### ISSUE TITLE
Tern binary not found

### ISSUE THREAD

**Issue by Troyciv** [syl20bnr/spacemacs#10006]
#### Description :octocat:
On startupe I get the following warning:

       Warnings:
           - tern binary not found!
    

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

Warning: tern binary not found

*Expected behaviour:* :heart: :smile:

Startup without any warnings

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.5 auto-completion-enable-help-tooltip nil auto-completion-enable-sort-by-usage t)
 csv emacs-lisp games git helm html javascript
 (latex :variables latex-enable-auto-fill t latex-enable-folding t)
 markdown
 (org :variables org-enable-reveal-js-support t)
 (python :variables python-test-runner 'nose python-enable-yapf-format-on-save t)
 rcirc ranger shell-scripts
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking themes-megapack twitter yaml)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by DVN196** [comment]
You should install tern either through npm or your distro package manager (in archlinux, it is nodejs-tern in AUR).

**Comment by danielhodson** [comment]
Additional information on resolving this warning message can be found in #7497.

**Comment by Troyciv** [comment]
thank you guys, solved

**Comment by jasonzhouu** [comment]
https://github.com/syl20bnr/spacemacs/issues/7497#issuecomment-305376657
