### ISSUE TITLE
Current point jumps back and forth until it finds (isearch) first `f` occurrence

### ISSUE THREAD

**Issue by velimir** [syl20bnr/spacemacs#10007]
#### Description :octocat:
Current point jumps back and forth until it finds first `f` occurrence.

#### Reproduction guide :beetle:
- Start Emacs
- Start `isearch-forward`: `C-s`
- Search for `f` character

*Observed behaviour:* :eyes: :broken_heart:
Current point jumps back and forth until it finds first `f` occurrence.

*Expected behaviour:* :heart: :smile:
Pointer jumps straight to the `f`.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by duianto** [comment]
Confirmed.
It happens in Emacs state, but not in Evil state.
On both the master and develop branches.
In Emacs 25.3.1 and 26.0.50.
But only when searching for the letter `f`, not with any other letter of the alphabet.

**Comment by Miciah** [comment]
Can you reproduce the problem if you add "evil-escape" to `dotspacemacs-excluded-packages`?

**Comment by velimir0xff** [comment]
@Miciah I do not use `spacemacs` anymore, though I do remember that exclusion of `evil-escape` package did resolve the issue.

**Comment by duianto** [comment]
@Miciah 's suggestion of excluding `evil-escape` does stop the cursor from jumping around.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c122eb6a0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm emacs-lisp git markdown neotree version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
