### ISSUE TITLE
Ivy's hydra menu matcher toggle doesn't show all possibilities

### ISSUE THREAD

**Issue by neojski** [syl20bnr/spacemacs#10008]
#### Description :octocat:
Ivy's hydra menu matcher toggle doesn't show all possibilities

#### Reproduction guide :beetle:
- Start Emacs
- <kbd>SPC f f</kbd>
- <kbd>C-o</kbd>
- <kbd>m</kbd> (press a couple of times)

*Observed behaviour:* :eyes: :broken_heart:
Impossible to select `regex-ignore-order` (the original value) after you pressed <kbd>m</kbd>. Outside of spacemacs it works.

*Expected behaviour:* :heart: :smile:
Pressing <kbd>m</kbd> twice returns to the original value `regex-ignore-order`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b4b7d63e4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript sml markdown ocaml auto-completion emacs-lisp neotree ivy)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by neojski** [comment]
I think I've found the reason:

https://github.com/syl20bnr/spacemacs/blob/4bb4cb46968e5bbb98fffd480c8c822269fced4f/layers/%2Bspacemacs/spacemacs-completion/packages.el#L173

vs

https://github.com/abo-abo/swiper/blob/ae438ff62fa3d9b98d899afc0e97c13be2148725/ivy-hydra.el#L68

**Comment by syl20bnr** [comment]
@neojski thank for the fix, merged in develop branch.
