### ISSUE TITLE
Smartparens mode should be configurable in Common Lisp layer

### ISSUE THREAD

**Issue by MatthewRock** [syl20bnr/spacemacs#10001]
Common Lisp layer has no way of selecting `smartparens-strict-mode` as a default one, or modifying it at all. It should at least provide option to choose smartparens on/off as a layer variable, or preferably choose any backend one wishes(e.g. paredit).

**Comment by MatthewRock** [comment]
Proposed fix in #9540

**Comment by CeleritasCelery** [comment]
Does globally enabling `smartparens-strict-mode` Not enable it in CL?

**Comment by MatthewRock** [comment]
I will check that when I get to my power supply, but there are two problems with this solution:

(1) As you can see in https://github.com/syl20bnr/spacemacs/pull/9540/commits/07319a368856144082b5fc98574ac9b62ab8c41c#diff-6c8e3545de06bc931eec4a2098202dfa , the layer turns off smartparens by default(and there's no easy way to override this behavior).

(2) Enabling globally `smartparens-strict-mode` might not be something user might want to do(e.g. me). This creates other problems like "Now I want to disable it for fundamental mode", which leads to workaround of workaround. The solution I propose allows one to set it only in CL layer, and sets base for other backends(e.g. paredit), if one wishes and if this gets implemented one day.

**Comment by CeleritasCelery** [comment]
From that line you point to, it looks like it only disables it in the slime REPEL, not the whole major mode.

**Comment by MatthewRock** [comment]
Yes, that was the point of the commit. The CL files use smartparens, the SLIME doesn't. I might have chosen the wording poorly.
