### ISSUE TITLE
pyenv-mode not showing all available python versions

### ISSUE THREAD

**Issue by martinffx** [syl20bnr/spacemacs#10005]
#### Description :octocat:
`pyenv-mode-set` does not show all available python versions

#### Reproduction guide :beetle:
- Start Emacs
- Open Python file
- `M-m v s`

*Observed behaviour:* :eyes: :broken_heart:
Do not see full list of available python versions when I run `pyenv versions`

```
  pyenv-mode-set
  system
  3.4.6
  3.5.3
  3.6.1
```

*Expected behaviour:* :heart: :smile:
To see full list of available python versions when I run `pyenv versions`

```
  $ pyenv versions
  system
  2.7.14
  3.6.1
  3.6.2
* 3.6.3
```

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(clojure helm auto-completion emacs-lisp git markdown org csv erlang scala typescript shell-scripts elm ruby nginx docker yaml elixir
         (javascript :variables tern-command
                     '("node" "/usr/bin/tern"))
         sql html rust scheme markdown
         (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save t)
         spell-checking syntax-checking emoji
         (erc :variables erc-server-list
              '(("irc.freenode.net" :port "6697" :ssl t :nick "martinffx" :password "mesut")
                ("travelstart.irc.slack.com" :nick "martin" :ssl t :password "travelstart.BowLGqdOFRNmixTwlgzT\n"))))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by CeleritasCelery** [comment]
You should report this upstream at pyenv-mode
