### ISSUE TITLE
Can't install Spacemacs with nested folder

### ISSUE THREAD

**Issue by gagbo** [syl20bnr/spacemacs#10015]
I tried doing a fresh install of Spacemacs on Windows 7 (with the latest [sourceforge built release](https://sourceforge.net/projects/emacsbinw64/files/release/)) nesting spacemacs in a subfolder of .emacs.d as stated in the [README](https://github.com/syl20bnr/spacemacs#modify-spacemacs-start-directory-variable).

When I launched emacs (with `--insecure --debug--init`) I had a lot of errors about missing packages ; and eventually a failed assertion about untar-ing the hydra package.

Since I don't have this problem when cloning Spacemacs directly in `.emacs.d`, I believe the issue is about finding correctly the `elpa` folder, since in both cases it was directly in `~/.emacs.d`, and the nested install probably looked for the packages in `~/.emacs.d/spacemacs/elpa`.

If anyone else has issues with nested Spacemacs install, the problem may come from here, but I don't know how to really fix it

**Comment by CeleritasCelery** [comment]
Are you talking about the instructions in the section titled “Modify spacemacs-start-directory variable”?

**Comment by gagbo** [comment]
Yes exactly.

In the end I installed vanilla emacs and started from scratch, but if it helps I can try to reproduce it to answer questions if you like.

**Comment by CeleritasCelery** [comment]
Out of curiosity, why did you want the install to be nested?

**Comment by gagbo** [comment]
I wanted to be able to keep separately a configuration that I wrote and all the things that come with Spacemacs,
I thought it'd be easier to actually learn how Emacs work and Elisp stuff starting with the "easy mode" (< Spacemacs) hidden in a folder as a crutch, and then grow my own config / plugin selection from this.

**Comment by CeleritasCelery** [comment]
Did you make the changes to your init file?

**Comment by gagbo** [comment]
I did the one specified in the README, nothing more since I could not get it running.

Then I thought "I should just learn elisp to actually understand what I'm doing" so I'm just using my init file now (I created the issue so someone finds this if they have the same issue)

**Comment by fiveNinePlusR** [comment]
Does emacs for windows actually expand the tilde as home path? I know there was a big issue trying to get spacemacs working for on my non *nix based box. 

Also, FWIW, you can definitely learn a decent amount of elisp while using the standard spacemacs setup. (though I do recommend using `~/.spacemacs.d/init.el` instead of the `~/.spacemacs` file as spacemacs handles some loadpath stuff for custom layers and you can easily version control your customizations. 

In any event you can get some help in the [gitter chat](https://github.com/syl20bnr/spacemacs#getting-help) if you want some help getting off the ground.

**Comment by gagbo** [comment]
I think the ~ expansion was correct because the elpa packages were actually loaded in `~/.emacs.d/elpa` (where ~ was expanded to `C:\Users\username\AppData\Roaming).

Maybe a few weeks down the road I'll be able to come back to it and understand what went wrong, for now I read the documentation about evil and started my own config from [there](https://github.com/gagbo/emacs-setup)

**Comment by gagbo** [comment]
Fair enough. I definitely forgot about this. Closing.
