### ISSUE TITLE
helm-notmuch should be used conditionally

### ISSUE THREAD

**Issue by rgrinberg** [syl20bnr/spacemacs#10012]
Using something like this:

```
    (helm-notmuch :toggle (configuration-layer/layer-usedp 'helm))
```
cc @FrancescElies

**Comment by FrancescElies** [comment]
That makes sense to me, would https://github.com/francescelies/spacemacs/commit/074faab7 work for you?

If it's fine, I'll open a pr

**Comment by rgrinberg** [comment]
Looks fine. I'm no expert though

**Comment by FrancescElies** [comment]
Thanks for having a lok, I'm no expert either, I'll open a pr when I get some free time and see what happens

**Comment by syl20bnr** [comment]
@FrancescElies thank you for the fix.

Ivy should now be available with notmuch on develop branch.
