### ISSUE TITLE
unattended update-packages?

### ISSUE THREAD

**Issue by dwang20151005** [syl20bnr/spacemacs#10010]
Would it be hard to make `configuration-layer/update-packages` run unattended?  At the moment, it requires user interaction, which means I must remember to run it manually instead of scripting it to run on a timer.

**Comment by syl20bnr** [comment]
That's an interesting feature. We could force an update based on a frequency like once a week or once a month etc.
Would require a restart a emacs to be triggered though.

**Comment by dwang20151005** [comment]
I would still like this, yes.
