### ISSUE TITLE
Move SLIME layer into Common Lisp layer

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1002]
I intend to move SLIME into Common Lisp layer, since SLIME is designed for Common Lisp in the first place and only [swank-chicken](https://github.com/nickg/swank-chicken) uses SLIME server and only Chicken Scheme is supported. For Scheme, I would prefer using [Geiser](http://www.nongnu.org/geiser/) instead.

@farmerpat what do you think?

**Comment by farmerpat** [comment]
@tuhdo That seems reasonable to me...as it stands now, the slime contrib is explicitly set up for lisp anyways.  Also, we might luck out and a package might be created for [cltl2.el](http://www.uuhaus.de/software/cltl2.el) or some other useful lisp tool, which could be added to the cl contrib.

**Comment by redline6561** [comment]
:+1: for Geiser. I don't know how it compares to racket-mode for Racket but as stated there aren't good SLIME backends for Scheme.
