### ISSUE TITLE
Layer information

### ISSUE THREAD

**Issue by cojua8** [syl20bnr/spacemacs#10021]
Hello,

I just installed spacemacs but the layer info (`SPC h l`) seems to be incomplete.
Also I have connection time out for org repository, is that related?

Last, I can't get auto-completion to work

**Comment by CeleritasCelery** [comment]
What do you mean by incomplete?

**Comment by cojua8** [comment]
It doesnt show any information, just the headers and the logo.
![captura de pantalla de 2017-12-26 11-03-28](https://user-images.githubusercontent.com/34746495/34358192-4e7fd8ae-ea2c-11e7-9cd1-f80411cccc9a.png)

**Comment by duianto** [comment]
It's an org file, that is folded, you can press `TAB` on a header to cycle between:
Folded, Children and Subtree

To cycle all headers, press `S-TAB` (hold down `Shift` and press `TAB`):
Overview, Contents and Show All

**Comment by cojua8** [comment]
whoops, I thought I already did that. Thank you
