### ISSUE TITLE
about dotspacemacs-themes '(default)

### ISSUE THREAD

**Issue by u0024window** [syl20bnr/spacemacs#10026]
![image](https://user-images.githubusercontent.com/15700823/34317955-506e263a-e7f6-11e7-9372-253f1bf689f9.png)
setting default theme ,it will install every time when spacemacs start up

**Comment by u0024window** [comment]
![image](https://user-images.githubusercontent.com/15700823/34317971-c259a670-e7f6-11e7-9532-38f9e97a6538.png)

**Comment by paralin** [comment]
The default is named spacemacs-dark not "default".

**Comment by paralin** [comment]
Try `SPC f e D` to see a diff of your dotfile and the default.

**Comment by nixmaniack** [comment]
Default emacs theme is named as "default".
Default Spacemacs theme is named as "spacemacs-dark"

If you add `default` to `dotspacemacs-themes` it tries to download the theme named `default`. Support for using "default emacs" theme [was added in develop](https://github.com/syl20bnr/spacemacs/commit/c3d344cb8c30fb7c2e9a304df3e10ca60a2b7be6) but currently isn't present in master branch. 

You can switch to `develop` branch if that's possible or use some other theme apart from `default` and let us know if it helps.
