### ISSUE TITLE
Give the people evil mini-buffer

### ISSUE THREAD

**Issue by quicknir** [syl20bnr/spacemacs#10030]
I discovered recently that getting evil working in the minibuffer (at least reasonably well) is not actually that difficult. Looking at the source here: https://github.com/jojojames/evil-collection/blob/master/evil-collection-minibuffer.el I was able to use evil perfectly from e.g. `SPC c C` adding < 40 lines of code to my .spacemacs. This seems to work perfectly in ivy as well! In helm there's a bizarre cursor duplication that's still being worked on: https://github.com/jojojames/evil-collection/issues/63

Once this looks reasonable for helm, we should definitely look at merging this in. This would be a huge QoL upgrade for evil users; even if only relatively basic operations are supported, being able to do `yy` from `SPC c C` for example is huge. Only question is where exactly this should be merged in; by adding the code directly into the spacemacs evil core, or by having a layer wrapping evil-collection.

**Comment by kirillsalykin** [comment]
too bad that it is not gonna happen
