### ISSUE TITLE
executable-find: Symbol’s function definition is void: \,

### ISSUE THREAD

**Issue by idoo** [syl20bnr/spacemacs#10032]
Looks like some problem in  current `develop` branch
'spacemacs/helm-project-smart-do-search-region-or-symbol

**Comment by duianto** [comment]
I'm not sure what modifier key `H` is? But this:
```
(global-set-key (kbd "<f8>") 'spacemacs/helm-project-smart-do-search-region-or-symbol)
```
works for me on the latest develop branch.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 857f6304)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 emacs-lisp git haskell helm html markdown org treemacs spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by idoo** [comment]
@duianto did you update packages?

**Comment by duianto** [comment]
I had updated the packages.

`   dotspacemacs-search-tools '("rg" "ag" "pt" "ack" "grep")` is the default value in `spacemacs.template` on the develop branch.
https://github.com/syl20bnr/spacemacs/blob/857f6304c7f4d2c614e0b455e8d9fae7a8208da3/core/templates/.spacemacs.template#L301

What did you change it to, that solved the void issue?

**Comment by idoo** [comment]
@duianto yep, looks it's my bad
