### ISSUE TITLE
Error getting PACKAGE-DESC when installing ocaml layer

### ISSUE THREAD

**Issue by Lokeh** [syl20bnr/spacemacs#10036]
#### Description :octocat:
When using the OCaml layer, I receive the following error on startup:

```
Parsing tar file...done
Error getting PACKAGE-DESC: (wrong-type-argument arrayp nil)
(Spacemacs) Error: 
An error occurred while installing merlin (error: (wrong-type-argument package-desc nil))
```

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
OCaml/Reason mode is not working at all

*Expected behaviour:* :heart: :smile:
When opening a .ml or .re file, I should see syntax highlighting/autocomplete/etc.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 857f6304)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git javascript clojure reason themes-megapack shell)
```
Note: the `reason` layer depends on the `ocaml` layer and is found here: https://github.com/fredyr/reason
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by nixmaniack** [comment]
Have you checked https://github.com/syl20bnr/spacemacs/issues/8901? If that doesn't help - it would be more helpful to report it upstream as `reason` isn't part of spacemacs (yet).

**Comment by Lokeh** [comment]
I have tried clearing my cache, and so far hasn't helped. This seems to be a problem with the `merlin` package which is required by the `ocaml` layer; you can see that from the log line I posted.

Even deleting the `reason` layer from my config and replacing it with `ocaml` shows the same error.

**Comment by nixmaniack** [comment]
`merlin` can be installed directly from melpa without issues. The external `reason` layer (also) tries to install older version of `merlin` directly from the repo. The [comments](https://github.com/syl20bnr/spacemacs/issues/8901#issuecomment-340371744) on the issue #8901 tell us that there's some issue with quelpa recipe being used by Spacemacs and unless that's updated this issue won't be solved. 

Could you just try using vanilla `ocaml` layer from Spacemacs and see if the issue still persists?
