### ISSUE TITLE
Zerodark: theme broken if placed in dotspacemacs-themes

### ISSUE THREAD

**Issue by paralin** [syl20bnr/spacemacs#10037]
#### Description :octocat:

I use the theme provided by the package `zerodark-theme`.

I can load it just fine using `customize-themes` and am pretty happy with it there but Spacemacs seems intent on overwriting my settings.

Spacemacs doesn't want to load it properly.

#### Reproduction guide :beetle:

- Start Emacs
- Change dotfile: `dotspacemacs-themes '(zerodark)`
- Restart emacs

*Observed behaviour:* :eyes: :broken_heart:

Despite the zerodark-theme package already being installed, Spacemacs tries to re-install it and fails. It then throws this error and reverts back to the default theme:

```
- An error occurred while applying the theme "zerodark", fallback on theme
  "spacemacs-dark". Error was: (file-error Cannot open load file No such file or
  directory all-the-icons)      
- Please check the value of "dotspacemacs-themes" in your dotfile or open an issue
  so we can add support for the theme "zerodark".      
```

*Expected behaviour:* :heart: :smile:

Either load the theme correctly or add an option to disable Spacemacs theme handling, I'd prefer to just use customize-themes anyway.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. bb2489b9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion search-engine
                 (c-c   :variables c-c  -enable-clang-support t)
                 csharp games yaml emacs-lisp javascript typescript html git ivy markdown
                 (org :variables org-enable-github-support t org-enable-reveal-js-support t org-projectile-file "ProjectTODOs.org")
                 python
                 (typescript :variables typescript-fmt-on-save t)
                 systemd spell-checking syntax-checking version-control
                 (go :variables go-tab-width 4)
                 (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/bin/bash" shell-default-height 30 shell-default-position 'top)
                 spotify docker)
```
- System configuration features: XPM JPEG GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB GTK3 X11

**Comment by paralin** [comment]
Note that with no additional package installations I can click on "zerodark" in the customize-themes list and it loads the theme just fine.

**Comment by DVN196** [comment]
Tried putting `all-the-icons` in `dotspacemacs-additional-packages`?

**Comment by paralin** [comment]
@DVN196 I have `zerodark-theme` in the additional packages list, which pulls in `all-the-icons` with it. I tried adding all-the-icons but it didn't change anything about the thrown error.

**Comment by nixmaniack** [comment]
I can't reproduce this on develop branch. By any chance do you have corrupted package? Maybe delete the `zerodark-theme` and `all-the-icons` packages (on develop it's ` ~/.emacs.d/*/*/<package-name>-*`, on master it'd different)  and try again.

**Comment by paralin** [comment]
I tried this and am not seeing any particular errors any more, but the
theme doesn't look quite right. If I open up "customize-themes" zerodark
is checked, but checking another theme and then re-checking zerodark
again makes it look correct (different).

Basically each time I start Spacemacs I have to go to customize-theme
and re-select it.

**Comment by nixmaniack** [comment]
> but the theme doesn't look quite right

Could you elaborate perhaps with screenshots? 

Having zerodark as your first theme in `dotspacemacs-themes` should initialize everything correctly unless you have stale entries from other themes in your dotspacemacs file or custom settings file which could potentially interfere with other themes.

**Comment by paralin** [comment]
I'll close this one for now - will re-open if I see the error again. Not seeing it after a fresh install.

**Comment by a-berg** [comment]
I can confirm this exact same issue happens to me with darktooth theme and also with solarized-theme. In the last one it happens when you try to select a theme variant, e.g.:
```elisp
dotspacemacs-themes '(solarized-dark) ; no problem
dotspacemacs-themes '(solarized-gruvbox-dark) ; error as described by OP.
```

**Comment by nixmaniack** [comment]
@a-berg `master` branch may not have support for this theme. Support for additional solarized palettes is added in the `develop` branch.

**Comment by duianto** [comment]
The `develop` branch is the recommended branch until the next version is released.

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```
