### ISSUE TITLE
counsle-gtags command doesn't work in c-c++ layer

### ISSUE THREAD

**Issue by zhongke** [syl20bnr/spacemacs#10031]
#### Description :octocat:
counsle-gtags command doesn't work in c-c++ layer

#### Reproduction guide :beetle:
- Start Emacs
- Open a *.cc file
- , g g -> direct a new file
- , g p -> come back to previous file < not working>

*Observed behaviour:* :eyes: :broken_heart:
```
command-execute: Wrong type argument: commandp, counsel-gtags-previous-history
command-execute: Wrong type argument: commandp, counsel-gtags-next-history
```

*Expected behaviour:* :heart: :smile:
The gtags should work in diffrent directtion, next or previous.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 857f6304)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(javascript
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual auto-completion-enable-sort-by-usage t)
 osx python plantuml gtags ivy better-defaults emacs-lisp git treemacs org syntax-checking version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
command-execute: Wrong type argument: commandp, counsel-gtags-previous-history
command-execute: Wrong type argument: commandp, counsel-gtags-next-history
```

**Comment by zhongke** [comment]
Is there anyone have some idea? It still exist in develop branch.

**Comment by xiaocj** [comment]
you can modify the file "layers/+tags/gtags/funcs.el", change
`    "gn" 'counsel-gtags-next-history
    "gp" 'counsel-gtags-previous-history
`
to
`    "gn" 'counsel-gtags-go-forward
    "gp" 'counsel-gtags-go-backward
`

**Comment by zhongke** [comment]
It works!  Thank you very much! Is it possible to fix this issue in the branch?

**Comment by sdwolfz** [comment]
@zhongke sure, please open a PR with your changes and I'll take a look to merge it.

**Comment by zhongke** [comment]
Fixed in develop branch.
