### ISSUE TITLE
Python method names truncated when running python-test-one

### ISSUE THREAD

**Issue by revmischa** [syl20bnr/spacemacs#10042]
#### Description :octocat:
Running one python test uses a truncated method name

#### Reproduction guide :beetle:
- Start Emacs
- create python test case with a long method name like test_foo_bar_baz_blah_hello_testo
- run `SPC m t t` for `'python-test-one`

*Observed behaviour:* :eyes: :broken_heart:
`ERROR: not found: FooTest:: test_foo_bar_baz_bla`

*Expected behaviour:* :heart: :smile:
Do what it's doing except use the whole name of the test method

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(html javascript
      (python :variables python-test-runner 'pytest)
      helm auto-completion better-defaults emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking version-control mish)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by revmischa** [comment]
<img width="1680" alt="screen shot 2017-12-28 at 21 24 14" src="https://user-images.githubusercontent.com/245131/34413377-ac5d58bc-ec15-11e7-8016-2236bfe6d726.png">

**Comment by fleimgruber** [comment]
This seems like default upstream https://github.com/ionrock/pytest-el behaviour.  Specifically, the regexp in `pytest-inner-testable` works backward from point.  If your point would be at the end of the test function, i.e. `test_worker_heartbeat<point>(self)` then this should work.
