### ISSUE TITLE
Symbol’s value as variable is void: anaconda-mode-view-mode-map

### ISSUE THREAD

**Issue by miraclemore** [syl20bnr/spacemacs#10047]
#### Description :octocat:
Symbol’s value as variable is void: anaconda-mode-view-mode-map

#### Reproduction guide :beetle:
- Start Emacs
- Open the first python file

*Observed behaviour:* :eyes: :broken_heart:
Error (use-package): anaconda-mode/:config: Symbol’s value as variable is void: anaconda-mode-view-mode-map

*Expected behaviour:* :heart: :smile:
No error

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b4d663d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion
      (better-defaults :variables better-defaults-move-to-beginning-of-code-first t)
      (treemacs :variables treemacs-use-filewatch-mode t treemacs-use-collapsed-directories 3)
      ibuffer emacs-lisp git markdown org asm c-c++ gtags python imenu-list spell-checking syntax-checking miraclemore)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Voleking** [comment]
Same Issue here. It seems like [anaconda-mode](https://github.com/proofit404/anaconda-mode) has removed the variable `anaconda-mode-view-mode-map`.
This [line](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/python/packages.el#L62) use this variable.

**Comment by nixmaniack** [comment]
Yes, It [looks like](https://github.com/proofit404/anaconda-mode/commit/e72e9beeb8c80acfee4d85748464d1c5147946ad) all variables `anaconda-mode-view-*` are renamed to `anaconda-view-*`. We need to update Spacemacs code.

**Comment by syl20bnr** [comment]
@nixmaniack Thank you!

Should be fix in develop branch.
Will hotfix master during the WE.

**Comment by NightMachinary** [comment]
@syl20bnr The issue has returned?
Error (use-package): anaconda-mode :config: Symbol’s value as variable is void: anaconda-view-mode-map

**Comment by nixmaniack** [comment]
@NightMachinary I'm not sure why you're hitting this issue but I don't see any code change in `anaconda-mode` related to this. Even the [latest master](https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L790) has same name as defined/used by spacemacs. 

You should re-try after purging `anaconda-mode` packages and `*.elc` files.

**Comment by edliaw** [comment]
@nixmaniack it doesn't seem to be using master, but 0.1.9 https://github.com/proofit404/anaconda-mode/blob/v0.1.9/anaconda-mode.el

**Comment by liujoey** [comment]
When uses spacelpa, the anaconda package was an old version released in 2017.
   dotspacemacs-use-spacelpa t

So what I'm doing now for reinstall all package is:
set dotspacemacs-use-spacelpa to nil, such that I can install all packages' latest version, but this will complain about can't find org-contrib-plus and other org related packages.
Then I have to set dotspacemacs-use-spacelpa to t such that I can install org related packages from spacelpa.

**Comment by nixmaniack** [comment]
@edliaw Thanks for pointing that out. From what I understand, develop would use latest packages so this issue shouldn't arise in `develop` branch.

@liujoey I don't seem to have a nicer solution than what you have.

**Comment by zhenlei** [comment]
Face the same problem again, fix it by removing dot file .spacemacs and regenerating it.

**Comment by xqliu** [comment]
This issue happens again on Emacs 26.1, develop branch spacemacs and latest anaconda-mode (anaconda-mode-20180606.2217), seems all those anaconda-view-mode-map related definitions has been deleted recently.

**Comment by syl20bnr** [comment]
Oh dear.... they just disappear or have they been renamed ?

**Comment by syl20bnr** [comment]
Outch: https://github.com/proofit404/anaconda-mode/commit/0a9f518291f4b2c52213ffb8de5648ca4612d4b6

**Comment by syl20bnr** [comment]
@xqliu can you create a new issue about this ? thank you.\

**Comment by zhenlei** [comment]
it's been removed in anaconda by [https://github.com/proofit404/anaconda-mode/commit/0a9f518291f4b2c52213ffb8de5648ca4612d4b6](url)

**Comment by zhenlei** [comment]
[https://github.com/proofit404/anaconda-mode/commit/0a9f518291f4b2c52213ffb8de5648ca4612d4b6](profit404)
