### ISSUE TITLE
Can't escape from isearch-mode normally as vim

### ISSUE THREAD

**Issue by dsdshcym** [syl20bnr/spacemacs#1004]
When I use "/" and "?" in spacemacs, if I hit `ESC` to escape, I will jump to the first occurrence of the search result.

But in vim, I will jump back to where I am before the searching.

**Comment by dsdshcym** [comment]
Made a pr #1006 for this issue.

(And sorry for the repeat. It's my second time to make pull request.)

**Comment by TheBB** [comment]
Fixed by you, I suppose.
