### ISSUE TITLE
links in spacemacs configuration layers are down

### ISSUE THREAD

**Issue by casouri** [syl20bnr/spacemacs#10046]
All three links in distributions are down.

http://spacemacs.org/layers/LAYERS.html#distributions

And I don't think there is a boot-strap bistro.

**Comment by KngZhi** [comment]
Is this why I can't configure the default layers?    `dotspacemacs-configuration-layers` ?

**Comment by duianto** [comment]
They have been fixed on the develop branch:
http://develop.spacemacs.org/layers/LAYERS.html#distributions
They will probably be fixed on the master branch, when the next major Spacemacs version is released (I have no insight into when that is).

**Comment by casouri** [comment]
Sorry I forgot to close this.
