### ISSUE TITLE
Magit Holy Keybindings are Inconsistent

### ISSUE THREAD

**Issue by BigBeautifulBro** [syl20bnr/spacemacs#10054]
#### Description :octocat:

Using holy keybindings, the keybindings are different between magit-status and the magit-dispatch-popup.

For example, pressing the key "O" will do magit-reset-popup when in the magit-dispatch-popup. However, pressing the key "O" will do magit-subtree-popup when in the magit-status.

I fixed this issue locally by including evil-magit in the dotspacemacs-excluded-packages.

#### Reproduction guide :beetle:

- Start Emacs

- Use Holy Mode keybindings
- Run magit-status in a project under git control
- Press "O". Note that this starts magit-subtree-popup.
- Press "C-g" to exit back to magit-status.
- Press "?" to open magit-dispatch-popup.
- Press "O". Note that this starts magit-reset-popup.

*Observed behaviour:* :eyes: :broken_heart:

Pressing "O" did two different things depending upon whether or not you are in magit-status or magit-dispatch-popup. Likely other keys have this issue as well.

*Expected behaviour:* :heart: :smile:

Pressing "O" and other keys should do the same things when in magit-status or magit-dispatch-popup.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(csv windows-scripts javascript sql autohotkey helm
     (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior nil :disabled-for org erc)
     (better-defaults :variables better-defaults-move-to-beginning-of-code-first t better-defaults-move-to-end-of-code-first t)
     emacs-lisp git markdown org syntax-checking erc rust themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by syl20bnr** [comment]
duplicate of https://github.com/syl20bnr/spacemacs/issues/10078 or is it the other way around ? :-)

Fixed in develop.
