### ISSUE TITLE
Disable line highlighting?

### ISSUE THREAD

**Issue by 9mm** [syl20bnr/spacemacs#10064]
From everything I've read I supposedly just set...

    (global-hl-line-mode nil)

But in evil mode it keeps showing the line highlight that follows the cursor

**Comment by sdwolf** [comment]
Put the following line in your `dotspacemacs/user-config`:
```emacs-lisp
(spacemacs/toggle-highlight-current-line-globally-off)
```

**Comment by duianto** [comment]
The `SPC h d f global-hl-line-mode` doc-string states that:
>... enable Global Hl-Line mode if ARG is
positive, and disable it otherwise.  If called from Lisp, enable
the mode if ARG is omitted or nil.

It seems strange that, it gets enabled with `nil`.

`(global-hl-line-mode -1)` disables it.

**Comment by 9mm** [comment]
@duianto thank you, that worked!
