### ISSUE TITLE
`helm-projectile-find-file` cannot find some files

### ISSUE THREAD

**Issue by liamzh** [syl20bnr/spacemacs#10066]
My problem is that `helm-projectile-find-file` cannot find some files, and after visiting missing file(s) manually I get `File xxx added to project yyy cache`.

Using `projectile-invalidate-cache` can only clean invalid files but not add missing files.

What I need is like Sublime, you can *literally* get every file in search.

Is there something wrong with my configuration?

**Comment by CeleritasCelery** [comment]
`projectile-invalidate-cache` will remove the entire cache. Then when you try and open a file in the cache it should rebuild it.

**Comment by liamzh** [comment]
@CeleritasCelery So is there any ways to automatically cache everything? It doesn't feel right if I'm not familiar with some new projects.

**Comment by CeleritasCelery** [comment]
It does cache everything (unless it is ignored) when you open a new project. The only files it won’t have are ones that are add after the cache is built.
