### ISSUE TITLE
How to change parenthesis color?

### ISSUE THREAD

**Issue by 9mm** [syl20bnr/spacemacs#10069]
I realize the `highlight-parenthesis` plugin changes the color of the parent parens, but the actual color of the paren when you're highlighting over it in normal mode is some other color and I can't find where that's defined.

**Comment by sdwolf** [comment]
I have the following in my `dotspacemacs/user-config` maybe it's what you need:

```emacs-lisp
(set-face-attribute 'show-paren-match nil :background "#FF0000")
(set-face-attribute 'show-paren-match nil :foreground "#1D1F21")
(set-face-attribute 'show-paren-match nil :underline  t        )
```

**Comment by 9mm** [comment]
Nice!

**Comment by 9mm** [comment]
thanks :D
