### ISSUE TITLE
use package-archives without configuration-layer--elpa-archives when update packages

### ISSUE THREAD

**Issue by lsytj0413** [syl20bnr/spacemacs#10060]
#### Description :octocat:
use package-archives without configuration-layer--elpa-archives when update packages

#### Reproduction guide :beetle:
- Start Emacs
- Click update packages button

*Observed behaviour:* :eyes: :broken_heart:
fresh package from package-archives

*Expected behaviour:* :heart: :smile:
fresh package from configuration-layer--elpa-archives

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.50.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 020eee4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((ivy :variables ivy-extra-directories nil)
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for org)
 (better-defaults :variables better-defaults-move-to-end-of-code-first t)
 emacs-lisp git markdown org
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (python :variables python-sort-imports-on-save t)
 semantic
 (go :variables go-tab-width 4 go-use-gometalinter t)
 protobuf ranger gtags ibuffer sql
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 900)
 graphviz plantuml docker
 (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
 liter ycmd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
```

**Comment by iromise** [comment]
As you are using develop branch, you use the `configuration-layer-elpa-archives` instead of  `configuration-layer--elpa-archives`.

**Comment by lsytj0413** [comment]
see #10268 , closed.
