### ISSUE TITLE
What happened to the Forth layer?

### ISSUE THREAD

**Issue by AresAndy** [syl20bnr/spacemacs#10074]
And why is it no longer available? What should I do if I want to program in Forth?

**Comment by nixmaniack** [comment]
It's available in the `develop` branch. Check [here](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/forth). It's not merged in `master` yet.

**Comment by AresAndy** [comment]
Can I switch to the ```develop``` branch only for that layer? Sorry if I ask here, but searching for documentation online for Spacemacs can be quite daunting at times

**Comment by nixmaniack** [comment]
There isn't any inbuilt mechanism that I know of. You can copy that directory and keep it in your private layers directory(default `~/.emacs.d/private`) and then add it to your `dotspacemacs-configuration-layers`.

**Comment by AresAndy** [comment]
That has done it. I can see why it is not part of the stable branch, is a little blunt but it will do
Thanks
