### ISSUE TITLE
terminal spacemacs does not let TAB auto-complete shell commands (ansi/multi-term)

### ISSUE THREAD

**Issue by jpstone** [syl20bnr/spacemacs#10073]
#### Description :octocat:

Using spacemacs in iTerm/Terminal.app, TAB does not auto-complete shell commands when in ansi/multi-term while in INSERT mode. If I enter normal mode, it completes fine. When in insert mode, it brings up helm Hmm.

This behavior does not exist for spacemacs GUI.

I think the behavior should be the same for terminal spacemacs as it is for the GUI.

#### Reproduction guide :beetle:
- Start Emacs in a terminal
- Open ansi/multi-term
- Try to auto-complete shell commmands while in insert mode

*Observed behaviour:* :eyes: :broken_heart:

Instead of auto-completing, it brings up a helm menu.

*Expected behaviour:* :heart: :smile:

Auto-completion!

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7fa68a4)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml csv haskell elixir
      (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t =enable-flyspell-auto-completion= t)
      (erc :variables erc-server-list
           '(("irc.freenode.net" :port "6697" :ssl t :nick "jpstone")))
      (shell :variables shell-default-position 'full)
      (markdown :variables markdown-live-preview-engine 'vmd)
      (c-c++ :variables c-c++-enable-clang-support t)
      (auto-completion :variables auto-completion-tab-key-behavior nil auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip nil auto-completion-enable-snippets-in-popup nil)
      html helm better-defaults emacs-lisp git markdown org syntax-checking version-control themes-megapack gnus fasd react jpstone-eslintd jpstone-projectile jpstone-themes)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by htc502** [comment]
up for the same needs. 😄

**Comment by crimsonalucard** [comment]
It's valid man tab completion does not work for me in ansi-term

**Comment by apmarshall** [comment]
Have we verified if this is a spacemacs configuration issue or something inherent to the difference between terminal’s and GUIs?

**Comment by lebensterben** [comment]
This is **not** a bug of emacs or spacemacs.

I'm using emacs 27.1 and spacemacs develop branch.
Tab completion is working for
- Both zsh and bash
- In xterm, gnome-terminal, and alacritty
- In ansi-term, and vterm

Check your own setup.
