### ISSUE TITLE
In Holy mode, Magit's help popup shows Evil-mode keybinding

### ISSUE THREAD

**Issue by rymndhng** [syl20bnr/spacemacs#10078]
#### Description :octocat:
In Holy mode, Magit's help popup shows Evil-mode keybinding

This is confusing for newbies trying to use Spacemacs with Magit because the wrong key is pressed to discard a change.

#### Reproduction guide :beetle:
- Start Emacs
- Open Magit-Status
- Press `?` to popup magit help

*Observed behaviour:* :eyes: :broken_heart:
In the help screen, I see `x Discard`

*Expected behaviour:* :heart: :smile:
I expect to see `k  Discard`

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.3
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(typescript nginx auto-completion better-defaults clojure csv docker elm helm emacs-lisp git github
            (haskell :variables haskell-completion-backend 'intero)
            html javascript markdown php python
            (org :variables org-enable-github-support t)
            osx plantuml ruby ruby-on-rails
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            shell-scripts sql syntax-checking
            (version-control :variables version-control-diff-tool 'diff-hl)
            yaml)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by nixmaniack** [comment]
This is indeed inconsistent. Maybe we should disable `evil-magit` when `holy` is the editing style.

But I'm not sure what would be the expected behaviour of `C-z` which toggles the editing style between `emacs` and `vim` or `hybrid`. If we want to keep the keybindings consistent across editing styles then in that case excluding `evil-magit` doesn't sound like an option. 

Related issue: https://github.com/syl20bnr/spacemacs/issues/10054

**Comment by rymndhng** [comment]
I like your suggestion about disabling `evil-magit` for users using holy mode at startup and I think this sounds feasible if assumption holds:

Users who set `dotspacemacs-editing-style` to `holy-mode` probably don't use evil-mode.

I'm in this camp and I would like to think that most other folks that use holy-mode do so as well.

---

Another option would be to add a layer config value to  disable the `evil-magit` package.

**Comment by nixmaniack** [comment]
> Another option would be to add a layer config value to disable the evil-magit package.

You can exclude a particular package by adding it to `dotspacemacs-excluded-packages` in your `~/.spacemacs` file.

**Comment by nixmaniack** [comment]
@rymndhng @BigBeautifulBro Can you test https://github.com/syl20bnr/spacemacs/pull/10090?

**Comment by syl20bnr** [comment]
Thx @nixmaniack , should be fixed in develop.
