### ISSUE TITLE
New frame has first line obscured by frame title

### ISSUE THREAD

**Issue by goughjt** [syl20bnr/spacemacs#10089]
#### Description :octocat:
(make-frame) - New frame has first line obscured by frame title

#### Reproduction guide :beetle:
- Start Emacs
- Do the `make-frame` command (`SPC F n` or `SPC w F`)

*Observed behaviour:* :eyes: :broken_heart:
- New frame opens with first line at the top of the file hidden behind the frame title

*Expected behaviour:* :heart: :smile:
- New frame opens with first line visible

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b3ddc962)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go yaml sql typescript csv php python osx helm html javascript auto-completion better-defaults emacs-lisp git docker markdown org
    (shell :variables shell-default-height 30 shell-default-position 'bottom)
    syntax-checking elixir shell-scripts)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
I am not sure what to put here

**Comment by goughjt** [comment]
A friend of mine who also uses a Mac laptop does NOT experience this issue so it is a problem with my system. I am hoping somebody else has experienced this and found a fix.

**Comment by duianto** [comment]
Could post a screenshot?

The first line is visible for me, when the cursor is on the first line, of for example `.spacemacs`, and a new frame is opened `SPC F n`.

![emacs_2018-01-08_18-38-30](https://user-images.githubusercontent.com/13420573/34683759-4b54b39e-f4a3-11e7-88a8-03f6bb1853ec.png)

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f8ecf0cb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 emacs-lisp git haskell helm html markdown org treemacs spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by goughjt** [comment]
@duianto I am attaching a screenshot to illustrate the issue
<img width="1439" alt="spacemacs_new_frame_bug" src="https://user-images.githubusercontent.com/6205186/34717576-7fc7efbe-f52b-11e7-8e30-e9e0af783eb3.png">

**Comment by duianto** [comment]
The first line is hidden behind what looks like tabs, which are shown below the frame title.

Is the first line visible if you only have one tab open (that is if the tabbar disappears when there only is one)?

Is it a terminal application that's handling the tabs? You might want to check that applications issue tracker (if there is one).

**Comment by goughjt** [comment]
@duianto Yes, the first line is visible if I have only one tab open.

I am not aware of an application that is handling the tabs, I thought it was spacemacs default setting. I will look more into it, see where the tabs are coming from. Thanks for helping out.
