### ISSUE TITLE
Change rcirc key-bindings

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#1008]
The `rcirc` layer currently uses `C-k` and `C-j` to scroll between prev/next input from history. It's also one of the modes that start out in `emacs-state` by default. This results in us overwriting one of the most used Emacs bindings, `C-k` for `kill-line`, which is useful for deleting messages that we changed our mind about while typing. 

I suggest changing these to `M-k` and `M-j` to avoid this conflict. I'll create a pull-request here but figured I should file an issue as well just for the record.

**Comment by syl20bnr** [comment]
I see. `C-k` `C-j` should be associated to `insert state` only.
The default state should be `normal` in vim style and `emacs` in emacs style.

**Comment by StreakyCobra** [comment]
This issue has been solved long ago by the PR #1009, and it's already in `master`, so closing it.
