### ISSUE TITLE
C-C++ Layer: not respecting c-basic-offset setting

### ISSUE THREAD

**Issue by aurabindo** [syl20bnr/spacemacs#10080]
#### Description :octocat:
C-C++ Layer: not respecting c-basic-offset setting. My spacemacs config contains:

```
(defun dotspacemacs/user-config ()
  "Configuration for user code:
This function is called at the very end of Spacemacs startup, after layer
configuration.
Put your configuration code here, except for variables that should be set
before packages are loaded."
  (setq-default
   c-default-style "bsd"
   c-basic-offset 4)
  )
```

#### Reproduction guide :beetle:
- Start Emacs
- Open a C source file and start a new line.

*Observed behaviour:* :eyes: :broken_heart:

Offset defaults to default value of 2 in C-C++ mode

*Expected behaviour:* :heart: :smile:

offset must be set to the value specified in user-config()

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3b24f45)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript sql helm c-c++ rust gtags shell auto-completion emacs-lisp git markdown neotree org spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by aurabindo** [comment]
Just saw #10051 
So I'll close this.

**Comment by aurabindo** [comment]
Reopening since the suggested fix in #10051 did not fix my problem. Did the way to change the default C style change in C-C++ layer ?

**Comment by syl20bnr** [comment]
So this is not working as intended ?

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/c-c++/README.org#enable-google-set-c-style

**Comment by syl20bnr** [comment]
The above layer variable should be `nil` by default.

**Comment by aurabindo** [comment]
@syl20bnr  I enable clang-format as mentioned in the Readme, and I also have the following in `dotspacemacs/user-config`
```
  (setq-default
   c-default-style "bsd"
   c-basic-offset 4)
  )
``` 

I am not enabling google style explicitly. But my above setting is not being respected as `SPC j =` formats my C code with indentation of 2 rather than 4. What do I need to tweak to get this fixed ?

**Comment by myme** [comment]
I bisected this down to 16fd3e85a4e0941c365722d28cbe81eef02a1305, which landed in develop sometime in December. It seem like the `when` checks in `c-c++/init-google-c-style` doesn't respect the layer variables correctly:

```elisp
(defun c-c++/init-google-c-style ()
  (use-package google-c-style
    :if (or 'c-c++-enable-google-style 'c-c++-enable-google-newline)
    :config (progn
    (when 'c-c++-enable-google-style (add-hook 'c-mode-common-hook 'google-set-c-style))
    (when 'c-c++-enable-google-newline (add-hook 'c-mode-common-hook 'google-make-newline-indent)))))
```

So:

`(when 'c-c++-enable-google-style (print "FOO"))`

prints "FOO", while:

`(when c-c++-enable-google-style (print "FOO"))`

does not and returns `nil`. The variables are supposed to be evaluated and not quoted, I suppose?

**Comment by myme** [comment]
To add to that:

```
c-mode-common-hook is a variable defined in ‘cc-vars.el’.
Its value is
(google-make-newline-indent google-set-c-style spacemacs//init-company-c-mode-common company-mode)

Original value was nil

  This variable may be risky if used as a file-local variable.
```

It's clear that the functions have been added to the `c-mode-common-hook` while `c-c++-enable-google-style` and `c-c++-enable-google-newline` are set to `nil`.

**Comment by syl20bnr** [comment]
@myme thank you for the fix, should be fixed in develop.

**Comment by lovrolu** [comment]
Confirmed, this fixes the issue for me.

**Comment by sunlin7** [comment]
I use these slice of code to modify the `c-basic-indent` without exclude the google-c-style,
(eval-after-load 'google-c-style
```elisp
(eval-after-load 'google-c-style
    (dolist (v google-c-style)
      (when (and (listp v) (eq (car v) 'c-basic-offset)) 
        (setcdr v 4))))
```

**Comment by c02y** [comment]
Tried https://github.com/syl20bnr/spacemacs/issues/10051#issuecomment-605979333 ?
