### ISSUE TITLE
Persp-mode issue

### ISSUE THREAD

**Issue by duytrung** [syl20bnr/spacemacs#10081]
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.10
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

I have this message:
Error (use-package): persp-mode/:catch: Required feature ‘persp-mode’ was not provided

Is this a bug or just a message?

Thanks 

TN

**Comment by CeleritasCelery** [comment]
If you can still use layouts and workspaces then it is not a problem.

**Comment by syl20bnr** [comment]
Do you have repro steps ?

**Comment by duytrung** [comment]
I've just opened spacemacs and it showed that message.

**Comment by dchen23** [comment]
same problem. On windows

**Comment by divusmetaphysica** [comment]
Hi, I have 

emacs version:25.2 for windows

Yesterday I cleanly cloned spacemacs into `.emacs.d`, but used my customized `.spacemacs` config 
(just a few layers and some env settings).

Then open spacemacs via `runemacs.exe` and let it run packages and updates. Near the end it stops on the persp-mode error: 

`Error (use-package): persp-mode/:catch: Required feature ‘persp-mode’ was not provided`

**Comment by CeleritasCelery** [comment]
@divusmetaphysica did you update your packages?

**Comment by divusmetaphysica** [comment]
@CeleritasCelery I updated before and didn't face this. I got a new account on this computer so I snatched my older emacs and .spacemacs and got latest spacemacs from 'hub. This error happened on new startup.

I tried to update packages after this issue on both 25.2.1 and 25.3.1, but no luck.

**Comment by CeleritasCelery** [comment]
Delete `persp-mode` from your elpa for then restart.

**Comment by divusmetaphysica** [comment]
@CeleritasCelery Great! I removed the elpa/persp-mode-<version>/ and restarted spacemacs. Then the spacemacs re-installed the package and not error occurred. Thank you.

Fix confirmed.
