### ISSUE TITLE
Which-key-delay affects all actions done within which-key, when it (arguably) shouldn't.

### ISSUE THREAD

**Issue by oisincar** [syl20bnr/spacemacs#10091]
#### Description :octocat:
Which-key delay (dotspacemacs-which-key-delay, as set in the dotfile) applies both to the initial trigger of which-key, as well as subsequent keypresses to open folders in which-key.

#### Reproduction guide :beetle:
- Start Emacs
- (Optional: Set dotspacemacs-which-key-delay to a higher value, say, 2 seconds)
- Press SPC, wait, which key triggers correctly after 2 seconds.
- Press another key (say, f)

*Observed behaviour:* :eyes: :broken_heart:
- Nothing happens for 2 more seconds, before which-key finally changes to 'files'.

*Expected behaviour:* :heart: :smile:
- Which-key responds instantally to subsequent keypresses once it has already opened, changing to the 'files' submenu.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3b24f45)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 csharp csv elixir elm emacs-lisp go
 (haskell :variables haskell-completion-backend 'intero)
 html java javascript latex lua markdown python shell-scripts yaml vimscript
 (shell :variables shell-default-shell 'eshell shell-default-height 40 shell-default-position 'bottom)
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'complete auto-completion-enable-sort-by-usage t :disabled-for org)
 colors git gtags ivy org osx
 (ranger :variables ranger-override-dired t)
 semantic)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by oisincar** [comment]
It feels akward if you have the delay set to anything higher than half a second, which I do. The fix is to simply set ```which-key-idle-secondary-delay``` to an (almost) zero value.

Still, I'm not sure if this behavior is intentional so I thought I'd open an issue here to discuss before submitting a pull request to change it. I felt which-key was just awkward and laggy for most of the time I've been using spacemacs, didn't realize it could be easily changed and made more responsive.

**Comment by syl20bnr** [comment]
WOW this feature is 2 years old, it completely passed under our radar even when which-key author himself was a collaborator on Spacemacs. This is a great feature, thank you for adding it :-)
