### ISSUE TITLE
Multiple cursors ?

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#101]
I wish we could integrate consistently [multiple cursors](https://github.com/magnars/multiple-cursors.el) from @magnars. 

I don't need it so often with the tools available in Spacemacs and the macros but sometimes it would be extremely useful and no doubt that if we could have it in our tool belt we could find a lot of cool use cases for it.

The tricky part is to make it play well with  `evil`. There is a long opened issue on this topic [here](https://github.com/magnars/multiple-cursors.el/issues/17).

Are there any ST users here who can relate about their experience with multiple cursors ?

**Comment by CestDiego** [comment]
Will this actually work now with the spacemacs/ground-control? :)

**Comment by shaief** [comment]
any news regarding this issue? did someone was able to make multiple-cursors play nice with spacemacs?
Thanks!

**Comment by trishume** [comment]
A layer for this could totally happen now for use by holy-mode people.

**Comment by syl20bnr** [comment]
I will do some work on this, I might be able to do something interesting even for vim users.

**Comment by shaief** [comment]
Hi @syl20bnr, did you manage to make EVIL and multiple-cursors play nice together?

**Comment by syl20bnr** [comment]
Not for now, I tried a long time ago and it was not really usable. One known trick is to only use it in insert state but it is pretty limited. Or you learn some basic emacs key bindings and you switch to emacs state while in multiple cursor.

**Comment by shaief** [comment]
Thanks for answering!

**Comment by jimmythekid** [comment]
has there been any more work around a multi-cursor mode for evil users in spacemacs?

**Comment by snario** [comment]
+1 this is a deal breaker for many people

**Comment by rugginoso** [comment]
+1

**Comment by Devagamster** [comment]
Progress is being made here: https://github.com/syl20bnr/spacemacs/issues/2669

**Comment by rjhilgefort** [comment]
:+1:

**Comment by TheBB** [comment]
I'm closing this in favour of #2669.
