### ISSUE TITLE
How can I skip the package refresh at the beginning of each startup?

### ISSUE THREAD

**Issue by rococode** [syl20bnr/spacemacs#10107]
![](https://i.imgur.com/ajwSn5M.png)

I'm a new emacs/spacemacs user coming from vim, and this part of spacemacs in particular is driving me crazy and I'm hoping for some help! Every time I start emacs, there's like 10+ seconds worth of package refreshing. I just sit there waiting for it to refresh (and it seems some of the default themes in the mega theme pack are unavailable?). Is there any way to make this run async or just disable it and make it only run manually?

And this may be tangentially related, but I consistently get a timeout to the org repository:

![](https://i.imgur.com/OfsSvKg.png)

This is what I'm seeing in the `Messages` buffer. I'm running on Windows 10.

![](https://i.imgur.com/yJhihyp.png)

From my totally uninformed point of view it looks like the startup is constantly hanging up on connecting to various sites (yet I have a fast internet connection and seem to be able to load these without any issue in browser), so unless it's a different problem altogether I'm just trying to disable these connections.

**Comment by AlejandroCatalina** [comment]
Those particular messages are shown because the packages you indicated are not recognisable in melpa, so you should either indicate the private repo or just add them by ```(add-to-list 'load-path "path/to/package/) (require 'package)```.

**Comment by rococode** [comment]
I'm literally just using the `themes-megapack` that's kinda built in. I don't actually want those themes, I'm just using 1 out of the tons of themes there. Should I just install that theme manually?

**Comment by AlejandroCatalina** [comment]
Seeing your edition it may also have to do with the SSL connection. You may try to set ```   dotspacemacs-elpa-https nil``` in your config file.

**Comment by duianto** [comment]
The themes have been removed from the `themes-megapack` layer on the develop branch. They will most likely be removed on the master branch, when the next major version of Spacemacs is released (I have no insight into when that is).

The current solution on the master branch is to exclude the missing themes, by adding them to the `dotspacemacs-excluded-packages` variable:
```
dotspacemacs-excluded-packages '(firebelly-theme
                                 niflheim-theme
                                 pastels-on-dark-theme
                                 tronesque-theme
                                 zonokai-theme)
```
in your `.spacemacs` file, which you can open by pressing `SPC f e d`

**Comment by jpventura** [comment]
@pavloo check #9628

**Comment by komali2** [comment]
This would still be nice to actually disable, as for example I live in Taiwan and sometimes these connections can take minutes to resolve, or simply fail, and if they fail my entire emacs environment hangs until I `C-g`, in which case Spacemac's initialization is cancelled and things like evil-mode aren't working. Quite annoying.
