### ISSUE TITLE
Formatting JS and React

### ISSUE THREAD

**Issue by cinjon** [syl20bnr/spacemacs#10109]
How do I get spacemacs and the react layer to recognize and properly format when using .js files? It works fine with jsx but not js.

**Comment by cinjon** [comment]
Actually, on close and reopen emacs, it works.

**Comment by cinjon** [comment]
Actually, this isn't quite working. I'm having trouble debugging what's going on, but it seems that the majority of my normal js files do not recognize that they are in fact ReactJS. How do I fix this?

**Comment by cinjon** [comment]
Adding to this, I've found that if I include the line /** @jsx React.DOM */ at the top of the file, then everything seems to work as intended. However, this is deprecated in newer versions of React and so does not play nicely with hot reloads. With this new info, any ideas how to fix this?

**Comment by shishirsharma** [comment]
`/** @jsx React.DOM */ ` is deprecated, React mode works by auto-detecting `import react`. But render blocks are not properly indented.

```
return (
      <div>
      <MuiThemeProvider>
      <NavBar addNote={this.addNote} search={this.search} lockNotes={this.lockNotes} lock={this.state.lock} />
      </MuiThemeProvider>
      <div className="container-fluid content-wrapper">
      <div>
      <div className="notes">
      {cardColumns}
      </div>
      </div>
      </div>
      <HelpModal />
      <UnlockModal unlockNotes={this.unlockNotes} invalid_key={this.state.invalid_key}/>
      { settingsModal }
      </div>
    );
```

**Comment by cinjon** [comment]
Any update on this? I am still having this problem and it's really frustrating.

**Comment by d12frosted** [comment]
@cinjon sorry to hear that you have problems with formatting React code. 

To be honest, I don't write React code, so I can't help you with this fast. I'll try to find someone who can help here.

**Comment by cinjon** [comment]
Thanks @d12frosted ! That is much appreciated. Afaict, it's only happening with React :(.

**Comment by cinjon** [comment]
Any update?

**Comment by d12frosted** [comment]
@cinjon I've asked around and it seems that no one has picked this issue. :(
