### ISSUE TITLE
not: Symbol’s function definition is void: gtags-get-rootpath

### ISSUE THREAD

**Issue by kvaneesh** [syl20bnr/spacemacs#10105]
With the latest develop branch enabling rtags support and using c-c++-tags-find-symbol give the error
not: Symbol’s function definition is void: gtags-get-rootpath. I guess that function comes from gtags.el?

-aneesh

**Comment by syl20bnr** [comment]
Can you verify this is fixed with last develop ?

**Comment by kvaneesh** [comment]
Tested with 0d5f3cfe2fdbb91f5e1872e698e52550e3109d72 . I am not sure I am missing anything related to config. I looked at ggtags.el and helm-gtags. Both don't include gtags-get-rootpath. It is present in gtags.el supplied by global project. But it is not in melpa as a package and I don't see a (require 'gtags) anywhere in the code. If I add the require statement it works.

**Comment by sunlin7** [comment]
Same issue in my local. `gtags-get-rootpath` is in then gtags.el, but gtags.el is neither in elpa nor packed with spacemacs. So I add the location of gtags.el which bounding with the gnu-global installation to the `load-path` as a workaround.
```elisp
(add-to-list 'load-path "/usr/share/gtags/") ; gtags.el in this dir
```
