### ISSUE TITLE
Ivy buffers is slow

### ISSUE THREAD

**Issue by AlejandroCatalina** [syl20bnr/spacemacs#10101]
#### Description :octocat:
Since I installed the ivy layer I notice that the buffer list is a bit slow (```SPC b b```). 

#### Reproduction guide :beetle:
- Start Emacs
- SPC b b
- Filter some "py" buffers

*Observed behaviour:* :eyes: :broken_heart:
The response from emacs is a bit slow.

*Expected behaviour:* :heart: :smile:
Butter smooth behavior.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f8ecf0cb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults emacs-lisp git org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking latex bibtex python mc-column)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:

Thanks and share if this happens to you too or if it's an issue on my side.

PS: I don't have that many buffers open, about 20 or so.

**Comment by zzjjzzgggg** [comment]
Is it related to the recent change in #9543? Try a different version before commit 3467aa84.

**Comment by AlejandroCatalina** [comment]
It shouldn't be related, I noticed the slowness before the change. I will try tho.

**Comment by syl20bnr** [comment]
We should make `ivy-rich` a layer variable.

If you use macOS be sure to have Emacs compile with the vfork patch included in `emacs-plus`. It greatly improve process spawning performance which makes everything more snappy in Emacs (especially Magit). Maybe `ivy-rich` is concerned by this depending on how it fetched info on the buffers/files.

**Comment by syl20bnr** [comment]
Outch I tested it quickly on my Mac with vfork patch enabled... it is indeed really slow.

**Comment by syl20bnr** [comment]
I nobody make a PR I'll do it tomorrow evening.

**Comment by AlejandroCatalina** [comment]
I’ll try to address the PR today. Essentially making ivy-rich a variable (turned off by default).

**Comment by syl20bnr** [comment]
Fixed in develop, thank tou @AlejandroCatalina

**Comment by achikin** [comment]
But there is a `ivy-enable-advanced-buffer-information` variable, which enables ivy-rich?

**Comment by Yevgnen** [comment]
@syl20bnr 

Hi, 

I don't know that `ivy-rich` is on [spacemacs/develop](https://github.com/syl20bnr/spacemacs/tree/develop)!

Does `ivy-rich` still slow on macOS? `ivy-rich` does not spawn any process though. I'm using `macOS 10.13.4` and everything works fine.

The only performance issue may come from `projectile` or a slow `tramp` connection. It's known that there was some issue when getting project root in `projectile`. About the tramp connection, there are two variables `ivy-rich-parse-remote-buffer` and `ivy-rich-parse-remote-file-path` controls how remote buffers are processed, please refer to the docstring of them for more details.

Also note that, `ivy-rich` is now support displaying column [customization](https://github.com/Yevgnen/ivy-rich#1312-add-icons-for-ivy-switch-buffer), which means that you can remove columns that has 'performance issue' easily, if any. Or you can completely write your own transformers for `ivy-switch-buffer`, `counsel-describe-function`, etc.

**Comment by Hindol** [comment]
@Yevgnen I just tested. Scrolling with `Ctrl + n` and `Ctrl + p` is super-slow on Mac. Please let me know if you need more info to debug this.

**Comment by Hindol** [comment]
@Yevgnen Here you go! I forgot to mention, the slowness is only in `ivy-switch-buffer`, so that is what I did.

1. Start profiler.

**Comment by Yevgnen** [comment]
@Hindol 

> [projectile-file-exists-p 
"#<compiled 
0x417ce0b5>" 
cl--position 
cl-position 
apply 
cl-find 
apply 
cl-find-if 
"#<compiled 
0x417cf4e9>" 
projectile-locate-dominating-file 
projectile-root-top-down 
"#<compiled 
0x417cf419>" 
cl-some 
projectile-project-root 
projectile-project-p 
ivy-rich-switch-buffer-in-propject-p] 
2109 

A quick look it seems that `projectile` was spending much time locating project root as I mentioned in my first post. Maybe you could give a try to modify `projectile-project-root-files-functions` or refer to issues like [this](https://github.com/bbatsov/projectile/issues/1003) or upgrading to the latest version?

**Comment by Hindol** [comment]
@Yevgnen I keep open a bunch of files from different projects. I tried enabling [caching](https://github.com/bbatsov/projectile/blob/master/doc/configuration.md#caching) but it did not help.

Do you have sample configurations for `projectile-project-root-files-functions`?
