### ISSUE TITLE
popup window will cause new extra window created when there are 2 windows

### ISSUE THREAD

**Issue by dum3ng** [syl20bnr/spacemacs#10106]
Env: 
- emacs 25.3
- osx 10.13.1
- spacemacs 0.200.10

I have a layout which is 
```
        +         +
neotree | window1 | window2
        |         |
        |         |
        |         |
        |         |
        +         +

```
, and assume the window1 is a cider-repl buffer, then if an error occured in the repl, a `repl-error` popped up from below, and I expect it to be like:

```
        +                  +
neotree | window1          | window2
        |                  |
        |                  |
        +------------------+
        | repl-error       |
        +                  +

```
But the result is 
```
        +         + copy   +
neotree | window1 |  of    | window2
        |         | window2|
        |         |        |
        +---------+--------+
        | repl-error       |
        +                  +

```

and if I do not delete the newly created copy of window2, then when a new error occured, more window will be created.

This is very annoying. 
And same issue may appear when I use `SPACE h d v` to view help.

**Comment by CeleritasCelery** [comment]
I have encountered a similar issue with `pop-shell`

**Comment by jbmckeon** [comment]
I'm having the same issue and it's driving me nuts.  Closing the neotree window fixes the issue but this is not ideal.  Any workarounds other than closing neotree?

**Comment by anonimitoraf** [comment]
> I'm having the same issue and it's driving me nuts. Closing the neotree window fixes the issue but this is not ideal. Any workarounds other than closing neotree?

Thanks for that. Can confirm it's the same for me. Does this suggest that it's a bug in Neotree, then?
