### ISSUE TITLE
Spacemacs ignores helm-grep-ag-command

### ISSUE THREAD

**Issue by danielmt** [syl20bnr/spacemacs#10100]
I'm trying, as per issues and helm documentation, to set helm-grep-ag-command to ripgrep (rg).
Spacemacs ignores it, and if I uninstall ag, nothing works, it's a mess.

How do I make it work?
I've tried on user-init/user-config, setq/setq-default. SPC h d v picks it up, but, spacemacs simply uses the default for some reason.

(setq helm-grep-ag-command "rg --color=always --smart-case --no-heading --line-number %s %s %s") on user-config is what is supposed to work.

Help.$#@(*&ˆ$#

**Comment by duianto** [comment]
There's a `dotspacemacs-search-tools` variable in `.spacemacs`. At least on the develop branch, it's set to:
` '("rg" "ag" "pt" "ack" "grep")` by default. 

One thing to try, could be to remove `"ag"` from the list.
And you can check if Emacs is able to see `rg`, by evaulating: `(executable-find "rg")` from the `Eval:` prompt (`S-M-;`).

**Comment by danielmt** [comment]
Doesn't work.
Changing dotspacemacs-search-tools to rg yields: "Wrong type argument: commandp, helm-project-do-rg".
Uninstalling "ag" just breaks grepping for good, if you set it to "ag" and override the documented helm var to use "rg" instead. Spacemacs does its own thing and ignores the documented helm settings.

**Comment by duianto** [comment]
Are you on the master or develop branch?
There's an issue with that same `Wrong type argument: commandp, helm-project-do-rg` message on the master branch: helm-project-do-rg broken on master #8694
The answer by bmag states that `rg` isn't supported on master.

**Comment by danielmt** [comment]
The bottom line is: this is supported on helm. You can change helm-grep-ag-command to point to rg and it works, except on Spacemacs. Spacemacs does its own thing and ignores the setting somehow.

https://github.com/emacs-helm/helm/issues/1624

**Comment by duianto** [comment]
This might be the PR where ripgrep support was added to the develop branch.
`Add support for ripgrep, fixes #7370` #7490

**Comment by danielmt** [comment]
Thank you, I'll see what I can do on my end to use this on master.
