### ISSUE TITLE
Can't see macro contents in evil register with `evil-show-registers`

### ISSUE THREAD

**Issue by kbdluv** [syl20bnr/spacemacs#10116]
#### Description :octocat:
Can't see macro contents with evil-show-registers

#### Reproduction guide :beetle:
- Start Emacs
- Go to `*scratch*` buffer
- Type `q l i foobar <ESC> q`
- Type `@l`
- Type `"lp`
- Type `SPC r e`, or run `evil-show-registers`, or type `:registers` in normal mode

*Observed behaviour:* :eyes: :broken_heart:
Typing `@l` runs the macro stored in register `l`, inserting `foobar`, as expected.

Typing `"lp` pastes the macro contents from register `l` as expected (`ifooobar^[`).

But the last command to show registers lists `l` on the left, but nothing on the right, as if the `l` register were empty.

*Expected behaviour:* :heart: :smile:
Show `l` on the left, and `ifooobar^[` on the right.

(If you take the repro steps on Vim that's what happens.)

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.60
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b4d663dc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown javascript haskell html elm
          (typescript :variables typescript-fmt-on-save nil)
          helm
          (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-sort-by-usage t)
          emacs-lisp neotree org
          (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-term))
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by duianto** [comment]
Confirmed

It might be related to the `<ESC>` character: `^[`
Because if `<ESC>` is replaces with `fd` (quickly), then the evil-registers buffer shows:

| Register | Value     |
| -------- | --------- |
| l        | ifoobarfd |


#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3cb9fea0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 emacs-lisp git haskell helm html markdown org treemacs spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by kbdluv** [comment]
>if <ESC> is replaces with fd (quickly), then the evil-registers buffer shows `l | ifoobarfd`

You're right! This is what happens here too. And thanks for teaching me about `fd` :)

**Comment by duianto** [comment]
It's provided by the https://github.com/syl20bnr/evil-escape package, and the key binding can be customized. Here's the Spacemacs documentation for it: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#escaping

**Comment by syl20bnr** [comment]
Not sure to understand why `fd` would make the register empty with `SPC r e` 🤔

**Comment by kbdluv** [comment]
@syl20bnr `fd` doesn't, it's `<ESC>` that does. With `fd` the register contents show up just right.

It possibly has to do with `<ESC>` being a ASCII character of code 27 that gets represented as an indivisible `^[` in some places. Maybe it screws up the rendering somehow, I dunno.

**Comment by Miciah** [comment]
This is an upstream issue.  Does https://github.com/emacs-evil/evil/pull/1071 resolve it for you?

**Comment by duianto** [comment]
@Miciah 's solution fixes it. 👍 

Now the `*evil-registers*` buffer shows:
```
l          i f o o b a r <escape>
```

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c122eb6a0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm emacs-lisp git markdown neotree version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
This has now been fixed upstream.
