### ISSUE TITLE
Buffer rendering broken in terminal

### ISSUE THREAD

**Issue by jsoo1** [syl20bnr/spacemacs#10118]
#### Description :octocat:
Spaceline renders one row too high and breaks the rendering of the rest of the buffer in terminal.

#### Reproduction guide :beetle:
- *update* Open a tmux session.
- Start Emacs in tmux
- `SPC f e d` edit a file

*Observed behaviour:* :eyes: :broken_heart:
Weird buffer rendering and spaceline appears one row too high.

Note below that `;; cider-restart` is on only line 440.  Scrolling through the buffer updates lines.
![screenshot of weird rendering](https://files.gitter.im/syl20bnr/spacemacs/EDUQ/Screen-Shot-2018-01-10-at-12.17.08-PM.png)
*Expected behaviour:* :heart: :smile:
nice good usual rendering :smile:

* A little additional information 💡 
Using `(emacs-lisp :variables emacs-lisp-hide-namespace-prefix nil)` ~fixes~ helps with the issue.  The issue is worse in tmux.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3cb9fea0f)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((auto-completion
  (haskell :variables haskell-completion-backend 'dante))
 c-c++ clojure csv dash docker elm
 emacs-lisp
 emoji
 erlang evil-snipe fsharp
 (git :variables git-magit-status-fullscreen t)
 (gtags :variables gtags-enable-by-default t)
 html
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 idris ivy
 (java :variables java-backend 'ensime)
 (javascript :variables tern-command
             '("node" "/usr/local/bin/tern"))
 (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill t latex-enable-folding t)
 lua major-modes
 (markdown :variables markdown-live-preview-engine 'vmd)
 nginx
 (org :variables org-enable-reveal-js-support t org-enable-github-support t org-projectile-file "TODOs.org")
 osx python ranger react restclient ruby rust
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts
 (slack :variables slack-spacemacs-layout-name "@Slack" slack-spacemacs-layout-binding "s")
 (spell-checking :variables spell-checking-enable-by-default nil)
 spotify sql swift syntax-checking tmux treemacs twitter version-control vimscript vinegar windows-scripts yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by syl20bnr** [comment]
Thank you for the report, a couple of questions :-)

> Using (emacs-lisp :variables emacs-lisp-hide-namespace-prefix nil) fixes helps with the issue.

What does that mean exactly ? Does it fix it ? Was it working as intended before ?
Have you tried without the line numbers ? If you test with a vanilla `.spacemacs` files, does it happen ?

**Comment by jsoo1** [comment]
1. I think `(emacs-lisp :variables emacs-lisp-hide-namespace-prefix nil)` may have nothing to do with it.  Testing today with that layer configuration doesn't help.

2. It was working as intended until a recent rebase with develop.

3. I will try with a vanilla .spacemacs and report back.

**Comment by jsoo1** [comment]
May be my configuration.  Vanilla spacemacs works as expected.

**Comment by jsoo1** [comment]
Simply moving the old .emacs.d back seems to have fixed it.  Maybe some bytecode was stale?

**Comment by phairoh** [comment]
I am having this same issue. It appears to be related to a recent change (d9e5652ae79d43fcb0c03df8fbfe34da6e764ad6) that enabled Nameless by default. Disabling Nameless solves the problem.

**Comment by sdwolf** [comment]
Same problem here, Manjaro XFCE terminal.

```
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 80a10f79)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion helm org neotree react c-c++ elixir emacs-lisp erlang go groovy html java javascript markdown php python ruby rust shell-scripts sql vimscript windows-scripts yaml git
  (gtags :disabled-for elixir emacs-lisp java ruby)
  ansible docker)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 LIBSYSTEMD JSON LCMS2
```

Nameless is unusable inside a terminal.

**Comment by syl20bnr** [comment]
We reverted back the default value to `nil` so hiding namespaces is now an opt-in feature.

**Comment by syl20bnr** [comment]
We still need to address this bug, I guess that nameless should be disable in terminal but it gets tricky with emacs as a daemon.

Is this bug reported upstream ?

**Comment by jsoo1** [comment]
I started experiencing this again with Nameless disabled.

**Comment by jsoo1** [comment]
I notice it happens with `dotspacemacs-mode-line-theme '(spacemacs :separator arrow :separator-scale 1.5)` but using `dotspacemacs-mode-line-theme '(all-the-icons :separator arrow :separator-scale 1.5)` helps

**Comment by syl20bnr** [comment]
If you set the `:separator-scale` to 1, does it fix completely the issue ?

**Comment by jsoo1** [comment]
still happens with `:separator-scale 1.0`.

**Comment by jsoo1** [comment]
`dotspacemacs-excluded-packages '(nameless)` does help, though

**Comment by jsoo1** [comment]
I have been experiencing this again but only in particular modes, haskell and elisp in particular. I will do some debugging.

**Comment by jsoo1** [comment]
Disabling the minor mode segment in spaceline fixes the issue. Disabling any of my diminish-symbols customization does not help.

**Comment by jsoo1** [comment]
This issue seems to only effect emacsen in tmux.
