### ISSUE TITLE
Space-/ search issue when a file in sub direcotry opened

### ISSUE THREAD

**Issue by QiBaobin** [syl20bnr/spacemacs#10111]
#### Description :octocat:
Space-/ uses rg search then open found file, it fails because it use path related with the directory of current buffer instead of project directory.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file in a git repo, the file is in a sub directory.
- Use space-/ to toggle rg search, use enter to open selected file
- An empty buffer opened and saying it's a new file, you can use mkdir to create the new directory

*Observed behaviour:* :eyes: :broken_heart:
Use find-file command and I can see the path is not correct.

*Expected behaviour:* :heart: :smile:
The file can be opened successfully.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 020eee45)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(javascript
 (markdown :variables markdown-command "pandoc -t slidy -s")
 ivy auto-completion better-defaults emacs-lisp
 (git :variables magit-repository-directories
      '("~/code"))
 markdown
 (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 50 shell-default-position 'bottom)
 python kotlin ipython-notebook spell-checking syntax-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by nixmaniack** [comment]
This is fixed in recent develop branch with PR https://github.com/syl20bnr/spacemacs/pull/10070. You have stale `develop` branch. 
> Spacemacs branch: develop (rev. 020eee4)

Just update once and try again.

**Comment by QiBaobin** [comment]
Thanks @nixmaniack , updated and works now.
