### ISSUE TITLE
powerline of active buffer displays incorrectly

### ISSUE THREAD

**Issue by Nadrin** [syl20bnr/spacemacs#1012]
This one is weird I guess. No matter how I set powerline-scale in my `~/.spaceemacs` file, powerline separators on the bottom line still look terrible.

I'm using Emacs 24.4.1 on Debian Testing in KDE 4.
![spaceemacs-powerline](https://cloud.githubusercontent.com/assets/615654/6930303/3aae0362-d802-11e4-9a36-bf23289934a5.png)

**Comment by syl20bnr** [comment]
And when the upper window is selected ?

**Comment by Nadrin** [comment]
Just checked. It is indeed selected window's mode-line that displays incorrectly.

**Comment by syl20bnr** [comment]
Can you install the package `fonts-nanum` and restart Emacs ?

**Comment by Nadrin** [comment]
Installed but I'm not sure if that helped anything.

I noticed that the active window mode-line displays incorrectly only if I set font smaller than 13pt. For >= 13pt fonts both active and inactive window modelines are the same size. For fonts <13pt inactive window modeline scales correctly but active window modeline does not.

**Comment by syl20bnr** [comment]
Do you have customized variables generated by emacs at the end of your dotfile ? If yes, do you see anything which could alter the expected behavior ?

**Comment by Nadrin** [comment]
See my updated comment above.

**Comment by syl20bnr** [comment]
You may be able to directly tweak the variable `powerline-height` in your config function.

**Comment by syl20bnr** [comment]
Just in case: `SPC h d v powerline-height` to see the current value.

**Comment by Nadrin** [comment]
Hm... setting `powerline-height` doesn't seem to have any effect (I'm setting it in `dotspacemacs/config`) although when I read the value back via the above command then it indeed reports the value I previously set.

Anyway, the case seems to be that the powerline seems to render incorrectly whenever I set bitmap font for buffers (even if I use scalable font for mode-line). To reproduce this bug try setting either `Terminus` or `Classic Console` in `.spacemacs`.

**Comment by x-ji** [comment]
This is also happening for me. Setting `powerline-height` and `powerline-scale` didn't help. Strangely it only happens when the minor mode lighters are on. If I run `SPC t m m` then the issue is gone. However I won't be able to see the lighters either.

The problem existed out of the box with fresh install... With font as Source Code Pro.

![screenshot 2015-04-27 23 22 04](https://cloud.githubusercontent.com/assets/2999209/7350871/6396bd4a-ed34-11e4-94b1-770c8eef2b4c.png)

@Nadrin did you manage to solve the problem in the end?

**Comment by x-ji** [comment]
Using the new `vim-powerline` package in `develop` seems to have fixed it.

**Comment by x-ji** [comment]
In my case I seem to finally be able to confirm that this was introduced by my using `light` version of `Source Code Pro` font instead of `regular` version. i.e. in

```
  dotspacemacs-default-font '("Source Code Pro"
                              :size 13
                              :weight regular
                              :width normal
                              :powerline-scale 1.1)
```

I was always using `:weight light` until recently. And once I changed it back to `:weight regular` the bar is normal again.

**Comment by louy2** [comment]
Met this problem after I used `(spacemacs//set-monospaced-font "Source Code Pro" "Noto Sans Mono CJK TC Regular" 14 14)`. It is observed that the lighters are displayed differently, and it is the change in the heights of the lighters that resulted in the change of powerline-height. Somewhere the fonts used by the lighters are changed.

It only happens on focus because lighters are not displayed in windows not focused.

**Comment by louy2** [comment]
OK, in my case it is because `(spacemacs//set-monospaced-font)` sets symbol font as the Chinese font, in this case to Noto Sans Mono, changing the height of the glyph. Deleting `symbol` it from the `(do-list)` solves the problem.

@zilongshanren Quickfix in the layer?

**Comment by zilongshanren** [comment]
@louy2 
Could you send a PR?
Thanks.

**Comment by louy2** [comment]
@zilongshanren Done. #3130

**Comment by AVHon** [comment]
I'm still having this problem.
![spacemacspowerlineheight](https://cloud.githubusercontent.com/assets/3957499/10687648/a2a27b3e-793c-11e5-8ede-b36c6ef13a27.png)
I have the default .spacemacs file and have installed the Source Code Pro font.
Fedora 22 amd64 with KDE5.

**Comment by TheBB** [comment]
It's a font setup issue. You need to either install a good unicode fallback font or disable unicode symbols in your modeline (set `dotspacemacs-mode-line-unicode-symbols` to `nil`).

**Comment by AVHon** [comment]
Disabling unicode does fix the powerline. However, I'd like to have unicode enabled.

By "install a fallback font", do you mean "install on my system" or "install on emacs"?

**Comment by TheBB** [comment]
Install it on your system or configure it so that Emacs can find it. I'm not 100% sure what it would entail, sorry.

**Comment by louy2** [comment]
Which font are the lightings displayed in by default?

**Comment by AVHon** [comment]
How do I find out?

**Comment by TheBB** [comment]
We don't set a font. If Source Code Pro doesn't have the glyph, a fallback will be chosen according to some arcane scheme known only to demigods.

**Comment by louy2** [comment]
Maybe it is better to set a default font, or this platform dependent problem will continue to come up.

**Comment by TheBB** [comment]
Okay, I opened. https://github.com/syl20bnr/spacemacs/issues/1012

**Comment by TheBB** [comment]
Okay, I opened https://github.com/TheBB/spaceline/issues/23

**Comment by lucasdellabella** [comment]
A friend and I are also both having this problem, he's had a fresh install of ubuntu 15.04 and I'm on the newest version of lubuntu.

**Comment by dilas** [comment]
On Debian 8.2 (jessie), i just installed the `unifont` package and everything its fine now (as @TheBB pointed - install a good unicode fallback). :grinning:

![image](https://cloud.githubusercontent.com/assets/86712/12188685/c79eaca2-b59e-11e5-9233-8815bce96a36.png)

**Comment by psamim** [comment]
I can confirm that I had the same issue on Archlinux and installed `ttf-unifont` from AUR and everything is fine now.

**Comment by ZaphyrVonGenevese** [comment]
Fedora 23: `sudo dnf install adobe-source-code-pro-fonts` fixed it.

**Comment by nujabse** [comment]
@psamim that worked for me too , on manjaro linux!  Finally solved it.

**Comment by scaryPonens** [comment]
Confirmed using docker and Ubuntu 16.04. [Docker-ized solution](https://gist.github.com/scaryPonens/ce790699ea4ca18708feb9d2c6c648b9)

**Comment by Honigmelone** [comment]
Hey I have this issue on a machine where I don't have administrative privileges. Therefore I cant just install a new font package. Is there some a way to fix this with the emacs configuration? Should I open a new issue?

**Comment by ZaphyrVonGenevese** [comment]
@Honigmelone Hi, I recently used this on Ubuntu:
https://www.leggiero.uk/post/installing-adobe-source-code-pro-fonts/

It does not need elevated privileges, so you should be good to go.

**Comment by tatsuhirosatou** [comment]
I followed [these steps](http://askubuntu.com/questions/193072/how-to-use-the-new-adobe-source-code-pro-font) on Ubuntu 16.04 to install the missing fonts and it fixed the issue with the powerline.

**Comment by codydiehl** [comment]
Note also on Ubuntu 16.04, not that it really matters. 
I installed Source Code Pro regular in my ~/.fonts dir
I was using the TTF font and the issue persisted,
once switching to OTF it worked as expected. 
Worth noting.

**Comment by alexryndin** [comment]
Sorry, but any of the solutions above didn't solved the issue for me on Ubuntu 18.04 with latest emacs. I use Patched Source Code Pro  --  NerdFonts
My font config is:
```
`   dotspacemacs-default-font '("Sauce Code Pro Nerd Font"
                               :size 13
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)

````
As it said above, it is well when font-size is set >13, or powerline-scale >1.3, but I would like to stay with defaults.

**Comment by p-himik** [comment]
@alexryndin I just fixed the issue by installing the latest set of SCP fonts (both variable and regular) and rebuilding the font cache. The spacemacs config is the default one.

**Comment by favianioel** [comment]
> Can you install the package `fonts-nanum` and restart Emacs ?

Ubuntu 18.04
I3wm 
this worked for me :top:

**Comment by jerome-diver** [comment]
not for me. I'm trying to use Inconsolata Nerd Font Complete Mono
It just failed and no clue.

**Comment by gussmith23** [comment]
`sudo apt install unifont` on Ubuntu 18.04 (Windows Subsystem for Linux) confirmed to work for me!

**Comment by msafarulla** [comment]
did you try M-x set set-face-font and change it for mode-line?
