### ISSUE TITLE
In markdown mode, "+" sometimes gets replaced with "|" on save

### ISSUE THREAD

**Issue by mgsloan** [syl20bnr/spacemacs#10129]
#### Description :octocat:

With the markdown layer, `+` sometimes gets turned into `|` on file save.  I
find this behavior to be bizarre and unexpected, particularly because it happens
within code blocks.

I realize this may be an upstream issue from spacemacs, but I'm not sure where
would be best to report it.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file ending in `.md`
- Insert the following into the buffer
```
-+-
 |
```
- Save the buffer.

*Observed behaviour:* :eyes: :broken_heart:

The saved file and buffer now instead have

```
-|-
 |
```

Somewhat humorously, a similar bug also occurred when I used `C-c C-c` to submit this report.  Except this time, all occurrences of `+` got replaced with space (` `).  Even the simple inline usages of + wrapped in backticks got replaced with spaces.  Bizarre!

*Expected behaviour:* :heart: :smile:

I'd expect that `+` remains a `+`, particularly when patterns like this are used
within code blocks. This could easily modify someone's code example to no longer
compile.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml helm git auto-completion syntax-checking chrome emacs-lisp graphviz haskell html javascript markdown python react rust)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND NOTIFY ZLIB TOOLKIT_SCROLL_BARS LUCID X11

#### Backtrace :paw_prints:
```
N/A
```

**Comment by mgsloan** [comment]
Duplicate of #8237 .  Sucks.  I've found that for the most part the md mode's automagic harms more than helps.  How can I disable it and only have highlighting?

**Comment by sdwolf** [comment]
Add this to your `dotspacemacs/user-config`:

```emacs-lisp
(with-eval-after-load 'markdown-mode
  (remove-hook 'markdown-mode-hook 'spacemacs//cleanup-org-tables-on-save))
```

**Comment by mgsloan** [comment]
@sdwolf Ah, thanks, much appreciated!!
