### ISSUE TITLE
void-variable evil-evilified-state-modes when starting

### ISSUE THREAD

**Issue by QiBaobin** [syl20bnr/spacemacs#10124]
#### Description :octocat:
void-variable evil-evilified-state-modes when starting

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Init failed, but it works when reset to commit 42adde95ec65d3c1c44fdabcd68dbb26d6934aa8

*Expected behaviour:* :heart: :smile:
Works as normal

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 34a0eb24)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(javascript
 (markdown :variables markdown-command "pandoc -t slidy -s")
 ivy auto-completion better-defaults
 (emacs-lisp :variables emacs-lisp-hide-namespace-prefix nil)
 (git :variables magit-repository-directories
      '("~/code"))
 markdown
 (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 50 shell-default-position 'bottom)
 python kotlin ipython-notebook spell-checking syntax-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-variable evil-evilified-state-modes)
  (memq major-mode evil-evilified-state-modes)
  (if (memq major-mode evil-evilified-state-modes) (evil-evilified-state) (funcall (intern (format "evil-%S-state" hybrid-mode-default-state))))
  (cond ((eq (quote hybrid) style) (if (memq major-mode evil-evilified-state-modes) (evil-evilified-state) (funcall (intern (format "evil-%S-state" hybrid-mode-default-state))))) ((and (eq (quote vim) style) (memq evil-state (quote (hybrid emacs)))) (cond ((memq major-mode evil-evilified-state-modes) (evil-evilified-state)) ((memq major-mode evil-motion-state-modes) (evil-motion-state)) (t (evil-normal-state)))))
  (save-current-buffer (set-buffer buffer) (cond ((eq (quote hybrid) style) (if (memq major-mode evil-evilified-state-modes) (evil-evilified-state) (funcall (intern (format "evil-%S-state" hybrid-mode-default-state))))) ((and (eq (quote vim) style) (memq evil-state (quote (hybrid emacs)))) (cond ((memq major-mode ev
```

**Comment by QiBaobin** [comment]
The issue happens on commit e9fb5285f412613cff7c003662d59b03cd9c082e and below is the whole trace:

Debugger entered--Lisp error: (void-variable evil-evilified-state-modes)
  (memq major-mode evil-evilified-state-modes)
  (if (memq major-mode evil-evilified-state-modes) (evil-evilified-state) (funcall (intern (format "evil-%S-state" hybrid-mode-default-state))))
  (cond ((eq (quote hybrid) style) (if (memq major-mode evil-evilified-state-modes) (evil-evilified-state) (funcall (intern (format "evil-%S-state" hybrid-mode-default-state))))) ((and (eq (quote vim) style) (memq evil-state (quote (hybrid emacs)))) (cond ((memq major-mode evil-evilified-state-modes) (evil-evilified-state)) ((memq major-mode evil-motion-state-modes) (evil-motion-state)) (t (evil-normal-state)))))
  (save-current-buffer (set-buffer buffer) (cond ((eq (quote hybrid) style) (if (memq major-mode evil-evilified-state-modes) (evil-evilified-state) (funcall (intern (format "evil-%S-state" hybrid-mode-default-state))))) ((and (eq (quote vim) style) (memq evil-state (quote (hybrid emacs)))) (cond ((memq major-mode evil-evilified-state-modes) (evil-evilified-state)) ((memq major-mode evil-motion-state-modes) (evil-motion-state)) (t (evil-normal-state))))))
  (while --dolist-tail-- (setq buffer (car --dolist-tail--)) (save-current-buffer (set-buffer buffer) (cond ((eq (quote hybrid) style) (if (memq major-mode evil-evilified-state-modes) (evil-evilified-state) (funcall (intern (format "evil-%S-state" hybrid-mode-default-state))))) ((and (eq (quote vim) style) (memq evil-state (quote (hybrid emacs)))) (cond ((memq major-mode evil-evilified-state-modes) (evil-evilified-state)) ((memq major-mode evil-motion-state-modes) (evil-motion-state)) (t (evil-normal-state)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- (buffer-list)) buffer) (while --dolist-tail-- (setq buffer (car --dolist-tail--)) (save-current-buffer (set-buffer buffer) (cond ((eq (quote hybrid) style) (if (memq major-mode evil-evilified-state-modes) (evil-evilified-state) (funcall (intern ...)))) ((and (eq (quote vim) style) (memq evil-state (quote ...))) (cond ((memq major-mode evil-evilified-state-modes) (evil-evilified-state)) ((memq major-mode evil-motion-state-modes) (evil-motion-state)) (t (evil-normal-state)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  hybrid-mode//update-states-for-current-buffers(hybrid)
  enable-hybrid-editing-style()
  (if hybrid-mode (enable-hybrid-editing-style) (disable-hybrid-editing-style))
  (let ((last-message (current-message))) (setq-default hybrid-mode (if (eq arg (quote toggle)) (not (default-value (quote hybrid-mode))) (> (prefix-numeric-value arg) 0))) (if hybrid-mode (enable-hybrid-editing-style) (disable-hybrid-editing-style)) (run-hooks (quote hybrid-mode-hook) (if (default-value (quote hybrid-mode)) (quote hybrid-mode-on-hook) (quote hybrid-mode-off-hook))) (if (called-interactively-p (quote any)) (progn (customize-mark-as-set (quote hybrid-mode)) (if (and (current-message) (not (equal last-message (current-message)))) nil (let ((local "")) (message "Hybrid mode %sabled%s" (if (default-value ...) "en" "dis") local))))))
  hybrid-mode()
  (progn (hybrid-mode))
  (if (eq (quote hybrid) dotspacemacs-editing-style) (progn (hybrid-mode)))
  (progn (if (eq (quote hybrid) dotspacemacs-editing-style) (progn (hybrid-mode))) (progn (setq spacemacs-toggles (cons (append (quote (hybrid-mode)) (quote (:function spacemacs/toggle-hybrid-mode :predicate spacemacs/toggle-hybrid-mode-status)) (quote (:status hybrid-mode :on (progn ... ...) :off (hybrid-mode -1) :documentation "Globally toggle hybrid mode." :evil-leader "tEh"))) spacemacs-toggles)) (defalias (quote spacemacs/toggle-hybrid-mode) (function (lambda nil "Toggle hybrid-mode on and off." (interactive) (if t (if (and ... ...) (message ... ... major-mode "") (if ... ... ... ...)) (message (concat "Toggle: %S\n" "This toggle is not supported.") (quote hybrid-mode)))))) (defalias (quote spacemacs/toggle-hybrid-mode-status) (function (lambda nil "Check if hybrid-mode is on." (and t (and (or ... ...) hybrid-mode))))) (defalias (quote spacemacs/toggle-hybrid-mode-on) (function (lambda nil "Toggle hybrid-mode on." (interactive) (if (spacemacs/toggle-hybrid-mode-status) nil (spacemacs/toggle-hybrid-mode))))) (defalias (quote spacemacs/toggle-hybrid-mode-off) (function (lambda nil "Toggle hybrid-mode off." (interactive) (if (spacemacs/toggle-hybrid-mode-status) (progn (spacemacs/toggle-hybrid-mode)))))) (let ((--dolist-tail-- (quote ("tEh"))) key) (while --dolist-tail-- (setq key (car --dolist-tail--)) (spacemacs/set-leader-keys key (quote spacemacs/toggle-hybrid-mode)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (let ((cell (assq (quote hybrid-mode) spacemacs--diminished-minor-modes))) (if cell (setcdr cell (quote (" Ⓔh" " Eh"))) (setq spacemacs--diminished-minor-modes (cons (quote (hybrid-mode " Ⓔh" " Eh")) spacemacs--diminished-minor-modes)))))
  (progn (progn (if (eq (quote hybrid) dotspacemacs-editing-style) (progn (hybrid-mode))) (progn (setq spacemacs-toggles (cons (append (quote (hybrid-mode)) (quote (:function spacemacs/toggle-hybrid-mode :predicate spacemacs/toggle-hybrid-mode-status)) (quote (:status hybrid-mode :on ... :off ... :documentation "Globally toggle hybrid mode." :evil-leader "tEh"))) spacemacs-toggles)) (defalias (quote spacemacs/toggle-hybrid-mode) (function (lambda nil "Toggle hybrid-mode on and off." (interactive) (if t (if ... ... ...) (message ... ...))))) (defalias (quote spacemacs/toggle-hybrid-mode-status) (function (lambda nil "Check if hybrid-mode is on." (and t (and ... hybrid-mode))))) (defalias (quote spacemacs/toggle-hybrid-mode-on) (function (lambda nil "Toggle hybrid-mode on." (interactive) (if (spacemacs/toggle-hybrid-mode-status) nil (spacemacs/toggle-hybrid-mode))))) (defalias (quote spacemacs/toggle-hybrid-mode-off) (function (lambda nil "Toggle hybrid-mode off." (interactive) (if (spacemacs/toggle-hybrid-mode-status) (progn ...))))) (let ((--dolist-tail-- (quote ("tEh"))) key) (while --dolist-tail-- (setq key (car --dolist-tail--)) (spacemacs/set-leader-keys key (quote spacemacs/toggle-hybrid-mode)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (let ((cell (assq (quote hybrid-mode) spacemacs--diminished-minor-modes))) (if cell (setcdr cell (quote (" Ⓔh" " Eh"))) (setq spacemacs--diminished-minor-modes (cons (quote (hybrid-mode " Ⓔh" " Eh")) spacemacs--diminished-minor-modes))))) (run-hooks (quote use-package--hybrid-mode--post-config-hook)))
  (if (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-config-hook)) (progn (progn (if (eq (quote hybrid) dotspacemacs-editing-style) (progn (hybrid-mode))) (progn (setq spacemacs-toggles (cons (append (quote ...) (quote ...) (quote ...)) spacemacs-toggles)) (defalias (quote spacemacs/toggle-hybrid-mode) (function (lambda nil "Toggle hybrid-mode on and off." (interactive) (if t ... ...)))) (defalias (quote spacemacs/toggle-hybrid-mode-status) (function (lambda nil "Check if hybrid-mode is on." (and t ...)))) (defalias (quote spacemacs/toggle-hybrid-mode-on) (function (lambda nil "Toggle hybrid-mode on." (interactive) (if ... nil ...)))) (defalias (quote spacemacs/toggle-hybrid-mode-off) (function (lambda nil "Toggle hybrid-mode off." (interactive) (if ... ...)))) (let ((--dolist-tail-- (quote ...)) key) (while --dolist-tail-- (setq key (car --dolist-tail--)) (spacemacs/set-leader-keys key (quote spacemacs/toggle-hybrid-mode)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (let ((cell (assq (quote hybrid-mode) spacemacs--diminished-minor-modes))) (if cell (setcdr cell (quote (" Ⓔh" " Eh"))) (setq spacemacs--diminished-minor-modes (cons (quote ...) spacemacs--diminished-minor-modes))))) (run-hooks (quote use-package--hybrid-mode--post-config-hook))))
  (when (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-config-hook)) (progn (if (eq (quote hybrid) dotspacemacs-editing-style) (progn (hybrid-mode))) (progn (setq spacemacs-toggles (cons (append (quote (hybrid-mode)) (quote (:function spacemacs/toggle-hybrid-mode :predicate spacemacs/toggle-hybrid-mode-status)) (quote (:status hybrid-mode :on ... :off ... :documentation "Globally toggle hybrid mode." :evil-leader "tEh"))) spacemacs-toggles)) (defalias (quote spacemacs/toggle-hybrid-mode) (function (lambda nil "Toggle hybrid-mode on and off." (interactive) (if t (if ... ... ...) (message ... ...))))) (defalias (quote spacemacs/toggle-hybrid-mode-status) (function (lambda nil "Check if hybrid-mode is on." (and t (and ... hybrid-mode))))) (defalias (quote spacemacs/toggle-hybrid-mode-on) (function (lambda nil "Toggle hybrid-mode on." (interactive) (if (spacemacs/toggle-hybrid-mode-status) nil (spacemacs/toggle-hybrid-mode))))) (defalias (quote spacemacs/toggle-hybrid-mode-off) (function (lambda nil "Toggle hybrid-mode off." (interactive) (if (spacemacs/toggle-hybrid-mode-status) (progn ...))))) (let ((--dolist-tail-- (quote ("tEh"))) key) (while --dolist-tail-- (setq key (car --dolist-tail--)) (spacemacs/set-leader-keys key (quote spacemacs/toggle-hybrid-mode)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (let ((cell (assq (quote hybrid-mode) spacemacs--diminished-minor-modes))) (if cell (setcdr cell (quote (" Ⓔh" " Eh"))) (setq spacemacs--diminished-minor-modes (cons (quote (hybrid-mode " Ⓔh" " Eh")) spacemacs--diminished-minor-modes))))) (run-hooks (quote use-package--hybrid-mode--post-config-hook)))
  (progn (when (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-config-hook)) (progn (if (eq (quote hybrid) dotspacemacs-editing-style) (progn (hybrid-mode))) (progn (setq spacemacs-toggles (cons (append (quote ...) (quote ...) (quote ...)) spacemacs-toggles)) (defalias (quote spacemacs/toggle-hybrid-mode) (function (lambda nil "Toggle hybrid-mode on and off." (interactive) (if t ... ...)))) (defalias (quote spacemacs/toggle-hybrid-mode-status) (function (lambda nil "Check if hybrid-mode is on." (and t ...)))) (defalias (quote spacemacs/toggle-hybrid-mode-on) (function (lambda nil "Toggle hybrid-mode on." (interactive) (if ... nil ...)))) (defalias (quote spacemacs/toggle-hybrid-mode-off) (function (lambda nil "Toggle hybrid-mode off." (interactive) (if ... ...)))) (let ((--dolist-tail-- (quote ...)) key) (while --dolist-tail-- (setq key (car --dolist-tail--)) (spacemacs/set-leader-keys key (quote spacemacs/toggle-hybrid-mode)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (let ((cell (assq (quote hybrid-mode) spacemacs--diminished-minor-modes))) (if cell (setcdr cell (quote (" Ⓔh" " Eh"))) (setq spacemacs--diminished-minor-modes (cons (quote ...) spacemacs--diminished-minor-modes))))) (run-hooks (quote use-package--hybrid-mode--post-config-hook))) t)
  (condition-case err (progn (when (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-config-hook)) (progn (if (eq (quote hybrid) dotspacemacs-editing-style) (progn (hybrid-mode))) (progn (setq spacemacs-toggles (cons (append ... ... ...) spacemacs-toggles)) (defalias (quote spacemacs/toggle-hybrid-mode) (function (lambda nil "Toggle hybrid-mode on and off." ... ...))) (defalias (quote spacemacs/toggle-hybrid-mode-status) (function (lambda nil "Check if hybrid-mode is on." ...))) (defalias (quote spacemacs/toggle-hybrid-mode-on) (function (lambda nil "Toggle hybrid-mode on." ... ...))) (defalias (quote spacemacs/toggle-hybrid-mode-off) (function (lambda nil "Toggle hybrid-mode off." ... ...))) (let ((--dolist-tail-- ...) key) (while --dolist-tail-- (setq key ...) (spacemacs/set-leader-keys key ...) (setq --dolist-tail-- ...)))) (let ((cell (assq ... spacemacs--diminished-minor-modes))) (if cell (setcdr cell (quote ...)) (setq spacemacs--diminished-minor-modes (cons ... spacemacs--diminished-minor-modes))))) (run-hooks (quote use-package--hybrid-mode--post-config-hook))) t) ((debug error) (funcall use-package--warning4 :config err)))
  (condition-case-unless-debug err (progn (when (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-config-hook)) (progn (if (eq (quote hybrid) dotspacemacs-editing-style) (progn (hybrid-mode))) (progn (setq spacemacs-toggles (cons (append ... ... ...) spacemacs-toggles)) (defalias (quote spacemacs/toggle-hybrid-mode) (function (lambda nil "Toggle hybrid-mode on and off." ... ...))) (defalias (quote spacemacs/toggle-hybrid-mode-status) (function (lambda nil "Check if hybrid-mode is on." ...))) (defalias (quote spacemacs/toggle-hybrid-mode-on) (function (lambda nil "Toggle hybrid-mode on." ... ...))) (defalias (quote spacemacs/toggle-hybrid-mode-off) (function (lambda nil "Toggle hybrid-mode off." ... ...))) (let ((--dolist-tail-- ...) key) (while --dolist-tail-- (setq key ...) (spacemacs/set-leader-keys key ...) (setq --dolist-tail-- ...)))) (let ((cell (assq ... spacemacs--diminished-minor-modes))) (if cell (setcdr cell (quote ...)) (setq spacemacs--diminished-minor-modes (cons ... spacemacs--diminished-minor-modes))))) (run-hooks (quote use-package--hybrid-mode--post-config-hook))) t) (error (funcall use-package--warning4 :config err)))
  (prog1 (condition-case-unless-debug err (progn (when (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-config-hook)) (progn (if (eq (quote hybrid) dotspacemacs-editing-style) (progn (hybrid-mode))) (progn (setq spacemacs-toggles (cons ... spacemacs-toggles)) (defalias (quote spacemacs/toggle-hybrid-mode) (function ...)) (defalias (quote spacemacs/toggle-hybrid-mode-status) (function ...)) (defalias (quote spacemacs/toggle-hybrid-mode-on) (function ...)) (defalias (quote spacemacs/toggle-hybrid-mode-off) (function ...)) (let (... key) (while --dolist-tail-- ... ... ...))) (let ((cell ...)) (if cell (setcdr cell ...) (setq spacemacs--diminished-minor-modes ...)))) (run-hooks (quote use-package--hybrid-mode--post-config-hook))) t) (error (funcall use-package--warning4 :config err))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package hybrid-mode" elapsed) (message "%s...done" "Configuring package hybrid-mode"))))
  (let ((now (current-time))) (message "%s..." "Configuring package hybrid-mode") (prog1 (condition-case-unless-debug err (progn (when (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-config-hook)) (progn (if (eq ... dotspacemacs-editing-style) (progn ...)) (progn (setq spacemacs-toggles ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (defalias ... ...) (let ... ...)) (let (...) (if cell ... ...))) (run-hooks (quote use-package--hybrid-mode--post-config-hook))) t) (error (funcall use-package--warning4 :config err))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package hybrid-mode" elapsed) (message "%s...done" "Configuring package hybrid-mode")))))
  (if (not (require (quote hybrid-mode) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote hybrid-mode)) :error) (let ((now (current-time))) (message "%s..." "Configuring package hybrid-mode") (prog1 (condition-case-unless-debug err (progn (when (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-config-hook)) (progn (if ... ...) (progn ... ... ... ... ... ...) (let ... ...)) (run-hooks (quote use-package--hybrid-mode--post-config-hook))) t) (error (funcall use-package--warning4 :config err))) (let ((elapsed (float-time (time-subtract ... now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package hybrid-mode" elapsed) (message "%s...done" "Configuring package hybrid-mode"))))))
  (prog1 (if (not (require (quote hybrid-mode) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote hybrid-mode)) :error) (let ((now (current-time))) (message "%s..." "Configuring package hybrid-mode") (prog1 (condition-case-unless-debug err (progn (when (run-hook-with-args-until-failure ...) (progn ... ... ...) (run-hooks ...)) t) (error (funcall use-package--warning4 :config err))) (let ((elapsed (float-time ...))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package hybrid-mode" elapsed) (message "%s...done" "Configuring package hybrid-mode")))))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package hybrid-mode" elapsed) (message "%s...done" "Loading package hybrid-mode"))))
  (let ((now (current-time))) (message "%s..." "Loading package hybrid-mode") (prog1 (if (not (require (quote hybrid-mode) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote hybrid-mode)) :error) (let ((now (current-time))) (message "%s..." "Configuring package hybrid-mode") (prog1 (condition-case-unless-debug err (progn (when ... ... ...) t) (error (funcall use-package--warning4 :config err))) (let ((elapsed ...)) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package hybrid-mode" elapsed) (message "%s...done" "Configuring package hybrid-mode")))))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package hybrid-mode" elapsed) (message "%s...done" "Loading package hybrid-mode")))))
  (progn (condition-case-unless-debug err (when (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-init-hook)) (run-hooks (quote use-package--hybrid-mode--post-init-hook))) (error (funcall use-package--warning4 :init err))) (let ((now (current-time))) (message "%s..." "Loading package hybrid-mode") (prog1 (if (not (require (quote hybrid-mode) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote hybrid-mode)) :error) (let ((now (current-time))) (message "%s..." "Configuring package hybrid-mode") (prog1 (condition-case-unless-debug err (progn ... t) (error ...)) (let (...) (if ... ... ...))))) (let ((elapsed (float-time (time-subtract ... now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package hybrid-mode" elapsed) (message "%s...done" "Loading package hybrid-mode"))))))
  (condition-case err (progn (condition-case-unless-debug err (when (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-init-hook)) (run-hooks (quote use-package--hybrid-mode--post-init-hook))) (error (funcall use-package--warning4 :init err))) (let ((now (current-time))) (message "%s..." "Loading package hybrid-mode") (prog1 (if (not (require (quote hybrid-mode) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote hybrid-mode)) :error) (let ((now ...)) (message "%s..." "Configuring package hybrid-mode") (prog1 (condition-case-unless-debug err ... ...) (let ... ...)))) (let ((elapsed (float-time ...))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package hybrid-mode" elapsed) (message "%s...done" "Loading package hybrid-mode")))))) ((debug error) (funcall use-package--warning4 :catch err)))
  (condition-case-unless-debug err (progn (condition-case-unless-debug err (when (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-init-hook)) (run-hooks (quote use-package--hybrid-mode--post-init-hook))) (error (funcall use-package--warning4 :init err))) (let ((now (current-time))) (message "%s..." "Loading package hybrid-mode") (prog1 (if (not (require (quote hybrid-mode) nil t)) (display-warning (quote use-package) (format "Cannot load %s" (quote hybrid-mode)) :error) (let ((now ...)) (message "%s..." "Configuring package hybrid-mode") (prog1 (condition-case-unless-debug err ... ...) (let ... ...)))) (let ((elapsed (float-time ...))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package hybrid-mode" elapsed) (message "%s...done" "Loading package hybrid-mode")))))) (error (funcall use-package--warning4 :catch err)))
  (progn (defvar use-package--warning4 (function (lambda (keyword err) (let ((msg (format "%s/%s: %s" ... keyword ...))) (display-warning (quote use-package) msg :error))))) (condition-case-unless-debug err (progn (condition-case-unless-debug err (when (run-hook-with-args-until-failure (quote use-package--hybrid-mode--pre-init-hook)) (run-hooks (quote use-package--hybrid-mode--post-init-hook))) (error (funcall use-package--warning4 :init err))) (let ((now (current-time))) (message "%s..." "Loading package hybrid-mode") (prog1 (if (not (require ... nil t)) (display-warning (quote use-package) (format "Cannot load %s" ...) :error) (let (...) (message "%s..." "Configuring package hybrid-mode") (prog1 ... ...))) (let ((elapsed ...)) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package hybrid-mode" elapsed) (message "%s...done" "Loading package hybrid-mode")))))) (error (funcall use-package--warning4 :catch err))))
  (use-package hybrid-mode :config (progn (if (eq (quote hybrid) dotspacemacs-editing-style) (progn (hybrid-mode))) (progn (setq spacemacs-toggles (cons (append (quote (hybrid-mode)) (quote (:function spacemacs/toggle-hybrid-mode :predicate spacemacs/toggle-hybrid-mode-status)) (quote (:status hybrid-mode :on ... :off ... :documentation "Globally toggle hybrid mode." :evil-leader "tEh"))) spacemacs-toggles)) (defalias (quote spacemacs/toggle-hybrid-mode) (function (lambda nil "Toggle hybrid-mode on and off." (interactive) (if t (if ... ... ...) (message ... ...))))) (defalias (quote spacemacs/toggle-hybrid-mode-status) (function (lambda nil "Check if hybrid-mode is on." (and t (and ... hybrid-mode))))) (defalias (quote spacemacs/toggle-hybrid-mode-on) (function (lambda nil "Toggle hybrid-mode on." (interactive) (if (spacemacs/toggle-hybrid-mode-status) nil (spacemacs/toggle-hybrid-mode))))) (defalias (quote spacemacs/toggle-hybrid-mode-off) (function (lambda nil "Toggle hybrid-mode off." (interactive) (if (spacemacs/toggle-hybrid-mode-status) (progn ...))))) (let ((--dolist-tail-- (quote ("tEh"))) key) (while --dolist-tail-- (setq key (car --dolist-tail--)) (spacemacs/set-leader-keys key (quote spacemacs/toggle-hybrid-mode)) (setq --dolist-tail-- (cdr --dolist-tail--))))) (let ((cell (assq (quote hybrid-mode) spacemacs--diminished-minor-modes))) (if cell (setcdr cell (quote (" Ⓔh" " Eh"))) (setq spacemacs--diminished-minor-modes (cons (quote (hybrid-mode " Ⓔh" " Eh")) spacemacs--diminished-minor-modes))))))
  spacemacs-base/init-hybrid-mode()
  funcall(spacemacs-base/init-hybrid-mode)
  (let* ((pkg-name (eieio-oref pkg (quote :name))) (owner (car (eieio-oref pkg (quote :owners))))) (spacemacs-buffer/message (format "%S -> init (%S)..." pkg-name owner)) (funcall (intern (format "%S/init-%S" owner pkg-name))) (mapc (function (lambda (layer) (if (configuration-layer/layer-used-p layer) (progn (if (not ...) (spacemacs-buffer/message ...) (spacemacs-buffer/message ...) (condition-case err ... ...)))))) (eieio-oref pkg (quote :post-layers))))
  configuration-layer//configure-package([eieio-class-tag--cfgl-package hybrid-mode nil (spacemacs-base) nil nil local t pre nil nil nil nil])
  mapc(configuration-layer//configure-package ([eieio-class-tag--cfgl-package hybrid-mode nil (spacemacs-base) nil nil local t pre nil nil nil nil] [eieio-class-tag--cfgl-package holy-mode nil (spacemacs-base) nil nil local t pre nil nil nil nil] [eieio-class-tag--cfgl-package exec-path-from-shell nil (spacemacs-base) nil nil elpa (or (spacemacs/system-is-mac) (spacemacs/system-is-linux) (eq window-system (quote x))) pre nil nil nil nil] [eieio-class-tag--cfgl-package evil-evilified-state nil (spacemacs-base) nil nil local t pre nil t nil nil]))
  (let (packages-to-configure) (let ((--dolist-tail-- packages) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg (quote :lazy-install)) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ...) (not ...)) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg ...)) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) ((not (configuration-layer//package-reqs-used-p pkg)) (spacemacs-buffer/message (format ... pkg-name))) ((not (cfgl-package-enabled-p pkg)) (spacemacs-buffer/message (format "%S is disabled." pkg-name))) (t (let (...) (if dir ...)) (if (memq ... ...) nil (configuration-layer//activate-package pkg-name)) (cond (... ...) (t ... ...))))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (mapc (quote configuration-layer//configure-package) packages-to-configure))
  configuration-layer//configure-packages-2((evil-evilified-state exec-path-from-shell holy-mode hybrid-mode))
  configuration-layer//configure-packages((abbrev ac-ispell ace-link ace-window adaptive-wrap add-node-modules-path aggressive-indent anaconda-mode ansi-colors archive-mode async auto-compile auto-complete auto-dictionary auto-highlight-symbol auto-yasnippet avy bind-key bind-map bookmark bracketed-paste centered-buffer-mode centered-cursor clean-aindent-mode coffee-mode column-enforce-mode comint company company-anaconda company-quickhelp company-statistics company-tern compile conf-mode counsel counsel-projectile cython-mode debug default-helm-config default-ivy-config default-org-config define-word desktop diminish dired dired-x doc-view dumb-jump edebug ediff ...))
  configuration-layer/load()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (require (quote core-spacemacs)) (configuration-layer/load-lock-file) (spacemacs/init) (configuration-layer/stable-elpa-download-tarball) (configuration-layer/load) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/Users/a483334/.emacs.d/init.el" nil t)  ; Reading at buffer position 1308
  load-with-code-conversion("/Users/a483334/.emacs.d/init.el" "/Users/a483334/.emacs.d/init.el" t t)
  load("/Users/a483334/.emacs.d/init" t t)
  #[0 "\205\266

**Comment by nixmaniack** [comment]
I can confirm that this is introduced by e9fb528. Also, it seems to be specific to `hybrid` style as I don't see any errors in `vim` and `emacs` styles. 

I have this.
```elisp
dotspacemacs-editing-style '(hybrid :variables
                                    hybrid-mode-enable-evilified-state t
                                    hybrid-mode-enable-hjkl-bindings nil
                                    hybrid-mode-use-evil-search-module nil
                                    hybrid-mode-default-state 'normal)
```

**Comment by syl20bnr** [comment]
@QiBaobin @lixinchin I fixed the regression in develop, can you test it ? Your PR may be not necessary.

**Comment by QiBaobin** [comment]
Debugger entered--Lisp error: (void-variable user-emacs-directory)
  (defvar spacemacs-start-directory user-emacs-directory "Spacemacs start directory.")

**Comment by QiBaobin** [comment]
Works now, thanks @syl20bnr , @lixinchin
