### ISSUE TITLE
run java code

### ISSUE THREAD

**Issue by teichholz** [syl20bnr/spacemacs#10120]
Is there a way to run java code inside Spacemacs? I installed the java layer but it doesn't seem to add any function for it, so im quite curious.

**Comment by willbush** [comment]
I'm not familiar with that layer, but usually programming language layers need external tools installed that they depend on and possibility additional configuration. From the [layer docs](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/java) it appears you need to choose a backend and set it up. Looks like the key bindings and what functions you have available depend on which backend you use. For example, `SPC m p r` will 'Run project' if you choose eclim and configure it.
