### ISSUE TITLE
notmuch help key is broken

### ISSUE THREAD

**Issue by jb55** [syl20bnr/spacemacs#10123]
When in the notmuch layer, the key `?` should launch a help buffer, but it is broken in evil mode for some reason. There is a potential work around described here:

https://github.com/syl20bnr/spacemacs/pull/9927#issuecomment-353710598

**Comment by yangsheng6810** [comment]
I just made the following workaround, seems to work:
```emacs-lisp
(defun notmuch-describe-key (actual-key binding prefix ua-keys tail)
  "Prepend cons cells describing prefix-arg ACTUAL-KEY and ACTUAL-KEY to TAIL

It does not prepend if ACTUAL-KEY is already listed in TAIL."
  (let ((key-string (concat prefix (key-description actual-key))))
    ;; We don't include documentation if the key-binding is
    ;; over-ridden. Note, over-riding a binding automatically hides the
    ;; prefixed version too.
    (unless (assoc key-string tail)
      (when (and ua-keys (symbolp binding)
		 (get binding 'notmuch-prefix-doc))
	;; Documentation for prefixed command
	(let ((ua-desc (key-description ua-keys)))
	  (push (cons (concat ua-desc " " prefix (format-kbd-macro actual-key))
		      (get binding 'notmuch-prefix-doc))
		tail)))
      ;; Documentation for command
      (push (cons key-string
		  (or (and (symbolp binding) (get binding 'notmuch-doc))
		      (and (functionp binding) (notmuch-documentation-first-line binding))))
	    tail)))
  tail)
```
The changes are:
1. replacing `format-kbd-macro` with `key-description`
2. only call `notmuch-documentation-first-line` if `binding` is a function. For me, the only cases that `binding` is not a function are
- aya-persist-snippet
- spacemacs/search-pt-grep-region-or-symbol
- spacemacs/search-pt-grep
- spacemacs/search-rg-grep-region-or-symbol
- spacemacs/search-rg-grep
- spacemacs/search-ack-grep-region-or-symbol
- spacemacs/search-ack-grep

**Comment by jb55** [comment]
seems to work. It shows a bunch of unrelated keybinds as well but at least it shows something. Can you PR this?

**Comment by yangsheng6810** [comment]
Sure. I will test it for a few days and PR if no more errors are found.

**Comment by yangsheng6810** [comment]
I have reported and sent the patch to upstream.

**Comment by yangsheng6810** [comment]
Fixed in upstream, but not available in melpa yet.

**Comment by jb55** [comment]
Should be fixed now
