### ISSUE TITLE
`SPC h l` eval-buffer: Symbol’s value as variable is void: c-c++-enable-rtags-support

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#10126]
#### Description :octocat:
`SPC h l`(`ivy-spacemacs-help-layers`) throws following error.

```
eval-buffer: Symbol’s value as variable is void: c-c++-enable-rtags-support
```

#### Reproduction guide :beetle:
- Start Emacs
- Type `SPC h l`

*Observed behaviour:* :eyes: :broken_heart:
Throws following error.
```
eval-buffer: Symbol’s value as variable is void: c-c++-enable-rtags-support
```

*Expected behaviour:* :heart: :smile:
Shows list of layers to access documentation.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 34a0eb24)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(sql csv javascript ivy auto-completion better-defaults
     (emacs-lisp :variables emacs-lisp-hide-namespace-prefix nil)
     git markdown osx finance org go
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
     syntax-checking
     (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left)
     yaml python ruby ruby-on-rails themes-megapack restclient docker ibuffer imenu-list)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-variable c-c++-enable-rtags-support)
  (if c-c++-enable-rtags-support (progn (configuration-layer/declare-layer 'gtags)))
  eval-buffer(#<buffer  *load*> nil "/Users/nixmaniack/.emacs.d/layers/+lang/c-c++/layers.el" nil t)  ; Reading at buffer position 362
  load-with-code-conversion("/Users/nixmaniack/.emacs.d/layers/+lang/c-c++/layers.el" "/Users/nixmaniack/.emacs.d/layers/+lang/c-c++/layers.el" nil nil)
  load("/Users/nixmaniack/.emacs.d/layers/+lang/c-c++/layers.el")
  (if (file-exists-p file) (load file))
  (let ((file (concat (eieio-oref obj ':dir) file))) (if (file-exists-p file) (load file)))
  (while --dolist-tail-- (setq file (car --dolist-tail--)) (let ((file (concat (eieio-oref obj ':dir) file))) (if (file-exists-p file) (load file))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- files) file) (while --dolist-tail-- (setq file (car --dolist-tail--)) (let ((file (concat (eieio-oref obj ':dir) file))) (if (file-exists-p file) (load
```

**Comment by nixmaniack** [comment]
It's because of recent commit dbf1deaa4cd713d617b72a6b43415eae8c28d2b8.

**Comment by vmfhrmfoaj** [comment]
you can temporary avoid it as follows.
`dotspacemacs/user-init` function in `.spacemacs` file:
```elisp
(setq c-c++-enable-rtags-support t) 
```

**Comment by sdwolf** [comment]
Can somebody please test out #10137 and check if their error goes away AND that the rtags functionality works as expected?

**Comment by dschrempf** [comment]
I want to confirm this issue and add that I got this error already when starting spacemacs. Setting c-c++-enable-rtags-support to t is a workaround! I do not use rtags so I cannot test the functionality. Cheers!

**Comment by nixmaniack** [comment]
Fixed in develop. Closing.
