### ISSUE TITLE
Linting problems with javascript layer

### ISSUE THREAD

**Issue by heyarne** [syl20bnr/spacemacs#10131]
#### Description :octocat:
I'm having problems with the javascript layer not properly finding my local `eslint` config. I've discussed the issue in greater detail [here](https://github.com/flycheck/flycheck/issues/1384#issuecomment-356920872), but what it boils down to is this:

- If `SPC e v` shows me that `javascript-eslint` is enabled for `flycheck`, the `js2-mode` checker is used still. Linter output of `eslint .` in my shell is different from the one I see in emacs.
- In subfolders of a project a local version of `eslint` installed in `$PROJECT_ROOT/node_modules/.bin/eslint` is not found and `javascript-eslint` is shown as automatically disabled

```bash
$ which eslint
node_modules/.bin/eslint
$ eslint .

/Users/heyarne/test/controllers/games.js
  11:1  error  More than 1 blank line not allowed  no-multiple-empty-lines

✖ 1 problem (1 error, 0 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.

$ eslint --no-eslintrc .

/Users/heyarne/test/controllers/games.js
  1:1  error  Parsing error: The keyword 'const' is reserved

/Users/heyarne/test/index.js
  1:1  error  Parsing error: The keyword 'const' is reserved

/Users/heyarne/test/migrations/20180110170854-init.js
  3:15  error  Parsing error: Assigning to rvalue

/Users/heyarne/test/migrations/20180110184039-create-player-table.js
  3:15  error  Parsing error: Assigning to rvalue

/Users/heyarne/test/utils/database.js
  1:1  error  Parsing error: The keyword 'const' is reserved

/Users/heyarne/test/utils/generate-name.js
  7:3  error  Parsing error: The keyword 'const' is reserved

✖ 6 problems (6 errors, 0 warnings)
```

The warnings I see in emacs:

<img width="628" alt="screen shot 2018-01-11 at 13 25 57" src="https://user-images.githubusercontent.com/525780/34826073-6b5f9756-f6d5-11e7-8887-1118ae84a6ad.png">

#### Reproduction guide :beetle:
- Start Emacs
- Enable the `syntax-checking` and `javascript` layers
- Add an `.eslintrc` to your project root with content `{  "extends": "standard" }`
- `npm i -D eslint eslint-config-standard eslint-plugin-import eslint-plugin-node eslint-plugin-promise eslint-plugin-standard`
- Open any javascript file and check the linter output

*Observed behaviour:* :eyes: :broken_heart:
See above.

*Expected behaviour:* :heart: :smile:
I'd expect the output to be identical to what my local `eslint` install provied.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript helm
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'complete auto-completion-return-key-behavior 'complete)
            syntax-checking emacs-lisp python clojure html php yaml git
            (version-control :variables version-control-diff-tool 'git-gutter version-control-global-margin t)
            markdown
            (org :variables org-projectile-file "docs/PROJECT.org")
            osx themes-megapack)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by syl20bnr** [comment]
Is there a way to overwrite the executable of a checker in Flycheck ?

**Comment by heyarne** [comment]
https://github.com/flycheck/flycheck/pull/272 seems to suggest that this is possible.

**Comment by zer09** [comment]
@heyarne  I don't know if it is related but have you tried setting this in your ```.S>/user-init```
```
  (setq js2-mode-show-parse-errors nil)
  (setq js2-mode-show-strict-warnings nil)
```

**Comment by heyarne** [comment]
@zer09 Nice! That solves a part of the problem. It now uses the local `eslint` when I'm in the same location and output is expected. It doesn't underline the whole lines but just shows a mark underneat the affected cols, which is okay I gues.. When I'm in a subfolder the output of `SPC e v` however is still as shown below and linting is disabled:
```
Syntax checkers for buffer 20180110170854-init.js in js2-mode:

  javascript-eslint (disabled)
    - may enable:  Automatically disabled!
    - executable:  Not found
    - config file: missing or incorrect

  javascript-jshint (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  javascript-jscs (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  javascript-standard (disabled)
    - may enable: Automatically disabled!
    - executable: Not found

  drupal-phpcs (disabled)
    - may enable: Automatically disabled!
    - predicate:  nil
    - executable: Not found

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20171109.216)
Emacs version:    25.3.1
System:           x86_64-apple-darwin16.7.0
Window system:    ns
```

**Comment by zer09** [comment]
I can't remember if I experience this before, but when I fully move from vscode to ```spacemacs``` for my js dev, I end up installing ```eslint``` globally.

I will try tomorrow if I can reproduced this by installing eslint locally.

**Comment by heyarne** [comment]
The problem with installing it globally is that all modules referenced in the config need to be installed globally as well. This can quickly become a problem when working with different teams and running into dependency-conflicts.

**Comment by zer09** [comment]
Ok I am able to reproduced your issue, if eslint installed locally.

**Comment by heyarne** [comment]
There is [this suggested solution](https://stackoverflow.com/a/39434694/2345852) that's using projectile to find the local `.eslintrc` and use that instead but I couldn't get it to work? Any thoughts?

**Comment by zer09** [comment]
Maybe this issue can help flycheck/flycheck#1087 specially the  2nd to the last comment.

**Comment by heyarne** [comment]
Nice, that solved it! Thanks a lot.

**Comment by jameslaneconkling** [comment]
@heyarne can you post your solution?  I tried the solutions suggested in https://github.com/flycheck/flycheck/issues/1087, but couldn't get it to work, perhaps b/c I'm not configuring it correctly for spacemacs.  Thanks!

**Comment by heyarne** [comment]
Sure: In my spacemacs config I added `javascript` to `dotspacemacs-configuration-layers` and `add-node-modules-path` to `dotspacemacs-additional-packages`. in `dotspacemacs/user-config` I added `(setq js2-mode-show-parse-errors nil js2-mode-show-strict-warnings nil)` to disable the standard linter that comes with `js2-mode`. Finally I made sure that all the packages are installed locally in your project (`eslint` + x).

If you're still having trouble, you can check your flycheck config via `SPC e v`.

**Comment by peterspicer** [comment]
In addition to all of the above.... for Spacemacs users ...

1. in   dotspacemacs-configuration-layers

`   dotspacemacs-additional-packages '(add-node-modules-path)
`

2. in dotspacemacs/user-config ()
```
  ;;===== Node setup:
  ;;  1. Careful of global ($npm -g install <module>) vs. local ./node-modules
  ;;  2. Best to use local as conflicts between projects might occur
  ;;  3. See inclusion of "add-node-modules-path" in dotspacemacs-additional-packages
  ;;  4. https://melpa.org/#/add-node-modules-path
  ;;
  ;; stop default linter - use ESLint linter as part of FlyCheck
  (setq js2-mode-show-parse-errors nil js2-mode-show-strict-warnings nil)
  (eval-after-load 'js2-mode
    '(add-hook 'js2-mode-hook #'add-node-modules-path))
```

**Comment by samuy** [comment]
Is this still a viable solution? I'm reading that `node-add-modules-path` introduces a [security risk](https://stackoverflow.com/questions/9679932#comment33532258_9683472). Sorry if I'm not understanding the solution correctly -- still very new to spacemacs
