### ISSUE TITLE
Don't shorten "spacemacs" and "dotspacemacs" in init file

### ISSUE THREAD

**Issue by tasmo** [syl20bnr/spacemacs#10136]
#### Description :octocat:
The strings "spacemacs" and "dotspacemacs" is shortened in my init file.

#### Reproduction guide :beetle:
- Start Emacs
- Open init file with [SPC f d]

*Observed behaviour:* :eyes: :broken_heart:
In my whole `~/.spacemacs.d/init.el` the string "dotspacemacs" is replaced by the string ".<S" and "spacemacs" is replaced by "<S".

*Expected behaviour:* :heart: :smile:
I want to see the whole strings for better overview and indentation.

#### System Info :computer:
- OS: gnu/linux (NixOS)
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 80a10f79)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm asciidoc ansible
      (auto-completion :variables auto-completion-enable-help-tooltip 'manual)
      (better-defaults :variables better-defaults-move-to-beginning-of-code-first t better-defaults-move-to-end-of-code-first t)
      colors
      (dash :variables helm-dash-browser-func 'eww)
      deft emacs-lisp games
      (geolocation :variables geolocation-enable-automatic-theme-changer t)
      git gtags html
      (ibuffer :variables ibuffer-group-buffers-by 'projects)
      (javascript :variables tern-command
                  '("node" "~/.npm-packages/bin/tern"))
      lua
      (markdown :variables markdown-live-preview-engine 'vmd)
      (mu4e :variables mu4e-spacemacs-layout-name "Mu4e" mu4e-spacemacs-layout-binding "m" mu4e-get-mail-command "mbsync -aq" mu4e-mu-binary "/run/current-system/sw/bin/mu" mu4e-installation-path "/run/current-system/sw/share/emacs/site-lisp")
      nginx nixos
      (org :variables org-enable-github-support t org-enable-reveal-js-support t org-projectile-file "todo.org")
      pass php python
      (rcirc :variables rcirc-enable-znc-support t rcirc-enable-authinfo-support t)
      ruby
      (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-position 'full)
      shell-scripts
      (spell-checking :variables spell-checking-enable-auto-dictionary t enable-flyspell-auto-completion t spell-checking-enable-by-default nil)
      syntax-checking theming
      (typography)
      version-control vimscript xkcd yaml)
```

**Comment by duianto** [comment]
The names are shortened by the https://github.com/Malabarba/Nameless package.

It can be disabled by adding:
```elisp
(emacs-lisp :variables emacs-lisp-hide-namespace-prefix nil)
```
to the `dotspacemacs-configuration-layers` variable, in `.spacemacs`.

source: https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/emacs-lisp#nameless

**Comment by tasmo** [comment]
@duianto Thank you very much for pointing to the right preference switch. This (of course) made it.

**Comment by duianto** [comment]
The nameless package has been disabled by default now, so you won't need to set that variable (after updating the develop branch).
Here's the PR: Disable nameless by default #10138
