### ISSUE TITLE
Treemacs/Neotree causes split to open with the wrong size

### ISSUE THREAD

**Issue by piotrpalek** [syl20bnr/spacemacs#10130]
#### Description :octocat:
When I try to open the first split to the right (while having only the main window and treemacs open) the opened split isn't properly sized, it's a small area to the right instead of half of the size of my main window.

#### Reproduction guide :beetle:
- Start Emacs
- Open any file / buffer
- Open Treemacs (SPC f t)
- Focus the main window
- Try to split it (SPC w /)

*Observed behaviour:* :eyes: :broken_heart:
The new split is created to the right but with the wrong size

*Expected behaviour:* :heart: :smile:
The split is created with the right size (half of the main window)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3cb9fea0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby python helm auto-completion better-defaults emacs-lisp typescript csv yaml lua git github markdown org deft pandoc
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking version-control javascript html erlang elixir react treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS NOTIFY LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by sdwolf** [comment]
I'm experiencing this with neotree as well, I believe that the 3rd window is created with `Width / 3` size, while the correct would be `(Width - 25) / 2` since the tree view window has a fixed size of 25.

Not sure how to fix this though.

**Comment by sdwolf** [comment]
I had these lines of code in my `.spacemacs` file ever since I started using it:

```emacs-lisp
  (defun my-evil-window-split-and-move ()
    (interactive)
    (evil-window-split)
    (windmove-down))
  (defun my-evil-window-vsplit-and-move ()
    (interactive)
    (evil-window-vsplit)
    (windmove-right))

  (spacemacs/set-leader-keys "ws" 'evil-window-split             )
  (spacemacs/set-leader-keys "wv" 'evil-window-vsplit            )
  (spacemacs/set-leader-keys "wS" 'my-evil-window-split-and-move )
  (spacemacs/set-leader-keys "wV" 'my-evil-window-vsplit-and-move)
```

I guess it never became a pain point bad enough for me to look into it. 

Evil seems to know how to do the right thing while the default emacs `split-window-right` function does not.

**Comment by syl20bnr** [comment]
Should we report this upstream ?

**Comment by Alexander-Miller** [comment]
> while having only the main window and treemacs open

Is this the only window configuration when this happens? If so I can add an extra call to balance windows when that happens.

**Comment by piotrpalek** [comment]
From my testing it seems to be the only configuration when that happens. Adding an extra call seems more like a workaround to me. Shouldn't it open properly in the first place?
Not saying it's a treemacs issue, maybe there's some deeper issue to look at.

**Comment by piotrpalek** [comment]
Also additional note, I've just tried to split the window horizontally (`SPC w /`) and then balance the windows (`SPC w =`) and the result is also a weird ratio.

**Comment by Alexander-Miller** [comment]
I've spent some time in the debugger. Long story short: The sizing discrepancy is due to treemacs not being a side window. Making it a side window causes its own issues (see https://github.com/Alexander-Miller/treemacs/issues/17) and changes its window's behaviour from emacs 26 onwards (like not being affected by `C-x 1`).
Looks like I'll need to advice `split-window-right`.

@piotrpalek Try the following:
```
(defun treemacs--split-window-advice (original-split-function &rest args)
  (-let [w (treemacs--is-visible?)]
    (unwind-protect
        (progn
          (when w (set-window-parameter w 'window-side treemacs-position))
          (apply original-split-function args))
      (when w (set-window-parameter w 'window-side treemacs-position)))))
(advice-add 'split-window-right :around #'treemacs--split-window-advice)
```

**Comment by piotrpalek** [comment]
@Alexander-Miller this seems to do the trick :+1:

**Comment by Alexander-Miller** [comment]
I've pushed that code to master now. IIRC side window parameters were changed in emacs 26, so it may need an additional patch.
