### ISSUE TITLE
Latest develop, broken helm-swoop [SPC s s]

### ISSUE THREAD

**Issue by vbauerster** [syl20bnr/spacemacs#10132]
#### Description :octocat:
Latest develop branch, has broken helm-swoop: [SPC s s]

#### Reproduction guide :beetle:
- Start Emacs
- press [SPC s s]

*Observed behaviour:* :eyes: :broken_heart:
Wrong type argument: commandp, helm-file-do-rg

*Expected behaviour:* :heart: :smile:
helm swoop pane.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 34a0eb24)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org git
      (version-control :variables version-control-diff-side 'left)
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip t)
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      (spell-checking :variables spell-checking-enable-by-default nil)
      html markdown neotree yaml javascript rust
      (go :variables go-tab-width 4 gofmt-command "goimports" go-use-gometalinter t)
      protobuf docker themes-megapack dash semantic
      (ranger :variables ranger-show-preview t ranger-show-literal t ranger-max-preview-size 4)
      (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by syl20bnr** [comment]
Thank you for the report, fixed in develop.
