### ISSUE TITLE
Magit navigation on dvorak keyboard-layout is not working as expected.

### ISSUE THREAD

**Issue by zer09** [syl20bnr/spacemacs#10133]
#### Description :octocat:
4a34ef4 break the dvorak layout navigation for magit. The up and down was rebinded.

#### Reproduction guide :beetle:
- Pull the latest commit including the commit 4a34ef4
- Start Emacs
- Open project
- Open magit
- Then try to navigate.

*Observed) behaviour:* :eyes: :broken_heart:
The the navigation key ```t``` is just openning "I am not sure if it was ```tags```".
The the navigation key ```n``` is navigating downward.

*Expected behaviour:* :heart: :smile:
The navigation key ```t``` should navigate downward.
The navigation key ```n``` should navigate upward.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: test (rev. 014ed731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((fasd)
 (imenu-list)
 (spell-checking :variables spell-checking-enable-by-default nil)
 (syntax-checking)
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 (ycmd)
 (rebox :variables rebox-enable-in-text-mode t)
 (ranger :variables ranger-enter-with-minus t ranger-show-hidden t ranger-max-preview-size 1)
 (colors)
 (c-c++ :variables c-c++-enable-clang-support t c-c++-enable-rtags-support t)
 (theming)
 (keyboard-layout :variables kl-layout 'dvorak)
 (git)
 (version-control :variables version-control-diff-tool 'git-gutter+ version-control-diff-side 'left)
 (systemd)
 (shell :variables shell-default-shell 'eshell)
 (protobuf)
 (go :variables go-use-gometalinter t gofmt-command "goimports" go-tab-width 4 flycheck-gometalinter-fast t flycheck-gometalinter-deadline "30s" flycheck-gometalinter-enable-linters
     '("testify" "safesql"))
 (html)
 (javascript :variables javascript-disable-tern-port-files nil)
 (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t)
 (shell-scripts)
 (sql :variables sql-capitalize-keywords t)
 (yaml)
 (lua)
 (ivy :variables ivy-extra-directories nil)
 emacs-lisp markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by nixmaniack** [comment]
I think I have figured out the problem but since I don't understand `keyboard-layout` implementation I won't be able to propose a right solution. 

The issue is here https://github.com/syl20bnr/spacemacs/blob/80a10f79db891990e3f26c2310f33e038d80303b/layers/%2Bintl/keyboard-layout/packages.el#L357

`evil-magit` is initialized after `magit` is loaded and this code checks for `evil-magit-*` variables (to perform the replacement bindings?) which are undefined at that moment and bails out leaving `magit-*` without `keyboard-layout` configurations.  

Current *workaround* would be to add `(require 'evil-magit)` before this `dolist` block until proper fix is proposed.

**Comment by JonathanReeve** [comment]
The same thing is happening for the Colemak keyboard layout. Am I correct to assume that, since Spacemacs lazy-loads packages, then the keyboard-layout layer doesn't effect layers that aren't loaded at startup? That was what I thought was going on with `dired`.

**Comment by nixmaniack** [comment]
@JonathanReeve Your problem with `dired` could be a related one. There were some changes pertaining to load order of packages and I'm suspecting that could be one of the reasons for this regression.

**Comment by Electron-libre** [comment]
Don't understand why is this closed. It's not merged in develop and this issue is not fixed.

**Comment by nixmaniack** [comment]
The issue is still open @Electron-libre.

**Comment by nixmaniack** [comment]
Thanks @StreakyCobra for fixing this _properly_! 👍 .

**Comment by zer09** [comment]
Merged.

Thanks @StreakyCobra .
