### ISSUE TITLE
spacemacs.org broken - wrong certificate

### ISSUE THREAD

**Issue by phoe** [syl20bnr/spacemacs#10159]
![screenshot from 2018-01-15 10-16-41](https://user-images.githubusercontent.com/15045546/34935171-3e23ce32-f9dd-11e7-8c8b-6051330d42c9.png)

**Comment by syl20bnr** [comment]
Thank you for the issue, we have on issue for this opened on the webiste repo: https://github.com/syl20bnr/spacemacs.org/issues/24
