### ISSUE TITLE
evil-nerd-commenter + web-mode = :-(

### ISSUE THREAD

**Issue by bsandrow** [syl20bnr/spacemacs#1015]
Looks like `evil-nerd-commenter` is looking for `web-mode-is-comment`, which doesn't exist. In `web-mode`, you *can* hit `M-;` which [apparently](http://emacs.stackexchange.com/questions/7307/how-can-i-comment-a-block-of-css-or-html-in-web-mode) calls `comment-dwim`. This works, but is less than ideal. It would be nice to be able to use the same bindings.

I realize that this could be tackled in a number of ways, but since it's part of the Spacemacs experience, I thought that I would open an issue here first.

**Comment by syl20bnr** [comment]
Thank you, it is good to open an issue here to track it. I guess it should be reported upstream in the [evil-nerd-commenter](https://github.com/redguardtoo/evil-nerd-commenter) repo.

**Comment by bsandrow** [comment]
Issue opened here: https://github.com/redguardtoo/evil-nerd-commenter/issues/48

**Comment by bsandrow** [comment]
Looks like this was a change to `web-mode` that broke `evil-nerd-commenter`, and that repo was updated 3 days ago to fix it. Somehow I ended up with the broken version.
