### ISSUE TITLE
pytest python testing fails to import modules.

### ISSUE THREAD

**Issue by choppsv1** [syl20bnr/spacemacs#10151]
#### Description :octocat:
pytest python testing fails to import modules.

#### Reproduction guide :beetle:
- Setup or lcoate python package as described in *observed behavior* section.
- Start Emacs
- Configure python-test-runner as `'pytest`.

*Observed behavior:* :eyes: :broken_heart:

When running `, t m` (or similar) in a test file in a subdirectory of a python
project and using pytest (rather than nose), pytest fails to import the module
under test.

project/
  mypkg/
    __init__.py
    ...
  tests/
    test_mypkg.py
    ...

So when one is in a buffer visiting `test_mypkg.py` and runs a python test
command (test module, test file, test function, ...) pytest will fail to be able
to import `mypkg`.

*Expected behaviour:* :heart: :smile:

Test should work as it does when `nose` is used.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 21e96612)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-private-snippets-directory "~/.spacemacs.d/private/snippets" auto-completion-tab-key-behavior 'cycle)
 better-defaults docker graphviz gtags ietf jabber mu4e org
 (osx :variables osx-use-option-as-meta t)
 pdf-tools ranger rebox
 (shell :variables)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-tooltips t)
 theming themes-megapack
 (version-control :variables version-control-diff-tool 'git-gutter version-control-diff-side 'left version-control-global-margin t)
 php csv
 (c-c++ :variables c-c++-default-mode-for-headers 'c-mode c-c++-enable-clang-support t)
 emacs-lisp git go html javascript
 (latex :variables latex-build-command "latexmk")
 (lua :variables lua-default-application "lua5.1")
 markdown
 (python :variables python-fill-column 100 python-test-runner
         '(pytest nose)
         pytest-global-name "python -m pytest" python-enable-yapf-format-on-save nil)
 (semantic :disabled-for emacs-lisp)
 shell-scripts systemd yaml
 (yang :variables yang-pyang-rules "lint" yang-pyang-extra-args "--max-line-length=79")
 (erc :variables erc-server-list
      '(("irc.freenode.net" :port "6697" :ssl t :nick "chopps"))))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by choppsv1** [comment]
The workaround, as can be seen in the elisp section in the OP, is to set 

`pytest-global-name "python -m pytest"`

instead of the default `py.test`

**Comment by syl20bnr** [comment]
Thank you for the work-around. PR welcome :-)

**Comment by Compro-Prasad** [comment]
Is this still valid?

**Comment by choppsv1** [comment]
I haven't used this functionality lately, but if nothing has changed then it's probably valid. I think @syl20bnr may have been suggesting to just commit the work-around into mainline, and that a PR to do this would be welcome. :)
