### ISSUE TITLE
evil-shift-width is being set to 2 and can't be set to 4 from python hook

### ISSUE THREAD

**Issue by adrian-castravete** [syl20bnr/spacemacs#10160]
#### Description :octocat:
evil-shift-width is being set to 2 and can't be set to 4 from python hook.
This is also similar to https://github.com/syl20bnr/spacemacs/issues/5793

#### Reproduction guide :beetle:
- Start Emacs
- Add the next bit of configuration code to `user-config`:
```elisp
(add-hook 'python-mode-hook
          (lambda ()
            (setq indent-tabs-mode nil)
            (setq tap-width 4)
            (setq evil-shift-width 4)))
```

*Observed behaviour:* :eyes: :broken_heart:
The shifting behaviour moves by two spaces (Spacemacs' VIM mode: `>>` and `<<`).
Moreover, inspecting the variable with `<SPC h d v>` gives:
```
evil-shift-width is a variable defined in `evil-vars.el'.
Its value is 2
Original value was 4
```

*Expected behaviour:* :heart: :smile:
The shifting behaviour moves by four spaces.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 4bb4cb4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(haskell clojure vimscript nginx yaml windows-scripts helm auto-completion better-defaults emacs-lisp git markdown org
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         (spell-checking :variables spell-checking-enable-by-default nil)
         syntax-checking version-control python lua emoji games xkcd react colors csv)
```

#### Backtrace :paw_prints:
```
```

**Comment by adrian-castravete** [comment]
I have also tried changing the bare minimum in `.spacemacs` (no other layers and changes other than specified above). To note I'm using the **master** branch.

**Comment by nixmaniack** [comment]
What if you set `(setq-default python-indent-offset 4)` in your `dotspacemacs/user-init` ? 

Also, if you already have buffer with indentation width of 2, I believe that's what will be automatically set when you open the buffer.

**Comment by adrian-castravete** [comment]
I just tried your suggestion. And it still happens. The code I'm testing this on is:
```
#!/usr/bin/env python

def main():
    pass

if __name__ == '__main__':
    main()
```
and just trying to move `pass` to the left or right.

**Comment by nixmaniack** [comment]
Have your removed your modifiction(python hook) before adding my suggestion?
What's the value of `evil-shift-width` and `python-indent-offset` when you're in this file?

**Comment by adrian-castravete** [comment]
OK. I took the following steps:
1. backed-up my current `.spacemacs`
2. added the line in `user-init`
3. restarted emacs
4. opened the python file at which it asked me to add the `python` layer for `python-mode` (did so)
5. restarted emacs
6. reopened the python file
After this everything went fine. So it must be something I was overriding/overwriting, though I don't see where. The only place I'm specifying 2 space shift/tabs is for javascript related variables.

After this though, I started investigating and singled out the problem. Do you have any idea why the next piece of code in `user-config` would set the shift width to 2?
```
  (add-hook 'python-mode-hook
            (lambda ()
              (flycheck-set-checker-executable 'python-pylint "~/.profile_scripts/my-pylint")))
```

**Comment by adrian-castravete** [comment]
Thank you very much @nixmaniack ! Sorry for the disturbance.

**Comment by Isti115** [comment]
I would just like to point out that the initial comment has a typo (`tap-width` instead of `tab-width`), if you could edit it, @adrian-castravete , it could help future visitors who wish to copy the code.

**Comment by duianto** [comment]
@Isti115 Thanks for helping future visitors. The typo has been fixed.

**Comment by AleXoundOS** [comment]
In my case `(setq evil-shift-width 4)` does not work. Only `(setq-default evil-shift-width 4)` works but it sets `evil-shift-width` globally (for orgmode too):
```elisp
(add-hook 'markdown-mode-hook
          (lambda ()
            (setq indent-tabs-mode nil)
            (setq tab-width 4)
            (setq-default evil-shift-width 4)))
```
And further to set orgmode shift width back to 2:
```elisp
(add-hook 'org-mode-hook
          (lambda () (setq-default evil-shift-width 2)))
```
