### ISSUE TITLE
Unable to use Source Code Pro fonts?

### ISSUE THREAD

**Issue by costis-t** [syl20bnr/spacemacs#10162]
#### Description :octocat:
I have installed Source Code Pro fonts and libotf (from a [SE question](https://emacs.stackexchange.com/questions/33245/what-is-the-proper-way-to-identify-a-font-for-spacemacs-file/33250)) but I do not get spacemacs to display the fonts properly as [this image ](https://imgur.com/a/G7FYV) shows.
The `.spacemacs` configuration file is untouched since the installation (default).

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The fonts are not displayed correctly.

*Expected behaviour:* :heart: :smile:
The fonts should be correctly displayed.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(haskell helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS NOTIFY ACL GNUTLS ZLIB GTK3 X11

Both  Source Code Pro fonts and libotf are installed:
```
equery files source-code-pro
 * Searching for source-code-pro ...
 * Contents of media-fonts/source-code-pro-2.030.1.050_p20170816:
/usr
/usr/share
/usr/share/doc
/usr/share/doc/source-code-pro-2.030.1.050_p20170816
/usr/share/doc/source-code-pro-2.030.1.050_p20170816/README.md.bz2
/usr/share/fonts
/usr/share/fonts/source-code-pro
/usr/share/fonts/source-code-pro/SourceCodePro-Black.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-BlackIt.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-Bold.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-BoldIt.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-ExtraLight.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-ExtraLightIt.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-It.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-Light.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-LightIt.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-Medium.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-MediumIt.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-Regular.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-Semibold.ttf
/usr/share/fonts/source-code-pro/SourceCodePro-SemiboldIt.ttf
/usr/share/fonts/source-code-pro/encodings.dir
/usr/share/fonts/source-code-pro/fonts.dir
/usr/share/fonts/source-code-pro/fonts.scale

equery files dev-libs/libotf
 * Searching for libotf in dev-libs ...
 * Contents of dev-libs/libotf-0.9.13:
/usr
/usr/bin
/usr/bin/libotf-config
/usr/bin/otfdump
/usr/bin/otflist
/usr/bin/otftobdf
/usr/bin/otfview
/usr/include
/usr/include/otf.h
/usr/lib64
/usr/lib64/libotf.so -> libotf.so.0.0.0
/usr/lib64/libotf.so.0 -> libotf.so.0.0.0
/usr/lib64/libotf.so.0.0.0
/usr/lib64/pkgconfig
/usr/lib64/pkgconfig/libotf.pc
/usr/share
/usr/share/doc
/usr/share/doc/libotf-0.9.13
/usr/share/doc/libotf-0.9.13/AUTHORS
/usr/share/doc/libotf-0.9.13/ChangeLog.bz2
/usr/share/doc/libotf-0.9.13/NEWS.bz2
/usr/share/doc/libotf-0.9.13/README.bz2
```
`M-x describe-font` returns:
```
name (opened by): -adobe-courier-medium-r-normal--17-120-100-100-m-100-iso8859-1
       full name: -adobe-courier-medium-r-normal--17-120-100-100-m-100-iso8859-1
            size: 17
          height: 15
 baseline-offset:  0
relative-compose:  0
  default-ascent:  0
          ascent: 12
         descent:  3
   average-width: 10
     space-width: 10
       max-width: 10
```

**Comment by da-edra** [comment]
Hello, have you tried installing Source Code Pro fonts inside `/usr/share/fonts/adobe-source-code-pro`?
Your folder is named `source-code-pro`, the default (at least on Arch) is `adobe-source-code-pro`.

**Comment by costis-t** [comment]
Thanks for your help, da-edra! Yes, the fonts were correctly installed.
My issue is now solved.
In the gentoo I currently work on,I rebuilt emacs with every available flag (overkill, ok) and it worked.
I narrowed the use flags down and it seems the `xft` use flag, which builds emacs _"with support for XFT font renderer (x11-libs/libXft)"_ is required.
I close this issue.

Thanks again!

```
$ equery uses emacs
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for app-editors/emacs-25.3:
 U I
 + + X                   : Add support for X11
 - - Xaw3d               : Add support for the 3d athena widget set
 + + acl                 : Add support for Access Control Lists
 + + alsa                : Add support for media-libs/alsa-lib (Advanced Linux Sound Architecture)
 - - athena              : Enable the MIT Athena widget set (x11-libs/libXaw)
 + + dbus                : Enable dbus support for anything that needs it (gpsd, gnomemeeting, etc)
 - - dynamic-loading     : Enable loading of dynamic libraries at runtime
 - - games               : Support shared score files for games
 - - gconf               : Use gnome-base/gconf to read the system font name
 - - gfile               : Use gfile (dev-libs/glib) for file notification
 + + gif                 : Add GIF image support
 + + gpm                 : Add support for sys-libs/gpm (Console-based mouse driver)
 - - gsettings           : Use gsettings (dev-libs/glib) to read the system font name
 + + gtk                 : Add support for x11-libs/gtk+ (The GIMP Toolkit)
 + + gtk3                : Prefer version 3 of the GIMP Toolkit to version 2 (x11-libs/gtk+)
 - - gzip-el             : Compress bundled Emacs Lisp source
 - - imagemagick         : Use media-gfx/imagemagick for image processing
 + + inotify             : Enable inotify filesystem monitoring support
 + + jpeg                : Add JPEG image support
 - - kerberos            : Add kerberos support
 - - libxml2             : Use dev-libs/libxml2 to parse XML instead of the internal Lisp
                           implementations
 - - livecd              : !!internal use only!! DO NOT SET THIS FLAG YOURSELF!, used during livecd
                           building
 - - m17n-lib            : Enable m17n-lib support
 - - motif               : Add support for the Motif toolkit
 - - pax_kernel          : Enable building under a PaX enabled kernel
 + + png                 : Add support for libpng (PNG images)
 - - sound               : Enable sound support
 - - source              : Install C source files and make them available for find-function
 + + ssl                 : Add support for Secure Socket Layer connections
 + + svg                 : Add support for SVG (Scalable Vector Graphics)
 + + tiff                : Add support for the TIFF image format
 - - toolkit-scroll-bars : Use the selected toolkit's scrollbars in preference to Emacs' own scrollbars
 - - wide-int            : Prefer wide Emacs integers (typically 62-bit). This option has an effect
                           only on architectures where "long" and "long long" types have different
                           size.
 + + xft                 : Build with support for XFT font renderer (x11-libs/libXft)
 + + xpm                 : Add support for XPM graphics format
 + + zlib                : Add support for zlib (de)compression
```

**Comment by kuberlog** [comment]
Thanks. This helped me!

**Comment by NeroAngelo-117** [comment]
> Thanks for your help, da-edra! Yes, the fonts were correctly installed.
> My issue is now solved.
> In the gentoo I currently work on,I rebuilt emacs with every available flag (overkill, ok) and it worked.
> I narrowed the use flags down and it seems the `xft` use flag, which builds emacs _"with support for XFT font renderer (x11-libs/libXft)"_ is required.
> I close this issue.
> 
> Thanks again!
> 
> ```
> $ equery uses emacs
> [ Legend : U - final flag setting for installation]
> [        : I - package is installed with flag     ]
> [ Colors : set, unset                             ]
>  * Found these USE flags for app-editors/emacs-25.3:
>  U I
>  + + X                   : Add support for X11
>  - - Xaw3d               : Add support for the 3d athena widget set
>  + + acl                 : Add support for Access Control Lists
>  + + alsa                : Add support for media-libs/alsa-lib (Advanced Linux Sound Architecture)
>  - - athena              : Enable the MIT Athena widget set (x11-libs/libXaw)
>  + + dbus                : Enable dbus support for anything that needs it (gpsd, gnomemeeting, etc)
>  - - dynamic-loading     : Enable loading of dynamic libraries at runtime
>  - - games               : Support shared score files for games
>  - - gconf               : Use gnome-base/gconf to read the system font name
>  - - gfile               : Use gfile (dev-libs/glib) for file notification
>  + + gif                 : Add GIF image support
>  + + gpm                 : Add support for sys-libs/gpm (Console-based mouse driver)
>  - - gsettings           : Use gsettings (dev-libs/glib) to read the system font name
>  + + gtk                 : Add support for x11-libs/gtk+ (The GIMP Toolkit)
>  + + gtk3                : Prefer version 3 of the GIMP Toolkit to version 2 (x11-libs/gtk+)
>  - - gzip-el             : Compress bundled Emacs Lisp source
>  - - imagemagick         : Use media-gfx/imagemagick for image processing
>  + + inotify             : Enable inotify filesystem monitoring support
>  + + jpeg                : Add JPEG image support
>  - - kerberos            : Add kerberos support
>  - - libxml2             : Use dev-libs/libxml2 to parse XML instead of the internal Lisp
>                            implementations
>  - - livecd              : !!internal use only!! DO NOT SET THIS FLAG YOURSELF!, used during livecd
>                            building
>  - - m17n-lib            : Enable m17n-lib support
>  - - motif               : Add support for the Motif toolkit
>  - - pax_kernel          : Enable building under a PaX enabled kernel
>  + + png                 : Add support for libpng (PNG images)
>  - - sound               : Enable sound support
>  - - source              : Install C source files and make them available for find-function
>  + + ssl                 : Add support for Secure Socket Layer connections
>  + + svg                 : Add support for SVG (Scalable Vector Graphics)
>  + + tiff                : Add support for the TIFF image format
>  - - toolkit-scroll-bars : Use the selected toolkit's scrollbars in preference to Emacs' own scrollbars
>  - - wide-int            : Prefer wide Emacs integers (typically 62-bit). This option has an effect
>                            only on architectures where "long" and "long long" types have different
>                            size.
>  + + xft                 : Build with support for XFT font renderer (x11-libs/libXft)
>  + + xpm                 : Add support for XPM graphics format
>  + + zlib                : Add support for zlib (de)compression
> ```

How do add these use flags in a ubuntu based distro?

**Comment by CaydendW** [comment]
@Young-Angelo you can't. You don't have to compile everything from the source. apt install emacs is all you have to do.

**Comment by adeltby** [comment]
On MacOS after installing the font from google fonts you have to run :

`cp SourceCodePro-VariableFont_wght.ttf ~/Library/Fonts`

**Comment by lebensterben** [comment]
locking this topic now.

refer the README at root of the repository for installation institutes of source code pro font.
