### ISSUE TITLE
How to Bind vim commands to hotkeys in order to run a makefile under current directory

### ISSUE THREAD

**Issue by M-Yudaxia** [syl20bnr/spacemacs#10163]
usually i type this  :!make it will run the makefile
but i want to map the  command-R
(global-set-key (kbd "s-r") 'somefunction)
i have no idea how to write lisp.

**Comment by myrgy** [comment]
Helm-make is integrated into spacemacs. And it should be able to compile with `sps c c` or `sps c C`
