### ISSUE TITLE
Org's package repo can be https now

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#10169]
#### Description :octocat:

Org's package repo should be https now

http://lists.gnu.org/archive/html/emacs-orgmode/2018-01/msg00096.htmlre

Currently it's set to http somewhere (I can't figure out where).

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4c231ae2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(rust octave swift nginx better-defaults spacemacs-layouts ivy
      (markdown :variables markdown-live-preview-engine 'vmd)
      (syntax-checking :variables syntax-checking-enable-tooltips t)
      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup nil spacemacs-default-company-backends
                       '(company-capf
                         (company-dabbrev-code company-keywords)
                         company-files company-dabbrev))
      git dash pdf-tools html
      (org :variables org-enable-github-support t org-enable-reveal-js-support t org-want-todo-bindings t)
      colors
      (osx :variables osx-command-as 'super)
      github
      (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
      (spell-checking :variables spell-checking-enable-by-default nil)
      version-control rcirc tmux yaml docker restclient lua chrome
      (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
      emoji aj-elixir aj-emacs-lisp aj-javascript aj-term aj-typescript aj-ruby auto-correct cleverparens-lispy dotenv flow match-indent shift-number writing)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES LCMS2

**Comment by hex2a** [comment]
this needs to be changed to https:
https://github.com/syl20bnr/spacemacs/blob/723604d904e357511c16b908693a06876fc74455/core/core-configuration-layer.el#L2461

this check/workaround needs to be removed (else the repo will still use http)
https://github.com/syl20bnr/spacemacs/blob/723604d904e357511c16b908693a06876fc74455/core/core-configuration-layer.el#L490

**Comment by benbotwin** [comment]
Spacemacs now tells me that it can't connect to orgmode.org:443. Could this be the cause of it?

**Comment by aaronjensen** [comment]
@benbotwin it could be the catalyst, but the cause is probably somewhere else as this is accessible for me: https://orgmode.org/elpa/

**Comment by benbotwin** [comment]
@aaronjensen I can get to that from my browser as ell, but spaceman’s is telling me it can’t connect. I’ve tried it on several different networks too and it hasn’t changed.

**Comment by aaronjensen** [comment]
What version of emacs? Is it true with emacs -Q?

**Comment by benbotwin** [comment]
What do I after running `emacs -Q`?

Sorry, I'm not super emacs savy

**Comment by aaronjensen** [comment]
Try evaling `(url-retrieve-synchronously "https://orgmode.org/elpa/")` (you can use `M-:` to eval something)

**Comment by benbotwin** [comment]
I got this

```
Debugger entered--Lisp error: (error "Could not create connection to orgmode.org:443")
  signal(error ("Could not create connection to orgmode.org:443"))
  error("Could not create connection to %s:%d" "orgmode.org" 443)
  url-http(#s(url :type "https" :user nil :password nil :host "orgmode.org" :portspec nil :filename "/elpa/" :target nil :attributes nil :fullness t :silent nil :use-cookies t :asynchronous nil) #f(compiled-function (&rest ignored) #<bytecode 0x40a82541>) (nil) nil tls)
  url-https(#s(url :type "https" :user nil :password nil :host "orgmode.org" :portspec nil :filename "/elpa/" :target nil :attributes nil :fullness t :silent nil :use-cookies t :asynchronous nil) #f(compiled-function (&rest ignored) #<bytecode 0x40a82541>) (nil))
  url-retrieve-internal("https://orgmode.org/elpa/" #f(compiled-function (&rest ignored) #<bytecode 0x40a82541>) (nil) nil nil)
  url-retrieve("https://orgmode.org/elpa/" #f(compiled-function (&rest ignored) #<bytecode 0x40a82541>) nil nil nil)
  url-retrieve-synchronously("https://orgmode.org/elpa/")
  eval((url-retrieve-synchronously "https://orgmode.org/elpa/") nil)
  eval-expression((url-retrieve-synchronously "https://orgmode.org/elpa/") nil nil 127)
  funcall-interactively(eval-expression (url-retrieve-synchronously "https://orgmode.org/elpa/") nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

But I can still get to that url from my browser.

**Comment by aaronjensen** [comment]
What version of emacs are you on? `M-x emacs-version`

**Comment by benbotwin** [comment]
I was running 27.0.50. I just installed 25.3 and it works fine. I guess 27 is buggy still.

**Comment by aaronjensen** [comment]
Oh. I'm on 26 and it works. You may want to report that bug.
