### ISSUE TITLE
error: (void-variable counsel-projectile-switch-project-actions)

### ISSUE THREAD

**Issue by lsytj0413** [syl20bnr/spacemacs#10177]
#### Description :octocat:
An error occurred while post-configuring swiper in layer spacemacs-layouts (error: (void-variable counsel-projectile-switch-project-actions))

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.50.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e11f7ba)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((ivy :variables ivy-extra-directories nil)
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for org)
 (better-defaults :variables better-defaults-move-to-end-of-code-first t)
 emacs-lisp git markdown org
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (python :variables python-sort-imports-on-save t)
 semantic
 (go :variables go-tab-width 4 go-use-gometalinter t)
 protobuf ranger gtags ibuffer sql
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 900)
 graphviz plantuml docker
 (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
 liter ycmd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lsytj0413** [comment]
This commit 4b111f7701ffea8e724666471a64867fe0c7af22 broken.

**Comment by nixmaniack** [comment]
[`counsel-projectile`](https://github.com/ericdanan/counsel-projectile/commit/a4e9a34d7f040a8e4f50b45537ffe211e676bd6d) has [updated](https://github.com/ericdanan/counsel-projectile/commit/a4e9a34d7f040a8e4f50b45537ffe211e676bd6d) this mechanism a month back and `counsel-projectile-switch-project-actions` is no more defined. This needs to be fixed in Spacemacs.

**Comment by MarcusE1W** [comment]
Same problem here. Archlinux, emacs 25.3.1 develop branch

**Comment by marienz** [comment]
Same here. This is with the counsel-projectile from spacelpa-0.300 (counsel-projectile-20171001.641). It has counsel-projectile-switch-project-actions, but that isn't autoloaded. Sticking a `(require 'counsel-projectile)` in `spacemacs-layouts/post-init-swiper` makes the error go away (not saying that's the right fix, but seems to confirm the problem is a missing autoload or require).

**Comment by robbyoconnor** [comment]
Same problem -- rebase and remove https://github.com/syl20bnr/spacemacs/commit/4b111f7701ffea8e724666471a64867fe0c7af22 and everything should be good.

**Comment by nilehmann** [comment]
I confir the error. I tried @marienz fix but that didn't work for me. Still getting the error after adding `(require 'counsel-projectile)`

**Comment by syl20bnr** [comment]
Should be fixed in develop.

**Comment by jsoo1** [comment]
I still have this on develop `9d540f8`.

**Comment by nixmaniack** [comment]
@jsoo1 Have you updated packages? Could you describe the repro steps with your system info and if possible include the backtrace?

**Comment by jsoo1** [comment]
I can include a backtrace tomorrow.  I have updated packages. Reproduction is via `SPC p l`.

**Comment by jsoo1** [comment]
``` elisp
Debugger entered--Lisp error: (void-variable counsel-projectile-switch-project-action)
  (ivy-read "Switch to Project Perspective: " (if (projectile-project-p) (cons (abbreviate-file-name (projectile-project-root)) (projectile-relevant-known-projects)) projectile-known-projects) :action counsel-projectile-switch-project-action :caller 'spacemacs/ivy-persp-switch-project)
  spacemacs/ivy-persp-switch-project(nil)
  funcall-interactively(spacemacs/ivy-persp-switch-project nil)
  call-interactively(spacemacs/ivy-persp-switch-project nil nil)
  command-execute(spacemacs/ivy-persp-switch-project)
```

**Comment by jsoo1** [comment]
I notice in the diff the read syntax `#'` was removed from [`/layers/+spacemacs/spacemacs-layouts/funcs.el:425`](https://github.com/syl20bnr/spacemacs/blob/3eb6ae20eac6b33bf119656f369211ab914f8d81/layers/%2Bspacemacs/spacemacs-layouts/funcs.el#L425) which is the same as wrapping the function in `(function ...)` (which i just discovered [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Anonymous-Functions.html#index-g_t_0040samp_007b_0023_0027_007d-syntax-882).  Adding `#'` back fixes the issue.  Should submit a PR?

**Comment by nixmaniack** [comment]
I don't fully understand why it should make such a difference. If you think that is the correct solution to your problem - you may open a PR. 

Could you once try removing your compiled elisp files and see if it helps? If it doesn't - then you can open a PR with the fix you described.

**Comment by jsoo1** [comment]
Neither do I. Deleting `.elc` files makes sense...

**Comment by jsoo1** [comment]
Removing all compiled elisp did not solve the issue, but adding back the quote does.  I am hesitant to PR because I am not sure why it helps and an ubuntu machine using emacs 27 does not have the same problem.

**Comment by syl20bnr** [comment]
Please verify in develop.

**Comment by jsoo1** [comment]
I can verify tomorrow thanks so much!

**Comment by jsoo1** [comment]
Working in develop.
