### ISSUE TITLE
commit 0f646b8 breaks `SPC f e R`.

### ISSUE THREAD

**Issue by EMayej** [syl20bnr/spacemacs#10171]
commint 0f646b884dd9164f923839ed59898c56020e34cc breaks `dotspacemacs/sync-configuration-layers`

in here:
https://github.com/syl20bnr/spacemacs/blob/0f646b884dd9164f923839ed59898c56020e34cc/core/core-dotspacemacs.el#L757-L765

**Comment by duianto** [comment]
Confirmed

Using a list as the value for the mode line theme:
`dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 1.5)`
causes one of the `SPC f e R` tests to fail:
>** TEST: [[file:c:/Users/Username/AppData/Roaming/.spacemacs::dotspacemacs-mode-line-theme][dotspacemacs-mode-line-theme]] is 'spacemacs, 'all-the-icons, 'custom, 'vim-powerline or 'vanilla
*** FAIL: (spacemacs :separator wave :separator-scale 1.5)

There is also an issue with using all but one of the symbols as the mode line theme:
- `spacemacs`
- `custom` (with the custom theme example, added to `dotspacemacs/user-init`: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#custom-spaceline-theme)
- `vim-powerline`
- `vanilla`

They all show:
>Error (use-package): spaceline-all-the-icons/:init: Symbol’s value as variable is void: spaceline-all-the-icons-separator-scale

on startup, and after syncing the configuration layers `SPC f e R`

Using the `all-the-icons` symbol, doesn't show the error message.

**Comment by syl20bnr** [comment]
Indeed the tests has to be updated for the new supported list type as value for this variable.

**Comment by syl20bnr** [comment]
Fixed in last develop.

**Comment by x61** [comment]
This issue still persists in develop branch as recent as today. Please address it.

**Comment by duianto** [comment]
@x61 `SPC f e R` is not showing any errors for me on the latest develop branch.

Please include your system info, press `SPC h d s` and it will be copied to your clipboard.
#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0e3a3713)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by x61** [comment]
@duianto, thanks for the response. Below is my system info:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0e3a371)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown org evil-commentary
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control c-c++)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by x61** [comment]
@EMayej, below is the output with the error message:

** TEST: [[file:/home/coolrunning/.spacemacs::dotspacemacs-mode-line-theme][dotspacemacs-mode-line-theme]] is 'spacemacs, 'all-the-icons, 'custom, 'vim-powerline or 'vanilla or a list with `car' one of the previous values and properties one of the following: `:separator' or `:separator-scale'
*** FAIL: nil
*

**Comment by EMayej** [comment]
@x61  It seems that your `dotspacemacs-mode-line-theme` is nil. Please set that value in you .spacemacs file. You can run `SPC f e D` to compare your .spacemacs with official template.

**Comment by x61** [comment]
@EMayej, that was the culprit. Don't know how I managed to delete that line from my default dotspacemacs. I am coming from emacs, never used VI. I must have deleted it without realizing it.  Thanks for you input

**Comment by abeluck** [comment]
This happened to me today when I cloned a fresh spacemacs (from master), edited the .spacemacs, then switched to develop.

The .spacemacs generated by the master branch didn't have `dotspacemacs-mode-line-theme`.

**Comment by x61** [comment]
@abeluck, I can attest to this. Each time I re-install a new spacemacs and switch to the develop branch, I end up getting this error message and had to added it. It got so frequent that I just backup my `.spacemacs` and replace the new one each time I needed to reinstall spacemacs and use the `develop` branch.

**Comment by EMayej** [comment]
@x61 @abeluck 
try clone develop branch directly
`
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
`

**Comment by duianto** [comment]
Maybe one solution could be, to have a branch choice in the initial setup.
Possibly something like this:
Choose branch (switching branch will restart Emacs):
- [master]
- develop

**Comment by x61** [comment]
@EMayej, any reason why the `.spacemace` does not behave the same when you directly clone the 'develop' branch versus checking it out? Is it possible for the `.spacemacs` to update to the corresponding `.spacemacs` for `develop` and `master`?

**Comment by EMayej** [comment]
@x61 
1. The commits introduced `dotspacemacs-mode-line-theme` to develop are not cherry picked into master.
2. `git clone -b develop ...` is in section `Quick Install` of README.md under the root directory of develop branch

**Comment by dijonkitchen** [comment]
This is a still a problem for users going from `master` to the `develop` branch. Can there be some migration or sensible default if it's not in the `.spacemacs` config?

**Comment by dennismayr** [comment]
@dijonkitchen That did the trick; just tried `develop` after a year, and only this was getting in the way of using it again without breaking my original config.

**Comment by dijonkitchen** [comment]
FYI, I found out recently you can run `SPC f e D` to run a diff between the template (which should have the new configs) with your existing dotspacemacs file.

**Comment by dennismayr** [comment]
@dijonkitchen  I'll try that during the weekend; I see there are new ways to implement older `master` branch options, so I guess it's time to bite the bullet and do some "dotfile refactoring".

**Comment by gitprouser** [comment]
I'm trying to compile all the information I found here. The problem happens when you `git clone` spacemacs repo and run the installer for the first time. At that moment, you are in the `master` branch and installation wouldn't add the modeline configuration. After this point switching to the develop branch under `~/.emacs.d/` won't help. 

Way to resolve this issue is:
0.) Shutdown emacs
1.) Create a bkp of `~/.spacemacs` file
2.) Open emacs and you'll run through the installer again.
3.) Do an ediff between the newly created ~/.spacemacs file and your bkp file. 
4.) Run the tests. You would be fine now.
