### ISSUE TITLE
Add easy way to add SPC bindings in user configuration

### ISSUE THREAD

**Issue by reem** [syl20bnr/spacemacs#10175]
It's possible I'm just missing something obvious, but I've been unable to add new bindings to the SPC menu in my `.spacemacs`, which is pretty sad since it would be really nice to be able to add new commands to it.

**Comment by nixmaniack** [comment]
Do check the documentation at https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#binding-keys. It tells you about `spacemacs/set-leader-keys`.

**Comment by reem** [comment]
This allows you to add direct keybindings and to change your leader key, I want to add bindings to the SPC menu (e.g. SPC-p-something SPC-f-something etc.), not standalone new bindings.

**Comment by nixmaniack** [comment]
> This allows you to add direct keybindings and to change your leader key

Not sure I understand this part. 

Let's say you want to bind `SPC w w` to `'ace-window`, here's how you do it.

```elisp
(spacemacs/set-leader-keys
  "ww" 'ace-window)
```

Later in the docs it talks about it [here](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#reserved-prefix-command-for-user) for user bindings. I hope that's what you're looking for.
