### ISSUE TITLE
Pandoc and org-reftex-citation bibliography incompatibility

### ISSUE THREAD

**Issue by josefschwan** [syl20bnr/spacemacs#10176]
#### Description :octocat:
I am trying to use pandoc export to pdf from org mode and org-reftex-citation in the same file. I can set the bibliography file with "#+BIBLIOGRAPHY: bib_name". However,  pandoc expects the .bib extension to be included (eg. "#+BIBLIOGRAPHY: bib_name.bib"), while org-reftex-citation expects the .bib extension to be omitted (eg. "#+BIBLIOGRAPHY: bib_name"). I can get the functions to work by adding or removing the .bib extension depending on what function I want to run, but I can not get them both to work without having modify the header.

I do not recall having this problem in 'regular' emacs, but I may be misstaken. Am I missing something trivial?

#### Reproduction guide :beetle:
- Make a test bibtex file 'bibfile.bib'.
- Start Emacs
- Open a new org-file in the same directory as bibfile.bib
- Set the bibliography file using "#+BIBLIOGRAPHY: bibfile" header
- Add some sample text
- Try using org-reftex-citation and pandoc export to pdf (,eepL) with the bibliography set by "#+BIBLIOGRAPHY: bibfile"
- Change the header to "#+BIBLIOGRAPHY: bibfile.bib"
- Run org-reftex-citation and pandoc export to pdf again.

*Observed behaviour:* :eyes: :broken_heart: 
Without the .bib extension:

- Citations can be searched and added by org-reftex-citation
- Pandoc export to pdf can not find the bibliography file, giving the following error:

"org-export--dispatch-action: Export aborted
File (bibfile) can not be found"

With the .bib extension:
- org-reftex-citation sees the bibliography command and gives you the search prompt. However, at that point it adds an additional .bib extension making it unable to see the bibliography file. If a search term is entered the following error appears:

"No such BibTeX file bibfile.bib.bib (ignored)
reftex-offer-bib-menu: Wrong type argument: stringp, nil"

Note: I get the same behaviour if I use the absolute path to the bibfile.

*Expected behaviour:* :heart: :smile:
Both org-reftex-citation and pandoc expect the same format in "#+BIBLIOGRAPHY:", or can handle bibliography paths both with and without the .bib extension. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git pandoc deft
      (org :variables org-projectile-file "TODOs.org")
      (latex :variables latex-enable-auto-fill t latex-enable-folding t)
      bibtex
      (spell-checking :variables enable-flyspell-auto-completion nil))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
```

**Comment by fleimgruber** [comment]
The org-ref [documentation](https://github.com/jkitchin/org-ref/blob/master/org-ref.org#references) uses the org-mode link `bibliography:bib_name.bib` to specify the .bib file.  Since the docs do not mention `#+BIBLIOGRAPHY` I assume using the link is the recommended way to do this.
