### ISSUE TITLE
Can you add "--depth" to the user's installation command?

### ISSUE THREAD

**Issue by yuzumx** [syl20bnr/spacemacs#10187]
Hello:
First, I'm sorry for my poor English

You started to maintain this configuration very early, so a large number of git commit records have been accumulated.
This does not matter, but it can cause problems for those of us who "just want to use"  and with very slow internet speeds.
Like me, it can take up to a quarter of an hour to clone your configuration on a new computer (One of the reasons is that  the Internet is blocked).

So can you add `--depth` parameter to the install command ?
This will greatly improve the experience of those with slow internet speeds.
Or, can you add suggestions for these users?
Really not everyone has a broadband network, and not every spacemacs user knows git very well.

Data:
```
$ git clone https://github.com/syl20bnr/spacemacs ~/spacemacs
$ du -sh ~/spacemacs
54M           spacemacs

$ git clone --depth 1 https://github.com/syl20bnr/spacmeacs ~/spacemacs
$ du -sh ~/spacemacs
19M          spacemacs
```

Thank you.

**Comment by smile13241324** [comment]
@yuzumx I have merged the PR from @pedrocunial would you mind to double check if this would be enough to make this more clear for people with limited internet connections and close the ticket when it is ok this way?

**Comment by Compro-Prasad** [comment]
The `--depth` option should be provided as the default one and before the one with `--depth`. If they want to contribute they have the option to download the full repo. Generally it isn't required for every user. I could open a PR if you like my opinion.
