### ISSUE TITLE
ggtags-mode part on powerline is garbled

### ISSUE THREAD

**Issue by miraclemore** [syl20bnr/spacemacs#10184]
#### Description :octocat:
ggtags-mode powerline is garbled

#### Reproduction guide :beetle:
- Start Emacs
- Enable ggtags-mode

*Observed behaviour:* :eyes: :broken_heart:
powerline garbled for ggtags-mode
![screenshot from 2018-01-19 02-41-26](https://user-images.githubusercontent.com/3292065/35115414-0c08358a-fcc3-11e7-9f47-032b554e0842.png)

*Expected behaviour:* :heart: :smile:
ggtags-mode show correct

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.50.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e11f7bad)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion
      (better-defaults :variables better-defaults-move-to-beginning-of-code-first t)
      (treemacs :variables treemacs-use-filewatch-mode t treemacs-use-collapsed-directories 3)
      ibuffer emacs-lisp git markdown org asm c-c++ gtags python imenu-list spell-checking syntax-checking miraclemore)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by myrgy** [comment]
I have the same issue on ArchLinux. Fedora 27 - seems to be fine.

**Comment by gatto73** [comment]
I have the same problem on Windows 10. With the same configuration and Emacs version on Ubuntu 18.04 I don't see the problem.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6a724e416)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(org helm neotree emacs-lisp auto-completion markdown html csv
     (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
     (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion nil spell-checking-enable-auto-dictionary nil)
     (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
     (python :variables python-test-runner 'pytest)
     gtags common-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2
