### ISSUE TITLE
Separators are broken on the development branch when using emacsclient

### ISSUE THREAD

**Issue by robbert-vdh** [syl20bnr/spacemacs#10181]
#### Description
Separators are broken when using emacsclient as of commit 0f646b884dd9164f923839ed59898c56020e34cc.

#### Reproduction guide
- Start Emacs through emacsclient (`emacsclient -a '' -nc`)

*Observed behaviour:*
![emacsclient](https://i.imgur.com/zolqRBR.png)

Separators show up as big, square glyphs. The same happens when using the default settings.

*Expected behaviour:*
![Regular Emacs](https://i.imgur.com/nmg0OoB.png)

The separators show up fine when starting Emacs normally (i.e. when not using the emacsclient).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b82c12404)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((ivy :variables ivy-enable-advanced-buffer-information t)
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup nil auto-completion-tab-key-behavior 'cycle)
 csharp colors csv docker emacs-lisp git gpu graphviz gtags
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell" hindent-reformat-buffer-on-save t)
 html javascript
 (latex :variables latex-enable-folding t)
 markdown nginx nlinum
 (org :variables org-enable-bootstrap-support t)
 pdf-tools php
 (python :variables python-enable-yapf-format-on-save t)
 ranger
 (rust :variables rust-format-on-save t)
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts
 (spell-checking :variables flyspell-default-dictionary "nl" spell-checking-enable-by-default nil)
 (treemacs :variables treemacs-silent-filewatch t treemacs-silent-refresh t)
 typescript syntax-checking version-control yaml debug
 (languagetool :variables langtool-default-language "nl" languagetool-show-error-on-jump t langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*"))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

The bahaviour is the same when doing a clean install with default settings from the regular development branch.

**Comment by Isimoro** [comment]
Same Problem here. A few observations:

The slant separator breaks scaling and produces the placeholder character, the wave separator does neither, powerline is simply displayed without a separator.
If the configuration is reloaded via `SPC f e R` the separators go back to normal and stay so in any client frame opened later.

**Comment by jsoo1** [comment]
Same problem here, though `dotspacemacs/sync-configuration-layers` does not fix the issue in terminal.

**Comment by jcf** [comment]
Workaround from #10261:

> I've added this to my `dotspacemacs/user-config` and my mode line fixes itself automatically.

```
(spacemacs|do-after-display-system-init
 (spacemacs-modeline/init-spaceline))
```

**Comment by syl20bnr** [comment]
duplicate of https://github.com/syl20bnr/spacemacs/issues/10261

**Comment by bersace** [comment]
I confirm this here too. `SPC f e R` works but not `init-spaceline`.

**Comment by internaught** [comment]
Same behavior here, powerline separators disappear after a reload using `SPC f e R`

**Comment by bennofs** [comment]
The problem here is that `powerline-height` is set incorrectly (it's 0). The commit that regressed this is 378392e, and this happens only with emacsdaemon because font measurements do not work before the graphics system has been initialized and the computation of `powerline-height` does do font measurements.

**Comment by bennofs** [comment]
What is the status on this? Any idea on how to fix this? 

Right now, I need to hardcoded powerline-height myself which sucks...

**Comment by jerome-diver** [comment]
same problem here... how to fix this bug please ?

**Comment by smile13241324** [comment]
I have just merged the fix from @bennofs, please check if this solves your issue on develop.
