### ISSUE TITLE
Clojure layer: Symbol Highlight Transient state broken by '>' in symbol name

### ISSUE THREAD

**Issue by laynor** [syl20bnr/spacemacs#10186]
#### Description :octocat:
greater than (>) character breaks '*' in clojure mode

#### Reproduction guide :beetle:
- Start Emacs
- open a clojure file
- type
```clojure
foo->bar
foo->bar
```
- place the cursor on the first occurrence of `foo->bar`
- type '*' in normal mode (evil)

*Observed behaviour:* :eyes: :broken_heart:
Symbol Highlight Transient State buffer pops up, 0 occurrences reported.

*Expected behaviour:* :heart: :smile:
Should report 2 occurrences and move the cursor to the next one.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. eae6497b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(erlang yaml rust vimscript shell-scripts elm elixir helm auto-completion better-defaults
        (python :variables python-test-runner
                '(nose pytest))
        latex
        (ibuffer :variables ibuffer-group-buffers-by 'projects)
        (c-c++ :variables c-c++-enable-clang-support t)
        clojure java javascript react html emacs-lisp scheme git github markdown neotree org lua colors floobits rtags syntax-checking
        (version-control :variables version-control-diff-tool 'diff-hl))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by kommen** [comment]
@Miciah Your solution makes `*` work. Hard to tell though, if it also breaks anything else. Maybe it would make sense to only set `ahs-include` to this in clojure buffers?
