### ISSUE TITLE
Documentation to customize `all-the-icons` modeline

### ISSUE THREAD

**Issue by maikol-solis** [syl20bnr/spacemacs#10182]
Hi, 
I would like to know if there is some documentation to customize `all-the-icons` modeline. I liked it, and I'm a sure that have many cool features. But, I can't see all its potential due to the default configuration and my own ignorance to change them. 

I like to use Emacs, but I'm a newbie when I have to hack the .spacemacs file. 

For a normal user, it's enough to know if it's possible add or remove segments or change the height. 
I don't know if there are hidden parameters additionally to the already documented, 

`(setq dotspacemacs-mode-line-theme '(all-the-icons :separator 'slant))`

Thanks for your help.

**Comment by nixmaniack** [comment]
You should be able to use segment toggles since it's based on spaceline.

**Comment by maikol-solis** [comment]
Thanks for the reply @nixmaniack . Could you point me how to use those toggles and how to enable them in my .spacemacs? I appreciate your help.  

Best.

**Comment by nixmaniack** [comment]
Docs from spaceline: https://github.com/TheBB/spaceline#turning-segments-on-and-off

If you do `SPC SCP ` and search for `spaceline-toggle-all-the-icons-*` you would see all the available toggles. You can then add them in your `~/.spacemacs` under `dotspacemacs/user-config`. 

Note that some of the segments depend on extra packages such as weather - not sure if that's documented at upstream.
