### ISSUE TITLE
Layouts are not accessible with `SPC l L`

### ISSUE THREAD

**Issue by sjsrey** [syl20bnr/spacemacs#10198]
### Description
Layouts are not accessible with `SPC l L`

#### Reproduction guide
- Start Emacs
- `SPC l L`

*Observed behavior:*

Getting helm related error message (in backtrace)

*Expected behavior*
A list of previously saved layouts to select form

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f3d4bdb3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults bibtex deft git helm emacs-lisp latex markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 ranger spell-checking syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace
```
Debugger entered--Lisp error: (wrong-number-of-arguments (lambda (buffer) "Display the Helm window respecting `helm-position'." (let ((display-buffer-alist (list spacemacs-helm-display-help-buffer-regexp spacemacs-helm-display-buffer-regexp))) (helm-default-display-buffer buffer))) 2)
  spacemacs//display-helm-window("*helm-mode-persp-load-state-from-file*" nil)
  helm-display-buffer("*helm-mode-persp-load-state-from-file*" noresume)
  helm-internal((((name . "persp-load-state-from-file") (header-name . #[257 "\211\30!P\207" [helm-find-files-doc-header substitute-command-keys] 4 "\n\n(fn NAME)"]) (init . #[0 \211\211\207" [helm-ff-auto-update-initial-value helm-ff-auto-update-flag helm-ff--auto-update-state] 3]) (candidates . #[0 "\303\304\n!?\205\n
```

**Comment by duianto** [comment]
A recent helm update added a second argument to a function that Spacemacs uses.
This seems to break all helm commands.
There's a PR that fixes it: Fix completely broken helm #10196

**Comment by WarFox** [comment]
Is this in any way related to this? #10193

**Comment by duianto** [comment]
@WarFox This issue was probably just related to the helm issue, since `SPC l L` opens the helm buffer:
`HELM Persp Load State From File`

The helm issue has been fixed on the develop branch by this commit:
spacemacs-completion: comply w/ new helm-display-buffer signature https://github.com/syl20bnr/spacemacs/commit/f93d1a1afd6cc9c5bd450614ccd2a8e88734bea8

@sjsrey If `SPC l L` is working for you again, then you can close this.

**Comment by R0dri** [comment]
@duianto Thanks! I just manually applied the commit to my spacemacs and now it works!

**Comment by Miciah** [comment]
https://github.com/syl20bnr/spacemacs/commit/08df5f97fe53488904a1962b30c968f46e4f0f7f should have fixed this on the master branch.  Can this issue be closed?
