### ISSUE TITLE
Rust: How to enter input to stdin when running program

### ISSUE THREAD

**Issue by kbdluv** [syl20bnr/spacemacs#10194]
I'm following the first example in the Rust Book that uses `stdin`, which goes as follows (code not important, it just reads from stdin):

```rust
use std::io;

fn main() {
    println!("Guess the number!");

    println!("Please input your guess.");

    let mut guess = String::new();

    io::stdin()
        .read_line(&mut guess)
        .expect("Failed to read line");

    println!("You guessed: {}", guess);
}
```

When I run it with `, q` (`spacemacs/rust-quick-run`), Spacemacs opens a window with the running program, correctly outputting this:

```
Guess the number!
Please input your guess.
```

I then move focus to this window. It's in normal mode, so I type `i` to go to insert mode, and I get the message:

```
i is undefined
```

Which leaves me with no way of interacting with the program.

Is this a bug? How should I proceed in order to interact with a program I just compiled and ran from Spacemacs using the `rust` layer? Thanks!

**Comment by nightire** [comment]
see this: https://github.com/kwrooijen/cargo.el/issues/29

if you try to capture stdin, use eshell (or other variants) instead.
