### ISSUE TITLE
Switching to a project with `SPC p l` does not switch to a new layout

### ISSUE THREAD

**Issue by semihalf-dubiel-michal** [syl20bnr/spacemacs#10193]
#### Description :octocat:
Switching to a project with `SPC p l` does not switch to a new layout.

This was first introduced by this commit: https://github.com/syl20bnr/spacemacs/commit/4b111f7701ffea8e724666471a64867fe0c7af22

Probably related issue #10177 with PR #10188 does not fix this issue with switching to a project in a new layout. The problem still remains.

#### Reproduction guide :beetle:
- Start Emacs
- Try to switch to a project using `SPC p l`

*Observed behaviour:* :eyes: :broken_heart:
The project is opened in the 'Default' layout.

*Expected behaviour:* :heart: :smile:
The project should be opened in a new layout, not the 'Default'.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f72f954)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript html markdown ivy auto-completion emacs-lisp git
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (python :variables python-test-runner 'pytest)
            (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
            gtags pandoc)
```
- System configuration features: JPEG SOUND GPM DBUS NOTIFY LIBSELINUX GNUTLS LIBXML2 ZLIB MODULES

**Comment by WarFox** [comment]
I'm having this issue as well on macOS with emacs 25.3.1
It's affecting my workflow now

**Comment by chrismcg** [comment]
This is still happening for me on latest develop with `ivy`, it seems to be working ok if I use `helm` instead.

**Comment by semihalf-dubiel-michal** [comment]
That's right, the issue is with Ivy only. The commit that has introduced this (mentioned in the description of the issue) touches only the Ivy related functions.

**Comment by myrgy** [comment]
Seems to be duplicate #10240

**Comment by nixmaniack** [comment]
Could you please test the PR https://github.com/syl20bnr/spacemacs/pull/10247? I had mistakenly removed the advice which creates/switches the perspectives.

**Comment by semihalf-dubiel-michal** [comment]
@nixmaniack I have tested the PR #10247 and it fixes the issue.

**Comment by semihalf-dubiel-michal** [comment]
Closing as #10247 has fixed it.
