### ISSUE TITLE
Company Mode RET Completion Can Be Annoying

### ISSUE THREAD

**Issue by trishume** [syl20bnr/spacemacs#102]
There should be a way to switch auto-completion to use `TAB` only instead of `RET` only.

For days I've been using `RET` for auto-completion with no problems. But this past 5 minutes I discovered something that makes me want to switch to `TAB`

Sometimes there are common constructs that come before newlines, and in Ruby these are words.
With company-mode at least typing `5.times do` and hitting `RET` will get you something like `5.times downcase`, which is extremely annoying.

The problem is that `TAB` is used by indentation, yasnippet and completion depending on the context. These contexts are largely unambiguous, it is just a question of writing the right function that in the correct order:

1. Expands a snippet if there is one
2. Completes if there is completion available
3. Indents the line

I'm going to try and write this function, but until then this will be highly annoying.

**Comment by syl20bnr** [comment]
I close this old issue.
If it is still relevant you can re-open it.

**Comment by trishume** [comment]
It can still be annoying, but it is annoying me less since I added the snippet to make it not pop up for certain keywords.

**Comment by TheBB** [comment]
I had the same problem in LaTeX, but I was able to fix it by setting `auto-completion-return-key-behavior` to nil. `C-l` still performs the same action as `RET` used to do, and I find that a better binding anyway. Is there a reason this remains open?

**Comment by TheBB** [comment]
Closing, since IMO the configuraiton variables for the auto-completion layer solve this problem. We can discuss defaults, of course.
