### ISSUE TITLE
How to configure easy-hugo to work in spacemacs

### ISSUE THREAD

**Issue by bimawa** [syl20bnr/spacemacs#10204]
I found a easy-hugo mode for hugo site generator, and can't work with it. Buttons not handled. May be I want read something about binding or layout configuration?
I create cross [issue](/masasam/emacs-easy-hugo/issues/35)

**Comment by bimawa** [comment]
Get on research

**Comment by bimawa** [comment]
Get on research

**Comment by masasam** [comment]
@bimawa .
There is some evil-mode and key binding in spaceemacs.
If you turn evil-mode off, it will work.
Are you ordering me to make it work like evil-mode?
