### ISSUE TITLE
.html.md files should be markdown-mode

### ISSUE THREAD

**Issue by bostonaholic** [syl20bnr/spacemacs#10216]
#### Description :octocat:
`.html.md` files should be using `markdown-mode` but instead are using `html-mode`.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file with the extension `.html.md`

*Observed behaviour:* :eyes: :broken_heart:
The major mode is `html-mode`.

*Expected behaviour:* :heart: :smile:
The major mode should be `markdown-mode`.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults clojure docker emacs-lisp git github helm html javascript markdown nginx org react
                 (ruby :variables ruby-version-manager 'rbenv)
                 ruby-on-rails spell-checking sql syntax-checking yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Miciah** [comment]
Does https://github.com/jrblevin/markdown-mode/commit/b92f00d10e2582028d4306d3be8730add58e9fa1 resolve this issue for you?

**Comment by bostonaholic** [comment]
It must have. I'm no longer having this issue. Thanks for checking in @Miciah!
