### ISSUE TITLE
[windows install sapcemacs] about the README.md file's `emacs --insecure` 

### ISSUE THREAD

**Issue by Xmagicer** [syl20bnr/spacemacs#10213]
in the readme file ,it says using `emacs --insecure`  on windows, it should be `emacs-25.3.exe --insecure`. People may feel puzzle because in windows's emacs's bin directory there are two files named `emacs.exe` and `exmacs-25.3.exe`. And I don't konw what the two files differ.

**Comment by fleimgruber** [comment]
First, this depends on the installed Emacs distribution.  Second, at least with the GNU Windows release, the `emacs.exe` and `emacs-25.3.exe` are identical, so I don't think the README should make a distinction here.
