### ISSUE TITLE
Emacs freeze when searching on the file.

### ISSUE THREAD

**Issue by zer09** [syl20bnr/spacemacs#10215]
#### Description :octocat:
Probably related to issue #9220 and #9887.

The problem is that using ```/``` for searching emacs freeze. And the subject
file has just 500 line of html tags.

Just experience this when using the ```all-the-icons``` theme for the mode-line.
And adding the ```(spaceline-all-the-icons--setup-anzu)``` to show the anzu icon.
But removing the ```(spaceline-all-the-icons--setup-anzu)``` fix the issue.

I dont know if it is a upstream issue. Please tell me if I should open an issue
to https://github.com/domtronn/spaceline-all-the-icons.el.

#### Reproduction guide :beetle:
- Start Emacs with the ```(spaceline-all-the-icons--setup-anzu)``` on the config.
- Open a file.
- Then start searching using the ```/```.

*Observed behaviour:* :eyes: :broken_heart:
Emacs freeze and need to manually kill.

*Expected behaviour:* :heart: :smile:
Emacs should not freeze and highlight all the result.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9c585370)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((fasd)
 (imenu-list)
 (spell-checking :variables spell-checking-enable-by-default nil)
 (syntax-checking)
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 (ycmd)
 (rebox :variables rebox-enable-in-text-mode t)
 (ranger :variables ranger-enter-with-minus t ranger-show-hidden t ranger-max-preview-size 1)
 (colors)
 (c-c++ :variables c-c++-enable-clang-support t c-c++-enable-rtags-support t)
 (theming)
 (keyboard-layout :variables kl-layout 'dvorak)
 (git)
 (version-control :variables version-control-diff-tool 'git-gutter+ version-control-diff-side 'left)
 (systemd)
 (shell :variables shell-default-shell 'eshell)
 (protobuf)
 (go :variables go-use-gometalinter t gofmt-command "goimports" go-tab-width 4 flycheck-gometalinter-fast t flycheck-gometalinter-deadline "30s" flycheck-gometalinter-enable-linters
     '("testify" "safesql"))
 (html)
 (javascript :variables javascript-disable-tern-port-files nil)
 (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t)
 (shell-scripts)
 (sql :variables sql-capitalize-keywords t)
 (yaml)
 (lua)
 (ivy :variables ivy-extra-directories nil ivy-enable-advanced-buffer-information t)
 semantic emacs-lisp markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

### Backtrace :paw_prints:

A couple of bactraces.
```
#Debugger entered--entering a function:
* eval((spaceline-ml-all-the-icons))
  redisplay_internal\ \(C\ function\)()
  read-string("/" #("location" 0 8 (face shadow)) evil-ex-search-history)
  evil-ex-start-search(forward nil)
  evil-ex-search-forward(nil)
  funcall-interactively(evil-ex-search-forward nil)
  call-interactively(evil-ex-search-forward nil nil)
  command-execute(evil-ex-search-forward)
```

```
Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
  read-string("/" #("console.log" 0 11 (face shadow)) evil-ex-search-history)
  evil-ex-start-search(forward nil)
  evil-ex-search-forward(nil)
  funcall-interactively(evil-ex-search-forward nil)
  call-interactively(evil-ex-search-forward nil nil)
  command-execute(evil-ex-search-forward)

```
```

Debugger entered--entering a function:
* evil-ex-hl-update-highlights-scroll(#<window 12 on appointment.html> 1780)
  redisplay_internal\ \(C\ function\)()
  read-string("/" #("location" 0 8 (face shadow)) evil-ex-search-history)
  evil-ex-start-search(forward nil)
  evil-ex-search-forward(nil)
  funcall-interactively(evil-ex-search-forward nil)
  call-interactively(evil-ex-search-forward nil nil)
  command-execute(evil-ex-search-forward)
```

**Comment by zer09** [comment]
Now on the latest commit, emacs will freeze even anzu is not enabled.

**Comment by CeleritasCelery** [comment]
I would still report this upstream since it still seems tied to that package.

**Comment by syl20bnr** [comment]
Possible duplicate of https://github.com/syl20bnr/spacemacs/issues/9220
