### ISSUE TITLE
[feature request]How could I clear the *spacemacs* home buffer?

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#10220]
I want a fresh Recent files and projects list when I start the spacemacs and show a clean *spacemacs* home buffer, because there are many wrong list in it.
but the buffer seems read-only

![image](https://user-images.githubusercontent.com/7722295/35209961-4718b7ba-ff8b-11e7-8a51-e0471b6be05c.png)

**Comment by zer09** [comment]
I think you want ```projectile-invalidate-cache (SPC p I)```

**Comment by hhxjzyr** [comment]
@zer09 Thank you very much! 
Actually, I tried `(SPC p I)`  but it didn't work 

And I found them in  `.emacs.d/.cache/recentf`
Thanks again!

**Comment by zer09** [comment]
Your welcome 😄 .

You may also close this issue if it already solved.
