### ISSUE TITLE
error at startup about existing elpa packages

### ISSUE THREAD

**Issue by pprw** [syl20bnr/spacemacs#10227]
I am trying spacemacs without using my previsous emacs configuration. I use `HOME=~/spacemacs emacs` to start spacemacs.

I get a lot of errors about packages I used: tablist for example. They are installed from debian unstable repository which provides some packages directly from elpa.

I don't want to remove these packages (I use them with emacs). I want to be able to use emacs and spacemacs side by side.

*Spacemacs should either use my system packages or download everything from elpa and keep them separate from the rest of the system.*

```
Found 7 orphan package(s) to delete...
--> deleting tablist... [1/7]

Warning (initialization): An error occurred while loading ‘/home/ppr/spacemacs/.emacs.d/init.el’:

error: Package ‘tablist-0.70’ is a system package, not deleting
```

**Comment by syl20bnr** [comment]
You need to add your packages to `dotspacemacs-additonal-packages`. 
See https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org#why-are-packages-installed-with-package-install-automatically-deleted-by-spacemacs-when-it-boots
