### ISSUE TITLE
Add convenient key bindings to navigate Spacemacs homepage

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1022]
Currently we have to use editing commands to navigate items on the homepage. It would be more convenient if we create common key bindings for navigating the home buffer. For example:

- `TAB` to move to next item. With a prefix argument N, move forward N items.
- `S-TAB` to move to previous item. With a prefix arugment N, move backward N items.
- `r` to jump to recent file section.
- `p` to jump to project section.

**Comment by CarlQLange** [comment]
Sounds good, will look at this.

**Comment by danielwuz** [comment]
How about using [ace-link](https://github.com/abo-abo/ace-link) in this case? with just two or three key strokes, we can jump to anywhere.

**Comment by CarlQLange** [comment]
https://github.com/syl20bnr/spacemacs/compare/syl20bnr:develop...CarlQLange:feature-startupify-shortcuts?expand=1

This patch partially works - `p`, `r`, and `b` work to jump to the lists, and `TAB` and `S-TAB` partially work to jump between buttons.

Have a look! I'm not sure what to do re: the tab behaviour :)

**Comment by tuhdo** [comment]
It didn't work. See the old issue: https://github.com/syl20bnr/spacemacs/issues/807

**Comment by CarlQLange** [comment]
@danielwuz Ace-link doesn't appear to work out of the box with our links. I've considered patching and pushing a fix but haven't gotten much further than that. Their `*help*` buffer jump should work out of the box but didn't appear to :)

**Comment by tuhdo** [comment]
@CarlQLange Hmm, the problem is that `(goto-char (next-overlay-change (point)))` always stops at the beginning of the first button, but at the space in between buttons. I guess it is because the space is part of later buttons. If so, we must remove the spaces to make it work properly.

**Comment by CarlQLange** [comment]
Actually, I think it's because `next-overlay-change` will also stop at the end of the overlay (which makes sense). I think if we do this with a combination of `next-overlay-change` and inspecting the properties at point, and if it's not a button, do `next-overlay-change` again. I'll get to this tonight or tomorro morning :)

**Comment by tuhdo** [comment]
@CarlQLange I think it's easier if we convert all the current buttons into a proper text widget button and  reuse all the widget navigation commands. Yes, we can get the button at point and check but it will be cleaner if we use proper buttons and later we can customize more (i.e. give buttons box similar to the ones you see in `magit-log` for tags, not the ugly gray button in Help buffer).

@syl20bnr what do you think? Should we replace?

**Comment by CarlQLange** [comment]
Yeah, I'd like to have @syl20bnr's approval, but I think I agree :)

**Comment by syl20bnr** [comment]
Let's go with widgets :-)

**Comment by CarlQLange** [comment]
Cool, I can get on this tonight or tomorrow!

**Comment by syl20bnr** [comment]
Great !

**Comment by CarlQLange** [comment]
While we're here, @syl20bnr can you have a look at where I put the keybindings for this (in the `add-hook` at the bottom)? I don't like 'em there, but I couldn't find somewhere better to put them. https://github.com/syl20bnr/spacemacs/compare/syl20bnr:develop...CarlQLange:feature-startupify-shortcuts

**Comment by syl20bnr** [comment]
@CarlQLange For now it's ok to put them in the `when` block where the buttons are added.

**Comment by tuhdo** [comment]
@CarlQLange You may also interested in making the link pretty buttons. For example (I assume you use `magit`, so you should have this face):

```elisp
(widget-create `(link :tag ,(propertize "Test button" 'face 'magit-log-head-label-remote)
                      :button-prefix ""
                      :button-suffix ""
                      :button-face nil
                      :format ""
                      :help-echo "This is a button"
                      :action nil
                      'test))
```

Now you have the same buttons as the only you see in Magit. Of course, we should create our own button faces for Spacemacs buttons.

**Comment by CarlQLange** [comment]
Okeydoke, widget buttons and keyboard shortcuts for things. :) https://github.com/syl20bnr/spacemacs/pull/1065

**Comment by stegrams** [comment]
I m learning spacemacs and I accidentally discover these bindings but I can find them on major mode describe.
My steps are:
```SPC-h-d-m```
```/^p ``` this results ```undo-tree-visualize-undo```
```/^r ``` ```"^r ": pattern not found```
