### ISSUE TITLE
flycheck-gometalinter doesn't work

### ISSUE THREAD

**Issue by lsytj0413** [syl20bnr/spacemacs#10234]
#### Description :octocat:
flycheck-gometalinter doesn't work

#### Reproduction guide :beetle:
- Start Emacs
- Open *.go file
- import a package dosen't used

*Observed behaviour:* :eyes: :broken_heart:
nothing error report

*Expected behaviour:* :heart: :smile:
flycheck report an error

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.50.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9c58537)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((ivy :variables ivy-extra-directories nil)
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for org)
 (better-defaults :variables better-defaults-move-to-end-of-code-first t)
 emacs-lisp git markdown org
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (python :variables python-sort-imports-on-save t)
 semantic
 (go :variables go-tab-width 4 go-use-gometalinter t)
 protobuf ranger gtags ibuffer sql
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 900)
 graphviz plantuml docker
 (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
 liter ycmd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by zer09** [comment]
What is the output if you do ```SPC e v```?

**Comment by lsytj0413** [comment]
@zer09 
`
Syntax checkers for buffer auth.go in go-mode:

  gometalinter
    - may enable: yes
    - executable: Found at /home/soren/workspace/golang/lib/bin/gometalinter

  go-gofmt (disabled)
    - may enable: yes
    - executable: Found at /usr/bin/gofmt

  go-golint (disabled)
    - may enable: yes
    - executable: Found at /home/soren/workspace/golang/lib/bin/golint

  go-vet (disabled)
    - may enable:  yes
    - predicate:   t
    - executable:  Found at /usr/bin/go
    - go tool vet: present

  go-build (disabled)
    - may enable: yes
    - predicate:  t
    - executable: Found at /usr/bin/go

  go-test (disabled)
    - may enable: yes
    - predicate:  nil
    - executable: Found at /usr/bin/go

  go-errcheck (disabled)
    - may enable: yes
    - predicate:  t
    - executable: Found at /home/soren/workspace/golang/lib/bin/errcheck

  go-unconvert
    - may enable: yes
    - predicate:  t
    - executable: Found at /home/soren/workspace/golang/lib/bin/unconvert

  go-megacheck
    - may enable: yes
    - executable: Found at /home/soren/workspace/golang/lib/bin/megacheck

Flycheck Mode is disabled. Use SPC u M-x flycheck-disable-checker to enable
disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20180116.147)
Emacs version:    25.3.50.2
System:           x86_64-pc-linux-gnu
Window system:    x
`

**Comment by zer09** [comment]
Does it remove the unused package, upon file save?

**Comment by lsytj0413** [comment]
I don't known what you exactly mean, the package list i remove is:
`
                                  magit
                                  magit-gh-pulls
                                  magit-gitflow
                                  org-projectile
                                  evil-mc
                                  realgud
                                  evil-args
                                  evil-ediff
                                  evil-exchange
                                  evil-unimpaired
                                  evil-indent-plus
                                  volatile-highlights
                                  smartparens
                                  holy-mode
                                  skewer-mode
                                  rainbow-delimiters
                                  highlight-indentation
                                  vi-tilde-fringe
                                  eyebrowse
                                  org-bullets
                                  smooth-scrolling
                                  org-repo-todo
                                  org-download
                                  org-timer
                                  livid-mode
                                  git-gutter
                                  git-gutter-fringe
                                  evil-escape
                                  leuven-theme
                                  gh-md
                                  evil-lisp-state
                                  spray
                                  lorem-ipsum
                                  symon
                                  ac-ispell
                                  ace-jump-mode
                                  auto-complete
                                  auto-dictionary
                                  clang-format
                                  define-word
                                  google-translate
                                  disaster
                                  epic
                                  fancy-battery
                                  org-present
                                  orgit
                                  orglue
                                  spacemacs-theme
                                  helm-flyspell
                                  flyspell-correct-helm
                                  clean-aindent-mode
                                  helm-c-yasnippet
                                  ace-jump-helm-line
                                  helm-make
                                  smeargle
                                  ido-vertical-mode
                                  flx-ido
                                  company-quickhelp
                                  counsel-projectile
                                  window-purpose
                                  ivy-purpose
                                  helm-purpose
                                  spacemacs-purpose-popwin

`

**Comment by zer09** [comment]
I mean the imported package on the ```go``` file.

**Comment by lsytj0413** [comment]
example:
`
package main

import (
	"fmt"
	"os"
)

func main() {
}
`

there is no error report.

**Comment by zer09** [comment]
hmm I got just used to that ```goimports``` handling it. Upon save the ```fmt``` and ```os``` package is automatically remove.

I don't if you like it, but you can add ```gofmt-command "goimports"``` in your ```go variables``` config.

**Comment by lsytj0413** [comment]
I found the error is because i disable syntax-checking by code :joy: :
`syntax-checking-enable-by-default t`

but the unused import is not report by flycheck still exists.

**Comment by zer09** [comment]
Ohh based on [#supported-linters](https://github.com/alecthomas/gometalinter#supported-lintersl), ```goimports``` is disabled by default.

Try to add this in your ```go variables```, ```flycheck-gometalinter-enable-linters '("goimports")```.

**Comment by lsytj0413** [comment]
` 
(setq flycheck-gometalinter-enable-linters '("golint" "goimports"))
`
I have add this code, but it still doesn't work. Now i use **gofmt goimports** to process the import.

**Comment by zer09** [comment]
I think you should add that to your ```dotspacemacs/layers```
```
     (go :variables
         go-tab-width 4
         go-use-gometalinter t
         flycheck-gometalinter-enable-linters '("goimports"))

```

Here is the screen shot.
![screenshot from 2018-01-24 10-40-52](https://user-images.githubusercontent.com/780780/35311859-b867b434-00f3-11e8-903a-618827002916.png)

**Comment by robbyoconnor** [comment]
Anyone come up with a solution?

**Comment by robbyoconnor** [comment]
Okay -- I found a solution, you need to manually set the GOPATH environment variable, do this in `dotspacemacs/user-config` like so: `(setenv "GOPATH" "/home/rob/gocode")`

**Comment by chrismcg** [comment]
@robbyoconnor I solved it by adding this to my `dotspacemacs/user-config`

```
  ;; setup GOPATH
  (exec-path-from-shell-copy-env "GOPATH")
```

**Comment by robbyoconnor** [comment]
@chrismcg I wonder if we should add this to the go layer?

**Comment by chrismcg** [comment]
@robbyoconnor I'm just messing around with Go at the moment so don't know enough to say whether that would be a good idea in general.
