### ISSUE TITLE
Ido keybinds that is still working and needs to be fixed

### ISSUE THREAD

**Issue by longtomjr** [syl20bnr/spacemacs#10237]
There is still issues regarding people running into ido when using emacs keybinds. The purpose of this post is to just document the ido keybindings that is still running rampant.  

### Ido keybindings in develop:
 - `C-x d` - `ido-dired`
 - `C-x C-w` - `ido-write-file`
 - `C-x k` - `ido-kill-buffer`
 - `C-x 4` - `switch-to-buffer-other-window` and in turn `ido-switch-buffer-other-window`
 - `C-x 4 f` and `C-x 4 C-f` - `ido-find-file-other-window`
 - `C-x C-v` - `ido-find-alternate-file`
 - a number of keybinds for `ido-find-file-other-frame` including `SPC F f`

What the best way might be to fix it is up in the air. Remove the bindings completely (to dissalow use), to show in the minibuffer what the spacemacs binding is for this feature (to encourage changing to spacemacs style), or fix the bindings to call the correct helm command. Please post if you run into any ido keybinds still, and I will add them to the list, I will also be going through ido commands and see what they are bind to since `SPC h d b` does not list the correct keybinds

For more context see #1126

**Comment by quicknir** [comment]
Discussed briefly in gitter; @longtomjr suggested I post my thoughts here:

Generally, spacemacs does not bind, or even change bindings, in any of the native emacs prefixes (C-c, C-x, C-w...). All three suggested solutions involve messing around with those bindings. Maybe we could add a section to the FAQ (https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org), "I'm coming from regular emacs. How do I do X idiomatically?". 

Another possibility would be to have a "spacemacs tutor mode". It could basically operate by adding advice before functions that "shouldn't" really be used in spacemacs. The function would basically error out, telling the user what function to use instead. However, this is more work, I'm not sure who really wants to do it (it's pretty easy to do though).

As far as the solutions go:

- ido-dired: just use `SPC f f` and hit enter on a directory
- ido-write-file `SPC f c` to copy a file
- ido-kill-buffer `SPC b b` and then `M-S-d` to delete whatever you want (can kill multiple in helm via marking)
- switch-to-buffer-other-window and... `SPC b b` and then `C-c o` (in helm)
- ido-find-file-other-window `SPC f f` and `C-c o` as above
- ido-find-alternate-file `, g a`; this is major mode dependent
- ido-find-file-other-frame I don't use frames. But this one should actually be fixed; something under spc `SPC F f` should be using helm. I think this stuff is pretty new.

**Comment by syl20bnr** [comment]
> Generally, spacemacs does not bind, or even change bindings, in any of the native emacs prefixes (C-c, C-x, C-w...)

This. We want that regular Emacs key bindings under `C-x/C-c` still work like vanilla Emacs or that they work as the authors of a package have intended. All Spacemacs key bindings are scoped under `SPC/M-m` prefix key. So we want people to get into the habits to use this prefix and not to comfort them into their old habits with `C-x/C-c` (although Spacemacs design allow this, which is a  feature).

**Comment by quicknir** [comment]
@syl20bnr I agree. But @longtomjr is interested in perhaps a layer/mode, "spacemacs-strict-tutor" perhaps, that would actually help enforce this by giving informative error messages when C-x/C-c bindings are used. E.g. you try to do C-x d and instead you get "Error: use SPC f f and select directory". What do you think of that specifically?

**Comment by syl20bnr** [comment]
I like it.

**Comment by bmag** [comment]
Upstream helm now disables ido-mode and throws an error when ido-mode and helm-mode are enabled together, so I'm just going to disable ido-mode. Means users won't run into ido bindings anymore (will get generic helm interface instead).
