### ISSUE TITLE
`SPC l [0..9]` doesn't create new layouts / perspectives

### ISSUE THREAD

**Issue by edran** [syl20bnr/spacemacs#10238]
#### Description :octocat:
Cannot create new layouts with `SPC l [0..9]`.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC l 2`
- Type `y`

*Observed behaviour:* :eyes: :broken_heart:

- After the prompt to create a new layout (choosing yes), a `helm-mode-persp-frame-switch` buffer is opened, but it's empty.

*Expected behaviour:* :heart: :smile:
- The buffer maybe should not open at all, or should create a new perspective and then assign the layout to it.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 03343a7f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by myrgy** [comment]
I cannot reproduce that bug. After `SPS l 2 y` emacs asks me for the new layout name.

**Comment by edran** [comment]
Nevermind, helm is just prompting for a name (thanks @quicknir!). When that is given, the layout gets created.

**Comment by edran** [comment]
I guess I got confused by seeing helm instead of a prompt in the minibuffer...

**Comment by myrgy** [comment]
Yeah, might be.
Hence could be close, because performs as expected:)
