### ISSUE TITLE
 All environment variables except PATH loaded from shell

### ISSUE THREAD

**Issue by xeals** [syl20bnr/spacemacs#10233]
#### Description :octocat:
All environment variables except PATH loaded from shell

#### Reproduction guide :beetle:
- Start Emacs as systemd unit

*Observed behaviour:* :eyes: :broken_heart:

PATH is not set:

```elisp
(getenv "PATH")
; "/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin"
```

But other environment variables are:

```elisp
(getenv "RUSTUP_HOME")
; "/home/xeal/.local/share/rustup"
```

Running `(exec-path-from-shell-initialize)` does not solve the issue, and `(exec-path-from-shell-copy-env "PATH")` returns the same default path.

*Expected behaviour:* :heart: :smile:

PATH should be set with other environment variables

```bash
$ echo $SHELL
/bin/zsh
$ echo $PATH
/home/xeal/.local/share/cargo/bin:/home/xeal/.local/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin
```

#### Other info

zshenv file is given [here](https://hastebin.com/axariripac) with sensitive information removed.

systemd unit file is given [here](https://hastebin.com/narecunubi).

Nothing in any of my (Spac)emacs config files modifying my path.

Running Emacs from a shell sources PATH correctly; it's only when it's run as a user systemd unit that it fails to source PATH. Typically I start the emacs server as a systemd unit and access it via `emacsclient`, which is why this matters to me.

To clarify: this has worked in the past. It only stopped working when I updated my Spacemacs and packages. I was likely on a version of develop from up to two weeks ago.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 617d6309)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy better-defaults
     (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion t)
     syntax-checking version-control
     (auto-completion :variables auto-completion-enable-snippets-in-popup t :disabled-for org latex text git eshell markdown)
     git emacs-lisp rust
     (clojure :variables clojure-enable-fancify-symbols t)
     elm java haskell python elixir pandoc markdown org
     (latex :variables latex-enable-auto-fill t TeX-view-program-selection
            '((output-pdf "PDF Tools")))
     bibtex yaml colors pdf-tools)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS NOTIFY LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by c02y** [comment]
Emacs daemon really has a lot of bugs.

I tested it without spacemacs configs and without any configs:

The `gocode` binary is in my PATH(fish-shell), but emacs daemon-client cannot find it. 

PATH values in emacsclient and emacs are different.

This is so weird.

**Comment by philippera** [comment]
This seems to be old but quite popular. Any update on this one? :-)
