### ISSUE TITLE
[Bug] Failure to update packages on macOS High Sierra.

### ISSUE THREAD

**Issue by raguay** [syl20bnr/spacemacs#10235]
#### Description :octocat:

The update packages says that I need to update 53 packages. But, when it tries to do that, it dies saying the ~/.emac.d/.cache/.rollback directory structure doesn't exist. I assume the script should create it.

Also, the C-c, C-c when creating this issues failed to work. It said no such file or directory: open

#### Reproduction guide :beetle:
- Start Emacs
- Select `update packeages` on the Spacemacs buffer.
- When prompted to update packeages, say yes.
- It will then die without updating the packeages due to not able to create the rollback area.

*Observed behaviour:* :eyes: :broken_heart:

The error message appears in the message buffer:

copy-directory: Opening output file: No such file or directory, /Users/raguay/.emacs.d/.cache/.rollback/18-01-23_10.31.35/dash-20171028.854/dash-autoloads.el

*Expected behaviour:* :heart: :smile:

All the packeages updated to the latest version.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50
- Spacemacs: 0.200.11
- Spacemacs branch: master (rev. c25f1c6d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm osx python html auto-completion better-defaults emacs-lisp git markdown html javascript haskell rust ruby scheme themes-megapack org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by zer09** [comment]
There is a fix on develop 1580dfd also please check this issue https://github.com/syl20bnr/spacemacs/issues/9832#issuecomment-359501057
In [gitter](https://gitter.im/syl20bnr/spacemacsl) @syl20bnr also add instruction on renaming the directory entries on ```.cache/rollback``` like ```develop18.01.xxxxxx``` into ```develop/18.01.xxxxx``` and **_probably_** ```master18.01.xxxxxx``` into ```master/18.01.xxxxx```. Here is the link to it https://gitter.im/syl20bnr/spacemacs?at=5a66332398927d5745211b61

**Comment by raguay** [comment]
It did not create the rollback directory at all on my system. Therefore, I
don't know what it want the `xxxxx` to be.

**Comment by zer09** [comment]
Yeah, that is auto generated when you update. 
And I think it was just a date and time.

**Comment by raguay** [comment]
I've cleared out and completely re-installed spacemacs and my full Emacs
install twice already and it still keeps happening. Will I have to redo the
fix each time?

**Comment by zer09** [comment]
I think the fix will be merged to master soon, or you can try out develop branch for the moment until the merged happen.

But if you already cleared it out and re-installs, I think you can just ignore it, because the purpose of ```.cache/.rollback``` is for update backup, that you can rollback if there is unwanted package update happened.

**Comment by syl20bnr** [comment]
If you reisntalled Spacemacs then it will download the last version of all the packages, you should not have any package to update.

I'll check this issue this week. In the meantime it is possible to update the packages by moving `~/.emacs.d/elpa` folder to `~/.emacs.d/elpa.bak` and restart Emacs. The last version of the packages will then be downloaded in a new `~/.emacs.d/elpa` folder.
