### ISSUE TITLE
Translating Vim keybindings to Emacs keybindings

### ISSUE THREAD

**Issue by da-edra** [syl20bnr/spacemacs#10243]
How can I translate (or use) Vim keybindings "on the fly" if I'm using Emacs keybindings as default and I'm not intending to use Vim keybindings?

I'd like to easily be able to delete things like "Recent Files" from the "Welcome buffer" using Emacs keybindings but it doesn't seem to be an Vim to Emacs equivalent keybindings document anywhere.

I could help writing one but I need to know the equivalence.

![captura de pantalla_2018-01-24_01-33-03](https://user-images.githubusercontent.com/10160626/35319702-9d792420-00a6-11e8-83b0-82931505a43b.png)

**Comment by nixmaniack** [comment]
I didn't understand your issue fully but regarding your query on `delete things like "Recent Files" from the "Welcome buffer"`  - that is not possible in the Vim style as well. The welcome buffer is `read-only` buffer. 

Instead, you can control number of recent files/projects displayed with the `dotspacemacs-startup-lists` variable in your  `.spacemacs` file.

**Comment by da-edra** [comment]
Thanks.
I was talking about Vim-Emacs key binding equivalence like ```SPC h l``` is from Vim.
```C-x C-s``` from Emacs.
How can I know the "equivalent" Vim key binding when using Emacs mode?

**Comment by nixmaniack** [comment]
The keys are consistent across both the styles. 
* `SPC h l` in vim style would translate to `M-m h l` in emacs style (here style means `dotspacemacs-editing-style`). 
* The `SPC` in that keybinding which appears in the start of the keybinding is called the `leader` key in `vim` style and translates to `M-m` in `emacs` style(in the default configuration and can be changed in your `~/.spacemacs` file). 

I'm not sure how did you come to the conclusion that `SPC h l` in Vim is equivalent to `C-x C-s` from emacs. `SPC h l` is `ivy-spacemacs-help-layers`(for ivy layer) and `C-x C-s` is `save-buffer`. Could you elaborate here?

**Comment by da-edra** [comment]
I see, thank you so much @nixmaniack 
No, no, I wasn't saying that `SPC h l` & `C-x C-s ` where equivalent, I was just giving some examples of keybindings.

Thank you so much for your help!!
