### ISSUE TITLE
Treemacs changes root directory?

### ISSUE THREAD

**Issue by cactuar** [syl20bnr/spacemacs#10246]
Hello,
I am having an issue with treemacs on develop: I open treemacs with treemacs-projectile and treemacs shows the correct project root (for example my-project). Then I open a file and go back to the treemacs buffer with m-0 and treemacs changes its root relative to this file (let's say the file is myproject/dir1/test.txt, then all I can see are the contents of dir1). This problem appeared when treemacs buffer numbering was removed, but I don't know if these two thins are related.
Thank you!

**Comment by Alexander-Miller** [comment]
Let us start with the easy questions: what's M-0 bound to?

**Comment by cactuar** [comment]
M-0 is bound to treemacs (sorry, I forgot to say that I use spacemacs in holy mode), it is the default for treemacs right now (days ago it had a proper window number).

**Comment by Alexander-Miller** [comment]
> M-0 is bound to treemacs

It shouldn't be. It's supposed to be bound to `treemacs-select-window` and SPC-0 to `treemacs`, or M-m 0 if youre on holy mode. Did you touch these in your config?

**Comment by cactuar** [comment]
Argh, sorry! I press M-m hundreds of times a day that I think of them as a single keystroke :-)
You are right, it's M-m 0

**Comment by Alexander-Miller** [comment]
Things are working as expected then. M-m 0 rebuilds treemacs with the current file as root, M-0 just selects it.

You are free to rebind M-m 0, the same function is also available at M-m f T.

**Comment by cactuar** [comment]
Thank you very much (for this answer and for treemacs, of course!), and sorry again for my inaccurate description.
