### ISSUE TITLE
Required feature ‘projectile’ was not provided when doing [SPC p f] in project

### ISSUE THREAD

**Issue by dstcruz** [syl20bnr/spacemacs#10249]
#### Description :octocat:
helm-projectile-find-file is not working

#### Reproduction guide :beetle:
- Start Emacs
- Open a file inside a .projectile folder
- [SPC p f]

*Observed behaviour:* :eyes: :broken_heart:
The following message is displayed in the mini-buffer:

Required feature ‘projectile’ was not provided

*Expected behaviour:* :heart: :smile:
Expect to have helm in the mini-buffer to chose a project file

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.200.11
- Spacemacs branch: master (rev. c25f1c6d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(haskell yaml fsharp csharp sql auto-completion emacs-lisp git helm html javascript markdown org themes-megapack version-control windows-scripts)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by casouri** [comment]
I would suggest you to switch to develop branch for better support since (probably) most of the Spacemacs users are on there. 
Also many of the bugs on master branch have been fixed on develop branch.
