### ISSUE TITLE
REGRESSION: spacemasc/ivy-persp-switch-project no longer creates new layouts

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#10240]
#### Description :octocat:
`SPC p l` / `spacemacs/ivy-persp-switch-project` no longer creates layouts after
4b111f7701ffea8e724666471a64867fe0c7af22 (and the subsequent fixes).

/cc @tadfisher 

#### Reproduction guide :beetle:
- Start Emacs
- `SPC p l`
- Select a project
- `SPC l l`

*Observed behaviour:* :eyes: :broken_heart:
The selected project does not have a layout in the list of layouts.

*Expected behaviour:* :heart: :smile:
The selected project should have a layout in the list of layouts.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 03343a7f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(rust octave gtags swift nginx better-defaults spacemacs-layouts ivy
      (markdown :variables markdown-live-preview-engine 'vmd)
      (syntax-checking :variables syntax-checking-enable-tooltips t)
      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup nil spacemacs-default-company-backends
                       '(company-capf
                         (company-dabbrev-code company-keywords)
                         company-files company-dabbrev))
      git dash pdf-tools html
      (org :variables org-enable-github-support t org-enable-reveal-js-support t org-want-todo-bindings t)
      colors
      (osx :variables osx-command-as 'super)
      (github :variables magit-gh-pulls-pull-detail-limit 200)
      (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
      (spell-checking :variables spell-checking-enable-by-default nil)
      version-control rcirc tmux yaml docker restclient lua chrome
      (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
      emoji aj-elixir aj-emacs-lisp aj-javascript aj-term aj-typescript aj-ruby auto-correct cleverparens-lispy dotenv flow match-indent shift-number writing)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES LCMS2

**Comment by aaronjensen** [comment]
Original PR: #9616
One fix (for other issues): #10188

**Comment by nixmaniack** [comment]
My mistake :( I had removed the advice which actually creates the perspective while fixing the other issue. Could you please test the PR https://github.com/syl20bnr/spacemacs/pull/10247?

**Comment by aaronjensen** [comment]
That worked, thanks!

**Comment by aaronjensen** [comment]
Closing, as this is a duplicate of #10193

**Comment by nixmaniack** [comment]
Thanks for testing @aaronjensen!

**Comment by syl20bnr** [comment]
Dup of https://github.com/syl20bnr/spacemacs/issues/10240
