### ISSUE TITLE
Typing quickly breaks umlauts

### ISSUE THREAD

**Issue by Granjow** [syl20bnr/spacemacs#10259]
#### Description :octocat:
When typing *für* quickly (around 5 keystrokes/s), emacs types `fÃ\274r`.

This happens only for `f` followed by a special character like ü (directly on the `de_CH` layout)
or é (Shift ö on the `de_CH` keyboard layout).

Also, it only happens in no-window mode (`emacs -nw`), but from any terminal (also xterm) and also in
a non-graphical environment (tty1).

When typing slowly, it does not happen. In window mode, it does not happen. For any other character
(admittedly only tested a-z) preceding the umlaut or special character, including upperspace F,
it does not happen.

See also [Typing quickly breaks umlauts](https://emacs.stackexchange.com/questions/38283/typing-quickly-breaks-umlauts)
on StackExchange.

#### Reproduction guide :beetle:
- Start Emacs
- Change to a keyboard layout which contains e.g. äöü, like de_CH
- Type the word “für” quickly

*Observed behaviour:* :eyes: :broken_heart:
Emacs types fÃ\274r

*Expected behaviour:* :heart: :smile:
Emacs types für

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(nginx php yaml typescript markdown html javascript ivy emacs-lisp)
```

**Comment by monnier** [comment]
FWIW, my crystal ball tells me that what is happening is the following:
some package somewhere tries to peek at the "next event" during a short time, e.g. with `read-event`
(but with a nil value for the optional `inherit` argument) after which it pushes the read event onto `unread-command-events`.

Sadly in a text-terminal this won't work right because the `read-event` will only read the first byte of the `ü` character, so the utf-8 sequence ends up broken into two chunks and Emacs's keyboard reading routines won't see it as a single char any more.

**Comment by syl20bnr** [comment]
Thank you @monnier for this clear explanation.
Indeed `evil-escape` intercept the `f`. 


@Granjow See https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#escaping
You can exclude this package by adding it to your `dotspacemacs-exclude-packages`.

@monnier Do you have a pointer to get the value of the `inherit` argument required to correctly push the event back to `unread-command-events` ?

**Comment by monnier** [comment]
Sounds like the culprit, indeed.  Sadly it's night on impossible to make "read key + unread key" 100% reliable.
A quick fix for the above problem might be to pass `t` for the `inherit-input-method` argument (and to temporarily let-bind `input-method-function` to nil at the same time).  At least that;s the technique I currently use in `sit-for` (which see).

**Comment by Granjow** [comment]
Wow, thanks! Interesting. Funnily, I fail to exclude the package now, adding this to `~/.spacemacs` did not work. Sorry for this basic question now, but how do I do that correctly?

```
(defun dotspacemacs/user-config ()
  (setq-default dotspacemacs-exclude-packages '(evil-escape))
  )
```

**Comment by nixmaniack** [comment]
@Granjow You shouldn't/don't need to re-define `dotspacemacs-exclude-packages`. It's already available in the `~/.spacemacs` in `dotspacemacs/layers` function. Search and add it there.

**Comment by Granjow** [comment]
@nixmaniack Cannot find it there. Maybe I am using a different setup; I have cloned the git repository into `~/.emacs.d` as suggested on the web page, and my `~/.spacemacs` file contains this `user-config` function which sounded like a good place to add the exclude.

When I grep my .emacs.d directory for `exclude-packages`, it does not find anything, also the `~/.emacs.d/layers/`directory contains no such call.

**Comment by nixmaniack** [comment]
You should search for that variable in `~/.spacemacs` and not in `~/.emacs.d`.

**Comment by Granjow** [comment]
@nixmaniack Aye, that worked, and the bug is gone! Thank you!
