### ISSUE TITLE
private/local for packages

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#10250]
I tried to put a package (font-lock+.el from the wiki) in `~/.emacs.d/private/local/` and could not get spacemacs to find it although the `README.org` in that directory says otherwise.

I tried to put the package in a subdirectory with version number, directly into the package directory, and with adding the package name to `dotspacemacs-additional-packages` with and without (font-lock+ :location local).

**Comment by Daeimon** [comment]
Hi, I can get it working by using M-x package-install-file to add the package file.

**Comment by gdkrmr** [comment]
this just got fixed in 79b87c7
