### ISSUE TITLE
Unicode symbols at home screen problem

### ISSUE THREAD

**Issue by adamhaber** [syl20bnr/spacemacs#10256]
Description :octocat:
Home screen shows weird unicode symbols.

Reproduction guide 🐞
- Start Emacs

Observed behaviour: 👀 💔
Home screen shows weird unicode symbols (see attached picture).

Expected behaviour: ❤️ 😄
Regular home screen layout.

System Info 💻

- OS: gnu/
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

```elisp
(helm emacs-lisp)
```
![screenshot_spacemacs](https://user-images.githubusercontent.com/20320402/35386203-e1cfa422-01d3-11e8-9fdf-1be29ba4b2dd.png)

**Comment by jabir366** [comment]
i am also  experiencing the same problem
