### ISSUE TITLE
Can't install org-plus-contrib on 0.200.12

### ISSUE THREAD

**Issue by CeleritasCelery** [syl20bnr/spacemacs#10251]
#### Description :octocat:
can't install org-plus-contrib on latest master. Might be because my proxy does not support HTTPS

#### Reproduction guide :beetle:
- Start Emacs
- Add org layer
- Save and restart

*Observed behaviour:* :eyes: :broken_heart:
```
--> installing package: org-plus-contrib@org... [1/12]
An error occurred while installing org-plus-contrib (error: (file-error https://orgmode.org/elpa/org-plus-contrib-20171009.tar Not found))
```

*Expected behaviour:* :heart: :smile:
org-plus-contrib should install. The file in question seems to exist

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.12
- Spacemacs branch: master (rev. d22de6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html markdown csv python debug graphviz vimscript shell-scripts perl c-c++ helm imenu-list syntax-checking
      (auto-completion :variables auto-completion-enable-sort-by-usage t)
      better-defaults evil-cleverparens ranger emacs-lisp git version-control colors journal org
      (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
      (shell :variables shell-default-shell 'shell)
      (spell-checking :variables spell-checking-enable-by-default nil)
      major-modes config shell-config)
```
- System configuration features: XPM JPEG TIFF PNG GPM NOTIFY ACL FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by syl20bnr** [comment]
This is weird, do you still have the error ? Maybe ELPA org was down ?
If your proxy does not support HTTPS then MELPA would not work as well.

**Comment by CeleritasCelery** [comment]
someone in the gitter chat mentioned that they could reproduce with `--insecure`.

**Comment by clm1** [comment]
Hi, same issue here with --insecure.
I'm behind a proxy and use cntlm to authenticate.

here is the error log on start up after after a pull of master and a full clean up of the elpa directory.

```
Found 4 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: org-plus-contrib@spacemacs-org... [1/4]
Package org-plus-contrib is unavailable. Is the package name misspelled?
--> installing package: org-present@org... [2/4]
Package org is unavailable. Is the package name misspelled?

An error occurred while installing org-present (error: (error Package `org-plus-contrib-7' is unavailable))
--> installing package: org-projectile@org... [3/4]
Package org is unavailable. Is the package name misspelled?

Package org is unavailable. Is the package name misspelled?

An error occurred while installing org-projectile (error: (error Package `org-plus-contrib-9.0.0' is unavailable))
--> installing package: orgit@git... [4/4]
Package org is unavailable. Is the package name misspelled?

An error occurred while installing orgit (error: (error Package `org-plus-contrib-8.3.3' is unavailable))
```

Thanks for your help.

**Comment by jlombera** [comment]
I can confirm that my configuration is also with `dotspacemacs-elpa-https` set to `nil` (same effect as `--insecure`) because I'm behind a proxy.

**Comment by benbotwin** [comment]
I'm getting a similar issue, but I'm not behind a proxy and I've tried over several networks.

I keep getting 
```
Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: org-plus-contrib@spacemacs-org... [1/1]
Package org-plus-contrib is unavailable. Is the package name misspelled?
```

I've tried running emacs with `--insecure` too, but still no dice.

**Comment by yxsongbo** [comment]
I think the problem is not proxy.maybe sapacemacs itself.I solve it by downloads org-plus-contrib from https://orgmode.org/elpa/  and  copy it to .emacs.d/elpa. then the problem is solved.

**Comment by yxsongbo** [comment]
please downloads org-plus-contrib from https://orgmode.org/elpa/ and copy it to .emacs.d/elpa

**Comment by CeleritasCelery** [comment]
that is how I solved it as well. But this still seems broken in Spacemacs.

**Comment by jlombera** [comment]
It seems there is a problem with the orgmode.org certificate.  I found this when trying to manually download org-plus-contrib as @yxsongbo suggested:
```
$ wget https://orgmode.org/elpa/org-plus-contrib-20180205.tar
--2018-02-11 12:05:29--  https://orgmode.org/elpa/org-plus-contrib-20180205.tar
Resolving <my_proxy_goes_here>... <proxy_ip>
Connecting to <my_proxy_goes_here>|<proxy_ip>|:80... connected.
ERROR: certificate common name “code.orgmode.org” doesn’t match requested host name “orgmode.org”.
To connect to orgmode.org insecurely, use ‘--no-check-certificate’.
```

**Comment by ruefo** [comment]
I am having the same (or similar?) problems with org-plus-contrib. Right now, I tried it on master and develop, but I'm not able to install the package. I also tried the suggestion of @yxsongbo with no luck. My complete spacemacs installation is broken by this (and I was not able to fix it, even with a complete reinstall), so please, can anyone bring some light in here?

Here the output when I am on master:

```
Debugger entered--Lisp error: (error "Package ‘org-plus-contrib-8.2.7’ is unavailable")
  signal(error ("Package ‘org-plus-contrib-8.2.7’ is unavailable"))
  error("Package `%s-%s' is unavailable" org-plus-contrib "8.2.7")
```

**Comment by CeleritasCelery** [comment]
How did you try to install it manually?

**Comment by ruefo** [comment]
@CeleritasCelery Sorry for the unclear formulation - I did not manually install org-plus-contrib. The only thing I tried here is to copy from [elpa](https://orgmode.org/elpa/).

**Comment by CeleritasCelery** [comment]
copy it from elpa to a temp area then install it with `package-install-file`

**Comment by ruefo** [comment]
Ah, thanks a lot, that did it.

**Comment by vmandela** [comment]
any pointers on what the root cause could be.

**Comment by levitanong** [comment]
@CeleritasCelery is this on the railwaycat version of emacs? This started happening to me when i switched to railwaycat from the d12frosted version.

**Comment by CeleritasCelery** [comment]
@levitanong no I am using SUSE linux, with the default Emacs distribution.

**Comment by vinurs** [comment]
meet the same problem in develop branch

**Comment by DoaneAS** [comment]
I'm also seeing this error on fresh install of spacemacs using emacs 26.1 on CentOS 7.

**Comment by kevinjamescasey** [comment]
Same problem in  `0.200.13.x`

I don't think I need any of this stuff:
https://github.com/magit/orgit
https://code.orgmode.org/bzg/org-mode/src/master/contrib

So `dotspacemacs-excluded-packages '(orgit org-plus-contrib)` in `dotspacemacs/layers` seems to quell the startup error.

**Comment by didibus** [comment]
I had to download `org-plus-contrib` from https://orgmode.org/elpa/ and install it manually using `package-install-file`.

**Comment by sizhky** [comment]
It's still a problem in `0.300.0@26.3`

**Comment by ro6** [comment]
I'm having the same issue, on a Centos 6.10 (with `gnutls-cli` installed and on `PATH`).
Is there a way to get more startup debug info than:
`An error occurred while installing org-superstar (error: (error Package 'org-plus-contrib-9.1.9' is unavailable))`?

**Comment by rinconjc** [comment]
Sadly, the  --insecure has become ineffective now that melpa is redirecting to http(80) to https (403). 
It sucks to be behind a MS proxy. I have cntlm proxying it, but still url.el doesn't seem to handle async https properly.
