### ISSUE TITLE
configuration-layer--elpa-archives is set but not work

### ISSUE THREAD

**Issue by lsytj0413** [syl20bnr/spacemacs#10268]
#### Description :octocat:
configuration-layer--elpa-archives is set but not work

#### Reproduction guide :beetle:
- set configuration-layer--elpa-archives in user-init function
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
refreshing package archive from melpa, org and gnu

*Expected behaviour:* :heart: :smile:
refreshing package archive from configuration-layer--elpa-archives

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.50.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3eb6ae2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((ivy :variables ivy-extra-directories nil)
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for org)
 (better-defaults :variables better-defaults-move-to-end-of-code-first t)
 emacs-lisp git markdown org
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (python :variables python-sort-imports-on-save t)
 (go :variables go-tab-width 4 go-use-gometalinter t gofmt-command "goimports")
 protobuf ranger gtags ibuffer
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 900)
 docker sql
 (syntax-checking :variables syntax-checking-enable-by-default t syntax-checking-enable-tooltips t)
 liter ycmd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

#### configuration-layer--elpa-archives

```
  (setq-default configuration-layer--elpa-archives
                '(("melpa-cn" . "http://elpa.emacs-china.org/melpa/")
                  ("org-cn" . "http://elpa.emacs-china.org/org/")
                  ("gnu-cn" . "http://elpa.emacs-china.org/gnu/")
                  ("marmalade-cn" . "http://elpa.emacs-china.org/marmalade/")
                  ("user42-cn" . "http://elpa.emacs-china.org/user42/")
                  ("melpa-stable-cn" . "http://elpa.emacs-china.org/melpa-stable/")
                  ("sunrise-commander-cn" . "http://elpa.emacs-china.org/sunrise-commander/")
                  )
                )
  (setq-default package-archives configuration-layer--elpa-archives)
```

**Comment by y-usuzumi** [comment]
Got bit by this months ago. If you are using the `develop` branch, then use `configuration-layer-elpa-archives` instead.

**Comment by lsytj0413** [comment]
@y-usuzumi 3ks
