### ISSUE TITLE
Mode line separators don't render with emacsclient

### ISSUE THREAD

**Issue by jcf** [syl20bnr/spacemacs#10261]
#### Description :octocat:

Mode line separators render as empty boxes when running Emacs via `emacsclient -c`.

#### Reproduction guide :beetle:

I'm running the `develop` branch (9d540f8a) of Spacemacs with Emacs 25.3.1.

- Start an Emacs server via systemd

```
# ~/.config/systemd/user/emacs.service
[Unit]
Description=Emacs: the extensible, self-documenting text editor

[Service]
Type=forking
ExecStart=/usr/bin/emacs --daemon
ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
Restart=always
Environment="DISPLAY=:0" "SSH_AUTH_SOCK=/run/user/1000/gnupg/S.gpg-agent.ssh"

# Set a more realistic startup timeout
TimeoutStartSec=120

[Install]
WantedBy=default.target
```

- Create a new frame with `emacsclient -c` (I have an i3 keybinding that execs that command)

 ## Observed behaviour: :eyes: :broken_heart:

![2018-01-26-11 56 03-6b47c541b1b0](https://user-images.githubusercontent.com/18374/35438817-ec4967e6-028f-11e8-9e2c-2c67ee0fb6fa.png)

## Expected behaviour: :heart: :smile:

This is what I see when I launch a regular Emacs GUI process.

![2018-01-26-11 57 08-a60b57df4374](https://user-images.githubusercontent.com/18374/35438838-10b70e9e-0290-11e8-9c80-a598715c262a.png)

---

Given that the separators work when I'm not using an Emacs server I must have the right fonts on my system.

**Comment by jcf** [comment]
I found [this issue that I commented on](https://github.com/syl20bnr/spacemacs/issues/4816#issuecomment-256172106) some time ago.

**Comment by jcf** [comment]
If I call `(spacemacs-modeline/init-spaceline)` then all my invocations of `emacsclient` get the pretty separators.

**Comment by jcf** [comment]
I've added this to my `dotspacemacs/user-config` and my mode line fixes itself automatically.

```
(spacemacs|do-after-display-system-init
 (spacemacs-modeline/init-spaceline))
```

**Comment by jsoo1** [comment]
Maybe a duplicate of #10181

**Comment by jcf** [comment]
@jsoo1 I think you're right. I'll copy the salient bits from here over to the other issue.

**Comment by jcf** [comment]
Closing in favour of #10181.
