### ISSUE TITLE
evil-mc's cursor count in mode line is hard to see

### ISSUE THREAD

**Issue by casouri** [syl20bnr/spacemacs#10263]
#### Description :octocat:
evil-mc mode-line face is not easy to see in spacemacs dark theme.

#### Reproduction guide :beetle:
- Start Emacs
- Use evil-mc by "C-n" in normal mode

*Observed behaviour:* :eyes: :broken_heart:

lighter in dark mode:

<img width="116" alt="screen shot 2018-01-26 at 11 16 55 am" src="https://user-images.githubusercontent.com/13118647/35449426-f5b4661e-028a-11e8-94c4-e1151de6cbc3.png">

lighter in light mode:

<img width="110" alt="screen shot 2018-01-26 at 11 17 10 am" src="https://user-images.githubusercontent.com/13118647/35449459-11e8f7a0-028b-11e8-9c25-25439553b5a0.png">

*Expected behaviour:* :heart: :smile:

Get rid of that background color?

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. dae6efec)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(evil-l visual-l edit-l lsp spacemacs-modeline config ivy-l git emacs-lisp spell-checking org
        (syntax-checking :variables syntax-checking-enable-tooltips nil)
        (lsp-python :variables python-enable-format-on-save t)
        (complete-l :variables complete-l-enable-snippets-in-popup t complete-l-enable-help-tooltip t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
N/A
```

**Comment by syl20bnr** [comment]
This can be implemented at the spacemacs level by a custom segment, or even better by a contributed segment to upstream https://github.com/TheBB/spaceline

**Comment by casouri** [comment]
I'll look into it, thanks.

**Comment by casouri** [comment]
So after some investigation, I am able to sneak my own little segment into default spacemacs modeline.

However I'm not sure if this should be in evil layer of spacemacs or contributed to Spaceline?

```emc``` is the custom segment, and I sneaked it into ```spaceline-spacemacs-theme``` by basically copying and pasting.
```
  (spaceline-define-segment emc
    "Show evil-mc cursor count in modeline"
    (when (> (evil-mc-get-cursor-count) 1)
      (format "EMC:%d" (evil-mc-get-cursor-count)))
    )

  (defun custom-spaceline-spacemacs-theme (&rest additional-segments)
    "Install the modeline used by Spacemacs.
ADDITIONAL-SEGMENTS are inserted on the right, between `global' and
`buffer-position'."
    (apply 'spaceline--theme
           '((persp-name
              workspace-number
              window-number
              emc)
             :fallback evil-state
             :face highlight-face
             :priority 0)
           '((buffer-modified buffer-size buffer-id remote-host)
             :priority 5)
           additional-segments))

  (custom-spaceline-spacemacs-theme)
```

The result is like this:

<img width="477" alt="screen shot 2018-01-26 at 3 34 58 pm" src="https://user-images.githubusercontent.com/13118647/35459937-21e7cd14-02b0-11e8-8a8d-6bc8f69d8bbf.png">

**Comment by casouri** [comment]
Also I suggest to remove the lighter code in evil layer for it doesn't look good anyway.

**Comment by duianto** [comment]
The evil-mc mode line text is dark for me, with both the `spacemacs-dark` and `spacemacs-light` themes: 
![evil-mc-mode-line-text-color](https://user-images.githubusercontent.com/13420573/35463083-2af23676-02ef-11e8-8a58-adfcd0270ab0.png) ![evil-mc-mode-line-text-color-light-theme](https://user-images.githubusercontent.com/13420573/35463210-d38663d4-02ef-11e8-9c74-73dcf7d9f2e4.png)


Evil-mc has 4 variables that control the mode line text:
```
evil-mc-one-cursor-show-mode-line-text
evil-mc-mode-line-text-cursor-color
evil-mc-mode-line-text-paused
evil-mc-mode-line-text-inverse-colors
```

https://github.com/gabesoft/evil-mc#mode-line-text-and-colors

I noticed that your using:
>Distribution: spacemacs-base

Maybe the mode line foreground text is different in the base distribution.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9d540f8a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
 emacs-lisp git haskell helm html markdown org treemacs spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by casouri** [comment]
Thanks! I’ll look at my variables on Monday.

**Comment by zer09** [comment]
@casouri this is not part of the issue, but have you experiencing that after ```C-n``` then go to insert mode then hit ```backspace``` erase text only the last cursor is removing the character?

**Comment by casouri** [comment]
No, mine works fine. Maybe you should ask under evil-mc?

**Comment by zer09** [comment]
Thanks for the reply.

I will try to do a fresh install first, maybe that will be fixed, if not then I will try ask it there.

**Comment by casouri** [comment]
Since it’s not a bug and I don’t have a problem anymore, I will close this issue.
