### ISSUE TITLE
Treemacs can't be opened via SPC f C-t the first time Spacemacs is launched

### ISSUE THREAD

**Issue by piotrpalek** [syl20bnr/spacemacs#10277]
#### Description :octocat:
When using treemacs, `SPC f C-t` doesn't work when Spacemacs is freshly started and didn't have treemacs opened before via another method (like `SPC f T`)

#### Reproduction guide :beetle:
- Start Emacs
- Try to use `SPC f C-t`

*Observed behaviour:* :eyes: :broken_heart:
Getting an error: "Wrong type argument: commandp, treemacs-find-file"

*Expected behaviour:* :heart: :smile:
Treemacs opens focused on the right file

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 64cf9f56)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ruby python ivy auto-completion better-defaults emacs-lisp typescript csv yaml lua git github markdown org deft pandoc
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking version-control javascript html erlang elixir react treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS NOTIFY LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by Alexander-Miller** [comment]
That one's simple. Find-file needs to be autoloaded. Note that with non-nil `treemacs-follow-after-init` it'll work the same as SPC f T / f P (other than keeping focus).

**Comment by piotrpalek** [comment]
Is this something I should fix on my end? If so I'd argue it shouldn't behave this way.

**Comment by Alexander-Miller** [comment]
No. Autoloading means telling emacs that this function is to be lazy loaded.

**Comment by Alexander-Miller** [comment]
Pushed an update. Find-file will be autoloaded in v1.17.

**Comment by bmag** [comment]
@Alexander-Miller IIUC this can be closed as "fixed upstream", right?

**Comment by Alexander-Miller** [comment]
Yes.

**Comment by bmag** [comment]
Thanks
