### ISSUE TITLE
(void-function go)

### ISSUE THREAD

**Issue by y-usuzumi** [syl20bnr/spacemacs#10273]
#### Description :octocat:
I added "go" to `dotspacemacs-configuration-layers` and added the following line to dotspacemacs/user-config (as per documentation in [https://github.com/syl20bnr/spacemacs/tree/master/layers/+lang/go](https://github.com/syl20bnr/spacemacs/tree/master/layers/+lang/go)):

```elisp
(go :variables go-use-gometalinter t)
```

During startup i got this error: (void-function go)

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Red bar at the bottom indicating errors occurred during startup. *Messages* buffer contains the following error message:
```
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: go
```

*Expected behaviour:* :heart: :smile:
The variable is set properly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(lua csv helm auto-completion better-defaults emacs-lisp git markdown org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     syntax-checking version-control themes-megapack csharp major-modes fsharp go html idris javascript nginx purescript python rust typescript yaml react)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-function go)
  (go :variables go-use-gometalinter t)
  eval((go :variables go-use-gometalinter t) nil)
  elisp--eval-last-sexp(nil)
  #[257 "\204\303!\207	\303!\n)B\211A	=\204\211A\211@\207" [eval-expression-debug-on-error elisp--eval-last-sexp-fake-value debug-on-error elisp--eval-last-sexp] 4 2274053 "P"](nil)
  #[(

**Comment by syl20bnr** [comment]
You need to add it to the variable `dotspacemacs-configuration-layers`. 

```
   ;; List of configuration layers to load.
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press `SPC f e R' (Vim style) or
     ;; `M-m f e R' (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     ;; .....
    (go :variables go-use-gometalinter t)
     ;; ....
     )
```

**Comment by y-usuzumi** [comment]
@syl20bnr Cool! Thanks!
