### ISSUE TITLE
Send word to REPL (python)

### ISSUE THREAD

**Issue by jobvisser03** [syl20bnr/spacemacs#10270]
I want to improve my Python workflow in the following way:
- Send word at cursor to REPL
- Send word.info() from word (variable) at cursor to REPL
- Send type(word) from word (variable) at cursor  to REPL

I do the following with Elpy but since I use spacemacs I'd rather not use it since it is big. Also I want to use the original layers as much as possible.
```
(defun jv-python/elpy-shell-send-word ()
  "Send word at cursor."
  (interactive)
  (elpy-shell--ensure-shell-running)
  (when (not elpy-shell-echo-input) (elpy-shell--append-to-shell-output "\n"))
    (elpy-shell--with-maybe-echo
  (python-shell-send-string (thing-at-point 'symbol)))
  )
```

Can someone please help me with the points above using spacemacs + e.g. eval-in-repl?

**Comment by jobvisser03** [comment]
Solved the above: 
```
(require 'eval-in-repl-python)
(eir-python-shell-send-string (thing-at-point 'symbol))
(eir-python-shell-send-string (format "%s.info()" (thing-at-point 'symbol)))
(eir-python-shell-send-string (format "type(%s)" (thing-at-point 'symbol)))
```

Last question: How can I replicate the functionality of elpy's send-current-line-or-statement? eval-in-repl can send a line, but when I call it from within a loop it gives and indent error. (the line is indented)

Is there a way to realise this behaviour?

**Comment by fleimgruber** [comment]
Did you consider using a debugger for stepping line-wise through loops?
