### ISSUE TITLE
clojure-doc improvements

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#1028]
Hi,

I'm just trying out clojure so I'm not sure what the community likes but here are my suggestions to make the spacemacs-clojure experience similar to those of other languages.

- `clojure-doc` should be called with the universal argument to provide help for thing under point without the need to press <kbd>RET</kbd>.
- the clojure doc window should be closable by pressing the <kbd>q</kbd> button.

**Comment by nwolfe** [comment]
:+1: :+1: yes please. I use Clojure full-time and this is very, very annoying

**Comment by swaroopch** [comment]
:+1:

**Comment by cpaulik** [comment]
Functions/variables for both of the changes already existed so this was not too hard.
