### ISSUE TITLE
Commas are added in org-mode with C++/JS/... source code block

### ISSUE THREAD

**Issue by kkweon** [syl20bnr/spacemacs#10286]
#### Description :octocat:
JSDoc/C++ style comment adds commas when used in org-mode

```
/**
 * Type comments in code block
 * Works fine in *Org Src temp.org [ js ]*
 * 
 */
```

will be viewed as

```
#+BEGIN_SRC js
  /**
   ,* Type comments in code block
   ,* Works fine in *Org Src temp.org [ js ]*
   ,* 
   ,*/
#+END_SRC
```
![image](https://user-images.githubusercontent.com/2981167/35647774-79008df8-0688-11e8-910e-51ab90c6b7d7.png)

Not just javascript, but any comment that uses the above style.

#### Reproduction guide :beetle:
- Start Emacs
- Create a `temp.org`
- Create a source block in `js` or `C++` or other languages that uses the above style
- Open code block using `, '` 
- Add comments
```
/**
 * Type comments in code block
 * Works fine in *Org Src temp.org [ js ]*
 * 
 */
```
- Close using `, ,`

*Observed behaviour:* :eyes: :broken_heart:

Commas are added.

```
#+BEGIN_SRC js
  /**
   ,* Type comments in code block
   ,* Works fine in *Org Src temp.org [ js ]*
   ,* 
   ,*/
#+END_SRC
```

If I open the code block again with `, '`, the commas disappear.

*Expected behaviour:* :heart: :smile:

should look like as below (no commas)
```
#+BEGIN_SRC js
  /**
   * Type comments in code block
   * Works fine in *Org Src temp.org [ js ]*
   * 
   */
#+END_SRC
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7a86333)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby search-engine typescript nginx docker go colors django react elixir graphviz csv yaml
      (elm :variables elm-format-command "elm-format")
      (haskell :variables haskell-enable-hindent-style "johan-tibell" haskell-completion-backend 'intero)
      github doxyspace java javascript html helm
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence-delay 0 auto-completion-complete-with-key-sequence "jk")
      better-defaults emacs-lisp neotree ess
      (git :variables git-magit-status-fullscreen t)
      (markdown :variables markdown-live-preview-engine 'vmd)
      (org :variables org-enable-bootstrap-support t org-enable-reveal-js-support t org-enable-github-support t)
      (shell :variables shell-default-height 30 shell-default-shell 'eshell shell-default-position 'bottom)
      shell-scripts spell-checking version-control
      (python :variables python-test-runner 'pytest)
      semantic
      (latex :variables latex-build-command "LatexMk")
      (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
      syntax-checking dash calendar gtags bibtex pdf-tools
      (plantuml :variables org-plantuml-jar-path "~/bin/plantuml.jar"))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Alexander-Miller** [comment]
Not a spacemacs issue, I can reproduce this in `emacs -q`, except the commas are inserted into the js-mode buffer and the following error is produced:
```
Debugger entered--Lisp error: (error "Invalid search bound (wrong side of point)")
  re-search-forward("^[ 	]*,?\\(\\*\\|#\\+\\)" 10 t)
  org-escape-code-in-region(1 10)
  org-edit-src-exit()
  funcall-interactively(org-edit-src-exit)
  call-interactively(org-edit-src-exit nil nil)
  command-execute(org-edit-src-exit)
```

You should report this upstream.

**Comment by jiacai2050** [comment]
@kkweon Have you reported this issue to Emacs? I have the same problem when edit C code.
