### ISSUE TITLE
helm-persp-switch-project doen't affect treemacs window

### ISSUE THREAD

**Issue by myrgy** [syl20bnr/spacemacs#10280]
#### Description :octocat:
switching between project with `SPS p l`  treemacs windows remains the same.

#### Reproduction guide :beetle:
- Start Emacs
- Load some project with `SPS p l`
- open Treemacs `SPS f P`
- Switch to another project using `SPS p l`

*Observed behaviour:* :eyes: :broken_heart:
- Treemacs will still show previous project files tree.

*Expected behaviour:* :heart: :smile:
- Treemacs will change file tree to the current project root.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 64cf9f56)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv lua yaml python ruby rust go graphviz pdf-tools helm
     (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t)
     docker semantic emacs-lisp git github gtags markdown javascript gpu
     (org :variables org-projectile-file "TODOs.org")
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control
     (c-c++ :variables c-c++-enable-rtags-support t c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
     cpp2
     (cmake :variables cmake-enable-cmake-ide-support t)
     (plantuml : variables org-plantuml-jar-path "~/.spacemacs.d/plantuml.jar")
     treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-variable cl-return)
  (progn cl-return)
  (if (>= num-buffers-placed num-windows) (progn cl-return))
  (while (consp --cl-var--) (setq buffer (car --cl-var--)) (if (>= num-buffers-placed num-windows) (progn cl-return)) (set-window-buffer (winum-get-window-by-number cur-win) buffer) (setq cur-win (+ 1 (mod cur-win num-windows))) (setq num-buffers-placed (1+ num-buffers-placed)) (setq --cl-var-- (cdr --cl-var--)))
  (let* ((--cl-var-- buffers) (buffer nil)) (while (consp --cl-var--) (setq buffer (car --cl-var--)) (if (>= num-buffers-placed num-windows) (progn cl-return)) (set-window-buffer (winum-get-window-by-number cur-win) buffer) (setq cur-win (+ 1 (mod cur-win num-windows))) (setq num-buffers-placed (1+ num-buffers-placed)) (setq --cl-var-- (cdr --cl-var--))) nil)
  (let ((num-buffers (length buffers)) (num-windows (length (winum--window-list))) (cur-win (winum-get-number)) (num-buffers-placed 0)) (let* ((--cl-var-- buffers) (buffer nil)) (while 
```

**Comment by Alexander-Miller** [comment]
Treemacs does not support persp, or any other perspective package. It won't support them for a long time either, since my next long-term goal is supporting multiple and non-file roots.

Treemacs buffers are always local to a frame, so if you want to work on multiple projects you'll need to make do with C-x 5 2 for now.

**Comment by myrgy** [comment]
could we attach treemacs to `persp-activated-hook` or will postpone till next treemacs release?

**Comment by Alexander-Miller** [comment]
That's not a viable solution (though you're free to try in your own config). Rebuilding treemacs on persp change means losing all your state, expanded nodes, history, point etc. If I'm to integrate with persp I plan to do it right.

**Comment by myrgy** [comment]
ok, hence closed
won't fix
