### ISSUE TITLE
mu4e can't reply to emails

### ISSUE THREAD

**Issue by BowenWang** [syl20bnr/spacemacs#10291]
I have set up mu and mu4e with spacemacs using the tutorial here.

I use 2 email accounts with mu4e.

All functionalities work fine except reply and forward. Whenever I type F or R in the header view, the message buffer says no email account found. I have set up the variable mu4e-account-alist. Any ideas?

PS: I can compose a new email and send it out using mu4e. Just the forward and reply don't work.

Bowen

**Comment by altschuler** [comment]
Instead of using `mu4e-account-alist`, you should use mu4e's context feature. See [here](http://www.djcbsoftware.nl/code/mu/mu4e/Contexts-example.html).
