### ISSUE TITLE
evil-unimpaired install fails, windows standard user

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#10295]
#### Description :octocat:
When one is logged in as a standard (non-administrator) windows user, then the `evil-unimpaired` package fails to install.

#### Reproduction guide :beetle:

- Clone Spacemacs
- Start Emacs
- Answer the 3 questions, to start downloading the packages

*Observed behaviour:* :eyes: :broken_heart:
When the `evil-unimpaired` package is about to be installed, then the Spacemacs home buffer shows this message:
>An error occurred while installing evil-unimpaired (error: (error Invalid version syntax: 'Copying permissions to: Operation not permitted, c:/Users/username/AppData/Roaming/.emacs.d/.cache/quelpa/build/evil-unimpaired/evil-unimpaired.el' (must start with a number)))

`evil-unimpaired` tries to download and install again with the same error message, if one restarts Emacs.

*Expected behaviour:* :heart: :smile:
The `evil-unimpaired` package should install without issues, like the other packages.

#### Notes
`evil-unimpaired` installs without any issues, if one is logged in to an administrator windows account.

#### Possible solution?
While searching, if someone already had reported this issue, I found this PR:
unimpaired: Update ownership #8011
A comment there talks about making `evil-unimpaired` into a package on MELPA.

Maybe this issue would be solved if `evil-unimpaired` were installed like the other packages?

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by duianto** [comment]
This might have been fixed on the `develop` branch.

Because I fixed the `evil-unimpaired` error on the `master` branch, by copying the 
`evil-unimpaired-0.1pre0.20180203.171612` directory from an administrator windows account, to the `.emacs.d/elpa` directory on the windows standard account, and Spacemacs started normally.

I then switched to the `develop` branch and restarted Emacs.
`[121/121]` packages were installed without any error messages.

I noticed that the `evil-unimpaired-20180203.220945` package doesn't have `0.1pre0.` in the name on the `develop` branch.

I guess this might start working on the `master` branch for standard windows account users, when the next major Spacemacs version is released.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f3b6a22c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by timor** [comment]
I just encountered the same error under linux and the 'develop' branch.

**Comment by timor** [comment]
The error occurs when the source of the package has no write permissions.  Specifically, quelpa seems to create the build directory for the package with the same permissions as the source location.  Even if it is permitted to overwrite the contents there it fails, because when trying to save the (internal) buffer with the package source, it tries to write to a read-only location.

**Comment by timor** [comment]
It also may be that this is not triggered the first time a package is built, but when quelpa tries to rebuild it with the build directory still in place.

**Comment by gzmask** [comment]
Having the same issue. Will this stop the whole updating process? I need to update other packages but it seems SPC f e U is not doing the job.

**Comment by jjzmajic** [comment]
Same here

**Comment by gracadedues** [comment]
I have a freshly installed emacs27.1 with spacemacs on windows 10. I get this: Error (use-package) : Cannot load evil-unimpaired. I am a total newbie. Can someone help please? TIA

**Comment by duianto** [comment]
I just cloned a fresh copy of the Spacemacs `develop` branch, and I didn't get any errors about `evil-unimpaired`.

These are the steps I took to clone and install the Spacemacs `develop` branch.

- Open the File explorer (`WIN e`)
- Navigate to the directory where Emacs looks for a `.emacs.d` directory.
By default: `C:\Users\username\AppData\Roaming`

The default directory is fine. But in this case I have added a `HOME` system variable that points to: `C:\Users\username\`

It's not needed to add a HOME system variable, but if someone wants to do it then here are some instructions:

<details><summary>
Add a `HOME` variable (Click to expand)
</summary>
<pre>
- Open the start menu by pressing: WIN (windows key)
- Type: env
for me it selects: Edit the system environment variables
- Press: RET (Return)
a System Properties window opens
- Click on the bottom right button: Environment Variables...
a Environment Variables window opens
In the bottom section: System variables
Press the button: New...
in the Variable name input box, type: HOME
in the Variable value input box, type: C:\Users\username\ (or your desired home directory)

</pre>
</details>

When the File Explorer shows the directory, `roaming` or the defined HOME path if one has been specified.
- Focus the File Explorer address bar (it can be focused with the keyboard by pressing: `Alt d`),
- Type: `cmd`
a command prompt window opens at that File Explorer directory
- Clone Spacemacs at the `develop` branch into a `.emacs.d` directory by running the following:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

When it's done, then Emacs can be started and the setup wizard appears.

Tested in Windows 1903

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 59f72709b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>
