### ISSUE TITLE
pipenv directory .venv and pyvenv file .venv conflict

### ISSUE THREAD

**Issue by rgb-24bit** [syl20bnr/spacemacs#10293]
#### Description :octocat:
In `Python`, an error occurs when there is a folder `.venv` in the root of my project.

#### Reproduction guide :beetle:
- Start Emacs
- There is a .venv folder and open a python script

*Observed behaviour:* :eyes: :broken_heart:
- error:
```elisp
File mode specification error: (file- error Opening input file Permission denied project/.venv)
```
- Can not be automatically completed

*Expected behaviour:* :heart: :smile:
- no error

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. daed52b0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(graphviz octave yaml ivy auto-completion better-defaults emacs-lisp markdown org windows-scripts javascript sql html latex plantuml python
          (c-c++ :variables c-c++-enable-google-style t c-c++-default-mode-for-headers 'c-mode)
          my-csharp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by twillis** [comment]
this is going to be especially problematic since pipenv is apparently the official way to do these kinds of things.  :/

**Comment by twillis** [comment]
fwiw redefining this function in your `dotspacemacs/user-config` like below seems to get around it.

```
(defun spacemacs//pyvenv-mode-set-local-virtualenv ()
    "Set pyvenv virtualenv from \".venv\" by looking in parent directories. handle directory or file"
    (interactive)
    (let ((root-path (locate-dominating-file default-directory
                       ".venv")))
      (when root-path
        (let* ((file-path (expand-file-name ".venv" root-path))
                (virtualenv
                  (if (file-directory-p file-path)
                    file-path
                    (with-temp-buffer
                      (insert-file-contents-literally file-path)
                      (buffer-substring-no-properties (line-beginning-position)
                        (line-end-position))))))
          (if (file-directory-p virtualenv)
            (pyvenv-activate virtualenv)
            (pyvenv-workon virtualenv))))))
```

**Comment by svenpanne** [comment]
Can we please at least get @twillis' workaorund into the `develop` branch? There are already 2 other open issues (#11145 and #10798) which report the same problem, and `pipenv` is the officially sanctioned way to handle virtual environments in Python nowadays. I use the workaround for a few months now, and it works perfectly for me, but I really think that this should work out-of-the-box.
