### ISSUE TITLE
ivy-occur is no longer editable in evil

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#10290]
#### Description :octocat:
ivy-occur is no longer editable

#### Reproduction guide :beetle:
- Start Emacs
- Go to a project directory
- `SPC /`
- Search for something
- `C-c C-e`
- Try to edit the buffer (`c w` for example)

If you disable evil-mode, you can edit it

*Observed behaviour:* :eyes: :broken_heart:
You can't edit the buffer, it uses the normal occur map which doesn't have any
change commands in evil.

*Expected behaviour:* :heart: :smile:
You can edit the buffer

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 64cf9f56)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(octave nginx better-defaults spacemacs-layouts ivy
        (markdown :variables markdown-live-preview-engine 'vmd)
        (syntax-checking :variables syntax-checking-enable-tooltips t)
        (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup nil spacemacs-default-company-backends
                         '(company-capf
                           (company-dabbrev-code company-keywords)
                           company-files company-dabbrev))
        git dash pdf-tools html
        (org :variables org-enable-github-support t org-enable-reveal-js-support t org-want-todo-bindings t)
        colors
        (osx :variables osx-command-as 'super)
        github
        (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
        (spell-checking :variables spell-checking-enable-by-default nil)
        version-control tmux yaml docker restclient lua
        (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
        emoji aj-elixir aj-emacs-lisp aj-javascript aj-term aj-typescript aj-ruby auto-correct cleverparens-lispy dotenv flow match-indent shift-number)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES LCMS2

**Comment by aaronjensen** [comment]
ping @abo-abo just in case you have an idea if anything has changed in this area.

**Comment by aaronjensen** [comment]
I believe the problem was introduced here: https://github.com/emacs-evil/evil/pull/985

`(evil-set-initial-state ivy-occur-grep-mode 'normal)` seems to work around it, but i'm not sure that's the right way.

**Comment by abo-abo** [comment]
> (evil-set-initial-state 'ivy-occur-grep-mode 'normal) seems to work around it, but i'm not sure that's the right way.

Looks like a problem in `evil` config; I think above is the correct solution.

**Comment by aaronjensen** [comment]
Thanks for responding @abo-abo. Is there a hook for when ivy-occur-grep goes from read-only to writable and back? I may be able to set states in that case

**Comment by abo-abo** [comment]
Doesn't `(evil-set-initial-state 'ivy-occur-grep-mode 'normal)` solve your problem?

**Comment by aaronjensen** [comment]
Yes, it does, but ideally it would be in motion state unless the buffer is writable. So the idea is would be to have motion state be the default as it is now but change to normal when switching to non Read only.

**Comment by abo-abo** [comment]
I'm not very familiar with `evil`. But I think that `ivy-occur` buffers should be treated similarly to `dired` buffers. Both have ways of becoming editable, but they are primarily in their own normal modes with commands not related to `evil`.

**Comment by aaronjensen** [comment]
Thanks, I believe dired is "evilified". I'm not too familiar w/ how to set that up or what the right thing to do here is so I'll wait for @syl20bnr or someone else to have time to chime in. Thanks!

**Comment by opsound** [comment]
I am also having issues, even with `(evil-set-initial-state 'ivy-occur-grep-mode 'normal)`. I remember my workflow below working previously.

For example,
- Cursor `thingToEdit` in buffer of interest
- `SPC /`
- `M-n`
- `C-c C-o`
- `/thingToEdit RET` cursor now on `thingToEdit`
- `cw` but instead of change-word, `c` now calls `ivy-occur-toggle-calling`

Navigating to to `thingToEdit` by moving manually with `wbhjkl`, followed by `cw` seems to work though.

**Comment by aaronjensen** [comment]
Hey @opsound, `C-c C-o` opens a read-only ivy-occur buffer. It is and never was expected that this would be editable. `C-c C-e` opens it editable or you could make it editable with `C-x C-q` or `w` after `C-c C-o`. This explains why navigating in a way that includes `w` makes it editable.

In other words, what you're describing is the expected behavior. Hope that helps.

**Comment by opsound** [comment]
@aaronjensen Ah - good call. `w` changing the buffer to be editable explains my confusion. I had thought that `C-c C-o` had new behavior that didn't require `C-x C-q`.

**Comment by bmag** [comment]
Should be solved by #10873 now, thanks for the report and for the help everyone.

**Comment by et2010** [comment]
The issue is back now since that fix has been reverted

**Comment by lebensterben** [comment]
@et2010 

can you elaborate when is it reverted? (in which commit)
