### ISSUE TITLE
[macOS] Frames created with SPC w F are created as macOS tabs and not windows in fullscreen mode

### ISSUE THREAD

**Issue by macbem** [syl20bnr/spacemacs#10307]
As in the title. When you maximize your Spacemacs app using the green dot on the title bar on macOS, creating a new frame (either from Dock or via Spacemacs commands) opens new tabs, not separate windows. I'm not sure if there's any possible workaround without fiddling with Emacs source, but this is probably not the intended behavior.

**Comment by humanfactors** [comment]
Does this still happen if you run `emacs -q` then `C-x 5 2` if so this issue should be closed as it is not a Spacemacs issue.
