### ISSUE TITLE
yas-snippet-dirs does not exist after each upgrade, causing warning

### ISSUE THREAD

**Issue by Blaisorblade** [syl20bnr/spacemacs#10316]
#### Description :octocat:

On Spacemacs stable, since a few weeks, upgrading yasnippet gives on each reboot a warning such as

    [yas] Check your `yas-snippet-dirs': /Users/pgiarrusso/.emacs.d/elpa/yasnippet-20180204.1613/snippets is not a directory
    
until I manually create the named folder. Since the folder name is version-based, the warning is triggered anew with each upgrade.

I also suspect the *content* of the folder isn't migrated with the upgrade.

#### Reproduction guide :beetle:

- Upgrade yasnippet
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

    [yas] Check your `yas-snippet-dirs': /Users/pgiarrusso/.emacs.d/elpa/yasnippet-20180204.1613/snippets is not a directory

*Expected behaviour:* :heart: :smile:

No warning.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp
      (latex :variables latex-build-command "LatexMk")
      git markdown
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by duianto** [comment]
>Yasnippet no longer bundles snippets directly, but it's very easy to get some!

source: https://github.com/joaotavora/yasnippet#where-are-the-snippets

The Spacemacs `auto-completion` layer has added the `yasnippet-snippets` package on the `develop` branch: 
auto-completion: add yasnippet-snippets #10156

I'm not sure what the fix is on the `master` branch.

Maybe `yasnippet` is able to see the snippets if `yasnippet-snippets` is installed
(add it to the `dotspacemacs-additional-packages` variable in `.spacemacs`).

Or maybe the path to the snippets need to be specified manually, by setting the `yas-snippet-dirs` variable, like in the example from the url above:
```
(setq yas-snippet-dirs
      '("~/.emacs.d/snippets"                 ;; personal snippets
        "/path/to/some/collection/"           ;; foo-mode and bar-mode snippet collection
        "/path/to/yasnippet/yasmate/snippets" ;; the yasmate collection
        ))
```

**Comment by deisi** [comment]
I can confirm, adding `yasnippet-snippets` to `dotspacemacs-additional-packages` fixes the issue

**Comment by Blaisorblade** [comment]
@deisi that worked for me too! So I guess `yasnippet-snippets` should also be added to the master branch, by backporting #10156 and 091800b2?

Or just wait for develop to be merged into master with the next release. I'm happy enough for now, so closing the issue.

**Comment by sr105** [comment]
In case anyone else ends up here via search like I did: 

1. Adding `yasnippet-snippets` to `dotspacemacs-additional-packages` does **NOT** fix it.
2. Setting `yas-snippet-dirs` **DOES** fix it, but defeats the purpose of the `auto-complete` layer.

The problem is that the auto-complete layer adds a no-longer existing directory to `yas-snippet-dirs` which causes yas-snippets to complain on initialization. 

https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bcompletion/auto-completion/packages.el#L213

This is all fixed in the develop branch which is now a year ahead of master.

**Comment by breneser** [comment]
Is this going to be merged to master anytime soon ?

**Comment by oliveratutexas** [comment]
Guessing this still hasn't been merged in?

**Comment by sdwolfz** [comment]
You are right, these changes were not released to master yet, but unfortunately I don't have an ETA for the next release.

**Comment by Blaisorblade** [comment]
The next release from develop will take a while, interested users can either switch to develop or contribute a backport of #10156.

**Comment by oliveratutexas** [comment]
I don't think main has been updated for a while.

**Comment by oliveratutexas** [comment]
@Blaisorblade how could I help with backporting? I'd be starting from square 0 w/ this, I'm a vim user of spacemacs who doesn't do much configuration outside of adding lines into my .spacemacs flie

**Comment by dogweather** [comment]
2019, and still seeing this. 

Is there something we can do to help?

**Comment by ssalinasf** [comment]
I've the same problem with the directories.

**Comment by antonazgarovich** [comment]
I too.

**Comment by yelizariev** [comment]
Switching to develop branch fixes the issue:

```
cd
cd .emacs.d
git fetch origin
git checkout develop
# restart emacs
```

**Comment by cinerea0** [comment]
Why is this issue marked "closed" when the fix still hasn't been merged into master?

**Comment by duianto** [comment]
The issue author said the following in the comment above: https://github.com/syl20bnr/spacemacs/issues/10316#issuecomment-367426093
>I'm happy enough for now, so closing the issue.

---

The `develop` branch is the recommended branch until the next version is released (I have no insight into when that is).

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Comment by Blaisorblade** [comment]
> The `develop` branch is the recommended branch until the next version is released (I have no insight into when that is).

👍 in practice, I've been using `develop` for ages — not sure the recommendation is official but it's reasonable.

**Comment by stormwatch** [comment]
I've found out very recently that the snippet tables were empty!

The auto-completion layer [ensures yasnippet-snippets is available](https://github.com/syl20bnr/spacemacs/blob/663cfc5ba7826dd20d18fe5c1f8fb09338284955/layers/%2Bcompletion/auto-completion/packages.el#L353)

And yasnippet-snippets autoloads [`yasnippet-snippets-initialize`](https://github.com/AndreaCrotti/yasnippet-snippets/blob/f50b4c16ca2a73fd04ebd301f0bf2f5ab6107d88/yasnippet-snippets.el#L47)
```emacs-lisp
(eval-after-load 'yasnippet
   '(yasnippet-snippets-initialize))
```

But I found out that `yasnippet-snippets-initialize` was apparently not being run. I am guessing that maybe it has to do with using `eval-after-load`.

My current workaround consists of adding 

```emacs-lisp
(use-package yasnippet-snippets
  :defer t
  :config
  (yasnippet-snippets-initialize))
```

to my `dotspacemacs/user-config`

**Comment by lebensterben** [comment]
@stormwatch 
According to https://github.com/syl20bnr/spacemacs/pull/10156#issue-288443684
> Note yasnippet-snippets does not need to be initialized with use-package; simply installing it and putting it in the load-path is enough for yasnippet to find the snippets.

**Comment by stormwatch** [comment]
@lebensterben Thank you!
