### ISSUE TITLE
How to enable org-notmuch?

### ISSUE THREAD

**Issue by dam5h** [syl20bnr/spacemacs#10317]
I have used the `customize` feature to set my `org-modules` list to include org-notmuch.  I then checked my dotfile to see if it registered and indeed I see this in `custom-set-variables` call:
```lisp
'(org-modules
   (quote
    (org-bbdb org-bibtex org-docview org-gnus org-info org-irc org-mhe org-rmail org-w3m org-notmuch)))
```
However `org-notmuch` does not appear on the `list-packages` output and also the underlying functions defined by the package are not recognized.

What am I doing wrong?

Thanks!

**Comment by jb55** [comment]
@dam5h did you figure it out? I have this on my todo as well.

**Comment by dam5h** [comment]
Yes, I actually just misunderstood how it worked.  First of all org-notmuch is not a package so it's not going to show up in `list-packages`.  Also the functions are not "interactive" so they aren't technically commands that would show up when searching after `M-x`.

The other misconception is that I didn't realize that `org-capture` was part of the process,  and it just works out of the box with `org-capture`.  I also did a little bit of customization to my `org-capture-templates` variable in my `user-config` function, to behave the way I wanted it to.  This post was helpful for writing the template:  http://pragmaticemacs.com/emacs/org-mode-basics-vii-a-todo-list-with-schedules-and-deadlines/
