### ISSUE TITLE
GUI Spacemacs transparency not activating

### ISSUE THREAD

**Issue by fosskers** [syl20bnr/spacemacs#10312]
#### Description :octocat:
GUI Spacemacs transparency not activating

#### Reproduction guide :beetle:

Add the following to the `dotspacemacs/user-config` section of `.spacemacs` as advertised [here](https://github.com/syl20bnr/spacemacs/pull/8461) and [here](https://github.com/syl20bnr/spacemacs/issues/4435):
```lisp
;; Transparency
(spacemacs/enable-transparency)
```

*Observed behaviour:* :eyes: :broken_heart:
My Emacs screen stays opaque (the default gray colour).

*Expected behaviour:* :heart: :smile:
I ought to see my desktop background.

#### System Info :computer:
- OS: Arch Linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5f6f9d23)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript html yaml
            (keyboard-layout :variables kl-layout 'colemak-hnei)
            (haskell :variables haskell-completion-backend 'intero)
            scala
            (elm :variables elm-sort-imports-on-save t)
            (purescript :variables psc-ide-use-npm-bin t)
            nixos
            (shell :variables shell-default-position 'right)
            helm auto-completion emacs-lisp git markdown
            (org :variables org-enable-github-support t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by fosskers** [comment]
A similar problem and solution was hinted at in [this Reddit post](https://www.reddit.com/r/spacemacs/comments/73zrxt/transparency_not_working/).

**Comment by tulsileathers** [comment]
I also have this issue. Also using archlinux and the develop branch

**Comment by fosskers** [comment]
It's X for me (Xmonad).

**Comment by Miciah** [comment]
Xmonad does not handle compositing itself, so you need to configure a compositor manager in order to get transparency: https://wiki.haskell.org/Xmonad/Frequently_asked_questions#How_do_I_use_compositing_with_xmonad.3F

As far as I can tell, GNU Emacs does not support transparency on Wayland; the NEWS files only mention support for transparency on X, Microsoft Windows, and macOS.

**Comment by Ethergeist** [comment]
Tried using this in dotspacemacs/user-config, but to no avail (possibly due to running in daemon mode)
`(spacemacs/enable-transparency)`
The following works for me in dotspacemacs/user-config:
`(add-hook 'after-make-frame-functions 'spacemacs/enable-transparency)`

I'm putting this here only because 'spacemacs enable transparency' returns this as a top result

**Comment by fosskers** [comment]
@Ethergeist 's solution doesn't work for me, but I guess that's the curse of XMonad (see above).

**Comment by Ethergeist** [comment]
@fosskers It seems that my solution only works when running emacs in daemon mode and connecting to the daemon using emacsclient. A separate install on OSX works with
```
(spacemacs/enable-transparency)
```

Either way, my installation is using i3 with compton - Have you tried installing compton and adding it to an XMonad launch script?

**Comment by various89** [comment]
Running `compton` from terminal showed some errors.. 
Fixing those at ~/.config/compton.conf, brought back transparency.
Additionally I switched from compton to [picom](https://wiki.archlinux.org/index.php/Picom), as it was recommended by on of the error messages.
(using manjaro, i3)

**Comment by fosskers** [comment]
I switched to `i3` recently, but still can't get the transparency to work.

**Comment by various89** [comment]
in my `~/.config/i3/config` file there is the following line `exec_always picom -b`

for testing purposes you could just run `picom` or `picom -b` in your terminal

my picom config located at `~/.config/picom.conf`

```
# Shadow
shadow = true;
# no-dnd-shadow = true;
detect-rounded-corners = true;
shadow-radius = 5;
shadow-offset-x = 1;
shadow-offset-y = 1;
shadow-opacity = .3;
shadow-ignore-shaped = false;
shadow-exclude = [
	"name = 'Notification'",
# workaround for conky until it provides window properties:
	"override_redirect = 1 && !WM_CLASS@:s",
    "class_g ?= 'Dmenu'",
#	"class_g ?= 'Dunst'",
# disable shadows for hidden windows:
	"_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
	"_GTK_FRAME_EXTENTS@:c",
# disables shadows on sticky windows:
#	"_NET_WM_STATE@:32a *= '_NET_WM_STATE_STICKY'",
# disables shadows on i3 frames
	"class_g ?= 'i3-frame'"
];

# shadow-exclude-reg = "x10+0+0";
# xinerama-shadow-crop = true;

#menu-opacity = 0.95;
#inactive-opacity = 0.93;
#active-opacity = 1;
#alpha-step = 0.01;
#inactive-dim = 0.0;
#blur-background = false;
#blur-kern = "3x3box";

fading = false;
fade-delta = 1;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-exclude = [ ];

backend = "xrender";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
detect-client-opacity = true;
unredir-if-possible = true;
refresh-rate = 0;
vsync = false;
dbe = false;
focus-exclude = [ "class_g = 'Cairo-clock'" ];
detect-transient = true;
detect-client-leader = true;
invert-color-include = [ ];
glx-copy-from-front = false;
use-damage = true;

#opacity-rule = [
#"99:name *?= 'Call'",
#"99:class_g = 'Chromium'",
#"99:name *?= 'Conky'",
#"99:class_g = 'Darktable'",
#"50:class_g = 'Dmenu'",
#"99:name *?= 'Event'",
#"99:class_g = 'Firefox'",
#"99:class_g = 'GIMP'",
#"99:name *?= 'Image'",
#"99:class_g = 'Lazpaint'",
#"99:class_g = 'Midori'",
#"99:name *?= 'Minitube'",
#"99:class_g = 'Mousepad'",
#"99:name *?= 'MuseScore'",
#"90:name *?= 'Page Info'",
#"99:name *?= 'Pale Moon'",
#"90:name *?= 'Panel'",
#"99:class_g = 'Pinta'",
#"90:name *?= 'Restart'",
#"99:name *?= 'sudo'",
#"99:name *?= 'Screenshot'",
#"99:class_g = 'Viewnior'",
#"99:class_g = 'VirtualBox'",
#"99:name *?= 'VLC'",
#"99:name *?= 'Write'",
#"93:class_g = 'URxvt' && !_NET_WM_STATE@:32a",
#"0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
#"96:_NET_WM_STATE@:32a *= '_NET_WM_STATE_STICKY'"
#];

wintypes :
{
  tooltip :
  {
    fade = true;
    shadow = false;
    opacity = 0.85;
    focus = true;
  };
  fullscreen :
  {
    fade = true;
    shadow = false;
    opacity = 1;
    focus = true;
  };
};
```

**Comment by fosskers** [comment]
I installed `picom` today and got this working.
