### ISSUE TITLE
mu4e does not allow scrolling (C-j and C-k)

### ISSUE THREAD

**Issue by altschuler** [syl20bnr/spacemacs#10313]
#### Description :octocat:
mu4e does not allow scrolling with `C-j` and `C-k` as described in the mu4e layer readme. **This is in the overview mode, not the header list.** I would suggest binding `C-j` and `C-k` to the same functionality as the up and down arrows in this view.

#### Reproduction guide :beetle:
- (setup mu4e)
- Start Emacs
- `SPC a M` to start mu4e
- `C-j` to go to next line

*Observed behaviour:* :eyes: :broken_heart:
Error saying "buffer is read-only"

*Expected behaviour:* :heart: :smile:
Cursor should move to the next line

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c130014f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby yaml javascript html typescript helm auto-completion better-defaults emacs-lisp git markdown org csharp
      (mu4e :variables mu4e-enable-notifications t mu4e-enable-mode-line t mu4e-use-maildirs-extension t)
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      (spell-checking :variables spell-checking-enable-by-default nil)
      syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by Miciah** [comment]
This issue is similar to (but less broad than) #4490.
