### ISSUE TITLE
Python 3rd party objects with names matching built-in objects incorrectly highlighted

### ISSUE THREAD

**Issue by tsoernes** [syl20bnr/spacemacs#10311]
With Python, syntax highlighting is a bit overeager.
`bool` in `np.bool'` is highlighted which it should not be since its not a Python type.
Similarly, `range` in `tf.range` is highligthed but should not be since its not a built-in function.
Perhaps a simple rule not to highlight types if they are preceded with a dot would suffice.

**Comment by Alexander-Miller** [comment]
> Perhaps a simple rule not to highlight types if they are preceded with a dot would suffice

It's certainly simple enough a change. If you want a quickfix for yourself grab the deifnition of `python-font-lock-keywords` and put a `(not (any "."))` before the `or` block containg bool and range.

**Comment by tsoernes** [comment]
Referring to the file `/usr/share/emacs/25.3/lisp/progmodes/python.el.gz`
```
    (,(rx symbol-start
          (not (any ".")) (or
           "abs" "all" "any" "bin" "bool" "callable" "chr" "classmethod"
         ....
```
No, that did not work, now the built-in functions are not highlighted at all (nor the 3rd party ones)

**Comment by tsoernes** [comment]
Yes, that did the trick. Having it as default would be nice though

2018-02-10 16:00 GMT+01:00 Alexander-Miller <notifications@github.com>:

**Comment by Miciah** [comment]
This looks like an issue that should be reported upstream.
