### ISSUE TITLE
Add proper autoload for find-by-pinyin-dired in Chinese layer

### ISSUE THREAD

**Issue by casouri** [syl20bnr/spacemacs#10325]
https://github.com/syl20bnr/spacemacs/blob/c130014ff0f263e14bd93786f880d2679958b484/layers/%2Bintl/chinese/packages.el#L73

**Comment by CeleritasCelery** [comment]
what is the ask here?

**Comment by casouri** [comment]
When using `use-package`, set `:defer t` without any other flag will make that package never load, right? I think there should be another flag like `commands:` or something.

**Comment by CeleritasCelery** [comment]
No that will just build autoloads from the autoload cookies in the file. Is it not loading for you?

**Comment by casouri** [comment]
Ok, I got it. No I saw some one complaining about one function cannot be found from that package. So I thought it is not loaded right. Since there is no problem, I will close this.

**Comment by CeleritasCelery** [comment]
If one of the functions is not auto loaded by the package it can be added to the `:commands` property.
