### ISSUE TITLE
What is the best way to switch from zsh plugins to eshell

### ISSUE THREAD

**Issue by lucasprag** [syl20bnr/spacemacs#10324]
Hi guys. I'm starting with spacemacs and I have a doubt that I couldn't figure out searching on the internet:

What is the best way to use something like the zsh plugins on eshell.

Per example, with [git, rails, ruby and bundler](https://github.com/lucasprag/dotfiles/blob/baea40fecf2381cd7ccc5879b053dfef0c07b2e7/zshrc#L9) plugins I have some commands like `be` for `bundle exec`, `gc` for `git commit` and so on.

I will be glad if someone could help me with that without creating aliases by hand.

Thank you very much.

**Comment by lucasprag** [comment]
I'm still figuring out how to customize the eshell layout, like change `~/P/i/d/projects/platform:bugfix/DEV-270-when-the-conciliation-process-tries* λ` to `platform:bugfix/DEV-270-when-the-conciliation-process-tries* λ`.

**Comment by Miciah** [comment]
Spacemacs installs the [eshell-prompt-extras](https://github.com/kaihaosw/eshell-prompt-extras) package, which is what provides that prompt.  Eshell-prompt-extras provides several "themes", including one ("epe-theme-pipeline") that claims to be similar to the oh-my-zsh prompt.  You could try that theme, or use it as an example for defining your own theme.

I used Zsh for about 15 years before I started seriously using Eshell, but I never tried oh-my-zsh.  Can you be more specific about what features from Zsh or oh-my-zsh you would like to see in Eshell?

**Comment by lucasprag** [comment]
Awesome, thank you @Miciah . =)
