### ISSUE TITLE
SPC f c - command spacemacs/copy-file, original file is left empty.

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#10327]
#### Description :octocat:
SPC f c, creats a new file but the original file is left empty.
SPC SPC copy-file works almost as expected: the origninal and new file have identical content (the current file is not pre-selected in Ivy as described in https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#files-manipulations-key-bindings).

In the help, these seem to be two different functions:
1) SPC h d k spacemacs/copy-file
2) SPC h d f copy-file

#### Reproduction guide :beetle:
- Start Emacs
- open a file
- SPC f c
- enter a new file name

*Observed behaviour:* :eyes: :broken_heart:
A new file is created but the original file is left empty.

*Expected behaviour:* :heart: :smile:
A new file is created and the original file is untouched.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(c-c++ emacs-lisp evil-snipe ivy org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
```

**Comment by CeleritasCelery** [comment]
`SPC f c` doesn't change the original file (though it won't save any unsaved changes either). Though it does remove the original file buffer so it will need to be reopened.

**Comment by wolfv6** [comment]
@CeleritasCelery this is what I am getting on my Spacemacs:
After creating and saving file f1 in Spacemacs, the directory contains f1 as expected:
```
$ ls
f1
$ cat f1
test
```

After SPC f c copy to f2, f1 is gone:
```
$ ls
 f2  '#f2#'
$ cat f2
test
```

**Comment by CeleritasCelery** [comment]
I cannot reproduce your example. It just makes a copy of f1 as expected.

**Comment by wolfv6** [comment]
Hmmm.
I am having other problems with Spacemacs as well, maybe they are all related: https://github.com/syl20bnr/spacemacs/issues/10348 and https://github.com/syl20bnr/spacemacs/issues/10347

When I commented the following line in my .spacemacs file, defun dotspacemacs/init () (setq-default :
```
dotspacemacs-auto-save-file-location 'original
```
then SPC f c copied normally.  So the bug is related to the above line.
