### ISSUE TITLE
Downgrading org-mode when enabling reveal-js

### ISSUE THREAD

**Issue by fluca1978** [syl20bnr/spacemacs#10322]
#### Downgrading org-mode when enabling reveal-js :octocat:
When I launch spacemacs I got `org-version` to 9.1.x, but when enabling
the reveal-js as for instructions available here:
<https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bemacs/org#revealjs-support>
with

```
...
   dotspacemacs-configuration-layers
   '(
     (org :variables org-enable-reveal-js-support t)
```

I see that `org-version` shows 8.2.1.
That makes org-mode unusable with recent features, including it to be unable to
export to reveal-js.
Any suggestion?

#### Reproduction guide :beetle:
- Start Emacs
- add `(org :variables org-enable-reveal-js-support t)`
- `M-x org-version`

*Observed behaviour:* :eyes: :broken_heart:
org-version is 8.2.1

*Expected behaviour:* :heart: :smile:
org-version should be 9.1.x

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
((org :variables org-enable-reveal-js-support t)
 php ivy emacs-lisp git markdown
 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND GSETTINGS NOTIFY LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by Miciah** [comment]
This upstream package issue looks relevant: https://github.com/yjwen/org-reveal/issues/324.  Unfortunately, the reporter of that issue closed it after working around the problem by doing something fiddly with the package manager and load path.

This Emacs bug report could be relevant: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30310.  It was closed in Emacs 26.1, so it might be worth trying Emacs 26.1 or newer if possible, although I am not confident that that fix will resolve this issue.

This Emacs bug report also could be relevant: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30321.  It remains open.

Before you enable `org-enable-reveal-js-support`, when you still have the newer org-mode package installed, what is the package's status? Use `SPC h d p org <Enter>` to check.

**Comment by fluca1978** [comment]
Sorry for late replying:

```
org is a built-in package.

     Status: Built-In.
    Summary: Outline-based notes management and organizer
Other versions: 20180823 (org), 9.1.13 (gnu).


Org is a mode for keeping notes, maintaining ToDo lists, and doing
project planning with a fast and effective plain-text system.

Org mode develops organizational tasks around NOTES files that
contain information about projects as plain text.  Org mode is
implemented on top of outline-mode, which makes it possible to keep
the content of large files well structured.  Visibility cycling and
structure editing help to work with the tree.  Tables are easily
created with a built-in table editor.  Org mode supports ToDo
items, deadlines, time stamps, and scheduling.  It dynamically
compiles entries into an agenda that utilizes and smoothly
integrates much of the Emacs calendar and diary.  Plain text
URL-like links connect to websites, emails, Usenet messages, BBDB
entries, and any files related to the projects.  For printing and
sharing of notes, an Org file can be exported as a structured ASCII
file, as HTML, or (todo and agenda items only) as an iCalendar
file.  It can also serve as a publishing tool for a set of linked
webpages.

Installation and Activation
---------------------------
See the corresponding sections in the manual at

  https://orgmode.org/org.html#Installation

Documentation
-------------
The documentation of Org mode can be found in the TeXInfo file.  The
distribution also contains a PDF version of it.  At the homepage of
Org mode, you can read the same text online as HTML.  There is also an
excellent reference card made by Philip Rooke.  This card can be found
in the doc/ directory.

A list of recent changes can be found at
https://orgmode.org/Changes.html

```

**Comment by fluca1978** [comment]
Self closing the issue, no update in a whole long time so I give up.
