### ISSUE TITLE
Haskell layer does not show show types.

### ISSUE THREAD

**Issue by AnthonyJacob** [syl20bnr/spacemacs#10337]
On startup :
```
C:\Users\Lenovo\AppData\Roaming\.emacs.d\elpa\flycheck-haskell-20160524.117\get-cabal-configuration.hs:42:59: error:
    Module
    `Distribution.PackageDescription'
    does not export
    `testEnabled'
   |
42 |         usedExtensions, allLanguages, hcOptions, exeName, testEnabled,
   |                                                           ^^^^^^^^^^^

C:\Users\Lenovo\AppData\Roaming\.emacs.d\elpa\flycheck-haskell-20160524.117\get-cabal-configuration.hs:43:25: error:
    Module
    `Distribution.PackageDescription'
    does not export
    `benchmarkEnabled'
   |
43 |         condTestSuites, benchmarkEnabled, condBenchmarks)
   |                         ^^^^^^^^^^^^^^^^
```
And when I hit `SPC-m-h-t` I get
```
haskell-interactive-session: No session associated with this buffer. Try M-x haskell-session-change or report this as a bug
```

**Comment by CeleritasCelery** [comment]
That is an emacs builtin function unrelated to Spacemacs. Have you tried the suggestion in the error message? Can you reproduce with stock emacs?

**Comment by AnthonyJacob** [comment]
I don't really know what the session is and How can I start it...

⁣

17. 2. 2018 5:57 PM, 5:57 PM, Troy Hinckley <notifications@github.com> napsal/a:

**Comment by CeleritasCelery** [comment]
https://github.com/serras/emacs-haskell-tutorial/blob/master/tutorial.md

**Comment by bapcyk** [comment]
It's valid with LSP even. But I see it in Doom Emacs too. But now such problem with Helix Editor on the same project (it uses LSP as well). Emacs shows type of simple functions like `pure` and nothing else (variables, etc, nothing).
