### ISSUE TITLE
Powerline looks ugly in active window, but works well in inactive windows.

### ISSUE THREAD

**Issue by sumitsahrawat** [syl20bnr/spacemacs#10339]
#### Description :octocat:

Powerline looks good only when window is not focused irrelevant of the `powerline-scale` settings.

#### Reproduction guide :beetle:
- Start Emacs
- Create a horizontal/vertical split

*Observed behaviour:* :eyes: :broken_heart:

The powerline looks great for the window that is not focused, but looks ugly for the focused window. Tweaking `powerline-scale` works, but then the powerline becomes too thick.

![2018-02-13-155301_swaygrab](https://user-images.githubusercontent.com/5645741/36145270-df7926aa-10d6-11e8-95be-3e11ae696ce0.png)

*Expected behaviour:* :heart: :smile:

The same look should be used for both the active and inactive windows.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by sumitsahrawat** [comment]
Found out that this is a duplicate of #1012. Closing.
For ArchLinux I solved it by installing `bdf-unifont`.

**Comment by jackgu1988** [comment]
`ttf-unifont` is also required (currently only on AUR) for best results.
