### ISSUE TITLE
auto-save does NOT remove the lock .#file

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#10347]
#### Description :octocat:
Auto-save does NOT remove the lock .#file

This might be related to https://github.com/syl20bnr/spacemacs/issues/10348

#### Reproduction guide :beetle:
This might be relevant: this is in my .spacemacs file, defun dotspacemacs/init () (setq-default :

    dotspacemacs-auto-save-file-location 'original

So all saves should be to the original file, not to an auto-save #file#

To reproduce the behavior:
1) open file in spacemacs
2) edit file and emacs creates a lock .#file
3) wait 30 seconds (or SPC SCP do-auto-save) and auto-save saves the file as expected, but the lock .#file remains
4) repeat with other files and the directory becomes cluttered with lock files
5) close emacs and the lock .#file remains

*Observed behaviour:* :eyes: :broken_heart:
Auto-save does NOT remove the lock .#file

note: opening locked file, edit, and SPC f s (save-buffer before auto-save) will remove lock .#file as expected.

*Expected behaviour:* :heart: :smile:
Auto-save removes the lock .#file

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(c-c++ emacs-lisp evil-snipe git ivy org shell spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by ssfrr** [comment]
I just hit this too, after wondering why I was sometimes getting these orphan lock files. I share org files over Dropbox and sometimes when switching computers I see the lock files still present even though neither machine has unsaved changes.

Rather than setting `dotspacemacs-auto-save-file-location` to `'original` I have `(setq auto-save-visited-file-name t)`, which I think should be doing the same thing, but I'm not sure which method is preferred. I tested both and they act the same (in the sense that the lock file is not deleted).

Any workarounds?

**Comment by sdwolfz** [comment]
Try adding this to your `dotspacemacs/user-config`:

```emacs-lisp
(setq create-lockfiles nil)
```

And you will never see lock files again 😉 .

**Comment by ssfrr** [comment]
Hah, I'd rather avoid the nuclear option if possible. I like the idea of lock-files and I'd want to know if I forgot to save in another session so I don't lose work.

**Comment by ssfrr** [comment]
For future folks in my situation, I added the following workaround in my `.spacemacs`:

```elisp
(defun sfr-save-org-buffers ()
  "Save all org buffers that are visiting a file"
  (mapc (lambda (buf)
          (if (buffer-file-name buf)
              (with-current-buffer buf (save-buffer))))
        (org-buffer-list 'files)))
```

and inside my `dotspacemacs/user-config` I have

```elisp
  (setq auto-save-timeout 300) ; number of idle seconds before saving
  (run-with-idle-timer auto-save-timeout t 'sfr-save-org-buffers)
```

So this will auto-save all my org buffers using `save-buffer`, which correctly removes the lockfile.
