### ISSUE TITLE
Spacemacs doesn't run the spec at point when using minitest with the spec syntax

### ISSUE THREAD

**Issue by lucasprag** [syl20bnr/spacemacs#10344]
#### Description :octocat:
The `ruby-test-run-at-point` doesn't run the spec at point when using minitest with the spec syntax.

Btw, it works well with rspec. 

#### Reproduction guide :beetle:
I created a project to simulate the problem: https://github.com/lucasprag/spacemacs-minitest-spec

- start Emacs
- open a test using minitest with the spec syntax like this:

```ruby
require 'minitest/spec'
require 'minitest/autorun'

describe Array do
  it "can be created with no arguments" do
    Array.new.must_be_instance_of Array
  end

  it "can be created with a specific size" do
    Array.new(10).size.must_equal 10
  end
end
```
- Type `SPC m t t` to run the `ruby-test-run-at-point` command.

*Observed behaviour:* :eyes: :broken_heart:
Emacs run the command but without all the needed params to work properly. (It missed the describe block)

```
-*- mode: compilation; default-directory: "~/Projects/labs/spacemacs-minitest-spec/minitest/" -*-
Comint started at Wed Feb 14 16:32:28

bundle exec ruby -I'lib:test' /home/lucas/Projects/labs/spacemacs-minitest-spec/minitest/array_test.rb --name "/"can be created with a specific size"/"
Run options: --name /can --seed 33009

# Running:



Finished in 0.000926s, 0.0000 runs/s, 0.0000 assertions/s.

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips

Comint finished at Wed Feb 14 16:32:28
```

*Expected behaviour:* :heart: :smile:
Emacs run the command with all the params like this:

```
ruby -I test minitest/array_test.rb --name='/Array\#test_\d _can be created with a specific size$/'

Run options: "--name=/Array\\#test_\\d _can be created with a specific size$/" --seed 30263

# Running:

.

Finished in 0.000814s, 1228.8560 runs/s, 1228.8560 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript yaml html ruby helm auto-completion emacs-lisp git markdown
            (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom))
```

Thank you =)

**Comment by lucasprag** [comment]
I forgot to say that the `ruby-test-run` (`SPC m t b`) works as expected.

**Comment by pmnhaes** [comment]
:+1:

**Comment by andsnleo** [comment]
omg, this :point_up:

**Comment by braytdp** [comment]
same problem here
