### ISSUE TITLE
Auto-save creates backup #file# after renaming the file

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#10348]
Auto-save creates a backup #file# after renaming the file.

This is in my .spacemacs file, defun dotspacemacs/init () (setq-default :

    dotspacemacs-auto-save-file-location 'original

So all saves should be saved to the original file, and NOT saved to an auto-save #file#

Saves are NOT to the original file.  This could confuse new Spacemacs users enough to cause them to lose data.  Please consider making this issue a High Priority.

This might be related to https://github.com/syl20bnr/spacemacs/issues/7927 https://github.com/syl20bnr/spacemacs/issues/10347 https://github.com/syl20bnr/spacemacs/issues/10327

#### Reproduction guide :beetle:
1) open file in spacemacs
2) SPC f R (spacemacs/rename-current-buffer-file) and rename file to file1
3) edit file1 but do not save it
4) wait 30 seconds (or SPC SCP do-auto-save) and auto-save creates #file1#
5) edit file and save

*Observed behaviour:* :eyes: :broken_heart:
Auto-save #file1# is created.
All saves (SPC f R or auto-save) are to auto-save #file1#.

*Expected behaviour:* :heart: :smile:
No auto-save #file1# is created.
All saves are to the original file1.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(c-c++ emacs-lisp evil-snipe git ivy org shell spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by CeleritasCelery** [comment]
Setting `dotspacemacs-auto-save-file-location 'original` just means to create an auto save file in same directory as the original file. If you don’t want an auto-save file created set this value to `nil`.

**Comment by wolfv6** [comment]
@CeleritasCelery 
Thanks for looking into this.  I am misinterpreting or the documentation is off.
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#location-of-auto-saved-files says:

> Auto-save of modified files can be performed in-place on the original file itself or in the cache directory (in this case the original file will remain unsaved).

My understanding is that `dotspacemacs-auto-save-file-location 'cache` will auto-save in same directory as the original file, and the original file will remain unsaved.
`dotspacemacs-auto-save-file-location 'original` will auto-save to the original file itself.

**Comment by CeleritasCelery** [comment]
> dotspacemacs-auto-save-file-location 'original will auto-save to the original file itself.

That would be no different then a regular save. 

`cache` will move all the auto saves to `.emacs.d/.cache` and `original` will keep the auto save in the original directory. If you feel that the documentation is unclear submit a PR that clarifies things.

**Comment by wolfv6** [comment]
I want a regular save every 30 seconds automatically.
In other words, auto-save modified files to the original file itself.
Is there a way to do that?

**Comment by CeleritasCelery** [comment]
You could write a function that saves the buffer on a timer. Shouldn’t be too hard. Though the question is, why don’t you want to use the builtin auto save? It’s more flexible because it won’t overwrite your file when you don’t want to.

**Comment by wolfv6** [comment]
I want to auto-save to the original file because my Linux crashes often, and it's easier to reboot and just keep going, rather than go through the file-recovery dance.

**Comment by CeleritasCelery** [comment]
Then you will have to roll your own implementation.

**Comment by wolfv6** [comment]
Normally my Spacemacs  auto-saves to the original file as described in the documentation.

#### Reproduction guide :beetle:
1) open file in spacemacs
2) edit file1 but do not save it
3) wait 30 seconds (or SPC SCP do-auto-save)

*Observed behaviour:
The file is auto-saved to the original file itself.
Verified by opening the file in another editor.
The directory time stamp indicates the time of auto-save.

But after SPC f R (spacemacs/rename-current-buffer-file) renaming the file, the auto-save behavior changes to saving to a #file# stored in the same directory (as described at the top of this thread).

I think that change in auto-save behavior is a bug, or a very strange feature.

**Comment by CeleritasCelery** [comment]
Looks like you were correct about the implementation of `original`. I misspoke.

**Comment by ssfrr** [comment]
Just to throw out another use case for auto-save on the original file - I sync my org-mode files across different computer using DropBox and the files tend to be actively open on the different machines. I don't always remember to save before I switch computers (e.g. leaving my work computer and going home), so my changes weren't always being propagated between machines and I was getting conflicts.

By auto-saving every 5min things stay better in sync, and by the time I sit at the other computer the changes have propagated to the open buffer (though lock files are still a problem, as in #10347). Maybe there's some other configuration where emacs would do a better job of noticing when an auto-save file is newer than the currently open one, but that wasn't happening.

**Comment by dijonkitchen** [comment]
Is there some work-around where we can edit how long it takes to auto-save? That might get us a better feedback loop on if there's an error (e.g., you'd see it in your git status faster).

**Comment by dijonkitchen** [comment]
Found some documentation here: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#auto-saving

The original PR implementing it might be useful too: https://github.com/syl20bnr/spacemacs/pull/1484

**Comment by hyiltiz** [comment]
@wolfv6  Your [comment above](https://github.com/syl20bnr/spacemacs/issues/10348#issuecomment-366480008) seem to have resolved the issue; if anything fancy is required, there are packages users can download and configure. 

Maybe consider closing this issue?

**Comment by wolfv6** [comment]
This is no longer an issue.  Solution documented at
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#location-of-auto-saved-files
