### ISSUE TITLE
Spacemacs spams my clipboard manager

### ISSUE THREAD

**Issue by x3rAx** [syl20bnr/spacemacs#10342]
This is actually not a bug report but a request for help.

Even though I'll use the bug tracker template as I think it will help me describing my problem.

#### Description :octocat:
I am using a clipboard manager (copyq) to keep track of the stuff I put on my clipboard. When using spacemacs, my clipboard manager gets filled with everything that gets killed within spacemacs. This means, when I type 'x' to delete a character, the character would appear on my clipboard manager.

Is there any way so that I can control what goes to the system clipboard and what not?

For example I would like to copy or delete lines using "y y" or "d d". This should be put in the system clipboard. But using "ciw" to delete a word and replace it with something else, this should not be sent to my clipboard. But it is okay, if it still goes to the kill ring.

#### Reproduction guide :beetle:
- Start Emacs (hybrid or evil mode)
- Open *scratch*
- Press `i` to change to insert mode
- Enter `This is an example.`
- Press `ESC` to enter normal mode
- Type `gg` to go to beginning of buffer
- Type `yy` to copy the whole line
- Paste into another editor (not spacemacs)
- Return to spacemacs and type `ciw` followed by `Here`
- Paste into the other editor again

*Observed behaviour:* :eyes: :broken_heart:
The "other" editor contains:

    This is an example.
    This

*Expected behaviour:* :heart: :smile:
The "other" editor should contain:

    This is an example.
    This is an example.

as the `ciw` should not change the system clipboard, the second line should be the same as the first one.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(javascript yaml python php markdown helm auto-completion emacs-lisp git)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by CeleritasCelery** [comment]
That is evil-modes emulation of vim behavior. When you delete something it is sent to the kill ring. So when you ran `ciw` it deleted the word `This` and put that in your clipboard. See #5750 for a solution

**Comment by x3rAx** [comment]
Oh sorry, I forgot to mention that I've tried that already but with moderate success. Sure, I could disable the usage of the system clipboard completely but I'd like to have several actions to use while others should not.

In the meantime I've played around with overwriting key bindings so that only certain actions would use the system clipboard (while having `(setq x-select-enable-clipboard nil)`) and I got it working for when I press `d` while in `visual mode` but I had trouble finding out how to tell emacs that for example `dd` should also put things to system clipboard.

Then I've tried it the other way around and wanted to _blacklist_ some actions. It worked for `x`, the clipboard was no longer flooded with single deleted characters but I had no idea how to do it with `ciw` for example.

The main problem seems to be that I have no idea how to bind those commands that make emacs (evil / vim) go into some "waiting-for-other-key-strokes" mode like pressing `d` or `c` does.

Also I had trouble findig the right emacs commands for some things I've tried. E.g. I wanted to copy selection in visual mode to clipboard (which I found out was `clipboard-yank`, I think). But for others I had no idea.. But hell its 2 or 3 days now since I gave up frustrated and can't remember now what it was...

For now it would be good to know how to overwrite `dd` or `ciw`.

**Comment by x3rAx** [comment]
One more thing: I tried things like remapping `x` to `"_x` using `(define-key map (kbd "x") (kbd "\"_x")` or so but that caused emacs to hang until I pressed `C-g` and then sometimes evil mode seems to be broken.

I think this is because `"_x` results in "pressing" `x` with will then again do `"_x` and so on. A perfect loop 😄. In vim you can do that using `nnoremap <x> "_x`. This seems to tell vim to just do the default action for `x` and not the remapped one. Is this somehow possible in emacs, too?

**Comment by thornjad** [comment]
@x3rAx have you been able to find any solution to this?

**Comment by jb55** [comment]
`(fset 'evil-visual-update-x-selection 'ignore)` in my `dotspacemacs/user-config` fixed this for me
