### ISSUE TITLE
~~Slow~~ Memory leak

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#10350]
#### Description :octocat:
~~Slow~~ memory leak ~~when a Python file is open.~~
I get the memory file with a C++ or LaTeX file too.

I saw this with Emacs 25.3 too, and updated to 26 in the hope it would be fixed.
#### Reproduction guide :beetle:
- Start Emacs
- Open a Python file
- Edit it, saving every so often

*Observed behaviour:* :eyes: :broken_heart:
Memory use grows, eventually causing swapping

*Expected behaviour:* :heart: :smile:
Constant memory use

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c130014f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-complete-with-key-sequence "<tab> <tab>" auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 colors emacs-lisp major-modes git markdown neotree org syntax-checking
 (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion t)
 typography
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 gpu
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "gibiansky")
 python pandoc latex html csv asm shell-scripts yaml semantic cscope dash ycmd javascript fasd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by CeleritasCelery** [comment]
You can use the built in [profiler](https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html) to see Emacs memory usage.

**Comment by beojan** [comment]
Here's the output:
![image](https://user-images.githubusercontent.com/3727925/36355153-93915a34-14df-11e8-947c-a5e24773d772.png)

**Comment by CeleritasCelery** [comment]
https://www.emacswiki.org/emacs/EmacsMemoryDebugging

**Comment by beojan** [comment]
When I manually run the garbage collector, nothing happens. I suspect
there's a configuration somewhere preventing garbage collection from
working (or it's a space leak).

**Comment by beojan** [comment]
Actually, it turns out I was running the garbage collector incorrectly. Now, `(garbage-collect)` reduces memory use a little, but not enough to solve the issue.

**Comment by beojan** [comment]
With some more investigation, switching from spaceline all-the-icons to the spacemacs spaceline theme helped.

Following that, spaceline-ml and semantic-lex are the functions using most of the memory.

**Comment by CeleritasCelery** [comment]
Interesting

**Comment by aaronjensen** [comment]
FWIW, I've moved away from spaceline to a customized version of the doom-modeline and emacs feels much faster, GC's way less often, even w/ a much lower gc limit:

```elisp
dotspacemacs-gc-cons `(,(* 16 1024 1024) 0.1)
```

**Comment by jbharat** [comment]
@aaronjensen can you share your customized version of doom-modeline

**Comment by aaronjensen** [comment]
Sure: https://gist.github.com/aaronjensen/32eb280a2ab67201dc350d6e392a3b65

**Comment by beojan** [comment]
After removing the semantic layer, the problem seems to be worse. The strange thing is that the `htop` reported memory use:
![emacs_os](https://user-images.githubusercontent.com/3727925/37768987-d599efd2-2dcf-11e8-8c45-baca232c1d8b.png)

Doesn't match what the `memory-usage` package reports (which is much lower):
![emacs_internal](https://user-images.githubusercontent.com/3727925/37769007-e6ff3912-2dcf-11e8-8f9c-0d31b37082a5.png)

**Comment by Voleking** [comment]
same issue here

**Comment by beojan** [comment]
This is definitely spacemacs related, since I don't see the issue with `emacs -q`. Is there any memory use which the `memory-usage` package doesn't report?

**Comment by CeleritasCelery** [comment]
I don’t think it reports memory usage for open buffers or emacs core.

**Comment by beojan** [comment]
> open buffers

Isn't that reported as `Buffer ralloc memory usage` and / or `151kB in buffers` above? I'm guessing the first is memory usage for the text, and the second is for lisp objects associated with a buffer?

> emacs core

Perhaps this is the culprit, though then it's strange the issue doesn't show up with `emacs -q`.

**Comment by CeleritasCelery** [comment]
If you can reliably reproduce the issue you could try it with `Spacemacs-base` and see if you still get the issue. That would really narrow down the potential problems. Also have you tried @aaronjensen ‘s suggestion of using a different modeline?

**Comment by LoLei** [comment]
Same here, makes my laptop unusable after like two hours.

**Comment by ahmednofal** [comment]
Thank you for the work on this project it is great but I have memory leak up to 4gigs.

**Comment by CeleritasCelery** [comment]
Have you checked the value of `gc-cons-threshold` to make sure garbage collection is happening?

**Comment by ahmednofal** [comment]
"Its value is 100000000
Original value was 800000"
thanks for you reply, are these the values ?

**Comment by CeleritasCelery** [comment]
Yes. you are telling it to not try and garbage collect until it reaches 100 MB in the heap. Though the default value of 800K is better, that still should not lead to 4 GB of leaks. Have you tried running the memory profiler?

**Comment by aaronjensen** [comment]
> Though the default value of 800K is better

Better in what context? In the past when I experimented with this (and the whole reason it's set higher in Spacemacs by default) is that a higher number allowed for fewer stutters when running with some of the more memory hungry (wasteful?) packages that come with Spacemacs.

That said, I prefer a hybrid approach where I set to to 100MB but then run this:

```emacs
  (defvar aj-gc-timer nil)
  (defun aj/maybe-gc ()
    (let ((original gc-cons-threshold))
      (setq gc-cons-threshold 800000)
      (setq gc-cons-threshold original
            aj-gc-timer (run-with-timer 2 nil #'aj/schedule-maybe-gc))))

  (defun aj/schedule-maybe-gc ()
    (setq aj-gc-timer (run-with-idle-timer 2 nil #'aj/maybe-gc)))

  (aj/schedule-maybe-gc)
```

**Comment by CeleritasCelery** [comment]
In my experience, the higher the number, the more noticeable the GC pauses. The lower the number the longer commands take to run. I found the default to be a good balance. I tried getting fancy with GC, but I would always shoot myself in the foot where it would get stuck at a large value and then I would have a memory leak.

**Comment by aaronjensen** [comment]
Yes, I agree. It can take a long time to gc with a 100mb limit. Fortunately for me, the fanciness I'm doing has worked well (without any memory leaks that I've seen) for almost a year. The 800k limit stuttered way too often for me, which made using Emacs closer to unbearable. I rarely notice the stutters now.

Oh, and also, if I remember correctly, at the time (I believe they've somewhat improved it) but using spaceline with an 800k threshold was pretty much a non-starter. Every other line move would trigger GC. It was unusable. I can't speak for how it is now, so if people are totally happy w/ 800k, they should use that.

**Comment by CeleritasCelery** [comment]
I am surprised you noticed sutter at 800 KB. the idea is that it is so low that GC pauses are imperceptible, even though they are frequent. I will have to give your idle-timer solution a try.

**Comment by aaronjensen** [comment]
It's been a while since I was dealing with it, but if I remember correctly it had to do with a longer running emacs session where it would have to check more objects for gc (that weren't ready for gc). It was enough to cause a stutter. Also, part of my context is that I have an extremely high key repeat rate and I make use of it a lot, so stutters are even more noticeable. I'm a little OCD about stutters/slowness 😄

**Comment by jbharat** [comment]
I have been using doom-emacs for sometime now. Its really fast with its bootup time. If anyone is interested https://github.com/hlissner/doom-emacs/wiki/FAQ. You can try to add few things from there to spacemacs. It may or may not work but worth trying.
