### ISSUE TITLE
SPC l is undefined

### ISSUE THREAD

**Issue by quangv** [syl20bnr/spacemacs#10356]
#### Description :octocat:
`SPC l is undefined`

trying to used layouts/workspaces

(I'm pretty new to Spacemacs, maybe I'm doing something wrong)

This also happens for me on `master` as well as `develop` branch.

Trying to follow the layous/workspaces docs here: http://spacemacs.org/doc/DOCUMENTATION.html#layouts-and-workspaces

#### Reproduction guide :beetle:
- Start Emacs
- hit Space, l (lowercase L)

*Observed behaviour:* :eyes: :broken_heart:
On the bottom it say:
`SPC l is undefined`

*Expected behaviour:* :heart: :smile:
Show layouts/workspaces commands?

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c130014)
- Graphic display: nil
- Distribution: spacemacs-base
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown vimscript html clojure helm emacs-lisp
          (keyboard-layout :variables kl-layout 'colemak-hnei))
```
- System configuration features: JPEG SOUND GPM DBUS NOTIFY LIBSELINUX GNUTLS LIBXML2 ZLIB MODULES

**Comment by CeleritasCelery** [comment]
Is persp-mode installed?

**Comment by bmag** [comment]
You are using spacemacs-base, which doesn't include layouts. You probably want to use the regular `spacemacs` distribution. Look in `.spacemacs` for the relevant variable ("something-distribution") and change it

**Comment by quangv** [comment]
Thanks! yes I am on `spacemacs-base`, switched it to `spacemacs` and `<SPC> l` is no longer undefined.
