### ISSUE TITLE
desktop-save saves to folder outside desktop-path

### ISSUE THREAD

**Issue by sampablokuper** [syl20bnr/spacemacs#10352]
#### Description :octocat:
In Spacemacs, `desktop-save` saves the desktop to a folder outside `desktop-path`.

#### Reproduction guide :beetle:

*N.B. I have never knowingly altered any variables relating to the `desktop` features of Emacs/Spacemacs on this machine. Therefore, whatever values they have, these values were likely set by the Debian Stretch `emacs25` package, or by the Spacemacs installer.*

Starting at a Bash prompt:

```
$ cd ~/myproject
$ ls -1
myfile
myotherfile
$ emacs25 myfile &
```
... continuing in Spacemacs (Vim-style):

```
:vsplit myotherfile
M-x desktop-save
```

Minibuffer then asks: `Directory to save desktop file in: /home/sampablokuper/.emacs.d/` . I press <kbd>RET</kbd>.

*Observed behaviour:* :eyes: :broken_heart:

Minibuffer responds with `Wrote /home/sampablokuper/.emacs.d/doc/.emacs.desktop.lock`. (Note the **doc** part of that path.) Also, `.emacs.desktop` is written to `~/.emacs.d/doc/`, despite the fact that this is neither the directory specified in the minibuffer, nor on my `desktop-path`.

The fact that `.emacs.desktop` is not on my `desktop-path` means that if I close Spacemacs, and then open Spacemacs again and run `M-x desktop-read`, Spacemacs says, `No desktop file.`.

*Expected behaviour:* :heart: :smile:

`.emacs.desktop` is written to the directory specified in the minibuffer, or at least to a directory on my `desktop-path`. Currently, the directories on my `desktop-path` are:

```
/home/sampablokuper/.emacs.d/.cache/
~/.emacs.d/
~                                   
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown yaml helm
          (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil)
          emacs-lisp org bibtex)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:

Even if I start Spacemacs with `emacs25 --debug-init myfile &`, and then run `M-x desktop-read` to trigger the `No desktop file.` message, no backtrace is produced.

**Comment by CeleritasCelery** [comment]
Can you reproduce with stock emacs?

**Comment by sampablokuper** [comment]
@CeleritasCelery wrote:
> Can you reproduce with stock emacs?

No, at least not by doing the following:

```
$ mv ~/.emacs.d ~/.emacs.d.old
$ cd ~/myproject
$ ls -1
myfile
myotherfile
$ emacs25 myfile &
```
in Emacs, I then used **C-x 1** (to close other windows) and then **C-x 3** (to open a new window at the right) and **C-x C-f** (to open `myotherfile` in that new window).

I then ran **M-x desktop-save**.

The minibuffer then asked: `Directory to save desktop file in: ~/.emacs.d/` . I pressed <kbd>RET</kbd>.

Unlike with Spacemacs, this resulted in:

```
$ tree -a ~/.emacs.d
/home/sampablokuper/.emacs.d
├── auto-save-list
│   └── .saves-15349-zian1~
├── .emacs.desktop
└── .emacs.desktop.lock

1 directory, 3 files
```

**Comment by sampablokuper** [comment]
@CeleritasCelery wrote:
> Can you reproduce with stock emacs?

No, at least not by doing the following:

```
$ mv ~/.emacs.d ~/.emacs.d.old
$ cd ~/myproject
$ ls -1
myfile
myotherfile
$ emacs25 myfile &
```
in Emacs, I then used **C-x 1** (to close other windows) and then **C-x 3** (to open a new window at the right) and **C-x C-f** (to open `myotherfile` in that new window).

I then ran **M-x desktop-save**.

The minibuffer then asked: `Directory to save desktop file in: ~/.emacs.d/` . I pressed <kbd>RET</kbd>.

Unlike with Spacemacs, this resulted in:

```
$ tree -a ~/.emacs.d
/home/sampablokuper/.emacs.d
├── auto-save-list
│   └── .saves-12379-myhostname~
├── .emacs.desktop
└── .emacs.desktop.lock

1 directory, 3 files
```
