### ISSUE TITLE
What's #'?

### ISSUE THREAD

**Issue by re-mx** [syl20bnr/spacemacs#10369]
Hello, I am an Emacs rookie.

Some spacemacs function names have `#'` in front of them。 but more spacemacs functions don't have it.
eg:
with `#'`:
```
(add-hook 'kill-buffer-hook #'spacemacs//add-buffer-to-killed-list)
```

without `#'`:
```
  (add-hook 'react-mode-hook 'spacemacs/js-doc-require)
```

I search for a moment, it seems that this symbol is used to indicate that followed by a function.
So why not all spacemacs functions take this symbol?

What is any special for those function with `#'`?

Sorry for my poor English.

Thank you very much!

**Comment by CeleritasCelery** [comment]
http://endlessparentheses.com/get-in-the-habit-of-using-sharp-quote.html

**Comment by re-mx** [comment]
I have read articles.

But I don't understand is why not all use?
