### ISSUE TITLE
Windows can't use colon in file/dir name, factor layer, : (colon) snippet name

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#10360]
#### Description :octocat:
The `factor` layer adds a snippet file with the name `:` (colon). This seems to be blocking windows users from pulling the latest `develop` branch.

It might be caused by windows not accepting a `:` (colon) in file or directory names.

In the Windows 10 File Explorer, if one tries to add a colon to a file or directory name, then a tooltip appears, saying:
>A file name can't contain any of the following characters:
\ / : * ? " < > |

#### Reproduction guide :beetle:
- Start Emacs on the Spacemacs `develop` branch
- Open `magit-status` (`SPC g s`) for the `.emacs.d` Spacemacs repository.
- Press `F` and "Pull into develop from" `origin/develop` (for me both `p` and `u` are listed as key bindings)

*Observed behaviour:* :eyes: :broken_heart:
The `magit-process-buffer` (opened by pressing: `$`), shows the git output:
>error: unable to create file layers/+lang/factor/local/snippets/factor-mode/:: Invalid argument

*Expected behaviour:* :heart: :smile:
The latest `develop` branch should update without errors.

#### Notes
*Possible solution:*
Maybe the snippet file should be renamed?

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c130014f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm emacs-lisp git org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
Bug introduced and fixed in develop, closing.
