### ISSUE TITLE
How to install and config lsp-mode for python

### ISSUE THREAD

**Issue by yssource** [syl20bnr/spacemacs#10363]
According to the the [README](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/lsp), I have lsp layer installed and configured in dot file, and then
`M-x lsp-capabilities` on a python file. But, it's always get message
`No language server is associated with this buffer`.
Any more details on [README](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/lsp) , it could help me?

**Comment by franksn** [comment]
`(python :variables python-backend 'lsp)`

on .spacemacs
as defined in config.el on the python layer.

**Comment by yssource** [comment]
@franksn thanks a lot. the server has started.
