### ISSUE TITLE
Python completion broken for the first Python buffer you visit

### ISSUE THREAD

**Issue by dsedivec** [syl20bnr/spacemacs#10366]
#### Description :octocat:
`company-backends` is not set up correctly the first time you open a Python buffer in Emacs.  (It is correct for subsequent buffers.)

#### Reproduction guide :beetle:
- Enable `python` and `auto-completion` layers in Spacemacs
- Start Emacs with Spacemacs `develop` branch
- Open a Python file

*Observed behaviour:* :eyes: :broken_heart:
`company-backends` has its global value, which notably does not include `company-anaconda`.

*Expected behaviour:* :heart: :smile:
`company-backends` has the appropriate value for a Python buffer, starting with `company-anaconda`.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 81a931f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(python helm auto-completion emacs-lisp neotree)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Additional information

I'm guessing this started at 81a931f48bdd6b.  I think the problem may be [the use of `python-mode-local-vars-hook`][1] to initialize company-mode for a Python buffer.  `hack-local-variables-hook` will, AFAIK, get run after `python-mode-hook`, so the hooks added by [`spacemacs//python-setup-anaconda-company`][2] will not be run for the first buffer.  They will be run for subsequent buffers.

By the way, if the intent was perhaps to let the user select between Anaconda and LSP for completion on a per-buffer basis, this would not work for the same reasons: by the time e.g. `spacemacs//python-setup-anaconda-company` is called, the mode hook has already run, and so `spacemacs|add-company-backends` will have no effect in the *current* buffer.

[1]: https://github.com/syl20bnr/spacemacs/blob/81a931f48bdd6bcca4fdf0a3baab7b4bd7695591/layers/%2Blang/python/packages.el#L75
[2]: https://github.com/syl20bnr/spacemacs/blob/81a931f48bdd6bcca4fdf0a3baab7b4bd7695591/layers/%2Blang/python/funcs.el#L41

**Comment by iromise** [comment]
I also met the problem, hope it can be fixed soon.

**Comment by changchunli** [comment]
I also met, but it hasn't be fixed. So I add this code in my config...
`(spacemacs//python-setup-anaconda-company)`

**Comment by et2010** [comment]
I can confirm. Company is  not setup as expected in the first python buffer.

**Comment by Miciah** [comment]
This looks like a duplicate of issue #10638, which was resolved in the develop branch by https://github.com/syl20bnr/spacemacs/commit/996cc91b5dc0494055813ccf660ad4e20658ae8f and https://github.com/syl20bnr/spacemacs/commit/7d19ba1711db953308d5ad04abee8b19e5f66859.
