### ISSUE TITLE
Wrong helm window placement

### ISSUE THREAD

**Issue by achikin** [syl20bnr/spacemacs#10372]
#### Description :octocat:
Helm window opens full width and right window disappears when two windows opened side-by-side
#### Reproduction guide :beetle:
- Start Emacs
- Split screen with SPC w /
- Open any helm search window SPC /
- Observe wrong behaviour (see screenshot below)
- Reload config with SPC feR
- Observe the right behaviour (see screenshot below)

*Observed behaviour:* :eyes: :broken_heart:
Helm opens below the both windows. The window that was not active at that moment disappears.
![screen shot 2018-02-21 at 13 11 31](https://user-images.githubusercontent.com/611419/36474807-badfad4e-1709-11e8-809f-b57e1cfcafdd.png)

*Expected behaviour:* :heart: :smile:
Helm opens only below the current window, leaving the second window unchanged.
![screen shot 2018-02-21 at 13 19 03](https://user-images.githubusercontent.com/611419/36474836-d37253a2-1709-11e8-87fd-63755b6ddb39.png)
#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(nginx org
       (helm :variables helm-position 'right)
       auto-completion better-defaults emacs-lisp git prodigy haskell markdown html go java sql
       (elm :variables elm-format-command "elm-format-0.18")
       javascript clojure evil-cleverparens themes-megapack)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by duianto** [comment]
I'm unable to reproduce this.

Helm opens below the two `SPC w /` split windows. Both before and after syncing the configuration layers `SPC f e R`. The same behaviour is observed on both the master and develop (c130014f not the latest) branches.

I see in your system info `Layers:` section, that you have:
```
       (helm :variables helm-position 'right)
```
But that doesn't seem to have any effect for me on the master branch. On the develop branch helm opens to the right of the two split windows.

Do you have any other custom helm settings?
Since the expected screenshot shows helm opened in the bottom left corner. I don't think helm does that by default.

**Comment by achikin** [comment]
@duianto I don't have any other custom helm settings. 

> Since the expected screenshot shows helm opened in the bottom left corner. I don't think helm does that by default.

The expected behavior for helm is to open below the current window, not in the bottom left corner. Let me add that to the ticket.

**Comment by duianto** [comment]
I'm now able to reproduce the disappearing second window issue on master.
I forgot that I had set:
```
(setq helm-always-two-windows nil)
```
in my user-config. There was a question about it recently in the gitter chat.
If you add that line to your user-config, then your non-selected windows, won't be hidden while helm is open. This issue has also been fixed on the develop branch.

I just found that there's a: `dotspacemacs-helm-position 'bottom` variable in `.spacemacs`
source: https://github.com/syl20bnr/spacemacs/issues/9044#issuecomment-309454459

When I changed it to `dotspacemacs-helm-position 'right`, and restarted Emacs, then helm opens to the right of the other open windows.

I seem to remember seeing helm opened below the current window, so we probably just have to find the right setting.

**Comment by achikin** [comment]
@duianto I realized that I have helm display function set already because of the recent helm issues

`  (with-eval-after-load 'helm
    (setq helm-display-function 'helm-default-display-buffer))
`

**Comment by duianto** [comment]
Setting `helm-display-function` to `'helm-default-display-buffer`, works for me on the develop branch.
The current window splits (top, bottom) and helm opens in the bottom half.

But on the master branch, helm opens in the next window.
For example:
With three windows split: left, middle, and right, and the left window is selected, then helm opens in the middle window.

**Comment by achikin** [comment]
@duianto thank you very much for your investigation and your help. I'm closing this ticket and waiting for the next release to confirm that helm is working as expected.
