### ISSUE TITLE
Bug with cursor movement when using python lsp backend

### ISSUE THREAD

**Issue by davidelbaze** [syl20bnr/spacemacs#10374]
#### Description :octocat:
Problems when navigating between lines of a python file when using python lsp backend.

#### Reproduction guide :beetle:
- Start Emacs
- Open a python file. Move the cursor in the buffer, and sometimes, the cursor will jump many lines away from where you wanted it to go.

*Observed behaviour:* :eyes: :broken_heart:
Move cursor to the line before, and the cursor goes to the first line of the buffer.
Example : 
[https://giphy.com/gifs/65FxicJBOnk9V6W4fL](https://giphy.com/gifs/65FxicJBOnk9V6W4fL)
In this video, I just use the right and up arrow key of my keyboard. Each frame of the gif correspond to a single action. You can see that when the cursor is on the comment line, under the ")", and after pressing the up arrow, the cursor goes to the beginning of the buffer.

*Expected behaviour:* :heart: :smile:
The cursor should move correctly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 81a931f4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 emacs-lisp
 (git :variables git-gutter-use-fringe t)
 version-control markdown org latex
 typography treemacs
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-enable-smart-eshell t)
 (c-c++ :variables c-c++-enable-clang-support t)
 rust
 (python :variables python-enable-yapf-format-on-save t python-shell-interpreter "python3" python-backend 'lsp python-fill-column 99 python-sort-imports-on-save t)
 (spell-checking :variables spell-checking-enable-by-default nil =enable-flyspell-auto-completion= t)
 syntax-checking lsp deft
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 imenu-list rebox shell-scripts speed-reading vinegar)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
Not relevent.

**Comment by bmag** [comment]
Probably this upstream issue: https://github.com/emacs-lsp/lsp-ui/issues/84
