### ISSUE TITLE
Document workaround for evil-escape issues with "jj".

### ISSUE THREAD

**Issue by person808** [syl20bnr/spacemacs#1037]
The [documentation](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#escaping) mentions problems with certain mappings for `evil-escape`. A simple workaround is to use `(add-hook 'evil-visual-state-entry-hook '(evil-escape-mode nil))`. Maybe this should be added to that section?

**Comment by syl20bnr** [comment]
But it disables evil-escape and you cannot use it to return to normal mode.

**Comment by person808** [comment]
Thats true, which is why its only a workaround

**Comment by syl20bnr** [comment]
The whole point of evil-escape is to give a no brainer sequence to escape everything , this workaround defeat this purpose :-)
