### ISSUE TITLE
github: missing key binding for magit-jump-to-pulls

### ISSUE THREAD

**Issue by kommen** [syl20bnr/spacemacs#10376]
For the `github` layer `magit-jump-to-pulls` is not mapped.

I'd expect it to be available with `gq` in magit status (`SPC g s`) as it is mapped to `jq` in magit-gh-pulls: https://github.com/sigma/magit-gh-pulls/blob/d526f4c9ee1709c79f8a4630699ce1f25ae054e7/magit-gh-pulls.el#L574

**Comment by kommen** [comment]
I tried to find a fix for that, but couldn't find the right place and way. Does this need to go in `keyboard-layout-packages`?

**Comment by Miciah** [comment]
Does the following work?
```elisp
(evil-define-key '(normal motion) magit-mode-map "gj" 'magit-jump-to-pulls)
```
If that works, you could place the following in `user-config` in your `.spacemacs`:
```elisp
(use-package magit-gh-pulls
  :config
  (evil-define-key '(normal motion) magit-mode-map "gj" 'magit-jump-to-pulls))
```
If you want to put it in a layer, you could probably put it in the definition of `github/pre-init-magit-gh-pulls` in `layers/+source-control/github/packages.el`.

**Comment by Miciah** [comment]
Note that you would be overriding the binding of `g j` to `magit-section-forward-sibling`.  I don't know whether the Spacemacs maintainers would accept a PR to do that.

**Comment by kommen** [comment]
@Miciah when I put `(define-key magit-mode-map "gq" 'magit-jump-to-pulls)` in `dotspacemacs/user-config` it works, but when I put it in here https://github.com/syl20bnr/spacemacs/blob/93ec42177e0d1584ecfa837258227f2210f5a499/layers/%2Bsource-control/github/packages.el#L77-L80 I get `Error (use-package): magit-gh-pulls/:config: Key sequence g q starts with non-prefix key g`

(Note I want to put it in `gq` not `gj` so that I don't override `magit-section-forward-sibling`)

I can't find the location where magit's default `j` keybindings get remapped to `g` in spacemacs...

**Comment by kommen** [comment]
I also tried `(evil-define-key '(normal motion) magit-mode-map "gq" 'magit-jump-to-pulls)` in both locations, but this doesn't seem to do anything.
