### ISSUE TITLE
bounded automatic-symbol-highlight?

### ISSUE THREAD

**Issue by vbauerster** [syl20bnr/spacemacs#10377]
There is a nice global toggle `SPC t h a`, which I'd like to enable for some specific file types only.
In other words, toggle `automatic-symbol-highlight` not at global level.
Is it feasible to achieve? How?

**Comment by imahajanshubham** [comment]
Hello vbauerster,

Try adding ~(spacemacs/toggle-automatic-symbol-highlight-on)~ to your ~user-config~ section. What I'm doing is manually toggling it to on, everytime the spacemacs is launched.

**Comment by vbauerster** [comment]
@imahajanshubham Thanks for advice, but this is not what I need.
What I'd like to achieve is to have `automatic-symbol-highlight` on for all file types (default behaviour), except `go-mode` (*.go file types), because for `go-mode` I have:

```
(add-hook 'go-mode-hook 'go-guru-hl-identifier-mode)
```

`automatic-symbol-highlight` and `go-guru-hl-identifier-mode` are exclusive, so I always find myself turning regular `automatic-symbol-highlight` off while editing go file.
It would be nice to let user to disable `automatic-symbol-highlight` for a specific major-mode.
