### ISSUE TITLE
Opening emacs-lisp files are so slowly

### ISSUE THREAD

**Issue by rynffoll** [syl20bnr/spacemacs#10381]
#### Description :octocat:
Opening emacs-lisp files are so slow

#### Reproduction guide :beetle:
- Start Emacs
- SPC f e d

*Observed behaviour:* :eyes: :broken_heart:
So slowly opening file (more than 3 seconds)

*Expected behaviour:* :heart: :smile:
Fast openning file

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ba13869c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(vimscript asciidoc
           (ansible :variables ansible-auto-encrypt-descrypt t)
           csv autohotkey nginx
           (ivy :variables ivy-enable-advanced-buffer-information t)
           treemacs
           (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
           better-defaults
           (org :variables org-want-todo-bindings t)
           (spell-checking :variables spell-checking-enable-by-default nil)
           syntax-checking
           (ibuffer :variables ibuffer-group-buffers-by 'projects)
           git
           (github :packages
                   (not magithub))
           (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left version-control-global-margin t)
           (shell :variables shell-default-shell 'eshell)
           docker systemd restclient ranger prodigy emacs-lisp
           (java :variables java-backend 'eclim)
           groovy kotlin scala
           (clojure :variables clojure-enable-fancify-symbols t)
           javascript typescript shell-scripts windows-scripts sql html yaml markdown react colors erc
           (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
           evil-commentary imenu-list command-log search-engine osx rynffoll)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by rynffoll** [comment]
<img width="1552" alt="2018-02-23 1 29 10" src="https://user-images.githubusercontent.com/5983502/36567892-0d63668e-1839-11e8-8c98-afc11a5d45dd.png">

**Comment by rynffoll** [comment]
The same situation with org-mode files. 😞

**Comment by sdwolfz** [comment]
Looks like yasnippet is responsible for the bulk of the slowdown. If you do not use snippets you can try disabling it, here is how I do it, but there might be a better way:

```emacs-lisp
dotspacemacs-excluded-packages '(auto-yasnippet yasnippet yasnippet-snippets)
```

**Comment by rynffoll** [comment]
I tried it and it works for emacs-lisp files, but excluding packages didn't solve problem with org-mode.
And I want to use snippets.

**Comment by Alexander-Miller** [comment]
The first org file will always open slowly, since org is 1) huge and 2) lazy loaded. Org files should open much faster after the first time. AFAIK the same goes for yasnippet, the snippets should only need loading once. 

What does the profiler say after you've opened multiple files?

**Comment by rynffoll** [comment]
Second opening is much faster than first.

**Comment by duianto** [comment]
@rynffoll The observed and expected descriptions need to be swapped.

**Comment by Alexander-Miller** [comment]
If you want those snippets you won't get rid of those loading times. The only question is *when* those items are loaded. As I see it there are 2 possible remedies that may or may not help, depending on your workflow:

 * You can load org/snippets on an idle timer. If emacs has been idle for x seconds things are loaded automatically, while you are doing something else.

 * You eagerly load org & snippets right from the start. This will increase load times, so it works best if rarely restart emacs. For this option you can also look into running emacs as a daemon.

**Comment by rynffoll** [comment]
Thanks for explanations, I think, you can close my request.

**Comment by aaronjensen** [comment]
@rynffoll could you close your request please? We do not have the power ⚡️
