### ISSUE TITLE
Spacemacs trying to re-install setq package at each boot

### ISSUE THREAD

**Issue by x61** [syl20bnr/spacemacs#10388]
Each time I start spacemacs, I get the following message:

Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: setq@dotfile... [1/1]
Package setq is unavailable. Is the package name misspelled?

I also get the following message.
(Spacemacs) --> installing package: setq@dotfile... [1/1]
(Spacemacs) Warning: tern binary not found!

It's a warning but I just want to know if there is something I can do for it to disappear. 

Here is my system inform#### System Info :computer:
-------------------------------------------------------
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 671701f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript helm auto-completion better-defaults emacs-lisp git markdown org evil-commentary
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking version-control c-c++ python ranger games latex ess xkcd sql)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by bmag** [comment]
> `installing package: setq@dotfile`

That means you have `setq` listed in your list of additional packages. What's the value of `dotspacemacs-additional-packages`? You probably need to change it.

(usual format is "`installing package: <package>@<layer>`", but for additional packages "dotfile" is listed as the layer)

**Comment by hyiltiz** [comment]
@x61 If it is resolved, please consider closing this.

**Comment by duianto** [comment]
We'll close this since the issue might just have been a `.spacemacs` typo.
