### ISSUE TITLE
"Contacting host: www.google.com:80 [3 times]"

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#1038]
Which package could be causing this to happen randomly while I am editing markdown files? 
Here's a screenshot with the relevant message highlighted.

![screen shot 2015-04-03 at 3 27 09 pm](https://cloud.githubusercontent.com/assets/302945/6978899/1dbd8bfe-da16-11e4-99d5-198e2b65e1c0.png)

**Comment by syl20bnr** [comment]
That's a good question, maybe `google-translate` ?

**Comment by sooheon** [comment]
Will go ahead and tentatively close this, updates to spacemacs and Emacs to 24.5 seem to have made it disappear.
