### ISSUE TITLE
Opening a file from *spacemacs* with the mouse pastes primary clipboard

### ISSUE THREAD

**Issue by iGEL** [syl20bnr/spacemacs#10380]
#### Description :octocat:
Clicking with the mouse on a file in `*spacemacs*` buffer causes to paste the content of the primary linux clipboard into the opened file.

#### Reproduction guide :beetle:
- Select some text in some program, so it populates the primary clipboard
- Start Emacs
- *Left* click on a file in the recent file list

*Observed behaviour:* :eyes: :broken_heart:

The content of the primary buffer is pasted at some location in the newly opened file. This does not happen when using the keyboard to open the file nor does it when clicking the file name in Dired.

*Expected behaviour:* :heart: :smile:

Just open the file without pasting anything :wink:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(clojure csv emacs-lisp
         (elm :variables elm-format-on-save t)
         git haskell helm html javascript markdown nginx python ruby spell-checking sql syntax-checking terraform yaml
         (version-control :variables version-control-diff-side 'left))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

You can find my .spacemacs [here](https://github.com/iGEL/dotfiles/blob/8ae42e3a72d1a778d5e0efd63c431df5c68a8203/spacemacs)

The only part missing is this
```elisp
'(safe-local-variable-values
   (quote
    ((flycheck-ruby-rubocop-executable . "/home/xxx/dev/webapp/bin/drubocop"))))
```

**Comment by duianto** [comment]
This sounds like duplicate of:
Auto paste into the files opened by mouse-click the item below Recent Files in Spacemacs buffer #5435

The solution there seems to be to add:
```
(add-hook 'spacemacs-buffer-mode-hook (lambda ()
(set (make-local-variable 'mouse-1-click-follows-link) nil)))
```
to the `dotspacemacs/user-config` section of your `.spacemacs`.
source: https://github.com/syl20bnr/spacemacs/issues/5435#issuecomment-195862080

**Comment by iGEL** [comment]
Right, thanks!
