### ISSUE TITLE
testing.Error `Causes possible formatting directive in error call`

### ISSUE THREAD

**Issue by kuberlog** [syl20bnr/spacemacs#10385]
#### Description :octocat:
testing.Error() causes `possible formatting directive in error call`

#### Reproduction guide :beetle:
- Start Emacs

			t.Error("ScaledDatumWithDelta.values[%f] expected to = %f but equals %f", 1.0, 1.0, 1.0)

*Observed behaviour:* :eyes: :broken_heart:
Marks the line with an error: `possible formatting directive in error call`

*Expected behaviour:* :heart: :smile:
No Error

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. c130014f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(php javascript html helm auto-completion clojure emacs-lisp common-lisp go git
     (markdown :variables markdown-live-preview-engine 'vmd)
     org spell-checking syntax-checking protobuf)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by Miciah** [comment]
Why do you expect no error? Your string has formatting directives, and you are passing it to a function that does not expect a format string.  See [the documentation for `T.Error`](https://golang.org/pkg/testing/#T.Error).  Did you mean to use `t.Errorf`?

Anyway, the error you report is coming from `go vet`:

1. Create `error.go` with the following content:
```go
package main

import (
	"testing"
)

func TestExample(t *testing.T) {
	t.Error("ScaledDatumWithDelta.values[%f] expected to = %f but equals %f", 1.0, 1.0, 1.0)
}
```
2. Run `go vet error.go`:
```
% go vet error.go
# command-line-arguments
./error.go:8: Error call has possible formatting directive %f
zsh: exit 2     go vet error.go
```

If `go vet` is in error, that is an upstream issue in the Go toolchain (but I don't think `go vet` is in error here).

Meanwhile, if you want to disable messages from `go vet`, you can prevent Spacemacs from running it using the following:
```emacs-lisp
(defun disable-go-vet ()
  (push 'go-vet flycheck-disabled-checkers))
(add-hook 'go-mode-hook #'disable-go-vet)
```
