### ISSUE TITLE
n command in treemacs buffer

### ISSUE THREAD

**Issue by iromise** [syl20bnr/spacemacs#10389]
#### Description :octocat:

`n` in treemacs dose not work.

#### Reproduction guide :beetle:
- Start Emacs
- open treemacs
- press `n` in treemacs buffer

*Observed behaviour:* :eyes: :broken_heart:
cursor does not move to next line.

*Expected behaviour:* :heart: :smile:
cursor should move to next line.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 81a931f4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(yaml
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'term shell-default-term-shell "/bin/zsh")
 tmux helm
 (spell-checking :variables spell-checking-enable-auto-dictionary nil)
 syntax-checking
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t)
 treemacs semantic better-defaults imenu-list shell-scripts windows-scripts emacs-lisp
 (markdown :variables markdown-live-preview-engine 'vmd)
 (latex :variables latex-enable-folding t)
 lsp
 (javascript :variables javascript-disable-tern-port-files nil js2-basic-offset 2 js-indent-level 2)
 (python :variables python-backend 'lsp python-enable-yapf-format-on-save t python-sort-imports-on-save t python-fill-column 177)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t c-c++-enable-clang-format-on-save t)
 (osx :variables osx-command-as 'hyper osx-option-as 'meta osx-control-as 'control osx-function-as 'none osx-right-command-as 'left osx-right-option-as 'left osx-right-control-as 'left)
 (colors :variables colors-enable-nyan-cat-progress-bar
         (display-graphic-p))
 git org)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by Alexander-Miller** [comment]
> Editing style: hybrid

That means you're still loading evil, right? In that case treemacs' evil integration is activated and your navigation should be done with j/k. 

You can still use n/p by overwriting evil's keybinds like this: `(define-key evil-treemacs-state-map (kbd "n") #'treemacs-next-line)`

**Comment by iromise** [comment]
> (define-key evil-treemacs-state-map (kbd "n") #'treemacs-next-line)

It works, But it seems strange that `p` works in the treemacs buffer when i use hybrid style. In my opinion, `n/p` and `j/k` should both works in treemacs buffer as the [following](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bfiletree/treemacs#inside-treemacs) said

> Treemacs will use either j/k or n/p to go to the next/previous line, depending on whether vim/hybrid editing style is used. Likewise refresh is only bound to g when emacs editing style is used, since under vim g is a prefix for many other commands.

**Comment by Alexander-Miller** [comment]
Either/or is exclusive, so the docs aren't wrong as far as I'm concerned. The fact that p works and n doesn't is just "chance", and depends on which keys evil overwrites. 

As for enabling both my answer is no: for evil/hybrid users n is already bound to `evil-ex-search-next`. It's a reasonable assumption that people are using evil's search in treemacs and then use n/N to jump between results. If I do away with that I'll just receive complaints from the other side.

**Comment by iromise** [comment]
Ok, Thanks a lot.
