### ISSUE TITLE
helm-M-x: Symbol’s function definition is void: helm-xref-show-xrefs

### ISSUE THREAD

**Issue by myrgy** [syl20bnr/spacemacs#10394]
#### Description :octocat:
helm-M-x: Symbol’s function definition is void: helm-xref-show-xrefs
I tried to disable deferred `helm-xref` package loading - then everything works fine.

I'm facing similar issue with helm-ctest package. It's not loaded propertly, but works fine if I force it's loading using `M-x  helm-ctest`.

Info: cpp2 layer force to load lsp and cquery layer.

#### Reproduction guide :beetle:
- Start Emacs
- open some file
- pressing `M-?`

*Observed behaviour:* :eyes: :broken_heart:
helm-M-x: Symbol’s function definition is void: helm-xref-show-xrefs

*Expected behaviour:* :heart: :smile:
show the list of usages using helm-xref

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.300.0
- Spacemacs branch: my_cq (rev. 757d8c7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv lua yaml python ruby rust go graphviz pdf-tools helm
     (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup nil)
     docker semantic emacs-lisp git github markdown javascript gpu org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control
     (cpp2 :variables c-c++-default-mode-for-headers 'c++-mode)
     (plantuml : variables org-plantuml-jar-path "~/.spacemacs.d/plantuml.jar")
     treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>

**Comment by cormacc** [comment]
I've just encountered the same issue -- seems to be because of a mssing :commands section in the helm layer packages.el. Just raised a PR...
https://github.com/syl20bnr/spacemacs/pull/10397

**Comment by myrgy** [comment]
@cormacc , do you know how to configure 'use-package' to propertly load package based on bindings?
```
(defun cmake/init-helm-ctest ()
  (use-package helm-ctest
    :defer t
    :config
    (dolist (mode cmake-modes)
      (spacemacs/set-leader-keys-for-major-mode mode
        "pt" 'helm-ctest))))
```

**Comment by cormacc** [comment]
@myrgy I'm afraid I don't. That fix was just an educated guess based on a quick scan of the helm layer files -- my lisp-fu is weak.

**Comment by syl20bnr** [comment]
Should be fixed.
