### ISSUE TITLE
`TAB` does not toggle current occurrence in `iedit state`

### ISSUE THREAD

**Issue by thebearmayor** [syl20bnr/spacemacs#10398]
#### Description :octocat:
`TAB` does not toggle current occurrence in `iedit state`. When cursor is on an occurrence, `TAB` is bound to `iedit-next-occurrence` instead of `iedit-toggle-selection`. When cursor is not on an occurrence, `TAB` is bound to `iedit-toggle-selection`, but it still does not work, as it is not on a selection.

See [docs](http://spacemacs.org/doc/DOCUMENTATION.html#replacing-text-with-iedit) for expected keybinding.

#### Reproduction guide :beetle:
- Start Spacemacs in Evil mode
- Move cursor to `The` in banner text
- Press `SPC s e` to enter `iedit state` with several occurrences
- Press `TAB`

*Observed behaviour:* :eyes: :broken_heart:
- Cursor moves to next occurrence.
- Current occurrence remains active.

*Expected behaviour:* :heart: :smile:
- Current occurrence becomes inactive.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 64cf9f56f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion clojure dash deft docker elm elixir emacs-lisp evil-commentary finance git github
                 (go :variables gofmt-command "goimports")
                 html ivy javascript
                 (markdown :variables markdown-live-preview-engine 'vmd)
                 (org :variables org-enable-github-support t org-projectile-file "notes.org")
                 python puppet
                 (ruby :variables ruby-version-manager 'rbenv)
                 ruby-on-rails
                 (shell :variables shell-default-term-shell "/usr/local/bin/fish" shell-default-height 30 shell-default-position 'bottom)
                 scala shell-scripts sql syntax-checking terraform themes-megapack version-control yaml)
```
- System configuration features: JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS LCMS2

#### Backtrace :paw_prints:
```

```

**Comment by siddharthshekar** [comment]
I am seeing this as well.

**Comment by duianto** [comment]
I remember pressing `TAB` to toggle the iedit occurrence under the cursor, a while back (possibly a couple of months ago), but now `M-;` toggles the current occurrence.

The `iedit` `M-;` binding, seems to take precedence over the `evil-iedit-state` `[tab]` binding.

`M-;` is bound here in the `iedit` package:
https://github.com/victorhge/iedit/blob/412490db4387ad9d040bfb5854f25de4c40c2146/iedit.el#L295 
```
    (define-key map (kbd "M-;") 'iedit-toggle-selection)
```

And `[tab]` is bound here in the `evil-iedit-state` package:
https://github.com/syl20bnr/evil-iedit-state/blob/02ce7ea1414aa0f139b52f1b3350c2b7af74d0ba/evil-iedit-state.el#L229
```
(define-key evil-iedit-state-map [tab] 'iedit-toggle-selection)
```

There's also a strange behaviour, when an occurrence has been toggled off with `M-;`. When the cursor still is on the deselected occurrence, then `TAB` selects it. Otherwise, when the cursor is on a selected iedit occurrence then `TAB` moves to the next one.

When the cursor is on an iedit occurrence, then `SPC h d k TAB` shows:
> `<tab>` runs the command iedit-next-occurrence (found in iedit-occurrence-keymap),
> which is an interactive compiled Lisp function in ‘iedit-lib.el’.
> 
> It is bound to `<tab>`, TAB, n.
> 
> (iedit-next-occurrence)

But after pressing `M-;` to deselect it, then `SPC h d k TAB` shows:
> `<tab>` runs the command iedit-toggle-selection (found in evil-iedit-state-map),
> which is an interactive compiled Lisp function in ‘iedit.el’.
> 
> It is bound to `<tab>`, M-;.
> 
> (iedit-toggle-selection)

**Comment by thebearmayor** [comment]
I suspect [this PR](https://github.com/syl20bnr/evil-iedit-state/pull/10/files) has it right. Based on [docs](https://www.emacswiki.org/emacs/TabKey) and [this answer](https://emacs.stackexchange.com/a/9634) I suppose `evil-iedit-state` needs to bind both `TAB` and `<tab>` because something else is binding them separately. Also see [iedit-occurrence-keymap-default](https://github.com/victorhge/iedit/blob/412490db4387ad9d040bfb5854f25de4c40c2146/iedit-lib.el#L186).

**Comment by duianto** [comment]
Adding:
```
(define-key evil-iedit-state-map (kbd "TAB") 'iedit-toggle-selection)
```
as suggested by the PR:
Bind "TAB" in addition to [tab] https://github.com/syl20bnr/evil-iedit-state/pull/10

Didn't help. `TAB` still moves to the next occurrence.

But commenting out these two bindings, in `iedit-lib.el`:
```
    (define-key map (kbd "TAB") 'iedit-next-occurrence)
    (define-key map (kbd "<tab>") 'iedit-next-occurrence)
```
in both of the iedit variables (it doesn't work if only one set of bindings are commented out): 
`iedit-lib-keymap` https://github.com/victorhge/iedit/blob/412490db4387ad9d040bfb5854f25de4c40c2146/iedit-lib.el#L177
and `iedit-occurrence-keymap-default` https://github.com/victorhge/iedit/blob/412490db4387ad9d040bfb5854f25de4c40c2146/iedit-lib.el#L192

Makes `TAB` toggle the occurrence again.

Maybe this means that the iedit `TAB` bindings are called after the `iedit-evil-state` `TAB` binding.

I don't know how to change the loading order.

**Comment by bpic** [comment]
I would also be interested in a fix for this.
Is there anything I can do to help ?

**Comment by syl20bnr** [comment]
Should be fixed in develop.

**Comment by bpic** [comment]
It is indeed, that's awesome, thank you!
