### ISSUE TITLE
Recommended strategy for version controlling private layers

### ISSUE THREAD

**Issue by dangom** [syl20bnr/spacemacs#10390]
As per the [spacemacs documentation](https://github.com/syl20bnr/spacemacs/tree/master/private), private layers should be placed in the private folder within .emacs.d.

This makes it hard to properly version control said private layers, as they are nested within the spacemacs repo. Although it does work to have a git repo nested within a git-ignored folder of a parent repo, this setup is rather fragile. A `git clean -fdx` would nuke everything.

What is the recommended setup for developing private layers?

**Comment by bmag** [comment]
Another option is to have a `~/.spacemacs.d` directory. You use `~/.spacemacs.d/init.el` as your dotspacemacs file instead of ~/.spacemacs`, and you put private layers in that directory as well. It should be mentioned in the docs somewhere.

**Comment by dangom** [comment]
@sdwolfz Indeed, I didn't know that other repos would be skipped. Quite a positive surprise =)
In my case, the private layer would survive, but all my non vc'd snippets would be removed.

@bmag The docs do mention that. Not in the private layer README, but [here](http://spacemacs.org/doc/DOCUMENTATION.html#alternative-dotdirectory).

**Comment by fiveNinePlusR** [comment]
Is there really any benefit to having two ways to do this? having the default way to setup spacemacs being as a configuration directory under `~/.spacemacs.d` is a clear win in usability to me. you could also have the folder template skeleton for layers, snippets whatever else put in place with a few examples to make adoption easier for new users. I say the default should be the configuration directory separate from `~/.emacs.d`
