### ISSUE TITLE
Restart stock emacs and emacs cannot locate ELPA packages

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#10395]
#### Description :octocat:
Emacs cannot find `use-package` when I hit `SPC q D` to restart stock emacs.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC q D`

**All my ELPA packages are under `~/.emacs.d/elpa/develop`**

*Observed behaviour:* :eyes: :broken_heart:
Stock emacs started but with an error `No such file or directory use-package` indicating emacs cannot locate the package.

*Expected behaviour:* :heart: :smile:
Stock emacs started with package loaded.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: work (rev. 439ccdd9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :disabled-for org latex)
 ansible better-defaults bibtex chrome csv dash docker emacs-lisp
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 font-lock-studio git html ibuffer imenu-list javascript latex markdown nlinum
 (org :variables org-projectile-file "TODOs.org" org-enable-reveal-js-support t org-reveal-js "file:///home/neoarch/git/reveal")
 org-config
 (han :variables han-enable-youdao-dict t han-enable-fcitx t han-org-line-spacing 0.2)
 pdf-tools
 (plantuml :variables org-plantuml-jar-path "/usr/bin/plantuml" plantuml-jar-path "/usr/bin/plantuml")
 python rcirc
 (rebox :variables rebox-style-loop
        '(71 72 73))
 ruby-on-rails scimax
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts spell-checking syntax-checking tldr treemacs
 (version-control :variables git-gutter+-disabled-modes
                  '(image-mode org-mode))
 w3m whizzytex yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

Note that I'm on a private branch based on develop. It's slightly different from the original.

**Comment by CeleritasCelery** [comment]
Emacs looks for packages under `~/.emacs.d/elpa/`
