### ISSUE TITLE
Deferred packages loading & key bindings

### ISSUE THREAD

**Issue by myrgy** [syl20bnr/spacemacs#10402]
I noticed that after migration on deferred packages loading some key-bindings are not available till I manually force package loading.

Here is similar issue: https://github.com/syl20bnr/spacemacs/issues/10394
but it was fixed due to the usage of `commands` keyword of `use-package`.
But it's doens't make any sense to use `use-package` `bind` instead of `spacemacs/set-leader-keys-for-major-mode`

I tried to find proper way to perform key bindings in [spacemacs documentation](https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#use-package),  but there is no hints.

```
(defun cmake/init-helm-ctest ()
  (use-package helm-ctest
    :defer t
    :config
    (dolist (mode cmake-modes)
      (spacemacs/set-leader-keys-for-major-mode mode
        "pt" 'helm-ctest))))
```
@syl20bnr , could you please tell if there's any proper way to achieve same behaviour as with 
`(use-package   :bind)`?

Same things was for me with `spacemacs|use-package-add-hook projectile` with `:post-config`.
 It doesn't work for me.
When I replaced it with `(with-eval-after-load 'projectile` - which works fine

**Comment by syl20bnr** [comment]
Fixed in develop branch.
