### ISSUE TITLE
develop: broken unimpaired shortcuts

### ISSUE THREAD

**Issue by vbauerster** [syl20bnr/spacemacs#10409]
#### Description :octocat:
broken unimpaired shortcuts <kbd>[</kbd><kbd>]</kbd>

#### Reproduction guide :beetle:
- Start Emacs
- Try `] spc` for example.

*Observed behaviour:* :eyes: :broken_heart:
`] spc` is undefined

*Expected behaviour:* :heart: :smile:
New line insert below the current one.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5c251f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org git
      (version-control :variables version-control-diff-side 'left)
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip t)
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      (spell-checking :variables spell-checking-enable-by-default nil)
      html markdown neotree yaml python javascript rust
      (go :variables go-tab-width 4 gofmt-command "goimports" go-use-gometalinter t godoc-at-point-function 'godoc-gogetdoc)
      protobuf docker themes-megapack dash semantic
      (ranger :variables ranger-show-preview t ranger-show-literal t ranger-max-preview-size 4)
      (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by NightMachinary** [comment]
See https://github.com/syl20bnr/spacemacs/issues/10411 for my workaround.

**Comment by bmag** [comment]
Fixed by https://github.com/syl20bnr/spacemacs/commit/f84ab9af8fb9de33ef3a4e044ade07cd082cdfc9, please report if there are still issues.
