### ISSUE TITLE
Commit 29c78ce on develop branch breaks the hybrid editing style.

### ISSUE THREAD

**Issue by heartnheart** [syl20bnr/spacemacs#10405]
#### Description :octocat:
Commit 29c78ce841 on develop branch breaks the hybrid editing style.

#### Reproduction guide :beetle:
- Start Emacs
- Use the latest develop spacemacs develop branch (4fe1600 as the time of writing).
- Set `dotspacemacs-editing-style` to `'hybrid`
- Press `i` to enter hybrid-state

*Observed behaviour:* :eyes: :broken_heart:
Vim Insert state is entered (state color is green).

*Expected behaviour:* :heart: :smile:
Hybrid-state should be entered (state color should be blue)

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. 1e6a0a66)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(groovy github emoji treemacs dash
        (helm :variables helm-org-show-filename t helm-org-headings-fontify t)
        (auto-completion :variables auto-completion-enable-help-tooltip t)
        pdf-tools latex better-defaults emacs-lisp git markdown
        (org :variables org-enable-github-support t)
        common-lisp
        (c-c++ :variables c-c++-enable-clang-support t c-c++-enable-rtags-support t c-c++-default-mode-for-headers 'c++-mode)
        (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell nil)
        (cmake :variables cmake-enable-cmake-ide-support t)
        python spell-checking syntax-checking
        (gtags :variables gtags-enable-by-default nil)
        semantic
        (deft :variables deft-directory "~/notes")
        (chinese :variables chinese-enable-fcitx t chinese-enable-youdao-dict t pyim-default-scheme 'xiaohe-shuangpin fcitx-active-evil-states
                 '(insert emacs hybrid))
        (version-control :variables version-control-diff-tool 'diff-hl))
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
The hybrid choice is also missing from `SPC t E`.

Adding `:demand t`, after `(use-package hybrid-mode` seems to fix it:
```
(defun spacemacs-base/init-hybrid-mode ()
  (use-package hybrid-mode
    :demand t
    :config
    (progn
```
in the file: `.emacs.d/layers/+distributions/spacemacs-base/packages.el`

**Comment by bmag** [comment]
Should be fixed by https://github.com/syl20bnr/spacemacs/commit/5c251f641549fd199af3383db72e7fa65278afd3, please report if there are still issues.
