### ISSUE TITLE
Possible Yasnippet issue

### ISSUE THREAD

**Issue by Balooga** [syl20bnr/spacemacs#10401]
(GitHub is returning a 500 error in response to [SPC h I], so report copied below.)

#### Description :octocat:
Possible yasnippet problem

'SPC i s' does not return any snippets.  The list is empty.

#### Reproduction guide :beetle:
- Start Emacs
- Create a new 'test.c' file
- Attempt to insert a snippet using 'SPC i s' 

*Observed behaviour:* :eyes: :broken_heart:
No snippets appear in the Helm window.

The following appears in *Messages*
````
[yas] Check your `yas-snippet-dirs': /home/vagrant/.emacs.d/elpa/yasnippet-20180218.459/snippets is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
[yas] Check your `yas-snippet-dirs': /home/vagrant/.emacs.d/elpa/yasnippet-20180218.459/snippets is not a directory
[yas] Prepared just-in-time loading of snippets with some errors.  Check *Messages*.
Auto-evilification could not remap these functions in map ‘edebug-mode-map’:
   - ‘edebug-Go-nonstop-mode’ originally mapped on ‘G’
GNU Emacs 25.3.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.10) of 2018-02-27
````

*Expected behaviour:* :heart: :smile:
Expected many snippets with the ability to filter using Helm.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.50.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(common-lisp pdf-tools cscope gtags semantic
             (c-c++ :variables c-c++-enable-clang-support t)
             php python html ruby helm auto-completion better-defaults emacs-lisp git
             (markdown :variables markdown-live-preview-engine 'vmd)
             (org :variables org-enable-github-support t org-enable-reveal-js-support t org-reveal-root
                  (cond
                   ((file-exists-p "~/.spacemacs.d/site/reveal.js")
                    "~/.spacemacs.d/site/reveal.js")
                   ((file-exists-p "~/.reveal.js")
                    "~/.reveal.js")))
             (shell :variables shell-default-height 30 shell-default-position 'bottom)
             spell-checking syntax-checking
             (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
             themes-megapack evil-commentary deft selectric speed-reading plantuml restclient
             (clojure :variables clojure-enable-fancify-symbols t)
             yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by CeleritasCelery** [comment]
> [yas] Check your `yas-snippet-dirs': /home/vagrant/.emacs.d/elpa/yasnippet-20180218.459/snippets is not a directory

is `/home/vagrant/.emacs.d/elpa/yasnippet-20180218.459/snippets` a directory?

**Comment by duianto** [comment]
Possible duplicate of:
yas-snippet-dirs does not exist after each upgrade, causing warning #10316

The `yasnippet` package used to include a snippets directory, but:
>Yasnippet no longer bundles snippets directly, but it's very easy to get some!

source: https://github.com/joaotavora/yasnippet#where-are-the-snippets

There is a `yasnippet-snippets` package, adding it to the `dotspacemacs-additional-packages` seems to fix it: https://github.com/syl20bnr/spacemacs/issues/10316#issuecomment-366981134

**Comment by Balooga** [comment]
I believe that might be it.

According to https://github.com/joaotavora/yasnippet/issues/885 , the actual snippets have been separated into their own package (https://github.com/AndreaCrotti/yasnippet-snippets) that must be installed separately.

**Comment by Balooga** [comment]
Closing.  Duplicate of #10316 .

**Comment by ashrasmun** [comment]
I have added the `yasnippet-snippets` package to `dotspacemacs-additional-packages` and it doesn't work :( 
I have the snippets directory in `yasnippets-snippets` directory, but not in `yasnippets`. 
Also, wherever I place ` (setq yas-snippet-dirs (append yas-snippet-dirs '("c:\\Program Files\\emacs\\.emacs.d\\elpa\\yasnippet-snippets-20190513.1049\\snippets\\")))` (or just setq) I cannot set the `yas-snippet-dirs` variable **before** `yasnippets `is initialized...

**Comment by duianto** [comment]
It has been fixed on the develop branch.

**Comment by ashrasmun** [comment]
> It has been fixed on the develop branch.

Sorry for hassle then, and thank you!

**Comment by ajohnston1219** [comment]
I am having the same issue. I notice that I have a "snippets" directory inside "path/to/.emacs.d/elpa/yasnippet-snippets-20200122.1140", but not inside "path/to/.emacs.d/elpa/yasnippet-20191222.2206/". Is it just looking in the wrong directory?

**Comment by duianto** [comment]
@ajohnston1219 The snippets used to be part of the yasnippet package:
https://github.com/joaotavora/yasnippet, but it has been separated into it's own package: https://github.com/AndreaCrotti/yasnippet-snippets

The issue reported by this issues author has been fixed on the Spacemacs `develop` branch.

It's the recommended branch until the next Spacemacs version is released (I don't have any insight into when that is).

#### To try the `develop` branch:
Backup your current setup, then make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal/command prompt and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Comment by ajohnston1219** [comment]
Thank you, I will try out the development branch. To be clear, I am currently including the `yasnippet-snippets` package in `dotspacemacs-additional-packages`. This package appears to install the snippets, just not in the same directory that spacemacs is looking for them.

**Comment by duianto** [comment]
You could try to specify the `yas-snippet-dirs` path manually as described here:
https://github.com/joaotavora/yasnippet#where-are-the-snippets
```elisp
(setq yas-snippet-dirs
      '("~/.emacs.d/snippets"                 ;; personal snippets
        "/path/to/some/collection/"           ;; foo-mode and bar-mode snippet collection
        "/path/to/yasnippet/yasmate/snippets" ;; the yasmate collection
        ))

(yas-global-mode 1) ;; or M-x yas-reload-all if you've started YASnippet already.
```
