### ISSUE TITLE
Rust layer doesn't configure Cargo's directory correctly

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10408]
#### Description :octocat:
Rust layer doesn't configure Cargo's directory correctly.

#### Reproduction guide :beetle:
- Start Emacs
- Have a Rust project named hello_rust. :D
- Open hello_rust/src/main.rs .
- Do ", c c" to cargo-compile.

*Observed behaviour:* :eyes: :broken_heart:
The following error gets printed because the directory is set to hello_rust/src/ not hello_rust/ :

```
-*- mode: cargo-process; default-directory: "/Base/- Code/Rust/hello_rust/src/" -*-
Cargo-Process started at Wed Feb 28 19:15:14

cargo build 
error: failed to parse manifest at `/Base/- Code/Rust/hello_rust/src/Cargo.toml`

Caused by:
  virtual manifests must be configured with [workspace]

Cargo-Process exited abnormally with code 101 at Wed Feb 28 19:15:15
```

*Expected behaviour:* :heart: :smile:
The directory should be the root not root/src.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 93ec4217)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((rust :variables rust-format-on-save t)
 crystal
 (haskell :variables haskell-enable-hindent t)
 html python
 (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
 autohotkey helm auto-completion emacs-lisp
 (ibuffer :variables ibuffer-group-buffers-by 'modes)
 coq emoji
 (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
 git
 (java :variables java-backend 'ensime)
 markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control osx racket clojure)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
Can't reproduce the bug. Are you sure the bug is in Spacemacs and not a bug in your project? Try running `cargo build` from the command line and tell us if that works.

**Comment by NightMachinary** [comment]
I'm sorry, the problem was with my side. Somehow there was an empty cargo.toml in my src folder (no idea how it was created). Removing that solved everything.

**Comment by realfabecker** [comment]
I had the same issue. In my case, it was related to the Cargo.toml file being created as root. I was running in a VSCode dev container and compiling the Rust project in another container, where the issue appeared. Resolving the permission problem fixed it for me.
