### ISSUE TITLE
lsp layer  File mode specification error: (void-function lsp-ui-mode) - use-package changes?

### ISSUE THREAD

**Issue by cormacc** [syl20bnr/spacemacs#10407]
This issue arises when opening any C file since a recent melpa package update.
Looks very similar to this https://github.com/syl20bnr/spacemacs/issues/10394, and can be resolved the same way (i.e. by adding :commands (lsp-ui-mode) to the use package macro invocation in lsp layer packages.el).

Haven't raised a PR yet, as this is starting to look like a systematic problem, either due to some upstream change in use-package, or something screwy with my system. At least one other individual @myrgy experienced the other issue though.

If someone can confirm it's not just me, I'll raise a PR.

System details below

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4fe1600f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 cquery my-code c-c++
 (cmake :variables)
 (colors :variables colors-enable-nyan-cat-progress-bar t nyan-bar-length 8)
 csv chrome dash deft emacs-lisp evil-snipe git
 (go :variables gofmt-command "goimports")
 haskell html
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (javascript :variables node-add-modules-path t)
 (markdown :variables markdown-live-preview-engine 'vmd)
 nlinum notmuch octave
 (org :variables org-enable-hugo-support t org-enable-github-support t org-enable-reveal-js-support t)
 pandoc plantuml python racket
 (ranger :variables ranger-show-preview t ranger-cleanup-on-disable t ranger-show-dotfiles t)
 (ruby :variables ruby-test-runner 'rspec)
 rust search-engine
 (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
 shell-scripts spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 systemd treemacs version-control windows-scripts yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by bmag** [comment]
We changed the default behavior of use-package in spacemacs, see https://github.com/syl20bnr/spacemacs/commit/e2b1cecb77be31f6551b8696f6c71d285886bd79 and https://github.com/syl20bnr/spacemacs/commit/29c78ce841ee5a99bb4077a2862afc96c8136107.

We tried to update everything accordingly, but probably missed some packages. Regressions are expected and will be fixed, issue reports and PRs are welcome.

**Comment by syl20bnr** [comment]
I reverted the use-package config changes, it was a bad idea.

**Comment by cormacc** [comment]
@syl20bnr I don't know. Lazy-loading by default sounds from the outside like a pretty good policy -- just one entailing a certain amount of pain upfront that could be mitigated by bit of end-user education. Easy to miss something like this in a busy project, even if one is in the habit of monitoring the commit logs, and I certainly hadn't bothered reading the use-package docs until I ran into an issue :) Could consider keeping it in, but placing a nice big announcement in the readme/release notes?

**Comment by erichlf** [comment]
I am having this issue on the latest develop (015303a).
