### ISSUE TITLE
Trailing Whitespace is not deleted when `dotspacemacs-whitespace-cleanup` is `'trailing`.

### ISSUE THREAD

**Issue by kkweon** [syl20bnr/spacemacs#10414]
#### Description :octocat:
A **trailing whitespace is not deleted** even though `dotspacemacs-whitespace-cleanup` is set to `'trailing`. It worked before, but today I updated to the latest branch, and then it doesn't work with any files.

<img src="https://user-images.githubusercontent.com/2981167/36823527-7108b1d0-1cb2-11e8-8006-ef15fad6a241.gif" alt="Trailing space" width="100%">

#### Reproduction guide :beetle:
- Start Emacs        
- Set `dotspacemacs-whitespace-cleanup` to `'trailing`
- Restart spacemacs to make sure
- Open any file and make trailing whitespaces
- Save

*Observed behaviour:* :eyes: :broken_heart:

- Nothing happens (trailing spaces remain)

*Expected behaviour:* :heart: :smile:

- all trailing spaces should be removed.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4fe1600f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(php ruby search-engine typescript nginx docker go colors django react elixir graphviz csv yaml
     (elm :variables elm-format-command "elm-format")
     (haskell :variables haskell-enable-hindent-style "johan-tibell" haskell-completion-backend 'intero)
     github doxyspace java javascript html helm
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence-delay 0 auto-completion-complete-with-key-sequence "jk")
     better-defaults emacs-lisp neotree ess
     (git :variables git-magit-status-fullscreen t)
     (markdown :variables markdown-live-preview-engine 'vmd)
     (org :variables org-enable-bootstrap-support t org-enable-reveal-js-support t org-enable-github-support t)
     (shell :variables shell-default-height 30 shell-default-shell 'multi-term shell-default-position 'bottom)
     shell-scripts spell-checking version-control
     (python :variables python-test-runner 'pytest)
     semantic
     (latex :variables latex-build-command "LatexMk")
     (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
     syntax-checking dash calendar gtags bibtex pdf-tools
     (plantuml :variables org-plantuml-jar-path "~/bin/plantuml.jar"))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by masolino** [comment]
I noticed this problem on develop, on master branch is working fine

**Comment by bmag** [comment]
Fixed by https://github.com/syl20bnr/spacemacs/commit/f84ab9af8fb9de33ef3a4e044ade07cd082cdfc9, please report if there are still issues.
