### ISSUE TITLE
[FEATURE REQUEST] Add a list of demanded additional packages to Spacemacs dotfile

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10413]
Add a list of demanded additional packages to Spacemacs dotfile, that are not deferred.

**Comment by aaronjensen** [comment]
@NightMachinary could you expand on why you would want this?

**Comment by NightMachinary** [comment]
@aaronjensen I am imagining that some packages might need it. It certainly doesn't hurt to give the user more control. :) I don't need it as of now.

**Comment by aaronjensen** [comment]
Gotcha, maybe we can wait until we have a use case and then reopen this?

**Comment by robbyoconnor** [comment]
Could you clarify this in your original comment and title?

**Comment by NightMachinary** [comment]
@aaronjensen Ok I will close it :)
But it seemed like an easy-to-add thing :D

**Comment by robbyoconnor** [comment]
I always go with make a PR -- worst case -- it's not accepted..
