### ISSUE TITLE
Local packages for private layers not loading

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#10417]
#### Description :octocat:

Local packages for private layers not loading

I have number of private layers in
`dotspacemacs-configuration-layer-path`
with local packages, e.g.:

    my-layer/local/my-package/my-package.el

`my-package` listed in layer's package.el with `:location local`,
everything seems to be correct in init function and in `use-package` body. Most importantly it used to work. But it somehow stopped. And I can't figure out what has changed.

**upd**: it appears to be broken only in `develop`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4fe1600f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm

**Comment by agzam** [comment]
I have found a workaround. If `use-package` is used with `:demand t` - it works. I'm not sure what has changed, probably this need to be documented.

**Comment by myrgy** [comment]
Now all packages loading is deferred. Seems like your doesnt expose autoloaded function. Could be used via :commands section of use-package

**Comment by myrgy** [comment]
Here is description: https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#use-package

**Comment by bmag** [comment]
Since https://github.com/syl20bnr/spacemacs/commit/29c78ce841ee5a99bb4077a2862afc96c8136107, Spacemacs sets `use-package-always-defer` to `t`. Meaning, `:defer t` is implied in all use-package declarations, unless overridden by `:demand t`. The change was documented in https://github.com/syl20bnr/spacemacs/commit/e2b1cecb77be31f6551b8696f6c71d285886bd79.

If previously you had a package configured like this:
```elisp
;; before `use-package-always-defer' change
(use-package foo
  :config (foo-mode))
```
You can restore the original correct behavior with this change:
```elisp
;; after `use-package-always-defer' change
(use-package foo
  :demand t
  :config (foo-mode))
```

As @myrgy wrote, if it makes sense to defer the package until it's really needed, you can adapt your configuration to lazy-loading (e.g. via `:commands`) instead of restoring the non-deferred behavior.

**Comment by duianto** [comment]
syl20bnr explained why the change was made, in this gitter message:
>@/all I pushed an important change in develop branch. use-package will now try to lazy load packages by default so :defer t is not necessary anymore as it is implied. To force a package to load right away you need to add :demand t. As 90% of the packages are lazy loaded it makes more sense to do it this way. This may triggers some regression in some package configured by spacemacs and in your private configuration as well.

source: https://gitter.im/syl20bnr/spacemacs?at=5a963234e4d1c63604a34fd2

**Comment by syl20bnr** [comment]
I think this was a mistake to use `use-package-always-defer` as `use-package` is more and more used in place of a simple `require`. Setting `use-package-always-defer` to `t` simply breaks this use case.

Going to revert, sorry for the bad good idea :-)

Great work @bmag by the way 👍

**Comment by syl20bnr** [comment]
Reverted in commit: https://github.com/syl20bnr/spacemacs/commit/ebe4c602647801d59013915c8c97d44570556f3e

**Comment by agzam** [comment]
BTW, does anyone know if it's possible to use `use-package :bind` with `spacemacs/set-leader-keys`, or `evil-define-key`?

**Comment by myrgy** [comment]
@agzam , I suspect that `use-package :bind` might not work as expected because it is not aware about spacemacs leader keys "magic"
@syl20bnr , is it possible to describe proper ways in https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org ?
