### ISSUE TITLE
[Scala] Multiple completion popups

### ISSUE THREAD

**Issue by bjarkevad** [syl20bnr/spacemacs#1041]
When using the `scala` layer with the `auto-completion` layer enabled, it looks like both `auto-complete` and `company` suggests completions.
See image:
![scala-completion](https://cloud.githubusercontent.com/assets/1748368/6980904/60b99dca-d9f9-11e4-9dfd-278d3c0114d1.png)

**Comment by syl20bnr** [comment]
That's very nice, twice as much choices !
It should be fixed in develop :-)
