### ISSUE TITLE
Wrong descriptions in menu

### ISSUE THREAD

**Issue by danmcatee** [syl20bnr/spacemacs#10412]
#### Description :octocat:

Spacemacs shows the wrong description for keys, f.e. when I press SPC the letters are followed by the word "prefix" instead of the correct category name.

#### Reproduction guide :beetle:
- Start Emacs
- Press Space

*Observed behaviour:* :eyes: :broken_heart:

Letters in menu followed by the word "prefix" and f.e. when i press SPC T instead of showing the description cycle through themes i get narrow/number.

*Expected behaviour:* :heart: :smile:

Correct descriptions of keys.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((html :variables web-mode-enable-current-element-highlight nil)
 ivy emacs-lisp
 (osx :variables osx-use-option-as-meta nil)
 git)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
So, this issue was fixed upstream?

Quote of duianto from gitter (https://gitter.im/syl20bnr/spacemacs?at=5a97ca1ae4ff28713ade7af9):
> @danmcatee The +prefix entries in the SPC popup was caused by a change in the which-key package. But it has now been fixed, just update your packages.

**Comment by duianto** [comment]
@bmag I suspect that it was caused by this commit:
Remove which-key--current-prefix https://github.com/justbur/emacs-which-key/commit/ded908ec0b95f8890e11a8ef3a700c583a0ca036

And fixed by this one:
Fixes related to removal of which-key--current-prefix https://github.com/justbur/emacs-which-key/commit/013681a1e3174071b26eedff57e2f09f6e6e7ad0
