### ISSUE TITLE
Cursor in Edebug mode is off by one character

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1042]
The cursor stops just right above the end of expression to be evaluated next while it's suppose to stop right after that expression.

**Comment by luxbock** [comment]
I've noticed that edebug is hardly usable from `normal-state`, but this is usually where I'm calling it from, so we should probably add key-bindings to it. I've only started getting familiar with edebug recently, so I think someone more familiar with it might be better suited to thinking a proper way to evilify the bindings.
