### ISSUE TITLE
treemacs-evil does not appear to be loading properly as of 29c78ce

### ISSUE THREAD

**Issue by kyren** [syl20bnr/spacemacs#10422]
#### Description :octocat:
treemacs-evil does not appear to be working as of 29c78ce841ee5a99bb4077a2862afc96c8136107

#### Reproduction guide :beetle:
- Start Emacs
- Use the latest develop spacemacs (5c251f641549fd199af3383db72e7fa65278afd3)
- Add `treemacs` to `dotspacemacs-configuration-layers`
- Open treemacs with `SPC f T`
- Press `q` to close the treemacs window

*Observed behaviour:* :eyes: :broken_heart:
Nothing happens (using vim editing style, it's now waiting on the macro register)

*Expected behaviour:* :heart: :smile:
Treemacs window is closed

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5c251f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html ruby sql windows-scripts javascript lua rust vimscript yaml haskell c-c++ helm auto-completion better-defaults emacs-lisp git markdown
      (treemacs :variables treemacs-use-follow-mode nil)
      org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (spell-checking :variables spell-checking-enable-by-default nil)
      syntax-checking version-control osx themes-megapack)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by bmag** [comment]
Thanks for the fix
