### ISSUE TITLE
Semantic tags does not support Python 3's function annotations

### ISSUE THREAD

**Issue by QiuMP** [syl20bnr/spacemacs#10437]
When I use python‘s function annotations like this:

```python
def create_sth(arg1: Iterable[str], arg2: int):
    pass
```

The semantic tags show the wrong function parameters. And when I add the type of return:

```python
def create_sth(arg1: str, arg2: int) -> bool:
    pass
```

The semantic tags does not recognize the code as function.
Does anyone know how to fix it?

**Comment by Alexander-Miller** [comment]
AFAIK semantic is not particularly well maintained. Your best best is probably to get your tags from something like gtags or a language server.
