### ISSUE TITLE
void function:org-projectile:per-repo

### ISSUE THREAD

**Issue by ListenLove** [syl20bnr/spacemacs#10434]
#### Description :octocat:
Error (use-package):org-projectile/:config:Symbols's function definition is void:org-projectile:prt-repo
#### Reproduction guide :beetle:
- Start Emacs
- Then gennrate a warnings buffer,which prints I have writed above.

*Observed behaviour:* :eyes: :broken_heart:
A package can not be loaded normaly.And generate the warings.

*Expected behaviour:* :heart: :smile:
I'm not clear.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp markdown org syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND GSETTINGS NOTIFY FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by tko** [comment]
Apparently fixed in develop with https://github.com/syl20bnr/spacemacs/commit/6063466231ce5e209aacd2de612e53390a25c442 (judging from the comment / line changed)

**Comment by smoh** [comment]
Given how many times this issue has been raised repeatedly (as @tko pointed out in #10483), is there a reason why the fix is not getting into master?

**Comment by livingcyborg** [comment]
I am the same as this guy... 
Error (use-package): org-projectile/:config: Symbol’s function definition is void: org-projectile:per-repo

**Comment by w20100w** [comment]
Bug not corrected yet.
@tko 's solution #10483  is working
I agree with smoh : why isn't it in Master ?

**Comment by burke** [comment]
Getting this too, more months later. Puzzled that it's not in master.

```
cd ~/.emacs.d
git checkout -b fix-org-projectile
git cherry-pick 6063466
rm CHANGELOG.develop
git add -A .
git cherry-pick --continue
```

**Comment by FlorianFranzen** [comment]
The last release of org-projectile was in August 2017...

@d12frosted what is the expected ETA for a fix in master?

**Comment by sdwolfz** [comment]
@FlorianFranzen end of this month.

**Comment by hyiltiz** [comment]
That was January. Now it is February. End of February too?

**Comment by FlorianFranzen** [comment]
@hyiltiz: It seems that spacemacs embraces the classic "real soon now" release management, e.g. see #11472.

**Comment by tko** [comment]
FWIW see also https://github.com/syl20bnr/spacemacs/milestones

**Comment by dotpyfe** [comment]
having the same issue

**Comment by imagirina** [comment]
Having the same issue "Error (use-package): org-projectile/:config: Symbol’s function definition is void: org-projectile:per-repo" after activating javascript, syntax-checking and auto-completion layers. Added  (auto-completion :variables
          auto-completion-return-key-behavior nil
          auto-completion-tab-key-behavior 'complete)

**Comment by MoHKale** [comment]
Same problem here surprised its been a year and the fix hasn't reached master yet.

**Comment by felix125** [comment]
I have the same issue too. The same error message.

**Comment by jleonard-r7** [comment]
I have this issue currently.

**Comment by nfedyashev** [comment]
After switching to the develop I no longer experience this issue.
Thank you

/cc @duianto

**Comment by sfines** [comment]
bump, same issue:
Error (use-package): org-projectile/:config: Symbol’s function definition is void: org-projectile:per-repo

**Comment by duianto** [comment]
@sfines Try the `develop` branch, it's the recommended branch until the next version is released.

Backup your current setup, then make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```

**Comment by s-surineni** [comment]
Still facing the same issue 
Error (use-package): org-projectile/:config: Symbol’s function definition is void: org-projectile:per-repo

**Comment by joshmedeski** [comment]
I'm also seeing this error on `master`. I'd prefer not to switch to the `develop` branch if possible.

**Comment by jleonard-r7** [comment]
Good luck with that. We've been on develop for years over here.

**Comment by hyiltiz** [comment]
`master` is dead. Even too late to mourn it. Just switch to `develop`; it is effectively an undisclosed rolling release at this point.

**Comment by nfedyashev** [comment]
![masters-dead-baby-masters-dead](https://user-images.githubusercontent.com/61983/93425375-83fd9780-f8c2-11ea-8e12-e9acc5cf905d.jpg)

**Comment by chuckberrypi** [comment]
Came here with the same issue, and it looks like the move is to switch over to the `develop` branch. My question: what's the best way to switch and easily migrate the customizations I've made in the dotspacemacs file (esp `dotspacemacs-configuration-layers` and `dotspacemacs/user-config`)? Do I just have to manually copy those over?

**Comment by duianto** [comment]
The `develop` branch is the recommended branch until the next version is released (I have no insight into when that is).

#### To switch to the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

Then copy over your customizations.

**Comment by hyiltiz** [comment]
@chuckberrypi Just copying those takes you 95% of the way there. There will be some configs broken, some layers that got renamed or removed, and some more rabbit holes to jump into. Good luck...
