### ISSUE TITLE
Spacelpa problem with Emacs 26

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10438]
#### Description :octocat:
Emacs 26 doesn't work with spacelpa.

#### Reproduction guide :beetle:
- Start Emacs
- The following error is shown:
```
Warning (tar): Extracted ‘ ’, a link, as a normal file
Warning (initialization): An error occurred while loading ‘/Users/evar/.emacs.d/init.el’:

Args out of range:  *tar-data spacelpa-0.300.tar.gz*, 513, 234451831318
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.9
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5c251f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript vimscript
            (rust :variables rust-format-on-save t)
            crystal
            (haskell :variables haskell-enable-hindent t)
            html python
            (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
            autohotkey kotlin helm
            (auto-completion :variables auto-completion-enable-help-tooltip t)
            emacs-lisp
            (ibuffer :variables ibuffer-group-buffers-by 'modes)
            coq emoji
            (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
            git
            (java :variables java-backend 'ensime)
            markdown org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking version-control osx racket clojure)
```

**Comment by dp12** [comment]
I'm seeing the same thing on Windows with Emacs 26.0.91

Warning (tar): Extracted ‘ ’, a link, as a normal file
Warning (initialization): An error occurred while loading ‘c:/home/.emacs.d/init.el’:

Args out of range:  *tar-data spacelpa-0.300.tar.gz*, 513, 234451831318

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

**Comment by NightMachinary** [comment]
The issue is present with Emacs 27.0.50 as well:

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript vimscript
            (rust :variables rust-format-on-save t)
            crystal
            (haskell :variables haskell-enable-hindent t)
            html python chrome
            (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
            autohotkey kotlin helm
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
            emacs-lisp
            (ibuffer :variables ibuffer-group-buffers-by 'modes)
            coq emoji
            (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
            git
            (java :variables java-backend 'ensime)
            markdown org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-tooltips t)
            (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
            version-control osx racket clojure)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by kyuwoo-choi** [comment]
here's the same issue with emacs 25.3.2, develop branch, dotspacemacs-use-spacelpa true

**Comment by kyuwoo-choi** [comment]
I fixed this by `chmod 777 ~/.emacs.d/.cache/stable-elpa/your.emacs.version/spacelpa-0.300.tar.gz`.

I found the file permission is "600"??? too restricted.
So I just gave it a try `dotspacemacs-use-spacelpa t` after I changed the permission.
And BOOM!!!

I got a luck today 🤣

**Comment by sutram** [comment]
Same here with 25.3.1 on OS X. In the file .emacs.d/init.el, I commented out line 32
    ;; (configuration-layer/stable-elpa-download-tarball)

which I suppose is the same as dotspacemacs-use-spacelpa nil ?

and it worked

**Comment by thanhvg** [comment]
I found a workaround
After spacemacs crashes go to ~/.emacs.d/.cache/stable-elpa/YOUR_EMACS_VERSION mine is
~/.emacs.d/.cache/stable-elpa/25.3.2 
you find a tarball spacelpa-0.300.tar.gz, extract it you will have the repo folder with the same name /spacelpa-0.300
Create a file name `version` in the same folder with the tarball, put a string 0.300 to it and save.
Restart spacemacs it should work. 
I think you can safely delete the tarball
I got it from here https://github.com/syl20bnr/spacemacs/issues/9958

**Comment by bhipple** [comment]
Thanks @thanhvg!  This worked for me:
```
$ cd ~/.emacs.d/.cache/stable-elpa/25.3.1
$ tar -xzvf spacelpa-0.300.tar.gz
$ echo -n "0.300" > version
```
Notably, the tarball is just extracted in the same dir, and if the version file has a newline, spacemacs won't recognize it!

**Comment by kyuwoo-choi** [comment]
HA! thanks @bhipple 
for me @thanhvg solution was not working because my `version` file doesn't have a newline!

👍 for you mentioned a newline.

**Comment by PierreR** [comment]
@syl20bnr Any hope for a proper fix anytime soon ?

**Comment by SavageMessiah** [comment]
Having a similar issue with emacs 26.1 and develop branch db0dd6d945

```
Warning (tar): Extracted '^_\213^H', a link, as a normal file
Warning (initialization): An error occurred while loading '/Users/<redacted>/.emacs.d/init.el':

File error: Opening output file, Illegal byte sequence, /Users/<redacted>/.emacs.d/.cache/stable-elpa/26.1/^_\213^H
```

I nuked my entire .emacs.d and recloned and the problem persists. The fix posted above doesn't help.

**Comment by ryanklee** [comment]
Same issue, emacs 26.1. Fix by @bhipple above worked for me.

**Comment by kylesnowschwartz** [comment]
@SavageMessiah I had the same issue. I caused it be clearing the .cache/ and elpa/ folders as other people suggested in order to fix problems with certain layers after pulling the latest version of develop. I was able to fix the problem by switching to the master branch and opening spacemacs, then my .spacemacs file with `spc f e d`. I changed `dotspacemacs-use-spacelpa` from t to nil. When I switched back to the develop branch I loaded spacemacs without an error. I think you could probably just edit your .spacemacs file directly with another editor without switching to the master branch but unsure.

**Comment by sdwolfz** [comment]
I've pushed a2bda16823ba27c8a1fd35d3f04a87a101443faa as a fix, please try it out and let me know if it worked as expected.

**Comment by bimmlerd** [comment]
Seems to have worked on OSX, emacs 26.1 and a clean checkout of `.emacs.d` on `develop`, at least I didn't get an error anymore. How can I tell that my packages were installed from spaceelpa instead of elpa/gnu whatever?

**Comment by sdwolfz** [comment]
You can look at the spacelpa repository to see the version of org mode and compare it to the one you have, for example.

**Comment by simonfxr** [comment]
Package installation over spacelpa worked afaik. However there was some interaction required:
- During installation of ess-R-data-view@ess I got asked wether to save abbrev_defs
- At the end I got asked if I wanted to rebuild the epdfinfo program, this is expected, but it might be a good idea to optionally pass 'no-prompt-p to pdf-tools-install.

Lsp-mode failed due to `(require 'lsp-clients)`, since the lsp-mode in spacelpa is outdated, maybe upgrade it?

**Comment by gcentauri** [comment]
I just had a success starting up with `spacelpa` as my primary repo.  Mac OSX Emacs 26.1

**Comment by ajholyoake** [comment]
Is this still an issue?

**Comment by turlando** [comment]
I would rather ask if Spacemacs is still being developed...

**Comment by syl20bnr** [comment]
It is :-)

**Comment by albertmichaelj** [comment]
It seems like this is fixed by the above referenced commit, and this is the last issue on the 0.300 release milestone. Is this still a problem for anyone, and if not, what is the path to a stable release from here? I'm happy to help contribute if there are open issues still.

**Comment by panchoh** [comment]
I can feel the 0.300 getting close, because...

This is SpaceMAAAAAAAACS!¹

¹: https://knowyourmeme.com/memes/this-is-sparta

(sorry, too good to pass up :-P)

Happy hacking, fellas!

**Comment by oliveratutexas** [comment]
THE HYPE, THE HYPE, THE ANTICIPATION

**Comment by Compro-Prasad** [comment]
This issue is fixed. Right?
I just checked it on my Emacs and it works fine. I am on Arch Linux though, if it makes any difference.

**Comment by sdwolfz** [comment]
Was waiting for @NightMachinary to confirm before I makerd it as fixed.

**Comment by oliveratutexas** [comment]
Like this if you've been watching this issue for the past 3 months but don't know enough lisp to help

**Comment by NightMachinary** [comment]
@sdwolfz Sorry, I opted out of Spacelpa, so I don’t know if it’s fixed or not. If other people aren’t having problems, then let’s just close it. One can always reopen an issue if it comes back. :D Thank you.

**Comment by revmischa** [comment]
![shipit](https://user-images.githubusercontent.com/245131/57198740-11b33e00-6f7f-11e9-9ba8-fbeeb46c8cfd.jpg)

**Comment by enmanuelr** [comment]
![image](https://user-images.githubusercontent.com/643014/57587203-571bc200-74cf-11e9-9619-44a4ac42c8d7.png)

**Comment by sdwolfz** [comment]
Closing this as the problem was solved. It's all up to @syl20bnr to decide when it's the best time to release.
