### ISSUE TITLE
nosetests doesn't work well with virtualenv

### ISSUE THREAD

**Issue by danielwuz** [syl20bnr/spacemacs#1044]
It seems that nosetests disregards path set by virtualenv. Open an issue to keep track of it.

**Comment by syl20bnr** [comment]
Indeed, we have to update it. Spacemacs uses my fork where the readme lists the differences [1].
We should check upstream what the new feature are.

[1] https://github.com/syl20bnr/nose.el

**Comment by danielwuz** [comment]
Should be fixed in this PR https://github.com/syl20bnr/nose.el/pull/2.

**Comment by danielwuz** [comment]
summon @syl20bnr

**Comment by syl20bnr** [comment]
Done :-)

**Comment by danielwuz** [comment]
Thanks! Now I can clean up my local repo =)
