### ISSUE TITLE
[Haskell] `show-smartparens-mode`

### ISSUE THREAD

**Issue by dschrempf** [syl20bnr/spacemacs#10441]
Spacemacs freezes when using `show-smartparens-mode` in Haskell and having variable names with primes, e.g.,

```haskell
myFunc :: Int -> Int
myFunc n' = n' + (1 - 3).
```

If the pointer is moved to the dot from the example above, Emacs freezes.

When I turn off `show-smartparens-mode` (NOT `smartparens-mode`), everything is fine.

**Comment by Alexander-Miller** [comment]
Does it freeze, or just get very slow? In the former case send a SIGUSR2 to emacs, in the latter case try the builtin profiler.

**Comment by dschrempf** [comment]
Thank you for explaining how to debug this problem. It freezes. I managed to get a debug log by sending SIGUSR2, I hope this helps:

```
Debugger entered--Lisp error: (quit)
  syntax-ppss(8344)
  sp--syntax-ppss(nil)
  sp-point-in-string()
  sp--get-context()
  sp--search-backward-in-context("\\(?:\\\\\"\\|[\"'`]\\)" nil t)
  sp--find-next-stringlike-delimiter("\\(?:\\\\\"\\|[\"'`]\\)" sp--search-backward-in-context)
  sp-get-expression(t)
  sp-get-sexp(t)
  sp-get-thing(:back)
  #[513 "\304!\211\203}\211\203$\305\306\"`U\204A\305\307\"\305\310\"G\\`U\204A?\205x\305\307\"`U\204A\305\306\"\305\311\"GZ`U\205x\312\305\307\"\305\306\"\305\310\"G\305\311\"G$\210\205x\313 \206`	?\205x\314\305\307\"\305\306\"\305\310\"G\305\311\"G$\262\202\230\203\215\315`GZG\"\210\202\223\315`G\"\210\316\211\211\207" [sp-echo-match-when-invisible cursor-in-echo-area sp-show-pair-previous-match-positions sp-show-pair-previous-point sp-get-thing plist-get :end :beg :op :cl sp-show--pair-create-overlays active-minibuffer-window sp-show--pair-echo-match sp-show--pair-create-mismatch-overlay nil] 12 "\n\n(fn MATCH &optional BACK)"](#(")" 0 1 (fontified t face (rainbow-delimiters-depth-1-face))) :back)
  sp-show--pair-function()
  apply(sp-show--pair-function nil)
  timer-event-handler([t 0 0 125000 t sp-show--pair-function nil idle 0])
```

**Comment by Alexander-Miller** [comment]
Looks like a bunch of smartparens code. I suggest you come up with a minimal reproducible case and then open an issue at smartparens.

**Comment by Fuco1** [comment]
This was reported upstream https://github.com/Fuco1/smartparens/issues/868 and we fixed it.  It was caused by a "fix" to a long-standing issue, however that caused more problems so it's now reverted on master.  Latest MELPA should have the working version.
