### ISSUE TITLE
Symbols's function definition is void: winum--window-list

### ISSUE THREAD

**Issue by vritxii** [syl20bnr/spacemacs#10446]
#### Description :octocat:
When I use Ctrl-x Ctrl-f to open a file, it wouldn't show the new buffer, only opened in the background, and shows "Symbols's function definition is void: winum--window-list" in the minibuffer, this bug also occurs when I use Ctrl-x b to switch buffer

#### Reproduction guide :beetle:
- Start Emacs
- At home page, Ctrl-x Ctrl-f to open a file / Ctrl-x b to switch buffer

*Observed behaviour:* :eyes: :broken_heart:
Showed "Symbols's function definition is void: winum--window-list" in the minibuffer

*Expected behaviour:* :heart: :smile:
Show me the new buffer

#### SYSTEM_INFO
- OS: GNU/Linux kernel 4.15
- Emacs Version: 27(Latest from Emacs master branch)
- Spacemacs: 0.300
- Spacemacs branch: develop(HEAD 2e8727ae)
- Graphic display: t

#### Backtrace
```
Symbols's function definition is void: winum--window-list
This function is called in `.emacs/layers/+completion/helm/funcs.el`
```

**Comment by changchunli** [comment]
I don't have this issue, @vritxii.

**Comment by duianto** [comment]
@vritxii If you've updated the packages, then it might be an Emacs 27 issue.

@changchunli which Emacs version are you using?

`C-x C-f` and `C-x b` works fine for me on the latest develop branch with updated packages.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm auto-completion emacs-lisp git org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by changchunli** [comment]
I use Emacs-27, Latest from Emacs master branch. @duianto

**Comment by changchunli** [comment]
When I use `SPC h d s` to get system informations, I get a error "Not enough arguments for format string"...

**Comment by changchunli** [comment]
#### System Info :computer:
- OS: gnu/linux （arch linux）
- Emacs: 27.0.50 (Latest from Emacs master branch)
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ac67a489)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD JSON LCMS2

**Comment by duianto** [comment]
Then my hypothesis failed.

**Comment by vritxii** [comment]
OK, I fixed the problem just now. In `~/.emacs.d/layers/+completion/helm/func.el` file, it calls a function---`winum--window-list` that not defined. I found it defined in `https://github.com/caisah/emacs.dz.git `, which also depends `https://github.com/magnars/dash.el.git`. So what I do is add 
```
(add-to-list 'load-path "/Path/To/emacs-winum/")
(require 'winum)
(winum-mode)
```
to the head of `~/.emacs.d/init.el`.
And add 
```
(add-to-list 'load-path "/Path/To/dash.el/")
```
to the head of `/Path/To/emacs-winum/winum.el`.
Now it works fine.

**Comment by dangirsh** [comment]
@vritxii Please re-open this. The bug is that the `helm` layer is silently depending on `winum` being available from a layer loaded before `helm`, which breaks if someone, for example, excludes `winum`.

**Comment by syl20bnr** [comment]
Should be fixed in develop branch. Please verify.

**Comment by dangirsh** [comment]
Works for me, thanks!

**Comment by dangirsh** [comment]
Works for me after adding change in #11068
