### ISSUE TITLE
Consistent bug from 'pers-mode'

### ISSUE THREAD

**Issue by duytrung** [syl20bnr/spacemacs#10440]
Hi,

i received this message whenever I open emacs some few months ago. How to fix it? Is it related to the plugin or something else?
It does not affect my work and I don't want to see that message.
![image](https://user-images.githubusercontent.com/2046672/37028746-0a969534-2185-11e8-919f-bc57065d1b1c.png)

Thanks

**Comment by Miciah** [comment]
This issue looks like a duplicate of #10081.
