### ISSUE TITLE
rust language server

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#10443]
Does anybody has been able to use lsp-mode, lsp-rust for Rust development?
Any pointers on what to do with the current master branch?

**Comment by non-Jedi** [comment]
In the develop branch there's an [lsp
layer](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/lsp)
already. See the [python
layer](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/python)
from develop for an example of adding lsp-mode as a backend for a language major
mode.

As far as what you can do on current master, I would recommend including the lsp
layer from develop as a local layer and hacking on the rust layer yourself.
Alternatively, a quick and dirty rust layer based solely on lsp without the
ability to specify backends might not be too hard to put together as a local
layer.

**Comment by shwsun** [comment]
Back to this topic, it looks like the best option with Rust is [lsp-rust](https://github.com/emacs-lsp/lsp-rust)

**Comment by shwsun** [comment]
Also see https://github.com/MaikKlein/rustrls/pull/1

**Comment by syl20bnr** [comment]
We can support multiple backend like in Javascript, Typescript, Python
and Java.

**Comment by shwsun** [comment]
@syl20bnr I think that would be the way to go.

**Comment by gnzlbg** [comment]
The 1.0 release candidate of the rust language server is available already. Has there been any progress on this? I think that by ~september it will be released, and that it would be good if the rust layer would set it up by default. In fact, it probably would make sense to get this set up before 1.0 gets released, so that we can forward any bugs reported here to the RLS team so that they can make sure that the 1.0 release works fine with spacemacs.

**Comment by gnzlbg** [comment]
This issue in rust-mode (https://github.com/rust-lang/rust-mode/issues/181) appears to recommend using eglot (https://github.com/joaotavora/eglot)

**Comment by Miciah** [comment]
> Yes, we should really have a look at (https://github.com/joaotavora/eglot), I almost get it to work with my config.

Did you run into any issues with Eglot? I have been using it with go-langserver, and Eglot itself seems to work well, and is exceptionally easy to use.  I use the following configuration:
```emacs-lisp
  (use-package eglot
    :defer t
    :init
    (spacemacs/declare-prefix "ae" "eglot")
    (spacemacs/set-leader-keys "aes" 'eglot
      "aeR" 'eglot-reconnect
      "aeq" 'eglot-shutdown
      "ae=" 'eglot-format
      "aeh" 'eglot-help-at-point
      "aeO" 'eglot-events-buffer
      "aeE" 'eglot-stderr-buffer
      "aer" 'eglot-rename
      "aee" 'eglot-code-actions))
```
Eglot is programmed with default language server binaries, including rls for rust-mode, so with the above configuration, <kbd>SPC a e s</kbd> should start the server right up.

**Comment by gnzlbg** [comment]
So I tried using it, but it made my spacemacs unusably slow when using it with Rust. Spacemacs would just freeze for 5 seconds every now and then. Maybe the Rust projects were just too big, but I ended up disabling it.

**Comment by Dummyc0m** [comment]
Auto-completion used to stall the ui for a few seconds every time it triggers. But I just tried eglot with Amethyst, and it works like a charm! Thanks @Miciah
