### ISSUE TITLE
Smartparens in react-mode

### ISSUE THREAD

**Issue by unalterable** [syl20bnr/spacemacs#10455]
Hi, i just want to remove a pair in react-mode. "<" ">". 
I need to be able to write () => {} arrow functions.

However i get 'We can not insert unbalanced closing delimiter in strict mode.'

I like strict-mode - i don't want to disable it.

I've tried everything i can think of. Mainly using the api described here: https://github.com/Fuco1/smartparens/wiki/Permissions

It would seem that this should work when placed in dotspacemacs/user-config:
```
(sp-local-pair 'react-mode "<" ">" :actions :rem)
and 
(sp-local-pair 'web-mode "<" ">" :actions :rem)
and 
(sp-pair "<" ">" :actions :rem)
```
but no

also i've tried in dotspacemacs/user-config:
```
(add-hook 'shell-mode-hook (lambda () (progn 
    (sp-local-pair 'react-mode "<" ">" :actions :rem)
))
```
also no luck.

Please help. Where are these pairs defined? And why i can i add pairs in dotspacemacs/user-config but not remove them?

**Comment by CeleritasCelery** [comment]
the `:rem` keyword will remove an action from the default action list. You are removing nothing because that property is blank. If you want to prevent it from auto inserting pairs use
```lisp
(sp-local-pair 'react-mode "<" nil :actions '(:rem insert))
```
if you want to prevent it from doing any actions use 
```lisp
(sp-local-pair 'react-mode "<" nil :actions nil)
```

**Comment by CeleritasCelery** [comment]
You might also want to open an issue with smartparens because it seems like there should be a way to keep the smartparens behavior (auto insert and wrapping) and also allow you to insert the ending delimiter in strict mode
