### ISSUE TITLE
Is there any tool in spacemacs to auto generate comment for a function?

### ISSUE THREAD

**Issue by tigerjack** [syl20bnr/spacemacs#10458]
The question is identical to the one [here](https://github.com/syl20bnr/spacemacs/issues/6794).
In particular, I'd like to achieve this for C/C++ projects. Is there any way?
One of the answer referred to a brief snippet which I have no idea on where it is or how to use it.

**Comment by fiveNinePlusR** [comment]
it uses https://github.com/joaotavora/yasnippet but you should ask this in the gitter chat as this is not a bug.

**Comment by robbyoconnor** [comment]
Use yasnippet.

**Comment by robbyoconnor** [comment]
Use yasnippet -- also why did you open this up when there was a previous one? It adds clutter.

**Comment by tigerjack** [comment]
Thanks guys for the responses, I'll try to get an answer on gitter.
