### ISSUE TITLE
Completion broken in many modes

### ISSUE THREAD

**Issue by trishume** [syl20bnr/spacemacs#1045]
769d54da026d60cb3d9d3c33e213604c2b6a46af broke completion in many modes where the package itself has special functionality to configure autocomplete.

This issue tracks which modes used to be working and now do not and which have been fixed using Github's fancy checkbox feature:
- Uses a built in function to manipulate `company-backends`
    - [x] Auctex
    - [x] Racket
- Were using default `company-backends` backends
    - [x] CSS
    - [x] Ctags/Gtags
- Benefited greatly from backend fallback
    - [x] Ledger: Fell back on `company-capf` backend
    - [x] Ruby: Without `robe` server (not possible for all projects) gets no auto-complete

Most of these should be pretty easy to fix. In fact I haven't actually tested that all these are broken but based on my knowledge of the current Spacemacs codebase they will be.

As these are fixed I will check them off on the list. Comment if I miss a fix and I'll add it.

**Comment by syl20bnr** [comment]
Excellent list :+1: 
I'm going to fix them.

**Comment by PierreR** [comment]
As mentioned in #1046, it probably does not work in Haskell mode either.

I do get the Ⓐ but completion never pops up anymore

**Comment by syl20bnr** [comment]
@PierreR you have to push in `company-backends-haskell-mode`. Spacemacs defines custom list of backends per mode.
I tested a bit and it seems that `:with company-yasnippet` prevent `ghc-company` from displaying candidates the first time. I removed it for now, can you try the last develop ?
Also note that the other backends you mentioned are now added by default so it should work. But if you have a better setup feel free to PR :-)

**Comment by PierreR** [comment]
I have just updated and it is actually worse ... The first opening file works ok, then it does not work for all others (same mode).

I will try to bisect to see when the problem occurs.

**Comment by PierreR** [comment]
So this is happening since 68ea3652e4 ... This is actually worse because there is no workaround anymore (the disable, enable dance make it work for all buffers ...)

**Comment by trishume** [comment]
Only Haskell left, almost there :D

**Comment by syl20bnr** [comment]
OMG............... How can I be so stupid on this. I reproduced the same flaw as actual company by enabling it globally........ crap.

There is no middle ground possible then, either going global company all the way down with global backend, either going the isolated company route.

For now I disable the global company but I have to give it some thought.

**Comment by syl20bnr** [comment]
@PierreR Get the last develop and it will be good. Sorry for the regressions.

**Comment by PierreR** [comment]
Euh no still no luck. Exactly the same symptom. I did restart emacs ...

**Comment by trishume** [comment]
@syl20bnr I don't get it, what about global company interferes? The new infrastructure will override global company with its own backends list so having global company shouldn't matter, right?

**Comment by syl20bnr** [comment]
@PierreR @trishume I found the issue, it was a hook order issue. It should be OK in Haskell and the other languages, I was also able to add back `company-yasnippet`.

@PierreR Can you test _again_ the last develop ? :-)

**Comment by syl20bnr** [comment]
I don't seem to be able to make `company-ghc` backend to work on my config :-(
Tried on several Haskell project, it seems that only the fallback backends are giving candidates.
I have also systematically `ghc-check` failure (display `failed` in the mode-line).

**Comment by PierreR** [comment]
At first sight, it seems OK on my side. I will keep you updated.

Cheers

**Comment by carlosgaldino** [comment]
`develop` should have the fixes for `ruby-mode`? Because I'm running in the `develop` branch with everything updated and still don't have auto complete in Ruby. OTOH things look good for Haskell.

**Comment by trishume** [comment]
@carlosgaldino what kind of auto-completion are you expecting? I get basic buffer completion in Ruby with `develop`.

Do you have the `auto-completion` layer installed?

**Comment by carlosgaldino** [comment]
@trishume I was expecting to have the same auto completion stuff I have when I'm writing other languages like existing variables/function names from the buffer I'm or any other buffer that I already opened. At least this is what I get when I'm in an `.hs` file.

**Comment by trishume** [comment]
@carlosgaldino you should get that, I certainly do. Do you have anything like an inf-ruby process running? Does it show the autocompletion 'a' in the modeline? Do you get any auto-completion popups ever? What do you get when you type `SPC : eval-expression RET company-backends`?

To help with a problem I can't reproduce I'm going to need a lot more info than just that it happens, sorry for all the questions.

**Comment by carlosgaldino** [comment]
@trishume Sure and is better that you ask the questions because I'm new to this and have no idea on what useful information I could give.

So, the output for `company-backends` is: `(company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf (company-dabbrev-code company-gtags company-etags company-keywords) company-oddmuse company-files company-dabbrev)`

Just an FYI, the output when I'm in a Haskell file is the following: `((company-ghc company-dabbrev-code company-yasnippet) (company-dabbrev-code company-gtags company-etags company-keywords) company-files company-dabbrev)`

The 'a' doesn't appear when I'm in a Ruby file but it does show when it's a Haskell file.

And I'm not sure about what you mean by "inf-ruby process running", could you explain?

Thank you.

**Comment by trishume** [comment]
@carlosgaldino got it, thanks for the help. I wasn't experiencing it because I enabled fallback global completion for modes without proper setup, and the ruby setup was missing something. Fixed with #1225.

**Comment by carlosgaldino** [comment]
Thanks @trishume. I commented on #1225 that your patch fixes the problem.

**Comment by trishume** [comment]
And with that this bug should be done.

**Comment by syl20bnr** [comment]
:+1:
