### ISSUE TITLE
Darktoooth theme doesn't load on start up

### ISSUE THREAD

**Issue by danielstaleiny** [syl20bnr/spacemacs#10459]
#### Description :octocat:
Darktooth theme bug when set up as default theme. 
#### Reproduction guide :beetle:
- Start Emacs
- add to dotspacemacs-configuration-layers `themes-megapack` layer
- set  ```dotspacemacs-themes '(
                         darktooth
                         minimal
                         oldlace)
        ```
 - save and restart
 - on start up darktooth bug happens

*Observed behaviour:* :eyes: :broken_heart:
On start up darktooth theme doesn't load.

 Warnings:
      - An error occurred while applying the theme "darktooth", fallback on theme
        "spacemacs-dark". Error was: (file-error Cannot open load file No such file or
        directory autothemer)      
      - Please check the value of "dotspacemacs-themes" in your dotfile or open an issue
        so we can add support for the theme "darktooth".  
        
        
There is no issue if darktooth theme is loaded as second or after start up. 
Bug seems to happen only when it is set up as default and on start-up.

*Expected behaviour:* :heart: :smile:
Load the theme without a problems ;)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(php rust markdown yaml csv html emacs-lisp git evil-cleverparens shell ranger restclient pdf-tools latex mu4e javascript themes-megapack ivy auto-completion emacs-lisp
     (shell :variables shell-default-height 30 shell-default-term-shell "/bin/zsh" shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
 Warnings:
      - An error occurred while applying the theme "darktooth", fallback on theme
        "spacemacs-dark". Error was: (file-error Cannot open load file No such file or
        directory autothemer)      
      - Please check the value of "dotspacemacs-themes" in your dotfile or open an issue
        so we can add support for the theme "darktooth".  
        
```

Love the work you are doing. Keep up the great work. :heart:

**Comment by danielstaleiny** [comment]
I just update my version of spacemacs to Spacemacs: 0.200.13 but the issue still exist and behaves the same way.

**Comment by tpearson1** [comment]
I'm experiencing the same issue.

**Comment by danielstaleiny** [comment]
workaround for now is to set default theme as spacemacs-dark(or any other default theme) and change it to darktooth once you load spacemacs.

**Comment by hersh-verthun** [comment]
I am facing the same issue. I tried setting the default theme to gruvbox. This happens with many themes of the **megathemes-pack**. I am running Solus OS (a linux distro).

**Comment by rouxbuciu** [comment]
Can confirm this is still happening as of 0.200.13@26.1. I've attempted to set the default theme many times (different ones) and I get the same error as @danielstaleiny. Work flawlessly when set manually after startup.

**Comment by duianto** [comment]
This issue seems to be marked as `fixed in develop`:
Themes not loading #8871

But this might be a workaround on the `develop` branch:
https://github.com/syl20bnr/spacemacs/issues/8871#issuecomment-308822752

**Comment by danielstaleiny** [comment]
I can confirm that it is fixed now, I am running darktooth as my default theme without the issue :)). Thanks upstream. 
```
   dotspacemacs-themes '(
                         darktooth
)
```

**Comment by duianto** [comment]
@danielstaleiny Did you switch to the `develop` branch? Or is it also working on the `master` branch?

**Comment by danielstaleiny** [comment]
@duianto  I am running Spacemacs version 0.300.0

**Comment by danielstaleiny** [comment]
I am no longer watching this, so I will close this issue, I don't know if it was fixed or not, so in future if anybody comes to this issue again, please create new issue.

Thank you Scpacemacs team.
