### ISSUE TITLE
Create dart lang layer

### ISSUE THREAD

**Issue by ar1a** [syl20bnr/spacemacs#10452]
Create a layer for https://www.dartlang.org/, the new app language thing.

**Comment by NightMachinary** [comment]
I think it'd have been more productive if you had pointed to a layer already on github and asked for it to be included.

**Comment by Miciah** [comment]
#8406 was made to add a layer for Dart, but it looks abandoned.

**Comment by duianto** [comment]
The PR:
Introduces Dart layer #11266
is now on the develop branch.
