### ISSUE TITLE
Remove  `(add-hook 'c-mode-common-hook 'spacemacs//c-toggle-auto-newline))` from +lang/c-c++/packages.el

### ISSUE THREAD

**Issue by MaskRay** [syl20bnr/spacemacs#10451]
This is an annoying option that is very hard to override on user's side.

auto-newline is annoying because people spend more time editing existing code than adding consecutive lines. The auto added new line is oftentimes undesired rather than useful.

**Comment by randomphrase** [comment]
+1

**Comment by AngelTerrones** [comment]
Does anyone know a workaround? :<

**Comment by umar456** [comment]
The `delq` command did not work for me on the latest devel branch. I used the following command to disable this functionallity.
```
(defun dotspacemacs/user-config ()
  ...
  (remove-hook 'c-mode-common-hook 'spacemacs//c-toggle-auto-newline )
  ...
)
```

**Comment by 0kaguya** [comment]
+1

**Comment by sdwolfz** [comment]
I created a varibale that controlls wether this feature is enabled or not, default disabled. You can set it in your `.spacemacs` as a layer variable.

```emacs-lisp
(c-c++ 
  :variables
  c-c++-enable-auto-newline t)
```
See 4219842f98d16f78e46408277fc458c20ae5dd76.
