### ISSUE TITLE
Shadowed keys with org layer

### ISSUE THREAD

**Issue by dzeruel** [syl20bnr/spacemacs#10462]
Hello!

Something is messed up in the latest org layer. With a fresh install of spacemacs and org layer on osx many of the funtions bindings are shadowed. I have no idea what causes this and how to fix it. (Even after hours of search.) Please help.

C-e             org-end-of-line
  (that binding is currently shadowed by another mode)

RET             org-return
  (that binding is currently shadowed by another mode)

<details>
  <summary>Other examples</summary>

C-y             org-yank
  (that binding is currently shadowed by another mode)

|               org-force-self-insert
  (that binding is currently shadowed by another mode)

M-RET           org-meta-return
  (that binding is currently shadowed by another mode)

M-h             org-mark-element
  (that binding is currently shadowed by another mode)

C-c C-w         org-refile
  (that binding is currently shadowed by another mode)

<remap> <self-insert-command>   org-self-insert-command
  (that binding is currently shadowed by another mode)

C-c C-a         outline-show-all
  (that binding is currently shadowed by another mode)
C-c C-b         outline-backward-same-level
  (that binding is currently shadowed by another mode)
C-c C-c         outline-hide-entry
  (that binding is currently shadowed by another mode)
C-c C-d         outline-hide-subtree
  (that binding is currently shadowed by another mode)
C-c C-e         outline-show-entry
  (that binding is currently shadowed by another mode)
C-c C-f         outline-forward-same-level
  (that binding is currently shadowed by another mode)
C-c TAB         outline-show-children
C-c C-k         outline-show-branches
  (that binding is currently shadowed by another mode)
C-c C-l         outline-hide-leaves
  (that binding is currently shadowed by another mode)
C-c RET         outline-insert-heading
  (that binding is currently shadowed by another mode)

C-c C-o         outline-hide-other
  (that binding is currently shadowed by another mode)

C-c C-q         outline-hide-sublevels
  (that binding is currently shadowed by another mode)
C-c C-s         outline-show-subtree
  (that binding is currently shadowed by another mode)
C-c C-t         outline-hide-body
  (that binding is currently shadowed by another mode)

C-c C-v         outline-move-subtree-down
  (that binding is currently shadowed by another mode)
C-c C-^         outline-move-subtree-up
  (that binding is currently shadowed by another mode)
C-c @           outline-mark-subtree
  (that binding is currently shadowed by another mode)

C-M-i           ispell-complete-word
  (that binding is currently shadowed by another mode)
</details>

Update:
Spacemacs/Emacs version: 
0.300.0@27.0.50 (spacemacs) (develope branch)
Installed the org layer only.
Fresh install => default settings.

**Comment by dzeruel** [comment]
It is fixed in the develop branch with the implementation of the M-RET prefix. Now it takes 2 M-RET to insert an org header.

**Comment by Somelauw** [comment]
For inserting a heading, you can use <C-return>, but it behaves a bit differently.

You can also put
```
dotspacemacs-emacs-leader-key "M-SPC"
```
in your init file to get "M-return" back in org-mode.

I don't know why the other keybindings are shadowed. Maybe check which other functions these keybindings ase bound to.

Can you also include some basic information? Which version of Spacemacs and Emacs are you using? Which layers and packages are you using?

**Comment by dzeruel** [comment]
Thank you! I'll check the solutions you provided. 
 Yep I forgot to include some basic info: 
Spacemacs/Emacs version: 
0.300.0@27.0.50 (spacemacs) (develope branch)
Installed the org layer only.
Fresh install => default settings.
