### ISSUE TITLE
No release in a long time

### ISSUE THREAD

**Issue by trishume** [syl20bnr/spacemacs#1046]
As you know, this is the longest time Spacemacs has ever gone between releases.
This wouldn't be a problem except there are lots of problems with `master` that have been fixed in `develop` which necessitates people switching who otherwise don't want bleading edge.

Recently 769d54da026d60cb3d9d3c33e213604c2b6a46af was committed to `develop` which is a big cool new feature but will require lots of work to get stable and working everywhere it should. So now we have a bunch of people forced to use a branch where lots of things aren't working that used to (e.g #1045).

Previous to that commit `develop` was actually quite stable so I recommend that 2905190dc869a1ce1b96bc873efb66d93c5d005f be merged as a new release, possibly using a git-flow release branch to fix up some things. That way we'll have a nice stable master and less time pressure to get the new auto-complete working smoothly.

**Comment by trishume** [comment]
This may also give us time to add a Changelog feature which will be useful since `auto-completion` layer not being default and the `company-mode` layer being gone will be a breaking change for almost every singe user of Spacemacs. Might reduce the inevitable hundreds of Gitter questions about auto-complete and company being "broken".

**Comment by syl20bnr** [comment]
I will release all at once with an explicit message on the startup screen. Like magit did for version 1.4.

**Comment by PierreR** [comment]
As a note, I have just switched to `develop` and the completion does not seem to work in haskell file. I do get the Ⓐ but it never pops up anymore (I did change `company-mode` for `auto-completion` in my .spacemacs)

**Comment by trishume** [comment]
@PierreR not surprising, I'm going to try and take a look at a lot of modes soon. Post it in #1045, this issue is on a different topic.

**Comment by syl20bnr** [comment]
jk ;-D

**Comment by trishume** [comment]
lol

**Comment by trishume** [comment]
woot! :confetti_ball: :fireworks: :sparkles: :sparkler:
