### ISSUE TITLE
Rogue crystal format function in after-save-hook

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10467]
#### Description :octocat:
Crystal layer adds a crytal format function to after-save-hook which is active for all files (at least it's active for .vimrc). It messes things up.
An easy fix would be to check the extension of the file before doing anything with it. It should also print a message that "Buffer auto-formatted by Crystal rules."

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: added-dvorak-right-handed-to-keyboard-layout-layer (rev. 11132295)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript vimscript
            (rust :variables rust-format-on-save t)
            crystal
            (haskell :variables haskell-enable-hindent t)
            html python chrome
            (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
            autohotkey kotlin helm
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
            emacs-lisp
            (ibuffer :variables ibuffer-group-buffers-by 'modes)
            coq emoji
            (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
            git
            (java :variables java-backend 'ensime)
            markdown org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-tooltips t)
            (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
            version-control osx racket clojure)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Miciah** [comment]
What is the name of the hook that is added when you edit a `.vimrc` file? When I enter `:e .vimrc<Enter>` and check the value of `after-save-hook`, it has the global value of `(rmail-after-save-hook)`.  When I enter `:e hello.cr<Enter>` and check the value of `after-save-hook`, it has the buffer-local value of `(crystal-mode-set-encoding t)`.
