### ISSUE TITLE
Default layers in .spacemacs template?

### ISSUE THREAD

**Issue by trishume** [syl20bnr/spacemacs#1047]
Over the last few months Spacemacs has become much more modularized into layers with a more lightweight core. I think this is great, however it doesn't give new users as good of an experience. 

There are certain layers like the new `auto-completion` that practically everyone will want to install.
I suggest `auto-completion`,`git` and `lang/markdown`.

I think the `.spacemacs` template should come with these layers in the list by default. Also important is when there is no `.spacemacs` file that these layers will be loaded so that even the *very first* experience with Spacemacs can show its true power.

**Comment by tuhdo** [comment]
I totally agree wih this.

**Comment by CestDiego** [comment]
So basically putting the layers into core?

**Comment by trishume** [comment]
@CestDiego the difference is that you can remove them from the default list if you want and you maintain the code organization.

**Comment by CestDiego** [comment]
:+1:  I like this. :D

**Comment by syl20bnr** [comment]
I agree with default layers, you are right  about `auto-completion`, it will also fix the blind spot of the documentation where elisp beginners don't know that the layer variable is a list.

**Comment by CarlQLange** [comment]
Put this in #1066. Don't you just love three-word change pull requests?

**Comment by CarlQLange** [comment]
I guess this can be closed? Pull was merged :)
