### ISSUE TITLE
Spacemacs: GTK-Theme Parsing Error

### ISSUE THREAD

**Issue by m0ne** [syl20bnr/spacemacs#10474]
#### Description :octocat:
- Fresh install of emacs25 (version 25.2 and after that 25.1), the addition of source_code_pro and cloning spacemacs.
- Starting emacs25 results in GTK-parsing error messages and spacemacs is unreadable

#### Reproduction guide :beetle:
- Purge emacs25
- Install emacs25 per apt-get (Debian GNU/Linux testing (buster))
- Make sure .emacs.d is non-existant
- Install Source_Code_Pro font
- Clone spacemacs
- start emacs25

*Observed behaviour:* :eyes: :broken_heart:
- Unreadable Output (white brackets and grey background) 

**State of Emacs, when started**

![emacs](https://user-images.githubusercontent.com/11767980/37351053-80013d42-26da-11e8-875f-ec19c12e21bd.png)

**Error messages, when invoked by the terminal**

![gtk-parsing](https://user-images.githubusercontent.com/11767980/37351456-6a9716c4-26db-11e8-89c8-dfd8d14c6345.png)

*Expected behaviour:* :heart: :smile:
- Have emacs25 running :)

**OS**:
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (buster)
Release:	testing
Codename:	buster

**Kernel**: 4.13.0-1-amd64

**GTK related packages:**
gtk-update-icon-cache/testing,now 3.22.28-1 amd64 [installed,automatic]
gtk2-engines-pixbuf/testing,now 2.24.32-1 amd64 [installed,automatic]
gtk2-engines-xfce/testing,now 3.2.0-3 amd64 [installed,automatic]
libcanberra-gtk3-0/testing,now 0.30-6 amd64 [installed,automatic]
libcanberra-gtk3-module/testing,now 0.30-6 amd64 [installed,automatic]
libdbusmenu-gtk4/testing,now 16.04.1+17.04.20170109.1-5 amd64 [installed,automatic]
libgirara-gtk3-2/now 0.2.7-1 amd64 [installed,local]
libgirara-gtk3-3/testing,now 0.2.8-2 amd64 [installed,automatic]
libgtk-3-0/testing,now 3.22.28-1 amd64 [installed,automatic]
libgtk-3-bin/testing,now 3.22.28-1 amd64 [installed,automatic]
libgtk-3-common/testing,testing,now 3.22.28-1 all [installed,automatic]
libgtk2-perl/testing,now 2:1.24992-1+b1 amd64 [installed,automatic]
libgtk2.0-0/testing,now 2.24.32-1 amd64 [installed,automatic]
libgtk2.0-bin/testing,now 2.24.32-1 amd64 [installed,automatic]
libgtk2.0-common/testing,testing,now 2.24.32-1 all [installed,automatic]
libgtkmm-2.4-1v5/testing,now 1:2.24.5-2 amd64 [installed,automatic]
libgtkmm-3.0-1v5/testing,now 3.22.2-2 amd64 [installed,automatic]
libgtksourceview-3.0-1/testing,now 3.24.6-1 amd64 [installed,automatic]
libgtksourceview-3.0-common/testing,testing,now 3.24.6-1 all [installed,automatic]
libgtksourceview2.0-0/testing,now 2.10.5-3 amd64 [installed,automatic]
libgtksourceview2.0-common/testing,testing,now 2.10.5-3 all [installed,automatic]
libjavascriptcoregtk-4.0-18/testing,now 2.18.6-1 amd64 [installed,automatic]
libreoffice-gtk2/testing,now 1:6.0.2-1+b1 amd64 [installed,automatic]
libwebkit2gtk-4.0-37/testing,now 2.18.6-1 amd64 [installed,automatic]
lightdm-gtk-greeter/testing,now 2.0.4-1 amd64 [installed,automatic]
python-gtk2/testing,now 2.24.0-5.1+b1 amd64 [installed,automatic]
qt5-gtk-platformtheme/testing,now 5.9.2+dfsg-12 amd64 [installed,automatic]

**Emacs related packages**
emacs25/now 25.1+1-4+deb9u1 amd64 [installed,upgradable to: 25.2+1-6+b1]
emacs25-bin-common/now 25.1+1-4+deb9u1 amd64 [installed,upgradable to: 25.2+1-6+b1]
emacs25-common/now 25.1+1-4+deb9u1 all [installed,upgradable to: 25.2+1-6]

#### Backtrace :paw_prints:
emacs25

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:542:18: negative values are not allowed.

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:543:19: negative values are not allowed.

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:770:13: negative values are not allowed.

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:3404:13: negative values are not allowed.

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:6278:13: negative values are not allowed.

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:6378:13: negative values are not allowed.

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:6782:13: negative values are not allowed.

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:6955:19: negative values are not allowed.

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:6956:22: negative values are not allowed.

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:7155:15: negative values are not allowed.

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:7188:21: negative values are not allowed.

(emacs25:7738): Gtk-WARNING **: Theme parsing error: gtk.css:7189:24: negative values are not allowed.

**Comment by jsoo1** [comment]
Is this issue still current? Can it be closed as upstream?

**Comment by m0ne** [comment]
sorry, was away on vacation. I will try @mroh69 suggestion, seems to be an external issue.
