### ISSUE TITLE
Possible autocompletion regression in (develop) python layer

### ISSUE THREAD

**Issue by thepreacher** [syl20bnr/spacemacs#10475]
So in the **master** branch of Spacemacs when I create a python module and in it I type
```
import time
time.

```
I get a list of all the possible completion candidates [clock, clock_gettime, clock_getres etc....]. However in the **develop** branch nothing happens. I don't get a completion list after the dot.

Pardon me if I'm missing the obvious here.

**Comment by changchunli** [comment]
Please see the issue #10366
