### ISSUE TITLE
Unable to install some packages with error "Package ... is unavailable. Is the package name misspelled?'

### ISSUE THREAD

**Issue by tddsg** [syl20bnr/spacemacs#10472]
Hi,

Recently, I update my Emacs setting and encounter the error that some packages cannot be installed.
I copy the error message as follow. (The error happens during the initialization of Emacs, hence I am unable to create a bug using `SPC h l`)

```
Found 5 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: column-marker@tddsg... [1/5]
Package column-marker is unavailable. Is the package name misspelled?
--> installing package: dired+@tddsg... [2/5]
Package dired+ is unavailable. Is the package name misspelled?
--> installing package: framemove@tddsg... [3/5]
Package framemove is unavailable. Is the package name misspelled?
--> installing package: llvm-mode@tddsg... [4/5]
Package llvm-mode is unavailable. Is the package name misspelled?
--> installing package: vline@tddsg... [5/5]
Package vline is unavailable. Is the package name misspelled?
```
The same bug happens to different versions of Emacs 25.3, 26.0.90, 27.0.50 and in both the two branches `master` and `develop` of Spacemacs.

Does anyone know how to fix this problem?

Thank you!

**Comment by smile13241324** [comment]
Hmmm judging from the error messages you have posted I see that the missing packages are all coming from the "tddsg" layer. 

Can you try to start without it and post the result? Also are you using develop or master?

**Comment by smile13241324** [comment]
@tddsg I did a quick package search for the failing packages and I am not able to find these on elpa or melpa please make sure that these packages are still available in the online package archives.

Spacemacs by default looks in [elpa](https://elpa.gnu.org/packages/) and [melpa](https://melpa.org/#/) as well as org.

**Comment by tddsg** [comment]
@smile13241324 Thank you for the response. I'm using the `master` branch now, but this issue also happens in the `develop` branch.

These 5 packages are configured by my personal layer `tddsg`, and I was able to download and use these 5 packages normally before. Only until the last month, the problem occurs.

By any changes that these 5 packages were removed from `elpa`, `melpa`?

**Comment by smile13241324** [comment]
@tddsg I assume that this is the case or they have been renamed. For llvm-mode I found proove [here](https://gitlab.com/theunixman/melpa/commit/aa2d7a88731ecd9410ab7dc887a7a5f837d8a93b). For dired+ and vline I had a look yesterday on elpa and melpa.

For rest please have a look yourself.

**Comment by tddsg** [comment]
@smile13241324 Thank you so much for the pointer. I also found that other packages, which are stored in the Emacswiki website, were removed by this commit: https://gitlab.com/theunixman/melpa/commit/a26379472690f2fdf7a0cd57aa8fbfc3b1dea0d3

**Comment by smile13241324** [comment]
@tddsg ahh thanks for the final post this will help others having the same issue in future.

**Comment by smile13241324** [comment]
@mrivas616 hmmm, strange I have just removed org-mime and it installed just normal. I am on develop. Using emacs 25.3.1. Could you please retry on an older emacs version preferably 25.3.1 I am not sure that 27.0.50 is already supported.

**Comment by mrivas616** [comment]
Thank you! @smile13241324 I downloaded emacs-25.3 from the GNU mirrors (turned out to be 25.3.2) and it seems to be working just fine now :smiley: . Now I'm getting another error `Error in dotspacemacs/user-config: Symbol’s value as variable is void: dotspacemacs-frame-title-format` but I guess that's from another issue.  Anyway, thank you again :+1:

**Comment by ihdavids** [comment]
I ran into the same issue on a custom build of Emacs 27.x for windows. It was working well a while back but after a refresh stopped working entirely.
I had to downgrade back to 26.x to get things to work.
