### ISSUE TITLE
Add an option to Semantic layer to disable function description in minibuffer?

### ISSUE THREAD

**Issue by qqldd** [syl20bnr/spacemacs#10477]
The semantic layer is good. But its function description in minibuffer sometime annoying. It hides messages from other functions. Can we add an option to disable this function? A previous example is: #878

**Comment by qqldd** [comment]
It seems disable the `global-semantic-idle-summary-mode` will disable the echo to the minibuffer. But since it is lazy loading. Not sure how to disable it correctly in user-config.

**Comment by smile13241324** [comment]
@qqldd your best bet would be to use an eval after load block in your user config. Like it is done for the org layer. Depending on whether you have an autoload object after leaving the layer load process "addhook" may be an alternative.

If you follow the eval after load approach don't forget to mention it in the semantic layer docu.

**Comment by JonathanKang** [comment]
I have lsp layer in my configuration, and it provides such a feature like `global-semantic-idle-summary-mode `, so you can see the definition of a variable/function in the mini buffer.
I also have semantic layer configured, which enables `global-semantic-idle-summary-mode ` by default. But it conflicts with the one provided by lsp layer(ccls) in c/c++ mode.

I just worked around it with the following config
````
(require 'semantic)
(setq semantic-default-submodes (remove 'global-semantic-idle-summary-mode semantic-default-submodes))
(semantic-mode 1)
````

But that's just my workaround. Hope there can be a official fix for this.

**Comment by bet4it** [comment]
I have disabled `semantic-idle-summary-mode` when `gtags` layer is used in #11511.
We can also check for `lsp-mode` with the similar way.

**Comment by JonathanKang** [comment]
> Is there anything semantic can do that lsp-mode can't?

semantic-stickyfunc-mode, which I found very useful.

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
Improve the use of semantic #11511
