### ISSUE TITLE
Ctrl-C menu option should be prominent (readable) from minibuffer

### ISSUE THREAD

**Issue by alexanderkjeldaas** [syl20bnr/spacemacs#10481]
When using the minibuffer, C-c will bring up a menu.  However, this is not advertised anywhere.  It should be possible to print this information somewhere in the minibuffer, say at the start of the prompt or somewhere.

**Comment by duianto** [comment]
One issue with listing all the bindings that open a menu from a minibuffer prompt, could be that it might not leave much room for writing the command/search term/etc.

For example: `C-h`, `C-x`, `M-g`, `M-m` and `M-o` (there might be more), also open a menu. And most of the commands in those menus, aren't minibuffer specific.

A quick check shows that, at the `M-:` `Eval:` prompt, the `C-c` menu, only lists one minibuffer specific binding: `C-l`, which calls `helm-minibuffer-history`.

But your right, it's not easy to discover, I might even have stumbled over `C-c C-l` by accident.
