### ISSUE TITLE
Rethink structured-haskell-mode keybindings

### ISSUE THREAD

**Issue by EDmitry** [syl20bnr/spacemacs#1048]
I have been trying to wrap my head around structured haskell mode.  By default `)` and `(` are mapped to movements. The problem is that `o` and `O` functionality is missing because you have to choose the right block before you can create a newline otherwise the indentation will be incorrect. I have found that binding ")" in normal mode to switch to insert mode and do `shm/close-paren` improved the workflow a bit. I have tried doing that without switching to insert mode but then the cursor is at the wrong position in the end of line (common evil-mode issue).

What's interesting though is that basically structured-haskell-mode is trying to emulate vim text objects in some way. It already has some sort of selection which is different from evil's selection. I wonder if there is a better way to integrate it with evil-mode.

**Comment by EDmitry** [comment]
Also, maybe we could use some ideas from evil-lisp-state. It seems like SHM is a similar concept but has less actions.

**Comment by gitfoxi** [comment]
I agree that SHM is not doing much in spacemacs. I wonder where would be a good place to work on it?

* Spacemacs
* evil-lisp-mode
* A new evil-haskell-mode

I'd love to know how SHM author @chrisdone thinks it should work.

**Comment by jb55** [comment]
A new `evil-haskell-mode` would be great :+1:

**Comment by d12frosted** [comment]
> I agree that SHM is not doing much in spacemacs.

I am using Spacemacs with emacs editing style and for me `shm` is priceless. But having `evil-haskell-mode` will not hurt me - I will still use `shm` :smile:

**Comment by syl20bnr** [comment]
We finally removed it from haskell layer in develop branch.
It may come back in a better shape at some point :-)
