### ISSUE TITLE
Centering cursor on screen when reopening file (save-place-mode)

### ISSUE THREAD

**Issue by hliebert** [syl20bnr/spacemacs#10484]
One thing that has been irritating me in Spacemacs is that while `save-place-mode` is enabled, the line on which the cursor is placed when re-entering a buffer is not centered on screen, requiring me to look for the cursor.

I have added the following to my `.spacemacs` to fix this, and it works sometimes, for example when opening files from the startup buffer, but not from helm. Opening a file via `SPC f r`, the cursor either doesn't center or I get  the message  `recentering a window that does not display current buffer`.

```
  (with-eval-after-load 'saveplace
    (defun adv/save-place-find-file-hook-recenter ()
      (recenter))
    (advice-add #'save-place-find-file-hook :after
                #'adv/save-place-find-file-hook-recenter))
```

Can anybody suggest a way to make this work? I am just starting with Emacs, so my understanding of Elisp is limited. Also (just a suggestion) isn't this behavior a good default?

**Comment by Somelauw** [comment]
If it opened the screen in exactly the state that you close it (recording position of pointer and window scroll), you can make it a habit to press M before saving and closing.

To me opening in exactly the same state as you closed it, seems the most logical default.

**Comment by hliebert** [comment]
thanks, `save-place-mode` works fine otherwise. do you have any idea how I could add this behavior? otherwise I'm going to close this issue.
