### ISSUE TITLE
How to activate the "themes-megapack" layer?

### ISSUE THREAD

**Issue by hersh-verthun** [syl20bnr/spacemacs#10488]
Hi

I activated the "themes-megapack" layer in the dotfile according to the documentation but pressing `SPC`-`T`-`S` does not bring up any new themes. Also I didn't notice Spacemacs installing the required packages when I restarted Spacemacs after activating this layer.

**Comment by CarlQLange** [comment]
Hey there, can you paste in your `dotspacemacs-configuration-layers` section?

**Comment by hersh-verthun** [comment]
Thanks for replying. I fixed it by reinstalling Spacemacs.
