### ISSUE TITLE
c/c++ #include <>  Cannot suggest header file

### ISSUE THREAD

**Issue by izhengzhixian** [syl20bnr/spacemacs#10487]
In the case where company-clang and company-c-headers are opened, #include <> cannot perform header completion and #include "" is OK.
The value of company-backends-c-mode-common is (company-clang company-c-headers
                   (company-dabbrev-code company-gtags company-etags company-keywords)
                   Company-files company-dabbrev)
Changed to (company-c-headers company-clang
                   (company-dabbrev-code company-gtags company-etags company-keywords)
                   In the case of company-files company-dabbrev, #include <> completions can be performed normally.

**Comment by Balooga** [comment]
I have never been able to get #include completions working in OSX, and yet in CentOS it just works.

What OS are you using?

**Comment by zzx666** [comment]
@Balooga                  deepin

**Comment by skeptomai** [comment]
I'm on OS X and have the same problem:
```
     (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
     ;; (c-c++ :variables c-c++-enable-clang-support t)
```
I toggle back and forth between these, and with the uncommented version, I get c++ header completion, but very little actual c++ completion.  If I comment it, and uncomment the second one, I get c++ completion, but '#include' no longer completes and the only header names that complete are in the project directory.

I know a number of variables like ```company-c-headers-path-system``` come into play, but I don't know how the options to the c-c++ layer mess with them.

**Comment by quicknir** [comment]
IMHO, the issue should be closed on the grounds that spacemacs should not support either company-clang, nor company-c-headers. They're both very sub-par packages, and spacemacs shouldn't endeavor to support many packages that do the same thing. There are multiple packages much closer to the state of the art. In particular, ycmd is already supported by spacemacs and provides both kinds of completion from a single package.

I have a fully working C++ setup on a large project based on ycmd + rtags; if you catch me in the gitter sometime I'm happy to answer questions. I also have my c++ setup as a standalone layer; I've been hoping to merge my setup into c-c++ but it's been a slow process: https://github.com/quicknir/config/tree/master/spacemacs.d/layers/cpp2.

**Comment by Mahua233** [comment]
I'm on OS X and have the same problem, and I used spacemacs develop branch :
>ELISP> (spacemacs//c-c++-get-standard-include-paths "c")

>("/usr/include" "/usr/local/include")

And I check on the terminal, Result look like this:
>echo | clang -xc -v -E -v - 2>&1 | sed -n '/#include <...> search starts here:/,/End of search list./{/#include <...> search starts here:/b;/End of search list./b;p}s' | sed -e 's/^ *//g'

>sed: 1: "/#include <...> search  ...": unexpected EOF (pending }'s)


When I delete all thing at `{}`:
> ~> echo | clang -xc -v -E -v - 2>&1 | sed -n '/#include <...> search starts here:/,/End of search list./p' | sed -e 's/^ *//g'

>#include <...> search starts here:
/usr/local/include
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks (framework directory)
End of search list.


Maybe sed command have some problem? [spacemacs//c-c++-get-standard-include-paths](https://github.com/syl20bnr/spacemacs/blob/d81e75584ecbefd8ac301d7165d384d6dbb409b1/layers/%2Blang/c-c%2B%2B/funcs.el#L86)

And 
>/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks **(framework directory)**

I think `(framework directory)` should deleted when them all push to [company-c-headers-path-system](https://github.com/syl20bnr/spacemacs/blob/d81e75584ecbefd8ac301d7165d384d6dbb409b1/layers/%2Blang/c-c%2B%2B/funcs.el#L129)

**Comment by izhengzhixian** [comment]
> I'm on OS X and have the same problem, and I used spacemacs develop branch :
> 
> > ELISP> (spacemacs//c-c++-get-standard-include-paths "c")
> 
> > ("/usr/include" "/usr/local/include")
> 
> And I check on the terminal, Result look like this:
> 
> > echo | clang -xc -v -E -v - 2>&1 | sed -n '/#include <...> search starts here:/,/End of search list./{/#include <...> search starts here:/b;/End of search list./b;p}s' | sed -e 's/^ *//g'
> 
> > sed: 1: "/#include <...> search  ...": unexpected EOF (pending }'s)
> 
> When I delete all thing at `{}`:
> 
> > ~> echo | clang -xc -v -E -v - 2>&1 | sed -n '/#include <...> search starts here:/,/End of search list./p' | sed -e 's/^ *//g'
> 
> > #include <...> search starts here:
> > /usr/local/include
> > /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.0/include
> > /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
> > /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include
> > /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks (framework directory)
> > End of search list.
> 
> Maybe sed command have some problem? [spacemacs//c-c++-get-standard-include-paths](https://github.com/syl20bnr/spacemacs/blob/d81e75584ecbefd8ac301d7165d384d6dbb409b1/layers/%2Blang/c-c%2B%2B/funcs.el#L86)
> 
> And
> 
> > /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks **(framework directory)**
> 
> I think `(framework directory)` should deleted when them all push to [company-c-headers-path-system](https://github.com/syl20bnr/spacemacs/blob/d81e75584ecbefd8ac301d7165d384d6dbb409b1/layers/%2Blang/c-c%2B%2B/funcs.el#L129)

Mac's own sed and linux are inconsistent, need to install gnu-sed。
`brew install gnu-sed
link -s /usr/local/bin/gnu-sed /usr/loca/bin/sed`
