### ISSUE TITLE
Tmux navigation keys broken when NERDTree open

### ISSUE THREAD

**Issue by ajholyoake** [syl20bnr/spacemacs#10496]
#### Description :octocat:
Tmux layer keybindings do not work in a NERDTree Buffer

#### Reproduction guide :beetle:
- Start Emacs
- Open nerdtree buffer (SPC f t) and press (C-h) (C-l)

*Observed behaviour:* :eyes: :broken_heart:
Cursor gets trapped in nerdtree (and shows / hides hidden files)

*Expected behaviour:* :heart: :smile:
Cursor should return to the original window

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp helm auto-completion better-defaults emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control ess python tmux javascript)
```

**Comment by changchunli** [comment]
Emacs 25.3 doesn't have this problem.
