### ISSUE TITLE
auto-complete "C-/" mapped to "undo-tree-undo" ?

### ISSUE THREAD

**Issue by Balooga** [syl20bnr/spacemacs#10490]
In the auto-complete documentation (http://spacemacs.org/layers/+completion/auto-completion/README.html#company) the key bindings for 'C-/' and 'C-d' are "_show candidates in Helm_", and "_open minibuffer with documentation of thing at point_" respectively.

However for me, 'C-/' and 'C-d' are "_undo-tree-undo_", and "_evil-scroll-down_" respectively.

Is the documentation correct on this?

**Comment by Miciah** [comment]
It sounds like you are using <kbd>C-/</kbd> and <kbd>C-d</kbd> in normal mode.  Is that the case? The <kbd>C-/</kbd>, <kbd>C-d</kbd>, <kbd>C-M-/</kbd>, and <kbd>M-h</kbd> key bindings in the table to which you linked are for the auto-complete menu that pops up after a delay while you are typing in insert mode.  Perhaps the documentation needs to be clearer.
