### ISSUE TITLE
t key binding for changing the to-do state no longer working in develop

### ISSUE THREAD

**Issue by manfredlotz** [syl20bnr/spacemacs#10495]
#### Description :octocat:

I changed to develop and now

   t change the to-do state

doesn't work any longer.

I tried to set org-want-todo-bindings to true but it didn't help.

#### Reproduction guide :beetle:
- Start Emacs
- go to an TODO item in an org file and type 'td'.

*Observed behaviour:* :eyes: :broken_heart:
Nothing happens.

*Expected behaviour:* :heart: :smile:
TODO changes its state to DONE

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby csv yaml python javascript html helm asciidoc auto-completion better-defaults clojure emacs-lisp erlang elixir git go haskell latex lua markdown nim ocaml org racket rust spell-checking syntax-checking neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      theming typography version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by tko** [comment]
When I type <kbd>SPC h d k</kbd> <kbd>t</kbd> to describe what the key is bound to I get
```
(evil-find-char-to &optional COUNT CHAR)

Move before the next COUNT’th occurrence of CHAR.
```
which seems like the correct behavior for vim mode. Can't comment on `org-want-todo-bindings` though.

The `org-todo` command I think you're expecting is bound to <kbd>SPC m T T</kbd> and there's also <kbd>Shift-Left/Right</kbd> key bindings to cycle through the todo-states.

**Comment by manfredlotz** [comment]
In stable I can type **td** to change a state to DONE. The alternative **SPC m T T d i**sn't a really good alternative.

**Comment by liujoey** [comment]
You are welcome!

```lisp
dotspacemacs-configuration-layers
   '(
     (org :variables org-want-todo-bindings t)
)
```

**Comment by manfredlotz** [comment]
@liujoey: Thanks a lot. That does it nicely. Very good.

When I had read  the _org_ documentation which says: _If the layer variable =org-want-todo-bindings= is true, the following bindings are also available._ I didn't realize that I have to set it in _dotspacemacs-configuration-layers_.

**Comment by tko** [comment]
Similar discussion in #8640
