### ISSUE TITLE
Company-mode for clojure.

### ISSUE THREAD

**Issue by person808** [syl20bnr/spacemacs#1049]
I think `company` is the better choice to use for clojure. The `cider` README recommends `company` and `auto-complete` throws up errors when a repl is not running. It's a small annoyance, but `company` can work without the repl. Is there something I'm missing that `auto-complete` provides for clojure the company doesn't?

**Comment by syl20bnr** [comment]
With the new architecture it is easy to switch auto-complete for company.
Simply add `company` and the other relevant packages to the `clojure-packages` list and remove `ac-cider` then you can follow the example of the haskell or python layers to see how the company bakcend is configured.

**Comment by person808** [comment]
@syl20bnr Its good to know I can do that :). But I still would like to know why `ac-cider` instead of `company`. What are the pros/cons of each choich?

**Comment by syl20bnr** [comment]
Good question, I don't know, I never really checked the differences, company is known to have a cleaner code base but it could be cargo cult, I did not dig it yet.
But I know for sure that Bozhidar prefers company _a lot_. So just for this I would move to company.

**Comment by luxbock** [comment]
Cider's README recommends company over auto-complete:
> CIDER users are advised to use company-mode to enable auto-completion inside of source code and REPL buffers.
