### ISSUE TITLE
Auto-complete and company-mode can run at the same time.

### ISSUE THREAD

**Issue by person808** [syl20bnr/spacemacs#1050]
If you go to a mode that uses company for autocomplete(like elisp), then to a mode that uses auto-complete(clojure), then back to elisp, both auto-complete and company are active
 
[Screenshot](https://files.gitter.im/syl20bnr/spacemacs/82pN/blob)

**Comment by syl20bnr** [comment]
Thank you for the report, it is fixed in `develop` :-)
