### ISSUE TITLE
Invoking projectile returns an error (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by OkanEsen** [syl20bnr/spacemacs#10506]
#### Description :octocat:
Invoking `SPC p p` and selecting a project or being inside of a project and invoking `SPC p f` does print the following error: `Debugger entered---Lisp error: (wrong-type-argument stringp nil)` inside the status line/minibuffer.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC p p` 
- Select a project

or

- Start Emacs
- Change directory to any known projectile directory
- `SPC p f` 

*Observed behaviour:* :eyes: :broken_heart:
Without the debug mode `SPC t D` Emacs reports the following error: `Debugger entered---Lisp error: (wrong-type-argument stringp nil)` inside the status line/minibuffer. Enabling the debug mode does open the backtrace and typing any letter activates the file search (projectile) for the current selected project.

*Expected behaviour:* :heart: :smile:
Open the file search for selected project.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5c0af4e56)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion dash docker emacs-lisp fasd git gtags helm
                 (osx :variables osx-command-as 'hyper osx-option-as 'meta osx-control-as 'control osx-function-as 'none osx-right-command-as 'left osx-right-option-as 'none osx-right-control-as 'left)
                 colors
                 (org :variables org-want-todo-bindings t org-enable-org-journal-support t)
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 parinfer restclient
                 (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left)
                 c-c++ clojure csharp emoji
                 (go :variables go-use-gometalinter t)
                 (haskell :variables haskell-enable-hindent-style "johan-tibell" haskell-completion-backend 'ghc-mod)
                 html
                 (java :variables java-backend 'meghanada)
                 javascript
                 (typescript :variables tide-tsserver-executable "~/.config/yarn/global/node_modules/.bin/tsserver")
                 latex markdown php python react rust shell-scripts sql yaml pdf-tools)
```
- System configuration features: DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES LCMS2

#### Backtrace :paw_prints:
Unfortunately enabling the debug mode does indeed show the full backtrace but typing anything with the keyboard or selecting any text inside of Emacs closes the backtrace and opens up the helm-buffer (I'm not entirely sure, what it's called) and lets me search the file inside the project via projectile and clears the backtrace buffer. That's why I had to make a screenshot of the backtrace, which I've attached below.
![bildschirmfoto 2018-03-21 um 17 50 24](https://user-images.githubusercontent.com/552226/37724983-394fc14e-2d32-11e8-94ea-99d1ca2cf292.png)

**Comment by maxigit** [comment]
Same problem. (It's an ongoing problem I have everytime I try to upgrade some package)

**Comment by ivar** [comment]
I'm still relatively new to emacs / spacemacs, and I've been experiencing this behaviour on the `master` branch (release 0.200.13.@25.3.1 ). Trying to search the project for a file (`SPC p f`) results in `Wrong type argument: stringp, nil`

**Comment by jonasws** [comment]
It looks to be a problem with a dependency: `helm-projectile`, or possibly even `helm` seems to be using the wrong call signature for the `helm-flx-fuzzy-highligher` function. Hopefully they will sort it out.

**Comment by duianto** [comment]
simendsjo has opened an issue on the `helm-projectile` repository:
helm-flx-fuzzy-highlighter wrong-type-argument stringp nil https://github.com/bbatsov/helm-projectile/issues/94

**Comment by Olical** [comment]
Weirdly I've found performing `rm -rf ~/.emacs.d/elpa` and re-opening Emacs solves my issue. But it comes back next time I update my packages.

**Comment by maxigit** [comment]
I have a similiar behavior (not sure what I did). I might be due to package not being recompiled when a dependencie has changed ..

**Comment by trcoffman** [comment]
duianto's fix appears to have worked for me.

**Comment by duianto** [comment]
This upstream issue seems to have been fixed.

I just updated the packages and pressing `SPC p f` in a dired buffer that's visiting the Spacemacs `.emacs.d` directory, works as expected without the stringp nil message.

**Comment by OkanEsen** [comment]
I'm going to close the issue, since the latest update has also fixed this issue for me.

**Comment by lane-s** [comment]
Unfortunately I'm getting this issue. I have basically an identical system to OkanEsen (up to date with develop), although I was originally using ivy rather than helm. I'm an emacs/spacemacs/oss noob, so let me know if I'm doing something dumb. I tried the following:
* Delete elpa and reinstall packages
* Delete .emacs.d and try a fresh clone of spacemacs
* Switch from ivy to helm
None of that worked, but using the template configuration works ok. It's worth noting that I get the same error with `SPC q R` and `SPC q r`.

Here's the bt from `SPC p p`:
[SPC-p-p.txt](https://github.com/syl20bnr/spacemacs/files/2237644/SPC-p-p.txt)
And from `SPC q r`:
[SPC-q-r.txt](https://github.com/syl20bnr/spacemacs/files/2237645/SPC-q-r.txt)

I'll see if I can narrow it down to any particular configuration layer that's causing it.
