### ISSUE TITLE
evil-search freeze Emacs in vertical window splits when editing html

### ISSUE THREAD

**Issue by liujoey** [syl20bnr/spacemacs#10505]
#### Description :octocat:
evil-search freeze Emacs in vertical window splits when editing html, tested on both Emacs-plus and Emacs-mac on Mac. It only freeze when I have vertical splits, it only freeze when using the GUI. It freeze on both vim style and hybrid style with evil-search-module enabled. It only freeze when I search "form". Tried to disable unicode symbols in power line, but still got freeze. Tried to disable anzu-mode but still freeze.

It does NOT freeze when in terminal, NOT when have horizontal splits or in single window, NOT when using hybrid mode with ISearch, NOT when search things other than "form", it just this word. Maybe I type "form" too fast?

It feels like the search is too fast as I typing such that updating of the power line can't catch up, but since I've disabled anzu-mode, I don't know anything else is updating the power line during search.

#### Reproduction guide :beetle:
- Save this html [gist](https://gist.github.com/liujoey/6c523504cb08c00fbc663b697741f9eb) somewhere
- Start Emacs
- `SPC w v` to open a vertical split
- Open any file in one split, then open the gist file in other window.
- in the html file buffer, use / to search word 'form', type it as fast as you can, I type '/form' in half second.
- if it doesn't freeze, then gg to the top and search the same thing again.
- if search 'form' in the example file, 8 out of 10 times the Emacs will freeze.

*Observed behaviour:* :eyes: :broken_heart:
Emacs freeze, doesn't respond to C-g, C-c, nor C-x C-c, can only be killed by "Force Quit Applications"

*Expected behaviour:* :heart: :smile:
jump to the search term and highlights.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm better-defaults osx
      (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual)
      emacs-lisp imenu-list colors
      (mu4e :variables mu4e-enable-mode-line t mu4e-enable-notifications t)
      (version-control :variables version-control-diff-tool 'diff-hl)
      (shell :variables shell-default-shell 'multi-term)
      markdown csv gtags yaml git html
      (go :variables go-use-gometalinter t)
      (java :variables java-backend 'ensime)
      (scala :variables scala-use-unicode-arrows t)
      javascript typescript python django evil-commentary
      (org :variables org-want-todo-bindings t)
      syntax-checking restclient docker vinegar evil-snipe treemacs)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
I'm unable to reproduce the freeze.

I `/` searched for `form` quickly, several times, both with and without first jumping to the top `gg`.

I opened `.spacemacs` (`SPC f e d`) in the first window.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(autohotkey helm auto-completion emacs-lisp git html org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by duianto** [comment]
I'm using the `Fira Code` font: https://github.com/tonsky/FiraCode/releases/tag/1.204

**Comment by liujoey** [comment]
Yes, I can confirm that once the font been upgraded, the freeze is gone.
My Source Code Pro was installed few years ago, not sure if that is the issue though. Closing this issue.
