### ISSUE TITLE
Change line spacing but vertically centered?

### ISSUE THREAD

**Issue by nocksock** [syl20bnr/spacemacs#10502]
I don't like having the lines that close to each other, so I found `(setq line-spacing 0.25)` which has the desired effect, with one little detail missing: the text is aligned to the top: 

![screen shot 2018-03-20 at 16 01 42](https://user-images.githubusercontent.com/22164/37662745-057596a8-2c58-11e8-9237-166660ded6ec.png)

Is there a way to get that line vertically centered too?

**Comment by duianto** [comment]
This SO question discusses this issue:
https://stackoverflow.com/questions/26437034/emacs-line-height

Adding text properties seems to be the closest solution:
```
(add-text-properties (point-min) (point-max)
                     '(line-spacing 0.25 line-height 1.25))
```

When I just tested it, then the line spacing/height doesn't change on the last line. Maybe it only works if there's a line below.

The answer here:
https://emacs.stackexchange.com/questions/30711/robust-way-of-applying-line-height-everywhere

states that:
>Emacs doesn't have a very sophisticated or complete rendering model.

And suggests:
>If you want something that's even nicer, I recommend diving into the rendering code and changing it so that line-spacing can be a list of two numbers, one for space below and one for space above the line. Then push that change out to the mailing list and see what they think of it.

So if your up for the challenge 😄

**Comment by nocksock** [comment]
> This SO question discusses this issue:
> stackoverflow.com/questions/26437034/emacs-line-height

I've found that one too, and as you noticed yourself, it works - but basically just once. :D 

> > If you want something that's even nicer, I recommend diving into the rendering code and changing it so that line-spacing can be a list of two numbers, one for space below and one for space above the line. Then push that change out to the mailing list and see what they think of it.

> So if your up for the challenge

I wouldn't even know where to start - especially being (as of now) completely unfamiliar with lisp that's beyond configuring spacemacs. 😅

**Comment by bmag** [comment]
This issue popped up in the gitter chat, so I'm just letting you know about the `default-text-properties` variable I found. Setting it like so should produce the desired spacing, except for the last line of the file:
```elisp
(setq default-text-properties '(line-spacing 0.25 line-height 1.25))
```

But that also affects the minibuffer, so maybe a better solution is:
```elisp
(defun set-bigger-spacing ()
  (setq-local default-text-properties '(line-spacing 0.25 line-height 1.25)))
(add-hook 'text-mode-hook 'set-bigger-spacing)
(add-hook 'prog-mode-hook 'set-bigger-spacing)
```

Anyway, this isn't really Spacemacs related, so I'm closing the issue. You're welcome to add the info to one of the SO questions - those threads usually have more visibility than Spacemacs issues and it will help more Emacs users.

**Comment by sebastiansturm** [comment]
there's a vertical-centering patch that may or may not be merged into emacs master (not sure about the current status): https://www.reddit.com/r/emacs/comments/cxywtc/i_wrote_a_patch_to_vertically_center_the_line/
https://lists.gnu.org/archive/html/emacs-devel/2019-08/msg00659.html
https://github.com/sollidsnake/emacs/
