### ISSUE TITLE
Difficult to rebind spacemacs/emmet-expand using emmet-mode

### ISSUE THREAD

**Issue by mdsib** [syl20bnr/spacemacs#10514]
`spacemacs/emmet-expand` is bound to tab when emmet-mode is initialized. See here: https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Blang/html/packages.el#L98

I would like to bind this to a different key, but I can't figure out a way to override the config for a `use-package` declaration, and don't know if there is a way to do that. If there isn't, I can make a PR that allows this section to be customizeable, perhaps with something like this:
```emacs-lisp
(defcustom html/emmet-mode-config-function 'html/emmet-init-config
 "Function to configure emmet-mode's config")
...
(defun html/emmet-init-config ()
 <keybinding sexps here>
)
...
(use-package emmet-mode
 ...
 :config
 (funcall html/emmet-mode-config-function)
)
```
Any other ideas of solving this issue?

**Comment by Chream** [comment]
See #10479. I think it solves this?

**Comment by mdsib** [comment]
It fixes a big issue I was having with that keybinding, but there's at least one other issue that makes me want to remap it. The react layer uses the html layer and emmet-mode, which is very useful when writing jsx, so I don't want it disabled completely. But initializing emmet-mode maps tab to `spacemacs/emmet-expand`, which causes an object accessor in plain js like `foo.bar<tab>` to expand to `<foo className="bar"></foo>`. I believe the simplest solution to this would be to allow the user to choose a different keybinding for `spacemacs/emmet-expand`.

**Comment by CarlQLange** [comment]
This is still an issue, unfortunately.

**Comment by kylesnowschwartz** [comment]
Thank you for this open issue which allowed me to discover why trying to map a different code completion function to `tab` was failing!

**Comment by smile13241324** [comment]
I have merged a fix for emmet-expand which was wrongly bound to tab, tab is reserved for auto-completion, now emmet-expand is bound to `C-return` which should solve your issues with rebinding tab.

You can simply rebind the key in your user-init with
``` elisp
  ;;; To bind to C-, instead
  (spacemacs|use-package-add-hook emmet-mode :post-config (define-key emmet-mode-keymap (kbd "C-,") 'spacemacs/emmet-expand))
```
