### ISSUE TITLE
Adding daemon-mode for macOS

### ISSUE THREAD

**Issue by anmoljagetia** [syl20bnr/spacemacs#10519]
I have been an avid user of spacemacs for more than an year now. The Documentation refers on how to run [emacs in daemon mode in Linux](https://github.com/syl20bnr/spacemacs/blob/master/doc/BEGINNERS_TUTORIAL.org#daemon-mode-and-instant-startup-linux). There are no reliable guide on how to do this on the Internet.  I have written a detailed [blog post](https://blog.anmoljagetia.me/perfect-macos-launcher-for-emacs/) on how to achieve this on macos (although it's a bit hacky). 

It would be great if you could include this in the documentation, through a link to the post, or I can issue a MR if you can add this into the main repo. I would have appreciated something like this when I was starting out. I am in no way, an expert on the subject, but it would be a good contribution from a noob just starting out with the super awesome spacemacs community!

Please keep doing the great work! Cheers!

**Comment by NightMachinary** [comment]
Homebrew does give commands to autolaunch the daemon for macOS.

**Comment by anmoljagetia** [comment]
Unfortunately, Homebrew has dropped support for all flags and now recommends installation with the Cask method that doesn't support daemon mode (Atleast without tinkering with the package). Also, this would have to be done on all subsequent updates.

**Comment by bushwakko** [comment]
Emacs-plus has support for said flags still
