### ISSUE TITLE
Projectile Helm Error

### ISSUE THREAD

**Issue by harveyslash** [syl20bnr/spacemacs#10511]
#### Description :octocat:
Helm Projectile gives error

#### Reproduction guide :beetle:
- Start Emacs
- go to some 'project' which has a .git
- press SPC p h to invoke helm projectile

*Observed behaviour:* :eyes: :broken_heart:
Getting error : `wrong type argument:stringp,nil`

*Expected behaviour:* :heart: :smile:
Error should not show up

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python markdown helm emacs-lisp git org markdown shell
        (auto-completion :variables auto-completion-enable-help-tooltip t)
        themes-megapack search-engine)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB

#### Backtrace :paw_prints:
I was unable to get the backtrace to copy to my clipboard using SPC b Y
<img width="1416" alt="screen shot 2018-03-22 at 10 13 35 am" src="https://user-images.githubusercontent.com/7107410/37775654-e1c15b80-2db9-11e8-939c-80b2d6b43b4c.png">

**Comment by LouisDelbosc** [comment]
I have the same unexpected behavior

- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml sql helm python javascript react auto-completion emacs-lisp elixir git markdown)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by mijoharas** [comment]
Dupe of https://github.com/syl20bnr/spacemacs/issues/10506

**Comment by mijoharas** [comment]
(see there for a mitigation). :)

**Comment by harveyslash** [comment]
That solves it for me.

**Comment by trcoffman** [comment]
Since #10506 is closed this should be too since it's a duplicate.

**Comment by romariolopezc** [comment]
I tried duianto's fix but had no success :/
