### ISSUE TITLE
MacOS running the app as client

### ISSUE THREAD

**Issue by harveyslash** [syl20bnr/spacemacs#10517]
I know that its possible to run spacemacs in daemon mode , and connect in the terminal using -nw. 
Is there a way to launch the GUI App as a client ?

**Comment by anmoljagetia** [comment]
Hey @harveyslash !

Sorry for the plug, but you can refer to my blog [here](https://blog.anmoljagetia.me/perfect-macos-launcher-for-emacs/) and find instructions on how to run this in daemon mode. The slow startup did bum me out, but this is the best I can do till now.

Please let me know in case of any concerns.

**Comment by NightMachinary** [comment]
There is: `emacsclient -c -n`. You can ommit -n to make the terminal wait for emacs.

**Comment by jsoo1** [comment]
@harveyslash was your question answered? If so can his issue be closed?
