### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by piggy00wiggy** [syl20bnr/spacemacs#10523]
%3C%3CREPLACE%20ALL%20UPPERCASE%20EXPRESSIONS%20AND%20DELETE%20THIS%20LINE,%20%60C-c%20C-c%60%20TO%20SUBMIT%3E%3E%0A%23%23%23%23%20Description%20:octocat:%0AAfter%20commenting%20several%20lines%20in%20dotspacemacs,%20and%20SPC%20b%20p%20to%20return%20to%20a%20.tex%20file%20that%20is%20being%20edited,%20the%20commented%20content%20will%20be%20pasted%20into%20the%20tex%20file%20somewhere.%0A%23%23%23%23%20Reproduction%20guide%20:beetle:%0A-%20Start%20Emacs%0A-%20open%20my%20.tex%20file%20from%20Recent%20files%0A-%20cannot%20automatically%20load%20latex-mode%0A-%20M-x%20to%20load%20latex-mode,%20prompt%20%22wrong%20type%20argument:%20listp%20Skim%22%0A-%20SPC%20f%20e%20d%20to%20open%20dotspacemacs,%20and%20comment%20lines%20as%20follows:%0A%20%20(setq-correlate-mode%20t)%0A%20%20(setq%20TeX-source-correlate-method%20'synctex)%0A%20%20(setq%20TeX-source-correlate-start-server%20t)%0A%20%20(setq%20TeX-view-program-list%0A%20%20%20%20%20%20%20%20'(%22Skim%22%20%22displayline%20-b%20-g%20%n%20%o%20%b%22))%0A%20%20(eval-after-load%20'tex%0A%20%20%20%20'(progn%0A%20%20%20%20%20%20%20(assq-delete-all%20'output-pdf%20TeX-view-program-selection)%0A%20%20%20%20%20%20%20(add-to-list%20'TeX-view-program-selection%20'(output-pdf%20%22Skim%22))))%0A-%20close%20spacemacs%20and%20reopen%20it,%20then%20open%20the%20tex%20files%0A-%20latex-mode%20can%20be%20loaded%20but%20the%20commented%20lines%20would%20be%20pasted%20somewhere%20in%20the%20tex%20file%0A%0A*Observed%20behaviour:*%20:eyes:%20:broken_heart:%0A%3C%3CDESCRIPTION%20OF%20THE%20OBSERVED%20BEHAVIOUR%3E%3E%0A%0A*Expected%20behaviour:*%20:heart:%20:smile:%0A%3C%3CDESCRIPTION%20OF%20THE%20EXPECTED%20BEHAVIOUR%3E%3E%0A%0A%23%23%23%23%20System%20Info%20:computer:%0A-%20OS:%20darwin%0A-%20Emacs:%2025.3.1%0A-%20Spacemacs:%200.200.10%0A-%20Spacemacs%20branch:%20master%20(rev.%204bb4cb469)%0A-%20Graphic%20display:%20t%0A-%20Distribution:%20spacemacs%0A-%20Editing%20style:%20vim%0A-%20Completion:%20helm%0A-%20Layers:%0A%60%60%60elisp%0A((python%20:variables%20python-enable-yapf-format-on-save%20t)%0A%20(c-c  %20:variables%20c-c  -default-mode-for-headers%20'c  -mode%20c-c  -enable-clang-support%20t)%0A%20auto-completion%20better-defaults%20emacs-lisp%20osx%20git%20markdown%20spacemacs-org%20latex%20bibtex%0A%20(shell%20:variables%20shell-default-term-shell%20%22/bin/zsh%22%20shell-default-height%2030%20shell-default-position%20'bottom%20exec-path-from-shell-check-startup-files%20nil)%0A%20spell-checking)%0A%60%60%60%0A-%20System%20configuration%20features:%20JPEG%20NOTIFY%20ACL%20GNUTLS%20LIBXML2%20ZLIB%20TOOLKIT_SCROLL_BARS%20NS%0A%0A%0A%23%23%23%23%20Backtrace%20:paw_prints:%0A%60%60%60%0A%3C%3CBACKTRACE%20IF%20RELEVANT%3E%3E%0A%60%60%60%0A

**Comment by piggy00wiggy** [comment]
the first commented line should be (setq TeX-source-correlate-mode t)

which is wrong typed in the description

**Comment by smile13241324** [comment]
@piggy00wiggy you need to rework your issue report.
* I cannot read the content it looks like garbled up html source in the github web interface.
* Adjust the headline of your issue report to a short summary of your issue, do not use "bug report" for this.

**Comment by piggy00wiggy** [comment]
@smile13241324 I just followed the bug report instruction from spacemacs, I dont know why it looks like this..

anywhere I will edit this issue when I have time

**Comment by jsoo1** [comment]
@piggy00wiggy would you mind closing the issue until there is a better formatted one?

**Comment by piggy00wiggy** [comment]
@jsoo1 yes I will close later
