### ISSUE TITLE
Spacemacs license?

### ISSUE THREAD

**Issue by dojeda** [syl20bnr/spacemacs#1052]
This is an excellent collection of packages, customization and more regarding emacs and evil-mode.
I'd like to copy some of your code to my own starter kit, which is several orders of magnitude more amateur, noobish, and personal.

I could not find what is the license of spacemacs on your github repo, so I'm not sure if I have the right to copy some of your code and reference spacemacs as the source. The only information I found was https://www.openhub.net/p/spacemacs which indicates AGPL 3.0+. Is this accurate?

**Comment by cpaulik** [comment]
It should be GPL3 -> https://github.com/syl20bnr/spacemacs/blob/master/doc/CONTRIBUTE.md#license

**Comment by dojeda** [comment]
Ah, sorry I missed that. Thanks
