### ISSUE TITLE
Add haskell-ide-engine support

### ISSUE THREAD

**Issue by IvanMalison** [syl20bnr/spacemacs#10520]
https://github.com/haskell/haskell-ide-engine and https://github.com/emacs-lsp/lsp-haskell seem to have finally reached a level of stability/ease of use that they should probably be added as an option for haskell support in spacemacs.

I made a PR to add instructions to the README for installing with emacs here https://github.com/haskell/haskell-ide-engine/pull/502

**Comment by siddharthist** [comment]
I've begin work on this, my branch is available here: https://github.com/syl20bnr/spacemacs/compare/develop...siddharthist:lsp-hie?expand=1

I'm running into the following issue, which has halted my progress: https://github.com/emacs-lsp/lsp-haskell/issues/28

**Comment by duianto** [comment]
The PR:
Haskell: add LSP support via HIE and lsp-haskell #11887
is now on the develop branch.

There's a comment: https://github.com/syl20bnr/spacemacs/pull/11887#issuecomment-462172870 on that PR, that states that it might fix this issue, can someone confirm?

**Comment by demokritos** [comment]
I can confirm that lsp works via hie.
But it seems that line breaks are missing in the information box for symbols,
![spacemacs_lsp_hie](https://user-images.githubusercontent.com/3399860/56075663-23327b80-5e01-11e9-914e-131ab8ce0bbc.png)
Also often the box is too small to show the content.
I know that this is spacemacs's problem, but I don't know who concerns.

**Comment by Compro-Prasad** [comment]
Maybe @yyoncho

**Comment by yyoncho** [comment]
@demokritos I think this is lsp-ui feature, you may open lsp-ui issue so we could work on improving it.

**Comment by razvan-panda** [comment]
Has this been implemented?

**Comment by duianto** [comment]
@razvan-panda This PR has been merged into the `develop` branch:
Haskell: add LSP support via HIE and lsp-haskell #11887

There has not been a `master` branch release with it yet, but it's in the works.
