### ISSUE TITLE
Consider using zoom as an alternative for golden-ratio

### ISSUE THREAD

**Issue by CarlQLange** [syl20bnr/spacemacs#10521]
https://github.com/cyrus-and/zoom

Just a thought, completely happy to see this closed, I don't really know what the advantages/disadvantages are between the two. I've personally seen some janky behaviour from golden-ratio but nothing I'd really call a bug. Perhaps an option would be to allow usage of either one, kind of like the way we do with helm and ivy or company and auto-complete.

**Comment by CarlQLange** [comment]
(I wish I could add labels to issues!)

**Comment by NightMachinary** [comment]
Use in user-config:
```
(with-eval-after-load 'zoom
    (setq zoom-size '(0.618 . 0.618))
    (spacemacs/set-leader-keys "tg" 'zoom-mode))
```
