### ISSUE TITLE
eomij + org-entry-put => "match data clobbered by buffer modification hooks".

### ISSUE THREAD

**Issue by georgewsinger** [syl20bnr/spacemacs#10527]
Using the `emoji` layer in spacemacs causes `org-entry-put` to generate the error "match data clobbered by buffer modification hooks".

**Comment by Miciah** [comment]
This issue looks like https://github.com/syl20bnr/emacs-emoji-cheat-sheet-plus/issues/5.

**Comment by Miciah** [comment]
This issue has been fixed upstream with https://github.com/syl20bnr/emacs-emoji-cheat-sheet-plus/pull/9.

**Comment by duianto** [comment]
Thanks for the update.
