### ISSUE TITLE
Emacs become unresponsive when editing .spacemacs 

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10524]
#### Description :octocat:
- Start Emacs
- Go to .spacemacs file
- try writing `(setq ac`
- Emacs starts uncompressing and parsing tons of files, and becomes unresponsive for some seconds. Then start typing another thing like `(setq to` and this happens again.
Such behavior is very weird. If it needs to do some indexing or something it should be done once when the daemon is started, and not bother the user. I guess this has to do with company completion, btw.

![image](https://user-images.githubusercontent.com/36224762/37867816-543073e2-2fbb-11e8-8863-c0a9e79a2d68.png)

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: added-dvorak-right-handed-to-keyboard-layout-layer (rev. 90440e5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript vimscript
            (rust :variables rust-format-on-save t)
            (haskell :variables haskell-enable-hindent t)
            semantic
            (c-c++ :variables c-c++-enable-clang-support t)
            html python chrome
            (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
            autohotkey kotlin helm
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
            emacs-lisp
            (ibuffer :variables ibuffer-group-buffers-by 'modes)
            coq emoji
            (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
            git
            (java :variables java-backend 'ensime)
            markdown org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-tooltips t)
            (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
            version-control osx racket clojure)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by OkIdeal0** [comment]
This is probably an issue with semantic. See #1907

**Comment by NightMachinary** [comment]
@OkIdeal0 Thanks, and yes that's it. It doesn't seem fixed though :(

**Comment by duianto** [comment]
It might be related to the `semantic` layer.
I seem to remember hesitation, while those parsing messages were shown in the minibuffer, like in your screenshot.
