### ISSUE TITLE
Issue with modeline icons

### ISSUE THREAD

**Issue by bradrn** [syl20bnr/spacemacs#10529]
#### Description :octocat:
I just updated to emacs 25.3.1 from emacs 25.1.1. I noticed that the modeline is now broken: the window number icon had become almost unreadably small, and the major mode indicators had been replaced with boxes.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The modeline has a very small window number, and the major mode indicators are replaced with boxes:

![image](https://user-images.githubusercontent.com/17613703/37893273-3909455a-3126-11e8-84b6-9e013d3b2253.png)

*Expected behaviour:* :heart: :smile:
The modeline looks has a readable window number, and the major mode indicators are letters:

![image](https://user-images.githubusercontent.com/17613703/37893369-816f5028-3126-11e8-8efe-eca37d489a33.png)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git
      (spell-checking :variables ispell-dictionary "british" spell-checking-enable-by-default nil)
      (syntax-checking :variables syntax-checking-enable-tooltips nil)
      (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell")
      (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill nil)
      themes-megapack ibuffer ranger html javascript
      (shell :variables shell-default-shell 'eshell shell-default-position 'right)
      yaml evil-snipe python common-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by jsoo1** [comment]
This looks like a problem with your font. Can you make sure Source Code Pro or your chosen font is installed?  Also, this would be a good question for the gitter channel, some join us :smile:.

**Comment by bradrn** [comment]
I am using the same font which worked with my previous emacs.

**Comment by jsoo1** [comment]
Which font is it and is it installed in your system? I see you’re on Windows so I’m not sure how font resolution works there, but this would be something that might happen on Linux if your font wasn’t found in the system.

**Comment by bradrn** [comment]
I'm using Consolas. The strange thing is that everything worked perfectly with the same setup with emacs 25.1.1, but as soon as I updated to emacs 25.3.1 the modeline stopped working.

**Comment by jsoo1** [comment]
Hey there.  Did you ever find a solution to your issue?

**Comment by bradrn** [comment]
No, I didn't.

**Comment by bradrn** [comment]
I've just upgraded to emacs 26.1 and the issue seems to have gone away:
![image](https://user-images.githubusercontent.com/17613703/40955657-b2926d9a-68ce-11e8-8e06-20b023968be3.png)
This must have been an issue with emacs 25.3. I'll reopen this if the issue reappears.
