### ISSUE TITLE
How to show the context after finding the file and text using (spacemacs/helm-project-do-rg)

### ISSUE THREAD

**Issue by zhixing2017** [syl20bnr/spacemacs#10537]
I often use the command `(spacemacs/helm-project-do-rg)`. 

But there is a little problem. Every time I run the command, I must run `(org－reveal)` to unfold the context.

Is there a simple way to open the context after finding the target?

Thank you.

Here is the information of PC.

Windows 7, 32 bit
GNU Emacs 25.3.1 (i686-w64-mingw32)
Org mode version 9.1.9
Spacemacs 0.300.0

**Comment by Miciah** [comment]
How about the following?
```emacs-lisp
(defun spacemacs/org-reveal (&rest _args)
  (when (derived-mode-p 'org-mode)
    (org-reveal)))
(advice-add 'helm-ag--find-file-action :after #'spacemacs/org-reveal)
```
(I would use `org-mode-hook`, but hooks run before `helm-ag--find-file-action` has positioned point.)

**Comment by Miciah** [comment]
This issue looks like a duplicate of https://github.com/syl20bnr/spacemacs/pull/9529, which has been reported upstream: https://github.com/syohex/emacs-helm-ag/issues/303, with propose fix: https://github.com/syohex/emacs-helm-ag/pull/304.

Meanwhile, I have been using the workaround I suggested in my previous comment.

**Comment by zhixing2017** [comment]
The code you provided works. Thanks very much.

**Comment by Miciah** [comment]
@fleimgruber, I don't understand what you mean by "`spacemacs/org-reveal` is not there anymore".  The workaround defines the `spacemacs/org-reveal` function and then uses `advise-add` to run `spacemacs/org-reveal` after helm-ag jumps to the target.  I have the following in my `dotspacemacs/user-config` definition, and it still works for me:

```emacs-lisp
(use-package org
    :defer t
    :config
    (defun spacemacs/org-reveal (&rest _args)
      (when (derived-mode-p 'org-mode)
        (org-reveal)))
    (advice-add 'helm-ag--find-file-action :after #'spacemacs/org-reveal))
```

**Comment by fleimgruber** [comment]
Well this is embarassing, sorry for the noise, just ignore my comment please. And thanks for the shove.

**Comment by duianto** [comment]
The following PRs changes have been cherry-picked into the develop branch:
Unfold an org line from helm-ag and magit #12750
