### ISSUE TITLE
C-h doesn't work in the help minibuffer displayed for evil commands using text objects

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10536]
#### Description :octocat:
C-h doesn't work in the help minibuffer displayed for evil commands using text objects.

#### Reproduction guide :beetle:
- Start Emacs
- Press yi in the normal.
- A help minibuffer would appear as expected, detailing possible text objects.
- Try C-h for paging.
- The minibuffer quits.

*Expected behaviour:* :heart: :smile:
It shouldn't quit. It is an excellent resource I need for learning what text objects are available.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: added-dvorak-right-handed-to-keyboard-layout-layer (rev. 90440e5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(windows-scripts javascript vimscript
                 (rust :variables rust-format-on-save t)
                 (haskell :variables haskell-enable-hindent t)
                 semantic lsp
                 (c-c++ :variables c-c++-enable-clang-support t)
                 html python chrome
                 (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
                 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
                 autohotkey kotlin helm
                 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
                 emacs-lisp
                 (ibuffer :variables ibuffer-group-buffers-by 'modes)
                 coq emoji
                 (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
                 git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking
                 (syntax-checking :variables syntax-checking-enable-tooltips t)
                 (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
                 version-control osx racket clojure)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Confirmed.

It's not Spacemacs specific, because it also happens when running:
`emacs --quick` and only enabling `evil` and `which-key`.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm auto-completion emacs-lisp git html org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by jsoo1** [comment]
Can this be closed? Looks like you got your answer upstream, @NightMachinary

**Comment by NightMachinary** [comment]
@jsoo1 Sure.
