### ISSUE TITLE
mu4e layer fails to load 'mu4e-context

### ISSUE THREAD

**Issue by eklitzke** [syl20bnr/spacemacs#10530]
#### Description :octocat:
mu4e-layer fails to load 'mu4e-context

#### Reproduction guide :beetle:
- Start Emacs
- Using mu4e built from the upstream 1.0 release tag and installed as a site package
- Notice that make-mu4e-context and related functions are undefined

I'm confused as to *why* this is the case, as it seems to be required by mu4e.el:

```
$ grep mu4e-context /usr/share/emacs/site-lisp/mu4e/mu4e.el
(require 'mu4e-context)  ;; support for contexts
```

I can fix this by adding to my config:

```elisp
(require 'mu4e-context)
```

But I don't think this is supposed to be necessary.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658cd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t c-c++-enable-google-newline t c-c++-enable-google-style t c-c++-enable-rtags-support t)
                 clojure colors common-lisp docker emacs-lisp evan git github
                 (go :variables gofmt-command "goimports")
                 helm html java javascript markdown
                 (mu4e :variables mu4e-enable-async-operations t mu4e-enable-mode-line t)
                 neotree nginx octave
                 (org :variables org-projectile-file
                      (expand-file-name "~/org/projects.org")
                      org-enable-github-support t)
                 puppet
                 (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t python-test-runner 'pytest)
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (shell-scripts :variables sh-basic-offset 2 sh-indentation 2)
                 spell-checking sql syntax-checking systemd twitter version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by JadElClemens** [comment]
Having the same issue on master, v0.200.13-1-gc7a103a77
