### ISSUE TITLE
a small error about line number in the spacemacs document

### ISSUE THREAD

**Issue by flySword** [syl20bnr/spacemacs#10546]
I am new to spacemacs.

In the help document ( SPC-h-SPC ), line 1154, 1167, 1176 , 1183

the variable `dotspacemacs-line-numbers` is written to `dotspacemacs-lines-numbers`, the 's' makes the setting invalid.

**Comment by duianto** [comment]
Thanks for reporting the issue, however it has already been fixed on the `develop` branch: 
fix spelling of variable in documentation #9619

It will be corrected on the `master` branch, when the next major Spacemacs version is released.

**Comment by flySword** [comment]
Sorry for the omission in searching. Thanks!
