### ISSUE TITLE
Evil Unimpaired doesn't work with golden-ratio

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10540]
#### Description :octocat:
Evil Unimpaired doesn't work with golden-ratio. The problem is with these functions probably:
(define-key evil-normal-state-map (kbd "[ w") 'previous-multiframe-window)
(define-key evil-normal-state-map (kbd "] w") 'next-multiframe-window)

#### Reproduction guide :beetle:
- Start Emacs
- Activate golden-ratio.
- Create some windows.
- Navigation using 'SPC w w' works.
- But using '[w' ']w' doesn't activate golden-ratio.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: added-dvorak-right-handed-to-keyboard-layout-layer (rev. 90440e5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(fsharp windows-scripts javascript vimscript
        (rust :variables rust-format-on-save t)
        (haskell :variables haskell-enable-hindent t)
        semantic lsp
        (c-c++ :variables c-c++-enable-clang-support t)
        html python chrome
        (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
        autohotkey kotlin helm
        (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
        emacs-lisp
        (ibuffer :variables ibuffer-group-buffers-by 'modes)
        coq emoji
        (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
        git markdown org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spell-checking
        (syntax-checking :variables syntax-checking-enable-tooltips t)
        (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
        version-control osx racket clojure)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```

```

**Comment by NightMachinary** [comment]
I can confirm this bug isnot present in zoom-mode. 
https://github.com/syl20bnr/spacemacs/issues/10521

**Comment by duianto** [comment]
The `next-multiframe-window` and `previous-multiframe-window` functions, just had to be added to the `golden-ratio-extra-commands` variable.
