### ISSUE TITLE
Fresh install of packages fails at magit

### ISSUE THREAD

**Issue by natecox** [syl20bnr/spacemacs#10543]
Had an issue upgrading my packages earlier which resulted in a failure to start emacs. I dropped my `.spacemacs` and `.emacs.d/` to do a fresh install, and I still end up with the same issue. See the screenshot below for exact details.

<img width="1001" alt="screen shot 2018-03-29 at 16 19 12" src="https://user-images.githubusercontent.com/2782695/38118010-fc07a5a4-336c-11e8-9738-76f68422cd89.png">

**Comment by radious** [comment]
See my comment in the magit/magit project: https://github.com/magit/magit/commit/4246392dc22239871d193eb7cae212d28cfcbf33#r28340731

**Comment by kommen** [comment]
The fix magit fix https://github.com/magit/magit/commit/80fb5cdcb5cb3d54b8fd6b0a205a4facfdbc137d mentioned here https://github.com/magit/magit/commit/4246392dc22239871d193eb7cae212d28cfcbf33#r28341614 seems to have fixed this issue for me.

**Comment by natecox** [comment]
Was just able to update packages successfully. Thanks!
