### ISSUE TITLE
Use terminal colors when execute with -nw

### ISSUE THREAD

**Issue by grg121** [syl20bnr/spacemacs#10550]
Hi there! I would like to make my spacemacs not to load a theme when start in terminal but use default terminal colors. When I start emacs with -nw it use the colors I want it to use while loading but then it load the default theme and overload them.

I've tried to disable default themes in .spacemacs file but it only make spacemacs to load a different theme .__.

Any idea of how could I do that easily?? 

Thanks :D

**Comment by CeleritasCelery** [comment]
maybe add this at the end of your `dotspacemacs/user-config`
```lisp
(unless (display-graphic-p)
   (disable-theme '<theme>))
```

**Comment by jsoo1** [comment]
@grg121 Did this work for you?

**Comment by grg121** [comment]
nop, @jsoo1  :/

**Comment by c02y** [comment]
I'd like this feature too. 

Spacemacs doesn't allow to disable using a theme. it is very unfriendly when using emacs in terminal.
