### ISSUE TITLE
spacemacs develop version conflict with yasnippet?

### ISSUE THREAD

**Issue by vinurs** [syl20bnr/spacemacs#10554]
#### Description :octocat:
I used spacemacs's develop up-to-date version, when i use its auto-completion layer, and in a file test snippet, code as following:
``` example
hello1
(yas-expand-snippet (buffer-string) (point-min) (point-max))
```
and execute C-x C-e after `(yas-expand-snippet (buffer-string) (point-min) (point-max))`
i found the buffer's content become:
``` example
hello1
(yas-expand-snippet (buffer-string) (point-min) (point-max))
hello1
(yas-expand-snippet (buffer-string) (point-min) (point-max))
```
It seems yas-expand-snippet didn't replace but append. when i remove the auto-completion layer, then it works ok
but, if I do this in master branch, it works ok, it seems that spacemacs develop branch doesn't work with auto-completion 

#### Reproduction guide :beetle:
- Start Emacs
- turn on auto-completion layer
- open a empty file, copy
```
hello1
(yas-expand-snippet (buffer-string) (point-min) (point-max))
```
- C-x C-e after `(yas-expand-snippet (buffer-string) (point-min) (point-max))` 
- found the buffer's content is appended, not replaced

*Observed behaviour:* :eyes: :broken_heart:

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm vinurs-better-defaults emoji emacs-lisp sql javascript java
      (clojure :variables clojure-enable-fancify-symbols nil)
      git markdown yaml neotree html
      (org :variables org-enable-hugo-support t)
      vinurs-orgmode vinurs-devs)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Miciah** [comment]
Are you still able to reproduce this issue? I could not reproduce it using Spacemacs rev. 0fa3658 and yasnippet  0.12.2 or 0.13.0.  Could the issue be caused by something in one of your custom layers?
