### ISSUE TITLE
Issue with loading RUST_SRC_PATH and behavior difference for env vars between .profile and .zshenv

### ISSUE THREAD

**Issue by willbush** [syl20bnr/spacemacs#10551]
##### Summary

There are potentially two issues here. 

1. Setting environmental variables in `.profile` behaves differently than
   setting them in `.zshenv`. Setting variables in `.profile` appear to get
   loaded into the `process-environment` varable, but `.zshenv` do not.

2. Perhaps `(spacemacs|use-package-add-hook exec-path-from-shell ...` is not
   getting called in `layers/+lang/rust/packages.el` or something else is broken
   here.

##### Details

As of commit in the develop branch: `0fa3658 develop origin/develop reorganize
spacemacs-base distribution into +spacemacs/spacemacs-xxx` I noticed that my
environmental variable I use for rust `RUST_SRC_PATH` is no longer getting set
properly in emacs. I've had some fun trying to figure out why, but I need to
learn more about elisp to really solve this myself.

First, I noticed that my path wasn't what I set it to, it was set to the result
of `rustc --print sysroot`, but I want it to be set to a local clone of the
compiler because I'm messing around with private features.

I noticed from `racer.el` this function:

```elisp
(defcustom racer-rust-src-path
  (or
   (getenv "RUST_SRC_PATH")
   (when (executable-find "rustc")
     (let* ((sysroot (s-trim-right
                      (shell-command-to-string
                       (format "%s --print sysroot" (executable-find "rustc")))))
            (src-path (f-join sysroot "lib/rustlib/src/rust/src")))
       (when (file-exists-p src-path)
         src-path)
       src-path))
   "/usr/local/src/rust/src")
```

When I perform eval-expression `M-:` `(getenv "RUST_SRC_PATH")` it returns nil
from the develop branch (rev. 0fa3658), which explains why my path is getting
set to `rustc --print sysroot` instead of what my env var is set to.

I can checkout the commit before the most recent and `(getenv "RUST_SRC_PATH")`
works. To checkout the commit I'm talking about do `git checkout 2e8727a` or `git
checkout HEAD~1` depending on if 0fa3658 is still latest.

According to the documentation on `getenv`, when optional FRAME is not included
in `(getenv VARIABLE &optional FRAME)` it searches in through the
`process-environment` variable. So I switched between latest develop and `HEAD~1`
to verify that the `process-environment` does not contain `RUST_SRC_PATH` when
on 0fa3658, but it does on the commit before.

I use ZSH and set my environmental variable in `.zshenv` as the FAQ recommends:

>It is recommended to set such variables in shell configuration files that are
>sourced unconditionally, such as =.profile=, =.bash_profile= or =.zshenv=, as
>opposed to files that are sourced only for interactive shells, such as =.bashrc=
>or =.zshrc=.

This leads to a potentially separate issue or perhaps misunderstanding on my
part. If I set `RUST_SRC_PATH` in `.profile` it ends up in `process-environment`
fine on both latest and `HEAD~1`. However, I noticed that none of my other
environmental variables from zshenv were making it into `process-environment` on
either commit. I'm not sure if this is a bug or intended. I don't see how it
makes a difference because I can run the terminal command `printenv` and
variables I set i `.profile` or `.zshenv` print out either way.

This also begs the quesion, why was `RUST_SRC_PATH` making it into
`process-environment` when I was using `.zshenv` when none of the others were
(e.g. CARGO_HOME etc)?

I searched recursively through `.emacs.d` for `RUST_SRC_PATH` and noticed in
`layers/+lang/rust/packages.el`:

```elisp
(defun rust/pre-init-exec-path-from-shell ()
  (spacemacs|use-package-add-hook exec-path-from-shell
    :pre-config
    (let ((var "RUST_SRC_PATH"))
      (unless (or (member var exec-path-from-shell-variables) (getenv var))
        (push var exec-path-from-shell-variables)))))
```

After playing around with this function a little `(member var
exec-path-from-shell-variables)` evals to nil because my rust source path is not
a member of exec-path-from-shell-variables whose value is `("PATH" "MANPATH")`.
Also, `getenv` call returns nil same as before.

So it does push the path variable on to the `exec-path-from-shell-variables`
list when I manually evaluate this.

So then I noticed when I checkout the commit before latest
`exec-path-from-shell-variables` has value `("RUST_SRC_PATH" "PATH" "MANPATH")`.
However, when I checkout latest, close emacs, and re-open emacs it has value
`("PATH" "MANPATH")`. So I guess the hook is not getting called or something
about it is not working since the latest commit. 

I noticed a lot of things changed with hooks in commit `0fa3658`, but I'm not
good enough with elisp yet to really see what exactly went wrong.

#### Reproduction guide :beetle:

1. install ZSH
2. running `echo $SHELL` should output `/bin/zsh`
3. create a `.zshenv` file with the line `export TEST=test`
4. logout and back in
5. `printenv | grep TEST` should show the test environmental variable loaded
6. Start Emacs on latest develop branch
7. perform eval-expression `M-:` `(getenv "TEST")` and it returns nil
8. Also, you can `SPC h d v` and type `process-environment` and it will show a
   list of environmental vars. If you can reproduce, `TEST` should not be in the
   list.

If you put the same in `.profile` instead, then it will make it into
`process-environment`.

For the `RUST_SRC_PATH` issue, perform same steps above, but replace `TEST` for
`RUST_SRC_PATH`. Then do the following:

1. Install the rust layer.
2. Ensure you're on latest develop (currently rev. 0fa3658).
3. Restart emacs.
4. `SPC h d v` and type `process-environment` and it should not show `RUST_SRC_PATH`.
5. `git checkout 2e8727a`
6. completely quit emacs and start it back up. I think `process-environment`
   does not get reloaded when only restarting (not 100% sure).
7. `SPC h d v` and type `process-environment` and it should show `RUST_SRC_PATH`.

*Observed behaviour:* :eyes: :broken_heart:

Racer completion was not working correctly for the rust layer. See description
for more info.

*Expected behaviour:* :heart: :smile:

I would expect racer.el to be able to get my `RUST_SRC_PATH` environment
variable from my `.zshenv`.

I would expect setting variables in `.profile` to behave the same as setting
them in `.zshenv`.

#### System Info :computer:

- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

```elisp
(markdown html emacs-lisp
          (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell" haskell-compile-cabal-build-command "stack build")
          (python :variables python-test-runner 'pytest)
          rust csharp yaml
          (auto-completion :variables auto-completion-private-snippets-directory "~/dotfiles/spacemacs/snippets/")
          git helm neotree
          (org :variables org-enable-github-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          spell-checking syntax-checking themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by anton-trunov** [comment]
Hi @willbush, it's been a while since you opened this issue. Is there an (unofficial) fix for this issue?

Btw, here is a workaround that works for me. I added

```elisp
(setq racer-rust-src-path "~/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src")
```

to the `dotspacemacs/user-config`function  in my `.spacemacs` file.

**Comment by willbush** [comment]
I went ahead and close the issue. I hardly recall anything about it. I'm sure the layer has changed enough since then that this is not worth worrying about.

**Comment by mfaerevaag** [comment]
For others coming over this issue, I'm having the same issue with `linum-mode`.
