### ISSUE TITLE
Problems with org-ident-mode and version-control layer

### ISSUE THREAD

**Issue by shitikanth** [syl20bnr/spacemacs#10555]
#### Description :octocat:
`version-control` layer seems to cause problems with `org-indent-mode`

#### Reproduction guide :beetle:
- Enable `org` and `version-control` layers in dotspacemacs.
- Restart Emacs.
- Open an org mode file and enable `org-indent-mode`.
- Create some headings and write some lines of text under the headings.

*Observed behaviour:* :eyes: :broken_heart:
Typing on a line in an org mode file causes the previous line to jump around (in indentation).

*Expected behaviour:* :heart: :smile:
Indentation on all lines should be visually stable, without any erratic and unexpected jumps.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree org version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by CeleritasCelery** [comment]
I cannot reproduce your issue on Master. The following packages are part of the `version-control` layer.
```
        diff-mode
        diff-hl
        evil-unimpaired
        git-gutter
        git-gutter+
        git-gutter-fringe
        git-gutter-fringe+
```

try selectively disabling these packages until you can find which package(s) is responsible for the behavior.
