### ISSUE TITLE
Layers is not instaling after adding to .spacemacs config

### ISSUE THREAD

**Issue by Volland** [syl20bnr/spacemacs#10556]
#### Description :octocat:
Layers is not instaling after adding to .spacemacs config

#### Reproduction guide :beetle:
- Start Emacs
- add git javascript org
- try refresh or restart
- run emacs --insecure

*Observed behaviour:* :eyes: :broken_heart:
I see a bunch of messages that package is unavailable or misspelled 

*Expected behaviour:* :heart: :smile:
get latest layers 

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown
      (org :variables org-enable-github-support t org-enable-reveal-js-support t)
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by CeleritasCelery** [comment]
Which packages is it complaining about? Can you post the relevant messages?

**Comment by Volland** [comment]
p(Spacemacs) --> installing package: ac-ispell@auto-completion... [1/41]
(Spacemacs) --> installing package: auto-complete@auto-completion... [2/41]
(Spacemacs) --> installing package: auto-dictionary@spell-checking... [3/41]
(Spacemacs) --> installing package: auto-yasnippet@auto-completion... [4/41]
(Spacemacs) --> installing package: esh-help@shell... [5/41]
(Spacemacs) --> installing package: eshell-prompt-extras@shell... [6/41]
(Spacemacs) --> installing package: eshell-z@shell... [7/41]
(Spacemacs) --> installing package: evil-magit@git... [8/41]
(Spacemacs) --> installing package: flyspell-correct@spell-checking... [9/41]
(Spacemacs) --> installing package: flyspell-correct-helm@spell-checking... [10/41]
(Spacemacs) --> installing package: fuzzy@auto-completion... [11/41]
(Spacemacs) --> installing package: gh-md@markdown... [12/41]
(Spacemacs) --> installing package: git-commit@git... [13/41]
(Spacemacs) --> installing package: git-link@git... [14/41]
(Spacemacs) --> installing package: git-messenger@git... [15/41]
(Spacemacs) --> installing package: git-timemachine@git... [16/41]
(Spacemacs) --> installing package: gitattributes-mode@git... [17/41]
(Spacemacs) --> installing package: gitconfig-mode@git... [18/41]
(Spacemacs) --> installing package: gitignore-mode@git... [19/41]
(Spacemacs) --> installing package: gnuplot@org... [20/41]
(Spacemacs) --> installing package: helm-c-yasnippet@auto-completion... [21/41]
(Spacemacs) --> installing package: helm-company@auto-completion... [22/41]
(Spacemacs) --> installing package: helm-gitignore@git... [23/41]
(Spacemacs) --> installing package: htmlize@org... [24/41]
(Spacemacs) --> installing package: magit@git... [25/41]
(Spacemacs) --> installing package: magit-gitflow@git... [26/41]
(Spacemacs) --> installing package: markdown-mode@markdown... [27/41]
(Spacemacs) --> installing package: markdown-toc@markdown... [28/41]
(Spacemacs) --> installing package: multi-term@shell... [29/41]
(Spacemacs) --> installing package: mwim@better-defaults... [30/41]
(Spacemacs) --> installing package: org-download@org... [31/41]
(Spacemacs) --> installing package: org-mime@org... [32/41]
(Spacemacs) --> installing package: org-pomodoro@org... [33/41]
(Spacemacs) --> installing package: org-present@org... [34/41]
(Spacemacs) --> installing package: org-projectile@org... [35/41]
(Spacemacs) --> installing package: orgit@git... [36/41]
(Spacemacs) --> installing package: ox-reveal@org... [37/41]
(Spacemacs) --> installing package: shell-pop@shell... [38/41]
(Spacemacs) --> installing package: smeargle@git... [39/41]
(Spacemacs) --> installing package: unfill@better-defaults... [40/41]
(Spacemacs) --> installing package: xterm-color@shell... [41/41]

**Comment by Volland** [comment]
Found 41 new package(s) to install...
--> refreshing package archive: gnu... [1/1]
--> installing package: ac-ispell@auto-completion... [1/41]
Package ac-ispell is unavailable. Is the package name misspelled?
--> installing package: auto-complete@auto-completion... [2/41]
Package auto-complete is unavailable. Is the package name misspelled?
--> installing package: auto-dictionary@spell-checking... [3/41]
Package auto-dictionary is unavailable. Is the package name misspelled?
--> installing package: auto-yasnippet@auto-completion... [4/41]
Package auto-yasnippet is unavailable. Is the package name misspelled?
--> installing package: esh-help@shell... [5/41]
Package esh-help is unavailable. Is the package name misspelled?
--> installing package: eshell-prompt-extras@shell... [6/41]
Package eshell-prompt-extras is unavailable. Is the package name misspelled?
--> installing package: eshell-z@shell... [7/41]
Package eshell-z is unavailable. Is the package name misspelled?
--> installing package: evil-magit@git... [8/41]
Package evil-magit is unavailable. Is the package name misspelled?
--> installing package: flyspell-correct@spell-checking... [9/41]
Package flyspell-correct is unavailable. Is the package name misspelled?
--> installing package: flyspell-correct-helm@spell-checking... [10/41]
Package flyspell-correct-helm is unavailable. Is the package name misspelled?
--> installing package: fuzzy@auto-completion... [11/41]
Package fuzzy is unavailable. Is the package name misspelled?
--> installing package: gh-md@markdown... [12/41]
Package gh-md is unavailable. Is the package name misspelled?
--> installing package: git-commit@git... [13/41]
Package git-commit is unavailable. Is the package name misspelled?
--> installing package: git-link@git... [14/41]
Package git-link is unavailable. Is the package name misspelled?
--> installing package: git-messenger@git... [15/41]
Package git-messenger is unavailable. Is the package name misspelled?
--> installing package: git-timemachine@git... [16/41]
Package git-timemachine is unavailable. Is the package name misspelled?
--> installing package: gitattributes-mode@git... [17/41]
Package gitattributes-mode is unavailable. Is the package name misspelled?
--> installing package: gitconfig-mode@git... [18/41]
Package gitconfig-mode is unavailable. Is the package name misspelled?
--> installing package: gitignore-mode@git... [19/41]
Package gitignore-mode is unavailable. Is the package name misspelled?
--> installing package: gnuplot@org... [20/41]
Package gnuplot is unavailable. Is the package name misspelled?
--> installing package: helm-c-yasnippet@auto-completion... [21/41]
Package helm-c-yasnippet is unavailable. Is the package name misspelled?
--> installing package: helm-company@auto-completion... [22/41]
Package helm-company is unavailable. Is the package name misspelled?
--> installing package: helm-gitignore@git... [23/41]
Package helm-gitignore is unavailable. Is the package name misspelled?
--> installing package: htmlize@org... [24/41]
Package htmlize is unavailable. Is the package name misspelled?
--> installing package: magit@git... [25/41]
Package magit is unavailable. Is the package name misspelled?
--> installing package: magit-gitflow@git... [26/41]
Package magit-gitflow is unavailable. Is the package name misspelled?
--> installing package: markdown-mode@markdown... [27/41]
Package markdown-mode is unavailable. Is the package name misspelled?
--> installing package: markdown-toc@markdown... [28/41]
Package markdown-toc is unavailable. Is the package name misspelled?
--> installing package: multi-term@shell... [29/41]
Package multi-term is unavailable. Is the package name misspelled?
--> installing package: mwim@better-defaults... [30/41]
Package mwim is unavailable. Is the package name misspelled?
--> installing package: org-download@org... [31/41]
Package org-download is unavailable. Is the package name misspelled?
--> installing package: org-mime@org... [32/41]
Package org-mime is unavailable. Is the package name misspelled?
--> installing package: org-pomodoro@org... [33/41]
Package org-pomodoro is unavailable. Is the package name misspelled?
--> installing package: org-present@org... [34/41]
Package org-present is unavailable. Is the package name misspelled?
--> installing package: org-projectile@org... [35/41]
Package org-projectile is unavailable. Is the package name misspelled?
--> installing package: orgit@git... [36/41]
Package orgit is unavailable. Is the package name misspelled?
--> installing package: ox-reveal@org... [37/41]
Package ox-reveal is unavailable. Is the package name misspelled?
--> installing package: shell-pop@shell... [38/41]
Package shell-pop is unavailable. Is the package name misspelled?
--> installing package: smeargle@git... [39/41]
Package smeargle is unavailable. Is the package name misspelled?
--> installing package: unfill@better-defaults... [40/41]
Package unfill is unavailable. Is the package name misspelled?
--> installing package: xterm-color@shell... [41/41]
Package xterm-color is unavailable. Is the package name misspelled?

**Comment by Volland** [comment]
(
     helm
      auto-completion
      better-defaults
     emacs-lisp
     git
     markdown
     (org :variables
          org-enable-github-support t
          org-enable-reveal-js-support t
     )
     (shell :variables
             shell-default-height 30
             shell-default-position 'bottom)
      spell-checking
     ;; syntax-checking
     ;; version-control
     )

**Comment by CeleritasCelery** [comment]
looks like none of them are installing. can you install them if you use `M-x package-install`?

**Comment by robbyoconnor** [comment]
Does this also occur on `develop`?

**Comment by robbyoconnor** [comment]
Try updating Emacs to the latest nightly

**Comment by Volland** [comment]
@robbyoconnor still same issue (

**Comment by kivikakk** [comment]
I'm getting this today! Just compiled latest Emacs (`emacs-version` reports `GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.25) of 2018-05-04`), cloned Spacemacs fresh, and after adding `auto-completion`, `git`, `syntax-checking`, `better-defaults` layers:

```
Found 20 new package(s) to install...
--> refreshing package archive: gnu... [1/1]
--> installing package: ac-ispell@auto-completion... [1/20]
Package ac-ispell is unavailable. Is the package name misspelled?
--> installing package: auto-complete@auto-completion... [2/20]
Package auto-complete is unavailable. Is the package name misspelled?
--> installing package: auto-yasnippet@auto-completion... [3/20]
Package auto-yasnippet is unavailable. Is the package name misspelled?
--> installing package: evil-magit@git... [4/20]
Package evil-magit is unavailable. Is the package name misspelled?
--> installing package: flycheck@syntax-checking... [5/20]
Package flycheck is unavailable. Is the package name misspelled?
--> installing package: flycheck-pos-tip@syntax-checking... [6/20]
Package flycheck-pos-tip is unavailable. Is the package name misspelled?
--> installing package: fuzzy@auto-completion... [7/20]
Package fuzzy is unavailable. Is the package name misspelled?
--> installing package: git-commit@git... [8/20]
Package git-commit is unavailable. Is the package name misspelled?
--> installing package: git-link@git... [9/20]
Package git-link is unavailable. Is the package name misspelled?
--> installing package: git-messenger@git... [10/20]
Package git-messenger is unavailable. Is the package name misspelled?
--> installing package: git-timemachine@git... [11/20]
Package git-timemachine is unavailable. Is the package name misspelled?
--> installing package: gitattributes-mode@git... [12/20]
Package gitattributes-mode is unavailable. Is the package name misspelled?
--> installing package: gitconfig-mode@git... [13/20]
Package gitconfig-mode is unavailable. Is the package name misspelled?
--> installing package: gitignore-mode@git... [14/20]
Package gitignore-mode is unavailable. Is the package name misspelled?
--> installing package: magit@git... [15/20]
Package magit is unavailable. Is the package name misspelled?
--> installing package: magit-gitflow@git... [16/20]
Package magit-gitflow is unavailable. Is the package name misspelled?
--> installing package: mwim@better-defaults... [17/20]
Package mwim is unavailable. Is the package name misspelled?
--> installing package: orgit@git... [18/20]
Package orgit is unavailable. Is the package name misspelled?
--> installing package: smeargle@git... [19/20]
Package smeargle is unavailable. Is the package name misspelled?
--> installing package: unfill@better-defaults... [20/20]
Package unfill is unavailable. Is the package name misspelled?
```

All the preselected layers appeared to install successfully on first run, which was weird.

**Comment by kivikakk** [comment]
Yep, checked out the 26.0.91 tag and all is well. Sorry for the noise!

**Comment by davidpasztor** [comment]
Does anyone still experience this issue? I'm running 27.0.50 and still have this. Moreover, whenever I try to add a layer to my `.spacemacs` file, then reload it using `SPC f e R`, I get this error:
>Wrote /Users/david/.spacemacs
run-hooks: Cannot open load file: No such file or directory, org-download

**Comment by Volland** [comment]
@davidpasztor I just switch to develop branch and it is solve the problem for me

**Comment by davidpasztor** [comment]
@Volland that solved the issue for me as well, thanks!
