### ISSUE TITLE
After uncommenting (and therefore activating) the org layer, an error showed up saying "Error (use-package): org-projectile/:config: Symbol's function definition is void: org-projectile:per-repo"

### ISSUE THREAD

**Issue by yw5aj** [syl20bnr/spacemacs#10565]
#### Description :octocat:
After uncommenting (and therefore activating) the org layer, an error showed up saying "Error (use-package): org-projectile/:config: Symbol's function definition is void: org-projectile:per-repo"

#### Reproduction guide :beetle:
- Uncomment the org layer in the ~/.spacemacs
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
After uncommenting (and therefore activating) the org layer, an error showed up saying "Error (use-package): org-projectile/:config: Symbol's function definition is void: org-projectile:per-repo"

*Expected behaviour:* :heart: :smile:
Start the spacemacs with all packages installed successfully and no errors.

#### System Info :computer:
- OS: Windows Subsystem for Linux - Ubuntu 16.04 
- Emacs: 24.5.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: org
```elisp
(helm emacs-lisp git org python)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by yw5aj** [comment]
And - the same error repeats for the Windows version of emacs.

Error message (the same):
"Error (use-package): org-projectile/:config: Symbol’s function definition is void: org-projectile:per-repo"

#### System Info :computer:
- OS: Windows 10 64 bit
- Emacs: 24.5.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: org
```elisp
(helm emacs-lisp git org python)
```

**Comment by yw5aj** [comment]
Seems similar to this one

https://github.com/syl20bnr/spacemacs/issues/9940

**Comment by al3xandru** [comment]
Seeing this too.  Same setup but on macOS.

**Comment by frankjonen** [comment]
Same here. OS: `macOS 10.13.4`

**Comment by Emantor** [comment]
You'll want 6063466231ce5e209aacd2de612e53390a25c442 from the develop branch.

**Comment by frankjonen** [comment]
Which file in there? `funcs.el`?

**Comment by sambooo** [comment]
I find this change paints over the error nicely if you don't expect to need `org-projectile`:

```diff
diff --git a/layers/+emacs/org/packages.el b/layers/+emacs/org/packages.el
index d6fad0ec..ba9c5137 100644
--- a/layers/+emacs/org/packages.el
+++ b/layers/+emacs/org/packages.el
@@ -27,7 +27,7 @@
     org-mime
     org-pomodoro
     org-present
-    (org-projectile :toggle (configuration-layer/package-usedp 'projectile))
+    ;; (org-projectile :toggle (configuration-layer/package-usedp 'projectile))
     (ox-twbs :toggle org-enable-bootstrap-support)
     ;; use a for of ox-gfm to fix index generation
     (ox-gfm :location (recipe :fetcher github :repo "syl20bnr/ox-gfm")
```

**Comment by pzskc383** [comment]
just cherry-picked 6063466231ce5e209aacd2de612e53390a25c442 onto master, bug is gone, works fine.

**Comment by FlorianFranzen** [comment]
@syl20bnr This is a duplicate of #10434!
