### ISSUE TITLE
Disabling flycheck automatic error pop-up

### ISSUE THREAD

**Issue by guillaumecherel** [syl20bnr/spacemacs#10563]
I would like to prevent error messages from poping-up when using flycheck. I would rather type `SPC e l` to see the errors when I need it. I have found that I can disable flycheck-pos-tip by adding it to the `dotspacemac-excluded-packages`, but then the errors still pop-up in a sort of pop-up buffer at the bottom of the window. Is it possible to disable this too?

**Comment by CeleritasCelery** [comment]
You should ask this upstream at flycheck.
