### ISSUE TITLE
Is there a way to add project corresponding layout in one step?

### ISSUE THREAD

**Issue by LukeXuan** [syl20bnr/spacemacs#10577]
Currently, every time I clone/create a project, I need to `SPC f f` to open the folder so that the path appears in choice of project layouts, and then `SPC p l` and choose the files. This process seems extremely tedious.

I expect there is someway to perform things like `projectile-add-known-project` and immediately create a layout for that project. Is it possible to add the feature or there already exist one that I'm not aware of?

**Comment by CeleritasCelery** [comment]
You can use the save an restore mechanism to save your project layouts then open them again when reopen Spacemacs.

**Comment by LukeXuan** [comment]
I'm already using it. What I'm referencing to is a brand new project that none of its information has appeared in the spacemacs ever before.

**Comment by Miciah** [comment]
I believe https://github.com/syl20bnr/spacemacs/pull/5959 implements the requested functionality.
