### ISSUE TITLE
Weird issue in org-capture with evilify

### ISSUE THREAD

**Issue by dschrempf** [syl20bnr/spacemacs#10579]
When I enter an `org-capture` buffer (independent of the template) and I immediately type `,` I do not see shortcuts such as `, a` for `org-capture-kill` or `, c` for `org-capture-finalize`. Only, when pressing escape or entering and exiting insert mode, these shortcuts show up. It looks like the hooks setting up the shortcuts are called too late. Do you have an idea why this could be? Does this also affect you, or is it something in my setup? Thanks.

**Comment by CeleritasCelery** [comment]
works fine for me. See https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report

**Comment by dschrempf** [comment]
Hm, I didn't want to go through all the hazzle before.

#### Description
The keybindings introduced in the `package.el` of the `org` layer are not available in `org-capture` mode before pressing `ESC` or entering and exiting insert mode.

The bindings are:

     ;; Follow the confirm and abort conventions
     (with-eval-after-load 'org-capture
       (spacemacs/set-leader-keys-for-minor-mode 'org-capture-mode
         dotspacemacs-major-mode-leader-key 'org-capture-finalize
         "a" 'org-capture-kill
         "c" 'org-capture-finalize
         "k" 'org-capture-kill
         "r" 'org-capture-refile))

They are saved in the keymap `spacemacs-org-capture-mode-map`.

#### Reproduction guide
- start Emacs
- enter Org Capture buffer
- press `,`
- keys are not showing up
- press `C-g` to go back to the capture buffer
- press `ESC`
- keys mentioned above are showing up

Keys are expected to show up right away.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658cd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults git
                 (gtags :variables gtags-enable-by-default nil)
                 helm ibuffer neotree ranger shell spell-checking semantic spacemacs-layouts version-control
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
                 emacs-lisp ess haskell html javascript latex markdown python shell-scripts vimscript yaml erc twitter mu4e org syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by CeleritasCelery** [comment]
This should fix it. This is technically considered a "feature" because it allows you to use `, ,` to finalize your capture. That is consistent with other keybindings in modes like `magit` and `org-src`

```lisp
(with-eval-after-load 'org-capture
  (spacemacs/set-leader-keys-for-minor-mode 'org-capture-mode
    dotspacemacs-major-mode-leader-key nil))
```

**Comment by dschrempf** [comment]
Hi,

that is interesting, thank you. And you are right `, ,` is very intuitive.

I am wondering why there is no way to make `, ,` work and still apply the key map immediately. Could you please guide me a little in the direction, as to why this delayed keymap issue is necessary so that I can understand?

Thank you,
Dominik

**Comment by CeleritasCelery** [comment]
So this change is only on develop and I am on master, so I may be missing something, but it looks like the only org keybindings that are overridden are `a`, `c`, `k`, `r`, and `,`.  Which means that if you wanted to restore all of them except for `,` you could just bind the others too `nil` as I did with `dotspacemacs-major-mode-leader-key` in my example, but leave `dotspacemacs-major-mode-leader-key` untouched.
