### ISSUE TITLE
Can't use doom-solarized-light theme?

### ISSUE THREAD

**Issue by FirstLoveLife** [syl20bnr/spacemacs#10570]
I have followed this article: https://github.com/syl20bnr/spacemacs-elpa-mirror/blob/master/stable-melpa/doom-themes-readme.txt

and add 
```
  (require 'doom-themes)

  ;; Global settings (defaults)
  (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
        doom-themes-enable-italic t) ; if nil, italics is universally disabled

  ;; Load the theme (doom-one, doom-molokai, etc); keep in mind that each
  ;; theme may have their own settings.
  (load-theme 'doom-one t)

  ;; Enable flashing mode-line on errors
  (doom-themes-visual-bell-config)

  ;; Enable custom neotree theme
  (doom-themes-neotree-config)  ; all-the-icons fonts must be installed!
```

to `dotspacemacs/user-config ()`

but still get errors: 
```
Warnings:
                                              - An error occurred while applying the theme "doom-solarized-light", fallback on
                                                theme "spacemacs-dark". Error was: (error Package ‘doom-solarized-light-theme-’
                                                is unavailable)      
                                              - Please check the value of "dotspacemacs-themes" in your dotfile or open an issue
                                                so we can add support for the theme "doom-solarized-light".      
```                                  

Additionally, `zonokai-red`, which is list in https://themegallery.robdor.com/, also gets the same error and warning.

**Comment by NightMachinary** [comment]
Have you added the package to `...-additional-packages`?

**Comment by FirstLoveLife** [comment]
@NightMachinary  I have, but cannot solve problems: 
```
dotspacemacs-additional-packages '(
                                      doom-themes
 }
```

**Comment by jsoo1** [comment]
There is a dotspacemacs configuration variable specifically for themes. Could you please use that and don’t do any configuration in `user-config` or `user-init` and tell me what happens?

**Comment by FirstLoveLife** [comment]
I also meet this problem @jsoo1 add nothing `user-config` or `user-init` also have the same warning.

**Comment by jsoo1** [comment]
Make sure `doom-themes` is in `additional-packages`, then specify the theme you want in the variable  `dotspacemacs-themes` In th `dotspacemacs/init` function.  No other configuration should be required.
