### ISSUE TITLE
vagrant-tramp-term fails on Windows

### ISSUE THREAD

**Issue by karlmccarron** [syl20bnr/spacemacs#10575]
#### Description :octocat:
vagrant-tramp-term fails on Windows, throws (wrong-type-argument arrayp nil)
#### Reproduction guide :beetle:
- Start Emacs
- Call vagrant-tramp-term (SPC a V t)

*Observed behaviour:* :eyes: :broken_heart:
(wrong-type-argument arrayp nil) message when function called

*Expected behaviour:* :heart: :smile:
Use vagrant-tramp-term normally

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(windows-scripts emacs-lisp c-c++ html javascript python ruby rust latex auto-completion vagrant docker helm nginx git markdown slack bibtex org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("[^-0-9a-zA-Z_./\n]" "\\\\\\&" nil)
  shell-quote-argument(nil)
  byte-code("\302\303\304\206�	!\305P!!\207" [load-file-name buffer-file-name shell-quote-argument executable-find file-name-directory "bin/vagrant-tramp-ssh"] 4)
  (defconst vagrant-tramp-ssh (byte-code "\302\303\304\206�	!\305P!!\207" [load-file-name buffer-file-name shell-quote-argument executable-find file-name-directory "bin/vagrant-tramp-ssh"] 4) ("c:/Users/Karl/.emacs.d/elpa/develop/vagrant-tramp-20160427.1632/vagrant-tramp.elc" . 816))
  autoload-do-load((autoload "vagrant-tramp" "SSH into BOX-NAME using an `ansi-term'.\n\n(fn BOX-NAME)" t nil) vagrant-tramp-term)
  command-execute(vagrant-tramp-term)

```

**Comment by CeleritasCelery** [comment]
Can you reproduce with stock Emacs and `vagrant-tramp-term`?

**Comment by karlmccarron** [comment]
It seems I can reproduce with stock Emacs and vagrant-tramp-term, so this isn’t a spacemacs issue as it seems to be a problem with vagrant-tramp. Sorry for the trouble.

**Comment by Miciah** [comment]
Upstream issue: https://github.com/dougm/vagrant-tramp/issues/30

Looks like the problem begins with this definition in the upstream package:
```emacs-lisp
(defconst vagrant-tramp-ssh
  (shell-quote-argument
   (executable-find (concat (file-name-directory
                             (or load-file-name
                                 buffer-file-name))
                            "bin/vagrant-tramp-ssh")))
  "TRAMP login helper script.")
```
That code probably should be replaced with something simpler, either the following:
```emacs-lisp
(defconst vagrant-tramp-ssh
  (concat (file-name-directory (or load-file-name buffer-file-name))
          "bin/vagrant-tramp-ssh"))
  "TRAMP login helper script.")
```
or the following:
```emacs-lisp
(defconst vagrant-tramp-ssh
  (executable-find "vagrant-tramp-ssh")
  "TRAMP login helper script.")
```
It looks like people got past that error on the upstream issue but ran into some other vague problem whereupon progress on the issue stalled.  @karlmccarron, maybe you (or someone else trying to use vagrant-tramp on an MS Windows system) can push it further along.
