### ISSUE TITLE
"Invalid hash table rehash size" in X mode

### ISSUE THREAD

**Issue by BenMoon** [syl20bnr/spacemacs#10586]
#### Description :octocat:
Emacs doesn't start in X mode with the below given error. Using the option "-nw" it starts though. Emacs also starts without spacemas in X, so I think this is a spacemacs problem...

#### Reproduction guide :beetle:
- Start Emacs with X mode

*Observed behaviour:* :eyes: :broken_heart:
- Emacs doesn't start with spacemacs but without in GUI mode
- It also isn't related to my spacemacs config, deleting it results with the same problem

### System Info :computer:                                                                
- OS: Debian/unstable                                                        
- Emacs: 25.2.2                                                                            
- Spacemacs: 0.200.13                                                                      
- Spacemacs branch: master (rev. c7a103a7)                                                 
- Graphic display: nil                                                                     
- Distribution: spacemacs                                                                  
- Editing style: vim                                                                       
- Completion: helm                                                                         
- Layers:                                                                                  
```elisp                                                                                   
(csv html helm auto-completion better-defaults emacs-lisp python ipython-notebook git org \
plantuml                                                                                   
     (shell :variables shell-default-height 30 shell-default-position 'bottom)             
     (semantic :disabled-for emacs-lisp)                                                   
     (spell-checking :variables spell-checking-enable-auto-dictionary t enable-flyspell-au\
to-completion t flyspell-auto-correct-binding                                              
                     (kbd "<S-f12>"))                                                      
     syntax-checking ranger)                                                               
```                                                                                        
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSE\
TTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCRO\
LL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (error "Invalid hash table rehash size" 1.0)
  read(#<buffer  *load*-704652>)
  eval-buffer(#<buffer  *load*-704652> nil "/usr/share/emacs/25.2/lisp/finder-inf.el" nil t)  ; Reading at buffer position 39098
  load-with-code-conversion("/usr/share/emacs/25.2/lisp/finder-inf.el" "/usr/share/emacs/25.2/lisp/finder-inf.el" t t)
  require(finder-inf nil t)
  package--build-compatibility-table()
  package-initialize(noactivate)
  (if package--initialized nil (setq configuration-layer-rollback-directory (configuration-layer/elpa-directory configuration-layer-rollback-directory)) (setq package-user-dir (configuration-layer/elpa-directory package-user-dir)) (setq package-archives (configuration-layer//resolve-package-archives configuration-layer--elpa-archives)) (setq package-enable-at-startup nil) (package-initialize (quote noactivate)))
  configuration-layer/initialize()
  spacemacs/init()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/gaston/.emacs.d/init.el" nil t)  ; Reading at buffer position 1264
  load-with-code-conversion("/home/gaston/.emacs.d/init.el" "/home/gaston/.emacs.d/init.el" t t)
  load("/home/gaston/.emacs.d/init" t t)
  #[0 "\205\266
```

**Comment by kepi** [comment]
After apt-get upgrade today everything is working again. Issue can be closed probably.

Still not sure what package caused this problem, but here is list of all packages which was upgraded on my system when things breaks and when it got fixed:

- fontconfig
- fontconfig-config
- gcc-8-base
- gvfs
- gvfs-daemons
- gvfs-libs
- libatomic1
- libcc1-0
- libfontconfig1
- libfontconfig1-dev
- libgcc1
- libgomp1
- libgtkglext1
- libitm1
- liblsan0
- libmpx2
- libquadmath0
- libstdc++6
- libtsan0
- linux-headers-liquorix-amd64
- linux-image-liquorix-amd64
- python-click
- python-gi
- python-gi-cairo
- python-gobject
- python-pyqt5
- python-pyqt5.qtsvg
- python-pyqt5.qtwebkit
- python3-gi
- python3-gi-cairo
- python3-pyqt5
- python3-pyqt5.qtopengl
- python3-pyqt5.qtquick
- python3-pyqt5.qtsql
- python3-pyqt5.qtwebengine
- python3-pyqt5.qtwebchannel
- python3-pyqt5.qtwebkit

Maybe libstdc or libquadmath?

**Comment by BenMoon** [comment]
Also solved here :)
Cheers
Ben
