### ISSUE TITLE
Font issues after installation

### ISSUE THREAD

**Issue by andreyorst** [syl20bnr/spacemacs#10584]
I'm coming from vim world, and decided to try out your emacs distribution. But I have some problems with fonts. There were no warnings about fonts, so I assume this as bug.

#### Reproduction guide :beetle:
- clone repo as proposed in the instructions
- open the emacs, wait till it installs all plugins and stuff
- Powerline broken, and font in table owerlaps vertically

![image](https://user-images.githubusercontent.com/19470159/38689215-af892992-3e83-11e8-8a2e-65c452388268.png)
Look at the vertical border of `Quick Help`. You can notice that there are dots. This is font overlap.

Also Powerline is wrong sized.

My system font confuguration doesn't cause any problems in other programs.

#### System Info :computer:
- OS: Arch Linux
- DE: KDE Plasma 5
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by CeleritasCelery** [comment]
in your `.spacemacs` file you can set the font and `powerline-scale` which should fix your issue. Find this section under `dotspacemacs/init`

```lisp
   dotspacemacs-default-font '("Source Code Pro"
                               :size 13
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
```

If you don't have Source Code Pro installed you will need to choose a different font.

**Comment by andreyorst** [comment]
I have Source Code Pro. I'll try it. Thanks!
