### ISSUE TITLE
[Question] Where I need to set indent tabs mode to t in python

### ISSUE THREAD

**Issue by rafaelleru** [syl20bnr/spacemacs#10580]
I tryed both with a hook, defining globally and editing the packages.el file of the layer bu I always have spaces instead of tabs, any help?

**Comment by CeleritasCelery** [comment]
https://stackoverflow.com/questions/6679625/how-to-make-emacs-python-mode-generate-tabs-for-indent

**Comment by rafaelleru** [comment]
Ok, I was missing the lambda, thanks :D

**Comment by digizeph** [comment]
@rafaelleru please close the issue if it has been resolved 😄
