### ISSUE TITLE
Warning (bytecomp): reference to free variable ‘smartparens-strict-mode’

### ISSUE THREAD

**Issue by lsytj0413** [syl20bnr/spacemacs#10582]
#### Description :octocat:
Warning (bytecomp): reference to free variable ‘smartparens-strict-mode’

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
```
Warning (bytecomp): reference to free variable ‘smartparens-strict-mode’
```

shows in Compile-Log buffer.

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.50.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((ivy :variables ivy-extra-directories nil)
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for org)
 (better-defaults :variables better-defaults-move-to-end-of-code-first t)
 emacs-lisp git markdown org
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (python :variables python-sort-imports-on-save t)
 (go :variables go-tab-width 4 go-use-gometalinter t gofmt-command "goimports")
 protobuf ranger gtags ibuffer
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 900)
 docker sql protobuf
 (syntax-checking :variables syntax-checking-enable-by-default t syntax-checking-enable-tooltips t)
 liter ycmd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
```

**Comment by NightMachinary** [comment]
I have this warning plastered over my .spacemacs (via flychecker). I think it is not important.

**Comment by jonbash** [comment]
I also have had this issue, and it leads to various packages not loading on startup, and hence Emacs being essentially unusable. Haven't been able to discover anything else. It only happens with emacs-mac; emacs-plus works fine.

**Comment by nikital** [comment]
Fixed in develop, we can close this
