### ISSUE TITLE
Insecure cert warning

### ISSUE THREAD

**Issue by revmischa** [syl20bnr/spacemacs#10587]
I have a brand new Emacs and spacemacs install - any idea why I see this or what I can do about it?

<img width="655" alt="screen shot 2018-04-13 at 19 01 46" src="https://user-images.githubusercontent.com/245131/38748097-51191c1c-3f4d-11e8-98b1-f3cdb9f94fd5.png">

**Comment by alexander-lazarov** [comment]
Just to confirm - I'm getting a similar error when installing from scratch.

<img width="772" alt="screen shot 2018-04-23 at 0 08 49" src="https://user-images.githubusercontent.com/5956709/39099926-d26cdeb8-468a-11e8-826f-0eb04e81ddd2.png">

The warning message from the screenshot appears for a split second and then disappears. I managed to select `Always` (by pressing `a`) and after restarting Emacs the installation went fine. Hope this helps.

I'm using:
- latest MacOS (10.13.4)
- Emacs from here - https://emacsformacosx.com/

**Comment by costa** [comment]
+1
