### ISSUE TITLE
Can't quit when dotspacemacs-auto-resume-layouts is set

### ISSUE THREAD

**Issue by revmischa** [syl20bnr/spacemacs#10589]
If I set `dotspacemacs-auto-resume-layouts t`

Then when I exit spacemacs, it won't actually exit. It just stays open. I have to `kill` it or force quit it.

**Comment by revmischa** [comment]
Backtrace just says:
`Debugger entered--Lisp error: (quit)`

**Comment by robbyoconnor** [comment]
Is that all that is shown?

**Comment by robbyoconnor** [comment]
`SPC t D` 

Then restart again -- and do `SPC h I`
