### ISSUE TITLE
package counsel not initialized in layer common-lisp

### ISSUE THREAD

**Issue by a-schaefers** [syl20bnr/spacemacs#10591]
#### Description :octocat:
package counsel not initialized in layer common-lisp

#### Reproduction guide :beetle:
- Start Emacs
- on develop && not using spacelpa

*Observed behaviour:* :eyes: :broken_heart:
- Warning displays on start.
" package counsel not initialized in layer common-lisp, you may consider removing this package from the package list or use the :toggle keyword instead of a `when' form."

*Expected behaviour:* :heart: :smile:
Expecting layer to 'just work' ;-)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm org auto-completion syntax-checking neotree git
      (version-control :variables version-control-global-margin t version-control-diff-tool 'diff-hl)
      gtags
      (shell :variables shell-default-shell 'eshell shell-default-position 'full)
      shell-scripts emacs-lisp common-lisp search-engine gnus
      (erc :variables erc-server-list
           '(("znc1.efers.org" :port "6697" :ssl t)
             ("znc2.efers.org" :port "6697" :ssl t)
             ("znc3.efers.org" :port "6697" :ssl t))
           erc-hide-list
           '("JOIN" "PART" "QUIT")
           erc-prompt-for-nickserv-password 'nil))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB GTK3 X11 THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by vv111y** [comment]
same, my info,
```
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c9e364721)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```

**Comment by syl20bnr** [comment]
Should be fixed in develop
