### ISSUE TITLE
In haskell repl hitting 'G' should take to the first input position

### ISSUE THREAD

**Issue by EDmitry** [syl20bnr/spacemacs#1059]
Right now hitting 'G' takes you to the first symbol of the last line, which is lambda:

```
λ>
^ cursor is here
    ^ should be here though
```

Compared to behavior in for example ERC this is not consistent. (In ERC it does the right thing). Not sure if this is something spacemacs should handle or haskell-mode.

Also similar bug: hitting `dd` doesn't clear the command line, it says "text read-only". This happens because the prompt is indeed read-only, but it should clear everything but prompt. With ERC works correctly as well.

**Comment by syl20bnr** [comment]
This would be a great improvements indeed. I have to write the conventions about the terminal. You can throw all your ideas in this issue.

**Comment by TheBB** [comment]
This is a bother in a number of terminal-like modes. It's likely an upstream issue at heart, but... Probably we can't override `G`, but how about a `,G` binding that takes you to the end of the last nonempty line?

**Comment by StreakyCobra** [comment]
@TheBB Is there a way to make a generic function working with all of those modes, or do we have to adapt the code for each one, in which case it should be better to report them upstream, no?

**Comment by TheBB** [comment]
I think so. If you go to an IELM buffer, for example, you'll see that there's a 'fake' linebreak between the prompt and the point after prompt. It's done with some kind of text property. This is how it should be done. Some REPLs don't follow this custom, and I believe they should.

**Comment by StreakyCobra** [comment]
For the record:

- [ ] Listing all REPL-like / terminal-like buffers in spacemacs
- [ ] Trying `G` in all of them
- [ ] Opening an issue upstream for all non `G`-compliant modes.
