### ISSUE TITLE
Weird symbols from Message checker `^[[0m^[[0m`

### ISSUE THREAD

**Issue by well1791** [syl20bnr/spacemacs#10596]
#### Description :octocat:
Weird symbols on checker warnings

#### Reproduction guide :beetle:
- Start Emacs
- Write some silly code for hlint
- Wait for hlint to suggest an improvement
- run `SPC-e-l`

*Observed behaviour:* :eyes: :broken_heart:
It return checker descriptions like `[Om[Om` (which doesn't make sense)

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((haskell :variables haskell-enable-hindent-style "johan-tibell" haskell-process-type 'stack-ghci)
 javascript html helm auto-completion better-defaults emacs-lisp markdown syntax-checking themes-megapack
 (version-control :variables version-control-global-margin t version-control-diff-tool 'git-gutter version-control-diff-side 'left))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
_No idea how to backtrace_

#### Screenshots 🖼 

<img width="958" alt="screen shot 2018-04-16 at 10 19 43 am" src="https://user-images.githubusercontent.com/6817008/38818233-e239d81c-415f-11e8-9a57-f1b30486e009.png">

**Comment by CeleritasCelery** [comment]
You should report this upstream at flycheck.

**Comment by well1791** [comment]
Thanks! I'll do that
