### ISSUE TITLE
Can't install any additional packages. Getting "package is unavailable. Is the package name misspelled?"

### ISSUE THREAD

**Issue by syvanpera** [syl20bnr/spacemacs#10598]
I had spacemacs working perfectly fine maybe a month or two ago, but now that I did a fresh install of spacemacs, I keep getting this error no matter what packages I try to install (in additional-packages or by adding a layer to dotspacemacs-configuration-layers (for example git layer).
My package-archives only seem to contain "gnu" and nothing else. 
(configuration-layer//resolve-package-archives configuration-layer--elpa-archives) returns "melpa", "gnu" and "org", though.

**Comment by syvanpera** [comment]
I checked out the develop branch. Looks like that one works.

**Comment by NightMachinary** [comment]
@syvanpera The develop branch is on Spacelpa I believe. Is your connection ok? Try using a VPN.

**Comment by syvanpera** [comment]
No problems with the connection. Just couldn't get it to work on a fresh install. I changed to develop branch and now everything works just fine. But I suppose it would be good to check whether a completely clean install of the master branch still works as it's supposed to

**Comment by Voleking** [comment]
Same issue here.

**Comment by npassaro** [comment]
I am running **emacs 27** behind a corporate proxy starting it from the command line with the proxy environment variables set. 

On `.spacemacs`, these configurations have no effect:
```lisp
(defun dotspacemacs/init ()
  (setq configuration-layer--elpa-archives
        '(("melpa" . "https://elpa.zilongshanren.com/melpa/")
          ("org" . "https://elpa.zilongshanren.com/org/")
          ("gnu" . "https://elpa.zilongshanren.com/gnu/")))

```

I only got the layer `typescript`, that only exists on Melpa, installed by putting the following on `init.el`:

```lisp
(add-to-list 'package-archives
    '("melpa-stable" . "https://stable.melpa.org/packages/") t)
```
After `(spacemacs/init)`.

**Comment by shishirsharma** [comment]
Deleting `.emacs.d/elpa` and restarting spacemacs works.

**Comment by Naomarik** [comment]
@npassaro's solution works. Better than deleting the elpa directory and waiting 10 minutes for it to redownload everything to install a single new package.

**Comment by shishirsharma** [comment]
v300 should fix all of this.

**Comment by jorgemorais** [comment]
I hit this problem just after upgrading Emacs to git master (27.0.50).  Deleting `.emacs.d/elpa` and restarting Spacemacs did not work.  I am behind a corporate proxy, but adding proxy configuration (`url-proxy-services`) to `.emacs.d/init.el` or `.spacemacs` did not work either.

What did work for me was setting `dotspacemacs-elpa-https` to nil in `.spacemacs`

**Comment by SimonAM** [comment]
I tried changing the package-archives as suggested, removed the elpa-folder multiple times and experimented with --insecure settings. What finally made the difference for me was:

1. Moving the .spacemacs-file into a .spacemacs.d-folder and renaming it init.el
2. Removing elpa-folder in .emacs.d
3. Running `./emacs --insecure`

I was running it from msys2 on windows 8.

**Comment by LucaMarconato** [comment]
I had the same problem and the @npassaro solution worked for me (I also deleted the elpa folder, but deleting the folder alone, without the modification cited have not worked)

**Comment by duianto** [comment]
I just tried running `sudo emacs-snapshot` in `Ubuntu 18.04.1` (as a virtualbox client, with `Windows 10 1803` as host) and got the `package is unavailable. Is the package name misspelled?` message, probably for all packages.

When I searched for the error message and found this page, I saw [SimonAM's comment](https://github.com/syl20bnr/spacemacs/issues/10598#issuecomment-433622580) about using 
`--insecure`. I didn't move or rename any folders, but instead just ran `sudo emacs-snapshot --insecure` and it worked. All packages were installed without any issues.

This might not be related, but I hadn't seen it before. When Emacs first started it showed something about let's encrypt.

I found a similar example of what it looked like, except that I hadn't specified that stable.melpa.org should be used, so it probably just said `melpa.org`.
```
Certificate information
Issued by:          Let's Encrypt Authority X3
Issued to:          CN=stable.melpa.org
Hostname:           stable.melpa.org
Public key:         RSA, signature: RSA-SHA256
Protocol:           TLS1.2, key: ECDHE-RSA, cipher: AES-128-GCM, mac: AEAD
Security level:     Medium
Valid:              From 2016-09-04 to 2016-12-03
```

source: https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-09/msg00272.html

After the packages had been installed, then the let's encrypt message didn't appear again, either with or without starting `emacs-snapshot` with `--insecure`.

**Comment by onemargaro** [comment]
> I hit this problem just after upgrading Emacs to git master (27.0.50). Deleting `.emacs.d/elpa` and restarting Spacemacs did not work. I am behind a corporate proxy, but adding proxy configuration (`url-proxy-services`) to `.emacs.d/init.el` or `.spacemacs` did not work either.
> 
> What did work for me was setting `dotspacemacs-elpa-https` to nil in `.spacemacs`

This works for me.
