### ISSUE TITLE
Suspicious state from syntax checker haskell-stack-ghc

### ISSUE THREAD

**Issue by well1791** [syl20bnr/spacemacs#10593]
#### Description :octocat:
Error/Warning messages every time I modify a haskell file

#### Reproduction guide :beetle:
- Start Emacs
- Open a haskell project
- Search a haskell file
- Modify the file

*Observed behaviour:* :eyes: :broken_heart:
\*Messages\* buffer is filled with this error for every single change in the file
```
Suspicious state from syntax checker haskell-stack-ghc: Flycheck checker haskell-stack-ghc returned non-zero exit code 1, but its output contained no errors: Usage: stack [--help] [--version] [--numeric-version] [--hpack-numeric-version]
             [--docker*] [--nix*] ([--verbosity VERBOSITY] | [-v|--verbose] |
             [--silent]) [--[no-]time-in-log] [--stack-root STACK-ROOT]
             [--work-dir WORK-DIR] [--[no-]system-ghc] [--[no-]install-ghc]
             [--arch ARCH] [--ghc-variant VARIANT] [--ghc-build BUILD]
             [-j|--jobs JOBS] [--extra-include-dirs DIR] [--extra-lib-dirs DIR]
             [--with-gcc PATH-TO-GCC] [--with-hpack HPACK]
             [--[no-]skip-ghc-check] [--[no-]skip-msys] [--local-bin-path DIR]
             [--[no-]modify-code-page] [--[no-]allow-different-user]
             [--[no-]dump-logs] [--resolver RESOLVER] [--compiler COMPILER]
             [--[no-]terminal] [--color WHEN] [--terminal-width INT]
             [--stack-yaml STACK-YAML] COMMAND|FILE
<command line>: cannot satisfy -package aeson-qq
    (use -v for more information)

Try installing a more recent version of haskell-stack-ghc, and please open a bug report if the issue persists in the latest release.  Thanks!
```

*Expected behaviour:* :heart: :smile:
Either
- Disable the errors warning pop up for every time I modify the file.
- Fix the issue regarding flycheck-haskell (if possible)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((haskell :variables haskell-enable-hindent-style "johan-tibell")
 javascript html helm auto-completion better-defaults emacs-lisp markdown syntax-checking themes-megapack
 (version-control :variables version-control-global-margin t version-control-diff-tool 'git-gutter version-control-diff-side 'left))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

- ghc: 8.2.2
- stack: 1.6.5
- yesod: 1.6.0

#### Backtrace :paw_prints:
_No idea how to backtrace_

#### Extra details :pensive:
I think this issue is the result of a couple of other issues.

1. The PATH variable wasn't loaded at first, so I used 
   ```elisp
   ;; add path
   (add-to-list 'exec-path "~/.local/bin/")
   ```
   However, that didn't loaded the `ghc` binary, because I use stack.
   So, I linked the binary from stack to the `~/.local/bin/` folder
   ```
   ln -s ~/.stack/programs/x86_64-linux/ghc-8.2.2/bin/ghc ~/.local/bin/ghc
   ```
   *Now, I'm not sure if that was right*

2. Following [this guide](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/haskell#the-project-root-directory-is-not-set-properly) I have now the error described above.

   But, before that I had an error saying:
  
   ```
   Suspicious state from syntax checker haskell-stack-ghc: Flycheck checker haskell-stack-ghc returned non-zero exit code 1, but its output contained no errors: <command line>: cannot satisfy -package criterion
       (use -v for more information)

   Try installing a more recent version of haskell-stack-ghc, and please open a bug report if the issue persists in the latest release.  Thanks!
   ```
  
   There was an [issue](https://github.com/syl20bnr/spacemacs/issues/7953) reported with the same behaviour but, the problem/solution is not clear.

Thanks in advance for any help. :pray:

**Comment by theophile-fl** [comment]
Any update on that problem @well1791?

**Comment by well1791** [comment]
Right now I don't remember what I did to make it work, sorry ): I think it was just a `git pull` that fixed it.

**Comment by theophile-fl** [comment]
hmm. Did you install GHC as a separate package, outside of stack?

**Comment by ThiagoLira** [comment]
I've reinstalled Stack, GHC, Cabal lots of timed and messed with paths and such and wasn't able to solve this :(
