### ISSUE TITLE
error "Undefined Color" "0xffffff"

### ISSUE THREAD

**Issue by anhdle14** [syl20bnr/spacemacs#10592]
#### Description :octocat:
error "Undefined Color" "0xffffff"

#### Reproduction guide :beetle:
- Start Emacs with a fresh install
- Using flags: --debug-init

*Observed behaviour:* :eyes: :broken_heart:
- Failed to start, try to uncomment and search for color but haven't find any thing relevent.

*Expected behaviour:* :heart: :smile:
- Normal first time setup behavior.

Linux ArchLinuxHPOMEN15-ce0xx 4.15.15-1-ARCH #1 SMP PREEMPT Sat Mar 31 23:59:25 UTC 2018 x86_64 GNU/Linux

OS: Arch Linux x86_64
Host: OMEN by HP Laptop 15-ce0xx
Kernel: 4.15.15-1-ARCH
Packages: 824
Shell: zsh 5.5
Resolution: 1920x1080
CPU: Intel i7-7700HQ (8) @ 3.800GHz
GPU: NVIDIA GeForce GTX 1060 Mobile 6GB
Memory: 1106MiB / 15991MiB

#### Backtrace :paw_prints:
```lisp
Debugger entered--Lisp error: (error "Undefined color" "#0xffffff")
  internal-set-lisp-face-attribute(cursor :background "#0xffffff" #<frame emacs@ArchLinuxHPOMEN15-ce0xx 0x111bc30>)
  set-face-attribute(cursor #<frame emacs@ArchLinuxHPOMEN15-ce0xx 0x111bc30> :background "#0xffffff")
  apply(set-face-attribute cursor #<frame emacs@ArchLinuxHPOMEN15-ce0xx 0x111bc30> (:background "#0xffffff"))
  face-spec-set-2(cursor #<frame emacs@ArchLinuxHPOMEN15-ce0xx 0x111bc30> (:background "#0xffffff"))
  face-spec-recalc(cursor #<frame emacs@ArchLinuxHPOMEN15-ce0xx 0x111bc30>)
  custom-theme-recalc-face(cursor)
  enable-theme(spacemacs-dark)
  #[(theme &optional no-confirm no-enable) "\306!\204
```

**Comment by anhdle14** [comment]
For the record, try with `emacs -nw` did resolve a success first time setup. But running only `emacs` won't work.

**Comment by Miciah** [comment]
What version of Emacs are using? Can you reproduce the problem using the [spacemacs-themes](https://github.com/nashamri/spacemacs-theme) package on plain Emacs?
