### ISSUE TITLE
Required feature 'let-alist' not provided

### ISSUE THREAD

**Issue by Casen** [syl20bnr/spacemacs#10608]
#### Description :octocat:
Trying to modify .spacemacs config always results in the following error:

Required feature 'let-alist' not provided

#### Reproduction guide :beetle:
- Start Emacs
- Add anything to layers
- SPC feR
- See error

*Observed behaviour:* :eyes: :broken_heart:
Error is always output at bottom of screen

*Expected behaviour:* :heart: :smile:
Error should not be output as let-alist is installed

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm git javascript typescript react themes-megapack
      (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB

#### Backtrace :paw_prints:
```
```

**Comment by mroh69** [comment]
what happens on develop branch?
