### ISSUE TITLE
Disable the tildes on homepage

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1060]
I think we should not let the tildes on Spacemacs home buffer. We don't edit it's not needed and without it the buffer look aesthetically better.

**Comment by CestDiego** [comment]
:+1:  This! Although being fair when you open vim it does show you the tildes (but we have made clear before that spacemacs is either vim nor emacs :P )

**Comment by syl20bnr** [comment]
That makes sense. Thank you!
