### ISSUE TITLE
Pytest fish error 

### ISSUE THREAD

**Issue by Alex-Keyes** [syl20bnr/spacemacs#10601]
#### Description :octocat:
I am having problems running pytest in a virtualenvironment I created with virtualfish, a wrapper for the virtualenv tool in python.
I cannot run pytest without an error regarding the formatting of the call to run the pytest command

#### Reproduction guide :beetle:
- Start Emacs
- activate a virtualenv created by virtualfish
- using pytest as the test runner, run a pytest from spacemacs

*Observed behaviour:* :eyes: :broken_heart:
```
-*- mode: compilation; default-directory: "~/Git/exercism-exercises/" -*-
Compilation started at Wed Apr 18 15:15:04

cd '/home/alex/Git/exercism-exercises/' && py.test -x -s ''/home/alex/Git/exercism-exercises/python/gigasecond/gigasecond.py::add_gigasecond''
fish: Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
cd '/home/alex/Git/exercism-exercises/' && py.test -x -s ''/home/alex/Git/exercism-exercises/python/gigasecond/gigasecond.py::add_gigasecond''
                                         ^


Compilation exited abnormally with code 127 at Wed Apr 18 15:15:05
```
*Expected behaviour:* :heart: :smile:
A nice pytest output

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown python helm emacs-lisp git org
          (python :variables python-test-runner 'pytest)
          syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by ExarKunFan** [comment]
You should edit format string in pytest config file like this and change && in template to **; and** expression:
(defcustom pytest-cmd-format-string "cd %s _**; and**_ %s %s %s"
  "Format string used to run the py.test command.")
 
File location is **~/.emacs.d/elpa/pytest-%something%**

And let me know if you don't have problems with running tests with virtualfish

**Comment by Alex-Keyes** [comment]
thanks for the help @ExarKunFan ,  I've stopped using spacemacs as my main editor, but I'd like to go through and see if I can fix this error anyway.  Maybe this weekend i'll get to it...

**Comment by ExarKunFan** [comment]
@Alex-Keyes Actually, i found easier way, just put this into init file:
```
(use-package pytest
  :init
  (progn
    (setq pytest-cmd-format-string "cd %s; and pipenv run %s %s %s"))
  :ensure t)
```
So, it can be used in any configuration, not only spacemacs.
