### ISSUE TITLE
Show org-pomodoro clock in modeline of all buffers and windows

### ISSUE THREAD

**Issue by hughwilliams94** [syl20bnr/spacemacs#10604]
I often use org-pomodoro whilst I am working in other windows and buffers and outside of emacs, when I switch away from the org buffer where I start the pomodoro the timer disappears. Is there any way to show the org-pomodoro timer in the modeline of inactive windows so that I can always see it (especially when outside emacs e.g. working in GIMP or Firefox)?

Edit: I also noticed that my system clock in also not shown when the emacs window is not active which is very inconvenient as I do not have any other clock on my desktop (no taskbar or systray).

**Comment by hughwilliams94** [comment]
I realise that I should have asked this in the spaceline repo which I have done now. [#192](https://github.com/TheBB/spaceline/issues/192)

**Comment by cmorgan** [comment]
@hughwilliams94 please close this
