### ISSUE TITLE
[DISCUSSION] Can't the project be licensed such that it remains open-source but use in commercial companies requires them to pay a small monthly fee per user?

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10607]
This would help the project immensely, and might even benefit those paying companies in the long run. What are the obstacles in this path?

**Comment by sdwolfz** [comment]
The project is licensed under GPL because emacs itself (and all it's code) is GPL, and any code that calls GPL code becomes GPL, whether it likes it or not. 

This is my understanding of how GLP works. So you can not actually change the license.

**Comment by Immortalin** [comment]
Patreon and sponsorship would be good models to look into for more funding. A full-time team maintaining spacemacs would be the best.

**Comment by henriquenj** [comment]
Spacemacs can charge a fee for an user (or a company) to get a copy of spacemacs. However this user has the freedom to distribute further copies for free if he/she wishes so, this freedom is _required_ by the terms of the GPL. This does not change if it's a company using it commercially or not.

For me charging a fee would make companies simply loose all interest in the project, it would be a barrier for users to start using spacemacs, they would migrate to other projects. I think patreon is a much better approach.
