### ISSUE TITLE
Command send me to evil state, when in holy mode

### ISSUE THREAD

**Issue by didibus** [syl20bnr/spacemacs#10615]
Some commands, like: `M-m k w` will put me in evil command mode, even though I'm configured to use Holy mode. I need to press Esc afterwards to get back to normal Holy mode.

Is this the intended behavior?

The bind calls evil-lisp-state-wrap. But there is also lisp-state-wrap which does not leave me in that mode.

Personally, I'd rather none of the commands pulled me out of Holy mode. So I'm not sure if this is a bug, or on purpose.

Thanks.

**Comment by smile13241324** [comment]
@didibus I had a look into `evil-lisp-state.el` as it looks like this mode has been created to automatically get into `evil-lisp-state` when certain commands are used. This state has to be
left with `ESC` to reenter the usual "evil" or "holy" bindings. As far as I can see this has been done out of purpose and is not a bug. 

As a holy-mode user I think the preferred solution would be not to use the bindings under `SPC k` but use the emacs specific ones for lisp interactions.

Maybe one could change the bindings for `SPC k` when holy mode is activated to use the classic emacs alternatives but I am not sure whether there are alternatives for all the commands `evil-lisp-state` declares.
