### ISSUE TITLE
Python REPL slow with single quotation marks

### ISSUE THREAD

**Issue by jsevo** [syl20bnr/spacemacs#10618]
Hey, I have a question re: python repl buffer. I am working within an inferior python process (i usually have a script in one emacs window and the repl in another). After a while, when entering something in the repl that contains single quotation marks (e.g. writing a pandas data frame to csv, like : df.to_csv('filename.csv'), the repl is lagging A LOT after I type the first quotation mark (it seems to try and auto complete with some nonsense). Has anyone got any advice?

UPDATE: If I try and simply type single quotation marks, the REPL hangs, and suggests something like:
`.join(__PYTHON_EL_get_completions('''''')))`
Maybe I am doing something wrong with my code completion set up?

**Comment by Miciah** [comment]
Is this the same issue as #10666?

**Comment by jsevo** [comment]
I got the exact same problem. Sometimes `spacemacs/comint-clear-buffer` that clears the print history helps a bit. But it usually becomes unusable and i have to restart the python process. It's a major issue and I have thus far failed to solve it, or to usefully search for a solution.
