### ISSUE TITLE
Clojure layer's fancify symbols messes up indentation

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10620]
By changing, say, `partial` to `P`, the length changes, and it causes the indentation to look different if this mode is active.

**Comment by eggsyntax** [comment]
I'm experiencing the same thing, and if I format the buffer, it results in bad indentation in the file.

I might be imagining it, but I would have sworn that this used to work correctly, where you could fancify symbols, it would look right in the editor, but then file indentation would be kept correct.

**Comment by eggsyntax** [comment]
Still true, unfortunately, with both `clojure-enable-fancify-symbols` and `global-prettify-symbols-mode`. I've stopped using them both even though I love them, because other people have to look at my code and it's not fair to mess up the indentation that they see ☹️

**Comment by NightMachinary** [comment]
@eggsyntax 

Try Julia. It supports Unicode aliases natively. Its macro system also is the most intuitive one I have ever seen.
