### ISSUE TITLE
Add Ethereum's Official Solidity Language Mode as Layer

### ISSUE THREAD

**Issue by josiah14** [syl20bnr/spacemacs#10629]
Request to have the official [ethereum/emacs-solidity](https://github.com/ethereum/emacs-solidity) language mode added as an official Spacemacs layer.

**Comment by lemontreeran** [comment]
Any update on this?

**Comment by d12frosted** [comment]
I don't see any related PRs. Also, I don't know of any WIP.

**Comment by duianto** [comment]
The following PRs (possibly modified) changes are now on the develop branch:
Add Solidity layer #12922
