### ISSUE TITLE
save new buffers

### ISSUE THREAD

**Issue by untoreh** [syl20bnr/spacemacs#10626]
as I write this it feels like there is a huge sign I have missed somewhere along the way...anyhow
I am accustomed to open new buffers, so `SPC-b-N` , but this does not create files. Too bad that any auto save package out there that I have tried calls `buffer-file-name` to check if the current buffer is a file. Of course this new buffer might or might not be a new file i don't want to be bothered giving it a name so instead of changing the check function of the auto save call I put this in my user config:
```elisp
(setq scratches-dir (concat spacemacs-cache-directory "scratches"))
(make-directory scratches-dir t)
(defun spacemacs/new-empty-file ()
  (interactive)
  (spacemacs/new-empty-buffer)
  (setq default-directory scratches-dir)
  (set-visited-file-name
   (make-auto-save-file-name)))
(spacemacs/set-leader-keys "fN" 'spacemacs/new-empty-file)
```
Is there a better way? The scratch buffer `bs` is just that...a buffer called `*scratch*` so didn't seem really useful. Or maybe my behaviour is just bad and should always commit to whatever new buffer I write :o 
Of course it still needs garbage collection among the scratches.

**Comment by humanfactors** [comment]
There is no need for the scratch buffer to write to a new blank file. If you need to 'auto-save' the scratch buffer to a file, you probably should be using a file. If I understand you correctly, you want to be able to immediately create a file and start writing in it? Luckily, there are quite a few solutions here;

1. `C-x C-f` open open a new file. You could also bind `SPC - O - [something]' to create a few file in a particular directory.
2. If you are taking notes, may I suggest the [deft](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btools/deft) layer, or the excellent orgmode? 
3. [You could just create a function to create a newfile in a `~/tmp` directory, named the current timestamp?](https://emacs.stackexchange.com/questions/14673/emacs-function-to-make-a-file-with-date-time-as-filename-and-a-shortcut-for-it)

**Comment by untoreh** [comment]
yes you are probably right, I suppose `bB` was too ingrained in my habits
