### ISSUE TITLE
Auto-completion for Python does not working

### ISSUE THREAD

**Issue by hilman-dayo** [syl20bnr/spacemacs#10638]
#### Description :octocat:
Most of the time, `auto-completion` for Python won't work within a `.py` file. I will need to manually run an `Inferior Python` buffer and import libraries within it. Auto complete for the `.py` file will then work if the imported libraries in the `Inferior Pyton` is the same with the imported libraries in the `.py` file.

#### Reproduction guide :beetle:
- Install and set spacemacs from scratch (develop branch)
- Insert `python` and `auto-completion` layer in the dotfile, quit and restart Emacs
- Open a `.py` file
- Since I am using `pyenv`, set the environment with `, v s`
- Import some libraries and test the auto-completion

*Observed behaviour:* :eyes: :broken_heart:
The auto-completion does not working. It will only works if an `Inferior Python` is available and libraries are imported within it. The `*anaconda-mode*` buffer rarely output any weird message. Most of the time, it just shows something like this: `anaconda_mode port 55403`. Some images:
<img width="1004" alt="before" src="https://user-images.githubusercontent.com/16521877/39530371-c9a916bc-4e63-11e8-8986-37582aa09c7d.png">
<img width="1004" alt="after" src="https://user-images.githubusercontent.com/16521877/39530376-cc45c9c4-4e63-11e8-9c5c-9f3ef55e0860.png">

*Expected behaviour:* :heart: :smile:
Auto-completion can work flawlessly.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d4017b1c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm python markdown auto-completion emacs-lisp neotree)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by saskenuba** [comment]
I'm having the exactly same behavior. Everything works normally, virtual envs and etc, but I get the auto-completion for objects methods only after I send the `.py` buffer to the `Inferior Python` to get interpreted.
And then if I want to create another variable, a list for example, in my `.py` buffer to get the the list methods, I need to send the buffer to the repl again.

On my Message buffer, these two errors pop everytime I write the `.` to access the methods:

```
Company: An error occurred in auto-begin
Company: backend company-capf error "Nothing to complete" with args (prefix)
```

**Comment by hilman-dayo** [comment]
Thought I was alone. As for me, the error got rarely printed out. I will need to try and error (starting and quitting Emacs multiple time) in order to get the `auto-completion` working.

**Comment by jg-made** [comment]
I have experienced this exact issue with a fresh install of Ubuntu 16.04 LTS and Spacemacs develop branch. Auto-completion does not work until a Python REPL is instantiated in the editor and the relevant libraries are imported via the REPL. The message buffer does not show any error message.

**Comment by jg-made** [comment]
My friends, I have a "fix" for this.
1. `pip install jedi` into your environment (I am assuming if you use venvs then your spacemacs detects that)
2. add jedi to additional packages in spacemacs config:
```
   dotspacemacs-additional-packages
   '(
     (jedi :location elpa)
     )
```
Enjoy your auto-completion

**Comment by saskenuba** [comment]
@jg-made the workaround works for me, so maybe this is an issue with company-backends not finding jedi system-wide?
When you send the buffer to the python repl, maybe company-capf use a cache system, so it works both at the `.py` buffer and the `Inferior Python`. 
I don' really know, just making some assumptions.

**Comment by hilman-dayo** [comment]
@jg-made For this time being, it is not working for me 😢.
Really want this problem to be solved..

**Comment by saskenuba** [comment]
Apparently `company-anaconda` is not set as a `company-backends` for some weird reason.
Remember to undo the workaround above or it won't work.

Try this putting this at your dotfile user-config:
```
(eval-after-load "company"
 '(add-to-list 'company-backends 'company-anaconda))
```

It should work right away with a new file, or after activating the virtualenv.

**Comment by jg-made** [comment]
@hilman-dayo Are you using virtual environments? If so, try installing jedi into your system environment.

**Comment by hilman-dayo** [comment]
It works!!! Thank you @saskenuba! This made my day! I hope I too someday can debug these kind of stuffs. Being a relatively beginner in emacs makes it a little harder for me.

One question though. Looks like at the start of working with a file, there are some errors. After a while, the errors stop. Below is from *anaconda-mode* buffer:

```
anaconda_mode port 49891
127.0.0.1 - - [04/May/2018 23:33:23] ================================================================================
Traceback (most recent call last):
  File "/Users/hilman_dayo/.pyenv/versions/3.6.5/envs/cv/lib/python3.6/site-packages/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/Users/hilman_dayo/.pyenv/versions/3.6.5/envs/cv/lib/python3.6/site-packages/anaconda_mode.py", line 30, in wrapper
    return f(Script(source, line, column, path))
  File "/Users/hilman_dayo/.pyenv/versions/3.6.5/envs/cv/lib/python3.6/site-packages/anaconda_mode.py", line 50, in wrapper
    for definition in f(script)]
  File "/Users/hilman_dayo/.pyenv/versions/3.6.5/envs/cv/lib/python3.6/site-packages/anaconda_mode.py", line 50, in <listcomp>
    for definition in f(script)]
  File "/Users/hilman_dayo/.emacs.d/.cache/anaconda-mode/0.1.9/jedi-0.12.0-py3.6.egg/jedi/api/classes.py", line 286, in full_name
    path = list(self._path())
  File "/Users/hilman_dayo/.emacs.d/.cache/anaconda-mode/0.1.9/jedi-0.12.0-py3.6.egg/jedi/api/classes.py", line 188, in _path
    return reversed(list(to_reverse()))
  File "/Users/hilman_dayo/.emacs.d/.cache/anaconda-mode/0.1.9/jedi-0.12.0-py3.6.egg/jedi/api/classes.py", line 164, in to_reverse
    for n in reversed(module_context.py__name__().split('.')):
AttributeError: 'ImplicitNamespaceContext' object has no attribute 'py__name__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hilman_dayo/.pyenv/versions/3.6.5/envs/cv/lib/python3.6/site-packages/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/Users/hilman_dayo/.pyenv/versions/3.6.5/envs/cv/lib/python3.6/site-packages/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/Users/hilman_dayo/.pyenv/versions/3.6.5/envs/cv/lib/python3.6/site-packages/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/Users/hilman_dayo/.pyenv/versions/3.6.5/envs/cv/lib/python3.6/site-packages/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "AttributeError(\\"\'ImplicitNamespaceContext\' object has no attribute \'py__name__\'\\",)"}}')
```

Is it normal? Is it because the *anaconda-mode* is _warming up_ at the beginning?

**Comment by Glaeqen** [comment]
Workaround worked for me as well. It is so discouraging that I'm unable to debug all those issues efficiently myself. I hope proper upstream patch will be figured out soon :)

**Comment by syl20bnr** [comment]
Thanks for the report, should be fixed in develop branch. Be sure to
remove the work-arounds when you update to last develop.

**Comment by Glaeqen** [comment]
@syl20bnr Unfortunately, [fix commit](https://github.com/syl20bnr/spacemacs/commit/996cc91b5dc0494055813ccf660ad4e20658ae8f) didn't resolve this issue (workaround still required to get company working) :cry:

**Comment by syl20bnr** [comment]
Mmmmhhh that's weird it does not work for you, the commit fix the issue
of company-backends not being set right away.

When you open a python buffer can you check the value of
`company-backends` ? `SPC h d v company-backends`.

**Comment by r0bobo** [comment]
@syl20bnr I also have the same issue with the latest develop version. Python completion does not work until I open a second python file.
The value for my `company-backends` is:
```elisp
Value: ((company-anaconda :with company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev :with company-yasnippet))

Original value was 
(company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
```

**Comment by syl20bnr** [comment]
Funny I introduced a new bug while fixing it where the side effect was
the same as the original bug when
`auto-completion-enable-snippets-in-popup` is set to nil :-)

This should be really fixed now in develop, thanks @dsedivec for finding
the bug and provided a solution to it.

**Comment by andno037** [comment]
I have a similar problem. Where autocompletion work for most of my modules but not all. I'm working on an open source project where they have created a module of there code and it's installed using a setup.py script. The installation works and autocomplete work in Inferior python buffer (after import) but not in the .py buffer. I'm not sure this is a bug rather just a difference how auto-completion is done in the two buffers.
I would appreciate if someone could point me in a direction where this differences may be and if it's possible to change. (The project in question is https://github.com/carla-simulator/carla)

**Comment by ThyrixYang** [comment]
I found I have duplicated python and javascript in the layers list, and after I deleted them the auto-completion started work. Hope this may help

**Comment by FightingGoWp** [comment]
I meet the same problem, have this sovled?

**Comment by FightingGoWp** [comment]
I met the same problem, have this solved?

**Comment by FightingGoWp** [comment]
> My friends, I have a "fix" for this.
> 
> 1. `pip install jedi` into your environment (I am assuming if you use venvs then your spacemacs detects that)
> 2. add jedi to additional packages in spacemacs config:
> 
> ```
>    dotspacemacs-additional-packages
>    '(
>      (jedi :location elpa)
>      )
> ```
> 
> Enjoy your auto-completion

when I try this, I just met a new problem like this:
Looking for `symbol' in `(jedi :location elpa)' failed because:
  not a symbol)"

**Comment by lebensterben** [comment]
@FightingGoWp use LSP.

**Comment by FightingGoWp** [comment]
already used!

**Comment by FightingGoWp** [comment]
Whatever i do , auto-complete doesn't work in .py file though I import the same lib in the Inferior Python now!

**Comment by lebensterben** [comment]
@FightingGoWp 
Same issue as describe in https://github.com/syl20bnr/spacemacs/issues/14535#issuecomment-803314114
Use 
```elisp
dotspacemacs-additional-packages '(jedi)
```
