### ISSUE TITLE
Changing default scratch buffer mode to org-mode greatly slows startup time

### ISSUE THREAD

**Issue by mraruiz** [syl20bnr/spacemacs#10646]
#### Description :octocat:
Changing default scratch buffer mode to org-mode greatly slows startup time.

#### Reproduction guide :beetle:
- Start Emacs
- Set default scratch buffer to org-mode
- Restart Emacs

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d4017b1c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by mraruiz** [comment]
After reading about use-package I realized that this behavior wasn't so unexpected after all.

**Comment by r33drichards** [comment]
care to share what you mean? or share what you read about use-package? I know that org-mode is a large package and loading it on init can slow load times, but I don't understand how use-package effects that.
