### ISSUE TITLE
I get two neotree windows open at the same time when I type `SPC p t`.

### ISSUE THREAD

**Issue by lucasprag** [syl20bnr/spacemacs#10647]
#### Description :octocat:

I get two neotree windows open at the same time when I type `SPC p t`.

![screen shot 2018-05-04 at 16 46 15](https://user-images.githubusercontent.com/2293178/39649314-cd5d08aa-4fbb-11e8-818b-55ca462f39a3.png)

#### Reproduction guide :beetle:
- Start Emacs
- Open a project `SPC p p`
- Open neotree `SPC p t`
- Choose and enter to open a file
- Go to a new workspace `SPC l w 2`
- Close neotree `SPC p t`
- Go back to the first workspace `SPC l w 1`
- Try to close the neotree that is open `SPC p t`
- See that you got two neotree windows

*Observed behaviour:* :eyes: :broken_heart:
I get two neotree windows

*Expected behaviour:* :heart: :smile:
Close the nettree window that is open

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql react javascript yaml html ruby helm auto-completion better-defaults emacs-lisp git markdown
     (shell :variables shell-default-shell 'eshell shell-default-height 40 shell-default-position 'bottom)
     syntax-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by Alexander-Miller** [comment]
That's an old neotree bug. I had found and reported it as far back as 2016. It hasn't been fixed since, though @bmag did propose [a workaround](https://github.com/jaypei/emacs-neotree/issues/167).

You can also try [treemacs](https://github.com/Alexander-Miller/treemacs). That bug is what inspired me to write treemacs in the first place and by now it is faster/prettier/more featureful etc than neotree.

**Comment by lucasprag** [comment]
@Alexander-Miller I will look at it, thanks =)

**Comment by lucasprag** [comment]
I will close this issue once @Alexander-Miller fixes my issue, thanks
