### ISSUE TITLE
How can I call `org-batch-agenda` and related friends in batch mode?

### ISSUE THREAD

**Issue by concretevitamin** [syl20bnr/spacemacs#10642]
```
~ » /usr/bin/emacs --batch --load ~/.emacs.d/init.el --eval '(progn (org-batch-agenda))'                                                                                                                255 ↵
Loading /Users/me/.emacs.d/core/core-versions.el (source)...
Loading /Users/me/.emacs.d/core/core-load-paths.el (source)...
Symbol's value as variable is void: user-emacs-directory
```

I'll admit I don't have an understanding of how emacs/spacemacs configuration work.  That said, this seem like a problem about not passing the correct file to `--load`.  

My spacemacs works normally with org-mode.

Any help would be greatly appreciated!

**Comment by glumanda99** [comment]
@concretevitamin This one worked for me https://github.com/syl20bnr/spacemacs/issues/4504#issuecomment-232973179

**Comment by concretevitamin** [comment]
@glumanda99 hmm, could you paste the exact command that worked for you?

**Comment by glumanda99** [comment]
@concretevitamin 

```emacs -batch -l ~/.emacs.d/init.el --eval "(run-hooks 'emacs-startup-hook)" --eval '(org-batch-agenda "a")' 2> /dev/null```
