### ISSUE TITLE
Add lsp java backend

### ISSUE THREAD

**Issue by yyoncho** [syl20bnr/spacemacs#10654]
https://github.com/emacs-lsp/lsp-java

**Comment by songpeng** [comment]
There is another lsp java using IntelliJ 
[intellij-lsp-server](https://github.com/Ruin0x11/intellij-lsp-server). The author also writes the [a layer for spacemacs](https://github.com/Ruin0x11/lsp-intellij-spacemacs). 
I tried this one, and it looks good.

**Comment by yyoncho** [comment]
I am working on it, you can assign the issue to me.

**Comment by sdwolfz** [comment]
@yyoncho as you requested :wink: . Good luck tackling this... java support has always been one of emacs's greatest weakness IMHO.

**Comment by Chream** [comment]
@yyoncho  This works awesome! Thank you. Finally a decent java ide

**Comment by yyoncho** [comment]
@Chream you welcome, there is more to come - integrated debugger, test runner: 

![emacs_041](https://user-images.githubusercontent.com/13259670/42290066-c683c402-7fcb-11e8-9808-3231f04647bd.png)

**Comment by sdwolfz** [comment]
Merged into develop, thanks @yyoncho for putting in the effort to make this happen :1st_place_medal:.
