### ISSUE TITLE
Unknown layer quote

### ISSUE THREAD

**Issue by gleb-dianov** [syl20bnr/spacemacs#10658]
(I tried to submit this using Spacemacs, but GitHub gave an error, so I just copied the markdown)

#### Description :octocat:
On startup Spacemacs shows a strange warning:
"Warnings: - Unknown layer quote declared in dotfile."
Here is the [dotfile](https://gitlab.com/gleb_dianov/dotfiles/blob/master/.laptop_spacemacs).

#### Reproduction guide :beetle:
- Start Emacs with the config file

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs shows a warning.
"Warnings: - Unknown layer quote declared in dotfile."

*Expected behaviour:* :heart: :smile:
No warnings

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d4017b1c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(themes-megapack csv html sql yaml ivy auto-completion emacs-lisp git markdown latex org bibtex
                 (org :variables org-enable-reveal-js-support t)
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking evil-commentary haskell
                 '(auto-completion
                   (haskell :variables haskell-completion-backend 'intero)))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by antonalekseev** [comment]
You should get rid of rogue quote at the beginning of https://gitlab.com/gleb_dianov/dotfiles/blob/master/.laptop_spacemacs#L70.

Following code will suffice:
```
(auto-completion
       (haskell :variables haskell-completion-backend 'intero))
```

**Comment by gleb-dianov** [comment]
Thank you @antonalekseev
