### ISSUE TITLE
cursor becomes underscore after theme change

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#10657]
#### Description :octocat:
The cursor becomes an underscore after window switch just after theme switch.   

#### Reproduction guide :beetle:
- Start Emacs
- C-x 3
- M-x disable-theme  ;; pick whichever is active, spacemacs-dark by default
- M-x enable-theme   ;; pick any
- M-2

*Observed behaviour:* :eyes: :broken_heart:
The cursor becomes an underscore `_` character

*Expected behaviour:* :heart: :smile:
The cursor should remain however it was

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(graphviz yaml html python rust javascript scheme shaders haskell common-lisp helm auto-completion emacs-lisp git markdown emoji org deft themes-megapack erc pdf-tools)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by syl20bnr** [comment]
Does it do it with `SPC T s` also ?

**Comment by asciiascetic** [comment]
@syl20bnr Alas it does still happen.   (Well, I use emacs editing style so I ran `M-m T s`).

Thanks, btw, for giving a portion of your attention to my petty annoyances :)

**Comment by syl20bnr** [comment]
I cannot reproduce it, I'm on MacOS with Emacs 25.3.1 though.

**Comment by asciiascetic** [comment]
Thanks for checking.  [Here is a screen cap](https://www.dropbox.com/s/lez3se2z772gfrv/screen-cap.mp4?dl=0) of a fresh session for me.
