### ISSUE TITLE
configurations for yasnippets need update for yasnippets separate  snippets to new package

### ISSUE THREAD

**Issue by sunlin7** [syl20bnr/spacemacs#10656]
#### Description :octocat:
configurations for yasnippets need update for yasnippets separate  snippets to new package named "yasnippet-snippets".
The location for 'yas-installed-snippets-dir is no longer exists.
So the lines in .spacemacs/layers/ completion/auto-completion/package.el are invalid now, and it will cause error message when the yasnippets-mode be actived.
`        ;; ~/.emacs.d/elpa/yasnippet-xxxxx/snippets`
`        (push 'yas-installed-snippets-dir yas-snippet-dirs)` 
#### Reproduction guide :beetle:
- Start Emacs
- enable auto-completion
- update the yasnippets package to last version.

*Observed behaviour:* :eyes: :broken_heart:
compile error after update the yasnippets

*Expected behaviour:* :heart: :smile:
update success without error message.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.50.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html python helm auto-completion better-defaults emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking
      (ibuffer :variables ibuffer-group-buffers-by 'projects)
      semantic
      (gtags :variables gtags-enable-by-default t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
```

**Comment by antonalekseev** [comment]
#10316?

**Comment by sunlin7** [comment]
Yes, exactly same issue, close this ticket now. 
Thank you.
