### ISSUE TITLE
One liner to perform a spacemacs health check and detect any startup errors

### ISSUE THREAD

**Issue by jamesla** [syl20bnr/spacemacs#10651]
I create my development box image via a CI/CD pipeline and this includes programatically installing and configuring spacemacs. 

Recently a bug must have made it's way onto master and when I built my box it installed spacemacs successfully but it would throw errors upon startup.

I want to detect if this is a case and stop the image from building if this is the case. Is there an emacs one liner that I can run from the shell that will tell me whether spacemacs and it's layers are healthy and that spacemacs will startup without any errors?

**Comment by sdwolfz** [comment]
Try the following:
```bash
emacs -batch -u "$USER" -kill
```

You might not need the `-u "$USER"` part at all, or you might need to set that variable yourself. Also I'm not sure what happnes when emacs prompts you for input, it might fail immediatily in the best case, or hand until the build times out.

**Comment by jamesla** [comment]
Thanks I intentionally put some gibberish in my .spacemacs config to make warnings pop ups appear however since they are just pop up warnings this command doesn't throw any kind of error. Any ideas on how I can do exactly this but catch warnings as well as errors?
