### ISSUE TITLE
Looking for ways to increase spacemacs startup speed

### ISSUE THREAD

**Issue by jamesla** [syl20bnr/spacemacs#10652]
Not really sure where else to ask this but what options are available that I could use to increase my spacemacs startup time? Things like lazy loading packages and skipping automatic updates etc etc. 

I have looked through existing issues and official docs but was unable to find anything.

**Comment by MarcusE1W** [comment]
I would be interested as well. My Spacemacs runs on  Archlinux in Virtualbox. That of course does not make things faster. I appreciate that.

My Spacemacs start time varies around 17-20 sec.
To compare, Emacs started with `emacs -Q` starts in 2-3 sec (estimated)

Btw, once started it is absolutely usable and fast enough.
Any pointers would be appreciated.

**Comment by braineo** [comment]
syl20bnr has implemented dump in `moon` branch to boost loading time. You can switch to that and test it out. Basic idea behind that is dump a new emacs binary with the plugins you are using so theoretically you can have it opened instantly just like vanilla emacs.

Remember it is a test feature, it might not work as you expected but you can report issues to make it get merged as soon as possible.

**Comment by MarcusE1W** [comment]
Wow. That moon branch is very impressive :-)

I have removed the develop branch and renamed the .spacemacs file to have a fresh start.

Here are my times from a few test runs:

| Configuaration | develop branch | moon branch |
| --- | --- | --- |
| default config | ~14-15 sec | 7 sec |
| basic setup | ~17-20 sec | ~7sec |

That's 100% faster compared to my previous experience.

To explain a bit:
- the moon default is just under 7 sec and the basic config is just over 7 sec.
- my basic setup is: org, markdown and 
- my basic setup in develop was a bit more with all-the-icons activated, not sure if that makes any difference
- For people who want to compare: My system is a Virtualbox on a Lenovo notebook x250 with 2 real and 4 hyper cores, 8 GB RAM and SSD. The VM has 2 cores and 3 GB of RAM.

This is a super improvement :-)

**Comment by syl20bnr** [comment]
That speed improvement on the moon branch is not intentional if you did
not test with Emacs 27.1 and use the guide here: https://github.com/syl20bnr/spacemacs/blob/moon/EXPERIMENTAL.org#spacemacs-dumps-using-the-portable-dumper

I heard some reports that Emacs 27.1 is already faster to start without
any modification to Spacemacs. But the portbable dumper is even more
impressive as Spacemacs can start in ~0.5s :-)

So if you just checked out the moon branch and still used Emacs 25.x
then I don't understand the speed improvement :man_shrugging: :D

**Comment by syl20bnr** [comment]
Thank you for taking time to redo the tests.

This is definitely weird, I'll need to investigate, the `init.el` file
in the moon branch is more complicated so maybe there is a side-effect
which makes the loading faster. I'm really surprised.

**Comment by jappeace** [comment]
I run emacs in [daemon mode](https://www.emacswiki.org/emacs/EmacsAsDaemon), forking out new windows is instant.

**Comment by jamesla** [comment]
I am not bleeding edge enough for the moon branch but I hadn't thought of daemon mode. I'll give that a shot!

**Comment by sdsaati** [comment]
Thank you @jappeace with your idea, I'm just using `"E:\Program Files\Emacs\x86_64\bin\emacsclientw.exe" -create-frame --alternate-editor=""` and now after first time I open something, it's really fast.
