### ISSUE TITLE
Update quelpa?

### ISSUE THREAD

**Issue by MegaJ** [syl20bnr/spacemacs#10653]
There's a new version of quelpa out (since 2018-03-25), and it restores the `wiki` fetcher way of getting packages. I personally find that convenient.

The one in core/libs conflicts with the one on melpa, and when I try to update packages with quelpa, I keep using the one in core/libs, and my melpa downloaded one is ignored.

**Comment by syl20bnr** [comment]
I pushed the last version of Quelpa on the develop branch.

**Comment by MegaJ** [comment]
Awesome! No longer an issue then. Wow you were fast. :1st_place_medal:
