### ISSUE TITLE
Layer latex package auctex-latexmk will be removed on restarting spacemacs.

### ISSUE THREAD

**Issue by XiaoGeMa** [syl20bnr/spacemacs#10659]
#### Description :octocat:
Layer latex package auctex-latexmk will be removed on restarting spacemacs.

#### Reproduction guide :beetle:
- Start Emacs
- add layer latex in dotspacemacs file and restart. Many packages in latex layer are installed.
  quit spacemacs and start it again.

*Observed behaviour:* :eyes: :broken_heart:
- (Spacemacs) --> deleting auctex-latexmk... [1/1]
   in *Messages buffer.

*Expected behaviour:* :heart: :smile:
- nothing

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d4017b1c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(vimscript markdown lua helm auto-completion better-defaults emacs-lisp git org
           (python :variables python-backend 'anaconda)
           (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-format-on-save t)
           spell-checking syntax-checking chinese
           (latex :variables latex-enable-folding t)
           ipython-notebook
           (shell :variables shell-default-height 30 shell-enable-smart-eshell t shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by syl20bnr** [comment]
There is a toggle for this package, maybe we have a bug with the toggle behavior.
The toggle is: 

``` elisp
        (auctex-latexmk :toggle (string= "LatexMk" latex-build-command))
```

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/latex/packages.el#L15

**Comment by XiaoGeMa** [comment]
add this in user-config part or in layer part ？

**Comment by XiaoGeMa** [comment]
I added texlive font path to system font path. After texlive font path is deleted, the error never happens.
Also, startup time  of spacemacs decreases from 15 seconds to 5 seconds.

**Comment by Blaisorblade** [comment]
> add this in user-config part or in layer part ？

user-init or layer, see https://github.com/syl20bnr/spacemacs/issues/8467#issuecomment-284254636.
