### ISSUE TITLE
`evil-escape` should not be loaded in `emacs` editing style

### ISSUE THREAD

**Issue by nbraud** [syl20bnr/spacemacs#10667]
#### Description :octocat:
`evil-escape` should not be loaded in `emacs` editing style

#### Reproduction guide :beetle:
- Set `dotspacemacs-editing-style` to `'emacs` in `.spacemacs`
- Start Emacs
- Type `fd` rapidly

*Observed behaviour:* :eyes: :broken_heart:
The typed letters disappear.

*Expected behaviour:* :heart: :smile:
Editing works as in vanilla Emacs, and letters are written.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(ocaml asciidoc ruby go python html nginx rust haskell julia ansible yaml ivy emacs-lisp git markdown theming org version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by smile13241324** [comment]
Yep, you are right, I have made a pull request to avoid loading it when emacs editing style is used.

**Comment by nbraud** [comment]
@sdwolfz @smile13241324 Thanks for taking care of this  :)
