### ISSUE TITLE
Find and Replace CamelCases (capitalizes) replacement text

### ISSUE THREAD

**Issue by joech4n** [syl20bnr/spacemacs#10661]
#### Description :octocat:

Find and Replace CamelCases (capitalizes) replacement text.

#### Reproduction guide :beetle:
- Start Emacs
- enter this text:

```
Example Text
```

- run Find and Replace Command

```
%s|\(.*\)|[[\1>>https://a.example.com/\1]]|g
```

*Observed behaviour:* :eyes: :broken_heart:

```
[[Example Text>>Https://A.Example.Com/Example Text]]
```

*Expected behaviour:* :heart: :smile:

```
[[Example Text>>https://a.example.com/Example Text]]
```
#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(yaml javascript python ivy deft emacs-lisp evil-snipe html
      (markdown :variables markdown-live-preview-engine 'vmd)
      (org :variables org-enable-reveal-js-support t org-enable-github-support t)
      spell-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by Miciah** [comment]
Sorry, I do not know whether it is intended or an oversight.  I suggest asking upstream.  This upstream issue provides some background that may be helpful in understanding the current behavior: <https://github.com/emacs-evil/evil/issues/314>
