### ISSUE TITLE
Python layer is not working properly with dockerized python interpreter

### ISSUE THREAD

**Issue by skliarpawlo** [syl20bnr/spacemacs#10660]
#### Description :octocat:
In python layer autocomplete or run tests doesn't work with docker. 
anaconda is being installed into docker automatically, but any ask for autocomplete
results in error:
  eldoc error: (error tool-castor_dev_run_1/37031 nodename nor servname provided, or not known)

#### Reproduction guide :beetle:
- Start docker container:
   docker ps
   ... name=my-docker-container ...
- set python interpreter in ~/.spacemacs:
(defun dotspacemacs/user-config ()
  (setq multi-term-program "/bin/zsh")
  (setq python-shell-interpreter "/docker:root@tool-castor_dev_run_1:python3.5")
  )

- Start Emacs
- Open python file, and ask for autocomplete with <TAB>

*Observed behaviour:* :eyes: :broken_heart:
  eldoc error: (error tool-castor_dev_run_1/37031 nodename nor servname provided, or not known)

*Expected behaviour:* :heart: :smile:
  provide some autocomplete obtained from docker

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.10
- Spacemacs branch: master (rev. 4bb4cb4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html javascript yaml
      (clojure :variables clojure-align-forms-automatically t)
      markdown helm auto-completion better-defaults emacs-lisp
      (python :variables python-test-runner 'pytest python-backend 'anaconda)
      osx scala shell git markdown org
      (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking themes-megapack docker)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by jmicahc** [comment]
You may have to set python-shell-interpreter in dotspacemacs/user-init to ensure it's loaded before the python layer. This fixed autocomplete for me when connecting over ssh. However, pytest (not sure about nose) still doesn't work.

**Comment by marcoleewow** [comment]
@skliarpawlo were you able to solve this issue?

**Comment by skliarpawlo** [comment]
No, I gave up on this idea 😞
