### ISSUE TITLE
problem of  line numbers in fedora

### ISSUE THREAD

**Issue by xfdbs** [syl20bnr/spacemacs#10672]
Fedora 28, emacs 25.3.1, spacemacs (both master and the latest release version). 
I can not show line numbers. I have modified text 'defvar dotspacemacs-line-numbers t' in core-dotspacemacs.el, but it did not work.

**Comment by Compro-Prasad** [comment]
AFAIK you set variables in `~/.spacemacs` or `~/.spacemacs.d/init.el`. @xfdbs Why are you editing `core-dotspacemacs.el`?

**Comment by xfdbs** [comment]
@Compro-Prasad  All right. But I don't think that caused the problem.

**Comment by Compro-Prasad** [comment]
What about `M-x linum-mode`? Does it work?

**Comment by xfdbs** [comment]
@Compro-Prasad  Yes, it works .  Thanks .

**Comment by Compro-Prasad** [comment]
You can add `(add-hook 'find-file-hook 'linum-mode)` to enable it in every file. There is a `SPC t n` keybinding to toggle line numbers. There is a `M-x global-linum-mode` too. Anything else you want?

**Comment by xfdbs** [comment]
@syl20bnr  Should I close this issue now or wait for it to be fixed ?

**Comment by xfdbs** [comment]
@Compro-Prasad  OK . Thank you very much .
