### ISSUE TITLE
Defadvice select-window can reduce the code about golden-ratio-extra-commands.

### ISSUE THREAD

**Issue by honmaple** [syl20bnr/spacemacs#10671]
Hello, I find a way to make golden-ratio work normal without define golden-ratio-extra-commands
```
  (setq golden-ratio-extra-commands nil)
  (defadvice select-window (after select-window activate)
    (golden-ratio))
```
It will reduce much code about golden-ratio-extra-commands. Can this be added to spacemacs?

**Comment by syl20bnr** [comment]
How long are you using this setup? I would prefer it to be battle-tested
before throwing it in the code base :-)

**Comment by bmag** [comment]
Looks more of an upstream issue to me. There probably is a reason why golden-ratio doesn't advise `select-window`, maybe this function is called too often? On the other hand, golden-ratio uses `post-command-hook`, which really is called all the time (after each command!), so maybe there isn't really a reason. Someone [asked this upstream](https://github.com/roman/golden-ratio.el/issues/57) 3 years ago but didn't receive an answer.

On another note, `advice-add` is an improved replacement for `defadvice`, so preferably use that. In this case it would simply be:
```elisp
(advice-add 'select-window :after #'golden-ratio)
```

(see [porting old advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Porting-old-advice.html#Porting-old-advice) for more info)

**Comment by syl20bnr** [comment]
I actually have the commit bit on the `golden-ratio` repository, I'll
look into it.

**Comment by honmaple** [comment]
Sorry for late reply, I have used this setup for about one month, and everything is ok except `helm-execute-persistent-action` that I use `tab` to expand a directory.

I usually use `winum-select-window-{num}, split-window-right,split-window-below, etc.`, and I noticed every commands call `select-window`, so maybe `defadvice select-window` is better way rather than `(add-to-list 'golden-ratio-extra-commands 'every-possible-command)`
