### ISSUE TITLE
company-backends broken in emacs-lisp-mode (and probably in other modes too)

### ISSUE THREAD

**Issue by dsedivec** [syl20bnr/spacemacs#10676]
#### Description :octocat:
In an `emacs-lisp-mode` buffer, `company-backends` is getting only the Spacemacs default value (`spacemacs-default-company-backends`), `company-capf` (added by emacs-lisp layer) is *not* being added, so completion is subpar/broken in all such buffers.

I think this is most likely due to 40f28c7d12, which introduced the "raw" company backend lists.  If you expand the `spacemacs|add-company-backends` call from [layers/+lang/emacs-lisp/packages.el](https://github.com/syl20bnr/spacemacs/blob/ebe4c602647801d59013915c8c97d44570556f3e/layers/%2Blang/emacs-lisp/packages.el#L56) you get:

```elisp
  (progn
    (defvar company-backends-emacs-lisp-mode-raw spacemacs-default-company-backends "Company backend list for emacs-lisp-mode.")
    (defvar company-backends-emacs-lisp-mode company-backends-emacs-lisp-mode-raw "Company backend list for emacs-lisp-mode.")
    (add-to-list 'company-backends-emacs-lisp-mode-raw 'company-capf)
    (defun spacemacs//init-company-emacs-lisp-mode nil "Initialize company for emacs-lisp-mode."
           (when auto-completion-enable-snippets-in-popup
             (setq company-backends-emacs-lisp-mode
                   (mapcar 'spacemacs//show-snippets-in-company company-backends-emacs-lisp-mode-raw)))
           (set
            (make-variable-buffer-local 'auto-completion-front-end)
            'company)
           (set
            (make-variable-buffer-local 'company-backends)
            company-backends-emacs-lisp-mode))
    (add-hook 'emacs-lisp-mode-hook 'spacemacs//init-company-emacs-lisp-mode t)
    (add-hook 'emacs-lisp-mode-hook 'company-mode t))
```

1. `company-backends-...-raw` is initialized with the default backends.
2. `company-backends-...` is set to the same value as `company-backends-...-raw`.
3. The requested backends are added to `company-backends-...-raw` *at the head*, which does not affect the value of `company-backends-...`.

I would put up a pull request to fix this but I'm not sure if it makes more sense to just move the `add-to-list` before `defvar company-backends-emacs-lisp-mode`, or if it would be better to make the hook set `company-backends-...` to the value of `company-backends-...-raw` every time (unconditionally, not just when `spacemacs//show-snippets-in-company` is true).

#### Reproduction guide :beetle:
- Start Emacs with Spacemacs on develop branch
- Open an Emacs Lisp file
- Show the value of `company-backends` in the buffer

*Observed behaviour:* :eyes: :broken_heart:
```
company-backends is a variable defined in ‘company.el’.
Its value is
((company-dabbrev-code company-gtags company-etags company-keywords)
 company-files)
```

*Expected behaviour:* :heart: :smile:
```
Value:
(company-capf
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files)
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e481894fc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(rust nginx lua ivy
      (auto-completion :variables auto-completion-enable-sort-by-usage t)
      better-defaults
      (emacs-lisp :variables emacs-lisp-hide-namespace-prefix nil)
      git markdown org spell-checking syntax-checking version-control ansible c-c++ chrome clojure common-lisp csv dash deft docker html imenu-list javascript latex
      (osx :variables osx-command-as 'super osx-option-as 'meta)
      pandoc perl5 python restructuredtext ruby shell shell-scripts sql yaml)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by jvalkeejarvi** [comment]
This commit is the reason for current behaviour:
https://github.com/syl20bnr/spacemacs/commit/40f28c7d12221e22da7e1994ec4b41066b4b70b3

Custom backends don't get pushed to `',backends-var-name` but only to `,raw-backends-var-name`. @syl20bnr should they be pushed to both?

**Comment by farva** [comment]
I couldn't reproduce the problem mentioned as the reason for [40f28c7](https://github.com/syl20bnr/spacemacs/commit/40f28c7d12221e22da7e1994ec4b41066b4b70b3).

Should it be reverted?

**Comment by syl20bnr** [comment]
Thank you for the great report, I opted for the second solution.
See commit https://github.com/syl20bnr/spacemacs/commit/391bbc149

**Comment by et2010** [comment]
Thanks for the fix. However, the issue persists. The completion backend breaks again after a few completions.

**Comment by syl20bnr** [comment]
What do you mean "after a few completions" ? Do you have a better repro
steps ? Do you have some user configuration related with company ?

I cannot reproduce your issue with last develop, typing `(shell-|)` with
point as `|` works as expected.

**Comment by et2010** [comment]
Sorry, but I can't reproduce it either. I think it's fixed.

**Comment by dsedivec** [comment]
Thanks for the fast fix @syl20bnr!  This issue is fixed for me, hope it's OK that I close it to keep the issues list tidy.
