### ISSUE TITLE
Tern doesn't start since latest develop update

### ISSUE THREAD

**Issue by tavurth** [syl20bnr/spacemacs#10686]
#### Description :octocat:
When starting any JSX file a new message buffer is spawned with the following note:

```
error in process sentinel: tern-find-server: Wrong type argument: listp, "tern"
error in process sentinel: Wrong type argument: listp, "tern"
```

#### Resolved by :beetle:
 - Running `git reset --hard 8df99c44` resolves this issue, so it's a more recent bug

#### Reproduction guide :beetle:
- Checkout the latest `/origin/develop` @ `d8b1f81f`
- Start Emacs
- Start any `jsx` file
- Run `C-c r` on any variable

*Observed behaviour:* :eyes: :broken_heart:
- Tern does not work
- `C-c r` (rename variable) does not work
- `magit` is broken
- `projectile` is broken
- `issue submission` is broken

I was unable to submit this report through `spacemacs` directly as it throws the error about `listp`

*Expected behaviour:* :heart: :smile:
- Everything working

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d8b1f81f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(markdown
csv
git
yaml
html
helm
nginx
react
python
javascript
common-lisp
syntax-checking
auto-completion)
```
- System configuration features: 
```
XPM
GIF
PNG
GPM
XFT
X11
JPEG
TIFF
RSVG
DBUS
ZLIB
GTK3
SOUND
LCMS2
NOTIFY
GNUTLS
LIBOTF
LIBXML2
MODULES
THREADS
FREETYPE
M17N_FLT
XWIDGETS
GSETTINGS
LIBSELINUX
LIBSYSTEMD
IMAGEMAGICK
TOOLKIT_SCROLL_BARS
```

#### Backtrace :paw_prints:
```
error in process sentinel: tern-find-server: Wrong type argument: listp, "tern"
error in process sentinel: Wrong type argument: listp, "tern"
```

**Comment by tavurth** [comment]
So I ran a search to find the commit which is causing the issue and it seems there may be two:

- [5a92c439](https://github.com/syl20bnr/spacemacs/commit/5a92c439) `error in process sentinel: Searching for program: No such file or directory, --strip-crs`
- [5c14486b](https://github.com/syl20bnr/spacemacs/commit/5c14486b) `Error (use-package): js2-mode/:init: Symbol’s value as variable is void: tern-command`
- [4cc57dea](https://github.com/syl20bnr/spacemacs/commit/4cc57dea) All working

After [5c14486b](https://github.com/syl20bnr/spacemacs/commit/5c14486b) the tern error starts to appear, but jump later in the history and `sentinel` starts throwing up errors instead of tern. I'm guessing they're linked.

Guessing that the issue is because of the changes in `5c14486b`

**Comment by williamchanter** [comment]
Not sure if this helps but can confirm I have very similar issue, when opening `.js` file. 

Tern does not start, it's not listed when running `<SPC> a p`. When running `tern-use-server` I get `Error (use-package): tern/:config: Symbol’s value as variable is void: tern-key-bindings-modes` in a warnings buffer. 

*I'm on develop and the latest commit `4980a6461d82c206a97ad38c74b8bbb6d27db8e2`*

On a side note, I never really comment on here so just wanted to say, the work being done here s pretty amazing and thank you

**Comment by tavurth** [comment]
Seems like the `--` is `BEM` style process-variable naming, and changing it back may cause issues or style issues in the near future.

@syl20bnr Would removing the `--` cause issues in near future?

**Comment by syl20bnr** [comment]
Should be fixed now, big thanks to @jvalkeejarvi for the great fixes.
