### ISSUE TITLE
Anaconda-Mode problems still exist?

### ISSUE THREAD

**Issue by vlurgio** [syl20bnr/spacemacs#10688]
#### Description :octocat:
Anaconda mode is not working correctly in python. I see that this was referenced about a year ago but why is this still a problem. 
(Note that I have tried editing the disutils python file and this did not work for me. )
#### Reproduction guide :beetle:
- Start Emacs
Install spacemacs. Open a python file. Try to find the declaration of a variable. (spc m g g)
*Observed behaviour:* :eyes: :broken_heart:
nothing happens at first if you keep trying you'll eventually get something like cannot find anaconda server. 

*Expected behaviour:* :heart: :smile:
The program finds declaration of variables and anaconda server stars up correctly 
#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm auto-completion better-defaults emacs-lisp markdown
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spell-checking syntax-checking version-control git react)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
The Back trace is not printing out correctly but here is what it is giving me 
```

[0;31mAssertionError[0m: ['-c', "\nimport sys, site\nsite.addsitedir('.')\nimport anaconda_mode\nanaconda_mode.main(sys.argv[1:])\n", '127.0.0.1', '']
[0;31m[0m
[0;31mAssertionError[0mTraceback (most recent call last)
[0;32m<<ipython-input-1-02efe3d5637d>[0m in [0;36m<<module>[0;34m()[0m
[1;32m      3[0m [0msite[0m[0;34m.[0m[0maddsitedir[0m[0;34m([0m[0;34m'.'[0m[0;34m)[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mimport[0m [0manaconda_mode[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0manaconda_mode[0m[0;34m.[0m[0mmain[0m[0;34m([0m[0msys[0m[0;34m.[0m[0margv[0m[0;34m[[0m[0;36m1[0m[0;34m:[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0m
[0m
[0;32m~/.emacs.d/.cache/anaconda-mode/0.1.10/anaconda_mode-0.1.10-py3.6.egg/anaconda_mode.py[0m in [0;36mmain[0;34m(args)[0m
[1;32m    106[0m [0;34m[0m[0m
[1;32m    107[0m [0;32mdef[0m [0mmain[0m[0;34m([0m[0margs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0m
[0;32m--> 108[0;31m     [0;32massert[0m [0mlen[0m[0;34m([0m[0margs[0m[0;34m)[0m [0;34m==[0m [0;36m2[0m[0;34m,[0m [0margs[0m[0;34m[0m[0m
[0m[1;32m    109[0m     [0mhost[0m [0;34m=[0m [0margs[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0m
[1;32m    110[0m     [0;32mif[0m [0margs[0m[0;34m[[0m[0;36m1[0m[0;34m][0m [0;34m!=[0m [0;34m""[0m[0;34m:[0m[0;34m[0m[0m

[0;31mAssertionError[0m: ['-c', "\nimport sys, site\nsite.addsitedir('.')\nimport anaconda_mode\nanaconda_mode.main(sys.argv[1:])\n", '127.0.0.1', '']

**Comment by rgb-24bit** [comment]
Try develop branch ?

**Comment by YinTianliang** [comment]
I encountered the same problem yesterday, in develop branch.
I don't know whether this is a problem of spacemacs or anaconda-mode,
but I have solved it by change
`104 anaconda_mode.main(sys.argv[1:])`
to
`104 anaconda_mode.main(sys.argv[-2:])`
in anaconda-mode.el. and then delete anaconda-mode.elc

Looking forward to better solution :D

**Comment by vlurgio** [comment]
This worked immediately. Thank you so much I code way to much in python for it not to work.

**Comment by syl20bnr** [comment]
Should it be submitted upsream ?

**Comment by vlurgio** [comment]
Possibly but upstream as in anaconda-mode we're not sure if its that or spacemacs that is causing the issue

**Comment by syl20bnr** [comment]
Ideally it should be tested in an `emacs -Q` session.

Actually I believe we have a great way to make this kind of test.
Let me search for it :-)

**Comment by syl20bnr** [comment]
Try this: https://git@github.com/syl20bnr/spacemacs/blob/develop/news/news01.org#L365-L367

```
- press ~SPC q D~ to restart Emacs with a selected list of packages to load,
  in this mode Spacemacs is completely disabled so you get the perfect way
  to test wether a bug comes from Spacemacs configuration or not
```

**Comment by YinTianliang** [comment]
There have been similar issues in upstream:
[can't start 'anaconda-mode' server](https://github.com/proofit404/anaconda-mode/issues/284)

I think this is an issue of anaconda-mode, and it only happens when using IPython.

I have submitted my fix:
[Fix bug when using IPython](https://github.com/proofit404/anaconda-mode/pull/287)
