### ISSUE TITLE
Request: Integrate python-x into the Python layer - Send LINES to REPL

### ISSUE THREAD

**Issue by jjzmajic** [syl20bnr/spacemacs#10691]
This is a must-have feature in interactive programming, present in most layers (e.g. emacs-lisp). Spacemacs even has a recommended keybinding for the feature.

Given that the functionality is already implemented in a package, would it be possible to integrate it, so as to avoid having to configure it manually and make it more in line with Spacemacs' philosophy?

**Edit for clarification**: python-x refers to this package https://github.com/wavexx/python-x.el
Apologies for not linking to it earlier

**Comment by syl20bnr** [comment]
Sorry I'm not sure to understand your request. What is `python-x` exactly ?

**Comment by jjzmajic** [comment]
I made the appropriate edits up top. Sorry for the inconvenience!
