### ISSUE TITLE
PDF-Tools evilified state and org mode

### ISSUE THREAD

**Issue by benneti** [syl20bnr/spacemacs#10699]
#### Description :octocat:
Keybindings in pdf-view not working as evilified state is not starting.
(Manually invocing it using evil-evilified-states works)

#### Reproduction guide :beetle:
- Start Emacs
- Enable org and pdf-tools
- somewhere in userconfig try to use a
    (with-eval-after-load 'org ...)
- Open a pdf and try to use "j" or "k" to navigate

*Observed behaviour:* :eyes: :broken_heart:
Evilified state not starting

*Expected behaviour:* :heart: :smile:
Evilified state starting by itself

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4980a646)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t auto-completion-complete-with-key-sequence "df" auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior nil auto-completion-enable-snippets-in-popup t)
 (spell-checking :variables ispell-dictionary "en_US")
 syntax-checking semantic
 (latex :variables latex-enable-folding t latex-enable-auto-fill t latex-build-command "LatexMk")
 bibtex cdlatex
 (org :variables org-bullets-bullet-list
      '("◉" "○" "◆" "▶" "✸" "✿" "■" "▲")
      org-want-todo-bindings t)
 python shell-scripts emacs-lisp neotree git dash pdf-tools
 (shell :variables shell-default-shell 'multi-term shell-default-position 'bottom shell-default-height 35))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by benneti** [comment]
I played around a bit with my config - deleting all files and trieing stuff - and was able to get it working by using my dotfile with the master branch.
After that I checked out the develop branch again and now it still works.
So I will close this for now.
And by the way, thank you for maintaining spacemacs, what you do is just great :1st_place_medal:

**Comment by et2010** [comment]
I'm still having this issue on develop branch. I start from scratch and tried to install one layer a time. I found If I enable pdf-tools without org layer the issue is gone. If I enable org layer and pdf layer at the same time, the issue is back. I think we should load pdf layer before org layer, but I don't know how.

**Comment by et2010** [comment]
If I comment out this line in org layer, the issue is gone:

```
(org :location built-in)
```

**Comment by benneti** [comment]
Ok, after the update to emacs 26.1 the issue was here again, but the suggested fix by @et2010 works

**Comment by erolx** [comment]
it doesn't work any fix over there working for me.
