### ISSUE TITLE
(c++-mode) Behaviour of `align-current` has changed

### ISSUE THREAD

**Issue by skebanga** [syl20bnr/spacemacs#10690]
#### Description :octocat:
Behaviour of `align-current` has changed

#### Reproduction guide :beetle:
- Start Emacs
- Open scratch buffer (`SPC b s`
- Enter C++-mode (`M-x c++-mode`)

Enter the following text:

    Foo::Foo(int i,
    double d,
    char c)
    {}

- Place point on anywhere inside the argument list (eg: line 2)
- Execute `align-current` (`SPC x a c`)

*Observed behaviour:* :eyes: :broken_heart:

Only the argument-variable-names are vertically-aligned, argument-types remain unaligned

    Foo::Foo(int i,
    double       d,
    char         c)
    {}

*Expected behaviour:* :heart: :smile:

Previously both argument-types and argument-variable-names would be vertically aligned

    Foo::Foo(int    i,
             double d,
             char   c)
    {}

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d8b1f81fb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp html javascript go lua octave csv git markdown neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      imenu-list version-control
      (c-c++ :variables c-c++-enable-clang-support nil c-c++-default-mode-for-headers 'c++-mode c-c++-enable-auto-newline nil)
      (ranger :variables ranger-show-literal nil)
      python yaml lori-cpp
      (smart-tabs :variables smart-tabs-default-insinuations
                  '(c c++))
      protobuf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by syl20bnr** [comment]
The behavior has changed relating to what ? master --> develop, develop
--> develop ?

Can you check your previous commit when it works with `git reflog` ?

**Comment by skebanga** [comment]
$ git reflog
    d8b1f81fb (HEAD -> develop, origin/develop) HEAD@{0}: pull: Fast-forward
    70c1737c4 HEAD@{1}: reset: moving to HEAD
