### ISSUE TITLE
integrate lsp-ui with flychecker (develop branch)

### ISSUE THREAD

**Issue by dagadbm** [syl20bnr/spacemacs#10709]
Apparently lsp-ui is already included in the javascript/react layer but flychecker isn't using it. I get this message when i do SPC e v:

The following syntax checkers are not registered:

  - lsp-ui

Try adding these syntax checkers to `flycheck-checkers'. Flycheck Mode is
enabled. Use SPC u C-c ! x to enable disabled checkers.

Shouldn't this be done automatically by the layer or by flychecker?

How to fix this? (Should this be addresed by the layer)

**Comment by mspinelli** [comment]
Adding the last line below seemed to work for me
```
  (require 'lsp-mode)
  (require 'lsp-ui)
  (add-hook 'lsp-mode-hook 'lsp-ui-mode)
  (add-hook 'lsp-ui-mode-hook ' flycheck-mode)
```

**Comment by msuess** [comment]
`<SPC e v>` is looking good on a fresh pull, with `lsp-ui` being enabled and executable and config file being reported as `found`.

Flycheck does not show any errors however.
