### ISSUE TITLE
Rule for smarter fuzzy search

### ISSUE THREAD

**Issue by barischrooneyj** [syl20bnr/spacemacs#10700]
When I `SPC SPC delete file` the results in the image below are shown. The spacemacs commands are further down in priority, last is the one with a `SPC` shortcut. It is likely that the fact they're spacemacs commands is not taken into account. As a spacemacs user the spacemacs commands are more likely to be wanted  (conjecture)  and could be given a higher weighting, so the user doesn't have to read so far down the list, and so saves time.

This would require us to plug in some weighting rule into helm and/or ivy.

Also try `SPC SPC rename file` and I'm sure many others, the cumulative time sized for a person over many commands *could* be significant, at least for beginners.

And I realise a user can also try find the command by `SPC f` (in these cases) first and then hope to find what they are looking for, but the helm approach is also used and we can save time.

<img width="1280" alt="screen shot 2018-05-18 at 23 11 33" src="https://user-images.githubusercontent.com/6631452/40258380-b3880146-5af1-11e8-9ad5-a0c95422da1c.png">

**Comment by Compro-Prasad** [comment]
It is a nice but not a general feature. It is better to put those `spacemacs*` functions on some keybindings and use those.

**Comment by syl20bnr** [comment]
Not sure we can do much about it :-(

**Comment by Miciah** [comment]
For fun, here's a quick hack to sort functions with keybindings first:

```emacs-lisp
(defun helm-M-x-transformer-1@prioritize-commands-with-bindings (orig-fun candidates &optional sort)
  (cl-loop for cand in (funcall orig-fun candidates sort)
           if (string-suffix-p ")" (car cand))
             collect cand into first
           else
             collect cand into second
           finally return (append first second)))

(advice-add 'helm-M-x-transformer-1 :around
            #'helm-M-x-transformer-1@prioritize-commands-with-bindings)
```

**Comment by Miciah** [comment]
I evaluated it in a scratch buffer, but `M-:` should work (if you evaluate the `defun` and the `advice-add` forms one at a time).  Did you get any output from evaluation? Is the behavior of `SPC SPC` unaffected, or are you getting an error?

**Comment by Compro-Prasad** [comment]
No, wait. It does show up first if I haven't type in anything yet. But when I search for something, they come up in a different order.

**Comment by Compro-Prasad** [comment]
@barischrooneyj You can use something like `spacemacs delete file` to search for spacemacs specific things. If what you are saying is implemented then it will be annoying to many people in general including me. You can close this issue if you are satisfied.
