### ISSUE TITLE
How do I insert multiple empty lines in spacemacs "hybrid" mode?

### ISSUE THREAD

**Issue by vlurgio** [syl20bnr/spacemacs#10714]
Looking at a vim manual it seems i should be able to type 5 o and have it insert 5 lines below my current line. However on pressing 5 I see in the minibuffer it says c-u 5 - then when i press o it just overrides this and only inserts one line. Am I doing something wrong?

**Comment by mroh69** [comment]
press ESC to left the emacs mode (vim insert becomes emacs mode in hybrid mode) -> 5 lines

**Comment by vlurgio** [comment]
This is being done from normal mode not from insert mode.

**Comment by vlurgio** [comment]
I was also under the impression that when in hybid mode when you're in normal mode you can use all vim key bindings as though you're in vim.

**Comment by nixmaniack** [comment]
Even in vim(not vim mode of spacemacs) `5 o` doesn't give me 5 lines. I have to press `5 o ESC` to get 5 lines. And same is the case in hybrid mode. Can you confirm?

**Comment by mroh69** [comment]
> This is being done from normal mode not from insert mode.

Yes, but 'o' puts you in insert mode and that is emacs in hybrid. If you go back to normal mode from there you get the 5 lines.

**Comment by vlurgio** [comment]
That odd I still just get the same one line I typed. For example 5 - o h e l l o ESC gives me hello on one line. If I do 5 - 0 - ESC i again just get the one line and am put back into normal mode.

**Comment by vlurgio** [comment]
After further testing this seems to only happen in org-mode for some reason. So it may be a bug or a side effect of the keybindings in org-mode

**Comment by Compro-Prasad** [comment]
Problem is that org mode replicates many similar Emacs keybindings instead of just using them. Thus this might be good issue to solve for `evil-org`.

**Comment by Somelauw** [comment]
@Compro-Prasad evil-org enhances some built-in evil bindings, but when practical, we try to fall back on default evil functions as much as possible.

The master branch of Spacemacs uses an outdated fork of evil-org. Please try upgrading to Spacemacs development or try using evil-org directly and see if your issue is solved.
