### ISSUE TITLE
spacemacs.org contribute link is broken

### ISSUE THREAD

**Issue by sorsasampo** [syl20bnr/spacemacs#10710]
Leads to 404 on:

http://spacemacs.org/CONTRIBUTING.html

**Comment by syl20bnr** [comment]
Thanks for the report.

In develop branch it seems to work: http://develop.spacemacs.org

Seems we don't have this file in the master branch ?

**Comment by jasonzhouu** [comment]
same problem with links in:
 http://spacemacs.org/layers/LAYERS.html
#12079
