### ISSUE TITLE
Issue with incorrect errors on brackets in web-mode after calling an object in PHP

### ISSUE THREAD

**Issue by williamchanter** [syl20bnr/spacemacs#10724]
#### Description :octocat:

Sorry for this probably poor explanation ... Issue with `Search failed: there is an unmatched expression somewhere or we are at the beginning/end of file. [2 times]` occurring on every file which uses web-mode and has PHP within it, after a object call has been made in PHP. 

**Example File**
```php
<?php

echo 'will';

$imporant->thing->help->what = $blah;

?>

<a href="#">thing</a>
```
A picture which makes it clearer what the issue is:

![Picture of issue on Imgur](http://i.imgur.com/mDTBZp2.png)

An example with some real code from some random project:

![Picture of issue on Imgur](http://i.imgur.com/aGnl5sk.png)

The problem seems to be around the fact that after the first function call in PHP it closes the PHP section and then everything is incorrectly offset thereafter.

#### Reproduction guide :beetle:
- Start Emacs
- Open file which has PHP and HTML content
- If not in web-mode, enter web-mode
- Observe highlighted syntax errors on all `<` and `>` even when correct after calling php variable from object. 
- Issue also occurs with `{}<>()` symbols as seen below:
![Picture of issue on Imgur](http://i.imgur.com/8YRfkpA.png)

*Observed behaviour:* :eyes: :broken_heart:
Lots of highlighted syntax errors

*Expected behaviour:* :heart: :smile:
No errors as file is correctly formatted

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 551ed9cdc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm gtags csv auto-completion better-defaults emacs-lisp git gnus php org perl5
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control evernote shell-scripts
      (tern :variables tern-disable-port-files nil)
      (javascript :variables javascript-backend 'tern js2-basic-offset 4 js-indent-level 4)
      html markdown sql wikipedia-mode atomic-chrome python autohotkey docker
      (elfeed :variables rmh-elfeed-org-files
              (list "~/.emacs.d/private/elfeed1.org"))
      neotree erc graphviz themes-megapack common-lisp hyperbole erlang ssh-deploy)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Compro-Prasad** [comment]
I wonder which package is highlighting those brackets?

**Comment by syl20bnr** [comment]
Put some packages from the php layer list[1] in
`dotspacemacs-excluded-packages` of your dotfile and restart.

Hopefully this weirdness is triggered by one of the php layer packages.

[1] https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/php/packages.el#L12-L26

**Comment by Compro-Prasad** [comment]
Don't know. I just enabled php layer and restarted spacemacs but I wasn't able to reproduce this issue. @syl20bnr @williamchanter Any pointers to any packages?

**Comment by williamchanter** [comment]
Hi, Okay so packages ....

Firstly I've just pulled the latest changes from develop and updated all the packages so should be up to date.

The issue only occurs when in `web-mode` as the major mode. 

So the minor modes currently running when opening just a standard file in `web-mode` ...

```
Enabled minor modes: 
Anzu Async-Bytecomp-Package Auto-Composition
Auto-Compression Auto-Encryption Auto-Highlight-Symbol Bug-Reference-Prog
Clean-Aindent Column-Number Company Diff-Auto-Refine Editorconfig
Electric-Indent Emmet Eval-Sexp-Fu-Flash Evil Evil-Escape Evil-Lion Evil-Local
Evil-Matchit Evil-Search-Highlight-Persist Evil-Surround Eyebrowse
File-Name-Shadow Flx-Ido Flycheck Flycheck-Pos-Tip Flyspell Font-Lock
Git-Gutter+ Global-Anzu Global-Atomic-Chrome-Edit Global-Auto-Revert
Global-Eldoc Global-Evil-Search-Highlight-Persist Global-Evil-Surround
Global-Flycheck Global-Font-Lock Global-Git-Commit Global-Git-Gutter+
Global-Hl-Line Global-Magit-File Global-Origami Global-Page-Break-Lines
Global-Spacemacs-Leader-Override Global-Spacemacs-Whitespace-Cleanup
Global-Undo-Tree Global-Vi-Tilde-Fringe Goto-Address-Prog Helm Helm-Flx
Highlight-Numbers Highlight-Parentheses Hl-Todo Hs Hybrid Ido-Vertical
Info-Breadcrumbs-In-Mode-Line Line-Number Magit-File Mouse-Wheel Origami
Override-Global Persp Projectile Pupo Purpose Rainbow-Delimiters Recentf
Save-Place Savehist Shell-Dirtrack Show-Smartparens Show-Smartparens-Global
Spaceline-Helm Spaceline-Info Spacemacs-Leader-Override
Spacemacs-Whitespace-Cleanup Transient-Mark Undo-Tree Vi-Tilde-Fringe
Volatile-Highlights Which-Key Winner Winum Xterm-Mouse Yas Yas-Global
```
This does make me realise now that spacemacs doesn't have `web-mode` as an actual layer and I have just been entering `web-mode` myself by either `.dir-locals.el` or `<M-x> Web-mode` . Could this be an issue maybe?

So carrying on with packages, if I disable everything just in the buffer minor mode menu section so only `web-mode` is showing I still get the issue. Picture below because not had enough coffee to explain very well:

![web-issue](https://i.imgur.com/7vYeTJP.png)  

and the issue still occurs, so I've added in this to the config ...

```lisp
   ;; A list of packages that will not be installed and loaded.
   dotspacemacs-excluded-packages
   '(
     drupal-mode
     eldoc
     flycheck
     ggtags
     counsel-gtags
     helm-gtags
     php-auto-yasnippets
     php-extras
     php-mode
     phpcbf
     phpunit
     company-php
     )
```
and the issue still occurs.

To me it seems the issue is somewhere in `web-mode` so I wonder if this isn't actually a spacemacs bug and secondly I wonder if I shouldn't technically be using `web-mode` as it's not actually a layer?

Thanks for your help

Will

**Comment by Compro-Prasad** [comment]
![screenshot from 2018-05-24 00-01-15](https://user-images.githubusercontent.com/11143962/40443991-a8ee60e8-5ee5-11e8-9106-c9115067004f.png)

**Comment by williamchanter** [comment]
Hi, So I've nuked the `~/.emacs.d/elpa` (Just deleted everything inside), it then went through installing and downloading and so on ...

and sadly it has had no effect :cry: 

![alt text](http://i.imgur.com/RjcV371.png)

Thanks for your help with this, any other ideas?

**Comment by Compro-Prasad** [comment]
Why not push your config somewhere so that it can be tested out

**Comment by Compro-Prasad** [comment]
What is the value of `web-mode-hook`?

**Comment by williamchanter** [comment]
Okay well ... I may have found some of the issue ... hyperbole !

So I was going back down the list of installed packages and stuff which I had installed outside of spacemacs with my own custom layers. The only one which was always running was hyperbole.

So when I remove hyperbole I don't get the highlighted errors which is nice but I do still get `Search failed: there is an unmatched expression somewhere or we are at the beginning/end of file.`.

Also here's my config https://gist.github.com/williamchanter/98553667a08d92b51fc7bb531a2776d3 

I guess it'd be nice to be able to run hyperbole still but I suspect that will take some digging to find the conflict, but I'm still a little confused why the error message still pops up :disappointed:

**Comment by williamchanter** [comment]
`web-mode-hook` has this ...
```lisp
web-mode-hook is a variable defined in ‘web-mode.el’.
Its value is
(#[nil "\303\304\305#\210\303\306\307#\210\303\310\311#\210\303\312\313#\210\303\314\315#\210\303\316\317#\210\303\320\321#\210\322\301!\210\323\324\n\325\326#\207"
       [web-mode-syntax-table sentence-end web-mode-map modify-syntax-entry 60 "(>" 62 ")<" 123 "(}" 125 "){" 34 "\"" 61 "." 46 "_" make-local-variable "\\([^ 	\n
>]<\\|>\\(<[^>]*>\\)*\\|[.?!][]\"')}]*\\($\\| $\\|	\\|  \\)\\)[ 	\n]*" define-key "." hui-select-goto-matching-tag]
       4]
 spacemacs/toggle-smartparens-off turn-on-evil-matchit-mode emmet-mode drupal-mode-bootstrap spacemacs//init-company-web-mode spacemacs//init-company-vars-web-mode company-mode)


  This variable may be risky if used as a file-local variable.

Documentation:
Hook run after entering Web mode.
No problems result if this variable is not bound.
‘add-hook’ automatically binds it.  (This is true for all hook variables.)
```

**Comment by williamchanter** [comment]
So after taking a closer look, it does certainly seem somehow hyperbole was causing the highlighting. With that layer turned off there is no highlighting errors. However the issue does still seem to be there ...

![issue still there](http://i.imgur.com/MoNd7Qy.png)

**Comment by williamchanter** [comment]
Okay so after more package debugging with `hyperbole` disabled, it has become clear the warning is coming from `smartparens` . So the current situation: 

| Disabled | Enabled | Issues |
| --- | --- | --- |
| smartparens + hyperbole | | No error message and no hightling error * | 
| smartparens | hyperbole | No error message but get highlighting error * |
| | smartparens + hyperbole | Get error message and get highlighting error | 

*Not ideal as don't get parens matching 

I'm now thinking the issue may lie within `smartparens`

**Comment by Compro-Prasad** [comment]
For me, `web-mode-hook` is `(er/add-html-mode-expansions er/add-web-mode-expansions spacemacs/toggle-smartparens-off turn-on-evil-matchit-mode emmet-mode drupal-mode-bootstrap spacemacs//init-company-web-mode spacemacs//init-company-vars-web-mode company-mode)`

**Comment by williamchanter** [comment]
:cry: hmmmmm

well yep mine doesn't look right ... interestingly if I uninstall `hyperbole` then it is:

```lisp
(spacemacs/toggle-smartparens-off turn-on-evil-matchit-mode emmet-mode drupal-mode-bootstrap spacemacs//init-company-web-mode spacemacs//init-company-vars-web-mode company-mode)
```
with `hyperbole` installed it is this:
```lisp
(#[nil "\303\304\305�#\210\303\306\307�#\210\303\310\311�#\210\303\312\313�#\210\303\314\315�#\210\303\316\317�#\210\303\320\321�#\210\322\301!\210\323�\324\n\325\326#\207"
       [web-mode-syntax-table sentence-end web-mode-map modify-syntax-entry 60 "(>" 62 ")<" 123 "(}" 125 "){" 34 "\"" 61 "." 46 "_" make-local-variable "\\([^ 	\n
>]<\\|>\\(<[^>]*>\\)*\\|[.?!][]\"')}]*\\($\\| $\\|	\\|  \\)\\)[ 	\n]*" define-key "�." hui-select-goto-matching-tag]
       4]
 spacemacs/toggle-smartparens-off turn-on-evil-matchit-mode emmet-mode drupal-mode-bootstrap spacemacs//init-company-web-mode spacemacs//init-company-vars-web-mode company-mode)
```

**Comment by williamchanter** [comment]
By no means an expect but this is evidently where the `hyperbole` makes the change, https://github.com/rswgnu/hyperbole/blob/master/hui-select.el#L300-L311 

Do you think that might be the issue?

**Comment by Compro-Prasad** [comment]
Seems like it is an issue with `hyperbole` then. Try opening an issue there.

**Comment by williamchanter** [comment]
Yeah it is :frowning_face: I'll see what hyperbole think 

Thanks again though for the help though

**Comment by Compro-Prasad** [comment]
Consider closing this issue, if possible.

**Comment by williamchanter** [comment]
Yep this clearly isn't an issue with spacemacs, thanks for the help though

**Comment by williamchanter** [comment]
So for future reference I have a very very very bodged fix which seems to have limited effect on functionality...

1. This removes the error on `Search failed: there is an unmatched expression somewhere or we are at the beginning/end of file. [2 times]` which was mentioned in here http://web-mode.org with regards to smartparens: 
```lisp
(defun my-web-mode-hook ()
  (setq web-mode-enable-auto-pairing nil))

(add-hook 'web-mode-hook  'my-web-mode-hook)

(defun sp-web-mode-is-code-context (id action context)
  (and (eq action 'insert)
       (not (or (get-text-property (point) 'part-side)
                (get-text-property (point) 'block-side)))))

(sp-local-pair 'web-mode "<" nil :when '(sp-web-mode-is-code-context))
(sp-local-pair 'web-mode "<(" ")>")
```   
2. This removed the extra highlighting from web-mode by commenting out code from `hyperbole` in `hui-select.el`:
```lisp
  (var:add-and-run-hook 'web-mode-hook
			(lambda ()
			  ;; (modify-syntax-entry ?<  "(>" web-mode-syntax-table)
			  ;; (modify-syntax-entry ?>  ")<" web-mode-syntax-table)
			  ;; (modify-syntax-entry ?\{ "\(\}" web-mode-syntax-table)
			  ;; (modify-syntax-entry ?\} "\)\{" web-mode-syntax-table)
			  ;; (modify-syntax-entry ?\" "\"" web-mode-syntax-table)
			  ;; (modify-syntax-entry ?=  "."  web-mode-syntax-table)
			  ;; (modify-syntax-entry ?.  "_"  web-mode-syntax-table)
			  (make-local-variable 'sentence-end)
			  (setq sentence-end "\\([^ \t\n\r>]<\\|>\\(<[^>]*>\\)*\\|[.?!][]\"')}]*\\($\\| $\\|\t\\|  \\)\\)[ \t\n]*")
			  (define-key web-mode-map "\C-c." 'hui-select-goto-matching-tag))))
```
Not a perfect fix but for me makes `web-mode`, `smartparens` and `hyperbole` kinda get along :slightly_frowning_face:
