### ISSUE TITLE
 inferior-haskell-find-haddock is not defind

### ISSUE THREAD

**Issue by Zetagon** [syl20bnr/spacemacs#10720]
#### Description :octocat:
The function inferior-haskell-find-haddock is not defined. That name is what is
bound to ", h d" in the haskell layer, the name does not seem to be mentioned anywhere else

#### Reproduction guide :beetle:
- Start Emacs
- Use `vim` editing mode
- Open a haskell file with haskell layer enabled
- In normal mode press , h d

*Observed behaviour:* :eyes: :broken_heart:
This text is shown in *Messages* buffer and nothing happens.

```Wrong type argument: commandp, inferior-haskell-find-haddock```

*Expected behaviour:* :heart: :smile:
inferior-haskell-find-haddock should execute.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fe7cc15a8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv my-spacemacs-init clojure
     (haskell :variables haskell-completion-backend 'intero haskell-enable-shm-support t haskell-enable-hindent-style "johan-tibell")
     org-rifle org-brain csharp lua ipython-notebook lispy org rust yaml themes-megapack search-engine spotify ranger python javascript typescript html latex auto-completion xkcd c-c++ MyLayer mu4e react helm emacs-lisp git markdown pdf-reference
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     evil-commentary spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by Miciah** [comment]
The command appears to have been removed upstream: https://github.com/haskell/haskell-mode/pull/1543 / https://github.com/haskell/haskell-mode/commit/ca94d814b943afeea5bc418df3773f19be9ac8e3.
