### ISSUE TITLE
Vertical and horizontal are swapped in docs for Window Manipulation Transient State

### ISSUE THREAD

**Issue by jbyler** [syl20bnr/spacemacs#10725]
Currently, the documentation for Window Manipulation Transient State (reached by `<leader>` `w` `.`), in the "Split" column, has the following text:

> [s] vertical
> [S] verti & follow
> [v] horizontal
> [V] horiz & follow

Although spacemacs mostly uses "split window below" and "split window right", which are unambiguous, I assume "vertical" and "horizontal" were chosen here to conserve space.  But "v" for "horizontal" seems backward, and indeed Vim's documentation for `CTRL-W v` says "Like |:split|, but split vertically"

I think that the current behavior is correct (s splits below, and v splits to the right) but the documentation is backwards.  I will submit a PR to fix.

**Comment by syl20bnr** [comment]
:+1:
