### ISSUE TITLE
lus

### ISSUE THREAD

**Issue by naqerf** [syl20bnr/spacemacs#10732]
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

**Comment by Compro-Prasad** [comment]
@naqerf Please edit this issue to be more useful or close it if you are testing it.

**Comment by naqerf** [comment]
Sorry, I have no idea how it was openend,. My bad, closing it.
