### ISSUE TITLE
Add DevDocs.el tool (Emacs fronted for https://devdocs.io/)

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#10739]
> [DevDocs.el](https://github.com/xuchunyang/DevDocs.el) this is an Emacs package allowing you to easily search the [DevDocs](https://devdocs.io/) documentation.  

@syl20bnr  Mb we should broaden [Dash](https://github.com/syl20bnr/spacemacs/tree/develop/layers/+tools/dash) into "documentation" layer ?

**Comment by syl20bnr** [comment]
Indeed, tricky part is to chose a good name for it.

**Comment by JAremko** [comment]
@syl20bnr  Yeah "help" or "documentation" layer may be misinterpreted. How about "Codex"?  At least it's not misleading and associated with "reading books".

**Comment by JAremko** [comment]
Or... "RTFM"  layer ? :shipit:

**Comment by syl20bnr** [comment]
:-)

docrefs ? refdocs ? reference_docs ? reference_documentation ?

Is that focused on language references ?

**Comment by JAremko** [comment]
fixed in #10739
