### ISSUE TITLE
Jump to definition of FFmpeg function

### ISSUE THREAD

**Issue by PiR-P** [syl20bnr/spacemacs#10740]
Hello, 

I am totally new to Spacemacs and Emacs in general. I have configured Spacemacs as a C++ IDE following [this video][1]. I have included some FFmpeg libraries in a project.

Autocompletion works perfectly well.
Now I'd like to be able to jump to a definition but I don't know how this is done with key bindings in Emacs/Spacemacs. 

Thanks for your help,

  [1]: https://www.youtube.com/watch?v=OjbkCEkboA8

**Comment by sdwolfz** [comment]
Hello @PiR-P, you might find it better to ask questions in the gitter chat: https://gitter.im/syl20bnr/spacemacs instead of opening issues here.
