### ISSUE TITLE
evil-normal-mode error when press *

### ISSUE THREAD

**Issue by XiaoGeMa** [syl20bnr/spacemacs#10747]
#### Description :octocat:
Sometimes number-or-marker-p nil error in evil-normal state 

#### Reproduction guide :beetle:
- Start Emacs
- open a not empty file,press <<*>> ,  sometimes it not act normal spacemacs/enter-ahs-forward 
but has a error in minibuffer. However, I cannot reproduction the problem each time.
When I test in *Message* buffer with such a line below:
 
jit-lock-fontify-now: Wrong type argument: number-or-marker-p, nil 

press * in jit-lock-fontify-now , it reproduces with a much high possibility.

*Observed behaviour:* :eyes: :broken_heart:
in minibuffer a error like
wrong type argument:number-or-marker-p,nil

in *Message* buffer : 
jit-lock-fontify-now: Wrong type argument: number-or-marker-p, nil

and emacs does not act as it should be.

*Expected behaviour:* :heart: :smile:
act normally.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c9e364721)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git org spell-checking syntax-checking latex python lsp ruby erc markdown c-c++)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS CANNOT_DUMP

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  jit-lock--run-functions(3124 3328)
  jit-lock-fontify-now(3124 3493)
  ahs-fontify()
  ahs-highlight("jit-lock-fontify-now" 3473 3493)
  ahs-idle-function()
  ahs-highlight-now()
  (progn (spacemacs/ensure-ahs-enabled-locally) (ahs-highlight-now))
  eval((progn (spacemacs/ensure-ahs-enabled-locally) (ahs-highlight-now)) nil)
  spacemacs/ahs-highlight-now-wrapper()
  (progn (spacemacs/integrate-evil-search t) (spacemacs/ahs-highlight-now-wrapper) (evil-set-jump) (spacemacs/symbol-highlight-transient-state/body) (ahs-forward))
  (if (eq forward spacemacs--ahs-searching-forward) (progn (spacemacs/integrate-evil-search t) (spacemacs/ahs-highlight-now-wrapper) (evil-set-jump) (spacemacs/symbol-highlight-transient-state/body) (ahs-forward)) (progn (spacemacs/integrate-evil-search nil) (spacemacs/ahs-highlight-now-wrapper) (evil-set-jump) (spacemacs/symbol-highlight-transient-state/body) (ahs-backward)))
  spacemacs//quick-ahs-move(t)
  spacemacs/quick-ahs-forward()
  spacemacs/enter-ahs-forward()
  funcall-interactively(spacemacs/enter-ahs-forward)
  call-interactively(spacemacs/enter-ahs-forward nil nil)
  command-execute(spacemacs/enter-ahs-forward)

```
-----------------------------------------------------------------------------------------------------------
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  jit-lock--run-functions(1706 1709)
  jit-lock-fontify-now(1706 1709)
  ahs-fontify()
  ahs-highlight(#("End" 0 3 (fontified t)) 2517 2520)
  ahs-idle-function()
  ahs-highlight-now()
  (progn (spacemacs/ensure-ahs-enabled-locally) (ahs-highlight-now))
  eval((progn (spacemacs/ensure-ahs-enabled-locally) (ahs-highlight-now)) nil)
  spacemacs/ahs-highlight-now-wrapper()
  (progn (spacemacs/integrate-evil-search t) (spacemacs/ahs-highlight-now-wrapper) (evil-set-jump) (spacemacs/symbol-highlight-transient-state/body) (ahs-forward))
  (if (eq forward spacemacs--ahs-searching-forward) (progn (spacemacs/integrate-evil-search t) (spacemacs/ahs-highlight-now-wrapper) (evil-set-jump) (spacemacs/symbol-highlight-transient-state/body) (ahs-forward)) (progn (spacemacs/integrate-evil-search nil) (spacemacs/ahs-highlight-now-wrapper) (evil-set-jump) (spacemacs/symbol-highlight-transient-state/body) (ahs-backward)))
  spacemacs//quick-ahs-move(t)
  spacemacs/quick-ahs-forward()
  spacemacs/enter-ahs-forward()
  funcall-interactively(spacemacs/enter-ahs-forward)
  call-interactively(spacemacs/enter-ahs-forward nil nil)
  command-execute(spacemacs/enter-ahs-forward)
```

**Comment by syl20bnr** [comment]
I believe I noticed this kind of inconsistency, not sure this is the
same thing though. All I know is that DWIM `SPC *` does not work I fall
back to selecting the text myself and then `SPC *` and it works.
