### ISSUE TITLE
evil text object evil-pasted does not include the last character

### ISSUE THREAD

**Issue by CeleritasCelery** [syl20bnr/spacemacs#10741]
#### Description :octocat:
evil text objected `evil-pasted` does not get the last character

#### Reproduction guide :beetle:
- Start Emacs
- yank some text
- paste (`p`)
- `viP`

*Observed behaviour:* :eyes: :broken_heart:
the last character of the paste is not selected

*Expected behaviour:* :heart: :smile:
the last character of the paste is selected 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.12
- Spacemacs branch: master (rev. 6379a22a0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- System configuration features: XPM JPEG TIFF PNG GPM NOTIFY ACL FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11

**Comment by syl20bnr** [comment]
I cannot reproduce it, I'm still on Emacs 25 but on develop branch.

**Comment by syl20bnr** [comment]
Oh.... already fixed by you :-]
