### ISSUE TITLE
Spacemacs GUI freezes when opening java file or synchronizing dotfile

### ISSUE THREAD

**Issue by RantSomeWhere** [syl20bnr/spacemacs#10743]
#### Description :octocat:
Spacemacs (GUI) freezes upon opening a java file. It is completely unresponsive and only reacts to C-g, after which Spacemacs behaves normally again. If a java file is opened again, Spacemacs freezes again. The emacs process has to be terminated with killall or using htop.
If the java layer is removed from the layer list however, or eclim is uninstalled, java files can be opened without any issues.
When Spacemacs freezes, commonly the last message I can see is the following:
```
Auto-evilification could not remap these functions in map 'archive-mode-map'
   - 'archive-chgrp-entry' originally mapped on 'G'
```
Editing the dotfile and synchronizing it with ```SPC-f-e-R``` gives the same issue.

#### Reproduction guide :beetle:
- Start Emacs
- ```SPC-f-f test.java``` OR ```:e test.java``` OR ```SPC-f-e-R```

*Observed behaviour:* :eyes: :broken_heart:
GUI becomes completely unresponsive. It goes back to normal though if C-g is pressed or if either eclim is uninstalled or the java layer is removed.

*Expected behaviour:* :heart: :smile:
Java file is opened in Spacemacs

#### System Info :computer:
- OS: gnu/linux (Arch Linux)
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking java)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

(Note: I am very new to Emacs and am coming from Vim. So bear with me please.)

**Comment by mroh69** [comment]
what happens on develop branch?

**Comment by sdwolfz** [comment]
Hmm.. it might be the same problem as #8654. What I suggest is you try spacemacs develop first. If that is not enough you might need to install emacs 26 from source.

**Comment by 7root** [comment]
Okay, I tried the develop branch, this is what's happening:
```SPC-f-e-R``` thrown this error:
```Warning: some tests failed, check *dotfile-test-result* buffer```
The content of this buffer is the following:
```* Running tests on [[file:/home/dennis/.spacemacs][/home/dennis/.spacemacs]] (v0.0)

* Testing settings in dotspacemacs/layers [[file:/home/dennis/.spacemacs::dotspacemacs/layers][Show in File]]
** TEST: Each path in [[file:/home/dennis/.spacemacs::dotspacemacs-configuration-layer-path][dotspacemacs-configuration-layer-path]] is a string
** TEST: Each path in [[file:/home/dennis/.spacemacs::dotspacemacs-configuration-layer-path][dotspacemacs-configuration-layer-path]] exists in filesystem
** TEST: Each layer in [[file:/home/dennis/.spacemacs::dotspacemacs-configuration-layers][dotspacemacs-configuration-layers]] can be found
*** PASS: helm
*** PASS: auto-completion
*** PASS: emacs-lisp
*** PASS: git
*** PASS: shell
*** PASS: spell-checking
*** PASS: syntax-checking
*** PASS: java
*** PASS: markdown
** RESULTS: [[file:/home/dennis/.spacemacs::dotspacemacs/layers][dotspacemacs/layers]] passed 9 out of 9 tests

* Testing settings in dotspacemacs/init [[file:/home/dennis/.spacemacs::dotspacemacs/init][Show in File]]
** TEST: [[file:/home/dennis/.spacemacs::dotspacemacs-editing-style][dotspacemacs-editing-style]] is 'vim, 'emacs or 'hybrid or and list with `:variable' keyword
*** PASS: vim
** TEST: [[file:/home/dennis/.spacemacs::dotspacemacs-mode-line-theme][dotspacemacs-mode-line-theme]] is 'spacemacs, 'all-the-icons, 'custom, 'vim-powerline or 'vanilla or a list with `car' one of the previous values and properties one of the following: `:separator' or `:separator-scale'
*** FAIL: nil
** TEST: [[file:/home/dennis/.spacemacs::dotspacemacs-auto-save-file-location][dotspacemacs-auto-save-file-location]] is one of 'original, 'cache or nil
*** PASS: cache
** TEST: [[file:/home/dennis/.spacemacs::dotspacemacs-highlight-delimiters][dotspacemacs-highlight-delimiters]] is one of 'all, 'any, 'current or nil
*** PASS: all
** TEST: Each element of [[file:/home/dennis/.spacemacs::dotspacemacs-startup-lists][dotspacemacs-startup-lists]] includes 'recents, 'bookmarks, 'todos, 'agenda or 'projects
*** PASS: (recents . 5)
*** PASS: (projects . 7)
** TEST: Each element of [[file:/home/dennis/.spacemacs::dotspacemacs-startup-lists][dotspacemacs-startup-lists]] list size is a number
*** PASS: (recents . 5)
*** PASS: (projects . 7)
** TEST: [[file:/home/dennis/.spacemacs::dotspacemacs-leader-key][dotspacemacs-leader-key]] is a string
*** PASS: SPC
** TEST: [[file:/home/dennis/.spacemacs::dotspacemacs-emacs-leader-key][dotspacemacs-emacs-leader-key]] is a string
*** PASS: M-m
** TEST: [[file:/home/dennis/.spacemacs::dotspacemacs-major-mode-leader-key][dotspacemacs-major-mode-leader-key]] is a string or nil
*** PASS: ,
** TEST: [[file:/home/dennis/.spacemacs::dotspacemacs-major-mode-emacs-leader-key][dotspacemacs-major-mode-emacs-leader-key]] is a string or nil
*** PASS: C-M-m
** TEST: [[file:/home/dennis/.spacemacs::dotspacemacs-emacs-command-key][dotspacemacs-emacs-command-key]] is a string
*** PASS: SPC
** RESULTS: [[file:/home/dennis/.spacemacs::dotspacemacs/init][dotspacemacs/init]] passed 12 out of 13 tests
```
I don't really understand what I'm supposed to make from that, I am very new here.

Opening a java file automatically installs meghanada, even though eclim is already installed and working. After the installation it throws this error when I open the file
```[2018-05-24 21:39:48,813][INFO ][Main      : 130] Meghanada-Server Version:1.0.3-414af7e
[2018-05-24 21:39:48,843][ERROR][EmacsServe: 369] Catching
java.lang.IllegalArgumentException: Project Not Found
	at meghanada.session.Session.lambda$createSession$0(Session.java:105) ~[meghanada-1.0.3.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:397) ~[?:?]
	at meghanada.session.Session.createSession(Session.java:105) ~[meghanada-1.0.3.jar:?]
	at meghanada.session.Session.createSession(Session.java:97) ~[meghanada-1.0.3.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:363) [meghanada-1.0.3.jar:?]
	at meghanada.Main.main(Main.java:132) [meghanada-1.0.3.jar:?]
[2018-05-24 21:39:48,866][INFO ][Main      :  69] shutdown server
[2018-05-24 21:39:48,873][INFO ][Config    : 198] memory usage (used/total/max): 16.00MB / 128.00MB / 752.00MB
```

**Comment by sdwolfz** [comment]
Put this in your layer's list instead of the current `java` value.

```emacs-lisp
(java :variables java-backend 'eclim)
```

Also when you swithc branches you should probably restart emacs instead of reloading the config. You probably want to do `SPC f e D` as well and merge the new options. A lot of things changes on develop since the last master release. You can find the entire documentation at: http://develop.spacemacs.org

**Comment by 7root** [comment]
I replaced said line. The issue persist and Spacemacs becomes unresponsive.
It even freezes at the same error message about the evilification (see OP). I'm starting to suspect that it's an issue with eclim maybe?
I will try to build emacs from source now. The source is humongous though, so it'll take some time.

**Comment by 7root** [comment]
Update: while I clone the repo, I decided to play around a bit more. I successfully opened the file without freezing now. However, it still becomes unresponsive when interacting with eclim in any way:
- Completing after a dot ==> freeze
- compiling / testing ==> freeze
- ```SPC-m-D-s``` (start eclim daemon) ==> freeze
etc.

**Comment by 7root** [comment]
Emacs is done compiling. But no luck, it still freezes. I'm going to open up an issue at the emacs-eclim repo, perhaps they can help

**Comment by 7root** [comment]
Successfully reproduced in a virtual machine (Windows host, Arch guest)
