### ISSUE TITLE
pdumper dump fails if run from emacs started from dumped file on windows 10

### ISSUE THREAD

**Issue by Kethku** [syl20bnr/spacemacs#10754]
#### Description :octocat:
If emacs is run from a pdumped dump, and a dump is started, it fails with error:

Opening dump output: Invalid argument, c:/Users/keith/.emacs.d/.cache/dumps/spacemacs.pdmp

#### Reproduction guide :beetle:
- Build emacs from pdumper branch
- Dump file following instructions in experimental.org
- Run emacs with emacs --dump-file=c:/users/keith/.emacs.d/.cache/dumps/spacemacs.pdmp
- Force dump by pressing <spc> f e R
- Switch to *spacemacs-dumper* buffer and observe failed

*Observed behaviour:* :eyes: :broken_heart:
*spacemacs-dumper* buffer indicates failed dump

*Expected behaviour:* :heart: :smile:
dump succeeds allowing user to restart emacs with new loaded files

Run from Windows10 with emacs built from source from pdumper branch.

**Comment by Compro-Prasad** [comment]
Can you give the specific error message?

**Comment by Kethku** [comment]
I think I did...

Only message I could find is in the *spacemacs-dumper* buffer:
Opening dump output: Invalid argument, c:/Users/keith/.emacs.d/.cache/dumps/spacemacs.pdmp

I'm not sure how to get a more specific message. For what its worth, windows reports no handles on the spacemacs.pdmp file.

**Comment by Kethku** [comment]
...or rather sysinternals handle.exe reports no handles.

**Comment by Compro-Prasad** [comment]
Does `c:/Users/keith/.emacs.d/.cache/dumps/spacemacs.pdmp` exist?

**Comment by Kethku** [comment]
Yup. I ran emacs from it.

Sent from my iPhone

On May 26, 2018, at 2:52 AM, Compro Prasad <notifications@github.com<mailto:notifications@github.com>> wrote:


Does c:/Users/keith/.emacs.d/.cache/dumps/spacemacs.pdmp exist?

**Comment by Compro-Prasad** [comment]
Try `emacs --dump-file c:/users/keith/.emacs.d/.cache/dumps/spacemacs.pdmp`

**Comment by Kethku** [comment]
That works. The issue is dumping the file while running from a dumped copy of emacs.

**Comment by Compro-Prasad** [comment]
AFAIK that won't be required because the next time you use the dump it will be as fast the previous one. Make sure that whatever you need is loaded before hand when you do your first dump. Still you can try:
```
emacs --dump-file c:/users/keith/.emacs.d/.cache/dumps/spacemacs.pdmp --force-dump
```

**Comment by Kethku** [comment]
I think we are miscommunicating...

The issue is once I have run an instance of emacs from a dump with 
emacs --dump-file c:/users/keith/.emacs.d/.cache/dumps/spacemacs.pdmp
and try to dump again usiing Spc f e R which will reload the config and trigger a dump, the dump fails.

I am not having problems running emacs from an already dumped configuration.
I am not having problems dumping emacs when the emacs instance is not started from a dumped file.

Does that make sense? Hopefully this helps clear things up :)

**Comment by Compro-Prasad** [comment]
IMO @syl20bnr can provide with a better explanation. After all he has written the code for dumping the config. From what I discussed on gitter it seems that spacemacs dumps only when any layer has changed.

**Comment by syl20bnr** [comment]
Yes this makes sense.

When Emacs is running from a dump, are you able to rename the
dump file in the Windows file explorer ?

If it works we could dump in a temporary file and then rename the files
if the dump succeded.

But maybe the issue is that redumping from a dump does not work somehow
in Windows, I'm pretty sure it does work on MacOS, I'll have to retest
it to confirm though.

**Comment by Kethku** [comment]
Yes that works. I think your solution is a good one. Any pointers on where I should make that change for a PR?
