### ISSUE TITLE
help: how to global-set-key C-z

### ISSUE THREAD

**Issue by jiaqifeng** [syl20bnr/spacemacs#10768]
I just want to re-define C-z as a new map for my function, but below does not work:

(define-prefix-command 'ctl-z-map)
(global-set-key (kbd "C-z") 'ctl-z-map)
(global-set-key (kbd "\C-z\C-a") 'copy-line)

C-z always bind to evil-exit-emacs-state. I search the issues but could not find any answer. What should I do?

**Comment by shwsun** [comment]
I am not sure this will work, but can you try this?
```elisp
;; evil hack
(define-key evil-normal-state-map (kbd "C-z") nil)
```
The primary issue you are facing are probably because `evil mode` works differently then the usual Emacs so you need to search for solution for `evil` + Emacs. To set up customized keybinding, you can try this:
```elisp
(with-eval-after-load 'rust-mode
  (add-hook 'rust-mode-hook (lambda() (define-key evil-normal-state-local-map
                                          (kbd "C-M-i")
                                          #'completion-at-point))))
```

**Comment by jiaqifeng** [comment]
I placed below into user-init and worked.
(setq evil-toggle-key "C-~")

**Comment by sdwolfz** [comment]
Personally I've remapped it to `M-z` since it's easier to type and it's kind of in the same area as far as muscle memory is concerned.
