### ISSUE TITLE
live-py-mode does not respect currently active virtualenv

### ISSUE THREAD

**Issue by skebanga** [syl20bnr/spacemacs#10763]
#### Description :octocat:
python layer

`live-py-mode` does not respect currently active virtualenv

#### Reproduction guide :beetle:
- Start Emacs
- Activate pipenv virtualenv (`pipenv-activate` / `SPC m v p a`).
- Enter live-py mode (`live-py-mode` / `SPC m l`)
- import module which is installed in virtualenv
- import fails

*Observed behaviour:* :eyes: :broken_heart:
imports of modules in virtualenv fail

Note that if I execute a local file (`python-execute-file-focus` / `SPC m c C`) the code runs inside my virtualenv, and works as expected 

*Expected behaviour:* :heart: :smile:
imports of modules in virtualenv succeed

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b68bd33a1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp html javascript go lua octave csv git markdown neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      imenu-list version-control
      (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
      (ranger :variables ranger-show-literal nil)
      python yaml lori-cpp
      (smart-tabs :variables smart-tabs-default-insinuations
                  '(c c++))
      protobuf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Compro-Prasad** [comment]
Might be an issue with either `pipenv-mode` or `live-py-mode`. Try referencing this issue there too. It may so happen that you might get an answer or either of them fixes it.

**Comment by durantschoon** [comment]
I added this to my dotspacemacs/user-config, so as long as my python executable is pointing to the correct python3 vs. python2 in my virtual env this seems to be working.

```elisp
  (add-hook 'live-py-mode-hook (lambda ()
                                 (progn
                                   (setq-default live-py-version (executable-find "python"))
                                   (live-py-update-all))))
```
