### ISSUE TITLE
Region face invisible in Wombat theme

### ISSUE THREAD

**Issue by tsoernes** [syl20bnr/spacemacs#10766]
#### Description :octocat:
Region face invisible in Wombat theme

#### Reproduction guide :beetle:
- Start Emacs
- Use 'wombat' theme
- Enter visual mode and mark a word on the line
- Can't distinguish visual selection highlight from current-line highlight

*Observed behaviour:* :eyes: :broken_heart:
Can't observe it; that's the problem!

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8f8248615)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(graphviz yaml javascript python latex bibtex shell-scripts helm auto-completion better-defaults emacs-lisp git markdown org spell-checking syntax-checking
          (haskell :variables haskell-process-type 'stack-ghci)
          (python :variables python-enable-yapf-format-on-save t)
          (latex :variables latex-build-command "LatexMk")
          (python :variables python-sort-imports-on-save t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by tsoernes** [comment]
@Compro-Prasad I might be mistaken, but I think that's the only theming I've got going on. I have attached my dotfile
[dotspacemacs.txt](https://github.com/syl20bnr/spacemacs/files/2048048/dotspacemacs.txt)

**Comment by Compro-Prasad** [comment]
![screenshot from 2018-05-29 17-44-10](https://user-images.githubusercontent.com/11143962/40658158-f0fe6334-6367-11e8-8149-632a28c6817f.png)

**Comment by tsoernes** [comment]
Is that with the region face set to gold background? The issue is that
setting the region face is necessary in the first place, lest its not
visible.

2018-05-29 14:14 GMT+02:00 Compro Prasad <notifications@github.com>:

**Comment by tsoernes** [comment]
You have to remove the last line which is a workaround to the problem im
describing
