### ISSUE TITLE
Customize-face resets after package update

### ISSUE THREAD

**Issue by tsoernes** [syl20bnr/spacemacs#10767]
#### Description :octocat:
Customize-face resets after package update

#### Reproduction guide :beetle:
- Start Emacs
- Customize a face
- Observe that it works (becomes present in dotfile)
- Update packages
- Restart
- Face customization gone (from dotfile too)

*Observed behaviour:* :eyes: :broken_heart:
- Face customization gone

*Expected behaviour:* :heart: :smile:
- Face customization not gone

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8f8248615)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(graphviz yaml javascript python latex bibtex shell-scripts helm auto-completion better-defaults emacs-lisp git markdown org spell-checking syntax-checking
          (haskell :variables haskell-process-type 'stack-ghci)
          (python :variables python-enable-yapf-format-on-save t)
          (latex :variables latex-build-command "LatexMk")
          (python :variables python-sort-imports-on-save t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by syl20bnr** [comment]
If you don't update the packages before the restart, does it correctly
save the customized faces ?

It might be a tricky bug to solve. Handling customize in a sane maner is
still a work in progress.

**Comment by tsoernes** [comment]
Yes.

2018-06-03 8:43 GMT+02:00 Sylvain Benner <notifications@github.com>:

> If you don't update the packages before the restart, does it correctly
> save the customized faces ?
>
> It might be a tricky bug to solve. Handling customize in a sane maner is
> still a work in progress.
>

**Comment by rpls** [comment]
For me, all customizations reset when packages are installed, for example, after restarting emacs when I update all packages, or when I add/remove a layer. The `dotspacemacs/emacs-custom-settings` is blank (appart from the `package-selected-packages` variable) after packages are installed. Current work-arround is to backup the dotfile and copy over the old `dotspacemacs/emacs-custom-settings` after package update (save the the `package-selected-packages` value). Other work-arround i've found is to call `customize-save-customized` right after packages are installed (I guess the customization is still in memory and get saved again?). This only affects `develop`.
