### ISSUE TITLE
Magithub sections not added to Magit unless it's explicitly loaded first

### ISSUE THREAD

**Issue by marienz** [syl20bnr/spacemacs#10760]
#### Description :octocat:
Magithub sections are not added to Magit unless it's explicitly loaded first (either explicitly or by calling some autoloaded function from it).

#### Reproduction guide :beetle:
- Start Spacemacs (develop branch) with the git and github layers enabled
- Open a Magit status buffer (`SPC f e i SPC g s` opens one for Spacemacs)
- Kill the status buffer
- `(require 'magithub)`
- Open the same Magit status buffer again

*Observed behaviour:* :eyes: :broken_heart:
Magit status buffer does not have Magithub's sections added to it the first time, but does the second time.

*Expected behaviour:* :heart: :smile:
Magit behaves the same way both times.

I tried removing the `:defer t` from `use-package magithub` (to make it more like the [Magithub quickstart](https://github.com/vermiculus/magithub#quick-start)). That seems to work: it doesn't load magit when I start Spacemacs, but it does load Magithub along with Magit. But I don't know if that's the correct Spacemacsy way of doing it :)

Macro-expanding the `use-package` call as Spacemacs has it confirms the `magithub-feature-autoinject` call ends up in `eval-after-load 'magithub`, which defeats its purpose.

I did not see the same problem on one of my other systems, where I had not updated packages for a while. I suspect `use-package`'s behavior changed.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b68bd33a1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(ivy git github emacs-lisp)
```
- System configuration features: XAW3D XPM JPEG TIFF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 THREADS LIBSYSTEMD LCMS2

**Comment by Miciah** [comment]
I think deleting `:defer t` so that Magithub loads when Magit loads is the best solution.  `magithub-feature-autoinject` is nontrivial—it hooks MagitHub into Magit in several ways (adding an action to a popup, adding a binding to one of Magit's key maps, and hooking into the status buffer)—so trying to do anything more nuanced would be much pain for little gain.

#11071 makes this change.

**Comment by marienz** [comment]
Thanks for the reminder, github-actions bot!

magithub was removed from Spacemacs in 79279f434b5af6a959a71fccebe6d042d5c90e93, so this issue no longer applies. Closing.
