### ISSUE TITLE
powerline-height is no longer applied correctly

### ISSUE THREAD

**Issue by Alexander-Miller** [syl20bnr/spacemacs#10764]
#### Description :octocat:

`powerline-height` is no longer properly obeyed since commit 378392e7cd513c8ab5fe800f224ed717a52eab39, not even if you redefine `spacemacs/compute-mode-line-height` to return a static value. 

#### Reproduction guide :beetle:
- Start Emacs
- (setq powerline-height 30)

*Observed behaviour:* :eyes: :broken_heart:
The modeline erratically changes its height. It looks like it depends on what the position indicator displays. For me the height appears to revert to its default value mostly when the indicator says "Bottom".

*Expected behaviour:* :heart: :smile:
Modeline consistenly retains its set height. I don't know if spaceline obeying powerline-height is intentional or merely accidential, but if it's the latter I think there should be a `dotspacemacs-modeline-height` option.

And don't mind my local branch, it's the same on the most recent develop.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: treemacs (rev. 6484dbe74)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil ...)
 better-defaults emacs-lisp finance git helm html markdown org python ...)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 LIBSYSTEMD LCMS2

**Comment by syl20bnr** [comment]
I was able to reproduce it only when utf-8 separator is used. I pushed a
fix for this to force the scaling to be 1.

For your issue I suggest you to use `:separator-scale` keyword instead
of setting `powerline-height`.

For instance:

```elisp
   dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 1.8)
```

**Comment by Alexander-Miller** [comment]
Using separator-scale works :+1:

**Comment by lvh** [comment]
Can we reopen this? It's great that we identified a workaround and hence a probable root cause, but it'd be neat if the workaround wasn't required and this Just Worked(TM) :)
