### ISSUE TITLE
Loading Portable dumper file causing segmentation falut

### ISSUE THREAD

**Issue by braineo** [syl20bnr/spacemacs#10770]
#### Description :octocat:

Loading Portable dumper file causing segmentation falut

#### Reproduction guide :beetle:
- Start Emacs
- Restore dot file to template setting and change dotspacemacs-editing-style to anything but `vim`
- Force dump
- Start with --dump-file

*Observed behaviour:* :eyes: :broken_heart:
`Fatal error Fatal error 11: Segmentation fault[1]    53971 abort      /usr/local/bin/emacs`

*Expected behaviour:* :heart: :smile:
Emacs starts in 0.5s loading everything for me

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2cbc48d0a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree)
```
- System configuration features: RSVG IMAGEMAGICK DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS CANNOT_DUMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Compro-Prasad** [comment]
This seems more of an Emacs problem rather than a spacemacs problem. The problem with pdumper is that it is not in master branch of Emacs yet and thus doesn't get updated.

**Comment by syl20bnr** [comment]
I can reproduce it. Not sure when I can work on this though :(
I'll try to give it a shot next week.

**Comment by braineo** [comment]
Thank you very much!

**Comment by et2010** [comment]
Is there a way to switch to hybrid style after dumping?

**Comment by et2010** [comment]
A workaround for this issue:

Put following lines in your user-config

```
  ;; Setup hybrid mode here due to known issue
  (setq hybrid-style-enable-hjkl-bindings t)
  (setq hybrid-style-visual-feedback t)
  (setq hybrid-style-use-evil-search-module t)
  (spacemacs/toggle-hybrid-mode-on)
```

**Comment by syl20bnr** [comment]
I pushed a fix to delay the hybrid and holy modes configuration until after the dump is loaded. Seems to do the trick.

**Comment by syl20bnr** [comment]
Closing as it should be fixed.
