### ISSUE TITLE
ansi-term scrolling

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#10779]
After updating to Emacs 26.1 I can't scroll on ansi-term.
In normal mode `j`, `k` don't seem to work anymore.

Any thoughts on this?

**Comment by jvillasante** [comment]
I don't know if #10844 is merged or not, but on latest develop this issue has not been fixed yet.

**Comment by akirakyle** [comment]
[In Emacs 26.1 the behavior of `term-char-mode` was changed](https://emacs.stackexchange.com/questions/44270/previous-line-function-in-term-char-mode), specifically `term-char-mode-point-at-process-mark` was introduced which keeps the point always on the current shell line. As a result any movement commands would be undone, even the built in `previous-line` which is what evil calls. So to go back to the previous behavior, just set `(setq term-char-mode-point-at-process-mark nil)`

The solution in #10844 breaks some things like pasting and doesn't work with my workflow of toggling between emacs state and normal mode.

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
shell: allow evil normal-mode movement in terminal buffer #12591
