### ISSUE TITLE
emacs-mac 26.1 + spacemacs hangs installing org-plus-contrib

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#10784]
#### Description :octocat:
On macos (High Sierra 10.13.4) fresh install of
* railwaycat/emacs-mac (emacs-26.1-z-mac-7.0)
* spacemacs develop (https://github.com/syl20bnr/spacemacs/commit/c7a103a772d808101d7635ec10f292ab9202d9ee)

hangs with beachball when trying to install `org-plus-contrib`

Observed originally when trying to upgrade (working) emacs-mac 25.3.3 installation but able to reproduce with fresh install.

#### Reproduction guide :beetle:
1. `brew tap railwaycat/emacsmacport`
1. `brew install emacs-mac`
1. `git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d`
1. Start Emacs
1. select defaults ('vim' and 'spacemacs') in the startup wizard

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs starts installing 103 packages. Some, not many, succeed. While installing `org-plus-contrib` gets stuck showing the macos beachball of death and never finishes. Killing emacs and retrying doesn't make a difference, still gets stuck with org-plus-contrib.

*Expected behaviour:* :heart: :smile:
Spacemacs home buffer.

**Comment by CeleritasCelery** [comment]
Might be related to #10251

**Comment by tko** [comment]
I can confirm installing org-plus-contrib manually fixes that. Then it gets stuck beachballing with another package or two (counsel-projectile) but after a while the installation completes.

Trying from scratch again it appears that even though emacs is totally frozen and shows now updates while installing org-plus-contrib it does actually continue installing packages. After a while (10 minutes or so, guess I was too hasty with the beachball) the installation completes with error
```
An error occurred while installing org-plus-contrib (error: (args-out-of-range #<killed buffer> 3730433 4695646))
```
and `*Messages*`
```
(Spacemacs) --> installing package: org-plus-contrib@spacemacs-org... [9/103]
Contacting host: orgmode.org:443 [2 times]
Opening TLS connection to ‘orgmode.org’...
Opening TLS connection with ‘gnutls-cli --x509cafile /etc/ssl/cert.pem -p 443 orgmode.org’...done
Opening TLS connection to ‘orgmode.org’...done
Parsing tar file...
Warning: premature EOF parsing tar file
Extracting org-plus-contrib-20180528/README_ELPA
Wrote /Users/tko/.emacs.d/elpa/26.1/develop/org-plus-contrib-20180528/README_ELPA
[...]
Wrote /Users/tko/.emacs.d/elpa/26.1/develop/org-plus-contrib-20180528/org-wl.el
Extracting org-plus-contrib-20180528/org.el
(Spacemacs) Error: 
An error occurred while installing org-plus-contrib (error: (args-out-of-range #<killed buffer> 3730433 4695646))
```
and the org-plus-contrib-20180528 directory remains but does not contain all the files.

**Comment by tko** [comment]
An old issue about incomplete org tarball: #4000

**Comment by tko** [comment]
I suspect the premature EOF is related to the package file sizes as `org-plus-contrib` and `tide` are two of the three largest packages according to spacelpa:
```
21752	fsharp-mode-20171021.431.tar
11352	tide-20171009.1142.tar
7120	org-plus-contrib-20171023.tar
6412	auctex-11.91.0.tar
5972	org-20171023.tar
```
large package size -> longer download time and more prone to network failures and/or timeouts.

And the bigger the package, the longer emacs remains totally unresponsive?

**Comment by syl20bnr** [comment]
That's tricky to fix this, I cannot reproduce it.

Actually there is high chance this is a bug in Emacs download code.
We have also issues with using Emacs built-in function to download the
spacelpa archive which prevent me from releasing 0.300. I think we will
fallback on curl for this. But for packages, this is done by package.el
source code which obviously uses Emacs internal functions to download to
archives.

**Comment by bleggett** [comment]
I cannot reproduce this using `railwaycat/emacs-mac (emacs-26.1-z-mac-7.0)`

**Comment by bleggett** [comment]
Alright, I do see it happening now. It might have something  to do with TLS, not sure, that's the step it hangs on anyway.

It eventually will unfreeze and complete the org install, it just freezes for a good several minutes.

**Comment by inflation** [comment]
Very interesting, manually `package-install` worked fine but spacemacs struggled downloading the package.

**Comment by razzmatazz** [comment]
This appears to be related to railwaycat/emacs-mac.

When using regular emacs from homebrew this issue is not triggered.

**Comment by tko** [comment]
@razzmatazz Agreed. I've been running newer version of emacs-mac (emacs-26.1-z-mac-7.4) for some time now and I've noticed `org-plus-contrib` and/or `tide` haven't been causing any problems with package updates lately.

**Comment by Compro-Prasad** [comment]
@tko So, is it fixed? Can we lose this?

**Comment by ivar** [comment]
FWIW - I just got this today (March 4, 2019):
`An error occurred while installing org-plus-contrib (error: (args-out-of-range #<killed buffer> 5586945 5638792))`

on osx, using:
```
~/.emacs.d ❯❯❯ brew info emacs-mac                                                                                   develop
railwaycat/emacsmacport/emacs-mac: stable emacs-26.1-z-mac-7.4, HEAD
YAMAMOTO Mitsuharu's Mac port of GNU Emacs
https://www.gnu.org/software/emacs/
/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.3 (4,009 files, 115MB)
  Built from source on 2018-11-12 at 20:57:45
/usr/local/Cellar/emacs-mac/emacs-26.1-z-mac-7.4 (64B)
  Built from source
From: https://github.com/railwaycat/homebrew-emacsmacport/blob/master/Formula/emacs-mac.rb
```

**Comment by tko** [comment]
@ivar if I'm reading the brew info output correctly it seems you have `mac-7.3` currently installed. As I recall I had that version, and the update problems, for a long while (the cask was lagging behind) but once I updated to `mac-7.4` the problems seem to have gone away.

**Comment by avit** [comment]
I still have the problem with `mac-7.4`, I suspect a different cause. Could it be the package was manually installed, as described by others?

**Comment by tamasgal** [comment]
I have the same problem with Emacs 26.3 on macOS Catalina (10.15.2) during the installation of Doom Emacs. I tried it already 5 times and it hangs at the same point over and over:

```
░ tamasgal@silverbox:~ took 2m 15s
░ 23:48:03 255 > doom install
Installing Doom Emacs!

> Creating .rc/doom.d/
  ✓ Created .rc/doom.d/
! init.el already exists, skipping
! config.el already exists, skipping
! packages.el already exists, skipping
- Envvar file already exists, skipping
Installing plugins
> Installing & building packages...
  → Cloning org (for org-plus-contrib)...
x There was an unexpected error:
  Type: doom-package-error
  Message:
    Error with packages
  Data:
    "org-plus-contrib"
    (error "Failed to run \"git\"; see buffer *straight-process*")
    "Cloning into '/Users/tamasgal/.emacs.d/.local/straight/repos/org'...
    fatal: https://code.orgmode.org/bzg/org-mode.git/info/refs not valid: is this a git repository?
    "
  Straight output:
    Cloning into '/Users/tamasgal/.emacs.d/.local/straight/repos/org'...
    fatal: https://code.orgmode.org/bzg/org-mode.git/info/refs not valid: is this a git repository?
```
