### ISSUE TITLE
Cannot run any interactive command after visiting a Haskell file with syntax checking enabled

### ISSUE THREAD

**Issue by jbyler** [syl20bnr/spacemacs#10789]
#### Description :octocat:
Cannot run any interactive command after visiting a Haskell file.

#### Reproduction guide :beetle:
- Enable Spacemacs layers "haskell" and "syntax-checking"
- Ensure exec-path does not have `runghc` available
  - `(locate-file "runghc" exec-path)` should return nil
- Start Emacs
- Visit a `.hs` file (Haskell source file)
- Type `M-x` or `M-:` or `SPC b b` or run pretty much any other interactive command

*Observed behaviour:* :eyes: :broken_heart:
Get an error:
```
Error in post-command-hook (global-flycheck-mode-check-buffers): (file-missing "Searching for program" "No such file or directory" "runghc")
```
Emacs is almost completely unusable at this point,
as there is no way to run any interactive command, and I haven't yet found a
workaround other than quitting emacs and restarting it.

*Expected behaviour:* :heart: :smile:
Emacs continues to function, and interactive commands can be run.

*Workaround:*
Turning off syntax checking by default is one way to enable syntax checking for other major modes but avoid it for Haskell.  This also avoids putting `global-flycheck-mode-check-buffers` into the `post-command-hook`, so when the error occurs it doesn't bring down all of emacs.
```
(syntax-checking :variables
    syntax-checking-enable-by-default nil)
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp haskell syntax-checking shell markdown)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

#### Backtrace :paw_prints:
I have been unable to get a backtrace.  I was able to trigger one *not* with `debug-on-error` but with `(setq debug-on-message "Error in post-command-hook")`, however emacs hangs upon entering the debugger.

**Comment by jbyler** [comment]
This is still present on the develop branch as of now, on commit 12a4d63.

**Comment by syl20bnr** [comment]
I don't code in haskell so I don't have an haskell env. ready right now.

`runghc` should be expected to be used with which package/variable ?

**Comment by YellowOnion** [comment]
flycheck-haskell calls runghc if stack.yaml file is not present, otherwise it'll use stack to runghc.

I solved this by creating a stack.yaml in my project, but I'm not sure this is the best solution for everyone.

**Comment by peterhoeg** [comment]
> flycheck-haskell calls runghc if stack.yaml file is not present, otherwise it'll use stack to runghc.

It defaults to ```stack``` followed by ```runghc```:

https://github.com/flycheck/flycheck-haskell/blob/master/flycheck-haskell.el#L76

**Comment by YellowOnion** [comment]
And now I'm getting a similar error trying to get an unrelated .yaml file. Maybe just a bug in upstream flycheck?

**Comment by Atemu** [comment]
This is still an issue. If `runghc` is not present when opening a .hs, nothing works anymore; no syntax highlighting from the major mode, eglot doesn't start automatically anymore if configured to do so etc.

Syntax checking not being able to function should never have this catastrophic of an effect. It should at most complain about it in the message log. I don't even think this warrants a print in the echo area tbh.; it's a minor issue and doesn't necessarily warrant attention from the user (e.g. you're looking at haskell files on a system that doesn't have ghc installed and don't plan on writing any haskell code).

What's even worse, this somehow appears to cause all other buffers to also not function. If I open any file whatsoever after opening a .hs file, it too does not have syntax highlighting until I install `runghc`.  
This is not sane behaviour.

The last part is weirdly non-reproducible depending on if you had other stuff open before. To repro this extremely catastrophic failure mode, you need to open a haskell file first and foremost and then attempt to open any other file.

Edit: Ah, I didn't read properly and it's indeed symptoms of no interactive function working at all, not even `C-h v`.

**Comment by fnussbaum** [comment]
> This is still an issue. If `runghc` is not present when opening a .hs, nothing works anymore; no syntax highlighting from the major mode, eglot doesn't start automatically anymore if configured to do so etc.

I cannot reproduce this using the above recipe. I tested on a default Spacemacs installation with syntax-checking and haskell layers, with and without lsp, up-to-date packages on Emacs 29 and 30, and ghc is not installed.
