### ISSUE TITLE
ReactJS ... line wrapping?

### ISSUE THREAD

**Issue by cinjon** [syl20bnr/spacemacs#10780]
#### Description :octocat:
I'm getting a really weird bug with ReactJS. When I load a file and then type
something, everything is fine. However, as soon as I press enter, what I typed
zooms to the far right side of the page. I know that it goes exactly 80 characters
to the right (with spaces between where it is now and where it was) because I 
have an 80-char demarcating line. 

It's not *actually* there though. I know this because when I hover over the line
again, it returns back to the correct place and when I cat the file, it shows up
in the correct place. It's only there when I am editing the file.

This doesn't seem to apply to other languages.

#### Reproduction guide :beetle:
- Start Emacs
- Navigate to a reactjs file.
- Edit.
- ... This is going to be hard to repro. :(

*Observed behaviour:* :eyes: :broken_heart:
See screenshot.

*Expected behaviour:* :heart: :smile:
Editor works as normal with no drifting of text.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(ruby yaml javascript python markdown ivy emacs-lisp react)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:

![screen shot 2018-05-30 at 2 37 44 pm](https://user-images.githubusercontent.com/615351/40741142-b0194f8a-6418-11e8-9cee-c671009f59fe.png)

**Comment by fiveNinePlusR** [comment]
Can you reproduce this on develop?

**Comment by Miciah** [comment]
Does disabling fill-column-indicator help? See #1950.
