### ISSUE TITLE
powerline symbols are not shown correctly in terminal model

### ISSUE THREAD

**Issue by randomizedthinking** [syl20bnr/spacemacs#10790]
#### Description :octocat:
Some powerline symbols are not shown correctly in terminal mode. On the other
hand, some symbols are rendered correctly.

I have installed and set up the powerline font pack from powerline/fonts.

#### Reproduction guide :beetle:
- Start Emacs
- emacs -nw

*Observed behaviour:* :eyes: :broken_heart:
Some powerline symbols shown as empty boxes.

*Expected behaviour:* :heart: :smile:
These symbols should be shown correctly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv python clojure sql helm emacs-lisp git markdown spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```
![spaceemacs-screenshot](https://user-images.githubusercontent.com/5283430/40861976-e3f9e156-659f-11e8-8d94-88cee248057c.jpg)

**Comment by Compro-Prasad** [comment]
They are not powerline fonts. They are Unicode fonts.

**Comment by randomizedthinking** [comment]
Thanks for pointing out. Do you happen to have a font to recommend for such Unicode fonts?

My search shows that most people use `source code pro`, yet it does not work under terminal.

**Comment by jsoo1** [comment]
@randomizedthinking did setting up your terminal font work for you?

**Comment by randomizedthinking** [comment]
Yes, I use urxvt... it is not easy to set up the UNICODE font. I have two
computers with almost identical configuration. Yet one shows  partial
unicode fonts, and the other one shows nothings. It puzzled me, :).

Thanks for the configuration file. Will try it out when having time.

**Comment by randomizedthinking** [comment]
Hi John, setting up the terminal font does not work at least in my case.
