### ISSUE TITLE
`python-layer` does not recognise `.venv/` virtualenv subdirectory created by pipenv

### ISSUE THREAD

**Issue by skebanga** [syl20bnr/spacemacs#10798]
#### Description :octocat:
`python-layer` does not recognise `.venv/` virtualenv subdirectory created by pipenv

#### Reproduction guide :beetle:
- set `PIPENV_VENV_IN_PROJECT=1` in environment
- create virtualenv using `pipenv`
- start Emacs
- open file in project

*Observed behaviour:* :eyes: :broken_heart:
virtualenv does not automatically activate
```
File mode specification error: (file-error Read error Is a directory /src/proj/.venv)
```

*Expected behaviour:* :heart: :smile:
Recognise that `.venv/` is a virtualenv subdirectory

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b68bd33a1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp html javascript go lua octave csv git markdown neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      imenu-list version-control
      (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
      (ranger :variables ranger-show-literal nil)
      python yaml lori-cpp
      (smart-tabs :variables smart-tabs-default-insinuations
                  '(c c++))
      protobuf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by iafilatov** [comment]
This is because `.venv` is supposed to be a file that contains the path to your virtual env. This isn't configurable at the moment. As a workaround you can try using a different name for the dir, i.e. `_venv` or `.virtualenv`. Then put `/path/to/your/_venv` in `.venv`. Relative path also works.

**Comment by skebanga** [comment]
pipenv doesn't support creating a `.venv` file, it only supports creating a `.venv/` directory.

**Comment by iafilatov** [comment]
[pyvenv wants is to be a file](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/python/README.org#automatic-activation-of-local-pyenv-version). I think the file name should be configurable.

**Comment by svenpanne** [comment]
For a workaround, see #10293.
