### ISSUE TITLE
Should not use number to execute Helm action

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1079]
When I have candidates with number in it, pressing a number key (i.e. 1) executes the action corresponding to that key. We should only do this in Helm microstate.

**Comment by syl20bnr** [comment]
I cannot reproduce it in vim style. It happens only in holy-mode which is strange. I don't see why it happens in emacs state.

**Comment by tuhdo** [comment]
It's easy to reproduce. Just enable `holy-mode` and press `1` in any Helm session. It will execute the first action.

**Comment by syl20bnr** [comment]
Yes that what I wrote. I don't see why it is happening though. I'll have to dig the issue tomorrow.

**Comment by TheBB** [comment]
I can't reproduce this. Since it appeared from discussion that it's easily reproducable I suspect this is fixed. Let me know if not.
