### ISSUE TITLE
Spacemacs Theme out of sync

### ISSUE THREAD

**Issue by NerdsvilleCEO** [syl20bnr/spacemacs#10802]
Is there a way we can change the spacemacs theme to point to the upstream package https://github.com/nashamri/spacemacs-theme? Or should we make a PR to core spacemacs to bring in desired functionality?

https://github.com/syl20bnr/spacemacs/tree/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/core/libs/spacemacs-theme

**Comment by syl20bnr** [comment]
The theme will be updated by @nashamri soon ;-)

**Comment by nashamri** [comment]
Just pushed a PR with the latest updates against the `develop` branch. (https://github.com/syl20bnr/spacemacs/pull/10810)

**Comment by nashamri** [comment]
@NerdsvilleCEO Spacemacs used to point directly at the theme repo. But we've been following this workflow for a while now. Waiting for a good chunk of updates to accumulate at the theme repo, then I push these updates to the `develop` branch of spacemacs. The theme is part of the core libraries currently and this workflow adds some reliability. Please close this issue, if this answers your question :smile:

**Comment by NerdsvilleCEO** [comment]
Ok sounds good :)
