### ISSUE TITLE
install layer "osx" fail on OSX

### ISSUE THREAD

**Issue by weaming** [syl20bnr/spacemacs#10801]
#### Description :octocat:

install layer `osx` fail

#### Reproduction guide :beetle:
- Start Emacs
- append `osx` before the end of `dotspacemacs-configuration-layers`
- `SPC f e R` reload configuration

errors messages:

```
Found 5 new package(s) to install...
--> refreshing package archive: gnu... [1/1]
--> installing package: launchctl@osx... [1/5]
Package launchctl is unavailable. Is the package name misspelled?
--> installing package: osx-dictionary@osx... [2/5]
Package osx-dictionary is unavailable. Is the package name misspelled?
--> installing package: osx-trash@osx... [3/5]
Package osx-trash is unavailable. Is the package name misspelled?
--> installing package: pbcopy@osx... [4/5]
Package pbcopy is unavailable. Is the package name misspelled?
--> installing package: reveal-in-osx-finder@osx... [5/5]
Package reveal-in-osx-finder is unavailable. Is the package name misspelled?
```

and 

```
Error (use-package): osx-trash/:init: Symbol’s function definition is void: osx-trash-setup
Error (use-package): Cannot load osx-trash
```

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git markdown org osx)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

### How do I fix it after asking help on gitter

check the `package-archives` variable in emacs: `C-h v package-archives`

the results is `Its value is (("gnu" . "https://elpa.gnu.org/packages/"))`

```sh
cd ~/.emacs.d
git checkout develop
```
then restart emacs, it will install some packages (100+), and no error message show up!

check `package-archives` again, the results:

```
Its value is
(("melpa" . "http://melpa.org/packages/")
 ("org" . "http://orgmode.org/elpa/")
 ("gnu" . "http://elpa.gnu.org/packages/"))
Original value was 
(("gnu" . "https://elpa.gnu.org/packages/"))
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
Current master branch and Emacs 27 (current in-development version of Emacs) don't work together due to introduction of `early-init.el`. Fixed in develop by #10367.

**Comment by d12frosted** [comment]
@benrki 

Please note that `--with-natural-title-bars` was first renamed and now it has no effect at all. From the `brew info emacs-plus` (the same is shown after you install `emacs-plus`):

```
--natural-title-bar option was removed from this formula, in order to
  duplicate its effect add following line to your init.el file
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (add-to-list 'default-frame-alist '(ns-appearance . dark))
or:
  (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  (add-to-list 'default-frame-alist '(ns-appearance . light))
```

This is just FYI. I just saw that you use unsupported options.

---

Honestly, I doubt that this particular issue is related to building from `HEAD` 😸

**Comment by dijonkitchen** [comment]
I recently added the `osx` layer without problems using the `master` branch and the stable `emacs-plus`.

**Comment by benrki** [comment]
> @benrki
> 
> Please note that `--with-natural-title-bars` was first renamed and now it has no effect at all. From the `brew info emacs-plus` (the same is shown after you install `emacs-plus`):
> 
> ```
> --natural-title-bar option was removed from this formula, in order to
>   duplicate its effect add following line to your init.el file
>   (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
>   (add-to-list 'default-frame-alist '(ns-appearance . dark))
> or:
>   (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
>   (add-to-list 'default-frame-alist '(ns-appearance . light))
> ```
> This is just FYI. I just saw that you use unsupported options.
> 
> Honestly, I doubt that this particular issue is related to building from `HEAD` 😸

@d12frosted 

Sorry, I didn't mean to imply that `HEAD` on emacs-plus is broken, just that `HEAD` installed v27 which has some issues with the `master` version of spacemacs.

Perhaps the README for spacemacs should periodically be updated to install a particular version that is known to work without any issues (instead of `HEAD`).

Thanks for the tip about the natural title bars!

**Comment by d12frosted** [comment]
@benrki 

> Sorry, I didn't mean to imply that HEAD on emacs-plus is broken

Don't worry, I didn't get offended. Sorry that I made you sorry! 😸 

---

> just that HEAD installed v27 which has some issues with the master version of spacemacs.

Well yes. But when one installs something from HEAD, one should expect problems 😸 

> Perhaps the README for spacemacs should periodically be updated to install a particular version that is known to work without any issues (instead of HEAD).

Maybe. On the other side, it's good to get feedback when people try different combinations of Spacemacs and Emacs.

> Thanks for the tip about the natural title bars!

No problem!

**Comment by LucaMarconato** [comment]
@benrki I had the same problem and reinstalling spacemacs without --HEAD solved it. Thanks 🎉
