### ISSUE TITLE
Strange looking of spaceline on emacs-mac-port

### ISSUE THREAD

**Issue by xiangsheng** [syl20bnr/spacemacs#10808]
#### Description :octocat:
Strange looking of spaceline on emacs-mac-port. But, using the same configuration, all things go well on the vanilla emacs for mac. 

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
![pic1](https://user-images.githubusercontent.com/5061641/40975348-3abbf32a-68fd-11e8-9f8d-ddab170c5bba.png)

*Expected behaviour:* :heart: :smile:
![pic2](https://user-images.githubusercontent.com/5061641/40975393-62b6cc06-68fd-11e8-9d58-6f9adbbedf74.png)

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4a9d53578)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp asm osx
      (chinese :variables chinese-enable-fcitx t)
      (latex :variables latex-enable-auto-fill t latex-enable-folding t latex-build-command "LatexMk")
      bibtex html python shell-scripts nginx neotree
      (org :packages
           (not org-projectile))
      (spell-checking :variables ispell-program-name "aspell" ispell-dictionary "american" spell-checking-enable-by-default nil))
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

**Comment by xiangsheng** [comment]
![2018-06-06 8 46 13](https://user-images.githubusercontent.com/5061641/41039038-c607659a-69ca-11e8-80c6-19a62339ac3b.png)
Another curious things, when the window is small enough, the glitch disappears. So maybe having some relations with rescaling?

**Comment by stardisblue** [comment]
it's because of the symbols of the minor-mode
