### ISSUE TITLE
Spacemacs (pdump version) on windows crashes whenever url-retrieve-synchronously is called

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#10804]
#### Description :octocat:
Spacemacs (pdump version) crashes whenever `url-retrieve-synchronously` is called

#### Reproduction guide :beetle:
- Start Emacs
- `M-:` and input `(url-retrieve-synchronously "https://www.gnu.org/software/emacs/manual/html_node/url/Retrieving-URLs.html")`, then just RET

*Observed behaviour:* :eyes: :broken_heart:
Emacs crashed

*Expected behaviour:* :heart: :smile:
Emacs does not crash and `url-retrieve-synchronously` works as expected

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4a9d535)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :disable-for org)
 autohotkey better-defaults chrome csv emacs-lisp
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 git ibuffer imenu-list latex markdown org pdf-tools
 (python :variables python-enable-yapf-format-on-save t)
 ranger semantic
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 shell-scripts
 (spell-checking :variables spell-checking-enable-by-default nil ispell-program-name "aspell")
 syntax-checking templates
 (treemacs :variables treemacs-use-filewatch-mode t treemacs-use-follow-mode t)
 (version-control :variables git-gutter+-disabled-modes
                  '(image-mode org-mode))
 windows-scripts et-goodies et-nl et-org et-python
 (et2010 :variables et2010-prettify-org-src-block nil))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS CANNOT_DUMP LCMS2

#### Backtrace :paw_prints:
No backtrace available

**Comment by robbyoconnor** [comment]
You have to apply a patch to make this work....

**Comment by et2010** [comment]
@robbyoconnor Could you enlighten me? Where can I find the patch?

**Comment by robbyoconnor** [comment]
@et2010 https://github.com/syl20bnr/spacemacs/blob/develop/EXPERIMENTAL.org

**Comment by et2010** [comment]
I use emacs downloaded from this link, I don't know if it was patched or not.

https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27-pdumper/

**Comment by robbyoconnor** [comment]
You still need to apply the change that is documented. Did you read
that? To use this with spacemacs, you need to apply that patch.

**Comment by et2010** [comment]
I compile a patched version, but the issue persists. Any ideas?

![image](https://user-images.githubusercontent.com/11584902/41057910-f834767c-69fa-11e8-91f1-bd4f1142ff26.png)

**Comment by syl20bnr** [comment]
Is that with a spacemacs dump file or does it crash the first time you launch it?

Be sure to have gnutls dynamic library.

**Comment by et2010** [comment]
Yes, it's with a spacemacs dump file dumped by patched emacs 27.0.50 and it crashes every time I call `url-retrieve-synchronously`.

**Comment by Kethku** [comment]
I can reproduce this on my installation as well. Windows 10, emacs 27.0.50

**Comment by Kethku** [comment]
Interestingly enough `(url-retrieve-synchronously "http://google.com")`  does not crash. However, `(url-retrieve-synchronously "https://google.com")` does. This seems to point to the fact that it was an ssl enabled url.

Definitely doesn't happen when running emacs not from a dumped file.

**Comment by Kethku** [comment]
This strikes me as an upstream issue...

**Comment by Kethku** [comment]
Other useful background: Running `(gnutls-available-p)` prints: `(ClientHello\ Padding Session\ Ticket Extended\ Master\ Secret Encrypt-then-MAC ClientHello\ Padding ALPN Heartbeat SRTP Signature\ Algorithms SRP Supported\ ECC\ Point\ Formats Supported\ curves Certificate\ Type OCSP\ Status\ Request Maximum\ Record\ Size Server\ Name\ Indication macs AEAD-ciphers ciphers digests gnutls3 gnutls)`

**Comment by et2010** [comment]
Is there any workaround for this? Lots of extensions rely on this function to fetch data from the web, e.g. some dictionary apps. Those extensions are useless without this function. Maybe we can figure out a patch for this?

**Comment by fuxialexander** [comment]
@et2010 well if those url also live in https form, maybe you can advice around url-retrieve-synchronously to modify the passed url with the string replace..
