### ISSUE TITLE
evil-mode with overwrite mode error on pressing key f

### ISSUE THREAD

**Issue by XiaoGeMa** [syl20bnr/spacemacs#10807]
#### Description :octocat:
overwrite mode error on pressing f

#### Reproduction guide :beetle:
- Start Emacs
open a not empty file
press i into insert mode
press insert into overwrite mode
press f

*Observed behaviour:* :eyes: :broken_heart:
the two charactors under and after the cursor will be replace by f.
if I press any key otherwise, only one charactor under the cursor will be replaced.
I'm not sure it's a bug or something meaningful I don't understand.

*Expected behaviour:* :heart: :smile:
like press other keys.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 24ca355b6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git org spell-checking syntax-checking latex python lsp ruby pass
      (erc :variables erc-enable-sasl-auth t erc-server-list
           '(("irc.freenode.net" :port "6697" :ssl t :nick "XXXX" :password)
             ("irc.gitter.im" :port "6697" :ssl t :nick "XXXX" :password)))
      (chinese :variables chinese-enable-youdao-dict t)
      markdown c-c++)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS CANNOT_DUMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by syl20bnr** [comment]
Can you open an issue upstream here: https://github.com/syl20bnr/evil-escape ?

**Comment by XiaoGeMa** [comment]
I  am a newbie of  github. Did you mean I should copy this issue to evil-escape?
