### ISSUE TITLE
escaping with 'fd' is not relevant when using holy-mode

### ISSUE THREAD

**Issue by nivpgir** [syl20bnr/spacemacs#10817]
#### Description :octocat:
typing 'fd' deletes the characters

#### Reproduction guide :beetle:
- Start Emacs
- go to scratch buffer (or any writeable buffer...)
- type 'fd' quickly

*Observed behaviour:* :eyes: :broken_heart:
'fd' characters get deleted

*Expected behaviour:* :heart: :smile:
'fd' will be typed

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e481894)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(d ruby graphviz
   (c-c++ :variables c-default-style "ellemtel" c-basic-offset 4 c-auto-newline nil)
   c++-rtags cscope shell git
   (org :variables org-src-fontify-natively t)
   (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip nil)
   emacs-lisp csv markdown asciidoc python html helm emacs-lisp niv-layer)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
```

I'm using holy-mode, and while typing "fd" quickly doesn't escape any mode (cause there's no mode to escape), the characters still get deleted, which is very annoying.

I would just type it slowly each time but it happens also when using macros, which
makes it impossible to type those characters one after the other when using a macro.

I get that this makes sense when using evil mode, but shouldn't this at least be
disabled by default when using holy-mode?

**Comment by Miciah** [comment]
This was recently fixed on the develop branch; see https://github.com/syl20bnr/spacemacs/pull/10681.  Your current revision (https://github.com/syl20bnr/spacemacs/commit/e481894fcbbbcfbc8f373bc111db609c9acecb40) is just a little too old to have the fix; can you update and try to reproduce the problem?

**Comment by nivpgir** [comment]
Updated, and indeed the problem is fixed, sorry for the duplicate.
Thank you.

**Comment by syl20bnr** [comment]
Closed as "duplicate" :-)
