### ISSUE TITLE
How to activate erlang relaeases which uses kerl

### ISSUE THREAD

**Issue by ehelaya** [syl20bnr/spacemacs#10816]
Hi,

I'm using [Kerl](https://github.com/kerl/kerl) to mange different erlang versions. whenever i want to use specific version of Erlang I'm activate it using below command

`source /usr/local/lib/erlang-19.3/activate`  

But when start spacemacs and try to use erlang-related packages spacemacs complained that it cannot find erlang in my machine. same goes for the elixir.

is there anyway to activate specific erlang version in spacemacs startup?

**Comment by syl20bnr** [comment]
BTW I would love if someone can submit an Erlang layer maybe based on EDTS, I can help if needed.
