### ISSUE TITLE
Strange behaviour in vim / emacs macros

### ISSUE THREAD

**Issue by geganizharadzeatamido** [syl20bnr/spacemacs#10811]
#### Description :octocat:
Strange behaviour when running specific macro(s). This is happening in a few different modes, but the
ones I've tried were `js-mode`, `text-mode`, `react-mode`.

It seems to be happening when there is a blank space in front of a cursor, so I will include a few
empty spaces in the reproduction guide on purpose.

#### Reproduction guide :beetle:
- Start Emacs
- Open up a scratch buffer in `text-mode`
- Run the following keyboard sequence `O SPC SPC ESC qq i fo ESC q @q`
- Another version of keyboard sequence `O <F3> fo <F4> <F4>`

Here's a screenshot:
https://cl.ly/2c0E023f4230

*Observed behaviour:* :eyes: :broken_heart:
`fofoo`

*Expected behaviour:* :heart: :smile:
`fofo`

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(themes-megapack html yaml javascript react elm
                 (clojure :variables clojure-enable-fancify-symbols t)
                 helm auto-completion emacs-lisp markdown org
                 (shell :variables shell-default-shell 'multi-term shell-default-height 20 shell-default-position 'bottom)
                 version-control mc-column
                 (git :variables git-gutter-use-fringe t)
                 (syntax-checking :variables syntax-checking-enable-tooltips nil))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by syl20bnr** [comment]
Cannot reproduce it in develop branch, I've got the expected result.
Try reinstalling all the packages.

**Comment by syl20bnr** [comment]
Have you tried with develop branch ?

**Comment by geganizharadzeatamido** [comment]
@syl20bnr yes, it's happening on both branches.

I tried it on other machines as well with different steps. i.e. I tried on a machine that has never had Spacemacs on it. Cloned spacemacs, started emacs, went through the initial set up, opened up a file and I could reproduce it straight away.

I also tried the same steps on another machine, but before cloning spacemacs, I first upgraded emacs to the recent version and then did all the above, and it's the same thing.

It's very difficult to determine what's causing it. Here's another screenshot of me recording and executing the same macro over and over again and as you can see, most times I can reproduce it. but sometimes it works fine.

https://cl.ly/1f0S1H2z0R1o

Again, the keyboard sequence what I'm doing there is this (starting off with normal mode):
`qq a fo ESC q @q`
