### ISSUE TITLE
Understanding CHANGELOG.develop

### ISSUE THREAD

**Issue by danielsuo** [syl20bnr/spacemacs#10818]
Hopefully this is a quick one to answer: how should we take the contents of ```CHANGELOG.develop``` versus the ```develop``` branch?

For example, I'm really interested in ```+tools/lsp``` and ```+tools/cmake```, but they aren't listed as new layers in ```CHANGELOG.develop```.

**Comment by syl20bnr** [comment]
`CHANGELOG.develop` is way out of sync with current develop branch, I
have like 30+ commit pages to review to update it :-(

This is time consuming but I will do it at some point, this is roughly
30min per page of commit so it might take a while.

**Comment by danielsuo** [comment]
No worries! Your efforts are much appreciated, just wanted to check.

I have seen other projects require updating changelogs as part of PRs,
though spacemacs isn’t quite so formulaic that this approach works
automatically, but something to consider!
Sylvain Benner <notifications@github.com>于2018年6月7日 周四上午12:47写道：

> `CHANGELOG.develop` is way out of sync with current develop branch, I
> have like 30+ commit pages to review to update it :-(
>
> This is time consuming but I will do it at some point, this is roughly
> 30min per page of commit so it might take a while.
>
>

**Comment by danielsuo** [comment]
Closing.
Daniel Suo <danielsuo@gmail.com>于2018年6月7日 周四上午7:00写道：

> No worries! Your efforts are much appreciated, just wanted to check.
>
> I have seen other projects require updating changelogs as part of PRs,
> though spacemacs isn’t quite so formulaic that this approach works
> automatically, but something to consider!
> Sylvain Benner <notifications@github.com>于2018年6月7日 周四上午12:47写道：
>
>> `CHANGELOG.develop` is way out of sync with current develop branch, I
>> have like 30+ commit pages to review to update it :-(
>>
>> This is time consuming but I will do it at some point, this is roughly
>> 30min per page of commit so it might take a while.
>>
>>

**Comment by syl20bnr** [comment]
>  I have seen other projects require updating changelogs as part of PRs,
> though spacemacs isn’t quite so formulaic that this approach works
> automatically, but something to consider!

We should do this.

**Comment by danielsuo** [comment]
Make the people work!

:)
