### ISSUE TITLE
layer go: add support for golangci-lint

### ISSUE THREAD

**Issue by utrack** [syl20bnr/spacemacs#10825]
Go layer has support for gometalinter, but it has no switch to use golangci-lint (https://github.com/golangci/golangci-lint) instead.
Flycheck already has package `flycheck-golangci-lint`.

**Comment by panchoh** [comment]
This issue was fixed a long time ago in `develop` (see referenced PR above), so I think it should be closed.

**Comment by duianto** [comment]
@panchoh Your right, thanks.

**Comment by dbriemann** [comment]
Sorry to hijack this but I think my question is related to this feature. I configured my spacemacs to use the `golangci-lint`. Now I have the problem, that compiler errors are not correctly shown. If I have no compile errors, the linter works correctly and shows me the linter errors/warnings on the correct lines.

Do I need to set the `go-build` linter before the `golangci-lint` linter? Is that possible? Or is there another recommended way to highlight build errors correctly before using the linter? If I set the linter to `lsp-ui`, build errors are also shown correctly, but is worse than `golangci-lint`.

p.s.
I am on the current develop branch.

**Comment by seriousben** [comment]
I see the same behavior as @dbriemann

**Comment by seriousben** [comment]
Using an official way of installing `golangci-lint` (https://github.com/golangci/golangci-lint#install) seems to work for me now.

```
$ golangci-lint version
golangci-lint has version 1.20.1 built from 849044b on 2019-10-15T19:11:27Z
```
