### ISSUE TITLE
Tab key behaves weirdly in certain layers

### ISSUE THREAD

**Issue by Gigahawk** [syl20bnr/spacemacs#10836]
#### Description :octocat:
Tab key behaves weirdly in certain layers

#### Reproduction guide :beetle:
- Start Emacs
- Open a markdown file
- Press tab (while in insert mode)
- Run `markdown-indent-region` or `markdown-exdent-region`
- Open REPORT_SPACEMACS_ISSUE
- (Optional) Go back to the markdown file
- Press tab (while in insert mode)

*Observed behaviour:* :eyes: :broken_heart:
Before opening the issue reporter, pressing tab while in insert mode does nothing.
If the cursor is somewhere in the middle of the line it will be moved to the beginning of the line.
`markdown-indent-region` and `markdown-exdent-region` do nothing

After opening the issue reporter, pressing the tab key on a line will insert two newlines followed by a tab character, then one more newline, the cursor is placed two lines down after the tab character.
Subsequent presses of the tab key will insert a new line with a tab character between the two 'bounding' newline characters.
`markdown-indent-region` and `markdown-exdent-region` still do nothing

*Expected behaviour:* :heart: :smile:
Pressing the tab key while in insert mode should just insert a tab key

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion html python emacs-lisp pdf-tools
(markdown :variables markdown-live-preview-engine 'vmd)
org latex)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2

**Comment by Gigahawk** [comment]
Not sure if this is relevant but `C-h k TAB` shows:
```
<tab> runs the command orgtbl-hijacker-command-102 (found in orgtbl-mode-map),
which is an interactive Lisp function.

It is bound to <tab>.

(orgtbl-hijacker-command-102 ARG)

In tables, run ‘orgtbl-tab’.
Outside of tables, run the binding of ‘<tab>’ or ‘TAB’.
```

**Comment by syl20bnr** [comment]
Cannot reproduce this on develop branch.

**Comment by antonalekseev** [comment]
Can confirm the issue. In order to workaround it one can disable `org-tbl` mode for `markdown-mode` buffer. However, I have no idea what else could be broken this way.

```
(with-eval-after-load 'markdown-mode (remove-hook 'markdown-mode-hook 'orgtbl-mode))
```

https://github.com/syl20bnr/spacemacs/issues/10949 probably related.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 239f60a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(aaa-lispyville ansible
                (auto-completion :variables spacemacs-default-company-backends
                                 '(company-yasnippet
                                   (company-gtags company-etags company-keywords)
                                   company-files company-dabbrev)
                                 auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual auto-completion-enable-sort-by-usage t auto-completion-idle-delay 2.0)
                bm common-lisp csv dap
                (dash :variables dash-docs-docset-newpath
                      (concat
                       (getenv "HOME")
                       "/Library/Application Support/Dash/DocSets/"))
                docker emacs-lisp fzf
                (gtags :variables gtags-enable-by-default nil)
                git github
                (go :variables go-tab-width 4 godoc-at-point-function 'godoc-gogetdoc go-use-golangci-lint t go-format-before-save t gofmt-command "goimports")
                (html :variables web-fmt-tool 'prettier)
                ipython-notebook ivy
                (json :variables json-fmt-tool 'prettier)
                (lsp :variables lsp-enable-symbol-highlighting nil lsp-ui-sideline-enable nil lsp-ui-doc-enable nil lsp-ui-flycheck-enable nil lsp-auto-guess-root t)
                (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
                neotree
                (javascript :variables javascript-fmt-tool 'prettier javascript-backend 'lsp js2-basic-offset 2 js-indent-level 2)
                markdown
                (org :variables org-confirm-babel-evaluate nil org-bullets-bullet-list
                     '("■" "◆" "▲" "▶"))
                (python :variables python-backend 'lsp python-test-runner 'pytest python-formatter 'black python-auto-set-local-pyenv-version nil python-auto-set-local-pyvenv-virtualenv nil)
                racket restclient aaa-rmsbolt
                (shell :variables shell-default-shell 'eshell shell-default-term-shell "zsh")
                (syntax-checking :variables syntax-checking-enable-tooltips nil)
                theming
                (version-control :variables version-control-diff-tool 'diff-hl)
                yaml)
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP
