### ISSUE TITLE
c-c++ layer and rtags package alternative location

### ISSUE THREAD

**Issue by Mafeuser** [syl20bnr/spacemacs#10839]
what should I put to packages.el in order to have rtags emacs package be downloaded directly from github.

I've tried the following, but it instead clones the whole git repo, then fails and it is not what I need.

```
(rtags :location (recipe :fetcher github :repo "Andersbakken/rtags"))
````

**Comment by bmag** [comment]
You can find the original MELPA recipe here: https://github.com/melpa/melpa/blob/master/recipes/rtags

Your recipe is missing `:files ("src/rtags.el")`.

**Comment by Mafeuser** [comment]
It works for me now.
@bmag, thank You for clarification

regards
