### ISSUE TITLE
Cannot submit spacemacs bug report without markdown layer

### ISSUE THREAD

**Issue by jbyler** [syl20bnr/spacemacs#10833]
#### Description :octocat:
Cannot submit spacemacs bug report without markdown layer

#### Reproduction guide :beetle:
- Start with a .spacemacs configuration that does *not* have the markdown layer enabled
- Start Emacs
- Begin to submit a bug report by typing `<SPC> h I` (spacemacs/report-issue)
- Try to submit the report by typing `C-c C-c` (`spacemacs//report-issue-done` [sic])

*Observed behaviour:* :eyes: :broken_heart:
When starting to report the issue, observe error:
```
let: Symbol’s function definition is void: markdown-mode
```

When submitting the issue, `C-c C-c` is unbound, becuase the mode is `fundamental-mode`.

*Expected behaviour:* :heart: :smile:
The major mode should be the report-issue mode, and `C-c C-c` should open a URL to submit a bug report.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

#### Backtrace :paw_prints:
(none)

**Comment by jbyler** [comment]
I cannot reproduce this on the develop branch, so I believe it is fixed there.  It appears as though the report-issue mode no longer uses markdown mode.

**Comment by AleXoundOS** [comment]
I experience this issue on the master branch.

**Comment by duianto** [comment]
It's been fixed on the develop branch. It will probably be part of the next major release (I don't have any insight into when that is).

This seems to be a workaround on the master branch:
>Meantime, people using the master branch can install the markdown layer or add markdown-mode to dotspacemacs-additional-packages.

source: https://github.com/syl20bnr/spacemacs/issues/7686#issuecomment-403639644

**Comment by AleXoundOS** [comment]
Thank you for such a quick response!
