### ISSUE TITLE
emacs 26 is installed but emacs 27 is searched when SPC f e R

### ISSUE THREAD

**Issue by giuscri** [syl20bnr/spacemacs#10830]
#### Description :octocat:
Reloading .spacemacs make spacemacs search for emacs 27.0.50

#### Reproduction guide :beetle:
- Start Emacs
- `SPC f e R` 

*Observed behaviour:* :eyes: :broken_heart:
`Searching for program: No such file or directory, emacs-27.0.50` is printed in the area below the powerline.

*Expected behaviour:* :heart: :smile:
spacemacs should not search for emacs 27.0.50, as I'm using emacs 26.1

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1833c9c4f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm auto-completion emacs-lisp git neotree
        (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by Compro-Prasad** [comment]
What is the value of `dotspacemacs-enable-emacs-pdumper` in your `.spacemacs`?

**Comment by giuscri** [comment]
```
$ cat ~/.spacemacs |ag pdumper
   dotspacemacs-enable-emacs-pdumper nil
   ;; for the portable dumper (this is currently the branch pdumper).
   dotspacemacs-emacs-pdumper-executable-file "emacs-27.0.50"
```

**Comment by Compro-Prasad** [comment]
@syl20bnr Why is pdumper executable is checked while pdumper(in .spacemacs) is turned off?

**Comment by giuscri** [comment]
This is my .spacemacs, https://gist.github.com/giuscri/3c846332f788d49e9ebe78c0ecdff1d8

Apart from a couple of things switched on/off, I basically never edited it by hand.

**Comment by Compro-Prasad** [comment]
That is fine. Your config still has `emacs-27.0.50` in it. Just search for `emacs-27.0.50` and replace it with `emacs`. The variable name is `dotspacemacs-emacs-pdumper-executable-file`.

**Comment by syl20bnr** [comment]
Has someone reproduced this bug yet ?

**Comment by sdwolfz** [comment]
I am also unable to reproduce this.

**Comment by syl20bnr** [comment]
Thank you for the report and the repro steps. Should be fixed in last develop.

**Comment by Compro-Prasad** [comment]
@giuscri You can pull latest changes on develop, recheck and close this issue when you have time.

**Comment by giuscri** [comment]
as of f1f8db002af108f58c9a78c5286e8beca59af6de this is fixed.
