### ISSUE TITLE
Spacemacs buffer is not usable in holy-mode right now

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1083]
Just a reminder from the discussion in this PR: https://github.com/syl20bnr/spacemacs/pull/1070

To solve it, simply bind `widget-button-press` or `evil-ret` to `RET` and `evil-mouse-drag` to left mouse click.

**Comment by syl20bnr** [comment]
What do you mean by "Spacemacs is not usable" ? I just tried in emacs style and Spacemacs works great.
Do you mean that the widgets on the spacemacs buffer cannot be activated ?

**Comment by tuhdo** [comment]
Opss sorry for the misleading title. I meant "Spacemacs buffer", not Spacemacs :)

Currently the widgets are not usable as stated in the PR.

**Comment by tuhdo** [comment]
And yes, `holy-mode` is very usable now. I enjoy it everyday.

**Comment by syl20bnr** [comment]
Ouf I'm relieved :-)

**Comment by tuhdo** [comment]
@syl20bnr Just a reminder since you already merged the change log PR that there's an issue with `holy-mode`, in case you forgot.
