### ISSUE TITLE
Helm window overrides text-scale of current window

### ISSUE THREAD

**Issue by mmcnl** [syl20bnr/spacemacs#1084]
Steps to Reproduce:

1. Run ```text-scale-increase``` three times in window 1
2. Notice font size increases and +3 for text-scale in shown in mode line
3. Open a helm window (eg with SPC b s)

Expected behavior:
Window 1 font size remains at +3

Actual behavior:
Window 1 font reverts to normal size but +3 remains for text-scale in shown in mode line
Note: If another text-scale change (up or down) is done, then the font/mode line revert to their correct values

**Comment by syl20bnr** [comment]
Thank you for the report, actually this is ido in your screenshot, not helm ;-)

**Comment by mmcnl** [comment]
Ooops, sorry! But it seems the behavior happens for me with both helm and ido.

Normal scale

![1](https://cloud.githubusercontent.com/assets/1498727/7038804/0e7f9944-dd6c-11e4-8c1c-40f465fcf711.png)

Scale up to +3 and fonts correctly increase in size

![2](https://cloud.githubusercontent.com/assets/1498727/7038806/0e80a30c-dd6c-11e4-9cdf-c7352b2cc7cb.png)

Open a helm/ido window
![2 5](https://cloud.githubusercontent.com/assets/1498727/7038849/76d4832e-dd6c-11e4-83e5-6b03f4faf1d5.png)

See inconsitency between +3 and displayed font size
![3](https://cloud.githubusercontent.com/assets/1498727/7038805/0e80666c-dd6c-11e4-8835-f0c4da46205a.png)

**Comment by syl20bnr** [comment]
Do you have the same behavior when splitting a window ?

**Comment by mmcnl** [comment]
No, splitting a window works fine. And guide key does not disturb the font sizes either.
![screen shot 2015-04-07 at 9 30 38 pm](https://cloud.githubusercontent.com/assets/1498727/7038911/7f507cb4-dd6d-11e4-814d-4af50ccde87d.png)

**Comment by mmcnl** [comment]
Also, I've noticed this behavior with my custom layer disabled.

**Comment by TheBB** [comment]
Does this still happen? I cannot reproduce.

**Comment by mmcnl** [comment]
No, happily it's fixed. Sorry I should have closed this!
