### ISSUE TITLE
OpenSSL deprecated flags

### ISSUE THREAD

**Issue by NerdsvilleCEO** [syl20bnr/spacemacs#10845]
#### Description :octocat:
When pulling packages, if on an openssl version which has deprecated and removed the -no_ssl2 flag, no packages can be pulled
**https://www.openssl.org/docs/man1.1.0/apps/s_client.html**
**https://www.openssl.org/docs/man1.0.2/apps/s_client.html**

#### Reproduction guide :beetle:
- System without gnutls util
- Install openssl 1.1.0/remove openssl < 1.1.0
- Remove .emacs.d
- Clone spacemacs
- Open emacs

*Observed behaviour:* :eyes: :broken_heart:
No packages can be installed

*Expected behaviour:* :heart: :smile:
Packages will be installed

**Comment by syl20bnr** [comment]
We don't do anything about this at the spacemas level so I think this is an Emacs upstream bug.

What would be the benefit to not install gnutls ?
