### ISSUE TITLE
Unknown layer pdf-tools on develop branch.

### ISSUE THREAD

**Issue by siulkilulki** [syl20bnr/spacemacs#10840]
#### Description :octocat:
No pdf-tools in develop branch?
Should I use something different?

#### Reproduction guide :beetle:
- switch to develop branch
- add pdf-tools to layers,
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs gives following warning:
(Spacemacs) Warning: Unknown layer pdf-tools declared in dotfile.

*Expected behaviour:* :heart: :smile:
Spacemacs installs pdf-tools.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5004e05)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(evil-snipe
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 themes-megapack theming colors csv
 (csv :variables csv-separators
      '("	"))
 yaml helm auto-completion
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 emacs-lisp git markdown latex pdf-tools
 (markdown :variables markdown-live-preview-engine 'vmd)
 ranger org neotree version-control python
 (python :variables python-enable-yapf-format-on-save t python-test-runner 'pytest python-sort-imports-on-save t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by siulkilulki** [comment]
it's now called `pdf` instead of `pdf-tools`

**Comment by hyiltiz** [comment]
This seriously should be raised in the error message. Everytime I try to live my life, spacemacs breaks and everytime I try to fix it, I was told it was fixed in develop, and everytime I checkout develop, I bump into another million issues waiting for me to fix.
