### ISSUE TITLE
Saving Python buffer with non-ascii characters converts them sometimes

### ISSUE THREAD

**Issue by MatthewRock** [syl20bnr/spacemacs#10850]
[w.txt](https://github.com/syl20bnr/spacemacs/files/2089999/w.txt)
#### Description :octocat:
When saving a python buffer with some non-ascii characters in it, but only in comments,
a wrong encoding is assumed, causing the non-ascii characters to be converted, possibly making script broken.

#### Reproduction guide :beetle:
- Start Emacs
- From the console, rename the attached file to Python file(`mv w.txt w.py`)
- Open the attached file
- Add a new line "a = 1"
- Save the file
- Notice that all the characters stayed as they were and the file saved successfully.
- Remove the line "ę = 1"
- Save the file
- Notice that the absence of unicode characters in the code(but not in the comments) made them convert other "ę" character.

*Observed behaviour:* :eyes: :broken_heart:
The absence of unicode characters in the code(but not in the comments) made them convert other "ę" character in the comments.

*Expected behaviour:* :heart: :smile:
Characters are not converted.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(graphviz auto-completion better-defaults c-c   common-lisp emacs-lisp git haskell javascript
          (rcirc :variables rcirc-enable-authinfo-support t)
          markdown
          (python :variables python-enable-yapf-format-on-save t)
          (ruby :variables ruby-version-manager 'rvm ruby-test-runner 'rspec)
          org
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          slack spell-checking syntax-checking themes-megapack version-control xkcd)
```

#### Backtrace :paw_prints:
None

**Comment by MatthewRock** [comment]
[w.txt](https://github.com/syl20bnr/spacemacs/files/2090005/w.txt)
+file

**Comment by Compro-Prasad** [comment]
It is better to show a screenshot for each step like before save, after save, etc. I can't understand your last step in `Reproduction guide`.

**Comment by MatthewRock** [comment]
Please find attached a screenshot before removing ę and after removing it.
![after](https://user-images.githubusercontent.com/1909226/41238720-e81143a2-6d96-11e8-9cf9-f16146894133.png)
![before](https://user-images.githubusercontent.com/1909226/41238721-e831166e-6d96-11e8-9f14-b4c9b157382a.png)

**Comment by Compro-Prasad** [comment]
Sorry, couldn't reproduce. My python layer has:
```
(python :variables
             python-backend 'anaconda
             python-enable-yapf-format-on-save t
             python-fill-column 80
             python-auto-set-local-pyenv-version 'on-visit
             python-auto-set-local-pyvenv-virtualenv 'on-visit
             python-sort-imports-on-save t
             python-test-runner '(nose pytest))
```

**Comment by MatthewRock** [comment]
Then I will try to investigate it further and see what happens. Thanks for trying it out.

**Comment by Miciah** [comment]
Any luck identifying the cause of the issue?

I would start by checking save hooks.  Use <kbd>C-h v</kbd> to see the values of `before-save-hook` and `after-save-hook`.  Then run each hook manually (e.g., <kbd>M-:</kbd> and enter `(yapfify-buffer)`) until you find one that causes the issue.  Alternatively, remove a hook (e.g., `(pop before-save-hook)`), save, and repeat until you find the cause.

It might also be worth trying a newer Emacs version.  Emacs 24.5.1 is several years old and two releases behind the latest.
