### ISSUE TITLE
Loading project layout from layout file results in error

### ISSUE THREAD

**Issue by sutram** [syl20bnr/spacemacs#10856]
#### Description :octocat:
Loading project layout from layout file results in error

#### Reproduction guide :beetle:
- Start Emacs
- Load a file that is recognized by projectile as being part of a project
- Let projectile save this layout as a project layout using SPC p l
- Save the layout in a custom file (I called it "projects")
- Use SPC l L to load this file
- The same thing happens if I use SPC q q to quit Emacs and then start Spacemacs and then load the layout file

*Observed behaviour:* :eyes: :broken_heart:
Backtrace as described below

*Expected behaviour:* :heart: :smile:
No errors and the layout file loads the right layout

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 386a8fa79)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(plantuml html javascript ansible csv markdown python clojure yaml helm auto-completion better-defaults emacs-lisp git org
          (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell shell-enable-smart-eshell t)
          sql osx pdf finance rust)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:
```
apply: Wrong number of arguments: (lambda nil "Assure the mode-line is loaded before restoring the layouts." (advice-remove (quote persp-load-state-from-file) (quote spacemacs//layout-wait-for-modeline)) (if (and (configuration-layer/package-used-p (quote spaceline)) (memq (spacemacs/get-mode-line-theme-name) (quote (spacemacs all-the-icons custom)))) (progn (require (quote spaceline-config))))), 1
```

**Comment by darcylee** [comment]
I also encountered this situation, who knows what repair?

**Comment by darcylee** [comment]
restart `SPC q r` emacs then it's works.

**Comment by sutram** [comment]
I think this is related to https://github.com/syl20bnr/spacemacs/issues/10849

**Comment by lululau** [comment]
It's maybe about this line of code:

`layers/+spacemacs/spacemacs-layouts/packages.el:221`:

`(advice-add 'persp-load-state-from-file :before 'spacemacs//layout-wait-for-modeline)`

the `persp-load-state-from-file` func needs some arguments specified, but the advice func `spacemacs//layout-wait-for-modeline` has no args declared.

My temporary work-around:

![image](https://user-images.githubusercontent.com/440583/41387197-3bba1d6c-6fb8-11e8-81bf-e306d05c5c75.png)


I don't know `interactive` args very much, or I would emit a PR

**Comment by robbyoconnor** [comment]
This seemed transient for me

**Comment by robbyoconnor** [comment]
Broken again for me...

**Comment by mpanarin** [comment]
experiencing the same issue

**Comment by robbyoconnor** [comment]
Should be fixed.

**Comment by sutram** [comment]
Yup, can confirm, it is fixed.
Thanks!
