### ISSUE TITLE
reStructuredText Layer Not Working

### ISSUE THREAD

**Issue by jjzmajic** [syl20bnr/spacemacs#10852]
#### Description :octocat:
`restructuredtext` layer causing issues with `linum` package after instalation.

#### Reproduction guide :beetle:
- Start Emacs
- Add `restructuredtext` layer to `.spacemacs`
- Restart Emacs

*Observed behaviour:* :eyes: :broken_heart:
```
Warnings:
    - package linum not initialized in layer restructuredtext, you may consider
      removing this package from the package list or use the :toggle keyword instead
      of a `when' form.      
```

*Expected behaviour:* :heart: :smile:
`restructuredtext` package 'just works'.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 86b4e6f76)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults c-c++ python emacs-lisp git markdown restructuredtext neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

#### Backtrace :paw_prints:
```
```

**Comment by ellakk** [comment]
I submitted a pull-request to fix this a couple of days ago #10837.
It's basically caused by a typo, init-post-linum should be changed to post-init-linum in the layers package.el file.

**Comment by jjzmajic** [comment]
Thanks for your work @ellak. Glad to hear someone is already on it. The OSS community never ceases to amaze.

**Comment by Miciah** [comment]
Since #10837 / https://github.com/syl20bnr/spacemacs/pull/10837/commits/3ae0b77507000109f8232e1f79fb8901b04b0203 is merged in the develop branch and there is no restructuredtext layer in the master branch, can this issue be closed as resolved?

**Comment by jjzmajic** [comment]
@Miciah thanks for bringing my attention to this. Close #10852.

**Comment by jjzmajic** [comment]
Fair enough. Thanks, @Miciah for bringing this to my attention.
