### ISSUE TITLE
Update evil package via [Update] link resulted in error start

### ISSUE THREAD

**Issue by reed1** [syl20bnr/spacemacs#1085]
Forgive me if it has been posted before,

I was updating packages using the [Update] link on front page. There was update for evil, that package is then deleted. But after emacs restart, it couldn't boot because it needs evil package. 

So I copied back evil folder from rollback dir then I tried to use paradox package menu and then the update runs fine.

thank you
-reed1

**Comment by syl20bnr** [comment]
Thank you for the report.
I just fixed it in develop, there were 2 serious bugs, sorry for this.

**Comment by reed1** [comment]
Nice, I tried to update evil and when emacs restarted it says

(Bootstrap) installing evil..

and installs just fine, tyvm ! : )
