### ISSUE TITLE
Globally turn off smartparens paren matching (2018 edition)

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#10858]
There are a few issues asking how to turn off smartparens without crippling spacemacs (like [this](https://github.com/syl20bnr/spacemacs/issues/1603) one or [this one](https://github.com/syl20bnr/spacemacs/issues/6144), but they mention functions like `spacemacs/toggle-smartparens-off` which don’t exist anymore.

Personally I am very allergic to “smart” heuristics that try to insert or delete characters while I’m typing, so how do I turn this off globally?

I found [this snippet](https://github.com/trishume/dotfiles/blob/df78a575e67a6361b4f953eeac9895c55c32f7f5/emacs%2B/spacemacs.symlink#L320) which removes a few pairings, but maybe there’s a better way?

**Comment by syl20bnr** [comment]
Excluding smartparens should enough. If not then we need to fix the bugs.

**Comment by Profpatsch** [comment]
Okay, I excluded it and will reopen if I find that causes bugs.

**Comment by vatrat** [comment]
Does `(remove-hook 'prog-mode-hook #'smartparens-mode #'show-smartparens-mode)` not do it for you? It seems that stops it from being enabled on buffers.

**Comment by Profpatsch** [comment]
```
   dotspacemacs-excluded-packages '(
     smartparens
```

seems to have done the trick.

**Comment by Profpatsch** [comment]
f

**Comment by ChShersh** [comment]
Adding `smartparens` to excluded packages doesn't work for me. But the snippet given by @Profpatsch works like magic! I've been suffering too long from automatic addition of closing parenthesis, square brackets, curly brackets, single quotes, double quotes and backtics. Thank you, @Profpatsch for the link to this snippet!

**Comment by dgealow** [comment]
The initial snippet mentioned has been working for me for a few years, but I recently started coding in Python with spacemacs and, to my horror, my parentheses are automatically closing themselves again in python mode. (Not, however, in any other mode I've tried, e.g. lisp or c.) I don't know if smartparens is the culprit, or if it's some other package that python mode is using.

**Comment by dgealow** [comment]
Update: it is indeed smartparens.
Workaround: add
`(add-hook 'python-mode-hook 'spacemacs/toggle-smartparens-off)`
to my `dotspacemacs/user-config`.
