### ISSUE TITLE
No Company documentation with Cider

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10854]
#### Description :octocat:
Cider's documentation is working (`, h h`) but pressing `C-h` on Company's completion candidates produces `No documentation available`. I am not sure if the problem is with Spacemacs, since I just updated all my packages and Spacemacs.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: added-dvorak-right-handed-to-keyboard-layout-layer (rev. 5c575adfb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc yaml fsharp windows-scripts javascript epub xkcd spotify twitter search-engine vimscript
          (elfeed :variables rmh-elfeed-org-files
                  (list "~/.emacs.d/private/feeds/elfeed1.org"))
          (rust :variables rust-format-on-save t)
          (haskell :variables haskell-enable-hindent t)
          semantic lsp
          (c-c++ :variables c-c++-enable-clang-support t)
          html
          (python :variables python-backend 'anaconda)
          chrome
          (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
          (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
          autohotkey kotlin helm
          (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
          emacs-lisp
          (ibuffer :variables ibuffer-group-buffers-by 'modes)
          coq emoji
          (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
          git markdown org
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          spell-checking
          (syntax-checking :variables syntax-checking-enable-tooltips t)
          (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
          version-control osx scheme
          (clojure :variables clojure-enable-fancify-symbols t))
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Compro-Prasad** [comment]
@NightMachinary This can't be reproduced as per information from upstream. Did you try updating everything and fixing your config or talking to someone else?

**Comment by NightMachinary** [comment]
I did update everything, but didn’t change my config (which I hadn’t
changed before the problem), and no, I haven’t talked to anyone.
Feel free to close this issue, I’ll reopen it if the problem didn’t get
solved with time. (As Emacs problems tend to do😂✂️)

**Comment by huu000000** [comment]
https://github.com/syl20bnr/spacemacs/labels/To%20be%20reproduced

**Comment by jr0cket** [comment]
@syl20bnr suggest closing this Clojure issue as its not been reproduced in a year.  Thank you

**Comment by duianto** [comment]
Thanks for the suggestion.
