### ISSUE TITLE
Error when using ripgrep to search in directory or files

### ISSUE THREAD

**Issue by jeremymeng** [syl20bnr/spacemacs#10863]
#### Description :octocat:
`rg` doesn't take `--max-columns` option

#### Reproduction guide :beetle:
- Start Emacs
- Open Dired for any directory
- Do `[SPC s r d]` to invoke `ripgrep`
- type some text pattern

*Observed behaviour:* :eyes: :broken_heart:
Unexpected argument `--max-columns`

*Expected behaviour:* :heart: :smile:
searching using `rg`

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8754b2450)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(yaml helm emacs-lisp fsharp git github markdown org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:
N/A

**Comment by jeremymeng** [comment]
![image](https://user-images.githubusercontent.com/7583839/41324141-cdac4954-6e67-11e8-887b-e8ec1fc81bee.png)

**Comment by Miciah** [comment]
Works for me with ripgrep 0.8.1 on GNU/Linux.

What version of ripgrep are you using? `--max-columns` was introduced in ripgrep 0.5.0.

**Comment by jeremymeng** [comment]
You are right.  I was using a pretty old version of ripgrep (0.4.0).
