### ISSUE TITLE
Spacemacs custom variables problem

### ISSUE THREAD

**Issue by latiagertrutis** [syl20bnr/spacemacs#10862]
Hi, I've just started using Spacemacs, i wanted to change some variables like cursor shape, it's supposed to be done in `dotspacemacs/user-config` inside `.spacemacs`, I've did it like that:

```
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
  (setq cursor-type 'bar)
  )
```
So I'm just wondering what I'm doing wrong
Thanks!

**Comment by syl20bnr** [comment]
See https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distributions/spacemacs-bootstrap/config.el#L71-L83

**Comment by latiagertrutis** [comment]
Thanks a lot!
