### ISSUE TITLE
Using oh-my-zsh, shell text garbled...

### ISSUE THREAD

**Issue by CanftIn** [syl20bnr/spacemacs#10866]
**Description**
I want to use zsh with oh-my-zsh installed as spacemacs internal shell, and on desktop, zsh work well.
run with commands `emacs -nw` and `M+x shell` to enter the shell mode, I got an garbled shell like the right side in the screenshot.
![error3](https://user-images.githubusercontent.com/26135447/41342572-287c1a4a-6f2f-11e8-81ed-54c93247db0c.png)
I use "powerlevel9k" as oh-my-zsh theme. After changing the theme, the shell still appear text garbled.

using `ansi-term` or `term` and run program /usr/bin/zsh, there will no strange characters.
![_ _20180613173649](https://user-images.githubusercontent.com/26135447/41343440-32317286-6f31-11e8-9450-e0d5dacb781c.png)
but the shell looks so hard...

I found past issues #6235 #3035 and try to change `.zshrc`, but these answers not address my problem.

PS: Guys suggest us not to use shell mode, Does it mean the shell mode still work great? Or I need to give zsh and change to eshell? 

**System Info**
- OS: Debian X64
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. [582f9aa](https://github.com/syl20bnr/spacemacs/commit/582f9aa45c2c90bc6ec98bccda33fc428e4c6d48))
- Distribution: spacemacs
- Completion: helm
- Other supplements:  
       TERM=xterm-256color
       zsh version: zsh 5.3.1 (x86_64-debian-linux-gnu)

**Comment by CanftIn** [comment]
@syl20bnr Sorry about that I noticed this FAQ before but I didn't try. Just now, I try to set the terminfo like that
![1](https://user-images.githubusercontent.com/26135447/41500984-62de9e78-71ce-11e8-910d-f76d4af638cc.png)
then I get into **ansi-shell**, still not working.
![2](https://user-images.githubusercontent.com/26135447/41501158-51ea954c-71d1-11e8-811f-ad998c1cd856.png)

I found a same symptom on stackoverflow two days ago: [How to customise Oh My ZSH within a Spacemacs shell?](https://stackoverflow.com/questions/45780419/how-to-customise-oh-my-zsh-within-a-spacemacs-shell?rq=1)
that's my config in '~/.spacemacs'
![3](https://user-images.githubusercontent.com/26135447/41501195-39b94210-71d2-11e8-8d7e-982c554abbe0.png)
use `M+x shell` after that config. It works like that, not very pretty
![4](https://user-images.githubusercontent.com/26135447/41501199-5f560b16-71d2-11e8-8051-dba2cd02b93e.png)

**Comment by Bungalally** [comment]
Would also appreciate it if anyone finds the solution to this.

**Comment by streichman** [comment]
Was trying to sort this out because I really like zsh. Found this:
https://github.com/dieggsy/eterm-256color

To add in spacemacs, just add 'eterm-256color' to your dotspacemacs-additional-packages and then add 
```
(add-hook 'term-mode-hook #'eterm-256color-mode) 
```
to your dotspacemacs/user-config

**Comment by aislanmaia** [comment]
> Was trying to sort this out because I really like zsh. Found this:
> https://github.com/dieggsy/eterm-256color
> 
> To add in spacemacs, just add 'eterm-256color' to your dotspacemacs-additional-packages and then add
> 
> ```
> (add-hook 'term-mode-hook #'eterm-256color-mode) 
> ```
> to your dotspacemacs/user-config

Thanks for your tip, it works!! But now my zsh is outputting when I run `ls` command:

`zsh: command not found: ls`

**Comment by xihajun** [comment]
> How to customise Oh My ZSH within a Spacemacs shell?

did you fix this issue?

**Comment by Bungalally** [comment]
Thanks for following up?

I ended up switching to Doom Emacs which seemed to resolve the problem. Unfortunately I am not very familiar with lisp and couldn’t diagnose the problem.

**Comment by thecocoa** [comment]
```
iTerm2 3.4.2
macOS Big Sur 11.1 (20C5061b)
GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H15)) of 2020-11-11
Spacemacs develop branch
```
I did the above (thank you, @streichman) and spacemacs recognized I didn't have an eterm-256color and download one for me from github and automagically ran:  
 
```-*- mode: compilation; default-directory: "~/" -*-
Compilation started at Thu Dec 10 23:54:58

tic -s /var/folders/8f/qkn0rcp16tn_9298l7np3_qc0000gn/T/eterm-color.ti
1 entries written to /Users/macuser/.terminfo

Compilation finished at Thu Dec 10 23:54:58
```

I tried to start a shell with ```space + '``` and this displayed in my message buffer:
```
eterm-256color-mode requires compilation of eterm-256color.ti.
Term may need to be restarted.  Compile now? (y or n)
```
I answered 'y' and this was displayed:
```
-*- mode: compilation; default-directory: "~/" -*-
Compilation started at Fri Dec 11 00:00:26

tic -s '/Users/macuser/.emacs.d/elpa/28.0/develop/eterm-256color-20190123.401/eterm-256color.ti'
1 entries written to /Users/macuser/.terminfo

Compilation finished at Fri Dec 11 00:00:26

```
Still getting garbled 133 ascii characters in my PS1
Still can't export TERM as eterm-256color.  If I try, I get the following error:
```
zle-line-init:echoti:1: no such terminfo capability: smkx
```

I disabled iTerm2 shell integration by commenting out the following line from my ~/.zshrc

```
#test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
```
At least now, my PS1 looks good when I do ```SPACE + '```   
It's not perfect - I still see ]2;ls -G]1;ls, but the terminal is much more readable.
