### ISSUE TITLE
Develop: Go layer tools doesn't work

### ISSUE THREAD

**Issue by vbauerster** [syl20bnr/spacemacs#10867]
#### Description :octocat:
It seems that Go's layer tools don't see a `$GOPATH` env variable.
I came to this conclusion, because none of the Go tool is working, on develop branch: 8754b2450

Everything was working here: 7944ed263

#### Reproduction guide :beetle:
- Start Emacs
- Open any go file with imports from std lib.
- Turn on syntax checking `SPC t s`

*Observed behaviour:* :eyes: :broken_heart:
All imports of std lib are error highlighted, saying package not found.

*Expected behaviour:* :heart: :smile:
Import of std lib packages should always be found and not error highlighted.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8754b2450)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org git
      (version-control :variables version-control-diff-side 'left)
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip 'manual)
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      (spell-checking :variables spell-checking-enable-by-default nil)
      html markdown neotree yaml python java javascript rust
      (go :variables go-tab-width 4 gofmt-command "goimports" go-use-gometalinter t godoc-at-point-function 'godoc-gogetdoc)
      protobuf docker themes-megapack dash semantic
      (ranger :variables ranger-show-preview t ranger-show-literal t)
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
      shell-scripts slack)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by ljupchokotev** [comment]
This is because of the new env-vars cache. The solution for this is to open the `.emacs.d/.cache/.env-vars` file and manually set GOROOT and GOPATH there.

This is probably going to be fixed, syl20bnr is already aware that it's buggy.

**Comment by syl20bnr** [comment]
Closing as duplicates of https://github.com/syl20bnr/spacemacs/issues/10851

**Comment by patrick-motard** [comment]
@ljupchokotev I don't have a file in `.emacs.d/.cache/.en-vars`. Perhaps it was never created since i started from a clean install on the dev branch? What do the contents of that file look like? I don't mind editing it manually to get the go layer working while I wait for this to be patched.

**Comment by ljupchokotev** [comment]
@patrick-motard Check the documentation about environment variables in Spacemacs. You can initialize that file yourself.

**Comment by patrick-motard** [comment]
@ljupchokotev I'm not seeing anything in [DOCUMENTATION.org](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org) regarding this file or how to initialize it, nor environment variables except for a brief mention of `SPACEMACSDIR`. Is there another location for documentation where I should be looking?

**Comment by Miciah** [comment]
@patrick-motard, make sure you are looking at the documentation for the develop branch: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#environment-variables-and-path

I think ljupchokotev was referring to `.spacemacs.env`.  The related key bindings are <kbd>SPC f e e</kbd> to edit `.spacemacs.env`, <kbd>SPC f e C-e</kbd> to re-initialize it from the current environment, and <kbd>SPC f e E</kbd> to reload it.

**Comment by krizex** [comment]
@Miciah  Your message saves my life, thanks!
