### ISSUE TITLE
Error (use-package): flycheck/:init: Symbol’s value as variable is void: flycheck-error-list-mode-map

### ISSUE THREAD

**Issue by Electron-libre** [syl20bnr/spacemacs#10865]
#### Description :octocat:

Error when initializing flycheck package.

```
Error (use-package): flycheck/:init: Symbol’s value as variable is void: flycheck-error-list-mode-map
```

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

The warning window report an error

```
Error (use-package): flycheck/:init: Symbol’s value as variable is void: flycheck-error-list-mode-map
```

*Expected behaviour:* :heart: :smile:

No error in warning window.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8754b2450)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 rust better-defaults emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-tooltips nil ispell-dictionary "english")
 csv javascript nginx docker elixir elm html ruby ruby-on-rails
 (haskell :variables haskell-enable-hindent-style "chris-done" haskell-completion-backend 'ghc-mode)
 sql shell-scripts yaml themes-megapack
 (keyboard-layout :variables kl-layout 'bepo)
 erc ansible floobits fsharp neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by CharlesHD** [comment]
I have the same issue with flycheck and evil-surround. My guess is that it is related to keyboard-layout not working with the new lazy-load features introduced by @syl20bnr . Specifically commits 03786aa94a334aa1a2a15f95300751a6074dec84 (evil-surround) and 19b478efbda00542e6aac19beb04534d6540f806 (flycheck). I'm going to inspect keyboard-layout in order to see how it can be integrated.

**Comment by CharlesHD** [comment]
Just opened the PR #10893 that fixes the problem for flycheck and evil-surround. If other packages remapped by keyboard-layout are lazy-loaded we may have to do the same sort of modification.

**Comment by CharlesHD** [comment]
@Electron-libre could you check if it fixed your problem ? If it did, feel free to close the issue.
