### ISSUE TITLE
messed up evil bindings when minibuffer looses focus

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#10869]
If I start a search with `/` and the minibuffer looses focus, e.g. by clicking into one of the open buffers, the evil key binding get messed up, e.g. `d` deletes an entire line instead of `dd`.
This can be fixed simply by clicking into the minibuffer and pressing `C-g`, but this can be annoying at times.

Edit: I am on Emacs 26.1.1 and the Spacemacs develop branch.

**Comment by ljupchokotev** [comment]
This is a known bug, see #10410 for a workaround.

**Comment by syl20bnr** [comment]
Closing as duplicate of https://github.com/syl20bnr/spacemacs/issues/10410
