### ISSUE TITLE
Add djangonaut package to spacemacs.

### ISSUE THREAD

**Issue by proofit404** [syl20bnr/spacemacs#10860]
Hi, I'm the author of the anaconda-mode package which is used by spacemacs right now.

Recently I developed [djangnaut](https://github.com/proofit404/djangonaut) package for Django developers.

I think many users of the spacemacs can benefit from it, so I want to discuss its inclusion in the spacemacs.

If we all agree I will provide a PR for it. Probably I'll need help with spacemacs layers API.

P.S. I know pony-mode is used for similar purposes right now, so it's fine if you think this functionality is already covered.

**Comment by syl20bnr** [comment]
PR welcome :-)

You could add it to the `django` layer which just has `pony-mode` package currently and add a layer variable in a `config.el` file called `django-backend` to be able to choose between `pony` and `djangnaut`.

Best is to see how it is done with other layers, the `python` is a good one to look at.

Tell me if you need more help.
