### ISSUE TITLE
void-function spaceline-all-the-icons--setup-neotree

### ISSUE THREAD

**Issue by FieryCod** [syl20bnr/spacemacs#10872]
#### Description :octocat:
I did update my spacemacs and after this update I'm receiving following error:
An error occurred while post-configuring neotree in layer spacemacs-modeline (error: (void-function spaceline-all-the-icons--setup-neotree))
<<DESCRIPTION OF THE PROBLEM>>

#### Reproduction guide :beetle:
- Start Emacs
- Check the messages
<<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
Error on spaceline-all-the-icons initialization
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
No error
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8754b2450)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'complete spacemacs-default-company-backends
                  '(company-files company-anaconda company-keywords company-dabbrev-code company-dabbrev company-yasnippet company-tide company-css company-web-html))
 docker php javascript evil-commentary csv better-defaults clojure go html github emacs-lisp syntax-checking neotree yaml parinfer plantuml ruby sql python colors markdown osx ivy
 (typescript :variables typescript-backend 'tide)
 gtags
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (git :variables git-magit-status-fullscreen t)
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 (org :variables org-enable-github-support t)
 (semantic :disabled-for emacs-lisp)
 (shell :variables shell-default-height 40 shell-default-position 'bottom shell-default-shell 'eshell))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by syl20bnr** [comment]
Can you test with last develop ? I just pushed new commits regarding spaceline.

**Comment by omidmnz** [comment]
The latest develop solves this for me.

**Comment by FieryCod** [comment]
Yep it's solved Thank you!
