### ISSUE TITLE
rg does not highlight results when using flags

### ISSUE THREAD

**Issue by Kernael** [syl20bnr/spacemacs#10879]
#### Description :octocat:
(Posting here because I couldn't find the package used for the ripgrep frontend)

When using `SPC /` inside of a project with `rg`, with additional flags such as `-t` or `-g`, the matched results will not be highlighed.

#### Reproduction guide :beetle:
- Start Emacs
- Navigate inside a projectile project
- Start searching something with `SPC /`
- search a string and use the `-g` flag to restrict the search to certain files e.g.: `test -g*.rb*`

*Observed behaviour:* :eyes: :broken_heart:
The matched strings from the results are not highlighted.

*Expected behaviour:* :heart: :smile:
The matched strings from the results should be highlighted.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 31324f68b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git markdown neotree org syntax-checking elixir ruby ruby-on-rails colors yaml html javascript erlang
      (osx :variables osx-option-as 'none)
      kernael react)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by syl20bnr** [comment]
I think this should be reported upstream: https://github.com/syohex/emacs-helm-ag
