### ISSUE TITLE
add option to disable `importmagic` in python-mode

### ISSUE THREAD

**Issue by jiahut** [syl20bnr/spacemacs#10876]
the `[importmagic] Indexed` take a long time each time when startup, My MAC is ringing 

Oh my god,  when I execute:

> `ps aux | grep importmagicserver.py | wc -l `

It's terrible

As an alternative, temporary add `  (remove-hook 'python-mode-hook 'importmagic-mode)
` to `dotspacemacs/user-config`

**Comment by syl20bnr** [comment]
Let's remove it if this is an issue.

**Comment by GregorySchwartz** [comment]
Whenever I opened a line below with `o`, emacs would freeze for a second. Profiling revealed that it was searching for importmagic each time. Adding importmagic to the excluded packages sped up editing tremendously for me.
