### ISSUE TITLE
Reloading .spacemacs with fullscreen enabled (in OS X) toggles fullscreen mode

### ISSUE THREAD

**Issue by CarlQLange** [syl20bnr/spacemacs#1088]
In OSX, if you have fullscreen mode enabled, and reload the spacemacs config, it toggles fullscreen mode. Not a big deal but a little frustrating.

**Comment by syl20bnr** [comment]
:-)
I'll look if there is a variable that holds the current state, otherwise we may have to make an ugly hack.
This is a generalized issue with any toggles that we encountered while loading spacemacs.

**Comment by louy2** [comment]
Same here on Windows 8.1

**Comment by aeschylus** [comment]
Same here. I did manage to make it open fullscreen when closed and re-opened, but I don't want to have to click the expand icon with the mouse (on a Mac) every time I edit the config. Until this is fixed, is there a SPC function somewhere that will toggle it for now?

**Comment by felipe-barros** [comment]
@aeschylus `SPC T F` ?

**Comment by aeschylus** [comment]
That's "auto-fill-mode". Not really sure what it's supposed to do, but it caused some vertical green lines to appear in some of my frames. `SPC T F` removed them again.

**Comment by StreakyCobra** [comment]
Waiting on PR: #2135 (#3211) was closed without being merged.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
