### ISSUE TITLE
problems with lazy eval

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#10881]
I had the following options in my `dotspacemacs/user-config`:

```
  (define-key evil-insert-state-map (kbd "TAB") yas-maybe-expand)
  (global-evil-mc-mode)
  (global-flycheck-mode)
  (spacemacs/toggle-automatic-symbol-highlight-on)
  (spacemacs/toggle-indent-guide-globally-on)
  (spacemacs/toggle-fill-column-indicator-on)
```
due to recent changes none of them get set at start up any more.

**Comment by syl20bnr** [comment]
Should be fixed in last develop.
Closing as duplicates of https://github.com/syl20bnr/spacemacs/issues/10849

**Comment by gdkrmr** [comment]
I just pulled the latest develop and `global-evil-mc-mode` is not activated and I get an error message at startup:
```
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s value as variable is void: yas-maybe-expand
```

**Comment by syl20bnr** [comment]
Should be:

```
(define-key evil-insert-state-map (kbd "TAB") 'yas-maybe-expand)
```

Note the quoted function `'yas-maybe-expand`.

**Comment by gdkrmr** [comment]
actually no, the quoted version gives me:
```
command-execute: Wrong type argument: commandp, yas-maybe-expand
```
