### ISSUE TITLE
$PATH not same with exec-path without exec-path-from-shell loaded

### ISSUE THREAD

**Issue by myme5261314** [syl20bnr/spacemacs#10883]
#### Description :octocat:
$PATH not correct as `exec-path`, missing `/usr/local/bin`.

I have two Macbook Pro, using the same `.spacemacs.d` configuration synchronized by my private repo, same Emacs installed through `brew cask install emacs`.
But Emacs.app works just fine on the 13-inch one and have issues described on
the 15-inch one.

If I delete the file located at `spacemacs-env-vars-file` whose value is
`~/.emacs.d/.cache/.env-vars`, then the error will disappear.
At this time, close the Emacs.app and re-open it again, the error occurs again.
```lisp
(defun spacemacs//initialize-exec-path-from-shell (&optional force)
     "Initialize exec-path and cache its value.
   Load from cache file if cache file exists and FORCE is nil."
     (when (display-graphic-p)
      (when force (delete-file spacemacs-env-vars-file))
      (if (file-exists-p spacemacs-env-vars-file)
        (load spacemacs-env-vars-file nil (not init-file-debug))
       (require 'exec-path-from-shell)
       (exec-path-from-shell-initialize)
       (spacemacs/dump-vars-to-file '(exec-path) spacemacs-env-vars-file))))
```

And there are still many other weird issues on 15-inch's Emacs.
But I think we should solve the issues one by one.
- Such as `j/k/h/l` will be undefined in `Message` buffer.
- `SPACE` key will not work properly on `spacemacs` buffer, message shows the buffer
is read only.
- the cursor and window index located at the left-bottom in the buffer will
shining and switching between two colors, and at this time, type is not
responding, press `⌘` can make typing ok and switching terminated.
- At the moment I'm writing this issue in Emacs.app, the vim-mode doesn't work, press `ESC`
will not get `normal-mode`.

#### Reproduction guide :beetle:
- Start Emacs from Emacs.app
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
Message on Warning buffer
`Error (use-package): python/:init: Invalid version syntax: ‘zsh:1: command not found: ipython’ (must start with a number)`

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d7f5b5889)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby ruby-on-rails docker nginx csv javascript helm better-defaults github
      (version-control :variables version-control-diff-tool 'git-gutter+ version-control-global-margin t)
      semantic markdown
      (vinegar :variables vinegar-reuse-dired-buffer t)
      (org :variables org-projectile-file "TODOs.org")
      prodigy search-engine
      (syntax-checking)
      (spell-checking)
      yaml python lua html command-log emacs-lisp emoji fasd deft ranger gtags cscope
      (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
      (colors :variables colors-enable-nyan-cat-progress-bar t)
      (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
      (ibuffer :variables ibuffer-group-buffers-by 'projects)
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
      (shell :variables shell-default-position 'full shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh")
      (chinese :variables chinese-enable-fcitx t chinese-enable-youdao-dict t)
      emacs-lisp markdown dash bibtex django pandoc vimscript my)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by fiveNinePlusR** [comment]
This is a known issue and is being resolved.

**Comment by myme5261314** [comment]
@fiveNinePlusR Any tips about the issue url? Thanks.

**Comment by syl20bnr** [comment]
Closing as duplicates of https://github.com/syl20bnr/spacemacs/issues/10851

Should be fixed in last develop, please verify.
