### ISSUE TITLE
Better way to get colours right

### ISSUE THREAD

**Issue by frankjonen** [syl20bnr/spacemacs#10889]
Instead of `(setq ns-use-srgb-colorspace nil)` to make all colours go whacky you can use
`(setq powerline-image-apple-rgb t)` to assign a colour space to the powerline pixmaps (at least that's what I think it does) and make everything display correctly in sRGB (external images still should be converted to Apple RGB to display correctly in the buffer).

With that set, the title bar matches the chosen theme as well. With sRGB disabled it was always much darker when set to dark and transparent.

**Comment by syl20bnr** [comment]
We already set it in develop ;-)
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+spacemacs/spacemacs-modeline/packages.el#L99
