### ISSUE TITLE
csharp layer not working, csharp-mode.elc:Warning

### ISSUE THREAD

**Issue by PandaLz** [syl20bnr/spacemacs#10899]
Opening a .cs file opens a window with this message and omnisharp server don't start

~/.emacs.d/elpa/csharp-mode-20180315.203/csharp-mode.elc:Warning:
    c-font-lock-declarators called with 3 arguments, but requires 4-5

Thank you

**Comment by syl20bnr** [comment]
I believe it should be reported upstream.

**Comment by PandaLz** [comment]
Thank you, I will report to csharp-mode

**Comment by PandaLz** [comment]
Follow up

It was an issue that was solved, reinstalled and now working as expected:

https://github.com/josteink/csharp-mode/issues/127

Thank you :)
