### ISSUE TITLE
Can not copy paste because pbcopy was disabled on Mac OS X layer

### ISSUE THREAD

**Issue by andresgutgon** [syl20bnr/spacemacs#10896]
#### Description :octocat:
[This change](https://github.com/syl20bnr/spacemacs/commit/386a8fa79d0c8564daab0a539b66b52fe5d808ef) commented `pbcopy` on Mac OS X layer

#### Reproduction guide :beetle:
- Start Emacs on Terminal
- copy a line with `yy` and go to other app or terminal. The text is not in your clipboard

*Observed behaviour:* :eyes: :broken_heart:
-

*Expected behaviour:* :heart: :smile:
Copy & paste text from inside spacemac  with `yy` to have in Mac OS X clipboard

#### Backtrace :paw_prints:
-

I hope is enough info. What a did as temporal fix was [revert the commit](https://github.com/syl20bnr/spacemacs/commit/386a8fa79d0c8564daab0a539b66b52fe5d808ef)

cc @syl20bnr

**Comment by syl20bnr** [comment]
You need to add it yourself in your dotfile. For now it introduces unbearable latency with Emacs 26.1 and daemon mode.

**Comment by andresgutgon** [comment]
Can we let this issue opened? I think current behaviour is buggy. It's obscure that copy & paste doesn't work

**Comment by bleggett** [comment]
This is another issue that is [fixed in Mitsuharu's mac-enhanced port](https://bitbucket.org/mituharu/emacs-mac/).

**Comment by aaronjensen** [comment]
I use this:

```
(defun aj/copy-from-osx ()
  (shell-command-to-string "pbpaste"))

(defun aj/paste-to-osx (text &optional push)
  (let ((process-connection-type nil))
    (let ((proc (start-process "pbcopy" nil "pbcopy")))
      (process-send-string proc text)
      (process-send-eof proc))))

(defun aj/select-text (text)
  (if (display-graphic-p)
      (gui-select-text text)
    (aj/paste-to-osx text)))

(defun aj/selection-value ()
  (if (display-graphic-p)
      (gui-selection-value)
    (aj/copy-from-osx)))

(setq interprogram-cut-function 'aj/select-text
      interprogram-paste-function 'aj/selection-value)
```

There is very little latency, which could have to do with how optimized my shell boot time is.

> This is another issue that is fixed in Mitsuharu's mac-enhanced port without the need for pbcopy.el

Unfortunately, that also breaks the ability to have tty and gui emacs share a server 😢

**Comment by ngoue** [comment]
Can anyone instruct me on how to add this to my own dotfile?  Not quite there yet with my emacs-lisp and general understanding of spacemacs to know exactly where to add the commented out values myself. 

So far the most I can figure out is I need to include the `pbcopy` package in my dotfile and then add the `defun osx/init-pbcopy ()` function somewhere... But I'm not sure where... Tried adding `pbcopy` to `dotspacemacs-additional-packages` and adding the function to my `dotspacemacs/user-config`...

Do I need to remove the `osx/` part of the function name?

**Comment by ngoue** [comment]
After adding the code I can get it working if I manually call the function with `SPC SPC` and then searching for `turn-on-pbcopy`.

**Comment by andresgutgon** [comment]
@ngoue I did this as @aaronjensen commented and worked for me:


First include `pbcopy` package like this:
``` lisp
   dotspacemacs-additional-packages '(flycheck-color-mode-line pbcopy)
```

Then in `user-config` put this:
``` lisp
(defun dotspacemacs/user-config ()
  ;; Copy & paste from spacemacs to osx and the other way
  ;; This used to be part of Spacemacs but for performance reasons they
  ;; decided to remove it. More info:
  ;; https://github.com/syl20bnr/spacemacs/issues/10896
  (defun copy-from-osx () (shell-command-to-string "pbpaste"))
  (defun paste-to-osx (text &optional push)
    (let ((process-connection-type nil))
      (let ((proc (start-process "pbcopy" nil "pbcopy")))
        (process-send-string proc text)
        (process-send-eof proc))))
  (defun select-text (text)
    (if (display-graphic-p)
        (gui-select-text text)
      (paste-to-osx text)
    )
  )
  (defun selection-value ()
    (if (display-graphic-p)
        (gui-selection-value)
      (copy-from-osx)
    )
  )
  (setq interprogram-cut-function 'select-text
        interprogram-paste-function 'selection-value)
```

btw I did not notice the performance problem on terminal.

**Comment by andresgutgon** [comment]
Oh!, nice thanks @aaronjensen

**Comment by andresgutgon** [comment]
Hi @aaronjensen I noticed an issue with your solution. I'm using evil mode (Vim mode) and when I copy a line with `yy` and then I paste with `p`. The text is copy in the current line, not in the next line. Are you having this issue? any idea?

**Comment by suonlight** [comment]
I know this issue before. I has tried both`pbcopy` and `osx-clipboard`. But I found `osx-clipboard`, it is faster than `turn-on-pbcopy` and we can use `yy` and `p`.

```
  ;; clipboard for emacs version >= 26
  (use-package osx-clipboard
     :config
     (progn
       (osx-clipboard-mode +1)
       (diminish 'osx-clipboard-mode)))
```

Please remember to add `osx-clipboard` to your addition packages

**Comment by andresgutgon** [comment]
@suonlight are that code for spacemacs config? I'm not where I've to put it

**Comment by aaronjensen** [comment]
If you use both graphical and terminal, you can do this:

```elisp
(use-package osx-clipboard
  :commands
  (osx-clipboard-paste-function osx-clipboard-cut-function))

(defun aj/select-text (text &rest ignore)
  (if (display-graphic-p)
      (gui-select-text text)
    (osx-clipboard-cut-function text)))

(defun aj/selection-value ()
  (if (display-graphic-p)
      (gui-selection-value)
    (osx-clipboard-paste-function)))

(setq interprogram-cut-function 'aj/select-text
      interprogram-paste-function 'aj/selection-value)

(provide 'init-macos-terminal-copy-paste)
```

Thanks for the pointer @suonlight

**Comment by suonlight** [comment]
This is my first PR. Please help me review it :) cc @aaronjensen, @andresgutgon
