### ISSUE TITLE
Develop branch does not properly read environment variables.

### ISSUE THREAD

**Issue by dangom** [syl20bnr/spacemacs#10897]
#### Description :octocat:
Develop branch does not properly read environment variables.

#### Reproduction guide :beetle:
- Start Emacs
- Run (getenv "PATH") and cry

*Observed behaviour:* :eyes: :broken_heart:
PATH only contains "/usr/bin:/bin:/usr/sbin:/sbin"

*Expected behaviour:* :heart: :smile:
PATH contains everything I defined in .bash_profile and .profile.local.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1faf4d3ee)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(lua spacemacs-completion spacemacs-defaults spacemacs-layouts spacemacs-editing spacemacs-navigation spacemacs-modeline spacemacs-project spacemacs-purpose spacemacs-org spacemacs-visual helm
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.25 auto-completion-enable-sort-by-usage t company-mode-completion-cancel-keywords
                      '("do" "then" "case" "begin" "ipython" "<ip"))
     better-defaults emacs-lisp git markdown
     (org :variables org-enable-reveal-js-support t org-enable-bootstrap-support t org-enable-org-journal-support t)
     (shell :variables shell-enable-smart-eshell t shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control javascript
     (python :variables python-fill-column 79 python-sort-imports-on-save t python-tab-width 4)
     ipython-notebook shell-scripts csv common-lisp html
     (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
     (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu" mu4e-contexts t mu4e-enable-notifications nil)
     ibuffer dash yaml major-modes
     (latex :variables latex-build-command "LatexMk")
     bibtex pdf
     (scimax :variables scimax-org-return-dwim t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by syl20bnr** [comment]
Thank you for the report. That’s an easy fix. I should be able to fix it quickly this morning.

**Comment by syl20bnr** [comment]
Should be fixed in last develop.

**Comment by dangom** [comment]
Thanks for the quick fix =)

**Comment by jgrosso** [comment]
(If I should open a new issue instead of commenting on a closed one, by the way, I'm happy to do so!)

**Comment by syl20bnr** [comment]
What is your OS and where is your PATH defined ?

**Comment by fiveNinePlusR** [comment]
if you put it in `~/.zshenv` it should work.

**Comment by Andre0991** [comment]
I'm getting this error in `1abce5ec10aa646c2bb95a1cb2e59ad57a7f5020`:

`(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: exec-path-from-shell-copy-envs`.
This function is not called from my dotfile, so I don't really get this message.

Also, there's no `exec-path-from-shell` in `~/.emacs.d/elpa/25.3/develop/`, is this expected?

If I use `package-install` to get `exec-path-from-shell` and run `exec-path-from-shell-initialize`, everything works fine.

**Comment by syl20bnr** [comment]
@Andre0991 That's weird, maybe a package you require that depends on `exec-path-from-shell` somehow ? Or in your private layers ? 

You don't need `exec-path-from-shell-copy-envs` anymore. All the env. vars are now imported asynchronously at startup (fast enough before `user-config` is called).

**Comment by Chream** [comment]
I might of caught you error @Andre0991. exec-path-from-shell package was not loaded correctly.

Behavior is now as expected when launching emacs **from the shell**. All env variables are copied. When launching as GUI env variables put in .bash_profile are not picked up though.

**Comment by Andre0991** [comment]
I think @Chream is correct, https://github.com/syl20bnr/spacemacs/pull/10905 did the trick.

@syl20bnr  so what you said applies only when launching Emacs from shell, correct? To be more specific, getting env vars on macOS with GUI Emacs still requires the `osx` layer (which is expected) with @Chream path.

**Comment by Andre0991** [comment]
Well, actually, https://github.com/syl20bnr/spacemacs/pull/10905 won't work after restarting Spacemacs.
Perhaps the behaviour is inconsistent, I don't know - but it did install `exec-path-from-shell`.
If I run `exec-path-from-shell-initialize` manually, it works.

**Comment by syl20bnr** [comment]
You don't need `exec-path-from-shell-initialize` ! :-)
We are doing this ourselves and more efficiently at startup. Open an issue with your problem, we'll work on it there.

**Comment by Andre0991** [comment]
@syl20bnr, thanks for you patience, I just opened an issue.

**Comment by didibus** [comment]
I'm similarly no longer having the correct PATH setup, and exec-path-from-shell is no longer a selected package with latest develop pull. I'm on linux.
