### ISSUE TITLE
Using emacsclient and fonts

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#10894]
running emacs by `emacsclient -c -a ""` does not respect `dotspacemacs-default-font` and the frame font defaults to "Ubuntu Mono". Running simply `emacs` works fine.

**Comment by gdkrmr** [comment]
looking through the spacemacs source code, I came across the following [comment]( https://github.com/syl20bnr/spacemacs/blob/master/core/core-spacemacs.el#L114):

```
   ;; If you are thinking to remove this call to `message', think twice. You'll
   ;; break the life of several Spacemacser using Emacs in daemon mode. Without
   ;; this, their chosen font will not be set on the *first* instance of
   ;; emacsclient, at least if different than their system font. You don't
   ;; believe me? Go ahead, try it. After you'll have notice that this was true,
   ;; increase the counter bellow so next people will give it more confidence.
   ;; Counter = 1
```

So someone must have poured some thought into this before.

**Comment by dubnde** [comment]
I found out that if I close the frame without killing `emacs` and then run the `emacsclient` command again, the default font is then respected.

**Comment by gdkrmr** [comment]
you can add:
```
  (add-to-list 'default-frame-alist
               '(font . "-ADBE-Source Code Pro-normal-normal-normal-*-13-*-*-*-m-0-iso10646-1"))
```
to your `user-init` and it works

**Comment by dubnde** [comment]
I just synced to tip and updated packages. seems happy again

**Comment by Anntoin** [comment]
Seeing this as well on develop (b54ea8e) packages are up to date

The workaround from @gdkrmr  works for me

**Comment by weidtn** [comment]
How do I get the name for my font? I want to use Hack.

**Comment by gdkrmr** [comment]
`SPC SPC select-font` will give you a list with available fonts

**Comment by spijet** [comment]
Just checked the latest develop — the issue is still there. @gdkrmr's workaround fixes it for me. My OS is the latest Arch Linux with Emacs package version `26.1-2`.

**Comment by dmbfm** [comment]
The bug is still present in the latest develop too.

**Comment by gdkrmr** [comment]
I found that `emacsclient -c -a "emacs"` fixes quite a lot of problems, I haven't tested if it fixes this one though. Spacemacs can be configured to start the daemon process.

**Comment by c02y** [comment]
@gdkrmr  Not work for me.

**Comment by mrsipan** [comment]
Another alternative is to pass it to the `emacsclient` `-F` options, like so:

```bash
emacsclient -c \
  -F '((font . "-ADBE-Source Code Pro-normal-normal-normal-*-16-*-*-*-m-0-iso10646-1"))'
```

And of course you should make and shell alias for it.

**Comment by hariseldon78** [comment]
the issue is still present

**Comment by lebensterben** [comment]
Please open new issues with details instead.
