### ISSUE TITLE
Dumped emacs still lazy loads things

### ISSUE THREAD

**Issue by Kethku** [syl20bnr/spacemacs#10902]
#### Description :octocat:
Dumped emacs still lazy loads things.

#### Reproduction guide :beetle:
- Start Emacs from dumped file
- Open helm, open org file, open elisp file etc

*Observed behaviour:* :eyes: :broken_heart:
Helm takes 2ish seconds to open but after that is instant.
Org mode, elisp mode etc also takes a weird amount of time to boot up.

*Expected behaviour:* :heart: :smile:
Given that we are dumping the status of emacs into a file I would love a way to force these things to
preload so that the emacs that we run from the dumped file is fast and speedy. This is the promise
of the portable dumper, but it doesn't seem like we are utilizing it to the fullest of its ability.

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1abce5ec1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csharp vimscript csv clojure yaml autohotkey typescript c-c++ csharp pdf markdown javascript rust ruby html windows-scripts racket helm auto-completion emacs-lisp git version-control org latex
        (spell-checking :variables spell-checking-enable-by-default nil)
        syntax-checking frame-move
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS CANNOT_DUMP

**Comment by Kethku** [comment]
Note I tried calling (load "helm.el") and (load "org.el") in my user load function in the init.el file, but there is still an annoying delay when opening helm and an org file the first time.

**Comment by syl20bnr** [comment]
What about `(require 'helm-mode)` and `(require 'org)` ?

**Comment by et2010** [comment]
I observed similar behavior. I think the long loading time for elisp-mode is due to "just in time" load of yasnippet. I tried `(require 'org)` but the improvement is negligible. I'm using pdumper on windows.

**Comment by syl20bnr** [comment]
Yasnipet is on my list of packages to improve, the loading is so painful, I'm sure we can improve it.

**Comment by Kethku** [comment]
Correct me if I'm wrong, but the loading improvements you are talking about have to do with lazy loading. What I'm interested in is forcing as much of my config to load and preconfigure before I dump the config. I don't care if the dump file is huge, what I would like to go for is a dumped emacs which will never lazy load anything as it is already all loaded. I'm not super familiar with the mechanics of lazy loading in emacs however, so I don't know how to achieve this goal

**Comment by et2010** [comment]
It seems better if I put those lines in user-load:

```
(with-temp-buffer
  (org-mode))
(with-temp-buffer
  (emacs-lisp-mode))
```

**Comment by Kethku** [comment]
This works great in my config. I still run into problems with helm though as I don't know how to run helm without requiring user input. As a side effect I found that this setup improved the time from running emacs to the spacemacs buffer showing. I'm not sure how but thats a nice plus.

**Comment by et2010** [comment]
> As a side effect I found that this setup improved the time from running emacs to the spacemacs buffer showing.

Yeah, I noticed that too.

> I don't know how to run helm without requiring user input.

Me either. Also, I didn't figure out how to run emacs-purpose with this approach. @bmag could you shed some lights on this?

**Comment by bmag** [comment]
@et2010 I'm not running Emacs 27 and can't comment on how the pdumper works, but I don't think there should be something special about purpose. I did fix a bug yesterday that prevented purpose-mode from loading, so maybe that's why you couldn't run it.

**Comment by bmag** [comment]
Regarding YASnippet, can't we just use this?
```elisp
(require 'yasnippet)
(when yas-snippet-dirs
  (yas-reload-all 'no-jit))
```

**Comment by Kethku** [comment]
Unfortunately yasnippet still loads pausing perceptibly when opening a file with a mode that has snippets.  I still get a message in the message buffer:

```[yas] Prepared just-in-time loading of snippets successfully.```

However if I use the solution above with loading modes in a dedicated buffer, this pause is gone.

**Comment by Kethku** [comment]
The comment motivated me to retry loading everything from scratch.

Adding this:
```
  (spacemacs|when-dumping
    (dolist (d (directory-files package-user-dir t nil 'nosort))
      (unless (or (string-equal ".." (substring d -2))
                  (string-equal "." (substring d -1))
                  (not (file-directory-p d)))
        (message "%s" d)
        (dolist (f (directory-files d t "\\.el$" 'nosort))
          (unless (string-match-p ".*pkg\\.el$" f)
            (message "%s" f)
            (ignore-errors (load f t)))))))
```
to my user-load function fixed my issues with helm and org-mode however I am still noticing slow down in from yasnippet when I first open a buffer for a given major mode. I found the above snippet commented out in the core-dumper.el file. @syl20bnr can you give any insight as to why it was commented out? It seems to work pretty well in my limited testing and it provides a great experience, but I want to make sure I'm not missing something subtle.

**Comment by Compro-Prasad** [comment]
@Kethku If you have time then please look into https://github.com/syl20bnr/spacemacs/issues/11923 and https://github.com/syl20bnr/spacemacs/issues/11924

**Comment by syl20bnr** [comment]
@et2010 I added the function you proposed here: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-dumper.el#L68-L74

I also added a mechanism to do some pre-dump stuff at the layer layer.
For each used layer the function `<layer>/pre-dump` is called before dumping. I added `pre-dump` functions for `org`, `helm` and `emacs-lisp` layers.
