### ISSUE TITLE
org-projectile/capture opening todo file by default

### ISSUE THREAD

**Issue by cbyrohl** [syl20bnr/spacemacs#10914]
#### Description
When using org-projectile/capture in a project. A new buffer is opened for entering the capture. In the positon of old buffer of the project, the corresponding todo file is opened. After C-c C-c, the prompt is closed, but the todo file buffer remains instead of going back to the project file, making a SPC-b-p necessary explicitly in order to return. This behavior is somewhat unexpected for me as the regular org-capture returns to the initial project file after C-c C-c. How can I achieve a similar behavior for org-projectile/capture?

#### Reproduction guide
- Start Emacs
- Open project
- SPC-a-o-p
- Enter something to be captured
- C-c C-c

*Observed behaviour:*
Buffer of target todo.org shows

*Expected behaviour:*
Buffer of initial projectt file shows as happens for regular org-capture

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f1f8db002)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp latex git markdown
      (org :variables org-want-todo-bindings t)
      spell-checking syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LCMS2

**Comment by fbkarsdorp** [comment]
I'm experiencing the same. The 'problem' is with org-projectile, not spacemacs. Here's a hacky solution for single file configuration:

```elisp
(defvar project-todos "project.org")
(defvar org-capture-before-config nil)

(defadvice org-capture (before save-config activate)
  "Save the window configuration before `org-capture'."
  (setq org-capture-before-config (current-window-configuration)))

(add-hook 'org-capture-mode-hook 'delete-other-windows)

(defun org-capture-cleanup ()
  "Clean up the frame created while capturing via org-projectile."
  (when (get-buffer project-todos)
    (kill-buffer project-todos))
  (when org-capture-before-config
    (set-window-configuration org-capture-before-config)))

(add-hook 'org-capture-after-finalize-hook 'org-capture-cleanup)
```

**Comment by lawrsp** [comment]
this issue  is still there

**Comment by duianto** [comment]
The same/similar issue was reported (and closed as a duplicate of this issue) here:
may be a bug in org-projectile/capture #13540

Therefore we'll unstale this.

If `fbkarsdorp` is correct then this should be reported upstream.
