### ISSUE TITLE
setenv cannot set environment with '='

### ISSUE THREAD

**Issue by AshKash** [syl20bnr/spacemacs#10910]
#### Description :octocat:
setenv cannot set environment with '='

#### Reproduction guide :beetle:
- Start Emacs
- Add the following lines to your init:
(setenv "CGO_CPPFLAGS" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/include -std=gnu++11")

then run shell-command M-! env

*Observed behaviour:* :eyes: :broken_heart:

CGO_CPPFLAGS=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/include -std

*Expected behaviour:* :heart: :smile:
CGO_CPPFLAGS=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/include -std=gnu++11

Note:
If you manually eval-region or eval-buffer, then this problem disappears

It looks like when the string is sent to the environment, it is not properly escaped (during initial load), but weirdly works after spacemacs is properly initialized.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f1f8db002)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(python osx git ivy
        (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup nil spacemacs-default-company-backends
                         '(company-capf company-files))
        syntax-checking javascript better-defaults sql neotree ashmacs
        (go :variables go-tab-width 4)
        (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

**Comment by Miciah** [comment]
#10909 looks like it will fix this issue.

**Comment by Miciah** [comment]
https://github.com/syl20bnr/spacemacs/commit/6220ace290b247265de8fac66bd9e84bef388326 and https://github.com/syl20bnr/spacemacs/commit/d0401f864037f528fe3767583b531e447d9ffd6c should have resolved this issue.

@AshKash, can you confirm that this issue is resolved and close it if so?

**Comment by AshKash** [comment]
Seems to be fixed in latest devel branch
