### ISSUE TITLE
Mode line settings ignored in dumped emacs

### ISSUE THREAD

**Issue by Kethku** [syl20bnr/spacemacs#10917]
#### Description :octocat:
Emacs run from dumped file doesn't respect mode line settings

#### Reproduction guide :beetle:
- Set mode line theme to something on default:
   (setq dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 1.5))
- Dump config to file
- Start Emacs from dumped file

*Observed behaviour:* :eyes: :broken_heart:
Mode line has default sizing and separator

*Expected behaviour:* :heart: :smile:
Mode line has wave separator and 1.5 scaling

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f1f8db002)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csharp vimscript csv clojure yaml autohotkey typescript c-c++ csharp pdf markdown javascript rust ruby html windows-scripts racket helm auto-completion emacs-lisp git version-control org latex
        (spell-checking :variables spell-checking-enable-by-default nil)
        syntax-checking frame-move
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS CANNOT_DUMP

**Comment by Kethku** [comment]
This can be mitigated by adding (spacemacs-modeline/init-spaceline)  to the dotspacemacs/user-config

**Comment by Kethku** [comment]
I have since run into this problem again. Not sure why but the mode line gets reset when run from dumped emacs.

**Comment by Kethku** [comment]
@syl20bnr can you add the portable dumper label to this issue? It is still a frustration (and one of the only remaining ones) I have with the portable dumper strategy.

**Comment by joshcho** [comment]
I am having trouble with this as well. The dump does not load my user-config (no dump emacs does). I was running Emacs 27, and now I am trying with Emacs 28.
