### ISSUE TITLE
Scala / Ensime organize-imports command gets into an infite loop with hunk confirmation prompts

### ISSUE THREAD

**Issue by mdedetrich** [syl20bnr/spacemacs#10915]
#### Description :octocat:
When applying the `ensime-refactor-diff-organize-imports` command on a Scala source file (using the Scala layer), spacemacs gets
into an infinite loop when dealing with hunk collision 

#### Reproduction guide :beetle:
- Start Emacs (with Scala layer installed)
- Open a Scala source file
- Run the  `ensime-refactor-diff-organize-imports`

*Observed behaviour:* :eyes: :broken_heart:
A prompt opens with the following text.

`Please answer y or n. Hunk has already been applied; undo it? (y or n)`

Answering `y` or `n` then opens up the following prompt

`Hunk has already been applied; Undo it? (y or n)`

You then go into an infinite loop between these prompts, the only way to get out of it is to process `esc` or by
cancelling the command with `C-g`. Pressing `y` or `n` doesn't actually seem to confirm the command.

*Expected behaviour:* :heart: :smile:
Typing in `y` or `n` actually confirms the prompt and applies the change. Either that or there is no prompt at all and it just changes the imports automatically.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python yaml
        (scala :variables scala-auto-start-ensime t scala-enable-eldoc t scala-auto-insert-asterisk-in-comments t ensime-startup-notification nil)
        docker react javascript typescript html osx helm auto-completion emacs-lisp git markdown spell-checking syntax-checking
        (version-control :variables version-control-diff-tool 'git-gutter  version-control-diff-side 'left version-control-global-margin t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (quit)
  signal(quit nil)
  y-or-n-p("Hunk has already been applied; undo it? ")
  diff-apply-hunk()
  ensime-refactor-diff-apply-hunks()
  ensime-refactor-diff-apply-silently("/private/var/folders/ng/9wyv05tj5kb_223yz89k0kc0nx7lvc/T/ensime-diff-8403025337018751638.tmp")
  ensime-refactor-diff-handler((:procedure-id 1 :refactor-type organizeImports :diff "/private/var/folders/ng/9wyv05tj5kb_223yz89k0kc0nx7lvc/T/ensime-diff-8403025337018751638.tmp"))
  #f(compiled-function (G13 G14 g714) #<bytecode 0x416a7d21>)(--buffer-- --cont-- (:ok (:procedure-id 1 :refactor-type organizeImports :diff "/private/var/folders/ng/9wyv05tj5kb_223yz89k0kc0nx7lvc/T/ensime-diff-8403025337018751638.tmp")))
  apply(#f(compiled-function (G13 G14 g714) #<bytecode 0x416a7d21>) --buffer-- --cont-- (:ok (:procedure-id 1 :refactor-type organizeImports :diff "/private/var/folders/ng/9wyv05tj5kb_223yz89k0kc0nx7lvc/T/ensime-diff-8403025337018751638.tmp")))
  (lambda (&rest --cl-rest--) (apply (function #f(compiled-function (G13 G14 g714) #<bytecode 0x416a7d21>)) '--buffer-- '--cont-- --cl-rest--))((:ok (:procedure-id 1 :refactor-type organizeImports :diff "/private/var/folders/ng/9wyv05tj5kb_223yz89k0kc0nx7lvc/T/ensime-diff-8403025337018751638.tmp")))
  ensime-dispatch-event((:return (:ok (:procedure-id 1 :refactor-type organizeImports :diff "/private/var/folders/ng/9wyv05tj5kb_223yz89k0kc0nx7lvc/T/ensime-diff-8403025337018751638.tmp")) 3) #<process ENSIME Scala>)
  ensime-process-available-input(#<process ENSIME Scala>)
  ensime-net-filter(#<process ENSIME Scala> "0000cb(:return\n  (\n    :ok (\n      :procedure-id 1\n      :refactor-type organizeImports\n      :diff \"/private/var/folders/ng/9wyv05tj5kb_223yz89k0kc0nx7lvc/T/ensime-diff-8403025337018751638.tmp\"\n    )\n  )\n  3)")
```

**Comment by songpeng** [comment]
Is it a bug in ensime or just not working in  spacemacs?

**Comment by mdedetrich** [comment]
@songpeng Its hard to tell from just looking at it, is there an easy way to find out?

**Comment by songpeng** [comment]
how about using ensime in the vanilia Emacs?

**Comment by mdedetrich** [comment]
Sure thing, will try this on the weekend

**Comment by jypma** [comment]
I'm having the same issue with ensime 2.0.2 on vanilla emacs.

**Comment by allenjohnashton** [comment]
I am having this issue on vanilla emacs as well.

**Comment by mdedetrich** [comment]
I also tried it with vanilla emacs and had the same issue, will try and report upstream

**Comment by allenjohnashton** [comment]
Can you link to the report I would like to add info.  I am only experiencing this on linux but not on mac

**Comment by allenjohnashton** [comment]
@mdedetrich Have you reported upstream?

**Comment by mdedetrich** [comment]
@allenjohnashton Unfortunately I am really busy this week, I should be able to generate an issue by the end of the week
