### ISSUE TITLE
Low color contrast in spaceline-highlight face while running in terminal.

### ISSUE THREAD

**Issue by jsoo1** [syl20bnr/spacemacs#10916]
#### Description :octocat:
Low color contrast in spaceline highlight face when running in terminal.

#### Reproduction guide :beetle:
- Start Emacs using -nw or in terminal client.

*Observed behaviour:* :eyes: :broken_heart:
Very low color contrast in spaceline (the highlight face, particularly), like observed in https://github.com/TheBB/spaceline/issues/109 and https://github.com/TheBB/spaceline/issues/37.  I originally commented in those issues but I think my issue is related to the way spacemacs configures spaceline.

*Expected behaviour:* :heart: :smile:
Dark foreground colors in the spaceline highlight face for nice visibility.

#### Extra information :books:
Adding lines like the following in `.spacemacs` fixes the issue. So it seems like the spacemacs faces are getting overridden somewhere.

``` elisp
(set-face-attribute 'spacemacs-normal-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-hybrid-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-emacs-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-evilified-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-visual-face nil :foreground "#262626")
(set-face-attribute 'spacemacs-replace-face nil :foreground "#262626")
;; etc
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 390462e36)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((auto-completion
  (haskell :variables haskell-completion-backend 'dante))
 c-c++ clojure coq csv dash docker
 (elm :variables elm-format-command "elm-format")
 (emacs-lisp :variables emacs-lisp-hide-namespace-prefix nil)
 emoji
 erlang evil-snipe fsharp
 (git :variables git-magit-status-fullscreen t)
 graphviz
 (gtags :variables gtags-enable-by-default t)
 (haskell :variables haskell-process-type 'stack-ghci haskell-enable-hindent-style "fundamental")
 html
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 idris ivy
 (java :variables java-backend 'ensime)
 (javascript :variables tern-command
             '("node" "/usr/local/bin/tern"))
 (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill t latex-enable-folding t)
 lua
 (markdown :variables markdown-live-preview-engine 'vmd)
 nginx nixos
 (org :variables org-enable-reveal-js-support t org-enable-github-support t org-projectile-file "TODOs.org")
 osx python react restclient ruby rust
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts
 (spell-checking :variables spell-checking-enable-by-default nil)
 spotify sql swift syntax-checking systemd tmux treemacs twitter version-control vimscript vinegar windows-scripts yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by drewLo** [comment]
I'm experiencing a similar issue, with poor constrast in the emacs terminal, is this akin to your problem?

https://imgur.com/a/q2g4fH1

uhh, idk how to post images in an issue so there's the link.

**Comment by jsoo1** [comment]
Looking at `spacemacs/define-evil-state-face`:
```elisp
 (eval `(defface ,(intern (format "spacemacs-%s-face" state))
           `((t (:background ,color
                             :foreground ,(face-background 'mode-line)
                             :inherit 'mode-line)))
           (format "%s state face." state)
           :group 'spacemacs)))
```

Creates the faces, but according to https://www.gnu.org/software/emacs/manual/html_node/emacs/Standard-Faces.html, `mode-line` is
> ... The inverse of the default face on non-windowed terminals
The default face background color is `unspecified-bg` in terminal (at least how I see it now). I believe this is the problem. Would the solution be to make the foreground something specific if `(daemonp)` is non-nil?

**Comment by jsoo1** [comment]
This seems related to https://github.com/syl20bnr/spacemacs/issues/6197. Not sure the best way to proceed.
