### ISSUE TITLE
perl5 and perl6 need emacs.d to be in develop branch

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#10911]
why not push perl6 and perl5 updates in master branch please ?
I have to stay in develop branch for be able to have perl6 and perl5 layer working... then each time i open spacemacs i have to wait 20 minutes due to many hundred of update/re-install packages.

**Comment by CeleritasCelery** [comment]
You should only need to update when you pull. If it is updating/reinstalling packages every time you start that seems like a different issue.
