### ISSUE TITLE
Any way to exclude a package based on emacs version?

### ISSUE THREAD

**Issue by didibus** [syl20bnr/spacemacs#10929]
Any way to exclude a package based on emacs version? The dotspacemacs-excluded-packages will exclude for all version, but I share a config accross different emac version, and would like to only have certain versions exclude packages that don't work with them.

Thanks

**Comment by fiveNinePlusR** [comment]
you might be able to do something like this

```elisp
(when (string-match-p "^26" emacs-version)
        (add-to-list 'dotspacemacs-excluded-packages 'somepackage))
```

but you might need to do something more tricky to setq-default that value if that doesn't work
