### ISSUE TITLE
vim-easymotion alike word search?

### ISSUE THREAD

**Issue by libniwtr** [syl20bnr/spacemacs#10925]
Hi, everyone, 
I have just switched from vim to spacemacs, but I wonder is there any method to search words just like `easymotion-sn` in [vim-easymotion](https://github.com/easymotion/vim-easymotion)?
Just like the one demonstrated in section "n-character search motion" in their [homepage](https://github.com/easymotion/vim-easymotion), one can use `easymotion-sn` to search any word in current buffer in a tree fashion, and use `<Tab>` to scroll down/up a page, when one hits `<CR> `then a set of choices are highlighted so that one can jump to that point quickly. See:

![img](https://camo.githubusercontent.com/3ac76c9ea11d3b95ad5b07a24255e2fe73c131e4/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f333739373036322f323033393235342f34666266373237362d383939652d313165332d396266332d3165343436636162633039372e676966)

I've checked `avy-goto-char-timer`, it worked fine in current visible page but can not scroll up or down a page. Because I always need to navigate through the whole text, the `<Tab>` functionality is so important to me that becomes the only obstacle I am meeting with.

Thanks for anyone that could help.

**Comment by gdkrmr** [comment]
you can do `/word` and every match in the current buffer should be highlighted, press `ENTER` and then you can use `n` and `N` to jump around. With `SPC s c` you 'unhighlight'.

**Comment by 9527KGG** [comment]
+1,

Please add the support for easy motion. Even vscode vim https://github.com/VSCodeVim/Vim supports easy motion. Please consider.

**Comment by thouger** [comment]
i think [https://develop.spacemacs.org/doc/DOCUMENTATION.html#vim-motions-with-avy](url) is the answer.

**Comment by thouger** [comment]
i think [https://develop.spacemacs.org/doc/DOCUMENTATION.html#vim-motions-with-avy](url) is the answer.

**Comment by lebensterben** [comment]
right. the documentation can be improved by directly mentioning vim-easymotion.
