### ISSUE TITLE
Spacemacs on a system with pyenv can't use system Python

### ISSUE THREAD

**Issue by aeberspaecher** [syl20bnr/spacemacs#10934]
#### Description :octocat:

`nil` considered a valid Python interpreter. 

#### Reproduction guide :beetle:
- Start Emacs
- Load Python script
- Try to execute using `SPC m c c`

*Observed behaviour:* :eyes: :broken_heart:

On a system with pyenv and pyenv-which-ext that uses system Python, `spacemacs/pyenv-executable-find` returns nil instead of a path to the system Python executable. `SPC m c c` on a Python file calls `nil` as the Python interpreter. 

*Expected behaviour:* :heart: :smile:

Script executes using system Python/IPython.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bb013ef99)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(shell-scripts deft csv themes-megapack colors ipython-notebook
               (semantic :disabled-for emacs-lisp)
               gtags ranger pandoc games typography latex c-c++ evil-commentary octave python helm auto-completion better-defaults emacs-lisp git markdown org
               (shell :variables shell-default-height 30 shell-default-position 'bottom)
               spell-checking syntax-checking major-modes debug version-control pdf)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by sebhahn** [comment]
Is related to #10898?

**Comment by aeberspaecher** [comment]
@sebhahn, I don't think so as I can select virtual environments.

The problem still persists in recent master (e33638d9). I am certain the problem is in `spacemacs/pyenv-executable-find` because my problem is fixed if I comment out all the logic besides the closing `(executable-find command)`.

Can anyone take me through the function's intentions? Perhaps @cpaulik who wrote the code? What is considered the correct executable path to return in case pyenv uses system Python?

**Comment by cpaulik** [comment]
The original intention was to not fall back to the system executable automatically. See https://github.com/syl20bnr/spacemacs/pull/9348 

If a user has selected the system interpreter in ´pyenv´ then the function should return the system version of the executable.

**Comment by cpaulik** [comment]
Looking at the function again it does at the moment indeed return ´nil´ if the executable is not in the same path as the activated pyenv environment. So we might need a special case in the function for treating the ´system´ environment.
