### ISSUE TITLE
projectile-rails-mode seems to be on, but key chords don't work.

### ISSUE THREAD

**Issue by timfenney** [syl20bnr/spacemacs#10933]
#### Description :octocat:
projectile-rails-mode seems to be on, but key chords don't work.

#### Reproduction guide :beetle:
- Start Emacs
- Navigate to a Rails 5 project
- Open a controller file
- Try a key chord, such as `SPC m r f`

*Observed behaviour:* :eyes: :broken_heart:
Result `SPC m r f is undefined`.
Furthermore, entering `M-x projectile-rails-mode` results in a minibuffer message saying, `Projectile-Rails mode disabled in current buffer`. Running `projectile-rails-mode` again results in a message saying it has been enabled. In other words, it appears that `projectile-rails-mode` was running when the above issue (`SPC m r f is undefined`) is experienced.

*Expected behaviour:* :heart: :smile:
I expected to see a representation of a buffer filled with the contents of the model file corresponding to the controller file whose contents appeared to be in the current buffer at the time I executed the command.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6b4a79d39)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby ruby-on-rails)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by asok** [comment]
@timfenney if you are on develop the keybindings have changes recently. It's now `SPC m f` or `, f f` + the key for the command (like `, f f c` for `projectile-rails-find-controller`).
