### ISSUE TITLE
Transient hooks can break during buffer restore

### ISSUE THREAD

**Issue by dsedivec** [syl20bnr/spacemacs#10930]
#### Description :octocat:
Transient hooks can break when `dotspacemacs-auto-resume-layouts` is on.

#### Reproduction guide :beetle:
- Start Emacs 26 with fresh Spacemacs config from develop branch (I did holy mode but standard distribution; holy shouldn't matter)
- Edit `.spacemacs`:
    - Enable `spell-checking` and `syntax-checking` layers
    - Set `dotspacemacs-scratch-mode` to `'lisp-interaction-mode`
    - Set `dotspacemacs-auto-resume-layouts` to `t`
    - Add the following to `dotspacemacs/user-config`, which will crudely simulate a very long startup for creating `*scratch*`:
    ```elisp
  (add-hook 'spacemacs-post-user-config-hook
            (lambda () (sleep-for (+ persp-auto-resume-time 0.1)))
            t)
    ```
- Restart Emacs
- (If you got the error already you can stop here)
- Open `.spacemacs` again and don't kill it before exiting, so it will re-open on restart
- Restart Emacs

*Observed behaviour:* :eyes: :broken_heart:
```
run-hooks: Symbol’s function definition is void: spacemacs//transient-hook-lazy-load-flycheck
```

*Expected behaviour:* :heart: :smile:
No errors on startup

#### Further explanation

The/a problem here is that one buffer can be set up in the middle of another buffer's setup.  In this case, what's happening is that setting up `*scratch*` runs half of `prog-mode-hook`, but then persp-mode restores `.spacemacs` which also runs `prog-mode-hook`, including the lazy-load *transient hook* for Flycheck.  `.spacemacs` fully loads, the transient hook is deleted and removed from `prog-mode-hook`, but then when the loading of `*scratch*` proceeds it goes on to try and run Flycheck's transient hook again—which no longer exists.

The reproduction here is contrived, but I promise you I ran into this in my actual config—no `sleep-for` necessary.  It seems that, due to the volume of stuff that I/Spacemacs/Emacs does between when persp-mode sets up its timer (as part of `spacemacs-post-user-config-hook`) and when the hooks for `lisp-interaction-mode` get around to calling `flyspell-prog-mode`, at least 1 second passes (`persp-mode-auto-resume-time` is set to `1` by Spacemacs).

I worry that this is a general problem with transient hooks.  Perhaps rather than being undefined after running they should just be redefined to a no-op?  (Still good to remove them from the hook list.)

This was *really hard* to track down, and like twice as hard to reproduce.  Here's my poor attempt at explaining the above order of events in a bit more detail:

* The layers configured above basically set `prog-mode-hook` to `(flyspell-prog-mode  spacemacs//transient-hook-lazy-load-flycheck)` (among other unimportant members)
* Spacemacs tries to set up `*scratch*` in `lisp-interaction-mode` **wherein I believe `run-hooks` captures the value of `prog-mode-hook` (among others)**
* `run-hooks` calls `flyspell-prog-mode`
* which starts ispell
* which does `(sit-for 0)` as part of its setup
* which runs any timers
* persp-mode's "resume perspectives" timer runs
* which tries to resume `.spacemacs` (or some other `emacs-lisp-mode` file) **which causes `prog-mode-hook` to be run again—before it could completely run for `*scratch*`
* which (may) start ispell again, but more importantly, eventually runs `spacemacs//transient-hook-lazy-load-flycheck`
* which then **removes `spacemacs//transient-hook-lazy-load-flycheck` from `prog-mode-hook` and undefines it**—note that we're still restoring `.spacemacs`, `*scratch*` still hasn't finished setting up!
* Control eventually returns down through the persp-mode timer, through `flyspell-prog-mode`, and back to `run-hooks` **which is using the old value of `prog-mode-hook` with `spacemacs//transient-hook-lazy-load-flycheck` in it**
* `run-hooks` calls `spacemacs//transient-hook-lazy-load-flycheck` and fails since it has been undefined

#### System Info :computer:
- OS: darwin
- Emacs: 26.1.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bb013ef99)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree spell-checking syntax-checking)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
(Below is the backtrace from where the error occurs, but this isn't nearly as interesting as hacking the Flycheck transient lazy load hook to contain `(debug)` so you can see that *you're initializing `.spacemacs` inside the `run-hooks` for `*scratch*`*.)

```
Debugger entered--Lisp error: (void-function spacemacs//transient-hook-lazy-load-flycheck)
  spacemacs//transient-hook-lazy-load-flycheck()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook emacs-lisp-mode-hook lisp-interaction-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook emacs-lisp-mode-hook lisp-interaction-mode-hook))
  run-mode-hooks(lisp-interaction-mode-hook)
  lisp-interaction-mode()
  funcall(lisp-interaction-mode)
  (save-current-buffer (set-buffer "*scratch*") (funcall dotspacemacs-scratch-mode))
  (progn (save-current-buffer (set-buffer "*scratch*") (funcall dotspacemacs-scratch-mode)))
  (if (fboundp dotspacemacs-scratch-mode) (progn (save-current-buffer (set-buffer "*scratch*") (funcall dotspacemacs-scratch-mode))))
  spacemacs/startup-hook()
  run-hooks(emacs-startup-hook term-setup-hook)
  #f(compiled-function () #<bytecode 0x4248946f>)()
  normal-top-level()
```

**Comment by bmag** [comment]
Wow, that's one heck of a bug report, thanks for taking the time to investigate all this. What you wrote is very plausible, and your proposed solution is the same as what I had in mind:

> Perhaps rather than being undefined after running they should just be redefined to a no-op? (Still good to remove them from the hook list.)

Since `run-hooks` captures the value of the hook before running all the hooked functions (see below), it is safe to remove the transient function from the hook and redefine it to a no-op, instead of deleting the function. @syl20bnr do you agree?

---

Some evidence that supports @dsedivec explanation: a small experiment I ran shows that `run-hooks` indeed captures the value of the hooks: (Emacs 26.1)
```elisp
;;; evaluate following code:

(defvar my-test-hook nil)
(defun test-fn-1 ()
  (remove-hook 'my-test-hook 'test-fn-1)
  (message "TEST: 1"))
(defun test-fn-2 ()
  (remove-hook 'my-test-hook 'test-fn-2)
  (message "TEST: 2"))
(defun test-fn-rec ()
  (message "TEST: rec enter")
  (remove-hook 'my-test-hook 'test-fn-rec)
  (run-hooks 'my-test-hook)
  (message "TEST: rec exit"))

(setq my-test-hook '(test-fn-rec test-fn-1 test-fn-2))
(run-hooks 'my-test-hook)

;;; result: this text is added to *Messages* buffer:
;; TEST: rec enter
;; TEST: 1
;; TEST: 2
;; TEST: rec exit
;; TEST: 1
;; TEST: 2
```
The last two messages show that `run-hooks` captures the value of the hook, otherwise it wouldn't have ran `test-fn-1` and `test-fn-2` twice.

The same bug occurs also with the following repro recipe: paste the following into an empty buffer and run `eval-buffer` (`, e b` if the buffer is in emacs-lisp-mode):
```elisp
(defun create-elisp-buffer-for-test ()
  (when (string= (buffer-name) "test-buffer")
    (with-current-buffer (get-buffer-create "new-buffer")
      (emacs-lisp-mode))))

(remove-hook 'emacs-lisp-mode-hook 'create-elisp-buffer-for-test)

(spacemacs|add-transient-hook emacs-lisp-mode-hook
  (lambda () nil)
  lazy-load-a-bug)

(add-hook 'emacs-lisp-mode-hook 'create-elisp-buffer-for-test)

(switch-to-buffer (get-buffer-create "test-buffer"))
(emacs-lisp-mode)
```

**Comment by syl20bnr** [comment]
`lazy-load-a-bug` 😂 

Thank you for the great investigation of this nasty side effect. Should be fixed by https://github.com/syl20bnr/spacemacs/commit/a861177c4

@bmag @JAremko @sdwolfz let's put the Awesome 💜 label on great issues or PR etc..

**Comment by dsedivec** [comment]
Finally updated Spacemacs yesterday and I can confirm I'm no longer experiencing this problem.  Looks to me like you intended to close this with a861177, so I'll go ahead and close.  Thanks @syl20bnr for the fix, and for @bmag explaining the problem more simply than I could!
