### ISSUE TITLE
GitError! There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'.  

### ISSUE THREAD

**Issue by dmitry-saritasa** [syl20bnr/spacemacs#10942]
#### Description :octocat:

Trying to commit staged chunk with magit  (```M-m g s```, then ```c c```) and get this

```
GitError! There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'.  [Type `$' for details***
```

and in **magit-process** window

```
  1 git … commit --no-verify
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: Symbol’s function definition is void: magit-process
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```

If I start spacemacs in the standalone mode, **then magit still fails with the message above.**

**and If I run the following:**

```
/usr/bin/emacs -Q --eval \(setq\ debug-on-error\ t\) -L /home/dmitry/.emacs.d/elpa/magit-20180604.958/ -L /home/dmitry/.emacs.d/elpa/magit-popup-20180509.1041/ -L /home/dmitry/.emacs.d/elpa/with-editor-20180414.757/ -L /home/dmitry/.emacs.d/elpa/git-commit-20180602.1756/ -L /home/dmitry/.emacs.d/elpa/dash-20180413.30/ -L /home/dmitry/.emacs.d/elpa/ghub-20180417.1527/ -l /home/dmitry/.emacs.d/elpa/magit-20180604.958/magit
```
then everything works *but I get barebones empty emacs*

If I disable the $EDITOR variable (or even set it to vimx) I get a different behavior once spacemacs is started

```
GitError! There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server42980'.  [Type `$' for details]
```

so now the socket address is different 

<h2>

```diff
- /tmp/emacs1000/server
+ /tmp/emacs1000/server42980
```
</h2>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(gnus php yaml themes-megapack html javascript helm
      (auto-completion :variables auto-completion-enable-snippets-in-popup t)
      emacs-lisp
      (git :variables git-magit-status-fullscreen t magit-save-repository-buffers 'dontask magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
      markdown org
      (shell :variables shell-default-height 30 shell-default-term-shell "/usr/bin/zsh" shell-default-position 'bottom)
      (syntax-checking :variables flycheck-select-checker 'javascript-eslint)
      (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
      evil-commentary chrome python django dmitry)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Compro-Prasad** [comment]
This has also happened with me without spacemacs. Can you try reproducing this with just magit installed in emacs without any extra config and packages?

**Comment by hussein-aitlahcen** [comment]
I am experiencing the same issue under NixOS with magit.
When trying to commit, the command prompt fail to appear with this error:
```
Waiting for Emacs...
*ERROR*: Unknown command: /home/hussein/git/github/clever-tools-nix/.git/COMMIT_EDITMSG
error: There was a problem with the editor '/nix/store/1wkskl46vlbackbbcmcrvgv344gn3k84-emacs-26.1.50/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```

**Comment by r2evans** [comment]
@hussein-aitlahcen ... what env vars were missing? I'm experiencing a related error, and I'd like to know what you changed to fix it.

**Comment by allentiak** [comment]
Adding details:

#### Description :octocat:
Cannot make commits with magit

#### Reproduction guide :beetle:
- Start Emacs
- Open a Git project
- Modify any of its files
- Save changes
- Stage changes
- Write commit message
- Do "With editor finish"

*Observed behaviour:* :eyes: :broken_heart:
Changes are staged, but not commited.

This is the Messages buffer:
```
Auto-evilification could not remap these functions in map ‘edebug-mode-map’:
   - ‘edebug-Go-nonstop-mode’ originally mapped on ‘G’
evil-line-move: End of buffer [2 times]
evil-line-move: Beginning of buffer
Running git commit --
Type , c to finish, or , k to cancel
Diffing changes to be committed (C-g to abort diffing)
error in process sentinel: user-error: Don’t kill this buffer.  Instead cancel using , k
error in process sentinel: Don’t kill this buffer.  Instead cancel using , k
There was a problem with the editor '/usr/bin/emacsclient.emacs --socket-name=/tmp/emacs1000/server'. ... [See buffer magit-process: clojure-for-the-brave-and-true--walkthrough for details]
Saving file <path/to/repo>/.git/COMMIT_EDITMSG...
Wrote <path/to/repo>/.git/COMMIT_EDITMSG

```

*Expected behaviour:* :heart: :smile:
Changes should be committed.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: improve-colemak-support (rev. ff6be2446)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git
      (markdown :variables markdown-live-preview-engine 'vmd)
      multiple-cursors
      (neotree :variables neo-theme 'icons)
      org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking
      (version-control :variables version-control-diff-tool 'git-gutter+ version-control-global-margin t)
      (clojure :variables cljr-warn-on-eval nil clojure-enable-sayid t clojure-enable-clj-refactor t)
      (parinfer :variables ensure t progn
                (setq parinfer-extensions
                      '(defaults pretty-parens evil smart-tab smart-yank)))
      (keyboard-layout :variables kl-layout 'colemak-neio-inverted)
      latex ess)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

**Comment by Compro-Prasad** [comment]
Is `Do "With editor finish"` bound to `C-c C-c` / `, ,`?

**Comment by allentiak** [comment]
It seems to be solved in latest `develop`.

**Comment by allentiak** [comment]
It does not work again (see #12056)
 :-(

**Comment by allentiak** [comment]
It seems to be solved in latest `develop`, after regenerating `.spacemacs`.

**Comment by allentiak** [comment]
Finally, I found a way to reproduce this:

Add the following code to eiter the `(defun dotspacemacs/user-init ())` or the `(defun dotspacemacs/user-init ())` section of your `.spacemacs` file

``` elisp
 (setq-default
    magit-diff-refine-hunk 'all
    magit-diff-adjust-tab-width t
    magit-diff-paint-whitespace 'all
    magit-diff-highlight-trailing 'all
    magit-diff-highlight-indentation 'all)
```

**Comment by kryptt** [comment]
Magit requires both the server-socket-dir and the server-name to generate the correct socket file. 

I add to add a 

`  (setq server-name "emacs-26")`

(where emacs-26 is the actual socket filename inside the socket-dir ...

**Comment by allentiak** [comment]
> @allentiak Is `Do "With editor finish"` bound to `C-c C-c` / `, ,`?

Yes. (Sorry for the late reply...)

**Comment by countvajhula** [comment]
I encountered a similar message and turned out it was because Emacs had been upgraded (from 26 to 27) without my knowing it when I `brew install`ed something else, while Emacs was still running. Exiting emacs and then properly reinstalling it from the right homebrew keg (in my case, `emacs-mac`) fixed it for me.

**Comment by Sudakatux** [comment]
Im having the same problem. Using a 
Debian 10 : 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
Emacs was installed using snap and its version is 27.2 I pulled develop today. it was working perfectly fine before i pulled

**Comment by lebensterben** [comment]
@Sudakatux 
try a `git bisect` to find which commit breaks it
