### ISSUE TITLE
Python completion and go to definition does not work

### ISSUE THREAD

**Issue by majkijin** [syl20bnr/spacemacs#10940]
#### Description :octocat:
Python layer features 'go to definition' (SPC m g g) and completion does not work.

#### Reproduction guide :beetle:
- Start Emacs
- Open a python file
- Try both typing a defined in the file function to check completion.
- Try to find the definition using SPC m g g.

*Observed behaviour:* :eyes: :broken_heart:
- Neither completion feature nor 'go to' work. Nothing happens.

*Expected behaviour:* :heart: :smile:
- The name of the method/variable/function should be proposed by the completion system.
- SPC m g g should jump to the definition.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e2a5ed6)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript html markdown ivy auto-completion emacs-lisp git
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (python :variables python-test-runner 'pytest)
            (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
            gtags pandoc
            (c-c++ :variables c-c++-enable-clang-support t))
```
- System configuration features: JPEG SOUND GPM DBUS NOTIFY LIBSELINUX GNUTLS LIBXML2 ZLIB MODULES THREADS LIBSYSTEMD LCMS2

#### Additional info ####
The company-backends value:
```elisp
(company-anaconda
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)
Original value was
(company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
Local in buffer types.py; global value is nil
```

**Comment by robbyoconnor** [comment]
Try the LSP backend? http://develop.spacemacs.org/layers/+lang/python/README.html

**Comment by giuscri** [comment]
I can't reproduce. Current origin/develop is bb013ef99343fd730ee5cc188f2db00935d55c3a though.

**Comment by robbyoconnor** [comment]
I don't know if they installed everything they needed...

**Comment by Compro-Prasad** [comment]
@semihalf-dubiel-michal I can't reproduce this too. Can you give us more insight into this? DO you have any virtualenv?

**Comment by semihalf-dubiel-michal** [comment]
Yes I do have a virtualenv:
```
$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
astroid (1.6.2)
autoflake (1.1)
certifi (2018.1.18)
cffi (1.11.5)
chardet (3.0.4)
click (6.7)
confluent-kafka (0.11.4)
cryptography (2.2.2)
decorator (4.2.1)
dnspython (1.15.0)
envparse (0.2.0)
idna (2.6)
importmagic (0.1.7)
ipython (6.2.1)
ipython-genutils (0.2.0)
isort (4.2.15)
jedi (0.11.1)
kafka-python (1.4.2)
lazy-object-proxy (1.3.1)
mccabe (0.6.1)
parso (0.1.1)
pexpect (4.3.1)
pickleshare (0.7.4)
pip (9.0.3)
pluggy (0.6.0)
prompt-toolkit (1.0.15)
ptyprocess (0.5.2)
py (1.5.3)
pycparser (2.18)
pyflakes (1.6.0)
Pygments (2.2.0)
pylint (1.8.3)
pyOpenSSL (17.5.0)
pyzmq (16.0.3)
requests (2.18.4)
Rx (1.6.1)
RXPY (0.1.0)
setuptools (39.2.0)
simplegeneric (0.8.1)
six (1.11.0)
tinyrpc (0.9.1)
tox (3.0.0)
traitlets (4.3.2)
uhashring (1.0)
urllib3 (1.22)
virtualenv (16.0.0)
wcwidth (0.1.7)
Werkzeug (0.14.1)
wheel (0.30.0)
wrapt (1.10.11)
yapf (0.21.0)
```
I am activating that env with SPC m v a. It used to work before. I upgraded recently both spacemacs and packages and after that I lost the goto and completion functionality.

**Comment by sid-kap** [comment]
I'm having the same problem; even if I activate my venv, it's not clear whether spacemacs is loading `pyls` or not. How can I debug this?

**Comment by iamriel** [comment]
I have experienced this in the latest develop branch as of this writing with the commit 34be14 and after updating packages.  Rolling the package made it work again, so I'm guessing the problem is with anaconda-mode or any related package.  Right now I am using anaconda-mode version `20180808.625` and there is ` 20181010.1035` version available.
