### ISSUE TITLE
Previewing LaTeX fragments in Org no longer works

### ISSUE THREAD

**Issue by jgrosso** [syl20bnr/spacemacs#10944]
#### Description :octocat:
Functions and variables for previewing LaTeX fragments in Org are suddenly gone on latest `develop`. Note that manually evaluating `(require 'ox)` fixes the problem.

#### Reproduction guide :beetle:
- Start Emacs
- Evaluate `(plist-put org-format-latex-options :scale 1.8)`.

*Observed behaviour:* :eyes: :broken_heart:
The error `(void-variable org-format-latex-options)` will be thrown.

*Expected behaviour:* :heart: :smile:
The `org-format-latex-options` variable should be modified appropriately.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bb013ef99)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(react auto-completion c-c++ clojure coq csharp csv dash emacs-lisp games git go javascript
       (haskell :variables haskell-completion-backend 'intero)
       helm html markdown mu4e
       (org :variables org-enable-github-support t)
       osx pdf php purescript ruby-on-rails rust
       (shell :variables shell-default-shell 'eshell)
       spotify syntax-checking themes-megapack theming treemacs
       (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
       vimscript yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by Compro-Prasad** [comment]
Something like `(with-eval-after-load 'org (progn (require 'ox)))` in your `user-config` should solve the problem temporarily.

**Comment by Miciah** [comment]
`org-format-latex-options` is declared in `org.el`, so it is not obvious why `(with-eval-after-load 'org ...)` would help.  Has `org` been loaded when the error occurs? Can we get a backtrace?

**Comment by jgrosso** [comment]
@Miciah Strangely enough, `org-mode` _is_ available, but (for example) `(plist-put org-format-latex-options :scale 1.8)` gives the following backtrace:
```
Debugger entered--Lisp error: (void-variable org-format-latex-options)
  (plist-put org-format-latex-options :scale 1.8)
  eval((plist-put org-format-latex-options :scale 1.8) nil)
  eval-expression((plist-put org-format-latex-options :scale 1.8) nil nil 127)
  funcall-interactively(eval-expression (plist-put org-format-latex-options :scale 1.8) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by Compro-Prasad** [comment]
Might be that `org-latex` is an extra module that needs to be loaded using: `(setq org-modules '(org-latex))`?
