### ISSUE TITLE
Unable to load aspell dictionary

### ISSUE THREAD

**Issue by simendsjo** [syl20bnr/spacemacs#10959]
#### Description :octocat:
I get the following at repeat:

```
Starting new Ispell process /run/current-system/sw/bin/aspell with default dictionary...
Error enabling Flyspell mode:
(Error: No word lists can be found for the language "en_US".)
```

But running `aspell config` shows `en_US` among other languages, and `(getenv "LANG")` returns `en_US.UTF-8`. And `echo "doesntexist" | aspell -a` in the terminal works, so this seems related to emacs/spacemacs.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Loops forever trying to find dictionary (until aborted with C-g)

*Expected behaviour:* :heart: :smile:
Loads correct dictionary

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6220ace29)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp semantic neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      windows-scripts better-defaults csv
      (elfeed :variables elfeed-db-directory "~/Dropbox/elfeed/elfeeddb" rmh-elfeed-org-files
              (list "~/Dropbox/elfeed/elfeed.org"))
      (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-tab-key-behavior 'complete)
      evil-commentary
      (version-control :variables version-control-global-margin t version-control-diff-side 'left version-control-diff-tool 'git-gutter+)
      git github imenu-list html restclient yaml graphviz pandoc
      (markdown :variables markdown-live-preview-engine 'vmd)
      chrome
      (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t)
      deft plantuml sql floobits fsharp csharp racket elm python haskell purescript idris sml javascript react typescript nixos mu4e gnus erc calendar spell-checking syntax-checking bibtex theming colors)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by Liverm0r** [comment]
@simendsjo , have you manage to solve this?

**Comment by simendsjo** [comment]
> @simendsjo , have you manage to solve this?

I just turned off the spell checking, and been living without ever since :/
I tried turing spell checking on again now, and it looks like it's solved!
So no, I haven't solved, but yes, someone else has :)

**Comment by chen-chao** [comment]
The dictionary may be in other package if you've installed aspell using package manager, see 
[How do I add missing dictionaries for aspell? [closed]](https://superuser.com/questions/601928/how-do-i-add-missing-dictionaries-for-aspell)

**Comment by agzam** [comment]
afaik you have to enable flyspell-mode at least once. Otherwise any attempt to spellcheck or correct a mistake would throw that error.
