### ISSUE TITLE
Can't move around ansi-term as if it's a typical buffer.

### ISSUE THREAD

**Issue by giuscri** [syl20bnr/spacemacs#10956]
#### Description :octocat:
Can't move around ansi-term as if it's a typical buffer.

#### Reproduction guide :beetle:
- Start Emacs
- SPC SPC ansi-term
- Run `lscpu` in shell (or anything else that prints a bunch of lines)

*Observed behaviour:* :eyes: :broken_heart:
After pressing ESC, being in Normal again, pressing k doesn't allow me to go up
one line in the buffer.

*Expected behaviour:* :heart: :smile:
After pressing ESC, being in Normal again, pressing hjkl should allow me to move
around in the buffer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 666671a88)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml markdown javascript python helm
     (auto-completion :variables auto-completion-complete-with-key-sequence-delay 0)
     emacs-lisp git neotree
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by Miciah** [comment]
#10844 might fix this.

**Comment by giuscri** [comment]
ping

**Comment by maxstreese** [comment]
Any updates on this? :(

**Comment by lukeorland** [comment]
This fixed the problem for me: https://github.com/syl20bnr/spacemacs/issues/10779#issuecomment-427712967

summary: An Emacs 26.1 change causes this behavior, which can be fixed via a user-config setting.

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
shell: allow evil normal-mode movement in terminal buffer #12591
