### ISSUE TITLE
Cannot report issue using `report-issue`, and `%LAST_KEYS%` are not replaced.

### ISSUE THREAD

**Issue by aguadopd** [syl20bnr/spacemacs#10950]
#### Description :octocat:

When trying to report an issue from Github, the template text suggests instead doing it from within Emacs: 

> If you are posting about a *bug* please close this issue and open a new one
> using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
> bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
> You can delete this message to start typing.

When in Emacs, the reporting template does not work as expected. Two main observed things:

1. `C-c C-c` does nothing. The template suggests `C-c C-c` TO SUBMIT`.
2. `%LAST_KEYS%` are not being replaced with anything.

**Related issues**: #10833

#### Reproduction guide :beetle:

- Start Emacs
- Press `SPC h I` or `M-m h I` (in holy mode) (I = capital i) to report a bug.
- Press `C-c C-c`

*Observed behaviour:* :eyes: :broken_heart:

Nothing happens.

*Expected behaviour:* :heart: :smile:

A browser window is opened? The bug is somehow reported?

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((markdown :variables markdown-live-preview-engine 'vmd)
 helm auto-completion better-defaults emacs-lisp markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

----------------

Screenshot 1: `%LAST_KEYS%` is not found and hence not replaced

![emacs_2018-06-24_15-55-02](https://user-images.githubusercontent.com/5558299/41822667-b6ef7338-77c9-11e8-9568-bb81b93864c4.png)

Screenshot 2: there is no `C c`  after pressing `C c`

![emacs_2018-06-24_15-55-36](https://user-images.githubusercontent.com/5558299/41822670-bcb9c084-77c9-11e8-86ee-bcc8b5557b45.png)

**Comment by kommen** [comment]
I just tried to reproduce this, but it works as expected with the latest `develop` branch. Do you still have this problem?
