### ISSUE TITLE
ripgrep / rg stops working with Helm / helm-ag

### ISSUE THREAD

**Issue by iamriel** [syl20bnr/spacemacs#10953]
#### Description :octocat:
`ripgrep` stops working with `helm`

<img width="704" alt="screen shot 2018-06-25 at 4 16 17 pm" src="https://user-images.githubusercontent.com/4214373/41838489-210e01ca-7893-11e8-9319-1478bcc985ee.png">

**Putting `--` in the pattern removes the error**

<img width="902" alt="screen shot 2018-06-25 at 4 13 14 pm" src="https://user-images.githubusercontent.com/4214373/41838407-f44d2e36-7892-11e8-97de-6c15b7e4a353.png">

`helm-ag` works if I uninstall `ripgrep` but it is using `ag`.

#### Reproduction guide :beetle:
- Install `ripgrep`
- Start Emacs
- Open files in directory (projectile)
- Do `[SPC /]` to invoke `Helm Ag: Using rg`
- type some text/pattern

*Observed behaviour:* :eyes: :broken_heart:
```
error: The following required arguments were not provided:
    <PATTERN>
```

*Expected behaviour:* :heart: :smile:
searching using `rg`

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: dev (rev. 81c2eb8e4) *this is based on develop*
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible better-defaults django docker emacs-lisp git github html javascript markdown nginx
         (org :variables org-confirm-babel-evaluate nil)
         osx search-engine slack spotify sql theming vimscript yaml
         (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence
                          (kbd "jk"))
         (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
         (helm :variables helm-ag-base-command "rg --vimgrep --no-heading")
         (python :variables python-test-runner 'pytest)
         (restclient :variables restclient-use-org t)
         (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh" shell-default-height 50 shell-default-position 'top)
         (spell-checking :variables spell-checking-enable-by-default nil)
         (syntax-checking :variables syntax-checking-enable-tooltips nil)
         (version-control :variables version-control-global-margin t))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
N/A
```

#### Ripgrep
```
❯ rg --version
ripgrep 0.8.1 (rev c8e9f25b85)
+SIMD -AVX
```

**Comment by Compro-Prasad** [comment]
Maybe you have littered your configuration. I am using latest spacemacs and packages and Emacs 27 and everything works fine.

**Comment by iamriel** [comment]
I apologize if I missed some information in my Post but here's my spacemacs configuration https://github.com/iamriel/config/tree/master/spacemacs

Also, I am using Emacs 26.1

**Comment by iamriel** [comment]
I have identified the reason behind the error.  I have a custom `.ripgreprc` and adding `--max-columns` option causes the error.

Below is the content of my `.ripgreprc` file:

```
# Don't let ripgrep vomit really long lines to my terminal.
# --max-columns=150

# Add my 'web' type.
--type-add
web:*.{html,css,js}*

# Because who cares about case!?
--smart-case
```

I commented out the `--max-columns` option and it works fine again.  I am not sure if the issue is on ripgrep itself, but it works fine before I upgrade spacemacs and packages and updated my emacs version to 26.1.  I am not sure also which of the upgrades/updates caused the error. :(

**Comment by roblabla** [comment]
Maybe rg should be run with `--no-config` ? This disables reading .ripgreprc.

**Comment by bcc32** [comment]
I think cefcce2 should have closed this issue?  In particular, I am now able to run ripgrep with a `--max-columns=` option in my `.ripgreprc` and things seem to be working fine.

**Comment by duianto** [comment]
@bcc32 Thanks for testing.

**Comment by iamriel** [comment]
I have tested this on latest develop branch as of writing [bcc3f1](https://github.com/syl20bnr/spacemacs/commit/bcc3f1292d8110642e7e77f3ce98343caffe633e) and I can confirm that the error is now fixed. Thanks!
