### ISSUE TITLE
Magit: ssh keys are not working from within emacs

### ISSUE THREAD

**Issue by majkijin** [syl20bnr/spacemacs#10969]
#### Description :octocat:
The commit https://github.com/syl20bnr/spacemacs/commit/6220ace290b247265de8fac66bd9e84bef388326 has introduced some issue and pushing/pulling to/from remote (private) repositories that requires shh access by key does not work. If I checkout just before the mentioned commit it workes fine, I am able to fetch from the remote repositories.

Also, I am able to fetch the repos normally using `git` command line (outside the emacs). I have all the keys added into the ssh-agent. It seems that they are not imported properly by the emacs/magit.

#### Reproduction guide :beetle:
- Start Emacs
- Open some private GitLab project.
- Try to fetch changes from the remote repository, for example by issuing `SPC g s f u`.

*Observed behaviour:* :eyes: :broken_heart:
- Magit reports the error:
   ```
   fatal: Could not read from remote repository.

   Please make sure you have the correct access rights
   and the repository exists.
   ```

*Expected behaviour:* :heart: :smile:
- Magit should fetch the remote repository.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b54ea8e)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript html markdown ivy auto-completion emacs-lisp git
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (python :variables python-test-runner 'pytest)
            (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
            gtags pandoc
            (c-c++ :variables c-c++-enable-clang-support t))
```
- System configuration features: JPEG SOUND GPM DBUS NOTIFY LIBSELINUX GNUTLS LIBXML2 ZLIB MODULES THREADS LIBSYSTEMD LCMS2

**Comment by jluttine** [comment]
I had a similar problem but not with SSH passwords but username+token credentials. Normally, Kwallet asks them once with a dialog and stores them so that I never need to enter them again, but after the commit pointed out in the issue, I need to enter my credentials every time at the bottom of the Emacs window. Checking out the previous commit indeed fixed the issue.

**Comment by syl20bnr** [comment]
I think I found the problem. This is not confirmed to be the same on
GNU/Linux but at least on macOS this bug is due to the caching of the
environment variables.

`SSH_AUTH_SOCK` should not be cached. I'll add a black list of env. vars
to not import.

Current work-around is to `SPC f e e` and delete the line with the env
`SSH_AUTH_SOCK` and restart Emacs.

**Comment by rpls** [comment]
There are probably a few variables which shouldn't be cached. For example, `DBUS_SESSION_BUS_ADDRESS` gets updated login on my system.

**Comment by syl20bnr** [comment]
I pushed the modification for the management of env vars, see commit https://github.com/syl20bnr/spacemacs/commit/a013d8687 See the commit message and content for more info.

It supports an ignore list, for now I added both `SSH_AUTH_SOCK` and `DBUS_SESSION_BUS_ADDRESS`.

**Comment by semihalf-dubiel-michal** [comment]
Just to let you know the issue seems fixed. With the commit you pointed out, the ssh keys work fine as it used to previously. Should this issue be closed now?

**Comment by srgkoshelev** [comment]
I have the same issue with (freshly reinstalled from master) 0.200.13@25.3.1.

For some reason `SPC f e e` leads nowhere so workaround is slightly problematic. Upgrading to a013d86 added some new exciting errors and made spacemacs crash on start.

**Comment by jarohen** [comment]
FWIW, for fellow emacs newbies - one workaround is to `echo $SSH_AUTH_SOCK` from a terminal, and set it in your emacs session using `M-x setenv`

**Comment by randomphrase** [comment]
For the record `KRB5CCNAME` needs to be added to the list of environment variables not to cache. This is used for Kerberos authentication.

**Comment by lmichelbacher** [comment]
I've been using Emacs for almost twenty years and I have no idea what you mean by `SPC f e e`.

**Comment by xorb0ss** [comment]
@jarohen thanks, solution seemed to work! Shame it's temporary...
