### ISSUE TITLE
Please consider removing multi-term

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1096]
It's buggy as hell and make `ansi-term` unable to run interactive programs such as `fzf` and `top`. It makes people think that `ansi-term` is buggy, while in fact it's not.

**Updated**: It's not `multi-term` issue, but between `multi-term` and `zsh`.

**Comment by CarlQLange** [comment]
Multi-term works perfectly for me...

**Comment by tuhdo** [comment]
Did you try running `top` and other interactive programs?

**Comment by CarlQLange** [comment]
Yep, and they work just fine. Slowish redraw but otherwise no issue.

**Comment by tuhdo** [comment]
You are right. It is a problem with `zsh`. I normally use it with `bash` and had no problem. Sorry for the noise :(

But I think we should document the larger incompatibility between `ansi-term` and `zsh` and suggest users to use Bash for best results.

**Comment by CarlQLange** [comment]
Ah, huh - I actually use `zsh` by default as well. :)

Have you done `(setq multi-term-program "/bin/bash")`?

**Comment by tuhdo** [comment]
I used `zsh` with `oh-my-zsh`.

> Have you done (setq multi-term-program "/bin/bash")?

Yes, I did. That's why I said it was not `multi-term` fault.

**Comment by CarlQLange** [comment]
Sorry, I edited afterwards: `(setq multi-term-program "/bin/zsh")`

Yep, I also use oh-my-zsh. :)

**Comment by mijoharas** [comment]
@tuhdo, same as CarlQLange I use zsh and oh-my-zsh and multi-term works fine (with top working fine) for me.

**Comment by tuhdo** [comment]
Yea it was my work machine that had this problem. It works fine for my home machine. Sorry about this.
