### ISSUE TITLE
wired clipboard bug??

### ISSUE THREAD

**Issue by qm1900** [syl20bnr/spacemacs#10961]
Found a wired thing

every time I open a file by mouse clicking from the recent file list, if there is a text already put in my clipboard, it will be automatically pasted into the file I have opened.

**Comment by CPUFronz** [comment]
I can confirm that bug.

**Comment by Anntoin** [comment]
Looks like this is what you're seeing https://github.com/syl20bnr/spacemacs/issues/6765

**Comment by iggar** [comment]
I keep bumping into the same issue. At least to me this is a very dangerous one, as I keep finding random text (sometimes personal) in the middle of my code while doing git diff! :open_mouth: 
I wish I could help debug it. I can help testing a possible fix, though.

**Comment by duianto** [comment]
This is a duplicate of this issue:
Auto paste into the files opened by mouse-click the item below Recent Files in Spacemacs buffer #5435

This comment seems to be the most up voted workaround:
https://github.com/syl20bnr/spacemacs/issues/5435#issuecomment-195862080
