### ISSUE TITLE
Generating TODOs in calendar (org-mode) not working

### ISSUE THREAD

**Issue by MrMic** [syl20bnr/spacemacs#10963]
- Start Emacs
- Create a test.org file with TODOs inside
- Generate agenda view= SPC-a-a and SPC-a-t
- Calendar generated but nothing inside !!! even if I add timestamp or deadline ...
- I try this with emacs alone and all is fine! I can see TODOs ...

Thanks for fixing that.
Rgds,

PS: I have tried the standard way to send Bug Report, but nothing
happen when I press: C-c C-c !!!
Another Bug ???

**Comment by polyedre** [comment]
Do you added test.org to your agenda files ?
Do `org-agenda-file-to-front` or `C-c [` when you are inside the file.

**Comment by MrMic** [comment]
I  created an .agenda_files
and put the list of todo files in it.
use the emacs variable:
org-agenda-files

Now all is OK;
Thank you anyway.

I close.
