### ISSUE TITLE
Entering normal-state should exit compaly tooltip

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#1097]
I tried using:

``` elisp
(add-hook 'evil-normal-state-entry-hook 'company-pseudo-tooltip-hide)
```

to achieve this, but it doesn't appear to work. It's a rather minor annoyance of mine.

**Comment by syl20bnr** [comment]
Seems that not everybody gets this behavior. I get it but if I remove my layers it disappears.
@luxbock can you confirm that you don't have this behavior with a stock spacemacs config ?

**Comment by luxbock** [comment]
Using `master`, if I remove all of my own configurations and leave only the `auto-completion` layer, then `ESC` does what I wish, i.e. goes to `normal-state` and disables the company popup, so yes I can confirm your finding.

I'm trying to investigate which setting it is that causes it, and have narrowed it down to my `(eval-after-load 'evil ...)` block in my `dotspacemacs/config`.

**Comment by luxbock** [comment]
I have identified the culprit: `(setq evil-move-cursor-back nil)`. Perhaps it's the same for you as well?

**Comment by CestDiego** [comment]
@syl20bnr @luxbock I do exit company popup when I press (for example) `nj` which is my evil-escape key. BUT I'm back to insert mode. shouldn't it go to normal state? because If I wanted to modify sth in insert mode I shouldn't have to exit company tooltip, I'd just write more because for entering company popup you HAVE to be inserting text.

**Comment by TheBB** [comment]
Status on this? Seems to work as expected for me.

**Comment by mmcnl** [comment]
I can confirm that setting `evil-move-cursor-back` prevents exiting normal mode (either by the evil-escape sequence or `C-[`) from also closing the company tooltip.

(Thanks @luxbock for tracking the issue down to that setting -- I spent far too long trying unsuccessfully to add hook behavior to close the tooltip manually). 

It'd be great to be able to have both the `evil-move-cursor-back` setting and the expected tooltip closing behavior but it's definitely not killing any kittens.

**Comment by mmcnl** [comment]
Oh, looks like using this hook instead is giving the desired behavior, even when `(setq evil-move-cursor-back nil)` is set:
```
(add-hook 'evil-normal-state-entry-hook 'company-abort)
```

**Comment by fintelkai** [comment]
@mmcnl Thanks for the tip (https://github.com/syl20bnr/spacemacs/issues/1097#issuecomment-150756458). This had been driving me bonkers.

**Comment by aldanor** [comment]
Would this be a sensible default?

**Comment by StreakyCobra** [comment]
@aldanor You can create a PR with this if you feel motivated, this would be discussed there :-)

**Comment by aldanor** [comment]
Well, I'm not sure it *is* a sensible default for everyone -- if it is I could try and open a PR. For me it surely is, it is natural to expect that `fd` or `ESC` actually kill the company popup; if you want to ignore the popup and stay in insert mode -- you just continue typing and it will go away on its own.
