### ISSUE TITLE
perp-load-state-from-file broken on develop

### ISSUE THREAD

**Issue by Fabbi** [syl20bnr/spacemacs#10979]
#### Description :octocat:
Calling `persp-load-state-from-file` with an argument causes the adviced function `spacemacs//layout-wait-for-modeline` to crash as it does not take any arguments.

#### Reproduction guide :beetle:
- Start Emacs
- call `persp-load-state-from-file` with argument

*Observed behaviour:* :eyes: :broken_heart:
```elisp
apply: Wrong number of arguments: 
(lambda nil "Assure the mode-line is loaded before restoring the layouts." 
  (advice-remove 'persp-load-state-from-file 'spacemacs//layout-wait-for-modeline)
  (when (and (configuration-layer/package-used-p 'spaceline)
             (memq (spacemacs/get-mode-line-theme-name) '(spacemacs all-the-icons custom)))
    (require 'spaceline-config))), 1
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b54ea8ef9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm markdown lua
      (c-c++ :variables c-c++-enable-clang-support t c-c++-enable-c++11 t c-c++-default-mode-for-headers 'c++-mode)
      (python :variables python-sort-imports-on-save t python-tab-width 2)
      ipython-notebook latex shell-scripts emacs-lisp
      (auto-completion :variables auto-completion-tab-key-behavior 'complete auto-completion-return-key-behavior nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
      ycmd
      wakatime
      git
      (neotree :variables neo-banner-message nil)
      (org :variables org-projectile-file "TODO.org")
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking dash semantic gtags
      (version-control :variables version-control-diff-tool 'diff-hl))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by Miciah** [comment]
This issue looks like a duplicate of #10856.

**Comment by Fabbi** [comment]
Oh, I'm sorry, I searched but didn't find it, so I opened a new one. Can be closed than.
