### ISSUE TITLE
Error (use-package): evil-args/:catch: Symbol’s value as variable is void: - 

### ISSUE THREAD

**Issue by fladd** [syl20bnr/spacemacs#10994]
#### Description :octocat:
Spacemacs starts with the error:

Error (use-package): evil-args/:catch: Symbol’s value as variable is void: - 

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Error (use-package): evil-args/:catch: Symbol’s value as variable is void: - 

*Expected behaviour:* :heart: :smile:
No error message

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv html helm auto-completion emacs-lisp git github markdown org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking python ranger games deft selectric)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Miciah** [comment]
Try the workaround here: http://spacemacs.org/doc/FAQ.html#orgheadline5
