### ISSUE TITLE
[META] Migrate site to Docusaurus

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#11009]
[Docasaurus](https://docusaurus.io/) is a static website solution created by Facebook that allows for a blog, website, and documentation to all be hosted under one unified tree. Way better than Sphinx/ReadTheDocs. Docasaurus uses React. 

I wonder if we should consider migrating to it? I'm opening this issue to start the discussion. 

CC: @JAremko

**Comment by JAremko** [comment]
@robbyoconnor  I'll look into it. But the final decision is up to  BDFL :+1: __

**Comment by robbyoconnor** [comment]
cc @syl20bnr

**Comment by JAremko** [comment]
It looks like Docasaurus was largely made to speed up starting from scratch but we already have most of what we need(in foreseeable future). Also Docasaurus  is:
 - markdown based
 - requires backed
 - provides much more than we need
 - integration with payed (or with open source "strings attached" permission) services like crowdin
 - requires front-end tool-chain knowledge for maintaining
 - has a lot of dependencies (potential npm hell memes?)
 - Requires running local server to preview.

What we have now:
 - Documentation is organized and its structure mirrors layer structure
 - Site and docs are a bunch of static files that can be uploaded to any CDN or viewed locally.
 - We have http://spacemacs.org/ for master and http://develop.spacemacs.org/ for develop branches.
 - To convert docs from org to html you only need Emacs and you can do it locally with fast iteration loop.
 - We can use ORG format for everything including blogging and editing everything in org-mode.

There is a room for improvement (and I'm working on it) but I would really like to preserve the advantages above :shipit:

**Comment by robbyoconnor** [comment]
I'll nuke this issue then :)
