### ISSUE TITLE
Emacs doesn't seem to recognize .emacs.d on the latest Windows Insider Preview

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#11008]
#### Description :octocat:
I was able to use Emacs normally on Windows until the latest update to `Build 17711.rs_prerelease.180703-1539`. Now, whenever I start Emacs, it just shows the default welcome page, even though `.emacs.d` is still present in my home folder. It seems that it's just ignoring `.emacs.d` altogether. I wonder if this has something to do with some changes introduced in this update.

If I change `.spacemacs` to `.emacs`, Emacs does seem to pick it up and apply some settings (e.g. the `variable-pitch` font specification). However, it apparently still can't use `.emacs.d` properly and still shows the default welcome page.

Maybe it has something to do with the folder name which contains two dots. Is there a way to configure Emacs to look for a folder with a different name to `.emacs.d`?

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Default Emacs welcome page without any customization shows up.

*Expected behaviour:* :heart: :smile:
Spacemacs starts up.

- Emacs: `25.3.1 (x86_64-w64-mingw32)` from Emacs-w64 project
- System: Windows 10 Pro Insider Preview `Build 17711.rs_prerelease.180703-1539`

**Comment by robbyoconnor** [comment]
This isn't a spacemacs bug. 

Are you sure you placed the `.emacs.d` in the correct directory...Windows is notoriously shitty to work with.

**Comment by x-ji** [comment]
I know. Just thought to post here to see if anybody is encountering the same issue

It was working right before I installed the update so that shouldn't be the issue.

**Comment by robbyoconnor** [comment]
I wonder if the home dir changed?

**Comment by robbyoconnor** [comment]
Windows is definitely weird.

**Comment by x-ji** [comment]
Doesn't seem to be the case either as it apparently picks out the `.emacs` file in the same folder, which is really weird...

**Comment by robbyoconnor** [comment]
I'm not entirely sure -- but this is clogging up our issue tracker right now. There are issues which aren't suitable for here, this is one of them.

**Comment by x-ji** [comment]
Right. I just wanted to post it here so if somebody on Windows Insider Preview encounters the same issue they can chime in and discuss, as a considerable amount of Emacs users are Spacemacs users now. I'll just close the issue but it should still be searchable for people who are looking for this, if any. If nobody shows up then probably something peculiar happened to my system.

**Comment by robbyoconnor** [comment]
Yup -- I just don't wanna have our issue tracker clogged up

**Comment by x-ji** [comment]
@winsphinx Thanks for the info. That's why posting this can be helpful. Could you explain how you found out this workaround?

**Comment by winsphinx** [comment]
I don't know why exactly, but same problem occurred on totalcommand and some others. TC shows some options about privilege. So I 类推。
And it is not due to `.` or `.d`, for running directly by `runemacs.exe` is OK, it only failed when running by shortcut. And `gvim` is OK on my computer, which has `.vimrc` and `.vim` directory.

**Comment by SamHasler** [comment]
I had to do this at the CMD prompt for emacs to recognise where HOME was:

`setx HOME ^%HOMEDRIVE^%^%HOMEPATH^%`
