### ISSUE TITLE
Can't enable lsp layer

### ISSUE THREAD

**Issue by sid-kap** [syl20bnr/spacemacs#11001]
#### Description :octocat:
Can't enable lsp

#### Reproduction guide :beetle:
- add `lsp` to `dotspacemacs-configuration-layers` in `.spacemacs`
- Press `SPC f e R`

*Observed behaviour:* :eyes: :broken_heart:
Test fails:
```
** TEST: Each layer in [[file:/Users/sidharthkapur/.spacemacs::dotspacemacs-configuration-layers][dotspacemacs-configuration-layers]] can be found
*** PASS: python
*** PASS: helm
*** PASS: auto-completion
*** PASS: better-defaults
*** PASS: emacs-lisp
*** PASS: git
*** PASS: markdown
*** FAIL: lsp
```

*Expected behaviour:* :heart: :smile:
```
*** PASS: lsp
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((python :variables python-backend 'lsp)
 helm auto-completion better-defaults emacs-lisp git markdown)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by sid-kap** [comment]
Ah, looks like lsp is in the develop branch but not in master (or any release).
Should I switch to develop branch somehow? Or are there plans to release the lsp layer soon?

**Comment by sid-kap** [comment]
Figured out how to switch to develop

**Comment by haydenflinner** [comment]
In case anyone hits this in the future, it's usually as simple as `git checkout develop` from your .emacs.d folder :p

**Comment by picaschaf** [comment]
Still not released in master. Is that plan cancelled?

**Comment by duianto** [comment]
Nope not canceled, syl20bnr is working on spacelpa.

When there's something new for us to test, then it most likely will be posted here:
Beta testing of spacelpa ELPA repository on various OS distributions #12652

**Comment by robsmith11** [comment]
It would be good to add to the lsp layer docs that one needs to use the develop branch.  It took me a little while to figure out why it wasn't working.
