### ISSUE TITLE
magit-status-mode, evil-leader/set-key-for-mode, and evil-emacs-state

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#1101]
I'm trying to add a few keybinds for `magit-status-mode` to personalize my Git experience using `evil-leader/set-key-for-mode`. However, the keybinds do not appear to register while I'm in `evil-emacs-state`, which is the state set for `magit-status-mode`. If I exit it and go to something like normal state the keybinds are indeed registered. I can use the keybinds with leader mode in `evil-emacs-state` but the additional keybinds that I declared do not appear in that state.

(Not sure where the cause could be but decided to start here.)

**Comment by prepor** [comment]
+1

**Comment by TheBB** [comment]
Magit status is no longer in emacs state by default, so I consider this fixed. Leader keybindings should work there.
