### ISSUE TITLE
lsp javascript autocompletition not working

### ISSUE THREAD

**Issue by i-oliva** [syl20bnr/spacemacs#11015]
#### Description :octocat:
LSP javascript autocompletion does not work

#### Reproduction guide :beetle:
- npm i -g typescript javascript-typescript-langserver flow-language-server
- Start Emacs
- Add and install lsp and JavaScript layers
- Set javascript :variables to lsp
- Open a js file and try to use autocompletition

*Observed behaviour:* :eyes: :broken_heart:
I get this error:
`Company: backend company-lsp error "Wrong type argument: lsp--workspace, nil" with args (prefix)`

*Expected behaviour:* :heart: :smile:
Autocompletition should work according to the lsp and javascript docs.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9dc5ba843)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking lsp
      (javascript :variables javascript-backend 'lsp))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by pavilion** [comment]
If I run
`lsp-capabilities`
I get
condition-case: No language server is associated with this buffer

**Comment by pavilion** [comment]
And this is the issue I opened in spacemacs repo
https://github.com/syl20bnr/spacemacs/issues/11015

**Comment by dokeeffe25** [comment]
I'm also having this issue. I tried to compare the normal setup instructions here: https://github.com/emacs-lsp/lsp-javascript with what the layer does but didn't have much luck. It seems to match up ok, although I wouldn't be very confident looking at elisp code.

**Comment by Jackson-soft** [comment]
I'm also having this issue.

**Comment by pavilion** [comment]
@dokeeffe25 @Jackson-soft if you find a workaround to get proper autocompletition in spacemacs, it would be nice if you could share it here :)

**Comment by dokeeffe25** [comment]
I still haven't had any luck with this. The issue is more that the LSP server doesn't seem to start at all rather than just autocompletion not working.

I opened a file in debug mode and I get this:
```
Debugger entered--Lisp error: (cl-assertion-failed (lsp--cur-workspace "No language server is associated with this buffer."))
  cl--assertion-failed(lsp--cur-workspace "No language server is associated with this buffer." nil nil)
  lsp--get-document-symbols()
  lsp--imenu-create-index()
  imenu--make-index-alist(t)
  imenu-update-menubar()
  redisplay_internal\ \(C\ function\)()
```

**Comment by fiveNinePlusR** [comment]
as of now running `lsp-javascript-typescript-enable` when in a buffer enables the server to run and can be verified by using `lsp-capabilities` completion will work if you turn on company mode with `company-mode`. you can verify it is working by typing a few characters and then `M-m spc company-complete` and it should pop up the completions. 

this should be something that needs to be fixed with a hook but this is a workaround for now.

**Comment by pavilion** [comment]
Hi @fiveNinePlusR 
When I run `lsp-capabilities` once I did run `lsp-javascript-typescript-enable`  I get `Company: backend company-lsp error "Wrong type argument: arrayp, nil" with args (prefix)`.

**Comment by robert-zaremba** [comment]
I've added a Pull Request for `lsp-javascript-flow` support in the javascript layer
https://github.com/syl20bnr/spacemacs/pull/11659
