### ISSUE TITLE
multiple candidate breaks `spacemacs/jump-to-definition`

### ISSUE THREAD

**Issue by ztlevi** [syl20bnr/spacemacs#11029]
`spacemacs/jump-to-definition` breaks if it has multiple candidates tested in `lsp-python`. Both `xref-find-definition` and `lsp-ui-peek-find-definitions` are opened. It needs to be fixed. 
![image](https://user-images.githubusercontent.com/16655096/42676512-55dde7ec-862d-11e8-860b-1807553534b0.png)

But if we just call `lsp-ui-peek-find-definitions`, we have:
![image](https://user-images.githubusercontent.com/16655096/42676657-d7feea0a-862d-11e8-8f45-7e5fe4c80634.png)

If we call `xref-find-definition`, we have:
![image](https://user-images.githubusercontent.com/16655096/42676608-af4e7c42-862d-11e8-97bd-5f1cba9ae888.png)

@TheBB Looks like you are the one refactor this. Could you take a look at this? 

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: temp (rev. a4a9d7d83)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(spacemacs-completion spacemacs-editing spacemacs-editing-visual spacemacs-evil
                      (spacemacs-layouts :variables layouts-enable-autosave nil)
                      spacemacs-misc spacemacs-modeline spacemacs-navigation spacemacs-org spacemacs-project spacemacs-visual
                      (ranger :variables ranger-show-preview t)
                      (vinegar :variables vinegar-reuse-dired-buffer t)
                      (pandoc :variables org-pandoc-options
                              '((standalone . t)))
                      dash
                      (better-defaults :variables better-defaults-move-to-end-of-code-first t better-defaults-move-to-beginning-of-code-first t)
                      (colors :packages
                              (rainbow-mode))
                      prodigy search-engine
                      (ivy :variables ivy-enable-advanced-buffer-information t)
                      (syntax-checking :variables syntax-checking-enable-by-default t syntax-checking-enable-tooltips nil)
                      (spell-checking :variables spell-checking-enable-by-default t)
                      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-idle-delay 0.2)
                      (git :variables magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
                      (github :packages
                              (not magithub))
                      docker perforce
                      (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left)
                      (ibuffer :variables ibuffer-group-buffers-by 'projects)
                      (osx :variables osx-dictionary-dictionary-choice "Simplified Chinese - English" osx-command-as 'super)
                      (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "zsh")
                      shell-scripts deft chrome imenu-list treemacs react lsp
                      (latex :variables latex-build-command "LatexMk" latex-enable-folding t)
                      markdown
                      (org :variables org-startup-folded nil org-want-todo-bindings t org-enable-bootstrap-support t org-enable-github-support t org-enable-reveal-js-support t)
                      gpu yaml
                      (python :variables python-indent-offset 4 python-backend 'lsp python-sort-imports-on-save t python-test-runner
                              '(nose pytest))
                      (html :variables css-indent-offset 2 web-mode-markup-indent-offset 2 web-mode-css-indent-offset 2 web-mode-code-indent-offset 2 web-mode-attr-indent-offset 2 web-mode-sql-indent-offset 2 web-mode-attr-value-indent-offset 2)
                      (javascript :variables node-add-modules-path t javascript-backend 'lsp js2-basic-offset 2 js-indent-level 2)
                      (web-beautify :variables spacemacs--web-beautify-modes
                                    '((web-mode . web-beautify-html)))
                      (typescript :variables typescript-backend 'lsp typescript-indent-level 2)
                      emacs-lisp
                      (cmake :variables cmake-enable-cmake-ide-support t)
                      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t c-c++-enable-google-style t c-c++-enable-google-newline t c-c++-enable-c++11 t)
                      ztlevi
                      (chinese :packages youdao-dictionary :variables chinese-enable-youdao-dict t))
```

**Comment by bmag** [comment]
I'd like to debug this, but I don't understand the pictures and don't know how to reproduce whatever the bug is.

- in what file does the bug happen?
- what keys do you press to trigger the bug?
- in what ways does it break?
- what branch is "temp (rev. a4a9d7d83)"?

**Comment by ztlevi** [comment]
Thank you @bmag. Let me go through each question.

The problem is due to [this line](https://github.com/syl20bnr/spacemacs/pull/11004/commits/69cc3c8d8f1e38e1bdb62e5334bec2193e41c026#diff-816b6cb123504249f5d374833e8529c2R157) from my commit. It's not merged yet. And it will break if it has multiple candidates.

1. A simple file is like this, `|` is your cursor
```
import os

os.p|ath
```
2. press `gd (spacemacs/jump-to-definition)`
3. it breaks because `spacemacs/jump-to-definition` invoke both `lsp-ui-peek-find-definitions` and `xref-find-definition`
4. You can try `M-x magit-status b y`, search [this PR](https://github.com/syl20bnr/spacemacs/pull/11004) and then merge to test it.

And if we remove the line from my commit, it will invoke `xref-find-definition` instead of `lsp-ui-peek-find-definitions` which is not expected.

**Comment by bmag** [comment]
@ztlevi thanks, I'll try to debug it towards the end of next week.

**Comment by ztlevi** [comment]
I cannot reproduce this in recent updates. Maybe it's due to this setting https://github.com/syl20bnr/spacemacs/blob/develop/layers/+tools/lsp/packages.el#L59 . I am going to close this for now.
