### ISSUE TITLE
Evil Surround ds<textobject> no longer deletes surrounding 

### ISSUE THREAD

**Issue by dubnde** [syl20bnr/spacemacs#11021]
#### Description :octocat:
Evil Surround ``ds<textobject>`` no longer deletes surrounding 

#### Reproduction guide :beetle:
- Start Emacs
- Try run `ds<textobject>` to delete surrounding brackets. Could be any surround
like braces, quotes

*Observed behaviour:* :eyes: :broken_heart:
surround brackets are not deleting

*Expected behaviour:* :heart: :smile:
Should delete/remove surrounding brackets.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c1bde286e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((helm :variables helm-enable-auto-resize t helm-use-fuzzy 'source helm-no-header t)
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 better-defaults
 (c-c++ :variables c-c++-enable-rtags-support nil c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
 (colors :variables colors-colorize-identifiers 'variables)
 debug emacs-lisp evil-commentary
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 git
 (ibuffer :variables ibuffer-group-buffers-by 'projects ibuffer-show-empty-filter-groups nil)
 imenu-list json protobuf python semantic
 (shell :variables shell-default-full-span nil)
 shell-scripts spell-checking syntax-checking
 (syntax-checking :variables flycheck-display-errors-function #'flycheck-display-error-messages-unless-error-list)
 (templates :variables templates-private-directory "~/.spacemacs.d/templates")
 version-control yaml my-misc my-projectile my-c-c++ my-org cquery my-ycmd my-uml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Miciah** [comment]
This issue is a duplicate of #11019.

**Comment by dubnde** [comment]
@Miciah I do not observe the `yss` issue reported in https://github.com/syl20bnr/spacemacs/issues/11019 as `yss` works for me without without having to enter visual mode. So this issue is different for me at least.

**Comment by chriskaukis** [comment]
`ds<surround>` works for me. I'm thinking maybe because it's lazily loaded it's sporadic.

**Comment by dubnde** [comment]
Will try a clean install

**Comment by Nate-Wilkins** [comment]
@dubnde works for me too. Let us know if you're still running into this!

**Comment by chriskaukis** [comment]
Just to be clear, I still experience the adding surround not working `yss<textobject>`. #11019

**Comment by Miciah** [comment]
@chriskaukis, are you saying that entering visual mode does not make `yss<textobject>` work in normal mode?

**Comment by chriskaukis** [comment]
No, I'm saying `yss<txtobj>` doesn't work at all in normal. in visual mode, `s<txtobj>` works.

**Comment by Miciah** [comment]
If you do `M-:` and enter `(require 'evil-surround)`, does `yss<txtobj>` start working in normal mode?

**Comment by chriskaukis** [comment]
@Miciah Yup that made it work in normal mode.

**Comment by dubnde** [comment]
Clean install seems to fix. Looks like my `.spacemacs` startup file is behind the latest and greatest on tip. So need to bring it up to speed.

**Comment by dubnde** [comment]
I am gonna close this now since confirmed add `(require 'evil-surround)` to my `user-config` is an acceptable workaround for me.

**Comment by bmag** [comment]
Marking this as duplicate of #11019, as they both seem to be caused by incorrect lazy-loading of evil-surround.
