### ISSUE TITLE
emacsclient crashes first time; develop branch; emacs-git

### ISSUE THREAD

**Issue by jpathy** [syl20bnr/spacemacs#11036]
On spacemacs develop branch, using emacs 27.0(master branch): When used in daemon mode, `emacsclient -c` crashes the first time with `*ERROR*: Wrong type argument: stringp, nil`. It works fine connecting again. I see no errors in *Messages* or with `--debug-init`. 

It's not an upstream bug as `emacs -Q --daemon` has no such problems. How would i go about debugging it? It only happens with daemon mode; any help is appreciated.

**Comment by estownya** [comment]
I can confirm

**Comment by jadlers** [comment]
Same for me

```
#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4af499588)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
    ```elisp
    ((auto-completion :variables auto-completion-enable-snippets-in-popup t)
    better-defaults git helm
    (ranger :variables ranger-override-dired t ranger-cleanup-on-disable t)
    osx semantic
    (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term)
    (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t)
    (syntax-checking :variables syntax-checking-enable-by-default nil)
    bibtex latex markdown org c-c++ emacs-lisp go html javascript react games spotify xkcd)
    ```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
```

**Comment by estownya** [comment]
The issue was resolved after updating spacemacs and emacs
