### ISSUE TITLE
Symbol’s value as variable is void: ivy-highlight-grep-commands

### ISSUE THREAD

**Issue by goofansu** [syl20bnr/spacemacs#11043]
Error when startup Emacs:
`Error (use-package): ivy/:config: Symbol’s value as variable is void: ivy-highlight-grep-commands`

Imported by https://github.com/syl20bnr/spacemacs/commit/d2dab66724711aba77454f677771b59566bd6208

**Comment by bmag** [comment]
Your `ivy` package isn't up-to-date, you need to update it.
