### ISSUE TITLE
align no longer respects smart-tabs-mode

### ISSUE THREAD

**Issue by skebanga** [syl20bnr/spacemacs#11044]
#### Description :octocat:
`align` no longer respects `smart-tabs-mode`

#### Reproduction guide :beetle:
- Start Emacs
- open scratch buffer
- `SPC SPC c++-mode` : enables `c++-mode`
- `M-: (setq indent-tabs-mode t)` : enables `indent-tabs-mode`
- `M-: (setq smart-tabs-mode t)` : enables `smart-tabs-mode`
- enter the following text:

```
struct Foo
{
	int i;
	double d;
	char c;
};
```
- Select above text 
- `SPC x a a` : aligns

*Observed behaviour:* :eyes: :broken_heart:
TABS used for alignment

```
struct Foo
{
	int	i;
	double	d;
	char	c;
};
```

In the above, vertical alignment of `i`, `d` and `c` is achieved with tabs

*Expected behaviour:* :heart: :smile:
SPACES used for alignment

```
struct Foo
{
	int    i;
	double d;
	char   c;
};
```
In the above, vertical alignment of `i`, `d` and `c` is achieved with spaces

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2f50f2841)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp html javascript go lua octave csv git markdown neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      imenu-list version-control
      (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
      (ranger :variables ranger-show-literal nil)
      python yaml lori-cpp smart-tabs protobuf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
`align` is a built-in Emacs function, and smart-tabs-mode is not part of Spacemacs. Couldn't reproduce the issue with Emacs 26.1 and latest develop. I suggest a more detailed repro guide (a complete example file and specify which region of text is selected) or taking this issue elsewhere.

**Comment by skebanga** [comment]
@bmag I've updated the issue details with a repro guide. Please let me know if you can reproduce? Thanks!

**Comment by bmag** [comment]
Thanks, I've managed to repro now with the recipe given (after installing smart-tabs-mode). The problem seems to be in how you activate smart-tabs-mode. Using `M-: (smart-tabs-mode)` instead of `M-: (setq smart-tabs-mode t)` fixes the bug on my setup. I'm assuming that's not how you really activate smart-tabs-mode in your config, right?

**Comment by skebanga** [comment]
@bmag No, you are correct, I'm not. I'm actually using `.dir-locals.el` to activate it, as the requirement to use `smart-tabs` is a project specific requirement

```
((nil . ((indent-tabs-mode . t)
         (smart-tabs-mode . t))))
```

**Comment by skebanga** [comment]
@bmag your comment on using `M-: (smart-tabs-mode)` has lead me to find out how to add `eval` statements in `.dir-locals.el`

The following now works:

```
((nil . ((indent-tabs-mode . t)
	(eval . (smart-tabs-mode)))))
```

Thanks so much! I will close this issue

I've got so much still to learn! :(

**Comment by bmag** [comment]
@skebanga I'm sorry, I won't have time to help you further with this issue. It doesn't seem like a bug in Spacemacs, though, so maybe you can try and reproduce it in stock Emacs or ask at https://emacs.stackexchange.com
