### ISSUE TITLE
emojicons do not display in buffers?

### ISSUE THREAD

**Issue by biocyberman** [syl20bnr/spacemacs#11049]
I've enabled emoji layer but can't get the the emojicons to display in buffers (see the attached screenshot). They are shown in the cheat sheet menu, but I guess the cheat sheet uses raster images. So it is a problem with font. I already installed `symbola` font and enabled it in user-init() as suggested in https://github.com/syl20bnr/spacemacs/issues/6654:

```
(defun dotspacemacs/user-init ()
(set-fontset-font t 'unicode "Symbola" nil 'prepend)
  )
```
I am trying this in a almost empty spacemacs with no special customization.

![screenshot at 2018-07-18 00-37-48](https://user-images.githubusercontent.com/447942/42849317-fa0ead12-8a22-11e8-8a69-d8910e97a2fd.png)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown helm ess emacs-lisp emoji)
```

**Comment by Miciah** [comment]
The cheat sheet inserts the ASCII representation; emojify-mode (or alternatively emoji-cheat-sheet-plus-display-mode; Spacemacs installs both ) adds the overlays that replace the ASCII representations with the raster images.  Try `:emojify-mode<Enter>` (or `:emoji-cheat-sheet-plus-display-mode<Enter>`) to enable it manually, or use a hook; e.g., `(add-hook 'rcirc-mode-hook 'emojify-mode)`.

**Comment by biocyberman** [comment]
Tried enabling `emoji-cheat-sheet-plus-display-mode` manually and it worked.
