### ISSUE TITLE
`evil-want-Y-yank-to-eol` doesn't seem to work

### ISSUE THREAD

**Issue by korayal** [syl20bnr/spacemacs#11054]
#### Description :octocat:
when I set `evil-want-Y-yank-to-eol` variable to `t`, I still get
`evil-yank-line` behavior instead of "yanking from current cursor to the end-of-line"

#### Reproduction guide :beetle:
- Start Emacs
- set `evil-want-Y-yank-to-eol` to `t`
- Write a text and go into the Normal mode
- Navigate to the middle of a line
- press `Y`
- Paste it's content to the line below

*Observed behaviour:* :eyes: :broken_heart:
The whole line get's copied

*Expected behaviour:* :heart: :smile:
The copied part should begin with where the cursor is

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2f50f2841)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(rust nginx vimscript shell-scripts csv helm dash
      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
      semantic themes-megapack ibuffer ranger fasd
      (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu4e" mu4e-use-maildirs-extension t mu4e-enable-async-operations t mu4e-enable-mode-line t)
      restclient emacs-lisp git html sql php octave
      (javascript :variables js2-basic-offset 2 js-indent-level 2 node-add-modules-path t)
      coffeescript purescript markdown neotree org
      (python :variables python-auto-set-local-pyvenv-virtualenv 'on-visit python-test-runner
              '(nose pytest))
      ipython-notebook
      (haskell :variables haskell-enable-hindent t haskell-completion-backend 'intero)
      yaml
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-full-span nil shell-default-shell 'ansi-term shell-default-term-shell "/usr/bin/fish")
      syntax-checking version-control
      (ycmd :variables ycmd-python-binary-path "/home/korayal/.virtualenvs/soostone/bin/python" ycmd-server-command
            '("python3.5" "/home/korayal/test/EMACS/ycmd/ycmd"))
      pdf epub better-defaults colors w3m
      (evil-snipe :variables)
      docker)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
-

**Comment by Miciah** [comment]
How did you set `evil-want-Y-yank-to-eol`? I specify the `vim-style-remap-Y-to-y$` variable in the editing-style setting in the `dotspacemacs/init` function definition in the `.spacemacs` file:
```emacs-lisp
   dotspacemacs-editing-style '(vim :variables
                                    vim-style-remap-Y-to-y$ t)
```
Then Spacemacs uses `customize-set-variable` to set `evil-want-Y-yank-to-eol`: https://github.com/syl20bnr/spacemacs/blob/b252d252b0e93249b51400f60a0c69a59aa140a4/layers/%2Bdistributions/spacemacs-bootstrap/packages.el#L92-L93

**Comment by korayal** [comment]
OK, now I see what happened. I've missed this ( https://github.com/syl20bnr/spacemacs/commit/9539e4206d3861a4f6f4cb13967fb3b5c1f7ff95#diff-411a2969fe619b3c95df8066ba35fe4a )  change and during a sync to the default template I lost the part that handles this.

**Comment by Miciah** [comment]
Oops, yeah, I linked to the master branch's version of `layers/+distributions/spacemacs-bootstrap/packages.el` instead of the develop branch's: https://github.com/syl20bnr/spacemacs/blob/6220ace290b247265de8fac66bd9e84bef388326/layers/%2Bdistributions/spacemacs-bootstrap/packages.el#L85-L86

I'm glad we got that sorted out!
