### ISSUE TITLE
purescript layer: error in process sentinel

### ISSUE THREAD

**Issue by AveryLychee** [syl20bnr/spacemacs#11055]
#### Description :octocat:
Upon opening a `.purs` file Purescript layer causes repeated error:

```
error in process sentinel: json-read: End of file while parsing JSON
error in process sentinel: End of file while parsing JSON
```

#### Reproduction guide :beetle:
- Install purescript
- Start Emacs
- Add `purescript` to `dotspacemacs-configuration-layers`
- Open a purs file

*Observed behaviour:* :eyes: :broken_heart:
functioning of spacemacs repeatedly frozen with error message

*Expected behaviour:* :heart: :smile:
spacemacs behaves as it usually does when there's a text file in the current buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(purescript javascript elixir yaml idris haskell html shell-scripts markdown ivy auto-completion emacs-lisp syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS NOTIFY ACL GNUTLS FREETYPE XFT ZLIB GTK3 X11

**Comment by TJTorola** [comment]
I am getting the same error, but on a `.js` file.

**Comment by kRITZCREEK** [comment]
Pretty sure the error message has gotten better since then, but the issue here is that one needs to run `psc-ide-start-server` and pick the project root to get the ide features. I think this issue can be close unless @AveryLychee still runs into trouble after my suggestion.
