### ISSUE TITLE
helm-projectile-switch-project emits error when selecting project

### ISSUE THREAD

**Issue by skebanga** [syl20bnr/spacemacs#11056]
#### Description :octocat:

I have a project open and execute `projectile-kill-buffers` (`SPC p k`)

All project-related buffers are killed

I then attempt to open a different project by executing `helm-projectile-switch-project` (`SPC p p`)

A helm-mini-buffer is displayed with recent projects.

I select one, and instead of showing a list of recent buffers, an error is emitted (See below)

Restarting emacs fixes the problem

*Observed behaviour:* :eyes: :broken_heart:

```
In ‘Projectile files’ source: ‘#[0 \301 \205;r\302!\203\206p\211q\210\303 \304 \305\211:\2036@\262\306"BB\262A\262\202\211\237\266\204)\207 [helm-current-buffer projectile-project-p buffer-live-p projectile-project-root projectile-current-project-files nil expand-file-name] 8]’ 
 (error "You’re not in a project")
```

*Expected behaviour:* :heart: :smile:
I can open the project

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2f50f2841)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp html javascript go lua octave csv git markdown neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      imenu-list version-control
      (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
      (ranger :variables ranger-show-literal nil)
      python yaml lori-cpp smart-tabs protobuf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by giuscri** [comment]
Cant' reproduce with Emacs 26.1, same spacemacs HEAD.
