### ISSUE TITLE
Replacing in visual selection does not work.

### ISSUE THREAD

**Issue by x3rAx** [syl20bnr/spacemacs#11067]
#### Description :octocat:
With vim you could select a region eg. a few words in a line and while in visual mode, you can press `:` which results in a command line `:'<,'>`. You can then type `s/\%V /-/g` so that the complete command looks like this: `:'<,'>s/\%V /-/g`. When you press enter, all spaces in the visual selection will be replaces with a `-`.

In Spacemacs (EVIL mode) this does not work. 

#### Reproduction guide :beetle:
- Start Emacs
- Open scratch buffer
- Type four or more words (e.g. `here are some words`)
- Hit `ESC` to leave insert mode
- Type `0w` (point is now at second word)
- Type `v$` to enter visual mode and select to end of line
  Selection should look like this:
  ```
  here are some words
       ^^^^^^^^^^^^^^
  ```

- Type `:s/\%V /-/g`
- Hit `Enter`

*Observed behaviour:* :eyes: :broken_heart:
Status line says "Replaced 0 occurences"

*Expected behaviour:* :heart: :smile:
Every space in the selection should have been replaced with a `-`. So the line should look like this: 

```
here are-some-words
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html ansible vimscript javascript yaml python php markdown helm auto-completion emacs-lisp git org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by Miciah** [comment]
Upstream issue: https://github.com/emacs-evil/evil/issues/513

**Comment by x3rAx** [comment]
So it works with:

    (setq evil-ex-visual-char-range t)

Even better than in vim itself because you don't need that `\%V`. :heart_eyes: 

Thank you :+1: and sorry, I didn't see that issue before.
