### ISSUE TITLE
Ivy 'other window' on candidate file does not respect projectile root path

### ISSUE THREAD

**Issue by Cbeck527** [syl20bnr/spacemacs#11063]
#### Description :octocat:
Ivy 'other window' on candidate file does not respect projectile root path

#### Reproduction guide :beetle:
- Start Emacs
- Open file in projectile project one folder deep (i.e. not at the root of the project `PROJECT_ROOT/subdir/test.json`)
- `SPC p f` to run `counsel-projectile-find-file`
- Select candidate in different subtree (i.e. `PROJECT_ROOT/subdir2/other.json` which appears as `subdir2/other.json` in the list of candidates)
- `M-o j` to open the candidate in 'other window'

*Observed behaviour:* :eyes: :broken_heart:
File is opened relative to position of current file, rather than the root of the project.
With the examples above the file that is opened is `PROJECT_ROOT/subdir/subdir2/other.json`.

*Expected behaviour:* :heart: :smile:
The candidate is open using the `PROJECT_ROOT` as the base of the path.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2f50f2841)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(csv sql ansible
     (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete)
     dash deft docker emacs-lisp git github
     (go :variables go-tab-width 4 gofmt-command "goimports")
     html ivy
     (javascript :variables js-indent-level 2)
     (markdown :variables
               '(markdown-pre-face
                 ((t
                   (:foreground "#586e75")))))
     nginx
     (org :variables org-enable-bootstrap-support t org-enable-github-support t org-enable-reveal-js-support t org-projectile-file "TODOs.org")
     osx
     (python :variables python-test-runner
             '(pytest nose))
     (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rbenv ruby-test-runner 'rspec)
     shell-scripts
     (spell-checking :variables spell-checking-enable-by-default nil)
     syntax-checking swift terraform
     (version-control :variables version-control-global-margin t version-control-diff-tool 'diff-hl)
     yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by timor** [comment]
I can confirm this behavior in recent develop branch.

cc @spacefrogg

**Comment by timor** [comment]
Seems to be working for me in develop.

@spacefrogg Can you confirm?

**Comment by spacefrogg** [comment]
It actually works again for me, too. So, is this solved or the error just masked again?...
