### ISSUE TITLE
Unable to send a bugreport without logging into github before that

### ISSUE THREAD

**Issue by vityafx** [syl20bnr/spacemacs#11076]
#### Description :octocat:
Unable to send a bug report using <SPC h I> keyboard shortcut. The spacemacs opens browser trying to put bug report
data inside GET paramaters but it is impossible to have a success until you log in into github before that. I am not
sure is there anything wrong with github or with anything else, but I think this issue needs some explanation or even
fixing if there is a problem on the spacemacs's side.

#### Reproduction guide :beetle:
- Start Emacs
- Open bug report buffer (<SPC h I>)
- Write the bug report
- Try to send this bug report

*Observed behaviour:* :eyes: :broken_heart:
The browser is opened with something like "https://github.com/login?redirect=github.com/create_issue" where github
reports error 500.

*Expected behaviour:* :heart: :smile:
There is no error when you try to send a bug report without logging into github before that.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.200.10
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml sql sailfish-developer extra-langs racket lua rust
      (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
      markdown version-control helm emacs-lisp git github
      (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by smile13241324** [comment]
The reason for the 500 return code you are seeing when you are not logged in is that spacemacs tries to create an issue which is a protected operation hence it requires you to be logged in on github. This seems to be not properly covered on githubs side therefore their general "some thing went wrong" message is shown.

I have checked the documentation and did find this function not mentioning that you need to be logged into github. For a first step I would expand the documentation here making clear that you need to be logged into github to write issues.

For a second step I think it would be worth discussing here whether it would make sense to change spacemacs behaviour to somehow detect that the user is not logged in and ask for github credentials to do the login before the browser is started.

**Comment by Compro-Prasad** [comment]
@sdwolfz Please add a fixed label.
