### ISSUE TITLE
Org layer: Inconsistent key bindings for navigating headers

### ISSUE THREAD

**Issue by teodorlu** [syl20bnr/spacemacs#11079]
#### Description :octocat:

Key bindings for heading navigation in Org-mode are inconsistent. Bindings:

- `outline-previous-visible-heading` -- unbound
- `outline-previous-heading        ` -- bound to `g p`
- `outline-next-visible-heading` -- bound to `g l`
- `outline-next-heading        ` -- unbound

Before, `C-c C-p` (previous visible) and `C-c C-n` (next visible) were consistent. With the current version of Spacemacs, `C-c C-p` opens Projectile's key map.

Suggestion: bind `g p` (or a more approperiate key combination) to previous visible. I've never wanted to navigate between headers I cannot see. Instead, the cursor just "gets stuck" on a heading.

#### Reproduction guide :beetle:
- Start Emacs
- Open an org document with multiple headers, and collapsed subeadings
- Navigate around collapsed subheadings with `g p` and `g l`

*Observed behaviour:* :eyes: :broken_heart:

- Observe lack of symmetry

*Expected behaviour:* :heart: :smile:
- Navigate up and down the same way!

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(vimscript common-lisp rust nginx ruby php csv yaml lua javascript windows-scripts octave sql elm html haskell python clojure org docker ivy
           (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
           emacs-lisp git markdown ranger spell-checking syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by teodorlu** [comment]
I seem to have ignored the `g NAVKEY` bindings in Evilified org mode.

- `g h`: outline-up-heading
- `g j`: org-forward-heading-same-level
- `g k`: org-backward-heading-same-level
- `g l`: outline-next-visible-heading

I still miss `C-c C-p` and `C-c C-n`, but it may be just a matter of getting used to it. I'm open to comments.

**Comment by timor** [comment]
With a recent version in develop, I think it is even more confusing.

`g h` and friends are bound to dwim-commands like `org-up-element` (see the bindings described in https://github.com/Somelauw/evil-org-mode/blob/master/doc/keythemes.org).

Using these, I cannot navigate headings in a practical manner, as they e.g. either only can be used to move into child elements, or do something like jumping to drawers instead of the next heading.  Am I missing some commands specifically targeted at navigating headings here?

**Comment by timor** [comment]
In my humble opinion, org mode navigation is still clumsy. However, I think a transient state based on the evil-org-mode bindings could be useful.  Or is there something like this and I missed it?
