### ISSUE TITLE
Unable to write "fd" quickly in any buffer

### ISSUE THREAD

**Issue by vityafx** [syl20bnr/spacemacs#11075]
#### Description :octocat:
Whenever I enter "fd" in edit mode (as in VIM) and I do this quickly, the text is just cleared and so I can't write
"fd" quickly but with a second delay or so.

#### Reproduction guide :beetle:
- Start Emacs
- Open any writable buffer
- Type "fd" quickly (there is a very little delay between pushing "f" and "d" buttons).

*Observed behaviour:* :eyes: :broken_heart:
After pushing "f" button the text ("f") is appended to the buffer at current caret position but after pushing "d" button the text ("f") is deleted and the caret moved back.

*Expected behaviour:* :heart: :smile:
You are able to write text consisting of "fd" quickly without any problems.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.200.10
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml sql sailfish-developer extra-langs racket lua rust
      (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
      markdown version-control helm emacs-lisp git github
      (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by eullerborges** [comment]
Duplicate of #4306.

This is the default behaviour on spacemacs. See [here](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#escaping).

**Comment by vityafx** [comment]
Thanks.
