### ISSUE TITLE
auto-completion keybindings broken in vanilla config

### ISSUE THREAD

**Issue by manveru** [syl20bnr/spacemacs#11070]
#### Description :octocat:

Completion is broken in interesting ways, I haven't checked all keybings, just the ones I usually use, and they're all broken.

I also tried going back in the `develop` branch history, since I'm sure it worked at some point, but couldn't find any commit that did.

#### Reproduction guide :beetle:

- Clone a fresh spacemacs config
- Start Emacs
- Enable the `auto-completion` layer
- `SPC f e R` or restart
- try completing anything in the `.spacemacs`

*Observed behaviour:* :eyes: :broken_heart:

- `C-n` closes completion popup and randomly shows strings, not sure what the pattern is
- `C-p` the same as `C-n`
- `C-d` works for the first time, the second time won't show the documentation buffer again

*Expected behaviour:* :heart: :smile:

- `C-n` should act like `TAB`
- `C-p` should act like `S-TAB`
- `C-d` should work repeatedly

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d9eecb760)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:

None

**Comment by manveru** [comment]
So it seems like the `C-n`/`C-d` issue can be fixed by putting

```
(define-key company-active-map (kbd "C-n") 'company-select-next)
(define-key company-active-map (kbd "C-p") 'company-select-previous)
```

in the `dotspacemacs/user-config`, but `C-d` behavior is still broken.

**Comment by Miciah** [comment]
Your report says that you are using the vim editing style; in this style, you should use <kbd>C-j</kbd> and <kbd>C-k</kbd> rather than <kbd>C-n</kbd> and <kbd>C-p</kbd>.  See <http://develop.spacemacs.org/layers/+completion/auto-completion/README.html#company>.

It looks like there is an issue with <kbd>C-d</kbd> though.

**Comment by manveru** [comment]
Yeah, just confirmed that switching to hybrid style in a vanilla config makes everything work again. I guess there's still a bug with vim style, but it doesn't affect me anymore.
