### ISSUE TITLE
Flycheck disabled by default

### ISSUE THREAD

**Issue by jorgemorais** [syl20bnr/spacemacs#11073]
#### Description :octocat:

`syntax-checking` layer is enabled; `syntax-checking-enable-by-default` is t; but
Flycheck starts disabled

#### Reproduction guide :beetle:

- Enable layer `syntax-checking` in `dotspacemacs-configuration-layers`
- Restart Emacs
- Open a Bash script
- SPC e v

*Observed behaviour:* :eyes: :broken_heart:

Flycheck is disabled.  I have reported this with my full Spacemacs config, but I have also reproduced it with an almost-vanilla config.

*Expected behaviour:* :heart: :smile:

Flycheck should be enabled by default, according to the layer's `README.org`.

Workaround: set `flycheck-global-modes` to t.  Unfortunately this needs to be
done in every Emacs session; just setting it in `.spacemacs` is not enough,
because layer code overrides it – which is probably a bug in itself.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d9eecb760)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((chrome :packages
         (not gmail-message-mode))
 csv erc helm
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-private-snippets-directory
                  (concat spacemacs-private-directory "shared_snippets")
                  auto-completion-enable-sort-by-usage t)
 (elfeed :variables rmh-elfeed-org-files
         `(,(concat spacemacs-private-directory "elfeed.org")))
 emacs-lisp git gnus json markdown neotree
 (notmuch :variables notmuch-message-deleted-tags
          '("+deleted"))
 org
 (shell :variables shell-default-shell 'shell)
 php shell-scripts spell-checking syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS

**Comment by Miciah** [comment]
I could not reproduce the issue.

What is the value of `flycheck-global-modes`? For me, it is `(json-mode php-mode sh-mode)`.  Each enabled layer that uses Flycheck should add itself to this list.

What did `SPC e v` show? For me, it shows the following:

    Syntax checkers for buffer foo.sh in sh-mode:
    
      bashate (disabled)
        - may enable: Automatically disabled!
        - executable: Not found
    
      rpm-rpmlint
        - may enable: yes
        - predicate:  nil
        - executable: Found at /bin/rpmlint
    
      sh-bash
        - may enable: yes
        - predicate:  nil
        - executable: Found at /bin/bash
    
      sh-posix-dash (disabled)
        - may enable: Automatically disabled!
        - predicate:  t
        - executable: Not found
    
      sh-posix-bash
        - may enable: yes
        - predicate:  t
        - executable: Found at /bin/bash
    
      sh-zsh
        - may enable: yes
        - predicate:  nil
        - executable: Found at /bin/zsh
    
      sh-shellcheck (disabled)
        - may enable:         Automatically disabled!
        - predicate:          t
        - executable:         Not found
        - Shell sh supported: yes
    
    Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.
    
    --------------------
    
    Flycheck version: 32snapshot (package: 20180720.247)
    Emacs version:    27.0.50
    System:           x86_64-pc-linux-gnu
    Window system:    x

**Comment by jorgemorais** [comment]
First, I am sorry for having taken this long to reply.

Today I updated Spacemacs and reproduced the issue in a config where the only modifications were choosing hybrid edit style and enabling the `syntax-checking` layer; as such, the only enabled layers were `helm`, `emacs-lisp`, `neotree` and `syntax-checking`.  Apparently we only get syntax-checking by default on shell script buffers if we, besides enabling the `syntax-checking` layer, also enable the `shell-scripts` layer.  This behavior creates the need to install a few extra packages to enable functionality that does not depend on them.  Should not `flycheck-global-modes` be left alone with its default t value, at least when `syntax-checking-enable-by-default` is non-nil?  If that's not possible, then please clarify the layer's `README.org`, because it currently says:

> By default, syntax-checking is enabled in all available major modes (except for
> emacs-lisp-mode) and may be toggled off with SPC t s.

Now I realized my original post involved a mistake of mine.  Explanation: I wanted to get on-by-default syntax-checking everywhere it is supported.  Therefore I set `flycheck-global-modes` to its default value (t) on my `dotspacemacs/user-config`.  However, if GNU Emacs changes the option default value (presumably to something better), I want to get the new default.  Therefore I did this in `dotspacemacs/user-config`:

```emacs-lisp
(dolist
    (var
     '(
       flycheck-global-modes
       make-backup-files
       org-log-done
       sentence-end-double-space
       org-agenda-restore-windows-after-quit))
  (set var (eval (cl-first (get var 'standard-value)))))
```

Out of the five options in the var list, only `flycheck-global-modes` does not get set to its standard value.  I assumed it was a bug in `syntax-checking` layer.  But now I realized that it works when I set `flycheck-global-modes` to t with plain old `(setq flycheck-global-modes t)`.  I now realize that my code excerpt above is wrong, because it executes before Emacs loads some of the five options and therefore Emacs does not know the corresponding standard values, in which case they probably get set to nil.  Despite this mistake of mine (which worsened the problem), I still believe the layer's behavior is not optimal; see my argument in the second paragraph above.

Regards

**Comment by smile13241324** [comment]
Yeah that depends on the respective mode, normally the modes do not setup flycheck but it is done by the language layers `Post-init` or `Pre-init` functions.

As to changing the default for `flycheck-global-modes` I am not sure about this, the documentation gives me the impression that this was done by intention, same for the deactivation of flycheck for `elisp` by default.

@syl20bnr can you give your opinion about the requested changes from jorgemorais? I am sure that there was a reason why this was done that way.
