### ISSUE TITLE
Unable auto-completion golang

### ISSUE THREAD

**Issue by floatval** [syl20bnr/spacemacs#11077]
#### Description :octocat:
When i config go lang and auto-compltion and python layers, then i try to
write go and python file. The completion work well with python but not work with golang.
#### Reproduction guide :beetle:
- Start Emacs
- C-x C-f some_go_file.go
- C-x C-f some_python.py
*Observed behaviour:* :eyes: :broken_heart:
e.g. when i write a python file,
```
import time
time.
```
after . there auto-complete some func and method
but when i write a go file
e.g.
```
package main
import "fmt"
func main () {
     fmt.
}
```
nothing happend.

*Expected behaviour:* :heart: :smile:
I use arch and emacs26.1, i also add ```GOPATH``` to my .zshenv
here is my .zshenv
```
# golang
export GOPATH="$HOME/development/go/"
export PATH="$PATH:$HOME/development/go/bin"
export GOROOT="/usr/lib/go"
export GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
```
and here is my .zshrc

```
export GOPATH="$HOME/development/go/"
export PATH="$PATH:$HOME/development/go/bin"
export GOROOT="/usr/lib/go"
export GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
```

here is my .spacemacs:
```
dotspacemacs-configuration-layers
   '(
     go
     python
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     helm
     auto-completion
     better-defaults
     emacs-lisp
     git
     markdown
     ;; org
......
  (add-hook 'after-init-hook 'global-company-mode)
  (add-hook 'go-mode-hook
          (lambda ()
            (set (make-local-variable 'auto-completion-backends) '(auto-completion-go))
            (auto-completon-mode)))
......
;; auto completion layer config
(setq-default dotspacemacs-configuration-layers '(
  (auto-completion :variables
                   auto-completion-return-key-behavior 'complete
                   auto-completion-tab-key-behavior 'cycle
                   auto-completion-complete-with-key-sequence '"jk"
                   auto-completion-complete-with-key-sequence-delay 0.1
                   auto-completion-private-snippets-directory nil)
                   ))
(defun dotspacemacs/user-config ()
......
```
i also try remove 
```
  (add-hook 'after-init-hook 'global-company-mode)
  (add-hook 'go-mode-hook
          (lambda ()
            (set (make-local-variable 'auto-completion-backends) '(auto-completion-go))
            (auto-completon-mode)))
```
but it doesn't work
Thanks for your replay

**Comment by birdayz** [comment]
You have to manually download the 'usual' go tools, like gocode, godoctor, go-guru. Their executables have to be in your $PATH.

**Comment by floatval** [comment]
@birdayz  Thanks, for your replay.
Yeah, i confirm that I have done it.
here is ```echo "$PATH" | grep go``` output
```
/home/ft-arch/development/go/bin:/home/ft-arch/myscript:/home/ft-arch/development/go/bin:/home/ft-arch/development/go/bin:/home/ft-arch/myscript:/home/ft-arch/development/go/bin:/home/ft-arch/development/go/bin:/home/ft-arch/myscript:/home/ft-arch/development/go/bin
```
and here is ``` go env ``` output
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ft-arch/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ft-arch/development/go/"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build726697752=/tmp/go-build -gno-record-gcc-switches"
```
here is [go layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go)
and i also do 
```
go get -u -v github.com/nsf/gocode
go get -u -v github.com/rogpeppe/godef
go get -u -v golang.org/x/tools/cmd/guru
go get -u -v golang.org/x/tools/cmd/gorename
go get -u -v golang.org/x/tools/cmd/goimports
```
they work well ,e.g. when i use ```,xx/SPC m xx```
here is ```gocode status``` output
```
Package cache contains 1 entries

Listing these entries:
	name: unsafe (default alias: unsafe)
	imports 4 declarations and 0 packages
	this package stays in cache forever (built-in package)
```

**Comment by floatval** [comment]
Ummm, i resolve it.
If you met the same problem, you might to reinstall gotools, some like gocode, gode...

**Comment by Alexander-Miller** [comment]
>  (auto-completon-mode)

Typo?

Besides, doesn't spacemacs only use company?

**Comment by floatval** [comment]
@Alexander-Miller  I would like to use other, but with defaullt go layers, it only use company.
You can find the layer packages.el in ```~/.emacs.d/layers/+lang/go```
here is packages.el
```
(setq go-packages
      '(
        company
        (company-go :toggle (configuration-layer/package-usedp 'company))
        flycheck
        (flycheck-gometalinter :toggle (and go-use-gometalinter
                                            (configuration-layer/package-usedp
                                             'flycheck)))
        ggtags
        helm-gtags
        go-eldoc
        go-mode
        go-guru
        (go-rename :location local)
        ))
```
But if you want to use another completation, you can put your config in ```~/.emacs.d/private``` and start it in your ```.spacemacs```

**Comment by robbyoconnor** [comment]
Also -- the current issue is that if you are using go 1.11 -- all tooling is kind of temporarily broken for now

**Comment by robbyoconnor** [comment]
Also -- use `develop` -- We have a [go layer](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/go).

**Comment by dennismayr** [comment]
Curiously, I'm having the same problem using the `go` layer as-is; `lsp` fires up effortlessly, but there's no autocompletion at all. My only `go` layer options are `go-backend 'lsp` and `go-format-before-save t`.
All `go` tools installed according to the `go`layer documentation for the `develop` branch, as of today.

Typing anything at 3 characters and pressing `tab` for autocompletion suggestions yields a `[No matches]` message at the bottom.

Currently using:
_Emacs 26.3_
`go-1.13.4`
$GOPATH is reachable at `~/go`
