### ISSUE TITLE
ranger-control violates reserved prefix command for user

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#1107]
From https://github.com/syl20bnr/spacemacs/blob/develop/contrib/ranger-control/config.el : 
```
(evil-leader/set-key
   "oc" 'ranger-control/projectile-cd)
```

From https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#reserved-prefix-command-for-user : 

> SPC o is reserved for the user. Setting key bindings behind <SPC> o is *guaranteed* to never conflict with Spacemacs defaults key bindings.

**Comment by syl20bnr** [comment]
@trishume what do you think about the ranger-control ? Does is practical for other users ? It can be moved to the `osx` layer if this OS is a prerequisite.

**Comment by trishume** [comment]
Frankly it should be a private layer for me, it was just created before there was such a thing as a private layer and the "contrib" section was supposed to be a place for users to share their own random snippets.

**Comment by syl20bnr** [comment]
@trishume That's OK, you can transfert it to a private layer then.
