### ISSUE TITLE
Autocomplete hangs the editor when writing a path to a directory containing hundreds of thousands of files

### ISSUE THREAD

**Issue by CMCDragonkai** [syl20bnr/spacemacs#11081]
I have a directory that contains nested directories with hundreds of thousands of files (images).

Whenever I wrote a path that points to that directory, even when I'm not going into the directory that contains the files, the entire editor hangs.

It appears that the autocomplete tries to look ahead beyond the directory path that I'm writing.

I have 2 suggestions/questions:

1. Is there a way to limit the autocomplete to only search on the specific directory that I'm in, so it's not searching into deeper nested directories.
2. Is there a way to make the autocomplete on directories with hundreds of thousands of files not hang the editor. Either make it run in a separate thread/process or make it something that is interruptible.

**Comment by Miciah** [comment]
To work around the issue, you can disable the completion backend that completes file paths:
```emacs-lisp
(delete 'company-files spacemacs-default-company-backends)
```
Does that prevent the hanging?

Beyond that, solving the issue will probably require upstream changes to [company-mode](https://github.com/company-mode/company-mode).

**Comment by smile13241324** [comment]
@CMCDragonkai did you had time to check Miciah's workaround? Did this solve your issue? If not it may be worth a while to report upstream at `company-mode`.
