### ISSUE TITLE
PDF changes its size automatically after I switch to another workspace and switch back.

### ISSUE THREAD

**Issue by yanghaoxie** [syl20bnr/spacemacs#11085]
#### Description :octocat:
PDF changes its size automatically after I switch to another workspace and switch back.

#### Reproduction guide :beetle:
- Start Emacs
- Open a TeX file
- Press ', a'
- PDF show in current buffer, but with error message in mini buffer: 'error in process sentinel: invalid image speficication nil'
- Switch workspace using eyebrowse
- Switch workspace back
- The PDF is zoomed in.

*Observed behaviour:* :eyes: :broken_heart:
- Error message in mini buffer
- PDF size is changed

*Expected behaviour:* :heart: :smile:
- No error message in mini buffer
- PDF stay the way it was

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 45ee95c28)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown helm auto-completion better-defaults emacs-lisp git org spell-checking syntax-checking pdf neotree ranger evil-snipe colors python latex chinese shell xclipboard my-config)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (error "Invalid image specification: nil")
  signal(error ("Invalid image specification: nil"))
  error("Invalid image specification: %s" nil)
* image-display-size(nil t)
  pdf-view-image-size(t)
  pdf-util-required-vscroll((8 1133 8 1169))
  pdf-util-tooltip-arrow(1133)
  pdf-sync-forward-search()
  TeX-pdf-tools-sync-view()
  TeX-run-function("View" "TeX-pdf-tools-sync-view" "NFV-in-full-dynamic-situation")
  TeX-run-discard-or-function("View" "TeX-pdf-tools-sync-view" "NFV-in-full-dynamic-situation")
  TeX-command("View" TeX-master-file 0)
  TeX-command-sequence(t nil TeX-master-file)
  TeX-command-sequence-sentinel(#<process LaTeX> "finished\n")

```

**Comment by ofenerci** [comment]
I am getting the same error. I wonder there is any solution?
