### ISSUE TITLE
Package Unavailable: ac-ispell

### ISSUE THREAD

**Issue by rieonke** [syl20bnr/spacemacs#11095]
hello,
`ac-ispell` is unavailable now https://stable.melpa.org/#/ac-ispell

**Comment by Miciah** [comment]
I don't really know the process for reporting a missing package, but I filed an issue upstream: https://github.com/melpa/melpa/issues/5657

**Comment by rieonke** [comment]
@Miciah just download the package from github and use `package-install-file` to install to

**Comment by semsturgut** [comment]
@rieonke that works. Thanks.

**Comment by syl20bnr** [comment]
closed as duplicate of https://github.com/syl20bnr/spacemacs/issues/11096
