### ISSUE TITLE
Toggle auto indent in sql-mode

### ISSUE THREAD

**Issue by darkbaby123** [syl20bnr/spacemacs#11108]
#### Description :octocat: 

The `sql-mode` uses `sql-indent` package for indentation. But most time the indentation result is not what I want and it is hard to [customize the rules](https://github.com/alex-hhh/emacs-sql-indent/blob/master/sql-indent.org). So I want to add a toggle to disable `sql-indent` package.

After some investigation I found that I can add some toggle like `sql-use-indent` in the `packages.el` like this:

```lisp
  (use-package sql-indent
    :if sql-use-indent
    :defer t
    :init (add-hook 'sql-mode-hook 'sqlind-minor-mode)
    :config (spacemacs|hide-lighter sqlind-minor-mode)))
```

and use the layer in my `.spacemacs` like this:

```lisp
(sql :variables sql-use-indent nil)
```

The only problem is, if I don't set the variable, the layer raises an error. So I think I need to define a default value for that variable in the layer. My lisp skill is very pool. Anyone can guide me how to do this? And if it's OK I want to send a PR for this functionality.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 026ba1469)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree
      (auto-completion :variables auto-completion-enable-snippets-in-popup t)
      git markdown
      (org :variables org-want-todo-bindings t)
      (osx :variables osx-use-dictionary-app nil)
      version-control elixir ruby yaml
      (sql :variables sql-use-indent t sql-capitalize-keywords nil sql-capitalize-keywords-blacklist
           '("id " "name" "type"))
      (javascript :variables js2-basic-offset 2 js-indent-level 2)
      csv)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by Miciah** [comment]
What is the error?

It sounds like you need to add something like `(defvar sql-use-indent t "Indent SQL statements.")` to `layers/+lang/sql/config.el` to make sure the variable is defined.

**Comment by darkbaby123** [comment]
@Miciah The error happens when Spacemacs starts, see below:

```
Warning (initialization): An error occurred while loading ‘/Users/david/.emacs.d/init.el’:

Symbol's value as variable is void: sql-use-indent

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace
```

I tried your solution and it works. Defining a variable with a default value in the layer is just what I need. Thank you!
