### ISSUE TITLE
Harmonize keybindings in contrib layers like markdown and org

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#1110]
I think we should try to harmonize the keybindings in some contribution layers.

It would be nice if I could e.g. insert a link or make text bold using the same keybindings in markdown and org.

I would be happy to start but would probably change some of the keybindings in markdown since the current ones do not seem very logical in some places.

**Comment by syl20bnr** [comment]
Good idea, we can discuss it in a PR.

**Comment by moesasji** [comment]
If you consider harmonizing it would be good to carefully look at the keybindings in `evil-org-mode` and not use them as the basis for org-mode in spacemacs as to me they appear ill thought out. 

The reason that I think this is:
 (i) The keybindings in org-mode have little relation to the keybindings from the org manual and are hard to recognize and/or remember.
(ii) Some of the keybindings in `evil-org-mode` override core and often used vim editing modes such as `O` (insert above) making it rather unworkable for someone who uses vim routinely.
(iii) There seems to be little activity on github for `evil-org-mode`. Is it still alive seeing that the issue in point 2 was raised a long time ago?

I don't know which keybindings would be better as I've only played with org-mode and not used it extensively. However with the current keybindings it is more natural to use the emacs ones (with the caveat that `C-u` suddenly becomes `SPC-u` in spacemacs) and that seems very strange for a keybinding that should be easier to remember.

**Comment by cpaulik** [comment]
@moesasji Thanks for the inspiration on the org mode keybindings. I will play around with them a little more and then we can suggest them to spacemacs in a separate PR. For now I wanted to focus on a consistent experience across markup languages whenever possible.

**Comment by CestDiego** [comment]
Hello guys, I saw this package that has sane org keybindings https://github.com/abo-abo/worf what do you think about it?
