### ISSUE TITLE
tab does both completion and indent causes issue in python shell

### ISSUE THREAD

**Issue by shelper** [syl20bnr/spacemacs#11100]
#### Description :octocat:
tab does both completion and indent causes issue in python shell

#### Reproduction guide :beetle:
- Start Emacs
- start python shell by run-python

*Observed behaviour:* :eyes: :broken_heart:
press tab and return
then i have line:
0__dummy_completion__  1__dummy_completion__

*Expected behaviour:* :heart: :smile:
press tab should just indent, but i think the system thought you try to auto complete and thus give the error

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1c2d498)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm emacs-lisp neotree)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
```

**Comment by smile13241324** [comment]
@shelper can you give some more details on how to reproduce without python layer?

**Comment by shelper** [comment]
just start python shell and put python code there...

**Comment by Miciah** [comment]
I can reproduce the issue without Spacemacs.

1. Run `emacs -Q`.
2. <kbd>C-x C-f</kbd> `foo.py` <kbd>RET</kbd>.
3. <kbd>M-x</kbd> `run-python` <kbd>RET</kbd>
4. <kbd>M-:</kbd> `(setq indent-tabs-mode t)` <kbd>RET</kbd> (Spacemacs's python layer sets this setting.)
5. <kbd>TAB</kbd> <kbd>RET</kbd>

After Step 5, I see 184 lines of identifiers, including the line in the original report.

This looks like an issue that should be reported upstream.

**Comment by smile13241324** [comment]
I have reported the bug to the github repository however as far as I see the bug should rather be reported to emacs bug tracker itself as python.el is now part of emacs itself. However I think we need some more information about this before an emacs bug has any chance of being worked on.

Especially does this also happen when `indent-tabs-mode` is not true? @JAremko do you have experience with reporting bugs to gnu repos? Do you think we should also report the bug there? I am not sure whether it would be necessary to report the problem in some special form on their bug trackers. Can you advise?

@Miciah can you tell how do you format your keys in markdown to look like single keystrokes?

**Comment by JAremko** [comment]
@smile13241324  You can mail it to bug-gnu-emacs@gnu.org

**Comment by Miciah** [comment]
@smile13241324, I found `(setq indent-tabs-mode t)` to be necessary to reproduce the problem.

In addition to the address JAremko mentioned, Emacs also has a built-in command for reporting bugs; use <kbd>M-x</kbd> `report-emacs-bug`.

I am using `<kbd>` and `</kbd>` to format keys.  I don't know how widely supported `<kbd>` is outside of GitHub.
