### ISSUE TITLE
Finance: Emacs hangs when using TAB key on first line of a .ledger file

### ISSUE THREAD

**Issue by ChchPtatoFvr** [syl20bnr/spacemacs#11105]
#### Description :octocat:
With the finance Layer:
Emacs hangs when using the tab key on the first line of a ledger file.

#### Reproduction guide :beetle:
Requirement: Finance Layer
- Start Emacs
- open an empty or nonempty .ledger file
- press TAB

*Observed behaviour:* :eyes: :broken_heart:
Emacs hangs and becomes completely unresponsive.

*Expected behaviour:* :heart: :smile:
Call the ledger-mode function: ledger-magic-tab
Should indent, complete, or align depending on the context.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 4a75b16)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript html finance helm
            (auto-completion :variables auto-completion-return-key-behavior 'nil auto-completion-tab-key-behavior 'complete)
            better-defaults emacs-lisp git
            (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
            python pdf-tools imenu-list themes-megapack docker markdown
            (org :variables org-enable-reveal-js-support t)
            (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term shell-default-term-shell "/bin/bash"))
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS NOTIFY GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS

**Comment by Alexander-Miller** [comment]
Run `kill -12 emacs` to force emacs to show you what it's hung up on.

**Comment by Alexander-Miller** [comment]
Stacktrace doesn't look suspicious to me. I cannot reproduce it either. Let's try something obvious then: try updating ledger mode and turn off linum (on Emacs26 you should be using the much faster display-line-numbers-mode anyway).

**Comment by Alexander-Miller** [comment]
> The finance layer is updated automatically right?

The layers do not *update* their packages, they only install what they need. Depending on how long ago you installed ledger you may have missed some updates or bug fixes.

> Is toggling linum-mode off sufficient?

Yes.
