### ISSUE TITLE
Windows are resizing on focus/unfocus, and minibuffer is resizing whenever Helm is active

### ISSUE THREAD

**Issue by jgrosso** [syl20bnr/spacemacs#11114]
#### Description :octocat:
A couple hours after starting Spacemacs, I consistently notice the following behavior:

- When I create a new window (e.g. via `<spc> w -`), I notice that the size of each window changes dramatically whenever I focus it. Specifically, focusing a window causes it to take up about 1/3 of the available space (whereas the unfocused window will then expand to take up 2/3 of the available space).
- When I access Helm (e.g. via `<spc> <spc>`), the minibuffer suddenly expands to the size of the helm window sitting right above it.

#### Reproduction guide :beetle:
- Start Emacs
- Wait several hours and create/focus windows in the meantime. Maybe creating new frames in the process causes the issue?

*Observed behaviour:* :eyes: :broken_heart:
Windows shrink and expand on focus/unfocus, and opening Helm causes the minibuffer to significantly enlarge.

*Expected behaviour:* :heart: :smile:
Windows should stay the same size regardless of whether they are focused or unfocused, and the minibuffer shouldn't grow whenever Helm is activated.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1ae546305)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(react auto-completion c-c++ clojure coq csharp csv dash emacs-lisp games git go javascript
       (haskell :variables haskell-completion-backend 'intero)
       helm html latex markdown mu4e
       (org :variables org-enable-github-support t)
       osx pdf php purescript ruby-on-rails rust
       (shell :variables shell-default-shell 'eshell)
       spotify syntax-checking themes-megapack theming treemacs
       (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
       vimscript yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Alexander-Miller** [comment]
Point 1 sounds like a reverse golden-ratio mode. Try enabling/disabling it.

**Comment by jgrosso** [comment]
@Alexander-Miller Now that you mention it, I do remember playing around with that a while ago.... However, enabling or disabling `golden-ratio` mode just flips whether it's the active or inactive window which is larger. Is there a way to disable this auto-resizing behavior entirely?

**Comment by Alexander-Miller** [comment]
The most direct cause is probably something in `window-configuration-change-hook` or advice on `window-select`, but the real question is why that behaviour was put there in the first place.

I think you'll need to dig through your config, preferably starting from vanilla spacemacs, to find the culprit.

**Comment by jgrosso** [comment]
Just found the issue: I had added window resizing code as a `compilation-mode` hook, but there was no buffer with that mode when the hook actually ran, so the `nil` buffer was getting resized forever and bad things happened.

**Comment by duianto** [comment]
Thanks for posting an update when you found the cause. 👍
