### ISSUE TITLE
macOS: Packages cannot be updated.

### ISSUE THREAD

**Issue by kenokenobingo** [syl20bnr/spacemacs#11121]
#### Description :octocat:
Updating packages is not working on macOS. I am using a relatively clean install of Spacemacs. On Linux, it is working perfectly fine, though.

#### Reproduction guide :beetle:
- Start Emacs on macOS
- Click on `Update Packages`

*Observed behaviour:* :eyes: :broken_heart:
- Packages are not updating
- Output: `Source: nil`
- New packages from `melpa` cannot be installed.

*Expected behaviour:* :heart: :smile:
Packages are be updated from both `elpa` and `melpa`.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html python yaml markdown javascript helm auto-completion emacs-lisp git markdown org syntax-checking version-control yaml)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by NeilMenne** [comment]
`*Messages*` output looks like:

```
(Spacemacs) --> refreshing package archive: gnu... [1/1]
Contacting host: elpa.gnu.org:443 [2 times]
Package refresh done
Fetcher: file
Source: nil
```
