### ISSUE TITLE
Go Language Server Support?

### ISSUE THREAD

**Issue by Jackson-soft** [syl20bnr/spacemacs#11137]
https://github.com/sourcegraph/go-langserver

**Comment by ljupchokotev** [comment]
I have a PR for lsp support here #10855, you can try it locally.

**Comment by smile13241324** [comment]
@Jackson-soft #10855 has been merged just now. Would you mind giving it a try and posting a short feedback how good it works?

**Comment by Jackson-soft** [comment]
OK, No problem.Already used it.

**Comment by winmillwill** [comment]
I'm not sure why, but with lsp-go enabled, whenever I load a go buffer, the flycheck checker is lsp, which doesn't seem to check anything.

**Comment by sdwolfz** [comment]
I'll go ahead and close this issue as the original request was addressed.
