### ISSUE TITLE
develop: goimports/gofmt are broken

### ISSUE THREAD

**Issue by vbauerster** [syl20bnr/spacemacs#11133]
#### Description :octocat:
goimports broken

#### Reproduction guide :beetle:
- Start Emacs
- Open any go file, do some edit.

*Observed behaviour:* :eyes: :broken_heart:
Upon save no goimport or gofmt applied, despite the fact my config says so.

*Expected behaviour:* :heart: :smile:
goimport and gofmt should be applied.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9af8e1564)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org
      (git :variables git-magit-status-fullscreen t)
      (version-control :variables version-control-diff-side 'left)
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip 'manual)
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      (spell-checking :variables enable-flyspell-auto-completion t spell-checking-enable-by-default nil)
      html markdown neotree yaml python java javascript
      (rust :variables rust-format-on-save t)
      (go :variables go-tab-width 4 gofmt-command "goimports" go-use-gometalinter t godoc-at-point-function 'godoc-gogetdoc)
      protobuf docker themes-megapack dash semantic
      (ranger :variables ranger-show-preview t ranger-show-literal t)
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
      shell-scripts
      (c-c++ :variables c-c++-enable-clang-support t c-c++-enable-rtags-support t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by douglarek** [comment]
yeah, same issue.

**Comment by vbauerster** [comment]
@douglarek Thanks for info!
