### ISSUE TITLE
[haskell-layer] How to use executables from ~/.stack/compiler-tools/ rather than ~/.local/bin?

### ISSUE THREAD

**Issue by lippirk** [syl20bnr/spacemacs#11132]
On the recommendation of this blog post: https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/ I don't want to do `stack install x` - I would like to have, for example, different `hindent` versions built for each ghc version.

I have built everything required by the haskell layer using `stack build --copy-compiler-tool apply-refact hlint stylish-haskell hasktags hoogle hindent` - I understand this is not what the README says! (After doing this my executables end up in `~/.stack/compiler-tools/x86_64-linux-tinfo6/ghc-8.4.3/bin`.)

Unfortunately, spacemacs then cannot find these executables. Is there a way to get spacemacs to figure out which lts/ghc version it is running, and then search in the correct sub folder under `~/.stack/compiler-tools/` for the right binaries?

I also noticed that in this blog, the following is mentioned:

'stack exec arranges for the executables for the current compiler version to end up in the PATH, so you only need to build and install your tools once per compiler version.'

so it is possible as an alternative, for example, to get spacemacs to run `stack exec hindent`, rather than `hindent`?

Many thanks!

**Comment by lippirk** [comment]
I have been using `(add-to-list 'exec-path "~/.stack/compiler-tools/x86_64-linux/ghc-8.4.3/bin")` and this is working fine for now. Would be nice if there was an option to use `stack exec` rather than the global binaries though

**Comment by dmp1ce** [comment]
I also have this issue. I think purcell/flymake-hlint only looks for `hlint`. I'll probably just install system wide for now.

**Comment by purcell** [comment]
When working in Stack projects it can be useful to add Stack's bin path to each buffer in the project. I have a hack to do just that [here](https://github.com/purcell/emacs.d/blob/de5551212dff3530dcccef4085ff0d2349844c0f/lisp/init-haskell.el#L59-L77).

**Comment by purcell** [comment]
Maybe I'll package that up and distribute it...

**Comment by dmp1ce** [comment]
I dropped that code into `dotspacemacs/user-config` of `.spacemacs` and it worked! Probably finding executable from the `stack exec` is the way to go for many projects.
