### ISSUE TITLE
Key mapping

### ISSUE THREAD

**Issue by fasddag** [syl20bnr/spacemacs#1113]
I want to map certain keys:
open org-link in the same window;
helm-find-files in a specific directory;
next and previous sentence, "(" and ")" by default.

I tried adding this to my dotspacemacs:
(require 'evil-states)
(require 'evil-commands)
(define-key evil-motion-state-map "S" 'evil-backward-sentence-begin)
(define-key evil-motion-state-map "s" 'evil-forward-sentence-begin)
(define-key evil-normal-state-map "(" 'evil-substitute)
(define-key evil-normal-state-map ")" 'evil-change-whole-line)

The s bindings did not work, the brackets worked. So I went to emacs.d/elpa/evil-blahblah/evil-maps and changed the bindings there. Now "s" and "S" work, but only as raw commands, but not as a part of say "ds" or "cS". The "d)" still works just fine.

How do I map these keys in a civilized way using my init file?

**Comment by person808** [comment]
I don't know if this will fix them, but here are some tips. Add the mappings to `dotspacemacs/config` in the init file.

>`(require 'evil-states)`

>`(require 'evil-commands)`

I don't think these are needed. Evil should be loaded at startup.

Wrap the key sequences with `kbd`. For example `"S"` becomes `(kbd "S")` in your `define-key` statement.

**Comment by fasddag** [comment]
I have tried doing it with (kbd "") it did not work.
When I remove the 'require' lines I get 
"Symbol's value as variable is void: evil-motion-state-map" 
error on start up and spacemacs fails to initialize.

**Comment by syl20bnr** [comment]
Arre you sure that you are in `dotspacemacs/config`  ?
I don't see why it does not work, your example are ok.

**Comment by fasddag** [comment]
Previously I was putting this in .spacemacs file (spc f e d). 
After your reply I tried ~\.emacs.d\spacemacs\config.el.
Just like you said I did not need the "requires", but I have the same problem: the "(", ")" bindings work like substitute, but the "s", "S" do not - they remain as substitute, too.

**Comment by smelnikov** [comment]
I'm having the same problem, seems like the key bindings do work, but they are appended to the previous binding instead of replaced. Is there to unbind the previous evil bindings before setting a new one?

**Comment by smelnikov** [comment]
Ok, I figured it out. I was defining the 's' key on the 'evil-motion-state-map' and it was still being defined as substitute within 'evil-normal-state-map'. So I had to do : `(define-key evil-normal-state-map "s" nil)`
