### ISSUE TITLE
Can we add `visual` to `dotspacemacs-line-numbers`?

### ISSUE THREAD

**Issue by yanghaoxie** [syl20bnr/spacemacs#11141]
Since emacs 26 has `display-line-numbers-mode`, which support `visual` option. Can we add this option to `dotspacemacs-line-numbers`. This option play well with folding code, and a detail use case can be found here #6536.

**Comment by NQNStudios** [comment]
I think I ran into the same issue with Spacemacs and Emacs 25: https://emacs.stackexchange.com/questions/34679/making-relative-line-numbers-behave-well-with-folds

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
Add support for visual line numbers #12450
