### ISSUE TITLE
Remove sayid from clojure layer [development]

### ISSUE THREAD

**Issue by Lokeh** [syl20bnr/spacemacs#11146]
With recent changes to CIDER and nREPL, sayid no longer works. The 0.300 development branch currently installs it and injects it on `cider-jack-in` by default, causing a number of issues for unsuspecting users of the Clojure layer.

I have raised an issue on the github project, however the last commit to sayid was over a year ago: https://github.com/bpiel/sayid.

It's safe to say that it's at risk for being abandoned and, IMO, should be removed from the defaults that the Clojure layer comes with.

**Comment by bbatsov** [comment]
Yeah, I've wasted a ton of time explaining to people how to address this problem, so I'd really appreciate this change. 

For the record - here's a PR that's going to fix sayid https://github.com/bpiel/sayid/pull/40

We might suggest to @bpiel to move his project to the `clojure-emacs` or the `nrepl` org down the road, so it can get some maintenance, but for the time being we should certainly disable it.

**Comment by Miciah** [comment]
> With recent changes to CIDER and nREPL, sayid no longer works.

Is it this issue? https://github.com/bpiel/sayid/issues/39

> I have raised an issue on the github project

Can you link to it?

> the last commit to sayid was over a year ago

I'm confused.  The last commit to the repository to which you linked was in April of this year.

**Comment by bbatsov** [comment]
> Is it this issue? bpiel/sayid#39

Yes. As I mentioned there's already a PR for this.

> I'm confused. The last commit to the repository to which you linked was in April of this year.

Look more closely. The last commit is just a release for a single PR that's over 1 year old. :-)

**Comment by bbatsov** [comment]
![image](https://user-images.githubusercontent.com/103882/43863315-024eb7d0-9b65-11e8-987c-5d32bd86c60a.png)

**Comment by Lokeh** [comment]
@Miciah sorry, @bbatsov raised the issue on that repo - my mistake (got confused with clj-refactor which had a similar issue and has been resolved). Like @bbatsov said, a release was cut earlier this year but no new development has occurred and this is blocking anyone using the `clojure` layer on the development branch and hasn't pinned their version of nREPL.

**Comment by Miciah** [comment]
It seems a little strong to say that the project is "at risk for being abandoned" when the owner made a release 4 months ago and has been commenting on issues and PRs since then.  I'll concede that I'm arguing semantics here though.  In practical terms, 11 months is a long turnaround, and if changes to other packages often break sayid, that long turnaround combined with the frequent breakage would be solid grounds not to install sayid with the clojure layer.

**Comment by bpiel** [comment]
hey everyone,  I've been in the middle of the woods with little connectivity and am just seeing this now.

While I don't think of Sayid as "abandoned" and don't expect to abandon it soon, I definitely have not been responsive about fixes or very active with improvements.

I was in no way involved in getting Sayid in the clojure layer. Honestly, I was surprised that it got in, because I'd guess that only a ridiculously tiny fraction of spacemacs users are using it.

With all of that in mind, I agree sayid should be removed from the layer.

Lastly, I'll just add that I intend to release the PR from @bbatsov once I'm back in civilization in a few days.

**Comment by kommen** [comment]
I also ran into an issue with spacemacs develop branch and up to date packages where after `cider-jack-in` emacs/spacemacs would just freeze and wouldn't accept any keyboard input at all. Adding `sayid` to the `dotspacemacs-excluded-packages` works around this issue for me.

**Comment by plexus** [comment]
The Clojure layer could use the same [pattern the org mode layer](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bemacs/org/packages.el#L31-L35) uses, so that sayid is opt-in.

``` emacs-lisp
(setq clojure-packages
      '(cider
        ...
        (sayid :toggle clojure-enable-sayid)
        ))
```

And in `.spacemacs`

``` emacs-lisp
   dotspacemacs-configuration-layers
   '( (clojure :variables clojure-enable-sayid t)
   )
```

**Comment by plexus** [comment]
@Lokeh @bpiel @bbatsov @Miciah does this seem like a good compromise?

https://github.com/syl20bnr/spacemacs/pull/11194

**Comment by bbatsov** [comment]
I'm fine with this approach. Generally I think that the default setup should aim to be robust instead of fancy, so it should enable just CIDER and the other packages should be opt-in. People who need them will know how to enable them. :-)

**Comment by Lokeh** [comment]
That sounds like a good plan.

Sorry for being very callous in my initial message - it was kind of a stressful couple days figuring out why my dev environment was broken, and then helping others fix the issue. As a casual Emacs user it was non trivial to discover that spacemacs was pulling in these various middleware who all depended on a specific version of nREPL, all of which can't be pinned.

I think that if we can't manage to keep the various packages that comprise a layer compatible (whether by pinning versions or ensuring that maintainers stay in lock step with each other) then they should, at the very least, not be enabled by default.

**Comment by plexus** [comment]
in the PR @bbatsov suggests doing the same for clj-refactor, disabling it by default but with opt-in. I'm happy to make another PR for that. Any objections?

**Comment by bbatsov** [comment]
@plexus Seems not. Probably the README for Clojure has to be tweaked a bit to mention the opt-ins. Not sure how many people read it, though. :-)

**Comment by reutsharabani** [comment]
Does this thread mean there is no option to debug Clojure (trace, place breakpoints, etc.) natively in Spacemacs?

I started using Spacemacs a week ago and there are shortcuts like `SPC m d b` that do not do anything (maybe I'm not setting something correctly).

Working without a debugger can be challenging to say the least. And if there isn't one the README should be updated: https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/clojure#debugging

**Comment by bbatsov** [comment]
CIDER has it's own debugger and tracing functionality, so you should be good even without sayid.

**Comment by reutsharabani** [comment]
I believe the stories, but I have no idea how to use it... Preferably in the vim-like fashion that spacemacs provides.

And the debugging key bindings from the README file for clojure doesn't work at all.

**Comment by bbatsov** [comment]
Take a look here http://www.cider.mx/en/latest/debugging/ and here http://www.cider.mx/en/latest/miscellaneous_features/#tracing-function-execution

**Comment by plexus** [comment]
@reutsharabani note that sayid is not actually removed, it's merely disabled by default. [This PR](https://github.com/syl20bnr/spacemacs/pull/11397) also updates the Clojure README to make that more clear, but that hasn't been merged yet.

If anything still seems off in the [README on that branch](https://github.com/syl20bnr/spacemacs/blob/0bbea1d8792be9bfe94e3be477ae6e8d478b7e4d/layers/%2Blang/clojure/README.org) (e.g. keys not working as advertised) then please [comment there](https://github.com/syl20bnr/spacemacs/pull/11397) and I will update it.
