### ISSUE TITLE
Hard to type a single quote in c-mode

### ISSUE THREAD

**Issue by hoosierEE** [syl20bnr/spacemacs#11142]
#### Description :octocat:
Single quote escaped; can't write character literals without extra work.

Typing a single quote in c-mode causes the text `\'\'` to appear, with the cursor after the first single quote.

#### Reproduction guide :beetle:
- Start Emacs
- open a .c file
- type a single quote

*Observed behaviour:* :eyes: :broken_heart:

`\'\'`

*Expected behaviour:* :heart: :smile:

`'`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml python html themes-megapack javascript better-defaults osx emacs-lisp latex git markdown org
      (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
      spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by hoosierEE** [comment]
I first mentioned this on #8791 but unsure if the root cause is the same.

**Comment by Miciah** [comment]
Upstream issue: https://github.com/Fuco1/smartparens/issues/783

In the upstream report, the following workaround is suggested:
```emacs-lisp
(setq-default sp-escape-quotes-after-insert nil)
```
Does the workaround work for you?

**Comment by hoosierEE** [comment]
The problem seems to have disappeared for me by now. I did not have to change anything in my .spacemacs file.

**Comment by MoHKale** [comment]
I'm encountering the same issue on the master branch. The above fix worked, did the fix never reach the master branch or has the problem crept back in?

**Comment by dmp450** [comment]
I'm also encountering this behaviour on master branch.

**Comment by duianto** [comment]
According to Miciahs comment:
https://github.com/Fuco1/smartparens/issues/783#issuecomment-417841576
The issue seems to be caused upstream in either smartparens or cc-mode.

If you could post a comment there, then that might bring the issue to the authors attention again.
