### ISSUE TITLE
Python-mode, Company not enabled when .venv in directory

### ISSUE THREAD

**Issue by saskenuba** [syl20bnr/spacemacs#11145]
Today I started using `pipenv` with the whole virtualenv inside the project directory using `PIPENV_VENV_IN_PROJECT=true`, because previously I had some issues with pipenv emacs extension not finding my project. All this started after I upgraded my python to 3.7.

Now, every time I go into a file on the project, the following message appears in my `*Messages*` buffer:
`File mode specification error: (file-error Read error Is a directory /home/martin/Documentos/Programming/Python/Projetos/simple-flask-blog/.venv)`

This doesn't occur when accessing a standalone `.py` file, where company-mode gets initiated with the appropriate backends.

Any guess on what is happening?

**Comment by rgb-24bit** [comment]
There is a compromise solution here. #10293
