### ISSUE TITLE
Web mode, keep completion

### ISSUE THREAD

**Issue by EvergreenHZ** [syl20bnr/spacemacs#11149]
I  am new to spacemacs, and when I write html in Web mode, it just keeps completing. When I type return, things are pasted. Something like below:

`1.<html>`
`2.        <head>`
`3.                <title> An Introduction to Programming in Emacs Lisp </title>`
`                                                                                                                 li    -> html`
`                                                                                                                em -> html ` 
`                                                                                                                 p    -> html`
`                                                                                                                ....`
I mean, when I am at the end of line 3, I just want to go to the next line by typing return, However, " li" is pasted, which really annoys me. (I am sorry if I do not describe things clearly.)

**Comment by delaanthonio** [comment]
This issue appears to be a duplicate of #8222. The issue is due to `company-minimum-prefix-length` being set to 0 in 3bbafcb.

**Comment by EvergreenHZ** [comment]
Thank you! Now it works.
