### ISSUE TITLE
*cider-repl-history* buffer (clojure layer) major mode key bindings shadowed

### ISSUE THREAD

**Issue by paulrd** [syl20bnr/spacemacs#11159]
#### Description :octocat:
Most of the keys for this major mode have been shadowed by evil mode.

#### Reproduction guide :beetle:
- Start Emacs
- Open clojure code buffer.
- Jack into a clojure repl (, ')
- in that repl buffer, go to *cider-repl-history* via C-c M-p
- hit q or Q to quit buffer

*Observed behaviour:* :eyes: :broken_heart:
Shadowed keys prevent the buffer from quitting

*Expected behaviour:* :heart: :smile:
Buffer should exit

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9af8e1564)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript rust markdown helm clojure finance prodigy html java sql auto-completion emacs-lisp git treemacs
            (org :variables org-enable-hugo-support t)
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
```

**Comment by kommen** [comment]
This issue is fixed in the `develop` branch.

**Comment by d12frosted** [comment]
@kommen thank you for reminder 😸
