### ISSUE TITLE
Feature Request: Dap-mode layer

### ISSUE THREAD

**Issue by Daniel-V1** [syl20bnr/spacemacs#11151]
Hello all,

I just wanted to raise awareness of this package and to put up a request for anyone out there who was great at making layers to look into making one for https://github.com/yyoncho/dap-mode. I would love to see it spacemacs-ified with excellent keybindings!

Thanks!

**Comment by smile13241324** [comment]
Have a look at #10820 @yyoncho proposed to integrate the package into java-layer. However Dap-mode could be used literally anywhere. Why not integrate it into lsp-layer as it is lsp related anyway. 

@sdwolfz what's your opinion about this? Basically one could attach arbitrary debug servers to spacemacs just like we do that today with LSP servers. Language layers could setup their respective supported debug servers.

**Comment by sdwolfz** [comment]
I love the idea of using dap-mode, but don't tie it up with LSP if it's not a dependency. Better to have a generic dap layer and integrations in each language.

**Comment by yyoncho** [comment]
I believe that it will be better to have a separate `dap` since there might be a languages which have `lsp` support but they do not have `dap` support.

**Comment by smile13241324** [comment]
You are right, lets move it into a separate layer, especially when there are "lsp only" languages out there.

**Comment by yyoncho** [comment]
@sdwolfz you may assign the issue to me, I will start working on it once `dap-mode` is onboarded to melpa -  https://github.com/melpa/melpa/pull/5660

**Comment by sdwolfz** [comment]
We have the following in the conventions file:
```org
The base prefix for debugging commands is ~SPC m d~.

| Key Binding | Description             |
|-------------+-------------------------|
| ~m d a~     | abandon current process |
| ~m d b~     | toggle a breakpoint     |
| ~m d B~     | clear all breakpoints   |
| ~m d c~     | continue                |
| ~m d d~     | start debug session     |
| ~m d i~     | step in                 |
| ~m d l~     | local variables         |
| ~m d o~     | step out                |
| ~m d r~     | run                     |
| ~m d s~     | next step               |
| ~m d v~     | inspect value at point  |

Notes:
  - Ideally a transient-state for breakpoint navigation should be provided.
  - If there is no toggle breakpoint function, then it should be implemented at
    the spacemacs level and ideally the function should be proposed as a patch
    upstream (major mode repository).
```

Now... the conventions can be changed if they are not realistic, I would rather have something that makes sense and is easy to use rather than following the rules.

My suggestion is to start with all of them under `SPC m d` and see how easy it is for you to use them that way in your normal debugging usage. If something is awkward, and it can not be fixed with having a transient state, then we can look into putting it somewhere else.

**Comment by yyoncho** [comment]
PR at for review at - https://github.com/syl20bnr/spacemacs/pull/11277

**Comment by yyoncho** [comment]
Here it is how PR #11277 looks in practice:

![dap-debug-session](https://user-images.githubusercontent.com/13259670/47254336-d9786200-d469-11e8-99cf-567850ba6630.gif)

**Comment by sdwolfz** [comment]
That screenshot looks amazing! so much magic happening there.

**Comment by smile13241324** [comment]
Woa this looks great, drop me a line if you are looking for someone to test this.

**Comment by sdwolfz** [comment]
@smile13241324 yes please help out if you have the time, the more people try it out the better.

**Comment by smile13241324** [comment]
Sorry for the long delay. Today I have took an hour and tested the current status of #11277 with a small gradle driven Java project.

**The positive**
First of all I want to say I am really impressed of how well `dap-layer` already works. After a bit of investigation of how to actually start the debug process and how to cleanly upgrade my `lsp server` I was able to successfully debug my small application.

It took me a bit more time to get familiar with the inspection function and to find the various `debug windows` but after this I would say the debugging environment is comparable to what I know from other more graphical IDEs like `netbeans` or `eclipse`.

**The negative**
Now comes the negative part, I find that the documentation for `dap layer` must be improved to explain the various `dap` specific concepts like the `dap-ui-repl` or the `inspection` function in more detail.

Also I am not sure that the `dap-hydra` plays well with `spacemacs-transient-states` I found myself mostly manually closing/opening the hydra buffer as it tends to interfere with evil bindings. I think a `transient state` would play considerably better with evil. Just for clarification, what I am missing is the default behaviour of `spacemacs-transient-states` to close automatically when a non bound key is pressed. I think this behaviour should at least be made possible by configuration parameters. 

**Summary**
I think `dap-layer` is already mature enough to considerably improve spacemacs debugger integration for most users. Therefore I would like to see it in `develop` as soon as possible.

The layer should then be improved in separate PRs.

**Comment by yyoncho** [comment]
@smile13241324 Thanks for the feedback!

I will try to improve the `dap-mode` documentation based on your comments. 

> Just for clarification, what I am missing is the default behaviour of spacemacs-transient-states to close automatically when a non bound key is pressed.

This behaviour was intentionally created and there are several transient state layers that do have the same behavour(all that have `:foreign-keys run`). The idea is that you can move to another point and perform another action. E. g.: `dap-hydra` - `bb` (place breakpoint) - `jjbb` - move two lines and place another breakpoint. I could add that option(it is one line) in `dap-hydra` if you insist but it is not clear to me what would be the usecase. You can quit the transient state by pressing `q`.

**Comment by smile13241324** [comment]
@yyoncho, well no I would not insist on this, basically I was just using hydra for stepping through the application rather than setting breakpoints. I was just running into some problems when I wanted to use the inspect functions and pressed `w` which was used by hydra rather then from my evil bindings.

Maybe it would be an alternative to avoid using `w` or `e` or any of `jkhl` in the hydra bindings?
Right now its effect is that some of the more general vim motions are lost when it is open, making it hard to use for `vim style` guys.

Anyway maybe its just a matter of getting used to, could be interesting how the key bindings work out when one has worked with it for a week or so.

**Comment by yyoncho** [comment]
> Maybe it would be an alternative to avoid using w or e or any of jkhl in the hydra bindings?

I am open for suggestions as I mentioned in the PR I run out of ideas. I guess the layer will evolve when it is added to Python/C++ and after it receives enough feedback.

**Comment by antonalekseev** [comment]
I think we need an option to disable `dap-mode` for specific layers or on per-project basis in the case, for example, using DAP-compatible debugger for Go and `realgud:trepan` for Python. Maybe it's already possible and I'm missing something, but as I can see here https://github.com/antonalekseev/spacemacs/blob/3e37a359b88e7aa6e2f2d238ea7441e60e98a44c/layers/%2Blang/python/funcs.el#L73 any other bindings are just unconditionally removed if the `dap` layer is in the list of enabled layers.

**Comment by yyoncho** [comment]
@antonalekseev  For that particular case, IMO it would be sufficient to move it to another keybinding to avoid the collision.

**Comment by vn-ki** [comment]
In python there is `python-test-pdb` keybings (`,tT`, `,tA`). There should be a similar one for dap mode (or replace the pdb ones if dap mode is active).

**Comment by yyoncho** [comment]
This is already done, could be closed.
