### ISSUE TITLE
configuration-layer/delete-orphan-packages fails when trying to uninstall site-local packages

### ISSUE THREAD

**Issue by nbraud** [syl20bnr/spacemacs#11160]
#### Description :octocat:

`configuration-layer/delete-orphan-packages` fails when there are site-local installed packages, interupting the loading of the configuration without providing a useful error message.

#### Reproduction guide :beetle:
- Install Spacemacs
- Install some Emacs package through your system package management (for instance, `apt install dpkg-dev-el` on Debian)
- Set `dotspacemacs-install-packages 'used-only` in `.spacemacs`
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs fails to start

*Expected behaviour:* :heart: :smile:
Spacemacs starts correctly, and provides a notice that there are seemingly-unused packages, installed system-wide, that cannot be uninstalled.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(graphviz elixir sql ocaml asciidoc ruby go python html nginx rust haskell julia ansible yaml ivy emacs-lisp git markdown theming org version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
Backtrace obtained with `emacs --debug-init`.

Debugger entered--Lisp error:
```elisp
  (error "Package ‘dpkg-dev-el-37.0’ is a system package, not deleting")
  signal(error ("Package ‘dpkg-dev-el-37.0’ is a system package, not deleting"))
  error("Package `%s' is a system package, not deleting" "dpkg-dev-el-37.0")
  package-delete([cl-struct-package-desc dpkg-dev-el (37 0) "Emacs modes for debian packaging" ((debian-el (37))) nil nil "/usr/share/emacs/25.2/site-lisp/elpa/dpkg-dev-el-37.0" nil nil] t t)
  (progn (package-delete p t t))
  (if p (progn (package-delete p t t)))
  (let ((p (car (cdr (assq pkg-name package-alist))))) (if p (progn (package-delete p t t))))
  (cond ((version<= "25.0.50" emacs-version) (let ((p (car (cdr (assq pkg-name package-alist))))) (if p (progn (package-delete p t t))))) (t (let ((p (car (cdr (assq pkg-name package-alist))))) (if p (progn (package-delete p))))))
  configuration-layer//package-delete(dpkg-dev-el)
  (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (progn (spacemacs-buffer/set-mode-line "Uninstalling not used packages...") (spacemacs//redisplay) (spacemacs-buffer/append (format "Found %s orphan package(s) to delete...\n" orphans-count)) (setq deleted-count 0) (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n"))
  (if orphans (progn (spacemacs-buffer/set-mode-line "Uninstalling not used packages...") (spacemacs//redisplay) (spacemacs-buffer/append (format "Found %s orphan package(s) to delete...\n" orphans-count)) (setq deleted-count 0) (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n")) (spacemacs-buffer/message "No orphan package to delete."))
  (let* ((dependencies (configuration-layer//get-packages-upstream-dependencies-from-alist)) (implicit-packages (configuration-layer//get-implicit-packages-from-alist packages)) (orphans (configuration-layer//get-orphan-packages packages implicit-packages dependencies)) (orphans-count (length orphans)) deleted-count) (if orphans (progn (spacemacs-buffer/set-mode-line "Uninstalling not used packages...") (spacemacs//redisplay) (spacemacs-buffer/append (format "Found %s orphan package(s) to delete...\n" orphans-count)) (setq deleted-count 0) (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n")) (spacemacs-buffer/message "No orphan package to delete.")))
  configuration-layer/delete-orphan-packages((ace-window adoc-mode alchemist anaconda-mode ansible ansible-doc async auto-compile bind-key bind-map bundler cargo chruby cmm-mode color-theme-solarized company-ghc company-ghci counsel counsel-projectile css-mode cython-mode diff-hl diff-mode diminish elisp-slime-nav elixir-mode emmet-mode evil evil-magit evil-visualstar exec-path-from-shell flx flycheck-credo flycheck-julia flycheck-mix gh-md ghc git-commit git-gutter git-gutter+ git-gutter-fringe git-gutter-fringe+ git-link git-messenger git-timemachine gitattributes-mode gitconfig-mode gitignore-mode gnuplot go-eldoc ...))
  (progn (configuration-layer/delete-orphan-packages packages))
  (if (and (or (eq (quote used) dotspacemacs-install-packages) (eq (quote used-only) dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages)))
  (let ((packages (append (configuration-layer/filter-objects configuration-layer--used-distant-packages (function (lambda (x) (let ... ...)))) (if (eq (quote all) dotspacemacs-install-packages) (progn (let (all-other-packages) (let ... ...) (configuration-layer//get-distant-packages all-other-packages nil))))))) (configuration-layer//install-packages packages) (if (and (or (eq (quote used) dotspacemacs-install-packages) (eq (quote used-only) dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages))))
  (if no-install nil (let ((packages (append (configuration-layer/filter-objects configuration-layer--used-distant-packages (function (lambda ... ...))) (if (eq (quote all) dotspacemacs-install-packages) (progn (let ... ... ...)))))) (configuration-layer//install-packages packages) (if (and (or (eq (quote used) dotspacemacs-install-packages) (eq (quote used-only) dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages)))))
  configuration-layer/sync()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/nicoo/.emacs.d/init.el" nil t)  ; Reading at buffer position 1264
  load-with-code-conversion("/home/nicoo/.emacs.d/init.el" "/home/nicoo/.emacs.d/init.el" t t)
  load("/home/nicoo/.emacs.d/init" t t)
  #[0 "^H\205\266^@	\306=\203^Q^@\307^H\310Q\202?^@	\311=\204^^^@\307^H\312Q\202?^@\313\307\314\315#\203*^@\316\202?^@\313\307\314\317#\203>^@\320\321\322!D\nB^R\323\202?^@\316\324^S\325^A\324\211#\210^K\324=\203e^@\326\327\330\307^H\331Q!\"\325^A\324\211#\210^K\324=\203d^@^A^S\210^K\203\247^@\332^K!\333\232\203\247^@\334^K!\211\335P\336^A!\203\201^@\211\202\214^@\336^B!\203\213^@^A\202\214^@\314\262^B^A\203\245^@\337^B^K\"\203\243^@\340\341^C^K#\210\342\343!\210^A^S\266^B\f?\205\264^@\314^]\325\344\324\211#)\262^A\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" initialization format-message "`_emacs' init file is deprecated, please use `.emacs'" "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7]()
  command-line()
  normal-top-level()
```

**Comment by ahmednofal** [comment]
I am having a similar experience with emacs25 on ubuntu 18.04, but fails with a different system package called dash functional the debugged trail is :  (error "Package ‘dash-functional-1.2.0’ is a system package, not deleting")
  signal(error ("Package ‘dash-functional-1.2.0’ is a system package, not deleting"))
  error("Package `%s' is a system package, not deleting" "dash-functional-1.2.0")
  package-delete([cl-struct-package-desc dash-functional (1 2 0) "Collection of useful combinators for Emacs Lisp" ((dash (2 0 0))) nil nil "/usr/share/emacs/25.2/site-lisp/elpa/dash-functional-1.2.0" nil nil] t t)
  (progn (package-delete p t t))
  (if p (progn (package-delete p t t)))
  (let ((p (car (cdr (assq pkg-name package-alist))))) (if p (progn (package-delete p t t))))
  (cond ((version<= "25.0.50" emacs-version) (let ((p (car (cdr (assq pkg-name package-alist))))) (if p (progn (package-delete p t t))))) (t (let ((p (car (cdr (assq pkg-name package-alist))))) (if p (progn (package-delete p))))))
  configuration-layer//package-delete(dash-functional)
  (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (progn (spacemacs-buffer/set-mode-line "Uninstalling not used packages...") (spacemacs//redisplay) (spacemacs-buffer/append (format "Found %s orphan package(s) to delete...\n" orphans-count)) (setq deleted-count 0) (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n"))
  (if orphans (progn (spacemacs-buffer/set-mode-line "Uninstalling not used packages...") (spacemacs//redisplay) (spacemacs-buffer/append (format "Found %s orphan package(s) to delete...\n" orphans-count)) (setq deleted-count 0) (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n")) (spacemacs-buffer/message "No orphan package to delete."))
  (let* ((dependencies (configuration-layer//get-packages-upstream-dependencies-from-alist)) (implicit-packages (configuration-layer//get-implicit-packages-from-alist packages)) (orphans (configuration-layer//get-orphan-packages packages implicit-packages dependencies)) (orphans-count (length orphans)) deleted-count) (if orphans (progn (spacemacs-buffer/set-mode-line "Uninstalling not used packages...") (spacemacs//redisplay) (spacemacs-buffer/append (format "Found %s orphan package(s) to delete...\n" orphans-count)) (setq deleted-count 0) (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n")) (spacemacs-buffer/message "No orphan package to delete.")))
  configuration-layer/delete-orphan-packages((ace-jump-helm-line ace-link ace-window adaptive-wrap aggressive-indent async auto-compile auto-highlight-symbol avy bind-key bind-map clean-aindent-mode column-enforce-mode define-word desktop diminish dumb-jump elisp-slime-nav eval-sexp-fu evil evil-anzu evil-args evil-ediff evil-escape evil-exchange evil-iedit-state evil-indent-plus evil-lisp-state evil-matchit evil-mc evil-nerd-commenter evil-numbers evil-search-highlight-persist evil-surround evil-tutor evil-unimpaired evil-visual-mark-mode evil-visualstar exec-path-from-shell expand-region eyebrowse fancy-battery fill-column-indicator flx-ido golden-ratio google-translate helm helm-ag helm-descbinds helm-flx ...))
  (progn (configuration-layer/delete-orphan-packages packages))
  (if (and (or (eq (quote used) dotspacemacs-install-packages) (eq (quote used-only) dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages)))
  (let ((packages (append (configuration-layer/filter-objects configuration-layer--used-distant-packages (function (lambda (x) (let ... ...)))) (if (eq (quote all) dotspacemacs-install-packages) (progn (let (all-other-packages) (let ... ...) (configuration-layer//get-distant-packages all-other-packages nil))))))) (configuration-layer//install-packages packages) (if (and (or (eq (quote used) dotspacemacs-install-packages) (eq (quote used-only) dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages))))
  (if no-install nil (let ((packages (append (configuration-layer/filter-objects configuration-layer--used-distant-packages (function (lambda ... ...))) (if (eq (quote all) dotspacemacs-install-packages) (progn (let ... ... ...)))))) (configuration-layer//install-packages packages) (if (and (or (eq (quote used) dotspacemacs-install-packages) (eq (quote used-only) dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages)))))
  configuration-layer/sync()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/naufal/.emacs.d/init.el" nil t)  ; Reading at buffer position 1264  load-with-code-conversion("/home/naufal/.emacs.d/init.el" "/home/naufal/.emacs.d/init.el" t t)
  load("/home/naufal/.emacs.d/init" t t)

 command-line()
  normal-top-level()

**Comment by KirinDave** [comment]
I've closed the other issue, but it's worth noting that this issue completely breaks installation on fresh Ubuntu 18.* images.

**Comment by copyninja** [comment]
Can any one tell me why this issue is closed? Is there a way around this?. I'm facing this issue with as I've packages like `dpkg-dev-el` `devscripts-el` on my system. I checked both issue mentioned here and both are closed but no resolution is mentioned.

**Comment by master-smily** [comment]
Started on a fix

**Comment by duianto** [comment]
master-smiley's PR has been merged into the `develop` branch:
Only remove non system pkg #11810
