### ISSUE TITLE
Setting conditions on directory

### ISSUE THREAD

**Issue by AyushGupta19** [syl20bnr/spacemacs#11164]
Hi to everyone. This is my first ever question on Github. 

I am using Emacs for Java with jdee. The problem is that whenever I open Emacs it loads very slow. My default text editor is Emacs so many time it loads jdee but I didn't need them.So I want to set conditions on my java directory so whenever I use that directory it loads jdee
`(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-color-names-vector
   ["#242424" "#e5786d" "#95e454" "#cae682" "#8ac6f2" "#333366" "#ccaa8f" "#f6f3e8"])
 '(custom-enabled-themes (quote (deeper-blue)))
 '(inhibit-startup-screen t)
 '(jdee-server-dir "C:/Emacs/jdee-20180711.2036/"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
(add-to-list 'load-path "C:/Emacs/jdee-20180711.2036/")
(load "jdee")
`

**Comment by Compro-Prasad** [comment]
@AYUSH-GUPTA-AYUSH I would recommend you to link your dotfile aka `.spacemacs` located in your home directory represented by `/home/username/.spacemacs` or `/Users/username/.spacemacs`. Do use a pastebin to show the contents of the dotfile.

GitHub supports markdown. It would be great to see the code in a section enclosed within triple backticks(`) each on a separate line.

Note: This was not the answer to your question. I just provided some details on how to ask questions by providing some details about your setup.

**Comment by smile13241324** [comment]
@AYUSH-GUPTA-AYUSH you can set a directory variable via `SPC f v d` this variable is set whenever emacs loads that directory. I would recommend to put this into your project.

However loading an emacs package manually with `load` is really a bad habit in spacemacs as this requires you to manually take care about compiling and autoloading. Consider migrating to the java-layer and use one of the supported spacemacs backends or at least let spacemacs install `JDEE` via `dotspacemacs-additional-packages` which would at least compile the file. 

More information about setting variables you can find in the [manual](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#renaming-files-in-a-directory).
