### ISSUE TITLE
How do I use LSP with Java/Python/Rust/C++?

### ISSUE THREAD

**Issue by haydenflinner** [syl20bnr/spacemacs#11161]
Just making this as a sort of knowledge collection issue. I wanted to try out one of the various LSP layers (I don't really care what language), but I think I might just be a bit early.

Ideally, I'd like to be able to install a language server, copy paste some easy elisp at worst, and be ready to go. When I started writing this issue it was because I had no success getting a C/C++ LSP system going in ~5 minutes, which is about when my patience for new tools runs out when given no feedback. So, I went digging for the status of LSP modes for each language, here's what I found:

Rust - [This](https://github.com/syl20bnr/spacemacs/issues/10443#issuecomment-391721510) issue is as close as I see to that, but it only gives you lsp-ui, whatever that is. Not completion, so no go for now.

C/C++ - [This](https://github.com/syl20bnr/spacemacs/issues/10134) seemed like it might be the closest thing, got there from quicknir's cpp2 layer, but then by the end of the thread MaskRay forked cquery and I jumped out. Did see [10486](https://github.com/syl20bnr/spacemacs/pull/10486) though, which I think I can just checkout and add the layer he mentions to my config and be ready to go? Will try that out tomorrow, I think.

Java - [Finished layer link!](https://github.com/Ruin0x11/lsp-intellij-spacemacs) this one appears to be done and ready to go, just that the author didn't submit a pull request. But then there's also [this](https://github.com/syl20bnr/spacemacs/pull/10820), not sure what the difference is unless maybe Ruin's just got stale and this new one will be able to be merged.

Edit: On the bright side, it looks like everyone is standardizing behind #10486, which means we will no longer have BS like the CPP layer's find reference being `, r` and anaconda mode's being `, r u`.

Python -[Finished layer link!](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/python) This appears to be done and ready to go!

**Comment by smile13241324** [comment]
The integration of LSP modes for the various language layers is currently pretty much an on going topic. For now the only one which I did find working as expected was the python one and also this had still some parsing issues with my source, which Anaconda did read without problems.

I think if we want to have Spacemacs support the latest and greates LSP servers for the various languages we have to add them to the various layers, the core team will surely not  be able to handle that giving the insane amount of supported languages for Spacemacs.

As to knowledge gathering don't forget #11137 which is a request to integrate LSP for go containing a go lsp server reference.

PS: lsp-mode and lsp-ui are the core emacs packages supplying LSP integration. LSP-UI contains the highlevel api, lsp-mode the low-level stuff. So if the Rust-layer supports lsp-ui it should pretty much have a working integration already.

PPS: I think there is also an LSP-layer now, providing some standard functions for lsp integrations into spacemacs.

**Comment by smile13241324** [comment]
For everybody who wishes to integrate a certain LSP server I have found #10211 where @syl20bnr mentiones the python layer to be a good example of how to add LSP support to a language layer.

So this would probably be a good starting point.

**Comment by haydenflinner** [comment]
Trying to get #10486 C++ LSP to work has been great fun. I grabbed it with `hub pr checkout 10486`.                                                        
I installed the cquery repos from arch repo, but I saw warnings in the buffer that we weren't finding cquery-clang or something like that. So I tried building  cquery from source. Cquery insisted on downloading clang, eventually failed to find ncurses. So I installed ncurses, it was too new, I just copied libtinfo.so.6 back to .so.5, seems to be working now.

Then I was getting errors when running lsp-preprocess-file and I'm not sure things were working right: `c++` was getting unrecognized arguments. So as a temporary hack, I symlinked clang++ to my tinkering folder as c++ and added that to my path; lo and behold, lots of things start working (although some of them worked before I switched to clang).

The end result, though, is promising:
Working:
- show heirarchy,
- go to type definition
Not working:
- cquery-references read doesn't seem to work.
- Go to implementation doesn't work through `, g i`, but `gd` works. I don't know if that goes through lsp or not, but it's going to std funcs without an `rdm` running (I never installed rtags on this box).
- autocomplete through CTRL+N/P, but it's shown as working in the underlying plugins, so maybe this demo layer is just missing the hooks. If that's the case, then I'm very close to replacing my rtags setup.

**Comment by Compro-Prasad** [comment]
I just followed instructions on `emacs-ccls` maintained by MaskRay and got it setup without the need of a separate layer. I didn't had the need to write a layer. https://github.com/Compro-Prasad/.spacemacs.d/blob/master/compro-cpp-lang.org#c-ide-configuration

**Comment by smile13241324** [comment]
@haydenflinner great, thanks for trying this out for C++, would you mind trying the same for Java and posting the results, I would then start with integrating the first LSP servers.

@Compro-Prasad yep its not about a new layer, rather the idea would be to have the possibility in the respective language layers to switch to an `LSP backend` instead of the standard `language` specific solution. This replaces the pretty old school `company UI` elements and replaces it with the superb `LSP-mode` and `LSP-UI` stuff. A good example for this is the `python-layer`.

**Comment by haydenflinner** [comment]
Starting on that right now.

I hope as part of this new feature going into all of the layers we can standardize one sequence for things like 
>CPP layer's find reference being , r and anaconda mode's being , r u.

**Comment by smile13241324** [comment]
Yep lets hope so, currently improvements on the lsp layer are discussed unfortunately this has been going on for a quite a while now without any maintainers so the resulting construct is difficult to integrate into the spacemacs system, but lets look forward, people are now working on this.

**Comment by smile13241324** [comment]
Yeah go LSP support has been merged #10855 :1st_place_medal:

**Comment by haydenflinner** [comment]
Java support is not working for me yet, I just get `Error from the language Server: Unable to find file [the file I'm in] (Internal Error`

**Comment by smile13241324** [comment]
Thanks for trying this out :) 

As to java the information provided by cmake's compile_commands.json is normally provided in java by a pom.xml or build.gradle file depending on the build system used.

So if you have used Apache POI it will most likely have a pom.xml for maven which will be used for getting project information.

**Comment by smile13241324** [comment]
Yep I also agree that as it is the paths should not have to be hard coded but should be obtained by emacs projectile package instead, but I doubt that this will be fixed with the first PR.

**Comment by chriskaukis** [comment]
I've been struggling, trying, and re-trying to get this working for Ruby trying to use either `lsp-ruby` package (https://github.com/emacs-lsp/lsp-ruby), `emacs-solargraph` (https://github.com/guskovd/emacs-solargraph), and `lsp-solargraph` (https://github.com/The-BigDaddy/lsp-solargraph) with no luck. 

I've add the lsp-ruby package via additional packages 
```
(lsp-ruby :location (recipe :fetcher github :repo "emacs-lsp/lsp-ruby")```

then in `user-config` 
```
(require 'lsp-ruby) 
(add-hook 'ruby-mode-hook #'lsp-ruby-enable)
```
When I open a Ruby file 
```
File mode specification error: (file-error make client process failed Connection refused :name lsp-ruby TCP connection :buffer nil :host 127.0.0.1 :service 7658 :nowait nil :tls-parameters nil)
```
I have confirmed that the LSP server is running (Solargraph) via `netstat` and I have tried running both Solargraph annually ahead of opening a Ruby file and letting it start the server automatically. 

I would appreciate any help? Where to start? Where exactly to look? I've wasted many hours on this.

**Comment by yyoncho** [comment]
For some reason, the emacs cannot establish connection. If netstat is confirming that the port is taken you may try the following code with different params (e. g. using localhost instead of 127.0.0.1). 

``` emacs-lisp
(open-network-stream (concat name " TCP connection")
                   nil host port
                   :type 'plain)
```

**Comment by yyoncho** [comment]
My comment was stated badly: So, the problem is that when you run lsp-ruby-enable it starts the server and then tries to connect with the code that I sent you above but it fails. Once the server running you may try to run the `open-network-stream` function by yourself. If you get this invocation right you will be able to determine what the problem is.

E. g. try to connect using "localhost" instead of 127.0.0.1:
``` elisp
(open-network-stream "TCP connection"
                   nil "localhost" 7658
                   :type 'plain)
```

**Comment by chriskaukis** [comment]
I tried using localhost and 127.0.0.1 and this is the output:

```
ELISP> (open-network-stream "TCP connection" nil "localhost" 7658 :type 'plain)
#<process TCP connection<1>>
ELISP> (open-network-stream "TCP connection" nil "127.0.0.1" 7658 :type 'plain)
#<process TCP connection<2>>
ELISP> 
```

**Comment by yyoncho** [comment]
I suspect that it takes some time for the server to take the port but lsp-mode is trying to connect right away, bellow is the connection code redefined with sleep in between, can you eval the code, turn on debug-on-error and open new ruby file and call lsp-ruby-enable.

```emacs-lisp
(defun lsp--make-tcp-connection (name command command-fn host port stderr)
  (lambda (filter sentinel)
    (let* ((command (if command-fn (funcall command-fn) command))
            (final-command (if (consp command) command (list command)))
            proc tcp-proc)
      (unless (executable-find (nth 0 final-command))
        (error (format "Couldn't find executable %s" (nth 0 final-command))))
      (setq proc (make-process
                   :name name
                   :connection-type 'pipe
                   :coding 'no-conversion
                   :command final-command
                   :sentinel sentinel
                   :stderr stderr
                   :noquery t))
      (sit-for 2)
      (setq tcp-proc (open-network-stream (concat name " TCP connection")
                                          nil host port
                                          :type 'plain))
      ;; TODO: Same :noquery issue (see above)
      (set-process-query-on-exit-flag (get-buffer-process (get-buffer stderr)) nil)
      (set-process-query-on-exit-flag tcp-proc nil)
      (set-process-filter tcp-proc filter)
      (cons proc tcp-proc))))
```

**Comment by chriskaukis** [comment]
```
Debugger entered--Lisp error: (void-variable command-fn)
  (if command-fn (funcall command-fn) command)
  (let* ((command (if command-fn (funcall command-fn) command)) (final-command (if (consp command) command (list command))) proc tcp-proc) (unless (executable-find (nth 0 final-command)) (error (format "Couldn't find executable %s" (nth 0 final-command)))) (setq proc (make-process :name name :connection-type 'pipe :coding 'no-conversion :command final-command :sentinel sentinel :stderr stderr :noquery t)) (sit-for 2) (setq tcp-proc (open-network-stream (concat name " TCP connection") nil host port :type 'plain)) (set-process-query-on-exit-flag (get-buffer-process (get-buffer stderr)) nil) (set-process-query-on-exit-flag tcp-proc nil) (set-process-filter tcp-proc filter) (cons proc tcp-proc))
  (lambda (filter sentinel) (let* ((command (if command-fn (funcall command-fn) command)) (final-command (if (consp command) command (list command))) proc tcp-proc) (unless (executable-find (nth 0 final-command)) (error (format "Couldn't find executable %s" (nth 0 final-command)))) (setq proc (make-process :name name :connection-type 'pipe :coding 'no-conversion :command final-command :sentinel sentinel :stderr stderr :noquery t)) (sit-for 2) (setq tcp-proc (open-network-stream (concat name " TCP connection") nil host port :type 'plain)) (set-process-query-on-exit-flag (get-buffer-process (get-buffer stderr)) nil) (set-process-query-on-exit-flag tcp-proc nil) (set-process-filter tcp-proc filter) (cons proc tcp-proc)))(#f(compiled-function (proc output) #<bytecode 0x40edb9ed>) #f(compiled-function (process exit-str) #<bytecode 0x516a3575>))
  lsp--start(#s(lsp--client :language-id #f(compiled-function (_) #<bytecode 0x4bb0e9b9>) :send-sync nil :send-async nil :type nil :new-connection (lambda (filter sentinel) (let* ((command (if command-fn (funcall command-fn) command)) (final-command (if (consp command) command (list command))) proc tcp-proc) (unless (executable-find (nth 0 final-command)) (error (format "Couldn't find executable %s" (nth 0 final-command)))) (setq proc (make-process :name name :connection-type 'pipe :coding 'no-conversion :command final-command :sentinel sentinel :stderr stderr :noquery t)) (sit-for 2) (setq tcp-proc (open-network-stream (concat name " TCP connection") nil host port :type 'plain)) (set-process-query-on-exit-flag (get-buffer-process (get-buffer stderr)) nil) (set-process-query-on-exit-flag tcp-proc nil) (set-process-filter tcp-proc filter) (cons proc tcp-proc))) :stderr "*lsp-ruby stderr*<2>" :get-root #f(compiled-function () #<bytecode 0x508b1805>) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 0/65 0x4bb0e9c5> :request-handlers #<hash-table equal 0/65 0x49120825> :response-handlers #<hash-table eql 0/65 0x5114a8fd> :string-renderers (("ruby" . lsp-ruby--render-string)) :last-id 0 :enable-function lsp-ruby-enable :prefix-function nil :uri-handlers #<hash-table equal 0/65 0x5114abd5> :action-handlers #<hash-table equal 0/65 0x50f8d8ad> :default-renderer nil) nil)
  lsp--enable-tcp-client(lsp-ruby :language-id "ruby" :language-id-fn nil :root-directory-fn #f(compiled-function () #<bytecode 0x508b1805>) :command ("solargraph" "socket") :command-fn nil :host "127.0.0.1" :port 7658 :ignore-regexps nil :ignore-messages nil :extra-init-params nil :initialize-fn lsp-ruby--initialize-client :enable-function lsp-ruby-enable :prefix-function nil)
  lsp-ruby-enable()
  funcall-interactively(lsp-ruby-enable)
  call-interactively(lsp-ruby-enable record nil)
  command-execute(lsp-ruby-enable record)
  helm-M-x(nil #("lsp-ruby-enable" 0 15 (match-part "lsp-ruby-enable")))
  funcall-interactively(helm-M-x nil #("lsp-ruby-enable" 0 15 (match-part "lsp-ruby-enable")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

Here is the output after evaluating the code you have above and running lsp-ruby-enable.

**Comment by yyoncho** [comment]
@chriskaukis I pinged you on gitter

**Comment by sdwolfz** [comment]
@chriskaukis @yyoncho If it helps you collaborate better, open up a PR with your changes, even if they don't work and put a `[WIP]` in the beginning of the title. I will look at it out of curiosity but not as a reviewer (unless requested) so there should be no pressure for you to get everything right. Maybe more people interested in ruby LSP will get involved.

**Comment by Miciah** [comment]
@chriskaukis, what version of Emacs are you using? Any chance you are using Emacs 24.2 or older? It looks like a closure isn't properly binding `command-fn`.

**Comment by yyoncho** [comment]
@Miciah we solved the issue offline. The was evaluating the code in ielm which as by default lexical-binding set to nil. @chriskaukis has found a solution to use STDOUT client instead of TCP one. The TCP related issue must be addressed on the `lsp-mode` side.

**Comment by chriskaukis** [comment]
@yyoncho @Miciah I realized Solargraph now has STDOUT support. So, I commented out the TCP in the ruby-lsp package. Then replaced the with "solargraph" "stdio" for execution instead of what ever that other game was. Works flawless.

I've been using Emacs (Mac) 26.1 for a while on develop Spacemacs branch updating regularly.

**Comment by chriskaukis** [comment]
@sdwolfz I just saw your message. I'll put up a PR and mention you as soon as I can.

**Comment by jvillasante** [comment]
Yesterday a friend showed me how easy it was to get RLS on VsCode. Has anybody been able to integrate RLS for Rust development?

**Comment by yyoncho** [comment]
@jvillasante there is https://github.com/emacs-lsp/lsp-rust and also https://github.com/syl20bnr/spacemacs/issues/10443 on spacemacs side.

**Comment by sdwolfz** [comment]
@chriskaukis Have you managed to get your ruby LSP working? I played with it a while ago and di not manage go get to far. If you submit a PR you'll be my personal hero!

**Comment by yyoncho** [comment]
@sdwolfz 
What problems did you hit?

As a side note, the following lsp changes are upcoming: https://github.com/emacs-lsp/lsp-mode/pull/469:

1. There will be single entry point for every lsp language
2. `lsp` mode will autoconfigure itself in case `lsp-ui`, `company-lsp` are present.

As a result the only thing that will differ between `lsp` languages will be installation instructions and extension methods if present.

**Comment by sdwolfz** [comment]
@yyoncho I don't really remember since it was ~2 months ago and I only spent a few minutes on it, I was getting errors related to the port being hardcoded and different from what solargraph used, and had issues with the solargraph server version as well. 

I will try again this evening and get back to you with what I find.

**Comment by sdwolfz** [comment]
OK so It's definitely working now. I tried it on a relatively large project (redmine) on a fairly old laptop and it needed a bigger `lsp-response-timeout`.

Hmm... I think I could get something done myself and open up a PR, but I will need some volunteers to review it.

**Comment by sdwolfz** [comment]
For reference here is the PR: #11593.

**Comment by yyoncho** [comment]
@sdwolfz Nice, I am planning implementing debugger support for Ruby in `dap-mode`.

**Comment by yyoncho** [comment]
Heads up for upcoming `lsp-mode` changes.

We are working on `lsp.el` which will replace the current `lsp-mode.el` package and it is not backward compatible. The following changes will affect spacemacs:

1. There will be single entry point for all of the languages.
2. The following packages will no longer be needed:
a) lsp-rust
b) lsp-ruby
c) lsp-python
d) lsp-cland
since they will be configured directly in `lsp.el` and they will work out of the box.
3. lsp.el by default will autoconfigure company-lsp/lsp-ui if they are available. 

After we move the packages to `lsp.el` https://github.com/emacs-lsp/lsp-mode/issues/479 we will delete the existing once. 

In my local test environment in order to make Spacemacs work for a particular language the following lines are sufficient (in addition the @cormacc changes https://github.com/syl20bnr/spacemacs/pull/11626)
``` emacs-lisp
 (add-hook 'go-mode-hook 'lsp)
```

(cc @cormacc as the author of the lsp layer).

**Comment by Miciah** [comment]
From an integration perspective, the forthcoming `lsp.el` sounds a lot like [Eglot](https://github.com/joaotavora/eglot), which similarly provides a single point of entry, support for many language servers, and integration with other packages including company, all in a single package.  If there is interest, once the LSP layer is using `lsp.el`, I could look into adding an option to the layer to use Eglot as an alternative.

**Comment by cormacc** [comment]
Sounds good @yyoncho -- do I need to make any changes to the lsp layer or c-c++ layers?

**Comment by yyoncho** [comment]
@cormacc Which language server do you use ccls or cquery? Both are not integrated with lsp.el at this point but I believe @MaskRay could provide some integration for ccls soon. 

1. emacs-{server}-enable will be changed to simply invoking `lsp`.
2. We should decide whether Spacemacs will rely on lsp.el autoconfiguration https://github.com/emacs-lsp/lsp-mode/blob/master/lsp.el#L2879 . 

@sdwolfz it would be good to make adding new lsp language support to a layer easier since `lsp.el` will support probably 20+ languages right out of the box.

**Comment by MaskRay** [comment]
emacs-ccls has been migrated

emacs-cquery/pull/54 will migrate it to lsp.el

**Comment by cormacc** [comment]
Thanks @MaskRay, @yyoncho -- using ccls, and seems to be working fine with some minor local modifications to the c-c++ layer. I'll submit a PR once my pending PR against the lsp layer get's resolved either way -- it's a headache managing multiple PR branches at once.

**Comment by yyoncho** [comment]
@cormacc we want to move  the deletion of the old legacy lsp-mode.el forward and spacemacs is one of the latest clients that were not updated. Given the fact that spacemacs is frozen and it is not clear how long it will take IMO it will be better to merge both PR into one. I will upgrade the python lsp layer + rust lsp layer + java lsp layer based. Alternatively, we (lsp-mode team) could delete the legacy code and ask spacemacs users to use melpa stable until the layers are fixed. 

@sdwolfz @cormacc, what do you think?

**Comment by sdwolfz** [comment]
@yyoncho Spacelpa (spacemacs snapshot of melpa) should still have the packages as a snapshot was created for version 0.300 a few weeks ago. While we have a code freeze and all efforts are directed towards creating the release notes (see the new branch: https://github.com/syl20bnr/spacemacs/tree/release_notes_0.300) if there's a bug or breaking change that needs to be addressed I accept PRs and will merge them before releasing.

Show me what needs to be done or point me to the PRs and I will get to it right away.

**Comment by yyoncho** [comment]
I want to unblock deletion of lsp-mode code since we currently have to support parallel versions of lsp mode cliens which is PITA. IMO merging https://github.com/syl20bnr/spacemacs/pull/11626 and your lsp.el changes and me contributing java python and rust changes to that pr seems like a good solution. If you want to fix the other layers I am fine too.

**Comment by cormacc** [comment]
Sure - I'll have a couple of questions, but maybe I'll make an initial commit amendment and we can continue the discussion over at #11626 -- will tag you when it goes in.

**Comment by jerome-diver** [comment]
so at the final time, where is the lsp package ? i can not find it.

**Comment by Compro-Prasad** [comment]
@jerome-diver You need to be on develop to use `lsp` as a layer. Then change the value of `python-backend` variable to `lsp`.

**Comment by yyoncho** [comment]
@duianto @smile13241324 this is already solved.
