### ISSUE TITLE
github layer is slow

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#11176]
I activated the `github` layer yesterday and it is terribly slow for large repos like `spacemacs`, is there a way around it, e.g. deactivating it for certain directories or limiting the number of issues and PRs to load?

**Comment by sdwolfz** [comment]
#11071 Introduced this. Unfortunately I was not able to find a fix and ended up excluding `magithub` and forgot about the problem.

@Miciah let's find a solution for this and document it here.

**Comment by Miciah** [comment]
Magithub uses a Git configuration variable to configure online or offline mode.  This variable can be set globally or locally (for a specific Git repository).

To toggle online/offline mode for a specific repository, use <kbd>SPC g m H C o</kbd>.

To change to offline mode globally, the following Emacs form should work:
```emacs-lisp
(magit-set "false" "--global" "magithub.online")
```
Alternatively, you can use a Git command:
```shell
git config --global magithub.online false
```

The Magit status buffer will indicate if you are in offline mode.  Alternatively, you can check whether Magithub is in online mode using <kbd>M-:</kbd> `(magithub-online-p)`.

**Comment by gdkrmr** [comment]
ok, that worked. Now I still have the problem that the `magit` buffer for the `spacemacs` repository has almost 2000 issues and moving the cursor in it causes it to hang for seconds.

**Comment by Miciah** [comment]
Does https://github.com/syl20bnr/spacemacs/pull/11184 look like a reasonable solution?

**Comment by goofansu** [comment]
@gdkrmr 

You need these

``` bash
git config --global --bool magithub.status.includestatusheader false
git config --global --bool magithub.status.includepullrequestssection false
git config --global --bool magithub.status.includeissuessection false
```

**Comment by gdkrmr** [comment]
Thanks! `git config --global magithub.online false` helped for now, I still have to include the github layer into a productive workflow. I will come back if there are more issues.

**Comment by sdwolfz** [comment]
#11184 is now merged, this issues is fixed as far as I tested.

**Comment by Miciah** [comment]
#11187 has the requested changes.

**Comment by sdwolfz** [comment]
Perfect, thanks @Miciah for the quick response!
