### ISSUE TITLE
Bind the default describe key to its default Emacs bindings

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1117]
Currently the default help key bindings do not have Helm activated, such as `C-h f` or `C-h v`. We should give it the same ones in `SPC h d`.

**Comment by syl20bnr** [comment]
oh really ? I think they do but one has to lazy-load helm before it works.
So you propose to rebind them to a wrapper like this ? https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/keybindings.el#L74

**Comment by tuhdo** [comment]
Yes.

**Comment by TheBB** [comment]
I can't reproduce this, so I assume it has been fixed in the meantime. Feel free to reopen if not.
