### ISSUE TITLE
git-gutter working strangely

### ISSUE THREAD

**Issue by emmanueltouzery** [syl20bnr/spacemacs#1119]
I'm having two issues with git-gutter in my spacemacs setup:

1. sometimes it does not appear at all, depending on the major mode. For text files (.txt), it does not appear. If I just run M-x haskell-mode then it appears. For git-controlled folders I would always like to have it... Which I assume is also the case for most people? And that's also what's implied by the spacemacs docs I think so maybe I broke something in my setup?

2. when updating the git status outside of emacs sometimes the git-gutter info does not update. I've opened to upstream https://github.com/syohex/emacs-git-gutter/issues/86 including a video showing the problem but upstream seems baffled by the problem so again I think it's either spacemacs or my configuration.

(still reproducing with 0.101.2)

and here's my spacemacs config in case it helps somehow:
https://github.com/emmanueltouzery/dotspacemacs

**Comment by person808** [comment]
Do you have `linum-mode` enabled? I experienced some bugginess with `linum-mode` enabled only in `prog-mode`. #1196 may help if thats the case for you

**Comment by emmanueltouzery** [comment]
no, i don't have display of line numbers set up in any mode, didn't touch the configuration on this.

**Comment by person808** [comment]
Different issue then :(

**Comment by TheBB** [comment]
Since git-gutter has been replaced with diff-hl, I'm closing this issue.
