### ISSUE TITLE
Emacs freezes when starting inferior Python process from TRAMP

### ISSUE THREAD

**Issue by r-zip** [syl20bnr/spacemacs#11195]
#### Reproduction guide :beetle:
- Start Emacs
- Open a remote Python file using TRAMP (e.g. `<SPC>ff /ssh:hostname:filename.py`)
- Start an inferior Python process `<SPC>msi`

*Observed behaviour:* :eyes: :broken_heart:
- Emacs freezes completely.

*Expected behaviour:* :heart: :smile:
- A remote Python REPL should start.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2 GMP

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (quit)
  accept-process-output(#<process *tramp/ssh aws*> 1 nil 0)
  tramp-accept-process-output(#<process *tramp/ssh aws*> 1)
  tramp-wait-for-regexp(#<process *tramp/ssh aws*> nil "\\(^\\|\0\\)[^#$\n]*///6900adc3af884a44113c80db31272293...")
  tramp-wait-for-output(#<process *tramp/ssh aws*>)
  tramp-send-command((tramp-file-name "ssh" nil nil "aws" nil "/tmp/pyF832pu" nil) "tramp_perl_file_attributes /tmp/pyF832pu integer 2...")
  tramp-send-command-and-check((tramp-file-name "ssh" nil nil "aws" nil "/tmp/pyF832pu" nil) "tramp_perl_file_attributes /tmp/pyF832pu integer")
  tramp-barf-unless-okay((tramp-file-name "ssh" nil nil "aws" nil "/tmp/pyF832pu" nil) "tramp_perl_file_attributes /tmp/pyF832pu integer" "`%s' returns with error" "tramp_perl_file_attributes /tmp/pyF832pu integer")
  tramp-send-command-and-read((tramp-file-name "ssh" nil nil "aws" nil "/tmp/pyF832pu" nil) "tramp_perl_file_attributes /tmp/pyF832pu integer")
  tramp-do-file-attributes-w
```

**Comment by Miciah** [comment]
Works for me using the same Spacemacs revision and layers on Emacs 27.0.50 revision ecd7a9407711ebe24d7e07d4402a2d66754ee693 on GNU/Linux.  Exactly what version (Git commit) of Emacs are you using?

Does it work for you if you use `emacs -Q`? I tried the following:

1. `emacs -Q`
2. <kbd>C-x C-f</kbd> `/ssh:user@hostname:foo.py` <kbd>RET</kbd>
3. <kbd>M-x</kbd> `run-python` <kbd>RET</kbd>

It does not freeze for me, and I can enter Python code such as `import os` and `os.system('/bin/ls')` and see that the code is executing on the remote system (TRAMP continues to amaze me!).

**Comment by rzpilgrim** [comment]
If I run emacs -Q, tramp hangs on `Waiting 60s for prompt from remote shell`.

I can definitely open the file using emacs in graphical mode, though.

**Comment by rzpilgrim** [comment]
Update: I just installed emacs 27.0.50 (current `HEAD`). Replicating these steps right after install worked, but the python version selected did not match the `$PATH` on the host machine.

After the Python layer is installed and Emacs is rebooted, the problem returns.

**Comment by rzpilgrim** [comment]
Update: I tried installing pyenv on my machine. After doing that, Emacs did not freeze, but it was again unable to find the correct Python version on either my machine or the remote. Looking into the details.
