### ISSUE TITLE
clang can not complete for c++ function,C is ok

### ISSUE THREAD

**Issue by pzh2386034** [syl20bnr/spacemacs#11192]
pans-MacBook-Pro:oj pan$ clang --version
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47

GNU Emacs 25.3.1

c function complete is ok:

<img width="449" alt="screen shot 2018-08-19 at 8 11 51 pm" src="https://user-images.githubusercontent.com/9897310/44308646-344ef800-a3ec-11e8-9f23-5a7bafe895ee.png">
<img width="467" alt="screen shot 2018-08-19 at 8 13 29 pm" src="https://user-images.githubusercontent.com/9897310/44308659-619ba600-a3ec-11e8-8c40-ae576521230b.png">

c++ function can  not complete:
<img width="559" alt="screen shot 2018-08-19 at 8 14 43 pm" src="https://user-images.githubusercontent.com/9897310/44308663-8d1e9080-a3ec-11e8-8b4a-d9ca194c5df4.png">

pans-MacBook-Pro:oj pan$ cat .clang_complete 
-I/usr/include
-I/usr/include/c++/4.2.1
-I/usr/local/Cellar/llvm/6.0.1/include/c++/v1/

err info in clang-error buffer:
Sun Aug 19 20:14:40 2018
clang failed with error 1:
/usr/local/opt/llvm/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -I/usr/include/sys/ -Xclang -code-completion-at=-:26:17 -

In file included from <stdin>:1:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/iostream:38:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/ios:215:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/iosfwd:90:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/wchar.h:119:
In file included from /usr/include/wchar.h:92:
In file included from /usr/include/_wctype.h:42:
In file included from /usr/include/__wctype.h:62:
/usr/include/_types/_wctype_t.h:32:9: error: unknown type name '__darwin_wctype_t'
typedef __darwin_wctype_t wctype_t;
        ^
In file included from <stdin>:1:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/iostream:38:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/ios:215:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/iosfwd:90:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/wchar.h:119:
/usr/include/wchar.h:98:15: error: unknown type name 'FILE'
wint_t  fgetwc(FILE *);
               ^
/usr/include/wchar.h:99:44: error: unknown type name 'FILE'
wchar_t *fgetws(wchar_t * __restrict, int, FILE * __restrict);
                                           ^
/usr/include/wchar.h:100:24: error: unknown type name 'FILE'
wint_t  fputwc(wchar_t, FILE *);
                        ^
/usr/include/wchar.h:101:40: error: unknown type name 'FILE'
int     fputws(const wchar_t * __restrict, FILE * __restrict);
                                           ^
/usr/include/wchar.h:102:11: error: unknown type name 'FILE'
int     fwide(FILE *, int);
              ^
/usr/include/wchar.h:103:14: error: unknown type name 'FILE'
int     fwprintf(FILE * __restrict, const wchar_t * __restrict, ...);
                 ^
/usr/include/wchar.h:104:13: error: unknown type name 'FILE'
int     fwscanf(FILE * __restrict, const wchar_t * __restrict, ...);
                ^
/usr/include/wchar.h:105:14: error: unknown type name 'FILE'
wint_t  getwc(FILE *);
              ^
/usr/include/wchar.h:113:23: error: unknown type name 'FILE'
wint_t  putwc(wchar_t, FILE *);
                       ^
/usr/include/wchar.h:117:24: error: unknown type name 'FILE'
wint_t  ungetwc(wint_t, FILE *);
                        ^
/usr/include/wchar.h:118:15: error: unknown type name 'FILE'
int     vfwprintf(FILE * __restrict, const wchar_t * __restrict,
                  ^
/usr/include/wchar.h:170:14: error: unknown type name 'FILE'
int     vfwscanf(FILE * __restrict, const wchar_t * __restrict,
                 ^
/usr/include/wchar.h:205:1: error: unknown type name 'FILE'
FILE *open_wmemstream(wchar_t ** __bufp, size_t * __sizep) __API_AVAILABLE(macos(10.13), ios(11.0), tvos(11.0), watchos(4.0));
^
/usr/include/wchar.h:215:18: error: unknown type name 'FILE'
wchar_t *fgetwln(FILE * __restrict, size_t *) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
                 ^
In file included from <stdin>:1:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/iostream:38:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/ios:216:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/__locale:15:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/string:477:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/string_view:176:
In file included from /usr/local/Cellar/llvm/6.0.1/include/c++/v1/__string:57:
/usr/local/Cellar/llvm/6.0.1/include/c++/v1/cstdio:108:9: error: no member named 'FILE' in the global namespace
using ::FILE;
      ~~^
/usr/local/Cellar/llvm/6.0.1/include/c++/v1/cstdio:109:9: error: no member named 'fpos_t' in the global namespace
using ::fpos_t;
      ~~^
/usr/local/Cellar/llvm/6.0.1/include/c++/v1/cstdio:112:9: error: no member named 'fclose' in the global namespace
using ::fclose;
      ~~^
/usr/local/Cellar/llvm/6.0.1/include/c++/v1/cstdio:113:9: error: no member named 'fflush' in the global namespace
using ::fflush;
      ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by smile13241324** [comment]
Can you give a bit more information about your emacs configuration as well as the problem you are having?

Right now I have concluded that auto completion for C++ did not work for you, however judging from the errors you have printed below your screenshots it also looks like you are getting a whole bunch of compiler errors from clang, which could be caused by linking issues.

Please provide some more information preferably via spacemacs `create issue mode`, you can call it via, `SPC h e I`, this includes information about your emacs configuration and a handy template to describe how to reproduce your error and what your expectation is.

With this I can have a look at this, on linux.
