### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by stackerzzq** [syl20bnr/spacemacs#11193]
Will this doc be finished in the feture?

http://spacemacs.org/layers/+spacemacs/spacemacs-editing/README.html

**Comment by sdwolfz** [comment]
That page is available under the develop branch:
https://develop.spacemacs.org/layers/+spacemacs/spacemacs-editing/README.html

It will be available on master at the next release. But unfortunately I do not have an ETA for that.
