### ISSUE TITLE
silence auto-save messages

### ISSUE THREAD

**Issue by wpchou** [syl20bnr/spacemacs#11190]
Is there a way to silence messages of auto-save of both buffer and layout. They keep bugging me and hiding other information like lint warning in minibuffer.

**Comment by smile13241324** [comment]
I would try something of the following [here](http://pragmaticemacs.com/emacs/make-emacs-a-bit-quieter/). The idea is to deactivate the default auto save function and replace it with a silent version of your own. This you could do in your user settings.

For the auto save stuff there is no special thing happening in spacemacs so its all emacs from here.

**Comment by Miciah** [comment]
This issue should be resolved by a recent change in Emacs: "Avoid clearing echo-area message by auto-save-visited-file-name" ([commit 03bb7a8da9](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=03bb7a8da9d16dd3dbd5a3ce56adb449e808bf2a), fixing [Bug#33490](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=33490)).
