### ISSUE TITLE
startup warning ad-disable-advice: rename-buffer is not advised

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#11207]
#### Description :octocat:
startup warning ad-disable-advice: rename-buffer is not advised

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

I am getting the following message on startup:

```
ad-disable-advice: ad-disable-advice: ‘rename-buffer’ is not advised
```

I'm on latest develop using emacs 26.

*Expected behaviour:* :heart: :smile:
no warning

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c122eb6a0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(html helm auto-completion better-defaults emacs-lisp
      (git :variables git-gutter-use-fringe t git-enable-github-support t)
      markdown
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control javascript python yaml
      (c-c++)
      common-lisp latex osx shell-scripts rust)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Miciah** [comment]
This is strange.  Disabling the advice when it is already disabled does not cause any error (at least it did not when I tried), so it looks like in your case, the advice does not exist at all.  However, the eyebrowse package advises `rename-buffer` when the package is loaded, and Spacemacs always installs the eyebrowse package and should be initializing it before it activates persp-mode (which is what tries to disable the advice).

@gnzlbg, can you check a few things?

1. What version of the eyebrowse package is installed? Use <kbd>M-m h d p</kbd> `eyebrowse` <kbd>RET</kbd> to check.
2. What advice does the `rename-buffer` function have? Use <kbd>M-m h d f</kbd> `rename-buffer` <kbd>RET</kbd> and look for the ":around advice:" lines in the help buffer to check.
3. Is there an `ad-Advice-rename-buffer` function? and if so, what is its description? Use <kbd>M-m h d f</kbd> `ad-Advice-rename-buffer` <kbd>RET</kbd> to check.

**Comment by hxx0215** [comment]
@Miciah it seems since [497285523](
https://github.com/syl20bnr/spacemacs/commit/497285523170d223c1d836d06f376d32b2c14cc6) it broken and my eyebrowse version is 20170318.1418
my rename-buffer :around advice: is `'uniquify--rename-buffer-advice'`
and I can't find any function `ad-Advice-rename-buffer`

**Comment by Miciah** [comment]
Thanks! #11213 should fix the problem with old versions of eyebrowse.

@gnzlbg, are you also using an old version of eyebrowse?

**Comment by gnzlbg** [comment]
1. Eyebrowse version:

```
 Status: Installed in ‘eyebrowse-20170318.1418/’ (unsigned). Delete
    Version: 20170318.1418
     Commit: 56af9e96cfc8c03cfdcf3a60b581a8db9fdcbb20
    Summary: Easy window config switching
   Requires: dash-2.7.0, emacs-24.3.1
   Homepage: https://github.com/wasamasa/eyebrowse
   Keywords: convenience 
Other versions: 20180514.1919 (melpa).
```

2. advice:

```


Change current buffer’s name to NEWNAME (a string).
If second arg UNIQUE is nil or omitted, it is an error if a
buffer named NEWNAME already exists.
If UNIQUE is non-nil, come up with a new name using
‘generate-new-buffer-name’.
Interactively, you can set UNIQUE with a prefix argument.
We return the name we actually gave the buffer.
This does not change the name of the visited file (if any).
```

> Is there an ad-Advice-rename-buffer function?

No :/
