### ISSUE TITLE
disable racer mode in the rust layer

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#11205]
Is it possible to disable racer mode in the rust layer ? If so, how ? The readme of the layer doesn't say, and I would prefer to use https://github.com/joaotavora/eglot instead.

**Comment by sdwolfz** [comment]
It should be enough to add `racer` to `dotspacemacs-excluded-packages` in your `.spacemacs` file.

Now, if you want LSP support for the Rust layer, that is something that's not available yet, but contributions are welcome.
