### ISSUE TITLE
evil-open-above/below ("O"/"o") adds whitespace again

### ISSUE THREAD

**Issue by jjzmajic** [syl20bnr/spacemacs#11204]
#### Description :octocat:
Adding an empty line with evil-open-below/above ("o"/"O") adds whitespace when it shouldn't.
This happens with *Hybrid* and *Vim* editing styles.
(Even after closed issue in 2016 - #7239)

#### Reproduction guide :beetle:
- Start Emacs
- Enter *Org mode*
- Place cursor on heading
- Press "o" (`evil-open-below`)

*Observed behaviour:* :eyes: :broken_heart:
- Line is indented by 2 spaces instead of starting at beginning of buffer.

*Expected behaviour:* :heart: :smile:
- Line starts at beginning of buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c122eb6a0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(restructuredtext sphinx helm auto-completion better-defaults emacs-lisp git markdown neotree
                  (org :variables org-enable-github-support t org-enable-bootstrap-support t org-enable-reveal-js-support t org-enable-org-journal-support t)
                  (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
                  spell-checking syntax-checking version-control python ess ocaml c-c++ nim html javascript sql shell-scripts pdf csv colors emoji imenu-list latex
                  (bibtex :variables org-ref-default-bibliography
                          '("~/Papers/references.bib")
                          org-ref-pdf-directory "~/Papers/" org-ref-bibliography-notes "~/Papers/notes.org" bibtex-completion-bibliography "~/Papers/references.bib" bibtex-completion-library-path "~/Papers" bibtex-completion-notes-path "~/Papers/notes.org"))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
N/A
```

**Comment by sdwolfz** [comment]
You should be able to fix that by having `(setq org-adapt-indentation nil)` inside your `dotspacemacs/user-config`.

Now... should we have this setting by default?
