### ISSUE TITLE
Documentation and autocomplete do not work when editing Python files using TRAMP

### ISSUE THREAD

**Issue by r-zip** [syl20bnr/spacemacs#11201]
#### Description :octocat:
Documentation and autocomplete do not work when editing Python files using TRAMP

#### Reproduction guide :beetle:
- Start Emacs
- Open the remote file (e.g. <kbd>SPC</kbd> <kbd>SPC</kbd> <kbd>f</kbd> <kbd>f</kbd> `/ssh:host:/path/to/file.py`)
- Import something: `import numpy as np` or start typing a function name `np.ndarray`
- Wait for failure

*Observed behaviour:* :eyes: :broken_heart:
Documentation/autocomplete is not working.

*Expected behaviour:* :heart: :smile:
Autocomplete suggestions should appear. Eldoc help on functions should appear.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c21d5098)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm auto-completion emacs-lisp git markdown neotree)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2 GMP

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument numberp nil)
  number-to-string(nil)
  anaconda-mode-bootstrap-filter(#<process anaconda-mode> "anaconda_mode port 42731\n" #f(compiled-function () #<bytecode 0x446ab0c1>))
  #f(compiled-function (process output) #<bytecode 0x446ab0d9>)(#<process anaconda-mode> "anaconda_mode port 42731\n")
  read-event(nil t 0.5)
  sit-for(0.5 t)
  company--fetch-candidates("sk")
  company-calculate-candidates("sk")
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer test.py> #<window 3 on test.py> 41 30)
  apply(company-idle-begin (#<buffer test.py> #<window 3 on test.py> 41 30))
  timer-event-handler([t 23422 47636 854585 nil company-idle-begin (#<buffer test.py> #<window 3 on test.py> 41 30) nil 0])

```

**Comment by ltrottier** [comment]
Same issue here.
