### ISSUE TITLE
golang stop working after upgrade to 1.11

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#11217]
I'm very new to go, but after the upgrade to go 1.11 it seems that gocode stopped working.

```
Company: backend (company-go :with company-yasnippet) error "GOCODE PANIC: Please check your code by "go build"" with args (candidates ur)
Company: An error occurred in auto-begin
```

It was working fine before the upgrade.
Any thoughts/

**Comment by asenyshyn** [comment]
nsf/gocode is not maintained anymore use https://github.com/mdempsky/gocode

**Comment by robbyoconnor** [comment]
If you're using modules -- good luck -- it's not supported yet.

**Comment by andres-lowrie** [comment]
^^ Is it on the roadmap to support modules?

**Comment by robbyoconnor** [comment]
@andres-lowrie -- When tooling is updated, sure -- currently neither [go-langserver](https://github.com/sourcegraph/go-langserver), which is used in for [lsp](https://github.com/emacs-lsp/lsp-go/), nor [gocode](https://github.com/mdempsky/gocode) support it. There is an [issue](https://github.com/mdempsky/gocode/issues/46) tracking this in the gocode repo.

**Comment by ihaveadrame** [comment]
I think it's time to support the module. 
Gopls already supports modules but does not correctly recognize modules on spacemac，
There are compatibility issues that need to be resolved, and these problems no longer exist on vscode.

**Comment by robbyoconnor** [comment]
It's relatively painless to switch the language server.

**Comment by ihaveadrame** [comment]
I solved my problem, gopls is ok!!

**Comment by mdempsky** [comment]
Hi. I'm not a Spacemacs user, but I work on Go.

Is Spacemacs enabling company-go / gocode by default? If so, can it be switched to use lsp-mode / gopls by default instead?

gopls is the Go project's officially supported tool for code completion. (Unlike mdempsky/gocode, which was best effort.)

**Comment by robbyoconnor** [comment]
Everything can be overridden.

**Comment by mdempsky** [comment]
I understand users can override the settings. My understanding though is Spacemacs is meant to provide users with good defaults. And if company-go / gocode isn't supported and isn't working, why is it the default instead of lsp-mode / gopls?

**Comment by p554157atch** [comment]
The default behavior with spacemacs and go layer is, it keeps autocomplete mode disabled, and enables the company-mode, which then enabled company-go by default.
This is incorrect behavior.

What is even worse is that `gocode` works sometimes and gives correct suggestions but when you start importing packages, then there is no error or warning things start to fail and company-mode tries to make guesses and gives wrong suggestions.

I spent a lot of time debugging this issue and finally gave up.
