### ISSUE TITLE
Modeline is broken if using emacs in daemon mode

### ISSUE THREAD

**Issue by bennofs** [syl20bnr/spacemacs#11210]
See https://github.com/syl20bnr/spacemacs/commit/378392e7cd513c8ab5fe800f224ed717a52eab39#commitcomment-29857386

The commit regressed the bug I fixed in #10624. With the bug, here's how the modeline looks for me:

![image](https://user-images.githubusercontent.com/3192959/44617945-dcd9dd80-a86c-11e8-9fe6-5e8865464927.png)

**Comment by sorawee** [comment]
Dup of #10181 I think?

**Comment by bennofs** [comment]
@sorawee you're right, closing.
