### ISSUE TITLE
How do I get fancy VSCode like auto-completion for Python?

### ISSUE THREAD

**Issue by dangom** [syl20bnr/spacemacs#11228]
I was reading through a slideshow presentation that criticizes Jupyter Notebooks, and the author has a slide showing [VSCode auto-completion for Python](https://docs.google.com/presentation/d/1n2RlMdmv1p25Xy5thJUhkKGvjtV-dkAIsUXP-AL4ffI/preview#slide=id.g3a428e2eb8_0_193).

I would like to have the same for Emacs. Is this possible? If yes, what do I have to do to get it working, and are there any caveats?

My config has the python and autocompletion layer and no further tweaks to those. I'm on develop branch but haven't pulled new changes since the end of June, i.e., since the removal of `exec-path-from-shell`. On MacOS, if that's relevant.

**Comment by ljupchokotev** [comment]
To get closer to VSCode-like features for Python, you should check the LSP backend for the Python layer.

**Comment by Compro-Prasad** [comment]
For me anaconda-mode is more superior to Python lsp. lsp-mode does support eldoc. The python backend/frontend might not be properly written.
