### ISSUE TITLE
PHP function descrptions not loaded

### ISSUE THREAD

**Issue by TensorTom** [syl20bnr/spacemacs#11237]
I'm new to spacemacs. I'm sure this is easily resolvable but idk what it is yet: https://i.imgur.com/9jLoMAT.png

**Comment by Compro-Prasad** [comment]
Please dig in to help us understand your issue. Like Emacs version, spacemacs branch, commit id if its develop. Link your dotfile(`.spacemacs`). And much more.

**Comment by phenix-factory** [comment]
Just hit M+x and ask for the command php-extras-generate-eldoc.
M should be your Alt key.
