### ISSUE TITLE
Spacemacs `Dired` Rename or Copy error: Rename or Copy fails with error `apply: Wrong number of arguments: (8 . 8), 10`

### ISSUE THREAD

**Issue by 00krishna** [syl20bnr/spacemacs#11230]
#### Description :octocat:
When using `dired` mode in spacemacs 0.200.13.x on emacs 26.1 I have inconsistent
behavior with the Rename and Copy operations. I can mark a couple of files
and then click `R` for rename. The first time this will usually work and I get
the prompt for the directory in which to move the files. The second time I try
and do this, I get an error message 

`apply: Wrong number of arguments: (8 . 8), 10`

There does not seem to be anything else wrong, but it makes `dired` unusable. 

NOTE: 
I did try running `emacs -Q` and then executing the same sequence of commands in the Reproduction section. With the vanilla config, the commands work just fine. So something in the Spacemacs config is causing this though it is not clear whether that is a conflict with an existing package or something else. 

#### Reproduction guide :beetle:
- Start Emacs
- Open `dired` mode with `SPC f j`
- navigate to desired directory
- mark two files with clicking on `m` 
- click `R` to do a rename for the first time, and move the files to a new directory
- mark two more files by clicking `m`
- click `R` to rename the files again, and experience the error.

*Observed behaviour:* :eyes: :broken_heart:
I just observe the error message `apply: Wrong number of arguments: (8 . 8), 10`. 
The files are not renamed or moved. 

*Expected behaviour:* :heart: :smile:
Emacs should prompt for the new directory, and then move the files to that new directory.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(graphviz helm auto-completion better-defaults emacs-lisp git latex bibtex markdown org
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          spell-checking syntax-checking version-control asciidoc themes-megapack shell plantuml python rust go search-engine typescript gtags html ess ipython-notebook javascript pandoc sql erc)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
This backtrace was generated when trying to move a pdf file named `jarrett-xxx.pdf`.

```
Debugger entered--Lisp error: (wrong-number-of-arguments (8 . 8) 10)
  helm-read-file-name-handler-1("Rename jarrett-iccv-09.pdf to: " read-file-name-internal file-exists-p nil "~/Downloads/" file-name-history nil nil "dired-do-rename" "*helm-mode-dired-do-rename*")
  apply(helm-read-file-name-handler-1 ("Rename jarrett-iccv-09.pdf to: " read-file-name-internal file-exists-p nil "~/Downloads/" file-name-history nil nil "dired-do-rename" "*helm-mode-dired-do-rename*"))
  helm--completing-read-default("Rename jarrett-iccv-09.pdf to: " read-file-name-internal file-exists-p nil "~/Downloads/" file-name-history nil nil)
  apply(helm--completing-read-default ("Rename jarrett-iccv-09.pdf to: " read-file-name-internal file-exists-p nil "~/Downloads/" file-name-history nil nil))
  #f(advice-wrapper :override completing-read-default helm--completing-read-default)("Rename jarrett-iccv-09.pdf to: " read-file-name-internal file-exists-p nil "~/Downloads/" file-name-history nil nil)
  completing-read("Rename jarrett-iccv-09.pdf to: " read-file-name-internal file-exists-p nil "~/Downloads/" file-name-history nil)
  read-file-name-default("Rename jarrett-iccv-09.pdf to: " "/home/krishnab/Downloads/" nil nil nil nil)
  read-file-name("Rename jarrett-iccv-09.pdf to: " "/home/krishnab/Downloads/" nil nil nil nil)
  ido-read-file-name("Rename jarrett-iccv-09.pdf to: " "/home/krishnab/Downloads/" nil nil nil nil)
  apply(ido-read-file-name ("Rename jarrett-iccv-09.pdf to: " "/home/krishnab/Downloads/" nil nil nil nil))
  #f(advice-wrapper :override #f(advice-wrapper :override read-file-name-default helm--generic-read-file-name) ido-read-file-name)("Rename jarrett-iccv-09.pdf to: " "/home/krishnab/Downloads/" nil nil nil nil)
  read-file-name("Rename jarrett-iccv-09.pdf to: " "/home/krishnab/Downloads/" nil)
  apply(read-file-name ("Rename jarrett-iccv-09.pdf to: " "/home/krishnab/Downloads/" nil))
  dired-mark-pop-up(nil move ("jarrett-iccv-09.pdf") read-file-name "Rename jarrett-iccv-09.pdf to: " "/home/krishnab/Downloads/" nil)
  dired-mark-read-file-name("Rename %s to: " "/home/krishnab/Downloads/" move nil ("jarrett-iccv-09.pdf") nil)
  dired-do-create-files(move dired-rename-file "Move" nil t "Rename")
  dired-do-rename(nil)
  funcall-interactively(dired-do-rename nil)
  call-interactively(dired-do-rename nil nil)
  command-execute(dired-do-rename)
```

**Comment by 00krishna** [comment]
This exact issue was reported elsewhere. The same behavior was observed with another user having the experience of the operation working the first time and then failing on subsequent attempt. So this is something that might need to be adjusted in the default config.

https://github.com/emacs-helm/helm/issues/1819

Seems like there is a genuine issue here. There seems to be some incompatibilities between helm and ido mode. These are documented in the helm wiki. 

https://github.com/emacs-helm/helm/wiki#use-helm-mode-and-ido-mode

**Comment by 00krishna** [comment]
So I worked with a person on Stackexchange on this issue, and there does seems to be a genuine helm issue. Unfortunately helm is not going to be actively developed now. The problem seems to be with the `helm-read-file-name-handler-1` function which accepts 8 arguments.

I will copy the info from the StackExchange request as that is probably the most useful. 

https://stackoverflow.com/questions/52052485/emacs-dired-error-when-renaming-file-apply-wrong-number-of-arguments/52067576#52067576

[EXCERPT FROM ANSWER]
At first glance, this looks to me like a bug in the current version of helm.

Installing helm from MELPA, I see that helm-read-file-name-handler-1 accepts 8 arguments:

    (helm-read-file-name-handler-1 PROMPT DIR DEFAULT-FILENAME MUSTMATCH INITIAL PREDICATE NAME BUFFER)

While helm--completing-read-default is guaranteed to call it with 10, as per the stack trace.

helm--completing-read-default looks up dired-do-rename in helm-completing-read-handlers-alist and finds that it is mapped to helm-read-file-name-handler-1. It then recognises the handler as being name-spaced as a helm function and, on that basis, calls it with 2 additional helm-specific arguments.

By default, helm-completing-read-handlers-alist includes:

(dired-do-rename . helm-read-file-name-handler-1)
(dired-do-copy . helm-read-file-name-handler-1)
(dired-do-symlink . helm-read-file-name-handler-1)
(dired-do-relsymlink . helm-read-file-name-handler-1)
(dired-do-hardlink . helm-read-file-name-handler-1))

So this issue affects all of those dired commands.

You could presuambly work around this by removing all of those.

e.g. M-x customize-option RET helm-completing-read-handlers-alist

**Comment by 00krishna** [comment]
Note that it seems like removing the choices listed from the `.spacemacs` custom variables section seemed to fix the problem. Of course this will disable the helm integration, so this is just a workaround for now. 

remove these. 
```
(dired-do-rename . helm-read-file-name-handler-1)
(dired-do-copy . helm-read-file-name-handler-1)
(dired-do-symlink . helm-read-file-name-handler-1)
(dired-do-relsymlink . helm-read-file-name-handler-1)
(dired-do-hardlink . helm-read-file-name-handler-1))
```

**Comment by phil-s** [comment]
https://github.com/emacs-helm/helm/issues/2085 confirms that `ido-everywhere` and `helm` just don't mix, and also says that the workaround of removing those handlers (see previous comment) is going to trigger this bug https://github.com/emacs-helm/helm/issues/1441

It seems that the only real solution is to not use `ido-everywhere` with `helm` is in use, so removing that from your config is evidentially the answer.

**Comment by schell** [comment]
In general I'm seeing "wrong number of arguments" errors for many project operations in both helm and ivy, which makes me think the bug is in spacemacs itself.

**Comment by phil-s** [comment]
@schell, "apply: Wrong number of arguments" is an extremely generic error. Any given instance of that error may be entirely unrelated to any other instance.
