### ISSUE TITLE
Helm text on mode-line

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#11233]
#### Description :octocat:
The text `Helm` is shown on the mode-line after opening a helm buffer.

#### Reproduction guide :beetle:
- Start Emacs
- Open HELM Mini: `SPC b b`

*Observed behaviour:* :eyes: :broken_heart:
`Helm` is shown on the mode-line.

*Expected behaviour:* :heart: :smile:
Since helm is part of the default Spacemacs setup, then it probably doesn't have to take up 4 characters on the mode-line.

#### Possible Cause:
This commit:
Truly lazy load helm based on key bindings https://github.com/syl20bnr/spacemacs/commit/e24be2186adcbf1bafafd3ca2ea4e31d8919c760#diff-fa2afbb00b304a76ad8b127262c68de4R69

commented out the line:
```
(spacemacs|hide-lighter helm-mode)
```
if it's called manually then `Helm` disappears from the mode-line.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ffc1617dd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey helm auto-completion emacs-lisp git markdown neotree version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by d12frosted** [comment]
I can't reproduce it 😿

**Comment by duianto** [comment]
I just tested it in Ubuntu 18.04 (as a vm client in virtualbox with windows 10 as host), and `Helm` also appears on the mode-line after a helm buffer has been opened.

![virtualbox_2018-10-30_11-23-54](https://user-images.githubusercontent.com/13420573/47712490-21e90a00-dc38-11e8-9d24-775032af4b15.png)

But `Helm` doesn't appear anymore after adding `(spacemacs|hide-lighter helm-mode)` to the `:config` section of `helm/init-helm`, as proposed in the PR:
Hide helm modeline indicator text #11518 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f5243bb69)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp multiple-cursors neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by d12frosted** [comment]
Neat. Must be something with my configuration. TBH, I don't use `helm` and `spacemacs-modeline` layers, so I tried to reproduce once I've enabled them. But still...

Welp, FYI I've applied your commit locally. Will play a little bit more with it and push soon (expect tomorrow morning).

**Comment by d12frosted** [comment]
Fix was merged to develop 🎉
