### ISSUE TITLE
Google Translate will not work

### ISSUE THREAD

**Issue by sirherrbatka** [syl20bnr/spacemacs#1123]
Hellow, I noticed that google translate (spc x g t) seems to not work for me, because I'm getting JSON readtable error. Can someone confirm this issue, please? I am dyslectic, non-native speaker so actually i want to check if I'm not writting nonsense.

**Comment by CarlQLange** [comment]
It worked fine for me - what languages are you using? Perhaps there's an issue there :)

**Comment by cheezy64** [comment]
Also worked for me when translating from English to Spanish

**Comment by sirherrbatka** [comment]
Ok, it must be something of my other machine since it seems to work at work. Thanks for cheking guys!
