### ISSUE TITLE
`spacemacs/toggle-whitespaces-globally` is not involutive

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#1124]
Doing `SPC t C-w` twice should revert back to not showing whitespace, but it does not. Also, this function should be called `toggle-whitespace-globally` because "whitespace" is not a countable noun in English.

**Comment by syl20bnr** [comment]
Fixed in develop.
But sometimes it is necessary to revert the current buffer (SPC b R), I don't know why.
