### ISSUE TITLE
Installation error: undo-tree paradox unavailable

### ISSUE THREAD

**Issue by c4dr01d** [syl20bnr/spacemacs#11246]
When I clone the develop branch to install spacemacs, the terminal say: undo-tree and paradox is unavailable, this error let 19 package not install. How can i fix it?

**Comment by Compro-Prasad** [comment]
How many times did you restart spacemacs? Which version of Emacs are using?

**Comment by c4dr01d** [comment]
I tried 10 times, I use Emacs 26.1

**Comment by Compro-Prasad** [comment]
Can you give the list of errors from the messages buffer? Also give the stack trace(if available) using `emacs --debug-init`.

**Comment by c4dr01d** [comment]
Yes,you can close this issue,because my problem is solved

**Comment by Compro-Prasad** [comment]
@c4dr01d You are the owner of this issue so you can close it or the maintainer can. I am not the maintainer.

**Comment by c4dr01d** [comment]
ok,I'll close it now
