### ISSUE TITLE
mismatching parents make my rust workflow freeze for seconds

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#11241]
Say I have `foo<F>` and I delete the last `<` into `foo<F`, then the parents get "highlighted" and my emacs freezes for 5 seconds. The same happens when working with macros and getting mismatching `{` or `(`, etc. What do I need to disable to work around this and why is this enabled by default ?

**Comment by Compro-Prasad** [comment]
Can you write down the steps to reproduce the issue in points like:

1. First do this
2. Then this
3. ...
