### ISSUE TITLE
Unable to set Fira Mono Medium as default font by any method.

### ISSUE THREAD

**Issue by fakheet** [syl20bnr/spacemacs#11250]
#### Description
I am unable to set Fira Mono Medium as a default font. The font works fine in Sublime Text 3 and vim/neovim in terminal. In Spacemacs I tried setting the font in every possible way I am aware of and nothing worked (Source Code Pro works fine though). I think this is either me being blind to an obvious solution, or this could be a bug.

None of the following ways I tried setting it worked:
```elisp
dotspacemacs-default-font '("Fira Mono"
                            :size 14
                            :weight medium
                            :width normal
                            :powerline-scale 1.2)
                           
dotspacemacs-default-font '("Fira Mono Medium"
                            :size 14
                            :weight medium
                            :width normal
                            :powerline-scale 1.2)

dotspacemacs-default-font '("Fira Mono Medium"
                            :size 14
                            :weight medium
                            :width normal
                            :style medium
                            :powerline-scale 1.2)

dotspacemacs-default-font '("Fira Mono Medium"
                            :size 14
                            :powerline-scale 1.2)
```
etc.

I also tried setting the font via `menu-set-font`. It didn't work either. 

No matter what I do, the font is set to Fira Mono Regular and `M-x describe-font RET RET` outputs the following:

```
name (opened by): -CTDB-Fira Mono-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1
       full name: Fira Mono:pixelsize=14:foundry=CTDB:weight=normal:slant=normal:width=normal:spacing=100:scalable=true
       file name: /usr/share/fonts/TTF/FiraMono-Regular.ttf
```

**However**, if I replace all instances of `Medium` by `Bold` and `medium` by `bold`, Spacemacs sets the bold version of the font just fine by any of the above mentioned methods:

```
name (opened by): -CTDB-Fira Mono-bold-normal-normal-*-14-*-*-*-m-0-iso10646-1
       full name: Fira Mono:pixelsize=14:foundry=CTDB:weight=bold:slant=normal:width=normal:spacing=100:scalable=true
       file name: /usr/share/fonts/TTF/FiraMono-Bold.ttf
```
What's also interesting, if I try to do `M-x describe-font RET Fira Mono Medium RET`, I get the entry for the Regular (Bold doesn't have this problem):
```
name (opened by): -CTDB-Fira Mono-normal-normal-normal-*-16-*-*-*-m-0-iso10646-1
       full name: Fira Mono:pixelsize=16:foundry=CTDB:weight=normal:slant=normal:width=normal:spacing=100:scalable=true
       file name: /usr/share/fonts/TTF/FiraMono-Regular.ttf
```
Maybe something prevents Spacemacs from recognizing Medium as Medium?

#### Reproduction guide 
- Set Fira Mono Medium as a default font by any method.
- Start Emacs

*Observed behaviour:*
The font is defaulting to Fira Mono Regular.

*Expected behaviour:*
Fira Mono Medium being set as a default font.

#### System Info
- OS: Arch Linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: `(helm emacs-lisp org)`
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by Compro-Prasad** [comment]
Maybe the font that is normal is same as normal.

**Comment by fakheet** [comment]
@Compro-Prasad if by that you mean that Regular and Medium look the same, then no. For comparison here are Fira Mono Regular and Medium respectively in Sublime Text 3
![screenshot_2018-09-01_18-04-36](https://user-images.githubusercontent.com/19792485/44945797-b6d6af00-ae11-11e8-9897-8e0d0c29a03e.png)
![screenshot_2018-09-01_18-05-20](https://user-images.githubusercontent.com/19792485/44945796-b6d6af00-ae11-11e8-9e83-934091ab7f1c.png)

**Comment by Compro-Prasad** [comment]
What I would assume is that they represent the same font with different height and weight.

**Comment by fakheet** [comment]
Well, yes? As I understand it, they are related in the same way as Source Code Pro Regular and Source Code Pro Medium are, yet SCP Reg and SCP Med both work fine.

**Comment by fakheet** [comment]
I was able to set the font by using
```
(set-frame-font "-CTDB-Fira Mono Medium-medium-*-normal-*-14-*-*-*-m-0-iso10646-1"
```
It produces the required result, but when I put it into dotspacemacs/user-config and restart, the font is set for a split second, and then gets reverted to SCP

**Comment by Compro-Prasad** [comment]
Try removing the SCP font from `.spacemacs`.

**Comment by fakheet** [comment]
it's not there

**Comment by carusog** [comment]
@fakheet was you able to sep it up?

**Comment by vityafx** [comment]
I also have the same problem, but with Regular font: I am unable to set regular font, the `medium` one always gets selected.

**Comment by fakheet** [comment]
> @fakheet was you able to sep it up?

Kind of. I switched to Doom Emacs recently, but the issue was there too. I was able to set Medium style by putting this into the init.el: 
`(set-frame-font "-CTDB-Fira Mono Medium-medium-*-medium-*-16-*-*-*-m-0-iso10646-1")` 

**The size of the font is important** because if you set it lower than 16, it would revert to Regular.

**Comment by Compro-Prasad** [comment]
Emacs has/is plans/planning for having font ligatures in core through a popular open source library. Hope it will help in future.

**Comment by LuminousMonkey** [comment]
Try adding :regular to the end of the font name:

dotspacemacs-default-font '("Fira Mono Medium:regular"
                            :size 14
                            :weight medium
                            :width normal
                            :powerline-scale 1.2)
