### ISSUE TITLE
Error in post-command-hook (global-flycheck-mode-check-buffers): (wrong-type-argument listp WARNING:)

### ISSUE THREAD

**Issue by YellowOnion** [syl20bnr/spacemacs#11259]
#### Description
Pressing ":" in evil mode causes: `Error in post-command-hook (global-flycheck-mode-check-buffers): (wrong-type-argument listp WARNING:)` in yaml file.

#### Reproduction guide
- Start Emacs
- open yaml
- press ":"

*Observed behaviour:*
Above error.

*Expected behaviour:*
allows me to input vim like commands.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git markdown haskell html javascript colors csv yaml nixos syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2

**Comment by sio-k** [comment]
Also occurs on:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git markdown org syntax-checking asm c-c++ clojure common-lisp csharp csv d elixir emacs-lisp erlang extra-langs fsharp go graphviz haskell html java javascript latex lua markdown nixos ocaml php purescript python racket ruby rust scala scheme shaders shell-scripts sql typescript yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

Further information:

Anything prompting for input in the minibuffer appears broken. Visit file, M-x, changing buffer. For some reason also the buffer overview.

Alternate reproduction guide:

- start emacs
- open Haskell source file

**Comment by necktwi** [comment]
Bump! For me, it occurs when I create/open a new/empty `.c` or `.cpp` file with emacs.

**Comment by bezoris** [comment]
I receive the same error on a fresh install (25 on Debian)... purged after running into a problem with custom init/agenda setup.

Noticed this starting to happen after Ido was automatically disabled in favor of Helm at startup.

**Comment by YellowOnion** [comment]
I'm so fucking done with spacemacs, atleast make `post-command-hook` safe, seriously everything 3 months something breaks this one hook, and I lose any ability to save or quit my projects.
