### ISSUE TITLE
url links in DOCUMENTATION.org do not open in browser

### ISSUE THREAD

**Issue by stkain** [syl20bnr/spacemacs#11256]
#### Description :octocat:
Following a web url link in spacemacs documentation (which is in org format: DOCUMENTATION.org) does not work
I suppose this will fail for any org mode url link

#### Reproduction guide :beetle:
- Start Emacs
- click on the 'search in spacemacs' link.
- go to the spacemacs documentation DOCUMENTATION.org   .
- from there, go to any link that points to a web page (for example the HELM wiki documentation link)

*Observed behaviour:* :eyes: :broken_heart:
Link does not open in external browser
when hovering over the link, the displayed url is correct, so it is not a problem with the DOCUMENTATION.org file
"https://github.com/emacs-helm/helm/wiki"

I debugged into the elisp files:

the function 'spacemacs//space-doc-open

is called with the path:

"//github.com/emacs-helm/helm/wiki"

notice the double slash!

I am not an org mode implementation expert.
In a function above this call in org-territory, the context element
is retrieved and has already the raw url split into a type "https"
and a path "//github.com/emacs-helm/helm/wiki"

the function 'spacemacs//space-doc-open
in spacemacs land 
then concatenates "https://" to the path and calls browse-url like so:

(browse-url (concat "https://" path))

This results in handing "https:////github.com/emacs-helm/helm/wiki"
over to the browser

I made a temporary fix for myself by removing the superfluous "//"
from the beginning of the path. This is a very ugly hack, of course, but at least
for the time being it is working. I did not dare debug into the org functionality which
seems to create some kind of parse tree for the org-file.

I do not know what the api contract is, but my gut feeling tells me,
that "org" should not split the url into a type "https" and a
disfunctional path "//........". the "//" in the path should go.

on the other hand, I find it weird, that any link passed to spacemacs//space-doc-open
gets blessed with "https://". What if you want to point to another protocol like ftp etc... ?

My current local workaround:
```
diff --git a/layers/+spacemacs/spacemacs-org/local/space-doc/space-doc.el b/layers/+spacemacs/spacemacs-org/local/space-doc/space-doc.el
index bbb9f85b7..423415bc3 100644
--- a/layers/+spacemacs/spacemacs-org/local/space-doc/space-doc.el
+++ b/layers/+spacemacs/spacemacs-org/local/space-doc/space-doc.el
@@ -434,7 +434,9 @@ Open all other links with `browse-url'."
                                  (or (match-string 2 path)
                                      "^")
                                  'subtree)
-      (browse-url (concat "https://" path)))))
+      (progn
+        (setq path (replace-regexp-in-string "^//" "" path))
+        (browse-url (concat "https://" path))))))
 
 (defun spacemacs//space-doc-find-regions-by-text-property
     (property value &optional start end)

```

*Expected behaviour:* :heart: :smile:
link does open in external browser

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp markdown org spell-checking pdf-tools python)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by Miciah** [comment]
This looks like the same issue as #10621, which has been fixed in develop.

**Comment by stkain** [comment]
Thanks! I upgraded to develop.
