### ISSUE TITLE
how do I disable the yasnippets when do happie-expend

### ISSUE THREAD

**Issue by lawrsp** [syl20bnr/spacemacs#11260]
It is vey annoy to do with expend when comes out the snippets, 

e.g:

1. write a variable called `column`
2. type `co` and want expand to `column`
but it always give me the comments snippets 

I want to  bind `C-p` without yasnippets, and bind `M-/` only  for snippets
how do I get this ?

**Comment by OkIdeal0** [comment]
Try setting
```
(setq hippie-expand-try-functions-list 
  (remove 'yas-hippie-try-expand hippie-expand-try-functions-list))
```
in your `user-config`.

**Comment by lawrsp** [comment]
@OkIdeal0 thanks , this is my setting:
```elisp
(with-eval-after-load 'yasnippet
    (setq hippie-expand-try-functions-list 
          (remove 'yas-hippie-try-expand hippie-expand-try-functions-list))
    (define-key yas-minor-mode-map (kbd "M-/") 'yas-expand))
```
