### ISSUE TITLE
lsp: use lsp as javascript backend, the error indicator disappears

### ISSUE THREAD

**Issue by lawrsp** [syl20bnr/spacemacs#11265]
my settings are: 

```elisp
 (lsp :variables
          lsp-ui-doc-enable	nil
          lsp-ui-sideline-enable nil)
 (javascript :variables
                 node-add-modules-path t
                 javascript-backend 'lsp
                 javascript-fmt-tool 'prettier)
```
when I use tern, there is a short underline at the first character of the error point 
after change to lsp, the buffer is always clean even there are errors

update:
not all errors clean
the syntax errors still have notations
but some errors not:
1.  imported but not used
2. variable used but not declared

**Comment by sei40kr** [comment]
I think those errors made by ESLint, and lsp selects the linter in the language server and disable other linters (you can check `SPC e v`).

Once I configured my `.spacemacs` to prevent lsp from selecting a checker, but I can't remember how to do that.

**Comment by lawrsp** [comment]
@sei40kr 
thank you for your info, I found disable ` lsp-ui-flycheck` can make it:
``` emacs-lisp
(lsp :variables
     lsp-ui-flycheck-enable nil)

```
