### ISSUE TITLE
ido and Helm co-existing?

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#1126]
It seems strange to me that Spacemacs provides both Helm and ido completion for various commands (find-file is the main one, I've encountered a few others that I can't recall at the moment).  Are there users who actively choose between using ido sometimes and Helm other times?  Providing both unnecessarily complicates Spacemacs's user interface with two different kinds of completion.

I feel like Spacemacs should provide Helm only, with ido as an optional layer for people that prefer it.

**Comment by syl20bnr** [comment]
`ido` is quicker to navigate in a file tree, essentially because it remembers the last visited paths. Can helm do this ?

**Comment by CestDiego** [comment]
you can always do fuzzy search..and helm can do recentf too... Helm would be ideal if it had the same functionality from ido with C-h and C-l (to go up or down a directory)

**Comment by tuhdo** [comment]
You can go up with `C-l` and go down with `C-j` (unfortunately this is shadowed by Evil) or execute persistent action (using `C-z`, but I think it should be switched to `TAB`)..

**Comment by darkfeline** [comment]
@syl20bnr I'm not sure what you are talking about, but I will take a closer look at ido.  My point is that having two completion interfaces is confusing for the user, although it's not a problem for those of us familiar with ido and Helm and can tell what's going on.

@tuhdo I also support swapping `TAB` and `C-z` in Helm.  Execute persistent action, which is bound to `C-z` by default, is extremely useful; in `helm-find-files`, it completes the current file or directory, which is essentially the same as going down/into a directory.  The action list, which is bound to `TAB` by default, is not used often at all.  Should that go into a new issue?

**Comment by tuhdo** [comment]
Helm does not offer recent files because it wants to keep the same output appears as you use `ls` command. However, it does have different feature to make up for it. One of that is navigating to arbitrary directory and insert the path into current buffer with `C-c i`. For example, you have path `~/.emacs.d/spacemacs` in your buffer, but want to change the path to something else deeper. Than you can navigate to that directory, for example `~/.emacs.d/spacemacs/private/my-layer/` and press `C-c i` to turn `~/.emacs.d/spacemacs` into `~/.emacs.d/spacemacs/private/my-layer`. Helm can also open file in other window *horizontally* (side by side), while current Ido in Spacemacs can only open vertically which is quite useless.

**Comment by darkfeline** [comment]
@syl20bnr I'm not sure what you are talking about even after using `ido` for a bit.  Are you talking about keeping a history of previously found files (`C-S-j`, `C-S-k` in `ido`)? Because `helm` has that (`C-c h`).  Are you talking about `ido` starting with the current file's directory as the search string?  `helm` has that too.  Are you talking about recently edited files?  `helm` has that too, although it is in `helm-mini`, not `helm-find-files`.

**Comment by syl20bnr** [comment]
`SPC f f` now uses helm.

**Comment by darkfeline** [comment]
Thanks, that's the biggest offender.

The final change is to disable ido mode (`(ido-mode -1)`) and enable helm mode so that all completion uses helm mode.

In the interest of full disclosure, I prefer helm mode and I'm sure people who prefer ido mode wouldn't like such a change, but I think it is important to maintain a consistent interface.  Spacemacs should either be all helm or all ido, but NOT both.  If a new Spacemacs user who has grown familiar with helm's interface all of a sudden is presented with ido's interface for completing, for example, dired, that can be disorientating.

**Comment by pennersr** [comment]
I think this issue is incorrectly marked as fixed. I have `develop` checkout out and `C-x d` is still bound to `ido-dired`. 

FWIW, I agree with @darkfeline here, I have attempted to switch to Spacemacs a few times now, and having to bump into `ido` here and there is a major turn off...

**Comment by pennersr** [comment]
Same goes for `C-c p d`. This should be the default:

    (setq projectile-completion-system 'helm)
    (helm-projectile-on)

**Comment by dschrempf** [comment]
I also repeatedly bump into `ido` buffers and find this confusing.
I know, I should not use these bindings, but coming from a normal Emacs I find myself automatically doing so:

`C-x C-w` is bound to `ido-write-file`
`C-x k` is bound to `ido-kill-buffer` (this is especially confusing)

**Comment by jorgemorais** [comment]
Also C-x C-v is bound to ido-find-alternate-file.  Why does C-x C-f use helm while C-x 4 f, C-x 5 f and C-x C-v use ido?  All four of these commands are used to find files, in only slightly different ways.
