### ISSUE TITLE
Switch main menu back?

### ISSUE THREAD

**Issue by ljgww** [syl20bnr/spacemacs#11269]
This is not bug, it is cry for help. I have emacs 25.3.1 on Ubuntu installed.

When spacemacs loads, at the very beginning of loading the application emacs application menu at the top shows and then gets removed in the process.

I have looked everywhere how to configure menu back. But I cannot find it.

Can main menu somehow be put back to window, please?

-----------------
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

**Comment by OkIdeal0** [comment]
`SPC SPC menu-bar-mode` activates the menu bar dynamically. To enable it at startup, put 
```
  (menu-bar-mode t)
```
in your `dotspacemacs/user-config`.

**Comment by robbyoconnor** [comment]
I urge you to learn how to work without it

**Comment by robbyoconnor** [comment]
`SPC T m` allows you to toggle it.

**Comment by robbyoconnor** [comment]
http://develop.spacemacs.org/doc/DOCUMENTATION.html#gui-toggles

**Comment by ljgww** [comment]
1. 

"SPC T m allows you to toggle it."

SPC does not work for me. Someone suggested to use Ctrl-X instead
with C-x T m nothing happens, actually it does. m gets typed in the buffer instead of showing the menu. I have found this already in the documentation.

2.

will try config - currently this looks as most promising path

3.

"I urge you to learn how to work without it" - understood that but in current state of afairs - it does not help and menu would help a lot (if it is working)

**Comment by ljgww** [comment]
(menu-bar-mode t)

at the end of ~/.spacemacs - WORKED! Thank you!

Thank you for the menu! - at least I can do some basic operations from there until I figure out all this strange keyboard-fu!

**Comment by robbyoconnor** [comment]
If you are using the emacs editing style, then it's `M-m` for the leader key.

**Comment by robbyoconnor** [comment]
I recommend you [read the docs](http://develop.spacemacs.org/doc/DOCUMENTATION.html)

**Comment by bmag** [comment]
I see the issue was resolved, so I'm closing it.

**Comment by ljgww** [comment]
@robbyoconnor thank you for pointing out - I did figure out that fact, in the meantime, on the way but not from recommended document, since that particular one is pretty unfriendly to emacs beginners.

Obvious intention of mentioned document is to give essential information to ones who would like, thru spacemacs, take on alternative Emacs setup. Essentially, it gives impression that it is written for ones who already know Emacs from before.
