### ISSUE TITLE
shell-script mode comment bug

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#11261]
#### Description :octocat:
![image](https://user-images.githubusercontent.com/36224762/44988395-c8e65800-af9f-11e8-8913-f1a8f4b0f81e.png)
As you see, `(#b)` is mistaken for a comment, causing a lot of problems.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. nil)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv sql asciidoc yaml fsharp windows-scripts javascript gpu epub xkcd spotify twitter search-engine vimscript
     (elfeed :variables rmh-elfeed-org-files
             (list "~/.emacs.d/private/feeds/elfeed1.org"))
     (rust :variables rust-format-on-save t)
     (haskell :variables haskell-enable-hindent t)
     semantic lsp
     (c-c++ :variables c-c++-enable-clang-support t)
     html
     (python :variables python-backend 'anaconda)
     chrome
     (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
     autohotkey kotlin helm
     (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
     emacs-lisp
     (ibuffer :variables ibuffer-group-buffers-by 'modes)
     coq emoji
     (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
     git markdown org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking
     (syntax-checking :variables syntax-checking-enable-tooltips t)
     (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
     version-control osx scheme
     (clojure :variables clojure-enable-fancify-symbols t))
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Miciah** [comment]
I can reproduce the issue using `emacs -Q` on GNU Emacs 27.0.50 (commit ecd7a9407711ebe24d7e07d4402a2d66754ee693).

1. Open an empty buffer.
2. Enter a shebang line into the buffer: `#!/bin/zsh`.
3. Start Shell Script Mode: <kbd>M-x</kbd> `shell-script-mode` <kbd>RET</kbd>.
4. Enter some code with a globbing flag: `x=${a/(#b)(c)/$match[1]}`.

The globbing flag (starting with the `#`) and everything that follows it is highlighted as a comment.

This issue should be reported upstream.

**Comment by NightMachinary** [comment]
Can you report it upstreams? I don’t have a good experience reporting bugs
to them.

**Comment by Miciah** [comment]
The issue has been fixed upstream (see https://debbugs.gnu.org/cgi/bugreport.cgi?bug=19455).

**Comment by duianto** [comment]
Thanks for the update.
