### ISSUE TITLE
emacsclient -c -a ""

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#11263]
when I run `emacsclient -c -a ""` the home buffer is broken, only the links on top of the page are shown. Also `SPC SPC` does not work. When  I run `emacs` everything works as expected.

I am on linux, emacs 26.1.1 and spacemacs develop

**Comment by gdkrmr** [comment]
Am I the only one observing this behaviour? This happens to me on 3 machines, maybe they all have the same broken config.

**Comment by gdkrmr** [comment]
There are no obvious errors in the message buffer. I will probably have to strip my config file and add stuff bit by bit. The whole thing is also not consistent across machines, the config files on the different machines should only differ in details.

**Comment by smile13241324** [comment]
I have tried that out myself now, when I start `emacsclient -c -a ""` I am getting all fonts rendered with 400% size, which is pretty strange. However `SPC SPC` is still working like a charm.

I am on Manjaro Linux and using emacs 26.1 on develop.

So chances are pretty high that there is something in your config which is misbehaving.

**Comment by gdkrmr** [comment]
Thanks for taking a look at this, i guess that it must be something at startup that doesn't work without a frame. If I find the cause, I will post it here.

**Comment by gdkrmr** [comment]
On one machine the problem occurred both with `emacs` and `emacsclient -c -a ""`, the problem disappeared in both after creating the directory and file `~/org/agenda.org`. I have the following in my `spacemacs/user-config`:

```elisp
  (with-eval-after-load 'org-agenda
      (setq-default
       org-directory            "~/org"
       org-default-notes-file   "~/org/capture.org"
       org-agenda-files       '("~/org/agenda.org")
       org-capture-templates
       '(("t" "Tasks")
         ("tg" "General" entry (file+headline "" "Tasks")
          "* TODO %?\n%i\n%U"
          :empty-lines 1)
         ("tl" "Location" entry (file+headline "" "Tasks")
          "* TODO %?\n%i\n%U\n%a"
          :empty-lines 1)
         ("n" "Notes")
         ("ng" "General" entry (file+headline "" "Notes")
          "* %?\n%i\n%U"
          :empty-lines 1)
         ("nl" "Location" entry (file+headline "" "Notes")
          "* %?\n%i\n%U\n%a"
          :empty-lines 1))))
```

I will check the other machines and report here!

**Comment by gdkrmr** [comment]
any idea how I can debug this?

**Comment by smile13241324** [comment]
@gdkrmr can you tell which issue you are referring too? Is your home buffer still broken? Or is `SPC SPC` not working?

For the keybinding issue it is surely an issue in your dotfile. Before you mentioned missing files from your org config, this is most likely the reason for the issue as the loading process of spacemacs is abnormally terminated when an error is raised in your `user-config` which may result in `undefined behaviour`.

For the changed fonts I have no idea where this comes from may be someone from the core team can help with this.

**Comment by gdkrmr** [comment]
I am referring to both issues
There are no errors in the `*Message*` buffer, I guess the startup process gets interrupted at a certain point if there is no frame but I have very limited knowledge on the startup process of spacemacs and therefore a  hard time debugging it.

**Comment by smile13241324** [comment]
Ok my best guess, not knowing your config, is to advice you to deactivate all custom content in your user config and make sure that spacemacs then starts up correctly. If this works. I would reactivate your config line by line till something breaks.

Checking the org snippet you have posted it looks a bit odd to me, especially as you only load it after `org-agenda` is loaded. `Org layer` requires to load configuration when `org` is loaded to avoid clashes with alternative org versions loaded from `elpa`. This could very likely create problems as you have reported.

For reference here is my config:
``` elisp 
(with-eval-after-load 'org
    (setq org-agenda-files (quote ("~/Documents/GTD/CalendarActionList.org" "~/Documents/GTD/NextActionList.org" "~/Documents/GTD/ProjectList.org")))
    (setq org-refile-targets (quote (("~/Documents/GTD/CalendarActionList.org" :maxlevel . 1)
                                     ("~/Documents/GTD/NextActionList.org" :maxlevel . 1)
                                     ("~/Documents/GTD/ProjectList.org" :maxlevel . 1)
                                     ("~/Documents/GTD/Reference.org" :maxlevel . 1)
                                     ("~/Documents/GTD/SomedayMaybe.org" :maxlevel . 1)
                                     ("~/Documents/GTD/WaitingFor.org" :maxlevel . 1))))
    (setq org-enforce-todo-dependencies t)
    (setq org-enforce-todo-checkbox-dependencies t)
    (setq org-brain-path "~/Documents/GTD")
    (setq org-default-notes-file "~/Documents/GTD/Inbox.org")
    (setq org-archive-location "~/Documents/GTD/Reference.org::* Archived from %s")
    (setq spaceline-org-clock-p t)
    (setq org-capture-templates
          '(("i" "Input" entry (file "")
             "* %? %i")
            ("r" "General reference" entry (file+headline "~/Documents/GTD/Reference.org" "General")
             "* %? %i")))
    (setq org-agenda-skip-scheduled-if-done t)
    (setq org-agenda-skip-deadline-if-done t)
    (setq org-agenda-skip-timestamp-if-done t)
    (setq org-agenda-todo-list-sublevels t)
    ;; (setq org-agenda-todo-ignore-with-date t)
    ;; (setq org-agenda-todo-ignore-deadlines 'all)
    (setq org-agenda-todo-ignore-scheduled 'all)
    (setq org-agenda-todo-ignore-timestamp 'all)
    (setq org-hierarchical-todo-statistics nil)
    (setq org-startup-align-all-tables t)
    (setq org-agenda-restore-windows-after-quit nil)
    (setq org-use-property-inheritance nil)
    (setq org-agenda-sorting-strategy (quote ((agenda habit-down time-up priority-down category-keep)
                                              (todo tag-up priority-down todo-state-up category-keep)
                                              (tags priority-down category-keep)
                                              (search category-keep)))))
```

**Comment by gdkrmr** [comment]
update: 
- `SPC SPC` not working was because `org-agenda` files that didn't exist on disk.
- If I start emacs with `emacsclient -c -a ""`, home buffer is not shown but I can make it appear with `SPC b h"
- The theme is broken.
