### ISSUE TITLE
Creates another workspace on macOs 10.13.6 when using lsp suggestions

### ISSUE THREAD

**Issue by osenvosem** [syl20bnr/spacemacs#11267]
#### Description :octocat:
When using lsp suggestions in fullscreen the workspace duplicates on macOs; the initial screen is black and the editor frame moves to a new workspace.

![screen shot 2018-09-04 at 20 56 39](https://user-images.githubusercontent.com/6762673/45049121-5603dc80-b086-11e8-8716-511687696989.jpg)

#### Reproduction guide :beetle:
- Start Emacs
- Start editing js/jsx file with lsp suggestions

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a226c78ea)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion git neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term)
      syntax-checking version-control
      (lsp :variables lsp-ui-remap-xref-keybindings t lsp-ui-doc-enable t lsp-ui-doc-include-signature nil lsp-ui-sideline-enable nil lsp-ui-sideline-show-symbol nil)
      emacs-lisp markdown
      (javascript :variables js2-basic-offset 2 js-indent-level 2 javascript-fmt-tool 'prettier javascript-backend 'lsp)
      react ruby)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by syl20bnr** [comment]
If it happens with emacs vanilla we should report it upstream.

**Comment by bittopaz** [comment]
This is also happen on my laptop

**Comment by codesuki** [comment]
> If it happens with emacs vanilla we should report it upstream.
Happens to me, too when enabling lsp-ui. I don't have spacemacs.

**Comment by nixmaniack** [comment]
Still an issue but should be reported upstream.

**Comment by codesuki** [comment]
Just found it, putting it here for reference: https://github.com/emacs-lsp/lsp-ui/issues/299
