### ISSUE TITLE
Weird characters in status line

### ISSUE THREAD

**Issue by mahalex** [syl20bnr/spacemacs#11264]
After fresh installation of Spacemacs (following the instructions in README) I see some weird characters in the status line next to "Spacemacs buffer" text.  Is this the intended behaviour? I have no idea.
![image](https://user-images.githubusercontent.com/19844519/45028418-38fae980-b045-11e8-9b5b-73045e0862ac.png)

I have Ubuntu Linux in WSL, Emacs 25.3.2.
I didn't use the suggested "open a new issue from within in Spacemacs" way, because it doesn't work: the first line of the buffer says "`C-c C-c` TO SUBMIT", but pressing C-c C-c just displays "C-c C-c is undefined" in the minibuffer.

**Comment by ljupchokotev** [comment]
@mahalex check https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#mode-line. You need to install the powerline patched fonts or disable the unicode symbols by changing `dotspacemacs-mode-line-unicode-symbols` in your `.spacemacs` to `nil`.

**Comment by mahalex** [comment]
Thanks for the tip! The documentation you link to says "Users who run Emacs in terminal mode may need to install the Powerline patched fonts", and I don't run Emacs in terminal mode; I use Xming X server. Nevertheless, I installed the powerline patched fonts (sudo apt-get install fonts-powerline), and it didn't help.

**Comment by mahalex** [comment]
@Alexander-Miller that's what I thought as well. It would be nice to have an example of such a font; I guess Source Code Pro that is recommended in README (although it's marked as _optional_) is not one of them.

**Comment by ljupchokotev** [comment]
@mahalex @Alexander-Miller is right. Here is an issue that might help you https://github.com/syl20bnr/spacemacs/issues/4489.

**Comment by Alexander-Miller** [comment]
describe-char gives me `xft:-MUTT-MUTT ClearlyU Wide-normal-normal-normal-*-17-*-*-*-*-123-iso10646-1`, whatever font that is.

**Comment by mahalex** [comment]
@ljupchokotev The recommendation in #4489 was to install ttf-symbola; I did that and now my status line looks like this:
![image](https://user-images.githubusercontent.com/19844519/45076834-c42eba80-b0eb-11e8-83d4-e2cd10fa9643.png)
I suppose that's the intended result, so my issue is resolved. I wish ttf-symbola (or a similar font) was listed as an install requirement in README, so that future generations of users wouldn't have to scroll over thousands of issues in search for answers.

**Comment by ljupchokotev** [comment]
@mahalex A PR would be welcome to add more information to the documentation, if you want to do it.

**Comment by gchamon** [comment]
It would also be great to have this package mentioned in arch linux documentation here: https://wiki.archlinux.org/index.php/Spacemacs#Install_Adobe_Source_Pro_fonts_.28optional.29

**Comment by abhi18av** [comment]
In my case, I just had to change the styling from `doom` to `spacemacs` version. I did this after trying out every single thing mentioned above :)

**Comment by RockyRoad29** [comment]
I may not want to install unfree stuff for the sake of an icon I barely use.

_ttf_symbola_ is not in standard repositories anymore in arch/manjaro (as for "Source Pro", the user needs to install an unsupported package from [AUR](https://aur.archlinux.org/packages/ttf-symbola) .
Those icons appear to be set in various spacemacs layers with
`spacemacs|diminish` .

Refering again to #4489 and #1012 , the ggtags mode issue comes from the line in
file:~/.emacs.d/layers/+tags/gtags/packages.el :
```elisp
      (spacemacs|diminish ggtags-mode " 🅶" " [g]"))))
```
 where the character used (press [SPC hdc] over it in spacemacs to find more) is
  - `0x1F176`: "NEGATIVE SQUARED LATIN CAPITAL LETTER G"

Why not replacing that which something more accessible ?
like
  - `0x24BC` : "CIRCLED LATIN CAPITAL LETTER G" : Ⓖ
  - `0x0193` : "LATIN CAPITAL LETTER G WITH HOOK" : Ɠ
  - `0x029B` : "LATIN LETTER SMALL CAPITAL G WITH HOOK" : ʛ
 evaluating
 ```elisp
(spacemacs|diminish ggtags-mode " ʛ" " [g]")
```
does the job for me.
As a bonus, it returns the list of currently defined icons.
It helps to see conflicts or problematic settings.

mode                   |icon | text
-----------------------|-----|------
purpose-mode           | nil | nil
ggtags-mode            | ʛ   | [g]
company-mode           | ⓐ   | a
flycheck-mode          | ⓢ   | s
smartparens-mode       | ⓟ   | p
yas-minor-mode         | ⓨ   | y
orgtbl-mode            | nil | nil
visual-line-mode       | Ⓛ   | L
projectile-rails-mode  | ⇋   | RoR
nameless-mode          | 🅽   | [n]
livid-mode             | 🅻   | [l]
importmagic-mode       | ⓘ   | [i]
flyspell-mode          | Ⓢ   | S
evil-cleverparens-mode | 🆂   | [s]
editorconfig-mode      | nil | nil
hybrid-mode            | Ⓔh  | Eh
holy-mode              | Ⓔe  | Ee
which-key-mode         | Ⓚ   | K
auto-fill-function     | Ⓕ   | F

For now I'm going to put that in my _dotfile_ .
I'm not sure yet where would be the best spot, so I leave recommendations to the
spacemacs team .
![Screenshot_2020-01-29_13-54-01](https://user-images.githubusercontent.com/964674/73358440-e1df5f80-429e-11ea-9c3c-302f16503564.png)

**Comment by evorion** [comment]
Under Debian installing fonts-symbola did it for me.

`sudo apt install fonts-symbola`

**Comment by michael-stokley-tractmanager** [comment]
Running `M-x all-the-fonts-install-fonts` resolved this for me.
