### ISSUE TITLE
Supports italic

### ISSUE THREAD

**Issue by denniscual** [syl20bnr/spacemacs#11276]
Great editor! I wonder how spacemac supports the italic in comments and keywords and
how to use it. Thanks.

**Comment by Compro-Prasad** [comment]
@denniscual That is theming and font feature. You can look into `/core/libs/spacemacs-theme/spacemacs-common.el`. Or you can use `M-x customize-face` to change the font of a specific text type. This issue can be closed as this isn't an issue itself. Head to https://gitter.im/syl20bnr/spacemacs for these kind of issues or questions.

**Comment by denniscual** [comment]
@Compro-Prasad thanks for the response!
