### ISSUE TITLE
can't install it

### ISSUE THREAD

**Issue by girvain** [syl20bnr/spacemacs#11273]
Warning (initialization): An error occurred while loading ‘/Users/gavinross/.emacs.d/init.el’:

File is missing: Cannot open load file, No such file or directory, evil

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

Found 18 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: adaptive-wrap@spacemacs-editing-visual... [1/18]
Package adaptive-wrap is unavailable. Is the package name misspelled?
--> installing package: evil@spacemacs-bootstrap... [2/18]
Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil (error: (file-error https://melpa.org/packages/goto-chg-20180105.1833.el Bad Request))
--> installing package: evil-anzu@spacemacs-evil... [3/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-anzu (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-args@spacemacs-evil... [4/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-args (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-ediff@spacemacs-evil... [5/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-ediff (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-escape@spacemacs-base... [6/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-escape (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-exchange@spacemacs-evil... [7/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-exchange (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-iedit-state@spacemacs-evil... [8/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-iedit-state (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-indent-plus@spacemacs-evil... [9/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-indent-plus (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-lisp-state@spacemacs-evil... [10/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-lisp-state (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-matchit@spacemacs-evil... [11/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-matchit (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-mc@spacemacs-evil... [12/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-mc (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-surround@spacemacs-evil... [13/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-surround (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-tutor@spacemacs-evil... [14/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-tutor (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-visual-mark-mode@spacemacs-evil... [15/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-visual-mark-mode (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: evil-visualstar@spacemacs-base... [16/18]
Package undo-tree is unavailable. Is the package name misspelled?

Package undo-tree is unavailable. Is the package name misspelled?

An error occurred while installing evil-visualstar (error: (error Package ‘undo-tree-0.6.3’ is unavailable))
--> installing package: paradox@spacemacs-ui... [17/18]
Package spinner is unavailable. Is the package name misspelled?

An error occurred while installing paradox (error: (error Package ‘spinner-1.7.3’ is unavailable))
--> installing package: undo-tree@spacemacs-editing... [18/18]
Package undo-tree is unavailable. Is the package name misspelled?

Found 1 orphan package(s) to delete...
--> deleting goto-chg... [1/1]

=======================================================================
I have tried to install with --insecure and re installed emacs according the the guid for mac and no change in the result. I don't want to have to go through all the packages and delete the ones that don't work as I wanted this to just work out the box.

**Comment by arendorff** [comment]
Same here. Can't get the undo-tree package. Have tried restarting the process 6 times now.

**Comment by bmag** [comment]
For some reason, `elpa.gnu.org` package archive is currently inaccessible. Until it's back up, some packages that Spacemacs relies on can't be installed. Spacemacs will be able to install the missing packages when problems with the archive are resolved, but that's not up to us.

**Comment by lianyoucq** [comment]
That's a bad news, and now hope elpa.gnu.org will be accessible asap.

**Comment by girvain** [comment]
That's cool I just wanted to check it wasn't a weird error with the install process. I'll try it another time and go back to my emacs rig.

**Comment by JonFStr** [comment]
I got a temporary solution for this issue: just add the ip of elpa.gnu.org (`host elpa.gnu.org`) to your etc/hosts file

**Comment by steing** [comment]
on windows i installed from [http://ftp.gnu.org/gnu/emacs/windows/](url)
 instead of the link recommended on the spacemacs readme [https://sourceforge.net/projects/emacsbinw64/files/release/](url) which gave me the error.
 Everything seems to work with emacs26.2

**Comment by duianto** [comment]
@steing, both of your links point to: https://github.com/syl20bnr/spacemacs/issues/url
instead of to the url in the link text.

**Comment by steing** [comment]
that's wierd.  Dont know whats up with that. copy and pasting works... i try again http://ftp.gnu.org/gnu/emacs/windows/

**Comment by duianto** [comment]
Yes those two work.

The issue seems to be that you might have clicked on the `Add a link` button that looks like two loops in a chain. It inserts: `[](url)`

Then the url was inserted between the square brackets like this:
` [http://ftp.gnu.org/gnu/emacs/windows/](url)`

which shows the link like this:
 [http://ftp.gnu.org/gnu/emacs/windows/](url)

But it points to:
https://github.com/syl20bnr/spacemacs/issues/url

Github seems to append the text `url` to the end `domain/owner/repository/issues/url`

The square brackets are intended for the link description, and the parentheses for the url.
`[description](domain.tld/subdomain)`

The `Add to link` button is only needed if you want to select some text and make it into a link, or if you want to type some custom text that will become a link.

Otherwise you can just paste the link a comment (it probably has to include `https://`).

https://github.com/syl20bnr/spacemacs

**Comment by Dietr1ch** [comment]
I've been seen this this week. I was unable to do a clean install on a new machine :(

**Comment by duianto** [comment]
@Dietr1ch 
There's an Emacs issue that seems like it's going to be included in the next version 26.3?

There's a workaround in this issue:
Failed to download 'gnu' archive. Bad request. (Solution included) #12535

**Comment by ckman** [comment]
I was facing the same problem when setting up Spacemacs on OS X.
I tried with several different builds of Emacs found here: https://emacsformacosx.com/builds
With each build there are different missing packages.
**Finally with Emacs-25.1-1-universal.dmg it works!**

**Comment by shroomist** [comment]
I'm running a `develop` branch here on osx.
the only build from https://emacsformacosx.com/builds that worked for me was the latest nightly (as of 2019-05-28), featuring emacs 27.

**Comment by Kevin-Mok** [comment]
[Using a mirror](https://www.reddit.com/r/emacs/comments/cdei4p/failed_to_download_gnu_archive_bad_request/ettq00i?utm_source=share&utm_medium=web2x) is what worked for me.

**Comment by seanjamesking** [comment]
Hey,  for anyone that is still playing around with this I added 
(require 'package)
  (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
  (package-initialize)
 to the top of my init.el file. Then everything was compiled and now spacemacs loads normally from the terminal. Please advise if there is a better way (am using emacs 26.2)

**Comment by narula2000** [comment]
I added these to my init.el
`(require 'package)
(defvar gnu '("gnu" . "https://elpa.gnu.org/packages/"))
(defvar melpa '("melpa" . "https://melpa.org/packages/"))
(defvar melpa-stable '("melpa-stable" . "https://stable.melpa.org/packages/"))
(defvar org-elpa '("org" . "http://orgmode.org/elpa/"))
;; Add marmalade to package repos
(setq package-archives nil)
(add-to-list 'package-archives melpa-stable t)
(add-to-list 'package-archives melpa t)
(add-to-list 'package-archives gnu t)
(add-to-list 'package-archives org-elpa t)
(package-initialize)
(require 'use-package)
(require 'org-bullets)
(add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
(defun packages-install (&rest packages)
  (message "running packages-install")
  (mapc (lambda (package)
          (let ((name (car package))
                (repo (cdr package)))
            (when (not (package-installed-p name))
              (let ((package-archives (list repo)))
                (package-initialize)
                (package-install name)))))
        packages)
  (package-initialize)
`

**Comment by bojohnson02** [comment]
I've just installed Linux Mint 19.3 and installed Emacs 25.2.2 from the repositories. I'm getting the very same error the OP had have tried all the fixes mentioned in this thread. Nothing has worked, however. Has there been anything else done with this issue I could try and get Spacemacs working on my machine?

**Comment by duianto** [comment]
@bojohnson02 If your able to install Emacs 26.3, and clone directly to the Spacemacs `develop` branch, then you should be able to install Spacemacs without any issues. 

If you have an existing Emacs or Spacemacs setup, then back it up first, then make sure that there isn't a `.emacs.d` directory or a `.spacemacs` or `.emacs` file in your home directory and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```

**Comment by amfern** [comment]
@duianto On fresh install of arch. Emacs 26.3, did `rm -rf .spacemacs .spacemacs.env .emacs.d`, and i still get the same error

**Comment by gregorywaynepower** [comment]
Another solution to this problem:

My issue was that I had emacs 25.x on my system and there were some issues with that verision of emacs. Here are the commands below that fixed my issue.

```
sudo apt autoremove emacs emacs23 emacs24 emacs25
sudo add-apt-repository ppa:kelleyk/emacs 
sudo apt-get update
sudo apt install emacs26
```

**Comment by bojohnson02** [comment]
I found installing Emacs 26 through the kelleyk ppa was the trick to getting it working on my system using the normal install route.

**Comment by duianto** [comment]
@gregorywaynepower Nice find.

The kellyk/emacs ppa: https://launchpad.net/~kelleyk/+archive/ubuntu/emacs
updated the expired ELPA signing key after Jaremko (a Spacemacs maintainer) messaged the creator/maintainer about it. The ppa description now says:
>An ELPA signing key expired in 2019-09. The new key, which is valid until 2024, is included Emacs 26.3 and later. I have also backported it to the `emacs25` series. If you have an existing install that is affected by the key expiration, instructions on fetching the new key and inserting it into the keychain are available here: https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html

So that PPA might be the best place to install Emacs from at the moment.

**Comment by ocelotsloth** [comment]
@amfern Were you able to find a solution? I've got the same issue on Arch.

**Comment by ozkc** [comment]
using vpn solved the issue for me

**Comment by well1791** [comment]
This info is quite important
Is there a way to pin this somewhere in the repo/web-page for new comers, so they don't struggle all over the internet with this issue?

**Comment by pradhyu** [comment]
> ```emacs-lisp
> ```emacs-lisp
> (require 'package)
> (defvar gnu '("gnu" . "https://elpa.gnu.org/packages/"))
> (defvar melpa '("melpa" . "https://melpa.org/packages/"))
> (defvar melpa-stable '("melpa-stable" . "https://stable.melpa.org/packages/"))
> (defvar org-elpa '("org" . "http://orgmode.org/elpa/"))
> ;; Add marmalade to package repos
> (setq package-archives nil)
> (add-to-list 'package-archives melpa-stable t)
> (add-to-list 'package-archives melpa t)
> (add-to-list 'package-archives gnu t)
> (add-to-list 'package-archives org-elpa t)
> (package-initialize)
> (require 'use-package)
> (require 'org-bullets)
> (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
> (defun packages-install (&rest packages)
>   (message "running packages-install")
>   (mapc (lambda (package)
>           (let ((name (car package))
>                 (repo (cdr package)))
>             (when (not (package-installed-p name))
>               (let ((package-archives (list repo)))
>                 (package-initialize)
>                 (package-install name)))))
>         packages)
>   (package-initialize)
> ```
> 
> 
> It fixed everything
> ```
Missing ) after packages) in second last line of the patch.

**Comment by duianto** [comment]
@pradhyu Thanks for posting about the missing close parenthesis 👍
I fixed it in the original comment above ☝️ https://github.com/syl20bnr/spacemacs/issues/11273#issuecomment-563788312
so that the next person that tries it doesn't run into the same issue.

**Comment by pradhyu** [comment]
tan q @duianto
