### ISSUE TITLE
Git interactive rebase is unusable.

### ISSUE THREAD

**Issue by person808** [syl20bnr/spacemacs#1128]
When attempting to interactively rebase from `magit-log`, I am put into an evilified buffer that I can edit.

**Comment by tuhdo** [comment]
How to reproduce it? When you press `E` to start an interactive rebase in a commit, it gives you an editable buffer, similar to how it is in command line.

**Comment by person808** [comment]
The buffer I'm put in is evilified, I cannot edit it. I tried running `evil-insert-state` but that left some keys with the evilified keybinding (<kbd>q</kbd> exited the buffer in insert mode)

**Comment by tuhdo** [comment]
I don't think you can edit it. Just follows the key bindings listed in the comments, and appropriate actions are taken. i.e. press `e` to change to `edit`, press `s` to `squash`... `C-k` to kill a commit, `M-p` to move up a commit, `M-n` to move down a commit.

**Comment by tuhdo** [comment]
I never tried to edit it so I'm not sure it's editable. Probably it's magit's feature that prevent you accidentally destroy the buffer.

**Comment by person808** [comment]
I did not know that. It looked exactly like how it looks in the command line so I assumed I could to edit it. I'll test it tomorrow and see if it works.

**Comment by syl20bnr** [comment]
Key bindings are available here: https://github.com/syl20bnr/spacemacs/tree/master/contrib/git#interactive-rebase-buffer

To squash a commit, go to the commit line in the action word, press `s` then `C-c C-c`.  The buffer is interactive but not writable, pretty slick.

**Comment by person808** [comment]
Oh ok, my bad.
