### ISSUE TITLE
Feature request: syntax highlighting for MDX files (Markdown + JSX)

### ISSUE THREAD

**Issue by hsribei** [syl20bnr/spacemacs#11288]
https://github.com/mdx-js/mdx/issues/119

**Comment by Gazler** [comment]
Not a full solution, but adding the following to your `dotspacemacs/user-config` will highlight as markdown.

```emacs
(defun dotspacemacs/user-config ()

  (add-to-list 'auto-mode-alist '("\\.mdx\\'" . markdown-mode))
```

**Comment by robbyoconnor** [comment]
https://github.com/syl20bnr/spacemacs/pull/13480

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Add support for mdx files #13480

If someone can confirm that it works on the latest develop branch then we can close this.

**Comment by robbyoconnor** [comment]
@duianto I did test this and it does work. Not optimal but it works

**Comment by duianto** [comment]
Thanks for testing. This can be a first step.

If someone wants to create better syntax highlighting, then this guide might be helpful:
http://ergoemacs.org/emacs/elisp_syntax_coloring.html
