### ISSUE TITLE
How to set cursor at the end of line while going through previous commands in evil-ex

### ISSUE THREAD

**Issue by qhuyduong** [syl20bnr/spacemacs#11286]
# Issue type
- Question

# Environment
Emacs version: 26.1
Operating System: macOS Sierra
Evil version: 
Evil installation type: 
Graphical/Terminal: Terminal

# Reproduction steps
- Start Emacs
- Trigger evil mode by ":"
- Use Up arrow key to go to previous command

# Expected behavior
- Cursor at the end of line
# Actual behavior
- Cursor is always at the beginning of line
# Further notes

**Comment by Miciah** [comment]
This is an upstream issue, and I see you have already reported it upstream: https://github.com/emacs-evil/evil/issues/1086.  This issue should be labeled "Reported upstream".
