### ISSUE TITLE
doom-modeline does not work and breaks Emacs

### ISSUE THREAD

**Issue by mc10** [syl20bnr/spacemacs#11287]
#### Description :octocat:
Enabled doom-modeline after e641e6c6e64f30b0d3b14f0e2f28a09affb0156c. However, doom-modeline fails to start up. Running Emacs on CentOS 7. (Works ok on macOS so I'm not entirely sure what the issue is.)

#### Reproduction guide :beetle:
- Change `dotspacemacs-mode-line-theme` to `'doom`
- Restart Emacs

*Observed behaviour:* :eyes: :broken_heart:
Error message:
```Invalid function: (modeline (doom-modeline key))```

and almost all features of Emacs are broken (e.g. cannot open list of buffers, cannot quit emacs without killing it in a terminal, etc.).

*Expected behaviour:* :heart: :smile:
doom-modeline should work.

**Comment by sdwolfz** [comment]
Does this PR: https://github.com/syl20bnr/spacemacs/pull/11279 fix your problem?

**Comment by mc10** [comment]
Nope, just tried applying the patch and it didn't fix the issue.

**Comment by et2010** [comment]
Try `emacs --debug-init` and post the error.

**Comment by mc10** [comment]
No errors appear; the only message that I see after trying most commands (like `SPC b b` or `SPC f f`) is
```Invalid function: (win (frame-selected-window))```

I'm unable to do some basic things like saving a file or quitting the editor. Also, my modeline flashes red whenever that error message appears.

**Comment by mc10** [comment]
Huh, a recent package update seemed to have properly installed doom-modeline, so closing.
