### ISSUE TITLE
julia-repl command in julia layer not working

### ISSUE THREAD

**Issue by orialb** [syl20bnr/spacemacs#11293]
#### Description :octocat:
julia-repl command in julia layer failing with
"wrong type argument listp key"

#### Reproduction guide :beetle:
- Start Emacs
- open a julia file
- run julia-repl (SPC m r)

*Observed behaviour:* :eyes: :broken_heart:
the function call fails with
"wrong type argument listp key"

*Expected behaviour:* :heart: :smile:
julia REPL opens

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 044237139)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown html python lsp julia helm auto-completion bibtex emacs-lisp git org latex themes-megapack spell-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument listp key)
  #[897 "\302 \203\303W\204	\303U\205H\205\304\305\306\307A\"\"\310\311\312\313	D\2045\2045\205@\314B\314	BEBBE\315BB\262\207" [cl--optimize-speed cl--optimize-safety cl--compiling-file 3 delq nil mapcar #[257 "\300!?\205\211\207" [macroexp-const-p] 3 "\n\n(fn X)"] progn or cl--assertion-failed quote list (nil)] 14 ("/usr/local/Cellar/emacs-plus/25.3/share/emacs/25.3/lisp/emacs-lisp/cl-macs.elc" . 82366)](key "Could not find any key in JULIA-REPL-EXECUTABLE-RECORDS.")
  (assert key "Could not find any key in JULIA-REPL-EXECUTABLE-RECORDS.")
  (let ((key (caar julia-repl-executable-records))) (assert key "Could not find any key in JULIA-REPL-EXECUTABLE-RECORDS.") key)
  julia-repl--default-executable-key()
  (or julia-repl-executable-key (julia-repl--default-executable-key))
  julia-repl--get-executable-key()
  (if --cl-rest-- (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--)))) (julia-repl--get-executable-key))
  (let* ((executable-key (if --cl-rest-- (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--)))) (julia-repl--get-executable-key))) (suffix (if --cl-rest-- (car-safe (prog1 --cl-rest-- (setq --cl-rest-- (cdr --cl-rest--)))) julia-repl-inferior-buffer-name-suffix))) (progn (if --cl-rest-- (signal (quote wrong-number-of-arguments) (list (quote julia-repl--inferior-buffer-name) (+ 2 (length --cl-rest--))))) (let* ((middle (if (eq executable-key (julia-repl--default-executable-key)) "" (format "-%s" executable-key))) (last (cond ((null suffix) "") ((integerp suffix) (format "<%d>" suffix)) ((symbolp suffix) (format "-%s" suffix)) (t (error "Inferior name suffix should be an integer or a symbol"))))) (concat julia-repl-inferior-buffer-name-base middle last))))
  julia-repl--inferior-buffer-name()
  (julia-repl--add-earmuffs (julia-repl--inferior-buffer-name))
  (get-buffer (julia-repl--add-earmuffs (julia-repl--inferior-buffer-name)))
  (and t (get-buffer (julia-repl--add-earmuffs (julia-repl--inferior-buffer-name))))
  (let* ((inferior-buffer (and t (get-buffer (julia-repl--add-earmuffs (julia-repl--inferior-buffer-name)))))) (if inferior-buffer (if (term-check-proc inferior-buffer) (progn inferior-buffer))))
  julia-repl--live-buffer()
  (and t (julia-repl--live-buffer))
  (let* ((inferior-buffer (and t (julia-repl--live-buffer)))) (if inferior-buffer inferior-buffer (julia-repl--start-and-setup (julia-repl--get-executable-key) julia-repl-inferior-buffer-name-suffix)))
  julia-repl-inferior-buffer()
  (switch-to-buffer-other-window (julia-repl-inferior-buffer))
  julia-repl()
  funcall-interactively(julia-repl)
  call-interactively(julia-repl nil nil)
  command-execute(julia-repl)

```

**Comment by orialb** [comment]
As further info I already opened up this issue in the julia-repl package repo (https://github.com/tpapp/julia-repl/issues/38) , but it seems to be a spacemacs specific issue.

Some debugging led me to the following conclusions:

The error was caused by the following function in julia-repl.el:

(defun julia-repl--default-executable-key ()
  "Return the default executable key."
  (let ((key (caar julia-repl-executable-records)))
    (assert key "Could not find any key in JULIA-REPL-EXECUTABLE-RECORDS.")
    key))
the problem seems to be with the assert statement. My workaround was to comment out the assertion and then everything worked just fine.

(let ((key (caar julia-repl-executable-records)))
    ;;(assert key "Could not find any key in JULIA-REPL-EXECUTABLE-RECORDS.")
    key))
not sure why is it causing problems.

**Comment by gdkrmr** [comment]
i cannot reproduce this

**Comment by orialb** [comment]
thanks for trying to reproduce. 
This problem seems to boil down to the fact that evaluating `(assert var string)` gives an error (while `(assert var)` is working fine) . 
I don't have a clue what could cause this, but it seems something just got messed up with my setup and it's not relevant for other people, so I'll close the issue.

**Comment by orialb** [comment]
this issue was fixed in the julia-repl package https://github.com/tpapp/julia-repl/pull/39
