### ISSUE TITLE
Where to add multi-line package, bindings?

### ISSUE THREAD

**Issue by gondalez** [syl20bnr/spacemacs#11309]
I really like [multi-line](https://github.com/IvanMalison/multi-line) for toggling single/multiline function invocations.

Currently I have it hacked in under `jump/join/split` as below. In future it'd be nice to convert to a transient state.

What would be the best way to package it up for other spacemacs users? 
It seems too small to be in its own layer.

```
diff --git a/layers/+distributions/spacemacs-base/keybindings.el b/layers/+distributions/spacemacs-base/keybindings.el
index 230a424ce..37d4ca970 100644
--- a/layers/+distributions/spacemacs-base/keybindings.el
+++ b/layers/+distributions/spacemacs-base/keybindings.el
@@ -217,6 +217,7 @@
   "jo" 'open-line
   "j=" 'spacemacs/indent-region-or-buffer
   "jS" 'spacemacs/split-and-new-line
+  "jm" 'multi-line
   "jk" 'spacemacs/evil-goto-next-line-and-indent)

 ;; navigation/jumping ---------------------------------------------------------
diff --git a/layers/+distributions/spacemacs-base/packages.el b/layers/+distributions/spacemacs-base/packages.el
index 6d5f3c93f..2dc125eea 100644
--- a/layers/+distributions/spacemacs-base/packages.el
+++ b/layers/+distributions/spacemacs-base/packages.el
@@ -53,6 +53,7 @@
         (visual-line-mode :location built-in)
         (whitespace :location built-in)
         (winner :location built-in)
+        multi-line
         ))

 ;; Initialization of packages
@@ -260,6 +261,10 @@
       (when dotspacemacs-line-numbers
         (global-linum-mode)))))

+(defun spacemacs-base/init-multi-line()
+  :init
+  )
+
 (defun spacemacs-base/init-occur-mode ()
   (evilified-state-evilify-map occur-mode-map
     :mode occur-mode))
```

**Comment by Miciah** [comment]
I would put it in the spacemacs-editing layer.  You could follow the string-inflection transient state as an example: https://github.com/syl20bnr/spacemacs/blob/c122eb6a05ddffeccfe20fc7f56cae550c463575/layers/+spacemacs/spacemacs-editing/packages.el#L384-L402
You might also consider <kbd>SPC x m</kbd> as a key binding.  <kbd>SPC j</kbd> is more movement-oriented commands (think "jumping") whereas <kbd>SPC x</kbd> has a lot of text-transformation commands.

**Comment by duianto** [comment]
A transient state key binding (`SPC x n`) has been added to the `develop` branch:
[editing] add binding for multi-line #14386
