### ISSUE TITLE
When I use spacemacs in the remote ubuntu, it is not possible to copy to the clipboard of local mac.

### ISSUE THREAD

**Issue by Keiku** [syl20bnr/spacemacs#11308]
Currently, I log in to remote ubuntu from local mac in iterm2 with ssh and use spacemacs there. In this environment, if I execute the copy command in each mode of spacemacs, it is not stored in clipboard of local mac. Note that spacemacs in tmux and screen did not work as well. How can I solve this problem?

I tried the following, but it did not work well.

* I checked "Applications interminal may access clipboard" with iterm2
* I tried this settings https://github.com/syl20bnr/spacemacs/issues/2222#issuecomment-269269359

The environment is as follows.
macOS: 10.13.6
emacs: 26
spacemacs: 0.200.13
iTerm2: Build 3.2.0
Ubuntu: 16.04 LTS

**Comment by robbyoconnor** [comment]
I'm fairly certain this is by design...

**Comment by robbyoconnor** [comment]
If you need to edit remote files, use [Tramp Mode](https://www.emacswiki.org/emacs/TrampMode).

**Comment by gdkrmr** [comment]
I have the same problem and I would like to know a workaround: My usual setup is a tmux session on a remote machine and a terminal emacs inside that session. Because both tmux and emacs intercept mouse clicks it is not possible to select and copy text from the terminal one can do with a plain terminal session.

**Comment by Keiku** [comment]
@robbyoconnor @gdkrmr 
One solution was found. I found a function called "Copy Mode" of iTerm2.

We can copy in Spacemacs as follows.

1. ssh ubuntu (ssh login)
2. emacs _file_ (Open _file_ by Spacemacs)
3. Shift ⌘ C (Copy Mode on iTerm2)
4. v (select _text_)
5. ⌘ C (copy _text_)
6. ⌘ V (paste _text_)

**Comment by iromise** [comment]
@Keiku That might be a workaround, but when you open file tree using treemacs, you may copy the file tree.

I am also wondering if there is some better choice.
