### ISSUE TITLE
Zoom frame results in (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by tchajed** [syl20bnr/spacemacs#11301]
#### Description :octocat:
Zoom frame in/out does not work on `develop`, instead results in `(wrong-type-argument stringp nil)`

#### Reproduction guide :beetle:
- Start Emacs
- run `M-x spacemacs/zoom-frm-in`

*Observed behaviour:* :eyes: :broken_heart:
`(wrong-type-argument stringp nil)`

*Expected behaviour:* :heart: :smile:
Frame should zoom

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 044237139)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion git org syntax-checking version-control lsp csv idris ruby coq fstar fsharp emacs-lisp haskell html javascript
                 (latex :variable latex-enable-folding t)
                 lua markdown ocaml python rust typescript yaml
                 (go :variables go-tab-width 4)
                 purescript)
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS THREADS GMP

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-to-number(nil)
  (+ (string-to-number (aref xlfd-fields xlfd-regexp-pixelsize-subnum)) increment)
  (let ((new-size (+ (string-to-number (aref xlfd-fields xlfd-regexp-pixelsize-subnum)) increment))) (if (> new-size 0) nil (signal 'font-too-small (list new-size))) (aset xlfd-fields xlfd-regexp-pixelsize-subnum (number-to-string new-size)))
  (let ((xlfd-fields (x-decompose-font-name fontname))) (if xlfd-fields nil (error "Cannot decompose font name")) (let ((new-size (+ (string-to-number (aref xlfd-fields xlfd-regexp-pixelsize-subnum)) increment))) (if (> new-size 0) nil (signal 'font-too-small (list new-size))) (aset xlfd-fields xlfd-regexp-pixelsize-subnum (number-to-string new-size))) (aset xlfd-fields xlfd-regexp-pointsize-subnum "*") (aset xlfd-fields xlfd-regexp-avgwidth-subnum "*") (x-compose-font-name xlfd-fields))
  frcmds-enlarged-font-name("-*-Source Code Pro-normal-normal-normal-*-*-*-*-*-..." #<frame 
```

As part of my backtrace the font name appears to be "-*-Source Code Pro-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1".

**Comment by epichub** [comment]
Yeah I am suffering the same problem, I have tried changing from Source Code Pro to "Hack" without any more luck..

**Comment by duianto** [comment]
I'm not seeing any error messages when I call `M-x spacemacs/zoom-frm-in` (or `-out`) or press the zoom frame transient state bindings `SPC z f`, in either Windows 10 or Ubuntu 18.04.02

On the latest develop branch with updated packages.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23df5aa55)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown multiple-cursors
            (org :variables org-enable-org-journal-support t)
            spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2


#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23df5aa55)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP
