### ISSUE TITLE
Symbol's function definition is void: org-export-dispatch

### ISSUE THREAD

**Issue by andreasfrom** [syl20bnr/spacemacs#1130]
After updating to 0.101.0 and adding `org` to my layers, I get the above error when trying to run `org-export-dispatch` through `SPC m e`. There is no entry for it, in the `SPC :` menu.
My `org-version` is below

Org-mode version 8.2.10 (release_8.2.10 @ mixed installation! /Users/andreasfrom/.emacs.d/elpa/ox-gfm-20141211.240/ and /nix/store/6j7w5180n6y002512bsg6h45m1mw9ms4-emacs-24.4-mac-5.1/share/emacs/24.4/lisp/org/

**Comment by CarlQLange** [comment]
Seems related, in the chat:
[April 13 2015 10:23 AM](https://gitter.im/syl20bnr/spacemacs?at=552b6ede0e3138bb6be7f231)

**Comment by andreasfrom** [comment]
Okay commenting out `ox-gfm` in `~/.emacs.d/contrib/org/packages.el` fixes the problem.
Thank you for the hotfix.

**Comment by CarlQLange** [comment]
The better way to do this until a fix is merged is to add `ox-gfm` to the excluded packages in your dotfile. Sorry for giving bad advice!

**Comment by syl20bnr** [comment]
Thank you for the report and the investigation, I excluded `ox-gfm` from the org layer for now, available in version `0.101.1`.
