### ISSUE TITLE
Error running timer 'auto-revert-buffers': (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by non-Jedi** [syl20bnr/spacemacs#11314]
#### Description :octocat:

Constantly get error: `Error running timer ‘auto-revert-buffers’: (wrong-type-argument stringp nil)`

#### Reproduction guide :beetle:
- Start Emacs
- Open an org-mode buffer
- If that org-mode buffer has a SRC block with either `julia` or `jupyter-julia` (anything that uses `julia-mode` I think), errors will begin accumulating in `*Messages*`.

*Observed behaviour:* :eyes: :broken_heart:

`*Messages*` buffer fills up with an alarming number of the aforementioned error.

*Expected behaviour:* :heart: :smile:

No errors.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ba9331693)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(emacs-lisp vimscript shell python ipython-notebook nim sql
            (julia :variables julia-mode-enable-lsp nil julia-mode-enable-ess nil)
            ess ivy semantic html yaml latex markdown org epub pdf lsp git
            (auto-completion :variables auto-completion-idle-delay 0.5)
            spell-checking syntax-checking
            (w3m :location local))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB LUCID X11 MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  auto-revert-notify-add-watch()
  auto-revert-buffers()
  apply(auto-revert-buffers nil)
  timer-event-handler([t 23448 6609 992916 5 auto-revert-buffers nil nil 643000])

```

**Comment by non-Jedi** [comment]
Additional data seemingly related: when I open a `#+BEGIN_SRC` block in org-mode using `SPC-m-'`, I get the following backtrace; everything seems to be working otherwise though.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  flycheck-may-check-automatically(save)
  flycheck-buffer-automatically(save)
  flycheck-handle-save()
  run-hooks(after-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```

**Comment by non-Jedi** [comment]
Still have no idea what's going on here and would appreciate any help, but for anyone else who might be randomly running into this same issue, my current workaround is to customize `global-auto-revert-ignore-modes` to include `julia-mode`.

**Comment by non-Jedi** [comment]
@tpapp could the recent update to `julia-repl` be causing this? Does `julia-repl` handle the case where the buffer it's being invoked in doesn't have an associated file?

**Comment by selimober** [comment]
Can confirm the same working on Clojure file. I'm on rev 9865e7731

**Comment by peterhoeg** [comment]
I am not using neither Julia nor Clojure but I'm getting the same error. I'm guessing it's coming from the ```git``` layer as we both have that in common and the ```magit``` package is the only one doing anything with ```auto-revert-buffers```. @selimober, you are using the git layer too?

**Comment by selimober** [comment]
@peterhoeg both `git` and `version-control` are enabled in my config. But the funny thing I don't get this error anymore...

**Comment by peterhoeg** [comment]
When this happens, it becomes impossible to save. The workaround is the following which kills the timers:

```elisp
(cancel-function-timers 'auto-revert-buffers)
```

**Comment by non-Jedi** [comment]
@peterhoeg have you updated org-mode to 9.2? That fixed it for me as per the conversation in https://github.com/tpapp/julia-repl/issues/41.

**Comment by peterhoeg** [comment]
@non-Jedi, yep, on 9.2. But it happens very randomly/rarely.

**Comment by NightMachinary** [comment]
I get this, too.


#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby lua octave csv sql asciidoc yaml fsharp windows-scripts javascript
      (julia :variables julia-mode-enable-ess t julia-mode-enable-lsp nil)
      json ocaml idris fasd xclipboard gpu epub spotify search-engine vimscript
      (typescript :variables typescript-backend 'tide)
      (elfeed :variables rmh-elfeed-org-files
              (list "~/.emacs.d/private/feeds/elfeed1.org"))
      (rust :variables rust-backend 'racer rust-format-on-save t)
      (haskell :variables haskell-enable-hindent t)
      (c-c++ :variables c-c++-enable-clang-support t)
      html dap chrome
      (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
      (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
      autohotkey kotlin helm
      (auto-completion :disabled-for
                       '(ocaml)
                       :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
      emacs-lisp
      (ibuffer :variables ibuffer-group-buffers-by 'modes)
      coq emoji
      (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
      git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking
      (syntax-checking :variables syntax-checking-enable-tooltips t)
      (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
      version-control osx scheme
      (clojure :variables clojure-enable-fancify-symbols t))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS


#### Backtrace :paw_prints:
```

```

**Comment by montaropdf** [comment]
I also get this problem since sometimes now. It always happen after updating my emacs packages. The problem disappear if I restart Emacs.

I face the problem on Fedora 32 and CentOS 8, all using vanilla Emacs.

My base configuration is [here](https://github.com/montaropdf/reve-emacs-config).

**Comment by vibrys** [comment]
stumbled upon the same issue:
emacs.26.3, spacemacs commit 8b888c6a0

happens, just after I've compiled some c++ source file

(buffer-file-name) returns nil, when called from within `auto-revert-buffers'.

`(setq global-auto-revert-non-file-buffers nil)' doesn't cure

**Comment by vibrys** [comment]
IMO, this has strong relation with the following:

    (progn
      (require 'helm-make)
      (with-helm-default-directory
          "/path/to/dir/containing/Makefile/file/"
        (let
            ((targets
              (helm--make-cached-targets "Makefile"))
             (default-directory (file-name-directory "Makefile"))
             )
          (helm :sources
                (helm-build-sync-source "Targets" :candidates 'targets :fuzzy-match helm-make-fuzzy-matching :action 'identity)
                :history 'helm-make-target-history :input
                (when helm-make-target-history
                  (car helm-make-target-history))))))


it is reproducible on vanilla spacemacs origin/develop but not on vanilla helm.

*NOTE*: if You comment out `default-directory` setting, then problem does not persist.
*NOTE*: problem persists at first call after startup.

**Comment by lsandov1** [comment]
I started hitting this problem today but I am not a spacemacs user (sorry) but I am magit user. Under the magit code, grep matchez some auto-revert-buffers calls, so magit may be the culprit, at least in my case...

**Comment by mcardozo** [comment]
I removed `default-directory` setting and worked form
