### ISSUE TITLE
Searching for properties in org-mode (C-c / m) gives the wrong sparse tree

### ISSUE THREAD

**Issue by ramboman** [syl20bnr/spacemacs#11312]
#### Description :octocat:
In org-mode, I have an issue when I search for properties using `C-c \` or `C-c / m`. The sparse tree I get after the command is not as expected.

#### Reproduction guide :beetle:
- Start Emacs
- Open cats.org file. Here is the content of the file:
```org
* Cats
** Cat 1
   :PROPERTIES:
   :Name:     Mimi
   :END:
** Cat 2
   :PROPERTIES:
   :Name:     Kiwi
   :END:
```
- Type `C-c \` or `C-c / m`
- Type `Name={Mimi\|Kiwi}` and RET

*Observed behaviour:* :eyes: :broken_heart:
cats.org:
```org
* Cats...
```

Message buffer:
```
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-next-line’ originally mapped on ‘C-n’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-toggle-time-grid’ originally mapped on ‘G’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-filter-remove-all’ originally mapped on ‘|’
```

*Expected behaviour:* :heart: :smile:
cats.org:
```org
* Cats
** Cat 1...
** Cat 2...
```
The stars in front of Cat 1 and Cat 2 are highlighted.

It works on mimimal setup using vanilla emacs as specify here:
https://orgmode.org/org.html#Feedback

but not when I use the fresh spacemacs install with org-mode.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html vimscript lua python helm auto-completion emacs-lisp git markdown
      (org :variables org-projectile-file "TODOs.org")
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh")
      themes-megapack xsel yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by ramboman** [comment]
I made some tests using almost stock configurations.

- It wasn't before I added:
```
(setq-default dotspacemacs-configuration-layers
...
  (org :variables org-projectile-file "TODOs.org")
...)
```
that the following messages starts to appears the first time I do `C-c \` `Match: NAME={Mimi\|Kiwi}`:
```
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-next-line’ originally mapped on ‘C-n’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-toggle-time-grid’ originally mapped on ‘G’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-filter-remove-all’ originally mapped on ‘|’
```

- I did a fresh install choosing `None` instead of `Helm` at the first startup configuration. Helm was still installed. 
- Opened `cats.org` with emacs.
- Did `C-c \` `Match: NAME={Mimi\|Kiwi}`. It works the first time, but after I change the visibily of the subtree and retry, it does not work. 
- exited spacemacs.
- deleted the `~/.emacs.d/.cache` directory
- restarted spacemacs.
- redone `C-c \` `Match: NAME={Mimi\|Kiwi}`. It works the first time and not the following time. In the helm org-match-sparse-tree History buffer at the bottom, there is a choice `NAME={Mimi|Kiwi}` which is not what I typed earlier because `\` is missing.

I observed this behavior when I choose `None` or `Helm` at the first startup configuration.

- I did a fresh install choosing `Ivy` at the first startup configuration. Doing `NAME="Mimi"` and `Name={Mimi\|Kiwi}` works. Ivy records no history regarding my matches.

**Comment by ramboman** [comment]
I was in the master branch. The issue is solved in the develop branch.

**Comment by singpolyma** [comment]
I have this problem too, but switching to `develop` branch makes emacs unusably slow for me.  Any ideas what is broken in master?
