### ISSUE TITLE
Spacemacs does not set the font correctly in daemon mode as in #6197 (workaround included - potential clue as to what is causing the problem)

### ISSUE THREAD

**Issue by cyruseuros** [syl20bnr/spacemacs#11321]
#### Description :octocat:
Spacemacs does not set the font correctly in daemon mode as in #6197
(workaround included - a potential clue as to what is causing the problem).
This only happens when `themes-megapack` layer is installed - even with the default
`spacemacs-dark` theme.

#### Reproduction guide :beetle:
- Install themes megapack
- Start Emacs (`emacs --daemon` / `systemctl start --user emacs`)
- Start Emacs (`emacs` - not Emacs server)

*Observed behaviour:* :eyes: :broken_heart:
The wrong font is set in the Emacs server, while Source Code Pro (the right one)
is set in the regular Emacs instance.

The issue disappears if I do either of the following:
1. I remove `themes-megapack`
2. I add the following to `user-init`. My guess is that `themes-megapack`
   tries to load the fonts too early, and this later call in `user-init`
   corrects for the problem.
   ```
   (spacemacs|do-after-display-system-init
   (spacemacs/set-default-font dotspacemacs-default-font))
   ```

*Expected behaviour:* :heart: :smile:
Adobe Source Code Pro is set as the font in both the Emacs server and the regular instance.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(systemd restructuredtext sphinx helm auto-completion better-defaults emacs-lisp git markdown neotree
         (org :variables org-enable-github-support t org-enable-bootstrap-support t org-enable-reveal-js-support t org-agenda-files "~/org/agendarc" org-adapt-indentation nil org-todo-keywords
              '((sequence "TODO" "|" "DONE" "CANCELED" "NODO"))
              org-enable-org-journal-support t)
         (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
         spell-checking syntax-checking version-control python ess ocaml c-c++ nim html javascript sql shell-scripts pdf csv colors emoji gnus imenu-list latex chrome
         (bibtex :variables org-ref-default-bibliography
                 '("~/Papers/references.bib")
                 org-ref-pdf-directory "~/Papers/" org-ref-bibliography-notes "~/Papers/notes.org" org-latex-to-pdf-process
                 '("latexmk -pdf %f")
                 bibtex-completion-bibliography "~/Papers/references.bib" bibtex-completion-library-path "~/Papers" bibtex-completion-notes-path "~/Papers/notes.org" bibtex-dialect 'biblatex)
         themes-megapack
         (ranger :variables ranger-parent-depth 2 ranger-show-hidden nil ranger-show-preview t ranger-cleanup-on-disable t ranger-ignored-extensions
                 '("mkv" "iso" "mp4")))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:

**Comment by gdkrmr** [comment]
I have a couple of problems with daemon mode your particular problem can be solved by adding 

```elisp
  (add-to-list 'default-frame-alist
               '(font . "-ADBE-Source Code Pro-normal-normal-normal-*-13-*-*-*-m-0-iso10646-1"))
```
to `dotspacemacs/user-config`.

**Comment by CarlQLange** [comment]
I still get this issue (also when loading from a dump) and the fix outlined in the post works for me:

```
(spacemacs|do-after-display-system-init
(spacemacs/set-default-font dotspacemacs-default-font))
``` in my user-init or user-config.

**Comment by duianto** [comment]
Confirmed, the default OS font loads without the workaround.

- Fira Mono in PopOS
- Courier New in Windows

Once while testing, the mode line separators weren't shown and the spacemacs buffer menu colors were incorrect, but that hasn't happened again the last three times a new daemon/client was started.

![emacs_2020-06-12_11-04-31](https://user-images.githubusercontent.com/13420573/84489925-b8016500-aca2-11ea-858b-82af4a598010.png)

<details><summary>
System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5fcd84d84)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 emacs-lisp git helm html javascript lsp
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org"))
 (python :variables)
 ranger
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 themes-megapack treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by pamrg1** [comment]
> I still get this issue (also when loading from a dump) and the fix outlined in the post works for me:
> 
> ```
> (spacemacs|do-after-display-system-init
> (spacemacs/set-default-font dotspacemacs-default-font))
> ```
> 
> in my user-init or user-config.

This has been working until my ArchLinux system upgrade today... :'(

**Comment by psisis** [comment]
This issue is still valid. As far as I know, there are a few ways to set font in an Emacs Spacemacs distro.

The first is obviously by spacemacs-default-font, this doesn’t work with daemon mode, Spacemacs will warn about invalid family, and fontset will include the courier font.

The next is by ignoring spacemacs and setting Default Face in basic-faces, this works just fine with daemon mode. But spacemacs will still complain and courier will be loaded in the fontset.

I’ve also seen adding a font option to default-frame-alist, but this seems inefficient.

What I’ve noticed is that spacemacs-default-font and default-face will look **different**, even if they load the same font.

**Comment by lebensterben** [comment]
@psisis 

Do you have themes-megapack enabled as well?

This layer doesn't seem to do anything other than declaring those themes. I don't know why it would cause any issue.
