### ISSUE TITLE
Lsp mode for python doesn't autocomplete for pandas dataframes.

### ISSUE THREAD

**Issue by MAliNaqvi** [syl20bnr/spacemacs#11338]
#### Description :octocat:
Lsp mode for python doesn't autocomplete for pandas dataframes.

Instead, under the powerline I see the following meessage:

```
Error from the Language Server: TypeError: a bytes-like object is required, not ’str’ (Invalid Parameters) [3 times]
```

Interestingly this happens only when at the `.` less so when one character of the child object is added.

#### Reproduction guide :beetle:
- Start Emacs
- Open a python file
- Type in the following:

```
import pandas as pd


df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
a = df.
```
Press tab at the `.`

You should see the error message:

```
Error from the Language Server: TypeError: a bytes-like object is required, not ’str’ (Invalid Parameters) [3 times]
```

Add a character 'c' after the `.`

```
import pandas as pd


df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
a = df.c
```

Then press tab

Results in:
https://www.dropbox.com/s/kfpv3pumqowhhz3/Screenshot%202018-09-17%2017.47.52.png?dl=0

*Observed behaviour:* :eyes: :broken_heart:
No autocomplete at for pandas dataframes at `.`

*Expected behaviour:* :heart: :smile:
Pandas dataframe object should show autocomplete options at `.`

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql javascript csv html yaml
     (lsp :variables lsp-ui-remap-xref-keybindings t)
     (python :variables python-backend 'lsp python-test-runner 'pytest python-sort-imports-on-save t python-enable-yapf-format-on-save nil python-shell-interpreter-args "-i")
     docker helm auto-completion better-defaults emacs-lisp git org
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
     markdown)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by yyoncho** [comment]
This looks like an issue in `python-language-server` - https://github.com/palantir/python-language-server .
