### ISSUE TITLE
Option to use standard ruby-mode in ruby layer.

### ISSUE THREAD

**Issue by pbrown-fiksu** [syl20bnr/spacemacs#1133]
https://github.com/syl20bnr/spacemacs/tree/master/contrib/lang/ruby

enhanced-ruby-mode indents dramatically differently than the standard ruby-mode, and my team uses the standard way of indentation. It would be super nice if spacemacs could opt into using the standard ruby-mode.

**Comment by syl20bnr** [comment]
You can replace it in a private layer. Say your layer is called `my-ruby` which will be applied on top of the regular `ruby` (i.e. you add them both to your dotfile, the order does not matter).

Then a skeleton for the `packages.el` file of your layer would be:

```elisp
(defvar my-ruby-packages
  '(ruby-mode)
  "List of all packages to install and/or initialize. Built-in packages
which require an initialization must be listed explicitly in the list.")

(defvar my-ruby-excluded-packages '(enh-ruby-mode)
  "List of packages to exclude.")

(defun my-ruby/init-ruby-mode ()
  (use-package ruby-mode
    :defer t))
```

**Comment by pbrown-fiksu** [comment]
Awesome! This gets me by for now :smile:.

It still would be nice to have an official spacemacs toggle (with keybindings and such), but if I'm the only one who needs it I can deal.

**Comment by johnny** [comment]
I would vote for making ruby-mode the default and optionally use enh-ruby-mode while disabling rubocop.

At the moment, rubocop does not like the indentation of enh-ruby-mode, which results in lot's of blue dots :sob: . Base on this SO answer http://stackoverflow.com/a/24031261 I don't think that rubocop will change to support enh-ruby-mode's way of indentation.

**Comment by ptrckbrwn** [comment]
:+1: ruby-mode

**Comment by syl20bnr** [comment]
@johnny do you mean that `rubocop` is not compatible with the `ripper` class ?

**Comment by johnny** [comment]
@syl20bnr that is correct. `Ripper` produces indentation, that `rubocop` sees as a violation.

The indentation on multi line method calls is different, same goes for hash syntax (ripper indents one space, every ruby code I saw indents two spaces), ....

**Comment by mmainz** [comment]
I'd also love to use the standard `ruby-mode` instead. It indents a lot better than `enh-ruby-mode`, and is more compatible with the community style guide. Also, the fix mentioned above actually seems to prevent the keybindings from being set up correctly, at least `SPC m` is undefined for me :(

**Comment by TheBB** [comment]
There's an option for this in the develop branch now.
