### ISSUE TITLE
Switching to develop broke working configuration "Error in dotspacemacs/user-config: Symbol’s value as variable is void: (setf (flycheck-checker-get "

### ISSUE THREAD

**Issue by breneser** [syl20bnr/spacemacs#11347]
#### Description :octocat:
Setting sh-shellcheck checker's working directory to projectile-root no longer works since I switched to develop branch of spacemacs.

#### Reproduction guide :beetle:
- Add following code snippet to user-config in .spacemacs file
```elisp
  ; Change working dir to project root for shellcheck checker
  (setf (flycheck-checker-get 'sh-shellcheck 'working-directory)
    (lambda (checker)
      (projectile-project-root)
      ))
```

- Start Emacs
- You will see error at startup

`Error in dotspacemacs/user-config: Symbol’s value as variable is void: (setf (flycheck-checker-get `

*Observed behaviour:* :eyes: :broken_heart:
`Error in dotspacemacs/user-config: Symbol’s value as variable is void: (setf (flycheck-checker-get `

*Expected behaviour:* :heart: :smile:
sh-shellcheck working directory should be set to projectile-project-root

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python react markdown html javascript yaml helm
        (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
        emacs-lisp git
        (shell :variables shell-default-height 30 shell-default-shell `eshell shell-default-position 'bottom)
        shell-scripts spell-checking
        (syntax-checking :variables syntax-checking-enable-by-default t)
        vinegar
        (gtags :variables gtags-enable-by-default t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by Miciah** [comment]
Does using `with-eval-after-load 'flycheck` avoid the problem? Something like the following (untested):
```emacs-lisp
  (with-eval-after-load 'flycheck
    ;; Change working dir to project root for shellcheck checker.
    (setf (flycheck-checker-get 'sh-shellcheck 'working-directory)
      (lambda (checker)
        (projectile-project-root))))
```

**Comment by breneser** [comment]
@Miciah It does not show show any error on startup, but flycheck is disabled for shell file now, and when I try to enable ( SPC t s ), it shows the exact same error in the status line.

**Comment by Miciah** [comment]
It is gnarly as hack, but try the following (actually tested this time):
```emacs-lisp
  (with-eval-after-load 'flycheck
    (eval
     ;; Change working dir to project root for shellcheck checker.
     '(setf (flycheck-checker-get 'sh-shellcheck 'working-directory)
            (lambda (checker)
              (projectile-project-root)))))
```

**Comment by breneser** [comment]
Yea, that did it. Thanks a lot. So is that a bug that Spacemacs runs user-config before loading the packages ?

**Comment by Miciah** [comment]
No, Spacemacs uses autoloads (and other lazy-loading techniques) to avoid loading packages before they are used.  In particular, the syntax-checking layer uses `(use-package flycheck :defer t ...)`, which uses autoloads to defer loading the flycheck package until one of its functions is used.

**Comment by breneser** [comment]
Thanks, If I encounter the same error I will try the same. Much appreciated.
