### ISSUE TITLE
Symbol's function definition is void: magit-status

### ISSUE THREAD

**Issue by alexanderkjeldaas** [syl20bnr/spacemacs#11344]
#### Description :octocat:

I'm getting:
```
Symbol's function definition is void: magit-status
```

when using `SPC g s`

#### Reproduction guide :beetle:
- Start Emacs
- Press `SPC g s` in a project

or

- `rm -rf ~/.emacs.d`
- Start Emacs
- Press `SPC g s` in a project

*Observed behaviour:* :eyes: :broken_heart:
```
Symbol's function definition is void: magit-status
```

*Expected behaviour:* :heart: :smile:
It should work

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml haskell helm emacs-lisp git markdown org)
```

**Comment by alexanderkjeldaas** [comment]
This is fixed by upgrading to emacs26 and ```
rm -rf ~/.emacs.d
```

**Comment by Miciah** [comment]
If you or anyone else sees this again, please try to get a backtrace—see [Debugging on the Spacemacs Wiki](https://github.com/syl20bnr/spacemacs/wiki/Debugging#enable-debug).  However, note that Magit and Spacemacs will not support Emacs 24 in future releases (see [the Magit v.2.13.0 release notes](https://raw.githubusercontent.com/magit/magit/master/Documentation/RelNotes/2.13.0.txt)).

**Comment by bigos** [comment]
> This is fixed by upgrading to emacs26 and
> 
> ```
> rm -rf ~/.emacs.d
> ```

I do not use Spacemacs, but my finding may provide a clue. You do not need to remove the whole emacs folder. For me removing elpa folder was sufficient. In the elpa folder, I store packages from melpa and elpa. I guess that after installing a different version of Emacs, in my case 28 -> 29, some packages need reinstalling. In my case, the simplest way to reinstall was deleting my elpa folder and allowing Emacs to install packages on the next run. In Spacemacs it may be different.

**Comment by lebensterben** [comment]
locking since the original issue was posted 4 years ago without too many details to debug with, and things might be quite different now from then.
