### ISSUE TITLE
json/prettier reformatting SyntaxError in orgmode BEGIN_SRC block

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#11343]
#### Description :octocat:
json/prettier reformatting doesn't work in orgmode BEGIN_SRC block, instead prettier complains about "SyntaxError"

The same content when edited in a .json file reformats without problem.

#### Reproduction guide :beetle:
- Start Emacs
- Create test.org file containing
  ```org
  #+BEGIN_SRC json
  {"type":
   1}
  #+END_SRC
  ```
- Move within the `BEGIN_SRC` block and press `, '` (org-edit-special)
- Press `, =` to reformat the JSON in the buffer

*Observed behaviour:* :eyes: :broken_heart:
```
prettier errors:
[error] stdin: SyntaxError: Unexpected token, expected ";" (1:8)
[error] > 1 | {"type":
[error]     |        ^
[error]   2 |  1}
[error]   3 | 
```

*Expected behaviour:* :heart: :smile:
The buffer content is pretty-printed, something like
```org
#+BEGIN_SRC json
{
  "type: 1
}
#+END_SRC
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree
      (javascript :variables javascript-fmt-tool 'prettier)
      (json :variables json-fmt-tool 'prettier))
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

**Comment by Miciah** [comment]
In your example `BEGIN_SRC` blocks, the example json is missing a double-quote: `"type:` should be `"type":`.  However, from prettier's error message, it looks like you actually tested with `"type":`.  So just to be clear, are you getting the reported error message with `"type":`?

**Comment by tko** [comment]
I'm testing with valid json, so with `"type":` .. not sure what happened there.

**Comment by tko** [comment]
I'm seeing the same error if just I pipe json through `prettier`. Apparently for json you need `prettier --parser=json`. There's `prettier-js-args` variable that can pass arguments to prettier, I guess that should be prefilled for json.

**Comment by tko** [comment]
I guess similar hooks need to be set for all other modes (for which prettier is added) as well as prettier needs to be told what the _real_ format is when used in orgmode. Related: https://github.com/prettier/prettier-emacs/issues/38

**Comment by Miciah** [comment]
Looks like #11364 fixed this issue on the develop branch.

**Comment by duianto** [comment]
Thank you for posting an update.
