### ISSUE TITLE
A recent release?

### ISSUE THREAD

**Issue by hyiltiz** [syl20bnr/spacemacs#11352]
There have been quite a lot of fixes since the last official release, e.g. https://github.com/syl20bnr/spacemacs/issues/9374. While there is a milestone it hasn't really been updated for about a year. If simply using `develop` branch as a rolling release is officially recommended, I'd be more than willing to switch (some of my friends share this idea too). 

So, is it possible to either release one (maybe even a `-rc` or `-hotfix` release), or a recommendation for the develop branch?

**Comment by gdkrmr** [comment]
I personally use the develop branch and pull every other week and update packages, sometimes things break, mostly because of my local config, but most of the times it goes smoothly.

I have also given up on fixed and stable versions---version 0.300 should be "almost out" for a year now---I rather have the maintainers put their limited time into merging all the open pull requests and keep `develop` up to date with melpa packages and emacs version.

**Comment by robbyoconnor** [comment]
If you want things faster -- use `develop` -- Most consider the `develop` to be the rolling-release channel.

**Comment by jr0cket** [comment]
I have found `develop` to be perfectly than stable for my development of produciton code for well over a year.  I only pull new spacemacs commits when they have something interesting that I can use and I am not on any deadline to deliver something.

I always do a comparison with the .spacemacs template `SPC f e D` and then do a package update.  I always restart Emacs at least once after all this, sometimes twice just to make sure all the packages downloaded.

I am not sure how much sense it makes to keep master if there are not enough resources to do a 6 monthly release of master.  If I knew how to help, I would be happy to do so.

**Comment by robbyoconnor** [comment]
@jr0cket is right -- there were brief moments where `develop` became unstable but I use it as my daily driver -- have since I started using spacemacs. Spacemacs is far from dead.

**Comment by hyiltiz** [comment]
Maybe tentatively tag a commit to be considered `beta` and test for 3 months before it is considered *production quality* and is ready to be merged into `master`? I assume a large portion of users are migrating from Vim (as I am), and are thus new to `lisp`. But we could help organize issues, find solutions etc., as most issues have solutions somewhere out there already, and some example code that shows a fix. This is essentially how it already is working as I see it, but with a production cycle in mind. Alternatively, maybe put "consider `develop` a rolling release" somewhere in FAQ/Wiki so people wouldn't worry too much about jumping into `develop` branch.

**Comment by robbyoconnor** [comment]
I just jumped into emacs lisp and added the features I needed...try doing that -- I went the whole trial by fire route

**Comment by Kjir** [comment]
I was surprised to find out today that the latest release is nearly 9 months old - and not for a lack of new developments!
I'd say that spacemacs has good automated checks, so maybe it would be worth considering another release strategy.
IMO the releases should be based on time (e.g. every week/every month/every 3 months) instead of feature based (can't release until X, Y and Z are done). Right now `develop` is very far ahead and the risk for the next release to break something is bigger, leading to a spike of bug reports right after the release which will slow everything down.

The release process should be automated, so that the focus can be solely on managing the pull requests and bugs. If something is not done about the abundant number of open PRs (and issues) the risk is that the community might stop contributing altogether: it makes you feel uncertain if the PR will ever be considered or merged (regardless if it's true or not).

This is not to criticize anyone's work. I only think that Spacemacs might have reached a turning point where it needs to change some processes to better enable the community to drive it forward. What worked up until now might not work anymore, which is a great sign of success!

**Comment by dijonkitchen** [comment]
Made https://github.com/syl20bnr/spacemacs/pull/11472 to help the discussion. 

I also think `master` is lagging behind `develop` too much. It's going to be hard to merge and figure out conflicts and other potential bugs. Big bang releases are always riskier than continuous deployment. Can the project move to that?

**Comment by hyiltiz** [comment]
Taking actions are great. We also need to discuss and find out what works best for the developer team and the user base as a whole, and that discussion is better done here than in another thread. I agree @Kjir above. An automated and more frequent release cycle would be great.

I am guessing that most would be using highly customized emacs like spacemacs on their desktop and custom servers, instead of streamlined production or deployment servers. Therefore, a rolling release cycle would work for the user base; it may have bugs from time to time, but desktop users generally would be able to deal with them (more easily) and the consequences might be smaller than in production servers. 

It the release lags behind too much, it will be much similar to what vim had gone through from 7 to 8 major releases and the neovim etc.

**Comment by dijonkitchen** [comment]
I think the main thing is there should be more public communication on what the owners are thinking, so all the users don't need to panic. I don't believe there's enough transparency.

**Comment by dijonkitchen** [comment]
I think the main thing is there should be more public communication on what the owners are thinking, so all the users don't need to panic. I don't believe there's enough transparency.

**Comment by dijonkitchen** [comment]
I think the main thing is there should be more public communication on what the owners are thinking, so all the users don't need to panic. I don't believe there's enough transparency.

**Comment by dijonkitchen** [comment]
Maybe coming soon? 

https://twitter.com/spacemacs/status/1067118393550098432

**Comment by hanzhixing** [comment]
I with I knew how to write nice elisp codes.

**Comment by WhittlesJr** [comment]
If 0.300 isn't actively being worked on, I'd rather see "VERSION 0.300 IS ALMOST OUT!" and related inaccurate optimism removed from the *spacemacs* buffer. It's actually embarrassing to show Spacemacs to new people because of this.

**Comment by robbyoconnor** [comment]
A reminder that we need to remember that if we want releases, help incentivize by donating. There is a link the README to do so. `develop` has most of the stuff that will land in `0.300.0`. 

None of us have any rights to demand anything, nor does @syl20bnr  or any of the contributors have to actually listen to us, we can hope they do but at the end of the day -- we're entitled to nothing when it comes to FOSS. Pull requests are being merged, so the project is not dead.

**Comment by WhittlesJr** [comment]
There. $50 USD to Bountysource. 

I'm not asking for a major effort here -- I'm asking for *honesty*. If no one actually intends to follow through with what is heralded in all caps on the front page of the application, then it should be taken down. 

Think about a new user, for example. They boot up spacemacs and see these really exciting promises shouted at them on the first buffer that pops up, and they can't wait to see 0.300 and have a rock-solid, stable editing experience. Then six months go by and nothing happens, so they start asking around. They are told that they should just stick with develop if they want anything recent, and pray that nothing breaks when they pull. 

Fine, but why not say that up front? Why not replace the message in `*spacemacs*` with that exact advice? `Spacemacs is a rolling-release application, please track develop.` *That* would be honesty, and that is all I'm asking for.

**Comment by idoo** [comment]
@WhittlesJr I guess you're right. Would be better to rename `develop` to `master` I change release cycle :)

**Comment by hyiltiz** [comment]
@idoo Not idea, but definitely far easier to implement, and also better than whatever the community is stuck with so far.

**Comment by abitrolly** [comment]
If merging is hard or impossible, maybe then move current `master` into dedicated `branch-0.200`, move `develop` to `master` and tag `0.300` from new `master`. Add install instructions for how to rollback installation to an old stable `branch-0.200`.

What drawbacks are expected from this proposal?

**Comment by dijonkitchen** [comment]
That might be confusing for existing users that are locked on a particular branch. 

If I remember correctly, there's also some differences like people on master expecting it auto-update. 

Configuration is also different (breaking in some cases) between `master` and `develop`.

**Comment by langston-barrett** [comment]
Still valid.

**Comment by hyiltiz** [comment]
Stale bot's algorithm is stale :D This issue itself is about staleness of a project... Kinda triple jokes on us here.

**Comment by robbyoconnor** [comment]
The thing is that most of us use `develop` so treat Spacemacs as a rolling release effectively.

**Comment by smile13241324** [comment]
Sorry guys but this ticket is duplicate and in my opinion should be closed.
A discussion about releases and how to proceed with the develop branch should be done in #13380 which we will keep open.

As to bounties and such, I think the most straightforward way is to support @syl20bnr via github sponsors.

Other threads discussing the same topic should refer to 13380 and be closed in turn.

**Comment by hyiltiz** [comment]
#13380 With all due respect, you would usually close all later issues as duplicates, since they'd also refer to the earlier ones, and keep the most early one. AFAICT, this is the first issue on this topic with large interest from the community. If you close this, everyone who've contributed to the discussion, subscribed to it, and are still interested to be updated will simply get ignored.

I'd strongly urge against closing this issue while the issue is not yet resolved, esp. in favor of a later duplicate.

**Comment by hyiltiz** [comment]
BTW @smile13241324 since you have the Collaborator permission, would you care to remote the `stale` flag for this Issue? Ironically, the issue is about staleness but that doesn't mean the issue itself is stale by any means.

**Comment by robbyoconnor** [comment]
It got removed automatically.

**Comment by altsalt** [comment]
Hi, as someone new exploring this project, I am nudging the relevant issues in the hope of having some sort of movement on this problem. While I appreciate the defensive and caring community around the project, this is a huge "missing stair" and a trap for newcomers.

Copying over my thoughts from an open issue, as an example of why this is important to make clear.

> Wow, while reading through the documentation and considering switching to Spacemacs, I came across a broken link to one of the layers. Just dropped by to submit a quick PR and my pre-search found this issue. Glad I didn't put in too much effort, but to answer your question [removed username to avoid excess pings], yes, people absolutely use the main branch, since that's what anyone unfamiliar with the project is directed to.

_Originally posted by @altsalt in https://github.com/syl20bnr/spacemacs/issues/14420#issuecomment-826141878_
_Also posted in https://github.com/syl20bnr/spacemacs/issues/14136#issuecomment-826142499_
_Also posted in https://github.com/syl20bnr/spacemacs/issues/13380#issuecomment-826143482_

**Comment by WhittlesJr** [comment]
I pulled develop again today, and I noticed that we get a very different startup banner now:

```
╭─ Important Notes (Release 0.999.x) ──────────────────────────────────────────╮
│                                                                              │
│         ╭───────────────────────────────────────────────────────────╮        │
│                                                                              │
│                      This is the current rolling release                     │
│                                                                              │
│         ╰───────────────────────────────────────────────────────────╯        │
│                                                                              │
╰─ Update your dotfile (SPC f e D) and packages after every update ────────────╯
```

Thank you for making the correct expectation clear. That is just what I was asking for. I still see references to `master` being "stable" on the README. Should those be updated, as well?

**Comment by robbyoconnor** [comment]
Yes, they're now just doing rolling releases.

**Comment by robbyoconnor** [comment]
@WhittlesJr yes it's now using rolling releases.

**Comment by lebensterben** [comment]
@WhittlesJr 

currently master branch is "stale" rather than "stable"...

**Comment by robbyoconnor** [comment]
@lebensterben i wonder if we should set the default branch to `develop`?

**Comment by lebensterben** [comment]
@robbyoconnor 
I really wish. But  I've no access to that setting.

**Comment by robbyoconnor** [comment]
@syl20bnr what say you? Let's get rid of `maater`?

**Comment by smile13241324** [comment]
Stable should not longer be referenced from the Readme, PRs are welcome here. I think the default branch is already develop. The only thing left would be to change the website. Here however I have no access.

**Comment by robbyoconnor** [comment]
@smile13241324 then let's close this issue

**Comment by anka-213** [comment]
Could we add a commit to master with a message that it is no longer recommended and how to switch, e.g. at the home-screen, so people will discover this more easily?

**Comment by smile13241324** [comment]
Sure, I'll have a look what I can do

**Comment by altsalt** [comment]
Somewhat related, clicking on the `News` link from the homepage leads to a page without a clear date, changelog, etc. Perhaps this should be opened as a different issue related to documentation.

**Comment by lebensterben** [comment]
@altsalt 

There is a clear date on the lower left corner: 2016-10-03 Mon 01:52

**Comment by altsalt** [comment]
@lebensterben that's listed as when the page was created, not updated. That said, if the last update to the News page was in 2016... well, that does seem to be a problem.

**Comment by lebensterben** [comment]
@altsalt 

See the history of https://github.com/syl20bnr/spacemacs/commits/develop/news/news01.org

You can say it's never really updated.

**Comment by smile13241324** [comment]
Master is deprecated to make this more clear I have added a new news page on master explaining that "develop" is the only maintained branch now.

This is as far as I am willing to go with master.

**Comment by altsalt** [comment]
One of the related issues I've encountered, and it addresses my last comment, is that https://www.spacemacs.org/ is sourced from the main branch. Due to this, basic things like links to updated documentation and the "beginners tutorial" are missing for most new users. To find these, one would need to visit https://develop.spacemacs.org/
