### ISSUE TITLE
haskell layer tries to start intero even when the project is in the blacklist?

### ISSUE THREAD

**Issue by simendsjo** [syl20bnr/spacemacs#11369]
#### Description :octocat:
Freezes for several seconds once movement stop (idle timer trying to start intero?)

#### Reproduction guide :beetle:
- Start Emacs
- Install the haskell layer
- `(setq haskell-completion-backend 'intero)`
- Open a non-stack project (like `ghc`)
- Move around

See opened issue at intero, but I suspect this might be the haskell layer.
https://github.com/commercialhaskell/intero/issues/578#issuecomment-423723163

*Observed behaviour:* :eyes: :broken_heart:
Freezes

*Expected behaviour:* :heart: :smile:
Smooth movement

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp semantic neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      windows-scripts better-defaults csv
      (elfeed :variables elfeed-db-directory "~/Dropbox/elfeed/elfeeddb" rmh-elfeed-org-files
              (list "~/Dropbox/elfeed/elfeed.org"))
      (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-tab-key-behavior 'complete)
      evil-commentary
      (version-control :variables version-control-global-margin t version-control-diff-side 'left version-control-diff-tool 'git-gutter+)
      git github imenu-list html restclient yaml graphviz pandoc
      (markdown :variables markdown-live-preview-engine 'vmd)
      chrome
      (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t)
      deft plantuml sql floobits fsharp csharp racket elm python haskell purescript idris sml javascript react typescript nixos mu4e gnus erc calendar syntax-checking bibtex theming colors)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
```
```

**Comment by chrisdone** [comment]
I've exposed [`intero-should-start-p`](https://github.com/chrisdone/intero/commit/16fb2fe) for the spacemacs authors to use to check whether intero should start in this buffer.
