### ISSUE TITLE
Evil mode substitution using * broken

### ISSUE THREAD

**Issue by neildurant** [syl20bnr/spacemacs#11366]
#### Description :octocat:
Evil mode substitution using * broken

#### Reproduction guide :beetle:
- Start Emacs
- Open scratch buffer
- Enter the following text:
```
111222
111333
```
- Move the cursor to the first line and do this substitution:   `:s/2*/x/`

*Observed behaviour:* :eyes: :broken_heart:
The substitution has been applied to the second line as well as the first:
```
x111222
x111333
```

*Expected behaviour:* :heart: :smile:
```
x111222
111333
```

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by robbyoconnor** [comment]
Report [upstream](https://github.com/emacs-evil/evil).

**Comment by robbyoconnor** [comment]
Report [upstream](https://github.com/emacs-evil/evil).

**Comment by robbyoconnor** [comment]
If you encounter bugs like these odds are it's upstream

**Comment by robbyoconnor** [comment]
I recommend you close this to clean up the issue tracker @neildurant
