### ISSUE TITLE
ESS major-mode keybindings undefined

### ISSUE THREAD

**Issue by RCIIIcm** [syl20bnr/spacemacs#11371]
#### Description :octocat:
ESS major-mode keybindings undefined

#### Reproduction guide :beetle:
- Start Emacs
- Open R file
- Press [SPC m]

*Observed behaviour:* :eyes: :broken_heart:
"SPC m is undefined".

"ESS[R]" does show in the status bar, and I can use ESS with, e.g., [C-c C-n] to run a line, but the Spacemacs keybindings don't work.

*Expected behaviour:* :heart: :smile:
I expected to see the command continuations for the ESS major-mode.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python latex html helm emacs-lisp ess git markdown org themes-megapack finance)
```
- System configuration features: JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by RCIIIcm** [comment]
Further information: I just deleted my .spacemacs file, restarted emacs, and added ess to dotspacemacs-configuration-layers. I see the same behavior. I opened emacs in a terminal (also 26.1 but different binary) and see the same behavior.

**Comment by gdkrmr** [comment]
I cannot reproduce this on develop. There are a lot of recent major changes in the ESS repo, so I suggest that you use either an older version or switch to spacemacs develop.

**Comment by shaunpatel** [comment]
I have the same issue. Switched to develop and issue persisted.

**Comment by Artymort** [comment]
Reproduced then fixed for me — I'm just moving from vim to (spac)emacs so maybe this is stating the obvious, but I'm putting this where I hoped to find it when I looked upon this issue.

With the following added to my .spacemacs: `dotspacemacs-additional-packages '(ess)` I reproduce the bug, namely that a `.R` file with only the following:
```r
print("Testing bindings.")
```
triggers the ESS[R] mode, `C-c C-n` executes a line but `SPC m is undefined`.

However if I now move the addition of the ess package **from `dotspacemacs-additional-packages` to `dotspacemacs-configuration-layers`** the `SPC m` bindings work as expected.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 901f35849)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree ess)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

Thanks for the work!

**Comment by mixmixmix** [comment]
I have the same issue on current release 0.200.13
emacs 25.3
OS: darwin
Emacs: 24.3
Spacemacs: 0.200.13
Spacemacs branch: master (582f9aa)
Graphic display: t
Distribution: spacemacs-base
Editing style: vim
Completion: helm

I rolled back all packages back to the dates when I remember ESS working correctly (roughly a month ago) but to no avail. I also changed to some old release (tag https://github.com/syl20bnr/spacemacs/tree/v0.200.12) but still doesn't work. I'm a bit confused by it because I had it workign soem time before.

I have `ess` in configuration layers.

Happy to try to debug the problem more. Not sure where to start though.

**Comment by mixmixmix** [comment]
I have now tried on development branch (https://github.com/syl20bnr/spacemacs/commit/e6811c83559797eadc9c94e752550357ad077fa9) and still the problem persists.

**Comment by mixmixmix** [comment]
I tested it now on ubuntu 18.04, with Emacs 25.2.2
Problem persists on both master and develop. 
This is all for ESS[R], for Julia all is fine.

@gdkrmr, Could you tell me how can I switch to an older version of ess?

**Comment by paullemmens** [comment]
I also still have that problem. For me the switch between spacemacs-additional-packages versus layer did not work. What did work was adding the `ess-r-mode` to the `dolist` in the last line below. Not sure whether this is a correct solution but for me it works.

```
  ;; R --------------------------------------------------------------------------
  (setq spacemacs/ess-config
        '(progn
           ;; Follow Hadley Wickham's R style guide
           (setq ess-first-continued-statement-offset 2
                 ess-continued-statement-offset 0
                 ess-expression-offset 2
                 ess-nuke-trailing-whitespace-p t
                 ess-default-style 'DEFAULT)
           (when ess-disable-underscore-assign
             (setq ess-smart-S-assign-key nil))

           (define-key ess-doc-map "h" 'ess-display-help-on-object)
           (define-key ess-doc-map "p" 'ess-R-dv-pprint)
           (define-key ess-doc-map "t" 'ess-R-dv-ctable)
           (dolist (mode '(ess-r-mode ess-julia-mode ess-mode))
```

**Comment by cole-brokamp** [comment]
This has been an ongoing problem for me too.  Based on @paullemmens comment above, I think that my setup was in "ess-r-mode" and for some reason was not also recognizing leader keys set for "ess-mode".  By setting the major mode (`M-x ess-mode`), I could tell that the keybindings were again working, but syntax highlighting was not.

I only use ess for R (not Julia or SAS), so my fix was to change 
```
(spacemacs/set-leader-keys-for-major-mode 'ess-mode
...
)
```
to
```
(spacemacs/set-leader-keys-for-major-mode 'ess-r-mode
...
)
```

The same change goes for `spacemacs/declare-prefix-for-mode` et al

**Comment by paupereira** [comment]
I still have this issue.
I have a fresh install of spacemacs.
