### ISSUE TITLE
Transparency 

### ISSUE THREAD

**Issue by brorbw** [syl20bnr/spacemacs#11375]
I propose another type of transparency than the current form. In the current form everything in the entire frame becomes transparent.
I would like to have only the background transparent. And maybe add a gaussian blur to the background as well. 
Here is a gif of the desired property. 
[GIF](https://media.giphy.com/media/1Qb2HKA548PDCxoPnU/giphy.gif)

**Comment by d12frosted** [comment]
Hi @brorbw,

Maybe it's a silly question, but what kind of transparency do we have now? Are you talking about Cocoa Emacs (e.g. GUI Emacs in macOS)?

**Comment by brorbw** [comment]
Not silly at all. I'm using the homebrew emacs-plus version with a --no-titlebar install. I don't think that it's an installation with cocoa.
The transparency right now is here everything, text and all becomes transparent. I would prefer a version where only the background becomes transparent.

**Comment by d12frosted** [comment]
> Not silly at all. I'm using the homebrew emacs-plus version with a --no-titlebar install. I don't think that it's an installation with cocoa.

It is Cocoa then 😸 This option just removes `NSWindowStyleMaskTitled` flag from the window.

> The transparency right now is here everything, text and all becomes transparent. I would prefer a version where only the background becomes transparent.

Right. Never used it actually 😸 The idea sounds cool.

**Comment by Migacz85** [comment]
That would be brilliant actually. It's even possible?

**Comment by LeeRuns** [comment]
I was looking for a solution. Does anyone have an answer on this? Would love to be able to read the background window while reading my code

**Comment by lebensterben** [comment]
The solution resides in the composer. Simply put, first use *nix OS and second use something like picom and set window transparency + blur.

Since this is not related to Emacs or Spacemacs, I'm locking this.
