### ISSUE TITLE
Can not configure 'shell' layer.

### ISSUE THREAD

**Issue by joakim-hove** [syl20bnr/spacemacs#11376]
#### Description :octocat:
Can not configure 'shell' layer.

#### Reproduction guide :beetle:
- Start Emacs
Add 'shell' to the list of configured layers in spacemacs.el

*Observed behaviour:*  :eyes: :broken_heart:
Get the following error message in the *Warnings* buffer: "Error (use-package): Cannot load xterm-color

If I try to invoke shell behaviour with e.g. SPC ' I get the error message: "No such file or directory shell-popup"

*Expected behaviour:* :heart: :smile:
Expecting shell layer to install correctly and afterwards shell functionality to work.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ibuffer csv html yaml javascript python helm auto-completion better-defaults emacs-lisp git django markdown shell
         (c-c   :variables c-c  -enable-clang-support 't)
         org)
```
- System configuration features: XPM JPEG TIFF PNG RSVG SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by beyondpie** [comment]
1. [xterm-color package files are blank ](https://stackoverflow.com/questions/41695678/cant-enable-spacemacs-shell-layer)
2. [terminal emacs color](https://stackoverflow.com/questions/7617458/terminal-emacs-colors-only-work-with-term-xterm-256color)

Hope the two links above make sense.

**Comment by joakim-hove** [comment]
> Hope the two links above make sense.

Thank your answering; but no - they did not make much sense. I do not have any  versions of either `xterm-color` or `shell-popup` in my `.emacs.d/elpa/` directory.
