### ISSUE TITLE
Freezes on fresh install after pressing yy in evil mode

### ISSUE THREAD

**Issue by greenfork** [syl20bnr/spacemacs#11374]
#### Description :octocat:
Emacs hangs when I press `yy` in evil mode to copy a line.

Sometimes it doesn't. Goes without freezing after doing editing for a while (or it might as well freeze).

Yanking/pasting is okay when in emacs mode.

#### Reproduction guide :beetle:
- `$ mv ~/.spacemacs ~/.spacemacs.bak`
- `$ rm -r ~/.emacs.d/elpa/`
- Start Emacs
- Choose vim-mode and any combination of spacemacs/spacemacs-base and ivy/helm
- Wait for all packages to be downloaded
- Press `yy`

*Observed behaviour:* :eyes: :broken_heart:
First keypress `y` turns cursor into edit mode, second press `y` hangs emacs.

*Expected behaviour:* :heart: :smile:
Should copy the line and not freeze.

#### System Info :computer:
- OS: OpenBSD 6.3
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK DBUS GCONF GSETTINGS NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by elenapan** [comment]
Having the same issue.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lua helm emacs-lisp neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

- Only this line in user-config:
```
(global-set-key (kbd "C-x C-b") 'ibuffer)
```

**Comment by Miciah** [comment]
This issue looks similar to https://github.com/syl20bnr/spacemacs/issues/6650 and https://github.com/syl20bnr/spacemacs/issues/8359.  Do you see the freeze if you specify the blackhole register by first pressing <kbd>"_</kbd> and then press <kbd>yy</kbd>?
