### ISSUE TITLE
Error during redisplay: (eval (spaceline-ml-helm)) signaled (error "Invalid face" spacemacs-nil-face) [Display not ready]

### ISSUE THREAD

**Issue by chriad** [syl20bnr/spacemacs#11373]
#### Description :octocat:
Error during redisplay: (eval (spaceline-ml-helm)) signaled (error "Invalid face" spacemacs-nil-face)
[Display not ready]

#### Reproduction guide :beetle:
- Start Emacs
- call `org-drill` on a org document or call `org-noter` on a buffer with a pdf document

*Observed behaviour:* :eyes: :broken_heart:
- org-drill does not start a drill session, instead [Display not ready] is echoed
- org-noter does not work and [Display not ready] is echoed

*Expected behaviour:* :heart: :smile:
org-drill should start a drill session in the current org buffer
org-noter should start an org-noter session 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv javascript
     (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp")
     ruby python html markdown ipython-notebook latex yaml ess common-lisp helm auto-completion better-defaults emacs-lisp git org pdf-tools
     (shell :variables shell-default-height 30 shell-default-shell "ansi-term" shell-default-position 'bottom)
     evil-commentary)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by sharad** [comment]
For debugging
in function spaceline-compile in spaceline.el
comment out

      (when spaceline-byte-compile
        (let ((byte-compile-warnings nil))
          (byte-compile target-func)))

or set spaceline-byte-compile to nil


then eval (spaceline-compile)

then try to reexecute

may get offending code lines.

It cold be in segments defined in spaceline-segments.el
