### ISSUE TITLE
mu4e layer often messes up windows

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#11389]
#### Description :octocat:
mu4e layer often messes up windows

very often window config gets screwed up in mu4e, for example: when you're in headers view and mail gets delivered. 

##### Prerequisites:
- installed and configured mu4e layer

##### Steps to repro:
- start mu4e layer
- open headers view
- open any message
- press `C-c C-u` - `mu4e-update-mail-and-index`

*Observed behaviour:* :eyes: :broken_heart:
- the windows all messed up after it's done delivering mail

#### Apparent cause:
it looks like it might be happening due to this:

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+email/mu4e/packages.el#L27-L35

I am not sure how to fix this properly, as a temporary measure I can suggest maybe creating a variable and do that only if it's set to true?

Personally I have disabled these hooks in my config (until I find better a way) like so:

```emacs-lisp
(dolist (h (mapcar #'derived-mode-hook-name '(mu4e-main-mode
                                              mu4e-headers-mode
                                              mu4e-view-mode
                                              mu4e-compose-mode))) 
  (remove-hook h #'spacemacs-layouts/add-mu4e-buffer-to-persp))
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml emacs-lisp lua javascript ag-haskell ag-clojure
     (html :packages
           (not pug-mode slim-mode))
     (markdown :packages
               (not mmm-mode)
               :variables markdown-live-preview-engine 'vmd)
     (shell-scripts :packages
                    (not fish-mode))
     (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
     docker emoji fasd helm imenu-list restclient search-engine treemacs
     (shell :packages
            (not eshell-prompt-extras eshell-z multi-term xterm-color)
            :variables shell-default-shell 'eshell)
     git
     (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t magit-repository-directories
                      '("~/DevProjects" "~/Sandbox")
                      magit-display-buffer-function 'magit-display-buffer-same-window-except-diff-v1)
     (github :packages
             (not magit-gh-pulls)
             :variables gist-view-gist t magithub-api-timeout 5)
     ag-colors ag-dired ag-exwm ag-general ag-web ag-lang-tools ag-org ag-mail)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```

```

**Comment by CharlesHD** [comment]
Couldn't reproduce on the same rev. 
I'm still on emacs 25.1
My mu4e version is 0.9.18

I'll try to reproduce on the same emacs version.

**Comment by yangsheng6810** [comment]
I can also confirm this issue. Currently I am using `(setq mu4e-split-view 'single-window)` as a (not so good but OK) workaround.
