### ISSUE TITLE
"Spacemacs encountered an error while loading your `/Users/<user>/.spacemacs' file"

### ISSUE THREAD

**Issue by raddevon** [syl20bnr/spacemacs#11385]
I get this error every time I launch Spacemacs now.

```
Spacemacs encountered an error while loading your `/Users/<user>/.spacemacs' file
```

This started occurring yesterday after I opened a second concurrent instance of Spacemacs. I have verified the .spacemacs file is at that location and looks normal. Predictably, none of my layers are install nor is my custom configuration available.

Once Spacemacs has launched, I can load my dotfile with `SPC-f e R` and everything appears to work as expected. It won't load on launch though.

How can I fix this?

**Comment by henriquenj** [comment]
There should be more information about the error on the home buffer (reachable by calling `SPC b h`) or the messages buffer. Please check these.

**Comment by raddevon** [comment]
Thank you, @henriquenj. I didn't see anything on the home buffer, but I found it by looking at the messages buffer. I had put some of my configuration in the root of my dotfile instead of inside the `dotspacemacs/user-config` function. Moved those into the function and all is well now.

I'm still not clear why I was able to load the dotfile with `SPC f e R`, but launching loads it properly now.
