### ISSUE TITLE
Some themes from the themes-megapack cannot be set as default

### ISSUE THREAD

**Issue by hersh-verthun** [syl20bnr/spacemacs#11380]
Default theme at startup is specified by changing the variable `dotspacemacs-themes` in the dotfile. When I specify **soft-stone** as one of the values of this variable it is applied as the default theme successfully. However when I specify **darktooth** or **gruvbox** it doesn't.

How can I fix this?

**Comment by duianto** [comment]
Here are two threads that talk about issues with darktooth and gruvbox:
Unable to use some themes (e.g. darktooth and gruvbox) #8090
No easy way to use custom themes #7373

The last comment on the first thread states that it's working on the develop branch. So if your on the master branch then you might want to try the develop branch.

Here's the develop branch documentation for "Choosing themes":
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#choosing-themes
