### ISSUE TITLE
default shell cant set hight properties and position.

### ISSUE THREAD

**Issue by brorbw** [syl20bnr/spacemacs#11388]
#### Description :octocat:
Using the system default shell
```
   '(shell :variables
           shell-default-shell 'shell
           shell-default-height 30
           shell-default-position 'top)
```
Ignores height and position. Using any of the other shells works fine, but the colors are all broken. Using the built in is the only shell that have proper colors. Im using zsh as the system default shell.
I can drag the size with the mouse but it cannot be set 

#### Reproduction guide :beetle:
- Start Emacs
- Set the default shell to be the system default
- Open a shell window, `[SPC ']`

*Observed behaviour:* :eyes: :broken_heart:
The shell pops op where ever and at half the size of frame its in. 

*Expected behaviour:* :heart: :smile:
Expected the shell to open in the top and with a height of 30.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((javascript :variables javascript-disable-tern-port-files nil)
 yaml octave html python swift rust scala latex ivy
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 better-defaults emacs-lisp git markdown
 (c-c++ :variables c-c++-enable-clang-support t)
 (spell-checking :variables enable-flyspell-auto-completion t)
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'top)
 xkcd
 (org :variables org-enable-reveal-js-support t org-projectile-file '"~/org/TODOs.org")
 themes-megapack
 (wakatime :variables wakatime-api-key "<<REMOVED KEY>>" wakatime-cli-path "/usr/local/bin/wakatime"))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by cipharius** [comment]
Try switching to develop branch, the issue should be fixed now.

**Comment by brorbw** [comment]
I am
