### ISSUE TITLE
gui breaks upon startup

### ISSUE THREAD

**Issue by emkoch** [syl20bnr/spacemacs#11392]
#### Description :octocat:
gui breaks upon startup

#### Reproduction guide :beetle:
- Start Emacs 
- Attempt to click links in *spacemacs* buffer

*Observed behaviour:* :eyes: :broken_heart:
\*spacemacs\* buffer only loads 147/149 at startup.
Get message:
`projectile--remove-current-project: Invalid function: (project (projectile-project-root))`
When attempt to click links in *spacemacs* buffer get the message:
`gui-get-primary-selection: No selection is available`

*Expected behaviour:* :heart: :smile:
Links take me to recently opened files etc.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: nil (rev. c7a103a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>

**Comment by macdanny** [comment]
I am also having this issue.

**Comment by d12frosted** [comment]
@emkoch can you please try on the latest `develop`? Plus make sure to upgrade all your packages.

**Comment by nasutiooon** [comment]
@d12frosted Still having this issue using `develop` branch and all-upgraded packages.

**Comment by nasutiooon** [comment]
Just now I'm able to install and run spacemacs okay using `master` branch. I think we can close this issue?

**Comment by emkoch** [comment]
I think we can close it. Upgrading packages seems to have fixed the problem.

**Comment by d12frosted** [comment]
Cool. Thank you both for coming back with an update 😸
