### ISSUE TITLE
helm eshell history kills emacs

### ISSUE THREAD

**Issue by MAliNaqvi** [syl20bnr/spacemacs#11390]
#### Description :octocat:
helm eshell history kills emacs

#### Reproduction guide :beetle:
- Start Emacs
- go into eshell `SPC '`
- type some commands eg. ls, cd ..,
- bring up helm eshell history `, H`
- select any command and emacs dies

*Observed behaviour:* :eyes: :broken_heart:
emacs dies on calling commands from eshell history

*Expected behaviour:* :heart: :smile:
emacs shouldn't die and eshell history command should appear in eshell

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql javascript csv html yaml
     (lsp :variables lsp-ui-remap-xref-keybindings t)
     (python :variables python-backend 'lsp python-test-runner 'pytest python-sort-imports-on-save t python-enable-yapf-format-on-save nil python-shell-interpreter-args "-i")
     docker helm
     (auto-completion :variables spacemacs-default-company-backends
                      '(company-files company-capf company-ansible)
                      auto-completion-tab-key-behavior 'cycle auto-completion-return-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
     better-defaults emacs-lisp git org
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
     markdown)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
I can only show the error that appears after

The log is too long and is posted here:

https://gist.github.com/MAliNaqvi/b99add3c84e9a7188e3d2162c5ca8c79

There was one occasion where I saw multiple emacs windows being opened which eventually lead to emacs being killed.

**Comment by CharlesHD** [comment]
Reproduced it with the same dev rep. It just spawned infinitely many emacs instance.

**Comment by CharlesHD** [comment]
Conclusion : Updating the helm package fixed the issue for me.

**Comment by MAliNaqvi** [comment]
@CharlesHD 
The snippet you wrote works well!

However, for the helm upgrade, I am using the version you specified:

```
helm is an installed package.

     Status: Installed in ‘helm-20181002.459/’ (unsigned).
    Version: 20181002.459
    Summary: Helm is an Emacs incremental and narrowing framework
   Requires: emacs-24.4, async-1.9.3, popup-0.5.3, helm-core-3.0
Required by: helm-xref-20180528.1516, helm-swoop-20180215.1154, helm-purpose-20170114.1636, helm-projectile-20180815.1514, helm-mode-manager-20151124.938, helm-make-20180602.1353, helm-gitignore-20170211.8,
               helm-flx-20180103.516, helm-descbinds-20180429.1456, helm-css-scss-20140627.25, helm-company-20180828.1612, helm-c-yasnippet-20170128.1542, helm-ag-20170209.1545,
               ace-jump-helm-line-20160918.1836
   Homepage: https://emacs-helm.github.io/helm/
Other versions: 20181002.459 (melpa).
```

**Comment by CharlesHD** [comment]
I'll try on another machine. Maybe I did some side effect change.

**Comment by MAliNaqvi** [comment]
No luck. :(

**Comment by MAliNaqvi** [comment]
I even tried a fresh install of spacemacs by removing .emacs.d folder, cloning this repo and switching to develop branch. The problem still persists.

**Comment by CharlesHD** [comment]
I can't reproduce it anymore even on fresh installs :'( . I'll inspect it further later. Meanwhile there is the quickfix.
