### ISSUE TITLE
File name completion doesn't work correctly in js2-mode when lsp is used as completions backend

### ISSUE THREAD

**Issue by jvalkeejarvi** [syl20bnr/spacemacs#11407]
#### Description :octocat:
File name completions are offered only after typing a `/` in file path.

#### Reproduction guide :beetle:
- Start Emacs
- Open javascript file
- Type in a javascript import statement, eg `import aa from './a'`

*Observed behaviour:* :eyes: :broken_heart:
No completions are offered even if current folder contains file(s) starting with `a`

File name completion only works just after typing `./`.

*Expected behaviour:* :heart: :smile:
Completions are offered

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: fixCompanyFilesJavascriptLsp (rev. 64413183f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html lsp
      (javascript :variables js2-basic-offset 2 js-indent-level 2 javascript-backend 'lsp)
      ivy
      (auto-completion :variables auto-completion-enable-help-tooltip t)
      emacs-lisp git markdown shell-scripts
      (org :variables org-want-todo-bindings t org-enable-github-support t org-enable-reveal-js-support t)
      (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by d12frosted** [comment]
PR was merged to develop. Please verify that it's fixed 😸
