### ISSUE TITLE
helm-projectile-find-file with symbolic link in project

### ISSUE THREAD

**Issue by lauccode** [syl20bnr/spacemacs#11411]
I create a simple project with ".projectile" with "!/" to be sure to find all with the command **"helm-projectile-find-file"** (shortcuts in spacemacs is 'SPACE p f')

If I use "helm-projectile-find-file" in a project, it seems this command is not able to find anything by following a "symbolic link" (file or directory).
Don't know if it is necessary to add specific settings to do that or if it is not possible.
It should be nice to have this option working ?

Regards

**Comment by d12frosted** [comment]
Hi @lauccode 

I haven't tested it myself, but you could try setting `projectile-generic-command` to the following value.

```
(setq projectile-generic-command "find -L . -type f -print0")
```

**Comment by lauccode** [comment]
Not working in a big project but working now in a small example that I did.
/home/name/projet_link/
-sub/
 --proj_link_dir/     (symbolic link made with ln -s target name)
  ---one_link.txt
  ---space.space
 .projectile

I did "projectile-invalidate-cache" to be regenerated in both cases.
Symbolic link are done the same in big project or small example.

In the case of the big project, symbolic link is going on a svn repository.
I already have this line in my **user-config**, otherwise the command doesn't stop to initializing cache:
`(setq projectile-svn-command "find . -type f -not -iwholename '*.svn/*' -print0")`
I tried with , but doesn't work too :
`(setq projectile-svn-command "find -L . -type f -not -iwholename '*.svn/*' -print0")`

**Comment by d12frosted** [comment]
You can disable cache by setting the value of `projectile-enable-caching` to `nil`. After a short glance on your `find` command, I don't see any obvious mistakes. Should work.

**Comment by lauccode** [comment]
Not working too.
But I can see a strange behavior.
emacs is in project.
When I open **neotree** and do a "helm-projectile-find-file", I can see "(2770 total)" in helm and at the top "Projectile files in current Dired buffer".
If I go on the symbolic link in **neotree**, I can see"(106557 total)" in helm and at the top "Projectile".  
This symbolic link directory is pointing on a svn directory with a .projectile on root because I use it also as a project. I removed this .projectile but it is not better.

**Comment by d12frosted** [comment]
@lauccode any luck with this?

**Comment by lauccode** [comment]
Hello d12frosted,
I always have the issue.
I should try with some another smaller svn repo or have a link on small directory.
Maybe svn repo is too big.
**In my config, I guess I should keep these both lines ? :**
```
(setq projectile-svn-command "find -L . -type f -not -iwholename '*.svn/*' -print0")
(setq projectile-generic-command "find -L . -type f -print0")
```

**Comment by lauccode** [comment]
I tested with a symbolic-link on smaller svn directory.
I got the same issue with **"helm-projectile-find-file"**. No file in symbolic link are found.
If I put the cursor on the symbolic link in **neotree** and do again **"helm-projectile-find-file"** I can see **"cache initializing"** only on the svn directory and no more in the original project. And so I can find files only on the svn directrory.
For me this is an issue because you can not find the files located by a symbolic link on svn directory.

**Comment by lauccode** [comment]
I tested with a small symbolic link on svn directory. I got the same issue.
I guess this is because this directory is not declared in git. But it should not be an issue because I have "!/" in .projectile.

**Comment by d12frosted** [comment]
@lauccode thank you for doing all these checks! Right now I have no other ideas and I haven't had a chance to test it myself. Hopefully will do it in the observable future. 

Meanwhile, if you have time/desire, you can check it with stock emacs + projectile. If it's reproducible like this, you can also ask for help in the projectile repository.

**Comment by lauccode** [comment]
Hello,
I fell back into an old problem. And so that is not only with symbolic links.
Now I can not find the files in a svn directory inside a projectile project.
In case someone will observe the same thing here.
