### ISSUE TITLE
mu4e icons?

### ISSUE THREAD

**Issue by simendsjo** [syl20bnr/spacemacs#11414]
This might not be the correct place for this issue. I have a standard installation of mu4e, but there are missing icons. I have all-the-icons installed too, which works fine for neotree.

![image](https://user-images.githubusercontent.com/351519/46750727-e56d6280-ccb8-11e8-9f2b-2a64ba0ca97d.png)

**Comment by d12frosted** [comment]
Pitty to hear 😿 

Just a shot in the sky - what font are you using and is it GUI or terminal?

**Comment by simendsjo** [comment]
> Just a shot in the sky - what font are you using and is it GUI or terminal?

GUI with SauceCodePro Nerd Font. Tried a couple of fonts I think. But I've only used `dotspacemacs-default-font` -- I don't know how to configure spacemacs/emacs with more fonts/fallbacks etc.

**Comment by olavpe** [comment]
@simendsjo Did you ever figure this one out? Same issue here

**Comment by simendsjo** [comment]
> @simendsjo Did you ever figure this one out? Same issue here
> 
> EDIT: Nevermind, found this https://github.com/stardiviner/mu4e-marker-icons

Not really, but it's easy set icons which you do have: https://github.com/djcb/mu/blob/master/mu4e/mu4e-headers.el#L237
