### ISSUE TITLE
Spacemacs: 'master' branch 0.200.13: Emacs freezes when switching themes with 'helm-themes'

### ISSUE THREAD

**Issue by dennismayr** [syl20bnr/spacemacs#11416]
Having several files open or none at all, Emacs freezes when switching themes via `helm-themes` typing `M-m T s` and choosing any theme.

It's not possible to `C-g` out of it, can't check any backtrace since there was no information to recover in the first place after `toggle-debug-on-quit`.

Active layers:

- html
- javascript
- typescript
- php
- sql
- python
- go
- shell-scripts
- nginx
- c-c++
- csharp
- csv
- java
- rust

Expected:
`M-m T s` brings up `helm` with the theme list, and choosing a theme activates it instantly.

What happens:
Selecting the theme freezes Emacs, only `Not enabling jit-lock: it does not work in indirect buffer` visible at the bottom.

Using the `develop` branch proved to break more things than what it fixed, so it's a no-go for now.

Edit: Emacs only freezes when there are open files.
It does not freeze when switching themes on the main window (*spacemacs* buffer) without opening any files yet.

**Comment by dennismayr** [comment]
I did some debugging that included:
- Removing `.emacs.d` and `.spacemacs`, and reinstalling Spacemacs from scratch
- Re-adding my personalized options to `.spacemacs` one line at a time, saving, restarting, opening files, switching themes.

I found out that only while editing a particular javascript/nodejs file, [server.js](https://github.com/dennismayr/codeburst_WeatherApp/blob/develop/server.js), Emacs freezes while switching themes with `M-m T n` or selecting any other with `M-m T s`.

Having 20+ other files did not freeze Emacs; formats vary from *Markdown* and plain text, to *java*, *javascript*, *php* and *html* files.

The conflicting *javascript* file is being edited under `js2-mode`, so I'll report this to the project owner.

**Comment by dennismayr** [comment]
I just tried setting *Js2 Dynamic Idle Timer Adjust* to `0.3` (` '(js2-dynamic-idle-timer-adjust 0.3)` in the dotfile), according to a similar problem described [here](https://github.com/mooz/js2-mode/issues/49#issuecomment-6063062), and the problem disappeared.

Why did this happen? It's beyond me.

**Comment by d12frosted** [comment]
@dennismayr wow! Though it's not a solution, I am glad you have found a workaround for this.

**Comment by dennismayr** [comment]
I'll test this on vanilla Emacs on a virtual machine during the weekend, as agreed with the package mantainer, to see if it's only *Spacemacs*-related, or a `js2-mode` problem.

**Comment by dennismayr** [comment]
Update:

setting *Js2 Dynamic Idle Timer Adjust* to **0.4** ('(js2-dynamic-idle-timer-adjust 0.4) in the dotfile) works better; I got a random freeze after setting it to *0.3*, but since I set it to *0.4*, no freezes have occurred for a whole day.

**Comment by dennismayr** [comment]
This isn't happening anymore since I switched to `develop`, so I'm closing the issue.
