### ISSUE TITLE
Show text colors in helm-swoop

### ISSUE THREAD

**Issue by danielwuz** [syl20bnr/spacemacs#1142]
Not sure if this is desirable for everyone, but I think it gives better user experience with colored text in `helm-swoop` buffer, especially when working with source code files. 

I have `(setq helm-swoop-speed-or-color t)` for couple months now. It works well with file over 10000 lines and I haven't experienced any performance issue.

Would you consider having `(setq helm-swoop-speed-or-color t)` in stock spacemacs?

**Comment by tuhdo** [comment]
I agree. I also enable colour for Helm Swoop and it's much better.

**Comment by syl20bnr** [comment]
Sure, PR welcome :-)

**Comment by danielwuz** [comment]
As in here https://github.com/syl20bnr/spacemacs/pull/1156. Thanks!
