### ISSUE TITLE
Change keybinding for helm-org-rifle

### ISSUE THREAD

**Issue by kepi** [syl20bnr/spacemacs#11420]
there was addition of helm-org-rifle in ff9fd1bcc3c74c2bdc04e9fe0241f7769aa0166d

Shortcut was set to `SPC m r` which is used during capture to refile captured buffer. I think this is missleading and shouldn't be used in that way. What about `SPC m R`?

**Comment by kepi** [comment]
Ok, one more point. This shouldn't be in `SPC m` because it should be on global key binding. You want to rifle through files from anywhere in emacs, not from org buffers.

**Comment by d12frosted** [comment]
Good point regarding global availability. Please see #11424 with the proposal.

**Comment by d12frosted** [comment]
Since this issue was introduced in `develop` branch and quickly fixed, I am closing the issue.

Thank you @kepi for staying on guard 😸 💯
