### ISSUE TITLE
shall we skip loading the default theme when using spacemacs in terminal to keep the appearance consistent

### ISSUE THREAD

**Issue by archerfeel** [syl20bnr/spacemacs#11428]
Hello, 
I usually use emacs in terminal rather than GUI. I found that all the color themes are not fully compatible with the terminal appearance, especially when setting iTerm background transparent. Since 
most terminals have their own theme settings, shall we skip loading the default spacemacs theme when in terminal? 
I add a `(if (display-graphic-p) ` in `core/core-spamces.el` to decide whether load the themes. But it's just my preference, I'm not sure what do others think, like the themes or not. 

it looks like:

<img width="1280" alt="screen shot 2018-10-13 at 00 05 25" src="https://user-images.githubusercontent.com/22611640/46881474-41351880-ce7e-11e8-9003-d8e38ea09275.png">

<img width="1280" alt="screen shot 2018-10-13 at 00 06 47" src="https://user-images.githubusercontent.com/22611640/46881726-f667d080-ce7e-11e8-8418-59e8a40a88c8.png">

thanks

**Comment by d12frosted** [comment]
Actually, maybe we should provide an option not to load any theme.
