### ISSUE TITLE
Shell popup broken in macOS 10.14 (Mojave)

### ISSUE THREAD

**Issue by drivasperez** [syl20bnr/spacemacs#11430]
#### Description :octocat:
Shell popup opens and immediately closes on OS X.
#### Reproduction guide :beetle:
- Start Emacs
- Checkout develop
- Add the "shell" layer in .spacemacs.
- Press space-' to open shell popup.

*Observed behaviour:* :eyes: :broken_heart:
Shell appears to pop up (Maybe? Hard to tell, more of a flicker) then immediately dies. Error message "Wrong type argument: commandp, spacemacs/shell-pop-nil".

Note: Using the command M-x "shell-pop" works fine. I also tried to reproduce on Ubuntu 18.04 and could not. Deleting and reinstalling Spacemacs didn't solve the issue.

*Expected behaviour:* :heart: :smile:
The shell should pop up.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1 ([Emacs for Mac OS X binary](https://emacsformacosx.com/))
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c0508d1f7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown neotree org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by d12frosted** [comment]
Might be related to https://github.com/syl20bnr/spacemacs/commit/79fe37c8b2c1da7f7383eeb18d21d5368acd2251

**Comment by d12frosted** [comment]
I will take a look tomorrow.

**Comment by drivasperez** [comment]
Thanks!

**Comment by drivasperez** [comment]
Rolling back to 2e0f495c47edf3af2e25a3c8f95386ba055b9208 has fixed the issue, so it does look like the bug is in 79fe37c8b2c1da7f7383eeb18d21d5368acd2251.

**Comment by cipharius** [comment]
Probably messed up the case statement, default case should be `(t shell-default-shell)`.

**Comment by drivasperez** [comment]
That does fix the issue, thanks! I submitted a PR with the patch.

**Comment by d12frosted** [comment]
The fix is in the `develop` branch. Thank you for quick reaction ❤️ 

Since this issue was introduced in `develop`, you can close it once you verify that it works.

**Comment by drivasperez** [comment]
Thanks, everyone.
