### ISSUE TITLE
How to disable purpose-mode in deer buffers

### ISSUE THREAD

**Issue by ishovkun** [syl20bnr/spacemacs#11469]
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>
I cannot figure out how to automatically disable purpose-mode for specific major modes
(deer to be specific).

I have tried:
```
(add-hook 'ranger-mode-hook (lambda () (purpose-mode nil)))
(add-hook 'deer-mode-hook (lambda () (purpose-mode nil)))
(add-hook 'dired-mode-hook (lambda () (purpose-mode nil)))
```
None of those seem to help.

#### Reproduction guide :beetle:
- Start Emacs
- Split windows vertically
- Open some buffer file in the left window
- Open deer in the right window
- Select a file in the deer buffer and press Return

*Observed behaviour:* :eyes: :broken_heart:
A new buffer opens in the other (left) window, which is freaking me out

*Expected behaviour:* :heart: :smile:
A new buffer is opened in the same window as the deer buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9865e7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(html javascript cmake helm markdown semantic auto-completion better-defaults emacs-lisp git
      (latex :variables latex-enable-auto-fill nil)
      python
      (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
      imenu-list ycmd
      (spell-checking :variables spell-checking-enable-by-default nil)
      (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
      syntax-checking ranger org deft shell version-control pdf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
1. For the question in the title: purpose-mode is a global mode, so you can't turn it off just for a specific major mode.

2. To turn off a mode you should pass `-1` instead of `nil`.

3. For fixing the bug: What command is bound to `RET` in deer mode? You can check with `SPC h d k RET`. Also, what is the major mode and purpose of the "file buffer"? If I know the exact command and window layout I can follow the code and find the problem. A "before" and "after" screenshots would also help.

**Comment by bmag** [comment]
@ishovkun ping

**Comment by ishovkun** [comment]
Sorry for the late response. I think setting (purpose-mode -1) solved the issue for me.
