### ISSUE TITLE
Can't run pt commands on windows box

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#1147]
Changes at commit eb527f stopped pt from working.  On windows machine, `spacemacs/helm-projectile-pt` and `spacemacs/helm-do-pt` show empty buffers now.

**Comment by syl20bnr** [comment]
I tried to debug it yesterday but was not successful. There is the same issue with ag I believe.
Tracked upstream in this issue: https://github.com/syohex/emacs-helm-ag/issues/99

**Comment by ralesi** [comment]
this is fixed now
