### ISSUE TITLE
It takes very very long to install packages after first installation

### ISSUE THREAD

**Issue by zchrissirhcz** [syl20bnr/spacemacs#11476]
I'm new to spacemacs and see some blog or forum threads says spacemacs is cool.

However, installing spacemacs takes too long time. It always stuck at contacting to melpa.org.

Why not ask users to choose his/her nearest mirror site to speed up?  Or maybe there is a way to modify it? Tell me if you know that, thanks.

**Comment by d12frosted** [comment]
I am sorry to hear that you have problems with the initial installation.

Please note that it takes some time to install all the packages, though it should not be stuck on contacting to `melpa.org`.

I don't remember all the quirks, but you can try setting `dotspacemacs-elpa-https` to `nil` in your `.spacemacs` file ([template](https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template#L86)).

You can also use a mirror if you have troubles connecting https://melpa.org or http://melpa.org. But let me ask an important question - what branch are you on? Is it `develop` or `master`?

**Comment by zchrissirhcz** [comment]
@d12frosted Thanks for your reply. I was using master branch. Is develop branch recommended?

**Comment by d12frosted** [comment]
@zchrissirhcz I can't say that `develop` is 'officially' recommended, but I usually advise people to use `develop`.

Also, I don't remember if you can use the mirror with `master` branch, so for this particular use case I would insist on using `develop`.

You can use [my own mirror of ELPA][1]. It has installation instructions for local and remote use, but let me duplicate the remote scenario:

```emacs-lisp
;; add this to `dotspacemacs/init' function
(setq configuration-layer-elpa-archives
      '(("melpa" . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/melpa/")
        ("org"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/org/")
        ("gnu"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/gnu/")))
```

  [1]: https://github.com/d12frosted/elpa-mirror
