### ISSUE TITLE
Helm doesn't load automatically for some commands

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#11479]
### Description

Helm doesn't load automatically for some commands, like rename `SPC f R` or when checking out a branch in magit `bb`. But if a helm buffer is opened with for example `SPC SPC` then the rename and checkout branch commands open in a helm buffer until the next time Emacs is restarted.

### Steps to reproduce

1. Start Emacs, and before opening a helm buffer like `SPC SPC`
2. Open `.spacemacs` by pressing `SPC f e d`
3. Open a rename prompt by pressing `SPC f R`

### Observed behavior

The minibuffer shows the rename prompt:

```text
New name: ~/.spacemacs
```

Helm doesn't seem to have been loaded yet, because if a helm buffer is opened with for example `SPC SPC` then `SPC f R` opens in a helm buffer, until the next time Emacs is restarted.

### Expected behavior

Helm should probably load when a command that uses the helm buffer is called.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7ccddbcec)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp git helm html markdown org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by sdwolfz** [comment]
I think this is the result of having helm deffered, @syl20bnr is the best person tho handle this as I remember this change was done to improve startup time.

**Comment by duianto** [comment]
This issue has been fixed by this PR:
Load helm before read-file-name and completing-read #11877
