### ISSUE TITLE
Scala mode, issue when using eldoc (void-function ensime-print-type-at-point)

### ISSUE THREAD

**Issue by Yiding-Sun** [syl20bnr/spacemacs#11482]
#### Description :octocat:
On scala mode, there is an issue when using eldoc
That's a small issue that can be fixed by changing a single line in *spacemacs/layers/+lang/scala/funcs.el*
```
(defun scala/enable-eldoc ()
  (setq-local eldoc-documentation-function
              (lambda ()
                (when (ensime-connected-p)
                  (ensime-print-type-at-point))))
  (eldoc-mode +1))
```
where *ensime-print-type-at-point* should be *ensime-type-at-point*

#### Reproduction guide :beetle:
- Start Emacs
- Add layer Scala
- Config Ensime
- Stop cursor on an expression for a while

*Observed behaviour:* :eyes: :broken_heart:
- An error happen that in the minibuffer (void-function ensime-print-type-at-point)

*Expected behaviour:* :heart: :smile:
- Print the type of the class

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control themes-megapack scala
      (scala :variables scala-indent:use-javadoc-style t)
      (scala :variables scala-enable-eldoc t)
      (scala :variables scala-auto-insert-asterisk-in-comments t)
      (scala :variables scala-auto-start-ensime t)
      (scala scala-indent:apply-indent-rules
             '(4)))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS THREADS

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-function ensime-print-type-at-point)
  (ensime-print-type-at-point)
  (progn (ensime-print-type-at-point))
  (if (ensime-connected-p) (progn (ensime-print-type-at-point)))
  (lambda nil (if (ensime-connected-p) (progn (ensime-print-type-at-point))))()
  eldoc-print-current-symbol-info()
  #f(compiled-function () #<bytecode 0x400dd3ff>)()
  apply(#f(compiled-function () #<bytecode 0x400dd3ff>) nil)
  timer-event-handler([t 0 0 500000 nil #f(compiled-function () #<bytecode 0x400dd3ff>) nil idle 0])
```

**Comment by beyondpie** [comment]
So you give the answer? If it is, why not send a PR?

**Comment by d12frosted** [comment]
@Yiding-Sun I second this. Please send a PR 😸

**Comment by bmag** [comment]
This is actually fixed in develop, but the code moved around a bit. Will post more later

**Comment by bmag** [comment]
The code was fixed and moved to `java` layer. From [layers/+lang/java/funcs.el](https://github.com/syl20bnr/spacemacs/blob/862d873fa8be9be7ce45fd704b595967ada2c6b5/layers/%2Blang/java/funcs.el#L93-L99):

```elisp

(defun spacemacs//java-setup-ensime-eldoc ()
  "Setup ENSIME eldoc."
  (setq-local eldoc-documentation-function
              (lambda ()
                (when (ensime-connected-p)
                  (ensime-type-at-point))))
  (eldoc-mode))
```

**Comment by d12frosted** [comment]
@bmag nice! I didn't know about that!
