### ISSUE TITLE
(Haskell Layer)Intero Keystrokes Dissapeared

### ISSUE THREAD

**Issue by OctavioElMagnifico** [syl20bnr/spacemacs#11495]
Since the last actualization, intero keystrokes stopped working.
While adding keys to the sequence, they are gone from the menu after <SPC + m>. For an example: <SPC + m + i> is registered as non assigned.

I checked the layer files and the combination is registered and assigned to intero commands.
I tested this in Arch and NixOs.

**Comment by OctavioElMagnifico** [comment]
Sorry for the lack of crucial data.

I've tried this in Arch and NixOs, with Emacs 25.3 and 26.1 and originally into develop branch.

Deleting the .emacs.d folder and cloning the stable branch didn't help, as didn't either deleting .spacemacs and regenerating it whith the questions spacemacs asks when you first start it.

I was succesfully using this functions in both emacs versions in both OSs before. I didn't pull pretty often, i will check later if there's a command to see some kind of pull's history in a git folder.

**Comment by d12frosted** [comment]
No problem.

> i will check later if there's a command to see some kind of pull's history in a git folder.

`git reflog` is your friend 😸 

---

But actually, I understand your problem now. I also don't see any `intero` bindings (for example, `intero-restart` that should be under `SPC m i r`). 

Thank you for reporting, I will check why it doesn't work. 

If you have any other valuable information, don't hesitate to share it.

**Comment by d12frosted** [comment]
Maybe it was a misconfiguration on my side, but I can't reproduce it with anymore. Even without my additional configurations.

Are you sure that your completion backend is `intero`? You can check it by `SPC h d v haskell-completion-backend RET`.

This is how I enable Haskell layer:

```emacs-lisp
   dotspacemacs-configuration-layers
   '(
     auto-completion
     (haskell :variables
              haskell-completion-backend 'intero)
     )
```

**Comment by rbobrowicz** [comment]
I had the same issue. I had my auto-completion variables set the way they are in the docs:

```
(setq-default dotspacemacs-configuration-layers
              '(auto-completion
                (haskell :variables haskell-completion-backend 'intero)))
```

Yet `SPC h d v haskell-completion-backend RET` would return `ghci` every time. I changed my dotfile to be:

```
(setq-default dotspacemacs-configuration-layers
              '(auto-completion :variables 
                                           haskell-completion-backend 'intero)))
```

And it started working. Not sure if the docs are incorrect, or if something changed in the auto-completion package or spacemacs variable loading.

This is on Emacs 25.2.2, master branch of spacemacs.
