### ISSUE TITLE
Gnus keys not working

### ISSUE THREAD

**Issue by StillerHarpo** [syl20bnr/spacemacs#11494]
#### Description :octocat:
Keys for gnus in group buffer are not working.  Normal vim key binding is
used instead, despite `spc-?` shows correct keys.

#### Reproduction guide :beetle:
- Start Emacs
- Add gnus layer
- start gnus
- press G

*Observed behaviour:* :eyes: :broken_heart:
cursor goes to last line

*Expected behaviour:* :heart: :smile:
Wait for second key for gnus command

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b8d555534)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(coq gnus haskell helm auto-completion better-defaults emacs-lisp git markdown neotree org
     (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill t)
     nixos
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD

**Comment by Compro-Prasad** [comment]
Use Emacs state for gnus. Vim keybindings aren't supported yet. gnus itself is modal.
