### ISSUE TITLE
helm-projectile-switch-project returns an error on windows clean build

### ISSUE THREAD

**Issue by GlitchedCode** [syl20bnr/spacemacs#11507]
#### Description :octocat:

I'm using a fresh spacemacs install on Windows. At startup, if i try to open an existing project using projectile via `helm-projectile-switch-project`, i get the error cited below. Back to a couple months ago, this error did not occur, but now i reproduce this error on two windows machines using the same `.spacemacs` file.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC p p`
- Choose any project directory containing a .projectile file

*Observed behaviour:* :eyes: :broken_heart:

`In ‘Projectile files’ source: '[a bunch of escaped characters that i am not able to copy and paste] [helm-current-buffer projectile-project-p buffer-live-p projectile-project-root projectile-current-project-files nil expand-file-name] 8]’ 
 (file-error "Setting current directory" "No such file or directory" "c:/Users/Giuseppe/Source/Repos/projectdir/\"tr\" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
/")`
The last part roughly translates to "no such file or directory".`

*Expected behaviour:* :heart: :smile:

Spacemacs shows a dired of the project's directory.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript html helm auto-completion git syntax-checking version-control
            (colors :variables colors-enable-nyan-cat-progress-bar t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by GlitchedCode** [comment]
I did some additional research, and it seems adding 
`  (setq projectile-indexing-method 'native)`
to my `user-config()` function in `.spacemacs` fixes the problem, even though it's somewhat slower.

**Comment by tuxayo** [comment]
hi :) since a package update in august, I have had issues to use `help-projectil-find-file` in a project that contains git repos in a git repo (I haven't done a particular setup for submodule, just created a repo in a folder where there were several repos) I don't know it that the cause.

```
In ‘Projectile files’ source: ‘#[0 \301 \205;\0r\302!\203\0\206\0p\211q\210\303 \304 \305\211:\2036\0@\262\306"BB\262A\262\202\0\211\237\266\204)\207 [helm-current-buffer projectile-project-p buffer-live-p projectile-project-root projectile-current-project-files nil expand-file-name] 8]’ 
 (file-missing "Setting current directory" "Dosiero aĊ­ dosierujo ne ekzistas" "/data/cloud/fatal: No url found for submodule path 'cryptocurrencies/ethereum/ethereum_talk' in .gitmodules
/")
```

And adding `(setq projectile-indexing-method 'native)` in `user-config()` in `.spacemacs` worked around the issue. Thanks :) I hope this other case can help.

**Comment by goughjo02** [comment]
> hi :) since a package update in august, I have had issues to use `help-projectil-find-file` in a project that contains git repos in a git repo (I haven't done a particular setup for submodule, just created a repo in a folder where there were several repos) I don't know it that the cause.
> 
> ```
> In ‘Projectile files’ source: ‘#[0 \301 \205;\0r\302�!\203�\0�\206�\0p\211�q\210\303 \304 \305\211�:\2036\0�@\262��\306���"B�B\262��A\262�\202�\0\211\237\266\204)\207 [helm-current-buffer projectile-project-p buffer-live-p projectile-project-root projectile-current-project-files nil expand-file-name] 8]’ 
>  (file-missing "Setting current directory" "Dosiero aĊ­ dosierujo ne ekzistas" "/data/cloud/fatal: No url found for submodule path 'cryptocurrencies/ethereum/ethereum_talk' in .gitmodules
> /")
> ```
> And adding `(setq projectile-indexing-method 'native)` in `user-config()` in `.spacemacs` worked around the issue. Thanks :) I hope this other case can help.

This did not work for me - i got an error in loading the .spacemacs file - could you please share the full user-config() block of code please? thank you

I am also on windows on a practically fresh install of emacs and spacemacs.

**Comment by JohnWillker** [comment]
> (setq projectile-indexing-method 'native)

Solve my problem, but made the process slower in large projects, especially when I run `SPC P F`

**Comment by barcharcraz** [comment]
Can this be set as default on windows until it's fixed upstream?

**Comment by untoreh** [comment]
projectile fails to index whenever any of the indexing commands returns an error, I encountered it when some files in the repo had wrong permissions.
To fix the command related to submodules you either fix the submodules mapping or 
ignore the errors with:
```
(setq projectile-git-submodule-command "git submodule --quiet foreach 'echo $path' 2>/dev/null | tr '\\n' '\\0'"
```

**Comment by ilkka** [comment]
To make this problem go away for me (Win10, emacs26) I customized `projectile-git-submodule-command` to

```
git submodule --quiet foreach 'echo $path'
```

That is, I removed the `tr` entirely. At least that made the immediate problem go away -- I don't really use submodules so I don't know if the command still works for that purpose.
