### ISSUE TITLE
Opt-in to native line numbers because it hogs up too much space

### ISSUE THREAD

**Issue by deb0ch** [syl20bnr/spacemacs#11504]
Native line numbers were very exciting because we know how dirty and underperforming `linum` implementation is, it can get slow on large files, it is implemented in elisp, bla bla bla...

The problem is, native line numbers take up extra space in your buffers compared to linum (5 in the included screenshots !) and [there is apparently no way around it](https://lists.gnu.org/archive/html/emacs-devel/2017-06/msg00413.html). I rarely open large files, and anyways Spacemacs now has a setting to disable line numbers in large files. I work on a small screen (13") so space matters, in this case a lot. I really don't care _how_ my line numbers are implemented as long as they provide the feature, which `linum` does better than native line numbers for now.

So I suggest to make native line numbers an opt-in, and disable it by default until this issue is addressed. If people here agree I will make a PR.

Here are some screenshots (I reproduced the same with a clean install and default configuration):

`linum`:
<img width="1474" alt="screen shot 2018-10-25 at 15 00 59" src="https://user-images.githubusercontent.com/6248219/47513967-a1b15600-d87f-11e8-8f04-0c1631047043.png">

native line numbers:
<img width="1474" alt="screen shot 2018-10-25 at 15 02 23" src="https://user-images.githubusercontent.com/6248219/47513951-9b22de80-d87f-11e8-8afd-e6e01dcca8de.png">

**Comment by sdwolfz** [comment]
Does `(setq-default display-line-numbers-width nil)` help? This should make the minimum reserved space as small as possible.

**Comment by deb0ch** [comment]
It reduces the number of extra spaces to three for this particular file, for other files it does nothing 😕

Best case is when there is only one extra space, which is still unsatisfactory.

I prefer a slow, badly implemented `linum` (where I never even notice the "slowness") that does not add this extra space to the theoretically more beautifully implemented `display-line-numbers` if it hogs even only one extra space in my buffers.
