### ISSUE TITLE
Misaligned html attribute indentation in web-mode

### ISSUE THREAD

**Issue by phardyn** [syl20bnr/spacemacs#11515]
#### Description :octocat:
After switching spacemacs branch from `master` to `develop`, the indentation of **html** attributes in **web-mode** doesn't seem to be working as expected. I've tested vanilla spacemacs and the result is the same as I experienced with my custom configuration.

Is this a bug, or is the indentation set like that on purpose?
How can I achieve expected indentation behavior?

Thanks for the help in advance!

#### Reproduction guide :beetle:
- Start Emacs
- Create ***.html** file
- Paste:
```html
<div id="b"
     class="a">
</div>
```
- Select all
- Press `<TAB>` (indent)
       
*Observed behaviour:* :eyes: :broken_heart:
Code is being indented to 4 spaces:
```html
<div id="b"
    class="a">
    ...
</div>
```

*Expected behaviour:* :heart: :smile:
Code is being indented to align the first attribute (id):
```html
<div id="b"
     class="a">
    ...
</div>
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2715b2de7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(html helm emacs-lisp neotree)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
[web-mode documentation](http://web-mode.org/) says:

> By default, tag attributes are indented like this:
> ```html
> <img src="pix.png"
>      class="noborder"/>
> ```
> You can force a fixed indentation with web-mode-attr-indent-offset
> ```html
> <img src="pix.png"
>   class="noborder"/>
> ```

When I do `M-m h d v` → `web-mode-attr-indent-offset` I get:

> web-mode-attr-indent-offset is a variable defined in ‘web-mode.el’.
> Its value is nil
> 
>   This variable is safe as a file local variable if its value
>   satisfies the predicate which is a byte-compiled expression.
> 
> Documentation:
> Html attribute indentation level.
> 
> You can customize this variable.
> 
> [back]

**Comment by duianto** [comment]
For me `TAB` aligns `class="a">` under `id="b"`, even when a newline is added before `id="b"`:
```html
<div
    id="b"
    class="a">
</div>
```

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f5243bb69)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp git helm html markdown multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by phardyn** [comment]
Thank you for verification @duianto!

For both **id** and **class** in a new line, I have the same result as you.
I've noticed that you use **vim editing style**, so I just checked if it would work as expected with that editing style, but I have the same result after a clean spacemacs/vim install (on the same commit - `f5243bb`). 
I've also verified vanilla emacs with only **web-mode** installed and the indentation works just fine.

**Comment by phardyn** [comment]
It's pretty weird issue ... 
After further investigation it seems like the problem is related to `web-mode-attr-indent-offset` variable. Even after changing it to `10` (either in `customize` or `dotspacemacs/user-config`) emacs keeps indenting the attribute to 4 spaces (again, I'm testing it on vanilla spacemacs).
After that `M-m h d v` → `web-mode-attr-indent-offset` results in:

> web-mode-attr-indent-offset is a variable defined in ‘web-mode.el’.
> Its value is 4
> Original value was nil
> Local in buffer header.component.html; global value is 10
> 
>   This variable is safe as a file local variable if its value
>   satisfies the predicate which is a byte-compiled expression.
> 
> Documentation:
> Html attribute indentation level.
> 
> You can customize this variable.
> 
> [back]

I've managed to "solve" the problem by adding this hook to `dotspacemacs/user-config`:
```elisp
(add-hook 'web-mode-hook
            (lambda () (setq web-mode-attr-indent-offset nil)))
```

Maybe someone will find this useful.

**Comment by westlywright** [comment]
I'm having this problem as well but @phardyn's solution doesn't work for me either.

**Comment by westlywright** [comment]
@phardyn I think I was having a conflict with editor config and found this issue 

https://github.com/editorconfig/editorconfig-emacs/issues/104

I added the following snippet to my `user-config` and im golden now
```
  (add-hook 'editorconfig-custom-hooks
    (lambda (hash) (setq web-mode-block-padding 0)))
```
