### ISSUE TITLE
Spacemacs Commit Message Style

### ISSUE THREAD

**Issue by delaanthonio** [syl20bnr/spacemacs#11526]
We currently don't have a standard commit message style. This leads to commits such as
1. [TravisCI] [docfmt] ignore master branch updates.
2. c-c++: remove c-c++-enable-c++11
3. Fix missing newline warning 

I suggest that we agree on standard conventions for commit messages so that we have a more uniform commit log. I recommend that we use the following style: [layer] change x

For example we could have a message like: [python] Add support for [lsp].

Since both python and lsp are layers, we know what layers the commit affects. Additionally, using the bracks "[" and "]" will highlight the contents in magit for extra emphasis. I've attached a screenshot of a recent spacemacs commit log in magit to illustrate my points.

![spacemacs_magit_log](https://user-images.githubusercontent.com/5178705/47669400-3ae2b400-db81-11e8-998a-c38bec61f548.png)

**Comment by d12frosted** [comment]
I kind of agree on that. Having great commit messages is really nice.

I wonder, how will it affect the PR merging speed 😸
