### ISSUE TITLE
change powerline color 

### ISSUE THREAD

**Issue by Yeonjj** [syl20bnr/spacemacs#11521]
I tried powerline active color setting and spaceline also. I changed everything that it shows me when I search 'powerline' and 'spaceline' in the customize group. But I couldn't change the color of this little thing.

<img width="242" alt="screen shot 2018-10-29 at 11 50 30 am" src="https://user-images.githubusercontent.com/15681271/47626983-2a2a4200-db71-11e8-98a3-957eb003a57a.png">

I guess it's set to 'skyblue' as a default. How can I set this color to a different one?

**Comment by d12frosted** [comment]
Hi @Yeonjj,

I think you are looking for [faces of spaceline](https://github.com/TheBB/spaceline#the-highlight-face). If you are using `vim` editing style, the interesting faces are [listed](https://github.com/TheBB/spaceline/blob/master/spaceline.el#L161) in `spaceline-evil-state-faces`.

**Comment by Yeonjj** [comment]
Closes #123

**Comment by Yeonjj** [comment]
Closes #11521

**Comment by d12frosted** [comment]
@Yeonjj neat! Glad you got the desired result :)
