### ISSUE TITLE
Aggressive-indent-mode interferes with reverting hunks

### ISSUE THREAD

**Issue by yuhan0** [syl20bnr/spacemacs#11523]
#### Description :octocat:
With the version-control layer and aggressive-indent-mode enabled, using `spacemacs/vcs-revert-hunk` triggers auto-indentation to happen directly after reverting the hunk, making it troublesome to restore a hunk to a previous revision with non-standard indentation.

#### Reproduction guide :beetle:
- Start Emacs
- Navigate to a version controlled lisp file
- Stage and commit some lines with non-standard indentation
- `M-x aggressive-indent-mode`
- Auto-indent the lines (SPC j =)
- Attempt to revert the hunk to original state (`SPC g . r` / `M-x spacemacs/vcs-revert-hunk`)

*Observed behaviour:* :eyes: :broken_heart:
The command appears to have no effect - because the reverted lines are immediately re-indented.
User has to manually toggle aggressive-indent-mode off and on between each revert operation, or revert using other indirect means (eg. magit status or vc-diff buffer)

*Expected behaviour:* :heart: :smile:
Hunk should be reverted _verbatim_ to the previous revision, without any post-processing or formatting performed on it afterwards (which would defeat semantics of reverting)

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: feature/improve-transient-states (rev. 49316261c)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion)
 (colors :excluded nyan-mode)
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-repeat-scope 'whole-visible evil-snipe-scope 'line evil-snipe-show-prompt t evil-snipe-spillover-scope 'whole-visible)
 (git)
 (github)
 (ibuffer :variables ibuffer-group-buffers-by 'modes)
 (irony)
 (ivy :variables ivy-initial-inputs-alist nil ivy-enable-advanced-buffer-information t)
 (lispy)
 (lsp)
 (pdf)
 (org :variables org-special-ctrl-a/e t org-export-preserve-breaks t org-html-validation-link nil org-enable-github-support t org-want-todo-bindings t evil-org-retain-visual-state-on-shift t org-html-htmlize-output-type 'css)
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 (syntax-checking)
 (theming)
 (version-control :variables version-control-diff-side 'left)
 (clojure :variables clojure-enable-clj-refactor t clojure-enable-sayid t clojure-enable-fancify-symbols nil)
 (c-c++)
 (csv)
 (emacs-lisp)
 (epub)
 (fsharp)
 (haskell)
 (html :variables sgml-quick-keys t)
 (hy)
 (javascript)
 (typescript)
 (markdown :variables markdown-command "pandoc" markdown-asymmetric-header t)
 (python :variables python-shell-interpreter "python3" python-shell-interpreter-args "-i"))
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS XWIDGETS LCMS2

#### Backtrace :paw_prints:
```

```

**Comment by smile13241324** [comment]
I have merged the PR, care to check if this solves your issue?

**Comment by yuhan0** [comment]
Yes it does, thanks for the merge!
