### ISSUE TITLE
`(setq window-combination-resize nil)` not working when placed under `user-config`. 

### ISSUE THREAD

**Issue by LucaMarconato** [syl20bnr/spacemacs#11537]
#### Description :octocat:
`(setq window-combination-resize nil)` does not work when placed under `user-config`. 
If instead you evaluate the code manually (for instance by using `M-:`), then the observed behavior and the expected behavior match.
A brief example on the effect of the value of `window-combination-resize`
When `window-combination-resize` is 't', then if you press `C-x 3`' twice, the windows will be balanced, as in `|xx|xx|xxxxxxxx|"`.
When `window-combination-resize` is `nil`, then if you press `C-x 3` twice, the windows will not be balanced, as in `|xxxx|xxxx|xxxx|`.

I prefer the first behavior since you can always balance the windows using `C-x  `.

#### Reproduction guide :beetle:
- Start Emacs
- check if `window-combination-resize` is `t`
- put `(setq window-combination-resize nil)` in your .spacemacs under `user-config`
- restart Emacs

*Observed behaviour:* :eyes: :broken_heart:
- `window-combination-resize` is still `t`

*Expected behaviour:* :heart: :smile:
- `window-combination-resize` should be `nil`

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults bibtex
                 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
                 helm emacs-lisp emoji ess git github html latex markdown org osx pdf-tools php python semantic shell shell-scripts spell-checking sql swift syntax-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
not relevant
```

**Comment by d12frosted** [comment]
I can't reproduce nor on `master`, nor on `develop`. Are you sure you've put it in `dotspacemacs/user-config`?

**Comment by LucaMarconato** [comment]
Yes, I can't reproduce it in `develop`, but I can in `master`.
I get the same behavior with `(setq undo-tree-visualizer-diff nil)` in the `develop` branch. Maybe the cause is the same and you will be able to reproduce it.
