### ISSUE TITLE
Shell (SPC a s i) history lost after restarting the shell

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#1153]

**Comment by TheBB** [comment]
I think this is just something that you have to deal with if you want to use shell. FWIW, `term` seems to work fine, and is better than shell in just about every way.

**Comment by StreakyCobra** [comment]
I agree with @TheBB, and as there was also no update from nearly 10 months, I'm closing it. Feel free to open a new one it this problem appears again.
