### ISSUE TITLE
Clojure layer refactorings are gone.

### ISSUE THREAD

**Issue by didibus** [syl20bnr/spacemacs#11531]
#### Description :octocat:
Clojure layer binding for refactoring are gone. And overall clj-refactor functions seem to be missing.

Specifically, pressing SPC m r just says prefix and then only c exists inside it, which says prefix, and has
unrelated bindings like clojure-convert-collection etc. No other bindings are found.

#### Reproduction guide :beetle:
- Start Emacs
- Activate clojure layer
- Go to a clj file in clojure-mode and cider-mode
- cider-jack-in into a Clojure REPL.
- Try SPC m r
- You'll see the bindings are gone.

*Observed behaviour:* :eyes: :broken_heart:
Seems all refactoring from clj-refactor are gone from the Clojure layer. Can't see any of its functions or bindings.

*Expected behaviour:* :heart: :smile:
I expect all clj-refactor functions to exist, and their bindings to be in SPC m r

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f5243bb69)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(html clojure ivy
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
      emacs-lisp git markdown org spell-checking
      (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left version-control-global-margin t))
```
- System configuration features: XAW3D XPM JPEG PNG SOUND ACL LIBSELINUX LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11

#### Backtrace :paw_prints:
```
NA
```

P.S.: Seems like report-issue-done also does not work anymore. So I had to copy paste this and manually create an issue.

**Comment by yuhan0** [comment]
I believe this was recently changed on the develop branch, now you will have to enable clj-refactor as a layer variable:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/clojure/README.org#enabling-sayid-or-clj-refactor

**Comment by sdwolfz** [comment]
@yuhan0 is correct, you need to expicitly enable `clj-refactor` in your config now.

**Comment by yuhan0** [comment]
Side note, maybe refactorings which are defined in clojure-mode should be bound to the appropriate keys even without cljr-refactor present.  

From the `cljr--all-helpers` list, that looks like the following:  

```emacs-lisp
("ci" . clojure-cycle-if)
("cp" . clojure-cycle-privacy)
("tf" . clojure-thread-first-all)
("th" . clojure-thread)
("tl" . clojure-thread-last-all)
("ua" . clojure-unwind-all)
("uw" . clojure-unwind)
```

I'll probably submit a PR sometime soon to move the relevant bits from `init-cljr-refactor` over to `init-clojure-mode`, and also update the documentation of the keybindings to reflect this :)

**Comment by didibus** [comment]
I find it strange though that there's no more name for the category under `SPC m r c`, so in which-key they show up as `+prefix`.

But thanks for the answer.

**Comment by d12frosted** [comment]
@didibus it's easy to fix. PR is welcome ;)
