### ISSUE TITLE
Coq layer spuriously auto-expands words from abbrev

### ISSUE THREAD

**Issue by ineol** [syl20bnr/spacemacs#11539]
#### Description :octocat:
In the coq layer, when going from insert mode to normal mode using the escape key, words are autocompleted. For instance, if I write "I", with the cursor after the I, and then press espace, I get "INTRO". Or "Sec" becomes "Section", and do on.

#### Reproduction guide :beetle:
- Start Emacs
- open a .v Coq file
- write text
- press escape

*Observed behaviour:* :eyes: :broken_heart:
Some words are autocompleted using snippets it seems.

*Expected behaviour:* :heart: :smile:
My text should be left alone

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cb4a15608)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript csv python yaml html markdown coq ocaml java haskell shell rust scala go
            (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode flycheck-gcc-language-standard "c++14" flycheck-clang-language-standard "c++14")
            git
            (auto-completion :variables auto-completion-complete-with-key-sequence "jk" auto-completion-tab-key-behavior 'complete auto-completion-return-key-behavior 'complete)
            (latex :variables latex-enable-auto-fill t)
            spell-checking syntax-checking org themes-megapack ivy)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by ineol** [comment]
Actually, the problems comes from the coq-abbrev part of proof general. If I comment out the part of PG which builds the abbrev table, the problem seems to be gone. It looks like when I hit ESC, emacs uses the abbrev table to expand nearby letters/words.

**Comment by bmag** [comment]
Please see discussion at https://github.com/syl20bnr/spacemacs/issues/8853 and https://github.com/ProofGeneral/PG/issues/216. Apparently, putting `(setq evil-want-abbrev-expand-on-insert-exit nil)` in user-config or putting `(setq coq-mode-abbrev-table '())` in user-init will work around the issue.

**Comment by ineol** [comment]
Great, thank you!
