### ISSUE TITLE
How to change the tooltip color given by flyspell(?)

### ISSUE THREAD

**Issue by LucaMarconato** [syl20bnr/spacemacs#11534]
I have installed Spacemacs today and I am experimenting the python layer. It works fine but the error s in the code are displayed in a color that is difficult to read. How can I customize the colors of the tooltip? I think that the tooltip is displayed by `flyspell`, but correct me if I am wrong.

<img width="212" alt="screenshot 2018-10-31 at 19 30 58" src="https://user-images.githubusercontent.com/2664412/47810580-f3f0ec00-dd43-11e8-9ec0-eacf2a1a4310.png">

**Comment by bmag** [comment]
Note the tooltip is displayed by `flycheck`, not `flyspell`. To customize the color, you need to find the correct face (see `customize-face` and `customize-apropos-faces` commands), and then you can customize it either through the customize interface, or by enabling the `theming` layer and setting `theming-modifications` variable in user-init (see the layer's README).

However, I'm pretty sure what you're seeing is not the intended color (the popup looks completely different on my machine, even has an icon).
