### ISSUE TITLE
Flycheck disabled by default for csharp

### ISSUE THREAD

**Issue by vanceism7** [syl20bnr/spacemacs#11540]
#### Description :octocat:
Flycheck is disabled by default when working in csharp

#### Reproduction guide :beetle:
- Create a new cs project using `dotnet new console -n MyApp`
- Start Emacs
- Open cs file

*Observed behaviour:* :eyes: :broken_heart:
No code errors are being shown. When looking at `flycheck-verify-setup`, it says the following:

> Syntax checkers for buffer Program.cs in csharp-mode:
> 
>   csharp-omnisharp-codecheck
>     - may enable: yes
>     - predicate:  nil
> 
> Flycheck Mode is disabled. Use SPC u M-x flycheck-disable-checker to enable
> disabled checkers.  

I can enable flycheck using `M-x flycheck-mode`, and it works fine from there.
But it should be enabled by default.

*Expected behaviour:* :heart: :smile:
cs file opens and flycheck is showing me code errors

#### System Info :computer:
- OS: gnu/linux -- Manjaro Arch
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2715b2de7)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml csharp
      (haskell :variables haskell-completion-backend 'intero)
      helm
      (auto-completion :variables auto-completion-return-key-behavior 'cycle auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
      emacs-lisp git markdown neotree
      (shell :variables shell-default-height 40 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by bmag** [comment]
You need to enable the `syntax-checking` layer

**Comment by vanceism7** [comment]
Darn it! Sorry, I didn't realize that. My syntax checking was working fine for my other layers (haskell, typescript), so I didn't realize there was another step. Thanks for your help!
