### ISSUE TITLE
Tweaks to useful/useless buffers behavior

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#11545]
To make them really useful (no pun intended 😄 ) here what we need to do:
- [x] do not filter `SPC TAB` behavior, i.e. `SPC TAB` always display the previous buffer not matter its type (already done by @deb0ch)
- [x] fix helm buffer list to filter out useless buffers
- [ ] fix ivy buffer list to filter out useless buffers
- [ ] make sure `SPC b` and `SPC p` avoid useless buffers
- [x] create a new key binding `SPC b U` to list all useless/special buffers 
- [x] ~~move `SPC b u` to `SPC b U` (undo/reopen killed buffers)~~
- [ ] mark all special buffers starting with `*` as useless and remove the magit buffers entry
- [ ] Update documentation about special buffers in `DOCUMENTATION.org` and `FAQ.org`

**Comment by deb0ch** [comment]
Hey, I just have some interrogations about what you just wrote:
1. what do you mean by `make sure SPC b and SPC p avoid useless buffers` ? Those are prefixes to a lot of keybindings
2. what do you mean by `mark all special buffers starting with * as useless and remove the magit buffers entry` ? That we should consider all buffers starting with `*` as useless and make magit buffers not useless anymore ? If so, that would be the contrary of what you did by removing everything from the useless buffers list and what we did recently adding the magit buffers so I don't understand 😕 
3. I think it would make more sense to keep `reopen-killed-buffer` under the more accessible `SPC b u` and have the `list-useless-buffers` under `SPC b U`, as by definition they are useless so we would want them listed less often than a true feature like an `undo`

**Comment by henriquenj** [comment]
I'm also in favor of not changing `SPC b u` from the current `reopen-killed-buffer`. Maybe `SPC b B` for listing useless buffers?

**Comment by deb0ch** [comment]
`SPC b B` is already bound to `spacemacs-layouts/non-restricted-buffer-list-helm` for listing all buffers in all persp's layouts and it makes a lot of sense there.

`SPC b U` is not taken at the moment, is very mnemonic and makes sense, what do you not like about it ?

**Comment by henriquenj** [comment]
I have nothing against using `SPC b U`, I only suggested `SPC b B` as an alternative. But given your last comment it seems to me that `SPC b U` is indeed our best option.

**Comment by syl20bnr** [comment]
> I think it would make more sense to keep reopen-killed-buffer under the more accessible SPC b u and have the list-useless-buffers under SPC b U, as by definition they are useless so we would want them listed less often than a true feature like an undo

FWM :+1:
