### ISSUE TITLE
The new pixel-scroll-mode is unusable

### ISSUE THREAD

**Issue by ishovkun** [syl20bnr/spacemacs#11549]
#### Description :octocat:
The new pixel-scroll-mode is unusable (super-slow).
I beleive it is related to the spaceline (according to web forums).

#### Reproduction guide :beetle:
- Start Emacs
- M-x pixel-scroll-mode
- Perform a scroll with a mouse/touchpad

*Observed behaviour:* :eyes: :broken_heart:
Pixel scrolliing is super sluggish

*Expected behaviour:* :heart: :smile:
Scrolling is buttery-smooth as in modern editors

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f5243bb69)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(html javascript cmake helm markdown semantic auto-completion better-defaults emacs-lisp git
      (latex :variables latex-enable-auto-fill nil)
      python
      (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
      imenu-list ycmd
      (spell-checking :variables spell-checking-enable-by-default nil)
      (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
      syntax-checking ranger org deft shell version-control pdf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by Eiyeron** [comment]
Also happens here
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: origin/develop (rev. 152d41e7c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown multiple-cursors neotree org syntax-checking version-control chicken-dotfiles semantic perforce asm rust html javascript plantuml graphviz)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by NightMachinary** [comment]
I opened an upstream [bug report](https://mail.google.com/mail/u/1/#sent/QgrcJHsbkfHVtHPGfkBFHclLXDrzQwqJWVB).
