### ISSUE TITLE
multi-term: paste (p) not working properly in normal mode

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#1155]
![ezgif com-crop](https://cloud.githubusercontent.com/assets/6420591/7151020/d453ca62-e32c-11e4-8dbc-846d915917c2.gif)

**Comment by syl20bnr** [comment]
Do you have an example of the issue ? What's the behavior you encounter ?

**Comment by CestDiego** [comment]
I have this too... the behaviour is kinda like I can see the pasted stuff...but when I hit `return` it's as if there was no text there.

**Comment by xged** [comment]
I think its a more wider problem with normal mode in multi-term as I seen glitches here and there.

**Comment by CarlQLange** [comment]
Yep, same behavour as @CestDiego here. Very annoying.

**Comment by alex-glv** [comment]
Can confirm same behavior. Doesn't seem to work for holy-mode, either.

**Comment by stormpat** [comment]
I have issues with paste too, but the issue is very hard to reproduce, basically sometimes i cannot paste to emacs (from my browser/other app) and sometimes its works normally.

Im on the gui emacs-mac port, and on osx. Using the latest versions.

**Comment by trishume** [comment]
I'm pretty sure the reason for this is that terminals use a custom function to send input while passing through vt emulation and they bind all the normal letter keys to send input. Paste bypasses that and just inserts directly in the buffer, which is supposed to represent the output after running through vt emulation.

I have a feeling this represents a fundamental incompatibility with most editing commands and while it will be possible to fix special cases like paste manually, it will never work for all editing commands.

**Comment by frankdj412** [comment]
Agree with @trishume that you need to rebind all the letters to send input. For the case of "paste", I rebind the paste (p) command:
```elisp
(evil-define-key 'normal term-raw-map
  "p" 'term-paste)
```
Hope this can help you.

**Comment by syl20bnr** [comment]
Thank you @frankdj412 I put your fix in develop.
