### ISSUE TITLE
after update spacemacs to latest, the dotspacemacs-line-numbers config not work any more.

### ISSUE THREAD

**Issue by hackrole** [syl20bnr/spacemacs#11559]
#### Description :octocat:
after upate spacemacs to the new version, the dotspacemacs-line-modes config not working.
I configure it like below:
```elisp
   dotspacemacs-line-numbers '(:relative t
                               :disabled-for-modes dired-mode
                                                   doc-view-mode
                                                   markdown-mode
                                                   org-mode
                                                   pdf-view-mode)
```
it work before I update spacemacs, now the line-mode active in text-mode/org-mode.
especilly in pdf-view-mode, which make pdf-view really stuck.

#### Reproduction guide :beetle:
- Start Emacs
- open a pdf-file with pdf-view-mode
- the emacs will stuck, and the pdf-view-buffer will have line number

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(graphviz vimscript
          (erc :variables erc-server-list
               '(("irc.freenode.net" :port "6697" :ssl t :nick "hackrole" :password "freeme")))
          helm
          (syntax-checking :variables syntax-checking-use-original-bitmaps t)
          (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior nil auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory "~/.spacemacs.d/snippets" auto-completion-enable-snippets-in-popup t spacemacs-default-company-backends
                           '(company-files company-capf)
                           require-final-newline nil auto-completion-enable-help-tooltip t)
          themes-megapack imenu-list
          (dash :variables helm-dash-browser-func 'eww)
          git github
          (plantuml :variables org-plantuml-jar-path "/usr/share/plantuml/plantuml.jar" plantuml-jar-path "/usr/share/plantuml/plantuml.jar")
          salt vimscript
          (markdown :variables markdown-live-preview-engine 'vmd)
          org
          (ranger :variables ranger-show-literal t ranger-show-hidden t ranger-cleanup-on-disable t ranger-parent-header-func 'ranger-parent-header-line ranger-cleanup-eagerly t ranger-parent-depth 2 ranger-ignored-extensions
                  '("mvk" "iso" "mp4"))
          (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh")
          emacs-lisp
          (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save t flycheck-flake8-maximum-complexity 8)
          ipython-notebook scheme c-c   erlang
          (go :variables go-tab-width 2 go-fmt-command "goimports")
          haskell html
          (typescript :variables typescript-fmt-on-save t)
          javascript react lua plantuml elixir clojure scala ruby yaml rust typescript javascript sql docker pdf-tools chrome
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 THREADS

**Comment by simonpintarelli** [comment]
I noticed the same problem (same dotspacemacs-line-numbers as above), but it was not related to updating spacemacs, but because of upgrading elpa packages. Downgrading org-plus-contrib to version 20181029 fixed it for me.

**Comment by hackrole** [comment]
@simonpintarelli how to downgrading package? I cannot find any doc about this.

**Comment by simonpintarelli** [comment]
you can downgrade to a version which was installed previously using `M-x configuration-layer/rollback`

**Comment by hackrole** [comment]
It reports error: No rollback slot available.

**Comment by jvanheugten** [comment]
I have the same issue:
```
dotspacemacs-line-numbers '(:enabled-for-modes prog-mode
                               :disabled-for-modes org-mode
                               :relative t)
```
The above doesn't turn off line numbers in `org-mode`.

Also it seems that there is a typo in the Spacemacs docs, since it says in some cases `dotspacemacs-lines-numbers` instead of `dotspacemacs-line-numbers`.

**Comment by jvanheugten** [comment]
Why is this closed? It is still unresolved in my case. If this happens everytime we update packages, this must be fixed somewhere, right?

**Comment by hackrole** [comment]
@jvanheugten after update spacemacs, it seems work for me now, so I closed this issue.

**Comment by SadFoxDave** [comment]
Do you guys still have this problem? I'm unable to solve this.
