### ISSUE TITLE
print('hey', end='.') gives me SyntaxError: invalid syntax [E999]

### ISSUE THREAD

**Issue by LucaMarconato** [syl20bnr/spacemacs#11563]
#### Description
The following line of code is underlined in red by the syntax checker `print('hey', end='.')`.

Since the problem is similar to the one described here 
https://github.com/syl20bnr/spacemacs/issues/2064 I give you the output of `flake8 --version`, called from the `*shell*` buffer within Emacs: `3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.5 on Darwin`.

#### Reproduction guide
- Start Emacs
- Create a `.py` file
- Write `print('hey', end='.')` in it

*Observed behaviour:*
The line is underlined in red and the error you get is `SyntaxError: invalid syntax [E999]`

<img width="319" alt="screenshot 2018-11-08 at 11 40 18" src="https://user-images.githubusercontent.com/2664412/48193596-19d14e80-e34b-11e8-9179-7e58bee79e3d.png">

*Expected behaviour:*
No error should be presented

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f5243bb69)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(javascript auto-completion better-defaults bibtex
            (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
            (cmake :variables cmake-enable-cmake-ide-support t)
            helm emacs-lisp ess git github html latex markdown org osx php python semantic shell shell-scripts spell-checking sql swift syntax-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace
Not relevant

**Comment by tko** [comment]
It might help to know the flycheck setup for the buffer (`SPC e v`) as flake8 and other tools may be invoked indirectly and get python2 that way.

**Comment by carmenbianca** [comment]
In user-config:

      (setq python-shell-interpreter "/usr/bin/python3")

**Comment by LucaMarconato** [comment]
You are right guys, it was using Python 2. Here is the output

```

  python-flake8
    - may enable:         yes
    - executable:         Found at /usr/bin/python
    - configuration file: Not found
    - `flake8' module:    Found at "/Library/Python/2.7/site-packages/flake8/__init__.pyc"

  python-pylint
    - may enable:         Automatically disabled!
    - executable:         Found at /usr/bin/python
    - configuration file: Not found
    - `pylint' module:    Missing

  python-pycompile
    - may enable: yes
    - executable: Found at /usr/bin/python

  python-mypy
    - may enable:         Automatically disabled!
    - predicate:          t
    - executable:         Not found
    - configuration file: Not found
```

@carmenbianca apparently that line does not solve the problem, now I get the following error when opening `.py` files: `Importmagic and/or epc not found. importmagic.el will not be working.`

**Comment by LucaMarconato** [comment]
After closing and reopening Emacs I was not able to open `.py` files anymore, getting the following error when doing.

<img width="495" alt="screenshot 2018-11-09 at 00 47 58" src="https://user-images.githubusercontent.com/2664412/48234280-3efca600-e3b9-11e8-8920-99ba40269261.png">

Since this made Emacs freeze I had to the line `(setq python-shell-interpreter "/usr/bin/python3")`

**Comment by carmenbianca** [comment]
Perhaps also try:

      (setq flycheck-python-pycompile-executable "python3")
