### ISSUE TITLE
develop: broken helm-git-grep-run-default-action

### ISSUE THREAD

**Issue by vbauerster** [syl20bnr/spacemacs#11569]
#### Description :octocat:
develop: broken helm-git-grep-run-default-action

#### Reproduction guide :beetle:
- Start Emacs
- Press `space g /` or `space g *` inside git project

*Observed behaviour:* :eyes: :broken_heart:
Wrong type argument: listp, helm-git-grep-run-default-action

*Expected behaviour:* :heart: :smile:
helm search prompt

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9da5da1d2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org multiple-cursors
      (git :variables git-magit-status-fullscreen t)
      (version-control :variables version-control-diff-side 'left)
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip 'manual)
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      (spell-checking :variables enable-flyspell-auto-completion t spell-checking-enable-by-default nil)
      html markdown treemacs yaml javascript lsp
      (go :variables go-backend 'lsp go-tab-width 4 go-format-before-save t gofmt-command "goimports" go-use-gometalinter t go-use-test-args "-race -timeout 10s" godoc-at-point-function 'godoc-gogetdoc)
      protobuf docker themes-megapack dash semantic
      (ranger :variables ranger-show-literal nil ranger-show-preview t ranger-show-hidden t ranger-cleanup-eagerly t ranger-cleanup-on-disable t ranger-ignored-extensions
              '("mkv" "flv" "iso" "mp4"))
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
      shell-scripts
      (rust :variables rust-format-on-save t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by gcentauri** [comment]
If I start from a clean `.spacemacs`, enable `git` in the layers and press `SPC g /` the helm prompt opens for me.  Currently on commit https://github.com/syl20bnr/spacemacs/commit/4912b54f24db78bbc88cb03015cde361eaffaf01

I also installed all of the layers you have listed and am still able to run the `helm-git-grep` commands.

**Comment by vbauerster** [comment]
After I did manual clean up https://github.com/syl20bnr/spacemacs/issues/11568#issuecomment-439504447, problem with git blame gone, however this one still broken.

**Comment by felipernb** [comment]
In my setup this issue seems to come an go in different updates, any clue on what might be happening?

**Comment by gcentauri** [comment]
I still haven't been able to reproduce it. If you have it occur perhaps you can turn on the debug trace on error? Then possibly we could instrument the function in question with edebug and figure out what the cause is.

**Comment by vbauerster** [comment]
I works as expected now, with latest develop.

**Comment by erichlf** [comment]
I am having this problem [`eval: Wrong type argument: listp, helm-git-grep-run-default-action
`] also... I have run `rm -rf cache/* elpa/*`, but it didn't help at all.
