### ISSUE TITLE
ccls can not be started

### ISSUE THREAD

**Issue by meziberry** [syl20bnr/spacemacs#11574]
#### Description :octocat:
<<ccls can not be started>>

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION>>

*Observed behaviour:* :eyes: :broken_heart:
<<c-c++: No c-c++-lsp-cache-dir specified: defaulting to /xxx/.emacs.d/.cache/lsp-ccls
Error from the Language Server: /xxxxx/linux/fs/aio.c is being indexed. (Server Not Initialized) [2 times]
/xxxxx/linux/: lsp-ccls has exited (illegal instruction: 4)>>

*Expected behaviour:* :heart: :smile:
<<ccls is working correctly>>

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a3cac69fb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy python auto-completion better-defaults emacs-lisp git ibuffer unicode-fonts neotree colors chinese gtags
     (org :variables org-projectile-file "TODOs.org")
     (shell :variables shell-default-height 30 shell-default-position 'right)
     spell-checking syntax-checking
     (c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-ccls c-c++-lsp-sem-highlight-method 'font-lock c-c++-lsp-executable "/usr/local/bin/ccls" c-c++-lsp-sem-highlight-rainbow t)
     scheme multiple-cursors pdf
     (osx :variables osx-dictionary-dictionary-choice "Simplified Chinese-English" osx-command-as 'super))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by sdwolfz** [comment]
Ping @cormacc or @MaskRay as they ar the people who can potentially help with this. Might be an upstream issue.

**Comment by cormacc** [comment]
That looks to me like an upstream issue alright - try raising against the ccls project

**Comment by cormacc** [comment]
A quick google search for 'Illegal instruction 4' throws up few hits. Maybe you need to recompile ccls for your version of OS X? I'm on linux mostly. Haven't tried ccls on OS X myself yet, but cquery worked OK when I did a few months ago. Or could just be something in your codebase / project setup that's not going down well with the language server.

https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

**Comment by myrgy** [comment]
You may try to install ccls from brew. Saw similar issue in ccls bug tracker.

**Comment by meziberry** [comment]
@myrgy 's method is useful. it seems that 'tag 20180924' have a problem.  Thank you  for everyone.

**Comment by myrgy** [comment]
@meziberry , happy that my advice was useful. I assume it worth o close issue since it looks like non-spacemacs issues, but upstream.
