### ISSUE TITLE
multiple-cursors layer overrides magit key binding

### ISSUE THREAD

**Issue by sei40kr** [syl20bnr/spacemacs#11578]
`g r` refreshes magit status, but it is now overridden by `multiple-cursors` layer.

**Comment by sdwolfz** [comment]
Make sure you update to the latest develop and have this commit 4036556fb5b120cccb577ab88cdddfd18bf57ee7 that fixed the problem.

**Comment by sei40kr** [comment]
@sdwolfz Thanks! I'm closing this.
