### ISSUE TITLE
Best way to modify existing layer with personal options?

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#1157]
I have more settings that I use in Auctex than are used in the included layer, and I was wondering if there was a preferred way to use the existing layer but add my settings to it. Off the top of my head, I could
 
1. Modify the auctex layer directly and create a personal layer based off of it. 
2. Include the extra settings in .spacemacs
3. Add a private layer and use it in conjunction with the official one. 

I am currently using 2, because 1 seems to not be a good long term solution and I had trouble getting 3 to work correctly. I think 3 is the neatest solution, but it's not clear to me how to set it up correctly. Should I just use a function in packages.el like my-layer/post-init-auctex? What if the code in the auctex layer is deferred? It would be  nice to be able to extend use-package in the auctex layer, but in my own layer. Is that possible?

Thanks

**Comment by CestDiego** [comment]
:+1: bump... I would like to do the same with the org layer...and I would guess most people would do...but I'm not sure whether you can override a use-package call :(

**Comment by jupl** [comment]
I haven't had an issue with modifying existing layers yet between `setq`, `setq-default`, `add-hook`, `remove-hook`, `with-eval-after-load`, etc. at disposal.

**Comment by CestDiego** [comment]
@jupl it's not about whether it's possible. It's about having everything tidy and organised somewhere. And what is the suggested way of doing it and where.

**Comment by sooheon** [comment]
Same situation here with the clojure layer. Maybe we just work around the config-layer :variables?

**Comment by justbur** [comment]
Was looking through use-package and found this: https://github.com/jwiegley/use-package/blob/master/use-package.el#L86-L105

Looks like there are predefined hooks for use-package that could be used to extend an existing use-package declaration.

**Comment by syl20bnr** [comment]
These hooks have been added specifically at my request for spacemacs, I have yet to incorporate them and play a bit with them to write a documentation.
