### ISSUE TITLE
[question] why does insert start always with 2 leading spaces?

### ISSUE THREAD

**Issue by Huxpro** [syl20bnr/spacemacs#11581]
I came from Vim and was writing Haskell, but I found `i`nsert always start with two leading spaces. 

Besides, do we have any forum/chats for asking questions? not sure is this the proper place to do so.

**Comment by jamartin9** [comment]
@Huxpro 
There is a gitter chat (taken from the README.md) <a href="https://gitter.im/syl20bnr/spacemacs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_c\
    ontent=badge"><img src="https://badges.gitter.im/Join Chat.svg" alt="Gitter"></a> 

Unfortunately I lack any insight into your actual question on insert spacing. Out of curiosity what branch are you seeing the behavior on and have you updated your packages recently?
