### ISSUE TITLE
[Feature Request] Add fixjson support

### ISSUE THREAD

**Issue by sei40kr** [syl20bnr/spacemacs#11580]
I want `fixjson` in Spacemacs. There're no packages for Emacs yet.

`fixjson` corrects syntax errors automatically, and format whole the buffer.
The official repo has a GIF that shows how it works.
https://github.com/rhysd/fixjson

**Comment by jrmiller82** [comment]
If there's no package for emacs yet, then I think your issue here may be a bit premature.

**Comment by sei40kr** [comment]
https://github.com/syl20bnr/spacemacs/pull/12970
