### ISSUE TITLE
Refactor prettier

### ISSUE THREAD

**Issue by sei40kr** [syl20bnr/spacemacs#11595]
I added Prettier formatter few months ago.

I added prettier layer and added a key binding in the same way as web-beautify does, a formatter layer adds a binding for specific modes.
But prettier layer doesn't add a binding for typescript-mode. `spacemacs/typescript-format` directly selects a formatter to use, and run it.

I like the way `spacemacs/typescript-format` does.

It doesn't confuse developers and make them easier to add a new formatter.
Every language layer should have a format function like typescript, I think.

**Comment by sei40kr** [comment]
https://github.com/syl20bnr/spacemacs/blob/4912b54f24db78bbc88cb03015cde361eaffaf01/layers/%2Blang/typescript/funcs.el#L128

**Comment by rocha** [comment]
@sei40kr It would be nice if prettier also worked with `html` files in `web-mode`.
