### ISSUE TITLE
line numbers causing scalling to go nuts

### ISSUE THREAD

**Issue by yanniknelson** [syl20bnr/spacemacs#11603]
When i set dotspacemacs-line-numbers to t in the .spacemacs file when i load back in and zoom in and zoom out using ctrl x + or ctrl x - after doing so if i scroll or use the arrow keys the text moves either to the right or left making it unusable, using ctrl x 0 usually resets everything though

**Comment by kommen** [comment]
I think this needs more information (emacs version, spacemacs version, etc.), please report bugs with `spacemacs/report-issue` (`SPC h I`), which automatically collects this and more.

**Comment by ssbothwell** [comment]
I'm having the same issue. 

I was also unable to submit a report using `spacemacs/report-issue` due to `C-c C-c` being unbound. This is an essentially stock spaceemacs config. 

Here is my system information:

```
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml helm auto-completion emacs-lisp git org syntax-checking version-control
      (haskell :variables haskell-completion-backend 'intero)
      idris javascript themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
```

**Comment by duianto** [comment]
There has been a couple of reports about this issue. They are linked in this comment:
https://github.com/syl20bnr/spacemacs/issues/12401#issuecomment-498431109

It's been fixed on the `develop` branch, where Spacemacs uses the Emacs 26 built in line numbers.

My next comment in that thread:
https://github.com/syl20bnr/spacemacs/issues/12401#issuecomment-499036378
has a workaround for the `master` branch.

**Comment by ssbothwell** [comment]
Thanks, switching to `develop` fixed this for me.

**Comment by duianto** [comment]
The `C-c C-c` submit issue key binding has also been fixed on the `develop` branch.
