### ISSUE TITLE
[Feature Request] [Layer] [swift] Add LSP support for swift

### ISSUE THREAD

**Issue by fiveNinePlusR** [syl20bnr/spacemacs#11604]
there is a recent LSP server for the swift language [here](https://github.com/apple/sourcekit-lsp)

It would be nice to have swift support for this.

**Comment by sdwolfz** [comment]
I think you need to ask someone from https://github.com/emacs-lsp to implement a package for swift, after which we can integrate it.

**Comment by fiveNinePlusR** [comment]
alright, reported upstream https://github.com/emacs-lsp/lsp-mode/issues/472

**Comment by fiveNinePlusR** [comment]
Thanks for that. i'll see if that works in the meantime.

**Comment by fiveNinePlusR** [comment]
they have something working here: https://github.com/danielmartin/emacs-sourcekit-lsp

not sure what the final plan is for it but it's up and running there.

**Comment by sdwolfz** [comment]
We might be able to use that when it's in MELPA.

**Comment by fiveNinePlusR** [comment]
seems like they are moving it to a different repository and hopefully will be up on melpa shortly.

**Comment by sdwolfz** [comment]
Yaay for @yyoncho.

**Comment by yyoncho** [comment]
I asked @danielmartin to move it under `emacs-lsp` - https://github.com/emacs-lsp/lsp-mode/issues/472#issuecomment-440949055 . If user @danielmartin agrees I could do that and do the onboarding melpa request.

**Comment by yyoncho** [comment]
I just want to note that thanks to @danielmartin there is debugger support for swift in `dap-mode`. Here it is screenshot:
<img width="1212" alt="swift" src="https://user-images.githubusercontent.com/13259670/50609052-4632c280-0ed7-11e9-8ec7-23962a600edc.png">

**Comment by dato** [comment]
Could this be reopened, please? lsp-sourcekit is now [available on melpa](https://melpa.org/#/lsp-sourcekit). (Many thanks to all involved.)

**Comment by johalun** [comment]
Do we have any updates on this? Trying to get things working by manually configuring but no luck so far. I'm on Linux btw.

**Comment by yyoncho** [comment]
@johalun what is your issue when you do `M-x lsp` in swift mode file?

**Comment by johalun** [comment]
> @johalun what is your issue when you do `M-x lsp` in swift mode file?

Got `LSP[Disconnected]` in status bar.

**Comment by johalun** [comment]
I got it working! I think what was missing was load-path to lsp-sourcekit folder.

**Comment by electricRGB** [comment]
@johalaun would you mind posting all the code you used to get it working? Is you `.spacemacs` online by any chance? I'm trying to do this right now and having trouble.

**Comment by lebensterben** [comment]
@electricRGB https://emacs-lsp.github.io/lsp-sourcekit/

**Comment by electricRGB** [comment]
@lebensterben Yep I followed all that and can't seem to get it to work.
Whenever I open a .swift file, I get `File mode specification error: (file-missing Cannot open load file No such file or directory lsp-sourcekit)`

My [.spacemacs](https://github.com/electricRGB/.dotfiles/blob/main/RC_Files/.spacemacs) (note: whether I use the current way to set `lsp-sourcekit-executable` or give it a hardcoded path, I get the same error)

**Comment by johalun** [comment]
@electricRGB I installed the emacs part of sourcekit from elpa and added this to user-config. Make sure you use the correct path for the your installs.
```
  (add-to-list 'load-path "/home/johalun/.emacs.d/elpa/27.1/develop/lsp-sourcekit-20210404.1624")

  (eval-after-load 'lsp-mode
    (progn
      (require 'lsp-sourcekit)
      (setq lsp-sourcekit-executable
            "/home/johalun/swift/swift/usr/bin/sourcekit-lsp")))

  (add-hook 'swift-mode-hook (lambda () (lsp)))
```

**Comment by schell** [comment]
Any updates here? It's been a couple years - maybe things have progressed?

**Comment by smile13241324** [comment]
Adding lsp support should be straight forward but I may need someone to test this on a mac though

**Comment by schell** [comment]
@smile13241324 I would, but I'm no longer using spacemacs :(

**Comment by smile13241324** [comment]
LSP support for swift has been added. Someone with an apple would need to test this though.
