### ISSUE TITLE
multiple-cursors keys conflict with evil-mode keys

### ISSUE THREAD

**Issue by vbauerster** [syl20bnr/spacemacs#11607]
In latest dotfile template (`space f e D`) `multiple-cursors` layer is on by default.
But its keys `C-t` conflicts with evil-mode:
[![Screenshot-2018-11-14-at-16-07-25.png](https://i.postimg.cc/761yHrbd/Screenshot-2018-11-14-at-16-07-25.png)](https://postimg.cc/Ppq7ycWQ)
[![Screenshot-2018-11-14-at-16-26-15.png](https://i.postimg.cc/Twv6v32n/Screenshot-2018-11-14-at-16-26-15.png)](https://postimg.cc/qtwY8037)

So conflict keys should be either fixed/changed or `multiple-cursors` layer should be off by default.

**Comment by sdwolfz** [comment]
The keybinding is defined in the upstream package: https://github.com/gabesoft/evil-mc/blob/master/evil-mc.el#L96

I'll have to take a look and see how to change that in our config. Any suggestion for a replacement key binding? (also for any other you see conflicting)

**Comment by vbauerster** [comment]
Sorry for late reply, I dont use mc, just dicovered this conflict after it was enabled by default. So not sure what is the best way to resolve.
