### ISSUE TITLE
How to use spacemacs-dark theme instead of builtin one?

### ISSUE THREAD

**Issue by aruku7230** [syl20bnr/spacemacs#11611]
The builtin spacemacs-dark theme in `core/libs/spacemacs-theme` have [a issue](https://github.com/syl20bnr/spacemacs/issues/11575), so I want to use the latest version of spacemace-dark theme provided by [spacemacs-theme repository](https://github.com/nashamri/spacemacs-theme)

I tried `dotspacemacs-additional-packages '(spacemacs-theme)`, It should load spacemacs-theme from melpa but did not.

Run `M-x package-install spacemacs-theme` seem works, but I think it's not the way of spacemacs.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp org)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by bet4it** [comment]
Why not use the develop branch of spacemacs?

**Comment by seminaoki** [comment]
I want to use a stable version. Does develop branch stable enough?

**Comment by zer09** [comment]
@seminaoki based on my experience, develop branch is stable, so far I didn't get any trouble using it even I am always keep pulling the latest commit. But I am always keeping a backup of my ```.emacs.d``` in-case anything bad happen or some package update got problems.

**Comment by seminaoki** [comment]
I will give develop branch a try to see if it slove this issue.
