### ISSUE TITLE
html's web-mode and TAB

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#1161]
If I hit `TAB` while in normal or insert mode to expand a div I get the error message.
```
[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'
```
In addition, I get something along the lines of the following with the cursor at `*`:
```html
<div>
  $1
</div>*
```
<hr>
Now, if I run the command `emmet-expand-yas` (the command that `TAB` runs) from helm-M-x then it expands and moves the cursor properly without an error message:
```html
<div>
  *
</div>
```

**Comment by CestDiego** [comment]
I also get this when openning a javascript file for example typing: `for` and then pressing tab gives no signal of working...using `M-x yas-expand-snippet` gives the same error message:
```
[yas] `yas-expand-snippet' needs properly setup `yas-minor-mode'
```

**Comment by louy2** [comment]
:+1: , have the html problem as well.

**Comment by louy2** [comment]
Posted a fix. Seems `local-set-key` does not play nice with evil.
