### ISSUE TITLE
ess-disable-underscore-assign variable uses deprecated ess functionality

### ISSUE THREAD

**Issue by leezu** [syl20bnr/spacemacs#11617]
`ess-disable-underscore-assign` introduced via https://github.com/syl20bnr/spacemacs/pull/9102 relies on functionality deprecated in ESS 18.10. The deprecated functionality may be removed from ESS soon and as melpa follows ESS master branch, spacemacs should be adapted.

@jackkamm

**Comment by leezu** [comment]
Thanks for your prompt reply @jackkamm . `(setq ess-smart-S-assign-key nil)` seems to be the way to go forward, I opened a PR for that #11620.

I am however not sure, why `ess-smart-S-assign` is still called by ESS upon entering `_` in some buffer. This causes the message:

>  `ess-smart-S-assign` is an obsolete command (as of ESS 18.10); use `ess-insert-assign` instead.

Do you have any insight about this? Or might this warning be a bug in ESS?

**Comment by jackkamm** [comment]
From briefly looking at the docs just now -- maybe ESS is finally getting rid of the horrid default to make `_` insert `<-`, and requiring users to manually bind `ess-insert-assign` instead if they want this behavior? Not sure though. Might be worth pinging the ESS maintainers about, or looking through their issues/manual on github to see if there's any discussion of this.
