### ISSUE TITLE
htmlfontify-buffer bugged on first run

### ISSUE THREAD

**Issue by dschrempf** [syl20bnr/spacemacs#11627]
#### Description :octocat:
When executing `htmlfontify-buffer` for the first time, an error occurs.
Subsequent executions work normally.

#### Reproduction guide :beetle:
- Start Emacs
- Run `SPC SPC htmlfontify-buffer`.

*Observed behaviour:* :eyes: :broken_heart:

    Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
      jit-lock--run-functions(1 9097)
      jit-lock-fontify-now()
      hfy-force-fontification()
      htmlfontify-buffer()
      funcall-interactively(htmlfontify-buffer)
      call-interactively(htmlfontify-buffer record nil)
      command-execute(htmlfontify-buffer record)
      helm-M-x(nil #("htmlfontify-buffer" 0 18 (match-part "htmlfontify-buffer")))
      funcall-interactively(helm-M-x nil #("htmlfontify-buffer" 0 18 (match-part "htmlfontify-buffer")))
      call-interactively(helm-M-x nil nil)
      command-execute(helm-M-x)

*Expected behaviour:* :heart: :smile:
The welcome buffers gets converted into HTML.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: spacemacs-develop (rev. 4dbe241ac)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults git gtags helm ibuffer neotree ranger shell spell-checking semantic spacemacs-layouts version-control
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support nil)
                 emacs-lisp ess haskell html
                 (javascript :variables tern-command
                             '("node" "~/.node_modules_global/bin/tern"))
                 latex markdown nginx php python rust shell-scripts vimscript yaml erc twitter mu4e my-org syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  jit-lock--run-functions(1 9097)
  jit-lock-fontify-now()
  hfy-force-fontification()
  htmlfontify-buffer()
  funcall-interactively(htmlfontify-buffer)
  call-interactively(htmlfontify-buffer record nil)
  command-execute(htmlfontify-buffer record)
  helm-M-x(nil #("htmlfontify-buffer" 0 18 (match-part "htmlfontify-buffer")))
  funcall-interactively(helm-M-x nil #("htmlfontify-buffer" 0 18 (match-part "htmlfontify-buffer")))
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

```

**Comment by theHedster** [comment]
Ubuntu 18.04.4
Emacs 26.3 (from PPA)

M-x htmlfontify-buffer halts with this error message --
   wrong-type-argument number-or-marker-p nil

Please advise what further information you need and how to obtain it. I am not a Lisp or any other kind of programmer but can follow clear instructions.

**Comment by duianto** [comment]
It doesn't seem to be limited to Spacemacs.

Because it also happens when Emacs is started without any configurations:
- `emacs --quick`
- `C-x b *Messages*  RET`
(Typing `Mes` and pressing `TAB` at the `Switch to buffer` prompt, should complete `Mes` to `*Messages*`)
- `M-x htmlfontify-buffer RET`
