### ISSUE TITLE
Disable "parentheses" matching / highlighting in rust layer

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#11622]
Whatever the library being used in the rust layer to match / highlight parentheses, it freezes spacemacs for seconds way too often, making it IMO unusable.

Reproducer: Try removing or adding new braces to any big file containing lots of blocks, like the unix module in the libc crate: https://github.com/rust-lang/libc/blob/master/src/unix/mod.rs

"Highlighting parentheses" is not an acceptable feature if it costs 10 second freezes.

**Comment by gnzlbg** [comment]
> What's your hardware?

Macbook Air mid-2012 (8GB RAM, 1.8 Ghz Dual Core i5)

**Comment by jrmiller82** [comment]
I think a 6-year old laptop is more your problem. I think these problems go away with a more powerful processor. Have you tried on a newer computer or desktop to see if the problem goes away?

**Comment by gnzlbg** [comment]
Just to triple check, are you really suggesting that a ~2Ghz dual core with 8 Gb of RAM is not powerful enough to edit files containing 1000 lines of code ?

**Comment by jrmiller82** [comment]
Yes. Spacemacs (emacs) isn't terribly efficient, and Rust (in any editor with code completion) is going to be running CPU-heavy background processes. It's not how many lines of code are in the specific file; it's how hard to compile your entire crate in rust. I have a 2013 MBPro that struggles to keep up with Rust development in spacemacs, and that likely has way more oomph than a 2012 Air.

**Comment by jrmiller82** [comment]
There. It's likely blocking trying to call racer.

**Comment by gnzlbg** [comment]
Hmm, that makes sense. I have the `racer` emacs package disabled like this:

```elisp
   ;; A list of packages that will not be installed and loaded.
   dotspacemacs-excluded-packages '(evil-mc racer)
```

Should I enable the package and install racer ?
