### ISSUE TITLE
Provide a layer equivalent to pretty-fonts

### ISSUE THREAD

**Issue by mdedetrich** [syl20bnr/spacemacs#11639]
As can be seen by https://github.com/tonsky/FiraCode/wiki/Emacs-instructions providing font-ligatures to emacs is far more complicated than what it should be.

I think it makes sense to provide a layer analogous to https://github.com/ekaschalk/.spacemacs.d/blob/master/layers/display/local/pretty-fonts/pretty-fonts.el so that people can easily configure font-ligatures, what do you guys think?

**Comment by syl20bnr** [comment]
Indeed that would be nice :+1:

**Comment by georgreen** [comment]
@mdedetrich [doom emacs](github.com/hlissner/doom-emacs/blob/develop/modules/ui/pretty-code) do have a rather complete implementation, including mathematics notation symbols. I would have taken up the port but I'm new to this stuff.

**Comment by mdedetrich** [comment]
@georgreen The link you posted doesn't work, care to update it?

**Comment by georgreen** [comment]
> @georgreen The link you posted doesn't work, care to update it?

done

**Comment by ezmiller** [comment]
@georgreen I'm new to spacemacs/emacs (coming from vim). Is the link you posted above somethign that can be used to get FiraCode working with spacemacs?

**Comment by howdoicomputer** [comment]
@ezmiller It'll probably be easier to follow the wiki instructions for FiraCode to enable ligatures. It's mostly copy and pasting a bunch of lisp into your user-config.

As for this thread, I am in love with https://github.com/ekaschalk/.spacemacs.d/tree/master/layers/display

**Comment by absentmindedguy** [comment]
Is there any progress on this? I've been trying to get ligatures working and it just doesn't seem to want to play ball... I'm not of the opinion that adding a bunch of elisp should be required t oget this kind of thing working, in vs code it's just a checkbox... Maybe I am missing a package that makes this very easy?

**Comment by carusog** [comment]
I started to use Spacemacs very little weeks ago, and I found super difficult to set up font ligatures from Fira Code in it. Not knowing how to set up .spacemacs correctly, I ended up choosing emacs-mac that with a one line of settings, enables ligatures immediately.
I strongly believe that this should be a default feature in modern Spacemacs. I, like most of us, use it, in fact, just for the "out of the box" features, and is a great entry point to Emacs wonderful features.
Modern development use ligatures quite commonly lastly. It would be great to have this feature built-in to the distribution.

**Comment by ekaschalk** [comment]
Ligatures are coming to Emacs FYI. Harfbuzz is integrated on Emacs master and Eli says it is the final step to (true) ligature support.

https://old.reddit.com/r/emacs/comments/byddvm/emacsdevel_harfbuzz_is_now_available_on_master/

**Comment by hyiltiz** [comment]
My `SPC h d s` includes HarfBuz, but how do I use it/enable it? Using Fire Code or Hasklig didn't render `=>` as expected after an emacs restart. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 30250403a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy gtags ibuffer auto-completion better-defaults
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     git ess pandoc spell-checking syntax-checking version-control pdf semantic typography finance erc
     (ranger :variables ranger-show-preview t ranger-show-hidden t ranger-cleanup-eagerly t ranger-cleanup-on-disable t ranger-ignored-extensions
             '("mkv" "flv" "iso" "mp4"))
     shell-scripts emacs-lisp octave haskell go
     (latex :variables latex-enable-folding t)
     lua python scheme ruby javascript purescript vimscript
     (org :variables org-enable-reveal-js-support t)
     markdown html graphviz yaml csv)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER LCMS2 GMP

**Comment by Kazark** [comment]
This PR was merged: https://github.com/syl20bnr/spacemacs/pull/13921 I think that is at least partly relevant.

**Comment by hyiltiz** [comment]
To anyone interested, it seem `unicode-fonts` provides `unicode-fonts-ligature-modes` and `unicode-fonts-enable-ligatures`, which may be how the new support may be used.

**Comment by hyiltiz** [comment]
Is this really resolved? If so, we should just close it before the bot seals the issue.

**Comment by hyiltiz** [comment]
`unicode-fonts` breaks `lsp-ui`? Maybe we need to file an issue there and close this one?

**Comment by lebensterben** [comment]
It's long known and reported.
