### ISSUE TITLE
Create dart layer in SpaceMacs

### ISSUE THREAD

**Issue by aswinmohanme** [syl20bnr/spacemacs#11631]
With the current growing popularity of Flutter it would be really awesome if the dart-layer was supported in spacemacs. Having dart support would be the first step towards supporting Flutter.

A lot of work has been done here I think but looks abandoned.
https://github.com/syl20bnr/spacemacs/pull/11266

I'm a newbie here previously from vim and SpaceMacs Rocks :D

**Comment by bltavares** [comment]
@aswinmohanme the layer has been updated to match the latest version of `dart-mode`. You may download it locally while it is not merged on the `develop` branch.

**Comment by aswinmohanme** [comment]
I have copied the files from your dart-layer branch into my private layers. Everything except auto complete works. 

Here is my configuration
```
     (dart :variables
           dart-sdk-path "/home/aswinmohanme/Flutter/flutter/bin/cache/dart-sdk/"
           dart-analysis-server t
           dart-format-on-save t)
```

**Comment by duianto** [comment]
The PR:
Introduces Dart layer #11266
is now on the develop branch.

**Comment by GLodi** [comment]
I just wanted to point out that if someone sees JSON-readable errors being thrown while using it, verify that the SDK path is correct.

**Comment by GLodi** [comment]
Does anyone know how to disable the docs that show up under the powerline?

<img width="1132" alt="Screenshot 2019-04-16 at 18 25 19" src="https://user-images.githubusercontent.com/4631114/56227251-95ef6100-6064-11e9-94f4-045a2a9b7555.png">

I have the following under configuration-layers:

    (dart :variables                                                                                                                       
             ;; dart-sdk already in PATH                                                                         
             dart-enable-analysis-server t                           
             dart-format-on-save t)  

And the following under user-config:

    (add-hook 'dart-mode-hook 'lsp)

It's just really annoying to see the powerline constantly going up and down as I move over the code.

I'm not sure if this is specific to dart, though.
