### ISSUE TITLE
Pylookup makefile breaks when 'fish' is the default shell

### ISSUE THREAD

**Issue by korayal** [syl20bnr/spacemacs#11647]
piping is different on 'fish', so when `$SHELL` is set to `fish` on this makefile, it breaks.

https://github.com/syl20bnr/spacemacs/blob/fc2d220b5eab09bfe1ee5cd61a777091f520af08/layers/%2Blang/python/local/pylookup/makefile#L1

**Comment by smile13241324** [comment]
Hi @korayal,

I have merged your PR on develop. Would you mind closing the issue when it is solved for you?
