### ISSUE TITLE
Error (use-package): helm/:config: Helm-mode enabled (Ido is incompatible with Helm-mode, disabling it)

### ISSUE THREAD

**Issue by iqgrande** [syl20bnr/spacemacs#11640]
Greetings:

I tried to submit the bug below from within Spacemacs however C-c C-c was "undefined" and wouldn't submit it. So, there are sorta 2 bugs. 

#### Description :octocat:
I get the following message when I launch Spacemacs after a fresh installation.
Error (use-package): helm/:config: Helm-mode enabled (Ido is incompatible with Helm-mode, disabling it)

#### Reproduction guide :beetle:
- =rm -rf ~/.spacemacs ~/.emacs.d=
- =git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d=
- Start Emacs
- It will display error...

*Observed behaviour:* :eyes: :broken_heart:
I have a warning/error buffer that displays the message above (replicated here for your convenienced).
Error (use-package): helm/:config: Helm-mode enabled (Ido is incompatible with Helm-mode, disabling it)

*Expected behaviour:* :heart: :smile:
I am expecting not to see warnings/errors when I launch Spacemacs.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp spell-checking)
```
- System configuration features: JPEG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by cole-h** [comment]
I'm seeing the same thing here, but on develop. Both 26.1 (as distributed with Arch) and 27.0.50 (built from source today) exhibit the same behavior. Rolling back the most recent package updates fixes the issue. System info and batched package updates below.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fc2d220b5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(gtags rust lsp systemd yaml lua
       (c-c++ :variables c-c++-backend 'lsp-cquery)
       html helm
       (latex :variables latex-build-command "LaTeX")
       (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip nil spacemacs-default-company-backends
                        '((company-dabbrev-code company-gtags company-etags company-keywords)
                          company-files))
       emacs-lisp git markdown neotree org syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Updated Packages :package: 
```
auto-yasnippet
counsel
doom-modeline
evil-goggles
git-commit
helm
helm-core
ivy
magit
org-plus-contrib
rtags
```

**Comment by iqgrande** [comment]
Greetings:

Thank you for your excellent response time!! How do I roll back the updates? Thank you for your help with this.

Kind regards,
Anthony
(Please excuse typos; this is sent from a mobile device.)

**Comment by cole-h** [comment]
Easiest way to roll back the updates would be to select "Rollback Package Update" from the Spacemacs home buffer. This will roll back the most recently updated packages as a group. You can also access this by using `M-x configuration-layer/rollback RET`, which will show you all rollback slots.

**Comment by bmag** [comment]
Will be fixed when #11646 is merged. In the meantime you can add `(ido-mode -1)` to your user-config and it should fix the issue.

**Comment by bmag** [comment]
> Should I file an issue upstream at https://github.com/emacs-helm/helm/?

The error is intended and is due to a deliberate decision upstream (see https://github.com/emacs-helm/helm/issues/2085#issuecomment-441458735). You are free to file an issue if it bothers you, but as far as Spacemacs is concerned I feel we're ok with this decision.

**Comment by bezoris** [comment]
> Will be fixed when #11646 is merged. In the meantime you can add `(ido-mode -1)` to your user-config and it should fix the issue.

Thanks! This was driving me crazy on 27.

**Comment by NordicOhm** [comment]
> Will be fixed when #11646 is merged. In the meantime you can add `(ido-mode -1)` to your user-config and it should fix the issue.

Super new to spacemacs, how exactly would i go about doing this? i can't seem to find where my user config is located... (OSX Mojave)

**Comment by cole-h** [comment]
> Super new to spacemacs, how exactly would i go about doing this? i can't seem to find where my user config is located... (OSX Mojave)

Your user config is in the `~/.spacemacs` file (just saw you use OSX... might change the file location) under the function `defun dotspacemacs/user-config()`. To get to your user config easier, Spacemacs has a keybind set up: `SPC f e d`.

**Comment by tidux** [comment]
User config is in fact still at `~/.spacemacs` on OS X.

**Comment by duianto** [comment]
`(ido-mode -1)` doesn't seem to be needed anymore.

Helm was updated: [Disable only ido-everywhere (#2085)](https://github.com/emacs-helm/helm/commit/d926c9ff8548ec5b8d39224f55b7c7bb289c1486)

>Ok, so I have reenabled ido-mode, disabling only ido-everywhere, sad to
see people use such configuration i.e. ido-mode+helm-mode which is non-sense.

source: https://github.com/emacs-helm/helm/issues/2085#issuecomment-441917270

**Comment by aswinmohanme** [comment]
Facing the same issue, (ido-mode -1) seems to work like a charm.
