### ISSUE TITLE
getenv does not return merged path env variables

### ISSUE THREAD

**Issue by cdfa** [syl20bnr/spacemacs#11650]
#### Description :octocat:
Multiple PATH occurrences in `spacemacs.env` are merged into exec-path, but `getenv` only returns the first occurrence.

EDIT: For context: I ran into this while trying to get js-beautify from the JavaScript layer to work. When trying to format, I get an error saying bash can't find js-beautify (so `executable-find` returns the correct path, but `shell-exec` fails). I'm still relatively new to Emacs, so if I misattributed this to `getenv' not containing the right path, please tell me. 

#### Reproduction guide :beetle:
- Add some path to the PATH variable in `.bashrc`
- Start Emacs
- `SPC f e e` to view `spacemacs.env`
- Observe two different path occurrences

*Observed behaviour:* :eyes: :broken_heart:
- `M-: (get-env "PATH")` only returns paths from the first occurrence

*Expected behaviour:* :heart: :smile:
- `M-: (get-env "PATH")` returns a merged list of paths from both occurrences like it does for `exec-path`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4912b54f2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git github org spell-checking syntax-checking version-control javascript ranger treemacs semantic themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by CeleritasCelery** [comment]
`exec-path` is not the same thing as `$PATH`. The former is used to find executables for subprocesses in Emacs and the later is passed to subshells as an environment variable. If you want them to match you can concat `exec-path` and set it yourself. `(setenv "PATH" (mapconcat 'identity exec-path ":"))`

**Comment by cdfa** [comment]
Okay, sounds logical, do you have any explanation for the specific behaviour I observed (`executable-find` returning the path to js-beautify while `shell-exec` fails saying it can't find the executable)?

**Comment by cdfa** [comment]
So, the web-beautify package should use some function to run js-beautify using `exec-path`? Or where is the error here? Or is my path not setup correctly? I think nvm put some exports in my .bashrc on installation which is why I can see the path to js-beautify in `exec-path`.
