### ISSUE TITLE
Function spacemacs/cider-test-run-project-tests does not work (missing an argument in a call to cider-test-run-project-tests)

### ISSUE THREAD

**Issue by jgracin** [syl20bnr/spacemacs#11652]
Hi!

The function spacemacs/cider-test-run-project-tests does not seem to work because it is not providing the mandatory argument in a call to cider-test-run-project-tests.  Using the latest commit (69a89cc41) from the develop branch and with all the packages updated.

Here's what works for me:
```
layers/+lang/clojure/funcs.el
@@ -135,7 +135,7 @@ the focus."
   "Run project tests."
   (interactive)
   (cider-load-buffer)
-  (cider-test-run-project-tests))
+  (cider-test-run-project-tests nil))
```

**Comment by TimoFreiberg** [comment]
https://github.com/syl20bnr/spacemacs/pull/12035 should fix this
