### ISSUE TITLE
wgrep-save-all-buffers. 'No buffer has been saved'

### ISSUE THREAD

**Issue by johnny-mh** [syl20bnr/spacemacs#11651]
#### Description :octocat:
I'm using develop branch of spacemacs.

When i trying to using wgrep editing.

Buffers are not saved. and displaying 'No buffer has been saved' message.

Please seeing below gif.

This error is occur even if reinstall spacemacs without any configuration modifications.

![spacemacs](https://user-images.githubusercontent.com/1061205/49057847-cca71500-f244-11e8-9d9c-ff0e1f4afaf2.gif)

#### Reproduction guide :beetle:
- Start Emacs
- Open any project `SPC p l`. and open any file.
- `SPC /` and search some files.
- When listing some files. press `C-c C-o` to switch wgerp mode
- Editing some lines
- Press `, ,` to finish editing
- Press `, s` to save all buffers.

*Observed behaviour:* :eyes: :broken_heart:
Buffers are not saved and displaying 'No buffer has been saved' message.

*Expected behaviour:* :heart: :smile:
Saved all buffers

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 69a89cc41)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(typescript ivy
            (auto-completion :variables auto-completion-enable-sort-by-usage t)
            emacs-lisp git markdown multiple-cursors neotree
            (version-control :variables version-control-diff-tool 'diff-hl))
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by robbyoconnor** [comment]
1. Use `SPC h I` from now on. 
2. Give `SPC h d s` in your initial comment.

**Comment by johnny-mh** [comment]
@robbyoconnor I got it.
