### ISSUE TITLE
Internationalization support of documentation

### ISSUE THREAD

**Issue by danielwuz** [syl20bnr/spacemacs#1165]
I would like to add Chinese translation of documentation for this project. It should be beneficial for the large amount of Emacs users in China who don't speak English. Where's the best place for me to keep these translations? Is it a good idea to have a wiki for different languages?

**Comment by syl20bnr** [comment]
That's great ! What kind of documentation you want to translate ?
I'm not fond of the wiki approach, it is easy to edit but it is also easy to be out of sync with the code base.
I would go for a support of language in the repo, I have to think about it, proposal are welcome.

**Comment by StreakyCobra** [comment]
As there was no update the last 6 months, I'm closing this issue. Feel free to open a new one if there is anything new about this.
