### ISSUE TITLE
Haskell completion backend

### ISSUE THREAD

**Issue by brettgilio** [syl20bnr/spacemacs#11661]
Does anybody have any experience on setting the haskell completion backend on a per project basis? For example, using .dir-locals.el

**Comment by xiongchenyu6** [comment]
I also curious about it, just read blogs on dir-locals and tried something like
```
((haskell-mode . ((haskell-completion-backend . ghci))))
```
but it did not work as I expected, could someone help with it? Thanks

**Comment by d12frosted** [comment]
It's possible to do with https://github.com/syl20bnr/spacemacs/pull/11550. It wasn't merged yet though. Would be nice if you give it a try.
