### ISSUE TITLE
Spacemacs packages not loading - bad archive-contents

### ISSUE THREAD

**Issue by apj68** [syl20bnr/spacemacs#11673]
#### Description :octocat:
I'm trying to get spacemacs working.  I had no problems on my home macos but at work things are not working.  After reading various similar issues I believe this has something to do with melpa being down... ?

#### Reproduction guide :beetle:
- Start Emacs
- Initially I was getting tons of errors like `Package xxx is unavailable. Is the package name misspelled?`
- To "fix" this per a comment here I increased `dotspacemacs-elpa-timeout 5` to 300
- The initial errors (`Package xxx is unavailable...`) seemed to be resolved but then I got `(wrong-type-argument listp closed)`

*Observed behaviour:* :eyes: :broken_heart:
`(wrong-type-argument listp closed)`

*Expected behaviour:* :heart: :smile:
Successful startup of spacemacs.

(I'm not sure what %LAST_KEYS% is)

- OS: Windows (Version	10.0.17134 Build 17134)
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrd
- Completion: helm
- Layers: <not there yet>

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument listp closed)
  package--read-archive-file("archives/melpa/archive-contents")
  package-read-archive-contents("melpa")
  package-read-all-archive-contents()
  package--update-downloads-in-progress(("melpa" . "https://melpa.org/packages/"))
  #[0 "\301\300!\207" [("melpa" . "https://melpa.org/packages/") package--update-downloads-in-progress] 2]()
  package--check-signature("https://melpa.org/packages/" "archive-contents" "closed\nWARNING: can't open config file: /usr/local/ssl/openssl.cnf
\ndepth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
\nverify error:num=20:unable to get local issuer certificate
\n" nil #[256 "\302\300\303\301\303\304%\210\211\205
```

It seems that it's looking for `openssl.cnf` in the wrong place but I don't know why or what I should do next.

**Comment by mapolone** [comment]
Are you generally able to connect to websites protected by Let's Encrypt certificates from your Windows machine? Try to connect [here](https://melpa.org) and see what happens.

Error `unable to get local issuer certificate` generally means you don't have a certificate authority on your machine.

**Comment by apj68** [comment]
Yes, I can get to the link fine in my browser.  I assumed the local issuer error was a result of this:

` WARNING: can't open config file: /usr/local/ssl/openssl.cnf`

Because I'm on a Windows machine, I don't have that file.  I'm just not sure why it wants to look there for that file. . .?

**Comment by apj68** [comment]
Update: I upgraded my emacs to 27.0.50 and now using my original `.emacs.d` everything is fine but if I use the spacemacs distribution it doesn't even start, I can't even see any output with `--debug-init`, it just doesn't do anything.  I'm going to close this for now.  Will give spacemacs a try another time.
