### ISSUE TITLE
TMPDIR in ~/.spacemacs.env breaks spacemacs after backup restore on a new Mac 

### ISSUE THREAD

**Issue by loxs** [syl20bnr/spacemacs#11674]
#### Description :octocat:
TMPDIR in ~/.spacemacs.env breaks spacemacs after backup restore on a new Mac 

#### Reproduction guide :beetle:
- Start Emacs after moving your home directory to a new Mac 

*Observed behaviour:* :eyes: :broken_heart:
- It fails to update properly and displays errors that it can't read/write files in old tmp directory which no longer is the same on the new Mac 
- I had to delete .spacemacs.env and it took me several hours to find what the problem is (didn't even know that such a thing as .spacemacs.env exists)

*Expected behaviour:* :heart: :smile:
Hardcoding the path to a machine specific directory is probably wrong, or at least spacemacs should have a mechanism to recover from this if it doesn't find the configured directory.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 69a89cc41)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(python nginx ocaml csv yaml javascript html react markdown emacs-lisp erlang elixir git org syntax-checking)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
File mode specification error: (file-missing Creating directory with prefix No such file or directory /var/folders/wq/hh0gd3_57pschvmv66g839w40000gq/T/babel-)
Auto-evilification could not remap these functions in map ‘edebug-mode-map’:
   - ‘edebug-Go-nonstop-mode’ originally mapped on ‘G’
helm-M-x: Creating directory with prefix: No such file or directory, /var/folders/wq/hh0gd3_57pschvmv66g839w40000gq/T/babel-
```

**Comment by loxs** [comment]
Also maybe consider moving this file to `~/.emacs.d/` as it's quite intuitive to try and delete this folder and reinstall spacemacs, which would have fixed the problem.
The existence of .spacemacs.env was not obvious.

**Comment by gorrog** [comment]
I have had the same issue this morning, also most likely caused by me moving my .spacemacs.env file over to a new machine (thinking that this was an important config file that needed to be retained).

Deleting `~/.spacemacs.env` fixed the problem. Thanks @loxs for the solution posted above.

**Comment by loxs** [comment]
This doesn't seem to be fixed. The workaround is still valid - delete ~/.spacemacs.env
