### ISSUE TITLE
develop: magit-list-repositories broken

### ISSUE THREAD

**Issue by vbauerster** [syl20bnr/spacemacs#11687]
#### Description :octocat:
`magit-list-repositories` broken

#### Reproduction guide :beetle:
- Start Emacs
- make sure (setq magit-repository-directories '("~/go/src"))
- Press `SPC g L`

*Observed behaviour:* :eyes: :broken_heart:
wrong-type-argument listp "~/go/src"

*Expected behaviour:* :heart: :smile:
buffer with dir listing

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5b2e969b3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org
      (git :variables git-magit-status-fullscreen t)
      (version-control :variables version-control-diff-side 'left)
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip 'manual)
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      (spell-checking :variables enable-flyspell-auto-completion t spell-checking-enable-by-default nil)
      html markdown ...)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument listp "~/go/src")
  #f(compiled-function (arg0) #<bytecode 0x45c43575>)("~/go/src")
  mapcan(#f(compiled-function (arg0) #<bytecode 0x45c43575>) ("~/go/src"))
  cl-mapcan(#f(compiled-function (arg0) #<bytecode 0x45c43575>) ("~/go/src"))
  magit-list-repos()
  magit-repolist-refresh()
  magit-list-repositories()
  funcall-interactively(magit-list-repositories)
  call-interactively(magit-list-repositories nil nil)
  command-execute(magit-list-repositories)

```

**Comment by duianto** [comment]
You can close this issue if it's been resolved.
