### ISSUE TITLE
Latex layer views two files when space in file name.

### ISSUE THREAD

**Issue by ExampleOne** [syl20bnr/spacemacs#11684]
#### Description :octocat:
Latex layer views two different files when using [SPC m v].

#### Reproduction guide :beetle:
- Start Emacs
- Open a .tex file with a space in it, say "A B.tex"
- Build file using [SPC m b].
- Use [SPC m v] to view pdf output.

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs tries to open two files, "A B.pdf", and "B.tex" (note for the second file, it appears to source is being opened?).

*Expected behaviour:* :heart: :smile:
Open only "A B.pdf"

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown org spell-checking syntax-checking version-control pdf-tools latex python ipython pyvenv)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by ExampleOne** [comment]
Never, mind, found a solution.
Was following guide at [here](https://mssun.me/blog/spacemacs-and-latex.html), but which recommended adding the following two sections to .spacemacs:

`(cond
 ((string-equal system-type "darwin")
  (progn (setq TeX-view-program-selection '((output-pdf "Skim")))))
 ((string-equal system-type "gnu/linux")
  (progn (setq TeX-view-program-selection '((output-pdf "Okular"))))))`

and

`(setq TeX-source-correlate-mode t)
(setq TeX-source-correlate-start-server t)
(setq TeX-source-correlate-method 'synctex)
(setq TeX-view-program-list
      '(("Okular" "okular --unique %o#src:%n`pwd`/./%b")
        ("Skim" "displayline -b -g %n %o %b")
        ("Zathura"
         ("zathura %o"
          (mode-io-correlate
           " --synctex-forward %n:0:%b -x \"emacsclient +%{line} %{input}\"")))))`

Getting rid of one mention of Okular resolved the issue. Sorry.

**Comment by vv111y** [comment]
@ExampleOne 
According to that blog post, as of 2016 you shouldn't have to make TeX-view-program-list. Did you try without it?
I want to get zathura going. Also, if you use zathura, do you have to create the script from that post?

**Comment by ExampleOne** [comment]
Sorry, I didn't actually use Zathura, used Okular. Not sure how different that is. But yes, in my new .spacemacs, I now have commented out the TeX-view-program-list, and it seemed to work without (case sensitive though, so used "Okular"). Don't know about the script in that post, sorry.
