### ISSUE TITLE
layers/+lang/go: golangci-lint output not visible when lsp backend is used

### ISSUE THREAD

**Issue by theckman** [syl20bnr/spacemacs#11680]
#### Description :octocat:
An interaction between the Go layer using LSP for code completion results in the `golangci-lint` linter not running, or at a minimum the results not being rendered in the UI. I'm able to reproduce this issue in my local project when I have:

```elisp
(go :variables
    go-tab-width 4
    go-backend 'lsp
    gofmt-command "goimports"
    go-use-golangci-lint t)
```

If I comment out the `go-backend 'lsp` line so that the default is used, everything works as-expected.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file in `.go` that has linting issues

*Observed behaviour:* :eyes: :broken_heart:
- Lint errors are not rendered in the UI

Not seeing any clear errors in the `*Messages*` buffer:
```
Saving file /Users/theckman/go/src/stash.corp.netflix.com/core/halp2/test/mocks/mockstore/store.go...
Wrote /var/folders/f5/zjcsdkrx2bxdm32zzqfg5yp80000gn/T/gofmtho43XA.go
Calling gofmt: goimports (-srcdir /Users/theckman/go/src/stash.corp.netflix.com/core/halp2/test/mocks/mockstore/store.go -w /var/folders/f5/zjcsdkrx2bxdm32zzqfg5yp80000gn/T/gofmtho43XA.go)
Buffer is already gofmted
Wrote /Users/theckman/go/src/stash.corp.netflix.com/core/halp2/test/mocks/mockstore/store.go
```

*Expected behaviour:* :heart: :smile:
- Lint errors should be visible in the UI.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4912b54f2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers: go lsp

```elisp
(auto-completion lsp better-defaults dash git github helm nginx osx spell-checking syntax-checking version-control html markdown nginx org yaml emacs-lisp groovy sql docker protobuf rust typescript
                 (go :variables go-tab-width 4 go-backend 'lsp gofmt-command "goimports" go-use-golangci-lint t)
                 java javascript python
                 (ruby :variables ruby-enable-enh-ruby-mode t)
                 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
N/A

**Comment by theckman** [comment]
Tagging those who may have some insight. @ljupchokotev @sdwolfz @cormacc @MaskRay @bittopaz

**Comment by bittopaz** [comment]
@theckman I'm afraid I can't help on this one anymore.

I have switched from Spacemacs to doom-emacs, also, the LSP for Golang is not as mature as I thought.

I'm not using LSP for golang now.

**Comment by vbauerster** [comment]
At latest develop, enabling lsp `go-backend 'lsp` doesn't work any more, following warning appears:
```
Error (use-package): lsp-mode/:config: Cannot open load file: No such file or directory, lsp-clients
```

**Comment by vbauerster** [comment]
@bittopaz I agree with you that default [go-langserver](https://github.com/sourcegraph/go-langserver) isn't as mature and has bugs, but there is a very promising alternative [bingo](https://github.com/saibing/bingo), so it would nice to switch or at least let user define which one to use.

**Comment by theckman** [comment]
@vbauerster that has nothing to do with this issue.

**Comment by theckman** [comment]
@bittopaz finally figured it out, I think (if you're curious): https://github.com/syl20bnr/spacemacs/pull/12043

**Comment by duianto** [comment]
The PR:
Set lsp-prefer-flymake to :none when Go layer is using LSP #12047
has been cherry-picked into the `develop` branch.
