### ISSUE TITLE
[feature-request] support for xah-fly-keys to have modal support for emacs editing

### ISSUE THREAD

**Issue by nipunarora** [syl20bnr/spacemacs#11689]
Currently, spacemacs does not have modal mode support similar to `xah-fly-keys` for emacs editing mode (admittedly vi already has one). Could we get support for `xah-fly-keys` as a layer in spacemacs?

**Comment by gcentauri** [comment]
I have opened a PR #11701  to add this as a layer.  Feel free to comment on it if you have opinions on how to integrate another modal map.
