### ISSUE TITLE
Spacemacs high memory, slow, hanging on exit on NixOS

### ISSUE THREAD

**Issue by GregorySchwartz** [syl20bnr/spacemacs#11694]
#### Description :octocat:
Spacemacs on NixOS takes a while to open, takes up 40% of memory, and hangs
(forever) when closing. No issues on Ubuntu 18.04 nor Arch.

#### Reproduction guide :beetle:
- Start Emacs in NixOS with default configuration.

*Observed behaviour:* :eyes: :broken_heart:
High memory and CPU usage, hangs on exit.

*Expected behaviour:* :heart: :smile:
Same memory and CPU usage as on other operating systems, and no hanging on exit.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fc2d220b5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python yaml shell-scripts csv html javascript
        (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-complete-with-key-sequence-delay 0 auto-completion-idle-delay 0)
        helm lsp better-defaults emacs-lisp git markdown mu4e neotree
        (org :variables org-enable-reveal-js-support t org-enable-bootstrap-support t)
        (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell shell-default-term-shell "/usr/bin/fish")
        spell-checking syntax-checking erc
        (ranger :variables ranger-show-preview t)
        haskell nixos ess
        (latex :variables latex-enable-auto-fill t latex-enable-folding t)
        bibtex pandoc pdf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by NotBrianZach** [comment]
I use spacemacs on develop on nixos, no problem like this one, sha: 901f35849af44ae433670d5030024834985ce9d4

**Comment by GregorySchwartz** [comment]
@NotBrianZach Do you experience this issue with emacs 26.1 on NixOS stable?

**Comment by laMudri** [comment]
I'm on nixos-unstable and Emacs 26.1, but haven't noticed anything like this. How much is 40% of your RAM?

**Comment by GregorySchwartz** [comment]
It's using up about 11G. It's interesting that you do not see the issue. Do you have any special configuration for emacs in your nix config?

**Comment by GregorySchwartz** [comment]
Yes, I also have the issue with the default spacemacs configuration. Interestingly, I have no issue with `emacs -Q`.

**Comment by GregorySchwartz** [comment]
Profiling the hanging on exit shows that most of the time is spent on `save-place-kill-emacs-hook` in `indent-sexp`, around those parts.

**Comment by GregorySchwartz** [comment]
I should mention that the memory usage is from the very start and performance while using emacs is fine, it's just high memory usage and it hangs on exit.

**Comment by GregorySchwartz** [comment]
I don't know what happened, but pulling from develop today as opposed to two weeks ago and purging `.emacs.d` again worked.
