### ISSUE TITLE
In Spacemacs, what is the order of load-path?

### ISSUE THREAD

**Issue by re-mx** [syl20bnr/spacemacs#11692]
Hello:

In Spacemacs, what is the order of the items in `load-path`?

Thank you.

**Comment by yangwen0228** [comment]
Please see the **\*Message\*** buffer.

**Comment by re-mx** [comment]
Thank you for your reply!

But `*Message*`buffer only provides the loading order of the layer. Not the order of `load-path`.

What I want to know is the order of things in `load-path`. For example, is the local package in front of or behind elpa?

**Comment by yangwen0228** [comment]
No. The front directory or local package has higher priority. You can find more information by checking the function `list-load-path-shadows`.

**Comment by re-mx** [comment]
Please forgive me for my bad English.

I mean:
In the "add to `load-path`" action, the local package is more backward.

Then the local package is closer to the head in `load-path`?
