### ISSUE TITLE
Add shortcut for delete-other-windows

### ISSUE THREAD

**Issue by lukerandall** [syl20bnr/spacemacs#1170]
Currently the only way I can find of deleting other windows is pulling up the window manipulation micro state, then hitting `C` (or obviously using `C-x 1`); it would be nice to have a window layer shortcut for it. Ideally, we'd use the same key as the micro state `C` as it mirrors `c` for delete-window, but that will necessitate swapping ace-delete-window out for something else.

**Comment by cpaulik** [comment]
You can just do <kbd>SPC w m</kbd> to maximize the current window. You can undo the maximization by pressing the keys again or just continue splitting in another way.

**Comment by lukerandall** [comment]
I'm happy that this solves the problem. Thanks @cpaulik

**Comment by ralesi** [comment]
Or `c-w o` ala Vim

**Comment by wminshew** [comment]
> You can just do SPC w m to maximize the current window. You can undo the maximization by pressing the keys again or just continue splitting in another way.

this works pretty well but would be nice if there was a command to kill the other buffer too
