### ISSUE TITLE
Flycheck tooltip white text on light background

### ISSUE THREAD

**Issue by tomekowal** [syl20bnr/spacemacs#11716]
#### Description :octocat:
Flycheck tooltip has white text on light background making it unreadable.

#### Reproduction guide :beetle:
- Start Emacs
- open a document checked by flycheck
- make an error in it and set the cursor on underlined words

*Observed behaviour:* :eyes: :broken_heart:
The popup has white text on very light background.

<img width="1081" alt="zrzut ekranu 2018-12-13 o 08 07 49" src="https://user-images.githubusercontent.com/907415/49921815-0ddb2e00-feaf-11e8-8a9d-edc745a1ef60.png">

*Expected behaviour:* :heart: :smile:
The popup should either inherit theme colors or be black text on white background

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv python sql yaml osx shell syntax-checking auto-completion better-defaults erlang elixir elm javascript emacs-lisp git markdown org dash html colors selectric
     (wakatime :variables wakatime-api-key "[[REDACTED]]" wakatime-cli-path "/usr/local/bin/wakatime")
     spell-checking version-control spotify)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by jparkrr** [comment]
Are you in dark mode? If so, there's a workaround here https://github.com/syl20bnr/spacemacs/issues/11541 and can probably close this issue as a dupe.

**Comment by tomekowal** [comment]
I am using Dark Mode and the solution works.
I wouldn't expect that this is the problem. Thank you!
And sorry I haven't found the original issue. I searched for "tooltip" while it used "tool-tip" in the name.
Closing as a duplicate of #11541
