### ISSUE TITLE
[Request] Liquid template support

### ISSUE THREAD

**Issue by mateusvahl** [syl20bnr/spacemacs#11719]
Hi, I work with a lot of liquid files, unfortunately there's no support for highlight that on Spacemacs.
Could someone indicate what is necessary to implement a liquid support ? It's quite similar to html/handlebars, so we may find a way of reuse existent code.

Best

[Liquid reference](https://shopify.github.io/liquid/)

**Comment by Decoherence** [comment]
This would be outstanding! I work with liquid templates every day, and highlighting/indentation would be very helpful.

**Comment by duianto** [comment]
There's a `liquid-mode `package here:
https://github.com/alesguzik/liquid-mode

It doesn't seem to work with Spacemacs (or possibly with Emacs either) in it's current state (see below).

It's not on https://melpa.org so it has to be loaded from github.

Adding this:
```elisp
(liquid-mode :location (recipe :fetcher github
                                     :repo "alesguzik/liquid-mode"))
```
to the `dotspacemacs-additional-packages` variable in `.spacemacs`.

Tries to download and install it.
(I'm not sure if it works on the Spacemacs `master` branch, but it is downloaded on the `develop` branch)

### It doesn't seem to work in it's current state

On startup Spacemacs tries to download and install the package, but it shows these error messages:
>Error getting PACKAGE-DESC: (error Package lacks a file header)
(Spacemacs) Error: 
An error occurred while installing liquid-mode (error: (wrong-type-argument package-desc nil))

It will download and try to install the package again with the same errors the next time Spacemacs is restarted, as long as the package is listed in the additional packages variable.

It needs a file header (I'm not sure what that consists of).

This is not a working solution, but it might be a starting point for getting syntax highlighting to work.

**Comment by ezmiller** [comment]
+1
