### ISSUE TITLE
clojure-mode not activated for 'build.boot'

### ISSUE THREAD

**Issue by usharf** [syl20bnr/spacemacs#1172]
`build.boot` files open into fundamental mode, though package installed by contrib/lang/clojure has `'\\build.boot\\` in `'auto-mode-alist`.

```emacs-lisp
  (add-to-list 'auto-mode-alist '("\\`build.boot\\'" . clojure-mode))
```

NB It works when added manually under the use-package `:init` declaration in contrib/lang/clojure.

**Comment by jballanc** [comment]
Ideally it would be nice to have all `*.boot` files open in clojure-mode.
