### ISSUE TITLE
Neotree error: `Wrong type argument`

### ISSUE THREAD

**Issue by outkine** [syl20bnr/spacemacs#11725]
#### Description :octocat:
Toggling neotree two times causes error: `Wrong type argument: window-valid-p, #<window 14>`

#### Reproduction guide :beetle:
- Start Emacs
- open neotree (SPC f t)
- close neotree (SPC f t)
- attempt to open neotree again (SPC f t)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5b2e969b3)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(elixir python javascript react helm auto-completion better-defaults emacs-lisp git markdown syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT GTK3 X11 MODULES THREADS LIBSYSTEMD JSON LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument window-valid-p #<window 14>)
  window-buffer(#<window 14>)
  neo-global--window-exists-p()
  neotree-toggle()
  funcall-interactively(neotree-toggle)
  call-interactively(neotree-toggle nil nil)
  command-execute(neotree-toggle)
```

**Comment by Dietr1ch** [comment]
This keeps happening to me when I use emacs-client.

I think that it works fine with the first time I open it on my first frame, but if I close the frame
I can't use neotree until I restart the server. I guess that there's some caching that shouldn't
be there (or should be verified before re-using)


This is my backtrace,
```
Debugger entered--Lisp error: (wrong-type-argument window-valid-p #<window 24>)
  window-buffer(#<window 24>)
  neo-global--window-exists-p()
  (if (neo-global--window-exists-p) (neotree-hide) (let ((origin-buffer-file-name (buffer-file-name))) (neotree-find (projectile-project-root)) (neotree-find origin-buffer-file-name)))
  neotree-find-project-root()
  funcall-interactively(neotree-find-project-root)
  call-interactively(neotree-find-project-root nil nil)
  command-execute(neotree-find-project-root)
```

**Comment by codejamninja** [comment]
I'm getting this same error

**Comment by lebensterben** [comment]
Cannot reproduce this issue.
Please update all system packages, Spacemacs, and emacs packages.
If it persists, attach your system info via <kbd>SPC h I<kbd> below.
