### ISSUE TITLE
<SPC> p f is slow

### ISSUE THREAD

**Issue by talexu** [syl20bnr/spacemacs#11726]
Hi all,

I have been spacemacs user since 2016, it was very fast in emacs 24.5.1.
But now I get a 1 second latency after I type "SPC p f" to search a file in a project in emacs 26.1.
Does anyone has the same performance issue? I want to get response immediately when I type "SPC p f".

System Info 💻

- OS: MacOS 10.14.1 (18B75)
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5b2e969b3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
`(go
     ruby
     osx
     helm
     auto-completion
     emacs-lisp
     git
     multiple-cursors
     neotree
     syntax-checking
     )`

Thanks.

**Comment by renatomassaro** [comment]
I have experienced the same problem on `master` and `develop`. `SPC p f` got slow recently, but I'm afraid I don't know exactly *when* it started acting this way.

**Comment by jsmestad** [comment]
Try running a profiler to see what is causing it.

`M-x profiler-start` (profiling CPU is probably what you want) then do your SPC p f command then `M-x profiler-report` to see the results. (when done profiler-stop)

**Comment by zilongshanren** [comment]
I figure it out that there are so many `find-file-hooks` and I manually rebuilt the hooks which 3-5 hook function matters to me.
