### ISSUE TITLE
new `lsp-mode` and flycheck

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#11724]
`flymake` integration of `spacemacs` is not great and the new `lsp-mode` is using `flymake` by default, maybe this should be changed globally by setting `lsp-prefer-flymake` to `nil` by default.

**Comment by yyoncho** [comment]
Check https://github.com/syl20bnr/spacemacs/pull/11626 . lsp-prefer-flymake will be nil.
