### ISSUE TITLE
Error `failed to define function lsp-cquery-enable` when using lsp-cquery backend for c-c++ layer

### ISSUE THREAD

**Issue by szobov** [syl20bnr/spacemacs#11731]
#### Description :octocat:
Error `File mode specification error: (error Autoloading file /home/user/.emacs.d/elpa/26.1/develop/cquery-20181203.1829/cquery.elc failed to define function lsp-cquery-enable)` when using lsp-cquery backend for c-c++ layer and this backend isn't working.

#### Reproduction guide :beetle:
- Enable lsp-backed for c-c++ layer in config.
- Restart Emacs
- Open any c/c++ files
- Look into *Messages* buffer

*Observed behaviour:* :eyes: :broken_heart:
`lsp-cquery backend` isn't working. Error in *Messages* buffer.

*Expected behaviour:* :heart: :smile:
`lsp-cquery backend` is working without any errors.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5b2e969b3)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust helm emacs-lisp neotree graphviz auto-completion syntax-checking version-control spell-checking restclient git github ansible docker nginx sql markdown yaml protobuf shell windows-scripts python erlang elixir
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-auto-newline t c-c++-backend 'lsp-cquery c-c++-lsp-executable "/home/user/.nix-profile/bin/cquery")
      semantic html javascript typescript react
      (go :variables go-use-test-args "-race -timeout 30s -v" godoc-at-point-function 'godoc-gogetdoc)
      nixos evernote org neotree emoji pdf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS

**Comment by beyondpie** [comment]
Ref: #11626 
lsp-cquery-enable is old, and  need to change the layer code use `lsp` command instead.

**Comment by szobov** [comment]
@beyondpie  yes, thanks, I've merged the changes from this PR and the error disappeared.
So I'll wait this changes to be merged into develop branch.

**Comment by beyondpie** [comment]
@sdwolfz 
I think this issue can be closed.

**Comment by szobov** [comment]
The error still exists in develop branch, but ok, I'll close this issue.
