### ISSUE TITLE
“jj” to normal, it doesn't work well.

### ISSUE THREAD

**Issue by wolongge** [syl20bnr/spacemacs#11730]
code:
```
(setq-default
  evil-escape-key-sequence "jj"
  evil-escape-unordered-key-sequence "true"
)
```
or
```
(setq-default  evil-escape-key-sequence "jj")
```
it doesn't work well. Juse first time, it work. But it doesn't work after the first time. 
I don't know when to start working again.

So it sometimes works.

But "jk" works very well.

**Comment by westlywright** [comment]
I can repro on develop branch. Added the following to my user-config

`(setq-default  evil-escape-key-sequence "jj")`

`jj` works the first time, subsequent `jj` do not work.

**Comment by ZBQtesla** [comment]
I faced the same issue, and this worked for me:

```elisp
(defun dotspacemacs/user-config ()
  ;; increase the delay of evil-escape
  (setq-default evil-escape-delay 0.2)
  (setq-default evil-escape-key-sequence "jj"))
```
  `(setq-default evil-escape-delay 0.2)` is used to increase the delay of `evil-escape` as mentioned in #7029
