### ISSUE TITLE
error loading clojure layer

### ISSUE THREAD

**Issue by benswift** [syl20bnr/spacemacs#11735]
#### Description :octocat:

with latest `develop` branch clojure layer, I get a missing package error for
clojure-cheatsheet (which is apparently now integrated into CIDER as per the
[README](https://github.com/clojure-emacs/clojure-cheatsheet))

#### Reproduction guide :beetle:
- add clojure layer to `dotspacemacs-configuration-layers`
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

written to `*spacemacs*` buffer:

```
Found 1 new package(s) to install...
--> installing package: clojure-cheatsheet@clojure... [1/1]
Package clojure-cheatsheet is unavailable. Is the package name misspelled?
```

*Expected behaviour:* :heart: :smile:

clojure layer (inc. cider) loads normally

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5b2e969b3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-private-snippets-directory "~/.dotfiles/snippets/")
 emacs-lisp git
 (markdown :variables markdown-asymmetric-header t)
 mu4e
 (org :disabled-for ess)
 (asm :variables indent-tabs-mode t tab-width 4)
 bibtex c-c++ clojure cmake csv docker emacs-lisp
 (ess :variables ess-smart-S-assign-key nil)
 (extempore :location local)
 helm html
 (javascript :variables js-indent-level 2)
 latex multiple-cursors python restclient ruby scheme
 (shell :variables shell-default-shell 'shell)
 shell-scripts yaml spell-checking syntax-checking)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by jamartin9** [comment]
Refs: https://github.com/syl20bnr/spacemacs/pull/11361

**Comment by 0atman** [comment]
This is an important fix, as currently this package tries to get installed every startup, which means the package lists are refreshed every startup, which blocks the UI.
Thank you! :+1:

**Comment by 0atman** [comment]
The workaround for this, if anyone came here to find one, is to add this to your `dotspacemacs/layers` function:

```elisp
   ...
   dotspacemacs-configuration-layers
   '((clojure :packages (not clojure-cheatsheet))
```

**Comment by benswift** [comment]
Great, thanks - that's the workaround I had been using 🙂

**Comment by sdwolfz** [comment]
Should be fixed in develop now.
