### ISSUE TITLE
[Proposal] Add highlight-parentheses to Spacemacs core for Lisp modes

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1173]
`highlight-parentheses` highlights the sexp scope the cursor is in and several upper sexp levels. Let's have a look at this screenshot:

![highlight-parentheses-demo](https://cloud.githubusercontent.com/assets/4818719/7155293/cd58725c-e387-11e4-86b0-d9f62cbf07e2.gif)

in the screenshot, you see the cursor is on the opening parenthesis of the form `buffer-substring-no-properties`. Then, you see a closing turquoise parenthesis. If you look up, you will also see an opening turquoise parenthesis next to `with-temp-buffer`. It means that if I press `C-M-k` and delete `buffer-substring-no-properties` and after the form is deleted, my cursor will be right above the closing turquoise parenthesis. This is the only package that let me know exactly the end of my parenthesis. You can think this is similar to `show-smartparen-mode`, except that instead of moving point on a parenthesis, it highlights the parentheses as long as cursor is inside the current sexp..

It is useful in writing regexp:

![highlight-parentheses-regexp-demo](https://cloud.githubusercontent.com/assets/4818719/7155525/8571b1e0-e389-11e4-90fc-4064a6881e1d.gif)

`rainbow-parentheses` just has to many colours that make it impossible to do the above tasks.

**Comment by tuhdo** [comment]
Let's have a look at a more complicated example:

![highlight-parentheses-demo2](https://cloud.githubusercontent.com/assets/4818719/7155658/a33f3912-e38a-11e4-8d4f-f09c6ab122b1.gif)

In the screenshot above, when looking you immediately know where the `while` form ends and the scope of the `ignore-num` form by looking at red the opening and closing red parens.

**Comment by syl20bnr** [comment]
It is way more useful than `rainbow-delimiters`, we can put it has default in spacemacs but we should introduce de variable `dotspacemacs-highlight-delimiters` with possible value `all` `scope`.
`scope` is maybe not the best symbol to describe the behavior of `highlight-parentheses`.

**Comment by tuhdo** [comment]
We should enable it by default, at least for Lisp modes. What do you think?

**Comment by syl20bnr** [comment]
Yes definitely but people are really used to rainbow-delimiters so I think we must drive this with a `dotspacemacs-xxx` variable with the default value to use `highlight-parentheses`.
