### ISSUE TITLE
spacemacs become unresponsive with recent updates, editing in spacemacs is really a pain now.

### ISSUE THREAD

**Issue by Yu-da-xia** [syl20bnr/spacemacs#11736]
im using a macbookpro with spacemacs installed for years , and i use spacemacs very frequently , but last time when i update, with estimated 20 packages updated in a row, my spacemac become extremely unresponsive, i disabled auto-complete, and the problem appeared again, when i editing, spacemacs often lagging, and i will miss one character or another, i have to go back and re-type it again, i have to switch to another editor temporarily , and i'm waiting for newer updates to fix this problem.

**Comment by Yu-da-xia** [comment]
![dec-20-2018 16-49-01](https://user-images.githubusercontent.com/20807817/50274085-44004b00-0477-11e9-93ea-031646304c3d.gif)
for example: i want to type "num" here, the editor does not shot "u", i m frustrated.

**Comment by zilongshanren** [comment]
You could use `profiler-start` and `profiler-report` to profiling your Emacs configuration.

Here is the link might helps: 

https://emacs-china.org/t/21-emacs-18/946

**Comment by sorawee** [comment]
I just upgraded yesterday and this started to happen to me too. But it's rare enough that I can't reliably debug it...

**Comment by sorawee** [comment]
@Yu-da-xia I notice that the `*Messages*` buffer has a lot of "Quit". Is it the same to you?

**Comment by tensor-programming** [comment]
I've got the same issue happening to me on windows. It also seems to depend on the programming language that I am working with.  If I am writing Clojure or some other Lisp, then there is very little latency; when I write in Go or Rust, the latency gets much worse and I constantly see the "quit" line in the *Messages* buffer while typing.

**Comment by sorawee** [comment]
Steps to reproduce:

1. Freshly install/clone Spacemacs (develop branch)
2. Comment out every layer
3. Create a file name `a.pm`. When asked whether you want to install a layer, say no.
4. In the first line, write `(y-a)`.
5. Keep typing `The quick brown fox jumps over a lazy dog.` on the second line, third line, and so on.
6. You will get "Quit" message in the minibuffer after typing a few lines (3 for me). This will make you miss a character (as reported by @Yu-da-xia).
7. The "Quit" lines also appear in the `*Messages*` buffer.

Of course, the problem doesn't only appear with the `.pm` extension.

@tensor-programming as I understand, company-mode comes with the auto-completion layer, correct? The freshly installed Spacemacs, with _every_ layer disabled, still has this problem, so I don't think that's the fault.

I totally agree that editing in Spacemacs is really a pain now.

**Comment by sorawee** [comment]
@tensor-programming @Yu-da-xia can you try disabling `smartparens`? I think this is due to https://github.com/Fuco1/smartparens/pull/943 because when I put `smartparens` in `dotspacemacs-excluded-packages`, the `Quit` lines don't come up.

**Comment by sorawee** [comment]
Note: if you need to use `smartparens`, you can switch to use the `spacelpa` repo meanwhile.

**Comment by sorawee** [comment]
@Yu-da-xia @tensor-programming whenever you can, would you mind trying disabling `smartparens` and see if the problem goes away? I would like to confirm that the problem is due to `smartparens`, but right now it's still unconfirmed (at https://github.com/Fuco1/smartparens/issues/946)

**Comment by arvinpan** [comment]
I met the same problem today after all my packages updated.

And seems working fine for now after disabling `smartparens` @sorawee. Thanks Bro!

**Comment by Lokeh** [comment]
Can confirm that I've been having this same issue for the last few days, and excluding `smartparens` appears to have resolved the problem.

**Comment by aaronjensen** [comment]
Worth trying some version of https://github.com/Fuco1/smartparens/pull/882? I think being more explicit about when checking for inputs can help with stuff like this...

**Comment by Lokeh** [comment]
At this point, I'm just trying to figure out how to roll back my version of smartparens.

Enabling spacelpa resulted in my Emacs config completely breaking.

**Comment by duianto** [comment]
This has been fixed, [smartparens reverted](https://github.com/Fuco1/smartparens/commit/ef660fb4d99ea93c5c50886c8462f73f84745174) the problematic `while-no-input` call that was causing the issue.

**Comment by Yu-da-xia** [comment]
> This has been fixed, [smartparens reverted](https://github.com/Fuco1/smartparens/commit/ef660fb4d99ea93c5c50886c8462f73f84745174) the problematic `while-no-input` call that was causing the issue.
