### ISSUE TITLE
helm-projectile-find-file aborts unexpectedly while typing too fast

### ISSUE THREAD

**Issue by y-usuzumi** [syl20bnr/spacemacs#11753]
#### Description :octocat:
helm-projectile-find-file aborts unexpectedly while typing too fast

#### Reproduction guide :beetle:
I can't find reliable reproduction steps so I made a screen recording when the bug appears.

- Start Emacs
- Open a HUGE project
- M-m p f to run `helm-projectile-find-file`
- (Watch the screen recording for further steps)

[Screen recording here](https://vimeo.com/user93204887/review/308251079/3410750b07)
(Note: The first search attempt succeeds, the latter search fails. Something is also wrong with my Python layer. File opening is SOOO slow)

*Observed behaviour:* :eyes: :broken_heart:
The helm window closes prematurely and the remaining key strokes go to the editing buffer.

*Expected behaviour:* :heart: :smile:
The search works normally

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8b3a30f24)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git
                 (helm :variables helm-no-header t)
                 markdown neotree
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking themes-megapack version-control csharp fsharp fstar
                 (go :variables gofmt-command "goimports" go-tab-width 4)
                 (haskell :variables haskell-completion-backend 'intero haskell-process-type 'stack-ghci)
                 html idris javascript
                 (python :variables)
                 rust typescript yaml react dash chinese)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:

(I'd love to prepare a backtrace but how? The message buffer has nothing related to this behavior)

Also, In DOOM Emacs I have never seen it fail.

**Comment by jbrechtel** [comment]
I'm also experiencing this.

**Comment by duianto** [comment]
@jbrechtel Could you post your system info. It might help to narrow down where the issue is occurring. Press `SPC h d s` to copy your system info to the clipboard.
