### ISSUE TITLE
Weird string when pressing `spc /`

### ISSUE THREAD

**Issue by goofansu** [syl20bnr/spacemacs#11750]
#### Description :octocat:
There is a weird string `%-4d` when pressing `spc /`

#### Reproduction guide :beetle:
- Start Emacs
- In any project, press `spc /`

*Observed behaviour:* :eyes: :broken_heart:
![screenshot of emacs 2018-12-25 11-35-42 pm](https://user-images.githubusercontent.com/1143191/50424431-6db5d980-089e-11e9-8b56-bee4deb71790.png)

*Expected behaviour:* :heart: :smile:
The string should not be there.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8b3a30f24)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion ivy better-defaults emacs-lisp
                 (org :variables org-enable-hugo-support t)
                 coffeescript csv elixir erlang scheme html javascript markdown
                 (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rbenv rbenv-installation-dir "/usr/local/" ruby-test-runner 'rspec)
                 shell-scripts yaml react osx git github version-control dash docker nginx systemd wakatime)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by duianto** [comment]
The PR: Fix ivy prompt #12030
has been cherry-picked into the develop branch.
