### ISSUE TITLE
Search project command not work.

### ISSUE THREAD

**Issue by johnny-mh** [syl20bnr/spacemacs#11751]
#### Description :octocat:
search project command not work.

#### Reproduction guide :beetle:
- Start Emacs
- Load any project by `SPC p l`
- Start search project by `SPC /`
- Type some characters

*Observed behaviour:* :eyes: :broken_heart:
Some error occured.

![snack](https://user-images.githubusercontent.com/1061205/50431601-67ac1100-090f-11e9-8c19-ad731cb54dd7.gif)

*Expected behaviour:* :heart: :smile:
Search project properly.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8b3a30f24)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html typescript ivy
      (auto-completion :variables auto-completion-enable-sort-by-usage t)
      emacs-lisp git markdown multiple-cursors neotree
      (version-control :variables version-control-diff-tool 'diff-hl))
```
- System configuration features: RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by goofansu** [comment]
See #11747

**Comment by goofansu** [comment]
@johnny-mh Solved by https://github.com/syl20bnr/spacemacs/pull/11756, can close this.
