### ISSUE TITLE
Select python-backend using .dir-locals.el

### ISSUE THREAD

**Issue by simonpintarelli** [syl20bnr/spacemacs#11774]
#### Description :octocat: 

I'd like to use the anaconda python-backend as
default and then use `.dir-locals.el` to selectively enable the lsp-backend.
Setting the python backend using `.dir-locals.el` has no effect, e.g. anaconda
mode is enabled but not lsp, although the variable `python-backend` is set to lsp.

#### Reproduction guide :beetle:
- Set the backend in `.spacemacs`
```
(python :variables python-backend 'anaconda)
```
- Set the python-backend in `.dir-locals.el`:
```
((python-mode
  (python-backend . lsp)))
```
- open a python file in the corresponding project directory

*Observed behaviour:* :eyes: :broken_heart:
lsp mode is not enabled, although the variable `python-backend` is set to `lsp`.

*Expected behaviour:* :heart: :smile:
The python backend is selected accordingly to the value set in `.dir-locals.el`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ac4c30ee6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(lua helm docker bibtex ipython-notebook
     (python :variables python-backend 'anaconda)
     yaml latex csv github git ranger ibuffer mu4e markdown
     (c-c++ :variables c-c++-backend 'lsp-cquery)
     lsp emacs-lisp themes-megapack sourcetrail semantic multiple-cursors neotree spacemacs-org org org-capture
     (version-control :variables version-control-diff-side 'right version-control-global-margin t)
     auto-completion spell-checking syntax-checking spacemacs-editing-visual)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by beyondpie** [comment]
where you put the `.dir-local.el`? I put it in the root of my project, and find it OK. It will ask me whether or not use the local variable.
