### ISSUE TITLE
Loss of python function and constant error messages.

### ISSUE THREAD

**Issue by cremacs** [syl20bnr/spacemacs#11780]
#### Description :octocat:

After a moderate amount of python usage, get the following error:

<Server error: InvalidPythonEnvironment("Could not get version information for '/Users/default/miniconda/bin/python': OSError(24, 'Too many open files')",)

#### Reproduction guide :beetle:
- Start Emacs
- Using python layer with anaconda backend and (possibly) a conda environment, edit files for about 10 minutes.

*Observed behaviour:* :eyes: :broken_heart:
No autocompletion and constant spamming of above error message.

*Expected behaviour:* :heart: :smile:
Normal python layer behavior.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8b3a30f24)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 bibtex csv git helm html javascript
 (latex :variables latex-enable-auto-fill nil)
 markdown python ranger
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts syntax-checking
 (version-control :variables version-control-global-margin t version-control-diff-tool 'git-gutter))
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:
```

```

**Comment by yuhan0** [comment]
Are you using the latest version of `anaconda-mode`? It might be related to  https://github.com/proofit404/anaconda-mode/issues/169 which was recently fixed.

**Comment by gaasedelen** [comment]
I also have been getting this on a clean install I did about a month ago from master (200.13).

Also related: https://github.com/syl20bnr/spacemacs/issues/11399

I am using whatever the latest version of anaconda is pulled through 200.13 update packages mechanism.

**Comment by samspills** [comment]
I was getting the same error message with the lsp backend, and in my case it was caused by a bug in jedi: https://github.com/davidhalter/jedi/issues/1242

You could try checking your jedi version and updating if you're using one of the affected releases (the fix is in 0.13.2, I think the bug showed up in 0.11 somewhere?)

**Comment by rubic** [comment]
I'm getting the same error message on Ubuntu 18.04, even after upgrading to jedi 0.13.3.  Running anaconda 0.0.1.1.  The _"Too many open files"_ messages start showing up anywhere from 10-30 minutes after working on Python projects.

**Comment by rubic** [comment]
I've switched to `lsp-mode` and no longer get this error messages.
