### ISSUE TITLE
modeline not working at all

### ISSUE THREAD

**Issue by dagnachewa** [syl20bnr/spacemacs#11784]
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

**Comment by dagnachewa** [comment]
my modeline used to look like this https://imgur.com/a/CxB14vK but today I lost the modeline and it looks like this https://imgur.com/a/I9KOnXp

**Comment by boothead** [comment]
@peschkaj How do you pin to melpa stable? I have the same issue. I've tried:

```
  (push '("melpa-stable" . "stable.melpa.org/packages/") configuration-layer--elpa-archives)
  (push '("spaceline" . "melpa-stable") package-pinned-packages)
```

In `dotspacemacs/user-init`.

**Comment by peschkaj** [comment]
You’ll need to add spaceline, all-the-icons, and spaceline-all-the-icons. Once you’ve done that, you need to delete those packages locally and restart spacemacs.

FWIW, I tried this recently and I was unable to get spacemacs to pick up the change successfully. I have done this in emacs using my custom configuration just fine.

**Comment by boothead** [comment]
Thanks @peschkaj! For my future reference (and anyone else who finds themselves here) these are the exact lines I had to add in `dotspacemacs/user-init`:

```
  (add-to-list 'configuration-layer-elpa-archives '("melpa-stable" . "stable.melpa.org/packages/"))
  (add-to-list 'package-pinned-packages '(spaceline . "melpa-stable"))
  (add-to-list 'package-pinned-packages '(spaceline-all-the-icons . "melpa-stable"))
  (add-to-list 'package-pinned-packages '(all-the-icons . "melpa-stable"))
```

**Comment by dagnachewa** [comment]
thanks a lot it worked

**Comment by anmoljagetia** [comment]
Both these solutions don't seem to work for me, and I keep getting the same error. I am facing this after I recently updated the packages in my spacemacs installation. Is there anything I can post here, for some help? I am not very good with elisp, so my understanding can be limited so any help is greatly appreciated.

**Comment by laermannjan** [comment]
@anmoljagetia After applying @boothead 's fix, you need to reinstall the involved packages for it to take effect.

E.g.:
add them to your excluded packages 
```
dotspacemacs-excluded-packages '(
                                all-the-icons  
                                spaceline
                                spaceline-all-the-icons
                                )
```
restart with `SPC q r`, then remove them from the excluded packages list again. Now they are going to be installed from the melpa-stable repo as intended.

Also: The documentation is a little misleading in suggesting to set the mode-line as 
` dotspacemacs-mode-line-theme '(all-the-icons :separator 'slant :separator-scale 1.5)`
Do not use an apostrophe for the separator, i.e. use `slant` instead of `'slant` or whichever separator you like.

**Comment by anmoljagetia** [comment]
Thanks for this @laermannjan! 
I ended up using a PR from the repo, and udating the package to get it to work with my initial setup. I think they finally merged that.

**Comment by bcc32** [comment]
It looks like https://github.com/domtronn/spaceline-all-the-icons.el/pull/101 was merged, so there is no longer a need to pin the package version to melpa-stable.
