### ISSUE TITLE
org-archive-subtree does not work

### ISSUE THREAD

**Issue by dmbfm** [syl20bnr/spacemacs#11788]
#### Description :octocat:
org-archive-subtree does not work.

#### Reproduction guide :beetle:
- Start Emacs
- Open an .org file
- Go to a headline and try to archive it (<C-c C-x C-a> or by calling
  the org-archive-subtree function)

*Observed behaviour:* :eyes: :broken_heart:
I get the following message: 'invalid function: org-preserve-variables' and the
headline is not archive. Neither the org file is changed nor a archive file is
created.

*Expected behaviour:* :heart: :smile:
The headline should be archived.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c28c7d21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
nil```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2

**Comment by dmbfm** [comment]
It also does not work on master. Works fine on vanilla emacs.

**Comment by glogiotatidis** [comment]
I get the same error while refiling issues

**Comment by samspills** [comment]
I also have this issue. But I've noticed a few other issues with the org layer: 
1. `, i t` now raises an error when setting tags (I think it needs to switch to using `org-set-tags-command` in new org release)
2. pressing tab no longer expands `<s`, `<q` etc. into the appropriate block

I'm 80% sure these issues are also related to the new org release. In that case, should a single issue be created to track the updates that need to be made to the org layer? I have a branch with `org-set-tags-command`, but the fix for tab completion and and archiving might be beyond my beginner abilities (I haven't had time to look into these problems yet though).

**Comment by thanhvg** [comment]
> pressing tab no longer expands `<s`, `<q` etc. into the appropriate block

Org 9.2 has dropped this feature, you need org-tempo to re-enable it
https://orgmode.org/Changes.html#org1b5e967

I can't reproduce the org-archive-subtree issue though. I'm on dev branch and packages are up to date

**Comment by samspills** [comment]
I was able to solve the org-archive-subtree issue by deleting all org *.elc files and recompiling. 

I think I will open a pr later today with the new tags command, and perhaps a new binding to open the new insert template menu.

**Comment by sdwolfz** [comment]
I can no longer reproduce this on the latest develop. Master should work again after we release.

**Comment by hyiltiz** [comment]
I understand that bugs happen, but that was such a horrible bug that deletes data. I wish there was some kind of safety net mechanism, not just for `subtree` but for most org basic commands that mutates user data, to make sure it either successfully does what it promises to do, or simply fails.

I had no idea I was losing all of my entries as I "archived" my away into nothingness. I am very skeptical I can retrieve anything and lost a weeks worth of data and work.

**Comment by TS-CUBED** [comment]
Hello, this bug seems to be back as of 15/11/2020, just reset everything on a fresh clone of develop. Exactly the same problem on 0.300.0@26.3
