### ISSUE TITLE
no autocompletion for inferior python REPL

### ISSUE THREAD

**Issue by vv111y** [syl20bnr/spacemacs#11785]
#### Description :octocat:
no autocompletion for inferior python REPL

#### Reproduction guide :beetle:
- Start Emacs
- Open python REPL (either before or after a .py buffer)
- import module, ie ```import numpy as np```
- try to get a completion list ```np.``` hit ```TAB```

*Observed behaviour:* :eyes: :broken_heart:
```[no matches]``` almost always
completions do work for filenames in the current directory, so company is running

*Expected behaviour:* :heart: :smile:
A beautiful popup complete with many completion candidates

I have tried to fix this myself with all sorts of permutations of 'fixes' to no avail.
Also note this is the same for linux. Both machines use same dotfile.  
Using LSP mode.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1624477f2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 ansible better-defaults bibtex
 (c-c++ :variables c-c++-enable-clang-support t)
 chrome
 (clojure :variables clojure-enable-fancify-symbols t)
 (cmake :variables cmake-enable-cmake-ide-support t)
 command-log common-lisp copy-as-format coq cscope csv dap dash debug deft docker emacs-lisp erc
 (ess :variables ess-use-auto-complete t ess-use-eldoc t ess-ask-about-transfile nil)
 fasd finance git github go gpu
 (haskell :variables haskell-completion-backend 'intero)
 helm html hy ibuffer imenu-list ipython-notebook java
 (javascript :variables)
 (julia :variables julia-mode-enable-ess nil)
 (latex :variables latex-enable-folding t latex-enable-auto-fill t latex-build-command "LatexMk" latex-enable-magic t)
 lua lsp multiple-cursors
 (markdown :variables markdown-live-preview-engine 'vmd)
 nim ocaml
 (osx :variables osx-use-option-as-meta t)
 (org :variables org-enable-github-support t org-enable-reveal-js-support t org-enable-bootstrap-support t org-enable-hugo-support t org-startup-indented t org-startup-folded t)
 outshine pandoc pdf-tools php
 (python :variables python-backend 'lsp)
 racket ranger
 (rust :variables rust-format-on-save t)
 (scala :variables scala-auto-insert-asterisk-in-comments t scala-enable-eldoc t scala-indent:use-javadoc-style t)
 scheme search-engine
 (spell-checking :variables spell-checking-enable-by-default nil)
 sql syntax-checking
 (shell :variables shell-default-height 30 shell-default-position 'right)
 themes-megapack tmux
 (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t)
 vagrant version-control yaml zotero)
```
- System configuration features: JPEG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS THREADS LCMS2

#### Backtrace :paw_prints:
```

```

**Comment by absentmindedguy** [comment]
I get the same thing for clojure, no matches almost always

**Comment by next-mad-hatter** [comment]
Could this be the same issue as https://github.com/syl20bnr/spacemacs/issues/11718?

**Comment by next-mad-hatter** [comment]
(Almost) same here.

* The "numpy" in `import numpy as np` gets a completion -- when I do a M-x company-diag with numpy partially typed, I get the following:

```
Emacs 25.3.1 (x86_64-slackware-linux-gnu) of 2017-09-12 on hive64
Company 0.9.9

company-backends: ((company-files company-capf)
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)

Used backend: (company-files company-capf)

Major mode: inferior-python-mode
Prefix: "num"
Completions:
  #("numpy" 0 3 (face (completions-common-part) company-backend company-capf) 3 4 (face (completions-first-difference) company-backend company-capf) 4 5 (company-backend company-capf))
  #("numbers" 0 3 (face (completions-common-part) company-backend company-capf) 3 4 (face (completions-first-difference) company-backend company-capf) 4 7 (company-backend company-capf))
```

* After having typed `np.`, company-diag gives
```
Emacs 25.3.1 (x86_64-slackware-linux-gnu) of 2017-09-12 on hive64
Company 0.9.9

company-backends: ((company-files company-capf)
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)

Used backend: (company-files company-capf)

Major mode: inferior-python-mode
Prefix: "np."
Completions: none
```

AFAICS this behaviour is independent of python completion backend (same with anaconda and lsp).

My .spacemacs file: [dot-spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/2802863/dot-spacemacs.txt)

**Comment by vv111y** [comment]
For no good reason I can see, setting ```pyvenv-workon``` to some environment made it work. But my default, base, environment has all the relevant modules. Note I am executing that while in the REPL buffer.

@next-mad-hatter thanks for showing ```company-diag```, learned some new emacs today. 

Wow, I just tried ```company-diag``` on itself in an elisp buffer and I got a 14MB buffer in response!
```Buffer has 40314 lines, 2243444 words, and 13613493 characters```
That's some completion

**Comment by vv111y** [comment]
Also, I am taking trying out https://github.com/dzop/emacs-jupyter as an alternative. Very promising.

**Comment by next-mad-hatter** [comment]
I'm not even sure company is responsible for completion at this point -- TAB is bound to `python-shell-completion-complete-or-indent` in my case, and I'm not really sure where it comes from -- I'm quite new to emacs and grepping the emacs dir for python-shell-completion only gives me company and ob-ipython as a result (and latter is not active afaics).

Will try to set up a virtual env and see if it helps -- but I'd be very happy to see it work without...

**Comment by PeterChristoph** [comment]
not sure whether i have exactly the same problem. With pyenv activated I do not get any company-completions in the inferior-python buffer. Without pyenv however, company works fine.

**Comment by PeterChristoph** [comment]
edit: it seems that my problem occured, because i activated pyenv from my .emacs without calling ipython. when i call ipython first and activate pyenv, autocompletion works fine.

**Comment by sxdxyxy** [comment]
I have the same problem, but no way to solve it. several days struggle,  reinstall all the package and application, no use.

**Comment by vv111y** [comment]
fwiw I have removed ob-ipython; it is no longer maintained. I put it in `dotspacemacs-excluded-packages` for good measure. What I have works now except lsp occasionally sends rubbish completions. 
I also only use `emacs-jupyter` now.   

Further configs:
```
     (auto-completion :variables
                      auto-completion-return-key-behavior 'complete
                      auto-completion-tab-key-behavior 'cycle
                      auto-completion-enable-help-tooltip 'manual
		     auto-completion-enable-snippets-in-popup nil
                      auto-completion-private-snippets-directory nil
                      ;; auto-completion-complete-with-key-sequence nil
                      auto-completion-complete-with-key-sequence-delay 0.1
                      auto-completion-idle-delay 0.001
                      auto-completion-use-company-box nil
                      auto-completion-enable-sort-by-usage t)
```  

And  

```
  (add-hook 'after-init-hook 'global-company-mode)    ;; jun5-17
  (require 'company)
  (define-key company-mode-map [remap indent-for-tab-command] #'company-indent-or-complete-common) ;; can hit TAB anytime for completions
  (setq company-tooltip-align-annotations nil)
  (setq company-selection-wrap-around t)
  (setq company-lsp-cache-candidates 'auto)   ;; 13/9/18
  ;; (setq lsp-enable-snippet nil)
  (setq company-lsp-enable-snippet nil)
  ;; (add-to-list 'load-path "~/.local/share/icons-in-terminal/") ;; Dec26-18
  (setq lsp-ui-peek-enable t) ;; 14/9/18
  ;; disabled 13/9/18 may not need
  ;; (eval-after-load "company"
  ;;   '(add-to-list 'company-backends 'company-anaconda))

  (custom-set-variables
   '(company-dabbrev-downcase nil)
   '(company-dabbrev-ignore-case nil)
   ;; '(company-idle-delay 0)
   '(company-minimum-prefix-length 2)
   '(company-quickhelp-color-background "gray11")
   '(company-quickhelp-color-foreground "light green")
   '(company-quickhelp-mode t)
   '(company-require-match nil)
   '(company-selection-wrap-around t)
   '(company-statistics-mode t)
   '(company-transformers
     (quote
      (spacemacs//company-transformer-cancel company-sort-by-occurrence company-sort-by-statistics company-sort-by-backend-importance))))
```

**Comment by sxdxyxy** [comment]
> fwiw I have removed ob-ipython; it is no longer maintained. I put it in `dotspacemacs-excluded-packages` for good measure. What I have now works except lsp occasionally sends rubbish completions.
> I also only use `emacs-jupyter` exclusively.
> 
> Further configs:
> 
> ```
>      (auto-completion :variables
>                       auto-completion-return-key-behavior 'complete
>                       auto-completion-tab-key-behavior 'cycle
>                       auto-completion-enable-help-tooltip 'manual
> 		     auto-completion-enable-snippets-in-popup nil
>                       auto-completion-private-snippets-directory nil
>                       ;; auto-completion-complete-with-key-sequence nil
>                       auto-completion-complete-with-key-sequence-delay 0.1
>                       auto-completion-idle-delay 0.001
>                       auto-completion-use-company-box nil
>                       auto-completion-enable-sort-by-usage t)
> ```
> 
> And
> 
> ```
>   (setq company-lsp-cache-candidates 'auto)   ;; 13/9/18
>   (setq company-lsp-enable-snippet nil)
> 
>   (custom-set-variables
> ...
>    '(company-transformers
>      (quote
>       (spacemacs//company-transformer-cancel company-sort-by-occurrence company-sort-by-statistics company-sort-by-backend-importance))))
> ```

I modified my config using SPC  f e d， replace layer configuration as yours ,and add your additional config to user-init 
and add ob-python to  exclusive package, it become fast, but completion and strdoc still does not work.

![image](https://user-images.githubusercontent.com/13362677/75976230-fc979a80-5f14-11ea-9647-ac86698e59ce.png)

![image](https://user-images.githubusercontent.com/13362677/75976280-133df180-5f15-11ea-9d6a-9e49d55cdfe2.png)

**Comment by vv111y** [comment]
When I run `company-diag` in a python buffer I get 
```
Emacs 26.3 (x86_64-apple-darwin18.7.0) of 2019-12-07 on WillMBA.local
Company 0.9.12

company-backends: (company-lsp
 (company-semantic company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)

Used backend: company-lsp
Major mode: python-mode
...
```
What do you get?   
For orgmode I have to look into that.

**Comment by sxdxyxy** [comment]
@vv111y python-mode is always working correctly, but the jupyter and org-src can not. so I code when I run spc a y r and write code in  the web browser, I think this is a alternate solution.

**Comment by neilyio** [comment]
I'm also having this issue, would love some pointers on what to do about it.

**Comment by lebensterben** [comment]
Cannot reproduce.
```
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> python.el: native completion setup loaded
>>> import numpy as np
```

Than everything seems fine to me.
Please provide more details if it's still an issue.
(Make sure to update your system packages, Emacs packages, and Spacemacs first)

**Comment by simohauml** [comment]
I had this issue too, any solutions?

OS: Windows 10
Python: 38.10
spacemacs: 0.999, develop branch
