### ISSUE TITLE
Buffer opens in wrong window when using neotree

### ISSUE THREAD

**Issue by phoe** [syl20bnr/spacemacs#11795]
#### Description :octocat:
Buffer opens in wrong window when using neotree

#### Reproduction guide :beetle:
- Start Emacs
- Open neotree (`SPC f t`)
- Split window
- Select window 2
- Click a file in neotree

*Observed behaviour:* :eyes: :broken_heart:
File opens in window 1 even though window 2 was previously selected

*Expected behaviour:* :heart: :smile:
File should open in window 2

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c28c7d21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(latex javascript sql html markdown helm auto-completion emacs-lisp common-lisp emacs-lisp git org version-control
       (shell :variables shell-default-height 30 shell-default-position 'bottom)
       multiple-cursors neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
None

**Comment by thanhvg** [comment]
We don't use mouse with Spacemacs :) 
If you press enter key instead of mouse click it will work as expected

Anyway sometimes mouse really helps. You may want try to use my crappy code bellow to see if it works. Add the following to your `dotspacemacs/user-config` 
``` elisp
  ;; neo click on file open on active window
  (defun my//neo-wrapper-function (orig-fun &rest args)
    ;; (message "fn called with args %S" args)
    (let* ((added-args (if (second args) args
                         (list (first args)
                               (winum-get-number (get-mru-window)))))
           (res (apply orig-fun added-args)))
      ;; (message "fn called %S returned %S" added-args res)
      res))
  (defun my/mod-neo-click-on-file ()
    (advice-add 'neo-open-file :around #'my//neo-wrapper-function))
  (add-hook 'neotree-mode-hook #'my/mod-neo-click-on-file)

```

**Comment by phoe** [comment]
This workaround seems to work. Thanks!

**Comment by Asalle** [comment]
@syl20bnr this seems to be resolved, maybe close it?

**Comment by phoe** [comment]
@Asalle Has this patch made it into the codebase though?

If the workaround from here is not integrated into code, then new tickets will appear on the same issue.
