### ISSUE TITLE
Org source block babel expansion stopped working

### ISSUE THREAD

**Issue by RockyRoad29** [syl20bnr/spacemacs#11798]
#### Description :octocat:
 
   - DISCLAIMER -- This report may seem wordy or redundant, but I hope it would add
                   a few keywords to help users facing a similar issue.

  According to ["Easy-templates" section in orgmode manual](https://orgmode.org/manual/Easy-templates.html#Easy-templates)
  > "< s TAB expands to a ‘src’ code block. "

When I do that, nothing happends anymore. No other template either 2

#### Reproduction guide :beetle:
  - Start Emacs
  - Create a new file in org-mode, say `/tmp/t.org`
  - Type an "easy template", like "<s"
  - Press TAB to expand

  *Observed behaviour:* :eyes: :broken_heart:
  Not expansion, indentation instead.

  *Expected behaviour:* :heart: :smile:
  Replacement of "<s" with:

```org
# +BEGIN_SRC

# +END_SRC
```

#### Investigations
Thanks to good documentation, it is rather easy:

In `*Messages*` you may read:

      File mode specification error: (wrong-type-argument stringp (#+BEGIN_NOTES
      ?
      #+END_NOTES))

and also an explanation in a `*Warnings*` buffer.

The customizable variable `org-structure-template-alist` is altered somewhere with a "NOTES" entry.

      - help:org-structure-template-alist

Displays the following:

      Hide org-structure-template-alist:
      '(("n" "#+BEGIN_NOTES\n?\n#+END_NOTES")
        ("a" . "export ascii")
        ("c" . "center")
        ("C" . "comment")
        ("e" . "example")
        ("E" . "export")
        ("h" . "export html")
        ("l" . "export latex")
        ("q" . "quote")
        ("s" . "src")
        ("v" . "verse"))
          State : CHANGED outside Customize. (mismatch**
        An alist of keys and block types

The "n" entry is absent from source definition (`~/.emacs.d/elpa/26.1/develop/org-plus-contrib-20181230/org.el`)

  **Suppressing the first entry (e.g. in customize) solves the problem.**

#### Solution : PR in ox-reveal

This is related to a recent change in org-plus-contrib :
https://orgmode.org/Changes.html#outline-container-org1b5e967 .

For me, the responsible appears to be `'ox-reveal'` .

It is actually added in
`/.emacs.d/elpa/develop/ox-reveal-20161027.226/ox-reveal.el`.

This is easy to fix:

```diff
@@ -1185,7 +1185,7 @@ Return output file name."
 ;; Register auto-completion for speaker notes.
 (when org-reveal-note-key-char
   (add-to-list 'org-structure-template-alist
-               (list org-reveal-note-key-char "#+BEGIN_NOTES\n\?\n#+END_NOTES")))
+               (cons org-reveal-note-key-char "notes")))
```

I was about to build a PR but somebody has already submitted an identical one which currently pending.
https://github.com/yjwen/org-reveal/pull/359/commits/21b17507f7e05cbb5fcf8afc1ff3c9fb2c1f30e1

#### Workaround : fix the value in dotfile

To patiently wait until the PR is applied upstream, I tried this, in user-config():

```elisp
  (with-eval-after-load 'ox-reveal
    (let ((entry (assoc "n" org-structure-template-alist)))
      (when (and entry  (string-match-p "BEGIN" (cdr tmp:entry)))
        (setcdr entry "notes")
      )
    )
  )
```
Unfortunately, though the inner code is working (fixes the problem in current session), `with-eval-after-load` doesn't seem
to be the way to do it. I also tried to wrap it in `use-package :config` and
in `configure-layers org` stanza, with no more success.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c28c7d21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion c-c++ csv
                 (dash :variables helm-dash-docset-newpath "~/.local/share/Zeal/Zeal/docsets")
                 docker emacs-lisp erc git graphviz gtags ...
                 (org :variables org-enable-reveal-js-support t org-reveal-root "file:///usr/local/src/reveal.js")
                 ...
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by dqdinh** [comment]
This temp workaround worked for me - https://github.com/yjwen/org-reveal/pull/340#issuecomment-451660990

Add the following to dotspacemacs/user-config:

```
(setq org-reveal-note-key-char nil)
```

Afterwords, one can use `C-c C , s` to insert a src block.

**Comment by dqdinh** [comment]
FYI - this has been fixed. So if you added the work around above, you'll need to remove it.

**Comment by BobCromwell** [comment]
> FYI - this has been fixed. So if you added the work around above, you'll need to remove it.

Which branch? I update develop branch and still meet the same issue.

**Comment by yssource** [comment]
`(setq org-reveal-note-key-char nil)`, does not work for me.
But, 
comment out `org-enable-reveal-js-support t` in org layer, works for me.

**Comment by dqdinh** [comment]
I was using the stable branch but I updated my layers and it resolved the issue I had. I

**Comment by srgkoshelev** [comment]
The template expansion works in master (stable) and doesn't work in develop branch.
Blindly adding
```
  (with-eval-after-load 'ox-reveal
    (setq org-reveal-note-key-char nil)
  )
```
to user-config didn't help.

**Comment by agirdler-sonder** [comment]
@srgkoshelev 
On develop it seems the version of `org-mode` has templating separated and `org-tempo` module is not loaded. I was able to resolve this by adding the following lines to my dotfile to load `org-tempo` for version of `org` >= 9.2 (the abstraction seems to be a part of the [9.2 release](https://orgmode.org/Changes.html#org1b5e967)):

```elisp
  (when (version<= "9.2" (org-version))
    (require 'org-tempo))
```

**Comment by srgkoshelev** [comment]
@agirdler-sonder Thank you, it works!

**Comment by igor-kupczynski** [comment]
I'm on develop. Adding the snippet suggested by @agirdler-sonder works for me:

```elisp
  ;; FIXME: workaround
  ;; https://github.com/syl20bnr/spacemacs/issues/11798
  (when (version<= "9.2" (org-version))
    (require 'org-tempo))
```

By *works* I mean that I can use `< s TAB`.

With `(setq org-reveal-note-key-char nil)` `< s TAB` wasn't working for me, but `C-c C-, s` worked.

**Comment by Anton-Latukha** [comment]
At the time it trickles-down - you can use `SPC m i b s` instead of `<s[TAB}`.

**Comment by collector1871** [comment]
it seems that we need to use `(require 'org-tempo)`

please check at
https://orgmode.org/Changes.html
"Change in the structure template expansion"

so this is official change in org template system. And now `<sTAB` is optional

btw. i am also fan of "good old" templates and i am using `(require 'org-tempo)`. But from consistence point of view, it will be better for emacs to leave org templates/snippets to common and centralized mechanism like `company-mode` or/and `yasnippets`

**Comment by jr0cket** [comment]
I upgraded org-reveal to org-re-reveal using the basic instructions in the issue:
https://github.com/syl20bnr/spacemacs/issues/11935

If you do not wish to use org-reveal, you can simply set `org-enable-reveal-js-support` to `nil` to nil in the org layer or remove it as a variable.

**Comment by pnyccz** [comment]
I have the same problem, or-re-reveal package has helped, however, it broke org-mode-agenda completely.

Using Linux, Emacs 26.1, Spacemacs 0.200.13.

**Comment by shanesveller** [comment]
@pnyccz what sort of problems are you seeing with `org-agenda`, so I know what to look out for after I switched to `org-re-reveal`?

**Comment by pnyccz** [comment]
@shanesveller Agenda and clocking stopped working. Report tables for time spent on various tasks also stopped working. I don't recall seeing other issues.

**Comment by ColeWunderlich** [comment]
I am on the stable branch and this is still broken for me.

**Comment by ZythonNera** [comment]
> 我在稳定的分支上，这对我来说仍然是坏的。



> I am on the stable branch and this is still broken for me.

Adding (require 'org-tempo) to user-config solves the problem of <s <TAB> not working

**Comment by ZythonNera** [comment]
> You can also use Spacemacs menu `SPC m i b s` instead of `<s[TAB}`.
> 
> Special thanks for submission of so informative bug report and having so good discussion here.
@Anton-Latukha
I don't think I found this shortcut in my evil-org-mode

**Comment by Anton-Latukha** [comment]
@ColeWunderlich @ZythonNera 
collector1871 in answer https://github.com/syl20bnr/spacemacs/issues/11798#issuecomment-465259918 already gave a full quality resonce&report&solution. I personally asked him to post it here, and he did. Please read the thread, or at least look at most liked responses in thread before writing. This issue open for people to see the solution and read the explanation.

@ZythonNera
In Emacs "Org major mode" - `SPC m i b` - `org-insert-structure-template` "is an interactive Lisp closure in `org.el`", since 9.2.
Which means it is present in new Org-mode.

Since there seems to be duality of understanding of my old comment, I updated it with precise info, and created an issue.

**Comment by RockyRoad29** [comment]
Well, it's over a year now I'm trying to get used to "the new way" e.g. to insert a source block : ~SPC m i b s~ . I still find it less convenient than ~< s TAB~ . So I'd prefer to see org-tempo style staying around. 
"my 2 cents"

**Comment by Anton-Latukha** [comment]
The real solution is mentioned in the year 1-1.5 years ago, I am using it in that timespan.

**Comment by Anton-Latukha** [comment]
It is https://github.com/syl20bnr/spacemacs/issues/11798#issuecomment-504739959

**Comment by maxsatula** [comment]
There seems to be a problem with `C-,` combination. While it works fine in
1. GNOME terminal
2. GUI non-terminal version of Emacs

It does not work (either simple comma entered or nothing happens) on
1. lxterminal
2. any terminal over ssh
3. in PuTTY

I know, that is not Emacs problem, but I'm not sure about whether it is a good idea to assign troublesome keys in default configuration.
