### ISSUE TITLE
Make sure "." and ".." show up first in Helm `dired-do-rename` or `dired-do-copy`

### ISSUE THREAD

**Issue by log0ymxm** [syl20bnr/spacemacs#11809]
This is one of the most frustrating aspects of using Helm, and I haven't found a way to change this. I use emacs to move files around a lot, and when `.` and `..` aren't first I always seem to clobber existing files and lose track of what I just renamed a file into. Is there any way to get a more default ordering when using Helm?

**Comment by log0ymxm** [comment]
Do you know what functions do the sorting for these helm buffers?

**Comment by duianto** [comment]
I don't know how they are sorted.

When I did a quick search for `helm sort candidates`, then this variable came up:
`helm-locate-fuzzy-sort-fn`.
source: [Allow globally sorting the candidates in an async source](https://github.com/emacs-helm/helm/issues/1657)

It might be a starting point for figuring it out.

And this helm issue might also be helpful:
[Can we add a variable to omit "." and ".." directories?](https://github.com/emacs-helm/helm/issues/1668)

**Comment by log0ymxm** [comment]
It is related to helm fuzzy searching, for now I've just set `dotspacemacs-helm-use-fuzzy 'nil` in the spacemacs config. Better to have predictability for the dot & dot2 candidates rather than the fuzzy search features.

@duianto You might be right, the correct way to do this may be to customize `helm-locate-fuzzy-sort-fn` so that those candidates are at the top when input is empty, but I didn't want hassle with doing that.

Considering that turning off helm fuzzy matching is not really a fix, what packages are used to implement this in spacemacs, maybe this can be isolated to those.

**Comment by duianto** [comment]
These packages are used in the helm layer:
https://github.com/syl20bnr/spacemacs/blob/7af300a225180708ad7e10f7cba2591cdc727ca0/layers/%2Bcompletion/helm/packages.el#L12-L34

I don't know which effect the sorting order.
