### ISSUE TITLE
org-want-todo-bindings broken on develop after org 9.2 release? (not all org-mode-hooks being applied automatically)

### ISSUE THREAD

**Issue by samspills** [syl20bnr/spacemacs#11805]
#### Description :octocat:
`org-want-todo-bindings` is set to `t` in my spacemacs config, but it does not toggle todo status. I can't confirm that something in org 9.2 caused this change but that's the major change to my setup that happened recently. Does anyone else have this problem? 

#### Reproduction guide :beetle:
- Start Emacs
- Set `org-want-todo-bindings` to true in config
- confirm variable setting with `SPC h d v`
- in org file press `t` when on a TODO heading

*Observed behaviour:* :eyes: :broken_heart:
- pressing t calls `evil-find-char-to` 

*Expected behaviour:* :heart: :smile:
- pressing t brings up the org-todo-state tree

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: sam/org-layer-bindings (rev. bf8792736)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html yaml markdown auto-completion spell-checking better-defaults emacs-lisp git
      (org :variables org-want-todo-bindings t)
      (shell :variables shell-default-shell 'eshell)
      syntax-checking plantuml
      (python :variables python-test-runner 'pytest python-fill-column 100)
      sql themes-megapack csv javascript ipython-notebook weechat)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
Not relevant.

**Comment by boothead** [comment]
Same here. I have `org-want-todo-bindings t` and I don't have the todo bindings in spacemacs `develop` anymore.

**Comment by samspills** [comment]
@boothead Thanks for confirming :) I'll look into this later this week / this weekend and let you know if I figure anything out.

**Comment by samspills** [comment]
## Update

The issue seems to be related to hooks. Inspecting the value of `org-mode-hooks` confirms that `evil-org` is there, and I expect the `evil-org` minor mode to be enabled when I open an org file. However this is _not_ happening. If I manually enable `evil-org` then I get the expected behaviour for `t`. (Also, it's not just evil-org mode that isn't being properly hooked, I noticed that org-bullets-mode is also not being automatically enabled)

I'm still trying to figure out what the root cause of this hook issue is though.

**Comment by samspills** [comment]
## Resolution

Some org-mode-hooks (set in the spacemacs org layer) were being ignored because of org-mode-hooks being set elsewhere. For me this broke down into two separates issues that could both cause the problem in isolation.

1. The spacemacs org-layer sets hooks in the init phase, making use of `add-hook`. However, in my personal config, I was adding hooks using the `:hooks` parameter provided by `use-package`. These two methods must be incompatible in some way (I didn't delve into _why_ it wasn't working, I just know that they conflicted). I updated all my own hooks to use the same method as spacemacs, and the problems in my personal config were solved. 

2. including the `ipython-notebook` layer also caused the org-mode-hook issues to happen. I narrowed it down to the setting of an org-mode hook in the function `ipython-notebook/pre-init-ob-ipython`. The hook is currently being set `post-config`. I switched it to be set `post-init` and the problem was resolved. 

I'm going to create a separate issue to discuss the ipython-notebook hook. I don't fully grasp why the hook would interfere with setup when set during `post-config` but not during `post-init`.

cc @boothead I hope this helps you out!

**Comment by boothead** [comment]
Thanks @samspills!
