### ISSUE TITLE
Powerline characters not drawn properly

### ISSUE THREAD

**Issue by sandorex** [syl20bnr/spacemacs#11803]
#### Description :octocat:
Powerline characters are not drawn properly

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Powerline draws incorrectly as shown in this picture ![](https://user-images.githubusercontent.com/18004075/50735572-9187f200-11b1-11e9-9af0-5677124c12dd.png)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm c-c++ auto-completion emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LCMS2

**Comment by sandorex** [comment]
After reading other issues related to powerline and [this comment](https://github.com/syl20bnr/spacemacs/issues/10181#issuecomment-416060683), setting `powerline-height` fixes it but according to the comment it should be calculated automatically

**Comment by smile13241324** [comment]
@sandorex I have just merged a fix for setting powerline-height via hook, can you please check on develop whether this solved your issue.

**Comment by sandorex** [comment]
Unfortunately i changed my OS so i don't think it would be of any help to test on windows now
