### ISSUE TITLE
spacemacs js-beautify error

### ISSUE THREAD

**Issue by lianduy** [syl20bnr/spacemacs#11811]
Hi, I have a problem!

ERROR: Could not apply web-beautify. See *Web Beautify Errors* to for details.

ERROR: Unable to open path "/Users/zukunft/working/higgs/HTKApi/-" Run `js-beautify -h` for help.

What should I do?
<img width="584" alt="2019-01-08 19 33 48" src="https://user-images.githubusercontent.com/7471730/50828654-f0e62d80-137c-11e9-8edd-105b9baa5d5a.png">
<img width="435" alt="2019-01-08 19 33 31" src="https://user-images.githubusercontent.com/7471730/50828663-f8a5d200-137c-11e9-9ad8-a06f5fc94ffa.png">

**Comment by lianduy** [comment]
hi, i run `js-beautify -h`, and it is successful.
<img width="1011" alt="2019-01-09 11 14 44" src="https://user-images.githubusercontent.com/7471730/50874717-1cf6c280-1400-11e9-9b2e-d9653048541b.png">

i run `js-beautify fileName`, and it is successful. so i think `js-beautify` is normal.

**Comment by samspills** [comment]
I've done some googling, and it sounds like there is an issue with the `-` marker not being recognized. See these issues: https://github.com/beautify-web/js-beautify/issues/1609 and https://github.com/yasuyk/web-beautify/issues/38

I still don't think this is a spacemacs issue

**Comment by lianduy** [comment]
Thanks very much！you are right，this is a `js-beautify v1.8.9` issue.

**Comment by kayvank** [comment]
I had the same issue, and the solution worked for me as well: 
`npm install -g js-beautify@1.9.0-beta2`

**Comment by iromise** [comment]
Now the js-beautify 1.9.0 is out. It works well.

**Comment by aswinmohanme** [comment]
js-beautify 1.9.0 fixes the issue can be closed
