### ISSUE TITLE
Spacemacs version on top of the *Spacemacs* buffer is unnecessarily split over two lines

### ISSUE THREAD

**Issue by phoe** [syl20bnr/spacemacs#11816]
#### Description :octocat:
Spacemacs version on top of the buffer is unnecessarily split over two lines - the last closing parenthesis spills over to the next line.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
![zrzut ekranu z 2019-01-09 12-13-47](https://user-images.githubusercontent.com/15045546/50896007-10766800-1408-11e9-90c6-274dab34de54.png)

*Expected behaviour:* :heart: :smile:
No lone closing parentheses on the second line of the buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c28c7d21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(latex javascript sql html markdown helm auto-completion emacs-lisp common-lisp emacs-lisp git org version-control
       (shell :variables shell-default-height 30 shell-default-position 'bottom)
       multiple-cursors neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:

**Comment by duianto** [comment]
The screenshot and system info do not match.

The screenshot shows the master branch 0.200.13 in what seems to be a terminal.
The system info says that it's the develop branch 0.300.0, running in a gui (`Graphic display: t`).

The issue does not occur in Gui Emacs on either the master and develop branches in 
Windows 10 or Ubuntu 18.04.1.

But in the Windows command prompt, Windows powershell and Ubuntu terminal, the closing parenthesis is outside the frames right edge and if `SPC t l` (lowercase L) (`truncate-lines`) is disabled, then the closing parenthesis wraps to the second line (like the screenshot shows).

A PR has been submitted.

**Comment by phoe** [comment]
Yes, sorry - here is a better screenshot. The issue seems to occur both on master and develop in terminal, hence the mismatch in the original info.

![zrzut ekranu z 2019-01-24 22-51-10](https://user-images.githubusercontent.com/15045546/51710816-93173e00-202a-11e9-9c5d-5db1dab4c0b9.png)

**Comment by duianto** [comment]
Np, I submitted a possible fix. It reduces the version line by one character if Emacs is running in a terminal.

**Comment by duianto** [comment]
This issue has been fixed on the develop branch.

**Comment by phoe** [comment]
Thanks!
