### ISSUE TITLE
Display :0 does not exist

### ISSUE THREAD

**Issue by sephii** [syl20bnr/spacemacs#11812]
#### Description :octocat:
Some commands fail with message `Display :0 does not exist`.

#### Reproduction guide :beetle:
- Start Emacs
- Create a buffer and activate python-mode
- Go in insert mode and type `foo = defaultdict(list)` 
- Exit insert mode, put the cursor on `defaultdict`
- Type `, r f` to run `importmagic-fix-symbol-at-point`

*Observed behaviour:* :eyes: :broken_heart:
The error `Display :0 does not exist` shows up. In some rare circumstances it doesn't, but I couldn't figure out why.

*Expected behaviour:* :heart: :smile:
No error shows up and import magic is run.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c28c7d21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(elm ansible yaml php javascript markdown html python helm auto-completion better-defaults git org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     syntax-checking version-control themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
I had to remove some parts of the backtrace because it's too long to paste.
```
Debugger entered--Lisp error: (error "Display :0 does not exist")
  signal(error ("Display :0 does not exist"))
  error("Display %s does not exist" ":0")
  get-device-terminal(":0")
  frames-on-display-list(":0")
  framep-on-display(":0")
  display-pixel-height(":0")
  helm-display-buffer-in-own-frame("*helm-mode-importmagic-fix-symbol*" nil)
  helm-display-buffer("*helm-mode-importmagic-fix-symbol*" noresume)
  helm-completing-read-default-1("Querying for defaultdict: " ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict") nil t nil nil ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict") nil "importmagic-fix-symbol" "*helm-mode-importmagic-fix-symbol*" t)
  helm-completing-read-default-handler("Querying for defaultdict: " ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict") nil t nil nil ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict") nil "importmagic-fix-symbol" "*helm-mode-importmagic-fix-symbol*")
  helm--completing-read-default("Querying for defaultdict: " ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict") nil t nil nil ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict") nil)
  apply(helm--completing-read-default ("Querying for defaultdict: " ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict") nil t nil nil ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict") nil))
  #[128 "\300\301\"\207" [apply helm--completing-read-default completing-read-default nil] 4 nil]("Querying for defaultdict: " ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict") nil t nil nil ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict") nil)
  completing-read("Querying for defaultdict: " ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict") nil t nil nil ("from collections import defaultdict" "from lib2to3.btm_matcher import defaultdict"))
  importmagic-fix-symbol("defaultdict")
  importmagic-fix-symbol-at-point()
  funcall-interactively(importmagic-fix-symbol-at-point)
  call-interactively(importmagic-fix-symbol-at-point nil nil)
  command-execute(importmagic-fix-symbol-at-point)
```

**Comment by dangom** [comment]
Likely a problem with your environment file. Check on a terminal what's the output of DISPLAY and make sure that you get the same value when you call (getenv "DISPLAY"). Check your file .spacemacs.env and see what the DISPLAY variable looks like.

If you find inconsistencies, fix them. Check the docs of functions `spacemacs/load-spacemacs-env` for more infos.

**Comment by sephii** [comment]
Thanks! I checked my `.spacemacs.env` file and noticed there was some garbage in it, like warnings returned from the shell. I removed the weird lines and it seems to have fixed the problem. :tada:
