### ISSUE TITLE
Terminal cursor movement

### ISSUE THREAD

**Issue by shaunpatel** [syl20bnr/spacemacs#11813]
#### Description :octocat:
Unable to move cursor up in ansi-terminal window (SPC ') to copy output of command (e.g. pwd)

#### Reproduction guide :beetle:
- Start Emacs
- Open termina (SPC ')

*Observed behaviour:* :eyes: :broken_heart:
The cursor remains on the current line is unable to be moved up to access output from previous commands.

*Expected behaviour:* :heart: :smile:
Previously was able to move up to copy output.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion bibtex better-defaults emacs-lisp git helm ibuffer markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 python ranger spell-checking syntax-checking version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by shane-segal** [comment]
Can confirm that this also happens on MacOS with Spacemacs on the develop branch. You can get around this by hitting `C-c j` to enable navigation around the terminal buffer, and then hitting `C-c k` to be able to enter commands normally again.
