### ISSUE TITLE
Void function definition `frame-parent` on spacemacs/ace-delete-window

### ISSUE THREAD

**Issue by cubranic** [syl20bnr/spacemacs#11817]
#### Description :octocat:
Void function definition `frame-parent` on spacemacs/ace-delete-window

#### Reproduction guide :beetle:
- Start Emacs
- create another window
- press `SPC w D` (`spacemacs/ace-delete-window`)

*Observed behaviour:* :eyes: :broken_heart:
Error message in minibuffer "Symbol's function definition is void: frame-parent"

*Expected behaviour:* :heart: :smile:
Overlay character shortcuts over each buffer to let me choose which window to close.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c28c7d21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(go html ansible ivy auto-completion emacs-lisp git markdown org
    (python :variables python-test-runner 'pytest)
    ranger ruby syntax-checking yaml)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by stuglaser** [comment]
This might be related to a bug in ace-window: https://github.com/abo-abo/ace-window/issues/152

**Comment by cubranic** [comment]
I'm pretty sure it's because `frame-parent` was introduced in Emacs (commit emacs-mirror/emacs@3fdd3bb56c006a2a24761b8fcea0cbd9b0cba422), and I am running 25.1.1.

I'm not sure if this is something Spacemacs can or should work around. It does seem way to restrictive to have to run off the latest Emacs release though.

**Comment by cubranic** [comment]
The problem went away for me when I upgraded my Emacs (to 26.1 at the time), and since the source of the bug, abo-abo/ace-window#152, has been fixed, we can close this too. Thanks for the pointer @stuglaser!
