### ISSUE TITLE
org-align-all-tags   , =  Not working with org 9.2

### ISSUE THREAD

**Issue by snuffop** [syl20bnr/spacemacs#11818]
#### Description :octocat:
org-align-all-tags command returns

Wrong type argument: commandp, org-align-all-tags 

#### Reproduction guide :beetle:
- Start Emacs
- Open org file or change to org mode
- [spacemacs] , =

- SPC SPC / M-x  org-align-all-tags is missing

- SPC h d v   org-align-all-tags returns:

```
org-align-all-tags is a compiled Lisp function in ‘org-compat.el’.

(org-align-all-tags)

This function is obsolete since Org 9.2;
use `org-align-tags' instead.

Align the tags in all headings.
```

*Observed behaviour:* :eyes: :broken_heart:

Wrong type argument: commandp, org-align-all-tags 

*Expected behaviour:* :heart: :smile:

Tags to align to (in my case) 80th column

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 03eb7d7c2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-idle-delay 1 auto-completion-enable-sort-by-usage t)
 bm better-defaults colors csv deft docker emacs-lisp
 (elfeed :variables rmh-elfeed-org-files
         (list
          (expand-file-name "elfeed.org" dotspacemacs-directory)))
 evil-commentary finance git
 (gtags :variables gtags-enable-by-default t)
 html
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 imenu-list
 (ivy :variables ivy-extra-directories nil ivy-enable-advanced-buffer-information t)
 (javascript :variables javascript-backend 'lsp)
 json latex markdown major-modes multiple-cursors neotree nginx pass pdf php prodigy
 (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save t python-sort-imports-on-save t python-backend 'anaconda)
 (ranger :variables ranger-show-preview t ranger-cleanup-on-disable t ranger-cleanup-eagerly t ranger-enter-with-minus t ranger-ignored-extensions
         '("mkv" "iso" "mp4")
         ranger-parent-depth 1 ranger-width-parents 0.1 ranger-max-parent-width 0.12 ranger-max-preview-size 10 ranger-show-dotfiles t)
 ruby rust salt semantic shell-scripts
 (shell :variables shell-default-shell 'ansi-term shell-default-position 'bottom shell-default-height 30 shell-enable-smart-eshell t shell-protect-eshell-prompt nil shell-default-full-span nil)
 (spell-checking :variables enable-flyspell-auto-completion t spell-checking-enable-auto-dictionary t spell-checking-enable-by-default t)
 sql
 (syntax-checking :variables syntax-checking-enable-tooltips t syntax-checking-use-original-bitmaps t)
 systemd theming
 (templates :variables templates-private-directory "~/.spacemacs/local/templates")
 vim-empty-lines
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t version-control-diff-side 'left)
 (wakatime :variables wakatime-api-key "e4f06099-c203-47e0-ad88-785182dcb8a5" wakatime-cli-path "/usr/bin/wakatime")
 xclipboard yaml marty-base marty-org marty-mu4e marty-org-gcal counsel-tramp paperless outshine weechat)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by snuffop** [comment]
.;; -*- lexical-binding: t -*-
(configuration-layer/declare-layer
 '(org :variables
       org-directory "~/Notes/org/"
       org-agenda-files '(
                          "~/Notes/org"
                          "~/Notes/calendar"
                          "~/Notes/org/journal"
                          "~/Source/NSI/NSI-Documentation")
       org-clock-out-remove-zero-time-clocks t
       org-clock-persist t
       org-clock-persist-query-resume nil
       org-completion-use-ide t
       org-contacts-files (concat org-directory "contacts.org")
       org-default-notes-file (concat org-directory "0mobile.org")
       org-ellipsis " ⤵"
       org-enable-github-support t
       org-enable-hugo-support t
       org-enable-org-journal-support t
       org-fontify-done-headline nil
       org-fontify-quote-and-verse-blocks nil
       org-fontify-whole-heading-line t
       org-hide-leading-stars t
       org-icalendar-include-todo "all"
       org-journal-date-format "%A, %B %d %Y"
       org-journal-date-prefix "#+TITLE: Daily Notes for "
       org-journal-dir (concat org-directory "journal")
       org-journal-enable-agenda-integration t
       org-journal-time-format "%k:%M "
       org-journal-time-prefix "** "
       org-icalendar-store-UID t
       org-id-locations-file "~/Notes/org-id-locations"
       org-id-track-globally t
       org-log-done t
       org-log-into-drawer 1
       org-refile-targets '((nil :maxlevel . 9) (org-agenda-files :maxlevel . 9))
       org-tags-column -80
       org-want-todo-bindings t
       spaceline-org-clock-p t
       spaceline-org-pomodoro-p t
       )
 )

**Comment by snuffop** [comment]
`(defconst marty-org-packages '(
                               (org-subtask-reset :location local)
                               org-bullets
                               (org-jira
                                :location (recipe
                                           :fetcher github
                                           :repo "ahungry/org-jira"
                                           :branch"master"))
                               ))

;;; Code
;;;; org-subtask-reset local packages INIT

(defun marty-org/init-org-subtask-reset()
  (use-package org-subtask-reset
    :after org))

;;;; Org-bullets post

(defun marty-org/post-init-org-bullets ()
  (use-package org-bullets
    :ensure t
    :init
    (add-hook 'org-mode-hook 'org-bullets-mode)))

;;;; org contacts post

(defun marty-org/post-init-org-contacts ()
  (use-package org-contacts
    :ensure nil
    :after org
    :custom (org-contacts-files '("~/Notes/org/contacts.org"))))

;;;; org-jira

(defun marty-org/init-org-jira ()
  (use-package org-jira
    :defer t
    :init
    (progn
      (spacemacs/declare-prefix-for-mode 'org-mode "mj" "jira")
      (spacemacs/declare-prefix-for-mode 'org-mode "mjp" "projects")
      (spacemacs/declare-prefix-for-mode 'org-mode "mji" "issues")
      (spacemacs/declare-prefix-for-mode 'org-mode "mjs" "subtasks")
      (spacemacs/declare-prefix-for-mode 'org-mode "mjc" "comments")
      (spacemacs/declare-prefix-for-mode 'org-mode "mjt" "todos")
      (spacemacs/set-leader-keys-for-major-mode 'org-mode
        "jpg" 'org-jira-get-projects
        "jib" 'org-jira-browse-issue
        "jig" 'org-jira-get-issues
        "jih" 'org-jira-get-issues-headonly
        "jif" 'org-jira-get-issues-from-filter-headonly
        "jiF" 'org-jira-get-issues-from-filter
        "jiu" 'org-jira-update-issue
        "jiw" 'org-jira-progress-issue
        "jir" 'org-jira-refresh-issue
        "jic" 'org-jira-create-issue
        "jik" 'org-jira-copy-current-issue-key
        "jsc" 'org-jira-create-subtask
        "jsg" 'org-jira-get-subtasks
        "jcu" 'org-jira-update-comment
        "jtj" 'org-jira-todo-to-jira)
      )
    ))

;;; packages.el ends here
`

**Comment by snuffop** [comment]
etc

**Comment by snuffop** [comment]
I don't believe it is specific to spacemacs   I've traced it down to (it was) in org-contrib.. but doesn't seem to be there any longer

**Comment by plattyfish** [comment]
OK, nothing seems to be working and no options to align tags in a buffer. 
![Screenshot from 2022-10-19 20-27-02](https://user-images.githubusercontent.com/63901922/196785821-92cc3800-62e9-4266-849e-d1299686b459.png)
