### ISSUE TITLE
Spacemacs overrides the OS mouse cursor with no feature to disable

### ISSUE THREAD

**Issue by jonathanj** [syl20bnr/spacemacs#1181]
Using the solarized-dark theme (and all the other bundled themes I tested) the mouse cursor colours are set to values different from the regular OS values. In some cases this might be desirable but it would be nice if it was possible to not have the cursor changed.

I couldn't figure out how to undo these changes after they were applied either at runtime (I tried `set-mouse-color`) or by commenting all "mouse" lines in `.emacs.d/spacemacs/extensions/solarized-theme/solarized.el`.

On OS X using solarized-dark I think the default OS X cursor has far better visibility than the customized one, in my opinion anyway.

Spacemacs cursor:
![spacemacs_cursor](https://cloud.githubusercontent.com/assets/112166/7162785/d5e4950e-e396-11e4-9ec5-192196b5930c.png)

OS X cursor:
![os_cursor](https://cloud.githubusercontent.com/assets/112166/7162789/dc869a06-e396-11e4-8021-28c93d476fb4.png)

**Comment by syl20bnr** [comment]
I looked for this issue a bit and did not find anything useful, with a dark theme I would go with `(set-mouse-color "white").

**Comment by jonathanj** [comment]
For what it's worth this doesn't happen with my old (pre-Spacemacs) config that uses the "sanityinc-solarized-dark" theme.

**Comment by StreakyCobra** [comment]
@jonathanj [You said](https://github.com/syl20bnr/spacemacs/pull/1239#issuecomment-94282941) this issue has been solved, right?

**Comment by jonathanj** [comment]
@StreakyCobra Yes, it looks like it has been solved and appears in Spacemacs develop.
