### ISSUE TITLE
Unable to open helm transient state

### ISSUE THREAD

**Issue by skebanga** [syl20bnr/spacemacs#11829]
#### Description :octocat:
Unable to open helm transient state (`M-SPC`) as my window manager has reserved `M-SPC` for itself

#### Reproduction guide :beetle:
- Start Emacs (on Ubuntu 18.04 using stock Gnome window manager)
- Open helm mini-buffer (eg: `SPC-b-b`)
- Press `M-SPC`

*Observed behaviour:* :eyes: :broken_heart:
Gnome context menu appears as if I had right-clicked on the emacs menu bar

![popup](https://i.imgur.com/SDufTxZ.png)

*Expected behaviour:* :heart: :smile:
Helm transient state appears

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c28c7d21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp html javascript go lua octave csv git markdown neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      imenu-list version-control
      (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
      (ranger :variables ranger-show-literal nil)
      python yaml lori-cpp
      (smart-tabs :variables smart-tabs-default-insinuations
                  '(c c++))
      protobuf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by sdwolfz** [comment]
This behaviour is probably controlled from gnome itself and has nothing to do with emacs. Check gnome's keybinding settings to see what `M-SPC` is bound to.

**Comment by geoffreyvanwyk** [comment]
On Windows, `M-SPC` is bound to the [shortcut menu for the current window](https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec#WindowsVersion=Windows_10). 

Is it possible to change the shortcut for the Helm transient state?
