### ISSUE TITLE
Extending spacemacs|define-text-object

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#1182]
Currently defining text object uses the actual text and composes a regex-object as the text object.  This allows us to define the text object in both `evil-surround` and `evil` so that it remains consistent. 

One improvement could be to extend text-object movement by defining next / previous operators. 

In order to allow major-mode specific maps, we will also need to make evil-outer / inner-object-maps as buffer-local.   By using hooks, we can make these objects major mode specific such that within spacemacs we define text objects for functions and methods simply by surround the selected text in a certain manner. 

Another thing we can try is to add the surround maps to guidekey (if possible) so that we can see the possible objects to be added.

**Comment by syl20bnr** [comment]
What do you want to discuss about this topic ?
If you want to go this route maybe we can consider to make a package to correctly integrate it in spacemacs. Say you create `evil-extend-text-objects`, we can put it in spacemacs layer, then in each language layer we can define a `<layer>/post-init-evil-extend-objects` function to add major-specific text objects related to the layer.

As a side note: To select some text based on the semantic of the language there is `expand-region` on `SPC v`, it can prevent us from defining a lot of text objects. When it is well defined it even allows to select inner or outer text objects. Obviously it cannot catch all the useful text objects though.

**Comment by ralesi** [comment]
I am not sure a simple macro deserves its own package. 

Perhaps if we extend it properly it can, but at this point it is just a macro to add real text objects to `evil` and `evil-surround`.  The primary use-case I can see for this macro in spacemacs is that the contrib lang layers can make use of it to add buffer-local maps.
