### ISSUE TITLE
org-brain: Properties drawer leaking into Entry

### ISSUE THREAD

**Issue by srgkoshelev** [syl20bnr/spacemacs#11823]
#### Description :octocat:
When creating a first header child for an empty file org-brain-visualize shows child's properties as parent's entry.

#### Reproduction guide :beetle:
- Start Emacs
- SPC a o b (org-brain-visualize)
- (Start a new brain)
- Add a header child (h)

*Observed behaviour:* :eyes: :broken_heart:
Contains of child's Properties drawer in Parent's Entry

*Expected behaviour:* :heart: :smile:
Empty entry 

*Notes*
Description and some pictures are at https://github.com/Kungsgeten/org-brain/issues/142
I have reinstalled spacemacs with no result. The issue is consistent.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c28c7d21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm emacs-lisp git org finance)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by dangom** [comment]
Does the issue happen if you use Emacs w/o Spacemacs? If yes, or if you don't know the answer to that question, then I suggest closing this issue and posting your question at the upstream repository, i.e., org-brain.

**Comment by srgkoshelev** [comment]
I am not sure I know how to run emacs w/o Spacemacs.

Also, I did open an issue for org-brain but the author was unable to reproduce it.

**Comment by srgkoshelev** [comment]
Thanks to a very nice person the issue has been reproduced on bare emacs:
https://github.com/Kungsgeten/org-brain/issues/142#issuecomment-484724724
As it is mentioned in the comment, the issue is not with spacemacs but org-brain package itself.
