### ISSUE TITLE
org-mode hook set with spacemacs|use-package-add-hook preventing other hooks from being enabled properly

### ISSUE THREAD

**Issue by samspills** [syl20bnr/spacemacs#11832]
#### Description :octocat:
When `spacemacs|use-package-add-hook` is used to add a `post-config` hook to org, it interferes with other org-mode hooks that already set in spacemacs-org and org layers. 

*Debugging work*: I switched the hook from `post-config` to `post-init` and that seemed to solve the problem but I don't understand why. I can submit a PR to fix it (and also check to see if any other intances of the issue exist) but I don't want to without actually understanding whats going on.

#### Reproduction guide :beetle:
- Start Emacs (vim mode, with only org-mode and ipython-notebook layers, user-config is empty)
- open any org file

*Observed behaviour:* :eyes: :broken_heart:
- no pretty bullets, org-bullets-mode is not enabled
- evil-org is not enabled

*Expected behaviour:* :heart: :smile:
- evil-org and org-bullets-mode minor modes enabled
- pretty bullets, evil-org keybindings available

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c28c7d21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((org :variables org-want-todo-bindings t)
 ipython-notebook)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
Not sure if relevant?

**Comment by boothead** [comment]
Not sure if this helps, but I noticed a similar problem with `C-c C-c` not working when adding a note during state change. When I comment this function

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+completion/ivy/funcs.el#L320

from the `ivy/post-init-org` function here https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bcompletion/ivy/packages.el#L277

it starts working again.

I really don't understand enough elisp to poke further...

**Comment by boothead** [comment]
I raised #11844
