### ISSUE TITLE
[Documentation update] Python layer: anaconda dependency

### ISSUE THREAD

**Issue by TerryTsao** [syl20bnr/spacemacs#11830]
The readme in python layer has this:

```python
pip install --upgrade "jedi>=0.9.0" "json-rpc>=1.8.1" "service_factory>=0.1.5"
```

However, that's not the case as of today. I'm a newbie, so I have no idea how to correct this. 

---

###### The rest description in detail is just for some other newbie like me in the future. Hopefully they can google it out quickly, w/o spending several hours to get this to work.

Just move from vim to spacemacs for a few days. I've been trying to get auto completion to work correctly in python. And finally I found out why.

After seeing this https://github.com/syl20bnr/spacemacs/issues/9777#issuecomment-340658408, I went to look at `*anaconda mode*` buffer. It says about `jedi` requires >=13.0 or sth. However, I had 12.0. Deep, I know.

Now it's perfect. Much better than what I had in vim. Thank you all for spacemacs to work out of the box perfectly. :smile:

**Comment by bet4it** [comment]
Refer: #11546
