### ISSUE TITLE
Org-mode file under RCS. When opened this way, no longer shows fancy-formatted bullets etc. How to fix?

### ISSUE THREAD

**Issue by ArenT1981** [syl20bnr/spacemacs#11834]
Hello - thanks for all the effort put into Spacemacs.

Quick question. So I have a big org file with important material in, so I consequently decided to use Emacs built in RCS to put it under version control. That works great.

Just one problem. I no longer get the super-lovely fancy formatting that you get with Spacemacs when opening the org file. So instead of lovely pimped up bullet points and different text sizes based on headings, it is just showing everything in the same standard font with however many actual asterisks are there in the raw text itself. The syntax colouring and folding is working, but that is all.

So now, after opening the file, I then have to check out a version for editing. This seems to have interfered with the fancy auto-formatting process. Is there a command I can issue to get it to re-parse the now editable file so that it looks sexy again? I've tried 'revert-buffer' and 'redraw-screen', neither made a difference. Switching/toggling syntax highlighting on/off also didn't make a difference, which makes sense, sine I guess it is some other package entirely that does the super-prettifying. I can't see anything relevant in the org major mode menu either. I'm confused as to why RCS has interfered with this, since presumably the fancy formatting involved is purely something done on the fly anyway, with no effect on the original file. Guess it must be some special file metadata tag/block that tells Emacs it is a RCS controlled file...

Anyway, anyone here know the answer?

I want the fancy formatting back, but I'm storing some important/substantial material in these org files, so I want to make use of Emacs handy per-file version control.

Thanks.

**Comment by jjzmajic** [comment]
I didn't change anything at all, but my `org-bullets` went away too. The rest of the fancy formatting is still there though. Toggling `org-bullet-mode` works, and I checked, it's still in `org-mode-hook` but it doesn't seem to be getting called.

**Comment by duianto** [comment]
What's both of your system info? `SPC h d s`

This is what this example org file looks like for me on the latest develop branch with updated packages.

![emacs_2019-04-26_19-17-24](https://user-images.githubusercontent.com/13420573/56824899-1d548580-6858-11e9-979c-d1ed315ea6b3.png)

```
# source: org example file
# http://eschulte.github.io/org-scraps/scraps/2011-02-21-new-lists.html
** new lists
   :PROPERTIES:
   :DATE:     2011-02-21
   :END:
*** results embedded inside of a list
    :PROPERTIES:
    :DATE:     2011-02-22
    :END:
1. this has results
   #+name: something-in-a-list
   : foo
2. and this doesn't work
   #+begin_src emacs-lisp :var data=something-in-a-list
     data
   #+end_src

   #+name:
   : foo

*** reading and writing
    :PROPERTIES:
    :DATE:     2011-02-22
    :END:
#+name: simple-list
- 1
- two
- 3
- four


#+name: simple-list
#+begin_src emacs-lisp :var lst=simple-list :results list
  (reverse lst)
#+end_src

#+RESULTS: simple-list
- ("four")
- ("3")
- ("two")
- ("1")
```

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9665670f8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm javascript multiple-cursors org spell-checking treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
I'm seeing the same thing in Ubuntu:

![VirtualBoxVM_2019-04-26_19-24-31](https://user-images.githubusercontent.com/13420573/56825278-f8144700-6858-11e9-8469-9c24db6d84f3.png)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9665670f8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

**Comment by jjzmajic** [comment]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9665670f8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm better-defaults
      (neotree :variables neo-theme 'ascii neo-autorefresh t neo-mode-line-type 'default)
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell shell-enable-smart-eshell nil)
      spell-checking
      (syntax-checking :variables syntax-checking-enable-by-default t flycheck-global-modes t)
      (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-return-key-behavior 'complete)
      multiple-cursors
      (ranger :variables ranger-parent-depth 2 ranger-show-hidden nil ranger-show-preview t ranger-cleanup-on-disable t ranger-ignored-extensions
              '("mkv" "iso" "mp4"))
      version-control git debug cscope semantic dap lsp tern web-beautify prettier
      (dash :variables helm-dash-docset-newpath "~/.local/share/Zeal/Zeal/docsets" helm-dash-browser-func 'eww)
      emacs-lisp vimscript shell-scripts systemd
      (c-c++ :variabes c-c++-enable-clang-support nil c-basic-offset 4 c-default-style "linux" clang-format-style "WebKit")
      nim
      (java :variables java-backend 'lsp lsp-eldoc-enable-hover nil)
      (python :variables python-backend 'anaconda)
      (javascript :variabes javascript-fmt-tool 'prettier javascript-backend 'tern node-add-modules-path t js2-include-node-externs t)
      (typescript :variabes typescript-fmt-tool 'prettier typescript-backend 'tide tide-tsserver-executable "/usr/bin/tsserver")
      html
      (org :variables org-highlight-latex-and-related
           '(latex script entities)
           org-enable-github-support t org-enable-bootstrap-support t org-enable-reveal-js-support t org-agenda-files "/home/uros/Sync/org/agendarc" org-adapt-indentation nil org-todo-keywords
           '((sequence "TODO" "|" "DONE" "CANCELED" "NODO"))
           org-enable-org-journal-support t org-latex-pdf-process
           (list "latexmk -f -pdf %f"))
      pdf latex
      (bibtex :variables org-agenda-list t org-ref-default-bibliography
              '("~/Papers/references.bib")
              org-ref-pdf-directory "~/Papers/" org-ref-bibliography-notes "~/Papers/notes.org" org-latex-to-pdf-process
              '("latexmk -pdf %f")
              bibtex-completion-bibliography "~/Papers/references.bib" bibtex-completion-library-path "~/Papers" bibtex-completion-notes-path "~/Papers/notes.org" bibtex-dialect 'biblatex)
      markdown restructuredtext sphinx ess csv ipython-notebook themes-megapack theming colors)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by jjzmajic** [comment]
![org-bullet_issue](https://user-images.githubusercontent.com/24733181/56837482-66441400-682f-11e9-8ad9-9544845464df.png)

**Comment by jjzmajic** [comment]
@duianto did a fresh clone as well, the issue persists. even adding the `org-mode` hook manually achieves nothing

**Comment by duianto** [comment]
@jjzmajic 
I first tried to add the same org layer variables (one by one, and restarting Spacemacs in between), as in your system info: https://github.com/syl20bnr/spacemacs/issues/11834#issuecomment-487206507

But the issue didn't happen, so I tried the `bibtex` layer and variables one by one (since at least some of the variables are org related), but the issue didn't occur there either.

That's when I decided to try your exact layer/variable setup, and now I'm seeing the same thing, the headings show all of the `*` characters:

![emacs_2019-04-28_00-36-46](https://user-images.githubusercontent.com/13420573/56855793-f5474e00-694d-11e9-9b27-8e1385ffd67b.png)

I don't know if it's related but when I try to open the test org file, then nothing happens for 10 seconds when the minibuffer shows this message:
>File mode specification error: (json-readtable-error 39)

and after 10 more seconds, the org file opens.

**Comment by jjzmajic** [comment]
Hmmmm, interesting, I don't get the 10 second thing at all. I never thought the issue could be outside the org setup part. I'll start bisecting and I'll let you know how it goes

**Comment by duianto** [comment]
This is just a guess, but I didn't change any of the paths, to actual paths in Windows, so maybe Emacs keeps searching for something until it times out.

**Comment by jjzmajic** [comment]
aaaand git pull --rebase and it's gone

**Comment by jjzmajic** [comment]
![org-bullet_update_fixed](https://user-images.githubusercontent.com/24733181/56907406-05981f80-6a59-11e9-91dc-64debdc415bd.png)

Don't see any glaring org-related changes

**Comment by jjzmajic** [comment]
Commenting all of my config out and then back in has shown the following: Whatever the problem is, it will not appear when the package causing it is first installed, it only happens after a restart (and also expains why it happened that one time after an update). I'll repeat the process again later today, this time taking care to restart emacs twice after every edit and i'll report my results.

**Comment by jjzmajic** [comment]
Found it! The culprit is the `ipython-notebook` layer, *but only after the second time Emacs is restarted* after the layer is added.

**Comment by duianto** [comment]
It seems to be some interaction between the `org` and `ipython-notebook` layers.

The issue occurs when both of them are in the configuration layers list.

It doesn't happen when they are present without the other one.

I'm seeing the same error message as mentioned in a previous comment, when both layers are uncommented and an .org file is opened:
>File mode specification error: (json-readtable-error 39)

**Comment by duianto** [comment]
The org-bullets appear correctly, and the json error message doesn't appear, after installing jupyter:
```
pip install jupyter
```
