### ISSUE TITLE
ESS major mode key bindings undefined

### ISSUE THREAD

**Issue by paupereira** [syl20bnr/spacemacs#11831]
#### Description :octocat:
ESS major mode key bindings (`SPC m`) are missing.
I've tried the solutions proposed in #11371 to no avail.

#### Reproduction guide :beetle:
- Start Emacs
- Open R script.
- Press `SPC m` (or ,).

*Observed behaviour:* :eyes: :broken_heart:
See `SPC m is undefined` message.

*Expected behaviour:* :heart: :smile:
ESS' major mode keybindings appear.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c28c7d21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(markdown pandoc ess julia scala html helm auto-completion better-defaults emacs-lisp clojure git multiple-cursors colors neotree org
          (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'shell shell-default-term-shell "/bin/zsh"))
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2 GMP

#### Backtrace :paw_prints:
```
```

**Comment by gdkrmr** [comment]
I can confirm this, R files are opened in `fundamental` mode.

**Comment by gdkrmr** [comment]
I spent some trying to fix this but cannot figure out how. ESS went through major refactoring recently.

**Comment by gdkrmr** [comment]
this should work now, can you confirm @paupereira?

**Comment by paupereira** [comment]
It does :) 
Thanks, you guys are rockstars!

**Comment by gdkrmr** [comment]
this can be closes the I guess.

**Comment by MCMaurer** [comment]
I'm actually encountering this issue as well, on the latest update of spacemacs and ess.

I can open up a `.R` file and see that I'm in ESS[R] mode, but there are no keybindings to SPC m. Should I try to install the ESS layer from the develop branch, since it seems that's where it's been fixed? (I'm fairly new to spacemacs and I'm still trying to get the hang of things)

**Comment by gdkrmr** [comment]
I had a similar issue on one machine, pulling latest spacemacs develop and updating packages helped. The only config I have is

```elisp
     (ess :variables
          ess-use-flymake nil
          ess-assign-key "\M--")
```

**Comment by MCMaurer** [comment]
Good call, switching over to the develop branch worked like a charm, thank you!

**Comment by hasan356** [comment]
@paupereira  this issue can be closed now.
