### ISSUE TITLE
How to bump yasnippet to the latest version?

### ISSUE THREAD

**Issue by yssource** [syl20bnr/spacemacs#11847]
~/.emacs.d/elpa/develop/yasnippet-0.13.0
Current, the version of yasnippet is 0.13.0 tag, which is not the most latest one from the master branch.
Some latest functions are not available to me in 0.13.0 tag, for instance `yas--auto-next`.
I wander how to use the master branch of [joaotavora/yasnippet](https://github.com/joaotavora/yasnippet) in spacemacs in a proper way?
Thanks.

**Comment by antonalekseev** [comment]
You should overwrite package location set by `auto-completion` layer with:
```
dotspacemacs-additional-packages
     '((yasnippet :location (recipe :fetcher github :repo "joaotavora/yasnippet" :branch "master")))
```

**Comment by yssource** [comment]
I removed the old packages (~/.emacs.d/elpa/develop/yasnippet-0.13.0) manually, and restart emacs, and a new version ( ~/.emacs.d/elpa/develop/yasnippet-20181015.1212) is installed. It works well.
Thanks all the same.
