### ISSUE TITLE
Remove this display-graphic-p test in OSX layer?

### ISSUE THREAD

**Issue by an0** [syl20bnr/spacemacs#11852]
https://github.com/syl20bnr/spacemacs/blob/c7a103a772d808101d7635ec10f292ab9202d9ee/layers/%2Bos/osx/keybindings.el#L16

This `display-graphic-p` test in OSX layer prevents those keybindings from being applied if emacs is launched as daemon. I don't see any harm of removing this test so I suggest we remove this test.

**Comment by sdwolfz** [comment]
Hmm... if you provide a PR with the change and detailed steps to reproduce, someone with a mac could QA this and we will be able to merge.

**Comment by an0** [comment]
This is the PR: https://github.com/syl20bnr/spacemacs/pull/11883.

Someone using daemon on macOS should be able to reproduce it:
1. Launch Emacs in daemon mode: https://www.emacswiki.org/emacs/EmacsAsDaemon#toc6.
2. Connect an Emacs client to the daemon with `emacsclient -c`.
3. Try keybinding `command =` to see that it doesn't work.
