### ISSUE TITLE
Switch <tab> and C-z in helm?

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#1185]
I find it way more "natural" especially in `helm-find-files` 

As far as I know quite a lot of people switch it anyway because of @tuhdo's helm tutorial.

**Comment by josiah14** [comment]
+1.  Both Vim and Emacs use C-z to suspend Emacs temporarily and go to the Terminal.  Why would this common behavior change with Spacemacs, therefore, being one of the few points on which Emacs and Vim agree?

C-z is currently mapped to switch between Emacs and Vim modes, it appears - this can easily be defaulted to something more sensible, IMO.

**Comment by darkfeline** [comment]
I agree with this.  I made a PR https://github.com/syl20bnr/spacemacs/pull/1209

**Comment by darkfeline** [comment]
Pulled into `develop`
