### ISSUE TITLE
[feature request] Support company-tabnine

### ISSUE THREAD

**Issue by sei40kr** [syl20bnr/spacemacs#11867]
https://tabnine.com/
https://github.com/TommyX12/company-tabnine
I want to use company-tabnine instead of company-dabbrev-code.
Its most useful feature is completion for multiple words at once.

**Comment by sei40kr** [comment]
Adding it to `spacemacs-default-company-backends` worked.
But 
* company-lsp backend disables other backends
* Mode-specific backend group is used and company-tabnine is not used.

**Comment by sei40kr** [comment]
![2019-01-19 16 12 52](https://user-images.githubusercontent.com/11665236/51423537-2274b980-1c05-11e9-9320-46d37717bef5.png)

**Comment by sei40kr** [comment]
https://github.com/syl20bnr/spacemacs/issues/11950

**Comment by sei40kr** [comment]
https://github.com/syl20bnr/spacemacs/pull/11985

**Comment by tnfru** [comment]
Did you ever get this working? It's an either lsp or tabnine for me, nothing seems to work.
Adding it to spacemacs-default-company-backends in configuration layers does nothing for me, because LSP still takes control.

**Comment by sei40kr** [comment]
@tnfru 
> Did you ever get this working?

No. I have no motivation to implement this, because TabNine gave me terrible completions.

> Adding it to spacemacs-default-company-backends in configuration layers does nothing for me, because LSP still takes control.

`company-backends` documentation:
> The list of active backends (completion engines).
> 
> Only one backend is used at a time.  The choice depends on the order of
> the items in this list, and on the values they return in response to the
> ‘prefix’ command (see below).  But a backend can also be a "grouped"
> one (see below).

You need to put `company-lsp` and `company-tabnine` in same group.
Or you can configure `TabNine.toml` and enable semantic completion, and use only `company-tabnine` for the backends. (please see for TabNine documentation for details)

**Comment by Ghasak** [comment]
@sei40kr  and @tnfru 
I wrote an extensive solution for how to achieve all company completions in `spacemacs`. If you are interested 
[read here](https://emacs.stackexchange.com/a/77349/40519)
