### ISSUE TITLE
how to change max recentf number size in HELM?

### ISSUE THREAD

**Issue by collector1871** [syl20bnr/spacemacs#11873]
branch: develop
os: linux

hello,
I would like to change max recentf size number to 1000 in HELM. Currently it's max 100 only (**SPC f r**).
I tried this in `dotspacemacs/user-config` ;

```
(setq recentf-max-saved-items 1000) 
(setq recentf-max-menu-items 1000)
```
but it's not working for HELM.
And it seems that pure command **recentf-open-files** works correctly (corrently it shows 173 entries), so probably it could be something with HELM. 
Probably it's not really a bug, but question - how can i change it in HELM?

thanks

**Comment by dangom** [comment]
Just add the following inside your `dotspacemacs/user-config`:

```elisp
;; Increase the number of helm candidates to see, e.g., more files from recentf.
(with-eval-after-load 'helm
    (setq helm-candidate-number-limit 1000)) 
```

But why would you want to see more results? The idea of helming is that you continue typing and narrowing down results. You don't really want to read 1000 candidates, or do you?

**Comment by collector1871** [comment]
ok, thank you - we can close this topic

i would like to change... why not? maybe you are right, but i prefer big list :)

**Comment by bingguo1** [comment]
I actually tried the above settings, but doesn't work. It seems recentf is not a helm inner function, even though helm can take advantage of it. the default of max recentf number size is 20 which is too small for me. To change it:

'''lisp
 (recentf-mode 1)
  (setq recentf-max-saved-items 100)
'''
