### ISSUE TITLE
No such action ... for this source

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#11878]
#### Description :octocat:

Trying to open a helm search buffer for the selected project from the HELM Projectile buffer shows the error message:
>No such action ‘spacemacs/helm-project-smart-do-search-in-dir’ for this source

#### Reproduction guide :beetle:

- Open the HELM Projectile buffer `SPC p p` 
- Press `C-s`

*Observed behaviour:* :eyes: :broken_heart:

>No such action ‘spacemacs/helm-project-smart-do-search-in-dir’ for this source

*Expected behaviour:* :heart: :smile:

A Helm search buffer should open.

#### Notes 📓

The issue doesn't seem to be limited to a key binding in the HELM Projectile buffer.

Similar error messages appear if one tries to call [e] edit occurrences from the Helm Transient State (`M-SPC`) in these buffers:
- HELM Find Files (`SPC f f`), `M-SPC` `e`
> No such action ‘spacemacs//helm-find-files-edit’ for this source
- HELM Swoop (`SPC s s`), `M-SPC` `e`
> No such action ‘helm-swoop--edit’ for this source

#### What works

A helm search buffer for a project can be opened from the HELM Projectile buffer by opening the Helm Actions (`C-z`) list and choosing:
> Grep in projects `C-s'

Pressing `e` from the Helm Transient State in a `*helm-ag*` (`SPC /`) buffer works.

There's no error message and a `*helm-ag-edit*` buffer opens as expected.

#### System Info :computer: ℹ️ 
- OS: windows-nt **(the same thing occurs in Ubuntu 18.04, running in virtual box with Win 10 as host)**
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1a87b0c64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp git helm html ibuffer markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by dsnipe** [comment]
As for `HELM Swoop (SPC s s), M-SPC e`
There is an issue with helm-swoop itself: https://github.com/ShingoFukuyama/helm-swoop/issues/133
And looks like the library is abandon.  But it's possible to fix it, using a patched version (instruction is in the issue).

**Comment by duianto** [comment]
Thanks for the link. It might also be helpful for finding a solution to the other issues.

**Comment by duianto** [comment]
This might be the source of the project search issue.

`helm-projectile` defines these actions:
```
(defcustom helm-source-projectile-projects-actions
  (helm-make-actions
   "Switch to project" (lambda (project)
                         (let ((projectile-completion-system 'helm))
                           (projectile-switch-project-by-name project)))
   "Open Dired in project's directory `C-d'" #'dired
   "Open project root in vc-dir or magit `M-g'" #'helm-projectile-vc
   "Switch to Eshell `M-e'" #'helm-projectile-switch-to-eshell
   "Grep in projects `C-s'" #'helm-projectile-grep
   "Compile project `M-c'. With C-u, new compile command" #'helm-projectile-compile-project
   "Remove project(s) from project list `M-D'" #'helm-projectile-remove-known-project)
  "Actions for `helm-source-projectile-projects'."
  :group 'helm-projectile
  :type '(alist :key-type string :value-type function))
```
source:
https://github.com/bbatsov/helm-projectile/blob/38d72b6b661234088bae9f3c2b3c18228a3c0564/helm-projectile.el#L209

All but the `C-s` binding work from the `HELM projectile: .Emacs.D` (`SPC p p`) buffer

The help information for the key bindings in `Helm projectile` can be viewed in Spacemacs by pressing 
`C-S-h` followed by for example `C-d` which shows:
```
C-d runs the command #[0 "\300\301!\207" [helm-exit-and-execute-action dired] 2
nil nil] (found in helm-projectile-projects-map), which is an interactive
compiled Lisp function.

It is bound to C-d.

(anonymous)

Not documented.
```

And `M-g` shows:
```
M-g runs the command #[0 "\300\301!\207" [helm-exit-and-execute-action
helm-projectile-vc] 2 nil nil] (found in helm-projectile-projects-map), which is
an interactive compiled Lisp function.

It is bound to M-g.

(anonymous)

Not documented.
```

But `C-s` shows:
```
C-s runs the command spacemacs/helm-projectile-grep (found in
helm-projectile-projects-map), which is an interactive Lisp function in
‘../../funcs.el’.

It is bound to C-s.

(spacemacs/helm-projectile-grep)

Replace ‘helm-projectile-grep’ to actually use ‘ag’, ‘pt’ etc..
```

When `C-s` is pressed (without the `C-S-h` prefix) the error message is shown:
>No such action ‘spacemacs/helm-project-smart-do-search-in-dir’ for this source

That error message is defined in:
`helm-exit-and-execute-action` https://github.com/emacs-helm/helm/blob/fa5a56f9d52dc5346ffc42bb68ee97ad4fe888b2/helm.el#L1974

And `helm-exit-and-execute-action` seems to expect the function name to be listed as an action.

In this case `helm-projectile` lists the action as:
```
   "Grep in projects `C-s'" #'helm-projectile-grep
```
But Spacemacs binds `C-s` to `spacemacs/helm-projectile-grep` here: https://github.com/syl20bnr/spacemacs/blob/322528ca8d6330c9f3492c1e86216ce0d1edaf0c/layers/%2Bcompletion/helm/packages.el#L181

And the function is bound here:
https://github.com/syl20bnr/spacemacs/blob/322528ca8d6330c9f3492c1e86216ce0d1edaf0c/layers/%2Bcompletion/helm/funcs.el#L328

I don't know how to get `helm-exit-and-execute-action` to detect:
`spacemacs/helm-project-smart-do-search-in-dir` as an action.

**Comment by duianto** [comment]
The HELM Swoop (`SPC s s`), `M-SPC e` issue seems to have been fixed upstream.

But the HELM Find Files (`SPC f f`), `M-SPC e` (or `C-c C-e`) issue remains.

I opened a separate issue to track it:
No such action ‘spacemacs//helm-find-files-edit’ for this source #13038
