### ISSUE TITLE
Are there other keys like 'fd' that could be interfering with my regular typing in insert-mode?

### ISSUE THREAD

**Issue by LaloHao** [syl20bnr/spacemacs#11889]
I have an issue that happens randomly (i think) when i'm typing in `insert-mode`, a message shows `quit` in the echo buffer and the key that was pressed doesn't get typed.

This doesn't happen with my personal `emacs` configuration, but since i started using spacemacs i can't type fluidly, i thought it was `keychord mode` but it's not even installed.

Posted on stackoverflow with no answer:
https://stackoverflow.com/questions/54119672

**Comment by hugotkk** [comment]
https://github.com/syl20bnr/spacemacs/issues/11736
check this out

**Comment by FrancescElies** [comment]
I get this `Quit` message only in `typescript-mode`, not sure why...

**Comment by FrancescElies** [comment]
@LaloHao upgrading packages worked for me, disabling smartparens as described in https://github.com/syl20bnr/spacemacs/issues/11736 didn't have any effect.
