### ISSUE TITLE
evil-cleverparens layer is absent in develop branch

### ISSUE THREAD

**Issue by achikin** [syl20bnr/spacemacs#11881]
#### Description :octocat:
evil-cleverparens layer is absent in develop branch

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
This is found in messages after startup is complete
```
Loading /Users/achikin/.spacemacs...done
(Spacemacs) Warning: Unknown layer evil-cleverparens declared in dotfile.
Spacemacs is ready.
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: spacemacs/toggle-evil-cleverparens-on
```
*Expected behaviour:* :heart: :smile:
evil-cleverparens works as expected

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fb4e58111)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript html helm org auto-completion better-defaults emacs-lisp git markdown sql gtags themes-megapack
            (clojure :variables cider-dynamic-indentation nil)
            evil-cleverparens)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
Loading /Users/achikin/.spacemacs...done
(Spacemacs) Warning: Unknown layer evil-cleverparens declared in dotfile.
Spacemacs is ready.
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: spacemacs/toggle-evil-cleverparens-on
```

**Comment by sdwolfz** [comment]
The `evil-cleverparens` layer was removed and cleverparens is now part of the `spacemacs-evil` distribution layer, as noted in the `CHANGELOG.develop` file.

**Comment by Kasuko** [comment]
For those who ended up here via Google:

evil-cleverparens was added to the spacemacs-evil layer and creates a toggle in major mode of modes that support it. Thus you can use `,Ts` to toggle evil-cleverparens on.

The best way I could find to put evil-cleverparens on by default was to add the following to my `dotspacemacs/user-config`:
```elisp
  ;; Cleverparens ON by default
  (use-package evil-cleverparens
    :defer t
    :init (spacemacs/toggle-evil-safe-lisp-structural-editing-on-register-hooks))
```

However, I am no expert so this could be very wrong.

**Comment by duianto** [comment]
Thanks for posting a solution to enable it on startup.
I'm sure it's fine. If something works, keep using it until a better solution is discovered/suggested.
