### ISSUE TITLE
Using S for evil-surround instead of s

### ISSUE THREAD

**Issue by hoyon** [syl20bnr/spacemacs#11896]
#### Description :octocat:
I want to use capital S instead of lowercase s to activate evil-surround. I've read the documentation regarding this and have added the snippet
```
(evil-define-key 'visual evil-surround-mode-map "s" 'evil-substitute)
(evil-define-key 'visual evil-surround-mode-map "S" 'evil-surround-region)
```
to the end of my `dotspacemacs/user-config` function, but it has no effect. However if I then source the two lines after emacs has loaded, it then has the desired effect.

I understand the rationale behind the switch, however I also regularly use vim and the difference in keybinding is very annoying.

#### Reproduction guide :beetle:
- Start Emacs
- Add above snippet to `dotspacemacs/user-config`
- Press capital S in visual mode

*Observed behaviour:* :eyes: :broken_heart:
Substitutes characters

*Expected behaviour:* :heart: :smile:
Starts evil-surround

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 990290e24)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql lua erlang csv python themes-megapack helm
     (auto-completion :variables auto-completion-tab-key-behavior 'complete auto-completion-return-key-behavior nil)
     neotree emacs-lisp git github markdown org yaml html javascript typescript
     (haskell :variables haskell-completion-backend 'intero)
     (elm :variables elm-format-on-save t elm-sort-imports-on-save t)
     vimscript latex sml
     (c-c++ :variables c-c++-enable-clang-support t c-c++-enable-c++11 t)
     ycmd docker version-control syntax-checking
     (spell-checking :variables spell-checking-enable-by-default nil)
     deft epub
     react rust elixir phoenix ruby ruby-on-rails
     (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 30 shell-default-position 'bottom)
     (ranger :variables ranger-show-preview t)
     restclient
     (sql :variables sql-capitalize-keywords t sql-capitalize-keywords-blacklist
          '("name")))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LCMS2

#### Backtrace :paw_prints:
```
No backtrace
```

**Comment by Miciah** [comment]
Since that documentation was written, Spacemacs has been changed to load evil-surround lazily, which causes it to configure evil-surround after `dotspacemacs/user-config` runs, overriding the key bindings that you made. Try the following in `dotspacemacs/user-config`:
```emacs-lisp
 (spacemacs|use-package-add-hook evil-surround
   :post-config
   (evil-define-key 'visual evil-surround-mode-map "s" 'evil-substitute)
   (evil-define-key 'visual evil-surround-mode-map "S" 'evil-surround-region))
```

**Comment by hoyon** [comment]
Thanks! That seems to have worked. I've create a PR to update the docs.
