### ISSUE TITLE
Slow to the point of being unusable

### ISSUE THREAD

**Issue by gcross** [syl20bnr/spacemacs#11909]
#### Description :octocat:
It slows to the point of being literally unusable, often hanging and requiring it to be killed and restarted.

#### Reproduction guide :beetle:
- Start Emacs
- Use it as normal to edit text files.

*Observed behaviour:* :eyes: :broken_heart:
Over time, typing gets slower and slower to the point where I have been (not kidding) spending a lot of time browsing Reddit waiting for it to catch up to me;  I am probably going to switch to another editor soon, unfortunately, so that I can start making good progress again, unfortunately.

Sometimes killing and restarting Emacs helps (which I have to do from time to time anyway as it completely hangs), but lately even that hasn't always caused it to become usable on boot.

*Expected behaviour:* :heart: :smile:
I would expect that I could use it as a normal text editor and not feel frustrated at always having to stop what I am doing so that it can catch up to me.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(bibtex haskell html javascript latex python yaml helm auto-completion better-defaults emacs-lisp git markdown spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by LucaMarconato** [comment]
When Emacs starts being slow, use `M-x profiler-start`, do some stuff and then use `M-x profiler-report`.
You will hopefully find what is making Emacs slow.

**Comment by gcross** [comment]
Is this telling me anything useful?

    + command-execute                                               21832  54%
    + flyspell-post-command-hook                                     8604  21%
    + timer-event-handler                                            3826   9%
    + flycheck-handle-signal                                         3599   8%
    + redisplay_internal (C function)                                1589   3%
    + global-hl-line-highlight                                        449   1%
    + ...                                                              80   0%
    + evil-repeat-post-hook                                            12   0%
    + winner-save-old-configurations                                   12   0%
      global-hl-line-unhighlight                                        9   0%
    + evil--jump-hook                                                   8   0%
      tooltip-show-help-non-mode                                        6   0%
      flycheck-help-echo                                                6   0%
      company-post-command                                              4   0%
    + hl-paren-initiate-highlight                                       4   0%
      company-pre-command                                               4   0%
      flycheck-perform-deferred-syntax-check                            4   0%
    + flycheck-hide-error-buffer                                        4   0%
      global-page-break-lines-mode-check-buffers                        4   0%
    + evil-activate-visual-state                                        4   0%
    + evil-visual-pre-command                                           4   0%
      sp--save-pre-command-state                                        3   0%
      which-key--hide-popup                                             2   0%
      undefined                                                         2   0%

**Comment by gcross** [comment]
Also, thanks a lot for your help!

**Comment by gcross** [comment]
I tried doing more typing this time and got a slightly different report:

      timer-event-handler                                      43,880,731  43%
    + flyspell-post-command-hook                               30,405,200  30%
    + redisplay_internal (C function)                          12,516,612  12%
    + command-execute                                          10,988,587  10%
    + company-post-command                                      1,596,440   1%
    + flycheck-handle-signal                                      285,838   0%
    + winner-save-old-configurations                              169,632   0%
    + evil-escape-pre-command-hook                                 84,132   0%
    + hl-paren-initiate-highlight                                  45,088   0%
    + flycheck-display-error-at-point-soon                         31,072   0%
    + ...                                                          16,376   0%
    + sp--save-pre-command-state                                   15,840   0%
    + evil-repeat-pre-hook                                         13,480   0%
    + evil-repeat-post-hook                                         2,112   0%
    + eldoc-schedule-timer                                          1,056   0%
    + which-key--hide-popup                                         1,056   0%
    + tramp-set-auto-save-file-modes                                1,024   0%
    + eldoc-pre-command-refresh-echo-area                           1,016   0%

**Comment by LucaMarconato** [comment]
Try disabling `flyspell` and check if the performance improved. If not, try profiling also the memory (I assume you profiled the CPU). Also, `command-execute` could be worth further analysis, try expanding it pressing the return key when your point is over it.

**Comment by gcross** [comment]
Hmm, the delay seems to pop up sometimes but not others.  Also, is pressing return on an item (with a + or not) supposed to do something?  It doesn't for me.

**Comment by LucaMarconato** [comment]
Pressing the return key on the items should expand the tree of the profiler. It always worked for me, both for stock Emacs and stock Spacemacs. Try running `emacs -Q` from your terminal (which open a vanilla emacs) and check if the profiler lets you expand the items. If not, upgrade emacs to the latest version.

**Comment by octplane** [comment]
> Hmm, the delay seems to pop up sometimes but not others. Also, is pressing return on an item (with a + or not) supposed to do something? It doesn't for me.

TAB works for me for that.
