### ISSUE TITLE
`treemacs` icons are not shown

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#11915]
#### Description :octocat:
`treemacs` icons are not shown

I guess that the general path for the icons is not set to the right directory, here is the help string to `treemacs-icon-c` which points to "~/.emacs.d/icons/c.png" instead of the directory where `treemacs` is actually installed in:
```elisp
treemacs-icon-c is a variable defined in ‘treemacs-icons.el’.
Its value is
#("  " 0 1
  (img-unselected #1=(image :type imagemagick :file "/home/gkraemer/.emacs.d/icons/c.png" :scale 1 :ascent center :width 22 :height 22 :background "#002b36")
                   img-selected
                   (image :type imagemagick :file "/home/gkraemer/.emacs.d/icons/c.png" :scale 1 :ascent center :width 22 :height 22 :background "#073642")
                   display #1#))

Documentation:
Not documented as a variable.
```
#### Reproduction guide :beetle:
- Start Emacs
- `SPC 0`

*Observed behaviour:* :eyes: :broken_heart:
File-type icons in spacemacs are shown as black squares

*Expected behaviour:* :heart: :smile:
Icons for file-types

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a46b784)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-rtags-support t c-c++-enable-clang-support t)
      cscope chrome csv javascript ranger emacs-lisp
      (ess :variables ess-use-flymake nil ess-assign-key "\255")
      (julia :variables lsp-julia-command "julia-1.0" julia-mode-enable-lsp t julia-mode-enable-ess nil)
      git github html
      (latex :variables TeX-view-program-selection
             '((output-pdf "PDF Tools"))
             TeX-view-program-list
             '(("PDF Tools" TeX-pdf-tools-sync-view))
             TeX-source-correlate-start-server t preview-scale-function 1.5)
      bibtex
      (lsp :variables lsp-prefer-flymake nil)
      markdown multiple-cursors
      (mu4e :variables mu4e-installation-path "~/progs/misc/mu/mu4e/" mu4e-get-mail-command "offlineimap" mu4e-enable-mode-line t mu4e-use-maildirs-extension t mu4e-spacemacs-layout-name "@Mu4e" mu4e-spacemacs-layout-binding "m")
      octave
      (org :variables org-latex-pdf-process
           (list "latexmk -shell-escape -bibtex -f -pdf %f")
           org-format-latex-options
           '(:foreground default :background default :scale 1.5 :html-foreground "Black" :html-background "Transparent" :html-scale 1.0 :matchers
                         ("begin" "$1" "$" "$$" "\\(" "\\[")))
      pdf python rust
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      shell-scripts spell-checking syntax-checking treemacs themes-megapack version-control vimscript yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Alexander-Miller** [comment]
Those icon paths are set when treemacs is compiled. So maybe you compiled in some strange way, maybe the compiler itself was weird (I don't think it'd be the first time). Either way reinstalling treemacs should fix it.

**Comment by gdkrmr** [comment]
It resolved itself, I guess it only needed a reinstall.
