### ISSUE TITLE
pdumper crash on setting dotspacemacs-editing-style to 'hybrid in dotfile

### ISSUE THREAD

**Issue by Compro-Prasad** [syl20bnr/spacemacs#11923]
- Just follow the normal steps as given in the https://github.com/syl20bnr/spacemacs/blob/develop/EXPERIMENTAL.org file. [You don't need to `git checkout pdumper`]
- Then set `dotspacemacs-editing-style` to `'hybrid` in your dotfile accessible using `SPC f e d`
- Modify layer list as you like so that Spacemacs starts dumping after a restart.
- Restart Spacemacs.
- Let the process in `*spacemacs-dumper*` complete.
- Close spacemacs
- Open again using `emacs-27.0.50 --dump-file ~/.emacs.d/.cache/dumps/spacemacs.pdmp`

This will crash Emacs without even launching.

OS: Antergos (Arch Linux)

**Comment by syl20bnr** [comment]
Should be fixed now.

**Comment by Compro-Prasad** [comment]
```
Loading /home/compro/.emacs.d/init.el (source)...
Loading /home/compro/.spacemacs.d/init.el (source)...
c-c++: No c-c++-lsp-cache-dir specified: defaulting to /home/compro/.ihsec/spacemacs/.cache/lsp-ccls
Error (use-package): magit/:config: Symbol’s value as variable is void: hybrid-style-enable-evilified-state
Error (use-package): markdown-mode/:config: Symbol’s value as variable is void: hybrid-style-enable-hjkl-bindings
[yas] Prepared just-in-time loading of snippets successfully.
(Spacemacs) Pre-dumping layer helm...
Loading mode helm-mode...
Symbol’s value as variable is void: hybrid-style-enable-hjkl-bindings

Process spacemacs-dumper exited abnormally with code 255
```

**Comment by smile13241324** [comment]
@Compro-Prasad just merged a related PR would you mind testing this again?

**Comment by Compro-Prasad** [comment]
This is fixed on my side. Thanks @smile13241324 and @madand .
