### ISSUE TITLE
Jump to definitions is unusable in javascript file

### ISSUE THREAD

**Issue by kunish** [syl20bnr/spacemacs#11920]
#### Description :octocat:
Jump to definitions is unusable in javascript file.

#### Reproduction guide :beetle:
- Start Emacs
- Open a javascript file
- Press `gd` on a variable
- A minibuffer prompt shows up in the bottom saying visit tags table
- Press `return`, No jump handler was able to find this symbol

*Observed behaviour:* :eyes: :broken_heart:
Can't jump to definition

*Expected behaviour:* :heart: :smile:
Jump to definition

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ab2fc3fb0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp
      (colors :variables colors-enable-nyan-cat-progress-bar t)
      git markdown org syntax-checking version-control themes-megapack multiple-cursors tern prettier
      (javascript :variables javascript-fmt-tool 'prettier)
      html go typescript react shell-scripts python)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by galaxycubic** [comment]
![image](https://user-images.githubusercontent.com/17328586/51892518-1d6df200-23dd-11e9-8ab2-a9cfa293d797.png)

But after `SPC h d v spacemacs-jump-handlers <RET>`

![image](https://user-images.githubusercontent.com/17328586/51892668-9bca9400-23dd-11e9-88e5-61cc97c30a9c.png)

Now, I can jump to definitions by using dumb jumps.

![image](https://user-images.githubusercontent.com/17328586/51892807-f9f77700-23dd-11e9-9508-88bc707ba390.png)

**Comment by galaxycubic** [comment]
And also, I have tern layer installed. When I press `SPC m g g` on a variable, it behaves exactly the same as before.

**Comment by Compro-Prasad** [comment]
Correct me if I am wrong.

You open Spacemacs, then open a JavaScript file in which jump to definition doesn't work. It works only after you open a second JavaScript file or turn on js2-mode.

**Comment by galaxycubic** [comment]
@Compro-Prasad
Yes, that's right.
Any help?

**Comment by Compro-Prasad** [comment]
This might be an issue with lazy loading some part of configuration.

**Comment by galaxycubic** [comment]
@Compro-Prasad
Oh, that makes sense. But how can we fix that? It's getting kind of annoying sometime.
