### ISSUE TITLE
Spacemacs doesn't dump proper values of variables from the config using the pdumper

### ISSUE THREAD

**Issue by Compro-Prasad** [syl20bnr/spacemacs#11924]
I have the following in my dotfile:

```
dotspacemacs-mode-line-theme '(spacemacs :separator slant :separator-scale 1.4)
```

My dumped Spacemacs has the following modeline:
![screenshot from 2019-01-30 03-01-18](https://user-images.githubusercontent.com/11143962/51941816-84ba8f00-243b-11e9-9388-fa820cd92326.png)

Loading from actual config looks like the following(which is correct):
![screenshot from 2019-01-30 03-02-25](https://user-images.githubusercontent.com/11143962/51941844-93a14180-243b-11e9-99fc-3ff448b0d110.png)

**Comment by Kethku** [comment]
This is a repeat of https://github.com/syl20bnr/spacemacs/issues/10917
