### ISSUE TITLE
space-doc-mode appears to render _some_ TITLE blocks of the README docs with strangely elided characters 

### ISSUE THREAD

**Issue by qizwiz** [syl20bnr/spacemacs#11930]
#### Description
The correct version below I got by toggling ```space-doc-mode``` with ```, T V```. I tried to troubleshoot this myself to no avail. I _believe_ the problem lies somewhere in the ```spacemacs-space-doc-modificators-functions``` but so far I haven't been able to manually reproduce this by running those decorators separately. Intuition suggests that it's in ```spacemacs//space-doc-alternative-tags-look``` because of it's call to ```spacemacs//space-doc-font-lock-fontify-region-function```. But again, I haven't been able to prove that.

#### Reproduction guide
- Start Emacs from the develop branch
- Set ```dotspacemacs-pretty-docs``` to ```t```
- Open ~/.emacs.d/layers/+lang/erlang/README.org OR ~/.emacs.d/layers/+lang/emacs-lisp/README.org (there may be others, but these are the only ones I've found so far that display this behavior)

*Observed behaviour:*
The TITLE block looks like this:
![screenshot from 2019-01-31 10-19-02](https://user-images.githubusercontent.com/211900/52134461-38bd4500-2609-11e9-81ae-5fcda6e80ba6.png)

or this:
![screenshot from 2019-01-31 14-39-08](https://user-images.githubusercontent.com/211900/52134564-70c48800-2609-11e9-9b6b-ca8e52d61452.png)

*Expected behaviour:*
It should look like this:

![screenshot from 2019-02-01 10-11-28](https://user-images.githubusercontent.com/211900/52134733-e29cd180-2609-11e9-92f9-352426e8d181.png)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a2bda1682)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql
 (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t treemacs-use-collapsed-directories 3)
 (spacemacs-layouts :variables spacemacs-layouts-directory "~/.dotfiles/spacemacs-layouts/" layouts-enable-autosave t layouts-autosave-delay 1800)
 geolocation erlang erc themes-megapack syntax-checking templates parinfer yaml html dap ruby
 (ruby :variables ruby-enable-enh-ruby-mode nil ruby-version-manager 'rvm ruby-test-runner 'rspec)
 ruby-on-rails docker command-log gtags helm spacemacs-visual spacemacs-editing-visual auto-completion org emacs-lisp git github ibuffer markdown multiple-cursors
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD CANNOT_DUMP LCMS2 GMP

**Comment by duianto** [comment]
I'm unable to reproduce the issue. The expected result is shown in:
- Windows 10 1803
- Ubuntu 18.04.1

With both:
- Emacs 26.1 
- Emacs 27.0.50

>dotspacemacs-pretty-docs is a variable defined in ‘core-dotspacemacs.el’.
Its value is t

`SPC h l` `erlang` `RET`

![virtualboxvm_2019-02-03_12-35-51](https://user-images.githubusercontent.com/13420573/52176285-0e0df080-27b1-11e9-842c-41d16908ed0d.png)

`SPC h l` `emacs-lisp` `RET`

![virtualboxvm_2019-02-03_12-39-25](https://user-images.githubusercontent.com/13420573/52176286-0e0df080-27b1-11e9-9930-e5b15f5254d7.png)



#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1 (**And 27.0.50**)
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a2bda1682)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp erlang git helm html ibuffer markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2 GMP


#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1 (**And 27.0.50**)
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a2bda1682)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm erlang emacs-lisp git multiple-cursors treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

**Comment by qizwiz** [comment]
I've noticed a couple of more things.

1) If the file is opened from a dired buffer or find-file (with and without helm), you have to open it _twice_ to see the eliding effect demonstrated above. Thereafter it always does it.
2) If the file is opened from ```SPC h l``` (```helm-spacemacs-help-layers```), then you never get the eliding effect

I know it hasn't been reproduced by anyone else here yet, but maybe those observations will help in troubleshooting. I can reliably reproduce this on my work linux box AND my personal macbook pro. 

My theory is that somewhere in the ```find-file``` chain of events, ```space-doc-mode``` is getting called twice with all the ```spacemacs-space-doc-modificators-functions```. I think this would explain why I can't reproduce it with edebug. ```helm-spacemacs-help-layers``` seems to follow a different path, but I haven't had the time to fully document the differences yet.

**Comment by duianto** [comment]
Confirmed in Ubuntu 18.04.1 (as a virtualbox client), when opening:
`~/.emacs.d/layers/+lang/erlang/README.org` from either a Dired (`SPC a d`) buffer or `SPC f f` (it happens the first and subsequent times, it didn't require opening it twice).

![virtualboxvm_2019-02-14_19-46-36](https://user-images.githubusercontent.com/13420573/52810389-bdd93d00-3092-11e9-958d-e83cba862be0.png)

When readme.org is opened then it first shows it correctly for a split second before the letters disappear.

The mode line shows Org major mode in both Windows and Ubuntu, 

But in Ubuntu it shows three extra minor modes `ViewIndSD`.This is the description when the mouse pointer is moved over the minor mode indicators:
- View `view-mode`
- Ind `org-indent-mode`
- SD `space-doc-mode`

Pressing `SPC m` shows:
>SPC m is undefined

Calling `M-x space-doc-mode RET` shows all the letters in the title, until the buffer is closed and reopened.

The issue still doesn't occur in Windows 10 1803, when opening with Dired or find files.
`SPC m` works, it opens the which-key popup `Major mode commands`.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 95422ae5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm erlang emacs-lisp git multiple-cursors treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP
