### ISSUE TITLE
What happened with BEGINNERS_TUTORIAL.org ?

### ISSUE THREAD

**Issue by abitrolly** [syl20bnr/spacemacs#11934]
There is `BEGINNERS_TUTORIAL.org` in https://github.com/syl20bnr/spacemacs/tree/master/doc but no references to it. Is it actual?

**Comment by bradyt** [comment]
There's a [helm](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bcompletion/helm/local/helm-spacemacs-help/helm-spacemacs-help.el#L131) reference, as well as a reference at http://develop.spacemacs.org/.

I only searched here to find these, https://github.com/syl20bnr/spacemacs/search?q=BEGINNERS_TUTORIAL.org.

**Comment by abitrolly** [comment]
I expected to find http://spacemacs.org/doc/BEGINNERS_TUTORIAL with a link
to it somewhere. At least in README. I knew only this https://helm.sh/ )

**Comment by smile13241324** [comment]
Well emacs is a self documenting system, this means you should use emacs itself when you are looking for documentations. Basically the way to go is `spc h spc`, when you search there for `begin` you should get the reference to the beginners tutorial. When you enter nothing the first block lists all `spacemacs documentation files` which can be read directly in spacemacs.

More detailed documentation about individual packages, of which the layers consists, can be obtained with `spc h d m`. Also detailed instructions about individual layers can be obtained with `spc h spc` e.g. about the `helm` system which is `http://tuhdo.github.io/helm-intro.html` and not `https://helm.sh` which is a `kubernetes package manager`.

New users should read the users manual and then use emacs build in documentation tools to read the remaining files if required.

**Comment by abitrolly** [comment]
New users don't know what they should do. I expect users like me expect to read all documentation online, and at GitHub at particular. Expected behavior for desktop application is to respond with firsthand useful info by pressing F1 key.

**Comment by abitrolly** [comment]
https://develop.spacemacs.org/doc/BEGINNERS_TUTORIAL.html
