### ISSUE TITLE
Cannot load moe-theme (part of themes-megapack layer)

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#1193]
When I type `SPC T h`, I cannot see `moe-dark` or `moe-light` themes.

When I open `ielm` and type `(require 'moe-theme)`, then `SPC T h` shows `moe-dark` and `moe-light`.

If somebody is willing to guide how to fix this, I can work on a patch.

**Comment by syl20bnr** [comment]
I guess this theme requires a function `themes-megapack/init-moe-theme` in order to correctly declare the themes.

Note that while it does not work with `SPC T h`, it does work when added to the `dotspacemacs-themes`, try `moe-dark` and `moe-light`.

**Comment by swaroopch** [comment]
Yep, `moe-dark` works when added to `dotspacemacs-themes`.

(I'm still sticking with `solarized-dark` though since the spacemacs mode line has dark text on dark background in `moe-dark`)

**Comment by syl20bnr** [comment]
Themes declared in `dotspacemacs-themes` are now correctly installed.
Should be fixed in develop.
