### ISSUE TITLE
`Error callling diff` message when syncing configuration layers: SPC f e R

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#11938]
#### Description :octocat:

A `Error callling diff` error message is shown when the configuration layers are synced `SPC f e R`.
(Yes with 3 l's)

#### Reproduction guide :beetle:

- Start Spacemacs
-  Press: `SPC f e R` (which calls: `dotspacemacs/sync-configuration-layers`)

*Observed behaviour:* :eyes: :broken_heart:

Everything seems to be reloaded as expected. But the messages buffer shows:
```
Error callling git diff:

```
The minibuffer has the height of two lines (the second line is empty), so it seems like a newline is added after the error message.

The messages buffer shows:
```
Loading c:/Users/username/.spacemacs...done
Loading c:/Users/username/.spacemacs...done
Loading c:/Users/username/.spacemacs...done
Done.
Error callling git diff:

```

*Expected behaviour:* :heart: :smile:

The error message should probably not be there.

#### Notes :notebook:

The error message is defined in the `git-gutter-plus` package.
In the function:
```elisp
(defun git-gutter+-diff (curfile)
  (let ((args (git-gutter+-diff-args curfile))
        (file (buffer-file-name))) ;; for tramp
    (with-temp-buffer
      (if (git-gutter+-insert-git-output args file)
          (progn (goto-char (point-min))
                 (let ((diff-header (git-gutter+-get-diff-header))
                       (diffinfos   (git-gutter+-get-diffinfos)))
                   (list diff-header diffinfos)))
        (message "Error callling git diff:\n%s" (buffer-string))
        nil))))
```
source: https://github.com/nonsequitur/git-gutter-plus/blob/b7726997806d9a2da9fe84ff00ecf21d62b6f975/git-gutter%2B.el#L199

There's an open issue from the git gutter plus repository that mentions that error message:
Getting 'Error callling diff" errors with latest magit #41
https://github.com/nonsequitur/git-gutter-plus/issues/41

It just states that:
>Apart from the spelling error in "callling", this seems to break everything.
package version:
magit-20180409.1612

#### Possible source ℹ️ 

Spacemacs uses `git-gutter+` in the `version-control` layer:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+source-control/version-control/packages.el#L202

This might be the command with the issue:
`        (add-hook 'magit-pre-refresh-hook 'git-gutter+-refresh)`

because the function: `git-gutter+-refresh`
calls: `git-gutter+-process-diff`
which calls: `git-gutter+-diff` (where the error message is defined)

#### System Info :computer:

- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a2bda1682)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp erlang git helm html ibuffer markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by johanhugg** [comment]
I've had this for the longest time, so annoying. Happens on Mac and Linux

**Comment by brandelune** [comment]
This happens on (close to) vanilla emacs too. But not with all repositories.

**Comment by duianto** [comment]
I wasn't able to reproduce it in Emacs 26.3 or 27.1.

Until I remembered that I had set the `default-directory` in a previous config (when this issue was first reported):
```elisp
(setq default-directory "~/.emacs.d/")
```
in the `dotspacemacs/user-init` section in `.spacemacs`.

Now: `SPC f e R` in the Spacemacs home buffer, shows the error message:
>Error callling git diff:

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0125af2be)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git go haskell helm
            (javascript :variables javascript-backend 'lsp)
            (languagetool :variables langtool-language-tool-jar "C:\\Users\\username\\Applications\\LanguageTool-5.0\\languagetool-commandline.jar")
            lsp markdown multiple-cursors org
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            shell version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>
