### ISSUE TITLE
Spacemacs auto escapes character in C files.

### ISSUE THREAD

**Issue by simplect** [syl20bnr/spacemacs#11946]
#### Description :octocat:
Spacemacs auto escapes character definition in C files.

#### Reproduction guide :beetle:
- Start Emacs
- Open .c File
- Try to write char my_char = '';

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs autocompletes '' to \\'\\'

*Expected behaviour:* :heart: :smile:
Just '' when I want to type ''

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. edf3b9d28)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql html python ipython-notebook octave javascript clojure yaml haskell c-c++ docker nginx helm auto-completion emacs-lisp git markdown themes-megapack org shell latex ess spotify deft)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by vishvanath45** [comment]
Do `M-x smartparens-mode` which will disable it. I would normally suggest using `electric-pair-mode` which is less intrusive as compared to `smartparens-mode`. If this fixes your issue then you can close it. I would also suggest asking these questions on Gitter first.

**Comment by simplect** [comment]
That solves it. Thank you! 

Will post it to Gitter next time.
