### ISSUE TITLE
parinfer-mode doesn't start when opening a clojure buffer

### ISSUE THREAD

**Issue by Akeboshiwind** [syl20bnr/spacemacs#11940]
#### Description :octocat:
`parinfer-mode` doesn't start when opening a clojure buffer

#### Reproduction guide :beetle:
- Start Emacs
- Open a clojure file
- Type `SPC tP`
- The following error message appears in the `*Messages*` buffer:
```
Toggle: parinfer-indent
This toggle is not supported.
```

*Observed behaviour:* :eyes: :broken_heart:
As above

*Expected behaviour:* :heart: :smile:
Am able to switch between parinfer modes by typing `SPC tP`

The expected behaviour can be achieved by typing `SPC SPC parinfer-mode` while in the clojure buffer

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a2bda1682)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(rust shell-scripts clojure javascript python vimscript windows-scripts sql emacs-lisp html markdown csv pdf
      (latex :variables latex-build-command "LaTeX")
      bibtex yaml terraform parinfer auto-completion spell-checking git nginx
      (org :variables org-enable-github-support t org-enable-bootstrap-support t)
      ivy floobits docker
      (treemacs :variables treemacs-lock-width t))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by rakyi** [comment]
I can confirm the issue. The culprit seems to be f13f99d967b60624e2120d57d3faed7f597e7e34 I'm afraid my elisp skills are too lacking to investigate this further.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 170bb98cb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion
      (clojure :variables clojure-enable-clj-refactor t)
      docker emacs-lisp finance git gtags groovy html
      (javascript :variables javascript-fmt-tool 'prettier node-add-modules-path t)
      markdown nginx org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      osx parinfer prettier
      (python :variables python-test-runner 'pytest)
      ranger shell-scripts
      (spell-checking :variables spell-checking-enable-auto-dictionary t)
      sql syntax-checking treemacs version-control yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by duianto** [comment]
The PR:
Fix post-init of parinfer in the clojure layer #12138
has been cherry-picked into the `develop` branch.
