### ISSUE TITLE
Treemacs not working - treemacs/:config: Symbol’s function definition is void: treemacs-git-mode

### ISSUE THREAD

**Issue by AshKash** [syl20bnr/spacemacs#11955]
#### Description :octocat:
treemacs/:config: Symbol’s function definition is void: treemacs-git-mode

#### Reproduction guide :beetle:
- Start Emacs
- Add (treemacs :variables treemacs-use-follow-mode t) to dotspacemacs-configuration-layers restart/reload
- Open a buffer
- Hit M-0 or do M-x treemacs

*Observed behaviour:* :eyes: :broken_heart:
Error (use-package): treemacs/:config: Symbol’s function definition is void: treemacs-git-mode
Error (use-package): treemacs/:config: Symbol’s function definition is void: treemacs-git-mode
In *Messages* buffer:
let*: Symbol’s value as variable is void: treemacs--buffer-name-prefix
add-to-list: Symbol’s value as variable is void: treemacs--buffer-name-prefix

*Expected behaviour:* :heart: :smile:
Treemacs window on side to be displayed as per docs

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 170bb98cb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(php html csv python osx git ivy syntax-checking javascript better-defaults sql
     (treemacs :variables treemacs-use-follow-mode t)
     tabbar ashmacs
     (go :variables go-tab-width 4 go-format-before-save t)
     (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
     (version-control :variables version-control-diff-side 'left))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:

**Comment by Alexander-Miller** [comment]
It's behaving as if treemacs was not installed and loaded. Is treemacs' code actually downloaded, can you find its modules with `SPC f e l`?

**Comment by AshKash** [comment]
Looks like spacelpa had very old version of the package. I disabled it (dotspacemacs-use-spacelpa nil) and it's working fine now.

**Comment by invisiblegaudi** [comment]
I've had the same issue, using ` 0.999.0@29.4 (spacemacs)`,  installing `treemacs` manually from Melpa has fixed it temporarily. 

Is there a way to ensure it always pulls it from melpa?
