### ISSUE TITLE
rev 24d875e break keyboard-layout

### ISSUE THREAD

**Issue by CharlesHD** [syl20bnr/spacemacs#11954]
#### Description :octocat:
New changes (probably commit 24d875e1933be939bbfe73fcaa572c9f66038aa4 ) break keyboard-layout compatibility and yield 
```
Warning (initialization): An error occurred while loading ‘/home/charleshd/.emacs.d/init.el’:

error: Key sequence w c c starts with non-prefix key w c
```

**EDIT**: This is true for bepo configuration. But not for Dvorak. I suspect this is a wild rebinding of `wc` somewhere inside the keyboard-layout machinery.

#### Reproduction guide :beetle:
- Ensure you have the keyboard-layout layer
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Initialization error

*Expected behaviour:* :heart: :smile:
No error

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: usage (rev. 69f63556c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((keyboard-layout :variables kl-layout 'bepo))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS

**Comment by gh-salt** [comment]
I have the same issue. I also use the bepo layer. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3dd753945)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3dd753945)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
```
((keyboard-layout :variables kl-layout 'bepo))
```
- System configuration features: XAW3D XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11

**Comment by CharlesHD** [comment]
For the moment my quick dirty fix is to comment those lines in 
`layers/+spacemacs/spacemacs-defaults/keybindings.el` : 
```elisp
  ;; "wcc"  'spacemacs/toggle-centered-buffer
  ;; "wcC"  'spacemacs/toggle-distraction-free
  ;; "wc."  'spacemacs/centered-buffer-transient-state
```

**Comment by bepolymathe** [comment]
Thank you for this correction which allowed me to solve this problem temporarily. Solutions have since been found?

**Comment by CharlesHD** [comment]
I was planning to do a PR about this (just line commenting). Then an exploratory work to get `evil-window` working. But I forgot. Thanks for the reminder. I'll take a look when i'm in front of a keyboard.

**Comment by PiOverFour** [comment]
@CharlesHD Hi, I have the same error. Are you still working on the issue?

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Keyboard-Layout : Quick Fix of issue #11954 #13159

**Comment by bepolymathe** [comment]
Thank you for this information @duianto . So we can remove these changes without fear? Or will the next update correct this?

**Comment by duianto** [comment]
If your using the `develop` branch (it's the suggested branch until the next `master` branch release (I don't have any insight into when that is)) then you can remove your local changes to fix this issue.
