### ISSUE TITLE
Haskell popup window - how to quit?

### ISSUE THREAD

**Issue by srid** [syl20bnr/spacemacs#1195]
See attached screenshot. In vanilla emacs, I hit 'q' to close this window, but hitting this key starts a keyboard macro in spacemacs.

![screen shot 2015-04-15 at 11 22 11 pm](https://cloud.githubusercontent.com/assets/3998/7175153/76a25e5c-e3c6-11e4-81d7-29ecf867a0a9.png)

**Comment by srid** [comment]
While `C-x C-k` kills this window, it does not automatically go back to the REPL.

**Comment by bmag** [comment]
I also get this problem in some modes. Pressing `iq` usually works for me. `i` to enter insert-mode, then `q` to quit.

**Comment by srid** [comment]
Sounds like not a bug, then. Just a matter of being aware of the fact that buffer-specific Emacs keybindings may only work in the INSERT mode.

**Comment by ocharles** [comment]
I think this should re-opened. It is not expected behavior that you should have to enter insert mode for a read-only buffer. Could you re-open this, @srid?

**Comment by kRITZCREEK** [comment]
:+1: on re-opening.
