### ISSUE TITLE
Modeline separator look weird

### ISSUE THREAD

**Issue by Crides** [syl20bnr/spacemacs#11956]
#### Description :octocat:
Just installed spacemacs and noticed that the separators don't look like the screenshots on the website

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The upper and lower edge of the separator icon are not directly on the edges of the modeline itself.
![screenshot from 2019-02-08 13-37-54](https://user-images.githubusercontent.com/15631555/52502901-91608500-2ba9-11e9-8411-606d07b911e6.png)

*Expected behaviour:* :heart: :smile:
The edges of the separator should be directly on the edges of the modeline. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by Crides** [comment]
This issue seems to be related to the scale of the powerline icons. For separators like arrow, slant, box, bar, alternate, nil, the problem can be solved by changing the `:powerline-scale` option in the following setting to a larger number:

```elisp
dotspacemacs-default-font '("Source Code Pro"
                               :size 15
                               :weight normal
                               :width normal
                               :powerline-scale 1.5)
```

**Comment by dennismayr** [comment]
This quirk hasn't gone away.

It loads weird-looking, but normalizes after invoking `helm` for the first time.

![loading...](https://imgur.com/dQVu4xy.png)
![invoking helm](https://imgur.com/5iHGiNR.png)
![done](https://imgur.com/srNWCKS.png)

`powerline-scale` has been previously adjusted accordingly.

**Comment by pascalsiemsen** [comment]
Same problem here.

**Comment by Deanamic** [comment]
Same problem here, font is ttf-hack with unicode patched in, have tried tweaking powerline scale and separator scale but it doesn't work. Invoking helm fixes the issue
