### ISSUE TITLE
typescript layer with flycheck creates additional flycheck-*.ts files in filesystem

### ISSUE THREAD

**Issue by peter9207** [syl20bnr/spacemacs#11977]
#### Description :octocat:

after adding typescript layer, whenever i edit a file a 'flycheck-<filename>.ts' file appears in my filesystem.

#### Reproduction guide :beetle:
- Start Emacs
- modify any existing *.ts file
- git status

*Observed behaviour:* :eyes: :broken_heart:
 observe there is a flycheck-*.ts file in the filesystem

*Expected behaviour:* :heart: :smile:
the original file is saved, with no additional files

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((typescript :variables typescript-fmt-tool 'typescript-formatter typescript-backend 'tide)
 csv
 (go :variables go-tab-width 4)
 vimscript python terraform helm auto-completion better-defaults javascript yaml themes-megapack emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by phenix-factory** [comment]
I got the same issue on a windows machine. But I thought Windows was the issue since Emacs is super slow on that OS.
