### ISSUE TITLE
auto-evilification broken on latest magit

### ISSUE THREAD

**Issue by axelson** [syl20bnr/spacemacs#11978]
None of the normal spacemacs magit keybindings are working on the latest magit. I'm pretty sure that it's due to this PR that landed today: https://github.com/magit/magit/pull/3728

It changes from [magit-popup](https://github.com/magit/magit-popup) to [transient](https://github.com/magit/transient).

**Comment by bmag** [comment]
We use evil-magit for those keybindings, but it isn't updated for Transient yet, see upstream issue https://github.com/emacs-evil/evil-magit/issues/61.

In the meantime you can add `evil-magit` to `dotspacemacs-excluded-packages` in your dotspacemacs file and live with the non-evil bindings, or rollback the package update to return to an older version of Magit.

As a side note, please read our ["How to make a great bug report"](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report). If the bug wasn't so obvious, it would have been hard to figure out the problem ("broken" and "not working" only tells me there's a problem, but I usually need to know the symptoms of  the problem). Kudos for the relevant links, though.

**Comment by axelson** [comment]
Thanks, noted for next time!

**Comment by yuhan0** [comment]
Looks like Doom just pushed a commit to pin the magit version in the meantime: https://github.com/hlissner/doom-emacs/commit/33ef90343e156f1123d6616a00ff7458018ab8f8, perhaps Spacemacs should do the same? It's a pretty big breaking change and the fixes to evil-magit seem to be non-trivial and might take a while to sort out.

(PS. thanks for the issue labels, that really needs to be a more common practice around here!)

**Comment by bmag** [comment]
@yuhan0 I thought about pinning in a similar way, but I believe we'd also need to pin Magit's several dependencies to avoid other possible issues. I'd rather fix evil-magit than do that legwork, frankly.

**Comment by Silex** [comment]
I think https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bsource-control/git/packages.el needs to be modified as well.

**Comment by duianto** [comment]
Searching `SPC /` for `magit.*popup` in `.emacs.d` (spacemacs develop branch) finds these entries:
```

Search at ~/.emacs.d/
CHANGELOG.develop:1219:22:  - ~SPC g f d~ for =magit-diff-buffer-file-popup= (thanks to Ag Ibragimov)
CHANGELOG.develop:1227:11:- Change =magit-svn-popup= keybinding to =~= (thanks to hornuda)
CHANGELOG.org:1715:36:+ Revamp key bindings to leverage =Magit= dispatch popup and free up some keys
CHANGELOG.org:1718:17:    - ~SPC g >~ magit-submodule-popup
CHANGELOG.org:1719:17:    - ~SPC g A~ magit-cherry-pick-popup
CHANGELOG.org:1720:17:    - ~SPC g c~ magit-commit-popup
CHANGELOG.org:1722:17:    - ~SPC g d~ magit-diff-popup
CHANGELOG.org:1726:17:    - ~SPC g f~ magit-fetch-popup
CHANGELOG.org:1727:17:    - ~SPC g F~ magit-pull-popup
CHANGELOG.org:1729:17:    - ~SPC g l~ magit-log-popup
CHANGELOG.org:1731:17:    - ~SPC g r~ magit-rebase-popup
CHANGELOG.org:1732:17:    - ~SPC g P~ magit-push-popup
CHANGELOG.org:1734:17:    - ~SPC g x~ magit-reset-popup
CHANGELOG.org:1736:21:    displaying the =Magit= dispatch popup
CHANGELOG.org:3059:33:- Redefine key bindings to user Magit popups whenever it is possible
CHANGELOG.org:3865:28:- Add ~#f~ key binding in =magit-status= for =magit-gitflow-popup= (thanks to
layers/+intl/keyboard-layout/packages.el:401:8:      (magit-change-popup-key 'magit-dispatch-popup :actions ?t ?j)
layers/+intl/keyboard-layout/packages.el:402:8:      (magit-change-popup-key 'magit-dispatch-popup :actions ?s ?k)
layers/+intl/keyboard-layout/packages.el:403:8:      (magit-change-popup-key 'magit-dispatch-popup :actions ?S ?K))
layers/+source-control/git/packages.el:160:16:        "gfd" 'magit-diff-buffer-file-popup
layers/+source-control/git/packages.el:163:16:        "gm"  'magit-dispatch-popup
layers/+source-control/git/packages.el:222:27:              (define-key magit-mode-map "%" 'magit-gitflow-popup)))
layers/+source-control/git/packages.el:232:27:              (define-key magit-mode-map "~" 'magit-svn-popup))))
layers/+source-control/git/README.org:64:15:Press ~!~ in *Magit* buffer to open the magit-svn-popup.
layers/+source-control/git/README.org:77:22:| ~~~         | open magit-svn-popup |
layers/+source-control/git/README.org:122:17:| ~SPC g m~   | magit dispatch popup                                |
layers/+source-control/github/packages.el:95:19:      (define-key magit-status-mode-map "@" #'magithub-dispatch-popup))))
layers/+source-control/github/README.org:57:6:the =magit status= buffer (~SPC g s~) and then open the Magithub settings popup
layers/+source-control/github/README.org:82:26:| ~@ C~       | open the Magithub settings popup                 |
layers/+source-control/version-control/keybindings.el:24:8:  ("d" magit-ediff-popup :exit t)
layers/+source-control/version-control/keybindings.el:26:8:  ("F" magit-pull-popup :exit t)
layers/+source-control/version-control/keybindings.el:27:8:  ("P" magit-push-popup :exit t)
layers/+source-control/version-control/keybindings.el:28:8:  ("c" magit-commit-popup :exit t)
layers/+source-control/version-control/keybindings.el:29:8:  ("f" magit-fetch-popup :exit t)
layers/+source-control/version-control/keybindings.el:30:8:  ("l" magit-log-popup :exit t)

```

**Comment by syl20bnr** [comment]
`evil-magit` fix for the loading issue has been pushed a few hours ago and should be available soon. It won't fix the popups documentation.

**Comment by bmag** [comment]
In Spacemacs, we need to apply these changes: (I'll work on a PR)
```
layers/+intl/keyboard-layout/packages.el:401:8:      (magit-change-popup-key 'magit-dispatch-popup :actions ?t ?j)
layers/+intl/keyboard-layout/packages.el:402:8:      (magit-change-popup-key 'magit-dispatch-popup :actions ?s ?k)
layers/+intl/keyboard-layout/packages.el:403:8:      (magit-change-popup-key 'magit-dispatch-popup :actions ?S ?K))
```
remove `-popup` suffix, replace `magit-change-popup-key` with `transient-suffix-put`

```
layers/+source-control/git/packages.el:160:16:        "gfd" 'magit-diff-buffer-file-popup
layers/+source-control/git/packages.el:163:16:        "gm"  'magit-dispatch-popup
```
remove `-popup` suffix, but need to verify that `magit-diff-buffer-file` does the same as `magit-diff-buffer-file-popup`.

```
layers/+source-control/git/packages.el:222:27:              (define-key magit-mode-map "%" 'magit-gitflow-popup)))
layers/+source-control/git/packages.el:232:27:              (define-key magit-mode-map "~" 'magit-svn-popup))))
layers/+source-control/github/packages.el:95:19:      (define-key magit-status-mode-map "@" #'magithub-dispatch-popup))))
```
need to check how `magit-gitflow`, `magit-svn` and `magithub` handle Transient.

```
layers/+source-control/version-control/keybindings.el:24:8:  ("d" magit-ediff-popup :exit t)
layers/+source-control/version-control/keybindings.el:26:8:  ("F" magit-pull-popup :exit t)
layers/+source-control/version-control/keybindings.el:27:8:  ("P" magit-push-popup :exit t)
layers/+source-control/version-control/keybindings.el:28:8:  ("c" magit-commit-popup :exit t)
layers/+source-control/version-control/keybindings.el:29:8:  ("f" magit-fetch-popup :exit t)
layers/+source-control/version-control/keybindings.el:30:8:  ("l" magit-log-popup :exit t)
```
remove `-popup` suffix

**Comment by bmag** [comment]
Here's the PR: https://github.com/syl20bnr/spacemacs/pull/11983

**Comment by bmag** [comment]
Latest develop branch with latest magit and magit-related packages now work, it is safe to update.

**Comment by axelson** [comment]
Awesome thanks, updated to the latest releases and everything is now working for me so I am closing the issue 🎉
