### ISSUE TITLE
markdown-mode: How to define external image opening program

### ISSUE THREAD

**Issue by michelk** [syl20bnr/spacemacs#11973]
With the cursor above an image link, `C-c C-o` opens the image in emacs. This is useless, if the GUI is disabled. 

How do I set an external opening command  to e.g. `eog`?

Thanks, 
Michel

**Comment by nnungest** [comment]
this is defined in the package `markdown-mode.el` which doesn't seem like it supports the concept of images. the function you are describing is `markdown-follow-thing-at-point`  also defined in spacemacs as `, f`  if you `describe-function` you can take a peek at the package internals. it doesn't appear that the package author has made a separate distinction for images.

**Comment by Compro-Prasad** [comment]
The function definition of `markdown-follow-link-at-point` states:

```
        ;; Open full URLs in browser, files in Emacs
```

So, it would be better to report it to https://github.com/jrblevin/markdown-mode
