### ISSUE TITLE
Anaconda mode auto-complete not working for python, issues with jedi 

### ISSUE THREAD

**Issue by nipunarora** [syl20bnr/spacemacs#11974]
#### Description: 
My understanding is that the python-layer comes with a pre-packaged anaconda-mode. However, auto-complete with anaconda-mode does not work in my python buffer. I see the following error in the anaconda-buffer:

AssertionError: Jedi version should be >= 0.13.0, current version: 0.12.1

However when I check the `.cache/anaconda-mode` I see `easy-install.pth                jedi-0.13.2-py3.7.egg           parso-0.3.1-py3.7.egg           service_factory-0.1.5-py3.7.egg` installed.

Hence I do not understand where is the jedi package being picked for.

Auto-complete seems to work fine for everything but python

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
No tool tips with auto-complete suggestions

*Expected behaviour:* :heart: :smile:
Tool tips with auto-complete suggestions

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(go osx python helm
    (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
    better-defaults emacs-lisp git syntax-checking version-control fzf)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
AssertionErrorTraceback (most recent call last)
<ipython-input-1-fe2fa803d967> in <module>
     79 # Setup server.
     80 
---> 81 assert jedi.__version__ >= jedi_dep[1], 'Jedi version should be >= %s, current version: %s' % (jedi_dep[1], jedi.__version__,)
     82 
     83 if virtual_environment:

AssertionError: Jedi version should be >= 0.13.0, current version: 0.12.1

```

**Comment by nipunarora** [comment]
@gcentauri tagging you here since I discussed this with you in the IRC channel

**Comment by nipunarora** [comment]
problem persists on fresh install

```
Searching for jedi>=0.13.0
Skipping development or system egg: jedi 0.13.2
Skipping development or system egg: jedi 0.12.1
Reading https://pypi.org/simple/jedi/
Downloading https://files.pythonhosted.org/packages/c2/bc/54d53f5bc4658380d0eca9055d72be4df45e5bfd91a4bac97da224a92553/jedi-0.13.2-py2.py3-none-any.whl#sha256=c8481b5e59d34a5c7c42e98f6625e633f6ef59353abea6437472c7ec2093f191
Best match: jedi 0.13.2
Processing jedi-0.13.2-py2.py3-none-any.whl
Installing jedi-0.13.2-py2.py3-none-any.whl to /Users/nipun/.spacemacs.d/.cache/anaconda-mode/0.1.13
writing requirements to /Users/nipun/.spacemacs.d/.cache/anaconda-mode/0.1.13/jedi-0.13.2-py3.7.egg/EGG-INFO/requires.txt
Adding jedi 0.13.2 to easy-install.pth file

Installed /Users/nipun/.spacemacs.d/.cache/anaconda-mode/0.1.13/jedi-0.13.2-py3.7.egg
Processing dependencies for jedi>=0.13.0
Searching for parso==0.3.3
Skipping development or system egg: parso 0.3.3
Skipping development or system egg: parso 0.3.1
Reading https://pypi.org/simple/parso/
Downloading https://files.pythonhosted.org/packages/f9/95/917fbfaca4c173651cb8f02bd50712414a0e2a154c8b7077a80027c0864b/parso-0.3.3-py2.py3-none-any.whl#sha256=6ecf7244be8e7283ec9009c72d074830e7e0e611c974f813d76db0390a4e0dd6
Best match: parso 0.3.3
Processing parso-0.3.3-py2.py3-none-any.whl
Installing parso-0.3.3-py2.py3-none-any.whl to /Users/nipun/.spacemacs.d/.cache/anaconda-mode/0.1.13
writing requirements to /Users/nipun/.spacemacs.d/.cache/anaconda-mode/0.1.13/parso-0.3.3-py3.7.egg/EGG-INFO/requires.txt
Adding parso 0.3.3 to easy-install.pth file

Installed /Users/nipun/.spacemacs.d/.cache/anaconda-mode/0.1.13/parso-0.3.3-py3.7.egg
Processing dependencies for parso==0.3.3
Finished processing dependencies for parso==0.3.3
Finished processing dependencies for jedi>=0.13.0
Searching for service_factory>=0.1.5
Reading https://pypi.org/simple/service_factory/
Downloading https://files.pythonhosted.org/packages/51/ad/7e07f1f11919033a883acc18eb60e0f45e221d98edc42657060f36ff451e/service_factory-0.1.5-py3-none-any.whl#sha256=d466a7b1e1f0e196abdc27a69aef6afdaff3b1814146068573e9c46ae8be2658
Best match: service-factory 0.1.5
Processing service_factory-0.1.5-py3-none-any.whl
Installing service_factory-0.1.5-py3-none-any.whl to /Users/nipun/.spacemacs.d/.cache/anaconda-mode/0.1.13
Adding service-factory 0.1.5 to easy-install.pth file

Installed /Users/nipun/.spacemacs.d/.cache/anaconda-mode/0.1.13/service_factory-0.1.5-py3.7.egg
Processing dependencies for service_factory>=0.1.5
Finished processing dependencies for service_factory>=0.1.5

AssertionErrorTraceback (most recent call last)
<ipython-input-1-fe2fa803d967> in <module>
     79 # Setup server.
     80 
```

**Comment by nipunarora** [comment]
` '(python-shell-interpreter "ipython"))` was configured to `ipython` is that correct?

**Comment by Compro-Prasad** [comment]
I wonder if you have installed `jedi` on your system itself?

**Comment by bet4it** [comment]
That's a bug of `anaconda-mode`.
If you use `ipython` as `python-shell-interpreter`, `anaconda-mode` will use the `jedi` which is loaded by `ipython` before, rather than the `jedi` downloaded in `.cache/anaconda-mode`.
You can check `jedi`'s version used by it with `ipython -c "import jedi;print(jedi.__version__)"`.

More details in https://github.com/proofit404/anaconda-mode/pull/327#issuecomment-436956933

**Comment by gcentauri** [comment]
That sounds right @bet4it, I believe @nipunarora resolved this by removing the `ipython` that was already installed.  Can you confirm?  I think this ticket can be closed.

**Comment by nipunarora** [comment]
yep confirmed this is resolved thanks @gcentauri for all the assist :)
