### ISSUE TITLE
Xwidget doesn't work

### ISSUE THREAD

**Issue by maikol-solis** [syl20bnr/spacemacs#11971]
#### Description :octocat:
The xwidget-webkit-browse-url doesn't work. It shows only a blank screen

#### Reproduction guide :beetle:
- Start Emacs
- `SPC` `SPC`
- `xwidget-webkit-browse-url` `RET` `google.com` `RET`

*Observed behaviour:* :eyes: :broken_heart:

Only a blank frame

![xwid](https://user-images.githubusercontent.com/4078489/52633476-1e495e00-2e8a-11e9-9f8b-da7e2cf43108.png)

*Expected behaviour:* :heart: :smile:

The typed website. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 95422ae5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid 
- Completion: helm
- Layers:
```elisp
(html helm auto-completion spell-checking syntax-checking org
      (latex :variables latex-enable-magic t)
      ess pdf themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD

#### Backtrace :paw_prints:
Starting emacs from terminal appeared this

```
(emacs:14146): Gdk-WARNING **: gdkwindow-x11.c:5579 drawable is not a native X11 window
```

**Comment by vishvanath45** [comment]
Replace `google.com` with `https://google.com` and it should work.  

You can close the issue, if it fixes your problem.

**Comment by maikol-solis** [comment]
Thanks, I didn't realize that xwidget was too picky with the http or https. 

However, it fixes the problem partially. 

I can enter to google.com or gmail.com, but I can't introduce text in the text boxes. I put the cursor in the text box, press `RET` and try to type something, but it doesn't work. 

Thanks for the help.

**Comment by Compro-Prasad** [comment]
@maikol-solis AFAIK Xwidget functionality is optionally provided in Emacs and has nothing to do with what spacemacs offers. So, it would be better to report this issue to the Emacs bug tracker.
