### ISSUE TITLE
spacemacs/helm-do-ack is broken

### ISSUE THREAD

**Issue by lukerandall** [syl20bnr/spacemacs#1198]
When I run `SPC s k` for spacemacs/helm-do-ack (or if ack is my only search tool and I run `SPC s /`) it gives the error

    Wrong type argument: commandp, spacemacs/helm-do-ack

as spacemacs/helm-do-ack seems to be undefined.

**Comment by chrisbarrett** [comment]
This is probably the culprit: https://github.com/syl20bnr/spacemacs/blob/fa3c610a426a216fce036bd5ac0bc9cd22941189/spacemacs/packages.el#L1503

Someone has stubbed this function out, and deleted its `interactive` spec while they were at it. I don't know if this stub is necessary, but hacky fix would be to restore the interactive spec.

**Comment by chrisbarrett** [comment]
Uh, ignore the above, that was github search taking me to a completely random commit.

**Comment by syl20bnr** [comment]
This is a pretty old issue and some heavy refactoring has been made in 0.103 regarding search with eternal tools, I'm pretty sure that it has fixed this issue. Feel free to re-open if you have still an issue.

**Comment by lukerandall** [comment]
It is indeed fixed. Thanks @syl20bnr!
