### ISSUE TITLE
Which-key popup name disappears if opened slowly

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#11981]
#### Description :octocat:

When typing a multi key keybinding slowly so that the which-key popup appears for each key, then the second+ popups only show the popup name for a split second before it's removed.

It doesn't seem to be a which-key issue, since the popup name remains without Spacemacs (just Emacs and Which-key).

#### Reproduction guide :beetle:

- Copy this line:
```
(which-key-add-key-based-replacements "C-x a" "abbrev/expand")
```
- Open the Eval prompt `M-S-;`
- Paste (Emacs yank) the copied line `C-y` and evaluate it `RET`
- Press `C-x` and wait for which-key popup to appear. 
  - In Spacemacs the minibuffer only shows `C-x-`
  - Without Spacemacs it shows `C-x- Control-X-prefix`
(Maybe the name was removed in Spacemacs because it's redundant.)
- Press `a`

*Observed behaviour:* :eyes: :broken_heart:

The minibuffer shows `C-x a- abbrev/expand` for a split second before removing the name, and leaving only `C-x a-`.

![which-key name disappears](https://user-images.githubusercontent.com/13420573/52853207-28ce5680-311b-11e9-9c76-77e339654a85.gif)

Without Spacemacs the name remains.

*Expected behaviour:* :heart: :smile:

The which-key popup name should remain visible.

#### Notes :notebook:

Typing `C-x a` quickly without waiting for the `C-x` popup to appear, keeps the name visible.

![which-key name remains](https://user-images.githubusercontent.com/13420573/52853259-59ae8b80-311b-11e9-868b-26cd46c23cd2.gif)

The name also remains if the `C-x` popup is opened and Emacs loses focus (ex: another application is selected), when Emacs is selected again, and `a` is pressed, then the name is visible:
`C-x a- abbrev/expand`.

#### System Info :computer:

- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 95422ae5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby autohotkey colors emacs-lisp git helm html markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by bmag** [comment]
This happens because we set `which-key-idle-secondary-delay` to a lower value than `which-key-echo-keystrokes` (0.01 and 0.02, respectively). It is actually documented in the help for `which-key-echo-keystrokes` and `which-key-idle-secondary-delay`, although in an unclear manner. Setting `which-key-idle-secondary-delay` to 0.04 in `spacemacs-bootstrap/init-which-key` should solve the bug.

I'm hesitant to make changes to develop before the next release (0.300.0), but will make sure to fix it for 0.300.1.
