### ISSUE TITLE
Instead of renaming the file neotree rotates its icon

### ISSUE THREAD

**Issue by Asalle** [syl20bnr/spacemacs#11980]
#### Description :octocat:
Instead of renaming the file neotree rotates its icon
#### Reproduction guide :beetle:
- Start Emacs
- `f t` to open neotree 
- navigate to any file
- `r` to rename
*Observed behaviour:* :eyes: :broken_heart:
File's icon rotates clockwise, rename pop-up does not appear. No errors.
*Expected behaviour:* :heart: :smile:
Rename pop-up appears
#### System Info :computer:
- OS: gnu/linux (Fedora 29)
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown go helm auto-completion emacs-lisp shell org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by robbyoconnor** [comment]
Are you certain that this shouldn't be reported upstream?

**Comment by Asalle** [comment]
> Are you certain that this shouldn't be reported upstream?

Thanks, I will try to report it to neotree

**Comment by Alexander-Miller** [comment]
That'll happen when point is on an image because that activates a position-local keymap that, among other things, lets you rotate images.

**Comment by Asalle** [comment]
Thanks @Alexander-Miller, you made my day!
