### ISSUE TITLE
Mapping SPC .* ESC to keyboard-escape-quit

### ISSUE THREAD

**Issue by jandamm** [syl20bnr/spacemacs#11989]
I'm trying to map the escape key as a always return to `normal` state in spacemacs.

I got rid of the weird ESC leader-key behaviour with this mapping:
```elisp
(global-set-key [escape]
                  (lambda ()
                    (interactive) (progn (keyboard-escape-quit)(evil-normal-state))))
```

I also used this 
```elisp
(spacemacs/set-leader-keys "ESC" 'keyboard-escape-quit)
```
to map `SPC ESC` to quit input.

Is there a way to also map `SPC f ESC`, `SPC w ESC` and so on to just quit?
Without having to `set-leader-keys` for every variation?

Cheers

**Comment by xged** [comment]
> I got rid of the weird ESC leader-key behaviour

What behavior?
> to quit input

What inpput?
> Is there a way to also map SPC f ESC, SPC w ESC and so on to just quit?

Quit what? Following your example:
(spacemacs/set-leader-keys "f \<escape\>" 'keyboard-escape-quit)
(spacemacs/set-leader-keys "w \<escape\>" 'keyboard-escape-quit)

**Comment by jandamm** [comment]
The 'weird' behavior looks like this.
![image](https://user-images.githubusercontent.com/5963139/52964637-1403f400-33a3-11e9-839f-fa75581296a8.png)
I'm not quite sure if it only happens in the Spacemacs buffer but tapping any command afterwards is not working. Tapping `C-M--` results in `ESC C-M-- is undefined`.

Thanks for the hint for mapping `SPC f ESC`. I guess there is no way to avoid mapping `ESC` for every prefix?

**Comment by xged** [comment]
> The 'weird' behavior looks like this.

What have you pressed before? SPC?

> My goal is that whenever I start a SPC command and decide to cancel it, a single press on ESC should cancel the command so I can start a new SPC command or continue typing.

If you mean you want to cancel a leader key chord with ESC in a middle of it, its already a default behavior. I believe there are no default leader key bindings that includes ESC key.

**Comment by xged** [comment]
Hmm "SPC f ESC .." is actually a thing, weird.

**Comment by jandamm** [comment]
It seems my installation is a bit messed up. This happens with 'vanilla' spacemacs.
Fresh .spacemacs file: `evil`, `spacemacs`, `helm`. 

> What have you pressed before? SPC?
I haven't pressed anything (except `ESC`).

![image](https://user-images.githubusercontent.com/5963139/52966724-47954d00-33a8-11e9-8ba0-d623e46b5b50.png)
I have to press `ESC` twice to cancel the 'input-mode'
![image](https://user-images.githubusercontent.com/5963139/52966777-698ecf80-33a8-11e9-823e-413915a1f3d8.png)

**Comment by jandamm** [comment]
I also have Karabiner installed but only modify my internal keyboard not my external (which I used for this)

**Comment by xged** [comment]
What does `C-h-k ESC` outputs if you dont have that "global-set-key [escape]" map?

**Comment by jandamm** [comment]
![image](https://user-images.githubusercontent.com/5963139/52967958-11f26300-33ac-11e9-8371-2d6cac743fbe.png)
Need to type `ESC` three times. Then it says:

> ESC ESC ESC (translated from <escape> <escape> <escape>) runs the command
keyboard-escape-quit (found in global-map), which is an interactive compiled
Lisp function in ‘simple.el’. ...

**Comment by xged** [comment]
Do you use vim mode? Have you knowingly rebinded your ESC key? (we are talking before "global-set-key [escape] .." thing)

**Comment by jandamm** [comment]
Currently I have the `.spacemacs` file you get when you delete the config and select `vim`, `spacemacs` and `helm`

**Comment by xged** [comment]
When you delete the config, is the ESC behavior normal (no "ESC-..")?

**Comment by jandamm** [comment]
I canceled the installation with escape seing the spacemacs buffer but no spacemacs used.
`ESC` still has this weird behavior

**Comment by xged** [comment]
You didnt answer whether you use vim or emacs mode? I presumed you use vim mode and testing ESC from evil-normal mode.

**Comment by jandamm** [comment]
Sorry, yes that is right.
In normal mode in any buffer besides `Spacemacs buffer` (Welcome screen) `ESC` works fine and exits `insert`, `visual`, ... mode and enters `normal` mode.
This does not work in `Spacemacs buffer` and maybe in other `read-only` buffers as well (not tested).

The `SPC ... ESC` not working does not depend on the buffer.

The `fd` 'escape' doesn't work either for me. But I haven't configured anything there. So it wouldn't be enabled if it isn't enabled by default.

**Comment by xged** [comment]
> This does not work in Spacemacs buffer

It works, it just that *Spacemacs* buffer starts in evil-motion-state (for whatever reason).
You can rebind escape to a desired-function in motion state like that: (define-key evil-motion-state-map (kbd "<escape>") 'desired-command).

**Comment by jandamm** [comment]
Okay, but not having a `normal-state` is not the issue, but having the `ESC` completion popup is weird.

**Comment by xged** [comment]
You said ESC works fine in evil-normal-state, didnt you?

**Comment by jandamm** [comment]
Yes, this doesn't open the `ESC` completion. I can fix that with your mapping.

But the `SPC f ESC ...` issue is state independent.

**Comment by xged** [comment]
I would call that a bug. Is `SPC f ..` the only place where that happens?

**Comment by jandamm** [comment]
No every time I start a `SPC` command I have to press `ESC` multiple times.
Doesn't matter if it is `SPC ESC ESC`, `SPC f ESC ESC`, `SPC e ESC ESC` and so ob

**Comment by xged** [comment]
Its fine for me. Does it happens with and without that "global-set-key [escape] .." binding?

**Comment by jandamm** [comment]
Yes, then as well.

I just figured out that it is working in the terminal but not in the gui.
In the terminal the escape key is not named `ESC` but `<escape>` not sure if this makes a difference...

**Comment by jandamm** [comment]
Okay, I found a explanation here: https://stackoverflow.com/questions/16677825/emacs-escape-key
Not sure how to change though

**Comment by xged** [comment]
> in the terminal

Are you talking about `emacs -nw`?

**Comment by jandamm** [comment]
Yes `emacs -nw` or `emacsclient attach -t`

**Comment by xged** [comment]
I am on GUI.

**Comment by jandamm** [comment]
Are you using Mojave, emacs-plus via homebrew (or emacs via homebrew cask)?
If you type `SPC f ESC` you cancel directly instead of this?
![image](https://user-images.githubusercontent.com/5963139/52977777-dfa62d00-33ce-11e9-8cd8-caafc7536b8f.png)

**Comment by xged** [comment]
> You cancel directly instead of this?

`SPC f ESC ..` is a key-chord node (bug). It cancels with (single) ESC as every other key-chord node.

**Comment by yuhan0** [comment]
I recall this is due to ESC being treated as the Meta key for historical reasons. 
In the long run it's probably better to retrain your muscle memory to use `C-g` to cancel things instead, it's pretty universal across all parts of Emacs and (subjectively?) easier to press than reaching for the escape key.

**Comment by jandamm** [comment]
Yes, that's what I figured from reading many old posts.
Haven't found a way to unbind `ESC` from `M`.

`C-g` is a valid option but it doesn't quite fit the `vim` mode.
And on my keyboard I moved the escape key to a more sane position.

**Comment by jandamm** [comment]
For now I "fixed" it by using `Keyboard Maestro` to type two `ESC` whenever I press the escape key in Emacs.
But I would still prefer a Emacs only solution.

**Comment by yuhan0** [comment]
FWIW, my own config involves using Karabiner Elements to map the easy-to-reach`CapsLock-;` to `f13`, which I then bind to `evil-escape` command in Emacs. It acts like a generalized version of the ESC key across more contexts.

A native way to disable the ESC<->meta mapping would be nice, but from what I gathered some time ago, it seems to be hard-coded in Emacs internals. If anyone knows how it would be much appreciated :)

**Comment by jandamm** [comment]
Even better idea.
Now I map my ESC to f19 in Emacs. Which then is mapped to `evil-escape`.

**Comment by mtourne** [comment]
I also find behavior about SPC .* ESC (only in gui) pretty frustrating 

I've tried a few things but ESC seems very special unfortunately : 
https://emacs.stackexchange.com/a/14757

ESC apparently always acts as the prefix for esc-map and that's set in the c code and not changeable.

**Comment by snippins** [comment]
This also happens when using emacs keybindings with any leader key. I have the following lines in my config to get rid of this behavior.

```
(which-key-define-key-recursively global-map [escape] 'ignore)
(which-key-define-key-recursively evil-emacs-state-map [escape] 'ignore)
```

People who use vim keybindings could use the same tricks with other appropriate evil maps to solve this problem.

**Comment by helltone** [comment]
I think I faced same thing. 
I could not escape evil-mode insert mode with ESC in terminal mode of spacemacs on mac.
This 'weird' popup appeared each time.
Then I found that evil-escape package is installed in my dotfile, after checking [readme](https://github.com/syl20bnr/evil-escape/blob/master/README.md)  found that escape chord is 

> fd

**Comment by bldu** [comment]
> This also happens when using emacs keybindings with any leader key. I have the following lines in my config to get rid of this behavior.
> 
> ```
> (which-key-define-key-recursively global-map [escape] 'ignore)
> (which-key-define-key-recursively evil-emacs-state-map [escape] 'ignore)
> ```
> 
> People who use vim keybindings could use the same tricks with other appropriate evil maps to solve this problem.

Your solution works, thank you so much. I've been annoyyed  for a long time!
