### ISSUE TITLE
No protobuf layer available

### ISSUE THREAD

**Issue by Asalle** [syl20bnr/spacemacs#11991]
#### Description :octocat:
No protobuf layer available
#### Reproduction guide :beetle:
- Start Emacs
- `f e d` to open ~/.spacemacs
- add `protobuf` to the  `dotspacemacs-configuration-layers`
- `f e R` to reload configuration

*Observed behaviour:* :eyes: :broken_heart:
```
* Testing settings in dotspacemacs/layers [[file:/home/asalle/.spacemacs::dotspacemacs/layers][Show in File]]
** TEST: Each path in [[file:/home/asalle/.spacemacs::dotspacemacs-configuration-layer-path][dotspacemacs-configuration-layer-path]] is a string
** TEST: Each path in [[file:/home/asalle/.spacemacs::dotspacemacs-configuration-layer-path][dotspacemacs-configuration-layer-path]] exists in filesystem
** TEST: Each layer in [[file:/home/asalle/.spacemacs::dotspacemacs-configuration-layers][dotspacemacs-configuration-layers]] can be found
*** PASS: markdown
*** PASS: go
*** PASS: helm
*** PASS: auto-completion
*** FAIL: protobuf
*** PASS: emacs-lisp
*** PASS: shell
*** PASS: org
** RESULTS: [[file:/home/asalle/.spacemacs::dotspacemacs/layers][dotspacemacs/layers]] passed 7 out of 8 tests

```
*Expected behaviour:* :heart: :smile:
`protobuf` layer successfully installed
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown go helm auto-completion emacs-lisp shell org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2

**Comment by bmag** [comment]
You are using master branch, until the next release protobuf layer is only available in develop branch.

**Comment by darwin67** [comment]
@bmag I was on the develop branch yesterday and it didn't work though?

it was saying it couldn't load the `protobuf-mode` after the installation

**Comment by bmag** [comment]
@darwin67 that's a different issue, and possibly just a download/installation error - in which case Spacemacs should try to install again at next startup (there are also rare cases where the package is "installed" but the actual package file is empty - then you need to delete it to force a new installation attempt).
