### ISSUE TITLE
[Magit] shows `b b` (checkout) as dwim 

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#11997]

**Comment by duianto** [comment]
The name seems to be set by magit:
https://github.com/magit/magit/blob/8b6c39999f0654601058bcae79b9fffe44696a09/lisp/magit-branch.el#L220

```
    ("b" "dwim"              magit-checkout)]
```

**Comment by duianto** [comment]
I don't think it's using which-key, the latest magit changes might be using a hydra to show them.

**Comment by duianto** [comment]
The acronym "DWIM" stands for "Do What I Mean", and typically signifies behaviour that changes contextually in order to do (hopefully) the most useful thing at the time.

source: https://www.reddit.com/r/emacs/comments/6o3nhh/magit_no_longer_branching_for_me/dkg2u8v/

**Comment by xged** [comment]
I presume its intentional then (probably not the best practice of documenting things though.. :) )

**Comment by duianto** [comment]
The wikipedia page also mentions that it is a concept in Emacs:
>The DWIM concept has been adopted by users of the GNU Emacs text editor to describe Emacs Lisp functions or commands that "do the right thing" depending on context, and do not specifically correct the user's typing. The Emacs wiki gives the example of a file copy command that is able to deduce the destination path from a split window configuration that contains two dired windows, one of which displays the source path. DWIM functionality is often mentioned in the command's name; GNU Emacs has a comment-dwim function that comments out a selected region if uncommented, or uncomments it when already commented out, using comment characters and indentation appropriate for the environment and current context.

source: https://en.wikipedia.org/wiki/DWIM

But your right it isn't very descriptive if one hasn't seen it before. And I'm sure that there are some people trying out Magit that haven't used Emacs before.
