### ISSUE TITLE
Windows 7 ownership of directories

### ISSUE THREAD

**Issue by vadtec** [syl20bnr/spacemacs#11999]
#### Description :octocat:
Ownership of ~/.emacs.d/server folder is set to "Administrators" rather than the user account during install.

#### Reproduction guide :beetle:
- Download and extract emacs into an appropriate folder (c:\emacs26)
- Download c7a103a772d808101d7635ec10f292ab9202d9ee as a tarball and extract into ~/.emacs.d/ (ends up in %appdata%/.emacs.d/)
- Run emacs with --insecure --debug-init

*Observed behaviour:* :eyes: :broken_heart:
After install is done, receive the following message:

----------
```
Warning (initialization): An error occurred while loading ‘c:/Users/Vadtec/AppData/Roaming/.emacs.d/init.el’:

error: ‘c:/Users/Vadtec/AppData/Roaming/.emacs.d/server’ is not a safe directory because it is not owned by you (owner = nil (544))

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```
----------

Re-run emacs (M-q-R), receive the following message:

----------
```
Debugger entered--Lisp error: (error "‘c:/Users/Vadtec/AppData/Roaming/.emacs.d/server’ is not a safe directory because it is not owned by you (owner = nil (544))")
  signal(error ("‘c:/Users/Vadtec/AppData/Roaming/.emacs.d/server’ is not a safe directory because it is not owned by you (owner = nil (544))"))
  error("`%s' is not a safe directory because %s" "c:/Users/Vadtec/AppData/Roaming/.emacs.d/server" "it is not owned by you (owner = nil (544))")
  server-ensure-safe-dir("~/.emacs.d/server/")
  server-start()
  (if (server-running-p) nil (server-start))
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require 'core-spacemacs) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require 'server) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "c:/Users/Vadtec/AppData/Roaming/.emacs.d/init.el" nil t)  ; Reading at buffer position 1264
  load-with-code-conversion("c:/Users/Vadtec/AppData/Roaming/.emacs.d/init.el" "c:/Users/Vadtec/AppData/Roaming/.emacs.d/init.el" t t)
  load("c:/Users/Vadtec/AppData/Roaming/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1000be22d>)()
  command-line()
  normal-top-level()
```
----------

*Expected behaviour:* :heart: :smile:
I would expect the installer to not change ownership of files and/or directories.

After checking the folder ownership, it was set to "Administrators". Once I changed ownership of it (and everything within it) to my user and restarted the issue went away.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by DanLanglois** [comment]
The installer does not have permission to  change ownership of files and/or directories. There is a logical dimension to this point. They are called 'permissions', right? For example, an app might want permission to see your device contacts or location.  You can control which permissions an app can access. I would think about whether you installed as administrator in the first place. Alternatively, this is some spectacularly mysterious bug-of-all-time, in Windows itself, anything is possible..

**Comment by didierbroska** [comment]
Not run emacs in Administrator if you install spacemacs for your own user.
