### ISSUE TITLE
Commenting broken - error: void-variable display-line-numbers-type

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#11995]
#### Description :octocat:
Commenting broken - error: (void-variable display-line-numbers-type)

#### Reproduction guide :beetle:
- Start Emacs
- ```SPC c l```

*Observed behaviour:* :eyes: :broken_heart:
- Lisp error: (void-variable display-line-numbers-type)

*Expected behaviour:* :heart: :smile:
- Commenting line

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-variable display-line-numbers-type)
  evilnc--forward-line(0)
  evilnc--operation-on-lines-or-region((lambda (b e) (evilnc--fix-buggy-major-modes) (evilnc--comment-or-uncomment-region b e)) 1)
  evilnc-comment-or-uncomment-lines(1)
  (let ((evilnc-invert-comment-line-by-line nil)) (evilnc-comment-or-uncomment-lines arg))
  spacemacs/comment-or-uncomment-lines(1)
  funcall-interactively(spacemacs/comment-or-uncomment-lines 1)
  call-interactively(spacemacs/comment-or-uncomment-lines nil nil)
  command-execute(spacemacs/comment-or-uncomment-lines)

```

**Comment by duianto** [comment]
`SPC c l` works as expected for me in both Windows 10 1803 with Emacs 26.1 and Ubuntu 18.04.1 with Emacs 27.0.50, in both a terminal and GUI:
- In the `*Spacemacs*` buffer it asks for comment syntax.
- In `.spacemacs` it comments the current line.

#### System Info :computer:                                                     
- OS: gnu/linux                                                                 
- Emacs: 27.0.50                                                                
- Spacemacs: 0.300.0                                                            
- Spacemacs branch: develop (rev. 4b195ddfc)                                    
- Graphic display: nil                                                          
- Distribution: spacemacs                                                       
- Editing style: vim                                                            
- Completion: helm                                                              
- Layers:                                                                       
```elisp                                                                        
(helm emacs-lisp git multiple-cursors org treemacs version-control)             
```                                                                             
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND G\
PM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M1\
7N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XW\
IDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

**Comment by bmag** [comment]
Backtrace shows it is probably a bug in `evilnc--forward-line`. Please report upstream at [evil-nerd-commenter](https://github.com/redguardtoo/evil-nerd-commenter). Variable `display-line-numbers-type` was introduced in Emacs 26.1 and isn't defined in previous Emacs versions. Also, I have to say I can't understand why evilnc cares about line numbers at all.

**Comment by sebhahn** [comment]
Thanks @bmag! I reported it upstream.

**Comment by sebhahn** [comment]
Problem has been fixed!
