### ISSUE TITLE
Emacs flickers/flashes when typing or scrolling.

### ISSUE THREAD

**Issue by carloscheddar** [syl20bnr/spacemacs#12009]
#### Description :octocat:
Emacs flickers/flashes when typing or scrolling on all modes.

![emacs flicker-trim-480 mov](https://user-images.githubusercontent.com/3360539/53180771-b2bf6900-35cc-11e9-9d14-c2065ee02efc.gif)

#### Reproduction guide :beetle:
- Start Emacs
- Scroll or type
- Keep scrolling/typing until screen flashes

*Observed behaviour:* :eyes: :broken_heart:
Emacs flickers/flashes.

*Expected behaviour:* :heart: :smile:
Emacs shouldn't flicker/flash.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python react sql
        (helm :variables helm-use-frame-when-more-than-two-windows nil)
        auto-completion emacs-lisp
        (osx :variables osx-use-option-as-meta nil)
        git html
        (markdown :variables markdown-live-preview-engine 'vmd)
        ruby org javascript coffeescript yaml themes-megapack scala csv syntax-checking version-control emoji)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
No error seems to be showing even with `debug-on-error` enabled.

**Comment by carloscheddar** [comment]
I fixed this issue by using another port of emacs. Instead of emacs-plus I installed emacs from homebrew cask with `brew cask install emacs`.

**Comment by conorfoley** [comment]
I had this same issue, and it was only resolved by installing this specific port: https://github.com/railwaycat/homebrew-emacsmacport

**Comment by xiaozhu1337** [comment]
> I had this same issue, and it was only resolved by installing this specific port: https://github.com/railwaycat/homebrew-emacsmacport

best solution.
