### ISSUE TITLE
Interrupted system call when on vbox share (magit)

### ISSUE THREAD

**Issue by igoralmeida** [syl20bnr/spacemacs#12001]
#### Description :octocat:
At $WORK I run Spacemacs in a linux virtual machine on a windows host[1]. This
VM has access to windows folders using virtualbox's Shared Folders feature
(`mount` reports the share as type `vboxsf`).

Occasionally I use magit for repositories that live in the windows filesystem,
and I get intermittent (but frequent enough to be annoying) errors due to
"Interrupted system call". This does not seem specific to magit (sometimes
org-agenda also complains), that's just the most reliable way I could find for
reproducing this.

So inside the magit-status window (`SPC g s`) I can press `g r` to refresh the
buffer, and if I'm lucky I'll get an error in the minibuffer: "Setting current
directory: interrupted system call...". Using debug-on-error I managed to create a
simple script that (tries to) reproduces the problem, and here's a minimal
stacktrace:

```
Debugger entered--Lisp error: (file-error "Setting current directory" "Interrupted system call" "/path/to/some/vboxsf/share/")
  call-process("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "rev-parse" "--show-toplevel")
  apply(call-process "git" nil (t nil) nil ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "rev-parse" "--show-toplevel"))
  process-file("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "rev-parse" "--show-toplevel")
  eval-buffer()  ; Reading at buffer position 164
  funcall-interactively(eval-buffer)
  call-interactively(eval-buffer nil nil)
  command-execute(eval-buffer)
```

[1] VirtualBox 5.2.22, but this has happened on previous versions and will
probably continue to happen if I upgrade.

#### Reproduction guide :beetle:
- Start Emacs
- Evaluate the following script (e.g. using the scratch buffer)
```
(cd "/path/to/some/vboxsf/share/")
(process-file "git" nil '(t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "rev-parse" "--show-toplevel")
```
- Cry after it happens for the tenth time in a row

*Observed behaviour:* :eyes: :broken_heart:
Error shows up in the minibuffer. Or magit just breaks and you have to open everything again.

*Expected behaviour:* :heart: :smile:
No error. Running the same command (shown below) in a terminal does not show an[y visible] error, and the command has return value 0.
```
igor@host /path/to/some/vboxsf/share/ $ git --no-pager --literal-pathspecs -c core.preloadindex=true -c log.showSignature=false rev-parse --show-toplevel

/path/to/some/vboxsf/share/
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa45)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git version-control
      (latex :variables latex-enable-auto-fill t latex-enable-folding t)
      markdown
      (org :variables org-enable-github-support t org-clock-mode-line-total 'current org-enforce-todo-dependencies t)
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
      semantic octave rcirc
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
      python journal theming)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (file-error "Setting current directory" "Interrupted system call" "/path/to/some/vboxsf/share/")
  call-process("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "rev-parse" "--show-toplevel")
  apply(call-process "git" nil (t nil) nil ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "rev-parse" "--show-toplevel"))
  process-file("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "rev-parse" "--show-toplevel")
  eval-buffer()  ; Reading at buffer position 164
  funcall-interactively(eval-buffer)
  call-interactively(eval-buffer nil nil)
  command-execute(eval-buffer)

```

**Comment by Compro-Prasad** [comment]
> Error shows up in the minibuffer. Or magit just breaks and you have to open everything again.

What is *everything* that you have mentioned?

**Comment by igoralmeida** [comment]
Sometimes the magit-status goes entirely blank. Sometimes just the syntax highlighting for the diffs shuts down. I seem to recall it happening just after closing a COMMIT_EDITMSG buffer as well. The point being, think of "everything" as "I'm not sure how to recover from this, so I just close magit-related stuff and start over with `SPC g s`".

**Comment by SutharMukesh** [comment]
Also having the same issue of **interrupted system calls**, the worst part is that it happens randomly.
