### ISSUE TITLE
What is the most proper way to add org modules?

### ISSUE THREAD

**Issue by Anton-Latukha** [syl20bnr/spacemacs#12003]
#### Description :octocat:
Spacemacs has a specially crafted structure for Org-mode.

I want to clarify a question to solve for me and others in a doc/PR about this.

Officially by `org-mode` - additional (especially official) extensions to `org-mode` recommended to be installed by extending the `org-modules` list.
I asked a question on Gitter, and recieved some responses, as also found my own, but nothing really solid.
I what to clarify what is the most proper way to add official org modules to extend `org-mode` from the `org` layer.

---

Also good to have some input to maybe open other issue/PR. Default `org-modules` list has many modules enabled by default:
```elisp
(org-w3m org-bbdb org-bibtex org-docview org-gnus org-info org-irc org-mhe org-rmail org-eww)
```
And most of them probably not used by many if not majority people that use Spacemacs. Browsers AFAIK in Spacemacs not in great shape.
Probably it can be right to allow people to populate `org-modules` from the ground-up.

#### Reproduction guide :beetle:
- Start Emacs
Wonder what is the proper way to add `org-habit` to extend `org` layer.

*Observed behaviour:* :eyes: :broken_heart:
Declare installation of `org-habit` after the initialization of `org` layer.

*Expected behaviour:* :heart: :smile:
Something beautiful. Like:
```elisp
(org :variables
  org-modules '(
    org-habit
    org-capture
    org-id
    org-protocol
    org-brain
    )
)
```
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 95422ae5d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm

**Comment by agzam** [comment]
Modules have to be extended, not in prescriptive manner like you suggesting using `:variables`. Simply doing something like this should work `(add-to-list 'org-modules 'org-tempo t)`.

**Comment by Anton-Latukha** [comment]
Yes, currently I do a number of (add-to-list ...) expressions.
It does not seem like the best way to do it.
1. On every module - Emacs runs an `add-to-list` expression that adds a single element to the beginning of the list.
2. Official `org-mode` documentation states to add new entries to the end of the list. So if respect that - `nreverse` -> `add-to-list` -> `nreverse` it back. For every element.  

I did:
```elisp
require 'org
(nconc org-modules
       '(
         org-capture
         org-habit
         org-id
         org-protocol
         org-brain
         )) 
```
It is one invocation and code easily readable/modefiable. `nconc` in this form adds values to the back, back to the referred list.

But I want to know is I am doing the completely right thing regarding Spacemacs `org` layer.

**Comment by michaelherold** [comment]
This is what I'm using in a private layer:

```elisp
# packages.el
(with-eval-after-load 'org
  (add-to-list 'org-modules 'org-habit t))
```

**Comment by Anton-Latukha** [comment]
Basically I got sure that Org packages just need to be loaded, there is no need to declare them as modules explicitly.
