### ISSUE TITLE
Yapfify doesn't use python version corresponding to virtualenv version

### ISSUE THREAD

**Issue by oliveratutexas** [syl20bnr/spacemacs#12004]
#### Description :octocat:
Yapfify doesn't match the virtualenv version set by [SPC m v s] in python mode.

#### Reproduction guide :beetle:
- create a python virtualenv w/ python 3.6
- Start Emacs
- use some 3.6 specific syntax like
```
def foo(var : str) -> str:
   pass
```
- run yapify [SPC m =] in python mode
- open the yapfify buffer [ SPC b b]

*Observed behaviour:* :eyes: :broken_heart:
Code won't get formatted and the path will show a python version that's older on most systems.

*Expected behaviour:* :heart: :smile:
Code will be formatted with the version specified in the virtualenv. 

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion
      (auto-completion :variables auto-completion-enable-snippets-in-popup t)
      emacs-lisp markdown multiple-cursors git neotree debug nginx csv
      (markdown :variables markdown-live-preview-engine 'vmd)
      python javascript tmux yaml django ansible docker sql shell
      (shell :variables shell-default-full-span nil)
      github html spell-checking syntax-checking version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by beyondpie** [comment]
In my situation, everything works fine. I usually first set the virtual env.  In that virtual env, I personally install a new yapf with pip in that env. 
Is that because the yapf is not installed in your current virtual env?
