### ISSUE TITLE
Ledger mode missing ledger-set-year command

### ISSUE THREAD

**Issue by RidaAyed** [syl20bnr/spacemacs#12005]
#### Description :octocat:
I'd like to set the year for quicker addition of transactions, though the command `ledger-set-year` seems not availabe. `Spc` `Spc` and entering `ledger-set-year` returns nothing similar. Removing `.ledgerrc` didn't help.

#### Reproduction guide :beetle:
- Start Emacs
- Add finance layer
- Sync configuration `Spc` `f` `e` `R`
- Open somejournal.ledger
- Press `,` `y`

*Observed behaviour:* :eyes: :broken_heart:
command-execute: Wrong type argument: commandp, ledger-set-year

*Expected behaviour:* :heart: :smile:
Can `ledger-set-year` by hitting `,` `y`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(finance yaml csv gnus javascript
         (org :variables org-enable-reveal-js-support t)
         journal ranger python plantuml html markdown helm auto-completion better-defaults git markdown org
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by nnungest** [comment]
looking at the package its hard to tell why you are expecting ledger-set-year to exist. is this a ledger-cli command? Have you used this function before? Or is this a feature request?

**Comment by RidaAyed** [comment]
Thank you Nick @nnungest

I'm not sure I understand your question quite well, since I'm refering to an out-of-the-box function from this layer: https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btools/finance#ledger-1

Does this help?

**Comment by nnungest** [comment]
Yes it does. I see that it is there and indeed is not functioning for me either on Develop
