### ISSUE TITLE
M-RET is acting like major-mode-leader-key

### ISSUE THREAD

**Issue by chrisbarrett** [syl20bnr/spacemacs#1200]
`M-RET` has inexplicably started displaying commands bound to the `SPC m` prefix. Is this expected?

**Comment by tuhdo** [comment]
In `holy-mode`, yes. `M-m` executes global leader and `C-M-m` (or `M-RET`) executes major mode leader.

**Comment by chrisbarrett** [comment]
Evil user. No want.

**Comment by tuhdo** [comment]
Did you update your `.spacemacs` file after the latest release? I think if you don't, then you should try it.

**Comment by chrisbarrett** [comment]
Thanks, I'll do that now.

**Comment by CarlQLange** [comment]
I kinda wish there was a mechanism for this...

**Comment by chrisbarrett** [comment]
So turns out the holy-mode leader bindings are enabled in insert state. You can set them to `nil` to disable them.
```lisp
(setq dotspacemacs-emacs-leader-key nil)
(setq dotspacemacs-major-mode-emacs-leader-key nil)
```
