### ISSUE TITLE
Editing mode characters in powerline superimposed

### ISSUE THREAD

**Issue by lzmartinico** [syl20bnr/spacemacs#12016]
#### Description :octocat:
Editing mode characters in powerline are superimposed, due to a font spacing issue, where the character seems to end with the right margin of the letter within the circle, rather than the circle itself. Tested by changing the powerline width and scale to various value with no results

#### Reproduction guide :beetle:
- Start Emacs
- Set editing mode to Emacs (holy) or Hybrid

*Observed behaviour:* :eyes: :broken_heart:
The `h` or `e` character are partially superimposed to the Unicode character `Ⓔ`  (the ascii character starts at the end of E within Ⓔ , rather than the end of the circle) when using a patched font (I haven't tried them all, but all the ones I used had the same problem) 

*Expected behaviour:* :heart: :smile:
The letter Ⓔ and h should be displayed distinctly (i.e `Ⓔ h` rather than `Ⓔh`)

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77) (also tested on develop, rev. 4b195ddfc)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults bibtex emacs-lisp finance git helm latex markdown org python semantic
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (spell-checking :variables enable-flyspell-auto-completion t)
                 syntax-checking version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB THREADS

**Comment by nnungest** [comment]
terminal emulator?

**Comment by Compro-Prasad** [comment]
Would be great to see a screenshot.

**Comment by lzmartinico** [comment]
Yes, and I am using the standard Mac Terminal app.
<img width="408" alt="screen shot 2019-02-27 at 10 34 23 am" src="https://user-images.githubusercontent.com/5137520/53484277-5dc39d00-3a7b-11e9-9443-9275747ad55d.png">

**Comment by Compro-Prasad** [comment]
Which mode does the `h` represent?

**Comment by lzmartinico** [comment]
That would be Hybrid mode - see 
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#minor-modes

**Comment by lzmartinico** [comment]
The issue is still valid, on the latest commit of the develop branch

**Comment by duianto** [comment]
Confirmed

It's observed in the PopOS terminal:

![VirtualBoxVM_2020-06-03_13-27-53](https://user-images.githubusercontent.com/13420573/83641171-72131580-a5ad-11ea-9186-63faf660aeec.png)

The mode line indicator is defined here:
https://github.com/syl20bnr/spacemacs/blob/23976ab799b09b41ad8d0faac6c2f54ebb0c3586/layers/%2Bdistributions/spacemacs-bootstrap/packages.el#L559

Adding a space between the characters solves it in the terminal:

![VirtualBoxVM_2020-06-03_13-36-36](https://user-images.githubusercontent.com/13420573/83641402-c61dfa00-a5ad-11ea-8d18-e875ea06d4fc.png)

but then there's an extra space when not using a terminal:

![2020-06-03_15-24-15](https://user-images.githubusercontent.com/13420573/83641975-8acffb00-a5ae-11ea-93e9-34ede35b1046.png)


<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23976ab79)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-use-company-box t auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 emacs-lisp git helm html javascript lsp
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org"))
 (python :variables)
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23976ab79)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-use-company-box t auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 emacs-lisp git helm html javascript lsp
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org"))
 (python :variables)
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by duianto** [comment]
The same issue is observed with:
- `SPC t h i` highlight indentation
- `SPC t h c` highlight indentation current column

![VirtualBoxVM_2020-06-03_21-39-33](https://user-images.githubusercontent.com/13420573/83681770-29764f00-a5e3-11ea-8c00-f27665440409.png)

A PR is pending with a possible fix:
[core] Terminal fix mode line indicator overlap #13638

**Comment by smile13241324** [comment]
Fix is merged, @lzmartinico can you double check?

**Comment by lzmartinico** [comment]
Yes, #13638 solved this. Thanks for fixing this!
