### ISSUE TITLE
Syntax highlighting in Haskell files is broken

### ISSUE THREAD

**Issue by seanparsons** [syl20bnr/spacemacs#12015]
#### Description :octocat:
Since a particular commit in develop my syntax highlighting for Haskell files has been broken. I suspect some important aspect of this is that I run emacs from a shell which has used direnv to load a nix-shell instance for the projects I work on. Which for the default Emacs way of loading the path means things like cabal and ghc aren't available. I _assume_ this means that it's failing to run a tool and the end result is that it completely fails to do some detection and bombs out, but I've never seen any errors or indications as to what is wrong.

#### Reproduction guide :beetle:
- Start Emacs
- Open a Haskell file.

*Observed behaviour:* :eyes: :broken_heart:
If I try the commit before:
https://github.com/syl20bnr/spacemacs/commit/152d41e7cf907482fcea7781a5e6337fd8a07752#diff-c3268d8a736d68ae0f7cff07aaf344d0
then my syntax highlighting in Haskell files works. After that particular commit the syntax highlighting is completely empty.

*Expected behaviour:* :heart: :smile:
Syntax highlighting works correctly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. 152d41e7c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((haskell :variables haskell-completion-backend 'company-ghci haskell-process-type 'cabal-ghci)
 yaml docker colors helm auto-completion better-defaults emacs-lisp html javascript typescript games git github markdown org spell-checking syntax-checking version-control xkcd latex nixos)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Compro-Prasad** [comment]
That seems like an old commit. When did you notice it?

**Comment by seanparsons** [comment]
I only noticed it because I had to install from fresh a week or so ago, decided to track down exactly what had changed today.
