### ISSUE TITLE
Evil-iedit wrongly places the cursor on the left top corner in clojure-mode when match word is removed

### ISSUE THREAD

**Issue by FieryCod** [syl20bnr/spacemacs#12018]
#### Description :octocat:
When I'm in Clojure mode.
     When I run evil-iedit and use D to delete all occurrences then the cursor goes to
     top of the window while it should stay in place like in other modes.

#### Reproduction guide :beetle:
- Start Emacs
- Go to some `.clj` file
- visual select some word which has more than 1 occurence
- spc s e
- D
- cursor is on the left top corner

*Observed behaviour:* :eyes: :broken_heart:
Cursor goes to the left top corner

*Expected behaviour:* :heart: :smile:
Cursor should stay in place like in other modes

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup nil auto-completion-return-key-behavior nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence-delay 0.3 auto-completion-tab-key-behavior 'complete)
 asciidoc
 (rust :variables rust-backend 'lsp rust-format-on-save t)
 lsp multiple-cursors
 (python :variables python-backend 'anaconda)
 (git :variables git-magit-status-fullscreen t)
 version-control
 (org :variables org-enable-github-support t)
 (shell :variables shell-default-height 35 shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh")
 (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips t)
 (treemacs :variables treemacs-silent-refresh t treemacs-collapse-dirs 0 treemacs-use-git-mode 'simple)
 (typescript :variables typescript-backend 'tide)
 (ruby :variables ruby-version-manager 'rvm ruby-enable-enh-ruby-mode t)
 (clojure :variables clojure-enable-fancify-symbols t clojure-enable-sayid t clojure-enable-clj-refactor t)
 ivy
 (go :variables go-use-gometalinter t go-backend 'lsp)
 nginx ruby-on-rails yaml colors spotify haskell docker javascript evil-commentary csv better-defaults html github emacs-lisp parinfer plantuml sql)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
No errors
```

**Comment by duianto** [comment]
Do you have the latest version of `iedit-20181114.950`?

I had noticed this same issue in `web-mode` with the example below, but I'm unable to reproduce the issue anymore, and in my notes about the issue I have written that this commit might have fixed it:

fix `iedit-mode-on-fuction problem https://github.com/victorhge/iedit/commit/59cb214f2edce368dfeb202b485e1b5f844ea959

#### Previous reproduction steps

- Open or create a buffer in `web-mode`:
- Paste or type:
```
(test)
(test)
(test)
```
- Move the cursor to the second lines word `test`
- Start iedit: `SPC s e`
- Press either of these:
  - `S` `(evil-iedit-state/substitute)`
  - `D` `(iedit-delete-occurrences)`
  - `c` `(evil-iedit-state/evil-change)` followed by a motion: `w`, `e`, or `l`

The cursor jumps to the beginning of the buffer, in evil insert mode

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp git github haskell helm html markdown multiple-cursors org shell spell-checking treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by FieryCod** [comment]
I have the newest version of `evil-iedit`. I also tried to recompile the el file without success. Should I report the bug upstream?

**Comment by duianto** [comment]
I'm not able to reproduce it without Spacemacs either.

With `GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30`
and the packages:
- `iedit-20181114.950`
- `evil-20190222.1212`
- `evil-iedit-state-20180607.558`
- `clojure-mode-20190227.1057`

With your clojure example from the iedit issue (linked above this comment).
```clojure
(ns basic-lambda.lambda
  (:require
   [fierycod.holy-lambda.core :as h]))

(h/deflambda BasicLambda
  [event context]
  (println event)
  {:status-code 200
   :body {}})
```

with the cursor on `event` in the line `(println event)`, 
- `M-x` `evil-iedit-state/iedit-mode`
- Press: `D`

#### Observed
The two occurrences of `event` were deleted and the cursor didn't move `(println [])` ([] = box cursor)

**Comment by FieryCod** [comment]
I will take a closer look into it on weekend, maybe there is something else I’m missing.

**Comment by FieryCod** [comment]
@duianto The issue is when you use `show-smartparens-mode` at least this is what I spotted. Could you please try to reproduce?

**Comment by duianto** [comment]
No change (the cursor remains) after:
- Installing the package `smartparens-20190128.1747`
- Calling: `M-x` `show-smartparens-mode` (either before or after calling `M-x` `evil-iedit-state/iedit-mode`)
- Pressing `D` to call `iedit-delete-occurrences`.

>show-smartparens-mode is a variable defined in ‘smartparens.el’.
Its value is t
Local in buffer clojure-iedit-issue-test.clj; global value is nil

**Comment by FieryCod** [comment]
That’s very bizzare to me. Nevertheless  after disabling `show-smartparens-mode` iedit works perfectly fine so let’s close it for now.

**Comment by FieryCod** [comment]
Btw did you use both `show-smartparens-mode` and `smartparens-mode`?

**Comment by duianto** [comment]
Still no cursor jump with either `show-smartparens-mode` or `smartparens-mode`.

The same results (no cursor jump) were also observed when trying the steps above, both with and without Spacemacs (with updated packages on the latest develop branch 4b195ddfc9228256361e0b264fe974aa86ed51a8) in `Ubuntu 18.04.2 LTS` running as a `VirtualBox` client, with `Windows 10 version 1803` as the host.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(clojure emacs-lisp git helm multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

**Comment by polothy** [comment]
@FieryCod were you able to turn off `show-smartparens-mode` from your config file?  If so, what code did you use and what section of your config file did you put it in?  Ran into the same problem as you and `SPC SPC turn-off-show-smartparens-mode` fixes it, but would like to turn that off on startup.  Thanks for any help you can give!

**Comment by polothy** [comment]
Figured it out

**Comment by polothy** [comment]
@duianto asked me to post my info about this issue, so here it goes.

#### Reproduction guide :beetle:

My reproduction steps are exactly the same [as these](https://github.com/syl20bnr/spacemacs/issues/12018#issuecomment-467834694) under the `Previous reproduction steps` section.

Here's a gif of me in the scratch buffer, switched to `web-mode` pushing the keys `SPC s e` and then `D` and you can see the cursor jumping:

![iedit_jump](https://user-images.githubusercontent.com/634657/60215309-322fa400-981c-11e9-8a92-fb11a8016681.gif)

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 50c27cd3f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript php html csv deft docker rust groovy yaml
            (go :variables go-use-golangci-lint t godoc-at-point-function 'godoc-gogetdoc gofmt-command "goimports" go-format-before-save t go-tab-width 4)
            helm
            (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip t)
            emacs-lisp git markdown multiple-cursors treemacs
            (org :variables org-want-todo-bindings t)
            osx
            (terraform :variables terraform-auto-format-on-save t)
            (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/local/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
            (ranger :variables ranger-show-preview t)
            (spell-checking :variables spell-checking-enable-by-default nil)
            syntax-checking version-control theming xclipboard)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Workaround 💡 

Disable `show-smartparens-mode` by adding the following to your `(defun dotspacemacs/user-config ()` section:

```elisp
  ;; Disable show-smartparens-mode as it breaks iedit
  (show-smartparens-global-mode -1)

```

**Comment by FieryCod** [comment]
@polothy This is what I did as well!
