### ISSUE TITLE
org-insert-structure-template not working since easy-template refactoring.

### ISSUE THREAD

**Issue by jjzmajic** [syl20bnr/spacemacs#12012]
#### Description :octocat:
`org-insert-structure-template` is not working.

#### Reproduction guide :beetle:
- Start Emacs
- Open org mode file
- Press `SPC m i b` to insert structure-template

*Observed behaviour:* :eyes: :broken_heart:
Something is modifying `org-structure-template-alist` and adding an entry in the
format used when `easy-templates` were a thing. `add-variable-watcher` reports `nil`
as `WHERE` (where the variable was modified). This breaks `org-insert-structure-template`.

*Expected behaviour:* :heart: :smile:
- Entry is added in new format so that `("n" ("#+BEGIN_NOTES\n?\n#+END_NOTES") "")` becomes `("n" "notes")`
- Or alist is not modified at all

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm better-defaults
      (neotree :variables neo-theme 'ascii)
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell shell-enable-smart-eshell nil)
      spell-checking
      (syntax-checking :variables syntax-checking-enable-by-default t flycheck-global-modes t)
      (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-return-key-behavior 'complete)
      multiple-cursors
      (ranger :variables ranger-parent-depth 2 ranger-show-hidden nil ranger-show-preview t ranger-cleanup-on-disable t ranger-ignored-extensions
              '("mkv" "iso" "mp4"))
      version-control git semantic dap lsp cscope emacs-lisp shell-scripts
      (python :variables python-backend 'anaconda)
      (c-c++ :variabes c-c++-enable-clang-support nil c-basic-offset 4 c-default-style "linux" clang-format-style "WebKit")
      (java :variables java-backend 'lsp lsp-eldoc-enable-hover nil)
      nim
      (javascript :variabes javascript-disable-tern-port-files nil js2-include-node-externs t)
      html vimscript systemd
      (org :variables org-highlight-latex-and-related
           '(latex script entities)
           org-enable-github-support t org-enable-bootstrap-support t org-enable-reveal-js-support t org-agenda-files "/home/uros/Sync/org/agendarc" org-adapt-indentation nil org-todo-keywords
           '((sequence "TODO" "|" "DONE" "CANCELED" "NODO"))
           org-enable-org-journal-support t org-latex-pdf-process
           (list "latexmk -f -pdf %f"))
      pdf latex
      (bibtex :variables org-agenda-list t org-ref-default-bibliography
              '("~/Papers/references.bib")
              org-ref-pdf-directory "~/Papers/" org-ref-bibliography-notes "~/Papers/notes.org" org-latex-to-pdf-process
              '("latexmk -pdf %f")
              bibtex-completion-bibliography "~/Papers/references.bib" bibtex-completion-library-path "~/Papers" bibtex-completion-notes-path "~/Papers/notes.org" bibtex-dialect 'biblatex)
      markdown restructuredtext sphinx ess csv ipython-notebook themes-megapack theming colors)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p ("#+BEGIN_NOTES\n?\n#+END_NOTES"))
  org-mks((("n" ("#+BEGIN_NOTES\n?\n#+END_NOTES") "") ("a" "export ascii" "") ("c" "center" "") ("C" "comment" "") ("e" "example" "") ("E" "export" "") ("h" "export html" "") ("l" "export latex" "") ("q" "quote" "") ("s" "src" "") ("v" "verse" "") ("\011" "Press TAB, RET or SPC to write block name" "")) "Select a key\n============" "Key: ")
  org--insert-structure-template-mks()
  byte-code("\300 \211:\205(\0\211@\211\301\232\203\025\0\302\303!\202&\0\001A\211:\205$\0\211@\211\211\262\001\262\001\262\001\262\001\262\001C\207" [org--insert-structure-template-mks "\011" read-string "Structure type: "] 6)
  call-interactively(org-insert-structure-template nil nil)
  command-execute(org-insert-structure-template)
```

**Comment by tko** [comment]
Looks duplicate of #11798
