### ISSUE TITLE
No way to disable `rainbow-mode`?

### ISSUE THREAD

**Issue by edburyenegren-okta** [syl20bnr/spacemacs#12020]
<img width="225" alt="screenshot 2019-02-27 12 15 20" src="https://user-images.githubusercontent.com/36284167/53519981-64f1a780-3a89-11e9-8100-fef1f621b06b.png">

I am unable to disabled `rainbow-mode`. The develop docs suggest:

>To enable, you must manually toggle it on and off on a per-buffer basis with: `SPC t C c`

This is incorrect on two counts:

1. `rainbow-mode` is automatically enabled in the `html` layer
2. `SPC t C c` is an undefined command; similarly `rainbow-mode` is not available via `M-x`

**Comment by Compro-Prasad** [comment]
@edburyenegren-okta Which mode is the buffer in? `css-mode` or `web-mode` or `html-mode`?

**Comment by edburyenegren-okta** [comment]
@Compro-Prasad `scss-mode` which is a child of `css-mode` (based on `C-h m`)

**Comment by Compro-Prasad** [comment]
Setting `css-fontify-colors` to `nil` helped.

**Comment by edburyenegren-okta** [comment]
Solved my issue! Thanks @Compro-Prasad. Is this already in the docs somewhere?

**Comment by Compro-Prasad** [comment]
Emacs is self documenting and provides lot of introspecting capabilities. The common way is to use `M-x describe-variable` bound to `SPC h d v` and `C-h v`. Another way is to use `M-x customize` and search for `css color`. Actually there are a lot more ways.
