### ISSUE TITLE
magit-gitflow is overriding/contradicting magit worktree command

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#12027]
#### Description :octocat:
magit-gitflow is overriding/contradicting magit worktree command; the popup menu says `%` is one thing (Worktree) but using it shows something completely different (magit-gitflow)

#### Reproduction guide :beetle:
- Start Emacs
- go to git project, open magit status (`SPC g s`)
- press `?` for help popup
- press `%` for `Worktree`

*Observed behaviour:* :eyes: :broken_heart:

Popup shows `% Worktree`
Pressing `%` shows commands for magit-gitflow

*Expected behaviour:* :heart: :smile:

Either the popup shows `% Worktree` _and_ pressing `%` shows worktree commands (and magit-gitflow is on different prefix)

OR

Popup shows `% Flow` (or similar) and pressing `%` shows magit-gitflow commands

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp multiple-cursors treemacs
      (auto-completion :variables auto-completion-enable-help-tooltip t)
      (c-c++ :variables c-c++-enable-clang-support t)
      (colors :variables colors-colorize-identifiers 'variables)
      dash docker
      (finance :variables ledger-default-date-format "%Y-%m-%d")
      git graphviz html imenu-list
      (javascript :variables javascript-fmt-tool 'prettier)
      (json :variables json-fmt-tool 'prettier)
      lsp lua
      (markdown :variables markdown-command "markdown-tko")
      meson
      (osx :variables osx-use-option-as-meta nil osx-right-option-as 'meta osx-right-command-as 'super)
      python react restclient
      (rust :variables rust-backend 'lsp rust-format-on-save t)
      semantic shell-scripts sql syntax-checking
      (typescript :variables typescript-fmt-tool 'prettier)
      (version-control :variables version-control-diff-tool 'git-gutter+)
      yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

**Comment by tihuang02** [comment]
I am seeing the same issue? Any suggested workaround to disable git-workflow since I don't use/need it. But I'd like '%' bound to worktree as documented.

**Comment by mexisme** [comment]
If I can't easily change the key-binding, I'd really like to be able to disable git-flow altogether.

**Comment by nixmaniack** [comment]
@mexisme You can add `magit-gitflow` to `dotspacemacs-excluded-packages` in your `~/.spacemacs` file.

But I think we shouldn't shadow magit core binding. I would prefer following option:

> Either the popup shows `% Worktree` _and_ pressing `%` shows worktree commands (and magit-gitflow is on different prefix)

**Comment by tshu-w** [comment]
Perhaps this is a conflict caused by evil-magit (now evil-collections) and should be reported upstream

**Comment by lebensterben** [comment]
@tshu-w 
https://github.com/syl20bnr/spacemacs/blob/aa0c0301e2dc5751690518372ec4c0329f60420f/layers/%2Bsource-control/git/packages.el#L289

It's caused by a bad config.
I've known this four about 2 years and I've a PR to fix this. It's just never completed..

**Comment by tshu-w** [comment]
@lebensterben 😂

**Comment by duianto** [comment]
Pending PR:
git: Added magit-todos, improved docs, etc. #14554

**Comment by lebensterben** [comment]
@duianto 
That's a minimal version of a larger PR (not submitted) or another (almost) rewrite of git layer ....... So it doesn't fix the magit-gitflow issue.

Well I can fix the % problem in the pending PR if you want.

**Comment by duianto** [comment]
>I've known this for about 2 years and I've a PR to fix this. It's just never completed..

Ok, I misunderstood. I thought that you meant that you've had a PR open for 2 years, that fixes this.

When I searched for a pending magit-gitflow PR, I only found this one:
git: Added magit-todos, improved docs, etc. #14554

which makes some magit-gitflow related changes.

>So it doesn't fix the magit-gitflow issue.

👍 

---

>Well I can fix the % problem in the pending PR if you want.

It's probably best to keep them separate.

**Comment by lebensterben** [comment]
Someone please ping me so this thread will be in my inbox.

**Comment by duianto** [comment]
@lebensterben 📥
