### ISSUE TITLE
Finishing a fixup commit in magit does not support evil/vim-like keys

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#12025]
#### Description :octocat:
Finishing a fixup commit in magit does not support evil/vim-like keys `, ,` or `, k` that work in other similar contexts, instead one must use `C-c C-c` and `C-c C-k`.

#### Reproduction guide :beetle:
- Start Emacs
- Stage a commit in git repo
- Make a fixup commit (`c f`)
- Press `q` to exit diff mode
- Select a commit to fixup into and press `, ,` to commit or `, k` to cancel

*Observed behaviour:* :eyes: :broken_heart:

Instructions in modeline after `c f` and top of buffer after `q`:
`Type C-c C-c on a commit to fixup into it, or C-c C-k to abort`

Pressing `,` gives error `Can't find )`

*Expected behaviour:* :heart: :smile:

Instructions in modeline after `c f`  and top of buffer after `q`:
`Type , c on a commit to fixup into it, or , k to abort`

Pressing `, ,` commits the fixup, `, k` cancels it.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp multiple-cursors treemacs
      (auto-completion :variables auto-completion-enable-help-tooltip t)
      colors csv dash docker git
      (go :variables go-format-before-save t gofmt-command "goimports")
      html imenu-list javascript lsp markdown nginx
      (org :variables org-enable-reveal-js-support t)
      (osx :variables osx-use-option-as-meta nil)
      puppet python react restclient shell-scripts syntax-checking typescript version-control yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

**Comment by duianto** [comment]
This seems to be where the `,,`, `,k` bindings are defined:
https://github.com/syl20bnr/spacemacs/blob/4b195ddfc9228256361e0b264fe974aa86ed51a8/layers/%2Bsource-control/git/packages.el#L198-L207

**Comment by yuhan0** [comment]
There is an open PR #11856 that adds these bindings, tagged for the next bugfix release 0.300.1 whenever that may be.

**Comment by duianto** [comment]
The PR:
Add accept/cancel leader bindings to Forge and Magit log modes #11856
is now on the develop branch.
