### ISSUE TITLE
Add support for pytest --last-failed argument

### ISSUE THREAD

**Issue by Cadair** [syl20bnr/spacemacs#12023]
It would be a really useful feature to have a shortcut in the python layer to run pytest with `--last-failed` to rerun the tests that failed on the last run.

**Comment by jluttine** [comment]
I noticed that `, t l` is bound to `python-test-last` but I get an error `This test function is not available with ´pytest´ runner.`

Is this the right keybinding or what is `python-test-last` meant to do? Or should there be a new keybinding for running last failed?

**Comment by jluttine** [comment]
Oh, `python-test-last` should re-run the last test command. So, we need a new shortcut for running last failed..

**Comment by jluttine** [comment]
I opened a feature request in the pytest emacs package that spacemacs uses: https://github.com/ionrock/pytest-el/issues/29

Once that package supports it, then we can add keybindings on spacemacs side.

**Comment by jluttine** [comment]
I made a pull request: https://github.com/syl20bnr/spacemacs/pull/12902

It depends on the upstream pull request too.
