### ISSUE TITLE
Tags file paths

### ISSUE THREAD

**Issue by gleb-dianov** [syl20bnr/spacemacs#12026]
Is there a way to see file paths in the tags mini buffer?

![2019-03-01-115329_375x263_scrot](https://user-images.githubusercontent.com/39841057/53636636-d57afe80-3c18-11e9-8c3b-ba211513e586.png)

**Comment by antonalekseev** [comment]
`(setq helm-xref-candidate-formatting-function 'helm-xref-format-candidate-long)`?

**Comment by gleb-dianov** [comment]
Thank you @antonalekseev
