### ISSUE TITLE
<scroll> is undefined

### ISSUE THREAD

**Issue by ticolensic** [syl20bnr/spacemacs#12021]
#### Description :octocat:
I have a pretty fresh emacs/spacemacs install (well, it occured a couple of times over many installations). After some time this message in status bar keeps reoccuring:
```<scroll> is undefined```
It sort of gets in the way when I start a key sequence (`SPC-<any-key>-<any-key>`..) and is bugging me all around. See logs from *Messages* below. I _guess_ it's not in spacemacs itself, probably its in Evil or somewhere. Please help me debug this problem, and I'll go to the appropriate ticket tracker.
#### Reproduction guide :beetle:
- Start Emacs
- ???
- At some point it just starts happening

*Observed behaviour:* :eyes: :broken_heart:
<scroll> is undefined [21 times]
Mark set
<scroll> is undefined [4 times]
scroll-down-command: Beginning of buffer
<scroll> is undefined
scroll-down-command: Beginning of buffer
<scroll> is undefined [10 times]
Quit [2 times]
<scroll> is undefined [9 times]

*Expected behaviour:* :heart: :smile:
Well, I want it to stop!

(%LAST_KEYS%)

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion emacs-lisp git ansible markdown java python sql haskell
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     (spacemacs-ui-visual :package neotree))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by DanLanglois** [comment]
I note first, that 'Spacemacs branch: master' is updated  a year ago lastest commit. I am just getting oriented myself, and okay, this is the default branch, but you might check out 'develop' branch, 2574 commits ahead. Next, I see this: 'OS: windows-nt'. Just to be clearn, I am guessing what this even means -- named just Windows NT, eh? The NT version number is not now generally used for marketing purposes. And also, I wonder exactly how this works with emacs, as far as what offers simple and straightforward installation on Windows 7+? You need administrator account access? It occurs to me that it could ber relevant to ask if you have 64 bit Windows 10 or, like, emacs 32-bit. 

Leaving all that aside, If I had to guess from the messages I would say that it could be some mouse wheel action that is not defined. Actually, it occurs to me just now that for all I know, you have cygwin emacs under windows. But I digress. You say this: 

'After some time this message in status bar keeps reoccuring:
<scroll> is undefined'

Well, I wonder if you are using the mouse to scroll. I am also curious about the ScrollLock key. Heck, what does Scroll Lock do? Why is Scroll Lock used? These are not rhetorical questions, all I know is that it is sometimes abbreviated as ScLk, ScrLk, or Slk, and the Scroll Lock key is found on a computer keyboard, often located close to the pause key. I'm reaching, but from your query I wonderabout the possible existence of a minor mode that only toggles single variable, or I dunno. Fact is, I'm sure that if you install emacs on Windows you'll get errors, you must like this, you signed up for this. Just in case we are not on the same page about that. Summary here is to try the develop branch. I have to assume that you are prepared to muck about with switching branches, using git. My emphasis would be on the point that yes this is rather assuming that you have git installed, and are comfortable with all this kind of developer/hacker workflow, but if you aren't, then it's not for the end user to goof with installing emacs on windows anyways.

**Comment by ticolensic** [comment]
First of all, thank you for the response!

Ok, answering questions. Yes, this happens to be Windows 10. I am bound to this distribution, so there's no way around no matter how many people dread the damn thing :)
Mouse scroll doesn't seem do relate, as doesn't ScrLk (man, I'm on a laptop and even though I come from the times keyboards had no win-key but had a handy AT-XT switch, I sincerely have no idea how to switch Scroll Lock on on Lenovo :D), on the bright side I seem to have nailed it closer. 

This happens when I switch between windows with taskbar, alt-tab or just clicking on emacs. However, it doesn't happen with e.g. Firefox or Skype, but it does happen with WSL window and Cisco Jabber (I'm terribly sorry to bring up such software into this discussion, I'm a Linux guy, honestly, frankly). Amongst the output I provided, sometimes this turns up:
`<M-scroll> is undefined`
which could lead to mouse actions (triggered by switching windows even with keyboard).
I set the warning level (in scratch with eval-buffer), nothing happened, the messages keep coming. I tried setting it to debug, no new messages. Apparently it wouldn't help though, cause there is an event, and not seeing it in logs wouldn't mean it didn't happen. E.g.:
`SPC b <scroll> is undefined`
I was trying to switch buffers, but got interrupted. Annoying.

I'm happy to skim through the source code when I have time, please give me the direction, cause I'm sorta newbie in lisp.

**Comment by ticolensic** [comment]
So, to sum up. Some scroll event is sent to emacs window constantly after I switch to it from WSL window or Cisco Jabber, but not from Firefox. And I finally tested that it's not related to spacemacs, so I guess we can close the ticket. I'll try mailing lists.

(facepalm)

**Comment by Eli-Zaretskii** [comment]
It's not a scroll *event*, it's a keypress of the Scroll Lock key.

See the documentation of the variable `w32-scroll-lock-modifier`, which controls the effect of that key.

**Comment by ticolensic** [comment]
IDK who causes it (I'm thinking Kaspersky), I don't even have this key on the keyboard, but setting this variable to 't' seems to solve the problem. Thanks!

**Comment by ticolensic** [comment]
It turns out that scroll lock is on in some applications and off in others. Again, I don't have this key on my keyboard :)

**Comment by ticolensic** [comment]
And the followup.
To switch keyboard layout, I use this program: http://flydom.ru/capslang/
It turns out, I used a version with Scroll lock indication.
