### ISSUE TITLE
Treemacs causing Emacs to use 100% CPU

### ISSUE THREAD

**Issue by zentetsukenz** [syl20bnr/spacemacs#12031]
#### Description :octocat:
Treemacs causing Emacs process to use 100% CPU.

#### Reproduction guide :beetle:
- Start Emacs
- Open any file within the projectile
- Open Treemacs with `SPC p t`
- Switch cursor to window 1 while treemacs is open with `SPC 1`
- Notice that Emacs CPU usage is 100%

*Observed behaviour:* :eyes: :broken_heart:
The CPU usages of the Emacs process is 100% while treemacs is open and the cursor is not in treemacs. The issue does not happen after either I relocate the cursor to treemacs with `SPC 0` or close treemacs with `SPC p t`.

*Expected behaviour:* :heart: :smile:
The CPU usage is normal while treemacs is open and the cursor is not in treemacs.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion better-defaults docker emacs-lisp git go html ivy javascript osx python ruby rust shell-scripts version-control yaml elixir)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
There is no error. Only that the CPU usage is always 100%.

**Comment by zentetsukenz** [comment]
Add more information here.

The 100% CPU and the reproduce steps above only happen when treemacs follow mode is on.

**Comment by Alexander-Miller** [comment]
I have fixed leaks that can cause this in powerline and doom-modeline. Is the issue still present when these packages are updated (you may need to restart to properly reset the previous advice-based mechanism)?

**Comment by zentetsukenz** [comment]
The update fixes this issue. closing.

**Comment by spark-technology** [comment]
Still got the 100% cpu usage when in another workspace on i3.

**Comment by patata3000** [comment]
It's happening a bit less than before but as soon as I change the cursor's place in a buffer and I change workspace, I get 100% cpu usage. I come back to emacs' workspace everything is back to normal. I leave again emacs workspace without changing the cursor's place and I have normal usage. Really weird...

**Comment by Alexander-Miller** [comment]
I need to know where this is coming from. See https://github.com/Alexander-Miller/treemacs/issues/369#issuecomment-469351026

**Comment by patata3000** [comment]
I'm not proficient with elisp and spacemacs. Anyhow I'll try later what is in your linked comment. :)

**Comment by patata3000** [comment]
I think it's from python layer. I installed it and it started using cpu again when not on screen.
I'm using importmagic, flake8. I wish to try what is in your comment but it means I need to learn:
- what is a buffer with a lexical scope
- how to evaluate it
- Disable the tracing with (fset #'trace-follow-hook #'ignore) (where?)

I wouldn't mind a bit of help with that. Or maybe what I told you is enough. Usually a python buffer needs to be opened for the cpu to start working.

**Comment by Alexander-Miller** [comment]
> what is a buffer with a lexical scope

One where lexical-binding is t. You need to run `(setq-local lexical-binding t)` to enable it.

> how to evaluate it

Paste the code into some elisp buffer, move cursor behind the expression, press `, e e`.

> (fset #'trace-follow-hook #'ignore) (where?)

Same as above, paste wherever and evaluate. Or just restart emacs.

> Usually a python buffer needs to be opened for the cpu to start working.

I cannot reproduce this, neither with my own config, nor default spacemacs, neither anaconda, nor lsp backend. So I need you to do the digging. Another thing you can try when emacs gets stuck is to `kill -12 emacs-id` where emacs-id is found with `pgrep emacs`. That'll stop emacs and make it show a stack trace of whatever it's doing, but I doubt that will be precise enough, hence the targeted approach with the hook.

**Comment by patata3000** [comment]
Ok so I got this:
```
  backtrace()
  (progn ...)
  (if ...)
  trace-follow-hook()
  run-hooks(buffer-list-update-hook)
  kill-buffer(#<killed buffer>)
  #[nil ...]()
  format-spec("%I@%S" ...)
  (let* ...)
  (progn ...)
  (unwind-protect ...)
  (let ...)
  spacemacs/title-prepare("%I@%S")
  eval(...)
  redisplay_internal\ \(C\ function\)()
  recursive-edit()
  debug(error ...)
  scan-sexps(2 ...)
  forward-sexp(-1)
  #[0 ...]()
  apply(#[0 ...] ...)
  evil--preceding-sexp(#[0 ...])
  apply(evil--preceding-sexp ...)
  elisp--preceding-sexp()
  elisp--eval-last-sexp(nil)
  #[257 ...](nil)
  ad-Advice-eval-last-sexp(#[257 ...] ...)
  apply(ad-Advice-eval-last-sexp ...)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp ...)
  call-interactively(eval-last-sexp ...)
  command-execute(eval-last-sexp)
```
Btw I did ', e e' and I got : 'Scan error: "Containing expression ends prematurely", 1, 1'
I selected the code with V and ran ', e f' then it worked. I'm telling you this because if you know a quick fix for it, I'll take it :)

I didn't tell you but I'm in the develop branch.

**Comment by patata3000** [comment]
Hey what's happening with this issue? Should it be reopen?

**Comment by Alexander-Miller** [comment]
Sorry, I got distracted elsewhere.

> command-execute(eval-last-sexp)

Your backtrace is the result of calling this command. That's not what I need. You need to reproduce the situation where treemacs is part of the feedback loop that taxes your cpu, so I can understand what's calling what in that loop. That is why `n` must be large enough. Otherwise you'll produce so many backtraces emacs will hang completely.

Another thing you can try is start with a default config and treemacs and keep slowly adding your other layers to see what finally causes it.

**Comment by patata3000** [comment]
I'm pretty sure it's python layer. I added it as the first layer and it started eating up my cpu.

**Comment by Alexander-Miller** [comment]
I need more than a pretty sure. If you have a minimal dotspacemacs then push it to pastebin and I'll try it (I doubt it's just python since I use that layer as well). If that doesn't work I will need the info from the backtraces.

**Comment by ikselven** [comment]
@Alexander-Miller see #12387 for a way to reproduce this with a vanilla Spacemacs installation and the default configuration. A backtrace created with your code snippet is also included in that issue.
