### ISSUE TITLE
Documentation on notmuch using msmstp layer seems to have issues

### ISSUE THREAD

**Issue by vonpupp** [syl20bnr/spacemacs#12036]
Hi,

I wasn't sure if I opened a new issue or I should have added this to #2163. I decided to open a new one, I hope that is ok.

I am new to spacemacs (and emacs in general). I am trying to configure the notmuch layer as described on the documentation using `msmtp`. However when I try to send an email I get a prompt asking: "Outgoing SMTP mail server:".

I don't know why this happens since I am delegating the sending process to msmtp. Is this normal? How should I proceed?

Thank you very much.

**Comment by vonpupp** [comment]
I used the same data from msmtp and emacs created an `.authinfo` file with `machine... login... port... password...`.

The emails seems to go out fine, but I wonder why this happens and if msmtp is being used at all.

**Comment by jb55** [comment]
what's your `message-send-mail-function` set to? It should be:

`'message-send-mail-with-sendmail`

I think the default is `'message-smtpmail-send-it`

**Comment by jb55** [comment]
I also have ` '(message-sendmail-f-is-evil t)` set, can't remember if msmtp needed that...

**Comment by vonpupp** [comment]
Thank you, I will double check on that and post the results.

**Comment by jb55** [comment]
Let me know, and we can update the docs accordingly.

**Comment by vonpupp** [comment]
I had both lines, however my `'message-sendmail-f-is-evil` was set to nil instead of `t`. Now it seems to work. Thank you very much!
