### ISSUE TITLE
'Stuck' in magit window after choosing something with helm

### ISSUE THREAD

**Issue by actionshrimp** [syl20bnr/spacemacs#12034]
#### Description :octocat:
'Stuck' in magit window (can't close it with `C-g`) after picking an option via a helm popup - keymap seems to be broken. Can't even kill emacs with `C-x` `C-c` - have to `killall emacs`.

Not sure if this is an upstream magit issue, but it seems to be due to an interaction with helm so hoping someone here might have more of an idea of what's happening :-)

#### Reproduction guide :beetle:
- Start Emacs
- Run a command that uses helm so helm is loaded (e.g. `SPC p f`), then close it again
- Open magit status buffer
- Set upstream branch (`b`, then `u` inside the status buffer)
- Helm pops up over the magit window, select the branch from helm
- Now back in the magit window and unable to leave it as the keymap seems to be broken.

*Observed behaviour:* :eyes: :broken_heart:
Stuck in magit and unable to do anything else inside emacs (can't even kill emacs with C-c C-x). Have to `killall emacs`.

*Expected behaviour:* :heart: :smile:
Magit's keymap should kick in again properly, allowing you to exit the magit window.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((osx :variables osx-right-command-as 'meta)
 tmux my-evil auto-completion helm emacs-lisp rust treemacs git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (syntax-checking :variables syntax-checking-enable-tooltips nil)
 (version-control :variables version-control-diff-tool 'diff-hl)
 javascript
 (node :variables node-add-modules-path t)
 shell-scripts html sql
 (elm :variables elm-format-on-save t elm-sort-imports-on-save t)
 yaml ruby
 (python :variables python-backend 'anaconda)
 ocaml ipython-notebook docker markdown terraform my-clojure my-evil-lisp my-sql my-js-json my-haskell my-python lsp reason imandra xclipboard)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Confirmed.

I'm able to exit by first pressing: `C-x` which showed some more magit help keys, and pressing:
`C-z` or `C-q` closed the magit branches window.

**Caution:** When I tried other key bindings and pressed `C-c C-x C-x`. Now `C-x` doesn't show the help keys, and I haven't found another way to close it (yet 😄 ).

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
It seems to work without Spacemacs.

Start `emacs --quick`
- Initialize the Spacemacs elpa directory:
```
(setq package-user-dir "~/.emacs.d/elpa/26.1/develop/")
(package-initialize)
```
- Load Helm: `M-x helm-mode`
- Open the Spacemacs repository in Magit: `M-x magit-status` `~/.emacs.d`
- Open the branch popup: `b`
- Open a Helm buffer by setting the remote branch `u` (if it's set, otherwise unset it first), the helm buffer can be closed with `C-g`.

Now `C-g` closes the Magit branch popup.

Possibly because the Helm window doesn't open over the Magit branch popup. Here Helm uses the `magit: .emacs.d` window.

**Comment by duianto** [comment]
Commenting out:
https://github.com/syl20bnr/spacemacs/blob/4b195ddfc9228256361e0b264fe974aa86ed51a8/layers/%2Bcompletion/helm/packages.el#L71

Still shows the Helm buffer over the Magit branch popup, but when the Helm buffer is closed, then the Magit branch popup bindings work as expected.

**Comment by duianto** [comment]
The docstring for this function says that it deactivates transient maps:
https://github.com/syl20bnr/spacemacs/blob/4b195ddfc9228256361e0b264fe974aa86ed51a8/layers/%2Bcompletion/helm/funcs.el#L17-L20

**Comment by duianto** [comment]
Maybe the Magit transient map should be excluded? I'm not sure how to do that.

**Comment by syl20bnr** [comment]
Should be fixed in develop branch.

**Comment by duianto** [comment]
Confirmed, it's not getting stuck anymore. Thanks!

**Comment by actionshrimp** [comment]
Yep - all fixed, have switched back to helm from ivy and it's all solid now. Thanks v much for sorting.
