### ISSUE TITLE
Magit instant fixup fails and doesn't return to the magit status

### ISSUE THREAD

**Issue by DMRobertson** [syl20bnr/spacemacs#12039]
#### Description :octocat:
Magit instant fixup fails if previous buffer does not belong to the same project

#### Reproduction guide :beetle:
- Start Emacs
- `SPC w 1` so that we only have one active window
- Open a git-controlled file, then close all other buffers with `SPC b C-d`
- Open the magit status window with `M-x magit-status`
- Stage a change (`s`). Keep it simple so there won't be a conflict when we fixup.
- Apply an instant fixup (`c F`) to a previous commit. (`q` to quit the diff buffer, then `C-c C-c` to apply the fixup to the commit at point.)

*Observed behaviour:* :eyes: :broken_heart:
Instant fixup does not apply. I return to a buffer and the magit status window does not reappear. The minibuffer contains an error message: backtrace below. If I navigate to the magit status window again, the git repository status is unchanged.

*Expected behaviour:* :heart: :smile:
Instant fixup applies and I'm returned to the magit status buffer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql csv python html javascript html markdown helm git emacs-lisp ranger
     (c-c++ :variables c-c++-enable-rtags-support 'no-completion c-c++-enable-c++11 t)
     shell yaml python javascript neotree shell-scripts spell-checking version-control search-engine auto-completion org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2
- magit version 20190305.1106 from ELPA (I think?)

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  (or (file-exists-p (magit-git-dir "rebase-merge")) (file-exists-p (magit-git-dir "rebase-apply/onto")))
  magit-rebase-in-progress-p()
  (and (magit-rebase-in-progress-p) (not (magit-anything-unstaged-p)) (y-or-n-p "Nothing staged.  Continue in-progress rebase? "))
  (cond ((or (magit-anything-staged-p) (and (magit-anything-unstaged-p) (member "--all" args)) (and (not strict) (or (member "--amend" args) (member "--allow-empty" args)))) (or args (list "--"))) ((and (magit-rebase-in-progress-p) (not (magit-anything-unstaged-p)) (y-or-n-p "Nothing staged.  Continue in-progress rebase? ")) (setq this-command 'magit-rebase-continue) (magit-run-git-sequencer "rebase" "--continue") nil) ((and (file-exists-p (magit-git-dir "MERGE_MSG")) (not (magit-anything-unstaged-p))) (or args (list "--"))) ((not (magit-anything-unstaged-p)) (user-error "Nothing staged (or unstaged)")) (magit-commit-ask-to-stage (if (eq magit-commit-ask-to-stage 'verbose) (progn (magit-diff-unstaged))) (prog1 (if (y-or-n-p "Nothing staged.  Stage and commit all unstaged changes? ") (progn (magit-run-git "add" "-u" ".") (or args (list "--")))) (if (and (eq magit-commit-ask-to-stage 'verbose) (derived-mode-p 'magit-diff-mode)) (progn (magit-mode-bury-buffer))))) (t (user-error "Nothing staged")))
  magit-commit-assert(("--") t)
  (and t (magit-commit-assert args t))
  (let* ((args (and t (magit-commit-assert args t)))) (if args (progn (if commit (progn (if (and rebase (not (magit-rev-ancestor-p commit "HEAD"))) (progn (let* ((val (read-char-choice (concat (format "%s isn't an ancestor of HEAD.  " commit) "[c]reate without rebasing, [s]elect other, [a]bort ") '(99 115 97)))) (cond ((eq val 99) (setq rebase nil)) ((eq val 115) (setq commit nil)) ((eq val 97) (user-error "Quit")) (t nil))))))) (if commit (progn (setq commit (magit-rebase-interactive-assert commit t)))) (if (and commit (or confirmed (not (or rebase current-prefix-arg magit-commit-squash-confirm)))) (let ((magit-commit-show-diff nil)) (setq args (cons (concat option "=" commit) args)) (if edit nil (setq args (cons "--no-edit" args))) (if rebase (let ((magit-process-popup-time -1) (shell-file-name (if (and (eq system-type 'windows-nt) (not magit-cygwin-mount-points)) "cmdproxy" shell-file-name))) (let ((with-editor--envvar magit-with-editor-envvar) (process-environment process-environment)) (with-editor--setup) (magit-call-git "commit" "--no-gpg-sign" (-remove-first (apply-partially (function string-match-p) "\\`--gpg-sign=") args)))) (magit-run-git-with-editor "commit" args)) t) (magit-log-select (function (lambda (commit) (if (and (magit-commit-squash-internal option commit args rebase edit t) rebase) (progn (magit-commit-amend-assert commit) (magit-rebase-interactive-1 commit (list "--autosquash" "--autostash" "--keep-empty") "" "true" nil t))))) (format "Type %%p on a commit to %s into it," (substring option 2)) nil nil nil commit) (if magit-commit-show-diff (progn (let ((magit-display-buffer-noselect t)) (apply (function magit-diff-staged) nil (magit-diff-arguments))))))) nil))
  magit-commit-squash-internal("--fixup" "33f2bcfa590" ("--") t nil t)
  (and (magit-commit-squash-internal option commit args rebase edit t) rebase)
  (if (and (magit-commit-squash-internal option commit args rebase edit t) rebase) (progn (magit-commit-amend-assert commit) (magit-rebase-interactive-1 commit (list "--autosquash" "--autostash" "--keep-empty") "" "true" nil t)))
  (closure ((args "--") (confirmed) (edit) (rebase . t) (args) (commit . #("33f2bcfa590" 0 1 (ws-butler-chg delete))) (option . "--fixup") t) (commit) (if (and (magit-commit-squash-internal option commit args rebase edit t) rebase) (progn (magit-commit-amend-assert commit) (magit-rebase-interactive-1 commit (list "--autosquash" "--autostash" "--keep-empty") "" "true" nil t))))("33f2bcfa590")
  funcall((closure ((args "--") (confirmed) (edit) (rebase . t) (args) (commit . #("33f2bcfa590" 0 1 (ws-butler-chg delete))) (option . "--fixup") t) (commit) (if (and (magit-commit-squash-internal option commit args rebase edit t) rebase) (progn (magit-commit-amend-assert commit) (magit-rebase-interactive-1 commit (list "--autosquash" "--autostash" "--keep-empty") "" "true" nil t)))) "33f2bcfa590")
  (let ((fun magit-log-select-pick-function) (rev (magit-commit-at-point))) (magit-mode-bury-buffer 'kill) (funcall fun rev))
  magit-log-select-pick()
  funcall-interactively(magit-log-select-pick)
  call-interactively(magit-log-select-pick nil nil)
  command-execute(magit-log-select-pick)

```

**Comment by DMRobertson** [comment]
A little more information:

- `(magit-git-dir)` correctly evaluates to the repository's .git folder when I evaluate it at the "Type C-c C-c on a commit to fixup" screen.
- At the same screen,`(file-exists-p (magit-git-dir "rebase-merge"))` is nil, and so too is `(file-exists-p (magit-git-dir "rebase-apply/onto"))`
- At the debugger screen, `(magit-git-dir)` is nil. But perhaps this makes sense, since the \*Backtrace\* buffer isn't in a projectile project, and I think magit uses the current project to determine the git directory?

**Comment by duianto** [comment]
The reproduction steps are working as expected for me.

### Windows 10 Version 1803
Magit 20190306.413, Git 2.20.1.windows.1, Emacs 26.1, windows-nt
from both gui and Powershell.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

### Ubuntu 18.04.2 (virtualbox guest with win 10 as host)

Magit 20190306.413, Git 2.17.1, Emacs 27.0.50, gnu/linux
from both gui and terminal.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP


### Also tested without Spacemacs in both Windows and Ubuntu
- `emacs --quick`
- package initialize Spacemacs elpa directory
```
(setq package-user-dir "~/.emacs.d/elpa/26.1/develop/")
(package-initialize)
```
