### ISSUE TITLE
Is it possible to override .spacemacs by project?

### ISSUE THREAD

**Issue by lh-hoon** [syl20bnr/spacemacs#12046]
I love to use many languages across the projects.
That makes my editor  too heavy.
If I can define my dotspacemacs by project(git root directory) to override ~/dotspacemacs, 
It would be useful.

### I want...
[node_project]
// load packages related node
[golang_project]
// load packages related golangs

**Comment by ryanprior** [comment]
Spacemacs already employs lazy-loading, so modes and libraries that aren't being used should not make your editor heavier. If you find that certain heavy dependencies are being loaded even when they aren't being used, there might be a problem with the lazy-loading and you could open an issue about that.

### To specifically answer your question...

You might be able to get some of what you're describing using `.dir-locals.el`: https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html

If you eval a `use-package` in a directory-local config, then you would be able to move that out of your .spacemacs.

**Comment by smile13241324** [comment]
@lh-hoon well are you sure that all is ok in your dotfile? I also have a pretty big config supporting lots of languages and with lazy loading applied spacemacs requires 20s for my entire config.

`621 packages loaded in 20.413s (e:525 r:6 l:24 b:66)
(0.542s spent in your user-config)`

When your config requires more time you should check what you are doing in your `dotspacemacs/user-config`.
