### ISSUE TITLE
Scheme layer with Chicken Scheme 5 doesn't work when follow the docs

### ISSUE THREAD

**Issue by Liverm0r** [syl20bnr/spacemacs#12044]
**Problem**:

I add scheme layer following this [docs](http://spacemacs.org/layers/+lang/scheme/README.html).
I can't perform this: 
```bash
cd `csi -p '(chicken-home)'`
```
First problem is that Chicken Scheme 5 doesn't have `csi`, it's now `chicken-csi`. So you should probably change the docs.

```bash
cd `chicken-csi -p '(chicken-home)'`
```
Second, when I run it with `chicken-csi`, I got:
`Error: unbound variable: chicken-home`. Here I don't know what to do :(

When I try to launch a REPL from the .scm file, which contains some code with Chicken like
`(import (chicken random))`, I get 

> Unable to start REPL:
> Searching for program: No such file or directory, csi

However when I start a REPL from the file without Chicken-mention, REPL works fine.

There is also a question on [stackoverflow](https://stackoverflow.com/questions/54205192/chicken-scheme-error-unbound-variable-chicken-home)

**My system Info:**
> - OS: gnu/linux manjaro
> - Emacs: 26.1
> - Spacemacs: 0.200.13
> - Spacemacs branch: master (rev. c7a103a77)
> - Graphic display: t
> - Distribution: spacemacs
> - Editing style: vim
> - Completion: helm
> - Layers:
> ```elisp
> (shell-scripts vimscript search-engine fzf scheme
>                (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
>                (clojure :variables clojure-enable-clj-refactor t)
>                (git :variables git-magit-status-fullscreen t git-enable-github-support t git-gutter-use-fringe t)
>                evil-cleverparens markdown org syntax-checking
>                (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
>                helm emacs-lisp
>                (shell :variables shell-default-shell 'shell shell-default-position 'full shell-default-full-span 'nil)
>                spell-checking syntax-checking)
> ```
> - System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by gcentauri** [comment]
Problem 1:

It looks like there's a [package naming conflict](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/chicken&id=8b9a65eb88d899f7c9c78b56bba5bea5cdba534a) in the Open BSD

Problem 2:
Chicken 5 doesn't import `chicken-home` by default.  You can accomplish the same thing with:

`csi -b -e "(import (chicken platform))" -p "(chicken-home)"`

Problem 3:
Related to problem 1, you'll want to set the name of the `geiser-chicken-binary` to `chicken-csi` since that is what your system calls it.

```
geiser-chicken-binary is a variable defined in ‘geiser-chicken.el’.
Its value is "csi"

Documentation:
Name to use to call the Chicken executable when starting a REPL.
```

**Comment by Liverm0r** [comment]
@gcentauri thank you, everything works fine!
I added `(setq geiser-chicken-binary "chicken-csi")`  inside the `dotspacemacs/user-config`

**Comment by gcentauri** [comment]
@Liverm0r I made a PR #12045 to update the layer documentation.

**Comment by duianto** [comment]
The PR:
scheme: Update install docs for Chicken 5 changes #12045
has been cherry-picked into the develop branch.
