### ISSUE TITLE
Helm File Find Troubles

### ISSUE THREAD

**Issue by g00sed** [syl20bnr/spacemacs#12049]
#### Description :octocat:
When hitting return upon selcting a directory in helm (Space f f), a list of the directory's contents fill the frame, forcing out whatever buffer was there previously

#### Reproduction guide :beetle:
- Start Emacs
- Space f f
- select dir

*Observed behaviour:* :eyes: :broken_heart:
see above

*Expected behaviour:* :heart: :smile:
list directory's contents in helm buffer at bottom of screen

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(haskell lua lsp python
         (haskell :variables haskell-completion-backend 'ghci haskell-process-type 'stack-ghci)
         themes-megapack c-c++ imenu-list helm auto-completion emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
Hmm I think you misunderstood the keybindings for helm. Basically when you are in helm you can move into a directory by pressing `Tab` or `ctrl l` when you are using `vim bindings`. 

When you press `return` you start [`dired`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html) instead which is the emacs file explorer.

So I think there is nothing wrong here.

**Comment by g00sed** [comment]
Is there a way to override the default behavior?

**Comment by smile13241324** [comment]
Hmmm good question basically you can configure everything in emacs and spacemacs is not different. However I have never tried to change helm keybindings.

Basically I would run with something among `(define-key helm-<keymap> (kbd "YourKey") 'yourFunction)` as was used in the helm layer in your user config. For the right keymaps I would refer to the package documentation or to the `helm guide` or `helm wiki` in the `helm layer`.
