### ISSUE TITLE
avy.elc failed to provide feature 'avy'

### ISSUE THREAD

**Issue by FiloSpaTeam** [syl20bnr/spacemacs#12040]
#### Description :octocat:
Everytime i try to open treemacs i have this error:
```lisp
long-pattern.... avy.elc failed to provide feature 'avy'
```

#### Reproduction guide :beetle:
- Start Emacs
- press `[SPC]-p-t

*Observed behaviour:* :eyes: :broken_heart:
Nothing special

*Expected behaviour:* :heart: :smile:
Should open treemacs as usually

I'm using Parabola GNU/Linux with Emacs 26.1 and Spacemacs 0.300 develop branch.

**Comment by Alexander-Miller** [comment]
I guess this can happen when package.el or your internet screwed up and somehow downloaded an empty file. So try reinstalling avy.

**Comment by FiloSpaTeam** [comment]
Ok i'll try :+1:

**Comment by FiloSpaTeam** [comment]
YEAH! I had not thought about it. Thanks
