### ISSUE TITLE
How to remove or change major mode prefix

### ISSUE THREAD

**Issue by smallid** [syl20bnr/spacemacs#12055]
I have customized some of the org-mode key bindings, but am hitting an issue where which-key still displays the old prefix and I cannot find how to fix that. I would like to be able to rename or even remove prefixes defined in the package via my user configurations: is that possible, or is there some other method of doing this?

Note that this issue is only related to the displayed string in the which-key menu: I am able to re-bind the actual function call.

**Example:**
The default 'org' package defined the major mode prefix 'mb' as "babel" using `spacemacs/declare-prefix-for-mode 'org-mode "mb" "babel)` (I'm slightly simplifying the actual code used). I am re-mapping that key combination to call `org-tree-to-indirect-buffer`. The key function remapping is happening but which-key still displays 'b -> babel'.

**User customization:**
 ```
 (spacemacs/set-leader-keys-for-major-mode 'org-mode
    "di" 'org-time-stamp-inactive
    "da" 'org-time-stamp
    "b" 'org-tree-to-indirect-buffer
    "n" 'org-narrow-to-subtree
    "w" 'widen)
```
I have tried using 'declare-prefix-for-mode' but that does not change the existing prefix.
```
  (spacemacs/declare-prefix-for-mode 'org-mode "mb" "org-tree-to-indirect-buffer")
```

**Comment by duianto** [comment]
This page might be helpful:
https://github.com/justbur/emacs-which-key#custom-string-replacement-options

**Comment by smallid** [comment]
Which key doesn't seem to have any functions which allow replacing a replacement: only various methods to append one to the various alists which it uses to implement them. Appending a replacement for one which already exists does not seem to work (which seems reasonable, as I'd guess which-key is searching for the first match in its lists).

**Comment by duianto** [comment]
This variable `which-key-allow-multiple-replacements` might solve your issue, it's docstring says:
>  "Allow a key binding to match and be modified by multiple
elements in \`which-key-replacement-alist' if non-nil. When nil,
only the first match is used to perform replacements from
\`which-key-replacement-alist'."

source: https://github.com/justbur/emacs-which-key/blob/c87b0ce78213f922a725be1e0ae2dede1cf29516/which-key.el#L210

The Spacemacs `develop` branch sets it to `t` by default.
https://github.com/syl20bnr/spacemacs/blob/4b195ddfc9228256361e0b264fe974aa86ed51a8/layers/%2Bdistributions/spacemacs-bootstrap/packages.el#L312

**Comment by smallid** [comment]
Very interesting. Setting `which-key-allow-multiple-replacements` to nil seems to fix my problem.

In which-key-replacement-alist I see my entries being added at the top of the list, while babel is further down.
```
(org-mode
  (("\\`M-RET b\\'")
   nil . #93="org-tree-to-indirect-buffer")
<snip>
  (("\\`M-RET b\\'")
   nil . #109="babel")
```
I don't fully understand which-key's replacement mechanism, but based on the description of that setting the older entry further down the list would override the newer entry up top.

@syl20bnr Do you have any info on why which-key-allow-multiple-replacements is set to t in spacemacs?  What is lost by setting it to nil?

**Comment by smallid** [comment]
Related issue describing usage of `which-key-allow-multiple-replacements`: justbur/emacs-which-key/issues/156

**Comment by smallid** [comment]
I haven't found any problems with `(setq which-key-allow-multiple-replacements nil)`. I'm still not sure why that variable was set, but I am going to close this issue.

My code to override a major mode key that was previously set as a prefix:
```
  (setq which-key-allow-multiple-replacements nil)
  (spacemacs/declare-prefix-for-mode 'org-mode "mb" "org-tree-to-indirect-buffer")
  (spacemacs/set-leader-keys-for-major-mode 'org-mode "b" 'org-tree-to-indirect-buffer)
```
