### ISSUE TITLE
org tables in markdown no longer behave correctly

### ISSUE THREAD

**Issue by AveryLychee** [syl20bnr/spacemacs#12059]
#### Description :octocat:
Using org mode table shortcuts in markdown mode results in numerous errors and confusing consequences, frequently the error is "Marker does not point anywhere", and occasionally inserting text into a table causes emacs to get stuck in the insert state (no evil keybindings work and the error `evil-first-non-blank: parse-sexp-propertize-function did not move syntax-propertize--doneError during redisplay: (internal--syntax-propertize 208781) signaled (error "Marker does not point anywhere")` appears) . Possibly related to the function "org-table-with-shrunk-field" being called, when it does not exist.

This error occurs with a fresh install of spacemacs.
This error did not occur until very recently.

#### Reproduction guide :beetle:
- Start Emacs
- Open a markdown file with some tables
- Try pressing tab on the start of the table
- Try inserting text into the table
- (Note that this issue is very flakey and does not always come up)

*Observed behaviour:* :eyes: :broken_heart:
Occasionally it behaves as normal. Sometimes, pressing tab doesn't advance the cursor to the next column. Sometimes, emacs gets stuck in the insert state and evil seems to no longer work.

*Expected behaviour:* :heart: :smile:
Tabbing through the table should work as it does in org mode. Entering insert mode in a table should insert text into the table and allow you to exit.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(yaml idris haskell html shell-scripts markdown nixos ivy auto-completion emacs-lisp pdf-tools themes-megapack syntax-checking imenu-list)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (error "Marker does not point anywhere")
  syntax-ppss-flush-cache(205519)
  syntax-propertize(208861)
  font-lock-fontify-syntactically-region(#<marker at 205549 in audio-guide.md> 208861 nil)
  font-lock-default-fontify-region(#<marker at 205549 in audio-guide.md> 208861 nil)
  font-lock-fontify-region(#<marker at 205549 in audio-guide.md> 208861)
  #f(compiled-function (fun) #<bytecode 0x569b0d>)(font-lock-fontify-region)
  run-hook-wrapped(#f(compiled-function (fun) #<bytecode 0x569b0d>) font-lock-fontify-region)
  jit-lock--run-functions(#<marker at 205549 in audio-guide.md> 208861)
  jit-lock-fontify-now(#<marker at 205549 in audio-guide.md> #<marker (moves after insertion) at 208861 in audio-guide.md>)
  org-font-lock-ensure(#<marker at 205549 in audio-guide.md> #<marker (moves after insertion) at 208861 in audio-guide.md>)
  org-table--shrink-columns(nil #<marker at 205549 in audio-guide.md> #<marker (moves after insertion) at 208861 in audio-guide.md>)
  #f(compiled-function () #<bytecode 0x2b71515>)()
  org-table-insert-row(below)
  org-table-next-field()
  orgtbl-tab(nil)
  funcall-interactively(orgtbl-tab nil)
  call-interactively(orgtbl-tab)
  (if (org-at-table-p) (call-interactively 'orgtbl-tab) (let (orgtbl-mode) (call-interactively (or (key-binding [(tab)]) (key-binding "\011") 'orgtbl-error))))
  orgtbl-hijacker-command-102(1)
  funcall-interactively(orgtbl-hijacker-command-102 1)
  call-interactively(orgtbl-hijacker-command-102 nil nil)
  command-execute(orgtbl-hijacker-command-102)
```

**Comment by zetok** [comment]
I've also run into this issue. The issue started happening after I've updated packages. The packages that were working correctly are from 2018 (or maybe even 2017, I'm not 100% sure how long I didn't update them).

>(Note that this issue is very flakey and does not always come up)

For me it's frequent enough to prevent me from actually working on a table. I've been trying to create a new table, perhaps that's a more reliable way to reproduce it.

### Workaround

Turning `orgtbl-mode` off prevents emacs from being stuck in insert mode.

**Comment by duianto** [comment]
@zetok Are you also on the `master` branch?

Could either of you try it on the `develop` branch, the issue might have been fixed.

I tried adding a simple table in a `markdown-mode` buffer:
```markdown
| a    | b    |
|------+------|
| asdf | zxcv |
| jkl; |      |
```
and pressing tab seems to work as expected, it jumps to the next cell, (previous cell with `S-TAB`), and adds a new row from the bottom right cell.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d6c8df3d0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm markdown multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by zetok** [comment]
>@zetok Are you also on the `master` branch?

Yeah.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm ansible emacs-lisp html javascript markdown nginx
      (org)
      python rust shell spell-checking syntax-checking)
```
- System configuration features: XPM JPEG PNG RSVG GLIB NOTIFY ACL GNUTLS FREETYPE M17N_FLT LIBOTF XFT ZLIB OLDXMENU X11 XDBE XIM THREADS LIBSYSTEMD


---

I've tried to make a reproducible test case, and surprisingly I couldn't reproduce the bug. I even tried with a copy of the same markdown file that I've tried to edit initially, and there were no problems.

Contents of the file were the same, and the only difference that I could note was that the file wasn't tracked by git.

This helped:

```sh
mkdir repo
cd repo
git init
touch test.md
git add test.md
```

The minimal test case where problems start:

1. Open `test.md`
2. Type just this: `| foo | bar`
3. Press `<tab>`, `<backspace>`, `---` (three dashes), `<tab>`
4. This already causes misbehaviour,  as the last `<tab>` fails to produce the `|----+----|` and instead creates another row and puts cursor in the first column of it.
5. Now you can just press `<shift> + <tab>` twice (or more), and notice how the cursor doesn't go back to the cell with the three dashes.

The above test case only works when:

- file in question is tracked by git
- `orgtbl-mode` is active

**Comment by duianto** [comment]
Great reproduction steps 👍 

It doesn't seem to matter if `test.md` is staged in a repository or not for me, I'm seeing the same result in both cases.

After step 3 it looks like this:
```
| foo | bar |
|---  |     |
|     |     |
```
`S-TAB` stops in the cell under `bar`.

It works if five dashes are typed, possibly because when `TAB` is pressed and the pipe symbols are aligned vertically, then the dashes will fill the cell.
```
| foo | bar |
|----- |     |
```

I haven't created a lot of tables so I'm not sure how it's supposed to work, but I seem to remember typing `|-|-|` (matching the number of vertical lines above), on the second line and pressing `TAB`, and it also works now:
```
| foo | bar |
|-|-|
```
resulting in:
```
| foo | bar |
|-----+-----|
|     |     |
```
I just tried it with a only a single dash in the second rows first column:
```
| foo | bar |
|-|     |
```
And it also seems to work with only two characters on the second line: `|-` `TAB`.

`orgtbl-mode` is enabled by default for me on the `develop` branch.
When it's disabled, then step 3 results in:
```
| foo | bar |
|-----|-----|
|     |     |
```

Note:
An observation. It seems like the spaces in the header can be left out:
```
|foo|bar
```
followed by `TAB` results in:
```
| foo | bar |
|     |     |
```
