### ISSUE TITLE
[javascript layer] Autocompletion using 'tern' doesn't autocomplete 'console.log'. Yes.

### ISSUE THREAD

**Issue by dennismayr** [syl20bnr/spacemacs#12054]
Very low priority issue.

I'm using `tern` as backend for `js2-mode`, and it works great for everything **except** for autocompleting `console.log`.

Whenever I type `cons`, instead of completing `console.log`, it offers:

* `const`
* `continue`

Anything but `console`. It guesses _anything else_ correctly.
I know it's a pretty stupid issue, I'm just having to type `console` a lot lately.

My dotfile includes the following `js2-mode` custom configurations:
```
'(js2-highlight-level 3)
'(js2-include-node-externs t)
'(js2-strict-missing-semi-warning nil)
```

Is there a catch in the mode configuration? :)
Not sure if a `js2-mode` issue or a Spacemacs layer thing.

OS: elementaryOS Juno / Ubuntu 18.04
Emacs: 26.1
Spacemacs branch: `develop`, current
`js2-mode-20190307.1649`

**Comment by thanhvg** [comment]
Try this workaround: type log, then press `M-/`. It comes from `yasnipet` which should be enabled by default. I don't use `tern` though, `lsp` is better imo

**Comment by dennismayr** [comment]
Hi @thanhvg, I tried your suggestion; it's a fine workaround.
However, you're right: `lsp` has turned out to be a better option than `tern`; the autocompletion is both accurate and 'complete-er' :)
