### ISSUE TITLE
Startup dired does not have helm completion

### ISSUE THREAD

**Issue by loysollivier** [syl20bnr/spacemacs#12064]
#### Description :octocat:
At spacemacs startup helm completion is not loaded for dired.
Once it has been loaded by something else. Dired uses helm too.

#### Reproduction guide :beetle:
- Start Emacs
- Enter `SPC a d`
- notice that completion is not using helm
- Enter something to load helm such as `M-x`
- Retry dired: `SPC a d`
- Notice that this time it uses heml

*Observed behaviour:* :eyes: :broken_heart:
No helm completion

*Expected behaviour:* :heart: :smile:
Helm completion

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc922)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu4e/" mu4e-use-maildirs-extension t)
 auto-completion better-defaults c-c++ cscope csv emacs-lisp git gnus helm html javascript markdown notmuch org pdf python shell
 (syntax-checking :variables syntax-checking-enable-tooltips nil syntax-checking-enable-by-default nil)
 version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
No backtrace needed, there's no lisp error.
```

**Comment by duianto** [comment]
This has been fixed by this commit: https://github.com/syl20bnr/spacemacs/commit/f8ed4739febd0becee64fcd60349a9771d926690

The PR with the discussion can be found here: 
Load helm before read-file-name and completing-read #11877

Dired calls `read-file-name`, and that commit made sure that helm loads before `read-file-name`.
