### ISSUE TITLE
Document that prefix argument does not work with helm-M-x

### ISSUE THREAD

**Issue by deech** [syl20bnr/spacemacs#1206]
SPC-u M-x does not work with helm-M-x, it fails with:
Error: Specifying a prefix arg before calling `helm-M-x`

This is because `helm-M-x` takes the universal argument in the normal way (C-u) after invocation: https://github.com/emacs-helm/helm/issues/696

It might be good to add a sentence or two to this section: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#universal-argument.

**Comment by syl20bnr** [comment]
Nice catch, there is some inconsistencies with `SPC-u` as the universal argument, I wonder if I should remove it tell people to use `SPC n ,` and the like.

**Comment by deech** [comment]
Maybe that's a good idea. The nice thing about that is that it doesn't break macros.

**Comment by sschuldenzucker** [comment]
+1 for documenting this.
This thread just saved me acting stupid while trying to execute `C-u M-x org-reload` to work around [this](http://comments.gmane.org/gmane.emacs.orgmode/99680) issue. For the record, it's `SPC : org-reload C-u RET` in spacemacs.

**Comment by linchen2chris** [comment]
first SPC-SPC then C-u before you run the command
