### ISSUE TITLE
Make double Esc clear last search highlights

### ISSUE THREAD

**Issue by srid** [syl20bnr/spacemacs#1207]
I am forced to search for a random junk string just to clear the vim search highlights. Can [Esc][Esc] be bound to do this? cf. http://stackoverflow.com/a/27207615/55246

**Comment by swaroopch** [comment]
@srid I think the Vim idiom is `:nohl`

**Comment by stormpat** [comment]
You can clear the searches with ```SPC s c```

**Comment by srid** [comment]
`SPC s c` was what I was looking for, thanks!

**Comment by shamil614** [comment]
i was searching for this too! thanks!
