### ISSUE TITLE
extend smerge transient-state with diff keybindings, can someone review my PR?

### ISSUE THREAD

**Issue by dwang20151005** [syl20bnr/spacemacs#12073]
Hey,

Apologies if I'm misunderstanding the workflow somehow.  I submitted PR #11855 a couple months ago extending the smerge transient-state in a hopefully uncontroversial way.  

The entire PR is 11 lines of diff.

Could someone please merge, or tell me what I need to fix, or tell me explicitly that the PR will not be accepted?

**Comment by duianto** [comment]
The PR:
Extend smerge transient-state with diff keybindings #11855
is now on the `develop` branch.
