### ISSUE TITLE
mu4e layer config forces use of hard newlines as default

### ISSUE THREAD

**Issue by orialb** [syl20bnr/spacemacs#12078]
Hi,

With the current mu4e config (on develop)  it is not possible to add a hook in the user-config which tells mu4e to disable hard newlines by default when composing a message. 
The reason I want to do this is that from my testing this seems to be important in order for my text emails to be properly displayed in other clients (e.g. Gmail, Fastmail).

What I try to do is add the following line to the user-config: 
```elisp
(add-hook 'mu4e-compose-mode-hook (lambda () (use-hard-newlines -1)))
```
however when I compose a message, hard newlines are still enabled by default.

The reason for this behavior is that the following hook is added in the layer configuration (in packages.el  file) :
```elisp
  (add-hook 'mu4e-compose-mode-hook
(lambda () (use-hard-newlines t 'guess)))
```
When I add my hook it is added as the first hook in the list and hence emacs first calls my hook (which disables hard newlines) and then calls the hook added by the layer config (which enables hard newlines). 
When I comment out the above two lines in the layer's config it works as expected (hard newlines disabled by default).

Is there a specific reason why this hook is added? Am I missing something?  
If not I think the use-hard-newlines hook should be removed from the layer config (or be made optional). 

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml rust markdown html python
      (julia :variables julia-mode-enable-lsp nil)
      helm auto-completion bibtex emacs-lisp git markdown
      (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu/mu4e" mu4e-use-maildirs-extension t)
      pandoc
      (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t)
      latex themes-megapack
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking pdf scheme)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by Alexander-Miller** [comment]
The commit in question is 060547608336824d2b23d5010e59e768c8d8f886, though it doesn't say way hard newlines are used.

> When I add my hook it is added as the first hook in the list and hence emacs first calls my hook 

`add-hook` has optional arguments to handle that.

**Comment by orialb** [comment]
> add-hook has optional arguments to handle that.

thanks for the tip. For some reason I just looked at the info page about adding hooks where this option is not mentioned, but didn't think to just do `describe-function` on `add-hook`.

 On the other hand the manual section about adding hooks has the following:
> For a normal hook, hook functions should be designed so that the
> order in which they are executed does not matter.  Any dependence
> on the order is asking for trouble

So I guess it's not best practice to have this as a workaround ? Maybe a better solution can be to add a variable to the mu4e layer  that will allow to enable/disable hard-newlines  when adding the layer?

**Comment by nixmaniack** [comment]
> Is there a specific reason why this hook is added? Am I missing something?
> If not I think the use-hard-newlines hook should be removed from the layer config (or be made optional).

I'm not sure why it's there, but I agree with you. It should be optional or at least be a proper function so that we can remove from the hook in our configuration.
