### ISSUE TITLE
some links in http://spacemacs.org/layers/LAYERS.html can not be visited

### ISSUE THREAD

**Issue by jasonzhouu** [syl20bnr/spacemacs#12079]
such as the links of `helm`
http://spacemacs.org/layers/+completion/helm/README.html

**Comment by duianto** [comment]
http://develop.spacemacs.org/layers/+completion/helm/README.html works on the develop branch: http://develop.spacemacs.org/

It will be fixed when the develop branch is merged into the master branch (I don't have any insight into when that is)
