### ISSUE TITLE
evil-escape-key-sequence has no effect/is broken

### ISSUE THREAD

**Issue by schlowm0** [syl20bnr/spacemacs#12088]
#### Description :octocat:
When I try to remap the escape sequence to "qw" according to the steps described in the documentation, it does not update the keymap. Meaning the re-mapping has no effect. I tried "qw", "ii", "jk" separate and together. Without any success.

#### Reproduction guide :beetle:
- Start Emacs
- add the following line to user-config
- (setq-default evil-escape-key-sequence "qw")
- SPC f e R
- open a file
- press "i" to go into insert-mode
- press "qw" to go into normal-mode

*Observed behaviour:* :eyes: :broken_heart:
When in insert-mode and typing "qw" I write qw but do not escape insert-mode.

*Expected behaviour:* :heart: :smile:
When pressing "qw" to switch to normal-mode

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195dd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp ranger git markdown multiple-cursors treemacs org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control python bibtex latex themes-megapack pdf-tools)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by schlowm0** [comment]
Here my user-config entry:
```
(defun dotspacemacs/user-config ()
    ;; "Configuration for user code:
    :: This function is called at the very end of Spacemacs startup, after layer
    ;; configuration.
    ;; Put your configuration code here, except for variables that should be set
    ;; before packages are loaded."
    ;; Set escape keybinding to "qw"
    (setq-default evil-escape-key-sequence "qw"))
```

**Comment by antonalekseev** [comment]
What does `SPC h d v` `evil-escape-key-sequence` `RET` tell you?

**Comment by schlowm0** [comment]
That it is set to `fd`. I now overwrote this with my desired `qw` sequence. However, I want to have multiple sequences such as `jk`, `ii` etc. But the command only let me set one key sequence.

**Comment by antonalekseev** [comment]
> But the command only let me set one key sequence.

That is true but there is workaround – https://github.com/syl20bnr/spacemacs/issues/5445#issuecomment-195123766.

**Comment by schlowm0** [comment]
But why does the `(setq-default evil-escape-key-sequence "qw")` command in my `.spacemacs` has no effect? 
Thanks for the work around I'll try it asap

**Comment by henriquenj** [comment]
@schlowm0 Check if your `.spacemacs` is indeed being called. Maybe you have a`.spacemacs.d/` directory laying around?

**Comment by schlowm0** [comment]
My layers are loaded, so I assume that my `.spacemacs` is being called properly.

@antonalekseev 
[#5445](https://github.com/syl20bnr/spacemacs/issues/5445#issuecomment-195123766) does not solve my problem, as the new key-bindings are not loaded.

**Comment by schlowm0** [comment]
So after restarting 2 times the work around proposed by @antonalekseev works like a charm. Issue "solved" and I am closing this issue

**Comment by zhaojio** [comment]
it not work:
 (defun dotspacemacs/user-config ()
  (setq-default evil-escape-key-sequence "jk")
)

it work:
(defun dotspacemacs/user-config ()
  (setq-default evil-escape-key-sequence "jk")
  (setq-default evil-escape-delay 0.3)
)
