### ISSUE TITLE
Spacemacs freezes when trying to indent invalid Python code

### ISSUE THREAD

**Issue by tsoernes** [syl20bnr/spacemacs#12080]
#### Description :octocat:
When pressing "tab" in invalid Python code, Emacs often, but not always, freeze and don't recover.
Example:

https://i.imgur.com/i9dDzYk.png

In that code, the function declaration (left window) is missing a colon `:`. Pressing `tab` caused emacs to freeze. Restarting emacs and trying the same again did not cause emacs to freeze, however I encounter this exact problem 3-4 times a week.  
#### Reproduction guide :beetle:
Don't know a surefire way.

*Observed behaviour:* :eyes: :broken_heart:
Emacs freezes

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html yaml javascript python rust latex bibtex theming auto-completion shell-scripts helm auto-completion better-defaults emacs-lisp git markdown org spell-checking syntax-checking shell lsp ipython-notebook
      (markdown :variables markdown-live-preview-engine 'vmd))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by adamczykm** [comment]
Got the same issue on OS X.

**Comment by duianto** [comment]
@adamczykm Could you post your system info, press `SPC h d s` to copy it to your clipboard.

And do you have some reproduction steps?
