### ISSUE TITLE
Add binding for EOF (^D) in term

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#1208]
Add a binding to send an EOF in term mode.

Pull request: https://github.com/syl20bnr/spacemacs/pull/1188

**Comment by syl20bnr** [comment]
Great, thank you. It should work only in `insert state`, is this the case ?

**Comment by darkfeline** [comment]
@syl20bnr I am using `term-bind-key-alist` that is currently being used for `term-send-tab` as well.  Unfortunately, it seems to bind for both insert and normal state.  I can change it to only work in insert state; should I go ahead and fix it for `term-send-tab` as well?

**Comment by syl20bnr** [comment]
Yes,  go ahead, thank you :-)

**Comment by darkfeline** [comment]
Fixed PR for EOF: https://github.com/syl20bnr/spacemacs/pull/1188
Made PR to make `term-send-tab` only work in insert mode: https://github.com/syl20bnr/spacemacs/pull/1271

**Comment by darkfeline** [comment]
Fixed.
