### ISSUE TITLE
Using autopep8

### ISSUE THREAD

**Issue by nguyenthanhvuh** [syl20bnr/spacemacs#12087]
I couldn't figure out how to enable `autopep8` to format Python code in spacemacs, I have it installed at `/usr/local/bin/autopep8` but not sure how invoke it automatically on save.  I don't have anything about `autopep8` in my `.spacemacs` file.

Currently, I was able format Python code  with `yapf` by having 
`(python :variables python-enable-yapf-format-on-save t)` in `dotspacemacs-configuration-layers`.

Is there some equivalent way to do that with `autopep8` ?  Thanks,

**Comment by tko** [comment]
I think autopep8 is not supported out of the box and that any command line formatter probably needs some amount of elisp around it to hook it up properly. There is #11770 adding "black" as formatter. I'd imagine something similar would be needed to integrate autopep8 into spacemacs proper.

Having said that, I see there's https://melpa.org/#/py-autopep8 which looks like it could be installed by adding `py-autopep8` to `dotspacemacs-additional-packages` and
```elisp
  (add-hook 'python-mode-hook 'py-autopep8-enable-on-save)
```
in `dotspacemacs/user-config`

**Comment by nguyenthanhvuh** [comment]
I think this works.  Thanks !

**Comment by beyondpie** [comment]
@nguyenthanhvuh  maybe you can close  this issue?
