### ISSUE TITLE
[meta] List of maintained forks of Spacemacs / merging resources

### ISSUE THREAD

**Issue by theckman** [syl20bnr/spacemacs#12082]
I wanted to reach out and see what the current state of the project is, in relation to merges in to the `develop` branch. There are a few outstanding PRs that would address critical issues with my setup, and I'm hoping to get them merged in so that I can make use of them without running on a fork.

Who is currently a resource available for merging? Could the doors be opened up to give some others the opportunity to review and merge changes that are low-risk and fix issues.

Separately, is there a list of maintained forks out there?

**Comment by dwang20151005** [comment]
I have an 11-line PR that's been sitting untouched for months now.  I thought I was just falling through the cracks, but is there something more general going on?

**Comment by Elidrake** [comment]
It appears that the project is currently in feature freeze, with a few more pull requests to merge before the release of .300: https://github.com/syl20bnr/spacemacs/milestone/7

**Comment by theckman** [comment]
I think we need to differentiate between features and bugfixes, as I'm specifically looking to get fixes in and not feature additions.

**Comment by dangom** [comment]
True. For a community-driven distribution, a 2 month window of non-responsiveness should not be acceptable. It'd be nice to have a large number of moderators, or indeed someone who is willing to maintain a bugfix fork while things don't move forward.
