### ISSUE TITLE
the keybind 'SPC i S c' for creating new snippet not work in develop branch.

### ISSUE THREAD

**Issue by hackrole** [syl20bnr/spacemacs#12089]
#### Description :octocat:
the key bind 'SPC i S c' to create new snippets not work. And it not report errors.
I check the key binding with 'SPC h d k'. It is still bind to aya-create.
It used to work good two weeks ago while I was in master branch.
I am in develop branch now.

#### Reproduction guide :beetle:
- Start Emacs
- open a file, let's say a python file
- select a few line of code. And press 'SPC i S c'

*Observed behaviour:* :eyes: :broken_heart:
- nothing happen, And I check the *Message* buffer, it has nothing about this.

*Expected behaviour:* :heart: :smile:
it used to split a new buffer for current file type to write snippets,
and I can use C-c C-c to save and load it.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195dd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible graphviz vimscript
         helm
         (ibuffer :variables ibuffer-group-buffers-by 'projects)
         nixos pass restclient sphinx restructuredtext
         (syntax-checking :variables syntax-checking-use-original-bitmaps t)
         (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior nil auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory "~/.spacemacs.d/snippets" auto-completion-enable-snippets-in-popup t spacemacs-default-company-backends
                          '(company-files company-capf)
                          require-final-newline nil auto-completion-enable-help-tooltip t)
         themes-megapack imenu-list
         (dash :variables helm-dash-browser-func 'eww)
         git github
         (plantuml :variables org-plantuml-jar-path "/usr/share/plantuml/plantuml.jar" plantuml-jar-path "/usr/share/plantuml/plantuml.jar")
         salt vimscript
         (markdown :variables markdown-live-preview-engine 'vmd)
         fasd org
         (ranger :variables ranger-show-literal t ranger-show-hidden t ranger-cleanup-on-disable t ranger-parent-header-func 'ranger-parent-header-line ranger-cleanup-eagerly t ranger-parent-depth 2 ranger-ignored-extensions
                 '("mvk" "iso" "mp4"))
         (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh")
         emacs-lisp
         (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save nil python-sort-imports-on-save t flycheck-flake8-maximum-complexity 8)
         ipython-notebook django scheme c-c++ erlang
         (go :variables go-tab-width 2 go-format-before-save t go-use-golangci-lint t go-backend 'lsp godoc-at-point-function 'godoc-gogetdoc go-fmt-command "goimports")
         haskell html
         (typescript :variables typescript-fmt-on-save t)
         javascript react lua plantuml elixir clojure scala ruby yaml rust typescript javascript sql docker pdf chrome
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by antonalekseev** [comment]
> select a few line of code. And press 'SPC i S c'

Could you please provide lines of code you tried to run specified command on?

**Comment by hackrole** [comment]
I try many times, on every lines of code, it behave the same. for example below
```python
import re
```

**Comment by antonalekseev** [comment]
@hackrole Ah, I see. The problem is that `SPC i S c` calls `aya-create` whichs stand for new `auto-yasnippet` and expects special syntax for on-demand snippets. See example of usage https://github.com/abo-abo/auto-yasnippet#a-basic-example. Current snippet can also be persisted with `SPC i S w`. What you are trying to achive is probably just to add regular yasnippet and this can be done with `yas-new-snippet`.

**Comment by hackrole** [comment]
@antonalekseev you are right. I used to create a key-bind `SPC <f7>` to `yas-new-snippet. but have mistake it with the `SPC i S c` after a few time not used it. I have change the key-binding to `SPC i S n`.
thank you very much.
