### ISSUE TITLE
How to close Spacemacs running as emacs client without bringing down the emacs daemon?

### ISSUE THREAD

**Issue by Qqwy** [syl20bnr/spacemacs#12095]
I am used to closing Spacemacs using `SPC q q`. However, recently I switched over to [using Emacs as a daemon](https://nobbz.gitlab.io/2018/02/16-emacs-as-a-service.html). This works fine, but when using `SPC q q` on a Spacemacs session (started with `emacsclient -c`) I end up inadvertantly killing the daemon (which will then restart but this obviously takes time and resources for the computer), rather than only closing the current `emacsclient` window.

 I was unable to find any Spacemacs (evil-mode) key binding that only closes emacsclient. Does it exist? If not, can we create one or maybe remap `SPC q q` to only closing the emacsclient if Spacemacs is running as a client?

**Comment by antonalekseev** [comment]
You need to kill current frame instead of killing emacs with `save-buffers-kill-emacs`. Binding should be like `(evil-leader/set-key "q q" 'spacemacs/frame-killer)`. You can use default binding `SPC q f` as well.

**Comment by ajholyoake** [comment]
Or `SPC F d`

**Comment by Qqwy** [comment]
Thank you!
