### ISSUE TITLE
Slow startup, one possible solution

### ISSUE THREAD

**Issue by Trapez** [syl20bnr/spacemacs#12098]
My arch based emacs has been very slow starting for the last year, over 20s. I tried all the suggested solutions, but none helped. Replacing `ttf-google-fonts.git` with `adobe-source-code-pro-fonts` reduced emacs startup time to about 5s. After reinstalling `ttf-google-fonts.git`, emacs startup time is still around 5s. So it was all due to a bad installation of one font package.

**Comment by abitrolly** [comment]
How did you profile that?

**Comment by Trapez** [comment]
I never manages to profile it, I discovered by luck.
