### ISSUE TITLE
dumb-jump-go fails with "invalid function helm-build-sync-source" error

### ISSUE THREAD

**Issue by orialb** [syl20bnr/spacemacs#12096]
#### Description :octocat:
dumb-jump-go fails with invalid-function helm-build-sync-source error

#### Reproduction guide :beetle:
- Start Emacs
- open a file in a git repo. 
- use dumb-jump-go on a function with more than one method defined, for example you can use the following minimal example in Julia (using dumb-jump-go on `f` in the last line) : 
```julia
function f(x::Int)
    return 1
end

function f(x::Float)
    return 2
end

x = f(2)
```

*Observed behaviour:* :eyes: :broken_heart:
get an error `invalid function helm-build-sync-source` 

*Expected behaviour:* :heart: :smile:
dumb-jump-go works

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml rust markdown html python
      (julia :variables julia-mode-enable-lsp nil)
      helm auto-completion bibtex emacs-lisp git markdown
      (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu/mu4e" mu4e-use-maildirs-extension t)
      pandoc
      (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t)
      latex themes-megapack
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking pdf scheme)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by orialb** [comment]
Some further info:
- looking at the dumb-jump issues I found this https://github.com/jacktasia/dumb-jump/issues/224, there it was recommended to reinstall helm. I did this but it didn't help.
- the user in https://github.com/jacktasia/dumb-jump/issues/224 was using doom-emacs, the author of doom-emacs commented what might be the problem in that case:

> After some testing, it appears that this is a load-order issue at compile-time. If dumb-jump is byte-compiled (i.e. installed) before helm, then helm-build-sync-source isn't expanded correctly. Loading helm before dumb-jump is byte-compiled fixes the issue.

I guess a similar thing might be happening with spacemacs, how can I make sure helm is loaded before dumb-jump is byte-compiled?

**Comment by thanhvg** [comment]
I had this issue last month. 

Because helm gets upgraded, you will need to recompile dumb-jump .

First start spacemacs, make sure helm is fully loaded (do a `spc spc` then `esc`, because spacemacs is lazy loading almost everything) let spacemacs run. Now go to dumb jump package location (for example ~/.emacs.d/elpa/26.1/develop/dumb-jump-20190221.1723/) and delete the compiled file `dumb-jump.elc`. Now  back to spacemacs a do a recompile `M-x`: `spacemacs/recompile-elpa`. Restart spacemacs.

**Comment by orialb** [comment]
that solved the issue. thanks so much!

**Comment by achikin** [comment]
@thanhvg I followed your instructions but `dumb-jump.elc` did not appear after `spacemacs/recompile-elpa`. Is there any way to recompile it explicitly?

**Comment by orialb** [comment]
You could also try to just remove the whole dumb-jump folder and restart spacemacs, it should reinstall it on startup.

**Comment by achikin** [comment]
@orialb @thanhvg I'm sorry. I didn't realize that I'm on the develop branch and should remove `elpa/26.3/develop/dumb-jump-*/` instead of `elpa/26.3/dumb-jump-*`
