### ISSUE TITLE
Not possible to set the cursor at the end of a pattern using /<pattern>/e

### ISSUE THREAD

**Issue by mtourne** [syl20bnr/spacemacs#12106]
#### Description :octocat:
Not possible to set the cursor at the end of a pattern using`/<pattern>/e`

#### Reproduction guide :beetle:

- Start Emacs
- in `*scratch*` type "will delete this, but not that"
- at the beginning of the line type `d/but not that`<return>
- only "will delete this," remains.
- undo. and now try:
- at the beginning of the line type `d/but not that/e`<return>

*Observed behaviour:* :eyes: :broken_heart:

pattern is not found

*Expected behaviour:* :heart: :smile:
the whole line should be deleted by with `/e` setting the cursor at the end of the pattern included. as described here : https://vi.stackexchange.com/questions/15746/delete-with-search-motion-in-normal-command

I fixed the issue following this: https://github.com/emacs-evil/evil/issues/1084 

and adding this to my .spacemacs seems to correct the behavior :
  `(evil-select-search-module 'evil-search-module 'evil-search)`

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql
 (go :variable go-tab-width 4)
 helm emacs-lisp git markdown version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by yuhan0** [comment]
Fixed in develop since 2 years ago: c7e47de9383f7556553c531ff27e7654b3cba3db

**Comment by mtourne** [comment]
Is master this far behind develop?

**Comment by haydenflinner** [comment]
Yes. It's not really mentioned in the manual anywhere that I remember but almost everyone I know uses develop
