### ISSUE TITLE
c-c++ layer iedit and lsp-mode conflict.

### ISSUE THREAD

**Issue by jstaursky** [syl20bnr/spacemacs#12109]
#### Description :octocat:
When I use iedit in c or c++ mode along with lsp-mode, the updating of the variable being renamed is inconsistent. For example I will type `Shift + #` with point on a variable called `foobar` and iedit acts normally to highlight every instance. Next I enter the editing mode with iedit to update all instances of `foobar` to `fuubar`, each instance of `foobar` starts getting updated as I type, but if I pause while typing and then type again, only the instance of `foobar` being updated is the one that point is on.  I am using the c-c++ layer and the lsp layer; this problem doesn't occur when the lsp layer is not present.

 with lsp-mode running causes iedit to only change 1 instance of a variable name being changed or to lagg and then update the other variables.
This is especially evident if you "type.. pause.. type" while using iedit.

#### Reproduction guide :beetle:
- Start Emacs
- have the following layers
  c-c++ and lsp
- open some c or c++ file
- M-x "lsp" (connects to clangd)
- use iedit to change some variable name.
- "type.. pause.. type"
- See variable being update inconsistently accross buffer.

*Observed behaviour:* :eyes: :broken_heart:
The variable that iedit updates across buffer is updated inconsistently.

*Expected behaviour:* :heart: :smile:
All instances should be updated in the same fashion.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript git
            (lsp :variables lsp-remap-xref-keybindings t lsp-ui-sideline-enable nil)
            gtags multiple-cursors pdf
            (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
            syntax-checking treemacs
            (version-control :variables version-control-diff-side 'left version-control-diff-tool 'diff-hl)
            (shell :variables shell-default-term-shell "/usr/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
            helm
            (auto-completion :disabled-for org :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete)
            c-c++ emacs-lisp markdown org python)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```
#### Other
I have ran `emacs --chdir="$HOME/Desktop/emacs-testing" -Q` where
`emacs-testing` contains only the necessary packages to run both iedit and lsp-mode + lsp-ui-mode.
Then evaluated
```
(add-to-list 'load-path "~/Desktop/emacs-testing/iedit")
(add-to-list 'load-path "~/Desktop/emacs-testing/lsp-mode")
(add-to-list 'load-path "~/Desktop/emacs-testing/dash")
(add-to-list 'load-path "~/Desktop/emacs-testing/f.el")
(add-to-list 'load-path "~/Desktop/emacs-testing/s.el")
(add-to-list 'load-path "~/Desktop/emacs-testing/ht.el")
(add-to-list 'load-path "~/Desktop/emacs-testing/spinner.el")
(add-to-list 'load-path "~/Desktop/emacs-testing/lsp-ui")
(add-to-list 'load-path "~/Desktop/emacs-testing/markdown-mode")
(require 'iedit)
(require 'lsp-mode)
(require 'lsp-ui)
```
Next I went to a c or c++ file to check for the same bug I was getting in spacemacs and it did not appear. So the package conflict is coming from somewhere else I believe.

**Comment by cormacc** [comment]
If you take a look at the instructions in the layer readme, you're supposed to set the layer variable `c-c++-backend` to one of `'ccls` or `'cquery` (the last update to the layer predates the inclusion of clangd as an lsp-mode default). That may not be at the root of your issue, but probably worth eliminating as a potential cause -- the default c-c++ layer setup includes some settings / bindings that conflict with lsp, which are disabled if the backend is set appropriately.

I'm using the ccls backend and use iedit search/replace without issues (evil mode keybindings).

**Comment by jstaursky** [comment]
Hmm wish that did the trick for me as well, but even after installing `ccls` and setting `(c-c++ :variables c-c++-backend 'lsp-ccls)` I am still encountering the same problem. Have you tried typing, then going backwards and deleting?

**Comment by jstaursky** [comment]
okay just deleted everything, now on `Spacemacs branch: develop (rev. b28f1a2ab)` and everything with regards to this issue seems to be resolved.
