### ISSUE TITLE
dotspacemacs-mode not activated in many cases

### ISSUE THREAD

**Issue by trishume** [syl20bnr/spacemacs#1210]
@Volodya333 in the Gitter had trouble finding `SPC m c c` because his `.spacemacs` wasn't created with the template file so it didn't have the magic mode line. Also it doesn't work for people like me who symlink their `.spacemacs` and so opening it opens `~/Box/Dev/Dotfiles/emacs+/spacemacs.symlink`.

IMO we should fix this by getting rid of `dotspacemacs-mode` and just binding `spacemacs/sync-configuration-layers` globally somewhere. There's no reason the binding should only work in the dotfile and that the dotfile needs a separate major mode just to define a keybinding when it really is plain emacs lisp. Most of the code to implement it is actually just ugly hacks to make it actually still work as an elisp mode with smartparens and bindings.

**Comment by darkfeline** [comment]
I think it makes sense to make `spacemacs/sync-configuration-layers` available in all Elisp buffers because it is common to be editing an elisp file that is required or loaded somewhere down the line from `.spacemacs`.

**Comment by CestDiego** [comment]
:+1

**Comment by syl20bnr** [comment]
I agree, one possible key binding could be `SPC f e R` for reload, I prefer the shifted key for this kind of action.
Now if I remove dotspacemacs mode we have to tell people to revert the file local variable, so be ready on the gitter chat :-)

**Comment by trishume** [comment]
@syl20bnr how about to avoid breaking things we just leave dotspacemacs-mode or if there is some way, alias it to elisp. Then just move the functionality elsewhere so it isn't necessary and only there for backwards compatibility.

**Comment by syl20bnr** [comment]
Fixed in develop. I had to change all the defvar to setq to be able to fully use the new bindings (i.e. someone adds a package in a layer and press `SPC f e R` to install it).

I'm adding a message in the release note to tell people to change their `defvar` to `setq`. I won't do any sort of migration script.

**Comment by trishume** [comment]
Sweet! I assume that layers with `defvar` won't crash emacs, just make reloading not work perfectly, which should be fine as a backwards-incompatible change.
