### ISSUE TITLE
Proposal: automatic insert mode in shell

### ISSUE THREAD

**Issue by HerrAugust** [syl20bnr/spacemacs#12113]
I think it does make sense to automatically activate Insert Mode after pressing `SPC '` for shell, so that people can write directly. If I press those keys, it is obvious that I want to write afterwards

**Comment by Miciah** [comment]
Here are a couple ways to configure this.  The simplest way would be to add the following to `dotspacemacs/user-config`:
```emacs-lisp
  (evil-set-initial-state 'eshell-mode 'insert)
```
With the above configuration, Eshell will start in insert state.  However, if one leaves insert state, closes the shell popup, and then re-opens it, then Eshell will then be in the state in which one left it.  If this is not what you want, you can try the following instead:
```emacs-lisp
(add-hook 'shell-pop-in-after-hook
          (lambda ()
            (when (evil-normal-state-p)
              (evil-append 1))))
```
The latter configuration might be annoying though if one switches to normal mode to view some text in scrollback, then switches away from Eshell, and then switches back using <kbd>SPC '</kbd>.
