### ISSUE TITLE
lsp layer and gtags layer in conflict

### ISSUE THREAD

**Issue by jstaursky** [syl20bnr/spacemacs#12114]
using the gtags layer with the lsp layer causes iedit not to work.
originally I thought this was an issue with iedit and the lsp layer see [https://github.com/syl20bnr/spacemacs/issues/12109](original issue).
But now that I have started my init.el from scratch and am adding back all my previous init.el's configurations, it seems that adding gtags was the culprit to my original issue.

**Comment by jstaursky** [comment]
Here's my fix; remove `gtags` layer, add `(helm-gtags :toggle (configuration-layer/package-usedp 'helm))` to `dotspacemacs-additional-packages`  then add the following to init.el
```
  (use-package helm-gtags-mode
    :hook (c-mode c++-mode)
    :init
    ; MUST put following in :init, putting in :config does not work
    (defun helm-gtags-dwim-other-window ()
      "helm-gtags-dwim in the other window"
      (interactive)
      (let ((helm-gtags--use-otherwin t)
            (split-height-threshold nil)
            (split-width-threshold 140))
        (helm-gtags-dwim)))
    (defun spacemacs/helm-gtags-define-keys-for-mode (mode)
      (spacemacs/set-leader-keys-for-major-mode mode
        "oc" 'helm-gtags-create-tags
        "od" 'helm-gtags-dwim
        "og" 'helm-gtags-dwim-other-window
        "ou" 'helm-gtags-update-tags
        "os" 'helm-gtags-select
        "ol" 'helm-gtags-parse-file
        )
      )
    (spacemacs/helm-gtags-define-keys-for-mode 'c-mode)
    (spacemacs/helm-gtags-define-keys-for-mode 'c++-mode)
    )
``` 
of course this only works for `c/c++` source files. But clearly easy to adapt to one's own needs.

Guess I'll leave this open in case anyone else needs something more generic than my soln.

**Comment by creasyw** [comment]
Thank you, @jstaursky! This is very helpful.
