### ISSUE TITLE
 mode line in terminal display error

### ISSUE THREAD

**Issue by sundexian** [syl20bnr/spacemacs#12119]
<img width="846" alt="屏幕快照 2019-04-03 下午2 56 55" src="https://user-images.githubusercontent.com/38940460/55459298-c9240000-5621-11e9-83d0-c73627b7e3e7.png">
I work with macbook pro 2015. I installed spacemacs yesterday.  And the emacs gui have no problem. but the mode line in terminal display error.

**Comment by dukebarman** [comment]
A same error, OSX 10.14

**Comment by sundexian** [comment]
Problem solved. I removed `~/.emacs.d` and recloned the `develop` branch of spacemacs. (I cloned the `master` at first.) But i still don't know why.

**Comment by dukebarman** [comment]
I use master branch

**Comment by Voleking** [comment]
Maybe you need use powerline font in terminal or item2
