### ISSUE TITLE
Proposal: copy&paster easier

### ISSUE THREAD

**Issue by HerrAugust** [syl20bnr/spacemacs#12116]
I think I'm going to say something that many think: shouldn't a basic thing like copy&paste made way easier? Emacs such shortcuts are quite heavy and counter-intuitive. Why not just using something similar to what everyone expects: `C-c` and `C-v` in Insert Mode? Or at least one of the 2. Or at least providing a plugin (layer) easy to install?

Or `M-c` and `M-v`, which are already used for "secondary" shortcuts (scroll up and down) in Emacs, which anyway are already perfectly integrated by `C-up` and `C-down` or similar in Spacemacs

PS: I am a newbie with Emacs, but I guess many will encourage this change

**Comment by duianto** [comment]
Emacs comes with a mode called `cua-mode` which allows for `C-v`, `C-c`, and `C-x` to paste, copy and cut.

You can read about it here:
https://www.emacswiki.org/emacs/CuaMode
http://www.gnu.org/software/emacs/manual/html_node/emacs/CUA-Bindings.html

and the title of this discussion seems like it could include some pros and cons about the mode:
https://www.reddit.com/r/emacs/comments/4hh5kg/learning_emacs_to_cua_or_not_to_cua/

**Comment by humanfactors** [comment]
There will be a vocal group (myself included) who would not support this idea. As mentioned above, these are stock standard settings you can change. This should be closed.

**Comment by HerrAugust** [comment]
Anyways, I've found how to to copy-paste easily.

https://wiki.archlinux.org/index.php/Spacemacs - "Visual state" section
