### ISSUE TITLE
Naming of align-repeat in quick menu

### ISSUE THREAD

**Issue by paullemmens** [syl20bnr/spacemacs#12112]
I recently was in need of aligning on a tilde and was surprise to not being able find a key combo like `SPC x a =` to align on equal sign. The solution obviously is `align-regexp` that I could call with `SPC SPC` at the expense of a lot of typing.

Today, I delved deeper and realized that what Spacemacs calls `align-repeat` (in the quick menu that appears after `SPC x a` with key `r`) actually is referring to `align-regexp`. The [documentation clearly says this](http://spacemacs.org/doc/DOCUMENTATION.html#text-manipulation-commands).

Would it be difficult (code-wise, because the Spacemacs internal function `spacemacs/align-repeat` seems to use Emacs' `align-regexp`) to make (only) the quick menu refer to `SPC x a r` as align-regexp instead of the (to me much unclearer) `align-repeat` ?

(or, is there a specific, historic?, reason why we've labelled it as `align-repeat` that I could use as mnemonic?)

**Comment by paullemmens** [comment]
Bad timing maybe, posting this on April 1st, still, what could I do to help in this?

**Comment by duianto** [comment]
The `develop` branch has an entry in the align keys `SPC x a` section for `=`:
https://github.com/syl20bnr/spacemacs/blob/803d4e720227251e73f687462d54047f849a3f9f/layers/%2Bspacemacs/spacemacs-defaults/keybindings.el#L532

This might be the source of the name `align-repeat`.

The function:
https://github.com/syl20bnr/spacemacs/blob/803d4e720227251e73f687462d54047f849a3f9f/layers/%2Bspacemacs/spacemacs-defaults/funcs.el#L1062
has a comment above it:
>;; modified function from http://emacswiki.org/emacs/AlignCommands

On that page there's this entry:
>Repeating align-regexp
Arguably, for daily use, it’s better to define some adhoc align command, e.g.
```elisp
  (defun align-repeat (start end regexp)
    "Repeat alignment with respect to 
     the given regular expression."
    (interactive "r\nsAlign regexp: ")
    (align-regexp start end 
        (concat "\\(\\s-*\\)" regexp) 1 1 t))
```
>The final t (aka true) is responsible for repeating the task. Call that command with the regular expression [[:space:]]+

**Comment by paullemmens** [comment]
@duianto thanks for the explanation and code analysis. I unsure, however, whether to interpret is as a "this is how it came about and that's it" or as a "here's the relevant bits of code, go ahead to improve it"?

**Comment by duianto** [comment]
Or both 😄 
That seems to be where the name came from.
and
Suggestions for improvements are always welcome.

**Comment by paullemmens** [comment]
@duianto Took some time before I had time to look into it. So I now see how the original function is/was constructed and how all the other repeated aligns are built in spacemacs. So there's a whole bunch of functions `align-repeat` that to be clearer to *my* head should be renamed to `align-regexp`.

I see two but's in that approach: one, it might be only my head having this "difficulty" and two it requires (re)writing a whole lot of documentation to explain the change, etc. Note though that I wouldn't mind putting in that work.

Another approach would be something using `defalias` to just get the menu item labeled the "right" way preventing a lot of (principally) superfluous modifications.

Either way, I think I would like your (or somebody else's) advice on which solution is preferable.

**Comment by duianto** [comment]
I'll forward the question to the maintainers.
