### ISSUE TITLE
holy-mode leader clashes with "[m] - Prefix Command" option

### ISSUE THREAD

**Issue by thelmstedt** [syl20bnr/spacemacs#1211]
In python-mode compare the leader-menu (ie. SPC in normal vs M-m in holy-mode).  Specifically holy-mode's menu is missing the "[m] - Prefix Command" option.  

This probably isn't specific to python-mode.

**Comment by tuhdo** [comment]
You can access major mode command groups with `C-M-m` or `M-RET`.

**Comment by syl20bnr** [comment]
The `[m] - Prefix Command` is not supported in guide-key for now, this is one rough edges we have to address.
We have already an issue for this #183

**Comment by StreakyCobra** [comment]
The key guide is now handled by `which-key`, which shows `[m]` in holy mode. Issue solved few releases ago, so closing this one :relieved:
