### ISSUE TITLE
Transient state convention?

### ISSUE THREAD

**Issue by didibus** [syl20bnr/spacemacs#12111]
The doc says: https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#transient-state that M SPC and S M SPC should be used for transient state.

In practice, it seems that `.` and `?` are used more often. Is there something I don't understand? Or when is one favored over the others?

**Comment by smile13241324** [comment]
Nope "." has mostly been used for older layers and we did not come around or found it important yet to change these. However the layers should bind the other two conventional bindings too.

If they don't it is a bug and should be reported.

**Comment by nixmaniack** [comment]
I'm not sure why this confusion. The transient states are—per convention—on `.`.  The link you mentioned says that as first line.

> Transient states are generally put behind the dot key `.`, for instance the windows manipulation transient state in `SPC w .`.

On the other hand  when it's not possible to use `.`, for example in completion frameworks `helm` or `ivy`, they should be bound to `M-SPC` or `s-M-SPC`. The mentions that as second convention. 
> When it is not possible to use the . (like in `helm` buffers) transient states should be enabled with `M-SPC` and `s-M-SPC`. We need the latter bindings on macOS since `M-SPC` is used by the OS for spotlight.

The question mark `?` convention was a derivation from wide-spread use of magit popups and its convention which more and more packages adopted e.g. `neotree`, `treemacs`. In general, these are provided by packages themselves and spacemacs doesn't change those unless it conflicts with core convention.

**Comment by smile13241324** [comment]
Lol @nixmaniack you seem to know the conventions better than I do :), thanks for helping me out here.

**Comment by nixmaniack** [comment]
@smile13241324 😅I have followed spacemacs evolution closely, and when these conventions were drafted and it just so happens that I'm a bit more pedantic when it comes to conventions in general! Happy to help 😄!
