### ISSUE TITLE
epdfinfo won't load libpoppler

### ISSUE THREAD

**Issue by grepcake** [syl20bnr/spacemacs#12129]
#### Description :octocat:
PDF view is unusable, keeps complaining about not
found libpoppler. Stable spacemacs manages fine.

#### Reproduction guide :beetle:
- Start Emacs
- Try to open any pdf buffer
- Agree to rebuild epdfinfo
- Open any pdf buffer
- Enable pdf-view-mode

*Observed behaviour:* :eyes: :broken_heart:
PDF is opened as a binary file. 

*Expected behaviour:* :heart: :smile:
Working pdf view

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c175e96d8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(yaml
 (ivy :variables ivy-wrap t ivy-height 15 ivy-re-builders-alist
      '((swiper . ivy--regex)
        (t . ivy--regex-fuzzy)))
 (auto-completion :variables auto-completion-idle-delay 0.1 auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual)
 markdown org deft bibtex pandoc latex pdf
 (shell :variables shell-default-shell 'eshell shell-enable-smart-shell t shell-default-height 30 shell-default-position 'bottom)
 ranger treemacs imenu-list git version-control syntax-checking semantic
 (cmake :variables cmake-enable-cmake-ide-support t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c-mode c-c++-enable-clang-support t)
 emacs-lisp
 (haskell :variables haskell-enable-hindent t)
 html ipython-notebook python rust)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
pdf-info-encrypted-p: Error running ‘/home/artem/.emacs.d/elpa/26.1/develop/pdf-tools-20190309.744/epdfinfo’: /home/artem/.emacs.d/elpa/26.1/develop/pdf-tools-20190309.744/epdfinfo: error while loading shared libraries: libpoppler.so.85: cannot open shared object file: No such file or directory
```

**Comment by gcentauri** [comment]
@grepcake can you post the log of building `epdfinfo`?  it sounds to me like a path issue, but perhaps the build on your system didn't work properly.  I'm on OSX currently and will try to reproduce, but the place `poppler` gets installed to is going to be different i'm sure

**Comment by grepcake** [comment]
@gcentauri 
\*Messages*
```Need to (re)build the epdfinfo program, do it now ? (y or n) y
Comint finished
Building the PDF Tools server succeeded
```
build log
```-*- mode: compilation; default-directory: "~/.emacs.d/elpa/26.1/develop/pdf-tools-20190309.744/build/server/" -*-
Comint started at Sat Apr  6 00:49:25

/home/artem/.emacs.d/elpa/26.1/develop/pdf-tools-20190309.744/build/server/autobuild -i /home/artem/.emacs.d/elpa/26.1/develop/pdf-tools-20190309.744/
---------------------------
    Installing packages    
---------------------------
Skipping package installation (already installed)

---------------------------
 Configuring and compiling 
---------------------------
./configure -q --bindir=/home/artem/.emacs.d/elpa/26.1/develop/pdf-tools-20190309.744/ && make -s

Is case-sensitive searching enabled ?     yes
Is modifying text annotations enabled ?   yes
Is modifying markup annotations enabled ? yes


---------------------------
       Installing          
---------------------------
make -s install
make[1]: Entering directory '/home/artem/.emacs.d/elpa/26.1/develop/pdf-tools-20190309.744/build/server'
 /usr/bin/mkdir -p '/home/artem/.emacs.d/elpa/26.1/develop/pdf-tools-20190309.744'
  /usr/bin/install -c epdfinfo '/home/artem/.emacs.d/elpa/26.1/develop/pdf-tools-20190309.744'
make[1]: Nothing to be done for 'install-data-am'.
make[1]: Leaving directory '/home/artem/.emacs.d/elpa/26.1/develop/pdf-tools-20190309.744/build/server'

===========================
   Build succeeded. :O)    
===========================

Comint finished at Sat Apr  6 00:49:30
```

**Comment by gcentauri** [comment]
@grepcake i'm wondering if the part that skipped the package installation means that the dependencies like `poppler` need to be updated on your system.  This is just a guess, but its possible that the older `pdf-tools` package installed older versions of the system libraries.  You could try updating the dependencies on your system, check out the `pdf-tools` github if you haven't already.

Also, look for where `libpoppler` is installed on your system and maybe that will help shed some light on it.  Could be simply a environment/path issue.

**Comment by grepcake** [comment]
@gcentauri thanks for advice. I reinstalled pdf-tools packages and it works once again
