### ISSUE TITLE
Use Ctrl-C to exit insert mode in vim mode

### ISSUE THREAD

**Issue by dandoh** [syl20bnr/spacemacs#12133]
I'm too familiar with exit insert mode in Vim using Ctrl-C instead of Esc. However, I'm not allowed to do this in Spacemacs, how can I set Ctrl-C to exit insert mode and bind current Ctrl-C to other keys?

I'm an absolute beginner in Emacs and Spacemacs.

**Comment by duianto** [comment]
This seems to work:
```
(define-key evil-insert-state-map (kbd "C-c") 'evil-normal-state)
```
You add it to the `(defun dotspacemacs/user-config ()` section of your `.spacemacs` file, which you can open by pressing `SPC f e d`.

**Comment by emil-r-petersen** [comment]
@dandoh Consider closing the issue if this answered your question.

**Comment by LemmingAvalanche** [comment]
Note (not the OP but anyone else who might not know) that `C-c` and `ESC` are [not equivalent in Vim](https://stackoverflow.com/a/80761/1725151).
