### ISSUE TITLE
magit-dispatch SPC g m hot key stopped working

### ISSUE THREAD

**Issue by srgkoshelev** [syl20bnr/spacemacs#12131]
#### Description :octocat:
SPC g m stopped working some time ago.
I have tried deleting .emacs.d and updating from repo to no result.

#### Reproduction guide :beetle:
- Start Emacs
- SPC g m

*Observed behaviour:* :eyes: :broken_heart:
wrong type argument commandp, magit-dispatch

*Expected behaviour:* :heart: :smile:
dispatch pop-up!

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7b5ce34e6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(finance html python helm emacs-lisp git org spell-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by duianto** [comment]
This comment: https://github.com/syl20bnr/spacemacs/issues/12056#issuecomment-472885439
suggests regenerating `.spacemacs` (if you haven't done that already).

`SPC g m` works fine for me.
It's a fresh clone from two days ago, that's on the latest commit of the develop branch. And all packages are up to date.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 09835e1ed)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm lsp multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by srgkoshelev** [comment]
It worked fine, thank you for the tip!

**Comment by amiryal** [comment]
> This comment: [#12056 (comment)](https://github.com/syl20bnr/spacemacs/issues/12056#issuecomment-472885439)
> suggests regenerating `.spacemacs` (if you haven't done that already).

FWIW, for me it was not a case of regenerating `~/.spacemacs`, but rather of updating packages (clicked `[Update Packages]` in the Spacemacs home buffer.)
