### ISSUE TITLE
[regression] smartparens closes ' in M-:

### ISSUE THREAD

**Issue by sei40kr** [syl20bnr/spacemacs#12145]
There seems to be a regression that smartparens closes `'` in M-:.

Is this commit related?
https://github.com/syl20bnr/spacemacs/commit/91914378c16965649a4ed66ef5184bf699024788

I don't want apply smartparens for `'` like rust layer does for lifetime specifiers.
@aaronjensen

**Comment by aaronjensen** [comment]
@sei40kr I can't reproduce this. Can you reproduce it with a default spacemacs config? I wonder if the rust layer is somehow polluting smartparens's handling of emacs lisp in `M-:` which that commit you linked to re-enabled.

**Comment by sei40kr-work** [comment]
@aaronjensen 
I restarted Emacs and I couldn't reproduce this. I'm closing this and reopen with details when it occurs again. Thank you.

**Comment by sei40kr** [comment]
@aaronjensen 
I restarted Emacs and I couldn't reproduce this. I'm closing this and reopen with details if it occurs again. Sorry.
