### ISSUE TITLE
Ocaml and Auto-Complete lead to unusable emacs

### ISSUE THREAD

**Issue by bschommer** [syl20bnr/spacemacs#12149]
#### Description :octocat:
When enabling the ocaml layer as well as the auto-complete layer and opening a .ml file lead to an unresponsive emacs which always hangs at loading yas-snippets on the current development branch.

#### Reproduction guide :beetle:
- Enable ocaml and auto-complete layer
- Start Emacs
- Open a .ml file

*Observed behaviour:* :eyes: :broken_heart:
Emacs hangs at the step loading yas-snippets and will hang after every restart

*Expected behaviour:* :heart: :smile:
Working ocaml-mode

*System Info:* :computer:
OS: linux
Emacs: 26.1
Spacemacs: 0.300.0
Spacemacs branch: develop (rev.  b00767c)
Graphic display: t
Distribution: spacemacs
Editing style: emacs
Layers: ocaml, auto-complete

**Comment by benkonz** [comment]
I've been using Spacemacs for a while with the ocaml-layer and auto-completion. Do you have `merlin` installed?

**Comment by duianto** [comment]
The hanging Emacs issue was related to hl-todo, but it's been fixed, try updating the packages.
It's described in this issue:
hl-todo issue, files open modified, auto-complete layer causes hangs #12143

**Comment by bschommer** [comment]
> A hanging Emacs issue was related to hl-todo, but it's been fixed, try updating the packages.
> It's described in this issue:
> hl-todo issue, files open modified, auto-complete layer causes hangs #12143
> 
> It wasn't ocaml related.

Yes that was probably the issue, spacemacs works again. The issue only occurred after a package update yesterday.

**Comment by bschommer** [comment]
Thanks for the fast reply.
