### ISSUE TITLE
JS language layer throwing errors on develop

### ISSUE THREAD

**Issue by westlywright** [syl20bnr/spacemacs#12144]
#### Description
New JS dependency `import-js` throwing errors on startup

#### Reproduction guide
- Pull latest develop (as of 3-9-2019)
- Install import-js via NPM globally as the new JS lang docs suggest
- Start Emacs

*Observed behaviour:*
The following errors are thrown in the messages buffer 

```elisp
error in process filter: import-js-handle-data: Symbol’s function definition is void: nil
error in process filter: Symbol’s function definition is void: nil
error in process filter: import-js-handle-data: Symbol’s function definition is void: nil
error in process filter: Symbol’s function definition is void: nil
error in process filter: import-js-handle-data: Symbol’s function definition is void: nil
error in process filter: Symbol’s function definition is void: nil
```

*Expected behaviour:*
Not see any errors

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f85acca55)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 emacs-lisp
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 (git :variables git-magit-status-fullscreen t)
 github helm html
 (javascript :variables javascript-backend 'tern node-add-modules-path t)
 (tern :variables tern-command
       '("node" "~/.nvm/versions/node/v11.8.0/bin/tern"))
 markdown
 (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
 (org :variables org-projectile-file "~/repos/org/TODOs.org" org-enable-github-support t org-enable-reveal-js-support t org-enable-org-journal-support t org-enable-bootstrap-support t)
 python shell-scripts
 (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh" shell-default-heightnil 30 shell-default-position 'top)
 sml syntax-checking theming tmux treemacs vim-empty-lines vimscript
 (version-control :variables version-control-diff-tool 'git-gutter+ version-control-global-margin t version-control-diff-side 'left)
 yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by westlywright** [comment]
Maybe related https://github.com/syl20bnr/spacemacs/issues/12142

**Comment by tko** [comment]
OTOH import-js shouldn't be required. _Not_ installing it leads to errors in message buffer on startup:
```
File mode specification error: (file-missing Searching for program No such file or directory importjsd) [5 times]

[persp-mode] Error: Can not autoresume perspectives -- (file-missing Searching for program No such file or directory importjsd)
```
I had three perspectives (layouts?) before restarting, only two got resumed.

**Comment by dennismayr** [comment]
Same here; just out of curiosity: are you using upstream `melpa` packages, or the `spacelpa` repo?

**Comment by westlywright** [comment]
@dennismayr `melpa`

**Comment by tko** [comment]
`melpa` for me as well

**Comment by dennismayr** [comment]
Installing `import-js` globally with `sudo -H npm i -g import-js --unsafe-perm` fixed it for me.

**Comment by tko** [comment]
I just noticed that import-js is also breaking magit ediff, just complains about missing importjsd. Optional dependencies shouldn't be let to break things so badly when not installed. Maybe the package installation should be conditional on existence of importjsd?

In the meantime adding `import-js` to `dotspacemacs-excluded-packages` is a useful workaround.

**Comment by thornjad** [comment]
#12172 fixed all these errors for me

**Comment by smile13241324** [comment]
#12172 has been merged, would you mind giving the latest develop a go @thornjad?

**Comment by thornjad** [comment]
No errors for me on latest develop!

**Comment by dennismayr** [comment]
Error is gone for good.
