### ISSUE TITLE
Javascript using LSP backend crashing after last commits.

### ISSUE THREAD

**Issue by rafagil** [syl20bnr/spacemacs#12142]
#### Description :octocat:
Javascript using LSP backend stopped working after last commits.
I get the message:
File mode specification error: (file-missing Searching for program No such file or directory importjsd)
I'm using typescript-language-server as the lsp provider.

#### Reproduction guide :beetle:
- Start Emacs
- add the lsp layer
- add the javascript layer
- set the javascript backend to 'lsp
- restart
- open any js file

*Observed behaviour:* :eyes: :broken_heart:
An error is shown:
File mode specification error: (file-missing Searching for program No such file or directory importjsd)
lsp is not enabled in the current buffer.

*Expected behaviour:* :heart: :smile:
LSP backend should be enabled and show no errors (Like it does with typescript files currently)

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f85acca55)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (lsp :variables lsp-ui-sideline-enable nil)
 html
 (javascript :variables javascript-backend 'lsp)
 (typescript :variables typescript-backend 'lsp)
 auto-completion emacs-lisp git multiple-cursors treemacs
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by thanhvg** [comment]
That's new feature from import-js. Did you do a 'npm install -g import-js'?

**Comment by rafagil** [comment]
I'm trying to install it on my machine, but it doesn't install for some reason (I get the same permission error in 2 different machines, so probably something wrong with my node version and the npm package).

But anyway, where do I find this information (that I have to install the import-js globally)?

And I don't think the entire LSP should break if one of the cli is missing. couldn't it just work without the import feature? Maybe show a warning or something (not sure if is a spacemacs layer issue)

**Comment by thanhvg** [comment]
Check `README.org` of the `javascript` layer for instruction. 

You may want to use with sudo
```
sudo npm install -g import-js
```
Or in my case I had to use yarn

`import-js` is not very stable. I think we need to refactor is as a standalone layer like `prettier-js` and `web-beautify` instead of this deep integration to `javascript` layer, pinging @syl20bnr and @sei40kr

**Comment by thaibeouu** [comment]
You can also try installing `import-js` with `--unsafe-perm` tag
```
sudo npm install --unsafe-perm -g import-js
```

**Comment by dennismayr** [comment]
@thaibeouu Just tried it and it worked like a charm.

**Comment by rafagil** [comment]
That worked, thanks for help and the info about the README @thanhvg :)
I'll close this as your new issue should solve my other question.
Thanks again!

**Comment by dennismayr** [comment]
This works in Linux; has anyone made it work in Windows 10?
