### ISSUE TITLE
IETF layer is broken due to missing package 

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#12158]
Did nobody test this? 
```
Found 2 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: irfc@ietf... [2/2]
Package irfc is unavailable. Is the package name misspelled?
```

_Originally posted by @robbyoconnor in https://github.com/syl20bnr/spacemacs/pull/12033#issuecomment-482417861_

**Comment by smile13241324** [comment]
Thanks for the catch I will make a fix this evening.

**Comment by goofansu** [comment]
@smile13241324 Seems the PR is closed.

**Comment by robbyoconnor** [comment]
@smile13241324 it didn't work for me so I closed it - Not sure why in testing this isn't working correctly but it isn't :(

**Comment by smile13241324** [comment]
Made a fix, please test and close if ok.

**Comment by robbyoconnor** [comment]
Closing in favor of #12166
