### ISSUE TITLE
Which versions of Emacs does Spacemacs support?

### ISSUE THREAD

**Issue by seako** [syl20bnr/spacemacs#12150]
The README says:
```
Spacemacs requires Emacs 24.4 or above. The development version of Emacs (at the time of writing, this is 25.2) is not officially supported, but should nevertheless be expected to work.
```

But the latest version of Emacs is now 26.1 so this statement is out of date. I'm hoping someone will be able to reply with the versions that Spacemacs supports and then I'll be glad to update the docs accordingly.

**Comment by duianto** [comment]
That's from the master branch documentation.
Here's the latest develop branch documentation: https://github.com/syl20bnr/spacemacs/tree/develop#emacs

>Spacemacs requires Emacs 25.1 or above. The development version of Emacs is not officially supported, but it should nevertheless be expected to work.

**Comment by duianto** [comment]
Thanks for offering to fix it. I'm sure you'll beat us to the next improvement to the docs 😄 
The master branch documentation will be updated when the next major Spacemacs version is released.
(I don't have any insight into when that is)

**Comment by seako** [comment]
Thanks.
