### ISSUE TITLE
[bugreport] M-z-x scale font bad behavior when global-line-number enabled

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#12154]
~/.spacemacs:
dotspacemacs-line-numbers t

![image](https://user-images.githubusercontent.com/36628823/55929717-8630e080-5c50-11e9-92a2-c52f9ff97adc.png)

**Comment by duianto** [comment]
Which Emacs version do you have?

You can copy your Spacemacs system info to the clipboard by pressing `SPC h d s`, then edit your initial post (click the three dots in the top right corner `...`), and paste your system info below the image.

Emacs 26 has built-in line numbers `display-line-numbers-mode`.

I see no gap between the line numbers and the first column, no matter how many times I scale up and down using the `SPC z x` Font Scaling Transient State.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 12defb470)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(c-c++ elfeed helm emacs-lisp git multiple-cursors treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by byteor** [comment]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(go
 (python :variables flycheck-flake8-maximum-line-length 160)
 helm yaml docker auto-completion better-defaults emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
 syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
There have been previous reports of the same issue:
Linum-mode creates margins on zoomed-in font #9382
Line number doesn't go back to normal after I increase the font size and reset it. #8481
org-present not displayed correctly on `develop` branch #8458

I can also confirm that it's an issue on the master branch:

![emacs_2019-04-12_18-20-25](https://user-images.githubusercontent.com/13420573/56051742-f5d9c500-5d4f-11e9-896c-d7b48207baf5.png)

Here's a possible workaround until the next major version is released (I don't have any insight into when that is):
Add this to the `dotspacemacs/user-config` section of your `.spacemacs`:
```
    (spacemacs/set-leader-keys "tn" 'display-line-numbers-mode)
```
Then the `SPC t n` key binding will toggle the new Emacs built-in line numbers in Emacs 26+.

**Comment by byteor** [comment]
thks for your help
