### ISSUE TITLE
Newly opened files get an instant clipboard paste

### ISSUE THREAD

**Issue by 0atman** [syl20bnr/spacemacs#12163]
#### Description :octocat:
spacemacs pastes the contents of my clipboard into the first file I open

#### Reproduction guide :beetle:
- Start Emacs
- select a file either from the spacemacs homescreen, or [SPC b b] and choose a previous file

*Observed behaviour:* :eyes: :broken_heart:
SPACEMACS PASTES MY FRICKIN CLIPBOARD INTO WHEREVER THE CURSOR FIRST APPEARS

Guys, this has been ruining my life subtly for 4 months. I broke so many builds.

*Expected behaviour:* :heart: :smile:
File opens, no edits happen.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 12defb470e9eb6b19c6576045864a4187fc01317)
- Graphic display: wayland
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: Spacemacs default, I deleted my .spacemacs file to check
- System configuration features: 

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
This sounds like a duplicate of:
Auto paste into the files opened by mouse-click the item below Recent Files in Spacemacs buffer #5435

This seems to be the current solution:
https://github.com/syl20bnr/spacemacs/issues/5435#issuecomment-195862080

**Comment by 0atman** [comment]
Aye, dupe of https://github.com/syl20bnr/spacemacs/issues/5059
