### ISSUE TITLE
themes-megapack breaks solarized-dark, changes themes during installation

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#1216]
As title.

1. Add `themes-megapack` to `dotspacemacs-configuration-layers` in a fresh dotfile
2. Load Spacemacs
3. Watch several dozen theme packages be installed, notice that *the current theme is changed by the mere act of installing packages*!
4. Restart Spacemacs
5. Do `SPC T n` to switch to the solarized-dark theme
6. Notice that the colors of the window are not actually dark (they are not what solarized-dark usually looks like)

**Comment by syl20bnr** [comment]
Thank you, fixed in develop and current release branches.

**Comment by bradleywright** [comment]
Worth noting that the `solarized-dark` clash is fixed as of https://github.com/sellout/emacs-color-theme-solarized/pull/157 (not sure about the other issues)

**Comment by syl20bnr** [comment]
@bradleywright thank you, I reopen the issue to add it back again.

**Comment by ddefrenne** [comment]
Seems to be happening again. Installing themes-megapack changes themes during installation. After switching to a theme from the pack back to spacemacs-light seems to mix themes:
![screen shot 2016-10-21 at 14 10 41](https://cloud.githubusercontent.com/assets/83854/19597977/3b617b20-9798-11e6-8478-42d7fef22308.png)

**Comment by romariolopezc** [comment]
@ddefrenne did you solve it?

**Comment by dennismayr** [comment]
When I exit Emacs saving the desktop using a dark theme, and reopening and doing `M-x desktop-read`, previous buffers are loaded and the previous theme is mixed with the current one (I have theme-changer activated, to switch to dark theme after sundown, so reopening under a light theme gets dark elements mixed in). I have to `M-m T n` to cycle themes, and only then is color correctly back again.
