### ISSUE TITLE
"Show snippets in company popup" doesn't work when using company-lsp

### ISSUE THREAD

**Issue by krdzo** [syl20bnr/spacemacs#12173]
#### Description :octocat:
There are no snippets in company popup, when using company-lsp, although auto-completion-enable-snippets-in-popup is set.

company-diag shows this:
```elisp
company-backends: (company-lsp
 (company-c-headers :with company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev :with company-yasnippet))
```
When using a different company backend it works fine. It only doesn't work when using company-lsp.

#### Reproduction guide :beetle:
- Start Emacs
Just enabled and set up company-lsp with ccls for c-c++-mode and set auto-completion-enable-snippets-in-popup.

*Observed behaviour:* :eyes: :broken_heart:
There are no snippets in company popup.

*Expected behaviour:* :heart: :smile:
To see snippets in company popup.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 66eebcf03)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm lsp
      (auto-completion :variables auto-completion-enable-snippets-in-popup t)
      git multiple-cursors treemacs org
      (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
      emacs-lisp
      (c-c++ :variables c-c++-backend 'lsp-ccls)
      lua html)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

**Comment by Compro-Prasad** [comment]
AFAIK it wont work because lsp controls the full completion list. @tigersoldier might be the right person to ask about this.

**Comment by howdoicomputer** [comment]
Yeah, it's either one or the other. The indentation with `yas-insert-snippet` is really wonky and eats up more time than if I just typed stuff in manually. Using company really made it seamless.

**Comment by howdoicomputer** [comment]
So both `emacs-lsp` and `company-lsp` have support for yasnippets. I set the required variables for both but that didn't seem to do anything... but then if I disable `lsp-mode` then I still get lsp features through other lsp minor modes with the additions of snippets.

**Comment by Compro-Prasad** [comment]
@howdoicomputer I you want to get snippets completion in company then you might have to remove `company-lsp` from `company-backends`.
