### ISSUE TITLE
`SPC T h` breaks `SPC T n`

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#1217]
Steps to reproduce:

1. Open Spacemacs with a fresh dotfile
2. Do `SPC T h` and select some theme other than solarized-light
3. Notice that `SPC T n` will no longer allow you to select solarized-light, despite solarized-light being a member of the variable `dotspacemacs-themes`, because solarized-light has been replaced by the theme you selected

**Comment by geo7** [comment]
@TheBB SPC T n seems to be working here..... this still a 'thing' ?

**Comment by kini** [comment]
Yes. Did you try to reproduce according to the listed steps?
