### ISSUE TITLE
spacemacs/enter-ahs-backward doesn't work if word starts with underscore

### ISSUE THREAD

**Issue by sid-kap** [syl20bnr/spacemacs#12188]
#### Description :octocat:
spacemacs/enter-ahs-backward doesn't work if word starts with underscore

#### Reproduction guide :beetle:
- Start Emacs
- In evil mode, move the cursor over a word that starts with an underscore (e.g. `_hi`) and press <kbd>#</kbd>

*Observed behaviour:* :eyes: :broken_heart:
The word doesn't get highlighted in the darker color, and <kbd>n</kbd> and <kbd>p</kbd> don't do anything

*Expected behaviour:* :heart: :smile:
The word should get highlighted in the darker color, and <kbd>n</kbd> and <kbd>p</kbd> should go to the other instances of the word in the file

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8b3a30f24)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml go javascript markdown
      (python :variables python-backend 'lsp)
      helm auto-completion better-defaults emacs-lisp git github neotree lsp groovy latex)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by thanhvg** [comment]
By default evil/emacs doesn't take underscore as word, you can find the fix at
 
http://spacemacs.org/doc/FAQ.html#include-underscores-in-word-motions

**Comment by sid-kap** [comment]
Thanks!
