### ISSUE TITLE
Add org elpa repository to package-archives

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#1218]
I would like to install the `org-plus-contrib` package; AFAICT, the only way to do that within the layer system is to modify the Spacemacs `core-configureation-layer.el` file to include the additional repository, since the init function in .spacemacs runs before `packages-archives` is defined, and the config function runs after the layer system.

**Comment by tuhdo** [comment]
Totally agree. There are quite some good packages in ELPA.

**Comment by syl20bnr** [comment]
Which repository is it ?

**Comment by rpglover64** [comment]
"http://orgmode.org/elpa/" (detailed [here](http://orgmode.org/elpa.html)]

Alternatively, it would be useful if there was some way in `.spacemacs` or in individual layers to specify custom archives.

**Comment by syl20bnr** [comment]
This is planned since the beginning of the layer system and one required feature for `1.0`, one day I hope :-)

What are the additional feature of the `plus-contrib` package ? Do you think it can be used as default in spacemacs ?

**Comment by rpglover64** [comment]
I have it turned on for the [`drill`](http://orgmode.org/worg/org-contrib/org-drill.html) and [`velocity`](http://orgmode.org/worg/org-contrib/org-velocity.html) modules.

I think it can be used, but I don't think it's particularly necessary.

**Comment by tuhdo** [comment]
Why can't ELPA be added? It has some handy packages.

**Comment by meditans** [comment]
@rpglover64, could you detail please how do you manage to use `org-drill`? I inserted the `org` repository in `core-configureation-layer.el`, but don't know what to do next. The problem I have is that it's not a package, so I can't make a layer from it.

**Comment by rpglover64** [comment]
@meditans, Make an `org-plus-contrib` layer (`org-plus-contrib` is a package). I used customize on the variable `org-modules` to enable `org-drill` module, although you can probably use `use-package` in the layer instead.

**Comment by syl20bnr** [comment]
Should be available in develop.
