### ISSUE TITLE
Creating a layer from a package.

### ISSUE THREAD

**Issue by anmoljagetia** [syl20bnr/spacemacs#12192]
So, I am new to the world of emacs, and like most ex-vimmers, I am starting with Spacemacs. I have been trying to find time to do some leetcode and would like to use the package [leetcode-emacs](https://github.com/ginqi7/leetcode-emacs). 

I have been trying to follow the docs and have tried the following :

1. I pressed `SPC` `SPC` `configuration-layer/create-layer`.
2. In the corresponding files that were created, in packages.el, I added the following code.

``` elisp
(defconst myleetcode-packages
  '(
    (ctable :location local)
    names
    (leetcode :location (recipe
                         :fetcher github
                         :repo "ginqi7/leetcode-emacs"))))


(defun myleetcode/init-ctable ()
  (use-package ctable))

(defun myleetcode/init-names ()
  (use-package names))

(defun myleetcode/init-leetcode ()
  (use-package leetcode
    :after names
    :config
    (setq
     leetcode-path "/tmp/"
     leetcode-language "python")))
```

Unfortunately, I asked around on different forums and somebody on Reddit pointed out that this is happening since the package is using the names package for implementing namespaces.

That's why I added the code to import that package as well, but I am getting the exact same error as before :

`Error (use-package): leetcode/:catch: Symbol’s value as variable is void: leetcode-
`

I also tried asking this question a few times in the Gitter chat but I haven't received any help, unfortunately. I am out of my depth here, and I am expecting someone to please point me in the right direction. All and any help is greatly appreciated. Thank you for creating spacemacs, I really like using it!

**Comment by Compro-Prasad** [comment]
You could instead add `leetcode-emacs` to `dotspacemacs-additional-packages` in `~/.spacemacs`. Creating a layer isn't necessary.

**Comment by anmoljagetia** [comment]
Still doesn't work. It needs additional dependencies. I would also like to create a layer so that I can add nice keybindings for it as well.

**Comment by Compro-Prasad** [comment]
I don't think this is a problem with spacemacs. Follow the steps properly and discuss in the Gitter chat and check if you get any suggestions.

**Comment by gcentauri** [comment]
I can take some time to help you out, but I wanted to suggest one solution... If you fork the leetcode package and make it so it doesn't require `names` that might simplify things for you. It essentially means you'd need to add `leetcode-` in front of the function names in that file I think.

**Comment by anmoljagetia** [comment]
@gcentauri Thanks! You're an absolute legend. After struggling for a lot longer, I got frustrated and deleted everything and started again, and surprisingly it worked! It must have been a case of wrong compiled code being available in that location. It's also a bit hard to catch since the layer first downloads the package in `~/.emacs.d/.cache/quelpa/build/leetcode` but ultimately compiles and saves it in `~/.emacs.d/elpa/develop`.

I would remove the names package but my motivation isn't solely to get this working but to sort of understand how to handle package dependencies like this, for other additional layers that I decide to write in the future (I am here for the long term!).

So all in all, the first step is done in my quest. My next idea would be to add keybindings here. I would prefer to add it in `SPC a L` basically` SPC` -> `applications` -> `Leetcode` and then separate  keys for all the available functions.

Can you guid me as to what can I do? The present code is available [here].(https://github.com/anmoljagetia/leetcode-emacs-layer)

**Comment by anmoljagetia** [comment]
@Compro-Prasad The Gitter chat is always very unresponsive and also when other people post things, the context is lost and people aren't able to help. IMO. the GitHub issues follow a better flow for discussions and progress on any issues.

**Comment by anmoljagetia** [comment]
@gcentauri has been of the greatest help and this is the reason I think Open Source is great! With his help, I have been able to work with the problems one-by-one and it's been great!
