### ISSUE TITLE
[auto-completion] How can I using filepath alias for auto completion?

### ISSUE THREAD

**Issue by hanzhixing** [syl20bnr/spacemacs#12194]
Besides the "~", I want to customize alias for filepath auto-completion.

Example: 
1. Set "@/" as an alias for the path "~/workspace/MyProject/src/".
2. Then can type "import '@/lib/.....'" with auto-completion.

I've read the source of "company-files.el", and the "File Aliases" from the emacs manual, but my current knowledge can not help me to achieve this yet.

Why?
[Webpack's Alias](https://webpack.js.org/configuration/resolve/#resolvealias )

Maybe It - the alias - is not a "good thing", but the webpack is so popular, it leads other people place "import '@/lib/....'" in the source code. Without auto-completion, it's too painful.

(English is not my first language. If it is confusing, sorry for that. I will try hard to describe the situation more precisely)

**Comment by gcentauri** [comment]
@hanzhixing - this isn't exactly a Spacemacs specific issue, but I'm happy to help.  If this doesn't solve your problem, you might want to post a question on the Emacs Stack Exchange as well.

One solution that might work uses Emacs `abbrev-mode`.  I honestly don't know if `abbrev-mode` is toggled on by default in Spacemacs but you can try this in your user config.

```emacs-lisp
(setq-default abbrev-mode t)
(define-abbrev global-abbrev-table "src" "~/workspace/MyProject/src/")
```

Then whenever you're typing anywhere pressing `s r c /` will expand the abbreviation.  I could not get it to work with the `"@"` character at all, but I can't say why.  You probably want to use a better abbreviation than `src`, but I thought I'd offer an example.

**Comment by gcentauri** [comment]
@duianto - non-Spacemacs issue, though I admit I don't know if there is a "Spacemacs way" to configure a feature like already.

**Comment by duianto** [comment]
I don't know.

**Comment by hanzhixing** [comment]
Um.......thanks for your quick reply!

It’s of course not a spacemacs issue, nor a company-mode issue.

From my colleagues，I got that other IDEs/Editors have very easy way to integrate such tiny but very useful feature into the tool, like the vscode, webstorm.....

But in emacs it seems doing so is not that easy. Maybe it’s just about whether you’ve materred the elisp......

It’s a pity, the spacemacs default keybindings are too comfortable and I even can not suffer other IDE way any more.

**Comment by hanzhixing** [comment]
Which layer do you think is the best choice, if it is worth to exist? auto-complete?

**Comment by antonalekseev** [comment]
You can as well create following yasnippet in `js-mode` (or whatever mode):

```
# -*- mode: snippet -*-
# name: @ 
# key: @ 
# --
`(concat (projectile-project-root) "src/")`
```

Given that you use projectile and have `.projectile` file in your project root (`~/workspace/MyProject/`), `@` will be expanded with `M-/` to `~/workspace/MyProject/src/`

**Comment by hanzhixing** [comment]
> You can as well create following yasnippet in `js-mode` (or whatever mode):
> 
> ```
> # -*- mode: snippet -*-
> # name: @ 
> # key: @ 
> # --
> `(concat (projectile-project-root) "src/")`
> ```
> Given that you use projectile and have `.projectile` file in your project root (`~/workspace/MyProject/`), `@` will be expanded with `M-/` to `~/workspace/MyProject/src/`

It's not the expected behavior. Snippets replace the content including you typed.
The final code is `......... '@/relative/path/to/a/file'`, not the one has expanded.

The code you show can be correctly resolved by the module resolver, but on the other side, there are team's coding styles(conventions). Like when you typing `~/file/path` in a bash shell,  the bash won't expand the `~` to `/home/Person/file/path`.

**Comment by antonalekseev** [comment]
I see. Sorry, should have pay attention. Then you should advise `company-files` to at first replace all occurences of `@` in `prefix` to string resolvable on the filesystem (desired `src` directory) and then perform reverse replacement on the selected candidate prior to inserting into the buffer. Can't suggest any working code off the top of my head, but this [example](https://www.reddit.com/r/emacs/comments/7dnbxl/how_to_temporally_filter_companymode_candidates/dpzxx6t?utm_source=share&utm_medium=web2x) will give you a hint regarding advising `company` backends.

**Comment by antonalekseev** [comment]
By the way, have you looked at brand new `import-js` Spacemacs layer? It seems to support aliases (https://github.com/Galooshi/import-js#aliases), and even in the case it's not exactly what you want I suppose it will be more convenient for you to extend `import-js` in javascript rather than apply dirty hacks to `company-files` in emacs lisp.

**Comment by hanzhixing** [comment]
> By the way, have you looked at brand new `import-js` Spacemacs layer? It seems to support aliases (https://github.com/Galooshi/import-js#aliases), and even in the case it's not exactly what you want I suppose it will be more convenient for you to extend `import-js` in javascript rather than apply dirty hacks to `company-files` in emacs lisp.

Thank you for your time. It seems `import-js` provides very flexible configurations, I will try it out.

**Comment by hanzhixing** [comment]
If you guys interest, here is [vscode-way](https://code.visualstudio.com/docs/languages/jsconfig#_using-webpack-aliases) and [webstorm-way](https://stackoverflow.com/questions/34943631/path-aliases-for-imports-in-webstorm).

The alias-game may only be introduced by javascript developers now, but I guess this kind of feature is going to be very basic implementation of an IDE/Editor one day, who knows.

If we forget the languages of programming, it is just another enhanced path auto-completion, which is also based on the file system (with path alias supported).

**Comment by hanzhixing** [comment]
Sad! I got no help from import-js.
