### ISSUE TITLE
with-editor: Cannot determine a suitable Emacsclient

### ISSUE THREAD

**Issue by CanftIn** [syl20bnr/spacemacs#12201]
#### Description :octocat:
warning message is
```
Warning (with-editor): Cannot determine a suitable Emacsclient

Determining an Emacsclient executable suitable for the
current Emacs instance failed.  For more information
please see https://github.com/magit/magit/wiki/Emacsclient.
```
running `M-x with-editor-debug` output is
```
with-editor: /home/canftin/.emacs.d/elpa/26.2/develop/with-editor-20190224.931/with-editor.el
emacs: /usr/bin/emacs (26.2)
system:
  system-type: gnu/linux
  system-configuration: x86_64-pc-linux-gnu
  system-configuration-options: --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var --with-x-toolkit=gtk3 --with-xft --with-modules 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
server:
  server-running-p: nil
  server-process: nil
  server-use-tcp: nil
  server-name: server
  server-socket-dir: /tmp/emacs1000
    ERROR: not an accessible directory
  server-auth-dir: ~/.emacs.d/server/
    WARNING: not an accessible directory
with-editor-emacsclient-executable:
 value:   nil (nil)
 default: nil (nil)
 funcall: nil (nil)
path:
  $PATH: "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/canftin/.gem/ruby/2.6.0/bin:/home/canftin/.npm-global/bin:/home/canftin/.gem/ruby/2.6.0/bin:/home/canftin/.npm-global/bin:/home/canftin/.gem/ruby/2.6.0/bin:/home/canftin/.npm-global/bin:/home/canftin/.gem/ruby/2.6.0/bin:/home/canftin/.npm-global/bin"
  exec-path: (/usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /home/canftin/.gem/ruby/2.6.0/bin /home/canftin/.npm-global/bin /home/canftin/.gem/ruby/2.6.0/bin /home/canftin/.npm-global/bin /home/canftin/.gem/ruby/2.6.0/bin /home/canftin/.npm-global/bin /usr/lib/emacs/26.2/x86_64-pc-linux-gnu)
  with-editor-emacsclient-path:
    /usr/local/sbin (t)
    /usr/local/bin (t)
    /usr/bin (t)
      /usr/bin/emacsclient (DLL)
    /usr/lib/jvm/default/bin (t)
    /usr/bin/site_perl (t)
    /usr/bin/vendor_perl (t)
    /usr/bin/core_perl (t)
    /home/canftin/.gem/ruby/2.6.0/bin (t)
    /home/canftin/.npm-global/bin (t)
    /usr/lib/emacs/26.2/x86_64-pc-linux-gnu (t)

```

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
warning appears on Emacs starting.
*Expected behaviour:* :heart: :smile:
remove warning
#### System Info :computer:
- OS: ArchLinux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5510749ea) 
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python clojure haskell scheme racket c-c++ helm
        (colors :variables colors-colorize-identifiers 'variables colors-enable-nyan-cat-progress-bar t)
        prodigy emoji search-engine graphviz
        (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip nil auto-completion-enable-sort-by-usage t)
        better-defaults emacs-lisp markdown multiple-cursors neotree
        (org :variables org-enable-github-support t org-enable-bootstrap-support t)
        syntax-checking version-control CanftIn
        (display :location local))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```

```

**Comment by CanftIn** [comment]
I follow https://github.com/magit/magit/issues/2492 and add ```(setq-default with-editor-emacsclient-executable "emacsclient")``` to remove the warning. But I don't know why leads to the warning.

**Comment by gcentauri** [comment]
@CanftIn - I can't say I found out why it is happening, but I found an open issue that seems like it could be related. https://github.com/magit/with-editor/issues/62 .  I just tried recreating on my own system with a fresh install, but my system seemed to pick up all the configurations correctly.

I can't seem to find that this is an issue with anything Spacemacs is doing though.  You may want to see if the `with-editor` issue I posted is relevant, and if so, this one could possibly be closed as an upstream package issue.

**Comment by gcentauri** [comment]
@duianto - I'm not sure but it seems like this might be an upstream issue rather than a Spacemacs issue.  I can't find anywhere in the spacemacs project that is configuring the `with-editor` paths.

**Comment by duianto** [comment]
You might be right, the only entries for `with-editor` that I'm finding are these:
>CHANGELOG.org:3051:68:- New key bindings ~SPC m ​,​~ and ~SPC m c~ to Valid/Confirm =with-editor=
CHANGELOG.org:3053:62:- New key bindings ~SPC m a~ and ~SPC m k~ to Abort/Discard =with-editor=
layers/+source-control/git/packages.el:206:20:        (add-hook 'with-editor-mode-hook 'evil-normalize-keymaps)
layers/+source-control/git/packages.el:209:36:            (evil-define-key state with-editor-mode-map
layers/+source-control/git/packages.el:210:39:              (concat mm-key mm-key) 'with-editor-finish
layers/+source-control/git/packages.el:211:39:              (concat mm-key "a")    'with-editor-cancel
layers/+source-control/git/packages.el:212:39:              (concat mm-key "c")    'with-editor-finish
layers/+source-control/git/packages.el:213:39:              (concat mm-key "k")    'with-editor-cancel))))
