### ISSUE TITLE
enable virtualenv in python mode automatically

### ISSUE THREAD

**Issue by csfreebird** [syl20bnr/spacemacs#12202]
I have python virtualenv installed on /opt/Python3Env/ folder.
Each time I opened python script file using spacemacs, I need to do the following to enable virtualenv manually:
M-m m v w , 
select . 
then press Enter
M-x revert-buffer

How to make it automatically. I use python everyday, need a way to make it easier.

**Comment by antonalekseev** [comment]
One of the options available is to create `.dir-locals.el` in your project root and call `pyvenv-workon` from it. Like https://emacs.stackexchange.com/a/46641.

**Comment by csfreebird** [comment]
I need a way to do for all python script files. Thanks.

**Comment by antonalekseev** [comment]
In the case of you *always* activating the same virtual environment for all your python files you can add following hook to your `dotspacemacs/user-config`:

```
(add-hook 'python-mode-hook (lambda () (pyvenv-workon "Python3Env")))
```
given that you have `WORKON_HOME` set to `/opt/`, for `pyvenv-workon` accepts virtual env name not full path as argument.

**Comment by csfreebird** [comment]
Thank you very much. It works, and will save a lot time for me.
