### ISSUE TITLE
Auto indent on return after parenthesis?

### ISSUE THREAD

**Issue by GLodi** [syl20bnr/spacemacs#12219]
Is it possible to use auto-indentation on parenthesis just like after braces?

What happens with braces is:

```dart
Widget myWidget() {/*cursor here*/}
```

Press return ->

```dart
Widget myWidget() {   
    /*cursor here*/
}
```

What I would like to have is:

```dart
RaisedButton(/*cursor here*/)
```

Press return ->

```dart
RaisedButton(
    /*cursor here*/
)
```

Whereas now what happens after I press return is simply:

```dart
RaisedButton(
/*cursor here*/)
```

This would be particularly useful in Flutter because there are a lot of elements (widgets) that need to be declared like that.

**Comment by gcentauri** [comment]
@GLodi - it certainly is possible, but I can't say the best way to do it.

I did some digging, and it appears that the behavior for braces you see is defined in the `spacemacs-editing` layer configuration of the `smartparens` package.  in the `spacemacs-editing/init-smartparens` function there are these two lines:

```elisp
      (sp-pair "{" nil :post-handlers
               '(:add (spacemacs/smartparens-pair-newline-and-indent "RET")))
      (sp-pair "[" nil :post-handlers
               '(:add (spacemacs/smartparens-pair-newline-and-indent "RET")))
```

I added an identical line with the open paren and was able to get pretty close to what you want, except that it is still going to indent according to the major mode you are currently in.  You should be able to add this to your `user-config` to create a new smartparens rule that would apply globally.

```elisp
(with-eval-after-load 'smartparens
    (sp-pair "(" nil :post-handlers
             '(:add (spacemacs/smartparens-pair-newline-and-indent "RET")))
    )
```

In elisp mode, I ended up with parens like this:

```elisp
(
  ; cursor here ;
  )
```

That is normal for indenting parens in emacs-lisp mode, so maybe just adding that one configuration to smart-parens will do it for you.  If you want more specific behavior, you can write your own function to stand in place for `spacemacs/smartparens-pair-newline-and-indent`.

Now... it might be better to limit that behavior to the one mode you're wanting it in, but I'm not sure.  If you want to do that there is `sp-local-pair` that will allow you to apply it to a mode or list of modes.

**Comment by GLodi** [comment]
That works great! Thanks!
I made it dart-mode specific like you suggested, because I need it only for Flutter:
```elisp
 (with-eval-after-load 'smartparens
    (sp-local-pair 'dart-mode "(" nil :post-handlers
             '(:add (spacemacs/smartparens-pair-newline-and-indent "RET")))
    )
```

**Comment by gcentauri** [comment]
@GLodi - awesome!  Glad it worked.  It was good for me to dig into what was actually creating that behaviour with the other braces and  brackets.  One of those features I just took for granted :)
