### ISSUE TITLE
evil escape lags in the Terminal editor.

### ISSUE THREAD

**Issue by josiah14** [syl20bnr/spacemacs#1221]
On OSX Mavricks using the stock terminal and tmux.

Recreation steps:
open a file with some text and enter these keys in quick succession with the cursor in the middle of a line which has lines of text above and below (so you can see what happens).

Start in normal mode.
O Esc k j

Observed behavior:
The text below until the next blank line/paragraph is deleted and the character j is inserted into the file at the resulting cursor location.

Sequences such as this make Spacemacs impractical for me to switch to as a Vim user who spends most of his time in the Terminal.  I spend too much time fixing accidentally deleted text by popping history from my undo stack.

**Comment by josiah14** [comment]
I would be happy to fix this myself, but I'm not proficient enough in elisp or emacs at the moment to make that viable :-1:

**Comment by nugend** [comment]
:+1: I'm trying to figure out how to mitigate this right now. For what it's worth, the evil-escape "fd" key sequence provides the correct behavior in that it *immediately* switches from insertion mode to command mode with no lag or intermediate delay. However it seems you can't simply use `(setq-default evil-escape-key-sequence "C-[")` or any equivalent to effectively remap without the lag.

**Comment by syl20bnr** [comment]
I have this kind of feature on the todo list for `evil-escape` but the package was not designed to support this so it may require some works, I see when I can give it a try.

**Comment by syl20bnr** [comment]
Oh and since it seems to be an `evil` related bug you should open an issue here: https://bitbucket.org/lyro/evil/issues

**Comment by nugend** [comment]
Ah, found [this](https://bitbucket.org/lyro/evil/issue/69/delay-between-esc-or-c-and-modeswitch) issue in the evil/issues list which seems to explain the problem (and changing the setting for tmux fixes it for me). @josiah14 Are you also using screen/tmux?

It's kinda weird that tmux even has this setting since I don't know of any tmux command sequences that use escape. Also weird that I've never had any issue with while using vim.

Would it be appropriate to include a note about this in errata somewhere?

**Comment by josiah14** [comment]
I am using tmux, @nugend.  I think it would be appropriate to mention this gotcha in the docs somewhere.  I have yet to meet a serious terminal lover who does not use tmux.

**Comment by josiah14** [comment]
The command to use in your tmux.conf to eliminate the escape timeout is exactly the below:

`set -s -g escape-time 0`

**Comment by josiah14** [comment]
I'm calling this a non-issue since it seems to have been related to my Tmux config (although it's interesting that it doesn't lag for me in Vim, as you mentioned).  Do others agree, or do we think Spacemacs should override the Tmux config to guarantee that hitting ESC will work with a default system configuration?

**Comment by syl20bnr** [comment]
I consider this fixed since there is a working tmux configuration.
