### ISSUE TITLE
open shell and execute command automatically

### ISSUE THREAD

**Issue by csfreebird** [syl20bnr/spacemacs#12215]
I always type 'source /opt/pythenEnv/bin/activate' to switch to python virtualenv after opening shell with M-x ' .
How to make it happen automatically without type 'source ...' command manually?

**Comment by antonalekseev** [comment]
If you use `eshell` (value of `shell-default-shell` is `eshell`) then place your `source ...` command to startup script file which location is specified in `eshell-rc-script` variable.

**Comment by csfreebird** [comment]
I am using shell by default
`     (shell :variables
            shell-default-height 30
            shell-default-shell 'shell
            shell-default-position 'bottom)`

**Comment by antonalekseev** [comment]
Then you should place said command to `~/.emacs_SHELLNAME` where `SHELLNAME` is the name of inferior shell of you choice (like `bash` or `zsh`, see `shell-file-name` variable). See also `SPC h d f shell`.

**Comment by csfreebird** [comment]
I tried ~/.emacs_bash, add 'source ... ' command in it, restart emacs. It works, 
Thank you again. :)
