### ISSUE TITLE
Same “README” file in two layers

### ISSUE THREAD

**Issue by makeztc** [syl20bnr/spacemacs#12216]
The README file in [spacemacs-project](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bspacemacs/spacemacs-project/README.org) layer is same as the file in[ spacemacs-org](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bspacemacs/spacemacs-org/README.org) layer.

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
Fix spacemacs-project setup readme #12241

**Comment by makeztc** [comment]
Thanks!
