### ISSUE TITLE
AutoDocStrings layer similar to AutoDocstring in Sublime

### ISSUE THREAD

**Issue by schlowm0** [syl20bnr/spacemacs#12211]
I was wondering if there exist a layer for spacemacs which creates empty docstrings for all written functions in a given python script/file, but also creates entries for all functions parameters, warnings and return values similar to [this](https://packagecontrol.io/packages/AutoDocstring)?

**Comment by schlowm0** [comment]
Any update on this?

**Comment by lebensterben** [comment]
There's no such package.
