### ISSUE TITLE
Julia-layer: Version manager support

### ISSUE THREAD

**Issue by taqtiqa-mark** [syl20bnr/spacemacs#12229]
Enhancement / Feature-request:

Julia has inherited the Ruby version manager scripts, [rbenv](https://github.com/rbenv/rbenv) in the form of [jlenv]() and [julia-build](https://github.com/HiroakiMikami/julia-build).

Consequently, it would be useful to replicate the [Ruby-layer version manager support](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/ruby#ruby-version-management) in the Julia layer.  

For example:
```
(defun dotspacemacs-configuration-layers ()
   '((julia :variables julia-version-manager 'jlenv)))
```

At the moment I have only used jlenv.

**Comment by gdkrmr** [comment]
You can select the julia version by setting `lsp-julia-command` for the language server and there are ways to manage julia version with `julia-repl.el` https://github.com/tpapp/julia-repl. What exacly would you gain by doing this? It would probably make sense to unify setting the julia version for both packages.

**Comment by taqtiqa-mark** [comment]
Thanks for looking into this @gdkrmr.

I don't use the Language Server, maybe I should but it appears to be fragile, not easy to get working, and not conducive to switching to the bleeding edge fro time to time - I'll update with reference links.

> What exacly would you gain by doing this?

Users would gain the functionality of `jlenv` in regular/production work flows:

1. Project/folder specific Julia versions.
1. Switching versions defined by `.julia-version' file or `JLENV_VERSION` variable.
1. Isolates Julia installed versions to `~/.jlenv`

Unfortunately I'm not familiar with the Julia ayer or `julia-repl`.  Is it possible to have the Julia layer or `julia-repl.el` switch the Julia it launches using `jlenv`?

**Comment by taqtiqa-mark** [comment]
The following appears to be a workaround.  Interesting that `~/.jlenv/shims/julia` does not seem to work.
```
(setq julia-repl-executable-records
      '((default "/home/<your-user-name>/.jlenv/shims/julia")   ; in the executable path
        (global "/user/local/bin/julia"))) ; compiled from the repository
```

Hope that helps someone else?

**Comment by gdkrmr** [comment]
I usually put a symlink in `~/bin` and manage the julia version by switching the target of that symlink to different julia versions. This does not let you edit julia 1.0 and julia 0.6 projects simultaneously but I never had the need to do that.
