### ISSUE TITLE
auto-complete error c++ qt5 clang

### ISSUE THREAD

**Issue by osfe** [syl20bnr/spacemacs#12225]
#### Description :octocat:
auto-completion error with qt5 headers

#### Reproduction guide :beetle:
- Start Emacs
- edit c++/qt5 file
- insert `#include <QWidget>`

*Observed behaviour:* :eyes: :broken_heart:
```
Wed Apr 24 15:45:41 2019
clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c   -Xclang -code-completion-at=-:11:6 -

<stdin>:4:10: fatal error: 'QWidget' file not found
#include <QWidget>
         ^~~~~~~~~
1 error generated.
```

*Expected behaviour:* :heart: :smile:
no error

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(yaml html helm
      (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
      emacs-lisp git org
      (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
      spell-checking syntax-checking
      (colors :variables colors-colorize-identifiers 'variables))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2

#### Backtrace :paw_prints:
```
Wed Apr 24 15:45:41 2019
clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c   -Xclang -code-completion-at=-:11:6 -

<stdin>:4:10: fatal error: 'QWidget' file not found
#include <QWidget>
         ^~~~~~~~~
1 error generated.
```

**Comment by osfe** [comment]
I think I found the solution. Create a file .clang_complete in the folder and add the path to the headers clang can't find himself...

```
-I/usr/include/qt5/
-I/usr/include/qt5/Enginio/
-I/usr/include/qt5/Qt3DAnimation/
-I/usr/include/qt5/Qt3DCore/
-I/usr/include/qt5/Qt3DExtras/
-I/usr/include/qt5/Qt3DInput/
-I/usr/include/qt5/Qt3DLogic/
-I/usr/include/qt5/Qt3DQuick/
-I/usr/include/qt5/Qt3DQuickAnimation/
-I/usr/include/qt5/Qt3DQuickExtras/
-I/usr/include/qt5/Qt3DQuickInput/
-I/usr/include/qt5/Qt3DQuickRender/
-I/usr/include/qt5/Qt3DQuickScene2D/
-I/usr/include/qt5/Qt3DRender/
-I/usr/include/qt5/QtAccessibilitySupport/
-I/usr/include/qt5/QtBluetooth/
[...]
```
The problem is that clang becomes quite slow.

[clang_complete.txt](https://github.com/syl20bnr/spacemacs/files/3116976/clang_complete.txt)

**Comment by osfe** [comment]
Actually, still an error 

`Fri Apr 26 12:28:22 2019
clang failed with error 1:
/usr/bin/clang -fsyntax-only -Xclang -code-completion-macros -x c++ -I/usr/include/qt5/Enginio/ -I/usr/include/qt5/Qt3DAnimation/ -I/usr/include/qt5/Qt3DCore/ -I/usr/include/qt5/Qt3DExtras/ -I/usr/include/qt5/Qt3DInput/ -I/usr/include/qt5/Qt3DLogic/ -I/usr/include/qt5/Qt3DQuick/ -I/usr/include/qt5/Qt3DQuickAnimation/ -I/usr/include/qt5/Qt3DQuickExtras/ -I/usr/include/qt5/Qt3DQuickInput/ -I/usr/include/qt5/Qt3DQuickRender/ -I/usr/include/qt5/Qt3DQuickScene2D/ -I/usr/include/qt5/Qt3DRender/ -I/usr/include/qt5/QtAccessibilitySupport/ -I/usr/include/qt5/QtBluetooth/ -I/usr/include/qt5/QtCharts/ -I/usr/include/qt5/QtConcurrent/ -I/usr/include/qt5/QtCore/ -I/usr/include/qt5/QtDataVisualization/ -I/usr/include/qt5/QtDBus/ -I/usr/include/qt5/QtDesigner/ -I/usr/include/qt5/QtDesignerComponents/ -I/usr/include/qt5/QtDeviceDiscoverySupport/ -I/usr/include/qt5/QtEdidSupport/ -I/usr/include/qt5/QtEglFSDeviceIntegration/ -I/usr/include/qt5/QtEglSupport/ -I/usr/include/qt5/QtEventDispatcherSupport/ -I/usr/include/qt5/QtFbSupport/ -I/usr/include/qt5/QtFontDatabaseSupport/ -I/usr/include/qt5/QtGamepad/ -I/usr/include/qt5/QtGlxSupport/ -I/usr/include/qt5/QtGui/ -I/usr/include/qt5/QtHelp/ -I/usr/include/qt5/QtInputSupport/ -I/usr/include/qt5/QtKmsSupport/ -I/usr/include/qt5/QtLinuxAccessibilitySupport/ -I/usr/include/qt5/QtLocation/ -I/usr/include/qt5/QtMultimedia/ -I/usr/include/qt5/QtMultimediaGstTools/ -I/usr/include/qt5/QtMultimediaQuick/ -I/usr/include/qt5/QtMultimediaWidgets/ -I/usr/include/qt5/QtNetwork/ -I/usr/include/qt5/QtNetworkAuth/ -I/usr/include/qt5/QtNfc/ -I/usr/include/qt5/QtOpenGL/ -I/usr/include/qt5/QtOpenGLExtensions/ -I/usr/include/qt5/QtPacketProtocol/ -I/usr/include/qt5/QtPlatformCompositorSupport/ -I/usr/include/qt5/QtPlatformHeaders/ -I/usr/include/qt5/QtPositioning/ -I/usr/include/qt5/QtPositioningQuick/ -I/usr/include/qt5/QtPrintSupport/ -I/usr/include/qt5/QtQml/ -I/usr/include/qt5/QtQmlDebug/ -I/usr/include/qt5/QtQuick/ -I/usr/include/qt5/QtQuickControls2/ -I/usr/include/qt5/QtQuickParticles/ -I/usr/include/qt5/QtQuickTemplates2/ -I/usr/include/qt5/QtQuickTest/ -I/usr/include/qt5/QtQuickWidgets/ -I/usr/include/qt5/QtRemoteObjects/ -I/usr/include/qt5/QtRepParser/ -I/usr/include/qt5/QtScript/ -I/usr/include/qt5/QtScriptTools/ -I/usr/include/qt5/QtScxml/ -I/usr/include/qt5/QtSensors/ -I/usr/include/qt5/QtSerialBus/ -I/usr/include/qt5/QtSerialPort/ -I/usr/include/qt5/QtServiceSupport/ -I/usr/include/qt5/QtSql/ -I/usr/include/qt5/QtSvg/ -I/usr/include/qt5/QtTest/ -I/usr/include/qt5/QtTextToSpeech/ -I/usr/include/qt5/QtThemeSupport/ -I/usr/include/qt5/QtUiPlugin/ -I/usr/include/qt5/QtUiTools/ -I/usr/include/qt5/QtWaylandClient/ -I/usr/include/qt5/QtWaylandCompositor/ -I/usr/include/qt5/QtWebChannel/ -I/usr/include/qt5/QtWebEngine/ -I/usr/include/qt5/QtWebEngineCore/ -I/usr/include/qt5/QtWebEngineWidgets/ -I/usr/include/qt5/QtWebKit/ -I/usr/include/qt5/QtWebKitWidgets/ -I/usr/include/qt5/QtWebSockets/ -I/usr/include/qt5/QtWebView/ -I/usr/include/qt5/QtWidgets/ -I/usr/include/qt5/QtX11Extras/ -I/usr/include/qt5/QtXcb/ -I/usr/include/qt5/QtXml/ -I/usr/include/qt5/QtXmlPatterns/ -Xclang -code-completion-at=-:15:10 -

In file included from <stdin>:1:
In file included from ./port_setup.hxx:4:
In file included from /usr/include/qt5/QtWidgets/QWidget:1:
/usr/include/qt5/QtWidgets/qwidget.h:43:10: fatal error: 'QtWidgets/qtwidgetsglobal.h' file not found
#include <QtWidgets/qtwidgetsglobal.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
`

**Comment by Compro-Prasad** [comment]
I think `-I/usr/include/qt5/` wasn't applied properly.

**Comment by osfe** [comment]
what do you mean ??

**Comment by Compro-Prasad** [comment]
`QtWidgets/qtwidgetsglobal.h` lies in the `/usr/include/qt5/` directory and if it isn't in the include path then `QtWidgets/qtwidgetsglobal.h` won't be found. IMO using just `qtwidgetsglobal.h` would work as `/usr/include/qt5/QtWidgets/` is in the include path.

**Comment by osfe** [comment]
does not work either...
[_clang_complete.txt](https://github.com/syl20bnr/spacemacs/files/3141321/_clang_complete.txt)

**Comment by Compro-Prasad** [comment]
Try with:
```
-I/usr/include/qt5/
-I/usr/include/qt5/Qt3DQuickInput/qt3dquickinput_global.h
-I/usr/include/qt5/QtCharts/qchartglobal.h
-I/usr/include/qt5/Enginio/enginioclient_global.h
-I/usr/include/qt5/QtXml/qtxmlglobal.h
-I/usr/include/qt5/QtScript/qtscriptglobal.h
-I/usr/include/qt5/QtRemoteObjects/qtremoteobjectglobal.h
-I/usr/include/qt5/QtHelp/qhelp_global.h
-I/usr/include/qt5/QtWebEngineWidgets/qtwebenginewidgetsglobal.h
-I/usr/include/qt5/QtCore/qglobal.h
-I/usr/include/qt5/QtGui/qtguiglobal.h
-I/usr/include/qt5/Qt3DQuickScene2D/qt3dquickscene2d_global.h
-I/usr/include/qt5/Qt3DAnimation/qt3danimation_global.h
-I/usr/include/qt5/QtSql/qtsqlglobal.h
-I/usr/include/qt5/Qt3DQuick/qt3dquick_global.h
-I/usr/include/qt5/QtNetwork/qtnetworkglobal.h
-I/usr/include/qt5/QtWaylandCompositor/qtwaylandcompositorglobal.h
-I/usr/include/qt5/QtWaylandClient/qtwaylandclientglobal.h
-I/usr/include/qt5/QtQuick/qtquickglobal.h
-I/usr/include/qt5/QtBluetooth/qtbluetoothglobal.h
-I/usr/include/qt5/QtBluetooth/qbluetoothglobal.h
-I/usr/include/qt5/QtPositioningQuick/qpositioningquickglobal.h
-I/usr/include/qt5/QtGamepad/qtgamepadglobal.h
-I/usr/include/qt5/QtPrintSupport/qtprintsupportglobal.h
-I/usr/include/qt5/QtXmlPatterns/qtxmlpatternsglobal.h
-I/usr/include/qt5/Qt3DInput/qt3dinput_global.h
-I/usr/include/qt5/QtWebEngine/qtwebengineglobal.h
-I/usr/include/qt5/QtWebEngineCore/qtwebenginecoreglobal.h
-I/usr/include/qt5/Qt3DExtras/qt3dextras_global.h
-I/usr/include/qt5/QtTextToSpeech/qtexttospeech_global.h
-I/usr/include/qt5/QtWebView/qwebview_global.h
-I/usr/include/qt5/QtSvg/qtsvgglobal.h
-I/usr/include/qt5/QtLocation/qlocationglobal.h
-I/usr/include/qt5/QtDBus/qtdbusglobal.h
-I/usr/include/qt5/QtMultimedia/qtmultimediaglobal.h
-I/usr/include/qt5/Qt3DQuickExtras/qt3dquickextras_global.h
-I/usr/include/qt5/Qt3DQuickRender/qt3dquickrender_global.h
-I/usr/include/qt5/QtSerialPort/qserialportglobal.h
-I/usr/include/qt5/QtWidgets/qtwidgetsglobal.h
-I/usr/include/qt5/Qt3DLogic/qt3dlogic_global.h
-I/usr/include/qt5/QtWebKit/qwebkitglobal.h
-I/usr/include/qt5/QtPositioning/qpositioningglobal.h
-I/usr/include/qt5/QtWebSockets/qwebsockets_global.h
-I/usr/include/qt5/QtSensors/qsensorsglobal.h
-I/usr/include/qt5/QtSerialBus/qserialbusglobal.h
-I/usr/include/qt5/QtQuickTest/quicktestglobal.h
-I/usr/include/qt5/QtConcurrent/qtconcurrent_global.h
-I/usr/include/qt5/QtQuickControls2/qtquickcontrols2global.h
-I/usr/include/qt5/QtDesigner/sdk_global.h
-I/usr/include/qt5/QtDesigner/extension_global.h
-I/usr/include/qt5/QtDesigner/qdesigner_components_global.h
-I/usr/include/qt5/QtDesigner/uilib_global.h
-I/usr/include/qt5/QtX11Extras/qtx11extrasglobal.h
-I/usr/include/qt5/Qt3DRender/qt3drender_global.h
-I/usr/include/qt5/QtQml/qtqmlglobal.h
-I/usr/include/qt5/Qt3DQuickAnimation/qt3dquickanimation_global.h
-I/usr/include/qt5/Qt3DCore/qt3dcore_global.h
-I/usr/include/qt5/QtTest/qtest_global.h
-I/usr/include/qt5/QtTest/qttestglobal.h
-I/usr/include/qt5/QtQuickWidgets/qtquickwidgetsglobal.h
-I/usr/include/qt5/QtOpenGL/qtopenglglobal.h
-I/usr/include/qt5/QtNetworkAuth/qoauthglobal.h
-I/usr/include/qt5/QtNfc/qnfcglobal.h
-I/usr/include/qt5/QtNfc/qtnfcglobal.h
-I/usr/include/qt5/QtDataVisualization/qdatavisualizationglobal.h
-I/usr/include/qt5/QtWebChannel/qwebchannelglobal.h
```
