### ISSUE TITLE
some basic features do not work in table.el with org mode

### ISSUE THREAD

**Issue by csfreebird** [syl20bnr/spacemacs#12222]
I will change to table.el in org when merged cell feature needed. But some basic features in org table do not work in table.el. e.g.
1. link to something, i.e.  [[chapter1][chapter1]]
2. latex i.e. $x_{i}$
3. Calc and Elisp formulas

correct me if I was wrong, or any help to solve part of above issues?

**Comment by gcentauri** [comment]
@csfreebird There is a bit of info about Org cooperation with `table.el` here.  https://orgmode.org/manual/Cooperation.html

It sounds like you can't really get org features in those tables.  If this answers your question, please go ahead and close this issue ticket.
