### ISSUE TITLE
[Request] Live preview markdown with pandoc?

### ISSUE THREAD

**Issue by biocyberman** [syl20bnr/spacemacs#12223]
For my writings, I use markdown and pandoc a lot. Currently I have to switch to the terminal or use `SPC  c C` to run pandoc command line. After that I open and view PDF or HTML file myself. It will be very nice if I can preview in PDF or HTML format my markdown document on another buffer. Currently `markdown` and `pandoc` layers do not seem to have anything for this purpose. I tried setting `markdown-live-preview-engine` to `pandoc` but it didn't help.

**Comment by Voleking** [comment]
@biocyberman you need edit markdown-command too, Here is my config as an example:
```emacs-lisps
     (markdown :variables
               markdown-command "pandoc -t html5 -f markdown+smart --mathjax --highlight-style=pygments --toc --toc-depth 3 --template github.html5 --css html/css/github.css"
               markdown-live-preview-engine 'pandoc)

```

**Comment by biocyberman** [comment]
@Voleking Thanks I changed markdown-command as well and it made some differences. However I am still haven't got the desirable outcome. It's anyway another problem, so I will close this for now.
