### ISSUE TITLE
Deleting windows based on its numbers

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1222]
Since we can switch between window with SPC 1 and such, it would be nice if we can delete them with number i.e. "SPC d 1" deletes wondow 1. Similarly, "SPC b 1" switches buffer in window 1 when we are in window 2 without switching to it. With this feature, we won't have to move to a window, switch buffer than go back. And it would be much easier to control when we have 3 or more windows.

**Comment by syl20bnr** [comment]
Maybe with the prefix argument ? Ideally we could contribute to `window-numbering`.

**Comment by tuhdo** [comment]
I think we should separate the commands instead of reusing the existing `SPC-<number>` keys. Imagine that if I want to open a buffer in a window with `C-u SPC 2` but for mistaken added another prefix argument to become `C-u C-u SPC 2` and delete my window number 2, it's pretty annoying. Probably we can use `C-u SPC` to delete windows, but `SPC b <number`> to switch buffer on that window. That way, it would be easier to avoid mistake and has more logical grouping. And of course, we have to reuse `window-numbering`.

**Comment by syl20bnr** [comment]
What I propose is <kbd>SPC #</kbd> to switch to a window as it is now, it is a high frequency key binding, adding a keystroke would be bad for productivity.
To delete a window <kbd>SPC u SPC #</kbd>.  So there is no ambiguity. But in holy-mode it is the less smooth <kbd>C-u M-m #</kbd>, OTOH deleting windows is not has frequent and to delete several windows there is <kbd>SPC w .</kbd> micro-state.

<kbd>SPC b #</kbd> could used for something else, like buffer swapping for instance.

**Comment by tuhdo** [comment]
Yes, `SPC b <number>` can be used for something else, if we could make use of `window-purpose` since buffer can be automatically assigned to correct window that has the same purpose. But for deleting windows, that's my frequent operation i.e. when you have 3 or more windows, you have to switch window and delete it then move back to original window. It would be nice if we simply use the same way to switch to a window, but this time instead of switching, just delete it without moving cursor elsewhere.

**Comment by syl20bnr** [comment]
What about shifting the number then ? <kbd>SPC !</kbd> to delete window 1.

**Comment by tuhdo** [comment]
Ok, look good to me.

**Comment by StreakyCobra** [comment]
`SPC u SPC #` is already available in current release. Old issue, not relevant anymore.

For the record:

> What about shifting the number then ? SPC ! to delete window 1.

This would have break a loooot of keyboard layouts, even the `QWERTY` based ones (like french `AZERTY`, Swiss-french `QWERTZ`, etc.)
