### ISSUE TITLE
Hydra key behaviors do not match the Hydra menu in Spacemacs.

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#12231]
#### Description :octocat:
Hydra menu appears as expected on Spacemacs:
    see screen shot at https://i.stack.imgur.com/uRqpA.png

But some of the Emacs \*help\* hydra-ivy/body functions and Hydra key behaviors do not match the Hydra menu.  Four examples follow.

1) Hydra menu says:

        [f] case-fold: auto

    Pressing 'f' toggles between 'nil' and 'auto'.
    In the help, hydra-ivy/body says:

        "f": ‘ivy-alt-done &optional’
        Exit the minibuffer with the selected candidate.

2) Hydra menu says:

        [TAB] alt done

    Pressing TAB opens \*ivy-occur counsel-find-file ""\*<2>:
        see screen shot at https://i.stack.imgur.com/jIzon.png
    In the help, hydra-ivy/body does not mention "TAB".

3) Hydra menu says:

        [c] & cont

    Pressing 'c' opens \*ivy-occur counsel-find-file ""\*<2>.
    In the help, hydra-ivy/body says:

        "c":    ‘ivy-toggle-calling’

4) Hydra menu says:

        [o]  occur

    In the help, hydra-ivy/body says:

        "o": ‘keyboard-escape-quit’

    Pressing 'o' opens \*ivy-occur counsel-find-file ""\*<2>

Related links:
https://emacs.stackexchange.com/questions/49101/how-to-select-a-rotating-hydra-option
https://github.com/abo-abo/swiper/issues/1213

#### Reproduction guide :beetle:
- Start Emacs
- open minibuffer with SPC f f
- C-o in the minibuffer displays a hydra menu

*Observed behaviour:* :eyes: :broken_heart:
Some of the Emacs *help* hydra-ivy/body functions and Hydra key behaviors do not match the Hydra menu.  Details are above in the "Description" section.

*Expected behaviour:* :heart: :smile:
All the Emacs *help* hydra-ivy/body functions and Hydra key behaviors match the Hydra menu.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(rust html csv c-c++ git shell spell-checking ivy emacs-lisp markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS XWIDGETS LCMS2

#### Backtrace :paw_prints:
none

**Comment by gcentauri** [comment]
Hi @wolfv6, the issue here is that the hydra/transient you are viewing when pressing `C-o` is *not* the Ivy hydra.  It is a custom hydra set by `spacemacs|define-transient-state` in the `spacemacs-completion` layer.  I think the answer on your stack exchange question said the same thing.

So when you press `C-o` while in an `ivy` buffer in spacemacs, it actually calls the function `spacemacs/ivy-transient-state/body`, and those are the bindings you are seeing in the menu.

If you want to launch the normal `hydra-ivy/body` menu, that is mapped to `M-SPC` in the Spacemacs Ivy layer.

Now, it looks to me like the code that set-up the Spacemacs Ivy hydra is from a few years ago before ivy-hydra package was part of the Ivy layer, and perhaps it now redundant.

If you want to map `C-o` to open the standard Ivy hydra, that is certainly doable.  But the root cause here is that you are not actually viewing the `hydra-ivy/body` menu, so the help doesn't match up.

**Comment by wolfv6** [comment]
Which Hydra menu and function is Spacemacs intended call by design?

On my Linux Fedora, M-SPC opens the Gnome desktop's window-resize context menu.

**Comment by gcentauri** [comment]
I assume Spacemacs is designed to call `spacemacs/ivy-transient-state/body`.   Here is the `spacemacs-completion` default Ivy configuration:

```elisp
(defun spacemacs-completion/init-default-ivy-config ()
  (with-eval-after-load 'ivy
    (setq ivy-height 15
          ivy-re-builders-alist '((spacemacs/counsel-search . spacemacs/ivy--regex-plus)
                                  (t . ivy--regex-ignore-order)))
    (spacemacs|hide-lighter ivy-mode)
    ;; setup hooks
    (add-hook 'spacemacs-editing-style-hook 'spacemacs//ivy-hjkl-navigation)
    ;; key bindings
    ;; ensure that the correct bindings are set at startup
    (spacemacs//ivy-hjkl-navigation dotspacemacs-editing-style)
    ;; Transient state
    ;; ivy-hydra disabled for now, waiting to see how the dependency management
    ;; evolves upstream
    ;; (require 'ivy-hydra)
    (spacemacs|define-transient-state ivy
      :doc "
 Move/Resize^^^^      | Select Action^^^^   |  Call^^          |  Cancel^^    | Toggles
--^-^-^-^-------------|--^-^-^-^------------|--^---^-----------|--^-^---------|---------------------
 [_j_/_k_] by line    | [_s_/_w_] next/prev | [_RET_] & done   | [_i_] & ins  | [_C_] calling: %s(if ivy-calling \"on\" \"off\")
 [_g_/_G_] first/last | [_a_]^ ^  list all  | [_TAB_] alt done | [_q_] & quit | [_m_] matcher: %s(spacemacs//ivy-matcher-desc)
 [_d_/_u_] pg down/up |  ^ ^ ^ ^            | [_c_]   & cont   |  ^ ^         | [_f_] case-fold: %`ivy-case-fold-search
 [_<_/_>_] resize     |  ^ ^ ^ ^            | [_o_]   occur    |  ^ ^         | [_t_] truncate: %`truncate-lines
 [_h_/_l_] out/in dir |  ^ ^ ^ ^            |  ^ ^             |  ^ ^         |  ^ ^

Current Action: %s(ivy-action-name)
"
      :foreign-keys run
      :bindings
      ;; arrows
      ("j" ivy-next-line)
      ("k" ivy-previous-line)
      ("l" ivy-alt-done)
      ("h" spacemacs/counsel-up-directory-no-error)
      ("g" ivy-beginning-of-buffer)
      ("G" ivy-end-of-buffer)
      ("d" ivy-scroll-up-command)
      ("u" ivy-scroll-down-command)
      ;; actions
      ("q" keyboard-escape-quit :exit t)
      ("C-g" keyboard-escape-quit :exit t)
      ("<escape>" keyboard-escape-quit :exit t)
      ("i" nil)
      ("C-o" nil)
      ("M-SPC" nil)
      ("TAB" ivy-alt-done :exit nil)
      ;; ("C-j" ivy-alt-done :exit nil)
      ;; ("d" ivy-done :exit t)
      ("RET" ivy-done :exit t)
      ("c" ivy-call)
      ("C-m" ivy-done :exit t)
      ("C" ivy-toggle-calling)
      ("m" ivy-rotate-preferred-builders)
      (">" ivy-minibuffer-grow)
      ("<" ivy-minibuffer-shrink)
      ("w" ivy-prev-action)
      ("s" ivy-next-action)
      ("a" ivy-read-action)
      ("t" (setq truncate-lines (not truncate-lines)))
      ("f" ivy-toggle-case-fold)
      ("o" ivy-occur :exit t))
    (define-key ivy-minibuffer-map "\C-o" 'spacemacs/ivy-transient-state/body)
    (define-key ivy-minibuffer-map (kbd "M-SPC")
      'spacemacs/ivy-transient-state/body)
    (define-key ivy-minibuffer-map (kbd "s-M-SPC")
      'spacemacs/ivy-transient-state/body)
    ))
```
Notice the comment about not requiring `ivy-hydra` right now to see how dependency management evolves upstream.

The `ivy` layer _does_ require `ivy-hydra` but only does very minimal configuration:

```elisp
(defun ivy/init-ivy-hydra ()
  (use-package ivy-hydra)
  (define-key hydra-ivy/keymap [escape] 'hydra-ivy/keyboard-escape-quit-and-exit))
```
If you want to remap `C-o` to use the standard `ivy-hydra`, just put this in your `user-config`:

`(define-key ivy-minibuffer-map (kbd "C-o") 'hydra-ivy/body)`

**Comment by wolfv6** [comment]
@gcentauri, thanks for clearing up the confusion.

So there is no matching Spacemacs manual for Spacemacs hydra?
Is there some underlying structural issue that makes amending the Spacemacs manual difficult?
Or is it just because no one has got around to writing a Spacemacs hydra manual?

**Comment by gcentauri** [comment]
@wolfv6 - This is the only docs for that layer http://develop.spacemacs.org/layers/+spacemacs/spacemacs-completion/README.html that I can find.  :frowning_face: 

I do think this issue could use some work after spending time looking at what you brought up.  I am not a maintainer, but anyone is welcome to make a PR with suggested changes.  Definitely seems like there should be some documentation around this.  There isn't really anything difficult about updating the docs, but Spacemacs is a very large project with not so many maintainers, so things don't move very fast, especially into the master branch.  If you want to work on building better docs as you go through this issue, I'm sure the community would appreciate it!

**Comment by wolfv6** [comment]
@gcentauri, "M-SPC" is not mentioned in the link you provided.
I will to postpone learning Hydra untill I am more farmiliar with Emacs and Spacemacs.
Thanks for looking into this issue.

**Comment by gcentauri** [comment]
http://develop.spacemacs.org/layers/+completion/ivy/README.html

This is the layer in develop where I found that key binding.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
