### ISSUE TITLE
Shell command run `terminal-notifier` not working correctly as in Emacs -Q or terminal

### ISSUE THREAD

**Issue by tshu-w** [syl20bnr/spacemacs#12239]
#### Description :octocat:
Shell command run terminal-notifier not working correctly as Emacs -Q or in terminal

#### Reproduction guide :beetle:
- brew install terminal-notifier or gem install terminal-notifier
- Start Emacs
- shell-command: `terminal-notifier -sender org.gnu.Emacs -sound default -message "???????"`

*Observed behaviour:* :eyes: :broken_heart:
notification doesn't appear as except, but appear in notifications centre.

*Expected behaviour:* :heart: :smile:
terminal-notifier works correctly as run in emacs -q or terminal
![Screenshot 2019-04-27 at 14 54 11](https://user-images.githubusercontent.com/13161779/56846032-580ff980-68fc-11e9-978c-0a0521865465.png)

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6b03fefe1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

**Comment by Voleking** [comment]
command without `-sender org.gnu.Emacs` work correctly
