### ISSUE TITLE
[Develop] Jump-to-definition is broken in haskell mode with dante

### ISSUE THREAD

**Issue by cjay** [syl20bnr/spacemacs#12238]
#### Description :octocat:
Jump-to-definition is broken in haskell mode with dante once again.

#### Reproduction guide :beetle:
- Start Emacs. Spacemacs develop branch.
- Using haskell layer with `(haskell :variables haskell-completion-backend 'dante)`.
- trigger `spacemacs/jump-to-definition` with `gd` or similar.

*Observed behaviour:* :eyes: :broken_heart:
It does "HELM Dumb jump" instead, which just searches for the string without knowing what a definition is.

*Expected behaviour:* :heart: :smile:
With dante it should do `xref-find-definitions`, which works when run manually.

As a workaround, setting `(spacemacs|define-jump-handlers haskell-mode xref-find-definitions haskell-mode-jump-to-def-or-tag)` in `layers/+lang/haskell/config.el` works, but this may break other backends that are not dante. I couldn't figure out the actual issue. There is an inconsistency between spacemacs-jump-handlers and spacemacs-jump-handlers-haskell-mode in haskell buffers, I'm not sure if that is correct behavior.

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e7e2283cf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git github gpu markdown html neotree org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control osx python javascript
      (haskell :variables haskell-completion-backend 'dante)
      c-c++ colors scala swift themes-megapack)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by magthe** [comment]
Would you check if this is in fact the same as #12289 (except that I use intero instead of dante), i.e. are jump handlers set properly in the _second_ Haskell buffer/file you open?

**Comment by cjay** [comment]
@magthe  Confirmed, `spacemacs-jump-handlers` is different in the second Haskell buffer I open, and jump-to-definition works there. 
In the first buffer it's `(haskell-mode-jump-to-def-or-tag evil-goto-definition dumb-jump-go)`, in the second buffer it's `(xref-find-definitions haskell-mode-jump-to-def-or-tag evil-goto-definition dumb-jump-go)`.

**Comment by magthe** [comment]
@cjay OK, well then it's only a matter of putting together a fix for it.

I'm written comments about two possible routes to solving it, but I'm not familiar enough with emacs to know which route is best... or if there's another, even better, route to take.

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
[haskell] Put the jump handlers straight into the buffer var #12296

@cjay Can you test if it solved this issue.

I tried to test it https://github.com/syl20bnr/spacemacs/pull/12296#issuecomment-498629156
`g d` and `, g g` still opens `HELM Dumb Jump Choices` with the PR applied.
But `, g G` starts opening `HELM Xref Find Definitions` with the PR applied.

I don't know anything about haskell, so I might not it setup correctly.

**Comment by cjay** [comment]
The issue seems to be solved in the current state of the develop branch. `g d` works for me, at least in new-style cabal projects.
