### ISSUE TITLE
spacemacs org mode latex supports Chinese words

### ISSUE THREAD

**Issue by csfreebird** [syl20bnr/spacemacs#12243]
I want to write Chinese words in latex formular, e.g.
`$$\delta(人) = 0.26\;\;\Psi(人)=Start\;\;\delta(人生) = 0.44\;\;\Psi(人生)=Start$$`

After pressing C-c C-x C-l, the formular does not show the Chinese words
![11](https://user-images.githubusercontent.com/870486/56857118-1f276180-699c-11e9-83dc-60ab3820d75a.png)

**Comment by Voleking** [comment]
@csfreebird Please refer to [spacemacs org中得latex fragment里面输入中文preview并不正确](https://emacs-china.org/t/topic/6507)

**Comment by csfreebird** [comment]
@Voleking that does not work.

**Comment by Voleking** [comment]
@csfreebird I added my config, you can refer to it again.
https://emacs-china.org/t/topic/6507/8?u=voleking
