### ISSUE TITLE
unnecessary recentf buffers after opening spacemacs

### ISSUE THREAD

**Issue by collector1871** [syl20bnr/spacemacs#12246]
branch: develop
emacs version: 26.2 (latest one)
completion: helm
booting method: **emacsclient** which is connecting to **emacs --daemon**

hello everyone, 
after opening spacemacs i sometimes have 2 two unnecessary buffers inside the `SPC b b`:
**recentf**
**recentf<2>**

it's important for me to keep buffers list clean, because after whole day of coding i have this list quite big. And it will be much better to keep it small as possible at the boot time.

I have also tried insert this command inside the init config file:
`(kill-buffer "recentf")`
`(kill-buffer "recentf<2>")`

but it's not working

any idea how to kill these two buffers?

btw. i have also:
`(with-eval-after-load 'helm-buffers`
 `(add-to-list 'helm-boring-buffer-regexp-list "*scratch*")`
 `(add-to-list 'helm-boring-buffer-regexp-list "*Messages*")`
 `(add-to-list 'helm-boring-buffer-regexp-list "*spacemacs*"))`
and...
`(kill-buffer "*dotfile-test-results*")`
`(kill-buffer ".spacemacs")`
`(kill-buffer "*spacemacs*")`
`(kill-buffer "*Messages*")`
...and this is working as expected - buffer list is much cleaner after it

**Comment by duianto** [comment]
Could you add your system info `SPC h d s`, and possibly your `.spacemacs`, that might help with tracking down the issue.

Does it happen even if you comment out all your user configurations?

I don't remember ever seeing a recentf buffer on startup, and the dotfile-test-results buffer should probably only appear after syncing the configuration layers `SPC f e R`.

I just tried starting `emacs --daemon` and opening a frame with `emacsclient -c`, both from two separate windows command prompts (cmd.exe)

But I'm not seeing a recentf buffer in HELM Mini `SPC b b`, not even among the hidden buffers `C-c a`.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. dd5240d55)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by collector1871** [comment]
ok, i think i found it.

so basically i have custom spacemacs directory with:
**/home/collector1871/custom/location/to/my/spacemacs**
but i have also script for maintaining (updating, restarting) spac/emacs. And inside this script i am processing someting **.cache** directory. And if we will have **.cache** directory and .recentft in wrong location, then recentf will have bugs

so i had **.cache** directory inside the $HOME/.emacs.d/ , but whole spacemacs files inside other location

after moving whole **.cache** directory into **.spacemacs** i am not seeing this bug.
currently my **$HOME/.emacs.d** is empty

btw i sue chemacs: https://github.com/plexus/chemacs
so this is why i have custom location for spacemacs and doom
