### ISSUE TITLE
Tramp hangs after entering password and can't access debug output

### ISSUE THREAD

**Issue by kenogo** [syl20bnr/spacemacs#12253]
#### Description :octocat:
Tramp hangs after entering password, entire emacs crashes when trying to access debug output.

#### Reproduction guide :beetle:
- Start Emacs
- Be on latest commit of develop branch (issue appeared randomly while I was still on an earlier commit, though, just checked if it's still an issue on develop and it is)
- `M-x helm-find-files /ssh:user@server:` (Same problem with other protocols than ssh)
- Enter password, press enter and wait
- Nothing happens, after a LONG time, it will tell you that something went wrong
- Not an issue with helm, same thing happens with `M-x find-files`
- `M-x set variable tramp-verbose 10`
- Repeat the steps above
- Watch EMACS CRASH when trying to access the debug buffer

*Observed behaviour:* :eyes: :broken_heart:
Literally nothing works past the stage of entering your password. Can't even access the debug log.

*Expected behaviour:* :heart: :smile:
I just want to edit files remotely.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c05c42102)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm auto-completion emacs-lisp git markdown
        (org :variables org-enable-org-journal-support t org-journal-dir "~/Nextcloud/bujo" org-journal-file-format "%Y/%m/%d" org-journal-carryover-items nil org-journal-time-format "")
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by kenogo** [comment]
I'm not sure what `emacs -Q` does, but it still happens when I start emacs like that. Does that mean it's definitely not a spacemacs issue?

**Comment by kenogo** [comment]
Oh ffs, now suddenly emacs starts telling me that `tramp-verbose` doesn't exist, so I can't even replicate the behavior above anymore.

**Comment by kenogo** [comment]
Through sheer luck and messing around, I just figured out that tramp can only connect when the bash prompt is not colored. I'm fairly certain this is not a spacemacs issue at this point, so I'm closing.

**Comment by duianto** [comment]
>I'm not sure what emacs -Q does

**Answer:**
>‘-Q’
‘--quick’
Start Emacs with minimum customizations. This is similar to using ‘-q’, ‘--no-site-file’, ‘--no-site-lisp’, ‘--no-x-resources’, and ‘--no-splash’ together.. 

source: https://www.gnu.org/software/emacs/manual/html_node/emacs/Initial-Options.html

**Comment by kenogo** [comment]
@duianto Well I've read that :P But I'm not sure if that means that nothing related to spacemacs is run

**Comment by duianto** [comment]
Nothing Spacemacs related will load when Emacs is started with: `-Q`
