### ISSUE TITLE
search-ag or search-rg always shows grep

### ISSUE THREAD

**Issue by xster** [syl20bnr/spacemacs#12250]
#### Description :octocat:
Using spacemacs/search-ag or spacemacs/search-rg always ends up using grep.

ag and rg are accessible in path from within emacs (via, for instance, M-m ! ag).

.spacemacs has
dotspacemacs-search-tools '("ag" "rg")

#### Reproduction guide :beetle:
- Start Emacs
- summon spacemacs/search-ag or spacemacs/search-rg via any mechanism
- note that a mini-buffer with 'grep from ...' appears

*Observed behaviour:* :eyes: :broken_heart:
'grep from ...' appears

*Expected behaviour:* :heart: :smile:
'ag from ...' or 'rg from ...' appears

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b26ea277f)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(markdown python shell-scripts yaml ivy auto-completion emacs-lisp osx themes-megapack git ruby treemacs)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by xster** [comment]
umm somewhat obscure but this only happens if I started the daemon via `brew services start emacs` but not if I started it myself via `emacs --daemon`

**Comment by antonalekseev** [comment]
Make sure that `/usr/local/bin/` (or whatever localtion where said tools are installed) is within `PATH` in your `.spacemacs.env` (`SPC f e e`). Probably, Spacemacs is unable to find `rg`/`ag` executables when started without environment of your user's shell.

**Comment by xster** [comment]
This must be it. Thanks! (though I'm somewhat surprised there wasn't an error reported in Messages for failing to find the specific tool that was invoked)

**Comment by duianto** [comment]
@xster If you know how to add an error message when a requested search tool isn't available, then a PR is welcome. Otherwise you could open a new issue. It sounds like a useful feature. Someone else might also find it useful and be able to help.
