### ISSUE TITLE
The default theme doesn't work well with tmux+screen-256color

### ISSUE THREAD

**Issue by c02y** [syl20bnr/spacemacs#12257]
Pay attention to my cusor position and color of the highlight line, all my cursors in the following images are in the same position .

1. GUI emacs:
![gui](https://user-images.githubusercontent.com/2135996/57191729-48775d00-6f5b-11e9-950b-f268be7712d5.png)

2. terminal emacs+tmux without ~/.tmux.conf (TERM: screen) using command `emacs -nw`
![no-tmux-screen](https://user-images.githubusercontent.com/2135996/57191805-2205f180-6f5c-11e9-9a90-969b1166f7ff.png)

3. terminal emacs+tmux without ~/.tmux.conf using command
`env TERM=screen-256color emacs -nw`
![tmux-env](https://user-images.githubusercontent.com/2135996/57191859-b3756380-6f5c-11e9-888b-b308e9098ce3.png)

3. terminal emacs+tmux with ~/.tmux.conf containing only `set -s default-terminal "screen-256color"` using command
`emacs -nw`
![tmux-env](https://user-images.githubusercontent.com/2135996/57191918-680f8500-6f5d-11e9-8707-2123dc90c6f9.png)

4. terminal emacs without tmux using command:
`env TERM=screen-256color emacs -nw`
![no-tmux-env](https://user-images.githubusercontent.com/2135996/57191877-f0415a80-6f5c-11e9-9ba3-cbfdc91bcfb1.png)

**Conclusion**:
1. The themes of "GUI emacs" and "terminal emacs without tmux but with screen-256color enabled" are bascially the same.
2. Once I use tmux, the backgrounds of terminal emacs will be different
3. I can see the highlighed line(cursor line) when using tmux without screen-256color
4. once I use tmux + screen-256color(no matter pass it in command line or set it in ~/.tmux.conf), the highlighed line(cursor) will be invisible, besides, if I select any text, the mark is invisiable.

Normally `set -s default-terminal "screen-256color"` is in my ~/.tmux.conf, this is the result of aftering using tmux+fish for several years, so this is the best configuration, but terminal spacemacs doesn't work with tmux+screen-256color, how can I fix it?

**FYI**:
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw scroll bars) of 2019-03-18
Spacemacs develop branch
xfce4-terminal 0.6.3
Ubuntu 16.04.6 LTS
tmux v2.8

**Comment by c02y** [comment]
Don't know why I changed an environment, it works again, the highlighed line in `SPC b b` and color of marked text work as expected again.

**FYI**:
GNU Emacs 26.2 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.8)
Spacemacs develop branch
Yakuake v3.0.5
openSUSE Tumbleweed
tmux v2.9

**Comment by KPLauritzen** [comment]
I'm having the same issue. What did you do to solve it?

**Comment by c02y** [comment]
@KPLauritzen I haven't solve it, I just switched to another environment, check the two FYI parts.

**Comment by c02y** [comment]
@KPLauritzen 
I solved it by using the following configuration in user-config
~~~
  (with-eval-after-load 'helm
    ;; change the color of current highlight line
    (set-face-background 'hl-line "839496")
    ;; change the color of selected item in helm list
    (set-face-background 'helm-selection "839496")
    )
~~~

**Comment by sdwolfz** [comment]
Have you tried following the instructions from this guide? 
https://github.com/syl20bnr/spacemacs/wiki/Terminal

**Comment by c02y** [comment]
@sdwolfz Yes, the problem of colors is fixed. 

But another serious probelm happens again(I mentioned this problem in here https://emacs.stackexchange.com/questions/50546/my-terminal-emacs-displays-weird-characters-u2506-for-unvisiable-characters-i)
Emacs in terminal
![terminal](https://user-images.githubusercontent.com/2135996/58064400-7f34b080-7bb4-11e9-92cd-ba9cb7148bee.png)

Vm in terminal:
![terminal-vim](https://user-images.githubusercontent.com/2135996/58064409-8956af00-7bb4-11e9-9949-37e7c486fd85.png)

**Comment by sdwolfz** [comment]
Hmm... I think you need to select a powerline font for your terminal: https://github.com/powerline/fonts.

**Comment by c02y** [comment]
I found out that this is the problem of the variable LANG,
~~~
$ echo $LANG
en_US
~~~

But
~~~
$ cat /etc/locale.conf
LANG=en_US.UTF-8
$ localctl status
System Locale: LANG=en_US.UTF-8
...
~~~
After I export the LANG to en_US.UTF-8, and problem is gone, and I don't have to do anything from the https://github.com/syl20bnr/spacemacs/wiki/Terminal

I don't know why `echo $LANG` returns `en_US`. This OS is managed my administrator in my company and a lot of files have been changed, and I've been using Linux for several years, and this is the first time this problem happens to me.

Anyway, if anyone has the same problem, please change your LANG variable to `en_US.UTF-8`.

**Comment by sdwolfz** [comment]
Thanks @c02y, I've added the exports to the wiki page for future reference.

**Comment by c02y** [comment]
@sdwolfz I'm sorry, this is not perfect, changing the environment variable of LC_ALL/LANG only solved the issue I mention at https://github.com/syl20bnr/spacemacs/issues/12257#issuecomment-494220038 

The issue (highlight faces) I posted at the beginning of this page is back again.

And I use MobaXterm to access two OS, one is openSUSE, one is RHEL7, besides, there are the following info I need to mention:
0. MobaXterm configs are the same
1. Both spacemacs configs are the same
2. Both tmux configs are the same including TERM
3. Both shell configs are the same(fish shell)
4. spacemacs with configs and vanilla emacs with configs work in openSUSE, not work in RHEL7

So this is not the problem of emacs or spacemacs or tmux , this is problem of my RHEL7 itself.

I reopen this issue, and will update it.
