### ISSUE TITLE
org-drill has org-outline-overlay-data error

### ISSUE THREAD

**Issue by Anton-Latukha** [syl20bnr/spacemacs#12252]
#### Description :octocat:
`org-drill` function from the `org-plus-contrib` was not working.

#### Reproduction guide :beetle:
- Add `org-drill` to the `org-modules` list
- Restart Emacs
- Open any Org file, add `:drill:` tag to any entry inside (or use

*Observed behaviour:* :eyes: :broken_heart:
Getting an error:
```
helm-M-x: Symbol’s function definition is void: org-outline-overlay-data
```

*Expected behaviour:* :heart: :smile:
Start the time spaced learning of flash cards though org-drill.

**Comment by Anton-Latukha** [comment]
Solution is similar to: https://github.com/syl20bnr/spacemacs/issues/11801

You need to delete pre-compiler org elisp binaries:
```shell
cd ~/.emacs.d/elpa/<your_emacs_ver>/<spacemacs_branch>
find org*/*.elc -print0 | xargs -0 rm
```
And restart Emacs, open org-file and try `org-drill` again.

**Comment by megamos** [comment]
I got a bit confused by the path your trying to go to. Linked solution #11801 helped out. Did this and it worked:
`cd ~/.emacs.d/elpa/`
`find org*/*.elc -print0 | xargs -0 rm` 
"and then inside spacemacs I ran `spacemacs/recompile-elpa` "
