### ISSUE TITLE
unable to use electric-operator-add-rules-for-mode in spacemacs

### ISSUE THREAD

**Issue by c02y** [syl20bnr/spacemacs#12269]
#### Description :octocat:
I tried to use electric-operator in spacemacs

I put electric-operator in dotspacemacs-additional-packages, and put
~~~
(add-hook 'c-mode-common-hook #'electric-operator-mode)
(electric-operator-add-rules-for-mode
'c-mode
(cons "<>" "<> ")
(cons "<" " < ")
(cons ">" " > ")
(cons ";" "; ")
(cons "++" "++"))
~~~
in dotspacemacs/user-config, but after I start emacs, it says 

~~~
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: electric-operator-add-rules-for-mode
~~~
in *Message* buffer and I am not able to use the operators defined in electric-operator-add-rules-for-mode in c-mode file. electric-operator-mode is enabled and I am able to use built-in operators.

#### Reproduction guide :beetle:
- Start Emacs
- Check the *Message* buffer, there is an error in it, and open a C file, unable to use operators defined in electric-operator-add-rules-for-mode

*Expected behaviour:* :heart: :smile:
Able to use electric-operator-add-rules-for-mode

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a385f17ef)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown vimscript
		  (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
		  better-defaults emacs-lisp python git helm multiple-cursors org spell-checking syntax-checking semantic shell-scripts treemacs evil-commentary
		  (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
		  (c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-ccls c-c++-lsp-cache-dir "~/.emacs.d/.cache/lsp-ccls")
		  lsp dap)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD

**Comment by duianto** [comment]
Try wrapping the rules with: `with-eval-after-load`
```
    (with-eval-after-load 'electric-operator-mode
      (electric-operator-add-rules-for-mode
       'c-mode
       (cons "<>" "<> ")
       (cons "<" " < ")
       (cons ">" " > ")
       (cons ";" "; ")
       (cons "++" "++")))
```
then the rules might only be applied once your in a buffer where `electric-operator-mode` is enabled.

**Comment by c02y** [comment]
Thanks, I copied the config directly from my old .emacs.d/init.el, it doesn't need with-eval-after-load.

Anyway, it works, but don't know why some of operators won't work as defined.

**Comment by duianto** [comment]
I don't know if it's because Spacemacs lazy-loads a lot of stuff. Maybe the `electric-operator` package only gets loaded when it's used.

**Comment by c02y** [comment]
Can I disable lay-load for a specific package?

**Comment by c02y** [comment]
No, actually all defiend operators in electric-operator-add-rules-for-mode don't work at all, only builtin operators works as expected.

**Comment by c02y** [comment]
Change 
~~~
(with-eval-after-load 'electric-operator-mode
~~~
to
~~~
(with-eval-after-load "electric-operator"
~~~
now `electric-operator-add-rules-for-mode` works an expected.
