### ISSUE TITLE
table.el not support major mode leader key

### ISSUE THREAD

**Issue by haormj** [syl20bnr/spacemacs#12262]
#### Description :octocat:
`table.el` not support  major mode leader key `,`, must use `C-c C-c` every time, also I hope it can support transient state. Thanks anyway :-)

#### Reproduction guide :beetle:
- Start Emacs
- Create `temp.org`
- Create `org-mode` table
- Convert to `table.el` by `, t c`
- Use `C-c C-c` operate `table.el` 

*Observed behaviour:* :eyes: :broken_heart:
- Must use `C-c C-c` every time
- `C-c C-c` not work when cursor not in table

*Expected behaviour:* :heart: :smile:
- Support major mode leader key `,`
- Support transient state

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2441f36a7)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(html yaml
      (python :variables python-backend 'anaconda python-enable-yapf-format-on-save t python-sort-imports-on-save t)
      (go :variables go-format-before-save t go-tab-width 4 godoc-at-point-function 'godoc-gogetdoc gofmt-command "goimports")
      (helm :variables helm-enable-auto-resize t helm-no-header t helm-position 'top helm-use-fuzzy 'source)
      (auto-completion :variables auto-completion-idle-delay 0.05 auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip t)
      chinese
      (better-defaults :variables better-defaults-move-to-end-of-code-first t)
      emacs-lisp git markdown multiple-cursors
      (treemacs :variables treemacs-use-follow-mode nil)
      (org :variables org-enable-org-journal-support t org-want-todo-bindings t org-enable-github-support t org-agenda-files
           '("~/agenda/gtd.org")
           org-journal-dir "~/agenda/journal")
      (shell :variables shell-default-shell 'term shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/bash")
      syntax-checking xclipboard json)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS NOTIFY GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS

#### Backtrace :paw_prints:
It's very easy to reproduce

**Comment by Miciah** [comment]
> * Use `C-c C-c` operate `table.el`

What does <kbd>C-c C-c</kbd> do? It just printed `Use ‘C-c '’ to edit table.el tables` when I tried it.  Anyway, <kbd>, ,</kbd> should perform the same action as <kbd>C-c C-c</kbd> (and if you want to use the leader key instead of <kbd>C-c '</kbd>, try <kbd>, '</kbd>).

**Comment by haormj** [comment]
@Miciah thanks for your reply

1. <kbd>, t c</kbd> convert to `table.el` table
2. <kbd>, '</kbd> edit `table.el` table
3. <kbd>C-c C-c</kbd> operate `table.el` table
![Screenshot from 2019-05-16 07-02-52](https://user-images.githubusercontent.com/18750674/57815117-ac462500-77a8-11e9-9605-8a8f8ba1cacb.png)
e.g. I want to span cell, I must use <kbd>C-c C-c *</kbd> rather than <kbd>, *</kbd>
4. <kbd>, c</kbd> or <kbd>, ,</kbd> exit editing `table.el` table
