### ISSUE TITLE
Can we fix the bug of "golang support" asap ?

### ISSUE THREAD

**Issue by johnnyjpixy** [syl20bnr/spacemacs#12263]
I noticed golang support cannot work at all. Can we fix it asap ?

**Comment by irfn** [comment]
@johnnyjpixy what you noticed is probably to do with `go mod`. go as a community has switched to `gopls` https://github.com/golang/go/wiki/gopls based on  https://langserver.org/

Emacs already has great support via `lsp-mode`

add this in the go-mode hook. 

`(use-package lsp-mode
    :commands lsp
    :config
    (lsp-register-client
     (make-lsp-client :new-connection (lsp-stdio-connection "gopls")
                      :major-modes '(go-mode)
                      :server-id 'gopls)))`


I guess the go layer should move to lsp-mode for `go-mod` and only use `gocode` for older go versions.

**Comment by duianto** [comment]
@irfn A note on markdown formatting. If you add three backticks `` ``` `` on the line before and on the line after a code snippet then it will appear with the correct indentation. Like this:
```
(use-package lsp-mode
    :commands lsp
    :config
    (lsp-register-client
     (make-lsp-client :new-connection (lsp-stdio-connection "gopls")
                      :major-modes '(go-mode)
                      :server-id 'gopls)))
```
which makes it easier to read and copy.

**Comment by robbyoconnor** [comment]
https://github.com/syl20bnr/spacemacs/issues/11217

Please don't make new issues and search before you create a new one.
