### ISSUE TITLE
Persp-mode bug with layouts containing same-name files

### ISSUE THREAD

**Issue by DoomsdayDevice** [syl20bnr/spacemacs#12275]
#### Description :octocat:
Persp-mode bug with layouts containing same-name files in different folders

#### Reproduction guide :beetle:
- Start Emacs
- create two files with the same name in two different folders
- open them at the same time in emacs
- they will have postfixes with their folder names: `same_file.html <folder-one>`, `same_file.html <folder-two>`

- save the layout with one of the buffers to a file with SPC-l-L
- load the layout in a different emacs session

*Observed behaviour:* :eyes: :broken_heart:
- the buffer with that file shows *scratch* 
- (apparently it points to `same_file.html <folder-one>` while the new buffer's name is just `same_file.html`)

*Expected behaviour:* :heart: :smile:
- the buffer with that file should display its contents

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python markdown javascript html php helm auto-completion emacs-lisp git react org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by duianto** [comment]
This seems to be a duplicate of this issue:
Problem opening different files with same filename in different layouts #10183

It's been fixed on the `develop` branch.

**Comment by DoomsdayDevice** [comment]
I've seen that one. It's not the same as mine though. Mine is about _loading_ the layout from a file. But i'll switch to develop a bit later and see if that fix solved my problem too

**Comment by DoomsdayDevice** [comment]
So I've switched to the `develop` branch, but the problem persists. 
For now just using a new instance of emacs for each layer is a good enough workaround I guess. Hopefully I'll find some time later on to fix it myself
