### ISSUE TITLE
scala is not loading

### ISSUE THREAD

**Issue by zxcvbn97** [syl20bnr/spacemacs#1228]
Hi there,

I'm using the latest version of spacemacs with scala layer.
However, a scala mode does not load for my .scala file.
Can you please have a look? 
![image](https://cloud.githubusercontent.com/assets/9757976/7214109/03c6b68a-e560-11e4-9aab-cc6054a88dda.png)

Thank you,

**Comment by zxcvbn97** [comment]
@ chrisbarrett

**Comment by syl20bnr** [comment]
(you put a space) cc @chrisbarrett

**Comment by syl20bnr** [comment]
@zxcvbn97 You can try the gitter chat also.

**Comment by syl20bnr** [comment]
@zxcvbn97 any news an this ?

**Comment by TheBB** [comment]
Since nobody has been able to reproduce this, and @zxcvbn97 is not responding, I'm closing this for now. Feel free to reopen if this is still a problem.
