### ISSUE TITLE
Haskell: jump handlers aren't correct in the first buffer opened

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#12289]
#### Description :octocat:
Jump handlers aren't set properly for the first file opened in Haskell mode.

#### Reproduction guide :beetle:
- Configure Spacemacs with the haskell layer using intero
- Start Emacs
- Open one Haskell file
- Inspect `spacemacs-jump-handlers`
- Open a second Haskell file
- Inspect `spacemacs-jump-handlers`

*Observed behaviour:* :eyes: :broken_heart:
The (buffer-local) variable `spacemacs-jump-handlers` is different in the two buffers, in particular `intero-goto-definition` is present only in the second buffer's variable.

*Expected behaviour:* :heart: :smile:
The two buffers' value for `spacemacs-jump-handlers` should be the same.

#### Possible cause

Upon inspecting the haskell layer I noticed that `spacemacs-jump-handlers-haskell-mode` is modified in functions called from the mode hook. I'm guessing that the buffer variable `spacemacs-jump-handlers` is set based on the value of `spacemacs-jump-handlers-haskell-mode` prior to the mode hook being executed. At least that would explain why only the first buffer gets the wrong value but all following buffers have the correct value.

Unfortunately I'm not familiar enough with the load sequence to know exactly where the modifications to `spacemacs-jump-handlers-haskell-mode` should be set to get the desired behaviour. If I get a suggestion I'm more than happy to put together a patch.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e8e4c6338)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash docker evil-commentary evil-snipe git github gtags
 (helm :variables helm-no-header t)
 mu4e restclient
 (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
 syntax-checking
 (clojure :variables clojure-enable-sayid t clojure-enable-clj-refactor t)
 emacs-lisp
 (haskell :variables haskell-completion-backend 'intero)
 shell-scripts graphviz html json latex markdown
 (org :variables org-enable-reveal-js-support t org-enable-github-support t)
 spacemacs-org
 (sql :variables sql-auto-indent nil)
 pandoc terraform yaml archlinux clipboard-fix)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by magthe** [comment]
Once possible work-around is to modify `spacemacs-jump-handlers` in the hook functions, i.e. to make this sort of change for each of the setup functions

```diff
diff --git a/layers/+lang/haskell/funcs.el b/layers/+lang/haskell/funcs.el
index 92f1ddc6d..5f3cf94ff 100644
--- a/layers/+lang/haskell/funcs.el
+++ b/layers/+lang/haskell/funcs.el
@@ -100,7 +100,7 @@
 (defun spacemacs-haskell//setup-intero ()
   (interactive-haskell-mode)
   (intero-mode)
-  (add-to-list 'spacemacs-jump-handlers-haskell-mode 'intero-goto-definition))
+  (add-to-list 'spacemacs-jump-handlers 'intero-goto-definition))
 
 (defun spacemacs-haskell//setup-intero-company ()
   (spacemacs|add-company-backends
```

**Comment by magthe** [comment]
This might be a better fix.

```diff
diff --git a/layers/+lang/haskell/funcs.el b/layers/+lang/haskell/funcs.el
index 92f1ddc6d..db476c7bf 100644
--- a/layers/+lang/haskell/funcs.el
+++ b/layers/+lang/haskell/funcs.el
@@ -82,8 +82,7 @@
 ;; Dante functions
 
 (defun spacemacs-haskell//setup-dante ()
-  (dante-mode)
-  (add-to-list 'spacemacs-jump-handlers-haskell-mode 'xref-find-definitions))
+  (dante-mode))
 
 (defun spacemacs-haskell//setup-dante-company ()
   (spacemacs|add-company-backends
@@ -99,8 +98,7 @@
 
 (defun spacemacs-haskell//setup-intero ()
   (interactive-haskell-mode)
-  (intero-mode)
-  (add-to-list 'spacemacs-jump-handlers-haskell-mode 'intero-goto-definition))
+  (intero-mode))
 
 (defun spacemacs-haskell//setup-intero-company ()
   (spacemacs|add-company-backends
diff --git a/layers/+lang/haskell/packages.el b/layers/+lang/haskell/packages.el
index 70c8f9071..61475c361 100644
--- a/layers/+lang/haskell/packages.el
+++ b/layers/+lang/haskell/packages.el
@@ -106,6 +106,7 @@
       (spacemacs|diminish intero-mode " λ" " \\")
       (advice-add 'intero-repl-load
                   :around #'haskell-intero//preserve-focus)
+      (add-to-list 'spacemacs-jump-handlers 'intero-goto-definition)
 
       (dolist (mode haskell-modes)
         (spacemacs/set-leader-keys-for-major-mode mode
@@ -140,6 +141,7 @@
     :defer t
     :config
     (progn
+      (add-to-list 'spacemacs-jump-handlers-haskell-mode 'xref-find-definitions)
       (dolist (mode haskell-modes)
         (spacemacs/set-leader-keys-for-major-mode mode
           "ht" 'dante-type-at
```

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
[haskell] Put the jump handlers straight into the buffer var #12296
