### ISSUE TITLE
multiple-cursors layer is broken

### ISSUE THREAD

**Issue by idanko** [syl20bnr/spacemacs#12282]
#### Description :octocat:
multiple-cursors layer is unreachable and the feature is unabaliable

#### Reproduction guide :beetle:
- Start Emacs
- Open the .spacemacs dotfile
- Add multiple-cursors layer the existing dotspacemacs-configuration-layers (see the Layers)

multiple-cursors becomes unavailable or non existent

*Observed behaviour:* :eyes: :broken_heart:
After adding multiple-cursors layer and restart emacs the new layer will be installed and accessible

*Expected behaviour:* :heart: :smile:
`Warnings - Unknown layer multiple-cursors declared in dotfile` is popped up on the spacemacs home

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html markdown javascript
      (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
      (go :variables go-use-golangci-lint t go-tab-width 4)
      ivy emacs-lisp git)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by idanko** [comment]
Update: I found that multiple-cursors and evil-mc are shipped with spacemacs even when the multiple-cursors layer isn't specified. Besides that, g-r-x mapping feature becomes available if evil-mc-mode turned on manually, looks like strange a bit (I've just gotten familiar with spacemace, so maybe it by design). Anyway it quite controversial what the documentation [says](http://develop.spacemacs.org/layers/+misc/multiple-cursors/README.html) about the feature's installation

**Comment by sei40kr** [comment]
@idanko 
`multiple-cursors` layer is still not merged to `master` branch, and the doc you mentioned is for `develop` branch.

**Comment by sei40kr** [comment]
You can use `multiple-cursors` layer by switching to `develop` branch, but note that it's unstable
.

**Comment by idanko** [comment]
@sei40kr Is there any up today information regarding layers or features the community is working on. For instance, [Go layer](http://develop.spacemacs.org/layers/+lang/go/README.html) is under the developer URI (according to the provided link) however it's available on the master
