### ISSUE TITLE
The custimized value "evil-respect-visual-line-mode" seems totally disrespected.

### ISSUE THREAD

**Issue by fulgenssequar** [syl20bnr/spacemacs#12284]
According to the introduction, editing this value should swap the behavior of going up and down in the visual lines or real lines, which very is useful to write documents.
So I  just pressed "C-h v" to look up the value "evil-respect-visual-line-mode", changed it, and apply and save, and restart the spacemacs. When I checked the value again, it is actually modified, so everything seems fine.
However, when I navigated the truncated lines using j and k, the cursor still goes up and down the whole lines, and only "gj" and "gk" fulfilled my purpose, which seems that the modification ot this value changed nothing.
So is there anything important I neglected, or my understanding ot its funciton is totally wrong?

**Comment by yuhan0** [comment]
You have to set this particular variable before Evil is initialized, i.e. in `dotspacemacs/user-init`

**Comment by fulgenssequar** [comment]
> You have to set this particular variable before Evil is initialized, i.e. in `dotspacemacs/user-init`

Still doesn't work, but everything else behaves strangely too and even collapsed several times. I'm resorting to the original Emacs now. Thx
