### ISSUE TITLE
Mouse wheel scrolling with control held scrolls window, rather than zooming the frame

### ISSUE THREAD

**Issue by DMRobertson** [syl20bnr/spacemacs#12293]
#### Description :octocat:
Mouse wheel scrolling with control held scrolls window, rather than zooming the frame.

#### Reproduction guide :beetle:
- Start Emacs
- Open a buffer with text inside which cannot be displayed within an entire window (e.g. open your spacemacs dotfile)
- Hold control and scroll the mouse wheel up and down a few times

*Observed behaviour:* :eyes: :broken_heart:
- The window scrolls up and down, just as if control was not held.

*Expected behaviour:* :heart: :smile:
Judging by the following lines from the end of [spacemacs-ui-visual/packages.el](https://github.com/syl20bnr/spacemacs/blob/c7a103a772d808101d7635ec10f292ab9202d9ee/layers/%2Bspacemacs/spacemacs-ui-visual/packages.el), I think the intention is that this increases the font size, just like a web browser would.

```
(defun spacemacs-ui-visual/init-zoom-frm ()
      ;; ...
      ;; Font size, either with ctrl + mouse wheel
      (global-set-key (kbd "<C-wheel-up>") 'spacemacs/zoom-frm-in)
      (global-set-key (kbd "<C-wheel-down>") 'spacemacs/zoom-frm-out))))
```

I can see these bindings in the "Helm descbinds" popup (`SPC ?`). I think the problem instead is that scrolling the wheel generates a different kind of event. If I describe variable `mouse-wheel-up-event` (`C-h v mouse-wheel--up-event RET`) I can see that it's value is `mouse-5`; similarly `mouse-wheel-down-event` is `mouse-4`.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7a9c455)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking auto-completion
                (helm :variables helm-ff-lynx-style-map nil)
                (org :variables org-todo-keywords
                     '((sequence "TODO" "WIP" "REVIEW" "DONE"))
                     org-hide-leading-stars t org-bullets-bullet-list
                     '("*"))
                (c-c++ :variables c-c++-backend 'rtags c-c++-default-mode-for-headers 'c++-mode)
                emacs-lisp html javascript json markdown python shell-scripts typescript yaml git version-control imenu-list salt systemd search-engine)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
### Issue observed in Ubuntu 18.04 (Virtualbox guest, with win 10 as host)

`C-h l` (lower case L) shows:
>   \<C-down-mouse-5> \<C-mouse-5>               ;; mwheel-scroll
 \<C-double-down-mouse-5> \<C-double-mouse-5> ;; mwheel-scroll
 \<C-triple-down-mouse-5> \<C-triple-mouse-5> ;; mwheel-scroll
 \<C-triple-down-mouse-5> \<C-triple-mouse-5> ;; mwheel-scroll
 \<C-triple-down-mouse-5> \<C-triple-mouse-5> ;; mwheel-scroll
 \<C-triple-down-mouse-5> \<C-triple-mouse-5> ;; mwheel-scroll
 \<C-down-mouse-4> \<C-mouse-4>               ;; mwheel-scroll
 \<C-double-down-mouse-4> \<C-double-mouse-4> ;; mwheel-scroll
 \<C-triple-down-mouse-4> \<C-triple-mouse-4> ;; mwheel-scroll
 \<C-triple-down-mouse-4> \<C-triple-mouse-4> ;; mwheel-scroll
 \<C-triple-down-mouse-4> \<C-triple-mouse-4> ;; mwheel-scroll
 \<C-triple-down-mouse-4> \<C-triple-mouse-4> ;; mwheel-scroll

#### Without Ctrl held down

> \<down-mouse-5> \<mouse-5>                   ;; mwheel-scroll
 \<double-down-mouse-5> \<double-mouse-5>     ;; mwheel-scroll
 \<triple-down-mouse-5> \<triple-mouse-5>     ;; mwheel-scroll
 \<triple-down-mouse-5> \<triple-mouse-5>     ;; mwheel-scroll
 \<triple-down-mouse-5> \<triple-mouse-5>     ;; mwheel-scroll
 \<triple-down-mouse-5> \<triple-mouse-5>     ;; mwheel-scroll
 \<down-mouse-4> \<mouse-4>                   ;; mwheel-scroll
 \<double-down-mouse-4> \<double-mouse-4>     ;; mwheel-scroll
 \<triple-down-mouse-4> \<triple-mouse-4>     ;; mwheel-scroll
 \<triple-down-mouse-4> \<triple-mouse-4>     ;; mwheel-scroll
 \<triple-down-mouse-4> \<triple-mouse-4>     ;; mwheel-scroll


#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e22cfadf1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(emacs-lisp git ivy multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP



### It works as expected in Windows 10 Version 1803

The text size changes, but the emacs frame also changes size (but this might be a windows 10 issue, win 10 added 7px invisible borders on the left, right and bottom edges of most application windows, so Emacs might not be detecting the correct frame size).

`C-h l` (lower case L) shows:
>  \<C-wheel-down> [spacemacs/zoom-frm-out]
 \<C-double-wheel-down> [spacemacs/zoom-frm-out]
 \<C-triple-wheel-down> [spacemacs/zoom-frm-out]
 \<C-triple-wheel-down> [spacemacs/zoom-frm-out]
 \<C-triple-wheel-down> [spacemacs/zoom-frm-out]
 \<C-wheel-down> [spacemacs/zoom-frm-out]
 \<C-wheel-up> [spacemacs/zoom-frm-in]
 \<C-double-wheel-up> [spacemacs/zoom-frm-in]
 \<C-triple-wheel-up> [spacemacs/zoom-frm-in]
 \<C-triple-wheel-up> [spacemacs/zoom-frm-in]
 \<C-triple-wheel-up> [spacemacs/zoom-frm-in]
 \<C-triple-wheel-up> [spacemacs/zoom-frm-in]

#### Without Ctrl held down

> \<wheel-down> [mwheel-scroll]
 \<double-wheel-down> [mwheel-scroll]
 \<triple-wheel-down> [mwheel-scroll]
 \<triple-wheel-down> [mwheel-scroll]
 \<triple-wheel-down> [mwheel-scroll]
 \<wheel-up> [mwheel-scroll]
 \<double-wheel-up> [mwheel-scroll]
 \<triple-wheel-up> [mwheel-scroll]
 \<triple-wheel-up> [mwheel-scroll]
 \<triple-wheel-up> [mwheel-scroll]

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e22cfadf1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey emacs-lisp git ivy html multiple-cursors org
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
