### ISSUE TITLE
SPC m is undefined in org-mode

### ISSUE THREAD

**Issue by c6401** [syl20bnr/spacemacs#12308]
#### Description :octocat:
After I updated spacemacs, "SPC m" doesn't work.
I've seen https://github.com/syl20bnr/spacemacs/issues/8106 but I have org enabled in my .spacemacs.

#### Reproduction guide :beetle:
On Ubuntu 19.04 without spacemacs installed (no ~/.emacs.d, no .spacemacs)
- `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d` (now it installs spacemacs 0.200.13@26.1)
- start emacs
- chose default options (vim, spacemacs, helm)
- wait for installation to finish
- close emacs
- uncomment org in .spacemacs like so (that's the only change in file):
```
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     helm
     ;; auto-completion
     ;; better-defaults
     emacs-lisp
     ;; git
     ;; markdown
     org                          ;; <------------- here I uncommented "org"
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     ;; syntax-checking
     ;; version-control
     )
```
- start emacs
- wait for installation to finish
- you'll see "Error (use-package): org-projectile/:config: Symbol’s function definition is void: org-projectile:per-repo" which is not the subject of this report
- (optionally, doesn't affect SPC m problem) close emacs and run `find ~/.emacs.d/elpa -name "*elc" -delete`
- open some .org file
- SPC m doesn't work: "SPC m is undefined"

*Observed behaviour:* :eyes: :broken_heart:
"SPC m is undefined"

*Expected behaviour:* :heart: :smile:
SPC m works

**Comment by thanhvg** [comment]
Can you try dev branch. Master branch is dead don't use it.

**Comment by c6401** [comment]
Thank you, yes it does work.
Um, would be awesome to have some info about this at least in README.md since it's kinda obscure.

**Comment by chespinoza** [comment]
I'm having the same issue, is needed to get the dev branch to get this working properly yet?

**Comment by shuaiwang88** [comment]
switching to dev branch does not work for me at mac, ubutun 18.04, nor manjaro.

**Comment by chshr** [comment]
Does not work for me at dev branch, on windows 7 x64

**Comment by e-monson** [comment]
Dev branch doesn't work for me, either. I'm pretty much ready to give up on this project, yet again. Every time I try to set up and use Spacemacs again, I run into something like this at *every single turn*. I honestly don't understand how anyone has the time or patience to get Spacemacs running.

**Comment by duianto** [comment]
I just cloned a fresh copy of the develop branch of Spacemacs,
from the home directory in the terminal (linux) and command prompt (windows), with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```
### In a `.org` file

#### Before uncommenting the `org` layer
`SPC m is undefined`

#### After uncommenting `org` and restarting Spacemacs
`SPC m` opens the major mode commands list of key bindings.

### System Info
<details><summary>
PopOS 20.04, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d65c09165)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors org treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d65c09165)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors org treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by gratuxri** [comment]
Same problem here on develop branch.
Workaround: rm -rf ~/.emacs.d/.cache ; rm -rf ~/.emacs.d/elpa ; emacs
