### ISSUE TITLE
LSP :: ts-ls has exited (exited abnormally with code 127)

### ISSUE THREAD

**Issue by jaaso** [syl20bnr/spacemacs#12309]
#### Description :octocat:
LSP :: ts-ls has exited (exited abnormally with code 127) 

#### Reproduction guide :beetle:
- Start Emacs
lsp
 (javascript :variables
                 node-add-modules-path t
                 javascript-backend 'lsp
                 javascript-fmt-tool 'prettier
                 js2-basic-offset 2
                 js-indent-level 2 )

     (flow :variables
           javascript-backend 'lsp
           node-add-modules-path t
                 javascript-fmt-tool 'prettier
                 js2-basic-offset 2
                 js-indent-level 2 )
     (typescript :variables
                 typescript-backend 'lsp
                 node-add-modules-path t
                 typescript-fmt-on-save t
                 typescript-fmt-tool 'typescript-formatter)

I am using spacemacs from develop branch

#### Backtrace :paw_prints:
```
![image](https://user-images.githubusercontent.com/4284477/57776119-f5519700-771e-11e9-819e-8eb9d33d701d.png)

**Comment by jaaso** [comment]
Just find out that lsp (javascript) is working correctly if I use emacs in console, with emacs version 26.1.

**Comment by Zxrcoming** [comment]
yeah, I have the same problem using emacs 26.3, with console lauch is ok, but it's not convient, did you solved it just using GUI spacemacs to make the lsp work.
