### ISSUE TITLE
Typing two asterisk characters in markdown-mode mangles text before point

### ISSUE THREAD

**Issue by yusefnapora** [syl20bnr/spacemacs#12305]
#### Description :octocat:
Typing two asterisk characters in markdown-mode mangles text before point

#### Reproduction guide :beetle:
- Start Emacs
- Open a buffer in markdown-mode with the markdown layer installed
- Enter some text containing double quotes. On the following line, type two `*` characters.

Before typing asterisks:

```markdown
Some "example text"
Another line, about to type stars 
```

*Observed behaviour:* :eyes: :broken_heart:
The second quote character in the first line is replaced with `**`:

```markdown
Some "example text**
Another line, about to type stars **
```

*Expected behaviour:* :heart: :smile:
The first line remains unaltered, e.g.

```markdown
Some "example text"
Another line, about to type stars **
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b26ea277f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm markdown multiple-cursors treemacs)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Notes:

Before filing this issue, I tried installing markdown-mode into vanilla Emacs.
It does not have the issue.

Next, I removed my custom spacemacs config and added the markdown layer to a default config without making any other changes. The weird behavior is present, so it seems this is either an issue with the markdown layer or a strange interaction between markdown-mode and another default spacemacs package.

Also, double quotes don't seem to be the only affected characters.

A few more examples:

```
some "text**
**

more (text**
**

single quotes 'also**
**

maybe any `closing element**
**
```

**Comment by duianto** [comment]
Confirmed

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 322528ca8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown multiple-cursors
            (org :variables org-enable-org-journal-support t)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
It might be `org-tbl` related.

After commenting out all but the markdown layer and restarting Spacemacs.

When a `.md` file is opened, then this message appears:
>File mode specification error: (void-function orgtbl-mode)

In this state the issue does not occur, and if one checks the command that's called when `*` is pressed:
`C-h k *`, it shows: `self-insert-command`

It seems like org hasn't been loaded yet, because if a org command is called, for example:
`M-x` `org-version`

Now if a `.md` file is opened, then the void message doesn't appear, and the issue occurs again.

Pressing: `*` calls: `orgtbl-self-insert-command`

**Comment by Miciah** [comment]
Actually, it seems to be related to smartparens.  I can reproduce the issue with smartparens enabled, but I cannot after I disable smartparens by pressing <kbd>SPC t p</kbd>.

**Comment by yusefnapora** [comment]
@Miciah that seems to be it! thanks for figuring that out - I can live without smartparens, but that was driving me crazy :)

**Comment by duianto** [comment]
Confirmed, disabling smartparens stops the issue.  Thanks Miciah for finding the source.
