### ISSUE TITLE
Typing `f` in terminal line-mode breaks command

### ISSUE THREAD

**Issue by c089** [syl20bnr/spacemacs#12303]
#### Description :octocat:
Typing `f` while using a terminal in line-mode triggers some kind of terminal
function, breaking the command to be executed.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC SPC ansi-term RET`
- `echo abcdef RET`
- `C-c C-j` to switch to `line-mode`
- `echo abcde`

*Observed behaviour:* :eyes: :broken_heart:

The first echo inputs and executes as expected, but when typing `f` after
switching to line-mode, the cursor jumps, and the shell state switches from:

```
bash-3.2$ echo abcde<CURSOR>
```

to:

```
<CURSOR>bash-3.2$ 
fecho abcde
```

Sometimes it seems to replace completely different text, which looks like it
might be coming from my shells history.

Note this seems independent of the shell configuration and even shell used, the
same issue I could reproduce with bash, zsh and fish without custom
configuration. It also happens with both `ansi-term` and `term`.

*Expected behaviour:* :heart: :smile:

`echo abcdef` is executed by the shell as usual.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ada180786)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby
 (elm :variables elm-format-on-save t)
 helm auto-completion better-defaults emacs-lisp git haskell html javascript markdown org ranger react semantic
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking typescript version-control yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by antonalekseev** [comment]
It seems that `evil-escape` default key sequence `fd` triggers as `(setq evil-escape-key-sequence nil)` resolved the issue for me. Why does it trigger in `abcdef` context is a good question, especially given that `evil-escape-unordered-key-sequence` is `nil` in my configuration, as well as by default.
