### ISSUE TITLE
SPC / consistency for symbol selection

### ISSUE THREAD

**Issue by dspearson** [syl20bnr/spacemacs#12307]
Currently, `SPC /` if using `grep` selects the symbol under the point. After installing `ag`, the default behaviour changes to not selecting the symbol. This change in behaviour based only on whether an external binary is available was confusing, and the defaults should likely be consistent, one way or another.

`(setq helm-ag-insert-at-point 'symbol)` was enough to change the `ag` behaviour to match that of `grep`, but this should probably be fixed in the layers.

**Comment by duianto** [comment]
How do you search without a symbol with `ag`, if both `SPC /` and `SPC *` includes the current symbol?

**Comment by dspearson** [comment]
I rarely do. Ideally I'd switch the keybindings to have `SPC /` default to selection, and `SPC *` to without, simply because I use the former much much more frequently than the latter, but honestly I've not looked at how to do the rebindings. The effort to move my hands to the shift+8 or across the keyboard to the far right is more than clearing the input field on the odd occasion I'm searching for something else, as backwards as that is.

I'll have a look at how to handle this properly in my configuration.

**Comment by duianto** [comment]
If you just want to switch the behavior of `SPC /` and `SPC *`.

Then you can add this to your user-config section in `.spacemacs`.
```
    (spacemacs/set-leader-keys
      "/" 'spacemacs/helm-project-smart-do-search-region-or-symbol
      "*" 'spacemacs/helm-project-smart-do-search)
```

The `SPC` which-key popup still shows the original names. I'm not sure how to rename them.
