### ISSUE TITLE
Installation unclear

### ISSUE THREAD

**Issue by Erhannis** [syl20bnr/spacemacs#12306]
Your installation explanation is unclear.  "Just clone it" is fine (for me), but "launch it" is not.  There are no binary executables to launch.  After examining several documents, I inferred that you are intended to launch _emacs_, as spacemacs is effectively a set of plugins/skins/templates/etc. for emacs.  Note that that latter point was not clearly stated in the documentation, either.  At this point, it's nearly irrelevant that having run `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`, I ran emacs and saw no difference.  This is about the extent of the effort I'm willing to expend to try an environment I have no solid reason to use, but I figured I'd at least tell you where some of your potential users are going.

**Comment by duianto** [comment]
Thanks for the information about the unclear explanation, I'll forward it to the maintainers.

The reason why you didn't see a difference when you first started Emacs after cloning Spacemacs, is because you might have had an existing `.emacs.d` directory and a `.emacs` file in your home directory.

This is explained in the Installation section: https://github.com/syl20bnr/spacemacs#default-installation
>If you have an existing Emacs configuration, back it up first:
```
cd ~
mv .emacs.d .emacs.d.bak
mv .emacs .emacs.bak
```
>Don't forget to backup and remove ~/.emacs file otherwise Spacemacs WILL NOT load since that file prevents Emacs from loading the proper initialization file.

**Comment by henriquenj** [comment]
Where are you reading the instructions? The readme files _do_ say to launch _emacs_. Both develop and master versions.

**Comment by duianto** [comment]
The author is referring to the introduction https://github.com/syl20bnr/spacemacs#introduction

>Just clone it, launch it, then press the space bar to explore the interactive list of carefully-chosen key bindings. You can also press the home buffer's [?] button for some great first key bindings to try.
