### ISSUE TITLE
org-link doesn't push mark so c-o doesn't jump back after link navigation

### ISSUE THREAD

**Issue by moconnor-leavened** [syl20bnr/spacemacs#12310]
Say I make an org link. Then a navigate to it. In most layers I can ctrl-o to jump back to where I was. But this doesn't work in org-mode. 

I suspect it's because org-mode has an org-mark-ring that it pushes to instead of the ring that evil-jump-backwords uses. Would be a really nice feature if this was integrated.

**Comment by pataquets** [comment]
See #9451
