### ISSUE TITLE
Javascript, react layer stops javascript format on save from working

### ISSUE THREAD

**Issue by Trapez** [syl20bnr/spacemacs#12322]
#### Description :octocat:
Adding react layer stops javascript format on save from working.

#### Reproduction guide :beetle:
- Start Emacs
- Add react layer

*Observed behaviour:* :eyes: :broken_heart:
The spacemacs/javascript-format funtion is not added to the local before-save-hook.

*Expected behaviour:* :heart: :smile:
Javascript format on save should work with react layer added or not.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5cc823cc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ansible ivy
         (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
         better-defaults emacs-lisp git markdown multiple-cursors
         (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t)
         (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
         prettier import-js lsp dap
         (python :variables python-backend 'lsp python-fill-column 99 python-formatter 'yapf python-format-on-save t python-sort-imports-on-save t python-pipenv-activate t)
         (html :variables web-fmt-tool 'prettier)
         react
         (javascript :variables javascript-backend 'lsp javascript-fmt-tool 'prettier javascript-fmt-on-save t javascript-import-tool 'import-js)
         (typescript :variables typescript-backend 'lsp typescript-fmt-on-save t typescript-fmt-tool 'typescript-formatter)
         common-lisp
         (java :variables java-backend 'meghanada)
         syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Gradecak** [comment]
Having the same issue! Have you had any luck finding a workaround?

**Comment by duianto** [comment]
A `.js` file gets formatted on save for me on the latest develop branch.

The `before-save-hook` has the same value with or without the `react` layer enabled:
>before-save-hook is a variable defined in ‘files.el’.
Its value is (t spacemacs/javascript-format)

There was a fix to the react layers fmt-on-save call, 21 days ago:
Fixes function name bug in react layer fmt-on-save https://github.com/syl20bnr/spacemacs/commit/740e6a2a3c5f0bd6e1f3e94b246ff7bb7fb62f47

It looks like your on a commit from january:
Spacemacs branch: develop (rev. 5cc823c)

Try updating to the latest develop branch.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a51b08133)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm html
            (javascript :variables javascript-backend 'lsp javascript-fmt-on-save t)
            lsp markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            react shell spell-checking syntax-checking themes-megapack treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by Trapez** [comment]
Seems to work now, closing.
