### ISSUE TITLE
Forge-pull fails

### ISSUE THREAD

**Issue by AkashGanesan** [syl20bnr/spacemacs#12320]
#### Description :octocat:
Forge-pull fails

#### Reproduction guide :beetle:
- Start Emacs
- Create personal access token
- git config --global github.oauth-token <token>
- M-x forge pull

*Observed behaviour:* :eyes: :broken_heart:
gnutls.el: (err=[-50] The request is invalid.) boot: (:priority NORMAL:-VERS-TLS1.3 :hostname api.github.com :loglevel 0 :min-prime-bits 256 :trustfiles (/etc/ssl/certs/ca-certificates.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)
helm-M-x: GnuTLS error: #<process api.github.com>, -50

*Expected behaviour:* :heart: :smile:
It should have pulled.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5cc823cc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(octave auto-completion better-defaults emacs-lisp git helm markdown multiple-cursors org python julia latex lsp github
        (julia :variables lsp-julia-command "julia" lsp-julia-default-environment "/home/akaberto/.julia/environments/v1.0" julia-mode-enable-lsp t julia-mode-enable-ess nil)
        spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
No backtrace
```

**Comment by vermiculus** [comment]
I'm getting this too, but do not use spacemacs. This should be closed in favor of magit/forge#156.

**Comment by vermiculus** [comment]
Closed the above in favor of magit/ghub#89 – see specifically https://github.com/magit/ghub/issues/89#issuecomment-495463508

**Comment by leezu** [comment]
This issue can be closed. Fixed upstream.

**Comment by duianto** [comment]
Thanks vermiculus and leezu for informing us.

This seems to be the upstream fix:
Adjust conditions for applying gnutls workaround https://github.com/magit/ghub/pull/90
