### ISSUE TITLE
(void-function poly-ein--narrow-to-inner) error on non-EIN related buffers

### ISSUE THREAD

**Issue by korayal** [syl20bnr/spacemacs#12347]
PS: I've created a [ticket](https://github.com/millejoh/emacs-ipython-notebook/issues/537) for this at the upstream too.

Unless I add `(require 'ein)` to `dotspacemacs/user-init` I keep getting this error on all buffers:

```
Error during redisplay: (jit-lock-function 3427) signaled (void-function poly-ein--narrow-to-inner)
Error during redisplay: (jit-lock-function 3927) signaled (void-function poly-ein--narrow-to-inner)
Error during redisplay: (jit-lock-function 2838) signaled (void-function poly-ein--narrow-to-inner)
Error during redisplay: (jit-lock-function 3338) signaled (void-function poly-ein--narrow-to-inner)
Error during redisplay: (jit-lock-function 3838) signaled (void-function poly-ein--narrow-to-inner)
```

I still received this error in the Messages buffer even though I've commented out `ipython-notebook` from the list of layers. The only way to make it go away was to re-enable the layer and add the require command I've mentioned above.

**Comment by duianto** [comment]
Could you add your system information (press `SPC h d s` to copy it to your clipboard).

**Comment by korayal** [comment]
this Issue is fixed on upstream

https://github.com/millejoh/emacs-ipython-notebook/pull/549
