### ISSUE TITLE
agda layer doesn't work in evil mode

### ISSUE THREAD

**Issue by googleson78** [syl20bnr/spacemacs#12342]
#### Description :octocat:
`auto` in `agda-mode` from the layer in this repo doesn't work in `evil` mode. It errors out with the following message:
```
Wrong type argument: commandp, agda2-auto
```
It works if I switch to `holy` mode (`ctrl+z`).
#### Reproduction guide :beetle:
- Have `Agda` >=2.6.0.0
- Have `agda` layer from this repo
- Start Emacs
- Open a `.agda` file
- Go to a hole, try to `SPC m a`
- See the error from above 

*Observed behaviour:* :eyes: :broken_heart:
Hole doesn't get filled in, instead `emacs` reports an error.

*Expected behaviour:* :heart: :smile:
Hole gets filled in (potentially), `emacs` doesn't report an error.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(agda helm emacs-lisp markdown fzf spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

**Comment by googleson78** [comment]
Well, it's not really stale, seeing as how it's fixed in develop. Is this supposed to stay open for as long as it isn't in master yet?

**Comment by duianto** [comment]
It might have been the case, that issues with the `Fixed in develop` label, were closed when the next version with the fix was released. But at the moment the `develop` branch is the recommended branch, and since the stale bot has been added, we've been trying to reduce the number of open issues. So let's close this.
