### ISSUE TITLE
Show words of state indicators in mode line like vim-powerline

### ISSUE THREAD

**Issue by c02y** [syl20bnr/spacemacs#12346]
How can I make the mode line of spacemacs (use spacemacs as the theme of mode line) display the state indicator as words like `NORMAL/HYBRID/VISUAL/...` instead of just colors.

There are so many colors and states displayed according to https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#states , I don't remember all those colors, it is perfect to display their names in mode line like vim-powerline, not just the color indicators.

**Comment by duianto** [comment]
Take a look at the custom spaceline theme:
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#custom-spaceline-theme

And this page might be helpful:
https://www.reddit.com/r/emacs/comments/b6btj7/evil_state_indicator_in_custom_mode_line/

**Comment by c02y** [comment]
That's too complicated, what about I just need to add the state indicator into the mode line, right before the winum number in mode line.

**Comment by duianto** [comment]
I'm not sure how to modify the existing default mode-line, but I might have solved your issue or at least gotten close by using a custom theme.

In the `dotspacemacs/user-init` section of your `.spacemacs`, add these lines:
```elisp
  (setq evil-emacs-state-tag "EMACS")
  (setq evil-hybrid-state-tag "HYBRID")
  (setq evil-insert-state-tag "INSERT")
  (setq evil-motion-state-tag "MOTION")
  (setq evil-normal-state-tag "NORMAL")
  (setq evil-operator-state-tag "OPERATOR")
  (setq evil-visual-state-tag "VISUAL")

  (defun spaceline-custom-theme (&rest additional-segments)
    "My custom spaceline theme."
    (spaceline-compile
      ;; left side
      '(((evil-state
          persp-name
          workspace-number
          window-number)
          :fallback evil-state
          :face highlight-face
          :priority 100)
        (anzu :priority 95)
        auto-compile
        ((buffer-modified buffer-size buffer-id remote-host)
          :priority 98)
        (major-mode :priority 79)
        (process :when active)
        ((flycheck-error flycheck-warning flycheck-info)
          :when active
          :priority 89)
        (minor-modes :when active
                      :priority 9)
        (mu4e-alert-segment :when active)
        (erc-track :when active)
        (version-control :when active
                          :priority 78)
        (org-pomodoro :when active)
        (org-clock :when active)
        nyan-cat)
      ;; right side
      '(which-function
        (python-pyvenv :fallback python-pyenv)
        (purpose :priority 94)
        (battery :when active)
        (selection-info :priority 95)
        input-method
        ((buffer-encoding-abbrev
          point-position
          line-column)
          :separator " | "
          :priority 96)
        (global :when active)
        (buffer-position :priority 99)
        (hud :priority 99)))
    (setq-default mode-line-format '("%e" (:eval (spaceline-ml-main)))))
```

Then change the mode-line-theme to:
```elisp
   dotspacemacs-mode-line-theme '(custom)
```
And restart Spacemacs.

#### This is how I created the custom theme

I used the Spacemacs custom spaceline theme example:
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#custom-spaceline-theme

And replaced the `(spaceline-compile` section with the example from the spaceline repository:
https://github.com/TheBB/spaceline#tweaking-or-defining-your-own-mode-line

And added `evil-state` as the first entry above `persp-name`.

Then I found out how to change `<N>`, `<I>`, to `NORMAL`, `INSERT` etc. here:
https://emacs.stackexchange.com/questions/30582/how-do-i-change-the-mode-indicators-for-evil-mode-in-the-spaceline-mode-line-pac

And added tags for emacs, hybrid, motion, and operator.

**Comment by c02y** [comment]
@duianto Thank you, I just cannot find the original definition of mode line for spaceline.

It works great, you are really kind.

**Comment by duianto** [comment]
> I just cannot find the original definition of mode line for spaceline.

In the introduction https://github.com/TheBB/spaceline#introduction it says that:
`spaceline-config.el: Defines the default themes.`

The file can be found here:
https://github.com/TheBB/spaceline/blob/master/spaceline-config.el

**Comment by c02y** [comment]
THANK YOU!
