### ISSUE TITLE
Scroll microstate exits automatically when it can't scroll any more.

### ISSUE THREAD

**Issue by deech** [syl20bnr/spacemacs#1234]
To reproduce:
1. Go to the top of the document
2. Invoke the scroll microstate SPC n ,
3. Press ',' to scroll up

The user is now no longer in the scroll microstate.

**Comment by syl20bnr** [comment]
I think the microstate is still activated but maybe a message overwrite the microstate message in the minibuffer.
We can avoid to use the minibuffer by removing `:use-minibuffer t` here: https://github.com/syl20bnr/spacemacs/tree/develop/spacemacs/packages.el#L701

**Comment by syl20bnr** [comment]
Should be fixed in develop
