### ISSUE TITLE
define-word is not installed correctly

### ISSUE THREAD

**Issue by johnbcoughlin** [syl20bnr/spacemacs#12356]
#### Description :octocat:
Functions from package define-word are not available

#### Reproduction guide :beetle:
- Start Emacs
- Add spacemacs-language to the dotspacemacs-configuration-layers list
- `SPC f e R`

*Observed behaviour:* :eyes: :broken_heart:
The function `define-word` is not available via `M-x`, despite `define-word` appearing in `configuration-layers--used-packages`.

*Expected behaviour:* :heart: :smile:
The function `define-word` should be available.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html ruby python osx ivy emacs-lisp cdlatex latex rust org org-clock-convenience spacemacs-language)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by jmromer** [comment]
@johnbcoughlin `define-word` is no longer installed if `osx-use-dictionary-app` is set. The default keybinding now displays definitions from the macOS dictionary.

```elisp
(setq-default dotspacemacs-configuration-layers '(
   (osx :variables osx-use-dictionary-app nil)))
```
https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bos/osx#define-words-using-os-x-dictionary

```lisp
;; layers/+spacemacs/spacemacs-language/packages.el L12-L14 (cce5668ad)

(setq spacemacs-language-packages
      '((define-word :toggle (not (bound-and-true-p osx-use-dictionary-app)))
        google-translate))
```
<sup>[[source](https://github.com/syl20bnr/spacemacs/blob/cce5668ad/layers/+spacemacs/spacemacs-language/packages.el#L12-L14)]</sup>
