### ISSUE TITLE
Is there any plan to support clangd as lsp-backend for c-c++ mode?

### ISSUE THREAD

**Issue by idears-org** [syl20bnr/spacemacs#12351]
I can find some workaround method in #12084 , but I think it's better to add a feature to support lsp-clangd in c-c++-backend.

Is there any plan to do this?

**Comment by auscompgeek** [comment]
I hacked up some clangd support in https://github.com/auscompgeek/spacemacs/tree/clangd. Far from perfect, but mostly gets the job done for now.

**Comment by yyoncho** [comment]
@auscompgeek IMO it looks ok and you could open a PR.

**Comment by idears-org** [comment]
@auscompgeek Awesome job, waiting for your pull request to be merged.

**Comment by yyoncho** [comment]
this is fixed
