### ISSUE TITLE
How to toggle the auto completion?

### ISSUE THREAD

**Issue by lazywei** [syl20bnr/spacemacs#1235]
Hi,

I followed the instruction in the doc: https://github.com/syl20bnr/spacemacs/tree/master/contrib/auto-completion

I have the following lines in my `.spacemacs`
```
(setq-default dotspacemacs-configuration-layers
  '(auto-completion :variables
                    auto-completion-use-tab-instead-of-enter t))
```

However, as I type, it doesn't show any completion suggestion. How can I toggle the auto completion?

**Comment by syl20bnr** [comment]
In which major-mode (language) are you typing ?
Do you have any error in `*Messages*` ?

**Comment by lazywei** [comment]
![image](https://cloud.githubusercontent.com/assets/2840571/7218568/d77e5704-e6a9-11e4-92d8-583ac3c21064.png)

I try to press `Tab` but nothing happen. Also, I'd like to have "completion as type". For example, like [YCM](https://github.com/Valloric/YouCompleteMe) in Vim:
![image](https://camo.githubusercontent.com/1f3f922431d5363224b20e99467ff28b04e810e2/687474703a2f2f692e696d6775722e636f6d2f304f50346f6f642e676966)

**Comment by syl20bnr** [comment]
The auto-completion  UX has been revamped see the documentation https://github.com/syl20bnr/spacemacs/blob/develop/contrib/auto-completion/README.md#key-bindings
