### ISSUE TITLE
The exec-path is Not equal to the PATH from .spacemacs.env exactly, The path of python from shims is not found correctly in Org-babel.

### ISSUE THREAD

**Issue by yssource** [syl20bnr/spacemacs#12353]
#### Description :octocat:
The path of python from shims is not found correctly in Org-babel. 
Since, exec-path always prepends system's bin path to the path of shims.

I think **The value of exec-path should equal to the PATH from .spacemacs.env exactly, No additional values are prepended to the exec-path.**

#### Reproduction guide :beetle:
- Start Emacs
- Open .spacemacs.env

``` org
PATH=/Users/jimmy/perl5/bin:/usr/local/opt/llvm/bin:/Users/jimmy/.pyenv/plugins/pyenv-virtualenv/shims:/Users/jimmy/.pyenv/shims:/usr/local/opt/qt/bin:/usr/local/sbin:/usr/local/opt/coreutils/libexec/gnubin:/Users/jimmy/.pyenv/bin:/usr/local/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/jimmy/perl5/bin:/usr/local/opt/llvm/bin:/Users/jimmy/.pyenv/plugins/pyenv-virtualenv/shims:/Users/jimmy/.pyenv/shims:/usr/local/opt/qt/bin:/usr/local/sbin:/usr/local/opt/coreutils/libexec/gnubin:/Users/jimmy/.pyenv/bin:/usr/local/opt/openssl/bin
```
- Write elisp to test
``` org
#+begin_src elisp :results output
  (print exec-path)
#+end_src

#+RESULTS:
: 
: ("/usr/local/bin/" "/usr/bin/" "/bin/" "/usr/sbin/" "/sbin/" "/opt/X11/bin/" "/Users/jimmy/perl5/bin/" "/usr/local/opt/llvm/bin/" "/Users/jimmy/.pyenv/plugins/pyenv-virtualenv/shims/" "/Users/jimmy/.pyenv/shims/" "/usr/local/opt/qt/bin/" "/usr/local/sbin/" "/usr/local/opt/coreutils/libexec/gnubin/" "/Users/jimmy/.pyenv/bin/" "/usr/local/opt/openssl/bin/" "/usr/local/Cellar/emacs-plus/26.2/libexec/emacs/26.2/x86_64-apple-darwin18.2.0/")

```
*Observed behaviour:* :eyes: :broken_heart:

I do not have settup ("/usr/local/bin/" "/usr/bin/" "/bin/" "/usr/sbin/" "/sbin/" "/opt/X11/bin/") in my PATH, but why these values are prepended to *my exec-path*?

``` org
"/usr/local/bin/" "/usr/bin/" "/bin/" "/usr/sbin/" "/sbin/" "/opt/X11/bin/" ... "/Users/jimmy/.pyenv/shims/" 
```

*Expected behaviour:* :heart: :smile:

It should first to look for my python from the shims, instead of the system's path.
The system's path should not be prepended to exec-path.
**The value of exec-path should equal to the PATH from .spacemacs.env exactly.**

``` org
#+begin_src elisp :results output
  (print exec-path)
#+end_src

#+RESULTS:
: 
: ("/Users/jimmy/perl5/bin/" "/usr/local/opt/llvm/bin/" "/Users/jimmy/.pyenv/plugins/pyenv-virtualenv/shims/" "/Users/jimmy/.pyenv/shims/" "/usr/local/opt/qt/bin/" "/usr/local/sbin/" "/usr/local/opt/coreutils/libexec/gnubin/" "/Users/jimmy/.pyenv/bin/" "/usr/local/opt/openssl/bin/" "/usr/local/Cellar/emacs-plus/26.2/libexec/emacs/26.2/x86_64-apple-darwin18.2.0/")

```

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4c8d82058)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((ivy :variables ivy-enable-advanced-buffer-information nil)
 better-defaults ranger colors prodigy search-engine graphviz
 (haskell :variables haskell-enable-hindent t haskell-completion-backend 'intero)
 (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
 (spell-checking :variables spell-checking-enable-by-default nil)
 (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 300)
 (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for org markdown)
 (osx :variables osx-dictionary-dictionary-choice "Simplified Chinese - English" osx-command-as 'super)
 restclient
 (gtags :disabled-for clojure emacs-lisp javascript latex python shell-scripts)
 (shell :variables shell-default-shell 'eshell)
 latex deft markdown
 (org :variables org-want-todo-bindings t)
 gpu yaml react
 (python :variables python-backend 'lsp python-test-runner
         '(nose pytest))
 lua html
 (javascript :variables javascript-backend 'nil)
 (typescript :variables typescript-fmt-on-save nil typescript-fmt-tool 'typescript-formatter)
 emacs-lisp racket
 (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-lsp-executable "/usr/local/bin/ccls" c-c++-default-mode-for-headers 'c++-mode)
 zilongshanren
 (chinese :packages youdao-dictionary fcitx :variables chinese-enable-fcitx nil chinese-enable-youdao-dict t)
 treemacs lsp dap)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

### This only happens to Org-babel. But, no problem for python scripts.

**Comment by leezu** [comment]
This is unrelated to Org-babel but a general issue with how spacemacs configures exec-path. Would you mind adopting your title? If the title makes it obvious that this is a general issue, the bug may get more attention and could be fixed.

**Comment by yssource** [comment]
@leezu 
Sorry. The problem is that I did not invoke the virtual environment for the Python in Org-babel.
Firstly, `, '` gets into the Python buffer of Org-babel , then `SPC m v a` or `pyvenv-activate` activates the required virtual environment for it.
Secondly, `Crtl-c Ctrl-c` on the Org-babel. Now, it will OK to run Org-babel with a virtual environment.

https://github.com/syl20bnr/spacemacs/issues/12381
https://github.com/syl20bnr/spacemacs/issues/10145#issuecomment-497915889

**Comment by leezu** [comment]
Ok, I submitted a new bug https://github.com/syl20bnr/spacemacs/issues/12403
