### ISSUE TITLE
.elc support for spacemacs

### ISSUE THREAD

**Issue by edwintorok** [syl20bnr/spacemacs#1237]
The startup time of spacemacs is quite good already (~1.8s), however maybe it could be improved if the configuration was byte-compiled (and not just the packages), however trying to byte-compile gives a lot of warnings about missing functions, including use-package.
I don't know much about emacs config and how to fix this, since I'm coming from Vim:

```
emacs --batch --eval '(byte-recompile-directory "~/.emacs.d/" 0)'
```
Done (Total of 312 files compiled, 206 failed, 241 skipped in 226 directories)

**Comment by syl20bnr** [comment]
`use-package` needs to be required to be able to byte-compile.
Now to byte-compile without warnings could require a lot of work for a small benefit in the end, not to mention that it could be difficult to maintain with a lot of PR.
@jwiegley reported to have 10% improvements with byte-compiled configuration, is it really worth it ?

**Comment by jwiegley** [comment]
It is not worth it.

**Comment by trishume** [comment]
Given how often spacemacs updates and the apparently limited benefits, probably not worth it.

**Comment by edwintorok** [comment]
I agree that if the improvement is only around 10% its not worth it, lets close this one.
