### ISSUE TITLE
Unable to use DAP layer with c++ on mac

### ISSUE THREAD

**Issue by zliebowitz** [syl20bnr/spacemacs#12370]
#### Description :octocat:
It errors with:

Could not start debugger process, does the program exist in filesystem?
Error: spawn lldb-mi ENOENT

I've run dap-gdb-lldb-setuo which says that it has succeeded in downloading, and tried added `(setq dap-gdb-lldb-path "...")`. The same machine is able to run the debugger using the same [extension](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/c-c%2B%2B#debugger-dap-integration) this is based off without issue.

#### Reproduction guide :beetle:
- Start Emacs
- ensure c-c++ layer is enabled with ccls backend, as well as DAP and LSP layers
- Open a c++ file
- Assuming evil mode, hit "space", "m", followed by "d" until prompted for a configuration
- Select the lldb option
- Select an executable (this issue doesn't seem to care about association with the source)

*Observed behaviour:* :eyes: :broken_heart:
The debugged executable fails to start with the above error.

*Expected behaviour:* :heart: :smile:
The debugged executable starts.

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b4907d054)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t)
 better-defaults
 (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-lsp-executable
        (file-truename "/usr/local/Cellar/ccls/0.20190314/bin/ccls"))
 cmake dap emacs-lisp helm git lsp markdown multiple-cursors org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
N/A

**Comment by yyoncho** [comment]
Do you have `lldb-mi` on the path?

**Comment by zliebowitz** [comment]
Yes, it is symlinked to /usr/local/bin/. I’m currently thinking this may be a symptom of #12396, but I’ve not had a chance to investigate that yet.

**Comment by zliebowitz** [comment]
I got it working/

Based on the assumption thatt the issue was the referenced ticket< I ran:
```
rm ~/.spacemacs* # remove existing config files
cd ~/.emacs.d
git clean -fdx # delete files that aren't tracked in repo
rm .cache # not deleted from the prior
```

From there, reinstalling and following instructions for the c++ layer worked.

I'm closing the issue as it is resolved.
