### ISSUE TITLE
Spacemacs can't start processes in some cases

### ISSUE THREAD

**Issue by rpls** [syl20bnr/spacemacs#12378]
#### Description :octocat:

Emacs can't start processes in some cases. For example, when using
`restart-emacs`, emacs will not restart but simply close. Other examples include
opening attachments using notmuch (using `notmuch-show-interactively-view-part`,
which in turn will call `mm-display-external` to start a process which will view
the attachment, for example, a PDF viewer). No errors will show up in
`*Messages*`. From what I can tell, the execution will (in the case of
`restart-emacs`, and also other instances) arrive at `call-process` or
`start-process` or similar, which in turn instead of starting a process, will
have no effect whatsoever.

The problem is not present in a blank emacs config (i.e. `emacs -q`).

Layers which, for example, use language servers are completely fine by the way. So starting processes doesn't fail in general.

#### Reproduction guide :beetle:
- Start Emacs and either
- Call `restart-emacs`
- Or evaluate `(call-process "SOMEPROGRAM")` 

*Observed behaviour:* :eyes: :broken_heart:

- Emacs will close and not restart, no error message
- `call-process` doesn't do anything

*Expected behaviour:* :heart: :smile:

- Emacs should restart
- `call-process` should start a process.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 95940a64e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lua systemd csv asciidoc markdown docker neotree git version-control
     (org :variables org-enable-bootstrap-support nil org-enable-reveal-js-support nil org-enable-hugo-support nil org-enable-trello-support nil org-enable-github-support t org-want-todo-bindings t)
     (dash :variables helm-dash-docset-newpath "~/.local/share/Zeal/Zeal/docsets")
     (debug :variables debug-additional-debuggers
            '("pdb" "trepan2" "trepan3k"))
     dap
     (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
     (lsp :variables lsp-navigation 'peek)
     (spell-checking :variables spell-checking-enable-auto-dictionary t)
     (syntax-checking :variables syntax-checking-enable-tooltips t syntax-checking-enable-by-default t)
     shell-scripts
     (c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-ccls c-c++-lsp-cache-dir "/tmp/lsp-cache" c-c++-lsp-executable "/home/petri/.local/bin/ccls" c-c++-lsp-sem-highlight-rainbow nil c-c++-lsp-sem-highlight-method 'font-lock)
     (python :variables python-test-runner 'pytest python-backend 'lsp python-save-before-test t)
     (latex :variables latex-build-command "LatexMk" latex-enable-auto-fill t latex-enable-magic nil)
     bibtex
     (ruby :variables ruby-test-runner 'minitest)
     (scala :variables scala-enable-eldoc nil scala-auto-insert-asterisk-in-comments t)
     (java :variables java-backend 'ensime)
     major-modes emacs-lisp gpu asm
     (cmake :variables cmake-enable-cmake-ide-support nil)
     shell pdf
     (notmuch :variables notmuch-spacemacs-layout-binding "n" notmuch-spacemacs-layout-name "@Notmuch"))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:

Not relevant

**Comment by rpls** [comment]
This seems to be a problem with the cached environment in `.spacemacs.env`. Apparently starting processes which needs a connection to X11 simply failed and restart-emacs or external file viewers started but crashed (sadly, they crashed silently) as the connection to X11 failed due to old environment variables (e.g. DISPLAY). Deleting `.spacemacs.env` fixed the issue for now. This didn't affect language servers and alike, as they didn't really depend on the invalid environment variables.

**Comment by duianto** [comment]
Both `restart-emacs` (`SPC q r` or `SPC q R`) and `call-process` works for me.
- `(call-process "gedit")` in Ubuntu 18.04.02 (virtualbox guest with win 10 as host)
- `(call-process "notepad")` in Windows 10 version 1803

I don't know anything about X11, so I don't know if gedit connects to it. If it doesn't is there some other application I can test with?

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b4907d054)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0f9315e63)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm markdown
            (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
            (org :variables org-enable-org-journal-support t)
            spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by rpls** [comment]
New reproduction guide:
- Open `.spacemacs.env` and change the DISPLAY variable (in my case, this happened over time as I changed display managers, usually the DISPLAY variable stays pretty much the same on all systems).
- Use `(call-process "XXX")` to start a process which requires X11.

Mitigation for now would be to simply force the regeneration of `.spacemacs.env` by deleting it. Full fix would be to continually update the environment stored in `.spacemacs.env`.

**Comment by duianto** [comment]
After changing `DISPLAY=:0` to: ``DISPLAY=:1` and restarting or pressing:
`SPC f e E` to call `dotspacemacs/call-user-env`

Now `(call-process "gedit")` doesn't start `gedit` and the minibuffer shows:
`1 (#o1, #x1, ?\C-a)`

With `DISPLAY=:0`, `gedit` starts and when it's closed then Emacs shows: `0 (#o0, #x0, ?\C-@)

**Comment by laynor** [comment]
For me, removing the `XDG_SESSION` related variables, `DISPLAY` and `xauthority` from the `.spacemacs.env` fixed the issue.

**Comment by khajavi** [comment]
> For me, removing the `XDG_SESSION` related variables, `DISPLAY` and `xauthority` from the `.spacemacs.env` fixed the issue.

I remove the .spacemacs.env and spacemacs created it again. now it works for me.
