### ISSUE TITLE
1 error at startup Symbol's value as variable is void: evil

### ISSUE THREAD

**Issue by cata0309** [syl20bnr/spacemacs#12389]
Well I am just a beginner here. I see this error when I open spacemacs.
It is a fresh install.

**Comment by cata0309** [comment]
![Screenshot from 2019-05-29 23-37-24](https://user-images.githubusercontent.com/35623921/58589782-5757e380-826b-11e9-997c-8681484d0537.png)

**Comment by duianto** [comment]
Could you post the contents of your `.spacemacs` file.
And what's your `emacs --version`?

**Comment by cata0309** [comment]
I uninstalled emacs, you can close the issue

joi, 30 mai 2019, 11:24 duianto <notifications@github.com> a scris:
