### ISSUE TITLE
just some suggestions for treemacs taglist function or the lsp-ui-imenu

### ISSUE THREAD

**Issue by jidibinlin** [syl20bnr/spacemacs#12384]
Treemacs and lsp-ui-imenu both of them support to list the method variable struct but they can`t refreash while i opend the other file . And  they can`t show me the method`s or the struct`s  variable types. Please add this function for spacemacs. Thanks for developing spacemacs.

**Comment by robbyoconnor** [comment]
@jidibinlin -- when I started using spacemacs, I knew very little Emacs Lisp...most of what you need to make this happen is already there...so you can do this -- make a PR -- I believe in you :muscle:

**Comment by emacs18** [comment]
It appears to me that treemacs and lsp cannot co-exist.  They both want to set
imenu-create-index-list when only one can set it!

I think this is a rather difficult problem to solve.  For now my work around is to launch
two emacs so that one has treemacs enabled and the other has lsp enabled.
I have to edit ~/.spacemacs file to comment out either treemacs or layer.
Sigh.

**Comment by emacs18** [comment]
I submitted https://github.com/Alexander-Miller/treemacs/issues/451 hoping that someone would come up with a solution.

**Comment by emacs18** [comment]
For now I would be happy with an easier work around.  For example is it possible to just turn off lsp after emacs starts up?  I tried lsp-shutdown-workspace, but that did not prevent lsp from coming back to life when I started editing some c++ files.  What I'm looking for is a way to completely disable within emacs  and allow me to re-enable lsp when I want it without launching new emacs after editing ~/.spacemacs.

**Comment by Alexander-Miller** [comment]
> They both want to set imenu-create-index-list when only one can set it!

No. Treemacs does *not* set that and I've no idea what made you think it does. All treemacs does is show the tags from whatever provider is around.

**Comment by Alexander-Miller** [comment]
> they cant refreash while i opend the other file 

Treemacs has a filewatch-mode option. It'll refresh the tags as well when the file changes.

> And they cant show me the methods or the structs variable types

Not a problem of treemacs. Or even spacemacs. All they do is show the tags that are provided by either some language's major-mode or an additional addon like a language server.

**Comment by duianto** [comment]
Since the upstream issue has been closed, we'll close this as well.
