### ISSUE TITLE
Line referring to `brew linkapps` in README seems to be obsolete

### ISSUE THREAD

**Issue by lukehesluke** [syl20bnr/spacemacs#12390]
This is, at time of writing, not in the master branch yet but it is in `develop`: https://github.com/syl20bnr/spacemacs/tree/develop#macos

For some context, this issue (https://github.com/syl20bnr/spacemacs/issues/10578) describes how `brew linkapps` was made obsolete by Homebrew releases at some point prior to Apr 2018. At the end of the issue, it is detailed that the README has been updated to use a `ln` command instead of `brew linkapps`.

However, I can see this sentence: "Copy and paste the symlink (ln) from the install instructions if brew linkapps is deprecated." in the develop README (https://github.com/syl20bnr/spacemacs/tree/develop#macos) which is incongruent as there are no other references to `brew linkapps` in that README. Since it is also referring to obsolete functionality, best to just remove the line? I'll create a PR very shortly to do just this.

**Comment by lukehesluke** [comment]
I see that I was mistakenly confused by what "the install instructions" meant. I see now that this refers to the log that is output at the end of `brew install emacs-mac`.

This is inconsistent with the above instruction for emacs-plus which works even for someone mindlessly following instructions and not looking at the logs (like me ;} ).

So I suggest still removing the line referring to `brew linkapps` and including the instruction

```
ln -s /usr/local/Cellar/emacs-mac/*/Emacs.app/ /Applications
```

To be consistent with the emacs-plus instructions and potentially easier for silly people like me

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
Make emacs-mac instruction consistent with emacs-plus #12391

**Comment by FabioMen10** [comment]
For who installed emacs-plus the right command it's below:
`ln -s /usr/local/opt/emacs-plus/Emacs.app /Applications`
