### ISSUE TITLE
Key binding missing for "live evaluation mode" in  JavaScript Layer in  REPL (skewer-mode)

### ISSUE THREAD

**Issue by ofenerci** [syl20bnr/spacemacs#12395]
I have installed JavaScript Layer and running js codes using develop branch of spacemacs. When I want to use a " live evaluation mode", I am supposed to enter `SPC m s a` (http://spacemacs.org/layers/+lang/javascript/README.html#repl-skewer-mode). Somehow, I can see all other commands (`SPC m s b` `SPC m s f` etc.) but not `SPC m s a`. I wonder  how to activate "live evaluation mode"

**Comment by duianto** [comment]
The key binding seems to have been changed to `SPC m T l` (lower case L) in this commit: https://github.com/syl20bnr/spacemacs/commit/8bc9060af83f97090945a4ae02e8c94af984da61
>javascript: change key binding for repl live eval toggle
>
>To respect convention move the key binding under `SPC m T l` and change
the lighter to a plain squared `l`.

The readme just needs to be updated.

**Comment by duianto** [comment]
The develop branch documentation:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/javascript/README.org

has been updated:
[javascript][doc] Update key toggle live evaluation https://github.com/syl20bnr/spacemacs/commit/7dace901a2864490b1fb222b67df0ef25445e569
