### ISSUE TITLE
Bibtex layer (org-ref): Emacs freezes when loading an Org file containing :ignore: in a heading

### ISSUE THREAD

**Issue by aschaap** [syl20bnr/spacemacs#12392]
#### Description :octocat:
Spacemacs (`develop` branch) with the `org` and `bibtex` layers (the latter for `org-ref`) causes Emacs to freeze when loading an Org file containing:
```org
    * Title page                                                         :ignore:
```
This is fixed by removing the contents of the `bibtex/pre-init-org-ref` function in the `bibtex` layer's `packages.el`, though I am unsure what other effects this change has because I am a fairly new Emacs and Spacemacs user without much knowledge of its internals or Elisp in general.

#### Reproduction guide :beetle:
- Ensure you are on Spacemacs' `develop` branch
- Ensure the `org` and `bibtex` layers are enabled in `.spacemacs` (I also have `ocaml`, `git`, `helm` and `spell-checking`, but these seem irrelevant)
- Open an Org file with Emacs that contains a top-level heading ending in `:ignore:`

*Observed behaviour:* :eyes: :broken_heart:
Emacs appears to freeze; sometimes one can move around a few seconds before it does so. It maxes out a single core (100% in `top`) until a `killall emacs25` stops it.

*Expected behaviour:* :heart: :smile:
Any Org file loads quickly and the user can subsequently edit it.

#### System Info :computer:
- OS: Ubuntu 16.04 LTS
- Emacs: 25.3.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 39ce04c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(ocaml bibtex git helm org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
Sorry, I read https://github.com/syl20bnr/spacemacs/wiki/Debugging but I'm not sure how to generate a backtrace with Emacs when it freezes upon opening a file.

**Comment by duianto** [comment]
I'm unable to reproduce a freeze in either Ubuntu or Windows.

On the latest develop branch with updated packages.

To make sure that it isn't an Emacs version issue, could you test if it also happens with Emacs 26+ or even with the latest snapshot 27.0.50?

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a281e6979)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(bibtex emacs-lisp git helm multiple-cursors ocaml org spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP



#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a281e6979)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey bibtex emacs-lisp git helm html markdown multiple-cursors ocaml
            (org :variables org-enable-org-journal-support t)
            spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by aschaap** [comment]
@duianto: Turns out it is an Emacs version problem. Just tested it with Emacs 26.1 on Gentoo and it seems perfectly fine. I guess both machines I tried it on had Emacs 25.3. Looks like I jumped the gun - sorry about that.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a281e6979)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git neotree org spell-checking syntax-checking ocaml lua bibtex pdf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS NOTIFY ACL GNUTLS FREETYPE XFT ZLIB GTK3 X11 THREADS LCMS2

**Comment by duianto** [comment]
No problem at all, now there's a solution if someone searches for freeze and org.
