### ISSUE TITLE
`SPC l l` is broken on develop branch

### ISSUE THREAD

**Issue by qqldd** [syl20bnr/spacemacs#12402]
#### Description :octocat:
`SPC l l` is broken on develop branch

#### Reproduction guide :beetle:
- Start Emacs
- Press `SPC l l`

*Observed behaviour:* :eyes: :broken_heart:
Nothing happend

*Expected behaviour:* :heart: :smile:
Should show `helm-perspective`

Further, `C-h v` on `spacemacs--persp-display-perspectives-func` shows

```
spacemacs--persp-display-perspectives-func is a variable defined in ‘funcs.el’.
Its value is ‘ignore’
```

Related commit: https://github.com/syl20bnr/spacemacs/commit/3bce69aba1dc34b01131b7508b2d79f543245ab2

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c7c348a67)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm
 (spacemacs-layouts :variables layouts-enable-autosave nil)
 auto-completion better-defaults emacs-lisp git markdown
 (multiple-cursors :variables multiple-cursors-backend 'mc)
 treemacs
 (version-control :variables version-control-diff-tool 'diff-hl)
 shell-scripts haskell csv shell gtags syntax-checking colors theming org yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
It's working as expected for me, on the latest develop branch with updated packages.

`SPC l l` opens the Layouts Transient State.

`SPC h d v` `spacemacs--persp-display-perspectives-func` shows:
>spacemacs--persp-display-perspectives-func is a variable defined in ‘funcs.el’.
Its value is ‘spacemacs/helm-perspectives’

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fc3677131)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git
            (haskell :variables haskell-completion-backend 'dante)
            helm ipython-notebook markdown multiple-cursors
            (org :variables org-want-todo-bindings t)
            spell-checking syntax-checking themes-megapack treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by qqldd** [comment]
Interesting, let me see why this line is not executed on my system: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+completion/helm/packages.el#L430
