### ISSUE TITLE
Weird behaviour when changing font size with line numbering turned on

### ISSUE THREAD

**Issue by Whitewing135** [syl20bnr/spacemacs#12401]
#### Description :octocat:
Weird behaviour when changing font size with line numbering turned on

#### Reproduction guide :beetle:
- Start Emacs
- Open a buffer with text in it
- Turn on line numbering (SPC t n)
- Enter font scaling transient state (SPC z x)
- Scale up font (press =)

*Observed behaviour:* :eyes: :broken_heart:
    Each time the font is scaled up the text in the buffer is shifted to the
right eventually turning it into a column of text.
    This continues after exiting the state on each move key press (j/k).

*Expected behaviour:* :heart: :smile:
Expected font to scale normaly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp markdown)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
This is a known issue:
Linum-mode creates margins on zoomed-in font #9382
Line number doesn't go back to normal after I increase the font size and reset it. #8481
org-present not displayed correctly on develop branch #8458
[bugreport] M-z-x scale font bad behavior when global-line-number enabled #12154

The `develop` branch has solved it by using the built-in Emacs 26 line numbers.

A workaround on the `master` branch might be to rebind the line numbers key binding.

Add this to the `dotspacemacs/user-config` section of your `.spacemacs`:
```elisp
    (spacemacs/set-leader-keys "tn" 'display-line-numbers-mode)
```

**Comment by Whitewing135** [comment]
Thanks it works as intended. As for relative numbering i guess i'll have to wait for the new version.

**Comment by duianto** [comment]
Here are two functions and key bindings that match the absolute and relative line numbers behavior of the `develop` branch:
```elisp
    (defun toggle-line-numbers-absolute ()
      "Toggle line numbers."
      (interactive)
      (if (and (featurep 'display-line-numbers)
               display-line-numbers-mode
               (eq display-line-numbers t))
          (progn
            (display-line-numbers-mode -1)
            (message "Line numbers disabled."))
        (display-line-numbers-mode)
        (setq display-line-numbers t)
        (message "Absolute line numbers enabled.")))

    (defun toggle-line-numbers-relative ()
      "Toggle relative line numbers."
      (interactive)
      (if (and (featurep 'display-line-numbers)
               display-line-numbers-mode
               (eq display-line-numbers 'relative))
          (progn
            (display-line-numbers-mode -1)
            (message "Line numbers disabled."))
        (display-line-numbers-mode)
        (setq display-line-numbers 'relative)
        (message "Relative line numbers enabled.")))

    (spacemacs/set-leader-keys "tn" 'toggle-line-numbers-absolute)
    (spacemacs/set-leader-keys "tr" 'toggle-line-numbers-relative)
```
