### ISSUE TITLE
Python layer overrides fill-width variable from editorconfig

### ISSUE THREAD

**Issue by sephii** [syl20bnr/spacemacs#12416]
#### Description :octocat:

The `python` layer has a `python-fill-column` variable that will automatically set the `fill-column` variable. This clashes with the `editorconfig` package, that sets the `fill-column` variable first, which then gets overwritten by the `python-fill-column` one.

Since there doesn't seem to be a way to disable this feature in the `python` layer, the only way I found to have Spacemacs respect the .editorconfig file with the `Python` layer is to add the following to my .spacemacs file:

```elisp
(add-hook 'python-mode-hook 'editorconfig-apply)
```

#### Reproduction guide :beetle:
- Start Emacs
- Make sure you have the `python` layer enabled
- Open the file of a project that has a `.editorconfig` file with `max_line_length = 88` in it
- Type `SPC h d v fill-column`, you'll see it's set to 79

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs doesn't respect the rules defined in the .editorconfig file (ie. the `fill-column` variable is set to 79).

*Expected behaviour:* :heart: :smile:
Spacemacs respects the rules defined in the .editorconfig file (ie. the `fill-column` variable is set to 88).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4cb922630)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(elm ansible yaml php javascript markdown html python helm auto-completion better-defaults git org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     syntax-checking version-control themes-megapack ranger django)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

**Comment by Compro-Prasad** [comment]
IMO this is a bug. You can open a PR about this.

**Comment by sephii** [comment]
I would love to, but I'm really not sure how to fix this. Should we allow `python-fill-column` to be `nil` and in that case not use it? Should we unset its default value and use it only if it's set? Should we remove it entirely? Should we make sure any value set by `editorconfig` isn't overwritten? And if so how can we know that the value was set by `editorconfig`?

**Comment by Compro-Prasad** [comment]
There are variable watchers in Emacs 26. So, we can watch `python-fill-column` to check if value has changed and force update values from editor config. But your fix `(add-hook 'python-mode-hook 'editorconfig-apply)` works or you so you can add it to the spacemacs python layer.
