### ISSUE TITLE
Spacemacs takes more than 30 seconds to include a new line after press enter.

### ISSUE THREAD

**Issue by rodrigosantana** [syl20bnr/spacemacs#12415]
#### Description :octocat:
Spacemacs takes more than 30 seconds to include a new line after press enter.

#### Reproduction guide :beetle:
- Start Emacs
- Open an R script
- Start programming
- Insert a new line of code and at the end press "ENTER"
- Spacemacs freeze for 30, sometimes 50 seconds, after that include the line.

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs freezes always when i am trying to include a new line using "ENTER".
If i use C-J, the process occur as expected.

*Expected behaviour:* :heart: :smile:
The line be inserted fastly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (spell-checking :variables spell-checking-enable-by-default nil)
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      ipython-notebook rust html yaml latex extra-langs
      (ess :variables ess-enable-smart-equals t ess-enable-electric-spacing t ess-enable-smartparens t)
      funk polymode header2)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Compro-Prasad** [comment]
You can include a backtrace too. Just do `M-x toggle debug-on-quit` and press `C-g` when it hangs. It should probably show a backtrace which you can include it in your issue.

**Comment by rodrigosantana** [comment]
Thanks @Compro-Prasad for the information. Bellow I present you the result of debug-on-quit.

Debugger entered--Lisp error: (quit)
  back-to-indentation()
  ess-maximum-args-indent(270737 nil)
  ess-calculate-indent--args()
  ess-calculate-indent()
  ess-r-indent-line()
  indent-according-to-mode()
  electric-indent-post-self-insert-function()
  self-insert-command(1)
  newline(nil t)
  #f(compiled-function () (interactive "*") #<bytecode 0x285903>)()
  ad-Advice-newline-and-indent(#f(compiled-function () (interactive "*") #<bytecode 0x285903>))
  apply(ad-Advice-newline-and-indent #f(compiled-function () (interactive "*") #<bytecode 0x285903>) nil)
  newline-and-indent()
  ess-roxy-newline-and-indent()
  funcall-interactively(ess-roxy-newline-and-indent)
  call-interactively(ess-roxy-newline-and-indent nil nil)
  command-execute(ess-roxy-newline-and-indent)

**Comment by Compro-Prasad** [comment]
Do you get the same backtrace at different points of time?
