### ISSUE TITLE
Spacemacs 'eats' Mac OS keyboard shortcuts

### ISSUE THREAD

**Issue by DavidJanz** [syl20bnr/spacemacs#12411]
I'm running Spacemacs on Mac OS. When I want to switch between two windows (say, split screen, app left terminal right), I'd use command+\` and command+shift+` to go back and forth. However, Spacemacs seems to 'eat' these keypresses, they appear not be be 'forwarded' to the operating system to act upon. How can I fix this? This happens in a blank install of Spacemacs. I've tried the osx layer, this does not help.

**Comment by antonalekseev** [comment]
<kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>\`</kbd> and <kbd>cmd</kbd>+<kbd>`</kbd> are not default combinations to switch between windows in macOS. Do you use any third party software to rebind default ones: <kbd>cmd</kbd>+<kbd>tab</kbd>, <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>tab</kbd>? Theoretically, all keystrokes that reach applications has not been handled by OS and any keyboard-related software and overriding this behaviour at application level is not a trivial task.

**Comment by DavidJanz** [comment]
@antonalekseev thanks for getting back to me. Those are the default shortcuts for "Move focus to next or active window" and its inverse for Mac OS High Sierra and Mojave (likely others too?). Spacemacs is the only application I've ran into for which these shortcuts cease to function.

**Comment by albertmichaelj** [comment]
@DavidJanz You are definitely right that Spacemacs eats <kbd>cmd</kbd> + <kbd>\`</kbd> is the default for changing between open windows within the same application on Mac OS. However, Spacemacs generally uses it's own bindings for this (I think <kbd>Space</kbd>+<kbd>F</kbd>+<kbd>o</kbd> is what you are looking for). However, you can get the standard Mac OS behavior by including the following in your `.spacemacs` file:
```
(global-set-key (kbd "M-`") 'other-frame)
(global-set-key (kbd "M-~") (lambda () (interactive) (other-frame -1)))
```
To be clear, since I normally use emacs on multiple operating systems, the snippet I actually use is:
```
  (when (eq system-type 'darwin)
    (progn
      (setq mac-command-modifier 'meta)
      (setq mac-option-modifier 'super)
      (global-set-key (kbd "M-`") 'other-frame)
      (global-set-key (kbd "M-~") (lambda () (interactive) (other-frame -1)))
      ))
```
So that it is only set when I'm on Mac OS.

Hope this helps!

**Comment by DavidJanz** [comment]
@albertmichaelj thanks for getting back to me on this. 

It appears the other-frame command only works if the other frame is also an emacs frame, is that correct? cmd+` and cmd+shift+` are not restricted to windows within the same application. My usecase for cmd+` and cmd+shift+` is if I have GUI emacs split screen with iterm, and I wish to switch between the two without my hands leaving the keyboard (and without the slowdown of cmd+tab due to window ordering etc). 

Do you have a suggestion for how to achieve that?

**Comment by albertmichaelj** [comment]
@DavidJanz I don't think what you're seeing is standard mac behavior. On default settings on a Mac, <kbd>cmd</kbd> + <kbd>\`</kbd> and <kbd>shift</kbd> + <kbd>cmd</kbd> + <kbd>\`</kbd> cycle forward and backward (respectively) through windows for a single mac applications (i.e. multiple Chrome browser windows or multiple terminal windows). <kbd>cmd</kbd> + <kbd>\`</kbd> never cycles between windows of different applications as far as I can tel, only <kbd>cmd</kbd> + <kbd>tab</kbd> does that (which is not eaten by spacemacs). The keyboard shortcuts I gave you restores the default behavior exactly. I do not know how to get emacs to behave according to your non-default behavior.

**Comment by DavidJanz** [comment]
@albertmichaelj  --- just tried it on a factory reset mac at work. Putting two windows of different applications into split screen, and pressing cmd + `` switches between them. Checked the binding for cmd + `` on both, it is listed as "Move focus to next or active window". However, the description of that command online indeed appears to suggest it should only switch within a given application.

If you bring up say a browser and a terminal into split screen mode on your Mac, cmd+`` won't switch between the two for you?

**Comment by albertmichaelj** [comment]
@DavidJanz Huh, I don't know what to say. I tested split screen with Safari and Mail (so two native mac apps), and <kbd>cmd</kbd> + <kbd>\`</kbd> doesn't switch between them. I also tested this on a fresh mac virtual machine (I couldn't reset my macbook pro just to test this), and it still didn't switch apps. On my Keyboard shortcuts page, you can see what I see below. <kbd>cmd</kbd> + <kbd>\`</kbd> is "Move focus to next window" and <kbd>ctrl</kbd> + <kbd>F4</kbd> is "Move focus to active or next window". 
<img width="429" alt="Screen Shot 2019-06-17 at 9 09 58 AM" src="https://user-images.githubusercontent.com/5385923/59606708-d3618080-90df-11e9-95b6-d3c440fefcbd.png">

I'm on Mac OS Mojave, so if you are on a different version, then you may have different behavior, but I'm pretty sure that what I've described is default behavior. However, Spacemacs also doesn't let <kbd>ctrl</kbd> + <kbd>F4</kbd> go through, and I'm not sure why that is (it's not bound to anything).

**Comment by albertmichaelj** [comment]
@DavidJanz I also found [this](https://www.reddit.com/r/emacs/comments/4m9l6v/passing_keybindings_to_the_os_possibly_mac_os/) post on reddit that talks about using apple script to recover the functionality that you want. It's not a complete example, but it should point you in the right direction. You may also try setting the <kbd>option</kbd> as meta instead of command, and then it might let you use standard command shortcuts (not sure about this, and not entirely sure how you do this).
