### ISSUE TITLE
Python: How to customise toggle breakpoint (pudb)

### ISSUE THREAD

**Issue by justinekizhak** [syl20bnr/spacemacs#12420]
**Description**: If you have installed pudb then on toggle breakpoint `SPC m d b` 
Emacs inserts `import pudb; pudb.set_trace()`.

This makes sense if you want to use pudb for debugging and haven't added `export PYTHONBREAKPOINT=pudb.set_trace` in your bashrc file.

But I have set the variable and would love to have Emacs add `breakpoint()` on the toggle.

So if there was a way to customise my breakpoint by adding some lines in my `spacemacs.el` that would be awesome.

**Comment by antonalekseev** [comment]
You can redefine the whole `spacemacs/python-toggle-breakpoint` function in your configuration file adding one more condition like `((getenv "PYTHONBREAKPOINT") "breakpoint()")` or replacing entire `cond` with `"breakpoint()"` to insert said string unconditionally. In former case make sure that `PYTHONBREAKPOINT` is actually passed to Emacs from your shell environment.

https://github.com/syl20bnr/spacemacs/blob/8c0b8c3440a33df2c291088c47e75fd5e4fbbb61/layers/%2Blang/python/funcs.el#L38-L54

**Comment by justinekizhak** [comment]
Does this means I have to edit `funcs.el` file? 
I would be happy to not edit any files inside the `emacs.d`.

**Comment by antonalekseev** [comment]
No, you should place new definition in your config file, particularly under `dotspacemacs/user-config` after layers configuration. Snippet above provided for reference, to base your new definition upon it.

**Comment by justinekizhak** [comment]
Thanks. 
Adding these lines to `dotspacemacs/user-config` worked. 

Also now the function checks for environment variables and only if it find 
`PYTHONBREAKPOINT` == `pudb.set_trace` 
the breakpoint uses `breakpoint()` 
else `import pudb; pudb.set_trace()`.

```emacs-lisp
  (defun spacemacs/python-toggle-breakpoint ()
     "Add a break point, highlight it."
     (interactive)
     (let ((trace (cond ((spacemacs/pyenv-executable-find "trepan3k") "import trepan.api; trepan.api.debug()")
                        ((spacemacs/pyenv-executable-find "wdb") "import wdb; wdb.set_trace()")
                        ((spacemacs/pyenv-executable-find "ipdb") "import ipdb; ipdb.set_trace()")
                        ((spacemacs/pyenv-executable-find "pudb") "import pudb; pudb.set_trace()")
                        ((spacemacs/pyenv-executable-find "ipdb3") "import ipdb; ipdb.set_trace()")
                        ((spacemacs/pyenv-executable-find "pudb3")
                         (if (string= (getenv "PYTHONBREAKPOINT") "pudb.set_trace")
                             "breakpoint()" "import pudb; pudb.set_trace()"))
                        ((spacemacs/pyenv-executable-find "python3.7") "breakpoint()")
                        ((spacemacs/pyenv-executable-find "python3.8") "breakpoint()")
                        (t "breakpoint()")))
           (line (thing-at-point 'line)))
       (if (and line (string-match trace line))
           (kill-whole-line)
         (progn
           (back-to-indentation)
           (insert trace)
           (insert "\n")
           (python-indent-line)))))
```
