### ISSUE TITLE
How to make SPC work in calc-mode

### ISSUE THREAD

**Issue by johnbcoughlin** [syl20bnr/spacemacs#12422]
Reproduction:

- Open emacs
- `SPC a c c`
- Press `SPC`, to use it as the spacemacs leader.

Unfortunately, calc mode binds SPC by default to `calc-enter`. You can unbind it with 

```
  (with-eval-after-load 'calc
    (define-key calc-mode-map " " nil)))
```

However, this just gives `SPC is undefined` instead of opening the spacemacs menu. How can I get calc-mode to recognize the spacemacs leader key?

**Comment by duianto** [comment]
This seems to work for me:
```elisp
    (with-eval-after-load 'calc
      (define-key calc-mode-map " " spacemacs-cmds))
```

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3d4e6fc0d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey colors emacs-lisp git helm markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by johnbcoughlin** [comment]
Thank you! I tried to figure out what function `SPC` was bound to normally and use that, but typing `C-h k SPC` just tries to start a key chord.

**Comment by duianto** [comment]
One way of finding out what `SPC` calls, is to call `describe-mode` with `C-h m` or `SPC h d m` and then search for `spc`. One of the entries are:
```
<evilified-state> SPC           spacemacs-cmds
```
