### ISSUE TITLE
:b# doesn't work right

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#1242]
In vim <kbd>:b#</kbd> switches to the previous (alternate?) buffer, in spacemacs that leads to 'No buffer with name '#' exists. Create new buffer?' prompt instead.

**Comment by syl20bnr** [comment]
This is a missing emulation from evil, you can open an issue here: https://bitbucket.org/lyro/evil/wiki/Home
If you do, add a reference to it here so we can track it.

**Comment by TheBB** [comment]
No response from @tko.
