### ISSUE TITLE
Ivy layouts buffer switching doesn't respect layout when completing without candidates

### ISSUE THREAD

**Issue by AlexLewandowski** [syl20bnr/spacemacs#12434]
#### Description :octocat:
Using ivy completion the layout buffer list in layout_a can result in buffers appearing from other layouts if ivy has no candidates in layout_a. This is confusing and inconsistent. A possibly related issue: the buffer list with ivy shows all open buffers in a new layout if no buffers are associated with that layout. This behavior should not happen with SPC l b. Although, maybe it is permissible for SPC b b. (This is different from #6300)

#### Reproduction guide :beetle:
- Start Emacs
- Create a layout named test and open a file "test.py"
- Create a new layout called new, SPC l b shows all buffers
- In the layout "new", open another file "new.py"
- SPC l b only shows new.py but typing test shows test.py

*Observed behaviour:* :eyes: :broken_heart:
The layout buffer list shows open buffers from other layouts when completing with ivy/swiper without candidates.

*Expected behaviour:* :heart: :smile:
The layout buffer list should only show open buffers in its respective layout, even when completing with ivy/swiper without candidates.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1.92
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5b7b5f2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(yaml html
      (python :variables python-backend 'anaconda)
      ivy bibtex auto-completion better-defaults emacs-lisp git markdown
      (org :variables org-enable-org-journal-support t)
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'right)
      syntax-checking
      (latex :variables latex-enable-auto-fill nil)
      markdown pdf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LCMS2

**Comment by duianto** [comment]
Confirmed.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 365c92bae)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey colors emacs-lisp git ivy markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
