### ISSUE TITLE
[question] How to config the Python layer to use Microsoft Python Language Server properly?

### ISSUE THREAD

**Issue by patzhang** [syl20bnr/spacemacs#12436]
Hi there, I am trying to use Microsoft Python Language Server with the Python, LSP layers with the develop branch Spacemacs on Ubuntu 18.04. It kind of works with the following configuration.
```
(python :variables
         python-backend 'lsp
         python-lsp-server 'mspyls
         ;; These two lines do not work for me.
         ;; python-backend 'lsp-ms
         ;; python-lsp-git-root "~/.python-language-server-ms.repo/")
```
But the code completion is not as good as VS Code. So my questions are
1) Is it correct to use this configuration `'lsp` and `'mypyls` with Microsoft Python Language Server?
2) Am I supposed to get the same code completion as VS Code on the same project?
3) Does the new `'lsp-ms` works? The server did not start when I use `'lsp-ms` and `python-lsp-git-root`.
4) If both configurations work with MS Python Language Server, what are the differences?

I did not fully understand [this section in the Python layer](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/python#language-server-protocol)

Any help or suggestions are highly appreciated. Thanks.
@cormacc and @yyoncho any suggestions? Thanks.

**Comment by yyoncho** [comment]
> But the code completion is not as good as VS Code. So my questions are

can you elaborate?

> Does the new 'lsp-ms works? The server did not start when I use 'lsp-ms and python-lsp-git-root.

What does happen? Logs? \*lsp-log\*.

**Comment by patzhang** [comment]
> > But the code completion is not as good as VS Code. So my questions are
> 
> can you elaborate?

When I use the following configuration, the LSP layer runs with Microsoft python language server when I open a python file.
```
(python :variables
         python-backend 'lsp
         python-lsp-server 'mspyls)
```
However, I do not get code completion sometimes. The pop-up documentation works correctly. When I have the code completion popup, it does not show the correct item at the top. This may be a configuration issue with company.

![IMG_20190613_165741](https://user-images.githubusercontent.com/1183059/59465316-869d5180-8e22-11e9-8b13-b7a9cdb6cdea.jpg)

![IMG_20190613_165536](https://user-images.githubusercontent.com/1183059/59465349-9a48b800-8e22-11e9-92c9-51692a3b5a0c.jpg)

![IMG_20190613_165817](https://user-images.githubusercontent.com/1183059/59465364-a7fe3d80-8e22-11e9-8a3a-eaa262b98885.jpg)

![IMG_20190613_170004](https://user-images.githubusercontent.com/1183059/59465409-c19f8500-8e22-11e9-98ce-d803ca0a81a9.jpg)

![IMG_20190613_170252](https://user-images.githubusercontent.com/1183059/59466077-4939c380-8e24-11e9-9c1e-e686070f059a.jpg)

Comparing to the code completion in VS Code
![IMG_20190613_170415](https://user-images.githubusercontent.com/1183059/59466241-be0cfd80-8e24-11e9-8357-e8f29270494f.jpg)

![spacemacs2](https://user-images.githubusercontent.com/1183059/59465507-f90e3180-8e22-11e9-8fe4-d34fb084ff27.png)
Sometimes, the above message comes up.
`LSP :: Object reference not set to  an instance  of an object.` 


![spacemacs1](https://user-images.githubusercontent.com/1183059/59465447-d2e89180-8e22-11e9-994f-3142c913fddf.png)

> > Does the new 'lsp-ms works? The server did not start when I use 'lsp-ms and python-lsp-git-root.
> 
> What does happen? Logs? *lsp-log*.

When I use the following configuration, the LSP layer and Microsoft python language server are not triggered when I open a python file.
```
(python :variables
          python-backend 'lsp-ms
          python-lsp-git-root "~/.python-language-server-ms.repo")
```
Because the LSP layer does not run, there is no *lsp-log*.  I tried `SPC SPC lsp-mode`, but it only enabled the LSP mode without running Microsoft python language server. This is the messages when I open a python file.

![spacemacs-lsp-ms-1](https://user-images.githubusercontent.com/1183059/59466011-23acba00-8e24-11e9-8515-a5b46ffa03a4.png)

![IMG_20190613_172329__01](https://user-images.githubusercontent.com/1183059/59465979-0c6dcc80-8e24-11e9-9438-164eb88e1bac.jpg)

I also tried to check out the latest develop branch of Spacemacs and only added the above python layer configuration and lsp layer. It does not use my custom configurations at all. However, the `'lsp-ms` still does not work.

Emacs: 26.2
Spacemacs (develop): 365c92bae5f600d0548eb2bb7f43ebb1de0ae18d
Microsoft python language server: [0.2](https://github.com/microsoft/python-language-server/releases/tag/0.2)
I tested on both Ubuntu 18.04 and Mac OSX.

Please let me know if you need more information. Thanks.

**Comment by cormacc** [comment]
Hi @patzhang 
Re. confusion over configuration to use language server checked out/built from git, that's my bad -- failed to update that section of the documentation when responding to change requests during PR review.
I'll raise a PR to correct shortly, but in the meantime this should work...

```
  (setq-default dotspacemacs-configuration-layers
    '((python :variables
              python-backend 'lsp
              python-lsp-server 'mspyls
              python-lsp-git-root "~/dev/python/python-language-server")))

```
That works for me with current spacemacs develop and and ms language server built from latest checkout. My original PR didn't use the `python-lsp-server` variable and had `lsp` and `lsp-ms` backends, but one of the reviewers sensibly pointed out that this was nasty :)

Re. differences in completion from vscode, I can't help you there. There are a couple of layers of abstraction here -- spacemacs python layer -> lsp-mode -> lsp-python-ms -> the actual language server.
So even using the same language server (and version) under the hood, it's probably used quite differently in the two contexts.

**Comment by patzhang** [comment]
Hi @cormacc, many thanks for the update.

I will use this setup for a few weeks on my "large" virtualenv and see how much better it is than the anaconda backend. I am sure LSP is the way going forward.

Also, thanks for explaining the layers for the MS PLS. I am experimenting with `company-lsp-cache-candidates 'auto` ATM. I hope the code completion will be as good as VS Code sooner or later.

One more thought, maybe in the future, we can have another backend for [Kite](https://kite.com/). :smile:

**Comment by yyoncho** [comment]
This is already fixed.
