### ISSUE TITLE
Hybrid editing style?

### ISSUE THREAD

**Issue by mkcode** [syl20bnr/spacemacs#1244]
This is a discussion issue.

I've been playing around with the following in my dotspacemacs config:

```elisp
  (define-key evil-emacs-state-map [escape] 'evil-normal-state)
  (setq evil-emacs-state-cursor '("chartreuse3" (bar . 2)))
  (defalias 'evil-insert-state 'evil-emacs-state)
```

Basically, just a drop in replacement of insert-state with emacs-state. So far, it's been working well, and I've been enjoying using this. I think of this as a hybrid mode, combining the best of both worlds from emacs and vim.

 * Any hidden issues with doing this, that I am not aware of?
 * Consider adding a `'hybrid` option to `dotspacemacs-editing-style`?

Quick background on me; I'm a long-time emacs user, that learned vim and wanted to setup emacs with evil-mode....then discovered spacemacs. Holy-mode doesn't do it for me b/c I loose all the nice hjkl-nav and evil-normal-state by default. And I prefer emacs editing keybindings, b/c I know them so well and they are consistent with terminal and others.

**Comment by mkcode** [comment]
Adding the evil-insert-mode-exit-hooks to evil-emacs-mode-exit-hooks would improve this as well.

**Comment by felipe-barros** [comment]
This is a great idea and I would love to see this implemented and discussed further.
Makes total sense in the Spacemacs context: the ultimate marriage between Vim and Emacs where you have both worlds activated simultaneously.

I'm a Vim user who recently switched to Spacemacs, but I've been studying pure Emacs and I'm trying to learn both ways of thinking text manipulation.

**Comment by mkcode** [comment]
@felipe-barros - FYI - I stopped using the code snippets in this PR due to some issues. Most notable was that this broke undo functionality, which was a deal breaker for me.

I'd love to see this idea explored more. Unfortunately it looks like it would require some deep integration into evil and emacs mode.

**Comment by felipe-barros** [comment]
Oh, thats sad, I had this in my mind all this days and was planning on trying it soon :/ I really think this is the way I want to roll... maybe when I have the technical elisp powers to dig this deeper.

**Comment by geo7** [comment]
as an option yeah why not... seems like it might be nice for some. 

For default I wouldn't be too keen on it though, as `insert` mode is strictly for typing, there shouldn't be any reason to be in `insert` mode if you're not entering text. As soon as one stops entering text `esc` sequence should be entered and then editing is done from `normal` mode, so in this respect I have no use for editing functionality in insert mode; I strictly use it for `insert`ing text :)

**Comment by felipe-barros** [comment]
@geo7 Yeah, that is the normal Vim-like workflow. If, like me, you want to use both Vim and Emacs style of editing, it makes a lot of sense to have holy mode enabled when you enter insert mode. Its a paradigm shift, no less.

Changing from Evil to Holy is fairly easy though, and if the implementation of this style is as hard as it seems, it may not be worthy, but I think it would be really badass. ;)

**Comment by felipe-barros** [comment]
@vkz pointed out that, if you set your Holy-mode as your default, pressing `ESC` puts you in Evil normal mode until you press `i`, which I believe is what we wanted!

I've been using Evil since day one and had absolutely no idea that Holy worked like this. Brilliant!

**Comment by vkz** [comment]
appears that something like this landed at least in `develop` branch, I stumbled over this feature just by assuming that something like it should totally exist and lo and behold it does. It's pretty neat.  Whoever did this deserves our thanks.

**Comment by vkz** [comment]
maybe it's just an accident but ESC in `holy` puts you in `normal` vim, `i` in normal puts you back in `holy`. This also kinda maybe solves (to some extend) the issue of nav keys in Dvorak #2443

**Comment by felipe-barros** [comment]
@vkz I'm not in `develop` and it's working here :D Hope this is here to stay, I really want to get used to this style.

**Comment by felipe-barros** [comment]
Well, one day in and I can tell I really like it, but the ideal scenario for someone coming from Vim is Evil as major and Holy as secondary (as was the original idea), exactly the opposite of what happens with Holy mode now.

At least now we know it is probably possible without too much hacking.

**Comment by syl20bnr** [comment]
> ESC in holy puts you in normal vim, i in normal puts you back in holy

> Hope this is here to stay

This is here to stay. Actually `holy` does not replace evil at all, Evil is always used no matter the style. `holy`only play with the Evil states to replace `insert` by `emacs` state and make `emacs` the default state.

If you want to have the `normal` state as default even in `holy` then add this to your `dotspacemacs/init` function of the dotfile:

```elisp
  (add-hook 'holy-mode-hook (lambda () (setq evil-default-state 'normal)))
```

**Comment by syl20bnr** [comment]
But all evilified buffer will be in `emacs` state.

I think you should ignore the `holy` mode and just add this to your `dotspacemacs/config` in the dotfile:

```elisp
(defadvice evil-insert-state (around benedictus-dominus disable)
  "Preparing the holy water flasks."
  (evil-emacs-state))
```

Hum maybe renamming the symbols would be a good idea :-)

**Comment by felipe-barros** [comment]
hauhauhauhahuh Oh yeah @syl20bnr ! Thank you!

If Spacemacs was a hacked video game, this would be in the menu as `enable God-mode`!

**Comment by syl20bnr** [comment]
:-)

I made a typo in the example above, `disable` should be `activate`.

**Comment by vkz** [comment]
very cool :+1: thank you!

**Comment by zilongshanren** [comment]
@syl20bnr  
How to use `C-[` to behavior like `ESC` in holy mode? I have tried the hybrid method above, it works great, but I often use `C-[` instead of pressing `ESC`.

Any suggestions?

Thanks. :+1:

**Comment by vkz** [comment]
You'd probably need to take the `C-[` back first:
```
(define-key input-decode-map [?\C-\[] (kbd "<C-[>"))
```
then bind it to the same thing as ESC I guess
```
(bind-keys ("<C-[>" . evil-normal-state))
```

**Comment by vkz** [comment]
you can use the same trick to take the `C-i` back (may not be a good idea if you run Emacs in terminal)

**Comment by zilongshanren** [comment]
@vkz  It works great. :+1: 
BTW, how to map ESC also to evil-normal-state in evil-emacs-state?

**Comment by vkz** [comment]
not sure what u mean. ESC should already be bound in holy mode. But you want to do it by hand any one of these will do:
```elisp
   (define-key evil-emacs-state-map [escape] 'evil-normal-state)
  (bind-keys :map evil-emacs-state-map
             ("<escape>" . evil-normal-state))
```

**Comment by TheBB** [comment]
> not sure what u mean. ESC should already be bound in holy mode.

What @zilongshanren wants is to use emacs state as a substitute for insert state, but not to enter that state by default in new buffers (which is what holy mode does). He's looking for a way to get the first effect without holy mode, so that's why escape doesn't work for him by default.

**Comment by zilongshanren** [comment]
@vkz  
Yes, I'm not using holy mode.  @TheBB  got what I mean here.
Thanks to both of you.

**Comment by felipe-barros** [comment]
Hmm, now I am in Evil with the following code in my dotspacemacs/config:

```
(defadvice evil-insert-state (around benedictus-dominus activate)
  "Preparing the holy water flasks."
  (evil-emacs-state))
```

And now Evil is activated by default and whenever I press an insert command, it puts me in Holy mode instead.

But I can't leave Holy mode! Escape doesn't work to put me back in Evil.

**Comment by TheBB** [comment]
@felipe-barros Follow some of the advice of @vkz above to bind escape in Emacs state.

**Comment by mkcode** [comment]
@syl20bnr - Amazing! Thanks for getting this right!

I'd like to wrap this up by codifying it into a PR. @syl20bnr - Would you accept a PR adding a 'hybrid option to `dotspacemacs-editing-style` with documentation?

**Comment by mkcode** [comment]
> If Spacemacs was a hacked video game, this would be in the menu as enable God-mode!

@felipe-barros  - :+1:  :beers:

**Comment by syl20bnr** [comment]
> I'd like to wrap this up by codifying it into a PR. @syl20bnr - Would you accept a PR adding a 'hybrid option to dotspacemacs-editing-style with documentation?

Would make sense and save a lot of time for some users willing to test this, also it matches the README introduction, so I'm all for it. The tricky part is the documentation :-D

**Comment by romanoaugusto88** [comment]
This is really a great idea!
But how we could add compatibility with `evil-repeat`?

**Comment by myrjola** [comment]
I also think this hybrid approach gives the best of both worlds. It turns out that I use very few insert-state keybindings. I noticed I was using `C-p` for completion, Spacemacs has bound that to `hippie-expand`, which is also bound to `M-/`, so it wasn't too hard to settle in. Back in my Vim days I used `C-r` to paste from register, but that has been surpassed by the ingenious paste-micro-state.

I'll also give my vote to include 'hybrid as an option to `dotspacemacs-editing-style`. I haven't even noticed anything breaking so far.

**Comment by CestDiego** [comment]
Please make it an editing option! :) this would save lots of confusion, also maybe hybrid is not reflecting the holyness, and evil...maybe call it `demigod` mode?

**Comment by justbur** [comment]
I want this too. Maybe we can implement it now before worrying about documentation to work out any quirks?

**Comment by syl20bnr** [comment]
I would not push the metaphor too much on this one even though it is fun ;-)
We can stick with `vim`, `emacs` and add `hybrid` as a new value.

Anyone willing to PR it is welcome ;-D

**Comment by syl20bnr** [comment]
Thanks to @justbur you can now try `hybrid` in your dotfile :-)

**Comment by CestDiego** [comment]
evil-escape key isn't working ;-; at least for setups that aren't `fd` as in mine ( `nj`)

**Comment by sooheon** [comment]
Can confirm evil-escape breaks. I've skimmed this thread, and I'm still not sure I understand the difference between holy and hybrid modes other than which state buffers open in by default. Holy mode is essentially drop-in replacing insert state with emacs state, no? Hybrid drop in replaces insert state with emacs state also, but names it insert state, and sets default state to normal? Do I have the right idea?

**Comment by TheBB** [comment]
Holy mode doesn't replace insert state with emacs state, it just puts everything emacs state by default. It's still possible to enter insert state by `C-z`-ing out of emacs state and entering insert state as you normally would.

You have basically the right idea for hybrid mode. It doesn't set any default states, so whatever settings you (and Spacemacs) have done will remain. Mostly that means normal state by default. It doesn't actually substitute emacs state by insert state. Instead it deletes the insert state keymap so that all the keybindings that *would* be captured by that is passed through to whatever else.

**Comment by justbur** [comment]
I threw it together to test, so I'm not surprised evil escape doesn't work. If you report any issues here I'll fix them as soon as I can. 

@TheBB explained what I did which is essentially to remove the insert state map and add back the escape key.

**Comment by justbur** [comment]
In #2645, I switched to explicitly removing keybindings for insert mode that are defined in evil-maps.el, so it won't unintentionally remove any escape-like bindings that are already set. 

What do you all think of using the same color as emacs state? Technically, I haven't touched emacs state, so this is possibly confusing but I wanted to change the insert mode color to remind you that you are not in the traditional insert state.

**Comment by justbur** [comment]
Also, I don't use evil-escape so I'm going to have to rely on someone who does to test it with their setup.

**Comment by syl20bnr** [comment]
Hmmm I don't know where my head was yesterday but why not use the same technic as in holy-mode ? That is using just an advice and modify the emacs state cursor to bar ?

@sooheon  Differences between emacs and hybrid:
- in hybrid the default state is normal instead of emacs
- in hybrid some buffers are evilified, not in emacs

I think that's all.

**Comment by justbur** [comment]
Just to put it slightly differently: hybrid assumes you still like normal/visual/etc mode, meaning you start in normal mode and you use evilified buffers. The only change is to remove any vim-related key bindings in insert mode.

holy mode behaves like emacs, starting in emacs state, not evilifying buffers, etc. 

From @vkz's comments above there are some subtle differences too around interpreting keys, which may show up in the terminal (I haven't investigated). That's why `C-[` wasn't sending a traditional escape in holy mode. 

@syl20bnr I don't understand your comment about the cursor. Is there something wrong with the way I did it?

**Comment by syl20bnr** [comment]
@justbur  Nothing wrong, I mentioned it because it is a cool idea :-)

To be more accurate I think we can avoid all the remapping stuff by using the advice [here](https://github.com/syl20bnr/spacemacs/issues/1244#issuecomment-126183700) and keep the cursor modification.

**Comment by justbur** [comment]
@syl20bnr but [this](https://github.com/syl20bnr/spacemacs/issues/1244#issuecomment-126230055) shows that there is more going on in emacs state. I also think the changes I made in #2645 will handle evil-escape stuff gracefully, which will not carry over without modification to emacs state.

**Comment by syl20bnr** [comment]
> this

This is just an entry to add to emacs state map right ? Same kind of thing as [this](https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/local/holy-mode/holy-mode.el#L61) in holy mode. Maybe we should add it to emacs state as well. All in all hybrid is like holy mode except for the default states.

In my opinion it is lighter to just take the emacs state and add the missing bits in the map.

**Comment by justbur** [comment]
My reasoning was that the creators of evil made those distinctions in emacs state for a reason, and I wanted to keep them around for those people that they're useful for (I don't know why they are useful, but somebody thought they were). If you advise insert state like that you remove the distinction. 

To me, using insert state was more natural, because current (and future?) methods of escaping insert mode in evil presumably target insert state and not emacs state. 

That being said, I don't really care that much since for my purposes they are equivalent.

**Comment by syl20bnr** [comment]
Both approaches are equally correct depending on how we define what the hybrid style. As long as the definition fits the implementation it's ok for me.

I'll for your implementation so we have to be accurate (I say this essentially for myself :-)) when defining the style, that is: 

> hybrid style replaces the insert state key bindings with the emacs key bindings.

Then shortcut to define it like I did is wrong:

> hybrid style replaces the insert state by emacs state

or 

> hybrid style change the default state of holy mode to normal state

etc...

**Comment by mkcode** [comment]
@justbur - Thanks for taking charge of getting this PR in! The toggle is nice, and it's working very well for me.

Looking over the implementation, I'd have to agree, that I think it would be better to use evil-emacs-state rather than unsetting evil-insert-state keybindings. Reasons:
 * A user setting a keybinding on evil-emacs-state-map would not work, which is unintuitive.
 * I would prefer to set keybindings on evil-emacs-state-map rather than global-map, because it's more explicit and is only set when it should be.
 * Easier for spacemacs to customize both holy-mode behavior and hybrid-mode behavior at the same time.

I can't think of a case where we would want to distinguish behavior between the general holy-mode emacs-state and entering emacs-state via a normal-mode insert command. Can anyone?

Also FWIW - my preference would be to leave the cursor the exact same evil-insert-state-cursor.

**Comment by syl20bnr** [comment]
I have to +1 to @mkcode. I think it is easier to explain what the hybrid style is if we are effectively using the emacs state instead of mutating the insert state.

**Comment by syl20bnr** [comment]
In both implementations we have the same culprit: duplication of states. In @justbur implementation we have duplication by copying and in the holy mode we have duplication by aliasing (sort of).

The ideal solution would be to synchronize the states... nobody wants to do this :-)

So the debate is about what hybrid means, is it to use emacs state during insertion or is it to import emacs bindings in insert state ?

**Comment by justbur** [comment]
But there's a big difference and that's how you get back to normal mode. For someone who googles it, none of these answers will work if you if you decide to use emacs-state 

http://stackoverflow.com/questions/10569165/how-to-map-jj-to-esc-in-emacs-evil-mode
http://stackoverflow.com/questions/19150003/binding-the-escape-key-to-a-keychord-for-evil-mode
http://blog.jenkster.com/2013/02/mapping-jk-in-emacs-evil-mode.html

Those are three examples, but the natural thing to do is to target the insert state map if you are trying to define a new way of escaping back into normal mode, and my implementation allows these to work. 

@mkcode I guess if you bound to evil-emacs-state-map you might be in for a surprise, but why not just bind to evil-insert-state-map? It would have exactly the same effect. I'm not removing the map, just the keys that evil puts into it.

**Comment by justbur** [comment]
I'm fine with whatever cursor you all decide on. I could care less about that, as long as it's different from normal mode and doesn't start flashing.

**Comment by mkcode** [comment]
> I'm fine with whatever cursor you all decide on. I could care less about that, as long as it's different from normal mode and doesn't start flashing.

Translucent, neon, and blinking. Agreed? :-P

**Comment by syl20bnr** [comment]
Both of you have very good points... I guess depending on which side the user comes from he will expect one or the other definition.

If I come from vim style then @justbur point of view is better.
If I come from emacs style then @mkcode point of view is better.

**Comment by justbur** [comment]
@mkcode You have a deal if it's fuchsia

**Comment by syl20bnr** [comment]
What color gives green and blue together ?

**Comment by justbur** [comment]
@syl20bnr I'm happy to leave the decision up to you. I think of hybrid conceptually as all of vim's modes with insert state removed. holy-mode already gives the option to default in emacs state and go to normal mode if you like.

**Comment by syl20bnr** [comment]
Let's set these rules:
- emacs is `left` and vim is `right`, it models correctly that emacs is all about copyleft and vim is always right.
- then `hybridl` is @mkcode implementation and `hybridr` is @justbur implementation

Probleme solved.

**Comment by syl20bnr** [comment]
Seriously, would it be too confusing to have `hybrid-emacs` and `hybrid-vim` ?

`hybrid-emacs` uses the emacs state for insertion.
`hybrid-vim` uses the insert state for insertion.

**Comment by mkcode** [comment]
@syl20bnr - Yes, that would be way too confusing. haha

**Comment by justbur** [comment]
I think you're asking for a lot of questions from people who want to
understand the difference.

**Comment by TheBB** [comment]
In fact, make `dotspacemacs-editing-style` a floating point number between 0 and 1.

**Comment by syl20bnr** [comment]
Damn, so we cannot solve this :-)

The difference is where the user maps her key binidings. BTW does people do this ?

**Comment by justbur** [comment]
Haha @TheBB you beat me to it

**Comment by syl20bnr** [comment]
Between [0, 0.5) and (0.5, 1], perfect hybrid style 0.5 is not defined :-(

**Comment by syl20bnr** [comment]
I will try to put this simply:

- if I tweaked my bindings in `emacs` state and I go hybrid, I want my bindings.
- if I tewaked my bindings in `insert` state and I go hybrid..... you know what, I want my bindings.

**Comment by justbur** [comment]
Ok one more argument and then I'm done I promise. Hybrid is still predominantly a vim editing style. There are modes, you start in normal model, and all of your hjkl keybindings work by default. In that sense, calling it a modified insert state is what I think will resonate with most (but clearly not all) people

**Comment by syl20bnr** [comment]
Time to sleep a bit on it and think out of the box :-)

**Comment by justbur** [comment]
Regardless, @syl20bnr can you merge #2645 when you get a chance? Even if we change the implementation later, the current state of hybrid-mode is broken for those using evil-escape at least.

**Comment by syl20bnr** [comment]
Of course!

**Comment by mkcode** [comment]
Ok! Here it is: `evil-hybrid-mode-map`

User can choose to copy keybindings from the mode-map of their choice onto it. 

We're done here.

**Comment by mkcode** [comment]
After thinking about this some more, I'm convinced that we should use emacs-state because of this really important point:

 * We can't expect to manage all the combinations of keybindings that users will want! What if I want my `C-r` to fire a rocket ship? There is no way we can tell (without black magic) if keybinding that is used by the default evil-insert-state-map was overridden by the user. Essentially, a user adding `(define-key evil-insert-state-map (kbd 'C-r') 'butterfly)`* to their config would be unset in hybrid mode.

*https://xkcd.com/378/

**Comment by CestDiego** [comment]
@mkcode but if the user adds all it's evil-insert-state-map modifications before the init function then this may be posible? D:

**Comment by justbur** [comment]
@mkcode You're not going to like this answer, but I can handle that case fine. I'll only remove the bindings if they're set to the default insert state commands.

**Comment by justbur** [comment]
Besides `butterfly` really belongs in the `global-map` anyway

**Comment by mkcode** [comment]
@CestDiego - Actually - I think a post init would do it.

@justbur - Yeah - you're right. I'll stop arguing.

**Comment by justbur** [comment]
There's also insert state entry and exit hooks that you can use. 

For those who understand what's going on it makes no difference which state/map we use. What I'm concerned about is what is going to be the more natural for people to understand and have the more surprising unintended side-effects. 

I'm simply picturing a lot of bug reports of the form "I enabled hybrid-mode and now my [insert fancy way of escaping insert mode that I found on google] won't work anymore".

**Comment by CestDiego** [comment]
I look forward to this hybrid mode :3 I'm testing it right now I see that `C-r` in shell-mode doesn't tries to insert from the register anymoar. and my `C-j` `C-k` keybindings that I defined for insert-mode in my config still work for going back in history as well(time to rebind them as now `C-r` works :) )

Still though...I was getting used to having `C-k` in insert mode to have the`insert char` or something like that..not it just kills the line (like in emacs). This is awesome :3

**Comment by justbur** [comment]
@CestDiego `kill-line` is in the global-map, so you can use this to override it with the old `C-k` behavior

```elisp
(global-set-key "\C-k" 'evil-insert-digraph)
```

**Comment by justbur** [comment]
Ok, I ended up implementing a special map for hybrid mode anyway, which is along the lines of what [this comment](https://github.com/syl20bnr/spacemacs/issues/1244#issuecomment-130728149) suggested. So for example, @CestDiego you can now do

```elisp
(define-key hybrid-mode-insert-state-map "\C-k" 'evil-insert-digraph)
```
 if you like. This keymap will only be active in "insert mode" when hybrid-mode is active and will never be touched (by hybrid-mode at least). I think with this keymap all of the above arguments are handled with hybrid-mode.

**Comment by CestDiego** [comment]
I'm loving this! :D I'm experimenting having this `hybrid` thing too in the Whole OS. Enabling Emacs keybindings in the chrome address bar and using vimium to navigate but using C-f C-b in input tags. <3. But it also works for all kind of input of text in any gnome app. 

I just had to add:
```
gtk-key-theme-name="Emacs"
```

to my .gtkrc-2.0

**Comment by CestDiego** [comment]
@syl20bnr in evil-insert state `C-o` made it possible to execute commands from normal state, so that one could use `SPC` but in the hybrid mode this is emacs-state so that's nonexistent and instead there is open-line. giving no way of executing `SPC`.;

So how do we access the leader? is there an special `M-` commands that replaces `SPC` in holy?

**Comment by TheBB** [comment]
@CestDiego Check your dotfile for `dotspacemacs-emacs-leader-key` and `dotspacemacs-major-mode-emacs-leader-key`. By default they are `M-m` and `C-M-m`.

**Comment by CestDiego** [comment]
Omg I thought these were only active when holy mode was enabled ;_; it *is*
the best of both worlds

**Comment by sooheon** [comment]
I think this could be resolved satisfactorily if there was just one toggle added to the holy style, to set the default state as normal or emacs. Those who subscribe to @justbur's idea of hybrid mode, which strips insert-state of all its default vimmy-bindings, can use that. Those who would like the emacs experience, with occasional evil goodness can use the current holy mode. That leaves people like me, who want the insert state to be replaced by emacs state (not modified to be *like* emacs state), *but still want to default to normal state*, and we can use holy style with the toggle to set default state as normal. Thoughts?

**Comment by justbur** [comment]
I was curious so I went through the source of evil to get a better idea of what the differences are and here's a list of things that you should expect to break/change if you use emacs state with normal mode:

- `evil-repeat` ("." command in normal mode)
- repeated insert commands from normal mode like 80i-
- `evil-want-fine-undo` (way to control the coarseness of the undo information)
- `evil-move-cursor-back`
- escape key handling as mentioned above

This is just fyi

**Comment by justbur** [comment]
By the way @sooheon 
```elisp
(setq evil-default-state 'emacs)
```
might be the toggle you are looking for

**Comment by sooheon** [comment]
@justbur Neither your snippet nor @syl20bnr 's snippet above really work as is. Yours doesn't actually take effect with editing style 'emacs (which overrides it), and syl20bnr's snippet which advices every instance of holy-mode screws up default states in *spacemacs*, *help*, *info* buffers etc which should be evilified or motion state.

**Comment by justbur** [comment]
@sooheon I'm struggling to understand what your concerns are with the way I've implemented it, since everything you're describing (evilified buffers, default normal state, etc.) is taken care of for you. Maybe you could explain the problem you are having/forsee and it will be easier for me to fix it in my code rather than trying to hack holy-mode to make it work for you. 

BTW I don't think you can `defalias` keymaps

**Comment by sooheon** [comment]
I think the way you've implemented it is great, and better than anything we had before. The defalias I was referring to was what @mkcode had in the very first post, which I've been using since I saw, mostly for compatibility with cider-debug and multiple cursors. I think my preferences are to err on the side of better compatibility with emacs-centric packages when in emacs-state than on the side of evil compatibility with how it treats insert state. This may be the worse approach, and I do see the benefit of better evil compatibility as well, the more I think about it.

**Comment by justbur** [comment]
@sooheon  Sorry I was thinking about the keymaps and not the functions themselves (`defalias` is just for functions I believe). 

Unless you touch the insert-state keymap or the emacs-state keymap (this one is empty by default and doesn't even show up in the evil docs) the only differences seem to be what I mentioned [here](https://github.com/syl20bnr/spacemacs/issues/1244#issuecomment-131184317) and all of that is processing that takes place when you go back into normal mode to retain the vim commands that span normal and insert mode (like evil-repeat). 

Anyway, I really don't think you have anything to worry about with respect to compatibility, and if the odd edge case arises we'll find a work around. Insert state is little more than a keymap that overlays emacs bindings, so after you remove that you're basically working in traditional emacs.

**Comment by syl20bnr** [comment]
Just to be clear about what is the holy mode, hole mode is plain emacs
experience but with a twist which is that anyone can go into normal state
by pressing ESC. So it is expected to not have anything in evilified or
even motion state. To get this you want vim style or hybrid.

Le vendredi 14 août 2015, Justin Burkett <notifications@github.com> a
écrit :

> @sooheon <https://github.com/sooheon> Sorry I was thinking about the
> keymaps and not the functions themselves (defalias is just for functions
> I believe).
>
> Unless you touch the insert-state keymap or the emacs-state keymap (this
> one is empty by default and doesn't even show up in the evil docs) the only
> differences seem to be what I mentioned here
> <https://github.com/syl20bnr/spacemacs/issues/1244#issuecomment-131184317>
> and all of that is processing that takes place when you go back into normal
> mode to retain the vim commands that span normal and insert mode (like
> evil-repeat).
>
> Anyway, I really don't think you have anything to worry about with respect
> to compatibility, and if the odd edge case arises we'll find a work around.
> Insert state is little more than a keymap that overlays emacs bindings, so
> after you remove that you're basically working in traditional emacs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/1244#issuecomment-131223920>
> .
>


-- 
-syl20bnr-

**Comment by robbyoconnor** [comment]
Have docs been updated?

**Comment by mkcode** [comment]
Some good ideas in #2676. Feedback is appreciated.

**Comment by mkcode** [comment]
@robbyoconnor - No good docs as of yet. I can get them in when hybrid-mode is more solid.

**Comment by robbyoconnor** [comment]
@mkcode I would help out if I was able -- I use the vim editing mode myself

**Comment by justbur** [comment]
@robbyoconnor for people coming from vim it's meant to be vim with any vim-related key bindings in insert mode removed (except ones related to escaping back to insert mode). Removing the key bindings prevents evil from shadowing the emacs bindings in insert mode. So for example C-[nfbp] are movement keys again. Anything outside of insert mode will not change.
