### ISSUE TITLE
[Clojure] Add joker and clj-kondo as linters - make all optional

### ISSUE THREAD

**Issue by jr0cket** [syl20bnr/spacemacs#12453]
There is a separate `clojure-lint` package that adds joker integration to Spacemacs

There is no current layer that includes clj-kondo, however, there are manual instructions on the clj-kondo readme
https://github.com/borkdude/clj-kondo/blob/master/doc/editor-integration.md#spacemacs

Eastwood and squiggly are included in the Clojure layer by default, although your code must be immune to side effects as squiggly reloads code into the running repl.

I would seem sensible to include all three linters as optional features for the Spacemacs Clojure layer, in the same way that clj-refactor and sayid are optional (layer variables).

**Comment by OwenPriceSkelly** [comment]
Are you on the develop branch? It seems like the clojure layer has a variable for clj-kondo and/or joker linters on develop

**Comment by jr0cket** [comment]
The joker package has only just been added to the clojure layer in the development branch.  Unfortunately no one discussed this change in advance in the #spacemacs channel of Clojurians so I have only just seen it.

I'll update the book soon.
Thanks

**Comment by jr0cket** [comment]
@duianto please close this issue, as it has been resolved by
https://github.com/syl20bnr/spacemacs/pull/12688
https://github.com/syl20bnr/spacemacs/pull/12685
https://github.com/syl20bnr/spacemacs/pull/12611

**Comment by duianto** [comment]
I thought that issue authors have a close issue button?
Or are you accessing Github some other way, where the close button isn't available?
I'm fine with being pinged. It's good to get suggestions for closing resolved issues.
I'm just curious what happened here.

**Comment by jr0cket** [comment]
I got into a pattern of commenting on other peoples issues and suggesting they were closed.  I simply forgot I could close the ones I raised... oops.

**Comment by duianto** [comment]
😄 np, thanks again for the suggestions.
