### ISSUE TITLE
vim-powerline layer broken in develop

### ISSUE THREAD

**Issue by lexxish** [syl20bnr/spacemacs#12454]
#### Description :octocat:
vim-powerline layer broken in develop. It works on master.

#### Reproduction guide :beetle:
- add vimpower-line layer
- SPC-feR

*Observed behaviour:* :eyes: :broken_heart:
fail to load vimpower-line

*Expected behaviour:* :heart: :smile:
load vim-powerline

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: develop (rev. 5389bf9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion python lsp emacs-lisp git helm markdown multiple-cursors org spell-checking syntax-checking treemacs search-engine evil-commentary gnus vim-powerline)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
The `vim-powerline` layer has been removed from the `develop` branch.

It's now a value in a new variable `dotspacemacs-mode-line-themes` that was added with this commit: https://github.com/syl20bnr/spacemacs/commit/a131c899094738b2628f5441ffcb58da420f7593#diff-7ce6cacb1ff19cc7fa401de6ebee205b:

Here's the documentation:
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#mode-line-themes

If you switched from a previous `master` branch setup to the `develop` branch, then you need to update `.spacemacs` to match the `develop` branch `.spacemacs.template`.

It has some new variables.
