### ISSUE TITLE
excessive delays inside which-key--maybe-replace when using lsp layer

### ISSUE THREAD

**Issue by randomphrase** [syl20bnr/spacemacs#12455]
#### Description :octocat:

I have observed performance degradation in which-key after a day's worth of development with spacemacs. Specifically, pressing the leader key and waiting for the menu to appear takes longer and longer.

Using the emacs profiler, I determined that almost all cpu time was being spent inside `which-key--maybe-replace`. Investigating further, it seems that the delays are due to growth of the `which-key-replacement-alist` variable, and this is in turn due to the `lsp` layer.

In the lsp layer, there is a call to `(spacemacs//lsp-declare-prefixes-for-mode major-mode)` as a hook attached to `lsp-after-open-hook`. This adds to the `which-key-replacement-alist` variable. Growth of this variable is correlated with the delays in showing the spacemacs menu.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file which uses LSP mode. I believe this could be any major-mode, but I am using c++-mode.
- Use `SPC b R` to revert this buffer
- Repeat the above step many times, or just open other files in the same LSP workspace
- Press leader key SPC and wait for menu to appear

*Observed behaviour:* :eyes: :broken_heart:

The more files opened, or the more times each buffer is reverted, the longer it takes to the menu to appear. This is observed to be correlated with the increasing value of `(length (assoc major-mode which-key-replacement-alist))`.

*Expected behaviour:* :heart: :smile:

The menu appears instantateously. Also the value of `(length (assoc major-mode which-key-replacement-alist))` is stable.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 37dcecbec)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(systemd javascript html sql auto-completion better-defaults
         (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-lsp-executable
                (expand-file-name "~/hack/extern/ccls/Release/ccls"))
         clojure dap
         (dash :variables helm-dash-docset-newpath
               (expand-file-name "~/.local/share/Zeal/Zeal/docsets"))
         emacs-lisp ess git helm markdown
         (org :variables org-enable-reveal-js-support t)
         python shell-scripts syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

**Comment by thanhvg** [comment]
Your investigation is awesome. I can also reproduce this bug with `js` layer.

**Comment by vv111y** [comment]
commit https://github.com/syl20bnr/spacemacs/commit/653a38bce52f1a69f60cb32cb4ea0b4cb89d0ea5 doesn't seem to work. I am still experiencing this.
@randomphrase great stuff digging into this. It is indeed in `which-key--maybe-replace`.

**Comment by thanhvg** [comment]
> commit [653a38b](https://github.com/syl20bnr/spacemacs/commit/653a38bce52f1a69f60cb32cb4ea0b4cb89d0ea5) doesn't seem to work. I am still experiencing this.
> @randomphrase great stuff digging into this. It is indeed in `which-key--maybe-replace`, and my `which-key-replacement-alist` was over 175K.

@vv111y can you describe how to reproduce this bug in your case? thanks

**Comment by randomphrase** [comment]
This does seem to be fixed for me. Thanks @thanhvg!

**Comment by vv111y** [comment]
First - my apologies for not responding. I wasn't sure what to report. The correct response would have been: "just use spacemacs".   

This issue was never resolved and the relevant information is upstream:
https://github.com/justbur/emacs-which-key/issues/226

Proposed solution:
https://github.com/justbur/emacs-which-key/issues/261
with the relevant comment:
https://github.com/justbur/emacs-which-key/issues/261#issuecomment-682610204

This requires spacemacs to modify how which-key is used (I don't know what that is, I haven't had the time to learn how this works). Shall I open a new issue? Is there anything I can do to help?

**Comment by opsxcq** [comment]
Observing a similar issue, but also `which-keu--create-buffer-and-show` creating a huge delay for everything (even save)

**Comment by smile13241324** [comment]
Interesting, do you see the same behaviour on latest develop @opsxcq? This should not longer be the case.

**Comment by opsxcq** [comment]
I will test with the latest develop and validate

**Comment by opsxcq** [comment]
@smile13241324 no, got the last version from `develop` and the result still the same. But apparently it gets worse when I use org mode, babel and sessions


```
- timer-event-handler                                           27043  84%
 - apply                                                        27043  84%
  - which-key--update                                           26748  84%
   - which-key--create-buffer-and-show                          26748  84%
    + which-key--get-bindings                                   25279  79%
    + which-key--create-pages                                    1441   4%
    + which-key--show-page                                         28   0%
  + #<compiled 0x1ffc3f>                                          197   0%
  + savehist-autosave                                              15   0%
  + sp-show--pair-function                                         11   0%
  + auto-revert-buffers                                             7   0%
- command-execute                                                3665  11%
 - call-interactively                                            3665  11%
  - funcall-interactively                                        3665  11%
   + lazy-helm/helm-mini                                         3174   9%
   + spacemacs/helm-M-x-fuzzy-matching                            430   1%
   + comint-send-input                                             55   0%
   + evil-normal-state                                              6   0%
```

**Comment by vv111y** [comment]
fwiw the situation has improved for me except now it's `helm-descbinds`.  
I timed it and it takes 1 minute 23 seconds to pop up. I just don't use it anymore.  
Doesn't seem to be related, but just in case I'll post it. 

```
- command-execute                                               42598  98%
 - funcall-interactively                                        42598  98%
  - helm-descbinds                                              42597  98%
   - helm                                                       33277  77%
    - helm                                                      33277  77%
     - helm-internal                                            33277  77%
      - helm-read-from-minibuffer                               33237  77%
       - helm-update                                            33085  76%
        - helm--collect-matches                                 33071  76%
         - helm-compute-matches                                 33071  76%
          - helm-process-filtered-candidate-transformer              33065  76%
           - helm-apply-functions-from-source                   33065  76%
            - helm-fuzzy-highlight-matches                      33058  76%
             - helm-flx-fuzzy-highlight-match                   33034  76%
              - require                                         32051  74%
                 apply                                          32048  74%
              + helm-flx-fuzzy-highligher                         876   2%
          + helm-get-cached-candidates                              6   0%
        + helm-render-source                                       12   0%
        + #<compiled -0x1d0af811aa49e27f>                           1   0%
        + helm--update-move-first-line                              1   0%
       + timer-event-handler                                       58   0%
       + command-execute                                           22   0%
       + redisplay_internal (C function)                            7   0%
         helm-get-candidate-number                                  3   0%
       + substitute-command-keys                                    1   0%
      + #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_84>                 14   0%
      + helm-initialize                                             1   0%
      + helm-display-buffer                                         1   0%
   - helm-descbinds-sources                                      9320  21%
    - helm-descbinds-all-sections                                9301  21%
     - describe-buffer-bindings                                  9278  21%
      - apply                                                    9278  21%
       - #<subr describe-buffer-bindings>                        9278  21%
        - describe-map-tree                                      9272  21%
         + describe-map                                            44   0%
       replace-regexp-in-string                                     2   0%
    + #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_11>                  7   0%
+ timer-event-handler                                             217   0%
+ ...                                                             208   0%
+ redisplay_internal (C function)                                  33   0%
+ which-key--hide-popup                                             2   0%
```
