### ISSUE TITLE
Showing gofmt errors when editing go file on remote server

### ISSUE THREAD

**Issue by 02040402** [syl20bnr/spacemacs#12456]
####  Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>

After install Spacemacs with go language layer, login to remote server with ssh method by Emacs' builtin tramp to edit go file. When saving the file always show this alert open a new window aside.
But edit local go lanuuage file doesn't matter.

#### Reproduction guide :beetle:
- Start Emacs
- SSH to remote server with `C-x C-f /ssh:server_ip:/server_file`

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
After saving edited go file, showed:

```
gofmt errors:
sh: goimports: command not found
```

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>
Don't show alert. Work well.

(%LAST_KEYS%)
%SYSTEM_INFO%

#### Backtrace :paw_prints:
```
%BACKTRACE%
```

**Comment by art-Hasan** [comment]
I have exactly the same problem.

**Comment by 02040402** [comment]
@art-Hasan It dues to the `tramp` and `golang` usage issue.

# tramp

When edit remote file, it will copy the remote file to local /tmp path.

# golang

Its bin path isn't /tmp path generally.

So it's difficult to realize. Edit golang file on the remote server is the best solution.
