### ISSUE TITLE
emacs daemon does not read environment variable correctly

### ISSUE THREAD

**Issue by thongpv87** [syl20bnr/spacemacs#12451]
I set two env variable, by `export` command and by add a new entry in `.spacemacs.env`, then reload the daemon. After that I open `emacsclient`, and use `getenv` to get the value of those env: both variables are not existed.

If I open the normal `emacs` GUI or `emacs -nw`, I can get those variable.

Emacs version: 25.2.2 - spacemacs branch: develop

**Comment by LanternD** [comment]
I have the same problem. The environment variable could not be loaded properly in `emacsclient`. Then I could not find the `pyenv` command in my emacs client mode. The standalone `emacs` does not have such problem. Btw, the `exec-path-from-shell` failed to work as well. 

Emacs 26.3, develop branch, Ubuntu 18.04

**Comment by LanternD** [comment]
I had a temporal solution, but not perfect.

1. Add `exec-path-from-shell` to `dotspacemacs-additional-packages`. (although `exec-path-from-shell` is already in  `'(package-selected-packages)`, it is not actually running in `emacsclient`.)
2. Add `(exec-path-from-shell-initialize)` to `dotspacemacs/user-config`, wrapped by a system type decision.
``` lisp
  (if (string-equal system-type "gnu/linux")
      (progn
        (exec-path-from-shell-initialize))
```
Now I can have my shell environment variable in `getenv`.

**Comment by jZhangTk** [comment]
I have the same problem on develop in MacOS. If I start emacs without daemon mode, it works probably. But with daemon mode, it would not load from `.spacemacs.env`.

Thanks @LanternD , `exec-path-from-shell` workaround works.

**Comment by jZhangTk** [comment]
Hmm, there's still issues for me with the workaround. I exported some variables in `.bash_profile`, but it doesn't seem to be picked up by `exec-path-from-shell` unless I use `exec-path-from-shell-copy-env`. Updating `PATH` variable works fine though.

**Comment by ccruquan** [comment]
A other solution with recall spacemacs/load-spacemacs-env. add under code to dotspacemacs/user-config()
``` lisp
  (spacemacs|do-after-display-system-init
   (spacemacs/load-spacemacs-env))
```

**Comment by jZhangTk** [comment]
Thanks @ccruquan , that worked for me.
