### ISSUE TITLE
Installation path is different on Windows

### ISSUE THREAD

**Issue by jamesgecko** [syl20bnr/spacemacs#1245]
When installing on Windows Vista or greater, the config directory should be cloned to `C:\Users\[user name]\AppData\Roaming\.emacs.d`, or something similar. Emacs doesn't seem to pick it up if it's just in `C:\Users\[user name]\.emacs.d`

**Comment by syl20bnr** [comment]
You need a `HOME` variable set to `C:\Users\[user name]`.

**Comment by CestDiego** [comment]
I didn't know this and I always cloned it to the \AppData\Roaming dir... :( it would've been cool to have it in the Doc

**Comment by StreakyCobra** [comment]
As all this is already documented in the README of `master`, I'm closing this issue :relaxed:

**Comment by CestDiego** [comment]
gud
