### ISSUE TITLE
Freeze on long lines in go mode

### ISSUE THREAD

**Issue by felberj** [syl20bnr/spacemacs#12457]
#### Description :octocat:
emacs freezes when editing a very long line in go mode

#### Reproduction guide :beetle:
- Start Emacs
- open new file with "go" layer
- edit this code:
```go
package main

func main() {
a := 0
}
```
- go to the `0` and type `C-u 10000 a` (It is enough to put a very long line there)

*Observed behaviour:* :eyes: :broken_heart:
- emacs freezes

*Expected behaviour:* :heart: :smile:
- emacs does not freeze

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5389bf976) `NOTE: also on master`
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(ruby sql php rust html lua javascript yaml
      (go :variables gofmt-command "goimports" go-tab-width 4)
      python c-c++ helm emacs-lisp auto-completion spell-checking syntax-checking themes-megapack)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Alexander-Miller** [comment]
That's a problem inherent to emacs itself. There is nothing spacemacs can do about it.

**Comment by felberj** [comment]
But it works much better in "text-mode"

**Comment by Alexander-Miller** [comment]
Unlikely. Syntax highlighting is a major contributor to the slowdown from long lines for any mode. And even if go-mode could be made faster, that's still not on spacemacs, but an issue for the maintainers of go-mode (I guess turning off font-lock-mode is another, bad, option).

I'd rather question why you're dealing with 1000+ character long lines, it's not like they're particularly readable or easy to work with, even if your editor has no issues displaying them.

**Comment by felberj** [comment]
I use it to compile binary data into the binary. Thanks for the feedback, I will try to follow up with the go-mode maintainers.
