### ISSUE TITLE
Helm hangs on C-c C-g, requiring force quit

### ISSUE THREAD

**Issue by cyberthal** [syl20bnr/spacemacs#12458]
#### Description :octocat:

Helm hangs on C-c C-g, requiring force quit

#### Reproduction guide :beetle:

- Start Emacs with my Spacemacs configuration, on my iMac, any user
- Load Org Agenda files. Ibuffer reports 2630 buffers open. Org Agenda directories contain 55M of .org files.
- Open two (or more?) frames
- C-x OR C-c (either prefix key will trigger the bug)
- pause a hearbeat
- C-g (or other canceling keys?)

Each step is required to produce the bug.

The same steps performed on my Macbook do not result in a bug. The Spacemacs configurations of the two machines are practically identical.

*Observed behaviour:* :eyes: :broken_heart:

Minibuffer shows C-x OR C-c
Helm completion popup menu does not appear
C-g does not appear in minibuffer
Emacs hangs
Only quitting Emacs from the menu bar or the Activity Monitor interrupts it. Quitting sometimes generates a crash report. No save prompts are ever given. 

I have several MacOS crash reports if that would be helpful.

*Expected behaviour:* :heart: :smile:

Helm completion popup menu opens and then is canceled by C-g C-g

#### System Info :computer:

iMac:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(php html javascript helm org better-defaults emacs-lisp markdown git autohotkey outshine personal cyborganize ruby yaml windows-scripts
     (colors :variables colors-enable-nyan-cat-progress-bar t))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

Macbook:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(php html javascript helm org better-defaults emacs-lisp markdown git autohotkey outshine personal cyborganize ruby yaml windows-scripts
     (colors :variables colors-enable-nyan-cat-progress-bar t))
```
- System configuration features: IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

#### Backtrace :paw_prints:
```
debug-on-error yielded no backtrace
gdb and lldb hung Emacs until I released the process, so I was unable to trigger the error. Possibly I did something wrong. I have never used gdb or lldb before.
```

**Comment by FinallyFinancialFreedom** [comment]
i have the same problem, HEAD of develop branch. but emacs -nw will not encouter this problem

**Comment by cyberthal** [comment]
Here's the non-hang manifestation of the bug:

Type
C-x
[pause]
C-g

If the pause is too short, the minibuffer will return 
"C-x C-g is undefined"
If the pause is too long, the key completion menu will appear after C-x, and C-g will cancel it, leaving the same minibuffer message.
If the pause is the right length, then the key completion menu will appear after C-g, and the minibuffer will display "Quit".

When Emacs is under sufficient load, the correct pause length will result in a hang.

Load increases the longer Emacs runs, the more buffers are open, and possibly the more Org agenda searches are canceled.

I suspect that fixing the pause-sensitivity issue would also prevent hangs under load.

**Comment by cyberthal** [comment]
I no longer experience this problem. IIRC some kind of keyboard delay setting was altered to prevent it, either by me or Spacemacs devs.
