### ISSUE TITLE
Elixir layer depends on Alchemist, which seems to be no longer maintained

### ISSUE THREAD

**Issue by 0rzech** [syl20bnr/spacemacs#12466]
As of now, elixir layer depends on alchemist package.

Both [alchemist.el](https://github.com/tonini/alchemist.el/tree/master) and [alchemist-server](https://github.com/tonini/alchemist-server/tree/master) seem to be abandoned. Latest alchemist.el release was on 30 Mar 2017 and latest commit to its master on 12 Mar 2018. Latest commit to alchemist-server's master was on 2 Nov 2017.

There is a guideline on how to set up Elixir tooling in Emacs and Spacemacs on Elixir Forum: https://elixirforum.com/t/emacs-elixir-setup-configuration-wiki/19196. Among others, it recommends excluding alchemist package and using lsp-mode or eglot instead. It would be great if elixir layer followed this guideline.

There are lsp and dap layers available in develop, so I guess it would be best to depend on them in elixir layer.

If this issue gets accepted, I can try with updating elixir layer. It may take some time though, because I don't know Elisp.

PS. Similar thoughts were expressed in [this comment](https://github.com/syl20bnr/spacemacs/pull/11677#issuecomment-488975958).

**Comment by aswinmohanme** [comment]
This is necessary, as vscode with the elixir-ls  plugin has far superior autocomplete with phoenix.

**Comment by mpanarin** [comment]
this was implemented in https://github.com/syl20bnr/spacemacs/pull/12668

**Comment by 0rzech** [comment]
Thanks, @mpanarin !
