### ISSUE TITLE
Suggestion: Evil mode colour themes, and high-contrast option.

### ISSUE THREAD

**Issue by equwal** [syl20bnr/spacemacs#12461]
The insert-mode cursor is a light blue vertical bar, which makes it hard to keep track of in `hybrid` mode when moving around.

I suggest making the bar thicker, or making a `high-contrast` colour scheme available for the evil modes on the mode-line/cursor, or exposing an interface to modify those colours (which would make it possible to include custom colours in a theme).

**Comment by duianto** [comment]
This might work to change the cursor shape and color:
https://emacs.stackexchange.com/questions/7403/evil-cursor-change-by-state
```elisp
(setq evil-insert-state-cursor '((bar . 5) "yellow")
      evil-normal-state-cursor '(box "purple"))
```
