### ISSUE TITLE
Eshell explodes when pasting transient state is activated.

### ISSUE THREAD

**Issue by equwal** [syl20bnr/spacemacs#12471]
#### Description :octocat:
Eshell explodes when pasting transient state is activated.

#### Reproduction guide :beetle:
- Start Emacs
- Open Eshell
- Paste something at the prompt, from the quiescent state, with `p`.
(explode)
- See that normal emacs yank (`C-y`) works fine.

*Observed behaviour:* :eyes: :broken_heart:
Message in \*Messages\*
command-execute: Wrong type argument: commandp, spacemacs/paste-transient-state/evil-paste-after
*Expected behaviour:* :heart: :smile:
Open transient paste buffer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 11d07d9c7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(evil-cleverparens evil-snipe boilerplate cursed init kmacro reader rectangle register slurp superparens timeclock auto-completion better-defaults c-c   clojure common-lisp csv emacs-lisp erc finance floobits git github gnus graphviz gtags haskell helm html jabber markdown markdown org pandoc pdf-tools prodigy python ranger scheme search-engine shell shell-scripts spell-checking spotify syntax-checking systemd version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```

```

**Comment by duianto** [comment]
It might just be an issue on the `master` branch, because I'm not seeing any error messages on the `develop` branch.

With:
`     (shell :variables shell-default-shell 'eshell)`
`dotspacemacs-enable-paste-transient-state t`

`SPC '` opens `eshell`
In `evil-state`: `normal`
`p` pastes the latest entry from the `kill-ring`, and opens the Pasting Transient State
`C-j` and `C-k` cycles through the entries in the `kill-ring`
`P` and `p` pastes before and after the cursor.

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d4cca7485)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion
            (c-c++ :variables c-c++-backend 'lsp-ccls)
            colors dap emacs-lisp ess git helm html javascript markdown multiple-cursors org python
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS THREADS PDUMPER LCMS2 GMP

**Comment by jebotz** [comment]
Works for me.

**Comment by duianto** [comment]
@jebotz Can you post your system info (`SPC h d s` copies the system info to your clipboard), then it'll be easier to see which setup does and doesn't work.

**Comment by jebotz** [comment]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby python elpy clojure haskell html yaml helm auto-completion emacs-lisp git markdown org asciidoc deft spell-checking version-control typography themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2

**Comment by duianto** [comment]
It also works for me in Ubuntu. On the latest `develop` branch with updated packages.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f40361fd6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm javascript markdown multiple-cursors org
            (shell :variables shell-default-shell 'eshell)
            spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP
