### ISSUE TITLE
Emacsclient unicode characters in the modeline not redered.

### ISSUE THREAD

**Issue by equwal** [syl20bnr/spacemacs#12472]
#### Description :octocat:
Unicode characters on the modeline not rendered in emacsclient.

#### Reproduction guide :beetle:
- Start Emacsclient
- Look at modeline

*Observed behaviour:* :eyes: :broken_heart:
The unicode characters and GUI features of the mode line are mistaken.

*Expected behaviour:* :heart: :smile:
Look the same as when I open without the daemon.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 11d07d9c7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(evil-cleverparens evil-snipe boilerplate cursed init kmacro reader rectangle register slurp superparens timeclock auto-completion better-defaults c-c   clojure common-lisp csv emacs-lisp erc finance floobits git github gnus graphviz gtags haskell helm html jabber markdown markdown org pandoc pdf-tools prodigy python ranger scheme search-engine shell shell-scripts spell-checking spotify syntax-checking systemd version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS PDUMPER LCMS2 GMP

**Comment by jebotz** [comment]
I use emascsclient and don't have this problem.  Can you be more specific about GUI features not present?  Attach a screeshot!

**Comment by jebotz** [comment]
Oh yeah, also, how are you starting emacs/emacsclient?  I.e. from a menu or icon or from the shell?  If you're starting one from a menu, and the other from the shell command line, that could explain a difference as environment variables might be different...

**Comment by equwal** [comment]
> Oh yeah, also, how are you starting emacs/emacsclient? I.e. from a menu or icon or from the shell? If you're starting one from a menu, and the other from the shell command line, that could explain a difference as environment variables might be different...

From a menu icon in `mate` with `emacsclient -nca ''`.
> Attach a screenshot.
 I can't reproduce it at the moment but when I can I will. The characters are redered as boxes, and the mode line GUI elements render without any curves (i.e. greyscale colored rectangles)

**Comment by equwal** [comment]
This has mysteriously disappeared for me, and as it is irreproducible it would be better to just close it.
