### ISSUE TITLE
Remove FCI, fill column indicator mode. Not maintained.

### ISSUE THREAD

**Issue by equwal** [syl20bnr/spacemacs#12473]
This package is not actively maintained. I suggest removing it.

https://github.com/alpaker/fill-column-indicator/issues/87

I'm not associated with this package.

**Comment by duianto** [comment]
Is there an alternative?
I use it all the time, and it seems to be working in it's current state.

**Comment by equwal** [comment]
Yes, use spacemac's highlight-long-lines mode `SPC t 8`

**Comment by alpaker** [comment]
> Is there an alternative?

`fci` mode had been reimplemented natively in the Emacs display engine.  That code is in `master`, and will be in Emacs 27 when it's released.  That probably won't be until next year, though.

**Comment by sdwolfz** [comment]
We still need to have it around until emacs 27 becomes our minimum supported version. So probably we'll remove that in 10 years 😄.

**Comment by equwal** [comment]
I'm glad to hear that emacs is going to natively support this thing, since I have been using it for years.
