### ISSUE TITLE
evil-paste-from-register does not move the cursor to the end of the pasted text

### ISSUE THREAD

**Issue by brandonwillard** [syl20bnr/spacemacs#12479]
#### Description :octocat:
`spacemacs//yank-indent-region` does not return its advised function's value, which breaks its dependent functions &mdash;like `evil-paste-from-register`.

The result is that calls to  `evil-paste-from-register` will not perform its return-dependent action and move the cursor forward a character to the end of the pasted text.

#### Reproduction guide :beetle:
- Start Emacs
- Input `abc` and yank in normal mode with `yy`
- Go into insert mode on a new line (e.g. `o` in normal mode), input `C-r "`

*Observed behaviour:* :eyes: :broken_heart:
`abc|`

*Expected behaviour:* :heart: :smile:
```
abc
|
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1aa0af260)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(nginx ocaml elixir javascript clojure go csv
       (lsp :packages
            (not flycheck-lsp))
       html markdown
       (latex :variables latex-build-command "Make")
       bibtex graphviz
       (python :variables python-auto-set-local-pyvenv-virtualenv 'on-visit python-test-runner 'pytest python-backend 'lsp :packages
               (not live-py-mode))
       python-extras
       (hy :variables hy-shell-spy-delim "\n--spy-output--\n")
       yaml sql helm
       (auto-completion :variables spacemacs-default-company-backends
                        '(company-files company-capf)
                        auto-completion-return-key-behavior nil auto-completion-idle-delay nil auto-completion-tab-key-behavior nil auto-completion-complete-with-key-sequence "C-y" auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual)
       emacs-lisp git
       (github :variables magit-gh-pulls-pull-detail-limit 50)
       scheme racket pdf
       (org :variables org-enable-github-support t org-projectile-file "TODOs.org")
       org-extras
       (shell :variables shell-default-height 30 shell-default-position 'bottom)
       spell-checking syntax-checking
       (erc :variables erc-server-list
            '(("chat.freenode.net" :port "6697" :ssl t :nick "brandonwillard"))
            erc-enable-notifications t erc-enable-sasl-auth t)
       common-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
Use return value from advised function in yank-indent-region #12480
