### ISSUE TITLE
Create private layers from MELPA 

### ISSUE THREAD

**Issue by mahaha** [syl20bnr/spacemacs#1247]
I'd love to be able to install packages from MELPA to get some more useful functionatlity out of emacs, namely things such as  [ebib](http://melpa.org/#/ebib), yet I just do not understand the documentation explaining how to add your own private layer, since just installing from MELPA leads to the deletion of orphaned packages.

Would anyone be willing to give a more or less detailed walk through of how to go about this in general? Thanks so much!

**Comment by person808** [comment]
Did you see [this](https://github.com/syl20bnr/spacemacs/blob/master/private/README.md)?

**Comment by mahaha** [comment]
I have seen that command, but am fairly lost how to go about creating such a layer. I have now tried this, but don't quite understand how this is supposed to load/why it doesn't load:

```
;;; packages.el --- ebib Layer packages File for Spacemacs
;;
;; Copyright (c) 2012-2014 Sylvain Benner
;; Copyright (c) 2014-2015 Sylvain Benner & Contributors
;;
;; Author: Sylvain Benner <sylvain.benner@gmail.com>
;; URL: https://github.com/syl20bnr/spacemacs
;;
;; This file is not part of GNU Emacs.
;;
;;; License: GPLv3

(defvar ebib-packages
  '(
    ebib
    cl-lib
    easymenu
    bibtex
    dash
    pp
    parsebib
    ebib-utils
    ebib-db
    ebib-filters
    ebib-keywords)
    ;; package ebibs go here
    )
  "List of all packages to install and/or initialize. Built-in packages
which require an initialization must be listed explicitly in the list.")

(defvar ebib-excluded-packages '()
  "List of packages to exclude.")

;; For each package, define a function ebib/init-<package-ebib>
;;
;; (defun ebib/init-my-package ()
;;   "Initialize my package"
;;   )
(defun ebib/init-ebib ()
  (use-package ebib
    :defer t))


(defun ebib/init-cl-lib ()
  (use-package cl-lib
    :defer t))

(defun ebib/init-easymenu ()
  (use-package easymenu
    :defer t))

(defun ebib/init-bibtex ()
  (use-package bibtex
    :defer t))

(defun ebib/init-dash ()
  (use-package dash
    :defer t))

(defun ebib/init-pp ()
  (use-package pp
    :defer t))

(defun ebib/init-parsebib ()
  (use-package parsebib
    :defer t))

(defun ebib/init-ebib-utils ()
  (use-package ebib-utils
    :defer t))

(defun ebib/init-ebib-db ()
  (use-package ebib-db
    :defer t))

(defun ebib/init-ebib-filters ()
  (use-package ebib-filters
    :defer t))

(defun ebib/init-ebib-keywords ()
  (use-package ebib-keywords
    :defer t))







;; Often the body of an initialize function uses `use-package'
;; For more info on `use-package', see readme:
;; https://github.com/jwiegley/use-package
```

I got the list of packages from [ebib.el](https://github.com/joostkremers/ebib/blob/master/ebib.el).

**Comment by person808** [comment]
The package list is only packages to install from melpa. So `ebib-packages` would be 
```elisp
(defvar ebib-packages '(ebib))
```

 You only need one init function (`ebib/init-ebib`) because there is only one package to install.

**Comment by mahaha** [comment]
Thanks! That makes it considerably easier. Now I just have:

```lisp
(defvar ebib-packages
  '(ebib
    )
    ;; package ebibs go here
    )
  "List of all packages to install and/or initialize. Built-in packages
which require an initialization must be listed explicitly in the list.")

(defvar ebib-excluded-packages '()
  "List of packages to exclude.")

;; For each package, define a function ebib/init-<package-ebib>
;;
;; (defun ebib/init-my-package ()
;;   "Initialize my package"
;;   )
(defun ebib/init-ebib ()
  (use-package ebib
    )
```

Now I stuck on how to load ebib.

**Comment by cpaulik** [comment]
Now you add ebib to the list of layers in your .spacemacs. Then restart and ebib will be installed.

**Comment by mahaha** [comment]
Thanks a lot for you patience! I have finally got ebib loaded. Editing `.spacemacs` in spacemacs and reloading the configuration with `C-c C-c` helped resolve issues in the `packages.el` file. Turned out I had one `)` too much. Now I just have to figure out how to use ebib!

**Comment by x-ji** [comment]
Sorry but now I've met a similar problem trying to install package `visual-fill-column` https://github.com/joostkremers/visual-fill-column. The following is my packages.el. Already added `visual-fill-column` under my `dotspacemacs-configuration-layers` Not sure if some extra steps are needed...

```emacs-lisp
;;; packages.el --- visual-fill-column Layer packages File for Spacemacs
;;
;; Copyright (c) 2012-2014 Sylvain Benner
;; Copyright (c) 2014-2015 Sylvain Benner & Contributors
;;
;; Author: Sylvain Benner <sylvain.benner@gmail.com>
;; URL: https://github.com/syl20bnr/spacemacs
;;
;; This file is not part of GNU Emacs.
;;
;;; License: GPLv3

(defvar visual-fill-column-packages
  '(
    ;; package visual-fill-columns go here
    visual-fill-column
    )
  "List of all packages to install and/or initialize. Built-in packages
which require an initialization must be listed explicitly in the list.")

(defvar visual-fill-column-excluded-packages '()
  "List of packages to exclude.")

;; For each package, define a function visual-fill-column/init-<package-visual-fill-column>
;;
(defun visual-fill-column/init-my-package ()
  "Initialize my package"
  use-package visual-fill-column
  )
;;
;; Often the body of an initialize function uses `use-package'
;; For more info on `use-package', see readme:
;; https://github.com/jwiegley/use-package
```

**Comment by cpaulik** [comment]
Your package init function is not correct. It should be:
```elisp
(defun visual-fill-column/init-visual-fill-column ()
  "Initialize my package"
  (use-package visual-fill-column)
  )
```

It should always have the name of the package after the `init-` part.
Also `(use-package)` has to be in parentheses otherwise it won't work

**Comment by x-ji** [comment]
Thanks. This worked.

**Comment by CarlQLange** [comment]
I think it would be really handy to have a `create-layer-for-package` command, for the case where you're doing nothing but using a package from MELPA. Eg, `SPC : create-layer-for-package RET ebib` which pretty much fills in the `packages.el` with:

```lisp
(defvar ebib-packages
  '(ebib))

(defvar ebib-excluded-packages '())

(defun ebib/init-ebib ()
  (use-package ebib
    )
```

Then all you have to do is add the layer to your `.spacemacs`. I think installing packages from MELPA is one of the first thing vim switchers do, and then they're confused when they get uninstalled next time you startup. Yes, even though it's document behaviour :)

**Comment by mahaha** [comment]
@CarlQLange That would be perfect! First thing you do switching from VIM is looking for suitable 'pulgins', which turns out to be non-trivial in spacemacs.

**Comment by cpaulik** [comment]
@CarlQLange I'm not sure if this would really help. Better documentation might be more useful.

I can already see the questions about slow startup if the private layers are not lazy loaded. If lazy loading would be the default then we will probably get questions about why commands are not available even though the package was installed.

**Comment by syl20bnr** [comment]
In develop I added a new dotspacemacs variable `dotspacemacs-additional-packages` where one can just add a package name and spacemacs will install it without needing to add it in a layer.

**Comment by mahaha** [comment]
Works great with ebib! I'm sure this will make it far easier for many to switch to emacs.

**Comment by xhevahir** [comment]
I'm trying to install a layer for Elm in private/ and can't figure out why it won't load. My packages.el looks like this:

(defun finance/init-ledger-mode ()
  (use-package ledger-mode
    ; Use :mode to set language modes to automatically activate on certain extensions
    :mode ("\\.\\(ledger\\|ldg\\)\\'" . ledger-mode)
    ; :defer t activates lazy loading which makes startup faster
    :defer t
    ; The code in :init is always run, use it to set up config vars and key bindings
    :init
    (progn ; :init only takes one expression so use "progn" to combine multiple things
      ; You can configure package variables here
      (setq ledger-post-amount-alignment-column 62)
      ; Using evil-leader/set-key-for-mode adds bindings under SPC for a certain mode
      ; Use evil-leader/set-key to create global SPC bindings
      (evil-leader/set-key-for-mode 'ledger-mode
        "mhd"   'ledger-delete-current-transaction
        "m RET" 'ledger-set-month))
    :config ; :config is called after the package is actually loaded with defer
      (message "Ledger mode was actually loaded!")))

I've successfully installed another layer to private/ so I don't know why this isn't working. Elm-mode is listed in MELPA, after all.

**Comment by xhevahir** [comment]
I'm trying to install a layer for Elm in private/ and can't get it to work. Since elm-mode is listed in MELPA, and I've already successfully installed another layer using more or less the same set of functions, I'm mystified as to why it won't install.  This is my private/packages.el 

    ;; List of all packages to install and/or initialize. Built-in packages
    ;; which require an initialization must be listed explicitly in the list.
    (setq elm-mode-packages
        '(
         elm-mode
         ))

    ;; List of packages to exclude.
    (setq elm-mode-excluded-packages '())
    
    ;; For each package, define a function elm-mode/init-<package-name>
    ;;
    (defun elm-mode/init-elm-mode ()
    ;;   "Initialize my package"
      (use-package elm-mode)
       :mode "\\.elm\\'" . elm-mode
       :defer t
       :config
         (message "Elm-mode was actually loaded!"))

**Comment by person808** [comment]
@xhevahir 

> (use-package elm-mode)

Should be `(use-package elm-mode`

**Comment by xhevahir** [comment]
Thanks, you're right. I don't know why the code I pasted has the parentheses there; I'm deleting the code I posted above and replacing it with the exact file I have on my machine. (Which is still not working.)
