### ISSUE TITLE
Go-layer: Autocomplete for import fails. (Suspicious state from syntax checker go-vet)

### ISSUE THREAD

**Issue by gi4c0** [syl20bnr/spacemacs#12470]
#### Description :octocat:
Import path auto complete fails with an error

#### Reproduction guide :beetle:
- create folder within the go project called test_import error
- export something from it `func HelloWorld() { fmt.Println("Hello world") }`
- try to import it from another package

*Observed behaviour:* :eyes: :broken_heart:
Autocomplete doesn't work. Returns an error:
```
Suspicious state from syntax checker go-vet: Flycheck checker go-vet returned non-zero exit code 1, but its output contained no errors: package main
	imports github.com/: non-canonical import path: "github.com/" should be "github.com"

Try installing a more recent version of go-vet, and please open a bug report if the issue persists in the latest release.  Thanks!
```

*Expected behaviour:* :heart: :smile:
Show autocomplete suggestions in popup.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d4cca7485)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(scala vimscript shell-scripts sql csv yaml helm emacs-lisp evil-commentary git version-control javascript react haskell html typescript syntax-checking auto-completion ibuffer org themes-megapack go lsp python)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by amasover** [comment]
Did you ever resolve this @gi4c0 ?

I think it might have something to do with [this issue in flycheck](https://github.com/flycheck/flycheck/issues/1523).

But my flycheck is up-to-date. Maybe something to do with company mode?

**Comment by dennismayr** [comment]
I tried replacing the deprecated `go tool vet` command with the current `go vet`.
However, behavior did not change, so autocomplete for the `go` layer remains broken: `tab-complete` yields a `[No matches]` message on the modeline gutter.
