### ISSUE TITLE
google-translate does not load

### ISSUE THREAD

**Issue by jmromer** [syl20bnr/spacemacs#12481]
#### Description :octocat:

`google-translate` package does not load

#### Reproduction guide :beetle:

- Ensure google translate package is not already downloaded
  (see: `ls ~/.emacs.d/elpa/26.2/develop/ | grep google`)
  Delete or move if there.
- Ensure `spacemacs-language` layer is in `dotspacemacs-configuration-layers`.
- Start Emacs
- Press `SPC x g` [as defined in the `spacemacs-language` layer][layer]

[layer]: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+spacemacs/spacemacs-language/packages.el#L44

*Observed behaviour:* :eyes: :broken_heart:

- Minibuffer says `SPC x g is undefined`
- `google-translate` package has not been downloaded to `~/.emacs.d/elpa/26.2/develop/`

*Expected behaviour:* :heart: :smile:

The google-translate hydra should appear.

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cce5668ad)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 2 auto-completion-idle-delay 0.1 auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets" auto-completion-enable-help-tooltip t)
 better-defaults bm
 (c-c++ :variables c-c++-enable-clang-support t)
 command-log copy-as-format dash deft django docker elixir
 (elm :variables elm-sort-imports-on-save t elm-format-on-save t elm-format-command "elm-format")
 emacs-lisp evil-commentary finance git github
 (go :variables gofmt-command "goimports" go-tab-width 4 go-use-gometalinter t)
 graphviz
 (gtags :variables gtags-enable-by-default t)
 (html :variables web-fmt-tool 'prettier)
 imenu-list ipython-notebook
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (ivy :variables ivy-enable-advanced-buffer-information t ivy-wrap t)
 (javascript :variables javascript-backend 'tern javascript-fmt-tool 'prettier node-add-modules-path t)
 (latex :variables latex-enable-auto-fill t latex-enable-folding t)
 (lsp :variables lsp-navigation 'both lsp-ui-remap-xref-keybindings nil lsp-ui-doc-enable t lsp-ui-doc-include-signature nil lsp-ui-sideline-enable nil lsp-ui-sideline-show-symbol nil)
 (markdown :variables markdown-live-preview-engine 'vmd)
 nginx
 (org :variables org-projectile-file "TODOS.org" org-enable-hugo-support t org-enable-org-journal-support t org-journal-dir "~/Dropbox/org/journal" org-enable-reveal-js-support t org-enable-bootstrap-support t org-enable-github-support t)
 (osx :variables osx-command-as 'hyper osx-option-as 'meta osx-control-as 'control osx-function-as nil osx-right-command-as 'left osx-right-option-as 'none osx-right-control-as 'left)
 parinfer pdf phoenix
 (python :variables python-save-before-test t python-test-runner 'pytest python-sort-imports-on-save nil python-enable-yapf-format-on-save nil)
 prettier semantic react restclient
 (ruby :variables ruby-enable-enh-ruby-mode nil ruby-version-manager nil ruby-test-runner 'rspec)
 ruby-on-rails rust scala search-engine
 (shell :variables multi-term-program "zsh" shell-default-full-span nil shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "zsh" shell-enable-smart-eshell nil)
 shell-scripts spacemacs-language spacemacs-layouts spacemacs-purpose speed-reading
 (sql :variables sql-capitalize-keywords t sql-auto-indent t)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default t syntax-checking-enable-tooltips t)
 (treemacs :variables treemacs-use-filewatch-mode t treemacs-use-follow-mode t)
 version-control vimscript vinegar yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by jmromer** [comment]
Also doesn't download when added to `dotspacemacs-additional-packages`:

```diff
   dotspacemacs-additional-packages
   '(
+     google-translate

)

```

**Comment by duianto** [comment]
For me, the `google-translate` package is downloaded automatically on startup, if it doesn't exist in the `C:\Users\username\.emacs.d\elpa\26.2\develop` directory.

Whether I have the `spacemacs-language` layer in my configuration layers list or not.
(**Note**: The `spacemacs-*` layers might be loaded by default on the `spacemacs` distribution, and only needed for selectively loading specific parts of Spacemacs on the `spacemacs-base` distribution)

Tested on the latest `develop` branch with updated packages.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2cfcf5445)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(autohotkey auto-completion colors emacs-lisp ess git
            (go :variables go-backend 'lsp)
            ivy html ibuffer imenu-list javascript lsp markdown multiple-cursors org
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
