### ISSUE TITLE
haskell-layer seems to be getting confused between cabal and stack

### ISSUE THREAD

**Issue by saurabhnanda** [syl20bnr/spacemacs#12482]
#### Description :octocat:
It _seems_ that spacemacs/haskell-layer is getting confused between using stack or cabal. I'm constantly getting the following error while typing in a haskell buffer:

> Suspicious state from syntax checker haskell-stack-ghc: Flycheck checker haskell-stack-ghc returned non-zero exit code 1, but its output container no error: <command line>: cannot satisfy -package HaskellNet
>    (use -v for more information)

Similarly, trying to use `C-c C-l` to start a REPL session resulted in a "this package has never been configured" error via Cabal.

I had ghc installed in a global location (presumably via Haskell Platform). I used `uninstall-hs`to get rid of it. Now, when I do a `C-c C-l` I get the following error:

> Package has never been configured. Configuring with default flags. If this fails, please run configure manually.
> cabal: The program 'ghc' version >=6.4 is required but it could not be found.

I've tried various combinations of the following config, but the problem persists:

    ((haskell :variables haskell-process-type 'stack-ghci haskell-process-args-ghci "ghci" haskell-process-path-ghci "stack"))

#### Reproduction guide :beetle:
- Start Emacs
- Open a haskell file and start editing it to get the fly-check related error mentioned above. Press `C-c C-l` to get the other error mentioned above.

*Observed behaviour:* :eyes: :broken_heart:
Already mentioned above.

*Expected behaviour:* :heart: :smile:
If my analysis is correct, and my understanding of the docs is correct, then haskell-layer should be able to automatically figure out the correct commands/binaries to execute depending upon whether the current buffer belongs to a stack project or a cabal project.

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(haskell ansible nginx markdown ivy elm html yaml javascript sql emacs-lisp syntax-checking auto-completion-packages purescript
         ((haskell :variables haskell-process-type 'stack-ghci haskell-process-args-ghci "ghci" haskell-process-path-ghci "stack"))
         osx)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
cabal: The program 'ghc' version >=6.4 is required but it could not be found.
```

**Comment by saurabhnanda** [comment]
Possibly related to https://github.com/syl20bnr/spacemacs/issues/10593 or https://github.com/syl20bnr/spacemacs/issues/7953

**Comment by duianto** [comment]
This probably isn't related but you have haskell defined twice in your layers list:
```
(haskell ansible nginx markdown ivy elm html yaml javascript sql emacs-lisp syntax-checking auto-completion-packages purescript
         ((haskell :variables haskell-process-type 'stack-ghci haskell-process-args-ghci "ghci" haskell-process-path-ghci "stack"))
         osx)
```
- Once as just `haskell`
- And once with variables but it has a second set of surrounding parentheses:
`((haskell :variables haskell-process-type 'stack-ghci haskell-process-args-ghci "ghci" haskell-process-path-ghci "stack"))`


When I try to define the layer with variables and the second set of parentheses, then I get this error message on startup:
>    - Unknown layer (haskell :variables haskell-process-type (quote stack-ghci)
      haskell-process-args-ghci ghci haskell-process-path-ghci stack) declared in
      dotfile.      

#### Back to the issue

I don't know much about haskell or flycheck, but it might be working as expected on the `develop` branch.

With the layer defined as just `haskell` or with your suggested layer variables (without the extra surrounding parentheses):
```
(haskell :variables haskell-process-type 'stack-ghci haskell-process-args-ghci "ghci" haskell-process-path-ghci "stack")
```

When I open an example file:
```haskell
-- https://www.schoolofhaskell.com/school/to-infinity-and-beyond/pick-of-the-week/Simple%20examples

import System.Info

main = do
    print os
    print arch
    print compilerName
    print compilerVersion
```

and press `C-c C-l`, then a `*haskell*` buffer opens saying:
```
Hours of hacking await!
If I break, you can:
  1. Restart:           M-x haskell-process-restart
  2. Configure logging: C-h v haskell-process-log (useful for debugging)
  3. General config:    M-x customize-mode
  4. Hide these tips:   C-h v haskell-process-show-debug-tips
λ> 
```

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b5d277496)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git
            (haskell :variables haskell-process-type 'stack-ghci haskell-process-args-ghci "ghci" haskell-process-path-ghci "stack")
            helm markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by dmp1ce** [comment]
The same thing is occurring for me when I use `haskell-stack-ghc` checker instead of `intero`.

```
Suspicious state from syntax checker haskell-stack-ghc: Flycheck checker haskell-stack-ghc returned non-zero exit code 1, but its output contained no errors: <command line>: cannot satisfy -package tasty
    (use -v for more information)

Try installing a more recent version of haskell-stack-ghc, and please open a bug report if the issue persists in the latest release.  Thanks!
```

**Comment by schell** [comment]
@dmp1ce I was seeing the same problem except instead of not being able to satisfy `tasty` mine couldn't satisfy `hspec`. I don't know why but it seems it was looking for the test dependencies. Running `stack test` in the project directory downloaded and built those deps/artifacts, and now it works for me. Good luck!
