### ISSUE TITLE
Treemacs opening in the wrong area

### ISSUE THREAD

**Issue by Jesse415** [syl20bnr/spacemacs#12492]
#### Description :octocat:
Opening treemacs with [Spc f t] opens an empty window on the left but all
the files pop-up at the bottom with a new window in the development branch.
Does work in the master branch.

#### Reproduction guide :beetle:
- Start Emacs
- [Spc f t]

*Observed behaviour:* :eyes: :broken_heart:
Opening file tree with [Spc f t] opens an empty window on the left but all
the files pop-up at the bottom with a new window. 

*Expected behaviour:* :heart: :smile:
File tree to open on the left window like in the master branch.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2bef3f67e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm evil-commentary auto-completion
        (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil)
        better-defaults emacs-lisp git java php-mode markdown
        (org :variable org-enable-github-support t)
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spell-checking syntax-checking version-control html)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
What your seeing at the bottom is a prompt for selecting a project (folder) to add to the `Treemacs` window.

`Treemacs` https://github.com/Alexander-Miller/treemacs works slightly differently than
`Neotree` https://github.com/jaypei/emacs-neotree

`Neotree` is the default file tree browser on the `master` branch.
`Treemacs` is the default file browser on the `develop` branch, therefore it will most likely be default when the next major Spacemacs version is released (I don't have any insight into when that is).

`Treemacs` has a lot more features (check the link above).

But if you want don't want to use/try `Treemacs` right now.
Then you can use `Neotree` by commenting out or removing `treemacs` from the
`dotspacemacs-configuration-layers` list near the top of your `.spacemacs` file (you can open it with `SPC f e d` and add a new entry for `neotree`.

Then just restart and `Neotree` will be installed and the file tree browser will work (`SPC f t`) like your used to.

**Comment by Jesse415** [comment]
Thank you, I will try out treemacs
