### ISSUE TITLE
Updating the python layer to work with the latest lsp-python-ms package with the automated MS PLS installation

### ISSUE THREAD

**Issue by patzhang** [syl20bnr/spacemacs#12497]
The latest lsp-python-ms package included the support for automatically installing Microsoft Python Language Server. MS PLS will be installed under `~/.emacs.d/mspyls`, and the `lsp-python-ms-executable` has already been set up as `~/.emacs.d/mspyls/Microsoft.Python.LanguageServer` by the lsp-python-ms package, which is brilliant.

The code at the end of the Python layer is still assuming there is an executable of `Microsoft.Python.LanguageServer` in the path, which works with the manual installation of MS PLS. So this code [`(setq lsp-python-ms-executable "Microsoft.Python.LanguageServer"))))`](https://github.com/syl20bnr/spacemacs/blob/d8defccf7ad9f18e4b0f3732ddb5f496ccede2f1/layers/%2Blang/python/packages.el#L439) overwrites `lsp-python-ms-executable` caused the package fails to find the file.

The more detailed error description can be found in [this issue](https://github.com/emacs-lsp/lsp-python-ms/issues/44).

I suppose that the code from [line 432](https://github.com/syl20bnr/spacemacs/blob/d8defccf7ad9f18e4b0f3732ddb5f496ccede2f1/layers/%2Blang/python/packages.el#L432) can be removed in order to make it to work with the latest lsp-python-ms package. And update the Python layer readme.

Does anyone have time to look into this?  I think this needs an urgent fix.

**Comment by patzhang** [comment]
This is resolved by [this commit](https://github.com/syl20bnr/spacemacs/commit/9dbc0b9d0c61803c768355426831a0f74b56f5ff).

**Comment by lexxish** [comment]
@patzhang do you need to do anything to configure automatic python lsp? I tried running lsp-python-ms-setup and lsp-python-ms-update-server but I don't see anything under .emacs.d/mspyls
