### ISSUE TITLE
the python layer default install `pippel` which  is vary slow

### ISSUE THREAD

**Issue by jiahut** [syl20bnr/spacemacs#12491]
#### Description :octocat:
after update  to the latest, the python layer default install `pippel` which  is vary slow.
and alway messaging `pip processing...` 
please support some variable to disable the feature

**Comment by Trapez** [comment]
It takes around 4s to list the 40 packages I have in a virtualenv with pippel, Running `pipenv graph` inside the same virtualenv takes 1s.
