### ISSUE TITLE
default font size

### ISSUE THREAD

**Issue by m-c-g** [syl20bnr/spacemacs#12490]
In .spacemacs when the default font size is set an integer is passed. This sets the size in pixels, you need to pass it as a float as in '':size 12.0" to get the size in points.

```
 ;; Default font or prioritized list of fonts.
   dotspacemacs-default-font '("Source Code Pro"
                               :size 12.0
                               :weight normal
                               :width normal)

```

**Comment by duianto** [comment]
Confirmed, it's quite a big difference between `13` and `13.0`.

![emacs_2019-07-01_22-02-51](https://user-images.githubusercontent.com/13420573/60463391-2729a900-9c4c-11e9-9047-730c76613675.png)

![emacs_2019-07-01_22-02-07](https://user-images.githubusercontent.com/13420573/60463401-2db82080-9c4c-11e9-9f09-2e8f3bfe8eb3.png)

**Comment by m-c-g** [comment]
I ran across the integer/float difference the other night in the emacs documentation. I didn't get a chance to try it out till this morning.  The doc didn't mention whether the float would scale the point size, just that and int would give pixels and float points. People seems to have been having problems with the default font size for a long time, this may have been the cause.

**Comment by duianto** [comment]
Is there an open issue about the font problems?

If we can show that a problem is solved by changing the default size to use a decimal, then I'm sure the maintainers would like to know about it.

I just found that the pixel/point difference also has been mentioned in this issue:
Proper way to set a default font and size #231
specifically this in comment: https://github.com/syl20bnr/spacemacs/issues/231#issuecomment-309670288

(Now there's a link to and from both issues so that if someone finds either one it will lead to the other.)

**Comment by m-c-g** [comment]
I'm not sure if there is an open issue, I'm just getting familiar with how github works and at the same time getting started with spacemacs. The default font size was the first thing I tried to change with spacemacs and there seemed to be issues with it going back quite a while, I never found anything that worked for me until I ran across this:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Low_002dLevel-Font.html
```
— Function: font-spec &rest arguments

    Return a new font spec using the specifications in arguments, which should come in property-value pairs. The possible specifications are as follows:

    :name
        The font name (a string), in either XLFD, Fontconfig, or GTK+ format. See Fonts.
    :family
    :foundry
    :weight
    :slant
    :width
        These have the same meanings as the face attributes of the same name. See Face Attributes.
    :size
        The font size—either a non-negative integer that specifies the pixel size, or a floating-point number that specifies the point size.

```

**Comment by Trapez** [comment]
This was helpful. By adjusting size to 10.5 I got the size I really wanted. Fractional sizes works on my current font, Iosevka SS08.

10.0, 11.0 and 10.5 in the middle:

![Skjermbilde fra 2019-07-02 19-26-10](https://user-images.githubusercontent.com/786294/60533489-0884ea00-9d00-11e9-9756-57648727ea9a.png)

**Comment by duianto** [comment]
Changing font size using floating-point numbers now works for me as well.

I don't why it wasn't working before. The only thing I did was to disable a function that resizes the Emacs frame on startup:
```elisp
  ;; resize and position Emacs on the right half of a display
  ;; with resolution: 1920x1200
  (defun start-emacs-on-left-screen-right-half ()
    (let (frame (selected-frame))
      ;; ISSUE:
      ;; the emacs window height doesn't fit the screen height
      ;; w944 h1195 (the height doesn't reach the screen bottom,
      ;; 13px above the bottom)
      (set-frame-size frame 912 1103 t)
      (set-frame-position frame -1272 0))
    ;; workaround:
    ;; start a timer to resize the frame when Spacemacs is idle
    (setq spacemacs-resize-idle-timer
          (run-with-idle-timer
           0 nil
           '(lambda ()
              (modify-frame-parameters
               nil '((left . (+ -937))
                     (top . 0)
                     (width . (text-pixels . 913))
                     (height . (text-pixels . 1167))))))))

  (start-emacs-on-left-screen-right-half)
```

Then I switched from the recommended `Source Code Pro` font to `Consolas` (default in windows 10).
And `10.0`, `10.5` and `11.0` with `Consolas` did change the font size.

When I switched back to `Source Code Pro`, now the font size changes when testing with the same decimal values.

And it also works when I enabled the startup frame resizing, so it might not have been related.

(I restarted Emacs between each test)

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2bef3f67e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (dash :variables helm-dash-docset-newpath "~/.emacs.d/.cache/.docsets")
 emacs-lisp git helm javascript lsp markdown multiple-cursors org react spell-checking syntax-checking treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
The `develop` branch `.spacemacs.template` now uses `10.0` as the default font size.
https://github.com/syl20bnr/spacemacs/blob/0ffdb353f9db507320495d19f71759ec819d267a/core/templates/.spacemacs.template#L212

**Comment by igalic** [comment]
My problem is that i appear unable to scale the font past a certain size, so i can set it to `84.0`, and it'll start with whatever size this is:
![Spacemacs showing .spacemacs file, in the background Elementary Terminal](https://user-images.githubusercontent.com/497249/71785973-4db70b00-3006-11ea-96c7-3044f012e3ba.png)

**Comment by duianto** [comment]
Setting the font size to `84.0` works as expected for me on the `develop` branch.
The Emacs frame gets a size of:
```
	x: 26	y: 26	w: 5392	h: 5115
Client:	x: 0	y: 0	w: 5376	h: 5076
```

Only about a fifth of the top left corner of the Emacs frame is visible on a 1280x1024 resolution display.

This is what the thumbnail looks like in the `Alt + Tab` switcher.

![spacemacs-font-size-84 0](https://user-images.githubusercontent.com/13420573/72203865-bde3e780-3471-11ea-8728-97827f746630.png)

<details><summary>
System Info: Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 96ef7b23a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm imenu-list
            (javascript :variables javascript-backend 'lsp)
            markdown multiple-cursors notmuch
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control
            (xclipboard :variables))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>
