### ISSUE TITLE
Unable to use `ediff-region-wordwise/linewise`

### ISSUE THREAD

**Issue by c02y** [syl20bnr/spacemacs#12498]
#### Description :octocat:
When I try to use `ediff-region-wordwise/linewise` in vanilla emacs, emacs asks me to choose buffers and then mark one region, `C-M-c`, and mark another region, `C-M-c` again to ediff the regions. This works very well when I try it in `emacs -q` or emacs with my own init.el, but when I try it in spacemacs with even fresh installation, one of the two regions in ediff session is not right, it is empty or just part of what I marked. I recorded a gif. Sorry about that the keystrokes were not captured, but I did follow the instructions to hit the keystrokes.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file containing the similar parts for ediff
- M-x ediff-region-wordwise # or M-x ediff-region-linewise
- choose the same buffer
- mark the first part using `v` or `C-Space`
- `C-M-c` as told
- mark the second part  using `v` or `C-Space`
- `C-M-c` as told
- ediff session will be opened, check the two buffers in ediff session

*Observed behaviour:* :eyes: :broken_heart:
One of the two buffers in ediff session is not right, it is empty or just part of what I marked

*Expected behaviour:* :heart: :smile:
Two buffers in ediff session should be exactly what I marked.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d8defccf7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```
![recorded](https://user-images.githubusercontent.com/2135996/60665789-0786c080-9e98-11e9-99d5-48db8201b321.gif)

**Comment by duianto** [comment]
Confirmed.

The issue occurs when the `dotspacemacs-distribution` variable is set to `'spacemacs` at the top of `.spacemacs`.

But it works as expected when it's set to `'spacemacs-base`.

So there's some setting/package that causes it.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d6c8df3d0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm markdown multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by Mikevin** [comment]
'spacemacs-base configures edit like [this](https://github.com/syl20bnr/spacemacs/blob/5df46b200eae368e3cd635f9757cca5c18f883a0/layers/%2Bspacemacs/spacemacs-defaults/packages.el#L109)

This could explain the difference.

**Comment by f380cedric** [comment]
On develop branch, commenting `spacemacs-purpose` in ` spacemacs/layers/+distributions/spacemacs/layers.el ` ([line](https://github.com/syl20bnr/spacemacs/blob/3757ad131ca00164ad4dc09123dcb0dcc71db36c/layers/%2Bdistributions/spacemacs/layers.el#L27)) does the trick. There is something to blame in this layer.

**Comment by duianto** [comment]
@f380cedric Nice catch, it seems like it might be `window-purpose` related.

@bmag Do you know what could be going on here?

Two example functions:
```elisp
    (defun clipboard/set (astring)
      "Copy a string to clipboard"
      (with-temp-buffer
        (insert astring)
        (clipboard-kill-region (point-min) (point-max))))

    (defun clipboard/get ()
      "Return the content of clipboard as string"
      (interactive)
      (with-temp-buffer
        (clipboard-yank)
        (buffer-substring-no-properties (point-min) (point-max))))
```
source: https://caiorss.github.io/Emacs-Elisp-Programming/Elisp_Snippets.html#sec-1-5

#### Reproduction steps
- Copy the two functions above.
- Open a new buffer `SPC b N n`.
- Paste the two functions `p`
- `M-x ediff-regions-wordwise RET`
- At the `Region's A buffer:` prompt, choose `untitled`, `RET`
- At the `Region's B buffer:` prompt, type `un` to highlight and choose `untitled`, `RET`
- Move the cursor to the first functions open parenthesis
- Start a selection by pressing `v`
- Jump to the matching parenthesis: `%`
- Mark the region: `C-M-c`
- Move the cursor to the second functions open parenthesis,
There's a selection but it can't be canceled with `Esc`.
(This is probably an ediff issue).
- Start a selection `v`
- Deselect `v`, now the initial selection is gone.
- Start a new selection `v`
- Jump to the matching parenthesis: `%`
- Mark the region: `C-M-c`
- Jumping to a diff hunk shows

### Observed
#### With `window-purpose` (Spacemacs `develop` branch without any `window-purpose` changes)
#### `ediff-regions-wordwise`

![ediff-regions-wordwise](https://user-images.githubusercontent.com/13420573/61755787-6d8ca680-adb9-11e9-9833-6e3a7c04ecd7.png)

#### The same steps above except by calling `ediff-regions-linewise`.

![ediff-regions-linewise](https://user-images.githubusercontent.com/13420573/61755859-b8a6b980-adb9-11e9-86b3-9b04a9921311.png)

#### With `window-purpose` excluded (and Spacemacs restarted)
```elisp
dotspacemacs-excluded-packages '(window-purpose)
```
#### `ediff-regions-wordwise`

![ediff-regions-wordwise-window-purpose-excluded](https://user-images.githubusercontent.com/13420573/61755908-f0adfc80-adb9-11e9-8fd5-6354da72d2b5.png)

#### `ediff-regions-linewise`

![ediff-regions-linewise-window-purpose-excluded](https://user-images.githubusercontent.com/13420573/61755946-1b985080-adba-11e9-8880-f6a63bef9f6f.png)

**Comment by bmag** [comment]
Thanks for the report and repro steps everyone. I looked into the matter and found that:
- the bug does not reproduce with vanilla Emacs and window-purpose, so it is not an upstream bug.
- the bug only reproduces when `purpose-mode` is enabled.
- the bug does not depend on Spacemacs configuration of ediff.
- the origin of the buggy behavior is in `ediff-clone-buffer-for-region-comparison`. The function is called twice to prompt the user for the desired regions, and the second call (for determining region B) somehow changes the region A (which was determined in the first call).

I wasn't able to find what causes the buggy behavior in `ediff-clone-buffer-for-region-comparison`, but I was to come up with a workaround. Put this in user-config, it disables `purpose-mode` during the call to `ediff-clone-buffer-for-region-comparison`:

```elisp
(defun bm-adv-without-purpose (fn &rest args)
  (without-purpose (apply fn args)))
(advice-add #'ediff-clone-buffer-for-region-comparison :around #'bm-adv-without-purpose)
```

Are there any more buggy ediff commands other than `ediff-region-wordwise/linewise`?

**Comment by duianto** [comment]
Confirmed that snippet seems to fix it.

I tried a couple of the other ediff commands and they seem to work, it might just be the region commands that have this issue.

I'm getting an unrelated issue with `ediff3`, `ediff-buffers3`, `ediff-files3` and `ediff-merge`
>/usr/bin/diff3: diff failed:

Even though:
```
(executable-find "diff3")
```
returns:
>"c:/tools/cygwin/bin/diff3.exe"

**Comment by c02y** [comment]
This bug seems fixed without the code snippet(`bm-adv-without-purpose`) posted by @bmag

**Comment by f380cedric** [comment]
Same here, seems fixed.

**Comment by duianto** [comment]
Confirmed, it seems to be working as expected without any changes.

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 76301564c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm lsp multiple-cursors org
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>
