### ISSUE TITLE
typescript-tsx-mode is missing

### ISSUE THREAD

**Issue by linchen2chris** [syl20bnr/spacemacs#12500]
#### Description :octocat:
typescript-tsx-mode is missing

#### Reproduction guide :beetle:
- Start Emacs
- M-x typescript-tsx-mode

*Observed behaviour:* :eyes: :broken_heart:
- can not find it

*Expected behaviour:* :heart: :smile:
- can set major mode typescript-tsx-mode for .tsx file

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d6c8df3d0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(imenu-list fasd treemacs neotree themes-megapack
						(multiple-cursors :variables multiple-cursors-backend 'evil-mc)
						emacs-lisp
						(auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-idle-delay 0.01 auto-completion-private-snippets-directory "~/MyConfig/private/snippets/")
						yaml import-js prettier react
						(javascript :variables javascript-backend 'lsp javascript-fmt-tool 'prettier javascript-fmt-on-save 't js2-basic-offset 2 js-indent-level 2 node-add-modules-path t javascript-import-tool 'import-js)
						(lsp :variables lsp-navigation 'simple lsp-ui-sideline-enable nil)
						(typescript :variables typescript-fmt-on-save 't typescript-fmt-tool 'typescript-formatter typescript-backend #'lsp)
						docker
						(terraform :variables terraform-auto-format-on-save t)
						git ivy
						(osx :variables osx-use-option-as-meta t osx-dictionary-dictionary-choice "English")
						syntax-checking
						(chinese :variables)
						(org :variables)
						(shell :variables shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t shell-default-shell 'multi-term)
						(version-control :variables version-control-diff-tool 'git-gutter+ version-control-global-margin t))
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2 GMP

#### Backtrace :paw_prints:
```

```

**Comment by linchen2chris** [comment]
I check out to commit *6ec6af84d*, then can get typescript-tsx-mode back, so must be some commits  later broke it.

**Comment by Trapez** [comment]
You need html layer enabled too.

**Comment by linchen2chris** [comment]
@Trapez thanks, you’re right 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by freedomsky11** [comment]
> You need html layer enabled too.

this solves my problem, thanks!
