### ISSUE TITLE
evil mode: delete key doesn't behave like in Vim

### ISSUE THREAD

**Issue by edwintorok** [syl20bnr/spacemacs#1251]
Pressing <kbd>DEL</kbd> in spacemacs when you have a visual selection deletes it, but doesn't add it to the proper register, and its not available for pasting.
As a workaround I can press <kbd>x</kbd> instead of <kbd>DEL</kbd> and that works like in Vim.

Try this in Vim:
```
$ vim -u NONE -U NONE
```
<kbd>i</kbd><kbd>foo</kbd><kbd>RET</kbd><kbd>bar</kbd><kbd>RET</kbd><kbd>test</kbd><kbd>ESC</kbd><kbd>gg</kbd><kbd>dd</kbd><kbd>V</kbd><kbd>DEL</kbd><kbd>p</kbd>

The result is:
```
test
bar
```

Now do the same in spacemacs, and the result is:
```
test
foo
```

**Comment by syl20bnr** [comment]
Interesting you should report it upstream here: https://bitbucket.org/lyro/evil/wiki/Home
And link to it in this thread so we can track its status.

**Comment by edwintorok** [comment]
Reported here: https://bitbucket.org/lyro/evil/issue/516

**Comment by edwintorok** [comment]
This has been fixed upstream, and updating the packages in spacemacs make the <kbd>DEL</kbd> key work as expected: https://bitbucket.org/lyro/evil/commits/aa036f64b424
