### ISSUE TITLE
smartparens region mapping fails in vim/hybrid modes

### ISSUE THREAD

**Issue by rubic** [syl20bnr/spacemacs#12518]
#### Description :octocat:
- `smartparens` region mapping doesn't work in `vim` or `hybrid` mode

#### Reproduction guide :beetle:
- Start Emacs
- Open a python buffer, verify in `python-mode`
- Verify `smartparens-mode` enabled `t`
- Select an active region, with `v` (normal state) or `C-SPC` (hybrid state)
- Press any of the smartparens pairs (paren, bracket, quote, etc.)

*Observed behaviour:* :eyes: :broken_heart:
- Either no response or the modeline expecting further input: `'-`

*Expected behaviour:* :heart: :smile:
- Wrap the selected region with the `smartparen` pair delimiter as occurs in `emacs` mode.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5df46b200)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(auto-completion better-defaults chrome csv django emacs-lisp git html ibuffer ivy javascript markdown org python ranger scheme syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

#### Backtrace :paw_prints:
```
- Not applicable
```

**Comment by duianto** [comment]
The reproductions steps need to be more precise.

In which `major-mode` (or file type) are your selecting the text?

Is `C-h v smartparens-mode` enabled: `t`?

How are you selecting the text?
- `v` (normal state)
- `C-SPC` (insert/hybrid state)

The observed and expected sections are empty.

**Comment by rubic** [comment]
> The reproductions steps need to be more precise.

Updated the original post to include more precise reproduction steps.

> The observed and expected sections are empty.

The sections were there, but `<< >>` angle brackets made them appear empty.  Removed so the sections are visible.

**Comment by duianto** [comment]
With a `python-example.py` file open:
```python
# Example python file
# https://www.pythonforbeginners.com/code-snippets-source-code/game-rolling-the-dice/
import random
min = 1
max = 6

roll_again = "yes"

while roll_again == "yes" or roll_again == "y":
    print "Rolling the dices..."
    print "The values are...."
    print random.randint(min, max)
    print random.randint(min, max)

    roll_again = raw_input("Roll the dices again?")

```
`smartparens-mode` is `t`

With an instance of `print` selected.

- In evil normal state, selected with `v`.
  - `(`, `{` and `'` (expects a mark key to be pressed) are used for navigation
  - `[` is a prefix for several commands
  -  `"` expects a register key to be pressed

- In evil insert/hybrid state, selected with `C-SPC`
All five of the characters mentioned above surrounds the region.

[`evil-surround`](https://github.com/emacs-evil/evil-surround) comes with Spacemacs and it can be used in normal state.

With an active region, press `s` followed by the surrounding character.

`sb` can be pressed for parenthesis (round brackets), it saves having to hold shift and stretch up to type the parenthesis character.

It's also possible to surround a text object without selecting it first, by starting with `ys`.

For example to surround the inner word: `ysiw` followed by the surround character.

You can also change the surrounding characters.
For example to change surrounding brackets to double quotes `csb"`.

There's more info on the evil-surround page https://github.com/emacs-evil/evil-surround

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cd24a7342)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git helm markdown multiple-cursors org python syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by rubic** [comment]
`evil-surround` addresses the issue I was having with `smartparens` region mapping. Thanks.
