### ISSUE TITLE
PlantUML previews are not working properly

### ISSUE THREAD

**Issue by rajasegar-c** [syl20bnr/spacemacs#12517]
#### Description :octocat:
PlantUML previews are not working properly with new package updates.

#### Reproduction guide :beetle:
- Start Emacs
- Enable plantuml layer 
- Preview any .pum file 

*Observed behaviour:* :eyes: :broken_heart:
Seems like the plantuml-mode  by default is using the "server" Execution mode 
for previews, which seems to be broken with the server is not able to reach properly.

Also the major mode is not enabled, I can't use "SPC-mcc" to preview the content.

The Preview is now opening in a new window instead of the same previously.

Possible fix:
We need to set the default execution mode to "jar"

```elisp
  (setq plantuml-default-exec-mode 'jar)
```

The above fix needs to be handled somehow in the layer.

*Expected behaviour:* :heart: :smile:
Previews should work properly.

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 582f9aa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript markdown html helm auto-completion better-defaults emacs-lisp git org
            (shell :variables shell-default-shell 'eshell shell-default-full-span nil shell-default-position 'bottom)
            spell-checking syntax-checking version-control plantuml shell-scripts osx)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
```

**Comment by sunlin7** [comment]
It's an upstream behavior change, and here is a commit mentioned the way to switch to jar exactly same with yours. 
https://github.com/syl20bnr/spacemacs/commit/7dd41188205cda51b3afc76088de8d43c23a43c0

**Comment by capsulecorplab** [comment]
I have `(setq plantuml-default-exec-mode 'jar)` in `dotspacemacs/user-config`, but `plantuml-preview` still isn't working. Has anyone else resolved this issue?

**Comment by capsulecorplab** [comment]
Upon further debugging, `plantuml-preview` appears to work, so long as `plantuml-output-type` is set to `"png"`, but doesn't work for `"svg"`.
