### ISSUE TITLE
Spacemacs keybindings in other emacs configurations

### ISSUE THREAD

**Issue by octavian124** [syl20bnr/spacemacs#12526]
I really like  Spacemacs vim mode'  keybindings . I mean the "Space + (something) " type of keybindings . Is there a way to install them in my personal emacs configuration. 

Sorry If I didnt explained enought.

**Comment by duianto** [comment]
This might be helpful: https://sam217pa.github.io/2016/09/02/how-to-build-your-own-spacemacs/
