### ISSUE TITLE
ess inferior-mode redefines "C-k" in hybrid and emacs modes 

### ISSUE THREAD

**Issue by dahtah** [syl20bnr/spacemacs#12524]
The ESS layer binds "C-k" to history navigation, even in emacs mode, which breaks a long-standing convention that C-k is bound to kill-line.  
The problematic line is in packages.el: 
```
           (define-key inferior-ess-mode-map (kbd "C-k") 'comint-previous-input)
```
It should be made conditional on evil-mode. 
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c05c42102)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(ivy ess auto-completion emacs-lisp markdown julia org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by duianto** [comment]
I'm guessing that the `C-j` binding also should be excluded from the Emacs editing style.
https://github.com/syl20bnr/spacemacs/blob/c825035e48c047f907968813a4bf57cace05ac21/layers/%2Blang/ess/packages.el#L130-L131

The same issue might be occurring in the `ocaml` layer:
https://github.com/syl20bnr/spacemacs/blob/c825035e48c047f907968813a4bf57cace05ac21/layers/%2Blang/ocaml/packages.el#L199-L200

### A possible solution
The python layer seems to have solved it like this:
https://github.com/syl20bnr/spacemacs/blob/c825035e48c047f907968813a4bf57cace05ac21/layers/%2Blang/python/packages.el#L356-L361

### Hybrid style hjkl variable
The hybrid editing style has a variable called:
`hybrid-style-enable-hjkl-bindings`

with the description:
>If non-nil then packages will configure h j k l key bindings for navigation

https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#hybrid

It's used like this:
https://github.com/syl20bnr/spacemacs/blob/c825035e48c047f907968813a4bf57cace05ac21/layers/%2Bspacemacs/spacemacs-completion/funcs.el#L78-L103

Maybe the hybrid hjkl variable should be used for the other instances where `C-j` and `C-k` has vim specific bindings.

https://github.com/syl20bnr/spacemacs/blob/c825035e48c047f907968813a4bf57cace05ac21/layers/%2Bdistributions/spacemacs-bootstrap/packages.el#L285-L292

https://github.com/syl20bnr/spacemacs/blob/c825035e48c047f907968813a4bf57cace05ac21/layers/%2Btools/shell/packages.el#L265-L271
