### ISSUE TITLE
Good practice for installing a third-party package

### ISSUE THREAD

**Issue by bepolymathe** [syl20bnr/spacemacs#12530]
Good morning, everyone,

I am delighted to discover Emacs (Spacemacs) and the advanced uses of Org-mode in a research project. I would like to think about the possibility of using Org-mode as a way to organize my documentation (Org-brain) but also as a way to analyze my data (from interviews, text analysis...). For this second aspect the proposals are less extensive (if I have looked carefully) but I have found a project that could be interesting: [orgqda](https://gitlab.com/andersjohansson/orgqda) 

The problem? There doesn't seem to be a Melpa package that can be easily installed. I've never had to install a package manually in spacemacs. Would a good soul like to accompany me in this process?

Thank you in advance!

**Comment by oleorhagen** [comment]
dotspacemacs-additional-packages '(
                                      (orgqda :location (recipe :fetcher gitlab :repo "andersjohansson/orgqda"))
                                      )

**Comment by oleorhagen** [comment]
Untested, but you should be able to haul this ashore from here :) 
The `dotspacemacs-additional-packages` list can be found in the `.spacemacs` configuration file
`<space> f e d`

**Comment by bepolymathe** [comment]
That's great ! Thank you !

**Comment by ubuntupunk** [comment]
I've just migrated to spacemacs, wondering what is the correct syntax for adding additional packages?

MELPA instructions on [Getting Started](https://melpa.org/#/getting-started) are for emacs.

Can one just add:

`(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)`

or is it?:
`dotspacemacs-additional-packages '(
(melpa-stable :location (recipe: x "https://stable.melpa.org/packages/"))
)`

recipe?

**Comment by fnussbaum** [comment]
Usually Spacemacs assumes the newest packages from ELPA or MELPA, in particular I would not recommend to use melpa-stable. To install a package without an associated Spacemacs layer, you can add it to `dotspacemacs-additional-packages`. If it is available on ELPA or MELPA, you should not provide any `:location` information, the name is enough.

**Comment by ubuntupunk** [comment]
Thanks, took me a while to get around the metaphors coming from VIM.

**Comment by paralin** [comment]
On macos if anyone runs into `wrong-type-argument package-desc nil` with this, you need gnu-tar:

```
brew install gnu-tar

# add to bashrc
export PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"
```

And you can add to    dotspacemacs-additional-packages for example

```
     shell-maker
     (acp :location (recipe :fetcher github :repo "xenodium/acp.el"))
     (agent-shell :location (recipe :fetcher github :repo "xenodium/agent-shell"))

```
