### ISSUE TITLE
In ivy-switch-buffer, `<C-k>` kills the selected buffer 

### ISSUE THREAD

**Issue by demokritos** [syl20bnr/spacemacs#12531]
#### Description :octocat:
In ivy-switch-buffer, `<C-k>` kills the selected buffer,
while `<C-k>` is supposed to move cursor.

#### Reproduction guide :beetle:
- Start Emacs
- Type `<s-b>` or `M-x ivy-switch-buffer <return>`
- Type `<C-j>` several times
- Type `<C-k>`

*Observed behaviour:* :eyes: :broken_heart:
The selected buffer is killed and disappears in the buffer list.

*Expected behaviour:* :heart: :smile:
The selection cursor should only move up.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e9afae228)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust systemd javascript html yaml lsp
      (haskell :variables haskell-completion-backend 'lsp haskell-process-type 'stack-ghci)
      helm
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
      better-defaults emacs-lisp git markdown treemacs neotree org ibuffer
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh")
      spell-checking syntax-checking unicode-fonts gnus react c-c++ julia racket scheme shell-scripts latex prolog games emoji spotify twitter themes-megapack exwm)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
```

**Comment by duianto** [comment]
Confirmed.

The key binding does load on startup:
https://github.com/syl20bnr/spacemacs/blob/e9afae2285220157c985d97b3c56d3b00cbfb72b/layers/%2Bspacemacs/spacemacs-completion/funcs.el#L199

But in the `SPC b b` (`ivy-switch-buffer`),
`C-S-h k` `C-k` shows:
>C-k runs the command ivy-switch-buffer-kill, which is an interactive compiled
Lisp function in ‘ivy.el’.
>
>It is bound to C-k.
>
>(ivy-switch-buffer-kill)

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e9afae228)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git ivy javascript markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
Cause:
`ivy-switch-buffer-kill` was moved from `C-c C-k` to `C-k` two days ago in swiper.
https://github.com/abo-abo/swiper/commit/d52c176e3cca6a6e533e26d577b0aa9ce352d8af

**Comment by duianto** [comment]
I've got a solution that seems to work for restoring `C-k` to `ivy-previous-line`
```elisp
(defun spacemacs//ivy-hjkl-navigation (style)
  "Set navigation on 'hjkl' for the given editing STYLE."
  (cond
   ((or (eq 'vim style)
        (and (eq 'hybrid style)
             hybrid-style-enable-hjkl-bindings))
    (dolist (map (list ivy-minibuffer-map
                       ivy-switch-buffer-map))
      (define-key map (kbd "C-j") 'ivy-next-line)
      (define-key map (kbd "C-k") 'ivy-previous-line))
    (define-key ivy-minibuffer-map (kbd "C-h") (kbd "DEL"))
    ;; Move C-h to C-S-h
    (define-key ivy-minibuffer-map (kbd "C-S-h") help-map)
    (define-key ivy-minibuffer-map (kbd "C-l") 'ivy-alt-done)
    (define-key ivy-minibuffer-map (kbd "<escape>")
      'minibuffer-keyboard-quit))
   (t
    (define-key ivy-minibuffer-map (kbd "C-j") 'ivy-alt-done)
    (define-key ivy-minibuffer-map (kbd "C-k") 'ivy-kill-line)
    (define-key ivy-minibuffer-map (kbd "C-h") nil)
    (define-key ivy-minibuffer-map (kbd "C-l") nil))))
```

But what should the key binding be for `ivy-switch-buffer-kill` when the editing style is
`vim` or `hybrid` with the `hybrid-style-enable-hjkl-bindings` variable set to `t`?

**Comment by asok** [comment]
Any update on that?

> But what should the key binding be for `ivy-switch-buffer-kill`

If you are expecting a community input on that question I would go with `C-d` or `C-M-k`.

**Comment by duianto** [comment]
I opened a PR and chose `C-M-k` for `ivy-switch-buffer-kill` for two reasons:
- `C-d` calls `ivy-delete-char` which might be useful for deleting forwards at the prompt
- `C-M-k` is more comfortable for touch typists that use the opposite hands modifier keys.

**Comment by smile13241324** [comment]
@demokritos I have merged the fix from duianto, would you mind checking this again and close the issue when its working?

**Comment by demokritos** [comment]
Actually I am using helm layer. At the moment, `ivy-switch-buffer` cannot be called. When I opened this issue, `ivy-switch-buffer` could be called.

Anyway, if I enable ivy layer, `C-k` in `ivy-switch-buffer` works as `ivy-previous-line`.

Thanks.
