### ISSUE TITLE
Brew emacs instead of emacs-mac from railwaycat/emacsmacport?

### ISSUE THREAD

**Issue by rdinse** [syl20bnr/spacemacs#1253]
In my experience this version runs much smoother and has more features included (I haven't compared them very thoroughly, though):

    brew install emacs --HEAD --use-git-head --cocoa --with-gnutls --with-rsvg --with-imagemagick

**Comment by stormpat** [comment]
Just tried it out, seems smooth. Will give a more thorough test tomorrow at work.

**Comment by sooheon** [comment]
Just tried your brew incantation, lost my powerline: 
![screen shot 2015-04-20 at 1 19 05 pm](https://cloud.githubusercontent.com/assets/302945/7223633/dc788ade-e75f-11e4-84d8-c6d804ba8c09.png)

You don't have this problem?

**Comment by StreakyCobra** [comment]
This is an old issue without activity the last 7 months. I'm closing it then. Anyway, feel free to open a new issue/PR for this if there is any news, and link this thread in the comment.This will offer it more visibility if there are some interests :relaxed:
