### ISSUE TITLE
Emacs/Spacemacs crash when issueing M-m i u (helm-ucs)

### ISSUE THREAD

**Issue by ttamttam** [syl20bnr/spacemacs#12537]
#### Description :octocat:
Emacs/Spacemacs crash when issueing `M-m i u` (helm-ucs)

#### Reproduction guide :beetle:
- Start Emacs
- `M-m b s`
- `M-m i u` 

*Observed behaviour:* :eyes: :broken_heart:
Emacs/Spacemacs crashes

*Expected behaviour:* :heart: :smile:
Should provide the list of unicode codepoints?

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
I do not know how to produce a backtrace?

#### Additionnal remarks/questions

This is with a Debian 10 OS.
For this test, I started with a fresh spacemacs `git clone` and moved my `.spacemacs` file away.
Is this bug reproduced by anybody?
If not, it would mean that something is broken on my install? What should I check?

**Comment by duianto** [comment]
It's working for me on the `develop` branch, but it took about a minute or two start the first time.
There was a percentage message that counted up in the minibuffer:
>collecting ucs names...99%

It stopped for a maybe 15-30 seconds twice at 6% and 8%.

It seems like the collection is performed every time Spacemacs is restarted, so if you get it working and use it a lot. then you probably should run Spacemacs as a server, here's a setup guide:
https://medium.com/@bobbypriambodo/blazingly-fast-spacemacs-with-persistent-server-92260f2118b7

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cc4ab653c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git helm javascript markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by ttamttam** [comment]
Thanks for your time. After further checks, it appears this bug is not related to spacemacs, since I can reproduce it with a stock emacs.

Sorry for the noise.
