### ISSUE TITLE
Centaur tabs flickering

### ISSUE THREAD

**Issue by ema2159** [syl20bnr/spacemacs#12532]
Hi! I am the author of centaur tabs, a tabs plugin. Some of my users that are using my plugin in Spacemacs are reporting a flickering problem. Would you have any idea whats causing this so that I try to fix it? 
Here's the original issue: https://github.com/ema2159/centaur-tabs/issues/18

**Comment by duianto** [comment]
Hello, I had not tried the https://github.com/ema2159/centaur-tabs package yet, it looks interesting. 👍 

I'm not seeing any flickering with:
- The default spacemacs mode-line theme:
```elisp
   dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 1.5)
```
- @mpanarin's config: https://github.com/ema2159/centaur-tabs/issues/18#issuecomment-510519698
- Two split windows (either horizontally or vertically)
- Moving the cursor several lines up or down.
- Navigating up or down between the candidates in a helm buffer, for example:
  - `SPC SPC` (`HELM M-x`)
  - `SPC f f` (`HELM Find Files`)
  - `SPC s s` (`HELM Swoop`)

Tested in:
- Ubuntu 18.04.2, Emacs 27.0.50
- Windows 10 version 1803, Emacs 26.2 and 27.0.50.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e9afae228)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm html markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP


#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e9afae228)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git helm javascript markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS THREADS PDUMPER LCMS2 GMP

**Comment by ema2159** [comment]
I know there was a similar problem with Helm, maybe it has to do with that somehow or is a similar problem.

**Comment by mpanarin** [comment]
@duianto did you try with different files?
Because i encounter flickering when 2 windows show 2 different files but from the same project.
ex. window 1 shows content of tab1, window 2 shows the content of tab 2.

It is specific, because if you have windows with different projects open (so each window has different set of tabs) it doesn't flicker. As well as if you have several tabs open of one project, but the same buffer is open on both winodws it won't flicker. Hope it helps  :)

Me and a friend of mine who has the same issue both use manjaro. I doubt that it is the issue, but just in case.

**Comment by duianto** [comment]
I did try it with different files in both windows.

Could you:
- post your system info `SPC h d s`.
- provide reproduction steps from starting Spacemacs.
- make a screen recording?

**Comment by mpanarin** [comment]
@duianto Tried once again in VB. Here is the info:
specs:
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e9afae228)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2
 
gist of spacemacs config:
https://gist.github.com/mpanarin/adcce0e670ec12d1bfa8e12d178cfc63

will add screen recording in a minute
(although it flickers here way less compared to my instance but still does. Probably connected to the amount of modes it activates/deactivates?)

**Comment by mpanarin** [comment]
https://dropmefiles.com/3vQdE

screen recording

**Comment by duianto** [comment]
Ok I'm able to reproduce it now.

The mode-line isn't flickering on every line change, only when the cursor tries to move past the top or bottom of the window.

And when the second windows mode-line becomes "unfocused/unhighlighted", then it remains unfocused as long as the cursor is moved up and down in the same column, but moving the cursor left or right returns the mode-line focus/highlight.

**Comment by duianto** [comment]
I got into a state where the mode-line switched between focused and unfocused ever time the cursor moved to the next and previous line.

But I don't know how to reproduce it.

The Emacs frame was split into two windows, the split direction did't matter, horizontal or vertical.
Two buffers were open in the same tab group, with different buffers in each window.
The second window was selected and in `emacs-lisp-mode`.

When the cursor moved on top of or one character to the right of an open or close parenthesis, then for every cursor movement the mode-line become focused, but it lost focus quickly (maybe there's a timer focusing the tab bar?)

A possible reason why it only happens when moving on parenthesis, might be because it's matching pair is highlighted, maybe that causes the mode-line to be redrawn.

This example worked at the time.
```
;; ()
;; ()
;; ()
;; ()
;; ()
```
When the cursor moved anywhere other than on or after a parenthesis, then the mode-line remained unfocused.

Before I got into that state, then the mode-line also remained unfocused when `M-TAB` switching to another application and back to Spacemacs.

Moving the cursor up or down on a non-parenthesis character didn't focus the mode-line, but moving left or right did.

**Comment by ema2159** [comment]
Just and idea. In this code block:

https://github.com/ema2159/centaur-tabs/blob/eddd7563d8bd45f8f43874954b359c725b7cc67c/centaur-tabs.el#L656

Is the one that constantly redraws the tabs. Could that have something to do with the problem?

**Comment by duianto** [comment]
That does seem to be a likely source, when those three hooks are commented out:
```elisp
(add-hook 'after-save-hook #'centaur-tabs-on-saving-buffer)
(add-hook 'first-change-hook #'centaur-tabs-on-modifying-buffer)
(add-hook 'after-change-functions #'centaur-tabs-after-modifying-buffer)
```
Then the mode-line remains focused when pressing the cursor against the left or top of the window.

**Comment by mpanarin** [comment]
Can confirm that commenting hooks above partially fixes the issue.

I also found that commenting out this part with them:
```elisp
(dolist (hook centaur-tabs-hide-tabs-hooks)
  (add-hook hook (lambda () (setq-local header-line-format nil))))
```

fixes the issue for me completely

**Comment by duianto** [comment]
Just commenting out those two lines don't seem to work for me.

They are defined here:
https://github.com/ema2159/centaur-tabs/blob/84d07fd68a9dd94836e69b4a19fbd77878db3682/centaur-tabs.el#L1984

The mode-line still becomes unfocused when moving the cursor against the window top or bottom, or when trying to move to the left of a lines first character, or to the right of a lines last character, in `evil-mode`, with the variable `evil-cross-lines` set to `nil` (default), meaning that the cursor stops at the end of a line.
When the variable is set to `t`, then the cursor moves from the end of a line to the beginning of the next line.

**Comment by ema2159** [comment]
> Can confirm that commenting hooks above partially fixes the issue.
> 
> I also found that commenting out this part with them:
> 
> ```emacs-lisp
> (dolist (hook centaur-tabs-hide-tabs-hooks)
>   (add-hook hook (lambda () (setq-local header-line-format nil))))
> ```
> 
> fixes the issue for me completely

The problem is that by doing so, the modified buffers marking feature is removed.

**Comment by PanarinM** [comment]
> > Can confirm that commenting hooks above partially fixes the issue.
> > I also found that commenting out this part with them:
> > ```emacs-lisp
> > (dolist (hook centaur-tabs-hide-tabs-hooks)
> >   (add-hook hook (lambda () (setq-local header-line-format nil))))
> > ```
> > 
> > 
> > fixes the issue for me completely
> 
> The problem is that by doing so, the modified buffers marking feature is removed.

Well, i have `centaur-tabs-set-modified-marker` set to nil. Shouldn't, in this case, hooks be disabled?

**Comment by mpanarin** [comment]
> > Can confirm that commenting hooks above partially fixes the issue.
> > I also found that commenting out this part with them:
> > ```emacs-lisp
> > (dolist (hook centaur-tabs-hide-tabs-hooks)
> >   (add-hook hook (lambda () (setq-local header-line-format nil))))
> > ```
> > 
> > 
> > fixes the issue for me completely
> 
> The problem is that by doing so, the modified buffers marking feature is removed.

Well, i have centaur-tabs-set-modified-marker set to nil. Shouldn't, in this case, hooks be disabled?

**Comment by mpanarin** [comment]
> Just commenting out those two lines don't seem to work for me.
> 
> They are defined here:
> https://github.com/ema2159/centaur-tabs/blob/84d07fd68a9dd94836e69b4a19fbd77878db3682/centaur-tabs.el#L1984
> 
> The mode-line still becomes unfocused when moving the cursor against the window top or bottom, or when trying to move to the left of a lines first character, or to the right of a lines last character, in `evil-mode`, with the variable `evil-cross-lines` set to `nil` (default), meaning that the cursor stops at the end of a line.
> When the variable is set to `t`, then the cursor moves from the end of a line to the beginning of the next line.

yes, what I am saying is disabling 3 hooks above and, additionally, this hook completely fixes any issues with flickering for me. 
Disabling 3 above hooks only fixes flickering partly, as random flickering when line changes is still present.

**Comment by ema2159** [comment]
> Well, I have `centaur-tabs-set-modified-marker` set to nil. Shouldn't, in this case, hooks be disabled?

No, that just disables the marker but centaur-tabs still changes the faces of the tabs that are modified, it just doesn't display the icon. 

It seems we're getting close to the problem, although I'm not quite sure why this affects:
``` elisp
(dolist (hook centaur-tabs-hide-tabs-hooks)
  (add-hook hook (lambda () (setq-local header-line-format nil))))
```

This is just a hook for hiding the unwanted buffers from the tabs, and for some reason it is binding the header-line to the mode-line, which should be separate things. @duianto what configurations are present in Spacemacs for the header-line? does it use it at all?

**Comment by duianto** [comment]
I don't know if there's a connection between the header-line and mode-line.

These are the 34 places in Spacemacs on the `develop` branch where `header-line` is mentioned:
```elisp
./CHANGELOG.develop:1289:  - ~SPC m h~ to =csv-header-line= (thanks to Francesc Elies Henar)
./layers\+lang\csv\packages.el:24:        "h"  'csv-header-line
./layers\+spacemacs\spacemacs-completion\funcs.el:51:  (when (with-helm-buffer helm-echo-input-in-header-line)
./layers\+spacemacs\spacemacs-completion\funcs.el:59:(defun helm-toggle-header-line ()
./layers\+spacemacs\spacemacs-completion\packages.el:24:        helm-display-header-line nil
./layers\+spacemacs\spacemacs-completion\packages.el:27:        helm-echo-input-in-header-line t
./layers\+spacemacs\spacemacs-completion\packages.el:41:    (add-hook 'helm-before-initialize-hook 'helm-toggle-header-line)
./layers\+spacemacs\spacemacs-completion\packages.el:55:        (after spacemacs/helm-header-line-adv activate)
./layers\+tools\ranger\README.org:64:return a string that is placed in the header-line.
./layers\+tools\ranger\README.org:67:  (setq ranger-header-func 'ranger-header-line)
./layers\+tools\ranger\README.org:71:return a string that is placed in the header-line.
./layers\+tools\ranger\README.org:74:  (setq ranger-parent-header-func 'ranger-parent-header-line)
./core\libs\spacemacs-theme\spacemacs-common.el:200:     `(header-line ((,class :background ,bg4)))
./core\libs\spacemacs-theme\spacemacs-common.el:516:     `(helm-header-line-left-margin ((,class (:foreground ,keyword :background ,nil))))
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:559:;;     Info-toggle-breadcrumbs-in-header-line: Added 3rd arg to make-obsolete.
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:571:;;     Renamed Info-toggle-breadcrumbs-in-header-line to Info-toggle-breadcrumbs-in-header.
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:612:;;     Info-toggle-breadcrumbs-in-header-line, Info-save-current-node: Added MSGP arg.
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:644:;;     Added: Info-breadcrumbs-in-header-flag, Info-toggle-breadcrumbs-in-header-line,
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:691:;;     (Emacs 22+) Don't change faces info-menu-header, *-title-*, *(-header)-node, header-line.
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:922:(defvar header-line-format)
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:954:(defvar Info-use-header-line)
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:1571:line from non-nil `Info-use-header-line'."
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:1577:(defalias 'Info-toggle-breadcrumbs-in-header-line 'Info-toggle-breadcrumbs-in-header)
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:1578:(make-obsolete 'Info-toggle-breadcrumbs-in-header-line 'Info-toggle-breadcrumbs-in-header "2014/03/04")
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:3336:          (when Info-use-header-line
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:3352:                                 'header-line (replace-regexp-in-string
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:3709:          (when Info-use-header-line
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:3725:                                 'header-line (replace-regexp-in-string
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:4058:                ;; `Info-use-header-line', it is either used in the
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:4065:          (when Info-use-header-line
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:4081:                                 'header-line (replace-regexp-in-string
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:4855:  (when Info-use-header-line     ; do not override global header lines
./layers\+spacemacs\spacemacs-navigation\local\info+\info+.el:4856:    (setq header-line-format  '(:eval (get-text-property (point-min) 'header-line))))
./layers\+vim\vim-empty-lines\local\vim-empty-lines-mode\vim-empty-lines-mode.el:165:                                (if header-line-format 1 0))))
```

**Comment by mpanarin** [comment]
> > Well, I have `centaur-tabs-set-modified-marker` set to nil. Shouldn't, in this case, hooks be disabled?
> 
> No, that just disables the marker but centaur-tabs still changes the faces of the tabs that are modified, it just doesn't display the icon.
> 
> It seems we're getting close to the problem, although I'm not quite sure why this affects:
> 
> ```emacs-lisp
> (dolist (hook centaur-tabs-hide-tabs-hooks)
>   (add-hook hook (lambda () (setq-local header-line-format nil))))
> ```
> 
> This is just a hook for hiding the unwanted buffers from the tabs, and for some reason it is binding the header-line to the mode-line, which should be separate things. @duianto what configurations are present in Spacemacs for the header-line? does it use it at all?

@ema2159  Okaaaaaaaay, I think i found the issue!
After some meddling with the hooks, it seems that `dolist` itself was the issue and not the hooks.
changing dolist to:
`(mapc (lambda (hook) (add-hook hook (lambda () (setq-local header-line-format nil))))
      centaur-tabs-hide-tabs-hooks)`
Fixed the issue with random flickers for me. Maybe `dolist` is just too slow in this situation?

So, only those 3 hooks are left to deal with.
Maybe it is worth to make a variable, that disable all the jazz with edited buffer as a workaround for the time being?

**Comment by ema2159** [comment]
>@ema2159 Okaaaaaaaay, I think i found the issue!
After some meddling with the hooks, it seems that dolist itself was the issue and not the hooks.
changing dolist to:
(mapc (lambda (hook) (add-hook hook (lambda () (setq-local header-line-format nil)))) centaur-tabs-hide-tabs-hooks)
Fixed the issue with random flickers for me. Maybe dolist is just too slow in this situation?

Nice! I'll implement this patch as soon as possible. Also I try the other temporary fix, but let's keep looking! we're almost there

**Comment by ema2159** [comment]
@duianto done. I was fixed in the `centaur-tabs` repo. For more information, you can read this: https://github.com/hlissner/doom-emacs/commit/eb690735784ba162e68d9fb9ab3704feae126e24. You even can find some useful info for solving similar issues.

**Comment by duianto** [comment]
Thanks for the update.
