### ISSUE TITLE
Font is blurry on windows by use sub Linux system

### ISSUE THREAD

**Issue by lmingde** [syl20bnr/spacemacs#12547]
I **use mobaxterm to connect sub Ubuntu system in windows  and open Spacemacs.** But the font is blurry. Any one can help me? 

![blurry](https://user-images.githubusercontent.com/38581341/61577086-f2a36180-ab14-11e9-90d7-7724cd68c021.png)

the left of picture is sublime text and the right is spacemacs

**Comment by duianto** [comment]
Maybe it's related to High DPI:
https://stackoverflow.com/questions/46890879/blurry-x11-forwarding-via-mobaxterm

**Comment by lmingde** [comment]
@duianto right, but the font don't scaled, so I find other method: https://superuser.com/questions/1370361/blurry-fonts-on-using-windows-default-scaling-with-wsl-gui-applications-hidpi/1462121#1462121

but I don't understand how to override GTK+ settings  this method.
