### ISSUE TITLE
How to line wrap?

### ISSUE THREAD

**Issue by shawnwanderson** [syl20bnr/spacemacs#12540]
I can't find anywhere in the docs. I looked all over the wiki, github, and youtube. How do I pretty-format a selected paragraph? As in prose. Like a book. Like what libre writer would do naturally. Pretty margins?

I want this in org mode. I have done it before but can not find any resource to aid my memory.

**Comment by duianto** [comment]
`M-q` calls `fill-paragraph` which wraps each line at the current fill-column,

You can view the current fill-column value with:
`SPC h d v fill-column` (default `80`)

Or toggle the visibility of a vertical line at the fill-column with `SPC t f`

The fill-column can be changed by pressing `C-x f`.
A minibuffer prompt appears:
`Set fill-column to (default x):`
(x is your cursors current column), but you can type any number.

**Comment by gdkrmr** [comment]
I always use `M-q`, which works in evil insert mode. Works also in source code comments and `org-mode`.
