### ISSUE TITLE
Unable to install Spacemacs

### ISSUE THREAD

**Issue by 3n-k1** [syl20bnr/spacemacs#12545]
#### Description :octocat:
Unable to install Spacemacs, first time setup (selecting all the defaults) fails with the following error on Fedora 30:

```
Warning (initialization): An error occurred while loading ‘/home/tay/.emacs.d/init.el’:

File is missing: Cannot open load file, No such file or directory, evil

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

#### Reproduction guide :beetle:
- Clone a clean copy of Spacemacs
- Start Emacs
- Select all the default setup options

*Observed behaviour:* :eyes: :broken_heart:
Install fails with an init.el issue

*Expected behaviour:* :heart: :smile:
Install succeeds without issue.

(%LAST_KEYS%)
%SYSTEM_INFO%

```
$ uname -a
Linux anarchy 5.1.17-300.fc30.x86_64 #1 SMP Wed Jul 10 15:20:27 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ emacs --version
GNU Emacs 26.2
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

#### Backtrace :paw_prints:
Backtrace is extremely long, pasted here: https://pastebin.com/NMun9gct

**Comment by 3n-k1** [comment]
Fixed by adding `(setq package-check-signature nil)` to `.emacs.d/init.el`. Is there any way to make this work without setting that to nil?

**Comment by 3n-k1** [comment]
Adding `(package-initialize)` Worked.

**Comment by retiform** [comment]
I am having the same problem. I have been unable to fix it.

**Comment by duianto** [comment]
Thanks for posting the fix.

There's an open issue with the same suggested fix here:
Failed to download 'gnu' archive. Bad request. (Solution included) #12535

Hopefully it will be fixed when the next Emacs version is released.

**Comment by SulfredLee** [comment]
> Fixed by adding `(setq package-check-signature nil)` to `.emacs.d/init.el`. Is there any way to make this work without setting that to nil?

It works thank you.
I am installing spacemacs under a VM, I am not sure if the root cause due to proxy setting.
Anyway, I use your method and finish the installation.

**Comment by briangorman** [comment]
This works to fix the bug on the latest Ubuntu as well

**Comment by atmichalak** [comment]
This bug occurs on Fedora 31 as well.

**Comment by duianto** [comment]
atmichalak, This comment is by a fedora user: https://github.com/syl20bnr/spacemacs/issues/12535#issuecomment-529062731

`dnf install gnutls-utils` seems to have fixed it.

**Comment by gregorywaynepower** [comment]
Another solution to this problem:

My issue was that I had emacs 25.x on my system and there were some issues with that verision of emacs. Here are the commands below that fixed my issue.

```
sudo apt autoremove emacs emacs23 emacs24 emacs25
sudo add-apt-repository ppa:kelleyk/emacs 
sudo apt-get update
sudo apt install emacs26
```
