### ISSUE TITLE
Python-mode not working

### ISSUE THREAD

**Issue by StillerHarpo** [syl20bnr/spacemacs#12544]
#### Description :octocat:
Python-mode not working. I tried it on develop and master.
I tried it withc backend lsp and the default one.  I also tried different files.
#### Reproduction guide :beetle:
- Start Emacs
- Open a python file

*Observed behaviour:* :eyes: :broken_heart:
Got error
`Autoloading file /home/florian/.emacs.d/elpa/26.1/develop/python-0.26.1/python.elc failed to define function python-mode`  
Enter fundamental mode
*Expected behaviour:* :heart: :smile:
Enter python mode

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a69323fb3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(envdir
 (python :variables python-backend 'lsp)
 (mu4e :variables mu4e-installation-path "/run/current-system/sw/share/emacs/site-lisp")
 racket coq csv
 (geolocation :variables geolocation-enable-automatic-theme-changer t geolocation-enable-weather-forecast t)
 (elfeed :variables rmh-elfeed-org-files
         (list "~/.emacs.d/private/elfeed.org"))
 games pdf gnus haskell shell-scripts html helm auto-completion better-defaults emacs-lisp lsp git
 (markdown :variables markdown-command "pandoc")
 neotree org
 (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill t)
 bibtex nixos
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables spell-checking-enable-auto-dictionary t)
 syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD

**Comment by simonpintarelli** [comment]
Mine is working:
```
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2770777bb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(
       ...
      (python :variables python-backend 'lsp)
      ...
      )
`
```

**Comment by tomlaube** [comment]
I'm having the same issue, not just with python-0.26.1, but with multiple elpa based packages (undo-tree, mmm-mode)

System Info:

    OS: gnu/linux
    Emacs: 26.1
    Spacemacs: 0.300.0
    Spacemacs branch: develop (rev. a69323f)
    Graphic display: t
    Distribution: spacemacs
    Editing style: hybrid
    Completion: helm
    Layers:
```
     (python :variables
             python-test-runner 'pytest
             python-backend 'lsp
             python-lsp-server 'mspyls)
```

**Comment by tomlaube** [comment]
The package list for elpa doesn't get downloaded properly, after copying .emacs.d/elpa/26.1/develop/archives/gnu/ from jare/spacemacs docker image everything works fine...

**Comment by duianto** [comment]
There's an open issue about that:
Failed to download 'gnu' archive. Bad request. (Solution included) #12535

**Comment by StillerHarpo** [comment]
I don't get the errors from #12535.  And the solution isn't working for me.

**Comment by duianto** [comment]
Sorry for the confusion.

I should have specified that the failed to download issue was related to tomlaubes comment about elpa not being downloaded correctly.

It's not python-mode related.

**Comment by rmhsilva** [comment]
@StillerHarpo do you have `ipython-notebook` in your layers list? I had the same issue as you, but removing `ipython-notebook` fixed it. Presumably something has changed upstream (https://github.com/millejoh/emacs-ipython-notebook). To be fair to them, they don't recommend the Spacemacs layer :(.

**Comment by StillerHarpo** [comment]
No i don't have the ipython layer.

**Comment by rihardsk** [comment]
Had the same problem on the spacemacs `develop` branch. Solved it by cleaning `~/.emacs.d` with `git clean -fdx`. After all the packages were re-downloaded, the problem was gone.

**Comment by StillerHarpo** [comment]
ihardsks solution fixed it. But i got this issue (https://github.com/syl20bnr/spacemacs/issues/8984) which i solved with `emacs --insecure`
