### ISSUE TITLE
Add key bindings for arrow keys in addition to hjkl

### ISSUE THREAD

**Issue by Sohalt** [syl20bnr/spacemacs#1255]
I use an alternate keyboard layout (neo-layout.org) where the hjkl keys are scrambled all over the place and basically become unusable for navigating. But neo provides arrow keys directly on the home row via a modifier. Having the ability to use the arrow keys in addition to hjkl in places like `SPC w`, where the bindings won't clash, would greatly improve the out of the box experience for people like me.

**Comment by syl20bnr** [comment]
You are right, we planned to do it but forgot it.

**Comment by StreakyCobra** [comment]
@Sohalt I just tried and arrows seem to work for `SPC w` now. Is there other bindings where you want this behaviour? Otherwise the issue can probably be closed :relaxed:

**Comment by Sohalt** [comment]
Thanks! I can't think of other bindings where I want this right now. It would be great to be able to search for all places where hjkl are uses as arrow keys/direction modifiers and see if arrow keys are suported and would make sense. But with the way bindings are set up currently I don't see a way to make this work.

**Comment by StreakyCobra** [comment]
As we don't know if there are other bindings where arrows are missing for now, I'm closing this issue. If you find any place where arrows are missing, feel free to open a new issue :relaxed:
