### ISSUE TITLE
Somehow identify when buffer is maximized

### ISSUE THREAD

**Issue by andres-lowrie** [syl20bnr/spacemacs#12558]
First let me say thank you, this distribution is amazing!

I work by opening up a lot of buffers at once. I then like to maximize a buffer to focus in on it and then unmaximize and so on and so on.

I was wondering if there was a way to configure it so the status bar could show me something that tells me that the buffer I'm on has been maximized, something similar to what tmux does when you maximize one of its panes (it adds and asterisk next to the pane name).

If I need to git gud and write some elisp to achieve this, is there a manual/book/tutorial that can guide me in it.

Thanks again !

**Comment by duianto** [comment]
Here's a discussion about how to use a custom mode line (status bar).
Show words of state indicators in mode line like vim-powerline #12346

This checks if the Emacs frame only has one window (is maximized).
```
(= (length (window-list)) 1)
```

I don't know how to use them together but it might be a starting point.
The spaceline repository (linked in that issue) might have more information.

**Comment by andres-lowrie** [comment]
Sweet... thank you!
