### ISSUE TITLE
How to properly setup magit?

### ISSUE THREAD

**Issue by allentiak** [syl20bnr/spacemacs#12553]
Hi,

I would like to pass a few parameters to magic. However, I can't find the proper section of the `.spacemacs` file where I should add them...

I have already tried the following, and all of them give me a "GitError!" message (see https://github.com/syl20bnr/spacemacs/issues/10942)

Option 1: either on `dotspaceemacs/user-init()` or `dotspaceemacs/user-config()`

``` elisp
  (setq-default
    magit-diff-refine-hunk 'all
    magit-diff-adjust-tab-width t
    magit-diff-paint-whitespace 'all
    magit-diff-highlight-trailing 'all
    magit-diff-highlight-indentation 'all)
```

Option 2: on `dotspaceemacs/configuration-layers()`
``` elisp
  (git :variables
    magit-diff-refine-hunk 'all
    magit-diff-adjust-tab-width t
    magit-diff-paint-whitespace 'all
    magit-diff-highlight-trailing 'all
    magit-diff-highlight-indentation 'all)
```

I got these params from [the magit documentation section of Diff options](https://magit.vc/manual/magit.html#Diffing.) However, I am definitely clueless about where should I put them within the `.spacemacs` file...

Could anyone please help me on this?

**Comment by duianto** [comment]
It might be a variable argument issue.

I first tried it with just the first variable to see if there were any issues with setting a magit variable, and it worked in all three places.

But when I tried it with all your variables/arguments set as git layer variables, and tried to commit some changes, then I also got the error message: `GitError! Git failed`

The magit-process: buffer `$` shows:
>  1 git.exe … "commit" "--"
>
>*ERROR*: Wrong type argument: arrayp, allerror: There was a problem with the editor '"c:/Users/username/Applications/emacs-26.2-x86_64/bin/emacsclient.exe"'.
Please supply the message using either -m or -F option.

And the messages buffer shows:
>magit-diff-paint-hunk: Wrong type argument: arrayp, all
Running C:/Program Files/Git/mingw64/libexec/git-core/git.exe commit --
Type , c to finish, , k to cancel, and <visual-state> g k and <visual-state> g j to recover older messages
Diffing changes to be committed (C-g to abort diffing)
error in process sentinel: user-error: Don’t kill this buffer.  Instead cancel using , k
error in process sentinel: Don’t kill this buffer.  Instead cancel using , k
Git failed ... [Hit $ to see buffer magit-process: .emacs.d for details]
Saving file c:/Users/username/.emacs.d/.git/COMMIT_EDITMSG...
Wrote c:/Users/username/.emacs.d/.git/COMMIT_EDITMSG

When I checked the help information for the variables (with the cursor on the variable and pressing `K`), I noticed that the first two seemed to be fine:
```
          magit-diff-refine-hunk 'all
          magit-diff-adjust-tab-width t
```
But the third one:
```
          magit-diff-paint-whitespace 'all
```
doesn't show `'all` as a possible value in the docstring:

> magit-diff-paint-whitespace is a variable defined in ‘magit-diff.el’.
> Its value is ‘all’
> Original value was t
> 
>   This variable is safe as a file local variable if its value
>   satisfies the predicate which is a byte-compiled expression.
> 
> Documentation:
> Specify where to highlight whitespace errors.
> 
> nil            Never highlight whitespace errors.
> t              Highlight whitespace errors everywhere.
> ‘uncommitted’  Only highlight whitespace errors in diffs
>                showing uncommitted changes.
> 
> For backward compatibility ‘status’ is treated as a synonym
> for ‘uncommitted’.
> 
> The option ‘magit-diff-paint-whitespace-lines’ controls for
> what lines (added/remove/context) errors are highlighted.
> 
> The options ‘magit-diff-highlight-trailing’ and
> ‘magit-diff-highlight-indentation’ control what kind of
> whitespace errors are highlighted.

In the magit manual that you linked to: https://magit.vc/manual/magit.html#Diffing
the next variable is called:
> User Option: magit-diff-paint-whitespace-lines
> Specify in what kind of lines to highlight whitespace errors.
> 
> t Highlight only in added lines.
> both Highlight in added and removed lines.
> all Highlight in added, removed and context lines.

And it accepts `'all` as an argument. Maybe it's just a variable name typo and you might have intended to use: `magit-diff-paint-whitespace-lines`

I kept checking the variables and the next one:
```
          magit-diff-highlight-trailing 'all
```
seems like it might only accept a boolean value: `t` or `nil`.
> magit-diff-highlight-trailing is a variable defined in ‘magit-diff.el’.
> Its value is ‘all’
> Original value was t
> 
>   This variable is safe as a file local variable if its value
>   satisfies the predicate ‘booleanp’.
> 
> Documentation:
> Whether to highlight whitespace at the end of a line in diffs.
> Used only when ‘magit-diff-paint-whitespace’ is non-nil.

It's defined as:
```
(defcustom magit-diff-highlight-trailing t
  "Whether to highlight whitespace at the end of a line in diffs.
Used only when `magit-diff-paint-whitespace' is non-nil."
  :group 'magit-diff
  :safe 'booleanp
  :type 'boolean)
```

source: https://github.com/magit/magit/blob/5362cf75f0a72be1f75efc62aed377b9c18251a1/lisp/magit-diff.el#L246


And the last one:
```
          magit-diff-highlight-indentation 'all
```
it's docstring doesn't mention `'all` as an option either.
> Documentation:
> Highlight the "wrong" indentation style.
> Used only when ‘magit-diff-paint-whitespace’ is non-nil.
> 
> The value is a list of cons cells.  The car is a regular
> expression, and the cdr is the value that applies to repositories
> whose directory matches the regular expression.  If more than one
> element matches, then the *last* element in the list applies.
> The default value should therefore come first in the list.
> 
> If the value is ‘tabs’, highlight indentation with tabs.  If the
> value is an integer, highlight indentation with at least that
> many spaces.  Otherwise, highlight neither.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bd6d4c27f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git
            (git :variables magit-diff-refine-hunk 'all magit-diff-adjust-tab-width t magit-diff-paint-whitespace 'all magit-diff-highlight-trailing 'all magit-diff-highlight-indentation 'all)
            helm javascript markdown multiple-cursors org python spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by allentiak** [comment]
Hi,

Thank you so much for testing this so thoroughly!
I am happy it seems I was simply putting a wrong parameter value :-)

I'll try it and let you know how it went.

Best,
Leandro

**Comment by allentiak** [comment]
Hi, @duianto,

I have tested what you suggested in `dotspaceemacs/configuration-layers()`. I'm almost there!
The following part works:

 ```elisp
(git :variables
            magit-diff-refine-hunk 'all
            magit-diff-adjust-tab-width t
            magit-diff-paint-whitespace t
            magit-diff-highlight-trailing 'all
            ; <magit-diff-highlight-indentation options -- see below>
            )
```

The problematic part is properly quoting the values of the `magit-diff-highlight-indentation` parameter...

I have problems interpreting the documentation...

> Documentation:
    Highlight the "wrong" indentation style.
    Used only when ‘magit-diff-paint-whitespace’ is non-nil.
>
>    The value is a list of cons cells. The car is a regular
    expression, and the cdr is the value that applies to repositories
    whose directory matches the regular expression. If more than one
    element matches, then the last element in the list applies.
    The default value should therefore come first in the list.
>
>    If the value is ‘tabs’, highlight indentation with tabs. If the
    value is an integer, highlight indentation with at least that
    many spaces. Otherwise, highlight neither.


All of the following options give me the same `GitError!`.

a) `(... magit-diff-highlight-indentation '('tabs))`
b) `(... magit-diff-highlight-indentation 'tabs)`

I am definitely quoting the values incorrectly. However, I don't know how to go about it...(If I don't quote the values, I get a "configuration error"...)

Could you please help me on how to properly quote the values? :-)

**Comment by duianto** [comment]
The magit author just posted an answer in the Magit gitter channel:
>The doc-string already describes the expected format (though in terms you might not be familiar with) and if you use the Custom interface then you are guided in getting the format right. `(setq magit-diff-highlight-indentation '(("c:/testrepo" . tabs)))`

https://gitter.im/magit/magit?at=5d3ef32aecf3bf7b1a59f0de

And the docstring was also updated:
>  "Highlight the \"wrong\" indentation style.
Used only when \`magit-diff-paint-whitespace' is non-nil.
>
>The value is an alist of the form ((REGEXP . INDENT)...).  The
path to the current repository is matched against each element
in reverse order.  Therefore if a REGEXP matches, then earlier
elements are not tried.
>
>If the used INDENT is \`tabs', highlight indentation with tabs.
If INDENT is an integer, highlight indentation with at least
that many spaces.  Otherwise, highlight neither."

https://github.com/magit/magit/blob/995c1d8a79c53e69f79b17b2b4cd5298a1380be7/lisp/magit-diff.el#L253

I hadn't used the `M-x customize` interface enough to remember that handles the parentheses etc. and just lets us enter the desired values.

We weren't the only once that misunderstood how it's supposed to be used:
Magit cannot call emacsclient anymore: *ERROR*: Wrong type argument: arrayp, t https://github.com/magit/magit/issues/1998

In this issue the author talks about why it isn't a global value:
Configure correct indentation per repository https://github.com/magit/magit/issues/2929

**Comment by allentiak** [comment]
Thanks for the pointer, @duianto!
I am extremely busy right now, though. I'll take a look and let you know :-)
