### ISSUE TITLE
Change default behavior of narrow-to-defun

### ISSUE THREAD

**Issue by jstaursky** [syl20bnr/spacemacs#12550]
I think it would be better to change the `narrow-to-defun` behavior to first use `clone-indirect-buffer` then use `narrow-to-defun`. That way you can divide your screen to narrow on different areas of the same file. I think this would improve workflow, so that instead of having to type
1. `SPC w /` `(split-window-right)`
2. `SPC b N i` `(clone-indirect-buffer)` 
3. `SPC n f` `(narrow-to-defun)`

You could instead simplify this to:

1. `SPC w /` 
2. `SPC n f`  

This adds functionality and retains the functionality found in the default behavior (for those who have no need of narrowing multiple regions).

**Comment by jstaursky** [comment]
It's simple enough to have user write their own key binding. Nvm

**Comment by duianto** [comment]
Changing the default behavior would probably be undesired for anyone that just wants to narrow in the current buffer.
Because cloning to an indirect buffer creates a new buffer.

A possible solution could be to bind the upper case equivalent key bindings to narrow to an indirect buffer.
```elisp
(defun spacemacs/narrow-to-defun-indirect-buffer ()
  (interactive)
  (call-interactively 'clone-indirect-buffer)
  (call-interactively 'narrow-to-defun)
  (message "Function narrowed to an indirect buffer"))

(defun spacemacs/narrow-to-page-indirect-buffer ()
  (interactive)
  (call-interactively 'clone-indirect-buffer)
  (call-interactively 'narrow-to-page)
  (message "Page narrowed to an indirect buffer"))

(defun spacemacs/narrow-to-region-indirect-buffer ()
  (interactive)
  (call-interactively 'clone-indirect-buffer)
  (call-interactively 'narrow-to-region)
  (message "Region narrowed to an indirect buffer"))
```
```elisp
  (spacemacs/set-leader-keys
    "nF" 'spacemacs/narrow-to-defun-indirect-buffer
    "nP" 'spacemacs/narrow-to-page-indirect-buffer
    "nR" 'spacemacs/narrow-to-region-indirect-buffer
    "nf" 'narrow-to-defun
    "np" 'narrow-to-page
    "nr" 'narrow-to-region
    "nw" 'widen)
```

### Issue
Narrowing to a region shows an error message:
>Error in post-command-hook (evil-visual-post-command): (error "Marker points into wrong buffer" #<marker at 21384 in keybindings.el<2>>)

**Comment by Kazark** [comment]
@duianto I put it PR #14083 that implements your suggestion; would you mind taking a look?

**Comment by duianto** [comment]
The following PR has been merged:
[core] provide keybindings for using narrow with an indirect buffer #14083

It's now possible to narrow using the uppercase letter key bindings:
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#region-narrowing
|  |  |
| - | - |
| `SPC n F`   | narrow to the current function in an indirect buffer |
| `SPC n P`   | narrow to the visible page in an indirect buffer     |
| `SPC n R`   | narrow to the selected text in an indirect buffer    |
