### ISSUE TITLE
Projectile cache

### ISSUE THREAD

**Issue by d12frosted** [syl20bnr/spacemacs#1256]
Hey, I noticed strange behaviour of projectile's cache. It shows me the files that don't exist anymore. I tried to invalidate cache using `M-m p I` and `C-c p i`, but it doesn't help (although I saw message saying that cache for current project is invalidated). 

The only thing that helps me is 

1. close emacs
2. remove `~/.emacs.d/.cache` directory
3. start emacs again

**Formal steps to reproduce**

1. navigate to any file in known project (be it git repository or directory with `.projectile` file) - to make sure that cache is create (also make sure that caching is enabled)
2. create new file in that project (from emacs or externally)
3. remove that file
4. invalidate cache
5. use `M-m p f` or `C-c p f` and notice that removed file still exists in list of files

**Expected**

User expects that removed file doesn't shown in list of files.

---

Sorry if it's not the right place to report this issue.

**Comment by CestDiego** [comment]
I get the same thing... :(

**Comment by tuhdo** [comment]
Could you confirm whether this happen with stock Emacs and only Projectile installed, or does it happen with Spacemacs only?

**Comment by d12frosted** [comment]
Well, few days ago I was using bare projectile and haven't seen this problem.

**Comment by tuhdo** [comment]
I found it: this is a bug in Projectile when you set `projectile-sort-order` to `recentf`. Projectile will then use `recentf`file list and select the files in project, then present those files first without checking for its existent.

**Comment by d12frosted** [comment]
Thanks for this finding. I'll try using `default` as a value of `projectile-sort-order`.

**Comment by jupl** [comment]
There is also the command `recentf-cleanup` to clean up nonexistant files from recentf.

**Comment by CestDiego** [comment]
Oh...we should advise the function that invalidates cache on projectile to also do the recentf-cleanup...or sth D: dunno...maybe have a spacemacs/invalidate-projectile-recentf-cache? bound to `SPC u <projectile command>`

**Comment by d12frosted** [comment]
Nice advice. I like using `recentf`, so here my solution for now:

```lisp
(defun my-invalidate-cache ()
  "Invalidate projectile and recentf cache."
  (interactive)
  (progn (projectile-invalidate-cache nil)
         (recentf-cleanup)))
```

**Comment by syl20bnr** [comment]
This is something to fix upstream right ?

**Comment by tuhdo** [comment]
@syl20bnr Yes. Someone opens an issue there and we can close this.

**Comment by emmanueltouzery** [comment]
If that helps anybody, I got tired of the projectile cache growing stale (which was all the time for me) and simply put `(setq projectile-enable-caching nil)` in my .spacemacs.

Honestly I have yet to notice a performance difference (including on my non-SSD desktop machine).

**Comment by bbatsov** [comment]
The caching exists mostly for the benefit of people using native indexing, as it's pretty slow. If you're using alien indexing you're unlikely to notice any difference for small and medium sized projects.

**Comment by syl20bnr** [comment]
Seems that this issue is fixed upstream.
Closing it.
