### ISSUE TITLE
Install of lsp layer fails with error

### ISSUE THREAD

**Issue by AkashGanesan** [syl20bnr/spacemacs#12564]
#### Description :octocat:
Install of lsp layer fails with error (develop-branch)

#### Reproduction guide :beetle:
- Latest develop branch
- Add lsp layer
- Start emacs

*Observed behaviour:* :eyes: :broken_heart:
error occurred while installing lsp-python-ms (error: (file-error https://elpa.gnu.org/packages/python-0.26.1.el Bad Request))

*Expected behaviour:* :heart: :smile:
lsp installs!

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. b68610954)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(ruby yaml html perl5 helm auto-completion better-defaults emacs-lisp git markdown org gpu bibtex json markdown xkcd spell-checking syntax-checking python perforce github julia ipython-notebook lsp ibuffer themes-megapack)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by swaroopch** [comment]
See https://github.com/syl20bnr/spacemacs/issues/12535

**Comment by toomaj** [comment]
I experience the same thing when trying to install `clojure`
