### ISSUE TITLE
all kinds of errors

### ISSUE THREAD

**Issue by markboston34** [syl20bnr/spacemacs#12571]
i just installed spacemacs for the first time and im getting tons of erros about missing packages and being unable to install things. if there something going on with the repo's?

**Comment by duianto** [comment]
There's an issue with Emacs, that most likely will be fixed in the next version.
This issue has the current workaround:
Failed to download 'gnu' archive. Bad request. (Solution included) #12535

**Comment by MarcusE1W** [comment]
Thanks. The workaround worked for me.
