### ISSUE TITLE
<s-right> is undefined: How to manually add a key mapping in Insert Mode

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#1257]
In normal OS X apps, Command + Right will make the cursor go to the end of current line. I sometimes consider it more convenient than going back to normal mode and pressing `A`. However it seems that this key mapping is not having any effect in spacemacs' insert mode, with `<s-right> is undefined` shown. Since it doesn't seem to have any other functionality yet, how can I remap the key to have the effect I want? If there's no easy way possible, maybe I'll even make it `<Esc> A` etc. I looked through the documentation but haven't found any info on remapping key bindings for insert mode.

**Comment by cpaulik** [comment]
You could set it like this 

```elisp
(define-key evil-insert-state-map (kbd "S-<right>") 'evil-end-of-line)
```

You can find more information about managing keymaps in evil on the [emacs wiki](http://www.emacswiki.org/emacs/Evil#toc8) or the evil documentation.

**Comment by x-ji** [comment]
Cool. That was actually `Command-right` I was talking about and `<s-right>` was the mapping. But it worked all the same.

**Comment by x-ji** [comment]
Actually `'evil-append-line` and `'evil-insert-line` suited my purpose more.
