### ISSUE TITLE
How to toggle by default spacemacs aciton

### ISSUE THREAD

**Issue by burgesQ** [syl20bnr/spacemacs#12576]
Hey, 

I'm new to spacemacs and by searching the web I realized that I could toggle the time mode by adding `(display-time-mode 1)` to my `user-config`.

From there I tried to enable some highlights (long line & indentation) & mode line (battery), but without success..

I tried (successively) :
```help
;; display battry info
(mode-line-battery 1)
(setq mode-line-battery 1)

;; highlight line over 80 col
(highlight-long-lines)
(spacemacs/toggle-highlight-long-lines-globally-on)
(setq spacemacs/toggle-highlight-long-lines-globally-on 1)
(spacemacs/toggle-highlight-long-lines-globally-on 1)

;; highlight indentation
(highlight-indetation-mode 1)
``` 

but none of those work ...

Could someone point me to the right piece of doc ? 

Thanks !

**Comment by duianto** [comment]
These seem to work:
```
    (spacemacs/toggle-mode-line-battery-on)
    (spacemacs/toggle-display-time-on)
    (spacemacs/toggle-highlight-long-lines-globally-on)
```
add them to the `dotspacemacs/user-config` section in `.spacemacs`.

But it doesn't seem to work to enable indentation highlighting globally on startup:
```
(spacemacs/toggle-highlight-indentation-on)
```
because it's docstring says:
>  Automatically becomes buffer-local when set.

Therefore it's only applied to the current buffer when enabled.

**Comment by burgesQ** [comment]
Great thanks ! I can close this issue then !
