### ISSUE TITLE
How to change or add icons to the dashboard ?

### ISSUE THREAD

**Issue by dagnachewa** [syl20bnr/spacemacs#12586]
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

**Comment by dagnachewa** [comment]
How can we add icons to the dashboard and change the layout to look like doom dashboard or this one https://github.com/emacs-dashboard/emacs-dashboard or is it possible to replace the dashboard ?

**Comment by duianto** [comment]
There's a PR that adds colors to the Spacemacs home buffer lists:
Colorized files in Spacemacs Buffer #12539

You could ask the if author knows how that could be implemented.

There's also this related issue:
Is it able to show the index of the recent files/projects in spacemacs home page? #12519

Maybe you three could come up with a combined solution or maybe implement all three and add a dotspacemacs variable where one can choose between them.

#### Note
You can edit your github comments by clicking in the top right corner `...` (three dots) and choose`Edit`. Your first post seems to just be the issue template. You can add your second comment there then remove the second comment.
