### ISSUE TITLE
Any best practices for distributing layers?

### ISSUE THREAD

**Issue by travisbhartwell** [syl20bnr/spacemacs#12592]
I am working on a layer for general configuration to share within my employer.

Is there a reasonable way to distribute this, short of having users manually checking out a git repo with it in it, and make these changes to their `.spacemacs` file:

```elisp
dotspacemacs-configuration-layer-path '("/path/to/layer-repo")
...
dotspacemacs-configuration-layers
'(
   our-internal-layer
...
)
```

But the thing about this is there is not a centralized way to keeping this up to date versus the Update Packages and Update Spacemacs functions exposed on the Spacemacs Home buffer.

Any ideas on how to make it easier?

**Comment by thanhvg** [comment]
I would just put them in `~/emacs.d/private` as mentioned in doc at
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#managing-private-configuration-layers
`Update Packages` will also update all packages regardless of whether they belong to a private layers or not.
I am not sure about `Update Spacemacs` I don't know if it's in force when you are on dev branch.

**Comment by travisbhartwell** [comment]
My question was not about the packages that the distributed layer depends on, I know that Update Packages handles those. I'm talking about the code for the layer itself.

To keep a Spacemacs config up to date now requires 4 things:
- Using the "Update Packages" mechanism in Spacemacs for the packages.
- Either using "Update Spacemacs" in the Spacemacs Home Buffer or updating the Spacemacs git repo for the development branch.
- Updating the repo that my personal config is in.
- Updating the repo that the distributed layer is in.

I would really prefer not to proliferate these mechanisms if possible.
