### ISSUE TITLE
Dart layer might be broken

### ISSUE THREAD

**Issue by bradyt** [syl20bnr/spacemacs#12605]
Disclaimer: not a spacemacs user, but the dart-mode maintainer, and giving a friendly notice that your dart layer might be broken. Apologies for the inconvenience.

`dart-mode.el` has been split in half, the server stuff has been broken into dart-server repo. There is a pull request at melpa to add dart-server, but I don't know if it will take upwards of a month for that to be merged. The layer may need a short `(use-package dart-mode)` and then the old use-package with all the bindings and config will probably be `(use-package dart-server ...`, but until it's added to melpa, you may need to specify url in use-package expression.

There is also a new tag for dart-mode before the split, if you want to freeze the version before then. dart-server also has a tag right after the split, if you want to freeze until it's on melpa.

Links:
- https://github.com/bradyt/dart-mode
- https://github.com/bradyt/dart-server
- https://github.com/melpa/melpa/pull/6352

**Comment by bradyt** [comment]
So one fix might be `:pin melpa-stable` to use dart-mode before the split.

**Comment by bradyt** [comment]
It seems that the following change would provide github location.

```elisp
(defconst dart-packages
  '(dart-mode
    flycheck))
```

Changed to,

```elisp
(defconst dart-packages
  '(dart-mode
    dart-server :location (recipe :fetcher github :repo bradyt/dart-server)
    flycheck))
```

**Comment by duianto** [comment]
Thanks for posting this notice. We're investigating.

**Comment by duianto** [comment]
I posted a PR with a possible fix:
[dart] Add dart-server package #12608 

We just need someone to test it, to make sure that it still works as expected.

**Comment by smile13241324** [comment]
Hi @bradyt,
we seem to have some serious issues in getting `dart-server` to work. When I execute `(dart-server t)` manually evil and which-key breaks. Have you heard of issues like described in #12608 before with your package?

I will try to have a look at what exactly breaks but I would still be happy about some hints if you have any.

**Comment by bradyt** [comment]
Hello @smile13241324,

I don't know when I can work on this.

Can spacemacs pin to dart-mode, at melpa-stable before the split?

If you can reproduce the issue without spacemacs, you're welcome to file an issue at dart-server.el repo.

But the real intention I have here, is to see dart-server.el as having less priority to maintain. Someone might factor the formatting out, to not rely on the dart server process to get path. There is also alternatives in reformatter.el, or format-all.

Besides the formatter, there is the dart analysis tools, and again, a lot of that may find better maintained packages in eglot and lsp-mode.

I think the above reduce the priority of reimplementing the dart layer exactly as it was before. Otherwise, again, you could pin to melpa stable in the short term. Also, minimal broken examples (without spacemacs, full and minimal steps, and with full backtraces, etc.) are welcome at dart-server.el repo, but not sure when I can address them.

**Comment by bradyt** [comment]
Perhaps someone can share a spacemacs user config here that does the pinning, to help people visiting the issue with a quick fix?

**Comment by bradyt** [comment]
Oh, I've reproduced the issue. And looking at the source code, of course, I forgot to return the `map` in the `defvar` of the keymaps. This is why I wasn't too keen on melpa's insistence of the code being modified before adding the split package.

**Comment by smile13241324** [comment]
I think this can be safely closed, point is we now have LSP for the dart layer which is also the primary way to continue working with dart.
