### ISSUE TITLE
[Clojure] Feature request regarding code folding

### ISSUE THREAD

**Issue by abhi18av** [syl20bnr/spacemacs#12602]
Hello spacemacs team,

I was wondering if there's already a more specific version of `evil fold` which acts only on the `comment` blocks in a file. This would essentially be a specific version of `z m` which is focused on `comments` in a `clj(s|c)` file.

Could you please point me in the right direction of help me out with the function?

**Comment by duianto** [comment]
This package sounds like it does you want:
https://www.emacswiki.org/emacs/HideOrIgnoreComments
and/or it might be helpful for figuring out how to implement the desired behavior.

**Comment by abhi18av** [comment]
Thanks @duianto, this package seems really handy!

**Comment by FieryCod** [comment]
@abhi18av `SPC c h` is your friend

**Comment by abhi18av** [comment]
@FieryCod , I've tried your suggestions and I'm happy to discover that it clears up the `;; comment` lines in the code. But it seems my wording wasn't clear for what I asked here 

Here's what happend with `SPC c h` 

![2019-08-14 21 03 25](https://user-images.githubusercontent.com/12799326/63034665-5aac5400-bed7-11e9-8a6a-f6f793bbb082.gif)


What I was looking for is a solution which folds all `(comment .... )` blocks in the code at once like so (done for a single block) 
![2019-08-14 21 04 03](https://user-images.githubusercontent.com/12799326/63034750-79aae600-bed7-11e9-9c68-6299e97eefb9.gif)

**Comment by yuhan0** [comment]
Here's a little function I have in my init file for that, feel free to take and modify it / integrate into Spacemacs:

```emacs-lisp
(defun qyh/clojure-close-comments (arg)
  "Close all top level (comment) forms. With universal arg, open all."
  (interactive "P")
  (save-excursion
    (goto-char (point-min))
    (while (search-forward-regexp "^(comment\\>" nil 'noerror)
      (call-interactively
       (if arg 'evil-open-fold
         'evil-close-fold)))))

(evil-define-key 'normal clojure-mode-map
  "zC" 'qyh/clojure-close-comments
  "zO" (lambda () (interactive) (qyh/clojure-close-comments 'open)))
```

**Comment by abhi18av** [comment]
@yuhan0 this is beautiful! Thanks man 👍 

I'll be closing this now, though I think that this thing is really handy and it might be worth adding this in the `clojure-mode` itself :)
