### ISSUE TITLE
Unable to type "C" in insert state

### ISSUE THREAD

**Issue by seschwar** [syl20bnr/spacemacs#1260]
I am unable to type the uppercase letter C in insert mode. I am not kidding.

I can type any other letter in insert state.  I can type "C" in ex, M-x and emacs state.  I can get a "C" with "C-q C" in insert mode.  However when i hit S-c in insert state "C-" is show in the message area.  When i try "C-h k C" in insert state i get "Describe key (or click menu item): C-" in the message area.  Somehow C seems to be bound to some kind of prefix key in insert state.

It seems I am not the only one with this problem:

    16:29:26 <seschwar> i have the funniest problem i can't type "C" in insert mode :D
    16:29:54 <seschwar> it seems to act like a prefix key
    16:30:13 <CestDiego> LOOOOOOOOOOOOOOOOOOL I have that too xD
    16:30:32 <CestDiego> wait..now I can D:
    16:30:35 <seschwar> how to fix it?
    16:30:51 <CestDiego> dunno..did C-g
    16:31:01 <CestDiego> trying to re-duplicate

I didn't do any fancy configuration. Just enabled a few layers and adjusted some settings with customize. The behaviour is independent of major mode and persists after Emacs is restarted.

**Comment by CestDiego** [comment]
Never could re-duplicate...maybe it was a mistake of mine. :( I wish I had this bug though.

**Comment by CestDiego** [comment]
Hey... just checked out..this happens to me in an html file...using web-mode buut with `T` instead of `C` D:

**Comment by seschwar** [comment]
Running `helm-descbinds` in insert state tells me that `C` is indeed a prefix key.  But one erroneously defined by me. I used

    (evil-global-set-key 'insert "C-v" 'quoted-insert)

instead of

    (evil-global-set-key 'insert (kbd "C-v") 'quoted-insert)

This can be closed then as @CestDiego fixed his similar issue with #1264.
