### ISSUE TITLE
Color Theme Bug

### ISSUE THREAD

**Issue by jcguu95** [syl20bnr/spacemacs#12613]
* I am reporting a bug. I used the bug reporting system by using `SPC h I` in spacemacs. However, at the end after using `C-c C-c` to submit, it pops out a webpage with error. I am not sure if it has been successfully submitted so decide to paste it here anyway.

---

#### Description :octocat:
I love the color theme "gruvbox", and have tried very hard to implement that.
I followed the documentation and found a bug.

#### Reproduction guide :beetle:
- Edit ~/.spacemacs by adding 'gruvbox' in to the list of themes:
  ```
  ...
  dotspacemacs-themes '(gruvbox spacemacs spacemacs-light)'
  ...
  ```
- Open emacs
- Emacs seems to be downloading the theme
- It works! (for only this time)
- Close emacs
- Open emacs again
- An error pop out! (more in the observed behaviour section)
- Close emacs, sadly
- Remove "gruvbox" from the config file
- Open emacs again. Emacs will remove the theme package it just installed.
- Close emacs
- Add "gruvbox" again in the config, the same way.
- Open emacs, and it will download and load the theme correctly.
- Close emacs, and openning it again gives the same error.
- Repeat the above. The error came out 5 times, and I am convinced that this is a bug.

*Observed behaviour:* :eyes: :broken_heart:
- After opening emacs the second time, the theme "gruvbox" fails to be loaded.
- The system falls back to the default theme, and outputs an error/warning message on the welcoming page, as follows:
                      Warnings:
                          - An error occurred while applying the theme "gruvbox", fallback on theme
                            "spacemacs-dark". Error was: (file-missing Cannot open load file No such file or
                            directory autothemer)      
                          - Please check the value of "dotspacemacs-themes" in your dotfile or open an issue
                            so we can add support for the theme "gruvbox".      

*Expected behaviour:* :heart: :smile:
- The system should (but not) work as the theme was freshly loaded.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
There are a several issues about the gruvbox theme on the `master` branch.
No easy way to use custom themes #7373
Unable to use some themes (e.g. darktooth and gruvbox) #8090
Themes not loading #8871
Some themes from the themes-megapack cannot be set as default #11380
etc.

It's marked as `fixed in develop`, but this might be a workaround on the `master` branch:
https://github.com/syl20bnr/spacemacs/issues/8871#issuecomment-308822752
