### ISSUE TITLE
[SOLVED] Clojure layer do NOT install correcly on Mac OSX

### ISSUE THREAD

**Issue by MrMic** [syl20bnr/spacemacs#12617]
- The installation is OK with Linux but with Mac OSX, I got issue:
=> queue always send back: Bad request

--> installing package: cider@clojure... [1/5]
An error occurred while installing cider (error: (file-error https://elpa.gnu.org/packages/queue-0.2.el Bad Request))
--> installing package: clj-refactor@clojure... [3/5]
An error occurred while installing clj-refactor (error: (file-error https://elpa.gnu.org/packages/queue-0.2.el Bad Request))
--> installing package: clojure-snippets@clojure... 

But the package is on Melpa, so...

Thanks for fixing it.
Any help welcome.
Rgds,

**Comment by duianto** [comment]
It sounds like this issue:
Failed to download 'gnu' archive. Bad request. (Solution included) #12535

**Comment by MrMic** [comment]
Yes, indeed.
Thank you very much.
I close so.
