### ISSUE TITLE
word-motions should include underscores

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#1261]
In vim `foo_bar` is considered as single word for word motions <kbd>w</kbd>, <kbd>dw</kbd>, etc. However in spacemacs that's three separate words `foo` `_` `bar`

In vim there's `iskeyword` option that defines what is a word, default appears to be `@,48-57,_,192-255`

http://vimdoc.sourceforge.net/htmldoc/motion.html#word-motions

**Comment by syl20bnr** [comment]
I consider this a user preference.
For more info see #1248 
PR to add this to [HOWTOs.md](https://github.com/syl20bnr/spacemacs/blob/master/doc/HOWTOs.md) very welcome :-)

**Comment by tko** [comment]
No argument about user preference, but IMO the default should be vim compatible to not add any unnecessary friction for everyone grown used to vim behaviour.

The PR was python specific. Is there some generic variable (similar to vim iskeyword) that would apply to all modes, or is this a tweak that must be applied to all modes separately?

Oh, I just realized the inconsistency in spacemacs is mode-specific. In haskell mode <kbd>w</kbd> and <kbd>\*</kbd> behave as in vim, in text and python modes <kbd>w</kbd> is inconsistent with <kbd>\*</kbd>, the latter still working as expected. Seems like there are multiple variables per mode involved?

**Comment by syl20bnr** [comment]
`*` always select the whole symbol since it is a quick symbol search. Indeed in Haskell `_` is part of a word, we may fix this.

**Comment by tko** [comment]
For reference, just stumbled upon [Underscore "_" is not a word character](https://bitbucket.org/lyro/evil/wiki/Home#!underscore-_-is-not-a-word-character) in evil wiki.

**Comment by simplygood** [comment]
If this is not going to be fixed, is there a work-around? Or, can you make this as a configurable option?

**Comment by TheBB** [comment]
This is probably not going to be fixed. See @tko's link for a way to configure this behaviour yourself. The `o` text object can also be used in many cases where this causes problems with `w`, `b`, `e` and `ge`.

I'm liable to agree with @syl20bnr.

**Comment by simplygood** [comment]
The solution found in @tko's link wasn't good enough. (setq-default evil-symbol-word-search 'symbol) seems to be the right way to go. I've been using for the past hour and it works really well. Could this make into a FAQ?

**Comment by TheBB** [comment]
@simplygood Yeah, that seems to change the behaviour for `*` and `#`, but not `w`, `b`, `e` and `ge`. Still, doc PRs are welcome. :-)

**Comment by syl20bnr** [comment]
Is it feasible to unify the behavior in all the modes and use something like https://github.com/tarao/evil-plugins/blob/master/evil-little-word.el ?

**Comment by TheBB** [comment]
I've been using evil-litte-word since I started using Spacemacs. I know it was removed at some point for unknown (to me) reasons, but I've had no problems with it.

**Comment by lukeorland** [comment]
I set this as the default behavior in Python by adding a line to my `.spacemacs`. I borrowed the code from the PR #1248.

```
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
 This function is called at the very end of Spacemacs initialization after
layers configuration. You are free to put any user code."

  ;; Make underscore count as a word character in Python mode.
  (modify-syntax-entry ?_ "w" python-mode-syntax-table)
)

```

**Comment by lukeorland** [comment]
My example in the last post actually causes spacemacs to hang when starting up. The error message is `Symbol's value as a variable is void: python-mode-syntax-table`. I'm a heavy Vim user with almost no experience using Emacs. How can I configure Spacemacs to treat underscore characters the same as Vim does by default, without forking and modifying the Spacemacs repo?

**Comment by TheBB** [comment]
Try doing it after python loads.

```
(with-eval-after-load python-mode
  (modify-syntax-entry ...))
```

**Comment by lukeorland** [comment]
Thanks for the suggestion. I changed it to this:

```
  (with-eval-after-load "python-mode"
   (modify-syntax-entry ?_ "w" python-mode-syntax-table))
```

but `_` characters are still not treated as part of a word.

I can probably just take this to gitter, since I think I'm steering the discussion away from the topic of this GitHub issue.

**Comment by ericmj** [comment]
Putting `(modify-syntax-entry ?_ "w")` inside `dotspacemacs/user-config` doesn't work for me. I would be will to contribute to the HOWTO but first I need to know how to configure it.

**Comment by TheBB** [comment]
@ericmj That only modifies the syntax table of the current buffer, which happens to be whatever buffer is current when that code runs. You want to put it in a hook or make the syntax table explicit, as in @lukeorland's code.

@lukeorland Your code probably doesn't work since python stuff is defined in python.el, not python-mode.el, so your `with-eval-after-load` is waiting forever for something that will never be loaded.

**Comment by TheBB** [comment]
I have added this to the FAQ now. I think this is due for closing.

**Comment by alxndr** [comment]
Where is it in the FAQ?

**Comment by TheBB** [comment]
Here: https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#include-underscores-in-word-motions

To be precise, it's in the FAQ on the develop branch.

**Comment by devlinzed** [comment]
I don't think this is an issue of user preference because it diverges from vim unnecessarily and unintuitively.  The documentation is unhelpful because this should be a global and not per-mode behaviour.

**Comment by elcritch** [comment]
Not sure what the state of this is but I just started using Spacemacs a couple of weeks back and I am really loving everything _but_ the lack of underscore support. The docs only mention configure support per language, but this seems to work well for me (just minor testing so far). Can anyone comment why this wouldn't be a good 'across the board solution', maybe to add to the docs? `(add-hook 'prog-mode-hook #'(lambda () (modify-syntax-entry ?_ "w")))`

**Comment by harveyslash** [comment]
putting 
` (modify-syntax-entry ?_ "w")`
in user-init makes it work for all files. 
I am new to spacemacs ,so this could cause problems , but it seems to work for me

**Comment by classieur** [comment]
> @simplygood Yeah, that seems to change the behaviour for `*` and `#`, but not `w`, `b`, `e` and `ge`. Still, doc PRs are welcome. :-)

Together with `(defalias 'forward-evil-word 'forward-evil-symbol)` it works.

**Comment by togakangaroo** [comment]
Where is the HOWTO referenced throughout here? The link seems to be dead.

**Comment by syl20bnr** [comment]
We have this: https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#include-underscores-in-word-motions
