### ISSUE TITLE
Warning on startup after adding new flycheck checker

### ISSUE THREAD

**Issue by jkbest2** [syl20bnr/spacemacs#12626]
#### Description :octocat:
Warning on startup after adding custom flycheck checker.

(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: flycheck-define-checker

#### Reproduction guide :beetle:
- Add custom checker to flycheck by inserting the following into `dotspacemacs/user-config`:

```elisp
  (flycheck-define-checker todo-checker
    "A checker to list open TODOs, CITEs, or other annotations in
  a file."
    :command ("todo-checker" source)
    :error-patterns
    ((warning line-start (file-name) ":" line ":" column ":" (message) line-end))
    :modes markdown-mode))
```

Where [`todo-checker`](https://github.com/jkbest2/todo-checker/blob/master/todo-checker) is a super simple regex that returns lines with `TODO` or sentences with `CITE`.

- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Warning on startup

```
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: flycheck-define-checker
```

No warning when `.spacemacs` is reloaded (`SPC f e R`).

After enabling `flycheck-mode`, checker works as expected, but only after `.spacemacs` is reloaded.

*Expected behaviour:* :heart: :smile:
No warning.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0ca502823)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion bibtex csv deft docker emacs-lisp ess
                 (geolocation :variables geolocation-enable-weather-forecast t)
                 git helm imenu-list jkb julia latex lsp markdown neotree
                 (org :variables org-enable-org-journal-support t org-journal-date-format "%Y-%m-%d %A (W%W)" org-journal-dir "~/Dropbox/journal" org-journal-enable-encryption t org-crypt-key "751707c9" org-tags-exclude-from-inheritance
                      '("crypt"))
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 speed-reading
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 themes-megapack version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND GSETTINGS NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 THREADS

**Comment by duianto** [comment]
`flycheck` might be lazy loaded, meaning that it's loaded when it's used, this might work. At least it doesn't show a void warning on startup:
```elisp
(with-eval-after-load 'flycheck
      (flycheck-define-checker todo-checker
        "A checker to list open TODOs, CITEs, or other annotations in
  a file."
        :command ("todo-checker" source)
        :error-patterns
        ((warning line-start (file-name) ":" line ":" column ":" (message) line-end))
        :modes markdown-mode))
```

**Comment by jkbest2** [comment]
That did it, thanks! I knew about `with-eval-after-load 'org`, but it's good to know it can be used for other packages.
