### ISSUE TITLE
Js-beautify - custom indentation levels

### ISSUE THREAD

**Issue by Migacz85** [syl20bnr/spacemacs#12621]
Hi - how I can setup custom indentation levels using web-beautify in spacemacs?

**Comment by duianto** [comment]
This might be what your looking for:
https://github.com/yasuyk/web-beautify#js-beautify-settings

**Comment by Migacz85** [comment]
Oh yeah, just add  .jsbeautifyrc to the project. That's can be fine. I just landed here from vim and there I just wrote a script where I was able adjust identation on the fly. However - that's fine. Thanks
