### ISSUE TITLE
[Hy Layer] Error while auto-completion

### ISSUE THREAD

**Issue by abhi18av** [syl20bnr/spacemacs#12624]
#### Description :octocat:

Auto-completion not working for `hy` layer

#### Reproduction guide :beetle:
- Start Emacs
- Open any file with suffix `hy`

*Observed behaviour:* :eyes: :broken_heart:

<img width="1280" alt="Screenshot 2019-08-16 at 2 17 40 PM" src="https://user-images.githubusercontent.com/12799326/63155792-ec7ba480-c030-11e9-9534-943e745c97e2.png">

*Expected behaviour:* :heart: :smile:
It should show the proper auto-completion 

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3757ad131)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(alda asciidoc
      (auto-completion
       (haskell :variables haskell-completion-backend 'intero haskell-process-type 'stack-ghci haskell-enable-hindent-style "johan-tibell"))
      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t auto-completion-tab-key-behavior 'cycle auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" auto-completion-enable-snippets-in-popup t :disabled-for org)
      copy-as-format
      (clojure :variables clojure-enable-sayid t clojure-enable-linters t clojure-enable-clj-refactor t)
      chrome csv c-c++ dap debug deft django docker dhall emoji ess emacs-lisp evil-snipe finance geolocation
      (go :variables go-use-golangci-lint t go-use-test-args "-race -timeout 10s" go-tab-width 4 gofmt-command "goimports" go-format-before-save t)
      groovy github
      (git :variables magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
      (helm :variables helm-enable-auto-resize nil)
      html hy import-js imenu-list
      (ibuffer :variables ibuffer-group-buffers-by 'projects)
      (java :variables java-backend 'lsp)
      (javascript :variables javascript-fmt-tool 'prettier javascript-import-tool 'import-js javascript-backend 'tern)
      json lsp
      (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
      (markdown :variables markdown-live-preview-engine 'vmd)
      ocaml
      (org :variables org-enable-github-support t org-enable-bootstrap-support t org-enable-org-journal-support t org-enable-reveal-js-support t org-enable-hugo-support t)
      perl5 prodigy parinfer
      (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t python-test-runner
              '(pytest nose))
      prettier prodigy react
      (ruby :variables ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec)
      rust restclient ranger shell-scripts
      (scheme :variables geiser-chez-binary "chez" scheme-program-name "chez")
      spacemacs-org spacemacs-evil
      (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/local/bin/bash" shell-default-height 30 shell-default-position 'bottom shell-enable-smart-eshell t shell-protect-eshell-prompt nil)
      spell-checking syntax-checking sql tern tmux transmission treemacs version-control vinegar vagrant web-beautify xkcd yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by mightydeadunicorn** [comment]
Any update on this?

**Comment by duianto** [comment]
Confirmed:

![emacs, hy-mode, completion, without jedhy](https://user-images.githubusercontent.com/13420573/89710181-f18fdd00-d980-11ea-9eda-db8e6eff0c28.png)

### Cause

On https://github.com/hylang/hy-mode it says:
>IDE components like autocompletion via company-mode rely on jedhy, which can be installed as standard with pip install jedhy in your virtual environment of choice, see https://github.com/ekaschalk/jedhy.

### Solution
The completion list appears correctly, after installing `jedhy`:
```
pip3 install jedhy
```
and then closing and reopening the `.hy` file:

![emacs, hy-mode, completion, with jedhy](https://user-images.githubusercontent.com/13420573/89710207-27cd5c80-d981-11ea-8936-f3a3f3dc61c5.png)

<details><summary>
PopOS 20.04, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3388972c2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm hy lsp multiple-cursors org
                 (python :variables python-backend 'anaconda python-formatter 'yapf)
                 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking
                 (typescript :variables typescript-backend 'lsp)
                 version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

### Fix
The Hy layer readme will be updated with the instructions.

**Comment by duianto** [comment]
The hy layer readme has been updated.
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/hy#auto-completion
