### ISSUE TITLE
keymapping for major mode not working

### ISSUE THREAD

**Issue by frankieliu** [syl20bnr/spacemacs#12631]
#### Description :octocat:
setting (spacemacs/set-leader-keys-for-major-mode 'python-mode "opa" 'my-code)
doesn't seem to work

#### Reproduction guide :beetle:
- Start Emacs
- edit test.py
- SPC o p a  (doesn't get picked up by spacemacs)

*Observed behaviour:* :eyes: :broken_heart:
After pressing o, I don't see an option for p

*Expected behaviour:* :heart: :smile:
The keybinding SPC o p a should be working

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0ca502823)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm auto-completion
        (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-privat-snippets-directory
                         '("~/Dropbox/Dev/Emacs/yasnippet"))
        emacs-lisp git org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
```elisp
(spacemacs/set-leader-keys-for-major-mode 'python-mode "opa" 'my-code)
```
That binds a major mode key under: `SPC m o p a`

This binds it under the leader key `SPC o p a`:
```elisp
(spacemacs/set-leader-keys "opa" 'my-code)
```

I don't know how to only bind `SPC o p a` while in python-mode.

**Comment by frankieliu** [comment]
@duianto thank you indeed it binds to SPC m o p a, confirmed.
