### ISSUE TITLE
`SPC SPC` doesn't do `M-x`

### ISSUE THREAD

**Issue by creasyw** [syl20bnr/spacemacs#12632]
#### Description :octocat:
`SPC SPC` doesn't do `M-x`

#### Reproduction guide :beetle:
- Start Emacs in a terminal
- Use `SPC SPC` but the message shows "SPC SPC is undefined" 

I normally pick up the upstream from the `develop` branch on a weekly basis, so there are not too many commits. So, I revert them one by one and find the problematic commit is 5f308b030. If I check out at the commit 883cf9730, which is the one earlier, the `SPC SPC` command is working.

*Observed behaviour:* :eyes: :broken_heart:
`SPC SPC` doesn't start Helm for emacs command

*Expected behaviour:* :heart: :smile:
`SPC SPC` should start Helm for emacs command

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5f308b030)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion
      (haskell :variables haskell-completion-backend 'intero)
      emacs-lisp git markdown multiple-cursors treemacs
      (latex :variables latex-enable-auto-fill t latex-enable-folding t latex-build-command "LaTeX")
      (org :variables org-startup-truncated nil org-want-todo-bindings t org-enable-org-journal-support t org-journal-file-format "%Y-%m-%d.org" org-journal-dir "~/workspace/journal/" org-journal-date-prefix "#+TITLE: " org-journal-date-format "%A, %B %d %Y, %H:%M:%S" org-journal-time-prefix "* " org-journal-time-format "")
      (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion t spell-checking-enable-auto-dictionary t)
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (syntax-checking :variables syntax-checking-enable-tooltips nil)
      (c-c++ :variables c-c++-enable-clang-support t c-c++-enable-google-style t c-c++-enable-clang-format-on-save nil c-c++-default-mode-for-headers 'c++-mode)
      cscope markdown
      (python :variables python-indent-offset 4 python-fill-column 100 python-indent-guess-indent-offset nil)
      (go :variables go-autocomplete t go-use-gometalinter t gofmt-command "goimports" go-tab-width 4))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB MODULES THREADS

**Comment by duianto** [comment]
The broken commit has been reverted, update Spacemacs and it should be fixed.

**Comment by creasyw** [comment]
Thank you, @duianto!
