### ISSUE TITLE
"Symbol’s value as variable is void: spacemacs-theme-custom-colors" on startup

### ISSUE THREAD

**Issue by HMPerson1** [syl20bnr/spacemacs#12630]
#### Description :octocat:
When starting Emacs, this error message is shown:
```
spacemacs/startup-hook: Symbol’s value as variable is void: spacemacs-theme-custom-colors
```

#### Reproduction guide :beetle:
- Have neither spacemacs theme listed first in `dotspacemacs-themes`
- Start Emacs
- Look at `*Messages*` buffer

*Observed behaviour:* :eyes: :broken_heart:
I see an error message

*Expected behaviour:* :heart: :smile:
I don't see any error messages

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 53f1445ec)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(coq emoji ruby graphviz python latex scala html yaml lsp
     (rust :variables rust-backend 'lsp)
     dap
     (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-lsp-cache-dir "/tmp/ccls-cache/" c-c++-lsp-sem-highlight-method 'font-lock c-c++-lsp-sem-highlight-rainbow t)
     (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
     emacs-lisp games git
     (haskell :variables haskell-completion-backend 'intero)
     (java :variables java-backend '_)
     helm markdown multiple-cursors spell-checking syntax-checking treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by HMPerson1** [comment]
Seems to be caused by https://github.com/syl20bnr/spacemacs/commit/5f308b0306d44b20d200ee2bc490540e1c9ee149 since commenting out the following lines gets rid of the error:
https://github.com/syl20bnr/spacemacs/blob/53f1445ecc10a491bc90d96b2da540cf489ca91d/core/core-spacemacs.el#L224-L227

**Comment by duianto** [comment]
The broken commit has been reverted, update Spacemacs and it should be fixed.

**Comment by pangdaxing23** [comment]
The revert fixed it on mine.
