### ISSUE TITLE
Spacemacs scans whole home directory for layers when it is current pwd

### ISSUE THREAD

**Issue by greboide** [syl20bnr/spacemacs#12643]
#### Description :octocat:
Spacemacs scans whole home directory for layers when it is current pwd

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
if there is a directory that spacemacs doesnt have permission to scan on my home
directory spacemacs brakes...

*Expected behaviour:* :heart: :smile:
it shouldnt scan it in the first place

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 600ca198a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(typescript html yaml helm
            (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
            c-c++ ruby ruby-on-rails javascript auto-completion better-defaults emacs-lisp git markdown org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking version-control gtags semantic
            (colors :variables colors-enable-nyan-cat-progress-bar t colors-colorize-identifiers 'variables)
            spotify themes-megapack ibuffer parinfer nim python treemacs google-calendar circe gnus multiple-cursors bibtex vinegar)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD JSON CANNOT_DUMP LCMS2

#### Backtrace :paw_prints:
I found the culprit to be dotspacemacs-configuration-layer-path being set as ""
and that was triggering the search path on current pwd on the function configuration-layer/discover-layers

**Comment by syl20bnr** [comment]
This is not the default value and the documentation for this variable is:

```
```
