### ISSUE TITLE
Spacemacs takes too long to start when network is poor or absent

### ISSUE THREAD

**Issue by mopsfelder** [syl20bnr/spacemacs#12642]
After https://github.com/syl20bnr/spacemacs/commit/25f639e40327f91752ec275cf7eb577fb2207cad, spacemacs takes too long to start when network is poor or absent.

Does spacemacs really need Internet connection to just start?
Can that connection check be done only when installing or upgrading packages?

This change dramatically breaks offline workflows to the point of leaving spacemacs useless when there is no Internet connection.

**Comment by henriquenj** [comment]
After 1541f7f515c69cb40c6800e2f43ce6a9131ec5df you should be able to start spacemacs at least.

**Comment by syl20bnr** [comment]
This work-around is necessary to fix a bug in some combination of Emacs and Gnutls versions.

How long is it exactly ?

We can define a timeout for it if necessary but I need to know how much time it takes for you to start.

Also another way to prevent this from happening is to use either use `gnutls` version 3.6.3 or lower or use Emacs 27 built from source. You can verify your version with `gnutls-cli --version`.

**Comment by syl20bnr** [comment]
Going to try another way to do it without contacting a URL but it might be less reliable.

**Comment by syl20bnr** [comment]
@mopsfelder I pushed an offline version of the work-around.

**Comment by mopsfelder** [comment]
Thank you @syl20bnr
