### ISSUE TITLE
Emacs after initilization always shows the same error with magit-gh-pulls-popup

### ISSUE THREAD

**Issue by vityafx** [syl20bnr/spacemacs#12650]
#### Description :octocat:
Every time I open my emacs, I see this error after initialization:

> Symbol’s value as variable is void: magit-gh-pulls-popup

It does not seem to affect magit anyhow, but annoys me all the time I run emacs and
open the magit status popup (only once).

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The error buffer opens and shows the message:

> Symbol’s value as variable is void: magit-gh-pulls-popup

*Expected behaviour:* :heart: :smile:
The emacs launches successfully without opening and other error buffers, does not show any error messages.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 40024fedb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python racket lua yaml extra-langs clojure scheme octave rust javascript java latex html sql common-lisp asm
        (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
        markdown version-control helm emacs-lisp git github
        (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by bjartur** [comment]
I had the same issue on Emacs 26.2 on Windows 10. I worked around the issue by reinstalling one package (I'm 90% certain it was magit-gh-pulls but it's possible it was magit-popup). Haven't seen the message since.

**Comment by andreineculau** [comment]
FWIW it was `magit-popup`. Thanks @bjartur !

**Comment by duianto** [comment]
This has been fixed on the `develop` branch:
Remove magit-gh-pulls as it never worked too well for me #10684

**Comment by vityafx** [comment]
Can confirm that it is fixed on the `develop` branch.

**Comment by vityafx** [comment]
Closed, re-open if you want to make it visible and clear to track for the `master` branch. I've been using the `develop` branch for quite a while and so for me, personally, it is okay now.
