### ISSUE TITLE
'dd' with whitespace-mode sometimes raises 'wrong-type-argument wholenump -[integer]'

### ISSUE THREAD

**Issue by JadElClemens** [syl20bnr/spacemacs#12651]
#### Description :octocat:
When placed on a whitespace character at the beginning of the line, using `dd` to delete a line (or `yy` to yank, `gcc` to comment, likely more) results in the error `wrong-type-argument wholenump -5`. This does not happen with `D`.

This seemingly only happens with `whitespace-mode` enabled. I tried debugging with only `evil` and `whitespace-mode` (using `make emacs` in a fresh evil source dir) and did not encounter this issue even with the same reproduction method.

~I can't confirm this, but after testing for a minute or so it seems like this only happens when the line contains or is immediately preceded or followed by "invalid" whitespace (e.g. a line containing only non-newline whitespace or that has trailing whitespace).~

After more testing, I have determined that the error occurs when either
1. Trying to perform such an action on a line when the cursor is placed on a whitespace character in column 0. In this case, the error is random and I sometimes have to keep undoing the action (in case of deleting), moving back and forth between lines, and trying again in order to encounter it.
2. Trying to perform such an action after moving the cursor up or down off of the second whitespace character in a line and not having moved left or right. When the cursor is first moved up or down, it will jump to column 0. With this method, the error occurs every time.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file or enter some text (multiple lines) in the scratch buffer. Make sure that one of the lines has two whitespace characters at the beginning.
- Enable `whitespace-mode` if not already enabled
- Try to perform one of the actions 1. or 2. outlined above

*Observed behaviour:* :eyes: :broken_heart:
The line is not deleted and I get the error message `wrong-type-argument wholenump -[integer]`, most often -5.

*Expected behaviour:* :heart: :smile:
The line is deleted.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f3f2db831)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(colors helm
		(auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
		(spell-checking :variables enable-flyspell-auto-completion t spell-checking-enable-by-default nil)
		syntax-checking evil-commentary git semantic themes-megapack
		(treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t treemacs-space-between-root-nodes nil treemacs-git-mode 'deferred)
		bibtex
		(c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
		emacs-lisp
		(latex :variables latex-enable-folding t)
		markdown
		(python :variables python-test-runner 'pytest)
		shell-scripts systemd
		(mu4e :variables mu4e-enable-mode-line t)
		(org :variables org-enable-github-support t)
		multiple-cursors gtags)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument wholenump -5)
  signal(wrong-type-argument (wholenump -5))
  evil-motion-range(evil-line nil nil)
  evil-operator-range(t)
  byte-code("\306\307\310\"\205\017\0\311\307\310\"\206\017\0\312\030\311\307\313\"\031`\032\314\211\033\034\314\211\035\026\026\016\027\026\030\315\316\317!\016\031\320 D\"`\022\015\026\026\321 \204=\0\322 \203@\0\317\026\032\321 \203L\0\323\324!\210\202`\0\311\307\325\"\203]\0\013\206X\0\nb\210\202`\0\nb\210.\006\207" [evil-operator-range-motion evil-operator-range-type orig evil-operator-range-beginning evil-operator-range-end evil-inhibit-operator evil-has-command-property-p evil-delete :motion evil-get-command-property undefined :type nil append evil-operator-range t evil-yank-handler evil-visual-state-p region-active-p evil-visual-rotate upper-left :move-point evil-inhibit-operator-value this-command evil-this-operator evil-this-register deactivate-mark] 5)
  call-interactively(evil-delete nil nil)
  command-execute(evil-delete)
```

**Comment by duianto** [comment]
I was unable to reproduce it in either Ubuntu or Windows.
But it's expected since you said that only happens sometimes.

<details><summary>
Ubuntu 18.04.3
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1299f262c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm markdown multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1299f262c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git
            (gnus :variables gnus-secondary-select-methods
                  '((nntp "gmane"
                          (nntp-address "news.gmane.org"))
                    (nntp "news.eternal-september.org")
                    (nntp "nntp.aioe.org")
                    (nntp "news.gwene.org")))
            helm multiple-cursors
            (org :variables)
            python
            (shell :variables eshell-completion-frame nil shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

#### Notes:
I noticed a typo in your layers:
```
(spell-checking :variables =enable-flyspell-auto-completion= t spell-checking-enable-by-default nil)
```
Remove the `=` (equal signs). The typo was most likely copied from the websites spell-checking documentation:
http://spacemacs.org/layers/+checkers/spell-checking/README.html#enable-auto-completion-popup

It's been fixed on the develop branch website and on both the master and develop branches on github.
http://develop.spacemacs.org/layers/+checkers/spell-checking/README.html#enable-auto-completion-popup
https://github.com/syl20bnr/spacemacs/tree/master/layers/+checkers/spell-checking#enable-auto-completion-popup
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bcheckers/spell-checking#enable-auto-completion-popup

**Comment by JadElClemens** [comment]
Just today I noticed that this is actually not linked to "improper" whitespace (though it does seem more common in that scenario) or even  `evil-delete`. I encountered this issue while yanking (`yy`) and commenting lines (`evil-commentary`) in my .spacemacs.

I'm running the latest version of Emacs on Arch, I'll try updating my .emacs.d to the latest branch and see if the issue still stands.

**Comment by duianto** [comment]
To make sure that we're testing the same thing. This is how I'm testing it:
- open the scratch buffer `SPC b s`
- enable whitespace-mode `SPC t w`
- insert some lorem ipsum text `SPC i l p`
- call `evil-fill-and-move` on the whole buffer (`gqig`), to split the lines at the fill column
- add a space at the end of each line:
  - move the cursor to the first line: `gg`
  - start recording a macro to register `q`, press: `qq`
  - move to the end of the line: `A`
  - insert a: `SPC`
  - exit insert state: `ESC`
  - move to the next line: `j`
  - stop recording the macro: `q`
  - repeat the macro for each line: `F4` or `@q`, it accepts a numeric argument to run the macro several times, ex: `5F4`

The buffer looks something like this. There are a couple of different lorem ipsum lines so it might have different words:
```
Pellentesque dapibus suscipit ligula. Donec posuere augue in quam. Etiam vel 
tortor sodales tellus ultricies commodo. Suspendisse potenti. Aenean in sem ac 
leo mollis blandit. Donec neque quam, dignissim in, mollis nec, sagittis eu, 
wisi. Phasellus lacus. Etiam laoreet quam sed arcu. Phasellus at dui in ligula 
mollis ultricies. Integer placerat tristique nisl. Praesent augue. Fusce 
commodo. Vestibulum convallis, lorem a tempus semper, dui dui euismod elit, 
vitae placerat urna tortor vitae lacus. Nullam libero mauris, consequat quis, 
varius et, dictum id, arcu. Mauris mollis tincidunt felis. Aliquam feugiat 
tellus ut neque. Nulla facilisis, risus a rhoncus fermentum, tellus tellus 
lacinia purus, et dictum nunc justo sit amet elit. 
```

Pressing `dd` on any of the lines only deletes the line for me. Without any errors.

After typing the above I notice the backtrace note about whitespace before the lines. Adding spaces or pressing tab before the lines, with or without trailing whitespace, doesn't show errors either when deleting lines with `dd`.

**Comment by choltz** [comment]
I am encountering this as well. Occasionally I'll get this: `evil-motion-range: Wrong type argument: wholenump, -[integer]` when I type `dd` or `yy`. As @JadElClemens mentioned above, If I move to the right so I'm not at the very beginning of the line, I don't get the error.

If I disable `evil-mode` and re-enable it, things start working properly again.

**Comment by JadElClemens** [comment]
Sorry for the long delay in responding - I sort of ignored this issue since I was able to move the cursor away from the first column in order to work around the error. I did some more testing today and found that the error occurs for me consistently under the following two scenarios:

First off, we need to prepare the buffer.

**Preparing the test buffer**:
- Follow @duianto's reproduction attempt up to and including the `evil-fill-and-move` step. It is not necessary to insert spaces at the end of each line
- Insert a new line containing the text `[SPC][SPC]asdf` - the "test line". [SPC] = a whitespace character (I've tested space and tab).

---- 
**1. Moving the cursor from a whitespace character _not in the first column_ to the first column of another line (in one motion), then deleting/yanking/etc.**

Placing my cursor on the second space, I move up or down any number of lines and try to delete/yank/etc.. The error occurs every time. 

I should note that moving the cursor up or down from the second space in the test line puts my cursor into the first column of the line I move it into. 
- Moving up or down while positioned onto a third space/tab on the test line does not move to the first column and the error does not occur.
- If the second column of the test line does not contain a whitespace character, the cursor does not move to the first column when moving up or down and the error does not occur.
- Moving left or right after I've moved off of the test line results in the error not occurring.

**Reproduction Guide**:
1. Prepare the test buffer
2. Position your cursor on the second whitespace character in the test line
3. Move up or down a line. The cursor should jump to the first column of whichever line you move to.
    - (Optionally) continue moving up/down lines as you please, but do not move left/right. Further vertical motion does not affect reproduction of the bug.
4. Try to delete (`dd`), yank (`yy`), or comment (`gcc`) the line
----
**2. Encountering the error on a line that starts with whitespace and then moving vertically to another line repeats the error.**

If I encounter the error trying to delete/yank/comment the test line, I can move up or down any number of times and the error will always occur the next time I try this action, no matter how many lines I've moved.
- Similarly to example 1, this does not occur if I move left or right at any point after encountering the error on the test line.

**Reproduction Guide**:
1. Prepare the test buffer
2. Position your cursor at the beginning of the test line and try to delete/yank/comment the line.
    - If the action succeeds, undo if necessary to restore the buffer to its previous state, move off and then back onto the test line, and try again until the error occurs.
3. Move the cursor up and/or down any number of lines. Do not move left or right at any point.
4. Try to delete/yank/comment any other line. The same error should occur.
    - The error will keep occurring for any such action if you stay on this line. Once you move away, the actions should succeed on any line (even the second line on which the error occurred - assuming you've moved away and come back to it).

**Comment by JadElClemens** [comment]
I've edited the OP with more accurate and up-to-date information. I also fetched the most recent development commit (as of about 10 minutes ago) and tested there - the issue still exists.

**Comment by duianto** [comment]
I'm not able to reproduce it with your reproduction steps either.
- Moving up or down from the second whitespace on a line always moves the cursor vertically, I haven't seen it jump to the first column.
- With the cursor on whitespace at the beginning of a line.
`dd`, `u`, move up/down or down/up, repeat 10+ times didn't show any errors. 

I even copied your layer configurations, but there was no change.

But since choltz confirmed it, I'll update the labels.

<details><summary>
Pop!_OS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 76245081d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(colors helm
        (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
        (spell-checking :variables enable-flyspell-auto-completion t spell-checking-enable-by-default nil)
        syntax-checking evil-commentary git semantic themes-megapack
        (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t treemacs-space-between-root-nodes nil treemacs-git-mode 'deferred)
        bibtex
        (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
        emacs-lisp
        (latex :variables latex-enable-folding t)
        markdown
        (python :variables python-test-runner 'pytest)
        shell-scripts systemd
        (mu4e :variables mu4e-enable-mode-line t)
        (org :variables org-enable-github-support t)
        multiple-cursors gtags)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 239f60a65)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(colors helm
        (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
        (spell-checking :variables enable-flyspell-auto-completion t spell-checking-enable-by-default nil)
        syntax-checking evil-commentary git semantic themes-megapack
        (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t treemacs-space-between-root-nodes nil treemacs-git-mode 'deferred)
        bibtex
        (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
        emacs-lisp
        (latex :variables latex-enable-folding t)
        markdown
        (python :variables python-test-runner 'pytest)
        shell-scripts systemd
        (mu4e :variables mu4e-enable-mode-line t)
        (org :variables org-enable-github-support t)
        multiple-cursors gtags)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by hisnawi** [comment]
The issue exists for me as well. Any follow up on this?

**Comment by duianto** [comment]
@hisnawi Could you post your system info, press `SPC h d s` to copy it to your clipboard.
And could you include some reproduction steps of what your doing when it happens.

**Comment by hisnawi** [comment]
I don't use spacemacs, can't execute that command you gave.
But I am on Emacs 26.3 and I always see this issue when doing yy (evil) while at the begging of the line. Once it happens Doing yy continuously will keep reproducing it. But I am not sure under what conditions it does happen.

**Comment by hisnawi** [comment]
By the way, "I don't even use spacemacs, just vanilla emacs with customized setup. And couldn't find anything about this issue except here.

**Comment by duianto** [comment]
If it happens without Spacemacs, then it probably should be reported to the evil repository:
https://github.com/emacs-evil/evil

**Comment by JadElClemens** [comment]
> By the way, "I don't even use spacemacs, just vanilla emacs with customized setup. And couldn't find anything about this issue except here.

Interesting. I tried with just evil and whitespace-mode (see OP) and didn't experience this bug. Can you post your config somewhere?

**Comment by hisnawi** [comment]
> Interesting. I tried with just evil and whitespace-mode (see OP) and didn't experience this bug. Can you post your config somewhere?

FWIW:
I found out that these two lines caused my issue.
Once removed, I stopped getting the error.

```
    (define-key evil-normal-state-map (kbd "j") 'evil-next-visual-line)
    (define-key evil-normal-state-map (kbd "k") 'evil-previous-visual-line)

```
Which I don't remember why I had placed them in my config file.
