### ISSUE TITLE
How to disable lazy-load

### ISSUE THREAD

**Issue by junfx** [syl20bnr/spacemacs#12653]
With lazy-load, or auto-load, the first time I run commands such as `SPC f r`, `SPC f f`, `SPC b b` emacs loads things for 2-3 seconds,  for ~10 seconds the first time I open an org file. Emacs bogs, I bog.
So how to preload some packages, or disable lazy-load? I've tried `(require 'helm)` and other things in .spacemacs, it does not work.

OS: windows 10
spacemacs: 0.200.13.x

**Comment by syl20bnr** [comment]
It is not really possible to disable lazy-loading, we have no option to do that. People prefers fast startup :-)

But... when Emacs 27 will be released you will be able to use the portable dumper and get ultra fast startup with no lazy loading for org, helm etc...  Actually you can already test it if you want: https://github.com/syl20bnr/spacemacs/blob/develop/EXPERIMENTAL.org#spacemacs-dumps-using-the-portable-dumper

Note that it requires to use the `develop` branch which has a lot of new stuff and some changed key-bindings, you can find the change notes here: https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop

**Comment by junfx** [comment]
The reason why loading takes so long is LANDESK. Thanks.
