### ISSUE TITLE
Setting theme for spacemacs from bash

### ISSUE THREAD

**Issue by Migacz85** [syl20bnr/spacemacs#12660]
Hi guys

I can set theme by hitting space T n. However I want to do it more programmatically
it is possible to set espacemacs theme externally from bash ? 

Thanks

**Comment by duianto** [comment]
If you mean that you would like to change the startup theme, then you can add the theme name as the first item in the `dotspacemacs-themes` list in your `.spacemacs`.
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#color-themes

I'm don't know if it's possible to load a theme from the command prompt on startup, Spacemacs might still load the first listed theme in `dotspacemacs-themes`.
