### ISSUE TITLE
Change web page to install develop instead of master

### ISSUE THREAD

**Issue by NatHarari** [syl20bnr/spacemacs#12672]
Hey guys, maybe this is not such a major deal, but a lot of newbies do land on the front page and start with Master which, as everyone knows, people in the chat tell them to get off of and install Develop right away (for all the right reasons). Could you guys please just change the link on the front of the web site to switch it to install the Develop branch instead of the Master? It would only take 10 seconds to do I'm sure.

Thanks.

P.S. Somebody has to look out for all the new people. :)

**Comment by syl20bnr** [comment]
Thank you for the idea. I tag this as bug.
We should also update the README of the master branch to tell people to install the develop branch until the next stable is ready (which will includes support for spacelpa ELPA repository and fix lots of stability issues for master branch users).

**Comment by yyoncho** [comment]
@syl20bnr you may change the default branch for the repository from Settings -> Branches.

**Comment by bimawa** [comment]
Damn, 5 years I live in master :-/
