### ISSUE TITLE
helm-adaptive-mode breaks startup

### ISSUE THREAD

**Issue by seschwar** [syl20bnr/spacemacs#1267]
Enabling and saving `helm-adaptive-mode` via customize breaks the startup of Emacs.

    Warning (initialization): An error occurred while loading `/home/seschwar/.emacs.d/init.el':
    
    File error: Cannot open load file, no such file or directory, helm-adaptive
    
    To ensure normal operation, you should investigate and remove the
    cause of the error in your initialization file.  Start Emacs with
    the `--debug-init' option to view a complete error backtrace.

`helm-adaptive.el` end `.elc` exist and in `lisp-interaction-mode` i can successfully `(require 'helm-adaptive)` and then use it.

**Comment by sgraf812** [comment]
I'm not entirely sure if this is related, but I always hit this on Windows when I apply the latest updates (last version was from ~1 month):

```
Warning (initialization): An error occurred while loading `c:/Users/Sebastian/AppData/Roaming/.emacs.d/init.el':

error: use-package: Unrecognized keyword: :idle

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

**Comment by syl20bnr** [comment]
@sgraf812 This is an unrelated issue, you have a layer using `:idle` which is deprecated in `use-package` 2.0

@seschwar I don't know about `helm-adaptive` what is it ? One possible solution could be that helm is missing an auto-load for it.

**Comment by tuhdo** [comment]
@seschwar according to Helm maintainer, you should not use `helm-adaptive` directly. It is used for internal Helm.

**Comment by seschwar** [comment]
`helm-adaptive` should sort the candidates according to recent usage frequency.

If it's an internal thing then why is it exposed via customize? There's no problem when enabling it in Emacs without spacemacs.

**Comment by tuhdo** [comment]
You can enable via `helm-mode-hook`. But according to this issue: https://github.com/emacs-helm/helm/issues/751 and [this discussion](https://groups.google.com/forum/#!topic/emacs-helm/S6FXhGfDFqA), it is not used outside of some specific Helm commands. In this issue, Thierry said that only commands that support adaptive sort are affected by this mode: https://github.com/emacs-helm/helm/issues/485

**Comment by seschwar** [comment]
To clarify: I'm not calling `helm-adpative` interactively like say `helm-M-x`. When I enable it via customize it should affect the other helm commands that support it. My point is that when enabling it can't be loaded in spacemacs while it loads just fine in regular Emacs.

**Comment by TheBB** [comment]
You probably have to enable it after helm loads.

```lisp
(with-eval-after-load 'helm
  (helm-adaptive))
```

Or something along those lines. Closing this now since it seems old and unsupported.
