### ISSUE TITLE
FR: Python layer should support nose2 as testrunner

### ISSUE THREAD

**Issue by znewman01** [syl20bnr/spacemacs#12675]
First, thanks a bunch to the Spacemacs developers for a great piece of software!

It looks like [`nose`](https://github.com/nose-devs/nose) is [abandoned-*ish*](https://github.com/nose-devs/nose/issues/1092). It has a successor, [nose2](https://nose2.io/).

I have nose2 working-ish with the Python layer (I only use some of the functionality, and haven't done all of the variations of tests you can run [1]. I basically just copied `nose.el`, did `s/nosetests/nose2/`, fixed up some flag names, and plumbed in `'nose2` to all the defuns in `funcs.el`.

It'd be relatively easy (famous last words, I know) to flesh out what I have and contribute upstream. Would you be interested in a PR?

Longer-term, I think we'd want to refactor to make adding test-runners easier (there's a lot of different places to modify, and a lot of assumptions that there are only 2 test runners). I may or may not be interested in doing that.

**[1]**: That is:

- `'spacemacs/python-test-all`
- `'spacemacs/python-test-module`
- `'spacemacs/python-test-one`
- `'spacemacs/python-test-pdb-all`
- `'spacemacs/python-test-pdb-module`
- `'spacemacs/python-test-pdb-one`
- `'spacemacs/python-test-pdb-suite`
- `'spacemacs/python-test-suite`

**Comment by cvchaparro** [comment]
This is still a relevant issue and I'd be willing to help with some of these updates.
