### ISSUE TITLE
Cursor jumps around on first two lines in suckless st.

### ISSUE THREAD

**Issue by comalice** [syl20bnr/spacemacs#12681]
#### Description :octocat:

![spacemacs-jumping-cursor-first-two-lines](https://user-images.githubusercontent.com/52582426/64068783-872cd380-cc2c-11e9-8723-9b70951eeb32.gif)

#### Reproduction guide :beetle:d

- install suckless st
- install emacs
- install spacemacs
- open a file with more than three lines in emacs

*Observed behaviour:* :eyes: :broken_heart:

move the cursor across the first and second lines, observe jumping around. The same happens with the second line.

*Expected behaviour:* :heart: :smile:

I expect the cursor to move linearly across the line when I type or navigate.

#### System Info :computer:
- OS: gnu/linux
- Terminal Emulator: st 0.8.2
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

```
elisp
nil
```

- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```

```

#### Things I've Tried

:NOTE: If we're running emacs as a server, we'll need to kill it to force reload the configuration.

- Tried with VIM and the behaviour is absent.
- Tried with bare emacs (no config) and the behaviour is absent.

This leads me to believe the problem is somewhere in the =spacemacs= configuration files.

- Commented out user specific configuration. Behaviour is still present.
- Commented out all configuration layers. Behaviour is still present.
- Started `tmux`, started `emacsclient -nw`. Behaviour is absent.
- Installed `termite`, started `termite` started `emacsclient -nw`. Behaviour is absent.

**Comment by colbell** [comment]
I'm not seeing this. I'm using a recent version of Emacs 27 and the develop branch of spacemacs. 

I've had some issues in the past with the master branch of spacemacs. You could try the develop branch and see if that fixes it.

What key are you using to move around - it works for me with both the right arrow and l keys

**Comment by comalice** [comment]
I'm using the arrow keys to navigate in the above example.

I'll do a fresh installation of everything and see if that works.
