### ISSUE TITLE
Flycheck displays all erros on first line.

### ISSUE THREAD

**Issue by pedrobellini** [syl20bnr/spacemacs#12696]
#### Description :octocat:
All the errors get listed on a single bullet on the first line of the file.

#### Reproduction guide :beetle:
- Start Emacs
- Make a test lisp file (test.el)
- Turn on syntax-checking (SPC t s)
- Paste the lines below:
```lisp
(setq test "foo")
(+ 3 (23 ))
-- = bar

_)(*!@Fc)
(arxs foo)
```
- Also open the flycheck list buffer (flycheck-error-list <SPC e l>)

*Observed behaviour:* :eyes: :broken_heart:
- Line 1 takes the error mark:
In "flycheck_test.el": Invalid read syntax: ")"
- flycheck list shows correctly it should be at line 5
![flycheck_issue](https://user-images.githubusercontent.com/2975966/64282983-635add80-cf0b-11e9-9fd0-24ba61f69f18.png)

*Expected behaviour:* :heart: :smile:
- Flycheck error mark on correct lines.
![flycheck_issue_notInVanilla](https://user-images.githubusercontent.com/2975966/64282991-6950be80-cf0b-11e9-9d07-046a01b7d4a1.png)

*Extra info:*
I have talked with flycheck devs and perform the tests to narrow to Spacemacs, here:
https://github.com/flycheck/flycheck/issues/1618
You can see on a raw emacs flycheck works and has more information about the errors.

Cheers!

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: pb_dev (rev. 1299f262c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(windows-scripts html helm auto-completion emacs-lisp git multiple-cursors neotree python org spacemacs-org
                 (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
                 (shell :variables shell-default-height 30 shell-default-position 'top)
                 syntax-checking cmake gpu)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by pedrobellini** [comment]
## extra info: 
Im using this version of emacs
https://github.com/zklhp/emacs-w64/releases/tag/e0284ab

**Comment by pedrobellini** [comment]
## Update
It does work in c++ mode as expected (still not in python nor lisp)

![flycheck_issue_notInCpp](https://user-images.githubusercontent.com/2975966/67404438-41272880-f568-11e9-8186-241c7a49d402.png)

**Comment by duianto** [comment]
Can you test if it's related to the Emacs version, the latest official version is 26.3.
https://www.gnu.org/software/emacs/download.html

**Comment by pedrobellini** [comment]
Yes! it works, I don't know if was just about updating to 26.3 or something else as well in develop. 
But thanks for fixing!

**Comment by SirSharpest** [comment]
I have this issue, using spacemacs, emacs 28. Was a solution ever found?

**Comment by SirSharpest** [comment]
Just to update, I've tried on several different builds of emacs - this worked for me before moving to spacemacs

**Comment by SirSharpest** [comment]
Very odd issue - default spacemacs setup on OSX. Way to fix is:
`(setq-default flycheck-disabled-checkers '(python-flake8))`
Tested on both macbook and imac, not sure why though?

**Comment by duianto** [comment]
My two tests seems to be working as expected:

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d4a27babf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm javascript markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 python
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>

![flycheck-issue-12696-popos](https://user-images.githubusercontent.com/13420573/72217789-38c10700-3533-11ea-9841-116713c42a13.png)


<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d4a27babf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-use-company-box t)
 command-log emacs-lisp git helm html imenu-list
 (javascript :variables javascript-backend 'lsp)
 markdown multiple-cursors
 (nixos :variables nixos-enable-company t)
 notmuch
 (org :variables org-agenda-files
      '("c:/Users/username/org/notes.org"))
 python
 (shell :variables shell-default-shell 'eshell)
 spell-checking syntax-checking treemacs version-control
 (xclipboard :variables))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

![flycheck-issue-12696-win10](https://user-images.githubusercontent.com/13420573/72217710-475aee80-3532-11ea-864f-1c309dedfd15.png)
