### ISSUE TITLE
`eglot` vs `lsp-mode`

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#12694]
`lsp-mode` integration works quite well, any opinions about `eglot` as an alternative?

**Comment by thanhvg** [comment]
Yeah I think it's important to have an alternative to lsp-mode. I tried eglot months ago but the experience wasn't as smooth as lsp-mode. I would love to know news from both packages.

**Comment by gdkrmr** [comment]
Here is an opinion from someone that prefers `eglot`:
https://discourse.julialang.org/t/using-languageserver-jl-with-eglot-in-emacs/23125/8

**Comment by sdwolfz** [comment]
Kind of late for me to reply to this one 😸... but as you said @gdkrmr in that forum post... it's just a matter of somebody submitting a contribution.

**Comment by NightMachinary** [comment]
It seems to me that eglot is easier to start than lsp-mode.

**Comment by thanhvg** [comment]
@NightMachinary do you know how to make `eglot` work with `flycheck`? I've been searching everywhere and the answer I got is always use `flymake`.

**Comment by NightMachinary** [comment]
Idk.
