### ISSUE TITLE
Parinfer layer is documented but not in master

### ISSUE THREAD

**Issue by togakangaroo** [syl20bnr/spacemacs#12690]
So I found this confusing and blew some time on it.

I'm on the master branch of spacemacs and wanted to use parinfer. According to [this issue](https://github.com/syl20bnr/spacemacs/issues/5574) a parinfer layer seems to be in develop. However a [parinfer layer is documented](http://develop.spacemacs.org/layers/+misc/parinfer/README.html) with no indication that it might not be installable yet.

Should the docs get removed or maybe just caveated?

**Comment by yyoncho** [comment]
I think that you confusion comes from the fact that you are missing that the documentation is for *develop* branch. So it is installable in *develop* and documented only in *develop*.
