### ISSUE TITLE
[develop] go fmt is not executed before save

### ISSUE THREAD

**Issue by Asalle** [syl20bnr/spacemacs#12709]
#### Description :octocat:
go fmt is not executed before save in develop. `(go :variables go-format-before-save t)` is set in `user-config`, but when checking if the variable is actually set with `SPC h d v` it's set as `nil`. Tried reloading with ` f e R` and re-opening the emacs.

On `master` everything works as expected.

#### Reproduction guide :beetle:
- Start Emacs
- add `go` to layers
- open .go file
- type something that formatter would fix

*Observed behaviour:* :eyes: :broken_heart:
- hit `:w` -> buffer is not formatted
- hit `,=` -> buffer is formatted

*Expected behaviour:* :heart: :smile:
Buffer is formatted before save automatically.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 00e870815)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown go helm auto-completion git org c-c++
          (shell :variales shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term)
          better-defaults syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2

#### Backtrace :paw_prints:

**Comment by duianto** [comment]
`(go :variables go-format-before-save t)` should be added to the variable
`dotspacemacs-configuration-layers`, near the top of `.spacemacs`, where you currently only have an entry for the `go` layer. Replace `go` with `(go :variables go-format-before-save t)`

**Comment by Asalle** [comment]
Thank you for the solution, it works now. Then, can we make the `go-format-before-save` set to `t` per default on develop? Or how can I make your solution more obvious for the newbies like me (can I add it to the docs somewhere)?

**Comment by duianto** [comment]
Formatting on save was was disabled in this PR:
Go: Add toggle to disable gofmt before save #11082

There's probably some discussions pro/con it's default value there.

Feel free to open a PR with a suggestion for how the documentation can be improved.
