### ISSUE TITLE
How to disable evil-escape?

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#1270]
Is there a way to disable evil-escape?  I've tried putting `(evil-escape-mode -1)` in `dotspacemacs/config`, but this results in a whole slew of errors: almost every single command raises an error "Value of first-key as variable is void" the first time a command is called, and it completely borks org-agenda-mode and probably other modes as well.

I'm not sure if this is a bug in `evil-escape-mode` or spacemacs's custom configuration.

**Comment by person808** [comment]
Have you tried adding `evil-escape` to `dotspacemacs-excluded-packages`?

**Comment by darkfeline** [comment]
Nope, I forgot that variable existed.  Excluding `evil-escape` works.
