### ISSUE TITLE
Ansible doc is outdated

### ISSUE THREAD

**Issue by abitrolly** [syl20bnr/spacemacs#12718]
The documentation at http://spacemacs.org/layers/+tools/ansible/README.html doesn't match [master](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Btools/ansible/README.org) or [develop](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Btools/ansible/README.org) version of Ansible. How to update it?

**Comment by Asalle** [comment]
Hey there, just create a pull request to the develop branch of this repo. The file that you need to change is `https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btools/ansible`.

**Comment by abitrolly** [comment]
@Asalle the contents of http://spacemacs.org/layers/+tools/ansible/README.html and the file you linked are already different.

**Comment by Asalle** [comment]
That is true, I just noticed that you already linked the file I mentioned in your first comment, sorry about that :)

**Comment by Asalle** [comment]
> the current versions so they won't be removed.
understood
> the author has been busy
so maybe let's make it automatic so the author would not need to do this by hand?

**Comment by duianto** [comment]
I was informed that it is automated, but the master branch and the docs are just really old.

The suggestion is to use the develop branch docs for now.

The author mentioned in this thread, that the release is getting closer:
https://github.com/syl20bnr/spacemacs/issues/12672#issuecomment-530870060

**Comment by Asalle** [comment]
Ah, interesting. I thought in this case master of GitHub and spacemacs.org
should match (which is not the case, huh?)

**Comment by duianto** [comment]
I got a correction. The automation hasn't been implemented yet, but it will be tested with the next release.

**Comment by Asalle** [comment]
Thanks for the update! All clear now.

**Comment by syl20bnr** [comment]
Sorry for the inconvenience, indeed only the develop branch is kept up to date.
