### ISSUE TITLE
Minor graphics issue

### ISSUE THREAD

**Issue by JuneWhitmore** [syl20bnr/spacemacs#12719]
Hi, I'm seeing some minor artifacts with Spacemacs. I've not been able to find anything related.
![spacemacsglitch](https://user-images.githubusercontent.com/47912080/64670913-3c922f00-d456-11e9-8b91-59c750510c5f.png)

**Comment by duianto** [comment]
It's mentioned in the documentation here:
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#font

Or here if your on the `develop` branch:
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#separator-scale

It seems like one can fix it by changing the `dotspacemacs-default-font` scale value in `.spacemacs`.

**Comment by JuneWhitmore** [comment]
I changed powerline-scale to 1.2 and the glitch disappeared. Thank you so much!
