### ISSUE TITLE
Latex preview doesn't work on spacemacs fresh install on Ubuntu 18.04

### ISSUE THREAD

**Issue by Rareform** [syl20bnr/spacemacs#12728]
**Description**

I installed spacemacs on Ubuntu, as well as latex via texlive-full package. Spacemacs does compile latex files. But unfortunately the preview feature doesn't work (red stop signs are everywhere instead of latex formated preview). I tried removing and adding latex into configuration layer without a success.
In the beginning I get asked, whenever the preamble should be cached, which is already strange (in my working windows version of spacemacs it just executes the preview command) and no matter if I choose yes or no I don't get a preview. One mistake which pops up which might give you a hint is "LaTeX: LaTeX found no preview images".

**System info**

OS: ubuntu 18.04
Emacs: 26.3
Spacemacs: 0.200.13
Spacemacs branch: master
Graphic display: t
Distribution: spacemacs
Editing style: vim
Layers: latex

**Backtrace**

Package etex Warning: Extended allocation already in use.
(etex)                etex.sty code will not be used.
(etex)                To force etex package to load, add
(etex)                \RequirePackage{etex}
(etex)                at the start of the document.

)) (/usr/share/texlive/texmf-dist/tex/latex/tkz-berge/tkz-arith.sty (/usr/share/texlive/texmf-dist/tex/latex/tkz-base/tkz-tools-arith.tex))) (/usr/share/texlive/texmf-dist/tex/generic/pgfplots/libs/tikzlibrarypgfplots.polar.code.tex)
No file _region_.aux.
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1ptm.fd) (/home/**/.emacs.d/elpa/auctex-12.1.2/latex/preview.sty (/usr/share/texlive/texmf-dist/tex/generic/luatex85/luatex85.sty) (/home/**/.emacs.d/elpa/auctex-12.1.2/latex/prtightpage.def) (/home/**/.emacs.d/elpa/auctex-12.1.2/latex/prauctex.def
No auxiliary output files.

(/home/**/.emacs.d/elpa/auctex-12.1.2/latex/prauctex.cfg)) (/home/**/.emacs.d/elpa/auctex-12.1.2/latex/prfootnotes.def)
Preview: Fontsize 10pt
Preview: PDFoutput 1
) (/usr/share/texlive/texmf-dist/tex/latex/microtype/mt-ptm.cfg) (/usr/share/texlive/texmf-dist/tex/context/base/mkii/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grfext.sty) (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg)) (/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.dfu) (/usr/share/texlive/texmf-dist/tex/latex/translator/translator-basic-dictionary-English.dict) (/usr/share/texlive/texmf-dist/tex/latex/siunitx/siunitx-abbreviations.cfg) ABD: EveryShipout initializing macros
Package pgfplots notification 'compat/show suggested version=true': you might benefit from \pgfplotsset{compat=1.15} (current compat level: 1.14).

(/usr/share/texlive/texmf-dist/tex/latex/microtype/mt-cmr.cfg) (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsa.fd) (/usr/share/texlive/texmf-dist/tex/latex/microtype/mt-msa.cfg) (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsb.fd) (/usr/share/texlive/texmf-dist/tex/latex/microtype/mt-msb.cfg) (/usr/share/texlive/texmf-dist/tex/latex/base/ulasy.fd)  !name(main.tex) !offset(160)   !name(main.tex) !offset(164)  )
(see the transcript file for additional information)
No pages of output.
Transcript written on _region_.log.

TeX Output exited as expected with code 1 at Fri Sep 13 20:17:37
LaTeX: LaTeX found no preview images

**Comment by someonedomath** [comment]
I had a similar issue under the following system:

OS: macOS Mojave 10.14.6
Emacs: 26.3
Spacemacs: 0.300.0
Spacemacs branch: develop
Editing style: vim
Layers: latex
Themes: spacemacs-light

Thanks to #12654, I solved this by changing the theme from 'spacemacs-light' to 'whiteboard'.
Maybe something is wrong with the spacemacs-light theme?

**Comment by Rareform** [comment]
Thank you a lot for the tip! This does indeed solve the problem with the preview. Strangely in windows spacemacs-light theme works. Interestingly enough TeX-PDF-mode  C-c C-t C-p lets me see some notation, but not the things inside equation or align environments. Will there be any fix to the themes compatability with the latex preview?

**Comment by duianto** [comment]
The Spacemacs themes are handled by this repository:
https://github.com/nashamri/spacemacs-theme

It might not have support for latex previews yet.

Posting some reproduction steps with screenshots will probably be helpful for finding a fix.

**Comment by tshu-w** [comment]
@Rareform @zhenyao-sun add this code in my config fix this issue
```emacs-lisp
(custom-set-faces
 '(preview-reference-face ((t (:foreground "black")))))
```
