### ISSUE TITLE
opening svg crashing emacs

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#12727]
#### Description :octocat:

opening an svg file crashes emacs

#### Reproduction guide :beetle:
- Start Emacs
- open an svg file

*Observed behaviour:* :eyes: :broken_heart:
emacs simply crashes

*Expected behaviour:* :heart: :smile:
opening the svg file

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ae51fd7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-rtags-support t c-c++-enable-clang-support t)
      cscope chrome csv docker javascript ranger emacs-lisp
      (ess :variables ess-style 'RStudio ess-use-flymake nil ess-assign-key "\255")
      (julia :variables lsp-julia-command "julia-1.2" lsp-julia-default-environment "/home/gkraemer/.julia/environments/v1.1" julia-mode-enable-lsp t julia-mode-enable-ess nil)
      git github graphviz html
      (latex :variables TeX-view-program-selection
             '((output-pdf "PDF Tools"))
             TeX-view-program-list
             '(("PDF Tools" TeX-pdf-tools-sync-view))
             TeX-source-correlate-start-server t preview-scale-function 1.5)
      bibtex
      (lsp :variables lsp-prefer-flymake nil)
      markdown multiple-cursors
      (mu4e :variables mu4e-installation-path "~/progs/misc/mu/mu4e/" mu4e-get-mail-command "offlineimap" mu4e-enable-mode-line t mu4e-use-maildirs-extension t mu4e-spacemacs-layout-name "@Mu4e" mu4e-spacemacs-layout-binding "m")
      octave
      (org :variables org-bullets-bullet-list
           '("⣿" "⣾" "⣽" "⣼" "⣻" "⣺" "⣹" "⣸" "⣷" "⣶" "⣵" "⣴" "⣳" "⣲" "⣱" "⣰" "⣯" "⣮" "⣭" "⣬" "⣫" "⣪" "⣩" "⣨" "⣧" "⣦" "⣥" "⣤" "⣣" "⣢" "⣡" "⣠" "⣟" "⣞" "⣝" "⣜" "⣛" "⣚" "⣙" "⣘" "⣗" "⣖" "⣕" "⣔" "⣓" "⣒" "⣑" "⣐" "⣏" "⣎" "⣍" "⣌" "⣋" "⣊" "⣉" "⣈" "⣇" "⣆" "⣅" "⣄" "⣃" "⣂" "⣁" "⣀" "⢿" "⢾" "⢽" "⢼" "⢻" "⢺" "⢹" "⢸" "⢷" "⢶" "⢵" "⢴" "⢳" "⢲" "⢱" "⢰" "⢯" "⢮" "⢭" "⢬" "⢫" "⢪" "⢩" "⢨" "⢧" "⢦" "⢥" "⢤" "⢣" "⢢" "⢡" "⢠" "⢟" "⢞" "⢝" "⢜" "⢛" "⢚" "⢙" "⢘" "⢗" "⢖" "⢕" "⢔" "⢓" "⢒" "⢑" "⢐" "⢏" "⢎" "⢍" "⢌" "⢋" "⢊" "⢉" "⢈" "⢇" "⢆" "⢅" "⢄" "⢃" "⢂" "⢁" "⢀" "⡿" "⡾" "⡽" "⡼" "⡻" "⡺" "⡹" "⡸" "⡷" "⡶" "⡵" "⡴" "⡳" "⡲" "⡱" "⡰" "⡯" "⡮" "⡭" "⡬" "⡫" "⡪" "⡩" "⡨" "⡧" "⡦" "⡥" "⡤" "⡣" "⡢" "⡡" "⡠" "⡟" "⡞" "⡝" "⡜" "⡛" "⡚" "⡙" "⡘" "⡗" "⡖" "⡕" "⡔" "⡓" "⡒" "⡑" "⡐" "⡏" "⡎" "⡍" "⡌" "⡋" "⡊" "⡉" "⡈" "⡇" "⡆" "⡅" "⡄" "⡃" "⡂" "⡁" "⡀" "⠿" "⠾" "⠽" "⠼" "⠻" "⠺" "⠹" "⠸" "⠷" "⠶" "⠵" "⠴" "⠳" "⠲" "⠱" "⠰" "⠯" "⠮" "⠭" "⠬" "⠫" "⠪" "⠩" "⠨" "⠧" "⠦" "⠥" "⠤" "⠣" "⠢" "⠡" "⠠" "⠟" "⠞" "⠝" "⠜" "⠛" "⠚" "⠙" "⠘" "⠗" "⠖" "⠕" "⠔" "⠓" "⠒" "⠑" "⠐" "⠏" "⠎" "⠍" "⠌" "⠋" "⠊" "⠉" "⠈" "⠇" "⠆" "⠅" "⠄" "⠃" "⠂" "⠁")
           org-latex-listings 'minted org-latex-pdf-process
           (list "latexmk -shell-escape -bibtex -f -pdf %f")
           org-format-latex-options
           '(:foreground default :background default :scale 1.5 :html-foreground "Black" :html-background "Transparent" :html-scale 1.0 :matchers
                         ("begin" "$1" "$" "$$" "\\(" "\\[")))
      pdf python rust
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      shell-scripts spell-checking syntax-checking treemacs themes-megapack
      (typescript :variables typescript-fmt-on-save t typescript-fmt-tool 'tyescript-formatter typescript-backend 'tide)
      version-control vimscript yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LCMS2

#### Backtrace :paw_prints:
emacs crashes without any backtrace

**Comment by duianto** [comment]
Does Emacs crash for you without Spacemacs?
Try starting without loading any configurations: `emacs -q`

For me Spacemacs doesn't crash, when I open `.emacs.d/assets/spacemacs.svg`

#### System info
<details><summary>
Ubuntu 18.04.3
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f97c0ae6c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm markdown multiple-cursors org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f97c0ae6c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git helm html multiple-cursors org python ranger
            (shell :variables eshell-completion-frame nil shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by gdkrmr** [comment]
I tried with `spacemacs` on another machine and svg-files are opened just fine in `nXML-mode`, an error is shown in the `*Messages*` buffer:
```
Cannot display image: (Invalid image type ‘svg’)
```

**Comment by duianto** [comment]
The Ubuntu 18.04.3 test was done in a VirtualBox VM guest (with Wwindows 1903 as host) by first installing:
`sudo apt install librsvg2-dev`
and compiling Emacs 26.3.

Another difference other than the OS version, might be that I also added modules support:
`./configure --with-modules`
It's needed for libvterm, there's a PR in the works: 
Add support for libvterm #11552

**Comment by gdkrmr** [comment]
If I remember correctly I just did plain
```
./autogen.sh
./configure
make
```
for compilation, I am also using Ubuntu 16.04. I filed a bug report with the emacs developers, haven't heard back yet.
