### ISSUE TITLE
tags are hidden by bottom bar of window

### ISSUE THREAD

**Issue by lovebug356** [syl20bnr/spacemacs#12723]
#### Description :octocat:
bottom line of window overlaps with tags in =org-set-tags-command=. (see screenshot)

#### Reproduction guide :beetle:
- Start Emacs
- open an org file with predefined tags
- for example starting with
  #+TAGS: @work(w) @home(h)
- run the command =org-set-tags-command=

*Observed behaviour:* :eyes: :broken_heart:
- the proposed tags are not visible (see screenshot), I expect to be able to read clearly @work and @home, ...
![Screen Shot 2019-09-12 at 15 52 49](https://user-images.githubusercontent.com/51261/64790677-c1746a00-d576-11e9-8def-17736357e9b7.png)

*Expected behaviour:* :heart: :smile:
- the proposed tags should be clearly visible

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a326913a9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 better-defaults emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 git helm dap
 (lsp :variables lsp-ui-doc-enable nil)
 (mu4e :variables mu4e-enable-notifications t mu4e-enable-mode-line t mu4e-enable-async-operations t)
 mu4e multiple-cursors themes-megapack
 (org :variables org-projectile-file "todo.org" org-enable-github-support t org-enable-bootstrap-support t org-enable-org-journal-support t org-enable-jira-support t jiralib-url "https://itrack.barco.com" org-want-todo-bindings t org-enable-reveal-js-support t)
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking treemacs version-control javascript html markdown
 (python :variables python-backend 'lsp python-test-runner 'pytest python-fill-column 120 python-sort-imports-on-save t python-format-on-save t)
 (rust :variables rust-format-on-save t rust-backend 'lsp)
 yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by zhigang26** [comment]
@lovebug356  
I have a temporary solution :
1. =SPC f t= : show file tree
2.  run the command =org-set-tags-command=
3. you will see the tag command windows back to normal

**Comment by duianto** [comment]
I don't have a mac to test with, but they are visible for me in both:

### Linux

![2020-06-14_15-56-58](https://user-images.githubusercontent.com/13420573/84595448-36ebce80-ae58-11ea-9c07-596a11da992c.png)

<details><summary>
PopOS 20.04 (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5fcd84d84)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp fasd git helm lsp markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 ranger
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking themes-megapack treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

### Windows

![emacs_2020-06-14_15-56-24](https://user-images.githubusercontent.com/13420573/84595449-3c491900-ae58-11ea-9fcb-f67566de476e.png)

<details><summary>
Windows 1903 (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5fcd84d84)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 emacs-lisp git helm html javascript lsp
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org" "~/temp/org-tags-view_broken._13509.org"))
 (python :variables)
 ranger
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>
