### ISSUE TITLE
Python mode is ignoring .dir-locals.el 

### ISSUE THREAD

**Issue by twillis** [syl20bnr/spacemacs#12735]
#### Description :octocat:
Python mode is ignoring .dir-locals.el and falling back on default testrunner nose which is not what I want.

#### Reproduction guide :beetle:
- Start Emacs
- create a .dir-locals.el per instructions in the python layer docs

```elisp
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((python-mode
  (python-test-runner . pytest)))

```
- have pytest installed and not nose
- open a unit test file

```python

def test_python():
  print('yay') # python 3

```

- `, t b` 
*Observed behaviour:* :eyes: :broken_heart:
```bash
/home/tom/projects/navigator8_env/.venv/bin/python -u -c "import nose; nose.main()"    -s -w "/home/tom/projects/navigator8_env/navigator/" -c "/home/tom/projects/navigator8_env/navigator/setup.cfg" "/home/tom/projects/navigator8_env/navigator/tests/test_survey_definition.py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'nose'

Compilation exited abnormally with code 1 at Tue Sep 17 09:42:43
```

*Expected behaviour:* :heart: :smile:
should run pytest as configured

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f42b2db56)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible typescript rust windows-scripts docker nginx scheme helm csv sql auto-completion clojure common-lisp
         (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'rbenv ruby-backend 'lsp)
         python
         (javascript :variables javascript-backend 'lsp)
         emacs-lisp markdown
         (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t org-enable-bootstrap-support t)
         nim syntax-checking version-control git osx shell ibuffer yaml html colors erc react pandoc
         (lsp :variables lsp-enable-snippet nil)
         dap)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by twillis** [comment]
update: .dir-locals.el functionality seems to work fine for other modes

```elisp
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((markdown-mode
  (markdown-foo . 1))
 (python-mode
  (python-foo . 123)))
```

so something definitely fishy with the python layer. if I turn off the layer and open a python file then .dir-locals.el is read as it should.

**Comment by twillis** [comment]
update 2: so it seems the only way to get it to work is by configuring the python layer like so...

```elisp
       (python :variables
               python-backend 'lsp)

```

anaconda backend used to work without having to install anaconda stuff but that seems to have changed recently...bummer bc lsp is kind of heavy and noisy.

**Comment by Compro-Prasad** [comment]
You can disable lsp-ui stuff to make it far less noisy.

**Comment by twillis** [comment]
@Compro-Prasad not in my experience https://github.com/syl20bnr/spacemacs/issues/13183

**Comment by lebensterben** [comment]
Should be fixed now.
