### ISSUE TITLE
spacemacs stopped working on Fedora 31 Silverblue beta

### ISSUE THREAD

**Issue by Zlopez** [syl20bnr/spacemacs#12737]
#### Description :octocat:
I recently updated to Fedora 31 Silverblue, which is currently in beta. After update spacemacs stopped working.

I tried to delete content of `.emacs.d` and pull the content again, but this didn't help.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Standard emacs started

*Expected behaviour:* :heart: :smile:
spacemacs started

OS: Fedora 31 Silverblue
Emacs version: GNU Emacs 26.2
Spacemacs develop commit: https://github.com/syl20bnr/spacemacs/commit/5894c396cb12e5b38d2786bee224487b7ac15361

**Comment by duianto** [comment]
If you have a `.emacs` file in your home directory then it takes precedence over `.spacemacs`.

**Comment by Zlopez** [comment]
Thanks, this solved the issue. I don't know why `.emacs` was created, I didn't create it as far as I remember.
