### ISSUE TITLE
Unable to get the python layer working

### ISSUE THREAD

**Issue by tamasgal** [syl20bnr/spacemacs#12733]
I just started to play around with spacemacs and installed the latest Emacs version for ArchLinux and the full spacemacs distribution. I activated the python layer and all the packages were automatically installed. However, it does not seem to work at all: no auto-completion, no suggestions, no docstrings etc.

The following error was thrown during compilation of the packages:

```

Compiling file /home/tgal/.emacs.d/elpa/anaconda-mode-20190917.321/anaconda-mode.el at Tue Sep 17 12:14:06 2019
Entering directory ‘/home/tgal/.emacs.d/elpa/anaconda-mode-20190917.321/’
anaconda-mode.el:39:1:Error: Cannot open load file: No such file or directory, posframe

Compiling no file at Tue Sep 17 12:14:07 2019
Leaving directory ‘/home/tgal/.emacs.d/elpa/cython-mode-20190111.2150’
```

How do I debug this? I read that there is an `*anaconda-buffer*` or something similar but `M-x switch-to-buffer` does not show such a buffer, so I cannot see any other error message.

Btw. I am using `pyenv` under the hood with Python 3.7.4.

Edit: I also tried to manually install `posframe` with `M-x package-install RET posframe` but the Python layer still does not seem to work

**Comment by tamasgal** [comment]
I just tried the latest `develop` branch but it seems that it's the same problem with `anaconda-mode`. This is what I get when I open a Python file:

```
File mode specification error: (file-missing Cannot open load file No such file or directory posframe)
```

**Comment by bet4it** [comment]
`anaconda-mode` is [not maintained by its author](https://twitter.com/proofit404/status/1171919301789593601) now.
Try to use  `(python :variables python-backend 'lsp)`.

**Comment by Compro-Prasad** [comment]
Also, enable the respective layers for having auto completion and syntax checking.
