### ISSUE TITLE
RET doesn't show the current commit when blaming a .org file

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#12747]
#### Description :octocat:
`RET` doesn't open the current commit (`magit-show-commit`) when blaming `SPC g b` a `.org` file.
Instead `RET` calls: `org-open-at-point`.

#### Reproduction guide :beetle:
- `SPC f f`
- choose an org file, for example in the Spacemacs repository:  `/.emacs.d/community.org`
- `SPC g b`
- `SPC h d k RET` shows:
>RET (translated from <return>) runs the command org-open-at-point, which is an
interactive compiled Lisp function in ‘org.el’.

It works as expected in non org files, for example:
- `SPC f f` `/.emacs.d/.gitignore`
- `SPC g b`
- `SPC h d k RET` shows:
>RET (translated from <return>) runs the command magit-show-commit (found in
magit-blame-read-only-mode-map), which is an interactive autoloaded compiled
Lisp function in ‘magit-diff.el’.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1fae31b56)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by smile13241324** [comment]
@duianto I have merged the fix from compro-pasad, can you double check and close this issue when it is gone? In my small local test blaming works now in org buffers too.

**Comment by duianto** [comment]
Confirmed it works now. Thanks @Compro-Prasad
