### ISSUE TITLE
Line Numbers, no Line wrapping questions

### ISSUE THREAD

**Issue by beardedprojamz** [syl20bnr/spacemacs#1274]
Hey everyone,

Love this project - great work! If I want to have line numbers defaulted to on as well as truncate-lines - should I be calling the spacemacs toggle functions in `dotspacemacs/config` like below?

```
(defun dotspacemacs/config ()
  "Configuration function.
 This function is called at the very end of Spacemacs initialization after
layers configuration."
  (spacemacs/toggle-line-numbers)
  (spacemacs/toggle-truncate-lines)
)
```

Line numbers will work, but not truncate lines. Essentially, what is the most correct way to default things to be on instead of off or vice versa?

**Comment by person808** [comment]
You can toggle minor-modes explicitly, so activating line numbers would be `(global-linum-mode t)` or `(linum-mode t)` depending on if you want them globally. I'm pretty sure truncating lines is a variable `(setq truncate-lines t)` if I remember correctly.

**Comment by beardedprojamz** [comment]
Thanks for the feedback. Updating before closing:

truncate lines I added to `dotspacemacs/init` in the big `setq-default` list.

linum-mode I added it to the prog-mode hook like below:

```
  (add-hook 'prog-mode-hook 'linum-mode)
```
