### ISSUE TITLE
Inferior Python shell uses tabs instead of spaces despite indent-tabs-mode nil 

### ISSUE THREAD

**Issue by tsoernes** [syl20bnr/spacemacs#12749]
I'm on Spacemacs develop.

The Inferior Python shell (running IPython) indents using tabs, not spaces. I have this in my dotfile:-
```
  (add-hook 'inferior-python-mode-hook
            (lambda () (setq indent-tabs-mode nil)))
```
Describing the `indent-tabs-mode` variable after opening the shell says it's `t`.

**Comment by Compro-Prasad** [comment]
Is that a problem? If so, what?

**Comment by tsoernes** [comment]
That's a problem if you paste code from anywhere, which is likely to use
spaces which is the PEP standard, and then modify that pasted code, you'll
end up with a mix of tabs and spaces, which the python interpreter throws
an error at.

**Comment by Compro-Prasad** [comment]
If so, do you like to remove `spacemacs//inferior-python-setup-hook` from `inferior-python-mode-hook` as a PR?

**Comment by tsoernes** [comment]
I'll do it.

**Comment by tsoernes** [comment]
https://github.com/syl20bnr/spacemacs/pull/12752
