### ISSUE TITLE
Remove current buffer from helm-projectile-switch-project

### ISSUE THREAD

**Issue by dsdshcym** [syl20bnr/spacemacs#1275]
Every time I use ```helm-projectile-switch-project```, I find that the current buffer is in the ```Project buffers``` section.

This behavior is really odd most of the time. Cause if I use ```helm-projectile-switch-project``` instead of ```helm-projectile-find-file```, the current buffer is clearly not the file of the Project I want.

And I also find that the current buffer's path is changed to the chosen project path.

Like this:
![screen shot 2015-04-20 at 14 43 44](https://cloud.githubusercontent.com/assets/4723751/7224987/d70d80e8-e76b-11e4-94be-6d6789216546.png)

But the original path of ```ics.org``` is:
![screen shot 2015-04-20 at 14 46 15](https://cloud.githubusercontent.com/assets/4723751/7225001/14880cfe-e76c-11e4-836f-a0ce4514ba6a.png)

I don't know if this is a ```projectile```'s bug or something else. Maybe we can improve this in spacemacs.

**Comment by sooheon** [comment]
I've had the same frustration, curious if this should be dealt with upstream at projectile, though?

Great choice of font btw :)

**Comment by dsdshcym** [comment]
@sooheon Well, I'll post this issue to ```projectile```, hope it will be fixed soon.

Thank you. It's ```Input```.

**Comment by syl20bnr** [comment]
@dsdshcym post back a reference to the issue here in order to track it, thank you.

**Comment by dsdshcym** [comment]
https://github.com/bbatsov/projectile/issues/721
