### ISSUE TITLE
`haskell-compile` (SPCmcc) problems

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#1276]
It creates a sticky popup and moves the cursor to a next window. It should create a typical popup (escapable with `fd`) or at least should not move the cursor away from a sticky one.

**Edit**(removed)**:** It prompts to save all unsaved buffers. It should prompt for just a current one.

**Comment by syl20bnr** [comment]
Does `haskell-compile` only compile the current buffer or does it compile some kind of project if available ?

**Comment by ocharles** [comment]
It compiles the whole project. I think asking for all unsaved buffers to be saved is the right thing to do.

**Comment by xged** [comment]
After playing around a little bit I am fine with default behavior of popups.
