### ISSUE TITLE
Rust LSP Auto-completion Does Not Expand Correctly

### ISSUE THREAD

**Issue by BigBeautifulBro** [syl20bnr/spacemacs#12766]
#### Description :octocat:
When using the Rust layer with auto-completion and LSP as the company backend, selecting a completion from the dropdown list does not work properly when the completion candidate is a function with one or more parameters. In this situation when using M-x company-complete, after selecting a candidate, the selection's yasnippet template is incorrectly pasted as-is without expansion. This issue also occurs when attempting to a select a candidate by just typing a couple letters, waiting for the autocompletion list without using M-x company-complete, and then selecting a candidate.

Auto-completion works properly and as expected when using M-x company-lsp instead of M-x company-complete.

If the solution is that users should use M-x company-lsp when using Rust with LSP as the company backend, please document this. This was not obvious to me, and I thought you should be using M-x company-complete.

#### Reproduction guide :beetle:
- Start Emacs
- Open a rust-mode buffer
- add a new line in a function and type:
  "test".re
- Wait for the candidate list to automatically show or use M-x company-complete
- Select the "replace" candidate

*Observed behaviour:* :eyes: :broken_heart:
The text "replace(${1:from: P}, ${2:to: &str})" is pasted literally as a completion with the user's cursor at the end of this text. The user is not able to edit the parameters as a yasnippet expansion.

*Expected behaviour:* :heart: :smile:
The text "replace(from: P, to: &str)" should be pasted as a completion with the user's cursor in the first parameter allowing them to edit the parameters as a yasnippet expansion.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4d57a4b90)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(rust themes-megapack
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior nil :disabled-for org erc)
      emacs-lisp git helm multiple-cursors syntax-checking treemacs lsp dap)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by BigBeautifulBro** [comment]
For others that are having this issue, an easy temporary work around is to just disable the automatic completion pop-up and change the bind for company-complete in rust mode:
```elisp
; Under dotspacemacs-configuration-layers
; Ensure auto-completion-idle-delay is nil to prevent automatic completion pop-up
(auto-completion :variables
                      auto-completion-enable-help-tooltip t
                      auto-completion-enable-snippets-in-popup nil
                      auto-completion-return-key-behavior 'complete
                      auto-completion-tab-key-behavior nil
                      auto-completion-idle-delay nil
                      :disabled-for org erc)

...
; Under dotspacemacs/user-config
  (global-set-key (kbd "C-.") 'company-complete)
  (define-key spacemacs-rust-mode-map-root-map
    (kbd "C-.") 'company-lsp)
```

**Comment by MarcoIeni** [comment]
Hi, I reproduced your problem but for me it works, I am using rust-analyzer.
![Peek 2020-04-14 11-48](https://user-images.githubusercontent.com/11428655/79211188-329a3980-7e46-11ea-9853-aa8fa46005a5.gif)

As you can see from my config I copy-pasted your auto-complete settings

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 50921702a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(octave yaml clojure dap
        (lsp :variables lsp-ui-doc-enable nil lsp-ui-sideline-code-actions-prefix " " lsp-ui-sideline-show-hover nil lsp-rust-server 'rust-analyzer lsp-rust-analyzer-server-display-inlay-hints nil)
        (rust :variables rust-format-on-save t)
        (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior nil :disabled-for org erc)
        (syntax-checking :variables syntax-checking-enable-tooltips nil)
        (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
        helm emacs-lisp
        (git :variables git-magit-status-fullscreen nil magit-diff-refine-hunk 'all)
        multiple-cursors neotree
        (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t)
        semantic cscope spell-checking treemacs
        (version-control :variables version-control-diff-side 'left version-control-diff-tool 'diff-hl))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by lebensterben** [comment]
Closing since
- No further update from OP
- I'm a heavy user of Rust, for both RLS and rust-analyzer, and I cannot reproduce this issue.
