### ISSUE TITLE
dap-gdb-lldb-setup failed

### ISSUE THREAD

**Issue by jidibinlin** [syl20bnr/spacemacs#12770]
**I followed the c-c++ layer to config my spacemacs, but when I came to the debuger config (M-x dap-gdb-lldb-setup) message reported like blew**
![dap-issue](https://user-images.githubusercontent.com/38578679/65681046-c5ca7800-e08a-11e9-84a0-bc2be9452ab9.png)  
**And this is my .config**
![dapissue2](https://user-images.githubusercontent.com/38578679/65681176-00341500-e08b-11e9-87eb-bc3048982a0a.png)

**I used develop branch thankyou!**

**Comment by jidibinlin** [comment]
I have solved this problem.

**Comment by k4lipso** [comment]
@jidibinlin 

> I have solved this problem.

realy? Is that all you tell us about your solution? Thanks for nothing.

**Comment by duianto** [comment]
@jidibinlin Could you describe how you solved it? 

Like k4lipso, anyone that finds this thread when searching for the same error message, will wonder how you solved it.

**Comment by k4lipso** [comment]
After checking the *Messages* buffer i saw that dap-gdb-lldb-setup writes a .zip file to /tmp/ and than fails with the "Wrong type argument: stringp, nil" message. I checked if "unzip" was installed on my system and it was not, installing it solved the problem. so it seems like dap-gdb-lldb-setup depends on unzip (and the user needs write permissions on /tmp).

Depending on you distro you should be able to install unzip with one of the following commands:
`apt install unzip`
`pacman -S unzip`
`nix-env -i unzip`
On most linux distributions unzip is installed by default.

**Comment by omrisim210** [comment]
`xbps-install unzip` on Void.

I'm surprised this still isn't mentioned in the README for the C/C++ layer, or that the error isn't reported in a more obvious manner.

It's also worth noting I had to restart Emacs (SPC-q-r) after installing unzip for it to work.

**Comment by duianto** [comment]
An issue has been opened upstream to improve the error message if `unzip` isn't installed.
dap-gdb-lldb-setup requires unzip https://github.com/emacs-lsp/dap-mode/issues/313
