### ISSUE TITLE
Unable to start-up Spacemacs without Internet connection

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#1278]
I've had this happen a few times at coffee shops and hotel WiFi's where the connection is less than stellar. If I try to open up Spacemacs, the GUI starts and I see "Connecting host: tromey.com:80" in the minibuffer, but nothing happens beyond this and Emacs becomes totally unresponsive. I thought I managed to get around this previously by turning off my WiFi entirely, but when I tried this recently, I get the following stacktrace when trying to start with `--debug-init`:

```
Debugger entered--Lisp error: (error "tromey.com/80 nodename nor servname provided, or not known")
  make-network-process(:name "tromey.com" :buffer #<buffer  *url-http-temp*> :host "tromey.com" :service 80 :nowait t)
  open-network-stream("tromey.com" #<buffer  *url-http-temp*> "tromey.com" 80 :type plain :nowait t)
  byte-code("\306\211\n\307>\203$

**Comment by syl20bnr** [comment]
Spacemacs will try to contact the servers only if a used package is not installed. We can add a variable to disable the auto-installation of packages, there is already a variable to disable automatic cleanup of orphans.

**Comment by luxbock** [comment]
If I start Spacemacs with Internet connection, it should download and install any missing packages in my config, correct? If I then turn off my WiFi and restart Spacemacs, I would expect there to be nothing it should need to check, since I haven't deleted or added any packages since the last time I ran it, but yet when I repeat this process then the result is always the same, i.e. the issue discussed here. I tried this with all of my `dotspacemacs-configuration-layers` disabled just in case, but it didn't seem to have any effect. I'm trying to understand how I should change my configuration to avoid this issue, but I haven't been able to figure out what I'm doing wrong from looking at the code base yet. Any pointers?

**Comment by tuhdo** [comment]
After Spacemacs is completely installed, restarting Spacemacs should not causing any network activity.

**Comment by luxbock** [comment]
After deleting all of my themes from `~/.emacs.d/elpa/` and removing the theme-megapack from my `.spacemacs` the issue appears to have gone away.

**Comment by syl20bnr** [comment]
I think this should be resolved in develop because used themes are not considered orphans anymore. This is the only explanation I have for this network activity.
I close it for now, feel free to re-open if you have still the issue.
