### ISSUE TITLE
Error (use-package): cquery/:config: Symbol’s function definition is void: spacemacs/dap-bind-keys-for-mode

### ISSUE THREAD

**Issue by laynor** [syl20bnr/spacemacs#12784]
#### Description :octocat:

Error (use-package): cquery/:config: Symbol’s function definition is void: spacemacs/dap-bind-keys-for-mode

#### Reproduction guide :beetle:
- Enable the c-c++ layer
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Emacs reports 
Error (use-package): cquery/:config: Symbol’s function definition is void: spacemacs/dap-bind-keys-for-mode

*Expected behaviour:* :heart: :smile:
No warnings

The spacemacs/dap-bind-keys-for-mode function is not declared anywhere in the code base, as dap configuration is now done in the dap layer (see https://github.com/syl20bnr/spacemacs/pull/12712#issuecomment-536503141_), so it should be safe to remove those calls.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fdd38eec9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(idris javascript haskell factor emacs-lisp common-lisp racket
       (python :variables python-test-runner
               '(nose pytest)
               python-backend 'lsp)
       fsharp
       (c-c++ :variables c-c++-backend 'lsp-cquery)
       html yaml dap shell-scripts helm cmake
       (auto-completion
        (haskell :variables haskell-completion-backend 'intero))
       better-defaults lsp git github syntax-checking dap
       (version-control :variables version-control-diff-tool 'diff-hl))
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS PDUMPER GMP

**Comment by cormacc** [comment]
This is closed by #12712

**Comment by yssource** [comment]
Error (use-package): ccls/:config: Symbol’s function definition is void: spacemacs/dap-bind-keys-for-mode

**Comment by emacs18** [comment]
If I understood #12712, we are still waiting for Sylvain to commit his refactor of c-c++ layer.  When that is done, then this void function problem will also be resolved, i.e., this problem will be solved when #12712 is resolved.

**Comment by syl20bnr** [comment]
Indeed I am still refactoring it, I'm about 50% maybe more. Good chances I finish it during this long week end here at Quebec :-)

**Comment by syl20bnr** [comment]
Some update, I'm currently trying to use the various backends with a C++ project. If you have ideas for C/C++ repository I could test with, I'm all hear :-)

**Comment by robertodr** [comment]
This one: https://github.com/nlohmann/json or this one: https://github.com/catchorg/Catch2

**Comment by beyondpie** [comment]
Still has the problem... Anyone has solved it?

**Comment by duianto** [comment]
Here's the link to the refactoring PR: [c-c++] Layer refactor #12869

**Comment by syl20bnr** [comment]
Refactored PR has been pushed to develop branch.

**Comment by emacs18** [comment]
Thanks.  I think this issue is now moot since spacemacs/dap-bind-keys-for-mode no longer exist anywhere.

**Comment by sunlin7** [comment]
Issue is fixed now.
