### ISSUE TITLE
python layer forces lsp backend

### ISSUE THREAD

**Issue by skebanga** [syl20bnr/spacemacs#12789]
#### Description :octocat:
python layer forces lsp backend

#### Reproduction guide :beetle:
- Start Emacs
- have python layer configured
- if lsp is available (eg: from another layer) `pyls` will be started
- setting `python-backend nil` has no effect
- setting `python-backend 'anaconda` is a workaround

*Observed behaviour:* :eyes: :broken_heart:
`pyls` is started with no way to prevent it

*Expected behaviour:* :heart: :smile:
enabling lsp support should be explicit

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fdd38eec9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp html javascript go lua octave csv git markdown neotree
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
      imenu-list version-control
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-backend 'lsp-cquery)
      (ranger :variables ranger-show-literal nil)
      (python :variables python-backend 'anaconda)
      yaml lori-cpp
      (smart-tabs :variables smart-tabs-default-insinuations
                  '(c c++))
      protobuf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by dhruvinsh** [comment]
with this commit https://github.com/syl20bnr/spacemacs/commit/ac30247811d28e86c4b33d6150d678d5f5824330 everything changed,  all the language with LSP support, lsp will be used by default. setting `python-backend 'anaconda` is an intended functionality.

if no further question, please close an issue.
