### ISSUE TITLE
CoffeeScript language support

### ISSUE THREAD

**Issue by dd1994** [syl20bnr/spacemacs#1279]
[CoffeeScript](http://coffeescript.org/) is a little language that compiles into JavaScript, it's really popular,
according to https://www.npmjs.com/package/coffee-script , 2,577,116 downloads in the last month.,
it would be awesome if spacemacs support it !

**Comment by stormpat** [comment]
The JS layer has built in support for CoffeeScript, https://github.com/syl20bnr/spacemacs/tree/master/contrib/lang/javascript

**Comment by dd1994** [comment]
Thank you @stormpat

**Comment by idoo** [comment]
Please help me apply syntax highlighter?

**Comment by liukun** [comment]
@idoo Edit your ~/.spacemacs and place `javascript` under `(setq-default dotspacemacs-configuration-layers '(` then restart Emacs to see the highlighted coffeescript codes. ref: https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/javascript
