### ISSUE TITLE
Feature request: There exists awesome Telegram client for Emacs

### ISSUE THREAD

**Issue by Anton-Latukha** [syl20bnr/spacemacs#12800]
There is a shiny new and unique client: https://github.com/zevlg/telega.el

Why unique? I mean, /****/, huge part of features done in it are unique for Telegram community clients:

> + VoIP calls, including D-Bus call notification
> + Display chat actions, such as "@user is typing..."
> + Display/Update chat's draft message
> + Secret chats
> + Special messages such as location/live location, voice/video messages, contacts, etc (PARTLY)
> + Poll messages, Poll creation
> + Handling local links, such as "tg:" or "https://t.me/xxx" (PARTLY)
> + ReplyMarkup (inline keyboard buttons) in the messages (PARTLY)
> + InstantView for web pages
> + Blocking/Unblocking users, listing blocked users
> + Labeled chats, you can assign custom label to chat
> + Client side messages filtering
> + Get diff for the message edits

Some of these features are not even in the official desktop (& Electron) Telegram client.

Guys (mainly the `zevlg` alone) did & we got the best Telegram client on Linux desktops right here, and it is in Emacs.

**Comment by AleXoundOS** [comment]
The issue is still valid. But it's not clear how the spacemacs integration is going to look like.

**Comment by Anton-Latukha** [comment]
Yep.

Configuration & installation now works.

Even on NixOS.

The current installation is a simple addition of the package, and installing/compiling local system deps, `tdlib` and checking local telegram CLI works.

How Spacemacs integration would look like? - Just like Slack or IRC. What Spacemacs can add? - simplified instructions and guidence, key bindings to access different buffers of the client, major mode submenu and bindings, and maybe rebind some initial `telega` binds to be uniformal with what Spacemacs uses.

**Comment by AleXoundOS** [comment]
The issue is still valid.
