### ISSUE TITLE
Consider setting helm-split-window-in-side-p to t

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1280]
It's less annoying when users have a layout with multiple windows; otherwise it makes Helm very annoying to use frequently because window layout keeps changing, hence flashing the screen. Even for two windows side-by-side, Helm window is often wide enough to display everything and still has significant space left to the right on my 15'' laptop. Even open Helm window in other window is less annoying because it increases the display height and we can look at more candidate.

Setting `helm-split-window-in-side-p` to `t` makes Helm window appears in current window only and thus saving screen space.

**Comment by tuhdo** [comment]
Also when setting that variable to `t`, the bug that the cursor escapes minibuffer prompt while a helm session is active no long remains.

**Comment by syl20bnr** [comment]
:+1:
