### ISSUE TITLE
Terminal Doesnt Support CPR / ipdb

### ISSUE THREAD

**Issue by th3r00t** [syl20bnr/spacemacs#12806]
#### Description :octocat:
ipdb terminal doesnt support cursor position request,
When trying to debug any python file using ipdb a CPR error
occurs

#### Reproduction guide :beetle:
- Start Emacs
- Open python file
- insert breakpoint
- debug a test or otherwise invoke debugging

*Observed behaviour:* :eyes: :broken_heart:
Begins debugging until the repl prompt is to be displayed,
and instead prints out the CPR error

*Expected behaviour:* :heart: :smile:
To instantiate the debugger correctly

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 emacs-lisp git org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control
 (python :variables python-backend 'lsp python-fill-column 99 python-formatter 'yapf python-enable-yapf-format-on-save t python-sort-imports-on-save t python-test-runner 'pytest python-pipenv-activate t)
 ranger)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by Trapez** [comment]
Switch to the develop branch. Check your config against the develop documentation.
