### ISSUE TITLE
dotspacemacs-mode-line-theme not working as expected

### ISSUE THREAD

**Issue by ThomasBiede** [syl20bnr/spacemacs#12818]
#### Description :octocat:
dotspacemacs-mode-line-theme not working

I tried to customize the mode-line but the lines I tried from the docs were not working/effecting the mode-line in any way. 
#### Reproduction guide :beetle:
- Start Emacs
- Open .spacemacs
- add dotspacemacs-mode-line-theme configurations from the doc

*Observed behaviour:* :eyes: :broken_heart:
Nothing changed, it still shows the standard modeline theme

*Expected behaviour:* :heart: :smile:
Different modeline theme

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html javascript python helm auto-completion better-defaults emacs-lisp git shell
      (shell :variables shell-default-height 20 shell-default-position 'bottom shell-default-full-span nil)
      spell-checking syntax-checking version-control colors
      (colors :variables colors-enable-nyan-cat-progress-bar t)
      window-jump
      (spaceline-toggle-buffer-size-off))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
The `dotspacemacs-mode-line-themes` variable is only available on the `develop` branch at the moment.

You might have been watching the develop branch documentation.
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#mode-line-themes

The new variable is listed in the `changelog.develop`:
>  - New variable =dotspacemacs-mode-line-themes= adds support for mode-line
    themes. Supported themes are =spacemacs=, =all-the-icons=, =vim-powerline=,
    =custom=, and =vanilla=. The first three are spaceline themes, =custom= is
    user defined, and =vanilla= is the default Emacs mode-line.
    (thanks to Sylvain Benner and James Wang)

https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop#dotfile-changes

If you want to use the mode-line themes now, then you'll have to switch to the develop branch.

**Comment by humanfactors** [comment]
This should be closed.
