### ISSUE TITLE
[Proposal] Switching from popwin to window-purpose

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1281]
As I already the advantages of [window-purpose](https://github.com/bmag/emacs-purpose) in this PR: https://github.com/syl20bnr/spacemacs/pull/1072, it gives you precise control on where a buffer should appear. `popwin` will be a burden when more layers are added, when you have packages that create windows i.e. Geiser (interactive development for Scheme similar to SLIME) or SLIME (interactive development for Common Lisp). Currently `popwin` messes with SLIME buffers such as debugger and inspector windows badly, `*vc -diff*` is unusable when poping from below...

`guide-key` won't be affected because it has its own temporary window mechanism.

**Comment by syl20bnr** [comment]
I see what interesting UI we can achieve with this, I'll have a look at it.

**Comment by bmag** [comment]
As the author of `window-purpose` and a relatively new Spacemacs user, I'd be glad to help.
I was planning to write an extension for `window-purpose` that emulates `popwin` sometime in the next month, but I can try and do it sooner  if you want.

**Comment by jordwalke** [comment]
I would be curious if `window-purpose` could solve the problem that I described here: https://github.com/syl20bnr/spacemacs/issues/4247

**Comment by bmag** [comment]
If I understand the problem correctly, I don't think there will be a difference. I tried both `popwin` and `window-purpose` and didn't see a difference.

**Comment by jordwalke** [comment]
Could you fix this in window-purpose? Vim and emacs are terrible at this and it would be great if someone finally fixed it.

**Comment by bmag** [comment]
I doubt I can fix it, I think it's an Emacs thing. When creating a new window (e.g. for Helm), Emacs needs to split an existing window. But what if the point ("point" means the cursor's position in the window's buffer) is hidden from view? Then Emacs scrolls the window so the point is visible again. You can set the variable `window-split-keep-point` to `nil`, but that will change the behavior only for the `split-window-below` function and other functions that rely on it. For other scenarios, I don't of a simple way to prevent Emacs from scrolling the window.

You can read about `window-split-keep-point` and related stuff [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Split-Window.html), or via `C-h v window-split-keep-point RET`.

**Comment by jordwalke** [comment]
Continuing discussion there.

**Comment by StreakyCobra** [comment]
PR Pending: #1958

**Comment by syl20bnr** [comment]
Should be fixed in develop, #1958 has been merged.
