### ISSUE TITLE
Move text and transpose microstates

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1282]
I think these groups should have their microstates. Currently to move text up, after executing `M-m x m j` , it's faster to press `C-x z` (run command `repeat` to repeat last command), then keep pressing `z` (after initial `C-x z` invocation).

**Comment by syl20bnr** [comment]
Would be pretty cool to have a microstate for moving text. For the transpose I don't see the use case though, do you have an example ?

**Comment by tuhdo** [comment]
@syl20bnr You are right. We don't need one for transposing text.

**Comment by CestDiego** [comment]
:+1:

**Comment by syl20bnr** [comment]
I added one on `xJ` and `xK`.

**Comment by CestDiego** [comment]
What is this transpose for? I think evil has something like thid unger `g`

**Comment by syl20bnr** [comment]
I did not understand the question. transpose is not in the micro-state as discussed above.

**Comment by CestDiego** [comment]
Sorry typo fixed... I meant that there is something in evil that moves text around. it's under the `g` preffix I suppose.

**Comment by syl20bnr** [comment]
Ok, maybe open a new issue about this if you find the Vim corresponding keys.
