### ISSUE TITLE
impatient-mode doesn't work

### ISSUE THREAD

**Issue by krdzo** [syl20bnr/spacemacs#12831]
#### Description :octocat:
Impatient mode (more accurately simple-httpd) doesn't work. Browser won't open localhost:8080/imp or any other localhost url.
Tried a clean emacs install and impatient-mode and it works.
Also tried only to install impatient-mode package and not the whole layer and it still doesn't work.

#### Reproduction guide :beetle:
- Start Emacs
- Install html layer
- Starting impatient-mode or manually starting httpd server with (httpd-start)
- Going to localhost:8080 in my browser and the page doesn't open.

*Observed behaviour:* :eyes: :broken_heart:
Can't open html buffer with impatient-mode in browser.

*Expected behaviour:* :heart: :smile:
To open my html buffer in my browser.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8d6f73620)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion lsp emacs-lisp helm multiple-cursors treemacs
                 (c-c++ :variables c-c++-backend 'lsp-ccls)
                 html)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:

This is the contents of the \*httpd\* buffer:
```

(stop "Tue Oct 15 01:06:03 2019")
(start "Tue Oct 15 01:06:03 2019")
(connection "127.0.0.1")
(connection "127.0.0.1")
(request
 (date "Mon, 14 Oct 2019 23:06:08 GMT")
 (address "127.0.0.1")
 (get "/")
 (headers
  ("GET" "/" "HTTP/1.1")
  ("Host" "localhost:8080")
  ("Connection" "keep-alive")
  ("Upgrade-Insecure-Requests" "1")
  ("User-Agent" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.93 Safari/537.36 Vivaldi/2.8.1664.40")
  ("Sec-Fetch-Mode" "navigate")
  ("Sec-Fetch-User" "?1")
  ("Accept" "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3")
  ("Sec-Fetch-Site" "none")
  ("Accept-Encoding" "gzip, deflate, br")
  ("Accept-Language" "en-US,en;q=0.9")
  ("Content" "")))
(directory "/home/user/workspace/")
(error 500
       (wrong-type-argument number-or-marker-p
                            [utf-8-unix utf-8-dos utf-8-mac]))
(hard-error
 (wrong-type-argument number-or-marker-p
                      [utf-8-unix utf-8-dos utf-8-mac]))

```

**Comment by krdzo** [comment]
Thanks. It works now. I rolled back simple-httpd and the problem is fixed now.

**Comment by duianto** [comment]
Maybe this is upstream issue is the same or similar:
Impatient mode doesn't work at all https://github.com/skeeto/impatient-mode/issues/20
