### ISSUE TITLE
Loading auctex and cdlatex

### ISSUE THREAD

**Issue by rahulk73** [syl20bnr/spacemacs#12840]
I'm a spacemacs beginner so this may seem trivial but I'm having trouble trying to load installed packages, and after browsing similar issues online I couldn't find a fix.
I'm using the Emacs editing style.

I installed two packages -

1. `auctex` 
2. `cdlatex`

using `ELPA` and it worked perfectly. 

However spacemacs kept deleting them on reboot as it was marking them as orphan packages.
I found a workaround to this by changing the ` dotspacemacs-install-packages 'used-only` to ` dotspacemacs-install-packages 'used-but-keep-unused`

But now when I reload spacemacs, the packages are not loaded.

If I add the lines `require 'auctex` or `require 'cdlatex` I get thrown a not found error.
Its weird beacause I have other packages installed via `ELPA` and a simple `require 'package-name` worked perfectly, but something about these two packages doesn't seem to make it work.
If someone could please help me find a way to load these packages on startup, I'd be really grateful.

**Comment by duianto** [comment]
`auctex` is part of the Spacemacs `latex` layer:
https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/latex

`cdlatex` seems to be `org-mode` related. This command is suggested to enable cdlatex mode:
```elisp
(add-hook 'org-mode-hook 'turn-on-org-cdlatex)
```
source: https://orgmode.org/manual/CDLaTeX-mode.html

**Comment by rahulk73** [comment]
Thanks a ton @duianto , I added the latex layer and auctex works perfectly.

cdlatex was still not working (I already had that add-hook command), but after some fiddling , this seemed to make it work for me - 
`  (add-to-list
   'load-path.
   (expand-file-name "~/.emacs.d/elpa/cdlatex"))
  (require 'cdlatex)`

**Comment by duianto** [comment]
That's great 👍 

The markdown syntax for inserting a code block is to add three backticks on the line before, and after the code block.
Here's a guide: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by rahulk73** [comment]
Sorry about that, I'll fix that.

Thanks for the link and thanks for the help again !
