### ISSUE TITLE
emacsclient: one session freezes other sessions under certain interactive commands

### ISSUE THREAD

**Issue by randomizedthinking** [syl20bnr/spacemacs#12842]
#### Description :octocat:
My workflow is to launch an emacs in daemon mode, then use emacsclient to
connect to it. In general, I have multiple frames open at the same time.

The problem I found is: many components might be in conflict between sessions.
For instance, if I have helm-mini buffer open in one session, then all other
sessions would be frozen. Most helm interactive commands have this issue.

Also, this is not only related to helm, but other packages as well. For
instance, if we execute `M-x org-agenda` in one emacsclient, it will effectively
freeze other sessions.

#### Reproduction guide :beetle:
- Start Emacs: `emacs --daemon`
- Start emacsclient 1: `emacsclient -nw`
- Start emacsclient 2: `emacsclient -nw`
- Open helm-mini in emacsclient 1: `SPC b b`

*Observed behaviour:* :eyes: :broken_heart:
- Now emacsclient 2 is frozen...

*Expected behaviour:* :heart: :smile:
I wish we will work as usual in emacsclient 2.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv python clojure sql helm auto-completion emacs-lisp git markdown shell
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
I suspect that the packages don't have separate sessions under the same daemon.
Variables and key maps are probably changed when for example the helm buffer is opened.

You could ask in the upstream packages if it's something they could implement.

And/or try:
https://github.com/plexus/chemacs
>Chemacs is an Emacs profile switcher, it makes it easy to run multiple Emacs configurations side by side.
>
>Think of it as a bootloader for Emacs.

One issue might be if you try to open the same file from different Emacs instances, then you'll have to steal it away from the other one.

You probably have to keep duplicate sets of all Emacs related files.

But then you should be able to open, for example helm buffers in each instance, without one effecting the other one.

**Comment by randomizedthinking** [comment]
Thanks for the input.

I feel this is a quite hard issue, and it requires re-writes from the very bottom...
