### ISSUE TITLE
Version Control to take dark/light them into account

### ISSUE THREAD

**Issue by dmocek** [syl20bnr/spacemacs#12853]
As an enhancement request, it would be nice if Version Control (really, all layers) took the current them into account when choosing colors.  In particular, the "green" for "added" is very difficult to see in light themes, especially Solarized Light.  For Version Control, I think it would be sufficient to have just a set of colors for dark themes (the current colors would work fine) and another set of dark colors for  light themes...specifically different colors for dark/light gutters.

**Comment by duianto** [comment]
The colors are handled by each theme.

You can open an issue in the upstream theme to suggest better colors.
Provide a screenshot of what your seeing.
And if possible a suggestion for a better color.

This seems to be the repository for the solarized emacs theme:
https://github.com/bbatsov/solarized-emacs

If you want to change faces locally now, then you can add this command to the `dotspacemacs/user-config` section of your `.spacemacs` file.
```elisp
(set-face-attribute 'default nil :foreground "#333333" :background "#aaaaaa")
```
If you want ideas about which diff faces to set:

Here's the diff faces that are supported by the default Spacemacs theme: https://github.com/nashamri/spacemacs-theme
https://github.com/nashamri/spacemacs-theme/blob/32ddc1a9b9f4f58ebe8410abc1124b7acf0f36b1/spacemacs-common.el#L288

And here are the supported Magit faces:
https://github.com/nashamri/spacemacs-theme/blob/32ddc1a9b9f4f58ebe8410abc1124b7acf0f36b1/spacemacs-common.el#L618

You can also find a list of face names by pressing: `SPC h d F`
And if you want to find out which faces are shown under the cursor, then press `SPC h d c` which calls `describe-char`, and scroll to the bottom of the `*Help*` window.

There is a delay when Spacemacs starts before your custom attribute is applied. Spacemacs seems to prioritize loading the theme that's listed first in the `dotspacemacs-themes` variable in `.spacemacs`.

I tried adding the set-face-attribute command to to the `dotspacemacs/user-init` section, but it doesn't seem to load any faster than from the `dotspacemacs/user-config` section.

If you want a custom color to load on startup, then you could create your own theme.
Or you can use a modified version of an existing theme.

Here's a guide which might be helpful:
https://github.com/syl20bnr/spacemacs/issues/12333#issuecomment-537401501
