### ISSUE TITLE
Alchemist key-bindings not available in Elixir major mode menu

### ISSUE THREAD

**Issue by carsten-luckmann** [syl20bnr/spacemacs#12859]
#### Description :octocat:
Alchemist key-bindings are not available in the Elixir major mode menu (SPC-m or ,).

First analysis shows that alchemist-mode is not loaded automatically when elixir-mode is used as major mode.
After having loaded alchemist-mode manually, Alchemist key-bindings are still not available in the Elixir major mode menu.

The problem was observed in Emacs 26.2 on Mac OSX (reporting system, see below) as well as in Emacs 26.3 on GNU/Linux.

#### Reproduction guide :beetle:
- Start Emacs
- Open an Elixir file
- Open the major mode menu (SPC-m or ,)

*Observed behaviour:* :eyes: :broken_heart:
- alchemist-mode is not loaded automatically
- Alchemist key-bindings as documented on http://develop.spacemacs.org/layers/+lang/elixir/README.html are not available.

*Expected behaviour:* :heart: :smile:
- alchemist-mode is loaded automatically
- Alchemist key-bindings as documented on http://develop.spacemacs.org/layers/+lang/elixir/README.html are available.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5fcd6e31e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((osx :variables osx-use-option-as-meta nil)
 helm auto-completion better-defaults asciidoc bibtex bm c-c++
 (chrome :variables edit-server-url-major-mode-alist
         '(("github\\.com" . markdown-mode)))
 (clojure :variables clojure-enable-fancify-symbols nil)
 (colors :variables colors-colorize-identifiers 'variables)
 crystal cscope csv debug docker
 (elixir :variables flycheck-elixir-credo-strict t)
 (elm :variables elm-format-on-save t elm-sort-imports-on-save t)
 emacs-lisp erlang finance git
 (go :variables go-backend 'lsp go-format-before-save t go-tab-width 4 go-use-golangci-lint t go-use-test-args "" godoc-at-point-function 'godoc-gogetdoc gofmt-command "goimports")
 graphviz
 (haskell :variables haskell-enable-hindent t haskell-enable-hindent-style "johan-tibel")
 html
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 imenu-list
 (javascript :variables js2-basic-offset 4 js-indent-level 4)
 json jsonnet
 (latex :variables latex-enable-auto-fill t latex-enable-magic t)
 (lsp ::variables lsp-ui-doc-enable t lsp-ui-sideline-enable t)
 markdown multiple-cursors nixos
 (org :variables org-enable-github-support t org-enable-reveal-js-support t org-enable-org-journal-support t org-enable-sticky-header t)
 pandoc parinfer pdf phoenix protobuf purescript
 (python :variables python-backend 'lsp python-format-on-save t python-save-before-test t python-sort-imports-on-save t)
 rebox restclient
 (ruby :variables ruby-enable-enh-ruby-mode t)
 ruby-on-rails
 (rust :variables rust-backend 'lsp rust-format-on-save t)
 selectric
 (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom shell-enable-smart-eshell t)
 shell-scripts spell-checking
 (sql :variables sql-capitalize-keywords t)
 syntax-checking themes-megapack
 (treemacs :variables treemacs-use-filewatch-mode t treemacs-use-follow-mode t)
 (typography :variables typography-enable-typographic-editing t)
 (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac)
 version-control yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by sdwolfz** [comment]
```

**Comment by carsten-luckmann** [comment]
`elixir-backend` 'alchemist works. Will also try `lsp`.

Since this is not mentioned on the layer documentation page, I suggest adding it.

Thanks for your help.

**Comment by carsten-luckmann** [comment]
Nevermind, I have seen that the documentation is already updated in the git repository. Just the website http://develop.spacemacs.org/layers/+lang/elixir/README.html does not show it yet.
