### ISSUE TITLE
Deleting a new buffer with changes does not ask for confirmation

### ISSUE THREAD

**Issue by gutsle** [syl20bnr/spacemacs#12857]
Given that software usually asks when one is about to throw away unsaved work I find this behavior unexpected and it should be changed.

**Comment by gutsle** [comment]
If you would like to reproduce `SPC b N`, type something,` SPC b d`.

**Comment by thanhvg** [comment]
Buffer is different concept in emacs. For you concern create new buffer with `spc f f` then emacs will nag you on closing without saving

**Comment by gutsle** [comment]
@thanhvg But `SPC f f` requires a filename, which I don't always want to deal with when I am creating random "scratch buffers". Not to be confused with the actual *scratch* buffer.

**Comment by antonalekseev** [comment]
@gutsle Then you could create junk file with `SPC f J` and name will be provided. Either add custom `kill-buffer-hook` like explained [here](https://emacs.stackexchange.com/a/16337).

**Comment by gutsle** [comment]
@antonalekseev That's a nice link. I think, since Spacemacs is all about good defaults, maybe it would be a nice improvement to make this work as described there.
To reiterate here:
Indeed commonly programs just have a "new file" button and you are asked to save exactly if your changes would be lost. That seems like a good way to do it in Spacemacs as well.

**Comment by henriquenj** [comment]
I like this feature request. I think we should keep it open. @duianto can you keep this open if someone wants to work on it?
