### ISSUE TITLE
Spacemacs consumes huge amounts of memory (memory leak?)

### ISSUE THREAD

**Issue by natask** [syl20bnr/spacemacs#12870]
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>
  spacemacs consumes exorbitant amount of memory. Opening new frames adds on to memory consumed. It can go up to a GB and even more with time/with opened frames. Closing frames doesn't have impact on memory usage and garbage collect doesn't have effect. I am using spacemacs develop branch.

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>
- Keep opening new frames and closing them.

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
memory consumption sky-rockets.

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>
vanilla and doom emacs sustain constant memory usage under the same test.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3747afb4b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by natask** [comment]
here is the profiler report.

- command-execute                                       5,272,073,586  74%
 - call-interactively                                   5,271,840,128  74%
  - funcall-interactively                               4,065,447,187  57%
   + helm-M-x                                           1,855,736,332  26%
   + lazy-helm/spacemacs/report-issue                     888,659,493  12%
   + evil-mouse-drag-region                               690,772,207   9%
   + mwheel-scroll                                        411,820,064   5%
   + helm-spacemacs-help-layers                           212,838,311   3%
   + evil-ex-search-forward                                 4,499,007   0%
   + evil-delete-backward-char-and-join                       196,616   0%
   + profiler-report-toggle-entry                             191,513   0%
     left-char                                                152,556   0%
     right-char                                               152,556   0%
   + evil-next-line                                            92,600   0%
   + handle-delete-frame                                       76,361   0%
   + mouse-set-point                                           74,968   0%
   + evil-previous-line                                        67,312   0%
   + handle-focus-in                                           41,184   0%
   + self-insert-command                                       24,288   0%
   + evil-ex-search-next                                       13,552   0%
   + mouse-drag-region                                          9,416   0%
   + mouse-yank-primary                                         3,403   0%
   + file-notify-handle-event                                   2,104   0%
   + evil-force-normal-state                                    2,048   0%
   - evil-insert                                                2,048   0%
    + if                                                        2,048   0%
   + evil-shift-right-line                                      1,296   0%
   + handle-switch-frame                                        1,056   0%
  - byte-code                                           1,206,386,605  17%
   - helm-M-x-read-extended-command                     1,206,383,437  17%
    + helm-comp-read                                    1,206,381,325  17%
 + autoload-do-load                                           170,138   0%
- tooltip-show-help-non-mode                              726,909,199  10%
 + replace-regexp-in-string                                   546,276   0%
 + message                                                      7,416   0%
- linum-update-current                                    592,198,500   8%
 - linum-update                                           592,179,492   8%
  - mapc                                                  592,152,036   8%
   - linum-update-window                                  591,825,300   8%
      linum--face-width                                     1,127,576   0%
    + window-end                                              132,800   0%
      line-number-at-pos                                       41,184   0%
    get-buffer-window-list                                     21,120   0%
+ redisplay_internal (C function)                         297,222,224   4%
- timer-event-handler                                     104,718,883   1%
 - apply                                                  104,599,547   1%
  - savehist-autosave                                      95,542,857   1%
   - savehist-save                                         93,347,027   1%
    + savehist-printable                                      399,526   0%
    + run-hooks                                                19,638   0%
      generate-new-buffer                                      11,666   0%
    + #<compiled 0x16bbca9>                                     6,693   0%
    + called-interactively-p                                    1,056   0%
  + sp-show--pair-function                                  8,798,522   0%
  + auto-revert-buffers                                        78,070   0%
  + evil-ex-hl-do-update-highlight                             59,136   0%
    jit-lock-context-fontify                                   33,792   0%
  + #<compiled 0x280563>                                       30,002   0%
  + hl-paren-highlight                                         29,480   0%
  + evil-visual-update-x-selection                                232   0%
 + timer-activate-when-idle                                    84,480   0%
 + timer-inc-time                                              14,784   0%
 + timer-activate                                              11,616   0%
   timer-until                                                  7,392   0%
+ mouse-fixup-help-message                                 43,007,304   0%
+ winner-save-old-configurations                            1,606,512   0%
+ evil-normal-post-command                                  1,216,168   0%
+ evil-escape-pre-command-hook                              1,106,752   0%
+ evil-visual-post-command                                    255,160   0%
+ xselect-convert-to-string                                   249,904   0%
+ xselect-convert-to-targets                                  222,024   0%
+ evil-activate-visual-state                                  108,232   0%
+ ...                                                          88,300   0%
+ evil-activate-visual-state                                   74,864   0%
+ which-key--hide-popup                                        71,808   0%
+ evil--jump-hook                                              62,008   0%
+ evil-activate-visual-state                                   23,916   0%
+ evil-repeat-post-hook                                        23,112   0%
+ evil-activate-visual-state                                   21,884   0%
+ evil-activate-visual-state                                   21,804   0%
+ hl-paren-initiate-highlight                                  21,120   0%
+ evil-visual-pre-command                                      20,224   0%
+ evil-activate-visual-state                                   19,780   0%
+ evil-activate-visual-state                                   18,724   0%
+ evil-activate-visual-state                                   18,708   0%
+ sp--save-pre-command-state                                   17,952   0%
+ evil-activate-visual-state                                   16,776   0%
+ evil-activate-visual-state                                   15,580   0%
+ evil-activate-visual-state                                   14,672   0%
+ evil-activate-visual-state                                   13,616   0%
+ evil-activate-visual-state                                   12,648   0%
+ evil-activate-visual-state                                   12,640   0%
+ evil-activate-visual-state                                   12,324   0%
+ evil-activate-visual-state                                   10,536   0%
+ evil-activate-visual-state                                   10,536   0%
+ evil-activate-visual-state                                   10,528   0%
+ undo-auto--add-boundary                                       9,504   0%
+ mouse--down-1-maybe-follows-link                              8,448   0%
+ evil-activate-visual-state                                    8,448   0%
+ evil-activate-visual-state                                    8,448   0%
+ evil-activate-visual-state                                    8,188   0%
+ eldoc-schedule-timer                                          6,336   0%
+ eldoc-pre-command-refresh-echo-area                           6,168   0%
+ evil-repeat-pre-hook                                          4,208   0%
  sp--post-command-hook-handler                                 3,168   0%
+ global-hl-line-highlight                                      1,056   0%
+ global-eldoc-mode-check-buffers                               1,056   0%
+ global-anzu-mode-check-buffers                                1,056   0%
+ global-vi-tilde-fringe-mode-check-buffers                     1,056   0%
+ evil-activate-visual-state                                    1,056   0%
+ #<compiled 0x121474d>                                         1,056   0%

**Comment by henriquenj** [comment]
Maybe you can get a report from the `memory-usage` package (available on elpa), which generates a per-buffer overview of memory usage. It might be restricted to a given major mode.

**Comment by eshom** [comment]
Maybe this is related? I'm experiencing a possible memory leak. Quite often, after using the ESS layer for a while, the memory usage remains very high even after closing all previously used buffers and processes.
I use ESS mainly to run an R and create/test package. I usually notice high memory usage after testing a package for a while.

Another thing to note, this happens when I'm running sapcemacs as a daemon: `emacs --bg-daemon`. I haven't checked if it happens when you start spacemacs normally.

I'm sorry for wasting your time if this issue is not related to spacemacs, but to the ESS package. I wasn't sure.

Sys info:
OS: gnu/linux
Emacs: 27.1
Spacemacs: 0.300.0
Spacemacs branch: develop (rev. eccdcbb1d)
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm
Layers: ESS

Profiler output:
```
- command-execute                                         313,477,653  72%
 - call-interactively                                     313,471,196  72%
  - funcall-interactively                                 221,591,265  51%
   - spacemacs/helm-M-x-fuzzy-matching                    212,096,260  48%
    - let                                                 212,096,260  48%
     - call-interactively                                 212,093,188  48%
      - funcall-interactively                             212,093,172  48%
       - helm-M-x                                         212,093,172  48%
        - helm-M-x-read-extended-command                  212,093,172  48%
         - helm                                           211,512,068  48%
          - apply                                         211,511,044  48%
           - helm                                         211,511,044  48%
            - apply                                       211,511,044  48%
             - helm-internal                              211,511,044  48%
              - helm-read-from-minibuffer                 178,636,751  41%
               - read-from-minibuffer                     167,799,039  38%
                - command-execute                         152,506,861  35%
                 - call-interactively                     152,505,805  35%
                  - funcall-interactively                 152,505,581  35%
                   - helm-next-line                       152,125,493  35%
                    - helm--next-or-previous-line         152,125,493  35%
                     - helm-move-selection-common         152,125,493  35%
                      - helm-display-mode-line            151,991,413  35%
                       - apply                            151,991,413  35%
                        - ad-Advice-helm-display-mode-line   151,991,413  35%
                         - #<compiled 0x1560c06a7c81>     151,980,853  35%
                          - helm--set-header-line             443,489   0%
                           - #<compiled 0x1560c02590a9>       150,464   0%
                            - internal--after-with-selected-window       150,464   0%
                             - select-window                  150,464   0%
                              - apply                         150,464   0%
                               - ad-Advice-select-window       150,464   0%
                                - evil-refresh-cursor         150,464   0%
                                 - evil-set-cursor            149,408   0%
                                    evil-set-cursor-color       149,408   0%
                             end-of-visual-line                69,760   0%
                           - regexp-opt                        56,252   0%
                            - regexp-opt-group                 41,652   0%
                             - regexp-opt-group                18,684   0%
                                mapcar                         10,284   0%
                             - mapcar                           9,432   0%
                                #<compiled 0x1560d4513c91>         4,192   0%
                           - replace-regexp-in-string          42,928   0%
                              apply                            24,040   0%
                             helm-window                        4,224   0%
                             helm-set-default-prompt-display         1,056   0%
                      + select-window                         133,024   0%
                        helm-log-run-hook                       1,056   0%
                   + helm-previous-source                     378,480   0%
                   + self-insert-command                        1,368   0%
                   + helm-confirm-and-exit-minibuffer             240   0%
                + timer-event-handler                       9,037,369   2%
                + redisplay_internal (C function)           4,942,388   1%
                + helm--update-header-line                     66,528   0%
                + minibuffer-inactive-mode                     52,712   0%
                + #<compiled 0x1560c045c4d9>                    5,312   0%
                + winner-save-unconditionally                   5,192   0%
                + evil-escape-pre-command-hook                  3,812   0%
                + winum--update                                 2,080   0%
                + global-spacemacs-leader-override-mode-check-buffers         1,056   0%
                + global-hl-todo-mode-check-buffers             1,056   0%
                + global-spacemacs-whitespace-cleanup-mode-check-buffers         1,056   0%
                + global-flycheck-mode-check-buffers            1,056   0%
                  flycheck-pos-tip-hide-messages                1,056   0%
                + which-key--hide-popup                         1,056   0%
               + helm-update                                9,105,259   2%
               + helm-get-candidate-number                     20,064   0%
               + thing-at-point                                 2,074   0%
              + helm-display-buffer                        24,780,059   5%
              + helm-execute-selection-action               8,026,836   1%
              + helm-initialize                                56,842   0%
              + #<compiled 0x1560bfbad3e5>                     10,556   0%
            helm-parse-keys                                     1,024   0%
         + helm-make-source                                   580,864   0%
         + run-at-time                                            240   0%
     + add-to-list                                              3,072   0%
   + helm-buffers-list                                      7,533,684   1%
   + kill-buffer                                            1,502,129   0%
   + profiler-report-toggle-entry                             251,656   0%
   + evil-previous-line                                       106,592   0%
   + evil-next-line                                            88,288   0%
   + evil-forward-char                                          7,304   0%
   + evil-backward-char                                         1,216   0%
  + #<compiled 0x1560cda0b209>                             91,875,707  21%
+ timer-event-handler                                      99,254,325  22%
+ redisplay_internal (C function)                          20,673,016   4%
+ winner-save-old-configurations                              219,824   0%
+ evil-escape-pre-command-hook                                 47,100   0%
  evil--jump-hook                                              16,544   0%
+ tooltip-show-help-non-mode                                   10,362   0%
+ evil-repeat-post-hook                                         7,296   0%
+ evil-repeat-pre-hook                                          6,232   0%
+ which-key--hide-popup                                         5,069   0%
  mouse-fixup-help-message                                      4,328   0%
+ global-font-lock-mode-check-buffers                           3,168   0%
+ evil-mode-check-buffers                                       3,168   0%
+ yas-global-mode-check-buffers                                 3,168   0%
  evil--jump-handle-buffer-crossing                             3,168   0%
+ global-eldoc-mode-check-buffers                               3,168   0%
+ global-anzu-mode-check-buffers                                3,168   0%
+ global-spacemacs-whitespace-cleanup-mode-check-buffers         3,168   0%
+ global-flycheck-mode-check-buffers                            2,112   0%
+ global-page-break-lines-mode-check-buffers                    2,112   0%
+ global-undo-tree-mode-check-buffers                           1,056   0%
+ undo-auto--add-boundary                                       1,056   0%
  flycheck-pos-tip-hide-messages                                1,056   0%
+ global-evil-surround-mode-check-buffers                       1,056   0%
+ global-spacemacs-leader-override-mode-check-buffers           1,056   0%
+ global-hl-todo-mode-check-buffers                             1,056   0%
+ global-display-line-numbers-mode-check-buffers                1,056   0%
+ global-hl-line-highlight                                        960   0%
  ...                                                               0   0%
```

**Comment by lebensterben** [comment]
you can detect memory leak with valgrind
