### ISSUE TITLE
No autocomplete when clicking right arrow in `treemacs-add-project` and other

### ISSUE THREAD

**Issue by Asalle** [syl20bnr/spacemacs#12874]
#### Description :octocat:
No autocomplete when clicking right arrow

#### Reproduction guide :beetle:
- Start Emacs
- open treemacs
- `treemacs-add-project` or `ctrl-c ctrl-p a`
- start typing a name of a folder
- click right arrow to autocomplete the name of the folder

![treemacs-add-project-bug](https://user-images.githubusercontent.com/4975074/67747489-1c7bf680-fa29-11e9-96af-f341cbc1ca9e.gif)

Same behaviour can be seen with `helm-find-files`, that is why I think it is spacemacs' bug and not treemacs' or helm's. The bug cannot be reproduced in vanilla emacs.

![helm-find-files-bug](https://user-images.githubusercontent.com/4975074/67747498-2140aa80-fa29-11e9-8bf9-7623a57e8bdd.gif)

*Observed behaviour:* :eyes: :broken_heart:
*Messages* says `funcall-interactively: End of buffer [4 times]`, no autocompletion.

*Expected behaviour:* :heart: :smile:
I would expect treemacs to autocomplete the name of the folder and display its contents in the buffer below.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fdd38eec9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml
 (rust :variables rust-format-on-save t rust-backend lsp)
 html
 (markdown :variables markdown-live-preview-engine 'vmd)
 helm auto-completion better-defaults emacs-lisp git lsp
 (org :variables org-want-todo-bindings t)
 (go :variables go-backend 'lsp go-use-golangci-lint t go-format-before-save t go-tab-width 3)
 treemacs
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2

#### Backtrace :paw_prints:
```
funcall-interactively: End of buffer [4 times]
```

**Comment by Alexander-Miller** [comment]
It doesn't work because the left/right arrow keys move your cursor. Has it *ever* worked like you describe? AFAIR selection was always done with TAB and C-h + C-l.

**Comment by Asalle** [comment]
Not in spacemacs, a friend of mine showed me this in emacs (in open file).

**Comment by Asalle** [comment]
TAB gives me `orgmode/` with `helm-treemacs-open-project`, works as expected with `helm-find-files`.
`C-h + C-I` just executes `C-h` (go one level up)

**Comment by Asalle** [comment]
just to be clear: in helm-treemacs-open-project neither TAB or `C-h + C-I` give the expected result (autocompletion).
TAB: says `Can't split side window or a parent of side window`
`C-h+C-I` does what `C-h` would do, i. e. go one level up

**Comment by duianto** [comment]
At least two `cannot split side window` issues have been fixed upstream in the `helm` package.
- One of them occurred when `SPC f f` were called from Neotree or Treemacs.
- The other when opening `SPC f f` when there was a Help buffer open.

Are your packages up to date?

**Comment by Asalle** [comment]
thank you @duianto !
it works after update

For those who have the same issue:
on the statrtup page click `[Update packages]`.
