### ISSUE TITLE
Modeline in terminal window steals highlighting when using ivy to change buffers in other window

### ISSUE THREAD

**Issue by dmusican** [syl20bnr/spacemacs#12879]
#### Description :octocat:
Modeline in terminal window steals highlighting when using ivy to change buffers in other window.

#### Reproduction guide :beetle:
- Start Emacs
- Make sure ivy layer is enabled
- [SPC w 2] to open up two windows side-by-side
- [SPC 2] to go to second window
- M-x ansi-term
- [SPC 1] to go back to first window, ovserve that modelne in first window is highlighted
- Use ivy-switch-buffer to change buffers in first window
- Observe that focus remains in first window (as it should), but the modeline is highlighted in the second window.

*Observed behaviour:* :eyes: :broken_heart:
Modeline in second window, when a terminal is running it, steals highlighting (which is bad) but not focus (which is good).

*Expected behaviour:* :heart: :smile:
Highlighting on modeline should remain for first window.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. fdd38eec9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(racket csv
        (auto-completion :variables auto-completion-complete-with-key-sequence "jk" :disabled-for org git)
        better-defaults c-c++ emacs-lisp git html ivy java
        (latex :variables latex-build-command "LatexMk" latex-enable-auto-fill t latex-enable-folding t)
        markdown multiple-cursors org pdf python
        (shell :variables shell-default-height 30 shell-default-width 50 shell-default-position 'right shell-default-shell 'ansi-term)
        spell-checking syntax-checking treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Confirmed.

<details><summary>
System Info, Click to expand
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 968c4fa70)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion c-c++ emacs-lisp git ivy lsp markdown multiple-cursors org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>
