### ISSUE TITLE
Extra space after symbols in lsp-treemacs-symbol window

### ISSUE THREAD

**Issue by pavlosun** [syl20bnr/spacemacs#12880]
![Screenshot from 2019-10-30 23-52-12](https://user-images.githubusercontent.com/11482899/67920265-9c14dd00-fb71-11e9-8929-1c293f360f37.png)
#### Description :octocat:
After lsp-treemacs-symbol is called, the corresponding window presented. Everything is ok,
all symbols in place. However, they all separated from each other by an extra line. 

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Extra line after the symbols

*Expected behaviour:* :heart: :smile:
No extra line after the symbol. They should go one by one.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 383da46e3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory
                  '("~/.emacs.d/elpa/develop/yasnippet-snippets-20191010.1106/snippets" "~/.emacs.d/private/snippets"))
 emacs-lisp git org spell-checking syntax-checking semantic version-control yaml html dap
 (lsp :variables lsp-enable-snippet t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c-or-c++-mode c-c++-backend 'lsp-ccls c-c++-adopt-subprojects t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

**Comment by Alexander-Miller** [comment]
Looks like a consequence of `treemacs-space-between-root-nodes`. Maybe lsp should locally set it to nil in views like these?

ping @yyoncho

**Comment by yyoncho** [comment]
Make sense. I will fix this on lsp-treemacs side.

**Comment by yyoncho** [comment]
Pushed a fix into lsp-treemacs. This can be closed now.
