### ISSUE TITLE
Haskell: completion with intero broken

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#12889]
#### Description :octocat:

`intero` doesn't to work as expected in the Haskell layer

#### Reproduction guide :beetle:
- Configure Haskell layer to use `intero` as `completion-back-end`
- Start Emacs
- Open a Haskell source file in a project using `stack`

*Observed behaviour:* :eyes: :broken_heart:

- an error is reported from flycheck `File local-variables error: (wrong-type-argument stringp nil)`
- nothing happens, Emacs freezes (but can be brought back with `C-g`) when trying to get type at point

*Expected behaviour:* :heart: :smile:

A few days ago `intero` worked just fine, I'd really like it to go back to that state :)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. 9606dd344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash docker evil-commentary evil-snipe git github gtags
 (helm :variables helm-no-header t)
 mu4e restclient spacemacs-layouts
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking templates
 (clojure :variables clojure-enable-sayid t clojure-enable-clj-refactor t)
 dhall emacs-lisp
 (haskell :variables haskell-completion-backend 'intero haskell-process-type 'stack-ghci)
 python shell-scripts graphviz html json latex markdown
 (org :variables org-enable-reveal-js-support t org-enable-github-support t)
 spacemacs-org
 (sql :variables sql-auto-indent nil)
 pandoc terraform yaml archlinux clipboard-fix)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by magthe** [comment]
Oh, I should add that `pgrep -a intero` shows that `intero` _is_ started.

**Comment by radrow** [comment]
I can confirm the issue. Also

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\." nil 0)
  split-string(nil "\\.")
  intero-ghci-output-flags()
  intero-start-process-in-buffer(#<buffer  intero:backend:latte /home/radek/Programowanie/Haskell/projects/latte> nil #<buffer StdLib.hs> nil)
  intero-get-worker-create(backend nil #<buffer StdLib.hs> nil)
  intero-restart()
  funcall-interactively(intero-restart)
  call-interactively(intero-restart nil nil)
  command-execute(intero-restart)

```

**Comment by duianto** [comment]
Confirmed.

But Spacemacs doesn't freeze for me.

The process-list `SPC a p` shows:
```
stack           8232    run      intero:back... --           stack ghci --with-ghc C:\Users\username\AppData\Roaming\stack\compiler-tools\x86_64-windows\ghc-8.6.5\bin/intero --docker-run-args=--interactive=true --no-build --no-load --ghci-options -ignore-dot-ghci
```

The messages buffer shows:
>Disabling interactive-haskell-mode ...
Booting up intero ...
File local-variables error: (wrong-type-argument stringp nil)


It might be an upstream issue in flycheck.
Because here's a recent thread with the same error message that doesn't mention Spacemacs.
https://stackoverflow.com/questions/59058854/intero-error-wrong-type-argument-stringp-nil
>(wrong-type-argument stringp nil)

### Notes

It seems like intero is looking for new maintainers.

>The intero project has reached the end of its life cycle. 🌇
>
>I will not be maintaining it any longer.
Minimal pull requests will be accepted for a few months.
After which, I will archive the project.
If an individual or group would like to fork take over the project, they are welcome to do so. I will update this README to point to those alternatives.

https://github.com/chrisdone/intero

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ccd6c48d4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log debug emacs-lisp git
            (haskell :variables haskell-completion-backend 'intero)
            helm html javascript markdown multiple-cursors
            (org :variables org-agenda-files
                 '(("c:/Users/username/org/notes.org")))
            php python shell spell-checking syntax-checking themes-megapack treemacs typescript version-control vue)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by radrow** [comment]
The funny thing is it _sometimes_ works, but rarely and I can't find the rule

**Comment by radrow** [comment]
Does the problem occur with dante instead of intero?

**Comment by magthe** [comment]
This is most likely unrelated, but I just need to whinge a little :grin: 

I'm having other issues with _haskell-mode_ right now too. The hook `haskell-mode-hook` isn't always running which means that not even LSP works in all cases :disappointed:

**Comment by radrow** [comment]
Dante works very well (despite missing some functionalities). It can be a temporary workaround

**Comment by magthe** [comment]
> Dante works very well (despite missing some functionalities). It can be a temporary workaround

I did try it, but found it a very poor replacement. In particular I never got it to ever show me the type of anything :disappointed: 

In the meantime, and quite possibly as a permanent replacement, I'm trying out LSP.
