### ISSUE TITLE
new display-fill-column-indicator-mode in emacs 27

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#12884]
FYI: `fci-mode` is unmaintained and will be replaced in emacs 27 by `display-fill-column-indicator-mode`:
https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/display-fill-column-indicator.el

**Comment by duianto** [comment]
Support for Emacs 27's `display-fill-column-indicator-mode` has been implemented on the `develop` branch.
Added support for native fill column indicator in Emacs 27+ #13071
