### ISSUE TITLE
spacemacs/toggle-auto-completion broken

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#1289]
`spacemacs/toggle-auto-completion` is broken.  When trying to toggle auto completion, I get `Symbol's value as variable is void: auto-completion-front-end`.  It checks for `auto-completion-front-end` which doesn't seem to get set.

Relevant file: https://github.com/syl20bnr/spacemacs/blob/develop/contrib/auto-completion/funcs.el

I suppose the solution would be to set that variable in `config.el` for the `auto-completion` layer, but I'm not sure if that's how it was supposed to work as designed.

**Comment by syl20bnr** [comment]
Thank for the report I'm going to fix it.

**Comment by syl20bnr** [comment]
so 20 days later it is fixed in develop :-)

**Comment by darkfeline** [comment]
Confirmed fixed.

**Comment by hiphoox** [comment]
When are you going to promote it to master? Or what it is the better way to get the update?

**Comment by syl20bnr** [comment]
I will push it in a few hours.

**Comment by syl20bnr** [comment]
@hiphoox Thank you for mentioning this fix. It is available on the master branch in version 0.101.4

**Comment by hiphoox** [comment]
@syl20bnr Thanks!!
