### ISSUE TITLE
High cpu load for evil mode commands

### ISSUE THREAD

**Issue by pavlosun** [syl20bnr/spacemacs#12895]
#### Description :octocat:
Freshly started system. Freshly opened spacemacs. Typing comands like `x`, `dd`, `dw`
hang my spacemacs instance with 100% cpu load. I can abort this by typing C-g. Moving
towards insert mode using `i` works ok. 

#### Reproduction guide :beetle:
- Start Emacs
- type `x`, `dd`, `dw`

*Observed behaviour:* :eyes: :broken_heart:
See description above

*Expected behaviour:* :heart: :smile:
No cpu load and better response with evil-mode commands

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 08fdb02d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory
									'("~/.emacs.d/elpa/develop/yasnippet-snippets-20191010.1106/snippets" "~/.emacs.d/private/snippets"))
 (python :variables python-backend 'anaconda)
 emacs-lisp git org spell-checking syntax-checking semantic version-control yaml html dap
 (lsp :variables lsp-enable-snippet t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c-or-c++-mode c-c++-backend 'lsp-ccls c-c++-adopt-subprojects t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

Please provide any guide on how I can debug this behavior? 

UPDATE: 
Running profiler-start I got the following report:
```
+ command-execute                                                2324  85%
+ redisplay_internal (C function)                                 262   9%
+ timer-event-handler                                              51   1%
+ ...                                                              41   1%
+ evil--jump-hook                                                  17   0%
+ evil-repeat-post-hook                                             5   0%
+ winner-save-old-configurations                                    4   0%
+ evil-escape-pre-command-hook                                      3   0%
+ evil-repeat-pre-hook                                              2   0%
  global-hl-line-maybe-unhighlight                                  1   0%
```

**Comment by duianto** [comment]
I tested it with your layer configurations and Spacemacs remains responsive, when `x`, `dd` or `dw` are pressed several times in `.spacemacs`.

#### System Info
On the latest commit on the `develop` branch with updated packages.

<details><summary>
Pop!_OS 19.10 (Virtualbox guest with Windows 1903 as host)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 195ba3357)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory
                  '("~/.emacs.d/elpa/26.3/develop/yasnippet-snippets-20191010.1106/snippets" "~/.emacs.d/private/snippets"))
 (python :variables python-backend 'anaconda)
 emacs-lisp git org spell-checking syntax-checking semantic version-control yaml html dap
 (lsp :variables lsp-enable-snippet t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c-or-c++-mode c-c++-backend 'lsp-ccls c-c++-adopt-subprojects t))
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 195ba3357)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory
                  '("~/.emacs.d/elpa/26.3/develop/yasnippet-snippets-20191010.1106/snippets" "~/.emacs.d/private/snippets"))
 (python :variables python-backend 'anaconda)
 emacs-lisp git org spell-checking syntax-checking semantic version-control yaml html dap
 (lsp :variables lsp-enable-snippet t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c-or-c++-mode c-c++-backend 'lsp-ccls c-c++-adopt-subprojects t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by pavlosun** [comment]
Last time I was editing meson.build file. Could it be related to the file type? Is there any way for me to debug this and provide more information?

**Comment by duianto** [comment]
I found this sample `meson.build` file:
https://github.com/kstenerud/meson-examples/blob/master/executable/meson.build

I'm not seeing any delays there either.

You could try to comment out your configurations.
If that doesn't help, then try a fresh clone of Spacemacs (backup your setup first).

**Comment by duianto** [comment]
This issue might be the same or similar to this one:
Some commands, like `dd`, cause emacs to enter in a stuck state #6752
