### ISSUE TITLE
Startup screen inserted into a file

### ISSUE THREAD

**Issue by Apromixately** [syl20bnr/spacemacs#12896]
#### Description :octocat:
Parts of the startup screen are inserted into a file of mine.

#### Reproduction guide :beetle:
I am not sure how to reproduce this but here is what I think is happening:
- I have a file kb.org which has recovery information.
- This file is also in my path for org-agenda-files.
- My startup screen is configured to display org-todo items.
- When starting up emacs I get an empty startup screen. It seems it is trying to figure out the todo items for the startup screen but fails because of the recovery information.
- When opening kb.org somehow the previous process is continued and now the rest of the startup screen is pasted in there.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e4c8cef41)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust python auto-completion emacs-lisp git helm markdown multiple-cursors org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      treemacs version-control html ranger)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
I haven't been able to reproduce the startup screen contents being inserted into a file.

And the Spacemacs home buffer `todos` section is loading without issues for me if the `notes.org` file has a recovery file and the path to `notes.org` is defined in the `org` layer variable: `org-agenda-files`

But I stumbled over a case where it looks like the Spacemacs buffer is empty.

I opened a separate issue for it:
org-agenda-files with incorrect path and dotspacemacs startup-lists todos section #12907

---

I was able to create a recovery file by making a change to `notes.org` and restarting with either:
`SPC q r` or `SPC q R`.

A prompt appears asking to save the file.
I pressed: `n` (skip)

Now a prompt appears stating that there are modified buffers, exit anyway?:
I pressed: `y`

#### System Info

<details><summary>
Pop!_OS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 729ad60b2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion c-c++ emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 php python
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 729ad60b2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion emacs-lisp git ivy latex
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 python spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by Apromixately** [comment]
@duianto I was trying to use your method but somehow I don't get a recovery file. At least not one that will prompt me to restore things when I open the file again.
Any other ideas for creating one?

**Comment by duianto** [comment]
My initial assumption that it was a recovery file, was incorrect.
It might have come from the message in the minibuffer (and in the messages buffer):
>abc.txt has auto save data; consider M-x recover-this-file

that appears when the file is opened after restarting Spacemacs.

It's an auto-save file, that's stored in:
`c:/Users/username/.emacs.d/.cache/auto-save/site/`

as: ` #c!!Users!username!Temp!abc.txt#`

The auto-save file seems to be created from the temporary file: `.#abc.txt`
the temporary file is created when one starts editing a file: `abc.txt`

I edited the file without saving it, and force closed Spacemacs (task manager, end process).

The temporary file: `.#abc.txt` remained in the original files location until Spacemacs was restarted, then Emacs probably found the temporary file and stored it in the auto-save directory.

I don't know how to create a recovery file that will show a prompt when a file is opened.

**Comment by Apromixately** [comment]
It seems using a virtual machine and powering it off might work for reproduction!
