### ISSUE TITLE
Layer specific configuration / Layers with same name?

### ISSUE THREAD

**Issue by JP-Ellis** [syl20bnr/spacemacs#1290]
I have recently discovered Spacemacs and you guys have done a really great job; however, I was a little unsure as to what is the standard procedure for modifying an existing layer and the documentation isn't very clear on that (unless I've missed it).  For example, can I create a new layer in `private/` and does spacemacs merge them nicely?  Or should I copy the layer in `contrib/` to `private/` and then make the modifications?  Or is it best to fork spacemacs and then edit the layer in `contrib/`?

In particular, I'm interested in modifying the AucTeX layer and adding a few improvements of my own; for example, I would like to add support for latexmk, `SPC m \` to use AucTeX's command completion/insertion, support for evince with synctex, etc...

**Comment by syl20bnr** [comment]
You can create a private layer with a different name and add it to your dotfile.
You can extend a configuration by defining a funcion `<layer>/post-init-<package>`.

For instance if you want to extend `auctex` which is configured with the function [auctex/init-auctex](https://github.com/syl20bnr/spacemacs/tree/develop/contrib/auctex/packages.el#L9) you can define a private layer called `my-auctex` where you add `auctex` package to `my-auctex-packages` variable and define your configuration in `my-auctex/post-init-auctex`.

Wrap your configuration in an `eval-after-load` form which delay the evaluation of its body. For instance:

```elisp
(defun my-auctex/post-init-auctex
  (eval-after-load 'auctex
    '(progn
      .....)))
```
This will assure that `'(progn ...)` will be evaluated after auctex has been loaded.

**Comment by JP-Ellis** [comment]
Curiously, what happens if two layers have conflicting names?  Does one take precedence over the other, or will it result in errors?

**Comment by syl20bnr** [comment]
The last one took precedence.
I added a check and keep the first one, so all the subsequent layers with the same name are discarded. A warning message is displayed in Messages buffer.
