### ISSUE TITLE
Error navigation in Clojure buffers doesn't work for linter errors

### ISSUE THREAD

**Issue by rakyi** [syl20bnr/spacemacs#12919]
#### Description :octocat:
Error navigation in Clojure buffers (e.g. `SPC e n`) doesn't work for linter errors/warnings.

#### Reproduction guide :beetle:
- Install Clojure layer with any linter enabled
- Start Emacs
- Open Clojure buffer with any code causing linter warning
- Try to navigate to a warning using `SPC e n`

*Observed behaviour:* :eyes: :broken_heart:
Nothing happens.

*Expected behaviour:* :heart: :smile:
Cursor moves to place in code which causes the warning.

#### Cause
We set [flycheck-standard-error-navigation](https://www.flycheck.org/en/latest/user/error-interaction.html#variable-flycheck-standard-error-navigation) to `nil` and decide whether to use Flycheck or not ourselves in `spacemacs/error-delegate`. Since Cider sets `next-error-function` right at the start, Flycheck navigation functions won't be used in cider-mode.

#### Possible solutions

1. Improve `spacemacs/error-delegate` logic.
2. Fix it upstream in Cider by not setting `next-error-function` when compilation buffer is not visible or such.
3. Set `flycheck-standard-error-navigation` to `t` and let Flycheck hook into `next-error` throwing out `spacemacs/error-delegate` and co. This would be a major change, which might be risky. It is unclear to me why there is custom handling for error navigation in the first place. Probably for a good reason, but it should be documented.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 55ea4dfee)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-return-key-behavior nil)
 (clojure :variables clojure-enable-clj-refactor nil clojure-enable-linters 'clj-kondo)
 docker emacs-lisp finance git groovy helm html
 (javascript :variables javascript-fmt-tool 'prettier node-add-modules-path t)
 lsp lua markdown nginx
 (org :variables org-enable-github-support t)
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 osx parinfer prettier purescript
 (python :variables python-backend 'anaconda python-lsp-server 'mspyls python-test-runner 'pytest python-formatter 'black)
 ranger shell-scripts
 (spell-checking :variables spell-checking-enable-auto-dictionary nil)
 sql syntax-checking treemacs typescript version-control yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by thanhvg** [comment]
Great insight! FYI this is my related PR https://github.com/syl20bnr/spacemacs/pull/12208

I like your `#3` proposal. I don't know neither why we set `flycheck-standard-error-navigation` to `nil`. To avoid risk we can flip `flycheck-standard-error-navigation` to `t` on a `cider` hook for example and that would have no effect on other layers. But if we do so how it would be when the compilation buffer comes into place?  Can`cider` produce a compilation buffer?

**Comment by rakyi** [comment]
I confirmed that this also happens in vanilla Emacs with flycheck, flycheck-clj-kondo and cider. This could be maybe solved upstream in cider, if they would provide flycheck integration.

**Comment by lebensterben** [comment]
Is this still a bug?
Have you tried lsp? https://github.com/clojure-lsp/clojure-lsp

**Comment by zane** [comment]
This is still valid!
