### ISSUE TITLE
Image rotation doesn't work with ImageMagick support

### ISSUE THREAD

**Issue by jiaming-shi** [syl20bnr/spacemacs#12914]
When major-mode is image-mode, there is a keybinding `SPC m t r` names `image-transform-rotation`. But it doesn't work, and the error message is:
```
Wrong type argument: commandp, image-transform-rotation
```
When I use describe-key, it says:
```
Symbols function definition is void: image-transform-rotation
```

Furthermore, there are two commands binding to the same key:
![image](https://user-images.githubusercontent.com/11895323/68541626-c15ce300-03dc-11ea-8171-405320a37223.png)

**Comment by RicardoMing** [comment]
Emacs version: 26.3
Spacemacs: develop branch b837c1d39705b9e03bd9922da249e4c154023a92

**Comment by csfreebird** [comment]
use command to rotate image

M-x image-transform-set-rotation
then enter degree
