### ISSUE TITLE
latex-mode-hook does not work with spacemacs/toggle-auto-fill-mode-off

### ISSUE THREAD

**Issue by concretevitamin** [syl20bnr/spacemacs#12926]
I have all these in my config,
```
  (add-hook 'LaTeX-mode-hook #'spacemacs/toggle-auto-fill-mode-off)
  (add-hook 'latex-mode-hook #'spacemacs/toggle-auto-fill-mode-off)
  (add-hook 'TeX-mode-hook #'spacemacs/toggle-auto-fill-mode-off)
  (add-hook 'tex-mode-hook #'spacemacs/toggle-auto-fill-mode-off)
```
but whenever I open a `.tex` file, `autofill-mode` still kicks in.

Inside a `.tex` file inspecting the `major-mode` variable: it is `latex-mode`.  So I'd assume the second line above would work.

Spacemacs version: Spacemacs v.0.300.0

**Comment by martin3141** [comment]
I'm having the same problem with v.0.200.13@26.3

**Comment by duianto** [comment]
There's a layer variable: `latex-enable-auto-fill`

When it's set to `nil`:
```elisp
(latex :variables latex-enable-auto-fill nil)
```
Then it seems to disable `auto-fill-mode` when a `.tex` file is opened.

It also seems possible to add the `spacemacs/toggle-auto-fill-mode-off` command to the hooks, but they have to be appended:
```elisp
      (add-hook 'LaTeX-mode-hook #'spacemacs/toggle-auto-fill-mode-off 'append)
      (add-hook 'latex-mode-hook #'spacemacs/toggle-auto-fill-mode-off 'append)
      (add-hook 'TeX-mode-hook #'spacemacs/toggle-auto-fill-mode-off 'append)
      (add-hook 'tex-mode-hook #'spacemacs/toggle-auto-fill-mode-off 'append)
```
Maybe the functions in the hook are called in order from latest to oldest, meaning that the latex layer hook:
https://github.com/syl20bnr/spacemacs/blob/5111de7d1acd7fa05448657ef439608db2e70898/layers/%2Blang/latex/packages.el#L45-L46

is called last, therefore it might be overriding any user configurations.

It's definition looks like this:
https://github.com/syl20bnr/spacemacs/blob/5111de7d1acd7fa05448657ef439608db2e70898/layers/%2Blang/latex/funcs.el#L42-L46

---

The `auto-fill-mode` docstring says:
>When ‘auto-fill-mode’ is on, the ‘auto-fill-function’ variable is
non-nil.

### `auto-fill-function`
#### Before
>auto-fill-function is a variable defined in ‘C source code’.
Its value is ‘latex//autofill’
Local in buffer main.tex; global value is nil

#### After
>auto-fill-function is a variable defined in ‘C source code’.
Its value is nil

---

The documentation for the variable seems to be backwards:
https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/latex#auto-fill
>To enable auto-fill set the variable latex-enable-auto-fill to t.

It indicates that it's only enabled when the variable is set to `t`.
But it is enabled by default and only disabled when it's set to `nil`.

The layer variable seems to have been introduced and set to `t` a while back, in this commit:
https://github.com/syl20bnr/spacemacs/commit/cfcce3efa7f9bb9123db0518ffa11129d86d48c3
>A few improvements to AucTeX:
>
> - Move function definitions from inside package.el to funcs.el;
> - Add a few variables to allow some configuration with .spacemacs;
> - Enable RefTeX support;
> - Move key-binding-prefixes to config.el (similar to git layer);
> - Use auto-fill-mode, with a environment-aware auto-fill function;
> - Provide a few additional sane defaults (some of the more "annoying"
>   ones are configurable from .spacemacs)
> - Remove `build-view` in favour of just `build` as it seemed to be
>   broken and introduce `SPC m v` to view;
> - Add support to LatexMk.

**Comment by duianto** [comment]
The documentation has been updated to state that auto-fill-mode is enabled by default.
https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/latex#auto-fill
And how to disable it.

**Comment by concretevitamin** [comment]
Thanks @duianto !
