### ISSUE TITLE
[c-c++] clangd keeps adding random headers that break compilation

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#12936]
I am using the new and shiny `c-c++` layer with `clangd` and it is a great experience! The only thing that keeps happening is that sometimes extra `#include` statements that break compilation get added without me noticing. Does anyone else notice this behaviour?

**Comment by thanhvg** [comment]
I guess that would be `cpp-auto-include` package. Can you disable it and see if the auto include is gone?

**Comment by gdkrmr** [comment]
Thanks, this is weird, looking at the `c-c++` layer, this should not happen, because I have not configured `c++-enable-organize-includes-on-save` and it is set to `nil` by default. I guess that this happens when using `SPC m r i`. I will observe this for a while. Thanks!

**Comment by gdkrmr** [comment]
I have uninstalled `cpp-auto-include` via `dotspacemacs-excluded-packages` and random headers keep getting added.

**Comment by kvaneesh** [comment]
I use `-header-insertion=never` clangd option. IIUC that is clangd trying to insert headers when it autocompletes new functions.

**Comment by nertpinx** [comment]
This is bothering me for a while. It is not the cpp-auto-include as that one adds cpp headers (even in C files). I might very well be clangd that suggests some change and it gets applied. @kvaneesh how could I make that the default, is that the `lsp-clients-clangd-args` variable? Can I tell lsp to not apply changes at all (even though I would like to keep using it for formatting), maybe just for C code?

**Comment by kvaneesh** [comment]
I am using       ` lsp-clients-clangd-args `( "--header-insertion=never" )`

**Comment by nertpinx** [comment]
I can confirm, this works for me and it also looks like it is a `clangd` issue, not really related to lsp/spacemacs.

**Comment by gdkrmr** [comment]
> I am using `lsp-clients-clangd-args`( "--header-insertion=never" )`

This seems to work, should I close the issue or should this be the default option?

**Comment by nertpinx** [comment]
@gdkrmr I'm fine with just closing it, although I can see how some people may be annoyed at default behaviour being buggy. Maybe just mentioning it in `layers/+tools/lsp/README.org` could help. I must admit, though, that I did not look there for the solution either...

**Comment by gdkrmr** [comment]
Thinking about it, this should be done by `lsp-mode`, so closing this.

**Comment by fredrikatmainspringenergy** [comment]
Same issue with:
```
(c-c++ :variables
    c-c++-backend 'lsp-ccls)
```
