### ISSUE TITLE
Limiting counsel search to a directory does not work

### ISSUE THREAD

**Issue by jvalkeejarvi** [syl20bnr/spacemacs#12939]
#### Description :octocat:
Counsel search is not limited to given directory.

#### Reproduction guide :beetle:
- Start Emacs
- Open project
- Press `<SPC> a f`  to run `spacemacs/search-ag`
- Select directory

*Observed behaviour:* :eyes: :broken_heart:
Search is done within whole project

*Expected behaviour:* :heart: :smile:
Search is limited to the given directory

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 300abd74b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html
 (lsp :variables lsp-prefer-flymake ':none)
 (javascript :variables js2-basic-offset 2 js-indent-level 2 javascript-backend 'lsp javascript-lsp-linter nil node-add-modules-path t)
 ivy
 (auto-completion :variables auto-completion-enable-help-tooltip t)
 emacs-lisp git markdown shell-scripts
 (typescript :variables typescript-backend 'tide typescript-lsp-linter nil)
 (org :variables org-want-todo-bindings t org-enable-github-support t org-enable-reveal-js-support t)
 (syntax-checking :variables syntax-checking-enable-tooltips nil syntax-checking-use-original-bitmaps t)
 (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
The following PRs (possibly modified) changes are now on the develop branch:
[spacemacs/sudo-edit] Fix sudo-edit on TRAMP & [spacemacs/counsel-search] Fix wrong initial directory #12867
