### ISSUE TITLE
nyan-mode no longer works with doom-modeline

### ISSUE THREAD

**Issue by qizwiz** [syl20bnr/spacemacs#12946]
#### Description :octocat:
`nyan-mode` no longer works with `doom-modeline`

#### Reproduction guide :beetle:
- Start Emacs
- Set `dotspacemacs-modeline-theme` to `doom`
- add `(colors :variables colors-enable-nyan-cat-progress-bar t)` to `dotspacemacs-configuration-layers`
- change buffers
- look at the *Messages* buffer

*Observed behaviour:* :eyes: :broken_heart:
- You'll see warnings about doom-modeline-segments and nyan-minimum-window-width
- no rainbow kitties :cry: 

*Expected behaviour:* :heart: :smile:
no warnings, rainbow kitties

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 22d200fba)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(systemd csv auto-completion
         (colors :variables colors-enable-nyan-cat-progress-bar t)
         command-log common-lisp csharp dap
         (dash :variables dash-docs-docset-newpath "~/.local/share/Zeal/Zeal/docsets" zeal-at-point-zeal-version "0.6.1")
         debug docker elm emacs-lisp erc erlang evernote geolocation git github gtags
         (haskell :variables haskell-completion-backend 'ghci haskell-process-type 'stack-ghci)
         helm html ibuffer imenu-list javascript lsp markdown multiple-cursors org pandoc parinfer
         (restclient :variables restclient-use-org t)
         (ruby :variables ruby-enable-enh-ruby-mode nil ruby-version-manager 'rvm ruby-test-runner 'minitest)
         ruby-on-rails search-engine
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         spacemacs-editing-visual
         (spacemacs-layouts :variables spacemacs-layouts-directory "~/.dotfiles/spacemacs-layouts/" layouts-enable-autosave t layouts-autosave-delay 1800)
         spacemacs-visual spotify sql syntax-checking syntax-checking templates themes-megapack
         (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t treemacs-use-collapsed-directories 3)
         twitter version-control
         (wakatime :variables wakatime-api-key "6ef19e49-f25b-4a1b-802f-89f81c9c0db1" wakatime-cli-path "/usr/local/bin/wakatime")
         yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

#### Comments:
This is because nyan-mode is set to location local in the colors layer. If you remove that bit, it downloads the latest nyan-mode and everything's peachy :peach:

**Comment by duianto** [comment]
There's been discussions about adding the melpa version of `nyan-mode` before, but there seems to be some modifications that only are available in the local version:
Actually download `nyan-mode' from MELPA. #12153

@robbyoconnor was part of those discussions and might have some insight into how `nyan-mode` works.
