### ISSUE TITLE
Error getting PACKAGE-DESC when attempting to install pdf-tools from github repo

### ISSUE THREAD

**Issue by rnwolf** [syl20bnr/spacemacs#12959]
#### Description :octocat:

Error getting PACKAGE-DESC when attempting to install pdf-tools from github rep.

#### Reproduction guide :beetle:
- Start Emacs
- Open op .spacemacs
- Update the additional package function, and add a line for org-pdftools.
```
dotspacemacs-additional-packages '(org-ql
                                      org-vcard
                                      helm-org-rifle
                                      (org-pdftools :location (recipe :fetcher github :repo "fuxialexander/org-pdftools" ) ))
```
- Restart spacemacs 
- Observe error message.

*Observed behaviour:* :eyes: :broken_heart:

Error message as spacemacs starts up.

```
Error getting PACKAGE-DESC: (file-missing Opening input file No such file or directory c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/packages/pdf-tools-20191031.642.tar)
```

*Expected behaviour:* :heart: :smile:

It seems that the tar file is missing.
Might this because the package owner needs to make a release?
Or is there something in the functions that spacemacs is executing that sould create this tar file and is not? 

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 300abd74b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm markdown multiple-cursors org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:

```
(Spacemacs) --> installing package: org-pdftools@dotfile... [1/1]
Cloning https://github.com/melpa/melpa.git to c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/melpa
Fetcher: github
Source: fuxialexander/org-pdftools

Cloning https://github.com/fuxialexander/org-pdftools.git to c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/org-pdftools/
Saving file c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/packages/org-pdftools-20191024.1554.el...
Wrote c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/packages/org-pdftools-20191024.1554.el
Wrote c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/packages/org-pdftools-readme.txt
Fetcher: github
Source: politza/pdf-tools

Cloning https://github.com/politza/pdf-tools.git to c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-annot.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-annot.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-cache.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-cache.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-dev.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-dev.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-history.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-history.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-info.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-info.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-isearch.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-isearch.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-links.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-links.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-loader.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-loader.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-misc.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-misc.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-occur.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-occur.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-outline.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-outline.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-sync.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-sync.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-tools.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-tools.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-util.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-util.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-view.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-view.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/lisp/pdf-virtual.el -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/pdf-virtual.el
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/README -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/README
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/Makefile -> c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/build/Makefile
c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/build/pdf-tools/server => c:/Users/rnwol/AppData/Local/Temp/pdf-toolsl1sQjj/pdf-tools-20191031.642/build/server
Wrote c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/packages/pdf-tools-readme.txt
Error getting PACKAGE-DESC: (file-missing Opening input file No such file or directory c:/Users/rnwol/AppData/Roaming/.emacs.d/.cache/quelpa/packages/pdf-tools-20191031.642.tar)
(Spacemacs) Error: 
An error occurred while installing org-pdftools (error: (wrong-type-argument package-desc nil))

```

**Comment by duianto** [comment]
I'm seeing similar error messages for the packages:
`php-extras` when enabling the `php` layer and 
`metal-mercury-mode` with the `mercury-layer` (a PR is pending to rename it to just `mercury`).

When I tested the `php` layer in Linux, then the `php-extras` package installed without any issues.

This issue seems to be the same or similar:
php-extra package fails #4849

sdwolfz mentioned seeing something similar on mac:
>I remember a similar problem on OSX, the tar available in the system was bsdtar instead of gnu tar

I have two `tar` executables:
```
C:\Users\username>where tar
C:\tools\cygwin\bin\tar.exe
C:\Windows\System32\tar.exe
```
I think I'm seeing the same error message with either `tar.exe`, because when the error first appeared, I read somewhere that it might depend on the order they are listed in the OS PATH variable, I moved up the cygwin/bin path above system32, but I'm still seeing the error message.

**Comment by zipy124** [comment]
Could this possibly be related to the fact that the pdf-tools package has been renamed to pdf?

**Comment by duianto** [comment]
It's unlikely to be related to `pdf` layer having been renamed, since it happens with packages in other layers, where the layer hasn't been renamed. And because it works in Linux. (I've only tested with the `php` layer where the `php-extras` package is installed without any issues).

**Comment by duianto** [comment]
A workaround/fix was posted by zendo in this comment: https://github.com/syl20bnr/spacemacs/issues/10566#issuecomment-451968501
>install git for windows, than add this to your config. (setq-default quelpa-build-tar-executable "C:/Program Files/Git/usr/bin/tar")

### Note:
It has to be added to the `dotspacemacs/user-init` section, it doesn't work from the `dotspacemacs/user-config` section in `.spacemacs`.

That comment is in a thread about issues with installing `php-extras` but it also worked with the `mercury` layer for me.

**Comment by firmart** [comment]
I'm just passing by, but this issue probably comes from a missing semicolon in the header (see `quelpa` or `quelpa-use-package` issues, e.g. [quelpa-use-package#14](https://github.com/quelpa/quelpa-use-package/issues/14). In the case of `pdf-tools`, the issue is already fixed. Moreover `pdf-tools` is now on MELPA.
