### ISSUE TITLE
how to remove buffers ~?

### ISSUE THREAD

**Issue by nicolas4d** [syl20bnr/spacemacs#12950]
there's ~ in buffer's left side, how to remove ~?

**Comment by jjforsythe** [comment]
Use `spacemacs/toggle-vi-tilde-fringe (SPC T ~)`

**Comment by nicolas4d** [comment]
> spacemacs/toggle-vi-tilde-fringe (SPC T ~)

thank you very mush, bor~

**Comment by jjforsythe** [comment]
No worries, please could you close this issue?

**Comment by duianto** [comment]
This page might also be helpful for anyone else finding this issue and wonders how it can be toggled off globally.
https://emacs.stackexchange.com/questions/19096/how-do-i-turn-off-spacemacs-s-tildes-on-empty-lines
