### ISSUE TITLE
Key remapping issues for evil mode

### ISSUE THREAD

**Issue by BowenWang** [syl20bnr/spacemacs#12954]
I tried to remap movement keys inside evil mode. 

The remap commands I am using are:
    (define-key evil-motion-state-map "t" 'evil-next-line)
    (define-key evil-motion-state-map "n" 'evil-previous-line)
    (define-key evil-motion-state-map "s" 'evil-forward-char)

    (define-key evil-motion-state-map "j" 'evil-motion-state-map)
    (define-key evil-motion-state-map "k" 'evil-search-next)
    (define-key evil-motion-state-map "l" 'evil-substitute)

    (define-key evil-normal-state-map "t" 'evil-next-line)
    (define-key evil-normal-state-map "n" 'evil-previous-line)
    (define-key evil-normal-state-map "s" 'evil-forward-char)

    (define-key evil-normal-state-map "j" 'evil-motion-state-map)
    (define-key evil-normal-state-map "k" 'evil-search-next)
    (define-key evil-normal-state-map "l" 'evil-substitute)

    (define-key evil-visual-state-map "t" 'evil-next-line)
    (define-key evil-visual-state-map "n" 'evil-previous-line)
    (define-key evil-visual-state-map "s" 'evil-forward-char)

    (define-key evil-visual-state-map "j" 'evil-motion-state-map)
    (define-key evil-visual-state-map "k" 'evil-search-next)
    (define-key evil-visual-state-map "l" 'evil-substitute)

    (define-key evil-operator-state-map "t" 'evil-next-line)
    (define-key evil-operator-state-map "n" 'evil-previous-line)
    (define-key evil-operator-state-map "s" 'evil-forward-char)

    (define-key evil-operator-state-map "j" 'evil-motion-state-map)
    (define-key evil-operator-state-map "k" 'evil-search-next)
    (define-key evil-operator-state-map "l" 'evil-substitute)

Everything works well in Normal mode. After I turned into Visual mode I found that when I type the key "s", it behaves as evil-substitute instead of evil-forward-char, but in visual mode, other three movement keys work well. 

Any ideas? Thanks.

**Comment by BowenWang** [comment]
I think I have figured out the reason. The problem is in evil-surround. Once I disabled this package, then the key s works correctly in visual mode. 

Any way to solve this problem(instead of disabling evil-surround)?

**Comment by BowenWang** [comment]
I think I have already figured out a solution:
(evil-define-key 'visual evil-surround-mode-map "s" 'nil)
(evil-define-key 'visual evil-surround-mode-map "l" 'evil-substitute)

But I encounter another problem when trying to remap number keys. In my own vimrc, I have a remap like:
noremap } 3
noremap 3 }

Because I am a Programmer Dvorak layout user. 

In spacemacs, I try to remap keys like:
(define-key evil-motion-state-map "3" 'evil-forward-paragraph)
(define-key evil-normal-state-map "3" 'evil-forward-paragraph)
(define-key evil-visual-state-map "3" 'evil-forward-paragraph)
(define-key evil-operator-state-map "3" 'evil-forward-paragraph)

(define-key evil-motion-state-map "}" "3")
(define-key evil-normal-state-map "}" "3")
(define-key evil-visual-state-map "}" "3")
(define-key evil-operator-state-map "}" "3")

After remaps, it seems that both "}" and "3" invoke the command evil-forward-paragraph instead of the digit argument. Is there any solution to this problem? Thanks.

**Comment by duianto** [comment]
This seems to work:
```elisp
      (keyboard-translate ?} ?3)
      (keyboard-translate ?3 ?})
```
---

It's possible to bind to multiple states at once, without having to write a definition for each state:
```elisp
(evil-define-key '(normal insert) evil-mc-key-map
  (kbd "C-M-j") #'evil-mc-make-cursor-move-next-line
  (kbd "C-M-k") #'evil-mc-make-cursor-move-prev-line)
```
source: https://github.com/syl20bnr/spacemacs/commit/6556cfc80d4ba070c7385f44f932fbe2b97c0663#diff-5cb219219266a5c2251eb821f358f6b1R36

But it might be enough to just bind the keys in `motion` state instead of for all four:
`motion`, `visual`, `normal` and `operator`

>Motion state is a bit strange. Keys bound in motion state are inherited in the normal, visual, and operator state keymaps if they are not shadowed.

source: https://github.com/noctuid/evil-guide#global-keybindings-and-evil-states

**Comment by BowenWang** [comment]
@duianto  Thanks for your reply. But the commands you post don't achieve what I am trying to do.
      (keyboard-translate ?} ?3)
      (keyboard-translate ?3 ?})

These commands swap 3 and } in all situations in Emacs. What I am trying to do is this swap only occurs in all modes in Evil mode except evil-insert.

(evil-define-key '(normal insert) evil-mc-key-map
  (kbd "C-M-j") #'evil-mc-make-cursor-move-next-line
  (kbd "C-M-k") #'evil-mc-make-cursor-move-prev-line)

I have been trying something like this, the problem is that to make this work, you need to know what commands each key are bound to. I know what the command of }, but the command of 3 is not clear to me.

In Emacs, it says that number keys run command digit-argument, but a simple 'digit-argument in remapping doesn't work, it seems you need to specify the actual number with the command, I am not sure how to do that right now.

**Comment by duianto** [comment]
Sorry about that.

I was to focused on just swapping `3` and `}`. And that seemed to work. So I suggested it.

I found this thread:
https://stackoverflow.com/questions/30266374/rebind-digits-for-normal-mode-in-evil

The second answer (+50 up votes) only seems to remap the keys when `evil-mode` is enabled (when the `evil-mode-hook` is called).

I modified it to rebind the keys on startup (when the normal state is entered).

It restores the default keys when entering insert state and rebinds them again when exiting insert state.

```elisp
      (defun custom/restore-evil-default-keys ()
        (define-key key-translation-map (kbd "}") "}")
        (define-key key-translation-map (kbd "3") "3"))

      (defun custom/remap-evil-keys ()
        (define-key key-translation-map (kbd "}") "3")
        (define-key key-translation-map (kbd "3") "}"))

      (add-hook 'evil-normal-state-entry-hook 'custom/remap-evil-keys)

      (add-hook 'evil-insert-state-entry-hook 'custom/restore-evil-default-keys)
      (add-hook 'evil-insert-state-exit-hook 'custom/remap-evil-keys)
```

**Comment by BowenWang** [comment]
These commands work pretty well in Evil mode, but seems to be just one problem. 

When I was trying to run ex command in Evil mode, let's say:
:e buffer_name 

In this case, 3 is remapped to } and } is remapped to 3. Is that possible to restore the original key map in this case?

**Comment by duianto** [comment]
It also happens in other (most/all?) prompts:
Eval: (`M-S-;`)
Helm `SPC b b`
etc.
So it might not be the correct solution.

**Comment by BowenWang** [comment]
Yes, this happens in other prompts. 

Is that possible to solve this problem? Thanks.

**Comment by duianto** [comment]
The first answer on that SO page might work:
https://stackoverflow.com/questions/30266374/rebind-digits-for-normal-mode-in-evil

I renamed the function, because it mentioned capslock which probably is specific to the author.
```elisp
      (defun custom/digit-argument-fn (digit)
        `(lambda (arg)
           (interactive "P")
           (setq last-command-event (+ ,digit ?0))
           (digit-argument arg)))

      (define-key evil-motion-state-map "}" (custom/digit-argument-fn 3))
      (define-key evil-visual-state-map "}" (custom/digit-argument-fn 3))
      (define-key evil-motion-state-map "3" 'evil-forward-paragraph)
```

It seems like the visual state needs to be defined, it's not part of the motion state map for me.

**Comment by BowenWang** [comment]
Ok, I have tried this approach. Just a simple problem. 

In operator pending mode, if you want to delete forward 3 characters, you need to type the command starting in normal mode:
d 3 l

It seems that with these remapping commands, when you type }, it actually breaks the command and start a new command. After d is typed, Evil enters operator-pending mode, the correct behavior for typing } is add 3 to d.

This can actually be bypassed by typing:
3 d l

But I am just wondering if there is any solution to this.

**Comment by BowenWang** [comment]
When you type: 
d 3 l
the correct behavior is it will delete forward 3 characters. 

But with these remapping commands, when you type }, the delete command d will be terminated. So what will happen is the cursor will be moved forward 3 characters instead of deleting.

**Comment by BowenWang** [comment]
Maybe a possible solution of this problem is to add another version definition of the function custom/digit-argument-fn for just handling operating-pending mode, but I don't know how to implement it.

**Comment by duianto** [comment]
It might require checking how https://github.com/emacs-evil/evil handles digit arguments after operators.

The `evil-delete` operator is defined here:
https://github.com/emacs-evil/evil/blob/e0e9797a2baa1608e815beec6485aa8db1703dfb/evil-commands.el#L1387

And the `evil-key-press-parser` mentions `digit-argument`:
https://github.com/emacs-evil/evil/blob/e466df1f4d2a34631c01e29a84555a00268e4405/evil-common.el#L506

It might be a starting point.

I have to get back to the backlog, but hopefully we made some progress 😄

**Comment by BowenWang** [comment]
Ok, I will try to investigate this problem.
