### ISSUE TITLE
sqlfmt-option not known by sqlfmt-executable

### ISSUE THREAD

**Issue by pepperblue** [syl20bnr/spacemacs#12952]
I'm not really sure, if this is a bug - because there are different implementations of sqlfmt ...
When I use this binary [sqlfmt-v1.1.0-linux-amd64](https://github.com/lopezator/sqlfmt/releases/download/v1.1.0/sqlfmt-v1.1.0-linux-amd64) it complains about unknown option "-u" ...
Setting `sqlfmt-options` to "--use-spaces" makes it work again

**Comment by it-is-wednesday** [comment]
I guess [`sqlfmt.el`](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/sql/local/sqlfmt/sqlfmt.el) was written with [this project](https://github.com/jackc/sqlfmt) in mind as it does have `-u` in its parameters:
```
 ~/g/bin  ./sqlfmt --help                                                                                                                    I 
usage:  ./sqlfmt [options] [path ...]
  -u    format with upper-case
  -version
        print version and exit
  -w    write result to (source) file instead of stdout
```

**Comment by it-is-wednesday** [comment]
Seems like this commit fixed it https://github.com/syl20bnr/spacemacs/commit/903ad8a8e19c777960331aeb4eff533a0db8cafe

**Comment by pepperblue** [comment]
Seems to be solved for me :-)
