### ISSUE TITLE
Setting up Python with LSP

### ISSUE THREAD

**Issue by anihm136** [syl20bnr/spacemacs#12953]
Hi. I'm having some trouble with getting lsp to work with python. Whenever I open a python buffer, an error pops up saying `Server pyls:<some number> status:starting exited with status exit.Do you want to restart it?`

I have python language server installed using pip, and lsp is working well for other languages (java, js, c-c++ ). What am I doing wrong here?

**Comment by it-is-wednesday** [comment]
Umm that's kinda vague but here's a couple of general suggestions.
Dumb solutions first: make sure you have installed the latest version, that it's available from PATH (you can run via terminal/cmd), you've restarted Emacs after installing pyls, you didn't accidentally install pyls using Python 2 pip etc.
Can you use it from other editors? Do you get any errors when simply running `pyls` in terminal?

**Comment by anihm136** [comment]
I'm able to run it in terminal. I installed it using both python 2 and 3 just in case. I'm also using it in vim with no issues. But in spacemacs, it refuses to start after numerous retries.
The strange thing is, it's working on another system of mine in spacemacs which has the same config as far as I know.

**Comment by yyoncho** [comment]
@anihm136 - check the content of the stderr buffer.

**Comment by anihm136** [comment]
Sorry I haven't replied in a while. I followed what @yyoncho said, and realised the issue was due to an unrelated package called pyls in my conda install, which was broken. Removing that and installing the actual python language server did the trick. Now I just have to figure out how to change back to my default python from conda. Thanks all!
