### ISSUE TITLE
Lisp keybindings misteriously missing from the develop branch?

### ISSUE THREAD

**Issue by equwal** [syl20bnr/spacemacs#12963]
Where is the `SPC k` prefix and friends? The prefixes are still defined in `layers/spacemacs-defaults/keybindings.el`, but the bindings are gone.

Reproduction:
Install develop branch
`SPC k`
not defined?

**Comment by duianto** [comment]
`SPC k` is bound to the `evil-lisp-state-map` when a `prog-mode` buffer is opened.

https://github.com/syl20bnr/spacemacs/blob/b243785a338e3ad3324769b3bf4b672869558261/layers/%2Bspacemacs/spacemacs-evil/packages.el#L201-L208

**Comment by equwal** [comment]
> `SPC k` is bound to the `evil-lisp-state-map` when a `prog-mode` buffer is opened.
> 
> https://github.com/syl20bnr/spacemacs/blob/b243785a338e3ad3324769b3bf4b672869558261/layers/%2Bspacemacs/spacemacs-evil/packages.el#L201-L208

Okay. This change of behaviour was causing confusion, as specified in this (your) comment [here](https://github.com/syl20bnr/spacemacs/pull/12938#pullrequestreview-318014967).

**Comment by equwal** [comment]
After testing this commit, it seems that `SPC K` works fine. Even after opening a `*scratch*` buffer and running `M-x lisp-mode` the `SPC k` smartparens prefix is not defined.

**Comment by duianto** [comment]
`lisp-mode` might not be part of the `prog-mode-hook`.
But enabling `emacs-lisp-mode` in a buffer, enables the `SPC k` `evil-lisp-state` key bindings.

**Comment by equwal** [comment]
> `lisp-mode` might not be part of the `prog-mode-hook`.
> But enabling `emacs-lisp-mode` in a buffer, enables the `SPC k` `evil-lisp-state` key bindings.
This is not the behaviour I am observing on the current dev branch.

**Comment by duianto** [comment]
Hmm, now that I was trying to replicate it again.
`M-x lisp-mode` in a new buffer `SPC b N n` does load the `SPC k` key bindings.
I don't know why it didn't work before.
But it seems to be working now.

I see now from the docstring for `lisp-mode`:
>In addition to any hooks its parent mode ‘prog-mode’ might have run,
this mode runs the hook ‘lisp-mode-hook’, as the final or penultimate step
during initialization.

So it's a prog-mode child mode.

**Comment by equwal** [comment]
> This is not the behaviour I am observing on the current dev branch.

To be clear: prog-mode is not loading the `SPC  k` keybindings for me. I'm using a very recent Emacs 27.5, and the post recent commit on the Spacemacs `dev` branch.

**Comment by duianto** [comment]
Then we weren't testing the same thing, maybe it's an issue with a very recent Emacs snapshot version.

The behavior I'm seeing was first observed in `Emacs 26.3`.

But now I downloaded the latest Windows snapshot:
`GNU Emacs 27.0.50 (build 1, x86_64-w64-mingw32) of 2019-11-11`

And I'm seeing the same thing as in `26.3`
`SPC k` is undefined until a `prog-mode` child mode is enabled.
For example: `lisp-mode` or `evil-lisp-mode` (or even `prog-mode`).

On the latest `develop` branch with updated packages.

**Comment by equwal** [comment]
> Then we weren't testing the same thing, maybe it's an issue with a very recent Emacs snapshot version.
> 
> The behavior I'm seeing was first observed in `Emacs 26.3`.
> 
> But now I downloaded the latest Windows snapshot:
> `GNU Emacs 27.0.50 (build 1, x86_64-w64-mingw32) of 2019-11-11`
> 
> And I'm seeing the same thing as in `26.3`
> `SPC k` is undefined until a `prog-mode` child mode is enabled.
> For example: `lisp-mode` or `evil-lisp-mode` (or even `prog-mode`).
> 
> On the latest `develop` branch with updated packages.

Here is my `M-x version`: `GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.11) of 2019-11-23`.

The issue only comes up on a _fresh .spacemacs_. I have the same `SPC k undefined` on my emacs 26:
`GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu)`.

So it seems to be the current dev snapshot (checkout commit 300abd74bda715c23aaeb5a90d932c0fe1343691), and not the emacs version.

**Comment by equwal** [comment]
duianto <notifications@github.com> writes:

> Then we weren't testing the same thing, maybe it's an issue with a very recent Emacs snapshot version.
>
> The behavior I'm seeing was first observed in Emacs 26.3.
>

Actually no, I believe that the issue is not related to the Emacs
version.

> But now I downloaded the latest Windows snapshot:
> GNU Emacs 27.0.50 (build 1, x86_64-w64-mingw32) of 2019-11-11
>
> And I'm seeing the same thing as in 26.3
> SPC k is undefined until a prog-mode child mode is enabled.
> For example: lisp-mode or evil-lisp-mode (or even prog-mode).
>
> On the latest develop branch with updated packages.

Yes, we are having different behaviour then. It is at least consistent
across Emacs versions, though perhaps different based on platform. I'd
like to setup a Windows VM and see if I can reproduce the behaviour you
have.

--
Spenser Truex
spensertruex.com
San Francisco, USA
