### ISSUE TITLE
Org layer: There should be a key binding to enter the org-agenda from any buffer

### ISSUE THREAD

**Issue by ocharles** [syl20bnr/spacemacs#1296]
I generally want to view the agenda when I'm *not* already editing files in my agenda. For example, I finish a piece of work and need to know what to work on next. Perhaps we could have `SPC a o`, which is currently unused?

**Comment by cpaulik** [comment]
You are right. I think there also should be a global keybinding for org-capture which I [proposed](https://github.com/syl20bnr/spacemacs/pull/1162/files#diff-c06c0f6f09ad0291af715939a963c395R109) to be `SPC C c`

**Comment by syl20bnr** [comment]
Org is so important that we can add a convention for it and give it a global key binding. Pity that `SPC o` is reserved for the user :-) We could use `SPC O` but I feel that it should be left to the user too.

Any proposal for a global prefix for all org related stuff ?

**Comment by cpaulik** [comment]
I'm not sure if a global prefix is necessary. The only commands that should be available globally are org-agenda and org-capture. Am I missing commands? All others are org buffer specific.

**Comment by moesasji** [comment]
I think you are indeed missing one more command that need to be available globally to make good use of org-mode, ie the command to store a link. From the org-manual:

>The four Org commands org-store-link, org-capture, org-agenda, and org-iswitchb should be accessible through global keys (i.e., anywhere in Emacs, not just in Org buffers). Here are suggested bindings for these keys, please modify the keys to your own liking. 

See: http://orgmode.org/org.html#Activation I think in reality only `org-capture` `org-store-link`  and `org-agenda` are still needed as I think the iswitchb has disappeared in emacs 24.4?

**Comment by ralesi** [comment]
I agree `SPC O` is a good option.  It is how I have been using my private org layer for a while now.  There are about 10 org specific bindings that I have accessible in all buffers. I will submit a PR later today for review if someone doesn't already have one started for this.

**Comment by ralesi** [comment]
Here are some bindings I can have bound:

````
      ;; use O as org global bindings
      (evil-leader/set-key
        "Oa" 'org-agenda
        "Og" 'helm-org-agenda-files-headings
        "Oo" 'org-clock-out
        "Oc" 'org-capture
        "OC" 'helm-org-capture-templates ;requires templates to be defined.
        "Ol" 'org-store-link)
````

**Comment by syl20bnr** [comment]
`SPC O` is very appealing but it is like stealing a key that is reserved to the user, I know the doc says `o` not `o` and `O`.... mmmhhh
I could add `SPC ,` to the reserve key for the user and we take `SPC O`.

**Comment by ralesi** [comment]
How about making another leader,  a localleader if you will,  for users' use.  In Vim,  I normally mapped localleader to `\`.  Granted though, this makes three leader prefix keys.

**Comment by syl20bnr** [comment]
It can be possible but it should reference a `SPC something`, like `,` leader is a remapping of `SPC m`.
So `SPC ,` could be reserved to the user and we setup `\` as a shortcut (can be modified in the dotfile). I like the idea. :-)

**Comment by BlinkD** [comment]
@syl20bnr how about `SPC o` for org mode  and `SPC .` for users' use
`SPC .` is easy to press, and no worry duplication of names.

**Comment by jasoncyu** [comment]
:+1: for `SPC .` for user use. I think `SPC ,` is a little confusing since `,` is already the major mode leader `SPC M`

**Comment by louy2** [comment]
:+1: `SPC .`

**Comment by mkaito** [comment]
:+1: `SPC .` for user, `SPC o` for global org-mode.

**Comment by emmanueltouzery** [comment]
Just a little minus: in some languages you need to press shift for .

**Comment by felipe-barros** [comment]
I agree Org deserves the `SPC o` spot and both `SPC ,` and `SPC .` are good solutions for the user space.

**Comment by mkaito** [comment]
@emmanueltouzery
> in some languages you need to press shift for `.`

Well, what is the unshifted character on that key?

**Comment by emmanueltouzery** [comment]
In the case of the french keyboard from what i see online it's ; -- don't have one in front of me now.

**Comment by mkaito** [comment]
Shouldn't `SPC ;` be pretty safe too?

**Comment by felipe-barros** [comment]
I still think `SPC .` or `SPC ,` are the best alternatives. You can't really take all the keyboard layouts into consideration, and that comes from someone using Dvorak. My `.` is your `e`. Even with the need to shift, it's still pretty easy for the poor French folks who by now are probably accustomed to entering periods. :)

**Comment by ralesi** [comment]
Where are we on this?  Does anyone even use `SPC o` for anything? Typically if I want to map a new command, I set it up in my dotspacemacs config section, so it doesn't matter what spacemacs has already set. If we were to change user reserved binding to `SPC .`, is there anything in the source that needs to be changed?

**Comment by ZucchiniZe** [comment]
Is there any progress on this issue, because I would love it as a feature!

**Comment by TheBB** [comment]
I don't think there's any official ruling on this. FWIW I don't want to move the user reserved space. I feel the few global org bindings fit well under `SPC a o` (*a* for *applications*, which the agenda certainly is). That's my proposition.

**Comment by ZucchiniZe** [comment]
`SPC a o` sounds reasonable for the agenda.

**Comment by syl20bnr** [comment]
There are other global key bindings useful for org. Agenda is one of them, but capture bindings should be global too. I think @TheBB proposes to put all org global key bindings under `SPC a o` which would give `SPC aoa` for org-agenda. Am I right ?

**Comment by ZucchiniZe** [comment]
If you put all global org bindings on `SPC a o` to get to the agenda you would have to run `SPC a o a a`.

**Comment by syl20bnr** [comment]
Why doubling the `a` ?

**Comment by TheBB** [comment]
This is what I propose.

* `SPC aoa`: agenda
* `SPC aoc`: capture
* `SPC aol`: store link
* `SPC aoO`: clock out (for example... to mirror `SPC m O`, but we could make it whatever else)
* etc.

**Comment by ZucchiniZe** [comment]
>Why doubling the `a`?

Because when using `org-agenda` it brings up a list of things to select: ![](https://alexb.io/s/q8TUo.png)

**Comment by TheBB** [comment]
Since the agenda is probably the most interesting thing, we can replicate all or most of those bindings directly on `SPC ao`, thus `SPC aoa` is agenda, `SPC aot` is todo list, etc. Maybe `SPC aoA` can be the regular agenda menu. That should still leave plenty of space to the 3-4 other global org bindings.
