### ISSUE TITLE
Shebang insertion in Org-mode codeblocks

### ISSUE THREAD

**Issue by tuxiqae** [syl20bnr/spacemacs#12965]
I would love to be able to use  `SPC i !` in-order to insert a shebang for the language in the codeblock.

So if I created a new Python codeblock - after pressing the aforementioned combo, Spacemacs would print `#!/usr/bin/env python` on the first line of the codeblock.

Currently, I just receive the error "Extension ignored", I guess it's because of the extension of the org file.

**Comment by JonathanReeve** [comment]
Could you say more about why you need shebangs within org-mode code blocks?

If I'm not mistaken about what it is you're looking for, isn't this something that can be achieved with a yasnippet snippet? Look at [the `py` snippet in the org-mode directory](https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/snippets/org-mode/python), for instance.

**Comment by tuxiqae** [comment]
To be honest I wouldn't really use it that much - but I would love to have the ability to generate complete functions using those code blocks.

P.S. I found out that they are rather helpful to me while studying - if I need to create multiple tiny algorithms I like to just open one org-mode file for the entire task and use each code block as an entire codebase (even though it's only 10-15 LOCs)

Thanks :)
