### ISSUE TITLE
[Solution](setq org-src-tab-acts-natively t) will cause issue for org-src-edit buffer

### ISSUE THREAD

**Issue by c02y** [syl20bnr/spacemacs#12967]
In case anyone has this problem:

When you are using org-mode+auto-completion, and try to expand org-src snippet like the following one using `M-/` or selecting one from drop-list of auto-completion layer, spacemacs will replace or create the other window with the same buffer you use org-src instead of the empty org-src-edit buffer, check the screenshot.
~~~
# -*- mode: snippet; -*-
# name: src-lisp
# key: <sl
# --
#+BEGIN_SRC lisp
`(org-edit-special)`
#+END_SRC
~~~

This problem is caused by `org-src-tab-acts-natively t` in https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bemacs/org/packages.el 

All you need to do is putting `(setq org-src-tab-acts-natively nil)` in your use-config part to fix this problem.

![org](https://user-images.githubusercontent.com/2135996/69228083-ecee8300-0bbd-11ea-95d3-d45eeca71845.png)

**Comment by duianto** [comment]
Thanks for posting a solution to a problem you found. ❤️

I'm sure it will be appreciated by anyone that encounters the same issue.

**Comment by orialb** [comment]
This also solved a problem for me where hitting `, c` in the org-src buffer (calling  `org-edit-src-exit` would close the buffer but leave the window open (so I would get two windows with the original org-mode buffer). 
I didn't use to have this problem before so I wonder what changed. I only recently updated Spacemacs to the latest develop (I was on earlier commit of develop before), but I see the specific `org-src-tab-acts-natively` setting was introduced 2 years ago so I had it also before in my config. 
Maybe it could be related to some changes in org-mode itself and release of Org 9.3?  Although it seems that the original issue is from before the release of org 9.3 so maybe it is unrelated.

**Comment by orialb** [comment]
> Maybe it could be related to some changes in org-mode itself and release of Org 9.3? 

To answer my own question I tested setting `(setq org-src-tab-acts-natively t)` with org 9.3 in vanilla emacs and it doesn't seem to cause any problems.

**Comment by orialb** [comment]
In any case, shouldn't this be tagged as a bug as it seems to work in vanilla emacs?

**Comment by duianto** [comment]
This is what I'm seeing:
- Open new buffer: `SPC b N n`
- Switch to org-mode: `M-x org-mode`
- Create the snippet that `c02y` suggested:
  - `M-x yas-new-snippet`
  - Replace the buffer with the snippet:
```
# -*- mode: snippet; -*-
# name: src-lisp
# key: <sl
# --
#+BEGIN_SRC lisp
`(org-edit-special)`
#+END_SRC
```
  - Save the snippet: `SPC f s`
  - Give it a name, for example: `issue-12967`
- The snippet buffer can be closed `SPC b d` 
or just switch back to the `untitled` `org-mode` buffer: `SPC TAB`
- Type: `<sl`
- Press: `M-/`

### org-src-tab-acts-natively t (Spacemacs default)

The frame splits into two windows (top and bottom),
and the minibuffer shows a prompt:
- The top window shows the previously created buffer: `untitled`
The snippet was expanded and `` `(org-edit-special)` `` was evaluted to: `t`
the buffer now contains these three lines:
```
#+BEGIN_SRC lisp
t
#+END_SRC
```
- The bottom window: `*Org Src untitled[ lisp ]*`
only has one line:
`Edit, then exit with ', c' or abort with ', k'`
- The minibuffer shows:
`Return to existing edit buffer ([n] will revert changes)? (y or n)`

![emacs_2019-12-17_16-13-30](https://user-images.githubusercontent.com/13420573/71010920-d835da00-20ec-11ea-9361-0e213691970f.png)

#### Pressing: `y`
The bottom window switches to another buffer,
possibly the last visited buffer.

#### Pressing: `n`
The bottom window shows the same `untitled` buffer as the top window.


### org-src-tab-acts-natively nil

The frame splits into two windows (top and bottom),
but there is no minibuffer prompt.
The top and bottom windows shows the same windows as above:
top: `untitled`
bottom: `*Org Src untitled[ lisp ]*`

The bottom window is selected.

![emacs_2019-12-17_16-19-42](https://user-images.githubusercontent.com/13420573/71010949-e7b52300-20ec-11ea-8893-388af3505c32.png)

#### Just pressing: `,c` without typing anything
The bottom window closes, 
and the second line is erased leaving it empty.

#### Typing: `abc`
and pressing: `,c`
The bottom window closes
and the second line is indented,
and the `t` is replaced with: `abc`


#### pressing: ,k
Closes the bottom window.


### The commit that enabled the variable: `org-src-tab-acts-natively`
org: enable org-src-tab-acts-natively https://github.com/syl20bnr/spacemacs/commit/b09fe8553d853555f5c54a6797fb3911a07866d0

@syl20bnr Do you remember why it was enabled by default?

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6f029cc05)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm
            (latex :variables)
            markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by orialb** [comment]
Thanks for taking a look at this @duianto .
I checked this again, and now I am actually seeing the (unwanted) behavior you are describing in the `org-src-tab-acts-natively t` case irregardless of the actual value of `org-src-tab-acts-natively`. 
Last time I checked this I was seeing exactly the same behavior as you in both cases so I don't know what changed.
