### ISSUE TITLE
Shell commands in org mode source code blocks on MS-Windows do not seem to be getting executed. 

### ISSUE THREAD

**Issue by rnwolf** [syl20bnr/spacemacs#12979]
#### Description :octocat:
Shell commands in org mode source code blocks on MS-Windows do not seem to be getting executed. 

#### Reproduction guide :beetle:
- Start Emacs on MS-Windows
- Create src code block   
```
#+begin_src shell
dir
#+end_src
```
and the same for

```
#+begin_src shell
C:/Users/rnwol/AppData/Roaming/getmycalendars.bat
#+end_src
```

- Execute code blacks with  `,,y`

*Observed behaviour:* :eyes: :broken_heart:

Results returned as below, for both of the above code blocks.
```
#+RESULTS:
| Microsoft                        | Windows | [Version  | 10.0.19028.1] |     |        |           |
| (c)                              |    2019 | Microsoft | Corporation.  | All | rights | reserved. |
| c:\Users\rnwol\OneDrive\orgmode> |         |           |               |     |        |           |
```

*Expected behaviour:* :heart: :smile:
For the `dir` command I expect to see list of files, in a similar way that I do when I run the code block on Ubuntu.

When I run  `SPC !` for shell commands via mini-buffer, the command runs with output displayed as expected.

On the other hand if I run the following codeblock, with a windows batch file, I can confirm that the batch file actually ran, based on files modified by it.
cmdproxy seems to be the layer between spacemacs and the OS shell when running shell src blocks.

```
#+begin_src elisp
  (call-process "cmdproxy"  nil "foo" nil "/c"  "C:/Users/rnwol/AppData/Roaming/getmycalendars.bat")
#+end_src

#+RESULTS:
: 0
```
It would be great to see the same output that I get when using `SPC !` to run a shell command, in the #+RESULTS: section after executing a shell code block. 

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a2fbb3d94)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm markdown multiple-cursors org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:
```

```

**Comment by rnwolf** [comment]
Ok it seems like I can get some thing that almost meets my needs with the following elisp command shell-command-to-string:
via https://stackoverflow.com/questions/4858975/in-emacs-lisp-what-is-the-correct-way-to-use-call-process-on-an-ls-command

```
#+begin_src elisp
(shell-command-to-string "netsh wlan show interfaces") 
#+end_src

#+RESULTS:
#+begin_example

There is 1 interface on the system: 

    Name                   : Wi-Fi
    Description            : Intel(R) Wireless-AC 9560 160MHz
    GUID                   : 2996aa1d-b3d6-4e43-b7cb-21d0c18b0b16
    Physical address       : dc:fb:48:d2:dc:ff
    State                  : connected
    SSID                   : sllflitwickwifi
    BSSID                  : c0:ea:e4:cf:30:14
    Network type           : Infrastructure
    Radio type             : 802.11a
    Authentication         : WPA-Personal
    Cipher                 : TKIP
    Connection mode        : Auto Connect
    Channel                : 48
    Receive rate (Mbps)    : 54
    Transmit rate (Mbps)   : 54
    Signal                 : 80% 
    Profile                : sllflitwickwifi 

    Hosted network status  : Not available

#+end_example

```

**Comment by duianto** [comment]
```
#+begin_src shell
dir
#+end_src
```
Showed this result:
```
#+RESULTS:
| Microsoft                                                  | Windows | [Version  | 10.0.18362.476] |     |        |           |
| (c)                                                        |    2019 | Microsoft | Corporation.    | All | rights | reserved. |
| c:\Users\username\Applications\emacs-26.3-x86_64\bin>More? |         |           |                 |     |        |           |
```

Then I found a suggestion to add an advice to the `org-babel-sh-evaluate` function.
https://emacs.stackexchange.com/a/19301

But before trying the advice tried to use `sh` as the source block instead of `shell` and now when `,,y` is pressed in the src block:
```
#+begin_src sh
dir
#+end_src
```
The results heading contains the list of files in the current directory.

### System Info

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cab1e6958)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence "jk")
 (colors :variables)
 command-log dap debug emacs-lisp git helm json java
 (javascript :variables javascript-backend 'lsp)
 markdown multiple-cursors
 (org :variables)
 (python :variables)
 react shell spell-checking syntax-checking treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by Osherz5** [comment]
If anyone else as frustrated as me arrives here, I've spent some time debugging this issue and it seems like a bug in Org, in which `org-babel-sh-evaluate` does not add a newline to the end of the buffer it is trying to evaluate.
Notice the code block cannot evaluate just the last line (in our case the ONLY line).

This is how I solved it:
Edit the file `ob-shell.el`, and replace this line
`(t (org-babel-eval shell-file-name (org-trim body) )))))`
With this
`(t (org-babel-eval shell-file-name (concat (org-trim body) "\n"))))))`
