### ISSUE TITLE
Error (use-package): dap-mode/:config: Key sequence d d d starts with non-prefix key d d

### ISSUE THREAD

**Issue by dennismayr** [syl20bnr/spacemacs#12975]
OS: Ubuntu 18.04 / elementaryOS Juno
Emacs version: 26.3 (kelleyk PPA build)
Spacemacs version: _0.300.0_ `develop` [8bb98bcff]

Enabled layers:
```elisp
     (c-c++ :variables
            c-c++-backend 'lsp-clangd)
     csv
     (dart :variables
           dart-sdk-path "~/flutter/bin/cache/dart-sdk/"
           )
     (go :variables
         go-backend 'lsp
         go-format-before-save t)
     (html :variables
           web-fmt-tool 'web-beautify
           )
     java
     (javascript :variables
                 javascript-backend 'lsp
                 javascript-repl `nodejs
                 javascript-import-tool 'import-js
                 javascript-fmt-tool 'prettier)
     (json :variables
           json-fmt-tool 'prettier)
     kotlin
     markdown
     nginx
     php
     (python :variables
             python-lsp-server 'pyls)
     react
     (rust :variables
           rust-backend 'lsp)
     shell-scripts
     sql
     (typescript :variables
                 typescript-backend 'lsp)
     windows-scripts
     yaml

     helm
     auto-completion
     better-defaults
     cmake
     dap
     debug
     docker
     emacs-lisp
     (geolocation :variables
                  geolocation-enable-automatic-theme-changer t)
     git
     github
     gtags
     import-js
     lsp
     multiple-cursors
     (treemacs :variables
               treemacs-use-collapsed-directories 3)
     (org :variables
          org-enable-github-support t
          org-enable-bootstrap-support t
          org-enable-trello-support t)
     pandoc
     prettier
     shell
     semantic
     spell-checking
     syntax-checking
     unicode-fonts
     version-control
     web-beautify
```

When opening files under any mode that involves `lsp`, I get the following message on the pop-up `Warnings` buffer:

`Error (use-package): dap-mode/:config: Key sequence d d d starts with non-prefix key d d`

So far, no functional impairment detected (not that I've used the feature extensively, though).
Just an annoyance.

**Comment by sei40kr** [comment]
Looks like key bindings in `debug` layer conflicts with `dap`.

**Comment by jidibinlin** [comment]
I have this problems too.

**Comment by jidibinlin** [comment]
Error (use-package): dap-mode/:config : Symbo`s function definition is void: dap-ui-mode

**Comment by smile13241324** [comment]
I think I have fixed this weeks ago on develop. @dennismayr care to recheck and close this issue if it works?

**Comment by dennismayr** [comment]
@smile13241324 I confirm that the error has been fixed.

There's a new error message involving `lsp` that says `Warning (emacs): Replace (require ’lsp) with (require ’lsp-mode)`, but I'll open a new issue fot it.

This issue can be closed.
Thanks for looking into it :smile:

**Comment by smile13241324** [comment]
@dennismayr thats non of our bugs, the package `cquery-common.el` is requiring lsp but should require `lsp-mode`. This should be opened upstream.

**Comment by dennismayr** [comment]
All clear then, closing.

**Comment by hyiltiz** [comment]
`Debugger entered--Lisp error: (error "Key sequence R T A B starts with non-prefix key R ...")` I am getting a similar error. How does one go about finding out which packages are clashing? `SPC h d k` didn't show anything relevant.

**Comment by smile13241324** [comment]
@hyiltiz your best bet is to do a full text search on all files in the layers directory i.e. `SPC / R\ T` which shows latex layer as the most likely candidate for the conflict.

Looks like this is caused by my lsp integration, lets see if I can fix it.

**Comment by hyiltiz** [comment]
```
> pwd
/home/hyiltiz/.emacs.d.spacemacs/layers
> rg 'R T'
+lang/latex/README.org
223:| ~SPC m r TAB~ or with LSP ~SPC m R TAB~ | reftex-index                          |
230:| ~SPC m r T~ or with LSP ~SPC m R T~     | reftex-toc-recenter                   |
```
