### ISSUE TITLE
Clarify documentation in autocomplete

### ISSUE THREAD

**Issue by mathpunk** [syl20bnr/spacemacs#12974]
Writing clear documentation is hard! But please, can someone who understands auto-complete, company, and yasnippet try and clarify this section in the docs: https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bcompletion/auto-completion#enable-company-or-auto-complete-globally

> You may want to **enable company globally** to get auto-completion everywhere even in the modes which are not configured by Spacemacs. To do so, you just have to add (global-company-mode) in the dotspacemacs/user-config function of your dotfile.

> Note that if you want **to enable auto-complete globally you will have to disable company** first, see the next section to do so.

So which is it? Should company be enabled, or disabled, to get autocompletion everywhere?

**Comment by lvh** [comment]
I think the confusion is that the layer is called `auto-completion` and there are two Emacs packages that provide auto-completion functionality: `auto-complete` and `company`.

The first quote is referring to the auto-completion layer/behavior. The second quote is referring to `auto-complete` the package.
