### ISSUE TITLE
Typing "he" quickly in some modes causes the cursor to jump and an exit from normal mode.

### ISSUE THREAD

**Issue by danielzfranklin** [syl20bnr/spacemacs#12988]
#### Description :octocat:

Typing "he" quickly in some cases causes the cursor to jump and an exit from normal mode.

#### Reproduction guide :beetle:
- Start Emacs
- Open a scratch buffer
- Set the buffer to emacs-lisp-mode or org-mode (Two I've found this occurs for, may well occur in more.)
- Type "the" repeatedly and quickly (I consistently see the error within twenty times)

*Observed behaviour:* :eyes: :broken_heart:

Observe the message "Mark set" and that the cursor moves back one and document is now in insert mode.

*Expected behaviour:* :heart: :smile:

Document remains in insert mode and the cursor isn't moved. I think this might
be a shortcut, but the is so common a word to type it should trigger on
something else if that's the case. Also, this should be documented clearer if
this is intended behavior.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm auto-completion better-defaults emacs-lisp git markdown org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spell-checking syntax-checking version-control
        (mu4e :variables mu4e-enable-notifications t mu4e-enable-mode-line t))
```
- System configuration features: XAW3D XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by equwal** [comment]
Are you on a computer with a trackpad? Is it possible that you are just activating the mouse?

Try disabling your trackpad.

**Comment by danielzfranklin** [comment]
Is moving the mouse while typing supposed to set a mark? That seems to me to be very confusing behavior. 

Disabling the trackpad fixes the issue. However, disabling my trackpad whenever I want to type in emacs doesn't seem a good solution to me. Is there a better way to solve this?

What emacs functionality getting activated, and can I disable it?

**Comment by equwal** [comment]
> Is moving the mouse while typing supposed to set a mark? That seems to me to be very confusing behavior.
> 
> Disabling the trackpad fixes the issue. However, disabling my trackpad whenever I want to type in emacs doesn't seem a good solution to me. Is there a better way to solve this?
> 
> What emacs functionality getting activated, and can I disable it?

This is not a problem with Spacemacs, it is a problem with your trackpad configuration.

[Here are the docs for setting a Synaptics trackpad configuration (on Gentoo)](https://wiki.gentoo.org/wiki/Synaptics). Here is my trackpad config; I don't use any smart features (no tap click, no scroll). This issue can be closed I think.
```shell
Section "InputClass"
        Identifier "touchpad catchall"
        Driver "synaptics"
        MatchIsTouchpad "on"
        Option "VertEdgeScroll" "0"
        Option "CircularScrolling"         "0"
        Option "MaxTapTime" "0"
        Option "maxDoubleTapTime" "0"
        Option "CornerCasting" "0"
        Option "HorizEdgeScroll" "0"
        Option "VertTwoFingerScroll" "0"
EndSection
```

**Comment by danielzfranklin** [comment]
Thank you for helping me to debug my issue even though it wasn't an issue with spacemacs. I forgot I had recently enabled tap to click.
