### ISSUE TITLE
Magit rebase - resolve conflicts

### ISSUE THREAD

**Issue by rakanalh** [syl20bnr/spacemacs#12998]
#### Description :octocat:
Magit rebase - conflict resolution

#### Reproduction guide :beetle:
- Start Emacs
- Open a project
- Rebase a branch with conflicts
- Try to resolve conflicts with SPC g v r

*Observed behaviour:* :eyes: :broken_heart:
- The Ediff layout opens with all 3 buffers showing the magit-status content
- In addition, pressing `q` to quit the ediff session should restore previous layout, it doesn't.

*Expected behaviour:* :heart: :smile:
- The non-spacemacs way i am accustomed to is to be given a list of files that have conflicts to choose from.
- Once a file is chosen, the Ediff layout would open with that specific file

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8fcc9d849)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(sql yaml lua javascript python rust solidity auto-completion better-defaults emacs-lisp git ivy markdown multiple-cursors org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Screenshot
![DeepinScreenshot_select-area_20191129122626](https://user-images.githubusercontent.com/195829/69866115-821b0700-12a3-11ea-9780-e4092c44fa5f.png)

**Comment by duianto** [comment]
Confirmed

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f34ca06b0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git
            (haskell :variables haskell-completion-backend 'dante haskell-process-type 'stack-ghci haskell-process-args-ghci "ghci" haskell-process-path-ghci "stack")
            helm
            (javascript :variables javascript-backend 'lsp)
            lsp markdown multiple-cursors
            (org :variables org-agenda-files
                 '(("c:/Users/username/org/notes.org")))
            shell spell-checking syntax-checking treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by rakanalh** [comment]
I can also add that:
- SPC g s (magit-status)
- Placing the cursor on the conflicting file
- Pressing `e` for magit ediff

It takes roughly 10 - 20 seconds to start the ediff session.

**Comment by duianto** [comment]
Pressing `e` on the conflict file opened the ediff session in 3-4 seconds for me.

But I'm guessing that it's because of the small conflict. The `test.txt` file only contains two lines, and the second line is different on the `master` and `test` branch.

**Comment by rakanalh** [comment]
Thank you for helping the verification of the bug @duianto.

I could say that before switching to spacemacs from my own emacs configs, ediff was much faster.

**Comment by duianto** [comment]
I'll check if there's a difference in the linux vm.

**Comment by duianto** [comment]
I'm seeing the same thing in PopOS 19.10 as in Windows 1903.
- `SPC g v r` opens the magit buffer in all three ediff buffers.
- `e` on the conflict file, opens a correct ediff session in 2 seconds.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f3f2db831)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 python
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
