### ISSUE TITLE
`bash-language-server` LSP Hinting Throwing Errors on Hover State

### ISSUE THREAD

**Issue by macintacos** [syl20bnr/spacemacs#12997]
#### Description :octocat:
I'm on the `develop` branch and am trying to get the `bash-language-server` to work, however it doesn't appear to be functioning properly for at least the hover state. I've been trying to figure out how to modify the server endpoint but can't figure out how to do that. Naturally this isn't a great comparison, but I was able to get the `bash-language-server` functioning correctly with the Bash IDE VSCode extension (which has you spin up a docker container for explainshell integration).

The error I'm getting looks something like:

```
LSP :: Request textDocument/hover failed with message: Error: Invalid URI "/api/explain?cmd=export" [3 times]
```

Screenshot of what it looks like (showing `Messages` and `lsp-log` output when I put the cursor on various keywords): https://p-37fygj.b1.n0.cdn.getcloudapp.com/items/6quLmERK/Image+2019-11-27+at+23.37.30.png?v=76285447d3a0a320a72c4824f4c2ba1e

This is what it theoretically _should_ be returning for a hover state on `export` (for example): https://p-37fygj.b1.n0.cdn.getcloudapp.com/items/X6uDq80g/Image+2019-11-28+at+00.14.43.png?v=0dc07616e0a82c4ec978c1ea43a4800d

#### Reproduction guide :beetle:
- Start Emacs
- Navigate to a file that is handled by the `bash-language-server` LSP
- Put the cursor over a keyword (like `function` or `export`). Hover state error should be echo'd out at the bottom of the window.

*Observed behaviour:* :eyes: :broken_heart:
You get an error, similar to what I've shown above.

*Expected behaviour:* :heart: :smile:
You don't get an error, but actually get useful information about a keyword provided by the LSP backend.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cab1e6958)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory nil)
 emacs-lisp git github go helm html
 (javascript :variables javascript-backend 'lsp javascript-fmt-tool 'prettier javascript-import-tool 'import-js)
 (json :variables json-fmt-tool 'prettier)
 (lsp :variables lsp-log-io 't lsp-navigation 'peek)
 markdown org osx
 (prettier :variables prettier-js-show-errors 'echo)
 (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t python-backend 'lsp)
 react
 (rust :variables rust-backend 'lsp rust-rls-cmd
       '("rustup" "run" "stable" "rls")
       rust-format-on-save t)
 (shell-scripts :variables shell-scripts-backend 'lsp)
 spacemacs-modeline
 (syntax-checking :variables syntax-checking-enable-by-default t)
 treemacs
 (typescript :variables typescript-fmt-on-save t typescript-fmt-tool 'prettier)
 version-control yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by yyoncho** [comment]
This is lsp-mode specific issue.
CC @danielmartin

**Comment by danielmartin** [comment]
Thanks for the report. We've just fixed a bug in the Bash language client. Now you should get regular `onHover` behavior in Bash files. If you want better hover via Explainshell, launch the Docker image, evaluate the following line and restart the workspace with `lsp-restart-workspace`:

`(setq lsp-bash-explainshell-endpoint "http://0.0.0.0:5000/")`

(Replace the URL with your Docker image URL)

**Comment by yyoncho** [comment]
@duianto friendly reminder that you might CC me for lsp-mode related issues.

**Comment by duianto** [comment]
@macintacos Did the fix solve your issue?

**Comment by macintacos** [comment]
Apologies forgot to follow up; yes, the issue is resolved now! I’ll go ahead and close this.
