### ISSUE TITLE
Spacemacs freezes from time to time. When this happens it eats up almost all memory and CPU.

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#1300]
OS X 10.10 user here. I've only used Spacemacs for 3 days but it has frozen multiple times, even in one day :( ... By "freeze" I mean it just doesn't respond to anything at all, be it mouse click or keyboard input. I had to `sudo kill -9` to kill the process and restart it, losing unsaved changes in the meantime. Is there any way to get an error log or something such that I might look at it/attach it here so that it would be easier to figure out what happened? I figure it could have something to do with "persistent server" but I'm not sure.

**Comment by tuhdo** [comment]
Which Spacemacs version are you using?

**Comment by x-ji** [comment]
Pulled it on Sunday. Also installed Carbon Emacs on that day. Didn't do update since then.

**Comment by tuhdo** [comment]
By Carbon Emacs, do you mean Emacs for Emacs OS X? If so, which Emacs version is it?

**Comment by x-ji** [comment]
The CHANGELOG in .emacs.d says Spacemacs' version is Release 0.101.x (2015/04/13)

I followed the following instructions on the project homepage to installed Emacs on OS X.

The version of Emacs seems to be 24.5

> The recommended version for OS X is emacs-mac-port. It can be installed via homebrew with the following commands:

> $ brew tap railwaycat/emacsmacport
> $ brew install emacs-mac

> The default key handling is different from the official OS X port. To correct this you can add the osx layer to your dotfile layer list:

> (setq-default dotspacemacs-configuration-layers '(osx))

> Note that the emacs-mac-port server behaves differently than the regular Emacs server. Details can be found on the emacs-mac-port README.

**Comment by tuhdo** [comment]
So, is it default Spacemacs or have you added anything to your `.spacemacs` file? If you add some layer, it would be useful to list the layers you enabled. And does this symptom happen on which language mode or Emacs in general?

This PR is updating the emacs-mac-port link: https://github.com/syl20bnr/spacemacs/pull/1295, so maybe you are using older version. What's the output of `M-x emacs-version`?

**Comment by x-ji** [comment]
GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, Carbon Version 157 AppKit 1347.57) of 2015-04-19

I have a `.spacemacs` file and the following are the layers enabled:

```
     osx
     auto-completion
     better-defaults
     (git :variables
          git-enable-github-support t
          git-gutter-use-fringe t)
     markdown
     org
     syntax-checking
     themes-megapack
     auctex
     iedit
     python
     javascript
     php
     ruby
     shell-scripts
     haskell
     html
     c-c++
     ess
     autohotkey

     visual-fill-column
```

where `visual-fill-column` is a custom layer to add the package `visual-fill-column` from melpa.

Seems to be happening in general. Happened when I was editing LaTeX and Python, and just then when I was going through my `.spacemacs` file it happened again......

**Comment by tuhdo** [comment]
Do you see some messages at the bottom when this freezing happens? When this freezing happens, even `Ctrl-g` doesn't work?

Probably a layer is causing this, i.e. when this happens, which is the last file (i.e. Python or Latex) you opened?

**Comment by kendall** [comment]
brew seems borked right now; I did an update and then:

==> Upgrading 1 outdated package, with result:
emacs-mac emacs-24.5-z-mac-5.7
==> Upgrading emacs-mac
==> Cloning http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git
Updating /Library/Caches/Homebrew/emacs-mac--git
error: Unable to find 5fdc612745165110dff7d17c4c1eab8bb68e36aa under
http://www.math.s.chiba-u.ac.jp/~mituharu/emacs-mac.git
Cannot obtain needed commit 5fdc612745165110dff7d17c4c1eab8bb68e36aa
while processing commit 866501efe0fdc0c29448e0aaf8696eb0a3c8fcd6.
error: fetch failed.
Error: Failed to download resource "emacs-mac"
Failure while executing: git fetch -q origin

Anyone else seeing this?

Cheers,
Kendall

**Comment by x-ji** [comment]
I think I didn't see any message. `Ctrl-g` isn't having any effect either. It just ... froze. Nothing seems to change inside of the interface, and it doesn't respond to anything. Strangely there isn't a spinning ball when I move the mouse over. The mouse just remained in the shape of "pointer" and wouldn't change to "insert" even if I move it over some text.

What I meant is that it happened multiple times, and each time I'm just working on one type of file. So for example the time when I was editing LaTeX, I was only working on LaTeX files throughout the whole session. The same for the Python session. If it's induced by a layer, then this layer could be a global one?

**Comment by x-ji** [comment]
Although Activity Monitor doesn't treat it as "not responding", if I use normal "exit" from GUI on it it wouldn't exit, because nothing is being shown whatsoever. Even normal "force kill" from the GUI seems to not work. `sudo kill -9` was the only thing that worked for me.

**Comment by jupl** [comment]
Not sure if it helps, but I've had it freeze like this when I tried to use helm-projectile while working on a web-mode file.

**Comment by stormpat** [comment]
@kendall Theres an open issue on the emacs-macport repo, https://github.com/railwaycat/homebrew-emacsmacport/issues/22

**Comment by kendall** [comment]
Thanks. I fixed it by removing the existing git repo in the brew cache.

**Comment by x-ji** [comment]
Turns out it could be that this freeze issue is induced by my Mac running out of disk space... I'll wait for a few more days to see the situation after I've cleaned up my disk.

**Comment by x-ji** [comment]
Unfortunately disk space doesn't seem to be related... Even when I have more than 10GB of free space Emacs is still freezing up and eating memory.

The following are stats reported by Activity Monitor:

![screenshot 2015-04-24 13 57 45](https://cloud.githubusercontent.com/assets/2999209/7315445/24a97442-eaa0-11e4-82b4-6ceb68d79ac1.png)
![screenshot 2015-04-24 13 58 05](https://cloud.githubusercontent.com/assets/2999209/7315447/28369dba-eaa0-11e4-9d34-7849885f9441.png)
![screenshot 2015-04-24 16 33 42](https://cloud.githubusercontent.com/assets/2999209/7315451/2d1531ca-eaa0-11e4-9a8b-ddf468e6e009.png)
![screenshot 2015-04-24 16 33 56](https://cloud.githubusercontent.com/assets/2999209/7315455/2f51068a-eaa0-11e4-8267-bdab6bf520fa.png)

My Mac only has 16GB of memory so I'm not sure what's going on. Also the memory usage of `kernal_task` doesn't seem to be normal either.

**Comment by x-ji** [comment]
Finally I did a clean reinstallation of Spacemacs(both `.emacs.d` and `.spacemacs` file) using the same Emacs installation, and the issue seems to be gone. I suspect it's caused by a private layer I created to use some melpa plugin though I'm not sure.

**Comment by x-ji** [comment]
No it's not the problem of a private layer... It's probably some variable set in `custom-set-variables` via `Customization`. I noticed that after I've set a certain variable(not sure what), Spacemacs hangs for 10 seconds, and eats up to nearly 6GB of memory on starting up, on loading `config.el`. Then, after it finally loads, it easily freezes.

The following is my customization settings:

```elisp
;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ahs-case-fold-search nil)
 '(ahs-default-range (quote ahs-range-whole-buffer))
 '(ahs-idle-interval 0.25)
 '(ahs-idle-timer 0 t)
 '(ahs-inhibit-face-list nil)
 '(global-auto-complete-mode t)
 '(global-linum-mode t)
 '(global-visual-line-mode t)
 '(js-indent-level 2)
 '(org-mobile-directory "~/DropBoxBackup/Dropbox/orgmode")
 '(org-mobile-files (quote (org-agenda-files "~/GoogleDrive/orgmode/")))
 '(org-mobile-inbox-for-pull "~/GoogleDrive/orgmode/from-mobile.org")
 '(ring-bell-function (quote ignore) t)
 '(standard-indent 2))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-tooltip-common ((t (:inherit company-tooltip :weight bold :underline nil))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :weight bold :underline nil)))))
```

Could it be `global-auto-complete-mode`?

**Comment by tuhdo** [comment]
If you remove the customization, does the freezing happen?

**Comment by x-ji** [comment]
As I said, after I did a fresh installation the problem disappeared. However it seems that if I start to do customization after the fresh install, the issue seems to happen again.

**Comment by tuhdo** [comment]
Probably you should remove the customization one by one to see which causes the problem. I suspect `auto-complete-mode` or maybe `org-mobile` keeps syncing?

**Comment by x-ji** [comment]
Yeah that was my thought. Unfortunately the problem was severe enough to the extent that I couldn't even invoke `M-x customize-group` before it froze... Also, editing the `.spacemacs` file and commenting out the customizations via an external editor seems to break Spacemacs. I'm trying another fresh install now.

**Comment by x-ji** [comment]
It seems to be working fine now after I enabled everything except for `org-mobile`, so I suppose it's because I didn't set it up correctly. Thanks for the help.

**Comment by x-ji** [comment]
I hate to say it but it's back again... Without any private layer nor `auto-complete` nor `org-mobile` in custom......

![screenshot 2015-04-26 21 52 43](https://cloud.githubusercontent.com/assets/2999209/7337513/17c28cb2-ec5f-11e4-8da7-072e2fc43b41.png)

I'm not sure whether it could be related to https://github.com/syl20bnr/spacemacs/issues/1263 ...

**Comment by x-ji** [comment]
Also I realized when this happens, because it requires so much memory beyond current memory capacity, Emacs constantly fills up disk space until it's full.

**Comment by x-ji** [comment]
In my case I can currently confirm that an abnormally large `savehist` file caused the issue each time and disabling `savehist-mode` solved it. Though I currently have no idea as to why this happened...

**Comment by jawwada** [comment]
how to do it, i mean remove kill ring from save hist

**Comment by x-ji** [comment]
Already removed in commit `bef15e7`

**Comment by Danl2620** [comment]
Hi, I'm getting sporadic 10 second freezes in spacemacs. I have a call stack sample dump during one of them attached.

My spacemacs version is:  0.200.9@25.2.1 (spacemacs)
My emacs version is: GNU Emacs 25.2.1 (x86_64-apple-darwin15.0.0, NS appkit-1404.13 Version 10.11.1 (Build 15B42)) of 2017-05-24

[emacs_freeze_sample.txt](https://github.com/syl20bnr/spacemacs/files/1086288/emacs_freeze_sample.txt)

**Comment by kpanic** [comment]
This https://github.com/syl20bnr/spacemacs/issues/1905#issuecomment-129592455 helped for me.
I was getting freeze after auto-completing in `elixir-mode` and maximum CPU usage (fan was turning on)

After I applied those settings in emacs24 I did not had this behaviour anymore
