### ISSUE TITLE
Use shell-pop for toggling eshell/shell

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1301]
[shell-pop](https://github.com/kyagi/shell-pop-el) is a nice little package I have been using for a long time. Essentially when you call it, it toggles a shell buffer below your current window, with directory path set to the `default-directory` path of your current buffer. Another benefit is that it can be configured to always open at the bottom and with full width, popout when needed. It's much better than the default toggle currently in Spacemacs where it just takes over current window.

**Comment by tonylotts** [comment]
I think shell-pop should be added, but it should be noted that multi-term has similar functionality with multi-term-dedicated.

**Comment by tuhdo** [comment]
With [my PR](https://github.com/syl20bnr/spacemacs/pull/1678), it can behave like `multi-term` and even better, the shell can track directory of the current buffer. You can also type `exit` to kill `ansi-term` and its window immediately and by just using `ansi-term`, you get full key bindings integration with Emacs.
