### ISSUE TITLE
Symbol’s function definition is void: battery-update

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#13010]
When the `dotspacemacs-mode-line-theme` variable is set to `doom`.
Then a warning is shown on startup:
>Error (use-package): doom-modeline/:init: Symbol’s function definition is void: battery-update

#### It's been reported upstream:
void function battery-update https://github.com/seagle0128/doom-modeline/issues/274

#### A temporary fix
Until it's fixed upstream:
- Switch to the `spacemacs` `dotspacemacs-mode-line-theme`
- Or ignore the warning:
This solution was provided by hlissner 
https://github.com/seagle0128/doom-modeline/issues/274#issuecomment-560269645
Add the following command to the `dotspacemacs/user-init` section of `.spacemacs`:
```elisp
(fset 'battery-update #'ignore)
```

**Comment by wow-yorick** [comment]
thanks

**Comment by duianto** [comment]
The latest doom-modeline commit was just reverted. 
https://github.com/seagle0128/doom-modeline/commit/2fcb6e8c0f78f6d5755a09872e253e96e2b2e233

We'll have to wait for Melpa to update. https://melpa.org/#/doom-modeline

From the current commit that causes the warning:
>Source github (commit 211c0d)

To the revert commit: 2fcb6e8

**Comment by duianto** [comment]
The fix is on Melpa. I just updated the packages and the warning is gone.
