### ISSUE TITLE
helm-org-in-buffer-headings and helm-org layer don't work

### ISSUE THREAD

**Issue by Rareform** [syl20bnr/spacemacs#13014]
I cloned spacemacs via git clone https://github.com/syl20bnr/spacemacs. 
For some reason helm-org layer is absent per default. But if I install it via `package-list-packages`
on ubuntu or on windows some functions from `helm-org` module are not working. 

For example I get `helm-M-x: Symbol’s function definition is void: helm-dynamic-completion ` when I try `helm-org-in-buffer-headings` in Ubuntu. On Windows I get only NIL values for resulting buffer headings.
I opened a thread on emacs.stackexchange and other persons seem also to have this issue:
> https://emacs.stackexchange.com/questions/54092/spacemacs-helm-org-layer-is-missing

**Comment by gcentauri** [comment]
I can confirm that after installing the `helm-org` package I get entries that are just `nil`

![image](https://user-images.githubusercontent.com/760104/70066425-5012e900-15b2-11ea-84b8-8f0b71bc329c.png)

I thought it might have to do with a conflict in `org-bullets`, like the regex looking for * characters was failing, but removing `org-bullets` does not seem to fix it.  It works as expected in a vanilla emacs setup with helm and helm-org.

**Comment by orialb** [comment]
It might be related to the fact that org-mode 9.3 was released yesterday and maybe there was some changes which broke helm-org. 
I also see this behavior with a config that uses org 9.3 , but not with a one that uses the previous version. 

>  It works as expected in a vanilla emacs setup with helm and helm-org.
Which version of org do you use in the vanilla setup? (the default one is older) You could try to upgrade to latest org and see if this causes the same behavior.

**Comment by orialb** [comment]
Upgrading helm-org to latest master solved this issue for me (the issue @gcentauri was referring to, I'm not sure it is actually related to the original issue).

**Comment by gcentauri** [comment]
@orialb @Rareform - works for me now too. must have just hit `helm-org` at the wrong moment.

@Rareform - if you can confirm it works for you after a package update (you can use the Update Packages button on the home page) then we can close the issue.

**Comment by Rareform** [comment]
The issue with NIL headings is gone.
The original issue is still present. 
If I put `helm-org` to the additional packages in configuration file I get
`Error running timer ‘org-indent-initialize-agent’: (void-function org-time-add) [13 times]
eldoc error: (void-function org-src-get-lang-mode)`
errors, which continuously occur. 
The helm-in-buffer-headings function works, but this is not an acceptable state.
If I put in configuration layers helm-org gets deleted with the next spacemacs restart.

**Comment by orialb** [comment]
> If I put in configuration layers helm-org gets deleted with the next spacemacs restart.

I'm a bit confused regarding what exactly you are doing here. Note that `helm-org` package doesn't have a layer of it's own but is rather a part of the `helm` layer. Do you have `helm` in your `dotspacemacs-configuartion-layers` ?

**Comment by Rareform** [comment]
Sorry, I should have made my description more precise. Actually this is a part of this issue. 
I have `helm` in my configuration layer and I know, that `helm-org` should actually come automatically with it, but for some unknown reason the helm-org package is missing (at least the functions which come with it). This is why I tried to install it via `package-install-packages`. Do you know what could be the reason why `helm-org` is missing? Windows and Linux pcs of mine both have this issue.

**Comment by orialb** [comment]
I see. From your initial description I suspect you might be using the master branch of spacemacs? If this is the case you should switch to the develop branch because master is way behind at the moment.

**Comment by Rareform** [comment]
It works on the develop branch. It is not that great, that the standard features do not work on the master branch, but as long as there is some working branch I guess it's ok.

**Comment by gcentauri** [comment]
@Rareform - as far as I can tell, the `helm-org` package is not a part of the `helm` layer at all.  It is certainly not part of `helm.el` by default. This is not unusual.  Emacs is a huge ecosystem, and Helm is a fairly large sub-ecosystem.  The great thing about Spacemacs is that the community can decide what is useful to add into a layer. If `helm-org` is something you think is a must-have feature for the `helm` layer, feel free to add it in a PR, or request it in an issue.

**Comment by orialb** [comment]
I claimed it is a part of the `helm` layer, but it is actually part of the `org` layer (on develop branch) 
https://github.com/syl20bnr/spacemacs/blob/6f029cc0573b8f42a05dea26be92617d5d5282cb/layers/%2Bemacs/org/packages.el#L20

In any case it is included in develop.
