### ISSUE TITLE
Package in configuration layer not installed

### ISSUE THREAD

**Issue by igoodrich** [syl20bnr/spacemacs#1302]
I have my own little configuration layer 'ian-space'.
In packages.el:

    (defvar space-ian-packages
      '(
        key-chord
        ag
       )

key-chord will be installed, ag will not.

FWIW, I believe the problem is somewhere in core-configuration-layer.el.
Specifically, my little ag gets filtered by:
  
    configuration-layer//filter-packages-with-deps 

And does not make it out of:
  
    (let* ((not-installed (configuration-layer//get-packages-to-install
                           configuration-layer-all-packages-sorted))
         (not-installed-count (length not-installed)))

This is of course a particularly awkward place to have a defect (if that's what this is) as I can't install this package except through the configuration layer.  Excited about the kit overall!

**Comment by trishume** [comment]
I assume your layer also has an `space-ian/init-ag` function.

You seem to have found where it is getting removed, what makes this package get filtered but not other spacemacs packages?

**Comment by igoodrich** [comment]
@trishume All me!!  I didn't add that init function.  It is working now.  Going to close...
