### ISSUE TITLE
Best practice for registering a helm function as auto-loadable?

### ISSUE THREAD

**Issue by orialb** [syl20bnr/spacemacs#13021]
Hi,

I recently wanted to make the function `helm-find-files-1` auto-loadable. I ended up modifying the Helm layer directly and added `:commands (helm-find-files-1)` in the `use-package` declaration for helm. 
While this works, it means that from now on I have to maintain my own version of the Helm layer with this change in it. 
I guess it's not such a big deal, but I was nevertheless wondering whether there is a way to achieve this without directly modifying the layer?

**Comment by duianto** [comment]
It seems to work to call the following from the `dotspacemacs/user-config` section in `.spacemacs`:
```elisp
      (use-package helm :commands helm-find-files-1)
```
I tested it with this key binding:
```elisp
      (global-set-key (kbd "<f8>") '(lambda () (interactive)
                                      (helm-find-files-1 "~/")))
```
before calling the use-package commands line on startup, then the key binding returns:
>Symbol’s function definition is void: helm-find-files-1

Until a helm buffer is opened.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6649e78f3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git helm html javascript markdown multiple-cursors
            (org :variables org-agenda-files
                 '(("c:/Users/username/org/notes.org")))
            python shell spell-checking syntax-checking themes-megapack treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by orialb** [comment]
Thanks for checking this! 
Do you know whether it is good practice to call `use-package` on some package more than once (especially in the Spacemacs context)? Could the second declaration in the user-config interfere somehow with the declaration from the layer?
In case you don't know I should just test it myself for a couple of days and report back here. 

Thanks again!

**Comment by duianto** [comment]
I don't know if it's good practice or if there's a better solution, but that's what I came up with and it seemed to work.

There's some discussion about it here:
Calling use-package multiple times on the same package
https://github.com/jwiegley/use-package/issues/662

**Comment by duianto** [comment]
JAremko (another Spacemacs collaborator) had two other solutions:
>or do (autoload filename docstring interactive type)
https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload.html
or make a proxy function that first requires the package that provides helm-find-files-1 and then calls the function

I'm guessing that the second suggestion looks something like this:
```elisp
      (defun my/helm-find-files-1 ()
        (interactive)
        (require 'helm)
        (helm-find-files-1 "~/"))

      (global-set-key (kbd "<f8>") #'my/helm-find-files-1)
```

It seems to work.

**Comment by orialb** [comment]
Thanks for digging into this, this is very helpful!
I will play with the different options you suggested a bit in the weekend when I have more time to do some tests. 

I think this can be closed for now. I will report back here if I have some interesting findings after trying the suggested methods. 

Thanks again for your help!
