### ISSUE TITLE
eshell autocompletion opens tons of new frames

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#13048]
Does anybody else observe this? When my eshell prompt is directly after a slash (e.g. `~/`) and I press `TAB` a lot of new emacs tabs get opened (I suspect it is one per file in the directory). If I already started typing autocompletion and pressing `TAB` works fine (e.g. `~/Doc`).

Edit: I just saw that a buffer `HELM Pcomplete` opened, but it opens to the side and not at the bottom as helm buffers usually do.

**Comment by duianto** [comment]
### completion layer: ivy
#### test 1
- typing: `~/`
- pressing: `TAB`
- shows completions after the cursor
- `C-j` and `C-k` or `TAB`, `S-TAB` cycles between them

#### test 2
- typing: `/`
- pressing: `TAB`
- shows suggestions below the prompt line, in the same shell buffer
- the same thing is observed when typing: `a`
- and pressing `TAB`
- the completions are shown below the prompt line


### completion layer: helm
#### test 1
- typing: `~/`
- pressing: `TAB`
- the same behavior as with `ivy` is observed
- the completions appear after the cursor
- `C-j` and `C-k` or `TAB`, `S-TAB` cycles between them

#### test 2

- typing: /
- pressing: TAB
- opens two Emacs smaller frames on top of each other, both have two windows:
  - The visible frame:
    - (top window) `HELM Pcomplete` with suggestions
    - (bottom window) `*eshell-1*` (the same buffer as in the initial frame before TAB was pressed)
  - The hidden frame
    - (top window) `*spacemacs*` (the spacemacs home buffer)
    - (bottom window) `*eshell-1*`

`C-g` or `ESC` closes the visible frame
but the second frame is still open.

The second frame seems to only open the first time after the eshell buffer has been opened, and `TAB` is pressed after `/`.

After closing the `HELM Pcomplete` frame (`C-g` or `ESC`), then only that frame appears the next `TAB` is pressed after `/`.

There's no change if the second frame is left open or closed with `SPC F d`, before opening the HELM Pcomplete frame.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5111de7d1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm html
            (javascript :variables javascript-backend 'lsp javascript-fmt-on-save t)
            lsp markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            react
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking themes-megapack treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by gdkrmr** [comment]
This behaviour is known seems to be intended by helm: https://github.com/emacs-helm/helm/issues/2091.
> Because it is much better except perhaps for spacemacs users

It can be fixed by configuring:
```
(setq helm-show-completion-display-function #'helm-show-completion-default-display-function)
```
Personally I would prefer to use company, but the fix above is acceptable.

**Comment by duianto** [comment]
We need to fix the buggy frame behavior, but there has been other requests to use  company instead of a frame. So it would probably be best to add an option to choose how to display the completions. Maybe as a auto-completion layer variable.
