### ISSUE TITLE
`org-edit-src-exit` breaks current layout

### ISSUE THREAD

**Issue by soulawaker** [syl20bnr/spacemacs#13058]
#### Description :octocat:
`org-edit-src-exit` breaks current layout and only its parent file buffer window occupied current frame.

#### Reproduction guide :beetle:
- Start Emacs
0. Divide current frame into multiple windows layout
1. Go to src block in any org file
2. Press , '
3. Edit something
4. Press , c
5. The parent file buffer window in current layout occupied the entire frame

*Observed behaviour:* :eyes: :broken_heart:
The parent file window in current layout occupied the frame

*Expected behaviour:* :heart: :smile:
Normally recover previous layout in the current frame

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 239f60a65)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(csv ivy systemd lua python ruby sql go yaml java csharp groovy
     (kotlin :variables kotlin-tab-width 4)
     javascript html deft auto-completion emacs-lisp
     (clojure :variables clojure-enable-clj-refactor t clojure-enable-fancify-symbols t clojure-enable-linters 'joker)
     docker latex windows-scripts git github
     (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t)
     org
     (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/usr/bin/zsh" shell-default-height 50 shell-default-position 'bottom shell-default-full-span nil)
     (spell-checking :variables enable-flyspell-auto-completion t spell-checking-enable-by-default nil)
     syntax-checking colors finance search-engine
     (ansible :variables ansible-auto-encrypt-decrypt t)
     nginx pdf epub dash evil-snipe pandoc rebox command-log multiple-cursors)
```
- System configuration features: XAW3D XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11

#### Backtrace :paw_prints:
```
```

**Comment by emacs18** [comment]
Perhaps this was the documented change in org mode?

https://www.orgmode.org/Changes.html says the following.

Change in behavior on exit from an Org edit buffer

Org will no longer attempt to restore the window configuration in the frame to which the user returns after editing a source block with org-edit-src-code. Instead, the window configuration will remain as it is.

**Comment by emacs18** [comment]
I tried the following which seem to restore window configuration.

```elisp
(defadvice org-edit-src-exit (after restore-window-config activate)
  (winner-undo))
```

I'll be checking out this advice and see how it works over the next few days.

**Comment by emacs18** [comment]
https://code.orgmode.org/bzg/org-mode/commit/819e98afd018cad3c13fd58bfcbd979ab36dfbc7
is the change that removed code to restore window configuration.
I would have submitted a PR against org-mode to add (winner-undo), but sadly emacs related projects seem to require patches to be emailed.  I tried to send email to the org-mode email list, but it appears that the email never got delivered.  Oh well.

**Comment by soulawaker** [comment]
Thanks. It worked! I've never thought it's intended. I wonder its reason. Also I know it will takes so long for them to check mails. I had sent a report on wrong web link within official org mode home. They had checked it after quite long time. Anyway, happy new year to you in advance!

**Comment by GPPassos** [comment]
Hi,

For reference, I also had this problem, but on regular emacs, not spacemacs.

Have you checked the variable `org-src-window-setup`? It seems this is the one that controls how the frame layout is changed by editing src blocks. I changed to `split-window-right` but there are other values possible (see the variable description). This solved the problem for me.

I am not sure if this solves for your case but I suppose so, so just in case I'm sharing.

**Comment by soulawaker** [comment]
Hi, @GPPassos

Yes, it prevents breaking previous layout. But it splits the buffer into two small windows unlike original Spacemacs org configuration expands it before splitting. Someone might be good but others not. So I think it is not a solution for this situation. But it is quite useful information for me. I didn't know `org-src-window-setup` change src edit buffer assignment. Thanks for your sharing!
