### ISSUE TITLE
Missing gpg key?

### ISSUE THREAD

**Issue by JoKeyser** [syl20bnr/spacemacs#13054]
During initial install on Ubuntu 18.04, I receive this gpg error:

```
Failed to verify signature archive-contents.sig:
No public key for 066DAFCB81E42C40 created at 2019-12-11T14:10:02+0100 using RSA
Command output:
gpg: Signature made Mi 11 Dez 2019 14:10:02 CET
gpg:                using RSA key C433554766D3DDC64221BFAA066DAFCB81E42C40
gpg: Can't check signature: No public key
```

And when I try to `gpg --recv-keys 066DAFCB81E42C40`, I get this:

```
gpg: key 066DAFCB81E42C40: 1 signature not checked due to a missing key
gpg: key 066DAFCB81E42C40: "GNU ELPA Signing Agent (2019) <elpasign@elpa.gnu.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

**Comment by JoKeyser** [comment]
Oh, the fix was simple:
```
$ gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40

gpg: key 066DAFCB81E42C40: public key "GNU ELPA Signing Agent (2019) <elpasign@elpa.gnu.org>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by karlicoss** [comment]
Related: https://github.com/aquamacs-emacs/aquamacs-emacs/issues/166

**Comment by karlicoss** [comment]
I wonder if it's worth reopening?
Not sure what's the proper way to resolve this would be, but this must be very confusing for people new to Spacemacs (half of packages failing to install).

**Comment by duianto** [comment]
Emacs 26.3 is supposed to have fixed the signature issue.

And the `ppa:kelleyk/emacs` has also updated the keys for older Emacs versions:
ELPA signing key expired https://github.com/kelleyk/ppa-emacs/issues/9

So the issue might have been fixed in linux, maybe the mac repositories need to update the key in their builds as well.

**Comment by vvarik** [comment]
Not fixed in Linux (Ubuntu 18.04.4), just ran into it today. I can confirm it is confusing for new people. For instance, I don't know whether I should 1) just import the gpg key and restart; 2) remove everything in `elpa` except the `gnupg` folder and then import gpg key; 3) remove everything in `elpa` and issue `emacs --insecure`

**Comment by dennismayr** [comment]
I tried this, passing the keyserver:
`gpg --homedir ~/.emacs.d/elpa/gnupg --keyserver hkp://keys.gnupg.net --recv-keys 066DAFCB81E42C40`

It worked in Ubuntu 18.04.

**Comment by vityafx** [comment]
> I tried this, passing the keyserver:
> `gpg --homedir ~/.emacs.d/elpa/gnupg --keyserver hkp://keys.gnupg.net --recv-keys 066DAFCB81E42C40`
> 
> ```shell
> gpg: clave 066DAFCB81E42C40: "GNU ELPA Signing Agent (2019) <elpasign@elpa.gnu.org>" sin cambios
> gpg: Cantidad total procesada: 1
> gpg:              sin cambios: 1
> ```
> 
> It worked in Ubuntu 18.04.

Also works on centos 7.5.

**Comment by refmitchell** [comment]
I should clarify, I'm not a spacemacs user, just straight emacs but I don't think that matters beyond the repo the issue happens to be in. Just reaching out for help wherever I can.

I'm still having experiencing this issue (Ubuntu 18.04). I tried the command suggested by @dennismayr which results in:

`gpg --homedir ~/.emacs.d/elpa/gnupg --keyserver hkp://keys.gnupg.net --recv-keys 066DAFCB81E42C40
`
`gpg: keyserver receive failed: No data`

When I search the keyserver via web-browser I can't find the fingerprint either and I'm completely lost. I have a related stackexchange post [here](https://emacs.stackexchange.com/questions/60554/cannot-run-melpa-package-refresh-due-to-gpg-errors?noredirect=1#comment95174_60554) with all the info. The main roadblock I seem to hit is that I can never find the fingerprint and I have no idea why.

**Comment by Grazfather** [comment]
Easiest fix for me was to just install emacs 27.1

For ubuntu:
```bash
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt update
sudo apt install emacs27
```

**Comment by toomaj** [comment]
Try the following as I've also updated  [here](https://emacs.stackexchange.com/questions/60554/cannot-run-melpa-package-refresh-due-to-gpg-errors?noredirect=1#comment95174_60554)

    gpg --homedir ~/.emacs.d/elpa/gnupg --keyserver hkps://keys.openpgp.org --recv-keys 066DAFCB81E42C40

You might also like to add `keyserver hkp://keys.gnupg.net` to your `~/.emacs.d/elpa/gnupg/gpg.conf` file

**Comment by dennismayr** [comment]
> Try the following as I've also updated [here](https://emacs.stackexchange.com/questions/60554/cannot-run-melpa-package-refresh-due-to-gpg-errors?noredirect=1#comment95174_60554)
> 
> ```
> gpg --homedir ~/.emacs.d/elpa/gnupg --keyserver hkps://keys.openpgp.org --recv-keys 066DAFCB81E42C40
> ```
> 
> You might also like to add `keyserver hkp://keys.gnupg.net` to your `~/.emacs.d/elpa/gnupg/gpg.conf` file

Yup, apparently the server you've pointed `gpg` to works better. I'll update my documents, too; thanks for the collective heads-up!

**Comment by Awsome-Chen** [comment]
> I wonder if it's worth reopening? Not sure what's the proper way to resolve this would be, but this must be very confusing for people new to Spacemacs (half of packages failing to install).

I can't agree it more.Some very sticky troubles always happened when I started .

**Comment by lebensterben** [comment]
Please add additional information, at least your system information, when adding new comments.

**Comment by lebensterben** [comment]
Let's add this to FAQ.

**Comment by CFGrote** [comment]
I have the same issue now with emacs28.2 on debian 12. after fresh install of spacemacs, I get this:

![image](https://github.com/syl20bnr/spacemacs/assets/15476807/414cfacd-fc34-46c4-ba94-59b6c00768ff)

Trying to get the key manually also failed:
```
▶ gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 645357D2883A0966          
gpg: keyserver receive failed: No data
```

Any advice would be appreciated. Thanks!

**Comment by sebogh** [comment]
`gpg --homedir ~/.emacs.d/elpa/gnupg --keyserver hkp://keyserver.ubuntu.com  --recv-keys 645357D2883A0966`

worked for me (Debian 12, Emacs 28.2)

**Comment by CFGrote** [comment]
Thanks @sebogh , switching to `hkp://keyserver.ubuntu.com` solved it for me, too. The missing key was 645357D2883A0966 in my case, though (as per your edited comment).

**Comment by ghost** [comment]
> `gpg --homedir ~/.emacs.d/elpa/gnupg --keyserver hkp://keyserver.ubuntu.com --recv-keys 645357D2883A0966`
> 
> worked for me (Debian 12, Emacs 28.2)

This also worked for me on Pop!_OS 22.04 LTS using Emacs 27.1, with the same key.

**Comment by smile13241324** [comment]
Os error not our bug
