### ISSUE TITLE
org-archive-subtree and org-refile fail with "invalid-function org-preserve-local-variables" 

### ISSUE THREAD

**Issue by orialb** [syl20bnr/spacemacs#13051]
Since upgrading to org 9.3 I have noticed that I am unable to use `org-archive-subtree` as it fails complaining that `org-preserve-local-variables` is an invalid function.
This is very odd as I can eval (org-preserve-local-variables SOMETHING) in the org buffer without problems (that is to say `org-preserve-local-variables` is defined).

Did someone else notice this problem or is it something peculiar with my configuration ? (although I'm not sure what I could be changing that will cause this). 

The backtrace:
```
Debugger entered--Lisp error: (invalid-function org-preserve-local-variables)
  org-preserve-local-variables("Copied: Subtree(s) with 949 characters")
  org-copy-subtree(1 nil t)
  org-archive-subtree(nil)
  funcall-interactively(org-archive-subtree nil)
  call-interactively(org-archive-subtree nil nil)
  command-execute(org-archive-subtree)
```

**Comment by orialb** [comment]
I tested this with a fresh clone of Spacemacs develop with no personal configuration (beynod enabling the org layer and what was enabled by default) and the problem seems to persist. So it is not related to some change I made. 

It works with vanilla emacs (with Org 9.3), so it seems to be some Spacemacs specific problem, unless there is something else I am missing. 

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 239f60a65)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors org treemacs)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by orialb** [comment]
This happens also with `org-refile`.

**Comment by orialb** [comment]
This is a duplicate of https://github.com/syl20bnr/spacemacs/issues/11801, so I will close this. Sorry for the noise and for not searching better.

**Comment by rileyrg** [comment]
fyi happening  on debian buster  using a straight.el install of org

**Comment by orialb** [comment]
The solution in https://github.com/syl20bnr/spacemacs/issues/11801 worked for me (removing all elc files).

**Comment by rileyrg** [comment]
thanks for the reply. It didnt for me. I had to recompile the org repo in straight.el. Very confusing. When it works, it works well, when it doesnt its head scratch time.

**Comment by ashutosh-dwivedi-e3502** [comment]
> The solution in #11801 worked for me (removing all elc files).

Thanks this worked for me as well.
