### ISSUE TITLE
Reloading config with fullscreen-at-startup t (in macOS) toggles fullscreen mode

### ISSUE THREAD

**Issue by tshu-w** [syl20bnr/spacemacs#13073]
#### Description :octocat:
If I reload config on macOS with `dotspacemacs-fullscreen-at-startup t`, it make frame fullscreen.

#### Reproduction guide :beetle:
- Start Emacs
- toggle fullscreen mode
- spc-f-e-R

*Observed behaviour:* :eyes: :broken_heart:
config reload and fullscreen frame

*Expected behaviour:* :heart: :smile:
config reload without fullscreen frame

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6649e78f3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm osx
      (chinese :variables chinese-enable-fcitx t)
      dash git
      (version-control :variables version-control-diff-tool 'diff-hl)
      github
      (pandoc :variables pandoc-data-dir "~/.spacemacs.d/pandoc-mode")
      lsp dap
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support nil c-c++-enable-google-style nil)
      emacs-lisp
      (python :variables python-backend 'anaconda python-sort-imports-on-save t python-formatter 'black python-format-on-save t blacken-fast-unsafe t python-fill-column 99)
      (markdown :variables markdown-command "pandoc -t html5 -f markdown+smart --mathjax --highlight-style=pygments --toc --toc-depth 3 --template github.html5 --css html/css/github.css" markdown-live-preview-engine 'pandoc)
      (org :variables org-agenda-files
           '("~/Documents/Org")
           org-directory '"~/Documents/Org" org-projectile-file "TODOs.org" org-want-todo-bindings t org-enable-hugo-support t org-enable-reveal-js-support nil org-enable-org-journal-support t org-journal-dir "~/Documents/Org/Journals/")
      (latex :variables latex-enable-auto-fill nil latex-enable-folding t latex-enable-magic nil)
      (bibtex :variables org-ref-default-bibliography
              '("~/Dropbox/Documents/Zotero/refs.bib")
              org-ref-pdf-directory "~/Dropbox/Documents/Zotero/" org-ref-bibliography-notes "~/Dropbox/Documents/Zotero/notes.org")
      (deft :variables deft-directory "~/Documents/Org/Notes" deft-recursive t deft-extensions
        '("org" "md" "txt")
        deft-org-mode-title-prefix t deft-use-filename-as-title nil deft-use-filter-string-for-filename t deft-auto-save-interval 0 deft-file-naming-rules
        '((noslash . "-")
          (nospace . "-")
          (case-fn . downcase))
        deft-strip-summary-regexp
        (concat "\\(" "[\n	]" "\\|^#\\+[[:upper:]_]+:.*$" "\\|^#\\+[[:alnum:]_]+:.*$" "\\)"))
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup nil auto-completion-enable-sort-by-usage nil)
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      (wakatime :variables wakatime-cli-path "/usr/local/bin/wakatime")
      unicode-fonts xkcd cfg)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by antonalekseev** [comment]
If I understand the issue correctly you are setting `dotspacemacs-fullscreen-at-startup t`, then pressing `SPC f e R` and expecting full-screen mode to be toggled right away? I'm afraid this not going to happen as aforementioned variable affects startup routine, which calls `spacemacs/toggle-frame-fullscreen` depending on this variable's value. Startup routine doesn't happen in response to `SPC f e R` for it's just synchronization of Spacemacs running configuration state with one in the configuration file. Therefore you either need to `SPC q r` after setting configuration variable, or manually toggle fullscreen mode one time `SPC T T` – on next restart it just happens.

**Comment by TshuW** [comment]
@antonalekseev Thx for your reply and sorry for my misrepresentation. I have updated the description. Hope clear now.

**Comment by duianto** [comment]
Confirmed.
It's not mac specific. It also happens in Windows.

I'll ask the other maintainers if they know of a way to limit checking the variable and toggling to fullscreen on startup.

**Comment by tshu-w** [comment]
active

**Comment by duianto** [comment]
PR pending with a possible fix:
[defaults] Prevent fullscreen on config reload #14241

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
[defaults] Prevent fullscreen on config reload #14241
