### ISSUE TITLE
Error (use-package): counsel/:config: Symbol’s function definition is void: lexical-let

### ISSUE THREAD

**Issue by TakaakiFuruse** [syl20bnr/spacemacs#13070]
#### Description :octocat:
Spacemacs allerts

```
Error (use-package): counsel/:config: Symbol’s function definition is void: lexical-let
```
when launched.

#### Reproduction guide :beetle:
- Start Emacs
- Pull latest dev of spacemacs
- Restart spacemacs

*Observed behavior:* :eyes: :broken_heart:
It shows an error message, but ivy is functioning.

*Expected behavior:* :heart: :smile:
No error should not happen.

If I comment out 

```
(spacemacs//ivy-command-not-implemented-yet "jI")
```

on spacemacs/layers/+completion/ivy/packages.el and restart, the error will gone.
So I assume the function is doing something wrong...

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d18d09049)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(lsp spacemacs-layouts spacemacs-editing-visual spacemacs-modeline spacemacs-org spacemacs-project spacemacs-navigation
     (treemacs :variables treemacs-display-in-side-window nil treemacs-show-hidden-files t treemacs-silent-filewatch t treemacs-silent-refresh t treemacs-sorting 'alphabetic-desc treemacs-space-between-root-nodes t treemacs-tag-follow-cleanup t treemacs-width 35)
     (ivy :variables ivy-enable-advanced-buffer-information t)
     (rust :rust-backend 'lsp)
     (mypython :variables python-backend nil python-enable-yapf-format-on-save nil python-sort-imports-on-save nil python-test-runner 'pytest python-auto-set-local-pyenv-version nil python-auto-set-local-pyvenv-virtualenv nil pytest-cmd-flags "-xlsq --tb=short")
     (markdown :variables markdown-live-preview-engine 'vmd)
     colors yaml git
     (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.001 auto-completion-private-snippets-directory "~/dotfiles/emacs-files/my-snipptes")
     emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by madand** [comment]
#13067 has a fix and more info on the issue.

**Comment by TakaakiFuruse** [comment]
@madand 

Thanks. I could fixed it.
