### ISSUE TITLE
Please change the default font for Spacemacs to get a greet status line

### ISSUE THREAD

**Issue by jidibinlin** [syl20bnr/spacemacs#13089]
Please change the Default Font from Source code to a Nerd patched font. Because source code without nerd patched may make the status line urgly. When i changed the default font to ' DejaVuSansMono Nerd Font ' I can adjust the separator-scale to 1.0 from 1.5.
![2019-12-17_18-21](https://user-images.githubusercontent.com/38578679/70987018-0d94f480-20fa-11ea-8724-50528c34df32.png)
And the result just like this

**Comment by jidibinlin** [comment]
@ duianto. 
### I find that the appearance of the spaceline not only depend on the default font for spacemacs but also depend on the system fonts.
* First I installed spacemacs and changed the default font to nerd font on my new matchine. But the spaceline didn\`t work as my expection. It\`s still urgly. separator-scale still can`t drop to 1.0.
* Second I installed all the [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts). Now spaceline worked as my exception.

**Comment by syl20bnr** [comment]
Thank you for the opening issue. Font is tricky to get right for everyone because it depends on various factors like the OS and terminal so this is something that must be adjusted by users.

I propose to rename your issue so that it is easier for other users to find it and read your solution.

**Comment by jidibinlin** [comment]
@syl20bnr 
Yes! you are right. I find **powerline fonts** is also important for spaceline.
I just copied the font`t directory  in my previously system, so i didn`t find this mistake
