### ISSUE TITLE
spacemacs keybinding to finish org-capture is not working: ', ,' can do nothing useful here 

### ISSUE THREAD

**Issue by k-jell** [syl20bnr/spacemacs#13084]
#### Description :octocat:
When I'm trying to finish and file away an `org-capture` buffer that has been invoked from an `org-agenda` buffer (by pressing `, ,` or `SPC m ,`), without entering insert-mode, I get the error message `', ,' can do nothing useful here`.
It works however when opening the capture buffer without having an agenda buffer open first. It also works after entering insert mode in the capture buffer. The emacs keybinding `C-c C-c` also works. The error is only shown if the destination file is added to `org-agenda-files`.

#### Reproduction guide :beetle:
- Start Emacs
- open an `org-agenda` buffer
- open an `org-capture` buffer while the agenda buffer is active (the destination file for the org-capture process needs to be in the org-agenda files)
- finish the capturing process, without entering insert mode (e.g. happens when using only prompts for the input) using `, ,` or `SPC m ,` 
- see error `', ,' can do nothing useful here`

*Observed behaviour:* :eyes: :broken_heart:
Capturing process cannot be finished using the spacemacs keybindings `, ,` or `SPC m ,`. Instead the error `', ,' can do nothing useful here` is shown. 

*Expected behaviour:* :heart: :smile:
Org-capture works without error message.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0f5cc6e5f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm javascript html markdown pandoc python latex auto-completion emacs-lisp org bibtex multiple-cursors spell-checking pdf treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
This is what I'm seeing right after starting Spacemacs.
- `SPC a o o` opens the buffer: `*Agenda Commands*`
- `t` opens an `*Org Agenda*` buffer that lists all TODO items.
- `SPC a o c` opens a `*Org Select*` buffer
- `t` chooses Task from the capture template
A `CAPTURE-notes.org` buffer opens, where the first line says:
`Capture buffer.  Finish 'C-c C-c', refile 'C-c C-w', abort 'C-c C'k'.`
- `, ,` opens the buffer: `HELM Org Set Tags Command`
`C-h l` calls `view-lossage` which shows that it called: ` , , [org-ctrl-c-ctrl-c]`

The `, ,` and `, k` key bindings are not bound to completing and aborting the capture buffer on startup. I'm not quite sure what steps to perform to enable them, but they become enabled after a while while testing this issue.

`, ,` is bound:
- to `org-ctrl-c-ctrl-c` here:
https://github.com/syl20bnr/spacemacs/blob/473d019b47d75ee7cba25528bbf14fb9acbf0aa4/layers/%2Bemacs/org/packages.el#L314
- and to `org-capture-finalize` here:
https://github.com/syl20bnr/spacemacs/blob/473d019b47d75ee7cba25528bbf14fb9acbf0aa4/layers/%2Bemacs/org/packages.el#L145

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 473d019b4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by smile13241324** [comment]
Hmmm sounds like an anoying issue. I am using org popups all the time for capturing and task tracking and the spacemacs way of confirming these screens should always work.

I will have a look into this issue.

**Comment by smile13241324** [comment]
@k-jell I think I have fixed your issue on develop. Can you double check and close this ticket if it works?

**Comment by k-jell** [comment]
Yes, it is fixed now. Everything works as intended. Thanks :smiley:
