### ISSUE TITLE
[Feature Request] LSP backend support for JSON layer

### ISSUE THREAD

**Issue by sei40kr** [syl20bnr/spacemacs#13086]
## Description

I want LSP backend for JSON layer. It'll be easy to setup `lsp-json`, but I also want to integrate with [JSON Schema Store](http://schemastore.org/json/) like [lsp-yaml does](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-yaml.el#L95).

**Comment by smile13241324** [comment]
Sensible addition, having lsp everywhere is must these days

**Comment by smile13241324** [comment]
Json lsp is life.
