### ISSUE TITLE
Include mfiano's sly package/layer for common-lisp

### ISSUE THREAD

**Issue by equwal** [syl20bnr/spacemacs#13080]
I'd like to put [common-lisp-sly](https://github.com/mfiano/common-lisp-sly) into spacemacs, but I see some problems:
- It is not a layer, but a package.
- It violates all kinds of other conventions of spacemacs.
- It has no maintainer.

At least it works right now. It certainly smoothes over usage of sly, and we already have a slime layer.

So there are about two ways to go for a sly layer:
- Try to copy the [slime layer](https://develop.spacemacs.org/layers/+lang/common-lisp/README.html), but for sly.
- Reformat mfiano's layer to meet conventions.

**Comment by anlsh** [comment]
I'm willing to put in some legwork to make this happen. What exactly are the violations of convention? I'm rather new to spacemacs layers, and as far as I can tell `common-lisp-sly` mirrors the source code of the existing [common-lisp-layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/common-lisp) pretty closely.

**Comment by equwal** [comment]
I'm not really interested in doing this anymore @anlsh, though if you want to do it you can make your own pull request.

The package needs to be a spacemacs layer instead of a package, primarily. Mostly it just needs edits according to the style conventions of spacemacs.
