### ISSUE TITLE
Include helm-org as a must-have feature in all stable releases

### ISSUE THREAD

**Issue by Rareform** [syl20bnr/spacemacs#13091]
Referring to the conclusion in the issue #13014 I think helm-org is a must-have feature for the org layer, and should be included, fully functioning, in all stable releases. Currently it has some problems on the master branch as described in #13014.

**Comment by duianto** [comment]
From issue @13014 it seems like it's working on the `develop` branch. I'm quite sure it will be fixed on the `master` branch when the next version is released. I don't have any insight into when that is.
