### ISSUE TITLE
magit-diff not showing diff

### ISSUE THREAD

**Issue by Asalle** [syl20bnr/spacemacs#13096]
#### Description :octocat:
magit-diff not showing diff on `d r` in transient mode, returns an erroe

#### Reproduction guide :beetle:
- Start Emacs
- Start treemacs
- open any file under git
- open magit-treansient with `SPC g s`
- go to any commit
- press `d` in transient mode (for diff)
- press any key from the submenu (`r`, `d`, ...)

*Observed behaviour:* :eyes: :broken_heart:
no diff is shown and the line
`magit-diff-arguments: Wrong number of arguments: (1 . 1), 2`
is in *Messages*

*Expected behaviour:* :heart: :smile:
a diff is shown

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7af300a22)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python yaml javascript
				(markdown :variables markdown-live-preview-engine 'vmd)
				(go :variables go-format-before-save t go-use-golangci-lint t go-backend 'lsp godoc-at-point-function 'godoc-gogetdoc)
				helm auto-completion git org c-c++ github
				(shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term)
				better-defaults syntax-checking lsp protobuf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2

**Comment by duianto** [comment]
On the latest `develop` branch with updated packages.

Pressing `dd` on a commit in:
- The `magit: .emacs.d` (`SPC g s`) buffers: `Recent commits` list
- or in the `ll` (two lowercase L's) `magit-log: .emacs.d` buffer

Opens a `magit-diff: .emacs.d` buffer, without any error messages.

#### System Info :computer:

<details><summary>
Pop!_OS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 37fdd1ef8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm
                 (javascript :variables javascript-fmt-on-save t)
                 markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 37fdd1ef8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm imenu-list markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control
            (xclipboard :variables xclipboard-enable-cliphist t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by Asalle** [comment]
re-checked at home and you're right @duianto 
Closing this.
