### ISSUE TITLE
Create official shortkeys cheatsheet and free to assign keys cheatsheet

### ISSUE THREAD

**Issue by Rareform** [syl20bnr/spacemacs#13097]
Although a lot of useful keys are mentioned in [documentation](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org) it would be really handy to have some official document solely dedicated to various shortcuts in spacemacs. 

Other thing which I miss even more is that there is to my knowledge no list of free to assign keys, so that users at the moment need to double check themselves whether the shortkey does something or not. Sometimes they still cannot be sure, because it might be used in certain modes.

**Comment by mosic** [comment]
`SPC o` and `SPC m o` are reserved for user bindings, so you can put everything there and not worry about overriding a keybinding.

https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#reserved-prefix-command-for-user

**Comment by hyiltiz** [comment]
I thought you could ask find the answer without leaving Emacs: `SPC h d b` read as Spacemacs-help-describe-(key)bindings.

**Comment by Rareform** [comment]
> You can find the answer without leaving Emacs: `SPC h d b` read as Spacemacs-help-describe-(key)bindings.

This advice is quite handy, thanks. What is missing to give me full satisfaction though is that it is a dropdown menu. It would be handy to have an option `download-shortcuts` where you get a downloaded file with shortcuts sorted in categories. Is there a way to write the output of `SPC h d b` in a file?

**Comment by hyiltiz** [comment]
`SPC h d b` to open, `SPC b Y` to yank, `SPC b s` to open scratch buffer, `p` to paste, `:w spacemacs-keybindings.txt` to save.

**Comment by duianto** [comment]
@hyiltiz The instructions seem to be missing a step.
Because `SPC h d b` opens either of the prompts:
- HELM Descbinds
- Ivy Bindings 

Pressing `SPC b Y` at the prompts, just insert a `space character`, `b` and `Y`.

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 08442790c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion colors command-log emacs-lisp git github haskell helm imenu-list markdown multiple-cursors org
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by nixmaniack** [comment]
For `ivy`, the generic keybinding to get the list of completions into a buffer is `C-c C-o` (`ivy-occur`). 
So, after `SPC h d b`, you can hit `C-c C-o` and then `:w spacemacs-keybindings.txt`.

**Comment by hyiltiz** [comment]
@Rareform if you believe it is resolved, please close the issue and spare the devs some work.

**Comment by Rareform** [comment]
The issue is resolved, thanks to all participants!

**Comment by hyiltiz** [comment]
Hmm, now that I tried my sequence `SPC h d b SPC b Y SPC b s p :w spacemacs-keybindings.txt` in another machine, it failed. As you pointed out, the key binding reference is opened in helm minibuffer. In that case, you can probably use `helm occur` as @nixmaniack mentioned to get the results into a editable/yankable buffer.
