### ISSUE TITLE
how can I update orgmode to 9.3

### ISSUE THREAD

**Issue by onriv** [syl20bnr/spacemacs#13098]
Now I'm at commit 473d019, but the org-mode version is still 9.2.. I want package org-num, which is provided in 9.3.
Thanks a lot!

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. eadbfaf87)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html csv restclient sql onriv javascript vimscript autohotkey markdown ipython-notebook helm
      (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-idle-delay 0.2 auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip nil auto-completion-enable-sort-by-usage nil)
      multiple-cursors emacs-lisp windows-scripts org themes-megapack yaml latex plantuml ibuffer
      (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
      python treemacs typescript)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON CANNOT_DUMP LCMS2

**Comment by thanhvg** [comment]
You should have it if you use ELPA, `SPC b h` click on `Update Package`

After the update is done; `M-x: org-version` to verify

**Comment by onriv** [comment]
Got it. I will close the issue, thank you
