### ISSUE TITLE
[SPC ?] takes >10 secs to popup

### ISSUE THREAD

**Issue by zirni** [syl20bnr/spacemacs#13094]
#### Description :octocat:
Calling [SPC ?] takes a way to long to show up.
My emacs frame is open for several days and I did
some project work. The buffer list [SPC b b] has 
a lot of items.

#### Reproduction guide :beetle:
- Start Emacs
- 

*Observed behaviour:* :eyes: :broken_heart:
[SPC ?] takes >10 secs to show up

*Expected behaviour:* :heart: :smile:
[SPC ?] should pop up immediatly

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. da7c2c875)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(react html eww javascript markdown
       (ruby :variables ruby-version-manager 'rvm)
       ruby-on-rails helm emacs-lisp git markdown org shell
       (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

#### Profiler :paw_prints:
```
- command-execute                                               36897  99%
 - call-interactively                                           36897  99%
  - byte-code                                                   36415  98%
   - helm-M-x-read-extended-command                             36415  98%
    - helm-comp-read                                            36415  98%
     - helm                                                     36404  98%
      - apply                                                   36404  98%
       - helm                                                   36404  98%
        - apply                                                 36404  98%
         - helm-internal                                        36404  98%
          - helm-read-pattern-maybe                             36308  97%
           - helm-update                                        33770  91%
            - helm--collect-matches                             33762  91%
             - helm-compute-matches                             33762  91%
              - helm-process-filtered-candidate-transformer              33746  90%
               - helm-apply-functions-from-source               33746  90%
                - apply                                         33746  90%
                 - helm-fuzzy-highlight-matches                 33742  90%
                  - helm-flx-fuzzy-highlight-match              33742  90%
                   - require                                    31854  85%
                      apply                                     31854  85%
                   + helm-flx-fuzzy-highligher                   1888   5%
                 + helm-M-x-transformer-no-sort                     4   0%
              + helm-get-cached-candidates                         16   0%
            + helm--update-move-first-line                          4   0%
            + helm-render-source                                    4   0%
           + read-from-minibuffer                                2519   6%
          + helm-initialize                                        68   0%
          + #<compiled 0x259c485>                                  24   0%
          + helm-display-buffer                                     4   0%
     + helm-make-source                                            11   0%
  + funcall-interactively                                         482   1%
+ timer-event-handler                                             102   0%
+ ...                                                              60   0%
+ redisplay_internal (C function)                                  24   0%
  undo-auto--add-boundary                                           5   0%
  global-undo-tree-mode-check-buffers                               4   0%
```

edit: label

**Comment by duianto** [comment]
Have you updated the packages?
You might have hit a helm update that had issues.

We noticed last week in the gitter chat that some helm buffers took a long time to open:
https://gitter.im/syl20bnr/spacemacs?at=5df2b2bee47fb31eb79febe6
https://gitter.im/syl20bnr/spacemacs?at=5df344ae7ce7ea1e3576dd19

>Confirmed (at least in a linux vm with Emacs 26.3) some helm buffers opens slowly. SPC SPC takes about 10 seconds, but C-h f takes 25 seconds to open.
It Windows 1903 with either Emacs 26.3 or 27.0.50 (2019-11-11), SPC SPC opens in less than two seconds, C-h f opens in less than four seconds.
SPC b b or SPC p p opens quickly in both the linux vm and windows.

When I rolled back `helm` and `helm-core` then the slow helm buffers opened quickly again. It might have been fixed the next day.

Now when I tested with the latest helm version `SPC SPC` and `C-f` opens quickly.

#### System Info :computer:
<details><summary>
Pop!_OS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6f029cc05)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm
                 (javascript :variables javascript-fmt-on-save t)
                 markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6f029cc05)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm
            (latex :variables)
            markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by duianto** [comment]
If that's wasn't your issue then this might be something to try:
https://github.com/emacs-helm/helm/wiki/FAQ#slow-frame-and-window-popup-in-emacs-26

**Comment by zirni** [comment]
Thanks alot @duianto

Did a package update and restarted Emacs. So far [SPC ?] is back as fast as usual :-)
```
~/.emacs.de/elpa

Before:
helm-20191126.822
helm-core-20191126.727

Now:
helm-20191217.1347
helm-core-20191218.1205
```
