### ISSUE TITLE
key binding for forge not consistent

### ISSUE THREAD

**Issue by real-or-random** [syl20bnr/spacemacs#13108]
#### Description :octocat:
The key binding for forge is not consistent and changes when opening the help in magit-status.
Moreover, the docs for the github layer on the website says the keybinding is `F` but it's never `F`.

#### Reproduction guide :beetle:
- Start Emacs
- Open file in git repo
- Press `SPC g s` to open magit-status view

*Observed behaviour:* :eyes: :broken_heart:
The key binding for forge is `@` without opening the help.
When opening the help with `?`, it's changed to `'`, which was "submodule" earlier. Then `@` does not work anymore.
Sometimes "submodule" is changed to `"` then and sometimes not, which the help showing `'` both for forge and submodule.

*Expected behaviour:* :heart: :smile:
The key binding should be consistent and should match the docs.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git github markdown
      (org :variables org-enable-github-support t)
      spell-checking syntax-checking latex pdf-tools yaml lua gtags
      (c-c   :variables c-c  -enable-clang-support t)
      php python rust)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by antonalekseev** [comment]
Can't reproduce with the following configuration.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 239f60a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy

I suppose the reason of the inconsistency you experience is that the `source-control/git` Spacemacs layer on the `master` branch haven't been updated for the last three years while `forge` support was added to the `develop` only at the end of 2018 (https://github.com/syl20bnr/spacemacs/pull/11764). I suggest you to try `develop` branch. My own impression is that it's pretty reliable.

**Comment by real-or-random** [comment]
Yes, indeed. It works there. I'm new to spacemacs and I've switched to the develop branch now. The master branch is pretty outdated apparently. This is not the first time I get caught by this:    
https://github.com/syl20bnr/spacemacs/pull/11360#issuecomment-564319732
