### ISSUE TITLE
Rust quick run broken on develop

### ISSUE THREAD

**Issue by kidpollo** [syl20bnr/spacemacs#13111]
#### Description :octocat:
Rust quick run does not produce output

#### Reproduction guide :beetle:
- Start Emacs
- create hello.rs as https://doc.rust-lang.org/rust-by-example/hello.html
- [SPC q]

*Observed behaviour:* :eyes: :broken_heart:
Compilation works but program does not get run

*Expected behaviour:* :heart: :smile:
"Hello World" output

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ffccb1742)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv graphviz rust spell-checking gtags helm treemacs html github
     (ruby :variables ruby-version-manager 'rvm)
     yaml javascript better-defaults osx colors org syntax-checking emacs-lisp
     (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
     (shell :variables shell-default-shell 'multi-term shell-default-term-shell "zsh")
     (version-control :variables version-control-global-margin t version-control-diff-tool 'git-gutter+ version-control-diff-side 'left)
     (git :variables git-gutter-use-fringe t)
     (clojure :variables clojure-enable-fancify-symbols t clojure-enable-linters 'clj-kondo)
     markdown
     (spell-checking :variables spell-checking-enable-by-default nil)
     sql)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by gcentauri** [comment]
@kidpollo - if you pull recent changes, i think this should work for you

**Comment by duianto** [comment]
In the reproduction steps, the third step says: `[SPC q]`

Have you rebound it to a custom command, or was it a typo?

Because by default `SPC q` shows the Spacemacs quit key bindings for the commands:
`frame-killer`, `kill-emacs`, `prompt-kill-emacs`, `save-buffers-kill-emacs` and several `restart-*` commands.

**Comment by kidpollo** [comment]
Wooops i meant <leader> q. It maps to spacemacs/rust-quick-run is I
remember correctly

**Comment by duianto** [comment]
I haven't tried either the `rust` layer or installing `rust` before, so I'm not sure If I've set it up correctly.

I don't remember all the commands I ran to try to install `rust` and the `rust language server`.
But I first installed `RUSTUP‑INIT.EXE` from https://www.rust-lang.org/learn/get-started

And I found these commands for installing the the language server:
```
rustup self update
rustup update nightly
rustup component add rls --toolchain nightly
rustup component add rust-analysis --toolchain nightly
rustup component add rust-src --toolchain nightly
```
source: https://www.shadercat.com/setting-up-a-rust-development-environment-on-windows-10/

With the `rust` and `lsp` layers enabled, when I created and open the `hello.rs` example file in the `c:/Users/username/Temp` directory, then the following prompt appeared:
```
LSP :: Connected to [rls:9648 status:starting].
LSP :: rls:9648 initialized successfully
There are 10845 files in folder c:/Users/username/Temp so watching the repo may slow Emacs down.
Do you want to watch all files in c:/Users/username/Temp? (y or n) y
```

Answering: `y` shows:
```
LSP :: You can configure this warning with the `lsp-enable-file-watchers' and `lsp-file-watch-threshold' variables
LSP :: could not find `Cargo.toml` in `c:\Users\username\Temp` or any parent directory
```

The process list `SPC a p`, shows that the `rls` server is running:
```
ispell          23632   run     --              --           c:/tools/cygwin/bin/aspell.exe -a -m -B --encoding=utf-8
rls             9648    run     *rls*           --           rls
rls stderr      --      open    *rls::stderr*   --           
```
Pressing `SPC m q` in the `hello.rs` file, opens a `*compilation*` buffer that shows:
```
-*- mode: compilation; default-directory: "~/Temp/" -*-
Compilation started at Fri Dec 27 12:46:24

rustc -o "c:/Users/username/AppData/Local/Temp/hello.rs-e50d743278ffb5740c76fb0aab12723b" "c:/Users/username/Temp/hello.rs"

Compilation finished at Fri Dec 27 12:46:24
```
I'm not sure where the `Hello World` message is supposed to appear, but I'm not seeing it in the `*Messages*` buffer.

**Comment by gcentauri** [comment]
@duianto - it should appear in that compilation buffer.  I think it isn't working for you because of the path name on windows. I tried making the function to print it more restricted by only firing on compilation buffers that include `(concat "rustc -o" temporary-file-directory)` It works for me on Linux:

```
-*- mode: compilation; default-directory: "~/projects/rust/" -*-
Compilation started at Fri Dec 27 15:55:27

rustc -o /tmp/hello.rs-69489781721928f8164ddfc2b54686e3 /home/shoshin/projects/rust/hello.rs

Compilation finished at Fri Dec 27 15:55:27

Hello World!
```

but the value of `temporary-file-directory` is `"/tmp/"` for me.

**Comment by duianto** [comment]
The now merged PR:
[rust] remove compilation buffer string match on rust-quick-run #13131

Fixed it. Thanks @gcentauri 

`Hello World!` is shown in the compilation buffer:
```
-*- mode: compilation; default-directory: "~/Temp/rust/" -*-
Compilation started at Sat Dec 28 15:29:19

rustc -o "c:/Users/username/AppData/Local/Temp/hello.rs-ef295451ba920ffe13695ec92417bbd5" "c:/Users/username/Temp/rust/hello.rs"

Compilation finished at Sat Dec 28 15:29:20

Hello World!
```

@kidpollo Can you pull the latest develop commit and check if it's also working for you. If it does then you can close this issue.

**Comment by kidpollo** [comment]
Thanks! works now!
