### ISSUE TITLE
Default powerline theme breaks EMMS modeline

### ISSUE THREAD

**Issue by 3marcusw** [syl20bnr/spacemacs#1311]
The spacemacs modeline conflicts with EMMS. Normally, EMMS displays the current song and the song's current time in the modeline, [like this](https://i.imgur.com/eG6f0.png), but with powerline, the emms-modeline is completely absent. Is there a setting i need to change?

**Comment by 3marcusw** [comment]
Strangely, emms-modeline does appear when in the help minor mode
![screenshot-of-emms-help](https://cloud.githubusercontent.com/assets/3537909/7291120/7a30a0e0-e959-11e4-923f-2ad6de935f8e.png). Unfortunately, it is otherwise absent, like this.
![screenshot-of-emms-playlist](https://cloud.githubusercontent.com/assets/3537909/7291143/befbd028-e959-11e4-8d75-487f2484edff.png)

**Comment by syl20bnr** [comment]
Thanks for the report, the powerline in spacemacs is cool but also a weak spot. I need to work on it to make it easy to add segment.

It would be great if you could start a PR with an EMMS layer for spacemacs !
