### ISSUE TITLE
Redundant package checking during update makes updating slow

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#13114]
#### Description :octocat:
Updating packages checks packages redundantly while traversing the deps tree.
This makes package updating take a very long time when you combine a slow to
check package (like one fetched from github via quelpa) and a package that is
depended on by many other packages (like undo-tree, which is depended on by
evil, which is depended on by many packages).

#### Reproduction guide :beetle:
- Start Emacs
- Add to `additional-packages`:

    ```el
    (undo-tree :location (recipe :fetcher github :repo
    "emacsorphanage/undo-tree"))
    ```
- Update packages

*Observed behaviour:* :eyes: :broken_heart:
It takes a really long time and undo-tree is checked multiple times.

*Expected behaviour:* :heart: :smile:
Every package is only checked once.

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0c774416d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(c-c++ cscope nginx better-defaults spacemacs-layouts ivy
       (markdown :variables markdown-live-preview-engine 'vmd)
       (syntax-checking :variables syntax-checking-enable-tooltips t)
       (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup nil spacemacs-default-company-backends
                        '(company-capf
                          (company-dabbrev-code company-keywords)
                          company-files company-dabbrev))
       git dash pdf html
       (org :variables org-enable-github-support t org-enable-reveal-js-support t org-want-todo-bindings t)
       colors
       (osx :variables osx-command-as 'super)
       github
       (shell :variables shell-default-term-shell "/usr/local/bin/zsh" shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
       (spell-checking :variables spell-checking-enable-by-default nil)
       version-control tmux yaml docker prettier restclient lua
       (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
       emoji theming multiple-cursors aj-elixir aj-emacs-lisp aj-javascript aj-org aj-term aj-typescript aj-ruby auto-correct cleverparens-lispy flow match-indent shift-number writing)
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```

```

**Comment by aaronjensen** [comment]
PR: https://github.com/syl20bnr/spacemacs/pull/13115

**Comment by smile13241324** [comment]
@aaronjensen I have merged your PR. Update checking should not longer be redundant. Please double check whether this solved your issue and close it when it does please.

**Comment by aaronjensen** [comment]
I no longer use spacemacs, but my pr did fix my issue previously so I assume it still does so I will close this.
