### ISSUE TITLE
Layer installing packages using a github recipe doesn't put it anywhere accessible to load-path

### ISSUE THREAD

**Issue by togakangaroo** [syl20bnr/spacemacs#13128]
I am creating my own layer and I do

```
(defconst gim-org-packages
  '(
    (ob-racket :location (recipe :fetcher github :repo "xchrishawk/ob-racket"))))

(defun gim-org/init-ob-racket ()
  (spacemacs|use-package-add-hook org
    :post-config
    (use-package ob-racket
      :init (progn (add-to-list 'org-babel-load-languages '(racket . t))
                   (message "!!Racket for org initialized")))))
```

`use-package` fails.

```
~/.emacs.d $ find . -name "ob-racket*" 
./.cache/quelpa/packages/ob-racket-20160818.1955.el
./.cache/quelpa/build/ob-racket
./.cache/quelpa/build/ob-racket/ob-racket.el
```

so it *does* download but it only lives in this `.cache/quelpa/build` directory

None of the stuff in my `load-path` variable references `.cache` so this doesn't seem right.

That would be why `use-package` fails (though oddly, the message *does* print - not sure why `:init` would run if it fails...)

I'm guessing it is supposed to be moved by the recipe somewhere into the `elpa` directory and `load-path` modified, but that seems to not be happening.

**Comment by JAremko** [comment]
@togakangaroo   

Emm. Why not ?

``` elisp
(defun gim-org/init-ob-racket ()
  (use-package ob-racket ...
```
:thinking:

**Comment by togakangaroo** [comment]
Because that's the example I was going off of from some other org babel
layers. It makes sense though, according to spacemacs principles I
shouldn't be loading it until it's needed. Either way, it's not on
load-path so neither use-package or even require in the scratch buffer work.

**Comment by JAremko** [comment]
@togakangaroo  I think something wrong with the package then. For example `(provide 'ob-racket)` should be at the end https://github.com/xchrishawk/ob-racket/blob/master/ob-racket.el  (at least per convention) 

Try forking some simply package like https://github.com/snosov1/toc-org/blob/master/toc-org.el and see if it will install properly.

**Comment by togakangaroo** [comment]
Hmm I'll try it when I'm at a computer tonight but this would also be quite
odd. When I manually put that file on my load-path, it works like a charm.
Strange

**Comment by togakangaroo** [comment]
Sorry for the delay, just getting back to this, @JAremko just checking now, I already have `org-toc` installed so probably best to use a different one - any suggestions on org packages that are not typically included in common layers?

**Comment by togakangaroo** [comment]
Ok, so I tried
```
(defconst gim-org-packages
  '(
    (ob-translate :location (recipe :fetcher github
                                    :repo "krisajenkins/ob-translate"))
    (ob-racket :location (recipe :fetcher github
                                 :repo "xchrishawk/ob-racket"))))
```

I'm not seeing that working, same issue with it not being found and

```
~/.emacs.d $ find . -name ob-translate*
./.cache/quelpa/melpa/recipes/ob-translate
./.cache/quelpa/build/package-build/recipes/ob-translate
```

both of which are just a file containing
```
(ob-translate :fetcher github :repo "krisajenkins/ob-translate")
```

**Comment by JAremko** [comment]
```
Error getting PACKAGE-DESC: (error Package lacks a file header)
(Spacemacs) Error: 
An error occurred while installing ob-racket (error: (wrong-type-argument package-desc nil))
```

:roll_eyes:

**Comment by togakangaroo** [comment]
That did it! I cloned and [edited here](https://github.com/togakangaroo/ob-racket) and it worked

**Comment by JAremko** [comment]
Glad to help! Close the issue if it resolved :+1:

**Comment by emacs18** [comment]
Could the originial problem with `spacemacs|use-package-add-hook` was due to this bug in `use-pacakge`?
https://github.com/jwiegley/use-package/issues/785

I had to apply the work around detailed above in order to get things like SPC l b to work which also relied on a hook.

**Comment by lebensterben** [comment]
closing since it's fixed upstream
