### ISSUE TITLE
Documentation on `packages` const defined in layers packages.el?

### ISSUE THREAD

**Issue by togakangaroo** [syl20bnr/spacemacs#13127]
Both in the layers documentation and [in the org layer](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bemacs/org/packages.el#L33) I see something like the following

```
    (ox-gfm :location (recipe :fetcher github :repo "syl20bnr/ox-gfm")
            :toggle org-enable-github-support)
```

yet I can't find any sort of documentation on what sort of thing can go in this list - what is this `:location` key? what is this `recipe` function? What exactly does it do? I assume it pulls down that repo from github but where is it installed to?

**Comment by togakangaroo** [comment]
Nevermind, I see it [here]( https://github.com/syl20bnr/spacemacs/blob/master/core/templates/packages.el.template) and it pops up when I do `configuration-layer/create-layer`. I somehow read all the layer docs without seeing a reference to this function.

**Comment by duianto** [comment]
For easier access, the description says:
https://github.com/syl20bnr/spacemacs/blob/71d4e15e67feda18692ee35d50f3d98216cd90aa/core/templates/packages.el.template#L58-L59
And here's a clickable link: https://github.com/melpa/melpa#recipe-format
