### ISSUE TITLE
let*: Symbol’s function definition is void: helm-org-get-candidates

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#13123]
#### Description :octocat:
The `helm-org` package has removed the function: `helm-org-get-candidates`

In this PR:
Use dynamic completion emacs-helm/helm-org#10

Spacemacs still uses it here:
https://github.com/syl20bnr/spacemacs/blob/37fdd1ef87f739f27c548e19a78c3a5b0d51a0ef/layers/%2Bcompletion/helm/local/helm-spacemacs-help/helm-spacemacs-faq.el#L64

This issue was reported by `mphojele` in the gitter chat:
https://gitter.im/syl20bnr/spacemacs?at=5e03b519d2dadb3893793ff3

#### Reproduction guide :beetle:

- `SPC h f`

*Observed behaviour:* :eyes: :broken_heart:
`let*: Symbol’s function definition is void: helm-org-get-candidates`

*Expected behaviour:* :heart: :smile:
The headings in FAQ.org should be shown in a helm buffer:

![emacs_2019-12-25_22-21-36](https://user-images.githubusercontent.com/13420573/71450754-4707d880-2768-11ea-9c3d-2c5c75adaa57.png)

#### Notes :notebook:
The screenshot was taken with a previous version of helm-org: `helm-org-20190818.521`
from before the PR emacs-helm/helm-org#10 was merged.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 37fdd1ef8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm imenu-list markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control
            (xclipboard :variables xclipboard-enable-cliphist t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
There's a pending draft PR:
Fix helm-spacemacs-help-faq, SPC h f #13136

**Comment by smile13241324** [comment]
@duianto I think your PR has been merged, can you double check whether your issue persist and close this issue if it works now?

**Comment by duianto** [comment]
Thanks for the reminder, yes it works now.
