### ISSUE TITLE
Package unavailable. Is the package name misspelled?

### ISSUE THREAD

**Issue by jeremyperkin** [syl20bnr/spacemacs#13126]
Trying to install on emacs 26.3-1.
OS : Arch Linux 
Selected VIM and HELM options.
Install failed - get the message....
File is missing: Cannot open load file, No such file or directory, bind-map

Tried running emacs --insecure.   This too fails.

**Comment by gcentauri** [comment]
Is it possible this is related to out of date GPG keys?  I'm hesitant to say it is for sure, because I think your version of Emacs should be fine.  But check this and see if it helps at all:

https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html

The other thing I might suggest is switching to the `develop` branch of Spacemacs.

**Comment by amfern** [comment]
i am on develop branch and it solved the issue for me

**Comment by duianto** [comment]
This seems to be a duplicate of this issue:
File error: Cannot open load file, No such file or directory, bind-map #8984
It's labeled as MELPA and some comments state that they tried installing after half an hour and it worked, so it might be a package server issue.

**Comment by Towerism** [comment]
Thank you @amfern This worked for me.

**Comment by Kyllingene** [comment]
Worked for me, the tricky part was that I had to re-install Emacs _and_ my spacemacs dotfiles.

**Comment by tokuchan** [comment]
Confirming in 2023 that https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html worked on develop branch and emacs 30.0.50 on Ubuntu Linux.

**Comment by darkhandz** [comment]
Confirming in 2023 that https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html worked on develop branch and emacs 29.0.92 on Windows 11.
