### ISSUE TITLE
SPC no longer works as a custom agenda command key in org-mode

### ISSUE THREAD

**Issue by liny01-nbsa** [syl20bnr/spacemacs#13138]
#### Description :octocat:
My org-agenda-custom-commands contains
```elisp
(" " "Notes" tags "NOTE"
  ((org-agenda-overriding-header "Notes")
   (org-tags-match-list-sublevels t)))
```
notice the key is "SPC" in this case, it used to work without issue. however
after a recent update of spacemacs and package update
(org-plus-contrib-20191230). It suddenly stopped working.

When I'm in the agenda commands buffer, pressing "SPC" key, the message area
shows "End of Buffer". I suspect SPC as a movement command supersedes it as a
key for the above agenda custom command.

#### Reproduction guide :beetle:
include the above piece in the variable "C-c a" to get the agenda commands
window, then press "SPC"

*Observed behaviour:* :eyes: :broken_heart:
"End of Buffer" message shows in the message area, not bringing up the NOTE
agenda.

*Expected behaviour:* :heart: :smile:
Bringing up the NOTE agenda

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 71d4e15e6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t)
 better-defaults emacs-lisp git helm markdown multiple-cursors
 (org :variables org-enable-github-support t org-enable-bootstrap-support t org-enable-reveal-js-support t)
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking treemacs version-control c-c++ chinese csv docker gnus go haskell html java javascript latex major-modes notmuch php python react ruby ruby-on-rails rust selectric semantic shell-scripts spacemacs-defaults speed-reading sql systemd theming typescript yaml
 (clojure :variables clojure-enable-clj-refactor t)
 ly-setup)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by nixmaniack** [comment]
I can confirm this issue. I started using alternate key when I faced this.

**Comment by duianto** [comment]
Confirmed

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7636811b7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion clojure command-log dap emacs-lisp git helm imenu-list java lsp markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            ranger rust
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by duianto** [comment]
A possible reason why the behavior changed might be because of this commit from 2 months ago:
https://code.orgmode.org/bzg/org-mode/commit/80b29acba3847c1756fa3c143d6991964f7273ca

agenda: Enable navigation for the agenda dispatch buffer
* lisp/org-agenda.el (org-agenda-get-restriction-and-command): Use
  keys C-n, C-p, SPC, DEL analogue to export dispatcher.  See function
  org-export--dispatch-action.

Reported by Nathan Neff https://lists.gnu.org/archive/html/emacs-orgmode/2019-10/msg00179.html.

---

It made it possible to scroll the agenda buffer if it's to small to fit everything.

**Comment by liny01-nbsa** [comment]
> A possible reason why the behavior changed might be because of this commit from 2 months ago:
> https://code.orgmode.org/bzg/org-mode/commit/80b29acba3847c1756fa3c143d6991964f7273ca
> 
> agenda: Enable navigation for the agenda dispatch buffer
> 
>     * lisp/org-agenda.el (org-agenda-get-restriction-and-command): Use
>       keys C-n, C-p, SPC, DEL analogue to export dispatcher.  See function
>       org-export--dispatch-action.
> 
> 
> Reported by Nathan Neff https://lists.gnu.org/archive/html/emacs-orgmode/2019-10/msg00179.html.
> 
> It made it possible to scroll the agenda buffer if it's to small to fit everything.

Confirmed. After comment out the part referring to "?\s", "SPC" starts to work as Agenda key again.

**Comment by nixmaniack** [comment]
Thanks @duianto for finding out the change which affected this. We'll have to amend the personal keybinding it seems.

**Comment by nixmaniack** [comment]
I believe there's nothing in Spacemacs that needs be fixed for this and probably `wontfix`/`not-a-bug`.

**Comment by duianto** [comment]
It should probably be reported upstream. Possibly with a request to be able to disable/rebind the scrolling keys so that `SPC` can be user customized again.

**Comment by liny01-nbsa** [comment]
Reported [upstream](https://www.mail-archive.com/emacs-orgmode@gnu.org/msg126406.html).

**Comment by bzg** [comment]
Thanks for reporting this. Fixed in [master](https://code.orgmode.org/bzg/org-mode/commit/2508dfa6).

**Comment by liny01-nbsa** [comment]
> Thanks for reporting this. Fixed in [master](https://code.orgmode.org/bzg/org-mode/commit/2508dfa6).

Thanks for the fix!

**Comment by liny01-nbsa** [comment]
Reported issue is fixed.

**Comment by nixmaniack** [comment]
Wow! I didn't expect such an issue to be fixed in upstream org with this velocity! This gives me hope in reporting org issues at upstream. Thanks @bzg and @liny01-nbsa.

**Comment by nixmaniack** [comment]
@bzg Would it be possible to get a release on elpa with this change? Currently, I'm using git HEAD for this change but would prefer a release.

**Comment by bzg** [comment]
I am preparing the release of Org 9.4, which will be available from GNU ELPA.

This requires some work, it is a big release. If things go well, I hope we can release it before the middle of this month.
