### ISSUE TITLE
Emacs "tabs"

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1313]
So I saw the discussion about having tabs similar to Vim. If this is the case, you almost have exact the same thing: it is called `frame`. Each Emacs frame is a complete new OS window in GUI mode; however, in terminal it works like Vim but does not display tab at the top. These frames in terminal are called *virtual frames*.

- Frames in GUI:

![frames-gui](https://cloud.githubusercontent.com/assets/4818719/7267705/3b168dfe-e8e9-11e4-9bfd-5057b1d643a9.gif)

- Frames in terminal: Do you see the `F1` and `F2` in the modeline? Those are frame number respectively.

![frames-term](https://cloud.githubusercontent.com/assets/4818719/7267702/2446508c-e8e9-11e4-90fd-1bd2b3d0a53c.gif)

@trishume  Emacs manages its own windows for consistent experience across platform and reducing learning burden for users. Imagine without all the windowing functionality in Emacs, it would be difficult to manage Emacs OS windows, because they will have to find one tool to manage their windows on Linux, then another tool on Windows and another tool on OSX when the users has to work on different OS. Tmux and the such does not work well on Windows and certainly it cannot manage OS windows. What you want is Emacs frames, and with a window manger like i3, it looks exactly like Vim tabs but better since the actual window manager of OS manages the frames.

@syl20bnr Currently Spacemacs modeline does not support frame number, which is an important part of Emacs. I think we should add frame number at the far right. Emacs has a command to switch frame by names, called `select-frame-by-name`.

**Comment by TheBB** [comment]
> @syl20bnr Currently Spacemacs modeline does not support frame number, which is an important part of Emacs. I think we should add frame number at the far right. Emacs has a command to switch frame by names, called select-frame-by-name.

A bit off topic, but I haven't yet found a way to rename frames. Is there one? The default name is the last active buffer, but it would be cool to be able to have dedicated frame names.

**Comment by tuhdo** [comment]
> A bit off topic, but I haven't yet found a way to rename frames. Is there one? The default name is the last active buffer, but it would be cool to be able to have dedicated frame names.

You can use the command `set-frame-name`. Like the command `select-frame-by-name`, it is unbound.

**Comment by trishume** [comment]
Like @tuhdo mentioned I use GUI frames to manage my different contexts. The general problem with this is that most people's window managers suck shit at *managing windows* :angry:. I solved this by writing my own script for the Hammerspoon OSX window manager that lets me get tab-like window management for Emacs OSX windows:
![screen shot 2015-04-19 at 5 51 11 pm](https://cloud.githubusercontent.com/assets/887610/7278362/ff700344-e8e2-11e4-9c3e-fc82d6d8688f.png)

As @tuhdo also said this isn't very portable. Which is the unfortunate reason that nowadays any good piece of software ends up implementing its own window manager (as Emacs already has, along with iTerm, Vim, Tmux, Chrome, Eclipse, ...) It would be cool if there was a quality method of effectively managing frames within a single GUI window for this reason, like the terminal.

I looked into this before writing my OSX tabs and there isn't a very good place to put the GUI. There is the emacs header line and mode line but those are per window whereas the type of tabs we want are per frame. I think visual feedback about what tabs exist and which one you are on are really important both for knowledge and fast switching.

Perspectives currently falls short both in the visual aspect and I also found it somewhat flakey in other aspects. For example, the method of switching perspectives is way too slow.

**Comment by tuhdo** [comment]
@trishume actually Emacs has its own window for many valid reasons. One reason is that the window Emacs manage automatically inherits everything from Emacs (i.e. all packages of Emacs) whether with `tmux` approach, it's a completely new window of another application.  The use case in which a buffer is on the left and the REPL on the right is very strong and useful. Or when you read man or Info pages, [follow-mode](http://www.gnu.org/software/emacs/manual/html_node/emacs/Follow-Mode.html) is extremely useful. You create another Emacs "workspace" (frame) and read doc there. 1 big left window and 2 small right windows is quite common. So I think it's valid for application to manage its own window; OS devs cannot make window manager behave like `i3` because majority of (non-technical) users could not use that.

The only thing we should do now is to adopt Spacemacs users the habit of using frames in replacement of Vim tabs by writing documentation and add key bindings for some frame commands.

**Comment by trishume** [comment]
Agreed it is great that Emacs implements its own windows. I'm just lamenting the fact that most window managers are crap so Emacs has to do it. 

I have an idea for a WM that would use a tree-like structure and a good user-preference and app-hint system that would basically allow the default to be exactly like a traditional WM except that it would manage chrome's tabs and emacs windows and things in a consistent way. With the bonus of being easily adapted for things like tiling and adding split windows to Chrome. But that's just a dream.

Also agreed about the course of action being to add better frame management.

**Comment by tuhdo** [comment]
> Agreed it is great that Emacs implements its own windows. I'm just lamenting the fact that most window managers are crap so Emacs has to do it.

Actually I was saying that Emacs has its own window manager not because of OS WM is bad, but because it's a need, since Emacs window are integrated and can share things with each other while OS windows are not integrated. Back in the old days Emacs does not have a server mode so you cannot just run multiple Emacs clients.

> I have an idea for a WM that would use a tree-like structure

Have you take a look at [stumpwm](https://github.com/stumpwm/stumpwm). It's written in Common Lisp and can be manipulated directly inside or outside Emacs (only exist in Linux though).

**Comment by trishume** [comment]
@tuhdo That's part of what I was saying about OS WMs. They can be integrated if you can hint the WM towards the right positioning. If a good tree-based WM existed Emacs could hint saying "new diff window, prefer side split from existing" and then if it is put by the side it can sync it up with the other window (it is all controlled by the same process). Unfortunately apps would have to have been built like this with a good WM from the start, so it is a moot point now.

I have looked at stumpwm. Of all the linux WMs i3 is the closest to what I want. But by the time I switch to linux Wayland should be ready so I plan on writing my dream WM as a Wayland compositor when I eventually switch...

**Comment by rphillips** [comment]
added a simple binding. Helm is used by default it seems.

**Comment by ralesi** [comment]
What about changing `M-1` through `M-9` to select window as currently bound, but if only one window in frame, go to that numbered frame instead?

**Comment by syl20bnr** [comment]
I never thought about using frames as Vim tabs, makes sense. What do we have in the Helm arsenal to support easy management of frames ?

The tabs bar is graphical sugar and not very important, what is important is the workflow. Replicating the buffers workflow with frames would be both consistent and powerful.

But I wonder if it is possible. To make an intuitive workflow based on frames we have to get this feature:
when the user switch buffer, go to the frame where the buffer "belongs" (i.e. frames where the buffer has been explicitly opened, there could be several frames, no problem).  But I fear that buffers belong to all the opened frame by default.

**Comment by tuhdo** [comment]
> But I wonder if it is possible. To make an intuitive workflow based on frames we have to get this feature:
> when the user switches buffer, go to the frame where the buffer "belongs" (i.e. frames where the buffer has been explicitly opened, there could be several frames, no problem). But I fear that buffers belong to all the opened frame by default.

`ido-switch-buffer` already does it this way. Unfortunately, `helm-mini` does not work this way;; `helm-mini` keeps the same behavior of stock `switch-to-buffer` command, and you can have to explicitly press `C-c C-o` to switch to other frame that has that buffer already opened, or pop a new frame with the buffer if there's none. I may post a feature request to Helm if we can get the behavior of switching to frame automatically.

**Comment by tuhdo** [comment]
This will do what we want with `helm-mini` or `helm-buffers-list`:

```elisp
(define-key helm-buffer-map (kbd "RET") (lambda (buf)
                                          (interactive "P")
                                          (helm-quit-and-execute-action
                                           (lambda (buf)
                                             (ido-visit-buffer buf ido-default-buffer-method t)))))
```

Basically `RET` in `helm-mini` or `helm-buffers-list` binds to stock `switch-to-buffer`. We simply reusing the way Ido switch buffer here. Also thanks to @michael-heerdegen for this hint.

**Comment by trishume** [comment]
The tab bar is more important than you might think. My favourite thing about tabs is using `M-1` through `M-9` to switch to them quickly. This can only be done if you always have a tab bar that shows you the order and names (and maybe even a number) so that you know which number to hit. Just window numbers (which I love) would be far less quick if you couldn't see them all the time.

That doesn't mean the feedback has to be the tab bar, just something so that you know how to switch to exactly the frame you want in one command. Helm switching is a bit too slow for my tastes, compared to how zippy window and tab numbers are.

**Comment by tuhdo** [comment]
@trishume If you want something like that, you have [frame-tag](https://github.com/liangzan/frame-tag.el), no visual appearance though.

You can explore all kinds of frame support [here](http://emacswiki.org/emacs/CategoryFrames).

**Comment by syl20bnr** [comment]
We have to wonder what frames give that perspective does not.

For the numbers, they are indeed useful if the associated items does not change a lot during a coding session. If they change too much then I claim that the consistency of switching to a buffer by name is quicker, the brain has less to process visually (we are bad for this). There is also buffer back and forth key bindings which lower the need of numbers. Once again if the items associated to the number don't change very often then numbers can deliver efficient UX (the windows are a good example of this, the predefined workspaces in A WM are another example, the idea is to suppress the need for visual processing).

**Comment by tuhdo** [comment]
> We have to wonder what frames give that perspective does not.

- Does not depend on `perspective`. It's built-in.
- Behave the same way as Vim tabs. It does not create a local workspace with local buffer set so we can easily exchange information between frames.
- Perspective works best in combination with Projectile.

But in general, I think it's simpler to use perspective. It's just that as @syl20bnr, we need an automatic command that when switching buffer, it switches to that perspective automatically and effectively restoring the window configuration for that perspective, effectively achieve something like Vim tab with the power of Helm for managing large amount of candidates (in this case, "tabs"). For this, we can advise `switch-to-buffer`, since Helm uses `switch-to-buffer` to switch buffer anyway. Or maybe we can request upstream.

**Comment by syl20bnr** [comment]
I see another benefit with perspective, it may seems stupid but...
perspective works in the same frame. This is a huge benefit. Different
frames means some additional management required at the OS window manager.
The second benefit is serialization, it _may_ be easier to restore
perspectives than frames for the same reason mentioned above. For frames we
have the issue of positioning them.

-syl20bnr-

**Comment by tuhdo** [comment]
@syl20bnr I agree. What we need is a command that switches to a perspective automatically when switching a buffer/file in a project or currently in a perspective, effectively restores the window layout. There, we have Vim tabs now.

**Comment by tuhdo** [comment]
Also, [eyebrowse](https://github.com/wasamasa/eyebrowse) is also worth checking. It behaves similar to i3 window manager. That is, each window configuration is given a number and you can switch between them by pressing `C-c C-w <number>` (we can bind it to anything else). It's small and simple enough that makes it closer to Vim tabs i.e. you don't have local buffers per workspace.

The nice thing is that when you press `C-c C-w <number>` and no such workspace exists, it creates one automatically. This is the exact same behavior with `i3` window manager. It also has support for Vim key bindings when Evil is detected. That is, you can press `1gt` to go to first "tab" (window config) or `3gt` to go to 3rd "tab".

**Comment by daviwil** [comment]
@tuhdo Eyebrowse looks awesome, thanks for that!  I've been wanting something like this, I just didn't know it existed yet.

**Comment by syl20bnr** [comment]
Ahah:

> eyebrowse is a global minor mode for Emacs that allows you to manage your window configurations in a simple manner, just like tiling window managers like **i3wm** with their workspaces do. It displays their current state in the modeline by default. The behaviour is modeled after **ranger**, a file manager written in Python.

i3 and ranger in the description... I will definitely check it :-)

**Comment by tuhdo** [comment]
For this issue: https://github.com/wasamasa/eyebrowse/issues/25, I did a workaround with the hook `eyebrowse-post-window-switch-hook`:

```elisp
(defvar spacemacs-slot nil)
(defun spacemacs-eyebrowe-maybe-switch-home ()
  (interactive "P")
  (unless (member slot spacemacs-slot)
    (push slot spacemacs-slot)
    (delete-other-windows)
    (spacemacs/home)))
(add-hook 'eyebrowse-post-window-switch-hook 'spacemacs-eyebrowe-maybe-switch-home)
````

So now if you switch to a new config and the config is not available, just go home.

**Comment by tuhdo** [comment]
I updated the code to handle closing a window config it should also delete the active slot list that Spacemacs keeps track of.

**Comment by tuhdo** [comment]
@syl20bnr should we add `eyebrowse` to `.spacemacs` by default and add `gt` and `gT` key bindings?

**Comment by syl20bnr** [comment]
Yes we will surely add it in the template but I want us first to play a bit with it and see what kind of feature we should contribute to the package.
Yes for `gt`, `gT` I forgot about them, it would be nice to have them.
As I see it, eyebrowse could even be part of default spacemacs, need some time to see where it goes but it is very promising.

**Comment by wasamasa** [comment]
@syl20bnr: `eyebrowse-setup-opinionated-keys` contains code for `gt` and `gT` and a few more, I plan to implement the remaining vim tab commands though.

**Comment by tuhdo** [comment]
@syl20bnr Please note that `dired-mode` the `gt` and `gT` of `eyebrowse` is not working but are shadowed by other key bindings: `g` to refresh buffer and `t` to mark all items. So you will need to evilified this mode as well.

**Comment by tuhdo** [comment]
@CestDiego @syl20bnr we could replace `C-TAB` of `org-mode` with `C-<right>`, which is bound to right word, so we can use `C-TAB` and `C-S-TAB` to cycle back and forth between workspaces.

**Comment by CestDiego** [comment]
@wasamasa @tuhdo if dired buffer get's evilified can we have gg to go to the first file and G to the last? :P also evil-search is not working in dired.

**Comment by ralesi** [comment]
@CastDiego, I will have a vinegar layer out later this week that has g and G set up for dired.

**Comment by gberenfield** [comment]
I'm using
```
(define-key evil-motion-state-map (kbd "g]") 'eyebrowse-next-window-config)
(define-key evil-motion-state-map (kbd "g[") 'eyebrowse-prev-window-config)
```
which works well for me for jumping between windows.

I'm very new to emacs/spacemacs (coming from vim) but find the only missing link I'd personally like is to include the window # on the powerline/airline bar at the bottom. But it works quite well for my workflow.

I did copy in syl20bnr's "develop" branch eyebrowse package and see the nifty unicode circled numbers on ```<SPC>W```. Now if that were on the powerline bar (for me), perfect.

**Comment by StreakyCobra** [comment]
`eyebrowse` and `perspectives` are both offering this functionality in `develop`, so tagging it as `Fixed in develop` :smile:
