### ISSUE TITLE
how to change line character numbers when using python-format-buffer

### ISSUE THREAD

**Issue by csfreebird** [syl20bnr/spacemacs#13137]
I tried following in .spacemacs, but not work
M-x customize-variable
'(flycheck-flake8-maximum-line-length 180)

**Comment by Trapez** [comment]
All the formatters are [documented](http://flake8.pycqa.org/en/2.6.0/config.html).

**Comment by csfreebird** [comment]
Configured the ~/.config/flake8 file as described below on Ubuntu, then restart spacemacs, does not work.

User (Global)
The user settings are read from the ~/.config/flake8 file (or the ~/.flake8 file on Windows). Example:

[flake8]
ignore = E226,E302,E41
max-line-length = 160
exclude = tests/*
max-complexity = 10

**Comment by csfreebird** [comment]
I find a way. config layer like below:
```
     (python :variables
          python-format-on-save t
          python-formatter 'yapf
          python-sort-imports-on-save t
          python-backend 'anaconda)
```

According to the yapf documentation, create ~/.config/yapf/style file, add following
```
   [style]
   based_on_style = pep8
   spaces_before_comment = 4
   split_before_logical_operator = true
   column_limit = 180
```
