### ISSUE TITLE
org-notmuch renamed to ol-notmuch in org 9.3.1

### ISSUE THREAD

**Issue by PhDyellow** [syl20bnr/spacemacs#13139]
https://github.com/syl20bnr/spacemacs/blob/71d4e15e67feda18692ee35d50f3d98216cd90aa/layers/%2Bemail/notmuch/packages.el#L122

I upgraded to the latest version of spacemacs devel, and org 9.3.1, and recieved an error that "org-notmuch" could not be found.

According to https://notmuchmail.org/emacstips/ "org-notmuch" had been renamed to "ol-notmuch", so the line of code linked above needs to change.

The change is pretty recent, org version 9.2 named the file "org-notmuch".

**Comment by loysollivier** [comment]
Found it too.
Sent a PR #13149

**Comment by PhDyellow** [comment]
Thanks, should I close this now or after the PR is merged?

**Comment by loysollivier** [comment]
I'd say leave it open and let the admins do the sorting / closing :)

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
[notmuch] rename require to 'ol-notmuch #13149

If that fixed the issue for you then feel free to close this issue.
