### ISSUE TITLE
New to emacs - found the bug but not sure how to report

### ISSUE THREAD

**Issue by duytrung** [syl20bnr/spacemacs#13144]
Hello,

I found the bug but not sure how to report it in MSYS2 command console:
I ran emacs --debug-init and found the following output:

![image](https://user-images.githubusercontent.com/2046672/71652456-ab80f400-2d75-11ea-9221-b9a8d4d0d8b3.png)

I'm new to emacs and learn the new commands. Sorry for not copying the text

Thanks a lot

**Comment by emacs18** [comment]
I think this is a problem with using master branch of spacemacs.
I suggest you use develop branch, i.e., go to ~/.emacs.d directory and type
```
git checkout -b develop origin/develop
```
then restart emacs.

**Comment by smile13241324** [comment]
@duytrung master is pretty old right now, we are working on providing an updated version but until this is finished please stick to develop which constantly pushes forward.

Can you already tell whether your bug persist on develop?
