### ISSUE TITLE
Unable to load evil-unimpaired on Windows emacs 26.3

### ISSUE THREAD

**Issue by BraydonKains** [syl20bnr/spacemacs#13141]
DISCLAIMER: This feels like something I'm doing wrong rather than a bug, but if it turns out to be a bug I'm happy to close this and make a proper report through spacemacs. 
I searched open issues and did not see anything like this, and any of the issues I searched seemed unrelated (I did find #6933 but the suggested solutions did not work; it's also a different error).
I am completely new to emacs and not awesome at Windows; I am usually a Linux and vim guy.

I am trying to set up spacemacs on Windows 10. I downloaded emacs 26.3 from the nearest GNU mirror. I cloned the spacemacs repo into `~/.emacs.d` and started emacs. Everything worked as expected except for loading this package. 

`An error occurred while installing evil-unimpaired (error: (error Invalid version syntax: ‘Copying permissions to: Operation not permitted, c:/Users/bkains/.emacs.d/.cache/quelpa/build/evil-unimpaired/evil-unimpaired.el’ (must start with a number)))`

I have tried:
- Changing line endings to dos or unix (same result either way)
- Removing the .cache directory and restarting to redownload the package

Any possible help would be appreciated!

**Comment by emacs18** [comment]
I think this is a problem with using master branch of spacemacs.
I suggest you use develop branch, i.e., go to ~/.emacs.d directory and type
```
git checkout -b develop origin/develop
```
then restart emacs.

**Comment by BraydonKains** [comment]
Thanks for the suggestion, it solved the issue. Cheers!
