### ISSUE TITLE
recently added flycheck-elsa breaks many things

### ISSUE THREAD

**Issue by emacs18** [syl20bnr/spacemacs#13151]
On Dec 27, https://github.com/syl20bnr/spacemacs/commit/9b836093709160ce3fe993400a5a2b9d1f103bd4 was checked in which
added use of flycheck-elsa in emacs-lisp mode. This is causing many
problems. First SPC SPC is no longer bound which normally should be
bound to helm-M-x. This is how I discovered this problem. Second many
things related with emacs-lisp mode are broken, e.g., attempting to run
pp-eval-expression on load-path results in the same error that is also
reported when emacs starts up, i.e., these lines in *Message* buffer:

```
eieio-defclass-internal: Given parent class package-recipe is not a class
```

I think the problem is that

1. flycheck-elsa package requires cask package
2. cask package requires package-build package
3. spacemacs has an old copy of package-build.el file within in it which
   is not compatible with cask.el which requires more modern version of
   package-build.el.

More specifically package-build.el from package-build package has line
such as this which package-build.el embedded within spacemacs does not:

``` elisp
(defmethod package-build--checkout :before ((rcp package-recipe))
```

For now I resolved this problem by simply deleting
core/libs/package-build.el from my copy of spacemacs so that package-build.el
that comes with package-build package would be used.

**Comment by conao3** [comment]
FYI: Merged the PR; removing cask dependency on `flycheck-cask`.

**Comment by emacs18** [comment]
Thanks.  I verified that picking up updated flycheck-elsa resolved the problems I reported.
