### ISSUE TITLE
Can't disable auto-indent when pasting after emacs-evil patch

### ISSUE THREAD

**Issue by pszynk** [syl20bnr/spacemacs#13160]
This bug was present before #8897 and was fixed on develop #12240

But, after recent changes to emacs-evil (issue emacs-evil/evil#1199 and pr emacs-evil/evil#1222) 
`SPC u p` no longer pastes without indent, but rather pastes  4 times (which is an expected behavior from the look of emacs-evil creators)

This is rather troublesome. I'd argue that pasting 4 times after `SPC u p` makes little sense but it is consistent with standard emacs behavior. Still it would be nice to have this option of pasting without auto-indent. 

I would like to contribute and propose some fixes (I'm not to experienced in emacs/elisp).
I see two ways to approach this:
* abandon the idea of raw paste triggered by universal argument `SPC u`, maybe it's not the best idea to confuse it with the option of pasting n-times. Use a different key combination for raw paste i.e. `_p`
* check if universal argument `<= 0`, if so assume that user wants a raw paste. Pasting 0 or less times makes no sense either way. `SPC u - p` or `M-- p` would do raw paste.

**Comment by pszynk** [comment]
Actually added a pr #13161 so `SPC u -<n> p` pastes `n` times without auto-indent. This allows for multiple non-auto-indent and doesn't clash to much with intended use of universal argument (at least as I see it)

**Comment by smile13241324** [comment]
@pszynk your PR has been merged, can you double check whether this issue is still present and close this bug if it is solved please.

**Comment by pszynk** [comment]
@smile13241324 yep, sorry for the hanging bug, closing.
