### ISSUE TITLE
Constant freezes in evil-delete-char (using a minimal configuration on OpenBSD)

### ISSUE THREAD

**Issue by bforte** [syl20bnr/spacemacs#13178]
#### Description

Emacs froze on various occasions (I recall deleting two lines with `d2j` and using `x` to cut the current character) to the point where I had to kill it by external means (`kill -15`).

I'm new to Emacs, so I don't know how to fix this myself but did my best to track the freezes. Their origin seems to come from `evil-delete`/`evil-delete-char`. The behaviour is fairly reproducible by using `x` in any file, it makes Spacemacs barely usable.

#### Reproduction guide
1. `rm -rf ~/.emacs.d && git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
2. Start Emacs
3. Use a minimal configuration:
  - *What is your preferred editing style?* -> choose *vim*
  - *What distribution of spacemacs would you like to start with?* -> choose *spacemacs-base* (same with *spacemacs*, just doing this to reduce the potential sources of the bug)
  - *What type of completion framework do you want?* -> choose *None* (again, this doesn't seem to matter.. I initially picked *ivy* here)
4. Success.. The only warning in \*spacemacs\*: *Cannot find any of the specified fonts (Source Code Pro)! Font settings may notbe correct.* (behaviour persists when using an installed font)

These steps don't always, but with high "success" rate, reproduce the error:

5. create new file `:e bug.txt` and:
  - enter some characters (`a` in the following backtraces, doesn't matter though)
6. use `x`

*Observed behaviour:*

7. Emacs freezes, `C-g` doesn't work, not even the window-manager can close it
8. Either use `xkill` and clean up or use `kill -15` work to kill it

*Expected behaviour:*

The behaviour of `evil-delete-char`: cut the character and put in `"`, at least please don't freeze. It makes Spacemacs unusable.

#### System info

```
$ uname -a
OpenBSD host.name 6.6 GENERIC.MP#3 amd64
$ emacs --version
GNU Emacs 26.3
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

#### Backtrace

Using `kill -SIGUSR2` I was able to get some backtraces. A freeze with `x` produced (it always looks the same):

```
Debugger entered--Lisp error: (quit)
  x-get-selection-internal(CLIPBOARD STRING nil nil)
  #f(compiled-function (selection-symbol target-type &optional time-stamp terminal) #<bytecode 0x35efd1>)(CLIPBOARD STRING)
  apply(#f(compiled-function (selection-symbol target-type &optional time-stamp terminal) #<bytecode 0x35efd1>) (CLIPBOARD STRING))
  gui-backend-get-selection(CLIPBOARD STRING)
  gui-get-selection(CLIPBOARD STRING)
  gui--selection-value-internal(CLIPBOARD)
  gui-selection-value()
  kill-new("a")
  evil-yank-characters(55 56 nil nil)
  evil-yank(55 56 exclusive nil nil)
  evil-delete(55 56 exclusive nil)
  evil-delete-char(55 56 exclusive nil)
  funcall-interactively(evil-delete-char 55 56 exclusive nil)
  call-interactively(evil-delete-char nil nil)
  command-execute(evil-delete-char)
```

To copy it here I marked it all with `vgg` and `y`anked it which produced another freeze:

```
Debugger entered--entering a function:
* undo-tree-post-gc()
  #f(compiled-function () #<bytecode 0xb241f0ed>)()
  evil-yank(1 809 line nil nil)
  funcall-interactively(evil-yank 1 809 line nil nil)
  call-interactively(evil-yank nil nil)
  command-execute(evil-yank)
  recursive-edit()
  debug(error (quit))
  x-get-selection-internal(CLIPBOARD STRING nil nil)
  #f(compiled-function (selection-symbol target-type &optional time-stamp terminal) #<bytecode 0x35efd1>)(CLIPBOARD STRING)
  apply(#f(compiled-function (selection-symbol target-type &optional time-stamp terminal) #<bytecode 0x35efd1>) (CLIPBOARD STRING))
  gui-backend-get-selection(CLIPBOARD STRING)
  gui-get-selection(CLIPBOARD STRING)
  gui--selection-value-internal(CLIPBOARD)
  gui-selection-value()
  kill-new("a")
  evil-yank-characters(55 56 nil nil)
  evil-yank(55 56 exclusive nil nil)
  evil-delete(55 56 exclusive nil)
  evil-delete-char(55 56 exclusive nil)
  funcall-interactively(evil-delete-char 55 56 exclusive nil)
  call-interactively(evil-delete-char nil nil)
  command-execute(evil-delete)
```

Huh, another one by accident: Re-started Emacs and `ESC k`:

```
Debugger entered--Lisp error: (quit)
  x-get-selection-internal(CLIPBOARD STRING nil nil)
  #f(compiled-function (selection-symbol target-type &optional time-stamp terminal) #<bytecode 0x35efd1>)(CLIPBOARD STRING)
  apply(#f(compiled-function (selection-symbol target-type &optional time-stamp terminal) #<bytecode 0x35efd1>) (CLIPBOARD STRING))
  gui-backend-get-selection(CLIPBOARD STRING)
  gui-get-selection(CLIPBOARD STRING)
  gui--selection-value-internal(CLIPBOARD)
  gui-selection-value()
  kill-new("  be correct.")
  copy-region-as-kill(894 907 nil)
  kill-region(894 907)
  kill-sentence(1)
  funcall-interactively(kill-sentence 1)
  call-interactively(kill-sentence nil nil)
  command-execute(kill-sentence)
```

---

I could not repro it with using Emacs+evil only, using the following `init.el` so it does not seem like it is a problem of Emacs.

```
;; load melpa package manager
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

;; update local package index
(unless package-archive-contents (package-refresh-contents))

;; install evil
(setq package-list '(evil evil-leader))
(dolist (package package-list)
  (unless (package-installed-p package)
    (package-install package)))

;; configure evil
(require 'evil)
(evil-mode t)

(require 'evil-leader)
(global-evil-leader-mode)
(evil-leader/set-leader ",")
(evil-leader/set-key
  "b" 'switch-to-buffer
  "w" 'save-buffer)
```

**Comment by bforte** [comment]
Checked on dev branch (ie. `git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d`), and the behaviour seems to have changed.

Now the `x` action sometimes (often like before) "freezes" Emacs, but as soon as I try to move my mouse it will eventually work. This is pretty weird, the bug on master suggests some non-terminating loop but this does something else entirely.

The behaviour also vanishes, it's only the first time when Emacs started. I can live with that, but is it a smart idea to use the dev branch? Probably not.

**Comment by st-j** [comment]
I encountered the same problem on my Linux machine today:
- RHEL 8
- Emacs 26.1
- Spacemacs develop branch

Using any of the evil cut/yank commands (x, dd, y) in a text file causes emacs to freeze every time, the backtrace produced with `kill -SIGUSR2` looks extremely similar to bforte's backtrace above:

```
   * symbol-overlay-refresh(1 5 0)
     x-get-selection-internal(CLIPBOARD UTF8_STRING nil nil)
     #f(compiled-function (selection-symbol target-type &optional time-stamp terminal) #<bytecode 0x534949>)(CLIPBOARD UTF8_STRING)
     apply(#f(compiled-function (selection-symbol target-type &optional time-stamp terminal) #<bytecode 0x534949>) (CLIPBOARD UTF8_STRING))
     gui-backend-get-selection(CLIPBOARD UTF8_STRING)
     gui-get-selection(CLIPBOARD UTF8_STRING)
     gui--selection-value-internal(CLIPBOARD)
     gui-selection-value()
     kill-new(#("fdfd\n" 0 5 (fontified t wrap-prefix "" yank-handler (evil-yank-line-handler nil t))))
     evil-yank-lines(126 131 nil nil)
     evil-yank(126 131 line nil nil)
     evil-delete(126 131 line nil nil)
     funcall-interactively(evil-delete 126 131 line nil nil)
     call-interactively(evil-delete nil nil)
     command-execute(evil-delete)
```
I don't know what causes the error, but have made an interesting observation: while the above freezes occured, I had a Fedora 31 guest running in KVM (with virt-manager, in case that matters). After I shut down the VM, deleting/yanking started to work as expected in emacs.

The problem did not reappear when booting the VM again, so I unfortunately cannot reproduce the strange bug at the moment.

**Comment by bforte** [comment]
The bug seems to occur whenever the clipboard (XA_CLIPBOARD) is empty. If you have something in the clipboard the bug doesn't appear.

**Comment by overchu** [comment]
I have the same problem since months. But it is only occuring from time to time. It seems to be a clipboard related issue since the `pass` password manager is also affected. Same as emacs `pass` hangs when it is supposed to write a password to the clipboard. All other programs work without issues. Also `pash` a more simple `pass` replacement is working while `pass` and emacs are affected.
I will try to find what `pass` and emacs or spacemacs have in common regarding the clipboard.

**Comment by overchu** [comment]
![grafik](https://user-images.githubusercontent.com/76196884/119437799-70f46e80-bd51-11eb-98ee-95077e3c9543.png)

Sorry can not copy and paste out of emacs due to the nature of the bug. So here is a screenshot.

**Comment by overchu** [comment]
`pass` copies to `XA_CLIPBOARD` while `pash` copies to the default which is `XA_PRIMARY`.

**Comment by lebensterben** [comment]
looks like upstream bug

**Comment by overchu** [comment]
Oh, and I am on develop and the bug persists since at least four month maybe longer.

**Comment by lebensterben** [comment]
definitely something wrong with clipboard.
do you use bsd or Linux? x11 or Wayland?

**Comment by overchu** [comment]
Thanks for reaching out.

I use Wayland on Linux (Fedora 34)
Gnome 3

**Comment by lebensterben** [comment]
I suggest to post this finding to Emacs Dev mail-list. They should have better idea of what's going on.
