### ISSUE TITLE
Emacs run batch using run-hooks 'emacs-startup-hook dies

### ISSUE THREAD

**Issue by braun-steven** [syl20bnr/spacemacs#13179]
#### Description :octocat:
I'm trying to export my agenda-views via `org-batch-store-agenda-views` from the commandline. For this I'm running:

```sh
emacs -batch -l ~/.emacs.d/init.el --eval "(run-hooks 'emacs-startup-hook)" --eval '(org-batch-store-agenda-views)'
```

Which outputs
```
...
Skipping check for new version (reason: dotfile)
Wrong type argument: hash-table-p, nil
Warning (emacs): recentf mode: Wrong type argument: hash-table-p, nil
Error in kill-emacs-hook (ido-kill-emacs-hook): (wrong-type-argument hash-table-p nil)
```

and exits.

Running `org-store-agenda-views` (non-batch version) from within emacs GUI works without any issue.

#### Reproduction guide :beetle:
Run
```sh
emacs -batch -l ~/.emacs.d/init.el --eval "(run-hooks 'emacs-startup-hook)" --eval '(org-batch-store-agenda-views)'
```

*Observed behaviour:* :eyes: :broken_heart:
Output:
```
...
Warning (emacs): recentf mode: Wrong type argument: hash-table-p, nil
Error in kill-emacs-hook (ido-kill-emacs-hook): (wrong-type-argument hash-table-p nil)
```

*Expected behaviour:* :heart: :smile:
- Emacs shouldn't error out and produce the agenda export file

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d4a27babf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript vimscript html csv helm
            (auto-completion :variables spacemacs-default-company-backends
                             '(company-files company-capf)
                             auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
            emacs-lisp git markdown org
            (shell :variables shell-default-term-shell "/bin/zsh" multi-term-program "/bin/zsh" shell-default-height 30 shell-default-position 'bottom shell-scripts-backend 'lsp)
            (spell-checking :variables enable-flyspell-auto-completion nil spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
            syntax-checking
            (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
            themes-megapack
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            (gtags :variables gtags-enable-by-default t)
            (latex :variables latex-enable-auto-fill t)
            pdf
            (c-c++ :variables =c-c++-backend= 'lsp-clangd)
            gpu prolog deft)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```

```

**Comment by smile13241324** [comment]
Hmm using spacemacs as a batch is something I haven't seen in a looooonnnnnggggg time.
I will have a look.

**Comment by smile13241324** [comment]
Sorry to say but I have no clue why this is not working maybe someone from the community is more familiar with the emacs batch use-case and can help here.

**Comment by JAremko** [comment]
You can try cleaning up the `kill-emacs-hook` variable.

**Comment by JAremko** [comment]
The problem, most likely, is that the `ido-kill-emacs-hook` thingy tries to interact with a user and fails in a strange way :thinking:
