### ISSUE TITLE
lsp-ui-doc-enable nil and lsp-ui-sideline-enable nil dont seem to be respected at least in python mode...

### ISSUE THREAD

**Issue by twillis** [syl20bnr/spacemacs#13183]
#### Description :octocat:
lsp-ui-doc or sideline does not respect configuration params and shows annoying doc windows that take up the whole damn window

#### Reproduction guide :beetle:
- Start Emacs
- create new file named test.py

add code

import json

json.loads(

*Observed behaviour:* :eyes: :broken_heart:
witness a thorough doc that would be helpful the first time you might use loads that takes up the majority of window so much that you can only see a few lines of text in what you are editing.
![lsptakingover](https://user-images.githubusercontent.com/183699/72353132-81063380-36b1-11ea-992a-7089634d01af.png)

*Expected behaviour:* :heart: :smile:
when these things pop up it really gets me out of my flow. I would rather not see docs unless I specifically ask for it. 99% of the time this behavior though it may be neat and ide like is not useful at all... I have code to write. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3d39b98e9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible typescript rust windows-scripts docker nginx scheme helm csv sql auto-completion clojure common-lisp
         (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'rbenv ruby-backend 'robe)
         (python :variables python-backend 'lsp python-test-runner
                 '(pytest nose))
         (javascript :variables javascript-backend 'lsp)
         emacs-lisp markdown
         (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t org-enable-bootstrap-support t)
         nim syntax-checking version-control git shell ibuffer yaml html colors erc react pandoc
         (lsp :variables lsp-navigation 'simple lsp-ui-doc-enable nil lsp-ui-sideline-enable nil)
         dap restclient)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by yyoncho** [comment]
Posting also in original issue: use `lsp-signature-auto-activate`

**Comment by yyoncho** [comment]
(this could be closed)
