### ISSUE TITLE
Setting dotspacemacs-line-numbers 'relative does not work as expected in spacemacs base - happens again

### ISSUE THREAD

**Issue by wangggong** [syl20bnr/spacemacs#13189]
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs. If the
bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template)
You can delete this message to start typing.

Setting dotspacemacs-line-numbers 'relative does not work as expected in spacemacs base #9487 happens again.

Myself's solution: add linum-relative package. Works well, but boring.

**Comment by emacs18** [comment]
Relative line number mode works fine for me using latest develop branch of spacemacs.

Can you describe what you expected to see and what you actually see to claim that it is not working?

**Comment by wangggong** [comment]
> Relative line number mode works fine for me using latest develop branch of spacemacs.
> 
> Can you describe what you expected to see and what you actually see to claim that it is not working?

I used master branch for "reliablity". Didn't try develop branch, but thank you, I'll try it.

**Comment by duianto** [comment]
The `develop` branch uses the built in Emacs 26 line numbers. 

The `develop` branch is also the recommended branch until the next version is released (I don't know when that is).

There have been a lot of changes since the `master` branch:
https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop
