### ISSUE TITLE
using pdumper results in error wrong-type-argument

### ISSUE THREAD

**Issue by kvaneesh** [syl20bnr/spacemacs#13185]
#### Description :octocat:
using pdumper results in error wrong-type-argument

#### Reproduction guide :beetle:
- Start Emacs
- use spacemacs/dump-emacs

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.60
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 96ef7b23a25c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python html markdown
	(org :variables org-enable-reveal-js-support t)
	treemacs
	(helm :variables helm-grep-file-path-style 'relative)
	emacs-lisp notmuch
	(git :variables magit-revision-insert-related-refs nil magit-revision-show-xref-buttons nil magit-backup-mode nil)
	asm
	(gtags :variables gtags-enable-by-default t)
	(lsp :variables lsp-navigation 'both lsp-ui-doc-enable nil lsp-enable-file-watchers nil lsp-enable-indentation nil lsp-ui-peek-always-show t lsp-ui-doc-use-webkit t lsp-use-native-json t lsp-enable-semantic-highlighting t lsp-ui-flycheck-live-reporting nil lsp-ui-sideline-enable nil)
	(c-c++ :variables c-c++-backend `lsp-clangd lsp-clients-clangd-executable "/llvm-project/build/bin/clangd" lsp-clients-clangd-args
	       `("-background-index" "-header-insertion=never"))
	(auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-snippets-in-popup t auto-completion-use-company-box t auto-completion-private-snippets-directory nil)
	(shell :variables shell-default-position 'bottom shell-default-height 30)
	mycustom version-control
	(multiple-cursors :variables multiple-cursors-backend 'evil-mc))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
Error: (error (wrong-type-argument number-or-marker-p nil))
  (undo-tree-mode 1)
  (turn-on-undo-tree-mode)
 .....
```

**Comment by kvaneesh** [comment]
Updated to latest emacs-27 branch and now i get
```Skipping check for new version (reason: dotfile)
unsupported object type in dump: module function
Warning (emacs): recentf mode: Wrong type argument: hash-table-p, nil

Process spacemacs-dumper exited abnormally with code 255
```

**Comment by kvaneesh** [comment]
That was due to my custom layer that was using magit-libgit package. What config changes I need to make to support external C modules?

**Comment by duianto** [comment]
I don't know anything about pdumper, but if by modules you mean compiling Emacs with module support, then you'll add this argument:
```
./configure --with-modules
```

Here's some instructions how to compile Emacs:
https://gist.github.com/Yevgnen/316e7e69fc224d0c2722222795944c84

**Comment by kvaneesh** [comment]
The error was actually due to the usage of external modules. The question was how to what changes i need to make in the spacemacs config so that we can avoid `unsupported object type in dump: module function`. I possibly need to unload the module before I call dump-emacs.

**Comment by mphojele** [comment]
set your `dotspacemacs-emacs-pdumper-executable-file` to the emacs binary in the directory you are building in or first really install emacs 27 rather than running it locally. My assumption is that you have another emacs in your path that isn't the one you are currently running.

**Comment by smile13241324** [comment]
I am totally uneducated when it comes to dumping but we just merged a bunch of dumper fixes in develop. Care to try it out and see whether this solved your issue?

**Comment by kvaneesh** [comment]
As explained here, to use https://lists.gnu.org/archive/html/emacs-devel/2020-02/msg00148.html we need to have the ability to unload a few packages before we can take a dump. In my case, it was the usage of the emacs external module (libgit2) that was causing the issue. I was wondering if there is a spacemacs way to specifying what to unload before taking a dump and load them back after taking the dump

**Comment by smile13241324** [comment]
Hmmm as far as I understand the code spacemacs tries to determine that on its own. However I don't think it checks for external modules. Not sure if this can be done maybe just providing a list where external modules must be set and then unloading them before dumping would be the way to go.

I can try to have a look at this however I will definitely need some help for testing it.
