### ISSUE TITLE
Some packages in .emacs.d/private/local are not found when loaded via dotspacemacs-additional-packages

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#13180]
#### Description :octocat:
Some packaged in `.emacs.d/private/local` directory are not found, while other packages are found. For example I have three files in the /private/local directory, [helm-recoll.el](https://github.com/emacs-helm/helm-recoll), [helm-tracker.el](https://github.com/gdkrmr/helm-tracker) and [ob-racket.el](https://github.com/xchrishawk/ob-racket), after adding the three packages to `dotspacemacs-additional-packages` the helm-recoll package is loaded correctly while my spacemacs complains that the helm-tracker and ob-racket packages are unavailable and asks if the package names are misspelled.

If the files are loaded interactively with `load-file` then all packages load correctly.

#### Reproduction guide :beetle:
- Start Emacs
Place the files [helm-tracker.el](https://github.com/gdkrmr/helm-tracker), [ob-racket.el](https://github.com/xchrishawk/ob-racket) and [helm-recoll.el](https://github.com/emacs-helm/helm-recoll) in `.emacs.d/private/local` directory, add `helm-recoll`, `helm-tracker` and `ob-racket` to `dotspacemacs-additional-packages`, then start spacemacs.

*Observed behaviour:* :eyes: :broken_heart:
At startup spacemacs messages that the packages helm-tracker and ob-racket are not available. And asks if their names are misspeled. On the other hand, the helm-recoll is loaded correctly. 
*Expected behaviour:* :heart: :smile:
Expected behavior is that all packages load correctly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d4a27babf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript scheme racket html octave python hy jupyter shell-scripts pdf latex prodigy
            (orgwiki :variables org-wiki-location "~/Sync/org/wiki")
            eww themes-megapack auto-completion better-defaults emacs-lisp git helm lsp markdown multiple-cursors
            (org :variables org-enable-org-journal-support t)
            shell spell-checking syntax-checking
            (treemacs :variables treemacs-use-follow-mode 'tag))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by dalanicolai** [comment]
I did a git pull to sync with the latest development branch and I updated packages btw

**Comment by dalanicolai** [comment]
Also I see now that the `helm-recoll` package is available on MELPA so that is probably the reason why that one loads correctly as it is just loaded from MELPA

**Comment by duianto** [comment]
This might be what your looking for:
```elisp
dotspacemacs-additional-packages '(some-package (some-package2 :location local))
```
source, this comment: https://github.com/syl20bnr/spacemacs/issues/2278#issuecomment-283704435
in this issue: Private Additional Packages possible? #2278

**Comment by dalanicolai** [comment]
@duianto Thanks for that answer. It works indeed. I thought I had tried this already because I remember to have seen it in somewhere.

Anyway, I came here because actually I saw only today that documentation on how to use local packages is in the docstring just above the declaration of the `dotspacemacs-additional-packages` variable in the spacemacs file (have to gain experience on where to look for documentation, but getting there). However, although I could find the `:location local` form in [how to add packages to layers](https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org#packagesel), the `:location local` option is not documented in that docstring, neither in the README file in the /private/local directory. Would be nice to document it there.

**Comment by duianto** [comment]
That's the `master` branch documentation, which isn't up to date at the moment.

The latest changes including that suggestion:
```elisp
    ;; A local package
    (some-package :location local)
```
can be found on the `develop` branch:
https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#packagesel

The `develop` branch is the recommended branch until the `master` branch is updated (I don't have any insight into when that is).

**Comment by dalanicolai** [comment]
So actually I was wrong. It still does not work. I don't know why I said the 

    dotspacemacs-additional-packages '(some-package (some-package2 :location local))

solution worked. Maybe I was trying the helm-recoll package (which turned out to be on melpa). But anyway, I tried this solution but it doesn't work.

As I created a [layer for orgwiki](https://github.com/dalanicolai/org-wiki) before using an external package (actually this layer I forked to apply some fixes, but I created a simpler working version before from scratch), I tried to create a layer for helm-tracker to see if it would work in the 'layer-variant'. However that solution also doesn't work. So I guess there must be something wrong with the helm-tracker package. However all of the `helm-tracker.el` file looks fine to me, and the package works well when loaded manually using `load-file`.

(I pulled the latest spacemacs version from the develop branch, and I updated all the packages)

**Comment by dalanicolai** [comment]
Another update. Although the 

    dotspacemacs-additional-packages '(some-package (some-package2 :location local))

trick is still NOT WORKING, wrapping the packages in a local layer does load them correctly. In my previous comment I thought it did not work but it turned out that in the [helm-tracker.el file on github](https://github.com/gdkrmr/helm-tracker/blob/master/helm-tracker.el) the groupname in the defgroup declaration was quoted.

Anyway, I removed the quote from that file in my private layer directory, where that file is in the local directory WITHIN the layer directory. Then the package was loaded correctly.

I also removed the quote from the file in the local directory and tried to load it as additional package, but it did not work.
I then also tried to load the [helm-recoll package](https://github.com/emacs-helm/helm-recoll) as an additional package, but it also did not work.

To be sure I post the code from my .spacemacs file here

    dotspacemacs-additional-packages
    '((helm-recoll :location local)
    (helm-tracker :location local))

**Comment by dalanicolai** [comment]
So finally someone on the Spacemacs gitter channel pointed out the problem. It turns out that using the local package required two modifications:
- the .el file should be placed in its own subdirectory in the `.emacs.d/private/local` directory
- it needs to get loaded  or required explicitly in the user-config section of the .spacemacs file
Finally I found that this solution was already described in issue #8421.

I will see if I can update the documentation and create a pull request.
