### ISSUE TITLE
spacemacs-modeline doesn't display filename: file_%.bb

### ISSUE THREAD

**Issue by sr105** [syl20bnr/spacemacs#13186]
The bitbake build system uses % characters as wildcards in filenames. A typical recipe modification might be included in a file named `gdb_%.bbappend`. Spacemacs displays that filename in the modeline as `gdb_bbappend`.

**Comment by duianto** [comment]
The default spacemacs modeline uses the package:
https://github.com/TheBB/spaceline
It might be best to report it there.

Another option could be to try the modeline theme: `doom`
Which uses the package:
https://github.com/seagle0128/doom-modeline

It's only available on the Spacemacs `develop` branch at the moment.

Change the `dotspacemacs-mode-line-theme` variable:
from:
`   dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 1.5)`
to:
`   dotspacemacs-mode-line-theme '(doom)`

**Comment by sr105-tm** [comment]
Thanks for the hints. `doom-modeline` doesn't have the issue. Also, I went to file a bug on `spaceline` and discovered that I created one 2 years ago already and forgot.

https://github.com/TheBB/spaceline/issues/189
