### ISSUE TITLE
helm-swoop does not work as expected anymore

### ISSUE THREAD

**Issue by brunosmmm** [syl20bnr/spacemacs#13196]
#### Description :octocat:
helm-swoop does not work as expected

#### Reproduction guide :beetle:
- Start Emacs (freshly cloned spacemacs repo, no modifications to .spacemacs)
- Open any file or even use the home buffer
- SPC s s to open helm-swoop, write any search string

*Observed behaviour:* :eyes: :broken_heart:
helm-swoop buffer displays entire buffer that is being searched with occurences highlighted, not just lines with occurrences, making it impossible to jump between occurrences

*Expected behaviour:* :heart: :smile:
helm-swoop buffer displays only lines with occurrences of the search string, able to jump between buffer locations by navigating up/down helm-swoop buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 278be4101)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
Confirmed.

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d7e9a803f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion colors command-log emacs-lisp git haskell helm imenu-list latex markdown multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/notes.org"))
            python
            (shell :variables shell-default-shell 'eshell)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by duianto** [comment]
It seems to be caused by `helm-core-20200119.739`
when I reverted to the previous version I have: `helm-core-20200116.512`

Then helm-swoop `SPC s s` starts working as expected. On the Spacemacs home buffer when searching for `pack`, then only the five lines containing `pack` are shown.

**Comment by duianto** [comment]
Correction it might not have been caused by: `helm-core-20200119.739`
That was just the latest one where I'm seeing the issue.

There is a newer version available when I just checked: `helm-core-20200120.1141`
But unfortunately the issue remains.

**Comment by brunosmmm** [comment]
This is an upstream issue, I've tried with a completely vanilla emacs, helm-core / helm-swoop installed from melpa with the same results.

As a sidenote, it isn't immediately clear to me how can I temporarily revert to that version with spacemacs, can you please elaborate?

**Comment by duianto** [comment]
When updating packages, the outdated packages from the five previous times are stored in:
`c:/Users/username/.emacs.d/.cache/.rollback/26.3/develop/`

The current version is stored in:
`c:/Users/username/.emacs.d/elpa/26.3/develop/`

Move the current version some where else and copy the previous version from a rollback dir and paste it where the current version was.

Unfortunately it won't work if one just has cloned a fresh copy of Spacemacs, because it downloads the latest versions from melpa.

**Comment by duianto** [comment]
Thanks for testing it without Spacemacs.

**Comment by duianto** [comment]
I found some notes about a possible way to load a package at a specific commit.
```
;; Load a specific commit of a github repository
   dotspacemacs-additional-packages '(
                                      (hl-todo :location (recipe :fetcher github :repo "tarsius/hl-todo" :commit "60797aa364e2ea6f4efead7f408eed9358dce5b5")))
```
source: https://github.com/syl20bnr/spacemacs/issues/12143#issuecomment-481456757

An article with a similar suggestion:
http://jr0cket.co.uk/2017/03/spacemacs-managing-broken-emacs-packages.html

**Comment by duianto** [comment]
This seems to be the helm-swoop repository:
https://github.com/emacsorphanage/helm-swoop

Feel free to report it, I'm sure they also would like to get it fixed.

**Comment by brunosmmm** [comment]
I've already tracked down the commit from helm that seems to break helm-swoop, I'll be reporting shortly. Should this issue be closed?

**Comment by twillis** [comment]
was able to rollback to a working config. In case it helps anyone in the meantime. 

```
  drwxr-xr-x   2 tom tom 12288 Jan  8 07:04 helm-20200107.1518
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-ag-20170209.1545
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-company-20190812.1429
  drwxr-xr-x   2 tom tom  4096 Jan  8 07:03 helm-core-20200108.724
  drwxrwxr-x   2 tom tom  4096 Jan  2 07:54 helm-css-scss-20191230.1549
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-c-yasnippet-20170128.1542
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-descbinds-20190501.935
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-flx-20180103.516
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-git-grep-20170614.1411
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-gitignore-20170211.8
  drwxrwxr-x   2 tom tom  4096 Nov 27 15:08 helm-ls-git-20191127.510
  drwxrwxr-x   2 tom tom  4096 Jan  4 09:34 helm-lsp-20200103.1659
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-make-20190729.1221
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-mode-manager-20151124.938
  drwxrwxr-x   2 tom tom  4096 Dec 30 07:12 helm-org-20191229.635
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-org-rifle-20190809.1831
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-projectile-20190731.1538
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-purpose-20170114.1636
  drwxr-xr-x   2 tom tom  4096 Sep 17 11:01 helm-pydoc-20160918.542
  drwxrwxr-x   2 tom tom  4096 Dec 25 19:16 helm-swoop-20191225.959
  drwxrwxr-x   2 tom tom  4096 Sep 17 08:56 helm-themes-20160918.545
 
```

**Comment by duianto** [comment]
@brunosmmm Leave it open until it's fixed.

**Comment by brunosmmm** [comment]
Reported. Just for reference, this behavior shows up from upstream helm commit c09329cd8bf2363

**Comment by MrMic** [comment]
Confirmed! I was just about to report the same bug.

**Comment by duianto** [comment]
The `helm-swoop` package has merged a temporary workaround fix:
Temporary workaround; not update candidate issue https://github.com/emacsorphanage/helm-swoop/pull/176

I just updated the packages and the `helm-swoop` update was included.

Now when I search for `pack` with `SPC s s` in the Spacemacs home buffer, only the five lines containing the word "pack" are shown.
