### ISSUE TITLE
how to quit vim after git commit in emacs ansi-term shell open one while git commit 

### ISSUE THREAD

**Issue by hackrole** [syl20bnr/spacemacs#13191]
while I press `SPC ' ` in a project , it will open a ansi-term, I would like to do git commit or something else. It will open a vim in current buffer for edit message, but I cannot quit it .

type :q in this buffer while close the ansi buffer, but while I swich to ansi-buffer, it still stay in vim editing. how to fix it .

PS: I know how to use magit for commit, But I just more like use git in shell.

**Comment by feng-qi** [comment]
Did you try to use `C-z`(which bind to command `evil-emacs-state` in my local)? It kind of disables evil. Then keys you type will go directly to the buffer, which should go to vim if you have it running in current buffer. `C-z` again will get you back to evil.

Hope I understand your problem right.

**Comment by martijnjanssen** [comment]
Alternatively, you might want to take a look at the `git` layer (which is `magit`). This layer is built for git functionalities.

**Comment by hackrole** [comment]
> Did you try to use `C-z`(which bind to command `evil-emacs-state` in my local)? It kind of disables evil. Then keys you type will go directly to the buffer, which should go to vim if you have it running in current buffer. `C-z` again will get you back to evil.
> 
> Hope I understand your problem right.

C-z is exactly what I want, thanks very much
