### ISSUE TITLE
lsp-rename times out in python-mode

### ISSUE THREAD

**Issue by dbankmann** [syl20bnr/spacemacs#13202]
Hi, I'm trying to use

`SPC m r r` in python mode `(lsp-rename)`.

I want to rename a class but only get 
```lsp-request: Timeout while waiting  for response. Method: textDocument/rename```. 

the lsp server is running and installed. No complaints on startup.

Any ideas, which variables I could check?

**Comment by yyoncho** [comment]
You may increase lsp-response-timeout and retry. But probably the server has failed and it should be reported upstream.

**Comment by szobov** [comment]
Same here, using mspyls as a backend-server
