### ISSUE TITLE
spacemacs launch error

### ISSUE THREAD

**Issue by csfreebird** [syl20bnr/spacemacs#13210]
> Warning (initialization): An error occurred while loading ‘/home/dean/.emacs.d/init.el’:
> 
> error: Loading file /home/dean/.emacs.d/elpa/26.3/develop/which-key-20200119.2010/which-key.elc failed to provide feature ‘which-key’
> 
> To ensure normal operation, you should investigate and remove the
> cause of the error in your initialization file.  Start Emacs with
> the ‘--debug-init’ option to view a complete error backtrace.

I am using develop  branch(latest code), after clicking 'update package' in *spacemacs* buffer, run into the above error.

**Comment by Alexander-Miller** [comment]
Remove which-key, manually if you have to. Sounds like a corrputed install.

**Comment by csfreebird** [comment]
I reinstalled spacemacs, it works now. But have one question, should I upgrade package in *spacemacs* buffer when using develop branch?

**Comment by Alexander-Miller** [comment]
:man_shrugging: It really shouldn't make any difference.

Since your issue is resolved you should close this ticket.

**Comment by tshu-w** [comment]
> I reinstalled spacemacs, it works now. But have one question, should I upgrade package in _spacemacs_ buffer when using develop branch?

Yes, you can upgrade packages, if you meet some issue, you can use `configuration-layer/rollback` to rollback.
