### ISSUE TITLE
Layers are loaded in alphabetical order insted as defined in dotspacemacs-configuration-layers.

### ISSUE THREAD

**Issue by newloran2** [syl20bnr/spacemacs#1321]
If one layer remap some keybinds already defined by other layer (a personal configuration layer) these layer should be loaded in the order that was defined.

For example:
I have a personal layer named Erik, this layer remap option and command behaviour from osx layer.
I would like my layer was loaded before osx layer, but because the alphabetical order my layer is always loaded after the osx.

**Comment by alex-glv** [comment]
Use eval-after-load, like here https://github.com/syl20bnr/spacemacs/blob/064a598bff56f7cef1ac2ddf1c43684357dde56a/contrib/ansible/packages.el#L24

**Comment by newloran2** [comment]
Alex-glv thanks for the quick response.
I did some tests following your suggestion and here are some considerations.

The eval-after-load does not work for the case that I reported because the packages.el is loaded before keybinds.el.

For example:
I added this snippet in my keybindgs.el.

(eval-after-load 'pbcopy
   (when (equal system-type 'darwin)
     (message "Run erik")
     (mac-option-modifier setq 'super)
     (setq mac-command-modifier 'goal)
     )
   )

When my keyboard.el file is loaded the eval-after-load will be triggered becouse the pbcopy module was already loaded on the layer osx.
But due to loading in alphabetical order the keybindigs.el of osx layer will be called after my layer (erik) and override the settings that i made.

For now i simply added these settings on my .spaceemacs, but I think putting that sort of thing in a configuration layer is much more organized.

**Comment by syl20bnr** [comment]
This is a spacemacs feature. Packages are loaded in alphabetical order to avoid an infinity of bugs that would occur if the users could shuffle the order. Since the order is easily predictable and always the same we can reliably identify the case where `eval-after-load` is required.

If A requires B then use:
```elisp
(eval-after-load 'B '(progn ....))
```
