### ISSUE TITLE
ht package needs some update

### ISSUE THREAD

**Issue by dorneanu** [syl20bnr/spacemacs#13222]
#### Description :octocat:
The `ht` package has to be updated. It causes some problems with `pocket-reader`
(also see https://github.com/alphapapa/pocket-reader.el/issues/13#issuecomment-579201257).

In my spacemacs instance I have to load the newer version using:

```
load-library ht
```

#### Reproduction guide :beetle:
- Start Emacs
- install `pocket-reader`
- start `pocket-reader`

*Observed behaviour:* :eyes: :broken_heart:
Whenever I start `pocket-reader` I see an error:

```
helm-M-x: Wrong number of arguments: (lambda (alist) "Create a hash table with initial values according to ALIST." (let ((h (ht-create))) (let ((--dolist-tail-- (reverse alist)) pair) (while --dolist-tail-- (setq pair (car --dolist-tail--)) (let ((key (car pair)) (value (cdr pair))) (ht-set! h key value)) (setq --dolist-tail-- (cdr --dolist-tail--))) (setq pair nil) h))), 2
```

*Expected behaviour:* :heart: :smile:
When all installed correctly `pocket-reader` should just show the list of entries in the getpocket account.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml helm auto-completion emacs-lisp git go
      (go :variables go-tab-width 4)
      (go :variables go-format-before-save t)
      (go :variables godoc-at-point-function 'godoc-gogetdoc)
      (go :variables gofmt-command "goimports")
      markdown org neotree tmux gtags)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```

**Comment by emacs18** [comment]
Spacemacs has ht version 2.0 embedded within it.
This was released in 2014, i.e., 6 years ago.
Perhaps an update is long overdue.

**Comment by alphapapa** [comment]
This seems especially curious since `pocket-reader.el` declares that `ht` 2.2 is required, which should cause the newer version to be loaded from MELPA.

**Comment by emacs18** [comment]
Newer ht package is installed.  However the issue may be that it is not used since ht.el is a core spacemacs library so that (require 'ht) I don't think will load the newer version.

**Comment by emacs18** [comment]
This problem was seen with other packages as I recall.  The only solution I think is to update ht.el within spacemacs to a newer version.

**Comment by smile13241324** [comment]
You are right ht is pretty outdated, let me check if there is some specific reason not to update

**Comment by smile13241324** [comment]
@dorneanu I have upgraded the version of ht included with spacemacs core, would you mind trying if this solves your original issue. If it does please let me know and close the issue.
