### ISSUE TITLE
Symbol’s value as variable is void: treemacs-scope-types

### ISSUE THREAD

**Issue by Zlopez** [syl20bnr/spacemacs#13226]
#### Description :octocat:
When trying to open treemacs window (SPC p t), I'm getting `Symbol’s value as variable is void: treemacs-scope-types` instead of the treemacs window.

#### Reproduction guide :beetle:
- Start Emacs
- Open any project file
- SPC p t

*Observed behaviour:* :eyes: :broken_heart:
Symbol’s value as variable is void: treemacs-scope-types

*Expected behaviour:* :heart: :smile:
treemacs window is opened

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 75cfd40d3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(systemd html javascript rust yaml python
         (auto-completion :variables auto-completion-enable-snippets-in-popup t)
         emacs-lisp git markdown multiple-cursors org lsp helm spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2

**Comment by nixmaniack** [comment]
This looks like stale treemacs* packages issue which recently added `Perspective` scoping feature. 
Update packages(`SPC f e U`) and try again.

**Comment by Zlopez** [comment]
I had some issue when updating using `SPC f e U`, but after restart the treemacs is working again. Thanks

**Comment by nixmaniack** [comment]
👍 A typical workflow for updating packages involves `SPC f e U` followed by `SPC q R`(`restart-emacs`) until then new packages aren't downloaded/configured. 

If your issue is solved, you may close it.
