### ISSUE TITLE
layer geolocation broken spacemacs layouts

### ISSUE THREAD

**Issue by tshu-w** [syl20bnr/spacemacs#13221]
#### Description :octocat:
Wrong type argument: commandp, spacemacs/layouts-transient-state/body

#### Reproduction guide :beetle:
- Start Emacs
- SPC-l

*Observed behaviour:* :eyes: :broken_heart:
Wrong type argument: commandp, spacemacs/layouts-transient-state/body

*Expected behaviour:* :heart: :smile:
SPC-l work correctly

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 96e7621f8)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(default config lang misc my-org
  (geolocation :variables geolocation-enable-automatic-theme-changer t geolocation-enable-location-service t geolocation-enable-weather-forecast nil))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument commandp spacemacs/layouts-transient-state/body)
  call-interactively(spacemacs/layouts-transient-state/body nil nil)
  command-execute(spacemacs/layouts-transient-state/body)
```

**Comment by duianto** [comment]
This is what I saw when testing this issue.

`SPC l` (l = lowercase L) is `undefined` by default in the `spacemacs-base` layer.

It works again after adding the `spacemacs-layouts` layer.

It still works after adding the `geolocation` layer without any variables.

But when I added the same variables as in your config:
`(geolocation :variables geolocation-enable-automatic-theme-changer t geolocation-enable-location-service t geolocation-enable-weather-forecast nil)`

On restart the `theme-changer` package started to install, but the white progress bar on the mode line stopped at about 3/4.

The cursor can be moved, but the Spacemacs home buffer still shows:
>Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: theme-changer@geolocation... [1/1]

In this state when `SPC l` is pressed then it shows the same error message:
>command-execute: Wrong type argument: commandp, spacemacs/layouts-transient-state/body

When restarting again, then a white progress bar on the mode line stops below half.

I now noticed that there's an error message:
>user-error: calendar-longitude is not set

After adding the suggested configuration:
```elisp
      (setq calendar-location-name "Barcelona, Spain"
            calendar-latitude 41.23
            calendar-longitude 1.80)
```
from the geolocation layer:
https://github.com/syl20bnr/spacemacs/tree/develop/layers/+tools/geolocation#location

And restarting. Now the mode line progress bar didn't stop mid way, and `SPC l` opens the Layouts Transient State without any errors.

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a549b9f3b)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((geolocation :variables geolocation-enable-automatic-theme-changer t geolocation-enable-location-service t geolocation-enable-weather-forecast nil)
 spacemacs-layouts autohotkey auto-completion colors command-log emacs-lisp git github haskell ivy imenu-list markdown multiple-cursors org
 (shell :variables shell-default-shell 'eshell)
 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by tshu-w** [comment]
Thank you for your very detailed reply, I make some mistake when I report this issue.
after I set `calendar-location-name`, `calendar-latitude` and `calendar-longitude`, I still get `let*: Wrong type argument: number-or-marker-p, nil`. Seems like `(change-theme 'solarized-light 'solarized-dark)` doesn't work on my side, I will report [upstream](https://github.com/hadronzoo/theme-changer) later.

**Comment by tshu-w** [comment]
It seems like even set `geolocation-enable-location-service t` when spacemacs startup `calendar-longitude` is not set.
