### ISSUE TITLE
question: remove nils from dotspacemacs-configuration-layers

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#13237]
Can someone please point to the place in Spacemacs code where `dotspacemacs-configuration-layers` need to be trimmed to exclude `nil`s, so doing something like this in your config wouldn't throw warnings:

    (defun dotspacemacs/layers ()

      dotspacemacs-configuration-layers
      `(
        ,(when (eq system-type 'darwin) 'osx)
        ,(when (eq system-type 'gnu/linux) 'exwm))

**Comment by duianto** [comment]
The error message is defined here:
https://github.com/syl20bnr/spacemacs/blob/f4f95d28fbeb4653f97d795cae6985a558a26ec4/core/core-configuration-layer.el#L1509

**Comment by agzam** [comment]
https://github.com/syl20bnr/spacemacs/pull/13242

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
fix: ignore nil values in dotspacemacs-configuration-layers #13242
