### ISSUE TITLE
Officially switching to a rolling release?

### ISSUE THREAD

**Issue by allentiak** [syl20bnr/spacemacs#13248]
Hi, all,

I have been using Spacemacs for almost three years now.

Given the lack of stable releases after 0.200.13, I switched to `develop` over a year and a half ago now, with no major glitches. I am sure I am not the only one.

I think the current release model simply does not work. The last "stable" release (0.200.13) is over two years old. And "develop" does not seem to be "stable" enough to be promoted to the 0.300 release any time soon...

Why not simply officially accept this reality, acknowledge there will never be a new "stable" release, and simply switch the release model to "rolling"?

There are many successful free software projects with this model, such as Arch Linux.
I think the main benefits of this model (quickly delivering both features and feedback) are more than needed here.

What does the rest of the community think about this?

Best,
Leandro

**Comment by dijonkitchen** [comment]
This may be a duplicate of https://github.com/syl20bnr/spacemacs/issues/11352

**Comment by allentiak** [comment]
Your're right, it is.
Maybe changing #11352 's title may help other people don't open the same
issue again? :-)

**Comment by lebensterben** [comment]
Please leave comment in https://github.com/syl20bnr/spacemacs/issues/14198
I strongly think we need to address this issue. Sooner the better.
