### ISSUE TITLE
Find-file-at-point fails, but only once after restart

### ISSUE THREAD

**Issue by rogerbosman** [syl20bnr/spacemacs#13245]
#### Description :octocat:
Every time I invoke `find-file-at-point` for the fist time in Spacemacs, it
fails with the message included below. It only fails for the *first time*, after
this it works until I restart Spacemacs.

I know this is probably not enough information, but I have no idea how to supply
a stack trace or something? I'd be happy to include further information, if
given instructions about how to actually get it.

#### Reproduction guide :beetle:
- Start Emacs
- Place cursor over a file description (For example an \include{...} statement
in Latex)
- Call `find-file-at-point` either trough `SPC SPC find-file-at-point` or `g f`
- Observe error
- Invoke `find-file-at-point` again, now it works fine.

*Observed behaviour:* :eyes: :broken_heart:
Helm opens to select from all found files

*Expected behaviour:* :heart: :smile:
Error is given. Copied from `*Messages*` buffer:

```
helm-M-x-execute-command: In ‘find-file-at-point’ source: ‘#[0 \307\300\301\305\306\304\203\303\204
\202\310%\311\302"\207 [#[771 \306\300\301G\303%\307!\310=\205\311\303\312"\206\313\314A\203%\314\241\210\205*\315\316!\262\317\302\205?\320>\205?\302C\321\203R	G\322V\203R!\202S\304\305#"\207 [ffap-read-file-or-url-internal nil ~/FILE_LOCATION_OMMITTED.tex (metadata (category . file) (completion--unquote-requote . t)) nil t completion-all-completions last emacs completion-metadata-get display-sort-function #[257 \300\301"\207 [sort helm-generic-sort-fn] 4 

(fn CANDIDATES)] nil t copy-sequence append (helm helm-fuzzy) helm-completion-in-region--initial-filter 0 helm-completion-style helm-completion--sorting-done] 13 

(fn STR PREDICATE ACTION)] nil ~/FILE_LOCATION_OMMITTED.tex nil t nil t helm-comp-read-get-candidates  helm-cr-default helm-pattern] 6]’ 
 (wrong-number-of-arguments (3 . 3) 2)
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7b28e62fb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript html markdown auto-completion bibtex emacs-lisp git
            (haskell :variables haskell-completion-backend 'ghci haskell-interactive-mode 'stack-ghci)
            helm latex multiple-cursors
            (org :variables org-want-todo-bindings t)
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            shell-scripts syntax-checking treemacs yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
I don't know how to do this
```

**Comment by duianto** [comment]
I'm unable to reproduce the issue.

With the `bibtex` and `latex` layers installed.

Right after starting Spacemacs:
- on the Spacemacs home buffer
- from the recently files list, the following file was opened: `UseLATEX.tex`
- it has these lines that are referring to a file: `UseLATEX.cmake`
```
18 \hypersetup{pdftitle={UseLATEX.cmake: LaTeX Document Building Made Easy}}
32 \newcommand*{\UseLATEX}{\textfile{UseLATEX.cmake}\xspace}
61   \title{UseLATEX.cmake: \latex Document Building Made Easy}
117 include(UseLATEX.cmake)
849 CMake Error at UseLATEX.cmake:377 (MESSAGE):
1068 include(UseLATEX.cmake)
1325   %% \section{UseLATEX.cmake Listing}
1326   %% \label{sec:UseLATEX.cmakeListing}
1328   %% \includeCodeListing[fontsize=\footnotesize]{UseLATEX.cmake}
```

With the cursor on any occurrence of: `UseLATEX.cmake`
pressing: `gf`
opens a `HELM Find File At Point buffer`


<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c1a518439)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion bibtex command-log emacs-lisp git github helm latex markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
</pre>
</details>


<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c1a518439)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion bibtex command-log emacs-lisp git github helm imenu-list latex markdown multiple-cursors org
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by rogerbosman** [comment]
After moving to a fresh install the error does not show up anymore, not sure what was happening but I think this can be closed
