### ISSUE TITLE
Add ctags layer

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1324]
Since we have `gtags` layer, it would be desirable to have a `ctags` layer since many people just use `ctags`. Todos:

- We should recommend people to use [fishman-ctags](https://github.com/fishman/ctags), but optional since Emacs has its own `etags` 

- Create a command that builds tags or using [find-and-ctags](https://github.com/redguardtoo/find-and-ctags). 

- `helm-etags-select` is a better command than stock `find-tag`. Should replace `find-tag` currently bound to `M-.` with it.

**Comment by syl20bnr** [comment]
:+1: 

Would be cool to have helm-gtags equivalent for it.

**Comment by kevincolyar** [comment]
:+1:

**Comment by ianbattersby** [comment]
+1 for this, I have git hooks generating ctags files so a layer to work with this would be cool.

**Comment by sudostack** [comment]
:+1:

**Comment by TheBB** [comment]
Closing this in favour of the discussion in #3273.
