### ISSUE TITLE
Theme Change Consistency

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#1325]
Something I encountered is when I switch themes while for instance in org mode some colors do not update:

![screen shot 2015-04-22 at 8 49 35 am](https://cloud.githubusercontent.com/assets/2065876/7276411/0f4fb0a2-e8cf-11e4-9859-5957d367d9f8.png)

![screen shot 2015-04-22 at 8 50 36 am](https://cloud.githubusercontent.com/assets/2065876/7276412/0f569cc8-e8cf-11e4-8b83-3ec567f28aae.png)

So far the fastest way for me to resolve this is in the case of org is to reload org-mode, or sometimes I just close and reopen the file. It would be great if there was a way for this to be handled automatically or if anything an easy keybind.

**Comment by trishume** [comment]
I'm also pretty sure the fringe colours don't change. That or every single theme I have tried has the same fringe colours. Also some themes don't change the colour of string quotes (leaving them black) when dynamically switching.

**Comment by syl20bnr** [comment]
As mentioned in the [documentation](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#color-themes) it is intrinsec to Emacs way to apply themes. There is no such things as current themes in Emacs, themes are applied on top of each other which allow to mix them. There is an unload-theme function in Emacs and Spacemacs uses it but it has some inconsistencies like this one.

The only theme which is guaranteed to be consistent is the first one at startup.

**Comment by mattly** [comment]
I've noticed the same issue, and I think it has to do with org-mode dynamically creating faces for the hidden header stars, and how it doesn't hook into theme changes to re-create those.
