### ISSUE TITLE
auto-complete-rst: (void-variable File)

### ISSUE THREAD

**Issue by fleimgruber** [syl20bnr/spacemacs#13251]
#### Description :octocat:
Warning from `auto-complete-rst` after opening `*.rst` file.

#### Reproduction guide :beetle:
- Start Emacs
- Load `restructuredtext` layer
- Visit any `*.rst`

*Observed behaviour:* :eyes: :broken_heart:
The `*Warnings*` buffer pops open in other window showing:

```
Warning (emacs): [auto-complete-rst] Failed to eval the source generated by genesource.py. Got: (void-variable File)
```

*Expected behaviour:* :heart: :smile:
The layer `restructuredtext` works without warnings.

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.60
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7f92a4388)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lua pbz latex csv
     (treemacs :variables treemacs-use-follow-mode t)
     multiple-cursors semantic-web jabber dash javascript helm bibtex ranger
     (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/")
     csharp sphinx restructuredtext
     (lsp :variables lsp-prefer-flymake nil)
     dap emacs-lisp
     (git :variables git-enable-magit-svn-plugin t)
     octave sql html web-beautify
     (markdown :variables markdown-command "pandoc")
     (windows-scripts :toggle
                      (eq system-type 'windows-nt))
     (shell-scripts :toggle
                    (or
                     (eq system-type 'darwin)
                     (eq system-type 'gnu)))
     shell
     (org :variables org-enable-reveal-js-support t org-enable-trello-support t)
     syntax-checking
     (version-control :variables version-control-diff-tool 'git-gutter version-control-diff-side 'left)
     (osx)
     graphviz nixos systemd
     (c-c++ :variables c-c++-enable-clang-support t c-c++-backend 'lsp-ccls)
     (go :variables go-tab-width 4 go-backend 'lsp)
     lua ess rust
     (clojure :variables clojure-enable-linters 'clj-kondo)
     erlang
     (python :variables python-test-runner 'pytest python-backend 'lsp python-fill-column 88)
     (julia :variables julia-mode-enable-lsp t julia-mode-enable-ess nil)
     haskell java)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
No backtrace.

**Comment by smile13241324** [comment]
I have double checked the documentation for the auto-complete-rst package as well as the layer documentation and the problem seems to be that auto-complete-rst has seen his last contribution around 2014. As a result of this it lost compatibility with a version of sphinx higher than 1.4.9. For reference I have currenctly version 2.3.0 on my linux box.

I think we need to remove `auto-completion-rst` from this layer to supress the warning. Does the package work for you independent of the warning @fleimgruber.

**Comment by fleimgruber** [comment]
Thanks for digging into this - yes, there are related issues and a PR from 2015 in there.

> Does the package work for you independent of the warning

I tried with a handful of the directives (see [here](https://docutils.sourceforge.io/docs/ref/rst/directives.html)), but none get proper completion.

**Comment by smile13241324** [comment]
@fleimgruber hmm do you have a proper alternative for rst support you would like to see in Spacemacs? Right now I seem not to find any.

In the meantime I will disable `auto-completion-rst` to avoid this warning.

**Comment by smile13241324** [comment]
@fleimgruber I have disabled the faulty packages on develop. Can you double check if this solves your issue and if it does close this one?

**Comment by fleimgruber** [comment]
@smile13241324 Just pulled latest develop, seems to work. Thanks!

I use .rst files mostly with [Sphinx](https://www.sphinx-doc.org/en/master/) so I will try out  https://github.com/Fuco1/sphinx-mode for that at some point. It is not actively developed from what I can see and does not explicitly support completion. I will have a look at [elpy](https://github.com/jorgenschaefer/elpy) and similar packages, maybe someone there supports .rst.
