### ISSUE TITLE
JetBrains Mono is missing font anti-aliasing

### ISSUE THREAD

**Issue by YaLTeR** [syl20bnr/spacemacs#13250]
#### Description :octocat:
JetBrains Mono is missing font anti-aliasing.

#### Reproduction guide :beetle:
- Start Emacs
- SPC-f-e-d and change the font to JetBrains Mono.
- SPC-f-s, SPC-q-r and observe.

*Observed behaviour:* :eyes: :broken_heart:
The text is not anti-aliased.

![image](https://user-images.githubusercontent.com/1794388/74027812-fa93f780-49b9-11ea-80a1-b8a45e4776a0.png)

*Expected behaviour:* :heart: :smile:
The text is anti-aliased.

#### System Info :computer:
- OS: Arch Linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7f92a4388)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm lsp markdown multiple-cursors org spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
It looks aliased for me in both PopOS 19.10 and Windows 1903.

![VirtualBoxVM_2020-02-10_12-34-52](https://user-images.githubusercontent.com/13420573/74146703-fce89280-4c01-11ea-87e1-75dc986d7d73.png)

![emacs_2020-02-10_12-22-42](https://user-images.githubusercontent.com/13420573/74145944-4c2dc380-4c00-11ea-9a9b-0f2bb31f38d6.png)

**Comment by YaLTeR** [comment]
I'm now running Fedora and it works fine here. I've no idea what was causing it on Arch.
