### ISSUE TITLE
Org Mode consistency graph not rendering on Agenda View

### ISSUE THREAD

**Issue by ssbothwell** [syl20bnr/spacemacs#13252]
#### Description :octocat:
Org Mode consistency graph not rendering on Agenda View

#### Reproduction guide :beetle:
1 Erase .spacemacs file to start with a fresh config.
2 Add `org` layer to new .spacemacs file.
3 Reload config.
4 Open an org file with habits in it. Add this file to the agenda list.

*Observed behaviour:* :eyes: :broken_heart:
5. Open Org Agenda Week View.
6. Witness that the consistency graph is being rendered correctly for habits.
7. Restart emacs.
8. Open Org Agenda Week View.
9. Consistency graphs are no longer being rendered. :(

*Expected behaviour:* :heart: :smile:
I would expect the consistency graphs to be rendered.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f94fea920)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors org treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
@ssbothwell I have merged the fix from @klochowicz. Please check whether this solves your issue and close the ticket accordingly.

**Comment by ssbothwell** [comment]
I just pulled the latest from develop and restarted emacs. I am not seeing any diffference.

**Comment by klochowicz** [comment]
I'm sorry to hear that. I don't recall doing anything more than this fix my issue which sounded similar to yours (but I'm on emacs 28.0.50, maybe that made the difference). Would you mind checking if org-habit module is enabled in your config (print result of the `org-modules` variable)?

**Comment by ssbothwell** [comment]
`space h d v` `org-modules`:
```
org-modules is a variable defined in ‘org.el’.
Its value is
(org-habit ol-w3m ol-bbdb ol-bibtex ol-docview ol-gnus ol-info ol-irc ol-mhe ol-rmail ol-eww)
Original value was 
(ol-w3m ol-bbdb ol-bibtex ol-docview ol-gnus ol-info ol-irc ol-mhe ol-rmail ol-eww)
```

When writing my original bug report I wiped `.emacs.d/` and did a fresh install of spacemacs with a stock config. I'll try doing that again to verify my system isn't in some weird state.

**Comment by juanwolf** [comment]
Any news on this? I am getting the same problem and no habit graph is displayed. If that can help, the org-modules variable contains org-habit. However, the org-habit mode is missing on a org-agenda buffer (and impossible to run any org-habit-* function).

**Comment by smile13241324** [comment]
Unfortunately not @juanwolf, I did not have a look into this apart from merging the PR which seems to have not fixed the issue.
I have marked the ticket as help wanted maybe someone else has time to look into this. If not I may come back to this in time.

**Comment by juanwolf** [comment]
Hi @smile13241324, 

I dug a bit today and found out that I misconfigured some recurring tasks which was making the whole org-habit layer not load on an agenda view. So it works perfectly fine on the develop branch and I think you can close that issue. 

I need to find a way to get a better feedback on error messages (alarm on change on the Messages buffer maybe?) but that's another problem.
Thanks again!

**Comment by smile13241324** [comment]
:+1:

**Comment by wminshew** [comment]
@juanwolf may I ask how you were misconfiguring the recurring tasks?

mine was working until I recently re-installed emacs-plus (updating brew packages broke the link to imagemagick), not sure why `org-habit` isn't working anymore

**Comment by wminshew** [comment]
following up here -- interestingly enough, eval'ing `(require 'org-habit)` solved it for me..
