### ISSUE TITLE
[React] RJSX mode still using LSP linter even though `javascript-lsp-linter` is disabled

### ISSUE THREAD

**Issue by br0p0p** [syl20bnr/spacemacs#13261]
#### Description :octocat:
The combination of the `react` layer with LSP via the `javascript` layer doesn't work with `flycheck`.

#### Reproduction guide :beetle:
- Start Emacs
- Set the following in `dotspacemacs-configuration-layers`:
    ```
    react
    (javascript :variables
                    javascript-backend 'lsp
                    javascript-lsp-linter nil
                    node-add-modules-path t)
    ```

*Observed behaviour:* :eyes: :broken_heart:
RJSX mode still uses the LSP linter and doesn't use Flycheck. I tried both `(spacemacs/enable-flycheck 'rjsx-mode)` and `(add-hook 'rjsx-mode-hook 'flycheck-mode)` and neither corrected the problem.

*Expected behaviour:* :heart: :smile:
RJSX mode should use the Flycheck linter (ESlint) instead of the LSP linter.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c9c5637ac)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git helm lsp markdown multiple-cursors org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking treemacs version-control csv
                 (go :variables go-tab-width 4 go-backend 'lsp go-format-before-save t go-use-golangci-lint t godoc-at-point-function 'godoc-gogetdoc)
                 gtags html
                 (javascript :variables javascript-fmt-on-save t javascript-fmt-tool 'prettier javascript-import-tool 'import-js javascript-backend 'lsp javascript-lsp-linter nil js-indent-level 4 js2-basic-offset 4 js2-include-node-externs t node-add-modules-path t)
                 (json :variables json-fmt-tool 'prettier json-fmt-on-save t)
                 lsp
                 (php :variables php-backend 'lsp)
                 sql yaml react
                 (typescript :variables typescript-backend 'tide typescript-fmt-on-save t))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by br0p0p** [comment]
After some more testing it seems like setting `javascript-lsp-linter` to `nil` does not at all as intended. JS2 mode still uses the LSP linter with my current config.

**Comment by duianto** [comment]
@yyoncho Do you know what the issue could be here?

**Comment by yyoncho** [comment]
What is the value of lsp-diagnostic-package in the buffer?

**Comment by duianto** [comment]
If I'm replicating the issue correctly, then the variables value is:
>lsp-diagnostic-package is a variable defined in ‘lsp-mode.el’.
Its value is ‘:auto’

`SPC e v` which calls `flycheck-verify-setup`, shows:
```
Syntax checkers for buffer react-example.js in js2-mode:

First checker to run:

  lsp (explicitly selected)
    - may enable: yes
    - predicate:  t

Checkers that could run if selected:

  javascript-jshint  select
    - may enable:         yes
    - executable:         Found at c:/Users/username/AppData/Roaming/npm/jshint.cmd
    - configuration file: Not found

  javascript-standard  select
    - may enable: yes
    - executable: Found at c:/Users/username/AppData/Roaming/npm/standard.cmd

Checkers that are compatible with this mode, but will not run until properly configured:

  javascript-eslint (disabled)
    - may enable:  Automatically disabled!
    - executable:  Found at c:/Users/username/AppData/Roaming/npm/eslint_d.cmd
    - config file: missing or incorrect

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20191126.2142)
Emacs version:    26.3
System:           x86_64-w64-mingw32
Window system:    w32
```

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0a06c7ca6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git github helm imenu-list
            (javascript :variables javascript-backend 'lsp javascript-lsp-linter nil node-add-modules-path t)
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org react
            (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by yyoncho** [comment]
`:auto` means pick flycheck if available, otherwise use flymake if available.

`lsp-diagnostic-package` should be :none to disable the lsp checker.

**Comment by yyoncho** [comment]
To elaborate a bit more, lsp-diagnostic-package is a new variable to replace lsp-prefer-flymake.

**Comment by duianto** [comment]
I tried `spacemacs/copy-and-comment-lines` (`gy`) all lines with `lsp-prefer-flymake` and replaced the uncommented duplicate with `lsp-diagnostic-package`.
```
./layers\+frameworks\react\funcs.el:38:          ;; (setq-local lsp-prefer-flymake :none))
./layers\+frameworks\vue\funcs.el:34:        ;; (setq-local lsp-prefer-flymake :none)
./layers\+lang\go\funcs.el:59:          ;; (setq-local lsp-prefer-flymake :none))
./layers\+lang\javascript\funcs.el:54:          ;; (setq-local lsp-prefer-flymake :none))
./layers\+tools\lsp\config.el:18:;; (defvar lsp-prefer-flymake nil
./layers\+lang\scala\funcs.el:55:  ;; (setq-local lsp-prefer-flymake nil)
./layers\+lang\typescript\funcs.el:74:          ;; (setq-local lsp-prefer-flymake :none))
```

Now the variable says:
>lsp-diagnostic-package is a variable defined in ‘lsp-mode.el’.
Its value is ‘:none’
Original value was :auto
Local in buffer react-example.js; global value is nil

But I'm still seeing the error hints in the top right corner.

This is the file I'm testing with:
`react-example.js`
```react
ReactDOM.render( <
    h1 > Hello, world! < /h1>,
    document.getElementById('root')
);
```

**Comment by yyoncho** [comment]
What are the flycheck backends?

**Comment by duianto** [comment]
How do I check that?

**Comment by yyoncho** [comment]
SPC e v ?

**Comment by duianto** [comment]
```
Syntax checkers for buffer react-example.js in js2-mode:

First checker to run:

  javascript-jshint
    - may enable:         yes
    - executable:         Found at c:/Users/username/AppData/Roaming/npm/jshint.cmd
    - configuration file: Not found

Checkers that could run if selected:

  javascript-standard  select
    - may enable: yes
    - executable: Found at c:/Users/username/AppData/Roaming/npm/standard.cmd

Checkers that are compatible with this mode, but will not run until properly configured:

  javascript-eslint (disabled)
    - may enable:  Automatically disabled!
    - executable:  Found at c:/Users/username/AppData/Roaming/npm/eslint_d.cmd
    - config file: missing or incorrect


The following syntax checkers are not registered:

  - lsp

Try adding these syntax checkers to `flycheck-checkers'. Flycheck Mode is
enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20191126.2142)
Emacs version:    26.3
System:           x86_64-w64-mingw32
Window system:    w32
```

**Comment by yyoncho** [comment]
Ok, so this disables the lsp checker and solves the issue?

**Comment by duianto** [comment]
I incorrectly assumed that the top right messages were lsp related, since I've only seen them while testing a lsp issue/pr.

But:
>The following syntax checkers are not registered:
>
>  - lsp

does seem to indicate that it solved the issue, @br0p0p can you confirm?

I'll open a PR to replace the obsolete variable.

**Comment by duianto** [comment]
To test it now, replace this line:

https://github.com/syl20bnr/spacemacs/blob/0a06c7ca6bea2031d6b432144aefeb92fb22fd0e/layers/%2Btools/lsp/config.el#L18
with:
```elisp
(defvar lsp-diagnostic-package nil
```

And both of these lines:
https://github.com/syl20bnr/spacemacs/blob/0a06c7ca6bea2031d6b432144aefeb92fb22fd0e/layers/%2Blang/javascript/funcs.el#L54
https://github.com/syl20bnr/spacemacs/blob/0a06c7ca6bea2031d6b432144aefeb92fb22fd0e/layers/%2Bframeworks/react/funcs.el#L38
with:
```elisp
          (setq-local lsp-diagnostic-package :none))
```

**Comment by yyoncho** [comment]
Just for the record, all the places that set lsp-diagnostic-package to t could be deleted, because the default :auto covers that case.

**Comment by duianto** [comment]
👍 It doesn't seem like it's set to `t` anywhere.

**Comment by br0p0p** [comment]
@duianto Your suggestions above seem to fix it for me.

**Comment by yyoncho** [comment]
>  It doesn't seem like it's set to `t` anywhere.

Sorry, I meant "set to `nil`." In the old code base set to nil means use flycheck. In the new codebase the default is :auto which means use flycheck.

**Comment by duianto** [comment]
Ok. Currently `lsp-prefer-flymake` is redefined in the Spacemacs `lsp` layer, with the default value: `nil`
https://github.com/syl20bnr/spacemacs/blob/f03392573ab07063fa929e305e4dbb17a7f83610/layers/%2Btools/lsp/config.el#L18-L21

Probably because it was set to `t` by default in `lsp-mode`
https://github.com/emacs-lsp/lsp-mode/pull/1384/files#diff-b1e9bc82c3b6bd6e95470e18ee41a19bL533

But with the new name and definition, if we should use `:auto` as the default value, which matches the `lsp-mode` default value.

I'm guessing that it might be best to remove the Spacemacs `lsp` layer definition?

All but one of the layers that use the variable, sets it to: `:none`
The scala layer sets it to: `nil` in the `spacemacs//scala-setup-metals` function:
https://github.com/syl20bnr/spacemacs/blob/f03392573ab07063fa929e305e4dbb17a7f83610/layers/%2Blang/scala/funcs.el#L55

>In the old code base set to nil means use flycheck. In the new codebase the default is :auto which means use flycheck.

Then we can remove the line from the scala layer.

**Comment by yyoncho** [comment]
> I'm guessing that it might be best to remove the Spacemacs lsp layer definition?

Yes.

**Comment by smile13241324** [comment]
@br0p0p I have merged duiantos PR, would you mind giving it another go and close the issue if it works for you?

**Comment by br0p0p** [comment]
@smile13241324 yep, looks good! Thanks so much!

**Comment by duianto** [comment]
@br0p0p Issue authors can close their own issues by clicking the `Close issue` button at the bottom of the page. We can do it but it's probably better to let the authors get into the habit of closing resolved issues.

**Comment by br0p0p** [comment]
@duianto oops, just slipped my mind!
