### ISSUE TITLE
When `evil-search-module` is `evil-search` then `SPC s c` doesn't work

### ISSUE THREAD

**Issue by jonathanj** [syl20bnr/spacemacs#1326]
It would be nice if `SPC s c` worked for `evil-search` mode too, I prefer `evil-search` since it's a lot like Vim's search rather than Emacs' isearch.

For some reason search highlights also look different when `evil-search` is the selected search module, I don't understand why.

**Comment by tuhdo** [comment]
Indeed when setting `evil-search-module` to `evil-search`, it can no longer clear highlighting or activate highlighting. You should report upstream.

**Comment by jonathanj** [comment]
@tuhdo What is the correct upstream module to report this to?

**Comment by tuhdo** [comment]
@jonathanj this is unrelated to this issue but related to the issue with searching with `hgrep` buffer earlier. Actually you can use these key bindings to easily navigate the buffer and it won't conflict with `evil-mode`:

- `C-<down>`: go to next match and open the match.
- `C-<up>`: go to previous match and open the match.
- `M-<down>`: go to next match without opening the match.
- `M-<up>`: go to next match without opening the match.

**Comment by tuhdo** [comment]
@jonathanj the deleting windows issue has just been fixed upstream few minutes ago. Wait a few hours and update Helm again, you won't have that error anymore.

**Comment by tuhdo** [comment]
@jonathanj btw when you want to search for actual key bindings of a major mode, use `SPC ?`. It will display a list of available key bindings in current major mode and you can play easily narrow to some commands or key bindings you care about by simply typing some pattern. You would find out these key bindings earlier if you had used `SPC ?`. And press `C-z` (or `Tab` in next release) to read the documentation of each command. It's really amazing.

**Comment by StreakyCobra** [comment]
This is an old issue that seems to have been solved upstream, closing it then, but feel free to open a new issue in case of troubles :relaxed:

**Comment by jonathanj** [comment]
This still doesn't seem to be working for me (I updated all my packages before testing this). The [upstream bug originally referenced](https://github.com/juanjux/evil-search-highlight-persist/issues/6) is still open and there has been no reply from the author to my question.

There also don't appear to be any commits upstream that would have resolved this. Do you mind explaining why you think the issue has been solved? Did I miss something?

**Comment by StreakyCobra** [comment]
Sorry, I'm doing a cleanup and I may be a little bit to prompt to close 6+ months issues without activity that I can't reproduce. As I failed reproducing it, I thought it was solved. I probably have missed a step.

As you say it's a valid issue, I reopen it :relaxed: Sorry for the annoyance.

**Comment by jonathanj** [comment]
@StreakyCobra I think the trick to reproducing it is in my comment on the upstream issue. You need to restart emacs after flipping that search switch otherwise you're still using the other search mode.

**Comment by StreakyCobra** [comment]
Indeed, putting `(setq evil-search-module 'evil-search)` in `user-config` and restarting allows to reproduce it.

**Comment by StreakyCobra** [comment]
PR pending #5727

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by agzam** [comment]
for me it mostly works, I found when it doesn't. When you do `g d` `evil-goto-definition` it highlights it, and then `SPC s c` does not clear it

**Comment by syl20bnr** [comment]
Thanks agzam, reopening the issue since there are still some bugs.

**Comment by duianto** [comment]
Fixed in develop
Clear both / and C-s search highlights with SPC s c #9449
