### ISSUE TITLE
I cant figure out how to use magit forge

### ISSUE THREAD

**Issue by dduenker** [syl20bnr/spacemacs#13269]
I am using the `develop` branch of spacemacs.

I tried loading by adding it to `dotspacemacs-additional-packages`.
Now i can't figure out how to make it load at startup and i am unable to add my private gitlab instance on startup.

I tried adding the following to `dotspacemacs/user-config`:
```elisp
 (add-to-list 'forge-alist '("192.168.0.20" "192.168.0.20/api/v4" "10.10.120.29" forge-gitlab-repository))
```
But i don't know very much about elisp.

Evaluating this by hand did work, but that is not really a solution.

I would appreciate it, if someone could help me figure this out.

**Comment by jr0cket** [comment]
@dduenker are you certain you need to add forge separately?  I though forge was now included in magit and the Spacemacs `git` layer includes magit.

`@` in the magit status buffer, `SPC g s` has several forge commands available.  I have layers `git` and `github` installed on `develop`, updated this weeks.

You will need to create a token for Ghub.  If you add a database, `@ a` then you are prompted to interactively create one.  Or you can read https://magit.vc/manual/forge/Token-Creation.html#Token-Creation

Hope this helps.

**Comment by duianto** [comment]
`forge` is part of the `github` layer.

On Windows it's disabled by default and needs to be added to the:
`dotspacemacs-additional-packages` variable as: `(forge :toggle t)`

source: https://github.com/syl20bnr/spacemacs/tree/develop/layers/+source-control/github#forge

There's a warning on startup:
>Ignoring :toggle for package forge because layer dotfile does not own it.

syl20bnr said this about the warning:
>(forge :toggle t) to enable forge on windows is an interesting hack and the side effect is expected. What happens is that the git layer remains the owner of the package as this is the layer that declare the init function for it. :toggle then does its job but warn that the doftile is not the owner of the package. The dotfile is the owner of the package if there is no layer that owns it.
>
>I’ll look at removing the message when this use case happens, because the dotfile correctly override the :toggle which is what we expect.

**Comment by dduenker** [comment]
> @dduenker are you certain you need to add forge separately? I though forge was now included in magit and the Spacemacs `git` layer includes magit.
> 
> `@` in the magit status buffer, `SPC g s` has several forge commands available. I have layers `git` and `github` installed on `develop`, updated this weeks.
> 
> You will need to create a token for Ghub. If you add a database, `@ a` then you are prompted to interactively create one. Or you can read https://magit.vc/manual/forge/Token-Creation.html#Token-Creation

Thanks, it is indeed loaded and accessible via `@`, but my problem, adding my private gitlab instance still remains.
Until i manually evaluate 
```elisp
 (add-to-list 'forge-alist '("192.168.0.20" "192.168.0.20/api/v4" "10.10.120.29" forge-gitlab-repository))
```
I get the following error message:
 `Cannot determine forge repository.  git@192.168.0.20:dd/test.git isn’t a forge url`

After adding my instance to `forge-alist`, it works as expected.
So how do i add this automatically?

**Comment by dduenker** [comment]
> ```emacs-lisp
> (with-eval-after-load 'forge
>    (add-to-list 'forge-alist '("192.168.0.20" "192.168.0.20/api/v4" "192.168.0.20" forge-gitlab-repository))
>    )
> ```
This works with the emacs 27 and current spacemacs develop branch. Live is great. :)
(i do not use the github layer and `forge` is added as additional package instead in `dotspacemacs-additional-packages`)
