### ISSUE TITLE
Python jump-to-definition not working

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#13263]
#### Description :octocat:
I cannot jump to any definitions (using `gd`) in Python, I get the message

"No jump handler was able to find this symbol"

I have the correct virtualenv activated using `pyvenv-workon` (though attempting
to enable *ANY* venv hangs emacs for almost a minute, that bug is here: https://github.com/syl20bnr/spacemacs/issues/13264). I have jedi installed,
and auto completion seems to work just fine.

It's unable to find definitions even if they are in the same file.

#### Reproduction guide :beetle:
- Start Emacs
- Activate venv `(pyvenv-workon "something")`
- Open python file
- Go to a symbol, press `gd`. 

*Observed behaviour:* :eyes: :broken_heart:

"No jump handler was able to find this symbol"

*Expected behaviour:* :heart: :smile:

It should jump to the definition.

#### System Info :computer:
- OS: darwin
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c9c5637ac)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go swift csv lua nginx sql auto-completion emacs-lisp git yaml javascript html markdown major-modes python org osx python ipython-notebook django syntax-checking spell-checking colors spacemacs-layouts vimscript helm
    (version-control :variables version-control-diff-tool 'diff-hl)
    (c-c++ :variables c-c++-enable-clang-support t)
    (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER LCMS2 GMP

**Comment by smile13241324** [comment]
I am working a lot with python and auto completion and finding definitions normally is no problem. Can you elaborate some more about the setup of yours i.e. can you make a sample file like below and tell me whether finding definitions and auto completion works for you when you just open that file as a standalone python script.
```python
""" Very simple test file """


def say(text: str) -> None:
    """ This prints what you tell it """
    print(text)


def add_eggs(text: str) -> str:
    """ This adds some eggs """
    return " ".join([text, "eggs"])


say(add_eggs("I love my spam with"))
```
This worked for me with the old `anaconda-mode` as well as with the much newer `pyls` lsp server.
