### ISSUE TITLE
What does the osx layer do on non-Apple operating systems?

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#13267]
I have a single `.spacemacs` cfg that I do share across Linux, windows, and OSX machines (amongst others). I need to maintain a fork of this config for OSX to be able to add the osx layer.

Would it be possible to guarantee that the osx layer only has any effects if the OS is actually MacOSX?

**Comment by tshu-w** [comment]
see [this](https://twitter.com/iLemming/status/1228225566920167424)

**Comment by duianto** [comment]
Here's the snippet as copyable text:
```elisp
dotspacemacs-configuration-layers
`(
  ,(when (eq system-type 'darwin) 'osx)
  ,(when (eq system-type 'gnu/linux) 'exwm))
```
source: fix: ignore nil values in dotspacemacs-configuration-layers #13242
