### ISSUE TITLE
Show hidden files doesn't work on Windows 10

### ISSUE THREAD

**Issue by Rareform** [syl20bnr/spacemacs#13276]
I would like to see hidden files using deer or ranger on Windows. Unfortunately the shortcut `z h`
doesn't change anything for deer and for ranger it shows hidden files only in the parent directory. Putting ` (setq ranger-show-hidden t)` also doesn't solve this issue. Of course the files are shown in the list of `helm-find-files`. How could I see hidden files with deer and ranger on a windows machine?

**Comment by duianto** [comment]
This seems to be an upstream issue in:
https://github.com/ralesi/ranger.el

and it's not limited to Windows.

The same thing is observed in Linux (PopOS 19.10) and Windows 1903, with or without Spacemacs.

When the `ranger-show-hidden` variable hasn't been set in the user config.

Then `zh` toggles between these three values:
>Show Dotfiles: prefer
Show Dotfiles: hidden
Show Dotfiles: format


But when the variable is set in `dotspacemacs/user-config`:
```elisp
(setq ranger-show-hidden t)
```
Then the dot files are shown when starting `deer` or `ranger` as expected, but when `zh` is pressed then it doesn't toggle between the three states, the messages buffer just shows:
>Show Dotfiles: nil

Before pressing `zh` the first time after starting (Spac)Emacs and opening `deer` or `ranger`, then the variables value is:
>ranger-show-hidden is a variable defined in ‘ranger.el’.
Its value is t
Original value was hidden

After pressing `zh`:
>ranger-show-hidden is a variable defined in ‘ranger.el’.
Its value is nil
Original value was hidden

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d44522ee1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git github helm imenu-list
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org ranger
            (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by Rareform** [comment]
Sorry, I am git illiterate, what should I do to report it upstream? Should I close this issue and report it as a ranger issue?

**Comment by duianto** [comment]
`upstream` just means the source.

This thread might explain it better:
https://stackoverflow.com/questions/2739376/definition-of-downstream-and-upstream

Keep this issue open until it's fixed in the ranger repository.
