### ISSUE TITLE
The '-key behaves as the d-key instead of invoking pdf-view-jump-to-register

### ISSUE THREAD

**Issue by nhmacuk** [syl20bnr/spacemacs#13270]
#### Description :octocat:
In pdf-view, the command jump-to-register seems to be bound to the  ```'``` key. However, when pressed, it performs the same action as pressing the ```d``` key, namely going down to the bottom of the page.
What I tried so far:
```
;; trying to fix ' to invoke "pdf-view-jump-to-register"
    ;;(with-eval-after-load 'pdf-view
    ;;  (evil-define-key 'evilified pdf-view-map (kbd "'") 'pdf-view-jump-to-register))
    ;(defun mp-add-pdf-view-keys ()
    ;  (local-set-key (kbd "'") 'pdf-view-jump-to-register))
    ;(add-hook 'pdf-view-hook 'mp-add-pdf-view-keys)

  ;; http://blog.lujun9972.win/emacs-document/blog/2019/03/14/evil-guide/
  ;;(evil-make-overriding-map pdf-view-mode-map 'normal)
  ;;(evil-define-key 'normal pdf-view-mode-map "'" 'pdf-view-jump-to-register)

    ;;   (add-hook 'pdf-view-mode-hook
    ;;     (lambda ()
    ;;      (local-set-key (quote [']) (quote pdf-view-jump-to-register))))
    (global-set-key (kbd "s-M-'") 'pdf-view-jump-to-register)
```
The last line works, but the keybinding is not optimal. 

#### Reproduction guide :beetle:
- Start Emacs
- open a pdf-file in pdf-view
- mark a page using ```m```.
- try visit the mark using ```d```.

*Observed behaviour:* :eyes: :broken_heart:
The key ```'``` to invoke the behavior bound to the key ```d``` (an```d``` works as expected/normal).

*Expected behaviour:* :heart: :smile:
The key ```'``` to invoke "pdf-view-jump-to-register".

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a69323fb3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(ruby gnus
      (plantuml :variables plantuml-jar-path "~/plantuml.jar")
      dap exwm pdf lsp racket html haskell latex helm
      (auto-completion :variables auto-completion-complete-with-key-sequence "fj" auto-completion-complete-with-key-sequence-delay 0.1)
      better-defaults emacs-lisp git markdown bibtex deft pandoc octave
      (org :variables org-want-todo-bindings t)
      python
      (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 35 shell-default-position 'right)
      syntax-checking spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
Sorry, I don't know what I should fill in here. If you need it let me know!

**Comment by duianto** [comment]
It's caused by the `pdf-view-mode` being `evilified`.

Because `SPC h d k '` shows:
>' runs the command image-scroll-up, which is an interactive compiled Lisp
function in ‘image-mode.el’.
>
>It is bound to ', <evilified-state> ', C-v.

`SPC h d K` `pdf-view-mode-map` `RET` shows that single quote is bound to both:
- `'               pdf-view-jump-to-register`
- `<evilified-state> '             image-scroll-up`

The pdf layer evilifies `pdf-view-mode` here:
https://github.com/syl20bnr/spacemacs/blob/0a06c7ca6bea2031d6b432144aefeb92fb22fd0e/layers/%2Breaders/pdf/packages.el#L107

Adding the keybinding to the evilified list, fixes it:
```
        "'" 'pdf-view-jump-to-register
```

`'` now shows `Jump to register:` and pressing `d` jumps to the previously set mark.

I opened a PR:
[pdf] Fix pdf-view-jump-to-register #13291

**Comment by smile13241324** [comment]
Hi @nhmacuk,

I have merged the fix from duianto, would you mind having another go at `develop` and close the issue if your problem is gone.

**Comment by nhmacuk** [comment]
I git rebased my .emacs.d according to your instructions here and in the documentation, and it works perfectly now. Really happy about this, very, very satisfying haha. Thank you for the fast and effective response, and this great pdf-reader!
