### ISSUE TITLE
Flow server in Javascript layer crashes in LSP mode

### ISSUE THREAD

**Issue by robert-zaremba** [syl20bnr/spacemacs#13275]
#### Description

Flow binary in Javascript layer LSP mode crashes immediately. 

Furthermore the syntax is not handled correctly (eg, the `import type` is highlighted in red).

I've also opened a [emacs.stackoverflow question](https://emacs.stackexchange.com/questions/55544/how-to-correctly-configure-flow-backend-for-lsp-mode) to get information about correct Flow setup.

#### Reproduction guide :beetle:
- Start Emacs
- install latest `flow-bin` (eg `yarn global add flow-bin`)
- turn on `lsp` layer and `lsp` backend for javascript as described in the `+layer/javascript/README.md` @develop.
- open a javascript file with `// @flow`  comment)

*Observed behaviour:* :eyes: :broken_heart:

LSP mode is turning on and tries to run the flow server, but it crashes:

    Server flow-ls:7818 status:starting exited with status exit. Do you want to restart it? (y or n) y

Each time I'm trying to restart I see the same thing.

*Expected behaviour:* :heart: :smile:

#### System Info :computer:

+ Linux (Fedora 31)
+ OS: gnu/linux
+ GNU Emacs 26.3
+ Spacemacs: 0.300.0
- Spacemacs branch: latest develop, `7b28e62fb02a`
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(asciidoc systemd dap sql ivy auto-completion lsp better-defaults emacs-lisp
          (syntax-checking :variables flycheck-disabled-checkers
                           '(go-build go-test go-errcheck go-unconvert go-megacheck))
          multiple-cursors yaml json markdown html
          (go :variables go-backend 'lsp go-tab-width 4 go-linter 'golangci-lint gofmt-command "goimports" go-format-before-save t)
          (rust :variables rust-format-on-save t rust-backend 'lsp)
          react
          (javascript :variables node-add-modules-path t js2-mode-show-parse-errors nil javascript-backend 'lsp)
          (typescript :variables typescript-linter 'eslint)
          (plantuml :variables plantuml-jar-path "~/bin/plantuml.jar")
          org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2

**Comment by smile13241324** [comment]
Hi @robert-zaremba,
Hmmm I would assume there is an issue between your LSP server and the flow binary. Basically emacs invoces your LSP server using the standard interface and the server does all the rest. I am not really into Javascript so I am not sure whether the javascript server impl you are using is actually supporting flow additions.

Can you tell which lsp server you are using and what the content of the *LSP* buffer is? There should be a normal *LSP* and a *LSP-error* buffer, both would be interesting.

**Comment by robert-zaremba** [comment]
@smile13241324 thanks for responding.
I've spend more time debugging this issue. The problem was that my projects / LSP project was assigned to the whole repository, which contains few applications (Backend in Go and frontend in JavaScript / Flow). The project root was the repository root. This doesn't work (I don't know why). Apparently LSP backend for Flow (`flow-bin`, in emacs-lsp it has ID: `flow-ls`) expect that the project root is the place where there is `package.json` (and probably `.flowconfig`). 
I couldn't find more meaningful error which could explain that. I think that LSP tries to run `flow` binary form the LSP project root - which won't work, because we need to run it from the `.flowconfig` location.

**Comment by robert-zaremba** [comment]
So the solutions is:

1. Make sure your LSP project is initialized with `.flowconfig` in the project root directory.
1. Make sure that `flow-bin` is installed.
1. Add `flow-js2-mode` package.
1. Enable `flow-js2-mode` in .js files to support flow syntax, eg:

        (add-hook 'js2-mode-hook #'flow-js2-mode))

**Comment by robert-zaremba** [comment]
Maybe we should add some of this to the `+lang/javascript/README.md`?
