### ISSUE TITLE
~C-e~ cursor not go to line end

### ISSUE THREAD

**Issue by hamkido** [syl20bnr/spacemacs#13274]
#### Description :octocat:
C-e keybind do not go to line end . better-defaults layer is on my .spacemacs config file.
 I have setting the (defvar better-defaults-move-to-end-of-code-first t) in .emacs.d/layers/+emacs/better-defaults/config.el

#### Reproduction guide :beetle:
- Start Emacs
- open .js file or .org file
- C-e
*Observed behaviour:* :eyes: :broken_heart:
cursor not move
Page down one line
*Expected behaviour:* :heart: :smile:
cursor will go to end of code

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 537e90344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults  graphviz git gtags games helm helpful html git json javascript multiple-cursors org shell-scripts treemacs vue
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by hamkido** [comment]
Narration in the .emacs.d/layers/+emacs/better-defaults/README.org
```
Smart line navigation: Subsequent presses of ~C-a~ toggles between the beginning of the line and the first non-whitespace character. Similarly, subsequent presses of ~C-e~ will toggle between the end of the code and the end of the comments.
```
I looked at similar issues but couldn't find a solution.

**Comment by duianto** [comment]
Your system info shows that your using:
>Editing style: vim

With the `vim` editing style in:
- Normal state: `C-e` is bound to `evil-scroll-line-down`.
- Insert state: `C-e` is bound to `evil-copy-from-below` which copies the character on the line below the cursor.

You can press `C-z` to toggle to and from Emacs state, where you can use the Emacs bindings, including the better defaults `C-e` for toggling between the code end and the line end.

Or if you want it to enable the Emacs state automatically when you enter Evil insert state, then you can change the: `dotspacemacs-editing-style`
From: `'vim`
To: `'hybrid`

**Comment by hamkido** [comment]
I tried what you call C-z switching to emacs style and it works great.
Then I change
dotspacemacs-editing-style 'vim
to
dotspacemacs-editing-style 'hybird.
I refreshed emacs, opened a .org file and press a to changed to insert state.
But C-e still not work and C-a still works.

**Comment by hamkido** [comment]
I think this might be my personal file configuration problem.
I tried to delete .emacs.d/ , and Re- git clone spacemacs there.
Cleanly installed spacemacs works
Thank you
