### ISSUE TITLE
spacemacs hang when I use tramp to open a remote python script

### ISSUE THREAD

**Issue by chuanma** [syl20bnr/spacemacs#13280]
**Description**
I can remotely open/edit/save other files without any issue. However, the entire spacemacs becomes frozen when I try to open a python script remotely.

**Reproduction guide** 
Start Emacs
C-x C-f
type `/ssh:<username>@<ip_address>:<path/to/a/python/script>`

**Observed behaviour:** 
Spacemacs frozen and it keeps using 99% CPU time.

**Expected behaviour:** 
Load the python script in spacemacs.

**System Info 💻**
OS: OSX
Emacs: 26.3
Spacemacs: 0.200.13
Spacemacs branch: master
Graphic display: t
Distribution: spacemacs
Editing style: evil
Completion: helm
remote server: ubuntu linux 18.04, python managed by Ananconda 
python settings in spacemacs :
```
  (setq python-shell-completion-native-enable nil)
  (setq python-shell-interpreter "python3")
  (setq python-shell-interpreter-args "-m IPython --simple-prompt -i")
  (setq flycheck-python-pycompile-executable "python3")
  (setq flycheck-python-flake8-executable "flake8")
  (setq flycheck-python-flake8-maximum-line-length 120)
  (setq flycheck-python-pylint-executable "pylint")
```

**Comment by smile13241324** [comment]
I am not using tramp, however would you mind giving it a go with latest develop branch? Master is really old now and we fixed like a ton of bugs on develop. So it could be that your issue is already solved there.

**Comment by tshu-w** [comment]
similar issue #10918

**Comment by chuanma** [comment]
@smile13241324 Just tried it out in develop branch. Same issue.

**Comment by lebensterben** [comment]
please comment under #10918
