### ISSUE TITLE
evil-want-Y-yank-to-eol is void

### ISSUE THREAD

**Issue by demokritos** [syl20bnr/spacemacs#13288]
#### Description :octocat:

When customizing group `evil`, an error occurs: `Symbol’s value as variable is
void: evil-want-Y-yank-to-eol`

#### Reproduction guide :beetle:
- Start Emacs
- `M-x customize-group<RET>evil`

*Observed behaviour:* :eyes: :broken_heart:

I see the error above, custom variables' states are all `UNINITIALIZED, you
should not see this.`

*Expected behaviour:* :heart: :smile:

I shouldn't see any error, and Custom variables' states shouldn't be
`UNINITIALIZED, you should not see this.`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f578e618a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust systemd javascript html yaml lsp
      (haskell :variables haskell-completion-backend 'lsp)
      helm
      (auto-completion :variables auto-completion-tab-key-behavior 'complete auto-completion-return-key-behavior nil)
      better-defaults emacs-lisp git markdown multiple-cursors treemacs neotree org ibuffer
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh")
      spell-checking syntax-checking unicode-fonts gnus react c-c++ julia racket scheme shell-scripts latex prolog games emoji spotify twitter themes-megapack docker go exwm)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by demokritos** [comment]
It seems that this is evil's issue. Evil does not properly initialize custom variables which are initialized by `evil-after-load-hook`.

**Comment by duianto** [comment]
The upstream issue can be found here: Custom variables are void https://github.com/emacs-evil/evil/issues/1278
