### ISSUE TITLE
Lost all my config?

### ISSUE THREAD

**Issue by Adrianzo** [syl20bnr/spacemacs#13285]
Hey, I went into the menu "Options > Customize Emacs" by chance. Somehow some code in the bottom of my `~/.spacemacs` was added then; and so, all my themes got a white background. I didn't realize until now that it's late in the night and I was looking forward to... work... anyway, I really needed the dark background so I removed that bit, even though this was under the commented section that had a warning... I only removed the bit that I guess was inserted by that random drift through emacs customization (which I didn't use for anything useful, only creating this aesthethic issue that now has grown into my nemesis xD).

Apparently, now my `~/.spacemacs` is ignored altogether and every time I start spacemacs it's asking me which editing style I prefer. I have manually seen  my `~/.spacemacs` file and it's still usable... well, another stroll through "Options > Customize Emacs" might have added another bit because I like to repeat my errors.

Here's  my `~/.spacemacs` tail:

```
;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-faces-vector
   [default default default italic underline success warning error])
 '(ansi-term-color-vector
   [unspecified "#FFFFFF" "#d15120" "#5f9411" "#d2ad00" "#6b82a7" "#a66bab" "#6b82a7" "#505050"])
 '(custom-enabled-themes (quote (zenburn)))
 '(custom-safe-themes
   (quote
    ("7aaee3a00f6eb16836f5b28bdccde9e1079654060d26ce4b8f49b56689c51904" "fa2b58bb98b62c3b8cf3b6f02f058ef7827a8e497125de0254f56e373abee088" "bffa9739ce0752a37d9b1eee78fc00ba159748f50dc328af4be661484848e476" "274fa62b00d732d093fc3f120aca1b31a6bb484492f31081c1814a858e25c72e" default)))
 '(evil-want-Y-yank-to-eol nil)
 '(fci-rule-character-color "#d9d9d9")
 '(helm-completion-style (quote emacs))
 '(inferior-R-args "--no-save --no-restore-data")
 '(linum-format " %5i ")
 '(package-selected-packages
   (quote
    (...lots of packages... ace-window ace-link ace-jump-helm-line)))


```

Please save me!

**Comment by martijnjanssen** [comment]
Probably this is due to an error in parsing your spacemacs configuration. You can diff with the template config and check the differences with `<spc> f e D`. I just had the same issue with me making an error with a closing bracket and spacemacs re-asking for my preferred editing style.

**Comment by Adrianzo** [comment]
Thanks! Couldn't see anything out of order, but commenting out the whole tail (posted above) solved it.
