### ISSUE TITLE
*lsp-log* show Command "ccls" is not present on the path

### ISSUE THREAD

**Issue by wutianjun5858** [syl20bnr/spacemacs#13294]
*lsp-log* show Command "ccls" is not present on the path
- emacs: 26.3
- spacemacs: f033925 2020-02-20 | [javascript] Fix another broken link in the documentation

but spacemacs(1aa0af2 2019-06-26 | Move indirect buffer key bindings to `SPC b N` prefix  (syl20bnr)) is ok, so is there a new configuration method?

my config:
```
(c-c++ :variables
            c-c++-default-mode-for-headers 'c++-mode
            c-c++-adopt-subprojects t
            c-c++-backend 'lsp-ccls
            c-c++-lsp-executable(file-truename "~/ccls/Release/ccls")
            c-c++-lsp-sem-highlight-rainbow t
            c-c++-enable-clang-format-on-save t
            )
```

**Comment by smile13241324** [comment]
The c++ layer has been reworked by sylable quite some time ago. I have checked the latest documentation and setting the lsp executable is package dependent now.

A similiar config to yours would look like this:
```elisp
     (c-c++ :variables
            c-c++-default-mode-for-headers 'c++-mode
            c-c++-adopt-subprojects t            
            c-c++-backend 'lsp-ccls
            ccls-executable "/my/path" ;; ccls specific config setting from the ccls package
            c-c++-lsp-enable-semantic-highlight 'rainbow
            c-c++-lsp-semantic-highlight-method 'overlay ;; you will most probably want this for precise highlighting
            c++-enable-organize-includes-on-save t ;; you will most probably want this if you wanted format on save
            c-c++-enable-clang-format-on-save t)
```

Would you mind giving it a go, and tell me the results?
If it is still not working I can take a deeper look. Right now this config is entirely based on the documentation and the lisp code I have seen from the packages.

**Comment by wutianjun5858** [comment]
@smile13241324 Thanks, it works
