### ISSUE TITLE
SPC SPC is undefined (again)

### ISSUE THREAD

**Issue by achikin** [syl20bnr/spacemacs#13295]
#### Description :octocat:
SPC SPC is undefined (again)

#### Reproduction guide :beetle:
- Start Emacs
- Press SPC SPC

*Observed behaviour:* :eyes: :broken_heart:
SPC SPC is undefined

*Expected behaviour:* :heart: :smile:
Helm M-x window shows up

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f03392573)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python yaml javascript html helm auto-completion better-defaults emacs-lisp syntax-checking git markdown sql themes-megapack
        (haskell :variables haskell-completion-backend 'company-ghci)
        (clojure :variables cider-dynamic-indentation nil clojure-enable-clj-refactor t clojure-align-forms-automatically nil clojure-indent-style 'align-arguments))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
```

**Comment by gdkrmr** [comment]
This usually happens if there are errors during loading of the config. Start emacs and check you message buffer.

**Comment by smile13241324** [comment]
I agree with gdkrmr, if this happens it is a sure sign that there was a fatal error during applying your spacemacs config. The best bet to find what is causing is is to:
* Deactivate your user config and user init if set
* Compare your config to the latest version of the template with `SPC f e D`
* Disable layers till your config works again, and double check whether the layer is misconfigured

If this all does not help post the content of your message buffer here for futher examination.

**Comment by gdkrmr** [comment]
On my main machine, I have some org agenda files, when copying the config to another computer these files are not there, the message buffer reports an error and `SPC SPC` doesn't work.

**Comment by achikin** [comment]
@gdkrmr @smile13241324 looks like it is a config issue indeed. I've generated a new config and cherry-picked customizations from the old one minus some 2yo legacy. Everything works fine, thank you!
