### ISSUE TITLE
In markdown-mode, <backspace> deletes a whole Hangul syllable

### ISSUE THREAD

**Issue by demokritos** [syl20bnr/spacemacs#13303]
#### Description :octocat:

In markdown-mode, `<backspace>` deletes a whole Hangul syllable. A Hangul
syllable is composed of some key inputs. So when a syllable is not completed,
`<backspace>` should cancel only a key input backwards. This happens when org
layer is enabled as well as markdown layer. In org-mode, this doesn't happen.

describe-key of `<backspace>`:
```
<backspace> runs the command orgtbl-hijacker-command-109 (found in
orgtbl-mode-map), which is an interactive Lisp function.

It is bound to <backspace>.

(orgtbl-hijacker-command-109 ARG)

In tables, run ‘org-delete-backward-char’.
Outside of tables, run the binding of ‘<backspace>’ or ‘DEL’.
```

#### Reproduction guide :beetle:
- Start Emacs
- Switch to `*scratch*` buffer
- Type `M-x markdown-mode`
- Type `M-x set-input-method<RET>korean-hangul`
- Input "한" with key `g`, `k` and `s` in order and type `<backspace>`
- If "한" is deleted, the problem is reproduced.
  If "한" is changed to "하", it is not.

*Observed behaviour:* :eyes: :broken_heart:
"한" is deleted

*Expected behaviour:* :heart: :smile:
"한" is changed to "하"

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 733a3a819)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm markdown multiple-cursors org treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by smile13241324** [comment]
Hmmm I have tried that on my linux box and it works as described by you. Please double check your config, update all emacs packages to the latest version and maybe retry with the latest stable version of emacs (26.3).

**Comment by demokritos** [comment]
This time, I tested with emacs 26.3. I could always reproduce this issue. I have used the default setting with only markdown and org layer added.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 733a3a819)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm markdown multiple-cursors org treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by smile13241324** [comment]
Reproduced the issue, after me updating my emacs packages I see the same behaviour. However with the older version it worked as expected.

The problem is caused by the latest version of `org`. Please report a bug upstream.

As a quick workaround you can bind `backspace` to `markdown-outdent-or-delete` or remove `org-layer`.

**Comment by lebensterben** [comment]
@demokritos 
It's true that a Hangul consists of multiple components, but a each component is a complete grapheme in its own right.
From this perspective it's not a bug.
Anyway please report this to emacs mail-list.
