### ISSUE TITLE
When opening the easy-customization menu, the default emacs keybindings are used instead of the evil-mode keybindings.

### ISSUE THREAD

**Issue by nhmacuk** [syl20bnr/spacemacs#13309]
#### Description :octocat:
When opening the easy-customization menu, the default emacs keybindings are used instead of the evil-mode keybindings.

#### Reproduction guide :beetle:
- Start Emacs
- open a easy-customization menu with SPC-SPC customize-group or SPC-SPC customize-mode

*Observed behaviour:* :eyes: :broken_heart
- notice the emacs keybindings are activated

*Expected behaviour:* :heart: :smile:
- notice the evil-mode keybindings are activated

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 07d12c130)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(ruby lsp gnus
      (plantuml :variables plantuml-jar-path "~/plantuml.jar")
      dap
      (exwm :variables exwm-custom-init
            (lambda nil
              (exwm/autostart-process "Unclutter " "unclutter")
              (exwm/autostart-process "Dropbox " "dropbox")))
      pdf racket html haskell latex helm auto-completion better-defaults emacs-lisp git markdown bibtex deft pandoc octave
      (org :variables org-want-todo-bindings t)
      python
      (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 35 shell-default-position 'right)
      syntax-checking spell-checking version-control
      (java :variables java-backend 'lsp)
      javascript)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Duplicate of:
Customize mode not evil #6699

**Comment by nhmacuk** [comment]
Oh thanks, didn't notice, I see the solution is indeed mentioned https://github.com/syl20bnr/spacemacs/issues/6699#issuecomment-235997803
