### ISSUE TITLE
When opening a pdf-file in pdf-view from the bookmark menu on the spacemacs home page, the default emacs keybindings are used instead of the evil-mode keybindings.

### ISSUE THREAD

**Issue by nhmacuk** [syl20bnr/spacemacs#13308]
#### Description :octocat:
When opening a pdf-file in pdf-view from the bookmark menu on the spacemacs home page, the default emacs keybindings are used instead of the evil-mode keybindings. When the pdf-file is first opened without using the bookmark, the pdf opens with the expected evil-keybindings, and if the bookmark is used to go to the right page, the expected evil-mode keybindings are still working. 

#### Reproduction guide :beetle:
- Start Emacs
- open a pdf-file in pdf-view from the bookmark menu on the spacemacs home page

*Observed behaviour:* :eyes: :broken_heart:
- notice the emacs keybindings are activated

*Expected behaviour:* :heart: :smile:
- notice the evil-mode keybindings are activated when opening the file from bookmark, without having to open the pdf first. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 07d12c130)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(ruby lsp gnus
      (plantuml :variables plantuml-jar-path "~/plantuml.jar")
      dap
      (exwm :variables exwm-custom-init
            (lambda nil
              (exwm/autostart-process "Unclutter " "unclutter")
              (exwm/autostart-process "Dropbox " "dropbox")))
      pdf racket html haskell latex helm auto-completion better-defaults emacs-lisp git markdown bibtex deft pandoc octave
      (org :variables org-want-todo-bindings t)
      python
      (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 35 shell-default-position 'right)
      syntax-checking spell-checking version-control
      (java :variables java-backend 'lsp)
      javascript)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
How are you seeing that the Emacs key bindings are active?
Which keys don't work as expected?

When a .pdf file has previously been saved with `SPC f b`.
When it's opened from the Bookmarks: section of the Spacemacs home buffer (`SPC b h`).

Then the `evil-state` says:
>evil-state is a variable defined in ‘evil-vars.el’.
Its value is ‘evilified’

And pressing: `:` (colon)
opens the evil-ex prompt.
`C-h l` (l = lowercase L) shows: `: [evil-ex]`

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6d024e789)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 pdf
                 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6d024e789)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion c-c++ command-log emacs-lisp git github
            (gnus :variables gnus-summary-thread-gathering-function 'gnus-gather-threads-by-subject)
            go helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org pdf
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by nhmacuk** [comment]
*How are you seeing that the Emacs key bindings are active?*
The bindings that work correspond to the regular keybindings as stated in the pdf-view documentation. e.g. <kbd> k </kbd> kills the document  as in emacs-keybindings instead of going up like in vim-keybindings, and <kbd> C-v </kbd> goes to the next page, instead of doing nothing in de pdf-view vim keybindings. 

I'll try to see the evil-state next session. I don't expect the colon to work.

**Comment by duianto** [comment]
Your using the `hybrid` editing style, I was using the `vim` editing style.
`hybrid` uses the Emacs key bindings where the cursor isn't in normal state.

However in Windows I'm still getting the vim key bindings with the `hybrid` editing style in a `pdf-view` buffer.

While in PopOS (Linux) I'm getting the Emacs bindings just like your describing.

`evil-state` shows:
>evil-state is a variable defined in ‘evil-vars.el’.
Its value is ‘emacs’
