### ISSUE TITLE
[EasyPG Assistant] menu and keybindings useful ?

### ISSUE THREAD

**Issue by jr0cket** [syl20bnr/spacemacs#13319]
Would it be useful to add a top-level menu for the [EasyPG Assistant](https://www.gnu.org/software/emacs/manual/html_mono/epa.html), part of Emacs for encrypting/decrypting files and managing gpg keys?

Usecases for EasyPG Assistant include encrypting org-mode files, encrypting passwords and personal access tokens (e.g. `.authinfo.gpg` for use with magit forge)

There are numerous functions starting with `epa-` that have no specific keybindings in Spacemacs.

EasyPG Assistant menu suggestions
1) SPC E menu
2) SPC a e menu

Useful commands that would benefit from keybindings
* `epa-encrypt-file`
* `epa-decrypt-file`
* `epa-list-keys`
* `epa-sign-region`

There are more examples in the https://www.gnu.org/software/emacs/manual/html_mono/epa.html page.

Note: files saved with the `.gpg` extension trigger a prompt to encrypt that file with any known keys (or using symetric crypto if there are no keys available).  Opening a `.gpg` file also automatically decrypts the file.

Feedback is welcome as to if this is a useful addition to the Spacemacs menu, which commands and keybindings should be used.

Thank you.

**Comment by dvzubarev** [comment]
I used this private [layer](https://gist.github.com/dvzubarev/b129ffb62f9edf9b9fc8e24c86b7aaa1) for some time. It may be helpful for anyone who wants to bring it to spacemacs.

**Comment by smile13241324** [comment]
@jr0cket hmmm sounds like a good addition. Your proposed bindings are nice too.
Care to make a PR?

**Comment by jr0cket** [comment]
Thanks for the feedback on EasyPG.  I'll knock up a PR over the weekend.

**Comment by nixmaniack** [comment]
Sounds good. I would vote for `SPC a e` just because not many users seem to be using it(epa-*` and `SPC E` seems too precious for such functionality in my opinion.

**Comment by smile13241324** [comment]
@nixmaniack hmm you could be right, lets run with `SPC a e` if this ends up to be too complicated we can still provide a shorter combination in the future.

**Comment by jr0cket** [comment]
I am curious as to if this should be a separate layer.  EPA is already part of Emacs, so seems strange to have a layer, but then again if custom code is required (as @dvzubarev suggests) then a layer seems more useful.  

If its just a matter of adding keybindings, I have not yet found no obvious place to add them.

Suggestions are most welcome.  Thanks.

**Comment by smile13241324** [comment]
Lets put it here
https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bspacemacs/spacemacs-defaults/README.org
.

In generel this is the place for configuring build in packages.

**Comment by jr0cket** [comment]
Okay, that make sense.  I am assuming adding the keybinding definition to line 183 onward, between `applications` and `buffers` would be the right place.

I assume I should use the new Spacebind approach.  This configuration seems to work so far
```
(spacemacs|spacebind
 "Encrypt / decrypt files with Easy PG"
 :global
 (("a" "applications"
   ("e"  "easy pg"
    ("e" epa-encrypt-file "Encrypt file...")
    ("d" epa-decrypt-file "Decrypt file to...")
    ("k" epa-list-keys "List GPG keys...")
    ("K" epa-list-secret-keys "List secret GPG keys...")))))
```
I will review the other commands and see what else seems useful
Thank you

**Comment by smile13241324** [comment]
Merged. @jr0cket can you verify that all is working and close the issue?

**Comment by jr0cket** [comment]
Thank you.
