### ISSUE TITLE
Reading gmane groups really slow with gnus layer.

### ISSUE THREAD

**Issue by amardeep** [syl20bnr/spacemacs#1331]
This is due to setting gnus-fetch-old-headers to t.
Its help says:
> This feature can seriously impact performance it ignores all
> locally cached header entries.  Setting it to t for groups for a
> server that doesn't expire articles (such as news.gmane.org),
> leads to very slow summary generation.

Setting it nil fixes the issue. Please consider not setting it to t by default.

**Comment by andreas-h** [comment]
I'm wondering why this was closed without comment?  I ran into the same problem recently, and believe that if you are against changing the default value, at least this should be documented.  I'm happy to prepare a PR to do either one -- what do you guys prefer?

**Comment by TheBB** [comment]
It's not closed.

**Comment by andreas-h** [comment]
Funny, my PC at home clearly showed the red CLOSED badge.

Anyways, which way forward do you prefer?

**Comment by TheBB** [comment]
It's referred to from an issue that's closed, maybe that's what you saw.

I don't use gnus so I have no input to give. People who use it should come to a consensus I guess. It seems mu4e is much more popular

**Comment by gour** [comment]
> It seems mu4e is much more popular.

It might be, but mu4e does not support newsgroups (nntp). Anyway, I'm new Spacemacs user and old Gnus one (although not a power one), but setting it to nil really helps. :+1:
