### ISSUE TITLE
Geolocation layer does not work with Mac OSX 

### ISSUE THREAD

**Issue by MrMic** [syl20bnr/spacemacs#13311]
#### Description :octocat:
<< geolocation does not work as expexted with Mac OSX >>

#### Reproduction guide :beetle:
- Start Emacs
- << Give geolocation layer the same variables values as with my
Ubuntu 18.04. With Ubuntu, all is working, but with Mac OSX, I always
got an Input for Username and then password! I have also noticed that
the URL is the same: New York ... without any appid ... but I gave
all of theses input in my .spacemacs file.
It seems that all the configuration is not taken into account ...
It behaves always the same way with or without it.
I have also given all the required authorization in my Mac settings.>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 937ab0111)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(finance
 (geolocation :variables geolocation-enable-weather-forecast t)
 lsp
 (osx :variables osx-option-as 'none)
 html
 (javascript :variables javascript-import-tool 'import-js node-add-modules-path t javascript-backend 'lsp javascript-fmt-tool 'prettier js2-basic-offset 2 js-indent-level 2)
 (typescript :variables typescript-backend 'lsp typescript-fmt-on-save t)
 react yaml helm
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
 better-defaults emacs-lisp clojure git ansible terraform docker
 (python :variables python-backend 'lsp)
 (conda :variables conda-anaconda-home "/usr/local/Caskroom/miniconda/base")
 markdown
 (org :variables org-enable-reveal-js-support t)
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control themes-megapack twitter
 (go :variables go-tab-width 4 go-use-gometalinter t gofmt-command "goimports")
 (treemacs :variables treemacs-use-filewatch-mode t treemacs-use-follow-mode t treemacs-use-collapsed-directories 3)
 (ranger :variables ranger-show-preview t)
 (dart :variables lsp-dart-sdk-dir "/Users/mic/WebstormProjects/Flutter/flutter/bin/cache/dart-sdk/" dart-server-sdk-path "/Users/mic/WebstormProjects/Flutter/flutter/bin/cache/dart-sdk/" dart-server-format-on-save t))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Please report in upstream.
