### ISSUE TITLE
Clicking "Release Notes" link on Spacemacs home screen in iTerm2 prevents user from exiting program

### ISSUE THREAD

**Issue by JeremyDurnell** [syl20bnr/spacemacs#13335]
#### Description :octocat:
Clicking "Release Notes" link on Spacemacs home screen/buffer in terminal (iTerm2) causes key capture mode to be activated with no way to exit

#### Reproduction guide :beetle:
- Start Emacs
- start emacs in iTerm2: `emacs . -nw`
- click "Release Notes" link with the mouse

*Observed behaviour:* :eyes: :broken_heart:
The mini-buffer just fills up with key presses, mouse clicks, etc... (as you keep typing/clicking)

*Expected behaviour:* :heart: :smile:
Should execute the link action; display release notes, or at least not hijack terminal

#### System Info :computer:
- OS: macOS High Sierra v 10.13.6
- Emacs: 28.0.50 (a13d1f953)
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: nil 
- Distribution: spacemacs-base
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
```

**Comment by lebensterben** [comment]
Please use `develop` branch and retry.
