### ISSUE TITLE
Weird autocomplete in Django templates/web-mode

### ISSUE THREAD

**Issue by kennethlove** [syl20bnr/spacemacs#1333]
In a Django template, typing `{%` produces `{%|}` as expected (with `|` as the cursor). Once you press space, though, to add the rest of the tag, something is changing the existing tag to `{% | %}}`. The same happens for `{{` tags: `{{ <space>` produces `{{ | }}}}`.

**Comment by kennethlove** [comment]
I'm guessing it's a conflict between the standard auto-pairing/closing of things like parentheses and braces and web-mode's auto-pairing/closing of them.

**Comment by CestDiego** [comment]
I don't see this issue. Is your html file called .html or .djhtml?

**Comment by kennethlove** [comment]
`.html`. I can record my screen if you'd like.

**Comment by CestDiego** [comment]
you can use [asciinema](http://asciinema.org) terminal emacs

**Comment by kennethlove** [comment]
[video](https://dl.dropboxusercontent.com/u/15988/spacemacs.mov)

**Comment by CestDiego** [comment]
Just to confirm, you are on branch master right? I think this behaviour changes in

**Comment by kennethlove** [comment]
I am indeed on master. I was using a symlinked version of the python layer (to have my YAPF plugin) but it was up-to-date with master. Just to be sure, I deleted the symlink and re-checked-out the python layer. Same behavior.

**Comment by nookiepl** [comment]
+1, same behaviour here.

**Comment by nookiepl** [comment]
I've found workaround in smartparens issue tracker.

You need to add

(sp-local-pair 'web-mode "<" nil :actions '(:rem insert))
(sp-local-pair 'web-mode "{" nil :actions '(:rem insert))

to configuration (I've added it to my web-mode-init functon, but don't know if it's correct, excuse me if not, this is my first day with emacs + spacemacs). :P

**Comment by StreakyCobra** [comment]
Does anybody still has this behaviour?

**Comment by darkfeline** [comment]
Seems to be fixed for me.

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
