### ISSUE TITLE
slime-autodoc not working

### ISSUE THREAD

**Issue by laynor** [syl20bnr/spacemacs#13342]
#### Description :octocat:
Slime autodoc is not working

#### Reproduction guide :beetle:
- Start Emacs
- open a common lisp file
- M-x slime RET
- Back to the lisp file
- Insert the text
```
(car foo)
```
Notice the eldoc for `car` is shown while typing (after typing the space character)
- Move the cursor between `car` and `foo`

*Observed behaviour:* :eyes: :broken_heart:
No eldoc is displayed

*Expected behaviour:* :heart: :smile:
The eldoc for car should be shown in the minibuffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e0aee1554)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion
  (haskell :variables haskell-completion-backend 'intero))
 better-defaults clojure cmake common-lisp
 (c-c++ :variables c-c++-backend 'lsp-cquery)
 csv dap emacs-lisp factor fsharp git github haskell helm html ibuffer idris javascript lsp
 (python :variables python-test-runner
         '(nose pytest)
         python-backend 'lsp)
 racket react shell-scripts sql syntax-checking
 (version-control :variables version-control-diff-tool 'diff-hl)
 windows-scripts yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
```

**Comment by laynor** [comment]
This fixed the problem for me:
```
(defun fix-eldoc-setup ()
  (interactive)
  (setq eldoc-documentation-functions '(slime-autodoc)))

(use-package slime
  :config
  (add-hook 'slime-autodoc-mode-hook
            'fix-eldoc-setup))
```

Normally, `slime-autodoc-mode` sets `eldoc-documentation-function`, but that is not working on my end. using `eldoc-documentation-functions` works instead (note the final `s`).

**Comment by duianto** [comment]
This is what I'm seeing on the `develop` branch with updated packages:
(without the suggestions above)

![VirtualBoxVM_2020-03-20_18-38-07](https://user-images.githubusercontent.com/13420573/77191715-a3fefa80-6adb-11ea-9624-cc925315ee24.png)

In PopOS with Emacs 26.3 and Windows 10 with both Emacs 26.3 and 27.0.90.

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b7fd2fab6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log common-lisp emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 python
                 (shell :variables shell-default-shell 'term shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bb8ec23ec)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey clojure command-log common-lisp emacs-lisp ess git helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP

</pre>
</details>
