### ISSUE TITLE
emacsclient -t crashes reliably

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#13344]
#### Description :octocat: 

When I run `emacsclient -t -c` on the terminal, it
briefly opens, and then exits with the error code `1`. No error message is
displayed.

#### Reproduction guide :beetle:
- Start Emacs Server: `emacs --daemon &`
- Open an Emacs Client with GUI that connects to the server, e.g., `emacsclient -c &`
- Open an Emacs Client in the terminal, e.g., `emacsclient -t -c`. 

*Observed behaviour:* :eyes: :broken_heart:

The `emacsclient -t -c` does open a client in the terminal briefly that shows the `*scratch*` buffer, but in approx. ~1 second it exits with the error code 1.

Inspecting the `*Messages*` buffer in the client using the GUI, I observe lines like this:

  `Unable to load color "nil" [2 times]`

where the count is incremented every time I open the client on the terminal. I've tried adding 

  `(customize-set-variable 'solarized-termcolors 256)`

to my `.spacemacs` but this does not resolve the issue.

*Expected behaviour:* :heart: :smile:

I expect to be able to create both GUI and terminal emacsclients to the emacs server.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e0aee1554)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(better-defaults emacs-lisp
                 (git :variables git-gutter-use-fringe t git-enable-github-support t)
                 helm markdown javascript yaml python multiple-cursors
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 osx shell-scripts
                 (rust :variables rust-backend 'lsp)
                 treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Alexander-Miller** [comment]
Sounds like a problem with your theme. Try changing your `dotspacemacs-themes`.

Also try it with debug-on-error.

Finally what is the value of `ansi-color-names-vector`?

**Comment by lebensterben** [comment]
when running emacs in daemon mode, make sure it's not fg-daemon
