### ISSUE TITLE
lsp-ui falls down with error: Symbol’s value as variable is void: lsp-ui-doc-winum-ignore

### ISSUE THREAD

**Issue by akdasa** [syl20bnr/spacemacs#13355]
#### Description :octocat:
lsp-ui falls down with error: `Symbol’s value as variable is void: lsp-ui-doc-winum-ignore`

#### Reproduction guide :beetle:
- Start Emacs
- Open any filw which uses LSP (python for example)

*Observed behaviour:* :eyes: :broken_heart:
- Error in *Messages* buffer: `Symbol’s value as variable is void: lsp-ui-doc-winum-ignore`
- No .dir-locals.el applied (it was how I found an issue)

*Expected behaviour:* :heart: :smile:
- No LSP related errors in messages buffer

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 884afe138)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lsp nginx auto-completion git helm multiple-cursors syntax-checking
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     (treemacs :variables treemacs-no-png-images t treemacs-lock-width t)
     (typescript :variables typescript-backend 'lsp)
     (vue :variables vue-backend 'lsp)
     (python :variables python-test-runner 'pytest python-backend 'lsp))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
LSP :: Restarting pyls:11751
LSP :: pyls has exited (killed: 9)
LSP :: Restarting LSP in buffer main.py
error in process sentinel: eval-after-load: Symbol’s value as variable is void: lsp-ui-doc-winum-ignore
error in process sentinel: Symbol’s value as variable is void: lsp-ui-doc-winum-ignore
LSP :: pyls:11771 initialized successfully
```

**Comment by akdasa** [comment]
Here is my spacemacs config file: https://github.com/akdasa/.dotfiles/blob/master/spacemacs/.spacemacs

**Comment by bjarkevad** [comment]
I think it's worth noting that this has much bigger impact than just an erroneous log message - LSP is pretty much broken completely. 

I did some digging, and found the culprit: https://github.com/emacs-lsp/lsp-ui/commit/5ba04fd9f37f808bb0abf848ea939e8a31d5b412#diff-6b8b8bc40bca8fcb893d9b4752f6167

Reverting that commit in `lsp-ui` fixed the problem.

**Comment by shpark** [comment]
This is the same problem that I am encountering!

A possible approach would be adding these lines to your `.spacemacs`
```
     (lsp :variables
          lsp-ui-doc-winum-ignore t
          lsp-ui-doc--buffer-prefix " *lsp-ui-doc-")

```

These variables are introduced to `lsp-ui` by emacs-lsp/lsp-ui#308.

I know this is not a fundamental solution, but kinda useful until this issues is resolved.

**Comment by akdasa** [comment]
Thank you guys for so fast response. Solution provided by @shpark works fine for me.

**Comment by smile13241324** [comment]
Guys do you still have this issue? I am working with python LSP almost every day and it just works for me, at least on the latest version (yesterday). I am running pyls 0.30.0 and there is at least one additional issue with the latest version of it and lsp-mode here #13358. 

Do you have this issue with other lsp powered modes too?
And is this happening on all operating systems for I seem not to have it.

I am running on Linux (Manjaro).

**Comment by ljupchokotev** [comment]
@smile13241324: Also running on Manjaro, and had this issue with Go.

I just tried removing the above workaround and it doesn't seem to happen anymore. I am running on the latest commit to the develop branch. I guess it was fixed in Spacemacs or maybe it was coming from upstream? Not sure. I will run it like this for a few days to see if it pops up.

**Comment by akdasa** [comment]
@smile13241324 I just tried to return to the configuration without a workaround, and it seems to me that it works fine.

**Comment by smile13241324** [comment]
Looks like its working. Please reopen if it doesn't.
