### ISSUE TITLE
<C-i> behaves as <TAB> in normal-mode in hybrid-mode

### ISSUE THREAD

**Issue by nhmacuk** [syl20bnr/spacemacs#13352]
#### Description :octocat:
When pressing <kbd> C-i </kbd> in edit/normal-mode in hybrid-mode, the key acts as a TAB, instead of jumping forward to the next position (so the opposite behaviour of <kbd> C-o </kbd>, jumping back).

#### Reproduction guide :beetle:
- Start Emacs
- open any buffer e.g. an existing org-mode file with 100 lines.
- move a few times to a different positions in the file, e.g. by pressing <kbd>5</kbd> <kbd>5</kbd> <kbd>G</kbd>.
- press <kbd> C-o </kbd> and jump back to last position. 
- press <kbd> C-i </kbd>

*Observed behaviour:* :eyes: :broken_heart:
- A tab is inserted like you expect in emacs editing style.

*Expected behaviour:* :heart: :smile:
- jumping forward to last position.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 07d12c130)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(ruby lsp gnus
      (plantuml :variables plantuml-jar-path "~/plantuml.jar")
      dap
      (exwm :variables exwm-custom-init
            (lambda nil
              (exwm/autostart-process "Unclutter " "unclutter")
              (exwm/autostart-process "Firefox " "firefox")
              (exwm/autostart-process "Dropbox " "dropbox")))
      pdf racket html haskell latex helm auto-completion better-defaults emacs-lisp git markdown bibtex deft pandoc octave
      (org :variables org-want-todo-bindings t)
      python
      (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 35 shell-default-position 'right)
      syntax-checking spell-checking version-control
      (java :variables java-backend 'lsp)
      javascript)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```
This would be icing on the cake, hybrid-mode is fantastic and what vim should be like imho.

**Comment by tshu-w** [comment]
you should set `dotspacemacs-distinguish-gui-tab t` in you `init.el`. but maybe this two key only work in normal states?

**Comment by nhmacuk** [comment]
Ah it worked! I mistakenly inserted (setq dotspacemacs-distinguish-gui-tab t) in my  dotspacemacs/user-config instead of the options above (so now I instead configured the variable in. However, now it seem that <C-i> isn't bound to <TAB> in insertion ("emacs") mode anymore. Is it possible to change that without affecting my normal (vim/evil) keybindings?

**Comment by tshu-w** [comment]
@nhmacuk I'm not quite understanding your question. If you want to change keybinding only in emacs mode, you can use `define-key` or `evil-define-key`:
```emacs-lisp
(define-key evil-emacs-state-map (kbd "C-i") #'fun)
(evil-define-key 'emacs 'global (kbd "C-i") #'fun)
```

**Comment by nhmacuk** [comment]
Ah what I meant was: shouldn't <C-i> be set to <TAB> in insertion mode in hybrid mode by default, when setting ```dotspacemacs-distinguish-gui-tab t```?

(is this question below relevant to this issue? If not please ignore)
Does it have to be a function from the list of functions provided by evil-maps like from https://github.com/emacs-evil/evil/blob/master/evil-maps.el ?
Thank you for your suggestion. I haven't been able to make it work yet by adding any of the following lines, although it seems to be in line with the documentation:
(define-key evil-emacs-state-map (kbd "C-i") (kbd "<tab>"))
(evil-define-key 'emacs 'global (kbd "C-i") (kbd "<tab>"))
(define-key evil-emacs-state-map (kbd "C-i") '(kbd "<tab>"))
(evil-define-key 'emacs 'global (kbd "C-i") '(kbd "<tab>"))

**Comment by tshu-w** [comment]
maybe `emacs` should be `hybrid`.

What's the result if you run `describe-key C-i` in hybrid mode(`M-m h d k` and `C-i`), on my side  `C-i` is bound to `(indent-for-tab-command &optional ARG)`, It seems like `C-i` had already bound to tab.

**Comment by nhmacuk** [comment]
Both in insert and in normal mode ```describe-key C-i``` returns:
```<C-i> (translated from TAB) is undefined```

**Comment by smile13241324** [comment]
Hi  @nhmacuk,
I had a look at your issue and for me setting `dotspacemacs-distinguish-gui-tab` to `t` solved the issue. Can you please double check on latest develop and close this issue if this restores the evil binding?

**Explanations:**
By default emacs does not distinguish between `C-i` and `TAB` as well as not between `C-m` and `return`. You can enable this in your dotfile via the above mentioned standard setting. Then evil binds `C-i` to `evil-jump-forward` which is the opposite of `evil-jump-backward` aka `C-o`.

**Comment by nhmacuk** [comment]
Yes, it restores the evil binding. Shall I make another issue for a feature request to have the Emacs/Hybrid-insert binding as tab as default when setting dotspacemacs-distinguish-gui-tab to t, or could that be part of this issue?

**Comment by smile13241324** [comment]
@nhmacuk I think a new issue would be better, there you could also describe more clearly what change you expect.

**Comment by nhmacuk** [comment]
Thanks @smile13241324, I'll add the try to add a link to the feature request when I have opened it.
