### ISSUE TITLE
move cursor into lsp help buffers

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#13351]
When using the `lsp` layer, documentation is shown in buffers that are overlayed. I just recently figured out that you can actually click on these buffers and move the cursor around and scroll these buffers. Once the cursor is inside this buffer, you can also use `SPC b d` to close it.

Is there a way to focus such a buffer without moving the mouse? When such a buffer is open and I press `SPC`, then it disappears.

**Comment by duianto** [comment]
@yyoncho Do you know if there's a key binding for this?

**Comment by yyoncho** [comment]
@duianto I think this should be addressed at lsp-ui side probably by enabling view-mode in that buffer. I am not familiar with that piece of code.
