### ISSUE TITLE
magit-status fails on Emacs 27.0.90 pretest

### ISSUE THREAD

**Issue by kommen** [syl20bnr/spacemacs#13357]
#### Description :octocat:
`magit-status` fails on Emacs 27.0.90 pretest

#### Reproduction guide :beetle:
- Start Emacs
- `SPC g s`

*Observed behaviour:* :eyes: :broken_heart:
```(wrong-type-argument stringp evil-mc-enable-bar-cursor)```

*Expected behaviour:* :heart: :smile:
magit status opens

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d17c6e1e9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv elixir scheme javascript html org
     (clojure :variables clojure-enable-linters 'clj-kondo clojure-enable-clj-refactor t)
     helm auto-completion emacs-lisp git osx markdown multiple-cursors syntax-checking version-control yaml github)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS PDUMPER

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument stringp evil-mc-enable-bar-cursor)
  string-match("\\(\\`\\|/\\)sendmail\\(\\.elc\\|\\.el\\|\\.so\\)?\\(\\.gz\\)?\\'" evil-mc-enable-bar-cursor)
  load-history-filename-element("\\(\\`\\|/\\)sendmail\\(\\.elc\\|\\.el\\|\\.so\\)?\\(\\.gz\\)?\\'")
  eval-after-load("sendmail" #f(compiled-function () #<bytecode 0x1ffcedf57835>))
  byte-code("\300\301\302\"\210\303\304!\207" [eval-after-load "sendmail" #f(compiled-function () #<bytecode 0x1ffcedf57835>) provide mailabbrev] 3)
  #<subr require>(mailabbrev)
  apply(#<subr require> mailabbrev)
  require(mailabbrev)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\300\313!\210\300\314!\210\300\315..." [require cl-lib mailheader gmm-utils mail-utils mailabbrev mail-parse mml rfc822 format-spec dired mm-util rfc2047 puny rmc autoload mailclient-send-it "mailclient" custom-declare-group message ((user-mail-address custom-variable) (user-full-name custom-variable)) "Mail and news message composing." :link (custom-manual "(message)Top") :group mail news message-various nil "Various Message Variables." (custom-manual "(message)Various Message Variables") message-buffers "Message Buffers." (custom-manual "(message)Message Buffers") message-sending "Message Sending." (custom-manual "(message)Sending Variables") message-interface "Message Interface." (custom-manual "(message)Interface") message-forwarding "Message Forwarding." (custom-manual "(message)Forwarding") message-insertion "Message Insertion." (custom-manual "(message)Insertion") message-headers "Message Headers." (custom-manual "(message)Message Headers") message-news ...] 14)
  #<subr require>(message)
  apply(#<subr require> message)
  require(message)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\305\306\307\310\311\312\311\313\314\315\316\317&\13\207" [require add-log pcvs-util ring message custom-declare-group log-edit nil "Major mode for editing RCS and CVS commit messages..." :group pcl-cvs vc :version "21.1" :prefix "log-edit-"] 12)
  #<subr require>(log-edit)
  apply(#<subr require> log-edit)
  require(log-edit)
  byte-code("\300\301!\210\300\302!\210\300\303\304\305#\210\300\306\304\305#\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\313\314\304\315\316\317\320\321\322\323&\11\210\324..." [require dash log-edit magit-git nil t magit-utils ring server transient with-editor custom-declare-group git-commit "Edit Git commit messages." :prefix "git-commit-" :link (info-link "(magit)Editing Commit Messages") :group tools custom-declare-variable global-git-commit-mode funcall function #f(compiled-function () #<bytecode 0x1ffcede8de15>) "Non-nil if Global Git-Commit mode is enabled.\nSee ..." :set custom-set-minor-mode :initialize #f(compiled-function (symbol exp) #<bytecode 0x1ffcede8de2d>) :type boolean] 12)
  #<subr require>(git-commit)
  apply(#<subr require> git-commit)
  require(git-commit)
  eval-buffer(#<buffer  *load*-343595> nil "/Users/kommen/.emacs.d/elpa/27.0/develop/magit-202..." nil t)  ; Reading at buffer position 2098
  load-with-code-conversion("/Users/kommen/.emacs.d/elpa/27.0/develop/magit-202..." "/Users/kommen/.emacs.d/elpa/27.0/develop/magit-202..." nil t)
  #<subr require>(magit)
  apply(#<subr require> magit)
  require(magit)
  eval-buffer(#<buffer  *load*> nil "/Users/kommen/.emacs.d/elpa/27.0/develop/magit-202..." nil t)  ; Reading at buffer position 1102
  load-with-code-conversion("/Users/kommen/.emacs.d/elpa/27.0/develop/magit-202..." "/Users/kommen/.emacs.d/elpa/27.0/develop/magit-202..." nil t)
  autoload-do-load((autoload "magit-status" "Show the status of the current Git repository in a..." t nil) magit-status)
  command-execute(magit-status)
```

**Comment by duianto** [comment]
I'm not getting any errors when I call `magit-status` in either:
GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
GNU Emacs 27.0.90 (build 1, x86_64-w64-mingw32) of 2020-03-01

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2049817b1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP

</pre>
</details>

From the first two lines of the backtrace:
>Debugger entered--Lisp error: (wrong-type-argument stringp evil-mc-enable-bar-cursor)
  string-match("\\(\\`\\|/\\)sendmail\\(\\.elc\\|\\.el\\|\\.so\\)?\\(\\.gz\\)?\\'" evil-mc-enable-bar-cursor)

It seems like you've got the `evil-mc-enable-bar-cursor` symbol somewhere where it expects a string.

The only place I'm finding an entry for `sendmail` is in the notmuch layers readme:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+email/notmuch/README.org#sending-emails-with-msmtp

**Comment by kommen** [comment]
Thanks for your feedback @duianto. I wouldn't know why I'm seeing this and you not. I tried to follow down the stacktrace, but to no avail. I guess I'll then just wait with upgrading to Emacs 27...

**Comment by duianto** [comment]
If you haven't tried it already. Backup your current setup and clone a fresh copy, without your current configurations, you can copy them over afterwards, if everything works.

**Comment by kommen** [comment]
Tried again today, updated all packages and now the error disappeared.

**Comment by sidraval** [comment]
I'm getting this same error. If I re-install magit, it works just fine until I quit emacs. Next time I open it, I see the error again as.

**Comment by duianto** [comment]
@sidraval I'm not seeing any errors on the latest `develop` branch with updated packages, when opening a magit-status buffer.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ac3c3546a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey emacs-lisp
            (erlang :variables erlang-enable-lsp-mode t)
            git ivy javascript lsp multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/")
                 org-enable-jira-support t org-enable-roam-support t)
            python rust shell spell-checking syntax-checking version-control treemacs yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

Could you include your system info, press `SPC h d s` to copy your system info to your clipboard,

**Comment by sidraval** [comment]
@duianto Sure, here's the output:

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 76849892e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html csv sql lsp osx yaml markdown emacs-lisp
      (ruby :variables ruby-test-runner 'rspec)
      (javascript :variables javascript-fmt-tool 'prettier javascript-fmt-on-save t)
      git
      (helm :variables helm-grep-ignored-directories
            '("node_modules/" ".git/"))
      (typescript :variables typescript-fmt-tool 'prettier typescript-backend 'lsp typescript-fmt-on-save t)
      react auto-completion themes-megapack multiple-cursors syntax-checking
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      treemacs)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER

**Comment by duianto** [comment]
Does the messages buffer (`SPC b m`) show any other errors?

If not, then to exclude any of your configurations.

Clone a fresh copy of Spacemacs to the develop branch.

Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

After the Spacemacs setup and package installations.
Add the `git` layer which installs `magit`.
Restart Spacemacs, and try to reproduce the issue.

If everything works, then add back your configurations.

if it breaks again, then remove your configurations, and add back half, then half of the remaining half, and so on until you find the issue.

**Comment by sidraval** [comment]
Just tried this again with a fresh install of spacemacs on the develop branch, and it breaks as soon as I add the `git` layer to the default `.spacemacs` file. You can see the exact `.spacemacs` file [here](https://gist.github.com/sidraval/72ccdaf05ebf54ce7fc75eba2c335daa).

The exact error is`load-history-filename-element: Wrong type argument: stringp, evil-mc-enable-bar-cursor` and I see no other errors in the messages buffer.

I'm running the following version of emacs:
<img width="396" alt="Screen Shot 2020-11-21 at 3 25 16 PM" src="https://user-images.githubusercontent.com/3432639/99886992-b30bee80-2c0e-11eb-9f8e-c7820e0147f3.png">

**Comment by lebensterben** [comment]
@sidraval have you updated all packages?

**Comment by sidraval** [comment]
@lebensterben Yes I have

**Comment by duianto** [comment]
I don't have a Mac to test with, but I'm still not seeing that error message about `evil-mc-enable-bar-cursor` in either Linux or Windows. After cloning to the `develop` branch and adding the `git` layer.

<details><summary>
Manjaro, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 77d84b14e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

</pre>
</details>

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 77d84b14e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP
</pre>
</details>

**Comment by sidraval** [comment]
I was able to fix this bug, but it's a very opaque solution... Ultimately, this issue solved my problems: https://github.com/termux/termux-packages/issues/423

To summarize:
- Commenting out the line `(setq current-load-list nil)` in `loadup.el` fixes the problem
- I installed emacs via https://emacsformacosx.com/
- My `loadup.el` file's location is: `/Applications/Emacs.app/Contents/Resources/lisp/loadup.el`

**Comment by lebensterben** [comment]
This deserves to be reported upstream

**Comment by emacs18** [comment]
I use emacs from https://github.com/railwaycat/homebrew-emacsmacport

Could this be a problem with emacs build from https://emacsformacosx.com?
