### ISSUE TITLE
add kubernetes tramp to kubernetes layer

### ISSUE THREAD

**Issue by impca** [syl20bnr/spacemacs#13367]
There is a new layer in develop branch - spacemacs/layers/+tools/kubernetes/ which adds kubernetes-el.

Would it be possible to also add support for Kubernetes Tramp https://github.com/gruggiero/kubernetes-tramp - just like the Docker layer adds support for Docker in Tramp?

**Comment by smile13241324** [comment]
@impca sure however I have just checked the docs for kubernetes.el and it should already include executing into a containers context.

Can you double check whether this work like tramp would or does tramp have a different api? Sorry for my noob questions but I have never worked with tramp and I would like to avoid introducing a duplicate feature.

[docs](https://github.com/chrisbarrett/kubernetes-el#kubernetes-el)

**Comment by impca** [comment]
Yes, indeed it does, it provides the "magit-style" interface, where you can see an overview of all running pods in a namespace, examine them, exec into etc... What is missing is the Tramp integration. 

Let me explain. 

When you search for a file to open (SPC f f), instead of typing path to a file, you can type `/ssh:hostname:/path/to/remote/file.txt` and Tramp will open and edit a file on a remote server.

When you install the Docker layer and search for a file to open ( SPC f f), you can type `/docker:` and you will be presented with a list of ids of running containers and you can open a file in a container - so the entire path will look like `/docker:CONTAINER_ID:/path/to/file.txt`

So, similarly, when you install Kubernetes layer, you should be able to search for a file to open (SPC f f) and then type `/kubectl:` and get a list of pods in the current namespace and the ability to access a file in one of those pods ( so the entire path will look like `/kubectl:container:/path/to/file.txt`). This is the part that is missing.

**Comment by smile13241324** [comment]
Sounds like a great feature, I'll integrate it.
Thanks for the long explanation by the way.

I will have to have a look at tramp thesedays. I am working like 90% of my
time in a kubernetes context anyway but till now I have kept my shell
separate yet. Time to replace it with spacemacs.

**Comment by smile13241324** [comment]
@impca I have integrated the package into the kubernetes layer as described on the project page. Can you double check and if it works close this ticket?

**Comment by impca** [comment]
Well, I guess it works, because I can see the list of running pods when I open a new file.

However, Tramp seems to hang as soon as I select a pod - so all I see is `/kubectl:POD_NAME:` ). But that is probably a problem with the kubernetes-tramp.el, I see he has some issues there with similar problems still open.

**Comment by smile13241324** [comment]
As to @impca comment this one should be solved.
