### ISSUE TITLE
ess module not working

### ISSUE THREAD

**Issue by roryk** [syl20bnr/spacemacs#1337]
I add it to to the layers and SPC-e-s-s seems to do something, but when I try to run any of the commands with SPC-m-whatever, it says SPC-m isn't defined. @michelk do you know what might be going on?

Thanks!

**Comment by roryk** [comment]
Hm, got it working now. Weird.

**Comment by michelk** [comment]
ESS setup is currently not ideal.

You still have to run `M-x R-mode` manually.

**Comment by roryk** [comment]
Thanks @michelk, that was it.
