### ISSUE TITLE
/ or ? + up or down keys for recalling previous words or expression used for search are not working

### ISSUE THREAD

**Issue by amlanguedoc** [syl20bnr/spacemacs#13379]
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>

emacs 26.3 using linux Manjaro last release

Using a nomal search evil procedure

/anywhere or ?anywhere it works

If I try to recall such as 

/   up keys or down key to recall the history or searches it doest not work.

In place spacemacs do up and down lines in the editing windows.

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

As described above

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

Should do as vim or neovim

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(markdown python ivy auto-completion emacs-lisp python c-c   rust java)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by jr0cket** [comment]
Cannot reproduce this issue in Spacemacs `develop` - commit 884afe138
The up and down arrows do navigate through the history of a `/` search.

* Distribution: spacemacs
* Editig style: vim
* Completion: helm  

Suggest its either an issue with Ivy or an issue only fixed in `develop`

**Comment by amlanguedoc** [comment]
Thanks for your help.
Do not work also with helm with standard spacemacs distribution and emacs 26.3
Problem not linked to ivy

Did try develop version with helm and ivy (2 clean installs) with emacs 26.3..dot not work
I intend to try emacs 25.2 and I will try with a different linux distrib.also.

**Comment by amlanguedoc** [comment]
Woks with  emacs 26.3 using linux Manjaro last release
Using a nomal search evil procedure and recalling previous search.
I did install develop version of spacemacs, Works with helm (did not test with ivy)

git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d

evil version is evil-20200304.1421

I did a test using emacs -Q and evaluate buffer with

;; Set up package.el to work with MELPA
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)

;; Download Evil
(unless (package-installed-p 'evil)
  (package-install 'evil))

;; Enable Evil
(require 'evil)
(evil-mode 1)

Do NOT work
evil version is evil-20200304.1421

**Comment by lebensterben** [comment]
Not reproducible here.
Feel free to reopen this if it still persist.
