### ISSUE TITLE
How do I customize auto-complete colours?

### ISSUE THREAD

**Issue by ChrisMGeo** [syl20bnr/spacemacs#13378]
Hi, I'm getting started with spacemacs, and am loving it so far! I use the Soothe theme and it looks great, but the auto-complete looks weird (its a bright yellow background with bright red text). How do I customize the auto complete's colours? I tried searching for auto-complete in customize-group, but couldn't find it specifically. I did find something like auto-insert, is this related to changing the colours? Also is it possible to do this within `.spacemacs` file, instead of the commands.

EDIT: Ok I realized that this is some other auto-complete called company. But I would still like to know how to customize auto-complete unless I'm severely misguided (Sorry).

**Comment by jr0cket** [comment]
One approach is to use the Emacs customize wizard
`SPC SPC customize` and search for Ac Candidate Face.

**Comment by ChrisMGeo** [comment]
I'm sorry but ac candidate doesn't show when I search for it

**Comment by duianto** [comment]
These are the Auto Complete faces that are modified by the: Soothe theme
https://github.com/emacsfodder/emacs-soothe-theme/blob/0786fe70c6c1b4ddcfb932fdc6862b9611cfc09b/soothe-theme.el#L220

This seems to be the colors that the auto-complete package suggests can be modified:
https://github.com/auto-complete/auto-complete/blob/2e83566ddfa758c69afe50b8a1c62a66f47471e3/doc/manual.md#change-colors

The default spacemacs-dark theme seems to only modify one auto complete face:
https://github.com/nashamri/spacemacs-theme/blob/fd394ac0a5f562edfe3582d70124de9faf22d4d5/spacemacs-common.el#L222

This thread might also be helpful:
https://stackoverflow.com/questions/27474936/color-schema-of-emacs-auto-complete-mode
