### ISSUE TITLE
Treemacs does not follow Layout Change

### ISSUE THREAD

**Issue by rsobik** [syl20bnr/spacemacs#13388]
#### Description :octocat:
Treemacs does not follow Layout Change and instead edits the current Treemacs Workspace

#### Reproduction guide :beetle:
- Start Emacs
- Enable Treemacs
- Configure two Treemacs Workspaces with paths A and B
- Configure two Layouts: One for each Treemacs workspace 

*Observed behaviour:* :eyes: :broken_heart:
When changing from layout A to layout B, the path from layout A is added to Treemacs Workspace B

*Expected behaviour:* :heart: :smile:
When changing from layout A to layout B, Treemacs should reconfigure for Workspace B

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 83fbc7a13)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(json
 (python :variables python-backend 'lsp python-formatter 'lsp)
 yaml vimscript markdown kubernetes lsp helm
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 emacs-lisp
 (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t treemacs-use-git-mode 'deferred)
 (org :variables org-projectile-file "TODOs.org" org-want-todo-bindings t)
 git version-control templates helpful
 (osx :variables osx-option-as 'none osx-right-option-as 'meta)
 syntax-checking shell)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by rsobik** [comment]
Given some guidance and help I would like to apply the necessary changes myself and create a PR for that. But bear in mind that I'm new to Elisp, Emacs and Spacemacs

**Comment by nixmaniack** [comment]
@rsobik If you can follow through the conversation here https://github.com/Alexander-Miller/treemacs/issues/592, you should, hopefully, find the solution at the end of the thread.

**Comment by rsobik** [comment]
@nixmaniack Thanks very much for that hin!. I've added `(with-eval-after-load 'treemacs (treemacs-set-scope-type 'Perspectives))` to `dotspacemacs/user-config` and removed all automatically added projects form my Treemacs workspaces.
