### ISSUE TITLE
spacemacs in wsl2 can't open links in windows browser while the default Emacs (using `emacs -Q`) can

### ISSUE THREAD

**Issue by Zxrcoming** [syl20bnr/spacemacs#13382]
![image](https://user-images.githubusercontent.com/50140264/76728633-42b0f180-6792-11ea-99ae-c969c24127c3.png)
> As we can see above is a link in spacemacs, and I am in graphcal version of spacemacs, when I click or simple hit RET, link can't open
> But in terminal-based spacemacs, it just work like a charm

here is the code I using for open links in wsl2 version of spacemacs
the code is put in the `.spacemacs` , in the `dotspacemacs/user-init()` session
![image](https://user-images.githubusercontent.com/50140264/76728821-b521d180-6792-11ea-9d5f-3ecb4299127d.png)

and using `emacs -Q' 
> the open link works like a charm

I think it's a problem of spacemacs config, not the X410 because the default emacs (using `emacs -Q`) simply work out,

but I am not sure, the only thing I changed from the `.spacemacs` and `.emacs.d` is the above code

*Also the x-server I use is the x410 downloaded from Micosoft Store*

**Comment by Zxrcoming** [comment]
well, 'git clone' again just solved it. 😂

**Comment by HanshenWang** [comment]
I have the exact same problem as you and running 
...
$ emacs26 -nw
...
has browse-url-generic working correctly. Can you please clarify what did you meant by updating the .spacemacs.env file? I've already tried spacemacs/force-init-spacemacs-env (SPC f e C-e) with no avail. I am on develop branch. Would be overjoyed if someone could shed some light on this.

**Comment by enriched** [comment]
@HanshenWang were you ever able to get an answer?

**Comment by HanshenWang** [comment]
@enriched 
> 
> 
> @HanshenWang were you ever able to get an answer?

Unfortunately no. I was able to set the WSL_INTEROP to the proper internal IP address and launch explorer.exe and win10 firefox through emacs ansi-term (and v term). 

I was also able to install the wolfram engine for developers onto my wsl2 ubuntu and successfully point the emacs-jupyter package to the wolfram kernel by editing my spacemacs .env file. So I know my .env file works and that the WSL2 interop (apparently) works. 

I'm not a programmer and I've pretty much exhausted all my google-fu. For now, I've resigned myself to install firefox inside my wsl2 ubuntu. It really is only useful for viewing html mail inside mu4e.

Let me know if you or somebody else manages to find a solution!

Cheers,

**Comment by HanshenWang** [comment]
My issue (and maybe yours) is most similar to https://github.com/microsoft/WSL/issues/6170 and https://github.com/Microsoft/WSL/issues/3806. 

There doesn't seem to be an easy solution as of now.

**Comment by enriched** [comment]
@HanshenWang don't know if you found the solution to this, but for me this was an issue with the WSL_INTEROP environment variable. It had been set in my `.spacemacs.env` and needed to come from the environment of the terminal.

I found the hint through [this medium article](https://elecming.medium.com/the-ultimate-emacs-hacking-tutorial-in-windows-10-wsl-2-cfd3ea3893e3).

**Comment by HanshenWang** [comment]
@enriched Thanks for the tip! I now get what the O.P. meant by updating the
.spacemacs.env. It turned out I had your snippet above in my .bashrc, but
"spacemacs//init-spacemacs-env" mangles it slightly when creating the
.spacemacs.env. After removing "spacemacs/load-spacemacs-env" and installing the
MELPA package "exec-path-from-shell" as suggested in the .spacemacs.env header,
"browse-url-generic" now works as in the original post! Many thanks!

Mu4e users will want to redefine "mu4e-action-view-in-browser" as well.

``` emacs-lisp

(defun mu4e-action-view-in-browser (msg)
    (browse-url (concat "file://///wsl$/Ubuntu" (mu4e~write-body-to-html msg))))

```
