### ISSUE TITLE
Unable to resolve link on org export for code block result

### ISSUE THREAD

**Issue by srgkoshelev** [syl20bnr/spacemacs#13387]
#### Description :octocat:
Unable to resolve link on org export (connected to #8054?).
The issue occurs for code block results that have been named (see below for example). The link works within org.

#### Reproduction guide :beetle:
- Start Emacs
- Create file:
```
#+begin_src python :results table
  return [[1,2,3],[4,5,6]]
#+end_src

#+NAME: Result
#+RESULTS:
| 1 | 2 | 3 |
| 4 | 5 | 6 |

Here is the link to calculation result: [[Result]].
Yet link within the org mode works.
```
- Export (e.g. `, e e h o`)

*Observed behaviour:* :eyes: :broken_heart:
```
org-babel-exp process python at position 1...
Can’t guess python-indent-offset, using defaults: 4
user-error: Unable to resolve link: "Result"
```
Same issue happens on Mac.

*Expected behaviour:* :heart: :smile:
Link is properly linked.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 710aa947b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html finance helm emacs-lisp git org spell-checking syntax-checking python latex)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

**Comment by duianto** [comment]
Confirmed.

>org-babel-exp process python at position 1...
Can’t guess python-indent-offset, using defaults: 4
Importmagic and/or epc not found. importmagic.el will not be working.
user-error: Unable to resolve link: "Result"

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d7868dae2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey clojure command-log common-lisp emacs-lisp ess git helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by Gahamelas** [comment]
I have the same problem when exporting an orgmode buffer that contains LINKS, and these do not exist anymore. Any way to solve this?

**Comment by iburunat** [comment]
Have you tried using ```
#+OPTIONS: broken-links:t to allow exporting with 'allegedly' broken links (org-export-with-broken-links)?

**Comment by srgkoshelev** [comment]
No, I haven't! I have tried and it works now.
Thank you for this workaround!

It doesn't seem to be the correct behavior, though, as the links are not broken, i.e. they exist, and lead to the position they should.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by iburunat** [comment]
Glad it did help! When you export it using `#+OPTIONS: broken-links:t`, do the links work (are they active) in the exported file?

**Comment by srgkoshelev** [comment]
I tried it with PDF export and all the links worked, i.e. were clickable and switched to the right table.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by iburunat** [comment]
Good to hear.

**Comment by lebensterben** [comment]
closing this for now.
For future references, you can try the workaround by @iburunat https://github.com/syl20bnr/spacemacs/issues/13387#issuecomment-632990368

**Comment by sunlin7** [comment]
Hi @srgkoshelev @duianto @AtomicNess123 ,

This issue also affect me, after investigation, it can be workaround by adding a `PROPERTY` before the `NAME`.

It can be considered as a known issue from upstream.

The doc for org Internat Link mentioned that it request a "CAPTION" with "NAME", https://orgmode.org/manual/Internal-Links.html#DOCF26,

>When targeting a ‘NAME’ keyword, the ‘CAPTION’ keyword is mandatory in order to get proper numbering (see Captions).

Adding a CAPTION before the NAME not work; while adding a 'PROPERTY' before the 'NAME' can get it work.

You can close this ticket, and submit the topic from upstream:

https://list.orgmode.org/orgmode/87ilpj9lv1.fsf@localhost/T/#t
