### ISSUE TITLE
How to decrease the excess padding on level 6 heading in org mode

### ISSUE THREAD

**Issue by dimitar-petrov** [syl20bnr/spacemacs#13396]
Hello,

Does anyone have an idea what did I do to increase the padding on heading 6
![image](https://user-images.githubusercontent.com/4025446/77220569-2e7e4300-6b4a-11ea-9078-877d87544a6e.png)

**Comment by duianto** [comment]
If you have any custom org settings, try disabling them.
Could you post your system info, `SPC h d s` copies the info to your clipboard.

This is what it looks like for me:

![VirtualBoxVM_2020-03-22_22-13-28](https://user-images.githubusercontent.com/13420573/77260992-807ab200-6c8b-11ea-8c86-32f84a71bce2.png)

 on the latest `develop` branch with updated packages in both of these OSs:

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d7868dae2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log common-lisp emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 python
                 (shell :variables shell-default-shell 'term shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>
 
<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d7868dae2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey clojure command-log common-lisp emacs-lisp ess git helm imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by dimitar-petrov** [comment]
I have many custom layers with settings, not sure how to track that specific setting though.

Here is my system info:
3397 ## System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bb8ec23ec)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust ruby systemd go nginx windows-scripts helm auto-completion better-defaults emacs-lisp
      (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t)
      tmux git markdown latex cscope
      (org :variables org-enable-hugo-support t org-reveal-note-key-char nil org-enable-reveal-js-support t org-reveal-title-slide "%t\n%d")
      speed-reading spell-checking syntax-checking csv php csharp django
      (python :variables python-test-runner 'pytest python-shell-prompt-detect-failure-warning nil pipenv-executable "/home/dpetrov/bin/custpipenv.sh")
      ipython-notebook html sql lua yaml javascript themes-megapack
      (mu4e :variables mu4e-enable-notifications t mu4e-enable-mode-line t)
      finance ansible
      (c-c++ :variables c-c++-enable-clang-support t)
      dp-main)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON LCMS2 GMP

**Comment by tko** [comment]
Could be theme dependent, different themes configuring header font sizes / margins differently?

**Comment by duianto** [comment]
@tko You might be right. 👍 
@dimitar-petrov Try another theme, I tested it with the default `spacemacs-dark` theme.

**Comment by dimitar-petrov** [comment]
@tko , right on the money

Switching to solarized removed the padding 
![image](https://user-images.githubusercontent.com/4025446/77793294-7c2b0c00-7072-11ea-95fc-a729700594fb.png)

How to track it in the specific theme?

**Comment by tko** [comment]
@dimitar-petrov presumably themes doing something about org headings would have something about `org-level-6` like [solarized](https://github.com/bbatsov/solarized-emacs/blob/8de268144ab2171896906c8553be7763d5c45fa5/solarized-faces.el#L1392-L1411) does -- or alternatively it might be the _lack_ of such theming that's causing this.
