### ISSUE TITLE
Race condition in pipenv.el fails to activate pyls/lsp/dap

### ISSUE THREAD

**Issue by senselessDev** [syl20bnr/spacemacs#13399]
#### Description :octocat:
If you open a python file in an pipenv for the first time of an emacs session, it fails to activate the environment and hence also the language server and so on. The python language server protocol implementation is only installed in the environment and hence `python-pipenv-activate t` in order to activate the environment first.

I traced the problem down to a kind of race condition in [pipenv.el](https://github.com/pwalsh/pipenv.el). Problem is the maintainer does not want to maintain anymore and hence I am trying my luck here to find a good solution first, hoping that with a nice PR he will merge and it will get fixed on elpa. 

The issue is basically coming from [here](https://github.com/pwalsh/pipenv.el/blob/b730bb509e8b60af9f5ab1f1e6c3458d1d95d789/pipenv.el#L341-L342). The call to the pipenv executable is done asynchronously and `python-shell-virtualenv-root` should be set in the second line due to the forced waiting on the previous first line (it is implemented via a callback mechanism (called filter here) for the asynchronous call of `make-process`). Unfortunately, the forced waiting is not working correctly. Hence, `python-shell-virtualenv-root` is `nil` as can be seen in the backtrace.
I suspect that the used `process-live-p` is not waiting for the callbacks (filter and sentinel) to finish which leads to this bug. There has been [some](https://github.com/pwalsh/pipenv.el/pull/17) [activity](https://github.com/pwalsh/pipenv.el/pull/44) over at pipenv.el but I think it is not solved yet.

A solution depends on ensuring that the filter and sentinel stuff is done with the `pipenv--force-wait `. Because I don't have any experience with lisp, let me know what the most elegant solution would be.

The following issues are probably related to the found problem:
- #12542
- #13101
- #12729

#### Reproduction guide :beetle:
- Start Emacs
- open python file where the lsp stuff is only installed in the environment given with the Pipfile

*Observed behaviour:* :eyes: :broken_heart:
- pyls does not start, `dap-debug` impossible

*Expected behaviour:* :heart: :smile:
- pyls starting automatically

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bb8ec23ec)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git
      (c-c++ :variables c-c++-enable-clang-support t)
      (latex :variables latex-enable-folding t latex-enable-auto-fill t)
      markdown lsp dap
      (python :variables python-pipenv-activate t)
      spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  directory-file-name(nil)
  pipenv-activate()
  (progn (pipenv-activate))
  (if python-pipenv-activate (progn (pipenv-activate)))
  spacemacs//python-setup-backend()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook python-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook python-mode-hook))
  run-mode-hooks(python-mode-hook)
  python-mode()
  set-auto-mode-0(python-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer GridStructure.py> "~/python/gridmap/GridStructure.py" nil nil "~/python/gridmap/GridStructure.py" (12457516 64769))
  find-file-noselect("~/python/gridmap/GridStructure.py" nil nil nil)
  find-file("~/python/gridmap/GridStructure.py")
  find-file-existing("~/python/gridmap/GridStructure.py")
  (lambda (&rest ignore) (find-file-existing "~/python/gridmap/GridStructure.py"))((push-button :args nil :value "~/python/gridmap/GridStructure.py" :action (lambda (&rest ignore) (find-file-existing "~/python/gridmap/GridStructure.py")) :mouse-face highlight :follow-link "\015" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay in no buffer> :from #<marker (moves after insertion) at 6357 in *spacemacs*> :to #<marker at 1 in *spacemacs*>) (mouse-1 (#<window 3 on *spacemacs*> 4275 (286 . 964) 88563815 nil 4275 (31 . 53) nil (7 . 10) (9 . 18))))
  widget-apply((push-button :args nil :value "~/python/gridmap/GridStructure.py" :action (lambda (&rest ignore) (find-file-existing "~/python/gridmap/GridStructure.py")) :mouse-face highlight :follow-link "\015" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay in no buffer> :from #<marker (moves after insertion) at 6357 in *spacemacs*> :to #<marker at 1 in *spacemacs*>) :action (mouse-1 (#<window 3 on *spacemacs*> 4275 (286 . 964) 88563815 nil 4275 (31 . 53) nil (7 . 10) (9 . 18))))
  widget-apply-action((push-button :args nil :value "~/python/gridmap/GridStructure.py" :action (lambda (&rest ignore) (find-file-existing "~/python/gridmap/GridStructure.py")) :mouse-face highlight :follow-link "\015" :button-prefix "" :button-suffix "" :format "%[%t%]" :button-overlay #<overlay in no buffer> :from #<marker (moves after insertion) at 6357 in *spacemacs*> :to #<marker at 1 in *spacemacs*>) (mouse-1 (#<window 3 on *spacemacs*> 4275 (286 . 964) 88563815 nil 4275 (31 . 53) nil (7 . 10) (9 . 18))))
  widget-button-click((mouse-1 (#<window 3 on *spacemacs*> 4275 (286 . 964) 88563815 nil 4275 (31 . 53) nil (7 . 10) (9 . 18))))
  funcall-interactively(widget-button-click (mouse-1 (#<window 3 on *spacemacs*> 4275 (286 . 964) 88563815 nil 4275 (31 . 53) nil (7 . 10) (9 . 18))))
  call-interactively(widget-button-click nil nil)
  command-execute(widget-button-click)

```

**Comment by lebensterben** [comment]
@senselessDev please try `pyenv.el`.
