### ISSUE TITLE
Unable to use org-export-to-html

### ISSUE THREAD

**Issue by samuelboland** [syl20bnr/spacemacs#13406]
#### Description :octocat:
Unable to use org-export-to-html. Receive error: 

helm-M-x: Symbol’s function definition is void: org-strip-quotes
#### Reproduction guide :beetle:
- Start Emacs
- Open org-mode file
- Attempt to export to HTML

*Observed behaviour:* :eyes: :broken_heart:
- Receive error message stated above. 

*Expected behaviour:* :heart: :smile:
- Export works and new HTML file is created at specified location

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql javascript yaml ruby html helm auto-completion better-defaults emacs-lisp git markdown
     (org :variables org-enable-bootstrap-support t)
     ruby-on-rails themes-megapack spell-checking syntax-checking)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by samuelboland** [comment]
It appears that this was due to me upgrading Emacs. At some point since my last update, the `org-strip-quotes` was removed. I have added that function back in to my personal functions file that I load at startup.  I used the function as defined here: 

https://github.com/bzg/org-mode/blob/master/lisp/org-macs.el#L900


Other issues are presenting themselves with missing functions. I assume that this was due to me upgrading my installation via homebrew. I'm not certain what the root cause of the issue is. Perhaps it's something wrong with my configuration or on my system specifically. I will keep this issue open, just in case this is something that requires fixing at the spacemacs level. It may not though. I'm new to the emacs space, and I don't yet have a good feel for where issues lie.

**Comment by duianto** [comment]
Make sure that you've updated the packages by pressing the `[Update Packages]` button on the  Spacemacs home buffer (`SPC b h`).


Exporting `, e e h h` this simple `.org` file:
```org
* abc
def
* ghi
jkl
```
doesn't show any errors for me, on either the `master` or `develop` branch.
`M-x org-version` shows:
>Org mode version 9.3.6 (9.3.6-25-g685b2c-elpaplus @ c:/Users/username/.emacs.d/elpa/26.3/org-plus-contrib-20200316/)


<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3) and develop (rev. b5f0eb5f7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git helm html imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>
