### ISSUE TITLE
`undo-tree-mode` is disabled by default in Coq files

### ISSUE THREAD

**Issue by kindaro** [syl20bnr/spacemacs#13407]
#### Description :octocat:
`undo-tree-mode` is disabled by default in Coq files.

#### Reproduction guide :beetle:
- Make sure:
  * The Coq layer is available.
  * The `undo-tree` package is available.
- Start Emacs.
- Open a text file.
  * Run `undo-tree-visualize` _(`SPC a u`)_.
  * Observe undo tree working normally.
- Open a Coq source file.
  * Run `undo-tree-visualize` _(`SPC a u`)_.
  * Observe error: `Undo-tree mode not enabled in buffer`.

*Observed behaviour:* :eyes: :broken_heart:

Error: `Undo-tree mode not enabled in buffer`.

*Expected behaviour:* :heart: :smile:

  Undo tree working normally.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c50d0a8d2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp
      (keyboard-layout :variables kl-layout 'bepo)
      coq)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
Confirmed.

It seems to be on purpose, because: `C-h l` (l = lowercase L) shows that `u` calls:
` u [pg-protected-undo]`

The repository: https://github.com/ProofGeneral/PG
remaps `undo` to `pg-protected-undo` here:
https://github.com/ProofGeneral/PG/search?q=pg-protected-undo&unscoped_q=pg-protected-undo

**Comment by kindaro** [comment]
Turns out there is an open issue in the Proof General repository that discusses this: ProofGeneral/PG#430

**Comment by kindaro** [comment]
This issue is still valid! And I still have not learned enough about Emacs's internals to fix it myself!
