### ISSUE TITLE
spacelpa authenticity can't be verified

### ISSUE THREAD

**Issue by Invertisment** [syl20bnr/spacemacs#13400]
#### Description :octocat:
Spacemacs cannot verify the authenticity of the stable ELPA archive (spacelpa).

#### Reproduction guide :beetle:
- Start Emacs.
- Update triggers spacelpa ELPA archive check.
- The message appears.

Additional:
- Installed a new system (manjaro linux).
- Put my own old `.spacemacs` config into `$HOME`.
- Checked out develop branch of spacemacs to `~/.emacs.d/`.
- Started emacs from app launcher.
I also ran a diff and there is this variable that may be useful to resolve the issue:
`dotspacemacs-use-spacelpa t`

*Observed behaviour:* :eyes: :broken_heart:
Verifying spacelpa archive shows a message that `spacelpa` authenticity can't be verified.
It was strange that this message appeared once.
But I pressed `No` and after a restart the message is still there.
It's either that I'm getting haxxed or spacemacs needs a patch.

*Expected behaviour:* :heart: :smile:
No messages, no security issues.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d7868dae2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python ruby typescript html csv yaml markdown
        (go :variables go-use-golangci-lint t go-format-before-save t gofmt-command "goimports" go-tab-width 2)
        lsp
        (clojure :variables clojure-enable-clj-refactor t)
        react javascript c-c++ rust java emacs-lisp helm multiple-cursors)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

A screenshot of what I see:
![Screenshot at 2020-03-22 12-14-32](https://user-images.githubusercontent.com/1641263/77247285-3b796000-6c38-11ea-89aa-1f60a5911775.png)

**Comment by duianto** [comment]
This error message is mentioned in this issue:
Beta testing of spacelpa ELPA repository on various OS distributions #12652

It's better to keep the reports in one thread.
Please post a comment over there, about what your seeing.
