### ISSUE TITLE
improve <ESC>

### ISSUE THREAD

**Issue by edwintorok** [syl20bnr/spacemacs#1340]
I found this useful (from a Vim perspective) to get back to normal mode in more buffers (like customize), but of course `fd` does more than this (it actually closes unwanted buffers). I'm not sure whether it'd have any unintended consequences:
```
(global-set-key [escape]
     (lambda ()
        (interactive) (progn (keyboard-escape-quit)(evil-normal-state))))
```

Somewhat related to https://github.com/syl20bnr/spacemacs/issues/1013

**Comment by edwintorok** [comment]
Regarding https://github.com/syl20bnr/spacemacs/issues/1341 it would be good to find a way to make ESC work in terminal mode to escape from emacs-state (that is entered with C-z), but evil mode does some manipulation of the terminal escape code when it is turned on and reverts it when its off, so not sure if possible.

**Comment by syl20bnr** [comment]
There is an opened issue in `evil-escape` repo to make ESC behaves like `fd`. I had not the time to look into it but `evil-escape` has not been designed for this kind of feature so it may be on trivial to achieve.

**Comment by TheBB** [comment]
The issue referred to by @syl20bnr (https://github.com/syl20bnr/evil-escape/issues/12) is closed, so I'm closing this.
