### ISSUE TITLE
How to delay the showing of syntax checking tooltip?

### ISSUE THREAD

**Issue by zer09** [syl20bnr/spacemacs#13411]
Is there a way to delay the syntax check tooltips?

I tried setting the `flycheck-display-errors-delay` to `3` but with no avail. The tooltip still showing almost instantly.

**Comment by zer09** [comment]
It's a bit annoying, when you are not done typing and there is an error, the tooltip will spam, and sometimes will interfere with the autocomplete.

And it look like it will cause a little bit slowdown, because when your not done typing, it try to show the tooltip, so what you type will got a little bit delay.

![](https://i.imgur.com/so2VP9M.gif)

**Comment by zer09** [comment]
Ohh, I cant remember if I saw this before.

![Screenshot from 2020-03-26 17-10-28](https://user-images.githubusercontent.com/780780/77629962-4e1bce00-6f85-11ea-96c0-027163d59661.png)

**Comment by lebensterben** [comment]
Are you using LSP?

**Comment by zer09** [comment]
> Are you using LSP?

Yes, I am using LSP

**Comment by lebensterben** [comment]
@zer09 
I suggest you to ask about this in lsp-mode.
It's likely to be configurable.

**Comment by lebensterben** [comment]
@zer09 
It might not be caused by LSP.
try setting `flycheck-pos-tip-timeout` to a larger number.

**Comment by zer09** [comment]
Thank you, I will try it.
