### ISSUE TITLE
vls error in vue layer

### ISSUE THREAD

**Issue by sanklamm** [syl20bnr/spacemacs#13419]
#### Description :octocat:
The vue language server does not start. I get the following error.

```
Error: Cannot find module 'vscode-css-languageservice/lib/umd/data/browsers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/sean/.nvm/versions/node/v10.16.3/lib/node_modules/vue-language-server/dist/modes/style/stylus/css-browser-data.js:7:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
internal/modules/cjs/loader.js:638
    throw err;
```

I followed the installation instructions in the vue layer beforehand.
After I got the error I installed the latest `vscode-css-languageservice` which didn't help.
I then installed `vscode-css-languageservice@4.0.2` which helped someone else but didn't help me.

#### Reproduction guide :beetle:
- Start Emacs
- add vue layer with setting the variable to add vls backend
- install the suggested npm packaged
- restart Emacs
- open `*.vue` file

*Observed behaviour:* :eyes: :broken_heart:
- vls tries to start but throws an error

*Expected behaviour:* :heart: :smile:
- vls starts without error

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f03392573)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence
                  (kbd "jk")
                  auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t :disabled-for org markdown)
 better-defaults c-c++
 (clojure :variables clojure-enable-fancify-symbols t)
 colors csv deft django docker emacs-lisp
 (git :variables git-magit-status-fullscreen t magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all)
 graphviz gtags helm helpful html
 (javascript :variables javascript-backend 'nil)
 json lsp bibtex
 (latex :variables latex-build-command "LaTeX")
 lua markdown
 multiple-cursors
 (org :variables org-enable-github-support t org-reveal-root "file:///Users/s/github_packages/reveal.js/js/reveal.js" org-reveal-mathjax t org-enable-bootstrap-support t org-enable-reveal-js-support t org-enable-hugo-support t org-enable-org-journal-support t org-projectile-file "TODOs.org")
 org-roam parinfer pdf php
 (python :variables python-test-runner 'pytest)
 react restructuredtext scheme semantic
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts
 (spell-checking :variables spell-checking-enable-by-default nil)
 sphinx sql syntax-checking themes-megapack treemacs typography
 (version-control :variables version-control-diff-side 'left version-control-global-margin t)
 (vue :variables vue-backend 'lsp)
 windows-scripts xkcd yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by thanhvg** [comment]
It's likely an issue with `vetur` install rather than the layer. When I ran `vls` in terminal I got the same error as yours. I suggest checking out their project https://github.com/vuejs/vetur. Or do downgrade vetur to previous version. 

When I did vue I used dumb backend.

**Comment by sanklamm** [comment]
@thanhvg I'm not really sure what `vetur` has to do with it. Can you explain?
I tried to follow your suggestion and installed the official `VSCode` and several versions of `vetur` but it didn't help. Why do I need `vetur` in the first place?

**Comment by sanklamm** [comment]
ahh. I see. vetur provides not only a client but also the server. I will debug some more.

**Comment by sanklamm** [comment]
ok. I got it working. the additional installation of `npm install vls -g` did the trick. Thanks for the hint.
