### ISSUE TITLE
Unable to disable syntax-checking by default

### ISSUE THREAD

**Issue by zer09** [syl20bnr/spacemacs#13414]
#### Description :octocat:
Unable to disable syntax-checking by default.

#### Reproduction guide :beetle:
- Start Emacs
- Open Spacemacs dotfile ```SPC f e d```
- Add ```syntax-checking-enable-by-default nil``` to the ```syntax-checking```
- Restart Emacs
- Open project
- syntax-checking is still enabled

*Observed behaviour:* :eyes: :broken_heart:
The syntax-checking is still enabled even it was disabled in Spacemacs dotfile.

*Expected behaviour:* :heart: :smile:
The syntax-checking should be disabled by default.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b5f0eb5f7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml csv vimscript
      (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage nil)
      (colors)
      (git)
      (helm)
      (imenu-list)
      (lsp :variables lsp-navigation 'simple lsp-ui-doc-enable nil lsp-ui-sideline-enable nil)
      (multiple-cursors)
      (ranger :variables ranger-cleanup-eagerly t ranger-enter-with-minus t ranger-show-hidden t ranger-max-preview-size 1)
      (spell-checking :variables spell-checking-enable-by-default nil)
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      (shell :variables shell-default-shell 'shell)
      (theming)
      (version-control :variables version-control-diff-tool 'git-gutter+ version-control-diff-side 'left version-control-global-margin t)
      (emacs-lisp)
      (html :variables scss-enable-lsp t html-enable-lsp nil web-mode-markup-indent-offset 2 web-fmt-tool 'web-beautify)
      (javascript :variables js-basic-offset 2 js-indent-level 2 javascript-fmt-tool 'web-beautify javascript-backend 'lsp)
      (json :variables json-fmt-tool 'web-beautify)
      (rust :variables rust-backend 'lsp rust-indent-offset 2)
      (shell-scripts)
      (sql :variables sql-capitalize-keywords t sql-auto-indent nil)
      (typescript :variables typescript-indent-level 2 typescript-fmt-tool 'typescript-formatter typescript-backend 'lsp))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
It seems to be working for me with this simple python file: `print.py`
```python
print "text"
```
#### With the `syntax-checking` layer enable by default variable disabled
```elisp
(syntax-checking :variables syntax-checking-enable-by-default nil)
```
After restarting Spacemacs and opening: `print.py`
Then there's no syntax checking.
Pressing `SPC t s` shows:
>syntax-checking enabled.

And a red dot appears in the left margin, and the `print "text"` line has a red underlined.
When the cursor is on that line, then a popup appears, saying:
>Missing parentheses in call to 'print'. Did you mean print("text")?

The `flycheck-global-modes` variable shows:
>flycheck-global-modes’s value is nil

#### Without any `syntax-checking` layer variables
After restarting Spacemacs and opening: `print.py`
The red dot in the margin, red underline and missing parentheses popup message appears.
And Pressing `SPC t s` shows:
>syntax-checking disabled.

The `flycheck-global-modes` variable shows:
>flycheck-global-modes is a variable defined in ‘flycheck.el’.
Its value is
(json-mode web-mode slim-mode scss-mode sass-mode pug-mode less-mode haml-mode js2-mode python-mode)
Original value was t


<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b5f0eb5f7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git helm html imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by zer09** [comment]
Yes I tried it, and it works correctly, but once the file is already on projectile it will enable  the syntax checking automatically.

When I open the file it will ask for ```"file" is not part of any project. Select action```, when I select "Do nothing", syntax checking is not enabled, but when I select "Import project root" it enable the syntax checking automatically.

**Comment by duianto** [comment]
Ok, I think I've managed to reproduce the issue.

With the `lsp` layer installed.

When a `.py` file is opened, then a `mspyls` server is installed and started.

Now the buffer is being syntax checked, and the variable:
`syntax-checking-enable-by-default nil` doesn't seem to have any effect.

But the following seems to disable the lsp syntax checking in a `python-mode` buffer:
```elisp
  (defun custom/disable-lsp-diagnostics ()
    (setq-local lsp-diagnostic-package :none)
    (setq-local lsp-ui-doc-enable nil))

  (when (configuration-layer/layer-used-p 'lsp)
    (add-hook 'python-mode-hook 'custom/disable-lsp-diagnostics))
```

`(setq-local lsp-ui-doc-enable nil)` disables the popup that appears below the cursor when moving around.
