### ISSUE TITLE
Candidate list in helm-projectile-switch-to-buffer is not correct

### ISSUE THREAD

**Issue by jgracin** [syl20bnr/spacemacs#13415]
#### Description :octocat:
Buffer list provided by helm-projectile-switch-to-buffer is not correct

#### Reproduction guide :beetle:
- Start Emacs
- Open two files from the same (projectile) project
- Use helm-projectile-switch-to-buffer (SPC p b) to switch back and forth between the two buffers

*Observed behaviour:* :eyes: :broken_heart:
Easily reproducible. When trying to switch buffer using `SPC p b` (with only one
window), the candidate list of buffers often does not contain the other buffer.
When I close helm by C-g and try again, then the other buffer appears.

*Expected behaviour:* :heart: :smile:

Using `SPC p b` repeatedly should alternate between the last two buffers.

Here are some further observations.

Helm-mini works correctly. My helm-full-frame is set to t.

I did some debugging and I think this might have to do with
spacemacs/helm-find-buffers-windows and the way it performs switching of windows
which confuses the built-in function `buffer-list`. In the problematic scenario
`buffer-list` is returning a list of buffers in which the first buffer is not
the last open buffer and it should be.

A workaround (for me) is to not use spacemacs/helm-find-buffers-windows, i.e.
rebind RET in helm-buffer-map:
(define-key helm-buffer-map (kbd "RET") 'helm-maybe-exit-minibuffer)

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b5f0eb5f7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(terraform groovy typescript asciidoc latex docker csv html ruby javascript yaml
           (clojure :variables clojure-enable-clj-refactor t)
           helm auto-completion better-defaults emacs-lisp git markdown org
           (ibuffer :variables ibuffer-group-buffers-by 'projects)
           (shell :variables shell-default-height 30 shell-default-position 'bottom)
           spell-checking syntax-checking version-control)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP

**Comment by duianto** [comment]
Confirmed.

Pressing `RET` in the `SPC p b` HELM Projectile buffer doesn't seem to update the list of candidates until the second time `SPC p b` is pressed.


<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2d7480f67)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm html imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by duianto** [comment]
A solution to this specific issue of only opening the HELM Projectile buffer (`SPC p b`),
and pressing `RET` to choose the selected candidate.

Could be to count the `(helm-marked-candidates)`:

If there are less than `2` candidates:
call the `(helm-maybe-exit-minibuffer)` function.

Otherwise:
Use the current distribute buffers function.

But the underlying issue will remain for anyone that marks `2` or more buffers.
