### ISSUE TITLE
Keybindings broken in ccls-tree-mode

### ISSUE THREAD

**Issue by rihardsk** [syl20bnr/spacemacs#13417]
#### Description :octocat:
Keybindings are broken in ccls-tree-mode

#### Reproduction guide :beetle:
- Start Emacs
- Open a c++ project using the ccls lsp backend
- Open the call hierarchy tree with `SPC g h c` (`ccls-call-hierarchy`)
- Try pressing `TAB` on an item

*Observed behaviour:* :eyes: :broken_heart:
Emacs complains that the buffer is read-only because `TAB` is bound to `indent-for-tab-command`. As far as i can tell, none of the other keybindings defined by the `ccls-tree-mode` are bound either (e.g., `l` should be bound to `ccls-tree-expand-or-set-root` but it isn't).

*Expected behaviour:* :heart: :smile:
The item in the call hierarchy tree is expanded/collapsed (`ccls-tree-toggle-expand` should be called). Other keybindings should also work.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d7868dae2)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(perl5 javascript fsharp haskell systemd html html yaml markdown themes-megapack helm python elm csharp nixos terraform lsp
       (c-c++ :variables c-c++-adopt-subprojects t c-c++-default-mode-for-headers 'c++-mode c-c++-lsp-sem-highlight-rainbow t c-c++-backend 'lsp-ccls c-c++-lsp-executable
              (file-truename "~/src/ccls/Release/ccls"))
       cmake auto-completion emacs-lisp git docker
       (org :variables org-enable-github-support t org-enable-org-journal-support t org-journal-dir "~/org/journal/" org-journal-file-format "%Y-%m-%d" org-enable-reveal-js-support t)
       spacemacs-org
       (shell :variables shell-default-height 30 shell-default-position 'bottom)
       shell-scripts syntax-checking imenu-list gtags search-engine latex pandoc
       (spell-checking :variables spell-checking-enable-by-default nil))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by rihardsk** [comment]
fwiw i've found out that i can easily switch to Emacs mode with `Ctrl+Z` where the keybindings work so it's much less of an issue for me than initially. But would be nice to see a fix i guess.

**Comment by emacs18** [comment]
This may already be fixed via c3f13d03910e6ae55e5c617ce7c7bd9cb9861d70 checked in on Apr 2.
As I recall I too had similar problem of TAB not working and so having to hit C-z to switch to emacs mode at which point TAB worked.  Today TAB is bound to the correct command for both vim mode and emacs mode.

**Comment by emacs18** [comment]
Actually many things seem to be broken in ccls-tree mode in vim mode when things work much better in emacs mode.  I'm going to add the following in my startup file so that ccls-tree always come up in emacs mode:
```elisp
(evil-set-initial-state 'ccls-tree-mode 'emacs)
```
I find the following code in spacemacs today, i.e., similar code that is commented out:
```elisp
;;(evil-set-initial-state 'ccls--tree-mode 'emacs)
```
Perhaps spacemacs used emacs mode for ccls-tree-mode at some point, but gave that up at some point.  I have no idea why.

**Comment by emacs18** [comment]
I submitted https://github.com/syl20bnr/spacemacs/pull/13672 to make emacs mode the default mode.

**Comment by smile13241324** [comment]
Merged, please double check @rihardsk and close this issue if it works.

**Comment by rihardsk** [comment]
@emacs18, @smile13241324 it's working perfectly. Thanks!
