### ISSUE TITLE
Compiling with latexmk through Spacemacs doesn't work

### ISSUE THREAD

**Issue by liwoxa** [syl20bnr/spacemacs#13429]
#### Description :octocat:
Compiling with latexmk through Spacemacs doesn't work.
Running `latexmk -pdf temp.tex` from the terminal compiles correctly.
Running `latexmk -pdf temp.tex` from inside Spacemacs using [SPC !] does nothing and prints:
```
*** collate_byname<char>::collate_byname failed to construct for 
```

#### Reproduction guide :beetle:
- Start Emacs
- Open a latex file
- Compile it by pressing [, b]

*Observed behaviour:* :eyes: :broken_heart:
Get the error (:paw_prints:) below.

*Expected behaviour:* :heart: :smile:
Compile the latex document.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 72f280dc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: (adding `latex-build-command "LatexMk"` to `latex :variables` doesn't help)
```elisp
(ocaml agda helm auto-completion coq emacs-lisp
       (latex :variables latex-enable-auto-fill nil)
       markdown osx spell-checking)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\(?: \"\\\\\\|\"\\|%\\(?:(\\(?:\\(?:PDF\\(?:out\\)?\\|cntxcom\\|ex\\(?:\\(?:ec\\|tra\\)opts\\)\\|file-line-error\\|latex\\|mode\\|o\\(?:\\?\\|utpage\\)\\|tex\\))\\)\\|cS\\|dS\\|vv\\|[%'STV`abdfl-tv]\\)\\)" nil nil)
  TeX-command-expand(nil TeX-master-file)
  TeX-command("LatexMk" TeX-master-file -1)
  (progn (let ((TeX-save-query nil)) (TeX-save-document (TeX-master-file))) (TeX-command latex-build-command (quote TeX-master-file) -1))
  latex/build()
  funcall-interactively(latex/build)
  call-interactively(latex/build nil nil)
  command-execute(latex/build)

```

**Comment by duianto** [comment]
It seems to be working without any issues for me from:
- the Command prompt (cmd.exe)
- Spacemacs `SPC !` both with and without the `latex` layer installed.

With this example file `test.tex`:
http://mally.stanford.edu/~sr/computing/latex-example.html

The same number of files with the same sizes were created:
| size   | file             |
| ------ | ---------------- |
| 9      | test.aux         |
| 4,366  | test.fdb_latexmk |
| 4,154  | test.fls         |
| 5,003  | test.log         |
| 89,263 | test.pdf         |




All three `.pdf`s look the same.
Except that the lines between: CP, Spec, C', C and SAgrP
on the page above, are not shown when viewing the pdf in either:
sumatrapdf or google chrome.

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2ca55e28e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm html imenu-list
            (java :variables java-backend 'meghanda)
            javascript latex lsp
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by liwoxa** [comment]
Lately I've been getting only this error when `[, b]`uilding:

```
Running `LatexMk' on `sol' with ``latexmk -pdf --synctex=1 -interaction=nonstopmode  -file-line-error  sol.tex''
*** collate_byname<char>::collate_byname failed to construct for 

TeX Output exited abnormally with code 1 at Sat Apr  4 10:35:38
```
_Here I tried to compile a file `sol.tex`._

**Comment by liwoxa** [comment]
I anyone is stuck as I am, here's my workaround. I use `latexmk`'s watch mode (flag `-pvc`) in a separate terminal window:
```bash
$ latexmk -pdf -pvc -synctex=1 filename.tex
```
With this `[, v]`iewing still works.

**Comment by liwoxa** [comment]
> It seems to be working without any issues for me from:
> 
> * the Command prompt (cmd.exe)
> * Spacemacs `SPC !` both with and without the `latex` layer installed.

Thanks @duianto. I have no doubt this works fine for most people, but I would be surprised if I'm the _only one_ with this problem.

By the way, I have MiKTeX installed locally as a user without administrator privileges, perhaps this is related?

**Comment by duianto** [comment]
Building with `,b` also worked.
And `,v` opens sumatrapdf and shows the pdf as expected.

The installer `basic-miktex-2.9.7152-x64.exe` says in the Installation Scope section:
>If you are administrator, you have the option to set up MiKTeX for all users.

It shows two options:
- Install MiKTeX only for me (username)
- Install MiKTeX for anyone who uses this computer (all users)

The second option is grayed out, so I most likely installed it using the first option.

`latexmk.exe` is located in the directory:
`C:\Users\username\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64`

**Comment by liwoxa** [comment]
I figured out that launching Emacs via the terminal (e.g. `/usr/local/Cellar/emacs-plus@27/27.1/Emacs.app`) fixes this for me, probably a `$PATH` issue of some sort. Also, I guess this has nothing to do with Spacemacs in particular.

Thanks for the help!
