### ISSUE TITLE
Ruby layer - No autocompletion?

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#1342]
I'm trying to switch to Spacemacs for all my development now, as it looks awesome. However, when I'm developing Rails projects, I cannot seem to get auto-completion right. Pressing Tab (in `.rb` or `.haml` files) doesn't give me any autocompletion suggestion. Did I set something wrong?

Also, one nice functionality of RubyMine IDE is its support for autocompletion for I18n texts. For example, say I want to type         `= t("action_mailer.listing_contact_request_mailer.agent_response_to_requester_mail.sections.reply.buttons.reply")` in a HAML file, I'll only need to type parts of it like `t("action.lis.butto.reply")` to let the IDE fetch the complete name. That's a huge time saver because localizations file can have very deep nesting. Is there a similar functionality in Emacs packages yet?

Thanks!

**Comment by CarlQLange** [comment]
Did you switch on the `auto-completion` layer in your `.spacemacs`? :) Unfortunately I don't do any Rails so I can't help you further.

**Comment by tuhdo** [comment]
Have you started `robe` with `robe-start` bound to `SPC m s i`? Only then, `company-robe` should give you autocompletion.

**Comment by x-ji** [comment]
Thanks. So if I want auto completion when editing Ruby files, I'll have to run `robe-start`?

Though I guess there's currently still no out-of-the-box support for i18n autocompletion support?

Another issue I'm getting is that `enh-ruby-mode` seems to not recognize the correct Ruby interpreter at first launch. I use `rbenv` and I've set `ruby-version-manager 'rbenv` in `/init()` function. I've also set `rbenv global`, `rbenv local` to `2.2.2` and exported the environment variable `RBENV_VERSION` as `2.2.2` in both `.zshrc` and `.bashrc`... Still it's weird that if I first open a Ruby file, there's no syntax highlighting. If I run `M-x enh-ruby-mode`, `rbenv: version '2.2.1' is not installed` gets shown. Only when I run `M-x enh-ruby-mode` *the second time*, `[rbenv] using 2.2.2` gets shown and the file gets syntax-highlighted correctly... Maybe I should look at how `enh-ruby-mode` gets the interpreter path and try to fix the potential misconfiguration?

**Comment by syl20bnr** [comment]
@x-ji did you try the `develop` branch ? I merged some PRs to fix auto-completion is Ruby. You'll have auto-completion out of the box, but you'll get better auto-completion when a robe interpreter is launched.
I'm not a ruby dev too so I cannot help you as much as I want on this.

**Comment by syl20bnr** [comment]
I fixed the auto-completion activation in master.

**Comment by x-ji** [comment]
Cool. The default auto-completion via `company` is in master now. I didn't see there was already an issue for buggy auto-completion.
