### ISSUE TITLE
Relative line number counts above/below current line repeating over and over

### ISSUE THREAD

**Issue by ezmiller** [syl20bnr/spacemacs#13433]
#### Description :octocat:
Relative line number counts above/below current line repeat numbers over and over.

#### Reproduction guide :beetle:
- Enable relative line numbering in .spacemacs `dotspacemacs-line-numbers 'relative`
- Start Emacs
- Open a file
- See odd line numbering

*Observed behaviour:* :eyes: :broken_heart:
The line numbers repeat over and over again, so that the counts are innaccurate. E.g. counts look like

```
1
1
1




34



1
1
1
1`
```
Image:
![image](https://user-images.githubusercontent.com/772738/77859956-4a34b980-71da-11ea-9639-93f7ed7e0d86.png)

*Expected behaviour:* :heart: :smile:
Counts should look like:

```
5
4
3
2
1
34
1
2
3
4
5
```

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: nil (rev. 582f9aa45)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(racket csv osx ruby sql yaml typescript markdown clojure docker
        (python :variables python-test-runner
                '(pytest nose)
                python-sort-imports-on-save t python-enable-yapf-format-on-save t)
        php html terraform
        (helm :variables helm-use-fuzzy 'source)
        auto-completion emacs-lisp git react org
        (shell :variables shell-default-shell 'multi-term shell-default-width '45 shell-default-position 'right)
        syntax-checking
        (version-control :variables version-control-diff-tool 'git-gutter version-control-diff-side 'left)
        ezfm-config)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:
N/A

**Comment by jr0cket** [comment]
This issue is fixed in Spacemacs develop branch.

I suggest the quickest way to resolve this issue is to switch to the Spacemacs develop branch, there is a suggested approach here https://practicalli.github.io/spacemacs/install-spacemacs/switch-to-develop.html  

Line numbers in `develop` now use native line numbers when using Emacs version 26.3 or above, which are far more efficient than the linenum approach your version of Spacemac is using.

**Comment by ezmiller** [comment]
@jr0cket Ha, okay. That's funny. I just switched off the develop branch, thinking it was time since the next version had been released.

**Comment by jr0cket** [comment]
@ezmiller my understanding is the next version of Spacemacs will be released after Spacelpa feature is complete https://github.com/syl20bnr/spacemacs/issues/12652  

Until then, I recommend the Spacemacs `develop` branch which is quite stable for the vast majority of people and has the latest updates on features such as DAP.  

Once everything works on `develop` there is no need to keep updating to the latest commit or updating the packages (unless you want to).

**Comment by ezmiller** [comment]
That is helpful @jr0cket. Thank you!
