### ISSUE TITLE
deleting yasnippet-snippets... 

### ISSUE THREAD

**Issue by lanigb** [syl20bnr/spacemacs#13436]
Hi, 
I am new to Spacemacs I have followed the instruction to install it on a Debian 10 system.
---------
Found 7 orphan package(s) to delete...
--> deleting yasnippet-snippets... [1/7]
Debugger entered--Lisp error: (error "Package ‘yasnippet-snippets-0.9’ is a system package, not deleting")
  signal(error ("Package ‘yasnippet-snippets-0.9’ is a system package, not deleting"))
  error("Package `%s' is a system package, not deleting" "yasnippet-snippets-0.9")
  package-delete(#s(package-desc :name yasnippet-snippets :version (0 9) :summary "Collection of yasnippet snippets" :reqs ((yasnippet (0 8 0))) :kind nil :archive nil :dir "/usr/share/emacs/site-lisp/elpa/yasnippet-snippets-0.9" :extras nil :signed nil) t t)
  (progn (package-delete p t t))
  (if p (progn (package-delete p t t)))
  (let ((p (car (cdr (assq pkg-name package-alist))))) (if p (progn (package-delete p t t))))
  (cond ((version<= "25.0.50" emacs-version) (let ((p (car (cdr (assq pkg-name package-alist))))) (if p (progn (package-delete p t t))))) (t (let ((p (car (cdr (assq pkg-name package-alist))))) (if p (progn (package-delete p))))))
  configuration-layer//package-delete(yasnippet-snippets)
  (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (progn (spacemacs-buffer/set-mode-line "Uninstalling not used packages...") (spacemacs//redisplay) (spacemacs-buffer/append (format "Found %s orphan package(s) to delete...\n" orphans-count)) (setq deleted-count 0) (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n"))
  (if orphans (progn (spacemacs-buffer/set-mode-line "Uninstalling not used packages...") (spacemacs//redisplay) (spacemacs-buffer/append (format "Found %s orphan package(s) to delete...\n" orphans-count)) (setq deleted-count 0) (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n")) (spacemacs-buffer/message "No orphan package to delete."))
  (let* ((dependencies (configuration-layer//get-packages-upstream-dependencies-from-alist)) (implicit-packages (configuration-layer//get-implicit-packages-from-alist packages)) (orphans (configuration-layer//get-orphan-packages packages implicit-packages dependencies)) (orphans-count (length orphans)) deleted-count) (if orphans (progn (spacemacs-buffer/set-mode-line "Uninstalling not used packages...") (spacemacs//redisplay) (spacemacs-buffer/append (format "Found %s orphan package(s) to delete...\n" orphans-count)) (setq deleted-count 0) (let ((--dolist-tail-- orphans) orphan) (while --dolist-tail-- (setq orphan (car --dolist-tail--)) (setq deleted-count (1+ deleted-count)) (spacemacs-buffer/replace-last-line (format "--> deleting %s... [%s/%s]" orphan deleted-count orphans-count) t) (configuration-layer//package-delete orphan) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n")) (spacemacs-buffer/message "No orphan package to delete.")))
  configuration-layer/delete-orphan-packages((ace-jump-helm-line ace-link ace-window adaptive-wrap aggressive-indent async auto-compile auto-highlight-symbol avy bind-key bind-map clean-aindent-mode column-enforce-mode define-word desktop diminish dumb-jump elisp-slime-nav eval-sexp-fu evil evil-anzu evil-args evil-ediff evil-escape evil-exchange evil-iedit-state evil-indent-plus evil-lisp-state evil-matchit evil-mc evil-nerd-commenter evil-numbers evil-search-highlight-persist evil-surround evil-tutor evil-unimpaired evil-visual-mark-mode evil-visualstar exec-path-from-shell expand-region eyebrowse fancy-battery fill-column-indicator flx-ido golden-ratio google-translate helm helm-ag helm-descbinds helm-flx helm-make helm-mode-manager helm-projectile helm-swoop helm-themes highlight-indentation highlight-numbers highlight-parentheses hl-todo hungry-delete hydra indent-guide link-hint linum-relative lorem-ipsum macrostep move-text neotree open-junk-file org-bullets org-plus-contrib paradox pcre2el persp-mode popup popwin projectile rainbow-delimiters request restart-emacs smartparens spaceline toc-org undo-tree use-package uuidgen vi-tilde-fringe volatile-highlights which-key winum ws-butler))
  (progn (configuration-layer/delete-orphan-packages packages))
  (if (and (or (eq 'used dotspacemacs-install-packages) (eq 'used-only dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages)))
  (let ((packages (append (configuration-layer/filter-objects configuration-layer--used-distant-packages (function (lambda (x) (let ((pkg (configuration-layer/get-package x))) (not (eieio-oref pkg ':lazy-install)))))) (if (eq 'all dotspacemacs-install-packages) (progn (let (all-other-packages) (let ((--dolist-tail-- (configuration-layer/get-layers-list)) layer) (while --dolist-tail-- (setq layer (car --dolist-tail--)) (let ((configuration-layer--declared-layers-usedp nil) (configuration-layer--load-packages-files t)) (configuration-layer/declare-layer layer) (let* ((obj (configuration-layer/get-layer layer)) (pkgs (if obj (progn (eieio-oref obj ':packages))))) (configuration-layer/make-packages-from-layers (list layer)) (let ((--dolist-tail-- pkgs) pkg) (while --dolist-tail-- (setq pkg (car --dolist-tail--)) (let ((pkg-name (if (listp pkg) (car pkg) pkg))) (if (member pkg-name all-other-packages) all-other-packages (setq all-other-packages (cons pkg-name all-other-packages)))) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (configuration-layer//get-distant-packages all-other-packages nil))))))) (configuration-layer//install-packages packages) (if (and (or (eq 'used dotspacemacs-install-packages) (eq 'used-only dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages))))
  (if no-install nil (let ((packages (append (configuration-layer/filter-objects configuration-layer--used-distant-packages (function (lambda (x) (let ((pkg (configuration-layer/get-package x))) (not (eieio-oref pkg ':lazy-install)))))) (if (eq 'all dotspacemacs-install-packages) (progn (let (all-other-packages) (let ((--dolist-tail-- (configuration-layer/get-layers-list)) layer) (while --dolist-tail-- (setq layer (car --dolist-tail--)) (let ((configuration-layer--declared-layers-usedp nil) (configuration-layer--load-packages-files t)) (configuration-layer/declare-layer layer) (let* ((obj (configuration-layer/get-layer layer)) (pkgs (if obj (progn (eieio-oref obj ':packages))))) (configuration-layer/make-packages-from-layers (list layer)) (let ((--dolist-tail-- pkgs) pkg) (while --dolist-tail-- (setq pkg (car --dolist-tail--)) (let ((pkg-name (if (listp pkg) (car pkg) pkg))) (if (member pkg-name all-other-packages) all-other-packages (setq all-other-packages (cons pkg-name all-other-packages)))) (setq --dolist-tail-- (cdr --dolist-tail--)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (configuration-layer//get-distant-packages all-other-packages nil))))))) (configuration-layer//install-packages packages) (if (and (or (eq 'used dotspacemacs-install-packages) (eq 'used-only dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages)))))
  configuration-layer/sync()
(if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require 'core-spacemacs) (spacemacs/init) (configuration-layer/sync) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (require 'server) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/alain/.emacs.d/init.el" nil t)  ; Reading at buffer position 1264
  load-with-code-conversion("/home/alain/.emacs.d/init.el" "/home/alain/.emacs.d/init.el" t t)
  load("/home/alain/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1dda91>)()
  command-line()
  normal-top-level()

**Comment by jr0cket** [comment]
Please report issues from within Spacemacs itself where possible, using `SPC h I`

The submitted details are very hard to read, but it seems that you have installed emacs packages using the debian package manager.  You should remove all emacs packages and only install emacs itself via the debian package manager (emac, emacs-gtk, emacs-common).

The error message also suggests the Emacs version installed it too old.  Emacs version 26.3 or greater is recommended.  This version is available in Debian Sid https://packages.debian.org/sid/emacs

If you cannot use Debian sid, then there are other approaches describe on https://www.emacswiki.org/emacs/EmacsSnapshotAndDebian

If you can remove the formatting from the information you pasted into this issue, it would be easier to understand the issue.

**Comment by lanigb** [comment]
Hi,
Thanks.
Removing the formatting was not easy, I don't know why it was still present after pasting it in vim.
I removed the packages and now Spacemacs seems to work well. Awesome.
I am ok with using a more recent  Emacs  but how stable are the snapshots ?

**Comment by jr0cket** [comment]
From my own experience then Emacs 26.3 is the most stable, although I did use Emacs27 snapshots for about 9 months without any issues.

The Ubuntu Emacs PPA snapshots are now onto version 28 and I haven't tried them yet.  You can install a emacs-snapshot package along side the Emacs package in Debian/Ubuntu, so it's easy to test.

Now you have Spacemacs working, then `SPC h I` will nicely format an issue for you.

Consider using the Spacemacs Gitter channel (there is a link on spacemacs.org) for more help.  There is also an IRC channel.

If the issue is resolved, please close it.  Thank you.

**Comment by lanigb** [comment]
Thanks a lot for your help. I close the issue.
