### ISSUE TITLE
popwin not work for helpful mode for the first time

### ISSUE THREAD

**Issue by tshu-w** [syl20bnr/spacemacs#13434]
### Description :octocat:
popwin not work for helpful mode for the first time

#### Reproduction guide :beetle:
- Start Emacs
- SPC-h-d-v
- describe any variable

*Observed behaviour:* :eyes: :broken_heart:
helpful window show in fullframe.

*Expected behaviour:* :heart: :smile:
helpful window show currently as popwin set.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 72f280dc0)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(emacs-lisp helpful)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by tshu-w** [comment]
related pull request #13375

**Comment by duianto** [comment]
This is what it looks like for me:
Right after restarting Spacemacs.
And pressing `SPC h d v` `RET` (`dotspacemacs-distribution` was selected as the first candidate)

![emacs_2020-04-05_17-00-25](https://user-images.githubusercontent.com/13420573/78501991-005e4d00-775f-11ea-8a81-c9c75b5a62ae.png)

The same thing is observed with:
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy

And with:
- Distribution: spacemacs
- Editing style: vim
- Completion: helm


<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helpful html imenu-list ivy
            (java :variables java-backend 'meghanda)
            javascript latex lsp
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by tshu-w** [comment]
@duianto It's so strange, I can't reproduce this issue now. I'm sorry to bother you.

**Comment by duianto** [comment]
It's not a problem at all. If something looks broken then it's fine to report it.

It might just have occurred under a specific condition.
Or if it was fixed upstream, then someone else might not have updated yet and they'll find this issue.
