### ISSUE TITLE
treemacs has error when starting

### ISSUE THREAD

**Issue by jnordwick3x** [syl20bnr/spacemacs#13440]
#### Description :octocat:
treemacs will not start

#### Reproduction guide :beetle:
- Start Emacs
SPC f t

*Observed behaviour:* :eyes: :broken_heart:
eieio-defclass-internal: Given parent class treemacs-scope is not a class

*Expected behaviour:* :heart: :smile:
treemacs window showing up

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 463bbd536)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults treemacs helm multiple-cursors themes-megapack version-control git github syntax-checking semantic shell-scripts python rust emacs-lisp markdown
                 (cmake :variables cmake-enable-cmake-ide-support nil)
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-backend 'rtags c-c++-enable-google-style t c-c++-enable-google-newline t c-c++-adopt-subprojects t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Alexander-Miller** [comment]
Sounds like you pulled treemacs-persp without updating treemacs. An update should fix things.

**Comment by duianto** [comment]
I'm not seeing any errors when opening Treemacs (`SPC f t`),
on the latest Spacemacs develop branch with updated packages.

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git helm helpful html imenu-list
            (java :variables java-backend 'meghanda)
            javascript latex lsp
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            pdf python
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

@jnordwick3x If updating the packages fixed the issue for you, then feel free to close this issue.

**Comment by troglotit** [comment]
For future info: I had this issue and updating packages helped me.

**Comment by duianto** [comment]
Thanks for confirming that updating solved it.
