### ISSUE TITLE
Feature request: Lockstep for pair programming

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#13442]
Spacemacs supports Floobits for pair programming, but Lockstep would be another interesting option: https://github.com/tjim/lockstep

Would be great to have a nice integration for that in Spacemacs.

**Comment by jr0cket** [comment]
Although the idea sounds interesting there is a serious security issue with Lockstep that could compromise a persons account and personal data.  Unless this security issue could be managed without having to create a separate login account with very limited permissions just to run Emacs and Lockstep, I dont believe it would be prudent to included Lockstep in Spacemacs.

From the website:

"BE CAREFUL: any programmer in the session will be able to control the Emacs process running as the user who started the Emacs server. That means that any programmer in the session can edit files and start processes as if they were that user. The best way to deal with this is to create a special account solely for the purpose of pair programming, give this account limited permissions, and let all of the programmers log in to the account."

**Comment by lebensterben** [comment]
Please reopen this issue if you still want this feature.
