### ISSUE TITLE
Disable mid-click paste on MacOSX

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#13447]
MacOS X does not support mid-click paste, but one can enable it using apps like `macpaste`. 

However, spacemacs sets mid-click to paste, in such a way that when macpaste is used, a mid-click performs a double paste. Is there a way to disable the mid-click paste of spacemacs on macosx ?

**Comment by lebensterben** [comment]
```elisp
(define-key evil-insert-state-map (kbd "<mouse-2>") nil)
(define-key evil-normal-state-map (kbd "<mouse-2>") nil)
```
