### ISSUE TITLE
For *.lagda.md files, Agda (not Markdown) should be the major mode

### ISSUE THREAD

**Issue by liwoxa** [syl20bnr/spacemacs#13456]
You can make Agda the major mode for `*.lagda.md` files by putting
```emacs
(setq auto-mode-alist (cons '("\\.lagda.md$" . agda2-mode) auto-mode-alist))
```
in `dotspacemacs/user-config`.

Should this be part of the Agda layer, perhaps as a variable? I think it should at least mentioned in the documentation of that layer.

**Comment by duianto** [comment]
Feel free to open a PR.

If there are cases where it would be useful to open `.lagda.md` files in markdown mode, then it might be best to add a layer variable.

It seems to work to add (without `$` after `.md`):
```elisp
(add-to-list 'auto-mode-alist '("\\.lagda.md\\'" . agda2-mode))
```
inside the `agda/init-agda` functions `:init` sections `progn`:
https://github.com/syl20bnr/spacemacs/blob/c3f13d03910e6ae55e5c617ce7c7bd9cb9861d70/layers/%2Blang/agda/packages.el#L44-L47

I tested it with this file:
https://raw.githubusercontent.com/cs6110/2019sp-web/master/src/lectures/lec34.lagda.md

**Comment by onestruggler** [comment]
How should I modify it for Agda-2.8, where agda2-mode is no longer used. I tried replacing agda2-mode with agda --emacs-mode, and several similar trials. All won't work. Thanks.
> 
> (setq auto-mode-alist (cons '("\\.lagda.md$" . agda2-mode) auto-mode-alist))
> in `dotspacemacs/user-config`.
