### ISSUE TITLE
Cannot switch to the correct project (workspace)

### ISSUE THREAD

**Issue by gnohz** [syl20bnr/spacemacs#13459]
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>
Cannot auto switch the workspace

#### Reproduction guide :beetle:
- Start Emacs
- open a file in a project under a workspace
- call treemacs

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
show the projects in another workspace

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>
show the project in the corresponding workspace for the current file

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/gDrive/.spacemacs.d_dev/snippets/" :disabled-for org markdown)
 (latex :variables latex-enable-folding t latex-build-command "LatexMK")
 emacs-lisp git helm lsp java markdown multiple-cursors org python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables enable-flyspell-auto-completion t)
 syntax-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
So that we're testing the same thing.

Could you include the key bindings your pressing:
>open a file in a project under a workspace

Spacemacs has workspaces under: `SPC l w` (l = lowercase L)
and Treemacs has workspaces under: `C-c C-w`

How are the workspaces setup (possibly with their names) which one is shown before and after.
