### ISSUE TITLE
Can't select neotree at window 0 (No window numbered 10)

### ISSUE THREAD

**Issue by rubynho** [syl20bnr/spacemacs#13457]
#### Description :octocat:
I've moved the neotree to the right side putting `'(neo-window-position (quote right))` in the custom-set-variable, since then I can't select the neotree by `SPC 0` or `alt+0` anymore, it shows `No window numbered 10` at the bottom.
 
#### Reproduction guide :beetle:
- Start Emacs
- Open neotree
- Select window 1
- Try to select neotree with `SPC 0` or `alt+0`

*Observed behaviour:* :eyes: :broken_heart:

It shows `No window numbered 10` at the bottom of the editor and I can select neotree by pressing `SPC 2` or `alt+2` instead if only one window is open, like neotree number is the last window open instead of window 0.

*Expected behaviour:* :heart: :smile:

Select neotree window at number 0.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown ruby elixir javascript react helm auto-completion emacs-lisp
          (git :variables git-magit-status-fullscreen t)
          org
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LCMS2

**Comment by duianto** [comment]
This works on the `develop` branch, where those key bindings are remapped like this:
https://github.com/syl20bnr/spacemacs/blob/c3f13d03910e6ae55e5c617ce7c7bd9cb9861d70/layers/%2Bfiletree/neotree/packages.el#L119-L120

`develop` is the recommended branch until the next version is released.

But if you don't want to switch from the `master` branch, then you can add the above remapping to the `dotspacemacs/user-config` section in your `.spacemacs` file.

You can also add the following to the user-config section if you want to group your user settings in the same place:
```elisp
  (setq neo-window-position 'right)
```

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Comment by rubynho** [comment]
It works. Thank you very much @duianto!
