### ISSUE TITLE
How to redefine a keybind after use spacebind?

### ISSUE THREAD

**Issue by darcylee** [syl20bnr/spacemacs#13450]
For example:

`<SPC> b C-d`  spacemacs is bind to `spacemacs/kill-other-buffers` default. 
BUT i want to rebind to `spacemacs/kill-matching-buffers-rudely`

In previous version , just add this 
`(spacemacs/set-leader-keys "b C-d" 'spacemacs/kill-matching-buffers-rudely)`
in my own config, but this config is not work well in latest version 

How to in latest version?

**Comment by duianto** [comment]
```elisp
  (spacemacs/set-leader-keys "b C-d" 'spacemacs/kill-matching-buffers-rudely)
```
now works on the latest `develop` branch, because the variable: `spacebind--eager-bind`
has been enabled by default: https://github.com/syl20bnr/spacemacs/commit/acdb59767cc26b40819cc103767491951405e176

You can close this issue if it works as expected now.

**Comment by darcylee** [comment]
@duianto thank you for your reply. After pulling the latest version of spacemacs, the key operation is correct. But there is a problem with the display, the old binding information is still displayed
 
![image](https://user-images.githubusercontent.com/6210592/79574085-36ea7f00-80f2-11ea-9bd8-69e97926c12b.png)

**Comment by duianto** [comment]
This method for removing the current name from the which-key list, seems to work:
```elisp
  (delete* '("\\`SPC b C-d\\'") which-key-replacement-alist :test #'equal :key #'car)
```
source: https://www.reddit.com/r/spacemacs/comments/9rnh0p/anyway_to_undo_default_spacemacs_leader_prefixes/e8id41h/

Now the key binding list (https://github.com/justbur/emacs-which-key) that appears when pressing:
`SPC b` shows the name of the current command, (without the commands `spacemacs/` prefix, the full command name is: `spacemacs/kill-other-buffers`):
>C-d -> kill-other-buffers

When the key is rebound with:
```elisp
  (spacemacs/set-leader-keys "b C-d" 'spacemacs/kill-matching-buffers-rudely)
```
Then the key is shown as:
>C-d -> kill-matching-buffers-rudely
