### ISSUE TITLE
Long initial loading times for org files

### ISSUE THREAD

**Issue by avggeek** [syl20bnr/spacemacs#13467]
#### Description :octocat:
I am finding that Spacemacs takes extremely long (>1 minute) to load small ```org``` files even when Emacs has been launched in daemon mode and a new instance of Emacs frame is on-screen. Loading a second ```org``` file is much faster, typically in the region of a few seconds. I understand that by default Spacemacs uses ```:defer t```, but 60+ seconds to load seems excessively long to me.

#### Reproduction guide :beetle:
- Start Emacs in daemon mode using ```runemacs.exe --daemon``` at startup
- Launch Emacs frame with ```emacsclientw.exe -n -e "(raise-frame)" -a "C:\msys64\mingw64\bin\runemacs.exe"```
- Hit ```<RET>``` on a org file listed in Recent files.

*Observed behaviour:* :eyes: :broken_heart:
I felt it would be easier to record a screencast of the behaviour. I hit ```<RET>``` to load the ```org``` file at around the 4-second mark in the screencast (as can be seen in the orange popup bottom-right). Link with embedded video below:

[![Spacemacs org file in Windows](https://res.cloudinary.com/marcomontalbano/image/upload/v1586499777/video_to_markdown/images/youtube--yPPPpLz07CA-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://youtu.be/yPPPpLz07CA "Spacemacs org file in Windows")

*Expected behaviour:* :heart: :smile:
- ```org``` file will display within a few seconds on initial load

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 72f280dc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git markdown org
      (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
      spell-checking emoji shell-scripts windows-scripts yaml dash chrome nginx windows-defaults)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2

**Comment by Becsa** [comment]
Maybe you could try using emax64 (https://github.com/m-parashar/emax64) see if that helps. I'm on windows too and I dont face this problem.

**Comment by avggeek** [comment]
@Becsa Thanks for the suggestion on emax64. I did try it out as well. While it does appear to be faster, it still seems relatively slow to start. Here's the behaviour I'm seeing so far:

- Start emax64 version of ```runemacs``` in daemon mode.
- Launch emax64 version of ```emacsclientw.exe```. Frame loads and displays ```*spacemacs*``` buffer in <10 seconds. Packages load time is listed as < 10 seconds (which I assume is the daemon instance).
- Hit ```<RET>``` on the same org file shown in my video above. File displays in approximately 16-17 seconds.

I understand that Emacs is single-threaded and slow, but 16 seconds to load a 3 KB file from an SSD still seems overly slow.

**Comment by Becsa** [comment]
One more thing you could try is setting `dotspacemacs-scratch-mode 'org-mode` so that org mode is initiated when you start the daemon. Or maybe even addig `agenda ` to your `dotspacemacs-startup-lists` so that it has to read an org file on startup, the daemons startup speed doesnt matter anyways.

**Comment by avggeek** [comment]
@Becsa I use ```projects``` a little bit and so I went with your alternative approach, setting ```dotspacemacs-scratch-mode 'org-mode```. It does help with the loading of org files after the daemon has loaded.

That said, I would like to leave this issue open. When I launched spacemacs today, the homepage showed it took _104_ seconds to load. That just does not seem normal 😞

**Comment by duianto** [comment]
#### Are you using any third party antivirus?
This comment: https://emacs.stackexchange.com/a/17879 says:
>I should also note that certain anti-virus software (McAfee, in particular) can cause massive slowdowns. With McAfee's On-Access Scanner enabled, things are a noticeably slower for me. Cygwin's git status can take up to 2 minutes! Only after turning it off do I get the times I stated above.

#### This is what I'm seeing
When this file: `example.org` was the last opened file before Spacemacs was closed/restarted.
```org
* one
a b c d e
* two
1 2 3 4 5
* three
I II III III IV
```

When Spacemacs started, then the org file was opened from the spacemacs home buffer by 
- pressing `r` to focus the first item (`example.org`) in the recent files list
- pressing `RET` to open it

<details><summary>
PopOS 19.10,
GNU Emacs 26.3.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.12) of 2019-10-31
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0a7ab7873)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 pdf python
                 (shell :variables shell-default-shell 'term shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

- Without a daemon: `~5` sec
- With a daemon: `~4-5` sec

<details><summary>
Windows 1903,
GNU Emacs 26.3 (build 1, x86_64-w64-mingw32) of 2019-08-29
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0a7ab7873)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log dap emacs-lisp git helm helpful html imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors nim
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

- Without a daemon: `~10-12` sec
- With a daemon: `~10` sec

The daemon was started like this:
Open two terminals/command prompts (cmd)
- call: `emacs --daemon` in one terminal/cmd
- call: `emacsclient -c` in the other terminal/cmd

#### Notes on the video
In the video: https://youtu.be/yPPPpLz07CA

Is the browser that opens at [1min 10sec](https://youtu.be/yPPPpLz07CA?t=70) related to opening the org file?
Or were you just tired of waiting and opened the browser 😄

#### If the browser is related to opening the org file:
Is the org file being exported and opened in the browser automatically?

#### If the browser is unrelated
and no exporting occurs (I haven't exported enough org files to know if it takes a long time), then it seems like something isn't working correctly.

It looks like the org file opened in Spacemacs at [1min 16sec](https://youtu.be/yPPPpLz07CA?t=76), but it's only fully visible for a couple of frames before the browser opens again.
(The youtube player can step forwards and backwards by frames when it's paused, with:
`,` (comma) and `.` (period))

It might be better to re-record future videos if something unrelated occurs.
Or explain that the browser accidentally opened.

**Comment by avggeek** [comment]
@duianto Thank you for the detailed and comprehensive reply! I will reply working backwards as some of the questions at the end are easier to answer.

> #### Notes on the video
> 
> In the video: https://youtu.be/yPPPpLz07CA
> 
> Is the browser that opens at [1min 10sec](https://youtu.be/yPPPpLz07CA?t=70) related to opening the org file?

It is partially related to opening the org file. At the time of recording of the video, the org file was had an "open" section with a TODO containing a URL. It appears as though as soon as the file opened, the URL under the cursor was launched as well. I cannot see a ```<RET>``` entry in my keystroke recording window so I'm not entirely sure how to explain this behaviour.

> (The youtube player can step forwards and backwards by frames when it's paused, with:
> `,` (comma) and `.` (period))

Thank you for the tip!

> It might be better to re-record future videos if something unrelated occurs.
> Or explain that the browser accidentally opened.

Noted!

> #### Are you using any third party antivirus?
> 
> This comment: https://emacs.stackexchange.com/a/17879 says:
> 
> > I should also note that certain anti-virus software (McAfee, in particular) can cause massive slowdowns. With McAfee's On-Access Scanner enabled, things are a noticeably slower for me. Cygwin's git status can take up to 2 minutes! Only after turning it off do I get the times I stated above.

Not just third-party antivirus but turns even the built-in Windows Defender AV can cause this problem! I have Windows Defender AV and Acronis Ransomware Protection turned on. I'm listing down what I saw for reference:

* In Windows Defender, exclude ```msys2``` folder and ```emacs.exe```, ```runemacs.exe``` and ```emacsclientw.exe``` and disable Acronis Ransomware Protection completely.
  - Emacs load time with ```dotspacemacs-scratch-mode 'text-mode``` : 4 seconds
  - Time to load org file: 12 seconds
  - Emacs load time with ```dotspacemacs-scratch-mode 'org-mode``` :  14 seconds

* Same Windows Defender settings, Enable Acronis Ransomware Protection  but exclude ```emacs.exe```, ```runemacs.exe``` and ```emacsclientw.exe```.
  - Emacs load time with ```dotspacemacs-scratch-mode 'text-mode``` : 8 seconds
  - Time to load org file: 22 seconds
  - Emacs load time with ```dotspacemacs-scratch-mode 'org-mode``` :  24 seconds

I can live with the 25 sec. startup when ```scratch-mode``` is set to ```org-mode``` as org files open instantaneously with this option. 

Should I mark the issue as closed?

**Comment by avggeek** [comment]
> 
> Should I mark the issue as closed?

Sigh. Looks like I spoke to soon. As of this morning, the Spacemacs home buffer is again showing loading times of around 100 seconds.

**Comment by duianto** [comment]
>Should I mark the issue as closed?

It's fine to close issues that have been resolved.
