### ISSUE TITLE
Opening a PDF (with `pdf` layer installed) results in a segfault

### ISSUE THREAD

**Issue by mnicstruwig** [syl20bnr/spacemacs#13468]
#### Description :octocat:
Opening a PDF (with `pdf` layer installed) results in a segfault

#### Reproduction guide :beetle:
- Start Emacs
- Run no additional commands
- Open any .pdf file (with the `pdf` layer installed)
- Emacs crashes with segfault

*Observed behaviour:* :eyes: :broken_heart:
- Emacs crashes immediately with segfault upon opening the file.

What's quite bizarre, however, is that if I call `M-x pdf-tools-help`, there is
some delay (not sure if some magic is going on in the background), and the
`pdf-tools` help documentation is shown. If I _then_ try and open a PDF file, things
work as expected.

*Expected behaviour:* :heart: :smile:
- Spacemacs opens a PDF file.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(pdf deft html react web-beautify csv ivy ess
     (python :variables python-test-runner 'pytest python-backend 'lsp python-lsp-server 'mspyls python-lsp-git-root "~/Code/python-language-server")
     common-lisp
     (org :variables org-enable-org-journal-support t)
     (auto-completion :variables auto-completion-enable-snippets-in-popup nil)
     latex emacs-lisp git markdown neotree org spell-checking syntax-checking lsp
     (javascript :variables javascript-import-tool 'import-js javascript-fmt-tool 'prettier javascript-backend 'lsp javascript-repl 'nodejs)
     (shell :variables shell-default-term-shell "/bin/zsh"))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by duianto** [comment]
A .pdf file opens from the recent files list on the spacemacs home buffer, without any issues for me, on the latest develop branch with updated packages.

<details><summary>
PopOS 19.10, 26.3.50
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. acdb59767)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion command-log emacs-lisp git ivy markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 pdf python
                 (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

<details><summary>
Windows 1903, Emacs: 26.3 and 27.0.90
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3 and 27.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. acdb59767)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 command-log dap emacs-lisp git helm helpful html imenu-list javascript latex
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org"))
 pdf
 (php :variables php-backend 'lsp)
 (python :variables python-backend 'anaconda)
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by beyondpie** [comment]
I didn't face this problem on the MacOS (10.15.4), Emacs 27.090 installed via emacs-plus

**Comment by mnicstruwig** [comment]
Bizarrely, after a system update (not emacs) the problem appears to have resolved itself. Closing!
