### ISSUE TITLE
A way to rebind core keybindings.

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#13460]
I'm dealing with this thing that's annoying me. I wanted to rebind `SPC p t`, which is bound to `(treemacs)` to be used by something else, in my case to be used by `direx` package. So I did this:

    (use-package direx
        :demand t
        :init
        (spacemacs/set-leader-keys "pt"  #'direx:jump-to-project-root-or-current-dir))
        
That didn't work - tremacs loads and still overrides that binding.

I thought, fine, I'll do it this way

    (use-package direx
            :demand t
            :init
            (with-eval-after-load 'treemacs
              (spacemacs/set-leader-keys "pt"  #'direx:jump-to-project-root-or-current-dir)))

And that worked, however - very first time (after loading Emacs) it still opens treemacs. The reason - the keybinding is set for treemacs, which loads lazily, and until you run it at least once, it won't rebind. 

Can someone suggest a workaround?

**Comment by jr0cket** [comment]
From the .spacemacs file

**Comment by agzam** [comment]
@jr0cket John, I don't want to remove treemacs, I just want to re-use the binding. And Spacemacs not letting me do that easily. Besides, that won't exclude it. It's a core package.

**Comment by robbyoconnor** [comment]
@agzam don't do this, use the `SPC o` prefix.

**Comment by agzam** [comment]
What do you mean "don't do this"? Don't be silly, it's Emacs we're talking about. If I want to do something, I probably can and I most definitely will :)

**Comment by robbyoconnor** [comment]
Of course but the issue is that you're doing something that well..is
perilous. Also SPC pt is defined in the neotree and treemacs layers, not
in core.

**Comment by agzam** [comment]
- treemacs package is included in Spacemacs by default, I am not explicitly including it.
- perilous or not, if an Emacs user wants to customize something, they should be able to. Especially something trivial like a top level keybinding. Telling users not to do things is a wrong approach. This is exactly why people leaving Spacemacs for Doom and custom configs.

**Comment by jr0cket** [comment]
> From the .spacemacs file
> 
> ```
>    ;; A list of packages that will not be installed and loaded.
>    dotspacemacs-excluded-packages '()
> ```
> 
> Would adding treemacs package here help ?

This is not the answer to the original question, but seems a viable alternative (I do not have that answer).

On a test of my system this morning, I commented out the treemacs layer and adding `treemacs` to `dotspacemacs-excluded-packages`.  After restarting Spacemacs the `SPC p t` keybinding was not present, however, `SPC SPC treemacs` still launches treemacs.

I am unsubscribing from this issue as I have nothing more to share.

**Comment by thanhvg** [comment]
Put your binding inside `dotspacemacs/user-config` which will run last so it will override what is set in `:init` by the tree layer. 

``` elisp
(spacemacs/set-leader-keys "pt"  #'direx:jump-to-project-root-or-current-dir)
``` 
Remove all binding code in your `use-package`. You won't need it. I don't use `treemacs`. I tested with `neotree`

**Comment by tshu-w** [comment]
maybe you can refer this: https://github.com/ekaschalk/.spacemacs.d/tree/master/layers/config/local/redo-spacemacs

**Comment by duianto** [comment]
The `spacebind--eager-bind` variable has now been enabled by default on the `develop` branch.
https://github.com/syl20bnr/spacemacs/blob/acdb59767cc26b40819cc103767491951405e176/core/core-spacebind.el#L14-L16

This enables rebinding `SPC p t` with:
```elisp
  (use-package direx
    :demand t
    :init
    (spacemacs/set-leader-keys "pt"  #'direx-project:jump-to-project-root))
```
or outside the `use-package` expression:
```elisp
(spacemacs/set-leader-keys "pt"  #'direx-project:jump-to-project-root)
```

@agzam Feel free to close this issue if the issue has been fixed.

### Note
Since I didn't have agzam's function `direx:jump-to-project-root-or-current-dir`
https://github.com/agzam/dot-spacemacs/blob/943d8d63b124a575151118c311a204231646bc90/layers/ag-dired/funcs.el#L81

I used `direx-project:jump-to-project-root` in the examples above.

@thanhvg The reason it works with the `neotree` layer, is because it binds `SPC p t` with the function: `spacemacs/set-leader-keys`
https://github.com/syl20bnr/spacemacs/blob/acdb59767cc26b40819cc103767491951405e176/layers/%2Bfiletree/neotree/packages.el#L107-L110

The `treemacs` layer binds it using the `spacmeacs|spacebind` macro.
https://github.com/syl20bnr/spacemacs/blob/d95d41f55ba074128b3ed8f0eedcdc3c31b52e42/layers/%2Bfiletree/treemacs/packages.el#L42-L51

**Comment by agzam** [comment]
@duianto I don't know what I'm missing but this fixed nothing for me. This is what I have right now:

- A custom layer with a package (direx). The layer does not anyhow refer to `treemacs`
- Nothing else in the entire configuration refers to treemacs
- Without doing anything, `SPC p t` binds to `spacemacs/treemacs-project-toggle` (that's expected)
- in my custom layer, I have an init function that runs `(use-package direx` piece, and it loads it just fine. But I'm still failing to override `SPC p t` from within my custom layer

What I've tried so far:

- Placing `(spacemacs/set-leader-keys "pt"  #'direx:jump-to-project-root-or-current-dir)` inside `:init` of use-package call
- Placing it outside of it
- Placing it within `:config` section
- I have even tried setting `(setq-default spacebind--eager-bind nil)` in `dotspacemacs/user-init`
- I tried creating layers.el for my layer with `(configuration-layer/declare-layers '(treemacs))`, hoping it will get loaded after treemacs layer
- I placed `(message "🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱🐱")` inside `use-package direx` block and `(message "🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶🐶")` inside `treemacs/init-treemacs` in `.emacs.d/layers/+filetree/treemacs/packages.el`. 
And the dogs always get printed after cats.

I don't know what else to try. But I can't rebind the damn keybinding without loading treemacs at least once.

**Comment by duianto** [comment]
### Previous test
I tested it by adding `direx` to the additional packages list.

And both the:
- use-package direx block with the set-leader-keys binding
- or just the set-leader-keys binding alone

worked from the user-config section, in both:

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. acdb59767)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 python
                 (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. acdb59767)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ag-dired autohotkey
          (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
          command-log dap emacs-lisp git helm helpful html imenu-list javascript latex
          (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
          multiple-cursors
          (org :variables org-agenda-files
               '("~/org/notes.org"))
          pdf
          (php :variables php-backend 'lsp)
          (python :variables python-backend 'anaconda)
          (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
          spell-checking
          (syntax-checking :variables syntax-checking-enable-by-default nil)
          treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

### New test
I now tried it with your `ag-dired` layer:
https://github.com/agzam/dot-spacemacs/tree/master/layers/ag-dired

And it seems to be a loading order issue.
When the key binding locations are logged:
```
ag-dired/init-direx :init define SPC p t
treemacs/init-treemacs :init define SPC p t
```
the treemacs binding is defined after the ag-dired binding (Spacemacs might be loading the layers alphabetically).

### A possible solution
It seems to work to add a new function: `ag-dired/post-init-direx`
```
ag-dired/init-direx :init
treemacs/init-treemacs :init define SPC p t
ag-dired/post-init-direx define SPC p t
```

By removing the following from the `ag-dired/init-direx` function:
```elisp
    (with-eval-after-load 'treemacs
      (spacemacs/set-leader-keys
        "pt"  #'direx:jump-to-project-root-or-current-dir))
```
https://github.com/agzam/dot-spacemacs/blob/master/layers/ag-dired/packages.el#L77

And adding the following after the `ag-dired/init-direx` function:
```elisp
(defun ag-dired/post-init-direx ()
  (spacemacs/set-leader-keys
    "pt"  #'direx:jump-to-project-root-or-current-dir))
```

However when I press `SPC p t` before a direx buffer has been opened, then I get the message:
>let: Symbol’s function definition is void: direx-project:find-project-root-noselect

**Comment by agzam** [comment]
Oh.. wow.. I don't know what to say. Your determination to keep digging to get to the bottom of this amazes me. Thank you! My apologies for complaining about something non-essential like this. I didn't mean to force you to spend so much time trying to find a solution. 

> let: Symbol’s function definition is void: direx-project:find-project-root-noselect

that can be fixed by requiring `direx-project`, it might be a tiny issue with direx.

**Comment by agzam** [comment]
I don't know how the simple idea of using post-init function to bind the key hasn't come to my mind. Once again - thank  you!

**Comment by duianto** [comment]
No apologies necessary, and it's not non-essential, if one person encounters an issue, then it's likely to happen again. Now we both know a little bit more about key binding loading order 😄
