### ISSUE TITLE
Can't disable company-mode for python-mode

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#13464]
#### Description :octocat:
I have done all the following to no avail:

```
 ;; In layers
     (python :variables python-backend 'anaconda)
      (auto-completion :disabled-for '(ocaml python) :variables
                      auto-completion-enable-help-tooltip t
                      auto-completion-enable-snippets-in-popup t)

 ;; In user-config
   (require 'dap-python)
  (setenv "WORKON_HOME" "~/anaconda/envs")
  (pyvenv-activate  "~/anaconda/bin")

   (defun my/python-mode-hook ()
    (company-mode -1)
    )
  (add-hook 'python-mode-hook 'my/python-mode-hook)
  (setq company-global-modes '(not tuareg-mode org-mode python-mode))
  (spacemacs|disable-company org-mode)
  (spacemacs|disable-company python-mode)
```

In the meantime, the reason I want company disabled is that it causes an infinite loop when trying to complete stuff. Not even ^G or `pkill -SIGUSR2 -i emacs` solves it. (The latter sometimes work.)

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby lua octave csv sql asciidoc yaml fsharp windows-scripts javascript json ocaml idris fasd xclipboard gpu epub spotify search-engine vimscript
      (elfeed :variables rmh-elfeed-org-files
              (list "~/.emacs.d/private/feeds/elfeed1.org"))
      (rust :variables rust-format-on-save t)
      (haskell :variables haskell-enable-hindent t)
      lsp
      (c-c++ :variables c-c++-enable-clang-support t)
      html
      (python :variables python-backend 'anaconda)
      dap chrome
      (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
      (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
      autohotkey kotlin helm
      (auto-completion :disabled-for
                       '(ocaml python)
                       :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
      emacs-lisp
      (ibuffer :variables ibuffer-group-buffers-by 'modes)
      coq emoji
      (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
      git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking
      (syntax-checking :variables syntax-checking-enable-tooltips t)
      (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
      version-control osx scheme
      (clojure :variables clojure-enable-fancify-symbols t))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
This line seems to be where company-mode is enabled for python-mode:
https://github.com/syl20bnr/spacemacs/blob/acdb59767cc26b40819cc103767491951405e176/layers/%2Blang/python/packages.el#L83

because when it's commented out then a `.py` file opens with company-mode being disabled.

I'm not sure how to enable the other methods, but a workaround for now, is to add the following to the `dotspacemacs/user-config` section:
```elisp
(remove-hook 'python-mode-local-vars-hook #'spacemacs//python-setup-company)
```

**Comment by NightMachinary** [comment]
@duianto I ended up disabling the layer and configing elpy manually. It’s way better than the python layer ever was. I think an elpy-based layer is a very good idea.

**Comment by vv111y** [comment]
@NightMachinary can you elaborate what makes elpy better than what we have? Or is there some info somewhere that compares the two? Thanks.

**Comment by vv111y** [comment]
fwiw somebody has an elpy layer https://github.com/deerainw/elpy

**Comment by NightMachinary** [comment]
[**@vv111y**](https://github.com/vv111y) commented on [Aug 24, 2020, 3:41 PM GMT+4:30](https://github.com/syl20bnr/spacemacs/issues/13464#issuecomment-679064456 "2020-08-24T11:11:57Z - Replied by Github Reply Comments"):
> [@NightMachinary](https://github.com/NightMachinary) can you elaborate what makes elpy better than what we have? Or is there some info somewhere that compares the two? Thanks.

The Python layer did not work for me. The elpy setup has quite intelligent autocomplete and good errors. But I have encountered a serious bug there that resets indentation by mere scrolling (I don't know how to reproduce it, but I saw it several times on the same file.).

(I have also switched to https://github.com/hlissner/doom-emacs/blob/develop/docs/faq.org, so I don't really have any skin in this game nowadays.)

**Comment by vv111y** [comment]
okay thanks
