### ISSUE TITLE
Debugger entered--Lisp error: (bad-signature "archive-contents.sig")

### ISSUE THREAD

**Issue by hyperlifehack** [syl20bnr/spacemacs#13466]
sorry pretty new to emacs.

when install spacemacs it downloads 90 packages. one failes with:

Debugger entered--Lisp error: (bad-signature "archive-contents.sig")
  signal(bad-signature ("archive-contents.sig"))
  package--check-signature-content

https://elpa.gnu.org/packages/" "archive-contents" "(1\n (ace-window .\n

restart and rinse?

**Comment by tianywan** [comment]
Have you fix this issue? I have the same problem, but  I don't have any solution for it.

**Comment by duianto** [comment]
Which Emacs version are you using?
`M-x emacs-version`

The signature key that comes with Emacs versions before 26.3 has expired:
https://stackoverflow.com/questions/58202993/emacs-failed-to-verify-signature-archive-contents-sig
>The signature check failed because you don't have the new key (the old signature key expired on Sep 23). The new key is available from the usual GPG key-servers, comes with Emacs≥26.3, and can also be obtained by installing the package gnu-elpa-keyring-update.

The accepted answer here, might also be helpful:
https://emacs.stackexchange.com/questions/233/how-to-proceed-on-package-el-signature-check-failure
>- set package-check-signature to nil, e.g. M-: (setq package-check-signature nil) RET
>- download the package gnu-elpa-keyring-update and run the function with the same name, e.g. M-x package-install RET gnu-elpa-keyring-update RET.
>- reset package-check-signature to the default value allow-unsigned
>
>This worked for me.

**Comment by NeroAngelo-117** [comment]
Like @duianto said, you need to download the signature and then import it. I went for the first option he mentioned and it worked for me. However the instructions are not precise as it refers to emacs not spacemacs. So here's my guide on how to do it:

1. Launch emacs--insecure.
2. Go to this [https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html](link) and then download the tar file and extract it somewhere in the home directory( preferably .emacs.d).
3. Back on spacemacs, press Ctrl + X, this will make spacemacs enter into command mode.
4. Now type `package-import-keyring` and hit enter.
5. Now open file manager and navigate to wherever you extracted your signature files, there will be a `etc` directory and inside of it a keyring file.
6. Copy the path name and paste it into spacemacs and hit enter(paste might not work tho, you might need to type the path yourself).
 
It should work now, as it did for me.

**Comment by vnctaing** [comment]
> - Fetch the new key manually, e.g. with something like:
> 
>       gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40
> 
> - Modify the expiration date of the old key, e.g. with something like:
> 
>       gpg --homedir ~/.emacs.d/elpa/gnupg \
>           --quick-set-expire 474F05837FBDEF9B 1y

From https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html


This did the trick to me
