### ISSUE TITLE
Dead keys aren't working

### ISSUE THREAD

**Issue by tuxayo** [syl20bnr/spacemacs#13469]
#### Description :octocat:
[Dead keys](https://en.wikipedia.org/wiki/Dead_key) aren't working.

#### Reproduction guide :beetle:
- Start Emacs
- go to scrach
- try to use a dead key
  - with a french (azerty) keyboard, press dead key `^` then press `e` to try to get `ê`

*Observed behaviour:* :eyes: :broken_heart:
message: `<dead-circumflex> is undefined`

*Expected behaviour:* :heart: :smile:
Not message and when pressing "e" the result should be ê

It happens also with `¨` and `˘`

Since years I have seen this. Not releated to recent versions.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2d7480f67)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby helm emacs-lisp git markdown org spell-checking syntax-checking html sql)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
I don't have a french keyboard, but maybe one of these workarounds will work:
```
>1/ launch emacs with "XMODIFIERS='' emacs"
2/ type C-x 8 RET RET once
3/ add "(require 'iso-transl)" to your .emacs.d/init.el or .emacs file
```
source: Can't type accented characters anymore: <dead-acute> is undefined
https://bugs.launchpad.net/emacs-snapshot/+bug/1251176

These pages seem to have some suggestions for how to rebind/remap the keys:
https://unix.stackexchange.com/questions/28170/some-keys-are-invalid-on-emacs-when-using-german-keyboard
https://emacs.stackexchange.com/questions/2568/problem-dead-acute-is-undefined-appearing-when-typing-greek-stress
https://stackoverflow.com/questions/9145972/mapping-dead-keys-like

**Comment by rubynho** [comment]
Worked changing the `XMODIFIERS` to `''` in the `.spacemacs.env` file. Don't forget to refresh the env vars (`SPC f e E`).

**Comment by tuxayo** [comment]
Thanks for answers :)

> 1/ launch emacs with "XMODIFIERS='' emacs"

It doesn't work in my case.

> 2/ type C-x 8 RET RET once

Works, I can't do ê but not ĝ,ĵ,ĉ,ŝ

> 3/ add "(require 'iso-transl)" to your .emacs.d/init.el or .emacs file

Works, I can't do ê but not ĝ,ĵ,ĉ,ŝ

**Comment by lebensterben** [comment]
@tuxayo
If you mean the AltGr key, you can try this:
https://github.com/syl20bnr/spacemacs/issues/5188#issuecomment-187388348

**Comment by tuxayo** [comment]
errata: *Works, I can do ê but not ĝ,ĵ,ĉ,ŝ

@lebensterben 
>  If you mean the AltGr key, you can try this:

No luck, didn't change the behavior.
What do you mean with AltGr ? I have the key but I don't know how it should be user here. It's not needed in other applications.

**Comment by lebensterben** [comment]
@tuxayo 
https://en.m.wikipedia.org/wiki/AltGr_key

**Comment by tuxayo** [comment]
>  https://en.m.wikipedia.org/wiki/AltGr_key

No problem with the AltGr key itself. It doesn't seem to be needed in this context because outside of Emacs, I can use directly the dead circumflex to do al my chars.

> If you're trying to type Esperanto, see setxkbmap section of https://www.esperanto.org.nz/learn-and-use-esperanto/kiel-tajpi-en-esperanto/linux/

You guessed well ^^
A way to handle multilingualism is to use one layout which allow to type all the chars for the desired languages. To not have to learn multiple layout and never be efficient in part/most of them. Also to mix language in the same phrase or paragraph, like it's done when speaking.

I this case, the basic fr layout allows to type ĉĝĥĵ in other programs so there is hope to do that in Emacs.

**Comment by tuxayo** [comment]
Still valid. Even if the workarounds would work. That's would still be a lack of support by default for (some?) dead keys.

**Comment by lebensterben** [comment]
@tuxayo 

does this work? https://github.com/syl20bnr/spacemacs/issues/13469#issuecomment-744633551

**Comment by rubynho** [comment]
What actually worked for me was to require the `iso-transl` package in the `dotspacemacs/user-config` section, apart from the fact I still can't type ĝ,ĵ,ĉ,ŝ.

**Comment by tuxayo** [comment]
> Please try to enable iso-transl package.

I didn't even need to try something else, I'm using emacs 28 and it works! :D

Just double checked, it seems I have nothing in my conf or env that made it work such as the previously proposed workarounds. So other people have a chance of it working out of the box :)

Thanks all for the help/
