### ISSUE TITLE
evil-forward-sentence-begin is bound to ), which is causing conflict to type ) in term.

### ISSUE THREAD

**Issue by naibprabhanjan** [syl20bnr/spacemacs#13472]

**Comment by naibprabhanjan** [comment]
Defined in ~/.emacs.d/elpa/evil-20200304.1421/evil-commands.el
I tried to comment this function, I am still not able to type ) in the term.

**Comment by duianto** [comment]
Can you provide some more information, based on the reporting template:
```
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

<< YOUR SYSTEM INFORMATION, it can be copied to the clipboard by pressing: SPC h d s >>
```
source: https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template

This is what I'm seeing with: `(shell :variables shell-default-shell 'term)`
when `S-0` (`Shift 0`) is pressed at a term shell prompt (`SPC '`):
- in evil insert state: It inserts `)` (a close parenthesis)
- in evil normal state: The cursor moves to the line below the current prompt
(it called `evil-forward-sentence-begin`)

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0a7ab7873)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp git helm markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 pdf python
                 (shell :variables shell-default-shell 'term shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

**Comment by naibprabhanjan** [comment]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html c-c++ pdf-tools javascript helm emacs-lisp org python elfeed semantic git
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle :disalbe-for org)
      (syntax-checking :variables syntax-checking-enable-by-default 't)
      (ibuffer :variables ibuffer-group-buffers-by nil)
      ranger
      (shell :variables shell-default-shell 'eshell)
      csharp command-log)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
The `develop` branch is the recommended branch until the next version is released (I have no insight into when that is).

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Comment by lebensterben** [comment]
Closed since no update is recieved.
