### ISSUE TITLE
[feature request] Getting Spacemacs to keep from shuffling buffer order

### ISSUE THREAD

**Issue by stradicat** [syl20bnr/spacemacs#13473]
Situation: editing buffers _A - B - C - D - E_, navigated in a left-to-right fashion with `C-x ← and C-x →`, then invoking some command like `magit`, closing the transient overlay and going back to buffers.

Now the buffers are ordered as _A - C - E - [some lsp log] - D - [some other log]_.
It gets a tad annoying after a while, since one has to keep going to `C-x b buffer-name` instead of just going sideways (some ThinkPads have integrated _page keys_ that trigger `C-x ← and C-x →`).

For comparison purposes, `doom-emacs` doesn't exhibit this apparently random reordering.

I haven't found a way to keep the buffer order yet, hence this call for help.

**Comment by dennismayr** [comment]
It looks even more counterintuitive when using `centaur-tabs` to keep an eye on open buffers for a project.
Adjacent buffers show adjacent tabs on the upper border of the current window, yet they're not cycled sequentially.
![](https://imgur.com/vJ3WQYk.png)

So far, after experimenting for a couple of weeks, I haven't been able to find any setting that could prevent this behavior.

**Comment by dennismayr** [comment]
The issue is still valid.

**Comment by lebensterben** [comment]
> The order of the buffers in this list is based primarily on how recently each buffer has been displayed in a window.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer-List.html

Likely related.

**Comment by lebensterben** [comment]
Also, you need to provide a concrete list of steps to reproduce the behaviour.

**Comment by dennismayr** [comment]
> > The order of the buffers in this list is based primarily on how recently each buffer has been displayed in a window.
> 
> > A buffer moves to the front of this list whenever it is chosen for display in a window (see Switching Buffers) or a window displaying it is selected (see Selecting Windows).
> 
> https://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer-List.html
> 
> Importantly,
> 
> > There are no functions available to the Lisp programmer which directly manipulate the buffer list
> 
> So I don't how doom could possibly fix the order.

That's exactly why I find it puzzling. Under `doom-emacs`, the buffer order remains unaltered. Under _Spacemacs_, it is modified.

**Comment by dennismayr** [comment]
> Also, you need to provide a concrete list of steps to reproduce the behaviour.
I can only sum this up as:

- Situation: editing buffers A - B - C - D - E
- Navigate between buffers in a left-to-right fashion with C-x ← and C-x →
- Invoke some command like `magit`, closing its transient overlay (e.g. to save a commit)
- Go back to the last edited buffer
- Navigated between buffers again in a left-to-right fashion with C-x ← and C-x →
- See that the buffer order has changed.
