### ISSUE TITLE
where is +lsp in layers/tools ?

### ISSUE THREAD

**Issue by TheZano** [syl20bnr/spacemacs#13484]

**Comment by honuonhval** [comment]
have you looked in develop branch? ([develop layers/tools/lsp](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/lsp))

**Comment by TheZano** [comment]
> have you looked in develop branch? ([develop layers/tools/lsp](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/lsp))

solved! thanks
