### ISSUE TITLE
Develop source-control layer missing commands

### ISSUE THREAD

**Issue by wminshew** [syl20bnr/spacemacs#13487]
Please let me know if there's any information I'm missing!

#### Description :octocat:
`SPC g v` is undefined with source-control layer installed (vc commands show up with `SPC SPC` and are accessible through their regular emacs [keybindings](https://www.emacswiki.org/emacs/VersionControl)

#### Reproduction guide :beetle:
- Start Emacs
- Open file (tested with enh-ruby/rails & javascript)
- Enter `SPC g v`

*Observed behaviour:* :eyes: :broken_heart:
`SPC g v` is undefined

*Expected behaviour:* :heart: :smile:
Keybindings for VC package

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.60
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. acdb59767)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 emacs-lisp emoji git
 (gtags :variables gtags-enable-by-default t)
 helm
 (html :variables web-fmt-tool 'prettier)
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (javascript :variables javascript-import-tool 'import-js javascript-backend 'lsp javascript-lsp-linter nil js2-mode-show-strict-warnings nil js2-mode-show-parse-errors nil javascript-fmt-tool 'prettier node-add-modules-path t js2-include-node-externs t)
 (json :variables json-fmt-tool 'prettier)
 (lsp :variables lsp-solargraph-use-bundler t)
 markdown multiple-cursors org osx prettier
 (ranger :variables ranger-show-preview t ranger-cleanup-on-disable t ranger-show-hidden t ranger-max-preview-size 10)
 react
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-backend 'lsp ruby-version-manager 'rbenv ruby-test-runner 'rspec ruby-highlight-debugger-keywords t)
 ruby-on-rails
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-enable-smart-eshell t)
 (spell-checking :variables ispell-program-name "aspell" ispell-dictionary "en_US")
 spotify
 (sql :variables sql-capitalize-keywords t)
 syntax-checking treemacs
 (version-control :variables version-control-diff-side 'left version-control-global-margin t)
 yaml)
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
No backtrace available

**Comment by duianto** [comment]
There's a pending PR with a possible fix:
[version-control] Load SPC g v keys on startup #13561

### Cause
The `SPC g v` key bindings only appeared when a `vc` buffer had been opened.

Because the key bindings are defined in the `version-control/init-vc` functions, `:config` section:
https://github.com/syl20bnr/spacemacs/blob/d0f5477c323ef6600e29d22b75d876c49916b3f4/layers/%2Bsource-control/version-control/packages.el#L33

Moving them to the `:init` section, loads them when when Spacemacs starts.

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
[version-control] Load SPC g v keys on startup #13561

**Comment by wminshew** [comment]
great, believe it's fixed thank you
