### ISSUE TITLE
Significant lag in `helm-swoop` due to fuzzy matching

### ISSUE THREAD

**Issue by danielwuz** [syl20bnr/spacemacs#1348]
I noticed an obvious delay in `helm-swoop` with fuzzy matching on, I believe related to the fuzzy matching feature we recently enabled.

To reproduce this, try `helm-swoop` for key word "fuzzy" in spacemacs/packages.el .

**Comment by tuhdo** [comment]
The fuzzy matching enabled is for built-in Helm commands, not `helm-swoop`. You can see it [here](https://github.com/syl20bnr/spacemacs/commit/431666823eb30aaafc85028f499574ce7264a800#diff-2dc8c6706748b706747e21bac4624b85R1279). Try disabling if the issue disappears but I don't think it will. On the other hand, you may want to look at this emergency fix: https://github.com/syl20bnr/spacemacs/pull/1345.

**Comment by ralesi** [comment]
This might also be due to the swoop setting change made recently to prefer color over speed.

**Comment by danielwuz** [comment]
You're right. I think this issue is related to my local OS. Thanks!
