### ISSUE TITLE
[pyls] pyls fails to start with No module named pyls

### ISSUE THREAD

**Issue by Zlopez** [syl20bnr/spacemacs#13493]
#### Description :octocat:
pyls fails to start with No module named pyls although it's installed and started from .local/bin/pyls

#### Reproduction guide :beetle:
- Start Emacs (with pyls installed)
- Open any python file

*Observed behaviour:* :eyes: :broken_heart:
pyls can't be started

*Expected behaviour:* :heart: :smile:
pyls server starts without issue

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. acdb59767)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible systemd html javascript rust yaml python
         (auto-completion :variables auto-completion-enable-snippets-in-popup t)
         emacs-lisp git markdown multiple-cursors org lsp helm spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LCMS2

#### Backtrace :paw_prints:
```
Traceback (most recent call last):
  File "/home/zlopez/.local/bin/pyls", line 6, in <module>
    from pyls.__main__ import main
ModuleNotFoundError: No module named 'pyls'
```

**Comment by beyondpie** [comment]
Is that because of the 'PATH' issue or PYTHON related PATH issue, that Emacs cannot find your program? I didn't face this.

**Comment by Zlopez** [comment]
I'm not sure, but from the backtrace it apparently starting the correct binary. And it worked in the past.

**Comment by beyondpie** [comment]
Then it might be the issue of pyls?  I now use msplys, not sure about the latest pyls.

**Comment by Zlopez** [comment]
It looks like the pyls has some issues with python 3.8. I tried to start it manually using system python interpreter and got:
```
Traceback (most recent call last):
  File ".local/bin/pyls", line 5, in <module>
    from pyls.main import main
  File "/home/zlopez/.local/lib/python3.8/site-packages/pyls/main.py", line 65
    print '%s%s' % ('    ' * indent, name)
          ^
SyntaxError: invalid syntax
```

**Comment by Zlopez** [comment]
I solved this by switching back to default anaconda-mode, which works for me.

**Comment by beyondpie** [comment]
@Zlopez 
The error you got seems to be the old python 2.7 format, which should not be the issue of python3.8. 

I'm not sure how you install pyls, and it should support python > 3.0; so you can reinstall pyls in a python >= 3.0 env (like python3). In the meanwhile, check your default  "python" (it might point to python2.7?).
 
Or you can use python 2.7 env to install pyls, and find a way (if you use conda , and activate a python 3.0 env, I'm not if it will be affected, possibly) to use python 2.7 to run it.

**Comment by beyondpie** [comment]
@Zlopez 
I check the github of pyls, and it supports both python 2.7 and python 3.5+.
So I think your error might be: you install pyls with python 2.7. But when you open a .py file, you are actually in a python3.0 env ?

**Comment by Zlopez** [comment]
@beyondpie 
I installed the pyls with `pip install --user` and my default python interpreter is python 3.8 and I don't have python 2.7 in system at all. So I don't understand what is happening. But at least the code completion working with anaconda-mode, so I'm happy with it.

**Comment by avatar-lavventura** [comment]
@Zlopez I keep getting `ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.`
