### ISSUE TITLE
How to completely remove Spacemacs?

### ISSUE THREAD

**Issue by FilipMiletic** [syl20bnr/spacemacs#1349]
Is there anyway to completely remove Spacemacs and all packages it installed.

**Comment by tuhdo** [comment]
Simply delete your `~/.emacs.d`. Solved.

**Comment by eksperimental** [comment]
any way to disabled it a runtime?

**Comment by chrisbarrett** [comment]
Nope.

**Comment by eksperimental** [comment]
@chrisbarrett thank you fro your answer

**Comment by ickma** [comment]
thanks

**Comment by sergeyklay** [comment]
Thank you

**Comment by mohamed-fardin-khan** [comment]
thank you so much

**Comment by mattthhh** [comment]
I installed spacemacs on Windows and wanted the minimal config but i missed, and now when i removed `.emacs.d` and i reinstall spacemacs, it saved that i wants the full config. How can i reset spacemacs entirely?

**Comment by fnussbaum** [comment]
@mattthhh Try deleting the `.spacemacs` file in your home folder as well.

**Comment by mattthhh** [comment]
> @mattthhh Try deleting the `.spacemacs` file in your home folder as well.

There is no `.spacemacs` in home folder in Windows :'(

**Comment by mattthhh** [comment]
> @mattthhh Try deleting the `.spacemacs` file in your home folder as well.

Oh I found it, it's not actually in my home folder, but in `$HOME\AppData\Romaing` same path that contains .emacs.d
