### ISSUE TITLE
New encryption shortcuts clash with Evernote layer

### ISSUE THREAD

**Issue by choffee** [syl20bnr/spacemacs#13496]
#### Description :octocat:
New encryption shortcuts clash with Evernote layer

This commit added some new shortcuts under a-e which clashes with the evernote layer ones.
https://github.com/syl20bnr/spacemacs/commit/1055baafa29ed89f7658604d91c92067763416fc

#### Reproduction guide :beetle:
- Start Emacs
- enable evernote layer

*Observed behaviour:* :eyes: :broken_heart:
Warning (initialization): An error occurred while loading ‘/home/john/.emacs.d/init.el’:

error: Key sequence a e s r starts with non-prefix key a e s

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
*Expected behaviour:* :heart: :smile:
Clean startup :)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. acdb59767)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(perl5
 (elixir :variables elixir-backend 'lsp elixir-ls-path "~/unstable/elixir-ls/release")
 nginx csv vimscript rust react helm
 (auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip t)
 calendar c-c++
 (colors :variables colors-enable-rainbow-identifiers nil)
 (clojure :variables clojure-enable-linters
          '(clj-kondo joker)
          clojure-enable-fancify-symbols t clojure-enable-sayid t)
 dap dash deft docker evernote emacs-lisp emoji games git github gtags haskell ibuffer markdown mu4e multiple-cursors
 (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t org-journal-enable-agenda-integration t org-journal-dir "~/org/journal/daily" org-journal-file-format "%Y-%m-%d")
 finance git
 (go :variables go-use-gometalinter t go-backend 'lsp go-format-before-save t go-tab-width 4 godoc-at-point-function 'godoc-gogetdoc gofmt-command "goimports")
 lsp html ipython-notebook
 (javascript :variables javascript-backend 'lsp)
 node lua typescript pandoc pass puppet prettier python ranger
 (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'rvm)
 (rcirc :variables rcirc-enable-znc-support t)
 restclient search-engine semantic
 (shell :variables shell-default-shell 'eshell)
 shell-scripts syntax-checking spell-checking spacemacs-purpose speed-reading spotify systemd terraform
 (typescript :variables typescript-backend 'lsp)
 themes-megapack treemacs vagrant version-control vinegar xkcd yaml vue
 (wakatime :variables wakatime-api-key "f3e99874-bb3f-4560-9d79-914d296eb1f1" wakatime-cli-path "/home/john/.local/bin/wakatime")
 aws jmc-org jmc-mu4e)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by choffee** [comment]
Hrumph, /me goes to change wakatime api key....

**Comment by jr0cket** [comment]
Sorry, didnt know `SPC a e` was already taken.  I did ask for feedback on the right keybindings to use in #13319

The alternative key binding for Easy PG I suggested was `SPC E`.
Or to keep it in applications, the key binding `SPC a g` could be used and labelled `gpg`.

Is there any way to see a list key bindings under `SPC a` that are used in layers.  I assume some sort of search in the git project.

/cc @smile13241324

**Comment by smile13241324** [comment]
Looks like we have some conflicts in the global bindings from various layers. I have made this list from helm, scanning the bindings in all the README.org files in the layer directory.
```
+chat/jabber/README.org:31:| ~SPC a j~
+chat/erc/README.org:107:| ~SPC a i~  ----> Conflict
+chat/rcirc/README.org:235:| ~SPC a i~  ----> Conflict (maybe use I)
+chat/slack/README.org:69:| ~SPC a C~
+emacs/org/README.org:358:| ~SPC a o~
+email/gnus/README.org:146:| ~SPC a g~
+email/mu4e/README.org:67:| ~SPC a M~
+email/notmuch/README.org:100:| ~SPC a N~
+fun/emoji/README.org:38:| ~SPC a E~
+fun/games/README.org:39:| ~SPC a G~
+fun/xkcd/README.org:34:| ~SPC a x~
+lang/ipython-notebook/README.org:73:bound to ~SPC a y~
+music/pianobar/README.org:56:| ~SPC a m~  ----> Conflict
+music/spotify/README.org:35:| ~SPC a m~ -----> Conflict (maybe use P)
+readers/deft/README.org:62:| ~SPC a n~
+readers/elfeed/README.org:112:| ~SPC a f~
+readers/speed-reading/README.org:26:| ~SPC a R~
+readers/dash/README.org:26:| ~SPC a z~
+tools/bm/README.org:36:| ~SPC a b~
+tools/chrome/README.org:74:| ~SPC a F~
+tools/command-log/README.org:28:| ~SPC a L~
+tools/docker/README.org:79:| ~SPC a D~
+tools/geolocation/README.org:119:| ~SPC a w~ ----> Layer uses two prefixes should be changed to use w only
+tools/geolocation/README.org:120:| ~SPC a W~ ----> Same
+tools/kubernetes/README.org:47:| ~SPC a K~
+tools/pass/README.org:28:| ~SPC A p~ -----> Layer is using wrong menu should use a instead of A
+tools/prodigy/README.org:38:| ~SPC a S~
+tools/quickurl/README.org:28:| ~SPC a Q~
+tools/ranger/README.org:128:| ~SPC a r~
+tools/ranger/README.org:129:| ~SPC a d~
+tools/shell/README.org:294:| ~SPC a s~
+tools/transmission/README.org:62:| ~SPC a t~
+tools/vagrant/README.org:21:- ~SPC a V~
+web-services/evernote/README.org:58:| ~SPC a e~
+web-services/search-engine/README.org:56:| ~SPC a /~
```
I think we should move Easy pg to ~SPC a Y~ this would use the y from easy pg as memonic as e and s is already taken.

**Comment by smile13241324** [comment]
@choffee @jr0cket I have moved the bindings accordingly. The global application bindings should not longer clash. As we are getting more and more members in that group we will have to eventually group them based on categories like it has been done for music and irc. But this is something for a different PR.

For now please double check on latest develop and close this issue when the conflicts are gone.

**Comment by choffee** [comment]
That has fixed it for me. Thank you.
