### ISSUE TITLE
Refactor SPC m a key bindings - running out of keys to use

### ISSUE THREAD

**Issue by practicalli-john** [syl20bnr/spacemacs#13503]
As discussed on #13496 there are a large number of applications added to Spacemacs as layers and sensible mnemonic keybindings are hard to come by and there are some conflicts already.

The proposal is to group applications by their categories, based on the directory they are contained in under layers
- chat
- email
- fun 
- music  (already exists)
- readers
- tools
- security
- web-services

Here is what the new keybindings would be based on categories.  This shows the new keybindings, the path and name of the layer and the current keybindings
```
 ~SPC a c j~ +chat/jabber ~SPC a j~
 ~SPC a c i~ +chat/erc  ~SPC a i~  ---> No conflict: different sub level bindings
 ~SPC a c i~ +chat/rcirc  ~SPC a i~ --> No conflict: different sub level bindings
 ~SPC a c s~ +chat/slack ~SPC a C~
 ~SPC a e g~ +email/gnus  ~SPC a g~
 ~SPC a e m~ +email/mu4e ~SPC a M~
 ~SPC a e n~ +email/notmuch  ~SPC a N~
 ~SPC a f e~ +fun/emoji ~SPC a E~
 ~SPC a f g~ +fun/games ~SPC a G~
 ~SPC a f x~ +fun/xkcd ~SPC a x~
 ~SPC a m~ +music/pianobar ~SPC a m~ --> No conflict: different sub level bindings
 ~SPC a m~ +music/spotify ~SPC a m~  --> No conflict: different sub level bindings
 ~SPC a r z~ +readers/dash ~SPC a z~
 ~SPC a r n~ +readers/deft ~SPC a n~
 ~SPC a r f~ +readers/elfeed  ~SPC a f~
 ~SPC a r s~ +readers/speed-reading ~SPC a R~
 ~SPC a t b~ +tools/bm ~SPC a b~
 ~SPC a t c~ +tools/chrome ~SPC a F~
 ~SPC a t d~ +tools/docker ~SPC a D~
 ~SPC a t g~ +tools/geolocation  ~SPC a w~ --> Duplicate: move
 ~SPC a t g~ +tools/geolocation  ~SPC a W~ --> Duplicate: remove
 ~SPC a t j~ +lang/ipython-notebook (move layer to tools, rename to Jupiter Notebook)
 ~SPC a t k~ +tools/kubernetes ~SPC a K~
 ~SPC a t l~ +tools/command-log ~SPC a L~
 ~SPC a t o~ +tools/prodigy ~SPC a S~
 ~SPC a t p~ +tools/pass ~SPC A p~ --> Layer using A rather than a
 ~SPC a t q~ +tools/quickurl ~SPC a Q~
 ~SPC a t r~ +tools/ranger  ~SPC a r~  --> Duplicate: move
 ~SPC a t r~ +tools/ranger  ~SPC a d~ --> Duplicate: remove
 ~SPC a t s~ +tools/shell  ~SPC a s~
 ~SPC a t t~ +tools/transmission ~SPC a t~
 ~SPC a t v~ +tools/vagrant ~SPC a V~
 ~SPC a w e~ +web-services/evernote ~SPC a e~
 ~SPC a w /~ +web-services/search-engine ~SPC a /~
```
As Org-mode is in Emacs, keep it at the top level
``` ~SPC a o~ +emacs/org  ~SPC a o~```

A security category, `SPC a s` could be used for Easy PG, `SPC a s e` and pass, `SPC a s p`.

Python / Jupiter notebook is under the lang tree layer, but unclear why this is the case.  Unless its dependent on the Python layer (no mention in the documentation) then seems more appropriate to move it to the tools path in layers and tools category.

Obviously this is a proposal and open to discussion as I appreciate changing keybindings is a disruption to workflow.

I am willing to work on a PR for such a change, if their is positive feedback.

Thank you.
/cc @smile13241324

**Comment by jr0cket** [comment]
A further refinement would be to create a virtualization category, `SPC a v`, for the docker, kubernetes and vagrant layers.

**Comment by smile13241324** [comment]
@jr0cket I have moved the conda and ipython-layer to the tools category as they do not provide any kind of syntax highlighting, they rather provide abstractions over external process calls, so this should be covered. I have also fixed the geolocation layer and the pass layer.

I would however suggest some changes to the proposed keybindings:
```
 ~SPC a c j~ +chat/jabber ~SPC a j~
 ~SPC a c i~ +chat/erc  ~SPC a i~  ---> No conflict: different sub level bindings
 ~SPC a c i~ +chat/rcirc  ~SPC a i~ --> No conflict: different sub level bindings
 ~SPC a c s~ +chat/slack ~SPC a C~
 ~SPC a e g~ +email/gnus  ~SPC a g~
 ~SPC a e m~ +email/mu4e ~SPC a M~
 ~SPC a e n~ +email/notmuch  ~SPC a N~
 ~SPC a f e~ +fun/emoji ~SPC a E~
 ~SPC a f g~ +fun/games ~SPC a G~
 ~SPC a f x~ +fun/xkcd ~SPC a x~
 ~SPC a m~ +music/pianobar ~SPC a m~ --> No conflict: different sub level bindings
 ~SPC a m~ +music/spotify ~SPC a m~  --> No conflict: different sub level bindings
 ~SPC a r z~ +readers/dash ~SPC a z~
 ~SPC a r d~ +readers/deft ~SPC a n~
 ~SPC a r e~ +readers/elfeed  ~SPC a f~
 ~SPC a r s~ +readers/speed-reading ~SPC a R~
 ~SPC a t b~ +tools/bm ~SPC a b~
 ~SPC a t c~ +tools/chrome ~SPC a F~
 ~SPC a t d~ +tools/docker ~SPC a D~
 ~SPC a t g~ +tools/geolocation  ~SPC a w~ --> Duplicate: move
 ~SPC a t i~ +lang/ipython-notebook (move layer to tools, rename to Jupiter Notebook)
 ~SPC a t k~ +tools/kubernetes ~SPC a K~
 ~SPC a t l~ +tools/command-log ~SPC a L~
 ~SPC a t p~ +tools/prodigy ~SPC a S~
 ~SPC a t P~ +tools/pass ~SPC A p~ --> Layer using A rather than a
 ~SPC a t q~ +tools/quickurl ~SPC a Q~
 ~SPC a t r~ +tools/ranger  ~SPC a r~  --> Duplicate: move
 ~SPC a t s~ +tools/shell  ~SPC a s~
 ~SPC a t t~ +tools/transmission ~SPC a t~
 ~SPC a t v~ +tools/vagrant ~SPC a V~
 ~SPC a w e~ +web-services/evernote ~SPC a e~
 ~SPC a w /~ +web-services/search-engine ~SPC a /~
```
For non layer bindings, so all thats either bound by +emacs layers or within the core I would still keep on the top level, this is `SPC a`.

About that new category of virtualisation, here I am not sure how much work it is to have a new category added to the `#+TAGS` flag in the README files. 

@duianto  @JAremko what's your opinion about the proposed key bindings? The general idea is to obtain more memonic keybindings for the `SPC a` bindings without having key conflicts between various layers.

**Comment by smile13241324** [comment]
I am not sure whether a "security" category is not too much already. Easy pg comes from the core and should therefore be bound to the top level, to be consistent, this would then leave the security category with only the pass layer which is does not justify it's own category.

**Comment by duianto** [comment]
>The general idea is to obtain more memonic keybindings for the SPC a bindings without having key conflicts between various layers.

👍

**Comment by jr0cket** [comment]
I will start a PR for this over the weekend.

I like to avoid PRs that go across layers, however, that would lead to nearly 30 very similar PR's.  I suggest doing a PR for each category, so 5 PR's in total.  This makes it easier to roll back specific parts should there be an issue.

Thank you.

**Comment by smile13241324** [comment]
Sounds good, when you need assistance or have questions just drop me a line :)

**Comment by jr0cket** [comment]
@smile13241324 Took longer to get to these key binding refactor due to illness and have been catching up over the last few weeks.  I'll spread the changes over a few pull request to make them easier to review.

**Comment by smile13241324** [comment]
Sounds good, I'll be happy to review.

**Comment by jr0cket** [comment]
@smile13241324 
Changing the applications under layer/+chat to `SPC a c` conflict with the `ac` keybinding for `calc-dispatch`, which is defined on line 181 of `layers/+spacemacs/spacemacs-defaults/keybindings.el`

Should the keybinding for calc-dispatch be changed, or a different sub-menu character be used for the chat applications?

**Comment by smile13241324** [comment]
@jr0cket 
Sounds good, lets move it to `SPC a *`

**Comment by pataquets** [comment]
I'm using `simplenote2` package and I have a WIP layer which I would like to contribute. I'm still figuring out which keybindings would be appropriate for it (I'm using `a n(otes) *` for commands), but since there is also an `evernote` layer using `a w e *`, I'm a bit unsure of how to proceed.
My guess is that there should be a `a n *` for note-taking apps, with Evernote and Simplenote children, so there will be `a n e *` for Evernote and `a n s *` for Simplenote, which would leave room for other services. Any advice and feedback will be much appreciated.

**Comment by practicalli-john** [comment]
@pataquets it would seem that simplenote is an external service connected to via an API, as with Evernote.
Therefore it seems logical to include key bindings under `SPC a w s`.

This issue is quite old and was resolved a long time ago.  Suggest creating an issue for this new feature and describing it's intended implementation.

Thank you.
