### ISSUE TITLE
dotspacemacs-smart-closing-parenthesis nil not working editing .spacemacs

### ISSUE THREAD

**Issue by singpolyma** [syl20bnr/spacemacs#13501]
#### Description :octocat:

dotspacemacs-smart-closing-parenthesis nil but pressing ) in insert mode before an existing ) still passed over while editing .spacemacs

#### Reproduction guide :beetle:
- Start Emacs
- SPC f e d
- Check that dotspacemacs-smart-closing-parenthesis is set nil
- i)ESCi)

*Observed behaviour:* :eyes: :broken_heart:

Only one ) is present

*Expected behaviour:* :heart: :smile:

Two ) are present, as I typed two of them.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. acf5ce87f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(haskell helm emacs-lisp git markdown org
			(shell :variables shell-default-position 'full)
			version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-number-of-arguments #f(compiled-function (ad--addoit-function string forward

**Comment by singpolyma** [comment]
This seems to fix it:

    	(setq-default sp-autoskip-closing-pair nil)

**Comment by lebensterben** [comment]
Please use `develop` branch instead.
