### ISSUE TITLE
Finding a non-existent directory does not create that directory

### ISSUE THREAD

**Issue by jgrey4296** [syl20bnr/spacemacs#13500]
#### Description :octocat:
Calling variations of helm-find-files to find a non-existent directory does
not create a new directory, but a buffer.

This is a limitation of spacemacs/helm-find-files-windows which is
*silently* bound to RET in helm-find-files-map.
So when you look in your action list (C-z), the function that you expect find files
to default to is still helm-find-file-or-marked.

#### Reproduction guide :beetle:
- Start Emacs
- SPC f f
- Find a non-existent directory: "~/i_dont_exist/"

*Observed behaviour:* :eyes: :broken_heart:
A Buffer will be created called "i_dont_exist"
And emacs will suggest you create a directory using "make-directory" in the minibuffer

*Expected behaviour:* :heart: :smile:
Emacs should ask to create a new directory, in the way helm-find-file-or-marked does.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b5f0eb5f7)
- Graphic display: nil
- Distribution: spacemacs-base
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ocaml jg-spacemacs-main-layer
       (syntax-checking :variables syntax-checking-enable-tooltips nil)
       (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by jr0cket** [comment]
When selecting a new directory and file name using `SPC f f`, the current behavior asks to create the new directory once `SPC f s` is used to save the current buffer to a file in the new directory.
This makes sense to me as I only want to create a new directory if the file is saved.

When using `SPC f f` and typing a new name to create a new directory, there is a message displayed in the mini-buffer with the command to create the directory straight away.  I prefer this approach rather  than to have to reply to a prompt, especially if I do not know if I am going to save the file yet.

**Comment by duianto** [comment]
Confirmed, there's an issue when only a new directory is entered.

@jr0cket You mentioned both a new directory and a file name when using `SPC f f`.

And that works, ex: `SPC f f` `~/new_dir/new_file` `RET`
opens a new buffer with the name: `new_file`
and the minibuffer shows:
>Use M-x make-directory RET RET to create the directory and its parents

Saving the buffer: `SPC f s`
shows:
>Directory ‘c:/Users/username/new_dir/’ does not exist; create? (y or n)

Pressing: `y`
shows:
>Wrote c:/Users/username/new_dir/new_file

---

jgrey4296 only mentioned adding a new directory.

### In Spacemacs
`SPC f f` `~/i_dont_exist/` (including the trailing slash: `/`) `RET`

Creates a buffer with the name: `i_dont_exist`

If one tries to save the buffer: `SPC f s`
Then a prompt appears:
>Directory 'c:/Users/username/i_dont_exist/' does not exist; create? (y or n)

Pressing: `y`
shows:
> changed on disk; really edit the buffer? (y, n, r, or C-h)

the buffer name seems to be missing, there's only a space before the word: `changed`

Pressing: `y`
shows:
>basic-save-buffer-2: Opening output file: No such file or directory, c:/Users/username/i_dont_exist/

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a0b099b54)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log dap emacs-lisp git helm html imenu-list javascript
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors nim
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'left)
            spell-checking
            (syntax-checking :variables syntax-checking-enable-by-default nil)
            (treemacs :variables treemacs-use-scope-type 'Perspectives)
            version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

### Without Spacemacs, just Emacs and Helm
`M-x helm-find-files` `~/i_dont_exist/` (including the trailing slash: `/`) `RET`

Shows a prompt:
>Create directory `~/i_dont_exist/'? (y or n)

Pressing: `y`
opens a new helm find files prompt asking for a file name in the new directory: `~/i_dont_exist/`
