### ISSUE TITLE
Emacs window goes black when exiting the last window in a perspective

### ISSUE THREAD

**Issue by posobin** [syl20bnr/spacemacs#13517]
#### Description :octocat:
On MacOS emacs window goes black when quitting the last window in the perspective

#### Reproduction guide :beetle:
- Start Emacs
- Maximize the window
- (optionally, not necessary but may be relevant) create new persepctive with `<SPC>lw2`
- Press `:q<Enter>`

*Observed behaviour:* :eyes: :broken_heart:
Emacs window goes black, doesn't respond to key presses.
To get it back, press `:`, or send SIGUSR2 to the process.

If emacs is not full-screen, it disappears, clicking on the emacs icon in the dock doesn't do anything, calling it from `CMD-Space` shows the window which is frozen and not reacting to key presses. Pressing `:` unfreezes it.

*Expected behaviour:* :heart: :smile:
Some kind of message asking whether I want to quit emacs or something like that? Not sure.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3a1bfc2a9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript sql auto-completion emacs-lisp git helm markdown multiple-cursors org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs clojure html spacemacs-evil)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by duianto** [comment]
It might be relevant
- how Emacs was maximized
  - `SPC T M`
  - or `shift` `option` clicking the green window button
source: https://apple.stackexchange.com/a/268426

- how Emacs was installed
Unless your seeing the same result with several (or all) installation methods, then you might want to try one of the other methods listed here: https://github.com/syl20bnr/spacemacs/tree/develop#macos

I don't have a mac to test with, but in both PopOS and Windows, Emacs closes after pressing `:q` `RET`

#### System Info (click to expand)
<details><summary>
PopOS 20.04
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1660527cd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion command-log emacs-lisp fasd git helm lsp markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("~/org/notes.org"))
                 ranger
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1660527cd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 emacs-lisp git helm html javascript lsp
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org"))
 (python :variables)
 ranger
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>
