### ISSUE TITLE
Gruvbox's themes not working. Can't find autothemer.

### ISSUE THREAD

**Issue by mario-bermonti** [syl20bnr/spacemacs#13515]
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>
#### Description :octocat:
I tried setting gruvbox-light-soft to be one of the default themes (using dotspacemacs-themes), but
when I start spacemacs I it can't load it and defaults to spacemacs-dark theme.

It works as expected if I select the gruvbox-light-soft theme using SPC T s.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
It doesn't load gruvbox-light-soft. It throws an error message (see traceback)
because it can't find autothemer.

*Expected behaviour:* :heart: :smile:
It should load the specified theme

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 8c0b8c344)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv javascript html
     (python :variables python-enable-yapf-format-on-save t python-test-runner
             '(pytest nose))
     helm auto-completion better-defaults emacs-lisp git markdown
     (org :variables org-enable-github-support t org-enable-reveal-js-support t org-babel-python-command "python3")
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control themes-megapack pandoc)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
(Spacemacs) Warning: An error occurred while applying the theme "gruvbox-light-soft", fallback on theme "spacemacs-dark". 
Error was: (file-missing Cannot open load file No such file or directory autothemer)
(Spacemacs) Warning: Please check the value of "dotspacemacs-themes" in your dotfile or open an issue 
so we can add support for the theme "gruvbox-light-soft".
```

**Comment by jr0cket** [comment]
Works on `develop` branch of Spacemacs / Emacs 26.3

Reproduction guide:
- Add `gruvbox-light-soft` to `dotspacemacs-themes` list
- Restart Spacemacs with `SPC q r`
- Spacemacs downloads `gruvbox-theme` package
- Spacemacs automatically switches to theme

**Comment by mario-bermonti** [comment]
Thanks for your answer. I will look into the `develop` branch. Does that mean that all users should start using the `develop` branch then?

**Comment by deepaknayan** [comment]
> Works on `develop` branch of Spacemacs / Emacs 26.3
> 
> Reproduction guide:
> 
>     * Add `gruvbox-light-soft` to `dotspacemacs-themes` list
> 
>     * Restart Spacemacs with `SPC q r`
> 
>     * Spacemacs downloads `gruvbox-theme` package
> 
>     * Spacemacs automatically switches to theme

Worked for me. Pretty useful. (On Linux Mint!)

**Comment by xahon** [comment]
@mario-bermonti why did you closed the issue when master is still not working as expected?

**Comment by mario-bermonti** [comment]
@xahon  After asking in the spacemacs’ gitter chat, everyone recommended using the dev branch as the standard/best practice. And this issue was solved there, so it made little sense to me to keep the issue open here if issues are really only being worked on in the dev branch. 

But I’m happy to reopen the issue if it should be kept open.

**Comment by xahon** [comment]
@mario-bermonti it is not a solution. In fact,

**Comment by mario-bermonti** [comment]
@xahon  I understand and appreciate your explanation. I will reopen until it is resolved in this branch.

**Comment by lebensterben** [comment]
It's not likely be resolved on master branch.
I'm closing this.
