### ISSUE TITLE
LSP Server does not work anymore since update on 19 April 2020.

### ISSUE THREAD

**Issue by MrMic** [syl20bnr/spacemacs#13512]
#### Description :octocat:
LSP server does not work anymore with last update on 19 April 2020
It just works fine before.
It is broken with all languages I work with: Dart, Typescript ...

#### Reproduction guide :beetle:
- Start Emacs
- Open a file and expect that LSP server start but ... No!

*Observed behaviour:* :eyes: :broken_heart:
Part of message:
=> LSP :: There are no language servers supporting current mode dart-mode ....

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b227a68c7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(multiple-cursors emoji finance evil-snipe imenu-list lsp
                  (osx :variables osx-option-as 'none)
                  (html :variables web-fmt-tool 'prettier css-enable-lsp t less-enable-lsp t scss-enable-lsp t)
                  (javascript :variables javascript-import-tool 'import-js node-add-modules-path t javascript-backend 'lsp javascript-fmt-tool 'prettier javascript-fmt-on-save t js2-basic-offset 2 js-indent-level 2)
                  (typescript :variables typescript-backend 'lsp typescript-fmt-tool 'prettier typescript-fmt-on-save t typescript-linter 'tslint)
                  react
                  (yaml :variables yaml-enable-lsp t)
                  helm
                  (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
                  better-defaults emacs-lisp git docker
                  (python :variables python-backend 'lsp)
                  (conda :variables conda-anaconda-home "/usr/local/Caskroom/miniconda/base")
                  markdown
                  (org :variables org-enable-reveal-js-support t)
                  (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
                  spell-checking syntax-checking version-control themes-megapack twitter
                  (go :variables go-tab-width 4 go-use-gometalinter t gofmt-command "goimports")
                  (treemacs :variables treemacs-use-filewatch-mode t treemacs-use-follow-mode t treemacs-use-collapsed-directories 3)
                  (ranger :variables ranger-show-preview t)
                  (dart :variables dart-backend 'lsp lsp-dart-sdk-dir "/Users/mic/WebstormProjects/Flutter/flutter/bin/cache/dart-sdk/" dart-server-sdk-path "/Users/mic/WebstormProjects/Flutter/flutter/bin/cache/dart-sdk/" dart-server-format-on-save t lsp-enable-on-type-formatting t dart-server-format-on-save t))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by MrMic** [comment]
It seems to work with Typescript and JavaScript, but with Dart / Flutter it is still failing.
Disappointing, because it works fine last week and before.
If anyone can fix that or give me a tip on how to fix it.
I have changed anything in my configuration.

**Comment by yyoncho** [comment]
This will be fixed by https://github.com/syl20bnr/spacemacs/pull/13518 . Current workaround is to add lsp-dart to additional packages.

**Comment by ericdallo** [comment]
Maybe we should think in some better message on minibuffer when these kinds of migrations happens...
