### ISSUE TITLE
Prettier layer not working? Test fail

### ISSUE THREAD

**Issue by bitVivAZ** [syl20bnr/spacemacs#13528]
Good day everyone,

I tried installing prettier today using the instruction given at the [layers wiki ](https://develop.spacemacs.org/layers/+tools/prettier/README.html) however everytime I reload the configuration file it keeps failing. 

Note that I'm really new to this, so sorry if I'm doing something really obviously wrong.

![Screenshot from 2020-04-26 12-49-41](https://user-images.githubusercontent.com/21178318/80305327-6d905b80-87bc-11ea-9288-ad575fb8595f.png)

**Comment by CosmicPegasis** [comment]
Hey I'm really new to Spacemacs too, how did you fix it?

**Comment by CosmicPegasis** [comment]
TLDR: Switch to develop layer of Spacemacs
For anyone reading this in the future I fixed this issue by switching to the develop branch of spacemacs.
In the command line do:
`cd ~/.emacs.d
git checkout develop`

After this restart spacemacs go into .spacemacs config file and try to rebuild it.
It might show some errors, read the test case and fix them.
Then add the prettier layer as shown in the wiki.
