### ISSUE TITLE
Kakoune mode / editing style

### ISSUE THREAD

**Issue by lboklin** [syl20bnr/spacemacs#13521]
Using this: https://github.com/jmorag/kakoune.el

It's not mature enough to contend with emacs/evil/hybrid modes, but maybe it could be at least an option?

Kakoune is a nice and fast editor and I like to use it when loading spacemacs is just overkill (it usually takes a couple seconds to load, or dozens even for heavier layers). Being able to edit similarly across both editors would be nice and ease the friction.

**Comment by gdkrmr** [comment]
Have you tried using `emacs` as a server? Then you use `emacsclient` to connect to an already running server and the editor window appears instantly.

**Comment by lboklin** [comment]
Yes. That doesn't help when I want to quickly open a source file in a big project with a fat layer.

**Comment by EPonyA** [comment]
There is [quantitative data ](https://delapouite.github.io/kakoune-tv/#4d1a7a05b8cb3409320001b4) suggesting that Kakoune is a fundamentally superior modal editing model to Vim. I think serious Kakoune emulation in Spacemacs would future-proof it at worst, or make it cutting edge at best. However, that would be very ambitious. Currently, VS Code has the only reasonable implementation of Kakoune in an IDE that I am aware of.

**Comment by lebensterben** [comment]
closing due to lack of interest.
PR is still welcomed.
