### ISSUE TITLE
Company-capf does not show up in php file

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#13524]
#### Description :octocat:
Company-capf does not show up in php file.
I m using lsp backend and intelephense.

My full spacemacs config is on this repo : https://gitlab.com/phenix-factory/config-spacemacs

#### Reproduction guide :beetle:
- Start Emacs
- Open a php file
- Type some already existing variable

*Observed behaviour:* :eyes: :broken_heart:
Company does'nt provide completion at all.
But I can for it via company-capf command

*Expected behaviour:* :heart: :smile:
company working

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1f6e39ea8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-idle-delay 0.2)
 helm emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 markdown csv
 (org :variables org-enable-reveal-js-support t)
 treemacs
 (erc :variables erc-server-list
      '(("irc.freenode.net" :port "6667" :ssl t :nick "phenix_spip")))
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom multi-term-program "/usr/bin/zsh")
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary nil enable-flyspell-auto-completion t)
 syntax-checking shell-scripts
 (php :variables php-backend 'lsp)
 restclient
 (sql :variables sql-capitalize-keywords t)
 (html :variables css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t web-fmt-tool 'prettier)
 lsp dap
 (javascript :variables javascript-fmt-tool 'prettier javascript-import-tool 'import-js javascript-backend 'lsp)
 (vue :variables vue-backend 'lsp)
 prettier import-js
 (node :variables node-add-modules-path t)
 lua imenu-list yaml finance colors dash multiple-cursors unicode-fonts
 (version-control :variables version-control-global-margin t shell-default-term-shell "/bin/bash")
 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp/" mu4e-enable-notifications t mu4e-enable-mode-line t mu4e-use-maildirs-extension t)
 (python :variables python-backend 'lsp python-lsp-server 'pyls python-formatter 'black python-format-on-save t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LCMS2

**Comment by AdeAttwood** [comment]
I think this is coming from `php-extras` and the `php-extras-company`. It' always completes with the default built-in php functions. I think this can be disabled when using the LSP backend as the built-in functions come up in `company-capf` provided by the LSP.

I don't know what other functionality we will be missing by disabling this package. By looking at the README all the functionality is provided by LSP apart from [php-extras-insert-previous-variable](https://github.com/arnested/php-extras#php-extras-insert-previous-variable)

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/php/packages.el#L23

``` diff
- (php-extras :location (recipe :fetcher github :repo "arnested/php-extras"))
+ (php-extras :location (recipe :fetcher github :repo "arnested/php-extras") :toggle (not (eq php-backend 'lsp)))
```

**Comment by phenix-factory** [comment]
This look like an issue, I excluded the php-extras package in my .spacemacs and lsp works a lot faster.
I have issue with laravel eloquent function that are not autocompleted, but thats all.

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Disable php-extras when the php layer backend is lsp #13916

@phenix-factory Could you test that it works as expected. If it does then you can close this issue.

**Comment by phenix-factory** [comment]
@duianto Everything works fine now.

Thanks everyone for this !
