### ISSUE TITLE
Shell indentation inconsistent with on clean install of spacemacs

### ISSUE THREAD

**Issue by SreenivasVRao** [syl20bnr/spacemacs#13525]
#### Description :octocat:
M-x shell `ls` shows inconsistent indentation.

#### Reproduction guide :beetle:
- Start Emacs
- M-x shell
- `ls` in a directory

*Observed behaviour:* :eyes: :broken_heart:
Tab spaces are inconsistent.
Comparison with emacs -q Example: https://imgur.com/a/H3AIBnc

*Expected behaviour:* :heart: :smile:
consistent indetation like emacs -q

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1f6e39ea8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by emacs18** [comment]
This is as intended by spacemacs developers when they changed default tab width from 8 to 2.
As a long time emacs user it is very disorienting for me as well for default tab with to be 2 instead of 8.  That is why I apply the following patch in my own fork of spacemacs.  You of course could set `tab-width` in your own ~/.emacs file.

```elisp
diff --git a/layers/+spacemacs/spacemacs-defaults/config.el b/layers/+spacemacs/spacemacs-defaults/config.el
index 32460923e..57041cdb5 100644

+++ b/layers/+spacemacs/spacemacs-defaults/config.el
@@ -76,7 +76,7 @@ It runs `tabulated-list-revert-hook', then calls `tabulated-list-print'."
 
 ;; use only spaces and no tabs
 (setq-default indent-tabs-mode nil
-              tab-width 2)
+              tab-width 8)
 
 ;; Text
 (setq longlines-show-hard-newlines t)
```

**Comment by SreenivasVRao** [comment]
Oh nice - this worked thanks! :)
