### ISSUE TITLE
Add org-roam layer [New Layer]

### ISSUE THREAD

**Issue by kitaev-chen** [syl20bnr/spacemacs#13536]
Org-roam is an excellent extension on org, which has doom-emacs configuration right now. Could you add a new layer to this?

Ref:
https://org-roam.readthedocs.io/en/master/installation/#spacemacs
https://org-roam.readthedocs.io/en/develop/ecosystem/

**Comment by duianto** [comment]
The second link (ecosystem) leads to a 404 page.

The org-roam `develop` branch seems to have been removed, according to this comment:
https://github.com/org-roam/org-roam/issues/590#issuecomment-626269025
>That's actually because the link you're at is for the develop branch, which is long gone.

This might be the correct page:
https://org-roam.github.io/org-roam/manual/Ecosystem.html

**Comment by kastork** [comment]
There's a person (https://www.reddit.com/user/snuffop/) in this thread (https://www.reddit.com/r/emacs/comments/f6erh0/total_noob_how_do_i_install_orgroam_in_spacemacs/) that seems to have made a start on this....

**Comment by emacs18** [comment]
I wrote this as `spacemacsdir/layers/+me/org-roam/packages.el`.  It was a while ago, so I don't remember how I wrote this.  I probably got the idea from someone and then tried to hack together based on what little I know about spacemacs config.  It seems to work for me.

Do we need a separate layer for org-roam or should we just add org-roam as another package into existing org layer?

I share this to start discussion.  If anyone is willing to take this and submit a PR, that would be great.  Otherwise I suppose I could submit a PR too.

```elisp
(defconst org-roam-packages
  '(org-roam))

(defun org-roam/init-org-roam ()
  (use-package org-roam
    :hook
    (after-init . org-roam-mode)
    :custom
    (org-roam-directory "/path/to/org-files/")
    :init
    (progn
      (spacemacs/declare-prefix "ar" "org-roam")
      (spacemacs/set-leader-keys
        "arl" 'org-roam
        "art" 'org-roam-dailies-today
        "arf" 'org-roam-find-file
        "arg" 'org-roam-graph)

      (spacemacs/declare-prefix-for-mode 'org-mode "mr" "org-roam")
      (spacemacs/set-leader-keys-for-major-mode 'org-mode
        "rl" 'org-roam
        "rt" 'org-roam-dailies-today
        "rb" 'org-roam-switch-to-buffer
        "rf" 'org-roam-find-file
        "ri" 'org-roam-insert
        "rg" 'org-roam-graph))))

```

**Comment by klochowicz** [comment]
It seems that a natural way would be expanding existing `org` layer, in the same way `org-brain` (a similar extension) has done it before. I'll have a go at it - will link the PR if I succeed :)

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
[org] Add org-roam support #14004

**Comment by komali2** [comment]
I'm not sure if I'm doing something wrong here, but I've removed my custom org-roam layer from /private, and have `org-roam` in my `dotspacemacs-configuration-layers`, and am getting the error 

    (Spacemacs) Warning: Unknown layer org-roam declared in dotfile.

I did pull from develop in my ~/.emacs.d so I'm not sure if there's another step people like me that had manually created an org-roam layer should do?

**Comment by emacs18** [comment]
org-roam is not a new layer.  Instead it is an optional new feature within exisint org layer.  Please read the documentation on org layer.

**Comment by emacs18** [comment]
Did you update ~/.spacemacs file as well?

**Comment by komali2** [comment]
I see. This also agrees with you: https://gitter.im/syl20bnr/spacemacs?at=5f88143161007f7d1b71a5d8

> don't add org-roam layer but add in the configuration layer specifty (org :variables
> org-enable-roam-support t).

**Comment by duianto** [comment]
It's understandable that it seemed like a new layer, since both the title and a label said: `New layer`

**Comment by pamrg1** [comment]
@komali2 did you also delete your custom private org-roam home-made layer?

**Comment by komali2** [comment]
> @komali2 did you also delete your custom private org-roam home-made layer?

Yup! Thanks for checking. It all works wonderfully now and has been for a few months now, on several different machines.

**Comment by pamrg1** [comment]
For noobs like me: https://philipperambert.com/Installing-Org-Roam-Bibtex-In-Spacemacs
