### ISSUE TITLE
"Important Notes" box border misaligned when using inconsolata font

### ISSUE THREAD

**Issue by iliakur** [syl20bnr/spacemacs#13534]
#### Description :octocat:
When using spacemacs with the Inconsolata font as default the "Important notes" box has strange border alignment on the left.

#### Reproduction guide :beetle:
In your config file set the default font to inconsolata:
```
dotspacemacs-default-font '("Inconsolata"
                               :size 17
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
```
- Start Emacs
- Look at home screen

*Observed behaviour:* :eyes: :broken_heart:
The left border of the "Important notes" box is not aligned at the top, bottom and at two points in the middle.

Here's a screenshot:
![screenshot-emacs-border](https://user-images.githubusercontent.com/899591/80677537-5c479780-8ab9-11ea-9871-087dd59901ce.png)

*Expected behaviour:* :heart: :smile:
The left border of the "Important notes" box is aligned.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go graphviz json html yaml python debug helm bm auto-completion emacs-lisp
    (latex :variables latex-enable-folding t latex-enable-auto-fill t)
    git markdown pdf restclient
    (erc :variables erc-enable-notifications nil)
    (org :variables org-enable-github-support t org-enable-reveal-js-support t)
    (spell-checking :variables =enable-flyspell-auto-completion= t)
    syntax-checking
    (keyboard-layout :variables kl-layout 'colemak-hnei))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
None
```
```

**Comment by duianto** [comment]
Confirmed.

```
   dotspacemacs-default-font '("inconsolata"
                               :size 10.0
                               :weight normal
                               :width normal)
```

![emacs_2020-06-12_16-27-54](https://user-images.githubusercontent.com/13420573/84517153-23f9c280-accf-11ea-9dd1-22c52ba97b00.png)


It seems to be caused because the text at the top and bottom of the Important Notes frame, is using a **bold** font.
`    uniscribe:-outline-Inconsolata-bold-normal-normal-mono-13-*-*-*-c-*-iso8859-1 (#x19F)`

while the text inside the frame, is using a normal font:
`    uniscribe:-outline-Inconsolata-normal-normal-normal-mono-13-*-*-*-c-*-iso8859-1 (#xD1)`

The font name info can be seen on line 12 in the Help buffer by pressing:
`SPC h d c` which calls `describe-char`

<details><summary>
System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5fcd84d84)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 emacs-lisp git helm html javascript lsp
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org"))
 (python :variables)
 ranger
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 themes-megapack treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by lebensterben** [comment]
I have seen other people reporting this issue and I found the way how Emacs is looking for fonts is not reliable to some use cases:

Often time people install patched fonts which contains icons and emojis mostly used for eye candies in shell peompt, mode line, etc.

Unfortunately sometimes the patched font may have the same name as the unpatched one. And the patching may not been done correctly, for example patching a non-strictly-monospaced variant of a font. So when you specify the `:family` of the font in the Emacs `fontspec`, it may ends up point to the one that's not really monospaced.

I've no idea how to fix this in script, though I manually fixed the issue.

**Comment by lebensterben** [comment]
For future references, when you set font in `dotspacemacs`, it's converted to font specification via Emacs' `font-spec` function. Then the font is located via `find-font` function.

To verify Emacs indeed find the one you want, evaluate the following:
```elisp
(find-font (font-spec :name NAME ...))
```
where `NAME` is the first element of the list of `dotspacemacs-default-font`, and `...` is any keywords their respective arguments specified in `dotspacemacs-default-font`.

So for example, the default `dotspacemacs-default-font` is
```elisp
'("Source Code Pro"
  :size 10.0
  :weight normal
  :width normal)
```
which translates to
```elisp
(find-font (font-spec :name "Source Code Pro" :size 10.0 :weight 'normal :width 'normal))
```
(Note that symbols like `'normal` should be quoted)

On my system this returns
```txt
#<font-entity ftcrhb ADBO Source\ Code\ Pro nil iso10646-1 normal normal normal 0 nil 100 0
((:font-entity "/usr/share/fonts/adobe-source-code-pro/SourceCodePro-Regular.otf" . 0)
(:name . "Source Code Pro"))
>
```

Check the `:font-entity` argument and make sure it points to the one you want.

If it's not, you may need to provide a few more keyword arguments. Supported keyword arguments can be found via `M-x describe-function font-spec`.

---

Case study:

I've installed `Iosevka SS08` and patched it myself. Unfortunately I haven't provided a different name when I did that, so they end up having the same name.

I've set `dotspacemacs-default-font` to
```elisp
'("Iosevka SS08"
  :size 13.5
  :weight normal
  :width normal)
```
but I've noticed a few very subtle anomalies. So I tried to figure out what's going on:
```
(find-font (font-spec :name "Iosevka SS08" :size 13.5 :weight 'normal :width 'normal))
#<font-entity ftcrhb BE5N Iosevka\ SS08 nil iso10646-1 normal italic normal 0 nil nil 0
((:font-entity "/home/lucius/.fonts/iosevka-ss08-nerd/Regular/Iosevka SS08 Italic Nerd Font Complete.ttf" . 0)
(:name . "Iosevka SS08"))
>
```

It seems that it has located my patched font. I tried adding more attributes and
```
(find-font (font-spec :name "Iosevka SS08" :size 13.5 :weight 'normal :width 'normal :slant 'normal))
#<font-entity ftcrhb BE5N Iosevka\ SS08 nil iso10646-1 normal normal normal 0 nil 90 0
((:font-entity "/home/lucius/.fonts/iosevka-ss08/iosevka-ss08-regular.ttc" . 0)
(:name . "Iosevka SS08"))
>
```
So it finds the correct one.

**Comment by iliakur** [comment]
Thanks for the pointer.

I ran this command:
```emacs-lisp
(find-font 
    (font-spec :name "Inconsolata" 
                     :size 17 
                     :weight 'normal 
                     :width 'normal 
                     :poweline-scale 1.1))
```

Output:
```
#<font-entity ftcrhb CYRE Inconsolata nil iso10646-1 normal normal normal 0 nil nil 0 ((:font-entity "/usr/share/fonts/levien-inconsolata/Inconsolata-Regular.ttf" . 0) (:name . "Inconsolata") (:poweline-scale . 1.1))>
```

I'm not sure what to make of this though. The file path doesn't *look* patched, but what if someone patched the contents of the file itself? I don't have the expertise or time to investigate this :(
