### ISSUE TITLE
"error Package ‘emacs-26’ is unavailable" on latest develop

### ISSUE THREAD

**Issue by forty** [syl20bnr/spacemacs#13535]
#### Description :octocat:
I get the following error after pulling the latest `develop`:
> An error occurred while installing posframe (error: (error Package ‘emacs-26’ is unavailable))

#### Reproduction guide :beetle:
- Update spacemacs to latest master
- Restart Emacs

*Observed behaviour:* :eyes: :broken_heart:
> This error happens at startup:
> Contacting host: elpa.gnu.org:443
> Package refresh done
> (Spacemacs) --> installing package: posframe@dap... [1/1]
> (Spacemacs) Error: 
> An error occurred while installing posframe (error: (error Package ‘emacs-26’ is unavailable))

*Expected behaviour:* :heart: :smile:
No error happens

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1f6e39ea8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git
      (version-control :variables version-control-diff-side 'left version-control-diff-tool 'diff-hl)
      markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking lsp
      (rust :variables rust-backend 'lsp)
      (scala :variables scala-backend 'scala-metals)
      (typescript :variables typescript-backend 'tide)
      (javascript :variables node-add-modules-path t javascript-backend 'tide)
      prettier sql yaml terraform
      (neotree :variables neo-vc-integration
               '(face)
               neo-autorefresh t)
      (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
N/A

**Comment by forty** [comment]
Reverting to c3f13d03910e6ae55e5c617ce7c7bd9cb9861d70 fixes the problem

**Comment by emacs18** [comment]
https://github.com/tumashu/posframe/blob/master/posframe.el has this line
```elisp
;; Package-Requires: ((emacs "26"))
```
So it appears that you must use emacs 26 or newer if you want to use newer posframe package.
This does not appear to be an issue with spacemacs.  If you think posframe should support emacs 25, then you perhaps should submit such request to posframe author.

**Comment by forty** [comment]
Well I don't really mind, I did end up upgrading emacs anyway but: the documentation says that emacs 25.1 should work. I think either it should be clear that Spacemacs actually requires 26+ or it should be made sure that all packages installed by Spacemacs are indeed compatible with 25.1. Ensuring version consistency is the main purpose of a distribution IMO.

That said, if you disagree, feel free to close this bug, I sincerely won't be offended.

**Comment by emacs18** [comment]
I see that spacemacs has checks to use posframe only for emacs 26 or later, e.g.,
```elisp
(defconst dap-packages
  '(dap-mode
    (posframe (not (version< emacs-version "26.1")))))
```
So it appears that use of posframe within spacemacs is already consistent with the fact that version 25 is supported, i.e., if any specific package requires 26 or later, then that fact is captured by the conditional statements shown above.

**Comment by emacs18** [comment]
It appears that I cannot close this issue, i.e., there are "Close" button that I can press.

So please close this.

**Comment by emacs18** [comment]
The problem was reported against (rev. 1f6e39e) which was from 2020/04/12.
The version check code I quoted above was added on 2020/04/20.
Thus the problem may have been fixed, i.e., posframe package should not be used by spacemacs if you are using emacs 25.

**Comment by forty** [comment]
Great then :) thanks!
