### ISSUE TITLE
Visual line mode not respecting (evil-next-line COUNT)

### ISSUE THREAD

**Issue by joshcho** [syl20bnr/spacemacs#13538]
In vim, I bound J and K to be 10j and 10k.

I want to replicate that behavior, so I tried:

```
(evil-define-key 'visual global-map "J"
    ( lambda () (interactive)(evil-next-line 10)))
```

This works as intended for visual mode and visual block mode, but not for visual line mode. When I press Shift+v then J, my cursor does not move.

**Comment by 0xsuk** [comment]
Have you fixed this issue? I'm having the same problem so let me know if you don't mind.
