### ISSUE TITLE
org-brain doesn't have SPC menu

### ISSUE THREAD

**Issue by srgkoshelev** [syl20bnr/spacemacs#13548]
#### Description :octocat:
This might be a feature request rather than a bug.
org-brain doesn't recognize default spacemacs key bindings, e.g. SPC menu.

#### Reproduction guide :beetle:
- Start Emacs
- Start org-brain
- Press SPC
- Be sad you can't switch to the other window

*Observed behaviour:* :eyes: :broken_heart:
`End of buffer`

*Expected behaviour:* :heart: :smile:
SPC menu!

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d95d41f55)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html markdown csv helm auto-completion emacs-lisp multiple-cursors treemacs finance python git org spell-checking syntax-checking latex)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by zeneofa** [comment]
I found something that works for me, though I am not sure if this will generalize.

In .spacemacs I added the following to the user config area
```
(with-eval-after-load 'org
    (evil-set-initial-state 'org-brain-visualize-mode 'hybrid))
```
When running `org-brain-visualize`, I get dropped into insert-mode. This allows me to use the org-brain keybindings from the documentation. To get the SPC commands working again, I just ESC insert-mode. To get back to the org-brain-visualize keybindings, I just use `i` to get back to insert-mode. 

I am not sure if this breaks anything downstream though.

**Comment by duianto** [comment]
The reason why `SPC` doesn't work by default is because `org-brain-visualize-mode` is started in emacs state:
https://github.com/syl20bnr/spacemacs/blob/28ebdf290843a96595546f306b8f375a950df37b/layers/%2Bemacs/org/packages.el#L600

possibly because it's suggested in the org-brain setup section:
https://github.com/Kungsgeten/org-brain#setup-and-requirements
>If you’re an evil user, you’ll want to add (evil-set-initial-state 'org-brain-visualize-mode 'emacs) to your org-brain configuration.

In emacs state the Spacemacs menu is opened by pressing: `M-m`

### A possible workaround:
Add this to the `dotspacemacs/user-config` section:
```elisp
  (with-eval-after-load 'org-brain
    (define-key org-brain-visualize-mode-map (kbd "SPC") 'spacemacs-cmds))
```

**Comment by srgkoshelev** [comment]
Thank you, the workaround works perfectly! I wish it could be added as a default setting.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by fosskers** [comment]
The workaround does indeed work. Should it / can it be upstreamed to the default setup for the `org` layer?

**Comment by duianto** [comment]
A PR has been opened with a possible solution:
[org][org-brain] Add SPC menu (vim or hybrid style) #14429

**Comment by duianto** [comment]
The PR's changes have been applied to the `develop` branch.

@srgkoshelev Can you test that it works as expected.
If it does, then you can close this thread.

**Comment by srgkoshelev** [comment]
Thank you, guys!

I have removed the lines from the config && updated everything. **It works!**

**Comment by fosskers** [comment]
Yup, works great!~
