### ISSUE TITLE
Helm transient state does not follow candidates

### ISSUE THREAD

**Issue by jollaWellbuur** [syl20bnr/spacemacs#13543]
In `helm-swoop` I can select the next candidate by pressing `C-n`. This also changes the cursor position in my original window, allowing me to see context.
If I enter transient state (`M-SPC`), I can select the next candidate by pressing `j`. However, follow-mode is disabled in this case.

Is it possible to enable helm-follow-mode (?) in helm transient state?

**Comment by jr0cket** [comment]
`C-c C-f` enables helm-follow in the active helm list, even when in helm transient state.

**Comment by jollaWellbuur** [comment]
nice, works!
important: `helm-follow-mode-persistent` REMEMBERS if follow-mode is turned on, so I have to turn it on in helm-swoop once! (Did not see that at first...)
