### ISSUE TITLE
[org layer] - use of remember in org layer

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#1354]
I started getting into org-mode more recently and discovered remember.  Does anyone agree that it should be added to the org layer?

**Comment by louy2** [comment]
Could you explain what is the function of it?

**Comment by d12frosted** [comment]
Are you talking about [this thing](http://orgmode.org/manual/Capture.html)?

**Comment by ralesi** [comment]
I guess so, I didn't realize remember.el was deprecated.  The clipboard feature I was using in remember is an expansion in capture.
