### ISSUE TITLE
"Adjust Window" Ex command (`:z`) not supported

### ISSUE THREAD

**Issue by umanwizard** [syl20bnr/spacemacs#13544]
#### Description :octocat:
"Adjust Window" Ex command (`:z`) not supported

I know Spacemacs does not claim to have full Vim compatibility, but this is not a Vim feature. It is mandated by the POSIX ex/vi standards.

#### Reproduction guide :beetle:
- Start Emacs
- type :z

*Observed behaviour:* :eyes: :broken_heart:
"Unknown command: 'z'"

*Expected behaviour:* :heart: :smile:
As documented under "Adjust Window" heading in POSIX standard:
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ex.html

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1f6e39ea8)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python better-defaults emacs-lisp helm multiple-cursors treemacs
        (lsp :variables lsp-rust-server 'rust-analyzer lsp-rust-analyzer-server-display-inlay-hints t lsp-rust-analyzer-cargo-watch-enable nil lsp-response-timeout 30)
        git
        (rust :variables rust-backend 'lsp rust-format-on-save t)
        xclipboard)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
N/A

**Comment by umanwizard** [comment]
Actually, I'm noticing that many ex commands are not supported. Perhaps ex/vi support is not an intended feature, so this is not actually a bug? If so, that should be called out in the docs, IMO.

**Comment by mineo** [comment]
The ex command are provided by [evil](https://github.com/emacs-evil/evil). I think that might be the more correct place for this bug report. Note that evil doesn't strive to be a standards-compliant ex/vi implementation, though.
