### ISSUE TITLE
c-c++ layer: indenting selected region has issues on latest Emacs & Spacemacs develop

### ISSUE THREAD

**Issue by iqgrande** [syl20bnr/spacemacs#13541]
#### Description :octocat:
Indenting a selected region does not adhere to parameters, but inserting new lines does.

#### Reproduction guide :beetle:
- Within .spacemacs (setq-default c-default-style "k&r")
- Within .spacemacs (setq-default c-basic-offset 4)
- Within .spacemacs (setq-default tab-width 4)
- Start Emacs
- Write C/C++ code and see it auto-indent nicely with 4 spaces.
- Now, highlight that code and press "=" and it will reformat with 2-space indentions.

*Observed behaviour:* :eyes: :broken_heart:
Incorrect indention is applied.

*Expected behaviour:* :heart: :smile:
Correct indention (4 spaces).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1f6e39ea8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-idle-delay 0.2 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip nil auto-completion-use-company-box nil auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 better-defaults emacs-lisp
 (helm :variables helm-position 'bottom helm-use-fuzzy 'always)
 lsp multiple-cursors org spell-checking
 (syntax-checking :variables syntax-checking-enable-tooltips t syntax-checking-enable-by-default t)
 treemacs imenu-list spacemacs-modeline python gtags c-c++)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by iqgrande** [comment]
FWIW, I found a thread on Reddit [here](https://www.reddit.com/r/emacs/comments/g9izf3/how_can_i_change_the_indentation_offset_used_by/) where someone else seems to be experiencing the same issue I am.

**Comment by iqgrande** [comment]
Some sleuthing of mine has led me to believe that this issue occurs from the "c-c++" layer. I think it is hardcoding the styles to be Google's and the only way around it is to use the clang-format methods (which work).

**Comment by iqgrande** [comment]
I don't see anything within the "c-c++" layer code that would impact this. I am not sure why turning on this layer somehow corrupts `evil-indent` and I am not sure how to look any deeper into it (don't know Lisp, Evil, etc. well enough). I also verified that this issue impacts Emacs 26.3 (installed via `snap install emacs --classic` on Linux Mint 19.3).

**Comment by alexey0308** [comment]
Does it solve the issue, if one uses lsp mode without indentation? 
```
(lsp :variables lsp-enable-indentation nil)
```

**Comment by alexey0308** [comment]
https://github.com/syl20bnr/spacemacs/issues/13646

**Comment by iqgrande** [comment]
So far this fix looks like it has addressed the issue. I set up a `.clang-format` file for my project (which Emacs uses correctly when I call `clang-format-*` functions). The ticket above mentions that setting that up would potentially address this, however I have not found that to be the case (again, unless I manually call `clang-format-*` functions). Are there any recommendations for this? Thank you again for figuring this out.

**Comment by alexey0308** [comment]
To use clang, do not disable lsp-indentation. Just set .clang-format file and use `,==` to format the buffer.

**Comment by iqgrande** [comment]
When I copy/paste, it reformats what I paste incorrectly until I manually fix it via clang-format-*. It does the same, at times, when I also do control loops, etc. How can I tell it to use the .clang-format for these workflows also? Thanks again.

**Comment by alexey0308** [comment]
I know it can be annoying. The problem here is in different functions for line and region indentation (check values of indent-line-function and indent-region-function). Only the region function is set to lsp and uses clang, the other is from emacs c-mode. I do not know how to fix it in spacemacs, but can suggest only a work-around:
in your buffer with correctly indented code run c-guess and then it will set the correct c-basic-offset.
You may save this style with some name and use it as default instead of k&r along with clang formatting, [more here](https://www.gnu.org/software/emacs/manual/html_node/ccmode/Guessing-the-Style.html). Hope it helps.

**Comment by lebensterben** [comment]
feel free to re-open this if it's not fixed
