### ISSUE TITLE
Callback function inside JSX breaks auto quoting

### ISSUE THREAD

**Issue by pimlu** [syl20bnr/spacemacs#13550]
#### Description :octocat:
Callback function inside JSX breaks autocomplete

#### Reproduction guide :beetle:
- Start Emacs
- Load up the text from https://codesandbox.io/s/react-typescript-playground-mg17m?file=/src/index.tsx (this is a minimal example)
- Try typing `myVar =` inside the callback, it is triggered by typing `=`

*Observed behaviour:* :eyes: :broken_heart:
It will always insert `""` and put your cursor in betwen, even though you are not assigning a JSX property, you are back in JS code. And if you press delete to try to get rid of the autocomplete, it only deletes the left quote.

*Expected behaviour:* :heart: :smile:
It simply shouldn't do anything. Just put an `=` sign there.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git markdown themes-megapack javascript react
      (typescript :variables tide-tsserver-executable "~/.yarn/bin/tsserver"))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Comment by pimlu** [comment]
Looks like the behavior in question is "auto quoting" from web mode: http://web-mode.org/

**Comment by pimlu** [comment]
I was able to make editing TSX in spacemacs usable by setting

`(setq web-mode-enable-auto-quoting nil)`

inside `dotspacemacs/user-config`. (from https://emacs.stackexchange.com/a/28097) Hope this helps someone!

**Comment by lebensterben** [comment]
> Try typing myVar = inside the callback, it is triggered by typing =

what do you mean by callback
