### ISSUE TITLE
Package company-tern is unavailable

### ISSUE THREAD

**Issue by lialzmChina** [syl20bnr/spacemacs#13555]
version: 0.200.13@26.3 
os:mac

when i add javascript layer alter some warn

![image](https://user-images.githubusercontent.com/6356434/81065679-857b8400-8f0e-11ea-8c59-d18d175e57fc.png)

**Comment by rwanyoike** [comment]
Dupe of https://github.com/syl20bnr/spacemacs/issues/13530
