### ISSUE TITLE
Key bindings to insert prev/next commit message in COMMIT_EDITMSG buffer move lines instead

### ISSUE THREAD

**Issue by swinkels** [syl20bnr/spacemacs#13559]
#### Description :octocat:
When you commit a change in Magit, the COMMIT_EDITMSG buffer is shown. In this buffer, key-binding g k should show the previous commit message. Instead it tries to move the cursor to the previous line.

If you switch to VISUAL mode and back again, key-binding g k does show the previous commit message.

#### Reproduction guide :beetle:
- Start Emacs
- Use magit to commit a change to a Git repo
- Stage a second change
- Press c c to open the COMMIT_EDITMSG buffer

*Observed behaviour:* :eyes: :broken_heart:
Key-binding g j moves the cursor to the next line, key-binding g k moves to the cursor to the first line again.

If you press g, Spacemacs shows that k is bound to evil-previous-visual-line and j is bound to evil-next-visual-line.

*Expected behaviour:* :heart: :smile:
Key-binding g k should insert the previous commit message.

If you press g, Spacemacs should show that k is bound to git-commit-prev-message and j to git-commit-next-message.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1f6e39ea8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion c-c++
                 (c-c++ :variables c-c++-backend 'lsp-ccls)
                 emacs-lisp javascript git gtags helm html journal lsp lua markdown org
                 (python :variables python-backend 'anaconda python-formatter 'black python-test-runner 'pytest)
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Confirmed.

A related issue is that `M-n` and `M-p` are bound to 
`git-commit-next-message` and `git-commit-prev-message` by default.

But in Spacemacs they are bound to these evil-mc commands:
> M-p [evil-mc-make-and-goto-prev-cursor]
 M-n [evil-mc-make-and-goto-next-cursor]

The evil-mc commands should probably only be bound when there is more than one cursor.

<details><summary>
System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5fcd84d84)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 emacs-lisp git helm html javascript lsp
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org" "~/temp/org-tags-view_broken._13509.org"))
 (python :variables)
 ranger
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by duianto** [comment]
`gj` and `gk` seems to be defined in the `evil-magit` package:
https://github.com/emacs-evil/evil-magit/blob/88dc26ce59dbf4acb4e2891c79c4bd329553ba56/evil-magit.el#L403
```elisp
    ((,evil-magit-state visual) git-commit-mode-map "gk" git-commit-prev-message "M-p")
    ((,evil-magit-state visual) git-commit-mode-map "gj" git-commit-next-message "M-n")
```

**Comment by duianto** [comment]
This seems to be the commit where they were moved to visual state:
https://github.com/emacs-evil/evil-magit/commit/c86de70f76b064b1e34369c6b1d63fcce0626dc3

>Make more magit commands available in visual state
>
>Previously some useful magit commands were shadowed in visual state like
A for cherry picking a selection of commits from a log buffer. This
commit attempts to fix all of these by only making movement commands
similar to the one available in normal state available in visual state
and letting the rest of the magit commands be available after that.
>
>This only affects those who use evil-magit-use-y-for-yank.

**Comment by fleimgruber** [comment]
It's unfortunate that these move (why not add without moving?) with the unsuspecting setting of `evil-magit-use-y-for-yank` to `t`.

**Comment by lebensterben** [comment]
Not really a bug, but an annoyance cause by upstream change.
