### ISSUE TITLE
Duplicates in Helm command history

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#13564]
#### Description :octocat:
Helm history contains duplicates. After discussions in Gitter it turns out I'm not alone in seeing this.

#### Reproduction guide :beetle:
- Start Emacs
- `Spc Spc`, then type part of a command you use often

*Observed behaviour:* :eyes: :broken_heart:
Command history with many duplicates

![helm-history-duplicates](https://user-images.githubusercontent.com/327270/81322021-a1f4f900-9093-11ea-9558-0b15ab8b9cb6.png)

*Expected behaviour:* :heart: :smile:
Command history where each previously used command appears once.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d0f5477c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash docker evil-commentary evil-snipe git github
 (helm :variables helm-no-header t)
 lsp mu4e multiple-cursors restclient
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak)
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking templates
 (xclipboard :variables xclipboard-enable-cliphist t)
 (clojure :variables clojure-enable-sayid t clojure-enable-clj-refactor t clojure-enable-linters 'clj-kondo)
 dhall emacs-lisp
 (haskell :variables haskell-completion-backend 'lsp haskell-process-type 'cabal-repl)
 (python :variables python-formatter 'yapf)
 shell-scripts graphviz html json latex markdown
 (org :variables org-enable-reveal-js-support t)
 nixos spacemacs-org
 (sql :variables sql-auto-indent nil)
 pandoc terraform yaml archlinux clipboard-fix projectile-extra)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by dennismayr** [comment]
This happens even after a fresh _Spacemacs_ install after wiping the `~/.emacs.d` folder

**Comment by jr0cket** [comment]
Please share a link to your .spacemacs configuration file if you are having this issue and I will see if I can replicate the problem (ensure you didn't add any sensitive data to this file before sharing).  

Currently I cannot replicate this issue on an Ubuntu Linux OS with the same system info, although my layer list is shorter that the original poster.

**Comment by thanhvg** [comment]
It's an upstream issue there was a brave soul reporting it in `helm` repo.

**Comment by thanhvg** [comment]
Try `(setq history-delete-duplicates t)`. Put it somewhere in dot file.
https://github.com/emacs-helm/helm/issues/2291#issuecomment-615037764

**Comment by jr0cket** [comment]
I assume the new variables can be set in the helm layer :variables of the dotspacemacs-configuration-layers list

```(helm :variables
           history-delete-duplicates t
           history-length 10)
```
Use what ever size of history length you prefer.

**Comment by magthe** [comment]
There seems to be no layer variable for it, but putting

```
(setq history-delete-duplicates t)
```

in `dotspacemacs/user-config` does the trick.

Maybe it should be made the default behaviour?

**Comment by dennismayr** [comment]
We salute that brave soul

**Comment by drewverlee** [comment]
Unfortunately setting history-delete-duplicates and history-length in the dot files, dotspacemacs/user-config didn't fix it for me. I still get duplicates.

**Comment by thanhvg** [comment]
Because your history still has duplicates, to trigger a remove of a duplicate execute it again , then it's duplicates will be remove from history.  Say if you have `foo` as duplicates then `M-x: foo` 

Or you can nuke your `savehist-file` if you don't care about history. It should be `~/.emacs.d/.cache/savehist`

**Comment by jr0cket** [comment]
I fixed this issue on my computer by deleting  `~/.emacs.d/.cache/savehist` which has to be done when emacs is not running, otherwise it recreates the file.

A less brutal approach would be to edit the ` ~/.emacs.d/.cache/savehist` using a different editor, when Emacs is not running, and delete the duplicates.

**Comment by laynor** [comment]
> Unfortunately setting history-delete-duplicates and history-length in the dot files, dotspacemacs/user-config didn't fix it for me. I still get duplicates.

I was getting duplicates until I re-executed the command - I had lots of `customize-*` occurrences, but after issuing for example `customize-face`, all the `customize-face` duplicates where gone (the other `customize-*` where still there until I re-issued the duplicate command). Is that the case for you too?

**Comment by enisozgen** [comment]
Nice bug report BTW. 

There are few solution in this page to fix that problem. After executing `(setq history-delete-duplicates t)` history will not produce duplicate variables. 

**NOTE**  Old duplicate value will still will stay!! 
If you want to get rid of from this duplicated values, you have to change the value `extended-command-history`.
```
(setq extended-command-history
      (delq nil (delete-dups extended-command-history)))
```

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
[helm] avoid duplicates in `helm-M-x' history #14403

**Comment by magthe** [comment]
Then I think this can be closed :)
