### ISSUE TITLE
evil-visual-mark-mode is void

### ISSUE THREAD

**Issue by Davidj361** [syl20bnr/spacemacs#13572]
#### Description :octocat:

evil-visual-mark-mode is void
I try toggling evil-visual-mark-mode with ```SPC t ` ``` but it it says the definition is void.
Obviously I don't see any visual indicator for markers, e.g. `m a`.

#### Reproduction guide :beetle:

- Start Emacs

- Open a buffer to anything
- Make a Evil/Vim marker, e.g. `m a`
- Toggle evil-visual-mark-mode with ```SPC t ` ```

*Observed behaviour:* :eyes: :broken_heart:

Nothing changes, only given an error below saying:
Symbol's function definition is void: evil-visual-mark-mode

![screenshot](https://i.imgur.com/NZgTjrK.png)

*Expected behaviour:* :heart: :smile:

Toggling evil-visual-mark-mode should display Evil/Vim markers.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lua html helm auto-completion emacs-lisp git markdown org syntax-checking gtags)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:

```

Debugger entered--Lisp error: (void-function evil-visual-mark-mode)
  (evil-visual-mark-mode)
  (if (spacemacs/toggle-evil-visual-mark-mode-p) (progn (evil-visual-mark-mode -1) (if (called-interactively-p (quote any)) (progn (message "evil-visual-mark-mode disabled.")))) (evil-visual-mark-mode) (if (called-interactively-p (quote any)) (progn (message "evil-visual-mark-mode enabled."))))
  (if (or (null (quote nil)) (and (or (and (symbolp (quote nil)) (boundp (quote nil))) (listp (quote nil))) nil)) (if (spacemacs/toggle-evil-visual-mark-mode-p) (progn (evil-visual-mark-mode -1) (if (called-interactively-p (quote any)) (progn (message "evil-visual-mark-mode disabled.")))) (evil-visual-mark-mode) (if (called-interactively-p (quote any)) (progn (message "evil-visual-mark-mode enabled.")))) (message "This toggle is not supported."))
  spacemacs/toggle-evil-visual-mark-mode()
  funcall-interactively(spacemacs/toggle-evil-visual-mark-mode)
  call-interactively(spacemacs/toggle-evil-visual-mark-mode nil nil)
  command-execute(spacemacs/toggle-evil-visual-mark-mode)
```

**Comment by duianto** [comment]
It's working as expected for me, on both the `master` and `develop` branches, with updated packages.

- Open the scratch buffer: `SPC b s`
- Insert a lorem ipsum paragraph: `SPC i l p`
- Place the cursor somewhere in the text, and insert a marker: `ma`
- Enable `evil-visual-mark-mode`: `SPC t ` ``

The markers indicator is visible in the text:

![emacs_2020-06-17_12-47-38](https://user-images.githubusercontent.com/13420573/84889226-d26b8200-b098-11ea-8a1f-f3caa479392e.png)

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f60997e6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables)
 emacs-lisp git helm html javascript
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org" "~/temp/org-tags-view_broken._13509.org"))
 python
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 themes-megapack treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>
