### ISSUE TITLE
PlantUML syntax highlighting is not working

### ISSUE THREAD

**Issue by k-jell** [syl20bnr/spacemacs#13574]
#### Description :octocat:
PlantUML syntax highlighting not working

#### Reproduction guide :beetle:
- Start Emacs
- open any .pum file

*Observed behaviour:* :eyes: :broken_heart:
Syntax highlighting is not working. In the message buffer there are two related messages:
```
Contacting host: www.plantuml.com:443
File mode specification error: (wrong-type-argument stringp nil)
```
*Expected behaviour:* :heart: :smile:
Syntax is highlighted properly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7dd209173)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm javascript html markdown pandoc python latex auto-completion emacs-lisp git org bibtex spell-checking pdf syntax-checking
      (plantuml :variables plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar" org-plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar")
      lsp
      (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-lsp-enable-semantic-highlight 'rainbow)
      semantic
      (ruby :variables ruby-version-manager 'rubyenv ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec ruby-backend 'robe)
      shell-scripts)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
Looks like there is an issue in plantuml mode, it looks like there are now various modes in which plantuml can be executed, the layer does not set the mode, which defaults to `server`, this will contact the official plantuml online server to determine the correct calling parameters, which fails with the mode's parsing function.

This must be reported to upstream (plantuml-mode). The layer also needs to be adapted to set the default mode to `jar` which was once the only choice available.

**Comment by smile13241324** [comment]
I have fixed the layer, it is now using `jar` execution as default, as intended, but still allows to explicitly select the execution mode by setting `plantuml-exec-mode` to `server`. This is described in full detail in the layers readme.

@k-jell please double check on develop and close the issue if it works for you again.

**Comment by k-jell** [comment]
It is working :smiley: Thanks a lot for fixing the issue!
