### ISSUE TITLE
Typos in holy-mode.el

### ISSUE THREAD

**Issue by phoe** [syl20bnr/spacemacs#13576]
https://github.com/syl20bnr/spacemacs/blob/d46eacd83842815b24afcb2e1fee5c80c38187c5/layers/%2Bdistributions/spacemacs-base/local/holy-mode/holy-mode.el#L61

Typos in `nominus` and `sipritus`. Should be `in-nomine-patris-et-filii-et-spiritus-sancti`

**Comment by smile13241324** [comment]
@phoe just checked on `develop`, there the typo has been removed.
