### ISSUE TITLE
In eshell when you type )  after a single quote ('), it is inserting )').

### ISSUE THREAD

**Issue by naibprabhanjan** [syl20bnr/spacemacs#13570]
```
λ xyz('something' <---when you type ) here
```
becomes
```
λ xyz('something)')
```

This is also happens in python interpreter
```
>>> open ('xyz' <---when you type ) here
```
becomes
```
>>> open ('xyz)')
```

--------------------Here is the system information--------------------
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html c-c++ pdf-tools javascript helm emacs-lisp org python elfeed semantic git
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle :disalbe-for org)
      (syntax-checking :variables syntax-checking-enable-by-default 't)
      (ibuffer :variables ibuffer-group-buffers-by nil)
      ranger
      (shell :variables shell-default-shell 'eshell)
      csharp command-log)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
This is what I'm seeing:

### In an eshell buffer
Typing: `xyz('something'` followed by a close parenthesis.
Inserts the closing parenthesis as expected: `xyz('something')`

### In a python file `.py`.
Pressing `,si` calls: `spacemacs/python-start-or-switch-repl`
Typing: `open (` inserts the closing parenthesis automatically after the cursor: `open ()`
Typing a single quote, inserts a second single quote after the cursor: `open ('')`

---

This was observed on both the `master` and `develop` branches with updated packages, in both Linux and Windows.

<details><summary>
PopOS 20.04, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f60997e6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors python
            (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
            treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f60997e6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 emacs-lisp git helm html javascript lsp
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files
      '("~/org/notes.org" "~/temp/org-tags-view_broken._13509.org"))
 (python :variables)
 ranger
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 themes-megapack treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

---

### PS:
This is unrelated to your closing parenthesis issue.

There's a typo in your `auto-completion` configuration layer:
```
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle :disalbe-for org)
```
change: `:disalbe-for`
to `:disabled-for`

https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#disabling-layer-services-in-other-layers

**Comment by lebensterben** [comment]
Not able to reproduce this in eshell.
