### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by xamount** [syl20bnr/spacemacs#13571]
A few broken links I noticed on the website:
Homepage: The "contribute" link gives a 404
The Layers list at https://www.spacemacs.org/layers/LAYERS.html has many broken links:
* All the links under the "4 Distributions" section
* The link under the "11 Misc" section
* All the links under the "15 Spacemacs distribution layers" section

**Comment by duianto** [comment]
Thanks for reporting this, however this time the broken links have been fixed on the develop branch webpage: https://develop.spacemacs.org/

And the layers page has been rewritten: https://develop.spacemacs.org/layers/LAYERS.html

The main page will be updated when the next Spacemacs version is released
(I don't have any knowledge of when that is).
