### ISSUE TITLE
Issues with anaconda-mode: Blocking call to accept-process-output with quit inhibited!!

### ISSUE THREAD

**Issue by shaief** [syl20bnr/spacemacs#1357]
I face some issues with `anaconda-mode`. 
At the buttom of a buffer with python file opened i get this message:
``` Blocking call to accept-process-output with quit inhibited!!```
My `anaconda-mode buffer` is full with this message:
```
emacs: /usr/local/bin/python: Exec format error 

Process anaconda_mode exited abnormally with code 126
```
i installed everything as described in lang Python. My OS is Arch Linux so my main Python is python3.4

Does anyone here knows how to solve it, and make it possible to work on Python in spacemacs?

Thanks!

**Comment by mijoharas** [comment]
Hi @shaief. So I have a working company-mode with `python 3.4` on arch linux. With this build I currently don't use virtualenv so I don't know if there is a problem there.

One thing I'd like to check is have you done anything special with your python executable? For me on arch the binary is located at `/usr/bin/python` and I have no python executables in `/usr/local/bin`.

**Comment by shaief** [comment]
Hi @mijoharas - thank you for getting back to me!
I don't think i've done anything special with my python executables. I do have Python execs in both `/usr/local/bin` and `/usr/bin/` (2.7, 3.4).

**Comment by mijoharas** [comment]
ok, well one thing to think is that if you have a `python2` in `/usr/local/bin` which appears to be the one that `anaconda-mode` is trying to use, you should be sure that the dependencies of anaconda-mode are installed for that python. I think there's a `pip2` and `pip` is symlinked to `pip3` (this is dusty memories of mine).

Have you tried: `pip2 install  jedi==0.8.1 json-rpc==1.8.1 service_factory==0.1.2`?

**Comment by shaief** [comment]
I tried to install everything through both pip and pip2, just to verify that i have all the dependencies. After pip-ing all requirements were met.

I did install everything without a specific versions - so i'll have the latest packages...

Do you know if i can point `anaconda-mode` to a specific python exec?

**Comment by mijoharas** [comment]
I think the dependancy versions matter which is why they're recommended. certain version combinations may not work correctly together. I think that's why this exact line to install them is recommended.

**Comment by shaief** [comment]
I've downgraded json-rpc (it was the only one that was in a newer version...) still have the same issues.

**Comment by mijoharas** [comment]
Looking [here](https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L68) it detects the `python` executable that is first in your path. put `/usr/bin` before `/usr/local/bin` and you will have that executable. (should be the executable that is located at `which python` in a terminal).

**Comment by shaief** [comment]
That means it should work then.
I think that the backend anaconda server doesn't start automatically.

**Comment by mijoharas** [comment]
I think that sounds right, but I'm afraid I'm not sure exactly what's going wrong with your setup. Everything just worked for me. Try figuring out which call is breaking with anaconda_mode, and then maybe try running that command with `python` to see what's going on.

Sorry I can't be any more help. :worried:

**Comment by mijoharas** [comment]
Oh, I've got an idea, try running `(anaconda-mode-start)` in eshell to see what that does ([ref](https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L78))

**Comment by shaief** [comment]
Nothing... :(
My `anaconda-mode buffer` is full with:
```
emacs: /usr/local/bin/python: Exec format error

Process anaconda_mode exited abnormally with code 126
```

Hey thanks a lot for you efforts! i really appreciate it!

**Comment by mijoharas** [comment]
Actually, the code for anaconda mode looks quite readable (for elisp of course). looking between [this file](https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el) and [this one](https://github.com/proofit404/anaconda-mode/blob/master/anaconda_mode.py) (if you're lucky) you should be able to figure out what's going wrong.

Np, wish I could've helped more. Good luck!

**Comment by syl20bnr** [comment]
@shaief Did you try posting the issue upstream to get help from anaconda maintainer ?
If you create an issue there, reference it here so we can track it.

**Comment by shaief** [comment]
@syl20bnr Thanks. I did, here is the link https://github.com/proofit404/anaconda-mode/issues/82
Unfortunately, though it is closed already, i still didn't manage to solve the issue.

**Comment by shaief** [comment]
I just checked at work, and here on Fedora 20 the python layer works as expected.
I guess it must have issues on my Arch due to python3 or different locations of python executables.

I'll be happy to hear ideas. Thanks!

**Comment by hafenr** [comment]
I don't now to what extent this may be related, but in case it helps:
Symlinking `/usr/bin/python` directly to the executable provided by homebrew in `/usr/local/bin/python` fixed the issue for me on OSX. Previously, `/usr/bin/python` linked to the python version provided by OSX itself.

**Comment by CestDiego** [comment]
as Anaconda now install all it needs at installation time this might no longer happen. Right?

**Comment by TheBB** [comment]
I suspect this is true. In any case this issue is likely out of date.
