### ISSUE TITLE
org-mode description list indentation behaviour has changed

### ISSUE THREAD

**Issue by jrmiller82** [syl20bnr/spacemacs#13586]
Question about org mode's description list indentation. Longer labels used to indent the content farther and now it is not doing so. For example: 

```
- Read this :: "Right after the explosion, I ducked behind a rain barrel. Then I
               heard a 'plop' and found this in the barrel."

- Read this :: "Right after the explosion, I ducked behind a rain barrel. Then I
  heard a 'plop' and found this in the barrel."
```

I'm trying to get the behaviour to go back to the first version, and not the second. 

Thoughts?

**Comment by smile13241324** [comment]
Looks like this has been changed in org-mode itself. I have found the following stackexchange entry asking a very similar [question](https://emacs.stackexchange.com/questions/48962/indentation-of-description-lists). 

This is a quote from the final answer:
> If you are using a newer version of org-mode (2019+) and ask yourself why the seconds line isn't indented as shown here: The fancy description list indentation got removed. Reason: Special indentation on description items breaks indentation in sub-items. – Hubisan Mar 4 at 11:19

So your best bet would be to open a ticket upstream asking them for a formatting replacement.

**Comment by jrmiller82** [comment]
Yup, here's the commit where they took it out. https://code.orgmode.org/bzg/org-mode/commit/683df456a41a2b0e308bdbf746f5db0235a6058a

**Comment by jrmiller82** [comment]
Sent a question to the mailing list; doesn't seem like it was discussed in the mailing-list archives before removing the functionality.
