### ISSUE TITLE
env not correctly populated when graphic dislay: nil

### ISSUE THREAD

**Issue by mcfilib** [syl20bnr/spacemacs#13582]
#### Description :octocat:

when i start non-graphical emacs, my `env` is not correctly set e.g. variables are missing and `PATH` is wrong.

#### Reproduction guide :beetle:
- start non-graphical emacs
- run `spacemacs/force-init-spacemacs-env`
- restart non-graphical emacs
- `M-x getenv`

*Observed behaviour:* :eyes: :broken_heart:
- `getenv` doesn't list all of the environment variables i would expect to see 😞 

*Expected behaviour:* :heart: :smile:
- `getenv` should list all of my environment variables 

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5280ac232)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git html javascript markdown org
                 (python :variables python-backend 'lsp)
                 react ruby ruby-on-rails syntax-checking themes-megapack typescript version-control yaml
                 (haskell :variables haskell-enable-ghc-mod-support nil haskell-process-type 'stack-ghci haskell-completion-backend 'intero)
                 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by mcfilib** [comment]
i have also tried:

- `spacemacs/load-spacemacs-env`

i will also try:

- adding env vars to `.zshenv` instead (saw this mentioned somewhere else in passing)

**Comment by mcfilib** [comment]
> adding env vars to ~/.zshenv instead (saw this mentioned somewhere else in passing)

has no effect.

**Comment by mcfilib** [comment]
i was able to "fix" this by adding the following line to `dotspacemacs/user-config`.

```elisp
(spacemacs/load-spacemacs-env t)
```

i'm guessing something changed in `emacs` or `spacemacs` around `env` handling since i created my `.spacemacs`. 

is there something that should be doing this automatically or is this a bug?

**Comment by jr0cket** [comment]
Ensure that you updated the .spacemacs file from the template.  There are several new sections when moving from master to develop.

https://practicalli.github.io/spacemacs/install-spacemacs/switch-to-develop.html

**Comment by mcfilib** [comment]
cheers! that’s just what i needed.
