### ISSUE TITLE
change mac install instructions

### ISSUE THREAD

**Issue by dmurphy112** [syl20bnr/spacemacs#13585]
In the mac [prerequisites](https://github.com/syl20bnr/spacemacs#prerequisites) there are a few homebrew commands to copy/paste:  
`$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus
$ brew linkapps emacs-plus`
`linkapps` is now deprecated, however the command `link` is a valid substitute.

**Comment by smile13241324** [comment]
See below quote from develop:

> macOS
Install emacs

> Using emacs-plus
brew tap d12frosted/emacs-plus
brew install emacs-plus
brew link emacs-plus

> Using emacs-mac
brew tap railwaycat/emacsmacport
brew install emacs-mac
brew link emacs-mac

There the instructions already refer to link instead of linkapps.

**Comment by dmurphy112** [comment]
Check line 148 on the readme:
`$ brew linkapps emacs-plus`

sorry I did not refer to that earlier!

**Comment by smile13241324** [comment]
Sorry didn't find it I have searched for `linkapps` in the entire project on `develop`. Please double check on develop.
