### ISSUE TITLE
Org babel with julia loaded leads to error when opening any `.org` file.

### ISSUE THREAD

**Issue by pietrodito** [syl20bnr/spacemacs#13597]
#### Description :octocat:
Org babel with julia loaded leads to error when opening any `.org` file.

#### Reproduction guide :beetle:
- Start Emacs
- with this config
```
    (custom-set-variables
     '(org-babel-load-languages (quote ((emacs-lisp . t)
                                        (R          . t)
                                        (julia      . t)
                                        )))
```
- 

*Observed behaviour:* :eyes: :broken_heart:
- Error:
`File mode specification error: (void-variable inferior-julia-program-name)`
- But can be fixed for the session if one visits the help description variale of `inferior-julia-program-name` which has value `"julia"`.
- After checking the help description everything works

*Expected behaviour:* :heart: :smile:
- No error
- And an understanding of why the visit of the help section changes the value of the variable defined in `ess-custom.el`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bf9d9d196)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((helm :variables helm-position 'bottom helm-no-header t)
 emacs-lisp ess org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
@pietrodito 
> Once ESS is up and running you will need to tell it where the =julia=
executable is. Edit the following and place it in your =.emacs=:
>
>#+BEGIN_SRC emacs-lisp :eval never
(setq  inferior-julia-program-name "/path/to/julia-release-basic")
#+END_SRC

Does this help?
