### ISSUE TITLE
Unknown layer dap declared in dotfile

### ISSUE THREAD

**Issue by DustyQuince** [syl20bnr/spacemacs#13599]
From my .spacemacs:
`dotspacemacs-configuration-layers
   '(
     python
     elm
     yaml
     csv
     sql
     javascript
     helm
     auto-completion
     better-defaults
     emacs-lisp
     git
     mu4e
     markdown
     org
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     spell-checking
     syntax-checking
     version-control
     react
     org-roam
     (ruby :variables
           ruby-enable-enh-ruby-mode t
           ruby-version-manager 'rbenv
           ruby-backend 'robe
           ruby-test-runner 'rspec)
     ruby-on-rails
     dap
     )`

After I added dap, I get the 'Unknown layer dap declared in dotfile' warning. According to the documentation [here](https://develop.spacemacs.org/layers/+tools/dap/README.html), all I need to do to get started with the layer is include it in the configuration layers list. Is this configuration layer no longer in the repos?

**Comment by basus** [comment]
`dap` seems to be present in the `develop` branch under `layers/+tools`, but I don't see it there in the master branch. You may need to be on the `develop` branch to use it?

**Comment by smile13241324** [comment]
@DustyQuince yeah dap as well as lsp is only fully supported on develop. Please switch branches.

**Comment by DustyQuince** [comment]
Confirmed. I'm no longer getting that message and I am able to use the layer. Thank you
