### ISSUE TITLE
C-g doesn't trigger `quit`

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#13592]
#### Description :octocat:
C-g doesn't trigger `quit`.

#### Reproduction guide :beetle:
- Start Emacs
- Press the spacebar once.
- Press C-g
- The shortcut should be cancelled, but it is not. I need to wait a few seconds and then the minibuffer shows `SPC C-g is undefined`.

I have observed this behavior when trying to cancel slow autocompletions, too. Nowadays I have to rely on this shell alias to unhang my emacs:

```
alias pe='pkill -SIGUSR2 -i emacs ; emacsclient -e '\''(setq debug-on-quit nil)'\'
```

`SPC h d k C-g` returns different things depending on I don't know what:

```
C-g runs the command pupo/close-window (found in global-map), which is an
interactive Lisp closure in ‘spacemacs-purpose-popwin.el’.

It is bound to SPC w p p, M-m w p p, C-g.

(pupo/close-window)

Close most recent popup window.
This command can be used repeatedly to close all popup windows.

[back]
```

```
C-g runs the command keyboard-quit (found in global-map), which is an
interactive compiled Lisp function in ‘simple.el’.

It is bound to C-g.

(keyboard-quit)

:around advice: ‘ad-Advice-keyboard-quit’

Signal a ‘quit’ condition.
During execution of Lisp code, this character causes a quit directly.
At top-level, as an editor command, this simply beeps.
```

Might be related to https://github.com/syl20bnr/spacemacs/issues/6219

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3f13d039)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby lua octave csv sql asciidoc yaml fsharp windows-scripts javascript
      (julia :variables julia-mode-enable-ess t julia-mode-enable-lsp nil)
      json ocaml idris fasd xclipboard gpu epub spotify search-engine vimscript
      (typescript :variables typescript-backend 'tide)
      (elfeed :variables rmh-elfeed-org-files
              (list "~/.emacs.d/private/feeds/elfeed1.org"))
      (rust :variables rust-backend 'racer rust-format-on-save t)
      (haskell :variables haskell-enable-hindent t)
      (c-c++ :variables c-c++-enable-clang-support t)
      html dap chrome
      (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
      (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
      autohotkey kotlin helm
      (auto-completion :disabled-for
                       '(ocaml)
                       :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
      emacs-lisp
      (ibuffer :variables ibuffer-group-buffers-by 'modes)
      coq emoji
      (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
      git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking
      (syntax-checking :variables syntax-checking-enable-tooltips t)
      (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
      version-control osx scheme
      (clojure :variables clojure-enable-fancify-symbols t))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```

```

**Comment by NightMachinary** [comment]
I think the culprit is whatever tying `C-g` to `pupo/close-window`. `‘spacemacs-purpose-popwin.el’`?

**Comment by NightMachinary** [comment]
This might also be related to https://github.com/syl20bnr/spacemacs/issues/11314 . Because after doing `(cancel-function-timers 'auto-revert-buffers)`, my `c-g` works as expected seemingly, although it's still randomly bound to `pupo/close-window`.

**Comment by emacs18** [comment]
For me SPC C-g immediately prints "SPC C-g is undefined" message.
Same goes for C-x C-g, C-x 4 C-g, C-c C-g, etc.
So SPC C-g is no different than all other prefix key bindings.
What is the problem?

**Comment by NightMachinary** [comment]
@emacs18 I thought it should cancel the whole process of “detecting a hotkey.” Anyhow, the problem as such is that it gets a few seconds for me to show that “... is undefined”. And pressing it multiple times during the wait sometimes causes emacs to hang completely.

**Comment by emacs18** [comment]
So we agree that the fact that "is undefined" message being printed is the expected behavior when C-g is pressed after some prefix keys.

The unexpected aspect is that (a) there is a delay after SPC C-g is pressed, and (b) emacs hangs on repeated C-g.

I do not observe either of these two problems on emacs 27 using latest develop branch of spacemacs on ubuntu 20.04.
