### ISSUE TITLE
ess layer: defvaralias obsolete var produces a warning with emacs 27

### ISSUE THREAD

**Issue by pietrodito** [syl20bnr/spacemacs#13596]
#### Description :octocat:
With emacs 27 warning about `ess-continued-statement-offset` when opening code file. I cannot reproduce this warning with vanilla emacs and ess package only installed.

#### Reproduction guide :beetle:
- Start Emacs
- Open `.R` file with code which needs to be indented. 

*Observed behaviour:* :eyes: :broken_heart:
Warning (defvaralias): Overwriting value of ‘ess-continued-statement-offset’ by aliasing to ‘ess-offset-continued’

*Expected behaviour:* :heart: :smile:
No warnings

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bf9d9d196)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp ess)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP

#### Backtrace :paw_prints:
```
```

**Comment by beyondpie** [comment]
Hi, I guest the problem from the line below.

https://github.com/beyondpie/spacemacs/blob/920f568d819d813956a07a72328ae18df6ce95c6/layers/%2Blang/ess/packages.el#L75

And I just comment `ess-continued-statement-offset`, which should be OK then.

**Comment by smile13241324** [comment]
Merged, please have another look @pietrodito.
