### ISSUE TITLE
CIDER Debugger bindings are overriden by Normal Mode

### ISSUE THREAD

**Issue by neilyio** [syl20bnr/spacemacs#13594]
#### Description :octocat:
Many single-key CIDER commands, like `i` and `c` for "into" and "continue" are interpreted as Normal Mode commands. Not only does this make the debugger unusable, but it makes it very easy to accidentally change the source code while you're debugging.

In the meantime, I'm using `C-z` to switch to Emacs state while debugging, but it took me some digging to know to do that. Until this is solved, maybe a `C-z` suggestion could be added to the in-buffer debugger tip?

#### Reproduction guide :beetle:
- Start Emacs
- Open a `.clj`, run a CIDER repl with `cider-jack-in-clj`
- Instrument a function with `SPC u , e f`
- Run function in REPL
- Press `i` or `c` in the debugger.

*Observed behaviour:* :eyes: :broken_heart:
Pressing `n` works for the debugger's "next".
Pressing `i` or `c` is overriden by Normal's "change" and "insert".

*Expected behaviour:* :heart: :smile:
All keypresses are passed to CIDER debugger.
Not sure I want to be able to change the source code at all while in the debugging state.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1f6e39ea8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(theming
 (clojure :variables clojure-enable-linters
          '(clj-kondo joker))
 html elm python markdown csharp c-c++ shell emacs-lisp git ivy dap lsp multiple-cursors
 (org :variables org-startup-indented t org-indent-mode t)
 themes-megapack version-control treemacs org-roam)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS

**Comment by jr0cket** [comment]
I also have this issue.  In my tests keys `n o h l j t q` correctly call the cider debug menu, however, `c e i p s` call the Evil normal state commands instead.

Manually using `C-z` to switch to Emacs state enables the keys to work, manually switching back when the debug session is done.

`\` calls `evil-execute-as-emacs-state` and using this before any of the keys that call evil state also makes them call the cider-debug menu keys correctly

I have uses a very simple project to test this at https://github.com/practicalli/exercism-clojure-guides/tree/master/two-fer
leiningen.org build tool and Java virtual machine are required to run the REPL for this project.

**Comment by mukeshbhakuni** [comment]
How to undo the set `cider-debug-defn-breakpoint` for the function.

**Comment by lebensterben** [comment]
One possible solution is to use `evil-collection`'s cider-mode setup.
Sepecifically for cider-debug, see

https://github.com/emacs-evil/evil-collection/blob/95b246e8fb09d64443b8f7173e1759c1f9cd3e54/modes/cider/evil-collection-cider.el#L99-L109

**Comment by practicalli-johnny** [comment]
Unfortunately this issue is still occurring and a noticeable error in behavior when using Spacemacs for Clojure development.

**Comment by fnussbaum** [comment]
> I also have this issue. In my tests keys n o h l j p q t correctly call the cider debug menu, however, c e i s call the Evil normal state commands instead.

I cannot exactly reproduce this, all of the keys call the cider bindings for me. The following existing code should indeed overwrite all default normal state bindings:
https://github.com/syl20bnr/spacemacs/blob/06067c381f6fc4c4bdcb6e3653b97987a7c1c7b9/layers/%2Blang/clojure/funcs.el#L197-L201

However, I think we should not only override default bindings, but should give the debug map the highest priority by using `evil-make-intercept-map` instead of `evil-make-overriding-map`. See #16579, perhaps this fixes the problem for you.

**Comment by fnussbaum** [comment]
This should be fixed as of https://github.com/syl20bnr/spacemacs/commit/2832ea8827820094296ff6adda3792848b731d2e.
