### ISSUE TITLE
[suggestion] section by release notes to show new configuration layers added in the latest version.

### ISSUE THREAD

**Issue by mijoharas** [syl20bnr/spacemacs#1359]
Was just thinking that it might be a good idea to have a section next to the release notes on the spacemacs splash-screen that shows any new configuration layers that have been added in the latest version.

I think it'd help discoverability, and since I occasionally check out the contrib folder to see anything that looks new there, it'd obviously be good if I could do that from within emacs easily. :smile: 

What does everyone think about this?

**Comment by syl20bnr** [comment]
This is a good idea, I will do that for the next release.
