### ISSUE TITLE
Missing key binding

### ISSUE THREAD

**Issue by ejez** [syl20bnr/spacemacs#13603]
#### Description :octocat:
Missing key binding

#### Reproduction guide :beetle:
- Start Emacs
- Press `SPC s r r`

*Observed behaviour:* :eyes: :broken_heart:
`SPC s r r is undefined`

*Expected behaviour:* :heart: :smile:
According to the [doc](https://github.com/syl20bnr/spacemacs/edit/develop/doc/DOCUMENTATION.org#L2760), the above key sequence should be bound to "search current file with ripgrep".

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 015303a70)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by emacs18** [comment]
I think no code exist to search current file using rg, and I don't think we should write such code when there are so many other options.

IMHO we should simply remove the two lines from the documentation, i.e., apply this patch:

```diff
diff --git a/doc/DOCUMENTATION.org b/doc/DOCUMENTATION.org
index 7f1e6e4..659ea7d 100644
--- a/doc/DOCUMENTATION.org
+++ b/doc/DOCUMENTATION.org
@@ -2757,8 +2757,6 @@ bindings (~SPC e n~ and ~SPC e p~) as well as the error transient state (~SPC e
 | ~SPC s a A~ | =ag= with default input                             |
 | ~SPC s g g~ | =grep=                                              |
 | ~SPC s g G~ | =grep= with default input                           |
-| ~SPC s r r~ | =rg=                                                |
-| ~SPC s r R~ | =rg= with default input                             |
 
 **** Searching in all open buffers visiting files
```

**Comment by lebensterben** [comment]
I've a unfinished PR that adds the functionality to ripgrep.

Stay tuned. It was started in late 2019 and probably it will finish this year. (it's already working)
