### ISSUE TITLE
lsp-mode breaks vim style completion

### ISSUE THREAD

**Issue by andreasknoepfle** [syl20bnr/spacemacs#13606]
#### Description :octocat:
Autocompletion in lsp mode breaks navigating completion suggestions in vim style (C-j or C-k).

Sidenote:
It seems that the lsp layer uses it's own company configuration (you can even remove the `auto-completion` layer and still have autocompletion).

#### Reproduction guide :beetle:
- Start Emacs
- Install LSP layer
- Use any mode that supports lsp-mode autocompletion (I tried with ruby/elixir with the same result)
- Try navigating code completion suggestions vim style `C-j` `C-k`

*Observed behaviour:* :eyes: :broken_heart:
Instead of navigating the completions close and you end up on the next line (default j k behaviour).
Navigation only works emacs style (`M-n` `M-p`)

![spacemacs](https://user-images.githubusercontent.com/239398/82436473-2aad6500-9a96-11ea-8da0-a9c8688f7bec.gif)

*Expected behaviour:* :heart: :smile:
Navigation works vim style (ideally depending on the editing style)

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 015303a70)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust emoji erlang csv
      (elixir :variables flycheck-elixir-credo-strict t)
      sql yaml html helm osx auto-completion better-defaults emacs-lisp evil-commentary react elm
      (ruby :variables ruby-backend 'lsp)
      ruby-on-rails
      git github markdown html org javascript
      (lsp :variables lsp-ui-doc-enable nil)
      dap
      (shell :variables shell-default-term-shell "/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control treemacs)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by smile13241324** [comment]
@andreasknoepfle I can't reproduce your issue, I have just created a test python file and lsp auto completion works with vim style completions.

For the records lsp layer has not his own implementation for auto-completion, it just depends on auto-completion and syntax-checking layers and loads them before by means of layer dependencies (layers.el).

**Comment by andreasknoepfle** [comment]
Hey @smile13241324,

thanks for trying. I actually switched to `doom` because of this and haven't tried a newer state of spacemacs ever since. Maybe it was a local anomaly then. Feel free to close this from my side :) 

Cheers
