### ISSUE TITLE
Evil motions to respect subword-mode

### ISSUE THREAD

**Issue by mkcode** [syl20bnr/spacemacs#1361]
I would love it if evil motion commands respected subword-mode. By this I mean all motion keys like `w, e, b` and actions like `dw`

For those that are unfamiliar, subword-mode changes emacs word motion commands to split on tokens like `-, _` as well as in between CamelCase words. subword-mode has a global-subword-mode command which is generally turned off by default and enabled for specific modes, usually for languages with CamelCase variables/functions such as javascript.

Looking into this, I found there has been some back and forth with this in evil for some time. There is a variable `evil-cjk-emacs-word-boundary`, which currently does nothing as far as I can tell.

If there is an easy way to do this, please let me know. Otherwise, I'll take a stab at implementing this by customizing the `evil-cjk-word-separating-categories` variable in a subword-mode-hook. 
http://permalink.gmane.org/gmane.emacs.vim-emulation/1594

**Comment by syl20bnr** [comment]
That's weird, it should be the case.
Do you have some examples with expected results I can try on my side ?

**Comment by mkcode** [comment]
@syl20bnr - evil has always split. on `_` and `-` for me. I want to split in between CamelCase word segments as well mimicking the behavior of subword-mode from emacs. This is more of a feature request than an issue. It's implemented in #1376.

Closing as this is not an issue.

**Comment by syl20bnr** [comment]
Great, thank you for the PR :+1:
