### ISSUE TITLE
evil-escape-key-sequence will turn off latex-magic-buffer effect at point

### ISSUE THREAD

**Issue by dwuggh** [syl20bnr/spacemacs#13616]
#### Description :octocat:
evil-escape-key-sequence will turn off latex-magic-buffer effect at point

#### Reproduction guide :beetle:
- Start Emacs
- open a .tex file
- insert a math symbol such as $\infty$
- if latex-magic-buffer has been turned on, a unicode symbol ∞ would be shown
- press jk(my evil-escape-key-sequence), ∞ would fall back to \infty

*Observed behaviour:* :eyes: :broken_heart:
∞ fall back to \infty

*Expected behaviour:* :heart: :smile:
∞ would not change

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5280ac232)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml vimscript emacs-lisp git ivy helm
      (auto-completion :variables auto-completion-enable-snippets-in-popup t)
      lsp markdown multiple-cursors
      (org :variables org-agenda-files
           '("~/org/agenda")
           org-enable-org-journal-support t org-journal-dir "~/org/journal/" org-journal-enable-agenda-integration t)
      (latex :variables latex-enable-magic t latex-enable-folding t latex-build-command "LaTeX" latex-enable-folding t)
      pdf orgwithlatex
      (spell-checking :variables ispell-program-name "aspell" spell-checking-enable-by-default nil)
      syntax-checking treemacs c-c++ rust
      (python :variables python-backend 'lsp python-lsp-server 'mspyls)
      prettier
      (javascript :variables javascript-backend 'lsp javascript-lsp-linter nil javascript-fmt-tool 'prettier)
      (typescript :variables typescript-fmt-tool 'prettier typescript-linter 'eslint typescript-backend 'tide typescript-lsp-linter nil)
      (vue :variables vue-backend 'lsp)
      html semantic dap themes-megapack dwuggh
      (haskell :variables haskell-completion-backend 'lsp))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Confirmed.
<details><summary>
System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 78176ff6f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git helm html javascript
 (latex :variables latex-build-command "LatexMk" latex-enable-magic t)
 (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
 multiple-cursors
 (org :variables org-agenda-files '("~/org/notes.org"))
 python ruby
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 themes-megapack treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>
