### ISSUE TITLE
Shell layer depends on persp-mode

### ISSUE THREAD

**Issue by jstaursky** [syl20bnr/spacemacs#13610]
#### Description :octocat:
Omitting ```persp-mode``` prevents terminal shell to open.
I don't really like default behavior of spacemacs, which is to reopen the file(s) I was last working on.
Often I am cloning or working on something in ```/tmp``` and so a restart removes these files anyway.
Point is, I like to start fresh upon every open to spacemacs to the home page.
Because of this I put ```persp-mode``` in my omitted package list. However this seems to affect the ```shell``` layer
as upon ```SPC ` ```  I receive the error ```Symbols function definition is void: safe-persp-mode```

#### Reproduction guide :beetle:
- Start Emacs
- put following in ```dotspacemacs-configuration-layers```
```elisp
     (shell  :variables
             shell-default-term-shell "/usr/bin/zsh" ; or similiar
             shell-default-height 30
             shell-default-position 'bottom)
```
- put following in ```dotspacemacs-excluded-packages```
```elisp
     persp-mode
```
- restart spacemacs
- type  ```SPC ` ```  to try and open ansii-shell.

*Observed behaviour:* :eyes: :broken_heart:
typing  ```SPC ` ```  causes spacemacs to respond ```Symbols function definition is void: safe-persp-mode```
and no shell is opened

*Expected behaviour:* :heart: :smile:
shell opens to default directory (or to whatever directory you are in for the buffer you are editing)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c6f47bd87)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml clojure typescript html csv
      (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion t spell-checking-enable-auto-dictionary t)
      rust graphviz javascript
      (python :variables python-backend 'lsp python-lsp-server 'pyls)
      html
      (perl5 :packages
             (not company-plsense))
      latex helm
      (org :variables org-enable-sticky-header t)
      pdf git
      (version-control :variables version-control-diff-side 'left version-control-diff-tool 'diff-hl)
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete :disabled-for org spacemacs-org)
      emacs-lisp markdown multiple-cursors
      (shell :variables shell-default-term-shell "/usr/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
      syntax-checking treemacs
      (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-adopt-subprojects t)
      (lsp :variables lsp-ui-sideline-enable nil lsp-ui-doc-enable nil))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER LCMS2 GMP

**Comment by LuisChDev** [comment]
Are you sure this is the default behavior of Spacemacs? Just backed up my .spacemacs and opened a fresh develop instance, and it just shows the home buffer on restart (only other two buffers are `*messages*` and `*scratch*`). Check the value of the variable `desktop-save-mode`, and if possible, upload your `dotspacemacs/user-init` and `dotspacemacs/user-config`.

**Comment by jstaursky** [comment]
Not at computer arm, but I'll upload a gif later to clarify the behavior.

**Comment by jstaursky** [comment]
hmm wasn't able to reproduce in any quick gif examples, but it looks like I am facing a similiar issue to what was mentioned  [here](https://www.reddit.com/r/emacs/comments/8uxuj1/anyone_use_perspmode_it_doesnt_seem_like_what_i/) so I may just not have a very good understanding on of persp-mode.

regardless, my issue with adding `persp-mode` to `excluded-packages` and being unable to open a terminal (error being `symbols function definition is void: safe-persp-name`) still stands. Pull'd in latest dev updates today and updated all packages.

**Comment by emacs18** [comment]
If you don't want spacemacs to re-open files when it starts up, then you can make that happen simply by removing the following line from `~/.spacemacs`:

```elisp
(spacemacs/load-spacemacs-env)
```
I have always commented out this line for me so that I always get fresh emacs each time emacs starts up.

**Comment by emacs18** [comment]
It appears my previous comment was misplaced, i.e., I think it was meant for another issue.  Sorry.

I think something like the following can fix the reported problem.

```diff
diff --git a/layers/+spacemacs/spacemacs-layouts/funcs.el b/layers/+spacemacs/spacemacs-layouts/funcs.el
index 8e98df730..98549b9bc 100644
--- a/layers/+spacemacs/spacemacs-layouts/funcs.el
+++ b/layers/+spacemacs/spacemacs-layouts/funcs.el
@@ -38,7 +38,9 @@
 
 (defun spacemacs//current-layout-name ()
   "Get name of the current perspective."
-  (safe-persp-name (get-frame-persp)))
+  (if (fboundp 'safe-persp-name)
+      (safe-persp-name (get-frame-persp))
+    "Default"))
 
 (defun spacemacs//layout-autosave ()
   "Perspectives mode autosave.
```

If `persp-mode` is excluded, then `safe-persp-name` won't be defined.  Hence adding a check to use it only when it is defined seems to be the logical solution.

**Comment by jstaursky** [comment]
no long seems to be an issue. Thank you!
