### ISSUE TITLE
Helm behaviour for org-match-sparse-tree should be similar to helm-find-files

### ISSUE THREAD

**Issue by vr00m** [syl20bnr/spacemacs#13624]
As illustrated in the image, helm's behaviour for `"C-c / m"` or `org-match-sparse-tree` needs to be more nuanced.

The input being asked here is not just tags, it is an argument having its own DSL , and multiple functionalities folded into one string. So, when the user types in input which does not match any of the tags simply, then the completion system should discard the tags suggestions completely, and use the input string as is.

![helm-issue](https://user-images.githubusercontent.com/306456/82917385-082ab880-9f7c-11ea-802f-847b3bbd5d5d.png)

I have the same issue with org-agenda-set-tags. For new tags, so many times I've mistakenly entered the wrong tags because helm 'helpfully' guessed that the new different tag/text that I entered manually, should actually be replaced by some pre-existing tag.

One usually expects to just type the text one wants and hit enter. Here, helm interferes in the workflow by making you check and be sure that your text-input hasn't been auto-completed to a _completely_ different thing.

I've searched for 2 days for some helm setting to change this behaviour, but unable to find it. There really should be a one point setting for this.

**Comment by duianto** [comment]
This should probably be reported upstream in the helm repository:
https://github.com/emacs-helm/helm

Currently there's a variable called: `helm-ff--move-to-first-real-candidate`
That has the default value: `t`
https://github.com/emacs-helm/helm/blob/6c7d4153a61d208ca5dd90e17070f4a8556d5177/helm-files.el#L719

And there's a function with the same name (without the double dash): `helm-ff-move-to-first-real-candidate`
https://github.com/emacs-helm/helm/blob/6c7d4153a61d208ca5dd90e17070f4a8556d5177/helm-files.el#L2415

And a function with the name: `helm-comp-read--move-to-first-real-candidate`
https://github.com/emacs-helm/helm/blob/6c7d4153a61d208ca5dd90e17070f4a8556d5177/helm-mode.el#L479

Maybe a similar variable could be added for non find files helm buffers.
