### ISSUE TITLE
treemacs-icons-dired-mode is not setup correctly

### ISSUE THREAD

**Issue by emacs18** [syl20bnr/spacemacs#13620]
`treemcs-icons-dired-mode` fails to work the very first time `dired-mode` is entered with the following error message:

    treemacs-icons-dired--display: Wrong type argument: char-or-string-p, nil 

Here is how to see the problem.

1.  Start spacemacs
2.  Hit `SPC 0` to start treemacs.
3.  Hit `SPC 1` to select main window.
4.  `SPC f f` then `ENTER` to start `dired-mode` on home directory.

The problem is not seen if steps `#2` and `#3` are omitted.

Following is a potential fix to this problem.

    diff --git a/layers/+filetree/treemacs/packages.el b/layers/+filetree/treemacs/packages.el
    index eba752240..b98fa09fc 100644
    --- a/layers/+filetree/treemacs/packages.el
    +++ b/layers/+filetree/treemacs/packages.el
    @@ -97,7 +97,7 @@
     
     (defun treemacs/init-treemacs-icons-dired ()
       (use-package treemacs-icons-dired
    -    :hook (dired-mode . treemacs-icons-dired-mode)))
    +    :config (treemacs-icons-dired-mode)))
     
     (defun treemacs/pre-init-winum ()
       (spacemacs|use-package-add-hook winum

Above is how treemacs web page says to setup `treemacs-icons-dired-mode`, i.e., at config time rather than via mode hook. An alternate solution is to make this change in treemacs:

    diff --git a/src/extra/treemacs-icons-dired.el b/src/extra/treemacs-icons-dired.el
    index aeb5c7d..29b5602 100644
    --- a/src/extra/treemacs-icons-dired.el
    +++ b/src/extra/treemacs-icons-dired.el
    @@ -129,6 +129,8 @@ This will make sure the icons' background colors will align with hl-line mode."
           (progn
             (treemacs--setup-icon-background-colors)
             (add-hook 'dired-after-readin-hook #'treemacs-icons-dired--display)
    +        (unless (member 'treemacs--select-icon-set dired-mode-hook)
    +          (treemacs--select-icon-set))
             (add-hook 'dired-mode-hook #'treemacs--select-icon-set)
             (add-hook 'dired-mode-hook #'treemacs-icons-dired--enable-highlight-correction)
             (advice-add 'ranger-setup :before #'treemacs--select-icon-set)

This is to make sure that dired mode icons are setup properly on the very first `dired-mode`.
The issue is that `treemacs--select-icon-set` added to `dired-mode-hook` allows future `dired-mode` to work, but not the current `dired-mode` being setup.

More detailed analysis of the `nil` variable problem follows. The problem is that `treemacs--select-icon-set` function is not called for the very first `dired-mode`. Hence treemacs icons are not setup. Specifically `treemacs-icon-dire-closed` variable is `nil` within `treemacs-icons-dired--display-icons-for-subdir`. This is why we get the "Wrong type argument" error.

If above change to use `:config` rather than `:hook` is acceptable, then I can submit a PR.

**Comment by smile13241324** [comment]
@emacs18 can you double check whether the merged fix solved your issue? I seem to not longer be able to reproduce it on my side.

**Comment by emacs18** [comment]
Following works fine in that dired mode comes up with treemacs icons shown properly:
```
emacs26 --eval '(find-file "~/")'
```
However this does not work if treemacs is used first before creating a dired buffer, i.e.,
```
emacs26 --eval '(progn (treemacs-select-window)  (find-file "~/"))'
```
fails with the following error
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  treemacs-icons-dired--display-icons-for-subdir("/home/kimr/repos/e/emacs/admin/" #<marker at 1 in admin>)
  treemacs-icons-dired--display()
  run-hooks(dired-after-readin-hook)
  dired-readin()
  dired-internal-noselect("~/repos/e/emacs/admin/" nil)
  dired-noselect("/home/kimr/repos/e/emacs/admin" nil)
  dired("/home/kimr/repos/e/emacs/admin")
  treemacs-visit-node-no-split(nil)
  funcall-interactively(treemacs-visit-node-no-split nil)
  call-interactively(treemacs-visit-node-no-split nil nil)
  command-execute(treemacs-visit-node-no-split)
```
However this problem comes up only on the very first dired-buffer.  Subsequent dired buffers are setup properly without errors.

**Comment by smile13241324** [comment]
Strange, this seems to work on my system, Manjaro with emacs 26.3, at least on latest develop with latest version of tickets.

Though spacemacs doesn't start in the opened buffer, rather it restores the previous layout but this may come from my dotfile.

**Comment by emacs18** [comment]
I'm going to close this for now, because above steps to reproduce the problem no longer work for me either.
