### ISSUE TITLE
goto definition doesn't work in typescript files

### ISSUE THREAD

**Issue by NANASHI0X74** [syl20bnr/spacemacs#13628]
#### Description :octocat:
~goto definition doesn't work in typescript files~ actually, I just fixed this myself, apparently typescript-mode wasn't activated in the buffer by default for some reason, activiating it fixed the problem

#### Reproduction guide :beetle:
- Start Emacs
- load a typescript file/buffer
- move point onto symbol
- press `g d`

*Observed behaviour:* :eyes: :broken_heart:
I get asked to provide a tags file, press enter, then I get "no jump handler was able to find this symbol" or it just highlights the symbol

*Expected behaviour:* :heart: :smile:
jumps to a different buffer with the definition of the symbol

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23976ab79)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((typescript :variables typescript-backend 'lsp)
 auto-completion better-defaults emacs-lisp git helm lsp markdown multiple-cursors org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by cmatzenbach** [comment]
Yeah I was not able to reproduce on the develop branch either.  `gd` works just fine.  This ticket should be closed.

**Comment by NANASHI0X74** [comment]
Yeah, the only thing that tripped me up though is that typescript mode wasn't activated when I loaded the file... maybe it's because I installed the layer just after loading the file via the prompt suggesting to install the layer?

**Comment by cmatzenbach** [comment]
Yeah that might be it.  The layer installed, but the file remained in the basic layer.  I guess that could be a future improvement, but with all the other work currently going on with this project, I don't think it's that important.  I'm assuming everything works fine for you now?

**Comment by NANASHI0X74** [comment]
Yeah, everyhting works for me now... I guess this issue may not need to be open. What's weird though is that restarts didn't fix it, so it tripped me up for a while. I guess emacs remembered which mode I was in last.

I'd try to push a fix myself, but I'm completely new to emacs, I only switched to it from nvim last week.
