### ISSUE TITLE
Windows 7 installation

### ISSUE THREAD

**Issue by sebastian-schmidt** [syl20bnr/spacemacs#1362]
Hi i tried to install spacemacs, but it would not download the dependencies.

```
Contacting host: elpa.gnu.org:80
Entering debugger...
```
it would not find gpg, which is not on my path.
Used this as a workaround:
http://emacs.stackexchange.com/questions/949/using-elpa-in-batch-mode-on-windows-fails
added `(setq package-check-signature nil)` to init.el
After a new start it loaded all the packages and after a second start it was ok.

Maybe this should be added to the faq for windows user.
Cheers and thanks for spacemacs

**Comment by tuhdo** [comment]
I am using this [64 bit build on Windows](http://emacsbinw64.sourceforge.net/) and it works for me without problem. Are you using the GNU build? If so, probably it's missing GnuTLS library so that it cannot verify with the server because the library is not included by default.

**Comment by sebastian-schmidt** [comment]
I used this:
http://semantic.supelec.fr/popineau/programming-emacs.html#sec-2

**Comment by tuhdo** [comment]
That was almost a year ago. Back then it was good but I remember I got problem with installing packages. The version there is the old development 24.4 version, not the released version and the author seems not to maintain it anymore. You should try the 64 bit build I linked. It works for me on both Windows machine

**Comment by tuhdo** [comment]
Now Emacs is 24.5. already.

**Comment by sebastian-schmidt** [comment]
Got emacs 24.5 (release) from your link and everything installed fine.

**Comment by andyjim47** [comment]
Hope it's ok to tag along with this thread, as it's on the general topic.  Let me know if I should start another thread instead.
Complete newbie here, hoping you can help me get Spacemacs up and running on Windows 7.  I’m not a programmer, not a geek.  My interest in Spacemacs relates to writing, journaling, notes, organization.  So please assume I know practically nothing if you try to help me.  

I have used Vim about a week and like it, and my interest in Spacemacs springs in part from that, in part from frustration with all other software (too long a story to tell here) and hoping Spacemacs will help me.  I’ll accept the learning curve to give it a try.

Ok, here’s where I am.  I just installed Emacs.  Here is the version:
GNU Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2015-04-22 on KAEL
Got it here:  http://sourceforge.net/projects/emacsbinw64/?source=typ_redirect 

I have downloaded Spacemacs, but slightly confused because there are two files sets, one called ‘spacemacs’, the other called ‘spacemacs-master’, which also includes ‘spacemacs’.  

Which one do I use and where do I put it?
And after putting spacemacs in the right place, what next to get up and running in Emacs?  Please go step by step.  I know nothing.

Sorry for the dumb questions, but I’ve been unable to decipher this from the Spacemacs documentation, as it seems to assume knowledge that I don’t have.  I think it assumes at least that I’m an experienced Emacs user.  I am not.

andyjim

**Comment by tuhdo** [comment]
How did you download Spacemacs? Have you installed Git and run this command:

```sh
git clone --recursive http://github.com/syl20bnr/spacemacs ~/.emacs.d
```

Emacs loads everything in there and automatically download necessary plugins. You don't have to do anything unless you want to add more features.

**Comment by andyjim47** [comment]
That worked this time.   Yesterday, with a different Emacs version, it didn't.  What a dizzying process, but Spacemacs is up and running now.  Thanks much.  

Now could you give me one or two more pointers?  Maybe from here it's just a matter of reading documentation, but the documentation seems to assume a lot of emacs knowledge.  I realize I'll have to have some Emacs knowledge though, so if you'd just point me in a good direction I'll plow ahead.

**Comment by tuhdo** [comment]
Here is a [good tutorial](http://ian.mccowan.space/2015/04/07/Spacemacs/) for beginner.

**Comment by andyjim47** [comment]
Thanks tuhdo, I'm on my way.  I see the evil tutor in Spacemacs, and that's great.  Personally I think it would be good to have a greeting page on start up similar to Emacs with links to the evil tutor (which I had to learn about elsewhere) and also an interactive Spacemacs tutorial, probably two or three of them from beginner level on up.  If these were briefly summarized on the greeting page, the new user could decide what tutes he/she needs.  

In my case, with no emacs and almost no Vim experience, I need them all.  Yep, I'll dig into the documentation, but tutorials are a nice narrative-like way to get acquainted.  It would help me grasp the capabilities that for now are unknowns for me.  These (or some of them anyway) should be geared to the complete dummy who knows nothing.  Assumption of prior knowledge is very frustrating to the complete beginner.  Examples of how such-and-such capability can be used, etc would be great. I'm sure the user could configure to skip the intro page when he/she no longer needs it.

I'll qualify my opinion on this by acknowledging that I'm probably in a very small minority of non-programmers who are interested in Spacemacs for writing and organization, so perhaps it's not worth writing tutes for my class of new users.

I'm looking forward to this adventure.  Cheers, andyjim

**Comment by syl20bnr** [comment]
@andyjim47 I guess you want `org`. :-)

Once you have spacemacs up and running which seems to be the case, press `SPC f e d` which opens the file `.spacemacs` stored in your user directory. There look for the variable `dotspacemacs-configuration-layers` and uncomment the `;; org` line then press `C-c C-c` to install it. To use `org` you have to be in a `org` buffer, opening a file with extension `.org` automatically set the buffer to major-mode `org`.

Note that in the next version `C-c C-c` has been replaced by `SPC f e R`.

I hope you'll enjoy emacs for notes taking.

**Comment by tuhdo** [comment]
> Thanks tuhdo, I'm on my way. I see the evil tutor in Spacemacs, and that's great. Personally I think it would be good to have a greeting page on start up similar to Emacs with links to the evil tutor (which I had to learn about elsewhere) and also an interactive Spacemacs tutorial, probably two or three of them from beginner level on up. If these were briefly summarized on the greeting page, the new user could decide what tutes he/she needs.

The next release will have this :). When you start, there will be a `[?]` button that you can click to learn basic navigation on home buffer and link to evil or emacs tutor. The home screen looks nicer to. If you want to try, `cd ~/.emacs.d` and then `git checkout develop`. If you done testing and want to use stable master, `git checkout master`.

**Comment by andyjim47** [comment]
Thank you, I would like to dig into org (heaven help me!).  I don't see the
'dotspacemacs-configuration-layers' variable in the file you led me to.  A
search in Explorer does not find a '.spacemacs' file.  Here are the
contents of the file that opened with SPC f e d.  In Spacemacs I do not see
a filename for this buffer.
*********************************************************************************
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (zenburn-theme window-numbering volatile-highlights vi-tilde-fringe
smooth-scrolling rfringe rainbow-delimiters powerline popup paradox
page-break-lines neotree multi-term move-text monokai-theme linum-relative
leuven-theme info+ indent-guide ido-vertical-mode hungry-delete hl-anything
highlight-numbers highlight-indentation helm-themes helm-swoop
helm-projectile helm-mode-manager helm-make helm-flyspell helm-descbinds
helm-c-yasnippet helm-ag guide-key-tip google-translate golden-ratio
fringe-helper flx-ido fill-column-indicator fancy-battery expand-region
exec-path-from-shell evil-visualstar evil-tutor
evil-terminal-cursor-changer evil-surround evil-search-highlight-persist
evil-numbers evil-nerd-commenter evil-matchit evil-lisp-state evil-jumper
evil-indent-textobject evil-iedit-state evil-exchange evil-escape evil-args
evil-anzu eval-sexp-fu elisp-slime-nav buffer-move base16-theme
auto-highlight-symbol auto-dictionary aggressive-indent adaptive-wrap
ace-window ace-link ace-jump-mode names anzu iedit smartparens highlight
flx pos-tip guide-key s popwin yasnippet projectile helm async parent-mode
spinner pkg-info epl evil-leader evil use-package bind-key dash)))
 '(ring-bell-function (quote ignore)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
****************************************************
Thanks,
Andy

**Comment by syl20bnr** [comment]
Do you have an old version of spacemacs ?
Be sure to have the last version, delete the `.spacemacs` file and restart emacs. Spacemacs should ask you what kind of key bindings you are using. Then press `SPC f e d` and you should have a valid `.spacemacs` file.

**Comment by andyjim47** [comment]
That worked, Thnx.  I'll be back for more help soon, I'm sure.
Andy

**Comment by andyjim47** [comment]
Well I'm back for more noob help.  When I launched Spacemacs this morning
it found 4 new packages to install, and said 'fetching new package
repository indexes'.  But then, one by one, it reported the packages
unavailable.  The 4 packages are:

(org) :evil-org
(org) :org-bullets
(org) :org-pomodora
(org) :org-repo-todo

My pace will be slow in learning.  I'll take it in small bites.  I do think
org-mode is what I need.  Thnx for help.
Andy

**Comment by idbrii** [comment]
@andyjim47: What version of spacemacs do you have now (it displays at the top of the startup buffer or `SPC b h`?

Did you do both of [the update steps](https://github.com/syl20bnr/spacemacs#update)?

**Comment by andyjim47** [comment]
Thanks for your reply David.
I have version 0.101.2
I just tried to update.  I clicked the Update button on the opening page.
It said Updating Spacemacs, etc, then:
--> fetching new package repository indexes

And there it hung...

Message at bottom:
Invalid version string: 'nil'

Since that step didn't seem to work I didn't try step 2.  I'm in Win7.

-Andy

**Comment by idbrii** [comment]
I'm still new, so I'm stumped. 

You could rename your .emacs.d and your .spacemacs and try re-cloning as tuhdo instructed above. Then bring your .spacemacs settings back over. It's possible that there's something in there that's breaking something.

**Comment by StreakyCobra** [comment]
There is people using Spacemacs on Windows 7, and there don't seem to be too much problems with its installation, as confirms the 6 months without news on this issue. I'm closing it, but feel free to open a new one in case of trouble :relaxed:
