### ISSUE TITLE
Powerline has graphical glitches with solarized-dark theme

### ISSUE THREAD

**Issue by ZornsLemma** [syl20bnr/spacemacs#13623]
#### Description :octocat:
When I use the solarized-dark theme, the powerline shows graphical glitches.

#### Reproduction guide :beetle:
- Start with no installation:
```
~$ ls -l .spacemacs .emacs .emacs.d
ls: cannot access '.spacemacs': No such file or directory
ls: cannot access '.emacs': No such file or directory
ls: cannot access '.emacs.d': No such file or directory
```
- Install the 'develop' version:
```
~$ git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
Cloning into '/home/steven/.emacs.d'...
[...]
~$ cd .emacs.d
~/.emacs.d$ git checkout develop
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Switched to a new branch 'develop'
~/.emacs.d$ git rev-parse HEAD
1ec43e7262238c66258cacc2f68e5b706c9248d7
```
- Start emacs, choose 'vim' and 'standard distribution', let the packages install.
- At this point the powerline looks fine, as in the attached screenshot spacemacs-good-powerline.png.
- Edit ~/.spacemacs to specify solarized themes:
```
   ;; List of themes, the first of the list is loaded when spacemacs starts.
   ;; Press `SPC T n' to cycle to the next theme in the list (works great
   ;; with 2 themes variants, one dark and one light)
   dotspacemacs-themes '(solarized-dark
                         solarized-light)
```
- Close emacs and re-open it; wait for it to install the solarized theme.

*Observed behaviour:* :eyes: :broken_heart:
Once the solarized theme is installed, the powerline has graphical glitches; the attached screenshot spacemacs-bad-powerline.png shows this:
  - the curves no longer reach the top of the powerline
  - the bottom row of pixels has an odd mix of colours (e.g. underneath the "821 \*spacemacs\*" text, there is a different-coloured row of pixels on the bottom line)
![spacemacs-bad-powerline](https://user-images.githubusercontent.com/7988240/82854203-a3ca1380-9eff-11ea-8ac6-9ed903f01f95.png)
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
Installing the solarized theme should not introduce these glitches. The overall colours of the powerline should change, but it should otherwise look similar to spacemacs-good-powerline.png:
![spacemacs-good-powerline](https://user-images.githubusercontent.com/7988240/82854206-a593d700-9eff-11ea-9187-1ae7a5711a98.png)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1ec43e726)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

The operating system is Ubuntu 18.04.4 x86-64.

**Comment by jr0cket** [comment]
In `.spacemacs` adjust the separator scale value to correct the mode line theme size.  This value is included in the configuration for this purpose.  The default is `1.5`, try a larger scale such as `1.8`

```
   dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 1.8)
```

The font and font size can also affect the mode line theme.  I am using doom-solarized-light with Ubuntu Mono font with normal weight and width and no noticeable issue with the mode line theme separators with either `wave` or `arrow`.

**Comment by ZornsLemma** [comment]
If I just use doom-solarized-dark or doom-solarized-light it works perfectly, so in practice that solves my problem; I don't even need to alter the separator-scale. Thanks for your help!

However, in case it's of interest, with solarized-dark:

- If I change the separator-scale to 1.8, the initial spacemacs loading screen doesn't look any different. However, if I interact with spacemacs (e.g. pressing ESC ESC) the powerline suddenly gets larger.

- separator-scale 1.8 does fix the problem where the curves don't reach the top of the powerline, but it doesn't remove the oddly coloured pixels on the bottom line of the powerline.

**Comment by Nequo** [comment]
I have the same issue with the regular spacemacs theme. Powerline separators are only small on the dashboard but get fixed when opening a buffer. I am using the latest develop branch and JetbrainsMono set to size 13. Will experiment further with fonts..

**Comment by lebensterben** [comment]
For future references
Please report this to upstream https://github.com/TheBB/spaceline
