### ISSUE TITLE
 font settings such as doom-emacs

### ISSUE THREAD

**Issue by ALipAkrohk** [syl20bnr/spacemacs#13634]
Hi, how can I set the font settings as shown below?
```
(setq doom-font (font-spec :family "JetBrains Mono" :size 24)
      doom-big-font (font-spec :family "JetBrains Mono" :size 36)
      doom-variable-pitch-font (font-spec :family "Overpass" :size 24)
      doom-serif-font (font-spec :family "IBM Plex Mono" :weight 'light))
```
I used these settings in doom-emacs.
But I don't understand its implementation in spacemacs.
Please help (sorry I don't write English well).

**Comment by cmatzenbach** [comment]
This should solve your issue (definitely in develop branch, not sure about master)

`  ;; Default font. `powerline-scale' allows to quickly tweak the mode-line
   ;; size to make separators look not too crappy.
   dotspacemacs-default-font '("Iosevka Term Medium"
                               :size 15
                               :size 12.0
                               :weight normal
                               :width normal
                               :powerline-scale 1.0)`

**Comment by lebensterben** [comment]
closing due to lack of feedback
