### ISSUE TITLE
flycheck-mix needs to be removed from elixir layer

### ISSUE THREAD

**Issue by qizwiz** [syl20bnr/spacemacs#13632]
#### Description :octocat:
`flycheck-mix` is no longer hosted by melpa

#### Reproduction guide :beetle:
- Start Emacs
- Install elixir layer
*Observed behaviour:* :eyes: :broken_heart:
spacemacs chokes on attempting to install flycheck-mix
*Expected behaviour:* :heart: :smile:
no errors on installation of elixir layer
#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23976ab79)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python systemd
        (elixir :variables elixir-backend 'lsp)
        csv graphviz auto-completion
        (colors :variables colors-enable-nyan-cat-progress-bar nil colors-colorize-identifiers 'variables)
        command-log common-lisp csharp dap
        (dash :variables dash-docs-docset-newpath "~/.local/share/Zeal/Zeal/docsets" zeal-at-point-zeal-version "0.6.1")
        debug docker elm emacs-lisp erc erlang geolocation git github gtags
        (haskell :variables haskell-completion-backend 'ghci haskell-process-type 'stack-ghci)
        helm html ibuffer imenu-list javascript lsp markdown multiple-cursors notmuch org pandoc parinfer phoenix
        (restclient :variables restclient-use-org t)
        (ruby :variables ruby-enable-enh-ruby-mode nil ruby-version-manager 'rvm ruby-test-runner 'minitest ruby-backend 'lsp)
        ruby-on-rails search-engine
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spacemacs-editing-visual
        (spacemacs-layouts :variables spacemacs-layouts-directory "~/.dotfiles/spacemacs-layouts/" layouts-enable-autosave t layouts-autosave-delay 1800)
        spotify sql syntax-checking syntax-checking templates themes-megapack
        (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t treemacs-use-collapsed-directories 3)
        twitter version-control
        (wakatime :variables wakatime-api-key "6ef19e49-f25b-4a1b-802f-89f81c9c0db1" wakatime-cli-path "/usr/local/bin/wakatime")
        yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by smile13241324** [comment]
I am not familiar with the elixier environment, @qizwiz is that package gone completely or has it just been removed from melpa and could be pulled from a different source i.e. github?

**Comment by qizwiz** [comment]
The author (@tomekowal) of the package has deprecated and removed it from MELPA in favor of using lsp.

See: [tomekowal/flycheck-mix](https://github.com/tomekowal/flycheck-mix)

**Comment by tomekowal** [comment]
Hey! The package provided flycheck errors by using `MIX_ENV=test mix compile` command from Elixir. That was a good solution for the old times. Now elixir layer provides two backends: alchemist and lsp. Both of them have error reporting covered, so my package is redundant. I'll check what parts of it are in Spacemacs and I'll try to remove it from the layer.

**Comment by tomekowal** [comment]
When I removed my deprecated package and any traces of its config, `lsp` backend correctly used its own checker. I am not sure how `alchemist` backend will deal with the change. Do you use `alchemist` backend to test if `flycheck` still works with it? I believe it should.

**Comment by smile13241324** [comment]
I have merged @tomekowal's PR and removed all remaining references to flycheck-mix in the README and layer variables. @qizwiz can you test whether flycheck integration still works with alchemist and lsp?

**Comment by qizwiz** [comment]
Yeah, I'll let you know as soon as I can get to it.

**Comment by lebensterben** [comment]
closing since it's removed in https://github.com/syl20bnr/spacemacs/commit/653fbab6bc9983eb3293ea08212016a0496fbfdc
