### ISSUE TITLE
How do I specify indent-region-function for c++-mode?

### ISSUE THREAD

**Issue by SleepyBag** [syl20bnr/spacemacs#13630]
When I paste something, spacemacs do some indent through indent-region-function. Currently, this function is `lsp-format-region`. I'd like to change it to a simpler function because it sometimes messes my code up. So I tried

```
 (add-hook 'c++-mode-hook (lambda () (setq-local indent-region-function #'c-indent-region)))
```

but it didn't work. When I open a C++ file, `indent-region-function` is still `lsp-format-region` and it is called when I paste something.

I'm not familiar with the processing of emacs setting these variable. So I'm seeking for your help. Thank you!

**Comment by yyoncho** [comment]
use lsp-managed-mode-hook

**Comment by SleepyBag** [comment]
Thank you for your reply!
