### ISSUE TITLE
emacs --insecure,but hit: unknow option --insecure

### ISSUE THREAD

**Issue by whaozl** [syl20bnr/spacemacs#13644]
who can help me ?
```shell
$emacs --insecure
```
but hit: unknow option --insecure

**Comment by emacs18** [comment]
I cannot find any mention of --insecure option in emacs manual or online help, i.e.,
`emacs --help | grep insecure` prints nothing.

Can you explain why you think --insecure is a valid emacs option?

**Comment by alexey0308** [comment]
@whaozl Is it related? 
https://github.com/syl20bnr/spacemacs/issues/5284#issuecomment-189866513

**Comment by duianto** [comment]
alexey0308 seems to be correct. At least the error message is the same in that issue: https://github.com/syl20bnr/spacemacs/issues/5284#issuecomment-189862689

@whaozl Can you test if the steps in this comment work for you: https://github.com/syl20bnr/spacemacs/issues/5284#issuecomment-189866513
>be sure to remove your old .emacs file first, it's probably why .emacs.d/init.el of Spacemacs is not used. Also --insecure is a Spacemacs option, so be sure to use it when you start with the Spacemacs config. As @TheBB said, be sure to remove elpa first before starting again with --insecure

That issues author said that the suggestion worked.

If it also works for you, then you can close this issue.

**Comment by whaozl** [comment]
thank you very much, it is related.
