### ISSUE TITLE
Auto-indentation on paste is broken

### ISSUE THREAD

**Issue by nertpinx** [syl20bnr/spacemacs#13646]
#### Description :octocat:
When pasting the `spacemacs//yank-indent-region` function indents differently than `indent-region`.

#### Reproduction guide :beetle:
- Start Emacs
- Open a C file.
- Paste part of code somewhere

*Observed behaviour:* :eyes: :broken_heart:
The code is indented with wrong offset (2 spaces) and needs to be fixed by indenting the whole thing as an extra command.  It also indents way too many lines below the pasted one (e.g. indenting whole condition body when just pasting in a condition) and indents things that are past 80 characters.  This makes fixing it back very annoying, especially when this auto-indentation cannot be disabled by an easy toggle or variable change.

*Expected behaviour:* :heart: :smile:
Only affected code is indented and it respects the same indentation rules as when marking a region and pressing `<TAB>`.  And if not that then at least there would be a way to turn the auto-indentation after paste off globally.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 23976ab799b0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm version-control
            (markdown :variables markdown-live-preview-engine 'vmd)
            org semantic
            (lsp :variables lsp-rust-server 'rust-analyzer lsp-rust-analyzer-server-display-inlay-hints t)
            cscope
            (c-c++ :variables c-c++-enable-clang-support t)
            (python :variables python-shell-prompt-regexp "In \\[[0-9]+\\]: " python-indent-guess-indent-offset-verbose nil python-shell-prompt-detect-failure-warning nil)
            (shell :variables shell-default-position 'right shell-default-shell 'multi-term term-bind-key-alist
                   '(("C-c C-c" . term-interrupt-subjob)
                     ("C-k" . term-send-kill-line)
                     ("C-p" . previous-line)
                     ("C-n" . next-line)
                     ("C-m" . term-send-return)
                     ("C-y" . term-paste)
                     ("M-f" . term-send-forward-word)
                     ("M-b" . term-send-backward-word)
                     ("M-p" . term-send-up)
                     ("M-n" . term-send-down)
                     ("<M-backspace>" . term-send-backward-kill-word)
                     ("<C-backspace>" . term-send-backward-kill-word)
                     ("<C-left>" . term-send-backward-word)
                     ("<C-right>" . term-send-forward-word)
                     ("M-d" . term-send-delete-word)
                     ("M-." . term-send-raw-meta)
                     ("M-y" . term-send-raw-meta)
                     ("C-/" . term-send-raw))
                   term-unbind-key-alist
                   '("C-c" "C-x" "C-h" "C-y"))
            (shell-scripts)
            (spell-checking :variables ispell-program-name "hunspell-emacswrapper")
            treemacs version-control erc mu4e xkcd
            (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
            gnus selectric ocaml
            (rust :variables rust-format-on-save t)
            (docker :variables docker-dockerfile-backend 'lsp)
            dap imenu-list major-modes html javascript)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB OLDXMENU X11 XDBE XIM THREADS

#### Backtrace :paw_prints:
```

```

**Comment by nertpinx** [comment]
Of course I removed unrelated e-mail addresses and private things from the layer list.

Also for now I have an ugly workaround:
``` emacs-lisp
  (dolist (func '(yank yank-pop evil-paste-before evil-paste-after))
    (advice-remove func #'spacemacs//yank-indent-region))
```

**Comment by nertpinx** [comment]
I also find out that the auto-indentation has the same result as `M-m j =` which is `spacemacs/indent-region-or-buffer` and `indent-region` (which is bound to `C-M-\` although the combination throws a user-error even when calling the function interactively works), but that does not conform to what `TAB` does, which calls `c-indent-line-or-region`.

**Comment by alexey0308** [comment]
lsp-mode changes `indent-region-function`.
Does it help, if you use in the `(defun dotspacemacs/user-config () ...`
```
  (add-hook 'c-mode-hook (lambda () (setq-local lsp-enable-indentation nil)))
```
or use 
```
(lsp :variables
       lsp-enable-indentation nil)
```
in the lsp-mode settings?

**Comment by nertpinx** [comment]
Looks like that could do the trick, thanks.

@alexey0308 do I understand it correctly that it would also be solved by properly setting up the language server configuration (e.g. `.clang-format` in case of C)?  That would be the best resolution for me, even though it would require creating few files based on my `.dir-locals.el`.

**Comment by alexey0308** [comment]
That's right, you are to choose, whether to use c-mode native indentation or lsp-based.
I agree that it is better to use .clang-format for a project, it helps non-emacs users as well to comply to the rules.

**Comment by nertpinx** [comment]
Forgot to close this as it is basically explained by https://github.com/syl20bnr/spacemacs/issues/13646#issuecomment-648955999 . Thanks again.
