### ISSUE TITLE
Upstream use-package patch: User :post-config not run when there is no :config

### ISSUE THREAD

**Issue by jjlee** [syl20bnr/spacemacs#13649]
This is a straightforward one-liner fix for [a use-package bug](https://github.com/jwiegley/use-package/issues/785) that I've posted [a patch for upstream](https://github.com/jwiegley/use-package/pull/840).  I think it would be good to get the nod of approval for from a core spacemacs developer before it's applied there, because though I think it's clearly the right fix, there is always some potential with this sort of thing for breaking marginal user configurations: in this case ones that contain untested user config that currently never runs, and so might break when use-package is fixed to run it as specified.

User perspective: I think this bug is the main reason that I've found configuring spacemacs confusing since I started using it.  Before investigating this in detail, I was often confused about why sometimes `spacemacs|use-package-add-hook` "doesn't work" and I'd have to use `with-eval-after-load` instead.  Configuration of this kind ended up split up into parts that used the spacemacs-recommended `spacemacs|use-package-add-hook` way in a personal layer, and parts that used `with-eval-after-load` in my `.spacemacs`, when I would have preferred to keep it in one place.  Also, currently if a spacemacs package removes a `:config`, user configuration using `spacemacs|use-package-add-hook` will stop being run.  That's a bad thing, since ideally configuration code should try to be as independent as possible of other configuration code, and typically will result in user-configurations stopping working for them without obvious reason.

The issue is that when you write configuration in the recommended way, using `spacemacs|use-package-add-hook` like this:

    (defun jjl/pre-init-evil-magit ()
      (spacemacs|use-package-add-hook evil-magit
        :post-config
        (spacemacs/set-leader-keys
          "gb" 'magit-blame)
        )

your `:post-config` will never be called if it so happens that the spacemacs package that you're configuring doesn't itself have a `:config` in its use-package declaration.

The patch brings the use-package behaviour into line with its documentation, which is to always call the hook even if there is no `:config`.

I've been using the patch for a month without problems, and one other user has [commented here](https://github.com/syl20bnr/spacemacs/issues/13545#issuecomment-633112557) that they've also used it without it causing any regressions for them.

Can somebody please take a look and give a thumbs up on [the PR](https://github.com/jwiegley/use-package/pull/840)?  Note the tests do pass, seems that use-package CI always fails right now.

**Comment by thanhvg** [comment]
It's amazing how far you have gone to fix this problem and communicate it to us spacemacs users. However I never encounter any problems you described. In the other link someone associated this bug with being unable to do `SPC l b` which I am able to do in all emacs versions I have from 26, 27 to 28 gccemacs build. I guessed this is a Heisenberg bug, some kind of race condition that only triggers at certain conditions.

But if it is a `use-package` bug then it should be fixed in `use-package`. If `spacemacs` has any problem with this fix I think you are the chosen one to save us.

Cheers!

**Comment by jjlee** [comment]
Hi @thanhvg

As far as I'm aware, this bug in use-package does not break any spacemacs features other than user configuration itself.

It is not a race condition, nor a Heisenbug.  Issue https://github.com/syl20bnr/spacemacs/issues/13545 is unrelated as far as I know -- what is related is rather the comment I linked to.

It should indeed be fixed in use-package.

Because it might affect spacemacs users, I thought it only polite and responsible to ask here and to make your life as a reviewer as easy as I can by describing it as clearly as I can and linking a comment with somebody other than me testing it out.  I'm a spacemacs user and I love spacemacs, so I'm here to "save" myself, as you put it, and sure, I imagine some other spacemacs users too.

Have a nice day.

**Comment by emacs18** [comment]
@thanhvg Using vanilla spacemacs develop branch files, does `SPC 0` work for you to bring up treemacs buffer on left?  For me this does not work.  It fails with 
```
winum-select-window-by-number: No window numbered 10
```
My work around for this now is to add the following line prior to loading spacemacs init files:
```elisp
(custom-set-variables '(use-package-inject-hooks t))
```
`use-package-inject-hooks` is set to `t` by spacemacs during startup, but not soon enough.  That is why setting it sooner works.

At first I thought that `SPC 0` failed to work due to use-package bug in question.  However even picking up the pending fix did not resolve `SPC 0` problem.

**Comment by thanhvg** [comment]
@emacs18 I don't use `treemacs`. I just installed the layer and did a quick check on `spc 0`. It seemed to work.

**Comment by emacs18** [comment]
Something is different between the two of us.  Using latest spacemacs develop branch code, and also using all packages that are no more than few days old, `SPC 0` does not work, because the code that sets up treemacs never gets called.  I can see this by applying the patch below.  The message added below is never printed in `*Messages*` buffer unless I set `use-package-inject-hooks` is set to t as explained above.  This is the case using emacs 26.3 as well as 27 that I built using latest source code.

```diff
diff --git a/layers/+filetree/treemacs/packages.el b/layers/+filetree/treemacs/packages.el
index eba752240..7c38cae2b 100644
--- a/layers/+filetree/treemacs/packages.el
+++ b/layers/+filetree/treemacs/packages.el
@@ -104,6 +104,7 @@
     :post-config
     (progn
       ;; `0', `M-0' and `C-x w 0' are bound to `winum-select-window-0-or-10'
+      (message "treemacs :post-config code reached")
       (define-key winum-keymap
         [remap winum-select-window-0-or-10] #'treemacs-select-window)
       ;; replace the which-key name
```

**Comment by emacs18** [comment]
Let me provide more details as to what I see and why I think something is wrong. In short spacemacs sets `use-package-inject-hook` variable too late for it to take effect. That is why almost all use of `use-package-hook-injector` within spacemacs is useless.

Below are few lines lifted from `*Messages*` buffer which detail spacemacs initialization sequence. I added one debug statement in `use-package-core.el` file prior to launching emacs, i.e., the line with `(message ...)` shown below. This change is to show the value of all important `use-package-inject-hooks` variable value at the time `use-package-hook-injector` is called.
```elisp
    (defun use-package-hook-injector (name-string keyword body)
      "Wrap pre/post hook injections around the given BODY for KEYWORD.
    The BODY is a list of forms, so `((foo))' if only `foo' is being called."
      (message "(use-package-hook-injector %s %s), use-package-inject-hooks=%s" name-string keyword use-package-inject-hooks)
      (if (not use-package-inject-hooks)
          body
        (let ((keyword-name (substring (format "%s" keyword) 1)))
          `((when (run-hook-with-args-until-failure
                   ',(intern (concat "use-package--" name-string
                                     "--pre-" keyword-name "-hook")))
              ,@body
              (run-hooks
               ',(intern (concat "use-package--" name-string
                                 "--post-" keyword-name "-hook"))))))))
```
As you can see if `use-package-inject-hooks` is nil, then the else-clause above will not be run and so hooks will not be run.

With the change above, following details sequence of events of interest. The first two lines show that `use-package-inject-hooks` is `nil` when `use-package-hook-injector` is called for `winum` package. Which means that `use-package--winum--post-config-hook` hook setup by `spacemacs|use-package-add-hook` (which in turn was called by `treemacs/pre-init-winum`) is simply ignored and never used.

    (use-package-hook-injector winum :init), use-package-inject-hooks=nil
    (use-package-hook-injector winum :config), use-package-inject-hooks=nil
    ...
    (use-package-hook-injector spacemacs-theme :init), use-package-inject-hooks=nil
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+distributions/spacemacs-bootstrap/packages.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+distributions/spacemacs-bootstrap/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-visual/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-purpose/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-project/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-navigation/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-modeline/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-evil/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-editing-visual/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-editing/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-layouts/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-completion/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-defaults/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+lang/emacs-lisp/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+completion/helm/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+misc/multiple-cursors/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+filetree/treemacs/funcs.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+distributions/spacemacs-bootstrap/config.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-modeline/config.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-evil/config.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-layouts/config.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-completion/config.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+spacemacs/spacemacs-defaults/config.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+lang/emacs-lisp/config.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+completion/helm/config.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+misc/multiple-cursors/config.el (source)...done
    Loading /home/kimr/repos/my/spacemacs-develop/layers/+filetree/treemacs/config.el (source)...done
    (Spacemacs) Loading auto-layer file...
    Loading /home/kimr/repos/my/spacemacs-develop/layers/auto-layer.el (source)...done
    (Spacemacs) + Configuring bootstrap packages...
    (Spacemacs) async -> init (spacemacs-bootstrap)...
    (Spacemacs) bind-key -> init (spacemacs-bootstrap)...
    (Spacemacs) bind-map -> init (spacemacs-bootstrap)...
    (Spacemacs) diminish -> init (spacemacs-bootstrap)...
    (Spacemacs) evil -> init (spacemacs-bootstrap)...
    (Spacemacs) hydra -> init (spacemacs-bootstrap)...
    (Spacemacs) use-package -> init (spacemacs-bootstrap)...

The last line is from the following function which sets `use-package-inject-hooks` to t, i.e., this is set to the correct value, but too late! It should have been set to t **before** calling `use-package-hook-injector`! This function is from `layers/+distributions/spacemacs-bootstrap/packages.el` file.
```elisp
    (defun spacemacs-bootstrap/init-use-package ()
      (require 'use-package)
      (setq use-package-verbose init-file-debug
            ;; inject use-package hooks for easy customization of stock package
            ;; configuration
            use-package-inject-hooks t)
      (add-to-list 'use-package-keywords :spacebind t))
```
This is using vanilla spacemacs files from the develop branch without any change (I have blank `~/.spacemacs` file) except the following one line change to to prevent spacemacs from removing my packages.
```diff
    diff --git a/core/templates/.spacemacs.template b/core/templates/.spacemacs.template
    index f8336b23d..4c76a96b8 100644
    --- a/core/templates/.spacemacs.template
    +++ b/core/templates/.spacemacs.template
    @@ -78,7 +78,7 @@ This function should only modify configuration layer settings."
        ;; installs only the used packages but won't delete unused ones. `all'
        ;; installs *all* packages supported by Spacemacs and never uninstalls them.
        ;; (default is `used-only')
    -   dotspacemacs-install-packages 'used-only))
    +   dotspacemacs-install-packages 'used-but-keep-unused))
     
     (defun dotspacemacs/init ()
       "Initialization:
```

**Comment by emacs18** [comment]
Please ignore my comments above.  It turned out that my problem was having activated use-package prior to starting spacemacs initialization process as detailed at https://github.com/syl20bnr/spacemacs/issues/13545

**Comment by syl20bnr** [comment]
Thank you for the upstream patch, I’ll comment on the linked issue.

Seems we have another issue unveiled here with some treemacs key bindings not being defined. Is it related to the original post or is it a different issue ? If the upstream fix does not fix the treemacs key bindings can you open a new issue about it ?

**Comment by emacs18** [comment]
Yes I'll submit new issues as needed.  Sorry for the noise (of bringing up another issue here).  Please close this issue ignoring my comments above.  If any issues remain, I will make sure to submit new issues.

**Comment by jjlee** [comment]
I raised this issue only with the intention of drawing attention to the potential for breaking working user configs (only if they're already kind of broken).  So I'm happy to close this.

Thanks for your attention everybody!
