### ISSUE TITLE
Enable folding in non editable buffers

### ISSUE THREAD

**Issue by tomekowal** [syl20bnr/spacemacs#13640]
Folding with `za` via origami is useful not only in editable buffers.

E.g. I'd like to use in my `*exunit-compilation*` buffer to inspect nested data structures when debugging tests. Folding makes it much easier.

Unfortunately, folding keybindings are defined in `spacemacs-editing` layer using `evil-normal-state-map`. Pressing `za` tells me, they are unbound. We could change it to `evil-motion-state-map` instead.

Would you find it a good idea to move folding to `evil-motion-state-map` and enable it globally even for non-editable buffers?

The change was small, so I've already made a PR. In case you don't like it - feel free to reject it :)

**Comment by smile13241324** [comment]
Merged your PR, please double check @tomekowal

**Comment by tomekowal** [comment]
Thank you, it works!
