### ISSUE TITLE
cannot insert 'T' character on html (web-mode) 

### ISSUE THREAD

**Issue by reed1** [syl20bnr/spacemacs#1364]
When I type T (uppercase) in insert mode on html, it's not inserted, instead emacs treat T and proceeding character as shortcut combination. I tried emacs with plain .spacemacs.template and add one "html" layer. 

thank you,
-reed1

**Comment by kendall** [comment]
I have this too but forgot to report it.

Cheers,
Kendall

**Comment by Ambrosia** [comment]
I think it's caused by this line https://github.com/syl20bnr/spacemacs/blob/develop/contrib/lang/html/packages.el#L132

**Comment by cpaulik** [comment]
Yes there is already a PR fixing the issue https://github.com/syl20bnr/spacemacs/pull/1264

**Comment by reed1** [comment]
Thxxx !!!!
