### ISSUE TITLE
Indentation of the yaml file changes when saving

### ISSUE THREAD

**Issue by maxiestudies** [syl20bnr/spacemacs#13655]
#### Description :octocat:
The indentation of the yaml files changes when I try to save the file using SPC f s

#### Reproduction guide :beetle:
- Start Emacs
- write an Ansible Playbook with one play and two tasks
- Try to save the file using either SPC f s or C-x C-s

*Observed behaviour:* :eyes: :broken_heart:
The indentation of the last task changes

*Expected behaviour:* :heart: :smile:
The indentation of the file should not change when saving

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible html yaml python helm auto-completion emacs-lisp git markdown
         (org :variables org-log-note-clock-out t)
         (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term)
         spell-checking syntax-checking version-control)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by cmatzenbach** [comment]
Might be worth switching to the `develop` branch to see if this is already fixed.  If it is, then maybe you can convince them to push the fix to `master`.  But I would definitely check `develop` first, and make sure you follow the instructions for refreshing your packages on `develop`: https://github.com/syl20bnr/spacemacs/#on-develop-branch

**Comment by smile13241324** [comment]
Jup, please try to reproduce on develop, also check the layer whether some implicit formatting is run after save.
