### ISSUE TITLE
Flawed commenting with <SPC-;> after update

### ISSUE THREAD

**Issue by CptnGreen** [syl20bnr/spacemacs#13650]
#### Description :octocat:
Commenting C code with `<SPC-;>` is unpredictable after recent update (update packages + `git pull --rebase` in `.emacs.d`)

#### Reproduction guide :beetle:
- Start Emacs
- Open some C code
- Navigate to necessary line
- Enter visual line mode with `<Shift-v>`
- Press `<SPC-;>` to comment line

*Observed behaviour:* :eyes: :broken_heart:
Something like this:
![image](https://user-images.githubusercontent.com/20269405/83950481-b879a600-a833-11ea-98e0-b3199549ac39.png)

instead of this: 
![image](https://user-images.githubusercontent.com/20269405/83950470-a8fa5d00-a833-11ea-9ff6-426d7da1b1d2.png)

*Expected behaviour:* :heart: :smile:
Line successfully commented like before update

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ecba7ad0d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-help-tooltip t)
 emacs-lisp git
 (org :variables org-projectile-file "TODOs.org")
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 ranger finance search-engine
 (wakatime :variables wakatime-python-bin "/usr/bin/python" wakatime-cli-path "/usr/bin/wakatime" wakatime-api-key "<some-key>")
 (lsp :variables lsp-ui-doc-enable nil lsp-enable-indentation nil lsp-enable-on-type-formatting nil)
 (c-c++ :variables c-c++-backend 'lsp-clangd)
 debug multiple-cursors
 (html :variables css-enable-lsp t html-enable-lsp t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by simonpintarelli** [comment]
I have the same problem after updating `spacemacs/comment-or-uncomment-lines` is broken.

**Comment by emacs18** [comment]
I cannot reproduce this problem on either emacs 26.3 or emacs 27 on ubuntu 20.04.
First `SPC ;` is bound to `evilnc-comment-operator` for me, and  `SPC c l` is bound to `spacemacs/comment-or-uncomment-lines`.  Both work as expected, i.e., after marking one line in a C file with `Shift v`, then hitting either `SPC ;` or `SPC c l` comments out that one line with `/* ... */`

**Comment by simonpintarelli** [comment]
After updating again (today) it works for me as expected.
@CptnGreen Could you please check and close the issue?

**Comment by CptnGreen** [comment]
Sorry for the long response. I've recently switched to Doom Emacs so I can't check this issue now but I believe it is already resolved so I'll indeed close this thread.
