### ISSUE TITLE
[FEATURE REQUEST] html-tidy included in the HTML layer

### ISSUE THREAD

**Issue by treymerkley** [syl20bnr/spacemacs#13659]
Flychecking for HTML would be great. Is there a way we can get Tidy added in, either as a default for HTML or as an option listed in the documentation?

**Comment by cmatzenbach** [comment]
The develop version already has a way to format HTML, check it out: https://develop.spacemacs.org/layers/+tools/web-beautify/README.html

You do have to install one third-part npm dependency, but that's it.  Refer to the link above for further docs.

**Comment by cmatzenbach** [comment]
@treymerkley Did this work for you?  Are there any major features `tidy` has for HTML that `web-beautify` doesn't?  If so, I think this can be closed @syl20bnr - `web-beautify` is simpler to setup, and you just hae to install one third-party global node dependency, vs having to install `tidy` via system package managers or building from source.

**Comment by treymerkley** [comment]
I haven't gotten a chance to test, but more than formatting, I'm really looking for error checking. Does `web-beautify` provide that?

**Comment by smile13241324** [comment]
@treymerkley your best bet for error checking would be LSP, the layer has proper support for html and css file lsps this will provide the default IDE content this is syntax checking, auto completion, formatting, refactoring....

Give it a try.

**Comment by treymerkley** [comment]
Yeah, that sounds plausible to me as a solution. Thank you! I'll close this and reopen if I have problems.
