### ISSUE TITLE
Discussion of layer AUCTeX vs LaTeX layer regarding #1160

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#1366]
I think it's time we set the naming and purpose of this layer, otherwise we will be adding new latex packages as layers and not in the LaTeX layer. 
packages like 
![file](https://i.imgur.com/p2V5L9e.png)

**Comment by syl20bnr** [comment]
You propose to rename it simply `LaTeX` and move it to `lang` category that's it ? :-)

**Comment by CestDiego** [comment]
Yep.. LaTeX ftw

**Comment by syl20bnr** [comment]
cc @trishume

**Comment by trishume** [comment]
Totally agreed. Other than the fact that I hate making breaking changes, but whatever. Also I think it should be `latex` rather than the proper `LaTeX` just to stick with all lower case layer names.

**Comment by CestDiego** [comment]
Yep, thinking about it, to avoid future headbangs we should stick consistent with other layer names.

**Comment by louy2** [comment]
:+1:
