### ISSUE TITLE
shifting window view upon jump to definition

### ISSUE THREAD

**Issue by jstaursky** [syl20bnr/spacemacs#13668]
#### Description :octocat:
when working in src code with two buffers open on the same file in different locations,
`spacemacs/jump-to-definition` shifts the buffer view (window) of the buffer not jumping to another file.

![simplescreenrecorder-2020-06-10_11 53 09](https://user-images.githubusercontent.com/25406664/84290181-5e1d6580-ab11-11ea-9099-b80a33ec938e.gif)

#### Reproduction guide :beetle:
- Start Emacs
- open a larger C++ project (something that has a file extending greator than 1 page view, and has a method definition in another file).
- open two buffer views on the same file.
- move point to a method whose def. is in another file.
- type `, g g` to jump 1 of the buffer views to the method def. in another file.

*Observed behaviour:* :eyes: :broken_heart:
typing `, g g` (spacemacs/jump-to-definition) shifts the page view of the buffer not performing the jump.

*Expected behaviour:* :heart: :smile:
jumping to a definition in 1 buffer view should not affect the buffer view in a separate window.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.60
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0d9cea8e2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby windows-scripts yaml clojure typescript html csv
      (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion t spell-checking-enable-auto-dictionary t)
      rust graphviz javascript
      (python :variables python-backend 'lsp python-lsp-server 'pyls)
      html
      (perl5 :packages
             (not company-plsense))
      latex helm
      (org :variables org-enable-sticky-header t)
      pdf git
      (version-control :variables version-control-diff-side 'left version-control-diff-tool 'diff-hl)
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete :disabled-for org spacemacs-org)
      emacs-lisp markdown multiple-cursors
      (shell :variables shell-default-term-shell "/usr/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
      syntax-checking treemacs
      (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-adopt-subprojects t)
      (lsp :variables lsp-ui-sideline-enable nil lsp-ui-doc-enable nil))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by emacs18** [comment]
I cannot reproduce this on emacs 27, latest deveop branch of spacemacs, all packages less than a week old.  I use ls-ccls backend as well, i.e., I see no change in the other buffer.

**Comment by jstaursky** [comment]
Ok I'll try and reproduce on a fresh install without my .init and provide an update to this issue soon.

**Comment by jstaursky** [comment]
Ok took me a while to get around to it but here is the proof,


![movie (1)](https://user-images.githubusercontent.com/25406664/86307988-1fe20600-bbe6-11ea-9be0-a2d3b4cc7af8.gif)

I know it goes kinda quick but i had to speed up,compress,etc. the video to meet github file size requirements. But this shows me cloning, creating a `compile_commands.json`, opening a fresh spacemacs install with only  
the following layers added 
```elisp
     (c-c++ :variables ; c++-enable-organize-includes-on-save t
            c-c++-backend 'lsp-ccls
            c-c++-adopt-subprojects t)

     (lsp :variables
          lsp-navigation 'simple
          lsp-ui-sideline-enable     nil
          lsp-ui-doc-enable          nil)
```
I then 
1. open the project containing the newly created `compile_commands.json`
2. split the filebuffer into two windows
3. move mid buffer in both windows
4. move point to around the middle of left window display
5. moving point over some method in the right window display
6. enter `, g g` (`jump-to-definition`) with the point over the method in step 5.
7. Observe the jump to the definition in the right window and a page shift occurring in left window.

**Comment by jstaursky** [comment]
The problem is in the function `spacemacs/jump-to-definition`, not in any of its jump handlers. I just entered `(advice-add  'spacemacs/jump-to-definition :override 'evil-goto-definition)` to replace it and it resolved the problem. Now my issue is that I can only call `evil-goto-definition` which may not always be the best function to call.
