### ISSUE TITLE
pytest execution fails

### ISSUE THREAD

**Issue by KorribanMaster** [syl20bnr/spacemacs#13686]
#### Description :octocat:
pytest run all fails with infinite recursion in pytest-find-test-runner-in-dir-named

#### Reproduction guide :beetle:
- Start Emacs
- Open Python test file
- `,ta` to run alle tests

*Observed behaviour:* :eyes: :broken_heart:
Execution of all tests fails with
Variable binding depth exceeds max-specpdl-size

Apparently a recursive function execution is done here:

```
(defun pytest-find-test-runner-in-dir-named (dn runner)
  (let ((fn (expand-file-name runner dn)))
    (cond ((file-regular-p fn) fn)
      ((equal dn "/") nil)
      (t (pytest-find-test-runner-in-dir-named
          (file-name-directory (directory-file-name dn))
          runner)))))
```

*Expected behaviour:* :heart: :smile:
Tests are executed

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 78b45b416)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv
 (python :variables python-backend 'lsp python-lsp-server 'pyls python-test-runner 'pytest python-lsp-git-root "~/python-language-server" python-sort-imports-on-save t python-save-before-test t python-formatter 'yapf)
 ipython-notebook major-modes javascript helm
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.2)
 better-defaults emacs-lisp
 (latex :variables latex-build-command "pdflatex")
 git version-control
 (lsp)
 (c-c++ :variables c-c++-backend 'lsp-clangd)
 markdown cmake themes-megapack org pdf
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control dap)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:
```

Debugger entered--Lisp error: (error "Variable binding depth exceeds max-specpdl-size")
  expand-file-name("runtests" "c:/")
  pytest-find-test-runner-in-dir-named("c:/" "runtests")
  pytest-find-test-runner-in-dir-named("c:/" "runtests")
  pytest-find-test-runner-in-dir-named("c:/" "runtests")
  pytest-find-test-runner-in-dir-named("c:/" "runtests")
....
* command-error-default-function((error "Variable binding depth exceeds max-specpdl-size") "" pytest-find-test-runner-in-dir-named)

```

**Comment by alexey0308** [comment]
It seem like an issue in stopping the search on Windows paths in pytest.el package.

Does adding 
```
   (with-eval-after-load "pytest"
     (add-to-list 'pytest-project-names "pytest"))
```
to `dotspacemacs/user-config ()` fixes the issue? 
(use another absolute path for the test-runner script instead of "pytest" in case pytest is not added to the PATH variable)

**Comment by alexey0308** [comment]
there is an upstream issue https://github.com/ionrock/pytest-el/issues/31
