### ISSUE TITLE
Tide server does not run - no auto-complete for .tsx files

### ISSUE THREAD

**Issue by benediktms** [syl20bnr/spacemacs#13692]
#### Description :octocat:
The Tide server does not start. Forcing the tide server to restart with `M-x tide-restart-server` will also fail. If the tide server is omitted in the Spacemacs configuration file, which should default to `lsp` the tide server is still called :( Syntax highlighting works but there is no auto-completion. TSX files seem to start in `html` major mode but without any TS packages which according to Issue #7344 seems to be the expected behaviour. This is the error I get:

`Error running timer 'tide--hl-identifiers-function': (error "Server does not exist. Run M-x tide-restart-server to start it again")`

Background info: Tide and TS are installed globally. This is a fresh install of Spacemacs. I've set up the `typescript layer`  according to the docs.

#### Reproduction guide :beetle:
- Start Emacs
- ensure `typescript` and `react` layers are installed.
- open a fiel with the .tsx extension
- use either the jsts or ts option Spacemacs will give you

*Observed behaviour:* :eyes: :broken_heart:
File is opened and syntax highlighting works more ore less (not sure what TSX elements are supposed to look like but basic TS syntax is recognised). The above error will display.

*Expected behaviour:* :heart: :smile:
The file to either open in typescript-mode or support for TS/TSX auto complete to be present in web mode (again referencing issue #7344)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 78b45b416)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git helm lsp markdown multiple-cursors org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control treemacs javascript html react
                 (typescript :variables typescript-backend 'tide tide-tsserver-executable "usr/local/bin/tsserver")
                 web-beautify prettier)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by thanhvg** [comment]
Enable `tide` layer and try again.

**Comment by benediktms** [comment]
> Enable `tide` layer and try again.

I have enabled the tide layer to no avail :( pardon my ignorance but is it possible to tell spacemacs to use the tsserver file in the project root directory rather than the global directory?

**Comment by thanhvg** [comment]
> I have enabled the tide layer to no avail :( pardon my ignorance but is it possible to tell spacemacs to use the tsserver file in the project root directory rather than the global directory?

You can enable `node` layer so `tssserver` in project root will be picked up first. If you choose to do so you need to remove your `tide-tsserver-executable` setting.

**Comment by benediktms** [comment]
I did a clean reinstall of emacs + spacemacs. And added the above layers as well as the node layer and omitted the tsserver file path but that also does not fix the issue. I think the issue is that the tsserver file form the global install is not actually the correct file (opening it in an editor shows it only has two lines of code) so I'm going to clone the Typescript repo and then try to point spacemacs to the tsserver folder to see if that helps.

**Comment by benediktms** [comment]
Reporting back, that method didn't help either (probably to be expected).

**Comment by A0A** [comment]
I'm having the exact same issue, but with .ts files (I don't have any .tsx to confirm whether or not it works there).

**Comment by thanhvg** [comment]
This is my layer config for js: 
``` elisp 
     (html :variables html-enable-lsp nil)
     tide
     (node :variables node-add-modules-path t)
     (javascript :variables
                 javascript-backend 'tide
                 javascript-lsp-linter nil
                 javascript-fmt-tool 'prettier
                 javascript-repl 'nodejs)
     react
     (typescript :variables
                 typescript-backend 'tide
                 typescript-linter 'eslint
                 typescript-fmt-tool 'prettier
                 typescript-lsp-linter nil)
     vue

**Comment by benediktms** [comment]
> This is my layer config for js:
> 
> ```emacs-lisp
>      (html :variables html-enable-lsp nil)
>      tide
>      (node :variables node-add-modules-path t)
>      (javascript :variables
>                  javascript-backend 'tide
>                  javascript-lsp-linter nil
>                  javascript-fmt-tool 'prettier
>                  javascript-repl 'nodejs)
>      react
>      (typescript :variables
>                  typescript-backend 'tide
>                  typescript-linter 'eslint
>                  typescript-fmt-tool 'prettier
>                  typescript-lsp-linter nil)
>      vue
> ```

Ahh I didn't have `node-add-modules-path t` added to my node layer variables. This fixed the issue for me! Thanks!

**Comment by A0A** [comment]
Thanks! Unfortunately I'm running into the same problem even after copying that config.

**Comment by benediktms** [comment]
Those configs also did not work for me. The tide server doesn't run on `.js`, `.jsx`, `.ts`, `.tsx` files for me so it's not specific to the file type.

**Comment by Lyonsclay** [comment]
@benediktms I had a similar issue, I can't remember the specifics. I used `SPC e v` to show the flycheck checkers. It should give the status of any given checker in the pipeline and then you can enable disabled checkers "Flycheck Mode is enabled. Use `SPC u C-c ! x` to enable disabled checkers." or set the correct executable `SPC e S` `flycheck-set-checker-executable`.

**Comment by stormwatch** [comment]
I could start `tsserver` after updating my `.spacemacs.env` to a current nvm binary directory.

**Comment by hequ** [comment]
I'm running Mac OS (Big Sur) and using nvm ton manage node environments and had this same issue where tide was complaining

```
Error running timer 'tide--hl-identifiers-function': (error "Server does not exist. Run M-x tide-restart-server to start it again")
```

I managed to resolve this on my case by looking up where my `tsserver` is installed by running:

```
$ which tsserver
/Users/me/.local/share/nvm/v12.20.0/bin/tsserver
```

and then setting that to `.spacemacs.env` file:

```
PATH={whatever-there-is-in-your-path-now}:/Users/me/.local/share/nvm/v12.20.0/bin
```
.

My dotspacemacs file `spacemacs-configuration-layers` contains the following layers for configuring tide:

```
node
(tide :variables tide-tsserver-executable nil)
(typescript :variables typescript-backend 'tide)
(javascript :variables javascript-backend 'tide)
```

I'm a complete newbie what comes to emacs, but this seems to work. :)

**Comment by lebensterben** [comment]
>I'm running Mac OS (Big Sur) and using nvm ton manage node environments and had this same issue where tide was complaining ...

@hequ
It should be fine once the server is in your PATH. You don't need to set other variables in dotspacemacs

**Comment by jishankai** [comment]
I fixed this by upgrading typescript.

```
# MacOS
brew upgrade typescript
```

**Comment by Choongkyu** [comment]
I'm having a similar issue and was wondering if there is a way to get this working without having to install tsserver globally, since I've gotten used to installing typescript on a project by project basis.

**Comment by lebensterben** [comment]
I'm going to close this unless someone pointed out why this is a bug.
