### ISSUE TITLE
Spacemacs gets stuck for a few seconds and hogs CPU(100% usage) from time to time

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#1369]
~~Now https://github.com/syl20bnr/spacemacs/issues/1300 is solved, Emacs no longer eats up memory and totally freezes.~~ (Update: https://github.com/syl20bnr/spacemacs/issues/1300 now happened again as well...) However, I still encounter random situations where Emacs just ramps up its CPU usage all the way to 100% from time to time, and gets stuck for at least 5 seconds. It happens almost every 30 seconds now. 

The first screenshot is when CPU usage peaks. Subsequently it drops rapidly to only about 1% and Emacs responds normally again.

![screenshot 2015-04-25 17 11 58](https://cloud.githubusercontent.com/assets/2999209/7332543/6dea4a1a-eb76-11e4-9900-5c8d12a04b8d.png)
![screenshot 2015-04-25 17 12 04](https://cloud.githubusercontent.com/assets/2999209/7332544/72b90914-eb76-11e4-9d63-8fcd4430631e.png)
![screenshot 2015-04-25 17 12 09](https://cloud.githubusercontent.com/assets/2999209/7332545/74cea006-eb76-11e4-971e-d9f0940e540b.png)

When this happens I'm not doing anything except for navigating a file using Vim bindings. It's weird because I've erased all the variables set via `Custom` but it doesn't help.

Also, pressing `SPC` and mouse-clicking on Emacs could both also induce the issue.

I think other users mentioned similar situations in both https://github.com/syl20bnr/spacemacs/issues/1300#issuecomment-95020725 and https://github.com/syl20bnr/spacemacs/issues/868#issuecomment-83773149

**Comment by x-ji** [comment]
Deleted both `.emacs.d` and `.spacemacs` and did a fresh reinstall again... This time didn't add any private layer and things seem to be working. Let me just suppose for now it's induced by some package not playing well with Spacemacs.

**Comment by danielwuz** [comment]
FYI, I recently ran into an issue of noticeable stuck when doing copy and paste. I eventually was able to find out it's related to `pbcopy` in `osx` layer, not sure why that happened, still need to look further into this problem.

**Comment by x-ji** [comment]
Now it happened again... I now suppose it's an issue of `semanticdb`, because it only occurred after Spacemacs asked me to create `semanticdb` folder and I clicked yes.

**Comment by tuhdo** [comment]
If no layer is included, probably it's the problem of your Emacs build. Maybe instead of emacs-mac-port, you should give Emacs for Mac OS X latest build (24.5) a try, since the new version fixed crashing bug in 24.4. If that doesn't work and you still have patient, probably try the development version Emacs 25.

**Comment by x-ji** [comment]
@tuhdo Will give it a try. The only issue with Emacs for Mac OS X compared with emacs-mac-port is the powerline color issue, right?

**Comment by balajisivaraman** [comment]
I'm having this problem as well, on OSX 10.9.5. I've tried with [Emacs 24.5.1 Universal](http://emacsformacosx.com/emacs-builds/Emacs-24.5-1-universal.dmg), the [26th April](http://emacsformacosx.com/emacs-builds/Emacs-2015-04-26_01-41-10-fddff05-universal.dmg) and the [20th April](http://emacsformacosx.com/emacs-builds/Emacs-2015-04-20_01-40-56-8f1eda7-universal.dmg) nightlies from EmacsForOSX.

In the case of the Nightlies, Emacs doesn't open itself. In the case of 24.5.1, Emacs opens, but when I try to do C-x C-f, it hangs and hogs the CPU at 99-100%. :-(

**Comment by x-ji** [comment]
Yeah, Emacs for OSX has the same problem too... And sometimes just as described in https://github.com/syl20bnr/spacemacs/issues/1300, it not only hogs CPU, but seems to increasingly require more and more memory until it has eaten up all disk space(presumably making virtual memory?) as well. That's quite monstrous.

**Comment by tuhdo** [comment]
Since you are using old OSX 10.9.5, consider upgrading to latest OS X Yosemite or downgrade Emacs to emacs-mac-port 24.4 or even 24.3. I don't think it has any problem with latest OS X since many people are using Emacs 24.5 on it.

**Comment by x-ji** [comment]
Unfortunately for me I'm using the newest version of Yosemite... :(

**Comment by tuhdo** [comment]
So, try reproducing it with just stock Emacs: `emacs -q` and run something if something strange happens. If so, probably it's an Emacs bug. However, I think many OS X users have their Emacs working fine so I'm not sure it's an Emacs problem. Not sure if you install some external apps that conflict with Emacs?

**Comment by x-ji** [comment]
Now I'm trying the Emacs build directly from `homebrew` instead of `emacs-mac-port` or Emacs for OS X, and so far so good. @balajisivaraman probably you can also try this build of Emacs?

Installation command: `brew install emacs --HEAD --use-git-head --with-cocoa --srgb`

**Comment by x-ji** [comment]
Ah no. The problem resurfaced. But it's actually killable via `C-g`, so I suppose it's an infinite loop issue.

**Comment by x-ji** [comment]
I got stuck again today on Emacs startup process as it started to infinitely hog CPU and memory again. I inspected my `.emacs.d` folder and found `savehist` file is 1.16 GB under `.cache`. Is that normal? After removing that file Emacs could be started normally.

**Comment by tuhdo** [comment]
That's not normal at all. Probably you should temporary disable `savehist-mode` for now. If you disable it, Emacs won't be able to jump to previous location in a visited file.

**Comment by x-ji** [comment]
Umm... Are `C-o` and `C-i` independent of `savehist-mode`? It seems that they're still working after I set `savehist-mode` to `nil`. They should suffice?

**Comment by x-ji** [comment]
Running `grep -E -b -o '^\(setq [^ ]+' ~/.emacs.d/.cache/savehist` following the advice from http://emacs.stackexchange.com/questions/12086/abnormally-large-savehist-file/12116 reveals the following:

```
116:(setq savehist-minibuffer-history-variables
350:(setq regexp-search-ring
566:(setq magit-read-rev-history
637:(setq read-expression-history
694:(setq command-history
19045:(setq helm-grep-history
20687:(setq minibuffer-history
75425:(setq file-name-history
83278:(setq ido-file-history
83377:(setq evil-ex-history
111288:(setq kill-ring
1162765006:(setq mark-ring
1162765028:(setq search-ring
1162765052:(setq regexp-search-ring
1162765268:(setq extended-command-history
```

Could it be anything to do with `evil`?

**Comment by tuhdo** [comment]
You `kill-ring` is really large. Probably you copy/paste very large amount of text? We should limit the `kill-ring` content stored in the file though.

**Comment by mattly** [comment]
I ran into a similar problem last night, which persisted across resetting my `.spacemacs` file to default and nuking my elpa directory. It only went away after clearing my `~/.emacs.d/.cache` directory.

**Comment by x-ji** [comment]
In my case I can currently confirm that an abnormally large `savehist` file caused the issue each time and disabling `savehist-mode` solved it. Though I currently have no idea as to why this happened...

**Comment by syl20bnr** [comment]
The `savehist` configuration added by spacemacs is here:
https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/config.el#L236-L244

We can see that the problematic variables @x-ji encountered are added explicitly by spacemacs.
I'm OK to remove them from spacemacs default.

**Comment by tuhdo** [comment]
We should only disable saving those variables (or just `kill-ring`) for OS X, not other OSes.

**Comment by syl20bnr** [comment]
The issue with these variables are only on OS X ? `emacs-mac` formulae only ?

**Comment by tuhdo** [comment]
I have no such abnormal large savehist in both my Linux and Windows machine. Not sure about which version of Emacs in OS X.

**Comment by x-ji** [comment]
Well for me it happened in all kinds of emacs builds, including emacs-mac,
emacs, and the binary file from emacsformacosx.com . In this case version
doesn't seem to be related.

Not sure I'm copying anything abnormal, especially considering it happens
every time I clear the file, not just once or twice. Even if there's a
large amount of content accumulated we should be able to limit the size in
some way? Or probably just exclude kill-ring.

**Comment by sbenhaim** [comment]
My guess is images/documents in clipboard interacting with `save-interprogram-paste-before-kill` means large bits of binary data in the kill-ring.

**Comment by syl20bnr** [comment]
@tuhdo removed the kill-ring from savehist which should fix the issue.

**Comment by azer** [comment]
This happens to me when I'm undoing.
