### ISSUE TITLE
don't know how to configure my own c++ header folder path 

### ISSUE THREAD

**Issue by csfreebird** [syl20bnr/spacemacs#13706]
I am using c-c++ layer, clangd is backend, the file under /usr/include folder can be found, I can jump into one file e.g. /usr/include/c++/9/iostream
using M-m m g g.

But my own c++ header folder in project cannot be found, I tried a few ways but failed.

How to make it? Need a help. Also suggest adding a chapter into the doc for newbie.

**Comment by alexey0308** [comment]
It could help, if there is more information on the issue: is cmake used to build the project?
clangd requires a special file compile_commands.json, which can be generated by cmake, e.g. [see here](https://clangd.llvm.org/installation.html).

For example,
if the source files in `src` and headers are in `include` dirs, having CMakeLists.txt  file in the root project directory with such content 
```
cmake_minimum_required(VERSION 3.10)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

add_executable(app src/main.cpp)
target_include_directories(app PUBLIC
                          "${PROJECT_SOURCE_DIR}/include")
```

and then running 

```
cmake .
```

works for me.

**Comment by csfreebird** [comment]
thank you, it works, I took several hours on this. you saved me.
ha ha

**Comment by bojohnson5** [comment]
> clangd requires a special file compile_commands.json

@alexey0308 If I could follow up on this issue here, I'm trying to link some external external libraries to a project and want autocomplete features using lsp. I manage to only get the Boost libraries working for this, but can't seem to find the right lines to include in my CMakeLists.txt file to get libraries like Eigen3 or ROOT to have compile_commands.json working properly with lsp. In an test project with Boost the CMakeLists.txt looks like
```
cmake_minimum_required(VERSION 3.10)
SET(CMAKE_CXX_STANDARD 14)
FIND_PACKAGE( Boost COMPONENTS program_options REQUIRED )
INCLUDE_DIRECTORIES( ${Boost_INCLUDE_DIR} )
SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)

ADD_EXECUTABLE( harmonic harmonic_oscillator.cpp )

TARGET_LINK_LIBRARIES( harmonic LINK_PUBLIC ${Boost_LIBRARIES} )
```
and everything works great! But when I have a test project for Eigen3 the CMakeLists.txt looks like
```
cmake_minimum_required(VERSION 3.10)
project(EigenTest)
set(CMAKE_CXX_STANDARD 14)
find_package(Eigen3)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

add_executable(eigentest main.cpp)

target_link_libraries(eigentest Eigen3::Eigen)
```
taken from their [website](https://eigen.tuxfamily.org/dox/TopicCMakeGuide.html) but it doesn't seem to have the right things exported to the json file for autocomplete with lsp. Could you point me in the right direction to finding how to fix this issue?

**Comment by alexey0308** [comment]
Hello @bojohnson5 ,
have you actually installed Eigen? Can the project be successfully compiled?

> but it doesn't seem to have the right things exported to the json file 

If there is more information on how you know, that something is not right, people could help you with higher probability.

**Comment by bojohnson5** [comment]
Thanks @alexey0308 for the response and sorry for not including more information. Yes Eigen is installed and the project compiles successfully. The output for the json file of the Eigen example is
```
[
{
  "directory": "/Users/bojohnson/Documents/Misc/DUNE",
  "command": "/Library/Developer/CommandLineTools/usr/bin/c++  -I/usr/local/include -isystem /usr/local/include/eigen3  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk -std=gnu++14 -o CMakeFiles/eigentest.dir/main.cpp.o -c /Users/bojohnson/Documents/Misc/DUNE/main.cpp",
  "file": "/Users/bojohnson/Documents/Misc/DUNE/main.cpp"
}
]
```
while the output for the Boost example is
```
[
{
  "directory": "/Users/bojohnson/Documents/Misc/Code/Projectt",
  "command": "/Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_PROGRAM_OPTIONS_DYN_LINK -isystem /usr/local/include  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk -std=gnu++14 -o CMakeFiles/harmonic.dir/harmonic_oscillator.cpp.o -c /Users/bojohnson/Documents/Misc/Code/Projectt/harmonic_oscillator.cpp",
  "file": "/Users/bojohnson/Documents/Misc/Code/Projectt/harmonic_oscillator.cpp"
}
]
```
I'm wondering if the extra flags passed to the Boost example is what make lsp able to find the Boost header files and functions when I work in source files as opposed to the Eigen example where I get errors that look like
<img width="581" alt="Screen Shot 2021-07-17 at 10 08 36 AM" src="https://user-images.githubusercontent.com/20647190/126039620-1b5ff8e9-5d69-43e9-aeb3-9a3d995bd941.png">
Cheers!

**Comment by alexey0308** [comment]
Have you tried?
```
#include <eigen3/Eigen/Dense>
```

**Comment by bojohnson5** [comment]
You're a beautiful human! Thanks, that did the trick!

**Comment by alexey0308** [comment]
thank you for your nice way of discussing issues, haha

If you do lsp-workspace-restart, does it also fixes it and you can switch back without problems to
```
#include <Eigen/Dense>
```
?

**Comment by bojohnson5** [comment]
It most certainly does haha! I guess the biggest thing is to restart the language server after creating the compile_commands.json file.
