### ISSUE TITLE
Shorten org file names when displaying org agenda on splash screen

### ISSUE THREAD

**Issue by greole** [syl20bnr/spacemacs#13702]
When displaying the org todo and agenda list on the splash screen long file names tend to clutter the splash screen, especially if the org files are store in a folder like `~/Dropbox/gtd/project1/foo.org` etc. Hence it would be great to have an option to shorten the file names to `foo.org`. Ideally an option to keep long filenames could be implemented to distinguish  `~/Dropbox/gtd/project1/inbox.org` and   `~/Dropbox/gtd/project2/inbox.org` if needed.

**Comment by smile13241324** [comment]
Merged your code and revised it a bit, please close this issue if it is ok @greole

**Comment by greole** [comment]
Thank you for merging!
