### ISSUE TITLE
Custom Spacemacs Build

### ISSUE THREAD

**Issue by Immortalin** [syl20bnr/spacemacs#1371]
Hi, how about a custom Spacemacs Build via a CI system such as Travis CI etc.? This way installation would be simpler and new users would have a easier time setting things up without having to download several bits and pieces. The GNU emacs download page is not particularly user friendly and this may turn off many potential new Spacemacs users.

**Comment by syl20bnr** [comment]
This is a good proposition but this is not spacemacs concern to maintain an emacs build distribution. We would have to maintain a lot of platforms and I don't know if there is any windows worker available with Travis.
If you were thinking about just packaging already built binaries along with spacemacs then I see little value to do so.

**Comment by Immortalin** [comment]
My point is that we should improve the UX as a lot of new users tend to be turned off by Emacs and GNU websites archaic UI and choose something that is perceived as more modern, e.g. sublime text. This, combined with the steep learning curve, creates a negative impression of Emacs in general. Since Spacemacs advertises itself as neither Emacs nor Vim, won't it be better to have better support and proper installers for Windows so new users won't have to jump through so many hoops to get started? Just my 2¢.

<div>-------- Original message --------</div><div>From: Sylvain Benner <notifications@github.com> </div><div>Date:27/04/2015  09:54  (GMT+08:00) </div><div>To: syl20bnr/spacemacs <spacemacs@noreply.github.com> </div><div>Cc: Immortalin <immortalin@icloud.com> </div><div>Subject: Re: [spacemacs] Custom Spacemacs Build (#1371) </div><div>
</div>This is a good proposition but this is not spacemacs concern to maintain an emacs build distribution. We would have to maintain a lot of platforms and I don't know if there is any windows worker available with Travis.
If you were thinking about just packaging already built binaries along with spacemacs then I see little value to do so.

**Comment by syl20bnr** [comment]
This is a valid proposal but it should be a separate project.
