### ISSUE TITLE
Shebang in a .ts file prevents major TS mode load

### ISSUE THREAD

**Issue by Invertisment** [syl20bnr/spacemacs#13715]
#### Description :octocat:
Including a GNU/Linux shebang as a Typescript file header results in major TS mode not being loaded.

#### Reproduction guide :beetle:
- Create a .ts file with a header: `#!/usr/bin/env node`
- Start Emacs
- Load already created .ts file with shebang:

```
#!/usr/bin/env node
export default hi = "hi"
```

- There is no Major mode (`<SPC-m>` doesn't exist).

*Observed behaviour:* :eyes: :broken_heart:
Typescript mode is not enabled for this file.
Instead it's set to JavaScript and there is completely no major mode.

*Expected behaviour:* :heart: :smile:
Typescript mode should be the main editing mode.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d4634b571)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql python ruby
     (typescript :variables typescript-fmt-on-save t)
     html csv yaml markdown
     (go :variables go-use-golangci-lint t go-format-before-save t gofmt-command "goimports" go-tab-width 2)
     (lsp :variables lsp-ui-doc-enable nil)
     (clojure :variables clojure-enable-clj-refactor t)
     react c-c++ rust java
     (scala :variables scala-backend 'scala-metals)
     (auto-completion :variables auto-completion-enable-help-tooltip nil)
     emacs-lisp helm spell-checking syntax-checking treemacs solidity)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by alexey0308** [comment]
Shebang takes precedence over file extension while opening a file in emacs.
Does it solve an issue, if one adds to the user-config in .spacemacs
```
(setq interpreter-mode-alist (assoc-delete-all "node" interpreter-mode-alist))
(add-to-list 'magic-mode-alist
              '((lambda ()
                  (string-match "\\.ts$" (buffer-file-name))) . typescript-mode))

```
?
Or using 
```
// -*- mode: typescript -*-
```
right after the shebang?

**Comment by Invertisment** [comment]
Thanks.
