### ISSUE TITLE
add line numbers to error messages from dotspacemacs

### ISSUE THREAD

**Issue by JonatanSahar** [syl20bnr/spacemacs#13713]
when I mess something up in my config it takes ages sometimes to find where the problem is, since there are no line numbers reported with the error. e.g. I now have:

`(Spacemacs) Error in dotspacemacs/user-config: Wrong number of arguments: define-key, 4`

But not much of a way to know where the problem is (yes, I've commented out all of my recent changes, I suppose it's some pasting error...)

**Comment by smile13241324** [comment]
Not a bad idea, not sure if its possible though, I am not sure that we have the information where emacs is when an exception is thrown during evaluation.

**Comment by lebensterben** [comment]
nice idea but it's out of scope of Spacemacs.
