### ISSUE TITLE
improve js-doc-insert-function-doc-snippet

### ISSUE THREAD

**Issue by WingDust** [syl20bnr/spacemacs#13712]
I very like like this style comment . its stick out a mile make me focus on this comment
```
  /**
   * [foo description]
   * @param  {[type]} x [description]
   * @return {[type]}
   */
  function foo (x) {}
```
not like in use function`js-doc-insert-function-doc-snippet`
```
/**
 * Function description.
 */
function Stack(){}
```
Can do that ?

**Comment by smile13241324** [comment]
So I did a quick lookup of that function `js-doc-insert-function-doc-snippet`. It is defined in the emacs package `js-doc`. If you would like to change the function impl, to have a different outcome you should open a ticket [here](https://github.com/mooz/js-doc).

Nevertheless checking the config vars that package exposes shows that you can also configure the format of your parameter and return lines to fit your needs. So maybe no code change is necessary to achieve what you want.

**Comment by WingDust** [comment]
@smile13241324  can help me how to config vars , I not good at elisp

**Comment by smile13241324** [comment]
Hmmm looks like I was wrong, you can change the appearance for the generated code for `js-doc-insert-function-doc-snippet` however this only generates a very simple version not looking like what you describe above.

The actual function bound by spacemacs to `,rdf` is called `js-doc-insert-function-doc-snippet` which generates the documentation as you describe above, with the exception of the `[]`. However this function does not allow to customise the generated text. 

So your best bet would be to overwrite that function in your dotfile or create a ticket for `js-doc` to get the wished `[]` in your generated comments.
