### ISSUE TITLE
The python interpreter not showing numbers as before.

### ISSUE THREAD

**Issue by Incantatoric** [syl20bnr/spacemacs#13710]
(C-c C-c didn't work for me in M-m h I, so I just copy-pasted the contents).

#### Description :octocat:
The python interpreter does not show the line numbers in Linux.

#### Reproduction guide :beetle:
- Start Emacs
- Open a .py file.
- C-c C-p to open a Python interpreter (python-shell-interpreter linked to an Anaconda one).
- C-c C-r to import packages.

*Observed behaviour:* :eyes: :broken_heart:
- The packages are successfully imported, but nothing changes in the interpreter screen (I can only see >>).
https://imgur.com/a/mupDHOY

*Expected behaviour:* :heart: :smile:
- Number should be changed to [2] in the interpreter screen after the packages are imported.
- In Windows, this is the behaviour, and in Linux, this had been the behavior.
- Today, I realized that spacemacs was reading the system python interpreter, so I changed it to the Anaconda one, but the problem persists.
I think this is a small problem but I could not figure out what was causing this. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(sql sql html python latex pdf-tools helm auto-completion emacs-lisp git)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by Incantatoric** [comment]
I have solved the issue by editing and adding the following lines to the dot file:

```
(setq python-shell-interpreter "/home/incantator/anaconda3/bin/ipython3")
(setq python-shell-interpreter-args "--simple-prompt -i")
```

I am not sure why it had worked fine without adding these lines before; maybe it has something to do with Arch Linux update. After pinpointing "ipython" instead of "python", I had the error message "your terminal doesn't support cursor position requests (CPR)", which was fixed after adding the second line. I wish my solution was correct and not a cover-up of some bad problems underneath it.

**Comment by alexey0308** [comment]
There is a layer for managing conda environment on the [development branch](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/conda).

Alternatively, there is another solution posted at [stackexchange](https://emacs.stackexchange.com/a/32206)

**Comment by Incantatoric** [comment]
@alexey0308 Thank you for your help. I was able to move to the development branch, but the conda layer is still not working. I changed `(conda :variables conda-anaconda-home "/home/name/anaconda3/")` removing the dot in front of "anaconda3" according to my installation location, but it still used the native python rather than the Anaconda one. I even confirmed the change by `C-h v conda-anaconda-home`. I had to revert back to my original solution for now. Also, the alternative solution is what I have used before, and it seems like it is not working now.

I will provide any details that are needed.

**Comment by alexey0308** [comment]
Unfortunately, I do not know much about conda.
Did you actually activated the environment? i.e. [SPC m n a].
Also, you might need to remove your customization in the dot file while trying it, i.e.  (setq python-shell-interpreter...)
and check if it successfully assigns the path of `python-shell-virtualenv-path`, see
[here](https://github.com/necaris/conda.el#what-do-activating-and-deactivating-actually-do) after it is activated.

**Comment by Incantatoric** [comment]
I have checked `M-x m n a`, and I think conda layer is working correctly. I just do not have any other environments than the default "base" at the moment, and it seems like I cannot just choose it by "conda activate" within spacemacs. I just added "conda activate base" in my .bashrc but `C-c C-p` still chooses the native Python. Sorry for my incompetence; I would still be happy if I can choose the base environment without setting python-shell-interpreter to the ipython.

**Comment by alexey0308** [comment]
I also have little understanding, how it works and try just to learn here.
What is an output of the command (entered with M-: )
`(python-shell-calculate-exec-path)`
before and after activating the base environment? It should change to the correct conda path, i.e. it should have 
`"/home/user/.anaconda3/envs/base/bin"` in the beginning, or something like this, if it is successful.
What is the output of  `(python-shell-calculate-command)` after activating conda base?

**Comment by Incantatoric** [comment]
@alexey0308 Thank you for keep following with me. I had thought that the layer is just not detecting the base environment, but even after I have created a new conda environment it is not picking it up. It is so weird because both my `conda-anaconda-home` and `conda-env-home-directory` are set correctly to "~/anaconda3" which I have checked within spacemacs by `C-h v`. In the shell, `conda env list` lists correctly all the environment I have.

Currently, M-: python-shell-calculate-exec-path gives me this:

Debugger entered--Lisp error: (void-variable python-shell-calculate-exec-path)
  eval(python-shell-calculate-exec-path nil)
  eval-expression(python-shell-calculate-exec-path nil nil 127)
  funcall-interactively(eval-expression python-shell-calculate-exec-path nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)

**Comment by alexey0308** [comment]
These are the function names, which I provided, please wrap it in parenthesis when evaluating.
i.e. enter literally this: (python-shell-calculate-exec-path) and this (python-shell-calculate-command). They should return you the all the paths and the command emacs uses to run the interpreter.

**Comment by Incantatoric** [comment]
@alexey0308 I am sorry for my mistakes. Unfortunately, I was not able to find how to activate conda within spacemacs with python mode. Instead, I just opened a shell, `conda activate`, and then called emacs so that it would recognize the conda environment correctly.

### [Without conda activate]
`(python-shell-calculate-exec-path)`
("/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu" "/home/name/anaconda3/condabin")
`(python-shell-calculate-command)`
"python -i"

### [In the shell, conda activate -> emacs]
`(python-shell-calculate-exec-path)`
("**/home/name/anaconda3/bin**" "/home/name/anaconda3/condabin" "/usr/local/sbin" "/usr/local/bin" "/usr/bin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/usr/lib/emacs/26.3/x86_64-pc-linux-gnu")
`(python-shell-calculate-command)`
"ipython --simple-prompt -i"

By the way, conda is not activated automatically in my case. Maybe should I add `conda activate` to my .bash_profile in order to use conda layer correctly?

**Comment by Incantatoric** [comment]
@alexey0308 Yes, it works without a problem.

**Comment by alexey0308** [comment]
Oh, the original problem was that you can not do it without conda. After installation of Linux you need to install ipython as well: without conda emacs finds only basic interpreter, i.e. python, not ipython.
```
python3 -m pip install ipython
```
should allow you to use ipython even _without_ conda activated.
Is it what you would like to have, right?

**Comment by Incantatoric** [comment]
Originally I did not want to touch the system python, so I installed Anaconda and let emacs use it instead. So my current objective is to **let my emacs use the Anaconda python** again, and a side mission is to **let conda layer recognize the conda environment**. The current problem is that conda-env-list shows nothing even when conda is activated through shell. Most of the solutions I have found was to set other variables such as conda-anaconda-home, but the problem persists even after I have set the variables correctly.

**Comment by alexey0308** [comment]
OK, the last thing I would check is that there exists "ipython" in any of the provided paths, i.e.
ls in those: "/home/name/anaconda3/bin" "/home/name/anaconda3/condabin".
I can be the case, that emacs looks for ipython, but there exists only ipython3 in these folders.
You may create a symbolic link named ipython pointing to ipython3 under the anaconda3/bin folder or
rename the interpreter name in emacs from ipython to ipython3.

P.S. You can always provide a custom interpreter command using SPC-u C-c C-p.

Besides this, I am not sure I have more to suggest...

**Comment by Incantatoric** [comment]
There is indeed "ipython" in "/home/name/anaconda3/bin".

Thank you for your help so far; I learned so much while searching for the relevant information. I think it might a path related problem (still not sure since conda-anaconda-home is set correctly to ~/anaconda3"), so I will try looking into that. For now, I think I should become more comfortable with spacemacs.
