### ISSUE TITLE
Package company-tern is unavailable in develop branch

### ISSUE THREAD

**Issue by umutozdemir97** [syl20bnr/spacemacs#13725]
#### Description :octocat:

I see this message everytime I open spacemacs. I'm on develop branch.
javascript, autocompletion and tern layers are enabled in dotfile.

Message:

--> refreshing package archive: gnu... [3/3]
--> installing package: company-tern@tern... [1/1]
Package company-tern is unavailable. Is the package name misspelled?

#### Reproduction guide :beetle:
- Start Emacs
- Wait and see the error message

*Observed behaviour:* :eyes: :broken_heart:
Javascript auto completion feature is not enabled. Nothing appears as I write.
Also, error message appers.

*Expected behaviour:* :heart: :smile:
Javascript autocompletion should work and error message shouldn't appear.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6452e8121)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript typescript python rust helm auto-completion emacs-lisp git tern markdown
            (osx :variables osx-option-as 'none osx-right-option-as 'none osx-command-as 'meta osx-control-as 'control)
            syntax-checking version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by emacs18** [comment]
`company-tern` is mentioned in `tern` layer of spacemacs.  However this package was removed about two months ago from `melpa` via <https://github.com/melpa/melpa/commit/8b967b02a5ba544b543a63edebb479cb2fe22c9b>

So we need adjust spacemacs to deal with this removal.

**Comment by smile13241324** [comment]
I have removed the package from tern layer, not sure if this layer still makes much sense without it though.
