### ISSUE TITLE
Running current Go test function fails when point is on the first line

### ISSUE THREAD

**Issue by joelpet** [syl20bnr/spacemacs#13722]
#### Description :octocat:
`spacemacs/go-run-test-current-function()` fails when point is anywhere but at the end of the line on the first line of the function.

#### Reproduction guide :beetle:
- Start Emacs
- Open an existing Go test file (name matches `*_test.go`)
- Move point to a location of the first line of a test function except to EOL, e.g. `func TestX(t *test[i]ng.T) {`
- Call `spacemacs/go-run-test-current-function()` 

*Observed behaviour:* :eyes: :broken_heart:
`*Messages*`: `Search failed: "^func[ ]+\\(([[:alnum:]]*?[ ]?[*]?\\([[:alnum:]]+\\))[ ]+\\)?\\(Test[[:alnum:]_]+\\)(.*)"`

*Expected behaviour:* :heart: :smile:
The `TestX` function is run and the results displayed in a popup.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6452e8121)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible auto-completion csharp csv django emacs-lisp git go helm html javascript lsp markdown mu4e nginx
         (org :variables org-enable-bootstrap-support nil org-enable-github-support t org-enable-reveal-js-support t)
         perl5 php python react restclient ruby rust scala shell-scripts spell-checking sql
         (syntax-checking :variables syntax-checking-enable-tooltips nil)
         systemd treemacs version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (search-failed "^func[ ]+\\(([[:alnum:]]*?[ ]?[*]?\\([[:alnum:]]+\\))[ ]+\\)?\\(Test[[:alnum:]_]+\\)(.*)")
  re-search-backward("^func[ ]+\\(([[:alnum:]]*?[ ]?[*]?\\([[:alnum:]]+\\))[ ]+\\)?\\(Test[[:alnum:]_]+\\)(.*)")
  (save-excursion (re-search-backward "^func[ ]+\\(([[:alnum:]]*?[ ]?[*]?\\([[:alnum:]]+\\))[ ]+\\)?\\(Test[[:alnum:]_]+\\)(.*)") (spacemacs/go-run-tests (cond (go-use-testify-for-testing (concat "-run='Test" (match-string-no-properties 2) "' -testify.m='" (match-string-no-properties 3) "'")) (go-use-gocheck-for-testing (concat "-check.f='" (match-string-no-properties 3) "$'")) (t (concat "-run='" (match-string-no-properties 3) "$'")))))
  (if (string-match "_test\\.go" buffer-file-name) (save-excursion (re-search-backward "^func[ ]+\\(([[:alnum:]]*?[ ]?[*]?\\([[:alnum:]]+\\))[ ]+\\)?\\(Test[[:alnum:]_]+\\)(.*)") (spacemacs/go-run-tests (cond (go-use-testify-for-testing (concat "-run='Test" (match-string-no-properties 2) "' -testify.m='" (
```

**Comment by smile13241324** [comment]
Fix merged, @joelpet please close this ticket when your issue is gone

**Comment by joelpet** [comment]
Confirmed working in `develop`. Thanks for the quick response.
