### ISSUE TITLE
Autocompletion does not work with helm and org-refile

### ISSUE THREAD

**Issue by pietrodito** [syl20bnr/spacemacs#13721]
#### Description :octocat:
Autocompletion does not work with helm and org-refile

#### Reproduction guide :beetle:
- Start Emacs
- Customize org-refile related variables as below:
```
  (setq org-agenda-files '("~/Nextcloud/org/life.org"
                           "~/Nextcloud/org/work.org"))
  (setq org-refile-targets '((org-agenda-files :maxlevel . 100)))
  (setq org-refile-allow-creating-parent-nodes 'confirm)
  (setq org-refile-use-outline-path 'file)
``` 
- Open some `.org` file.
- Use command `org-refile` on a subtree
- Try to use autocompletion feature to navigate .org files and heading trees

*Observed behaviour:* :eyes: :broken_heart:
`<TAB>` does nothing

*Expected behaviour:* :heart: :smile:
Autocompletion as usual with helm

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 85b57ecd0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(ess
 (general :location local)
 (smartparens :location local)
 (dired :location local)
 (pdfs :location local)
 (stats :location local)
 (coding-tools :location local))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by alexey0308** [comment]
Probably related https://github.com/syl20bnr/spacemacs/issues/3094
```
(setq org-outline-path-complete-in-steps nil)
```
Is it a solution?

**Comment by pietrodito** [comment]
Yes it is. Many tx.
