### ISSUE TITLE
gg=G replaces tabs with spaces in org-babel makefile

### ISSUE THREAD

**Issue by hoosierEE** [syl20bnr/spacemacs#13736]
#### Description :octocat:
typing gg=G replaces tabs with spaces in org-babel makefile code block

#### Reproduction guide :beetle:
- Start Emacs
- create org-mode file e.g. EXAMPLE.org
- Add content to org-mode file, including code block like this (note: there should be 1 tab in front of "foo", but it doesn't appear in a GitHub issue)

```
# -*- org-src-preserve-indentation: t -*-
#+begin_src makefile :tangle src/Makefile :mkdirp yes :exports code
all:
  foo bar
#+end_src
```
  
- type `gg=G` to auto-indent the whole EXAMPLE.org buffer file

*Observed behaviour:* :eyes: :broken_heart:
Tab character inside the SRC block has been replaced with spaces

*Expected behaviour:* :heart: :smile:
Tab character is preserved.

#### System Info :computer:
- OS: darwin
- Emacs: 26.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(git csv python markdown org latex javascript html themes-megapack
     (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
     (spell-checking :variables spell-checking-enable-by-default nil)
     (syntax-checking :variables syntax-checking-enable-by-default nil))
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

#### Backtrace :paw_prints:
```
```

**Comment by alexey0308** [comment]
This is likely due to the makefile-mode: could you please confirm, that you observe same behaviour during editing a Makefile in makefile-mode? If yes, it is probably to contact emacs dev list, since makefile-mode is a part of emacs.

**Comment by alexey0308** [comment]
Indentation is set according to the major mode. Tabs are converted depending on the value of evil-indent-convert-tabs variable.
(setq evil-indent-convert-tabs nil org-src-tab-acts-natively nil) will result in no re-indentation inside code blocks. One needs to edit code blocks using org-edit-special in this case.

**Comment by hoosierEE** [comment]
Thanks @alexey0308 setting those variables is ideal for my workflow (I prefer to use org-edit-special for editing source blocks).

Here's what I put at the top of my org-mode file; `gg=G` now works as desired:

```
# -*- evil-indent-convert-tabs: nil -*-
# -*- org-src-tab-acts-natively: nil -*-
```
