### ISSUE TITLE
twitter-leader-key conflicting with tools-prefix-key

### ISSUE THREAD

**Issue by WalnerM** [syl20bnr/spacemacs#13734]
#### Description :octocat:

These two leader keys are conflicting with each other:

https://github.com/syl20bnr/spacemacs/blob/41276119eae0750d4bb1e8a3ac119da48e52fb3b/layers/%2Bweb-services/twitter/packages.el#L22

https://github.com/syl20bnr/spacemacs/blob/41276119eae0750d4bb1e8a3ac119da48e52fb3b/layers/%2Bspacemacs/spacemacs-defaults/keybindings.el#L23

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 41276119e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
- System configuration features:

**Comment by gvc** [comment]
I stumbled upon this as well, and was thinking of remapping `twit` leader key to `T`. This is done in other places with compile/comments and Capture for orgmode. Do you think that would be a good solution?

**Comment by smile13241324** [comment]
Hmpf, I've totally overlooked that layer, lets rebind the global one to `SPC a t t` for application/tools/twitter.

**Comment by smile13241324** [comment]
Done, please double check if you still have conflicts @WalnerM.

**Comment by lebensterben** [comment]
This was fixed in https://github.com/syl20bnr/spacemacs/commit/70441bd088ad51411232355fa88af797c8b134f5
