### ISSUE TITLE
Key bindings conflit: org-journal package VS org layer

### ISSUE THREAD

**Issue by emiltoacs** [syl20bnr/spacemacs#13735]
#### Description :octocat:
Keybindings for org-journal setup by the org layer are conflicting with the keybindings of the org-journal package.

#### Reproduction guide :beetle:
- Load the org layer in your dotspacemacs-configuration-layers
- Enable the org-journal support `org-enable-org-journal-support t`
- Open the Emacs calendar (eg. use `org-time-stamp`)

*Observed behaviour:* :eyes: :broken_heart:
In the echo area and *Message* buffer:
> Key sequence i j starts with non-prefix key i

That is particularly annoying when you use `org-time-stamp` because it
conceals the calendar prompt used to choose the date.

*Expected behaviour:* :heart: :smile:
No keybindings clash

#### Code to investigate

- in org layer packages.el in function `org/init-org-journal ()`
``` elisp
(spacemacs/set-leader-keys-for-major-mode 'calendar-mode
       "i" 'org-journal-new-date-entry)
```
- in org-journal package in the `eval-after-load "calendar"`
``` elisp
(define-key calendar-mode-map (kbd "i j") 'org-journal-new-date-entry)
```

#### Solutions

1. Remove the binding "i" in the org layer for `org-journal-new-date-entry` (my current workaround)
2. Change the key bindings in the layers
3. Unbind some of the package key bindings

#### Proposition of pull request

I am willing to contribute for the first time to spacemacs so I can issue a pull request to solve this bug. According to the discussion I'm open to most appropriate solution to solve this bug.

Also there are some obsolete functions of org-journal used in the org layer that I could update.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 41276119e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-idle-delay 0.2 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual auto-completion-use-company-box t auto-completion-enable-sort-by-usage t)
 better-defaults
 (colors :variables colors-colorize-identifiers 'variables)
 command-log
 (dash :variables dash-autoload-commondocsets nil helm-dash-docset-newpath "~/.local/share/Zeal/Zeal/docsets")
 (deft :variables deft-zetteldeft t)
 emacs-lisp git
 (helm :variables helm-enable-auto-resize t helm-buffer-max-length 45)
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 latex perl5 markdown multiple-cursors pandoc
 (ranger :variables ranger-cleanup-on-disable t ranger-cleanup-eagerly t ranger-ignored-extensions
         '("avi" "fid" "flv" "m4v" "mkv" "mp4" "mpg" "webm" "mp4" "iso")
         ranger-max-preview-size 10 ranger-width-preview 0.45 ranger-show-hidden t ranger-show-preview t)
 restructuredtext
 (spacemacs-layouts :variables persp-autokill-buffer-on-remove 'kill-weak)
 (shell :variables shell-default-shell 'ansi-term shell-default-position 'bottom shell-default-height 36 shell-enable-smart-eshell t shell-default-term-shell "/bin/zsh" multi-term-program "/bin/zsh" close-window-with-terminal t)
 (spell-checking :variables enable-flyspell-auto-completion nil spell-checking-enable-by-default nil)
 syntax-checking systemd treemacs unicode-fonts version-control web-beautify csv
 (clojure :variables clojure-enable-fancify-symbols t)
 dap
 (javascript :variables javascript-fmt-tool 'web-beautify javascript-backend 'lsp)
 go groovy html
 (java :variables java-backend 'lsp)
 json
 (lsp :variables lsp-navigation 'both lsp-ui-doc-include-signature t lsp-ui-sideline-show-symbol t lsp-prefer-flymake nil)
 (python :variables python-backend 'lsp)
 ruby shell-scripts langtool bbcode dokuwiki mlt-org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by smile13241324** [comment]
I am not sure if this conflict is still there. I have checked the latest version of org journal and they bind `j n` for `org-journal-new-date-entry` now, this should keep `i` free for our use.

As to obsolete functions, please go ahead we always need people helping to keep the layers up-to-date. For a quick introduction please check CONTRIBUTING.org, details we can discuss during the reviewing process.

**Comment by emiltoacs** [comment]
@smile13241324 indeed org-journal update has solved the problem so no changes are needed, I have sent the pull request to update the obsolete function even if it's a very small change.
