### ISSUE TITLE
[FEATURE REQUEST] Darker option for mode-line color codes

### ISSUE THREAD

**Issue by treymerkley** [syl20bnr/spacemacs#13731]
When using a dark theme, the Evil state colors are great: They act as a light background for dark text, and so everything is very clear and crisp. 

Light themes, on the other hand, are often difficult to use because they have much lighter text color for the mode line, making it difficult to read the information you have your mode line present.

The solution, to me, would be to introduce a darker variant of the colors, one that you could tell what the colors are, but would provide a good contrast against light text, with some way of setting the mode line to use the lighter states in your .spacemacs.

Thanks!

**Comment by jr0cket** [comment]
Adding screenshots with examples of the color issues you are experiencing would be very helpful to understand the issue raised.

I used the`spacemacs-light` theme for most of the last year without noticing any particular issues with the mode line, so am curious to understand the issue in more detail.

I now use the doom modeline, as its much simpler and I dont need all the information the spacemacs modeline theme presents.
```   dotspacemacs-mode-line-theme '(doom)```

I also changed to the doom-gruvbox-light theme which may be of interest to you, as its had darker text.  
```dotspacemacs-themes '(doom-gruvbox-light doom-solarized-light doom-solarized-dark spacemacs-light spacemacs-dark)```

Example screenshots of the doom-gruvbox-light theme and the spacemacs-light theme are here 
https://practicalli.github.io/spacemacs/install-spacemacs/themes.html

**Comment by treymerkley** [comment]
So here's how the modeline for `gruvbox-light-hard` looks. I think the best way to describe it is very low contrast.
![Screenshot_20200707_101702](https://user-images.githubusercontent.com/28458492/86811452-2b488d80-c03b-11ea-9737-ad99bd5a8160.png)

**Comment by lebensterben** [comment]
This is pretty much out of the scope of this repository.
Please use a custom theme instead.
