### ISSUE TITLE
spacemacs will automatically delete all go related packages when bootup, even with go layer configed

### ISSUE THREAD

**Issue by zhenlei** [syl20bnr/spacemacs#13732]
#### Description :octocat:
Every time spacemcs bootup, it will delete all layers and packages related to "go" layer

#### Reproduction guide :beetle:
- Start Emacs
1. add go layer to dotfile
2. start emaacs and open a go file, emacs will promote that go layer need to be installed. install all go packages
3. restart emacs

*Observed behaviour:* :eyes: :broken_heart:
 below packages will be deleted on emacs startup
(Spacemacs) --> deleting swiper... [1/19]
Package ‘swiper-20200503.1102’ deleted.
(Spacemacs) --> deleting ivy... [2/19]
Package ‘ivy-20200624.1140’ deleted.
(Spacemacs) --> deleting helm-gtags... [3/19]
Package ‘helm-gtags-20200602.1610’ deleted.
(Spacemacs) --> deleting godoctor... [4/19]
Package ‘godoctor-20180710.2152’ deleted.
(Spacemacs) --> deleting go-tag... [5/19]
Package ‘go-tag-20180227.411’ deleted.
(Spacemacs) --> deleting go-rename... [6/19]
Package ‘go-rename-20190805.2101’ deleted.
(Spacemacs) --> deleting go-mode... [7/19]
Package ‘go-mode-20200425.1740’ deleted.
(Spacemacs) --> deleting go-impl... [8/19]
Package ‘go-impl-20170125.1552’ deleted.
(Spacemacs) --> deleting go-guru... [9/19]
Package ‘go-guru-20181012.330’ deleted.
(Spacemacs) --> deleting go-gen-test... [10/19]
Package ‘go-gen-test-20171023.358’ deleted.
(Spacemacs) --> deleting go-fill-struct... [11/19]
Package ‘go-fill-struct-20171225.331’ deleted.
(Spacemacs) --> deleting go-eldoc... [12/19]
Package ‘go-eldoc-20170305.1427’ deleted.
(Spacemacs) --> deleting ggtags... [13/19]
Package ‘ggtags-20190320.2208’ deleted.
(Spacemacs) --> deleting flycheck-golangci-lint... [14/19]
Package ‘flycheck-golangci-lint-20190330.1412’ deleted.
(Spacemacs) --> deleting dap-mode... [15/19]
Package ‘dap-mode-20200625.1904’ deleted.
(Spacemacs) --> deleting counsel-gtags... [16/19]
Package ‘counsel-gtags-20200101.1701’ deleted.
(Spacemacs) --> deleting counsel... [17/19]
Package ‘counsel-20200619.1030’ deleted.
(Spacemacs) --> deleting company-go... [18/19]
Package ‘company-go-20190203.19’ deleted.
(Spacemacs) --> deleting bui... [19/19]
Package ‘bui-20200426.2219’ deleted.

*Expected behaviour:* :heart: :smile:
don't delete go related packages

#### System Info :computer:
- OS: darwin
- Emacs: 27.0.90
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 05bc20d80)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((plantuml :variables org-plantuml-jar-path "~/plantUml.jar")
 helm
 (cmake :variables cmake-enable-cmake-ide-support t)
 emacs-lisp git markdown org lsp
 (go :variables go-backend 'go-mode)
 python
 (c-c++ :variables c-c++-backend 'lsp-clangd c-c++-enable-auto-newline t c-c++-enable-clang-format-on-save t c-c++-enable-google-style t)
 shell-scripts
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 rebox imenu-list
 (osx :variables osx-command-as 'hyper osx-option-as 'meta osx-control-as 'control osx-function-as 'none osx-right-command-as 'left osx-right-option-as 'left osx-right-control-as 'left))
```
- System configuration features: RSVG GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by ebeem** [comment]
same here with the dart layer

**Comment by smile13241324** [comment]
Never heard of this, to be honest. However if spacemacs asks whether to install a layer it is a strong indication that the layer is not properly set in your dotfile. Can you reproduce the issue with a standard dotfile without user config in place? Can you reproduce the issue on an official release of emacs 26.3?

**Comment by lebensterben** [comment]
if this problem still persist, feel free to reopen this issue and post your entire ~/.spacemacs file
