### ISSUE TITLE
Mnemonics: are they all in one place somewhere?

### ISSUE THREAD

**Issue by Trevoke** [syl20bnr/spacemacs#1374]
The way I want to explore spacemacs is to start from the mnemonics and work my way down.

I find it frustrating if I'm looking at source code, and suddenly I think "Oh, I wish I could jump to the definition for this function".. But I don't know how to get started because I have to hunt down the way to do it. 

So: where can I find all the mnemonics? I have conventions, readme and documentation open and I think, if the table exists, I haven't seen it.

**Comment by tuhdo** [comment]
You can press `SPC f e h`, select a layer and press `RET` to open a document buffer for that layer which also includes all the key bindings. Most layers use `SPC m g g` convention to go to a definition, which is quite consistent.

**Comment by syl20bnr** [comment]
@Trevoke You can read about the conventions but the file is not very well organized: https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.md

Also pressing `SPC` and waiting for the guide-key buffer will give you what you want BUT it does not work  for `SPC m` right now.

**Comment by Trevoke** [comment]
My question is much more generic than that, Tu Do. I think Sylvain gets the
idea. Unfortunately, I was stuck without internet and because I couldn't
easily discover spacemacs, I went back to my default configuration because
it was easier for me to get things done with it.

**Comment by StreakyCobra** [comment]
@Trevoke Does `which-key` (which is working for all keys, including `SPC m` and evil normal keybinding) in conjunction with `SPC :` which is showing the keybindings on which functions are mapped, fulfil your needs?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
