### ISSUE TITLE
[discussion] Support install and use of `develop` branch until Spacemacs 0.300 released

### ISSUE THREAD

**Issue by practicalli-john** [syl20bnr/spacemacs#13748]
In the Spacemacs Gitter channel, the most common piece of advice given to people with issues is to update to the Spacemacs `develop` branch.  This fixes the large majority of issues related to Spacemacs itself (not including packages).  There has also been an increase in issues raised recently where people are trying to use functionality only available in develop (eg. language support, LSP features, etc)

Would it be appropriate to add details on installing the `develop` branch to the spacemacs.org webpage, alongside the current install instructions?

![spacemacs-webpage-develop-button-and-install](https://user-images.githubusercontent.com/250870/86590253-24604300-bf87-11ea-8b45-e51ce5ce58a6.png)

A successful migration from an existing `master` install to `develop` requires changing the branch and updating the .spacemacs file from spacemacs.template. I was helping many people with this, so I create a guide for migrating

https://practicalli.github.io/spacemacs/install-spacemacs/switch-to-develop.html

Would this content be useful to add to Spacemacs documentation and where would be the appropriate place.

Thank you.

**Comment by Kazark** [comment]
Or does this mean it's time to cut bait and just release `develop`?

**Comment by jr0cket** [comment]
If there are only comments about releasing develop, I'll close this issue, as that has been discussed many times across many other issues and there are clear reasons not to do so.

**Comment by davidpiano** [comment]
IMO the reason you need to ask is that (in fact, but no one admits it) `master` is not really being supported anymore. Or, not better than `develop` anyway.

**Comment by Kazark** [comment]
@jr0cket I apologize; I am not up to speed on all those conversations. I didn't mean to derail the discussion.

**Comment by emacs18** [comment]
I don't understand why `develop` branch cannot be released.  I can only assume folks have good reasons.  In that case modifying installation instruction to promote `develop` branch as the first alternative and `master` as the second less desirable alternative sounds like a good idea to me.  Also an explanation as to why we keep around `master` branch would be nice.  My only knowledge of `master` branch is that when folks submit bug reports against `master`, then they are told to migrate to `develop`.  Latest change on `master` is 10 months ago.

**Comment by duianto** [comment]
Syl20bnr was working on finishing the `spacelpa` support. But then he got crazy busy at work and with homeschooling kids, so he'll try to work on it when he gets a spare moment.

The suggestion to promote the `develop` branch on the webpage has been forwarded.
