### ISSUE TITLE
Unknown layer Julia

### ISSUE THREAD

**Issue by Qfl3x** [syl20bnr/spacemacs#13741]
#### Description :octocat:
julia layer not found

#### Reproduction guide :beetle:
- add julia to .spacemacs layers
- restart emacs
- "Warnings:
                  - Unknown layer julia declared in dotfile. "

*Observed behaviour:* :eyes: :broken_heart:
No julia layer

*Expected behaviour:* :heart: :smile:
Julia layer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git python julia)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD

#### Backtrace :paw_prints:
```
```

**Comment by Qfl3x** [comment]
Aaaaaaand it fixed itself

**Comment by smile13241324** [comment]
You are on master, master is very out of date, julia is only available on develop. Please change branches.

**Comment by jr0cket** [comment]
@Qfl3x here is a guide to switching from Spacemacs master to develop
https://practicalli.github.io/spacemacs/install-spacemacs/switch-to-develop.html

It seems the large majority of Spacemacs uses are running the `develop` branch and I have found it a reliable experience.

**Comment by Qfl3x** [comment]
Weirdly, even on develop it says the same message. 

I am on develop proper, `julia` is present in `+lang`.

**Comment by Qfl3x** [comment]
The problem has been solved. mistakenly typed `.emacs.d` instead of `emacs.d`
