### ISSUE TITLE
Error (use-package): Cannot load evil-unimpaired

### ISSUE THREAD

**Issue by haswell4u** [syl20bnr/spacemacs#13743]
Hello,

I'm trying to install spacemacs on my windows 10 desktop PC.
And when spacemacs first started, all packages were installed except the **evil-unimpaired** package.

The error message is,

> An error occurred while installing evil-unimpaired (error: (file-missing Opening directory No such file or directory c:/Users/jwkim/AppData/Roaming/.emacs.d/.cache/quelpa/melpa/recipes))

> Error (use-package): Cannot load evil-unimpaired

I searched for the evil-unimpaired package in the MELPA package list, but it doesn't seem to exist.
Is this temporary because there is no evil-unimpaired in MELPA? Or is there something I'm missing?
(I followed the instructions in the install section.)

**Comment by jasperpilgrim** [comment]
To the best of my knowledge, `evil-unimpaired` is fetched locally, so it shouldn't matter if it is present in the MELPA package list or not. I could be mistaken.

A quick google gave me issue https://github.com/syl20bnr/spacemacs/issues/8341. I am not certain it is an identical issue, but you might try one or all of the following:

- turn it off and on again (restart Emacs a few times)
- delete the cache directory
- run `emacs --insecure` from the command line

You could also run `emacs --insecure --debug-init` from the command line and post the output here (along with your Emacs version).

**Comment by haswell4u** [comment]
After re-installation, the third method you suggested (`emacs --insecure`) solves this problem.
Sorry for asking the easy question.
But thanks for your kind advice.
