### ISSUE TITLE
Gradle bindings infect bindings of any subsequently used major-mode

### ISSUE THREAD

**Issue by Kazark** [syl20bnr/spacemacs#13750]
#### Description :octocat:
After using Java mode, Gradle keybindings infect or even clobber keybindings of any subsequently used major-mode.

#### Reproduction guide :beetle:
- Prerequisites: `java` layer installed, as well as one other layer (for this example, we will use `agda`, but this problem is not specific to the Agda layer)
- Start Emacs
- Open a Java file
- Open an Agda file
- Press `,` or `SPC m` to see the major mode menu

*Observed behaviour:* :eyes: :broken_heart:
The critical Agda major mode keybinding of `l` as `agda2-load` has been replaced with a Gradle menu! (Not sure if this whether this is more frustrating, or more hilarious.) Again, though, Agda is only a particularly poignant example; it seems that at this point Gradle has permanently infected all major mode menus.

*Expected behaviour:* :heart: :smile:
The Agda mode (or whatever major mode is pertinent) keybindings are not polluted by those from the Java layer.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: keith (rev. 6729eb62a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(agda auto-completion c-c++ emacs-lisp games git github graphviz
      (haskell :variables haskell-completion-backend 'ghci)
      helm html idris java javascript jsonnet markdown org osx
      (scala :variables scala-backend 'scala-metals scala-enable-eldoc t scala-auto-start-backend t)
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      scheme slack spell-checking sql syntax-checking version-control yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
No actual exception is surfaced.

**Comment by Kazark** [comment]
My guess is that what's going on here is that because Gradle is coming in as a [minor mode](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/java/packages.el#L65), it's bindings are sticky outside of Java mode.

**Comment by Kazark** [comment]
Hm, I think binding these to a minor mode and yet putting them under `SPC m` is just fundamentally incorrect. It seems to me that their source as a part of a minor mode is not important here and that the thing to do is just bind them w.r.t. the current major mode only. I think that should scope things correctly. I will try to make this change and if it fixes things will open a PR.

**Comment by Kazark** [comment]
Okay, now I'm doubting myself on that. I probably need to get a better understanding of the relationship between minor and major modes, and of the relationship between `spacemacs/declare-prefix-for-mode` and `spacemacs/set-leader-keys-for-minor-mode`.

**Comment by Kazark** [comment]
Alright, this one is over my head given my current understanding of Spacemacs. :/

**Comment by duianto** [comment]
Confirmed, `gradle-mode` seems to be enabled in every mode after opening a `.java` file.

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ce5f278a2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(agda autohotkey auto-completion c-c++ dap emacs-lisp git helm html java javascript
      (latex :variables latex-build-command "LatexMk" latex-enable-magic t)
      (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
      multiple-cursors
      (org :variables org-agenda-files
           '("~/org/notes.org"))
      python ruby
      (shell :variables shell-default-shell 'eshell shell-default-height 30)
      spell-checking sql
      (syntax-checking :variables syntax-checking-enable-by-default nil)
      themes-megapack treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by duianto** [comment]
Could it be caused by https://github.com/jacobono/emacs-gradle-mode seting the key map globally?
```elisp
  :global t
```

https://github.com/jacobono/emacs-gradle-mode/blob/e4d665d5784ecda7ddfba015f07c69be3cfc45f2/gradle-mode.el#L176-L183
```elisp
;;;###autoload
(define-minor-mode gradle-mode
  "Emacs minor mode for integrating Gradle into compile.
Run gradle tasks from any buffer, scanning up to nearest gradle
directory to run tasks."
  :lighter " Gradle"
  :keymap 'gradle-mode-map
  :global t)
```

**Comment by Kazark** [comment]
@duianto good call. The docs for `define-minor-mode` say about `:global`:

> If non-nil specifies that the minor mode is not meant to be
> buffer-local, so don't make the variable MODE buffer-local.
> By default, the mode is buffer-local.

**Comment by Kazark** [comment]
Not encouragingly, though, it looks like the author of `gradle-mode` hasn't been on GitHub since 2017. 😬

**Comment by Kazark** [comment]
And the last update of `gradle-mode` is from early in 2015. 😬 😬

**Comment by Kazark** [comment]
Yep, when I locally modified that and removed `:global t`, it fixed the problem. Good call, @duianto . The question remains, though: what's the best long-term fix? There was obviously a reason he had it set up like that, and I'm leery of breaking something else about it, when I'm such a n00b to all this. And: is he even accepting PRs? (It looks like he isn't.) And: `gradle-mode` never actually worked right for me in the first place; I've been running `gradle` by launching a terminal within Emacs. So maybe just disabling the whole mode is what I want anyway. 🤔

**Comment by Kazark** [comment]
Yeah, `gradle-mode` is actually not working for me at all anyway. I propose we remove it, given that it is implemented in a disruptive way, clearly not maintained for 5 years, and nonfunctional anyway. How are these things adjudicated for Spacemacs? Should I just go ahead and open a PR?

**Comment by smile13241324** [comment]
@Kazark I would agree, lets remove it if needed we can still create a better maintained package for this.

PRs are welcome, as long as they adhere to the rules defined in CONTRIBUTING.org. If something is controversial discussing it first in a ticket is appreciated. If not done it is discussed within the PR anyway :).

**Comment by Kazark** [comment]
@smile13241324 Thanks. I'll hope to submit a PR to deal with this then.

**Comment by smile13241324** [comment]
Merged the PR, please close the ticket when the issue is gone.

**Comment by Kazark** [comment]
Confirmed that the problem is gone in `develop`, with no adverse side-effects. Thanks @smile13241324 .
