### ISSUE TITLE
Env variables are not read in darwin on develop branch

### ISSUE THREAD

**Issue by umucorn** [syl20bnr/spacemacs#13761]
#### Description :octocat:
When I open a Rust file, I see many errors.

eldoc error: (user-error No such file or directory: /usr/local/src/rust/src. Please set racer-rust-src path or RUST_SRC_PATH

There is another error that includes name of flycheck and it's not being able to find `cargo`.

They are in my path in both .profile and .zprofile files. RUST_SRC_PATH is also set.

Here is my .zprofile file: (same with .profile file)

```sh
export PATH="$HOME/.cargo/bin:$PATH"
export RUST_SRC_PATH=`rustc --print sysroot`/lib/rustlib/src/rust/src
```

#### Reproduction guide :beetle:
- Start Emacs
- Open a Rust file
- Navigate to different Rust codes to see error. The error is the first error I mentioned above.

*Observed behaviour:* :eyes: :broken_heart:
I wasn't able to use rust features of spacemacs. Code coloring is working well.

*Expected behaviour:* :heart: :smile:
I should be able to use Rust language features of spacemacs.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f3f0e3a98)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html javascript typescript python rust helm auto-completion emacs-lisp git markdown
      (osx :variables osx-option-as 'none osx-right-option-as 'none osx-command-as 'meta osx-control-as 'control)
      syntax-checking version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS

**Comment by alexey0308** [comment]
Are these variables also set to another value in .spacemacs.env file?
https://develop.spacemacs.org/doc/DOCUMENTATION.html#default-behavior

**Comment by umucorn** [comment]
Clearing this file, running `env` command in console and copy-pasting the result to the file you mentioned have solved my problem.
