### ISSUE TITLE
(Spacemacs) Error in dotspacemacs/user-config: :token is required

### ISSUE THREAD

**Issue by richardeast** [syl20bnr/spacemacs#13762]
#### Description :octocat:
(Spacemacs) Error in dotspacemacs/user-config: :token is required appears on start up

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The error:
(Spacemacs) Error in dotspacemacs/user-config: :token is required

appears in white on a red background.
This occurred after updating develop branch.

*Expected behaviour:* :heart: :smile:
Should start up as expected

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f3f0e3a98)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv html javascript yaml
     (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory "~/org/documents/snippets/")
     (clojure :variables clojure-enable-fancify-symbols t)
     (colors :variables colors-enable-rainbow-identifiers nil colors-colorize-identifiers nil colors-enable-nyan-cat-progress-bar
             (display-graphic-p))
     command-log emacs-lisp emoji
     (git :variables git-magit-status-fullscreen t git-enable-github-support t git-gutter-use-fringe t)
     github helm markdown multiple-cursors
     (org :variables org-enable-github-support t org-enable-reveal-js-support t)
     (ranger :variables ranger-show-preview t ranger-show-hidden t ranger-cleanup-eagerly t ranger-cleanup-on-disable t)
     (restclient :variables restclient-use-org t)
     (ruby :variables)
     rust search-engine
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     (slack :variables slack-spacemacs-layout-name "@Slack" slack-spacemacs-layout-binding "s")
     spell-checking sql syntax-checking
     (treemacs :variables treemacs-use-filewatch-mode t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:
```
(Spacemacs) Calling dotfile user config...
Configuring package alert...done
Configuring package slack...done
(Spacemacs) Error in dotspacemacs/user-config: :token is required
```

**Comment by beyondpie** [comment]
@richardeast 
I guess the problem might relate with the layer *slack*. would you mind to comment *slack* layer to give it a try ?

**Comment by richardeast** [comment]
Yes. You're right. The :token keyword was being used by the slack layer. Thank you.
