### ISSUE TITLE
Dotspacemacs compiling everytime on reload.

### ISSUE THREAD

**Issue by sudraka** [syl20bnr/spacemacs#13760]
Every time I reload my dotspacemacs file using "space f e R" after some minor change in user-config, all packages are being compiled once again from scratch. It is killing an enormous amount of time. Even if they were updated a few hours ago, while the emacs initiated.

**Comment by beyondpie** [comment]
never face such an issue. which branch and what's the Emacs version you are using?

**Comment by smile13241324** [comment]
Same questions here, @Sudraka. Please provide some more information about your config, what you describe is no general issue so I am afraid I cannot say more without some info about your dotfile and emacs you are using.

There is a handy function `spacemacs/report-issue` which provides a list of infos about your system. Please edit your post to include this information. I am sure someone will then have a look into your issue.
