### ISSUE TITLE
Org layer bypasses upstream customisation mechanism for org-archive-subtree

### ISSUE THREAD

**Issue by cormacc** [syl20bnr/spacemacs#13772]
#### Description :octocat:
Org layer keybinding bypasses upstream customisation mechanism for org-archive-subtree.

PR to follow -- binds keys to `org-archive-subtree-default` rather than `org-archive-subtree`.

#### Reproduction guide :beetle:
- Start Emacs
- Set a custom subtree archiving command by modifying the value of `org-archive-default-command`
- Open an org-mode file and select/archive a subtree using `<spc> m s A`

*Observed behaviour:* :eyes: :broken_heart:
Default subtree archiving command (`org-archive-subtree`) invoked

*Expected behaviour:* :heart: :smile:
Custom function specified by `org-archive-default-command` invoked

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: org-archive-subtree-default (rev. 1e677bb53)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(typescript
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 (c-c++ :variables c-c++-backend 'lsp-clangd c-c++-enable-semantic-highlight 'rainbow)
 ceedling
 (cmake :variables)
 (colors :variables colors-enable-nyan-cat-progress-bar t nyan-bar-length 8)
 csv chrome
 (dash :variables dash-docset-newpath "~/.local/share/Zeal/Zeal/docsets")
 deft docker emacs-lisp git
 (go :variables gofmt-command "goimports" go-use-gometalinter t godoc-at-point-function 'godoc-gogetdoc)
 haskell helpful html
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 imenu-list ivy javascript
 (lsp :variables lsp-file-watch-threshold 10000 lsp-rust-server 'rust-analyzer)
 (markdown :variables markdown-live-preview-engine 'vmd)
 multiple-cursors octave
 (org :variables org-enable-sticky-header t org-enable-reveal-js-support t)
 org-roam my-org pandoc
 (plantuml :variables plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar" org-plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar")
 (python :variables python-backend 'lsp python-lsp-server 'mspyls python-formatter 'black python-format-on-save t python-sort-imports-on-save t python-fill-column 110 python-test-runner 'pytest)
 (ranger :variables ranger-show-preview t ranger-cleanup-on-disable t ranger-show-dotfiles t)
 react
 (ruby :variables ruby-test-runner 'rspec)
 (rust :variables rust-format-on-save t)
 scheme search-engine
 (shell :variables shell-default-shell 'vterm shell-default-term-shell "/bin/zsh")
 shell-scripts spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 sql systemd treemacs version-control windows-scripts yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by cormacc** [comment]
Resolved by #13773

**Comment by smile13241324** [comment]
Merged your PR, please close this issue when it is ok.

**Comment by cormacc** [comment]
Thanks Maximillian
