### ISSUE TITLE
semweb layer failing dotfile-test

### ISSUE THREAD

**Issue by sroertgen** [syl20bnr/spacemacs#13771]
When adding the [Semantic Web Layer](https://develop.spacemacs.org/layers/+lang/semantic-web/README.html) as `semweb` to the `dotspacemacs-configuration-layers` the dotfile-test fails.

#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 78176ff6f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults chrome csv emacs-lisp emoji git html ipython-notebook javascript
      (markdown :variables markdown-mmm-auto-modes
                '("c" "c++" "python" "javascript" "json" "scala"
                  ("elisp" "emacs-lisp")))
      (org :variables org-enable-reveal-js-support t org-re-reveal-root "file:////.../reveal.js-3.9.2" org-agenda-todo-ignore-scheduled t org-enable-github-support t org-enable-bootstrap-support t org-projectile-file "TODOs.org")
      osx
      (osx :variables osx-option-as 'meta osx-command-as 'hyper osx-right-command-as 'left osx-right-option-as 'none)
      python pandoc react
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking yaml version-control treemacs)
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

**Comment by duianto** [comment]
Confirmed.

The layer was renamed to `semantic-web` in this commit: https://github.com/syl20bnr/spacemacs/commit/53cb8a48d3e7a87b19c8eb4ade77d1394acfb550
> Move semweb to semantic-web
> 
> Minor configuration changes

But the readme wasn't updated with the new name.

A PR has been opened with a fix:
[semantic-web][docs] Fix layer renamed from semweb #13778

**Comment by smile13241324** [comment]
PR merged please check again and close this issue when its gone @sroertgen

**Comment by sroertgen** [comment]
Thank you a lot. It's working with `semantic-web`.
