### ISSUE TITLE
For all who have problem going up directory in helm-find-files

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1378]
You can use `C-l` to go up and `C-j` (not evilified Helm) to go in. The key bindings are on the homerow. Executing persistent action also enters the directory without entering Dired and in the next version it will be `TAB`. This means you can press `TAB` to go inside a directory.

**Comment by TheBB** [comment]
Some consistency between ido and helm would be nice. In ido, `C-h` goes up and `C-l` enters a directory, while in helm, as you say, `C-l` goes up and `C-j` enters. From a vim perspective, with left and right, the ido bindings definitely feel more natural.

**Comment by tuhdo** [comment]
> Some consistency between ido and helm would be nice. In ido, C-h goes up and C-l enters a directory, while in helm, as you say, C-l goes up. From a vim perspective, with left and right, the ido bindings definitely feel more natural.

`C-h` and `C-l` are probably added key bindings from Spacemacs. `TAB`/`C-z` or `C-j` is for entering directory. `C-l` was made just for conveniently go up and did not have Evil in mind, since Helm was made to be compatible with Emacs key bindings..

Probably @syl20bnr should add `C-h` and `C-l` when Helm is in `evil-mode` as well, for consistency. But definitely not for `holy-mode`.

**Comment by syl20bnr** [comment]
I took the decision to support only `C-j` and `C-k` in Helm buffer and remap the shadowed key bindings, this is for both `vim` and `emacs` style.
The rest is Helm default.

We should adopt the same philosophy in ido.

**Comment by justbur** [comment]
How about changing to something like `C-.` and `C-,` for moving in and out of directories in both ido and helm? These are what I use and they seem easy to remember and not to conflict with other key bindings.

**Comment by tuhdo** [comment]
Those key bindings don't work in terminal.

**Comment by justbur** [comment]
Hm, I didn't realize that. They could still be an option for the GUI users, no? I had to stop using `ido-find-file` because the inconsistency between helm and ido kept throwing me off. It also seems awkward to remap C-h in helm.

**Comment by TheBB** [comment]
`C-l` now goes up and `C-h` down.
