### ISSUE TITLE
Treemacs Documentation using Ace to open files isn't working

### ISSUE THREAD

**Issue by dustiestgolf** [syl20bnr/spacemacs#13786]
#### Description :octocat:
I am trying to set ace mode as the default action for pressing RET on a file.
I have added the lines suggested at the end of the treemacs layer documentation to `user-config` in my `.spacemacs` file. 
An error appears in the messages buffer stating:
`(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: treemacs-define-RET-action`.
Treemacs behavior does not change. 

It was suggested [here](https://github.com/syl20bnr/spacemacs/pull/13287) that I use 
```elisp
(setq treemacs-RET-action-config `((root-node-open . treemacs-toggle-node)))` 
```
instead. This does not result in an error, but it also does not change the treemacs RET behavior to use ace. 

#### Reproduction guide :beetle:
- Start Emacs
- open `.spacemacs`
- add the following lines to `user-config`
```elisp
(treemacs-define-RET-action 'file-node-closed #'treemacs-visit-node-ace)
(treemacs-define-RET-action 'file-node-open #'treemacs-visit-node-ace)
```
- restart emacs
- open treemacs and two windows
- select a file and press RET
- Ace does not activate and allow user to choose which window to open file in. 

*Observed behaviour:* :eyes: :broken_heart:
Using RET in treemacs does not open with ace allowing user to select which window to open file in. 

*Expected behaviour:* :heart: :smile:
When pressing RET on a file in treemacs acs is used to allow a user to select which window to open file in. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1e677bb53)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python auto-completion emacs-lisp git helm markdown multiple-cursors org treemacs pandoc)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
Ahhh now I understand what you mean. I have double checked the docs and indeed there is a mistake in the documented command. Basically the issue is that commands are used which are only available after `treemacs` has been loaded.

You can prevent this from happening by using this command:
```elisp
  (with-eval-after-load 'treemacs
    (treemacs-define-RET-action 'file-node-closed #'treemacs-visit-node-ace)
    (treemacs-define-RET-action 'file-node-open #'treemacs-visit-node-ace))
```
This defers the execution of the guarded code till `treemacs` is fully loaded.

I have added the modified command to the docs too.

**Comment by smile13241324** [comment]
@dustiestgolf please check whether this solves your issue and close this ticket when it does.

**Comment by dustiestgolf** [comment]
This solved my issue and it works without a hitch now. 

I am a little confused about why the code must be guarded in `user-config`. I thought that the code in that section was loaded after layer configuration. Is this different than fully loading treemacs? 

Thank you again for your help.

**Comment by smile13241324** [comment]
Well, in principle you are right, the layers are loaded as well as the packages, however to avoid the emacs typical startup delay almost everything is lazy loaded in spacemacs. The functions you need to call are not autoloaded so they are not available before the first autoloaded function of that package is called, therefore we need to delay our call till this happened.
