### ISSUE TITLE
Unable to load color "unspecified-fg"

### ISSUE THREAD

**Issue by zcjava** [syl20bnr/spacemacs#13784]
i use draclua-theme. it tip: Unable to load color "unspecified-fg". how fixed it

**Comment by smile13241324** [comment]
@zcjava sorry can't reproduce. I have just tried running `dracula` as well as `doom-dracula` on latest develop and it just worked.
Please provide some more information about your system and make sure that your packages and spacemacs is up-to-date.
Please also adjust your issue to match the official issue template, by copying the information from `spacemacs/report-issue`.

**Comment by zcjava** [comment]
> @zcjava sorry can't reproduce. I have just tried running `dracula` as well as `doom-dracula` on latest develop and it just worked.
> Please provide some more information about your system and make sure that your packages and spacemacs is up-to-date.
> Please also adjust your issue to match the official issue template, by copying the information from `spacemacs/report-issue`.

ye. i use spacemacs dev branch. and is newest. i use dracula-theme , it work well, but warning is :Unable to load color "unspecified-fg"

**Comment by be11ng** [comment]
I've had this problem for a while too.  This might be something along the lines of #6380 where its isn't a bug as such, and we just need to ignore it when the `*Messages*` buffer fills up with:
```
Unable to load color "unspecified-fg" [13 times]
```

Upstream, this may have something to do with dracula/emacs#59.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c39399045)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible auto-completion better-defaults bibtex c-c++ csv emacs-lisp epub
         (exwm :variables exwm-enable-systray t exwm-autostart-xdg-applications t exwm-locking-command "slock" :pin local)
         games git github gnus gtags
         (helm :variables helm-enable-auto-resize t)
         html ipython-notebook javascript latex markdown multiple-cursors
         (org :variables org-want-todo-bindings t)
         pass pdf python racket
         (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh")
         (spell-checking :variables spell-checking-enable-by-default nil)
         syntax-checking
         (treemacs :variables treemacs-use-git-mode 'deferred)
         vagrant w3m)
```
- Additional packages:
```elisp
(dracula-theme basic-theme cl-libify helm-exwm anki-editor
               (nethack :location local))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
Confirmed, I'm also seeing that message when using the `dracula` theme:
>Loading c:/Users/username/.spacemacs...done
Unable to load color "unspecified-fg"
PNG warning: Interlace handling should be turned on when using png_read_image
Unable to load color "unspecified-fg" [9 times]
Starting new Ispell process c:/tools/cygwin/bin/aspell.exe with default dictionary...
Spacemacs is ready.

be11ng seems to be correct that it's an upstream issue.

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9e6cfbb83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion c-c++ dap emacs-lisp git helm html java
            (javascript :variables javascript-backend 'lsp)
            (latex :variables latex-build-command "LatexMk" latex-enable-magic t)
            lsp
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            python ruby semantic-web
            (shell :variables shell-default-shell 'eshell shell-default-height 30)
            spell-checking sql syntax-checking themes-megapack treemacs
            (typescript :variables typescript-backend 'lsp)
            version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by vcg3rd** [comment]
Still have it in Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20).  My Messages are filled with it.
