### ISSUE TITLE
Startup error in layer groovy

### ISSUE THREAD

**Issue by juboba** [syl20bnr/spacemacs#13780]
#### Description :octocat:
Startup error in layer groovy

#### Reproduction guide :beetle:
- checkout any commit in `develop` after eacab7004
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The following message is shown on startup
```
An error occurred while post-configuring company in layer groovy (error: (void-variable groovy-mode))
```

*Expected behaviour:* :heart: :smile:
No error should be shown

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 39de9ff0a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(nginx ruby colors typescript
       (org :variables org-enable-github-support t org-enable-reveal-js-support t)
       auto-completion docker elm emacs-lisp games git haskell html imenu-list java javascript kubernetes lua markdown php prettier python react restclient
       (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
       spotify syntax-checking themes-megapack version-control vue yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by smile13241324** [comment]
@juboba fixed. Sorry my mistake, broke it when I introduced LSP support to this layer.
Please check and close this issue when it works again.

**Comment by juboba** [comment]
Confirming that is fixed in `develop`. Thanks @smile13241324
