### ISSUE TITLE
How to append search arguments in ivy?

### ISSUE THREAD

**Issue by jason--liu** [syl20bnr/spacemacs#13793]
Hi, 
I am new to spacemacs. recently I want to search a whole world in my project, so I add "-w" argument.
But it seems that there is an error.

After `SPC s p`

![image](https://user-images.githubusercontent.com/8001473/88281167-c61eb880-cd19-11ea-8a8e-9d78b38533b2.png)
while `start_kernel` is indeed in my project when I use `ag` search from terminal.

How Can I search with arguments?
>My config is:
System: ubuntu 18.04
spacemacs: develop branch

Thanks.

**Comment by henriquenj** [comment]
I don't think `SPC s p` forwards arguments to `ag`. The function that implements this is `spacemacs/counsel-search` which pass `nil` to the `EXTRA-AG-ARGS` argument (see the call [here](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+completion/ivy/funcs.el#L175).)

What you can do is try to customize `counsel-ag-base-command`, however that would be a global config, not limite to a particular search.

**Comment by dalanicolai** [comment]
Actually [counsel-ag](https://github.com/abo-abo/swiper/blob/master/counsel.el#L2965) provides the option to prepend with `SPC u SPC u` to give `EXTRA-AG-ARGS`. This also works with `SPC s p` (at least when `SPC s p` directs you to counsel-ag, which seems to be the case in the screenshot above).

Of course it would be great to update the docstring of `spacemacs/counsel-search` to add this information to the "docstring", but I am not sure what would be the best way to do this. As the options are different for every tool. And also I am not sure if the universal argument is forwarded to all tools

**Comment by vkuznetsov** [comment]
You can pass extra arguments to ag after a double dash:
`SPC s p`
`start_kernel -- -w`
