### ISSUE TITLE
pyenv and lsp via TRAMP point to remote machine instead of local machine

### ISSUE THREAD

**Issue by hakanyi** [syl20bnr/spacemacs#13808]
#### Description :octocat:
(1) When editing files locally, pyenv works perfectly fine and automatically activates the desired environment (which holds my Python language server) as expected.
However, when editing files remotely via TRAMP, the behavior is different as a) the environment is not set automatically (and hence LSP is not working) and b) trying to activate an environment manually (`, v s`) results in ["system", "/bin/bash:", "pyenv:", "command", "not", "found"].
(2) I'd like to be able to use my local environment (that holds pyls) when editing remote files.

#### Reproduction guide :beetle:
- Start Emacs
- Open python file in local project `SPC f f` --> Observe that both pyenv and lsp work
- Open python file in remote project via TRAMP `SPC f f /sshx:host:/file.py` --> Observe that both pyenv and lsp do not work 

*Observed behaviour:* :eyes: :broken_heart:
See 1) above 

*Expected behaviour:* :heart: :smile:
See 2) above

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 04b80d610)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm lsp markdown multiple-cursors
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking version-control treemacs dap
            (python :variables python-backend 'lsp python-fill-column 99 python-formatter 'yapf python-auto-set-local-pyvenv-virtualenv 'nil)
            julia)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by alexey0308** [comment]
Can using sshfs solve the issue?

**Comment by hakanyi** [comment]
Thanks @alexey0308 ! 
I switched to tramp as editing files (let alone using helm, projectile or magit) via sshfs turned out to be unbearably slow - If pyenv and lsp worked via sshfs it wouldn't help much, unfortunately.

Therefore, it'd be great to know of a way to keep pyenv-mode pointing to the local pyenv. If that's not possible, there's probably no other way than mirroring the local pyenv setup on the remote machine?

**Comment by alexey0308** [comment]
I do not know much about pyenv and lsp internals, but the documentation of lsp [says](https://emacs-lsp.github.io/lsp-mode/page/remote/), that it behaves differently for remote and local buffers. Hence, one needs to orchestrate 2 packages, pyenv and lsp.
However, I do not understand, what is the reason to keep code only remotely and invoke it locally. I would suggest to keep code locally as well then, and to sync it using git or rsync.
