### ISSUE TITLE
rust format on save

### ISSUE THREAD

**Issue by laynor** [syl20bnr/spacemacs#13807]
#### Description :octocat:
When `rust-format-on-save` is t, all the rust sources in the project are formatted and not just the saved buffer.

#### Reproduction guide :beetle:
- Start Emacs
- open a badly formatted rust project (or make one with `cargo new`, with at least two badly formatted files).
- enable the rust layer and set rust-format-on-save to t in the layer configuration
- modify one of the two files and save.

*Observed behaviour:* :eyes: :broken_heart:
Both badly formatted files have been formatted by cargo fmt.

*Expected behaviour:* :heart: :smile:
Only the saved file should be passed to the formatter, the other one should stay unmodified.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 04b80d610)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(dart go elixir
      (auto-completion
       (haskell :variables haskell-completion-backend 'intero))
      better-defaults clojure cmake colors common-lisp
      (rust :variables rust-format-on-save nil)
      c-c++ csv dap emacs-lisp factor git github haskell helm helpful html ibuffer javascript
      (lsp :variables lsp-rust-server 'rust-analyzer)
      (python :variables python-test-runner
              '(nose pytest)
              python-backend 'lsp)
      react shell-scripts sql syntax-checking
      (version-control :variables version-control-diff-tool 'diff-hl)
      yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
With these reproduction steps, only the current buffer gets formatted on save.
- create a new directory `~/temp/rust/`
- create a new rust project in that directory: `cargo init`
- create a file: `a.rs`
containing:
```rust
fn main() {
println!("a")
}
```
- If the format on save variable set to `t`: `(rust :variables rust-format-on-save t)`
to be able to save the file without indentation before the println! line,
disable format on save first: `M-x rust-disable-format-on-save`
- create a second file: `b.rs`
containing:
- To save without indentation, disable format on save in this buffer as well:
`M-x rust-disable-format-on-save`
```rust
fn main() {
println!("b")
}
```
- Restart Spacemacs or enable format on save again in both buffers: `M-x rust-enable-format-on-save`
- Open both files `a.rs` and `b.rs` side by side (`SPC w v`).
- Add a newline at the end of the buffer and save: `SPC f s`

### Observed
Only the selected buffer is formatted.

<details><summary>
PopOS 20.04, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3388972c2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm hy lsp multiple-cursors org
                 (python :variables python-backend 'anaconda python-formatter 'yapf)
                 (rust :variables rust-format-on-save t)
                 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking
                 (typescript :variables typescript-backend 'lsp)
                 version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3388972c2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion emacs-lisp git
            (haskell :variables haskell-completion-backend 'dante)
            helm hy imenu-list lsp multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            outshine python
            (rust :variables rust-format-on-save t)
            (shell :variables shell-default-shell 'eshell shell-default-height 30)
            spell-checking syntax-checking themes-megapack treemacs typescript version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by duianto** [comment]
The following is unrelated to this issue, but you've got the haskell layer declaration inside the auto-completion layer:
```elisp
(auto-completion
       (haskell :variables haskell-completion-backend 'intero))
```

**Comment by laynor** [comment]
> The following is unrelated to this issue, but you've got the haskell layer declaration inside the auto-completion layer:
> 
> ```emacs-lisp
> (auto-completion
>        (haskell :variables haskell-completion-backend 'intero))
> ```

Thanks ^^;;
