### ISSUE TITLE
org-match-sparse-tree multiple tag search not working

### ISSUE THREAD

**Issue by ildarf** [syl20bnr/spacemacs#13809]
#### Description :octocat:
org-match-sparse-tree does not support boolean basic logic like described in https://orgmode.org/manual/Tag-Searches.html#Tag-\
Searches for multiple tag search

#### Reproduction guide :beetle:
- Start Emacs
- create some org entries
- add multiple tags to them, example:
  - TODO buy this :buy:hobby:
  - TODO buy that :buy:household:
- Now press C-c / m
- enter as search string: +buy+hobby or buy&hobby or '+buy+hobby' or 'buy&hobby'

*Observed behaviour:* :eyes: :broken_heart:
- a non-related single-org entry or none is shown as result

*Expected behaviour:* :heart: :smile:
- org entries with tags :buy: AND :hobby: should be listed (if you do that with OR, this works neither)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML\
2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by duianto** [comment]
This gist sounds like it might be helpful:
Complete multiple org-mode tags with helm - Google Chrome
https://gist.github.com/alphapapa/a3433c54a631b693ba9d

**Comment by lebensterben** [comment]
closing due to no response.

please retry on latest develop branch with update to date packages.

comment if this is still an issue.
