### ISSUE TITLE
Blank modeline with emacs 27

### ISSUE THREAD

**Issue by coventry** [syl20bnr/spacemacs#13800]
#### Description :octocat:

modeline blank, with emacs 27     

#### Reproduction guide :beetle:
- Start Emacs
- open file
- observe modeline is a blank grey bar

*Observed behaviour:* :eyes: :broken_heart:

modeline is a blank grey bar. It's not clear how to add an image in this issue. I'll add one in a comment below.

*Expected behaviour:* :heart: :smile:

modeline contains useful information

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. bb0a11834)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(csv elixir ruby sql yaml nginx latex bibtex lua react php html
     (javascript :variables node-add-modules-path t)
     rust lsp
     (go :variables go-tab-width 2 go-backend 'lsp)
     docker markdown python treemacs ivy auto-completion better-defaults emacs-lisp git org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     syntax-checking
     (typescript :variables typescript-fmt-on-save t typescript-fmt-tool 'prettier typescript-indent-level 2))
```
- System configuration features: JPEG PNG IMAGEMAGICK NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB LUCID X11 XDBE XIM MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by coventry** [comment]
Problematic behavior: ![Screenshot from 2020-07-27 14-17-31](https://user-images.githubusercontent.com/70152/88576782-f4e7a800-d013-11ea-9535-0ebc49d633fc.png)

Expected behavior (emacs 26):

![Screenshot from 2020-07-27 14-19-30](https://user-images.githubusercontent.com/70152/88576928-3710e980-d014-11ea-9499-3ba9c0623b51.png)

**Comment by coventry** [comment]
I built emacs 27 with these instructions:

```bash
   git clone --depth=1 --single-branch --branch emacs-27 https://github.com/emacs-mirror/emacs.git
   cd emacs
   sudo apt install -y autoconf make gcc texinfo libgtk-3-dev libxpm-dev libjpeg-dev libgif-dev libtiff5-dev libgnutls28-dev libncurses5-dev libjansson-dev libharfbuzz-dev libharfbuzz-bin
   sudo apt-get install libxaw7-dev libmagick++-dev # These weren't caught by the above install command
   ./configure --with-json --with-modules --with-harfbuzz --with-compress-install --with-threads --with-included-regex --with-x-toolkit=lucid --with-zlib --without-sound --without-xpm --with-jpeg --without-tiff --without-gif --with-png --without-rsvg --with-imagemagick --without-toolkit-scroll-bars --without-gpm --without-dbus --without-makeinfo --without-pop --without-mailutils --without-gsettings --without-pop
   make -j 4
```
This was at emacs commit `73a2f5104331264656ac830c848912af9389a04b`.

**Comment by coventry** [comment]
Incidentally, if I move my `~/.spacemacs` out of the way, and start `emacs`, I still get the blank modeline. But with `emacs -q`, the modeline is as expected.

**Comment by jasperpilgrim** [comment]
Anything looking suspicious in the `*Messages*` buffer? Strange that Spacemacs and vanilla Emacs have the same issue but emacs -q does not.

**Comment by coventry** [comment]
As I understand it, `emacs -q` *is* vanilla emacs.

**Comment by coventry** [comment]
But you're right, there is something interesting in the `*Messages*` buffer. 

```
Loading /home/ubuntu/.spacemacs...done
Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid image type ‘xpm’")
Spacemacs is ready.
[yas] Prepared just-in-time loading of snippets successfully.
Loading /home/ubuntu/.emacs.d/private/disable-mouse.el (source)...done
Loading /home/ubuntu/.emacs.d/.cache/recentf...done
Skipping check for new version (reason: dotfile)
Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid image type ‘xpm’") [9 times]
Package cl is deprecated
Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid image type ‘xpm’") [24 times]
```

**Comment by coventry** [comment]
Traceback from `M-x eval-expression (spaceline-ml-main) RET`:

```elisp
Debugger entered--Lisp error: (error "Invalid image type ‘xpm’")
  signal(error ("Invalid image type ‘xpm’"))
  error("Invalid image type `%s'" xpm)
  image-type("/* XPM */ static char * wave_left[] = { \"11 25 3 1..." xpm t)
  create-image("/* XPM */ static char * wave_left[] = { \"11 25 3 1..." xpm t :ascent center :face mode-line)
  apply(create-image "/* XPM */ static char * wave_left[] = { \"11 25 3 1..." xpm t :ascent center :face mode-line nil)
  #f(compiled-function (face1 face2 &optional height) #<bytecode 0x15890d1c8b21>)(spacemacs-emacs-face mode-line)
  apply(#f(compiled-function (face1 face2 &optional height) #<bytecode 0x15890d1c8b21>) (spacemacs-emacs-face mode-line))
  (puthash key (apply #f(compiled-function (face1 face2 &optional height) #<bytecode 0x15890d1c8b21>) args) cache)
  (if val val (puthash key (apply #f(compiled-function (face1 face2 &optional height) #<bytecode 0x15890d1c8b21>) args) cache))
  (let* ((cache (pl/create-or-get-cache)) (key (cons 'G540 args)) (val (gethash key cache))) (if val val (puthash key (apply #f(compiled-function (face1 face2 &optional height) #<bytecode 0x15890d1c8b21>) args) cache)))
  powerline-wave-left(spacemacs-emacs-face mode-line)
  spaceline-ml-main()
  eval((spaceline-ml-main) t)
  eval-expression((spaceline-ml-main) nil nil 127)
  funcall-interactively(eval-expression (spaceline-ml-main) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by coventry** [comment]
If I set `dotspacemacs-mode-line-theme 'doom` to `'doom` in `dotspacemacs/init`, I do get a mode line, though it's pretty ugly.

**Comment by coventry** [comment]
`'vanilla` also works, and is a bit nicer.

**Comment by jasperpilgrim** [comment]
`emacs -q` actually still loads `site-start.el`. I believe `emacs -Q `loads it without init files + without `site-start.el`. I was trying to distinguish between Spacemacs and Emacs when I called it (Emacs _with_ init files) vanilla. Sorry for the confusion.

I am making an educated guess, but according to `*Messages*,` xpm (X PixMap) support was not compiled into your Emacs. And it would also seem spaceline uses xpm. I see that you did install `libxpm-dev`. Not sure what else is required.

To be sure, evaluate this line: `(image-type-available-p 'xpm)`. You can do this in a few ways, but a quick way is to do `M-x` and then `M-:`. It should return either `t` if support is baked in or `nil` otherwise. I reckon you know what you're doing, so evaluate it however you wish.

**Comment by coventry** [comment]
Thanks, @jasperpilgrim! Yep, `configure`'ing and `make`'ing with `--with-xpm` fixed the problem.
