### ISSUE TITLE
missing debugging keybindings for emacs-lisp layer

### ISSUE THREAD

**Issue by wminshew** [syl20bnr/spacemacs#13817]
https://develop.spacemacs.org/layers/+lang/emacs-lisp/README.html#debugging

in the readme, key bindings are currently missing & marked as TODO. If someone can tell me where to find the key bindings I'd be happy to port them over myself in a PR

**Comment by duianto** [comment]
These seem to be the Emacs key bindings those modes:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Edebug-Execution-Modes.html
https://www.gnu.org/software/emacs/manual/html_node/elisp/Debugger-Commands.html

These might be helpful for choosing Evil (vim) key bindings:
https://github.com/emacs-evil/evil-collection/blob/master/modes/edebug/evil-collection-edebug.el
https://github.com/emacs-evil/evil-collection/blob/master/modes/debug/evil-collection-debug.el

**Comment by wminshew** [comment]
ok updated -- thank you for the help!!

**Comment by wminshew** [comment]
I tested all of these locally so.. hopefully no more bugs here
