### ISSUE TITLE
Variable evil-escape-key-sequence not defined

### ISSUE THREAD

**Issue by pspencil** [syl20bnr/spacemacs#13814]
#### Description :octocat:
When starting up, got error "Cannot enable hl-todo-mode without font-lock". Then I cannot use "fd" to exit insert mode (and other modes like ivy-minibuffer-mode).

#### Reproduction guide :beetle:
- Start Emacs (develop branch)
- Load .spacemacs to be provided later.

*Observed behaviour:* :eyes: :broken_heart:
Got error in status bar ("Cannot enable hl-todo-mode without font-lock") also in message buffer

Also, I observed `evil-escape-key-sequence` is not defined at all (and my usual escape key "fd" doesn't work). My *hypothesis* is that the above error causes the loading to stop and didn't completing loading the evil-escape package. But I don't see a red status bar so there might be some other reason.

*Expected behaviour:* :heart: :smile:
no errors.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 04b80d610)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(python csv ivy
        (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'cycle)
        (c-c++ :variables c-c++-enable-clang-format-on-save t c-c++-lsp-enable-semantic-highlight 'rainbow)
        better-defaults emacs-lisp git lsp markdown org
        (shell :variables shell-default-height 30 shell-default-shell 'ansi-term shell-enable-smart-eshell t shell-protect-eshell-prompt t shell-default-position "bottom")
        syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by pspencil** [comment]
The .spacemacs that I used can be found [here](https://github.com/pspencil/dotfiles/blob/master/spacemacs).

It was working fine. I did a couple of changes since:

1. switched to dev branch from master branch.
2. ran `SPC f e D` and integrated a couple of changes from the template.

**Comment by pspencil** [comment]
A couple more observations:

After emacs loaded, I ran `SPC f e R` and a "Warnings" buffer pop up with this output

```
Error (use-package): hl-todo/:init: Cannot enable hl-todo-mode without font-lock
```

There might be a possibility that this warning is not the true cause of the problem.

**Comment by pspencil** [comment]
EDIT: the `hl-todo-mode` error is definitely the cause. The error went away after I excluded the package `hl-todo`

**Comment by NicholasKirchner** [comment]
Related: https://github.com/syl20bnr/spacemacs/issues/13813

**Comment by athos** [comment]
Same here.
Once I unistalled the latest version of `hl-todo` and pinned it to the stable one, Spacemacs managed to start up without an error:

```elisp
(defun dotspacemacs/user-init ()
  ...
  (add-to-list 'configuration-layer-elpa-archives
               '("melpa-stable" . "https://stable.melpa.org/packages/"))
  (add-to-list 'package-pinned-packages '(hl-todo . "melpa-stable") t)
  ... )
```

**Comment by duianto** [comment]
The hl-todo issue seems to have been caused and solved upstream:
Cannot enable hl-todo-mode without font-lock
https://github.com/tarsius/hl-todo/issues/56

---

Pressing: `fd` quickly exits from insert to normal state for me with the latest packages in both PopOS and Windows.

<details><summary>
PopOS 20.04, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d65c09165)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors org treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS

</pre>
</details>

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 76301564c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm lsp multiple-cursors
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>
