### ISSUE TITLE
Error (use-package): exec-path-from-shell/:init: Wrong type argument: number-or-marker-p, "Unknown signal 35"

### ISSUE THREAD

**Issue by alexander-yun** [syl20bnr/spacemacs#13819]
Error (use-package): exec-path-from-shell/:init: Wrong type argument: number-or-marker-p, "Unknown signal 35"

#### Reproduction guide :beetle:
- Start Emacs
start spacemacs in android in termux

*Observed behaviour:* :eyes: :broken_heart:
it seems all work but this warining annoying

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG GLIB NOTIFY GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XI\
M THREADS CANNOT_DUMP LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
If you haven't tried the Spacemacs `develop` branch already.

The `develop` branch is the recommended branch until the next version is released (I have no insight into when that is).

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```
