### ISSUE TITLE
Empty .cache created in ~/.config/emacs even though all cache-related paths were changed in dotspacemacs/init. 

### ISSUE THREAD

**Issue by nbfalcon** [syl20bnr/spacemacs#13820]
#### Description :octocat:
If the spacemacs is configured to store emacs "cache-related" date in some other
place as below, spacemacs still creates a .cache directory in ~/.config/emacs.
This is probably caused by $SPACEMACS/core/core-load-paths.el:71:
```elisp
(unless (file-exists-p spacemacs-cache-directory)
    (make-directory spacemacs-cache-directory))
```
The problem is that this is executed in some require clause, before
dotspacemacs/init is called and has a chance to change
spacemacs-cache-directory. I propose that those two lines be removed (as many
plugins create missing directories themselves) or moved to some place evaluated
after (spacemacs/init).

#### Reproduction guide :beetle:
- Start Emacs
- Change spacemacs-cache-directory and various other directories in
  dotspacemacs/init, and various plugin-specified variables to point to a custom
  location. (from my dotspacemacs/init):
```elisp
(setq
 spacemacs-cache-directory
 (concat
  (file-name-as-directory (or (getenv "XDG_DATA_HOME")
                              (concat user-home-directory ".local/share")))
  "spacemacs/cache/")

 spacemacs-buffer--cache-file
 (concat spacemacs-cache-directory "spacemacs/buffer.el")

 configuration-layer--rollback-root-directory
 (concat spacemacs-cache-directory "spacemacs/rollback/")

 configuration-layer--last-dotspacemacs-configuration-layers-file
 (concat spacemacs-cache-directory "spacemacs/last-configuration-layers.el")

 spacemacs-auto-save-directory
 (concat spacemacs-cache-directory "auto-save/")

 spacemacs--custom-file (concat spacemacs-cache-directory "custom.el")))
```
- calc-mode:
```elisp
(setq calc-settings-file (concat spacemacs-cache-directory "calc.el"))
```
- lsp and dap are handled in layer configuration (below)

*Observed behaviour:* :eyes: :broken_heart:
An empty .cache was created in my ~/.config/emacs/, pointing to my otherwise
clean spacemacs checkout.

*Expected behaviour:* :heart: :smile:
No .cache should be created.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 04b80d610)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(
      (lsp 
           (concat spacemacs-cache-directory "lsp/sessions.el")
           (concat spacemacs-cache-directory "lsp/servers/"))
      (dap :variables dap-breakpoints-file
           (concat spacemacs-cache-directory "dap/breakpoints.el")))
```
- System configuration features: XPM JPEG TIFF GIF PNG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER

#### Backtrace :paw_prints:
Not applicable here, as there is no crash.

**Comment by duianto** [comment]
This sounds like it's a related or the same issue:
spacemacs-cache-directory is ignored in dotspacemacs/*-init #12127
