### ISSUE TITLE
Add information on the serenata lsp server (php)

### ISSUE THREAD

**Issue by dduenker** [syl20bnr/spacemacs#13839]
The [php layer documentation](https://develop.spacemacs.org/layers/+lang/php/README.html) currently has information on two lsp backends:
- Intelephense has paid features
- php-language-server which appears to be unmaintained.

The website of lsp-mode lists another backend: https://emacs-lsp.github.io/lsp-mode/page/lsp-serenata/
[Serenata](https://serenata.gitlab.io/) is currently maintained and published under AGPL3.

Please add information on how to use this as lsp backend with spacemacs.

**Comment by dbrw** [comment]
This information will surely help a lot.
