### ISSUE TITLE
Package cl is deprecated (Emacs 27.1 / spacemacs develop)

### ISSUE THREAD

**Issue by mjsteinbaugh** [syl20bnr/spacemacs#13836]
#### Description :octocat:

Now seeing a cl package deprecation warning.

#### Reproduction guide :beetle:
- Start Emacs (can reproduce either in terminal or GUI client)

*Observed behaviour:* :eyes: :broken_heart:
Package cl is deprecated

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ca2cdd0fc)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy better-defaults evil-commentary syntax-checking version-control csv docker git ipython-notebook osx emacs-lisp
     (ess :variables ess-ask-for-ess-directory nil ess-default-style 'DEFAULT ess-eval-visibly-p nil ess-fancy-comments nil ess-history-file nil ess-indent-level 4 ess-indent-with-fancy-comments nil ess-language "R" ess-nuke-trailing-whitespace-p t ess-roxy-str "#'" ess-use-flymake t inferior-R-args "--no-restore --no-save")
     html markdown org
     (python :variables python-test-runner 'pytest)
     (ruby :variables ruby-backend 'lsp ruby-test-runner 'rspec ruby-version-manager 'rbenv)
     rust
     (shell :variables shell-default-position 'right shell-default-width 80)
     vimscript yaml)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER

**Comment by mjsteinbaugh** [comment]
Potentially relevant:

- https://github.com/syl20bnr/spacemacs/issues/12989
- https://github.com/hlissner/doom-emacs/issues/3372
- https://github.com/kiwanami/emacs-epc/issues/35

**Comment by thanhvg** [comment]
The warning may be annoying but things will work just fine.

This is entirely from the third party packages that Spacemacs are using and there nothing we can do about it and it is up to the 
those package maintainers to update them. 

To  list packages needed to be updated:
``` 
$ cd ~/.emacs.d/elpa/27.1/develop
$ rg -F "(require 'cl)" -l
git-gutter-fringe+-20140729.1103/git-gutter-fringe+.el
fuzzy-20150730.337/fuzzy.el
popwin-20200122.1440/popwin.el
spinner-1.7.3/spinner.el
emmet-mode-20180613.341/emmet-mode.el
log4e-20200420.745/log4e.el
... 
```

**Comment by ilyagr** [comment]
There is a workaround that I got from https://github.com/kiwanami/emacs-epc/issues/35#issuecomment-773420321.

You can add `(setq byte-compile-warnings '(cl-functions))` to the end of `~/.emacs.d/early-init.el`. This file is part of Spacemacs, so this will make updating Spacemacs a little more fussy. You might want to create a git branch for this change, or it might be easier to just live with the warning on startup.

**Comment by mjsteinbaugh** [comment]
This is safe to close. Thanks @thanhvg for the excellent tip on how to identify packages that require an update.
