### ISSUE TITLE
Cannot enable hl-todo-mode without font-locker while stuck at 147/149

### ISSUE THREAD

**Issue by bettio** [syl20bnr/spacemacs#13830]
#### Description :octocat:
After I clean install on Ubuntu 20.04, spacemacs loading is stuck at 147/149, this happen during the first bootstrap and during all subsequent startups.
A `Cannot enable hl-todo-mode without font-locker` message is also reported at each subsequent startup.

This was the first time I was trying using emacs, so I'm a total beginner.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
A `Cannot enable hl-todo-mode without font-locker` message is reported, and progress bar is stuck at 147/149.

*Expected behaviour:* :heart: :smile:
Startup without any error.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by hersh-verthun** [comment]
I am facing the same issue. Please take a look at the screenshot attached.
![spacemacs - startup trouble](https://user-images.githubusercontent.com/22866232/89839574-b1e91100-db8b-11ea-820d-f9f8ffbe0ba5.png)

**Comment by domi-e** [comment]
I am facing the exact same problem, and the loading process stopped at 147/149.

**Comment by bettio** [comment]
I solved the problem by using development branch instead of master. It looks like master is quite behind.

**Comment by bsielski** [comment]
Same issue here. I'm using spacemacs for the first time today (I'm an Emacs user already). It works with develop branch or when you install minimum base distro (the second question).

**Comment by K-Software** [comment]
I had the same problem and I resolved it  with to use to the develop branch

**Comment by duianto** [comment]
This was an upstream issue that has been fixed:
Cannot enable hl-todo-mode without font-lock https://github.com/tarsius/hl-todo/issues/56
