### ISSUE TITLE
fd does not work in Ocaml layer when your caret is behind a keyword.

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [syl20bnr/spacemacs#13832]
#### Description :octocat:
fd does not work in Ocaml layer when your caret is behind a keyword.

#### Reproduction guide :beetle:
- Start Emacs
- Enable the Ocaml layer
- Open an empty file with extension '.ml' (such that the layer is active)
- Type in the Ocaml keyword 'let' followed by any amount of whitespace
- Type 'fd' to exit insert mode

Observed behavior: Typing in 'fd' directly after (with some whitespace) any Ocaml keyword (let, type, module,...) except 'struct', will move the cursor to the end of that word instead of leaving insert mode.

Expected behavior: Typing 'fd' should leave insert mode.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html racket ocaml python shell haskell themes-megapack helm auto-completion emacs-lisp git markdown spell-checking syntax-checking version-control latex)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
Pressing `fd` quickly changes from insert to normal state for me on the `develop` branch.

After typing `let` followed by none, or up to at least 5 spaces.

In this example `.ml` file:
https://caml.inria.fr/pub/old_caml_site/Examples/oc/basics/fib.ml

<details><summary>
PopOS 20.04, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 76301564c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((elfeed :variables elfeed-feeds
         '(("http://nullprogram.com/feed/" blog emacs)
           "http://www.50ply.com/atom.xml"
           ("http://nedroid.com/feed/" webcomic)))
 emacs-lisp git helm multiple-cursors ocaml version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

</pre>
</details>

The `develop` branch is the recommended branch until the next version is released (I have no insight into when that is).

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Comment by LasseBlaauwbroek** [comment]
Confirmed. I was not aware that `develop` was the recommended branch. The Ocaml layer seems much improved there :+1: Thanks for the help! Closing.
