### ISSUE TITLE
Error on exiting iedit-mode after hitting "ESC"

### ISSUE THREAD

**Issue by mirubiri** [syl20bnr/spacemacs#13849]
#### Description :octocat:

`ESC` to exit iedit mode can't execute iedit-cleanup function 

#### Reproduction guide :beetle:
- Start Emacs
- SPC s e over a word
- `ESC` to exit edit mode
- iedit-done: Symbol’s function definition is void: iedit-cleanup

*Observed behaviour:* :eyes: :broken_heart:

iedit mode cannot be cleaned, cursor stays red and `iedit-cleanup` error keeps poping up on messages buffer

*Expected behaviour:* :heart: :smile:

After hitting ESC-ESC iedit mode is cleaned and spacemacs returns to normal mode

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 76301564c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql
 (deft :variables deft-auto-save-interval 10.0)
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 emacs-lisp emoji evil-snipe git html helm
 (javascript :variables javascript-backend 'lsp js2-basic-offset 2 js-indent-level 2)
 (json :variables js-indent-level 2)
 (markdown :variables markdown-live-preview-engine 'vmd)
 (org :variables org-want-todo-bindings t)
 (ruby :variables ruby-version-manager nil ruby-test-runner 'rspec ruby-enable-enh-ruby-mode t)
 syntax-checking
 (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left version-control-global-margin t)
 yaml)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP

**Comment by thanhvg** [comment]
This is because `evil-iedit-state` has not been updated with recent change in `iedit`.  Both `evil-idedit-sate ` and `Spacemacs` share the same owner. There is a bunch of PRs on `evil-idedit-sate` which is just one liner fix but I am very pessimistic that @syl20bnr would care anymore. 

In the mean time you can try my hack. Add these lines to your `dotspacemacs/user-config`

``` elisp
  (with-eval-after-load 'evil-iedit-state
    (fset 'iedit-cleanup 'iedit-lib-cleanup))
````

**Comment by mirubiri** [comment]
@thanhvg thx!

**Comment by dalanicolai** [comment]
This bug has also been reported [here](https://github.com/syl20bnr/evil-iedit-state/issues/27)

**Comment by mirubiri** [comment]
Thanks @dalanicolai im closing this one in favor of the one you mention

**Comment by duianto** [comment]
This issue has been fixed upstream:
iedit-cleanup -> iedit-lib-cleanup? by vtomilin https://github.com/syl20bnr/evil-iedit-state/pull/28

Update your packages.
