### ISSUE TITLE
Multiple toplevel javascript menus consuming too much space

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#13842]
#### Description :octocat:
When editing javascript files there are multiple toplevel menus dedicated to javascript. Not only are they making items harder to find but together they are consuming so much space from the menu bar that none of the global menu items (wifi, battery, clock, etc.) are accessible

#### Reproduction guide :beetle:
- Start Emacs
- open a javascript / jsx file

*Observed behaviour:* :eyes: :broken_heart:
There are 3 toplevel menus dedicated for JavaScript only
- IM-Javascript-IDE
- JavaScript
- JavaScript (yes, another one)
<img width="1258" alt="Screenshot 2020-08-14 at 12 54 54" src="https://user-images.githubusercontent.com/13787/90242917-2e028380-de2e-11ea-96d2-4f0b5c22063c.png">

- From the looks of it the contents of "IM-Javacript-IDE" is comparable to tags, which are already somewhat present in the Development menu.
- The first JavaScript seems js2-mode related.
- The second JavaScript says something about "Select New Mozilla Context" but all items are disabled.

*Expected behaviour:* :heart: :smile:
At most one JavaScript menu under which the other entries are neatly collected.

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4ff6bf424)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs ansible
            (auto-completion :variables auto-completion-enable-help-tooltip t)
            colors csv dash docker git
            (go :variables go-backend 'lsp go-format-before-save t go-use-golangci-lint t gofmt-command "goimports")
            graphviz helpful html imenu-list
            (javascript :variables javascript-backend 'lsp)
            lsp markdown nginx
            (org :variables org-enable-reveal-js-support t org-enable-sticky-header t org-enable-verb-support t)
            (osx :variables osx-command-as 'hyper osx-right-command-as 'super osx-option-as 'none osx-right-option-as 'meta)
            plantuml puppet python react restclient semantic shell-scripts syntax-checking
            (typescript :variables typescript-backend 'lsp)
            version-control yaml)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP

**Comment by duianto** [comment]
Confirmed.

The last one with "Select New Mozilla Context..." seems to come with Emacs by default.

It's the only JavaScript menu when a `.js` file is opened after starting: `runemacs --quick`

The other two comes from https://github.com/mooz/js2-mode

`(define-derived-mode js2-mode js-mode "Javascript-IDE"`
source: https://github.com/mooz/js2-mode/blob/40aab27581279d0fdbfeb9afeb85f39d401a927f/js2-mode.el#L11783

`  (imenu-add-to-menubar (concat "IM-" mode-name))`
source: https://github.com/mooz/js2-mode/blob/40aab27581279d0fdbfeb9afeb85f39d401a927f/js2-mode.el#L11813

The three javascript menus are shown in this issue:
empty menus · Issue https://github.com/mooz/js2-mode/issues/499

But no one seems to be surprised that there are three.

`js2-mode` should add it's menu items to the default javascript menu.

>they are consuming so much space from the menu bar that none of the global menu items (wifi, battery, clock, etc.) are accessible

This should probably be reported to Emacs and/or Apple.

An overflow menu (arrow) is usually added when showing all of them would push out everything to the right.

<details><summary>
Windows 1903, System Info (click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 346be150f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git
            (go :variables go-backend 'lsp go-format-before-save t go-use-golangci-lint t godoc-at-point-function 'godoc-gogetdoc)
            helm
            (javascript :variables javascript-backend 'lsp)
            lsp multiple-cursors org
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>
