### ISSUE TITLE
Can't make company-tabnine working.

### ISSUE THREAD

**Issue by MrMic** [syl20bnr/spacemacs#13846]
Hi,

Is there any easy way to make TabNine working with Spacemacs?

It works fine and easily with Vim, VS Code ...

Thanks for the reply and help.
Rgds,

M.C

**Comment by tshu-w** [comment]
spacemacs uses its own mechanism to set company-backend, so `(add-to-list 'company-backends #'company-tabnine)` should not work. Maybe you can refer to this https://github.com/syl20bnr/spacemacs/pull/11985.

**Comment by MrMic** [comment]
Yes, I have noticed that.
I just want a fix to this, if there is any.
No need to give link(s) that bring me no answer to this issue.
