### ISSUE TITLE
lsp-clients module is gone 

### ISSUE THREAD

**Issue by andreyk0** [syl20bnr/spacemacs#13857]
Looks like it was recently [refactored](https://github.com/emacs-lsp/lsp-mode/pull/2084).
`develop` branch errors on startup after a package update.

Local modification that simply replaces `(require 'lsp-clients)` with `(require 'lsp)` seems to work.

**Comment by dalu98** [comment]
`lsp.el` is also deprecated.

We should use `(require 'lsp-mode)` instead.

**Comment by Invertisment** [comment]
I have some kind of weird errors too.
With newest version of develop branch (`346be15`) `lsp` doesn't create `SPC-m` major mode actions for TS layer (I only tried TS) and `lsp-ui` doesn't pick up config from `auto-complete`.
As I use evil mode for editing I can't access `c-l` key and those commands were included into `SPC-m` before.

I've reset the develop branch several times to try out different TS servers and encountered this issue.
And it seems that the first time it loads it doesn't load the config from `(auto-complete :variables ...)` config (trying out to load `ts-ls` for TS).

After deleting `.emacs.d/.cache/lsp/` and restarting emacs it says that it deletes `tern` and then upon loading a source file it starts picking up the auto-complete config but major mode keys are still not bound.

Will your fix also fix my issue?
Will this require a real fix or simply a patch that won't work in my case?
I use the config that has very little changes from the default.

Emacs: `26.3`
Spacemacs develop branch `346be15`
TS server: `ts-ls`; I also tried `jsts-ls` and it works but I have different reasons to switch them that are out of this comment.

**Comment by stkain** [comment]
Hi, 

I pasted the require-statements that were once in lsp-clients.el (from github lsp-mode commit history)
into packages.el

```
      (require 'lsp-mode)
      (require 'dash)
      (require 'dash-functional)
      (require 'rx)
      (require 'cl-lib)
```

It works normal for me now. Also all the major mode short-cuts are back again.

Bye

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
[lsp] Remove mention of `lsp-clients` #13860

Feel free to close this issue if it solved your issue.

**Comment by stkain** [comment]
Hi,

lsp.el is there only for backward compatibility.
it is recommended in that file to (require 'lsp-mode)
So I guess, sooner or later lsp.el will be removed, too.

please have a look at my PR that includes the requires from the now missing lsp-clients.el.

(fosskers and I did not know each other requests)

Bye

**Comment by stkain** [comment]
Ah, I see, I am lagging a little behind... I can confirm, that the latest develop fixes the issue.
Bye

**Comment by andreyk0** [comment]
Thanks everybody! Just checked, my layer works but `git grep` shows `lsp-clients` in `layers/+lang/lua/funcs.el` as well.
Should the `require` be removed there or changed into something else?

**Comment by fosskers** [comment]
Looks like I missed that one, forgive me. Hard to say what should be done with it, since I don't use Lua :thinking:

**Comment by duianto** [comment]
@andreyk0 Thanks for checking.
A PR has been opened to remove the require lsp-clients line from the lua layer.
[lua] Remove require lsp-clients #13875

**Comment by andreyk0** [comment]
Thanks! Closing this.
