### ISSUE TITLE
After upgrading to 27.1, new installations consistently fail with "error in process sentinel: End of file during parsing"

### ISSUE THREAD

**Issue by phrxmd** [syl20bnr/spacemacs#13859]
#### Description :octocat:
After upgrading to Emacs 27.1 (on OpenSUSE Tumbleweed), new installations of Spacemacs consistently fail with "error in process sentinel: End of file during parsing".

This happens regardless of whether I clone the `master` or `develop` branch, or whether I use HTTP (with `emacs --insecure`) or HTTPS for download.

#### Reproduction guide :beetle:
- Delete `./emacs.d`
- Delete `.spacemacs`
- Download spacemacs using `git clone --branch develop https://github.com/syl20bnr/spacemacs ~/.emacs.d`
- Start Emacs 27.1.

*Observed behaviour:* :eyes: :broken_heart:
After the questions about editing styles and distributions, Spacemacs begins downloading packages. Dozens of package downloads fail with error messages:
```
error in process sentinel: async-handle-result: End of file during parsing
error in process sentinel: End of file during parsing
```
See https://pastebin.com/AzPJ0FZr and https://pastebin.com/VQzD6zgY for examples of `messages` during two separate attempts. 

Different packages are concerned every time. For example on this installation, the errors concerned the following packages (resulting in an almost unusable Spacemacs): 
```
auto-compile / packed
clean-aident-mode
dumb-jump
editorconfig
emr
paredit
iedit
evil-args
smartparens
evil-escape
evil-indent-plus
evil-matchit
evil-mc
evil-tutor
evil-visual-mark-mode
eyebrowse
flycheck-elsa
helm-ag
helm-make
helm-purpose
window-purpose
helm-xref
highlight-parentheses
link-hint
lorem-ipsum
move-text
org-superstar
spinner
popwin
restart-emacs
powerline
memorize
string-inflection
symon
pfuture
ht
treemacs-persp
vi-tilde-fringe
writeroom-mode
ws-butler
```

You end up with a Spacemacs installation that is only partially usable.

*Expected behaviour:* :heart: :smile:
Clean, successful installation.

#### System Info :computer:
- OS: gnu/linux (OpenSUSE Tumbleweed)
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 346be150f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by phrxmd** [comment]
This is related to MELPA being down, Emacs 27.1 on OpenSUSE TW seems to handle connection error messages as Lisp code and breaks.

In the meantime, a workaround is to use a different mirror, e.g. by putting this in your `user-init` in `~/.spacemacs`:

```
(defun dotspacemacs/user-init ()
  "Initialization for user code:
This function is called immediately after `dotspacemacs/init', before layer
configuration.
It is mostly for variables that should be set before packages are loaded.
If you are unsure, try setting them in `dotspacemacs/user-config' first."

  ;; Hack for using a different set of repositories when ELPA is down
  ;;(require 'package)
  (setq package-archives
        '(("melpa" . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/melpa/")
          ("org"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/org/")
          ("gnu"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/gnu/")))
  (setq package-check-signature nil)
  (package-initialize)
)
```
The `(package-initialize)` line is important, otherwise Spacemacs will override the package mirror list with its own.

**Comment by roganjoshua** [comment]
I am still getting this right at the very end, emacs then freezes :(
