### ISSUE TITLE
Python not recognized on Linux Mint 20

### ISSUE THREAD

**Issue by dustiestgolf** [syl20bnr/spacemacs#13853]
#### Description :octocat:
Every time I startup spacemacs or run `SPC f e R` I get this warning

`Error (use-package): python/:init: Invalid version syntax: ‘Please install the python package.’ (must start with a number)`

When I try starting livepy mode I get the error `/bin/bash: python: command not found`.

I think it may be particularly a Linux Mint issue. This  [twitter thread](https://twitter.com/Foone/status/1288158263758868481?s=20) seems to deal with same problem since if I have anaconda deactivated I also cannot run the commands `pip` or `python`. With anaconda activated they work just fine. 

The paths to conda and python in .spacemacs.env both match the results of `which` when run in a terminal with conda active. 

I think a solution would be in getting my spacemacs install to connect to anaconda from the outset. I tried installing the anaconda backend up this did not fix the issue. 

How would I go about getting spacemacs to hook into the base anaconda environment from the get-go so that I can avoid this issue? 

#### Reproduction guide :beetle:
- turn on python layer
- Start Emacs
- error appears

*Observed behaviour:* :eyes: :broken_heart:
I add python to my list of layers in .spacemacs and then when restart spacemacs or `SPC f e R` I get this error. 

*Expected behaviour:* :heart: :smile:
No error. Python works. Conda environments are accessible.

#### System Info :computer:
- OS: gnu/linux (linux mint)
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 76301564c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((python :variables python-backend 'anaconda)
 auto-completion emacs-lisp git helm markdown multiple-cursors
 (org :variables fill-column 72)
 treemacs pandoc)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```

**Comment by synic** [comment]
I dunno if this will work on mint:

```
$ sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
```

You would change the `/usr/bin/python3` to your python path (it might just be that).

**Comment by dustiestgolf** [comment]
Yes that is the correct path for my installation of LM20. This is a good suggestion as it does get rid of the error. 

My only concern is that I think they removed that symlink to prevent issues with older python2 code pointing there and finding python3 accidentally. 

I think the source of my confusion was that I expected that spacemacs would startup in the base conda environment by default with the conda layer enabled. Or that there would be a setting for this. Do you know if/how I could go about fiddling with that setting? I think this would solve the issue without needed to add a symlink.
