### ISSUE TITLE
Spacemacs Develop on Emacs 27.1: fonts break

### ISSUE THREAD

**Issue by zilti** [syl20bnr/spacemacs#13856]
#### Description :octocat:
I am getting the following error on Spacemacs Develop:
```
Cannot find any of the specified fonts (Fira Code)! Font settings may
                                                       not be correct.
```
The font worked fine so far, until this morning I got the update to Emacs 27.1. I even removed the font and re-installed it as a system-wide font without any positive change.

#### Reproduction guide :beetle:
- Clone Spacemacs and check out develop branch
- Put "Fira Code" as default font in .spacemacs
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
It loads a completely unusable non-mono font that is unrelated to the settings, and gives me the warning posted above. It also fails to load the all-the-icons symbols correctly.

*Expected behaviour:* :heart: :smile:
It loads Fira Code as font just as it always did.

**Comment by phrxmd** [comment]
Duplicate of #13855. Same thing happens on a fresh checkout of Spacemacs develop or master.

**Comment by zilti** [comment]
Is it a duplicate though? The way Spacemacs reacts is completely different. In the other (I assume non-dev version) it breaks with an error, and on develop it "only" gives a warning.

**Comment by phrxmd** [comment]
For me (on Spacemacs master) if I start it with the command line, I get a warning and Spacemacs initialization does not finish. If I start it with "emacsclient", Spacemacs initialization finishes, but I get an error and the horrible bitmap font you describe.

**Comment by phrxmd** [comment]
Update: this seems to be an OpenSUSE packaging error, see https://bugzilla.opensuse.org/show_bug.cgi?id=1175372

As recommended in the link there and on Reddit, until an updated package lands you can work around it by editing `/usr/share/X11/app-defaults/Emacs`, finding the line that says `Emacs.FontBackend: xft,x`, and prefix it with `!!` so that it says `!!Emacs.FontBackend: xft,x`.

**Comment by zilti** [comment]
Oh, thanks! Well, can't say I am that surprised anymore by OpenSUSE shenanigans as of late...
