### ISSUE TITLE
[layers/+lang/haskell] Make Dante default backend

### ISSUE THREAD

**Issue by Martinsos** [syl20bnr/spacemacs#13867]
As discussed here https://github.com/syl20bnr/spacemacs/pull/13802#event-3672622287 with @smile13241324, company-ghci (current default) is not so relevant anymore while Dante works very well and out of the box in many cases, so we want to have Dante as default backend.
I plan to tackle this in the following week or so.

**Comment by smile13241324** [comment]
This has been done today, so this ticket can be closed.
