### ISSUE TITLE
[layers/+lang/haskell] Improve README (reorganize and polish)

### ISSUE THREAD

**Issue by Martinsos** [syl20bnr/spacemacs#13869]
As discussed here https://github.com/syl20bnr/spacemacs/pull/13802#event-3672622287 with @smile13241324, there are some ways we could improve README to make it easier to start with Haskell layer.

Ideally, we would handle this after tackling issue https://github.com/syl20bnr/spacemacs/issues/13868, to make sure those changes are well documented.

Short summary of what we should do:
 - "install" section which just shows how the layer is declared.
 - "Configuration" section after "install" section of which the first choice is "Choosing a backend" which defines a primary backend which should be "dante" and alternative backends with additional setup procedures. It should give easy to understand information when to choose which. A good example would be the "groovy" layer. If there are configurations which are independent of the chosen backend it should follow on the same level as the "Choosing a backend" headline. For LSP if there are multiple servers to choose from the differences should be described below the "LSP" headline which is below the "Choosing a backend" headline.

I plan to tackle this in the following week or so.

**Comment by Martinsos** [comment]
Note for myself: If not yet in README, add information/FAQ on how to fix Dante misbehaving regarding tests, if that is happening.

**Comment by smile13241324** [comment]
This has been merged by now, I am putting this ticket into done state.
