### ISSUE TITLE
spacemacs show "No such file or directory, lsp-clients"

### ISSUE THREAD

**Issue by wutianjun5858** [syl20bnr/spacemacs#13862]
spacemacs commit-id: 346be150f
branch: develop
issue: install success, but spacemacs show  "No such file or directory, lsp-clients". I used ccls

**Comment by duianto** [comment]
Pull the latest develop branch.

This PR has been merged:
[lsp] Remove mention of `lsp-clients` #13860

**Comment by wutianjun5858** [comment]
[lsp] Remove mention of lsp-clients  is ok
