### ISSUE TITLE
[layers/+lang/haskell] Remove Intero and company-ghci backends

### ISSUE THREAD

**Issue by Martinsos** [syl20bnr/spacemacs#13868]
As discussed here https://github.com/syl20bnr/spacemacs/pull/13802#event-3672622287 with @smile13241324, company-ghci is not competitive with other backends any more, while intero is not maintained any more, so both of them should be removed.
This should be done after issue https://github.com/syl20bnr/spacemacs/issues/13867 has been resolved, because company-ghci is currently default backend so we want to first switch that to Dante.
I plan to tackle this in the following week or so.

**Comment by smile13241324** [comment]
This has been merged today so this ticket is done.
