### ISSUE TITLE
`emr@emacs-lisp` installation failing, causing issues on startup

### ISSUE THREAD

**Issue by OmanF** [syl20bnr/spacemacs#13864]
#### Description :octocat:
On starting Spacemacs, `emr@emacs-lisp` is repeatedly trying to install itself, and failing, giving a `Warning` buffer stating: `ERROR (use-package): Cannot load emr`.

#### Reproduction guide :beetle:
- Start Emacs
- (That's it. On Spacemacs splash-screen there will *always* be some packages will try to install, among them `emr@emacs-lisp`. It will fail to install!)

*Observed behaviour:* :eyes: :broken_heart:
(As stated above)

*Expected behaviour:* :heart: :smile:
All plugins install correctly, not getting any warnings

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 81d1c9f78)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults clojure emacs-lisp fsharp git helm lsp markdown multiple-cursors spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by phrxmd** [comment]
MELPA had some downtime recently, some packages might have failed to download correctly.

Have you tried a few checkout of Spacemacs? If that doesn't work, you could try an alternative mirror, e.g. by putting something like this in your `user-init` in `~.spacemacs`:
```
(defun dotspacemacs/user-init ()
  "Initialization for user code:
This function is called immediately after `dotspacemacs/init', before layer
configuration.
It is mostly for variables that should be set before packages are loaded.
If you are unsure, try setting them in `dotspacemacs/user-config' first."

  ;; Hack for using a different set of repositories when MELPA is down
  ;;(require 'package)
  (setq package-archives
        '(("melpa" . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/melpa/")
          ("org"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/org/")
          ("gnu"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/gnu/")))
  ;; (setq package-check-signature nil) ;; may not be necessary
  (package-initialize)
)
```

**Comment by comkieffer** [comment]
Has the same issue. Your snippet solved it for me. Thanks!

**Comment by OmanF** [comment]
Yes, thank you, the snippet-helped (although for me, had to uncomment the `(setq package-check-signature ni)` line.
Thanks!

**Comment by dschrempf** [comment]
I think the error is because the latest projectile fails to compile, see https://github.com/bbatsov/projectile/issues/1571. The issue is fixed upstream.

**Comment by dschrempf** [comment]
The issue is now fixed with the normal MELPA repository.
