### ISSUE TITLE
Cannot use stata in org-mode with spacemacs

### ISSUE THREAD

**Issue by jia-j-chen** [syl20bnr/spacemacs#13879]
#### Description :octocat:
Recently, I started using spacemacs and enjoy it very much. For a while, I was able to use Stata in org-mode in spacemacs through ESS. After a recent spacemacs update, I cannot use Stata in org-mode anymore because Stata is obsolete the latest release of ESS. When I try to edit the following code block,
#+begin_src stata :tangle yes
 webuse auto;
#+end_src
I cannot open the clock block and get an error message as follows

org-edit-src-code: No such language mode: stata-mode

I am using the develop branch of spacemacs 0.300 with emacs 27.0.50. And, I output my system information using

uname -a

with the following output

Linux 4.15.0-112-generic #113~16.04.1-Ubuntu x86_64 GNU/Linux

How do I use Stata in org-mode with spacemacs?

#### Reproduction guide :beetle:
- Start Emacs
- Open an org file 
- Use SPC-m ' to open a code block, such as
#+begin_src stata :tangle yes
 webuse auto;
#+end_src
- 
*Observed behaviour:* :eyes: :broken_heart:
I cannot open the code block and receive a message saying "org-edit-src-code: No such language mode: stata-mode"

*Expected behaviour:* :heart: :smile:
I expect to open the code block and edit the code block in org-mode.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 39df5e2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((helm :variables helm-candidate-number-limit 1000)
 emacs-lisp git
 (markdown :variables markdown-live-preview-engine 'vmd)
 bibtex html csv org ess
 (chinese :variables chinese-enable-fcitx t chinese-fcitx-use-dbus t pyim-default-scheme 'ziranma-shuangpin)
 latex auto-completion ranger version-control pdf
 better-defaults markdown
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 spell-checking python
 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
If stata is obsolete in ess I will not longer be supported in org, except that you have a package providing this support instead. Still I have just glanced over your ticket so my comment could be completely wrong.

I think someone working with ESS at least should check whether `stata` is still part of ESS and if it is not whether its support has moved into a new package.

If the support is gone I don't see a way to add this back except of making a PR upstream.

**Comment by jia-j-chen** [comment]
I temporarily solve this problem by downgrading ESS to an earlier version, and it works for now. I take steps as follows.

1. Remove the ess layer from dotspacemacs-configuration-layers of .spacemacs
2. Add the following into dotspacemacs-additional-packages of .spacemacs
`(ess
:location
(recipe :fetcher git
        :url "https://github.com/emacs-ess/ESS.git"
        :commit "14b9a3091916a1cb74dec7336e8461590dfc6a7d"
        :files ("lisp/*.el" "contrib/lisp/*.el" "doc/dir" "doc/*.texi" "etc")))`

[#7071 ](https://github.com/syl20bnr/spacemacs/issues/7071) and [#6575](https://github.com/syl20bnr/spacemacs/pull/6575)

**Comment by smile13241324** [comment]
So this is a dropped feature from ESS? Then I am afraid we cannot do much in Spacemacs, except if you have an alternative package to integrate.

**Comment by smile13241324** [comment]
Dropped feature from upstream, must be clarified in the ESS project.
