### ISSUE TITLE
More descriptive commit messages as contributing requirement

### ISSUE THREAD

**Issue by kepi** [syl20bnr/spacemacs#13871]
Would it be possible to change contributing guidelines to require more descriptive commit messages instead of "if necessary add one or more paragraphs"?

I belive that author of commit has all the context for the change and in many cases core contributors understand the change without context too. But for the other - we don't have the context and we might not understand the motivation to change. I think there is great value in detailed commit message, especially in such big project as spacemacs is. It can lower the confusion when digging through source to find the cuase of problems, help new contributors with orientation.

Only PR with commit messages containing reason to change and all needed context should be merged if this proposal is accepted.

I'm not sure how to propose such change so I chose the issue. I'm not sure about exact wording for guideliness and how strict it should be. At least little better then now would be great :)

Thanks for considering the proposal.

**Comment by jr0cket** [comment]
Including the layer namein the title of the commit would speed up reviewing and help the community provide feedback.
This is done for many commits, but not all.
E.g. [haskel] LSP key bindings for refactor

**Comment by smile13241324** [comment]
Jep adding the layer affected is a cool thing if the change can be narrowed to just one layer, if not it should still be omitted.
As to giving reasons for changes, this we would have to explain in more detail especially to which level of detail we expect changes to be explained / reasoned for.

I would suggest making a suggestion here for an improved commit message style block in CONTRIBUTING.org.
Right now it says:
```
*** Commit messages
Write commit messages according to adapted [[http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html][Tim Pope's guidelines]]:
- Use present tense and write in the imperative: "Fix bug", not "fixed bug" or
  "fixes bug".
- Start with a capitalized, short (72 characters or less) summary, followed by a
  blank line.
- If necessary, add one or more paragraphs with details, wrapped at 72
  characters.
- Separate paragraphs by blank lines.

This is a model commit message:

#+BEGIN_EXAMPLE
  Capitalized, short (72 chars or less) summary

  More detailed explanatory text, if necessary.  Wrap it to about 72
  characters or so.  In some contexts, the first line is treated as the
  subject of an email and the rest of the text as the body.  The blank
  line separating the summary from the body is critical (unless you omit
  the body entirely); tools like rebase can get confused if you run the
  two together.

  Write your commit message in the imperative: "Fix bug" and not "Fixed bug"
  or "Fixes bug."  This convention matches up with commit messages generated
  by commands like git merge and git revert.

  Further paragraphs come after blank lines.

  - Bullet points are okay, too

      - Typically a hyphen or asterisk is used for the bullet, followed by a
        single space, with blank lines in between, but conventions vary here

      - Use a hanging indent
#+END_EXAMPLE

[[https://github.com/magit/magit/][Git Commit]] and [[https://github.com/magit/magit/][Magit]] provide Emacs mode for Git commit messages, which helps you
to comply to these guidelines.
```
When there is a new form we can ask the other maintainers and syl20bnr for their approval.
