### ISSUE TITLE
auto-mode-alist gets ignored if you run $ emacs filename

### ISSUE THREAD

**Issue by Volker-Weissmann** [syl20bnr/spacemacs#13880]
#### Description :octocat:
auto-mode-alist only works if you open a file using M-x find-file, but not if you open a file using $ emacs filename

#### Reproduction guide :beetle:
Put 
(add-to-list 'auto-mode-alist '("\\.txt\\'" . python-mode))
into your user-config.
Run $ emacs test.txt

*Observed behaviour:* :eyes: :broken_heart:
Mode is "test"

*Expected behaviour:* :heart: :smile:
Mode should be "Python"

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(html rust typescript octave markdown javascript yaml csv python python emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by emacs18** [comment]
I don't consider this a bug.  The documentation for `dotspaceamcs/user-config` states that this is done at the very end.  There is no assurance that this will be called before command-line processing.  In fact the function is called after command-line arguments are processed, i.e., `auto-mode-alist` is set after the file is loaded.  Hence what you observe is as intended.  If you really want this to work as you want, you can use `dotspacemacs/user-init` instead.

**Comment by Volker-Weissmann** [comment]
This is not exactly the definition of ease of use and user-friendliness.

**Comment by emacs18** [comment]
If you can suggest a change in documentation or change in code, please submit a pull request.  I'm curious as to what kind of change in documentation could improve the situation without also adding complexity.
