### ISSUE TITLE
can‘t save a layout file

### ISSUE THREAD

**Issue by WingDust** [syl20bnr/spacemacs#13882]
#### Reproduction guide :beetle:
- Start Emacs
- `SPA l 0`
- `test`
- `SPA l S`
- Perspective name to save (default Default)
  - `test`
- Perspective name to save (default [>done<])<Default>:
  - `[>done<]`
- Save a subset of perspective (Default to a file : ~/.emacs.d/.cache/layouts/
  - `./`
- keep other perspective in the file ?
  - y
**Open input file : No such file directory , e:/spacemacs/emacs26-3/.emacs.d/.cache/layouts/**

*Expected behaviour:* :heart: :smile:
When i try save all layout it show
- `SPA l s`
  - `persp-mode error: you must provide nonempty filename to save perspectives`

spacemacs version : 0.300
emacs: 27.1
OS : Windows 10

**Comment by emacs18** [comment]
Did you type in the name of the file to save the perspective?
If so, what was it?
If I type "foo" in response to "Save a subset of perspective ..." prompt, then file named "foo" is created.
If you don't type in anything or "./", then you have not specified a file name.
