### ISSUE TITLE
Can't install debug layer

### ISSUE THREAD

**Issue by Diadlo** [syl20bnr/spacemacs#13909]
#### Description :octocat:
Can't install debug layer

#### Reproduction guide :beetle:
- Add `debug` layer
- Enter `SPC f e R` 
- Go to home page

*Observed behaviour:* :eyes: :broken_heart:
- After sync message about failed test is displayed
- On home page warning "Unknown layer debug detected in dotfile" is displayed

*Expected behaviour:* :heart: :smile:
No warnings and errors

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion
      (c-c++ :variables c-c++-enable-clang-support t)
      debug better-defaults emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by emacs18** [comment]
You are using master git branch which does not seem to have debug layer.
Only develop git branch seems to have the debug layer.
Thus the easiest solution for you seems to be just switch over to develop branch.

**Comment by Diadlo** [comment]
@emacs18 Good catch. But after installing the `develop` version neither the debug plugin nor many others didn't work properly. 

`SPC m` doesn't contain any debug related commands
![image](https://user-images.githubusercontent.com/6306608/92262368-ab785b80-eee3-11ea-8503-166f5ce2f489.png)

Autocompletion doesn't work too
![image](https://user-images.githubusercontent.com/6306608/92262461-d6fb4600-eee3-11ea-944e-2d4d0f2cd404.png)
![image](https://user-images.githubusercontent.com/6306608/92262507-eda19d00-eee3-11ea-8bb2-c6cfb3637553.png)

```elisp
   dotspacemacs-configuration-layers
   '(
     emacs-lisp
     helm
     ;;lsp
     ;;multiple-cursors
     auto-completion
     (c-c++ :variables
            c-c++-enable-clang-support t)
     debug
     better-defaults
     git
     markdown
     org
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     spell-checking
     syntax-checking
     version-control
     ;;treemacs
     )
```

**Comment by smile13241324** [comment]
@Diadlo master is horribly outdated, please switch to develop. Then check your dotfile config, many of the layers have changed especially the c-c++ layer so the config vars you are setting may not longer existing.

Also be aware that many of the more traditional emacs packages are non maintained anymore. The general recommendation is to use the lsp layer where ever possible which is certainly within the C++ layer. For debugging there is the dap layer which should in almost all cases be prefered to `realgud` given your LSP server supports it.

One possible config on develop using clang would be:
```elisp
     (c-c++ :variables
            c-c++-default-mode-for-headers 'c++-mode
            c-c++-backend 'lsp-clangd
            c-c++-lsp-enable-semantic-highlight 'rainbow
            c++-enable-organize-includes-on-save t
            c-c++-lsp-semantic-highlight-method 'overlay
            c-c++-enable-clang-format-on-save t
            c-c++-adopt-subprojects t
            c-c++-enable-auto-newline t)
```
For more details please refer to the respective layer README.

**Comment by Diadlo** [comment]
@smile13241324 As I said I have already installed the `develop` version. I have changed `c-c++` variables as you suggested, but autocompletion and syntax check still don't work. I have also tried ccls backend (used in vim before and works fine).

![image](https://user-images.githubusercontent.com/6306608/92298699-50328180-ef54-11ea-8b9b-62b0f5e1a193.png)

`M-x lsp-describe-session` shows an empty buffer

**Comment by smile13241324** [comment]
@Diadlo I have checked our LSP support for lsp-clang and lsp-ccls today and both work flawlessly in a small sample project of mine, so there is no general issue.

Lets make sure that your system is properly configured, first please add lsp and dap layer to your dotfile. This should normally be done by the layer itself but maybe it is not happening. I am mentioning this for the mode specific actions in your screenshot do not look like they have been loaded from LSP. If they would have it would look like below:
![Screenshot from 2020-09-05 23-30-42](https://user-images.githubusercontent.com/18098560/92313788-e061dc80-efcf-11ea-8a19-c09ab34ff215.png)

Then make sure that your c-c++ layer config looks exactly like this:
``` elisp
     (c-c++ :variables
            c-c++-default-mode-for-headers 'c++-mode
            c-c++-backend 'lsp-ccls
            c-c++-lsp-enable-semantic-highlight 'rainbow
            c++-enable-organize-includes-on-save t
            c-c++-enable-clang-format-on-save t
            c-c++-adopt-subprojects t)
```
Now check that `ccls` is on your path and can be found from emacs. Best invoke it directly from a terminal opened within emacs.
In addition please check the content of `*lsp-log*` it should contain lines like
```
Command "ccls" is present on the path.
Command "ccls" is present on the path.
Found the following clients for /home/smile13241324/c++SampleCMAKEProject/src/main.cpp: (server-id ccls, priority 0)
The following clients were selected based on priority: (server-id ccls, priority 0)
```
after having opened your main.c or main.cpp file.

Not sure if you are working in a project structure, if you don't consider switching to a CMAKE based project. The main reason for this is that many clang based tools, which are used by the LSP server implementations including `ccls`, may require access to your compiler settings which they normally read from a CMAKE compiler database. If they don't have they will normally use a standard set i.e. not the right standard version for example.

If this is still not working, or your lsp log buffer is still empty check your message buffer for any lisp error which could have stopped your loading process prematurely.

Ok that's all diagnostics I can think of now.

**Comment by Diadlo** [comment]
@smile13241324 Where I can found `*lsp-log*`? What it is? If it's a file, then where? If command, then `lsp-log-io-prev`, `-mode`, `-next` doesn't show anything. Even empty window.

**Comment by emacs18** [comment]
`*lst-log*` is a buffer with log messages from lsp.
If you don't see it, then you probably did not enable lsp, i.e., `lsp` elisp command was not called which is normall called by a hook.
Can you check what the value of `lsp-mode` variable is in your C++ buffer?
It should be `t`.  You can hit `C-h v` then `lsp-mode` to see the value.

**Comment by Diadlo** [comment]
Ok. Looks like the issue was in lack of project. Will do some research later. Thanks
