### ISSUE TITLE
Agda layer uses tabs for indentation

### ISSUE THREAD

**Issue by wenkokke** [syl20bnr/spacemacs#13900]
#### Description :octocat:
The +lang/agda layer uses tabs for indentation on the develop branch.
Unfortunately, tabs are a lexical error in Agda.

#### Reproduction guide :beetle:
- Start Emacs
- Start agda2-mode
- Indent an expression with TAB

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs inserts a tab character, as opposed to spaces.

*Expected behaviour:* :heart: :smile:
Spacemacs inserts spaces, using the TAB command provided by the `agda-mode` package.

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 346be150f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx helm auto-completion better-defaults spell-checking syntax-checking latex bibtex markdown html
     (typography :variables typography-enable-typographic-editing t)
     git version-control yaml docker agda haskell idris rust python ruby javascript emacs-lisp)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER LCMS2 GMP

**Comment by wenkokke** [comment]
For reference, agda2-mode [binds TAB to `eri-indent` by default](https://github.com/agda/agda/blob/f44aa0ec598c3d1a340b960ca62f7dc4b79f20ae/src/data/emacs-mode/agda2-mode.el#L239-L242).

**Comment by wenkokke** [comment]
And eri.el requires cl, which is deprecated. That may be the cause of this issue?

**Comment by smile13241324** [comment]
Strange, I have thought that Spacemacs replaces all tabs with spaces almost everywhere.
To fix this one would need to check which function is actually called by TAB in `agda-mode` and bind it to the proposed function then.

@wenkokke can you give me a hint, as I have absolutely no idea about agda, I have noticed the agda layer is using `agda-mode` however you are talking about `agda2-mode` is the mode targeted by the layer obsolete and we should rather load `agda2-mode`?

I will mark this down for working on this in the next view days.

**Comment by wenkokke** [comment]
Ah, that might've been a slip on my part. If it's called `agda-mode`, that's what you should load. The function that is bound to `TAB` is `eri-indent`, which is defined within `eri.el`: https://github.com/agda/agda/blob/master/src/data/emacs-mode/eri.el

**Comment by smile13241324** [comment]
Looks like I don't find the time to work on this, I will put the help wanted label and let someone with agda knowledge fix it.

**Comment by wenkokke** [comment]
I think this was caused by Spacemacs respecting .editorconfig, and my .editorconfig requesting tabs (for some reason).
