### ISSUE TITLE
org-clock in modeline not shown for long headlines

### ISSUE THREAD

**Issue by fawick** [syl20bnr/spacemacs#13905]
#### Description :octocat:
The org-clock value and description in modeline not shown for long headlines.

#### Reproduction guide :beetle:
- Start Emacs
- Start org-mode
- Clock-in a heading with longish description
- Reduce window width 
- Enable org-clock in Modeline (SPC t m c)

*Observed behaviour:* :eyes: :broken_heart:
If heading length is larger than modeline width allows the clock disappears.

*Expected behaviour:* :heart: :smile:
Show at least the [h:mm] value and the beginning of the text with an ellipsis (...)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a0728abf1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
```

**Comment by smile13241324** [comment]
Looks like internal behaviour of the spaceline package which has been moved into its own repo some time ago. We don't define whether elements should be hidden or shrink to fit during scaling in Spacemacs.

Please open an issue upstream `https://github.com/TheBB/spaceline`.

**Comment by fawick** [comment]
Thanks for the feedback, @smile13241324. I browsed through the spaceline issues prior to opening a new found. https://github.com/TheBB/spaceline/issues/217 sounds like it could be related.

**Comment by smile13241324** [comment]
Sure, just keep it open.

**Comment by fawick** [comment]
For the record, this my hacky current workaround:

```elisp
(setq spaceline-org-clock-p t)
(setq spaceline-org-clock-format-function (lambda ()
  (truncate-string-to-width (org-clock-get-clock-string) (- (window-total-width) 64) 0 nil t)))
```

I have this in `dotspacemacs/user-config()` in `~/.spacemacs`.

**Comment by smile13241324** [comment]
@fawick cool, I wasn't aware we could control that from lisp :thinking:, maybe we should add this as a preconfigured option to the dotfile, i.e. as an additional setting for when `spaceline` is used as mode line....

**Comment by fawick** [comment]
IMHO that hack should not be made a preconfigured default, as the hardcoded subtrahend 70 is fully arbitrary and subjective. I guess using the window-total-width is not the right idea, here, too.  The preconfigured default should probably compute based on the width values of all other currently active spaceline items.
