### ISSUE TITLE
Unicode fallback fonts on Windows

### ISSUE THREAD

**Issue by fandag** [syl20bnr/spacemacs#1390]
Emacs on Windows doesn't use all available unicode chars in Source Code Pro. Specifically 0x2500 and 0x2502 is using BatangChe instead. This misaligns the "Important Notes" section of the Spacemacs start screen:
![capture](https://cloud.githubusercontent.com/assets/10060520/7336565/22363d9c-ec05-11e4-9f14-e41e89d363da.PNG)
The corners (0x256D, 0x256E, 0x256F, 0x2570) are using Source Code Pro.

In general, the range 0x25xx is a (random?) mix of Source Code Pro, BatangChe and Gothic, but I can get around this by specifically asking Emacs to prioritise Source Code Pro for that range:

    (set-fontset-font t '(#x2500 . #x25FF) "Source Code Pro")

However, I know almost nothing about how Emacs handles fonts and fallback fonts, so there is probably a more correct way to handle this?

**Comment by syl20bnr** [comment]
The fallback fonts should be only fonts that are available in the system. Is it possible to find a good fallback font for this range that comes with a Windows install ?

**Comment by fandag** [comment]
Thanks for taking the time! Just to make my question a bit more clear: I have Source Code Pro installed (as well as Gothic) and it is working perfectly for the ASCII characters. I'm very happy with the font :-) I don't have personal font configuration in my .spacemacs, but use the standard spacemacs configuration.

However, for certain ranges BatangChe (a Windows font) "overrules" Source Code Pro, for example in the 0x25xx characters. I took a closer look and it seems like the priorisation is as follows:
 1. BatangChe
 2. Source Code Pro
 3. Gothic

If a character is available in BatangChe it is chosen (e.g. 0x2502 "straight lnie"), if it is not available in BatangChe, Source Code Pro is chosen (e.g. 0x256D "rounded corner") and if it is available in neither, Gothic is chosen (e.g. 0x25C7). I'm using `describe-char` and `list-charset-chars` to debug this.

Adding the following to my dotspacemacs/init:

    (set-fontset-font t '(#x2500 . #x25FF) "Source Code Pro")

solves the problem by specifically asking Emacs to use Source Code Pro for these characters (while still falling back to Gothic if needed). The range could of course be shortened to (#x2500 . #x2503), since only these characters are used on the Spacemacs home screen, but extending the range also fixes the various text banners in ./core/banners/. Another solution might be to just uninstall BatangChe (did not test).

This is a very minor bug, since it is only aesthetics, but fixing it provides a better experience for newcommers. We could solve the bug by adding the above line to the code, but other ranges are probably also affected. I'm also happy to just keep that line in my personal config. If others are having a similar problem, they'll probably google this issue.

I guess this is really a bug in Windows/Emacs font handling...

PS: Thanks for putting Spacemacs together - it is an awesome Emacs configuration :-D

**Comment by fandag** [comment]
I'm closing this bug, since it is probably not a Spacemacs issue, but rather a system specific issue. I'm back on Linux again (where everything is working fine), so I can't debug it further.
