### ISSUE TITLE
Semantic result is wrong for C++ function declaration with override attribute

### ISSUE THREAD

**Issue by fperies** [syl20bnr/spacemacs#13914]
#### Description :octocat:
Semantic result is wrong for C++ function declaration with override attribute
It reports a variable definition with override as variable name instead of a function declaration !

#### Reproduction guide :beetle:
- Start Emacs
- Open a C++ header file with function declarations with override attribute
- Invoke command helm-jump-in-buffer

*Observed behaviour:* :eyes: :broken_heart:
It reports the following:
Variables : int override
![image](https://user-images.githubusercontent.com/7024137/92211613-05036a80-ee91-11ea-8bc6-ec68e0ff29ad.png)

*Expected behaviour:* :heart: :smile:
It should report something like:
Functions: functionName() [override]
![image](https://user-images.githubusercontent.com/7024137/92211777-40059e00-ee91-11ea-9998-cdd0bfba40e5.png)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 39df5e26b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-use-company-box t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
 (c-c++ :variables c-c++-enable-clang-format-on-save t)
 (c-c++ :variables c-c++-backend 'rtags)
 (c-c++ :variables c-c++-lsp-enable-semantic-highlight 't)
 cmake csv fzf emacs-lisp git helm html ibuffer imenu-list javascript lua markdown
 (multiple-cursors :variables multiple-cursors-backend 'mc)
 org
 (plantuml :variables plantuml-jar-path "~/plantuml.jar")
 python treemacs semantic syntax-checking themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS JSON PDUMPER GMP

#### Backtrace :paw_prints:
N.A

**Comment by smile13241324** [comment]
@fperies this does not look like our bug to be honest, given your config, almost everything happening on the semantic level should be handled by `rtags` spacemacs has no specific parse logic for this.

If the result is wrong this is most likely an issue within the `rtags` project and should be opened there.

**Comment by fperies** [comment]
Ok, I agree.
So, I will close this issue and will open a new one within the `rtags` project.

Thanks!

**Comment by fperies** [comment]
Ok, I agree.
So, I will close this issue and will open a new one within the `rtags` project.

Thanks!

**Comment by fperies** [comment]
Ok, I agree.
So, I will close this issue and will open a new one within the `rtags` project.

Thanks!
