### ISSUE TITLE
Mu4e Org support is broken

### ISSUE THREAD

**Issue by enderger** [syl20bnr/spacemacs#13913]
#### Description :octocat:
The Org support for mu4e appears to be broken

#### Reproduction guide :beetle:
- Start Emacs with the mu4e and org layers installed
- Launch mu4e
- Compose an email
You should notice the lack of support for Org syntax despite 

*Observed behaviour:* :eyes: :broken_heart:
No org support is found in mu4e messages

*Expected behaviour:* :heart: :smile:
Org syntax can be used in mu4e

#### System Info :computer:
- OS: gnu/linux (Artix)
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3ba5234e8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(haskell rust html helm auto-completion emacs-lisp racket clojure git java python
         (org :variables org-enable-trello-support t org-latex-preview-ltxpng-directory \.ltximg)
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         (spell-checking :variables spell-checking-enable-auto-dictionary t =enable-flyspell-auto-completion= t)
         syntax-checking perl6 gnus
         (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp" mu4e-use-maildirs-extension t mu4e-enable-mode-line t)
         version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by smile13241324** [comment]
Not sure what the issue is, the layer correctly requires the org related mu4e packages. I expect this to be a load order issue or an issue between mu4e org package and latest version of org.

Would be great if someone using mu4e can tackle this. I am using plain old thunderbird.

**Comment by codetrick** [comment]
There are two separate org - mu4e integration features distributed with mu4e, one `org-mu4e.el`, the other `mu4e-org.el`. 

The feature currently required in the mu4e layer is `mu4e-org`, which only supports creating links to mu4e messages and queries. The other feature `org-mu4e.el` supports composing messages in org-mode format.

That said, I have never used the org-mode composing feature. I'll check if requiring this feature leads to proper org-mode support and report back.

**Comment by codetrick** [comment]
I think the issue is resolved by my PR above (now merged).  Press `, o` from the mu4e compose buffer to enable org-mode syntax. @enderger could you pull the latest development branch and check that it works for you?

**Comment by theophilusx** [comment]
From what I can see and what has been posted to the mu4e list, the support for composing messages using org syntax which was provided by org-mu4e.el has been deprecated. The mu4e-org.el file is still included, which provides org support for links to mu4e messages. 

There are a few options for composing messages using Org markup, such as orgstruct, outshine, outorg, poporg and a few others. However, one I think which might be worth considering as an addition and replacement for existing org support in the mu4e layer is org-msg. https://github.com/jeremy-compostella/org-msg. 

today, I added org-msg to my mu4e setup and it looks very promising. To have a clean integration into the mu4e layer, it will be necessary to sort out key mappings etc. Essentially, it gives a very org like experience with support for org markup, source blocks and even evaluation of source blocks and inclusion of RESULTS sections etc. I did need to make a slight tweak of mu4e to support the ability to reply to messages and NOT include any cited text. In my setup now, you can call R with the universal argument to have mu4e create a reply buffer which does not include any cited original message text. 

When I can find time, I will start to look at how to add evil key bindings, but in the meantime, if anyone wants my configuration and my mu4e reply hack, let me know.
