### ISSUE TITLE
Spacemacs FAQ won't open within Spacemacs

### ISSUE THREAD

**Issue by NicholasKirchner** [syl20bnr/spacemacs#13923]
#### Description :octocat:
Cannot open the Spacemacs FAQ within Spacemacs

#### Reproduction guide :beetle:
- Start Emacs
- Type 'SPC h f'

*Observed behaviour:* :eyes: :broken_heart:
- Error message: "Cannot open load file: No such file or directory, helm-org"
- No FAQ gets loaded

*Expected behaviour:* :heart: :smile:
FAQ should load in a buffer.

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 59f72709b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go helm emacs-lisp)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER

**Comment by duianto** [comment]
The `helm-spacemacs-help-faq` function which is called with `SPC h f` seems to depend on the `org` layer, where `helm-org` is defined.
https://github.com/syl20bnr/spacemacs/blob/59f72709b8c2863bb9182095fbdbc71eba56040f/layers/%2Bemacs/org/packages.el#L20
https://github.com/syl20bnr/spacemacs/blob/59f72709b8c2863bb9182095fbdbc71eba56040f/layers/%2Bemacs/org/packages.el#L88-L91

The pending PR #13924 does fix the error.

But it causes a warning on startup when the `org` layer is enabled:
>                      Warnings:
>                          - More than one init function found for package helm-org. Previous owner was helm,
>                            replacing it with layer org.      

I'm not sure how this should be handled, I'll ask if the other maintainers have any ideas.

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Add the helm-org package so that helm-spacemacs-faq works #13924

The `helm-org` definition was removed from the `org` layer. It's now only defined in the `helm` layer.
