### ISSUE TITLE
Consider not disabling menu-bar-mode by default

### ISSUE THREAD

**Issue by cadadr** [syl20bnr/spacemacs#13939]
Hi all!

As some of you might be aware, there's discussion regarding making Emacs more approachable to newcomers, over on emacs-devel.  Distributions like Spacemacs are part of the discussion, and it's a common conclusion that projects like yours are very helpful in this regard and there are ideas about collaboration and support.

As part of those discussions, trying to spot what some common patterns might be hiding some otherwise more discoverable functionality in Emacs, we came to the conclusion that the menu bar is important as a tool for discovering functionality, both a fixed set, and minor/major mode related stuff.

This is of course not a catch-all fix to the problems of the newcomers, and a lot of ideas are being produced around how to solve other, more major problems, but not disabling menu-bar-mode by default seems to be a step in the right direction.

So we thought that recommending distributions that seem to disable it by default to consider leaving that to the user instead. If you want to read more on the discussions, or contribute your views, please don't hesitate to do so on the emacs-devel mailing list.

**Comment by emacs18** [comment]
I agree that default should be geared for newer users.  Following patch changes the default so that toolbar, menubar, scrollbar are all enabled by default, but adds commented out line within user config function so that whoever wants these features disabled can do so merely by uncommenting one line.

```diff
diff --git a/core/core-spacemacs.el b/core/core-spacemacs.el
index 0d036bd..d5bb938 100644
--- a/core/core-spacemacs.el
+++ b/core/core-spacemacs.el
@@ -58,7 +58,6 @@ the final step of executing code in `emacs-startup-hook'.")
   (setq ad-redefinition-action 'accept)
   ;; this is for a smoother UX at startup (i.e. less graphical glitches)
   (hidden-mode-line-mode)
-  (spacemacs//removes-gui-elements)
   (spacemacs//setup-ido-vertical-mode)
   ;; explicitly set the preferred coding systems to avoid annoying prompt
   ;; from emacs (especially on Microsoft Windows)
diff --git a/core/templates/.spacemacs.template b/core/templates/.spacemacs.template
index 1529e5d..d1a565d 100644
--- a/core/templates/.spacemacs.template
+++ b/core/templates/.spacemacs.template
@@ -591,6 +591,8 @@ This function is called at the very end of Spacemacs startup, after layer
 configuration.
 Put your configuration code here, except for variables that should be set
 before packages are loaded."
+  ;; Uncomment following line to disable toolbar, menubar, and scrollbar.
+  ;; (spacemacs//removes-gui-elements)
   (setq-default evil-escape-key-sequence "fq")
 
   (when (eq dotspacemacs-editing-style 'hybrid)
```
