### ISSUE TITLE
Fails to start lsp-r server when entering ESS mode

### ISSUE THREAD

**Issue by Prometheus77** [syl20bnr/spacemacs#13934]
#### Description :octocat:
Fails to start lsp-r server when entering ESS mode

#### Reproduction guide :beetle:
- Start Emacs
- Add ESS layer to dotfile
- Open a .R file

*Observed behaviour:* :eyes: :broken_heart:
When starting up ESS[R] mode, get message:
Server lsp-r:11140 status:starting exited with status exit. Do you want to restart it? (y or n) 
Restarting (y) will just repeat the message. Exiting (n) will clear.

*Expected behaviour:* :heart: :smile:
lsp-r server starts with no issues

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 18949e85e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html auto-completion better-defaults emacs-lisp
      (ess :variables ess-r-backend 'lsp)
      git helm latex lsp lua markdown multiple-cursors org
      (python :variables python-backend 'anaconda)
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking themes-megapack tmux treemacs version-control
      (xclipboard :variables xclipboard-enable-cliphist t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2

#### Backtrace :paw_prints:
```
```

**Comment by beyondpie** [comment]
@Prometheus77 
I use macOS with Emacs 26.3, 27.1, even 28.05. No such problem.
Have you installed the[ R language server](https://github.com/REditorSupport/languageserver) ?

**Comment by smile13241324** [comment]
@Prometheus77 looks like there is an issue with your LSP server. Please check your buffers there should be a lsp log or lsp error buffer with some specific error message. If you don't find one, please start the server from the command line and post the error message you are seeing there, if any.

**Comment by Prometheus77** [comment]
This was my bad. I solved it by a simple `install.packages("languageserver") from within an R session. Apparently Emacs was using a different R instance than RStudio, which I did not realize.

**Comment by Prometheus77** [comment]
OK, just kidding. After briefly working, it is again not working. Reopening.

**Comment by smile13241324** [comment]
Strange, so the message you have posted should just be an informational one telling you that a certain feature from lsp is not supported by the language server.

When you open an R file does the server startup properly and do you have the default lsp bindings? You can find them in the lsp layer description.

In the meantime I am installing the ess layer and the lsp server and see what happens when I open a R file.

**Comment by smile13241324** [comment]
So I am through, I have installed the ESS layer with `(ess :variables ess-r-backend 'lsp)`.
Before I have started the R shell and installed the linter and language server into a local folder:
``` R
install.packages("lintr")
install.packages('languageserver')
```
After this I have put the result into my path and checked out `TMwR` from github. There I have opened the file `ames_snippets.R`. There I have seen the warnings you have seen however only when the buffer was in fundamental mode. When I switched to `ess-r-mode` everything worked as expected.

I think the only issue here is that the buffer is opened in fundamental mode but should actually auto-open in `ess-r-mode`. I will try to make a fix for this.

Would you mind trying whether the workflow described above solves your issue?


![Screenshot from 2020-09-23 21-01-55](https://user-images.githubusercontent.com/18098560/94057570-17156080-fde0-11ea-9263-5b480a12650d.png)

**Comment by beyondpie** [comment]
@Prometheus77 
would you mind to delete the LSP package (should under ~/.emacs.d/elpha/[emacs-version]/lsp-[blabla]), and let spacemacs reinstall LSP?   I have a similar problem, and it works after reinstalling the LSP.

**Comment by ECon87** [comment]
Any updates? I am having issues with R lsp and completion as well

**Comment by smile13241324** [comment]
Not really, I did not receive an answer to my last comment, and as it was working on my side, I let that issue drop. Can you double check with my workflow above and give some feedback? I could then have another look.

**Comment by Prometheus77** [comment]
For some unknown reason it's working again. Since I can't reproduce, going to close issue.

**Comment by ECon87** [comment]
I still get the error.

The lsp-log file reads:

`
Command "R --slave -e languageserver::run()" is present on the path.
Command "R --slave -e languageserver::run()" is present on the path.
Found the following clients for /PATH_TO_FILE/file.R: (server-id lsp-r, priority 0)
The following clients were selected based on priority: (server-id lsp-r, priority 0)
Cancelling textDocument/documentLink(5) in hook post-command-hook
Cancelling textDocument/documentLink(3) in hook post-command-hook
Cancelling textDocument/documentColor(2) in hook post-command-hook
`
The lsp-r::stderr reads

`
[2021-03-20 19:57:07.688] error handling json:  Error: parse error: premature EOF
                                       {"jsonrpc":"2.0","method":"text
                     (right here) ------^

Stack trace:
1: parse_string(txt, bigint_as_char)
2: parseJSON(txt, bigint_as_char)
3: parse_and_simplify(txt = txt, simplifyVector = simplifyVector, 
    simplifyDataFrame = simplifyDataFrame, simplifyMatrix = simplifyMatrix, 
    flatten = flatten, ...)
4: jsonlite::fromJSON(data, simplifyVector = FALSE)
[2021-03-20 19:57:07.693] Error: Unexpected non-empty line
Call: self$read_header()
Stack trace:
1: stop("Unexpected non-empty line")
2: self$read_header()
3: self$fetch(blocking = FALSE)
[2021-03-20 19:57:07.694] exiting
`
