### ISSUE TITLE
Setting Fonts in Emacs 27 not working

### ISSUE THREAD

**Issue by goldenHairDafo** [syl20bnr/spacemacs#13947]
#### Description :octocat:
Setting the font via dotspacemacs-default-font stopped working
after updating to Emacs 27.1 This effects the linux and the 
windows version of Emacs

#### Reproduction guide :beetle:
- Update Emacs
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The default font is used.

*Expected behaviour:* :heart: :smile:
My font would be used

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(windows-scripts helm auto-completion csv
                 (c-c   :variables c-c  -enable-clang-support t)
                 colors e6z9r elm emacs-lisp git markdown python spell-checking syntax-checking search-engine smex
                 (sql :variables sql-capitialize-keywords t)
                 version-control clojure html go
                 (ibuffer :variables ibuffer-group-buffers-by 'projects)
                 localconfig rust themes-megapack yaml plantuml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by duianto** [comment]
It seems to be working for me on both the `master` and `develop` branch, with Emacs 27.1 in Windows 2004.

The following font is specified in `.spacemacs`:
```elisp
   dotspacemacs-default-font '("DejaVu Sans"
                               :size 10.0
                               :weight normal
                               :width normal)
```
With the cursor on the Spacemacs buffers first character (`gg`) (the `0` in the version number on the first line)
Pressing: `SPC h d c` (which calls `describe-char`)
Opens a Help buffer where first paragraphs last line says:
```
    harfbuzz:-outline-DejaVu Sans-normal-normal-normal-sans-13-*-*-*-p-*-iso8859-1 (#x13)
```

And with the following font:
```elisp
   dotspacemacs-default-font '("Source Code Pro"
                               :size 10.0
                               :weight normal
                               :width normal)
```
`SPC h d c` shows:
```
    harfbuzz:-outline-Source Code Pro-normal-normal-normal-mono-13-*-*-*-c-*-iso8859-1 (#x36D)
```

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d8260ea04)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git go haskell helm
            (javascript :variables javascript-backend 'lsp)
            (languagetool :variables langtool-language-tool-jar "C:\\Users\\username\\Applications\\LanguageTool-5.0\\languagetool-commandline.jar")
            lsp markdown multiple-cursors org
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            shell version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by goldenHairDafo** [comment]
@duianto 

I tried the excat same lines on both Window Server 2012 and an up to date Arch Linux.

The output for SPC h d c on Windows:
    harfbuzz:-outline-Courier New-normal-normal-normal-mono-19-*-*-*-c-*-iso8859-1 (#x33)
 
As stated setting fonts via XResource on Linux and (set-frame-font ...) on Windows works just fine.

**Comment by goldenHairDafo** [comment]
Update: 
It looks like an timing issue. When I set the font in a layer under ~/.emacs.d/private 
via (set-frame-font ...) I can see that the font is set but gets overwritten shortly thereafter.

**Comment by andreaswittmann** [comment]
I have the same problem on MacOS (Catalina 10.15.7)
After Updating to Emacs 27.1 the variable dotspacemacs-default-font is ignored.
I am using the MacPort Version of GNU Emacs:
GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2020-08-16

**Comment by smatting** [comment]
I have the same problem since switching to the `develop` branch, on nixos-20.03. I can set my desired font with `menu-set-font`, but the configuration in `.spacemacs` is not applied when loading.

**Comment by theophilusx** [comment]
I do not see this issue on Ubuntu, Arch or macOS. Running the development branch (current head) of spacemacs. Using cascadia and fira code OTF fonts works. Note that Emacs 27. has changed default font handling and now works best using Cairo and hafbuzz. Have seen reports where people have had problems with some fonts not being available - reasons have been various, but having old xft font backend set in .Xresources or .Xdefaults one common cause (See Emacs News file). Might be worth checking the fonts will work with vanilla Emacs.

**Comment by goldenHairDafo** [comment]
@theophilusx as written before: Emacs itself has no problem using the fonts I tried. After init is complete I can use ```(set-frame-font ...)``` to set the font.

**Comment by omgMerrickD** [comment]
I have the same problem on Manjaro/Arch 20.1.2 on the develop branch.

I have spacemacs running in daemon mode and I've set the font in the spacemacs config via `SPC f e d`.  When I load into a frame (not a tty), spacemacs will use the default font/size.  If I do a `SPC h d c` it reports that it's using the correct size/weight, however that is not what I'm seeing on my screen.

However, if I then do a `SPC  T s` and choose any random theme, the correct font family, size and weight will be displayed on screen and `SPC h d c` will still report the exact same value that it erroneously reported prior. 

Please note that when exiting via frame killer `SPC q f`, reload config `SPC q R`/`SPC q r` or full kill `SPC q Q` will cause everything to stop working again.  I would then need to change the theme to get the font to display correctly.

Let me know if you need more information.  Maybe I could do video of it to highlight.

**Comment by ngoonee** [comment]
> I have the same problem on Manjaro/Arch 20.1.2 on the develop branch.
> 
> I have spacemacs running in daemon mode and I've set the font in the spacemacs config via `SPC f e d`. When I load into a frame (not a tty), spacemacs will use the default font/size. If I do a `SPC h d c` it reports that it's using the correct size/weight, however that is not what I'm seeing on my screen.
> 
> However, if I then do a `SPC T s` and choose any random theme, the correct font family, size and weight will be displayed on screen and `SPC h d c` will still report the exact same value that it erroneously reported prior.
> 
> Please note that when exiting via frame killer `SPC q f`, reload config `SPC q R`/`SPC q r` or full kill `SPC q Q` will cause everything to stop working again. I would then need to change the theme to get the font to display correctly.
> 
> Let me know if you need more information. Maybe I could do video of it to highlight.

This is the same behaviour I'm getting on Arch. However for me `SPC h d c` does not report the correct size/weight initially (only after I choose a theme). This is on the develop branch
