### ISSUE TITLE
git-gutter+ breaks visual line navigation when combined with org-indent-mode

### ISSUE THREAD

**Issue by muusik** [syl20bnr/spacemacs#13946]
#### Description :octocat:
Cursor does not stay in one column when navigating up and down visual lines of org-mode buffers if git-gutter+ is active.

#### Reproduction guide :beetle:
- Start Emacs
- Create or open a version-controlled org file
- Enable org-indent-mode
- Enable visual-line-navigation
- Insert a new heading. The more indented, the more obvious the effect.
- Below the new heading, insert a line of text long enough to wrap over three or more lines.
- Save the buffer. This should bring out the git-gutter-plus markings.
- Navigate up and down the resulting visual lines of text.

*Observed behaviour:* :eyes: :broken_heart:
- Cursor moves left and right in addition to up and down.
- Cursor sometimes skips visual lines.

*Expected behaviour:* :heart: :smile:
- Cursor should stay in one column (except on visual lines shorter than that column).
- Cursor shouldn't skip visual lines.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7a7b04abb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp multiple-cursors treemacs auto-completion csv finance git haskell html javascript lua markdown org org-customizations php
      (python :variables python-test-runner 'pytest python-formatter 'black)
      ranger rust shell-scripts sql syntax-checking themes-megapack typescript version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by duianto** [comment]
Confirmed.

![2020-09-18_07-35-17](https://user-images.githubusercontent.com/13420573/93560107-a30f2e80-f981-11ea-8527-d13018072f50.gif)

The cursor jumps over the second line: `vel tortor sodales ...`
when moving up, but not when moving down.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d8260ea04)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git go haskell helm
            (javascript :variables javascript-backend 'lsp)
            (languagetool :variables langtool-language-tool-jar "C:\\Users\\username\\Applications\\LanguageTool-5.0\\languagetool-commandline.jar")
            lsp markdown multiple-cursors org
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            shell version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by lebensterben** [comment]
This probably should be reported upstream. But git-gutter+ isn't actively updated.

**Comment by lebensterben** [comment]
@duianto 
Should we replace git-gutter+ with the more actively maintained [`git-gutter`](https://github.com/emacsorphanage/git-gutter/tree/1003c8cbe2367482ad02422ace0a85a7d56d01d3)?

**Comment by muusik** [comment]
For what it's worth, I can reproduce the same behaviour with git-gutter and diff-hl (as well as git-gutter+ as originally reported), so maybe it's org-indent-mode, or at least org-mode would be a worthwhile upstream to talk to?

Realistically, how much more actively is git-gutter maintained if it lives in "emacsorphanage"? Also, Version-Control layer supports easy switching between git-gutter[+] and diff-hl, so I wouldn't recommend going as far as removing either, perhaps changing the default if warranted. Unless one of them emerges as the clear winner in terms of features, compatibility and active maintainership.

**Comment by lebensterben** [comment]
@muusik 
Then the other alternative is to report this issue to org mode upstream and hopefully they can fix `org-indent-mode`. But I'm not sure what's the cause of the bug right now.
