### ISSUE TITLE
How should we respond to the archiving of Helm?

### ISSUE THREAD

**Issue by Kazark** [syl20bnr/spacemacs#13943]
Background: https://github.com/emacs-helm/helm/issues/2386

Helm is the default in Spacemacs, so this is something we will need to respond to. Should we:

* use a fork? I haven't heard of it being forked yet, but surely it will be.
* Make Ivy the default? I've never tried Ivy and don't know anything about this option.
* Add support for [Selectrum](https://github.com/raxod502/selectrum)?

Thought I should start a discussion.

**Comment by Kazark** [comment]
https://github.com/raxod502/ctrlf is a replacement for `helm-swoop`.

**Comment by jb55** [comment]
> Make Ivy the default? I've never tried Ivy and don't know anything about this option

I switched to ivy in spacemacs awhile ago and it works fine. Seems like the most reasonable option.

**Comment by Kazark** [comment]
@jb55 are there any features you miss?

**Comment by smile13241324** [comment]
Don't know if this is the right moment to do so, I still expect that someone will adopt this package. 

Personally I don't think that `Selectrum` is an alternative, it follows the same design principle `ivy` does this is less features, be fast and simple. That's normally not the design expected by people using helm, rather something among the line of provide a lot of choices to do exactly what I want, be allowed to be slow but comprehensive.

Lets try to gather alternative comprehensive search and narrowing frameworks for emacs.
Maybe we find a replacement for helm after all.

Btw that doesn't mean we could not support `Selectrum` but it sounds pretty undistinguishable from standard `ivy` from my perspective.

**Comment by Kazark** [comment]
@smile13241324 Selectrum's README links to another of comparable projects.

**Comment by syl20bnr** [comment]
This is big and sad news. I'm a Helm user myself.
For sure Helm is a great package but it is also huge, I really hope someone can take over 🤞 

We won't phase it out any time soon though but it is always good to see the alternatives.
Fortunately we have very good support for Ivy too. 

Let's see what happens following this news.

**Comment by Kazark** [comment]
Given that Helm is back, in some capacity, I'm thinking there's nothing for us to do at this time.
