### ISSUE TITLE
Can't push using `p` after toggling text-mode twice

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#13948]
#### Description :octocat:
Can't push using just `p` after having toggled text-mode twice in magit.

Initially I reported this issue at emacs-evil/evil-magit#84, but as I mention in a comment there, a co-worker tried in his Emacs (he uses _evil-magit_ but not Spacemacs) and he did not observe the same behaviour.

#### Reproduction guide :beetle:
- Start Emacs
- Open a project with a git repo
- Press `SPC g s` to enter magit
- Press `\` to enter text-mode
- Press `\` to exit text-mode
- Press `p` to push

*Observed behaviour:* :eyes: :broken_heart:
A message saying that `Buffer is read-only: #<buffer magit: proj>`.

*Expected behaviour:* :heart: :smile:
The magit push menu should pop up.

I should add that `p` does work if I enter visual mode first, i.e. `v` followed by `p`.
 
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 58d2a69a0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash docker evil-commentary evil-snipe git github
 (helm :variables helm-no-header t)
 lsp mu4e multiple-cursors restclient
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak)
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking templates
 (xclipboard :variables xclipboard-enable-cliphist t)
 (clojure :variables clojure-enable-sayid t clojure-enable-clj-refactor t clojure-enable-linters 'clj-kondo)
 dhall emacs-lisp
 (go :variables go-backend 'lsp)
 (haskell :variables haskell-completion-backend 'lsp haskell-process-type 'cabal-repl)
 (python :variables python-formatter 'yapf)
 shell-scripts csv graphviz html json latex markdown
 (org :variables org-enable-reveal-js-support t)
 nixos spacemacs-org
 (sql :variables sql-auto-indent nil)
 pandoc terraform yaml clipboard-fix direnv projectile-extra org-roam)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by duianto** [comment]
Confirmed.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3d5d4b2f2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git go haskell helm
            (javascript :variables javascript-backend 'lsp)
            (languagetool :variables langtool-language-tool-jar "C:\\Users\\username\\Applications\\LanguageTool-5.0\\languagetool-commandline.jar")
            lsp markdown multiple-cursors org
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            shell spell-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by duianto** [comment]
It seems to be caused by this line in the `multiple-cursors` layer:
https://github.com/syl20bnr/spacemacs/blob/3d5d4b2f280259daa737e8e3558eb6b61ae4ad54/layers/%2Bmisc/multiple-cursors/packages.el#L24

When it's commented out, then it works as expected.

**Comment by duianto** [comment]
`evil-mc` mode isn't enabled when a magit buffer is opened.

```
SPC h d m              ;; lazy-helm/describe-mode
```
shows:
>Enabled minor modes: Anzu Async-Bytecomp-Package Auto-Composition
Auto-Compression Auto-Encryption Clean-Aindent Column-Number Editorconfig
Electric-Indent Evil Evil-Escape Evil-Local Eyebrowse File-Name-Shadow Font-Lock
Global-Anzu Global-Auto-Revert Global-Eldoc Global-Font-Lock Global-Git-Commit
Global-Git-Gutter+ Global-Hl-Line Global-Hl-Todo Global-Magit-File
Global-Page-Break-Lines Global-Spacemacs-Leader-Override Global-Undo-Tree
Global-Vi-Tilde-Fringe Helm Helm-Descbinds Helm-Ff-Cache Helm-Flx Ido-Vertical
Line-Number Magit-Gitflow Mouse-Wheel Override-Global Persp Projectile Pupo
Purpose Recentf Save-Place Savehist Shell-Dirtrack Spaceline-Helm Spaceline-Info
Spacemacs-Leader-Override Transient-Mark Treemacs-Filewatch Treemacs-Follow
Treemacs-Fringe-Indicator Treemacs-Icons-Dired Undo-Tree Which-Key Winner Winum
Xterm-Mouse

After toggling to `text-mode` in the magit buffer, then `evil-mc-mode` becomes enabled:
>Enabled minor modes: Anzu Async-Bytecomp-Package Auto-Composition
Auto-Compression Auto-Encryption Clean-Aindent Column-Number Editorconfig
Electric-Indent Evil Evil-Escape Evil-Local Evil-Magit-Toggle-Text **Evil-Mc**
Evil-Surround Eyebrowse File-Name-Shadow Flyspell Font-Lock Global-Anzu
Global-Auto-Revert Global-Eldoc Global-Evil-Surround Global-Font-Lock
Global-Git-Commit Global-Git-Gutter+ Global-Hl-Line Global-Hl-Todo
Global-Magit-File Global-Page-Break-Lines Global-Spacemacs-Leader-Override
Global-Undo-Tree Global-Vi-Tilde-Fringe Helm Helm-Descbinds Helm-Ff-Cache
Helm-Flx Hl-Todo Ido-Vertical Line-Number Mouse-Wheel Override-Global Persp
Projectile Pupo Purpose Recentf Save-Place Savehist Shell-Dirtrack
Spaceline-Helm Spaceline-Info Spacemacs-Leader-Override Transient-Mark
Treemacs-Filewatch Treemacs-Follow Treemacs-Fringe-Indicator
Treemacs-Icons-Dired Undo-Tree Which-Key Winner Winum Xterm-Mouse

And it remains enabled when switching back to `magit-status-mode`.
>Enabled minor modes: Anzu Async-Bytecomp-Package Auto-Composition
Auto-Compression Auto-Encryption Clean-Aindent Column-Number Editorconfig
Electric-Indent Evil Evil-Escape Evil-Local **Evil-Mc** Evil-Surround Eyebrowse
File-Name-Shadow Font-Lock Global-Anzu Global-Auto-Revert Global-Eldoc
Global-Evil-Surround Global-Font-Lock Global-Git-Commit Global-Git-Gutter+
Global-Hl-Line Global-Hl-Todo Global-Magit-File Global-Page-Break-Lines
Global-Spacemacs-Leader-Override Global-Undo-Tree Global-Vi-Tilde-Fringe Helm
Helm-Descbinds Helm-Ff-Cache Helm-Flx Ido-Vertical Line-Number Magit-Gitflow
Mouse-Wheel Override-Global Persp Projectile Pupo Purpose Recentf Save-Place
Savehist Shell-Dirtrack Spaceline-Helm Spaceline-Info Spacemacs-Leader-Override
Transient-Mark Treemacs-Filewatch Treemacs-Follow Treemacs-Fringe-Indicator
Treemacs-Icons-Dired Undo-Tree Which-Key Winner Winum Xterm-Mouse

I'm not sure how to fix this, any suggestions are welcome.

**Comment by smile13241324** [comment]
Just merged the PR @magthe, can you retry with latest develop and close this issue when it is working?

**Comment by magthe** [comment]
Seems to work :smiley:
