### ISSUE TITLE
lsp-origami integration is broken

### ISSUE THREAD

**Issue by oxyum** [syl20bnr/spacemacs#13959]
#### Description :octocat:
lsp-origami integration is broken

#### Reproduction guide :beetle:
- Start Emacs 
- Open some files with LSP backend (Python with PyRight in my case)

*Observed behaviour:* :eyes: :broken_heart:
LSP works from time to time and mostly unusable

```
Error processing message (error "Autoloading file /home/ifedorov/.config/emacs/elpa/28.0/develop/lsp-origami-20200914.1846/lsp-origami.elc failed to define function lsp-origami").
Error running timer ‘lsp--on-idle’: (error "The connected server(s) does not support method textDocument/documentHighlight.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section")
```

Bug in lsp-origami repo: emacs-lsp/lsp-origami#11

*Expected behaviour:* :heart: :smile:
LSP works!

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 14dcebd4a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(syntax-checking
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 helm templates better-defaults helpful
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (org :variables org-enable-bootstrap-support t org-enable-github-support t org-enable-jira-support t org-enable-org-journal-support t org-enable-reveal-js-support t org-enable-sticky-header t)
 treemacs unicode-fonts django react selectric xkcd copy-as-format ietf multiple-cursors parinfer spotify asciidoc c-c++ csv emacs-lisp go graphviz groovy html ipython-notebook java
 (javascript :variables javascript-fmt-tool 'prettier)
 json major-modes markdown
 (plantuml :variables plantuml-jar-path "/usr/share/plantuml/plantuml.jar")
 protobuf
 (python :variables python-backend 'lsp python-lsp-server 'pyright python-formatter 'black python-test-runner 'pytest)
 rust typescript shell-scripts sql yaml dash deft epub pdf speed-reading
 (git :variables git-magit-status-fullscreen t)
 github version-control ansible bm chrome cmake command-log dap docker fasd imenu-list import-js kubernetes lsp nginx node pass prettier prodigy ranger restclient
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 systemd tern tide web-beautify xclipboard search-engine)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2

**Comment by oxyum** [comment]
As of now I just switched to 8dabfcd6c where lsp-origami is not merged yet.

**Comment by emacs18** [comment]
My emacs 28 on ubuntu works fine, i.e., lsp-origami loaded fine.

BTW you said you were using git rev `14dcebd`.  I can't locate that version.
I use develop branch rev `2fbd853f9` from Sep 16.

**Comment by allengreer-latero** [comment]
A workaround is also too add `lsp-origami` to  `dotspacemacs-excluded-packages` in your spacemacs config. :D

**Comment by smile13241324** [comment]
:thinking: thats strange issues like this should not happen, I will have a look.

**Comment by oxyum** [comment]
> My emacs 28 on ubuntu works fine, i.e., lsp-origami loaded fine.

It fails not right after start but after I opened some buffers with lsp-python.

> BTW you said you were using git rev `14dcebd`. I can't locate that version.

Man, are you serious?! :)

```git fetch``` can help you -> https://github.com/syl20bnr/spacemacs/commit/14dcebd4a30a1a18847adbaefa9df8d1e5c2bc4d

> I use develop branch rev `2fbd853f9` from Sep 16.

That's just one commit before mine.

**Comment by smile13241324** [comment]
I have made a fix on develop, which solved the issue for me for `web-mode` and `python-mode` lsp. Care to check on your side @oxyum and @allengreer-latero?

**Comment by allengreer-latero** [comment]
@smile13241324 Just pulled the latest changes & issue seems to be resolved! Thanks for the quick turn around on this one. Really a major improvement in `typescript`/`typescript-tsx` modes using origami as comments above functions were hidden:

### Before
```
// Comment obstructing view of first line of function
}
```
### After
```
// TODO: Donate to Spacemacs
const foo() => {
}
```

**Comment by oxyum** [comment]
@smile13241324 You are the BEST!!! Thanks!

**Comment by emacs18** [comment]
@oxyum Sorry about version comment.  I was multi-tasking and did git fetch from the wrong repo!

**Comment by oxyum** [comment]
@emacs18 no hard feelings! :)

**Comment by jmromer** [comment]
Still seeing this on develop @ 14dcebd4a:
```
File mode specification error: 
(error Autoloading file ~/.emacs.d/elpa/28.0/develop/lsp-origami-20200914.1846/lsp-origami.el failed to define function lsp-origami)
```

**Comment by oxyum** [comment]
@jmromer That's expected - it was fixed only at https://github.com/syl20bnr/spacemacs/commit/d8260ea04169e3b4527086e611fce97fc0027b86

**Comment by jmromer** [comment]
Thanks! User error — my spacemacs repo's remote was mis-set.
