### ISSUE TITLE
Fonts shrink too much when changing Gnome fractional scaling

### ISSUE THREAD

**Issue by dmusican** [syl20bnr/spacemacs#13965]
#### Description :octocat:
Changing Gnome fractional scaling from 100% to 125% makes very small fonts

#### Reproduction guide :beetle:
- Start Emacs under Ubuntu 20.04 with Gnome fractional scaling set to normal 100%
- Observe that Emacs starts at a reasonable font
- Change Gnome fractional scaling to 125%

*Observed behaviour:* :eyes: :broken_heart:
Fonts get really tiny and hard to read

*Expected behaviour:* :heart: :smile:
Fonts should stay essentially the same size. Vanilla emacs does this.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b83eb11e3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by robbyoconnor** [comment]
Probably has more to di with GTK+ than anything else.

**Comment by robbyoconnor** [comment]
This is likely not a spacemacs issue at all.

**Comment by dmusican** [comment]
Except the problem doesn't occur with vanilla emacs.

**Comment by jr0cket** [comment]
May be related to https://github.com/syl20bnr/spacemacs/issues/14142
