### ISSUE TITLE
Using the mouse in customize work only in insert state

### ISSUE THREAD

**Issue by real-or-random** [syl20bnr/spacemacs#13970]
#### Description :octocat:
Using the mouse to click on buttons and certain links in "customize" works only in insert state

I can reproduce this even after deleting my dotfile.

#### Reproduction guide :beetle:
- Start Emacs
- M-x M-x customize
- Click on the "State" button or on the one "More" link

*Observed behaviour:* :eyes: :broken_heart:
Nothing happens.
If you switch to insert state first, it works. 

*Expected behaviour:* :heart: :smile:
Should work in normal mode. I wouldn't bet my life on it but I believe this worked in normal mode before.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3d5d4b2f2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv html javascript systemd helm auto-completion better-defaults emacs-lisp git github markdown
     (org :variables org-enable-github-support t)
     spell-checking syntax-checking treemacs
     (latex :variables latex-enable-auto-fill nil)
     pdf yaml lua gtags lsp
     (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-lsp-enable-semantic-highlight 'rainbow)
     php python rust shell major-modes org-roam)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

Maybe related to https://github.com/syl20bnr/spacemacs/commit/68debde4a29c49797b6b70372c6b2ca2ac43ea45

**Comment by real-or-random** [comment]
Ah, and another issue with customize mode (not entirely sure if introduced by 68debde4a29c49797b6b70372c6b2ca2ac43ea45) is that using a link (no matter if with mouse or keyboard) opens a new buffer. That's pretty annoying. Browse around to get a grasp of possible settings and find that you have tens of buffers open.

**Comment by duianto** [comment]
Confirmed.
When mouse clicking on some links or buttons in a customize buffer, in evil normal state.

`C-h l` (l = lower case L) shows:
- When nothing happens:
```
 <help-echo> <down-mouse-1>                         ;; evil-mouse-drag-region
```
- When the link works:
```
 <mouse-1>                                          ;; widget-move-and-invoke
```

**Comment by real-or-random** [comment]
The issue is still valid.
