### ISSUE TITLE
Signed commits in develop branch don't have expected signatures.

### ISSUE THREAD

**Issue by rayw000** [syl20bnr/spacemacs#13979]
Hi there!

I've noticed that all the signed commits in `develop` branch are signed either with gpg key `2DD07025BFDBD89A` (owned by @smile13241324 ) or `4AEE18F83AFDEB23` (owned by GitHub). Seems commits of pull requests are always edited with the GitHub web UI before merging.

Signature means me a bit more, my own signature would make reputations for some organizations. 🙂
Could somebody tell me why we need to do this? How could I do to make my commits have my own signature? 

Thanks a lot! 😃

**Comment by robbyoconnor** [comment]
Because they tend to cherry-pick commits vs merge.

**Comment by robbyoconnor** [comment]
Because they tend to cherry-pick commits vs merge. Git commit objects are immutable, so when you cherry-pick, you are actually creating a new commit object.
