### ISSUE TITLE
flycheck-pylint is not called from project root

### ISSUE THREAD

**Issue by milochadam** [syl20bnr/spacemacs#13975]
#### Description :octocat:
flycheck-pylint is not called from project root which results 

#### Reproduction guide :beetle:
- Start Emacs
- Open a project with such structure:

```
.
├── submodule
│   ├── __init__.py
│   ├── a.py
│   └── b.py
```
Where `a.py`, and `b.py` contents are:
##### a.py
```
class A:
    def __init__(self):
        self.contents = ''
```

##### b.py
```
from .a import A


class B(A):
    def do_thing(self):
        self.contents = 'asdf'
```

*Observed behaviour:* :eyes: :broken_heart:
Error list shows:
```
b.py       4   9 warning  attribute-defined-outside-init Attribute 'contents' defined outside __init__ (python-pylint)
```

*Expected behaviour:* :heart: :smile:
Lack of this error since `self.contents` is defined.

It looks like something caused by checking file using `pylint b.py` from `submodule` directory instead of `pylint submodule/b.py` in project root (I checked that outside of Emacs and the latter doesn't report such error).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3d5d4b2f2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(systemd csv haskell lua org
         (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0 auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip 'manual auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup t)
         (spell-checking :variables spell-checking-enable-by-default nil)
         syntax-checking helm imenu-list lsp dap python django yaml react shell-scripts html
         (c-c++ :variables c-c++-backend 'rtags c-c++-enable-rtags-completion nil c-c++-enable-clang-format-on-save t c-c++-enable-google-style t c-c++-enable-google-newline t)
         javascript vimscript docker
         (python :variables python-backend 'lsp python-fill-column 200 python-lsp-server 'mspyls python-formatter nil python-sort-imports-on-save t)
         emacs-lisp
         (markdown :variables markdown-live-preview-engine 'vmd)
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         (latex :variables TeX-command-extra-options "-shell-escape" TeX-view-program-selection
                '((output-pdf "Okular")))
         git
         (ranger :variables ranger-show-preview t)
         multiple-cursors version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by beyondpie** [comment]
Hi, I guess the problem is that you are using lsp, and it doesn't get the project root. Normally, if it's a git repo, lsp will detect .git to set the root project. There exist some other ways to help lsp get the project root. You can try to search for the related infomration.

**Comment by milochadam** [comment]
Thanks for the tip though `(lsp-workspace-root)` seem to find the root correctly. The same goes for `(lsp-python-ms--workspace-root)` and `(projectile-project-root)`.
Are there any more variables or functions worth checking?

**Comment by beyondpie** [comment]
@milochadam 
I'm afraid that I cannot help you further since I know little about this...  I usually go to the gitter of lsp (you can find it easily on lsp github README) and ask them. They respond quickly and professionally.

**Comment by milochadam** [comment]
Turns out `(flycheck-compute-working-directory)` was getting the directory of the file.
Since `python-pylint` has no working-directory property I add it in my user-config:
```
(with-eval-after-load 'flycheck
  (put 'python-pylint (flycheck--checker-property-name 'working-directory) (lambda(_) (projectile-project-root))))
```
The warning seems to go away.

**Comment by alfans1** [comment]
husseinnooor46@gmail.com
