### ISSUE TITLE
Duplicate submenu items of menu item on the menu bar

### ISSUE THREAD

**Issue by bravestarr** [syl20bnr/spacemacs#13986]
- Description

If the menu bar is enabled, when getting into Info mode, there are duplicate Info menu items in the menu bar.
![info](https://user-images.githubusercontent.com/520822/94330644-f3793280-fff8-11ea-81ed-1b5905cb8909.png)
The same case is for the Minibuffer menu item.
![minibuffer](https://user-images.githubusercontent.com/520822/94330714-8ca84900-fff9-11ea-9528-3ef293fc41b2.png)
I'm not sure if there are similar problems, but the above cases occur always.

- System Info
OS: Windows 7
Emacs: 27.1
Spacemacs: 0.200.13
Spacemacs branch: master

**Comment by emacs18** [comment]
I too see the doubling of menu items for these major mode specific menus:
- in maigt mode, Magit pull-down menu show two "Magit" menu items
- in shell mode, following menu items are doubled up: "Complete", "In/Out", "Signals"

I use ubuntu 20.04, emacs 27, latest develop branch of spacemacs

**Comment by thanhvg** [comment]
This bug is on `evil` 
https://github.com/emacs-evil/evil/issues/404
https://github.com/emacs-evil/evil/issues/344
