### ISSUE TITLE
Autocomplete does not work inside org-edit-special for python

### ISSUE THREAD

**Issue by SarthakAdhikari** [syl20bnr/spacemacs#13992]
#### Description :octocat:
It seems that the company autocomplete works inside the org babel block but not inside a org-edit-special buffer(C-c ') for python. It works for elisp but not for python. 
Company mode also seems to be off by default on the special buffer for python.

#### Reproduction guide :beetle:
- Start Emacs
- Create new .org file
- Type the following:
```
#+begin_src python
  for i in range(10):
    print(10)
#+end_src
```
- Autocomplete pops up(company-complete) inside the src block and everything works fine until this point
- Put cursors inside the block and M-x org-edit-special (C-c ')
- Try to type the text again inside the special buffer and check if autocomplete still works when inside the special buffer

*Observed behaviour:* :eyes: :broken_heart:
Autocomplete is not showing up in the special buffer.

*Expected behaviour:* :heart: :smile:
Autocomplete works inside special buffer and pops up automatically during typing.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. ce7c2f05d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(html systemd systemd better-defaults emacs-lisp git
      (multiple-cursors :variables multiple-cursors-backend 'multiple-cursors)
      docker olivetti helm spotify lsp
      (auto-completion)
      markdown xah-fly-keys
      (elfeed :variables rmh-elfeed-org-files
              (list "~/.emacs.d/private/elfeed1.org" "~/.emacs.d/private/elfeed2.org"))
      command-log multiple-cursors python org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER GMP

**Comment by duianto** [comment]
Confirmed.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 00b1f419a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey clojure command-log emacs-lisp git go haskell helm
            (javascript :variables javascript-backend 'lsp)
            (languagetool :variables langtool-language-tool-jar "C:\\Users\\username\\Applications\\LanguageTool-5.0\\languagetool-commandline.jar")
            lsp markdown multiple-cursors org python shell spell-checking version-control tabs treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>
