### ISSUE TITLE
`(spacemacs/declare-prefix "d" "debugging")` which-key labels keybinding prefix as "documentation" instead of "debugging"

### ISSUE THREAD

**Issue by MElemental** [syl20bnr/spacemacs#13998]
#### Description :octocat:
which-key is labeling `d` as 'documentation' instead of 'debugging'.
Perhaps this is from some time when documentation was under `SPC d` instead of `SPC h`? I don't know if that's the case, but I assume that's why it would happen. Whatever the case I want which-key to label `d` as debugging and not documentation.

#### Reproduction guide :beetle:
- Start Emacs
- put `(spacemacs/declare-prefix "d" "debugging")` in `dotspacemacs/user-config`
- I also had `(spacemacs/set-leader-keys "d g" 'gdb)` in `dotspacemacs/user-config`
- `SPC q R` or `SPC f e R`
- press `SPC` to enter which-key
- Observe the label of `d`

*Observed behaviour:* :eyes: :broken_heart:

- which-key labels `d` as "documentation" and not "debugging"

*Expected behaviour:* :heart: :smile:
- which-key labels `d` as "debugging"

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 8b888c6a0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking syntax-checking auto-completion helm better-defaults
                (org :variables org-projectile-file "TODOs.org" org-enable-github-support t org-enable-org-journal-support t org-enable-epub-support t)
                typography neotree unicode-fonts emoji games xkcd alda asm bibtex c-c++ common-lisp csharp csv emacs-lisp ess fsharp graphviz gpu haskell html major-modes markdown java javascript latex octave python sql pdf epub speed-reading git github version-control cscope colors themes-megapack theming debug cmake command-log finance imenu-list ranger shell transmission
                (wakatime :variables wakatime-api-key "184d7ac8-c7f5-45cb-bfa3-08520925eb61" wakatime-cli-path "/usr/bin/wakatime"))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by MElemental** [comment]
There were some misplaced backticks and typos in my issue so I edited those if anyone saw this issue earlier.

**Comment by MElemental** [comment]
I found another keybinding that doesn't label according to my .spacemacs
`(spacemacs/declare-prefix "a e" "emms")` labels as `email` instead.

My guess is that perhaps these prefix declarations should be loaded with `with-eval-after-load` but I'm not sure what package you would load them after.

**Comment by duianto** [comment]
The "d" "documentation" prefix has recently been removed.

But "e" "email" remains.

The prefixes are defined here:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+spacemacs/spacemacs-defaults/keybindings.el#L17

I'm not sure how to make them user customizable.

**Comment by lebensterben** [comment]
@duianto I don't quite get it.
"email" is bound to "SPC a e" instead of "SPC e"

**Comment by duianto** [comment]
`SPC e` has key bindings related to: `errors`
`SPC a` has key bindings related to: `applications`

And `SPC a e` has key bindings related to: `email`

Three layers bind keys under that prefix.
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemail/gnus
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemail/mu4e
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemail/notmuch
