### ISSUE TITLE
dump-jump keybindings not remaining after restart

### ISSUE THREAD

**Issue by shirdekel** [syl20bnr/spacemacs#13993]
#### Description :octocat:
`dump-jump` keybindings only work after changing `dotspacemacs/user-config` and reloading configuration.

#### Reproduction guide :beetle:
- Start Emacs
- Set `dumb-jump` keys, e.g.:

```elisp
(spacemacs/set-leader-keys "jG" 'dumb-jump-go)
(spacemacs/set-leader-keys "jB" 'dumb-jump-back)
```

- Restart emacs
- New keybindings not under `SPC j`
- Reload configuration (`SPC f e R`)
- Keybindings now show under `SPC j`
- Restarting emacs again removes the keybindings

*Observed behaviour:* :eyes: :broken_heart:
Keybindings not appearing when first opening emacs

*Expected behaviour:* :heart: :smile:
Keybindings to remain after restarting emacs

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d72019e33)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp common-lisp git helm lsp markdown multiple-cursors
                 (markdown :variables markdown-command "pandoc" markdown-live-preview-mode nil)
                 org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control github html polymode
                 (osx :variables osx-command-as 'control osx-option-as 'meta osx-control-as 'hyper osx-function-as nil osx-right-command-as 'left osx-right-option-as 'left osx-right-control-as 'left osx-swap-option-and-command nil)
                 ess treemacs)
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by duianto** [comment]
The keys are bound on startup for me:

![emacs_2020-10-02_13-41-41](https://user-images.githubusercontent.com/13420573/94919749-43527080-04b5-11eb-8c1d-73e95dff2de4.png)

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cb26ca6b3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey clojure command-log emacs-lisp git go haskell helm
            (javascript :variables javascript-backend 'lsp)
            (languagetool :variables langtool-language-tool-jar "C:\\Users\\username\\Applications\\LanguageTool-5.0\\languagetool-commandline.jar")
            lsp markdown multiple-cursors org python shell spell-checking version-control tabs treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>


Maybe your already aware of it, but both of those commands are marked as obsolete:
>  This function is obsolete since 2020-06-26;
  `dumb-jump-go' has been obsoleted by the xref interface.

>  This function is obsolete since 2020-06-26;
  `dumb-jump-back' has been obsoleted by `xref-pop-marker-stack'.

**Comment by shirdekel** [comment]
I updated the ESS layer and now I use the xref interface, which works.
