### ISSUE TITLE
keybindings

### ISSUE THREAD

**Issue by sandikata** [syl20bnr/spacemacs#14025]
Hello, i am trying to understand how this works, and what SPC means?
If it's space, it does nothing in my case, as it just writing space on the document, but not as a shortcut.
Is it there some understandable documentation about the keybindings?

**Comment by V-J-P** [comment]
If spacemacs is installed correctly SPC (space) is the [leader key](https://www.spacemacs.org/doc/QUICK_START.html#the-leader-keys) for all bound commands.
When SPC just writes a whitespace you are either in insert mode of [evil-mode](https://www.emacswiki.org/emacs/Evil) or in emacs style.

**Comment by sandikata** [comment]
Hello!
Got it, thank you for your response.

**Comment by smile13241324** [comment]
Looks like the question is answered, can you close this issue then @sandikata?
