### ISSUE TITLE
Shortcut to repeat last command?

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#1402]
Maybe Spacemacs can add a shortcut to repeat the last command? For example if I did an ACK search in the project, I might want to quickly repeat it.

Or is there any way to cycle through command history?

**Comment by tuhdo** [comment]
Is the `ack` search you were doing using Helm? If so, you can press `SPC h l` to resume last Helm session. If you Ack search is not the last active Helm session, you can add prefix argumente `C-u` to select one.

You can also press `f3` to store the search result into a buffer (or press `TAB` to open action buffer and select the 3rd one; `TAB` is replaced by `C-z` for opening action menu in next Spacemacs release), and use `M-n` or `M-p` to navigate next and previous match, `M-N` or `M-P` to go to next and previous file in the search buffer.

**Comment by x-ji** [comment]
I see. That applies to scenarios involving `helm` well. Thanks.

Also it seems that from this Stackoverflow question http://stackoverflow.com/questions/275842/is-there-a-repeat-last-command-in-emacs to repeat the last general command one can use `C-x z`, and to repeat the last "complex" command one can use `C-x Esc Esc`. To bring up complex command history one can use `M-x M-p`. Seems that commands like those of `Ido` can be repeated in this fashion.

**Comment by Spadavecchia** [comment]
The shorcut was changed from `SPC h l` to `SPC r l`

`SPC r` is the prefix to a wonderful collection of commands. Explore it.

**Comment by braham-snyder** [comment]
would it make sense for Spacemacs to bind <kbd>SPC</kbd> <kbd>.</kbd> to `repeat` (as in<kbd>C-x</kbd><kbd>z</kbd>)?

**Comment by MoHKale** [comment]
That would be nice, but it doesn't seem to work as well as I'd like. For example, if I use aya-create to create a snippet (SPC-i-S-c) and then auto-yasnippet-expand (SPC-i-S-e) I'd probably want to repeat auto-yasnippet-expand command multiple times. In current spacemacs, using repeat would just repeat the last literal command, which in this case would be evil-normal-state. Maybe we need to introduce a repeat command working exclusively on spacemacs-leader-keys or ignoring evil state changes?
