### ISSUE TITLE
Unable to redo after package update (user-error: Customize ‘evil-undo-system’)

### ISSUE THREAD

**Issue by Corentin-pro** [syl20bnr/spacemacs#14036]
#### Description :octocat:
Unable to redo (C-r) after package update

#### Reproduction guide :beetle:
- Start Emacs
- Open a file a switch to scratch buffer
- Do any modification
- Undo (u)
- Try to redo (C-r)

*Observed behaviour:* :eyes: :broken_heart:
No redo is done, a message is printed : 
```user-error: Customize ‘evil-undo-system’ for redo functionality.```

*Expected behaviour:* :heart: :smile:
Redo is done as usual

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(nginx php csv yaml ivy auto-completion better-defaults emacs-lisp git markdown syntax-checking
	   (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh")
	   (python :variables python-fill-column 120)
	   evil-commentary docker c-c++ semantic latex javascript react)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
https://github.com/emacs-evil/evil made undo-tree optional:
Make undo-tree an optional dependency emacs-evil/evil#1360

The Spacemacs `develop` branch has been updated to restore the previous undo-tree behavior
Set evil-undo-system to undo-tree #14026

The `develop` branch is the recommended branch until the next version is released (I have no insight into when that is).

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

A lot of stuff have been fixed/improved on the `develop` branch, but if you don't want to switch (yet), then try adding this to the `dotspacemacs/user-config` section of your `.spacemacs`.
```elisp
(global-undo-tree-mode)
(evil-set-undo-system 'undo-tree)
```

**Comment by allentiak** [comment]
I'm experiencing the same problem, with latest develop (0f65b000da93fcb258e146ff4718dae0d2fa4378).

**Comment by allentiak** [comment]
I can confirm the problem does not occur with 714512b. Git bisecting...

**Comment by allentiak** [comment]
@duianto According to `git bisect`, the broken commit is:
[e096d6dd1e947550ab2206847eb1c5fd5328e1d6] Set evil-undo-system to undo-tree

**Comment by allentiak** [comment]
Full `git bisect` output:
```
e096d6dd1e947550ab2206847eb1c5fd5328e1d6 is the first bad commit
commit e096d6dd1e947550ab2206847eb1c5fd5328e1d6
Author: duianto <otnaiud@gmail.com>
Date:   Fri Oct 9 10:05:49 2020 +0200

    Set evil-undo-system to undo-tree

 CHANGELOG.develop                                     |  1 +
 layers/+distributions/spacemacs-bootstrap/packages.el |  2 ++
 layers/+spacemacs/spacemacs-editing/packages.el       | 17 ++++++++++-------
 3 files changed, 13 insertions(+), 7 deletions(-)
```

**Comment by liny01-nbsa** [comment]
I found this issue when I do my routine spacemacs upgrade by 1) git pull on develop branch and 2) doing package update within Emacs. However after 1). I see an error of void-function of `evil-set-undo-system`. I have to comment the change to start Emacs. After 2), I can uncomment this change without issue.

**Comment by duianto** [comment]
The message when pressing `C-r`:
>user-error: Customize ‘evil-undo-system’ for redo functionality.

comes from: https://github.com/emacs-evil/evil 
As stated above because of:
Make undo-tree an optional dependency emacs-evil/evil#1360

I just tested the latest evil update without Spacemacs (only Emacs the `evil` package installed).
And `C-r` shows:
>user-error: Customize ‘evil-undo-system’ for redo functionality.

In Spacemacs on the latest `develop` branch with updated packages.

The evil undo system has been set to use `undo-tree`:
Set evil-undo-system to undo-tree #14026

` C-h l                  ;; view-lossage` (l = lower case L), shows:
```
 u                      ;; evil-undo
 C-r                    ;; evil-redo
 C-/                    ;; undo-tree-undo
 C-?                    ;; undo-tree-redo
```
`C-r` redoes a previous undo without showing the customize message.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0f65b000d)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm javascript lsp multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/"))
            python rust spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

### spacemacs-base
As mentioned in the PR:
Set evil-undo-system to undo-tree #14026 
The fix doesn't work on the `spacemacs-base` distribution at the moment (it's being investigated)

`undo-tree` isn't loaded by default, which results in:
```
evil-undo: Symbol’s function definition is void: undo-tree-undo
evil-redo: Symbol’s function definition is void: undo-tree-redo
Undo
C-? is undefined
```
---

The message:
>void-function of evil-set-undo-system

means that Spacemacs has been updated, but not the packages.

The customize message, could mean that the packages were updated but not Spacemacs.

Anyone seeing any issues, could you press `SPC h d s` to copy your system info to the clipboard.

**Comment by nickanderson** [comment]
I hit this today.

I pulled update from develop, spacemacs wouldnt start. I checked out the commit I was on before, spacemacs started, then I updated packages, checked out from develop again and things are working.

**Comment by adispring** [comment]
I also hit this problem. How to solve it?

**Comment by Fenton-Fenton** [comment]
> I also hit this problem. How to solve it?

I found that deleting .emacs.d then redownloading spacemacs and switching to develop branch fixed this issue (presumably because this forces a refresh of all local MELPA files?)

**Comment by duianto** [comment]
Anyone seeing un/redo related issues.

Press `SPC h d s` to copy your system info to the clipboard. Then paste it in a new comment.
Include any error messages.

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Only set undo system if fun. exists. #14043

**Comment by allentiak** [comment]
@duianto It seems your latest commit fixes the bug. Thanks a lot!

**Comment by allentiak** [comment]
@Corentin-pro @adispring 
Could you please also confirm whether latest `develop` works fine for you as well, please?

**Comment by adispring** [comment]
@allentiak Yes, the latest `develop` works fine already.

**Comment by Corentin-pro** [comment]
@allentiak Yes works here too

**Comment by Corentin-pro** [comment]
The problem reappeared today on develop branch, fixed with `(evil-set-undo-system 'undo-tree)` in the `dotspacemacs/user-config` section of the confifuration file/dotfile (SPC f e d)

**Comment by wolfand11** [comment]
@Corentin-pro when i add (evil-set-undo-system 'undo-tree) in the dotspacemacs/user-config section.
redo and undo all doesn't work. message display in Message buffer as below:
evil-redo: Symbol’s function definition is void: undo-tree-redo
evil-undo: Symbol’s function definition is void: undo-tree-undo

**Comment by allentiak** [comment]
@Corentin-pro @adispring
Thanks!

**Comment by lebensterben** [comment]
please reopen the issue if the exact same problem appears.
Otherwise please open a new issue.
