### ISSUE TITLE
lsp pyright errors

### ISSUE THREAD

**Issue by sdorof1** [syl20bnr/spacemacs#14041]
For the next code (which runs without errors):
```
import numpy as np
print (np.sign(-1))
```
I got the error with pyright in emacs:
```
"sign" is not a known member of module (lsp)
```
But if I run pyright in the shell, it doesn't report any errors:
```
pyr$ pyright pyr.py 
No configuration file found.
stubPath /home/sd/pyr/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
0 errors, 0 warnings, 0 infos 
Completed in 0.551sec
```

So, I get a some mystic error report. This is also in other cases, for example, when work with pandas, when no pyright, no vscode doesn't reports any errors.

The value of `lsp-pyright-typechecking-mode` is `basic` for all cases.

**Comment by beyondpie** [comment]
Maybe you need to ask this issue in lsp-pyright repo. This seems to be not a spacemacs issue.

**Comment by smile13241324** [comment]
I require some more information about your config and system. Especially I would like to have the debug infos from `spacemacs/report-issue`. Also I would like to know what LSP server you are using.

**Comment by sdorof1** [comment]
> I require some more information about your config and system. Especially I would like to have the debug infos from `spacemacs/report-issue`. Also I would like to know what LSP server you are using.

I use pyright 1.1.78, emacs  26.3 and spacemacs from `develop` branch. The issue because `lsp-pyright`, as them [say](https://github.com/emacs-lsp/lsp-pyright/issues/30), enable the `useLibraryCodeForTypes`, but for full code completion need to use type stubs. So, may be this issue can be an idea about further improvement of default configuration. And apparently can be closed.

**Comment by smile13241324** [comment]
Ok, then I will close it.
