### ISSUE TITLE
Further beautify Spacemacs home buffer with magic-buffer

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1404]
Homepage for demo: https://github.com/sabof/magic-buffer

Do you see the table in the screenshot? It would be nicer to replace current text frame for display release note and quick help with a proper table like in the screenshot. The code for the table example is at [magic-buffer:1015](https://github.com/sabof/magic-buffer/blob/master/magic-buffer.el#L1015). As you see, a table is very easy to create.

**Comment by CarlQLange** [comment]
:+1:

**Comment by tuhdo** [comment]
Or actually we don't have to remove anything since we still need the table string for rendering anyway. I think the `magic-buffer` above is not an actual package but rather a demo on how Emacs can render text. If so, we can study it and apply for Spacemacs.

**Comment by syl20bnr** [comment]
If I understand correctly this is a demo of how to render text in emacs buffer. We can indeed beautify the frame with propertized text.
