### ISSUE TITLE
vue layer: vls keeps throwing code action errors

### ISSUE THREAD

**Issue by NANASHI0X74** [syl20bnr/spacemacs#14044]
#### Description :octocat:
vue-mode vls langserver keeps throwing errors:
`LSP :: Error from the Language Server: Request textDocument/codeAction failed with message: Cannot read property 'codeActions' of undefined (Internal Error) [3 times]`

This is similar to: https://github.com/vuejs/vetur/issues/2355
which is supposedly fixed by https://github.com/emacs-lsp/lsp-mode/commit/46d1a7e4029fb141d41504095e0e10741c7fb624
but I'm not sure how to find out which version of lsp-mode emacs and the vue layer is using? :sweat_smile: 

#### Reproduction guide :beetle:
- install vls with npm install -D vls
- start Emacs
- open *.vue file

*Observed behaviour:* :eyes: :broken_heart:
- the lsp keeps throwing these errors and spamming my messages buffer
- code actions don't work

*Expected behaviour:* :heart: :smile:
- lsp is quiet :D
- ideally code actions also work

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: PATCH-1 (rev. c9265e32f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python yaml sql auto-completion helm better-defaults emacs-lisp nixos git github helm lsp
        (node :variables node-add-modules-path t)
        multiple-cursors org
        (vue :variables vue-backend 'lsp)
        (typescript :variables typescript-backend 'tide)
        (javascript :variables javascript-backend 'tide javascript-fmt-tool 'prettier javascript-fmt-on-save t)
        (html :variables css-enable-lsp t less-enable-lsp t html-enable-lsp t scss-enable-lsp t web-fmt-tool 'prettier)
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP
- I'm also using nixos and the elvish shell

#### Backtrace :paw_prints:
none

**Comment by thanhvg** [comment]
If there is an update from upstream then you need to update your packages. `SPC b h` then click or enter on `[Update Packages]`

**Comment by duianto** [comment]
I'm not seeing any errors on the latest `develop` branch with updated packages.
With this `example.vue` file:
```vue
<div id="app">
<h1>{{ message }}</h1>
</div>

<script>
var myObject = new Vue({
    el: '#app',
    data: {message: 'Hello Vue!'}
})
</script>
```

You can view your lsp-mode version in:
`~/.emacs.d/elpa/27.1/develop/lsp-mode-20201016.1633/lsp-mode.el`

Currently it's: `;; Version: 7.1.0`

<details><summary>
Manjaro, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f2b17d8cd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm lsp multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            rust spell-checking syntax-checking version-control
            (vue :variables vue-backend 'lsp)
            treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

</pre>
</details>

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ac3c3546a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey emacs-lisp
            (erlang :variables erlang-enable-lsp-mode t)
            git ivy javascript lsp multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/")
                 org-enable-jira-support t org-enable-roam-support t)
            python rust shell spell-checking syntax-checking version-control treemacs
            (vue :variables vue-backend 'lsp)
            yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by NANASHI0X74** [comment]
thanks, updating packages fixed it :see_no_evil:
