### ISSUE TITLE
unable to do fresh install, Package 'xxx' is unavailable. Is the package name misspelled?

### ISSUE THREAD

**Issue by osfe** [syl20bnr/spacemacs#14040]
Hi there, 
I try to make fresh install on a new machine 
$ git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d && emacs
down to this message is the trace
emacs version 27.1

thank you very much for your help

Olivier 

Found 90 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: ace-jump-helm-line@helm... [1/90]
Package ace-jump-helm-line is unavailable. Is the package name misspelled?
--> installing package: ace-link@spacemacs-ui... [2/90]
Package ace-link is unavailable. Is the package name misspelled?
--> installing package: ace-window@spacemacs-base... [3/90]
Package ace-window is unavailable. Is the package name misspelled?
--> installing package: adaptive-wrap@spacemacs-editing-visual... [4/90]
Package adaptive-wrap is unavailable. Is the package name misspelled?
--> installing package: aggressive-indent@spacemacs-editing... [5/90]
Package aggressive-indent is unavailable. Is the package name misspelled?
--> installing package: async@spacemacs-bootstrap... [6/90]
Package async is unavailable. Is the package name misspelled?
--> installing package: auto-compile@emacs-lisp... [7/90]
Package auto-compile is unavailable. Is the package name misspelled?
--> installing package: auto-highlight-symbol@spacemacs-editing-visual... [8/90]
Package auto-highlight-symbol is unavailable. Is the package name misspelled?
--> installing package: avy@spacemacs-editing... [9/90]
Package avy is unavailable. Is the package name misspelled?
--> installing package: bind-key@spacemacs-bootstrap... [10/90]
Package bind-key is unavailable. Is the package name misspelled?
--> installing package: bind-map@spacemacs-bootstrap... [11/90]
Package bind-map is unavailable. Is the package name misspelled?
--> installing package: clean-aindent-mode@spacemacs-editing... [12/90]
Package clean-aindent-mode is unavailable. Is the package name misspelled?
--> installing package: column-enforce-mode@spacemacs-editing-visual... [13/90]
Package column-enforce-mode is unavailable. Is the package name misspelled?
--> installing package: define-word@spacemacs-language... [14/90]
Package define-word is unavailable. Is the package name misspelled?
--> installing package: diminish@spacemacs-bootstrap... [15/90]
Package diminish is unavailable. Is the package name misspelled?
--> installing package: dumb-jump@spacemacs-misc... [16/90]
Package dumb-jump is unavailable. Is the package name misspelled?
--> installing package: elisp-slime-nav@emacs-lisp... [17/90]
Package elisp-slime-nav is unavailable. Is the package name misspelled?
--> installing package: eval-sexp-fu@spacemacs-editing... [18/90]
Package eval-sexp-fu is unavailable. Is the package name misspelled?
--> installing package: evil@spacemacs-bootstrap... [19/90]
Package evil is unavailable. Is the package name misspelled?
--> installing package: evil-anzu@spacemacs-evil... [20/90]
Package evil-anzu is unavailable. Is the package name misspelled?
--> installing package: evil-args@spacemacs-evil... [21/90]
Package evil-args is unavailable. Is the package name misspelled?
--> installing package: evil-ediff@spacemacs-evil... [22/90]
Package evil-ediff is unavailable. Is the package name misspelled?
--> installing package: evil-escape@spacemacs-base... [23/90]
Package evil-escape is unavailable. Is the package name misspelled?
--> installing package: evil-exchange@spacemacs-evil... [24/90]
Package evil-exchange is unavailable. Is the package name misspelled?
--> installing package: evil-iedit-state@spacemacs-evil... [25/90]
Package evil-iedit-state is unavailable. Is the package name misspelled?
--> installing package: evil-indent-plus@spacemacs-evil... [26/90]
Package evil-indent-plus is unavailable. Is the package name misspelled?
--> installing package: evil-lisp-state@spacemacs-evil... [27/90]
Package evil-lisp-state is unavailable. Is the package name misspelled?
--> installing package: evil-matchit@spacemacs-evil... [28/90]
Package evil-matchit is unavailable. Is the package name misspelled?
--> installing package: evil-mc@spacemacs-evil... [29/90]
Package evil-mc is unavailable. Is the package name misspelled?
--> installing package: evil-nerd-commenter@spacemacs-evil... [30/90]
Package evil-nerd-commenter is unavailable. Is the package name misspelled?
--> installing package: evil-numbers@spacemacs-evil... [31/90]
Package evil-numbers is unavailable. Is the package name misspelled?
--> installing package: evil-search-highlight-persist@spacemacs-evil... [32/90]
Package evil-search-highlight-persist is unavailable. Is the package name misspelled?
--> installing package: evil-surround@spacemacs-evil... [33/90]
Package evil-surround is unavailable. Is the package name misspelled?
--> installing package: evil-tutor@spacemacs-evil... [34/90]
Package evil-tutor is unavailable. Is the package name misspelled?
--> installing package: evil-visual-mark-mode@spacemacs-evil... [36/90]
Package evil-visual-mark-mode is unavailable. Is the package name misspelled?
--> installing package: evil-visualstar@spacemacs-base... [37/90]
Package evil-visualstar is unavailable. Is the package name misspelled?
--> installing package: exec-path-from-shell@spacemacs-base... [38/90]
Package exec-path-from-shell is unavailable. Is the package name misspelled?
--> installing package: expand-region@spacemacs-editing... [39/90]
Package expand-region is unavailable. Is the package name misspelled?
--> installing package: eyebrowse@spacemacs-layouts... [40/90]
Package eyebrowse is unavailable. Is the package name misspelled?
--> installing package: fancy-battery@spacemacs-ui-visual... [41/90]
Package fancy-battery is unavailable. Is the package name misspelled?
--> installing package: fill-column-indicator@spacemacs-ui-visual... [42/90]
Package fill-column-indicator is unavailable. Is the package name misspelled?
--> installing package: flx-ido@spacemacs-ui... [43/90]
Package flx-ido is unavailable. Is the package name misspelled?
--> installing package: golden-ratio@spacemacs-ui-visual... [44/90]
Package golden-ratio is unavailable. Is the package name misspelled?
--> installing package: google-translate@spacemacs-language... [45/90]
Package google-translate is unavailable. Is the package name misspelled?
--> installing package: helm@helm... [46/90]
Package helm is unavailable. Is the package name misspelled?
--> installing package: helm-ag@helm... [47/90]
Package helm-ag is unavailable. Is the package name misspelled?
--> installing package: helm-descbinds@helm... [48/90]
Package helm-descbinds is unavailable. Is the package name misspelled?
--> installing package: helm-flx@helm... [49/90]
Package helm-flx is unavailable. Is the package name misspelled?
--> installing package: helm-make@helm... [50/90]
Package helm-make is unavailable. Is the package name misspelled?
--> installing package: helm-mode-manager@helm... [51/90]
Package helm-mode-manager is unavailable. Is the package name misspelled?
--> installing package: helm-projectile@helm... [52/90]
Package helm-projectile is unavailable. Is the package name misspelled?
--> installing package: helm-swoop@helm... [53/90]
Package helm-swoop is unavailable. Is the package name misspelled?
--> installing package: helm-themes@helm... [54/90]
Package helm-themes is unavailable. Is the package name misspelled?
--> installing package: highlight-indentation@spacemacs-editing-visual... [55/90]
Package highlight-indentation is unavailable. Is the package name misspelled?
--> installing package: highlight-numbers@spacemacs-editing-visual... [56/90]
Package highlight-numbers is unavailable. Is the package name misspelled?
--> installing package: highlight-parentheses@spacemacs-editing-visual... [57/90]
Package highlight-parentheses is unavailable. Is the package name misspelled?
--> installing package: hl-todo@spacemacs-ui-visual... [58/90]
Package hl-todo is unavailable. Is the package name misspelled?
--> installing package: hungry-delete@spacemacs-editing... [59/90]
Package hungry-delete is unavailable. Is the package name misspelled?
--> installing package: hydra@spacemacs-bootstrap... [60/90]
Package hydra is unavailable. Is the package name misspelled?
--> installing package: indent-guide@spacemacs-editing-visual... [61/90]
Package indent-guide is unavailable. Is the package name misspelled?
--> installing package: link-hint@spacemacs-editing... [62/90]
Package link-hint is unavailable. Is the package name misspelled?
--> installing package: linum-relative@spacemacs-evil... [63/90]
Package linum-relative is unavailable. Is the package name misspelled?
--> installing package: lorem-ipsum@spacemacs-editing... [64/90]
Package lorem-ipsum is unavailable. Is the package name misspelled?
--> installing package: macrostep@emacs-lisp... [65/90]
Package macrostep is unavailable. Is the package name misspelled?
--> installing package: move-text@spacemacs-editing... [66/90]
Package move-text is unavailable. Is the package name misspelled?
--> installing package: neotree@spacemacs-ui-visual... [67/90]
Package neotree is unavailable. Is the package name misspelled?
--> installing package: open-junk-file@spacemacs-ui... [68/90]
Package open-junk-file is unavailable. Is the package name misspelled?
--> installing package: org-bullets@spacemacs-org... [69/90]
Package org-bullets is unavailable. Is the package name misspelled?
--> installing package: org-plus-contrib@spacemacs-org... [70/90]
Package org-plus-contrib is unavailable. Is the package name misspelled?
--> installing package: paradox@spacemacs-ui... [71/90]
Package paradox is unavailable. Is the package name misspelled?
--> installing package: pcre2el@spacemacs-base... [72/90]
Package pcre2el is unavailable. Is the package name misspelled?
--> installing package: persp-mode@spacemacs-layouts... [73/90]
Package persp-mode is unavailable. Is the package name misspelled?
--> installing package: popup@spacemacs-ui-visual... [74/90]
Package popup is unavailable. Is the package name misspelled?
--> installing package: popwin@spacemacs-ui-visual... [75/90]
Package popwin is unavailable. Is the package name misspelled?
--> installing package: projectile@spacemacs-base... [76/90]
Package projectile is unavailable. Is the package name misspelled?
--> installing package: rainbow-delimiters@spacemacs-editing-visual... [77/90]
Package rainbow-delimiters is unavailable. Is the package name misspelled?
--> installing package: request@spacemacs-misc... [78/90]
Package request is unavailable. Is the package name misspelled?
--> installing package: restart-emacs@spacemacs-ui... [79/90]
Package restart-emacs is unavailable. Is the package name misspelled?
--> installing package: smartparens@spacemacs-editing... [80/90]
Package smartparens is unavailable. Is the package name misspelled?
--> installing package: spaceline@spacemacs-ui-visual... [81/90]
Package spaceline is unavailable. Is the package name misspelled?
--> installing package: toc-org@spacemacs-org... [82/90]
Package toc-org is unavailable. Is the package name misspelled?
--> installing package: undo-tree@spacemacs-editing... [83/90]
Package undo-tree is unavailable. Is the package name misspelled?
--> installing package: use-package@spacemacs-bootstrap... [84/90]
Package use-package is unavailable. Is the package name misspelled?
--> installing package: uuidgen@spacemacs-editing... [85/90]
Package uuidgen is unavailable. Is the package name misspelled?
--> installing package: vi-tilde-fringe@spacemacs-evil... [86/90]
Package vi-tilde-fringe is unavailable. Is the package name misspelled?
--> installing package: volatile-highlights@spacemacs-editing-visual... [87/90]
Package volatile-highlights is unavailable. Is the package name misspelled?
--> installing package: which-key@spacemacs-bootstrap... [88/90]
Package which-key is unavailable. Is the package name misspelled?
--> installing package: winum@spacemacs-ui... [89/90]
Package winum is unavailable. Is the package name misspelled?
--> installing package: ws-butler@spacemacs-editing... [90/90]
Package ws-butler is unavailable. Is the package name misspelled?

**Comment by osfe** [comment]
I guess it was something else. I restarted my computer, i did the same thing and now it works. Sorry for that...

**Comment by devurandom** [comment]
This problem also appears with recent versions of Emacs and Spacemacs. A workaround seems to be to disable TLSv1.3.

See-also: https://github.com/syl20bnr/spacemacs/issues/16122
