### ISSUE TITLE
Python closing brackets alignment

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#14053]
#### Description :octocat:
If I type the follwoing:
```python
    data = {
       "test": "test",
```

and hit enter after the comma, the closing bracket will be indented like so (and often emacs will try to fix it if I hit backspace and type a space or a comma or something), so it looks like this:

```python
    data = {
       "test": "test", 
        }
```

How do I get it to want to align the closing bracket, parens, braces, whatever, like this:

```python
    data = {
       "test": "test", 
    }
````

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ac3c3546a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(perl5 go swift csv lua nginx sql auto-completion emacs-lisp git yaml javascript html markdown major-modes python org osx python ipython-notebook django syntax-checking spell-checking colors spacemacs-layouts vimscript helm
       (version-control :variables version-control-diff-tool 'diff-hl)
       (c-c++ :variables c-c++-enable-clang-support t)
       (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by beyondpie** [comment]
I also have this sometimes. I then use reformat the buffer/file supported by lsp-pyright to format the codes. Could this be a temp help for your situation?

**Comment by synic** [comment]
Well, I have a workaround, and that's just to fix it manually. It's not a big deal, just sort of annoying

**Comment by lebensterben** [comment]
@synic
Can you share your workaround?

**Comment by synic** [comment]
I don't have the original method, I eventually stumbled on this solution which was easier: https://github.com/synic/dotspacemacs/commit/5558c3c65b1f27e4cfd44db3d38e00e91d225105#diff-82c647c7e6a8e02d1b94a30268eb483ff5aadf926762a759fcd0f4c5850356bfR691

It's not perfect (there are still situations where I feel like it does the wrong thing), but it is better.

Haven't had to deal with it as much since I started using black.

**Comment by lebensterben** [comment]
@synic 
If you want, you can set `dotspacemacs-activate-smartparens-mode t` in `.spacemacs`.
