### ISSUE TITLE
Telega: huge rendering slow down when sending message

### ISSUE THREAD

**Issue by firmart** [syl20bnr/spacemacs#14061]
This is a cross-issue coming from [telega](https://github.com/zevlg/telega.el/issues/206). Current progress, configuration and build are updated. This issue is not observed with `emacs -Q`.

## Current Behavior

- Sending message in `telega` causes a rendering infinite loop (however, the message is sent instantly).
- The issue gone with `emacs -Q`
```
emacs -Q -l ~/.emacs.d/elpa/28.0/develop/telega-20200903.1506/telega-autoloads.el -l ~/.emacs.d/elpa/28.0/develop/rainbow-identifiers-20141102.1526/rainbow-identifiers.el -l  ~/.emacs.d/elpa/28.0/develop/visual-fill-column-20200428.816/visual-fill-column-autoloads.el
```
- Disable `symbol-overlay` (*i.e.* put it in `dotspacemacs-excluded-packages`) seems improve the infinite rendering to a 30s delay.

## Steps to Reproduce

1. Reinstall `telega.el`, `telega-server` and `TDLib` to the version stated below. (I cleared `~/.telega` and the installed Melpa package, and reinstalled automatically `telega.el` through `use-package` and `telega-server` through `telega` (step 3)).
2. `M-x telega`
3. Setup `telega`: install `telega-server` and `VoIP` (replied `y` and `y`), setup phone number & login code.
4. Everything fetches correctly, send a message to anyone: infinite loop. 

## System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50 (2020.10.26)
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2ce32b461)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(rust html alda
      (auto-completion :variables auto-completion-private-snippets-directory "~/.emacs.d/snippets/" auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-tab-key-behavior nil)
      themes-megapack better-defaults emacs-lisp games git
      (ivy :variables ivy-enable-advanced-buffer-information t)
      markdown multiple-cursors notmuch org selectric spell-checking syntax-checking
      (treemacs :variables treemacs-use-follow-mode 'tag treemacs-use-filewatch-mode t treemacs-use-git-mode 'deferred treemacs-use-all-the-icons-theme t)
      version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD PDUMPER LCMS2

**Comment by lebensterben** [comment]
@firmart 
I saw the upstream issue is closed as you've found a solution yourself.
Unfortunately stackexchange is currently having some issue so I'm not able to check that right now.

Is this issue still relevant in Spacemacs?
If it requires some fixes, can you share them?
