### ISSUE TITLE
(How) can I paste in the helm-find-file prompt?

### ISSUE THREAD

**Issue by NANASHI0X74** [syl20bnr/spacemacs#14063]
Sometimes I want to pase something after doing `SPC f f`, and in other prompts as well, like cloning git repositories, but I can't figure out how... Or is this not possible?

**Comment by NANASHI0X74** [comment]
ctrl-v or ctrl-shift-v doesn't work for me

**Comment by kylesnowschwartz** [comment]
Try `ctrl+y` when in those modes. I can't remember how I found this trick, but it's surely documented somewhere.

**Comment by duianto** [comment]
`C-y` is the default Emacs key binding for yank (paste).
https://www.gnu.org/software/emacs/manual/html_node/emacs/Yanking.html

The word `yank` can be confusing if one uses the package: https://github.com/emacs-evil/evil

Emacs uses `yank` for inserting (pasting) the last killed (copied or cut) text:
>Yanking means reinserting text previously killed. The usual way to move or copy text is to kill it and then yank it elsewhere.
>
>C-y
>Yank the last kill into the buffer, at point (yank).

While Vim (and therefore also emacs-evil) uses `yank` for copy:
https://vim.fandom.com/wiki/Copy,_cut_and_paste
>y stands for yank in Vim, which in other editors is usually called copy

**Comment by NANASHI0X74** [comment]
thanks, yes, C-y works.
