### ISSUE TITLE
Opening python file and editiong org-babel python-code-blocks slow due to ipython

### ISSUE THREAD

**Issue by moritzschaefer** [syl20bnr/spacemacs#14065]
#### Description :octocat:
When using anaconda mode in the python layer, opening python files is slow (~1 second).

Also, when editing babel python-code blocks, completion is very slow (~1 second). This is connected to opening a python buffer, since org-babel calls the major-mode completion function for python, which requires org to open a python buffer in the background, which again takes 1 second.

Worsening matters, a newline in an org-babel source code block indirectly calls org-indent-line, which leads to execution of a TAB keypress within a newly opened background python buffer, which again takes 1 second. So pressing RETURN always takes one second.

The issue is that ipython takes 1 second to start and opening a python buffer starts a new ipython process. Evidence I found for this is that the emacs profiler doesn't report anything happening in this 1 second (so it must be an external process). Also, when artifically slowing down the ipython startup (time.sleep(5) in ipython_config.py), opening a python buffer also becomes slower.

A workaround is to set ´org-src-tab-acts-natively´ to nil, however of course I would like to have code completion within org babel python code blocks.

I wonder if the issue is that my ipython starts so slow or if opening a new python file should use an existing ipython buffer. A fix could also be that python is used instead of ipython.

#### Reproduction guide :beetle:
- Install spacemacs with python (anaconda backend)
- Open a python file
- Create a python code block within an org file

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
- Pressing return in the code block and opening the python files takes as long, as starting an ipython console.

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>
- <0.2 s delay for these actions

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 714512b13)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(shell-scripts systemd org-roam c-c++ dap lsp ruby nginx nixos
               w3m clojure latex rust
               (exwm :variables exwm-enable-systray t exwm-use-autorandr t exwm-autostart-xdg-applications t exwm-locking-command "slock" exwm-randr-workspace-monitor-plist
                     '(0 "eDP1" 1 "HDMI1" 2 "DP2" 3 "eDP1" 4 "eDP1" 5 "eDP1")
                     exwm-terminal-command "urxvt")
               csv yaml react typescript javascript html themes-megapack
               (python :variables python-backend 'anaconda python-enable-yapf-format-on-save t python-sort-imports-on-save t)
               helm
               (auto-completion :disabled-for org spacemacs-org :variables auto-completion-return-key-behavior 'nil auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
               pdf better-defaults latex emacs-lisp git ipython-notebook ess github markdown syntax-checking
               (org :variables org-projectile-file "TODOs.org")
               bibtex
               (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/run/current-system/sw/bin/fish" shell-default-height 30 shell-default-position 'bottom)
               spell-checking pass)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by moritzschaefer** [comment]
I found, that the reason why ipython is called, is that I had set python-shell-interpreter to "ipython" some time ago. However, this is recommended by several sources depending on the use case (https://www.emacswiki.org/emacs/PythonProgrammingInEmacs#toc30, https://stackoverflow.com/questions/17817019/how-to-open-ipython-interpreter-in-emacs). 
I myself would also like to benefit from the feaures of the ipython interpreter, however not with the 1 second lag

**Comment by brandonwillard** [comment]
Here's a shot in the dark: [`ipython --version`](https://github.com/syl20bnr/spacemacs/issues/13264#issuecomment-600316367) is/was slow.

**Comment by moritzschaefer** [comment]
The issue really is to use ipython as python-shell-interpreter in the first place. I close this for now since there doesn't seem to be a solution for having both, fast completion and ipython as shell-interpreter. 

I hope the issue serves as reference for future googlers
