### ISSUE TITLE
How can I load a minor mode on startup?

### ISSUE THREAD

**Issue by NANASHI0X74** [syl20bnr/spacemacs#14066]
I'm trying to use
https://github.com/wbolster/emacs-direnv
I added it to dotspacemacs-additional-packages and put direnv-mode in my dotspacemacs/user-config.
Now when I open a file, direnv-mode isn't activated by default, I have to do that manually. Should it not be enabled by the user-config code?

**Comment by NANASHI0X74** [comment]
for reference, the relevant parts of my config look like:
```elisp
   dotspacemacs-additional-packages
   '(direnv)
;;...
(defun dotspacemacs/user-config ()
  direnv-mode
  global-company-mode
  )
```

**Comment by emacs18** [comment]
The two symbols seem to be function which I think you meant to call.  If so, you need to parenthesis, e.g.,
```elisp
(direnv-mode)
(global-company-mode)
```

**Comment by NANASHI0X74** [comment]
ah, thank you :sweat_smile: yeah, that's me being a big n00b in elisp
