### ISSUE TITLE
With ripgrep installed, resume-last-search-buffer switches back to ag when search expression edited

### ISSUE THREAD

**Issue by gondalez** [syl20bnr/spacemacs#14079]
#### Description :octocat:
Using `resume-last-search-buffer` when `rg` is installed switches back to `ag` on edit of the search expression.

#### Reproduction guide :beetle:
- Have `rg` installed on your system
- Start Emacs
- Open a project
- `SPC /`
- enter `* --version`
- exit search
- `SPC s l` to `resume-last-search-buffer`
- edit search term to delete `--version`
- add `--version` back on to search term

*Observed behaviour:* :eyes: :broken_heart:
- search output shows `ag` outputting its version:
```
ag version 2.2.0
Features:
  +jit +lzma +zlib
```

*Expected behaviour:* :heart: :smile:
- search output shows `rg` outputting its version:
```
ripgrep 12.1.1
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### Repro in gif format 😌 

![CleanShot 2020-10-22 at 10 57 24](https://user-images.githubusercontent.com/1468141/96819809-190e2600-1457-11eb-90e7-627919e8189a.gif)

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 76849892e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm org
            (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'vterm)
            version-control treemacs html yaml javascript react prettier
            (ruby :variables ruby-test-runner 'rspec)
            cucumber auto-completion git github markdown org syntax-checking terraform emoji templates)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by thanhvg** [comment]
Yeah this is a hard one. But if you don't care about other search tools like ag, pt.... Set `rg` as your default search tool on your dot spacemacs and it will solve your specific use case:

```` elisp
(setq helm-ag-base-command "rg --smart-case --no-heading --color=never --line-number --max-columns=150")
````

**Comment by gondalez** [comment]
That works nicely. Thanks @thanhvg 😌

**Comment by lebensterben** [comment]
I will tackle this at some time.
I already have an unmerged PR that rewrite the helm buffer but it was from 2 years ago.
