### ISSUE TITLE
helm-buffer too small

### ISSUE THREAD

**Issue by mijoharas** [syl20bnr/spacemacs#1407]
I think sometime since yesterday the `helm` buffer got a lot smaller. Has anyone else noticed this and do people agree? I'd say the buffer should be maybe a third of the vertical height of the screen. What are everyones thoughts on this?

**Comment by tuhdo** [comment]
I think if people have no problem with Ido, they would have no problem with Helm buffer at current height. This could easily be fixed by changing the popwin height for Helm window to 0.35 (35% of frame height) though.

**Comment by mijoharas** [comment]
You're right in general, but I quite like having a larger frame for certain things (e.g. when I'm doing `SPC /` I like to see a good chunk of them at once). do you know what the function it should be @tuhdo? I might mess about with it in the mean time to see what it feels like.

**Comment by tuhdo** [comment]
You can change the height specification for Helm buffers:

```elisp
(push '("^\*helm.+\*$" :regexp t :height 0.4) popwin:special-display-config)
```

Now Helm buffer is displayed with 40% frame height window.

**Comment by mijoharas** [comment]
Ahhh, I didn't know that was one of the options. OK, I think a third of the screen should be taken up, as that looks right to me (maybe a little more might be good).

Let me know what everyone elses opinion is.

**Comment by luxbock** [comment]
+1 for making 1/3 the default height.

**Comment by syl20bnr** [comment]
+1

**Comment by trishume** [comment]
I also experience this problem in develop when I have many vertically stacked windows. I eval'd that code snippet but it didn't solve the problem.

**Comment by tuhdo** [comment]
@trishume do you mean the PR?

**Comment by tuhdo** [comment]
The PR works for me. Even if I have 10 vertically stacked windows, Helm always remains the same height. Maybe you mean the code snippet in this issue? It didn't work.

**Comment by trishume** [comment]
@tuhdo I meant the `(push '("^\*helm.+\*$" :regexp t :height 0.4) popwin:special-display-config)`. I haven't tried the PR.

**Comment by syl20bnr** [comment]
Should now have the ratio 0.4 of total height.

**Comment by mijoharas** [comment]
what's the protocol for issues that are fixed in develop? do we leave them open until we merge with master or do we close them when it's verified fixed? (just asking because as far as I'm concerned this is fixed, but I tend to use develop)
