### ISSUE TITLE
issue with latex within Spacemacs

### ISSUE THREAD

**Issue by xyderos** [syl20bnr/spacemacs#14080]
Hi,

I am posting this in the form specified in Spacemacs since I am new and I don't know yet how to report a problem(or send it actually via spacemacs).

#### Description :octocat:
Issue with latex in spacemacs
#### Reproduction guide :beetle:
- Start Emacs
I am running spacemacs within terminal and i am currently trying to learn latex.
*Observed behaviour:* :eyes: :broken_heart:
When i tried to build a .tex file via SPC m b i get an eror message "Wrong type argument: stringp, nil"
*Expected behaviour:* :heart: :smile:
Probably build the .tex file and output eeither an error message or print the .pdf file if built successfully.
#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(clojure markdown helm better-defaults latex
         (latex :variables latex-build-command "pdflatex" latex-enable-auto-fill t magic-latex-enable-block-highlight t magic-$
         c-c++
         (c-c++ :variables c-c++-backend 'lsp-clangd c-c++-lsp-enable-semantic-highlight 'rainbow c-c++-lsp-semantic-highlight$
         emacs-lisp git spell-checking syntax-checking version-control auto-completion
         (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'cycle auto-c$
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES TH$

**Comment by smile13241324** [comment]
I am working a lot with latex in spacemacs, given the used latex mode is old but normally it works as it should. In your case I assume that the configuration for your latex-build-command is wrong, can you verify that pdflatex is available from spacemacs?

I.e. from develop branch, which I would suggest to switch to as master is currently frozen and horribly outdated, you can use this config to verify whether the error comes from the build command:
``` ebill
     (latex :variables
            latex-enable-auto-fill t
            latex-enable-magic nil
            latex-enable-folding t)
```
With this in your dotfile and after a spacemacs restart + properly installed latex on your system which must be in the path. Then do `, b` in a buffer for your .tex file. This should result in something like
``` ebill
Type ‘C-c C-l’ to display results of compilation.
LatexMk: successfully formatted {2} pages
```

**Comment by xyderos** [comment]
Hello,

Yes, the pdflatex is working(when I am opening it on the terminal(how to check if it is available from spacemacs?) I am getting into an interactive mode where I can specify my files name).

I will switch to develop branch to see if there is a difference there.

I installed latex via this link (http://www.tug.org/mactex/) , correct me if I am wrong, but as I understood, this pkg installs all the dependencies and need to do nothing else(as I mentioned before, I can see the executable running from the terminal)

Thanks in advance!

**Comment by smile13241324** [comment]
You can check whether it can be found from Spacemacs by opening a terminal in spacemacs with `SPC '` and try to run it from there. You can also check your environment file with `SPC f e e` and see whether the executable is in your path. 

About your tex distribution I am not familiar with this package but if you have the executable in your terminal it should be ok.
You can also try to manually choose a build system interactively and see whether this works when for example you call `latexmk`.

Waiting for your reply.

**Comment by xyderos** [comment]
Hello,

Thanks for your response, I actually fixed the issue by switching to the development branch, nothing else needed.

Thanks for your help!!!
