### ISSUE TITLE
helm-swoop scrolling is broken

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#1409]
I suspect this might be related to the recent helm pop-win change?

Before when I would scroll through the candidates in helm-swoop, the point in buffer would follow along, allowing one to see the context of the matches nicely. Now the other window gets scrolled instead.

**Comment by tuhdo** [comment]
@luxbock do you have a recipe? I cannot reproduce it. What is the window layout you are using?

**Comment by luxbock** [comment]
Seems like you confirmed the issue? I get it with stock Spacemacs configuration, if I have more than two windows open.

**Comment by tuhdo** [comment]
Yes, the referenced PR there is for fixing this.
