### ISSUE TITLE
Magit + Transient not working on fresh install on WSL (Emacs 27.1)

### ISSUE THREAD

**Issue by samcoy3** [syl20bnr/spacemacs#14092]
#### Description :octocat:
On a fresh install of spacemacs in WSL, running various commands in magit provides the error:
"transient--emergency-exit: Wrong type argument: transient-suffix, #s(transient-switch 1 nil nil nil nil nil nil nil nil ...), object"

#### Reproduction guide :beetle:
- Start Emacs
- Navigate to a git project
- Attempt to commit/push/add remote
- Error should appear

*Observed behaviour:* :eyes: :broken_heart:
Error appears at bottom of screen

*Expected behaviour:* :heart: :smile:
magic opens the commit/push/remote menu

#### System Info :computer:
- OS: Ubuntu (via WSL)
- Emacs: 27.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(csv yaml auto-completion better-defaults bibtex emacs-lisp git ivy markdown
     (latex :variables latex-build-command "LatexMk" latex-enable-auto-fill nil)
     (org :variables org-enable-github-support t)
     pandoc spell-checking syntax-checking version-control clojure
     (haskell :variables haskell-enable-hindent-style "gibiansky")
     html python xkcd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by duianto** [comment]
I have never tried WSL, but I'm not seeing any of those issues on the Spacemacs `develop` branch.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3eb66f4ce)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey clojure emacs-lisp git helm javascript lsp multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/")
                 org-enable-jira-support t org-enable-roam-support t)
            python shell spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

`develop` is the recommended branch until the next version is released (I have no insight into when that is).

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Comment by samcoy3** [comment]
Thank you, I can confirm that this works on the develop branch.
