### ISSUE TITLE
Automatically launch certain packages when editing files with certain extensions.

### ISSUE THREAD

**Issue by kmabadshah** [syl20bnr/spacemacs#14095]
When I'm using any .js file, I would like to have rjsx-mode enabled by default. How can I achieve this? As of now, I have to manually enable it everytime I open a new file.

**Comment by lebensterben** [comment]
> rjsx-mode automatically registers itself for *.jsx files, but you can use (add-to-list 'auto-mode-alist '("components\\/.*\\.js\\'" . rjsx-mode))

https://github.com/felipeochoa/rjsx-mode
