### ISSUE TITLE
[question] is it possible to set the font size of the modeline to a different font than the main editor?

### ISSUE THREAD

**Issue by 3n-k1** [syl20bnr/spacemacs#14106]
i know this isn't really the place to ask, but i can't find anything online and it seems nobody really knows the answer to this

i'd like to set the font (specifically font size) of my modeline window to something different than the main editor window. is that at all possible to do? i've found some seemingly-related stuff by googling, but nothing that's actually worked

if there's no way to do this please feel free to just close this issue. thanks!

**Comment by lebensterben** [comment]
`M-x customize-face`, type `mode-line`, and enter.
In the new window, press enter on `Show All Attributes`, and you can set a scaling factor for the height.

**Comment by 3n-k1** [comment]
i can't seem to find the `Show All Attributes` bit, am i missing something?
![image](https://user-images.githubusercontent.com/51172302/97829277-93c91380-1c97-11eb-8034-09f5b42f55af.png)

**Comment by lebensterben** [comment]
@3n-k1 can you move the cursor down?

**Comment by 3n-k1** [comment]
@lebensterben sure can. this is the full window

![image](https://user-images.githubusercontent.com/51172302/97838069-769f3f80-1cad-11eb-9ba5-abc7c500b521.png)

if i run `M-x customize-face RET [anything else here] RET` i do see the `Show All Attributes` link

![image](https://user-images.githubusercontent.com/51172302/97838246-ca118d80-1cad-11eb-8f84-f34c1a536a2e.png)

**Comment by 3n-k1** [comment]
alright, i ended up editing anzu-modeline and looking at the generated lisp, which led me to the `:height` option. appending the following to `custom-set-variables` ended up giving me what i want:

```elisp
'(mode-line ((((class color) (min-colors 89)) (:inverse-video unspecified :overline "#073642" :height 0.9 :underline "#284b54" :foreground "#839496" :background "#073642" :box (:line-width 1 :color "#073642" :style unspecified))))))
```

thanks for the help! i'll definitely look at customize-face in the future
