### ISSUE TITLE
Section 5 (on debugging) of emacs-lisp layer doc is faulty 

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#14102]
#### Description :octocat: The section on emacs-lisp debugging in the emacs-lisp
layer doc
[here](https://develop.spacemacs.org/layers/+lang/emacs-lisp/README.html#debugging-elisp)
seems faulty.

First it says to use `, '` withing the source block to open another
emacs-lisp-mode buffer, while `, '` is bound to `IELM`. Later it says to put
cursor on the parenthesis and press `, e e`. But in evil mode, following this
step only evaluates the "spacemacs" string. Furthermore if someone just
copy-pasted the code to a file then it is not even possible to put the cursor after
the parenthesis for pressing `, '`, as there is no whitespace there for placing
the cursor, and also pressing `A` is not working because the buffer is in
read-only mode.

Proceeding evaluating with `, e f` (instead of `, e e`, and then pressing `s` to
next step up seems to not do what is meant in the doc (it places the cursor
behind the sexp, instead of going to some opening parentheses). And then also
`i` does not do what is meant.

It would be great if a more experienced developer, could fix that section. I
would have liked to do it, but I do not understand what is meant.

#### Reproduction guide :beetle:
- Start Emacs
- follow the steps
[here](https://develop.spacemacs.org/layers/+lang/emacs-lisp/README.html#debugging-elisp)
using evil-mode

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: specify_configuration_layer_info_and_add_cross_links (rev. 58b1d7046)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(centaur-tabs auto-completion emacs-lisp common-lisp clojure rust python lua jupyter
              (git :variables magit-repository-directories
                   '(("~/git" . 1)))
              (ivy :variables ivy-enable-advanced-buffer-information t)
              fasd
              (ranger :variables ranger-override-dired 'ranger ranger-show-preview t)
              lsp pdf djvu
              (calibre :variables calibredb-root-dir "/mnt/4EEDC07F44412A81/Calibrebibliotheek" calibredb-add-delete-original-file "yes" calibredb-download-dir "~/Downloads" calibredb-fetch-covers "yes" calibredb-show-entry-switch 'switch-to-buffer-other-window calibredb-show-results t calibredb-title-width 84 calibredb-author-width 25 calibredb-tag-width 14 calibredb-comment-width 32)
              toc
              (latex :variables reftex-toc-split-windows-horizontally t)
              markdown html multiple-cursors
              (org :variables org-enable-org-journal-support t org-journal-dir "~/Sync/org/journal/" org-journal-file-format "%Y%m%d.org" org-journal-file-type 'weekly org-directory "~/Sync/org" org-default-notes-file "~/Sync/org/notes.org" org-enable-reveal-js-support t)
              (shell :variables shell-default-height 30 shell-default-position 'bottom)
              spell-checking syntax-checking themes-megapack treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by duianto** [comment]
Your right, it doesn't always work as expected.

It seems to depend on how the readme file was opened.

Opening `emacs-lisp/README.org` with:
```
SPC h l                ;; helm-spacemacs-help-layers
```
opens the file in `space-doc-mode` (the mode line shows: `ViewSD`)

Now `, '` shows the minibuffer message:
>Buffer is read-only: #<buffer README.org>

The full message in the messages buffer is:
>org-edit-special: Buffer is read-only: #<buffer README.org>

Disabling `space-doc-mode`: `, T V` or `M-x space-doc-mode`
or opening the readme with either `SPC p p` or `SPC f f`

Makes `, '` work as expected.

Now `, '` opens a new buffer: `*Org Src README.org[ elisp ]*`
in `org-src-mode` (the minibuffer shows: `OrgSrc`)

The buffer contains the code from the debugging elisp source block.

And now the debugging instructions seem to work as expected in this buffer.

Except for the last step:
>Press a to stop debugging.

Pressing `a` just shows: `stop`
`C-h l` shows:
```
 a                      ;; edebug-stop
```

but nothing happens, the arrow in the left margin is still visible, indicating that we're still debugging.

`q` on the other hand shows:
>Back to top level

and `C-h l` shows:
```
 q                      ;; top-level
```
and the arrow in the left margin is gone, which seems to indicate that we are done debugging.

<details><summary>
Manjaro, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 48f25917c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm lsp multiple-cursors
            (org :variables org-agenda-files
                 '("~/org/notes.org"))
            rust spell-checking syntax-checking version-control
            (vue :variables vue-backend 'lsp)
            treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

</pre>
</details>

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 48f25917c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey clojure emacs-lisp git helm javascript
            (latex :variables latex-backend 'lsp)
            lsp multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/")
                 org-enable-jira-support t org-enable-roam-support t)
            python
            (ranger :variables ranger-enter-with-minus nil)
            shell spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by dalanicolai** [comment]
Ah I see now, that I understood things the wrong way. Somehow I was thinking completely the wrong way, and did not understand that `read this file` just above the code block referred to the README file I was reading (it seems quite logical now, so I don't understand why it wasn't clear but probably I was just too tired. I tried the instruction in the wrong way in an elisp file). Still it might be handy to state the location of the README file.

Thanks for checking and instructing me, the instructions actually just work, also from a normal elisp file. Sorry for the somewhat embarrassing misunderstanding. I am quite surprised how I could read/understand this wrong. I will close this issue right away :flushed:
