### ISSUE TITLE
spacemacs/helm-yas(SPC i s) breaks the `# condition: ` system of YASnippet

### ISSUE THREAD

**Issue by nfedyashev** [syl20bnr/spacemacs#14105]
#### Description :octocat:
Something must be wrong with `spacemacs/helm-yas` because it ignores(or caches?) the results for autocompletion. `# condition: ` is unusable with `helm-yas`

#### Reproduction guide :beetle:
Create the following snippet:
1.
```
cat enh-ruby-mode/big-number
# -*- mode: snippet -*-
# name: ruby big number digit readable human
# condition: (= (line-number-at-pos) 1)
# --
100_000_000_000
```
2. Open any `.rb` file or just switch to ruby-mode/enh-ruby-mode.
3. Navigate to any line that is not the first one and execute `SPC i s`(spacemacs/helm-yas)
4. Start typing e.g. "number"

*Observed behaviour:* :eyes: :broken_heart:
"ruby big number digit readable human` is listed in autocompletion mode(condition is ignored)

*Expected behaviour:* :heart: :smile:
"ruby big number digit readable human" snippet name must be available in auto-completion only on the first line(when a condition is true)

This issue is only reproducible in `helm-yas`. When I run `yas-insert-snippet` command instead it works fine! `# condition: ` is properly checked and only the matching snippets are displayed.

#### System info 

yasnippet pkg info 20200604.246
helm-c-yasnippet pkg info  20200520.1519
Spacemacs branch - develop

**Comment by smile13241324** [comment]
This sounds like a `helm-yas` issue to me, can you open a ticket upstream?

**Comment by nfedyashev** [comment]
The issue has been reported https://github.com/emacs-jp/helm-c-yasnippet/issues/21#issuecomment-729576708 but it didn't fix the issue.

As a workaround, I'll go with rebinding default mapping for yasnippet inserting so that it uses the function that works correctly(yas-insert-snippet)
