### ISSUE TITLE
Suggestion: different mapping

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#1410]
Its a minor 'issue', nonetheless
`delete-window` should be `SPC w d` instead of `SPC w c`, as `spacemacs/kill-this-buffer` is `SPC b d`.
`toggle-current-window-dedication` could be `SPC w t` instead of `SPC w d`

*d~delete* is stronger then *d~dedication*

**Comment by Sohalt** [comment]
I think it's `SPC w c` because VIM has CTRL+W c for closing the current window. But I agree that more overall consistency would be nice.

**Comment by syl20bnr** [comment]
I agree to have `d` and `D` in `SPC w` instead of `c` and `C`.
We could also remove `SPC b k` which is redondant with Helm actions.

**Comment by TheBB** [comment]
`SPC w d` is now taken by dedication, which is a really nice binding.

Do we want to move `SPC b d` to `SPC b c` instead, then?

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
