### ISSUE TITLE
Unable to use `C-u` and sometimes `M-m` due to running timer error: `window-live-p nil`

### ISSUE THREAD

**Issue by aaaawwWWWwwwwWWW** [syl20bnr/spacemacs#14104]
#### Description :octocat:
Sometimes, generally after opening `eshell` under some circumstances, the leading/complete keys `C-u` (for prefix argument) and `M-m` won't work, throwing a running timer error.

#### Reproduction guide :beetle:
I didn't find a way to reproduce it just yet, but opening eshell triggers it under some circumstances. What I think might be related:

- having different layouts active
- eshell
- org-agenda
- maybe calendar

Also, the fact I'm using native-comp + pgtk (aka `pgtk-nativecomp`) might be related.

*Observed behaviour:* :eyes: :broken_heart:
After pressing `C-u` (and sometimes with `M-m`), mini-buffer shows running timer error, making it impossible to invoke the functionality of these keys.

*Expected behaviour:* :heart: :smile:
To work as usual: after pressing `C-u` be able to pass numeric argument; or after pressing `M-m`, to show the `which-key` buffer and be able to choose other commands.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Emacs branch: pgtk-nativecomp by flatwhatson
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ab52131d9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(better-defaults multiple-cursors treemacs helm auto-completion spacemacs-layouts
                 (git :variables global-git-commit-mode t)
                 asciidoc csv graphviz html ipython-notebook latex markdown
                 (org :variables org-enable-hugo-support t)
                 plantuml yaml
                 (c-c++ :variables c-c++-backend 'lsp-clangd c-c++-lsp-enable-semantic-highlight 'rainbow)
                 emacs-lisp java javascript lsp
                 (python :variables python-backend 'lsp)
                 rust
                 (shell :variables shell-default-term-shell "/usr/bin/zsh")
                 syntax-checking systemd emoji spell-checking bibtex mu4e w3m
                 (rcirc :variables rcirc-enable-authinfo-support t))
```

- System configuration features: JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 PGTK XIM MODULES NATIVE_COMP THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2

#### Backtrace :paw_prints:
When pressing `C-u`, the `Messages` buffer throws:
```
Error running timer ‘helm-M-x--notify-prefix-arg’: (wrong-type-argument window-live-p nil) [112 times]

```

The `Backtrace`:
```
Debugger entered--Lisp error: (wrong-type-argument window-live-p nil)
  #<subr select-window>(nil norecord)
  ad-Advice-select-window(#<subr select-window> nil norecord)
  apply(ad-Advice-select-window #<subr select-window> (nil norecord))
  select-window(nil norecord)
  helm-M-x--notify-prefix-arg()
  apply(helm-M-x--notify-prefix-arg nil)
  timer-event-handler([t 24476 49793 598585 0.1 helm-M-x--notify-prefix-arg nil nil 780999])
```

**Comment by aaaawwWWWwwwwWWW** [comment]
So, as in the backtrace, it's related to helm. Now I'm using Ivy instead and I do not have this issue.

**Comment by vv111y** [comment]
Hi, I'm still using helm and this issue persists, I expect others are probably having it too. Perhaps this should be re-opened, or reported upstream.

**Comment by AtomicNess123** [comment]
I have this issue too. Any progress? Wouldn't like to change to Ivy.

**Comment by hnmurz** [comment]
I dont use spacemacs but I have ran into this issue and just doing `M-x helm-timers` and inspecting the absolute timers I saw an entry for `helm-M-x--notify-prefix-arg`. Killing this timer seems to have resolved the issue for me.

**Comment by borgauf** [comment]
And how do you kill this?

**Comment by hnmurz** [comment]
That depends in your keybindings, for me, after `M-x helm-timers` I navigate to select the entry and then hit `C-c d` which runs the command `helm-buffer-run-kill-persistent`.

**Comment by flintforge** [comment]
simply check `list-timers`

**Comment by AtomicNess123** [comment]
When checking `list-timers ` I can't find `notify-prefix-arg` to kill it...

**Comment by Quezion** [comment]
This bug still exists, but unlike Atomic, my timer showed up in `list-timers` and was cancellable (which fixed this.)

Saw this on Prelude build from October 25th, 2021. Mac OS 12.2.
I do have customizations in my `custom/` files, so it's possible that this only occurs as an interaction between them & helm. I've only seen this bug this one time.

**Comment by lebensterben** [comment]
@Quezion 

Yes I think you should also report this bug in Prelude.

But I will keep this issue open since a few other people are having the same problem.
