### ISSUE TITLE
Broken symbols in the sub menu at the bottom that indicate the mode

### ISSUE THREAD

**Issue by ludblom** [syl20bnr/spacemacs#14116]
The symbols at the bottom menu that indicate different kind of modes are broken for me. Everything else work perfectly fine but have found myself spending more time to try to fix this then I would like to. I though at first that it was because I did not have "Source Code Pro" installed correctly, but it seems to be working just fine.. Do not know what the problem may be..

**Comment by lebensterben** [comment]
If you are using Emacs in a terminal, this is normal due to terminal's limitation.

**Comment by ludblom** [comment]
No I am not using Emacs in the terminal but use the GUI

**Comment by smile13241324** [comment]
Make sure you have installed the standard unicode fonts of your distro i.e. all the icons. If these symbols don't render its a sure sign you are missing support for them on your system.

**Comment by ludblom** [comment]
ttf-linux-libertine was the package I was missing! Ty! :)
