### ISSUE TITLE
eyebrowse error on MSYS2 instance

### ISSUE THREAD

**Issue by mateusz-piotrowski** [syl20bnr/spacemacs#14114]
In my notebook, I can't install WSL so I decided to use MSYS2.
I install emacs and during setup spacemacs, I received the following error:
![emacs - eyebrowse error](https://user-images.githubusercontent.com/7917509/98054224-a9c30980-1e3a-11eb-91f6-c6f9e86260cb.png)

**Comment by smile13241324** [comment]
MSYS2 as well as Cygwin are no direct equivalents for a full featured Linux system. Therefore a lot of functions will behave differently on them then on a normal system. Emacs consists of thousands of functions, not to mention the hundreds of packages creating Spacemacs. It is very likely that packages will break randomly on both systems.

If you are on Windows use docker via the legacy Hyper-V backend, this is the only way to have a guaranteed working Spacemacs environment away from a Unix based system if the Linux subsystem is not available on Windows.

Now to your issue at hand, here is what I would do in a world without docker:
* Reduce your spacemacs config to the bare minimum
* Exclude eyebrowse via your dotfile, see  `dotspacemacs-excluded-packages`
* Make sure you get the basics installed, if you do you can add layers one after another, as I said expect that some packages will fail.
* If you are not getting any package installed make sure that emacs is able to access the internet and that gnutls is available. If not install it in the latest version.

**Comment by mateusz-piotrowski** [comment]
Thank you for your explanation. As I said in a previous post I can't use WSL because my notebook does not support virtualization. So, I can't use Hyper-V, too. I decided to use an old MSI ultrabook as my second notebook and install Linux on it.
I collecting money and waiting for MacBook Pro with probably the M1 processor.
You can close this request.
