### ISSUE TITLE
eyebrowse error

### ISSUE THREAD

**Issue by mateusz-piotrowski** [syl20bnr/spacemacs#14113]
In my notebook, I can't install WSL so I decided to use MSYS2.
I install emacs and during setup spacemacs, I received the following error:
![emacs - eyebrowse error](https://user-images.githubusercontent.com/7917509/98054224-a9c30980-1e3a-11eb-91f6-c6f9e86260cb.png)

**Comment by smile13241324** [comment]
Duplicate of #14114
