### ISSUE TITLE
Org Babel and Python layer don't play nice together

### ISSUE THREAD

**Issue by jassinm** [syl20bnr/spacemacs#14112]
Description :octocat:

Org babel and Python layer don't play nice together. Once the python layer is turned on in spacemacs 
I can't execute a python org babel block. If I turn off the python layer all works as expected

Reproduction guide 🐞

have python layer and org layer turned on in spacemacs
```
   dotspacemacs-configuration-layers
   '(
     python :variables python-backend 'anaconda)
     org
```
create a simple org file with the following  python org babel block

```
#+BEGIN_SRC python :exports both
res = [1,2,3]
return res
#+END_SRC
```
put cursor in the block and execute via Ctrl-C-C

Observed behaviour: 👀 💔

no output and I get the following messages in the Message buffer

```
executing Python code block...
Ispell process killed
Starting new Ispell process /usr/local/bin/ispell with default dictionary...done
Can’t guess python-indent-offset, using defaults: 4
pythonic-python-readable-file-name: Wrong type argument: stringp, nil
Ispell process killed
Starting new Ispell process /usr/local/bin/ispell with english dictionary...done
```

Expected behaviour: ❤️ 😄

would see
```
#+BEGIN_SRC python :exports both
res = [1,2,3]
return res
#+END_SRC

#+RESULTS:
| 1 | 2 | 3 |
```

System info:

running dev branch

**Comment by lebensterben** [comment]
Cannot reproduce.
Please update all your system packages, Spacemacs, and emacs packages and retry.
If it persists, attach system info via <kbd>SPC h I</kbd>.
