### ISSUE TITLE
org-mode: links to external programs don't open

### ISSUE THREAD

**Issue by elvis-sik** [syl20bnr/spacemacs#14119]
#### Description :octocat:
Links to all external programs (I tried a few different ones) stopped working, they'll show up in the messages buffer but not actually open, I even check it with `pgrep` to be sure. This started happening about a month ago after I updated the packages and `git pull --rebase`'d Spacemacs.

#### Reproduction guide :beetle:
- Start Emacs
- Open any org-mode file with a link to a file configured to be opened by an external program (e.g., `[[file:./a_file.pdf]]`)

*Observed behaviour:* :eyes: :broken_heart:
`Running zathura /home/elvis/a_file.pdf...done` shows up in the message buffer but the program doesn't open.
Running the exact same command (`zathura /home/elvis/a_file.pdf`) in the command line works.

*Expected behaviour:* :heart: :smile:
The program should open.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4c2fcc13c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(csv octave javascript auto-completion better-defaults emacs-lisp git markdown semantic
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
     syntax-checking version-control
     (c-c++ :variables c-c++-default-mode-for-headers 'c-mode c-c++-enable-clang-support t)
     html shell-scripts sql yaml
     (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save nil)
     ipython-notebook
     (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "gibiansky" haskell-enable-shm-support t haskell-completion-backend 'intero)
     evil-commentary
     (latex :variables latex-enable-folding t latex-enable-auto-fill nil)
     ivy emoji
     (org :variables org-enable-org-journal-support nil))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

**Edit**: had forgotten to add this **Edit** here clarifying that I corrected the example (missed `file`) after seeing @emacs18 's comment below.

**Comment by emacs18** [comment]
I thought links to file required "file:" link type, i.e., [[file:foo.pdf]] rather than just [[foo.pdf]].

**Comment by elvis-sik** [comment]
> I thought links to file required "file:" link type, i.e., [[file:foo.pdf]] rather than just [[foo.pdf]].

You are correct. It was a typo. I edited the text of the issue.

**Comment by elvis-sik** [comment]
I ran into a couple more annoying issues (most notably evil commands not working in magit) and since apparently I was the only one running into them, I ended up (backing up and) nuking `.emacs.d`. After reinstalling Spacemacs, everything seems to be ok. Thank you.

**Comment by elvis-sik** [comment]
Responing: I had tested it on `master`. The problem persisted after I switched to `develop`. This makes no sense to me since I had been updating Spacemacs every 2 weeks, but `git bisect` accuses a commit from 2 years ago as the culprit. For the time being, I'm using `a087ee2ec`.

```
a013d868744551114a18433a083a4a6cfb12e1a9 is the first bad commit
Author: syl20bnr <sylvain.benner@gmail.com>
Date:   Tue Jul 3 01:20:06 2018 -0400
```

**Comment by elvis-sik** [comment]
I decided to investigate. Nuked `.emacs.d`, removed my (backed up) `.spacemacs` and reinstalled `develop`. Everything is working perfectly. I have no idea why but if I find it out I'll make sure to post it here. In any case, I'll close this.
