### ISSUE TITLE
Move delete-current-buffer-file and rename-current-buffer-file to one group

### ISSUE THREAD

**Issue by Sohalt** [syl20bnr/spacemacs#1412]
Right now `delete-current-buffer-file` is in the file group `SPC f` and `rename-current-buffer-file` is in the buffer group `SPC b`.
Since both of them are closely related and operate on the currently opened file I would propose to move them together in one group, either `SPC b` or `SPC f` with a slight preference for the latter.

**Comment by syl20bnr** [comment]
Indeed `SPC b r` should be moved to `SPC f R`.

**Comment by TheBB** [comment]
Seems like this has been fixed.
