### ISSUE TITLE
Magit/git commit issue

### ISSUE THREAD

**Issue by doc1623** [syl20bnr/spacemacs#14121]
If this is the wrong place let me know or if I'm just doing something wrong, but I can't commit. I put this in [reddit](https://www.reddit.com/r/spacemacs/comments/jqi7tw/magit_commit_issueerror/) but no luck yet.

I'm new to magit and I was trying to set it up. I created a local repository and am able to do status. I get the "In the beginning there was darkness". I have some staged files. When I try to commit. 

I get the error:

`transient--emergency-exit: Wrong type argument: transient-suffix, [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil ...], object [2 times]
`

It seems to be the same as  [this issue](https://github.com/magit/magit/issues/1201)

Ubuntu 18.04.3 LTS
The rest was:
    - Emacs: 25.2.2
    - Spacemacs: 0.300.0
    - Spacemacs branch: develop (rev. 76ce0ac03)

now:

I reinstalled emacs and spacemacs with the stable branch today Spacemacs v.0.200.13 same emacs version. Still looking to find the option where I was able to print the above and tons of other info.

debugger output:

`Debugger entered--Lisp error: (wrong-type-argument transient-suffix [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil "-a" transient:magit-commit:--all t " %k %d (%v)" "Stage all modified and deleted files" nil nil nil nil nil nil nil nil nil "--all" "-a" nil unbound nil nil nil nil nil nil nil nil] object)

    signal(wrong-type-argument (transient-suffix [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil "-a" transient:magit-commit:--all t " %k %d (%v)" "Stage all modified and deleted files" nil nil nil nil nil nil nil nil nil "--all" "-a" nil unbound nil nil nil nil nil nil nil nil] object))

    transient--emergency-exit((wrong-type-argument transient-suffix [eieio-class-tag--transient-switch 1 nil nil nil nil nil nil nil nil "-a" transient:magit-commit:--all t " %k %d (%v)" "Stage all modified and deleted files" nil nil nil nil nil nil nil nil nil "--all" "-a" nil unbound nil nil nil nil nil nil nil nil] object))

    transient-setup(magit-commit)

    magit-commit()

    funcall-interactively(magit-commit)

    call-interactively(magit-commit nil nil)

    command-execute(magit-commit)`

**Comment by thanhvg** [comment]
I guessed the packages not compiled properly. You should force `spacemacs` to recompile every thing: ` spc u spc f e c` which calls `spacemacs/recompile-elpa` with the force option.

Other things to consider:

- Emacs 25.2 is pretty old now. I suggest emacs 27.1. There is a similar issue from upstream magit with 25.2 https://github.com/magit/magit/issues/4154. 

- Use develop branch. But your rev point is also old. just pull the latest one.

**Comment by smile13241324** [comment]
Jep, please upgrade to a newer version of emacs, core Spacemacs is still compatible with 25.1 but most of the elisp packages are not.
Also forcing a manual recompile would also be the first thing I would try to fix your issue though I have only seen a compilation issue of elisp packages once and this was not in relation with elisp classes (this is what eieio is used for).
