### ISSUE TITLE
Spacemacs hangs when using tramp / sudo to open a file owned by root.

### ISSUE THREAD

**Issue by wygulmage** [syl20bnr/spacemacs#14126]
#### Description :octocat:
Spacemacs hangs when using tramp / sudo to open a file owned by root.

#### Reproduction guide :beetle:
- Start Emacs.
- Open a file owned by root in read-only mode.
- Type [SPC f E] to open the file in read-write mode using tramp and sudo.

- Start Emacs.
- Type [SPC f f] to open a file owned by root that has previously been opened in read-write mode using tramp and sudo.

*Observed behaviour:* :eyes: :broken_heart:
- All spacemacs frame hang; message `Tramp: sending password` is displayed.

*Expected behaviour:* :heart: :smile:
- Spacemacs prompts for a password, does not hang; if correct password is entered, file is opened in read-write mode.

(no backtrace because spacemacs became unresponsive)

**Comment by thanhvg** [comment]
I had the same problem before when I had different emacs versions on my machine. I found that tramp is closely tied to emacs version. If somehow spacemacs loads a wrong version of tramp then you will have this problem. Do `M-x: tramp-version` on spacemacs and on barebone emacs (`emacs -Q`) to verify if it falls to this case.

How could spacemacs load a wrong version of tramp? One example is having emacs 27.0.9 and emacs 27.1  both installed to global or the same place. So in `usr/share/emacs` you have two elisp directories `27.0` and  `27.1` corresponding to emacs 27.0.9 and emacs 27.1 respectively. Barebone emacs will load the right directory but spacemacs will load all or just 27.0 directory which leads to a wrong tramp.

**Comment by lebensterben** [comment]
I've tramp version `2.4.3.27.1` with emacs 27.1 only.
I'm having the bug for a while. And it doesn't seem like barebone emacs solved this issue.

**Comment by thanhvg** [comment]
> I've tramp version `2.4.3.27.1` with emacs 27.1 only.
> I'm having the bug for a while. And it doesn't seem like barebone emacs solved this issue.

Then your `emacs` is the problem. Mine is 27.1 too and tramp version is `2.4.5-pre`

**Comment by lebensterben** [comment]
FYI, `2.4.3.27.1` is the correct version for latest stable build.

https://github.com/emacs-mirror/emacs/blob/86d8d76aa36037184db0b2897c434cdaab1a9ae8/lisp/net/trampver.el#L42

**Comment by thanhvg** [comment]
How about this:  
https://github.com/emacs-mirror/emacs/blob/emacs-27/lisp/net/trampver.el#L42

branch: emacs-27, :)

**Comment by lebensterben** [comment]
This is not the correct commit.
You should check the one tagged with "emacs-27.1"

**Comment by thanhvg** [comment]
Oops I misfired thanks for letting me know.

**Comment by treymerkley** [comment]
Also experiencing this issue, has there been any sort of fix in the intervening time?

**Comment by wygulmage** [comment]
I tried a couple of things to fix it, but couldn't get anything working. In the end I couldn't let it bog me down, so I switched back to vi.
