### ISSUE TITLE
Cannot use magit on MacOS

### ISSUE THREAD

**Issue by viebel** [syl20bnr/spacemacs#14127]
#### Description :octocat:
Cannot use magit

#### Reproduction guide :beetle:
- Start Emacs
- SPC g s or execute: `magit-status`

*Observed behaviour:* :eyes: :broken_heart:
An error is displayed:
Wrong type argument: listp, "osxkeychain"

magit buffer doesn't open

*Expected behaviour:* :heart: :smile:
magit buffer opens

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c3872f165)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors treemacs)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB MODULES THREADS JSON PDUMPER GMP

**Comment by emacs18** [comment]
Magit works fine for me using macos 10.15 Catalina, emacs 27, latest spacemacs develop branch, helm, vim.

**Comment by sidraval** [comment]
@viebel I encountered something similar recently, this may help: https://github.com/syl20bnr/spacemacs/issues/13357
