### ISSUE TITLE
How to initialize lsp server/workspace manually?

### ISSUE THREAD

**Issue by NANASHI0X74** [syl20bnr/spacemacs#14129]
Can I manually start an lsp server within emacs?
Sometimes emacs fails to start the lsp server for some file and then never attempts it again during that emacs session. The only solution I've found in that situation is to restart emacs. Is there a command i can run manually to start the lsp server again?

**Comment by lebensterben** [comment]
M x, lsp-mode
M x, lsp-mode

or

SPC b d for to close all the buffers where lsp stopped working, then open them again

**Comment by NANASHI0X74** [comment]
the first I tried and didn't work, I'll try the second one

**Comment by lebensterben** [comment]
@NANASHI0X74 that's a typo
enter the name of major mode instead

**Comment by NANASHI0X74** [comment]
that worked
