### ISSUE TITLE
doom-modeline checker segment fails to report flymake errors

### ISSUE THREAD

**Issue by zane** [syl20bnr/spacemacs#14133]
#### Description :octocat:
`doom-modeline` `checker` segment does not include errors.

#### Reproduction guide :beetle:
The instructions below are for triggering an elisp error, but I believe this bug can be reproduced with any flycheck error. 

I could not reproduce this bug on a vanilla Emacs configuration, so I believe this is not an issue upstream.

- In `.spacemacs` set `dotspacemacs-mode-line-theme` to `'doom`
- In `.spacemacs` add `syntax-checking` to `dotspacemacs-configuration-layers`
- Start Emacs
- Open a new `.el` file, insert `x)`, and save.
- Enable `flycheck-mode` for the `.el` file buffer.
- (Optional) Press `SPC e l` and note that flycheck is indeed reporting 5 info messages, 1 warning, and 1 error.

*Observed behaviour:* :eyes: :broken_heart:
The `checker` segment in the modeline shows ":no_entry_sign: 0".

*Expected behaviour:* :heart: :smile:
The `checker` segment in the modeline shows ":no_entry_sign: 7".

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 184bb2b00)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors syntax-checking treemacs)
```
- System configuration features: RSVG IMAGEMAGICK GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
Not applicable.

**Comment by sauvala** [comment]
I have this issue also. The checker doesn't reflect flychecker errors/warnings like you described. I tested this in the init.el config file and also in some Clojure code.

**Comment by lebensterben** [comment]
@zane 
I can confirm this bug for `emacs-lisp-mode`.

**Comment by theophilusx** [comment]
I can also confirm this with Javascript, lsp-mode and flycheck (lsp-mode linting disabled). The segment in the mode line showing errors always show 0 if there are any errors and a green tick if there are none. Switching the mode-line to spacemacs default and errors are shown correctly.

**Comment by zane** [comment]
Still an issue!

**Comment by fnussbaum** [comment]
I cannot reproduce this with the newest doom-modeline, perhaps it works since https://github.com/seagle0128/doom-modeline/commit/200145440276e6e31dc2a27165da4215ed67ebe7? It works correctly for both values of `doom-modeline-check-simple-format` for me.

**Comment by smile13241324** [comment]
@zane please double check with the latest package versions.

**Comment by smile13241324** [comment]
I assume it works with the latest version given there was no response in 28 days.
