### ISSUE TITLE
Cannot disable lsp-mode and flycheck-mode completely

### ISSUE THREAD

**Issue by jeongsoolee09** [syl20bnr/spacemacs#14148]
#### Description :octocat:

I cannot disable `lsp-mode` and `flycheck-mode` (and their respective friend packages) completely. (Very sorry to the devs, but I prefer having no intelligent support for my code.)

#### Reproduction guide :beetle:

- Start Emacs
- Add the following to `dotspacemacs-excluded-packages`:
  - `lsp-python-ms lsp-mode lsp-ui lsp-metals lsp-haskell lsp-java helm-lsp lsp-treemacs flycheck flycheck-package flycheck-elsa flycheck-ocaml`
- `package-delete` the above packages to make sure they are not installed
- Restart Emacs

*Observed behaviour:* :eyes: :broken_heart:

Spacemacs goes on to install `lsp-mode`, `flycheck-mode` and their friends again, recognizing them as new packages to install.

*Expected behaviour:* :heart: :smile:

`lsp-mode` and `flycheck-mode` no longer gets installed automatically, and thus is completely gone from my emacs.

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 812877409)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((go :variables go-tab-width 4)
 elm spacemacs-modeline spacemacs-layouts vimscript fsharp javascript clojure html helm
 (auto-completion :disabled-for org python shell)
 emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh" shell-default-shell 'vterm)
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 (spell-checking :variables spell-checking-enable-by-default nil)
 version-control haskell ocaml osx coq emoji python pdf c-c++ yaml racket themes-megapack java graphviz search-engine csv ipython-notebook prolog common-lisp pandoc dap hy slack
 (elfeed :variables rmh-elfeed-org-files
         (list "~/.emacs.d/elfeed.org"))
 (mu4e :variables mu4e-installation-path "/usr/local/Cellar/mu/1.4.13/share/emacs/site-lisp/mu/mu4e")
 multiple-cursors scheme latex ibuffer elm xkcd github
 (scala :variables scala-backend 'scala-metals))
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
LOL sorry but you are purposefully activating an LSP server in your dotfile dude. This triggers autoloading the LSP layer. Remove the line `(scala :variables scala-backend 'scala-metals)`.

Also if you do not want to have any kind of tool support for autocompletion or syntax checking, I assume for trainings purposes, just remove the `auto-completion` and `syntax-checking` layers from your dotfile. They will take flycheck and all associate packages with them. An alternative approach would be to use the `spacemacs-base` distribution instead which comes only with a minimal amount of packages.

**Comment by jeongsoolee09** [comment]
OMG. Can't believe I didn't exclude them from my layers list. Thanks for pointing those out.

**Comment by jeongsoolee09** [comment]
I'm closing this thread.
