### ISSUE TITLE
Unicode characters are not rendering in terminal as daemon

### ISSUE THREAD

**Issue by arifer612** [syl20bnr/spacemacs#14143]
#### Description :octocat:
Unicode characters not rendering in terminal when using daemon. This is a similar issue as #12472

#### Reproduction guide :beetle:
- Set necessary locales to en_US.UTF-8
- Start Emacs with daemon flag
- Start emacsclient in terminal with -ct flags

*Observed behaviour:* :eyes: :broken_heart:
All unicode characters are not rendered and are plain to see. The home page looked like this:
![1_002](https://user-images.githubusercontent.com/46054733/99395508-7c3a8d80-291b-11eb-9bfe-4bce87c9a280.png)

*Expected behaviour:* :heart: :smile:
All unicode characters to be rendered and a nice, pretty icon in the homepage. Just like this when I tried emacs -nw on the same terminal session without a problem: 
![1_003](https://user-images.githubusercontent.com/46054733/99395471-6c22ae00-291b-11eb-935a-6fd0c604b792.png)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. db82eff6d)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust systemd yaml html python helm auto-completion emacs-lisp git markdown org syntax-checking version-control unicode-fonts)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
nil

**Comment by lebensterben** [comment]
cannot reproduce

**Comment by anujdeshpande** [comment]
@arifer612 how did you solve this? Seeing something similar.
