### ISSUE TITLE
buffer-to-window-4 fails with "No window numbered 4"

### ISSUE THREAD

**Issue by m-plamann** [syl20bnr/spacemacs#14140]
#### Description
[SPC b 4] fails if run in a frame with fewer than 4 windows

I believe this bug was introduced by this commit:
https://github.com/syl20bnr/spacemacs/commit/0f65b000da93fcb258e146ff4718dae0d2fa4378

It compares the window number against the length of (window-list), but window-list returns the windows in the current frame.
So if you only have two windows in your current frame, you can't jump to a window numbered greater than 2.

#### Reproduction guide
- Start Emacs
- [SPC w v], [SPC b N n] to split the window and open a new buffer
- [SPC b 4]

*Observed behaviour:* 
[SPC b 4] fails with "No window numbered 4"

*Expected behaviour:* 
[SPC b 4] should move the current buffer to window 4

#### System Info
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. feaa63381)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF PNG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS JSON PDUMPER GMP

**Comment by duianto** [comment]
The reproduction steps seem to be missing the creation of a new frame: `SPC F n`

Confirmed.
`(length (window-list))` only gets the number of windows in the current frame.

There's a command called `count-windows`, that also only lists the current frames windows.

But it uses the command `window-list-1`, which takes an `ALL-FRAMES` argument:
>(window-list-1 &optional WINDOW MINIBUF ALL-FRAMES)

Therefore:
`(length (window-list-1 nil nil t))` returns the total number of windows in all frames.

A fix has been pushed to the `develop` branch: https://github.com/syl20bnr/spacemacs/commit/8128774090d747bed7ae34f69c682ca70d95ba2f

**Comment by m-plamann** [comment]
Oops, I did forget the `SPC F n` step.

Thanks for the quick fix!
