### ISSUE TITLE
Cannot insert timestamp in org-mode

### ISSUE THREAD

**Issue by viebel** [syl20bnr/spacemacs#14145]
#### Description :octocat:
Cannot insert timestamp in org-mode

#### Reproduction guide :beetle:
- Start Emacs
- Open a buffer in org-mode
- Execute `org-time-stamp`  (or press , t .)

*Observed behaviour:* :eyes: :broken_heart:
- An error is displayed: Key sequence j m starts with non-prefix key j

*Expected behaviour:* :heart: :smile:
Insert a timestamp

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql asciidoc
     (plantuml :variables plantuml-jar-path "~/bin/plantUml.jar")
     javascript
     (org :variables org-enable-org-journal-support t org-journal-dir "~/Dropbox/journal/")
     html
     (clojure :variables clojure-enable-fancify-symbols nil)
     helm themes-megapack
     (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
     emacs-lisp git github osx emoji markdown
     (spell-checking :variables enable-flyspell-auto-completion nil)
     syntax-checking version-control yaml evil-cleverparens)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB MODULES THREADS JSON PDUMPER GMP

**Comment by smile13241324** [comment]
Hi @viebel,

sounds like an issue on master, can you switch over to develop and retry? Master is stale for a while now, we are currently trying to find a way to review it with our BDFL.

**Comment by jr0cket** [comment]
@smile13241324  I can confirm that `org-time-stamp` works in Spacemacs 0.300, aka develop.  The key binding is `, d t` (major-mode, dates, org-time-stamp).

@viebel If you wish to switch to Spacemacs 0.300, try this switching guide I wrote https://practicalli.github.io/spacemacs/install-spacemacs/switch-to-develop.html
I have been using 0.300 for the last two years without any issue

**Comment by viebel** [comment]
@jr0cket I switched to 0.300 as you explain in your guide.
Now when I insert a timestamp I get this error:
```
Key sequence j m starts with non-prefix key j
```

**Comment by smile13241324** [comment]
Are you sure this is the right key binding? A warning of this kind is normally caused by using a inner key binding for which no description has been set. On develop the current key binding for inserting a timestamp is `SPC d t`.

Please double check your user config.

**Comment by viebel** [comment]
@smile13241324 It might be related to some weird settings in my configuration. Moving to @jr0cket [config](https://github.com/practicalli/spacemacs.d) solved the issue.

**Comment by viebel** [comment]
Now it works on Spacemacs from terminal, but on Spacemacs GUI when typing `, d t`, I get an error:
```
load-history-filename-element: Wrong type argument: stringp, evil-mc-enable-bar-cursor
```

**Comment by lebensterben** [comment]
For debugging, you'd better use a minimum .spacemacs file instead of someone else's.
