### ISSUE TITLE
Timeout raising Pull Requests against syl20bnr/spacemacs repository

### ISSUE THREAD

**Issue by jr0cket** [syl20bnr/spacemacs#14151]
I have been trying for the last 24 hours to create a Pull Request for the syl20bnr/spacemacs repository and every time I try GitHub is timing out.  Is anyone else having this issue?  I am asking GitHub support if there is an issue with the syl20bnr/spacemacs repository.

In trying to find the root cause I have
- cleared my browser cache
- used private browsing
- created a new fork of Spacemacs repository and pushed changes to that

Every time it times out.  So please let me know if you have been unable to create a pull request on Spacemacs since 17:00 UTC on Thursday 19th November.

I am able to create pull requests on other repositories, so far it just seems like its Spacemacs specific.

**Comment by lebensterben** [comment]
This is normal. When creating a PR via github.com it needs to compare the base branch to yours. That is, it compares the spacemacs/master branch to your branch which is based on spacemacs/develop. This is not a easy job.

Two approaches to solve this:
First is to manually change the URL, that replace master with develop
Second is to use GitHub's new official CLI tool to create the PR

**Comment by thanhvg** [comment]
You need manually edit the url to make it apply to develop branch. The difference between master and develop is too much for github to handle. 

For example https://github.com/syl20bnr/spacemacs/compare/master..blahblah
https://github.com/syl20bnr/spacemacs/compare/develop..blahblah

Anyway, I am fed up with master branch being stale. It is unfair to us users and contributors. At least switch default branch to develop. I am begging @syl20bnr @duianto @smile13241324 and all the other bosses I may not know. Please make 2020 less crappy.

**Comment by smile13241324** [comment]
That's a shity situation, I am trying to contact @syl20bnr to do something with this stale master. Lets hope he will respond, but I agree I am also fed up with the situation and will try to get a final resolution for the project.

Thanks for all your contributions so far, lets hope we can get this right.

**Comment by syl20bnr** [comment]
Agree this is shitty situation, I made the develop branch default for now. Once we release the new version we'll revert to master and we will do scheduled releases. The new default branch should fix the issue, please re-open the issue if you have still issues creating PRs. Thank you for contributing to Spacemacs 💜 .
