### ISSUE TITLE
org-roam buffer does not update

### ISSUE THREAD

**Issue by TS-CUBED** [syl20bnr/spacemacs#14157]
#### Description :octocat:

org-roam buffer does no longer update.

#### Reproduction guide :beetle:
- Start Emacs
- [SPC aorf <some org-roam file>]
- [SPC SPC org-roam-buffer-activate]
- [SPC aorf <some other org-roam file>]
- and switching to and from org-roam buffers

*Observed behaviour:* :eyes: :broken_heart:

the org-roam buffer does not update.

*Expected behaviour:* :heart: :smile:

org-roam buffer should update when switching between org-roam buffers.

This behaviour can be fixed by commenting the line that removes the post-command-hook to =org-roam-buffer--update-maybe= in =org-roam.el=:

```elisp
    ;; Disable local hooks for all org-roam buffers
    (dolist (buf (org-roam--get-roam-buffers))
      (with-current-buffer buf
        ;;(remove-hook 'post-command-hook #'org-roam-buffer--update-maybe t)
        (remove-hook 'before-save-hook #'org-roam-link--replace-link-on-save t)
        (remove-hook 'after-save-hook #'org-roam-db-update t))))))
```

Don't know when that was introduced (only been using org-roam for a week or so), but the behaviour was erratic since I started using it and this seems to fix it. Most likely related to =alternate-buffer= implementation in =core-funcs.el=.

See also https://github.com/org-roam/org-roam/issues/1305

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e3b646464)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(pdf html auto-completion python ipython-notebook latex
     (bibtex :variables org-ref-default-bibliography
             '("~/Documents/Latex/MyLibrary.bib")
             org-ref-pdf-directory "~/Documents/Papers" org-ref-bibliography-notes "~/Documents/Papers/notes.org")
     markdown c-c++ git multiple-cursors
     (org :variables org-agenda-files
          (list "~/Dropbox/Org/org" "~/Dropbox/Org/org-roam" "~/Dropbox/Org/org-roam/daily")
          org-refile-targets
          '((nil :maxlevel . 9)
            (org-agenda-files :maxlevel . 9))
          org-enable-roam-support t org-enable-github-support t org-enable-org-journal-support t org-todo-keywords
          '((sequence "TODO" "NEXT" "IN-PROGRESS" "WAITING" "|" "DONE" "CANCELLED"))
          org-agenda-search-view-always-boolean t org-agenda-include-diary t org-org-roam-db-update-method 'idle-timer org-roam-db-update-idle-seconds 2 hide-emphasis-markers t org-directory "~/Dropbox/Org/org" org-roam-directory "~/Dropbox/Org/org-roam")
     spell-checking syntax-checking treemacs pandoc helm
     (spotify :variables counsel-spotify-client-id "319ccab8d0f0412aa72f212e518730ca" counsel-spotify-client-secret "aa19b5e71da94e12a48e0d24e5f35fac")
     (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp" message-kill-buffer-on-exit t mu4e-enable-mode-line t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TS-CUBED** [comment]
Has been fixed in org-roam. But the behaviour of spacemacs that  triggered this is not considered "normal", so may need to be looked at here.

**Comment by emacs18** [comment]
I have similar setup, but my org-roam buffer updated automatically to track the current org buffer.
This is the case with or without the recent org-roam change in question.
