### ISSUE TITLE
Suggestion: alternative.to for plugins

### ISSUE THREAD

**Issue by idbrii** [syl20bnr/spacemacs#1416]
After seeing yet another "evil can't do a vim thing" [post](http://www.reddit.com/r/vim/comments/33lm1k/i_think_someone_at_google_may_be_a_bit_biased/cqn3nnx) get corrected I thought: what if there was an alternativeto.net equivalent for vim vs. emacs plugins/features?

This could be a page in the spacemacs docs that lists vim plugins and their emacs equivalent. Not sure where the best place is for this to get the most community involvement (since it's easy for users to suggest equivalents). There's no spacemacs wiki or I'd suggest that.

This request isn't spacemacs-specific, but would benefit users coming from vim.

**Comment by syl20bnr** [comment]
This is a good proposition, it could be a new `md` file in `doc`. To start it you can refer to https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#evil-plugins

**Comment by TheBB** [comment]
I think this is covered by the new VIMUSERS.org. Pull requests against that file are certainly welcome for anything that's missing.
