### ISSUE TITLE
cannot use ⌘-s  to save under macOS with osx layer

### ISSUE THREAD

**Issue by lawrsp** [syl20bnr/spacemacs#14166]
#### Description :octocat:
cannot save under macOS with osx layer

I found there is code which seems bind  ⌘-s to "\C-x\C-s" to do save, but it doesn't work
```emacs-lisp 
(global-set-key (kbd-mac-command "s")
                  (lambda ()
                    (interactive)
                    (call-interactively (key-binding "\C-x\C-s"))))
```

#### Reproduction guide :beetle:
- Start Emacs
- open a file
- type some thing
- ⌘-s to save

*Observed behaviour:* :eyes: :broken_heart:

cannot save, and got a message:
```
Wrong type argument: commandp, nil
```

*Expected behaviour:* :heart: :smile:

save without error

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 184bb2b00)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:

**Comment by emacs18** [comment]
My emacs does not have `kbd-mac-command` function defined.  If this is defined by some add-on package, which package?

**Comment by tko** [comment]
@emacs18 `kbd-mac-command` seems to be (conditionally) defined in the osx layer
https://github.com/syl20bnr/spacemacs/blob/6f830c149e2428237c224a8f4a1beeff97bb76f0/layers/%2Bos/osx/keybindings.el#L51

**Comment by lawrsp** [comment]
@emacs18  
as @tko commentted, it defined in the osx layer. It is ⌘ on my system

**Comment by lebensterben** [comment]
We should remove all those key bindings.
Users should learn to use vim/emacs style key bindings or add those bugOS style key bindings themselves.
