### ISSUE TITLE
org-brain-goto fails with "invalid function helm-build-sync-source" 

### ISSUE THREAD

**Issue by Wheest** [syl20bnr/spacemacs#14167]
Almost identical to issue number #12096, however the suggestions of recompiling the package, and even deleting entirely and reinstalling have not worked.

I've opened an issue with the [org-brain developer](https://github.com/Kungsgeten/org-brain/issues/342), and we've established that it's not that the issue is not with Helm deprecating anything, as they are on an even newer version, nor is it with org-brain itself.

Given issue #12096, it appears to be something in Spacemacs.  Are there any other approaches you might suggest?

**Comment by usq** [comment]
Bump, I face the same issue

**Comment by Wheest** [comment]
I've noted this actually impacts other packages for me, e.g. some functions in `markdown-mode`, such as `markdown-insert-link` fail with `helm--completing-read-default: Symbol’s function definition is void: helm-subr-native-elisp-p`.

**Comment by emacs18** [comment]
I would suggest adding this line in org-brain.el:
```elisp
(eval-and-compile (require 'helm-source))
```
This seems to be a common problem with package that use helm.  I ran into this myself several times, e.g.
https://github.com/jkitchin/scimax/commit/320f74b9bf167f9f1fdd8eb1a794f1ca155f2328

**Comment by usq** [comment]
Putting
```elisp
(eval-and-compile (require 'helm-source))
```
in `org-brain.el` actually did help! Thanks @emacs18!

**Comment by Wheest** [comment]
Thanks @emacs18!  Unfortuntely I've now hit another error trying to run org-brain, the one seen with my `markdown-mode` issue.  `helm-M-x-execute-command: Symbol’s function definition is void: helm-subr-native-elisp-p`

**Comment by emacs18** [comment]
`helm-subr-native-elisp-p` is a function, not a macro, defined in `helm-lib.el` within `helm-core` package. Thus the only way for anyone to see `symbol definition is void` error is if `(require 'helm-lib)` was not done in time. A trivial work around would be to add this missing line somewhere, e.g., in your startup file.

Second solution could be to add `(require 'helm-lib)` line within the file in which it is needed, i.e., the file in which `helm-subr-native-elisp-p` function is called. I don't know which file this is. You can find out by enabling stack trace to be printed on error which you can do by setting `debug-on-error` to `t` which you can do via `SPC t D` command.

Third solution could be to make the function in question autoloaded, i.e., add `;;;###autoload` line within `helm-lib.el` just above the function definition.
