### ISSUE TITLE
python-execute-file not using pipenv environment

### ISSUE THREAD

**Issue by chris-clem** [syl20bnr/spacemacs#14162]
#### Description :octocat:
Hello together, I am having a problem with executing a python file. It seems that `python-execute-file` (`SPC m c c`) is not using the activated pipenv environment.

On the screenshot, you can see the script I want to run. In the bottom, the correct environment is active (pipenv-test-...), and on the right, you can see the compilation output. There, the pipenv environment is not active.

![image](https://user-images.githubusercontent.com/36116534/99996171-aa0c5000-2dbb-11eb-9e68-cf988c311541.png)

#### Reproduction guide :beetle:
- Start Emacs
- Open python file in project with a pipenv file
- run python-execute-file

*Observed behaviour:* :eyes: :broken_heart:
The pyenv Python executable is used to run the file instead of the one from pipenv 

*Expected behaviour:* :heart: :smile:
The pipenv Python executable is used

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 77d84b14e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion bibtex emacs-lisp git helm lsp markdown
                 (org :variables org-enable-hugo-support t org-enable-org-journal-support t org-enable-roam-support t)
                 (python :variables python-backend 'lsp python-formatter 'black python-format-on-save t python-sort-imports-on-save t python-test-runner 'pytest)
                 (ranger :variables ranger-override-dired 'ranger ranger-show-preview t)
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by alexey0308** [comment]
Hi @chris-clem, have you solved the issue? 
Maybe it can help to see, what is the value of `python-shell-interpreter`, `exec-path` and `(spacemacs/pyenv-executable-find python-shell-interpreter)` when invoked after pipenv activation.

**Comment by pontakornth** [comment]
@alexey0308 I have the problem as well. The value of `(spacemacs/pyenv-executable-find python-shell-interpreter)` is `/usr/bin/python/`. I already activated pipenv using `python-pipenv-activate t` in the  dotfile. `python-shell-interpreter` is `python` which is Python 2.

**Comment by lebensterben** [comment]
Generally speaking utilities/wrappers for virtual environment of programming language requires adding shims directory to the PATH.

So it again is the annoying environment variable issue.
You can check `.spacemacs.env` to see whether it's in PATH.
If you started emacs as a daemon, it's also possible that when it's started, PATH is not set properly, especially if it's started as a systemd service.

**Comment by pontakornth** [comment]
Python 3.9 and pipenv is in the path along with other things I set in the fish shell (Oh-My-Fish) configuration. Virtualenv works just fine but `pipenv-activate` seems to do nothing. I expect `(spacemacs/pyenv-executable-find python-shell-interpreter)` to change but it still points to the old Python. There is no output to the message buffer but I see the output on the pipenv buffer.

I do not start emacs a daemon. I just open it from mac os application dock.

**Comment by lebensterben** [comment]
@pontakornth Do you have pyenv correctly set up?

https://github.com/pwalsh/pipenv.el#pyvenv

**Comment by Kesin1** [comment]
Working with poetry I just set the compile command to "poetry run python"

```
  (let ((universal-argument t)
        (compile-command (format "poetry run python %s" ;; "%s %s"
                                 ;; (spacemacs/pyenv-executable-find python-shell-interpreter)
                                 (shell-quote-argument (file-name-nondirectory buffer-file-name)))))
```

**Comment by shdennlin** [comment]
Hi, @chris-clem, I use `pyenv` + `virtualenvwrapper` to manage my python environment. And I have the same problem with you.
I modify function `spacemacs/pyenv-executable-find` in `~/.emacs.d/layers/+lang/python/` like:

``` diff
modified   layers/+lang/python/funcs.el
@@ -133,7 +133,7 @@
 If the executable is a system executable and not in the same path
 as the pyenv version then also return nil. This works around https://github.com/pyenv/pyenv-which-ext
 "
-  (if (executable-find "pyenv")
+  (if (and (not pyvenv-virtual-env) (executable-find "pyenv"))
       (progn
         (let ((pyenv-string (shell-command-to-string (concat "pyenv which " command)))
               (pyenv-version-names (split-string (string-trim (shell-command-to-string "pyenv version-name")) ":"))
```
``` lisp
(defun spacemacs/pyenv-executable-find (command)
  "Find executable taking pyenv shims into account.
If the executable is a system executable and not in the same path
as the pyenv version then also return nil. This works around https://github.com/pyenv/pyenv-which-ext
"
  (if (and (not pyvenv-virtual-env) (executable-find "pyenv"))
      (progn
        (let ((pyenv-string (shell-command-to-string (concat "pyenv which " command)))
              (pyenv-version-names (split-string (string-trim (shell-command-to-string "pyenv version-name")) ":"))
              (executable nil)
              (i 0))
          (if (not (string-match "not found" pyenv-string))
              (while (and (not executable)
                          (< i (length pyenv-version-names)))
                (if (string-match (elt pyenv-version-names i) (string-trim pyenv-string))
                    (setq executable (string-trim pyenv-string)))
                (if (string-match (elt pyenv-version-names i) "system")
                    (setq executable (string-trim (executable-find command))))
                (setq i (1+ i))))
          executable))
    (executable-find command)))
```
It works for me, hope it will help you.
