### ISSUE TITLE
org-todo keybinding on t doesn't do what it's documented to do

### ISSUE THREAD

**Issue by NANASHI0X74** [syl20bnr/spacemacs#14171]
#### Description :octocat:
org-todo keybinding on t doesn't work

#### Reproduction guide :beetle:
- Start Emacs
- have org layer and todo bindings enabled (org :variables want-todo-bindigs t)
- open a .org buffer
- press t

*Observed behaviour:* :eyes: :broken_heart:
the vim keybinding for t is used to go to a character before the next occurence
of a specific character which is what happens

*Expected behaviour:* :heart: :smile:
org bullet cycles through todo states
This is what I understand as the behavior it should have considering the docs:
```
if the layer variable org-want-todo-bindings is true, the following bindings are also available.

Key bindings	Description
t	Cycle TODO state of current heading
T	Insert new TODO heading
M-t	Insert new TODO sub-heading
```
I find the , T T binding much too verbose for this task anyway, I'd ideally like
a one- or maybe two-key binding for this

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b3ab4052)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python yaml sql auto-completion helm better-defaults emacs-lisp nixos git github helm lsp
        (node :variables node-add-modules-path t)
        multiple-cursors
        (org :variables want-todo-bindigs t)
        (dart :variables dart-backend 'lsp lsp-enable-on-type-formatting t)
        (vue :variables vue-backend 'lsp)
        (typescript :variables typescript-backend 'tide typescript-fmt-tool 'prettier)
        (javascript :variables javascript-backend 'lsp javascript-fmt-tool 'prettier javascript-fmt-on-save t)
        (html :variables css-enable-lsp t less-enable-lsp t html-enable-lsp t scss-enable-lsp t web-fmt-tool 'prettier)
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP

**Comment by NANASHI0X74** [comment]
ok, there is a keybinding that does what I want- S-right. found that out by watching a video... no thanks documentation 😅

**Comment by emacs18** [comment]
I don't see any mention of `want-todo-bindings` within spacemacs.  Instead I see `org-want-todo-bindings`.
Can you try adding `org-` prefix?

**Comment by NANASHI0X74** [comment]
thank you for alerting me to my blindness 😁 unfortunately, it still doesn't work, I have `(org :variables org-want-todo-bindings t)` in my layers now, but the shortcut still doesn't seem to be there
![Screenshot_20201130_104359](https://user-images.githubusercontent.com/17546398/100593679-f6deb200-32f8-11eb-83d4-62cfd7a59de1.png)

**Comment by NANASHI0X74** [comment]
ok, somehow it started working multiple reloads and restarts later 😅
