### ISSUE TITLE
pdumper&native-comp: Trying to load incoherent dumped eln file

### ISSUE THREAD

**Issue by yqu212** [syl20bnr/spacemacs#14179]
Anybody encounter this message? I use pdumper together with native-comp.

**Comment by akirak** [comment]
Yes, I encounter the same error with minimal config. It has nothing to do with Spacemacs.

**Comment by yqu212** [comment]
Yes. I have confirmed it.

I have submitted an bug report to emacs develop mailing list. https://lists.gnu.org/archive/html/bug-gnu-emacs/2020-12/msg00534.html

**Comment by larebsyed** [comment]
any update on this one, this looks like a major bug upstream

**Comment by yqu212** [comment]
No updates since then. Maybe we need to remind Andrea again.

**Comment by larebsyed** [comment]
Yes, I think we should

**Comment by lebensterben** [comment]
Closing this since it's out if scope.

Also note that pdump is turned off when native-comp is in use.
