### ISSUE TITLE
Can't enable smartparens in custom layer

### ISSUE THREAD

**Issue by taylskid** [syl20bnr/spacemacs#14170]
Hello, I am trying to write a small private layer for a scheme language, [gerbil](https://cons.io). They distribute a `gerbil-mode.el` as part of their source code and it's not in MELPA, so I have set up a private layer in `~/.emacs.d/private/gerbil` with their file copied to `~/.emacs.d/private/gerbil/local/gerbil-mode/gerbil-mode.el` and used a `:location local` specifier with success, gerbil-mode loaded properly! 

However, smartparens was disabled, which surprised me since it's enabled by default in spacemacs. I added `smartparens` to my `gerbil-packages` and specified  a `gerbil/post-init-smartparens`, resulting in this [packages.el](https://gist.github.com/taylskid/e9fafd1c66db87f332a0924a618f3818). But smartparens is still getting disabled whenever I open a gerbil-mode file! There's nothing interesting in the `*Messages*` buffer or anything like that. Am I doing something obviously wrong? Thanks, and sorry for the issue noise!

**Comment by lebensterben** [comment]
@taylskid 
Please show me your layer.
