### ISSUE TITLE
Could not disable smartparens-mode for LaTeX-mode

### ISSUE THREAD

**Issue by wang1zhen** [syl20bnr/spacemacs#14175]
Hi, I have been trying to disable smartparens-mode for LaTeX-mode since there is a better LaTeX-electric-left-right-brace for this specific mode, so I added

`(add-hook 'LaTeX-mode-hook (lambda () (smartparens-mode -1)))`

to the `dotspacemacs/user-config` part, and it results a failure: smartparens-mode is still active in LaTeX-mode.

However, I tried

`(remove-hook 'LaTeX-mode-hook 'smart-parens-mode)`

and this one worked! I am glad that this trick could be effective, but since `remove-hook` is not a common practice, I doubt that there might be something wrong with the packages or layers.

I am currently on the dev branch with all packages up to date.

**Comment by lebensterben** [comment]
do you notice you spelled it differently

**Comment by lebensterben** [comment]
@wang1zhen 
FYI:
> If called interactively, enable Smartparens mode if ARG is
positive, and disable it if ARG is zero or negative.  If called
from Lisp, also enable the mode if ARG is omitted or nil, and
toggle it if ARG is toggle; disable the mode otherwise.

These are the standard behaviours of emacs minor modes.
I think you should use one of the following:
```emacs-lisp
(add-hook 'LaTeX-mode-hook (lambda () (smartparens-mode nil)))
```
or, with the typo fixed
```emacs-lisp
(remove-hook 'LaTeX-mode-hook 'smartparens-mode)
```

**Comment by wang1zhen** [comment]
> 
> 
> @wang1zhen
> FYI:
> 
> > If called interactively, enable Smartparens mode if ARG is
> > positive, and disable it if ARG is zero or negative.  If called
> > from Lisp, also enable the mode if ARG is omitted or nil, and
> > toggle it if ARG is toggle; disable the mode otherwise.
> 
> These are the standard behaviours of emacs minor modes.
> I think you should use one of the following:
> 
> ```emacs-lisp
> (add-hook 'LaTeX-mode-hook (lambda () (smartparens-mode nil)))
> ```
> 
> or, with the typo fixed
> 
> ```emacs-lisp
> (remove-hook 'LaTeX-mode-hook 'smartparens-mode)
> ```

Sorry for the misspelling, Actually `remove-hook 'LaTeX-mode-hook 'smartparens-mode` worked for me before, and actually the problem was that neither `(add-hook 'LaTeX-mode-hook (lambda () (smartparens-mode nil)))` or `(add-hook 'LaTeX-mode-hook (lambda () (smartparens-mode -1)))` could disable the smartparens-mode for me.

Since `smartparens-mode` was called from lisp, to disable it I think I shall set it to -1, and it has no effect in my case.

**Comment by lebensterben** [comment]
Yep you are right, you should call it with a 0 or negative number.

Can you check whether you have `dotspacemacs-smartparens-strict-mode` set in your `.spaceemacs` ?

**Comment by wang1zhen** [comment]
`dotspacemacs-smartparens-strict-mode` was set to `nil` in my init file.

**Comment by lebensterben** [comment]
If you have
```emacs-lisp
(add-hook 'LaTeX-mode-hook (lambda () (smartparens-mode nil)))
```
and call `describe-variable` on `LaTeX-mode-hook`, what's the order of the hooks?

If `smartparens-mode` that added by `LaTeX` layer is behind the anonymous function, it will still be turned on.

**Comment by wang1zhen** [comment]
Thanks, that really makes sense, I shall give it a try.

**Comment by wang1zhen** [comment]
Here goes the value of `LaTeX-mode-hook`

`LaTeX-mode-hook is a variable defined in latex.el 
Its value is
(preview-mode-setup
 (closure
  (t)
  nil
  (smartparens-mode nil))
 spacemacs/load-yasnippet smartparens-mode flyspell-mode evil-matchit-mode turn-on-reftex spacemacs//latex-setup-backend TeX-PDF-mode TeX-source-correlate-mode LaTeX-math-mode TeX-fold-mode latex/auto-fill-mode spacemacs//init-jump-handlers-latex-mode spacemacs//init-company-LaTeX-mode company-mode)
Original value was nil`

I still have no idea which mode enabled the smartparens-mode.

**Comment by lebensterben** [comment]
The second item is the closure you added, and the forth one `smartparens-mode` should be set by

https://github.com/syl20bnr/spacemacs/blob/c629534013f7fb7690a68e47356e19adcc5fc079/layers/%2Blang/latex/packages.el#L204-L205

According to `add-hook`,
>(add-hook HOOK FUNCTION &optional DEPTH LOCAL)
>The place where the function is added depends on the DEPTH
parameter.  DEPTH defaults to 0.  By convention, it should be
a number between -100 and 100 where 100 means that the function
should be at the very end of the list, whereas -100 means that
the function should always come first.
Since nothing is "always" true, don't use 100 nor -100.
When two functions have the same depth, the new one gets added after the
old one if depth is strictly positive and before otherwise.

So for example, you can have
```emacs-lisp
(add-hook 'LaTeX-mode-hook (lambda () (smartparens-mode -1 90)))
```

But the other solution should always wokr
```emacs-lisp
(remove-hook 'LaTeX-mode-hook 'smartparens-mode)
```

**Comment by wang1zhen** [comment]
Thank you for your help, the solution above is fantastic. I'll close this issue.

**Comment by wang1zhen** [comment]
As a reminder, after days using the config, `(add-hook 'LaTeX-mode-hook (lambda () (smartparens-mode -1 90)))` would somehow cause strange problems, when opening a latex file in emacs, it would be turned into fundamental and latex mode (sounds strange but that is true), hence I recommend simply use `(remove-hook 'LaTeX-mode-hook 'smartparens-mode)`,which might be a better solution.

**Comment by lebensterben** [comment]
@wang1zhen 
Well, I typed the command wrong, it should be
```elisp
(add-hook 'LaTeX-mode-hook (lambda () (smartparens-mode -1)) 90)
```
