### ISSUE TITLE
adaptive-wrap messes up visual line indentation in org-mode

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#1418]
Something is wrong with adaptive-wrap. While in org-mode with org-indent-mode on, It stops visual line from indenting properly. After removing it, everything back to normal.

**Comment by syl20bnr** [comment]
We should disable it in org then.

**Comment by fintelkai** [comment]
I confirm the issue. I couldn't figure out how to selectively disable adaptive-wrap in org-mode. So, for now, I've disabled the adaptive-wrap package completely. But I'd be grateful if someone could figure out how to disable it selectively.

**Comment by incandescentman** [comment]
I have the same issue. I'm also excluding the `adaptive-wrap` package for now.

**Comment by aldanor** [comment]
Just wondering if anyone have come up with a way of visual line navigation, org-indent-mode and adaptive-wrap together, or is it a dead end? (which would be quite sad since if you prefer using org-indent-mode you have to choose between not using visual lines or visual lines not reflowing adaptively...)

(also related: #2732)

**Comment by Nikolaiam** [comment]
I think I might have found a workaround in [visual-fill-column](https://github.com/joostkremers/visual-fill-column). It seems to play nice with org-indent-mode and visual lines, although for some reason I could only get the visual-fill-column-width variable to work when setting it up with custom-set-variables :D My steps in case anyone wonders:

1. Add adaptive-wrap to dotspacemacs-excluded-packages and visual-fill-column to dotspacemacs-additional-packages
2. Add hooks to org
`(require 'visual-fill-column)
 (add-hook 'visual-line-mode-hook 'visual-fill-column-mode)
 (add-hook 'org-mode-hook 'turn-on-visual-line-mode) `
3. Modify visual-fill-column-width to the required width of wrapping
4. Profit

**Comment by jaksz** [comment]
What is actually missing if you exclude `adaptive-wrap`? I tried it and it it fixed the indentation issues I had, but am I missing out on something now?

**Comment by clhodapp** [comment]
If you have adaptive-wrap-prefix-mode off, long headings wrap terribly in org-mode. If you have it on, other text wraps glitchily.

**Comment by skalyan91** [comment]
I believe this is no longer a bug; `adaptive-wrap` now works perfectly well in org-mode, and in fact the solution with `visual-fill-column` no longer works.

**Comment by shelper** [comment]
it is still buggy with adaptive-wrap
you need to reflash org-indent-mode. 

i am running on windows, emcas 25.1, spacemacs latest develop branch

**Comment by brookter** [comment]
Just to reiterate the comment from shelper above: if you exclude adaptive-wrap in .spacemacs then the problem goes away.

Otherwise, only the first line (sometimes) two of a body text indents as you input. You need to refresh org-indent to get the desired view. Without adaptive-wrap, it works as expected.

**Comment by JonathanReeve** [comment]
I can confirm @brookter's comment above--excluding adaptive-wrap in .spacemacs fixes this issue. On Arch Linux, 0.200.9 and emacs 25.1.1.

**Comment by lopatin** [comment]
Banged my head against this for way too long. Thanks for pointing me in the right direction. Can confirm that removing `adaptive-wrap` via
```
dotspacemacs-excluded-packages '(adaptive-wrap)
```
fixed everything.

**Comment by ajyoon** [comment]
Also worth noting that adaptive-wrap has been causing crazy performance issues on my machine in `rust-mode` since it seems to be parsing the entire file on every edit action.

**Comment by syl20bnr** [comment]
I removed it from Spacemacs.

**Comment by ajyoon** [comment]
Thanks!

**Comment by iappp** [comment]
I use vanilla Emacs 27, not Spacemacs. I had this problem as well. For me the problem came from `adaptive-wrap-prefix-mode` being a minor mode everywhere. How are you loading `adaptive-wrap-prefix-mode`? I was using:

``
(add-hook 'visual-line-mode-hook #'adaptive-wrap-prefix-mode)
``

Changing to something like this keeps it off in org-mode buffers:

    (add-hook 'visual-line-mode-hook
              ;; this is our way of making adaptive-wrap-prefix-mode a global mode
              #'(lambda ()
                  (unless
                      (member
                       major-mode
                       '(org-mode
                         ;; adaptive-wrap-prefix-mode messes up the nice indentation and alignment provided by org-indent-mode
                         ;; (Add other major modes it conflicts with here)
                         ))
                    (adaptive-wrap-prefix-mode))))

Hope this helps someone.

**Comment by tbrodbeck** [comment]
> I removed it from Spacemacs. Andrew Yoon <notifications@github.com> writes:
> […](#)
> Also worth noting that adaptive-wrap has been causing crazy performance issues on my machine in `rust-mode` since it seems to be parsing the entire file on every edit action. -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#1418 (comment)](https://github.com/syl20bnr/spacemacs/issues/1418#issuecomment-390510505)

I just want to add that removing a feature can not be a real solution. `adaptive-wrap` is an important feature that I am missing in the current spacemacs build.

**Comment by Flupp** [comment]
In case someone comes by here again in search for a solution:

I use vanilla Emacs and I found the following solution:
```elisp
(add-hook 'org-mode-hook (lambda () (adaptive-wrap-prefix-mode -1)))  ;;; org-indent-mode already sets the correct wrap-prefix; see footnote for https://orgmode.org/org.html#Org-Indent-Mode
```
It seems similar to the approach of @proprietary, yet, maybe it’s still useful for someone.
