### ISSUE TITLE
mu4e-marks cannot be configured in mu4e layer

### ISSUE THREAD

**Issue by rommeswi** [syl20bnr/spacemacs#14180]
#### Description :octocat:
The list mu4e-marks is not set after package loading of the mu4e layer.
According to the mu4e manual, this list should be configurable.
(I tried to submit this bug via SPC h I but C-c C-c was undefined.)

#### Reproduction guide :beetle:
- Start Emacs with a working mu4e installation
- add a new mark using the mu4e instructions by adding it into
  dotspacemacs/user-config, for example
```
  (add-to-list 'mu4e-marks
               '(spam
                 :char       "M"
                 :prompt     "spam"
                 :show-target (lambda (target) mu4e-spam-folder)
                 :action      (lambda (docid msg target)
                                (mu4e~proc-move docid mu4e-spam-folder "+S-u-N"))))
  (mu4e~headers-defun-mark-for spam)
  (define-key mu4e-headers-mode-map (kbd "M") 'mu4e-headers-mark-for-spam)
```

- restart spacemacs

*Observed behaviour:* :eyes: :broken_heart:
- spacemacs will encounter an error during startup that mu4e-marks is not set
- mark is not working within mu4e
- calling (mu4e) within user-config before calling (add-to list 'mu4e-marks ...) adds the list entry correctly

*Expected behaviour:* :heart: :smile:
- mu4e-marks should be set before /dotspacemacs/user-config is called
- mark should be set correctly after entering it into the config
- it should not be needed to start mu4e within the config to get this to work

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp git bibtex spell-checking latex pdf-tools mu4e)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
not relevant
```

**Comment by smile13241324** [comment]
I am not a mu4e user however I see you are using master, which is pretty stale, we have changed the default branch to develop for now until it is reviewed. Please try to reproduce with develop and report back here.

Ok coming back to your specific issue your problem is that at the time your user-config is run mu4e is not yet loaded causing emacs to complain that you cannot add values to a list which is in fact nil. The solution is a standard one, just wrap your code in a `with-eval-after-load 'mu4e` block causing your code to wait till mu4e is fully loaded.

In your case this would look like:
``` elisp
(with-eval-after-load 'mu4e
  (add-to-list 'mu4e-marks
               '(spam
                 :char       "M"
                 :prompt     "spam"
                 :show-target (lambda (target) mu4e-spam-folder)
                 :action      (lambda (docid msg target)
                                (mu4e~proc-move docid mu4e-spam-folder "+S-u-N"))))
  (mu4e~headers-defun-mark-for spam)
  (define-key mu4e-headers-mode-map (kbd "M") 'mu4e-headers-mark-for-spam))
```

**Comment by rommeswi** [comment]
Given that a new version comes out soon and the problem does not exist in the develop branch, I close this. Many thanks for your help, @smile13241324
