### ISSUE TITLE
spacemacs/restart-emacs not working on WSL2

### ISSUE THREAD

**Issue by wang1zhen** [syl20bnr/spacemacs#14182]
I am using emacs through the WSL2 with X410, almost everything performs perfectly for now, but here go some minor issues:
whenever I press <SPC q r> to call spacemacs/restart-emacs-resume-layouts or press <SPC q R> to call spacemacs/restart-emacs, the emacs process gets terminated inside my WSL with no error information provided. The only information WSL provides is that when I run emacs, there is a warning of `dbind-WARNING **: 16:24:09.636: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-soVNZI44RC: Connection refused`, which I would regard as irrelevant.

**Comment by lebensterben** [comment]
the simplest solution is to use Linux. dbus support in WSL never worked perfectly

**Comment by wang1zhen** [comment]
Actually, it worked for WSL1, which makes it even more wierd.
