### ISSUE TITLE
Python lsp no completion for imported modules in python buffer

### ISSUE THREAD

**Issue by Hneuschmidt** [syl20bnr/spacemacs#14184]
#### Description :octocat:
When opening a python file in spacemacs, and having the python backend set to lsp I get no autocompletion for imported modules with pyls backend and an error message "unresolved-import" with mspyls backend.
Autocompletion for built in parts of python works fine with all backends.
Notably, autocompletion for imported modules works without any problems and very nicely in the python REPL ("C-c C-p")
I would hope to get this kind nicely working autocompletion also when editing files.

#### Reproduction guide :beetle:
- Start Emacs
- open python file
- type "`import os; os.`" or "`import numpy as np; np.`"

*Observed behaviour:* :eyes: :broken_heart:
nothing happens (pyls)
unresolved import error message appears when opening the file (mspyls)

*Expected behaviour:* :heart: :smile:
I get a dropdown menu of possible completions like I do in the REPL (np.array, np.linspace, ...)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: mine (rev. 664957dc3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html
 (python :variables python-backend 'lsp python-lsp-server 'pyls)
 ipython-notebook
 (c-c++ :variables c-c++-backend 'lsp-clangd c-c++-lsp-enable-semantic-highlight 'rainbow)
 rust ess java lsp debug git auto-completion syntax-checking
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 helm emacs-lisp treemacs multiple-cursors org latex bibtex spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

The python-lsp-server variable setting seems to have no effect on the choice of lsp server, I had to hardcode the priorities in the lsp-*.el files to select mspyls or pyls (I haven't managed to get pyright working yet)

**Comment by smile13241324** [comment]
Not sure why this is happening on your side. I am working with pyls privately and professionally in spacemacs and it works flawlessly. When I follow your example it just works for me, i.e. os. returns proper completions.

I also had a test with multiple lsp servers using the `python-lsp-server` settings which worked also.

Stuff you need to check:
* make sure you are NOT manually loading the respective python lsp package in your dot or init file.
* post your entire system config as is returned from `spacemacs/report-issue`
* Check my comments in https://github.com/syl20bnr/spacemacs/issues/14124 which was a similar problem.

**Comment by Hneuschmidt** [comment]
I have updated my first comment to include the system config.
My OS is OpenSuse, the branch "mine" is functionally equivalent to develop (and the issue persists on develop).
From the comments in #14124 I found out that both lsp-pyright and lsp-python-ms are to be found in `package-selected-packages`, but deleting them has no effect. There is no corresponding folder in  .cache to be found.

**Comment by Hneuschmidt** [comment]
The missing autocompletion on imports persists on a clean .spacemacs file with your config 2 from #14124

**Comment by Hneuschmidt** [comment]
It appears to be working now. I did update the develop branch once more, although that was before I tried the clean .spacemacs file.
I am using my old setup now and completion works for imported modules.
So I guess this issue can be closed.
