### ISSUE TITLE
Syntax highlighting for comments in Magit commit buffers with custom core.commentChar

### ISSUE THREAD

**Issue by Kazark** [syl20bnr/spacemacs#14195]
#### Description :octocat:

I set `git-commit-major-mode` to be `markdown-mode`, and to keep the `#` comment
lines that Git inserts from getting formatted like markdown headers, I switched
away from `#` as Git's comment delimiter. In my `.gitconfig`:

```ini
[core]
	commentChar = !
```

The commit buffer gets highlighted as Markdown, but the Git commit syntax
highlighting is lost. Thinking this may not already be supported or may require
special configuration, I asked a
[question](https://emacs.stackexchange.com/q/60915/19069) about it on the Emacs
StackExchange, and Jonas Bernoulli, maintainer of Magit, suggested:

> Try setting the comment-start variable using git-commit-setup-hook.

However, that did not fix the problem; when I did that, it made no difference.
Also, when I set commit buffers to have no major mode, it properly highlights
the comments that use `!`.

Jonas then recommended:

> Try to reproduce with `emacs -Q`, see [magit.vc/manual/magit/Debugging-Tools.html](https://magit.vc/manual/magit/Debugging-Tools.html)

However, I don't really know how to use Emacs from scratch; to date I have been
Spacemacs-only so I get a little lost in bare Emacs mode. After I said so, he
[responded](https://emacs.stackexchange.com/a/62123/19069):

> This is supposed to already work. Figuring out why it doesn't work for you
> will require a debugging effort on your part and I am afraid I won't be able
> to help you any more with that because I do not know enough about Spacemacs to
> do so. I suggest you ask for help from some other Spacemacs users.

I had a coworker who has built his own Emacs configuration test it out, and he
got the same result as Jonas: it works. So it looks like this is a Spacemacs
bug.

#### Reproduction guide :beetle:
- Set `core.commentChar` to `!` (or any other symbol that is not part of Markdown's syntax)
- Start Emacs
- `(setq git-commit-major-mode 'markdown-mode)`
- Enter a Git repo in Emacs
- Make a change
- Start to commit the change with Magit

*Observed behaviour:* :eyes: :broken_heart:

Git's commit lines at the bottom of the buffer are kept from being formatted
like headers by the switch to `!`, but these lines are no longer
syntax-highlighted according to the syntax of a Git commit; they show as they
would in a plain Markdown file, as plain text.

*Expected behaviour:* :heart: :smile:

To see markdown mode meshed with the an understanding of Git commits, so that
_above_ the comment lines would be highlighted with Markdown, and the comment
lines themselves would be highlighted.

#### System Info :computer:
- OS: darwin
- Emacs: 28.0.50 (gccemacs)
- Spacemacs: 0.300.0
- Spacemacs branch: keith (rev. 86cbb2777) (*Note*: this branch is barely divergent from the standard Spacemacs `develop`, I just use it so I can be dogfooding my own PRs before they hit upstream; currently I have none outstanding and the differences are minute)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking syntax-checking
                (auto-completion :variables auto-completion-enable-snippets-in-popup t)
                helm
                (org :variables org-enable-verb-support t)
                (unicode-fonts :variables unicode-fonts-ligature-modes
                               '(prog-mode))
                emoji games agda c-c++ clojure emacs-lisp fsharp graphviz
                (haskell :variables haskell-completion-backend 'ghci)
                html idris java javascript jsonnet kotlin markdown ocaml
                (scala :variables scala-backend 'scala-metals scala-enable-eldoc t scala-auto-start-backend t)
                scheme sql typescript yaml
                (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
                osx git github version-control
                (colors :variables colors-colorize-identifiers 'variables)
                (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: JPEG TIFF PNG NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES NATIVE_COMP THREADS XWIDGETS JSON PDUMPER LCMS2

#### Backtrace :paw_prints:

N/A

**Comment by lebensterben** [comment]
Run `(magit-emacs-Q-command)` and get the shell command to start emacs with only magit.
Then you start at scratch buffer, you can enter the following

```elisp
(defun set-comment-start () (interactive) (setq comment-start "!"))
(defun show-comment-start () (interactive) (message "%s" comment-start))
(add-hook 'git-commit-setup-hook 'set-comment-start)
```
Press M-x and type `eval-buffer`.

Then, use the GUI menu to open a file in a git repository. `M-x magit-status`. Then use arrow key move to a modified file, stage it and enter commit mode as usual.

You can use `M-x show-comment-start` to verify it's "!".

On my computer it's working correctly.

**Comment by lebensterben** [comment]
BTW,
```emacs-lisp
(add-hook 'git-commit-setup-hook (lambda () (setq-local comment-start "!")))
```
this works for me.

If this doesn't work for you, probably it's because markdown mode set comment-start to #

**Comment by Kazark** [comment]
Okay, so I'm an idiot. I didn't realize that in the `add-hook` you had to wrap the `setq-local` in a lambda. 🤦‍♂️ Thanks for the help @lebensterben .

**Comment by Kazark** [comment]
Actually, scratch that, I spoke to soon. I had unset `markdown-mode` again and that's why the comments were working before. I had used a `defun` previously instead of a `lambda` and it should be the same thing.

**Comment by Kazark** [comment]
Okay, so I went through the debugging steps you gave, and they were helpful, but the problem is not that `comment-start` doesn't work in the abstract, but that it doesn't work with `markdown-mode` enabled in the Git commit buffer via `git-commit-major-mode`. I guess I'll have to add a path to the startup command to get `markdown-mode` enabled.

**Comment by Kazark** [comment]
I was able to add `markdown-mode` to the load path, go through the steps you gave with the addition of putting `(setq git-commit-major-mode 'markdown-mode)` in the buffer that I evaled, _and everything worked_. So that certainly demonstrates that there is something in my Spacemacs setup that is jacking this up when the full thing gets loaded.

**Comment by Kazark** [comment]
This makes me suspect that something in the Git layer is messing it up.

**Comment by Kazark** [comment]
It is not the Git layer. I commented out the vast majority of that layer and nothing was different.

So then I looked at the Markdown layer. In the end what I did was to remove `markdown` from my layer list and to just add `markdown-mode` to my additional packages. Now it is working.

Ergo, there is something wrong in the Markdown layer. I wonder if it is the use of `mmm`.

**Comment by Kazark** [comment]
Confirmed. `mmm` is causing the issues.
