### ISSUE TITLE
latexmk not working properly in LaTeX mode

### ISSUE THREAD

**Issue by wang1zhen** [syl20bnr/spacemacs#14192]
I have enabled latex layer in my config file and specified 'LatexMk' as the build command:
```
(latex :variables
            latex-backend 'company-auctex
            latex-build-command "LatexMk"
            latex-enable-auto-fill t
            latex-enable-folding t
            latex-enable-magic nil
            ;; magic-latex-enable-block-highlight t
            ;; magic-latex-enable-block-align t
            ;; magic-latex-enable-pretty-symbols nil
            ;; magic-latex-enable-suscript nil
            ;; magic-latex-enable-inline-image nil
            )
```
And here goes my test latex file (with Chinese characters, so I wished to build this file with xelatex)

```latex
\documentclass[a4paper]{article}
\usepackage{ctex}
\usepackage{amsmath}
\usepackage{lipsum}

\author{test}

\begin{document}

\tableofcontents

\section{formulas}

\subsection{Newton's Law}

\begin{equation}
  F=ma
  \label{eq1}
\end{equation}

As mentioned above, equation \ref{eq1} is Newton's Law.

\section{中文}

式\ref{eq1}是牛顿第二定律。

\subsection{lorem-ipsum}

\lipsum[1]

\end{document}
```

I have created a .latexmkrc file to use xelatex instead of pdflatex while building the doc:

```
$pdflatex = 'pdflatex -file-line-error -hold-on-error -interaction=nonstopmode -synctex=1 %O %S';
$xelatex = 'xelatex -file-line-error -hold-on-error -interaction=nonstopmode -no-pdf -synctex=1 %O %S';
$xdvipdfmx = "xdvipdfmx -E -o %D %O %S";
$pdf_mode = 5;
$out_dir = './LaTeX.out';
```

If I run `latexmk main.tex' in command line, everything works fine, and this is the beginning of the log file:
```
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/Debian) (preloaded format=xelatex 2020.12.4)  6 DEC 2020 16:37
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**main.tex
(./main.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
```

However, if I build the doc from spacemacs, with `SPC m b`, `, b` or `, ,` then choose LatexMk, they all go wrong.

ERROR message:
```
ERROR: Critical Package ctex Error: CTeX fontset `fandol' is unavailable in current

--- TeX said ---

(ctex)                         mode.

Type <return> to continue.
 ...                                              
                                                  
l.113   }
         
--- HELP ---
No help available
```

As I claimed in my .latexmkrc file, the output files have gone to `LaTeX.out` directory, which means that my .latexmkrc has been applied, yet the `LaTeX.out/main.log` shows:

```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex 2020.12.4)  6 DEC 2020 16:42
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**main.tex
(./main.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
```

pdflatex have been used to build the doc? That is definitely not what I expected.

Thanks for your patience, and I really wish to know how to fix it.

**Comment by lebensterben** [comment]
Make sure LatexMk is in the PATH.
One way is "SPC f e C-e" to recreate the `~/.spacemacs.env` file, from which you can verify if LatexMk is in the PATH.

**Comment by wang1zhen** [comment]
This issue persists.

```
❯ which latexmk
/usr/bin/latexmk
```

in my .spacemacs.env file, /usr/bin is included in path

```
PATH=/home/wang1zhen/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/sbin:/sbin:/usr/games:/usr/local/games:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files (x86)/Bitvise SSH Client:/mnt/c/Go/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program Files/dotnet:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Polyspace/R2020a/runtime/win64:/mnt/c/Program Files/Polyspace/R2020a/bin:/mnt/c/Program Files (x86)/dotnet:/mnt/c/Users/wang1zhen/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Bandizip:/mnt/c/Users/wang1zhen/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/texlive/2019/bin/win32:/mnt/c/Users/wang1zhen/go/bin:/usr/lib/emacs/26.3/x86_64-linux-gnu
```

**Comment by lebensterben** [comment]
where do you installed ctex?

**Comment by wang1zhen** [comment]
I am on WSL Ubuntu, and I have installed texlive-full. Since I could build the doc from command line, I guess ctex environment is okay with me.

**Comment by lebensterben** [comment]
@wang1zhen
I'm asking because sometimes you've same program installed at different location. Say, one from the distro package manager, and one installed by yourself. They're very likely to be configured to use different library or data directory.
So clearly `ctex` is installed somewhere. I just want to make sure
- If there're multiple TeX installed, the one seen by emacs should be the once you use in the interactive shell
- If you only have one TeX installed, but it uses a non-standard library directory, and it's specified by another environment variable, you need to check whether emacs can see that variable.

**Comment by wang1zhen** [comment]
the tex environment is purely installed by `sudo apt install texlive-full` and nothing more.

**Comment by lebensterben** [comment]
I can confirm this bug.

**Comment by lebensterben** [comment]
The error results from these line:

https://github.com/tom-tan/auctex-latexmk/blob/4d353522650d7685acbf1d38f7dbc504f734bd84/auctex-latexmk.el#L107-L114

To solve this, you can use `customize-variable`, change the value of `Tex-Command-List`, where you will see something like

```text
Name: LatexMk
Command: latexmk %(-PDF)%S%(mode) %(file-line-error) %extraopts) %t
```

Just remove `%(-PDF)`, that will call `pdflatex`...

**Comment by lebensterben** [comment]
A better way is to set `latex-build-command` in your `.spacemacs` to, for example, `LatexMk-xetex`, and instead of modifing `LatexMk` entry, adding a new entry s.t.:

```text
Name: LatexMk
Command: latexmk %S%(mode) %(file-line-error) %(extraopts) %t
```

**Comment by wang1zhen** [comment]
Thanks to @lebensterben , I got this fixed. Here I'd like to share my solution.

I edited my `~/.spacemacs.d/init.el` file, and changed the the `latex-build-command` to `"LatexMk-xetex"`

and in my user-config part, I manually added this `"LatexMk-xetex"`:

```
(setq TeX-command-list
        (cons '("LatexMk-xetex" "latexmk %S%(mode) %(file-line-error) %(extraopts) %t" TeX-run-latexmk nil
                (plain-tex-mode latex-mode doctex-mode)
                :help "Run LatexMk (xelatex)")
              TeX-command-list))
```
After reloading the configs, the build command inside spacemacs works as expected.

Hope this could help anyone who might also get confused in such issues and again thanks to lebensterben.

**Comment by wang1zhen** [comment]
I tried `latex-build-command "LatexMk-xetex"` and put the following commands into my user-config, yet it didn't work:
```
  (defun latex-mode-build-command ()
    (setq TeX-command-list
          (cons '("LatexMk-xetex" "latexmk %S%(mode) %(file-line-error) %(extraopts) %t" TeX-run-latexmk nil
                  (plain-tex-mode latex-mode doctex-mode)
                  :help "Run LatexMk (xelatex)")
                TeX-command-list)))
  (add-hook 'LaTeX-mode-hook 'latex-mode-build-command 10)

```
the error is
```
TeX-command: Symbol’s function definition is void: TeX-run-latexmk
```
how should I correct?

**Comment by lebensterben** [comment]
@wang1zhen
This is defined in auctex-latexmk package and you need to make sure that package is loaded.
So in addition to add-hook, you also need eval-after-load

**Comment by wang1zhen** [comment]
No success for me, maybe I'm not quite familiar with elisp
```
  (defun latex-mode-build-command ()
    (setq TeX-command-list
          (cons '("LatexMk-xetex" "latexmk %S%(mode) %(file-line-error) %(extraopts) %t" TeX-run-latexmk nil
                  (plain-tex-mode latex-mode doctex-mode)
                  :help "Run LatexMk (xelatex)")
                TeX-command-list)))
  (with-eval-after-load "auctex-latexmk"
    (add-hook 'LaTeX-mode-hook 'latex-mode-build-command)
    )
```
when I tried `C-c C-c`, there is no `LatexMk` or `LatexMk-xetex` in the list.

**Comment by lebensterben** [comment]
'acutex-latexmk instead of "acutex-latexmk"

**Comment by lebensterben** [comment]
```elisp
(defun latex-mode-build-command ()
  (setq TeX-command-list
        (cons '("LatexMk-xetex" "latexmk %S%(mode) %(file-line-error) %(extraopts) %t"
                'TeX-run-latexmk nil
                (plain-tex-mode latex-mode doctex-mode)
                :help "Run LatexMk (xelatex)")
              TeX-command-list)))
(with-eval-after-load 'auctex-latexmk
  (add-hook 'LaTeX-mode-hook 'latex-mode-build-command))
```

**Comment by wang1zhen** [comment]
Sorry, I don't think the code above could work, there is still no "latexmk" or "latexmk-xetex" available for `TeX-command-list`. Plus, I didn't quote TeX-run-latexmk because [https://github.com/tom-tan/auctex-latexmk/blob/4d353522650d7685acbf1d38f7dbc504f734bd84/auctex-latexmk.el#L107-L114](https://github.com/tom-tan/auctex-latexmk/blob/4d353522650d7685acbf1d38f7dbc504f734bd84/auctex-latexmk.el#L107-L114) did not quote it so I copied it.

I feel kind of tired of the latexmk issue, I would prefer building the doc with command line instead of inside spacemacs. Anyway, thanks for your response and I would keep this issue open in case there would be a fix.

**Comment by lebensterben** [comment]
Overleaf is easy to use.

**Comment by wang1zhen** [comment]
update:

I have found an indecent fix to use xelatex as the compiler for latexmk.

in the spacemacs config file, use
```
latex-build-command "LatexMk"
```

and then hack the `.latexmkrc` file in the home directory:
```
$pdflatex = 'xelatex -file-line-error -hold-on-error -interaction=nonstopmode -no-pdf -synctex=1 %O %S';
$pdf_mode = 1;
```

It's a nasty hack by cheating latexmk to use `xelatex` for `pdflatex` recipe. Yet before a better solution comes out, this might be an acceptable solution, and I will leave the issue open.

**Comment by lebensterben** [comment]
Try having this in your latex layout config:

`(latex :variables TeX-engine 'xetex)`

**Comment by wang1zhen** [comment]
Great! This solution works for me, and thanks for your help!
