### ISSUE TITLE
projectile-dired not working

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#14203]
#### Description :octocat:
I have this tweak in my user-config:
```lisp
  (setq
   projectile-enable-caching 't
   ;; open dired project
   projectile-switch-project-action 'projectile-dired)
```

Since a few days, the `projectile-dired` is not working anymore.
Full `.emacs.d/private` can be found here: https://gitlab.com/phenix-factory/config-spacemacs

#### Reproduction guide :beetle:
- Start Emacs with my tweak in the user-config
- Open a project

*Observed behaviour:* :eyes: :broken_heart:
should open the root of the project in dired

*Expected behaviour:* :heart: :smile:
helm ask for a file

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c0f61fa03)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 helm emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 github markdown csv org
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom multi-term-program "/usr/bin/zsh")
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary nil enable-flyspell-auto-completion t)
 syntax-checking shell-scripts
 (php :variables php-backend 'lsp)
 restclient
 (sql :variables sql-capitalize-keywords t)
 (html :variables css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t web-fmt-tool 'prettier)
 lsp dap
 (javascript :variables javascript-fmt-tool 'prettier javascript-import-tool 'import-js javascript-backend 'lsp)
 (vue :variables vue-backend 'lsp)
 typescript prettier yaml finance colors multiple-cursors unicode-fonts
 (docker :variables docker-dockerfile-backend 'lsp)
 (version-control :variables version-control-global-margin t shell-default-term-shell "/bin/bash")
 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp/" mu4e-enable-notifications t mu4e-enable-mode-line t mu4e-use-maildirs-extension t)
 (python :variables python-backend 'lsp python-lsp-server 'pyls python-formatter 'black)
 imenu-list dash)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by tekacs** [comment]
I'm also experiencing this, using the https://github.com/practicalli/spacemacs.d/blob/5bcc7773aa0a8da785390a779609e73cb9dcd9bb/init.el configuration.

It doesn't appear to customize projectile in any way as far as I can tell.

**Comment by phenix-factory** [comment]
Well I updated modules and the problem is fixed !
