### ISSUE TITLE
"spc /" shortcut show "option ignore is ambiguous"

### ISSUE THREAD

**Issue by wutianjun5858** [syl20bnr/spacemacs#14209]
branch: develop
commit id: e7c9eda3fba9cad69e711a137f6296c47c42d381
issue:  "spc /" shortcut show "option ignore is ambiguous"

**Comment by wutianjun5858** [comment]
may be the os error

**Comment by mindgitrwx** [comment]
I've just installed this and the error does not be happened anymore.
https://github.com/ggreer/the_silver_searcher
