### ISSUE TITLE
[perf] Spacemacs should make sure that it loads dash bytecompiled.

### ISSUE THREAD

**Issue by yyoncho** [syl20bnr/spacemacs#14213]
Without doing this the performance of spacemacs is seriously hurt. As a result, the dash functions run 2+ times slower than they would run if they are used in vanilla and they are on the critical path of many packages. 

The same most likely applies to `ht`

**Comment by thanhvg** [comment]
Great idea, we can just re-implement  all `ht` functions we are using in core then remove `ht` and `dash` from our dependency all together. My quick search for (require 'ht) and (require 'dash) suggests that `dash` is required only for `ht` and the scope of `ht` dependency is not too big.  

./core/core-configuration-layer.el:20:(require 'ht)
./layers/+completion/helm/local/helm-spacemacs-help/helm-spacemacs-help.el:30:(require 'ht)
./layers/+completion/ivy/local/ivy-spacemacs-help/ivy-spacemacs-help.el:30:(require 'ht)

**Comment by smile13241324** [comment]
Good finding, yes indeed lets duplicate what we need for the core than let the packages load their compile version of ht and dash themselves. Also this means less forks to manually maintain :).

**Comment by yyoncho** [comment]
Just want to mention that even if `dash` is not required, it is still used in several places. Search for -filter/-if-let.

**Comment by lebensterben** [comment]
I'm working on a PR right now and it requires `dash`.

**Comment by emacs18** [comment]
I hope that folks can find a way for spacemacs not to have to have its own copy of other packages such as dash, ht, package-build, etc.  The problem with keeping a copy within spacemacs is that upstream changes are not picked up often enough.  For example package-build copy within spacemcs was not updated for months or years until suddenly spacemacs upgraded it some time ago.  Due to lots of api changes, all my custom code stopped working that relied on old api.  I still have not recovered this shock after many months.  That is why one of the changes I made on m own branch of spacemacs is to delete package-build copy within spacemacs.  I will now try to do the same for dash and ht so that I always use these packages that I have installed rather than using possibly stale copy that resides within spacemacs.

**Comment by lebensterben** [comment]
>I hope that folks can find a way for spacemacs not to have to have its own copy of other packages such as dash, ht, package-build, etc.  The problem with keeping a copy within spacemacs is that upstream changes are not picked up often enough.  For example package-build copy within spacemcs was not updated for months or years until suddenly spacemacs upgraded it some time ago.  Due to lots of api changes, all my custom code stopped working that relied on old api.  I still have not recovered this shock after many months.  That is why one of the changes I made on my own branch of spacemacs is to delete package-build copy within spacemacs.  I will now try to do the same for dash and ht so that I always use these packages that I have installed rather than using possibly stale copy that resides within spacemacs.

@emacs18 I second this.

**Comment by smile13241324** [comment]
Yep, we need to find a better solution for this right now it has a lot of side effects and is a hell to be kept up-to-date, maybe we can parts of this to our own code to isolate the core from these external libraries.

**Comment by emacs18** [comment]
I am in the process of experimenting with [straight](https://github.com/raxod502/straight.el) package manager. Part of the change I made with this effort is to remove most files from `core/libs` directory as detailed in [this change](https://github.com/emacs18/spacemacs/commit/f7b723a56213da6d46387595d384cb51e5107879) where the core packages are installed normally early on. This seems to be working fine so far. Whether `straight.el` or `package.el` is used, perhaps installing the core packages early on could work.

**Comment by smile13241324** [comment]
I like this idea @emacs18 however I'd still like to discuss this first with the more experienced lispers in the team before doing changes on this crucial part of Spacemacs. There may be a reason why it has not been done this way in the first place :thinking:.
