### ISSUE TITLE
Using pyright in python lsp mode is very slow

### ISSUE THREAD

**Issue by AkashGanesan** [syl20bnr/spacemacs#14210]
#### Description :octocat:
Python autocompletion when using pyright is slow

#### Reproduction guide :beetle:
- Start Emacs
- M-x pyvenv-workon <custom-workspace>

*Observed behaviour:* :eyes: :broken_heart:
While completion does work, it become unresponsive for a half a second to a
second for every character being typed. Initial load up before auto completion
works is also slow.  Microsoft's lsp works as intended.

*Expected behaviour:* :heart: :smile:
Responsive auto completion :)  

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. 4b3ab4052)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm bibtex better-defaults emacs-lisp git markdown org lsp
      (julia :variables julia-backend 'elpy)
      (python :variables python-backend 'lsp python-lsp-server 'pyright)
      ipython-notebook spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by lebensterben** [comment]
are you working on a new project or an existing code base?

I suspect it’s be slow if it’s a existing code base which also lacks sufficient type information.

**Comment by AkashGanesan** [comment]
On a new project.  The thing is, Microsoft's LSP implementation is really fast.  It has issues when trying to complete module names.

I am using conda and pyvenv to set the environment if that helps.

**Comment by tshu-w** [comment]
I also sometimes have performance issues (on tramp file), and restarting the server might help.

**Comment by AkashGanesan** [comment]
I'm not using tramp.  I did a complete restart as well as the server but to no avail.
