### ISSUE TITLE
Python run error, while tested ok with python and ipython outside the spacemacs.

### ISSUE THREAD

**Issue by fratcn** [syl20bnr/spacemacs#14219]
#### Description :octocat:

Python run error, while tested ok with python and ipython outside the spacemacs.
#### Reproduction guide :beetle:
- Start Emacs

The python code:

```
def c2f(celsius):
    fahrenheit=celsius*9.0/5+32
    return fahrenheit

celsius=float(input("Enter a temprature in Celsius:"))
fahrenheit=c2f(celsius)
print("That's",fahrenheit,"degrees Fahrenheit")
```

*Observed behaviour:* :eyes: :broken_heart:

```
-*- mode: compilation; default-directory: "~/temp/test/" -*-
Comint started at Fri Dec 18 11:47:43

/usr/bin/ipython test2.py
Enter a temprature in Celsius:34
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/temp/test/test2.py in <module>
      4     return fahrenheit
      5 
----> 6 celsius=float(input("Enter a temprature in Celsius:"))
      7 fahrenheit=c2f(celsius)
      8 print("That's",fahrenheit,"degrees Fahrenheit")

ValueError: could not convert string to float: '34\t\x08\x08\x08\x08\x0834\t\x08\x08\x08\x08\x0834\t\x08\x08\x08\x08\x0834'

Inferior Python exited abnormally with code 1 at Fri Dec 18 11:48:02

```
*Expected behaviour:* :heart: :smile:

```
Enter a temprature in Celsius:34
That's 93.2 degrees Fahrenheit
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0f21303ca)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(better-defaults emacs-lisp
                 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/dotfiles/spacemacs.d/snippets/")
                 helm mu4e markdown merat
                 (org :variables org-enable-github-support t org-enable-reveal-js-support t org-bullets-bullet-list
                      '("■" "◆" "▲" "▶")
                      org-agenda-dir "~/Writing/org-notes/" org-projectile-file "~/Writing/org-notes/todos.org")
                 html media yaml
                 (shell :variables shell-default-shell 'vterm shell-default-term-shell "/bin/zsh" spacemacs-vterm-history-file-location "~/.zsh_history")
                 epub pdf
                 (python :variables python-shell-completion-native nil python-test-runner 'pytest python-enable-yapf-format-on-save t)
                 treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Not able to replicate your error.
```
-*- mode: compilation; default-directory: "/tmp/" -*-
Comint started at Fri Dec 18 07:45:06

/home/lucius/.pyenv/shims/python test.py
Enter a temprature in Celsius:37
That's 98.6 degrees Fahrenheit

Inferior Python finished at Fri Dec 18 07:45:12
```

**Comment by fratcn** [comment]
The trick is:
The error happens when emacs start edit the code,after a while, the error may goes away and output the right answer,the after a while,this python-running error comes back again.
Really don't know why the spacemacs act like a unstable human.
The spacemacs is installed clean from official github,and the python layer is added following the dotspacemancs instruction.

**Comment by fratcn** [comment]
```
SPC m c C runs the command spacemacs/python-execute-file-focus, which is an
interactive Lisp function in ‘../../funcs.el’.

It is bound to <M-return> c C, M-m m c C, and many ordinary text characters.

(spacemacs/python-execute-file-focus ARG)

Execute a python script in a shell and switch to the shell buffer in
 ‘insert state’.
```

guess something wrong with the ‘interactive Lisp function in ‘../../funcs.el’’

**Comment by fratcn** [comment]
Today I backup emacs.d and turn from master to delevop branch of Spacemacs,this error replicate again.

**Comment by fratcn** [comment]
I find out the lisp code of “python-execute-file” in ~/.emacs.d/layers/+lang/python/funcs.el：
`   (defun spacemacs/python-execute-file (arg)
  "Execute a python script in a shell."
  (interactive "P")
  ;; set compile command to buffer-file-name
  ;; universal argument put compile buffer in comint mode
  (let ((universal-argument t)
        (compile-command (format "%s %s"
                                 (spacemacs/pyenv-executable-find python-shell-interpreter)
                                 (shell-quote-argument (file-name-nondirectory buffer-file-name)))))
    (if arg
        (call-interactively 'compile)
      (compile compile-command t)
      (with-current-buffer (get-buffer "*compilation*")
        (inferior-python-mode)))))

(defun spacemacs/python-execute-file-focus (arg)
  "Execute a python script in a shell and switch to the shell buffer in
 `insert state'."
  (interactive "P")
  (spacemacs/python-execute-file arg)
  (switch-to-buffer-other-window "*compilation*")
  (end-of-buffer)
  (evil-insert-state))`

Anything wrong with it？

**Comment by lebensterben** [comment]
Since I'm not able to replicate the error, I cannot debug this.

**Comment by alexey0308** [comment]
`python-execute-file` creates "compilation-mode" buffer, which looks like not playing well with an interactive input. Probably `python-shell-send-buffer-switch` is more suitable for this case (`, s B`)

**Comment by fratcn** [comment]
`python-shell-send-buffer-switch` work like this:

```
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: Enter a temprature in Celsius:-10
Out[4]: -10

In [5]: Enter a temprature in Celsius:25
Out[8]: 25

In [9]: 

In [9]: Enter a temprature in Celsius:0
That's 32.0 degrees Fahrenheit

In [12]: Enter a temprature in Celsius:-10
Out[15]: -10

In [16]: Enter a temprature in Celsius:-10
Out[19]: -10

In [20]: Enter a temprature in Celsius:-10
Out[23]: -10

In [24]: Enter a temprature in Celsius:25
That's 77.0 degrees Fahrenheit

In [25]: Enter a temprature in Celsius:-10
Out[28]: -10

```

the output isn't right all the time,but is right just twice.

**Comment by alexey0308** [comment]
Does disabling company-mode in either one (inferior buffer or compilation buffer) solves the problem?

**Comment by tshu-w** [comment]
Maybe you could try a clean configuration with just the Python layer.

**Comment by fratcn** [comment]
well，it works when I clear the auto-completion layer.
Thank you.

**Comment by alexey0308** [comment]
@fratcn emacs sends commands to get completions meanwhile you are typing the input, hence everything breaks.

**Comment by lebensterben** [comment]
>@fratcn emacs sends commands to get completions meanwhile you are typing the input, hence everything breaks. ...

@alexey0308
How's this possible? Executing the current script should be instantaneous, and how is it possible to break it by keep typing?

**Comment by alexey0308** [comment]
@lebensterben the input command make script waiting for the user input => user starts typing => completion query sent to the interpreter before user press <enter>. You can see the error msg in the first post: can not convert "34\t\x08...", so additional string was sent after the user typed 34.
But this is only a  guess.

**Comment by lebensterben** [comment]
>@lebensterben the input command makes script waiting for the user input => user starts typing => completion query sent to the interpreter before user press "enter". You can see the error msg in the first post: can not convert "34\t\x08...", so additional string was sent after the user typed 34. ...

@alexey0308 I also had tried to type input while the focus is not in the inferior shell, but I don't see this error. Have you replicated this?

**Comment by alexey0308** [comment]
But if you send the buffer to the inferior shell, you have to type the input within the inferior shell, I am confused now,
how do you type  "while the focus is **not** in the inferior shell"?

In my case, there is no error output for inferior buffer, same as [here](https://github.com/syl20bnr/spacemacs/issues/14219#issuecomment-748622181). If I enter fast, so completion's not started yet, I get the Fahrenheit. If I enter with some pause before pressing enter, no Fahrenheit in output.

**Comment by lebensterben** [comment]
>But if you send the buffer to the inferior shell, you have to type the input within the inferior shell, I am confused now, ...

@alexey0308 I kept typing while the focus is not in inferior shell, and therefore nothing is actually input there.
Once I switch to the inferior shell, auto-completion is not in effect, as it shouldn't be.

**Comment by alexey0308** [comment]
@lebensterben As I understand, with lsp-mode, completion in the file buffer comes from the lsp server, but in the inferior buffer from the inferior buffer process, hence they are independent and typing in the file buffer has no effect.
