### ISSUE TITLE
Featrue request - keybinding for which-key-show-major-mode

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#14225]
I have just discovered the command `which-key-show-(full)-major-mode`. It looks quite useful documentation wise, e.g. for org-mode or eww browser etc., except for one issue, namely it does not correctly show correct evilified keybindings. Although this feature request really is not of high priority, I thought I will still propose to make a keybinding for it, because maybe one of you likes this feature too and maybe some knowledgeable person knows how to implement it quickly, or likes to implement it as a hobby project.
I think binding it under `SPC h k m/M` would be a natural choice, moving `SPC h k` to `SPC h k k` under a 'keymaps' prefix.
There is already `SPC h d m` of course so it is really not of high importance. Just I was not aware of this command, and I was not sure if you guys knew about it.

**Comment by lebensterben** [comment]
@dalanicolai 
Are you still interested in this?

I think your suggested `SPC h k *` bindings are great.
And in addition we can have `SPC h k K` for `which-key-show-full-keymap`.

**Comment by dalanicolai** [comment]
@lebensterben Well, for me personally it does not make much of a difference. But of course, I still think that Spacemacs should help as much as possible with discoverability (which for sure does not mean expose as many features as possible; that hinders discoverability). But I think this is a good case where this increases discoverability. So maybe when you or I got some time then we can quickly implement it. I think I know how to implement these things much better now than last year....
