### ISSUE TITLE
spacemacs.org homepage

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#1423]
`spacemacs.org` is live (thanks to @naseer) with a temporary github pages generated site.

We need a beautiful, minimalistic landing page for spacemacs with a nav bar on top, the logo as the main element in the center, and a button like `Clone it Now` which could just display the required `git clone` command line for now.

In the future it would be useful to code some basic installation scripts and change the button to `Install it Now`.

**Comment by cpaulik** [comment]
Do you want to use a static site generator to render all the README files or is it too much work to maintain those files in the gh-pages branch?

What do you mean by `basic installation scripts`? Isn't `git clone` all we need for spacemacs? Or do you want to make a spacemacs installer that also includes emacs?

**Comment by syl20bnr** [comment]
For now a static site in the gh-pages branch is OK. I may split this into its own repository later if we judge that spacemacs repo size is more important than having the site available offline.

`basic installation scripts` would be to automate the git clone, with some basic support for backing up the current configuration of the user. We could ask the user if he wants to backup first for instance.

I'm not sure we want to install emacs for the user, there is too many versions/packages managers.

**Comment by stormpat** [comment]
:+1:

**Comment by naseer** [comment]
@syl20bnr - I'm assuming you have a page  like https://atom.io/ in mind?

**Comment by syl20bnr** [comment]
@naseer yes, this is a good example :+1:

**Comment by CarlQLange** [comment]
I'm happy to build spacemacs.org if nobody else wants to take it on, but don't really plan to maintain it, so if you want a nice shiny frontpage with a bunch of links to github cool, otherwise someone else should take it

**Comment by bobbyangelov** [comment]
Hi @syl20bnr , @naseer and @CarlQLange . I would like to have a go. From what I gathered it should be similar to Atom's website and also static for now. I have some knowledge of Jekyll, so we can build on that in the future. I'm going to start coding and will show you what I've got soon :) :neckbeard:

**Comment by CarlQLange** [comment]
:+1:

**Comment by naseer** [comment]
:+1:

**Comment by bobbyangelov** [comment]
I created a PR. Feedback would be great! I am especially not sure about the text content :smile:

**Comment by TheBB** [comment]
Can I get a briefing on how the domains are set up now?

spacemacs.org works. I kind of expected to see the same site at http://syl20bnr.github.io/spacemacs but nothing there. However I can see @bobbyangelov's at http://bobbyangelov.github.io/spacemacs.

I assume it's still the case what whatever is in `gh-pages` ends up on spacemacs.org immediately?

**Comment by bobbyangelov** [comment]
Yes, everything on `gh-pages` should be seen on spacemacs.org.

**Comment by syl20bnr** [comment]
@TheBB `syl20bnr.github.io`redirects to my blog which is empty, I'll have to fix it on my side to redirect to `spacemacs.org`.

**Comment by razetime** [comment]
I thought that maybe you could change the logo lettering to something like this:
#spaceᐧmacs

**Comment by StreakyCobra** [comment]
Concepts are not `space` and `macs` , neither they are `spac` and `emacs`. They are `space` and `emacs`, so I don't think it can easily be split.

- `space·macs`: "macs" represents nothing
- `spac·emacs`: "spac" represents nothing
- `spac·e·macs`: both represents nothing, and too complex :-p
- `spacemacs`: probably the best ^^
