### ISSUE TITLE
gpu layer installation fails

### ISSUE THREAD

**Issue by zbinkz** [syl20bnr/spacemacs#14236]
Hi,

Just tried installing the gpu layer, added it to `dotspacemacs-configuration-layers` and ran <M-m f e R> as usual but ended up with a fail on the gpu layer test. Everything else is fine (adding the git layer no issues) and I have the latest git update. Has the gpu layer been replaced with something else or am I missing something?

Thanks,
Z

**Comment by smile13241324** [comment]
@zbinkz just checked on my dotfile, gpu layer is correctly installed. Can you share your system information as is returned by `SPC h I` and reproduce on latest develop with a standard user config?

**Comment by zbinkz** [comment]
@smile13241324 never mind. I just installed Debian 10.7 from scratch and the issue went away. Something was probably off in my 10.6 install. Cheers...
