### ISSUE TITLE
Wrong type argument: stringp, async

### ISSUE THREAD

**Issue by dikeeris** [syl20bnr/spacemacs#14239]
I set up everything and then I get the error of the title. Initializing emacs with --debug-init gives this as result:

> 
> Debugger entered--Lisp error: (wrong-type-argument stringp async)
>   intern(async)
>   package-desc-from-define(async "20200809.501" "Asynchronous processing in Emacs" '((emacs "24.3")) :commit "14f48de586b0977e3470f053b810d77b07ea427a" :authors (("John Wiegley" . "jwiegley@gmail.com")) :maintainer ("John Wiegley" . "jwiegley@gmail.com") :keywords ("convenience" "async") :url "https://github.com/jwiegley/emacs-async")
>   apply(package-desc-from-define (async "20200809.501" "Asynchronous processing in Emacs" '((emacs "24.3")) :commit "14f48de586b0977e3470f053b810d77b07ea427a" :authors (("John Wiegley" . "jwiegley@gmail.com")) :maintainer ("John Wiegley" . "jwiegley@gmail.com") :keywords ("convenience" "async") :url "https://github.com/jwiegley/emacs-async"))
>   package-process-define-package((define-package async "20200809.501" "Asynchronous processing in Emacs" '((emacs "24.3")) :commit "14f48de586b0977e3470f053b810d77b07ea427a" :authors (("John Wiegley" . "jwiegley@gmail.com")) :maintainer ("John Wiegley" . "jwiegley@gmail.com") :keywords ("convenience" "async") :url "https://github.com/jwiegley/emacs-async"))
>   package-load-descriptor("/home/"username"/.emacs.d/elpa/27.1/develop/async-202008...")
>   package-load-all-descriptors()
>   package-initialize(noactivate)
>   (if package--initialized nil (setq configuration-layer-rollback-directory (configuration-layer/elpa-directory configuration-layer--rollback-root-directory)) (setq package-user-dir (configuration-layer/elpa-directory configuration-layer--elpa-root-directory)) (setq package-archives (configuration-layer//resolve-package-archives configuration-layer-elpa-archives)) (setq package-enable-at-startup nil) (package-initialize 'noactivate) (if (package-installed-p 'org-plus-contrib) (progn (spacemacs-buffer/message "Initializing Org early...") (configuration-layer//activate-package 'org-plus-contrib))))
>   configuration-layer/initialize()
>   spacemacs/init()
>   (let ((file-name-handler-alist nil)) (require 'core-spacemacs) (spacemacs/dump-restore-load-path) (configuration-layer/load-lock-file) (spacemacs/init) (configuration-layer/stable-elpa-init) (configuration-layer/load) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (spacemacs/dump-eval-delayed-functions) (if (and dotspacemacs-enable-server (not (spacemacs-is-dumping-p))) (progn (require 'server) (if dotspacemacs-server-socket-dir (progn (setq server-socket-dir dotspacemacs-server-socket-dir))) (if (server-running-p) nil (message "Starting a server...") (server-start)))))
>   (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (let ((file-name-handler-alist nil)) (require 'core-spacemacs) (spacemacs/dump-restore-load-path) (configuration-layer/load-lock-file) (spacemacs/init) (configuration-layer/stable-elpa-init) (configuration-layer/load) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (spacemacs/dump-eval-delayed-functions) (if (and dotspacemacs-enable-server (not (spacemacs-is-dumping-p))) (progn (require 'server) (if dotspacemacs-server-socket-dir (progn (setq server-socket-dir dotspacemacs-server-socket-dir))) (if (server-running-p) nil (message "Starting a server...") (server-start))))))
>   eval-buffer(#<buffer  *load*> nil "/home/"username"/.emacs.d/init.el" nil t)  ; Reading at buffer position 1918
>   load-with-code-conversion("/home/"username"/.emacs.d/init.el" "/home/"username"/.emacs.d/init.el" t t)
>   load("/home/"username"/.emacs.d/init" noerror nomessage)
>   startup--load-user-init-file(#f(compiled-function () #<bytecode 0xcc6545>) #f(compiled-function () #<bytecode 0xcc655d>) t)
>   command-line()
>   normal-top-level()

An emacs --version gives this message:

> GNU Emacs 27.1
> Copyright (C) 2020 Free Software Foundation, Inc.
> GNU Emacs comes with ABSOLUTELY NO WARRANTY.
> You may redistribute copies of GNU Emacs
> under the terms of the GNU General Public License.
> For more information about these matters, see the file named COPYING.

**Comment by flowerinthenight** [comment]
Got the same error today as well with version:
```
GNU Emacs 26.3
Copyright (C) 2019 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

**Comment by io12** [comment]
This seems to be a bug in MELPA.

https://github.com/melpa/melpa/issues/7312

**Comment by dikeeris** [comment]
> This seems to be a bug in MELPA.
> 
> [melpa/melpa#7312](https://github.com/melpa/melpa/issues/7312)

You might be correct, it seems like it is.

**Comment by Deanamic** [comment]
While this is not fixed, one possible solution is to enable the spacelpa repository in .spacemacs

**Comment by robbyoconnor** [comment]
Fixed upstream.
