### ISSUE TITLE
JavaScript mode top bar missing glyphs

### ISSUE THREAD

**Issue by tgroshon** [syl20bnr/spacemacs#14245]
#### Description :octocat:

Since updating to Emacs 27.1 and pulling latest `develop` branch, my JavaScript files (both under js2-mode and rjsx-mode) include a top bar with file path and symbol breadcrumbs, but some glyphs/icons are missing.

I have 'Source Code Pro' font installed and the following settings:

```elisp

(defun dotspacemacs/init ()
  ;; ... other stuff
  dotspacemacs-default-font '("Source Code Pro"
                              :size 11.0
                              :weight normal
                              :width normal))
```

![Screenshot from 2020-12-29 14-02-12](https://user-images.githubusercontent.com/1794859/103308260-fad91f00-49df-11eb-9ef7-f38d9435e950.png)

 And same rough situation in terminal ui:

![Screenshot from 2020-12-29 14-18-01](https://user-images.githubusercontent.com/1794859/103308551-b306c780-49e0-11eb-8a9d-077ac0205eee.png)

My Powerline glyphs at the bottom of the buffer are all fine.  It's just the top bar (which I've only seen on js mode files).

![Screenshot from 2020-12-29 14-14-19](https://user-images.githubusercontent.com/1794859/103308314-29ef9080-49e0-11eb-81c1-bfc7201c23c3.png)

#### Reproduction guide :beetle:
- Start Emacs
- Open a JavaScript file

*Observed behaviour:* :eyes: :broken_heart:

See a top bar with missing glyphs/icons

*Expected behaviour:* :heart: :smile:

See top bar without missing glyphs/icons

#### System Info :computer:
- OS: gnu/linux (POP!_OS 20.10)
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. dfd208cf8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible auto-completion better-defaults coffeescript docker emacs-lisp elixir git helm html
         (javascript :variables javascript-fmt-on-save t javascript-fmt-tool 'prettier javascript-backend 'lsp javascript-lsp-linter nil javascript-import-tool 'import-js node-add-modules-path t)
         markdown nginx
         (org :variable org-enable-github-support t org-enable-org-journal-support t)
         (python :variables python-formatter 'black python-format-on-save t)
         react
         (ruby :variables ruby-version-manager 'chruby ruby-enable-enh-ruby-mode t)
         rust syntax-checking
         (shell :variables shell-default-shell 'ansi-term close-window-with-terminal t)
         terraform
         (typescript :variables typescript-backend 'tide typescript-linter 'eslint typescript-fmt-on-save t typescript-fmt-tool 'prettier)
         yaml treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM MODULES THREADS PDUMPER GMP

**Comment by alexey0308** [comment]
Hi @tgroshon, does it help if you do M-x `all-the-icons-install-fonts`?

**Comment by lebensterben** [comment]
Just install one of nerd font.

**Comment by tgroshon** [comment]
> Hi @tgroshon, does it help if you do M-x `all-the-icons-install-fonts`?

Yes that fixed the GUI!  Is that documented anywhere?  I've been using Spacemacs for a couple years and never knew about that lol

**Comment by tgroshon** [comment]
> Just install one of nerd font.

I don't know what that means.

**Comment by lebensterben** [comment]
>> Just install one of nerd font. ...

@tgroshon Google "nerd font". It patches popular fonts with lots of glyphs, including font awesome, all my icons etc.

**Comment by alexey0308** [comment]
I got this problem today as well and found it somewhere in doom-emacs of lsp-mode repository

**Comment by lebensterben** [comment]
>I got this problem today as well and found it somewhere in doom-emacs or lsp-mode repository

@alexey0308 If you always have "breadcrumb" on, then this could be due to an update in "lsp-mode" package I guess.
