### ISSUE TITLE
Improve popwin

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1424]
Since we can easily set the position of Helm window using built-in utility of Emacs like in this PR: https://github.com/syl20bnr/spacemacs/pull/1421, I think it's time we can drop `popwin`. You may ask, how can we control the position of temporary buffers like help or compilation buffer? Easy, do it like we do for Helm buffers:

```elisp
(add-to-list 'display-buffer-alist
               `(,(rx bos "*compilation")
                 (display-buffer-reuse-window
                  display-buffer-in-side-window)
                 (side . bottom)
                 (reusable-frames . visible)))

  (add-to-list 'display-buffer-alist
               `(,(rx bos "*help")
                 (display-buffer-reuse-window
                  display-buffer-in-side-window)
                 (side . bottom)
                 (reusable-frames . visible)))
```

You may ask, how can we delete these windows without popwin. The answer: we add a command for deleting these buffers, from anywhere:

```elisp
(defun lunaryorn-quit-bottom-side-windows ()
    "Quit side windows of the current frame."
    (interactive)
    (dolist (window (window-at-side-list))
      (when (not (string-match ".*helm.*" (buffer-name (window-buffer window))))
        (quit-window nil window))))

  (global-set-key (kbd "C-c [") 'lunaryorn-quit-bottom-side-windows)
```

(the command is taken from [here](https://github.com/lunaryorn/.emacs.d/commit/ab7669a34747d8b44ffa67787a94636472115652), with slight modification to not delete Helm windows)

If you want similar behavior to popwin - pressing `C-g` to quit the temporary window - then simply execute it before `keyboard-quit` runs:

```elisp
(advice-add 'keyboard-quit :before 'lunaryorn-quit-bottom-side-windows)
```

However, I think having a separate key binding is better since we may not always want such windows to be closed (i.e. `vc-diff` window).

Without `popwin`, it is much easier to integrate `window-purpose` and provide a much better window management experience.

**Comment by tuhdo** [comment]
@syl20bnr If you test this, remember to remove the popwin hooks in `helm-after-initialize-hook` and `helm-cleanup-hook`. Otherwise whenever you run a Helm command and `popwin` is enabled again, making you cannot test this proposal properly.

**Comment by syl20bnr** [comment]
Interesting. We should turn this into a core library.
Support for the size on the window is missing.

**Comment by tuhdo** [comment]
Adding height is easy. See my PR: https://github.com/syl20bnr/spacemacs/pull/1421

Simply add `(window-height . 0.4)` there.

**Comment by syl20bnr** [comment]
:+1:

**Comment by tuhdo** [comment]
Actually as I was working on this issue, I realized that I started reinventing `popwin`. So I think rather removing it we can improve it. The solution is set `popwin:special-display-config` to `nil` at the beginning and let us manage it from scratch. Doing so, we avoid `popwin` messes up windows of some package. Like company, if a layer want to have `popwin` support, it must be explicitly specified.
