### ISSUE TITLE
New Layer: Emacs Tree Sitter

### ISSUE THREAD

**Issue by muhmud** [syl20bnr/spacemacs#14246]
https://github.com/ubolonton/emacs-tree-sitter

Thanks!

**Comment by smile13241324** [comment]
I assume this is a feature request to have tree-sitter, a native structural parsing library, integrated into Spacemacs? I am not sure this makes much sense, this library primarily targets emacs packages which in turn we group into pre-configured layers. This is to have tree sitter used in spacemacs it just has to be used by one of the packages integrated. Also binary installation of the C or Rust part of tree-sitter is covered by the standard melpa installation.

So this is no change for Spacemacs instead you should open an issue upstream on your individual emacs package you would want to have native support for.

**Comment by muhmud** [comment]
You could be right, and I should've done a better write up, but I see this as providing general syntax highlighting even without any other emacs language packages installed.

The highlighting definitions provided with emacs-tree-sitter are also somewhat basic. I've done a fair few modifications on the Java one to make them more suitable for myself. So, with a layer for this you would have a place to provide and maintain better rule definitions in a central place.

**Comment by lebensterben** [comment]
I agree with @smile13241324 
And I'd like to see some demonstration of this new package. It seems like a library for elisp developer (of language syntax highlighting) instead of a package for end-users.

**Comment by yyoncho** [comment]
JFYI tree-sitter ships with highlighting which tends to be much faster and more precise than what emacs major modes have. I don't have experience with it but this is the feedback that I am getting(especially for cc-mode related modes). 

IMHO bare tree sitter layer should be added and potentially it should be advertised as a default layer(when user's emacs supports dynamic modules) if the aforementioned perf and precision gains are real.
