### ISSUE TITLE
c/c++ Top bar garbled

### ISSUE THREAD

**Issue by wutianjun5858** [syl20bnr/spacemacs#14244]
spacemacs branch: develop
spacemacs commit id: c4ad14a73
lsp: ccls
os: ubuntu 18.04

![111](https://user-images.githubusercontent.com/25163353/103196207-b46fbb80-491e-11eb-96de-93ab8cd3dd6a.png)

**Comment by lebensterben** [comment]
You need to install a patched font, e.g. one of nerd font.

**Comment by wutianjun5858** [comment]
set lsp-headerline-breadcrumb-enable  as nil
