### ISSUE TITLE
Feature proposal: github discussions

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#14257]
Hi! Would it be nice to add the new [github discussions](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-or-disabling-github-discussions-for-a-repository#enabling-or-disabling-discussions-for-your-repository) feature to this repository? It could e.g. be used to discuss development/features. On gitter there is not too much response regarding development/feature discussions. Or should features/development be discussed in issues?

For example, I was wondering iwhat you think about adding [hercules.el](https://gitlab.com/jjzmajic/hercules.el#Motivation) to spacemacs core packages. It creates a kind of transient by just using which-key. Could be handy to create transients in Info-mode, eww etc.

Also I am not sure if and how to add org-contacts to the org layer. But I do think org-contacts is a great feature. Probably more user-friendly than bbdb/ebdb for users with only few contacts.

So should I open issues to discuss these things? Or could the discussion feature be nice for that?

Of course the github discussions could be used for some other purpose... but it probably would be handy somehow.

**Comment by smile13241324** [comment]
Good idea, I will post it to the maintainers chat, lets see what the others say. Also I am not sure I have the rights to activate repository wide functions.

**Comment by syl20bnr** [comment]
Good idea, this is activated. For now let's keep the default categories.
