### ISSUE TITLE
Treemacs does not display help

### ISSUE THREAD

**Issue by epsilon-phase** [syl20bnr/spacemacs#14254]
#### Description :octocat:

Treemacs appears to be wired to hydra incorrectly, as pressing the key to show help doesn't work.

#### Reproduction guide :beetle:
- Start Emacs
- Open treemacs
- press `?`

*Observed behaviour:* :eyes: :broken_heart:

Error message shows in status line, saying `command-execute: Wrong type argument: commandp, treemacs-helpful-hydra`

*Expected behaviour:* :heart: :smile:

Help display appears

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7b7076d4b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript html ocaml erlang ruby markdown helm emacs-lisp
            (common-lisp)
            git latex
            (c-c++ :variables c-c++-backend 'lsp-ccls)
            lsp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
2

#### Backtrace :paw_prints:

Doesn't appear relevant

### Other surprises

Running `treemacs-common-helpful-hydra` works properly, and after it is run pressing `?` works properly until emacs is restarted.

**Comment by Alexander-Miller** [comment]
Treemacs is wired correctly: https://github.com/Alexander-Miller/treemacs/blob/master/src/extra/treemacs-evil.el#L86

However it seems like Melpa is having trouble building new packages: https://github.com/melpa/melpa/issues/7333

**Comment by epsilon-phase** [comment]
Is there anything I can do in the meantime until it's fixed?

**Comment by duianto** [comment]
The treemacs hydra keys can be bound manually in the `dotspacemacs/user-config` section of your `.spacemacs` like this:
```elisp
  (with-eval-after-load 'treemacs
    (define-key evil-treemacs-state-map (kbd "?")   #'treemacs-common-helpful-hydra)
    (define-key evil-treemacs-state-map (kbd "C-?") #'treemacs-advanced-helpful-hydra))
```

**Comment by duianto** [comment]
This has now been fixed upstream:
package-build--build-single-file-package: Fix regression
https://github.com/melpa/package-build/commit/4ca24cb7143eb49365b8546f518ef4b857b9c253

Just update the packages and the latest `treemacs-evil.el` will be downloaded.
