### ISSUE TITLE
show-smartparens-mode seems much slower than show-parens-mode

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#1425]
I noticed that moving around in my buffer felt a lot slower than it used, and I found that disabling `show-smartparens-mode` fixed the issue. Enabling `show-parens-mode` doesn't have the same effect. 

@syl20bnr confirmed that he experiences the same effect.

I suggest that `show-parens-mode` should only be enabled in modes that do not work with `show-parens-mode`.

**Comment by syl20bnr** [comment]
Reproducible step:
Hover the point on the outer parens here: https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L2447

**Comment by pennyan** [comment]
Refer to #2432. I also have same problem. `show-parens-mode` is much faster.

**Comment by geo7** [comment]
@syl20bnr that step link doesn't work anymore btw - not sure whether this is still relevant or not...

**Comment by StreakyCobra** [comment]
@luxbock @pennyan Is this issue still relevant for you, or has it improved?

**Comment by luxbock** [comment]
@StreakyCobra I'm using:
```elisp
  (with-eval-after-load 'smartparens
    (show-smartparens-global-mode -1))
```
in my .spacemacs file to get rid of the behavior, but the issue is still present otherwise. I suppose if it doesn't bother others as much then it's fine to close this.

**Comment by StreakyCobra** [comment]
Ok thx. So it hasn't improved since April… In `show-smartparens-mode` it's explained that:

> show-smartparens-mode provides functionality similar to show-paren-mode, but works for all the user-defined pairs which are recognized by sp-get-sexp.

So it makes sense that `smartparens` version is slower than `paren` one. I thinks most people don't have troubles with this, so it should be a user choice to degrade this functionality, and your snippet is correct.

So I propose to put this in the FAQ with this workaround :-)

**Comment by StreakyCobra** [comment]
Actually, it's maybe better to put the snippet like this:

```elisp
      (spacemacs|use-package-add-hook smartparens
        :post-config
        (show-smartparens-global-mode -1))
```

But this has to be tried first.

**Comment by StreakyCobra** [comment]
Actually #3828 is discussing the same problem and they are wanting to go further with the idea of disabling it, so let's wait for this one :-)
