### ISSUE TITLE
In emacs 28 "when" parameter are mandatory in function define-obsolete-variable-alias

### ISSUE THREAD

**Issue by bsless** [syl20bnr/spacemacs#14265]
#### Description :octocat:
In emacs 28 "when" parameter are mandatory in function define-obsolete-variable-alias, Spacemacs cannot start.

#### Reproduction guide :beetle:
- Build Emacs from master
- Start Emacs
- Emacs fails to load init.el due to - libs/page-break-lines.el 109:(define-obsolete-function-alias 'turn-on-page-break-lines-mode 'page-break-lines-mode)

*Observed behaviour:* :eyes: :broken_heart:
Wrong number of arguments to define-obsolete-function-alias
Managed to workaround with:
```
(defun wrap-obsolete (orig-fn &rest args)
  (let ((args_ (if (= (length args) 2)
                   (append args (list "0"))
                 args)))
    (apply orig-fn args_)))

(advice-add 'define-obsolete-function-alias :around #'wrap-obsolete)
```
in init.el

*Expected behaviour:* :heart: :smile:
Wonderful Spacemacs starts with no issue :)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ee9201efe)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(octave erlang lua scheme haskell erc lsp dap restclient sql shell-scripts yaml java
        (elfeed :variables rmh-elfeed-org-files
                (list "~/.emacs.d/private/elfeed/tech.org"))
        (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
        better-defaults csv
        (clojure :variables clojure-enable-linters
                 '(clj-kondo)
                 clojure-backend 'cider clojure-enable-clj-refactor t clojure-enable-fancify-symbols t)
        (c-c++ :variables c-c++-backend 'lsp-clangd)
        ocaml docker emacs-lisp common-lisp git github graphviz gtags helm html javascript markdown
        (org)
        python react search-engine spell-checking syntax-checking version-control vimscript
        (slack :variables slack-buffer-emojify t slack-prefer-current-team t alert-default-style 'libnotify slack-log-level 'warn)
        treemacs
        (go :variables go-use-golangci-lint t go-tab-width 4)
        systemd
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        xkcd twitter)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2

#### Backtrace :paw_prints:
This backtrace is slightly different because I used advice to mitigate the issue and it probably got byte-compiled
```
Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 4) 2)
  #f(compiled-function (obsolete-name current-name when &optional docstring) "Set OBSOLETE-NAME's function definition to CURRENT-NAME and mark it obsolete.\n\n(define-obsolete-function-alias \\='old-fun \\='new-fun \"22.1\" \"old-fun's doc.\")\n\nis equivalent to the following two lines of code:\n\n(defalias \\='old-fun \\='new-fun \"old-fun's doc.\")\n(make-obsolete \\='old-fun \\='new-fun \"22.1\")\n\nWHEN should be a string indicating when the function was first\nmade obsolete, for example a date or a release number.\n\nSee the docstrings of `defalias' and `make-obsolete' for more details." #<bytecode -0xf812ef5c7281c61>)('singularize-string 'inflection-singularize-string)
  (define-obsolete-function-alias 'singularize-string 'inflection-singularize-string
```

See also https://github.com/emacs-lsp/lsp-mode/issues/2497

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
fix page-break-lines-mode alias definition #14262

@bsless Could you check that it works as expected now. If it does, then this issue can be closed.

**Comment by noaccOS** [comment]
@duianto It works for me now. Thanks!

**Comment by smile13241324** [comment]
@bsless can you check on latest develop and close this ticket if this fix works for you too?

**Comment by bsless** [comment]
@smile13241324 sorry for not getting to it sooner, I can report it solves that problem specifically, but it still exists in dependencies. Do you want to provide some temporary general purpose workaround or would you say it is outside of the scope of the issue?

**Comment by bsless** [comment]
Since the issue is essentially fixed as previously mentioned I'm closing it. Dependencies will have to solve it on their own.
