### ISSUE TITLE
Anaconda mode stops working for autocomplete after a while

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#14269]
#### Description :octocat:
anaconda-mode server stops responding, so python autocomplete stops working, anaconda buffer stops receiving output. Killing the anaconda process and toggling autocomplete makes it work again.

I don't see any particular errors in the buffer that would indicate a crash, though there is a lot of this:

```
<ipython-input-1-23f9ccda9a46>:98: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  result = f(jedi.Script(source, line, column, path, environment=virtual_environment))
<ipython-input-1-23f9ccda9a46>:98: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  result = f(jedi.Script(source, line, column, path, environment=virtual_environment))
<ipython-input-1-23f9ccda9a46>:154: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_signatures instead.
  signatures = script.call_signatures()
<ipython-input-1-23f9ccda9a46>:130: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).complete instead.
  for definition in script.completions()]
```

#### Reproduction guide :beetle:
- Start Emacs
- Code in python for a while
- Autocomplete eventually stops working, and no more output is appended to the `*anaconda-mode*` buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ee9201efe)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(perl5 go swift csv lua nginx sql auto-completion emacs-lisp git yaml javascript html markdown major-modes python org osx python ipython-notebook django syntax-checking spell-checking colors spacemacs-layouts vimscript helm
       (version-control :variables version-control-diff-tool 'diff-hl)
       (c-c++ :variables c-c++-enable-clang-support t)
       (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by smile13241324** [comment]
When this happens and you manually kill the log buffer does emacs regenerate? If it does your log buffer is overflowing.
The root of the issue may then be a conflict between latest version of jedi and ipython or anaconda-mode. The warning above just says that the way jedi is invoced is deprecated.

I have similar issues with LSP and python in my work environment however I have always though this would be an issue of my work box (its pretty slow), so this could still be an issue with us. Not sure if we can limit the size of a buffer in emacs 🤔.
