### ISSUE TITLE
Missed my C-e key binding

### ISSUE THREAD

**Issue by gizak** [syl20bnr/spacemacs#1427]
I am an emacs guy who never tried `evil` for the entire life.  spacemacs is really great but there is  one thing bugs me a lot. 

I could not use `C-e` (go to the end of a line) in evil's insert-mode. Checking the key binding gave me this:  

```
C-e runs the command evil-copy-from-below, which is an interactive compiled Lisp
function in `evil-commands.el'.
```

Is there any way to get it back? Thanks!

**Comment by tuhdo** [comment]
It should not be like that. Did you properly choose Emacs editing style. Spacemacs asks you when it first starts up and finds no `.spacemacs` file. If you already have your `.spacemacs` file, consider changing to Emacs editing style and you get every stock editing command.

**Comment by danielwuz** [comment]
Check out evil-rsi package

**Comment by gizak** [comment]
Thanks for the advice, `(define-key evil-insert-state-map "\C-e" 'end-of-line)` somehow fixed the problem.
