### ISSUE TITLE
issue installing a language server for freebsd

### ISSUE THREAD

**Issue by xyderos** [syl20bnr/spacemacs#14281]
I am trying to configure spacemacs for freebsd and so far i have fully configured the extensions for c-c++(including the clangd debugging server) but when it comes to python it's getting a little messy.

I tried the 'anaconda version as a backend(installed as mentioned in the layers tutorial for python) but when i am checking the log(inside spacemacs) to see if i am connected to a server i see no messages.(is there a way to test it if its working? i tried to write some code but i had no luck fixing that).

I tried to set pyls as an option but, unfortunately i think it is not supported because whenever i am trying to open a .py file i am getting a message that says:
"Unable to find installed server supporting this file. The following servers could be installed automatically"
and has mspyls as an option.

If i try to install mspyls i get a message that this server is not supported by my operating system.
Is it actually an OS's fault an if it is, can i somehow fix that?

Thanks in advance!

**Comment by xyderos** [comment]
I clean installed all the packages for Spacemacs and installed the requirements again in a virtual environment, it worked.

**Comment by lebensterben** [comment]
Is you Python language server in your PATH?
You can evaluate `(executable-find <NAME OF THE SERVER>)` in ielm buffer
