### ISSUE TITLE
Treemacs: `l` does not open subtree - enter does

### ISSUE THREAD

**Issue by Antiarchitect** [syl20bnr/spacemacs#14283]
It's about or month or so Treemacs does not open directory subtree by `l` now only Enter key works. Also having some troubles displaying help, but there is an issue for that: https://github.com/syl20bnr/spacemacs/issues/14254

**Comment by duianto** [comment]
The treemacs help `?`, issue has been fixed upstream.
package-build--build-single-file-package: Fix regression
https://github.com/melpa/package-build/commit/4ca24cb7143eb49365b8546f518ef4b857b9c253

The latest version of `treemacs-evil` is part of the package update now.

---

`l` seems to be working as expected for me.
It calls: `treemacs-root-down`
and the selected directory becomes root.

[Treemacs] v2.8 (installed 2021.01.09) @ Emacs 27.1
<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ed278491e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey emacs-lisp git helm javascript lsp multiple-cursors
            (org :variables org-agenda-files
                 '("c:/Users/username/org/")
                 org-enable-jira-support t org-enable-roam-support t)
            python shell spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

---

Could you update the packages and test if it works with the latest version.

If it still doesn't work:
- Do you see any error messages?
- What's your:
  - System info. Press `SPC h d s` to copy the info to your clipboard.
  - `M-x treemacs-version`

**Comment by Alexander-Miller** [comment]
> l seems to be working as expected for me.
It calls: treemacs-root-down
and the selected directory becomes root.

That is how it works when you have only 1 project, otherwise this free-form navigation is disabled. 

It's been the default for a long time now, so I have no intention to change it. If you are sure you want `l` to behave like `RET` you do it with

```Elisp
(with-eval-after-load 'treemacs
    (evil-define-key 'treemacs treemacs-mode-map (kbd "l") #'treemacs-RET-action))
```

**Comment by Antiarchitect** [comment]
Actually, when I press l on a directory I have this error:
```
[Treemacs Failure] Button at point is not a directory.
```

**Comment by Alexander-Miller** [comment]
Are you trying it on the root node of a project? Those are not quite the same as directories.

**Comment by Antiarchitect** [comment]
Sorry - my fault. It was actually a project root.
I tried your recommendation,  but it actually do not the same thing as it did before. It actually opens the tree, but before it also did root down. Anyway, previous behavior was: it made root down + opened the node. Now I think it could only do one of these things

**Comment by Antiarchitect** [comment]
I do not how to explain better. Without your proposed config `l` now actually do root-down, but do not display this new root content and I need to display it additionally by dwim RET or dwim TAB and that is very annoying

**Comment by Alexander-Miller** [comment]
> Without your proposed config l now actually do root-down, but do not display this new root content and I need to display it additionally by dwim RET or dwim TAB and that is very annoying

Yeah, I noticed that too, and I'll be fixing that soon.

**Comment by Antiarchitect** [comment]
@Alexander-Miller any news on this?

**Comment by Alexander-Miller** [comment]
Thanks for the reminder. I'll try and sit down for it today.

**Comment by Alexander-Miller** [comment]
Fix has been pushed.

**Comment by Antiarchitect** [comment]
@Alexander-Miller Worked like a charm! Thank you so much!
