### ISSUE TITLE
Bad interaction of flyspell and LSP headline breadcrumb

### ISSUE THREAD

**Issue by Kazark** [syl20bnr/spacemacs#14292]
#### Description :octocat:
Flyspell is marking code symbols in the [LSP's headerline breadcrumb](https://emacs-lsp.github.io/lsp-mode/page/main-features/#breadcrumb-on-headerline) as mispelled. I don't know whether this is something we can fix in Spacemacs by making the two play nicely, or whether it should be reported upstream; and if upstream, to which project.

#### Reproduction guide :beetle:
Open a file from a Scala project

*Observed behaviour:* :eyes: :broken_heart:
Squiggly underlines in LSP's headerline breadcrumb.

![image](https://user-images.githubusercontent.com/3661051/104246075-5c16de80-5433-11eb-8c65-20f6b5432db5.png)

*Expected behaviour:* :heart: :smile:
LSP notifies Flyspell that it is using the headerline and so to please ignore it?

#### System Info :computer:
- OS: darwin
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 667914e5f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking syntax-checking
                (auto-completion :variables auto-completion-enable-snippets-in-popup t)
                helm
                (org :variables org-enable-verb-support t)
                helpful
                (unicode-fonts :variables unicode-fonts-ligature-modes
                               '(prog-mode))
                emoji agda c-c++ clojure emacs-lisp graphviz
                (haskell :variables haskell-completion-backend 'ghci)
                html java javascript jsonnet kotlin markdown
                (scala :variables scala-auto-treeview nil scala-sbt-window-position 'bottom)
                scheme sql typescript yaml
                (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
                osx git github version-control
                (colors :variables colors-colorize-identifiers 'variables)
                (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: JPEG TIFF PNG NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES NATIVE_COMP THREADS XWIDGETS JSON PDUMPER LCMS2

**Comment by Kazark** [comment]
I'm not longer observing this. Perhaps a package update fixed it.

**Comment by Kazark** [comment]
I saw it again, this time in a Java file.

**Comment by dj0405** [comment]
> I'm not longer observing this. Perhaps a package update fixed it.

I am observing the same issue with C files!

**Comment by Kazark** [comment]
Why am I not seeing it in in Scala files now though? So confusing

**Comment by Kazark** [comment]
Now I am seeing it in one Scala file but not the other! 😮

**Comment by dj0405** [comment]
It seems it has to do with the path name! I have two C files open from two different projects. One file shows the spell check underline and one file seems okay! Very confusing!

**Comment by eklitzke** [comment]
I also see this intermittently. My guess is that flyspell has some heuristic it applies to detect if text is English or not, and if enough of it is English it's shows the spell check errors. In my example A few of the items on the breadcrumb line *are* valid dictionary words in English, and some aren ot.

**Comment by eklitzke** [comment]
I have a fix (I think), by adding this to my `dotspacemacs/user-config`:
```emacs-lisp
  (spacemacs|use-package-add-hook lsp-mode
    :post-config
    (add-hook 'lsp-headerline-breadcrumb-mode 'flyspell-mode-off))
```

I will see if I can make this work in the develop branch and make a PR.

**Comment by Kazark** [comment]
@eklitzke Excellent. Thank you!

**Comment by eklitzke** [comment]
That didn't actually fix it, but now I think that this actually might just be controlled by the variable `lsp-headerline-breadcrumb-enable-diagnostics` which colorizes the faces of headerline breadcrumb elements based on LSP diagnostics. I set that to `nil` in my config and the problem isn't happening right now (although it didn't always immediately happen before either).

**Comment by lebensterben** [comment]
>That didn't actually fix it, but now I think that this actually might just be controlled by the variable `lsp-headerline-breadcrumb-enable-diagnostics` which colorizes the faces of headerline breadcrumb elements based on LSP diagnostics. I set that to `nil` in my config and the problem isn't happening right now (although it didn't always immediately happen before either).

@eklitzke this is not a fix. it just turns off this feature

**Comment by jclosure** [comment]
Not Spacemacs-specific.  I'm seeing this with vanilla Emacs as well.
![image](https://user-images.githubusercontent.com/343099/121478006-24827300-c98e-11eb-957c-ac8df69e554b.png)

**Comment by Kazark** [comment]
@jclosure if you send me a snippet of your code I'll put it into Spacemacs. Thanks for discovering the solution.

**Comment by Kazark** [comment]
Or is your change something that should be upstreamed?

**Comment by Kazark** [comment]
@lebensterben what do you think the right course is here? Just put these changes into the `lsp` layer? Try to argue upstream at `lsp-mode` that the defaults do not make sense?

**Comment by lebensterben** [comment]
@jclosure @Kazark 
This is not a fix.

The documentation of `lsp-headerline-breadcrumb-path-warning-face` describes that
> Face used for breadcrumb paths on headerline when there is an warning under that path

So having curly underline is correct and idiomatic.
Unsetting this property doesn't change the fact that spell-checking is interfering with the headerline.

**Comment by lebensterben** [comment]
I cannot come up with a proper FIX for now.

The minor mode `lsp-headerline-breadcrumb-mode` works on the variable `header-line-format`, which is defined in `emacs` upstream.

So theoretically, though I haven't experienced, the irritating behaviour of `flyspell` on `lsp-headerline` could also occur to header line in general.
Therefore, I think we'd better ask for help from the broader emacs community about whether there's a proper solution to this issue. If there isn't, then we may need to request a feature that to disable `flyspell` for headerline!

**Comment by Kazark** [comment]
I see it in Rust mode too.

**Comment by SeanMaclochlainn** [comment]
I'm on Doom Emacs but was having the same issue. It went away when I installed dictionaries for [Hunspell](https://github.com/hunspell/hunspell), the dictionary for flyspell

```
mkdir -p ~/Library/Spelling
wget -O en_US.aff  https://cgit.freedesktop.org/libreoffice/dictionaries/plain/en/en_US.aff\?id\=a4473e06b56bfe35187e302754f6baaa8d75e54f
wget -O en_US.dic https://cgit.freedesktop.org/libreoffice/dictionaries/plain/en/en_US.dic\?id\=a4473e06b56bfe35187e302754f6baaa8d75e54f
```
I was also getting "Can’t find Hunspell dictionary with a .aff affix file" which also went away

**Comment by Kazark** [comment]
Thanks @SeanMaclochlainn . I'll give that a shot the next time I hit this.

**Comment by benleis1** [comment]
I'm seeing that behavior today. Has there been any progress discussing with the lsp folks?
