### ISSUE TITLE
New Layer: Request to add emacs-bazel-mode

### ISSUE THREAD

**Issue by bshashank** [syl20bnr/spacemacs#14294]
I didn't see an issue to track this. I use emacs to work with Bazel files. There is already an emacs mode to handle this at: https://github.com/bazelbuild/emacs-bazel-mode

I currently use this in my private layer configure, but I wanted to open an issue to see if there more general interest in making this a supported layer. If there is, I'll be happy to provide a pull-request.

**Comment by dalanicolai** [comment]
EDIT

As I find a number of 'likes' here. Let me add a [link to my unofficial layers](https://github.com/syl20bnr/spacemacs/discussions/14757)

END EDIT

I guess it would be nice to have a page with links to 'unofficial` layers, to which a link could be added from the official layers list. I have a few private layers too, that might be useful to some people, but for which I currently think it is not worth it to do all the work for making them official layers.

Of course if Bazel is very popular, making it an official layer might be worth it.

For now I think it might be handy to add a repo for your layer on your personal github page and add a link here.

**Comment by yesudeep** [comment]
@bshashank Could you please send a pull request anyway?
