### ISSUE TITLE
Symbol's function definition is void: evil-set-undo-system during init on develop

### ISSUE THREAD

**Issue by razc411** [syl20bnr/spacemacs#14303]
#### Description
Spacemacs fails to initialize when using the develop branch.

#### Reproduction guide
- Start Emacs

*Observed behaviour:*
Starts with the error

```
Symbol's function definition is void: evil-set-undo-system

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

debug-init does not reveal too much to me, but I am not well versed in debugging emacs.

If I go into packages.el and remove the evil-set-undo-system lines, I just encounter an issue with keymap

```
Warning (initialization): An error occurred while loading ‘/home/rz/.emacs.d/init.el’:

Symbol's function definition is void: which-key-add-keymap-based-replacements

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

*Expected behaviour:*
Emacs starts without error.

*System Info*
OS: Arch Linux
Kernel: 5.10.7-arch1-1
Emacs: 27.1
Spacemacs: Develop (fc20d1b4c10e419af329aa8dd7247df952fb14a1)

**Comment by emacs18** [comment]
Please update evil packages.  Using old evil package would explain the failure reported.

**Comment by rchennafi** [comment]
It seemed the only way to do this was to delete the repo altogether and check it out again, even though there were no changes in my develop branch or untracked files. This seems to have fixed it.

**Comment by razc411** [comment]
It seemed the only way to do this was to delete the repo altogether and check it out again, even though there were no changes in my develop branch or untracked files. This seems to have fixed it.

**Comment by Spadavecchia** [comment]
Deleting the `.emacs/elpa` directory inside and restarting spacemacs did the trick.
