### ISSUE TITLE
What is the buffer indicator in Spacemacs called?

### ISSUE THREAD

**Issue by ReneFroger** [syl20bnr/spacemacs#1430]
To be clear: I don't use Spacemacs because of my heavily customized Emacs, but I'm actively following Spacemacs. 

Today I saw in a video that Spacemacs have in the modeline a indicator, a small square block with blue indicicator. Every time when the point move around in the buffer, the blue indicator moves along with it. That's nice. :smiley:.

I would like to have it included into my Emacs configuration (I use it with Smart Mode Line, which allows me to have pop-ups for ERC and shortened path's with custom defining). But I couldn't figure out how this feature of indicator is being called, and where I could get it. 

Any suggestions? It would be appreciated. :+1:.

**Comment by TheBB** [comment]
You mean [this thing](https://github.com/milkypostman/powerline/blob/master/powerline.el#L260-275)?

**Comment by tuhdo** [comment]
I guess it is the left-most square of the modeline. If that is the case, then it is used for indicating window number, making switching easy by pressing `SPC <number>`. It is a unicode character returned by [window numbering](https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L2764). Then you have [powerline retrieves the character to display it in the modeline](https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L2231).

**Comment by ReneFroger** [comment]
I don't mean the left-most square, but the right-most square of the mode-line, on the right side of the `23%` percentage, as seen in this picture: 

https://github.com/syl20bnr/spacemacs/blob/master/doc/img/spacemacs-ahs-micro-state.png?raw=true

**Comment by TheBB** [comment]
Yes, that's the one in my link.

**Comment by ReneFroger** [comment]
Ah, thanks! I will figure a way out to integrate the code snippet into the Smart Mode Line. It's an awesome feature.
