### ISSUE TITLE
Python mode autocompletion not working for imported packages

### ISSUE THREAD

**Issue by zbinkz** [syl20bnr/spacemacs#14300]
GNU Emacs 26.1
Spacemacs develop branch commit a65497be79897ee5d1046eede5561283c43c667f
Debian 10.7
Python 3.7.3

Python mode autocompletion only works for native commands like `print` or `for`, but not for imported packages. Here is my layer setup:

dotspacemacs-configuration-layers
  (
     (python :variables python-backend 'anaconda)
     (auto-completion :variables
                      auto-completion-enable-sort-by-usage t
                      auto-completion-enable-snippets-in-popup t)
     better-defaults
     emacs-lisp
     git
     helm
     markdown
     multiple-cursors
     org
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     syntax-checking
     treemacs
     gpu)

Is it a bug or a messed up setup? Haven't found anything related searching online.

Thanks

**Comment by alexey0308** [comment]
@zbinkz for anaconda-mode one needs to initialize the inferior Python buffer. Does it solve the issue, if you do C-c C-p or M-x run-python?

**Comment by zbinkz** [comment]
> @zbinkz for anaconda-mode one needs to initialize the inferior Python buffer. Does it solve the issue, if you do C-c C-p or M-x run-python?

@alexey0308 yes, code completion works for imported modules now. All good, thanks :)

**Comment by zbinkz** [comment]
Closing issue.
