### ISSUE TITLE
Separators of `lsp-headerline-breadcrumb-mode` are garbled.

### ISSUE THREAD

**Issue by rayw000** [syl20bnr/spacemacs#14314]
I didn't see any fonts initialization in both `all-the-icons` and `lsp-headerline`. Separators go garbled on my spacemacs due to font missing like this.

![image](https://user-images.githubusercontent.com/69779107/105439778-67260600-5ca0-11eb-9b87-0e69a5734e39.png)

After running `all-the-icons-install-fonts`, things look fine.

![image](https://user-images.githubusercontent.com/69779107/105440148-0cd97500-5ca1-11eb-95a4-0a9a9aca8fa1.png)

I'm not sure where I can put `all-the-icons-install-fonts` gracefully without any side effects.

Would someone here give me a hint?

**Comment by lebensterben** [comment]
what do you mean by "without any side effects"?
if you don't want any side effects, why do you put this line of code anywhere in the first place?

**Comment by rayw000** [comment]
@lebensterben 
> what do you mean by "without any side effects"?
> if you don't want any side effects, why do you put this line of code anywhere in the first place?

I mean it may be better if we can run `all-the-icons-install-fonts` automatically to avoid seeing garbled separators, but I'm not sure if it should be run at post-install stage of `all-the-icons`, or at initialization stage of `lsp-headerline`. Neither of them is perfect.

May be we should just document it to let users know they need to install fonts to make `lsp-headerline-breadcrumb` work as expected. Do you agree?
