### ISSUE TITLE
Tab icons are not visible when Emacs is launched in daemon mode

### ISSUE THREAD

**Issue by balaji-dutt** [syl20bnr/spacemacs#14316]
#### Description :octocat:
I have installed the `tabs` layer and also have `all-the-icons` installed through a private layer. I'm seeing an odd behavior where the tab icons show up nicely when I launch Emacs without an already running `emacsdaemon` instance. However, if i first run `emacsdaemon` and then run `emacsclientw` the tab icons do not show up

#### Reproduction guide :beetle:
- Activate `tabs` layer in `init.el` after ensuring that `all-the-icons` is running and working correctly
- Start Emacs using `emacsclientw.exe`
- Verify if tab icons are visible. If yes, then quit Emacs completely
- Launch Emacs in daemon mode with `runemacs.exe --daemon`
- Connect to the running Emacs instance by running `emacsclientw.exe -n -a "runemacs.exe`

*Observed behaviour:* :eyes: :broken_heart:
- No tab icons visible when running ` runemacs.exe --daemon` and then `emacsclientw.exe -n -a "runemacs.exe`
![23-01-2021 10-34-06 AM](https://user-images.githubusercontent.com/3147070/105566667-60fb5c80-5d68-11eb-81f6-429a59c6f61f.png)

- Tab icons visible when running just `emacsclientw.exe -n -a "runemacs.exe`
![23-01-2021 10-37-25 AM](https://user-images.githubusercontent.com/3147070/105566707-930cbe80-5d68-11eb-9e8d-544a8853dfd0.png)

*Expected behaviour:* :heart: :smile:
Tab icons visible should be visible when running ` runemacs.exe --daemon` and then `emacsclientw.exe -n -a "runemacs.exe`

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. dfd208cf8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking helm auto-completion
                (org :variables org-enable-hugo-support t)
                tabs emoji multiple-cursors javascript html emacs-lisp
                (markdown :variables markdown-command "pandoc -t html5 -f markdown_mmd --self-contained --mathjax --quiet --highlight-style=zenburn --template github.html5" markdown-live-preview-engine 'pandoc)
                shell-scripts windows-scripts yaml dash
                (deft :variables deft-zetteldeft t)
                git
                (shell :variables shell-default-height 30 shell-default-position 'bottom)
                chrome nginx ansible docker kubernetes terraform
                (ranger :variables ranger-override-dired 'ranger ranger-show-preview t ranger-cleanup-eagerly t)
                my-private-layer all-the-icons)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS LCMS2

**Comment by lebensterben** [comment]
I confirm this on Linux

**Comment by lebensterben** [comment]
This bug seems to be fixed on upstream.
