### ISSUE TITLE
Enabling the semantic layer shows always `*invalid*` on the top bar.

### ISSUE THREAD

**Issue by abougouffa** [syl20bnr/spacemacs#14313]
#### Description :octocat:
Enabling the semantic layer shows always `*invalid*` on the stickyfunc-like top bar.

#### Reproduction guide :beetle:
- Start Emacs
- Add semantic layer to .spacemacs
- Reload configuration with `SPC f e R`
- Restart Emacs
- Open any .py or .cpp (tested ones, not exclusive to them)
- Move cursor on different code blocks, functions, classes... etc

*Observed behaviour:* :eyes: :broken_heart:
For any code block under the cursor, the top bar shows the `*invalid*` word next to the function/symbol name, see the attached screenshot.

![Screenshot_20210121_180202](https://user-images.githubusercontent.com/3716399/105386774-16b59680-5c15-11eb-943f-a405afd672fe.png)

*Expected behaviour:* :heart: :smile:
Anything but the `*invalid*`!

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a65497be7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(erc slack syntax-checking spell-checking
     (languagetool :variables langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*" langtool-default-language "en-US")
     auto-completion helm templates helpful ibuffer tabs org mu4e
     (treemacs :variables treemacs-use-all-the-icons-theme t)
     unicode-fonts games common-lisp emacs-lisp gpu sql asciidoc bibtex csv graphviz html json latex markdown plantuml restructuredtext yaml shell-scripts vimscript windows-scripts major-modes ess julia octave ipython-notebook asm lua python rust
     (c-c++ :variables c-c++-default-mode-for-headers 'c-mode c-c++-adopt-subprojects t c-c++-enable-c++11 t c-c++-backend 'lsp-clangd c-c++-lsp-enable-semantic-highlight t c-c++-lsp-semantic-highlight-method 'overlay c-c++-lsp-semantic-highlight-rainbow t c++-enable-organize-includes-on-save t)
     copy-as-format multiple-cursors spacemacs-completion spacemacs-defaults spacemacs-editing spacemacs-editing-visual spacemacs-evil spacemacs-language spacemacs-layouts spacemacs-misc spacemacs-modeline spacemacs-navigation spacemacs-org spacemacs-project spacemacs-purpose spacemacs-visual dash deft elfeed epub pdf speed-reading git version-control colors dap debug docker pandoc prettier ranger sphinx systemd vagrant web-beautify xclipboard lsp
     (cmake :variables cmake-enable-cmake-ide-support t cmake-backend 'lsp)
     (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom)
     confluence search-engine)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
This also happens to me

**Comment by zjp** [comment]
I was just trying to google why this happens.

**Comment by c02y** [comment]
![image](https://user-images.githubusercontent.com/2135996/105856506-47863900-6024-11eb-97ba-6532b1d85a1a.png)

Does anyone know that what is the symbol in the picture that unable to be displayed? If possible, how can I hide the icon of the file type? I don't want emacs to display any icon.

**Comment by lebensterben** [comment]
>![image](https://user-images.githubusercontent.com/2135996/105856506-47863900-6024-11eb-97ba-6532b1d85a1a.png) ...

@c02y install a patched font, eg all-the-icon

**Comment by c02y** [comment]
@lebensterben  Thanks for the hint, and I found this whole line belongs to `lsp-headerline-breadcrumb-enable`, just set it to `nil` if anyone wants to hide it, and install [all-the-icons](https://github.com/domtronn/all-the-icons.el/) otherwise(I didn't try it)

**Comment by mmance** [comment]
I was just reading the spacemac docs:

2.6. Breadcrumb on headerline

To display breadcrumb in the headerline, set lsp-headerline-breadcrumb-enable to t.

You can customize the breadcrumb segments via lsp-headerline-breadcrumb-segments. Available segments are:

    project shows the name of the current project.
    file shows the name of the current file.
    path-up-to-project shows the path up to the current project.
    symbols shows the document symbols.

Does this mean that the symbols were missing - *invalid* ?

**Comment by lebensterben** [comment]
@mmance nope.

lsp-headerline-breadcrumb-enable is defined in Spacemacs. The other one is defined in lsp-ui and has default value.

**Comment by mmance** [comment]
I get the thing *invalid* at the top just like you, I don't see it unless I have LSP mode enabled and I am working with cpp files.

**Comment by spacegoing** [comment]
> @lebensterben Thanks for the hint, and I found this string of whole line belongs to `lsp-headerline-breadcrumb-enable`, just set it to `nil` if anyone wants to hide it, and install [all-the-icons](https://github.com/domtronn/all-the-icons.el/) otherwise(I didn't try it)

I installed all fonts but it didn't help. *invalid* persists. I'm using pylsp backend

**Comment by wordhazard** [comment]
Same issue here.  I have all-the-icons installed with the fonts and still see "*invalid*".  I'm using ccls for backend.

**Comment by smile13241324** [comment]
Still valid, I am also seeing the string invalid, lets see if I can find out where this comes from

**Comment by smile13241324** [comment]
Hmpf this is stickyfunc-enhance I have no idea whether we really need this what I can say is that it is not useful when used together with LSP.

**Comment by smile13241324** [comment]
I have removed stickyfunc-enhance now as it is unmaintained for around 9 years now and is causing a lot of side effects in other modes. In addition its features are superseded by lsp-breadcrumb mode anyway so if this feature is missing please switch to a maintained LSP server.

**Comment by smile13241324** [comment]
This has removed the invalid tag for me in all lsp sessions.
