### ISSUE TITLE
How do I close Treemacs buffer without focusing it?

### ISSUE THREAD

**Issue by Invertisment** [syl20bnr/spacemacs#14323]
Hi.
Is there a way to close Treemacs (not kill) without focusing the window and issuing a window close command (in my case I would write `:q`).
It's easy to open Treemacs window by clicking `SPC 0` or `alt+0` but there is no shortcut to close it without focusing it.

This is what my search outputs for window commands:

![Screenshot at 2021-01-26 11-14-18](https://user-images.githubusercontent.com/1641263/105825431-445d5f80-5fc8-11eb-923c-8012c3bee596.png)

Is there a shortcut that could be general for whole editor? I could use that as well.
Currently I sometimes use vim's `:only` to remove other windows but it's not ideal if I have more than one window that I want to keep.

**Comment by duianto** [comment]
`SPC f t` can be used to hide the treemacs window when the cursor isn't in the treemacs window.
It calls `treemacs`, and it's docstring says:
>Initialise or toggle treemacs.
>* If the treemacs window is visible hide it.
>* If a treemacs buffer exists, but is not visible show it.
>* If no treemacs buffer exists for the current frame create and show it.
>* If the workspace is empty additionally ask for the root path of the first
  project to add.

**Comment by Invertisment** [comment]
Ah. I use `SPC f t` regularly but I didn't think to use it this way. Thanks.
