### ISSUE TITLE
Fresh installation fails on installing font-lock+ because of no `ssh-askpass`

### ISSUE THREAD

**Issue by gfarrell** [syl20bnr/spacemacs#14327]
System: Archlinux (kernel 5.9.14-arch1-1)

I freshly installed emacs (27.1-3) and followed the instructions in this repo to install spacemacs from the `develop` branch:

```
rm -rf ~/.emacs.d
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```

On opening emacs, I selected `vim` mode and the default spacemacs installation. I then hit this error (and on every subsequent quit-and-reopen cycle get the same error):
```
Errors:
    - 
      An error occurred while installing font-lock+ (error: (error Failed to checkout ‘font-lock+’: ‘Command ’(env LC_ALL=C /usr/bin/timeout -k 60 600 git clone https://github.com/emacsmirror/font-lock-plus.git /home/gideon/.emacs.d/.cache/quelpa/build/font-lock+/ --origin origin --depth 1 --no-single-branch)’ exited with non-zero status 128: Cloning into '/home/gideon/.emacs.d/.cache/quelpa/melpa'...
      ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
      git@github.com: Permission denied (publickey).
      fatal: Could not read from remote repository.
      
      Please make sure you have the correct access rights
      and the repository exists.
      Cloning into '/home/gideon/.emacs.d/.cache/quelpa/build/font-lock+'...
      ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
      git@github.com: Permission denied (publickey).
      fatal: Could not read from remote repository.
      
      Please make sure you have the correct access rights
      and the repository exists.
      ’))
```

`git clone` is working from GH urls everywhere else, but my system does not have `ssh-askpass` installed, and it seems that this script is expecting it for some reason.

**Comment by alexey0308** [comment]
duplicate https://github.com/syl20bnr/spacemacs/issues/14168

**Comment by alexey0308** [comment]
Hi @gfarrell 

what is the output for 
```
git remote -v
```
when run from `~/.emacs.d/.cache/quelpa/build/font-lock+`? Is there not the HTTPS protocol shown?

Does it help, if you either
1) remove font-lock+ directory in the cache or
2) change the URL in the font-lock+ repository to https
```
git remote set-url origin https://github.com/emacsmirror/font-lock-plus.git
```
?

**Comment by gfarrell** [comment]
```.../quelpa/build/font-lock+ > git remote -v                                (master!)
origin	git@github.com:emacsmirror/font-lock-plus.git (fetch)
origin	git@github.com:emacsmirror/font-lock-plus.git (push)```

I'll try to get everything to happen from scratch to see if it is still broken.

**Comment by gfarrell** [comment]
Tried `rm -rf ~/.emacs.d` and re-cloning, then opening emacs. Got a number of warnings during installation, then this error instead:

```
Warning (evil-collection): `evil-want-keybinding' was set to nil but not before loading evil.

Make sure to set `evil-want-keybinding' to nil before loading evil or evil-collection.

See https://github.com/emacs-evil/evil-collection/issues/60 for more details.
Error (use-package): Cannot load evil-unimpaired
```

**Comment by lebensterben** [comment]
They're not related to the original issue.
Is `font-lock+` correctly installed now?

**Comment by gfarrell** [comment]
Nope, on opening `emacs` I still get the errors with installing `font-lock+`.

```
An error occurred while installing font-lock+ (error: (error Failed to checkout ‘font-lock+’: ‘Command ’(env LC_ALL=C /usr/bin/timeout -k 60 600 git clone https://github.com/emacsmirror/font-lock-plus.git /home/gideon/.emacs.d/.cache/quelpa/build/font-lock+/ --origin origin --depth 1 --no-single-branch)’ exited with non-zero status 128: Cloning into '/home/gideon/.emacs.d/.cache/quelpa/melpa'...
      ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
      git@github.com: Permission denied (publickey).
      fatal: Could not read from remote repository.
      
      Please make sure you have the correct access rights
      and the repository exists.
      Cloning into '/home/gideon/.emacs.d/.cache/quelpa/build/font-lock+'...
      ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
      git@github.com: Permission denied (publickey).
      fatal: Could not read from remote repository.
      
      Please make sure you have the correct access rights
      and the repository exists.
```

But when I try to `cd ~/.emacs.d/.cache/quelpa/bulid/font-lock+` there is no such directory, so I can't set the remote.

**Comment by lebensterben** [comment]
@gfarrell 
Takes a look at https://git-scm.com/docs/gitcredentials#_requesting_credentials
It might be caused by your .gitconfig

**Comment by gfarrell** [comment]
I don't think so, I use git all the time to push and pull from a variety of
repos without any issues.

--
*Gideon Farrell*
Co-founder / CTO

www.converge.io

**Comment by lebensterben** [comment]
@gfarrell 
You may try replace the following in `~/.emacs.d/layers/+spacemacs/spacemacs-modeline/packages.el`:
```elisp
(font-lock+ :step pre
            :location (recipe :fetcher github
                              :repo emacsmirror/font-lock-plus))
```
with
```elisp
(font-lock+  :step pre
             :location (recipe :fetcher wiki))
```

**Comment by gfarrell** [comment]
@lebensterben that seems to have done the trick, thanks!

**Comment by lebensterben** [comment]
@gfarrell 
But.. this is not really a fix, but just circumvent the need for using git.. You still have issue with your git configuration.

There's nothing wrong with ssh-askpass, since no one manage credentials this way.

**Comment by gfarrell** [comment]
@lebensterben I think I identified the problem -- very old line in my git config that wasn't a problem because I normally use ssh checkouts but it was rewriting https checkouts. I suspect it was asking for ssh_askpass because it was running git clone outside of my shell (which would have the relevant environment variables already set).
