### ISSUE TITLE
Git layer breaks spacemacs

### ISSUE THREAD

**Issue by malchmih** [syl20bnr/spacemacs#1433]
Hello! Emacs layer without configuration somehow breaks Spacemacs in develop branch. For example, in Org mode, when I press ",", I receive "No previous search". If I disable the layer, everything works fine. I use Ubuntu with Emacs 24.3.1. On my Mac with Emacs 24.5.1 it works fine. It is also ok in 'master' branch.
There is also a message in '*Messages*' buffer: 'File mode specification error: (void-function with-eval-after-load)'. Not sure if it's related, but I see it only in 'develop'.

**Comment by person808** [comment]
I know the error. Git-gutter uses `with-eval-after-load` to load but it is only available in 24.4. I'll create a PR to fix it.

**Comment by malchmih** [comment]
Thank you!
