### ISSUE TITLE
Emacs freezes non-deterministically when inserting text in org-mode

### ISSUE THREAD

**Issue by trentfridey** [syl20bnr/spacemacs#14336]
#### Description :octocat:
Emacs freezes when inserting text in org-mode, usually in LaTeX markup. This freeze is temporary and requires external kill command. It doesn't happen in every org-mode editing session, nor does it affect every LaTeX markup, but once it triggers at a certain character, it will happen again if I attempt to resume inserting on the same character after restarting Emacs. I thought it might be spell check, but I turned that layer off and it still occurs.

#### Reproduction guide :beetle:
- Start Emacs
- Open an org document
- Insert LaTeX markup
- Render markup with `, T x`
- Repeat previous two steps a number of times
- ?

*Observed behaviour:* :eyes: :broken_heart:
Emacs freezes, becomes unresponsive, and must be killed externally via System Monitor. Upon restart, the document changes may or may not be recoverable.

*Expected behaviour:* :heart: :smile:
Regular ol' org mode editing experience.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3eb66f4ce)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust javascript emoji emacs-lisp html git helm lsp graphviz themes-megapack python julia multiple-cursors
      (org :variables org-enable-hugo-support t)
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER LCMS2 GMP

**Comment by arifer612** [comment]
I have also started to observe this issue. The only major change I had that might have caused this issue was the addition of the `auto-completion` and `lsp` layers. I came to realise that turning off `company-mode` while in `org-mode` reduced the number of times Emacs freezes but it still does not remove the fact that it will freeze every once in a while.

**Comment by lebensterben** [comment]
closing in favour of #14342
