### ISSUE TITLE
LSP does not remember git project if path to it contains symlinks

### ISSUE THREAD

**Issue by sfalmo** [syl20bnr/spacemacs#14331]
#### Description :octocat:
LSP does not remember git project if path to it contains symlinks

#### Reproduction guide :beetle:
- Have a git repo, e.g. consisting of `src/main.cpp` and `src/other.cpp`. This project lives in `long/path/to/project/`. Make a symlink: `ln -s long/path/to shortcut`.
- Start Emacs, open `main.cpp` by `SPC f f` and navigating through `shortcut/project/src/main.cpp`.
- LSP layer asks if project with root path `long/path/to/project` shall be imported, press `i` for yes. LSP works.
- Open `other.cpp` via `SPC f f`. LSP layer asks again if project shall be imported, you have to press `i` again for the LSP to also work on `other.cpp`.
- Close and reopen Emacs. Select `shortcut/project/src/main.cpp` from recent projects. You get asked again to import the project.

*Observed behaviour:* :eyes: :broken_heart:
The LSP layer does not remember imported projects if the path contains a symlink. By navigating to it via the full path, the LSP remembers the import and does not ask again. I tried to reproduce this issue without the project being a git repo, but in this case everthing works as far as I can tell.
Apart from the observed problem, I noticed that in this situation, the language server fails to start for python files, giving the message `File mode specification error: (wrong-type-argument stringp nil)`. This does not occur when using the full path.

*Expected behaviour:* :heart: :smile:
It should not matter if a project is reached via a symlink. The LSP layer should recognize the imported project even when using symlinks to navigate to corresponding files.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c590d84f7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(c-c++ python html javascript php emacs-lisp git helm markdown yaml
       (latex :variables latex-enable-auto-fill nil)
       syntax-checking lsp treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by smile13241324** [comment]
This is no layer issue but either caused by LSP-mode or projectile, please open an issue upstream.

**Comment by lebensterben** [comment]
Seems related: https://github.com/bbatsov/projectile/issues/1387
