### ISSUE TITLE
[.spacemacs.evn] env var DISPLAY is different for each `ssh -X` session, should not be stored in .spacemacs.evn

### ISSUE THREAD

**Issue by sunlin7** [syl20bnr/spacemacs#14348]
The env `DISPLAY` is stored in `.spacemacs.evn` as constant value, while it's actually different for each `ssh -X ...` session, and cause error when execute `(shell-command-to-string "emacs -q")` with error message when the real `DISPLAY` for running session is `localhost:13.0`, the `localhost:10.0` is the `DISPLAY` value which is stored in `.spacemacs.evn`.
```
Display localhost:10.0 unavailable...
```

**Comment by smile13241324** [comment]
Ups, this doesn't sound right, I will check later if we can exclude it from there.

**Comment by JAremko** [comment]
Add `display` to  `spacemacs-ignored-environment-variables`

**Comment by sunlin7** [comment]
JAremko's solution work in my local, I'll create a PR for this. Thanks

**Comment by sunlin7** [comment]
Close for solution 722fa45ea13412d1edc68a454ec3ab5dfd272669 merged.
Thanks.
