### ISSUE TITLE
Cannot pair parentheses "(" in latex mode after installing cdlatex

### ISSUE THREAD

**Issue by quarkquartet** [syl20bnr/spacemacs#14340]
I installed cdlatex package for the math-modify function which is not included in the latex layer of spacemacs. Code:

```elisp
dotspacemacs-configuration-layers
(
        (latex :variables
                   latex-backend 'company-auctex
                   latex-build-engine 'xetex
                   latex-enable-magic t
                   latex-enable-folding t)
)
dotspacemacs-additional-packages '(
cdlatex
)
(add-hook 'LaTeX-mode-hook 'turn-on-cdlatex)
(add-hook 'org-mode-hook 'turn-on-org-cdlatex)
```

Then, when I type `(` in latex, no pair appears. All other types of parenthesis, like `{`,  are fine.
This problem only happens to latex mode, not to org-mode. 
Screenshots:
![image](https://user-images.githubusercontent.com/26316540/106413265-9dd5ec00-6417-11eb-8702-f95180e2e283.png)

I tried https://gitmemory.com/issue/cdominik/cdlatex/15/643754217, but nothing changes. 

Anyway to install cdlatex in spacemacs without conflicting with the parenthesis?

**Comment by alexey0308** [comment]
Hi @IsaacRWangPhysics, you can try to add "(" symbol to  `cdlatex-paired-parens` variable while using `customize-variable`. Does it help?

**Comment by IsaacRWangPhysics** [comment]
> Hi @IsaacRWangPhysics, you can try to add "(" symbol to `cdlatex-paired-parens` variable while using `customize-variable`. Does it help?

Thanks. I finally take the opposite way and it works: forbid the parens in cdlatex. I guess both way works. My code:
`(define-key cdlatex-mode-map  "(" nil)`

**Comment by alexey0308** [comment]
@IsaacRWangPhysics I guess, the issue can be closed now?
