### ISSUE TITLE
Vue-mode doesn't support vue-i18n translations

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#14352]
#### Description :octocat:
Vue-mode doesn't works with i18n section.
If you work with vue.js and translations, you will probably end up using [vue-i18n](http://kazupon.github.io/vue-i18n/guide/sfc.html#basic-usage). It add support for in component translation using a i18n section (same level as the script and style section).
i18n section would contain a json translation looking like this:

```html
<i18n>
{
  "en": {
    "hello": "hello world!"
  },
  "ja": {
    "hello": "こんにちは、世界！"
  }
}
</i18n>
```

It also support YAML:

```html
<i18n>
en:
  hello: "hello world!"
ja:
  hello: "こんにちは、世界！"
</i18n>
```

#### Reproduction guide :beetle:
- Start Emacs
- open a .vue file that contain a i18n section
- i18n section should be showed as json content, but it's not

*Observed behaviour:* :eyes: :broken_heart:
i18n section isn't parsed correctly.

*Expected behaviour:* :heart: :smile:
i18n should be parsed as json

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 234144853)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 helm emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 github markdown csv org
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom multi-term-program "/usr/bin/zsh")
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary nil enable-flyspell-auto-completion t)
 syntax-checking shell-scripts
 (php :variables php-backend 'lsp)
 restclient
 (sql :variables sql-capitalize-keywords t)
 (html :variables css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t web-fmt-tool 'prettier)
 lsp dap
 (javascript :variables javascript-fmt-tool 'prettier javascript-import-tool 'import-js javascript-backend 'lsp)
 (vue :variables vue-backend 'lsp)
 typescript prettier yaml finance colors multiple-cursors unicode-fonts
 (docker :variables docker-dockerfile-backend 'lsp)
 (version-control :variables version-control-global-margin t shell-default-term-shell "/bin/bash")
 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp/" mu4e-enable-notifications t mu4e-enable-mode-line t mu4e-use-maildirs-extension t)
 (python :variables python-backend 'lsp python-lsp-server 'pyls python-formatter 'black)
 imenu-list dash)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
you'd report this to vue-mode

**Comment by phenix-factory** [comment]
@lebensterben Even if it's called "vue-mode", Spacemacs *doesn't* use vue-mode.
By Spacemacs documentation (https://develop.spacemacs.org/layers/LAYERS.html#vue) : 

> Note: This layer creates a derived mode called vue-mode on the fly out of web-mode to handle vue files. It will conflict with the vue-mode package, make sure you don't use that package together with this layer.

**Comment by thanhvg** [comment]
Yes, spacemacs vue mode is a derived web-mode. You can ask web-mode dev for help https://github.com/fxbois/web-mode/issues

**Comment by lebensterben** [comment]
It's reported upstream. See https://github.com/fxbois/web-mode/issues/1178
