### ISSUE TITLE
Hash symbol, osx, British keyboard layout.

### ISSUE THREAD

**Issue by latkins** [syl20bnr/spacemacs#1435]
Using the osx layer with a British keyboard  layout (on a macbook pro, in my case) leaves you unable to type # (this is usually alt-3). Instead, you switch to the 3rd window. Is there some workaround for this?

**Comment by syl20bnr** [comment]
Are you using Vim or Emacs editin style ?

**Comment by latkins** [comment]
Vim.

**Comment by syl20bnr** [comment]
You can remove the key bindings then since you can use `SPC #` where `#` is the window number.
Add this in your `dotspacemacs/config` function:

```elisp
    (define-key window-numbering-keymap "\M-0" nil)
    (define-key window-numbering-keymap "\M-1" nil)
    (define-key window-numbering-keymap "\M-2" nil)
    (define-key window-numbering-keymap "\M-3" nil)
...
```

Up to 9.

**Comment by latkins** [comment]
That fixed it. Thanks!

**Comment by obmarg** [comment]
I still can't type # after adding those `define-key` calls - now emacs seems to be interpreting alt-3 as the start of a command.

**Comment by obmarg** [comment]
Adding `(global-set-key (kbd "M-3") `(lambda () (interactive) (insert "#")))` as suggested here: http://stackoverflow.com/a/4786456/589746

Though if there's a more official fix I'd be open to using it.

**Comment by latkins** [comment]
I should note that this only works for me when opening emacs through the command line, I still can't type # when I go via the gui.

**Comment by obmarg** [comment]
Yeah, I was having problems in the GUI - not tried the command line.

**Comment by fmjrey** [comment]
So any idea how to fix the GUI, i.e. when you launch not from the command line?

**Comment by obmarg** [comment]
@fmjrey - I managed to get it working in the GUI by adding these lines: https://github.com/obmarg/dotfiles/blob/master/_spacemacs#L154-L166

**Comment by svalaskevicius** [comment]
the pasted config does allow inserting `#` however it also switches to editing mode.. so e.g. doesnt start backwards search of the highlighted word when in normal mode

**Comment by davemee** [comment]
It's a bit of a killer. The magic copypasta isn't working for me, though I have access to the £ symbol, which I think I've just needed to type for the first time in a decade. 

I suppose it gives me a good excuse for not commenting any code.

**Comment by davemee** [comment]
...or I only leave comments when running in a terminal. Looks like it's only being uncooperative running the non-terminal version.

**Comment by davemee** [comment]
...and then I have to fall back to ⎋ as the Meta key.

**Comment by chrismcg** [comment]
I use `mac-right-option-modifier nil` https://github.com/chrismcg/spacemacs_private/blob/master/dot_spacemacs#L231 which means right alt + 3 = # and left alt + 3 switches to window 3.

**Comment by davemee** [comment]
oh god thank you so much @chrismcg which will be one of the many names of my first child.

**Comment by apacala** [comment]
Thanks, @chrismcg ❤️

**Comment by d12frosted** [comment]
I constantly have to type `ALT` characters. That's why I don't use option key as meta key. Instead, my `cmd` is meta key.

> I still can't type # after adding those define-key calls - now emacs seems to be interpreting alt-3 as the start of a command.

@obmarg, by default `M-<number>` is treated as `C-u <number>` - this is nice shortcut for passing universal argument.

**Comment by AstonJ** [comment]
The snippets in this thread are not working for me - does anyone have a confirmed solution to this issue please? (For the left hand alt-key + 3)

**Comment by coelias** [comment]
For latest versions of winum use:

```
   (define-key winum-keymap "\M-3" nil)
   (global-set-key (kbd "M-3")(lambda () (interactive) (insert "#")))
```

**Comment by edalee** [comment]
@coelias where do you add this?  In `defun dotspacemacs/user-config ()` after package-selected-packages?

**Comment by coelias** [comment]
Yes it used to be at the end of ~/.emacs.d/elpa/winum-20171028.702/winum.el

Now it doesn't work, you have to modify /Users/deepbit/.emacs.d/layers/+spacemacs/spacemacs-ui/packages.el:

...
...
      (define-key winum-keymap (kbd "M-6") 'winum-select-window-6)
      (define-key winum-keymap (kbd "M-7") 'winum-select-window-7)
      (define-key winum-keymap (kbd "M-8") 'winum-select-window-8)
      (define-key winum-keymap (kbd "M-9") 'winum-select-window-9)
      (define-key winum-keymap "\M-3" nil)
      (global-set-key (kbd "M-3")(lambda () (interactive) (insert "#")))
      (winum-mode))))

**Comment by Drakx** [comment]
> Yes it used to be at the end of ~/.emacs.d/elpa/winum-20171028.702/winum.el
> 
> Now it doesn't work, you have to modify ~/.emacs.d/layers/+spacemacs/spacemacs-ui/packages.el:
> 
> ...
> ...
> (define-key winum-keymap (kbd "M-6") 'winum-select-window-6)
> (define-key winum-keymap (kbd "M-7") 'winum-select-window-7)
> (define-key winum-keymap (kbd "M-8") 'winum-select-window-8)
> (define-key winum-keymap (kbd "M-9") 'winum-select-window-9)
> (define-key winum-keymap "\M-3" nil)
> (global-set-key (kbd "M-3")(lambda () (interactive) (insert "#")))
> (winum-mode))))

It seems this file has since moved from the date of this comment, I just edited the following file and it working as expected
`~/.emacs.d/layers/+spacemacs/spacemacs-navigation/packages.el`
