### ISSUE TITLE
problems installing spacemacs

### ISSUE THREAD

**Issue by Trincazul** [syl20bnr/spacemacs#14362]
when I clone the project and try to open emacs, nothing happens emacs remains the old one, I tried it on linux mint and macOS.
could be an incompatibility of the emacs version?
already tried to remove emacs and try to download the repository and nothing happens.

I'm cloning directly into ~ / .emacs.d

**Comment by lebensterben** [comment]
This should be cloned AS ~/.emacs.d, not INTO ~/.emacs.d.

**Comment by Trincazul** [comment]
thank you very much, I will take the test here

**Comment by Mikrodz** [comment]
Hi! I just installed Spacemacs and Emacs. I'm new at both. I faced the same issue and the solution was: 
`rm .emacs`
`rm -r .emacs.d`
![capture-spacemacsfix](https://user-images.githubusercontent.com/76720718/145888653-abf1fee6-18e1-497a-bddc-7bac37284729.png)
I hope this helps!
