### ISSUE TITLE
Error occurred while loading ~/.emacs.d/init.el

### ISSUE THREAD

**Issue by sanklamm** [syl20bnr/spacemacs#14365]
I am running the spacemacs development branch and just updated it to commit `9375d6f54d10b9159ac833ee6eaf43f29b233a9f` when I got an error during startup.

Running a `git bisect` identified the following as the first bad commit

```
f62934620d49effcf4248a2feb458bcfdb6c963c is the first bad commit
commit f62934620d49effcf4248a2feb458bcfdb6c963c
Author: duianto <otnaiud@gmail.com>
Date:   Wed Dec 23 15:01:07 2020 +0100

    [base] Fix evil undo
```

I am running emacs 27.1 from the AUR on a current Manjaro system.

My solution will be to work with the last "good" commit.

**Comment by lebensterben** [comment]
what error?

**Comment by sanklamm** [comment]
```
Warning (initialization): An error occurred while loading ‘~/.emacs.d/init.el’:

Symbol's function definition is void: evil-set-undo-system
```

**Comment by lebensterben** [comment]
Have you updated all packages?

**Comment by Hneuschmidt** [comment]
I get the same error on current OpenSUSE tumbleweed

**Comment by lebensterben** [comment]
Update Emacs packages. Nothing to do with your distro package.

https://github.com/syl20bnr/spacemacs/issues/14267

**Comment by duianto** [comment]
Spacemacs now checks that `evil-set-undo-system` is bound (exists),
before setting the `evil-set-undo-system`.

Handle when evil-set-undo-system is missing https://github.com/syl20bnr/spacemacs/commit/b93bdbd4ad75566dc44f47698212b2ad30f3cd4e

**Comment by sanklamm** [comment]
Very good. Thanks for the help.
