### ISSUE TITLE
magit-status error: Wrong argument: listp, 4

### ISSUE THREAD

**Issue by eshom** [syl20bnr/spacemacs#14364]
#### Description :octocat:
magit-status command fails: `Wrong argument: listp, 4`

#### Reproduction guide :beetle:
- Start Emacs
- Run `M-x magit-status` or `SPC g s`
- Choose a repository

*Observed behaviour:* :eyes: :broken_heart:
Getting the output `Wrong argument: listp, 4` when running magit-status after choosing a repository, or when the working directory is already a git repository.

*Expected behaviour:* :heart: :smile:
Open the magit-status buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9375d6f54)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm lsp auto-completion better-defaults emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control semantic ess csv latex markdown multiple-cursors shell-scripts c-c++ colors themes-megapack theming imenu-list asm python spacemacs-editing xclipboard common-lisp pdf treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by eshom** [comment]
Actually, `magit` seems to be completely broken. It worked fine yesterday.

**Comment by lebensterben** [comment]
Cannot reproduce..

**Comment by eshom** [comment]
Still broken even after switching `.spacemacs` to the template (+ git layer), after rolling back package updates, and after rolling back to previous commits.

**Comment by lebensterben** [comment]
need more detailed error message

**Comment by eshom** [comment]
Sorry I'm new to debugging elisp. This should be the backtrace?
```
Debugger entered--Lisp error: (wrong-type-argument listp 4)
  dir-locals--get-sort-score(4)
  #f(compiled-function (a b) #<bytecode 0x1fe50f0d94e5>)(4 python-indent-offset)
  sort((setq) #f(compiled-function (a b) #<bytecode 0x1fe50f0d94e5>))
  dir-locals--sort-variables((setq))
  dir-locals-read-from-dir("/home/erez/python/venv/discoRd-bot/")
  hack-dir-local-variables()
  hack-dir-local-variables-non-file-buffer()
  magit-mode()
  magit-status-mode()
  magit-setup-buffer-internal(magit-status-mode nil ((magit-buffer-diff-args ("--no-ext-diff")) (magit-buffer-diff-files nil) (magit-buffer-log-args ("-n256" "--decorate")) (magit-buffer-log-files nil)))
  magit-status-setup-buffer("~/python/venv/discoRd-bot/")
  magit-status(nil ((6 . 3) (("~/python/venv/discoRd-bot/" . magit-toplevel) . "/home/erez/python/venv/discoRd-bot/") (("/home/erez/python/venv/discoRd-bot/" "rev-parse" "--show-cdup") . "") (("/home/erez/python/venv/discoRd-bot/" "rev-parse" "--show-toplevel") . "/home/erez/python/venv/discoRd-bot")))
  funcall-interactively(magit-status nil ((6 . 3) (("~/python/venv/discoRd-bot/" . magit-toplevel) . "/home/erez/python/venv/discoRd-bot/") (("/home/erez/python/venv/discoRd-bot/" "rev-parse" "--show-cdup") . "") (("/home/erez/python/venv/discoRd-bot/" "rev-parse" "--show-toplevel") . "/home/erez/python/venv/discoRd-bot")))
  call-interactively(magit-status nil nil)
  command-execute(magit-status)
```

**Comment by eshom** [comment]
This backtrace makes it obvious. My .dir-locals.el file was wrong, which caused magit to not work. Sorry and thank you for your time.
