### ISSUE TITLE
WoMan and TexInfo manual pages are sporadically, improperly formatted in Spacemacs

### ISSUE THREAD

**Issue by bryce-carson** [syl20bnr/spacemacs#14374]
#### Description :octocat:
The faces applied to sections of either texinfo info pages or man pages (using woman) are incorrect in Spacemacs. 

#### Reproduction guide :beetle:
- Start Emacs
- `SPC h m` to start woman (help-man-woman)
- Open a manual, such as BASH.

*Observed behaviour:* :eyes: :broken_heart:
Some areas are properly coloured and have the correct face applied, while others are improperly underlined. This issue is not present in default Emacs (begun with `emacs -q`).

At present, I am not able to reproduce the issue in `info`, but it is seen there occasionally.

The issue is sporadic; for example, sometimes the *Shell Grammar* section is properly formatted, other times it is entirely underlined, and sometimes the *Options* section is properly formatted, other times it is not.

*Expected behaviour:* :heart: :smile:
Formatting is correct and consistent across sessions.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ba9e0afa3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp helm html markdown multiple-cursors org python
                 (shell :variables shell-default-height 60 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER GMP

#### Backtrace :paw_prints:
No backtrace.

#### Screenshots
![Screenshot from 2021-02-12 16-14-48](https://user-images.githubusercontent.com/51974245/107832372-7eab5880-6d4d-11eb-9ce2-83e752f0617f.png)

**Comment by lebensterben** [comment]
not able to reproduce this
