### ISSUE TITLE
Packages 'php-auto-yasnippet' and 'phpcbf' in php layer unavailable

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#14381]
After installing the php layer, Spacemacs shows messages for `php-auto-yasnippet` and `phpcbf` that the packages are unavailable. Both packages have been archived on github (see [phpcbf](https://github.com/nishimaki10/emacs-phpcbf] and [php-auto-yasnippet]9https://github.com/emacs-php/php-auto-yasnippets)), and have been removed from Melpa (I guess both packages where available from Melpa before).
I don't work with php myself (I installed accidentally while using [org-thtml](https://github.com/juanjosegarciaripoll/org-thtml), where I probably pressed space when I was prompted for install of the php-layer.), so I don't know if the packages should be removed, or if better their "locations" should get updated.

**Comment by smile13241324** [comment]
To be honest if they have been removed from melpa I would vote for removing them from php layer completely. If this breaks major functionality for the emacs based backends we can still change the default to LSP, same as we did for scala.

**Comment by dbrw** [comment]
I use lsp as backend for PHP but still get the same errors.

**Comment by dalanicolai** [comment]
Yeah, I am not touching this layer because I do not use the PHP layer. Hope any PHP user will help with this soon... anyway, you can neglect these errors and/or add those packages to the  `dotspacemacs-excluded-packages` in your dotfile
`

**Comment by dbrw** [comment]
Thanks, my work around was just commented the two packages. Your tip to add those two packages to `dotspacemacs-excluded-packages` is great to know.

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
[+layer/php] Fix missed packages #14581

The two packages are pulled from their archived repositories:
https://github.com/nishimaki10/emacs-phpcbf
https://github.com/emacs-php/php-auto-yasnippets

**Comment by stradicat** [comment]
Apparently, the latest `develop` branch is still looking for  the repo when updating packages (I have the PHP layer active):

```
Updating /Users/stradicat/.emacs.d/.cache/quelpa/build/php-extras/
Fetcher: github
Source: nishimaki10/emacs-phpcbf

Updating /Users/dmayr/.emacs.d/.cache/quelpa/build/phpcbf/
quelpa-checkout: Failed to checkout ‘phpcbf’: ‘Command ’(env LC_ALL=C /usr/local/bin/timeout -k 60 600 git fetch --tags origin)’ exited with non-zero status 128: HEAD is now at 529191d Version 1.70 released
'2024-01-08 17:03:22 +0100'HEAD is now at ae3ead6 Make evil-escape escape from company too
'2023-11-02 20:33:11 +0100'HEAD is now at 3f462c6 Minor amendments for use-package compatibility.
'2021-09-07 08:23:45 +0100'HEAD is now at fb82413 further support rg
'2022-10-06 21:25:30 +0800'HEAD is now at d1e94f5 no summary available
'2019-11-21 17:20:35 +0100'HEAD is now at 5369ece Merge pull request #28 from dmvianna/fix-gar
'2023-09-13 23:41:36 -0400'HEAD is now at 5f0de84 no summary available
'2023-05-29 04:41:26 +0200'HEAD is now at 4e85b25 Use a cached temporary buffer for truncated printing
'2023-09-25 19:46:22 -0300'HEAD is now at 92e1d33 Merge pull request #3 from andreas-marschke/fix-logcat-new-adb-versions
'2018-06-20 15:49:48 -0700'HEAD is now at 04969bb Update documentation
'2015-04-22 21:48:39 -0400'HEAD is now at a904596 Merge branch 'master' of https://github.com/bastibe/org-journal
'2021-04-17 16:12:54 +0200'HEAD is now at 352ab00 Org 9 compatibility
'2016-11-14 09:08:31 -0500'HEAD is now at 03e1f08 [Chore] Update all of the copyright years
'2017-03-30 21:14:31 -0400'HEAD is now at d410c5a Create CONTRIBUTING.md
'2016-05-18 17:16:36 +0200'remote: Repository not found.

fatal: repository 'https://github.com/nishimaki10/emacs-phpcbf.git/' not found
```

**Comment by smile13241324** [comment]
Ups, looks like I have missed this ticket, I will have a look.
