### ISSUE TITLE
Add warning to `evilified-state-evilify` docstring that it is deprecated

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#14388]
I was trying to evilify the keymap for the [ebib](http://joostkremers.github.io/ebib/) package. To remind myself how to evilify a map, I peeked in some other layer (don't remember which one). I found that it used the `evilified-state-evilify` macro.

However, when I used this macro, I noticed that it does not evilify correctly, e.g it does not move `j` -> `J` and `J` to `C-j` etc.

Now in the source code I find a comment that this is an old macro, while just below there is the new macro `evilified-state-evilify-map`, which does evilify correctly.

As it is probably discouraged to use the old macro, I guess it would be better to add that to the docstring.
I would be happy to do it (just let me know)

**Comment by lebensterben** [comment]
@dalanicolai 

If you're still interested in it, you can go ahead and add it to docstring.

Alternatively, you can make it as obsolete. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Obsolete-Functions.html
