### ISSUE TITLE
Error (use-package): markdown-mode/:config: Please refer to the layer documentation and install a markdown command

### ISSUE THREAD

**Issue by didibus** [syl20bnr/spacemacs#14387]
#### Description :octocat:
After updating to latest develop commit of Spacemacs I see: Error (use-package): markdown-mode/:config: Please refer to the layer documentation and install a markdown command

#### Reproduction guide :beetle:
- Start Emacs
- Have: markdown as a layer
- Don't have a markdown executable on your system
- Don't set any :variables on the layer
- You should see: Error (use-package): markdown-mode/:config: Please refer to the layer documentation and install a markdown command

*Observed behaviour:* :eyes: :broken_heart:
Error (use-package): markdown-mode/:config: Please refer to the layer documentation and install a markdown command

*Expected behaviour:* :heart: :smile:
No error to show up when starting emacs.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1.91
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e4452f9a8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(html javascript
      (clojure :variables clojure-enable-clj-refactor t clojure-enable-linters 'clj-kondo)
      (lsp :variables lsp-ui-doc-enable nil lsp-ui-sideline-enable nil)
      dap
      (java :variables java-backend 'lsp)
      (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
      emacs-lisp git ivy markdown multiple-cursors org spell-checking syntax-checking treemacs
      (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left version-control-global-margin t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY GFILENOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
Not sure what a backtrace is?
```

**Comment by lebensterben** [comment]
Make sure one of the following is in your PATH:

"markdown" "pandoc" "markdown_py"

**Comment by alexey0308** [comment]
Hi @lebensterben , 
it is explicitly mentioned, that it is **not** on the path.
As I understand, @didibus intention is not to have error on the package load.

Not everybody uses preview functionality. One may use it only for editing.

**Comment by lebensterben** [comment]
Yes. This should be gated behind a layer variable.

**Comment by didibus** [comment]
> As I understand, @didibus intention is not to have error on the package load

Exactly. I don't use live-preview, I just like having the markdown mode in the buffer with the special buffer formatting. A recent change makes it I get this error message on start, but I don't care for live-preview and don't want to install any markdown command app.

**Comment by sunlin7** [comment]
@didibus The error message displayed only you set the variable `markdown-executable` but it's not exists.
Could you check the value of `markdown-executable` in your environment and verify it's exists or not?

**Comment by sunlin7** [comment]
I can reproduce it now, I'm checking it.

**Comment by sunlin7** [comment]
PR https://github.com/syl20bnr/spacemacs/pull/14394 should be fix this issue.

**Comment by smile13241324** [comment]
Merged, please retest @didibus
