### ISSUE TITLE
Repeat and undo interaction

### ISSUE THREAD

**Issue by xsrvmy** [syl20bnr/spacemacs#14385]
#### Description :octocat:
Using the repeat operator (.) after undo causes unexpected behaviour and freezes.
(Maybe this is a problem with evil?)

#### Reproduction guide :beetle:
- Start Emacs
- Go to scratchpad buffer
- Enter insert mode, type something and exit
- Enter insert mode, type something again, and exit
- Hit u to undo
- Hit . to repeat

*Observed behaviour:* :eyes: :broken_heart:
Undoes again. Hitting . again will cause a freeze, and upon hitting C-G undo-tree-canary complains about a cycle.

*Expected behaviour:* :heart: :smile:
Repeats the second insert.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b6aa0e651)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm
            (latex :variables latex-enable-auto-fill nil)
            multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by xsrvmy** [comment]
Looks like this is a problem with evil actually

**Comment by bhipple** [comment]
Did you ever figure this out?  I'm experiencing frequent freezing when I hit `u` and would love some help.

**Comment by bhipple** [comment]
This could also use the `undo` label.

**Comment by xsrvmy** [comment]
I believe this was fixed upstream.
