### ISSUE TITLE
OCaml layer: Changes with upcoming opam version 2.1

### ISSUE THREAD

**Issue by bschommer** [syl20bnr/spacemacs#14392]
With the next opam version 2.1 `opam config var share` will no longer work and be replaced by `opam var share`. I think one can support older and newer versions of opam by testing both and only failing if both return no result.

**Comment by smile13241324** [comment]
This sounds like changes would be necessary to the ocaml layer. As I am oblivious to ocaml I would ask the community to provide a PR for this. Support for both versions would be cool but not a must requirement in my opinion

**Comment by bschommer** [comment]
Add the moment this isn't even a problem for users trying to use the new opam version since one can set the environment variable `OPAMCLI` to 2.0 to get the old behavior.
