### ISSUE TITLE
[BUG] languagetool layer correct buffer doesn't work 

### ISSUE THREAD

**Issue by Novite5** [syl20bnr/spacemacs#14390]
#### Description :octocat:
languagetool layer doesn't work, can't get to some functions.

#### Reproduction guide :beetle:
- Start Emacs
- add `languagetool` layer and set `langtool-java-classpath`

*Observed behaviour:* :eyes: :broken_heart:
Press `SPC S L`, print out the information:
`command-execute: Wrong type argument: commandp, langtool-correct-buffer`

But `SPC S l` works.

`M-X` can only find two commands: `langtool-check` and `langtool-check-buffer`

Previously I use **langtool** as additional package, all commands can be found.

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e4452f9a8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-idle-delay 0.2 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual auto-completion-enable-sort-by-usage t)
 bibtex bm
 (c-c++ :variables c-c++-backend 'lsp-clangd c++-enable-organize-includes-on-save t c-c++-enable-clang-format-on-save t c-c++-enable-auto-newline t c-c++-adopt-subprojects t c-c++-lsp-semantic-highlight-method 'rainbow)
 (chinese :variables chinese-enable-avy-pinyin nil)
 (colors :variables colors-colorize-identifiers 'all colors-default-rainbow-identifiers-sat 42 colors-default-rainbow-identifiers-light 86 colors-enable-nyan-cat-progress-bar
         (display-graphic-p))
 common-lisp csv
 (dash :variables dash-docs-docset-newpath "~/.local/share/Zeal/Zeal/docsets")
 (docker :variables docker-dockerfile-backend 'lsp)
 dtrt-indent emacs-lisp epub finance git github
 (geolocation :variables geolocation-enable-automatic-theme-changer t geolocation-enable-location-service t geolocation-enable-weather-forecast nil)
 (gtags :variables gtags-enable-by-default t)
 (helm :variables helm-enable-auto-resize t)
 helpful
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 imenu-list
 (ipython-notebook :variables ein-backend 'jupyter)
 (json :variables json-fmt-tool 'prettier json-fmt-on-save t json-backend 'lsp)
 (languagetool :variables languagetool-show-error-on-jump t langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*")
 (latex :variables latex-backend 'lsp latex-build-command "LaTeX" latex-enable-auto-fill t latex-enable-folding t latex-enable-magic t)
 lsp markdown major-modes
 (notmuch :variables notmuch-message-deleted-tags
          '("+deleted" "-inbox" "-unread"))
 (org :variables org-enable-bootstrap-support t org-enable-github-support t org-enable-reveal-js-support t org-enable-roam-support t org-enable-sticky-header t org-projectile-file "TODOs.org" org-want-todo-bindings t org-roam-directory "~/Dropbox/org/roam")
 outshine pandoc parinfer pdf prettier
 (python :variables python-backend 'lsp python-test-runner
         '(pytest nose)
         python-format-on-save t python-auto-set-local-pyenv-version 'on-visit python-fill-column 79 python-sort-imports-on-save t)
 rebox semantic
 (shell :variables close-window-with-terminal t shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 30 shell-default-position 'bottom)
 (shell-scripts :variables shell-scripts-backend 'lsp)
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary nil)
 systemd syntax-checking themes-megapack tmux
 (treemacs :variables treemacs-use-follow-mode 'tag treemacs-use-filewatch-mode t treemacs-use-scope-type 'Perspectives treemacs-use-git-mode 'deferred treemacs-collapse-dirs 3 treemacs-lock-width t treemacs-use-all-the-icons-theme t)
 typography
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 unicode-fonts
 (xclipboard :variables xclipboard-enable-cliphist t)
 (yaml :variables yaml-enable-lsp t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
commandp hints to a non interactive function being linked to a key binding, if the function makes sense here it must be wrapped into an interactive one.

**Comment by Novite5** [comment]
As non-programmer I have no idea how to solve this problem. 

But should be this linked to `langtool` package in **elpa**? 
Because even in `M-x` can't find `langtool-correct-this-buffer` command.

**Comment by smile13241324** [comment]
@Novite5 no problem I can take care. About the source I am not sure, basically someone did bound a non interactive function at a slot were only interactive functions are allowed. This could have been wrong from the beginning or have been changed afterwards.

Anyway the change should be pretty easy, let me have a look.

**Comment by smile13241324** [comment]
Done, the package was missing an autoload on `langtool-correct-this-buffer`. I have added this in our use-package declaration now and the issue was gone for me. @Novite5 can you double check?

**Comment by Novite5** [comment]
Yes. It has been fixed.
Thank you very much for your works! :)
