### ISSUE TITLE
markdown mode throwing error about git-commit-mode

### ISSUE THREAD

**Issue by LukeXuan** [syl20bnr/spacemacs#14397]
#### Description :octocat:
`git-commit-mode` doesn't exist before running something related to magit as least once. This causes an error when opening markdown files because it tests for `git-commit-mode`. 

#### Reproduction guide :beetle:
- Start Emacs
- Open a markdown file

*Observed behaviour:* :eyes: :broken_heart:
`File mode specification error: (void-variable git-commit-mode)`

*Expected behaviour:* :heart: :smile:
Nothing goes wrong.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7e38f2e64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(systemd csv javascript helm
         (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'nil)
         better-defaults emacs-lisp git pdf markdown chrome
         (latex :variables latex-build-command "LatexMk")
         (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-adopt-subprojects t)
         (python :variables python-backend 'lsp)
         lsp
         (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
         (spell-checking :variables spell-checking-enable-by-default nil)
         (syntax-checking :variables syntax-checking-enable-by-default t syntax-checking-enable-tooltips t)
         coq csharp ocaml
         (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER GMP

**Comment by basil-conto** [comment]
Potentially related to magit/magit#4293?

**Comment by smile13241324** [comment]
Issue confirmed, should be fixed now, can you check again @LukeXuan?

**Comment by LukeXuan** [comment]
It's working for me, thanks.
