### ISSUE TITLE
Error upon boot:

### ISSUE THREAD

**Issue by wrkelly** [syl20bnr/spacemacs#14395]
REPORT_SPACEMACS_ISSUE buffer arises upon boot saying:
Error (use-package): Cannot load adaptive-wrap
Error (use-package): undo-tree/:init: Symbol's function distribution is void: global-undo-tree-mode
Error (use-package): Cannot load undo-tree

I'm not able to find any reference to this. The same thing happens upon reinitialization. Any help is appreciated.

Cheers

**Comment by alexey0308** [comment]
does it help, if you reinstall these packages? M-x package-reinstall undo-tree and adaptive-wrap ?

**Comment by wrkelly** [comment]
Neither package is recognized with package-reinstall:
"Wrong type argument: package-desc, nil"

**Comment by alexey0308** [comment]
Maybe if you share more information, it could help people to assist you: 
- are you on develop branch
- emacs version
- is this error on fresh installation or what did you change before observing the issue?

**Comment by alexey0308** [comment]
Can they be found after `package-refresh-contents`?

**Comment by wrkelly** [comment]
Sure - I'm on the develop branch.
Emacs 27.1
This is from fresh install.

When trying package-refresh-contents:
      Failed to verify signature archive-contents.sig:
      No public key for 066DAFCB81E42C40 created at 2021-02-17T22:05:02+0000 using RSA
      Command output:
      gpg: keyblock resource '/c/Users/novel/Desktop/Emacs/i686/bin/c:/Users/novel/Desktop/Emacs/.emacs.d/elpa/gnupg/pubring.kbx': No such file or directory [(<<< I see the path is doubled up)]
      gpg: Signature made Wed Feb 17 22:05:02 2021 GMTST
      gpg:                using RSA key
      gpg: Can't check signature: No public key

I'm resolving this currently. Should I just reinstall a more stable branch of spacemacs?

**Comment by alexey0308** [comment]
So it looks like you are running Emacs under Cygwin. 
Maybe [this](https://emacs.stackexchange.com/questions/60278/gpg-no-public-key) can help.

**Comment by wrkelly** [comment]
Ok, thanks Alexey.

gpg problem doesn't resolve with these other solutions.

**Comment by alexey0308** [comment]
Also [here](https://github.com/syl20bnr/spacemacs/issues/13866): did you add
```
(setq package-check-signature nil)
```
inside `dotspacemacs/user-init ()` and it did not help?

**Comment by smile13241324** [comment]
@wrkelly could also be that you are using Spaceelpa? Check your dotfile for `dotspacemacs-use-spacelpa` this var should be nil. Apart of this I would assume you are having issues with gpg and package installation in general, please refer to the linked instructions for gpg installation. Also upgrading cygwin to the latest version could also help.

**Comment by wrkelly** [comment]
Ah, yes - that worked, Alexey. Thanks for the help.

**Comment by alexey0308** [comment]
great, @wrkelly, could you close the issue then?
