### ISSUE TITLE
LSP over-riding long established Clojure major mode key bindings

### ISSUE THREAD

**Issue by practicalli-john** [syl20bnr/spacemacs#14400]
#### Description :octocat:
LSP over-riding long established key bindings for the Clojure major mode

#### Reproduction guide 🐞 
- Start Emacs
- Add lsp layer
- Restart Emacs
- Open a Clojure project
- `i` to index the clojure project with lsp

*Observed behaviour:* :eyes: :broken_heart:
`, T s` should toggle evil-cleverparens and has been over-ridden by lsp
`, h h` should open cider-docs but is over-ridden by lsp docs (and links to src do not work in lsp)

Further investigation of keybindings is underway.

*Expected behaviour:* :heart: :smile:
LSP should not over-ride established CIDER key bindings even when using LSP, especially where the functionality of the replacing functions is different or not as comprehensive.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e4452f9a8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python asciidoc
        (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
        (clojure :variables clojure-enable-linters 'clj-kondo clojure-toplevel-inside-comment-form t cider-repl-buffer-size-limit 100)
        command-log colors csv emacs-lisp emoji
        (git :variables git-magit-status-fullscreen t magit-diff-refine-hunk 'all)
        github graphviz
        (helm :variables helm-follow-mode-persistent t)
        html javascript json
        (lsp :variables lsp-enable-on-type-formatting nil lsp-ui-sideline-show-diagnostics nil)
        (markdown :variables markdown-live-preview-engine 'vmd)
        multiple-cursors
        (spacemacs-modeline :variables doom-modeline-height 12 doom-modeline-major-mode-color-icon t doom-modeline-buffer-file-name-style 'relative-to-project doom-modeline-display-default-persp-name t doom-modeline-minor-modes nil doom-modeline-modal-icon nil)
        (org :variables org-enable-github-support t org-enable-bootstrap-support t org-enable-reveal-js-support t org-want-todo-bindings t org-enable-org-journal-support t org-journal-dir "~/projects/journal/" org-journal-file-format "%Y-%m-%d" org-journal-date-prefix "#+TITLE: " org-journal-date-format "%A, %B %d %Y" org-journal-time-prefix "* " org-journal-time-format "" org-journal-carryover-items "TODO=\"TODO\"|TODO=\"DOING\"|TODO=\"BLOCKED\"|TODO=\"REVIEW\"")
        (ranger :variables ranger-show-preview t ranger-show-hidden t ranger-cleanup-eagerly t ranger-cleanup-on-disable t ranger-ignored-extensions
                '("mkv" "flv" "iso" "mp4"))
        (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
        (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak)
        spell-checking
        (syntax-checking :variables syntax-checking-use-original-bitmaps t)
        (treemacs :variables treemacs-indentation 1 treemacs-use-filewatch-mode t treemacs-use-follow-mode t)
        (unicode-fonts :variables unicode-fonts-enable-ligatures t unicode-fonts-ligature-modes
                       '(prog-mode))
        (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
        yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
I am not sure how this should be done, the whole idea behind LSP is to have common functionality behind the same bindings which work like interfaces. The respective implementation of this is entirely done by the respective LSP server implementation which the user can freely choose.

In otherwords if functionality for the help buffer is not as comprehensive as what cider provides this may only be true for the respective server. An alternative one may deliver this function. The same goes for the bindings as they are the same for every mode. This binding `, T s` is simply already taken so we cannot have this overwritten by specific layers without loosing general functionality.

Instead the toggle must be moved to a new binding where it does not conflict with the existing LSP toggles. I would suggest `, T E` for structural editing in case LSP is used.

About cider-doc what about moving it to `, h H` when LSP is installed? This would still allow to have the old functionality available when LSP is used.

For the missing LSP server feature for the help buffer I would suggest to open a PR upstream i.e. the server impl.

**Comment by smile13241324** [comment]
Funny I can't see where `, T s` is bound, does this come from the package itself?

**Comment by jr0cket** [comment]
As LSP has to be the only way for tooling now, the only choice is to add new binding for commands that LSP is replacing

I have tried to avoid upper case bindings but don't have any suggestions at present.  I will have a think about what could be used instead.

**Comment by jr0cket** [comment]
For evil-cleverparens, `, T c` is available and matches the package name.  I suggest this should just be changed regardless of if LSP is running.  This will avoid confusion of having two different key bindings for the same function depending on if LSP is enabled.

I dont think adding a `, h H` key binding when using lsp is useful, its just going to confuse things if there are two different key bindings for the same command.

When someone uses LSP they will have to get used to the changes or not use it (or bind their own shortcuts).

I will raise an issue on lsp, probably lsp ui package, to see if they can add the missing functionality for docs - in that it doesnt follow the file name and open the source.

I guess these things are to be expected in the rush to add LSP when the tooling around it is still quite new.  The only choice for Clojure is to use LSP or not use it, as their is only one implementation.  At least that implementation is getting some much needed work thanks to the Calva team and others.

**Comment by jr0cket** [comment]
It seems the safe structural editing affects numerous languages in Spacemacs, which all use the same key binding as that was always a principle of Spacemacs. 
- racket
- common-lisp
- scheme
- clojure
- emacs-lisp

So I assume the maintainers of all these languages need to agree what to do for the leader T s key binding across all these languages.

You will need to decide if the existing key binding or the new LSP key binding should be kept.  Its a shame the toggles were not put under a leader T l sub menu to avoid clashes

**Comment by lebensterben** [comment]
, T in LSP needs to be reworked. It's not mnemonic even without the issues you mentioned.

**Comment by smile13241324** [comment]
If we have so much layers affected maybe we should move the LSP toggle bindings to a prefix then, moving the LSP toggles to the mentioned prefix of `, T l` for toggles -> lsp may be a good idea.

@lebensterben I am not sure about the non mnemonic thing, conventions also say `T` for `toggles` for major mode specific ones. Whats your suggestion for an alternative binding?

**Comment by lebensterben** [comment]
I mean bindings under `, T`.

**Comment by smile13241324** [comment]
@jr0cket I have moved the LSP toggle bindings from `SPC m T` to `SPC m T l` for `toggle -> lsp` now.

If we have that much affected layers I think the damage we do with insisting on all these layers change their known bindings is higher than the damage we do if we move some rarely used LSP specific toggles to a new prefix. Also `T l` is definitely clearer as this prefix will only hold LSP specific settings and `SPC m T` may contain random mode specific toggles.

**Comment by lebensterben** [comment]
The real issue of LSP comes from lsp-ui in particular (and also some UI features in main lsp-mode package).

There are too many "toggles"  for various UI features, and we haven't added all of them yet.
