### ISSUE TITLE
"No such file or directory, bash.exe: warning: could not find /tmp, please create!" when I start emacs

### ISSUE THREAD

**Issue by ShapelessCat** [syl20bnr/spacemacs#14407]
#### Description :octocat:
When I start my emacs in Windows 10, I see "1 error(s) at startup! spacemacs may not be able to operate properly." and
```
(Spacemacs) Error in dotspacemacs/user-config: Searching for program: No such file or directory, bash.exe: warning: could not find /tmp, please create!
```
I think it has been showing up since last week.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
```
Loading c:/Users/LanJ/.spacemacs...done
Spacemacs is ready.
(Spacemacs) Error in dotspacemacs/user-config: Searching for program: No such file or directory, bash.exe: warning: could not find /tmp, please create!

Loading c:/Users/LanJ/.emacs.d/.cache/recentf...done
Skipping check for new version (reason: dotfile)
Package cl is deprecated
Error running timer ‘global-git-gutter+-mode’: (file-missing "Searching for program" "No such file or directory" "bash.exe: warning: could not find /tmp, please create!")
```

*Expected behaviour:* :heart: :smile:
No error message

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 9ecce8231)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(better-defaults emacs-lisp git helm lsp markdown multiple-cursors org version-control treemacs python java windows-scripts
                 (scala :variable scala-backend 'scala-metals)
                 rust racket erlang elixir)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by alexey0308** [comment]
@ShapelessCat Does creation of the /tmp directory help? like in answers [here](https://stackoverflow.com/a/64010411)?

**Comment by lebensterben** [comment]
@alexey0308 
This is either an upstream bug, or the error message is not precise, because Windows system doesn't have /tmp directory.

**Comment by alexey0308** [comment]
@lebensterben  https://gitforwindows.org/requirements.html
>Parts of Git are implemented in shell script, and Git for Windows runs those scripts via MSYS2's POSIX emulation layer, which in turn is based on the Cygwin POSIX emulation layer.

I do not know, where it actually mounts /tmp in the end, but the link posted is for Windows.

**Comment by lebensterben** [comment]
Does our auto-generated system info distinguish WSL from Windows?
It seems to me WSL is getting wider adoption that many issues are more or less caused by it.

**Comment by alexey0308** [comment]
@lebensterben  WSL is virtualization. I suppose, one would see 'gnu/linux' in system-type there (?).

Here it is native Windows compilation of Emacs, but the first link I attached is about *Git* installation, not Emacs.

**Comment by ShapelessCat** [comment]
> @ShapelessCat Does creation of the /tmp directory help? like in answers [here](https://stackoverflow.com/a/64010411)?

I tried it even before creating this issue, and it doesn't work.

**Comment by alexey0308** [comment]
Are you able to clone anything from github using your git on your machine? Just to document it, if it is actually relevant to Emacs at all?

**Comment by TradDog** [comment]
I can confirm I have the same issue. 

Trad.

**Comment by alexey0308** [comment]
@TradDog it can also be then path problem: Emacs is not able to find executable, because it misses the directory in the PATH environment variable (which also can be modified in the .spacemacs.env file, `SPS e e`)

Can you confirm, that M-: `(executable-find "bash.exe")` outputs nil for you? 

@ShapelessCat @TradDog It might be the path reason, see @duianto [comment](https://github.com/syl20bnr/spacemacs/issues/11728#issuecomment-449561494), namely about keeping .emacs.d under `AppData\Roaming\` path or adding the HOME variable.

**Comment by duianto** [comment]
I'm not seeing the error message.

For me `(executable-find "bash.exe")` returns:
>"c:/tools/cygwin/bin/bash.exe"

Cygwin was downloaded from: https://www.cygwin.com/

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 54e3cc572)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp git helm html markdown multiple-cursors
                 (org :variables org-agenda-files
                      '("c:/Users/username/org/"))
                 shell spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by ShapelessCat** [comment]
@duianto 
Run `(executable-find "bash.exe")`, and I get _C:\Users\username\Programs\cmder\vendor\git-for-windows\bin\bash.exe_.

@alexey0308 @duianto 
When using `HOME` equals "C:/Users/username", I can't find a way to make it work.

When stopping setting `HOME` manually in system environment, and move spacemacs configuration files to _C:\Users\username\AppData\Roaming_, I still can see the same error. Then I tried to comment `version-control` out from the `dotspacemacs-configuration-layers` to remove the package _git-gutter+_, and then uncomment `version-control` and reinstall _git-gutter+_. After then, it works.

Since I see errors when using both settings and I can only resolve that issue in the second setting (for the first setting, I did similar things, but it didn't work), I'm still not clear about WHY. Anyway, at the end it works.

Thanks! @alexey0308 @duianto 

I'll keep this issue open for several days to see if someone else has the same issue, and they know exactly why.

**Comment by alexey0308** [comment]
Hi @ShapelessCat ,

after moving under `AppData\Roaming`, is the output of `executable-find` changed?

**Comment by lebensterben** [comment]
reinstalling a package to fix the problem sounds weird to me...

how did git-gutter+ mess with bash.exe in the first place?

**Comment by TradDog** [comment]
@ShapelessCat  Then I tried to comment version-control out from the dotspacemacs-configuration-layers
Hi, 

nice trick ShapelessCat. Commenting version-control got rid of the error.  

To get the version-control layer to work again, it may have just been a question 
of uncommenting again and trigger re-install as you suggest. 

Now, for full disclosure, I had git intalled through cmder
(https://cmder.net/) in $CMDERROOT/vendor/git-for-windows
I had installed a tmp in all directories I could think of:
- $CMDERROOT/vendor/git-for-windows which seems to be the root ("/") in CMDER
-  ~/tmp
I noticed the mingw64 under $CMDERROOT/vendor/git-for-windows where I also
 installed a tmp for good measure. 

At any rate thanks for the tip. That worked for me. 

Trad

**Comment by ShapelessCat** [comment]
> Hi @ShapelessCat ,
> 
> after moving under `AppData\Roaming`, is the output of `executable-find` changed?

No change.

**Comment by ShapelessCat** [comment]
> reinstalling a package to fix the problem sounds weird to me...
> 
> how did git-gutter+ mess with bash.exe in the first place?

For me, it's sounds weird, too. However, this kind of issues happened several time when I tried to use spacemacs in different computers. Though, not all issues are exactly like this time, reinstall some packages helped me resolve some issues.
