### ISSUE TITLE
Cann't preview latex file.

### ISSUE THREAD

**Issue by stskyblade** [syl20bnr/spacemacs#14419]
I have added latex layer, and I use `SPC m p d preview-document` to preview my .tex file. I think it doesn't work properly. Here is the output:

```
Running `Preview-LaTeX' on `hello' with ``pdflatex  -interaction=nonstopmode -file-line-error \&prv_hello "/AUCTEXINPUT{" hello.tex "}"''
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
LaTeX2e <2020-10-01> patch level 2
L3 programming layer <2020-12-03> xparse <2020-03-03>
CUSTOMISED FORMAT. Preloaded files:
        .
 article.cls    2020/04/10 v1.4m Standard LaTeX document class
  size10.clo    2020/04/10 v1.4m Standard LaTeX file (size option)
        .
(./hello.tex (/usr/share/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def) (./hello.aux) (/home/stskyblade/.spacemacs.d/elpa/develop/auctex-13.0.0/latex/preview.sty (/usr/share/texmf-dist/tex/generic/luatex85/luatex85.sty) (/home/stskyblade/.spacemacs.d/elpa/develop/auctex-13.0.0/latex/prtightpage.def) (/home/stskyblade/.spacemacs.d/elpa/develop/auctex-13.0.0/latex/prauctex.def
No auxiliary output files.


(/home/stskyblade/.spacemacs.d/elpa/develop/auctex-13.0.0/latex/prauctex.cfg)) (/home/stskyblade/.spacemacs.d/elpa/develop/auctex-13.0.0/latex/prfootnotes.def)
Preview: Fontsize 10pt
Preview: PDFoutput 1
) )
No pages of output.
Transcript written on hello.log.

TeX Output finished with nothing to show at Wed Feb 24 19:38:53
LaTeX: LaTeX found no preview images

```

```
# hello.tex
\documentclass{article}
\begin{document}
Hello World!
\end{document}
```

If I run `pdflatex hello.tex` in terminal, it will work and there will be `hello.pdf` in the directory.

**Comment by alexey0308** [comment]
Hi @stskyblade, 

preview function generate images and formulae in the buffer, so one can see the final result just in the buffer.

If you add something like $$e^{-i\pi} = -1$$ and do preview-document, you will see the result **inside** the buffer.
You can toggle it with preview-at-point at a given location.

What you were aiming  is done by latex/build, which is on `, c`.

**Comment by stskyblade** [comment]
Thank you. `preview-document` and `latex/build` do work as you said. 
I have another question: Is there a function or keybinding can build and preview latex file in another buffer? I means that I edit plain text latex file in the left buffer and rendered PDF file will be displayed in the right buffer in real time automatically.

**Comment by lebensterben** [comment]
that's live preview. see layer documentation

**Comment by stskyblade** [comment]
@lebensterben 
Do you mean set `latex-refresh-preview` to `t`? I don't know how to use live preview feature. How can I open a preview buffer of latex file?
`, p d preview-document` only displays formulas in current buffer. `, c latex/build` only create a rendered PDF file.

**Comment by lebensterben** [comment]
> TexLab also supports more sophisticated previewing setup, which is documented here.

https://texlab.netlify.app/docs/installation/previewing

**Comment by stskyblade** [comment]
Thank you.
