### ISSUE TITLE
org-roam-mode not enabled when org-enable-roam-support is set

### ISSUE THREAD

**Issue by real-or-random** [syl20bnr/spacemacs#14411]
#### Description :octocat:
`org-roam-mode` is a global minor mode that hooks into find-file-function to make sure that org-roam files (those in `org-roam-directory`) are recognized as such and then other org-roam related hooks are initialized (e.g., hooks that update the org-roam when doing changes to files). See https://github.com/org-roam/org-roam/commit/8523fb43b46ffc6b76954bb3c5c19bb5748a6e18.

Thus this mode should be enabled when `org-enable-roam-support` is set in the org layer, see also the official instructions in https://github.com/org-roam/org-roam#installation .

Background: I noticed this accidentally: My org-agenda config makes use of some org-roam features, i.e., it uses org-roam functions to format agenda entries. When I open emacs and as a first thing I open the agenda, then this does not work anymore after #14238, which configures autoload for org-agenda. As a workaround, I'm using an explicit `(org-roam-mode)` in my user config.

But note that what I'm reporting is creating issues even without this somewhat special config, see reproduction guide below. 

I don't know enough about package loading to tell whether using autoload is at odds with how `org-roam-mode` is intended to be used upstream... Is it?

#### Reproduction guide :beetle:
 - Enable org layer with `org-enable-roam-support t`
 - Start emacs, and without issuing any other org-roam related commands, visit a file in `org-roam-directory`.
(This is important because if you use for instance `org-roam-find-file` to open the file, then everything will be alright.)

*Observed behaviour:* :eyes: :broken_heart:
 - `org-roam-mode` is disabled

*Expected behaviour:* :heart: :smile:
 - `org-roam-mode` is enabled

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cecc4ef88)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((unicode-fonts :variables unicode-fonts-enable-ligatures t)
 ansible csv html javascript systemd ivy
 (auto-completion :disabled-for org)
 better-defaults emacs-lisp git github markdown
 (org :variables org-enable-github-support t org-enable-roam-support t org-enable-sticky-header t org-want-todo-bindings t)
 deft syntax-checking treemacs
 (latex :variables latex-enable-auto-fill nil)
 bibtex
 (languagetool :variables langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*")
 yaml lua gtags lsp
 (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-lsp-enable-semantic-highlight 'rainbow)
 php python rust shell major-modes)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by smile13241324** [comment]
Looks like an autoload issue again in org-layer, I will take a look tomorrow.

**Comment by smile13241324** [comment]
Should be fixed now, `org` layer will now properly start `org-roam-global-minor-mode` after the package's init face.
This will fully load the package and should also solve your issue with `org-agenda` as the package will already be fully loaded at this point.

Still can you double check @real-or-random?

**Comment by real-or-random** [comment]
> Still can you double check @real-or-random?

Thanks, it's working now. :+1:
