### ISSUE TITLE
new helm window implementation breaks git status

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#1442]
From spacemacs buffer try `SPC g s` - select any git repository. Then the window splits but the cursor is not in magit but in the spacemacs buffer. This is probably helm related since it works with ido / before helm is loaded. It also works from any file that is already in a git repository.

Issue occurs on latest develop but not on master.

**Comment by tuhdo** [comment]
This issue is fixed in this PR: https://github.com/syl20bnr/spacemacs/pull/1428
