### ISSUE TITLE
LSP layer pulls in DAP even when DAP isn't enabled

### ISSUE THREAD

**Issue by ielll** [syl20bnr/spacemacs#14424]
#### Description :octocat:
LSP layer seems to pull in DAP without enabling the DAP layer.

I am interested in this because I want SPC m d b to insert a breakpoint rather than use DAP.

#### Reproduction guide :beetle:
- Start Emacs
Enable the LSP layer.

*Observed behaviour:* :eyes: :broken_heart:
DAP gets enabled as well.

*Expected behaviour:* :heart: :smile:
DAP does not get enabled.

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e4452f9a8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 bibtex csv emacs-lisp
 (ess :variables ess-assign-key "\255")
 git helm html
 (javascript :variables javascript-backend 'lsp)
 (julia :variables julia-backend 'lsp)
 (latex :variables latex-enable-auto-fill nil)
 lsp markdown
 (python :variables python-backend 'lsp python-lsp-server 'pyright lsp-pyright-auto-import-completions nil)
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'vterm)
 shell-scripts syntax-checking
 (version-control :variables version-control-global-margin t version-control-diff-tool 'git-gutter))
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
LSP is not pulling in DAP, however DAP is used in many layers if support for it is included and LSP is active.
Normally if LSP is used and DAP support is available it will be used automatically.

You can disable this for an individual mode by removing the respective mode from `spacemacs--dap-supported-modes` in your `user-config`.

``` elisp
(defun dotspacemacs/user-config ()
  "Configuration for user code:
This function is called at the very end of Spacemacs startup, after layer
configuration.
Put your configuration code here, except for variables that should be set
before packages are loaded."
     (delete 'python-mode spacemacs--dap-supported-modes))
```

**Comment by ielll** [comment]
This fixed it, thank you!
