### ISSUE TITLE
Binding `y` and `Y` in evil-evilified-state-map 

### ISSUE THREAD

**Issue by yyoncho** [syl20bnr/spacemacs#14431]
Is there a reason for not having y/Y bindings in evilified-state?

**Comment by duianto** [comment]
I don't know what the reason was for choosing some and not other keys.

The `evil-evilified-state.el` header says:
https://github.com/syl20bnr/spacemacs/blob/6d8101c20e600c9498398d3a1c412ab5e68f86f4/layers/%2Bdistributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state.el#L28-L41

These possibly useful keys are not bound either: `w`, `b`, `$` and `^`

But they, including `y`, are bound in the evilified visual state.

This seems to be where the evilified keys are defined:
https://github.com/syl20bnr/spacemacs/blob/721765dccb94fc89a51c4d3e4730e311fe70821d/layers/%2Bdistributions/spacemacs-bootstrap/local/evil-evilified-state/evil-evilified-state.el#L174-L194

**Comment by yyoncho** [comment]
Unless someone is against these binding imho they should be added. For me, it is a PITA, e. g. I want to copy something in evilified view-mode and I cant, I have to use a visual selection

**Comment by duianto** [comment]
Agreed, it's surprising when the evil keys don't work as expected.

I'll open a PR, someone might think of other useful keys that should be added.

It would also be useful to be able to apply text objects in visual state,
ex: `vio` for `evil-inner-symbol`

But I'm not quite sure how to bind those.

**Comment by duianto** [comment]
A PR is pending:
[evilified] Add evilified normal keys: yank, navigate #14448

**Comment by duianto** [comment]
`f`, `F`, `t` and `T` were also missing, they are included in the PR.

**Comment by duianto** [comment]
The PR: [evilified] Add evilified normal keys: yank, navigate #14448

broke org-agenda:
Evilified normal keys breaks "t" keabinding in agenda #14484

And probably more modes.
That "solution" was to general.

The PR has been reverted.

Let's add the keys for each specific mode where they are missing.

One instance is the `*Backtrace*` buffer (`debugger-mode`).

You mentioned: `view-mode`
Do you have some reproduce steps, I'm still in `normal` `evil-state` state when I just call: `M-x` `view-mode`

I can't think of any other modes at the moment.

**Comment by duianto** [comment]
The `debugger-mode` already has an evilified section without any bound keys:
https://github.com/syl20bnr/spacemacs/blob/de1425628c51ee6e894f0ceeee053557b0ad24d9/layers/%2Blang/emacs-lisp/packages.el#L82-L83

This seems to work:
```elisp
    :config (evilified-state-evilify-map debugger-mode-map
              :mode debugger-mode
              :bindings
              "$" 'evil-end-of-line
              "^" 'evil-first-non-blank
              "b" 'evil-backward-word-begin
              "B" 'evil-backward-WORD-begin
              "f" 'evil-find-char
              "F" 'evil-find-char-backward
              "gb" 'debugger-frame
              "t" 'evil-find-char-to
              "T" 'evil-find-char-to-backward
              "w" 'evil-forward-word-begin
              "W" 'evil-forward-WORD-begin
              "y" 'evil-yank
              "Y" 'evil-yank-line)))
```

by default `b` is bound to `debugger-frame`, but it might be expected by evil users to be able to jump to the previous word.

The idea to bind it to: `gb` `debugger-frame`
came from [`evil-collection-debug`](https://github.com/emacs-evil/evil-collection/blob/26493597c74a7e574364aa2ca751a1e70ee4e5eb/modes/debug/evil-collection-debug.el#L60)
