### ISSUE TITLE
New binding for `magit-file-dispatch` is confusingly different from `magit-dispatch` binding

### ISSUE THREAD

**Issue by ilyagr** [syl20bnr/spacemacs#14434]
Recent commit https://github.com/syl20bnr/spacemacs/commit/e3434e8635e6c13efd2702d5be2532e3c1faf18f switched the `<SPC> g f d` binding to mean `magit-file-dispatch` instead of `magit-file-diff`. I'm very happy to have a binding for `magit-file-dispatch`. However, now there is a confusing mismatch: `<SPC> g f d` means `magit-file-dispatch`, and `<SPC> g m` means `magit-dispatch`. I think one of the following two things should happen:

a) `<SPC> g f m` should mean `magit-file-dispatch` and `<SPC> g f d` should be restored to mean `magit-file-diff`. I'd prefer this, since `magit-file-diff` is useful.

b) The binding to `magit-dispatch` should change to `<SPC> g d`.

If either of these options look OK, I'm happy to implement it.

**Comment by ilyagr** [comment]
See also https://github.com/syl20bnr/spacemacs/pull/14408 for background. I don't think anyone noticed the mismatch.

**Comment by lebensterben** [comment]
I prefer the first solution.
