### ISSUE TITLE
Update docs regarding exec-path-from-shell

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#14447]
From core-env I can see spacemacs no longer use `exec-path-from-shell` by default

https://github.com/syl20bnr/spacemacs/blob/6d8101c20e600c9498398d3a1c412ab5e68f86f4/core/core-env.el#L79-L81

In below FAQ docs, it still mentioned of using `exec-path-from-shell` etc, I guess that's outdated?

https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-am-i-getting-a-message-about-environment-variables-on-startup

**Comment by dalanicolai** [comment]
Why did you close this? Well, indeed the comment in `core-env.el` is still relevant, but looking at 75f1d915a8be3c5cc9485341d4bbd871a2ca6e82, that section in the FAQ you've linked to is outdated indeed. Can this issue be reopened?
