### ISSUE TITLE
parinfer layer breaks auto-completion

### ISSUE THREAD

**Issue by AltamimiYasser** [syl20bnr/spacemacs#14453]
#### Description :octocat:
parinfer breaks auto-completion

#### Reproduction guide :beetle:
- Start Emacs
- enable auto-completion layer
- enable lisp layer
- enable parinfer

*Observed behaviour:* :eyes: :broken_heart:
no auto-completion pop-up

*Expected behaviour:* :heart: :smile:
completion pop-up to show

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6d8101c20)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-minimum-prefix-length 1 auto-completion-idle-delay 0.0 auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 emacs-lisp git
 (helm :variables helm-enable-auto-resize t)
 (lsp :variables lsp-lens--enable t lsp-headerline-breadcrumb-enable t)
 (markdown :variables markdown-live-preview-engine 'vmd)
 multiple-cursors
 (org :variables org-enable-sticky-header t org-enable-valign t)
 (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/fish")
 (spell-checking :variables enable-flyspell-auto-completion t)
 syntax-checking
 (version-control :variables version-control-diff-side 'left version-control-global-margin t)
 (treemacs :variables treemacs-use-git-mode 'deferred treemacs-use-all-the-icons-theme t)
 (ranger :variables ranger-override-dired 'ranger ranger-show-preview t)
 helpful ibuffer unicode-fonts emoji dtrt-indent spacemacs-defaults spacemacs-editing spacemacs-editing-visual spacemacs-evil)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
How to reproduce this?
It seems fine on my side.

**Comment by AltamimiYasser** [comment]
> How to reproduce this?
> It seems fine on my side.

Hi, thanks for your time!
I just enable the layer and start working on my configs or any lisp code and there is no auto-completion

**Comment by lebensterben** [comment]
@AltamimiYasser 
Does this issue still persist? I'm never able to reproduce this.

BTW, `parinfer-mode` recently is superseded by `parinfer-rust-mode`. Can you upgrade both Spacemacs and all Emacs packages and retry?

**Comment by AltamimiYasser** [comment]
Hello @lebensterben 
I updated Spacemacs sometimes ago and the problem seems to not be present anymore :).

You can close this now if you wish and thanks for your time!
