### ISSUE TITLE
Outlining Errors in Ruby

### ISSUE THREAD

**Issue by jarednorman** [syl20bnr/spacemacs#1445]
With the syntax-checking and ruby layers enabled I'm seeing errors outlined regardless of whether I toggle flycheck off. Is this a bug, or am I mistaken about what's providing this feature?

**Comment by swaroopch** [comment]
Can you please provide steps to reproduce and/or screenshots?

**Comment by jarednorman** [comment]
Enable ruby and syntax-checking layers. If I toggle flycheck off the indicators in the gutter disappear but the red borders on the problems remain.

![flycheckenabled](https://cloud.githubusercontent.com/assets/471667/7419402/ab89aeb8-ef29-11e4-96d4-ad3885e20d69.png)

**Comment by tuhdo** [comment]
@jarednorman That red border is trailing whitespace. If you add a character, it will fade away because it's not trailing anymore.

**Comment by jarednorman** [comment]
I realize this; I meant the borders around the rubocop complaints.

**Comment by syl20bnr** [comment]
@jarednorman Do you have some screenshot with flycheck disabled ?

**Comment by jarednorman** [comment]
I could go grab one but it looks _exactly_ the same except without the circular indicators in the margin.

**Comment by syl20bnr** [comment]
Ok, I guess the underline under the `args` and `end` should be gone too.
Seems that there is already a checker running, so we could disable flycheck or keep flycheck and disable the other one (like in Haskell).

**Comment by robbyoconnor** [comment]
This is not an issue.

**Comment by StreakyCobra** [comment]
I also can't reproduce this one, it has probably been solved in the meantime. @jarednorman In any case, feel free to reopen this one if its not the case, or open a new one if you encounter any other issue :relaxed:
