### ISSUE TITLE
how do I tell when project search is done, i.e., SPC * and SPC / commands?

### ISSUE THREAD

**Issue by emacs18** [syl20bnr/spacemacs#14455]
I use latest develop branch of spacemacs with emacs 27 on CentOS 6.  I have no choice in OS version here, because it is dictated by my company.  I use ubuntu 20.04 on my personal laptop.

I have absolutely no problem when using emacs on my laptop with searches, because all project searches finish in few seconds.
However when I use emacs on CentOS 6 linux server in my company server farm with networked file systems, then `SPC *` or `SPC /` commands to search a project could take over 30 seconds or even over a minute sometimes.

It would be extremely helpful if there was a feedback to let me know that the search is done.
Is there such a feedback already?  If so what is it?
If there is no such feedback, then should this request be made to upstream package owner or not?

Today after hitting `SPC *` or `SPC /` I just sit and wait while the search match count goes up.  Sometimes the count does not update for 10 or more seconds then update.  This could repeat few times. I have no idea whether the search is still going on or whether the search is done.  What I end up doing is to go to a shell buffer and type rg command to see if `SPC /` command reported all the matches or not.  This is very painful way to search for regexps.  All I'm looking for is the search command to print "done" or something like it to let me know that the search has completed.

I tried using both helm and ivy.  Both have the same problem.  One key difference I notice is that if I hit `C-x C-s` during helm searches, then the search stops immediately and only the items currently found are displayed in a buffer.  Ivy is different.  If I hit `C-c C-o` to save the search result to a buffer, then it would seem to hang for about 30 seconds, then a buffer pops up.  My guess is that ivy waits till the search is complete before popping up the search result buffer.

**Comment by lebensterben** [comment]
It's possible there's only grep installed on the server. If you are allowed to install additional softwares you should try to install ripgrep.

**Comment by emacs18** [comment]
I only use ripgrep.

**Comment by lebensterben** [comment]
With helm by design the search is asynchronous and it continuously reports back new matches.

https://github.com/emacsorphanage/helm-ag/blob/db52f860b50aa4d5edfa1c6c97802d36aef7f78b/helm-ag.el#L1217

You probably can try this:

https://github.com/emacs-helm/helm/blob/006c18063ce911acb3b9f89286ca3950a6888dc8/helm.el#L950

**Comment by alexey0308** [comment]
Hi @emacs18, do you mean you mount the file system to your local machine? I am asking, because if you would use tramp, the search would be done on the server (but you have to use the program installed there, i.e. probably grep) and may be run faster. 

Also from helm docs
>Helm grep works with TRAMP (you can grep a file on a remote host or in su/sudo methods), but TRAMP has poor support for multiple processes launched with short delays (< 5 seconds) between them.
>
> Therefore, you should suspend Helm updates with C-! while you write your regexp. Once done, hit again C-! to restart Helm updates. If you don’t, Helm grep should still work, but it will be slow and may result in occasional failures.

It does not solve original issue, but hope it helps.

**Comment by lebensterben** [comment]
Probably you can change helm-ag so that it's registered as a synchronous source, instead of async source, for helm.

**Comment by emacs18** [comment]
What I would like to do is add something like this to be executed when the search is done:
```elisp
(message "Search complete")
```
Where can I add such code?

My emacs is running on a server which has many NFS disks mounted to it.
So tramp is not relevant in my use case since emacs is running on a server with direct access to the disks even if it is slow NFS disks.

**Comment by emacs18** [comment]
@lebensterben I don't know how to register helm source synchronous or not.
Even if this synchronous thing works, if it prevents me from using emacs while the search is going on, then I don't think i would want it.

**Comment by alexey0308** [comment]
@emacs18, if you aim to guard yourself from quitting helm before the search is done, 
one can use a very ad hoc solution:

write a script wrapping your command (in my case it's ag):
```
#/bin/bash

ag "$@"
echo "/dev/null:0 \"------------------DONE---------------------\""
```

and then define a new function, which performs the same command with modified executable path for such cases:
```
(defun helm-with-guard
    (interactive)
  (let ((helm-ag-base-command "bash /home/user/.local/bin/ag-new.sh --nocolor --nogroup"))
    (helm-do-ag)))
```
It is not elegant, it would be better if one could find a hook function in the large helm code base.

**Comment by lebensterben** [comment]
I'm thinking maybe you should ask the author of helm-ag for help.

Some visual differences for ongoing/complete search is useful for use cases like yours.

**Comment by emacs18** [comment]
As far as I can tell, what I'm looking for seems to be already available, e.g., `helm-ag-show-status-function`.  This is used within spaceline package.  Just search for "helm-done" in that package.  It appears that "(DONE)" is supposed to pop up within the mode line, but why does it not?

**Comment by alexey0308** [comment]
It looks like a function call was removed [here](https://github.com/emacsorphanage/helm-ag/commit/29d633643d1bb324a7c578aafa2b9caac3070043), 1114-1115 lines.

**Comment by emacs18** [comment]
@alexey0308 Thanks.  I restored the removed code via this patch
```diff
diff --git a/helm-ag.el b/helm-ag.el
index 8952c04..a0b069b 100644
--- a/helm-ag.el
+++ b/helm-ag.el
@@ -1135,7 +1135,9 @@ Continue searching the parent directory? "))
            proc
            (lambda (process event)
              (helm-process-deferred-sentinel-hook
-              process event (helm-default-directory)))))))))
+              process event (helm-default-directory))
+             (when (string= event "finished\n")
+               (helm-ag--do-ag-propertize helm-input)))))))))
 
 (defconst helm-do-ag--help-message
   "\n* Helm Do Ag\n
```

This worked in that when the search was done, "(DONE)" was added to modeline.

**Comment by emacs18** [comment]
@alexey0308 If you don't get around to submitting a PR to `helm-ag` project, then I may do it later today.
Thanks again.

**Comment by alexey0308** [comment]
> @alexey0308 If you don't get around to submitting a PR to `helm-ag` project, then I may do it later today.
> Thanks again.

I'm glad it helped, the PR is yours :)

**Comment by emacs18** [comment]
The fix was checked into `helm-ag` package via https://github.com/emacsorphanage/helm-ag/commit/51e164b4bb1a9826fe8b39c0d02b4064c9352b9f
