### ISSUE TITLE
What's up with dired (fix docs, evilify)?

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#14467]
I'm not sure if I should open this here or in the github discussions section, but anyway I was wondering why dired seems to be neglected in Spacemacs. I can not find any (official) documentation about how to use dired in Spacemacs.

I was just trying to use it, so I pressed `?` to get some help (like in vanilla Emacs). But that does not seem to work in Spacemacs evil state. Therefore I think at least dired state should open in evilified state.

So I don't know why there is no documentation at all about dired. Probably it is because it is recommended to use either treemacs, or the ranger or vinegar layer (which does evilify dired mode). But then these recommendations should be documented.

I am happy to implement some basic fixes (i.e. evilify the mode and add the recommendations to the doc), but it would be great if somebody either give green light, or otherwise maybe shortly comment/motivate on why the situation is like this (I could not find the any info/motivation within a reasonable time).

**Comment by alexey0308** [comment]
Hi Daniel, 

> I am happy to implement some basic fixes (i.e. evilify the mode and add the recommendations to the doc), but it would be great if somebody either give green light, or otherwise maybe shortly comment/motivate on why the situation is like this (I could not find the any info/motivation within a reasonable time).

it is evilified by evil-collection already, `g ?` gives `dired-summary`. Is dired not in `evil-collection-mode-list` by you?

**Comment by smile13241324** [comment]
I think dired is not documented as its an emacs main package. It is evilified though, I am using it a lot and also prefer it before the tree based solutions. I am not sure if we can fix the behaviour in the mode specific help though, its mainly the same behaviour as in info mode i.e. standard emacs help without evil bindings.

I think it would be useful to have a section of the main documentation dedicated to these plain old emacs modes (dired, info) to make the way these packages work more clear to users not having an emacs background. Still they should provide links to understand how to obtain more information via the emacs way which for dired and info mode is the only reliable thing to do.

About evil-collection this is not part of the documentation for its rather an implementational change. This package is far from perfect but it is a standard evilify implementation for general emacs which we started to use after some main packages did move to it. For now we still prefer our own solution for it is more flexible but replace it gradually where evil-collection does the trick or is just used by upstream.

As to the preferance of one mode before the other, no we definitely do not prefer ranger over dired. We do prefer treemacs over neotree however again this is a pure choice of flavour, i.e. complex and feature complete vs fast and simple. We see the first as the sensible default for unexperienced users but still want to support the second use-case i.e. helm vs ivy vs spacemacs-base distribution.

So to cut a long story short, yes we should provide some introduction into these packages in our docs to help users without an emacs or tech background to help to understand these modes. PRs would be welcome.

**Comment by lebensterben** [comment]
I enabled `treemacs` layer as my file tree implementation, but to be honest I've never used it often.

I mostly relied on `helm` for navigation, and occasionally use `dired` (usually because I accidentally pressed enter in minibuffer and it opens the dired buffer for a directory).

I've never used file management capability of either `treemacs` or `dired`. The reason is I'm already very proficient with shell, and I haven't found any good tutorials for file management in `treemacs` or `dired` (with evilfied key-bindings).

I believe this, namely transition cost, is also one reason why many people never bothered to ask for better documentation for `dired` (or `treemacs`). But this certainly could be very important for new users.

**Comment by dalanicolai** [comment]
I have created a sensible evilified [info layer](https://github.com/abo-abo/hydra/wiki/Info), which implements the [example hydra-info](https://github.com/abo-abo/hydra/wiki/Info) adapted to Spacemacs. It would be great if one of you could check it out. Just clone the repo to your private dir (but rename the dir from 'info-layer' to 'info'), and add `info` to the layer list in your dotfile.
Then open some info buffer and press `?` once to open the hydra. Here is a screenshot:
![image](https://user-images.githubusercontent.com/18429791/111232662-dc042500-85eb-11eb-9438-c4e3a90237bf.png)

I did not bind `history back/forward` to `C-o/i` because this history is 'local' (only for Info-mode), and I preserved the `C-o/i` bindings for the global `evil-jump-back/forward` (some very minor detail, we do use `C-o/i` for scrolling the local history in `pdf-tools`, but I think this inconsistency very acceptable).

Although I do like the `evil-collection` initiative, indeed, I think that generally, I prefer the Spacemacs way of configuration. MAYBE this layer has little less consistent keybindings, but I think it is consistent where it should be and the documentation (hydra) is much more important/useful.

I did not create a PR for this yet, because I don't know if/how you prefer to implement this (personally of course, I think it is a great improvement). So it would be great if you could provide some feedback. For example, I know Spacemacs defines its own `spacemacs|define-transient-state` but I just wanted to implement it in a straightforward way for now (by using abo abo's installation instructions. I could probably quickly change it to use the `spacemacs|define-transient-state`, which looks better of course). Also, maybe you have some opinion about if this should be added as a layer, or in the core.

There is also an example [hydra-dired](https://github.com/abo-abo/hydra/wiki/Dired). If you like this info layer, then I could also adapt the dired hydra to Spacemacs when I have the time. Again, I probably prefer to revert dired-mode to the Spacemacs way of configuration (so remove the evil-collection bindings). The evilified bindings are already consistent, and the extra bindings are mode specific (e.g. copy, delete etc. in dired mode, and top,index etc info-mode) and I prefer to keep them consistent by sensible 'balancing' between evil and vanilla emacs bindings (as you will see in the info-layer).

@smile13241324 I think this hydra does a very good job in documenting `Info-mode`. So I can update the Spacemacs docs (to add info about pressing `?` (or maybe `, .`)) after I know your opinions about implementation.

**Comment by lebensterben** [comment]
@dalanicolai 

I think it's evilified now. What are the other features you still want for dired?
