### ISSUE TITLE
latex mode: `SPC m b` is undefined

### ISSUE THREAD

**Issue by pvazteixeira** [syl20bnr/spacemacs#14464]
#### Description :octocat:
`SPC m b` is undefined under latex mode

#### Reproduction guide :beetle:
- Start Emacs
- open tex file
- build it  

*Observed behaviour:* :eyes: :broken_heart:
_`SPC m b` is undefined_ message

*Expected behaviour:* :heart: :smile:
`SPC m b` runs the build command

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. de55a45db)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(octave html yaml javascript bibtex
        (c-c++ :variables c-c++-backend 'lsp-clangd c-c++-lsp-enable-semantic-highlight 'rainbow c-c++-enable-google-style t c-c++-adopt-subprojects t)
        (cmake :variables cmake-backend 'lsp)
        emacs-lisp git helm
        (julia :variables julia-backend 'lsp)
        (latex)
        lsp markdown
        (org :variables org-want-todo-bindings t)
        python syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
most likely TexLab is not found so LSP isn't in used.

**Comment by alexey0308** [comment]
Hi Pedro @pvazteixeira , you added lsp mode to the layers: it results in build command moved to `SPC m c`.

**Comment by pvazteixeira** [comment]
@alexey0308  thanks, that's it! I had been using `SPC m b` for a long time; going through the layer documentation `SPC m c` only shows up in the keybinding list - maybe it could be added to the section under build command?

@lebensterben in that case shouldn't `, b` bring up the 'menu'?

**Comment by alexey0308** [comment]
> @alexey0308 thanks, that's it! I had been using `SPC m b` for a long time; going through the layer documentation `SPC m c` only shows up in the keybinding list - maybe it could be added to the section under build command?
> 
I think, that it is better to keep keybindings in one place in general. Otherwise one needs to keep track about all the references to the given key in the help page.
Maybe it is worth to better emphasize that with lsp in the layers, it will be the default backend, which was exactly your case. You are welcome to make a PR in any case :)
