### ISSUE TITLE
[parinfer layer] 'parinfer-mode' package is not on MELPA anymore: please replace it with 'parinfer-rust-mode'

### ISSUE THREAD

**Issue by allentiak** [syl20bnr/spacemacs#14460]
Currently, the parinfer layer points to a broken implementation:
https://github.com/DogLooksGood/parinfer-mode

As pointed out by @DogLooksGood that implementation should be replaced by its spiritual successor:
https://github.com/justinbarclay/parinfer-rust-mode

**Comment by lebensterben** [comment]
It should not be simply replaced by `parinfer-rust-mode`, because that requires the `parinfer-rust` library and will be a breaking change.

Users should be given an option to choose which one of them to use.

**Comment by allentiak** [comment]
Whereas I understand your rationale, I forgot to add something very important: **`parinfer` is no longer on MELPA**. And its repo has been archived by the owner.

As I said, it's dead...

**Comment by allentiak** [comment]
Plus, there are other layers that install libraries (e.g. the `java` layer installs `meghanada`...).

**Comment by lebensterben** [comment]
@allentiak 
> Plus, there are other layers that install libraries (e.g. the java layer installs meghanada...).

I'm not denying that there are a few packages that install 3rd-party packages/libraries. The one thing I wish we could avoid, even for `develop` branch, is to avoid breaking changes.

Breaking changes can be frustrating for non-heavy users. At minimum, to replace `parinfer-mode` by `parinfer-rust-mode`, we need:
- Document the external dependency.
- Display an error (via `user-error` for example), if `parinfer-rust` is not found.

**Comment by allentiak** [comment]
Again, I think you haven't read what I wrote...
Have you tried installing `parinfer` from MELPA *today*? It's **gone**...

**Comment by allentiak** [comment]
What you propose would apply if `parinfer` was still there. (But it's not!)

**Comment by lebensterben** [comment]
For people already have `parinfer` enabled, `parinfer` will not disappear. And if you simply replaced it by `parinfer-rust`, and if they don't have the library installed, it's a breaking change.

I think I've described it very clear.

**Comment by allentiak** [comment]
@duianto @smile13241324 What do you think about this?

**Comment by duianto** [comment]
Confirmed.
>Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: parinfer@parinfer... [1/1]
Package parinfer is unavailable. Is the package name misspelled?

I don't know how this should be solved, but I have informed the maintainers.

**Comment by smile13241324** [comment]
@allentiak thanks for the information, I will checkout this new parinfer package.

**Comment by allentiak** [comment]
@smile13241324 You're welcome!
I had to switch to that package after I received the same message as @duianto ...

**Comment by smile13241324** [comment]
This new `Parinfer` implementation is really good, especially its a lot faster then the old package, due to most of the work is delegated to a native library in the background. I'd wish I would see more packages move into this direction.

The `Parinfer layer` has been refactored to use `parinfer-rust-mode` now. The package will silently install/update the necessary libraries in the background. They will be stored in our `cache` folder. The documentation gives some short remarks about the new native library and links to the new package repo for details.

**Comment by allentiak** [comment]
Awesome! Thanks for your hard work, @smile13241324 !

**Comment by allentiak** [comment]
BTW: After https://github.com/syl20bnr/spacemacs/commit/de55a45dbd46516cf17846f669f80a41f77c4ab4, if I add the newly refactored layer without any parameters (as stated [in the commit itself](https://github.com/syl20bnr/spacemacs/commit/de55a45dbd46516cf17846f669f80a41f77c4ab4)), I get the following error:

```
Error (use-package): parinfer-rust-mode/:init: Wrong number of arguments: setq, 5
```

**Comment by duianto** [comment]
@allentiak The `spacemacs|add-toggle` ended up in the combined `setq` above.

It's been fixed.
[parinfer] Fix: Wrong number of arguments: setq, 5 https://github.com/syl20bnr/spacemacs/commit/b7cbcb5ed5741fbe289a99efaed0350812ed85ad

**Comment by allentiak** [comment]
@smile13241324 @duianto

Thanks! Now it works.

Closing...
