### ISSUE TITLE
LatexMk build option doesn't appear until after configuration refresh

### ISSUE THREAD

**Issue by nmoroze** [syl20bnr/spacemacs#14461]
Hi, 

I've been having an issue with my Spacemacs Latex configuration -- I want to use Latexmk for building documents, and if I start Emacs, open a Latex document, and do `C-c C-c`, LatexMk doesn't appear as an option. However, if I reload my configuration with `SPC-f-e-R`, then LatexMk does show up as an option and I can build my document from within Emacs.

I've added the Latex layer to my .spacemacs like so:
```
     (latex :variables
            latex-backend 'lsp ; requires installing texlab
                               ; (https://texlab.netlify.app/, brew install texlab)
            latex-build-command "LatexMk")
     )
```

If it helps, I'm using GNU Emacs 27.1 and spacemacs 0.200.13. 

Thanks in advance for any help!

**Comment by lebensterben** [comment]
> `0.200.13`

Doesn't look right. Stable branch doesn't have LSP AFAIK.

**Comment by nmoroze** [comment]
I double-checked the version, and it looks right (`SPC-f-e-v` gives `Spacemacs v.0.200.13`). I removed the `latex-backend` setting in my configuration, but the problem still persists.

**Comment by lebensterben** [comment]
Just use the develop branch.
