### ISSUE TITLE
issue with ocaml layer?

### ISSUE THREAD

**Issue by qcfu-bu** [syl20bnr/spacemacs#14469]
Expected behavior: 
Enable ocaml, autocompletetion, and syntax-check layers in .spacemacs, get autocompletetion and syntax checking when editing .ml files. Opam, Merlin, Ocp-indent, utop, etc. are all installed and configured in .zshenv.

Actual behavior:
Syntax highlighting for .ml files work, but autocompletetion and syntax-checking do not. When manually browsing flycheck backends, neither merlin nor ocaml-flycheck show up.

Emacs verion 28.0.5, non-native compile.

**Comment by lebensterben** [comment]
you at least need helm/ivy layer.

**Comment by qcfu-bu** [comment]
Yes, I have helm installed

**Comment by qcfu-bu** [comment]
When opening .ml files, I get this message in the message buffer
```
Eager macro-expansion failure: (wrong-type-argument listp [(first-item . rest-items) (sp-get-list-items)])
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
File mode specification error: (wrong-number-of-arguments (3 . 4) 2)
Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 2) [2 times]
File mode specification error: (wrong-number-of-arguments (3 . 4) 2)
```

**Comment by qcfu-bu** [comment]
Interestingly, emacs 27.1 seems to work fine.

**Comment by lebensterben** [comment]
I do see the same error
`Eager macro-expansion failure: (wrong-type-argument listp [(first-item . rest-items) (sp-get-list-items)])`

I'm on 27.1 and yes OCAML works fine. So the thing is to figure out what's broken.

**Comment by dimitarvp** [comment]
I am on Emacs 27.2 and even though I experience no loss of functionality anywhere (as far as I can tell) this warning still pops up on startup -- it's a recent occurrence so I'd guess my often updating of Spacemacs pulled something in.

**Comment by lebensterben** [comment]
@dimitarvp 
Fixed in upstream https://github.com/Fuco1/smartparens/pull/1079
