### ISSUE TITLE
org-mode causes emacs 27 to freeze

### ISSUE THREAD

**Issue by wnkw** [syl20bnr/spacemacs#14462]
#### Description :octocat:
After upgrading to 27.1 Emacs hangs when opening an org-mode file.

#### Reproduction guide :beetle:
- Start Emacs
- Open an org-mode file with a bit of structure in it. Eg. a layer documentation.

*Observed behaviour:* :eyes: :broken_heart:
Emacs hangs and has to be killed.

*Expected behaviour:* :heart: :smile:
Org-mode should be usable.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 721765dcc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-complete-with-key-sequence "jk" auto-completion-enable-snippets-in-popup t)
 better-defaults bibtex common-lisp csv dash deft emacs-lisp
 (ess :variables ess-assign-key "\255")
 git haskell helm html ibuffer javascript latex markdown nixos org pandoc pdf python spell-checking syntax-checking
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
 treemacs yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Try:
First upgrade all packages. Second nuke .emacs.d/elpa directory.

**Comment by wnkw** [comment]
Thanks for the quick reply. This doesn't help unfortunately. I also removed emacs.d/.cache, upgraded to the latest revision, and removed all my org-mode related settings from the .spacemacs file. Emacs still freezes when opening an org file or reading documentation.

**Comment by lebensterben** [comment]
Is that a particular org file or any org file?
If it's a particular one, does that have uncommon features comparing to others?

**Comment by wnkw** [comment]
Any which is more complex than just a single heading. I test if this works by pressing `spc h l` and opening the org mode layer documentation (but I also tried opening some of my agenda files). This file actually opens but usually emacs freezes when scroll down a bit.

**Comment by lebensterben** [comment]
If that file has tables then you can try to disable valign.

**Comment by wnkw** [comment]
Thanks for your help. I don't think it's related to tables because in the other files I don't have any tables. I'll try to come up with a minimal file for which it hangs, but so far I am quite frustrated with it so I switched back to 26. I'll deal with this when I'll have the time.

**Comment by emacs18** [comment]
Did you try to get a stack trace?  I mean
- do `(setq debug-on-quit t)` before opening the org file
- open the org file
- Hit `Control-g` when it hangs

This should print stack trace.  If this does not work, then other things that you can try to narrow down the cause of your problem include
- `(setq org-mode-hook nil)` to see if any of the hooks are causing the problem
- use `edebug-defun` to instrument `org-mode` for single stepping with the debugger

**Comment by wnkw** [comment]
Thanks @emacs18 for the tips, very instructive. I didn't know you can get stack trace like that.
I managed to single out the problem with my agenda files by disabling org hooks. It looks like it was caused by org-superstar package, adding it to the excluded packages seems to "solve" (I liked my pretty bullets) the problem.

But emacs still freezes when I'm reading layer documentation, particularly org-mode layer documentation (the file `$HOME/.emacs.d/layers/+emacs/org/README.org`) this happens around line 300 which I believe is related to the superstar bullets chars, since on my screen scrolling down more would show "different bullets" section with those chars in them.
What could cause this? Fonts issues? I believe 27 changed something with how emacs renders fonts? I post the stacktrace below but I don't think it's telling much (these are two different traces from the same file).

```
Debugger entered--Lisp error: (quit)
  vertical-motion(1)
  line-move-1(1 nil)
  line-move(1 nil nil nil)
  next-line(1)
  evil-line-move(1)
  evil-next-line(nil)
  funcall-interactively(evil-next-line nil)
  call-interactively(evil-next-line nil nil)
  command-execute(evil-next-line)

Debugger entered--Lisp error: (quit)
  redisplay_internal\ \(C\ function\)()
```

**Comment by emacs18** [comment]
I use `org-superstar-mode` as well, but I do not have any problem. Perhaps you can try different theme, e.g., following is what I have in my `.spacemacs` file.

```elisp
   dotspacemacs-themes '(modus-operandi
                         modus-vivendi
                         spacemacs-light
                         spacemacs-dark)
```

**Comment by wnkw** [comment]
Unfortunately this doesn't help. I also tried disabling doom mode-line but without success.

**Comment by wnkw** [comment]
So I tried running vanilla emacs 27.1 with org superstar and the issue also occurs on vanilla. I'll report upstream. It has to be something specific to my setup but apparently more people experience this (or something similar) as can be seen in the doom emacs thread.

**Comment by lebensterben** [comment]
Just attach you .spacemacs here

**Comment by wnkw** [comment]
@lebensterben Thanks but it turned out to be a font problem. I use source code pro and on 27.1 emacs did a lot of work to render the glyphs which weren't available in the font. In 26 it would just omit them. The issue was solved by using the package unicode-fonts and following the guide: https://github.com/rolandwalker/unicode-fonts
