### ISSUE TITLE
Eager macro-expansion failure/ smartparens issue

### ISSUE THREAD

**Issue by jasontuna** [syl20bnr/spacemacs#14478]
#### Description :octocat:
Eager macro-expansion failure/ smartparens issue

#### Reproduction guide :beetle:
- Fresh install with no .spacemacs
- Start Emacs
- Shutdown Emacs
- Start Emacs and open .spacemacs file, through SPC ff, or file tree

I have tried with the development and non-development version of spacemacs. 
I have also tried with emacs-28.0.

*Observed behaviour:* :eyes: :broken_heart:
Eager macro-expansion failure: (wrong-type-argument listp [(first-item . rest-items) (sp-get-list-items)])
is output in the Messages buffer
and when a hook is added to the error I get the following output

Debugger entered--Lisp error: "Eager macro-expansion failure: (wrong-type-argumen..."
  message("Eager macro-expansion failure: %S" (wrong-type-argument listp [(first-item . rest-items) (sp-get-list-items)]))
  internal-macroexpand-for-load((defalias 'sp-split-sexp #'(lambda (arg) "Split the list or string the point is on into two...." (interactive "P") (cond ((equal arg '...) (-when-let [... ...] (sp-get first-item ...))) (t (let (...) (-when-let ... ...)))))) t)
  eval-buffer(#<buffer  *load*> nil "/home/jtuna/.emacs.d/elpa/27.1/develop/smartparens..." nil t)  ; Reading at buffer position 342020
  load-with-code-conversion("/home/jtuna/.emacs.d/elpa/27.1/develop/smartparens..." "/home/jtuna/.emacs.d/elpa/27.1/develop/smartparens..." nil t)
  smartparens-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook emacs-lisp-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook emacs-lisp-mode-hook))
  run-mode-hooks(emacs-lisp-mode-hook)
  emacs-lisp-mode()
  set-auto-mode-0(emacs-lisp-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer .spacemacs> "~/.spacemacs" nil nil "~/.spacemacs" (150870 66307))
  find-file-noselect("/home/jtuna/.spacemacs" nil nil nil)
  find-file("/home/jtuna/.spacemacs")
  dired-find-file()
  funcall-interactively(dired-find-file)
  call-interactively(dired-find-file nil nil)
  command-execute(dired-find-file)

*Expected behaviour:* :heart: :smile:
No errors.
I am unable to disable smartparens through methods mentioned in other discussions.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b7cbcb5ed)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: "Eager macro-expansion failure: (wrong-type-argumen..."
  message("Eager macro-expansion failure: %S" (wrong-type-argument listp [(first-item . rest-items) (sp-get-list-items)]))
  internal-macroexpand-for-load((defalias 'sp-split-sexp #'(lambda (arg) "Split the list or string the point is on into two...." (interactive "P") (cond ((equal arg '...) (-when-let [... ...] (sp-get first-item ...))) (t (let (...) (-when-let ... ...)))))) t)
  eval-buffer(#<buffer  *load*> nil "/home/jtuna/.emacs.d/elpa/27.1/develop/smartparens..." nil t)  ; Reading at buffer position 342020
  load-with-code-conversion("/home/jtuna/.emacs.d/elpa/27.1/develop/smartparens..." "/home/jtuna/.emacs.d/elpa/27.1/develop/smartparens..." nil t)
  smartparens-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook emacs-lisp-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook emacs-lisp-mode-hook))
  run-mode-hooks(emacs-lisp-mode-hook)
  emacs-lisp-
```
Thanks!!!!!

**Comment by duianto** [comment]
There's a pending PR upstream with a fix:
Fix [#1077](https://github.com/Fuco1/smartparens/issues/1077) by sirikid · Pull Request https://github.com/Fuco1/smartparens/pull/1079

**Comment by jasontuna** [comment]
Cool thanks!

After I posted the issue, I added the below to disable;

dotspacemacs-excluded-packages '(evil-lisp-state smartparens)

and 

(remove-hook 'comint-mode-hook 'smartparens-mode)
(remove-hook 'prog-mode-hook 'smartparens-mode)
(remove-hook 'minibuffer-setup-hook 'spacemacs//conditionally-enable-smartparens-mode)
(remove-hook 'emacs-lisp-mode-hook 'smartparens-mode)
(remove-hook 'change-major-mode-after-body-hook 'smartparens-mode)
(remove-hook 'emacs-lisp-mode-hook 'smartparens-mode)
(remove-hook 'evil-lisp-state-entry-hook  'smartparens-mode)

and so far, smartparens has not been called.

**Comment by emacs18** [comment]
I disabled smartparens completely several years ago via this change on my fork of spacemacs.

```diff
diff --git a/layers/+spacemacs/spacemacs-editing/packages.el b/layers/+spacemacs/spacemacs-editing/packages.el
index 836280190..438726212 100644
--- a/layers/+spacemacs/spacemacs-editing/packages.el
+++ b/layers/+spacemacs/spacemacs-editing/packages.el
@@ -377,7 +377,9 @@
     "xrpx" 'rxt-pcre-to-rx))
 
 (defun spacemacs-editing/init-smartparens ()
-  (use-package smartparens
+  ;; Completely disable smartparens which cause too much grief.
+  ;; https://github.com/syl20bnr/spacemacs/issues/12533
+  '(use-package smartparens
     :defer t
     :commands (sp-split-sexp sp-newline sp-up-sexp)
     :init
```

**Comment by emacs18** [comment]
Would something like this allow me to disable smartparens by setting a variable?

```diff
diff --git a/core/core-dotspacemacs.el b/core/core-dotspacemacs.el
index 73edb370f..94f3f4d5f 100644
--- a/core/core-dotspacemacs.el
+++ b/core/core-dotspacemacs.el
@@ -470,6 +470,9 @@ prettifying Org files.")
   "If non-nil, `kill-buffer' on *scratch* buffer
 will bury it instead of killing.")
 
+(defvar dotspacemacs-enable-smartparens t
+  "Enable use of smartparens package if `non-nil'.")
+
 (defvar dotspacemacs-byte-compile nil
   "If non-nil, byte-compile some of Spacemacs files.")
 
diff --git a/layers/+spacemacs/spacemacs-editing/packages.el b/layers/+spacemacs/spacemacs-editing/packages.el
index 438726212..9f15159db 100644
--- a/layers/+spacemacs/spacemacs-editing/packages.el
+++ b/layers/+spacemacs/spacemacs-editing/packages.el
@@ -27,7 +27,7 @@
         password-generator
         (persistent-scratch :toggle dotspacemacs-scratch-buffer-persistent)
         pcre2el
-        smartparens
+        (smartparens :toggle dotspacemacs-enable-smartparens)
         (evil-swap-keys :toggle dotspacemacs-swap-number-row)
         (spacemacs-whitespace-cleanup :location local)
         string-edit
```

**Comment by duianto** [comment]
@emacs18 Thanks for the suggestion.

@smile13241324 Just talked about adding a way to disable it from the dotfile.
https://github.com/syl20bnr/spacemacs/issues/12533#issuecomment-798872730

Your suggestion might be, or at least help with finding a solution.

**Comment by duianto** [comment]
A `dotspacemacs-activate-smartparens-mode` variable has been added:
Allow disabling smartparens in dotfile https://github.com/syl20bnr/spacemacs/commit/7d2ff48d77a1591d6ac91a5cb321f9e7371af15d

After pulling the latest develop branch.
The variable can be added to `.spacemacs` using `ediff`, 
- Press `SPC f e D` to compare the user `.spacemacs` to the `.spacemacs.template`
- `n` navigates to the next difference (`p` to the previous).
- press: `b` to copy the difference from the template in the right column (B), to `.spacemacs` in the left column (A).
if a difference was copied by mistake, then the previous difference in the left column (A) can be restored with `ra`
- `q` quits from the ediff session.

It's also possible to edit the `.spacemacs` (left column) directly while the ediff session is active.
Just remember to select the bottom `*Ediff Control Panel*` window to be able to use the ediff session keys again.
`!` updates the differences when a buffer has been edited manually.

**Comment by Fuco1** [comment]
I just merged a patch to fix this to main in SP repo.  Should build in a couple hours on MELPA.

**Comment by duianto** [comment]
Thanks.
