### ISSUE TITLE
clojure layer clj-refactor support adds an unqualified dependency, which is deprecated in deps.edn

### ISSUE THREAD

**Issue by lvh** [syl20bnr/spacemacs#14475]
#### Description :octocat:

The clojure layer's optional clj-refactor support injects the `clj-refactor`
dependency as an unqualifed dependency, which produces warnings with recent
versions of the deps.edn/clj tooling and will break at some point in the future.

#### Reproduction guide :beetle:

With the following layer configuration:

```
(clojure :variables clojure-enable-clj-refactor t)
```

- Start Emacs
- Go to a Clojure project with deps.edn
- Run `cider-jack-in`/`sesman-start` (<kbd>, '</kbd>)

*Observed behaviour:* :eyes: :broken_heart:

See the following warning in `*Messages*`:

```
error in process sentinel: Could not start nREPL server: DEPRECATED: Libs must be qualified, change refactor-nrepl => refactor-nrepl/refactor-nrepl
```

*Expected behaviour:* :heart: :smile:

No warning and threat of future breakage :)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b7cbcb5ed)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(windows-scripts rust typescript html go graphviz yaml javascript auto-completion better-defaults emacs-lisp git github helm multiple-cursors treemacs colors themes-megapack emacs-lisp markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control
                 (python :variables python-formatter 'black python-format-on-save t python-sort-imports-on-save t)
                 (clojure :variables clojure-enable-clj-refactor t clojure-enable-linters 'clj-kondo)
                 java terraform docker c-c++ gtags pdf plantuml graphql floobits fasd speed-reading)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by smile13241324** [comment]
This is an issue in the package, I will make a PR to clj-refactor.

**Comment by smile13241324** [comment]
I have opened a PR upstream, maybe you could have a quick look at my PR and have a short test with it @lvh. It can be found https://github.com/clojure-emacs/clj-refactor.el/pull/484

**Comment by yenda** [comment]
It was merged :+1:
