### ISSUE TITLE
Emacs hangs when started in daemon mode

### ISSUE THREAD

**Issue by codetrick** [syl20bnr/spacemacs#14477]
#### Description :octocat:

Emacs hangs when started in daemon mode when org-mode with `org-enable-roam-support` enabled. Emacs starts fine in standalone mode. I think the problem started in commit cf82ac2ed for me.

I don't know much about the emacs startup process. However I find it curious that the observed behavior below has lines for my custom config files that I put in `dotspacemacs/user-config`, but not in the expected behavior, which is run from commit b7cbcb5ed.

#### Reproduction guide :beetle:
- Add `(org :variables org-enable-roam-support t)` to `dotspacemacs-configuration-layers`
- Start Emacs with `emacs --daemon`
- The process does not return control to the shell, and `emacsclient -c` fails to connect.

*Observed behaviour:* :eyes: :broken_heart:

The emacs daemon process prints:

```
Warning: due to a long standing Gtk+ bug
https://gitlab.gnome.org/GNOME/gtk/issues/221
Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
Loading /home/codetrick/.spacemacs.d/init.el (source)...
Loading /home/codetrick/.spacemacs.d/init.el (source)...done
Loading /home/codetrick/.spacemacs.d/mu4e-conf.el (source)...
Loading /home/codetrick/.spacemacs.d/mu4e-conf.el (source)...done
Loading /home/codetrick/.spacemacs.d/org-conf.el (source)...
Loading /home/codetrick/.spacemacs.d/org-conf.el (source)...done
Loading /home/codetrick/.spacemacs.d/org-roam-conf.el (source)...
Loading /home/codetrick/.spacemacs.d/org-roam-conf.el (source)...done
Loading /home/codetrick/.spacemacs.d/org-noter-conf.el (source)...
Loading /home/codetrick/.spacemacs.d/org-noter-conf.el (source)...done
Loading /home/codetrick/.spacemacs.d/zotxt-conf.el (source)...
Loading /home/codetrick/.spacemacs.d/zotxt-conf.el (source)...done
Loading /home/codetrick/.emacs.d/.cache/recentf...
Loading /home/codetrick/.emacs.d/.cache/recentf...done
Skipping check for new version (reason: dotfile)
Package cl is deprecated

```

*Expected behaviour:* :heart: :smile:

```
Warning: due to a long standing Gtk+ bug
https://gitlab.gnome.org/GNOME/gtk/issues/221
Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
Loading /home/codetrick/.spacemacs.d/init.el (source)...
Loading /home/codetrick/.spacemacs.d/init.el (source)...done
Spacemacs is ready.
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. cf82ac2ed)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(asciidoc
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t)
 (spacemacs-org :variables org-enable-valign nil)
 multiple-cursors
 (ivy :variables ivy-enable-advanced-buffer-information t)
 (auto-completion :variables auto-completion-idle-delay nil)
 git bibtex latex
 (mu4e :variables mu4e-org-link-support t mu4e-org-compose-support t)
 pdf finance pass
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 (org :packages
      (not org-brain)
      :variables org-enable-roam-support t org-enable-org-journal-support t)
 my-org-roam
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking emacs-lisp
 (python :variables python-backend 'anaconda)
 julia javascript html clojure rust
 (plantuml :variables plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar" org-plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar")
 markdown)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by DCPRevere** [comment]
The same is happening for me, even without running emacs in daemon mode. I've confirmed by disabling and reenabling org-roam support.

**Comment by codetrick** [comment]
> The same is happening for me, even without running emacs in daemon mode. I've confirmed by disabling and reenabling org-roam support.
> 
> By checking out older versions, `901082b91` for instance, it does not freeze on startup, but once I try and use roam, such as with `, r f`. Is this the same for you @codetrick?
> 
> Edit: by deleting the `org-roam.db` file and starting emacs, I could see that the file was recreating and was growing, slowly. After leaving it for a long time to grow to >2MB, Spacemacs stopped hanging. This is the behaviour using the old checked out version, I'm not sure if the same behaviour is causing your problem with the latest version.

No, with commit 901082b91 my spacemacs starts up just fine. Perhaps my problem is a bit different from yours. Did you try `git bisect` to find out which commit started to cause problem?

**Comment by carlduevel** [comment]
I experienced the same problem: Emacs was not starting in daemon mode anymore after enabling org-roam support, but it did still start without the daemon flag. During such a start I noticed this in the messages buffer:

`face-attribute: Opening directory: No such file or directory, $HOME/org-roam`

I set `org-roam-directory` in the user-config. [I switched it to user-init](https://github.com/carlduevel/dotfiles/commit/3b21848f27cdb24394c1889855e0de6b5ef30b10) which fixed the problem.

**Comment by lebensterben** [comment]
There's enough bug reports related to org-roam, and we need to review its integration with spacemacs.

**Comment by danielkrizian** [comment]
the symptoms disappeared for me after defining `org-roam-directory` and `org-roam-db-location`  in `dotspacemacs-configuration-layers` (probably only the `org-roam-db-location` is required to fix the daemon. without it, the `org-roam.db` is created under `.emacs.d`)
```elisp
     (org :variables
          org-enable-roam-support t 
          org-roam-directory (concat org-directory "/roam")
          org-roam-db-location (concat org-roam-directory "/db/org-roam.db")
          org-roam-v2-ack t
          )
```

**Comment by schlagenhauf** [comment]
@danielkrizian 's changes did the trick for me after i added `org-directory <path>` before `org-roam-directory`.

**Comment by lebensterben** [comment]
by default, 
variable|default-value
--|--
`org-roam-directory`|`~/org-roam`
`org-roam-db-location`|`~/.emacs.d/org-roam.db`

try:
Without using the aforementioned workaround, create the directory structures
```bash
mkdir -p ~/org-roam
```
