### ISSUE TITLE
Bug: Not being able to type `k` followed by another character in multi-term `SPC a s t` 

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#1447]
This error is really weird look at it here (sorry for small font, currently experimenting with urxvt)

[![alt](https://asciinema.org/a/19370.png)](https://asciinema.org/a/19370)

**Comment by syl20bnr** [comment]
Weird but no suprising, this is due to the new `jk` to complete. I will fix this tonight.
Thank you for the report :+1:

**Comment by darkfeline** [comment]
I fixed this by sticking `(evil-define-key 'insert term-raw-map "k" 'term-send-raw)` in my personal config.

**Comment by TheBB** [comment]
I'm assuming this was fixed by https://github.com/syl20bnr/spacemacs/commit/8a6bcacb09183844f0b80a9e1395a67b4c47514f.
