### ISSUE TITLE
Do not run automatic formatting on yanking when in LSP mode?

### ISSUE THREAD

**Issue by kindaro** [syl20bnr/spacemacs#14488]
LSP mode has a toggle `lsp-enable-on-type-formatting` for whether code should be automatically formatted. But even when it is disabled, some other mechanism makes a section of code formatted when yanking happens nearby. It seems to use the LSP formatting facilities when LSP is active, but it does not respect LSP's toggle.

The work around is to disable this feature by hand, with this code:

    (dolist (func '(yank yank-pop evil-paste-before evil-paste-after))
      (advice-remove func #'spacemacs//yank-indent-region))

Maybe we should respect LSP's settings for whether automatic formatting is desired?

**Comment by yyoncho** [comment]
I want to add that lsp-mode formatters are much more aggressive than the other formatters and often users don't want to run them automatically like spacemacs do on paste. As a minimum, spacemacs should provide a setting to disable format on paste.

**Comment by lebensterben** [comment]
depending on the type of language, indentations may or may not have semantical meanings. so it makes sense to have it enabled by default to some languages. But in general this feature should be gated behind a toggle.

**Comment by lvh** [comment]
This is an even broader issue: something in my Clojure setup is causing this to trigger _all the time_. For example if I'm typing a call with the cursor at `|`:

```clojure
(->|)
```

and type a space, the lsp layer causes it to be immediately formatted as if I had never typed the space, which is incredibly annoying. Calling `lsp-toggle-on-type-formatting` or setting it disabled with the layer variable has no effect. Disabling lsp-mode has no effect. Disabling `smartparens-mode` (I was trying to figure out if that triggered anything) has no effect, neither does rainbow-delimiters. The only reliable way I have to get this to stop happening is to disable `lsp-mode`.

**Comment by yyoncho** [comment]
@lvh here is the analysis on lsp-mode side as well:

https://github.com/emacs-lsp/lsp-mode/issues/2600

**Comment by LightspeedLife** [comment]
I'm still getting this issue.  Kindaro's fix works for me.

**Comment by lebensterben** [comment]
@LightspeedLife what's the major mode in your case?

I found a workaround, say you're having `clojure-mode`
```elisp
(push 'clojure-mdde spacemacs-indent-sensitive-mode)
```

**Comment by LightspeedLife** [comment]
I'm using 'c-mode'; `(push 'c-mode spacemacs-indent-sensitive-modes)` does not work for me.

**Comment by lebensterben** [comment]
@LightspeedLife 
If `spacemacs-indent-sensitive-modes` contains `c-mode`, the region won't be indented after yanking.
Do you still find it indented?

**Comment by LightspeedLife** [comment]
Well this is really weird, I wish I knew how to explain it, but it's working now.  I started a fresh instance of Spacemacs and used `eval-expression` to test both solutions, and for some reason, only kindaro's worked last night, but they're both working now.

**Comment by amfern** [comment]
I am also experiencing the same issue, every time I do a new line or paste something, the region gets auto-formated

**Comment by lebensterben** [comment]
@LightspeedLife

After testing I can confirm that modifying `spacemacs`-indent-sensitive-modes` works as expected.

Please provide a example code snippet and a reproduction guide in case there's a misunderstanding.

**Comment by lebensterben** [comment]
@amfern 

Try either one of the following:
```elisp
(push 'foo-mode spacemacs-indent-sensitive-modes)
(add-to-list 'spacemacs-indent-sensitive-modes 'foo-mode)
```

**Comment by amfern** [comment]
@lebensterben i add `(add-to-list 'spacemacs-indent-sensitive-modes 'c-mode 'c++-mode)`   in the `dotspacemacs/user-config`  but it has no effect.

**Comment by lebensterben** [comment]
you're using the function wrong.
```elisp
(add-to-list 'spacemacs-indent-sensitive-modes 'c-mode)
(add-to-list 'spacemacs-indent-sensitive-modes 'c++-mode)
````

**Comment by amfern** [comment]
yes, it does work now.

**Comment by lebensterben** [comment]
I'm still thinking how to deal with this.

first spacemacs-indent-sensitive-modes is a layer config variable. but it's not documented.

second, I'm thinking whether I should just add the major mode to spacemacs-indent-sensitive-modes when lsp-mode starts.

**Comment by yyoncho** [comment]
@lebensterben alternatively check if lsp-mode is enabled in the buffer before formatting.
