### ISSUE TITLE
website: Add a UI to quickly switch between `master` and `develop` branch

### ISSUE THREAD

**Issue by lebensterben** [syl20bnr/spacemacs#14486]
Currently, `spacemacs.org` website redirects to `www.spacemacs.org` which is on the `master` branch, while `develop.spacemacs.org` is on the `develop` branch.

I wish there's an easy way to switch between the `master`/`develop` versions of all applicable web pages, including the main page, quick start, layer list, contribution guide, etc.

For example, we may add a `Switch to Develop`/`Switch to Stable` ribbon similar to the `Fork me on GitHub` ribbon we currently have.

**Comment by real-or-random** [comment]
I think this issue can be closed as obsolete. The correct solution is https://github.com/syl20bnr/spacemacs/issues/15995.
