### ISSUE TITLE
Evilified normal keys breaks "t" keabinding in agenda

### ISSUE THREAD

**Issue by janws** [syl20bnr/spacemacs#14484]
#### Description :octocat:
Evilified normal keys breaks "t" keybinding in agenda. It still works in the org file itself.

#### Reproduction guide :beetle:
- Start Emacs
- (Assumption: Key binding to toggle todo stat using "t" has been configured with e.g. customize)
- Open agenda with todo items
- Place point on line with todo item
- press "t"

*Observed behaviour:* :eyes: :broken_heart:
Nothing happens

*Expected behaviour:* :heart: :smile:
Todo item gets toggled e.g. TODO -> DONE

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 898e5092733d0ba6e3de0ac4b85e3382f3e52847)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv elixir ipython-notebook python mu4e ranger helm auto-completion better-defaults emacs-lisp git org spell-checking latex bibtex treemacs)
```
- System configuration features: XAW3D XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by duianto** [comment]
Confirmed.

The PR:
[evilified] Add evilified normal keys: yank, navigate #14448

Also broke these keys which used to call these commands:
`w`, `org-agenda-week-view`
`f`, `org-agenda-later`

most likely more.

The PR has been reverted. Pull the latest develop branch.

Sorry about that, it seems to have been the wrong solution for adding more evilified keys.

**Comment by janws** [comment]
Works again for me with current develop. Thank you!
