### ISSUE TITLE
org-protocol doesn't invoke org-capture

### ISSUE THREAD

**Issue by darioceccoli** [syl20bnr/spacemacs#14487]
#### Description :octocat:
Commit [cf82ac2](https://github.com/syl20bnr/spacemacs/commit/cf82ac2ed38c3bb7a46899802f35eb23d4818746) seems to be breaking `org-protocol`

#### Reproduction guide :beetle:
- Start Emacs
- (make sure org-protocol is setup, see https://github.com/sprig/org-capture-extension)
- Call from your browser: org-protocol://capture?template=l&url=https%3A%2F%2Fgithub.com%2Fsyl20bnr%2Fspacemacs%2Fissues%2F14411&title=org-roam-mode%20not%20enabled%20when%20org-enable-roam-support%20is%20set%20%C2%B7%20Issue%20%2314411%20%C2%B7%20syl20bnr%2Fspacemacs&body=

*Observed behaviour:* :eyes: :broken_heart:
After [cf82ac2](https://github.com/syl20bnr/spacemacs/commit/cf82ac2ed38c3bb7a46899802f35eb23d4818746), org-capture is not invoked and nothing happens.

*Expected behaviour:* :heart: :smile:
Reverting [cf82ac2](https://github.com/syl20bnr/spacemacs/commit/cf82ac2ed38c3bb7a46899802f35eb23d4818746), org-protocol invokes correctly org-capture, the org-capture buffer is opened

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 13791616c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx
 (helm :variables history-delete-duplicates t)
 (auto-completion :enabled-for org :variables spacemacs-default-company-backends
                  '(company-capf)
                  company-backends
                  '(company-capf))
 emacs-lisp git markdown
 (org :variables org-enable-roam-support t org-ellipsis " ▾" org-confirm-babel-evaluate nil org-src-tab-acts-natively t org-src-window-setup 'current-window org-src-strip-leading-and-trailing-blank-lines t org-src-preserve-indentation t org-edit-src-content-indentation 0 org-export-babel-evaluate nil org-superstar-headline-bullets-list
      '("◈" "■" "●" "◉" "▷" "➤" "➢" "➣"))
 org-M-RET-may-split-line
 '((default . t)
   (headline)
   (item))
 treemacs colors
 (themes-megapack :packages
                  (sanityinc-tomorrow-eighties doom-themes modus-operandi-theme modus-vivendi-theme))
 theming
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 org-clock-budget org-roam-server org-sidebar)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by sochotnicky** [comment]
FWIW I was facing the same and managed to get it fixed by adding:
```lisp
(require 'org-roam-protocol)
```

To my user-config. Ideally though - I do think if the var is specified the feature should probably fully work.

**Comment by sochotnicky** [comment]
I am that well versed in elisp but the way I read this (https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bemacs/org/packages.el#L972):
```lisp
(when org-enable-roam-protocol
          (add-hook 'org-roam-mode-hook (lambda ()
                                          (require 'org-roam-protocol))))
```

Is that the org-roam-protocol is only enabled once you have opened *some* org-roam specific buffer. I really think that if the feature is enabled it should probably be required immediately instead of setting up the hook?
