### ISSUE TITLE
Very long rendering of shortcuts when evil-ace-jump-line-mode

### ISSUE THREAD

**Issue by alex-glv** [syl20bnr/spacemacs#1449]
On OS X, emacs installed via `brew install emacs --with-cocoa --HEAD`, when I have 3 buffers open (some of them are tramp buffers) and press `SPC-l (lowercase L)` cursors in all buffers start blinking (as if rotating between normal and insert modes) for some time (5 or more seconds, seems to be dependant on buffer length) and only then it draws characters next to lines.

Very similar behaviour is observed when I use `d SPC-l`, I can see characters are drawn next to the lines very slowly, as if with artificially imposed sleep routine for 200-300 milliseconds.

**Comment by syl20bnr** [comment]
This is a regression in evil package. See #963
