### ISSUE TITLE
`dos-mode` package in `windows-script` layer should be replaced by `bat-mode`

### ISSUE THREAD

**Issue by lebensterben** [syl20bnr/spacemacs#14499]
https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/windows-scripts/local/dos/dos.el

`dos-mode` is obsolete and it's renamed to `bat-mode`, which is shipped with `emacs` now. We should replace it with `bat-mode`.

**Comment by snuffop** [comment]
I look forward to seeing the PR's  you create to address these issues.

**Comment by smile13241324** [comment]
The PR has been merged, please test and close this issue when all is working again @snuffop
