### ISSUE TITLE
`restructuredtext` is incomplete

### ISSUE THREAD

**Issue by lebensterben** [syl20bnr/spacemacs#14507]
It includes two local packages `rst-lists.el` and `rst-directives.el`
They seem to be included in buit-in `rst-mode` already.

https://github.com/tony/docutils-oldmigraton/blob/master/docutils/tools/editors/emacs/rst.el

**Comment by snuffop** [comment]
I look forward to seeing the PR's  you create to address these issues.

**Comment by lebensterben** [comment]
My original assessment is incorrect.
Some functionalities of `rst-lists` (by Wei-wei Guo) were added to `rst-mode` in 2010, but it's been updated til 2015, so certainly `rst-mode` is out-dated.

I will keep both, and add `rst-sphinx` package (also by Wei-wei Guo).

The real issue for this layer is, it's never really finished. Its key-bindings are not evilified at all.
