### ISSUE TITLE
`pylookup.el` is outdated

### ISSUE THREAD

**Issue by lebensterben** [syl20bnr/spacemacs#14500]
https://github.com/syl20bnr/spacemacs/blob/77d84b14e057aadc6a71c536104b57c617600f35/layers/%2Blang/python/local/pylookup/pylookup.el

This is outdated and is available at https://github.com/tsgates/pylookup
Is there any reason why we localise this package?

**Comment by snuffop** [comment]
I look forward to seeing the PR's  you create to address these issues.
