### ISSUE TITLE
use-package's ":load-path" is only effective after spacemacs finished loading

### ISSUE THREAD

**Issue by usharf** [syl20bnr/spacemacs#1451]
I'm trying to install a locally sourced package (ob-go) in a private layer, like this:

```emacs-lisp
(defun publishing/init-ob-go ()
  "Initialize my package"
  (use-package ob-go
    :load-path "private/site-lisp/ob-go"
    :defer t)
  )
```

On every launch of Emacs I see this message:
```emacs-lisp
Found 1 new package(s) to install...
--> fetching new package repository indexes...
--> installing (publishing):ob-go... [1/1]
Package ob-go is unavailable. Is the package name misspelled?
```

Though when manually syncing with `FER` (I'm on the develop branch) it seems to work just fine (and the module is indeed available and active).

```emacs-lisp
(Spacemacs) --> installing (publishing):ob-go... [1/1]
```

**Comment by syl20bnr** [comment]
You should move this package to `extensions.el` file which is for local packages.
`packages.el` is for installed packages from elpa repo.

**Comment by usharf** [comment]
Thank you, that solved the problem, which in fact, was that I left `ob-go` in the `packages` var of my private layer config...
