### ISSUE TITLE
NeoTree always shares the same buffer across frames. Is there a way to compare two project structures side-by-side?

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#1452]
One thing I miss from Vim/Sublime Text is that you're able to compare two project structures side-by-side. For example:

![screenshot 2015-04-30 19 12 56](https://cloud.githubusercontent.com/assets/2999209/7411905/5a676020-ef6f-11e4-9902-46b61036557a.png)

NeoTree doesn't have this functionality and in fact there has already been an issue https://github.com/jaypei/emacs-neotree/issues/57 about it but the author said it's a kind of hard to hack.

This is helpful when I'm spinning off another project based on a previous one, for example. Is there any way to get around it, or is some other handy alternative which can achieve this? Things like Dired seems to just list the root structure, but is unable to let me walk it.

**Comment by tuhdo** [comment]
You may want to look at [ztree](https://github.com/fourier/ztree) if you want to diff between 2 directories recursively.

**Comment by tuhdo** [comment]
As for Dired, you can press 'i' to insert sub-directories without creating new buffer.

**Comment by tuhdo** [comment]
Note that if you want to use `ztree`, remember to install `GNU Diff` and make sure it is the latest version, not the outdated one that comes with OS X.
