### ISSUE TITLE
Validation of dotspacemacs-themes is too strict

### ISSUE THREAD

**Issue by marienz** [syl20bnr/spacemacs#14529]
#### Description :octocat:
Validation of `dotspacemacs-themes` does not accept properties, while the [documentation](https://develop.spacemacs.org/doc/DOCUMENTATION.html#choosing-themes) says it will "accept the same properties as packages listed in layers package lists or in `dotspacemacs-additional-packages`". The documentation seems to (still) be correct: a theme specified this way loads correctly, but a warning is logged at startup.

I suspect both `dotspacemacs-additional-packages` and `dotspacemacs-themes` should use the same validation type as `dotspacemacs-configuration-layers`, not the current `(repeat symbol)`.

#### Reproduction guide :beetle:
- Initialize dotspacemacs-themes to something like `'((mz-tango :location local) spacemacs-dark)`
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The `*Messages*` buffer contains
```
(Spacemacs) Error in dotspacemacs/init: Variable: "dotspacemacs-themes" has value: "((mz-tango :location local) spacemacs-dark)" that doesn’t match its type: "(repeat symbol)". Validator message: "(user-error Looking for `(repeat symbol)' in `((mz-tango :location local) spacemacs-dark)' failed because:
Looking for `symbol' in `(mz-tango :location local)' failed because:
  not a symbol)"
```

*Expected behaviour:* :heart: :smile:
No errors.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 454e729ef)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((ivy :variables ivy-enable-advanced-buffer-information t)
 (auto-completion :variables auto-completion-idle-delay nil)
 better-defaults
 (ibuffer :variables ibuffer-group-buffers-by nil)
 (keyboard-layout :variables kl-layout 'dvorak kl-enabled-configurations
                  '(ace-window avy))
 c-c++ emacs-lisp
 (go :variables go-format-before-save t go-tab-width 4 go-backend 'lsp go-use-golangci-lint t)
 html
 (javascript :variables javascript-backend nil)
 typescript lua
 (markdown :variables markdown-executable "cmark")
 nginx perl5 protobuf python rust shell-scripts sql systemd yaml git github
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 syntax-checking
 (version-control :variables version-control-diff-tool 'diff-hl)
 (lsp :variables lsp-rust-server 'rust-analyzer)
 dap)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS GTK3 ZLIB

**Comment by timor** [comment]
I can confirm that using expressions like `(package :location ...)` cause validation errors for `dotspacemacs-additional-packages`.

**Comment by smile13241324** [comment]
@marienz  looks like this should be fixed on develop, can you double check and close the issue if it is gone?

**Comment by marienz** [comment]
Thanks! I can confirm that my .spacemacs now loads without errors again.
