### ISSUE TITLE
Add auto-save feature for Spacemacs

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1453]
Here is [a nifty trick for auto saving when switching window or buffer](http://batsov.com/articles/2012/03/08/emacs-tip-number-5-save-buffers-automatically-on-buffer-or-window-switch/).

Then, we can turn on `auto-save-mode` and automatically save the current active buffer with this function add to `auto-save-hook`:

```elisp
   (defun save-buffer-if-visiting-file (&optional args)
      "Save the current buffer only if it is visiting a file"
      (interactive)
      (if (and (buffer-file-name) (buffer-modified-p))
          (save-buffer args)))

   (add-hook 'auto-save-hook 'save-buffer-if-visiting-file)
```

We need the hook because despite the name `auto-save-mode`, it does something else: it automatically saves your buffer, but to a backup file rather than directly on your editing buffer.

**Comment by syl20bnr** [comment]
I would create a variable `dotspacemacs-auto-save-on-swtich` for this and put it deactivated by default because this is not something expected out of the box in editors.

**Comment by x-ji** [comment]
I think this is actually pretty common in modern editors... Be it Vim's swapfile or Sublime's automatic recovery etc. Actually with the current setting of `auto-save-default` set to `nil`, I sometimes indeed lost some changes on files because I had to kill `Emacs` abruptly when it encountered some bugs, and somehow `auto-save` was not triggered on such kills.

**Comment by tuhdo** [comment]
Autosave in Emacs behaves like Vim swap files. It saves your changes in a different file and surround the filename with `#` character i.e. `#.spacemacs#`. If you want to recover your changes, you have to explicitly invoke `recover-this-file` command. It only prints a message at the bottom to remind you to recover this file, so it's not as visible as Vim that uses the whole screen.

The autosave I'm suggesting go a step further: automatically save on buffer/window switch, and autosave directly to the current buffer after a specified interval. This behavior may differ from Vim but is common with majority editors out there.

**Comment by x-ji** [comment]
I see. I thought that for some reason autosave is not enabled by default in Spacemacs. The variable `auto-save-default` is `nil` and when I manually toggle `auto-save-mode` it seems that it was disabled in the beginning. Sometimes when I ran `recover-this-file` Emacs also couldn't find the backup file. So that shouldn't be the normal behavior?

**Comment by tuhdo** [comment]
`auto-save-mode` is enabled per buffer and it does not have a global minor mode. So, if you don't enable `auto-save-mode` while editing a buffer and wait for a specified interval, it won't save. `auto-save-mode` is currently not enabled in Spacemacs, that's why you can't recover the file. It's good time to start doing this now.

**Comment by x-ji** [comment]
Cool. Then your proposal definitely makes sense. Or maybe we can add hooks so that `auto-save-mode` would be enabled by default for most major modes?... I just supposed it is enabled by default just as in most editors, and thus lost some data I guess :sweat_smile:

**Comment by tuhdo** [comment]
I created a PR for enabling auto-save here: https://github.com/syl20bnr/spacemacs/pull/1484. It's a surprise that Spacemacs disables it by default. In stock Emacs, it is enabled by default. I guess maybe @syl20bnr doesn't like Vim swap files.

**Comment by syl20bnr** [comment]
hehe right, this is an artefact of my config :-)
I agree with @ralesi comments on the PR to expose this as a dotspacemacs variable enabled by default.

**Comment by dijonkitchen** [comment]
Looks like this was undone in https://github.com/syl20bnr/spacemacs/commit/cd70f04
