### ISSUE TITLE
Evil keys not working for mu4e

### ISSUE THREAD

**Issue by jia-j-chen** [syl20bnr/spacemacs#14548]
#### Description :octocat:
Evil keys not working for mu4e

#### Reproduction guide :beetle:
- Start Emacs
- Start mu4e
- Jump into inbox and open a message
- Try to move around inside the message using key "j" or "k"

*Observed behaviour:* :eyes: :broken_heart:
Cannot move and around and receive the error message below
"user-error: [mu4e] Unknown shortcut 'j'"

A futher check of the Messages buffer shows the following warning messages:
"Package cl is deprecated
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "mu4e-utils.el") => (macroexpand-all …) => (macroexpand (eval-when-compile …)) => (load "org-mu4e.el") => (load "mu4e.el") => (load "mu4e-headers.el") => (load "mu4e-utils.el")
Auto-evilification could not remap these functions in map ‘mu4e-headers-mode-map’:
   - ‘mu4e-headers-query-prev’ originally mapped on ‘\’
Auto-evilification could not remap these functions in map ‘mu4e-headers-mode-map’:
   - ‘mu4e-headers-query-prev’ originally mapped on ‘\’
Created mu4e link.
Auto-evilification could not remap these functions in map ‘mu4e-headers-mode-map’:
   - ‘mu4e-headers-query-prev’ originally mapped on ‘\’"

*Expected behaviour:* :heart: :smile:
Move around using evil keys

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3fe675d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(csv python bibtex html helm auto-completion better-defaults emacs-lisp git markdown org
     (chinese :variables chinese-enable-fcitx t chinese-fcitx-use-dbus t pyim-default-scheme 'microsoft-shuangpin)
     latex ranger pdf mu4e
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     version-control
     (mu4e :variables mu4e-use-maildirs-extension t mu4e-installation-path "/usr/share/emacs/site-lisp" mu4e-enable-async-operations t mu4e-maildir "/home/chenj/Maildir" mu4e-sent-folder "/Local_sent" mu4e-headers-full-search nil mu4e-headers-results-limit 500 mu4e-drafts-folder "/Drafts" mu4e-trash-folder "/Deleted_Messages" mu4e-attachment-dir "~/Downloads" mu4e-get-mail-command "offlineimap" mu4e-view-show-images t mu4e-view-show-addresses t mu4e-headers-date-format "%Y-%m-%d %H:%M" mu4e-compose-reply-to-address "jia.j.chen@foxmail.com" user-mail-address "jia.j.chen@foxmail.com" user-full-name "Jia CHEN" send-mail-function 'async-smtpmail-send-it message-send-mail-function 'async-smtpmail-send-it smtpmail-smtp-server "smtp.qq.com" smtpmail-smtp-service 465 smtpmail-stream-type 'ssl smtpmail-auth-credentials
           (expand-file-name "~/.authinfo.gpg")
           mu4e-headers-fields
           '((:date . 18)
             (:flags . 6)
             (:from . 15)
             (:to . 15)
             (:subject))
           mu4e-compose-signature "Jia CHEN @ http://chenjia.gsm.pku.edu.cn" mu4e-maildir-shortcuts
           '(("/INBOX" . 105)
             ("/PKU_Email" . 112)
             ("/Sent_Messages" . 115))))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by zzjjzzgggg** [comment]
It is caused by recent commit  f5d121599bd84bd5718a871a691467c609efa4bd. Deleting line 81 `:eval-after-load t` could fix this bug.

**Comment by duianto** [comment]
@jia-j-chen You can close this if it fixed your issue.

**Comment by jia-j-chen** [comment]
> I think the 'fix' for the void variable mu4e-view-mode-map was premature. This was an issue which occurred in the development version of mu4e after the maintainer did some re-factoring as part of the move to using GNUS to view messages rather than the older mu4e specific version.
> 
> I don't think spacemacs should apply patches to fix issues in development versions of packages it supports. These packages are often changing frequently and, as is the case here, the issue is likely to be resolved by changes in the development code anyway.
> 
> I think the patch to revert the change is a good idea. I have manually done this and it does fix the issue associated with loss of vi keys in mu4e-view-mode. The void variable for mu4e-view-mode-map was fixed in the mu4e code and does not need a fix in the spacemacs mu4e layer.

Thanks for the reply! Could you be more specific on how you manually revert the change?

**Comment by jia-j-chen** [comment]
#14549 has fixed my issue eight hours ago. I am closing this issue.

**Comment by theophilusx** [comment]
Note that the manual revert is now not required as the commit which
introduced the change has now been reverted.

The manual revert was simply to comment out the offending line.


-- 
Tim Cross

**Comment by lebensterben** [comment]
then we need to revert our fix if it's no longer needed...

**Comment by jia-j-chen** [comment]
> then we need to revert our fix if it's no longer needed...

As far as I can tell, our fix is still needed.
