### ISSUE TITLE
default company-transformers in spacemacs are causing trouble

### ISSUE THREAD

**Issue by yyoncho** [syl20bnr/spacemacs#14547]
Reference: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+completion/auto-completion/packages.el#L122

There are multiple issues related to these transformers:

1. Methods like doStuff won't be completed since do is considered as non-prefix
2. company-sort-by-occurrence breaks language server sorting order 
3. It introduces a slowdown. 

Proposed fixes:

Option 1: putting these behind a variable, which is off by default
Option 2: delete code related company-transformers
Option 3: disable them for lsp-mode enabled buffers.
Option 4: ?

I am voting for 2).

**Comment by smile13241324** [comment]
Hmmm, good point I was not aware that Spacemacs adds these in the first place. I would agree these are not longer up-to-date, especially the cancel conditions are far too generic and will cause various issues in many languages.

About the company-sort-by-occurrence function I personally like them however I think that for most modes it is not necessary and the performance costs are just too high for this.

Lets remove it for now. Individual layers can make this variable buffer local and add these transformers individually.
This would especially be true for `company-mode-completion-cancel-keywords` which would need to be set for each language individually anyway.

**Comment by smile13241324** [comment]
@yyoncho there is still the company-statistics package which will also add a company-transformer which will most likely interfere with server based completion sorting. Can we reliably disable this in the LSP layer when lsp-mode is activated.

**Comment by yyoncho** [comment]
> Hmmm, good point I was not aware that Spacemacs adds these in the first place.

I wasn't aware too, I was doing performance testing and they appeared in the profiler report. 

> Can we reliably disable this in the LSP layer when lsp-mode is activated.

I would say that the benefit from that package depends on the server. The simple one will benefit from the package while the complex one will do better without that package.

**Comment by smile13241324** [comment]
Hmmm this sounds like we would require something similar to dap mode, where the individual layers would need to set the modes for which company-statistic could be activated. Then auto-completion can make sure to add company-statistic package to the respective mode hooks.

Of course this would only be done if `auto-completion-enable-sort-by-usage` is non-nil.

Is there a way to find out via LSP capabilities if a server does completion sorting already? I just wonder how to find out whether to allow company-statistic for a mode.

**Comment by smile13241324** [comment]
I have removed the standard company-transformers just now. I think this should solve the first set of issues with auto-completion. The next step should be to make activating of company-statistics more flexible.

**Comment by yyoncho** [comment]
> Is there a way to find out via LSP capabilities if a server does completion sorting already? I just wonder how to find out whether to allow company-statistic for a mode

lsp-mode is always doing a sorting based on different input params(prefix, priority as defined by the server, etc). It will work well enough OOTB. My point is that, for the basic servers which pretty much only return a list of the items company-statistics might provide better UE.

**Comment by yyoncho** [comment]
I checked the code - having company-statistics guarded by auto-completion-enable-sort-by-usage is good enough IMHO.

**Comment by smile13241324** [comment]
Ok, lets keep it this way. 

I was just wondering how a user would manage to have company-statistics activated for a simple mode like lets say `json` and still have proper sorting done on the server side for a more complex server like for `groovy`.

When I understand `auto-completion-enable-sort-by-usage` correctly this would only allow for a global  setting which would always be wrong for one of the two use-cases.

**Comment by bcc32** [comment]
FYI, https://github.com/syl20bnr/spacemacs/commit/d16a8c3a7c698be49d521580ee573945e8c15b52 removes the definition of `company-mode-completion-cancel-keywords`, but there is still a reference to that variable in https://github.com/syl20bnr/spacemacs/blob/d16a8c3a7c698be49d521580ee573945e8c15b52/layers/%2Bcompletion/auto-completion/funcs.el#L315-L319

**Comment by smile13241324** [comment]
You are right the last traces of this function should also be removed.

**Comment by vv111y** [comment]
I'm getting   
```Company: An error occurred in auto-begin
Symbol’s function definition is void: spacemacs//company-transformer-cancel```  
and no completions. If I re-eval the function again I also have to set  
```(setq company-mode-completion-cancel-keywords nil)```   

then company is working again.
