### ISSUE TITLE
[error] can't find pylookup.py

### ISSUE THREAD

**Issue by sunlin7** [syl20bnr/spacemacs#14544]
Hi, after upgrade to last `develop` branch, there is an error when execute `pylookup-lookup` command:
>pylookup-exec-get-cache: Searching for program: No such file or directory, ~/.spacemacs.d/layers/+lang/python/local/pylookup/pylookup.py

It seems #14522 remove the `pylookup.py`.

**Comment by sunlin7** [comment]
It seems the new installation flow, it will download `pylookup` into `~/.emacs.d/.cache/quelpa/build/pylookup/`, then it will compile and install the package into `~/.spacemacs/elpa/27.2/develop/pylookup-20180819.2240/`, but forgot to copy the script `pylookup.py` to destination folder.

**Comment by sunlin7** [comment]
Hi @lebensterben , 
It not work in my local. 
To test this change, the `~/.emacs.d/.cache/quelpa/build/pylookup/` and `~/.spacemacs.d/elpa/27.2/develop/pylookup-20180819.2240` are removed, then start the (space)emacs. It will clone the `pylookup` into `~/.emacs.d/...` and install `pylookup` into `~/.spacemacs.d/...`, then run `pylookup-lookup`, get an error message:
> pylookup-exec-get-cache: Searching for program: No such file or directory, ~/.spacemacs.d/elpa/27.2/develop/pylookup-20180819.2240//pylookup.py

**Comment by lebensterben** [comment]
why it's .spacemacs.d not .emacs.d

**Comment by lebensterben** [comment]
and in any case, `~/.spacemacs.d/elpa/27.2/develop/pylookup-20180819.2240` should be the correct path.

**Comment by sunlin7** [comment]
This is no `pylookup.py` in the `~/.spacemacs.d/elpa/27.2/develop/pylookup-20180819.2240/` folder, only `*.el` files in it.
