### ISSUE TITLE
dir-locals.el not being read/used when opening a file using helm-projectile

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#14558]
#### Description :octocat:
`.dir-locals.el` file not being read when opening a file using helm-projectile.
Works fine if I open the file from dired.

#### Reproduction guide :beetle:
1. Add this file to `.dir-locals.el` in a git directory:

```elisp
((python-mode . (
      (pyvenv-activate . "/home/synic/.virtualenvs/neuro")
      (flycheck--automatically-enabled-checkers . (python-mypy python-flake8))
      (flycheck-python-mypy-config . "/home/synic/Projects/neuro/.mypy.ini")
      (flycheck-flake8rc . "/home/synic/Projects/neuro/.flake8")
)))
```

2. Open one of the project files using projectile

*Observed behaviour:* :eyes: :broken_heart:
`.dir-locals.el` file is ignored

*Expected behaviour:* :heart: :smile:
For the settings in the file to be applied

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3fe675d58)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(typescript perl5 go swift csv lua nginx sql auto-completion emacs-lisp git yaml javascript html markdown major-modes python org osx python ipython-notebook django syntax-checking spell-checking colors spacemacs-layouts vimscript helm
            (version-control :variables version-control-diff-tool 'diff-hl)
            (c-c++ :variables c-c++-enable-clang-support t)
            (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by tshu-w** [comment]
Can not reproduce with 
- OS: darwin
- Emacs: 28.0.92
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 6fc9faee8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python emacs-lisp helm org)
```
- System configuration features: ACL GIF GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS ZLIB
