### ISSUE TITLE
Clojure and LSP: Sideline "Action Prompts" Overflow when Cursor is Moved to the Right

### ISSUE THREAD

**Issue by markus-wa** [syl20bnr/spacemacs#14553]
#### Description :octocat:
Clojure and LSP: Action Prompts (e.g. `Extract Function`) Overflow / are misaligned when Cursor is Moved to the Right

This only started happening after a recent upgrade of spacemacs and installed packages.
I have since completely nuked my emacs installation and re-installed spacemacs, but the issue keeps coming back.

#### Reproduction guide :beetle:
- Start Emacs
- Enable `lsp` layer
- Open `.clj` file
- Respond yes when asked to install Clojure LSP
- Write any Clojure, or navigate to the right of a form in the opened code
- Note: you may need to wait for LSP to start properly and the jiggle around the code a bit, sometimes the alignment is correct at the beginning. But after moving across lines and back and forth it should break.

*Observed behaviour:* :eyes: :broken_heart:
The action prompts (e.g. `Extract Function`) on the right are misaligned when the cursor is moved to the right.
The prompts wrap / roll over onto the next line, interfering with existing code.

Specifically the alignment gets worse the further right the cursor is moved. moving the curser before the first form of a line gives us the expected result.
Moving the curser just to the right of the first form causes a single character to overflow on to the next line.
Going further to the right causes more and more characters to move onto the next line, always incrementing by one per form.

![image](https://user-images.githubusercontent.com/5138316/112346037-7d127000-8cbd-11eb-983b-42eacb392aec.png)

*Expected behaviour:* :heart: :smile:

Action prompts are aligned properly to the right side of the buffer.

![image](https://user-images.githubusercontent.com/5138316/112345367-e04fd280-8cbc-11eb-9ac9-0a6013b40b7a.png)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 679040fbf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lsp multiple-cursors terraform docker sql python csv clojure yaml helm auto-completion better-defaults emacs-lisp git markdown org
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term)
     spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:

I'm not sure if this is relevant at all to the issue (probably not actually), but the `Messages` buffer shows this message at LSP startup.

```
Eager macro-expansion failure: (wrong-type-argument listp [(first-item . rest-items) (sp-get-list-items)])
```

**Comment by lebensterben** [comment]
I'm familiar with LSP backends in several other major modes, and I've never observed this behaviour.

I don't think this is caused by settings in Spacemacs. Consider to report it to `lsp-mode`.
https://github.com/emacs-lsp/lsp-mode/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by markus-wa** [comment]
Thanks @lebensterben - I had a feeling this might be the wrong place :smile:

**Comment by markus-wa** [comment]
I'll have to re-open this.

The following config works as expected:
```el
dotspacemacs-default-font '("Source Code Pro")
```

while this one doesn't:
```el
dotspacemacs-default-font '("Source Code Pro"
                            :size 10.0)
```

which is strange as the comment above it says

```
;; Default font or prioritized list of fonts. The `:size' can be specified as
;; a non-negative integer (pixel size), or a floating-point (point size).
;; Point size is recommended, because it's device independent. (default 10.0)
```

> default 10.0

**Comment by lebensterben** [comment]
> while this one doesn't:
> 
> ```el
> 
> dotspacemacs-default-font '("Source Code Pro"
> 
>                             :size 10.0)
> 
> ```
Do you mean when setting this size to 10.0 the sideline stops working correctly?

Can you try 9.0 8.0 etc?
I believe this still is caused in lsp-mode. Have you opened an issue there?

**Comment by markus-wa** [comment]
I haven't opened an issue there yet
I'll try to find some time to do different options but at this stage I wouldn't know what issue to open in `lsp-mode` as I can't yet reproduce the behaviour without spacemacs :sweat_smile: 

I think first it would be good to understand why the two configs are not identical - looking at the comment above they should be

**Comment by lebensterben** [comment]
This is reported upstream: https://github.com/emacs-lsp/lsp-ui/issues/597

**Comment by markus-wa** [comment]
:pray:

thanks for finding that @lebensterben - I should have done a better job searching :sweat_smile:

**Comment by lebensterben** [comment]
@markus-wa 
But I still think it's intriguing why removing `:size 10.0` fixes the problem.
Does your emacs falls back to a smaller size when you remove `:size 10.0`?

**Comment by markus-wa** [comment]
> Does your emacs fallback to a smaller font size when you remove :size 10.0?

It actually falls back to a _larger_ font size. But yeah why it does that is still a puzzle to me :thinking:
