### ISSUE TITLE
emacs28.  spacemacs  Error (use-package): window-purpose/:config: Wrong number of arguments:

### ISSUE THREAD

**Issue by apple0012** [syl20bnr/spacemacs#14565]

**Comment by liny01-nbsa** [comment]
Restore package `imenu-list-20210305.2206` got rid of the issue for me.

**Comment by lebensterben** [comment]
@liny01-nbsa Has this been reported upstream? https://github.com/bmag/imenu-list

**Comment by liny01-nbsa** [comment]
Reported bmag/imenu-list#68

**Comment by yssource** [comment]
pyright --version

pyright 1.1.126

Error running timer ‘imenu-list-update’: (error "Timeout while waiting for response. Method: textDocument/documentSymbol.")

**Comment by yssource** [comment]
@yssource 
It works for me now, after updating to the latest imenu-list and emacs version.
"Error running timer ‘imenu-list-update’: " disappeared.
