### ISSUE TITLE
Cannot open load file: No such file or directory, ob-erlang

### ISSUE THREAD

**Issue by dtransposed** [syl20bnr/spacemacs#14567]
Hello!

I am facing the same problem as in this stale issue:
https://github.com/syl20bnr/spacemacs/issues/11669

I have fresh Spacemacs installation, version ```0.300.0@27.1```(develop branch). Everything has been working fine so far, but I am trying to learn about the ```org``` mode now. When I try to turn it on I get the error:
```Cannot open load file: No such file or directory, ob-erlang```

Could somebody help me out? Thanks!

EDIT: ```0.300.0@27.1``` not ```0.300.0@21.1 ``` (typo)

**Comment by lebensterben** [comment]
if your emacs is seriously 21.1, you should upgrade it first.

**Comment by dtransposed** [comment]
I am sorry, this was a typo, my emacs is 27.1

**Comment by lebensterben** [comment]
Does this problem occur when you try to open a specific file or any file?

**Comment by dtransposed** [comment]
I think it's file-agnostic. I simply open a new buffer, go ```space``` ```space``` and choose ```org-mode``` and expect to see my notes being edited according to org-mode. But they remain in text mode, plus this error appears.

**Comment by lebensterben** [comment]
So this even happen when the file is empty?

**Comment by lebensterben** [comment]
Add the following to `dotspacemacs-additional-packages`
```elisp
(ob-erlang :location (recipe :github :repo "https://github.com/xfwduke/ob-erlang/"))
```
In `dotspacemacs/user-config`
```elisp
(require 'ob-erlang)
(org-babel-do-load-languages
    'org-babel-load-languages
    '((erlang . t)))
```

**Comment by dtransposed** [comment]
This is interesting. I have modified the dot file:

```
;; List of additional packages that will be installed without being
 ;; wrapped in a layer. If you need some configuration for these
 ;; packages, then consider creating a layer. You can also put the
 ;; configuration in `dotspacemacs/user-config'.
 dotspacemacs-additional-packages '()
 (ob-erlang :location (recipe :github :repo "https://github.com/xfwduke/ob-erlang/"))
 ;; A list of packages that cannot be updated.
 dotspacemacs-frozen-packages '()
```

```
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
  )
(require 'ob-erlang)
(org-babel-do-load-languages
 'org-babel-load-languages
 '((erlang . t)))
;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
```

The org-mode is working file. However, whenever I start the new emacs session I get the following prompt:

```Spacemacs encountered an error while loading your '/Users/me/.spacemacs.d/init.el' file. Pick your editing style for recovery```

Have I done something wrong?

**Comment by lebensterben** [comment]
watch the parentheses.
What I showed you should be put in the parentheses.

**Comment by dtransposed** [comment]
I was playing with parenthesis but failed to fix the problem. Would you be so kind and show me, using the code blocks I entered before, how it should be done properly?

**Comment by lebensterben** [comment]
```elisp
dotspacemacs-additional-packages '(
 (ob-erlang :location (recipe :github :repo "https://github.com/xfwduke/ob-erlang/")))
```

```elisp
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
(require 'ob-erlang)
(org-babel-do-load-languages
 'org-babel-load-languages
 '((erlang . t))))
```

**Comment by dtransposed** [comment]
After doing that, I still had issues. I have reset the whole Spacemacs configuration and everything started working right off the bat, without additional editing of the dot file. Thank you for your patience @lebensterben (as a German speaker, appreciate the worldplay).

**Comment by lebensterben** [comment]
Well, then it's likely caused by some old packages￼, if by resetting you mean you had nuked the .emacs.d.

You can then try to remove the lines you just added.
