### ISSUE TITLE
Jump back to source in haskell repl

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#1456]
;; Switch back to editor from REPL
      (evil-leader/set-key-for-mode 'interactive-haskell-mode
        "msS"  'haskell-interactive-switch)

Implies some mode specific behaviour to jump back to the source. The mode specific options seem entirely missing.

**Comment by syl20bnr** [comment]
I don't know if this is useful, you could use `SPC #` with `#` begin the number of the window.
Does this shortuct switch the buffer in the current window ?

**Comment by fatlazycat** [comment]
Not sure I would use it either. 

Was just scanning the docs to see what's there and saw it.

**Comment by d12frosted** [comment]
Oh. So there was an open issue for this. Good thing - it's already fixed by #3274. You were looking for `haskell-interactive-switch-back` function :smile:

**Comment by fatlazycat** [comment]
Great thanks
