### ISSUE TITLE
core-jump: reference-handler api is not working at all

### ISSUE THREAD

**Issue by lebensterben** [syl20bnr/spacemacs#14577]
We've created internal APIs similar to jump-handlers (jump to definition) for jumping to references, but its' never actually used by any modes.
It's very surprising to me this is never implemented. Below is a minimal example how we can implement this:

```elisp
(setq spacemacs-default-reference-handlers '(xref-find-references))
```

This is surely not smart, because it's just matching the input token, but this is better than not having anything.

For example, often time in `emacs-lisp` mode this is all what I need.

Any thoughts on why this issue is never addressed?

**Comment by tshu-w** [comment]
Maybe not having a shortcut like `spacemacs/jump-to-definition` is a big reason that people don't know about this feature.

**Comment by lebensterben** [comment]
There is, `g r`. The thing is the function that creates the binding is never called.

**Comment by tshu-w** [comment]
I have no bindings on my side, maybe there is something wrong with my configuration.

**Comment by lebensterben** [comment]
https://github.com/syl20bnr/spacemacs/blob/eaf2e932e6aca3fe5a53715089f9566d9dacffe4/core/core-jump.el#L54-L75

As I said,
> There is, `g r`. The thing is the function that creates the binding is never called.

**Comment by tshu-w** [comment]
> https://github.com/syl20bnr/spacemacs/blob/eaf2e932e6aca3fe5a53715089f9566d9dacffe4/core/core-jump.el#L54-L75
> 
> As I said,
> 
> > There is, `g r`. The thing is the function that creates the binding is never called.

Sorry, I misunderstood your meaning.

**Comment by thanhvg** [comment]
It never worked. I am glad it didn't work because xref.el in core emacs is better.

https://github.com/syl20bnr/spacemacs/commit/c825035e48c047f907968813a4bf57cace05ac21#commitcomment-37484537

Spacemacs `core-jump` was great at the time when `lsp` and `xref.el` weren't  a thing yet. Now it is a redundant feature. I also have another pr on core-jump https://github.com/syl20bnr/spacemacs/pull/13448 sitting for a year but it will never see the light of day I guess.

**Comment by lebensterben** [comment]
@thanhvg 
Thus my simple solution described above just uses xref. The only real benefit is "g r" could be bounded for all prog-mode.

And yes, your unmerged PR deserves to be reviewed.

We can have both ", g d/r" and "g d/r" and both intelligently determine its source.

**Comment by thanhvg** [comment]
I think the days for Spacemacs to manage these standard features are over. Let `lsp` and `xref` do it. Let's go with the upstream standard. No more our own and isolated convention which will hurt ourselves in the long run.

Emacs 27 is full of new and powerful features already let alone 28 but we are still thinking about 25.  

If any package wants to manage xref such as tide and lsp it will go through  the xref interface not Spacemacs core-jump. For end users xref functions are what they need. I have this `gr` binding in my config:
``` elisp
  (define-key evil-normal-state-map "gr" #'xref-find-references)
```
And it works anywhere with all kinds for backends such as: lsp, tide, gtags or even dump-jump I guess. 

Btw I'm fine with my PRs being ignored. The maintainers have more important things to tend to and I have my fork anyway. These days I'm just arguing on matters that would make it impossible for me to rebase my fork on develop branch :)

**Comment by smile13241324** [comment]
lol proved you wrong @thanhvg :) your PRs are merged.
You are right we should definitely go on with modern standards and stop supporting century old systems in Spacemacs.

Lets modernise this beast.
