### ISSUE TITLE
Weird Evil keybidings in buffer-menu  

### ISSUE THREAD

**Issue by rcdeoliveira** [syl20bnr/spacemacs#14572]
#### Description :octocat:
Weird Evil keybidings in buffer-menu  

#### Reproduction guide :beetle:
- Start Emacs
- activate 'buffer-menu'
- Try to go up in the list with K

*Observed behaviour:* :eyes: :broken_heart:
K key in buffer-menu marks buffer to be deleted and go up in the list, it would be better just to go up and mark buffer to be deleted with D key, this will match better evil behavior shown in other buffers.

*Expected behaviour:* :heart: :smile:
Go up with K key in buffer-menu list without mark buffer to be deleted

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. aa0c0301e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(systemd html markdown auto-completion better-defaults emacs-lisp git ivy lsp multiple-cursors
         (terraform :variables terraform-backend 'lsp)
         spell-checking syntax-checking treemacs version-control
         (python :variables python-backend 'pyls)
         javascript yaml ansible
         (groovy :variables groovy-backend 'lsp groovy-lsp-jar-path "~/.local/share/lsp/groovy-language-server-all.jar"))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
`k` for `buffer-menu-delete` is the default key-binding in emacs.
What you said makes sense. `buffer-menu-mode` is not evilified.

**Comment by duianto** [comment]
Fixed in develop: 
buffer-menu: Add evil collection keys https://github.com/syl20bnr/spacemacs/commit/b005de9c40da4bbc086b3c95b1831ec508c567ed

The evil collection buff menu keys can be found here:
https://github.com/emacs-evil/evil-collection/blob/master/modes/buff-menu/evil-collection-buff-menu.el
