### ISSUE TITLE
tmux layer: Keys not available while in NeoTree window

### ISSUE THREAD

**Issue by gregpardo** [syl20bnr/spacemacs#1457]
Seems to be a conflict here. When my NeoTree is open. I can switch between tmux planes and windows seamlessly. When I move to the file tree I can no longer use the C-h/j/k/l to navigate out of the file tree.

**Comment by rphillips** [comment]
I bet neotree isn't in normal mode. Perhaps @tuhdo or @syl20bnr could comment on this. The tmux plugin only binds to the `evil-normal-state-map`, which might be wrong.

https://github.com/syl20bnr/spacemacs/blob/master/contrib/tmux/extensions/tmux/tmux.el#L56

**Comment by syl20bnr** [comment]
Indeed Neotree is in motion state, it should be added to the tmux layer.

**Comment by rphillips** [comment]
Seems to work a lot better now!

**Comment by gregpardo** [comment]
Looks good I was tempted to throw this in myself :)
