### ISSUE TITLE
Tern needs to be installed on windows for autocomplete in javascript mode

### ISSUE THREAD

**Issue by Devagamster** [syl20bnr/spacemacs#1458]
I added the javascript contrib layer to my .spacemacs file, but when I edit a javascript file, I periodically get the message "Request failed:  Could not start tern server."

I found that I needed to clone the tern repository to a location on my machine, install its dependencies with "npm install" and then change the tern-command variable to contain the path to my tern installation binary.

Is this correct? If so, I would be happy to change the javascript layer documentation to reflect this, but I'm not sure if I've missed something.

**Comment by geksilla** [comment]
Hi @Devagamster, you should install [node.js](https://nodejs.org/download/) for windows. Then install tern globally using node.js package manager called npm. To install tern execute ```npm install -g tern```.

**Comment by Devagamster** [comment]
I have done that. The issue is that the documentation doesn't tell you to anywhere

**Comment by syl20bnr** [comment]
@Devagamster sure feel free to update the doc.

**Comment by Devagamster** [comment]
Oh dang. Looks like it was updated in the develop branch, just not release :) nevermind.
