### ISSUE TITLE
spacemacs writing corrupt recentf file resulting in void-variables

### ISSUE THREAD

**Issue by tixthea** [syl20bnr/spacemacs#14586]
#### Description :octocat:
spacemacs writing garbage recentf files with extra spaces in function names and extra line feeds in comments.

I have already deleted .emacs.d and recloned.

#### Reproduction guide :beetle:
- Start Emacs
- open a file with :e ~/.spacemacs
- edit file and save
- quit emacs/spacemacs
- reopen emacs/spacemacs

*Observed behaviour:* :eyes: :broken_heart:

Writes garbage file like this:

```
;;;
Automatically generated by ‘recentf’ on Thu Apr  1 11: 55: 03 2021.

(setq recentf - list 'nil)

 (setq recentf - filter - changer - current 'nil)

  
  ;; Local Variables:
  ;; coding: utf - 8 - emacs
  ;; End:
```

resulting in attached stack trace.

*Expected behaviour:* :heart: :smile:

* loads and saves correctly formatted recentf

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. aa0c030)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml search-engine
     (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-enable-company-help-tooltip t auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil)
     better-defaults
     (git :variables git-enable-github-support t)
     colors github markdown org syntax-checking
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "/bin/bash")
     shell-scripts emacs-lisp python gtags html latex deft c-c++)
```
- System configuration features: XAW3D XPM JPEG PNG IMAGEMAGICK NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB LUCID X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-variable Automatically)
  eval-buffer(#<buffer  *load*> nil "/home/thea/.emacs.d/.cache/recentf" nil t)  ; Reading at buffer position 18
  load-with-code-conversion("/home/thea/.emacs.d/.cache/recentf" "/home/thea/.emacs.d/.cache/recentf" nil nil)
  #<subr load>("/home/thea/.emacs.d/.cache/recentf" nil nil t nil)
  apply(#<subr load> ("/home/thea/.emacs.d/.cache/recentf" nil nil t))
  load("/home/thea/.emacs.d/.cache/recentf" nil nil t)
  load-file("/home/thea/.emacs.d/.cache/recentf")
  recentf-load-list()
  recentf-mode()
  (if recentf-mode nil (recentf-mode) (recentf-track-opened-file))
  (lambda nil (if recentf-mode nil (recentf-mode) (recentf-track-opened-file)))()
  run-hooks(find-file-hook)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer .spacemacs> "~/.spacemacs" nil nil "~/dotfiles/dot_spacemacs" (51931733 2081))
  find-file-noselect("~/.spacemacs" nil nil nil)
  find-file("~/.spacemacs")
  evil-edit("~/.spacemacs" nil)
  funcall-i
```

**Comment by dalanicolai** [comment]
Did you also try to startup with a clean dotfile? Just move/backup your dotfile and restart Spacemacs (and probably also delete that `recentf` cache file)

**Comment by tixthea** [comment]
Clean dotfile works. Been using the same dotfile for 1+ yrs without problems.  I swtiched from master to development branch and this started happening.  I guess it's time to eliminate packages 1 by 1 to see what's causing the problem.

**Comment by tixthea** [comment]
Culprit found - this block was doing strange things to recentf.   Why would this run when it's specifically hooked to a different mode than lisp?

```
1091 ;;;;;;;;;;;;;;;;;;;;;;;;;
1092 ;; astyle
1093 ;;;;;;;;;;;;;;;;;;;;;;;;
1094 (defun astyle-this-buffer ()
1095   "Use astyle command to auto format c/c++ code."
1096   (interactive)
1097   (setq temp-point (point))
1098   (shell-command-on-region (point-min) (point-max)
1099                            "/usr/bin/astyle"
1100                            (current-buffer) t
1101                            (get-buffer-create "*Astyle Errors*") t)
1102   (goto-char temp-point)
1103   (recenter))
1104
1105 (defun astyle-before-save ()
1106   "Auto styling before saving."
1107   (interactive)
1108   (when (member major-mode '(cc-mode c++-mode c-mode))
1109        (astyle-this-buffer)))
1110
1111 (add-hook 'c-mode-common-hook (lambda () (add-hook 'before-save-hook 'astyle-before-save)))
```

**Comment by tixthea** [comment]
Line 1111 above should read:
```
(add-hook 'c-mode-hook (lambda () (add-hook 'before-save-hook 'astyle-before-save)))
```
Which fixes this problem.  Closing this ticket.

**Comment by tixthea** [comment]
Well, this does not solve the issue at all.


Any idea why recentf should be considered a c-mode file?

**Comment by alexey0308** [comment]
> Well, this does not solve the issue at all.
> 
> Any idea why recentf should be considered a c-mode file?

very improbable, but [local variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html) can have such an effect.

**Comment by tixthea** [comment]
I checked that in recentf and also added a line to the file to force lisp mode. However, this did not work either.  I loaded up vanilla spacemacs and recentf opens in fundamental mode. Some package or config is setting recentf as C mode.  I wonder if there is a default startup mode setting?

**Comment by alexey0308** [comment]
yes, there is one for default mode, which can be set with `(setq-default major-mode 'your-mode)`.
Also you can check its default value with `(default-value 'major-mode)`.

I don't think, that it the following is the reason, but just another way emacs selects modes are variables
auto-mode-alist, magic-mode-alist ans the like: they use filename regexp. But here the file is not opened, 
it is written directly from temporary buffer, as I see in the source code:
<details>
```
(defun recentf-save-list ()
  "Save the recent list.
Write data into the file specified by `recentf-save-file'."
  (interactive)
  (condition-case error
      (with-temp-buffer
        (erase-buffer)
        (set-buffer-file-coding-system recentf-save-file-coding-system)
        (insert (format-message recentf-save-file-header
				(current-time-string)))
        (recentf-dump-variable 'recentf-list recentf-max-saved-items)
        (recentf-dump-variable 'recentf-filter-changer-current)
        (insert "\n\n;; Local Variables:\n"
                (format ";; coding: %s\n" recentf-save-file-coding-system)
                ";; End:\n")
        (write-region (point-min) (point-max)
                      (expand-file-name recentf-save-file))
        (when recentf-save-file-modes
          (set-file-modes recentf-save-file recentf-save-file-modes))
        nil)
    (error
     (warn "recentf mode: %s" (error-message-string error)))))
```
</details>

**Comment by tixthea** [comment]
This problem is also affecting gtags as I have a gtags autogeneration set for c-mode

**Comment by tixthea** [comment]
more hints:

```
  run-mode-hooks(c-mode-hook)
  c-mode()
  set-auto-mode-0(c-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(t t)
  find-file-noselect-1(#<buffer recentf> "~/.emacs.d/.cache/recentf" nil nil "~/.emacs.d/.cache/recentf" nil)
  find-file-noselect("~/.emacs.d/.cache/recentf" nil nil nil)
  find-file("~/.emacs.d/.cache/recentf")
  evil-edit("~/.emacs.d/.cache/recentf" nil)
  funcall-interactively(evil-edit "~/.emacs.d/.cache/recentf" nil)
  call-interactively(evil-edit)
  evil-ex-call-command(nil #("e" 0 1 (ex-index 1)) #("~/.emacs.d/.cache/recentf" 0 1 (ex-index 3) 1 2 (ex-index 4) 2 3 (ex-index 5) 3 4 (ex-index 6) 4 5 (ex-index 7) 5 6 (ex-index 8) 6 7 (ex-index 9) 7 8 (ex-index 10) 8 9 (ex-index 11) 9 10 (ex-index 12) 10 11 (ex-index 13) 11 12 (ex-index 14) 12 13 (ex-index 15) 13 14 (ex-index 16) 14 15 (ex-index 17) 15 16 (ex-index 18) ...))
  eval((evil-ex-call-command nil #("e" 0 1 (ex-index 1)) #("~/.emacs.d/.cache/recentf" 0 1 (ex-index 3) 1 2 (ex-index 4) 2 3 (ex-index 5) 3 4 (ex-index 6) 4 5 (ex-index 7) 5 6 (ex-index 8) 6 7 (ex-index 9) 7 8 (ex-index 10) 8 9 (ex-index 11) 9 10 (ex-index 12) 10 11 (ex-index 13) 11 12 (ex-index 14) 12 13 (ex-index 15) 13 14 (ex-index 16) 14 15 (ex-index 17) 15 16 (ex-index 18) ...)))
  evil-ex-execute(#("e ~/.emacs.d/.cache/recentf" 0 1 (ex-index 1) 1 2 (ex-index 2) 2 3 (ex-index 3) 3 4 (ex-index 4) 4 5 (ex-index 5) 5 6 (ex-index 6) 6 7 (ex-index 7) 7 8 (ex-index 8) 8 9 (ex-index 9) 9 10 (ex-index 10) 10 11 (ex-index 11) 11 12 (ex-index 12) 12 13 (ex-index 13) 13 14 (ex-index 14) 14 15 (ex-index 15) 15 16 (ex-index 16) ...))
  evil-ex(nil)
  funcall-interactively(evil-ex nil)
  call-interactively(evil-ex nil nil)
  command-execute(evil-ex)
```

set-auto-mode is trying to say this is a c-mode file.....

**Comment by alexey0308** [comment]
But is astyle included in any layer? I can not find this package within the spacemacs repository.

**Comment by tixthea** [comment]
astyle is an external program that formats c/c++ code to whatever standards.  I am reformatting c/c++ files using this external tool by hooking c-mode/c++-mode.  For some reason with my config (which hasn't changed for years) after switching from master to develop, `set-auto-mode` thinks that recentf is c-mode.

**Comment by tixthea** [comment]
As a workaround, I added this to the top of the `auto-mode-alist`:

```
 ("recentf" . lisp-mode)
```

And now when loading the file the major mode is correctly indentified, which solves the problem.

**Comment by agenbite** [comment]
I'm getting a similar behaviour where spacemacs writes parts of the home buffer (including recent files list) into opened org-mode files at startup. Very annoying.

**Comment by dalanicolai** [comment]
@tixthea A little late response, but I only notice this now. As far as I understand, you are globally adding the `astyle-before-save` function to the `before-save-hook`. I guess you want it to be local in the `c-mode` buffer, so you should add a local hook as follows:
```
(add-hook 'c-mode-common-hook (lambda () (add-hook 'before-save-hook 'astyle-before-save nil t)))
```
