### ISSUE TITLE
Slow Spacemacs (describe commands + find-file + M-x)

### ISSUE THREAD

**Issue by nc10** [syl20bnr/spacemacs#14585]
Hi all,

I have recently switched from stock Emacs to Spacemacs. I am experiencing quite a noticeable delay between when I initiate a command and when I actually see the output. This generally applies to help commands (describe mode, describe function, describe variable), opening files (this could be because of auto-loading), finding files (Spc f f), and M-x command listing (Spc Spc). I switched to Ivy and it helped with finding files and M-x command listing, but the help commands are extremely slow (describe mode being the slowest). Here is some information that you find relevant:

Emacs version: 28.0.50
OS: macOS 10.15.7
Spacemacs: 0.300.0 (develop branch)
Layers: helpful

I am wondering if anybody has any suggestions about how I can determine the cause of this slowness. The stock Emacs is pretty fast. Also, Spacemacs is responsive enough when it comes to usual editing. 

Many thanks,

**Comment by nc10** [comment]
Hi all,

I did an experiment and came up with the following result:

Two identical machines (macOS 10.15.7)
Two identical .spacemacs
Two identical spacemacs (0.300.0, develop branch)

The only difference between these two machines is the version of Emacs. Machine 1 is running 28.0.50; Machine 2 is running 27.1.91

Here is the output of the profiler when I run it from my .spacemacs file execute Spc h d m and the get the report. 

Machine 1 (Emacs 28.0.50):

        1364  78% - command-execute
        1364  78%  - call-interactively
        1322  76%   - funcall-interactively
        1245  71%    - spacemacs/describe-mode
        1245  71%     - call-interactively
        1245  71%      - funcall-interactively
        1245  71%       - describe-mode
        1177  68%        + help-fns--list-local-commands
          29   1%        + help-fns-short-filename
          11   0%        + temp-buffer-window-show
           8   0%        + help-window-setup
           4   0%        + documentation
           1   0%          find-lisp-object-file-name
          76   4%    + evil-mouse-drag-region
           1   0%    + evil-next-line
          42   2%   + byte-code
         133   7% + timer-event-handler
         119   6% + ...
         100   5% + redisplay_internal (C function)
          10   0%   tooltip-show-help-non-mode
           2   0%   flyspell-post-command-hook
           1   0% + winner-save-old-configurations
           1   0% + which-key--hide-popup

Machine 2 (Emacs 27.1.91):

+ timer-event-handler                                             236  37%
+ redisplay_internal (C function)                            189  30%
+ ...                                                                             102  16%
- command-execute                                                97  15%
 - call-interactively                                                   97  15%
  - funcall-interactively                                            68  10%
   - spacemacs/describe-mode                              30   4%
    - call-interactively                                                30   4%
     - funcall-interactively                                         30   4%
      - describe-mode                                                30   4%
       + temp-buffer-window-show                            9   1%
       + help-window-setup                                         7   1%
       + documentation                                                 1   0%
         help-split-fundoc                                              1   0%
       + fill-paragraph                                                   1   0%
         find-lisp-object-file-name                               1   0%
   + profiler-report                                                     13   2%
   + winum-select-window-3                                   10   1%
   + evil-previous-line                                                 9   1%
   + evil-next-line                                                        3   0%
   + quit-window                                                         2   0%
   + profiler-report-toggle-entry                              1   0%
  + byte-code                                                             29   4%
+ evil-repeat-pre-hook                                             2   0%
+ evil--jump-hook                                                     1   0%
  clear-minibuffer-message                                      1   0%
+ which-key--hide-popup                                        1   0%
+ evil-escape-pre-command-hook                         1   0%

It appears that "help-fns--list-local-commands" is taking most of the execution time (it takes about 3 sec). On Machine 2 the result of describe mode command is displayed immediately. Any thoughts on this?

Many thanks

**Comment by nc10** [comment]
Here is Machine 1 (Emacs 28.0.50) output for the same steps when it is ran via -q flag

         574  81% - command-execute
         574  81%  - call-interactively
         361  51%   - byte-code
         361  51%    - read-extended-command
         361  51%     - completing-read
         361  51%      - completing-read-default
         211  30%       - read-from-minibuffer
           8   1%        - command-execute
           8   1%         - call-interactively
           8   1%          - funcall-interactively
           8   1%           - minibuffer-complete
           8   1%            - completion-in-region
           8   1%             - completion--in-region
           8   1%              + #<compiled -0x1b5eafd2e545762>
           1   0%          clear-minibuffer-message
         213  30%   - funcall-interactively
         115  16%    - execute-extended-command
          39   5%     + execute-extended-command--shorter
          31   4%     + command-execute
          27   3%     + sit-for
           1   0%       #<compiled -0xc7ab989cfa4ec75>
          87  12%    - describe-mode
          72  10%     + help-fns--list-local-commands
           4   0%     + help-fns-short-filename
           4   0%     + help-window-setup
           1   0%     + fill-paragraph
           1   0%     + temp-buffer-window-show
          10   1%    + next-line
           1   0%    + profiler-report
         106  15% + ...
          13   1% + mouse--click-1-maybe-follows-link
           5   0% + #<compiled -0x2223e40b2632199>
           2   0% + redisplay_internal (C function)
           1   0%   clear-minibuffer-message

**Comment by lebensterben** [comment]
You should report this upstream:

https://github.com/emacs-mirror/emacs/blob/a9645338e4109570ec64c902526d028c75e4369f/lisp/help-fns.el#L1839

**Comment by nc10** [comment]
Thanks. I just did.

**Comment by nc10** [comment]
Apparently, this is a known bug at the upstream (bug#45379). I confirm that Emacs 27 works just fine. So there is nothing to do at this point.
