### ISSUE TITLE
emacs 27 hangs on first use of helm after startup

### ISSUE THREAD

**Issue by emacs18** [syl20bnr/spacemacs#14593]
I use my build of emacs-27 (built few days ago) on ubuntu 20.04.

After starting spacemacs, any helm related operation such as `M-x` hangs emacs so that I'm forced to hit `C-g` to wake it up. A workaround is for me to set `helm--tramp-archive-maybe-loaded` to `t` in my config file to disable code added via <https://github.com/emacs-helm/helm/commit/2ca62b0384727338c2a7dd90a591fcac26d86a03> 16 days ago.

Following is the stack trace obtained by hitting `C-g` with `debug-on-quit` set to `t`.

    dbus-call-method(:system "org.freedesktop.Avahi" "/org/freedesktop/DBus" "org.freedesktop.DBus.Peer" "Ping")
    dbus-ping(:system "org.freedesktop.Avahi")
    zeroconf-init("local")
    byte-code("...
    #<subr require>(tramp-gvfs)
    apply(#<subr require> tramp-gvfs)
    require(tramp-gvfs)
    byte-code("...
    #<subr require>(tramp-archive nil t)
    apply(#<subr require> (tramp-archive nil t))
    require(tramp-archive nil t)
    helm--maybe-load-tramp-archive()
    helm-internal((((name . "Emacs Commands history") (candidates . #f(compiled-function () #<bytecode 0x1575c50a04b5>)) ...
    apply(helm-internal ((((name . "Emacs Commands history") (candidates . #f(compiled-function () #<bytecode 0x1575c50a04b5>)) ...
    helm((((name . "Emacs Commands history") (candidates . #f(compiled-function () #<bytecode 0x1575c50a04b5>)) ...
    apply(helm ((((name . "Emacs Commands history") (candidates . #f(compiled-function () #<bytecode 0x1575c50a04b5>)) ...
    helm(:sources (((name . "Emacs Commands history") (candidates . #f(compiled-function () #<bytecode 0x1575c50a04b5>)) ...
    helm-M-x-read-extended-command([icomplete-fido-delete-char js-jsx-regexps diary-included-files eval-sexp-fu-flash-error ...
    helm-M-x(nil)
    funcall-interactively(helm-M-x nil)
    call-interactively(helm-M-x)
    (let ((completion-styles completion-styles)) (add-to-list 'completion-styles (if (version< emacs-version "27") 'helm-flex 'flex) t) (call-interactively 'helm-M-x))
    spacemacs/helm-M-x-fuzzy-matching()
    funcall-interactively(spacemacs/helm-M-x-fuzzy-matching)
    call-interactively(spacemacs/helm-M-x-fuzzy-matching nil nil)
    command-execute(spacemacs/helm-M-x-fuzzy-matching)

The hang is observed only on first use of helm.  Once `C-g` wakes up emacs, then subsequent use of helm does not hang emacs.

Perhaps this bug report should have been made to upstream, i.e., at <https://github.com/emacs-helm/helm/>

I am hesitant to submit bug reports to helm not knowing whether that is appropriate.

**Comment by lebensterben** [comment]
you can report it to upstream and keep this open. if upstream accepts the bug report you may close it here.

**Comment by emacs18** [comment]
I don't observe the problem anymore.
