### ISSUE TITLE
Autocompletion not working for python

### ISSUE THREAD

**Issue by dtransposed** [syl20bnr/spacemacs#14608]
**Description**

Autocompletion is not working for a code written in a script, however it works for Inferior Python.

**Reproduction guide**

- Start Emacs
- Open new python script(```.py```)
- Activate virtual environment, which contains the correct module (```pyenv-mode-set```, tested module is ```numpy```, although I tried also with ```time```)
- Write a sample python script:
  ```
  import numpy as np
  a = np.
  ```
- Try to get a completion list (hit TAB)

**Observed behaviour**
Completions do not work. ```company-diag``` returns the log:
<img width="802" alt="Zrzut ekranu 2021-04-6 o 16 12 26" src="https://user-images.githubusercontent.com/28805077/113724775-fa44d880-96f2-11eb-9466-d54a7481376a.png">

However, when performing same import and autocompletion in inferior mode (```run-python```), autocompletion works as expected. ```company-diag``` returns the log:
<img width="802" alt="Zrzut ekranu 2021-04-6 o 16 12 00" src="https://user-images.githubusercontent.com/28805077/113726306-67a53900-96f4-11eb-820e-25c0f0053f04.png">

**System Info**

OS: darwin20.1.0
Emacs: 27.1
Spacemacs: 0.300.0
Spacemacs branch: 
```
commit df8249a0522c2bda83cef476d41d55de3cfbec0f (HEAD -> develop, origin/develop, origin/HEAD)
Author: JAremko <w3techplayground@gmail.com>
Date:   Mon Apr 5 06:15:21 2021 +0300
```
Distribution: spacemacs
Editing style: vim
Completion: helm
Layers:
<img width="554" alt="Zrzut ekranu 2021-04-6 o 16 16 41" src="https://user-images.githubusercontent.com/28805077/113725324-7e975b80-96f3-11eb-9ea9-76bfcc310140.png">

I have tried solutions listed in following issues:
https://github.com/syl20bnr/spacemacs/issues/11785
https://github.com/syl20bnr/spacemacs/issues/10638

Namely:
1. Putting this at your dotfile user-config:
```
(eval-after-load "company"
 '(add-to-list 'company-backends 'company-anaconda))
```
2. Adding

```dotspacemacs-additional-packages '(jedi)```

Nothing works for me so far.

**Comment by lebensterben** [comment]
not related, but this should be the example for other bug reports. it's well described.

**Comment by dtransposed** [comment]
I have noticed super interesting thing. 
Every time I run: ```pip install --upgrade jedi json-rpc service_factory``` in the peen environment, the autocompletion starts suddenly working! 
Then I restart emacs and autocompletion breaks! I run the ```pip install...``` again and things are working once again.
This is weird.

@lebensterben Thank you!

**Comment by lebensterben** [comment]
Do you have virtual environment?

**Comment by dtransposed** [comment]
Yes. I am using pyenv. 
For the purposes of this investigation I have created new environment ```testenv```
1. I open emacs.
2. Before I open any file I activate this environment through ```pyenv-mode-set```.
3. When I edit the file I can see that the name of virtual environment is present on the power bar.
4. ```pip install --upgrade jedi json-rpc service_factory``` is being run inside this virtual environment.

**Comment by alexey0308** [comment]
@dtransposed you use anaconda backend, which requires inferior python buffer created for auto-completion.
Hence, first C-c C-p, then everything should work.

**Comment by dtransposed** [comment]
@alexey0308 Thank you! It works like charm! Could you explain why this is the case? Do other backends have different behaviour?

**Comment by lebensterben** [comment]
https://github.com/syl20bnr/spacemacs/blob/3371a8220c8e48503dc6dd4e2d6ac532ba9946ad/layers/%2Blang/python/packages.el#L97-L109

Line 102 probably need to be changed to `:modes python-mode inferior-python-mode` for `anaconda` backend.

**Comment by alexey0308** [comment]
LSP starts its server automatically in the background, but you need to restart it if you activate the environment, so it catches up with the new configuration.
I don't use anaconda anymore and I don't remember, where actually I read, that one needs to have a python process for anaconda to work. Maybe check the source code or docs or take it as a folklore knowledge :)

**Comment by lebensterben** [comment]
But it's actually handled here:
https://github.com/syl20bnr/spacemacs/blob/3371a8220c8e48503dc6dd4e2d6ac532ba9946ad/layers/%2Blang/python/funcs.el#L64-L71

**Comment by lebensterben** [comment]
(If we drop support of all non-lsp backends, life would be much easier for all of us)

**Comment by alexey0308** [comment]
> https://github.com/syl20bnr/spacemacs/blob/3371a8220c8e48503dc6dd4e2d6ac532ba9946ad/layers/%2Blang/python/packages.el#L97-L109
> 
> Line 102 probably need to be changed to `:modes python-mode inferior-python-mode` for `anaconda` backend.

@lebensterben this is for inferior buffer only: it is always on anaconda backend, regardless of lsp or not for the python-mode.
For python-mode, you already found anaconda configuration in your second message.

**Comment by alexey0308** [comment]
> (If we drop support of all non-lsp backends, life would be much easier for all of us)

Anaconda can work with tramp AFAIK, I don't know if lsp as well?

**Comment by lebensterben** [comment]
> Anaconda can work with tramp AFAIK, I don't know if lsp as well?

A valid point. Setting up LSP over remote connection is doable, and I've actually seen someone mentioned this a few days ago. But it requires some setups.

See https://emacs-lsp.github.io/lsp-mode/page/remote/

But I really wish we can drop non-lsp support, for its many benefits:
- There are too much code just to deal with which backend the user is using, which makes Spacemacs bloated.
- With only LSP, a large part of layer configurations would be similar. And it's possible for us to abstract common setup routines out.
- Everything is handled by either LSP (and lsp-MAJOR-MODE), or a minor mode. We no longer needs to worry about key bindings collisions in many cases, since we don't need to maintain two sets of functions for the same functionality.

**Comment by alexey0308** [comment]
I understand, it's more work to support it, especially when there is no dedicated maintainer for every layer.
But it's rather a political decision: you see people using anaconda for some reason, or e.g. I use ess because I like to have completion based on the inferior buffer state as well, and lsp infers only based on the code base, right?
Trade-off between maintaining and users ¯\_(ツ)_/¯

**Comment by smile13241324** [comment]
One point against LSP is that it normally takes much more system load than traditional emacs modes. Still the ecosystem definitely goes into the direction of LSP. I dimly remember we already have layers supporting only LSP right now.

**Comment by lebensterben** [comment]
Please retry with one of the LSP backend.
