### ISSUE TITLE
The gpg keys in core/gnupg is expired

### ISSUE THREAD

**Issue by monwarez** [syl20bnr/spacemacs#14607]
#### Description :octocat:
When extracting the spacelpa repository, the archive cannot be verified since the gpg key is expired

#### Reproduction guide :beetle:
- Remove `$HOME/.emacs.d/.cache/stable-elpa`
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
There is a warning about not able to verify the spacelpa archive

*Expected behaviour:* :heart: :smile:
Emacs should be able to verify the signature

#### System Info :computer:
- OS: berkeley-unix
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. eec5ba657)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript java lua markdown python yaml meson html helm latex bibtex auto-completion emacs-lisp git dap go csharp markdown julia gpu org syntax-checking cmake lsp rust c-c++ semantic cscope erc xkcd games version-control themes-megapack plantuml treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
@syl20bnr 
Can we upgrade the key?

**Comment by monwarez** [comment]
Still an issue
