### ISSUE TITLE
vim layer key binding of "J" in dired mode

### ISSUE THREAD

**Issue by wztdream** [syl20bnr/spacemacs#14614]
In vim layer the "J" was bind to `dired-go-to-file` but this function is weak, it can only jump to the lines in dired buffer, can not jump to sub directory.
I use ivy layer, after press "J" in dired mode, the ivy completion works fine for the files in sub directory, but after press enter nothing happens, this is wired and it is due to the limited function of dired-go-to-file.
I also noticed that in in **spacemacs-bootstrap** layer, "J" was remaped to other function, and the reason is also the limited function of dired-go-to-file, so I think it is better to remap it to `spacemacs/counsel-find-file` which is more powerful and works fine with ivy
```
  ;; replace `dired-goto-file' with `helm-find-files', since `helm-find-files'
  ;; can do the same thing and with fuzzy matching and other features.
  (with-eval-after-load 'dired
    (evil-define-key 'normal dired-mode-map "J" 'spacemacs/helm-find-files)
    (define-key dired-mode-map "j" 'spacemacs/helm-find-files)
```

**Comment by smile13241324** [comment]
Fix is merged care to have another look @wztdream?
