### ISSUE TITLE
spacemacs themes does not highlight jsx tags , 

### ISSUE THREAD

**Issue by TPLinux** [syl20bnr/spacemacs#14620]
Hi guys , im trying to setup a good theme for my eyes 

but when i edit jsx codes the theme is annoying , 
 when open js files there is no highlight on jsx tags:

![1](https://user-images.githubusercontent.com/18364440/114267406-a9d3c080-99fb-11eb-86c8-282d1382f5d7.png)

but when i run` M-x rjsx-mode` the highlight works ,

i want to automatically run rjsx when ever i open js files

i tried to add this at the end of the `.spacemacs` file 

`(add-to-list 'auto-mode-alist '("\\.js\\'" . rjsx-mode))`

![2](https://user-images.githubusercontent.com/18364440/114267408-ab04ed80-99fb-11eb-9cba-b29e1bf4ee5e.png)

thanks in advance.

**Comment by jjforsythe** [comment]
`(add-to-list 'auto-mode-alist '("\\.js\\'" . rjsx-mode))` works for me, perhaps you have not put it inside `dotspacemacs/user-config`?

**Comment by TPLinux** [comment]
> `(add-to-list 'auto-mode-alist '("\\.js\\'" . rjsx-mode))` works for me, perhaps you have not put it inside `dotspacemacs/user-config`?

I tried to put it in config still not working

**Comment by TPLinux** [comment]
> `(add-to-list 'auto-mode-alist '("\\.js\\'" . rjsx-mode))` works for me, perhaps you have not put it inside `dotspacemacs/user-config`?

ok , i rechecked my init file, and this line was duplicated in `spacemacs/user-init`

`(add-to-list 'auto-mode-alist '("\\.js\\'" . rjsx-mode))`


thank you @jjforsythe

your comment worked for me, im gonna close this.
