### ISSUE TITLE
[bug][regression] press "enter" or mouse-1 in org-mode will enter "bat-mode"

### ISSUE THREAD

**Issue by sunlin7** [syl20bnr/spacemacs#14626]
Press "enter" or mouse-1 in org-mode will enter "bat-mode", it's an regression issue.
Enable both `org` and `windows-scripts` in configuration layer, then open an `*.org` file, press `enter` will reproduce the issue.

**Comment by lebensterben** [comment]
https://github.com/syl20bnr/spacemacs/blob/66d774cd67258bb08ca7207a09deb9fedad5640e/layers/%2Blang/windows-scripts/packages.el#L38

Removing this line should fix it.

**Comment by sunlin7** [comment]
It's work in my local now, thanks.

Look forward the solution is available in the repo.

**Comment by smile13241324** [comment]
Merged the fix, please have another go @sunlin7.

**Comment by sunlin7** [comment]
It's work now, thank you all guys.
