### ISSUE TITLE
`SPC f f` on new file in non-existent directory results in read-only buffer

### ISSUE THREAD

**Issue by timor** [syl20bnr/spacemacs#14632]
#### Description :octocat:
Since #14038, using `SPC f f` to open a file in a non-existent directory will make the buffer read-only.

Note that `find-file` and `counsel-find-file` are not affected.

I suspect the reason is that `spacemacs//counsel-find-file-action`, which is basically a re-implementation of `counsel-find-file-action`, uses `(switch-to-buffer (find-file-noselect (expand-file-name x ivy--directory) t nil t))` instead of `(find-file (expand-file-name x ivy--directory))`.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC f f`, `/nonexistent/directory/file.txt`

*Observed behaviour:* :eyes: :broken_heart:

Buffer is read-only.

*Expected behaviour:* :heart: :smile:

Buffer is not read-only.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: custom(based on develop) (base rev. aa0c0301e2dc5751690518372ec4c0329f60420f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(octave clojure ibuffer javascript json systemd go csv html perl5 ivy
        (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
        bibtex emacs-lisp ess git markdown
        (org :variables org-want-todo-bindings t org-enable-reveal-js-support t)
        spell-checking syntax-checking nixos
        exwm
        github
        erc
        c-c++ python common-lisp latex notmuch factor treemacs outshine
        spacemacs-modeline)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
```

**Comment by dalanicolai** [comment]
That's funny... I was annoyed by this behavior myself, but I did not realize that that PR caused it. B.t.w. it is true that that function is basically a reimplementation of `counsel-find-file-action`, and the PR message explains this is done to suppress the Emacs warning message (Spacemacs has its own warning mechanism, and otherwise Spacemacs would warn twice). Anyway, I think this should be considered a bug in Emacs, as the `nowarn` is `t` flag causes the "read-only behavior". Without that flag the file opens in editable mode (as expected). I will create an Emacs bug report, and await the answer. Thanks for reporting and identifying the root cause of the behavior...

**Comment by syl20bnr** [comment]
@dalanicolai If you have reported it upstream, can you post an URL about the ticket ?

**Comment by lebensterben** [comment]
The simple fix is
to set `large-file-warning-threshold` to `dotspacemacs-large-file-size`

**Comment by dalanicolai** [comment]
@syl20bnr Sure, the ticket is [bug#47850](https://lists.gnu.org/archive/cgi-bin/namazu.cgi?query=47850&submit=Search%21&idxname=bug-gnu-emacs&max=20&result=normal&sort=score).
So it has been picked up/fixed already (although I still, for myself, have to make sense of reply)

**Comment by dalanicolai** [comment]
@lebensterben I did not look into it again, and I forgot how it works exactly (and if now it works correctly), but I do remember that  the rationale (for me and probably originally also for the `dotspacemacs-large-file-size` variable) was to keep the `large-file-warning-threshold` intact as a limit for text files, while using `dotspacemacs-large-file-size` for larger files like (files that contain) images.
