### ISSUE TITLE
Latex Preview fails in latest revision of 0.300

### ISSUE THREAD

**Issue by wbmacleod** [syl20bnr/spacemacs#14641]
#### Description :octocat:

latex Preview not longer works with emacs 27.2 on latest development branch.
A march backup of develop branch of .emacs.d works fine.

#### Reproduction guide :beetle:
- Start Emacs
- open latex file
- ,pd

*Observed behaviour:
commandp, function not found

*Expected behaviour:
ask for cache, then preview

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b24fccdbf) this rev works, it is current rev that fails.
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git lsp markdown multiple-cursors org
            (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term)
            (spell-checking :variables enable-flyspell-auto-completion nil)
            spell-checking syntax-checking
            (ess :variables ess-r-backend 'lsp)
            latex bibtex finance)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
You can try `git bisect` to figure out the commit that breaks it.

**Comment by wbmacleod** [comment]
It looks like 85d0aa it good, so it is just after that.  I update
regularly, and use latex daily.  I will tag that version and use it for the
time being.  best b.
W. Bentley MacLeod
New York, New York

**Comment by wbmacleod** [comment]
I used bisect - first time - it is great.  The broken commit is the one
after 85d0aa21, the one that did a core jump change. many thanks b.
W. Bentley MacLeod
New York, New York

**Comment by wbmacleod** [comment]
I noticed several  typos in the comments for the commit f136f465...
W. Bentley MacLeod
New York, New York

**Comment by lebensterben** [comment]
I'm not sure how https://github.com/syl20bnr/spacemacs/commit/f136f465abf599f6869b178e9338c72053444aec affected this.
But I've found how to solve the problem
In a inferior emacs lisp mode
```elisp
(require 'preview)
```
