### ISSUE TITLE
How to correctly version control the .spacemacs file ?

### ISSUE THREAD

**Issue by mrotaru** [syl20bnr/spacemacs#14667]
In .spacemacs, there is this section:

```
;; Do not write anything past this comment. This is where Emacs will
;; auto-generate custom variable definitions.
(defun dotspacemacs/emacs-custom-settings ()
  "Emacs custom settings.
This is an auto-generated function, do not modify its content directly, use
Emacs customize menu instead.
This function is called at the very end of Spacemacs initialization."
```
Is there any way of putting that stuff in a different file, so I can version control the .spacemacs file ? Or is there some workaround I'm not aware of ?

**Comment by sdwolfz** [comment]
https://www.gnu.org/software/emacs/manual/html_node/emacs/Saving-Customizations.html

I have this in my `dotspacemacs/user-init` [config](https://gitlab.com/sdwolfz/dotfiles/-/blob/master/.spacemacs):
```elisp
  (setq custom-file "~/.emacs.d/.cache/.custom-settings")
  (load custom-file)
```
