### ISSUE TITLE
auto-highlight-symbol cannot be configured to automatically highlight symbol at point

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1467]
It seems like in old Spacemacs (long ago) I can do this when we were discussing `highlight-symbol` vs `auto-highlight-symbol`. Now I cannot enable this feature even when `global-auto-highlight-symbol-mode` is enabled.

**Comment by syl20bnr** [comment]
@tuhdo Do you succeed in making it work ?

**Comment by tuhdo** [comment]
Yes I fixed it.
