### ISSUE TITLE
exwm error: void variable list-length

### ISSUE THREAD

**Issue by theophilusx** [syl20bnr/spacemacs#14683]
#### Description :octocat:

exwm layer fails to start. Void symbol error list-length

#### Reproduction guide :beetle:
- add exwm to dotfile layers
- start emacs

alternatively, do the exwm desktop session setup and login to exwm session.

*Observed behaviour:* :eyes: :broken_heart:

Emacs fails to load correctly. Error is due to list-length being a void symbol.

This is caused because the exwm layer requires the list-length function (an alias for cl-list-length which is defined in cl.el).

There is no require in the exwm package file for 'cl, so the definition for cl-list-length is not loaded, nor is the alias 'list-length.

Not sure why cl-list-length is being used rather than just using standard elisp 'length. More generally, not sure if using the 'cl library is really justified. There doesn't seem to be anything much in the layer which could not be done with just basic elisp.

At the very least, a

(require 'cl)

needs to be added to package.el in the exwm layer or the layer needs to be re-factored to depend on core elisp functions rather than the 'cl module.

*Expected behaviour:* :heart: :smile:

Emacs starts and exwm session is run

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1ba93b2b1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-enable-help-tooltip t auto-completion-idle-delay 0.4 auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle)
 (clojure :variables clojure-enable-fancify-symbols t clojure-enable-clj-refactor t clojure-enable-linters 'clj-kondo)
 colors csv
 (elfeed :variables rmh-elfeed-org-files
         (list "~/Documents/org-data/my-feeds.org")
         elfeed-db-directory "~/Dropbox/.elfeed" elfeed-enable-goodies nil)
 emacs-lisp emoji epub eww exwm
 (git :variables git-magit-status-fullscreen t magit-diff-refine-hunk 'all)
 github graphql graphviz
 (html :variables css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t web-fmt-tool 'prettier)
 ivy
 (javascript :variables js2-mode-show-strict-warnings nil javascript-backend 'lsp javascript-lsp-linter nil javascript-fmt-tool 'prettier javascript-fmt-on-save t js2-basic-offset 2 js-indent-level 2 javascript-repl `nodejs js2-include-node-externs t)
 (json :variables json-fmt-tool 'prettier json-fmt-on-save t json-backend 'lsp)
 latex lsp markdown
 (mu4e :variables mu4e-installation-path
       (if
           (spacemacs/system-is-mac)
           "/usr/local/share/emacs/site-lisp/mu/mu4e" "/usr/local/share/emacs/site-lisp/mu4e")
       mu4e-enable-mode-line t)
 multiple-cursors
 (org :variables org-enable-github-support t org-enable-bootstrap-support t org-enable-reveal-js-support t org-enable-roam-support t org-want-todo-bindings t org-enable-org-journal-support t org-projectile-file "TODOs.org")
 prettier react restclient
 (sql :variables sql-capitalize-keywords t)
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 (spacemacs-modeline :variables doom-modeline-major-mode-color-icon t doom-modeline-buffer-file-name-style 'relative-to-project doom-modeline-minor-modes nil)
 spell-checking
 (syntax-checking :variables syntax-checking-use-original-bitmaps nil)
 theming
 (treemacs :variables treemacs-position 'right treemacs-width 25 treemacs-indentation 1 treemacs-use-filewatch-mode t treemacs-use-follow-mode t)
 (unicode-fonts :variables unicode-fonts-enable-ligatures t unicode-fonts-ligature-modes
                '(prog-mode))
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 yaml)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by smile13241324** [comment]
This seems to be gone on develop, just tried starting spacemacs with exwm layer on my linux box and it correctly reached the dashboard. I have also scanned the layer code for `list-length` and noticed it has been removed.

Could you have another try?
