### ISSUE TITLE
`semantic-idle-summary-mode` overwrites micro-state documentation

### ISSUE THREAD

**Issue by kecman** [syl20bnr/spacemacs#1469]
`semantic-idle-summary-mode` overwrites micro-state documentation.  I experience this issue using the C/C++ layer

**Comment by TheBB** [comment]
If you can provide some more details that'd be nice. Which micro-state, and what exactly are you doing to produce the problem?

**Comment by StreakyCobra** [comment]
@kecman Can you give more details about your issue, if it's still happening?

**Comment by kecman** [comment]
Hi sorry, actually I just stopped using semantic and haven't looked since, sorry I can't help!

**Comment by StreakyCobra** [comment]
Hi, thanks for your response! So I'm closing this issue as it's an old one and nobody seems to have encountered this problem. But feel free to open a new one if you start using `semantic` and notice it again :smile:
