### ISSUE TITLE
spacemacs/helm-dir-do-ack not work

### ISSUE THREAD

**Issue by datttnwork7247** [syl20bnr/spacemacs#14702]
#### Description :octocat:
`spacemacs/helm-dir-do-ack` not work

#### Reproduction guide :beetle:
- Setting default search tool for `helm` layer is `ack`
- Start Emacs
- Try: `spacemacs/helm-dir-do-ack`
- Search any string: "test"

*Observed behaviour:* :eyes: :broken_heart:
```
$ Option ignore is ambiguous (ignore-case, ignore-dir, ignore-directory, ignore-file)
$ ack: Invalid option on command line
```

*Expected behaviour:* :heart: :smile:
Showing search results without error

#### System Info :computer:
- OS: darwin
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(multiple-cursors auto-completion treemacs html lux
(c-c++ :variables c-c++-enable-clang-support t)
python emacs-lisp javascript erlang yang cscope
(helm :variables helm-position 'top)
dshell markdown git
(version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left)
 major-modes)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER

#### Backtrace :paw_prints:
```
This seem like `ack' shared construct function with `ag'
but `ack' do not have option `--ignore'.
(defun helm-ag--construct-ignore-option (pattern)
  "Not documented, PATTERN."
  (concat "--ignore=" pattern))
```

**Comment by lebensterben** [comment]
Use rg.

**Comment by datttnwork7247** [comment]
> Use rg.

`ack` work for me now but I have to modified `helm-ag--construct-ignore-option` function.
Or I did not config it right?  I just changed the order of search tools:

```
   ;; List of search tool executable names. Spacemacs uses the first installed
   ;; tool of the list. Supported tools are `rg', `ag', `pt', `ack' and `grep'.
   ;; (default '("rg" "ag" "pt" "ack" "grep"))
   dotspacemacs-search-tools '("ack" "grep" "rg" "ag" "pt")
```

**Comment by lebensterben** [comment]
The point is anything other than rg is slower than it by an order of magnitude.

It doesn't make any sense to fix any bug when the functionality itself doesn't serve any function.

**Comment by datttnwork7247** [comment]
> The point is anything other than rg is slower than it by an order of magnitude.
> 
> It doesn't make any sense to fix any bug when the functionality itself doesn't serve any function.

Not sure if I got your mean correctly. But do you mean it is not a bug? Just use rg instead.

**Comment by lebensterben** [comment]
It is a bug.
What I suggest is to ditch any other search tools because it doesn't worth your time to fix any bug...

**Comment by cheese** [comment]
Ack should be just removed from the default `dotspacemacs-search-tools` if it is not actually working.
