### ISSUE TITLE
Error when initializing haskell-mode

### ISSUE THREAD

**Issue by linhmtran168** [syl20bnr/spacemacs#1471]
After enabling haskell layout in spacemacs, I keep seeing this error when emacs starting
```
An error occurred while initializing haskell-mode (error: (file-error Cannot open
```
I think this is related to the fact that haskell-yas was removed from haskell-mode (https://github.com/haskell/haskell-mode/pull/618)

**Comment by alanz** [comment]
I tried adding `haskell-snippets` to the required package list, but it is not installed.  I ended up getting it to load by commenting out as below

```
(defun haskell/init-haskell-mode ()
  ;; (require 'haskell-yas)
```

But obviously then there are not snippets.

**Comment by syl20bnr** [comment]
Thank you for the report, this is fixed in develop and current release.

**Comment by syl20bnr** [comment]
Seems that there is another issue, I'll look into it this evening.

**Comment by syl20bnr** [comment]
OK should be good now :-)

**Comment by lebensterben** [comment]
I've found a fix for this
```elisp
(defun haskell/post-init-yasnippet ()
  (spacemacs/add-to-hooks 'spacemacs/load-yasnippet
                          '(haskell-mode-hook haskell-literate-mode-hook)))

(defun haskell/init-haskell-snippets ()
  (use-package haskell-snippets
    :defer t
    :hook (yas-minor-mode . haskell-snippets-initialize)))
```
This will be included in a coming PR.
