### ISSUE TITLE
How to disable `completion-at-point` when I press Return key inside a src block of org-mode?

### ISSUE THREAD

**Issue by stskyblade** [syl20bnr/spacemacs#14717]
I was editing a src block of org file. When my cursor is at the last char, a mini buffer of `Helm Completion At Point` will show when I press Return key.

```
    #+begin_src sh
   line1
   line2
    #+end_src
```
Such as put cursor after `line2`, and press Return.

I just want to insert a new line rather than call `completion-at-point`.

**Comment by lebensterben** [comment]
This is a known bug.
