### ISSUE TITLE
helm-locate broken when shell is fish

### ISSUE THREAD

**Issue by 2e0byo** [syl20bnr/spacemacs#14721]
#### Description :octocat:
`helm-locate` appends `^M` to every result, thus failing.

#### Reproduction guide :beetle:
- Start Emacs
- run `helm-locate` or `lazy-helm/helm-locate`

*Observed behaviour:* :eyes: :broken_heart:
Matches as normal but with appended `^M` on every line.  No action works (as the appended `^M` is taken to be part of the path)

*Expected behaviour:* :heart: :smile:
Matches without appended `^M`.

#### System Info :computer:
- OS: gnu/linux (arch)
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3371a8220)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(systemd ocaml csv shell-scripts protobuf rust ess yaml latex
         (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
         better-defaults emacs-lisp git helm lsp markdown multiple-cursors org spell-checking syntax-checking version-control treemacs mu4e
         (python :variables python-backend 'anaconda python-test-runner 'pytest python-formatter 'black python-format-on-save t python-sort-imports-on-save t)
         ranger vue)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

Clearly there is a problem parsing the output.  I'm not sure where the CRs are coming from.  Locale is set correctly:

```bash
$ locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```
```elisp
(locale-info 'codeset)
"UTF-8"
```

`helm-locate-command` is `"locate %s -e -A --regex %s"`.

and lastly, locate runs properly in a shell without any CRs.

Doubtless there's just a problem my end: I doubt this could be reproducible without being already reported.  Would appreciate knowing how to debug further.

**Comment by lebensterben** [comment]
Cannot reproduce this issue.

**Comment by 2e0byo** [comment]
Setting `shell-file-name` to `/bin/bash` fixes the output. I'm not tremendously bothered by using bash in emacs, but does anyone have any ideas why the CRs are coming in when emacs calls fish?

**Comment by 2e0byo** [comment]
Incidentally changing `shell-file-name` also fixes `helm-mu` which was previously showing the same 3 dates as output (?!) despite matching queries correctly.  With bash candidates are properly formatted `mu4e-headers` lines.

Perhaps a note should be added (sorry if I've missed it) on using a POSIX-compliant shell?

**Comment by 2e0byo** [comment]
For completeness (then I'll stop spamming this issue), to reproduce from pristine state:
```bash
mkdir arch # or some other linux
cd arch
vagrant init archlinux/archlinux # substitute as required
vagrant up
vagrant ssh
sudo -i
pacman -Syu
pacman -S emacs git mlocate
updatedb
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
emacs
```
- Then check `SPC f L` : it should work.

```bash
chsh
> /usr/bin/fish
exit
sudo -i
emacs
```
- check `SPC f L` : the CRs (`^M`) appear in every line.
- set `shell-file-name` to `/bin/bash`
- check `SPC f L`: it works

Despite this issue stopping me using two of the commands I use most frequently, I've become addicted to spacemacs in a week and couldn't go back :D

**Comment by lebensterben** [comment]
This is not a bug.

fish is never a login shell.

**Comment by 2e0byo** [comment]
```bash
$ uname -r 
5.11.15-arch1-2
$ cat /etc/shells
# Pathnames of valid login shells.
# See shells(5) for details.

/bin/sh
/bin/bash
/usr/bin/fish
/usr/bin/git-shell
/bin/fish
```
perhaps Arch [isn't standard](https://wiki.archlinux.org/index.php/Fish#Setting_fish_as_default_shell) ;)

But if you meant 'by default' then sure.  And yes, I've my own init scripts etc deliberately in fish.

If anyone else stumbles over this hopefully they'll see this issue.  Thanks again for spacemacs!
