### ISSUE TITLE
Emacs gets stuck on "Indexing layers..." during boot.

### ISSUE THREAD

**Issue by Martinsos** [syl20bnr/spacemacs#14720]
#### Description :octocat:
Forever stuck during boot, on "Indexing layers...".

#### Reproduction guide :beetle:
- Start Emacs, and ~ 1 out of 20 times this will happen.

*Observed behaviour:* :eyes: :broken_heart:
When it gets stuck, I quit re-enter emacs couple of times and then it is ok again.
I also reinstalled emacs completely and it didn't help.
I also installed it on fresh machine for the first time, and again the same problem.
This has been happening for some time now (months, maybe even a year, not sure).

*Expected behaviour:* :heart: :smile:
It should not get stuck.

#### System Info :computer:
- OS: gnu/linux (Archlinux)
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4262e01f1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python windows-scripts vimscript meson ruby docker terraform emoji
        auto-completion better-defaults emacs-lisp git
        (haskell :variables haskell-completion-backend 'dante dante-tap-type-time 1 haskell-indentation-layout-offset 4 haskell-indentation-starter-offset 4 haskell-indentation-left-offset 4 haskell-indentation-where-pre-offset 2 haskell-indentation-where-post-offset 2)
        helm html
        (javascript :variables js2-mode-show-strict-warnings nil js2-basic-offset 2 js-indent-level 2)
        lsp markdown multiple-cursors org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        (syntax-checking :variables syntax-checking-enable-tooltips nil flycheck-display-errors-function #'flycheck-display-error-messages-unless-error-list)
        treemacs version-control yaml cmake)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
I haven't encounter this problem myself. Need more report from community.

In the meantime consider to run Emacs in a daemon.

**Comment by Martinsos** [comment]
I found this one under closed issues https://github.com/syl20bnr/spacemacs/issues/8941 , however it ends up with an ask for possibly re-opening the issue due to the proposed solution not being completely effective.

I had problems running emacs in a daemon so I am keen into investing some more time into trying to fixing this before giving that a go again.

Do you have any suggestion on how to possibly debug this, or what to look into? Why is this "indexing of layers" step and what could be the potential problem here?

**Comment by lebensterben** [comment]
If you mean you cannot run Emacs client as --fg-daemon, just run it as --daemon.

To start debugging, search "indexing of layers" in the source.

**Comment by ksjogo** [comment]
Also started running into this with layers apparently not being loaded, will have a look.

**Comment by alexriabtsev** [comment]
I'm getting the same error when fullscreen mode is enabled.
