### ISSUE TITLE
Properly set up remote language server

### ISSUE THREAD

**Issue by xyderos** [syl20bnr/spacemacs#14724]
I have set up my Golang language server(gopls) and some helper extensions as mentioned in the go layer.

I tried to ssh into a pc via TRAMP and open a file remotely, but I got a message saying that there was no client.

This is the output:

`1. The language you are trying to use does not have built-in support in lsp-mode. You must install the required support manually. Examples of this are lsp-java or lsp-metals.  
2. The language server that you expect to run is not configured to run for major mode go-mode. You may check that by checking the :major-modes that are passed to lsp-register-client.
3. lsp-mode doesn't have any integration for the language behind go-mode. Refer to https://emacs-lsp.github.io/lsp-mode/page/languages and https://langserver.org/ .
4. You are over tramp. In this case follow https://emacs-lsp.github.io/lsp-mode/page/remote/.
5. You have disabled the lsp-mode clients for that file. (Check lsp-enabled-clients and lsp-disabled-clients).
`
I installed gopls on the remote and is it the path, I also make a .dir-locals.el file on the remote.

Since the connection is over TRAMP, I checked the link given but I am fairly new to emacs and I dont know where to place the script given there : 

`(lsp-register-client
    (make-lsp-client :new-connection (lsp-tramp-connection "<binary name (e. g. pyls, rls)>")
                     :major-modes '(python-mode)
                     :remote? t
                     :server-id 'pyls-remote))
` (taken from the link at number 4 from the output snippet).

Is there an easier way to set it up on spacemacs or do I need to follow the emacs-lsp website?

**Comment by lebensterben** [comment]
No.
Consult emacs-mode community for help.

This is not a bug.
