### ISSUE TITLE
Use of <Spc> m h t in haskell mode with ghci-ng

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#1472]
Originally reported this as an issue with ghci-ng integration but it happens without it as well

Currently <spc> m h t shows me no typing information i.e. haskell-process-do-type

Any ideas how to help resolve ?

Thanks

**Comment by fatlazycat** [comment]
The standard bindings of C-c C-t have now stopped working for me as well, any ideas ?

Thanks

**Comment by fatlazycat** [comment]
The underlying code I believe works as I can use in the repl :type-at and give it the location manual to determine the type.

It appears that the location emacs is sending the command is off by two places

λ> :type-at /Users/graham/Development/GitHub/fatlazycat/NICTA-course/src/Course/ListZipper.hs 240 29 240 31 xs

*Course.ListZipper| *Course.ListZipper| *Course.ListZipper| xs :: a -> List a -> List a
λ> :type-at /Users/graham/Development/GitHub/fatlazycat/NICTA-course/src/Course/ListZipper.hs 240 31 240 32 xs

*Course.ListZipper| *Course.ListZipper| *Course.ListZipper| 
<interactive>:1:1-2: Not in scope: ‘xs’

xs starts at column 31 according to the powerline in emacs.

**Comment by fatlazycat** [comment]
<spc> m h t works for ghci-ng but the output is not displayed. 

I can see the results in the haskell-process-log but not in the gutter

**Comment by geraldus** [comment]
@fatlazycat hmm, `M-h` is bound to `mark-paragraph` command in my Emacs installation. What exact command is bound to `M-h t` for you?

**Comment by fatlazycat** [comment]
Spacemacs uses evil and a leader key to try and create a convention, but you can still use the normal emacs commands.

C-c C-t is mapped to ghc-show-type 

<spc> m h t is mapped to haskell-process-do-type

The latter works for showing the type info in the haskell-process-log but doesn't appear in the gutter / tooltip for some reason.

**Comment by geraldus** [comment]
@fatlazycat we want to improve these functions a bit, but there is no strong opinion yet
https://github.com/haskell/haskell-mode/issues/638

**Comment by fatlazycat** [comment]
Yeah that saw that thanks and was going to digest later. At the moment trying to get the results displayed without having to use the haskell-process-log

**Comment by geraldus** [comment]
@fatlazycat oh, thank you! I've just realized that I likely broke it.

**Comment by geraldus** [comment]
@fatlazycat hmm, both `haskell-process-do-type` works for me, it should output result in **ehco-area** or present it in a separate buffer is presentation mode is enabled.
`ghc-show-type` comes from `haskell-ghc` package (and uses **ghc-mod**) IIRC.

**Comment by fatlazycat** [comment]
@geraldus ok thanks, I'll try and do some digging into the spacemacs config to determine why it's not showing. Not that I know a lot about debugging emacs :)

**Comment by geraldus** [comment]
@fatlazycat do you see any errors in messages buffer (you can quickly jump to messages buffer with `C-h e` by default)?

**Comment by fatlazycat** [comment]
@geraldus nothing in the messages buffer

**Comment by geraldus** [comment]
@fatlazycat try `M-x eval-expression RET (haskell-mode-message-line "TEST STRING")`. It should print `"TEST STRING"` in echo area. If that works try to run `M-x eval-expression RET (haskell-process-show-repl-response "putStr \"TEST STRING\"")` and see what happens.

**Comment by fatlazycat** [comment]
Both work fine and print TEST STRING to the echo area.

**Comment by geraldus** [comment]
Hmm, in this case I have no idea why it's not working for `haskell-process-do-type` ):

**Comment by fatlazycat** [comment]
Thanks for looking. Will carrying on trying to find out what's up.

**Comment by fatlazycat** [comment]
@syl20bnr any tips on trying to diagnose this ? Appears the function is called correctly but the result is not displayed in the echo area or any tooltip.

**Comment by fatlazycat** [comment]
Issue in Haskell-mode
