### ISSUE TITLE
`darkokai-mode-line-padding` is set to 1 too late during startup

### ISSUE THREAD

**Issue by Kazark** [syl20bnr/spacemacs#14739]
# Description :octocat:
`darkokai-mode-line-padding` is [set to 1](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+themes/themes-megapack/packages.el#L133) too late during startup if Darkokai is your primary theme, i.e. the one loaded at startup. You will not observe this problem if you switch to Darkokai after the fact; even if you reload the theme, it will fix the rendering.

# Reproduction guide :beetle:
- Start Spacemacs
- `SPC f e d` to open `.spacemacs`
- Add `themes-megapack` to your layers
- `SPC f e R` to install
- Put `darkokai` as the first theme in your `dotspacemacs-themes`
- `SPC q r` to restart

## Observed behaviour :eyes: :broken_heart:
- Observe the extra padding around the modeline
- Invoke Emacs Lisp help on `darkokai-mode-line-padding` and observe that it is
  set to 1 but was originally 8. The extra padding you observe is because it was
  set to 1 too late, after the padding was already set.

## Expected behaviour :heart: :smile:
- No extra fat on the modeline

# System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: keith (rev. 107867c03)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking syntax-checking
          (auto-completion :variables auto-completion-enable-snippets-in-popup t)
          helm helpful
          (org :variables org-todo-dependencies-strategy 'semiauto org-enable-verb-support nil org-enable-appear-support t)
          emoji agda c-c++ emacs-lisp haskell html javascript latex markdown scheme yaml
          (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
          (git :variables evil-collection-magit-use-y-for-yank t evil-collection-magit-want-horizontal-movement t)
          version-control
          (colors :variables colors-colorize-identifiers 'variables)
          themes-megapack
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          search-engine)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES NATIVE_COMP THREADS LIBSYSTEMD JSON PDUMPER LCMS2

**Comment by Kazark** [comment]
Workaround: `(setq darkokai-mode-line-padding 1)` in `dotspacemacs/user-init`.

**Comment by lebensterben** [comment]
what if you rename that function to pre-init*

**Comment by Kazark** [comment]
@lebensterben good idea, but strangely, it does not work. I'm guessing there is some special handling here with themes having to be loaded extra early to render the GUI at all.

**Comment by lebensterben** [comment]
🤔
