### ISSUE TITLE
spacemacs/jump-to-definition in C++ abnormal

### ISSUE THREAD

**Issue by shaynez** [syl20bnr/spacemacs#14740]
From a version in April, spacemacs/jump-to-definition in C++ will invoke two or three function in it. such as:
1. push the key link to spacemacs/jump-to-definition (SPC m g g)
2. helm-gtags will invoke, if C-g to cancel it.
3. helm-xref will present, you have to C-g again.
4. And, which looks like another function also invoke and print some info in min-mode.

**Comment by lebensterben** [comment]
@shaynez 
Could you pin down which commit caused this issue, via `git-bisect`?
