### ISSUE TITLE
Counsel-descbinds(SPC ?) taking long time to load

### ISSUE THREAD

**Issue by perfectayush** [syl20bnr/spacemacs#14769]
#### Description :octocat:
counsel-descbinds(SPC ?) is very slow. It takes more than a minute to load. It didn't
used to be this slow before.

#### Reproduction guide :beetle:
- Start Emacs
- Press `SPC ?` in any buffer

*Observed behaviour:* :eyes: :broken_heart:
counsel-descbind takes more than 1 minute to load. Also noticed in macOS activity
monitor that Emacs utilize 99% cpu while loading it.

I have cpu profiled the function. Please note that I am using the
native-compilation branch, not sure if it's related:

```
       16430  99% - command-execute
       16430  99%  - funcall-interactively
       16425  99%   - counsel-descbinds
       16216  98%    - counsel--descbinds-cands
       16211  98%     - describe-map-tree
          63   0%        describe-map
           1   0%       #<compiled -0x1c1ecf47ae4adeb3>
         200   1%    - ivy-read
         165   1%     - read-from-minibuffer
         114   0%      - timer-event-handler
         114   0%       - apply
         113   0%        - savehist-autosave
         107   0%         - savehist-save
           4   0%            savehist-printable
           2   0%          - run-hooks
           2   0%           - evil--jumps-savehist-sync
           1   0%              #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_10>
           1   0%            #<compiled -0x1c1ecf45ef58d0b3>
           1   0%            prin1
           1   0%        + auto-revert-buffers
           1   0%      + minibuffer-mode
```

*Expected behaviour:* :heart: :smile:
It should load in a few seconds and should not utilize so much cpu.

#### System Info :computer:
- OS: darwin
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 060f55853)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(sql systemd php rust
     (ivy :variables ivy-enable-advanced-buffer-information t)
     (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil)
     (lsp :variables lsp-headerline-breadcrumb-enable t lsp-headerline-breadcrumb-segments
          '(file symbols)
          lsp-lens-enable t lsp-navigation 'peek lsp-ui-remap-xref-keybindings t lsp-ui-remap-xref-keybindings t lsp-ui-doc-enable nil lsp-ui-sideline-enable nil)
     dap evil-snipe
     (vinegar :variables vinegar-reuse-dired-buffer t)
     multiple-cursors html
     (org :variables org-enable-github-support t org-enable-reveal-js-support t)
     plantuml emacs-lisp lua
     (python :variables python-backend 'lsp python-lsp-server 'pyright python-fill-column 80)
     (ruby :variables ruby-version-manager 'chruby ruby-enable-enh-ruby-mode t ruby-backend 'lsp)
     (go :variables go-backend 'lsp)
     (shell :variables shell-default-shell 'eshell)
     clojure julia javascript markdown
     (java :variables java-backend 'lsp)
     (yaml :variables yaml-enable-lsp t)
     ansible docker terraform csv archcode parinfer helpful confluence vagrant git github dash syntax-checking spell-checking better-defaults ibuffer pandoc colors speed-reading command-log restclient version-control treemacs theming ranger gtags nginx slack spotify
     (osx :variables osx-command-as 'super osx-right-command-as 'hyper))
```
- System configuration features: ACL GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS ZLIB

**Comment by lebensterben** [comment]
regardless of whether this is related to native compilation, it looks like an upstream bug, unless you can prove that in vanilla emacs it takes much shorter time.

**Comment by perfectayush** [comment]
> regardless of whether this is related to native compilation, it looks like an upstream bug, unless you can prove that in vanilla emacs it takes much shorter time.

Fair enough, I replicated it with following
```shell
env HOME=vanilla_emacs Emacs 
```
This opened a vanilla emacs. Installed counsel with `M-x package-install counsel`, and then ran `M-x counsel-descbinds`. It loaded within 2 sec.

Here is the profiler report
```
         527  94% - command-execute
         355  63%  - funcall-interactively
         355  63%   - execute-extended-command
         340  61%    - command-execute
         340  61%     - funcall-interactively
         337  60%      - counsel-descbinds
         292  52%       - counsel--descbinds-cands
         291  52%        - describe-map-tree
           7   1%           describe-map
          43   7%       - ivy-read
          21   3%        - read-from-minibuffer
           1   0%         - ivy--queue-exhibit
           1   0%          + ivy--exhibit
           1   0%        - ivy--reset-state
           1   0%         + mapcar
```

**Comment by lebensterben** [comment]
in spacemacs, serialize your keymaps and deserializd them in vanilla emacs.

I think it takes much shorter because you don't have much bindings in vanilla Emacs.

**Comment by perfectayush** [comment]
@lebensterben Upon further inspection the issue seems to be with `describe-buffer-bindings`, which is called by `counsel-descbinds`. This function is taking 42 sec (figured using elp-instrument-function). `counsel-descbinds` is taking the same time . This is a C function defined in keymap.c, so clearly an issue of with emacs itself.

This function inserts all keybindings in a buffer.
On vanilla emacs, it outputs around 2000 lines and takes 2 seconds
On spacemacs with my config, it outputs around 8000 lines and takes 42 seconds.

It seems to be related to how it's iterating the various keybinding maps

**Comment by perfectayush** [comment]
Ok, further inspection suggests that in October 2020, there were changes made to emacs to switch from a C version of underlying function to ELisp implementation of same.  Could be the cause of this regression: https://github.com/emacs-mirror/emacs/commit/8a1441310aa151e739cfed3bd2eff3358edc8001#diff-0da5c85163d4fb20949e0cd2c85abd96519a1d41bfbc15be1c1a12da17850e56

**Comment by lebensterben** [comment]
@perfectayush 
You can build an earlier version of Emacs and retry.
Building Emacs usually takes < 20 minutes.

I'm still not 100% convinced that the regression is caused by the change in implementation. It's possible. But there's still the confounding factor that Spacemacs has much more bindings than vanilla Emacs (about 4 times by line of code).

**Comment by perfectayush** [comment]
@lebensterben I have been able to considerably reduce my counsel-descbinds load time. Turns out following config was slowing it down which I had added to disable mouse.
```elisp
  (global-disable-mouse-mode)
  (mapc #'disable-mouse-in-keymap
        (list evil-motion-state-map
              evil-normal-state-map
              evil-visual-state-map
              evil-insert-state-map))

```
Removing  these lines, counsel-descbinds time reduced from 1min to 11 secs. This is some inoptimal config which is affecting keymap here.

But additionally, I also checked the configuration with Emacs 27, these lines present. And even with these lines present, Emacs 27 the `counsel-descbinds` loads in 0.1 secs. Clearly this is regression in `describe-buffer-bindings` for shifting from C to Elisp for underlying code. I am closing this ticket as it's not related to spacemacs.

**Comment by lebensterben** [comment]
Great, you may consider to report your findings to upstream.

**Comment by perfectayush** [comment]
@lebensterben I have never dealt with Emacs upstream issues. I have no idea where to report, is emacs-devel mailing list the right place?

**Comment by lebensterben** [comment]
that's a good place to start discussing your findings, which seems pretty well-founded to me.

if other mail-list users indeed agree about this, you can then report it to the bug mail-list

https://lists.gnu.org/mailman/listinfo/bug-gnu-emacs

**Comment by perfectayush** [comment]
@lebensterben I was about to report this to bug-gnu-emacs, but did a search for `describe-buffer-bindings` before.

Turns out it was already reported there, way back in December 2020:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2020-12/msg01892.html

Also looks like there is an ongoing effort to fix this per this thread:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-05/msg01099.html

Emacs community rocks. :)
