### ISSUE TITLE
protobuf layer not found

### ISSUE THREAD

**Issue by HiramSilvey** [syl20bnr/spacemacs#14775]
#### Description :octocat:
protobuf layer is not found.

#### Reproduction guide :beetle:
- Add 'protobuf' to dotspacemacs-configuration-layers in ~/.spacemacs.
- Start Emacs
- Observe error: '(Spacemacs) Warning: Unknown layer protobuf declared in dotfile.'

*Observed behaviour:* :eyes: :broken_heart:
'protobuf' layer is not found and editing protobuf files does not invoke any protobuf-mode.

*Expected behaviour:* :heart: :smile:
'protobuf' layer is found and editing .proto files invokes the protobuf-mode.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(python typescript javascript html php shell-scripts markdown go helm auto-completion better-defaults emacs-lisp git org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spell-checking syntax-checking version-control latex rust protobuf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
N/A.
```

**Comment by lebensterben** [comment]
You need to use develop branch.
