### ISSUE TITLE
Unable to select directory when using spacemacs/helm-files-smart-do-search with only grep installed.

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#14779]
#### Description :octocat:

Unable to select directory when using spacemacs/helm-files-smart-do-search with
only grep installed. Instead helm enters the directory (while when e.g. ripgrep
is installed, then a directory can be selected with enter)

#### Reproduction guide :beetle:

- Start Spacemacs (using helm) on a system without any alternative (to grep) search tools
installed
- Try to select a directory by selecting it in helm en pressing RET

*Observed behaviour:* :eyes: :broken_heart:
Helm enters the directory

*Expected behaviour:* :heart: :smile:
Helm starts the grep search in the selected directory

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 80e2fd427)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm lsp markdown multiple-cursors org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs djvu)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
there's no feature parity currently, that's solved by my unfinished PR.

**Comment by smile13241324** [comment]
I need to lookup how registering handlers for helm works to fix this. I wanted to do that anyway to understand why we cannot resume some buffers i.e. swap buffer. But this may take some time.

**Comment by dalanicolai** [comment]
Well, I am usually using Ivy anyway. Also, I guess most users will have some faster search tool installed, so the priority is really low.
But I was installing a fresh Spacemacs in a fresh OS installation, and then I noticed this, so I just reported it.
