### ISSUE TITLE
`evil-magit` Fails to install on startup

### ISSUE THREAD

**Issue by Luctins** [syl20bnr/spacemacs#14776]
#### Description :octocat:

The `evil-magit` is found as a installation candidate on startup, but fails to install. Probably related to it being deprecated and moved to `evil-collection` (according to the [official repo](https://github.com/emacs-evil/evil-magit)).

#### Reproduction guide :beetle:
- Start Emacs.

*Observed behaviour:* :eyes: :broken_heart:
spacemacs finds a new package to install, but fails.

*Expected behaviour:* :heart: :smile:
`evil-magit` would be installed.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. d46eacd83)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(octave rust csv markdown yaml
        (python :variables python-indent 8 python-indent-offset 4 indent-tabs-mode t tab-width 4)
        lua helm auto-completion better-defaults emacs-lisp git org
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: evil-magit@git... [1/1]
Package evil-magit is unavailable. Is the package name misspelled?
```

**Comment by lebensterben** [comment]
Use develop branch.

**Comment by Luctins** [comment]
OK, that solves the issue
