### ISSUE TITLE
Flycheck not automatically enabled when editing LaTeX files?

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#1478]
I have `syntax-checking` and `auctex` layers included. When I edit other files, `flycheck` mostly gets enabled automatically. However when editing LaTeX files, I have to manually enable `flycheck-mode` (using `chktex` as the checker). Is that an intentional design, or did I get some configuration wrong.

**Comment by syl20bnr** [comment]
Thank you for the report, I added support for flycheck in develop branch see https://github.com/syl20bnr/spacemacs/commit/a931de637d3361e8fd9157fb0ba0ec10d3331c89 for more info about how it is done.
