### ISSUE TITLE
where is lsp-pylsp package?

### ISSUE THREAD

**Issue by emacs18** [syl20bnr/spacemacs#14780]
Few days ago f8301056c964fd49a9dfb39151b30c0fd876d2e3 was checked in which introduced `lsp-pylsp` package in this newly added code:

    (require (pcase python-lsp-server
              ('pylsp 'lsp-pylsp)
              ('mspyls 'lsp-python-ms)
              ('pyright 'lsp-pyright)
              (x (user-error "Unknown value for `python-lsp-server': %s" x))))

However I cannot locate where this `lsp-pylsp` package is.  It is not within spacemacs.  I cannot find it in melpa.
Not surprisingly I get the following error when I load any python file:

    File local-variables error: (file-missing Cannot open load file No such file or directory lsp-pylsp)

So where is `lsp-pylsp` package?

**Comment by lebensterben** [comment]
https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-pylsp.el

Update your packages.
