### ISSUE TITLE
Fallback to `dumb-jump-go` for ruby layer no longer works

### ISSUE THREAD

**Issue by gondalez** [syl20bnr/spacemacs#14787]
#### Description :octocat:
I used to be able to configure the ruby layer so that pressing `gd` to goto definition used `dumb-jump-go`.

In the last few months the fallback to `dumb-jump-go` has stopped working.

By the way I have tried LSP but I find it too noisy and resource heavy. I quite like the simplicity of dumb jump.

#### Reproduction guide :beetle:

Set the `ruby-backend` to `robe`:

```lisp
   dotspacemacs-configuration-layers
   '(
     ;; ...
     (ruby :variables
           ruby-test-runner 'rspec
           ruby-backend 'robe 
           ruby-enable-enh-ruby-mode t
           )
     ;; ...
     )
```

- Start Emacs
- open a ruby project
- find a method
- press `gd`
- answer `N` to `No ruby console running. Launch automatically?`

*Observed behaviour:* :eyes: :broken_heart:
Message: `no jump handler was able to find this symbol`

*Expected behaviour:* :heart: :smile:
Jump using `dumb-jump-go` 

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2515f141b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(emacs-lisp git helm markdown multiple-cursors org
            (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'vterm spacemacs-vterm-history-file-location "~/.zsh_history")
            version-control treemacs html yaml ivy
            (javascript :variables javascript-fmt-tool 'prettier)
            (react :variables javascript-fmt-tool 'prettier)
            (javascript :variables javascript-backend 'tern)
            react prettier
            (ruby :variables ruby-test-runner 'rspec ruby-backend nil ruby-enable-enh-ruby-mode t)
            cucumber auto-completion github syntax-checking terraform emoji templates csv python nav-flash docker spacemacs-misc)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP

**Comment by lebensterben** [comment]
can you use git-bisect to pin down the commit that brought this change?

**Comment by lebensterben** [comment]
Also, setting ruby-backend to nil is not a documented usage and is likely to be a hard error in future.

**Comment by gondalez** [comment]
I have confirmed that if I revert as follows (off develop / 2515f141b69ce9fdb75ed27c4088fab3557df86b) then the issue is solved for me.

Also I am able to set `ruby-backend nil` in my config which allows me to jump quickly without having to answer no to the robe prompt as per repro steps.

```diff
modified   layers/+spacemacs/spacemacs-misc/packages.el
@@ -40,9 +40,10 @@
        ((configuration-layer/layer-used-p 'helm)
         (setq dumb-jump-selector 'helm)))
 
-      ;; Enable xref-backend of dumb-jump. It's chosen only when no better
-      ;; options is available
-      (add-hook 'xref-backend-functions #'dumb-jump-xref-activate))))
+      ;; Since it's dumb, we add it to the end of the default jump handlers. At
+      ;; the time of writing it is the only default jump handler. (gtags remains
+      ;; mode-local)
+      (add-to-list 'spacemacs-default-jump-handlers 'dumb-jump-go 'append))))
```

**Comment by smile13241324** [comment]
Hmmm :thinking: I understand that we have removed the obsolete dump-jump interface however shouldn't the xref fallback have the same effect?

@gondalez you should consider setting ruby-backend to robe instead of nil. Otherwise the layer may not be properly configured which could cause various errors. Also if the layer variables are replaced with config vars your config would fail.

**Comment by gondalez** [comment]
Hi @smile13241324 👋 , thanks for looking at this.
>  I understand that we have removed the obsolete dump-jump interface however shouldn't the xref fallback have the same effect?

It doesn't in my experience, because if I answer 'no' to starting the ruby console in robe mode the result is "no jump handler was able to find this symbol". Whereas if I apply the patch above it uses dumb jump and finds the symbol (see gifs below).

> you should consider setting ruby-backend to robe instead of nil

Thanks, yes, I know I should but using `nil` means I don't have to answer 'no' every time I want to jump so I'm happy to live with the wrong config 😅 

I really like using dumb jump as there are no extra requirements or startup time for robe/lsp. Maybe I'm the only one 🤔 

Hopefully this helps to illustrate my problem (when using robe as the backend):

*backend: robe*
(I must press `n` every time since I don't want to start up robe)
![CleanShot 2021-05-28 at 11 30 49](https://user-images.githubusercontent.com/1468141/119926160-6af8ca80-bfa9-11eb-8b52-82f6354aced1.gif)

*backend: nil*
(I don't need to press `n` to use dumb-jump)
![CleanShot 2021-05-28 at 11 34 07](https://user-images.githubusercontent.com/1468141/119926086-44d32a80-bfa9-11eb-96c3-5c27be894ceb.gif)

Would it be possible to implement a ruby backend that is dumb jump as the default? 🤔

**Comment by lebensterben** [comment]
- You want to avoid answering the same question. So the direct solution is to make it remember your choice, per-file, per-session, or permanently. Changing ruby-backend to an unidentified symbol just BREAKS the layer loading and is NEVER a solution.
- You prefer dumb jump for it's fast startup time comparing to LSP or rope. The direct solution is to get a new computer.

**Comment by thanhvg** [comment]
@gondalez can you add this line bellow o your `dotspacemacs/user-config`, and report the result:

``` elisp
(setq-default  spacemacs-default-jump-handlers '(xref-find-definitions))
```
If it doesn't work can you `eval` the variable `xref-backend-functions` in you ruby buffer, and report its value:

`M-: xref-backend-functions`.  

When `lsp-mode` is not active the `eval` should return `(dumb-jump-xref-activate etags--xref-backend)` then you are good with `gd` going through  new `dump-jump`.

**Comment by gondalez** [comment]
Thank you @thanhvg, that works nicely 👍 

Also I was able to use `(setq-default  spacemacs-default-jump-handlers '(dumb-jump-go))` to use dumb jump, which has slightly nicer behaviour for my use case.

**Comment by gondalez** [comment]
So now I only have the 'answering N' or incorrect `nil` in ruby layer config dilemma, which is a nice improvement :)

I really appreciate all the work that has gone into LSP and Robe. I have tried them both, but I find I prefer the minimalism of rg and dumb jump for my workflow.

It would seem this is also a nice default for newcomers as they can make the conscious decision to enable either backend.
At the point they decide to enable they would install the dependencies also.

I suppose this is more high level, but just curious as to others' thoughts around it. 

Again, thanks for the help!

**Comment by lebensterben** [comment]
The sensible default should be LSP for all supported major modes, without exception.

It's much easier for newcomers to learn LSP than dozens of separate modes.

A common argument against LSP is that it's slow. The direct solution is to buy a better computer. Otherwise just suck it up.

Software developers only solve software issues. Slow computer is not a hardware issue. So nothing can be done here.

**Comment by mbertheau** [comment]
> A common argument against LSP is that it's slow. The direct solution is to buy a better computer. Otherwise just suck it up.
> 
> Software developers only solve software issues. Slow computer is not a hardware issue. So nothing can be done here.

😂😂 Hilarious! :) 😂😂
