### ISSUE TITLE
Serious issue with window management while using `H` `J` `K` `L`

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#1479]
Also `U` and `u` don't work... (the functions still work when using `SPC w u`)
check this 

[![alt](https://asciinema.org/a/19503.png)](https://asciinema.org/a/19503)

**Comment by syl20bnr** [comment]
Thank you for the report.

There are a lot of things that does not work as expected in this micro-state, what you reported and #763 are one of them.

I don't use this micro-state so I always forget about it, sorry for this.

It may be related to the fact that or how we inject the `last-command` when performing the action. See https://github.com/syl20bnr/spacemacs/blob/develop/core/core-micro-state.el#L172
I'll check it sometimes in the next few days.
