### ISSUE TITLE
Error message on startup - Error (use-package): python/:init: Invalid version syntax

### ISSUE THREAD

**Issue by prehensilecode** [syl20bnr/spacemacs#14807]
#### Description :octocat:
Error on startup "Invalid version syntax"
#### Reproduction guide :beetle:
- Start Emacs
- message appears right after startup

*Observed behaviour:* :eyes: :broken_heart:
Error message shows in message buffer:
```
Error (use-package): python/:init: Invalid version syntax: '^[2;myhost: 
/Volumes/Homes/Users/myname^G^[]1;myhost^G7.23.1' (must start with a number)
```

*Expected behaviour:* :heart: :smile:
no error message

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.200.13
- Spacemacs branch: develop (rev. 5ef4960d4)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python vimscript helm emacs-lisp git markdown version-control)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB MODULES THREADS JSON PDUMPER GMP

Python installed with Homebrew
- pyenv version 2.0.0
- python3 version 3.9.5
- ipython version is 7.23.1 (which appears in error message)

Shell:
- tcsh 6.21.00

#### Backtrace :paw_prints:
n/a

**Comment by lebensterben** [comment]
cannot reproduce.
Does this error appear recently?

**Comment by prehensilecode** [comment]
I am new to using Spacemacs, and I just installed Spacemacs yesterday. The message appears as soon as I add the `python` layer.

FWIW, those control chars appear to be stuff used for setting window titles on terminal applications. Typically, [set in `$prompt`](https://tldp.org/HOWTO/Xterm-Title-4.html) but my `$prompt` is just `%B%.04::%m> %b`

**Comment by lebensterben** [comment]
can you try again in bash or zsh?
I don't think any maintainer have tested it on tcsh

**Comment by prehensilecode** [comment]
1. `chsh -s /bin/bash` and launch a new terminal. `emacs -nw` is OK -- error message does not appear
2. `chsh -s /bin/zsh` and launch a new terminal. `emacs -nw` is OK -- error message does not appear

**Comment by lebensterben** [comment]
Then I have to conclude some packages in python layer doesn't work with tcsh.
There's not likely anything we can do here.
a POSIX compatible shell should be a reasonable requirement.

**Comment by prehensilecode** [comment]
Understood.
