### ISSUE TITLE
Modeline is clobbered when fill-column is enabled

### ISSUE THREAD

**Issue by Luctins** [syl20bnr/spacemacs#14801]
#### Description :octocat:
The modeline is clobbered when the fill column is enabled.

#### Reproduction guide :beetle:
- Start Emacs
- open any text buffer
- Enable the fill column with `spacemacs/toggle-fill-column-indicator-on`

*Observed behaviour:* :eyes: :broken_heart:
- The modeline is clobbered when the fill column is enabled and is not restored until restarting Spacemacs.

*Expected behaviour:* :heart: :smile:
The fill column would appear and the modeline would not be affected. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 80e2fd427)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(octave rust csv markdown yaml
		(python :variables python-indent 8 python-indent-offset 4 indent-tabs-mode t tab-width 4)
		lua helm auto-completion better-defaults emacs-lisp git
		(org :variables org-image-actual-width 400 org-startup-with-inline-images t org-directory "~/Documents/" org-default-notes-file
			 (concat org-directory "todo.org")
			 org-startup-folded t)
		(shell :variables shell-default-height 30 shell-default-position 'bottom)
		spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
---------
```

**Comment by Luctins** [comment]
![spacebug](https://user-images.githubusercontent.com/4743486/119685561-d9a81d80-be1b-11eb-8901-aa071b3f5352.gif)

**Comment by smile13241324** [comment]
Strange, can you upgrade your spacemacs and your packages? I have just tried that on my linux box on Manjaro and my mode line is not clobbered.

### Steps to reproduce
- `SPC b s`
- `sample text <return>`
- `SPC t f`
- Check mode line, on my side it is not clobbered

I am using `Spacemacs-dark` and the `Spaceline`.

**Comment by lebensterben** [comment]
@smile13241324 
Probably related https://github.com/syl20bnr/spacemacs/issues/14726#issuecomment-835682803
I haven't got time to check

**Comment by lebensterben** [comment]
@Luctins I've pushed a commit and it should have fixed it.

**Comment by Luctins** [comment]
Thanks for the quick reply.
Sadly, it didn't work, same result as before.
my full .spacemacs is [here](https://gist.github.com/Luctins/4b45effaad5d9939ffa820ea6add0461) (barred the very long custom variables at the end, mostly flycheck paths).
One thing, that recently changed and could be the culprit, is that my distro  (popos) updated base emacs from 25.x to 26.x.
system version info:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy
```

**Comment by Luctins** [comment]
> @smile13241324
> Probably related [#14726 (comment)](https://github.com/syl20bnr/spacemacs/issues/14726#issuecomment-835682803)
> I haven't got time to check
Reading this, I've tested using the doom modeline, and it works even with the fill column indicator, but is missing features that the spaceline has (like menus for minor modes), and has a few corrupted characters (even using Source code pro font).

doom:
![image](https://user-images.githubusercontent.com/4743486/120029676-cbe5ca00-bfcc-11eb-8a09-dea4def44dfc.png)

**Comment by lebensterben** [comment]
@Luctins 
But it's not a fix for the bug itself...

**Comment by Luctins** [comment]
> @Luctins
> But it's not a fix for the bug itself...

Indeed. 
Is there any other thing I can test/run to try tracking the bug down?

**Comment by lebensterben** [comment]
Well. Another workaround is mentioned there: https://github.com/syl20bnr/spacemacs/issues/14726#issuecomment-835682803

If that ever fixed your issue, then my fix wasn't working...

**Comment by Luctins** [comment]
> Well. Another workaround is mentioned there: [#14726 (comment)](https://github.com/syl20bnr/spacemacs/issues/14726#issuecomment-835682803)
> 
> If that ever fixed your issue, then my fix wasn't working...

That does work.

**Comment by lebensterben** [comment]
🤦 I will take another try.

**Comment by smile13241324** [comment]
Thanks for having a look there @lebensterben.

**Comment by lebensterben** [comment]
should be fixed with https://github.com/syl20bnr/spacemacs/pull/14810
