### ISSUE TITLE
global-git-commit-mode disappears on first restart

### ISSUE THREAD

**Issue by amiryal** [syl20bnr/spacemacs#14811]
#### Description :octocat:                                                                                                                                            
After adding the `git` layer, `global-git-commit-mode` disappears on first restart.

Note: when uncommenting the `git` layer in advance of installing Spacemacs for the first time, `global-git-commit-mode` never becomes available.

For the reproduction below, I used Emacs 26.3, but the issue was first observed on Emacs 27.1.

#### Reproduction guide :beetle:
- `git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d`
- `cp ~/.emacs.d/core/templates/.spacemacs.template .spacemacs`
- Start Emacs, let it finish installing Spacemacs, quit Emacs
- `sed -e 's/;; git/git/' --in-place .spacemacs`
- Start Emacs, let it finish installing
- `SPC SPC`, type `global-git-commit-mode` and observe that the function is defined.
- `SPC q R`

*Observed behaviour:* :eyes: :broken_heart:
Once restarted, `global-git-commit-mode` is no longer defined.

*Expected behaviour:* :heart: :smile:
The `global-git-commit-mode` function should remain available.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b96ace131)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
N/A

**Comment by lebensterben** [comment]
It's not autoloaded since https://github.com/magit/magit/commit/13f20763ada7c9c9252fe146f5ec5643ce7b66c4

According to changelog, we need to (require 'git-commit) before using global-git-commit-mode

**Comment by amiryal** [comment]
Thanks @lebensterben! I’ve actually read [this](https://magit.vc/manual/magit/git_002dcommit_002dmode-isn_0027t-used-when-committing-from-the-command_002dline.html#git_002dcommit_002dmode-isn_0027t-used-when-committing-from-the-command_002dline) before submitting the issue, but didn’t think it applied in my case because it was working in Spacemacs before without any workaround.

So, to resolve the issue, the documentation [here](https://develop.spacemacs.org/layers/+source-control/git/README.html#global-git-commit-mode) should be updated to match the new behaviour, and possibly add a few words about the impact on load time.

**Comment by lebensterben** [comment]
Right.

**Comment by smile13241324** [comment]
I have extended the documentation of the git layer to explain how to properly activate `global-git-commit-mode` with the latest package versions.
