### ISSUE TITLE
Global toggle to use lsp-deferred instead of lsp

### ISSUE THREAD

**Issue by fuyu0425** [syl20bnr/spacemacs#14816]
Hello Spacemacs Community,
I recently learned that `emacs-lsp` can defer the LSP initialization when the buffer is visible.
To enable this, we can use `lsp-deferred` instead of `lsp`.

I found that `lsp-deferred` is extremely helpful when you use `dotspacemacs-auto-resume-layouts t`, which will reduce respond time after init a lot because there are many buffers using LSP.

Therefore, it will be helpful if there is a global toggle like `lsp-use-deferred` which can make each layer defer the LSP initialization.

**Comment by lebensterben** [comment]
I think they're already deferred, though not via `lsp-deferred`.

**Comment by fuyu0425** [comment]
What I observed is that it is not deferred. For example, the lsp-related stuff in python.
https://github.com/syl20bnr/spacemacs/blob/1ce4a7fd66a4f19c8b9008798d526a754b213f94/layers/%2Blang/python/packages.el#L367
https://github.com/syl20bnr/spacemacs/blob/1ce4a7fd66a4f19c8b9008798d526a754b213f94/layers/%2Blang/python/funcs.el#L32-L38
https://github.com/syl20bnr/spacemacs/blob/1ce4a7fd66a4f19c8b9008798d526a754b213f94/layers/%2Blang/python/funcs.el#L88-L98

From my understanding, the `lsp` will be called when there is a python-mode buffer? (even in the background)

If we use `lsp-deferred`, LSP will be initiated when we switch to the buffer.

**Comment by lebensterben** [comment]
Okay thanks for the explanation.
This is a very good idea.

**Comment by smile13241324** [comment]
Very good point, did run into this issue already at work, I will refactor the layers to use `(lsp-deferred)` instead.

**Comment by smile13241324** [comment]
Done, all layers using lsp are now deferring the start of the lsp server up to when the respective buffer is loaded.
