### ISSUE TITLE
Warn about too old Emacs

### ISSUE THREAD

**Issue by miikka** [syl20bnr/spacemacs#1481]
How about showing a message if the Emacs version is too old for Spacemacs?

I just tried to install Spacemacs on Emacs 23.3.1, started Emacs and nothing happened. Took me a while to figure out what's going on. Doing nothing is nicer than getting mysterious error messages that backwards-incompability would surely cause, but it'd be even nicer to get a simple message that tells me what's wrong.

**Comment by BlinkD** [comment]
```
(when (version< emacs-version  "24.4")
  (message "too old"))
```

**Comment by calebmeyer** [comment]
I don't mind PRing this change (assuming the code above isn't pseudocode), but I don't know where it should live.

**Comment by StreakyCobra** [comment]
@calebmeyer In `init.el` there is already a check for this with a `when`. This `when` could probably be changed to an `if`, and in the else clause, display a message to say emacs is to old.

**Comment by Immortalin** [comment]
@StreakyCobra @syl20bnr merge pull request and add `fixed in develop` label?

**Comment by AdrieanKhisbe** [comment]
(@Immortalin: just made a comment on the commit about formating :) )
