### ISSUE TITLE
Parentheses / braces duplicated if word is selected from end to start

### ISSUE THREAD

**Issue by dennismayr** [syl20bnr/spacemacs#14813]
#### Description :octocat:
Parentheses / braces duplicated if word is selected from end to start

#### Reproduction guide :beetle:
- Start Emacs.
- Create a buffer in any desired programming language; save the file.
- Place cursor at the last letter of a keyword (in a RTL sense).
- Hold `shift` to begin selecting a keyword to enclose in curly braces or parentheses, pressing <- until the whole keyword is selected up to its first letter.
- Press `{` or `(` to enclose the keyword in the following fashion: `{keyword}` or `(keyword)`. 
- Note that the final curly brace or parenthesis is duplicated: `{keyword}}` or `(keyword))`.
- If the keyword is selected from the first letter to the last (LTR sense), the final curly brace or parenthesis is _not_ duplicated.

*Observed behaviour:* :eyes: :broken_heart:
Keywords are enclosed as `{keyword}}` or `(keyword))`

*Expected behaviour:* :heart: :smile:
Keywords are enclosed as `{keyword}` or `(keyword)`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. c74b0f8bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-ccls)
 csv
 (dart :variables dart-backend 'lsp lsp-dart-sdk-dir "~/flutter/bin/cache/dart-sdk/" lsp-dart-flutter-sdk-dir "~/flutter/bin/cache/dart-sdk")
 (go :variables go-backend 'lsp go-use-golangci-lint t)
 graphql
 (html :variables web-fmt-tool 'prettier)
 (javascript :variables javascript-backend 'lsp javascript-repl 'nodejs javascript-import-tool 'import-js javascript-fmt-tool 'prettier js2-include-node-externs t)
 (json :variables json-fmt-tool 'prettier)
 (kotlin :variables kotlin-backend 'lsp kotlin-lsp-jar-path "/home/dmayr/kotlin-language-server/server/bin/kotlin-language-server")
 markdown nginx plantuml
 (php :variables php-backend 'ac-php-core)
 (python :variables python-backend 'lsp python-lsp-server 'pyls)
 react
 (rust :variables rust-backend 'lsp lsp-rust-server 'rust-analyzer cargo-process-reload-on-modify t)
 shell-scripts systemd
 (sql :variables sql-capitalize-keywords t)
 (typescript :variables typescript-backend 'lsp)
 (vue :variables vue-backend 'lsp vue-fmt-tool 'prettier)
 windows-scripts yaml
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults
 (cmake :variables cmake-enable-cmake-ide-support t cmake-backend 'lsp)
 dap debug docker emacs-lisp emoji
 (geolocation :variables geolocation-enable-automatic-theme-changer t)
 git github gtags helm import-js lsp meson multiple-cursors
 (treemacs :variables treemacs-use-collapsed-directories 3 treemacs-use-filewatch-mode t treemacs-use-git-mode 'deferred)
 (org :variables org-enable-bootstrap-support t org-enable-hugo-support t org-enable-github-support t)
 pandoc prettier restclient
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables enable-flyspell-auto-completion t)
 sql syntax-checking unicode-fonts version-control web-beautify)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
```

**Comment by lebensterben** [comment]
cut the jargon. what's the language and keyword you tried?

PS. not all language has keywords

**Comment by dennismayr** [comment]
Rust, Go, javascript, shell scripts. Could be anything, but I tried those.

**Comment by lebensterben** [comment]
Cannot reproduce.
Need concrete steps.

**Comment by dennismayr** [comment]
- Placer cursor at the end of the word
- Hold `shift`, then hit `ctrl` + `<-` to select the word
- Type `{` or `)`
- Check enclosure
- Try again, but this time placing cursor at the start of the word, holding `shift`, then `ctrl` + `->` and `{` or `(`.
- Check enclosure.

**Comment by lebensterben** [comment]
Cannot reproduce.

Say I've a rust buffer with a single line `struct X;`

- Place cursor at <|>, i.e. `struct<|> x;`
- `C-<left>` is bound to `left-word`, `S-C-<left>` thus select `struct`
- `{` is bound to `evil-backward-paragraph`. `(` is bound to `evil-backward-sentence-begin`

**Comment by dennismayr** [comment]
I deactivated `electric-pair-mode` and `electric-quote`, which I had previously activated simultaneously, and the problem disappeared.

PEBCAK, never mind.
Thanks for testing!

**Comment by dennismayr** [comment]
As an additional note:

To avoid my initially reported anomalous behaviour, I've set these parentheses options in _Spacemacs:_

```elisp
   ;; If non-nil and `dotspacemacs-activate-smartparens-mode' is also non-nil,
   ;; `smartparens-strict-mode' will be enabled in programming modes.
   ;; (default nil)
   dotspacemacs-smartparens-strict-mode nil

   ;; If non-nil smartparens-mode will be enabled in programming modes.
   ;; (default t)
   dotspacemacs-activate-smartparens-mode nil

   ;; If non-nil pressing the closing parenthesis `)' key in insert mode passes
   ;; over any automatically added closing parenthesis, bracket, quote, etc...
   ;; This can be temporary disabled by pressing `C-q' before `)'. (default nil)
   dotspacemacs-smart-closing-parenthesis t
```
