### ISSUE TITLE
tracking issue for correctly setting custom-variables

### ISSUE THREAD

**Issue by lebensterben** [syl20bnr/spacemacs#14829]
Currently many custom-variables (those defined via `defcustom`) are set via `setq` or `setq-default`.
We should instead set them with `custom-set-variables`. The benefits are:
- It's only set when its `defcustom` form is evaluated. So in case we made a typo in the variable name, the symbol won't be created.
- It won't appear in `customize-rogue`

**Comment by bcc32** [comment]
I think we should re-open this issue.  It is worth doing.
