### ISSUE TITLE
Cannot find font (Inconsolata) after upgrading to emacs 27.1

### ISSUE THREAD

**Issue by jia-j-chen** [syl20bnr/spacemacs#14822]
#### Description :octocat:
Cannot find any of the specified fonts (Inconsolata) after upgrading to emacs 27.1

#### Reproduction guide :beetle:
- Upgrade emacs from 26.05 to 27.1
- Start Emacs
- Warnings message: - Cannot find any of the specified fonts (Inconsolata)! Font settings may not be correct.

*Observed behaviour:* :eyes: :broken_heart:
- The font type and size are displayed as specified in .spacemacs before upgrading to emacs 27.1
- After upgrading to emacs 27.1, the font type and size are not correct, only default font type and size are used.

*Expected behaviour:* :heart: :smile:
- Wang to use the font type and size specified in .spacemacs
- dotspacemacs-default-font '("Inconsolata"
                               :size 36
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1ce4a7f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(csv python bibtex html helm auto-completion better-defaults emacs-lisp git markdown org
     (chinese :variables chinese-enable-fcitx t chinese-fcitx-use-dbus t pyim-default-scheme 'microsoft-shuangpin)
     latex ranger pdf
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     version-control
     (mu4e :variables mu4e-use-maildirs-extension t mu4e-installation-path "/usr/share/emacs/site-lisp" mu4e-enable-async-operations t mu4e-maildir "/home/chenj/Maildir" mu4e-sent-folder "/Local_sent" mu4e-headers-full-search nil mu4e-headers-results-limit 500 mu4e-drafts-folder "/Drafts" mu4e-trash-folder "/Deleted_Messages" mu4e-attachment-dir "~/Downloads" mu4e-get-mail-command "offlineimap" mu4e-view-show-images t mu4e-view-show-addresses t mu4e-headers-date-format "%Y-%m-%d %H:%M" mu4e-compose-reply-to-address "jia.j.chen@foxmail.com" user-mail-address "jia.j.chen@foxmail.com" user-full-name "Jia CHEN" send-mail-function 'async-smtpmail-send-it message-send-mail-function 'async-smtpmail-send-it smtpmail-smtp-server "smtp.qq.com" smtpmail-smtp-service 465 smtpmail-stream-type 'ssl smtpmail-auth-credentials
           (expand-file-name "~/.authinfo.gpg")
           mu4e-headers-fields
           '((:date . 18)
             (:flags . 6)
             (:from . 15)
             (:to . 15)
             (:subject))
           mu4e-compose-signature "Jia CHEN @ http://chenjia.gsm.pku.edu.cn" mu4e-maildir-shortcuts
           '(("/INBOX" . 105)
             ("/PKU_Email" . 112)
             ("/Sent_Messages" . 115))))
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
- how's this a spacemacs bug
- cannot reproduce

**Comment by jia-j-chen** [comment]
How do I make spacemacs recognize Inconsolata font?

Is there a better place for me to ask this question?

I upgraded emacs to 27.1 on another machine and did not experience the same warnings message.

**Comment by jia-j-chen** [comment]
> * how's this a spacemacs bug
> * cannot reproduce

How do I make spacemacs recognize Inconsolata font?

Is there a better place for me to ask this question?

I upgraded emacs to 27.1 on another machine and did not experience the same warnings message.

**Comment by lebensterben** [comment]
What's the output of `(find-font (font-spec :name "Inconsolata"))`

**Comment by lebensterben** [comment]
btw you'd want to upgrade to emacs 27.2. and use float point number for font size.

**Comment by jia-j-chen** [comment]
> What's the output of `(find-font (font-spec :name "Inconsolata"))`

The output of this is nil.

**Comment by lebensterben** [comment]
So emacs cannot see the font. You should start digging from here.

**Comment by jia-j-chen** [comment]
> btw you'd want to upgrade to emacs 27.2. and use float point number for font size.

OK. I upgraded to emacs 27.2. The problem persists.

**Comment by lebensterben** [comment]
As I said the issue is your emacs cannot see the font. Why not to reinstall the font?

**Comment by jia-j-chen** [comment]
> As I said the issue is your emacs cannot see the font. Why not to reinstall the font?

Have tried reinstall the font by using sudo apt remove fonts-inconsolata and then sudo apt install fonts-inconsolata. The problem is still there.

If I switch back to emacs 26.05, then the problem is gone.

**Comment by jia-j-chen** [comment]
This issue seems to be an old one. #13947

**Comment by jia-j-chen** [comment]
I solved the problem:

sudo apt install liboft-dev libgtk-3-dev librsvg2-dev libm17n-dev libotf-dev libxft-dev libfreetype6 libfreetype6-dev

./configure --prefix=/usr --with-x-toolkit=gtk3
make
sudo make install
sudo chown -v -R root:root /usr/share/emacs/27.2
sudo rm -vf /usr/lib/systemd/user/emacs.service

Reference:
[https://my.oschina.net/redhouse/blog/4943941](url)
[https://www.linuxfromscratch.org/blfs/view/cvs/postlfs/emacs.html](url)
