### ISSUE TITLE
org: export to odt fails

### ISSUE THREAD

**Issue by michelk** [syl20bnr/spacemacs#1482]
When trying to export an org document to odt (`org-odt-export-to-odt`) I get: 

    OpenDocument export failed: Buffer is read-only: #<killed buffer>

**Comment by pao** [comment]
I happened to experience this with an otherwise vanilla Emacs 24.4 on Windows; whatever it is seems to be fixed as of org 8.2.10-40-gc763fa-elpa (the 2015-05-04 ELPA package).

**Comment by syl20bnr** [comment]
Thank you @michelk for the report and @pao for the follow up.
@michelk can you check if it is ok on your side ?

**Comment by michelk** [comment]
How could I switch to org-mode on melpa or ELPA?

`org-version` tells me 8.2.10 with emacs 24.5.2 on linux.

**Comment by pao** [comment]
`M-x package-install RET org RET` ought to do it.

**Comment by syl20bnr** [comment]
I realize that there is an issue opened about this: #1218

**Comment by michelk** [comment]
With the ELPA-org-package the issue is resolved.

Thanks @pao

**Comment by pao** [comment]
You're welcome; happy to be able to help.
