### ISSUE TITLE
The width of left margin to show line numbers is not consistent

### ISSUE THREAD

**Issue by aruku7230** [syl20bnr/spacemacs#14837]
#### Description :octocat:
The width of left margin to show line numbers is not consistent

#### Reproduction guide :beetle:
- Config `dotspacemacs-line-numbers 'relative`.
- Start Emacs.
- Open this org file with more than 1000 lines in org-mode. There are two headlines at line 1 and 998. Below is the content of the file. Note the `<number>"` at the the left indicate the line number :
  ```
     1: * abcd
     2: abcd
     3: abcd
  ......
   998: * abcd
   999: abcd
  1000: abcd
  1001: abcd
  ```
- Fold the first headline at line 1, and go to line 1000.

*Observed behaviour:* :eyes: :broken_heart:

line 1000 is the current line. | represent the boundary of left margin and the
buffer content.

![image](https://user-images.githubusercontent.com/12474218/121482386-1709cf00-ca08-11eb-8dac-1ac3d06dd092.png)

*Expected behaviour:* :heart: :smile:

the right of line numbers is aligned.

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. af193f769)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((lsp :variables css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t)
 python csv windows-scripts
 (javascript :variables js2-basic-offset 2 js-indent-level 2)
 sql
 (html :variables web-fmt-tool 'web-beautify)
 web-beautify helm auto-completion emacs-lisp git markdown multiple-cursors treemacs
 (org :variables org-want-todo-bindings t)
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control
 (ranger :variables ranger-show-preview t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by aruku7230** [comment]
What mode does Spacemacs use to show line numbers, `linum-mode` or `display-line-numbers-mode`?

**Comment by lebensterben** [comment]
should be linum

**Comment by lebensterben** [comment]
well. the new behavior is to use display-line-number-mode unless you haven't updated dotspacemacs then it fallsback to linum package

https://github.com/syl20bnr/spacemacs/blob/c1c18b7eedc9bc6ee07618f064e8eb8d9ef58337/layers/%2Bspacemacs/spacemacs-defaults/funcs.el#L1725

**Comment by duianto** [comment]
Could it be a font issue?

It looks correct for me, with the Source Code Pro font:
`    harfbuzz:-outline-Source Code Pro-normal-normal-normal-mono-13-*-*-*-c-*-iso8859-1 (#x1C)`
source: The current font can be seen by pressing `SPC h d c` (calls `describe-char`)
That line appears at the end of the first paragraph in the Help buffer.

![emacs_9XNUJpQKdi](https://user-images.githubusercontent.com/13420573/121477971-c45cf280-c9c8-11eb-90fd-14298a022679.png)

<details>
<summary>System Info</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 120ce6959)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp git helm html javascript multiple-cursors org spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP
</pre>
</details>

**Comment by aruku7230** [comment]
@duianto , I updated the reproduction guide by adding headlines on org file and then fold the headline reproduced it.

**Comment by duianto** [comment]
Confirmed, I'm also able to reproduce it now.

![emacs_4OMLYNpQu5](https://user-images.githubusercontent.com/13420573/121484049-27518800-c9cf-11eb-8c4e-8f3152507e98.png)

It isn't limited to Spacemacs, it also happens with: `runemacs -Q` (it starts Emacs without any configurations)

![emacs_x6KzOUvkTi](https://user-images.githubusercontent.com/13420573/121484470-8a431f00-c9cf-11eb-980b-71ac85735abb.png)
