### ISSUE TITLE
Problems with LSP and clangd

### ISSUE THREAD

**Issue by GiulioCocconi** [syl20bnr/spacemacs#14831]
#### Description :octocat:
LSP doesn't find clangd for C/C++ development (on Raspberry PI 4)

#### Reproduction guide :beetle:
- Install clangd-9
- Start Emacs
- Create a .c file

*Observed behaviour:* :eyes: :broken_heart:
LSP tells me to install clangd server

*Expected behaviour:* :heart: :smile:
LSP starts normally

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 53027df)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t)
 better-defaults emacs-lisp git helm
 (lsp :variables lsp-use-lsp-ui t lsp-lens-enable t)
 org
 (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom)
 python
 (c-c++)
 cmake dash)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP

**Comment by lebensterben** [comment]
what's the result of `(executable-find "clangd")`

**Comment by GiulioCocconi** [comment]
/usr/bin/clangd

Il giorno dom 6 giu 2021 alle ore 22:22 Lucius Hu ***@***.***>
ha scritto:

**Comment by lebensterben** [comment]
what's the exact error message

**Comment by lebensterben** [comment]
LSP should be able to find clangd. You can set this variable and retry https://github.com/emacs-lsp/lsp-mode/blob/7b75d6bf01bed9ccb108cf1406d0e2af29d7e39b/clients/lsp-clangd.el#L162

**Comment by GiulioCocconi** [comment]
LSP :: The following servers support current file but do not have automatic
installation configuration: clangd
You may find the installation instructions at
https://emacs-lsp.github.io/lsp-mode/page/languages.
(If you have already installed the server check *lsp-log*).

But the *lsp-log* buffer doesn't exist

Il giorno dom 6 giu 2021 alle ore 23:03 Lucius Hu ***@***.***>
ha scritto:

**Comment by GiulioCocconi** [comment]
I tried but it's already setted to clangd dir...

Il giorno dom 6 giu 2021 alle ore 23:07 Lucius Hu ***@***.***>
ha scritto:

**Comment by lebensterben** [comment]
You should report this to lisp-mode

**Comment by GiulioCocconi** [comment]
The lsp-mode?

Il giorno lun 7 giu 2021 alle ore 08:28 Lucius Hu ***@***.***>
ha scritto:

**Comment by lebensterben** [comment]
yep.

**Comment by GiulioCocconi** [comment]
I reported to lsp-mode team...
When I start the basic lsp-mode with [this script](https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el) Clangd works normally...
I think that this is a Spacemacs problem

**Comment by GiulioCocconi** [comment]
I remove all the LSP variables and it worked...
