### ISSUE TITLE
Chinese layer fcitx error when reload configuration

### ISSUE THREAD

**Issue by yejianfengblue** [syl20bnr/spacemacs#14833]
#### Description :octocat:
I use `chinese` layer and set variable `chinese-enable-fcitx t`. When I `SPC f e R`, an error is displayed in buffer `*warning*`: `Error (use-package): fcitx/:config: Unknown ‘M-x’ binding command. Only original M-x, ‘smex’, ‘helm-M-x’ and ‘counsel-M-x’ are supported.`.

Fcitx function is not affected, but warning buffer popup is annoying.

If I manually change `(fcitx-default-setup)` to `(fcitx-aggressive-setup)` in function `chinese/init-fcitx()` from file `layers/+intl/chinese/packages.el`, no error.

Error routing in file `fcitx.el` is `fcitx-default-setup` -> `fcitx-M-x-turn-on` -> `error `. 

#### Reproduction guide :beetle:
- Start Emacs
- `SPC f e R`

*Observed behaviour:* :eyes: :broken_heart:
Buffer `*warning*` pops up with error `Error (use-package): fcitx/:config: Unknown ‘M-x’ binding command. Only original M-x, ‘smex’, ‘helm-M-x’ and ‘counsel-M-x’ are supported.`

*Expected behaviour:* :heart: :smile:
No warning or error pops up.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 120ce6959)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((chinese :variables chinese-use-fcitx5 t chinese-enable-fcitx t)
 emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
What's the output of `(key-binding (kbd "M-x"))`

**Comment by yejianfengblue** [comment]
> What's the output of `(key-binding (kbd "M-x"))`

spacemacs/helm-M-x-fuzzy-matching

**Comment by lebensterben** [comment]
Try to delete this line https://github.com/syl20bnr/spacemacs/blob/120ce6959d10cac04ae27b0a024f879d6d8356bf/layers/%2Bintl/chinese/packages.el#L41
And change the next line from :config to :init

**Comment by yejianfengblue** [comment]
@lebensterben 
still error 
```lisp
(defun chinese/init-fcitx ()
  (use-package fcitx
    :init
    (progn
      (setq fcitx-active-evil-states '(insert emacs hybrid))
      (when chinese-use-fcitx5
        (setq fcitx-remote-command "fcitx5-remote"))
      (fcitx-default-setup)
      (fcitx-prefix-keys-add "M-m" "C-M-m")
      (when chinese-fcitx-use-dbus
        (setq fcitx-use-dbus t)))))
```

**Comment by lebensterben** [comment]
Weird. Packages are loaded in alphabetical order so fcitx is loaded before helm.

The line causing the error is https://github.com/syl20bnr/spacemacs/blob/120ce6959d10cac04ae27b0a024f879d6d8356bf/layers/%2Bcompletion/helm/packages.el#L97

If fcitx is loaded before helm, then it should all be okay.

**Comment by yejianfengblue** [comment]
Spacemacs startup has no error but reload configuration has error.

**Comment by lebensterben** [comment]
that because when reloading the M-x bindings has been changed.
