### ISSUE TITLE
Helm is slow on remote project

### ISSUE THREAD

**Issue by yonatan-linik** [syl20bnr/spacemacs#14834]
#### Description :octocat:
When you try using helm with a remote (ssh) project many actions are very slow.
For example: helm-projectile is very slow (10 to 20 seconds).

#### Reproduction guide :beetle:
- Start Emacs
- Open a remote (ssh) large (~10G) project
- Try doing almost anything with helm

*Observed behaviour:* :eyes: :broken_heart:
Things are really slow - actions take ~10 seconds

*Expected behaviour:* :heart: :smile:
Things should be faster, almost as if they were local

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 51142a23a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python yaml protobuf emacs-lisp git helm markdown multiple-cursors org spell-checking treemacs)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
```

**Comment by lebensterben** [comment]
What do you mean by
> Try doing almost anything with helm

Do you mean "try do to anything with helm-projectile"?

**Comment by yonatan-linik** [comment]
Things like:
helm-projectile
helm-projectile-find-file

**Comment by lebensterben** [comment]
- they are supposed to be slow
- you should report it to upstream if you think it's a bug
