### ISSUE TITLE
Toggle fullscreen frame does not work

### ISSUE THREAD

**Issue by 526avijitgupta** [syl20bnr/spacemacs#1483]
The following error is encountered when running the command `spacemacs/toggle-fullscreen-frame`: Symbol's function definition is void `toggle-frame-fullscreen`

**Comment by tuhdo** [comment]
You can use stock Emacs key binding `M-<f10>` to toggle on/off maximized frame.

**Comment by 526avijitgupta** [comment]
Yeah, the keybinding `M-<f10>` works. Thanks.
But even then, executing the command should not throw an error like that!

**Comment by TheBB** [comment]
What Emacs version and OS is this? That might have something to do with it.

**Comment by TheBB** [comment]
No response from OP. Closing. If this is still a problem, please reopen.
