### ISSUE TITLE
Documentation on stable installation is wrong

### ISSUE THREAD

**Issue by clushie** [syl20bnr/spacemacs#14843]
At the moment `README.md` suggests that cloning this repository will yield to a stable installation (aka not develop). This is an important detail, for example because the develop-installation won't receive auto-updates by default.

From the README:

> For stable releases:
> `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
> For development updates and participation:
> `git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d`

This is incorrect since `develop` is configured as the default branch on GitHub, yielding a clone without specifying a branch to be `develop`, so basically at the moment, both commands are doing the same.

**Comment by lebensterben** [comment]
currently master branch is definitely not stable since it's not receiving updates.

**Comment by mixmixmix** [comment]
@lebensterben I just came here to find out what is the current state of the project? On `develop` I start having more and more problems, and as you pointed out `master` is no good at the moment. I keep reading "VERSION 0.300 IS ALMOST OUT!", but I'm not quite sure anymore ;)

@clushie I agree that it needs to be at least explained.

**Comment by lebensterben** [comment]
@mixmixmix 
`master` is "stale"
`develop` is active development.
