### ISSUE TITLE
Can't compile chez-scheme

### ISSUE THREAD

**Issue by Sventimir** [syl20bnr/spacemacs#14840]
#### Description :octocat:
Cannot compile chez scheme code or load into interpreter.

#### Reproduction guide :beetle:
- Install geiser-chez and enable scheme support
- Start Emacs
- Open a scheme file in a buffer
- Press SPC m c c to compile the buffer

*Observed behaviour:* :eyes: :broken_heart:
A message appears (nothing is compiled):
"geiser-eval--send/wait: Symbol’s value as variable is void: geiser-eval--geiser-procedure-function"

*Expected behaviour:* :heart: :smile:
The buffer should be compiled and produce an output.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: sventimir (rev. 1c21d448d)
- Graphic display: 
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(php markdown graphviz yaml auto-completion git helm tabs multiple-cursors org mu4e pass spacemacs-purpose spell-checking treemacs emacs-lisp haskell ocaml javascript python idris
     (scheme :variables scheme-implementations
             '(chez)))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
> Spacemacs branch: sventimir (rev. 1c21d44)

This is unsupported.

**Comment by Sventimir** [comment]
Well, this branch only adds my own `.spacemacs` file so that it is version-controlled, and a file `code/libs/sven-stdlib.el` with some of my standard utilities. On `master` it can't even find the `chez` implementation (which is `scheme` on my machine).

**Comment by lebensterben** [comment]
You should use develop branch.
I'm closing this if the bug report is not updated.

**Comment by lebensterben** [comment]
For all future references,
Forks are not supported. 
Don't bother to report a bug on a fork if it's not reproducible. For example, a fork to a non-public repository/branch.
