### ISSUE TITLE
org-roam layer doesn't work

### ISSUE THREAD

**Issue by Novite5** [syl20bnr/spacemacs#14846]
#### Description :octocat:
org-roam layer doesn't work.

#### Reproduction guide :beetle:
- Start Emacs
- run `org-roam-find-file` or `org-roam-db-build-cache`

*Observed behaviour:* :eyes: :broken_heart:
`org-roam-find-file` can neither create file nor find org files. And report `org-roam--directory-files-recursively: Opening directory: Data or Directory not found, /path/to/org-files`

`org-roam-db-build-cache' can build database but report `helm-M-x-execute-command: Opening directory: Data or Directory not found, /path/to/org-files`

*Expected behaviour:* :heart: :smile:
·org-roam-find-file` can find and open existed files, or create file when it doesn't exist.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2fd3eb3ed)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-idle-delay 0.2 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual auto-completion-enable-sort-by-usage t)
 bibtex bm
 (c-c++ :variables c-c++-backend 'lsp-clangd c++-enable-organize-includes-on-save t c-c++-enable-clang-format-on-save t c-c++-enable-auto-newline t c-c++-adopt-subprojects t c-c++-lsp-semantic-highlight-method 'rainbow)
 (chinese :variables chinese-enable-avy-pinyin nil)
 (colors :variables colors-colorize-identifiers 'all colors-default-rainbow-identifiers-sat 42 colors-default-rainbow-identifiers-light 86 colors-enable-nyan-cat-progress-bar
         (display-graphic-p))
 common-lisp csv
 (dash :variables dash-docs-docset-newpath "~/.local/share/Zeal/Zeal/docsets")
 (docker :variables docker-dockerfile-backend 'lsp)
 dtrt-indent eaf emacs-lisp epub finance git github
 (geolocation :variables geolocation-enable-automatic-theme-changer t geolocation-enable-location-service t geolocation-enable-weather-forecast nil)
 (gtags :variables gtags-enable-by-default t)
 (helm :variables helm-enable-auto-resize t)
 helpful
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 imenu-list
 (ipython-notebook :variables ein-backend 'jupyter)
 (javascript :variables js2-mode-show-strict-warnings nil javascript-import-tool 'import-js javascript-fmt-tool 'prettier javascript-fmt-on-save t javascript-backend 'lsp js2-basic-offset 2 js-indent-level 2 javascript-repl 'skewer node-add-modules-path t js2-include-node-externs t js2-mode-show-strict-warnings nil js2-mode-show-parse-errors nil)
 (json :variables json-fmt-tool 'prettier json-fmt-on-save t json-backend 'lsp)
 (languagetool :variables languagetool-show-error-on-jump t langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*")
 (latex :variables latex-backend 'lsp latex-build-command "LaTeX" latex-enable-auto-fill t latex-enable-folding t latex-enable-magic t)
 lsp markdown major-modes
 (notmuch :variables notmuch-message-deleted-tags
          '("+deleted" "-inbox" "-unread"))
 (org :variables org-enable-appear-support t org-enable-bootstrap-support t org-enable-github-support t org-enable-notifications t org-enable-reveal-js-support t org-enable-roam-support t org-enable-sticky-header t org-projectile-file "TODOs.org" org-start-notification-daemon-on-startup t org-want-todo-bindings t)
 outshine pandoc parinfer prettier
 (python :variables python-backend 'lsp python-test-runner
         '(pytest nose)
         python-format-on-save t python-auto-set-local-pyenv-version 'on-visit python-fill-column 79 python-sort-imports-on-save t)
 rebox semantic
 (shell :variables close-window-with-terminal t shell-default-shell 'eshell shell-enable-smart-eshell t shell-default-height 30 shell-default-position 'bottom)
 (shell-scripts :variables shell-scripts-backend 'lsp)
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary nil)
 systemd syntax-checking themes-megapack tmux
 (treemacs :variables treemacs-use-follow-mode 'tag treemacs-use-filewatch-mode t treemacs-use-scope-type 'Perspectives treemacs-use-git-mode 'deferred treemacs-collapse-dirs 3 treemacs-lock-width t treemacs-use-all-the-icons-theme t)
 typography
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 unicode-fonts
 (xclipboard :variables xclipboard-enable-cliphist t)
 (yaml :variables yaml-enable-lsp t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Did it work in the past and stopped working recently?

**Comment by Novite5** [comment]
> Did it work in the past and stopped working recently?

Nope, I've never got it to work.

**Comment by lebensterben** [comment]
Have you updated Emacs packages?

**Comment by Novite5** [comment]
> Have you updated Emacs packages?

Yes, I keep updating it to the latest.

**Comment by dalanicolai** [comment]
AFAIK this should work fine. Can you check the value of `org-enable-roam-support`. And can you restart Spacemacs using `SPC q d`?

**Comment by lebensterben** [comment]
> @Novite5 AFAIK this should work fine. Can you check the value of `org-enable-roam-support`. And can you restart Spacemacs using `SPC q d`?

It's t.

**Comment by Novite5** [comment]
> @Novite5 AFAIK this should work fine. Can you check the value of `org-enable-roam-support`. And can you restart Spacemacs using `SPC q d`?

`org-enable-roam-support` is t. After `SPC q d` the problem still occurs. 
And I found there is a line in `custom-set-variables`:
```
  '(org-roam-directory "/path/to/org-files/")
```
Shall I change it to my org-roam path?

**Comment by dalanicolai** [comment]
Ah that's interesting, because here the `org-roam` works, but there are no `roam` related variables in my `custom-set-variables`. So it would be interesting to know how it came there.

**Comment by dalanicolai** [comment]
Ah, that's embarassing, I did not read your issue well, somehow I was thinking the `org-roam-find-file` was not available.
But now I see it just complains about not being able to find org-file. So, the I guess by setting that `org-roam-directory` (or removing that line from custom set variables, in which case roam will use the `~/org-roam` directory, things will be fixed.

**Comment by lebensterben** [comment]
> Shall I change it to my org-roam directory path?

Yes

**Comment by Novite5** [comment]
> Ah, that's embarassing, I did not read your issue well. Somehow I was thinking the `org-roam-find-file` was not available.
> But now I see it just complains about not being able to find org files. So, I guess by setting that `org-roam-directory` (or removing that line from custom set variables, in which case roam will use the `~/org-roam` directory) things will be fixed.

Yeah, I tried it. Both wok.

Thanks very much for your help. 
Also, to you @lebensterben

**Comment by lebensterben** [comment]
This should better be reported to upstream.
If org-roam failed to start because of IO error such as non accessible directory, it should emits a clear error.
