### ISSUE TITLE
Unknown type purpose-mode-alist

### ISSUE THREAD

**Issue by basaran** [syl20bnr/spacemacs#14849]
Hello,

On a fresh git installed spacemacs, the setup phase is completing with this error:

```
Error (use-package): eyebrowse/:config: Unknown type purpose-mode-alist
```

Helm is not working, my emacs is:

```
GNU Emacs 28.0.50
Copyright (C) 2021 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

compiled from the emacs-git aur repository on manjaro.  If you could please provide any assistance, I will appreciate it. Thank you for making spacemacs.

**Comment by lebensterben** [comment]
Are you using `develop` branch?

**Comment by basaran** [comment]
Yes, to be sure I cloned with:

```
git clone --branch develop  https://github.com/syl20bnr/spacemacs ~/.emacs.d
```

**Comment by lebensterben** [comment]
What layers have you enabled?

**Comment by basaran** [comment]
I'm just letting the default installer complete itself, in the evil mode, using the default layer set.

**Comment by lebensterben** [comment]
A PR has been submitted to upstream
https://github.com/bmag/emacs-purpose/pull/188

Closing this.

**Comment by basus** [comment]
Is there a workaround for this while we wait for the upstream to fix it? Unfortunately using Emacs 27 seems completely unusable with my current configuration.

**Comment by lebensterben** [comment]
@basus disable the package and install the PR branch manually

**Comment by kennethkalmer** [comment]
Or delete the locally installed package and restart spacemacs, and you'll get the updated package.

~~~shell
$ rm -rf .emacs.d/elpa/28.0/develop/window-purpose-20210423.454
~~~

(version number might differ slightly)
