### ISSUE TITLE
org layer error "Error (use-package): Cannot load org-contrib" maybe due to recent PR update

### ISSUE THREAD

**Issue by wztdream** [syl20bnr/spacemacs#14853]
[This PR](https://github.com/syl20bnr/spacemacs/commit/63197014cc3c9f4bcd64be112543c859eec629d9) try to use org-contrib instead of org-plus-contrib, but below setting will results in **Error (use-package): Cannot load org-contrib**, this seems due to bellow setting in org layer as there is no feature named 'org-contrib'

```
(defun org/init-org-contrib ()
  (use-package org-contrib
    :defer t))
```
You can reproduce this error by adding org layer and restart emacs.

**Comment by lebensterben** [comment]
is https://elpa.nongnu.org/nongnu accessible in your network?

**Comment by wztdream** [comment]
> is https://elpa.nongnu.org/nongnu accessible in your network?

Yes, it is accessible. But I use mirror source in my configure file:
```
(defun dotspacemacs/user-init ()
  "Initialization for user code:
This function is called immediately after `dotspacemacs/init', before layer
configuration.
It is mostly for variables that should be set before packages are loaded.
If you are unsure, try setting them in `dotspacemacs/user-config' first."
;; (setq configuration-layer-elpa-archives
;;     '(("melpa-cn" . "http://mirrors.bfsu.edu.cn/elpa/melpa/")
;;       ("org-cn"   . "http://mirrors.bfsu.edu.cn/elpa/org/")
;;       ("gnu-cn"   . "http://mirrors.bfsu.edu.cn/elpa/gnu/")))
)
```
After remove this mirror setting, the error is gone and `org-contrib`  is installed correctly. So any idea how to add https://elpa.nongnu.org/nongnu  along with the mirror source?

**Comment by lebensterben** [comment]
I'm thinking maybe we should add those alternative elpa archives when `chinese` layer is enabled.
What do you think?

**Comment by wztdream** [comment]
> I'm thinking maybe we should add those alternative elpa archives when `chinese` layer is enabled.
> What do you think?

I did not use chinese layer very much, maybe we should add some docs in 'org' layer to inform user add this source when using mirrors.

**Comment by lebensterben** [comment]
@wztdream 
Added notes in the documentation
https://github.com/syl20bnr/spacemacs/blob/fe147e391db71ca44ac5df24493c03a4b221fca7/layers/%2Bintl/chinese/README.org#additional-notes
