### ISSUE TITLE
*Warnings* pops up in a bottom split randomly with messages.

### ISSUE THREAD

**Issue by zendevil** [syl20bnr/spacemacs#14854]
My spacemacs has a bug. macOS Catalina. Spacemacs v.0.300.0. When I’m using it, a window split occurs and *Warnings* opens with the following info:

```
Warning (emacs): recentf mode: Doing chmod: Operation not permitted, /Users/prikshetsharma/.emacs.d/.cache/recentf
Warning (emacs): recentf mode: Doing chmod: Operation not permitted, /Users/prikshetsharma/.emacs.d/.cache/recentf
Warning (emacs): recentf mode: Doing chmod: Operation not permitted, /Users/prikshetsharma/.emacs.d/.cache/recentf
Warning (emacs): recentf mode: Doing chmod: Operation not permitted, /Users/prikshetsharma/.emacs.d/.cache/recentf

```

**Comment by lebensterben** [comment]
this should mean you don't have enough permission to acesss '/Users/prikshetsharma/.emacs.d/.cache/recentf'

what's the output of
`ls -l /Users/prikshetsharma/.emacs.d/.cache/recentf`

**Comment by zendevil** [comment]
`-rwxrwxrwx  1 root  staff  77503 Jun 17 07:45 /Users/prikshetsharma/.emacs.d/.cache/recentf`

**Comment by lebensterben** [comment]
the owner is root

try to change it to your current user with chown or whatever you prefer
