### ISSUE TITLE
groovy-mode can't be manually enabled after restart emacs

### ISSUE THREAD

**Issue by rcdeoliveira** [syl20bnr/spacemacs#14858]
#### Description :octocat:
groovy-mode can't be manually enabled after restart emacs

#### Reproduction guide :beetle:
- Start Emacs
- Install groovy-mode
- Restart Emacs
- Open a groovy file, example: Jenkinsfile
- Look for groovy-mode with SPC SPC groovy-mode, the option is not shown

*Expected behaviour:* :heart: :smile:
Find groovy-mode as command and enabled it

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ab6b165e9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html php auto-completion emacs-lisp git helm lsp markdown spell-checking syntax-checking python javascript yaml ansible terraform treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
you haven't enabled groovy layer or Java layer

**Comment by rcdeoliveira** [comment]
That worked, thanks.
