### ISSUE TITLE
Spacemacs Crashes with Relative Line Numbers + Global Visual Line Mode

### ISSUE THREAD

**Issue by jsilve24** [syl20bnr/spacemacs#14850]
#### Description :octocat:
Spacemacs Crashes with Relative Line Numbers + Global Visual Line Mode

#### Reproduction guide :beetle:
- Start Emacs with completely fresh .spacemacs (e.g., if you delete .spacemacs and start fresh)
- edit .spacemacs to include the following two changes

```
   dotspacemacs-line-numbers '(:visual t
                                       :disabled-for-modes dired-mode
                                       doc-view-mode
                                       pdf-view-mode
                                       :size-limit-kb 1000
                                       :realtive t)
```

and add the following to user-config

```
  (spacemacs/toggle-visual-line-navigation-globally-on)
```

- Then open a new org-mode file (e.g., test.org) and edit it to have the following structure

```
* asdf
** asdf
** asedf
** asdf
** asdf
* asdf 
```
- Collapse the structure with Shift+TAB until what you see is:

```
* asdf...
* asdf
```

- Move your cursor to the end of the ellipsis and try to move farther to the right. 

*Observed behaviour:* :eyes: :broken_heart:

emacs crashes

Sometimes it takes a second, sometimes you have to try 2-3 times but its fairly reproducible. 

It took me about 4 hours to track this down. 
I don't understand what is happening but the mixture of global visual line mode and turning on relative line numbers does not play nice with unfolding / folded headers in org mode. I am not sure if this is this bug extends beyond that use case. 

*Expected behaviour:* :heart: :smile:

emacs doesn't crash

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. df15f8cc1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
None, emacs crashes without any backtrace or warning.

**Comment by jsilve24** [comment]
The issue seems to be fixed if I set `:visual nil` rather than `:visual t` in the line 

```
dotspacemacs-line-numbers '(:visual t
                                       :disabled-for-modes dired-mode
                                       doc-view-mode
                                       pdf-view-mode
                                       :size-limit-kb 1000
                                       :realtive t)
```


Perhaps this is my bad? Reading the comment on the `dotspacemacs-line-numbers` function I wonder if the `:visual t` is just redundant and the `:relative t` handles it all (both visual and relative line numbers?). 

If so its an easy fix but a fairly nasty bug to try to track down.

**Comment by lebensterben** [comment]
`:visual` is not mentioned in docstring but it's a valid keyword.
