### ISSUE TITLE
No JS autocompletion

### ISSUE THREAD

**Issue by cybbro** [syl20bnr/spacemacs#14857]
![image](https://user-images.githubusercontent.com/10908092/122467286-038bd480-cfc3-11eb-9465-a08f60510699.png)

How can I enable autocompletion for JS? 

.spacemacks JS settings:

![image](https://user-images.githubusercontent.com/10908092/122467393-2322fd00-cfc3-11eb-830a-b1fb79fe0474.png)

**Comment by lebensterben** [comment]
When you choose `tern` as backend, you'd use `tern` layer. See https://develop.spacemacs.org/layers/+lang/javascript/README.html#tern

**Comment by thanhvg** [comment]
term is dead someone should remove the layer

**Comment by cybbro** [comment]
I am first-time user, I honestly have no clue how to enable autocompletion in this distro... It just won't work..

**Comment by lebensterben** [comment]
@cybbro 
Have you installed one of the LSP client? https://develop.spacemacs.org/layers/+lang/javascript/README.html#language-server-protocol

**Comment by cybbro** [comment]
> @cybbro
> Have you installed one of the LSP client? https://develop.spacemacs.org/layers/+lang/javascript/README.html#language-server-protocol

Yes I have installed it by running:

`sudo npm i -g typescript typescript-language-server`

![image](https://user-images.githubusercontent.com/10908092/122530404-1b953f80-d027-11eb-8690-1f13c43bfd86.png)

unfortunately, id does not work in .js files anyway

OS: Ubuntu 21.04
