### ISSUE TITLE
spacemacs|define-transient-state is broken

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#14868]
It looks like custom transient-states are now broken (most likely due to some upstream change).

Anything defined using `spacemacs|define-transient-state`, on attempt to use the transient, is now throwing `command-execute: Wrong type argument: ...`

- Layouts transient [partially] broken for me - pressing `SPC l ?` doesn't work
- Paste transient doesn't work at all - pressing `p` in normal mode, throws: `cond: Symbol’s function definition is void: spacemacs/paste-transient-state/evil-paste-after`
- Custom transients don't work - `SPC l o` - throws: `spacemacs/select-custom-layout: Symbol’s function definition is void: spacemacs/custom-layouts-transient-state/body`

**Comment by lebensterben** [comment]
are you using unstable emacs

**Comment by agzam** [comment]
I tried in both Emacs 28 and 27, it seems to be broken in both. I can't figure out the root cause

**Comment by duianto** [comment]
Does it work on the latest develop branch?

A recent which-key update, revealed an incorrect usage in Spacemacs.

It seems to have caused a lot of issues.

The incorrect usage was just reverted.
Revert "Fix which-key entries: gr and gs in dired and magit" #14869

**Comment by agzam** [comment]
@duianto I just pulled latest develop. The issue appears to be fixed. Thank you guys for fixing it so quickly. I will keep the issue open until tomorrow, in case someone else updates the packages without pulling the latest.

**Comment by abellmann** [comment]
I am experiencing this issue and I am on a recent version of spacemacs develop (specifically commit #7991003. Did this issue return?  Note: I am using the compleseus layer...

**Comment by lebensterben** [comment]
@abellmann 

what's the backtrace?

**Comment by abellmann** [comment]
Hmm. There isn't much, since it just cannot find the method..

````
Debugger entered--Lisp error: (wrong-type-argument commandp spacemacs/zoom-frm-transient-state/body)
  command-execute(spacemacs/zoom-frm-transient-state/body)
````
