### ISSUE TITLE
Link in "Spacemacs logo" section of README.md is broken

### ISSUE THREAD

**Issue by popzxc** [syl20bnr/spacemacs#14860]
Readme states:

> For Ubuntu users, follow this guide to [change the logo in Unity](http://splendidabacus.com/posts/2015/03/spacemacs-unity-icon/).

However, this page seems to not exist anymore.

**Comment by arifer612** [comment]
You can view what the link used to show from [an archive of the page](https://web.archive.org/web/20190128131716/http://splendidabacus.com/posts/2015/03/spacemacs-unity-icon/).

In short, it creates a .desktop file that starts Emacs using the Spacemacs logo instead. In summary:

Create a new file in `~/.local/share/applications/spacemacs.desktop` with the contents

    [Desktop Entry]
    Name=Spacemacs
    GenericName=Text Editor
    Comment=Edit text
    MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;
    Exec=emacs %F
    Icon=/PATH/TO/.emacs.d/core/banners/img/spacemacs.png
    Type=Application
    Terminal=false
    Categories=Development;TextEditor;
    StartupWMClass=Emacs

where the icon path directs to your `.emacs.d` directory.

You can create a PR to fill in this information into the README file, just make sure to properly credit the original author of the page (@cpaulik).
