### ISSUE TITLE
Elfeeds displays in unexpected ways: always missing date, often missing article source and tags, and is unstyled. 

### ISSUE THREAD

**Issue by komali2** [syl20bnr/spacemacs#14862]
#### Description :octocat:

Elfeeds is displaying strangely. Oftentimes, there is no styling applied, dates shown, tags shown, or name of source shown. Sometimes, at most, I can get at least the name of the rss source displayed, by repeatedly refreshing the feed, however scrolling through the list usually reverts to plain styling showing only article titles. I would expect Date, article title, article source, and tags to display.

#### Reproduction guide :beetle:
- Start Emacs
- run Elfeed (SPC a r e )
- If no feeds displayed, run `elfeed-update`.
- Observe that perhaps the feed is displaying partially correctly (with no dates)
- Press down arrow, observe reversion to basic styling

Elfeed version: "3.4.1"
Elfeed date formatting:

elfeed-search-date-format is a variable defined in ‘elfeed-search.el’.
Its value is ("%Y-%m-%d" 10 :right)

Often, it displays as such: 

![Screenshot from 2021-06-21 10-21-05](https://user-images.githubusercontent.com/8533113/122698784-a20b7600-d20d-11eb-9cbf-045dba1ab945.png)

Weirdly, I can get some styling, if I press "r" on an item to mark it as "read":

![Screenshot from 2021-06-21 10-21-17](https://user-images.githubusercontent.com/8533113/122698808-b18abf00-d20d-11eb-97b2-f0da43f5eed1.png)

Sometimes, after refreshing, it will at least display feed title and tags, but no date:

![Screenshot from 2021-06-21 10-21-40](https://user-images.githubusercontent.com/8533113/122698834-bfd8db00-d20d-11eb-814c-2437e9cdf4b8.png)

I would expect it to look like the example provided in the elfeeds repo:

![Elfeeds example](https://i.imgur.com/kxgF5AH.png)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ab6b165e9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lua emacs-lisp helm lsp multiple-cursors treemacs rust yaml go better-defaults git markdown
     (org :variables org-directory "~/Dropbox/org" org-projectile-file "~/Dropbox/org/projects.org" org-enable-roam-support t org-enable-org-journal-support t org-roam-directory "~/Dropbox/org/notes/" org-roam-index-file "~/Dropbox/org/notes/20200526213916-index.org" org-default-notes-file
          (concat org-directory "/inbox.org"))
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking c-c++ semantic syntax-checking version-control javascript python sql html typescript
     (erc :variables erc-server-list
          '(("irc.freenode.net" :port "6697" :ssl t :nick "komali2" :password
             (password-store-get "freenode.net"))))
     mu4e
     (vue :variables vue-backend 'lsp)
     (node :variables node-add-modules-path t)
     racket tern common-lisp colors react
     (elfeed :variables elfeed-feeds
             '("https://researchbuzz.me/feed/" "http://n-gate.com/index.rss" "https://mjtsai.com/blog/feed/" "https://craphound.com/feed/" "https://pluralistic.net/feed/" "http://www.fudzilla.com/?format=feed" "http://semiengineering.com/feed/" "https://www.eff.org/rss/pressrelease" "http://news.mit.edu/rss/topic/nanotech" "http://news.mit.edu/rss/topic/electrical-engineering" "http://www.pocketables.com/feed" "https://www.quantamagazine.org/feed" "https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml" "https://machinelearningmastery.com/blog/feed/" "http://news.mit.edu/rss/topic/artificial-intelligence2" "https://bair.berkeley.edu/blog/feed.xml" "https://openai.com/blog/rss/" "https://www.technologyreview.com/topic/artificial-intelligence/feed" "https://www.jefftk.com/news.rss")))
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
what's the color scheme?

when did the issue start to appear?

**Comment by komali2** [comment]
This issue happens regardless of colorscheme, I've tested in spacemacs-dark and spacemacs-light, though the color scheme pictured is [vscode-default-hight-contrast](https://github.com/komali2/Emacs-VSCode-Default-High-Contrast). 

The issue has always been there for me, since installation of elfeed a few weeks ago. I've spent the last week or so thinking maybe it's a misconfiguration issue and trying to fix it myself, but I've come up blank and so submitted this issue.

**Comment by lebensterben** [comment]
So does it appear fine some of the time or does it just never work?

**Comment by komali2** [comment]
Well, dates never display, and most of the time it looks like my first screenshot, with no tags or source displaying either.

**Comment by arifer612** [comment]
I have also faced this issue several times. I can reproduce it whenever I close an open `elfeed` buffer, split my frame into 2 windows and run `elfeed` again. It only fixes itself once the window with the `elfeed` buffer is the only active window in the frame and running `elfeed-update`.

However, is this really an issue caused by Spacemacs? The only visual configuration the `elfeed` layer comes from the use of [`elfeed-goodies`](https://github.com/algernon/elfeed-goodies). I have found that the issue goes away by disabling `elfeed-goodies`.

    (dotspacemacs-configuration-layers
      '(...
        (elfeed :variables elfeed-enable-goodies nil)
        ...
      ))

So I believe that this issue would be more appropriately solved when raised in `elfeed-goodies`.

**Comment by overchu** [comment]
I got the same two issues.

1. Sometimes only the headlines are displayed and nor formatting is applied.
2. No date is shown.

For 1: This might be a somewhat intended behaviour, the developer state in an post from 2013 when he introduced elfeed:

>  Entry Listing Customization
> 
> The search buffer you see when starting Elfeed, where entries are listed, can be customized a few different ways. First, this buffer does grow dynamically. After re-sizing the window/frame horizontally you just have to refresh the view by pressing g (an Emacs convention). How it fills out depends on the settings of these variables,
> 
>     elfeed-search-title-max-width
>     elfeed-search-title-min-width
>     elfeed-search-trailing-width
> 
> They control how wide the different columns should be as the window size changes.

When I view elfeed in a full screen the feed name and tags are shown and formatting is applied, when the window is smaller it's not. So it might have something to do with this.

For 2. Unfortunately disabling `elfeed-enable-goodies` didn't work for me.

**Comment by komali2** [comment]
This remains an issue for me 

elfeed version "3.4.1"
spacemacs version 0.999.0
emacs version 28.1.50

![Screenshot from 2022-10-03 16-26-55](https://user-images.githubusercontent.com/8533113/193533110-577c4f41-4a7c-4bae-8c3c-39b1a3b5c77f.png)

**Comment by lebensterben** [comment]
@komali2 

I'll keep this open but I won't work on this myself because I never used elfeed.

**Comment by komali2** [comment]
Ok, I'm adding this to look into for my next week
