### ISSUE TITLE
evil-define-key overwrites keybindings globally

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#14864]
#### Description :octocat:
evil-define-key overwrites keybindings globally, while defined only in specialized mode-map.

#### Reproduction guide :beetle:
- Start Spacemacs
- add scheme layer including guile implementation using
`(scheme :variables
         scheme-implementations '(guile))`
- now run `M-x run-guile`

Now check the keybinding `C-l` in evil-insert-state, in any buffer other than
the guile-repl buffer.

It is bound to `(geiser-repl-clear-buffer)`, while in the packages.el file of
the scheme layer, this binding is created with 
`(evil-define-key 'insert 'geiser-repl-mode-map
  (kbd "C-l") 'geiser-repl-clear-buffer)`
and should only work in the geiser-repl buffer.

I have noticed similar behavior, when ob-python has been loaded, and then
evil-define-key is used to bind e.g.
`(evil-define-key 'insert 'inferior-python-mode
  (kbd "C-l") 'erase-buffer)`

Also here the binding is created globally.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b0ef47a88)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp
 (scheme :variables scheme-implementations
         '(guile))
 helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by dalanicolai** [comment]
It happens also in Spacemacs using Emacs 28.0.50. I have also tested the evil-define-key definition in vanilla Emacs where it seems to behave correctly.

**Comment by lebensterben** [comment]
this is strange.
This macro per se should work only on the specified evil auxiliary map. (unless when the first argument is nil, then it's equivalent to define-key)

Do you observe similar "leaks" elsewhere?

**Comment by dalanicolai** [comment]
@lebensterben I have found it is a bug in evil. When I start Emacs from the evil repo dir with `make emacs` (as described [here](https://github.com/emacs-evil/evil/blob/master/CONTRIBUTING.md)), then evaluate:
```
(evil-define-key 'insert 'inferior-python-mode-map
  (kbd "C-l") 'right-char)
```
then, after running `M-x run-python`, the `C-l` binding works also in the scratch buffer (where it should not of course).

I will create a bug report upstream and create a reference to it here...

**Comment by lebensterben** [comment]
Well. If the scratch buffer has a keymap that inherits the keymap of inferior python mode, the evil key bindings will still be available there.

But it doesn't sound like the case.

**Comment by dalanicolai** [comment]
https://github.com/emacs-evil/evil/issues/1479

**Comment by dalanicolai** [comment]
I now see that I made (I hope only a little) embarassing mistake. So I quoted the keymap symbol and that seems to be the cause or this behavior. It was confusing because it all seemed to work (although not completely as intended).

So I will quickly close this issue :grin:

**Comment by lebensterben** [comment]
when the second argument is quoted, it's one of global, local, or the name of a minor mode.
