### ISSUE TITLE
Spacemacs-based LaTeX document preparation environment with the coding/command completion and human text writing suggestion at the same time.

### ISSUE THREAD

**Issue by hongyi-zhao** [syl20bnr/spacemacs#14863]
On Ubuntu 20.04, I'm using the self-compiled git master version of Emacs and noticed the [company-wordfreq.el](https://github.com/johannes-mueller/company-wordfreq.el) project which can be used as a human language texts helper based on word frequency dictionaries. Currently, this package is not included in spacemacs. I want to know if I can have a spacemacs-based LaTeX document preparation environment which has the coding/command completion and human text writing suggestion based on the above-mentioned project at the same time.

I've tried some configurations with vanilla Emacs as discussed [here](https://github.com/KaratasFurkan/.emacs.d/issues/1#issuecomment-864704954), but sill can't figure out the full working configuration.

Any hints will be highly appreciated.

Regards,
HY

**Comment by lebensterben** [comment]
Send PR if you can. I doubt it's ever useful to sort completions barely according to word frequency.

**Comment by hongyi-zhao** [comment]
I haven't figured out how to get them to work together yet. What do you think should be the useful completion technique for human text writing?

**Comment by lebensterben** [comment]
Word frequency ignores the contextual information. A useful completion should be based on the context, just like how any other completion works in programming language.

**Comment by lebensterben** [comment]
Modern, large scale English word frequency list was first available in 1940s.

Counting the occurrences of word in text corpus at least goes back to Hellenistic period.

Any naive implementation of completion based on word frequency is basically using an ancient technique invented before 0 AD.

**Comment by hongyi-zhao** [comment]
In my mind, the Gmail web client has the feature of the phrase-and-sentence-based semantic completion to some extent.

**Comment by lebensterben** [comment]
That's different from the naive word-frequency based completion.

**Comment by hongyi-zhao** [comment]
Yes. It's based on AI. Another possible alternative is to [call LanguageTool from within Emacs](https://github.com/mhayashi1120/Emacs-langtool).

**Comment by lebensterben** [comment]
See https://github.com/syl20bnr/spacemacs/blob/develop/layers/+tools/languagetool/README.org

**Comment by hongyi-zhao** [comment]
I tried [the company-mode backend for TabNine](https://github.com/TommyX12/company-tabnine). It looks great in a way, as shown below:

![image](https://user-images.githubusercontent.com/11155854/124225099-70fa4200-db39-11eb-92b7-9c9337a31a7c.png)

See [here](https://github.com/company-mode/company-mode/issues/1128#issuecomment-872710453) for the corresponding configuration.
