### ISSUE TITLE
Application freezes while executing py script on comint shell

### ISSUE THREAD

**Issue by sumitkumar97** [syl20bnr/spacemacs#14861]
#### Description :octocat:
Application freezes on macos and needs to be killed

#### Reproduction guide :beetle:
- Start Emacs
- Open a python script that accepts few inputs from stdin
- Execute script with space-m-c-c
- Switch to comint shell window
- Enter the stdin values
- Switch back to py script window
- Execute script with space-m-c-C
- Enter the stdin values
- Repeat execution a few times

*Observed behaviour:* :eyes: :broken_heart:
Application froze up after throwing error: Inferior Python exited abnormally with code 1

*Expected behaviour:* :heart: :smile:
Successful execution of python script

#### System Info :computer:
- OS: darwin
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b0ef47a88)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((python :variables python-backend 'anaconda python-test-runner 'pytest python-formatter 'yapf python-format-on-save t python-enable-yapf-format-on-save t python-sort-imports-on-save t)
 osx helm auto-completion git
 (shell :variable shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 semantic cscope)
```
- System configuration features: ACL GLIB GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM ZLIB

**Comment by lebensterben** [comment]
what's the Python script

**Comment by sumitkumar97** [comment]
@lebensterben This was the script I tried running, it's not a persistant issue but it does occur frequently for me
`from collections import Counter

mylist = [1, 2, 3, 1]
dict = Counter(mylist)
print(dict)
product = lambda a, b: a * b
a = int(input())
b = int(input())

if __name__ == '__main__':
    print(product(a, b))`

**Comment by lebensterben** [comment]
So you mean in this example you typed the first input `23` and hit `enter`, then it freezes?

**Comment by sumitkumar97** [comment]
Yes, that is correct. And sometimes it freezes even before I press `enter` , so if I'm trying to enter `23,` it freezes just after 2 and then I have to kill the app.

**Comment by lebensterben** [comment]
Use stable emasc.

**Comment by sumitkumar97** [comment]
I'm facing this issue on emacs 27.2 as well.

**Comment by lebensterben** [comment]
But how to reproduce this？ I cannot.

**Comment by sumitkumar97** [comment]
I'm able to reproduce it 3 out of 5 times on spacemacs. I tried running it on iterm and didn't face the issue, so it must be specific to spacemacs. It is only happening with files that accept input from stdin.

**Comment by lebensterben** [comment]
> I tried running it on iterm and didn't face the issue, so it must be specific to spacemacs

You got me lost here. You can start an emacs with Spacemacs within iterm too.

**Comment by sumitkumar97** [comment]
Sorry for the confusion. I didn't launch emacs inside iterm, I just ran the file in it:
`$ python3 temp.py`

**Comment by lebensterben** [comment]
So you didn't show that it's specific to Spacemacs.
Unless you show that the same problem doesn't show up with vanilla emacs.

**Comment by sumitkumar97** [comment]
You're right, this problem might be there in vanilla emacs as well. I don't know enough emacs, so I can't verify that. If this issue is not reproducible at your end, I guess we can close it. I'll be using a workaround for running files for now.

**Comment by lebensterben** [comment]
@sumitkumar97 
I'm not closing this issue because this could indeed be a bug.

If anyone else has come across similar freeze/hanging bug when interacting with Python/inferior shell/compilation mode, please comment.
