### ISSUE TITLE
Cannot automatically use doc-view-mode when openning microsoft word file

### ISSUE THREAD

**Issue by jia-j-chen** [syl20bnr/spacemacs#14873]
#### Description :octocat:
Cannot automatically use doc-view-mode when reading microsoft word file

#### Reproduction guide :beetle:
- Open a microsoft word file

*Observed behaviour:* :eyes: :broken_heart:
- doc-view-mode is not automatically used, I see the raw code of the word file rather than its formatted content.
- I have to manually use doc-view-mode by typing SPC SPC and then choose doc-view-mode.
- Then, the file's formatted content can be seen.

*Expected behaviour:* :heart: :smile:
- Expect the doc-view-mode to be automatically used and expect to see the file's formatted content.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cf21402)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((helm :variables helm-candidate-number-limit 1000)
 emacs-lisp git
 (markdown :variables markdown-live-preview-engine 'vmd)
 bibtex html csv org
 (chinese :variables chinese-enable-fcitx t chinese-fcitx-use-dbus t pyim-default-scheme 'microsoft-shuangpin)
 (latex :variables latex-enable-folding t latex-enable-auto-fill t)
 auto-completion ranger version-control pdf
 (mu4e :variables mu4e-use-maildirs-extension t mu4e-installation-path "/usr/share/emacs/site-lisp" mu4e-enable-async-operations t mu4e-maildir "/home/chenj/Maildir" mu4e-sent-folder "/Local_sent" mu4e-headers-full-search nil mu4e-headers-results-limit 500 mu4e-drafts-folder "/Drafts" mu4e-trash-folder "/Deleted_Messages" mu4e-attachment-dir "~/Downloads" mu4e-get-mail-command "offlineimap" mu4e-view-show-images t mu4e-view-show-addresses t mu4e-headers-date-format "%Y-%m-%d %H:%M" mu4e-compose-reply-to-address "jia.j.chen@foxmail.com" user-mail-address "jia.j.chen@foxmail.com" user-full-name "Jia CHEN" send-mail-function 'async-smtpmail-send-it message-send-mail-function 'async-smtpmail-send-it smtpmail-smtp-server "smtp.qq.com" smtpmail-smtp-service 465 smtpmail-stream-type 'ssl smtpmail-auth-credentials
       (expand-file-name "~/.authinfo.gpg")
       mu4e-headers-fields
       '((:date . 18)
         (:flags . 6)
         (:from . 15)
         (:to . 15)
         (:subject))
       mu4e-compose-signature "Jia CHEN @ http://chenjia.gsm.pku.edu.cn" mu4e-maildir-shortcuts
       '(("/INBOX" . 105)
         ("/PKU_Email" . 112)
         ("/Sent_Messages" . 115)))
 better-defaults markdown
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 spell-checking python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 bm
 (colors :variables colors-colorize-identifiers 'all))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Do you have anything that contains DOCX in `auto-mode-alist`?

**Comment by jia-j-chen** [comment]
I can see this in `auto-mode-alist`

`("\\.\\(?:PDF\\|DVI\\|OD[FGPST]\\|DOCX\\|XLSX?\\|PPTX?\\|pdf\\|djvu\\|dvi\\|od[fgpst]\\|docx\\|xlsx?\\|pptx?\\)\\'" . doc-view-mode-maybe)`

**Comment by jia-j-chen** [comment]
I try to open a file, whose extension is DOC rather than DOCX.

**Comment by jia-j-chen** [comment]
I add file extension "doc" to doc-view-mode. The problem is solved.

`(add-to-list 'auto-mode-alist
               '("\\.doc\\'" . doc-view-mode))
`
