### ISSUE TITLE
Error when editing SAS or Stata source code

### ISSUE THREAD

**Issue by jia-j-chen** [syl20bnr/spacemacs#14874]
#### Description :octocat:
Error when editing SAS or Stata source code

#### Reproduction guide :beetle:
- Open a SAS or Stata source code file (both are statistics programming language)
- Press i to enter the editing mode and starting typing

*Observed behaviour:* :eyes: :broken_heart:
- An error message shows up: sp--post-self-insert-hook-handler: (wrong-type-argument stringp nil)

*Expected behaviour:* :heart: :smile:
- No such an error message.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cf21402)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((helm :variables helm-candidate-number-limit 1000)
 emacs-lisp git
 (markdown :variables markdown-live-preview-engine 'vmd)
 bibtex html csv org
 (chinese :variables chinese-enable-fcitx t chinese-fcitx-use-dbus t pyim-default-scheme 'microsoft-shuangpin)
 (latex :variables latex-enable-folding t latex-enable-auto-fill t)
 auto-completion ranger version-control pdf
 (mu4e :variables mu4e-use-maildirs-extension t mu4e-installation-path "/usr/share/emacs/site-lisp" mu4e-enable-async-operations t mu4e-maildir "/home/chenj/Maildir" mu4e-sent-folder "/Local_sent" mu4e-headers-full-search nil mu4e-headers-results-limit 500 mu4e-drafts-folder "/Drafts" mu4e-trash-folder "/Deleted_Messages" mu4e-attachment-dir "~/Downloads" mu4e-get-mail-command "offlineimap" mu4e-view-show-images t mu4e-view-show-addresses t mu4e-headers-date-format "%Y-%m-%d %H:%M" mu4e-compose-reply-to-address "jia.j.chen@foxmail.com" user-mail-address "jia.j.chen@foxmail.com" user-full-name "Jia CHEN" send-mail-function 'async-smtpmail-send-it message-send-mail-function 'async-smtpmail-send-it smtpmail-smtp-server "smtp.qq.com" smtpmail-smtp-service 465 smtpmail-stream-type 'ssl smtpmail-auth-credentials
       (expand-file-name "~/.authinfo.gpg")
       mu4e-headers-fields
       '((:date . 18)
         (:flags . 6)
         (:from . 15)
         (:to . 15)
         (:subject))
       mu4e-compose-signature "Jia CHEN @ http://chenjia.gsm.pku.edu.cn" mu4e-maildir-shortcuts
       '(("/INBOX" . 105)
         ("/PKU_Email" . 112)
         ("/Sent_Messages" . 115)))
 better-defaults markdown
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 spell-checking python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 bm
 (colors :variables colors-colorize-identifiers 'all))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Can you add `ess` layer first?

**Comment by jia-j-chen** [comment]
I add the ess layer, and the error it still there.

@lebensterben You thought that I previously did not add the ess layer, but I already did. I installed it in dotspacemacs-additional-packages with
`use-package
                                      (ess
                                       :location
                                       (recipe :fetcher git
                                               :url "https://github.com/emacs-ess/ESS.git"
                                               :commit "14b9a3091916a1cb74dec7336e8461590dfc6a7d"
                                               :files ("lisp/*.el" "contrib/lisp/*.el" "doc/dir" "doc/*.texi" "etc")))
`
I did that because ess no longer supports Stata mode. So, I find a solution that uses jupyter to edit stata files. That solution requires some old release of the ess pacakge. Please see https://github.com/emacs-ess/ESS/issues/1033 and #13879

Now, even if I remove the above lines and install ess in dotspacemacs-configuration-layers, I get the same error message.

**Comment by lebensterben** [comment]
(setq debug-on-error t)
and post the traceback here

**Comment by jia-j-chen** [comment]
> (setq debug-on-error t)
> and post the traceback here

`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  re-search-forward(nil 2 t)
  sp--looking-back(nil nil nil)
  sp--looking-back-p(nil)
  sp-ess-roxy-str-p("'" insert comment)
  sp--do-action-p("'" insert)
  sp--all-pairs-to-insert(nil nil)
  sp--pair-to-insert()
  sp-insert-pair()
  sp--post-self-insert-hook-handler()
  self-insert-command(1 32)
  funcall-interactively(self-insert-command 1 32)
  call-interactively(self-insert-command nil nil)
  command-execute(self-insert-command)
`

**Comment by lebensterben** [comment]
you need to report it to upstream

https://github.com/Fuco1/smartparens

**Comment by jia-j-chen** [comment]
> https://github.com/Fuco1/smartparens

OK. I did that: https://github.com/Fuco1/smartparens/issues/1090

**Comment by jia-j-chen** [comment]
> you need to report it to upstream
> 
> https://github.com/Fuco1/smartparens

OK. I did that here: https://github.com/Fuco1/smartparens/issues/1090

At the same time, I found #12533 and followed it to disable smartparens. The error was gone.

**Comment by lebensterben** [comment]
Seems fixed in upstream and I'm closing now.
