### ISSUE TITLE
evil-escape no longer works

### ISSUE THREAD

**Issue by ielll** [syl20bnr/spacemacs#14870]
Updating packages causes 'fd' to no longer trigger evil-escape. I have confirmed that this is the case with a fresh spacemacs install as well.

**Comment by duianto** [comment]
Could you provide some reproduction steps,
and your system info, press `SPC h d s` to copy the info to your clipboard.

I cloned Spacemacs about an hour ago,
and `fd` exits insert state as expected for me
in the scratch buffer `SPC b s`

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 443311c8f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by agzam** [comment]
Manually restarting evil-escape-mode temporarily fixes the issue.

**Comment by duianto** [comment]
Correction, your right there was an issue with `fd` after the recent which-key update.
Error at init time after updating which-key package #14865

I hadn't restarted since I had loaded the just pushed fix:
Revert "Fix which-key entries: gr and gs in dired and magit" https://github.com/syl20bnr/spacemacs/pull/14869

Without the fix `fd` didn't work.

But pull the latest develop branch and it should start working again.

**Comment by ielll** [comment]
Interestingly when I retry spacemacs from a fresh install it works now (it didn't last night). But updating my existing install still causes a failure. Here's my setup:

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 120ce6959)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory
                  (file-expand-wildcards "~/.emacs.d/elpa/*/develop/yasnippet-*/snippets"))
 bibtex csv emacs-lisp
 (ess :variables ess-assign-key "\255")
 git ivy javascript html
 (julia :variables julia-backend 'lsp)
 (latex :variables latex-enable-auto-fill nil)
 lsp markdown
 (python :variables python-backend 'lsp python-lsp-server 'pyright lsp-pyright-auto-import-completions nil)
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'vterm)
 shell-scripts syntax-checking
 (version-control :variables version-control-global-margin t version-control-diff-tool 'git-gutter))
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM MODULES THREADS JSON PDUMPER GMP

**Comment by ielll** [comment]
Fixed with most recent commit..
