### ISSUE TITLE
Save screenspace by shortening spacemacs function namespace

### ISSUE THREAD

**Issue by kecman** [syl20bnr/spacemacs#1487]
When using guide key the popup buffer can stick out quite far to fit in the function names, this could be improved by replacing `spacemacs/<function-name>` with  `sp/<function-name>` or similar.

**Comment by syl20bnr** [comment]
I understand this proposal but it would be a lot of work to do this and `sp` prefix is already taken by `smartparens`. We plan to have a better guide-key buffer with actual description of a key binding instead of its bound function name.

**Comment by TheBB** [comment]
There are tools in which-key for doing this without actually changing the function names.
