### ISSUE TITLE
[develop] `unicode-fonts-enable-ligatures t` freezes Emacs when opening Rust files (via `lsp`)

### ISSUE THREAD

**Issue by stradicat** [syl20bnr/spacemacs#14878]
#### Description :octocat:
Enabling `unicode-fonts-enable-ligatures t` in the  `unicode-fonts` layer freezes Emacs when opening Rust files (via `lsp`)

#### Reproduction guide :beetle:
- Start Emacs
- Hit `SPC f e d` to edit the dotfile
- Add the `unicode-fonts` layer with the following option:
```elisp
(unicode-fonts :variables
               unicode-fonts-enable-ligatures t
               )
```
- Restart Emacs
- Open a Rust file (i.e. `main.rs`)

*Observed behaviour:* :eyes: :broken_heart:
Emacs starts, but opening a Rust file hangs the program. It does not react to `C-g`; Emacs must be killed manually.

*Expected behaviour:* :heart: :smile:
Emacs opens the file and applies the expected ligatures to the expected symbols, using a ligature-patched font such as Hasklig.

*Workaround:*
In the following code, defining exactly which ligatures to show prevents Emacs from hanging:
```elisp
(unicode-fonts :variables
               unicode-fonts-enable-ligatures t
               unicode-fonts-ligature-set '("==" "===" "!=" "!==" "||" "&&" "<=" "=>" "<-" "->" "=/=" "=>=" "=<=")
               )
```
However, one would have to define *every* possible ligature, thus defeating the purpose of having a layer that takes care of the functionality.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 64fed6f7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-ccls)
 csv
 (dart :variables dart-backend 'lsp lsp-dart-flutter-sdk-dir "~/flutter/bin/cache/dart-sdk" lsp-dart-sdk-dir "~/flutter/bin/cache/dart-sdk/")
 (go :variables go-backend 'lsp go-use-golangci-lint t)
 graphql
 (html :variables web-fmt-tool 'prettier)
 (javascript :variables javascript-backend 'lsp javascript-fmt-tool 'prettier javascript-import-tool 'import-js javascript-repl 'nodejs js2-include-node-externs t)
 (json :variables json-fmt-tool 'prettier)
 (kotlin :variables kotlin-backend 'lsp kotlin-lsp-jar-path "/home/dmayr/kotlin-language-server/server/bin/kotlin-language-server")
 markdown nginx plantuml
 (php :variables php-backend 'ac-php-core)
 (python :variables python-backend 'lsp python-lsp-server 'pyls)
 react
 (rust :variables cargo-process-reload-on-modify t rust-backend 'lsp lsp-rust-server 'rust-analyzer)
 shell-scripts systemd
 (sql :variables sql-capitalize-keywords t)
 (typescript :variables typescript-backend 'lsp)
 (vue :variables vue-backend 'lsp vue-fmt-tool 'prettier)
 windows-scripts yaml
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults
 (cmake :variables cmake-backend 'lsp cmake-enable-cmake-ide-support t)
 dap debug docker emacs-lisp emoji
 (geolocation :variables geolocation-enable-automatic-theme-changer t)
 git github gtags helm import-js lsp meson multiple-cursors
 (treemacs :variables treemacs-use-collapsed-directories 3 treemacs-use-git-mode 'deferred treemacs-use-filewatch-mode t)
 (org :variables org-enable-bootstrap-support t org-enable-hugo-support t org-enable-github-support t)
 pandoc prettier restclient
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables enable-flyspell-auto-completion t)
 sql syntax-checking
 (unicode-fonts :variables unicode-fonts-enable-ligatures t unicode-fonts-ligature-set
                '("==" "===" "!=" "!==" "||" "&&" "<=" "=>" "<-" "->" "=/=" "=>=" "=<="))
 version-control web-beautify)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by dennismayr** [comment]
According to the _Hasklig_ maintainers, the following symbols have been implemented:
`<*` `<*>` `<+>` `<$>` `***` `<|` `|>` `<|>` `!!` `||` `===` `==>` `<<<` `>>>` `<>` `+++` `<-` `->` `=>` `>>` `<<` `>>=` `=<<` `..` `...` `::` `-<` `>-` `-<<` `>>-` `++` `/=` `==`

However, after adding each symbol to the `unicode-fonts-ligature-set` group, I found that adding ligatures for the following symbols completely freeze Emacs when opening Rust files:
`..` `...`

**Comment by lebensterben** [comment]
Upstream bug but it's unresolved.
See
https://github.com/emacs-lsp/lsp-mode/issues/1893
