### ISSUE TITLE
Issues with iedit

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#1488]
In *iedit* mode
*    `M-D` `M-L` `M-U` : symbol/word does not include uppercase letters (it should)
*    `M-R` `M-SPC` `M-N` : does not work
*    `M-S-SPC` `M-S-N` : works
*    `M-S-R` : works, but just right after `SPC s e`

`f` or `t` breakes evil-escape in *iedit* mode for the whole emacs session -
`SPCse fa fd` -> "can't find d" -> `<Esc> SPCse fd` -> "can't find d"

**Comment by StreakyCobra** [comment]
I tried to reproduce all this, most of them seems working for me, but I'm not sure to understand all the problems. @xged Can you give an update about what is still a problem on last spacemacs version?

**Comment by xged** [comment]
All working fine now (`M SPC` is 'occupied' by XFCE).
