### ISSUE TITLE
Spacemacs cannot verify the authenticity of the stable ELPA archive (spacelpa)

### ISSUE THREAD

**Issue by bshanks** [syl20bnr/spacemacs#14885]
When I start spacemacs, I get:

"
Spacemacs cannot verify the authenticity of the stable ELPA archive (spacelpa)!
The reason is: Verification failed! It is strongly advised to NOT install the stable ELPA repository and report it on GitHub.

Do you still want to install the stable ELPA repository ? (y or n) 
"

I just upgraded my OS (Pop!_OS, upgraded to version 21.04). This didn't happen before the upgrade.

I am reporting on GitHub as requested. What should I do in order to continue to use Spacemacs?

**Comment by mixmixmix** [comment]
I think the verification is not fully functional yet, you can see people being asked to test it now: https://github.com/syl20bnr/spacemacs/issues/12652

Someone else can offer you more detailed explanation, I do not fully understand the current state of things,

**Comment by bshanks** [comment]
Thanks

**Comment by lebensterben** [comment]
let's close this since `spacelpa` is not likely to be fully implemented in near future.

**Comment by bshanks** [comment]
If this is intended behavior for the foreseeable future, then I suggest removing the error message (and leaving the issue open until that is done).

**Comment by lebensterben** [comment]
@bshanks 
We accept PR.

**Comment by bshanks** [comment]
This still occurs in 2025 when I delete my elpa directory and then start emacs/spacemacs.
