### ISSUE TITLE
python3 completion working in Inferior Python REPL but not in source code buffer

### ISSUE THREAD

**Issue by zbinkz** [syl20bnr/spacemacs#14914]
Hi,

Running 0.300.0@26.1 develop on Debian stable 10.9. This is my layer setup:

``` dotspacemacs-configuration-layers
  '(
     javascript
     (python :variables
             python-backend 'anaconda)
     (auto-completion :variables
                      auto-completion-enable-sort-by-usage t
                      auto-completion-enable-snippets-in-popup t)
     better-defaults
     emacs-lisp
     git
     helm
     markdown
     multiple-cursors
     org
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     syntax-checking
     version-control
     treemacs
     gpu
     (lsp :variables
          lsp-lens-enable nil
          lsp-enable-file-watchers nil)
     (cmake :variables
            ;; cmake-backend 'lsp
            cmake-backend 'company-cmake
            cmake-enable-cmake-ide-support t
            )
     (c-c++ :variables
            c-c++-backend 'lsp-ccls
            c-c++-enable-clang-support t
            c-c++-lsp-enable-semantic-highlight 'rainbow
            c-c++-default-mode-for-headers 'c-or-c++-mode
            c-c++-adopt-subprojects t
            )
     shell-scripts
     )
```

Running python3 using `(run-python "python3")`. In python mode I get completion for normal Python modules (math, numpy, etc.) in the source code buffer and the Inferior Python REPL. Any other imported modules, like from pip3, completion works only in Inferior Python. Moreover, importmagic and epc are not found judging from the error message in *Messages*:

`Importmagic and/or epc not found. importmagic.el will not be working.`

However they are both installed through pip3 (importmagic 0.1.7 and epc 0.0.5).

Any idea what's wrong?

Thanks

**Comment by zbinkz** [comment]
Importmagic/epc error message gone after I installed them using pip for python2. Completion issues still the same.

**Comment by zbinkz** [comment]
It seems completions work for python2 packages regardless of the installation source (pip, Debian repos, official Python2 distribution) and only the official Python3 distribution.

**Comment by zbinkz** [comment]
Ended up reinstalling into a python3 venv. Now all python3 completions work in anaconda-mode. Still rather frustrating not to have it working for Debian repos packages.

**Comment by smile13241324** [comment]
You need to double check where your Python executable points to. From your description I assume "python" is pointing to python2 instead of python3. Please start a shell from emacs and check the content of "python --version".

Independent of the issues you are reporting, you should be aware that anaconda is deprecated and will only provide limited completions. For full IDE support you need to switch to LSP.
