### ISSUE TITLE
autocompletion UX improvements break escape keys starting with "k"

### ISSUE THREAD

**Issue by BrianHicks** [syl20bnr/spacemacs#1491]
## Test

 - set `evil-escape-key-sequence` to `"kj"`
 - open any buffer, and try to escape from insert mode

## Expected

Evil returns the buffer to normal mode

## Actual

"kj" is typed.

Commit e9f09d03e6726e7273bc446eb2b8a783a7d6a326 introduced this, it looks like if it's in insert mode it intercepts all "k" keypresses. My escape sequence is "kj", and this change means I can't use it anymore. Should the system detect the start of the escape sequence and fix the new keybinding?

**Comment by BrianHicks** [comment]
I'm not sure if this is related, but I tried setting it to "df" too. That works for escaping, but when I select a block of text and hit "d", it doesn't delete.

**Comment by syl20bnr** [comment]
Thank you for the report, I'll check tonight.

**Comment by syl20bnr** [comment]
Should be fixed in develop.
