### ISSUE TITLE
Python-mode lagging

### ISSUE THREAD

**Issue by sapristi** [syl20bnr/spacemacs#14926]
#### Description :octocat:

Working in python buffers is very slow. Any input (arrows, text input) has half a second delay.
It seems that the problem comes from `python-shell-interpreter` variable being set to `ipython`.

#### Reproduction guide :beetle:

- ipython is installed in user environment (binary in ~/.local/bin/ipython)
- python layer is installed
- Start Spacemacs
- Open a python buffer

*Observed behaviour:* :eyes: :broken_heart:

Working in python buffers is very slow. Any input (arrows, text input) has half a second delay.

*Expected behaviour:* :heart: :smile:

No noticeable lag when doing basic stuff.

#### System Info :computer:
- OS: gnu/linux (manjaro)
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5b3786f52)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(colors systemd html typescript react
        (python :variables python-backend 'lsp python-lsp-server 'pyright)
        shell-scripts nginx docker yaml
        (sql :variables sql-auto-indent nil)
        emacs-lisp git helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Additional information

I am using python-lsp, but noticed the same problem when using raw python layer.
I noticed `ipython` was called by emacs in `htop` when performing arrow movements (one exact command was `/usr/bin/python ~/.local/bin ipython --version`. I think there was another one, but didn't have time to read the full line).

The issue does not seem to happen when using python mode in `emacs -q`.

I have also tried setting `python-shell-interpreter` in  `dotspacemacs/user-config`, but the value of `python-shell-interpreter` was still set to `ipython` after opening a python file.

Uninstalling ipython seems to solve the issue.

**Comment by dalanicolai** [comment]
@sapristi I can not reproduce this. Can you post the output of:
`/usr/bin/python ~/.local/bin ipython --version`

and

check (and post) if you see any python processes in `M-x list-processes`?

**Comment by sapristi** [comment]
Hello, 
thanks for getting back to me. Here are the results:

```
❯ /usr/bin/python ~/.local/bin/ipython --version
7.25.0
```

`M-x list-processes`
```
pyright         28974   run     *pyright*                 --           Main         /usr/bin/pyright-langserver --stdio
pyright stderr  --      open    *pyright::stderr*         --           Main         
```

**Comment by Trapez** [comment]
I don't see any epc processes.

Keep all the python dependencies for spacemacs in the project virtualenv. You should at least have epc, importmagic, isort and ipython installed.

mkdir myproject && cd myproject && pipenv install --dev epc importmagic ipython isort

**Comment by sapristi** [comment]
Here's the output after installing the deps in the python user env:

```
epc:server:2    57276   run      *epc:server:2*           /dev/pts/1   Main         ipython /home/sapristi/.config/emacs/elpa/27.2/develop/importmagic-20180520.303/importmagicserver.py
pyright         57292   run     *pyright*                 --           Main         /usr/bin/pyright-langserver --stdio
pyright stderr  --      open    *pyright::stderr*         --           Main         
```

Installing those packages in the venv for a project didn't change anything (even when browsing files of said project). Pyright is using the correct venv (configured in `pyrightconfig.json`), but I'm not sure emacs is picking the venv. `ipython` was already installed in my venv without issue.

**Comment by Trapez** [comment]
You're not supposed to set anything in pyrightconfig.json. You tell spacemacs to activate the virtualenv for you. Look at the last line in my layer config.

```
dotspacemacs-configuration-layers
   '(

     (python :variables
             python-lsp-backend 'lsp
             python-lsp-server 'pyright
             python-fill-column 99
             python-formatter 'black
             python-format-on-save t
             python-test-runner 'pytest
             python-sort-imports-on-save t
             python-pipenv-activate t)

```

**Comment by sapristi** [comment]
Ok so I tried to fixed my layer config: from
```
    (python :variables
             python-backend 'lsp
             python-lsp-server 'pyright
             lsp-pyright-venv-path "/home/sapristi/.virtualenvs"
             )
```

to 
```
    (python :variables
             python-backend 'lsp
             python-lsp-server 'pyright
             python-pipenv-activate t
             )
```

Unfortunately, it seems pyright just won't pick any activated environment (even after restarting: `,-b-r`)

**Comment by Trapez** [comment]
The virtualenv folder needs to be in the project folder and it must be called .venv. Ensure pipenv creates the virtualenv in the project by export PIPENV_VENV_IN_PROJECT=1.

**Comment by Trapez** [comment]
I wrote a note on using Python in Spacemacs.

https://gist.github.com/Trapez/58d1526f7c06584af99e08709069f54d

**Comment by sapristi** [comment]
Thanks @Trapez ! 
I'm not sure I want to use `pipenv` yet, but using any of the methods you described to have the right venv activated seems to do the trick ! And indeed, having `ipython` installed as a local user package does not makes emacs freeze anymore.

With the information you provided, I think I found the where the issue comes from:  I had a file called `.venv` at the root of the project, containing only the name of the virtualenv (this file is used by [virtualfish](https://github.com/justinmayer/virtualfish); see https://virtualfish.readthedocs.io/en/latest/plugins.html#auto-activation-auto-activation ). I guess `pipenv.el` gets fooled by this file or something like that.

**Comment by dalanicolai** [comment]
As far as I know, switching between (buffer-local) virtual environments [should work fine with `pyvenv` also](https://develop.spacemacs.org/layers/+lang/python/README.html#automatic-activation-of-local-virtual-environment). At least it did in [this](https://github.com/syl20bnr/spacemacs/pull/13927).
