### ISSUE TITLE
org layer not fully compatible with org-roam v2

### ISSUE THREAD

**Issue by kappa** [syl20bnr/spacemacs#14929]
#### Description :octocat:
org-roam v2 replaced org-roam v1 on July 17.

#### Reproduction guide :beetle:
- Start Emacs
- "SPC a o r f"

*Observed behaviour:* :eyes: :broken_heart:
"Wrong type argument: org-roam-find-file"

*Expected behaviour:* :heart: :smile:
org-roam notes browser should open.

The new org-roam does away with files and now works with "nodes". The relevant command is called "org-roam-node-find".

There are probably other incompatibilities.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ba8074b60)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 bm dap dtrt-indent git gtags helm helpful imenu-list lsp multiple-cursors
 (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
 syntax-checking templates treemacs typography version-control unicode-fonts ibuffer colors command-log copy-as-format dash debug deft
 (org :variables org-enable-org-journal-support t org-journal-enable-agenda-integration t org-journal-dir "~/org/journal" org-enable-roam-support t org-projectile-file "TODO.org")
 outshine pandoc pdf ansible asm c-c++ csv docker emacs-lisp go graphql graphviz html javascript json markdown nginx perl5 raku plantuml python rust scheme shell-scripts terraform yaml kappa olivetti)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER GMP

**Comment by kappa** [comment]
Other incompatibilities: org-roam-insert replaced with org-roam-node-insert, org-roam-toggle-buffer-display with org-roam-toggle-buffer.

**Comment by ZacheryPD** [comment]
I actually came here to look for this, too.  The current PR looks like it should be fine to get things started, with the one exception that it should probably call the setup method as well. Hopefully this gets merged soon!

**Comment by sdorof1** [comment]
@kappa Please, disable also `global-page-break-lines-mode` because it will break the org-roam buffer:

`
:hook (org-roam-mode . (lambda () (global-page-break-lines-mode -1)))
`

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Rename commands for org-roam v2 compatibility #14930
