### ISSUE TITLE
Make org-brain optional

### ISSUE THREAD

**Issue by WarFox** [syl20bnr/spacemacs#14938]
Currently `org-brain` is installed on default with `org` layer. 

I don't use org-brain and instead use org-roam. I thought for many people making `org-brain` optional would be a good idea.

I've made a PR for the same https://github.com/syl20bnr/spacemacs/pull/14924

Please take a look and let me know if this is a good idea or not. Thank you

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Add flag to enable org-brain support making it optional #14924

**Comment by WarFox** [comment]
thanks @duianto

closing this issue now
