### ISSUE TITLE
Develop branch missing `org-agenda` `SPC a o [...]` shortcuts.

### ISSUE THREAD

**Issue by comalice** [syl20bnr/spacemacs#14937]
#### Description :octocat:

Changed `org-agenda` shortcuts. I had gotten used to `SPC a o <options>` for org-agenda and now those shortcuts are no longer in spacemacs?

#### Reproduction guide :beetle:

- Fresh install of emacs, spacemacs on `develop branch`.
- Start Emacs
- Press `SPC a o t`

*Observed behaviour:* :eyes: :broken_heart:

- Output "SPC a o unknown"

*Expected behaviour:* :heart: :smile:

- An org-agenda todo buffer opens.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a2ab0a023)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
N/A
```

**Comment by dalanicolai** [comment]
Those shortcuts are still available here. Did you try installing the `org layer`?

**Comment by emacs18** [comment]
`SPC a o` prefix key has at least 14 subkeys including `SPC a o t`, `SPC a o o`, etc.
This is using vanilla `develop` branch of spacemacs and with vanilla `.spacemacs` content except to enable few layers including `org` layer.
Thus I too would suspect the problem is that `org` layer was not enabled after a fresh install of spacemacs.

**Comment by comalice** [comment]
Looks like it was a configuration issue on my part. Closing this ticket.
