### ISSUE TITLE
Symbol's function definition is void: which-key-declare-prefixes   ,after i install it from master branch and start up it

### ISSUE THREAD

**Issue by googoo-s** [syl20bnr/spacemacs#14936]
Symbol's function definition is void: which-key-declare-prefixes

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

Debugger entered--Lisp error: (void-function which-key-declare-prefixes)
  (which-key-declare-prefixes dotspacemacs-leader-key '("root" . "Spacemacs root") dotspacemacs-emacs-leader-key '("root" . "Spacemacs root") (concat dotspacemacs-leader-key " m") '("major-mode-cmd" . "Major$
  spacemacs-bootstrap/init-which-key()
  funcall(spacemacs-bootstrap/init-which-key)
  (let* ((pkg-name (eieio-oref pkg ':name)) (owner (car (eieio-oref pkg ':owners)))) (spacemacs-buffer/message (format "Configuring %S..." pkg-name)) (mapc #'(lambda (layer) (if (configuration-layer/layer-us$
  configuration-layer//configure-package(#<cfgl-package cfgl-package-1fe43b657cf0>)
  (cond ((eq 'dotfile (car (eieio-oref pkg ':owners))) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//configure-package pkg)))
  (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref pkg ':excluded) (not (eieio-oref pkg ':protected))) (sp$
  (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ':lazy-install) (spacemacs-buffer/message (format "%S ignored since it can be lazily installed." pkg-name))) ((and (eieio-oref$
  (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ':lazy-install) (spacemacs-b$
  (let ((--dolist-tail-- packages) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg (configuration-layer/get-package pkg-name))) (cond (($
  configuration-layer//configure-packages-2((async bind-key bind-map diminish evil hydra use-package which-key))
  configuration-layer//configure-packages((abbrev ace-jump-helm-line ace-window archive-mode async auto-compile bind-key bind-map bookmark centered-buffer-mode conf-mode debug diminish dired dired-x edebug e$
  configuration-layer/sync()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-v$
  eval-buffer(#<buffer  *load*> nil "/Users/edz/.config/emacs/init.el" nil t)  ; Reading at buffer position 1264
  load-with-code-conversion("/Users/edz/.config/emacs/init.el" "/Users/edz/.config/emacs/init.el" t t)
  load("/Users/edz/.config/emacs/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1fe43aa49f2d>) #f(compiled-function () #<bytecode 0x1fe43aa27d85>) t)
  command-line()
  normal-top-level()

**Comment by sunlin7** [comment]
It seem you don't have which-key package, https://github.com/justbur/emacs-which-key , which should be auto downloaded when you starting emacs with Spacemacs.

**Comment by googoo-s** [comment]
done

**Comment by RCoeurjoly** [comment]
Why is not installed with Spacemacs? I am getting the same error.

**Comment by giuliano108** [comment]
This also happens if you *do* have `which-key` installed. Spacemacs (`master` branch) uses some symbols that no longer exist in newer `which-key` versions. https://github.com/syl20bnr/spacemacs/commit/6a84fb3c0eac1fbd75543e2a48f1932e75b28a08 (which is not on `master` yet) is the fix, either apply that diff to your own branch or switch to `origin/develop`. I guess downgrading `which-key` would work too.
