### ISSUE TITLE
org-babel-execute-buffer and org-babel-execute-subtree are not working

### ISSUE THREAD

**Issue by mario-bermonti** [syl20bnr/spacemacs#14941]
#### Description :octocat:
`org-babel-execute-buffer` (, b b) and `org-babel-execute-subtree` (, b s) are not working.

I can confirm it happens in python and basic-elisp code blocks

#### Reproduction guide :beetle:
- Start Emacs
- Open any org file
- Write some source code blocks
- Run any of the above functions

*Observed behaviour:* :eyes: :broken_heart:
Whenever I try to execute the src code blocks in an org file using
`org-babel-execute-buffer` (, b b) or `org-babel-execute-subtree` (, b s) I get
an the following error: `org-babel-execute-buffer: Symbol’s function definition is void: org-outline-overlay-data` and the code blocks are not executed.

*Expected behaviour:* :heart: :smile:
The code blocks should be executed.

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4bcd16d6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust ruby yaml csv javascript html
      (python :variables python-test-runner 'pytest python-formatter 'black python-fill-column 88)
      helm auto-completion better-defaults emacs-lisp git markdown
      (org :variables org-enable-github-support t org-enable-reveal-js-support t org-babel-python-command "python3")
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'vterm shell-default-term-shell "/bin/zsh")
      spell-checking syntax-checking version-control themes-megapack pandoc ipython-notebook)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
org-babel-execute-buffer: Symbol’s function definition is void: org-outline-overlay-data 
```

**Comment by duianto** [comment]
It seems to be working as expected for me in both Manjaro and Windows.

With this example file:
`source-block.org`
```elisp
* source block test
#+begin_src elisp
  (message "test")
#+end_src
```

either of these key bindings:
```
 , b b                                             ;; org-babel-execute-buffer
 , b s                                             ;; org-babel-execute-subtree
```
appends the following to the bottom of the buffer:
```
#+RESULTS:
: test
```

<details>
<summary>System Info</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 47f350726)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey emacs-lisp git helm html javascript multiple-cursors
                 (org :variables org-enable-org-brain-support t)
                 spell-checking syntax-checking version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by mario-bermonti** [comment]
Here is a very simple snippet with which it happens:
```
* trees
** tree 1
   #+begin_src python :results output
     print("Hello word")
   #+end_src
   
** tree 2
   #+begin_src python :results output
     print("Hello word 2")
   #+end_src
```

I tried searching for `org-outline-overlay-data` but spacemacs doesn't find anything ( , h d f) 🥴

**Comment by mario-bermonti** [comment]
Any ideas about how to go about identifying the source of the problem?

**Comment by duianto** [comment]
That snippet also works for me.

This seems like it might be the source of the issue:
org-mode: expand-region is broken https://github.com/syl20bnr/spacemacs/issues/12099#issuecomment-480904298
>The problem is that expand-region is byte-compiled with the built-in org, but then the org layer installs a newer version from ELPA which has changed the definition of the org-save-outline-visibility macro, leading to the symbol error.
>
>If I delete~/.emacs.d/elpa/*/develop/expand-region* spacemacs re-installs expand-region, compiles it against the new version of org, and everything works as it should.

Another solution is suggested on SE:
https://emacs.stackexchange.com/questions/49066/need-help-with-expand-region-symbol-s-function-definition-is-void-org-outlin

>As an alternative, you can try to update/reinstall the expand-region package via M-x package-reinstall RET expand-region RET (you might have to do M-x package-refresh-contents RET first to update your package index from ELPA.)

**Comment by mario-bermonti** [comment]
I deleted~/.emacs.d/elpa//develop/expand-region and when spacemacs re-installed it, it started working again. 

Thank you!

P.D. I tried reinstalling expand-region without deleting it first and it didn't work for me.

**Comment by mario-bermonti** [comment]
Should I close this or should I wait until it is "completely" solved?

**Comment by duianto** [comment]
Hopefully someone with more knowledge about this issue will figure out a permanent solution.
But let's close this for now.
