### ISSUE TITLE
Are all the spacemacs bindings implemented based on hydra?

### ISSUE THREAD

**Issue by hongyi-zhao** [syl20bnr/spacemacs#14946]
It's well known that [hydra](https://github.com/abo-abo/hydra) is a famous Emacs short key grouping and simplification tool. I'm not sure if spacemacs bindings implemented based on hydra in the core level? Any hints will be highly appreciated.

Regards,
HY

**Comment by emacs18** [comment]
`spacemacs|define-transient-state` is a low level macro used many times to define transient keymaps.
This macro calls `defhydra`.  Thus I suppose spacemacs makes good use of `hydra`.
