### ISSUE TITLE
Org-contrib is unavailable

### ISSUE THREAD

**Issue by lazzalazza** [syl20bnr/spacemacs#14948]
#### Description :octocat:
Package org-contrib is unavailable

#### Reproduction guide :beetle:
- Start Emacs
- Intall/Update Org

*Observed behaviour:* :eyes: :broken_heart:

During package refreshing:

--> refreshing package archive: gnu... [3/3]
--> installing package: org-contrib@org... [1/1]
Package org-contrib is unavailable. Is the package name misspelled?

Subsequently, org-mode doesn’t work.

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: darwin
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a7e8bd7e6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml helm html
     (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup 'complete)
     bibtex deft ibuffer
     (latex :variables latex-enable-folding t latex-enable-magic t latex-build-command "LatexMk")
     lsp markdown
     (org :variables org-enable-roam-support t org-enable-org-journal-support t)
     pdf pandoc python
     (ranger :variables ranger-show-preview t ranger-show-hidden t ranger-preview-delay 0.06 ranger-show-literal nil ranger-cleanup-eagerly t ranger-modify-header nil)
     rust
     (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom)
     spell-checking themes-megapack
     (typography :variables typography-enable-typographic-editing t)
     version-control)
```
- System configuration features: ACL GLIB GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lazzalazza** [comment]
I've tried to put this in the user-inti() function but this is weirdly ineffective.
Is there anything else I could try? The *Messages* and *Warngings* buffers are not of great help...

**Comment by tshu-w** [comment]
Oh, Sorry, spacemacs have already added nongnu https://github.com/syl20bnr/spacemacs/blob/eda7e193701742c58857e556b60db9bff6896916/core/core-configuration-layer.el#L2603, where `org-contrib` is available. I don't know why. Maybe you can try latest commit and default template config to see if issue still here.

**Comment by thanhvg** [comment]
Update your dev branch, it is too far behind. I remember @smile13241324 did something recently to deal with org-contrib

**Comment by emacs18** [comment]
@lazzalazza Your version is from 6 months ago.  You need to pick up https://github.com/syl20bnr/spacemacs/commit/63197014cc3c9f4bcd64be112543c859eec629d9 which was checked in two months ago.
