### ISSUE TITLE
[Feature Request] toggle pop-shell should remember its old path

### ISSUE THREAD

**Issue by c02y** [syl20bnr/spacemacs#14947]
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>
When I use `SPC-'` to toggle pop-shell(I use the default eshell), it should remember its old path. 

For instance, I open a buffer from /path/a, after I execute `SPC-'` to activate the pop-shell, I change my PWD to `cd ../b`(this is the directory I execute commands in), then I use `SPC-'` again to hide the terminal window or just switch back to the buffer window, I activate it again using `SPC-'`, the history content is still there, but the PWD is changed according to the currently opened buffer that I execute `SPC-`', I believe it should remember its old path, or at least I can set it using a variable.
#### Reproduction guide :beetle:
- Start Emacs
- `SPC-'`
- change your PWD using `cd`
- `SPC-'` to hide the terminal or just switch to the buffer window without hiding the terminal window
- 'SPC-'` to active it again, check the path in the terminal, it is changed

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

The PWD is changed according to the path of the opened buffer every time when I `SPC-`' 

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

Remember its path when I toggle the pop-shell using `SPC-'`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 431dfd5ad)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 better-defaults syntax-checking colors git
 (ivy :variables ivy-enable-advanced-buffer-information t)
 emacs-lisp markdown vimscript
 (rust :variables cargo-process-reload-on-modify t cargo-process--open-file-after-new t cargo-process--enable-rust-backtrace t cargo-process--command-flags "--color never" lsp-rust-server 'rls)
 yaml
 (treemacs :variables treemacs-position 'right treemacs-no-png-images t treemacs-use-scope-type 'Perspectives treemacs-display-in-side-window nil treemacs-show-cursor t)
 shell-scripts
 (python :variables python-backend 'lsp python-test-runner
		 '(pytest nose)
		 python-formatter 'black python-sort-imports-on-save t python-lsp-server 'pyright)
 (ipython-notebook :variables ein:jupyter-default-notebook-directory "~/ipynb" ein:output-area-inlined-images t)
 (conda :variables conda-anaconda-home "~/anaconda3")
 (go :variables go-use-golangci-lint t godoc-at-point-function 'godoc-gogetdoc)
 (org :variables org-want-todo-bindings t org-enable-epub-support t org-enable-sticky-header t)
 (shell :variables shell-default-shell 'eshell shell-enable-smart-shell t close-window-with-terminal t shell-default-full-span nil)
 (spell-checking :variables)
 (version-control :variables version-control-diff-tool 'git-gutter+ version-control-diff-side 'left)
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-adopt-subprojects t c-c++-lsp-enable-semantic-highlight t)
 (cmake :variables cmake-enable-cmake-ide-support t cmake-backend 'lsp cmake-ide-build-dir "build")
 (lsp :variables lsp-file-watch-threshold nil read-process-output-max
	  (* 1024 1024 3)
	  lsp-prefer-capf t lsp-idle-delay 0.5 lsp-log-io t lsp-auto-guess-root t lsp-ui-doc-delay 1 lsp-ui-sideline-show-hover t lsp-ui-sideline-delay 1 ccls-initialization-options
	  '(:index
		(:comments 2)
		:completion
		(:detailedLabel t)
		:cache
		(:directory "/tmp/ccls"))
	  ccls-sem-highlight-method 'font-lock lsp-enable-indentation nil lsp-headerline-breadcrumb-enable nil)
 (dap :variables dap-ui-locals-expand-depth 3)
 prettier import-js tern
 (javascript :variables javascript-import-tool 'import-js javascript-fmt-tool 'prettier javascript-backend 'tern js2-basic-offset 2 js2-include-node-externs t node-add-moduels-path t)
 json
 (html :variables web-fmt-tool 'web-beautify)
 (lua :variables lua-backend nil)
 (pdf :variables pdf-view-display-size 'fit-height))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by dalanicolai** [comment]
This can be achieved by setting/customizing the variable `shell-pop-autocd-to-working-dir` to `nil` (added instruction to docstring in #14959)

**Comment by c02y** [comment]
Didn't know that variable, thanks.

**Comment by dalanicolai** [comment]
> Didn't know that variable, thanks.

That's understandable. Thanks for the bug report as it helps improving the documentation.
