### ISSUE TITLE
Frame is destroyed unexpectedly 

### ISSUE THREAD

**Issue by agenbite** [syl20bnr/spacemacs#14953]
#### Description :octocat:
Frame gets destroyed unexpectedly under specific circumstances while using notmuch.

#### Reproduction guide :beetle:
1 Start Emacs
2 Create a new frame `SPC w F`
3 Zoom in/out the new frame `SPC z f`
4 Open notmuch-inbox `SPC a e n i`
5 Put it in tree-view `Z`
6 Open a message `ENTER`
7 Go to the message window `C-x o`
8 Maximize it `C-w 1`
9 Close the message `q` (bound to `notmuch-bury-or-kill-this-buffer`)

*Observed behaviour:* :eyes: :broken_heart:
The buffer is killed and the frame is destroyed. It suffices to go through step 3 once in a session to provoke the unexpected behaviour (i.e., if you create a new frame, the strange behaviour will repeat without step 3).

*Expected behaviour:* :heart: :smile:
The frame should not be killed, and it should go back to the tree view of step 5. This is what happens normally if step 2 or 3 are omitted. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 483cdd1c0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking auto-completion shell csv helm evil-snipe
                (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-override-mode t)
                emacs-lisp git google-calendar org
                (org :variables org-enable-hugo-support t)
                ess notmuch bibtex latex
                (latex :variables latex-enable-folding t latex-enable-auto-fill t latex-enable-magic t)
                syntax-checking pdf ranger
                (ranger :variables ranger-show-preview t)
                outshine
                (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2

**Comment by fran-penedo** [comment]
Can reproduce as described as well as by starting emacs as a daemon and skipping step 2.

**Comment by lebensterben** [comment]
Don't start it as `fg-daemon`. Use simple `daemon`.
This is a long-known upstream bug.

**Comment by agenbite** [comment]
I have launched emacs with the `--daemon` option, and tried the steps to reproduce the bug. It keeps happening. Maybe it's a different thing.

@lebensterben, could you please point me to the known upstream bug? I've tried to find it myself with no success.

**Comment by lebensterben** [comment]
@agenbite 

https://www.reddit.com/r/emacs/comments/2ans0z/have_you_encountered_that_gtk_bug_in_daemon_mode/

**Comment by agenbite** [comment]
Thanks for the link!

However, that reddit thread is about emacs crashing. My bug report is about a frame being closed unexpectedly, while the server keeps alive. Moreover, I've been able to reproduce the bug with the `daemon` option, as suggested, so I'm pretty sure we are not talking about the same thing.

**Comment by lebensterben** [comment]
that's what crash mean here.

When a kid says stomach hurts, it may be liver.

**Comment by agenbite** [comment]
Ok, sorry for the misunderstanding. Since the reddit thread mentions "daemon crashes" several times, I understood that it was different from "frame closing".

However, I can reproduce the bug with both `daemon` and `fg-daemon`, so the proposed solution is not working either... Have you been able to reproduce it?

**Comment by agenbite** [comment]
Done (with `systemctl` instead of `systemd`). 

The result is that if I'm on the first (and single) frame resulting from the initial call to `emacs`, everything works fine and the frame does not close when I repeat the steps above starting from step 3. However, if I follow the steps from step 2 (i.e. open a second frame), the second frame still gets destroyed.

**Comment by lebensterben** [comment]
@agenbite 
I suggest to contact the upstream https://notmuchmail.org/#index8h2

**Comment by agenbite** [comment]
Problem is that I can't reproduce the bug with standard emacs (without spacemacs), so I guess the problem is within spacemacs. Furthermore, the notmuch community does not support spacemacs. :(

**Comment by fran-penedo** [comment]
I do not believe this is a notmuch bug at all. @agenbite could you try to reproduce it with other buffers by calling `kill-buffer` directly?

**Comment by agenbite** [comment]
Thanks @fran-penedo. I don't really understand what you ask me: you mean trying to trigger the destruction of a frame by killing other buffers not related to notmuch?
