### ISSUE TITLE
Opening a junk file, opening .tex file or `SPC h l` or `configuration-layer/update-packages` throws eieio error

### ISSUE THREAD

**Issue by hyiltiz** [syl20bnr/spacemacs#14956]
I am running Spacemacs v.0.300.0 in emacs `GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2021-07-23, unofficial emacs-snapshot build: http://emacs.secretsauce.net` following spacemacs latest develop branch `c5248ac46`. 

I have tried:
- deleting *.elc files and restarting emacs
- deleting `elpa` folder and restarting spacemacs to re-install all packages
- starting an older emacs `Emacs 27`
- re-installing `emacs-snapshot` package (version shown above)
- rebooting the OS (Debian Testing)

None of the above solved the issue and the error message http://ix.io/3urP is too cryptic to do anything with it. My configuration file has not changed, and I am guessing it was a regression introduced by recent emacs udpate and/or spacemacs as I updated both. Either case, spacemacs should fix itself or catch up with emacs updates if emacs eieio internals changed.

Same issues with `GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0) of 2021-03-27, modified by Debian` as well. Here are a list of events that trigger eieio errors:
- opening a junk file
- opening .tex file
- SPC h l
- configuration-layer/update-packages
- `(emacs-version) |` running `eval-last-sexp` with cursor at the bar

**Comment by hyiltiz** [comment]
With help from wasamasa et al (#emacs at Libera.chat), evaluating the following two lines "fixed* the (symptom of?) issue (for now?).
```
(advice-remove 'eieio-oset 'eieio-oset--closql-oref) 
(advice-remove 'eieio-oref 'eieio-oref--closql-oref) 
```

**Comment by emacs18** [comment]
I don't run into this problem with
- SPC h l
- loading a file with ".tex" suffix
- evaluating `(emacs-version)`

I don't know what a junk file is so I can't try that.  
I didn't try `configuration-layer/update-packages`, because I simply don't use this.

I use Ubuntu 20.04 running my own recent build of emacs 27 and 28, and latest develop branch of spacemacs.

**Comment by hyiltiz** [comment]
By junk file I meant `SPC f J`. In my `~/.spacemacs` file, I also had the following block:
```elisp
(defun closql--closql-object-p (obj)
  ;; This is like `closql-object--eieio-childp' except that instead
  ;; of `object-of-class-p' it uses:
  (and (eieio-object-p obj)
       ;; This is like `object-of-class-p' except that instead of
       ;; `child-of-class-p' it uses:
       (let ((class 'closql-object))
         ;; This is like `child-of-class-p' except that it does not
         ;; enter recursive load when a class exists that is merely
         ;; autoloaded, since it uses `eieio--class-object' instead
         ;; of `eieio--full-class-object'.
         (let ((child (eieio--class-object obj)))
           (cl-check-type child eieio--class)
           (or (eq class 'eieio-default-superclass)
               (let ((p nil))
                 (setq class (eieio--class-object class))
                 (cl-check-type class eieio--class)
                 (while (and child (not (eq child class)))
                   (setq p (append p (eieio--class-parents child))
                         child (pop p)))
                 (if child t)))))))
```
which I copied from this issue tracker as it was recommended to fix/workaround some other issue. Maybe it is relevant?

**Comment by emacs18** [comment]
I don't know anything about your custom `closql--closql-object-p`.  I don't have it.
I just wanted to share that my setup is similar to yours (linux, emacs 28, latest develop branch of spacemacs), but I don't have the problems you are running into.

**Comment by hyiltiz** [comment]
Let's close it until someone else can replicate it then?
