### ISSUE TITLE
org-roam-mode buffer broken due to (global-)page-break-lines-mode (Spacemacs continuously switches major-mode)

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#14969]
#### Description :octocat:
org-roam-mode buffer is broken due to (global-)page-break-lines-mode

#### Reproduction guide :beetle:
- Start Emacs

- Install org-roam via the [org-mode layer instructions](https://develop.spacemacs.org/layers/+emacs/org/README.html#org-roam-support)
- Additionally carry out the [setting up instructions of the org-mode manual](https://www.orgroam.com/manual.html#Setting-up-Org_002droam).

- Create a node using `M-x org-roam-node-find` followed by `C-c C-c`

- Within that note create another note but now using `M-x org-roam-node-insert` (and submit with `C-c C-c`)

- follow the link to the newly created note

- in the 'new note' buffer do `M-x org-roam-buffer-toggle`

There should be a backlink, otherwise there is a bug (which probably has not yet
been reported). If there is no backlink then customize the
`org-roam-mode-section-functions`. There settings are correct, but possibly have
to get 'reapplied`. Please note down as a bug.

Finally if there is a backlink then notice that you can not follow it by placing
the cursor on it and pressing enter. If you switch off
`global-page-break-lines-mode` before creating the org-mode buffer (delete and
toggle again), then the link does work (as already reported
[here](https://github.com/syl20bnr/spacemacs/issues/14929#issuecomment-887764025).

Now the `org-roam-mode` is derived from `special-mode` (via
`magit-section-mode-hook`) and, as none of these modes is included in
`page-break-lines-modes`, should be excluded from `global-page-break-lines-mode`.
However Spacemacs, somehow designates the `org-roam-mode` buffer as (over here)
 either an `emacs-lisp-mode` buffer or an `org-mode` buffer.

Now it took me a long time to find the culprit, and still help is appreciated.
So to see what is causing the problem evaluate the following lines:

```
(defun derived-mode-p (&rest modes)
  "Non-nil if the current major mode is derived from one of MODES.
Uses the `derived-mode-parent' property of the symbol to trace backwards."
  (apply #'provided-mode-derived-p (print major-mode) modes))
```

now just observe what happens. Spacemacs is switching modes continuously.

The `derived-mode-p` function is used in `page-break-lines-mode-maybe`.

So maybe for now we can indeed first switch-off `global-page-break-lines-mode`
for users of `org-roam-mode` (as suggested
[here](https://github.com/syl20bnr/spacemacs/issues/14929#issuecomment-887764025)).

*Observed behaviour:* :eyes: :broken_heart:
backlinks don't work

*Expected behaviour:* :heart: :smile:
backlinks work

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 40ae5e229)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(erc restclient test-layer robot-framework
     (org-wiki :variables org-wiki-location "~/Sync/org/wiki")
     command-log
     (latex :variables latex-backend 'company-auctex)
     auto-completion gnus emacs-lisp common-lisp
     (scheme :variables scheme-implementations
             '(guile racket mit))
     (clojure :variables clojure-enable-linters 'clj-kondo)
     racket
     (haskell :variables haskell-completion-backend 'dante)
     git helm
     (ivy :variables ivy-enable-icons t)
     lsp dap markdown multiple-cursors
     (spacemacs-evil :variables spacemacs-evil-collection-allowed-list 'nil)
     helpful c-c++ rust julia python
     (jupyter :variables org-babel-jupyter-resource-directory "~/org/jupyter")
     ipython-notebook yaml javascript
     (org :variables org-directory "~/Sync/org" org-default-notes-file "~/Sync/org/notes.org" org-agenda-files
          '("~/Sync/org/google-calendar" "~/Sync/org/contacts.org" "/home/dalanicolai/Sync/org/journal" "/mnt/4EEDC07F44412A81/git/Masterthesis/TODOs.org" "~/spacemacs/diary.org")
          org-enable-notifications t org-start-notification-daemon-on-startup t org-enable-org-journal-support t org-journal-enable-agenda-integration t org-journal-dir "~/Sync/org/journal/" org-journal-file-format "%Y%m%d.org" org-journal-file-type 'weekly org-enable-roam-support t org-enable-templated-html-support t org-enable-github-support t org-enable-reveal-js-support t org-enable-org-contacts-support t org-contacts-files
          '("~/Sync/org/contacts.org")
          org-capture-templates
          '(("c" "Contacts" entry
             (file "~/Sync/org/contacts.org")
             "* %(org-contacts-template-name)\n          :PROPERTIES:\n          :EMAIL: %(org-contacts-template-email)\n          :PHONE:\n          :ALIAS:\n          :NICKNAME:\n          :IGNORE:\n          :ICON:\n          :NOTE:\n          :ADDRESS:\n          :BIRTHDAY:\n          :END:")))
     (bibtex :variables bibtex-dialect 'biblatex bibtex-enable-ebib-support t bibtex-files
             '("/mnt/4EEDC07F44412A81/jabref/main/main.bib")
             ebib-default-directory "/mnt/4EEDC07F44412A81/jabref/main/files" ebib-preload-bib-files bibtex-files ebib-file-search-dirs
             '("/mnt/4EEDC07F44412A81/jabref/main/files")
             ebib-import-directory "/mnt/4EEDC07F44412A81/jabref/main/files" org-ref-default-bibliography
             '("/mnt/4EEDC07F44412A81/jabref/main/main.bib")
             bibtex-completion-bibliography
             '("/mnt/4EEDC07F44412A81/jabref/main/main.bib")
             org-ref-get-pdf-filename-function 'org-ref-get-zotero-filename ebib-window-vertical-split 'above)
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control treemacs pdf djvu toc
     (calibre :variables calibredb-root-dir "/mnt/4EEDC07F44412A81/Calibrebibliotheek" calibredb-add-delete-original-file "yes" calibredb-download-dir "~/Downloads" calibredb-fetch-covers "yes" calibredb-show-entry-switch 'switch-to-buffer-other-window calibredb-show-results t calibredb-title-width 84 calibredb-author-width 25 calibredb-tag-width 14 calibredb-comment-width 32)
     epub fasd html github
     (sql :variables sql-capitalize-keywords t sql-lsp-sqls-workspace-config-path 'workspace)
     csv eaf eww info maxima)
```
- System configuration features: CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```

```

**Comment by dalanicolai** [comment]
While I wanted to report the backlink issue, I also noticed that this 'Spacemacs bug' was already reported: `https://github.com/org-roam/org-roam/issues/1732`

So also it seems that backlinks do not get created before "(re)applying" the `org-roam-mode-section-functions` or restarting Spacemacs.

**Comment by dalanicolai** [comment]
I am not sure what the bug-tracker label means; but I guess it means this is an upstream bug? Because I think this really is a Spacemacs bug.

**Comment by lebensterben** [comment]
apparently that's a bug of GitHub iOS client. They should be applied to another one.

**Comment by lebensterben** [comment]
bug tracker means this is a confirmed bug. if there's a future bug fix or workaround, this will be the tracking issue.

**Comment by duianto** [comment]
> I guess it means this is an upstream bug?

There is a separate `Upstream` label.

**Comment by dalanicolai** [comment]
Thanks! Handy to know...

**Comment by mattford63** [comment]
After disabling page-break-lines globally, locally, everywhere this issues still occurs.

However if after displaying the org-roam backlink buffer you manually do a org-roam-buffer-refresh it will work (but only if page-break-lines is disable)

**Comment by Sergey-Makarov** [comment]
Here is a simple solution that works for me so far and does not require disabling any of the modes (including `page-break-line-mode` and `display-line-number-mode`): https://github.com/org-roam/org-roam/issues/1732#issuecomment-1465326574

**Comment by lebensterben** [comment]
@dalanicolai 

please verify whether it fixes your issue

**Comment by nickanderson** [comment]
The elisp linked by @Sergey-Makarov (https://github.com/org-roam/org-roam/issues/1732#issuecomment-1465326574) fixes this issue for me as well.

**Comment by smile13241324** [comment]
I have added the fix for org-roam into spacemacs until this is fixed upstream. If this is not longer needed we can still remove it again.

**Comment by Sergey-Makarov** [comment]
@smile13241324 nit: in the related commit message, the link seems to be wrong as it does not point to this issue 🙂 I guess you confused the issue number with the one from the org-roam repo.

**Comment by smile13241324** [comment]
Lol I have noticed this too but now its impossible to change at least without force pushing ;)
