### ISSUE TITLE
Add company-web to web-mode

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1496]
A while ago @CestDiego complained `web-mode` only supports `auto-complete`. Now there's a [company version of it](https://github.com/osv/company-web). Maybe @CestDiego could give it a try and let us know if it can integrate into Spacemacs.

**Comment by syl20bnr** [comment]
:+1:

**Comment by CestDiego** [comment]
@syl20bnr @tuhdo I've done it...it looks great http://imgur.com/w3P9eN9 I still miss the old popup style (the one with transparency I showed you guys when I was starting to use spacemacs). Is there any way of getting it back?

**Comment by tuhdo** [comment]
Do you mean company popup should have the same colour as the background?

**Comment by CestDiego** [comment]
something like this http://i.imgur.com/1yPIQP9.png

**Comment by CestDiego** [comment]
offtopic: @syl20bnr I see you put the tag fixed in develop but not close the issue just yet. Is this because when you do the changelog you check through this tags to see what to write? If this is the case then it should be said so for us not to close issues.

**Comment by syl20bnr** [comment]
@CestDiego  Even if you close the issue the tag is still here so no problem. I clear the tags when the release is published.
