### ISSUE TITLE
Spacemacs buffer terminal mouse click on links appears broken

### ISSUE THREAD

**Issue by didibus** [syl20bnr/spacemacs#14964]
It seem that this line: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-spacemacs-buffer.el#L91

Should instead bound to `mouse-1` and not to `down-mouse-1` as it does.

The way it is now, when I click on a link from a terminal Emacs, the link gets highlighted, but it doesn't navigate, and Emacs is stuck waiting for more input as if I have not finished typing a keychord:

> down-mouse-1 ESC [ < 0 ; 8 1 ; 1 9 ; m

I'm not too sure why this happens, but it prevents the click from working, and afterwards everything I type or click on just gets added to more commands on the keychord and it only stops if I `C-g`.

I tried to simply change it to:

```
(define-key map [mouse-1] 'widget-button-click)
```

And that seems to have fixed it.

**Comment by dalanicolai** [comment]
Over here, on Fedora using X11 session, both `mouse` and `down-mouse` work fine in the terminal and in the gui.

On the other hand, the Update Packages button does not work for me at all (only via the keyboard using RET or 'ace-buffer-links`). And indeed with `down-mouse` I must type `Esc` (or `C-g`) to get control back.

So in the end, just `mouse` seems to be the better option indeed (for me).

And the Update packages button does not seem to work with the mouse at all.

**Comment by lebensterben** [comment]
what terminal are you using

**Comment by dalanicolai** [comment]
Tried both Konsole and gnome-terminal. Both same behavior.

**Comment by lebensterben** [comment]
some modern terminals detects URLs by themselves and may intercept mouse events.

**Comment by didibus** [comment]
It looks like emacs-dashboard has the same issue: https://github.com/emacs-dashboard/emacs-dashboard/issues/184

And they solved it the same way I propose: https://github.com/emacs-dashboard/emacs-dashboard/pull/285/files by binding [mouse-1] instead.

**Comment by lebensterben** [comment]
@didibus You can go ahead and submit a PR with the change you proposed.

**Comment by c02y** [comment]
In GUI Emacs, I cannot use mouse-click to open the buffer in the `*spacemacs*` buffer which contains the recent files/projects.

**Comment by lebensterben** [comment]
reopening due to https://github.com/syl20bnr/spacemacs/pull/15859#issuecomment-1370405246
