### ISSUE TITLE
New extra argument in python-shell-send functions in Emacs 28

### ISSUE THREAD

**Issue by dalanicolai** [syl20bnr/spacemacs#14974]
Very recently, the command `spacemacs/python-shell-send-with-output` was merged in  #14965.

However, the problem has been fixed in Emacs 28 where also most `python-shell-send` can receive an extra argument for controlling if they should incl. a `coding cookie` (by default the cookie is included and the comint does not print the output).

So probably the command of #14965 can get  removed again, and we could add a custom variable that controls the default behavior of sending cookies (or maybe control it via prefix arguments, or better both)

The main purpose of this issue is just to 'poll' opinions and to create a note about it.

**Comment by lebensterben** [comment]
you can wrap it with (when (version< "28.0" emacs-version))

**Comment by dalanicolai** [comment]
Just for tracking/administration, I am linking to this new proposed patch here... https://debbugs.gnu.org/cgi/bugreport.cgi?bug=49822#45

**Comment by lebensterben** [comment]
if only python itself has better tooling that can perform build, install, test, run, and other operations, then there's no need to do the heavy lifting in elisp.

for example, Emacs' cargo-process is merely a wrapper on cargo. and haskell-mode has the wrapper on cabal.
