### ISSUE TITLE
Dev doc on TeX-engine is misleading and implementation is confusing

### ISSUE THREAD

**Issue by vitaminace33** [syl20bnr/spacemacs#14978]
In the development branch of the LaTeX layer it is stated to append this code to the end of a .tex file for proper engine recognition:
```
% Local Variables:
% TeX-engine: 'xetex
% End:
```
However, on file opening, this will throw the message:
```
The local variables list in myfile.tex
contains values that may not be safe (*).
[...]
  * TeX-engine : 'xetex
```
and the error upon compilation through `SPC m b`:
```
‘'xetex’ is not a known engine.  Valid values are: default, luatex, omega, xetex.
```
This is easily solved by deleting the initial apostrophe on `xetex`.

After correction, the file will compile correctly with `SPC m b` and through the usual AUCTeX key binding `C-c c`.

_UPDATE: below initial version of the issue that was partly mistaken._

_After correction, the file will compile correctly with `SPC m b`, but not so through the usual AUCTeX key binding `C-c c`. This is corrected adding this snippet to `dotspacemacs/user-config`_
```
(add-hook 'LaTeX-mode-hook
  (lambda()
    (add-to-list 'TeX-command-list
      '("XeLaTeX"
        "%`xelatex -shell-escape -synctex=1%(mode)%' %t"
        TeX-run-TeX nil (latex-mode) :help "Run LaTeX"))))
```
_and a new local variable_
```
% Local Variables:
% TeX-command-default: "XeLaTeX"
% End:
```

**Comment by lebensterben** [comment]
You can open a PR to remove the apostrophe.

---

Your Tex command is redundant. It can be handled correctly by auctex-latexmk.

https://github.com/tom-tan/auctex-latexmk/blob/4d353522650d7685acbf1d38f7dbc504f734bd84/auctex-latexmk.el#L90

So using LaTexMK is sufficient.

**Comment by vitaminace33** [comment]
Thx for your remark, I didn't know about `latexmk`. After installing it (system packages, .el script is already installed by AUCTeX and/or Spacemacs) and following your indications, I confirm that this is a working .tex footer.
```
% Local Variables:
% TeX-engine: xetex
% TeX-command-default: "LatexMk"
% End:
```
`latexmk` apparently uses the value of `TeX-engine` to determine the engine.

However, as there are different values for `TeX-engine`, there should be different values for `TeX-command-default` so both, `SPC m b` and `C-c C-c`, work, specially for those that won't use `latexmk` (either because they can't install it or want to do a single compilation).

I don't know who should add these commands, if Spacemac's LaTeX layer o AUCTeX itself.

**Comment by lebensterben** [comment]
latexmk is included in both texlive and miktex. Why is it not installed already?

**Comment by vitaminace33** [comment]
LatexMk is included in TeX Live 2011+.

**Comment by vitaminace33** [comment]
LatexMk is included in TeX Live 2021+. Ubuntu 20.04 is shipped with TeX Live 2019 and a specific package must be installed. The same happens with Ubuntu 20.10, 21.04 and 21.10, which all three provide TeX Live 2020.

**Comment by lebensterben** [comment]
Okay I see.

**Comment by lebensterben** [comment]
@vitaminace33 

unlike `TeX-engine` which is customize variable, `TeX-command-default` is not. You can set it for a different value for sure, but this may break other functions.

So I suggest not to changing `TeX-command-default`. And improve the documentation. Specifically adding a recommendation to also install `latexmk`.

This is pretty much a low hanging fruit and would you like to make a PR to address it?

**Comment by vitaminace33** [comment]
Sure, why not?! I can make that PR.

On the other hand, I don't know what you mean by "`TeX-command-default` is not a customize variable". According to [AUCTeX's manual](https://www.gnu.org/software/auctex/manual/auctex/Selecting-a-Command.html#index-TeX_002dcommand_002ddefault) it is.

> As mentioned before, AUCTeX will try to guess what command you want to invoke.  If you want to use another command than &lsquo;<samp>TeX</samp>&rsquo;, &lsquo;<samp>LaTeX</samp>&rsquo; or whatever processor AUCTeX thinks is appropriate for the current mode, set the variable <code>TeX-command-default</code>.  You can do this for all files by setting it in a mode hook or per file byspecifying it as a file variable (see <a href="https://www.gnu.org/software/emacs/manual/html_node/emacs/File-Variables.html#File-Variables">(emacs)File Variables</a> section &lsquo;File Variables&rsquo; in <cite>The Emacs Editor</cite>).

Perhaps you mean something different than I do. Anyway, digging a bit into this, I've come to realize that `TeX-engine` is not behaving as expected. Again, according to [AUCTeX's manual](https://www.gnu.org/software/auctex/manual/auctex/Processor-Options.html#index-TeX_002dengine), `TeX-engine` should set `TeX-command-default`. I will have a further look on this and write that PR.

**Comment by lebensterben** [comment]
@vitaminace33 

See:
https://git.savannah.gnu.org/gitweb/?p=emacs/elpa.git;a=blob;f=tex.el;h=46d6bbc453563fde526c6ca267b7857f5078d1ef;hb=refs/heads/externals/auctex#l2202

Two issues:

- It should be declared via `defcustom` instead of `defvar`.
Most customize variables are declared with `defcustom` already.
- It should only be set to a symbol in the `TeX-command-list`, but that requirement is not mentioned in the docstring and thus it's confusing.

---

A major issue of running `xelatex` itself is it won't handle non-trivial source files correctly in one run. At least two runs of `xelatex` is needed.
Meanwhile `latexmk` is able to do that automatically.

**Comment by vitaminace33** [comment]
Thx for the input. On the other hand, I've come to realize that I've been mistaken for a decade. `TeX-engine` does not changes the `LaTeX-command-default` but does change the behavior of the `LaTeX` command does as expected, therefore there is no need of a `XeLaTeX` command. I found the above snippet in several forums as a solution to have XeLaTeX working and I have been "mistaken" since then.

With regards to the original message, only removing the apostrophe is sufficient. I'll add a recommendation for LatexMk for those who would like a multipass compilation command.
