### ISSUE TITLE
[SOLVED] Disabling auto-fill for LaTeX disables flyspell as well

### ISSUE THREAD

**Issue by vitaminace33** [syl20bnr/spacemacs#14986]
**UPDATE: The layers' configuration section was being rewritten hence the problem.**

#### Description :octocat:
Disabling `auto-fill` for LaTeX disables `flyspell` as well. It is perphaps not related to the LaTeX major mode.

#### Reproduction guide :beetle:
- (Optional) Install a clean Spacemacs.
- Start Spacemacs.
- Open `.spacemacs`, `SPC f e d`.
- Make sure the `latex` and `spell-checking` layers have been activated.
- (Optional) Add a `TeX-language` hook to the `dotspacemacs/user-config` section, e.g.
```
(add-hook 'TeX-language-en-hook
         (lambda () (ispell-change-dictionary "american")))
```
- Create a test file, `test.tex`, with minimal testing content, e.g.
```
\documentclass{minimal}
\usepackage[english]{babel}
\begin{document}
This is wong.
\end{document}
```
- Save and restart if needed, `SPC q r`.
- Check that `flyspell` is on (and the `american` dictionary has been loaded), `C-h v flyspell-mode RET` (and `C-h v ispell-local-dictonary RET`).
- Open `.spacemacs`, `SPC f e d`.
- Disable `auto-fill-mode` by adding the next snippet to the end of `dotspacemacs/layers` [as recommended](https://emacs.stackexchange.com/questions/42285/how-to-disable-line-wrapping-in-latex-layer/66802#66802).
```
  (setq-default dotspacemacs-configuration-layers
                '((latex :variables latex-enable-auto-fill nil)))
```
- Close `.spacemacs`, `C-x k`, an restart, `SPC q r`.
- Check that `flyspell` is *off* (and the `american` dictionary has still been loaded).

*Observed behaviour:* :eyes: :broken_heart:
Disabling `auto-fill` for LaTeX [as indicated in the documentation](https://emacs.stackexchange.com/questions/42285/how-to-disable-line-wrapping-in-latex-layer/66802#66802) also disables `flyspell`.

*Expected behaviour:* :heart: :smile:
Disabling `auto-fill` should not disable other minor modes as `flyspell`.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 40ae5e229)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((latex :variables latex-enable-auto-fill nil))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
@vitaminace33 
In the system-info section, you don't have `spell-checking` layer enabled.

**Comment by vitaminace33** [comment]
I don't know what you want me to say. Perhaps it is because the snippet is being included in `dotspacemacs/layers`.

**Comment by vitaminace33** [comment]
You are right! I was not configuring the layer properly. Thx for the remark.

**Comment by vitaminace33** [comment]
Having to understand Emacs, AUCTeX and Spacemacs on top of 'em is giving me a headache.
