### ISSUE TITLE
How do adjust the in file search behavior?

### ISSUE THREAD

**Issue by songverser** [syl20bnr/spacemacs#14981]
Currently when I search for the word and it is not on the current page, this word will display on the bottom 2 line of this page. But I am used to the behavior that this word will display on top of the page. Is there a way to define this by myself? Thanks in advance.

Editted below: In order to be specific.

Currently, when I using vim searching "/searchforsth" with "n" to search for words. After navigating through the words on this page, the next word that is not on the current page will appear at the bottom. But I am used to the behavior that this word will display on top or middle of this page, just like pressing "zt" or "zz". So I can see the following code of this searched pattern. Is there a way to define this behavior by myself? Thanks in advance.

**Comment by lebensterben** [comment]
Please ask for help in the upstream https://github.com/abo-abo/hydra

**Comment by lebensterben** [comment]
I don't think this is customizable
https://github.com/abo-abo/hydra/blob/2d553787aca1aceb3e6927e426200e9bb9f056f1/lv.el#L80-L81

**Comment by songbaai** [comment]
Actually I am asking how to restore the default emacs search behavior. Just open the emacs with "emacs -q somefile" the search behavior with "C-s" is different from what it looks like in spacemacs. The default search behavior search like google chrome. When going to next word that is not on this page it will appear in the middle of this page.

**Comment by songbaai** [comment]
After delete the folder spacemacs-navigation the problem is solved. Not the best solution though.
