### ISSUE TITLE
Unable to activate terraform-ls LSP

### ISSUE THREAD

**Issue by akumria** [syl20bnr/spacemacs#14987]
Hi,

I have installed both the terraform and lsp layers, however I find myself unable to configure terraform-ls correctly.

Some context: it appears there are two providers (LSPs) for terraform.

1. terraform-lsp: https://github.com/juliosueiras/terraform-lsp
2. terraform-ls: https://github.com/hashicorp/terraform-ls

I choose to use the second one, and followed the configuration specified for Emacs:

https://github.com/hashicorp/terraform-ls/blob/main/docs/USAGE.md

I placed the snippet within "`(defunc dotspacemacs/user-config ()`", however that break since emacs fails saying:

```
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s function definition is void: lsp-register-client
```

If I remove the configuration and then let spacemacs start. I am able to perform a `M-x describe-function` on `lsp-register-client` successfully; so I am guessing the actual loading is deferred. I do not understand where I should place things, if so.

For reference my `.spacemacs` `user-config ()` looks like:

```
(defun dotspacemacs/user-config ()
  "Configuration for user code:
This function is called at the very end of Spacemacs startup, after layer
configuration.
Put your configuration code here, except for variables that should be set
before packages are loaded."
    (setq magit-repository-directories
          '(("~/Projects/" . 2)))

;; this gets browse-url working on MacOS
    (setq browse-url-browser-function (quote browse-url-generic))
    (setq browse-url-generic-program "open")
    (setq flymd-browser-open-function 'browse-url-default-macosx-browser)

;; working terraform LSP
    (lsp-register-client
         (make-lsp-client :new-connection (lsp-stdio-connection '("/Users/kumriaa/bin/tfls" "serve"))
                          :major-modes '(terraform-mode)
                          :server-id 'terraform-ls))

    (add-hook 'terraform-mode-hook #'lsp-deferred)
)
```

**Comment by lebensterben** [comment]
(require 'lsp)
