### ISSUE TITLE
Info isn't evil enough

### ISSUE THREAD

**Issue by jebotz** [syl20bnr/spacemacs#14988]
This isn't a bug report, it's a request for discussion of an issue that's been frustrating to me.  The info mode is a good example for it, but affects other modes as well, specifically modes which like info mode are normally read only and thus use even in "normal" emacs use single key commands for navigation and other functions.

The problem is that info mode is partially evilified; enough so that we can use `j` `k` to move up and down, but `h` and `l` have their original non-evil meanings.  And this doesn't work very well with my finger muscle memory... in info mode `l` means go back to the last visited info node, and back is conceptually to the left, but of course in vi `l` means move to the right.  This causes and irritating level of cognitive dissonance for me and wastes a lot of time as I keep going back nodes when my fingers were just trying to move the cursor out of the way or I end up in a help window.  For a while I tried to make it a habit of switching to holy mode when in such a buffer to avoid this, but I don't really want to give up `j` and `k` for movement either.

What I'm getting at is that I think we need define a core set of vi commands that always work the vi way if a mode is even partially evilified, specifically the core movements and searches, and moves all conflicting keybindings from those keys onto a predictable alternate binding, maybe with a leader key that stands for "original binding".

What do y'all think?

**Comment by emacs18** [comment]
I would add that the mode line should clearly indicate whether the info buffer is in normal emacs mode or in evil mode.  Hitting C-z to toggle between the two modes results in absolutely no visible change anywhere in emacs which leaves me disoriented.
My fingers are trained to use normal emacs info key bindings going back decades.  I can limp along with evil key bindings in info buffer, but I often hit C-z out of frustration to go back to emacs mode.  Mode line clearly indicating which mode is active would help me greatly.
