### ISSUE TITLE
org-roam (v2) org-roam-mode buffer doesn't display/work correctly

### ISSUE THREAD

**Issue by jebotz** [syl20bnr/spacemacs#14998]
When using org-roam in the spacemacs devel branch (by passing 'org-enable-roam-support t' to the org layer) the org-roam-mode buffer (the backlinks buffer) doesn't display or work correctly.  For one thing the 'Backlinks(n)' heading appears on the second-to-last line rather than the top.  For another the folding of backlink details doesn't work correctly.  I tried this with a fresh spacemacs git clone with no customizations other than enabling the org layer with org-enable-roam-support. I also tried the same version of org-roam in a plain emacs, and there it does work correctly.

**Comment by emacs18** [comment]
https://github.com/syl20bnr/spacemacs/issues/14929 first noted that you need to disable `page-break-lines-mode` to get `org-roam-mode` to work.  #14929 disabled this in a hook.  I disabled this in `dotspacemacs/user-config` function.  Wherever you do this, you need to disable `page-break-lines-mode` until someone finds a way to fix this within default spacemacs configuration.  

https://github.com/syl20bnr/spacemacs/issues/14969 also is regarding `page-break-lines-mode`.

In addition, I also find myself having to execute `(global-git-gutter+-mode 0)` to disable this mode as well to make `org-roam` work.

**Comment by jebotz** [comment]
Disabling global-page-break-lines-mode indeed that doesolve this for me.
Thanks, Richard Kim!
