### ISSUE TITLE
dired is breaking in develop branch

### ISSUE THREAD

**Issue by spacegoing** [syl20bnr/spacemacs#14990]
I reinstalled spacemacs today and find dired and dired+ is breaking.

Here is my .spacemacs.d https://github.com/spacegoing/GitConfig/tree/master/spacemacs.

There are 2 problems:

1. Files are not displayed when `dired-hide-details` is enabled

![Screenshot from 2021-08-14 23-35-10](https://user-images.githubusercontent.com/5180020/129451508-66bc875c-3d61-45eb-9d60-f8646f86bb6c.png)

2. When `dired-hide-details` is disabled, although the file list is displayed, I still cannot visit any dir / file by hitting `Enter`.
![Screenshot from 2021-08-14 23-35-33](https://user-images.githubusercontent.com/5180020/129451509-d5766792-2871-4481-b43d-12957f65a41e.png)

**Comment by duianto** [comment]
The color of your cursor and left side of the mode line is: yellow

Which probably is evilified state (light brown), according to:
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#states

The default evil normal state cursor color is yellow.

Could you include your system info, press `SPC h d s` to copy the info to the clipboard.


I just cloned the Spacemacs `develop` branch in both Manjaro and Windows.

And hiding the dired details and opening a file with `return` works as expected.
With the key binding: `(` (open parenthesis)
and with: `M-x dired-hide-details-mode`

Pressing: `return` opens the file under the cursor as expected.
`C-h l` (which calls `view-lossage`) shows:
```
 <return>               ;; dired-find-file
 ```

<details>
<summary>System Info Manjaro</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f3b902a30)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

</pre>
</details>


<details>
<summary>System Info</summary>
<pre>
#### System Info Windows:computer:
- OS: windows-nt
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f3b902a30)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by duianto** [comment]
Maybe it's caused by this commit in your config:
[New] cope with spacemacs evil-collection dired
https://github.com/spacegoing/GitConfig/commit/362bf6821d089c8894b322ab6a26561fef00344f#diff-57d828ace1bb4878c155a7237c696db4870a8038a2d5a46f542c353c68d96a2b

```
  (add-to-list 'evil-evilified-state-modes 'dired-mode)
```

**Comment by spacegoing** [comment]
Many thanks @duianto , I just figured out that it is setting `dired-listing-switches` breaking dired:

```
  ;; dired humanreadable format
  (setq dired-listing-switches "-alFh")
```
Any idea how could I set this var correctly under current version?

**Comment by duianto** [comment]
This thread might have some useful suggestions:
https://stackoverflow.com/questions/22971299/conditionally-set-dired-listing-switches-locally-but-nil-remotely

**Comment by lestercheung** [comment]
I have been seeing something similar. Repo steps:

1. Fedora 35, Emacs 27.2, _develop_ branch.
2. No .spacemacs confile to start, dotspacemacs-distribution 'spacemacs.
3. Browse to a remote directory with _sshx_ in dired. (C-x C-f aka spacemacs/helm-find-files)
4. Put laptop to sleep, get a coffee/tea.
5. Resume, open up another remote directory in on the same connection, you will see a buffer with no files while you *know* the directory is not empty.

Interestingly I don't see this problem without spacemacs (starting emacs with -q).

I like spacemacs a lot but this is becoming such a problem that I'm starting emacs without it (which makes me sad). Help?

**Comment by lebensterben** [comment]
@lestercheung 
I think the comment above still applies.

**Comment by lestercheung** [comment]
Thanks for responding @lebensterben, which comment above do you mean? I have tried:
1. dired-hide-details-mode - didn't work after a connection stops showing files.
2. confirm that `dired-listing-switches` is the default (-al).
3. `tramp-cleanup-all-connections` && `tramp-cleanup-all-buffers` && trying to open a directory over tramp again.

Any hints would be appreciated.

**Comment by lebensterben** [comment]
I haven't tried myself. But it seems that
stackoverflow.com/questions/22971299/conditionally-set-dired-listing-switches-locally-but-nil-remotely
should help.

**Comment by lestercheung** [comment]
As I have started without a .spacemac file I have my `dired-listing-switches` set to the default (-la) which is supported on both of my local (Linux) and remote (macOS and Linux) machines.

**Comment by lebensterben** [comment]
@lestercheung 
If you want, you may start digging within https://github.com/syl20bnr/spacemacs/tree/bc27203615268ad192e917565585f55b3e61b2e6/layers/%2Bspacemacs.

Focus on any settings regarding dired. (by grepping "dired" for example)
And see whether some of our default settings messed thing up.
