### ISSUE TITLE
Smartparens disabled when expanding nested snippet.

### ISSUE THREAD

**Issue by jberrend** [syl20bnr/spacemacs#15009]
#### Description :octocat:
Smartparens gets disabled when a nested snippet is expanded - has to be manually re-enabled.

Smartparens remains enabled like expected if a "non-nested" snippet is expanded.

Noticed code here which looks relevant: https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bcompletion/auto-completion/funcs.el#L377

I think the nested snippet is making the code think that smartparens wasn't enabled in the first place, so it never re-enables it after exiting the top-level snippet, but I am very possibly completely wrong here :)

#### Reproduction guide :beetle:
- Start Emacs
- Open project (I develop in Java with `lsp-mode`, I imagine this would be applicable to any company / smartparens / yasnippet scenario, but I haven't tested anything else).
- have following code block defined (for sake of demonstration): `List<Integer> ints = new ArrayList<>();`
- Verify smartparens is enabled (`C-h m`).
- Type: `ints.rem<RET>ints.get<RET>1<TAB><TAB>;`
- End code should be: `ints.remove(ints.get(1));` with cursor immediately after semi-colon.

*Observed behaviour:* :eyes: :broken_heart:
- smartparens is disabled (not present in mode list `C-h m`)
- typing any character belonging to a pair (left paren, left code, left brace, etc), doesn't insert corresponding closing pair.

*Expected behaviour:* :heart: :smile:
- Smartparens should still be enabled.

#### System Info :computer:
- OS: darwin
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 3875f7a2f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(shell-scripts
 (python :variables python-backend 'lsp)
 yaml sql auto-completion docker emacs-lisp git helm
 (lsp :variables lsp-modeline-code-actions-enable nil lsp-modeline-diagnostics-enable nil)
 markdown json html react javascript typescript multiple-cursors org pandoc
 (unicode-fonts :variables unicode-fonts-enable-ligatures t)
 (shell :variables shell-default-height 30 shell-default-shell 'vterm shell-default-full-span nil shell-default-term-shell "/usr/local/bin/fish" shell-default-position 'bottom)
 spell-checking syntax-checking themes-megapack version-control
 (osx :variables osx-swap-option-and-command t)
 java treemacs)
```
- System configuration features: ACL GIF GLIB GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM ZLIB

#### Backtrace :paw_prints:

Trace is after hitting `<RET>` for first time in reproduction steps above with `debug-on-variable-change` enabled for `smartparens-mode`.

```
  debug--implement-debug-watch(smartparens-mode nil set #<buffer Test.java>)
  smartparens-mode(-1)
  (progn (if smartparens-strict-mode (progn (smartparens-strict-mode -1))) (smartparens-mode -1))
  (if global (progn (if smartparens-global-strict-mode (progn (smartparens-global-strict-mode -1))) (smartparens-global-mode -1)) (progn (if smartparens-strict-mode (progn (smartparens-strict-mode -1))) (smartparens-mode -1)))
  spacemacs//deactivate-smartparens()
  spacemacs//smartparens-disable-before-expand-snippet()
  run-hooks(yas-before-expand-snippet-hook)
  ...
```

**Comment by lebensterben** [comment]
It's best if you can make a screencast to illustrate the issue.
I've never seen this in Rust with LSP.

**Comment by Qwertee** [comment]
https://user-images.githubusercontent.com/10646220/130480812-f0cf9bf8-37f8-4dc3-aeac-7132e03ff780.mov

Here is a screencast of my doing the reproduce steps described in the overview. Notice how the pairs aren't being completed at the end.

**Comment by lebensterben** [comment]
Confirmed in Rust now.

**Comment by lebensterben** [comment]
Cause of bug:
https://github.com/syl20bnr/spacemacs/blob/f92af9989a8bf19c29c1b131f9098e06d501f0c5/layers/%2Bcompletion/auto-completion/packages.el#L284-L289

**Comment by lebensterben** [comment]
Has been reported upstream years ago:
https://github.com/joaotavora/yasnippet/issues/785

**Comment by lebensterben** [comment]
@Qwertee 

The workaround is disable `smartparens-mode` globally and enable `electric-pair-mode`, if what you only need is to insert paired delimiters.

**Comment by Qwertee** [comment]
I thought that was the point of the custom hooks defined here, to work around the yasnippet hook not running in nested snippet expansions?

https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bcompletion/auto-completion/funcs.el#L386

It seems like this behavior was changed recently in spacemacs as the referenced `spacemacs--yasnippet-expanding` is no longer present, so I guess comment about fixing the behavior is irrelevant and hence this behavior is observed.

**Comment by lebensterben** [comment]
Yasnippet never works well with smartparens, which is stated by the author of Yasnippet.

I think any attempt to bring them together is futile.

**Comment by usq** [comment]
May I ask what's the plan here? 

There is the 
```
   ;; If non-nil smartparens-mode will be enabled in programming modes.
   ;; (default t)
   dotspacemacs-activate-smartparens-mode t
```
setting, which makes me think that smartparens are the way to go in spacemacs and I did not configure any yasnippets explicitly.

> I think any attempt to bring them together is futile.

Shouldn't this setting be removed then?

**Comment by stephanoskomnenos** [comment]
Here is the solution from doom emacs.
```
;; HACK Smartparens will interfere with snippets expanded by `hippie-expand`,
;;      so temporarily disable smartparens during snippet expansion.
(with-eval-after-load 'hippie-exp
  (defvar +snippets--smartparens-enabled-p t)
  (defvar +snippets--expanding-p nil)

  ;; Is called for all snippet expansions,
  (add-hook 'yas-before-expand-snippet-hook
    (defun +snippets--disable-smartparens-before-expand-h ()
      ;; Remember the initial smartparens state only once, when expanding a
      ;; top-level snippet.
      (unless +snippets--expanding-p
        (setq +snippets--expanding-p t
              +snippets--smartparens-enabled-p smartparens-mode))
      (when smartparens-mode
        (smartparens-mode -1))))

  ;; Is called only for the top level snippet, but not for the nested ones.
  ;; Hence `+snippets--expanding-p'.
  (add-hook 'yas-after-exit-snippet-hook
    (defun +snippets--restore-smartparens-after-expand-h ()
      (setq +snippets--expanding-p nil)
      (when +snippets--smartparens-enabled-p
        (smartparens-mode 1)))))

```
In spacemacs, we could modify `auto-completion/post-init-smartparens` in `~/.emacs.d/layers/+completion/auto-completion/packages.el`.
```
(defun auto-completion/post-init-smartparens ()
  (with-eval-after-load 'hippie-exp             ;; replace `smartparens` with `hippie-exp`
    (add-hook 'yas-before-expand-snippet-hook
              #'spacemacs//smartparens-disable-before-expand-snippet)
    (add-hook 'yas-after-exit-snippet-hook
              #'spacemacs//smartparens-restore-after-exit-snippet)))
```
This just works for me.
