### ISSUE TITLE
[WORKAROUND] LaTeX quotation mechanism is broken

### ISSUE THREAD

**Issue by vitaminace33** [syl20bnr/spacemacs#15003]
#### Description :octocat:
The LaTeX quotation mechanism has been broken recently (1 week or less, I would say). I don't know if Spacemacs is to blame or some other package. A pure, clean Emacs session with uptodate AUCTeX works as expected.

#### Reproduction guide :beetle:

1. Create the following test file, `test.tex`.
```tex
\documentclass{minimal}
%\usepackage[german]{babel}
\begin{document}

Write a quoted word above.%
Write a quoted word below.%

\end{document}
```

2. In a clean Emacs installation, `rm -r ~/.emacs*`, install AUCTeX, `M-x package-install RET auctex RET`, and add the following to `~/.emacs`.
```lisp
(setq TeX-parse-self t) ; Enable parse on load.
(setq TeX-auto-save t)  ; Enable parse on save.
```

3. Restart and visit `test.tex`. Press double quote `"` once to get a two backticks ` `` `, and twice to get a literal double quote `"`. Write something and press double quote `"` again once, two single quotes `''`, or twice,literal double quote `"`,  to close the quote.
```tex
\documentclass{minimal}
%\usepackage[german]{babel}
\begin{document}
``Once''
Write a quoted word above.%
Write a quoted word below.%
"Twice"
\end{document}
```

4. Clear (undo) changes, uncomment `babel`'s line, save the file, restart and repeat the experiment (with now German quotation).
```tex
\documentclass{minimal}
\usepackage[german]{babel}
\begin{document}
"Once"
Write a quoted word above.%
Write a quoted word below.%
"`Twice"'
\end{document}
```

5. Repeat the experiments 3 and 4 with Spacemacs (with LaTeX's layer). English quotation will work as expected, with a slight change: Pressing `"` will insert directly both opening and closing quotation marks (with cursor in between), ` ``'' `. German quotation (an any other language style) breaks: Pressing `"` erases or swaps some characters of the previous line and wrong chars are inserted. Perhaps the package that changes the English behavior is now breaking the other styles.
```tex
\documentclass{minimal}
\usepackage[german]{babel}
\begin{document''  % Closing bracket deleted and two single quotes inserted.
`                  % A single backtick inserted.
Write a quoted word above.%
Write a quoted word below''.% The .% ignored and two single quotes inserted.
`                  % A single backtick inserted.
\end{document}
```

*Observed behaviour:* :eyes: :broken_heart:
If German (or other language) style is activated, `\usepackage[german]{babel}`, pressing `"` erases or swaps some characters of the previous line and wrong chars are inserted.

*Expected behaviour:* :heart: :smile:
If German (or other language) style is activated, `\usepackage[german]{babel}`, pressing `"` once should insert ``"`"'``, twice `""`.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d9c3dc678)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm latex multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
https://www.gnu.org/software/auctex/manual/auctex/auctex_78.html#Style-Files-for-Different-Languages

**Comment by vitaminace33** [comment]
**WORKAROUND**

When the 4th element of `TeX-quote-language` is `nil` and both quote marks are (non escaped) single characters the quotation mechanism works although not as expected for Spacemacs.

Add this snippet in `dotspacemacs/user-config`
```elisp
  (add-hook 'TeX-language-de-hook
    (lambda ()
      (add-to-list 'TeX-quote-language-alist '("german" "\"`" "\"'" nil))))
```
It will override the default German style. Now, if you press `"` once, it will insert ``"`'`` instead of  ``"`"'``, as expected (the escaped double quote is missing for some reason).

Rather than using TeX primitives for the Latin quotation marks, use UTF-8 chars.
```elisp
  (add-hook 'TeX-language-de-hook
    (lambda ()
      (add-to-list 'TeX-quote-language-alist '("german" "«" "»" nil))))
```
Now, if you press `"` once, it will insert `«` instead of  `«»`, as expected in Spacemacs, but you can still close it pressing `"` once after having written some text.

**Comment by lebensterben** [comment]
You should directly changing `TeX-quote-language-alist`.
The first element `"german"` runs `TeX-language-de-hook`.

Your workaround is self-referencing.

**Comment by vitaminace33** [comment]
No, it is not, the hook is triggered by the `german` option for `babel`'s package. AUCTeX, after parsing, applies the appropriate style, namely, `german.el`, which sets `TeX-quote-language` to ``("german" "\"`" "\"'" t)`` and then calls `TeX-language-de-hook`. My workaround uses the hook to set `TeX-quote-language-alist` to  ``( ("german" "«" "»" nil) )``, since the car of its only element coincides with the car of `TeX-quote-language`, it overrides it.

"German" is not a good label for the issue since this can happen for any language.

**Comment by lebensterben** [comment]
The quotations you preferred is not the default for German.
You can use French.

**Comment by lebensterben** [comment]
try to disable smartparens-mode first

**Comment by vitaminace33** [comment]
Good suggestion, after successfully disabling `smartparens` by adding it to `dotspacemacs-excluded-packages`, the quotation mark mechanism works as expected, that is, as in regular Emacs. I did suspect that the package electrifying pairs was the culprit, but I don't know how to continue from here.

**Comment by vitaminace33** [comment]
> The quotations you preferred is not the default for German.
> You can use French.
> 
> https://www.overleaf.com/learn/latex/Typesetting_quotations#Reference_guide

I am to rewrite most language styles because some are missing and others are simply wrong. Still, this doesn't solve `smartparens` breaking quotations.

**Comment by lebensterben** [comment]
@vitaminace33 you don't have to exclude this package all together.
Just have `dotspacemacs-smartparens-strict-mode` and `dotspacemacs-activate-smartparens-mode` set to nil.
https://github.com/syl20bnr/spacemacs/blob/b1c9ddc4525911255388e06a1be5c373816ac443/core/templates/.spacemacs.template#L408-L415

Another way is to add a hook to `LaTeX-mode-hook` that turn off smartparens mode.

**Comment by vitaminace33** [comment]
Thx @lebensterben, I went fast and furious ;-)

I notified upstream.
