### ISSUE TITLE
magit/:config: replacement is neither a cons cell or a string

### ISSUE THREAD

**Issue by hXtreme** [syl20bnr/spacemacs#15016]
#### Description :octocat:
magit/:config: replacement is neither a cons cell or a string

#### Reproduction guide :beetle:
- Start Emacs
- Open an org File (in my case BEGINNERS_TUTORIAL.org)

*Observed behaviour:* :eyes: :broken_heart:
I see a warning saying:

```
Error (use-package): magit/:config: replacement is neither a cons cell or a string
```

One the things I did before observing this was to install was a ipython-notebook and a python layer. The warning persists even if I remove the layers from my .spacemacs file.

*Expected behaviour:* :heart: :smile:
No warnings should pop up

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. de55a45db)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm markdown multiple-cursors org treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

This is pretty much my first few days with emacs so please bear with with me, let me know what other things I should share and how to obtain them.

**Comment by lebensterben** [comment]
please update Spacemacs

**Comment by hXtreme** [comment]
That is very surprising given that I've only installed it a week ago.

**Comment by lebensterben** [comment]
> #### System Info computer
> 
>     * Spacemacs branch: develop (rev. [de55a45](https://github.com/syl20bnr/spacemacs/commit/de55a45dbd46516cf17846f669f80a41f77c4ab4))

^

**Comment by teozkr** [comment]
This error now appears for me as soon as I start (Spac)emacs. It seems to have started somewhere between 08fa117af (good) and 63056ecb5 (bad).

**Comment by teozkr** [comment]
Bisecting, my error seems to have been introduced by 497c7670361cfafa7247fe484038f052feb9e137.
