### ISSUE TITLE
timeout setting for a delay to exit from INSERT mode to NORMAL mode in vim keybinding environment

### ISSUE THREAD

**Issue by chris-aeviator** [syl20bnr/spacemacs#15027]
When using `dotspacemacs-editing-style 'vim` I notice a delay when going from (vim) INSERT to (vim) NORMAL mode via hitting the ESC key.

This delay basically leads to a lot of errors. As a vim user I'm accustomed to apply very fast (muscle memory style) commands. When hitting keys inside the approx. .75 second delay spacemacs takes to go from INSERT to NORMAL they are interpreted as emacs/spacemacs commands.

## Example
A combination of  `ESC` `j` in vim  INSERT mode would put my cursor down one line. With the delay described here it will rather move my line and for example mess up my .org list. Even worse, undo (`U`) will not undo that move. I have therefore messed up already alot of things in my files, like headlines being full uppercase (guess `ESC U`)  

## Solution
I suggest to make the timeout configurable, if it is already please point to the docs.

**Comment by lebensterben** [comment]
looks duplicate https://github.com/syl20bnr/spacemacs/issues/5413
please try the workaround there

**Comment by chris-aeviator** [comment]
thanks for pointing out, at first glance the workaround seems to be targeted to OSX while I'm running on arch linux :-/

**Comment by chris-aeviator** [comment]
I realized that everytime I exit `I` mode, spacemacs saves my file. I'm running this on a M.2 SSD / PCIe NVMe so write time could not possibly be an issue here, but could other processes/ hooks be taking place and slowing things down?

**Comment by lebensterben** [comment]
https://github.com/syl20bnr/spacemacs/issues/5413#issuecomment-194112841

**Comment by chris-aeviator** [comment]
> [#5413 (comment)](https://github.com/syl20bnr/spacemacs/issues/5413#issuecomment-194112841)

:heart:

**Comment by chris-aeviator** [comment]
I didnt realize this since I'm only sometimes in Tmux but my standard shell is zsh which has also it's own escape time setting


## zsh
```
# 10ms
KEYTIMEOUT=1
```

## tmux
```
set -s escape-time 0
```

(https://www.johnhawthorn.com/2012/09/vi-escape-delays/)
