### ISSUE TITLE
dotspacemacs-install-packages doesn't match condition-case in dotspacemacs/sync-configuration-layers

### ISSUE THREAD

**Issue by 15cm** [syl20bnr/spacemacs#15022]
## Description
Got errors  when invoking `dotspacemacs/sync-configuration-layers`:
```
condition-case: Variable: "dotspacemacs-install-packages" has value: "nil" that doesn’t match its type: "(choice (const used-only) (const used-but-keep-unused) (const all))". Validator message: "(user-error Looking for `(choice (const used-only) (const used-but-keep-unused) (const all))' in `nil' failed because:
  all of the options failed
    Looking for `(const used-only)' in `nil' failed because:
      not the expected value
    Looking for `(const used-but-keep-unused)' in `nil' failed because:
      not the expected value
    Looking for `(const all)' in `nil' failed because:
      not the expected value)"
```

## System Info
System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 59852a6ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((spacemacs-layouts :variables layouts-autosave-delay 300)
 (shell :variables shell-default-shell ’multi-term shell-default-height 30 shell-default-position ’bottom)
 spell-checking chinese neotree
 (ranger :variables ranger-show-preview t ranger-show-literal nil ranger-ignored-extensions
         ’("mkv" "iso" "mp4" "zip" "tar")
         ranger-max-preview-size 10 ranger-parent-depth 2)
 systemd restclient
 (auto-completion :variables spacemacs-default-company-backends
                  ’((company-files company-capf)
                    (company-abbrev company-dabbrev))
                  auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t)
 semantic emacs-lisp lsp dap scheme
 (c-c++ :variables c-c++-default-mode-for-headers ’c++-mode c-c++-backend ’lsp-ccls)
 rust
 (go :variables go-backend ’lsp go-use-golangci-lint t)
 (python :variables python-backend ’lsp python-lsp-server ’pyright python-sort-imports-on-save nil)
 (java :variables java-backend nil)
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-backend ’lsp ruby-version-manager ’rbenv)
 (javascript :variables javascript-backend ’lsp javascript-fmt-on-save t javascript-fmt-tool ’prettier)
 (typescript :variables node-add-modules-path t typescript-backend ’lsp typescript-linter ’eslint typescript-fmt-on-save t typescript-fmt-tool ’prettier)
 haskell react yaml html lua shell-scripts vimscript sql csv syntax-checking
 (org :variables org-enable-github-support t org-startup-indented t org-enable-roam-support t)
 markdown
 (latex :variables latex-build-command "XeLaTeX")
 nginx git github prodigy my-better-defaults my-writing my-programming)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

## Cause
The cause is that dotspacemacs-install-packages is locally bound to `nil` in `dotspacemacs//test-dotspacemacs/layers` when testing the config during sync:  https://github.com/syl20bnr/spacemacs/blob/develop/core/core-dotspacemacs.el#L1092.

## Solution
When protecting the dotspacemacs-* variables in config testing, we should bind them to their current values instead of `nil`.

**Comment by lebensterben** [comment]
@15cm 
I'm trying to reproduce this error by invoking `dotspacemacs/sync-configuration-layers` but don't see the error.

**Comment by lebensterben** [comment]
the linked PR modified `dotspacemacs//test-dotspacemacs/layers`, which is called by `dotspacemacs/test-dotfile` which in turn is called during `dotspacemacs/sync-configuration-layers`.

I also tested with `dotspacemacs/test-dotfile` and cannot reproduce this error either.

In you `.spacemacs`, can you make sure `dotspacemacs-install-packages` has a correct value.

**Comment by 15cm** [comment]
Thank you for looking into this @lebensterben. For reference https://github.com/15cm/spacemacs-config is my config. I realized that the cause is that I incorrectly moved dotspacemacs-install-packages to `dotspacemacs/init` in the [config](https://github.com/15cm/spacemacs-config/blob/cbd7876c1c4ba42a68042e8d2c6213e388716606/init.el#L684). After moving it to `dotspacemacs/layers` as shown by the [.spacemacs.template](https://github.com/syl20bnr/spacemacs/blob/99e74fbd0ec0d6a000bf24cc7f162304d09e55a9/core/templates/.spacemacs.template) the issue is resolved. 

`dotspacemacs//test-dotspacemacs/layers` expects `dotspacemacs/layers` to set `dotspacemacs-install-packages` to a valid value rather then the default nil initialized in the `let`. I would argue it's better to initialize `dotspacemacs-install-packages` to a valid default value rather than nil. But it's not a blocker to close this comment.

PS: One way to reproduce the issue:
```
git clone https://github.com/15cm/spacemacs-config ~/.spacemacs.d
cd ~/.spacemacs.d
git checkout cbd7876c1c4ba42a68042e8d2c6213e388716606
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
emacs -nw .
```
Wait a while for the packages to install, then call `dotspacemacs/sync-configuration-layers` in Emacs.
