### ISSUE TITLE
Windows 10 Python dev - activating a venv spits out JSON-readtable-error 80 and LSP doesn't recognize Pyright

### ISSUE THREAD

**Issue by Zamachi** [syl20bnr/spacemacs#15026]
#### Description :octocat:
Activating a Python venv environment using "pyvenv-workon" spits out JSON-readtable-error 80.
Opening a Python project doesn't detect any language servers and sometimes spits out pycompile errors. 
The instructions followed for Pyright installation were taken from the documentation: https://develop.spacemacs.org/layers/+lang/python/README.html#microsoft-pyright-language-server 

#### Reproduction guide :beetle:
- Configure the Spacemacs dotfile the following layers:
 1. lsp
 2. python
 3. git
- Set the following in user config:   (setenv "WORKON_HOME" "~/.venvs/")
- Reload Emacs to install the packages and for it to configure itself, then close it again
- In the ~/.venvs/ folder, open up a shell (I used Powershell), type the following command to create a virtual environment: *python -m venv cs50-ai*(or whichever name you'd like)
- Activate the environment: on Windows 10, it's using the command *./environment-name(cs50-ai)/Scripts/activate.ps1*
- Upgrade pip
- Using pip3 install the following packages: isort, pyflakes, pillow, npm
- Using npm install Pyright, as instructed by the Spacemacs documentation: *npm install pyright*
- Exit the terminal and start Emacs
- Use the command *pyvenv-workon* and select cs50-ai(or whichever name u chose) to work on a specific virtual environment. (This is when it should spit out JSON-readtable error)
- Use *SPC p p* and find a project which contains Python files (*.py extension). After opening a project, the LSP will prompt you to automatically install a server(only offering mspyls), whilst it should use the one installed in the venv.
- 

*Observed behaviour:* :eyes: :broken_heart:
Opening up emacs and using a function *pyvenv-workon* produces JSON-readtable-error 80, with nothing else displayed or visually malfunctioning.
Opening up a Python project with *SPC p p* doesn't recognize any venv-installed language servers and it prompts to automatically install them. 

*Expected behaviour:* :heart: :smile:
Open up configured Spacemacs, preferably start a Python venv *BEFORE* opening up a project.
Open a project with *SPC p p*. Project should automatically detect the chosen virtual environment and load up all libraries and packages installed, including installed(if they are) Python interpreter(I don't have any installed in the venv itself, I use the global interpreter) and language server(in my case it's Pyright installed via npm according to the documentation provided above). 

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 59852a6ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lsp python emacs-lisp git helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
*Messages* buffer:
Loading c:/Users/Zamachi/.spacemacs...done
../../Users/Zamachi/.emacs.d/elpa/27.2/develop/window-purpose-20210628.715/window-purpose-fixes.el: Obsolete name arg "helm" to constructor purpose-conf
../../Users/Zamachi/.emacs.d/elpa/27.2/develop/window-purpose-20210628.715/window-purpose-fixes.el: Obsolete name arg "Neotree" to constructor purpose-conf
../../Users/Zamachi/.emacs.d/elpa/27.2/develop/window-purpose-20210628.715/window-purpose-fixes.el: Obsolete name arg "guide-key" to constructor purpose-conf
../../Users/Zamachi/.emacs.d/elpa/27.2/develop/window-purpose-20210628.715/window-purpose-fixes.el: Obsolete name arg "which-key" to constructor purpose-conf
../../Users/Zamachi/.emacs.d/elpa/27.2/develop/window-purpose-20210628.715/window-purpose-fixes.el: Obsolete name arg "zone" to constructor purpose-conf
../../Users/Zamachi/.emacs.d/elpa/27.2/develop/window-purpose-20210628.715/window-purpose-x.el: Obsolete name arg "purpose-x-code1" to constructor purpose-conf
../../Users/Zamachi/.emacs.d/elpa/27.2/develop/window-purpose-20210628.715/window-purpose-x.el: Obsolete name arg "magit-single" to constructor purpose-conf
../../Users/Zamachi/.emacs.d/elpa/27.2/develop/window-purpose-20210628.715/window-purpose-x.el: Obsolete name arg "magit-multi" to constructor purpose-conf
../../Users/Zamachi/.emacs.d/elpa/27.2/develop/window-purpose-20210628.715/window-purpose-x.el: Obsolete name arg "popwin" to constructor purpose-conf
Spacemacs is ready.
Loading c:/Users/Zamachi/.emacs.d/.cache/recentf...done
Skipping check for new version (reason: dotfile)
Package cl is deprecated
Auto-evilification could not remap these functions in map ‘edebug-mode-map’:
   - ‘edebug-Go-nonstop-mode’ originally mapped on ‘G’
helm-M-x-execute-command: JSON readtable error: 80
[yas] Prepared just-in-time loading of snippets successfully.
Importmagic and/or epc not found. importmagic.el will not be working.
Suspicious state from syntax checker python-pycompile: Flycheck checker python-pycompile returned 49, but its output contained no errors: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

Try installing a more recent version of python-pycompile, and please open a bug report if the issue persists in the latest release.  Thanks!

*lsp-log* buffer:

Command "pylsp" is not present on the path.
Command "pyls" is not present on the path.
```

**Comment by lebensterben** [comment]
I suggest to try pyenv instead. I'm using it for years and haven't seen issues.

**Comment by Zamachi** [comment]
But pyenv is for using different Python versions in different venvs, not to create venvs themselves, right?
I don't want a different version, this one I have is the one I want.

**Comment by lebensterben** [comment]
check Pyongyang-virtualenv

**Comment by Zamachi** [comment]
The issue still isn't resolved, I've decided to dump this and move my config onto WSL, it works properly over there without the need for pyenv, virtualenv, virtualenvwrapper or any third party software for Python virtual environments, using built-in python3-venv is simple enough
