### ISSUE TITLE
(Wrong-type-argument stringp nil) when I eval my init.el 

### ISSUE THREAD

**Issue by VIVIDryan** [syl20bnr/spacemacs#15056]
I just installed spacemacs in emacs in windows, and I try to eval-buffer when i open the init.el. And it came out the error. I tried to use  'M-x toggle-debug-on-error'. And it comes out the following place when error happened.
![image](https://user-images.githubusercontent.com/30765034/134154431-d9076e1c-ba82-4a2b-a78b-087bee2487bd.png)
Please help me!

**Comment by lebensterben** [comment]
This is not intended to be run in this way.
load-file-name is set by load.
normally ~/.emacs.d/init.el is loaded automatically and the said variable is set correctly. Then there would be no error.
