### ISSUE TITLE
Org mode `org-headline-done` face

### ISSUE THREAD

**Issue by dschrempf** [syl20bnr/spacemacs#15055]
Recently, the the default value of `org-fontify-done-headline` was changed to `t`. This means that headlines after the DONE keyword are fontified using the face `org-headline-done`. I think the standard spacemacs themes don't have a proper setting for this face (at least it is very different from the default on my screen and does not really fit). Do you think it makes sense to set this face in spacemacs?

**Comment by lebensterben** [comment]
@dschrempf 
Please report to the upstream https://github.com/nashamri/spacemacs-theme
