### ISSUE TITLE
https://orgmode.org/elpa/org-plus-contrib-20210920.tar Not found

### ISSUE THREAD

**Issue by gred7** [syl20bnr/spacemacs#15063]
#### Description :octocat:
   An error occurred while installing org-plus-contrib (error: (file-error https://orgmode.org/elpa/org-plus-contrib-20210920.tar Not found))

#### Reproduction guide :beetle:
- upgrade spacemacs via cd .emacs && git pull
- start emacs
- it will try to do package upgrade
- see error

*Observed behaviour:* :eyes: :broken_heart:
Error updating org-plus-contrib

*Expected behaviour:* :heart: :smile:
Everithing is updating properly

#### System Info :computer:
- OS: berkeley-unix
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f5bd49cc8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html perl5 ivy auto-completion better-defaults emacs-lisp git markdown org syntax-checking treemacs version-control c-c++ go rust php python yaml ansible terraform docker kubernetes csv templates nginx sql)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG DBUS GSETTINGS GLIB NOTIFY KQUEUE GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
what do you see when you open the link in browser

**Comment by gred7** [comment]
On Sun, 26 Sep 2021 06:34:32 -0700
Lucius Hu ***@***.***> wrote:

> what do you see when you open the link in browser
> 

hmm, works now. perhaps some problems reaching the host or file was
absent then re-appeared. anyway, sorry for the buzz.
