### ISSUE TITLE
Spacemacs with emacs25?

### ISSUE THREAD

**Issue by johalun** [syl20bnr/spacemacs#15073]
How do I use spacemacs with emacs25 (getting error that emacs26 is required)? Is there a branch or a commit I can checkout that will be compatible?
Please don't tell me to update to emacs26, that is not an option on some of the hosts I'd like to run spacemacs on. 

Thanks!

**Comment by lebensterben** [comment]
you can always build Emacs from source on any host you'd like to run.

alternatively check out an older commit of develop branch when 25 is still accepted.

**Comment by johalun** [comment]
> alternatively check out an older commit of develop branch when 25 is still accepted.

That's what I'm wondering about. Do we know when that is? Date or commit hash?

**Comment by lebensterben** [comment]
before e5be31bb8541e420c5fae666980287753f3c90e0

**Comment by johalun** [comment]
Thanks!
