### ISSUE TITLE
set powerline-scale not work

### ISSUE THREAD

**Issue by masterAllen** [syl20bnr/spacemacs#15080]
I want to adjust height of mode-line and i see `powerline-scale` work for this in documentation.

Here is a part of my .spacemacs:
```lisp
(defun dotspacemacs/init ()
  (setq-default
     ;; ...
     dotspacemacs-default-font '("Source Code Pro"
                                  :size 26
                                  :weight normal
                                  :width normal
                                  :powerline-scale 2)
  )
)
```
However, the height of mode-line not change.(change font size is ok)
And i found there are some statements in `.emacs.d/core/core-fonts-support.el` :
```lisp
(defun spacemacs/compute-mode-line-height ()   
"Return an adjusted mode-line height."  
 (let ((scale (if (and (boundp 'powerline-scale) powerline-scale)                    
                  powerline-scale 1)))     
    (truncate (* scale (frame-char-height))))) 
```

If i change powerline-scale to 2:
```lisp
(defun spacemacs/compute-mode-line-height ()   
"Return an adjusted mode-line height."  
 (let ((scale (if (and (boundp 'powerline-scale) powerline-scale)      
;; change powerline-scale to value               
                  2 1)))     
    (truncate (* scale (frame-char-height))))) 
```
Then i reboot emacs, changing height of modeline is successful. 

So how can i change `powerline-scale` in `.spacemacs` to adjust height of modeline. THANKS.

System Information
- OS: Arch Linux x86_64
- emacs: GUN Emacs 27.2
- spacemacs: 0.300.0@27.2

**Comment by HanshenWang** [comment]
I have this line in my .spacemacs user-config to change the modeline width.

``` emacs-lisp
(setf powerline-scale 0.50)
```

Have you tried placing your configuration after packages are loaded in
user-config versus user-init?

**Comment by masterAllen** [comment]
Yes, that works! Thank you very much!!! @HanshenWang

**Comment by HanshenWang** [comment]
Not a problem :).

For posterity, and a full explanation why user-config is preferred over user-init in this case, see: https://stackoverflow.com/a/37087862.

Open a pull request if any of these questions weren't clear from the documentation under `SPC h SPC`!

Happy emacsing,
