### ISSUE TITLE
Cannot press k to discard item in magit in holy-mode

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1509]
With recent changes, `k` in Magit is now `spacemacs//auto-completion-key-sequence-end`, not `magit-discard-item`.

**Comment by syl20bnr** [comment]
Thanks for the report. I already remove "jk" as a default, this feature is not enabled by default and it has to be explicitly enabled.
The regression is still here though, I will add a passthrough in read-only buffers and buffers without any auto-completion minor modes activated.

**Comment by syl20bnr** [comment]
Can you test this again with the feature enabled on "jk", the fix a did for #1491 should resolve this kind of issue.

**Comment by syl20bnr** [comment]
I tried it in holy-mode and it is OK on my side. Re-open the issue if you have still issues.
