### ISSUE TITLE
PDFView mode not working

### ISSUE THREAD

**Issue by jia-j-chen** [syl20bnr/spacemacs#15096]
#### Description :octocat:
When I try to open PDF files with the PDFView mode. The Spacemacs keys fail. I cannot solve the problem by following #13974.

#### Reproduction guide :beetle:
- Start Emacs
- Open a PDF file 

*Observed behaviour:* :eyes: :broken_heart:
- Try to move through the file
- Get errors "j is undefined" or "k is undefined"
- Get an error in the *Warnings* buffer: "Error (use-package): pdf-tools/:config: Selecting deleted buffer"

*Expected behaviour:* :heart: :smile:
- I search online and find https://github.com/syl20bnr/spacemacs/issues/13974
- I follow this link to
  1. Remove the pdf-tools package with "cd .emacs.d/elpa/27.2/develop" and "rm -rf pdf-tools-*"
  2. Restart spacemacs.
  3. SPC SPC pdf-tools-install
  4. Answer "y" to question "Need to (re)build the epdfinfo program, do it now ? (y or n)"
- Then, the issue is temporarily solved.
- However, if I close spacemacs and reopen it again, the issue will show up again.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 63056ec)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((helm :variables helm-candidate-number-limit 1000)
 emacs-lisp git
 (markdown :variables markdown-live-preview-engine 'vmd)
 bibtex html csv org ess
 (chinese :variables chinese-enable-fcitx t chinese-fcitx-use-dbus t pyim-default-scheme 'microsoft-shuangpin)
 (latex :variables latex-enable-folding t latex-enable-auto-fill t)
 auto-completion ranger version-control pdf
 (mu4e :variables mu4e-use-maildirs-extension t mu4e-installation-path "/usr/share/emacs/site-lisp" mu4e-enable-async-operations t mu4e-maildir "/home/chenj/Maildir" mu4e-sent-folder "/Local_sent" mu4e-headers-full-search nil mu4e-headers-results-limit 500 mu4e-drafts-folder "/Drafts" mu4e-trash-folder "/Deleted_Messages" mu4e-attachment-dir "~/Downloads" mu4e-get-mail-command "offlineimap" mu4e-view-show-images t mu4e-view-show-addresses t mu4e-headers-date-format "%Y-%m-%d %H:%M" mu4e-compose-reply-to-address "jia.j.chen@foxmail.com" user-mail-address "jia.j.chen@foxmail.com" user-full-name "Jia CHEN" send-mail-function 'async-smtpmail-send-it message-send-mail-function 'async-smtpmail-send-it smtpmail-smtp-server "smtp.qq.com" smtpmail-smtp-service 465 smtpmail-stream-type 'ssl smtpmail-auth-credentials
       (expand-file-name "~/.authinfo.gpg")
       mu4e-headers-fields
       '((:date . 18)
         (:flags . 6)
         (:from . 15)
         (:to . 15)
         (:subject))
       mu4e-compose-signature "Jia CHEN @ http://chenjia.gsm.pku.edu.cn" mu4e-maildir-shortcuts
       '(("/INBOX" . 105)
         ("/PKU_Email" . 112)
         ("/Sent_Messages" . 115)))
 better-defaults markdown
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 spell-checking python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 bm
 (colors :variables colors-colorize-identifiers 'all))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Cannot reproduce.
Just added pdf layer and installed the dependencies. But it works as expected, even after restarting.

**Comment by jia-j-chen** [comment]
> Cannot reproduce. Just added pdf layer and installed the dependencies. But it works as expected, even after restarting.

Is there anything that I can do to get more information, such as error messages?

**Comment by lebensterben** [comment]
are you running emacs daemon?

**Comment by lebensterben** [comment]
When you `cd ~/.emacs.d/27.2/develop/pdf-tools-20211004.514`, do you see `epdfinfo`?

**Comment by jia-j-chen** [comment]
> When you `cd ~/.emacs.d/27.2/develop/pdf-tools-20211004.514`, do you see `epdfinfo`?

Yes. I can see it.

Please note that I can solve the issue with `SPC SPC pdf-tools-install` and answer y to question "Need to (re)build the epdfinfo program, do it now ? (y or n)". By now, I can see `epdfinfo`.

However, the issue appears again after restarting emacs. I can still see `epdfinfo` after restarting emacs.

**Comment by lebensterben** [comment]
what if you add (setq pdf-info-epdfinfo-program to (expand-file-name "~/.emacs.d/27.2/develop/pdf-tools-20211004.514/epdfinfo")?

**Comment by lebensterben** [comment]
what if you evaluate
`(let ((pdf-info-restart-process-p t)) (pdf-tools-install-noverify))`?

**Comment by lebensterben** [comment]
no. I mean after evaluating this, does the problem persist?

**Comment by lebensterben** [comment]
you can put it after (require 'pdf-tools)

but by evaluation, I mean you can open a PDF file and type ":" and the rest of the forms in the minibuffer

**Comment by lebensterben** [comment]
You mentioned `pdf-tools-install` so I first thought there's something wrong with the underlying program. But it turned out that it's built and the it's setup properly.

Reading the [source code](https://github.com/vedang/pdf-tools/blob/f68899cf0646255ca763f1144f7a9520e7cd46db/lisp/pdf-tools.el#L364) and I find `pdf-tools-install` calls `pdf-tools-install-noverify` after building the `epdinfo`. So I asked you to evaluate the aforementioned forms.

The strange thing is `pdf-tools-install` is already called when you open a `.pdf` file https://github.com/syl20bnr/spacemacs/blob/5c88c3b089c132997bf9f571a0207d93739efef1/layers/%2Breaders/pdf/packages.el#L36

This time remove anything you added to fix the problem and open the pdf file.
Do you see major mode 'PDF' showing up in your modeline?

**Comment by jia-j-chen** [comment]
> You mentioned `pdf-tools-install` so I first thought there's something wrong with the underlying program. But it turned out that it's built and the it's setup properly.
> 
> Reading the [source code](https://github.com/vedang/pdf-tools/blob/f68899cf0646255ca763f1144f7a9520e7cd46db/lisp/pdf-tools.el#L364) and I find `pdf-tools-install` calls `pdf-tools-install-noverify` after building the `epdinfo`. So I asked you to evaluate the aforementioned forms.
> 
> The strange thing is `pdf-tools-install` is already called when you open a `.pdf` file
> 
> https://github.com/syl20bnr/spacemacs/blob/5c88c3b089c132997bf9f571a0207d93739efef1/layers/%2Breaders/pdf/packages.el#L36
> 
> This time remove anything you added to fix the problem and open the pdf file. Do you see major mode 'PDF' showing up in your modeline?

After removing everything that I added to .spacemacs to fix the problem, I see `PDFView` showing up in my modeline.

**Comment by jia-j-chen** [comment]
> this proves that pdf-tools is installed correctly and the major mode is already set to `pdf-view-mode`.
> 
> At this point, verify the following:
> 
> * `(describe-variable 'auto-mode-alist)` contains `("\\.[pP][dD][fF]\\'" . pdf-view-mode)`
**This is true.**

> * `(describe-variable 'magic-mode-alist)` contains `("%PDF" . pdf-view-mode)`
**This is true.**

> * One of the following is true:
>   
>   * `(memq 'pdf-occur-global-minor-mode pdf-tools-enabled-modes)` is nil
**This is not true. It returns `(pdf-occur-global-minor-mode)`.**

>   * `(describe-variable 'pdf-occur-global-minor-mode)` is nil
**This is not true. It returns `Its value is t
Original value was nil
`**

> * One of the following is true:
>   
>   * `(memq 'pdf-virtual-global-minor-mode pdf-tools-enabled-modes)` is nil
**This is true.**

>   * `(describe-variable 'pdf-virtual-global-minor-mode)` is nil
**This is true.**

> 
> To evaluate any of these, in normal state, type `:` and the rest of the form.
