### ISSUE TITLE
git layer is broken after "git-modes", replacing "git{attribues,config,ignore}-mode"

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#15113]
#### Description :octocat:
git layer is broken after "git-modes", replacing "git{attribues,config,ignore}-mode"

See
- https://github.com/melpa/melpa/commit/cc3a0ce6c8a4a67b8a8d4b8b2c090694535e6848
- https://github.com/syl20bnr/spacemacs/issues/15111

#### Reproduction guide :beetle:
- Make a fresh install of spacemacs: git clone --depth 1 https://github.com/syl20bnr/spacemacs ~/.emacs.d
- Start Emacs
- Add git layer
- Restart Emacs and watch the error happen

*Observed behaviour:* :eyes: :broken_heart:

```
(Spacemacs) --> installing package: gitattributes-mode@git... [1/4]
(Spacemacs) --> installing package: gitconfig-mode@git... [2/4]
(Spacemacs) --> installing package: gitignore-mode@git... [3/4]
(Spacemacs) --> installing package: helm-gitignore@git... [4/4]
(Spacemacs) Error:
An error occurred while installing helm-gitignore (error: (error Package ‘gitignore-mode-1.1.0’ is unavailable))
```

*Expected behaviour:* :heart: :smile:
Git layer should install without errors.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.60
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f320524)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp epub git helm html info
                 (javascript :variables javascript-backend 'tide)
                 json
                 (lsp :variables lsp-use-lsp-ui t lsp-ui-doc-enable t lsp-rust-server 'rust-analyzer cargo-process-reload-on-modify t)
                 markdown
                 (mu4e :variables mu4e-view-show-images t mu4e-view-show-addresses t)
                 (org :variables org-enable-org-journal-support t)
                 pdf scala spell-checking syntax-checking systemd themes-megapack tide treemacs
                 (typescript :variables typescript-backend 'tide tide-tsserver-executable "/usr/bin/tsserver")
                 (xclipboard :variables xclipboard-enable-cliphist t)
                 yaml)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS GTK3 ZLIB

**Comment by tarsius** [comment]
Sorry for not proactively informing you.

The announcement is here: https://emacsair.me/2021/10/21/git-modes.
