### ISSUE TITLE
CIDER's REPL starts in a non-state

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#1511]
When I start up CIDER's REPL, the mode-line is blank, and the `evil-state` variable is `nil`. I tried looking around the contrib clojure-layer but couldn't at first glance figure out what is causing it.

**Comment by syl20bnr** [comment]
Can you give a repro step ?

**Comment by luxbock** [comment]
Alright so appears to be an issue with my config, as I can't reproduce the issue with a barebones Spacemacs.

I tried removing all clojure and cider specific customizations from my dotspacemacs file and my packages, but that didn't solve the issue, so I will investigate further.

**Comment by syl20bnr** [comment]
I'm not sure to understand the issue, if you give me reproduction steps I can see if I have the same behavior.
