### ISSUE TITLE
Heads up: gitignore-mode and gitconfig-ode were moved to git-modes

### ISSUE THREAD

**Issue by ctsk** [syl20bnr/spacemacs#15111]
Ref: https://github.com/melpa/melpa/commit/cc3a0ce6c8a4a67b8a8d4b8b2c090694535e6848

The packages were merged under a new name, the old packages are no longer available.

**Comment by nfedyashev** [comment]
Before this is fixed in the `develop` branch I added 4 packages to the dotspacemacs-excluded-packages

helm-gitignote
gitattributes-mode
gitconfig-mode
gitignore-mode
