### ISSUE TITLE
Yasnippet expansion, hippie-expand and smartparens

### ISSUE THREAD

**Issue by jcpetkovich** [syl20bnr/spacemacs#1512]
Something strange is happening when expanding certain snippets using `hippie-expand` while `smartparens` is activated.

I can reproduce the issue on `develop` with a fresh `.spacemacs` template with only the `auto-completion` layer added:

1. clone spacemacs
2. initialize spacemacs, add `auto-completion` layer
3. start spacemacs
4. open a file `test.c`
5. type `main`
6. invoke `yas-expand` 
7. observe the correct result
8. delete buffer contents and type `main`
9. invoke `hippie-expand`
10. observe incorrect result (extra closing paren)

Sample of incorrect expansion:
```c
int main()int argc, char *argv[])
{
  
  return 0;
}
```

I have observed that toggling `smartparens` before and after like so:

```lisp
(add-to-list 'yas-before-expand-snippet-hook
             'spacemacs/toggle-smartparens)

(add-to-list 'yas-after-exit-snippet-hook
             'spacemacs/toggle-smartparens)
```

Resolves the issue, but I haven't been able to track down exactly why.

**Comment by tuhdo** [comment]
Hmm if this can't be fixed upstream maybe we should revert back to `company`.

**Comment by syl20bnr** [comment]
I thought this issue was resolved. See #541
So maye we could just add the hooks.

**Comment by herbertjones** [comment]
This also occurs when quotes are inside a snippet.  For snippet:

```
# -*- mode: snippet; require-final-newline: nil -*-
# name: include - quotes
# key: inc
# binding: direct-keybinding
# --
#include "${1:`(file-name-nondirectory (file-name-sans-extension (buffer-file-name)))`.hpp}"$0
```

expanding on ```inc``` produces:

```
#include "|"filename.hpp"
```

when

```
#include "|filename.hpp"
```

is expected.

Observed in ```develop 5b72221```.

**Comment by CestDiego** [comment]
@tuhdo why don't you PR this fix? does it work?

**Comment by tuhdo** [comment]
@CestDiego It should be fixed now. Do you have any problem? I have no problem with the latest `master`.

**Comment by tuhdo** [comment]
Ah I thought that this problem is related to `yasnippet` not enabled properly. If so, it's not merged yet: https://github.com/syl20bnr/spacemacs/pull/1644
