### ISSUE TITLE
Pressing enter at the end of a list item should create a new list item

### ISSUE THREAD

**Issue by 01abhishekjain** [syl20bnr/spacemacs#15128]
I want org-mode to default to alt-enter when under bullets, so that for bullets I can just press enter to make a new bullet.

So for instance:

Banana
Apple
Kiwi [MOUSE CURSOR HERE]
When I press enter, I want the following behavior (which happens when I press M-enter):

Banana
Apple
Kiwi
[MOUSE CURSOR HERE]
Instead of:

Banana
Apple
Kiwi
[MOUSE CURSOR HERE]

This used to be the behaviour until I recenty updated Spacemacs to the latest version. Not sure which version I was on previously.

**Comment by smile13241324** [comment]
Feature request, PRs are welcome 👩‍💻

**Comment by ajain-bst** [comment]
Thing is, it's not a **new** feature request as this has been the default behaviour on a recent earlier version of Spacemacs.

**Comment by lebensterben** [comment]
@ajain-bst 
there's no change to the bindings in org-mode recently.

https://github.com/syl20bnr/spacemacs/blame/develop/layers/%2Bemacs/org/packages.el#L357-L358

**Comment by lebensterben** [comment]
this is a low-hanging fruit.
Anyone interested in this could submit a PR s.t. it adds a new layer config variable that swap the binding of RET and M-RET.
