### ISSUE TITLE
`evil-redirect-digit-argument` File mode specification error: (void-function evil-redirect-digit-argument) 

### ISSUE THREAD

**Issue by dhawangayash** [syl20bnr/spacemacs#15123]
#### Description :octocat:
This isn't a bug per se but would like this documented as a known issue in spacemacs. 
Updating spacemacs packages leads to a broken dependency being pulled in from `evil-org-mode`.

#### Reproduction guide :beetle:
- Start Emacs
- Update spacemacs packages: `SPC f e U`
- This installs the broken version of `evil-org-mode`, package.

*Observed behaviour:* :eyes:
The following error message is printed on *Message* buffer. 
`File mode specification error: (void-function evil-redirect-digit-argument)`

*Expected behaviour:* :heart: :smile:
Everything should work without issues. :)

#### Backtrace :paw_prints:
NOT APPLICABLE.

#### Work around
This isn't a bug per se but would like this documented as a known issue in spacemacs. 

The latest version of `evil-org-mode` is broken owing to [this](https://github.com/Somelauw/evil-org-mode/issues/93)

So for any of you who has recently updated their packages will face the bug. The work around is provided in a comment [here](https://github.com/Somelauw/evil-org-mode/issues/93#issuecomment-949953955). 

I have tried it out and it works. I think this issue should be kept open to help others and closed once evil-org-mode comes with a newer fixed version.

**Comment by enisozgen** [comment]
There is quick fix:

https://github.com/Somelauw/evil-org-mode/issues/93#issuecomment-949953955

**Comment by bhoudebert** [comment]
There is also a very simple fix for evil-iedit-state here https://github.com/syl20bnr/evil-iedit-state/pull/37

**Comment by lebensterben** [comment]
As suggested in other comments, this results from breaking change in upstream API.
Now we should wait for updates in affected packages.

**Comment by smile13241324** [comment]
Added the temporary fix from @dalanicolai to heal the symptom. Still if the referenced pqckage is unmaintained we should switch to a maintained fork in the long run.

**Comment by dalanicolai** [comment]
FYI, the improved fix in #15184 is great, but it requires recompilation of `evil-iedit-state.el` (recompilation after the macro from the fix has already been loaded).

**Comment by gitprouser** [comment]
@dalanicolai I had to fetch the latest code change and I had to recompile all packages using `SPC r c`.

**Comment by dalanicolai** [comment]
I think it should be sufficient that you make sure you have the new macro loaded (i.e. sync/git pull spacemacs, restart, and press `SPC s e` somewhere to load the macro). Then you can do `M-x find-library` `evil-iedit-state` and then you do `M-x byte-recompile` only that file.
