### ISSUE TITLE
helm behavior different with original helm in Spacemacs

### ISSUE THREAD

**Issue by sunlin7** [syl20bnr/spacemacs#15124]
When enable the `helm` in `dotspacemacs-configuration-layers`, it always have to input full path and file name to copy a `test.txt` file. Reproducing steps as follow
1. creating testing folder structure and files with
```
touch ~/test.txt
mkdir -p /tmp/.s/.SpaceVim /tmp/.s/.SpaceVim.d /tmp/.s/.cache /tmp/.s/.cmake /tmp/.s/.config /tmp/.s/.dbus /tmp/.s/.emacs.d /tmp/.s/.emacs.save /tmp/.s/.emacs.spacemacs /tmp/.s/.gnupg /tmp/.s/.home.sl /tmp/.s/.ipython /tmp/.s/.java /tmp/.s/.jitsi /tmp/.s/.local /tmp/.s/.mozilla /tmp/.s/.npm /tmp/.s/.opm /tmp/.s/.pki /tmp/.s/.vim /tmp/.s/.pylint.d /tmp/.s/.root /tmp/.s/.ssh /tmp/.s/.var /tmp/.s/.wine /tmp/.s/.yarn /tmp/.s/.zbstudio /tmp/.s/dev-env /tmp/.s/logs /tmp/.s/packages /tmp/.s/projects /tmp/.s/tmp /tmp/.s/workspace 
touch /tmp/.s/.Xauthority /tmp/.s/.ZeroBraneStudio /tmp/.s/.arcrc /tmp/.s/.authinfo /tmp/.s/.bashrc /tmp/.s/.bash_history /tmp/.s/.bash_logout /tmp/.s/.bash_profile /tmp/.s/.emacs /tmp/.s/.esd_auth /tmp/.s/.fakexinerama /tmp/.s/.fs_cli_history /tmp/.s/.gdbinit /tmp/.s/.gitconfig /tmp/.s/.lesshst /tmp/.s/.mysql_history /tmp/.s/.opmrc /tmp/.s/.pdf-view-restore /tmp/.s/.python_history /tmp/.s/.rediscli_history /tmp/.s/.rnd /tmp/.s/.spacemacs /tmp/.s/.spacemacs.env /tmp/.s/.sqlite_history /tmp/.s/.viminfo /tmp/.s/.xmodmap /tmp/.s/.yarnrc /tmp/.s/.z
```
2. browser `~/` with `(dired "~/")`
3. move cursor to `test.txt` and press `C`
4. input `/tmp/.s/` (that mean try to copy `~/test.txt` as `/tmp/.s/test.txt`), can't continue unless input file name `test.txt`.

It seems a Spacemacs special bug, by run `./emacs-helm.sh` with vallina `helm`, the issue do not exist.

Here are the screen snapshort, left part is by running `./emacs-helm.sh`, you can see the folder path are in top, can be selected easyly.
The right part is Spacemacs, the folder path is not in top of list, user have to input full path `/tmp/.s/test.txt` and press enter to finish copy.
![Untitled](https://user-images.githubusercontent.com/4402280/138856713-f1fda1c8-c95e-46dd-a514-bfdd9a84e2f9.png)

Transfered from: https://github.com/emacs-helm/helm/issues/2451

**Comment by emacs18** [comment]
I cannot reproduce the problem.   I have two windows both showing dired-mode for two different directories.  If I hit C with the cursor over a file, then all I have to do is hit  Enter when helm pop-up buffer shows up.  The result is to copy the file under cursor to the directory shown in other buffer, i.e., I see /tmp/.s/. shown in green circle above rather than red circle.  I use
- latest version on spacemacs develop branch
- ubuntu 20.04
- emacs 27 and 28 I built using latest source code
- default .spacemacs file with no customizations other to select vim editing style

**Comment by sunlin7** [comment]
Original issue still exists after I upgrade to last devel branch.
It should relate to the custome part of helm in Spacemacs.

**Comment by smile13241324** [comment]
Seems to be a sorting issue, this happens when the target folder is starting with a ".", in this case the order of helm values is completely random resulting in this strange bug. Not hidden folders work as normal.

I need to have a more detailed look into what is causing this.

**Comment by sunlin7** [comment]
I find remove this function will give the expected list when do dired copy, I'll continue the investigation.
`(advice-remove 'helm-make-source #'spacemacs//helm-make-source)`

**Comment by sunlin7** [comment]
It seems the Spacemacs change helm behaviors on partcial.
Currently the `helm-completion-style` is `helm` in Spacemacs, the options maybe `(helm, helm-fuzzy, emacs)`.
But Spacemacs provide the variable `helm-use-fuzzy` (default value is `always`) to control helm matching behavior.

The behavior of `dired-do-copy` will be changed by Spacemacs with fuzzy matching.
Workaround for me: `(helm :variables helm-use-fuzzy 'source)`

And the solution should re-factory the helm configuration in Spacemacs.

**Comment by sunlin7** [comment]
The official helm provide the `helm-completion-style` with `[helm, helm-fuzzy, emacs]`,
But Spacemacs provide toggle flag `helm-use-fuzzy` with `[always, source]`.

To re-factory the helm configuration in Spacemacs will reduce the gap between official helm.

**Comment by smile13241324** [comment]
Jep this code should go to helm or if it is not useful anymore (obsolete?) be removed. We should not try to fix helm in Spacemacs.

**Comment by sunlin7** [comment]
Agree, we should not do heavy patch to fix helm in Spacemacs.
But I'm not sure the patch in Spacemacs is obsolete or not, especially the advice `spacemacs//helm-make-source`:
https://github.com/syl20bnr/spacemacs/blob/e75e925e3727136c5e1ef51fdd725c72c5f10b9b/layers/%2Bspacemacs/spacemacs-completion/packages.el#L60-L66
