### ISSUE TITLE
Odd powerline separator colours

### ISSUE THREAD

**Issue by kraterrak** [syl20bnr/spacemacs#1513]
I am using Emacs version 24.5.1 on Mac OSX. Since uprading to that version (from 24.3), I have been getting an odd issue with the powerline separator colours, shown below:

![screen shot 2015-05-06 at 15 39 13](https://cloud.githubusercontent.com/assets/2223420/7495597/e5011dac-f406-11e4-8de2-d14a1fe7bea7.png)

This is also a problem on other themes (though some are more subtle than others).

Could you please advise me on how best to fix this?

**Comment by syl20bnr** [comment]
This is addressed in the FAQ: https://github.com/syl20bnr/spacemacs#os-x-1

**Comment by blazeeboy** [comment]
Can we update the reference to the solution I think the README file is updated with new sections.

**Comment by StreakyCobra** [comment]
@blazeeboy http://spacemacs.org/doc/FAQ.html#orgheadline43
