### ISSUE TITLE
Agda's input method doesn't work in echo area for commands with arguments

### ISSUE THREAD

**Issue by lfrestrepog** [syl20bnr/spacemacs#15132]
#### Description :octocat:
Agda's input method doesn't work in echo area for commands with arguments, so it is very difficult to use unicode characters in identifiers. Notice that agda mode sets the input method up by default in vanilla emacs. This is likely just a configuration error.

#### Reproduction guide :beetle:
- Start Emacs
- Make sure Agda layer is configured and edit an Agda source file.
- Use any command that expects arguments in the echo area, a few examples are: SPC m d (infer type of an expression), SPC m n (compute normal form).
- Try any key binding for a unicode character, for instance: \bN

*Observed behaviour:* :eyes: :broken_heart:
The echo area doesn't use agda's input method for unicode characters.

*Expected behaviour:* :heart: :smile:
Agda's input method works in the echo area and users enjoy their nice unicode characters in all sorts of agda expressions.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 63056ecb5)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown emacs-lisp helm multiple-cursors agda treemacs)
```
- System configuration features: JPEG SOUND GPM DBUS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 ZLIB XIM THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
There is none.

**Comment by lfrestrepog** [comment]
It appears the issue is related to evil, switching the editing style to emacs solves it. Now I'm not sure whether to report it to Agda or evil, but certainly it shouldn't be here.

**Comment by lebensterben** [comment]
It may not be a bug. And you can ask the question in evil's community or on Reddit for example

**Comment by lfrestrepog** [comment]
Turns out the input method works fine in edit mode... I thought I'd mention it here in case anyone else faces the same problem later. This is probably obvious to more seasoned users, but I did spend some time looking at configuration options before realising it.
