### ISSUE TITLE
Inconvenience: When reinstalling spacemacs, manual intervention is required; native-comp

### ISSUE THREAD

**Issue by wildwestrom** [syl20bnr/spacemacs#15143]
#### Description :octocat:
This happens on any native-comp branch. When compiling packages for the first time, like during installation of Spacemacs, it will ask if I want to kill buffers that are modified. 
`Buffer ******.el has been modified; Kill anyway? (y or n)`

Usually it's an elisp file being compiled. The default behavior should be to just kill the buffer without asking, as it's not something meant to be edited anyway.

#### Reproduction guide :beetle:
- Install Spacemacs (as per official instructions)
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The message `Buffer ******.el has been modified; Kill anyway? (y or n)` appears repeatedly, requiring me to babysit initial installation.

*Expected behaviour:* :heart: :smile:
Just let the installation continue without intervention.

#### System Info :computer:
- OS: darwin
- Emacs: 29.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 548edefcc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((spacemacs-modeline :variables doom-modeline-height 12 doom-modeline-major-mode-color-icon t doom-modeline-buffer-file-name-style 'relative-to-project doom-modeline-display-default-persp-name t doom-modeline-minor-modes nil doom-modeline-modal-icon nil)
 theming
 (unicode-fonts :variables unicode-fonts-existence-checks 'first unicode-fonts-force-multi-color-on-mac t unicode-fonts-enable-ligatures t unicode-fonts-ligature-modes
                '(prog-mode))
 spell-checking multiple-cursors
 (helm :variables helm-follow-mode-persistent t)
 (ranger :variables ranger-show-preview t ranger-show-hidden t ranger-cleanup-eagerly t ranger-cleanup-on-disable t ranger-ignored-extensions
         '("mkv" "flv" "iso" "mp4"))
 (treemacs :variables treemacs-lock-width t treemacs-width 22 treemacs-indentation 1 treemacs-use-filewatch-mode t)
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak)
 command-log
 (clojure :variables clojure-enable-clj-refactor t cider-repl-display-help-banner nil cider-pprint-fn 'fipp clojure-indent-style 'align-arguments clojure-align-forms-automatically t clojure-toplevel-inside-comment-form t cider-result-overlay-position 'at-point cider-overlays-use-font-lock t cider-repl-buffer-size-limit 100 cider-eldoc-display-for-symbol-at-point nil)
 emacs-lisp haskell java rust shell-scripts html
 (javascript :variables javascript-backend 'lsp)
 typescript react prettier asciidoc csv json
 (markdown :variables markdown-live-preview-engine 'vmd)
 (org :variables org-clock-sound "~/emacs/spacemacs-config/bell.wav" org-enable-github-support t org-enable-asciidoc-support t org-enable-bootstrap-support t org-enable-reveal-js-support t org-enable-roam-support t org-enable-roam-protocol t org-roam-directory "~/Documents/org/Notes/" org-roam-dailies-directory "Journal/" org-roam-v2-ack t org-want-todo-bindings t org-latex-classes
      '("letter" "\\documentclass{letter}"
        ("\\section{%s}" . "\\section*{%s}")
        ("\\subsection{%s}" . "\\subsection*{%s}")
        ("\\subsubsection{%s}" . "\\subsubsection*{%s}")))
 yaml docker floobits
 (git :variables git-magit-status-fullscreen t magit-diff-refine-hunk t git-enable-magit-todos-plugin t)
 github
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 (syntax-checking :variables syntax-checking-use-original-bitmaps t)
 (lsp :variables lsp-enable-on-type-formatting nil lsp-enable-snippet t lsp-enable-symbol-highlighting t lsp-modeline-diagnostics-enable nil lsp-modeline-diagnostics-scope nil lsp-modeline-code-actions-enable nil lsp-ui-doc-show-with-cursor t lsp-ui-doc-show-with-mouse nil lsp-ui-doc-delay 2 lsp-ui-sideline-enable nil lsp-ui-sideline-show-code-actions nil lsp-ui-sideline-show-diagnostics nil lsp-lens-enable nil treemacs-space-between-root-nodes nil lsp-file-watch-threshold 10000 lsp-idle-delay 5.0 lsp-log-io nil)
 graphviz
 (shell :variables shell-default-shell 'vterm shell-default-term-shell "~/homebrew/bin/fish" shell-default-width 30 shell-default-position 'bottom terminal-here-mac-terminal-command 'iterm2))
```
- System configuration features: ACL DBUS GIF GLIB GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS WEBP XIM XWIDGETS ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by thanhvg** [comment]
Yes I notice this problem too. The problem I think is https://github.com/quelpa/quelpa or how Spacemacs uses quelpa. When the packages to install come from official sources like MELPA, GNU... they compile to native code just fine. But when we are pulling packages from sources like github, gitlab... we use quelpa to build them and quelpa is having this little problem like you described but I find that just ignore it with `y` is okay so far.

**Comment by thanhvg** [comment]
Update: Now I suspect it's Emacs 28/29 bug in `package-install-file` I filed a bug report here https://debbugs.gnu.org/cgi/bugreport.cgi?bug=51769

**Comment by thanhvg** [comment]
It has just been fixed in Emacs' emacs-28 branch thanks to a super quick response from Lars Ingebrigtsen, probably will be in master branch very soon. We can close this issue now.
