### ISSUE TITLE
Can’t upgrade to org-mode 9.5

### ISSUE THREAD

**Issue by lazzalazza** [syl20bnr/spacemacs#15141]
#### Description :octocat:
Can’t upgrade to org-mode 9.5

#### Reproduction guide :beetle:
- Start Emacs
- Press SPC f-e-U 

*Observed behaviour:* :eyes: :broken_heart:
Org-mode is always in version 9.4.6.

*Expected behaviour:* :heart: :smile:
Org-mode should be updated to version 9.5 but it doesn’t.

#### System Info :computer:
- OS: darwin
- Emacs: 28.0.60
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 548edefcc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup 'complete)
 bibtex emacs-lisp helm
 (latex :variables latex-enable-folding t latex-enable-magic t latex-build-command "LatexMk")
 multiple-cursors
 (org :variables org-enable-roam-support t)
 org-reledmac pdf pandoc
 (ranger :variables ranger-show-preview t ranger-show-hidden t ranger-preview-delay 0.06 ranger-show-literal nil ranger-cleanup-eagerly t ranger-modify-header nil)
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking spotify personal-keybindings personal-org-settings
 (typography :variables typography-enable-typographic-editing t)
 treemacs)
```
- System configuration features: ACL GIF GLIB GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by HanshenWang** [comment]
I had to manually delete my org-mode files located in
`~/.emacs.d/elpa/27.1/develop` for Org 9.5 to install. Give that a try.

See: https://old.reddit.com/r/spacemacs/comments/qo13xp/spacemacs_v300_uses_org_946_when_95_is_on_gnu_elpa/

**Comment by lazzalazza** [comment]
Curiously enough, it has updated with me without even noticing how and why… I now have 9.5 running.
Maybe some change was made upstream in the meanwhile?

**Comment by lebensterben** [comment]
probably some lags in cdn

**Comment by smile13241324** [comment]
A fix for this has been pushed @lazzalazza please close this ticket if this solved your issue
