### ISSUE TITLE
Add Emacs transparency microstate

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1514]
Transparency is useful when writing graphic code or programs that use GUI. Here is a solution for Emacs transparency:

```elisp
;; set transparency
(set-frame-parameter (selected-frame) 'alpha '(85 85))
(add-to-list 'default-frame-alist '(alpha 85 85))
```

From [Emacs SE](http://emacs.stackexchange.com/questions/5944/is-there-a-transparent-theme).

We could add a microstate that allows gradually adjusting the transparency.

**Comment by tuhdo** [comment]
This is not emergency. Just leave the issue there for future reference, in case someone is interested in working on it.

**Comment by tuhdo** [comment]
Oh amazing. Is it in the document yet?

**Comment by syl20bnr** [comment]
Only the key binding.

**Comment by CestDiego** [comment]
we could toggle transparency and let the microstate gradually adjust the value of it
