### ISSUE TITLE
evilified-state shadow some keybindings of major-modes (even after following Sec. "8.3 Evilified modes")

### ISSUE THREAD

**Issue by DrWaleedAYousef** [syl20bnr/spacemacs#15150]
#### Description :octocat:
evilified-state shadow some keybindings of major-modes (even after following Sec. "8.3 Evilified modes")

#### Reproduction guide :beetle:
- Start Emacs
Start gnus, which originally binds `j` to `gnus-group-jump-to-group`. Based on the documentation of spacemacs, Sec. 8.3, `j` should go to `shift-j`. However, this is not the case. `gnus-group-jump-to-group` is not bind now to anything.

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cac010555)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(dap c-c++ php systemd
     (latex :variables latex-build-command "LatexMk" latex-enable-auto-fill t latex-backend 'lsp latex-build-engine 'luatex latex-view-pdf-in-split-window t latex-enable-magic t latex-refresh-preview t latex-enable-folding t)
     (bibtex :variables bibtex-enable-ebib-support t ebib-preload-bib-files
             '("~/MyDocuments/Phd/texmf/bibtex/bib/base/publications.bib" "~/MyDocuments/Phd/texmf/bibtex/bib/base/booksIhave.bib")
             ebib-file-search-dirs
             '("~/MyDocuments/Phd/PDF/")
             ebib-import-directory
             '("~/Downloads/"))
     lua
     (html :variable css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t web-fmt-tool 'web-beautify html-enable-leex-support t)
     web-beautify prettier gnus
     (git :variables git-enable-magit-delta-plugin t git-enable-magit-gitflow-plugin t git-enable-magit-svn-plugin t)
     (yaml :variables yaml-enable-lsp t)
     (python :variables python-format-on-save t python-formatter 'yapf python-fill-column 99 python-backend 'lsp python-lsp-server 'pyright)
     (auto-completion :variables auto-completion-enable-help-tooltip t)
     better-defaults emacs-lisp
     (helm :variables helm-enable-auto-resize t helm-no-header t)
     (lsp :variables lsp-lens-enable t)
     (markdown :variables markdown-live-preview-engine 'vmd)
     (chrome :variables)
     multiple-cursors
     (org :variables org-enable-org-contacts-support t org-contacts-files
          '("~/.emacs.d.loadpath/Contacts-Imported.org")
          org-capture-templates
          '(("c" "Contacts" entry
             (file "~/Contacts-Imported.org")
             "* %(org-contacts-template-name))\n:PROPERTIES:\n:EMAIL: %(org-contacts-template-email)\n:END:")))
     (pdf :variables pdf-view-display-size 'fit-page)
     (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
     (spell-checking :variables spell-checking-enable-auto-dictionary t)
     syntax-checking version-control
     (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
Strange, I will try to have a look at this at the weekend.

**Comment by smile13241324** [comment]
The issue is caused by calling a wrong macro in the init code. This is happening for multiple layers so some more refactoring is in order.

**Comment by DrWaleedAYousef** [comment]
> The issue is caused by calling a wrong macro in the init code. This is happening for multiple layers so some more refactoring is in order.

I think there was an update last week that resolved the problem; right?

**Comment by smile13241324** [comment]
Yes the problem with this layer has been solved. Still a lot of other layers are using the wrong macro which could create more issues of that kind.
