### ISSUE TITLE
Evil mode transition takes time proportional to number of windows

### ISSUE THREAD

**Issue by jasoncyu** [syl20bnr/spacemacs#1516]
**Description**
There's a delay when changing evil modes because the cursor is updated in each window.

**Repro steps**
1. launch spacemacs on `master` or `develop`
2. open multiple windows
3. change into insert-mode from escape-mode with `i`

**expected result**
immediately go into insert mode

**actual result**
there's a delay before the mode changes. Durign that delay, my cursor flashes in each window, presumably b/c it's changing color between orange and green due to the mode change.

Here's a gif showing what's happening:
![evil_mode_change_lag_different_files](https://cloud.githubusercontent.com/assets/1874847/7819985/3994b944-039a-11e5-8bd9-cb468a31b8d2.gif)

This may be related, but expanding evil macros also takes longer when there are more windows. In the below gif, I'm expanding a macro that replaces `DOCUMENTATION` with `asdfasdf`. The expansion is kinda slow.
![evil_mode_lag](https://cloud.githubusercontent.com/assets/1874847/7819995/45b7fc2c-039a-11e5-926e-3181db6f5872.gif)

**Comment by syl20bnr** [comment]
How many windows do you have to create ? Are they window in the Emacs sense or are you talking about frames ?
I opened 9 windows in the same frame and pressing put me instantaneously in `insert state` with no blinking, my config:
- OS X 10.10
- GUI Emacs 24.4 homebrew on XQuartz

**Comment by jasoncyu** [comment]
Windows in the emacs sense. The lag is noticeable with two or more windows in a frame. I'm running
OSX 10.9.5 and the emacs `version` command tells me I'm running "GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org". I installed emacs from [emacsformacosx.com][emacsformacosx.com]

**Comment by jasoncyu** [comment]
I reinstalled emacs using homebrew, same problem. `version` tells me I'm running

` GNU Emacs  24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) `

**Comment by jasoncyu** [comment]
Ah, it's something to do with colorizing the cursor. When I set `dotspacemacs-colorize-cursor-according-to-state` to `nil`, I no longer experience any slowness. I'll look into why this is happening later, but this makes spacemacs usable w/ lots of windows

**Comment by syl20bnr** [comment]
Oh, makes me wonder if it would depend on the theme.

I noticed some poor performance with several themes like zenburn, maybe it
is related.

Le vendredi 29 mai 2015, Jason Yu <notifications@github.com> a écrit :

> Ah, it's something to do with colorizing the cursor. When I set
> dotspacemacs-colorize-cursor-according-to-state to nil, I no longer
> experience any slowness. I'll look into why this is happening later, but
> this makes spacemacs usable w/ lots of windows
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/1516#issuecomment-106893376>
> .
>


-- 
-syl20bnr-

**Comment by cmccloud** [comment]
I have the same issue.

**Comment by StreakyCobra** [comment]
Any news on this issue? I tried to reproduce it, but I didn't managed to. @cmccloud @jasoncyu What themes are you using? As @syl20bnr suggested, it may be related to this, so let's try :smiley:

**Comment by jasoncyu** [comment]
I get it on moe-theme-dark, spacemacs-dark, zenburn, wombat, etc. I cycled
through a lot of themes and I always get this slowdown. If someone could
explain where in the code cursor colorization is done, I could take a stab
at trying to figure out where the slowdown is happening.
ᐧ

JASON YU

LinkedIn <http://www.linkedin.com/pub/jason-yu/39/799/28b> | 734.646.8410

**Comment by nixmaniack** [comment]
@jasoncyu Mostly [here](https://github.com/syl20bnr/spacemacs/blob/2670d01a7836c6f8cd40ce0bc53346dd2108c595/layers/+distribution/spacemacs-base/packages.el#L153-L177)

**Comment by jasoncyu** [comment]
This issue is gone for me, closing.
