### ISSUE TITLE
symbol's value as variable is void: custom-theme-load-path while using spacemacs/dump-emacs

### ISSUE THREAD

**Issue by Jeff-avatar** [syl20bnr/spacemacs#15161]
When I use ```spacemacs/dump-emacs```, it failed because of "symbol's value as variable is void: custom-theme-load-path" in the *spacemacs-dumper* buffer

**Comment by smile13241324** [comment]
Please add your system specifications, to this ticket, instructions for doing so you should find in the new issue template.

I am sure someone will find the time to double check this feature.
