### ISSUE TITLE
Forge commands are missing from the magit status buffer

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#15162]
#### Description :octocat:

Forge commands aren't available under the documented shortcuts in a magit status buffer.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file in a git repo
- Press `SPC g s` to enter magit status
- Press `?` to see what commands are available

*Observed behaviour:* :eyes: :broken_heart:
None of the forge commands are listed under the shortcuts from the layer documentation nor do they work, e.g. `F p` to create a pull request.

(They used to be available behind a `@` prefix, but that's not the case any longer.)

*Expected behaviour:* :heart: :smile:
That the forge commands be available according to the layer documentation.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.60 (verified on 27.2 also)
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 99f07cbb3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash docker evil-commentary evil-snipe git github
 (helm :variables helm-no-header t)
 lsp mu4e multiple-cursors restclient
 (shell :variables shell-default-shell 'ansi-term)
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak)
 spacemacs-editing-visual spacemacs-visual
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking templates vinegar
 (xclipboard :variables xclipboard-enable-cliphist t)
 (c-c++ :variables c-c++-backend 'lsp-ccls)
 (clojure :variables clojure-enable-sayid t clojure-enable-clj-refactor t clojure-enable-linters 'clj-kondo clojure-backend 'cider)
 dhall emacs-lisp
 (go :variables go-backend 'lsp go-format-before-save t)
 (haskell :variables haskell-completion-backend 'lsp haskell-process-type 'cabal-repl)
 (python :variables python-formatter 'yapf)
 rust shell-scripts csv graphviz html json latex markdown
 (org :variables org-enable-reveal-js-support t org-enable-roam-support t)
 nixos spacemacs-org
 (sql :variables sql-auto-indent nil)
 pandoc terraform yaml direnv mt-misc org-marginalia projectile-extra roam-extra)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS GTK3 ZLIB

**Comment by John-Dawson-Camlin** [comment]
I also have the problem that the Magit status buffer is missing the Forge commands. In addition, the first time after opening Emacs I press `SPC g s` to open the Magit status buffer I receive the following message.
```
Cannot insert ("N" "Forge" forge-dispatch) into magit-dispatch; o not found
```
I am running Ubuntu 20.04 and installed Spacemacs thus.
```
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt update
sudo apt install emacs27
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```
In `~/.spacemacs` the layers are specified thus.
```
   ;; List of configuration layers to load.
   dotspacemacs-configuration-layers
   '(csv
     javascript
     (python :variables
             python-fill-column 72
             python-format-on-save t
             python-formatter 'black
             python-sort-imports-on-save t)
     rust
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press `SPC f e R' (Vim style) or
     ;; `M-m f e R' (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     ;; auto-completion
     ;; better-defaults
     emacs-lisp
     git
     github
     helm
     lsp
     ;; markdown
     multiple-cursors
     ;; org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     ;; syntax-checking
     ;; version-control
     treemacs)
```
`~/.gitconfig` is as follows.
```
[core]
	editor = emacs
[user]
	name = John Dawson
	email = <my_email>
[github]
	user = John-Dawson-Camlin
	oauth-token = <my_GitHub_personal_access_token>
```
`~/.authinfo` is as follows.
```
machine api.github.com login John-Dawson-Camlin^forge password <my_GitHub_personal_access_token>
```

**Comment by smile13241324** [comment]
I will have a look at the weekend, as far as I know those bindings should not have been removed.

**Comment by HanshenWang** [comment]
I believe this is breakage due to upstream Evil Collections. Who wants to spend their Friday without magit ;)?

**Comment by bitozoid** [comment]
I still see this message on startup:

```
Cannot insert ("N" "Forge" forge-dispatch) into magit-dispatch; o not found
```

**Comment by John-Dawson-Camlin** [comment]
@bitozoid, so do I.

**Comment by lebensterben** [comment]
make sure you've updated all packages

**Comment by smile13241324** [comment]
Thanks I'll have a look later

**Comment by smile13241324** [comment]
I have installed the same layers as you and I can indeed see this initial evil-collection warning, however this warning is only issued when the layers are freshly installed, when you restart with all layers installed the issue is gone and the keybindings are in place.

The warnings about auto evilification and forge-dispatch are normal and not related to this issue. They are caused by conflicting key bindings and should be solved in separate issues.
