### ISSUE TITLE
evil-collection requires a manual upgrade

### ISSUE THREAD

**Issue by creasyw** [syl20bnr/spacemacs#15179]
The commit https://github.com/syl20bnr/spacemacs/commit/dee70b8486ec8e11a3a620f7da359da79efe56b2 requires an updated version of `evil-collection` that contains the corresponding commit https://github.com/emacs-evil/evil-collection/commit/33461aa545bb722f575969339c2dfb97e7744647. Otherwise, the Spacemacs cannot be loaded or working correctly. I have the following error in my machine

```
Cannot open load file: No such file or directory .emacs.d/elpa/27.2/develop/evil-collection-20211028.1851/modes/forge/evil-collection-forge
```

I manually upgrade the package `evil-collection` in `list-packages` and resolve the issue, but I wonder if there is a way to automatically force the dependency to upgrade.

**Comment by lebensterben** [comment]
one should always update the packages.

**Comment by jaysharm** [comment]
Hey @creasyw How did you manually update?  I have this error, even after clicking 'Update Packages'.

In case it matters, I cannot use elpa directly, I've been using the github mirror here - https://github.com/d12frosted/elpa-mirror/

And then inserting these lines in .spacemacs after ``(defun dotspacemacs/init ()``

```
(setq configuration-layer-elpa-archives
      `(("melpa" . ,(concat user-home-directory ".elpa-mirror/melpa/"))
        ("org"   . ,(concat user-home-directory ".elpa-mirror/org/"))
        ("gnu"   . ,(concat user-home-directory ".elpa-mirror/gnu/"))))
```

**Comment by lebensterben** [comment]
@jaysharm this is unrelated to Spacemacs.
either wait for a few days until the mirror is updated or open issue in the mirror's repository.

**Comment by creasyw** [comment]
@lebensterben your reply is not helpful at all.

**Comment by lebensterben** [comment]
You've already figured out you need to upgrade the packages, so how is this a bug? If this is not a bug, why do you report it here?

My comment is just to summarize the solution to the error, which you've also found out independently.

As for the question whether there's a way to automatically update packages, the answer is no. But we accept PR.

**Comment by tveyben** [comment]
I came here for the same reason as the OP.
Being new to spacemacs I was not aware (or I forgot it after having read a gazillion pages of docs?) that the packages needed to be updated manually whenever needed (like in this case).

It's clearly described how to do so in the dev docs here: https://develop.spacemacs.org/doc/DOCUMENTATION.html#update-packages so I'm posting this note to help others (or the future myself :-)

https://xkcd.com/979/
