### ISSUE TITLE
 An error occurred while installing helm-gitignore (error: (error Package ‘gitignore-mode-1.1.0’ is unavailable))

### ISSUE THREAD

**Issue by llllbarcodellllllllll** [syl20bnr/spacemacs#15170]
#### Description :octocat:
      An error occurred while installing helm-gitignore (error: (error Package ‘gitignore-mode-1.1.0’ is unavailable))

#### Reproduction guide :beetle:
- Start Emacs
Start emacs as usual

*Observed behaviour:* :eyes: :broken_heart:
At start Emacs check udpates but on step 2/4 it report about error 

*Expected behaviour:* :heart: :smile:

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4f7246da0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(nginx yaml html csv emacs-lisp git helm lsp docker django multiple-cursors
       (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
       (org :variables org-agenda-include-diary t org-enable-notifications t org-start-notification-daemon-on-startup t org-enable-org-brain-support t org-image-actual-width nil org-default-notes-file "~/org/notes_mobile.org")
       (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom)
       (syntax-checking :variables syntax-checking-auto-hide-tooltips 3 syntax-checking-enable-tooltips nil)
       treemacs templates
       (python :variables python-backend 'lsp python-fill-column 79 python-test-runner 'pytest python-formatter 'yapf)
       (osx :variables osx-command-as 'hyper osx-option-as 'meta osx-control-as 'control osx-function-as nil osx-right-command-as 'left osx-right-option-as 'left osx-right-control-as 'left osx-swap-option-and-command nil)
       (sql :variables sql-capitalize-keywords t sql-backend 'lsp lsp-sqls-workspace-config-path nil))
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Update your Spacemacs first

**Comment by smile13241324** [comment]
This package has been removed some days ago please upgrade your git repo and retry.
