### ISSUE TITLE
[github] Gist package removed from layer

### ISSUE THREAD

**Issue by practicalli-john** [syl20bnr/spacemacs#15183]
#### Description :octocat:
GitHib gist bindings are no longer present and it seems gist package has been removed from the GitHub layer.

Adding `gist.el` to dotspacemacs-additional-packages` works as normal, so it seem unclear why the gist.el package was removed from the layer.

#### Reproduction guide :beetle:
- [Configure a token as described in the Spacemacs GitHub layer documentation](https://develop.spacemacs.org/layers/+source-control/github/README.html#git-configuration)
- Start Emacs
- `SPC f e d` to edit the .spacemacs configuration
- Add `github` as a layer
- `SPC q r` to restart Spacemacs and load the packages for the GitHub layer

*Observed behaviour:* :eyes: :broken_heart:
`SPC g g` is no longer a key binding

`SPC SPC gist` shows no matching results in helm popup

*Expected behaviour:* :heart: :smile:
`SPC g g` will create a GitHub Gist from the current buffer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 050221ee3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 (clojure :variables cider-repl-display-help-banner nil cider-pprint-fn 'fipp clojure-indent-style 'align-arguments clojure-align-forms-automatically t clojure-toplevel-inside-comment-form t cider-overlays-use-font-lock t cider-repl-buffer-size-limit 100)
 colors command-log csv emacs-lisp emoji
 (git :variables git-magit-status-fullscreen t magit-diff-refine-hunk t git-enable-magit-todos-plugin t)
 github graphviz
 (helm :variables helm-follow-mode-persistent t)
 html javascript
 (json :variables js-indent-level 2 json-backend 'lsp)
 (lsp :variables lsp-enable-on-type-formatting t lsp-enable-indentation t lsp-enable-snippet t lsp-enable-symbol-highlighting t lsp-modeline-diagnostics-enable t lsp-modeline-diagnostics-scope ':workspace lsp-ui-doc-enable nil lsp-ui-doc-show-with-cursor nil lsp-ui-doc-show-with-mouse nil lsp-ui-doc-delay 99999 lsp-ui-doc-include-signature t lsp-ui-sideline-enable nil lsp-ui-sideline-show-code-actions nil lsp-lens-enable t treemacs-space-between-root-nodes nil lsp-file-watch-threshold 10000 lsp-log-io nil)
 (markdown :variables markdown-live-preview-engine 'vmd)
 multiple-cursors
 (org :variables org-enable-github-support t org-enable-bootstrap-support t org-enable-reveal-js-support t org-want-todo-bindings t org-enable-org-journal-support t org-journal-dir "~/projects/journal/" org-journal-file-format "%Y-%m-%d" org-journal-date-prefix "#+TITLE: " org-journal-date-format "%A, %B %d %Y" org-journal-time-prefix "* " org-journal-time-format "" org-journal-carryover-items "TODO=\"TODO\"|TODO=\"DOING\"|TODO=\"BLOCKED\"|TODO=\"REVIEW\"" org-enable-jira-support t jiralib-url "https://statsbomb.atlassian.net:443")
 (ranger :variables ranger-show-preview t ranger-show-hidden t ranger-cleanup-eagerly t ranger-cleanup-on-disable t ranger-ignored-extensions
         '("mkv" "flv" "iso" "mp4"))
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak)
 (spacemacs-modeline :variables doom-modeline-height 12 doom-modeline-major-mode-color-icon t doom-modeline-buffer-file-name-style 'relative-to-project doom-modeline-display-default-persp-name t doom-modeline-minor-modes nil doom-modeline-modal-icon nil)
 spell-checking
 (syntax-checking :variables syntax-checking-use-original-bitmaps t)
 (treemacs :variables treemacs-indentation 1 treemacs-use-git-mode 'simple)
 theming
 (unicode-fonts :variables unicode-fonts-enable-ligatures t unicode-fonts-ligature-modes
                '(prog-mode))
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
```

**Comment by arifer612** [comment]
It's mentioned in #15098 that the package was removed because it's not being
maintained any longer.

**Comment by arifer612** [comment]
Some of your changes to the documentation can be used to close #15377. I would
recommend you can make use of your work to settle an active issue.

**Comment by practicalli-john** [comment]
> Some of your changes to the documentation can be used to close #15377. I would recommend that you make use of your work to settle an active issue :)

@arifer612 Created https://github.com/syl20bnr/spacemacs/pull/15381 as suggested.
