### ISSUE TITLE
Congratulations on writing the most unclear installation instructions I have ever read

### ISSUE THREAD

**Issue by jaimejim** [syl20bnr/spacemacs#15182]
If you are posting about a *bug* please close this issue and open a new one from within Spacemacs using:
- `SPC h I`
- `M-m h I`

(I = capital i)

If the bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template).

A few optional steps that might help:
- Update `emacs` to latest stable release.
- [Update](https://github.com/syl20bnr/spacemacs#update) `spacemacs`.
- Update all emacs packages. 
  -`M-x configuration-layer/update-packages`. When seeing the prompt, type `y` and then restart emacs with `SPC q r`.
- ~~If you are on Windows, try to restart.~~
  
You can delete this message to start typing.

**Comment by lebensterben** [comment]
We solves computer bugs but not stupidity.

**Comment by smile13241324** [comment]
Sorry but this is open source so if you don't like it go somewhere else.

If you have constructive feedback or want to improve this project go ahead.

But this issue is obviously not ment seriously and will therefore be closed.
