### ISSUE TITLE
`(configuration-layer/update-packages t)` does not update packages

### ISSUE THREAD

**Issue by atreyasha** [syl20bnr/spacemacs#15186]
#### Description :octocat:

When evaluating `(configuration-layer/update-packages t)`, `nil` is returned and packages are not updated after restarting `emacs`. This issue does not occur when evaluating `(configuration-layer/update-packages)` interactively.

I started observing this issue in the last weeks and suspect that commit cac0105553bf3c924a5247f45ecf91a114ddd46f might be related.

#### Reproduction guide :beetle:

- Start `emacs`
- Evaluate `(configuration-layer/update-packages t)` (assuming upstream updates exist, if not simulate them by downgrading one or more packages)
- Restart `emacs`

*Observed behaviour:* :eyes: :broken_heart:

`nil` is returned and no packages are updated on restart

*Expected behaviour:* :heart: :smile:

Packages should be updated on restart

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. 050221ee3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(org bibtex ruby html yaml helm emacs-lisp semantic themes-megapack
     (auto-completion :variables auto-completion-idle-delay nil)
     (markdown :variables markdown-live-preview-engine 'vmd)
     (ess :variables ess-use-flymake nil ess-indent-with-fancy-comments nil ess-eval-visibly 'nowait)
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t)
     (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
     (latex-plus :location local :variables latex-enable-magic nil latex-build-command "LatexMk")
     (elpy-plus :location local :variables python-shell-interpreter "ipython" python-shell-interpreter-args "-i --simple-prompt" elpy-shell-echo-output nil elpy-rpc-virtualenv-path "~/.spacemacs.d/rpc/elpy/rpc-venv"))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
@dalanicolai any idea?
