### ISSUE TITLE
Running Emacs as server, .spacemacs config does not apply

### ISSUE THREAD

**Issue by r-vd-woude** [syl20bnr/spacemacs#15181]
#### Description :octocat:
.spacemacs config not loaded when running as systemd daemon

#### Reproduction guide :beetle:
-Change defaults in .spacemacs. For instance font type or size, default theme etc.
-Run Emacs as a systemd daemon
-Connect as a client to the daemon

*Observed behaviour:* :eyes: :broken_heart:
No changes made to .spacemacs will be applied.

*Expected behaviour:* :heart: :smile:
Expected the font and theme changes to apply.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 050221ee3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(shell-scripts auto-completion emacs-lisp ess
               (ess :variables ess-r-backend 'lsp)
               helm lsp markdown multiple-cursors spell-checking syntax-checking treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

I'm pretty new to emacs and spacemacs. So I probably made an error somewhere. However, I see other GitHub issues with the same problem: https://github.com/syl20bnr/spacemacs/issues/8275.

Anyways, thanks to this awesome distribution, it made me finally switch to Emacs!

Little edit:

When I apply the config after I started the terminal it works as expected. It also works when running in standalone mode.

```

**Comment by lebensterben** [comment]
when you edit .spacemacs, is the daemon running?

**Comment by Moonl1ghter** [comment]
> when you edit .spacemacs, is the daemon running?

Not always, but this issue is consistent across reboots. So when I shut down the daemon, edit the file, restart the daemon the same issue applies. 

From what I gathered it is because the config is only applied to the first frame loaded, and since that first frame is the dameon, it won't have an effect. I'm just no sure how I can make it a global config. Searched the docs as well.

**Comment by ccruquan** [comment]
which mode does emacs service run?  system or user?
try enable emacs service in user mode
``` sh
systemctl enable emacs.service --user
```
