### ISSUE TITLE
Add consult-lsp to compleseus layer

### ISSUE THREAD

**Issue by kdoomsday** [syl20bnr/spacemacs#15197]
Feature request. I would like to add consult-lsp to the compleseus layer to get improved find-symbols and similar behavior.

**Comment by lebensterben** [comment]
https://github.com/gagbo/consult-lsp

This can be easily added since there's not much to configure.

**Comment by kdoomsday** [comment]
If I directly modify the layer, adding the consult-lsp package I can do something like this and get it to work:
`(defun compleseus/init-consult-lsp ()
  (use-package consult-lsp
    :defer t
    :init
    (spacemacs/set-leader-keys "os" 'consult-lsp-file-symbols)
    (spacemacs/set-leader-keys "oS" 'consult-lsp-symbols)
    (spacemacs/set-leader-keys "od" 'consult-lsp-diagnostics)
    ))
`

The additional keybindings are because the usual lsp actions to peek workspace symbols and similar do not work for me directly. It was necessary to call these ones, but these ones worked. I do not know how to get it to work with the existing framework.

**Comment by lebensterben** [comment]
You would also need to modify lsp layer, which defined three peek/jump styles: simple, lsp-based, and both.
