### ISSUE TITLE
Apply Ansi colors to "compilation-mode" derived modes

### ISSUE THREAD

**Issue by rinconjc** [syl20bnr/spacemacs#15198]
#### Description :octocat:
The output generated from running `dap-java-run-test-class` prints the ansi-colors as escaped chars, instead of applying the colors to the output.

The Spacemacs process hook `spacemacs-visual//compilation-buffer-apply-ansi-colors` is already bound by default when running the above function, but unfortunately it does work. The reason is that the above function runs for `compilation-mode` major modes only, and the dap-java uses a mode (`dap-server-log-mode`) derived from `compilation-mode`

#### Reproduction guide :beetle:
- Start Emacs
- Enable java and lsp layers
- Create a sample maven java projects
- Create sample Java test class
- Execute the test class with `dap-java-run-test-class`
- Notice the ansi colors escaped chars in the output buffer

*Observed behaviour:* :eyes: :broken_heart:
- Notice the ansi colors escaped chars in the output buffer

*Expected behaviour:* :heart: :smile:
- Ansi-color codes should be interpreted as colors, so for instance, instead of printing `^[[36m` it should display the subsequent text in `Cyan`.

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1a4912e51)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust go html javascript yaml python java auto-completion better-defaults emacs-lisp git helm lsp dap markdown multiple-cursors org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking treemacs)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
```

**Comment by smile13241324** [comment]
Same applies to the maven compile mode.
PRs are welcome.

**Comment by cwjnkins** [comment]
Is the package `parent-mode` a dependency of Spacemacs (or is `parent-mode-list` defined somewhere else)? I have recently upgraded Spacemacs (to this commit: 651a7a9f; my Emacs version is 27.1), and whenever I invoke `compile` (or similar functions) I receive an error saying this function is not defined.

**Comment by lebensterben** [comment]
@cwjnkins thanks for reporting.
Indeed, there's no `parent-mode-list`.
To get the parent mode(s) of `mode`, one should use `(get mode 'derived-mode-parent)`.

Can you try to replace `(parent-mode-list major-mode)` with `(get majr-mode 'derived-mode-parent)`?.

**Comment by cwjnkins** [comment]
@lebensterben (I assume you mean `major-mode`, not `majr-mode`)

Yes, that does the trick!

**Comment by lebensterben** [comment]
@cwjnkins 
great.
If you want you can make a PR to fix this. (I'm away from computer now)

**Comment by rinconjc** [comment]
I think this is broken again:
```elisp
(when (memq 'compilation-mode (get major-mode 'derived-mode-parent)
```
The above will fail because `memq` expects a list in the second argument, whereas the `(get major-mode ...)` returns a symbol

**Comment by lebensterben** [comment]
@rinconjc 
I just merged your new PR. Thanks.
