### ISSUE TITLE
[coq layer] Company-coq not getting setup

### ISSUE THREAD

**Issue by YaZko** [syl20bnr/spacemacs#15193]
#### Description :octocat:
Although the `coq` layer seems to provide everything to support both the PG and the company-coq plugins, only the former seems to get installed/setup. I can't quite figure out why and how to get company-coq to work as well.

#### Reproduction guide :beetle:
- Start Emacs
- Add `coq` to the `dotspacemacs-configuration-layers` in your `.spacemacs`
- Open a `.v` file. 

*Observed behaviour:* :eyes: :broken_heart:
ProofGeneral gets installed as expected, its associated keybindings are available in a `.v` file. However CompanyCoq does _not_ get installed, its associated keybindings are not available in a `.v` file.
Instrumenting the layer with `print` statements confirms that `coq/init-proof-general` gets run, but _not_ `coq/init-company-coq`.

*Expected behaviour:* :heart: :smile:
`coq/init-company-coq` is expected to be run, and hence `company-coq` available when using the `coq` layer.

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 17b5646e7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm coq multiple-cursors treemacs)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
```

Best,
Yannick

**Comment by lebensterben** [comment]
you need auto-completion layer

**Comment by YaZko** [comment]
Arg, it was just that easy, thanks a lot!

Out of curiosity and for the future, how could I have inferred this? There is no explicit reference to this layer in the layer for coq.

**Comment by lebensterben** [comment]
Why not to read source code?

**Comment by mohanr** [comment]
The auto-completion layer is on. But M-x package-install doesn't show the option. coq layer is working though.

**Comment by radrow** [comment]
I have the same problem with `auto-completion` included. It seems like `coq/init-company-coq` was never executed. I had to manually add `company-coq` to `dotspacemacs-additional-packages`.

**Comment by radrow** [comment]
Also, none of the `SPC m` key chords work. Almost fresh config with hybrid style. I looked at the layer code, but I don't get what could be wrong :(

**Comment by radrow** [comment]
I had a similar problem (`coq` and `auto-completion` layers on) and somehow it would not initialize company or even set keybinds. Cleared all cache I could think of, reinstalled coq and coq-lsp (even though it's not used?), rebooted PC and it magically worked.
