### ISSUE TITLE
projectile-helm-find-file crashes very easily

### ISSUE THREAD

**Issue by andyque** [syl20bnr/spacemacs#1519]
When use spacemacs with a large code base, the `projectile-helm-find-file` will cause emacs crash very easily when fine tune the file names, especially when use backspace key(or delete key on Mac).

I change to helm-ls-git, the problem still exists, but it is better than the `projectile-helm-find-file`.

**Comment by tuhdo** [comment]
I guess you are using OS X and Emacs 24.4? If so, have a look at this issue: https://github.com/bbatsov/projectile/issues/600. It is a bug in Emacs for Mac OS X 24.4 that crashes Emacs frequently when using Helm. The solution is using `emacs-mac-port` or upgrade to Emacs 24.5.

**Comment by tuhdo** [comment]
And how large is large? When I was using OS X, Helm Projectile works fine on project the size of Linux kernel or more (i.e. 40-50k files). You should really upgrade Emacs.

**Comment by andyque** [comment]
@tuhdo  Yes, I'm using OS X and Emacs 24.4.  Thanks, I will change to Emacs 24.5.

**Comment by andyque** [comment]
@tuhdo  The project is about 40-50k files.

**Comment by tuhdo** [comment]
If so, you should not have any problem. Helm can handle up to 250k files fine (and more but I only tested up to this).

**Comment by andyque** [comment]
Thanks very much  @tuhdo 
It seems solved. :+1:
