### ISSUE TITLE
Modeline Too Big

### ISSUE THREAD

**Issue by Seanld** [syl20bnr/spacemacs#15203]
Spacemacs while loading
![Spacemacs loading](https://user-images.githubusercontent.com/9366109/145614175-42f9b446-bb3d-4247-8179-dd4bb6543569.png)
Spacemacs when loaded
![Spacemacs loaded](https://user-images.githubusercontent.com/9366109/145614198-25f7e20a-b829-4008-bb88-c16ee4806814.png)

I've been having issues with my modeline (fonts were rendering weirdly), which was fixed by installing different fonts and adjusting the fallback preferences for the Unicode fonts layer. The circled window number, and circled minor mode labels now render properly.

After fixing that issue, the modeline now renders too tall, and leaves too much empty space. It was originally also rendering the separators too small, which I fixed by doing:

```elisp
   dotspacemacs-mode-line-theme '(spacemacs :separator curve :separator-scale 2)
```

The only thing I found to adjust the modeline height is the variable `powerline-height` but adjusting that both with the customize menu, and by setting it in `spacemacs/user-init` affects nothing.

Anyways, how can I force the modeline to be shorter?

**Comment by HanshenWang** [comment]
``` emacs-lisp
(setq powerline-scale 0.50)
```
Works for me. That said, grepping my way around `.emacs.d` shows either `powerline-scale` or `separator-scale` ought to work.

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+spacemacs/spacemacs-modeline/packages.el#L120

**Comment by lebensterben** [comment]
Easy solution is not to use default theme or any theme that relies on spaceline...
