### ISSUE TITLE
New face `mode-line-active` with variable pitch in emacs git/29.1

### ISSUE THREAD

**Issue by real-or-random** [syl20bnr/spacemacs#15206]
With the current emacs 29.1 (unreleased), the font in the mode-line is not monospace anymore:
![image](https://user-images.githubusercontent.com/1071625/146050530-2c0b8623-ba08-4166-8178-c5d095ceaecf.png)

This is due to a recent addition of a face `mode-line-active` which inherits from `variable-pitch`. I could describe the issue in more detail but the friends at doom have a great bug report: https://github.com/doomemacs/themes/issues/689

I'm not an expert enough to judge whether this is the right repo to report this but I feel this deserves some attention. Maybe this should be fixed in (all?) themes. But I can imagine that some workaround in spacemacs could be helpful because this will affect a lot of themes until they've all been fixed.

**Comment by lebensterben** [comment]
it looks like you're using spaceline. you can report there.

**Comment by real-or-random** [comment]
"Moved" this issue to https://github.com/TheBB/spaceline/issues/230. Please re-open here if you want to track it here.

For anyone finding this issue, let me note that a working workaround is to add this to the user config: 
```
(set-face-attribute 'mode-line-active nil :inherit 'mode-line)
```
