### ISSUE TITLE
Update packages doesn't finish. "Function is void read-answer".

### ISSUE THREAD

**Issue by Atrus7** [syl20bnr/spacemacs#15212]
#### Description :octocat:
Update packages broken, Function is void read-answer.

My Emacs (26) doesn't have that function
Breaking on Line 2164 in ~/.emacs.d/core/core-configuration-layer.el

#### Reproduction guide :beetle:
- Start Emacs
- <SPC> f e U to update packages

*Observed behaviour:* :eyes: :broken_heart:
Doesn't update. Error Message is `Function is void: read-answer`

*Expected behaviour:* :heart: :smile:
Updates packages.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: nil (rev. 387d16545)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
 helm git
 (org :variables org-want-todo-bindings t)
 (deft :variables deft-zetteldeft t)
 (shell :variables shell-default-shell 'shell)
 spell-checking version-control
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 common-lisp emacs-lisp haskell html javascript swift markdown csv
 (spell-checking :variables spell-checking-enable-by-default nil)
 python scheme vimscript yaml dash erc graphviz ibuffer semantic cf-home syntax-checking util-funcs cf-cc cf-calendar cf-desktop cf-irc cf-ide cf-linux cf-lisp cf-mac cf-opinions cf-org cf-scheme cf-ssh cf-writing)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 THREADS LIBSYSTEMD LCMS2

My workaround was to avoid the confirmation with a prefix, but this isn't ideal. 

I think this is breaker:
cac010555 * Add option to select packages for update

**Comment by Atrus7** [comment]
@dalanicolai hey, could you take a look. Not 100% sure if emacs 26 is supported, (first time submitting) but if it is, I think this will break others too.

**Comment by lebensterben** [comment]
I suggest to remove this feature entirely.
For a target user of maybe a few people, we've spent too much time on debugging.

**Comment by dalanicolai** [comment]
@atrus Sorry, I don't understand where you'd like me to take a look, what you mean with first time submitting, and what do you mean with breaking others too.

Indeed, I find that the `read-answer` probably was introduced in Emacs 26.2. I think this could quickly get fixed by providing the read-answer option only to Emacs versions > 26.1. (I hope you don't need the selective update, that would be a little much to fix for such an old Emacs)

@lebensterben I did hardly debug anything here. I think if it works fine, for Emacs > 26.1, then we could just keep it. I guess it wouldn't be too much work to restrict the functionality to Emacs > 26.1. I will have a look as soon as @Atrus7  clarifies what he means.

**Comment by Atrus7** [comment]
Oh, sorry let me clarify @dalanicolai . 

- by "take a look" I meant generally could you take a look at the bug.
- by "first time submitting" I meant it's my first time submitting a bug to spacemacs. 
- by "breaking others" I just meant other people with emacs <= 26.1. 

I don't need selective update feature. Restricting it to emacs >26.1 is fine from my user perspective.

**Comment by dalanicolai** [comment]
@atrus Thanks for the clarification. So I have had a look and created a PR (#15215). As I have no old emacs version installed I could not test it, but maybe you could manually copy paste the code from the diff [here](https://github.com/syl20bnr/spacemacs/pull/15215/files) and approve the PR if it make things work correctly.

Let me know if you have questions (for that I would recommend the Spacemacs Gitter, but here is okay too)

**Comment by Atrus7** [comment]
Worked for me. Approved from a test-perspective.  I'm not familiar with code-review standards for spacemacs to really vouch one way or another. Thanks for the fix!

**Comment by dalanicolai** [comment]
Okay great! Thanks for reporting the issue...

**Comment by lebensterben** [comment]
Since emacs 27.1 has just landed in Debian stable, I will soon upgrade the minimum emacs version to 27.1.
Unfortunately that means the said PR will be effectively reverted.
