### ISSUE TITLE
Tide does not start in typescript file

### ISSUE THREAD

**Issue by Rimann91** [syl20bnr/spacemacs#15217]
I am running spacemacs on windows. I have followed the instructions [here ](https://develop.spacemacs.org/layers/+tools/tide/README.html) verbatim. I am new to emacs, there doesn't seem to be any output at all associated with tide.  I don't know if there is a way to get verbose output that I don't know about?. No log buffers open. Any ideas what the issue might be?

**Comment by lebensterben** [comment]
Use SPC h I to generate the information needed for bug reports.

**Comment by lawrsp** [comment]
I also met this， error message is
```
File local-variables error: (void-variable tide-references-mode-map)
```
