### ISSUE TITLE
Add caps-lock package and add a toggle for it

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1521]
`caps-lock` is a minor mode that when enabled, it behaves like you turned on `Caps Lock`. The package is here: http://elpa.gnu.org/packages/caps-lock.html

However, currently we cannot download packages from ELPA. However, given how small it is (only 23 lines of actual code) we can just include the file directly inside Spacemacs.

**Comment by tuhdo** [comment]
Why is it needed? Because many Emacs users (and even Vim) swapped `Caps Lock` for something Ctrl or Esc, and the pressing `Cap Locks` is less convenient. More importantly, in Emacs when you enable Caps Lock, it appends every key pressed with `Shift`. For example, with Caps Lock on, when you press `C-a` it becomes `C-S-a` and thus making many commands not usable. This minor mode solved that problem.

**Comment by syl20bnr** [comment]
It can be included as an extension, but I'm surprised that we cannot download any package from ELPA, the repository is not present in spacemacs ?

**Comment by tuhdo** [comment]
Yes, I have to add `caps-lock` package to `dotspacemacs-additional-packages` otherwise adding to my private layer package list won't download the package. Seems like a bug.

**Comment by syl20bnr** [comment]
wow that's strange, when you added it to your layer, are you sure you added an associated init function ?

**Comment by tuhdo** [comment]
Ah it turned out that I made a typo in my init function.

**Comment by syl20bnr** [comment]
I think that spacemacs should warn in the Messages buffer when it does not find any `init` function.

**Comment by TheBB** [comment]
@tuhdo Since it seems you have the code already, please make a PR for this or close this issue.
