### ISSUE TITLE
~/.emacs.d/tutorial is generated by M-x help-with-tutorial (C-h t), but spacemacs is not aware of it

### ISSUE THREAD

**Issue by breadncup** [syl20bnr/spacemacs#15218]
#### Description :octocat:
`~/.emacs.d/tutorial` is generated by "C-h t", and it should not be tracked by the `git status` in spacemacs

#### Reproduction guide :beetle:
- Start Emacs
- M-x help-with-tutorial (`C-h t`)
- `C-x k` to kill the TUTORIAL buffer, and it asks whether you save the tutorial
- When you say, "yes", it stores the information at `~/.emacs.d/tutorial`

*Observed behaviour:* :eyes: :broken_heart:
The directory of `~/.emacs/tutorial` is generated, but it is not managed spacemacs.

*Expected behaviour:* :heart: :smile:
When I do `git status` in `~/.emacs.d`, it should show clean status.

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5bcedd191)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: RSVG IMAGEMAGICK DBUS GLIB NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM MODULES THREADS JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
N/A

**Comment by lebensterben** [comment]
You made the conscious decision to save the file. So how's this a bug?

**Comment by breadncup** [comment]
It's not a bug. It would be an enhancement request?

**Comment by lebensterben** [comment]
See https://github.com/emacs-mirror/emacs/blob/3af9e84ff59811734dcbb5d55e04e1fdb7051e77/lisp/tutorial.el#L679

**Comment by breadncup** [comment]
Thank you! It gave me the hint to change the tutorial directory by overriding function, `#'tutorial--saved-dir`
