### ISSUE TITLE
Racket layer show error lines in REPL

### ISSUE THREAD

**Issue by sinistersnare** [syl20bnr/spacemacs#15227]
Hi, I am using Spacemacs for my Racket editing and it is generally amazing. However, when I get a runtime error while running code in the REPL, it does not offer any line numbers or anything to help debug outside of the error message itself.

In DrRacket it would highlight the lines of code in the editor. That would probably be too much, but is the line-info there somewhere that can be printed?

If there is somewhere else to post this issue let me know, thanks!

**Comment by lebensterben** [comment]
Please try one of LSP implementation for Racket. See https://emacs-lsp.github.io/lsp-mode/page/languages/
It might have the feature your requested.

**Comment by sinistersnare** [comment]
I think with what I have installed there is some way to make things more explicit. Here is an example error trace (given a match with no possible branch)

```
; match: no matching clause for 5
; /home/sinistersnare/code/aams/src/racket/dybvig07/cekm.rkt:144:5
; Context (plain; to see better errortrace context, re-run with C-u prefix):
;   /usr/share/racket/collects/racket/match/runtime.rkt:24:0 body of "/home/sinistersnare/code/aams/src/racket/dybvig07/cekm.rkt"
```

The key here is the "Context (plain; to see better errortrace context, re-run with C-u prefix):"

This is after typing some code in the REPL that causes this error. So I am not sure how to re-execute the REPL with C-u prefix.

**Comment by sinistersnare** [comment]
I think my issue is with the Racket mode itself, I will close this. Thanks!
