### ISSUE TITLE
ebuild-mode gives out errors about lsp languageId

### ISSUE THREAD

**Issue by epsilon-0** [syl20bnr/spacemacs#15226]
#### Description :octocat:
Opening a gentoo ebuild gives out errors in an lsp-mode pane:
```
Warning (lsp-mode): Unable to calculate the languageId for buffer ‘rte_kni-kmod-21.11.ebuild’. Take a look at ‘lsp-language-id-configuration’. The ‘major-mode’ is ebuild-mode
```

#### Reproduction guide :beetle:
- Start Emacs.
- Open any gentoo ebuild.

*Observed behaviour:* :eyes: :broken_heart:
A split pane opens with hundreds of lines of the above error message.

*Expected behaviour:* :heart: :smile:
Everything should be fine, there should not be any error messages.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. beb173abf)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lsp ansible cscope emacs-lisp major-modes html java javascript yaml
     (shell-scripts :variables shell-enable-smart-eshell t)
     (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-enable-clang-support t)
     (python :variables python-lsp-server 'pyright python-formatter 'yapf python-enable-yapf-format-on-save t python-sort-imports-on-save t)
     git markdown version-control auto-completion better-defaults helm spell-checking syntax-checking
     (treemacs :variables treemacs-use-git-mode 'deferred treemacs-use-collapsed-directories 3))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND GPM DBUS GLIB NOTIFY INOTIFY ACL GNUTLS ZLIB GTK3 X11 XDBE XIM THREADS PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
N/A

**Comment by lebensterben** [comment]
Looks like this is already fixed by you in upstream.
Thanks.
