### ISSUE TITLE
Required package ‘org-plus-contrib-9.0.0’ is unavailable

### ISSUE THREAD

**Issue by Atemu** [syl20bnr/spacemacs#15225]
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>

Whenever I open Spacemacs develop, I get the following message:

```
Package refresh done
(Spacemacs) --> installing dependency: org-plus-contrib... [1/1]
Unable to activate package ‘org-category-capture’.
Required package ‘org-plus-contrib-9.0.0’ is unavailable
Unable to activate package ‘org-projectile’.
Required package ‘org-category-capture-0.0.0’ is unavailable
Spacemacs is ready.
```

#### Reproduction guide :beetle:
- Start Emacs

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5bcedd191)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(c-c++ debug docker emacs-lisp git groovy haskell
       (ibuffer :variables ibuffer-group-buffers-by 'projects)
       (ivy)
       (javascript)
       kotlin latex markdown multiple-cursors nixos org pdf python ranger rust
       (shell :variables shell-default-shell 'shell shell-default-term-shell "~/.nix-profile/bin/bash")
       (solidity :variables solidity-flycheck-solc-checker-active nil)
       systemd theming treemacs
       (version-control :variables version-control-diff-tool 'git-gutter)
       yaml)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by emacs18** [comment]
org-plus-contrib no longer exist.  It is not mentioned anywhere within spacemacs. Instead org package is installed separately from org-contrib package.  My guess is that your init file is referring to obsolete org-plus-contrib.  Please update your setup file.

**Comment by winsphinx** [comment]
I met the same, and i tried rm org-* packages, then reinstall them.
I dont know why, but now it works correctly.

**Comment by lebensterben** [comment]
This should be fixed in upstream. Update Spacemcas and optionally remove org-* packages.
Reopen if needed.
