### ISSUE TITLE
Inserting markdown breaks unicode bullets

### ISSUE THREAD

**Issue by bobf32** [syl20bnr/spacemacs#15224]
#### Description :octocat:
Inserting markdown code with BEGIN_SRC breaks unicode bullets.

#### Reproduction guide :beetle:
- Start Emacs
- Create org-mode file with contents:
```
* H1
* H2
** H2.1
*** H2.1.1
#+BEGIN_SRC markdown
# This here is markdown
#+END_SRC
*H3
```

- Revert buffer

*Observed behaviour:* :eyes: :broken_heart:
The bullet points for all H2 headings and down show as asterisks, where H1 and H3 remain in their unicode form.

Changing the token following BEGIN_SRC from markdown to anything else and reverting leads to the bullets regaining their unicode form.

*Expected behaviour:* :heart: :smile:
All heading bullets should show in unicode form.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5bcedd191)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql python vimscript javascript html asciidoc markdown helm emacs-lisp git markdown org xkcd)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM MODULES THREADS PDUMPER GMP

#### Backtrace :paw_prints:
```
```

**Comment by lebensterben** [comment]
Confirmed.
But I recommend to turn off org-superstar at all time as it has no practical use at all.

**Comment by bobf32** [comment]
Thanks @lebensterben - I can do that now I know what it's called :)
