### ISSUE TITLE
global-display-line-numbers-mode not functioning correctly under spacemacs

### ISSUE THREAD

**Issue by yth** [syl20bnr/spacemacs#15231]
#### Description :octocat:
global-display-line-numbers-mode not functioning correctly under spacemacs

#### Reproduction guide :beetle:
- Start Emacs
- Open ~/.spacemacs
- Add "(global-display-line-numbers-mode)" to the body of dotspacemacs/user-config

*Observed behaviour:* :eyes: :broken_heart:
No apparent change

*Expected behaviour:* :heart: :smile:
Display line numbers next to text after opening a file

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 1bd542836)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
Unable to provide any
```

**Comment by dalanicolai** [comment]
Thanks for the report. However, from the docstring of `line-number-mode` you can find that this mode makes Emacs show line-numbers in the mode-line. But Spacemacs shows them in the mode-line (at the right) already by default.

As you write that you expect line-numbers next to text, I assume you are looking for the `dotspacemacs-line-numbers` variable that you can find (e.g. using `SPC s s`) in your dotfile.

I guess you could find some info on google also about it, e.g. try `line numbers Spacemacs`. Please try google/duckduckgo before opening an issue here. Also there is the [Spacemacs gitter](https://gitter.im/syl20bnr/spacemacs/) for questions, with often quick answers.

**Comment by lebensterben** [comment]
Mare sure you have set `dotspacemacs-line-numbers` to `t` and then the `global-display-line-numbers-mode` should be enabled automatically.

And please provide more details on what went wrong because it's unclear to me.
