### ISSUE TITLE
[org] pls consider roll back 67b3c44fd2d56c838b2cd486a6b974bc7a5fb98a

### ISSUE THREAD

**Issue by wztdream** [syl20bnr/spacemacs#15234]
#### Description :octocat:
Please consider roll back [pr 15008](https://github.com/syl20bnr/spacemacs/pull/15008)
insert link right before cursor is correct behavior for all kinds of links. In my opinion it is OK to use this hack personally, but not for public usage.
And this will break visual mode selection too. Suppose you have selected a word "foo", then `org-roam-node-insert`, the selected word will gone due to this advice.
In my opinion, user can define a `org-roam-node-append` to solve the issue. But add an advice in upstream is a bad idea.
#### Reproduction guide :beetle:
no need reproduce, it is just in correct to add advice for a correct function in upstream
*Observed behaviour:* :eyes: :broken_heart:
It is a bad idea to add advice for org-roam-node-insert, considering the original behavior is correct and same for all kinds of links
It will break the visual mode selection too( although this can be solved by adding visual mode in advice, but I do not think is appropriate for upstream usage) 
*Expected behaviour:* :heart: :smile:
roll back  67b3c44fd2d56c838b2cd486a6b974bc7a5fb98a, if user need this function they can add personally.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5bcedd191)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(csv javascript spell-checking latex
     (spacemacs-editing-visual :packages
                               (not indent-guide))
     (conda :variables conda-anaconda-home "/home/wangzongtao/anaconda3")
     emacs-lisp bibtex multiple-cursors ivy git
     (python :variables python-backend 'lsp python-lsp-server 'pyright python-formatter 'black python-sort-imports-on-save t python-format-on-save t)
     (c-c++ :variables c-c++-backend 'lsp-clangd)
     (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-minimum-prefix-length 2 auto-completion-idle-delay 0.2 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip nil auto-completion-use-company-box nil auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
     (better-defaults :variables better-defaults-move-to-beginning-of-code-first t better-defaults-move-to-end-of-code-first nil)
     (org :variables org-enable-roam-support t org-enable-roam-protocol t)
     (shell :variables shell-default-shell 'vterm shell-default-height 60 shell-default-position 'bottom shell-default-term-shell "/bin/bash" shell-enable-smart-eshell t close-window-with-terminal t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
```

**Comment by emacs18** [comment]
I support this request even though I think I was the first person to suggest the original change.
First advising functions should be rarely done in any commonly used package such as spacemacs.
Second I think getting this kind of change right is hard and I'm afraid that the change may cause more harm than small good that it may do.

**Comment by lebensterben** [comment]
reverted
