### ISSUE TITLE
Website grammar typo

### ISSUE THREAD

**Issue by mcp292** [syl20bnr/spacemacs#15232]
On [the main page](https://www.spacemacs.org/#):
![image](https://user-images.githubusercontent.com/49123398/147860264-90ce312f-1132-47f6-aa3f-793573c9e891.png)

Suggestion:
Community-driven configuration provides curated packages tuned by power users and **means** bugs are fixed quickly.

**Comment by lebensterben** [comment]
What's wrong with the sentence?

**Comment by mcp292** [comment]
Community-driven configuration provides...bugs are fixed quickly.

**Comment by dalanicolai** [comment]
I agree it looks a little weird, it could use some comma's... However, I guess fixing this is of low priority

**Comment by lebensterben** [comment]
there's no grammatical error in the sentence.

And there's no such thing as grammar typo. typo stands for typographical error.

**Comment by mcp292** [comment]
Grammatical error: **provides bugs are fixed quickly**. **provides quick bug fixes** could work.

**Comment by lebensterben** [comment]
This is the sentence on the website:

> Community-driven configuration provides curated packages tuned by power users and bugs are fixed quickly.

It has two parts which are connected by an `and`:

1. `Community-driven configuration provides curated packages tuned by power users`
2. `bugs are fixed quickly`

Whatever you might believe, the second part is itself a complete sentence and not a noun phrase of the verb `provides`.

Your interest in improving this project is appreciated, but a minimal level of English proficiency is a must for the subject matter.

**Comment by mcp292** [comment]
> It has two parts which are connected by an `and`:
> 
>     1. `Community-driven configuration provides curated packages tuned by power users`
> 
>     2. `bugs are fixed quickly`
> 
> 
> Whatever you might believe, the second part is itself a complete sentence and not a noun phrase of the verb `provides`.

You still proved my point. Separate with `.` or `;`.

> Your interest in improving this project is appreciated, but a minimal level of English proficiency is a must for the subject matter.

What's with the disrespect?

**Comment by lebensterben** [comment]
You can connect two sentences with a conjunction such as `and`, and there's no need for a `;` or `.`.

**Comment by mcp292** [comment]
You obviously have some attachment to the way it is currently, and I don't appreciate your disrespectful tone. None of us get paid to be here. 

It does not read well. I would like someone else's opinion. 

Yet another suggestion that reads better:
Crowd Configured: Community-driven configuration, packages tuned by power users, quick bug fixes.

**Comment by mcp292** [comment]
Please re-open.

**Comment by lebensterben** [comment]
Your proposed fixes are not legit sentences and most of your comments in this thread is not a complete sentence.

Back to the original question I left, what is the grammatical error after all?

**Comment by dalanicolai** [comment]
@lebensterben As I mentioned already [here](https://github.com/syl20bnr/spacemacs/issues/15232#issuecomment-1004432236), I agree with @mcp292 that it reads a little weird. On the other hand, I think it is not a critical 'bug'. But I would say improvements are welcome (I am no native English speaker b.t.w., so I can not trust too much my own opinion, except for the opinion that I find it sound a little weird also).

**Comment by mcp292** [comment]
@lebensterben maybe you're having trouble reading. 

> Your proposed fixes are not legit sentences 

My propositions clearly indicate the portion of the sentence they intend to replace; thus, there is no requirement to repeat the entire sentence to a competent reader in every suggestion.

> and most of your comments in this thread is not a complete sentence.

most of your comments in this thread ~~is~~ **are** not ~~a~~ complete sentence**s**.

Please don't insult.

> a minimal level of English proficiency is a must for the subject matter.

**Comment by lebensterben** [comment]
Your original proposed fix:
> Community-driven configuration provides curated packages tuned by power users and means bugs are fixed quickly.

Either you left `means` with no subject, or you wrongly made `community-driven configuration` its subject. Whereas the former is grammar error, and the latter is not logically sound as configuration doesn't make bugs fixed quickly.

---

Then you commented

> You still proved my point. Separate with . or ;. "Whatever I believe" I was led to by the prose.

And I pointed out that

> You can connect two sentences with a conjunction such as and, and there's no need for a ; or ..

---

I asked you to point out the grammar error ad nauseam. But you either neglected the request or provide meaningless response.

**Comment by mcp292** [comment]
Once again, you are holding tightly to this sentence, and instead of joining me in improving it, you are focusing on justification for closing this issue, and insulting and detering new members of the community like myself.

Your acclimation to the way it reads does not lend itself to new users: the only people that matter in this context. This is the landing page of the project, and gives new users reasons to try it out. Those reasons should read well to support the project. 

Putting your bitterness aside, here are my thoughts:
According to your reasoning, which is that two sentences can be joined with "and" without presenting a grammatical error, I agree, maybe there's no "error", but the point remains: it does not read well. If you have to explain to me what the real subject of the sentence is, it's probably an indication of potential improvement. 

> Your original proposed fix:
> 
> > Community-driven configuration provides curated packages tuned by power users and means bugs are fixed quickly.
> 
> Either you left `means` with no subject, or you wrongly made `community-driven configuration` its subject. Whereas the former is grammar error, and the latter is not logically sound as configuration doesn't make bugs fixed quickly.

If I accept your point here, you prove my point! If "community-driven configuration" has nothing to do with "quick bug fixes", then why is it under the header "Crowd-Configured", a synonym for "community-driven configuration". The point you are proving is there are changes that need to be made to this sentence.

I argue, as the original author does, that "community-driven configuration" does lend itself to quick bug fixes because of the fact that it's "community-driven", or open source. The speed can be attributed to bugs being found faster with a community behind the product and bugs being fixed faster because anyone in the community can step in.

That being said, these are still valid suggestions:
1. Crowd Configured: Community-driven configuration provides curated packages tuned by power users and means bugs are fixed quickly.
2. Crowd Configured: Community-driven configuration provides curated packages tuned by power users and quick bug fixes.
3. Crowd Configured: Community-driven configuration, packages tuned by power users, quick bug fixes.

**Comment by lebensterben** [comment]
open a new issue if you want. this issue is about grammar error and there is none.

**Comment by dalanicolai** [comment]
Option 3 looks best to me...

**Comment by mcp292** [comment]
> open a new issue if you want. this issue is about grammar error and there is none.

That seems excessive. I could change the title if that makes you feel better. Stop being unreasonable.

**Comment by lebensterben** [comment]
There's no grammar error, despite the OP refuses to recognize it.
