### ISSUE TITLE
org-mode list RET not inserting indented paragraph after quote

### ISSUE THREAD

**Issue by wolfv6** [syl20bnr/spacemacs#15236]
#### Description :octocat:
This issue happens in the org-mode list.
From insert mode, RET inserts an indented paragraph as expected.
An unpaired double quote breaks this behavior.
In any list after the quote, RET inserts a line without indentation.

#### Reproduction guide :beetle:
- Start Emacs
- copy this text into a new org-mode file:

list
- item
  indented paragraph
- item
  indented paragraph

"

list
- item
not indented

*Observed behaviour:* :eyes: :broken_heart:
In any list after the quote, insert mode, RET inserts a line without indentation.

*Expected behaviour:* :heart: :smile:
From insert mode, RET inserts an indented line.

#### System Info :computer:
- org-mode 9.5.2, evil insert mode

- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4d59149eb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(bm emacs-lisp git ivy markdown multiple-cursors org spacemacs-org spell-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
```

**Comment by dalanicolai** [comment]
Thanks for the report. However, this is probably the wrong place to report it, as this is default org-mode behavior.
If possible (if it is not too much work), before you open an issue here, first try to test the behavior in vanilla Emacs, you can get it by starting Emacs with the `-q` flag, i.e. `emacs -q` from the command line. If you still prefer different behavior, then you could open an issue at org-mode.
