### ISSUE TITLE
`package-selected-packages` list does not get updated when layers are removed from `dotspacemacs-configuration-layers`

### ISSUE THREAD

**Issue by mcp292** [syl20bnr/spacemacs#15246]
#### Description :octocat:
`package-selected-packages` list does not get updated when layers are removed from `dotspacemacs-configuration-layers`. Packages are indeed removed though.

Also noted in [this SO post](https://emacs.stackexchange.com/questions/70015/how-to-remove-leftover-packages-from-unused-layers).

#### Reproduction guide :beetle:
- Add `themes-megapack` to `dotspacemacs-configuration-layers`.
-  `SPC f e R` and observe added packages in `package-selected-packages` list.
- Remove `themes-megapack` from `dotspacemacs-configuration-layers`.
- Observe presence of `*-theme` packages in `package-selected-packages` list, despite `SPC f e R` and/or restart Emacs.

*Observed behaviour:* :eyes: :broken_heart:
`package-selected-packages` list not updated.

*Expected behaviour:* :heart: :smile:
`package-selected-packages` list gets updated.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a843146f1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python emacs-lisp git helm multiple-cursors org spell-checking treemacs gnus)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
SPC f e R

**Comment by mcp292** [comment]
Tried `SPC f e R`, `SPC q r`, `SPC q R`. I made sure to start a new session and check before posting this as an issue.

**Comment by lebensterben** [comment]
`package-selected-packages` is written by `custom-save`. Try to run this command.

**Comment by mcp292** [comment]
I ran `custom-save` then `SPC f e d` and the `*-theme` packages were still present. Just to make sure I did `SPC f e R`, `SPC f e U` and `SPC q r` afterwards. The `*-theme` packages are still present.

**Comment by lebensterben** [comment]
The bug is confirmed.
