### ISSUE TITLE
Inconsistent menu after pressing SPC 

### ISSUE THREAD

**Issue by DrWaleedAYousef** [syl20bnr/spacemacs#15241]
#### Description :octocat:
After pressing `SPC`, what is available then at the `k` key is not always the `smartparens` menu; sometimes it is the `lisp` menu! This is inconsistent, and I cannot detect when it happens.

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0206197b2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv dap c-c++ php systemd
     (latex :variables latex-build-command "LatexMk" latex-enable-auto-fill t latex-backend 'lsp latex-build-engine 'luatex latex-view-pdf-in-split-window t latex-enable-magic t latex-refresh-preview t latex-enable-folding t)
     (bibtex :variables bibtex-enable-ebib-support t ebib-preload-bib-files
             '("~/MyDocuments/Phd/texmf/bibtex/bib/base/publications.bib" "~/MyDocuments/Phd/texmf/bibtex/bib/base/booksIhave.bib")
             ebib-file-search-dirs
             '("~/MyDocuments/Phd/PDF/")
             ebib-import-directory
             '("~/Downloads/"))
     lua
     (html :variable css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t web-fmt-tool 'web-beautify html-enable-leex-support t)
     web-beautify prettier gnus
     (git :variables git-enable-magit-gitflow-plugin t git-enable-magit-svn-plugin t)
     (yaml :variables yaml-enable-lsp t)
     (python :variables python-format-on-save t python-formatter 'yapf python-fill-column 99 python-backend 'lsp python-lsp-server 'pyright)
     (auto-completion :variables auto-completion-enable-help-tooltip t)
     better-defaults emacs-lisp
     (helm :variables helm-enable-auto-resize t helm-no-header t)
     (lsp :variables lsp-lens-enable t)
     (markdown :variables markdown-live-preview-engine 'vmd)
     (chrome :variables)
     multiple-cursors
     (org :variables org-enable-org-contacts-support t org-contacts-files
          '("~/.emacs.d.loadpath/Contacts-Imported.org")
          org-capture-templates
          '(("c" "Contacts" entry
             (file "~/Contacts-Imported.org")
             "* %(org-contacts-template-name))\n:PROPERTIES:\n:EMAIL: %(org-contacts-template-email)\n:END:")))
     (pdf :variables pdf-view-display-size 'fit-page)
     (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
     (spell-checking :variables spell-checking-enable-auto-dictionary t)
     syntax-checking
     (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Please provide more details.

What do you mean by
> sometimes it is the lisp menu

To me the key bindings listed looks the same. How to re-produce the result?

**Comment by DrWaleedAYousef** [comment]
I mean it is inconsistent. I do not know even when this happens. Sometimes SPC-k gives the lisp keybindings and sometimes it gives the smartparens keybinding, which is what I really need. 

Once more, this behaviour is very inconsistent

**Comment by DrWaleedAYousef** [comment]
> I mean it is inconsistent. I do not know even when this happens. Sometimes SPC-k gives the lisp keybindings and sometimes it gives the smartparens keybinding, which is what I really need.
> 
> Once more, this behaviour is very inconsistent

Ok; now, while I am working, it happened that (once again I do not know why or how) the `k` letter shows the keybindings of the smartparens not the lisp one. Please, take a look at the two attached picture for before/after pressing the `k` key
![image](https://user-images.githubusercontent.com/12213197/148291799-ae1d7175-ad55-4c39-afd6-253077eef401.png)
![image](https://user-images.githubusercontent.com/12213197/148291867-52d8b289-3851-4e02-8f9e-3eb42a28f14e.png)

**Comment by lebensterben** [comment]
I've no idea of what you mean by "the lisp one".

**Comment by DrWaleedAYousef** [comment]
> I've no idea of what you mean by "the lisp one".

Ok, I restarted emacs and now the behaviour is as appears hear in the attachment. See, what is available at the letter `k` and after I press it:
![image](https://user-images.githubusercontent.com/12213197/148414650-110f4934-f81f-4c0f-bee6-4471775dbc29.png)
![image](https://user-images.githubusercontent.com/12213197/148414701-5879c2f3-1d41-4f71-a1f5-c46834f2accd.png)

**Comment by lebensterben** [comment]
Confirmed. They should be added in https://github.com/syl20bnr/spacemacs/blob/d63e172bde5b2b3cb8ddb676f6db1e6df4b31fbb/layers/%2Bspacemacs/spacemacs-defaults/keybindings.el#L58-L59

It's likely those bindings are shadowed.

**Comment by emacs18** [comment]
The command in question seems to be `lisp-state-toggle-list-state` which is bound to `SPC k .` and `SPC m ,` among other key bindings.

**Comment by emacs18** [comment]
For me `SPC k` always shows the "lisp state" key bindings shown in the first of two images shown above.  The only way that I can switch to the other state shown in the second image above is to disable `evil-list-state` package by this patch 
```diff
diff --git a/layers/+spacemacs/spacemacs-evil/packages.el b/layers/+spacemacs/spacemacs-evil/packages.el
index e369b222c..fe58bf40b 100644
--- a/layers/+spacemacs/spacemacs-evil/packages.el
+++ b/layers/+spacemacs/spacemacs-evil/packages.el
@@ -34,7 +34,7 @@
         evil-iedit-state
         evil-indent-plus
         evil-lion
-        evil-lisp-state
+        ;; evil-lisp-state
         evil-nerd-commenter
         evil-matchit
         evil-numbers
```

**Comment by lebensterben** [comment]
Thanks for the tips @emacs18 
As I suspected, some keys are shadowed.
Specifically, we have first declared prefixes under `` SPC k ` ``, `SPC k d`, and `SPC k D` in spacemacs/layers/+spacemacs/spacemacs-defaults/keybindings.el
But then they are used again as key bindings for commands when `evil-lisp-state` mode started.

**Comment by lebensterben** [comment]
I'm investigating the issue.
It's related to how we declare prefix key description for which-key.

**Comment by lebensterben** [comment]
Found something interesting.

First, the "missing" prefixes will appear before you load any buffer that derives `prog-mode`.
But other key bindings under `SPC k` won't appear yet.

When a buffer that derives from `prog-mode` is loaded, `evil-lisp-state` will be loaded as well. At that point, all key bindings under `SPC k` appear but those prefixes disapper.

Now, after pressing `SPC k`, if you press `C-h C-d` to toggle docstrings, all key bindings and the missing prefixes would show up again.
