### ISSUE TITLE
 Invalid function: evill-redirect-digit-argument 

### ISSUE THREAD

**Issue by q60** [syl20bnr/spacemacs#15245]
`SPC-s-e` yields this

`Invalid function: evill-redirect-digit-argument`

I have a fresh installation of spacemacs.

![image](https://user-images.githubusercontent.com/61933599/148087566-2633eec2-e543-4251-a8da-956ac0dc974c.png)

**Comment by lebensterben** [comment]
Please follow the instruction of issue template.

**Comment by lebensterben** [comment]
This should be fixed in either
https://github.com/syl20bnr/spacemacs/commit/23367d08f890873e77fd9a434c9332cf53d5f9df
or
https://github.com/syl20bnr/spacemacs/commit/d3071ae37bbd3a527e3ad429d6f0e8f9bfd8c980

Please update your spacemacs.
Reopen if the issue still persists.
