### ISSUE TITLE
`projectile-replace` treats search string as regexp contrary to its function description

### ISSUE THREAD

**Issue by mcp292** [syl20bnr/spacemacs#15248]
#### Description :octocat:
`SPC p R` calls `projectile-replace` which according to its describe function should not treat the search string as regexp:

> Replace literal string in project using non-regexp ‘tags-query-replace’.

Yet, it uses regexp.

#### Reproduction guide :beetle:
- `SPC p R a. RET RET`

*Observed behaviour:* :eyes: :broken_heart:
Notice the minibuffer says "Replacing regexp" and shown matches follow the regexp result of "a.". Minibuffer message is consistent with and without the `.`.

*Expected behaviour:* :heart: :smile:
Search string is treated as literal, non-regexp.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a843146f1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python emacs-lisp git helm multiple-cursors org spell-checking treemacs gnus)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
Confirmed. But this should be reported in upstream.

**Comment by mcp292** [comment]
In other words it's not a spacemacs problem it's a projectile problem?

**Comment by lebensterben** [comment]
I think so.
