### ISSUE TITLE
Cannot disable `org-mode` by re-issuing `SPC SPC org-mode`

### ISSUE THREAD

**Issue by mcp292** [syl20bnr/spacemacs#15259]
#### Description :octocat:
Cannot disable `org-mode` by re-issuing `SPC SPC org-mode`.

#### Reproduction guide :beetle:
- `SPC SPC org-mode` (enabled)
- `SPC SPC org-mode` (still enabled)

*Observed behaviour:* :eyes: :broken_heart:
Org mode remains enabled.

*Expected behaviour:* :heart: :smile:
- `SPC SPC org-mode` (enabled)
- `SPC SPC org-mode` (disabled)

Similar to the behavior observed when replacing `org-mode` with `auto-fill-mode` in the above.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. a843146f1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python emacs-lisp git helm multiple-cursors org spell-checking treemacs gnus)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
Each buffer must have a major mode.
You cannot "toggle off" major mode like minor modes.
You can choose another major mode instead.

**Comment by mcp292** [comment]
Ah I see, so the way to get out is to issue `text-mode` or similar. Thanks!
