### ISSUE TITLE
"Crowd-Configured" section of website doesn't read well

### ISSUE THREAD

**Issue by mcp292** [syl20bnr/spacemacs#15250]
Forced to re-post this by the unreasonable, unproductive @lebensterben. Originally #15232.

> On [the main page](https://www.spacemacs.org/#): ![image](https://user-images.githubusercontent.com/49123398/147860264-90ce312f-1132-47f6-aa3f-793573c9e891.png)

Suggestions:
1. Crowd Configured: Community-driven configuration provides curated packages tuned by power users and means bugs are fixed quickly.
2. Crowd Configured: Community-driven configuration provides curated packages tuned by power users and quick bug fixes.
3. Crowd Configured: Community-driven configuration, curated packages tuned by power users, quick bug fixes.

**Comment by mcp292** [comment]
[Continuing the conversation](https://github.com/syl20bnr/spacemacs/issues/15232#issuecomment-1007379784) with @dalanicolai:
> Option 3 looks best to me... 

I agree, I like this the best, but when considering the other entries on the page, none of them follow a list format. They don't all have to conform, but I'd argue they should.

![image](https://user-images.githubusercontent.com/49123398/148584200-31a68b39-b53f-4af2-8765-c718ebc0b994.png)


> but 'curated' could stay

I added it back! Nice catch.

**Comment by lebensterben** [comment]
The original sentence reads best.

The first needlessly added a "means" and I've pointed out its problem already.

The second one shares the same issue as the first one, that it's illogical.

The third one is the best among all proposed changes, but it's too tedious.

**Comment by mcp292** [comment]
Odd, you make me re-open the issue, then reference what you said in the previous issue. Outstanding job!

What I believe your error is, is claiming that "provides" is unrelated to the phrase after the conjunction "and". The header is "Crowd-Configured", the first word of the sentence is "Community-driven configuration", or just another way of saying "Crowd-Configured". 

It goes on to emphasize that "Crowd-Configured" "provides" point 1 and 2. If 2 ("bugs are fixed quickly") has nothing do to with "Crowd-Configured" or what it "provides", then what is it doing there?
