### ISSUE TITLE
How to use polymode in spacemacs?

### ISSUE THREAD

**Issue by hengaini2055** [syl20bnr/spacemacs#15269]
as title!

**Comment by lebensterben** [comment]
It's unclear what you mean.
What do you want to achieve?

**Comment by lebensterben** [comment]
it's unclear to me what you mean by
> rust-mode cannot satisfied the <html, css, javascript> source code in rust code

I'm a rust programmer and I've no idea what you are talking.

**Comment by hengaini2055** [comment]
I mean "auto format".

**Comment by lebensterben** [comment]
Can you just show me the file you're working on so I can guess what you are trying to do?

**Comment by lebensterben** [comment]
> I mean "auto format".

rust-mode relies on rustfmt for formatting rust code.

I don't know why you need polymode.

**Comment by hengaini2055** [comment]
'''
impl Component for App {
    type Message = Msg;
    type Properties = ();

    fn create(_ctx: &Context<Self>) -> Self {
        Self {
            hovered: Hovered::None,
            list_link: WeakComponentLink::default(),
            sub_list_link: WeakComponentLink::default(),
        }
    }

    fn update(&mut self, _ctx: &Context<Self>, msg: Self::Message) -> bool {
        match msg {
            Msg::Hover(hovered) => {
                self.hovered = hovered;
                true
            }
        }
    }

    fn view(&self, ctx: &Context<Self>) -> Html {
        let on_hover = &ctx.link().callback(Msg::Hover);
        let onmouseover = &ctx.link().callback(|_| Msg::Hover(Hovered::None));
        let onmouseoversublist = &ctx.link().callback(|e: MouseEvent| {
            e.stop_propagation();
            Msg::Hover(Hovered::List)
        });
        let list_link = &self.list_link;
        let sub_list_link = &self.sub_list_link;

        // note the use of `html_nested!` instead of `html!`.
        let letters = ('A'..='C')
            .map(|letter| html_nested! { <ListItem name={letter.to_string()} {on_hover} /> });

        html! {
            <div class="main" {onmouseover}>
                <h1>{ "Nested List Demo" }</h1>
                <List {on_hover} weak_link={list_link}>
                    <ListHeader text="Calling all Rusties!" {on_hover} {list_link} />
                    <ListItem name="Rustin" {on_hover} />
                    <ListItem hide=true name="Rustaroo" {on_hover} />
                    <ListItem name="Rustifer" {on_hover}>
                        <div class="sublist" onmouseover={onmouseoversublist}>{ "Sublist!" }</div>
                        <List {on_hover} weak_link={sub_list_link}>
                            <ListHeader text="Sub Rusties!" {on_hover} list_link={sub_list_link}/>
                            <ListItem hide=true name="Hidden Sub" {on_hover} />
                            { for letters }
                        </List>
                    </ListItem>
                </List>
                { self.view_last_hovered() }
            </div>
        }
    }
}
```
html! block is html.

**Comment by lebensterben** [comment]
Okay I got it.

Currently it's not possible to format the "html" code in that macro invocation.
