### ISSUE TITLE
`lsp-ui-doc-mode` doesn't work well with `flycheck`

### ISSUE THREAD

**Issue by rayw000** [syl20bnr/spacemacs#15277]
![image](https://user-images.githubusercontent.com/69779107/149706915-d5164530-5d6b-4069-9689-bfef70ca33e9.png)

The popups generated by `lsp-ui-doc-mode` may overlap the errors from `flycheck`.

**Comment by lebensterben** [comment]
You should report it to upstream.

**Comment by lebensterben** [comment]
BTW I don't think this is a bug.

**Comment by rayw000** [comment]
Since we use these two packages simultaneously, we could do some checks and configurations, probably. Upstreams might not have the ability (and should not) to know the other's existence?

**Comment by lebensterben** [comment]
The pop up window is provided by lsp-ui, so is the sideline that shows you the flycheck error.
(You can turn lsp-sideline off if you are not convinced.)

I commented that this is not a bug because I don't see anything wrong when a pop-up window covers other UI elements.

**Comment by rayw000** [comment]
Understood. So in my opinion, `spacemacs` could do something to avoid this covering, since using both `flycheck` and `lsp-ui`  would be a common scenario.

**Comment by lebensterben** [comment]
This is not our responsibility:
- The behavior is not a bug. This is the expected behavior.
- Calculating the position of the pop-up window is not trivial.

**Comment by lebensterben** [comment]
And there's nothing to do with whatever layers you used.

Both lsp-sideline and lsp-ui-doc are purely artefacts of lsp.
