### ISSUE TITLE
Cursor color changes from insert mode color to normal mode color when it shouldn't.

### ISSUE THREAD

**Issue by Seanld** [syl20bnr/spacemacs#15279]
#### Description :octocat:
When doing things like `C-x C-s` to save a file, instead of the intended `SPC f s`, the cursor color *sometimes* changes to normal mode color (orange), but the cursor stays thin, as I'm still in insert mode. Also, when editing Babel blocks in Org, pressing tab also tends to change the cursor color to orange while in insert mode. It's very annoying to have the cursor color and the "mode square" behind the window number mismatched.

#### Reproduction guide :beetle:
- Start Emacs
- Save a buffer with `C-x C-s`, or
- Edit a Babel block in Org mode

*Observed behaviour:* :eyes: :broken_heart:
Cursor color changes to orange.

*Expected behaviour:* :heart: :smile:
Cursor color should not change.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.60
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 1541eed6b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((javascript :variables javascript-backend 'lsp)
 csv
 (go :variables go-tab-width 4)
 lua
 (sql :variables sql-backend 'lsp sql-lsp-sqls-workspace-config-path 'workspace sql-capitalize-keywords nil)
 html yaml
 (python :variables python-backend 'lsp python-lsp-server 'pyright)
 auto-completion emacs-lisp git helm
 (lsp :variables lsp-navigation 'both lsp-lens-enable t lsp-use-lsp-ui t lsp-ui-sideline-enable nil lsp-ui-doc-enable nil lsp-ui-doc-position 'top lsp-ui-doc-show-with-cursor t lsp-ui-doc-header nil lsp-ui-doc-include-signature nil lsp-ui-doc-alignment 'window lsp-ui-doc-use-childframe t lsp-ui-doc-max-height 7 lsp-ui-doc-max-width 70 lsp-ui-doc-delay 2 lsp-ui-doc-text-scale-level -1 lsp-ui-doc-winum-ignore t)
 markdown
 (org :variables org-enable-verb-support t org-enable-asciidoc-support t org-enable-github-support t)
 (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left)
 treemacs
 (unicode-fonts :variables unicode-fonts-enable-ligatures t unicode-fonts-ligature-modes
                '(text-mode prog-mode))
 pass colors eww slack c-c++ restclient)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ IMAGEMAGICK JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM XWIDGETS GTK3 ZLIB

**Comment by lebensterben** [comment]
Cannot reproduce.
