### ISSUE TITLE
[lang/rust] rust-analyzer (lsp) doesn't work

### ISSUE THREAD

**Issue by Martinsos** [syl20bnr/spacemacs#15276]
#### Description :octocat:
rust-analyzer (lsp server for rust) doesn't work.

#### Reproduction guide :beetle:
- Install rust-analyzer on machine and make sure it is in $PATH
- Create hello world rust project with `cargo new testproject`
- Start Emacs
- Configure emacs to use rust-analyzer as described in rust layer (develop branch).
- Open src/main.rs and notice that lsp features don't work and error is printed in emacs message buffer.

*Observed behaviour:* :eyes: :broken_heart:
Lsp server doesn't work, it says in the minibuffer it can't find the workspace, and it prints additional messages in the message buffer.

Snippet from the message buffer:

Saving file /home/martin/test/rusttest/src/main.rs...
Formatted buffer with rustfmt.
Wrote /home/martin/test/rusttest/src/main.rs
Suspicious state from syntax checker rust-cargo: Flycheck checker rust-cargo returned 101, but its output contained no errors: error: process didn't exit successfully: `rustc -vV` (exit status: 127)
--- stderr
rustc: error while loading shared libraries: libLLVM-13.so: cannot open shared object file: No such file or directory

*Expected behaviour:* :heart: :smile:
Expected lsp to work for rust, by using rust-analyzer.
I tried opening the same project in visual studio code, and it works, so rust-analyzer certainly is in the path and works.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. ca93e28a9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((rust :variables rust-format-on-save t)
 python windows-scripts vimscript meson ruby docker terraform emoji
 (auto-completion :variables auto-completion-return-key-behavior 'nil auto-completion-tab-key-behavior 'complete)
 better-defaults emacs-lisp git
 (haskell :variables haskell-completion-backend 'lsp haskell-indentation-layout-offset 4 haskell-indentation-starter-offset 4 haskell-indentation-left-offset 4 haskell-indentation-where-pre-offset 2 haskell-indentation-where-post-offset 2)
 helm html
 (javascript :variables js2-mode-show-strict-warnings nil js2-basic-offset 2 js-indent-level 2)
 (lsp :variables lsp-rust-server 'rust-analyzer)
 markdown multiple-cursors org
 (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom spacemacs-vterm-history-file-location "~/.bash_history")
 (syntax-checking :variables syntax-checking-enable-tooltips nil flycheck-display-errors-function #'flycheck-display-error-messages-unless-error-list)
 (treemacs :variables treemacs-use-git-mode 'deferred)
 version-control yaml cmake)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by Martinsos** [comment]
I added following to spacemacs/user-config:
```
  (use-package rust-cargo
    :config
    (setq flycheck-rust-cargo-executable "/home/martin/.cargo/bin/cargo")
    )
```
and that got me a step further.
So that means that emacs can't find cargo on my PATH? Why is that? Visual studio found it without any problems.

Now I get following error however:
```
LSP :: rust-analyzer failed to load workspace: Failed to read Cargo metadata from Cargo.toml file /home/martin/test/rusttest/Cargo.toml, cargo 1.58.0: Failed to run `"cargo" "metadata" "--format-version" "1" "--manifest-path" "/home/martin/test/rusttest/Cargo.toml"`: `cargo metadata` exited with an error: error: process didn't exit successfully: `rustc -vV` (exit status: 127)
--- stderr
rustc: error while loading shared libraries: libLLVM-13.so: cannot open shared object file: No such file or directory
```

Btw if I run `rustc -vV` in terminal, I get:
```
rustc 1.58.0 (02072b482 2022-01-11)
binary: rustc
commit-hash: 02072b482a8b5357f7fb5e5637444ae30e423c40
commit-date: 2022-01-11
host: x86_64-unknown-linux-gnu
release: 1.58.0
LLVM version: 13.0.0
```

**Comment by lebensterben** [comment]
where is cargo and other rust toolchain installed?

**Comment by Martinsos** [comment]
I installed them via `rustup`.

```sh
~$ whereis rustc cargo rust-analyzer rustfmt
rustc: /usr/bin/rustc /home/martin/.cargo/bin/rustc /usr/share/man/man1/rustc.1.gz
cargo: /usr/bin/cargo /home/martin/.cargo/bin/cargo /usr/share/man/man1/cargo.1.gz
rust-analyzer: /home/martin/.cargo/bin/rust-analyzer
rustfmt: /usr/bin/rustfmt /home/martin/.cargo/bin/rustfmt
```

Here is my PATH:
```
echo $PATH
...:/home/martin/.cargo/bin:...:/usr/local/bin:/usr/bin:/usr/local/sbin:...
```

**Comment by lebensterben** [comment]
Do you start Emacs as a systemd service?

**Comment by Martinsos** [comment]
@lebensterben no! I am using gnome and I normally start it from gnome UI, via Win + typing emacs and then click on the launcher.

Btw I just tried running it from the terminal, and I can confirm it behaves the same way as when run via Gnome launcher.

**Comment by lebensterben** [comment]
Try to change your PATH so that ~/.cargo/bin is before /usr/bin

**Comment by Martinsos** [comment]
@lebensterben it already is, as you can see from the comment above! First comes `$HOME/.cargo/bin`, which is actually done by `.cargo/env` which ensures that this path is prepended at the start of the PATH, then comes `/usr/bin` quite later.

**Comment by lebensterben** [comment]
@Martinsos 
They're not, from your comment.

rustc: /usr/bin/rustc /home/martin/.cargo/bin/rustc /usr/share/man/man1/rustc.1.gz
cargo: /usr/bin/cargo /home/martin/.cargo/bin/cargo /usr/share/man/man1/cargo.1.gz
rust-analyzer: /home/martin/.cargo/bin/rust-analyzer
rustfmt: /usr/bin/rustfmt /home/martin/.cargo/bin/rustfmt

**Comment by Martinsos** [comment]
@lebensterben I was referring to the comment where I echoed PATH, where it was visible that .cargo/bin is first!

Here is the output of which:
```
$ which rustc cargo rust-analyzer rustfmt
/home/martin/.cargo/bin/rustc
/home/martin/.cargo/bin/cargo
/home/martin/.cargo/bin/rust-analyzer
/home/martin/.cargo/bin/rustfmt
```

**Comment by lebensterben** [comment]
They appear to be the right order in a shell.

Next you need to make sure Emacs uses the same order.

You can check with (executable-find "cargo") for example.

**Comment by lebensterben** [comment]
Check your .spacemacs.env
There's a PATH there.

**Comment by Martinsos** [comment]
@lebensterben ok I wasn't aware of that!
So it "freezes" my env? But I am guessing it also loads PATH from the system every time, or it does not? 

In .spacemacs.env I have:
```
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/martin/opt
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

But when I print `exec-path` there is more to it, it also has those `nix` paths, where are those coming from? And why are rust paths not included?

**Comment by lebensterben** [comment]
You can manually change that to match your PATH in shell.

**Comment by Martinsos** [comment]
@lebensterben thanks, that sounds like it should work!

But it seems to me like the source of an error here is the fact that PATH is not read by (spac)emacs -> how is that, do you have any idea about it? I tried looking for docs on spacemacs page about spacemacs.env but haven't found anything. I was hoping to understand how is PATH read and how is it combined with the PATH from spacemacs.env .

**Comment by Martinsos** [comment]
I wonder if this is connected: https://github.com/syl20bnr/spacemacs/issues/14447 -> it seems spacemacs was before reading PATH from the shell, but now it doesn't any more? There is no explanation as to why this issue was closed so I don't know if the issue was incorrect or fixed or smth else though.

**Comment by Martinsos** [comment]
All right, so I moved the additions of rust exec paths to PATH from .bashrc to .bash_profile, and now when I see spacemacs is picking those up in `exec-path`:

```
exec-path is a variable defined in ‘C source code’.
Its value is
("/usr/local/bin" "/usr/bin" "/usr/local/sbin" "/usr/bin/site_perl" "/usr/bin/vendor_perl" "/usr/bin/core_perl" "/home/martin/opt" "/home/martin/.cargo/bin" "/home/martin/.cabal/bin" "/home/martin/.ghcup/bin" "/home/martin/.local/share/gem/ruby/3.0.0/bin" "/home/martin/.local/bin" "/home/martin/.nix-profile/bin" "/nix/var/nix/profiles/default/bin" "/usr/lib/emacs/27.2/x86_64-pc-linux-gnu")
```

However, /usr/bin is in front of /home/martin/.cargo/bin now, so that is a problem I have to solve next.

I could solve it by adding /home/martin/.cargo/bin at the start of PATH in spacemacs.env, but I would love to understand the idea behind spacemacs.env better.

I am wondering, how is it that visual studio code worked out of the box while in spacemacs I encountered these problems? Maybe spacemacs should also be looking into .bashrc? It seems to me, after some googling, that a lot of people are defining their paths in .bashrc and not directly in .bash_profile. Then there is spacemacs.env, which introduces additional confusion, at least in my case. I still don't understand how to think about it and haven't found anything about it in spacemacs docs. There is also the fact that spacemacs while merging PATH from spacemacs.env and external PATH changes the order of paths -> in my terminal `/usr/bin` comes much later then `/home/martin/.cargo/bin`, but in spacemacs it is the opposite.

**Comment by lebensterben** [comment]
@Martinsos 

The motivation, at least some of, of `.spacemacs.env` are:
- It's faster to parse this file instead of getting environment variables from the shell.
- It's "reproducible" and it allows users to investigate what's actually used as environment variables.

In my experience it causes confusions for me and I prefer to manually edit it. But there is a way to update it:
Press `SPC f e E` to refresh it.

It's possible that `.spacemacs.env` is written as in its current state before you added `~/.cargo/bin` to your `PATH`, and it haven't been updated since then.

**Comment by Martinsos** [comment]
Thanks for explaining!

Is there a piece of documentation explaining this (.spacemacs.env and how it merges itself with env vars from the shell)? If not should I look into making a PR to add one?

What about the fact that spacemacs reverses the order of my paths in exec-path -> that is pretty bad isn't it? It can easily cause unexpected behaviour.

I guess that the broader question is -> why does this stuff work seamlessly in vscode and not in spacemacs, and how do we get spacemacs closer to that experience?

**Comment by Martinsos** [comment]
Found the docs! https://develop.spacemacs.org/doc/DOCUMENTATION.html#environment-variables-and-path .

And I opened an issue for the messed up path in exec-path.

Since this issue is resolved, I will close it, thanks a lot @lebensterben for patience and effort!
