### ISSUE TITLE
Auto-completion layer breaks notmuch-company

### ISSUE THREAD

**Issue by agenbite** [syl20bnr/spacemacs#15270]
#### Description :octocat:
When both the notmuch and the auto-completion layers are active, the address completion in notmuch stops working. If auto-completion layer is off, notmuch works as expected.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC a e n i` to open notmuch
- `m` to create a new message
- Start writing an address in the To: line

*Observed behaviour:* :eyes: :broken_heart:
Autocompletion thinks you're writing text, tries to complete words.

*Expected behaviour:* :heart: :smile:
Autocompletion should use notmuch-company to populate a list of mail addresses.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5bcedd191)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python go yaml csv org
        (org :variables org-enable-hugo-support t)
        google-calendar notmuch evil-snipe
        (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-override-mode t)
        latex bibtex git version-control pdf emacs-lisp compleseus
        (compleseus :variables compleseus-engine 'selectrum)
        ranger)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by fran-penedo** [comment]
I don't see this behavior exactly. For me autocompletion is broken no matter what. I can fix it if I add the following to `notmuch/init-notmuch`'s `:config`:

```
      (spacemacs|add-company-backends
        :backends notmuch-company
        :modes notmuch-message-mode)
```

However, both layers haven't been changed in a while, so I assume it's a notmuch package change. Let me know if it works for you.

**Comment by agenbite** [comment]
Hey, thanks for looking into this! :) I had found the same solution yesterday, after quite a bit of testing. I'll send a patch to the notmuch layer, if that's ok. 

I'd say the info in the [autocompletion layer](https://develop.spacemacs.org/layers/+completion/auto-completion/README.html#add-auto-completion-in-a-layer) about adding the functionality to a layer could be improved indeed. And indeed it seems there's not much people using nor mantaining notmuch layer.

**Comment by fran-penedo** [comment]
If you have the autocompletion layer switched off, how is notmuch setting up autocompletion? Can you check? For completeness, I'm running emacs 27.2, commit cd9d8c5b2413e27763590366acf49a20f63c6f0d in spacemacs, and version 20220126.1122 of notmuch elpa package.

**Comment by agenbite** [comment]
On Fri Feb 4, 2022 at 1:07 PM CET, fran-penedo wrote:
> If you have the autocompletion layer switched off, how is notmuch
> setting up autocompletion? Can you check?
I'm not sure what you mean. Notmuch has this notmuch-company.el which
does autocompletion in the To: and related fields. And, apparently,
company gets installed by other layer amongst those that I have
activated (fwiw: systemd python go yaml csv org google-calendar notmuch
evil-snipe latex bibtex git version-control pdf emacs-lisp compleseus
lsp syntax-checking ranger). Did I reply to your question?

> For completeness, I'm running emacs 27.2, commit
> cd9d8c5b2413e27763590366acf49a20f63c6f0d in spacemacs, and version
> 20220126.1122 of notmuch elpa package.
I'm on emacs 27.1, spacemacs 0.300.0 and right now I use the last
development version of notmuch (cloned yesterday). 

Thanks for your time! :)

**Comment by fran-penedo** [comment]
> Notmuch has this notmuch-company.el which does autocompletion in the To: and related fields.

Yeah sure, but someone has to be telling company to be on in notmuch-message mode and with the notmuch-company backend. Even if you have some sort of global company variable set, it's not going to know which backend to use, someone has to set that variable.

> spacemacs 0.300.0

I'm not sure that number means anything, since we're in a sort of rolling release. Are you in a reasonably up to date commit in the `develop` branch?

**Comment by agenbite** [comment]
On Fri Feb 4, 2022 at 7:44 PM CET, fran-penedo wrote:
> Yeah sure, but someone has to be telling company to be on in notmuch-message mode and with the notmuch-company backend. Even if you have some sort of global company variable set, it's not going to know which backend to use, someone has to set that variable.
You mean if company-backends holds any reference to notmuch? Afaics, no. But of course it might be the case that the variable is somehow composed and the reference included when one enters in insert mode after the To: keyword... As you know, there's no reference to company in the definition of the notmuch layer.

> I'm not sure that number means anything, since we're in a sort of rolling release. Are you in a reasonably up to date commit in the `develop` branch?
It's been a while since I updated spacemacs, and I wasn't aware of the change in the release scheme... Of course, after pulling from git I'm in version 0.999.0, which is the rolling release.

**Comment by fran-penedo** [comment]
> You mean if company-backends holds any reference to notmuch? Afaics, no. But of course it might be the case that the variable is somehow composed and the reference included when one enters in insert mode after the To: keyword... As you know, there's no reference to company in the definition of the notmuch layer.

I'm so confused then as to how you're getting autocompletion. And you're sure after spacemacs is up to date you still see the same behavior?

**Comment by agenbite** [comment]
On Fri Feb 4, 2022 at 10:26 PM CET, fran-penedo wrote:
> I'm so confused then as to how you're getting autocompletion. And you're sure after spacemacs is up to date you still see the same behavior?
Might be related to the compleseus layer, which I use instead of
helm/ivy?

**Comment by lebensterben** [comment]
I've edited some of @agenbite 's comments to make them readable on both PC and mobile platform.

Please note that email reply doesn't support markdown (on some platforms). Please supplement it with ample amount of line breaks.
