### ISSUE TITLE
spacemacs modeline is highly customized, but how could I know the company backends status

### ISSUE THREAD

**Issue by andyque** [syl20bnr/spacemacs#1528]
From http://emacs.stackexchange.com/questions/5665/find-out-backend-used-in-company-completion

It said 

>company has a very useful feature that modifies its modeline lighter to display the backend currently in use.

But I can't see the backend in spacemacs mode line.

**Comment by person808** [comment]
Comment this line in `~/.emacs.d/contrib/auto-completion/packages.el`: `(spacemacs|diminish company-mode " ⓐ" " a")`

**Comment by andyque** [comment]
@person808  Thanks.
