### ISSUE TITLE
Spacemacs doesn't respect the order of paths in shell PATH while combining it with PATH from .spacemacs.env

### ISSUE THREAD

**Issue by Martinsos** [syl20bnr/spacemacs#15280]
My .spacemacs.env was somewhat old and had PATH that is effectively a subset of the PATH that is actually currently set in my shell.

The result of this was that, when combining PATH from shell with PATH from the .spacemacs.env, in order to build exec-path, spacemacs effectively changed the order of paths: in PATH in shell I had /usr/bin somewhere in the middle/end, but in exec-path it ended up at the front.

This resulted in LSP not being able to pick up correct version of binaries for Rust, which resulted in mystic errors from rust tooling, about missing shared libraries, missing workspaces and similar. This happened due to spacemacs picking up my global rust installation before the local one that was done in ~/.cargo/bin, due to it putting /usr/bin in front of the exec-path, although it was deliberately set to more backward position in the PATH in the shell.

The thing is, until now, I had no idea .spacemacs.env even existed, so this was altogether very confusing.

Would it make sense to modify the way spacemacs builds exec-path so that order of paths in PATH doesn't change? Or is there some other way to avoid these kind of problems? It seems to me that this can be very confusing for people who are not aware of .spacemacs.env, and I am not sure why would most be since it is not something that one normally touches or thinks about.

Btw after this I tried opting out of using .spacemacs.env and using `exec-path-from-shell` as per instructions in the docs, however I failed to figure out how to do it -> I added `exec-path-from-shell`, I removed the `(spacemacs/load-spacemacs-env)` from `dotspacemacs/user-env ()` and I added `exec-path-from-shell-initialize`, but got an error that `exec-path-from-shell-initialize` is not defined.

**Comment by Martinsos** [comment]
Here is the related issue where I encountered this problem: https://github.com/syl20bnr/spacemacs/issues/15276 .

**Comment by dalanicolai** [comment]
As far as I understand, Spacemacs sets the `exec-path` using the function `load-env-vars-set-env`. In that function it first removes duplicates from the [inherited exec-path](https://www.gnu.org/software/emacs/manual/html_node/elisp/Subprocess-Creation.html), then it takes `env-vars` from your `spacemacs-env-vars-file` (i.e. `.spacemacs.env`) and prepends them to the `exec-path`.
I am not sure how the `env-vars` are obtained from the `.spacemacs.env` (as I did not bother to completely understand the regexp in `load-env-vars-env-var-regexp`), but on my system the value of `env-vars` is nil.

I assume `usr/bin` is by default in your system path, and Spacemacs seems to only prepend environment variables to it, so I am not sure how `/usr/bin` ended up in front on your system. However, I guess it somehow took it from your `.spacemacs.env`.

Maybe you can use [edebug](https://www.gnu.org/software/emacs/manual/html_node/elisp/Using-Edebug.html) to debug `load-env-vars-set-env` by instrumentalizing it, and then doing `M-x spacemacs/load-spacemacs-env`. (The [emacs-lisp layer](https://develop.spacemacs.org/layers/+lang/emacs-lisp/README.html#debugging) provides nice keybindings for edebugging).

Finally, usually to `fix` your `.spacemacs.env` file, you can run `M-x spacemacs/force-init-spacemacs-env` (using just this, might have already fixed the issue).

If you find any weird behavior than please report here. Also, if you have any suggestions for improving [the documentation on environment variables and PATH](https://develop.spacemacs.org/doc/DOCUMENTATION.html#environment-variables-and-path) then they are welcome too.

About `exec-path-from-shell`, I guess you first have to install the package by adding it to your `dotspacemacs-additional-packages`.

**Comment by Martinsos** [comment]
@dalanicolai thanks for the response!

> then it takes the values of PATH variables from spacemacs-env-vars-file (i.e. .spacemacs.env) and prepends them to the exec-path, while again removing the duplicates. It removes duplicates by deleting duplicates from the end after prepending (using cl-remove-duplicates with :from-end t).
-> this part is the problem I believe, since it can result with /usr/bin moving from the end of the path to the start of the path, and that is exactly what happened to me.

I will give a very simplified example of what happened to me:

1. Let's say I have `PATH=/usr/bin` on our machine.
2. .spacemacs.env is generated based on this and it has `PATH=/usr/bin` inside.
3. All works fine, exec-path is `/usr/bin`.
4. After some time, I decide to install Rust-lang on machine. While installing Cargo (Rust's package manager), what Cargo does is add a line of code to .bash_profile that modifies PATH to be `/home/martin/.cargo/bin:/usr/bin`. Order is important here -> it ensures that during development we use rust toolchain binaries installed by Cargo, instead of system-wide rust binaries which are possibly there for other packages that might need them, not for development.
5. Now, spacemacs sees `PATH=/home/martin/.cargo/bin:/usr/bin` coming from the shell, but it has `PATH=/usr/bin` in .spacemacs.env, and due to the algorithm from above that spacemacs uses to build `exec-path`, the result is `exec-path = /usr/bin:/home/martin/.cargo/bin`.
6. Problem now occurs, if there are binaries with same name in /usr/bin as in cargo path.  In my case, because spacemacs was due to this using wrong version of Rust toolchain binaries, and error messages I was getting from LSP and rust-analyzer did not make that clear to me, it took me quite some time and only with help from @lebensterben did I manage to figure out the cause. First I needed to somehow figure out that wrong version of binaries might be the problem. Then I got confused because taking a look at PATH in my shell showed that it is correct and giving precedence to local binaries. I also tried then using Visual Studio Code, and everything was working correctly there. Only at that point was I sure problem is somewhere in spacemacs. And even now when I learned what the problem is, I still don't know how to prevent it in the future or solve it -> I solved it by removing the system installation of Rust because it turned out to be redundant in my case, but that shouldn't be the solution. And manually editing the .spacemacs.env to manipulate the PATH also feels wrong -> that is the purpose of it then?

What I am trying to argue for here is that:
- this is unexpected behaviour that is inconsistent with what other popular editors do or what one would normally expect.
- it is hard to figure out / debug.
- it can easily happen to anybody -> you just need to add smth in front of your PATH and you might have a problem.
- it is not clear how to avoid / fix it even when you know about it (at least in my case).

I think a big thing would be figuring out how to refactor that algorithm to ensure that order of items in PATH is preserved. I can see one tricky situation though: what if .spacemacs.env PATH contains some path that shell PATH does not contain? Should that one go to the start of exec-path or at the end? At start sounds problematic as it can again cause the unexpected behavior. But even putting it at the end could cause unexpected behaviour (if you are not aware of .spacemacs.env), since I might have deleted that path from shell PATH for a reason but then spacemacs adds it again. This is a separate problem really -> existence of .spacemacs.env is unexpected behaviour in general, if you are not aware of it (and I was not till now, although I have used spacemacs for last couple of years and even contributed before).

Personally I concluded that not using .spacemacs.env is the probably the best option for me, since I don't understand the benefits of it while I can easily imagine encountering similar problems in the future if I forget that .spacemacs.env is freezing/modifying my env vars.
I however haven't figure out yet how to do it, as I explained above. I wasn't clear about it but I did add `exec-path-from-shell` to `dotspacemacs-additional-packages`, however that didn't help with the error. I wonder if maybe that package is not loaded early enough to be used in `dotspacemacs/user-env ()`?

**Comment by dalanicolai** [comment]
@Martinsos Thanks for the detailed explanation. Personally, I am also not sure if using `.spacemacs.env` should be the preferred default. Also, the elisp manual states  (`SPC h j` `elisp` `i` `exec-path`) "Generally, you should not modify ‘exec-path’ directly.  Instead, ensure that your ‘PATH’ environment variable is set appropriately before starting Emacs.  Trying to modify ‘exec-path’ independently of ‘PATH’ can lead to confusing results." However, there is probably some good argument for using the env file also.

Anyway, about the current behavior, I think it could be considered to be a bug. I did not test or look into it more, but I guess it probably gets solved by simply `nreverse` the `env-vars` in the `dolist` within the `load-env-vars-set-env` function. About PATHs other than the 'shell PATH', I guess it is reasonable to prepend it to the 'shell PATH', as usually such entries are added to  verrule' the `shell PATH`.

I think [the docs](https://develop.spacemacs.org/doc/DOCUMENTATION.html#environment-variables-and-path) explain the behavior correctly, but the explanation does not look very beginner-friendly.

Strange that adding the `exec-path-from-shell` to `dotspacemacs-additional-packages` does not work there, because over here, the `exec-path-from-shell-initialize` command is available in `user-config` after simply doing that.

Have you tried to edebugging it b.t.w.? Learning about edebug is really useful, and it is almost no work. In essence, you instrumentalize a function by pressing `SPC u , e f` while the cursor is somewhere within it. Then you have to call the function somehow, and you can use `s` to step through it (however, I still have to figure out how to quickly step over a cycle in a loop, like in `dolist`).

**Comment by Martinsos** [comment]
While I didn't look into the elisp code (since my elisp knowledge is pretty basic), the easiest improvement would probably be just ensuring that when paths from .spacemacs.env PATH are being added to the shell PATH, if they already exist in shell PATH, that shell PATH should not change at all. Right now those paths get moved to the front and that causes issues.

Second thing might be ensuring that even if they are not duplicates, they still don't get added to the front, as that could also be confusing / unexpected. But this is less clear as to what is the right choice -> it is all about what the user expects from .spacemacs.env PATH to do. The biggest problem is if they don't know about it, I guess.

When reading docs:

> By default, the function dotspacemacs/user-env only calls the function spacemacs/load-spacemacs-env which loads the environment variables from the file ~/.spacemacs.env. This file is automatically created for you by Spacemacs and it is initialized with the environment variables of your system as well as the environment variables of your default shell.

I actually conclude that .spacemacs.env is first time created based on the system/shell env vars, but then spacemacs reads env vars only from that file. Docs don't mention anything about also loading env vars from the shell and then combining them with those from the .spacemacs.env (which does happen for PATH).

There are docs in the .spacemacs.env itself, which do mention that PATH is a special case:

> # PATH is a special case: all PATH settings are read, each non-duplicate
# directory entry is prepended to the `exec-path' variable, and then PATH is
# set to the final value of `exec-path'.

and they say that non-duplicate directory entries are prepended to the `exec-path` variable, so that is an expected behaviour (although can still be problematic in my opinion), however they don't say that duplicate directory entries will be moved to the start of the `exec-path`, so that would be an unexpected behaviour then.

Thanks for advice on using manual approach! So the thing is that I was putting `(exec-path-from-shell-initialize)` inside `(defun dotspacemacs/user-env ()`, and that didn't work. However now when I put it in `user-config`, it works, so that is great!

However, I then tried removing it completely, so no call to `(exec-path-from-shell-initialize)`, and even with that my exec-path is correctly set! Actually, when I use `(exec-path-from-shell-initialize)`, my exec-path contains two times the PATH, while if I remove it, it contains exactly the contents of path. So I am wondering now if I should just not do anything at all, since that seems to be the most correct? Just remove loading of spacemacs.env and that is it, no additional calls to `(exec-path-from-shell-initialize)`?

**Comment by Martinsos** [comment]
Oh and thanks about debugging tips, I never used it in elisp, and it seems I won't need it here, but it will be useful for the future!

**Comment by dalanicolai** [comment]
Ah, I thought I had read all these things in the docs, but I think I have read it also in that file you are quoting from then. Well, if you like, then you can always assist in updating the docs. Otherwise, it will only happen when some other volunteer finds some time and energy for it (the group of maintainers is really quite small, and lebensterben is doing so much work already. I am also no maintainer myself, I am just assisting them a little). But creating the detailed reports is also already very helpful, users can/should use these 'issues' as docs also.

As mentioned in the Emacs manual, (in the same section as when pressing `SPC h j elisp i exec-path`), the `exec-path` initializes its value from the `PATH` environment variable. I guess it means the PATH in the `process-environment`, which according to the answer [here}(https://emacs.stackexchange.com/a/57640/26163), gets initialized like the 'initial-environment. So I guess indeed, letting just Emacs do the work, might be the best default for most users (or at least for beginning users).
If you are using bash_profile already for setting your environment, then `exec-path-from-shell-initialize` does not really add anything (you can read the description of what the package does on it website).



> Oh and thanks about debugging tips, I never used it in elisp, and it seems I won't need it here, but it will be useful for the future!

I guess it will be useful indeed. You will find that Emacs provides a great lisp, and quite powerful, (e)lisp ecosystem...

**Comment by lebensterben** [comment]
@Martinsos 
What's the value of PATH in the variable `initial-environment`?

**Comment by lebensterben** [comment]
It's also good to know what's your login shell.
Is it bash?

**Comment by Martinsos** [comment]
@dalanicolai thanks for explaining further -> right, so in that case it makes sense that I just let emacs do its thing, since I am on Linux and using `bash`.

Some action items I can think of:
1. Updating docs to make it a bit clearer what is happening with the PATH when using spacemacs.env. Also, making it clearer how to now use spacemacs.env.
2. Updating the algorithm spacemacs.env uses to construct exec-path, so that it doesn't change the order of dirs in the path.
3. Remove spacemacs.env as a default option to avoid confusion for beginners.

(1) I could probably do relatively easily, (2) I might be able to do but it would probably take me a lot of time due to not knowing elisp well + not sure how to run and test it, while (3) is obviously a controversial move and I am imagining it might not be accepted as an option -> I do wonder though what are the benefits of .spacemacs.env and if they really outweigh the unexpected behaviour it potentially introduces.

@lebensterben 
Value of PATH in `initial-environment`: `"PATH=/home/martin/.nix-profile/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/martin/.cargo/bin:/home/martin/.cabal/bin:/home/martin/.ghcup/bin:/home/martin/.local/share/gem/ruby/3.0.0/bin:/home/martin/.local/bin:/home/martin/.nix-profile/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/martin/opt"`

This is the same as PATH defined in my .bash_profile.

I am using `bash`, and I am on Linux (Archlinux).

NOTE: I have a ton of these duplicate nix dirs in my PATH, but that is happening somewhere on my system, I have to admit I have no idea where is that being added though, but it doesn't hurt so I didn't bother with it for now.

**Comment by lebensterben** [comment]
@Martinsos 
Please attach the output of `bash -lc env` and `bash -ic env` respectively.

**Comment by Martinsos** [comment]
`bash -lc env`
```shell
PATH=/home/martin/.cabal/bin:/home/martin/.ghcup/bin:/home/martin/.local/share/gem/ruby/3.0.0/bin:/home/martin/.local/bin:/home/martin/.nix-profile/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/martin/.nvm/versions/node/v15.14.0/bin:/home/martin/.cabal/bin:/home/martin/.ghcup/bin:/home/martin/.local/share/gem/ruby/3.0.0/bin:/home/martin/.local/bin:/home/martin/.nix-profile/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/martin/.nix-profile/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/martin/.cargo/bin:/home/martin/.cabal/bin:/home/martin/.ghcup/bin:/home/martin/.local/share/gem/ruby/3.0.0/bin:/home/martin/.local/bin:/home/martin/.nix-profile/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/martin/opt:/home/martin/opt:/home/martin/opt
```
And here is formatted:
```
/home/martin/.cabal/bin
/home/martin/.ghcup/bin
/home/martin/.local/share/gem/ruby/3.0.0/bin
/home/martin/.local/bin
/home/martin/.nix-profile/bin
/home/martin/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/home/martin/.nvm/versions/node/v15.14.0/bin
/home/martin/.cabal/bin
/home/martin/.ghcup/bin
/home/martin/.local/share/gem/ruby/3.0.0/bin
/home/martin/.local/bin
/home/martin/.nix-profile/bin
/home/martin/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/home/martin/.nix-profile/bin
/home/martin/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/home/martin/.cargo/bin
/home/martin/.cabal/bin
/home/martin/.ghcup/bin
/home/martin/.local/share/gem/ruby/3.0.0/bin
/home/martin/.local/bin
/home/martin/.nix-profile/bin
/home/martin/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/home/martin/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/usr/local/bin
/usr/bin
/usr/local/sbin
/usr/bin/site_perl
/usr/bin/vendor_perl
/usr/bin/core_perl
/home/martin/opt
/home/martin/opt
/home/martin/opt
```

`bash -ic env`
```sh
PATH=/home/martin/.nvm/versions/node/v15.14.0/bin:/home/martin/.cabal/bin:/home/martin/.ghcup/bin:/home/martin/.local/share/gem/ruby/3.0.0/bin:/home/martin/.local/bin:/home/martin/.nix-profile/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/martin/.nix-profile/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/martin/.cargo/bin:/home/martin/.cabal/bin:/home/martin/.ghcup/bin:/home/martin/.local/share/gem/ruby/3.0.0/bin:/home/martin/.local/bin:/home/martin/.nix-profile/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/martin/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/martin/opt:/home/martin/opt
```
And here is formatted:
```sh
/home/martin/.nvm/versions/node/v15.14.0/bin
/home/martin/.cabal/bin
/home/martin/.ghcup/bin
/home/martin/.local/share/gem/ruby/3.0.0/bin
/home/martin/.local/bin
/home/martin/.nix-profile/bin
/home/martin/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/home/martin/.nix-profile/bin
/home/martin/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/home/martin/.cargo/bin
/home/martin/.cabal/bin
/home/martin/.ghcup/bin
/home/martin/.local/share/gem/ruby/3.0.0/bin
/home/martin/.local/bin
/home/martin/.nix-profile/bin
/home/martin/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/home/martin/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/usr/local/bin
/usr/bin
/usr/local/sbin
/usr/bin/site_perl
/usr/bin/vendor_perl
/usr/bin/core_perl
/home/martin/opt
/home/martin/opt
```

For login console `-lc` I get these additional paths on front, I believe that is because I source `.bashrc` in it, so some stuff is repeated? Anyway, it shouldn't hurt.
