### ISSUE TITLE
Some hooks do not reliably execute unless the debugger is active

### ISSUE THREAD

**Issue by codaraxis** [syl20bnr/spacemacs#15282]
#### Description :octocat:
Some (Org mode?) hooks do not reliably execute; in fact, these hooks seem to get reliably skipped. However, if an operation that would trigger such a hook is run with the debugger, either using `debug-on-entry` or `debug-on-variable-change`, the hooks execute correctly.

I've observed this problem for about a year, but assumed it was just a bug in my older version of Spacemacs. Unfortunately, it persists even now that I've pulled a new build and updated all the packages. I even re-downloaded and installed all the packages from scratch by removing `~/.emacs.d/elpa`.

##### Example 1: Org Todo Hooks When Using Org Edna
- Start Emacs
    - The Org edna package should be installed and `dotspacemacs/user-config` should include:
        ```
        (require 'org-edna)
        (org-edna-mode)
        ```
    - Task states should be configured to log when set
- In an Org mode file, create a sample task:
    ```
    * TODO Test
      :PROPERTIES:
      :TRIGGER:  self todo!(TODO)
      :END:
      :LOGBOOK:
      - State "TODO"       from              [2022-01-20 Thu 14:56]
      :END:
    ```
- Mark the task as DONE

##### Example 2: Org Agenda Hook to Start in Evil Emacs State
- Start Emacs 
    - The `dotspacemacs/user-config` should have the following hook:
        ````
        (add-hook 'org-agenda-mode-hook 'evil-emacs-state)
        ````
- Find an Org mode file
- `C-c a a` to start Org Agenda

*Observed behaviour:* :eyes: :broken_heart:

##### Example 1: Org Todo Hooks When Using Org Edna
Only the final todo state change is logged.
```
* TODO Test
  :PROPERTIES:
  :TRIGGER:  self todo!(TODO)
  :END:
  :LOGBOOK:
  - State "TODO"       from "DONE"       [2022-01-20 Thu 15:37]
  - State "TODO"       from              [2022-01-20 Thu 14:56]
  :END:
```

If I add additional triggers, e.g. `self todo!(TODO) todo!(NEXT)`, only the final change to NEXT is logged --- that is to say, I can add as many comopnents to the trigger as I like, but only the final one is actually logged. 

##### Example 2: Org Agenda Hook to Start in Evil Emacs State
Org Agenda starts in Evil normal mode

*Expected behaviour:* :heart: :smile:

##### Example 1: Org Todo Hooks When Using Org Edna
Each todo state change should be logged.
```
* TODO Test
  :PROPERTIES:
  :TRIGGER:  self todo!(TODO)
  :END:
  :LOGBOOK:
  - State "TODO"       from "DONE"       [2022-01-20 Thu 15:37]
  - State "DONE"       from "TODO"       [2022-01-20 Thu 15:37]
  - State "TODO"       from              [2022-01-20 Thu 14:56]
  :END:
```

##### Example 2: Org Agenda Hook to Start in Evil Emacs State
Org Agenda starts in Emacs mode.

#### System Info :computer:
- OS: windows-nt
- Emacs: 28.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. ca93e28a9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp finance git javascript html helm markdown multiple-cursors org
                 (ranger :variables ranger-show-preview nil)
                 spell-checking syntax-checking treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS PDUMPER

#### Backtrace :paw_prints:
```

```

**Comment by dalanicolai** [comment]
Have you tried printing some message from the hook and check the messages buffer? It seems unlikely to me that the hooks get skipped depending on the debug 'watchers' being active...

**Comment by lebensterben** [comment]
please report it to the upstream.
We've nothing to do with the hook facilities.
