### ISSUE TITLE
how to disable and enable lsp

### ISSUE THREAD

**Issue by emacs18** [syl20bnr/spacemacs#15283]
I would like to see something like `turn-off-lsp` and `turn-on-lsp` so that I can disable/enable lsp when I need to.

By disable I mean that lsp does not do anything in any buffer whether it currently exist or yet to be created. I don't want any resources (cpu or memory) used up by lsp for periods of times when I need to do some heavy editing of C++ files. With LSP enabled, it is just too painful slow to get any editing done. Following is what I have come up with so far.

```elisp
(defvar my-saved-c-c++-backend nil)

(defun my-turn-off-lsp ()
  (interactive)

  ;; prevent spacemacs from enabling lsp by calling lsp-deferred
  (setq my-saved-c-c++-backend c-c++-backend)
  (message "c-c++-backend was %s" c-c++-backend)
  (setq c-c++-backend nil)

  ;; Remove advice added by lsp
  (advice-remove 'set-visited-file-name #'lsp--on-set-visited-file-name)

  ;; Don't know the exact syntax of this variable.  It must be a list.
  ;; So I tried adding "/tmp" which seem to get the job done.
  (setq lsp-enabled-clients '("/tmp")))

(defun my-turn-on-lsp ()
  (interactive)
  (setq c-c++-backend my-saved-c-c++-backend)
  (advice-add 'set-visited-file-name :around #'lsp--on-set-visited-file-name)
  (setq lsp-enabled-clients nil))
```

It seems to get the job done in that emacs is not slowed down by lsp. I call `my-turn-off-lsp` before doing heavy editing, then call `my-turn-on-lsp` when I'm done with my editing work.

This is a hack. I'm sure that someone who knows how lsp works can come up with far better soution to globally disable/enable lsp.

I am also trying to get help from discord channel for lsp at https://discord.com/channels/789885435026604033/789890777626968107

**Comment by lebensterben** [comment]
Can you just set directory local variable c-c++-backend?

**Comment by emacs18** [comment]
Creating `.dir-locals.el` file with `((c++-mode . ((c-c++-backend . nil))))` in it does prevent lsp from being enabled on new C++ files loaded.  However it does disable lsp in buffers that have already enabled it.

**Comment by lebensterben** [comment]
@emacs18 
That's true. You need to shut down lsp or reopen the buffer.

**Comment by emacs18** [comment]
Following adds code to turn lsp off and on within pre-existing buffers.
```elisp
(defvar my-saved-c-c++-backend nil)

(defun my-disable-lsp-temporarily ()
  "Disable lsp in current buffer if it was enabled.  Also set a buffer local
variable for later use by `my-reenable-lsp' to re-enable lsp."
  (when lsp-mode
    (lsp-disconnect) ; disable lsp
    (setq-local my-lsp-disabled t)))

(defun my-reenable-lsp ()
  "If current buffer was disabled by `my-disable-lsp-temporarily' as indicated
by `my-lsp-disabled' buffer local variable, then enable lsp in current buffer."
    (when (and (bound-and-true-p my-lsp-disabled) (not lsp-mode))
      (lsp)
      (setq-local my-lsp-disabled nil)))

(defun my-turn-off-lsp ()
  "Disable lsp on all existing buffers as well new buffers to be created.  Thus
lsp will be disabled for all buffers until `my-turn-on-lsp' is called later on."
  (interactive)

  ;; prevent spacemacs from enabling lsp by calling lsp-deferred
  (setq my-saved-c-c++-backend c-c++-backend)
  (message "c-c++-backend was %s" c-c++-backend)
  (setq c-c++-backend nil)

  ;; Remove advice added by lsp
  (advice-remove 'set-visited-file-name #'lsp--on-set-visited-file-name)

  ;; Disable lsp in all buffers that have it enabled.  Also note which buffers
  ;; are disabled so that we can re-enable them later on.
  (mode-local-map-file-buffers #'my-disable-lsp-temporarily)
   
  ;; Don't know the exact syntax of this variable.  It must be a list.
  ;; So I tried adding "/tmp" which seem to get the job done.
  (setq lsp-enabled-clients '("/tmp")))

(defun my-turn-on-lsp ()
  "Re-enable lsp which was disabled by prior call of `my-turn-off-lsp'.
Lsp is re-enabled on all existing buffers if it was disabled earlier."
  (interactive)
  (setq c-c++-backend my-saved-c-c++-backend)
  (advice-add 'set-visited-file-name :around #'lsp--on-set-visited-file-name)
  (setq lsp-enabled-clients nil)
  (mode-local-map-file-buffers #'my-reenable-lsp))
```

**Comment by lebensterben** [comment]
I think they are good addition to LSP layer.

But what's the difference between this and "SPC b d" for shuting down the LSP server?

**Comment by emacs18** [comment]
`, w d` shuts down lsp for current buffer.  However lsp is started up again on new files loaded.
If there is a way to tell lsp "do not start automatically; start only when I tell you to", then that would solve part of the problem.

**Comment by lebensterben** [comment]
I like this toggle. Probably "SPC m T" is a good binding. PR is welcomed.

**Comment by emacs18** [comment]
I am not yet comfortable with this.  It feels like to me that there is a better way.  I hope to be examining lsp code to learn how it is setup.  Hopefully I can come up with something better or lsp experts on the discord channel can shed light on this topic.

**Comment by nigredo-tori** [comment]
@emacs18, I've done i write-up on a similar pain in #15334, with an extremely straightforward solution, but I'm not sure whether the simplest solution would be good enough for everyone, so I'm looking for some guinea pigs. :smile: Could you please disable your workaround, and instead try using [this Spacemacs branch](https://github.com/nigredo-tori/spacemacs/tree/15334-dont-autostart-lsp-server)? I'm interested to know whether it fits your use case.

What this does is it requires you to **explicitly** launch LSP servers for the workspaces you want (with `, w s`). So if you need to do some heavy editing in a workspace, you can open it without an LSP connection (or shut down the existing server with `, w q`), and open/edit files without the noise. I understand that this is not 100% what you had in mind, but could you please give it a go?

**Comment by emacs18** [comment]
No problem.  I am willing to test any solution that could help me.  My use case is as follows.  I want lsp to be enabled on all new buffers at first.  I then discover I need to go and fix dozens if not hundreds of C++ files to fix warnings, or rename symbols, etc.  When I start this editing work, then I want lsp to be disabled on all buffers that I may edit which includes buffers with lsp already enabled.  So what I need is to first disable lsp in all existing buffers, and also to prevent lsp from being enabled on all new buffers to be created.  
When I'm done editing, then I want to go back to the old state of things where lsp is enabled by default.
