### ISSUE TITLE
Eslint does not work.

### ISSUE THREAD

**Issue by sleroq** [syl20bnr/spacemacs#15298]
#### Description :octocat:

When I open any .ts file I get this message:\
`Server eslint:564874/starting exited with status exit(check corresponding buffer for details). Do you want to restart it? (y or n)`

#### Reproduction guide :beetle:
- Start Emacs
- Set this configurations for typescript layer:
```lisp
 (typescript :variables
              typescript-linter 'eslint
              typescript-backend 'lsp)
```
- Optionally set path for eslint server:
```lisp
(defun dotspacemacs/user-env ()
  (spacemacs/load-spacemacs-env)
       (setq lsp-eslint-server-command
               '("node" 
                 "/home/sloq/Applications/vscode-eslint/server/out/eslintServer.js" 
                 "--stdio"))
)
```
- Open any typescript project

*Observed behaviour:* :eyes: :broken_heart:

This message: `Server eslint:564874/starting exited with status exit(check corresponding buffer for details). Do you want to restart it? (y or n)`

Logs from \*eslint::stderr\*:

```
/home/sloq/Applications/vscode-eslint/server/out/eslintServer.js:242
        return ruleId2Meta.get(ruleId)?.docs?.url;
                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

Process eslint stderr finished
```
My output of `node --version`: v16.13.2

I can start eslintServer.js manually without any errors by running\
`node ~/Applications/vscode-eslint/server/out/eslintServer.js --stdio`

*Expected behaviour:* :heart: :smile:

Eslint works out of the box

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 42dc30e33)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python lsp speed-reading
				(shell :variables shell-default-height 30 shell-default-position 'bottom)
				(typescript :variables indent-tabs-mode t tab-width 2 typescript-indent-level 2 typescript-linter 'eslint typescript-backend 'lsp)
				markdown html multiple-cursors better-defaults emacs-lisp json git helm auto-completion spell-checking syntax-checking version-control treemacs tabs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
The bug message clear shows that it's an eslint bug.

**Comment by lebensterben** [comment]
Cannot reproduce this bug with your configurations.
Please retry with all your packages updated.
