### ISSUE TITLE
Unable to set leader keys for cuda-mode

### ISSUE THREAD

**Issue by suryakiran** [syl20bnr/spacemacs#15304]
#### Description :octocat:
Unable to set leader keys for cuda-mode

#### Reproduction guide :beetle:
- Start Emacs
- I have declared the prefix for user commands in cuda-mode using
  (spacemacs/declare-prefix-for-mode 'cuda-mode "mo" "custom")
  And tried to add leader keys for this mode using
  (spacemacs/set-leader-keys-for-major-mode 'cuda-mode "mof 'my-cuda-customization-function)
  But when I hit SPC m in cuda-mode, I'm not seeing the custom menu created.
- The same setup for C++ mode is working fine.

*Observed behaviour:* :eyes: :broken_heart:
No custom menu is seen

*Expected behaviour:* :heart: :smile:
Expected to see custom commands in cuda-mode (similar to c++ mode)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 42dc30e33)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(imenu-list html
            (c-c++ :variables c-c++-enable-clang-format-on-save t c-c++-backend 'lsp-clangd c-c++-default-mode-for-headers 'c++-mode)
            (helm :variables helm-candidate-number-limit 200 helm-buffer-max-length 50 helm-grep-max-length-history 200)
            (lsp :variables lsp-restart 'ignore lsp-response-timeout 30)
            (python :variables python-backend nil python-formatter 'yapf python-format-on-save t)
            (json :variables json-fmt-tool 'web-beautify json-fmt-on-save t json-backend nil)
            (shell-scripts :variables shell-scripts-backend nil)
            org cmake colors csv emacs-lisp ess go gpu java javascript multiple-cursors protobuf scala sql tabs templates typescript themes-megapack spacemacs-modeline spacemacs-layouts treemacs yaml skg rez erisk mycpp buffers)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
"m" is reserved for major modes.
try a different prefix.

**Comment by suryakiran** [comment]
I was using "mo" for custom commands under major mode
For c++-mode this works fine
This doesn't work with cuda files. The major mode is cuda-mode for cuda files. 

So, 
`(spacemacs/declare-prefix-for-mode 'c++-mode "mo" "custom")`
works fine for `c++-mode`

But
`(spacemacs/declare-prefix-for-mode 'cuda-mode "mo" "custom")`
doesn't work for `cuda-mode`

Also, after your suggestion, I tried other keys in cuda-mode. Nothing works.

**Comment by lebensterben** [comment]
```elisp
(spacemacs/declare-prefix-for-mode 'cuda-mode "mo" "custom")
(spacemacs/set-leader-keys-for-major-mode 'cuda-mode "of 'my-cuda-customization-function)
```

Works for me.

**Comment by suryakiran** [comment]
Hmm.. 
After declaring prefix and set leader keys, the mode-map was showing correctly.

`spacemacs-cuda-mode-map` shows the added keys and functions

But, when in cuda file, when I type `SPC m`
I'm getting the error `which-key: There are no keys to show`

**Comment by lebensterben** [comment]
@suryakiran 
copy and paste my code. they're not the same as yours.
