### ISSUE TITLE
Space bar is broken in eaf layer browser

### ISSUE THREAD

**Issue by James-Hanson** [syl20bnr/spacemacs#15306]
#### Description :octocat:
Pressing the space bar in eaf layer browser does nothing and throws an error. I've tested this on a totally fresh Ubuntu 20.04 installation. I installed Emacs with snap.

#### Reproduction guide :beetle:
- Start Emacs
- Add eaf to layers in .spacemacs file
- Restart Emacs to install
- Run M-x eaf-install
- Add all applications
- Open browser with SPC a a b o
- Open any website
- Press space bar

*Observed behaviour:* :eyes: :broken_heart:
Pressing space bar does nothing and throws an error:
```
apply: Wrong type argument: stringp, (epc-error "EPC-ERROR: No such method : call_function")
```

*Expected behaviour:* :heart: :smile:
Pressing space bar opens the menu and does not throw an error.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 0ba8aa194)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs eaf)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
Confirmed.
But I'm not able to do any debugging.
This package has never worked properly on my computer with 2 different OS.

**Comment by Vivien-lelouette** [comment]
Hello,

I am a Doom user, but I had the same issue.
Looking at the eaf source code, they are not calling the "call_function" but the "execute_function" instead.

The code given to doom users for the space bar to work is the following:
```
(define-key key-translation-map (kbd "SPC")
    (lambda (prompt)
      (if (derived-mode-p 'eaf-mode)
          (pcase eaf--buffer-app-name
            ("browser" (if  (string= (eaf-call-sync "call_function" eaf--buffer-id "is_focus") "True")
                           (kbd "SPC")
                         (kbd eaf-evil-leader-key)))
            ("pdf-viewer" (kbd eaf-evil-leader-key))
            ("image-viewer" (kbd eaf-evil-leader-key))
            (_  (kbd "SPC")))
        (kbd "SPC"))))
```

My fixed code is the following:
```
(define-key key-translation-map (kbd "SPC")
    (lambda (prompt)
      (if (derived-mode-p 'eaf-mode)
          (pcase eaf--buffer-app-name
            ("browser" (if (eaf-call-sync "execute_function" eaf--buffer-id "is_focus")
                           (kbd "SPC")
                         (kbd eaf-evil-leader-key)))
            ("pdf-viewer" (kbd eaf-evil-leader-key))
            ("image-viewer" (kbd eaf-evil-leader-key))
            (_  (kbd "SPC")))
        (kbd "SPC"))))
```

Note that the "stringp=" seems to be unecessary now.

Hope this can help you solve this issue for spacemacs !

Best Regards.

**Comment by TerryTsao** [comment]
Upstream wiki is outdated, while eaf APIs tend to be aggressively updated & live at HEAD. The workaround works perfectly. I'm willing to create PR (and fix upstream Wiki page) soon.
