### ISSUE TITLE
org-roam buffer is messed-up. Titles and contents are not in the right order

### ISSUE THREAD

**Issue by kuochang** [syl20bnr/spacemacs#15309]
Hi I am a noob to spacemacs. Recently I enabled "org-enable-roam-support" for org-roam. When I toggle org-roam buffer(backlinks window), the titles and contents are not in the right order(please see the attachment. Title "test1" is at the bottom but its content is at the top...). How can I make it right?
<img width="812" alt="截屏2022-02-04 上午10 43 02" src="https://user-images.githubusercontent.com/58517668/152464984-5ba1c071-1df5-48ab-aab6-d93ae8fa92ac.png">
?

**Comment by lebensterben** [comment]
please follow the issue template and attach required information.

**Comment by kuochang** [comment]
Opps! My bad... I'll follow the issue template and attach the required information later today. Thanks for the response.

**Comment by kuochang** [comment]
Here you are. I am stuck now. Please help. Thanks!
#### Description :octocat:

The Spacemacs bundled org-roam can't display the correct order and place of the content in the org-roam buffer(backlinks window). For example, in the back links window, the title C content displays under title A, The title A content displays above title C, and title B displays under "Backlinks". In short, it's messed up...

#### Reproduction guide :beetle:
- Start Emacs
- Add  org (org :variables org-enable-roam-support t) in the dotspacemacs-configuration-layers
- Add (setq org-roam-completion-everywhere t) in the dotspacemacs/user-init
- add (setq org-roam-directory (file-truename "~/org-roam"))   (org-roam-db-autosync-mode) in the dotspacemacs/user-config
- Restart spaceemacs.
- Press SPC a o r f to create title A, title B, title C notes respectively. Wrote the contents associated with those notes. Please note the contents for title B and title C both mention title A.
- Go to title A note. Press , r l(org-roam-buffer-toggle) to open org roam buffer(show backlinks).

*Observed behaviour:* :eyes: :broken_heart:
- The result is shown as attached picture.
<img width="818" alt="截屏2022-02-04 下午9 42 56" src="https://user-images.githubusercontent.com/58517668/152542738-eb889fe7-e209-4e30-b2ed-bc3a0e405576.png">


*Expected behaviour:* :heart: :smile:
All the contents to displayed under their titles, so I won't mis-undertand the content belong to which note in org roam buffer(backlinks window).

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. ce0becb72)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp helm lsp markdown multiple-cursors org
                 (org :variables org-enable-roam-support t)
                 python eww pdf evil-snipe spell-checking
                 (spell-checking :variables enable-flyspell-auto-completion nil)
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 syntax-checking treemacs)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP


#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by kuochang** [comment]
New findings today: If I executed org-roam-buffer-display-dedicated and chose the note, the org roam buffer can be display correctly as attached. However, when I executed org-roam-buffer-toggle, the same issue happened. Any clue?
<img width="1440" alt="截屏2022-02-05 下午7 05 44" src="https://user-images.githubusercontent.com/58517668/152639498-265ddc41-f337-4bf1-ad83-485958699463.png">

**Comment by lebensterben** [comment]
Confirmed.

**Comment by lebensterben** [comment]
@kuochang 
I recommend to report this to upstream because we didn't do anything to org-roam except for setting a bunch of bindings.

**Comment by dr-hildi** [comment]
I found a fix/workaround in this thread: [Need to refresh every time I open the roam buffer (Spacemacs)
[Troubleshooting](https://org-roam.discourse.group/t/need-to-refresh-every-time-i-open-the-roam-buffer-spacemacs/2204/8). This fixed the problem for me. I hope this helps to identify the problem.

**Comment by lebensterben** [comment]
@dr-hildi 

Thanks. But other people in the same thread said it didn't fix the problem for him.

**Comment by abgruszecki** [comment]
This seems like the same issue I was encountering and fixed by patching an internal definition of org-roam : https://github.com/org-roam/org-roam/issues/2286

I'd expect that Spacemacs adds some hooks which make some functions (take a look at my description in the linked issue) unexpectedly move the point. I might look into this the next time the urge to tinker strikes me, but I'd be very happy if someone else could investigate it.
