### ISSUE TITLE
Recent files list is cluttered with org files

### ISSUE THREAD

**Issue by Luctins** [syl20bnr/spacemacs#15305]
#### Description :octocat:
Setting the variables `org-directory` and `org-agenda-files` opens all files under the folder as buffers on startup and this fills the recent files list with org files.

This probably has to do with indexing the TODO list that is shown on the startup buffer.

#### Reproduction guide :beetle:
- Start Emacs
- Check the recent files on the `*spacemacs*` buffer
- View the buffer list to see that many org buffers were opened.

*Observed behaviour:* :eyes: :broken_heart:
All org files under  `org-directory` are opened as buffers on startup

*Expected behaviour:* :heart: :smile:
The recent files list would contain recent files from the last session.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0206197b2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(systemd emacs-lisp treemacs multiple-cursors
		 (org :variables org-enable-roam-support t org-enable-trello-support t org-roam-v2-ack t org-roam-directory "~/org/roam/")
		 html
		 (c-c++ :variables c-c++-backend 'lsp-ccls)
		 javascript octave rust csv markdown yaml
		 (python :variables python-indent 4 python-indent-offset 4 indent-tabs-mode t tab-width 4)
		 lua helm auto-completion better-defaults git
		 (shell :variables shell-default-height 30 shell-default-position 'bottom)
		 spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```lisp
;; the content of the cited variables
(setq org-directory "~/org/"
      org-agenda-files '( "~/org/" ))
```

**Comment by lebensterben** [comment]
yes this is an issue for quite some time. Not sure if it's reported before.

**Comment by Luctins** [comment]
Can I filter the recent files list somehow? 

also could opening many org buffers cause startup performance issues?

**Comment by lebensterben** [comment]
a workaround is not to show the recent file but recent file by project.
