### ISSUE TITLE
Replace github recipes with melpa?

### ISSUE THREAD

**Issue by BenediktBroich** [syl20bnr/spacemacs#15312]
Hello,

Why are we using github recipes when there is a package on MELPA etc. ? What should we prefer?

Disclaimer: So i was replacing all installed emacs packages with the ones managed by nixos. I found some packages that are not in nixos. NixOS just uses package repositories like MELPA and import these to manage them in nix. So i searched for the missing packages. On that journey i found some packages that are in MELPA, but in spacemacs we still use the github recipe. I just was wondering why.

Packages:
- org-journal [spacemacs](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+emacs/org/packages.el#L49) [melpa](https://melpa.org/#/org-journal)
- desktop-environment [spacemacs](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+window-management/exwm/packages.el#L27) [melpa](https://melpa.org/#/desktop-environment)
- company-glsl [spacemacs](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/gpu/packages.el#L27) [melpa](https://melpa.org/#/company-glsl)
- ox-gfm [spacemacs](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+emacs/org/packages.el#L62) [melpa](https://melpa.org/#/ox-gfm)

**Comment by lebensterben** [comment]
except for the case of desktop-environment which is recently uploaded to melpa, all others are forks of the melpa packages.
