### ISSUE TITLE
(global-git-commit-mode t) not working

### ISSUE THREAD

**Issue by manuel-arguelles** [syl20bnr/spacemacs#15324]
#### Description :octocat:
(global-git-commit-mode t) not working

#### Reproduction guide :beetle:
- Set (require 'git-commit) and (global-git-commit-mode t) in dotspacemacs/user-config as described in the documentation.
- Start Emacs from a git repository as emacs .git/COMMIT_EDITMSG

*Observed behaviour:* :eyes: :broken_heart:
The buffer stays in Fundamental mode.

*Expected behaviour:* :heart: :smile:
The buffer mode should be git commit.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. d36615013)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(protobuf systemd csv python html
          (typescript :variables typescript-linter 'tslint typescript-backend 'lsp typescript-lsp-linter nil)
          auto-completion emacs-lisp git ivy markdown multiple-cursors
          (org :variables org-want-todo-bindings t)
          plantuml
          (spell-checking :variables spell-checking-enable-auto-dictionary t)
          syntax-checking treemacs
          (mu4e :variables mu4e-view-use-gnus t mu4e-enable-mode-line t)
          (lsp :variables lsp-ui-doc-enable nil lsp-ui-sideline-enable t lsp-file-watch-threshold 20000 lsp-clients-clangd-executable "/usr/bin/clangd-12" lsp-clients-clangd-args
               '("--clang-tidy" "--malloc-trim" "--header-insertion=never"))
          (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-backend 'lsp-clangd)
          debug themes-megapack shell shell-scripts
          (vue :variables vue-backend 'lsp)
          (node :variables node-add-modules-path t)
          (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
          pdf epub)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
@manuel-arguelles 
`git-commit-mode` is a minor mode. The major mode would still be `fundamental-mode`, `text-mode`, or any mode according to your `dotspacemacs-new-empty-buffer-major-mode`.

So it's normal to see them in your modeline instead of `git-commit-mode`.

The question is, is there any functionality or keybindings missing?

**Comment by manuel-arguelles** [comment]
Well I do have `dotspacemacs-new-empty-buffer-major-mode` configured to `'text-mode` (I think that's the default), but still the buffer is opened in `fundamental-mode` maybe I could set a hook to open it in `text-mode` based on the name of the file?

**Comment by lebensterben** [comment]
@manuel-arguelles 
Can I see your `.spacemacs`?

**Comment by manuel-arguelles** [comment]
@lebensterben sure https://termbin.com/gui5

**Comment by lebensterben** [comment]
@manuel-arguelles 
the .spacemacs file looks good.

Can you try "GIT_EDITOR=emaca git commit"? I want to know whether it's text-mode in graphical Emacs.

**Comment by manuel-arguelles** [comment]
both behave the same, Fundamental mode gets loaded. I could try with auto-mode-alist to try to link COMMIT_EDITMSG to text-mode?

**Comment by manuel-arguelles** [comment]
no, stand alone emacs

**Comment by manuel-arguelles** [comment]
same

**Comment by lebensterben** [comment]
this is really weird.

**Comment by manuel-arguelles** [comment]
I fully exit it and launch it again... Perhaps there a mode or layer getting in the way, let me see if I can try commenting most of them

**Comment by manuel-arguelles** [comment]
`git-commit-mode` is active according to `SPC h d m` the problems seems to be that the main mode stays in Fundamental instead of going to text-mode.

**Comment by manuel-arguelles** [comment]
ok, this is odd... If i reopen the file `C-x C-v` it loads the correct mode, could it be that the file gets opened before the configuration is fully evaluated?

**Comment by lebensterben** [comment]
@manuel-arguelles 
Try:
- backup your current ~/.spacemacs (`mv ~/.spacemacs{,.backup}`
- use the default [.spacemacs](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/.spacemacs.template) ( `mv ~/.emacs.d/core/templates/.spacemacs.template ~/.spacemacs`)
- Change [this line](https://github.com/syl20bnr/spacemacs/blob/d366150139c2c3fa8b743f502efccd542e7a6f3a/core/templates/.spacemacs.template#L82) to `'used-but-keep-unused`
- Change [this line](https://github.com/syl20bnr/spacemacs/blob/d366150139c2c3fa8b743f502efccd542e7a6f3a/core/templates/.spacemacs.template#L44) to `(git :variables global-git-commit-mode t`)
- Restart Emacs and re-test?

**Comment by manuel-arguelles** [comment]
It loads the helm-ls-git-commit mode

**Comment by lebensterben** [comment]
@manuel-arguelles 
Please recheck.
`helm-ls-git-commit` is the major mode of the window showing you the git difference.
Not the major mode of the window where you edit the commit message. What is its major mode?

**Comment by manuel-arguelles** [comment]
It's `helm-ls-git-commit` and doesn't look good (got a `$` at the end of every line), I'd try to backup my entire `.emacs.d` directory and retry from a fresh start.

**Comment by lebensterben** [comment]
I really cannot reproduce any of these.

Have you disabled your own added packages and hooks?

**Comment by xuhdev** [comment]
I've encountered the same problem. I resolved this by having the following in `user-config`:

```elisp
  (require 'magit)  ;; <----- Add this line!
  (require 'git-commit)
  (global-git-commit-mode t)
```

I'm not sure why though...
