### ISSUE TITLE
Bug: `f` motion command not working with d

### ISSUE THREAD

**Issue by fmardini** [syl20bnr/spacemacs#1532]
Hello,
Fresh install
`vfa` works and highlights to the next a
`dfa` doesn't work; deletes character at point and then moves to the a

Thanks

**Comment by tuhdo** [comment]
Do you press it fast? If so, `df` activates escape to exit from all modes and it won't execute the intended command.

**Comment by metamorph** [comment]
I've got the same behavior here. Even if I press 'd' then 'f' really "slow" the effect is that the current char is deleted.

Also note that `dt[char]` works as expected.

**Comment by tuhdo** [comment]
`dfa` works for me: delete from current point up to `a`. Or, do you mean that `a` should not be deleted?

**Comment by metamorph** [comment]
Seems to be related to evil-escape for me. If I disable the `evil-escape` package the `df` motion works as expected.

**Comment by fmardini** [comment]
Same here disabling evil-escape solves the issue

**Comment by syl20bnr** [comment]
Fixed upstream in version 2.25 of evil-escape, it will be available in a couple of hours in MELPA.

**Comment by icambron** [comment]
Confirmed fixed.
