### ISSUE TITLE
Haskell and/or LSP layer install instructions need improvement

### ISSUE THREAD

**Issue by FuzzyWuzzyBMP** [syl20bnr/spacemacs#15335]
I believe the currently preferred method of installing Haskell and its tools is via ghcup (https://haskell-language-server.readthedocs.io/en/latest/installation.html). However, since, as I understand, spacemacs caches environment variables in `.spacemacs.env`, its version of the system `PATH` does not contain the updates from ghcup, so it does not find the LSP server executable.

After much tinkering, I figured out that the `PATH` was the issue, and that starting emacs from the terminal resulted in a working Haskell LSP mode. Then, some combination of

- Starting emacs from the terminal instead of the Gnome UI
- Calling `SPC f e E` (Refresh env. variables) from the terminal-started emacs
- Calling  `SPC f e C-e` (Recreate env. variables file) from the terminal-started emacs

was apparently successful in updating the `PATH` as seen by spacemacs, and from then on LSP functioned even when starting emacs from the GUI and not the terminal.

This should probably be documented somewhere in the LSP or Haskell layer documentation, so that others may be spared my pain. Currently, https://www.spacemacs.org/layers/+lang/haskell/README.html merely says that "First of all make sure that your `$PATH` contains the installation path for Haskell tools", but does not make it clear that the system `PATH` and spacemacs' `PATH` may differ. It does say that "For information about setting up `$PATH`, check out the corresponding section in the FAQ (`SPC h SPC $PATH RET`).", but

1. This seems to be outdated, as I could not find any entries on `PATH` or `$PATH` under `SPC h SPC`
2. Even if that did result in useful documentation, users knowledgeable about the system PATH won't look there, thinking it's about the system `PATH`, not spacemacs' `PATH`.

It is also not clear from https://develop.spacemacs.org/doc/DOCUMENTATION.html#environment-variables-and-path that the spacemacs and system `PATH`s may go out-of-sync. And in any case, even if a user were to read that far into the documentation, they may not connect that information to their troubles when they later try to enable LSP or other tooling.

Of course, ideally, the spacemacs and system paths would never go out of sync, or need more than a restart of spacemacs to re-sync, but I don't know the motivation behind `.spacemacs.env`, so I can't speculate on the best solution.

Thank you for your hard work on spacemacs.

**Comment by lebensterben** [comment]
Yes, the preferred way of Haskell toolchain involves `ghcup`.

The real issue here is how .spacemacs.env is generated currently.
We generate it once and leave it there forever without any warning or automatic update.

In the long run we should either enhance it or abandon it entirely by reverting back to `exec-path-from-shell`.

In the short run we can improve the layer documentation as you've pointed out.

If you'd like to contribute, you may start from the layer documentation.

**Comment by emacs18** [comment]
I have always wondered why spacemacs saves environment and tries to use the saved environment.
Why?  It is so dangerous thing to be doing.  Following is the change I made in my earliest days of spacemacs use to avoid so many potential problems with this bug (this not a feature to me).  Even on my laptop, where only one OS can access my emacs files, I don't dare save and reuse environment.  In linux server environment where I could be using any number of different OS'es using the same networked file system, saving and reusing environment is just insane.

```diff
diff --git a/core/templates/.spacemacs.template b/core/templates/.spacemacs.template
index b90b043e0..cc58abe7f 100644
--- a/core/templates/.spacemacs.template
+++ b/core/templates/.spacemacs.template
@@ -523,8 +523,11 @@ This function defines the environment variables for your Emacs session. By
 default it calls `spacemacs/load-spacemacs-env' which loads the environment
 variables declared in `~/.spacemacs.env' or `~/.spacemacs.d/.spacemacs.env'.
 See the header of this file for more information."
-  (spacemacs/load-spacemacs-env)
-)
+  ;; Saving and loading environment is too risky when many different machines
+  ;; use the same emacs files! Perhaps the environment file name should include
+  ;; the hostname.
+  ;; (spacemacs/load-spacemacs-env)
+  )
 
 (defun dotspacemacs/user-init ()
   "Initialization for user code:
```
