### ISSUE TITLE
minibuffer is broken, hence all spacemacs

### ISSUE THREAD

**Issue by vitaminace33** [syl20bnr/spacemacs#15347]
Sorry for not using spacemacs' built-in bug submitter but spacemacs is completely broken.

I have updated spacemacs to the last git commit. Most key bindings give me

> read-from-minibuffer: Autoloading file /home/cedricmc/.emacs.d/elpa/27.1/develop/highlight-parentheses-20210816.1119/highlight-parentheses.elc failed to define function highlight-parentheses-minibuffer-setup

which result in a broken spacemacs. I can't close buffers with C-x k, nor compile a LaTeX file with C-c C-c.

Workaround: I reinstalled spacemacs.

**Comment by lebensterben** [comment]
try to remove the highlight-parentheses directory

**Comment by vitaminace33** [comment]
I had backed up ~/.emacs.d in the hope of a better solution and, indeed, yours does the trick. I understand there has been some problem updating and compiling the package. Am I right? Thanks for the answer.

**Comment by lebensterben** [comment]
I've no idea of what's going on regarding this kind of problems.
If it's fixed, please close this issue.
