### ISSUE TITLE
weird characters in evil mode

### ISSUE THREAD

**Issue by zxcvbn97** [syl20bnr/spacemacs#15341]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/9757976/153724096-47f92d01-7aab-42c4-85e6-eed9edf1ded9.png">

Spacemacs keeps showing af0000 characters when I open documents for viewing. Using it with iTerm 2.
The issue does not appear on original macos terminal.

**Comment by lebensterben** [comment]
Please follow the instructions on issue template.

**Comment by zxcvbn97** [comment]
Please close.. I disable resizing of spacemacs banner and bug went away

**Comment by lebensterben** [comment]
It's not possible to do any meaningful debugging with virtually no information provided.

Please follow the instruction of the issue template and provide more information.
