### ISSUE TITLE
multiple cursors keybindings not working

### ISSUE THREAD

**Issue by rickwubs** [syl20bnr/spacemacs#15348]
the multiple cursors documentation for spacemacs lists a bunch of keybindings.
these do not work. 

for example, "g r" goes to smerge-transient-state, not to multiple-cursors.

This is with a fresh install of spacemacs. 

The only layers installed are:
```
auto-completion
better-defaults
git
helm
lsp
markdown
org
shell
spell-checking
version-control
treemacs

```
On an additional note; your documentation for develop gives links to the release version. none of these links actually work; they all give 404.

**Comment by lebensterben** [comment]
please follow the issue template and attach your system information.

**Comment by practicalli-john** [comment]
@rickwubs as the multiple-cursors layer is not installed, then the layer keys will not be available

See the install section of the multiple-cursors documentation (where you looked up the key bindings)
https://develop.spacemacs.org/layers/+misc/multiple-cursors/README.html#install
