### ISSUE TITLE
Typo in tabs layer

### ISSUE THREAD

**Issue by LukeXuan** [syl20bnr/spacemacs#15349]
It seems like the variable name in [config.el](https://github.com/syl20bnr/spacemacs/blob/3429bcf056e6593a43cb0fa01204182e99315bae/layers/%2Bemacs/tabs/config.el#L23) is different from that in [packages.el](https://github.com/syl20bnr/spacemacs/blob/3429bcf056e6593a43cb0fa01204182e99315bae/layers/%2Bemacs/tabs/packages.el#L38).

**Comment by lebensterben** [comment]
@LukeXuan 
Thanks, I've fixed the typo. https://github.com/syl20bnr/spacemacs/commit/0bdddfc165a11b5fb2d319bc028b327744186ed5
