### ISSUE TITLE
Replace ace-jump-mode with avy

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1534]
Since `ace-window` and `ace-link` now depend on [avy](https://github.com/abo-abo/avy) and has everything `ace-jump-mode` has, we should just remove `ace-jump-mode` to remove redundancy. And I like `avy` better than `ace-jump-mode` now.

**Comment by syl20bnr** [comment]
I plan to do it but first I have to work on avy integration in evil.

**Comment by tuhdo** [comment]
Currently, `o` in Spacemacs home buffer gives this error:

> spacemacs/ace-buffer-links: Symbol's function definition is void: ali-generic [9 times]

**Comment by mkcode** [comment]
Just FYI - these 2 modes seem to be conflicting in latest develop a740923dd9b47238b0f6cd9518bbfafd68176be7

```
Found 1 new package(s) to install...
--> fetching new package repository indexes...
--> installing avy... [1/1]
Found 1 orphan package(s) to delete...
--> deleting avy... [1/1]
```

every time spacemacs is restarted.

**Comment by syl20bnr** [comment]
What is your Emacs version ?

Le vendredi 8 mai 2015, Chris Ewald <notifications@github.com> a écrit :

> Just FYI - these 2 modes seem to be conflicting in latest develop a740923
> <https://github.com/syl20bnr/spacemacs/commit/a740923dd9b47238b0f6cd9518bbfafd68176be7>
>
> Found 1 new package(s) to install...
> --> fetching new package repository indexes...
> --> installing avy... [1/1]
> Found 1 orphan package(s) to delete...
> --> deleting avy... [1/1]
>
> every time spacemacs is restarted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/1534#issuecomment-100354430>
> .
>


-- 
-syl20bnr-

**Comment by mkcode** [comment]
GNU Emacs 24.5.1 (x86_64-apple-darwin14.1.0, Carbon Version 157 AppKit 1344.72)

**Comment by syl20bnr** [comment]
Thank you, can you open an issue for this,
Seems that we have a regression in 24.5.1, somebody else has another
package (spinner) acting like that.

Le vendredi 8 mai 2015, Chris Ewald <notifications@github.com> a écrit :

> GNU Emacs 24.5.1 (x86_64-apple-darwin14.1.0, Carbon Version 157 AppKit
> 1344.72)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/1534#issuecomment-100355775>
> .
>


-- 
-syl20bnr-

**Comment by mkcode** [comment]
@syl20bnr - sure thing. thanks for the help!

**Comment by tuhdo** [comment]
For a workaround, you should include in your private layer or `dotspacemacs-additional-packages` list.

**Comment by tuhdo** [comment]
I think the problem is that `avy` is a package on MELPA now: http://oremacs.com/2015/05/08/avy-0.1.0/. So, when you try installing `ace-window` or `ace-link`, it will also install `avy` but `avy` is not part of Spacemacs and for that reason, it is treated as orphan package to be deleted.

**Comment by syl20bnr** [comment]
It should not be uninstalled if it is used by a listed package in a used
layer.


Le vendredi 8 mai 2015, Tu Do <notifications@github.com> a écrit :

> I think the problem is that avy is a package on MELPA now:
> http://oremacs.com/2015/05/08/avy-0.1.0/. So, when you try installing
> ace-window or ace-link, it will also install avy but avy is not part of
> Spacemacs and for that reason, it is treated as orphan package to be
> deleted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/1534#issuecomment-100357855>
> .
>


-- 
-syl20bnr-

**Comment by mkcode** [comment]
> For a workaround, you should include in your private layer or dotspacemacs-additional-packages list.

thanks

**Comment by mkcode** [comment]
Opened issue #1538

**Comment by tuhdo** [comment]
> It should not be uninstalled if it is used by a listed package in a used
> layer.

So, we better add `avy` to `spacemacs-packages` to fix this problem since we install it anyway.

**Comment by syl20bnr** [comment]
Indeed for avy this is not a problem.

Le vendredi 8 mai 2015, Tu Do <notifications@github.com> a écrit :

> It should not be uninstalled if it is used by a listed package in a used
> layer.
>
> So, we better add avy to spacemacs-packages to fix this problem since we
> install it anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/1534#issuecomment-100366141>
> .
>


-- 
-syl20bnr-

**Comment by liujoey** [comment]
avy could also replace evil-snipe layer, just don't know how to bind normal s to it

**Comment by endrebak** [comment]
`evil-snipe` has some additional nice functionality like triggering a regex, but `avy` can do much of what `evil-snipe` does. I guess using `avy` will free up the buttons `S` and `Z` (due to its bidirectionality), which is nice.

**Comment by endrebak** [comment]
I do not see what `evil`-integration needs to be done for `avy`. This minimal install (`M-x configuration-layer/create-layer <RET> <RET> avy <RET>`) worked for me:

```elisp
;;; packages.el --- avy Layer packages File for Spacemacs
;;
;; Copyright (c) 2012-2014 Sylvain Benner
;; Copyright (c) 2014-2015 Sylvain Benner & Contributors
;;
;; Author: Sylvain Benner <sylvain.benner@gmail.com>
;; URL: https://github.com/syl20bnr/spacemacs
;;
;; This file is not part of GNU Emacs.
;;
;;; License: GPLv3

;; List of all packages to install and/or initialize. Built-in packages
;; which require an initialization must be listed explicitly in the list.
(setq avy-packages
    '(
      avy
      ))

;; List of packages to exclude.
(setq avy-excluded-packages '())

;; For each package, define a function avy/init-<package-name>
;;
(defun avy/init-avy ()
  (use-package avy)
  "Initialize my package"
  )
;;
;; Often the body of an initialize function uses `use-package'
;; For more info on `use-package', see readme:
;; https://github.com/jwiegley/use-package
```

I still think `evil-snipe` will have an important role to play in a truly evil setup though, since if you are working close range and just want to  "shoot" the nearest thing, having to type an additional char (or two) is a bother. Furthermore, `evil-snipe` adds multiline functionality to `f`, `F` `t` and `T` which is essential. 

(Just giving a heads-up to @hlissner about `avy` since it would probably be beneficial to focus `evil-snipe` on the things `avy` can't or won`t do well.)

**Comment by expez** [comment]
>  Furthermore, evil-snipe adds multiline functionality to f, F t and T and anything else just feels barbaric to me.

`(setq evil-cross-lines t)`

**Comment by hlissner** [comment]
>(setq evil-cross-lines t)

Was about to mention that. All evil-snipe has over vanilla f/F/t/T is incremental highlighting and independent search/repeat scopes.

>since if you are working close range and just want to "shoot" the nearest thing, having to type an additional char (or two) is a bother.

+1

>it would probably be beneficial to focus evil-snipe on the things avy can't or won`t do well

I'd love to try. Let me know on [snipe's issue tracker](https://github.com/hlissner/evil-snipe/issues) if anyone has ideas.

**Comment by endrebak** [comment]
Not to slight `avy` since it seems fantastic, but I would not use it close range at all; in addition to having to  write to extra chars, you have to read them first too (for someone as dull as me that might take close to a second and the chances of bungling something are much higher). In addition, there is no way to quickly go to the next occurence with `avy`. But all in all, it seems like a wonderful tool.

**Comment by syl20bnr** [comment]
`evil-snipe` and `avy` are 2 different weapons both very useful.
`evil-snipe` is `rifle` whereas `avy` is a `missile launcher`.

**Comment by xged** [comment]
I prefer ace-jump over avy. Ace-jump has better visuals and better mark naming (less double letters) when finding a char IMHO.

**Comment by endrebak** [comment]
The number of keypresses needed should be the same. I guess `avy` uses many fewer input chars by default (homerow only) so it will take more keypresses.

Set this in your `.spacemacs` to get as few keypresses as `ace-jump`: `(setq avy-keys (number-sequence ?a ?z))`

Also, do not use `de-brujin` as the `avy-style` - it uses more chars.

Avy might look worse with `spacemacs`, but you can customize the colors yourself using `<M-x> customize-group <RET> avy <RET>`. I'm guessing that when `avy` is included in spacemacs, the `avy` colors will match the themes.

Also, `avy` is much more customizable in general. See how easy it is to do clever things like this: https://github.com/abo-abo/avy/issues/71

**Comment by xged** [comment]
`(setq avy-keys (number-sequence ?A ?Z)) (setq avy-translate-char-function #'upcase)` is good. I guess visuals are ok too (familiarity bias...). 

I am fine with *avi* instead of *ace-jump* then.

**Comment by Devagamster** [comment]
At least for me, the fact that avy does not jump across frames is very bothersome. I work with a multimonitor setup and so having an easy way to jump between my monitors without having to hit alt tab is crucial to my workflow. I have not done much investigation into possible configs, but by default avy does not show jump locations on other frames while ace does.

**Comment by Devagamster** [comment]
nvm. Just found it. For anybody else looking for it:

``` lisp
(setq avy-all-windows 'all-frames)
```

works for me. I change my answer. Avy all the way.

**Comment by bmag** [comment]
Is there any reason why `avy` hasn't replaced `ace-jump`? Is it just because no one submitted a PR yet, or something else?

**Comment by expez** [comment]
Has anyone written code to make `avy` work like `ace-jump` with evil? E.g. to to do `dt<avy-jump-to-char>`?

**Comment by bmag** [comment]
@expez doing `d<avy-jump-to-char>` works for me, without writing any code at all.

**Comment by bmag** [comment]
Made a PR for this, feedback welcome.
