### ISSUE TITLE
The Spacemacs buffer does not load correctly

### ISSUE THREAD

**Issue by John-Dawson-Camlin** [syl20bnr/spacemacs#15359]
#### Description :octocat:
When Emacs is started the Spacemacs buffer does not load correctly: the progress bar at the bottom does not finish and the lists of recent files and projects do not appear.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
![Screenshot from 2022-02-18 08-48-50](https://user-images.githubusercontent.com/94545627/154649836-ae64ea44-6297-44c6-8cb4-e7bb75dbaa7d.png)
In the Spacemacs buffer the progress bar at the bottom does not finish and the lists of recent files and projects do not appear.

*Expected behaviour:* :heart: :smile:
The progress bar finishes and the lists of recent files and projects appear.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. ee3c558c8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by dromaludaire** [comment]
I observed the same behavior after a recent update. I use spacemacs-base distribution.
When switching to the spacemacs distribution, this behaviour didn't occur anymore.

Using git bisect, it turns out that:
```
b7e1dee13f619646d9d419f518f6ba8d835bef41 is the first bad commit
commit b7e1dee13f619646d9d419f518f6ba8d835bef41
Author: Lucius Hu <1222865+lebensterben@users.noreply.github.com>
Date:   Tue Feb 15 01:52:00 2022 -0500

    spacemacs-buffer: Added optional feature to show file icons (#15332)
    
    Co-authored-by: Lucius Hu <lebensterben@users.noreply.github.com>

 core/banners/img/heart.png                     | Bin 552 -> 0 bytes
 core/core-dotspacemacs.el                      |   6 +
 core/core-load-paths.el                        |   4 -
 core/core-spacemacs-buffer.el                  | 440 ++++++++++++++-----------
 core/core-spacemacs.el                         |   3 +-
 core/templates/.spacemacs.template             |   5 +
 layers/+completion/auto-completion/packages.el |  87 ++---
 layers/+spacemacs/spacemacs-visual/packages.el |   4 +
 8 files changed, 291 insertions(+), 258 deletions(-)
 delete mode 100644 core/banners/img/heart.png
 ```

HTH.

**Comment by nigredo-tori** [comment]
Same here. For me this was "fixed" by setting `dotspacemacs-startup-buffer-show-icons t` in `dotspacemacs/init`.After that the loading process was completed as expected. However, that left me with messed up icons in the spacemacs buffer (missing glyphs in the font, FWICT). `M-x all-the-icons-install-fonts` has fixed the icons.

**Comment by lebensterben** [comment]
Thanks for the report.

@dromaludaire @nigredo-tori Could you also attach your system information via `SPC h I`? Please also attach `dotspacemacs-excluded-packages` if it's not empty.

Also, @nigredo-tori , is this still a bug on latest develop if you have `dotspacemacs-startup-buffer-show-icons` set to `nil`?

**Comment by nigredo-tori** [comment]
> Could you also attach your system information via SPC h I?

- OS: gnu/linux
- Emacs: 28.0.91
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. ee3c558c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs graphviz protobuf javascript yaml systemd
            (auto-completion :variables auto-completion-minimum-prefix-length 3)
            git github helm
            (lsp :variables lsp-lens-enable t)
            dap
            (markdown :variables markdown-table-align-p nil)
            multiple-cursors org
            (sql :variables sql-indent nil)
            syntax-checking treemacs c-c++
            (scala :variables scala-auto-insert-asterisk-in-comments t)
            theming themes-megapack my-settings logview spacemacs-editing
            (java :variables java-backend nil))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

> Please also attach dotspacemacs-excluded-packages if it's not empty.

```elisp
dotspacemacs-excluded-packages '(helm-ls-git)
```

> Also, @nigredo-tori , is this still a bug on latest develop if you have dotspacemacs-startup-buffer-show-icons set to nil?

With `dotspacemacs-startup-buffer-show-icons nil` everything loads fine. However, this might be because I have changed `dotspacemacs-mode-line-theme` to `all-the-icons` since. If switch back to
```elisp
dotspacemacs-startup-buffer-show-icons nil
dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 1.5)
```
(so that `all-the-icons` is not loaded), then the bug is back again.

**Comment by nigredo-tori** [comment]
@lebensterben, this patch fixed the issue for me.

**Comment by lebensterben** [comment]
@John-Dawson-Camlin 
Please update Spacemacs and it should be fixed now.

**Comment by dromaludaire** [comment]
@lebensterben I confirm your latest commit fixed the issue when using spacemacs-base. Thanks!

**Comment by John-Dawson-Camlin** [comment]
@lebensterben, thank you for fixing this.
