### ISSUE TITLE
Opening the minibuffer causes an error in highlight-parentheses.elc in develop (rev. 3deed8f06)

### ISSUE THREAD

**Issue by kylesnowschwartz** [syl20bnr/spacemacs#15353]
#### Description :octocat:
Opening the minibuffer causes an error in highlight-parentheses after recently pulling the most recent develop branch

#### Reproduction guide :beetle:
Start Emacs
open mini buffer with SPC b b
Minibuffer is not working and error is raised

*Observed behaviour:* :eyes: :broken_heart:
No mini buffer is displayed, instead an error is raised

*Expected behaviour:* :heart: :smile:
The mini buffer should work

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 3deed8f06)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(python typescript react csv osx ivy
        (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'rbenv ruby-backend 'robe)
        ruby-on-rails yaml javascript coffeescript terraform sql html
        (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
        emacs-lisp git markdown multiple-cursors
        (haskell :variables haskell-completion-backend 'lsp)
        lsp org syntax-checking version-control prettier)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (error "Autoloading file /Users/kyle/.emacs.d/elpa/27.2/develop/highlight-parentheses-20210420.1924/highlight-parentheses.elc failed to define function highlight-parentheses-minibuffer-setup")
  signal(error ("Autoloading file /Users/kyle/.emacs.d/elpa/27.2/develop/highlight-parentheses-20210420.1924/highlight-parentheses.elc failed to define function highlight-parentheses-minibuffer-setup"))
  ivy-read("Switch to buffer: " internal-complete-buffer :keymap (keymap (27 keymap (11 . ivy-switch-buffer-kill)) (10 . ivy-next-line) (11 . ivy-previous-line)) :preselect "*spacemacs*" :action ivy--switch-buffer-action :matcher ivy--switch-buffer-matcher :caller ivy-switch-buffer)
  ivy-switch-buffer()
  funcall-interactively(ivy-switch-buffer)
  call-interactively(ivy-switch-buffer nil nil)
  command-execute(ivy-switch-buffer)

```

**Comment by lebensterben** [comment]
duplicated. See https://github.com/syl20bnr/spacemacs/issues/15347 for solution.
