### ISSUE TITLE
Autocomplete does not work inside Jupyter/IPython Notebook

### ISSUE THREAD

**Issue by mehrtash** [syl20bnr/spacemacs#15357]
#### Description :octocat:
Autocomplete does not work inside Jupyter/Ipython Notebook.

#### Reproduction guide :beetle:
- Start Emacs
- M-x conda-env-activate and select your conda enviornment
- M-x ein:jupyter-server-start and open a new or existing notebook
- Import some library and try to do autocomplete by tab and it does not work.
- Triggering company mode manually (M-x company mode) does not help.

*Observed behaviour:* :eyes: :broken_heart:
- Autocomplete is not showing up in the notebook buffer

*Expected behaviour:* :heart: :smile:
- Autocomplete works inside IPython notebook.

#### System Info :computer:
- OS: gnu/linux (same on Mac OS)
- Emacs: 27.1 (tested on 28.0.91 on Mac OS)
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 3deed8f06)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion
 (conda :variables conda-anaconda-home "/home/username/anaconda3")
 dap
 (ipython-notebook :variables ein-backend 'jupyter)
 emacs-lisp git helm lsp markdown multiple-cursors org python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control themes-megapack treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by alkimist** [comment]
Experiencing the same issue

**Comment by HanshenWang** [comment]
Not directly related, but I've had a better experience with https://github.com/nnicandro/emacs-jupyter over EIN.

**Comment by alkimist** [comment]
after enabling `debug-on-error` I get the following backtrace

`(ein:kernel-complete (symbol-value G616) (string-trim-right (thing-at-point 'line t)) (symbol-value G614) (list :complete_reply (list #'spacemacs//ein-company-callback cb)) nil)
  (lambda (G614 G615 G616 cb) (ein:kernel-complete (symbol-value G616) (string-trim-right (thing-at-point 'line t)) (symbol-value G614) (list :complete_reply (list #'spacemacs//ein-company-callback cb)) nil))(--col-- --arg-- --kernel-- #f(compiled-function (candidates) #<bytecode 0x156aaf6f0475>))
  apply((lambda (G614 G615 G616 cb) (ein:kernel-complete (symbol-value G616) (string-trim-right (thing-at-point 'line t)) (symbol-value G614) (list :complete_reply (list #'spacemacs//ein-company-callback cb)) nil)) --col-- --arg-- --kernel-- #f(compiled-function (candidates) #<bytecode 0x156aaf6f0475>))
  (lambda (&rest --cl-rest--) (apply #'(lambda (G614 G615 G616 cb) (ein:kernel-complete (symbol-value G616) (string-trim-right (thing-at-point ... t)) (symbol-value G614) (list :complete_reply (list ... cb)) nil)) '--col-- '--arg-- '--kernel-- --cl-rest--))(#f(compiled-function (candidates) #<bytecode 0x156aaf6f0475>))
  company--fetch-candidates(#("ge" 0 2 (fontified t :pm-mode python-mode :pm-span (body 3391 3466 #<pm-inner-overlay-chunkmode ein-input-cell::>))))
  company-calculate-candidates(#("ge" 0 2 (fontified t :pm-mode python-mode :pm-span (body 3391 3466 #<pm-inner-overlay-chunkmode ein-input-cell::>))) nil)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer  *ein: http://127.0.0.1:8888/ilri_bot/Untitled.ipynb*[python]> #<window 77 on  *ein: http://127.0.0.1:8888/ilri_bot/Untitled.ipynb*[python]> 4713 3393)
  apply(company-idle-begin (#<buffer  *ein: http://127.0.0.1:8888/ilri_bot/Untitled.ipynb*[python]> #<window 77 on  *ein: http://127.0.0.1:8888/ilri_bot/Untitled.ipynb*[python]> 4713 3393))
  timer-event-handler([t 25132 8418 328701 nil company-idle-begin (#<buffer  *ein: http://127.0.0.1:8888/ilri_bot/Untitled.ipynb*[python]> #<window 77 on  *ein: http://127.0.0.1:8888/ilri_bot/Untitled.ipynb*[python]> 4713 3393) nil 436000])
`

**Comment by lebensterben** [comment]
@HanshenWang 

Feel free to submit a PR to replace EIN.
