### ISSUE TITLE
zz, zt, zb don't work in NeoTree

### ISSUE THREAD

**Issue by temporized-andy** [syl20bnr/spacemacs#15355]
Could you please enable zz, zt, zb to position current line in NeoTree?

**Comment by temporized-andy** [comment]
@temporized-andy 
same functionality as in vim:
zz - scroll current line the center
zt - scroll current line to the top
zb - scroll current line to the bottom

**Comment by lebensterben** [comment]
for `zt` and `zb`, you can use `gg` and `G`.

Alternatively, add the following to your user-config.
```elisp
(evil-define-key 'evilified neotree-mode-map
  "zz" #'evil-scroll-line-to-center
  "zt" #'evil-scroll-line-to-top
  "zt" #'evil-scroll-line-to-bottom)
```

**Comment by temporized-andy** [comment]
Thank you so much! gg and G jump to the top/bottom which is slightly different but your snipped did exactly what I expected. It would be cool to have this out of the box like NerdTree.

**Comment by lebensterben** [comment]
We provide vim-inspired key bindings, which is gg and G.

But Neotree-style key bindings is not a design goal.

**Comment by temporized-andy** [comment]
@lebensterben I am sorry but this are not the Neotree keys these are vim keys. Neotree is just rendered inside a vim buffer and supports everything naturally. You can use the same key sequences anywhere in vim.

**Comment by smile13241324** [comment]
Hmm sounds useful, I see what I can do

**Comment by smile13241324** [comment]
I have added the vim bindings for zz, zt and zb.
However other evio bindings like L are still missing as this tree is pretty old and brings its own set of keybindings.

For a full vim experience you should consider switching to the more modern treemacs package.

**Comment by temporized-andy** [comment]
@smile13241324 thank you so much!
