### ISSUE TITLE
org-agenda-files not used correctly, causes Spacemacs not to load properly

### ISSUE THREAD

**Issue by abgruszecki** [syl20bnr/spacemacs#15366]
In the definition of `spacemacs-buffer//insert-recent-files`, `org-agenda-files` is used like it needs to be a list if it's non-nil (see [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-spacemacs-buffer.el#L1244)). In fact, it can be a string as well, which has a different meaning than a single-member list. If it's a string, this causes an error during Spacemacs init.

Maybe one should use `(org-agenda-files)` instead?

**Comment by abgruszecki** [comment]
Just tested this: using `(org-agenda-files)` does cause Emacs to load properly.

**Comment by abgruszecki** [comment]
Thanks for taking care of this soon, @lebensterben !

**Comment by lebensterben** [comment]
@abgruszecki 
feel free to submit a PR if you already have a solution.

I will also investigate it.

**Comment by Claude-Ray** [comment]
Sorry to bother @abgruszecki , `(org-agenda-files)` could slow down startup a lot.

Can we keep using the variable `org-agenda-files` instead of function? 

For example,

```elisp
(if (boundp 'org-agenda-files)
    (if (listp org-agenda-files)
        org-agenda-files
      (list org-agenda-files))
  nil)
```

**Comment by abgruszecki** [comment]
I'm not a regular maintainer of the repo. I guess @lebensterben will be able to answer you better.

From my perspective, only considering subset of possible settings of `org-agenda-files` would produce surprising behavior during startup, and I don't think the tradeoff in startup time is worth it. If it truly becomes a problem, maybe having a setting for not considering org-agenda-files at all could be useful.

**Comment by Claude-Ray** [comment]
Thanks for your prompt reply. 

Personally, I'm not a very heavy org-mode user, calling org-agenda-files can increase startup time by several times.
I agree with you that it would be better to make it optional.

**Comment by lebensterben** [comment]
@Claude-Ray 
It's already optional.
Just don't include agenda in dotspacemacs-startup-lists

**Comment by lebensterben** [comment]
@Claude-Ray 

Also note that if org-agenda-files is a single filename, this file contains the list of agenda files.

In that cases we need to parse the file to get the actual list.

But this is exactly what the function org-agenda-files is doing.
