### ISSUE TITLE
emacsclient --eval "" return code contains weird invisible characters

### ISSUE THREAD

**Issue by YuxiKou** [syl20bnr/spacemacs#15362]
#### Description :octocat:
`emacsclient --eval ""` return code contains weird characters

#### Reproduction guide :beetle:
Kill all emacs instances then
`echo $(emacsclient -a '' -n -e "") | cat -v`

*Observed behaviour:* :eyes: :broken_heart:
It outputs:
```
^[]12;#ffffffff0000^G^[]12;#ffff0000ffff^G
```
*Expected behaviour:* :heart: :smile:
should be nil

Since this started recently I bisected the git history and found the commit https://github.com/syl20bnr/spacemacs/commit/77ba076f697d270b011586944004ce8dfb6f61a4 where this started. But looking at it I am not sure why it is causing this behavior. The `emacsclient` command above is used by [emacs plugin ](https://github.com/ohmyzsh/ohmyzsh/blob/3427da4057dbe302933a7b5b19b4e23bfb9d0969/plugins/emacs/emacsclient.sh#L14,L20) for oh-my-zsh to detect whether an emacs frame exists. Because of these weird characters the detection always fail thus breaking the script.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. ebd060388)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 (go :variables go-tab-width 4)
 (markdown :variables markdown-live-preview-engine 'vmd)
 (org :variables org-want-todo-bindings t org-enable-org-journal-support t org-startup-indented t org-enable-roam-support t)
 (rust :variables rust-backend 'lsp)
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 csharp csv emacs-lisp git helm json lsp python spell-checking syntax-checking theming version-control web-beautify yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
A fix is on the way.
You can try to apply the patch mentioned here in the meantime:

https://github.com/syl20bnr/spacemacs/issues/15360#issuecomment-1045462804

**Comment by YuxiKou** [comment]
It doesn't seem to fix the problem and I am still seeing those chars. I did the replacement according to that comment and to be safe also removed .emacs.d/elpa folder. Still the same output (found a better command to demonstrate the output)

````
echo $(emacsclient -a '' -n -e "(message \"1\")") | cat -v
^[]12;#ffffffff0000^G"1"
````

Not sure if related, but I am using WSL 2 with Ubuntu in Windows 11. I have been using this same setup for a while so it is unlikely to be caused by this.

**Comment by YuxiKou** [comment]
I just tried on Emacs 28 on a mac, found similar output. 
```
echo $(emacsclient -a '' -n -e "(message \"1\")") | cat -v
emacsclient: can't find socket; have you started the server?
emacsclient: To start the server in Emacs, type "M-x server-start".
Loading .spacemacs...
Loading .spacemacs...done
Starting a server...
Starting new Ispell process /usr/local/bin/aspell with default dictionary... \
Starting new Ispell process /usr/local/bin/aspell with default dictionary...done
Spacemacs is ready.
Restarting server
Emacs daemon should have started, trying to connect again
^[[2 q^[]Plffffffff0000^[\^[[2 q"1"
```

**Comment by lebensterben** [comment]
@YuxiKou 
Can you use "git bisect" to pin down the commit that introduced this issue?

**Comment by YuxiKou** [comment]
> 

Yes it is introduced in commit https://github.com/syl20bnr/spacemacs/commit/77ba076f697d270b011586944004ce8dfb6f61a4 .

**Comment by lebensterben** [comment]
@YuxiKou 

Can you try to
1. add `evil-terminal-cursor-changer` to `dotspacemacs-excluded-packages` in your .spacemacs
2. Quit Emacs and exit daemon if it's running
3. Then start Emacs to see whether the issue persists

**Comment by lebensterben** [comment]
I think I'm going to disable `evil-terminal-cursor-changer` due to the unfixed upstream bug
https://github.com/7696122/evil-terminal-cursor-changer/issues/8

**Comment by YuxiKou** [comment]
Yes excluding evil-terminal-cursor-changer worked! Thanks!

**Comment by bryce-carson** [comment]
Rather than opening a new issue, I'll report here, @lebensterben, that excluding the `evil-terminal-cursor-changer` package in `.spacemacs` also fixes the same issue appearing in the *spacemacs-dumper* buffer.

### Before
```
^[]12;#ffffffff0000^G^[]12;#ffffffff0000^G^[]12;#ffffffff0000^G^[]12;#ffffffff0000^G^[]12;#ffffffff0000^G^[]12;#ffffffff0000^G^[]12;#ffffffff0000^G(Spacemacs) Pre-dumping layer emacs-lisp...
Loading mode emacs-lisp-mode...
[yas] Prepared just-in-time loading of snippets successfully.
Starting new Ispell process /usr/bin/enchant-2 with default dictionary... \ 
Starting new Ispell process /usr/bin/enchant-2 with default dictionary...done
^[]12;#ffffffff0000^G^[]12;#ffffffff0000^G^[]12;#ffffffff0000^G(Spacemacs) Pre-dumping layer helm...
Loading mode helm-mode...
Helm mode enabled
(Spacemacs) Pre-dumping layer org...
Loading mode org-mode...
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-next-line’ originally mapped on ‘C-n’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-toggle-time-grid’ originally mapped on ‘G’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-filter-remove-all’ originally mapped on ‘|’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-filter-by-tag’ originally mapped on ‘\’
^[]12;#ffffffff0000]12;#ffffffff0000^G^[]12;#ffffffff0000^G(Spacemacs) Pre-dumping layer python...
Loading mode python-mode...
Can’t guess python-indent-offset, using defaults: 4
Importmagic and/or epc not found. importmagic.el will not be working.
^[]12;#ffffffff0000^G(Spacemacs) Dumping Emacs...
dumping fingerprint: cecb3b2642bbc07339a9ad1c5c3fcf39c8e25b3f4e7365fbe4c215450cae568f
```

### After
```
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/cmake-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/desktop-entry-mode-init.el (source)...
Loading /usr/share/emacs/site-lisp/site-start.d/rpmdev-init.el (source)...
Loading /home/brycecarson/.spacemacs.d/init.el (source)...
Loading /home/brycecarson/.spacemacs...
(Spacemacs) --> deleting evil-terminal-cursor-changer... [1/1]
Package ‘evil-terminal-cursor-changer-20211225.600’ deleted.
Package cl is deprecated
Cannot insert ("N" "Forge" forge-dispatch) into magit-dispatch; o not found
Setting ‘forge-add-default-bindings’ to nil in ‘evil-collection-forge-setup’.
To suppress this message you can set this variable to nil in your init.el file.
(Spacemacs) Pre-dumping layer emacs-lisp...
Loading mode emacs-lisp-mode...
[yas] Prepared just-in-time loading of snippets successfully.
Starting new Ispell process /usr/bin/enchant-2 with default dictionary... \ 
Starting new Ispell process /usr/bin/enchant-2 with default dictionary...done
(Spacemacs) Pre-dumping layer helm...
Loading mode helm-mode...
Helm mode enabled
(Spacemacs) Pre-dumping layer org...
Loading mode org-mode...
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-next-line’ originally mapped on ‘C-n’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-toggle-time-grid’ originally mapped on ‘G’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-filter-remove-all’ originally mapped on ‘|’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-filter-by-tag’ originally mapped on ‘\’
(Spacemacs) Pre-dumping layer python...
Loading mode python-mode...
Can’t guess python-indent-offset, using defaults: 4
Importmagic and/or epc not found. importmagic.el will not be working.
(Spacemacs) Dumping Emacs...
dumping fingerprint: cecb3b2642bbc07339a9ad1c5c3fcf39c8e25b3f4e7365fbe4c215450cae568f
Dump complete
Byte counts: header=80 hot=45160800 discardable=126144 cold=27538016
Reloc counts: hot=2791583 discardable=4981
Done!
```

**Comment by lebensterben** [comment]
`evil-terminal-cursor-changer` is removed in commit https://github.com/syl20bnr/spacemacs/commit/d48bc8d90bb834fee2140499fee3b3f43f170320.

`term-cursor` would be used for this purpose instead. See https://github.com/syl20bnr/spacemacs/commit/d48bc8d90bb834fee2140499fee3b3f43f170320
