### ISSUE TITLE
github layer: docs for authentication outdated 

### ISSUE THREAD

**Issue by real-or-random** [syl20bnr/spacemacs#15377]
https://develop.spacemacs.org/layers/+source-control/git/README.html explains how to generate a GitHub auth token and add it to your git config. But this is unclear in multiple ways:

-  It doesn't explain to which of the packages to auth info applies. (Note that this doesn't really spark confidence in the reader, it's a little bit like "Paste your token here and spacemacs will use it for some stuff but I don't explain what stuff"). AFAIU the config applies only packages using `gh.el` as a backend, which is true for `github-clone` but not for the other packages in the layer. `forge` uses a different backend for instance (https://magit.vc/manual/forge/Token-Creation.html)
- The docs say the token should have the `gist` permission but the gist package was removed from the layer. 

Maybe for now, it will be easier to just refer to the package documentation...

**Comment by arifer612** [comment]
> https://develop.spacemacs.org/layers/+source-control/git/README.html

I believe you meant to link to the GitHub layer page over at 
https://develop.spacemacs.org/layers/+source-control/github/README.html
instead. I agree that the current documentation is rather straight-forward, but
it is sufficient enough to get the information across in setting up the layer.
You are always free to edit the README to improve on its delivery. A short note
at the end of the ``Git Configuration" subsection to the package documentations
should also suffice to guide users to the right places to know why they need to
prepare the auth tokens for it to work on Spacemacs.

As for the `gist` permission, it should definitely be removed for as long as the
GitHub layer does not include the `gist` package.

**Comment by real-or-random** [comment]
> > [develop.spacemacs.org/layers/+source-control/git/README.html](https://develop.spacemacs.org/layers/+source-control/git/README.html)
> 
> I believe you meant to link to the GitHub layer page over at [develop.spacemacs.org/layers/+source-control/github/README.html](https://develop.spacemacs.org/layers/+source-control/github/README.html) instead.

Oh sure.

> I agree that the current documentation is rather straight-forward, but it is sufficient enough to get the information across in setting up the layer. You are always free to edit the README to improve on its delivery. A short note at the end of the ``Git Configuration" subsection to the package documentations should also suffice to guide users to the right places to know why they need to prepare the auth tokens for it to work on Spacemacs.

Yes, I feel I don't have the time right now, so I opened an issue instead of a PR. 

> 
> As for the `gist` permission, it should definitely be removed for as long as the GitHub layer does not include the `gist` package.

**Comment by practicalli-john** [comment]
I'm creating a PR to briefly explain the need for the token and SSH key in the documentation
