### ISSUE TITLE
Formal way of removing deprecated layers

### ISSUE THREAD

**Issue by arifer612** [syl20bnr/spacemacs#15389]
Relevant: #15381 

This is with regards to layers that are no longer relevant, secure, or need to be pruned currently do not have a formal process for removal, unlike [creating or editing layers](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#contributing-a-layer). As this project matures, the need to merge or prune certain layers (i.e. the GitHub layer in #15381) may happen frequently. I would like to know and make clear what we should do if we wish to propose a removal of a layer from Spacemacs. 

Unlike adding or editing a layer, removing a layer is destructive and will negatively affect users who are using it so it should be handled delicately. This can be fixed by suggesting to users of a removed layer to move the affected layer from `.emacs.d/layers` to `~/.spacemacs.d/private/layer` before doing any update to their Spacemacs version.

**Comment by lebensterben** [comment]
We need a systematic approach to deprecate and remove:
- layer configuration variables defined in config.el
- functions, commands defined in a layer's funcs.el
- packages defined in a layer's packages.el
- an entire layer
- a core spacemacs function, commands, variable defined in one of core/core-*.el

The complete process of deprecating and finally removing the aforementioned things requires the following steps:
- A way to declare or mark the item as deprecated.
- Deprecation must be reflected in a layer's README.org, and/or user may receive a warning when the user uses the item
- After a given amount of "grace period", a deprecated item should be removed.
