### ISSUE TITLE
Outdated installation instructions.

### ISSUE THREAD

**Issue by chy-causer** [syl20bnr/spacemacs#15382]
Hi there!

On the installation instructions it gives two options for installing, one for develop branch and one for stable, but both commands seem to give be the development branch. Is this a mistake?

`git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d` vs `git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d`

I posted on Gitter and someone recommended I post here, so here I am :)

**Comment by arifer612** [comment]
Ever since #964f4c5 the develop branch has been the main branch served when you
pull using `git clone`. There is no longer a `stable' branch, so yes, the README
file is erroneous. It should now be proper to correct the README's installation
instruction to reflect this change.

**Comment by practicalli-john** [comment]
If www.spacemacs.org were automatically redirected to develop.spacemacs.org (for example in the spacemacs.org domain configuration - or a page redirect) then people (especially those new to spacemacs) would see the most recently published documentation, layer list, etc.

Alternatively, all the links on the spacemacs.org web page could be updated to point to their develop versions

Any instructions mentioning stable or the master branch would still need to be replaced though.

**Comment by arifer612** [comment]
Definitely. We'll have to go through the documentation in its full to correct all the dead links and outdated information. That'll be a mid-term undertaking that I should be able to start in about a month's time if nobody gets to it by then. Anybody who wants to do so please do feel free to do so, it's going to be a lengthy task but it's not hard and its effects are very far-reaching!

**Comment by practicalli-johnny** [comment]
The Spacemacs website still refers to a different version of Spacemacs than new users install and old users migrated from when there were noticeable issues

I suggest this issue is still very relevant

Thank you.
