### ISSUE TITLE
Helm autocomplete from emacs shell opens in a glitchy pseudo-window

### ISSUE THREAD

**Issue by dgealow** [syl20bnr/spacemacs#15380]
#### Description :octocat:
Helm autocomplete from emacs shell opens in a glitchy pseudo-window.

#### Reproduction guide :beetle:
- Start Emacs
- Launch emacs shell `SPC a t s e`
- Press tab

*Observed behaviour:* :eyes: :broken_heart:
Helm autocomplete opens up in the wrong place, and appears to be a glitchy
independent frame:

<img width="741" alt="Screen Shot 2022-02-27 at 19 27 30" src="https://user-images.githubusercontent.com/31712479/155907588-c9350da5-82e8-4c81-a867-5bc34d875fbc.png">

If an option is selected
or escape is pressed, it fills in (or doesn't fill in) properly and the pseudo-
window disappears. However, if you click back to the main frame, and keep
typing in the shell or do whatever else, the glitchy helm window will persist
(even past closing all other frames). If you click back to the main window
and press tab again after running more commands, then helm disappears
and a space is inserted on the line of the prompt that spawned it.

*Expected behaviour:* :heart: :smile:
Helm opens in the proper location.

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. f54897584)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql python
     (auto-completion :variables auto-completion-return-key-behavior 'nil auto-completion-tab-key-behavior 'complete)
     emacs-lisp helm multiple-cursors
     (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
     treemacs)
```
Note: this bug still occurs with the auto-completion layer disabled; there do appear to be odd interactions and something like a race condition between helm and some other tab-completion in certain circumstances but that's for another bug report.

- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
N/A

**Comment by lebensterben** [comment]
what additional packages do you have?

**Comment by dgealow** [comment]
> what additional packages do you have?
I think beyond the default ones it's just python and sql? Did a clean install earlier today since I hadn't updated in ages.

**Comment by dgealow** [comment]
For completion's sake, just did a completely fresh install. Selected vim keybindings; selected minimal distribution. Opened up the .spacemacs with `SPC f e d`, uncommented 
```
     (shell :variables
             shell-default-height 30
             shell-default-position 'bottom)
```
then saved and reloaded with `SPC f e R`. Opened shell with `SPC s t s e` and hit tab; bug still occurs.

**Comment by dgealow** [comment]
So, I just noticed that upon installation, compilation of one particular helm-related file is actually spewing a host of errors, including many about a number of window-related functions. Compilation log [here](https://pastebin.com/0cBEKjJR).

**Comment by smile13241324** [comment]
To be honest this eshell is pretty glitchy by itself, I am not sure if it really makes sense to spend more time on trying to improve this anymore. Instead you should consider switching over to one of the more recent shells, of which vterm would be the most advanced right now which has non of the issues described above.
