### ISSUE TITLE
Spacemacs org-mode: Hitting TAB key no longer expands headings. Instead generates error " symbol's function definition is void yas/expand"

### ISSUE THREAD

**Issue by 00krishna** [syl20bnr/spacemacs#15390]
#### Description :octocat:
I updated Spacemacs and its packages. Now for some reason my org-mode files are not working properly.
Usually when I hit the TAB key on a heading, this will expand or collapse the content under that heading.
Now, the TAB key produces no response. I just get an error message " symbol's function definition is void yas/expand".
So I would like to have the original expand/collapse functionality restored.

#### Reproduction guide :beetle:
- Start Emacs
- Open an org file.
- Navigate to a heading, meaning one of the headings with the *
- Hit the TAB key to try and expand or collapse the heading
- Note the error at the bottom of Emacs, "symbol's function definition is void yas/expand"

*Observed behaviour:* :eyes: :broken_heart:
I just obtain the error message, but nothing else happens. 

*Expected behaviour:* :heart: :smile:
The expected behavior is for the content of the heading to expand or collapse. 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. f54897584)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git ivy lsp markdown multiple-cursors org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control treemacs latex bibtex yaml graphviz asciidoc themes-megapack plantuml
                 (python :variables python-backend 'lsp)
                 (julia :variables julia-backend 'lsp)
                 dap rust
                 (c-c++ :variables c-c++-backend 'lsp-clangd)
                 search-engine html ess ipython-notebook pandoc sql erc)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
cannot reproduce here.

**Comment by 00krishna** [comment]
@lebensterben So I was trying some more things. It seems like when I reload the dotfile using SPC--f-e-R, then the expand/collapse action starts to work again. So it seems like perhaps it is missing or failing on the load? Is there any way to force the load of these org functions? I imagine that this function is in either the spacemacs org layer, or in some internal package, so not sure where to look.

**Comment by lebensterben** [comment]
just restart
