### ISSUE TITLE
[Feature request] Is it possible to add support for debugpy in +python layer?

### ISSUE THREAD

**Issue by DJManas** [syl20bnr/spacemacs#15394]
Hello,

just a quick question. Is it too hard to add support for debugpy in dap-mode for python?

I had tried to add this code into .spacemacs
```
(dap :variables
  dap-auto-configure-features '(sessions locals controls tooltip)
  dap-python-debugger 'debugpy)
```
By ```setq-default dotspacemacs-configuration-layers```

Inside block ```(defun dotspacemacs/user-init ()```

Or did I simply put it in wrong place and there is nothing between me and starting of using debugpy under spacemacs?
Thanks,
Regards,
Petr Sourek

**Comment by lebensterben** [comment]
you can raise this question in dap-mode repo or their discord channel.

**Comment by DJManas** [comment]
I had already asked and this should be sufficient:
```
(after! dap-mode
  (setq dap-python-debugger 'debugpy))
```

So I am wondering how to set this in spacemacs. Can I simply put it at the end of .spacemacs file in the same form?

**Comment by lebensterben** [comment]
No that looks like is for doom emacs.

You've set the variable correctly. If it's not working, you probably haven't install the debugger properly...

**Comment by DJManas** [comment]
Yes, I am switching between the two, because I can't to get dap-mode for python flask running. Raised ticket for this.

But on the other hand. I had followed [this guide](https://develop.spacemacs.org/layers/+tools/dap/README.html) and only inserted **dap** into **dotspacemacs-configuration-layers** section in .spacemacs and afterwards I set the variable as in the first post. Restarted, it installed the dap-mode. But it still passes the ptvsd into the dap-mode instead of debugpy and I am confused how can I install it more "correctly".

**Comment by lebensterben** [comment]
Please let me know if I'm mistaken, but I don't think this is either a bug report nor a feature request.

We have done nothing with dap-python-debugger.

And there's nothing we need to do with it.
You should only need to install debugpy and set `dap-python-debugger` and the rest should work as expected.

**Comment by DJManas** [comment]
Ok, I will do some further investigation. If you are telling me, that the configuration, I made, is correct (and I am not talking about the doom emacs one), I will try to investigate or to talk with dap-mode team. If we find something I will raise bug report.

Thank you for now.
