### ISSUE TITLE
ivy-avy-20211021.1602/ivy-avy.el failed to provide feature ‘ivy-avy’

### ISSUE THREAD

**Issue by paxsali** [syl20bnr/spacemacs#15399]
Hi all,

I just cloned the repo in a new spacemacs installation:

` ` `bash
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
` ` `

There is an error on startup:

` ` `
Error (use-package): ivy-avy/:catch: Loading file /home/paxsali/.emacs.d/elpa/27.2/develop/ivy-avy-20211021.1602/ivy-avy.el failed to provide feature ‘ivy-avy’
` ` `

The file is literally zero bytes:

` ` `bash
$ cd .emacs.d/elpa/27.2/develop
$ find . -type f -size 0c -ls
  3794467      0 -rw-r--r--   1 paxsali  paxsali         0 Mar  9 19:15 ./ivy-avy-20211021.1602/ivy-avy.el
` ` `

Are we supposed to ignore this?

I'm on ` 0.999.0@27.2`.

Any suggestions?

**Comment by tshu-w** [comment]
It's unnormal that ivy-avy.el have zero bytes. You can tried to delete `ivy-avy-20211021.1602` and reinstall this package.

**Comment by lebensterben** [comment]
Yes please retry according to @tshu-w 's suggestion.

**Comment by paxsali** [comment]
Hello again,

so I deleted `.emacs.d/elpa/27.2/develop/ivy-avy-20211021.1602` and restarted spacemacs again.

The error disappeared.

I'm ok with closing the issue. But really, the question is how could this happen in the first place.

**Comment by lebensterben** [comment]
@paxsali 

After you opened this issue, I went to melpa and found that ivy-avy is not available at that moment.

But when I closed the issue, the package re-appeared. So this could be a glitch.
