### ISSUE TITLE
Reporting a variable is void helm-map when use ivy and lsp-java-generate-*

### ISSUE THREAD

**Issue by liuchong** [syl20bnr/spacemacs#15393]
I'm using `(java :variables java-backend 'lsp)` and when I type `lsp-java-generate-getters-and-setters` or `lsp-java-generate-overrides`, I got errors `apply: Symbol’s value as variable is void: helm-map`.

How could I solve this problem? Maybe it's related to https://github.com/emacs-lsp/lsp-java/issues/147 👀 

- OS: darwin
- Emacs: 28.0.91
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. f54897584)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:

Thanks!

**Comment by lebensterben** [comment]
Please provide the full list of of layers.

**Comment by liuchong** [comment]
Thanks, it's the layer `+fun/emoji`, I've deleted it and the problem was fixed.
