### ISSUE TITLE
treemacs icons not shown correctly

### ISSUE THREAD

**Issue by fleimgruber** [syl20bnr/spacemacs#15404]
#### Description :octocat:
Treemacs icons are not shown properly in dired / ranger / helm-icons.

#### Reproduction guide :beetle:
- Start Emacs
- M-x all-the-icons-install-fonts
- Install the downloaded .ttf fonts
- Reboot
- Start Emacs
- M-x treemacs-icons-catalogue

*Observed behaviour:* :eyes: :broken_heart:
![image](https://user-images.githubusercontent.com/7400038/158020989-54d44ef3-bfa4-479a-9c68-38d37939a7fe.png)

*Expected behaviour:* :heart: :smile:
Treemacs icons are shown.

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.2.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. e32acdfad)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((org :variables org-enable-org-contacts-support t org-contacts-files
      `(,(expand-file-name "~/lg/contacts.org"))
      org-enable-reveal-js-support t org-enable-trello-support t org-enable-org-journal-support t org-journal-file-type 'yearly org-journal-dir
      (expand-file-name "~/lg")
      org-journal-date-format "%A, %d %B %Y" org-reverse-note-order t org-enable-roam-support t org-enable-appear-support t org-enable-transclusion-support t)
 pbz pbz-org-roam
 (tree-sitter :variables tree-sitter-syntax-highlight-enable t)
 polymode latex csv pdf finance
 (treemacs :variables treemacs-use-follow-mode t)
 multiple-cursors semantic-web jabber dash
 (javascript :variables javascript-import-tool 'import-js javascript-repl 'nodejs)
 tern helm bibtex ranger
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/")
 csharp sphinx restructuredtext
 (lsp :variables lsp-prefer-flymake nil)
 dap emacs-lisp
 (git :variables git-enable-magit-svn-plugin t)
 ess octave sql html
 (markdown :variables markdown-command "pandoc")
 (windows-scripts :toggle
                  (eq system-type 'windows-nt))
 (shell-scripts :toggle
                (or
                 (eq system-type 'darwin)
                 (eq system-type 'gnu)))
 (shell :variables shell-enable-smart-eshell t)
 syntax-checking
 (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left)
 (osx)
 graphviz nixos systemd
 (c-c++ :variables c-c++-enable-clang-support t c-c++-backend 'lsp-ccls)
 protobuf
 (go :variables go-tab-width 4 go-backend 'lsp)
 lua rust
 (clojure :variables clojure-backend 'cider clojure-enable-linters 'clj-kondo clojure-enable-clj-refactor t)
 erlang
 (python :variables python-test-runner 'pytest python-backend 'lsp python-lsp-server 'pylsp python-fill-column 88)
 (julia :variables julia-backend 'lsp julia-mode-enable-ess nil)
 haskell java elm
 (zig :variables zls-backend 'lsp zig-format-show-buffer nil zig-format-on-save t zig-return-to-buffer-after-format t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
there's one thing not very clear to me. After M-x all-the-icons-install-fonts, the fonts should already be installed.

Why do you have a separate step "Install the downloaded .ttf fonts"?

**Comment by fleimgruber** [comment]
I just did M-x all-the-icons-install-fonts again and the minibuffer says (and said) ` Successfully downloaded ‘all-the-icons’ fonts to ‘c:/Users/LeimgruberF/tmp/’!` upon which I installed them manually as noted in repro steps as I assumed this was necessary after download.

Only now I looked into `*Messages*` and it shows:

```
Wrote c:/Users/LeimgruberF/tmp/all-the-icons.ttf
 Successfully downloaded ‘all-the-icons’ fonts to ‘c:/Users/LeimgruberF/tmp/’!
ImageMagick error: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/562 [289 times]
user-error: Minibuffer window is not activeImageMagick error: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/562
ImageMagick error: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/562 [410 times]
```
I compiled Emacs via MSYS2 Mingw64 and it seems imagemagick is not installed / used correctly?

**Comment by lebensterben** [comment]
Okay after checking the source code of `all-the-icons-install-fonts`, I do find that it doesn't install the fonts on non *nix system.

So it's necessary to install the fonts manually on Windows.

---

The "icons" are actually unicode fonts and should work correctly with or without imagemagick. But I do recommend you to make sure it works properly.

---

To make sure the fonts are installed, can you try to open a GUI app such as Word to verify its available? Alternatively I think you should also be able to manage fonts in control panel.

(Also you may need to restart Emacs after you installed the font but I assume you've done this already.)

**Comment by fleimgruber** [comment]
> So it's necessary to install the fonts manually on Windows.

Thanks for looking into it and confirmation.

> To make sure the fonts are installed, can you try to open a GUI app such as Word to verify its available?

The fonts are available in system font settings and apps.

> (Also you may need to restart Emacs after you installed the font but I assume you've done this already.)

That and the OS as well, out of habit.

> The "icons" are actually unicode fonts and should work correctly with or without imagemagick. But I do recommend you to make sure it works properly.

Will try, but I don't have an idea where to debug this at the moment. Somewhere along the way in M-x treemacs-icon-catalogue the errors are triggered, but I don't know if Emacs uses a subprocess, e.g. the imagemagick `convert` CLI tool, or whether it uses a .dll directly. I assume it uses `convert` at some point for scaling the images, but I will need to find the place in the elisp source code I guess...

**Comment by fleimgruber** [comment]
I just found https://legacy.imagemagick.org/discourse-server~/viewtopic0814.html which might contain the solution. Is it possible to set the command that Emacs uses for imagemagick from `convert` to `magick`?

**Comment by lebensterben** [comment]
Can you try WSL2?

**Comment by fleimgruber** [comment]
> Can you try WSL2?

I tried that some time ago, it was a bumpy ride or I gave up too early, in any case, it never quite worked for me.

**Comment by fleimgruber** [comment]
I just found the solution via https://github.com/msys2/MINGW-packages/issues/1885, i.e. adding the mentioned 3 env vars solves this for me. Thanks for your support as always.

**Comment by lebensterben** [comment]
as for 
> Is it possible to set the command that Emacs uses for imagemagick from convert to magick

The answer is yes since you can change the source code...

But it doesn't worth it.

You should try to re-install imagemagick.

**Comment by lebensterben** [comment]
Reopening since I think we can mention this in FAQ at least.
