### ISSUE TITLE
c-w should delete word backwards in insert mode even if autocomplete is open.

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#15408]
Reopen of https://github.com/syl20bnr/spacemacs/issues/4243 because it was auto-closed.

> When the autocomplete window is open, c-w no longer deletes backwards. This seems like a pretty big bug, though it's likely the result of some conflict of packages/layers (again, I'm new to Emacs).
> 
> This is my entire config:
> 
>   (load-theme 'spacemacs-light t)
>   (set-face-attribute 'mode-line nil :box nil)
>   (set-face-attribute 'mode-line-inactive nil :box nil)
>   ;; Don't highlight line
>   (global-hl-line-mode -1) ; Disable current line highlight
>   (setq evil-want-fine-undo nil)
>   (setq evil-move-cursor-back nil)
>   (global-set-key (kbd "s-p") 'helm-M-x)
>   ; (setq powerline-default-separator 'utf-8)
>   (setq powerline-default-separator nil)
>   (global-vi-tilde-fringe-mode -1)
> 
> These are my enabled layers:
> 
>      company
>      ;; To toggle autocompletion on:
>      ;; space t a 
>      auto-completion
>      ;; better-defaults
>      emacs-lisp
>      themes-megapack
>      ;; Basic mac keybindings. (Cmd is super, alt is meta)
>      osx
> 
> The version of spacemacs I'm using is master as of today.

**Comment by lebensterben** [comment]
I reopened the original issue.
