### ISSUE TITLE
mu4e buffer is read only

### ISSUE THREAD

**Issue by rommeswi** [syl20bnr/spacemacs#15409]
#### Description :octocat:
mu4e does not start from home buffer a second time after closing it with q

#### Reproduction guide :beetle:
- Start Emacs
- Make sure home screen is visible
- SPC a e m to start mu4e
- q to quit mu4e
- Make sure home screen is visible
- SPC a e m to start mu4e again

*Observed behaviour:* :eyes: :broken_heart:
Mu4e does not start. Instead, it gives a message that the mu4e buffer is
read-only. Interestingly, this only occurs on the home screen but not when in
another file.

*Expected behaviour:* :heart: :smile:
Mu4e should start again

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. efdfecbf8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html ivy auto-completion emacs-lisp
      (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
      git bibtex latex pdf mu4e multiple-cursors org spell-checking treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
```

**Comment by lebensterben** [comment]
Please M-x toggle-debug-on-error, and post the backtrace.

**Comment by smile13241324** [comment]
Looks like I am not able to easily reproduce your issue. I have installed mu4e and setup an empty mail dir. When I am entering the home screen I can open the mu4e buffer and close it with q again. I can do this twice without getting a read only buffer message.

Is there anything else you have done that I have missed?

**Comment by rommeswi** [comment]
`
  (with-eval-after-load 'mu4e
    ;; Do not reply to self - it is also necessary to set mu4e-user-mail-address-list
    (setq mu4e-compose-dont-reply-to-self t)
    ;; ISO date display:
    (setq mu4e-headers-date-format "%F")
    ;; Remove quit confirmation
    (setq mu4e-confirm-quit nil)
    ;; Set up link to mbsync
    (setq mu4e-get-mail-command "mbsync -qa")
    ;; Avoid duplicate UIDs and wrong UID names
    (setq mu4e-change-filenames-when-moving t)

    ;; This sets up org-contacts
    (setq mu4e-org-contacts-file  "DIRECTORY NAME HERE")
    (add-to-list 'mu4e-headers-actions
                 '("org-contact-add" . mu4e-action-add-org-contact) t)
    (add-to-list 'mu4e-view-actions
                 '("org-contact-add" . mu4e-action-add-org-contact) t)
    ;; View Emails in Browser
    (add-to-list 'mu4e-view-actions '("ViewInBrowser" . mu4e-action-view-in-browser) t)
    ;; Close message after sending message
    (setq message-kill-buffer-on-exit t)
    )
`

These are the additional commands I have in my dotfile that are relevant to mu4e. Here are also my settings regarding the home buffer:

`
   dotspacemacs-startup-buffer-responsive t
   dotspacemacs-home-shorten-agenda-source nil
`

I cannot see anything suspicious that would be related to this problem.

**Comment by smile13241324** [comment]
Thanks for the info I will have another try.
