### ISSUE TITLE
Spacemacs org-layer too slow on medium size org-mode files

### ISSUE THREAD

**Issue by otilimp** [syl20bnr/spacemacs#15416]
For org-mode files with size between 0.5M and 1.0M, Spacemacs takes (which is extremely slow on my laptop, and sometimes emacs will freeze) nearly 10 times more than neovim shipped with `nvim-orgmode/orgmode`  to open it. 

Do you have any suggestions to **speed up the opening process** or **improve the experience of working with large org-mode files** on Spacemacs?

**Comment by otilimp** [comment]
Site for nvim-orgmode/orgmode: https://github.com/nvim-orgmode/orgmode (sorry for closing the issue by clicking the wrong button)

**Comment by lebensterben** [comment]
@otilimp 

Can you share a large org file with no sensitive information so I can test?

**Comment by otilimp** [comment]
> @otilimp
> 
> Can you share a large org file with no sensitive information so I can test?



@lebensterben  I made a large org file and I am sure there is no sensitive information in it (in large-org.zip). 
[large-org.zip](https://github.com/syl20bnr/spacemacs/files/8308931/large-org.zip)

I've tested Spacemacs' org layer performance on emacs 28 and I can feel much performance boost but 
it's still much slower than neovim.

**Comment by otilimp** [comment]
Switching to emacs 28 has speeded up the openning process, however when I try scrolling up and down I can still feel Spacemacs lagging on large org files.

**Comment by lebensterben** [comment]
please share your system information via SPC h I

**Comment by otilimp** [comment]
It's a relative old distro and I had no choice but to use Spacemacs master branch.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 297b23128)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(python auto-completion better-defaults emacs-lisp helm yaml markdown org
spell-checking syntax-checking version-control)
```

**Comment by otilimp** [comment]
> > @otilimp
> > Can you share a large org file with no sensitive information so I can test?
> 
> @lebensterben I made a large org file and I am sure there is no sensitive information in it (in large-org.zip). [large-org.zip](https://github.com/syl20bnr/spacemacs/files/8308931/large-org.zip)
> 
> I've tested Spacemacs' org layer performance on emacs 28 and I can feel much performance boost but it's still much slower than neovim.

What I mean there is that I've tested emacs 28 with similar configuration (but with develop branch of Spacemacs) on another environment.

**Comment by lebensterben** [comment]
master branch won't be maintained.

**Comment by otilimp** [comment]
> master branch won't be maintained.
> 
> Is performance an issue on develop branch with Emacs 27?

Then I'm sorry to report a bigger issue (maybe). 

First I need to say I'm not an Emacs expert. The combination of Spacemacs develop branch and the Emacs 27.1  usually fail to install org-layer. Detailed situations vary with emacs version and the developing of Spacemacs.

I'm not quite familiar with Emacs package management mechanism and It's a little hard for me to understand the  behaviors of Spacemacs on different emacs version at least for now.

**Comment by otilimp** [comment]
What I observe for a long time is that relatively old emacs (like 26 and 27.1) or too new emacs (>=29, built from source) will fail to fetch certain packages (situations vary with the development of spacemacs) while initializing.

**Comment by lebensterben** [comment]
you can open a new issue for that. but packages are downloaded via packages.el. So that should be reported in upstream.
