### ISSUE TITLE
Inaccurate documentation about semantic highlighting for c-c++ layer 

### ISSUE THREAD

**Issue by zerolfx** [syl20bnr/spacemacs#15417]
https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/c-c%2B%2B/README.org#semantic-highlighting
https://develop.spacemacs.org/layers/+lang/c-c++/README.html#lsp

It says semantic highlighting supports both `ccls` and `clangd`, but in fact only `ccls`.

**Comment by lebensterben** [comment]
nope clangd supports that.

this might be a bug from lsp-mode. (could be caused by changes in LSP)

**Comment by zerolfx** [comment]
On the same page:

> ccls server
Install the ccls server. See instructions. This is currently the most fully featured implementation, including semantic highlighting and some navigation/ introspection features **that are not provided by clangd**.

So is this part of documentation incorrect?

**Comment by zerolfx** [comment]
As for lsp-mode, it has an option of `lsp-semantic-tokens-enable`, which defaults to `nil`.

But enabling `c-c++-lsp-enable-semantic-highlight` doesn't enable `lsp-semantic-tokens-enable` or produce any semantic highlighting when using clangd as backend.

**Comment by lebensterben** [comment]
> So is this part of documentation incorrect

You can assume lots of the documentations are outdated...

**Comment by lebensterben** [comment]
> enabling c-c++-lsp-enable-semantic-highlight doesn't enable lsp-semantic-tokens-enable or produce any semantic highlighting when using clangd as backend

semantic token and semantic highlighting seems to be two different features.
