### ISSUE TITLE
TypeScript layer requires html and auto-complete to recognize .tsx 

### ISSUE THREAD

**Issue by joshmccall221** [syl20bnr/spacemacs#15412]
#### Description :octocat:
`typescript` layer requires `auto-completion` and  `html` to recognize `.tsx` files.
https://develop.spacemacs.org/layers/+lang/typescript/README.html

#### Reproduction guide :beetle:
- Start Emacs

```
   dotspacemacs-configuration-layers
   '(
     ;;auto-completion
     ;;html
     typescript
     )
```
- `SPC q r`
- open `.tsx` file

*Observed behaviour:* :eyes: :broken_heart:

Buffer is in `Fundamental` mode instead of `Typescript-tsx`

*Expected behaviour:* :heart: :smile:

Same behavior as :
```
   dotspacemacs-configuration-layers
   '(
     auto-completion
     html
     typescript
     )
```
note: if you don't see change in buffer, kill buffer and restart emacs, open buffer. 

#### System Info :computer:
- OS: darwin
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. e32acdfad)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(typescript)
```
- System configuration features: NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
Typescript layer should declare appropriate layer dependencies in this case. For this a layers.el file can be created.

See documentation for details.
