### ISSUE TITLE
Include copyright compliance guidelines in `CONTRIBUTING.org`

### ISSUE THREAD

**Issue by bryce-carson** [syl20bnr/spacemacs#15423]
Per #14722, the [CONTRIBUTING.org](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org) file needs to be updated to include guidance on copyright for third-party works, such as images in layer READMEs.

Decide on a canonical format, such as [footnotes](https://orgmode.org/manual/Creating-Footnotes.html) for URLs to copyright notices and upstream sources.

**Comment by lebensterben** [comment]
it's not necessary to open a new issue for each sub-task...

PR can be used as tasks too.
