### ISSUE TITLE
Nothing to match for 'helm-imenu-in-all-buffers'

### ISSUE THREAD

**Issue by bitozoid** [syl20bnr/spacemacs#15420]
#### Description :octocat:
Nothing to match for 'helm-imenu-in-all-buffers'

#### Reproduction guide :beetle:
- Start Emacs
- Open an org buffer
- type `SPC j I` (`helm-imenu-in-all-buffers`)
- type some keys

*Observed behaviour:* :eyes: :broken_heart:
Nothing is found in helm buffer. So that, typing a pattern shows no items.

*Expected behaviour:* :heart: :smile:
A behaviour similar to `SPC j i` (`helm-imenu`), where headings appear in the helm buffer and typing filters them in.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 18ad9759b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF PNG RSVG SOUND DBUS GCONF GLIB NOTIFY INOTIFY LIBXML2 FREETYPE LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
No elisp error, no backtrace.

**Comment by lebensterben** [comment]
do you see any error if you M-x toggle-debug-on-error

**Comment by bitozoid** [comment]
@lebensterben Not at all.

**Comment by smile13241324** [comment]
Found the issue and pushed a fix please have another try @bitozoid

**Comment by bitozoid** [comment]
It works!
