### ISSUE TITLE
Cannot `p`, `P` from  Windows clipboard, but `shift-insert` will work

### ISSUE THREAD

**Issue by mirkov** [syl20bnr/spacemacs#15434]
#### Description :octocat:
Cannot yank from Windows clipboard with `p`, `P` and the items are not available in kill-ring, but *shift-insert* works

#### Reproduction guide :beetle:
- Start Emacs
- Copy text from Windows app (Ctrl-C)
- `p` or `P` (bound to `eval-paste-before/after`), pasts the most recent Emacs copy

*Observed behaviour:* :eyes: :broken_heart:
- The text on Windows clipboard does not show on the kill ring
- *BUT* shift-insert (bound to `yank`) will paste the entry (thanks to Daniel Nicolai for this workaround)

*Expected behaviour:* :heart: :smile:
To paste from Windows clipboard

#### System Info :computer:
- OS: windows-nt
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 18ad9759b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv auto-completion better-defaults emacs-lisp helm lsp treemacs spell-checking syntax-checking markdown html latex bibtex org git version-control common-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
No error issued, no backtrace possible

**Comment by mirkov** [comment]
I believe the issue should be labeled a _bug_, and not _help wanted_. But I will not mind if it is shown that the problem is on my end and due to my Spacemacs set-up :-)

**Comment by lebensterben** [comment]
@mirkov 

- this is not confirmed yet.
- I don't have Windows.

**Comment by mirkov** [comment]
The problem is now gone. `p` and `P` works as expected - I have no idea what changed. 

I will keep this open for a bit longer. If the issue does not reccur within a week I will close it.

**Comment by mirkov** [comment]
This issue has gone away - I have no explanation for the observed behavior.

I will close it.
