### ISSUE TITLE
Helm problem after updating spacemacs

### ISSUE THREAD

**Issue by jia-j-chen** [syl20bnr/spacemacs#15439]
#### Description :octocat:
Helm error after updating spacemacs.

#### Reproduction guide :beetle:
- git pull in ~/.emacs.d/
- Start emacs
- Update packages by using SPC f e U
- Re-start emacs
- Try to find recent files by using SPC f f (or SPC b b or SPC l l)

*Observed behaviour:* :eyes: :broken_heart:
Receive an error: "Wrong number of arguments: (1 . 1), 2", and there is no list of recent files.

*Expected behaviour:* :heart: :smile:
Expect to see recent files.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 97af6fa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(csv python bibtex html helm auto-completion better-defaults emacs-lisp git markdown org ess
     (chinese :variables chinese-enable-fcitx t chinese-fcitx-use-dbus t pyim-default-scheme 'microsoft-shuangpin)
     latex ranger pdf
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     version-control
     (mu4e :variables mu4e-use-maildirs-extension t mu4e-installation-path "/usr/share/emacs/site-lisp" mu4e-enable-async-operations t mu4e-maildir "/home/chenj/Maildir" mu4e-sent-folder "/Local_sent" mu4e-headers-full-search nil mu4e-headers-results-limit 500 mu4e-drafts-folder "/Drafts" mu4e-trash-folder "/Deleted_Messages" mu4e-attachment-dir "~/Downloads" mu4e-get-mail-command "offlineimap" mu4e-view-show-images t mu4e-view-show-addresses t mu4e-headers-date-format "%Y-%m-%d %H:%M" mu4e-compose-reply-to-address "jia.j.chen@foxmail.com" user-mail-address "jia.j.chen@foxmail.com" user-full-name "Jia CHEN" send-mail-function 'async-smtpmail-send-it message-send-mail-function 'async-smtpmail-send-it smtpmail-smtp-server "smtp.qq.com" smtpmail-smtp-service 465 smtpmail-stream-type 'ssl smtpmail-auth-credentials
           (expand-file-name "~/.authinfo.gpg")
           mu4e-headers-fields
           '((:date . 18)
             (:flags . 6)
             (:from . 15)
             (:to . 15)
             (:subject))
           mu4e-compose-signature "Jia CHEN @ http://chenjia.gsm.pku.edu.cn" mu4e-maildir-shortcuts
           '(("/INBOX" . 105)
             ("/PKU_Email" . 112)
             ("/Sent_Messages" . 115)))
     bm
     (colors :variables colors-colorize-identifiers 'all))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by jajpater** [comment]
It is exactly the same as #15438. So this issue can be closed.
