### ISSUE TITLE
invalid number of arguments (1 . 1), 2 in helm-flx

### ISSUE THREAD

**Issue by stkain** [syl20bnr/spacemacs#15438]
#### Description :octocat:
SPACE SPACE results in invalid number of arguments (1 . 1), 2
SPACE b b results in the same error
spacemacs is currently unusable

#### Reproduction guide :beetle:
- Start Emacs
fresh .emacs.d clone, no .spacemacs file, so absolutely fresh

*Observed behaviour:* :eyes: :broken_heart:
SPACE SPACE does not work anymore

*Expected behaviour:* :heart: :smile:
should work

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 97af6fa9f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
cannot copy backtrace here.
error seems to occur in helm-flx-fuzzy-highlight-match
```

**Comment by lebensterben** [comment]
try to use ivy or compleseus for now

**Comment by stkain** [comment]
Hello, how do I do this?
the problem even occurs, if I comment out helm in .spacemacs

**Comment by stkain** [comment]
Ok,
In .spacemacs 
 I commented out helm and put in ivy --> restart
now SPACE SPACE works again :-)

**Comment by emiltoacs** [comment]
Hi thanks for the tip to replace Helm by Ivy, its a good workaround.

I have the same issue the exact error message is:
`helm-fuzzy-highlight-matches: Wrong number of arguments: (1 . 1), 2`
It happens since I updated my package some minutes ago so it really seems to be related to the helm package itself. Just as you it blocks all commands that uses helm.

**Comment by lebensterben** [comment]
The problem must be caused by upstream changes.

**Comment by JDawson-Camlin** [comment]
I did `SPC f e U` to update Spacemacs' packages and now Spacemacs has this problem. How can I undo the update?

**Comment by forgoty** [comment]
Same error. Installing ivy and comment helm will fix the problem at first sight. I want helm working again.

**Comment by svenpanne** [comment]
For a workaround, see my comment at 
https://github.com/emacs-helm/helm/commit/16ab10d4b8213594e09c3164025c57a6fe9c6cf6#commitcomment-70157730

**Comment by smile13241324** [comment]
Hmpf, seems like there are a lot of breaking chances in the helm project lately 🤔.

I'll update my packages and see if we need to change something on our side.

**Comment by DaryCC** [comment]
Same thing happened to me, So frustrating   I just wish I had read this before, i just did a pop os reinstallation. :(

**Comment by smile13241324** [comment]
Sorry guys but this really looks like a helm internal issue. I will open a bug report upstream  until this is solved please switch over to ivy.

You can do so by removing helm from your layers list and add ivy instead.

**Comment by smile13241324** [comment]
Looks like Helm is only accepting bug reports from vanilla Emacs users. Unfortunately I am completely out of my wits when it comes to vanilla emacs, can one of you do a quick reproduction with vanilla emacs and post a backtrace? I could then file an issue on the helm project if this is still necessary.

Now I need to get back in my bed, Covid is dragging me down again :(.

**Comment by svenpanne** [comment]
I don't really understand why helm doesn't just make the single function making problems more permissive in its arguments... :disappointed:

**Comment by lebensterben** [comment]
workaround for helm-flx

https://github.com/emacs-helm/helm/commit/16ab10d4b8213594e09c3164025c57a6fe9c6cf6#r70173993

**Comment by lebensterben** [comment]
they did not declare the calling convention as obsolete before changing this public API. that's a problem.

**Comment by svenpanne** [comment]
OK, the helm-flx fix works for me, too, now the question is: Can helm-flx be fixed quickly or can the spacemacs project add a hack to incorporate the fix somehow? helm-flx looks a bit dead IMHO, >4 years without a commit.

**Comment by jajpater** [comment]
You could make a pull/merge request for the helm-flx?

**Comment by jajpater** [comment]
@PythonNut accepted the pull request by @nigredo-tori. Updating the packages from MELPA solved the problem for me. I guess this issue can be considered closed.

**Comment by stkain** [comment]
Hello,

can confirm. issue is fixed.
Thank you for your help, folks!
