### ISSUE TITLE
Typescript and Typescript TSX modes don't contain `SPC m g b` keybind

### ISSUE THREAD

**Issue by Invertisment** [syl20bnr/spacemacs#15442]
#### Description :octocat:

I use develop version of spacemacs and I'm on commit `97af6fa9f`.

When I open a `*.ts` or `*.tsx` file the mode is `typescript-mode` and `typescript-tsx-mode` which is great. But I want to jump to definition (which works) and jump back to the previous file which I can't do.

The documentation of develop says that there should be a keybinding `SPC m g b` but it doesn't exist in the editor:
https://develop.spacemacs.org/layers/+lang/typescript/README.html#typescript-major-mode

#### Reproduction guide :beetle:
1. Create three `*.ts` or `*.tsx` files and create a function or a class.
2. Import files this way: A -> B -> C (first imports the second, second imports third).
3. Jump to the definition of that class using `SPC m g g` and then one more time.
4. Go back to the second file using `SPC m g b`.
5. Go back to the first file using `SPC m g b`.

*Observed behaviour:* :eyes: :broken_heart:
`SPC m g b` keybinding doesn't exist.

*Expected behaviour:* :heart: :smile:
It should return to the second buffer and then in the second time it should return to the first buffer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 97af6fa9f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(windows-scripts asciidoc yaml
                 (python :variables python-test-runner 'pytest)
                 javascript
                 (typescript :variables typescript-backend 'lsp typescript-linter 'eslint typescript-fmt-on-save t)
                 html yaml
                 (go :variables go-use-golangci-lint t go-format-before-save t gofmt-command "goimports" go-tab-width 2)
                 (lsp :variables lsp-ui-doc-enable nil lsp-ui-sideline-enable t lsp-ui-sideline-show-code-actions t lsp-headerline-breadcrumb-enable nil)
                 (clojure :variables clojure-enable-clj-refactor t clojure-backend 'cider clojure-enable-linters 'clj-kondo clojure-pprint-fn 'fipp)
                 react
                 (java :variables java-backend 'lsp lsp-java-vmargs
                       '("java.format.settings.url" : "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml"))
                 (auto-completion :variables auto-completion-enable-help-tooltip nil)
                 (plantuml :variables plantuml-jar-path "~/bin/plantuml.jar")
                 emacs-lisp helm lsp spell-checking
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 treemacs sql sqls)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by lebensterben** [comment]
please follow the guidances on issue template.

**Comment by Invertisment** [comment]
Ok. I'll update the issue.
I resolved it for myself though by adding this to my config:
```

**Comment by smile13241324** [comment]
You are using an LSP backend for these the bindings are defined in the LSP layer. The bindings defined in the typescript layer are only for build in backends. Looks like the README wasn't very clear about this.

The binding `SPC g b` is missing in the LSP scheme however it definitely makes sense. I will add it there.

**Comment by Invertisment** [comment]
I don't remember why other layers didn't work well for me. I think that I liked the LSP's usability better and that was the deciding factor. I made this decision long time ago and didn't even think to look into README. For some time it worked really well and I sticked with it.

I would prefer if the binding in the TS layer would work the same as in Clojure layer but I think it's based on CIDER and not LSP. I don't think it helps.

**Comment by smile13241324** [comment]
Ok we once tried to move the responsibility for lsp bindings to the lsp package but this seems to have gone wrong. I have reactivated our own binding procedure now. This includes all bindings in the LSP layer including the bindings to jump forward and backward on `SPC m g b`.

Yeah the clojure layer also has support for different backends. Cider is designed differently it is mostly based on lisps ability for inline evaluation. LSP behaves rather like a modern IDE hence it does a lot in the background and tends to be slower than other solutions also it is dependent on a project to work. For the future the LSP interface is universally used by a lot of IDEs so additional functions will rather be implemented in the LSP layer/package than in emacs/spacemacs itself.

Anyway please check the latest version and make sure you have a proper project setup. Than check whether the proper bindings are now in place and close this ticket if it does.

**Comment by Invertisment** [comment]
It works great!
