### ISSUE TITLE
Provide a option to enable CtrlP for file searching

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1544]
I think many Vim users are used to CtrlP plugin. It would be nice if we provide a spacemacs option i.e. `spacemacs-enable-ctrl-p` to use `CtrlP` for a combined all in one Spacemacs source for file navigation (Helm Projectile sources can be combined and used outside of any directory fine). Here is an example of such command using `helm-multi-files`:

``` elisp
(setq helm-for-files-preferred-list '(helm-source-buffers-list
                                      helm-source-buffer-not-found
                                      helm-source-projectile-projects
                                      helm-source-projectile-files-list
                                      helm-source-recentf
                                      helm-source-bookmarks
                                      helm-source-file-cache
                                      ;; helm-source-files-in-current-dir
                                      ))

(define-key evil-normal-state-map (kbd "C-p") 'helm-multi-files)
```

We can then say to use original CtrlP command in Vim, simply press `M-/`.

**Comment by tuhdo** [comment]
Or we could just use `helm-projectile-sources-list` and add the above sources and simply use `helm-projectile` command. The difference is that you can invoke `helm-locate` from `helm-multi-files` with `C-c C-p`, but then adding Helm Projectile sources to `helm-for-files-preferred-list` will cause error because Helm Projectile is not yet loaded.

**Comment by syl20bnr** [comment]
This is interesting, `C-S-p` could be used as well, I don't think it is used in spacemacs.

**Comment by tuhdo** [comment]
I think we should just use `Ctrl-p`, since `C-S-p` won't work in terminal (which many Vim users are accustomed to) and let user choose it. `Ctrl-p` is easer to press as well.

**Comment by syl20bnr** [comment]
So we have to find another key for hippie-expand. I know thhere is already one on `M-` but in Vim style we use `C-` instead, `M-` is not really necessary as opposed with Emacs which is modifier driven.

**Comment by tuhdo** [comment]
So how about `C-/` (for Vim style only)? `C-/` is bond to `undo-tree-undo`, but it already exists with `C-u`. And `C-/` is symmetric: instead moving your pinky above, you move below the `;` key.

**Comment by catesandrew** [comment]
+1 for `C-p` even though syl20bnr makes a strong argument against it. Coming from vim this command is so heavily used, it just needs to be `C-p`. For me, I gave up evil pop but can still use that with `M-y`, which i'm more used to using anyways with emacs.

**Comment by opyate** [comment]
Just my 2 cents from someone coming here having had experience with ```Ctrl-p``` under ```Vim``` and looking for "open file" functionality. You can [open a file](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#files-manipulations-key-bindings) using ```SPC f f```. It doesn't search recursively, but then I keep my projects small and don't need it.

**Comment by BorisVerk** [comment]
`C-c p f` which is `projectile-find-file` does what I was looking for.

**Comment by sdwolf** [comment]
Also my 2¢, I am a `C-p` vim user. When switching to Spacemacs I found out about `SPC p f` which is `helm-projectile-find-file`. This is the CtrlP equivalent AFAIC.

**Comment by kensupermen** [comment]
I am a vim user. When I switching to Spacemacs. I config like this(remember to reload your spacemacs):
`(define-key evil-normal-state-map (kbd "C-p") 'helm-projectile-find-file)`
So now, you can use like CtrlP.

**Comment by dkrieger** [comment]
Is there a way to make projectile treat the current directory as if it were a project dynamically, i.e. without actually placing an empty .projectile file in the dir? This is how I have fzf configured to work in vim, and it's extremely useful. If i'm in netrw, it uses '%', if I'm in a file, it uses '%:h'
