### ISSUE TITLE
Magit: selective staging not working after update

### ISSUE THREAD

**Issue by mirkov** [syl20bnr/spacemacs#15454]
#### Description :octocat:
Magit: s in visual-state should call magit-stage-item

#### Reproduction guide :beetle:
- Start Emacs
- Open magit session
- Select file
- Press `v` to select a line
- Optionally navigate to adjacent lines to select them as well
- Press `s` to commit the lines

*Observed behaviour:* :eyes: :broken_heart:
I see `s-` in the mini-buffer

*Expected behaviour:* :heart: :smile:
The selected lines to be committed

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 5c0650282)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv auto-completion better-defaults emacs-lisp helm lsp treemacs spell-checking syntax-checking markdown html latex bibtex org git version-control common-lisp
     (scheme :variables scheme-implementations
             '(mit)))
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP

#### Backtrace :paw_prints:
No backtrace to submit

#### Notes:

I updated Spacemacs after many months. Thus, I cannot narrow down when this issue appeared.
This issue seems identical to bug 1642

**Comment by lebensterben** [comment]
same as #15448 ?
