### ISSUE TITLE
Evil macro recorded characters don't match with inserted ones

### ISSUE THREAD

**Issue by Invertisment** [syl20bnr/spacemacs#15457]
#### Description :octocat:
Macro that inserts chars in insertion mode doubles `o` symbol when `o` is inserted in evil insertion mode.
(This sometimes inserts `i` and in some other cases even multiple characters but I couldn't isolate these)
(It's also possible that `f` gets inserted instead of some other letter and I couldn't isolate that one too)

#### Reproduction guide :beetle:
- Start Emacs
- Use VI editing bindings
- Open a buffer (I tried in clojure and scratch layers, they work the same)
- You may add some newlines, this doesn't have any effect
- Record a macro using VI bindings (press these keys):
`qqafoo`
- Then press `<Enter>`, `<Esc>` and `q` to end the macro.
- Then Repeat the macro one or several times: `@q`

*Observed behaviour:* :eyes: :broken_heart:
In this particular example the macro prints `fooo` instead of `foo`.
This throws me off and shows that something doesn't bind up correctly in the macro replay or recording.

*Expected behaviour:* :heart: :smile:
The macro should've inserted `foo` instead of `fooo`.
If you'd open `vim` and you'd press these keys on a buffer then you'd get `foo` and not `fooo`.
I think this is a long time problem with the macro recorder but I didn't report it for a long time as I only insert `oo` so much.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 6774f37fc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(windows-scripts asciidoc yaml
                 (python :variables python-test-runner 'pytest)
                 javascript
                 (typescript :variables typescript-backend 'lsp typescript-linter 'eslint typescript-fmt-on-save t)
                 html yaml
                 (go :variables go-use-golangci-lint t go-format-before-save t gofmt-command "goimports" go-tab-width 2)
                 (lsp :variables lsp-ui-doc-enable nil lsp-ui-sideline-enable t lsp-ui-sideline-show-code-actions t lsp-headerline-breadcrumb-enable nil)
                 (clojure :variables clojure-enable-clj-refactor t clojure-backend 'cider clojure-enable-linters 'clj-kondo clojure-pprint-fn 'fipp)
                 react
                 (java :variables java-backend 'lsp lsp-java-vmargs
                       '("java.format.settings.url" : "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml"))
                 (auto-completion :variables auto-completion-enable-help-tooltip nil)
                 (plantuml :variables plantuml-jar-path "~/bin/plantuml.jar")
                 emacs-lisp helm lsp spell-checking
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 treemacs sql sqls)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:

- The interesting thing is that the recording already contains the three `o`.
This is the value of the register `q` from the `:reg` menu:

```
q          a f o o o <return> <escape>
```

I'm not sure why the recorded macro register contains three `o` characters to replay.
This may probably be some artifact from the past.

**Comment by Invertisment** [comment]
This is something really peculiar. Because this time I was trying to rerun the experiment and I entered this to be recorded:
```
foo
```
But the register now contains only this:
```
q          o f o o <return> <escape>
```

And then I tried to enter more text and it came back:
```
q          a h e l l o SPC f o o o SPC h i <return> <escape>
```
And then I tried to enter `foo` again and it's back:
```
q          o f o o o <return> <escape>
```

**Comment by bryce-carson** [comment]
@Invertisment I was not able to reproduce the issue.
I also tried recording a new macro with more text inserted and was still unable to reproduce the issue.

```
q          a h e l l o SPC w o r l d SPC f o o SPC b a r SPC b a z z <backspace> <backspace> <backspace> <backspace> d o SPC Y o u SPC <C-backspace> <C-backspace> D o SPC y o u SPC l i k e SPC J a z z ? <return> <escape>
```

**Comment by Invertisment** [comment]
For a moment I thought that it somehow it magically fixed itself. But it didn't :/

I also tried to click random chars and got this instead (first line is me recording a macro with backspaces and so on):
```
afa88af8a8aaffffoofofoofofofoasasaiqiqiqiqi     9090()___affoofoofooo
afaa88af88a8aaffffoofoofooofoofoofooasasaiqiqiqiqi     9090()___affoofooofoooo
afaa88af88a8aaffffoofoofooofoofoofooasasaiqiqiqiqi     9090()___affoofooofoooo
```
I wrote `a` and it printed `aa`. 
It recorded this:
```
q          a a f a a 8 8 a f 8 8 a 8 a a f f f f o o f o o f o o o f o o f o o f o o a s a s a i q i q i q i q i q <backspace> SPC SPC SPC <backspace> SPC SPC SPC <backspace> SPC 9 0 9 0 ( ) _ _ _ a f f o o f o o o f o o o o <return> <escape>
```

I use Lithuanian language with number row at the top. And I had this issue in my previous laptop too. It's low impact but it's still a problem sometimes when I replace text and need to do a second pass to fix it.

**Comment by Invertisment** [comment]
Also I tried to play with it more and I got this result which is completely strange (first is my line, second is macro line):
```
foofoofoo
foofoofooo
foofoofooo
```
`:reg` output:
```
q          a f o o f o o f o o o <return> <escape>
```

**Comment by bryce-carson** [comment]
Perhaps <kbd>M-x</kbd> `set-input-method` and selecting Lithuanian will help things. I'm not sure, honestly. It may be something with evil, Emacs, or environment variables related to locale. It's a tricky thing!

- https://www.gnu.org/software/emacs/manual/html_node/emacs/Language-Environments.html
- https://stackoverflow.com/questions/27773044/evil-mode-bindings-for-non-english-languages

**Comment by Invertisment** [comment]
Could you try recording `foofoofoo` yourself? Because it was the third that got the additional char. I think it's the same key codes. It could probably be the recorder. I'll try it.

**Comment by bryce-carson** [comment]
I followed your reproduction steps exactly before trying the new macro I described.

For parity, I'll try `foofoofoo` again now.

```
foofoofoo
foofooofooo
foofooofooo
foofooofooo
```

Okay, interesting!

**Comment by Invertisment** [comment]
I tried to change my `set-input-method` to `lithuanian-numeric` and got this result:
```
foofoofoo
fooofooofooo
```
That's... very... consistent...
Also `lithuanian-keyboard` gives me the same result.
What do you use in that field? I think I had some kind of default value as I didn't know about that variable.

**Comment by bryce-carson** [comment]
@Invertisment It appears that the problem is caused by `evil-record-macro`. I was not able to reproduce the issue with the `foofoofoo` string using `kmacro-start-macro-or-insert-counter`, which by default is bound to <kbd>F3</kbd>.

To use Emacs "holy-mode" macro recording:

1. Press <kbd>F3</kbd> to begin recording the macro
2. Input text or perform commands: <kbd>a</kbd> <kbd>foofoofoo</kbd> <kbd>Return</kbd> <kbd>Escape</kbd>
3. Press <kbd>F4</kbd> to finish the defintion
4. Press <kbd>F4</kbd> to play the macro

Can you try using the non-`evil` macro recording to double check?

**Comment by bryce-carson** [comment]
> I tried to change my `set-input-method` to `lithuanian-numeric` and got this result:
> 
> ```
> foofoofoo
> fooofooofooo
> ```
> 
> That's... very... consistent... Also `lithuanian-keyboard` gives me the same result. What do you use in that field? I think I had some kind of default value as I didn't know about that variable.

I don't use anything non-English, so I have the (unfortunate) benefit of that in my computing experience.

Try unsetting the variable using `toggle-input-method` to undo what `set-input-method` did (which was set the input method to Lithuanian, from whatever it was before).

**Comment by Invertisment** [comment]
```
fffffoofofofofofofoofoofoofoo

fffffoofoofoofofofofoofooofooofooo
```

**Comment by bryce-carson** [comment]
```emacs-lisp
;; Using `a' with `kmacro-start-macro-or-insert-counter':
foofoofoo
foofoofoo
foofoofoo

;; Using `i' with `kmacro-start-macro-or-insert-counter':
foofoofoo
foofoofoo
foofoofoo

;; Using `a' with `evil-record-macro':
foofoofoo
foofoofoo
foofoofoo

;; Using `i' with `evil-record-macro':
foofoofoo
foofoofooo
foofoofooo
foofoofooo
foofoofooo
```

This is quite a strange bug. It was occuring with <kbd>a</kdb>, calling `evil-append`, then it wasn't. Then when I decided to move on to <kbd>i</kdb> for `evil-insert` it reared its strange, evil head again.

**Comment by Invertisment** [comment]
This one was recorded after entering the insertion mode with `o` key in VI mode and (after that) pressing F3 and F4 to end the macro (i.e. I'm in the insertion mode throughout the whole macro recording):
```
ffffffofofofofofofoofoofoofoofoofooofooo
ffffffofofofoofoofoofooofooofooofooofooofoooofoooo
```

**Comment by bryce-carson** [comment]
> This one was recorded after entering the insertion mode with `o` key in VI mode and (after that) pressing F3 and F4 to end the macro (i.e. I'm in the insertion mode throughout the whole macro recording):
> 
> ```
> ffffffofofofofofofoofoofoofoofoofooofooo
> ffffffofofofoofoofoofooofooofooofooofooofoooofoooo
> ```

<kbd>o</kbd> runs the command `evil-open-below`, but yeah.

---

1. <kbd>F3</kbd> to begin recording
2. Do things
3. <kbd>F4</kbd> to end recording
4. <kbd>F3</kbd> to play the recording

I assume you meant that. I'm not sure what pressing F3 during a recording would do... Let's find out:

```
foofoofoo0foofoofoo1
foofoofoo2foofoofoo3foofoofoo4foofoofoo5foofoofoo6foofoofoo7foofoofoo8foofoofoo9foofoofoo10foofoofoo11
```

Ah, that's the ⸻`or-insert-counter` part of the "holy" macro recording command name. That's actually neato.

**Comment by Invertisment** [comment]
No. I didn't know what F3 would do inside of a recorded macro.
What I did was I tried to isolate one more case where a macro is started by the holy-mode but with minimal interaction with evil-mode.
I.e. I go into insertion mode before I click F3 and then I click F3. And I begin and end my macro in insertion mode.

**Comment by bryce-carson** [comment]
I'm curious about *this* part of your issue:

<pre>
<b>ffffffofofofofofo</b>foofoofoofoofoofooofooo
<b>ffffffofofo</b>foofoofoofooofooofooofooofooofoooofoooo
</pre>

I can't think of anything that would cause that.

**Comment by bryce-carson** [comment]
> No. I didn't know what F3 would do inside of a recorded macro. What I did was I tried to isolate one more case where a macro is started by the holy-mode but with minimal interaction with evil-mode. I.e. I go into insertion mode before I click F3 and then I click F3. And I begin and end my macro in insertion mode.

That's good debugging. Minimizing the influence of `evil-mode` was a good idea.

**Comment by bryce-carson** [comment]
```
foofoofoo

foofoofoofoofoofoofoofoofoo
foofoofoofoofoofoofoofoofoofoofoofoofoofoofoo
foofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoo
```

This was recorded using the built-in, non-evil recording facilities while `evil-insert-state` was active.

**Comment by Invertisment** [comment]
What does it mean? I can't understand what it is. Did you record `foofoofoo` and then repeated that a lot and it... worked as expected? So it's not emacs recorder?

**Comment by bryce-carson** [comment]
In either case, I think `kmacro-step-edit-macro` will help debug this. It is interactive and proceeds one command at a time; thanks be to Emacs, single keypresses of <kbd>f</kbd> or <kbd>o</kbd> are single commands (our lovely friend `insert-char`).

Can you read this section of the Emacs manual, and see what you can dig up editing the macro interactively, step-wise?

- https://www.gnu.org/software/emacs/manual/html_node/emacs/Keyboard-Macro-Step_002dEdit.html

**Comment by bryce-carson** [comment]
> What does it mean? I can't understand what it is. Did you record `foofoofoo` and then repeated that a lot and it... worked as expected? So it's not emacs recorder?

Yes, I should have said that. `foofoofoo` was recorded, and then played back with many taps of <kbd>F4</kbd> and a couple taps of <kbd>Return</kbd>.

**Comment by Invertisment** [comment]
The docs are too much for me. I also have to do some work. Maybe later.

**Comment by bryce-carson** [comment]
Okay, that's alright. The documentation can be difficult, but it is worthwhile. I'll try a couple things. If and when you do try, can you use this HTML template for your message so I can see when and where things are done?

Make your macro definitions, and replay them, inside the `<pre>` tags in the "Definition:" and "Replay:" sections of the template.

```html
Using <pre>a</pre> with <pre>kmacro-start-macro-or-insert-counter</pre>:
Definition:
<div align="center">
    <pre>
    </pre>
</div>

Replay:
<pre>
</pre>
<hr>

Using <pre>i</pre> with <pre>kmacro-start-macro-or-insert-counter</pre>:
Definition:
<div align="center">
    <pre>
    </pre>
</div>

Replay:
<pre>
</pre>
<hr>

Using <pre>a</pre> with <pre>evil-record-macro</pre>
Definition:
<div align="center">
    <pre>
    </pre>
</div>

Replay:
<pre>
</pre>

Using <pre>i</pre> with <pre>evil-record-macro</pre>:
Definition:
<div align="center">
    <pre>
    </pre>
</div>

Replay:
<pre>
</pre>
```

**Comment by bryce-carson** [comment]
I forgot about your Backtrace, which already showed that the three `o`s appear in the macro ring:

> #### Backtrace 
> * The interesting thing is that the recording already contains the three `o`.
>   This is the value of the register `q` from the `:reg` menu:
> 
> ```
> q          a f o o o <return> <escape>
> ```
> 
> I'm not sure why the recorded macro register contains three `o` characters to replay. This may probably be some artifact from the past.

I'm exhausted of ideas at this point!

**Comment by bryce-carson** [comment]
#10811 reported the same issue four years ago. It's still a valid issue.

**Comment by bryce-carson** [comment]
I wanted to see what commands were being called while doing more testing, so I installed `command-log-mode` and was then unable to reproduce the issue. After finding nothing, because I couldn't reproduce the issue, I removed `command-log-mode` and was then able to reproduce the issue again.

There *may* be some interesting state effect with features, libraries, or deferred loads.

Can you add `command-log-mode` to your `dotspacemacs-additional-packages` list, and add `(use-package 'command-log-mode)` to your `dotspacemacs/user-config` function in your `.spacemacs`, then tell me if you can reproduce the issue after restarting *after* installing the package?

1. Specify `command-log-mode` as an additional package and `use-package` it.
2. <kbd>SPC</kbd> <kbd>f</kbd> <kbd>e</kbd> <kbd>R</kbd>
3. <kbd>SPC</kbd> <kbd>q</kbd> <kbd>r</kbd>
4. Again, <kbd>SPC</kbd> <kbd>q</kbd> <kbd>r</kbd>
5. Try to reproduce the issue

**Comment by Invertisment** [comment]
I've moved on to NVIM. They also don't have this macro problem.

Now I edit Clojure using Conjure and my own small mod/shim to make it trigger Clojure's nREPL test runner (when you go to `Conjure` readme you can see my plugins are also listed under `Mods` there):
https://github.com/olical/conjure#mods
https://gitlab.com/invertisment/conjure-clj-additions-cider-nrepl-mw

Demo:
https://asciinema.org/a/gttCs2OFslyjSmdDEVhw5DIh5

**Comment by lebensterben** [comment]
This should be reported to upstream.

**Comment by Invertisment** [comment]
Should I send an email like in this guide?
https://lists.gnu.org/mailman/listinfo/bug-gnu-emacs

**Comment by lebensterben** [comment]
https://github.com/emacs-evil/evil
