### ISSUE TITLE
`spacemacs/helm-file-do-rg` is not defined

### ISSUE THREAD

**Issue by hoorayphyer** [syl20bnr/spacemacs#15451]
#### Description :octocat:
`spacemacs/helm-file-do-rg` backend is missing for `spacemacs/helm-file-smart-do-search`.

#### Reproduction guide :beetle:
- Install ripgrep
- Start Emacs
- Execute `spacemacs/helm-file-smart-do-search`

*Observed behaviour:* :eyes: :broken_heart:
I got "wrong type argument: commandp, helm-file-do-rg". In my `.emacs.d/layers/+completion/helm/funcs.el`, I don't see `helm-file-do-rg` defined, while there an `helm-file-do-ag` version.

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: darwin
- Emacs: 28.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 5c0650282)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults
                 (c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-clangd c-c++-lsp-enable-semantic-highlight 'rainbow c-c++-enable-clang-format-on-save nil)
                 cmake emacs-lisp git helm
                 (json :variables json-backend 'lsp)
                 (latex :variables latex-build-engine 'luatex latex-enable-auto-fill t latex-enable_folding t latex-refresh-preview t latex-view-pdf-in-split-window t)
                 lsp multiple-cursors pdf
                 (perl5 :variables perl5-backend 'lsp)
                 (python :variables python-backend 'lsp python-lsp-server 'pyright)
                 treemacs)
```
- System configuration features: ACL GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG THREADS TIFF TOOLKIT_SCROLL_BARS XIM XWIDGETS ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
there's no feature parity between different search tools.
