### ISSUE TITLE
loading layout from command line

### ISSUE THREAD

**Issue by DrWaleedAYousef** [syl20bnr/spacemacs#15465]
If you are posting about a *bug* please close this issue and open a new one from within Spacemacs using:
- `SPC h I`
- `M-m h I`

(I = capital i)

If the bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template).

A few optional steps that might help:
- Update `emacs` to latest stable release.
- [Update](https://github.com/syl20bnr/spacemacs#update) `spacemacs`.
- Update all emacs packages. 
  -`M-x configuration-layer/update-packages`. When seeing the prompt, type `y` and then restart emacs with `SPC q r`.
- ~~If you are on Windows, try to restart.~~
  
I am not sure whether it is a bug or mis-use. I try to launch emas from the shell, and open a layout using this:
```
emacs --load=~/MyDocuments/MyScripts/init.el &
```
where `init.el` is:
```
(persp-load-state-from-file "~/MyDocuments/MyScripts/Recording")
```
It never launches the layout `Recording`

**Comment by lebensterben** [comment]
you need to follow the instructions on issue tempplate.

**Comment by DrWaleedAYousef** [comment]
Ok, I submitted a new one with the same title. I will delete this.
