### ISSUE TITLE
__name__ == __main__ ignored in python REPL

### ISSUE THREAD

**Issue by jagjordi** [syl20bnr/spacemacs#15461]
#### Description :octocat:
Python REPL seems to be ignoring `if(__name__ == '__main__')` statements.
This seems to be related to this "feature" 
https://github.com/emacs-mirror/emacs/blob/a715f2fbe70bb4cbb961e82af95e2965030b4513/lisp/progmodes/python.el#L3389
See also: https://github.com/jorgenschaefer/elpy/issues/69
#### Reproduction guide :beetle:
- Start Emacs
- Open python REPL
- Send buffer continaing main 

*Observed behaviour:* :eyes: :broken_heart:
Main is not executed

*Expected behaviour:* :heart: :smile:
Main is executed, or at least there is an option to decide whether it is executed or not

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 9f1155a99)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html typescript systemd rust javascript python spacemacs-editing emacs-lisp git ivy auto-completion lsp ranger
      (conda :variables conda-anaconda-home "/opt/anaconda3/" conda-env-home-directory "~/.conda/")
      markdown multiple-cursors org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking version-control csv pdf yaml treemacs ipython-notebook latex)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS FREETYPE HARFBUZZ XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
please report this to upstream.

**Comment by lebensterben** [comment]
Not even a bug.
Use prefix argument C-u.

**Comment by lebensterben** [comment]
@jagjordi 
SPC u

**Comment by jagjordi** [comment]
@lebensterben If I understand correctly the key sequence should be SPC u SPC m s b? Because that is not working for me :/
