### ISSUE TITLE
a bug make ^L just occupy half a line under linux in page-break-lines.el

### ISSUE THREAD

**Issue by XiaoGeMa** [syl20bnr/spacemacs#15460]
(defcustom page-break-lines-char ?─ 
...........
)
In linux  this symbol  "─" is a two byte char, while in MacOS it's a one byte char. It's "e29480" by utf8.
I found a almost the same one "—" ("e28094" by utf8) that can correct this bug.

**Comment by lebensterben** [comment]
you should report it to upstream.

https://github.com/purcell/page-break-lines/tree/cc283621c64e4f1133a63e0945658a4abecf42ef
