### ISSUE TITLE
Gnus: forwarding a message no longer includes the original message

### ISSUE THREAD

**Issue by DrWaleedAYousef** [syl20bnr/spacemacs#15479]
#### Description :octocat:
In gnus, forwarding or replying no longer includes the original message that is being forwarded or replied.

#### Reproduction guide :beetle:
- Start Emacs
- start gnus
- go to any message
- C-c C-f (to forward)

*Observed behaviour:* :eyes: :broken_heart:
The message buffer is created without including the original message that should be forwarded.

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. b3e67aafe)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv dap c-c++ php systemd
     (latex :variables latex-build-command "LatexMk" latex-enable-auto-fill t latex-backend 'lsp latex-build-engine 'luatex latex-view-pdf-in-split-window t latex-enable-magic t latex-refresh-preview t latex-enable-folding t)
     (bibtex :variables bibtex-enable-ebib-support t ebib-preload-bib-files
             '("~/MyDocuments/Phd/texmf/bibtex/bib/base/publications.bib" "~/MyDocuments/Phd/texmf/bibtex/bib/base/booksIhave.bib")
             ebib-file-search-dirs
             '("~/MyDocuments/Phd/PDF/")
             ebib-import-directory
             '("~/Downloads/"))
     lua
     (html :variable css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t web-fmt-tool 'web-beautify html-enable-leex-support t)
     web-beautify prettier gnus
     (git :variables git-enable-magit-gitflow-plugin t git-enable-magit-svn-plugin t)
     (yaml :variables yaml-enable-lsp t)
     (python :variables python-format-on-save t python-formatter 'yapf python-fill-column 99 python-backend 'lsp python-lsp-server 'pyright)
     (auto-completion :variables auto-completion-enable-help-tooltip t)
     better-defaults emacs-lisp
     (helm :variables helm-enable-auto-resize t helm-no-header t)
     (lsp :variables lsp-lens-enable t)
     (markdown :variables markdown-live-preview-engine 'vmd)
     (chrome :variables)
     multiple-cursors
     (org :variables org-enable-org-contacts-support t org-contacts-files
          '("~/.emacs.d.loadpath/Contacts-Imported.org")
          org-capture-templates
          '(("c" "Contacts" entry
             (file "~/Contacts-Imported.org")
             "* %(org-contacts-template-name))\n:PROPERTIES:\n:EMAIL: %(org-contacts-template-email)\n:END:")))
     (pdf :variables pdf-view-display-size 'fit-page)
     (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
     (spell-checking :variables spell-checking-enable-auto-dictionary t)
     syntax-checking
     (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
we haven't changed anything for gnus.

**Comment by DrWaleedAYousef** [comment]
@lebensterben In fact, it seems to be several problems, all seems to be related to the key-binding. I reported the same problem to gnus, and they told me that: "_it sounds like you're using a bunch of packages/cutomisations that's redefining key bindings. Try removing those._"

**Comment by DrWaleedAYousef** [comment]
UPDATE: I deleted `.emacs.d` completely and re-installed spacemacs anew. Now, gnus does not even create a new message; it just opens an empty buffer with no content. Gnus is very messy with spacemacs; I cannot use my email client.

**Comment by DrWaleedAYousef** [comment]
The problem is still existing; I am using the webmail for the previous months, which is painful after getting used to Gnus. I think the problem is that Gnus is looking for a folder that does not exist: `/home/wyousef/.emacs.d/.cache/auto-save/site/#6b2068bda5fe59e592ebfab3ec146dc110599f93#` , which is in this [message](https://github.com/syl20bnr/spacemacs/issues/15479#issuecomment-1149179055)

Any help?

**Comment by lebensterben** [comment]
As I said earlier,

> We haven't changed anything for gnus.

So it's either a configuration problem caused by you or an upstream bug.

**Comment by lebensterben** [comment]
Also, then email you attached above asks you what C-h k R is bound to. What is the answer? And you have not even mentioned this in your initial bug report or any later comments. (You only mentioned C-c C-f.)

Honestly it's painful to read your bug reports. They tend to be incoherent, that you suddenly changes the scope and issue across comments. 

And you don't immediately response to many of my questions. When you do respond several months later, you should not expect me to remember all the context. So I had to re-read all previous comments. And what's worse is that in your newer responses you almost always mentioning something remotely related to your previous findings.
