### ISSUE TITLE
Org layer broken when dotspacemacs-major-mode-leader-key is nil

### ISSUE THREAD

**Issue by person808** [syl20bnr/spacemacs#1547]
Error:

```elisp
Error (use-package): org :init: Key sequence m n starts with non-prefix key m
Error (use-package): org-pomodoro :init: Key sequence m p starts with non-prefix key m
Error (use-package): org-repo-todo :init: Key sequence m g t starts with non-prefix key m
```

When I have `(setq-default dotspacemacs-major-mode-leader-key nil)` I get the above errors on startup with the org layer enabled. It is caused by line 75 in the org layer's packages.el: `(concat "m" dotspacemacs-major-mode-leader-key) 'org-ctrl-c-ctrl-c`

**Comment by cpaulik** [comment]
Oh and I thought that was a good solution to bind `C-c C-c` to double tapping the major-mode-leader.

@person808 Just out of curiosity why do you have set it to `nil`?

**Comment by person808** [comment]
Just never used it I guess.
