### ISSUE TITLE
Suspicious (?) link in documentation 

### ISSUE THREAD

**Issue by 9s-l-s9** [syl20bnr/spacemacs#15489]
Hello,

I am new to spacemacs and looked through the documentation. 
On the site https://www.spacemacs.org/layers/+web-services/evernote/README.html

the link 'geeknote.me' seems to no longer be owned by the geeknote project and leads me to some strange websites. 

Btw. I've also found some dead links. Should I just open an issue for every seperate link? :)

**Comment by lebensterben** [comment]
thanks for reporting.

also please use

https://develop.spacemacs.org/layers/+web-services/evernote/README.html
