### ISSUE TITLE
bibtex layer, Symbol’s function definition is void: bibtex-completion-get-key-bibtex

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#15486]
When I'm opening a bibtex file I cannot use all keybindings and get the error message "org-ref-open-bibtex-notes: Symbol’s function definition is void: bibtex-completion-get-key-bibtex"

However, if I open an org file first everything works fine in the bibtex file.

I guess some layers/packages need to be loaded first when opening a bibtex file directly? Is this something to be set in the user-init or user-config?

Is there some way to list all the layers/packages currently loaded into emacs?

**Comment by arifer612** [comment]
Please add on more information of your configuration, such as which layers you have enabled and the system you are running. You can get this by `M-x spacemacs/report-issue` and copying everything under the `#### System Info :computer:` segment. You can get a list of all the packages loaded into Emacs by quoting exactly what is listed in the variable `package-selected-packages` in your dotspacemacs.

Seeing that `org-ref-open-bibtex-notes` comes up in the error, I am guessing that you have the `bibtex` layer enabled. It comes with the `org-ref` packaged in it. But then that is weird that such an error pops up suggests that the `helm-bibtex` or `ivy-bibtex` package is not loaded, which should not be the case if the layer is in enabled.

**Comment by sebhahn** [comment]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. c6c17748f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-minimum-prefix-length 3 auto-completion-idle-delay 0.4 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip nil auto-completion-use-company-box nil auto-completion-enable-sort-by-usage t)
 (bibtex :variables bibtex-enable-ebib-support t ebib-preload-bib-files
         '("~/ownCloud/areas/research/latex/zotero.bib")
         ebib-file-search-dirs
         '("~/ownCloud/areas/research/publications/")
         ebib-file-associations
         '(("pdf" . "zathura")
           ("ps" . "gv"))
         ebib-import-directory "~/ownCloud/areas/research/publications/")
 c-c++ colors
 (compleseus :variables compleseus-engine 'vertico)
 csv custom-org-config dash emacs-lisp
 (elfeed :variables rmh-elfeed-org-files
         (list "~/ownCloud/org/elfeed/elfeed.org")
         elfeed-db-directory "~/ownCloud/org/elfeed/db" elfeed-goodies/entry-pane-position 'bottom)
 elixir erc epub erlang ess
 (git :variables git-gutter-use-fringe t)
 fasd gnus html ipython-notebook
 (latex :variables font-latex-fontify-script nil latex-enable-auto-fill nil latex-enable-folding t)
 lsp json markdown multiple-cursors my-consult my-eglot my-mermaid my-mu4e my-org my-org-roam my-research my-python
 (org :packages
      (not org-roam)
      :variables org-enable-reveal-js-support t org-enable-org-journal-support t org-enable-epub-support t)
 pandoc
 (plantuml :variables plantuml-jar-path "~/ownCloud/org/bin/plantuml.jar" plantuml-default-exec-mode 'jar)
 (python :variables python-backend 'anaconda python-formatter 'yapf python-auto-set-local-pyenv-version 'on-project-switch python-test-runner 'pytest)
 ranger search-engine semantic
 (shell :variables shell-default-shell 'term shell-default-term-shell "/bin/zsh")
 shell-scripts spell-checking
 (syntax-checking :variables syntax-checking-enable-tooltips nil)
 tmux
 (version-control :variables version-control-diff-tool 'git-gutter version-control-global-margin t)
 xclipboard yaml)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by sebhahn** [comment]
I'm not loading any `helm` or `ivy` layer, is this a problem?
