### ISSUE TITLE
Install shows no visible changes

### ISSUE THREAD

**Issue by Cynosure-null** [syl20bnr/spacemacs#15488]
#### Description :octocat:
Install shows no visible changes

#### Reproduction guide :beetle:
- Use OpenSUSE Tumbleweed
- Use Emacs version 28.1
- Install spacemacs 
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Emacs appears to be the same before and after Spacemacs installation 

*Expected behaviour:* :heart: :smile:
Spacemacs installs as usual

*System Info:*
OpenSUSE Tumbleweed 20220424-0
Emacs 28.1
KDE Plasma with Wayland

#### Backtrace :paw_prints:
stdout is clean and no error messages appear in Emacs

**Comment by lebensterben** [comment]
describe how you installed emacs.

**Comment by Cynosure-null** [comment]
`sudo zypper in emacs`

**Comment by lebensterben** [comment]
sorry. I meant how do you install Spacemacs.

**Comment by Cynosure-null** [comment]
`git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d`
I did have a preexisting install as well

**Comment by lebensterben** [comment]
where is your other emacs configurations installed?

**Comment by lebensterben** [comment]
make sure you don't have ~/.emacs or ~/.emacs.el

**Comment by Cynosure-null** [comment]
Both of those files and .gnu-emacs still exist. I will try removing them

**Comment by Cynosure-null** [comment]
That worked. Thanks for the help.
