### ISSUE TITLE
helm-git-grep causes my computer to crash

### ISSUE THREAD

**Issue by JuanCaicedo** [syl20bnr/spacemacs#15497]
Hi everyone! I opened up an issue because I don't really know how to go about debugging this 😅 I'm seeing this pretty reliably, so if there's any more info I can provide, let me know 👍

#### Description :octocat:
Computer crashes when running helm-git-grep

#### Reproduction guide :beetle:
- Start Emacs
- Run `SPC g /`

*Observed behaviour:* :eyes: :broken_heart:
- My computer crashes

*Expected behaviour:* :heart: :smile:
- Command executes successfully

#### System Info :computer:
- OS: darwin 
  - MacOS 12.3.1
- Emacs: 28.1 (Also experienced this on v27)
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. c6c17748f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go sql python html clojure emoji typescript nginx docker csv helm emacs-lisp elm git javascript
    (keyboard-layout :variables kl-layout 'dvp)
    markdown neotree org osx ruby yaml shell-scripts)
```
- System configuration features: ACL GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM ZLIB

**Comment by lebensterben** [comment]
what do you mean by crash?

is it unresponsive?

**Comment by BenedictHW** [comment]
Helm-git-grep seems to be working fine here on Emacs 29.0.50.

Perhaps try,

``` emacs-lisp
(setf helm-candidate-number-limit 100)
```

and see if that makes helm more responsive? And I thought I'd mention SPC g s l
-F (or -G) RET (or refresh with g) as Magit's transient interface to use in the
meantime.

HTH,

**Comment by JuanCaicedo** [comment]
@lebensterben by [crash](https://en.wikipedia.org/wiki/Crash_(computing)) I mean it forces my computer to force restart 😅 I really don't know a better way to describe it.

@BenedictHW Thanks! I can to to set `helm-candidate-number-limit` to see if that helps 👍

I'm not sure what command you're suggesting. `SPC g s` triggers `magit-status`, and there's nothing I can see under `SPC g s l`. If by the transient interface you mean the magit status view, I'm not sure how I can grep through the whole codebase from there, which is my goal. Thank you for helping though!

**Comment by BenedictHW** [comment]
There's also the emacs debugger & profiler.

- Use ~SPC t D~ to enable debug on error, this will
  produce a backtrace when encountering a lisp error.

The =Profiler= is a tool that helps you identify why your editor is running
slowly or consumes a lot of memory. Here are key bindings related to it:

| Key binding | Description                 |
|-------------+-----------------------------|
| ~SPC h P k~ | stop the profiler           |
| ~SPC h P r~ | display the profiler report |
| ~SPC h P s~ | start the profiler          |
| ~SPC h P w~ | write the report to file    |

Regarding `SPC g s`, that was my bad, I misunderstood you. Inside the
`SPC g s` magit buffer "l" and then "-F" will allow you to grep through
commit logs.

To grep the whole codebase the usual method is `SPC /`. Grep/ag/ripgrep
will then search the project, where project is defined by projectile.

https://github.com/bbatsov/projectile

Projectile automatically recognizes version control marker files like .git.

You can bring up a list of projects that projectile recognizes with `SPC
p p`. So navigating to your .emacs.d/doc folder and pressing `SPC s d`
to search just the /doc folder is possible (that's where the above
keybind table come from :D ). See also `SPC s f`, which I've yet to see
Doom Emacs replicate, and is handy when you're aiming to grep folders or
files that are not in a defined project (C-2 C-h moves two directories
up in the `SPC f f` and `SPC s f` buffer!).

I hope this solves your use case, or at least can give us some debug
clues to work with.

Cheers,

**Comment by JuanCaicedo** [comment]
@BenedictHW Thanks for responding! `helm-candidate-number-limit` does not seem to help ☹️

I tried running the profiler, but after my computer crashes I can't recover the results 😕

`SPC /` doesn't seem to work very well for me. The results are super slow, to the point where it's not really usable. `SPC g /` with the same query returns very quickly (until my computer crashes 😅)

I feel like I'm sort of stuck with this issue 💔

**Comment by lebensterben** [comment]
@JuanCaicedo 

Install ripgrep and use SPC /.

**Comment by JuanCaicedo** [comment]
I was able to find the crash reports for my system and see that they are all from `Process Name = node`

Here's the part of the report that seems relevant (though I'm not sure if it's a red herring)
```
6   node                          	       0x1063b6787 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) + 71
```

I don't know why helm-git-grep would be interacting with node though 😅

I tried updating my version and am now on v16.14.0, but still get this crash.

@lebensterben Thanks for the tip 😀 I tried installing ripgrep and the results of `SPC /` are still very slow. I also tried running `ripgrep-regexp` and `projectile-ripgrep`, but neither of these seem to work (I get an error saying that the `rg` command is not found)

**Comment by lebensterben** [comment]
it's slow because it's not found so it fallbacks to grep.

it's not found because it's not added to PATH.

**Comment by BenedictHW** [comment]
1. Concerning ripgrep.

How did you install ripgrep (sudo apt install ripgrep)? Can you call ripgrep in
your terminal ($ rg)? But that's besides the main issue here.

2. Concerning the node out-of-memory error (OOM).

Without much else to go off of, I'm guessing your out of memory error could be
due to long lines when you attempt to open a JavaScript file? Does the error
still persist on your system with a vanilla configuration?

I.e. if you back up your .spacemacs, .emacs.d folder and install a fresh vanilla
configuration does SPC g / still crash your system?

I wish I knew more about the node, that's all I got for now. Let me know what
happens.

**Comment by acheng-hm** [comment]
I get the same crash unless I type my search term one character at a time, allowing it to finish before each additional character (or if I build my entire search term elsewhere and paste it in all at once for helm-git-grep). 

Is there a setting that I can tweak so it waits more milliseconds after the most recent keystroke before starting its next search? The problem feels like it's spawning "too many" searches when I type quickly.

**Comment by BenedictHW** [comment]
Running helm-dir-smart-do-search (SPC s d) "helm delay" while in
/home/$USER/.emacs.d/elpa/29.0/develop/helm-20220621.1947/ dired buffer gives me
`helm-grep-input-idle-delay`. Still, I am not sure of your root problem. I don't
use helm-git-grep much at all, instead I use SPC /.

**Comment by BenedictHW** [comment]
Ahah. Happy to find somebody else who encountered the same issue. I noticed the same behaviour with rg and SPC /. What allows me to find "bar foo" if you type "foo bar" is using ag (I use the packaged silversearcher-ag) instead of rg. I'm a little foggy on the reasons why this is, it's been awhile since I dug into this, but it is either

1. Rust's regex library (also used by fdfind) does not support look-ahead or look-arounds. Is this still the case?

2. Helm-ag package is currently stagnating. It works best with ag and perhaps getting rg to work with helm-ag will require some hacking.

3. I know a helm-rg package exists, but from the quick glance I took some while ago, it does not seem to equal helm-ag in capabilities yet. So some hacking in order again.

If switching to ag is no issue, then you should get the behaviour that you want. Make sure to set,

helm-ag-fuzzy-match to t.

Here's my config if it proves useful.

``` emacs-lisp
  ;;-------------------------------------------------------------------------
  ;; ***  Helm Config
  ;;-------------------------------------------------------------------------
  ;; https://www.linode.com/docs/guides/finding-files-with-fd-command/
  (load "helm-fd")
  (setf helm-fd-executable "fdfind" ; Debian package
        ;; See /home/ben/.config/fd/ignore
        helm-fd-switches '("--hidden" "--type" "f" "--type" "d" "--color" "never"))
  (defvar helm-source-fd
    (helm-make-source (format "fd (%s)" (abbreviate-file-name default-directory)) 'helm-fd-class))
  (load "helm-ag")
  (defvar helm-source-maria-ag
    (helm-make-source "Project Maria - AG" 'helm-do-ag-class
      :candidates-process
      (lambda ()
        (helm-ag--do-ag-set-command)
        (helm-ag--do-ag-candidate-process +project-maria-dir+)))
    "`helm-ag--do-ag-set-source' used as exemplar.")
  (defvar helm-source-emacs-commands
    (helm-build-sync-source "Emacs Commands"
      :candidates (lambda ()
                    (let ((cmds))
                      (mapatoms (lambda (elt)
                                  (when (commandp elt)
                                    (push (symbol-name elt) cmds))))
                      cmds))
      :coerce #'intern-soft
      :action #'command-execute)
    "A simple helm source for Emacs commands.")
  ;; https://github.com/syl20bnr/spacemacs/issues/15124
  ;; setf helm-use-fuzzy 'source
  (setf ace-jump-helm-line-default-action 'select
        helm-ff-auto-update-initial-value t
        helm-for-files-preferred-list '(;; Causes ad-Advice-set-window-buffer:
                                        ;; Wrong type argument: bufferp, nil
                                        ;; when selecting buffer.
                                        helm-source-buffers-list
                                        helm-source-recentf
                                        helm-source-file-cache
                                        helm-source-fd
                                        helm-source-maria-ag
                                        helm-source-emacs-commands)
        helm-candidate-number-limit 100
        helm-ff-skip-boring-files t
        helm-ag-fuzzy-match t)
  (defun ben/project-maria-ag ()
    "Search in project-maria with `ag'."
    (interactive)
    (spacemacs/helm-files-do-ag "~/Dropbox/project-maria/"))
  (defun ben/project-maria-ag-region-or-symbol ()
    "Search in project-maria with `ag' using a default input."
    (interactive)
    (spacemacs//helm-do-ag-region-or-symbol 'spacemacs/helm-files-do-ag "~/Dropbox/project-maria/"))
  (defun ben/helm-recent-directories()
    (interactive)
    (let ((current-prefix-arg 4))
      (call-interactively 'helm-find-files)))
  (spacemacs/set-leader-keys
    "SPC" #'helm-for-files
    (kbd "se") #'helm-mu
    ;; (kbd ";") #'ben/project-maria-ag
    (kbd ":") #'ben/project-maria-ag-region-or-symbol
    (kbd "fd") #'ben/helm-recent-directories)
```

**Comment by BenedictHW** [comment]
I should mention I set SPC SPC to helm-for-files elsewhere as well as ; to helm-occur. With `helm-source-emacs-commads` SPC SPC covers both M-x as well as whatever is in your `helm-for-files-preferred-list`. I'm fairly certain this capability is helm-specific, but who knows, some lisper has probably got something similar for ivy or the new completions consult/embark/corfu/what have you.

**Comment by BenedictHW** [comment]
I wish I knew more about helm-git-grep, but if you have further questions about
helm-git-grep, Evan Klitzke @eklitzke would be the person most likely to know
something.
