### ISSUE TITLE
evil-append will jump to next line if cursor is at the end of a link

### ISSUE THREAD

**Issue by wztdream** [syl20bnr/spacemacs#15493]
#### Description :octocat:
evil-append will jump to next line if cursor is at the end of a link.

#### Reproduction guide :beetle:
- Start Emacs
- type "i" to enter insert mode, then type [[123]] then get a link 123
- "esc" change to normal mode
- move cursor to the end of 123, using "C-e" for example, now the cursor is right after 123, i.e. 123x, and "x" represent the cursor, in normal mode
- then you type "a" to append a letter, but the cursor will jump to next line.

*Observed behaviour:* :eyes: :broken_heart:
cursor will jump to next line after typing "a"
123
x

*Expected behaviour:* :heart: :smile:
after typing "a", the cursor should be at the end of link, 123I, where "I" represents the cursor in insert mode

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. d79b12e7b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(emoji systemd yaml csv javascript spell-checking latex
       (spacemacs-editing-visual :packages
                                 (not indent-guide))
       (conda :variables conda-anaconda-home "/home/wangzongtao/anaconda3")
       emacs-lisp bibtex multiple-cursors ivy git
       (python :variables python-backend 'lsp python-lsp-server 'pyright python-formatter 'black python-sort-imports-on-save nil python-format-on-save nil)
       (c-c++ :variables c-c++-backend 'lsp-clangd)
       (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-minimum-prefix-length 2 auto-completion-idle-delay 0.2 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip nil auto-completion-use-company-box nil auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
       (better-defaults :variables better-defaults-move-to-beginning-of-code-first t better-defaults-move-to-end-of-code-first nil)
       (org :packages
            (not org-roam))
       (shell :variables shell-default-shell 'vterm shell-default-height 60 shell-default-position 'bottom shell-default-term-shell "/bin/bash" shell-enable-smart-eshell t close-window-with-terminal t)
       (wzt-chinese :variables chinese-enable-youdao-dict t)
       (wzt :variables org-clock-watch-work-plan-file-path "/home/wangzongtao/research/org/gtd.org"))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```

```

**Comment by lebensterben** [comment]
I believe this is a compatibility issue between evil and org in 28.1.

**Comment by wztdream** [comment]
close here, it should be evil package issue
