### ISSUE TITLE
Is visual-regexp-steroids removed and needs a layer or just needs to be enabled?

### ISSUE THREAD

**Issue by idbrii** [syl20bnr/spacemacs#1550]
I wanted to install benma/visual-regexp-steroids.el.

I found that it was already in [spacemacs/packages.el](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L2629-L2637), but with the bindings disabled (ce3a1775c6c790790f379826b31450891349fc9b). Am I supposed to enable something, or do I need to create a layer?

Adding it to my layers:

    dotspacemacs-configuration-layers '(
                                       visual-regexp
                                       visual-regexp-steroids
                                       )

and using it gives:

    Symbol's function definition is void: vr/query-replace

**Comment by idbrii** [comment]
I used config-system/create-layer to create a layer and filled in packages.el:

    (defvar visual-regexp-packages
    '(
        visual-regexp
        visual-regexp-steroids
        )
    "List of all packages to install and/or initialize. Built-in packages
    which require an initialization must be listed explicitly in the list.")

    (defvar visual-regexp-excluded-packages '()
    "List of packages to exclude.")

    (defun visual-regexp/init-visual-regexp ()
    (use-package visual-regexp
        :defer t
        :config
        :init
        ))

    (defun visual-regexp/init-visual-regexp-steroids ()
    (use-package visual-regexp-steroids
        :defer t
        :config
        :init
        ))

I didn't edit extensions.el.

And then in my .spacemacs I added the layers:

    dotspacemacs-configuration-layers '(
                                       visual-regexp
                                       visual-regexp-steroids
                                       )

I have this:

    (evil-nmap "g s" 'vr/query-replace)

That works, but I feel like I'm doing something wrong.

**Comment by syl20bnr** [comment]
Yes I removed it. You could contribute it back in a layer that we can call `regexp` where we would put packages related to regexp.

For the review of your layer:
- You can remove empty `:init` and `:config`
- move your key binding to the init section of `visual-regexp/init-visual-regexp`.
- in your dotfile just add the name of the layer, that is `visual-regexp`
