### ISSUE TITLE
How to invoke golden-ratio-adjust without enabling golden-ratio-mode?

### ISSUE THREAD

**Issue by idbrii** [syl20bnr/spacemacs#1551]
I figured out this code snippet to bind a key to adjust my windows according to the golden ratio:

    (defsubst david-golden-ratio-adjust ()
        "Invoke golden-ratio with default adjustment ratio."
        (interactive)
        (golden-ratio-adjust golden-ratio-adjust-factor))
    (evil-leader-nmap "w -" 'david-golden-ratio-adjust)

But if I try invoking my binding, I get this:

    david-golden-ratio-adjust: Symbol's function definition is void: golden-ratio-adjust

If I use `SPC t g` twice to toggle golden-ratio-mode on and off, then my binding works.

I tried adding                                        golden-ratio to my    dotspacemacs-configuration-layers, but no luck. I assume there's something wrong in the way I'm loading golden-ratio?

I like golden-ratio, but I want it to be only on manual invocation so it never auto-adjusts my window sizes.

**Comment by tuhdo** [comment]
That's because `golden-ratio` is only loaded when you use the default key binding `SPC t g`. Otherwise, it is not loaded and you won't have the `golden-ratio-adjust` to use.

**Comment by idbrii** [comment]
How do I load it without using the default key binding?

**Comment by syl20bnr** [comment]
@idbrii you could

```elisp
(golden-ratio-mode)
(golden-ratio-mode -1)
```

But I tried the function `golden-ratio-adjust` and it does not seem to do anything if `golden-ratio` is disabled.

**Comment by idbrii** [comment]
Splitting, toggling, switching, and then calling adjust with 1 resizes the windows for me:

    C-w s
    SPC t g
    SPC t g
    C-w w
    M-x golden-ratio-adjust
    1

If engaging and disengaging golden-ratio-mode is the only way to load its code, then is that a golden-ratio limitation or a spacemacs limitation?

**Comment by tuhdo** [comment]
You could load it directly with `(require 'golden-ratio)` in your `.spacemacs`.

**Comment by idbrii** [comment]
Calling require inside my dotspacemacs/config worked. Thank you!
