### ISSUE TITLE
org-roam-enable-protocol is referenced but not defined, and the readme uses a different name

### ISSUE THREAD

**Issue by tasheng** [syl20bnr/spacemacs#15514]
#### Description :octocat:
Emacs failed to load init.el when org-enable-roam-support is enabled with the org layer.
The readme of org layer suggests setting org-enable-roam-protocol, which doesn't match with the symbol missing a definition:
org-roam-enable-protocol

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
symbol's definition is void: org-roam-enable-protocol

*Expected behaviour:* :heart: :smile:
When roam-protocol is not enabled, Emacs should be able to load without error.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 1fde8719e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv php systemd html yaml
     (python :variables python-backend 'lsp python-lsp-server 'pyright)
     ipython-notebook javascript auto-completion emacs-lisp git helm
     (lsp :variables lsp-restart 'auto-restart lsp-enable-indentation nil)
     markdown multiple-cursors
     (org :variables org-latex-compiler "xelatex" org-latex-pdf-process
          '("latexmk -xelatex --shell-escape -interaction=nonstopmode -output-directory=%o -f %f")
          org-enable-roam-support t org-roam-directory
          (file-truename "~/org/roam")
          org-enable-roam-protocol t org-enable-reveal-js-support t)
     bibtex
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control treemacs multiple-cursors evil-snipe
     (c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-ccls c-c++-lsp-semantic-highlight-method 'overlay)
     cmake
     (dap :variables dap-enable-ui-controls nil dap-auto-configure-features
          '(sessions locals breakpoints expressions tooltip))
     jupyter
     (mu4e :variables mu4e-installation-path "~/bin/mu/mu4e" mu4e-mu-binary "~/bin/mu/mu/mu")
     ranger pdf spacemacs-language fasd chrome theming captain)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS WEBP XIM XWIDGETS GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by korayal** [comment]
Caused by this change introduced with https://github.com/syl20bnr/spacemacs/issues/14487:
https://github.com/syl20bnr/spacemacs/blob/24640fca75b96a97c852e32f41559bbe02b4fb8d/layers/%2Bemacs/org/packages.el#L981
