### ISSUE TITLE
Emacs 29: restart is broken

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#15524]
#### Description :octocat:
Restarting fails with the message `spacemacs/restart-emacs: Wrong number of arguments: restart-emacs, 1`

As you can see below I'm currently running Emacs 29, and I understand that this bug report won't get too much attention right away. I'm reporting it mostly to see if someone else has a workaround for this already, and maybe it can serve as a heads-up for the inevitable release of Emacs 29 :grin:

#### Reproduction guide :beetle:
- Start Emacs
- When started, try to restart using `SPC q r` or `SPC q R`

*Observed behaviour:* :eyes: :broken_heart:
Emacs doesn't restart, instead it shows the message `spacemacs/restart-emacs: Wrong number of arguments: restart-emacs, 1`

*Expected behaviour:* :heart: :smile:
Emacs should restart

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 6f5de5cc4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash docker evil-commentary evil-snipe
 (git :variables git-enable-magit-todos-plugin t)
 (helm :variables helm-no-header t)
 (lsp :variables lsp-lens-enable nil lsp-use-lsp-ui t lsp-use-upstream-bindings nil)
 mu4e multiple-cursors restclient
 (shell :variables shell-default-shell 'ansi-term)
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak)
 spacemacs-editing-visual spacemacs-visual
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking templates tree-sitter vinegar
 (xclipboard :variables xclipboard-enable-cliphist t)
 (c-c++ :variables c-c++-backend 'lsp-ccls)
 (clojure :variables clojure-enable-sayid t clojure-enable-clj-refactor t clojure-enable-linters 'clj-kondo clojure-backend 'lsp)
 emacs-lisp
 (go :variables go-backend 'lsp go-format-before-save t)
 (haskell :variables haskell-completion-backend 'lsp haskell-process-type 'cabal-repl)
 (python :variables python-formatter 'yapf)
 rust shell-scripts csv graphviz html json latex markdown
 (org :variables org-enable-reveal-js-support t org-enable-roam-support t org-roam-enable-protocol nil)
 nixos spacemacs-org
 (sql :variables sql-auto-indent nil)
 pandoc systemd terraform yaml direnv mt-misc projectile-extra roam-extra)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS WEBP XIM XWIDGETS GTK3 ZLIB

**Comment by BenedictHW** [comment]
You're not alone :), this is a duplicate of
https://github.com/syl20bnr/spacemacs/issues/15505 but I daresay your report has
a better title.

**Comment by dalanicolai** [comment]
FYI, I've posted a quick-fix [here](https://github.com/syl20bnr/spacemacs/issues/15505#issuecomment-1128799137)

**Comment by smile13241324** [comment]
Thanks for reporting I'll have a look into this

**Comment by rommeswi** [comment]
@magthe Since I see that you are also running a latex layer, is auctex also broken for you in Emacs 29 with spacemacs? If I want to edit a .tex document it says (void-function TeX-latex-mode) and remains in the standard major mode.

**Comment by magthe** [comment]
> @magthe Since I see that you are also running a latex layer, is auctex also broken for you in Emacs 29 with spacemacs? If I want to edit a .tex document it says (void-function TeX-latex-mode) and remains in the standard major mode.

No, that works fine for me.

**Comment by magthe** [comment]
> Thanks for reporting I'll have a look into this

Nice! It's been like this for a while now, so if a temporary, simple and cheap workaround is possible it'd be rather nice. The current situation is more of a nuisance than life-or-death :grin:

**Comment by smile13241324** [comment]
> agenbite Please have a try with latest develop and close this ticket when it works, thanks.

@magthe I have pushed a possible fix, please have a look if this solves the issue in emacs 29 and close this ticket if it does, thanks.

**Comment by magthe** [comment]
I'll close this as it's a duplicate of #15505 .
