### ISSUE TITLE
The `notmuch` layer reports that the definition of `spacemacs|add-company-backends` is void when the `auto-completion` layer is not installed

### ISSUE THREAD

**Issue by gphilip** [syl20bnr/spacemacs#15529]
Spacemacs version : 0.999.0@27.1 (spacemacs)

I added the `notmuch` layer and started getting the following message in the *Warnings* buffer each time I started up spacemacs:

   `Error (use-package): notmuch/:config: Symbol’s function definition is void: spacemacs|add-company-backends`

As far as I could see, this had no other adverse effect, than that I had to switch out of the *Warnings* buffer before I could use spacemacs. 

I reported this on gitter chat, and @dalanicolai helped me solve the issue: they figured out that this message is because the `auto-completion` layer is not installed in my spacemacs. I enabled `auto-completion` and the warning went away.

I am opening this issue at @dalanicolai 's suggestion, to alert the maintainers of the `notmuch` layer about this.

Here is a similar issue that I could find, which apparently went away on its own: #9160

**Comment by agenbite** [comment]
I can reproduce it and it gets solved like suggested. The `auto-completion` layer wasn't necesary before.
