### ISSUE TITLE
Treemacs doesn't honor current working directory with `M-m 0`

### ISSUE THREAD

**Issue by tidux** [syl20bnr/spacemacs#15528]
#### Description :octocat:
Treemacs doesn't honor current working directory with `M-m 0`

#### Reproduction guide :beetle:
- Start Emacs
- Open a file
- `SPC-0`
- open new window in different buffer outside of previous directory hierarchy
- `M-m 0`

*Observed behaviour:* :eyes: :broken_heart:
Treemacs opens the buffer at the old location.

*Expected behaviour:* :heart: :smile:
Treemacs opens the buffer at the new location.

#### System Info :computer:
- OS: darwin
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 6f5de5cc4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion docker emacs-lisp epub eww git helm kubernetes
                 (lsp :variables lsp-rust-server 'rust-analyzer)
                 markdown multiple-cursors org
                 (python :variables python-formatter 'black python-format-on-save t)
                 rust
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking themes-megapack
                 (treemacs :variables treemacs-use-scope-type 'Perspectives)
                 version-control)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER THREADS TOOLKIT_SCROLL_BARS ZLIB

**Comment by emacs18** [comment]
My reading of treemacs documentation indicates that "honoring current directory" is not how it is supposed to work.
Perhaps you could try `M-x treemacs-add-and-display-current-project`.
