### ISSUE TITLE
spell-checking - Hunspell - en_US.aff dictionary not found - macOS

### ISSUE THREAD

**Issue by mat-r** [syl20bnr/spacemacs#15533]
#### Description :octocat:
I added the `spell-checking` layer. I have `hunspell` installed in my system. I have dictionaries installed as well. When I try to use `ispell-buffer`, I get the following error:
```
Error enabling Flyspell mode:
(Can’t find Hunspell dictionary with a .aff affix file)
```

#### Reproduction guide :beetle:
- Start Spacemacs (assuming `spell-checking` layer is already installed
- open a text buffer
- execute `ispell-buffer`

*Observed behaviour:* :eyes: :broken_heart:
The following message is displayed in the Messages buffer:
```
Error enabling Flyspell mode:
(Can’t find Hunspell dictionary with a .aff affix file)
```

*Expected behaviour:* :heart: :smile:
The dictionary en_US.aff should be found.

#### System Info :computer:
- OS: darwin
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 6f5de5cc4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion
better-defaults
(c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
emacs-lisp
git
helm
helpful
lsp
markdown
outshine
org
spell-checking)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER THREADS TOOLKIT_SCROLL_BARS ZLIB

#### Backtrace :paw_prints:
```shell
> hunspell -D
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
/Library/Spelling/en_US
```
```shell
> ls /Library/Spelling/
en_US.aff en_US.dic
```

From Emacs help:
```elisp
ispell-dictionary is a variable defined in ispell.el.gz.

Value
nil

Toggle Set Customize

Documentation
Default dictionary to use if ispell-local-dictionary is nil.
```

```shell
❯ which hunspell
/opt/homebrew/bin/hunspell
```

`/opt/homebrew/bin` is in `~/.spacemacs.env`

Also, setting ispell-dictionary to en_US does not solve the problem.

**Comment by MagisDing** [comment]
Same issue here.

**Comment by khaledmust** [comment]
I've got the same issue here.
Has been any progress regarding this issue?

**Comment by lebensterben** [comment]
This is not a Emacs problem.
https://stackoverflow.com/questions/8931580/hunspell-cant-open-affix-or-dictionary-files-for-dictionary-named-en-us
