### ISSUE TITLE
snippets in private cannot be loaded automatically

### ISSUE THREAD

**Issue by eyesfrog** [syl20bnr/spacemacs#1553]
I wrote some snippets and saved them to ~/.emacs.d/private/snippets/cc-mode/.
But I find them cannot be loaded by Yasnippets automatically.
I must press space-t-y twice or reload everything then it works well.

**Comment by tuhdo** [comment]
Do you have `auto-yasnippet`? If that is the case, when you use `auto-yasnippet` it will make the `yas-minor-mode` function available and Spacemacs cannot loads yasnippet properly because it thinks that the package already loaded.

**Comment by eyesfrog** [comment]
I don't quite know about it. How to check if I have auto-yasnippet?
I am not familiar with emacs and spacemacs.😔

**Comment by eyesfrog** [comment]
Oh why this packages.el is different from mine?
In my packages.el, there just 3 in auto-completion-packages: company, auto-complete and ac-ispell.

I change the packages.el as you fixed,  it still cannot work.

**Comment by tuhdo** [comment]
That packages.el is in the `develop` branch.

**Comment by eyesfrog** [comment]
I see.
Thx a lot~

**Comment by eyesfrog** [comment]
Well, I've just tried but it still can't work.
Orz.

**Comment by syl20bnr** [comment]
@eyesfrog any news on this ? Did the last changes in `develop` fix this issue ?
