### ISSUE TITLE
[clojure] README: add support for ClojureScript stepper via LSP-mode and DAP-mode

### ISSUE THREAD

**Issue by allentiak** [syl20bnr/spacemacs#15546]
It would be nice to have an option in the clojure layer to automatically setup a ClojureScript stepper via DAP and LSP.

The instructions from [1] are declared as valid for vanilla Emacs.
However, they need to be adapted for Spacemacs.

_(I tried making it work by installing the `dap` layer, but couldn't make it work due to a lack of specific Spacemacs/Emacs knowledge. You may find my current `~/.spacemacs.d/init.el` in [2].)_

[1] https://emacs-lsp.github.io/lsp-mode/tutorials/debugging-clojure-script/
[2] https://github.com/allentiak/.spacemacs.d/blob/46df5678aa0918b5105b013089f6ddf235d7e5fe/init.el

Relevant Message from the Clojurians Zulip:
https://clojurians.zulipchat.com/#narrow/stream/151763-beginners/topic/spacemacs.20.2B.20clojurescript.20.2B.20debugging.20.3F/near/281212390

Related issue from `dap-mode`:
https://github.com/emacs-lsp/dap-mode/issues/554#issuecomment-1118456198

**Comment by allentiak** [comment]
UPDATE: I have made dap-debug work for ClojureScript:

- Add the `dap` layer to the `dotspacemacs/layers ()` section of your `.spacemacs` file (at the top of the file). 
- Require the corresponding module in the `dotspacemacs/user-config ()` section of your `.spacemacs` (at the bottom of the file).
(In my case, I made it work with Chromium.)
- Make sure the Chromium executable is correctly setup (see https://github.com/syl20bnr/spacemacs/issues/13614#issuecomment-1179478365)


```elisp
dotspacemacs/user-config()
  ...
  ;; Enable DAP debugging in ClojureScript.
  ;; Trying almost all options...

  ;; This one downloads OK.
  (require 'dap-chrome)

  ;; These two cannot be downloaded... 
  ;; (require 'dap-firefox)
  ;; (require 'dap-node)

  ;; I'm not into trying this one...
  ;; (require 'dap-edge)
```

Based on:
https://emacs-lsp.github.io/lsp-mode/tutorials/debugging-clojure-script/

**Comment by lebensterben** [comment]
Feel free to make this a wiki page.

**Comment by allentiak** [comment]
Should this be added to the Clojure layer documentation page?
