### ISSUE TITLE
Documentation Request: Add elisp function to all keybinding tables

### ISSUE THREAD

**Issue by jgarte** [syl20bnr/spacemacs#15540]
Hi @syl20bnr 

Would PRs to add the elisp function(s) corresponding to keybindings in [similar tables](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/plantuml/README.org#key-bindings) be accepted?

I wouldd create a new column for elisp functions to each layer keybind table:

```
* Key bindings

| Key binding              | Description                                               | Function                                                     |
|----------------------------+------------------------------------------------------+--------------------------------------------------------|
| ~SPC m c c~ or ~C-c C-c~ | Build diagram from the text in the current buffer     | ~plantuml-preview~         |
| ~SPC m c o~              | Set the output type (=unicode text=, =svg=, or =png=) | ~plantuml-set-output-type~|
```

I'd be happy to volunteer to do this documentation work for __all__ layers.

wdyt

excuse the github formatter for an org table

**Comment by jgarte** [comment]
Does anyone have any thoughts on this idea?

**Comment by BenedictHW** [comment]
I had the same idea some time back. When learning emacs I found it helpful to
keep my own | KEY | EFFECT | tables. In the vein of teaching a man to fish, I
myself reach more often nowadays for C-h b (SPC h d b) which gives up to date
information. And given a function name we all know our beloved C-h f, C-h v, K,
and gd to jump to definition etc. I think it would be quite helpful in teaching
newbies the association that you can remap any function to any keybindings and
that the fun starts when you tweak or define your own elisp functions. Whether
this is done by appending a new column (more maintenance burden?) or a guided
walkthrough on Emacs introspection capabilities is bikeshedding. I do applaud
the desire to help emacs newcomers though.

**Comment by jgarte** [comment]
Is there currently an existing function to get all and only the bindings for a particular spacemacs layer? 

Starting from that point, we can automate converting that data to org mode.

wdyt

**Comment by jgarte** [comment]
> Like what Ubuntu did for Debian way back when...

And unlike what pycharm did for the python docs which is another project I'm interested:

That is, an alternative elisp and guile docs with a less academic tone. [Pycharm](https://www.jetbrains.com/pycharm/) has their own distilled/nicer documentation for most of the python standard library and select 3rd party libraries which is unfortunately not easily readable/distributable unless you're using their IDE.

**Comment by BenedictHW** [comment]
Good point. Writing for humans is much harder in some respects than for a machine eh.
