### ISSUE TITLE
Strange behaviour for the help on key bindings

### ISSUE THREAD

**Issue by DrWaleedAYousef** [syl20bnr/spacemacs#15548]
#### Description :octocat:
The `C-h k` command does not work with any key binding and gives the message:
_mapcar: Symbol’s value as variable is void: code-cells-mode_

**Clue** Is this relatd to the strange behavior of the key bindings mentioned in issue #15479 ?

**EDIT**
The problem exists even when I commented everything inside `(defun dotspacemacs/user-config ()` and my layer definition is:

```
   dotspacemacs-configuration-layers
   '(pandoc
     csv
     dap
     c-c++
     php
     systemd
     (latex :variables
            latex-build-command "LatexMk" ;;default
            ;; latex-build-command "LaTeX" ;;default
            latex-enable-auto-fill t ;;default
            latex-backend 'lsp
            latex-build-engine 'luatex
            latex-view-pdf-in-split-window t
            latex-enable-magic t
            latex-refresh-preview t
            latex-enable-folding t
            )
     (bibtex :variables
             bibtex-enable-ebib-support t
             ebib-preload-bib-files'("~/MyDocuments/Phd/texmf/bibtex/bib/base/publications.bib" "~/MyDocuments/Phd/texmf/bibtex/bib/base/booksIhave.bib")
             ebib-file-search-dirs '("~/MyDocuments/Phd/PDF/")
             ebib-import-directory '("~/Downloads/")
             )
     lua
     (html :variable
           css-enable-lsp t
           less-enable-lsp t
           scss-enable-lsp t
           html-enable-lsp t
           web-fmt-tool 'web-beautify
           html-enable-leex-support t
           )
     web-beautify
     prettier
     gnus
     (git :variables
          ;; git-enable-magit-delta-plugin t
          git-enable-magit-gitflow-plugin t
          git-enable-magit-svn-plugin t
          )
     (yaml :variables
           yaml-enable-lsp t
           )
     (python :variables
             python-format-on-save t
             python-formatter 'yapf ;; default is lsp
             python-fill-column 99
             python-backend 'lsp
             python-lsp-server 'pyright
             )
     (auto-completion :variables
                      auto-completion-enable-help-tooltip t
                      )
     better-defaults
     emacs-lisp
     (helm :variables
           helm-enable-auto-resize t
           helm-no-header t)
     (lsp :variables
          lsp-lens-enable t)
     (markdown :variables
               markdown-live-preview-engine 'vmd
               )
     (chrome :variables
             )
     multiple-cursors
     (org :variables
          org-enable-org-contacts-support t
          org-contacts-files '("~/.emacs.d.loadpath/Contacts-Imported.org")
          org-capture-templates '(("c" "Contacts" entry (file "~/Contacts-Imported.org")
                                   "* %(org-contacts-template-name))
:PROPERTIES:
:EMAIL: %(org-contacts-template-email)
:END:"                                   ))
          )
     (pdf :variables
          pdf-view-display-size (quote fit-page))
     (shell :variables
            shell-default-shell 'eshell
            shell-default-height 30
            shell-default-position 'bottom
            ;; shell-enable-smart-eshell t
            )
     (spell-checking :variables
                     spell-checking-enable-auto-dictionary t)
     syntax-checking
     ;; version-control
     (treemacs :variables
               treemacs-use-follow-mode t
               treemacs-use-filewatch-mode t)
     )
```

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 756e204d2)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(pandoc csv dap c-c++ php systemd
        (latex :variables latex-build-command "LatexMk" latex-enable-auto-fill t latex-backend 'lsp latex-build-engine 'luatex latex-view-pdf-in-split-window t latex-enable-magic t latex-refresh-preview t latex-enable-folding t)
        (bibtex :variables bibtex-enable-ebib-support t ebib-preload-bib-files
                '("~/MyDocuments/Phd/texmf/bibtex/bib/base/publications.bib" "~/MyDocuments/Phd/texmf/bibtex/bib/base/booksIhave.bib")
                ebib-file-search-dirs
                '("~/MyDocuments/Phd/PDF/")
                ebib-import-directory
                '("~/Downloads/"))
        lua
        (html :variable css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t web-fmt-tool 'web-beautify html-enable-leex-support t)
        web-beautify prettier gnus
        (git :variables git-enable-magit-gitflow-plugin t git-enable-magit-svn-plugin t)
        (yaml :variables yaml-enable-lsp t)
        (python :variables python-format-on-save t python-formatter 'yapf python-fill-column 99 python-backend 'lsp python-lsp-server 'pyright)
        (auto-completion :variables auto-completion-enable-help-tooltip t)
        better-defaults emacs-lisp
        (helm :variables helm-enable-auto-resize t helm-no-header t)
        (lsp :variables lsp-lens-enable t)
        (markdown :variables markdown-live-preview-engine 'vmd)
        (chrome :variables)
        multiple-cursors
        (org :variables org-enable-org-contacts-support t org-contacts-files
             '("~/.emacs.d.loadpath/Contacts-Imported.org")
             org-capture-templates
             '(("c" "Contacts" entry
                (file "~/Contacts-Imported.org")
                "* %(org-contacts-template-name))\n:PROPERTIES:\n:EMAIL: %(org-contacts-template-email)\n:END:")))
        (pdf :variables pdf-view-display-size 'fit-page)
        (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
        (spell-checking :variables spell-checking-enable-auto-dictionary t)
        syntax-checking
        (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by BenedictHW** [comment]
Dr,

I have a feeling this may be due to your config. I am unable to reproduce the
bug from my Spacemacs. Usually when "Symbol's value as variable is void" that
means said symbol is undefined. Sometimes wrapping the relevant code in a
"with-eval-after-load" macro solves the issue if the symbol is only undefined at
a certain point in time.

I would check that whatever package code-cells-mode has been successfully
loaded. Do other symbols in the same package show up when you "C-h f" function
names or "C-h v" variable names? Instead of the "C-h k" command try removing
helm-descbinds with the following in your dotspacemacs/layers,

``` emacs-lisp
(helm :packages (not helm-descbinds))

```

And then "C-h b". will give you the loaded keymaps for a particular buffer and
its respective modes. Has code-cells-mode's keymaps listed? Does "C-h m" show
code-cells-mode under it's minor modes?

As an aside, I use https://github.com/nnicandro/emacs-jupyter which has been
able to connect to both the wolfram kernel and sagemath.

HTH,

**Comment by jgrosso** [comment]
I am also having this issue, except for me it's that `string-edit-mode` is void.

**Comment by thanhvg** [comment]
Did you update the packages yet?

**Comment by jgrosso** [comment]
Yup, as recently as this morning (as well as pulling the latest `.emacs.d`). If it's helpful , the error *used* to be about `code-cells-mode` for me too, but then it changed to `string-edit-mode` after I updated packages/Spacemacs a few days ago.

**Comment by jgrosso** [comment]
(I just reset to an old `develop` commit, but the issue is still there, so I suspect the issue might be in the packages or my own config.)

**Comment by DrWaleedAYousef** [comment]
I still will reply @BenedictHW; meanwhile, I update almost daily. This problem seems to reflect on gnus behaviour as I indicated (not very sure)

**Comment by DrWaleedAYousef** [comment]
I updated the issue above to reflect my current configurations. I commented everything inside the user configuration function. The problem is still there.

**Comment by DrWaleedAYousef** [comment]
Oh; one more thing. Just now, after I updated the issue above, I tried to comment out the python layer:
```
     ;; (python :variables
     ;;         python-format-on-save t
     ;;         python-formatter 'yapf ;; default is lsp
     ;;         python-fill-column 99
     ;;         python-backend 'lsp
     ;;         python-lsp-server 'pyright
     ;;         )
```

The problem is gone! However, gnus' problems are the same!

**Comment by tko** [comment]
I had similar problem with code-cells. After tinkering with some things I came up with patch I forgot to send that seems to have fixed the issue.
```diff
diff --git a/layers/+lang/python/packages.el b/layers/+lang/python/packages.el
index d84314e3e..3e5eb7cd2 100644
--- a/layers/+lang/python/packages.el
+++ b/layers/+lang/python/packages.el
@@ -99,10 +99,11 @@
 (defun python/init-code-cells ()
   (use-package code-cells
     :if (not (configuration-layer/layer-used-p 'ipython-notebook))
+    :commands code-cells-mode
+    :hook (python-mode . code-cells-mode)
     :defer t
-    :init
+    :config
     (progn
-      (add-hook 'python-mode-hook 'code-cells-mode)
       (spacemacs/set-leader-keys-for-minor-mode 'code-cells-mode
         "gB" 'code-cells-backward-cell
         "gF" 'code-cells-forward-cell
```
IIRC the main issue was with `:init` vs. `:config` and the other bits are needed to declare the dependencies properly for :config . maybe there's similar issue with `string-edit-mode`

**Comment by taquangtrung** [comment]
> I had similar problem with code-cells. After tinkering with some things I came up with patch I forgot to send that seems to have fixed the issue.
> 
> ```diff
> diff --git a/layers/+lang/python/packages.el b/layers/+lang/python/packages.el
> index d84314e3e..3e5eb7cd2 100644
> --- a/layers/+lang/python/packages.el
> +++ b/layers/+lang/python/packages.el
> @@ -99,10 +99,11 @@
>  (defun python/init-code-cells ()
>    (use-package code-cells
>      :if (not (configuration-layer/layer-used-p 'ipython-notebook))
> +    :commands code-cells-mode
> +    :hook (python-mode . code-cells-mode)
>      :defer t
> -    :init
> +    :config
>      (progn
> -      (add-hook 'python-mode-hook 'code-cells-mode)
>        (spacemacs/set-leader-keys-for-minor-mode 'code-cells-mode
>          "gB" 'code-cells-backward-cell
>          "gF" 'code-cells-forward-cell
> ```

I encountered the same error `mapcar: Symbol’s value as variable is void: code-cells-mode`.

Applying the above patch can resolve it. Thanks a lot, @tko!

**Comment by xuan-w** [comment]
I also have this problem. Since I don't use code-cells, I removed it and everything is fine.

**Comment by ir210** [comment]
> I am also having this issue, except for me it's that `string-edit-mode` is void.

@jgrosso I believe you are using Emacs 29. In that case, if you don't need `string-edit` (SPC x e), you can simply put `string-edit` into the `dotspacemacs-excluded-packages` list.

The reason for that is that Emacs added a new built-in package called `string-edit` in 29 and this is an entirely different package than what Spacemacs uses for "SPC x e". There is a package naming collision here.

See: https://github.com/magnars/string-edit.el/issues/19

**Comment by lebensterben** [comment]
@ir210 

Thanks for the information. I will make a workaround to turn of string-edit on Emacs 29
