### ISSUE TITLE
latex/build is broken

### ISSUE THREAD

**Issue by simonpintarelli** [syl20bnr/spacemacs#15541]
#### Description :octocat:
`M-x latex/build` / `, c` yields: Wrong type argument: stringp, nil

#### Reproduction guide :beetle:
- Start Emacs
- open a latex document
- hit `, c` or `M-x latex/build`

*Observed behaviour:* :eyes: :broken_heart:
wrong type argument

*Expected behaviour:* :heart: :smile:
tex file is compiled to a pdf.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 1439f8b25)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(perl5 rust lua php html javascript
       (dap :variables dap-enable-mouse-support nil)
       emacs-lisp
       (c-c++ :variables c-c++-lsp-enable-semantic-highlight 't c-c++-dap-adapters
              '(dap-lldb dap-gdb-lldb dap-cpptools))
       cmake docker csv git helm
       (ess :variables ess-r-backend 'lsp ess-assign-key "\255")
       ibuffer fortran
       (python :variables python-backend 'lsp python-lsp-server 'pyright python-formatter 'black)
       (ipython-notebook :variables ein-backend 'jupyter)
       latex
       (lsp :variables lsp-headerline-arrow "❯" lsp-use-lsp-ui 't lsp-lens-enable 'nil)
       markdown
       multiple-cursors major-modes pdf ranger sphinx spacemacs-org spacemacs-navigation sourcetrail shell
       (julia :variables julia-backend 'lsp)
       (shell-scripts :variables shell-scripts-backend 'lsp)
       themes-megapack
       (org)
       bibtex
       (yaml :variables yaml-enable-lsp t)
       (shell :variables shell-default-height 30 shell-default-position 'bottom)
       (spell-checking :variables spell-checking-enable-by-default nil)
       version-control treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\(?: \"\\\\\\|\"\\|%\\(?:(\\(?:\\(?:O\\?\\(?:aux\\|idx\\|pdf\\)\\..." nil nil)
  TeX-command-expand(nil)
  TeX-command("LatexMk" TeX-master-file -1)
  (progn (let ((TeX-save-query nil)) (TeX-save-document (TeX-master-file))) (TeX-command latex-build-command 'TeX-master-file -1))
  latex/build()
  funcall-interactively(latex/build)
  call-interactively(latex/build nil nil)
  command-execute(latex/build)

```

**Comment by lizhuohua** [comment]
This is caused by package [auctex-latexmk](https://github.com/tom-tan/auctex-latexmk), see #15467.

This is solved by this [PR](https://github.com/tom-tan/auctex-latexmk/pull/40). Unfortunately seems like the author no longer maintains this package.

**Comment by smile13241324** [comment]
I have created a fork and incorporated the changes from the linked PR into it. Spacemacs now refers to this fork and the build function is working again.

When applying this fix please make sure that the package is really replaced, on my PC emacs did not replace the package unit I did manually remove it.
