### ISSUE TITLE
[version-control] vc-svn-log-view-mode-map error on startup

### ISSUE THREAD

**Issue by practicalli-john** [syl20bnr/spacemacs#15554]
#### Description :octocat:

Warning regarding a variable that is not directly used in the Spacemacs configuration

```
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s value as variable is void: vc-svn-log-view-mode-map
```

#### Reproduction guide :beetle:
- Start Emacs
- Pull latest commits from Spacemacs repository
- `SPC f e U` to update packages
- `SPC f e D` to diff Spacemacs configuration with template (updating any new sections from template)
- Restart Emacs

*Observed behaviour:* :eyes: :broken_heart:

Warning appears on home buffer and in `*messages*` buffer

```
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s value as variable is void: vc-svn-log-view-mode-map
```

*Expected behaviour:* :heart: :smile:

Spacemacs should start without generating a warning

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: magit-forge-pr-toggle-draft (rev. a66c1c9e2)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 (clojure :variables clojure-enable-kaocha-runner t cider-repl-display-help-banner nil cider-print-fn 'puget clojure-indent-style 'align-arguments clojure-align-forms-automatically t clojure-toplevel-inside-comment-form t cider-result-overlay-position 'at-point cider-overlays-use-font-lock t cider-repl-buffer-size-limit 100)
 colors command-log csv emacs-lisp emoji
 (git :variables git-magit-status-fullscreen t magit-diff-refine-hunk t git-enable-magit-todos-plugin t)
 graphviz
 (helm :variables helm-follow-mode-persistent t)
 html javascript json
 (lsp :variables lsp-ui-doc-enable nil lsp-ui-sideline-enable nil treemacs-space-between-root-nodes nil)
 (markdown :variables markdown-live-preview-engine 'vmd)
 multiple-cursors
 (org :variables org-enable-github-support t org-enable-bootstrap-support t org-enable-reveal-js-support t org-want-todo-bindings t org-enable-org-journal-support t org-journal-dir "~/projects/journal/" org-journal-file-format "%Y-%m-%d" org-journal-date-prefix "#+TITLE: " org-journal-date-format "%A, %B %d %Y" org-journal-time-prefix "* " org-journal-time-format "" org-journal-carryover-items "TODO=\"TODO\"|TODO=\"DOING\"|TODO=\"BLOCKED\"|TODO=\"REVIEW\"")
 (ranger :variables ranger-show-preview t ranger-show-hidden t ranger-cleanup-eagerly t ranger-cleanup-on-disable t ranger-ignored-extensions
         '("mkv" "flv" "iso" "mp4"))
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak)
 (spacemacs-modeline :variables doom-modeline-height 12 doom-modeline-major-mode-color-icon t doom-modeline-buffer-file-name-style 'relative-to-project doom-modeline-display-default-persp-name t doom-modeline-minor-modes nil doom-modeline-modal-icon nil)
 spell-checking
 (syntax-checking :variables syntax-checking-use-original-bitmaps t)
 (treemacs :variables treemacs-indentation 1 treemacs-use-filewatch-mode t treemacs-use-follow-mode t)
 theming
 (unicode-fonts :variables unicode-fonts-enable-ligatures t unicode-fonts-ligature-modes
                '(prog-mode)
                unicode-fonts-ligature-set
                '("->" "::" "__" "#{" "#(" "#_" "#_(" "#?" "#:" ".-" ";;" "~@" "->>"))
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 yaml)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by practicalli-john** [comment]
My assumption is the error is generated by the version-control layer, as this seems to have the only code in Spacemacs that refers to the `vc-svn-log-view-mode-map` variable

https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bsource-control/version-control/packages.el#L75-L107

**Comment by smile13241324** [comment]
Do you still see this error on latest develop?
I have thought I have fixed this specific error some days ago.

**Comment by practicalli-john** [comment]
I am afraid I still get the the same error.

I have pulled the latest development commits as of 5 minutes before posting this comment.
I have diff'd my Spacemacs configuration with the template and there are no missing parts
I've updated the packages and restarted Emacs

The error message displays on the Home buffer as Spacemacs starts up, also appears near the start of the `*messages*` buffer.  Once Spacemacs has started there is a red line saying that Spacemacs may not be operational (although Spacemacs seems to be fine other than this warning)

![image](https://user-images.githubusercontent.com/250870/172023860-6ff26b0e-d550-4cd6-b751-fbcb0a9c1927.png)

**Comment by practicalli-john** [comment]
If I comment out the [lines that were added to the +layers/source-control/version-control/packages.el via this commit](https://github.com/syl20bnr/spacemacs/commit/39b9def6d5ef4988ca2862d5198dee611452dfb7), then the error no longer occurs.

I assume this also removes some key binding functionality, so appreciate its probably a change to syntax of these lines that is required
```
      ;; (evilified-state-evilify-map vc-svn-log-view-mode-map
      ;;   :mode vc-svn-log-view-mode)
      ;; (evilified-state-evilify-map vc-git-log-view-mode-map
      ;;   :mode vc-git-log-view-mode)
      ;; (evilified-state-evilify-map vc-git-log-view-mode-map
      ;;   :mode vc-hg-log-view-mode)

```

**Comment by sunlin7** [comment]
Hi @practicalli-john 
I submit a PR #15584 to fix this issue, please help verify the change. Thanks.

**Comment by practicalli-john** [comment]
@sunlin7 yes that works and I see its already been merged, thank you for the quick fix everyone.

**Comment by sunlin7** [comment]
Thank you for confirmation.
