### ISSUE TITLE
void-function consult-completing-read-multiple

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#15555]
This function no longer exists in the [latest version of consult](https://github.com/minad/consult/blob/main/CHANGELOG.org):
`consult-completing-read-multiple` but is used in the [compleseus layer definition](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bcompletion/compleseus/packages.el#L194)

**Comment by thanhvg** [comment]
Can you create a PR to remove that line https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bcompletion/compleseus/packages.el#L194? I think that's all we need.
