### ISSUE TITLE
How to set line numbers only when editing?

### ISSUE THREAD

**Issue by eyesfrog** [syl20bnr/spacemacs#1555]
I have tried to add (global-linum-mode t) in .spacemacs
but the line number will appear in the initial buffer, that is  very ugly!!
So, how to set line numbers **only when I am editing**?

**Comment by tuhdo** [comment]
Simply load it in programming buffers (buffers with `prog-mode-hook`):

```lisp
  (add-hook 'prog-mode-hook #'linum-mode)
```

**Comment by eyesfrog** [comment]
Get it!
Thanks guy.
