### ISSUE TITLE
Symbol’s function definition is void: mu4e--main-action-str

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#15559]
#### Description :octocat:
I have error's when opening mu4e (1.6.10):

```
error in process sentinel: insert: Symbol’s function definition is void: mu4e--main-action-str
error in process sentinel: Symbol’s function definition is void: mu4e--main-action-str
```
My current config if needed:
https://gitlab.com/phenix-factory/config-spacemacs/-/tree/v300

#### Reproduction guide :beetle:
- Start Emacs
- Open mu4e

*Observed behaviour:* :eyes: :broken_heart:
Errors + maildir not showing correctly

*Expected behaviour:* :heart: :smile:
No error's and showing maildir

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 69027b8ee)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(systemd
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 hackernews helm emacs-lisp
 (git :variables git-enable-magit-delta-plugin t)
 github markdown csv
 (org :variables org-enable-github-support t org-enable-org-journal-support t org-journal-dir "~/org/journal/" org-journal-file-format "%Y-%m-%d")
 (shell :variables shell-default-shell 'vterm shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/usr/bin/zsh")
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary nil enable-flyspell-auto-completion t)
 syntax-checking shell-scripts
 (php :variables php-backend 'lsp)
 restclient
 (sql :variables sql-capitalize-keywords t)
 (html :variables css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t web-fmt-tool 'prettier)
 (lsp :variables lsp-use-lsp-ui t lsp-headerline-breadcrumb-enable nil)
 dap
 (javascript :variables javascript-fmt-tool 'prettier javascript-import-tool 'import-js javascript-backend 'lsp)
 (vue :variables vue-backend 'lsp)
 typescript prettier yaml finance colors multiple-cursors unicode-fonts
 (docker :variables docker-dockerfile-backend 'lsp)
 (version-control :variables version-control-global-margin t shell-default-term-shell "/bin/zsh")
 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp/" mu4e-enable-notifications t mu4e-enable-mode-line t mu4e-use-maildirs-extension t)
 (python :variables python-backend 'lsp python-lsp-server 'pyright python-formatter 'black)
 imenu-list dash themes-megapack)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by sebhahn** [comment]
I think [the maintainer of mu4e-maildirs-extension](https://github.com/agpchil/mu4e-maildirs-extension/commit/3f4dce6e297f63869d00bfb9eb574983380314ef) has been too quick in updating the [coming changes in mu 1.7](https://github.com/djcb/mu/blob/master/NEWS.org):

> mu4e is slowly moving from using the ’~'= to the more common '=--'= separator for private functions; i.e., =mu4e-foo becomes mu4e--foo.

The easiest way to fix this problem for now would be downgrading (or deactivating) mu4e-maildirs-extension

**Comment by phenix-factory** [comment]
Well that work. I guess it's a way it temporary fix it until everything is release properly

**Comment by jia-j-chen** [comment]
How do I downgrading (or deactivating) mu4e-maildirs-extension?

**Comment by phenix-factory** [comment]
@jia-j-chen You just need to turn `mu4e-use-maildirs-extension` to `nil`. See my config:

```lisp
     (mu4e :variables
           mu4e-installation-path "/usr/share/emacs/site-lisp/"
           mu4e-enable-notifications t
           mu4e-enable-mode-line t
           mu4e-use-maildirs-extension nil)
```

**Comment by jia-j-chen** [comment]
> @jia-j-chen You just need to turn `mu4e-use-maildirs-extension` to `nil`. See my config:
> 
> ```lisp
>      (mu4e :variables
>            mu4e-installation-path "/usr/share/emacs/site-lisp/"
>            mu4e-enable-notifications t
>            mu4e-enable-mode-line t
>            mu4e-use-maildirs-extension nil)
> ```

That works. Thanks!
