### ISSUE TITLE
pyim cause an error:  variable is void: pyim-dict-manager-mode-map

### ISSUE THREAD

**Issue by winsphinx** [syl20bnr/spacemacs#15568]
#### Description :octocat:
pyim cause an error:
`Error (use-package): pyim/:init: Symbol’s value as variable is void: pyim-dict-manager-mode-map`

#### Reproduction guide :beetle:
- Start Emacs
- The error appears

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: windows-nt
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 85edf6a57)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(
 ......
 (chinese :variables chinese-enable-youdao-dict t pangu-spacing-real-insert-separtor t pyim-page-tooltip
          '(posframe popup minibuffer))
 ......         
```
- System configuration features: ACL GIF GMP GNUTLS HARFBUZZ JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY W32NOTIFY PDUMPER PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XPM ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by tshu-w** [comment]
The `pyim-dict-manager`  need to require manually after 22-05-29, see https://github.com/tumashu/pyim/blob/2f1aaaa9a7f0e6640e5bafb66857a9a0f49e80f8/README.org#2022-05-29-sun-pyim-cregexp-utils-pyim-cstring-utils-和-pyim-dict-manager-需要用户手动-require

**Comment by winsphinx** [comment]
It is already autoload'ed in https://github.com/syl20bnr/spacemacs/blob/85edf6a578c81f12537ac0b1d8b98324625e4275/layers/%2Bintl/chinese/packages.el#L62-L63

**Comment by sunlin7** [comment]
It's my failed, and the PR https://github.com/syl20bnr/spacemacs/pull/15577 will solve the problem.

**Comment by winsphinx** [comment]
@sunlin7 It works perfectly. Thanks.

**Comment by sunlin7** [comment]
Thanks for verifying, I'll try to get it to merge into the repo.

**Comment by sunlin7** [comment]
solution merged
