### ISSUE TITLE
Symbol’s function definition is void: mu4e--main-action-str

### ISSUE THREAD

**Issue by jia-j-chen** [syl20bnr/spacemacs#15575]
#### Description :octocat:
Symbol’s function definition is void: mu4e--main-action-str

#### Reproduction guide :beetle:
- Start Emacs
- Start mu4e with SPC a e m

*Observed behaviour:* :eyes: :broken_heart:
Two errors:
error in process sentinel: mu4e-maildirs-extension-update: Symbol’s function definition is void: mu4e--main-action-str
error in process sentinel: Symbol’s function definition is void: mu4e--main-action-str

If quit mu4e, then I cannot open it again. The error "error in process filter: Symbol’s function definition is void: mu4e--main-action-str" shows up if I try to open mu4e.

*Expected behaviour:* :heart: :smile:
No error.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 85edf6a)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((helm :variables helm-candidate-number-limit 1000)
 emacs-lisp git
 (markdown :variables markdown-live-preview-engine 'vmd)
 bibtex html csv org ess
 (chinese :variables chinese-enable-fcitx t chinese-fcitx-use-dbus t pyim-default-scheme 'microsoft-shuangpin)
 (latex :variables latex-enable-folding t latex-enable-auto-fill t)
 auto-completion ranger version-control pdf
 (mu4e :variables mu4e-use-maildirs-extension t mu4e-installation-path "/usr/share/emacs/site-lisp" mu4e-enable-async-operations t mu4e-maildir "/home/chenj/Maildir" mu4e-sent-folder "/Local_sent" mu4e-headers-full-search nil mu4e-headers-results-limit 500 mu4e-drafts-folder "/Drafts" mu4e-trash-folder "/Deleted_Messages" mu4e-attachment-dir "~/Downloads" mu4e-get-mail-command "offlineimap" mu4e-view-show-images t mu4e-view-show-addresses t mu4e-headers-date-format "%Y-%m-%d %H:%M" mu4e-compose-reply-to-address "jia.j.chen@foxmail.com" user-mail-address "jia.j.chen@foxmail.com" user-full-name "Jia CHEN" send-mail-function 'async-smtpmail-send-it message-send-mail-function 'async-smtpmail-send-it smtpmail-smtp-server "smtp.qq.com" smtpmail-smtp-service 465 smtpmail-stream-type 'ssl smtpmail-auth-credentials
       (expand-file-name "~/.authinfo.gpg")
       mu4e-headers-fields
       '((:date . 18)
         (:flags . 6)
         (:from . 15)
         (:to . 15)
         (:subject))
       mu4e-compose-signature "Jia CHEN @ http://chenjia.gsm.pku.edu.cn" mu4e-maildir-shortcuts
       '(("/INBOX" . 105)
         ("/PKU_Email" . 112)
         ("/Sent_Messages" . 115)))
 better-defaults markdown
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 spell-checking python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 bm
 (colors :variables colors-colorize-identifiers 'all))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by sebhahn** [comment]
see https://github.com/syl20bnr/spacemacs/issues/15559

**Comment by jia-j-chen** [comment]
OK. Thanks!
