### ISSUE TITLE
Spacemacs failure to start correctly even after complete removal and re-installation!

### ISSUE THREAD

**Issue by DrWaleedAYousef** [syl20bnr/spacemacs#15571]
I cannot generate any bug report because spacemacs, all of the sudden, no longer starts correctly even after I fully removed the folder `.emacs.` and re-installed spacemacs. The following message always appear upon starting:
```
Warning (initialization): An error occurred while loading ‘/home/wyousef/.emacs.d/init.el’:

Symbol's value as variable is void: dotspacemacs-startup-banner-scale

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging
```

**All my work is pending now. I cannot do anything**

**Comment by real-or-random** [comment]
Duplicate of #15567.

You'll also need to update `~/.spacemacs`. It's not in `~/emacs.d`.

For a quick fix, try `git checkout 51686e5f1206d57a86d9d33a62ed02c9aa9c7e8b` in `~/.emacs.d`

**Comment by DrWaleedAYousef** [comment]
Sorry, what do you mean by updating '.spacemacs'

**Comment by sunlin7** [comment]
PR #15579 will fix this issue.

**Comment by DrWaleedAYousef** [comment]
I added the line in the `.spacemacs`; it is back almost to normal. However, it seems there is a problem with cashing. It never save the latest files and projects opened.

**Comment by sunlin7** [comment]
It sound like a new issue.
Dose the original issue on this ticket was resolved?  Thanks

**Comment by DrWaleedAYousef** [comment]
Yes; but I just reported this here in the case that it is related or connected.

**Comment by sunlin7** [comment]
Please verify with the last version in develop branch.

**Comment by DrWaleedAYousef** [comment]
> Please verify with the last version in develop branch.
```
85edf6a57 * develop origin/develop org-contacts no longer built-in
```

**Comment by sunlin7** [comment]
Here are the version history, especially the `216b98c` would fix this ticket.

d1bdf6c Evilify the pyim-dict-manager-mode-map after its mode be loaded
5a715c8 [pdf] Evilify the pdf-outline-buffer-mode-map after its mode be loa..
216b98c [core] Add variable `dotspacemacs-startup-banner-scale' to scale..
85edf6a org-contacts no longer built-in
a485b5a Make startup banner scalable (from dotfile)

**Comment by DrWaleedAYousef** [comment]
But I already almost daily update, by pulling the most recent version (I wrote a shel script for that). Can you elaborate please.

**Comment by sunlin7** [comment]
You had pasted your local repo head is 85edf6a57, it's behind the original/develop.

Please try to fetch the repo and check out the original/develop branch manually.

**Comment by DrWaleedAYousef** [comment]
Ok; I will check out the commit that you mentioned. But can I know why the following script that I run almost daily does not guarantee I always have the most recent commit:
```
emacsclient -e '(kill-emacs)'
emacs --daemon -f configuration-layer/update-packages
emacsclient -e '(kill-emacs)'
cd .emacs.d
git pull --rebase
emacs &
```

**Comment by sunlin7** [comment]
change your line `git pull --rebase` to follow line maybe help:

`git fetch --prune origin && git checkout origin/develop`

**Comment by dalanicolai** [comment]
The same PR that caused the bug reported here, indeed also caused the recentf functionality to be broken I have pushed a fix at #15585, which you can very easily implement yourself for the time being...  Thanks @sunlin7 for your help

**Comment by DrWaleedAYousef** [comment]
> The same PR that caused the bug reported here, indeed also caused the recentf functionality to be broken I have pushed a fix at #15585, which you can very easily implement yourself for the time being. Although the first bug, I could reasonably have prevented, this latter bug would have been hard to foresee. I guess we are experiencing the drawback of using the develop branch as the default branch. Thanks @sunlin7 for your help

So, updating from shell using this script guarantees fixing the two bugs?
```
emacsclient -e '(kill-emacs)'
emacs --daemon -f configuration-layer/update-packages
emacsclient -e '(kill-emacs)'
cd .emacs.d
git fetch --prune origin && git checkout origin/develop
emacs &
```

**Comment by dalanicolai** [comment]
Looks like that should work. However, I would do the `git pull` before updating the packages.

**Comment by DrWaleedAYousef** [comment]
> Looks like that should work. However, I would do the `git pull` before updating the packages.

Thanks so much. Now, the cashing problem seems to be resolved but not in Gnus ([this comment](https://github.com/syl20bnr/spacemacs/issues/15479#issuecomment-1149179055)). I am idle now and cannot use my email client.

**Comment by dalanicolai** [comment]
Anybody else using Gnus here? Can you check?

**Comment by sunlin7** [comment]
change your line `git pull --rebase` to follow line maybe help:

git fetch --prune origin && git checkout origin/develop​

________________________________

**Comment by lebensterben** [comment]
closing because it has nothing to do with Spacemacs.
