### ISSUE TITLE
Keyboard-layout layer (bepo) binding mismatch in magit 

### ISSUE THREAD

**Issue by remyzorg** [syl20bnr/spacemacs#15582]
#### Description :octocat:
In magit 's' doesn't stage a file anymore using `keyboard-layout` with `bepo` and evil mode. It was not the case a few month back.

A way to fix this would be to enable `magit` configuration in `keyboard-layout`. But in fact it changes the shortcut displayed, but not the actual shortcut. The magit configuration is supposed to set `k` as _stage_ action, but it is not bounded.

#### Reproduction guide :beetle:

- Use the following package config in .spacemacs
  and set up in evil mode
```
     git
     (keyboard-layout :variables
                      kl-layout 'bepo
                      kl-disabled-configurations '(org magit))
     )
```

- Start Emacs
- cd to any git repository
- edit a file
- SPC-g-s to open magit
- move to the unstaged file

*Observed behaviour:* :eyes: :broken_heart:
- 's' causes the cursor to move

*Expected behaviour:* :heart: :smile:
- 's' stages the file

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 3ba43e291)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(csv yaml ivy emacs-lisp org python ivy
     (rust :variables rust-backend 'racer)
     javascript markdown sql html shell-scripts latex git ocaml themes-megapack
     (reasonml :variables reason-auto-refmt t)
     (keyboard-layout :variables kl-layout 'bepo kl-disabled-configurations
                      '(org)))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by gh-salt** [comment]
I am also using `keyboard-layout` with `bepo` and evil mode, but without disabling the configuration for magit (so my expected behaviour for 's' is that it moves the cursor down and it should be 'k' that stages commits. Since a few weeks, when I type 'k' in magit, instead of staging, it asks whether I want to discard unstaged changes in the file I want to stage. A (tedious) workaround I have found  is to first type '?' then 'k'. Then the file gets staged as wanted. 

@remyzorg : Does that workaround also work for you?

**Comment by smile13241324** [comment]
I have noticed a similiar behaviour in magit's interactive rebasing view where "s" does call "vim substitute" rather than marking the commit for staging. I think there is a bigger issue in the standard evilification of these special buffers. I will try to have a look into this.

**Comment by remyzorg** [comment]
@gh-salt Hey, it works thanks. That's kind of a relief. It's way better than using the terminal.
Note that it also works with magit mode for kl disable using `?-s`.

Still if it can be fixed in some way it could be better... Thanks for the help.

**Comment by JulienDlq** [comment]
Same here (about the issue of `k` not staging anymore but discarding instead!), I can confirm that `?-k` workaround is working for me too, thanks. :+1: 

If it can be fixed, it will be so cool!

**Comment by ejpcmac** [comment]
As a workaround, I’ve added this to my `.spacemacs`:

```elisp
  (with-eval-after-load 'magit
    (define-key magit-mode-map (kbd "k") 'magit-stage))
```

Not sure if it breaks anything else.
