### ISSUE TITLE
No *Recent Files* in the \*spacemacs\* buffer

### ISSUE THREAD

**Issue by SyrakuShaikh** [syl20bnr/spacemacs#15586]
Updated spacemacs today, develop version, emacs 28.1

And now, no `Recent Files` section every time I start spacemacs, only Projects.

 Also, when I use `SPC b b`, there is no *Recentf* buffer. 

Any solution or clue? thanks!

**Comment by jajpater** [comment]
I've got the same problem.

**Comment by jajpater** [comment]
I guess this pr fixes it: https://github.com/syl20bnr/spacemacs/pull/15585

**Comment by SyrakuShaikh** [comment]
OK, thanks for the pr. thank you @jajpater  @dalanicolai !

**Comment by dalanicolai** [comment]
You can very simply implement [the fix](https://github.com/syl20bnr/spacemacs/pull/15585/files) yourself for the time being...

**Comment by smile13241324** [comment]
I have merged a fix please have another go and close this ticket when its fixed @SyrakuShaikh
