### ISSUE TITLE
(tool-bar-mode 1) ignored in dotspacemacs/user-config

### ISSUE THREAD

**Issue by emacdona** [syl20bnr/spacemacs#15583]
#### Description :octocat:
tool-bar-mode in dotspacemacs/user-config is ignored.

#### Reproduction guide :beetle:
- Add following to .spacemacs:
(defun dotspacemacs/user-config ()
  (tool-bar-mode 1)
)
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
If you watch emacs come up, you'll see the toolbar appear briefly, then disappear.

*Expected behaviour:* :heart: :smile:
Toolbar stays put.

I've spent a lot of time trying to find a solution to this. I believe it used to work as expected. I understand that Spacemacs is geared towards keyboard navigation. I dont want the toolbar enabled by default -- I just want a reliable way to modify my configuration so that *I* can have it enabled by default in my environment :-)

If the way I'm attempting to do so is no longer the preferred way, please let me know what is. Thank you for making Spacemacs!

#### System Info :computer:
- OS: darwin
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 756e204d2)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm multiple-cursors treemacs common-lisp
                 (shell :variables shell-default-shell 'vterm)
                 (osx :variables osx-command-as 'hyper osx-option-as 'meta osx-control-as 'control osx-function-as nil osx-right-command-as 'left osx-right-option-as 'left osx-right-control-as 'left osx-swap-option-and-command nil))
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER THREADS TOOLKIT_SCROLL_BARS ZLIB

#### Backtrace :paw_prints:
```
NA
```

**Comment by emacdona** [comment]
Similar for (menu-bar-mode 1) when I'm on Linux. I don't see the same behavior for menu-bar-mode when I'm on a Mac b/c I suspect it's harder to remove the menu bar on OS X (it's not part of the Emacs frame on OS X).

**Comment by dalanicolai** [comment]
For investigating, you could add a `(debug-on-variable-change 'tool-bar-mode)` after you activate `tool-bar-mode` in your user-config. You will find that `tool-bar-mode` is called by `spacemacs/removes-gui-elements` from the `window-setup-hook`.
That hook is run after user-config, so to activate tool-bar-mode again after that you can call/add the function later in that hook with `(add-hook 'window-setup-hook (lambda () (tool-bar-mode)) 99)`.

So it seems Spacemacs was 'deliberately' designed this way. I am not sure if adding configuration options for it will have priority, but let's see! Anyway, I hope these suggestions will solve it for now for you...

**Comment by smile13241324** [comment]
I think in the beginning the emacs facilities were so bad that sylable did hide them automatically as in nobody ever should see them, however they have improved in time so maybe adding a configuration option for this would be useful with the default being to still hide this gui element.

I think a lot of new users will want to be able to fall back to the UI sometimes.

PRs welcome :).

**Comment by emacs18** [comment]
So the simplest way to enable GUI elements is to add one line in `early-init.el` as shown here:

```diff
diff --git a/early-init.el b/early-init.el
index 31e429709..c511dfcc1 100644
--- a/early-init.el
+++ b/early-init.el
@@ -49,6 +49,7 @@
 ;; see https://www.gnu.org/software/emacs/manual/html_node/emacs/Early-Init-File.html
 (add-hook 'window-setup-hook 'spacemacs/removes-gui-elements)
 (add-hook 'tty-setup-hook 'spacemacs/removes-gui-elements)
+(advice-add 'spacemacs/removes-gui-elements :around 'ignore)
 
 ;; Setup to use straight.el package manager rather than the default package.el.
 (let* ((default-directory (file-name-directory load-file-name))
```

If you don't want to touch `early-init.el`, then adding the following in `dotspacemacs/user-config` should work as well:

```elisp
(remove-hook 'window-setup-hook 'spacemacs/removes-gui-elements)
(remove-hook 'tty-setup-hook 'spacemacs/removes-gui-elements)
(menu-bar-mode 1)
(scroll-bar-mode 1)
(tool-bar-mode 1)
(tooltip-mode 1)
```

There may have been a good reason years ago to disable GUI, but perhaps that reason no longer applies. I think the default today should be to enable all GUI elements.

**Comment by emacdona** [comment]
Thank you for all of the suggestions. I opted for removing the hooks in the user-config before toggling the gui elements (@emacs18 's second solution above -- it worked) because it seemed like the most "self documenting" to me.

Regarding this comment:
` I think the default today should be to enable all GUI elements.`

Everyone on this thread so far but me is a Contributor or Collaborator. That's up to you all :-)

But, my opinion is: I thought the spacemacs philosophy was "keyboard first", and I'm totally fine with that. I'm just happy I have a way to make my desired configuration permanent now (instead of manually toggling on every startup). The toolbar does take up a lot of screen real estate -- I bet you'd get complaints if you make it enabled by default ;-)

Anyway, thanks again, and thank you for making Spacemacs!

**Comment by smile13241324** [comment]
We should add a new setting to the dotfile allowing to select whether to disable UI elements. The default should be to hide the toolbar. However new users should have an easy way to enable it and should not be forced to hack their user-config.

PRs are welcome :).
