### ISSUE TITLE
Do we still need to keep `vim-empty-lines` layer, or merge it into `spacemacs-evil` to replace `vi-tilde-fringe`?

### ISSUE THREAD

**Issue by rayw000** [syl20bnr/spacemacs#15596]
I notice that `spacemacs-evil` layer requires package `vi-tilde-fringe` to mark empty lines with a leading `~`, while `vim-empty-lines` layer uses `vim-empty-lines-mode` to implement the same feature. Do we need to keep both of them? Or could we drop `vim-empty-lines` layer and move its code into `spacemacs-evil` to replace `vi-tilde-fringe`?

**Comment by smile13241324** [comment]
Lets merge it. I will check your PR later.
