### ISSUE TITLE
error on fresh spacemacs installation

### ISSUE THREAD

**Issue by w6jq** [syl20bnr/spacemacs#15598]
#### Description :octocat:
An error occurred while installing vim-powerline (error: (wrong-type-argument package-desc nil))

#### Reproduction guide :beetle:
- fresh installation of spacemacs
- Start Emacs
- error then pops up

*Observed behaviour:* :eyes: :broken_heart:
emacs still seems usable, despite the error

*Expected behaviour:* :heart: :smile:
no error

#### System Info :computer:
- OS: gnu/linux (opensuse)
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 22eaeb8ef)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM XWIDGETS GTK3 ZLIB

#### Backtrace :paw_prints:
```

```

**Comment by slwolfram** [comment]
i'm getting the same error on fresh install, opensuse leap 15.2

**Comment by BenedictHW** [comment]
1. See commit d059c4c0b2739a8a10c3e9b28f3e98de89d21a17. Update to develop HEAD?

2. I remember seeing an opensuse specific issue with packages here, #15629

HTH,

**Comment by brossaip** [comment]
I have the same problem in my opensuse Tumbleweed distribution. I have followed the link of BenedictHW and I have written 
```
(defvar quelpa-build-explicit-tar-format-p t
     "Ensure Qulpa calls tar with the argument `gnu' to the `--format' option.")
``` 
in `early-init.el` as mentioned in the link and the error has disappeared.

Thanks BenedictHW for the suggestion!

**Comment by lebensterben** [comment]
@brossaip 

Please retry with the latest commit (after removing the changes you made to early-init.el).

**Comment by Xanaxus** [comment]
@lebensterben It works now I had a similar issue yesterday too

**Comment by lebensterben** [comment]
@mgscott1 are you on latest develop?

**Comment by mgscott1** [comment]
@lebensterben 
I think so.
I installed using git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d.
Currently git pull shows everything is up-to-date

**Comment by lebensterben** [comment]
@mgscott1 
What do you get from `tar --show-defaults`?

**Comment by mgscott1** [comment]
@lebensterben 
Mac tar doesn't seem to have that option.
I am getting tar: Option --show-defaults not support in terminal and eshell
I also couldn't find that option on tar man page

**Comment by lebensterben** [comment]
@mgscott1 

gnu tar is required.

**Comment by mprentice** [comment]
For anyone else finding this happening on Mac OS X, install gnu-tar with homebrew and the error should disappear. `brew install gnu-tar`
