### ISSUE TITLE
Lua Syntax highlighting breaks, if there is a single quote (') in the comment line.

### ISSUE THREAD

**Issue by yssource** [syl20bnr/spacemacs#15607]
A single quote in my comment line. 
`-- we need only index it to force load it's value`

I have these modes enabled.
- lua
- lsp + lua-language-server
- tree-sitter

![Screenshot_2022-06-21_17-40-27](https://user-images.githubusercontent.com/3756334/174770779-926e7e1f-4dde-4012-9d0e-7b8c23b8b925.png)

Syntax highlighting works again, if remove the single quote from the comment line.
`-- we need only index it to force load its value`

![Screenshot_2022-06-21_17-52-03](https://user-images.githubusercontent.com/3756334/174771918-b145ca1b-fb48-419d-814b-d8b3f1dc4018.png)

**Comment by dalanicolai** [comment]
I can not reproduce this behavior? Does it occur on all 'comment' lines?

If it still occurs, can you test using `emacs -q`?
You should [add Melpa archive](https://melpa.org/#/getting-started) and refresh package contents.
Then install and load lua-mode...
Please let us know if behavior occurs there...

**Comment by yssource** [comment]
It only happens on lua file comment lines, if there are single `'` or `"` there.

`emacs -q` with lua-mode has no such Syntax highlighting problem.

I will take a look into my spacemacs configurattion.

**Comment by lebensterben** [comment]
Is it caused by tree-sitter?

**Comment by yssource** [comment]
I tested it with [tree-sitter-lua](https://github.com/Azganoth/tree-sitter-lua/issues/14), it is not its problem.
Maybe it is concerned with [elisp-tree-sitter](https://github.com/emacs-tree-sitter/elisp-tree-sitter).

**Comment by lebensterben** [comment]
why would elisp-tree-sitter be active in a Lua file?

**Comment by yssource** [comment]
Sorry, It's caused by my personal user-config.
`(add-hook 'prog-mode-hook #'(lambda () (modify-syntax-entry ?- "w")))`

The dash is the comment mark in lua-mode, after commenting out the line, the syntax highlighting works well.
