### ISSUE TITLE
org-mode issues after removal of vim-empty-lines layer

### ISSUE THREAD

**Issue by Rav830** [syl20bnr/spacemacs#15605]
#### Description :octocat:
Removal of the vim-empty-lines layer seems to have caused issues with Org-mode behavior.
From what I have encountered:
1) it breaks the functionality of org-latex-export-to-pdf (and probably all other org-export functions) with an error message mentioning vim-empty-lines
2) causes strange behavior when running `org-insert-todo-heading` when inside a checklist.

#### Reproduction guide :beetle:
1)
- Start Emacs
- Create a minimal org file such as the following
```
* heading A
** sub heading
some content
* heading B
** sub heading
```
- place the cursor on "heading A" and then run `C-c C-e C-s l o` and it might produce the error

2)
- Start Emacs
- Create the following minimal org file
```
* heading 1
- [ ] 
- [ ] some text must be here
```
- place the cursor at the end of the last line and in normal mode run `org-insert-todo-heading`
- Then the cursor will jump to the bottom of the file and add in a bunch of non-whitespace... not really sure how to describe it.

*Observed behaviour:* :eyes: :broken_heart:
described above

*Expected behaviour:* :heart: :smile:
1) to create a pdf file of with just the contents of "heading A"
2) to insert a new check box below so the org file looks like the following:
```
* heading 1
- [ ] 
- [ ] some text must be here
- [ ]
```

*Note:* I rolled back to the commit you see below (ee95121e6) and this is the point at which everything worked.
I had the commit at (e74610ddb) when I faced errors.
Also the issue seems to be dependent on if there is a new line or not after the cursor or if there is extra spaces, honestly not sure but I described the method to reproduce to the best of my ability.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: nil (rev. ee95121e6)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql autohotkey erc typescript javascript yaml csv auto-completion bibtex emacs-lisp helm helpful html latex markdown multiple-cursors nginx org pdf python lsp systemd shell spell-checking treemacs ibuffer
     (latex :variables latex-build-command "LatexMk" latex-enable-folding t)
     (org :variables org-enable-org-journal-support t org-enable-roam-support t)
     (python :variables python-backend 'lsp python-lsp-server 'pyright)
     (spell-checking :variables spell-checking-enable-by-default nil))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
N/A

**Comment by smile13241324** [comment]
I think this PR was rolled back, can you check if this still occurs?

**Comment by Rav830** [comment]
Seems like the issue has been resolved.

I updated to the latest commit I saw (ed8ddd9) in both a fresh install and an update and the errors I listed have been resolved.
