### ISSUE TITLE
error in process sentinel: Symbol’s function definition is void: compat-assoc

### ISSUE THREAD

**Issue by Zlopez** [syl20bnr/spacemacs#15611]
#### Description :octocat:
Magit status window is not being rewritten and instead you will see
```
error in process sentinel: Symbol’s function definition is void: compat-assoc
```

#### Reproduction guide :beetle:
- Start Emacs
- Open any git project
- SPC g s
- b b
- Change to any branch

*Observed behaviour:* :eyes: :broken_heart:
```
error in process sentinel: Symbol’s function definition is void: compat-assoc
```

*Expected behaviour:* :heart: :smile:
Magit status window is changed correctly

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 4eaff2526)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(asciidoc shell-scripts ansible systemd html javascript rust yaml python
          (auto-completion :variables auto-completion-enable-snippets-in-popup t)
          emacs-lisp git markdown multiple-cursors org
          (ivy :variables ivy-enable-advanced-buffer-information t)
          spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER GMP

**Comment by bschwehn** [comment]
Thanks. I deleted my emacs.d/melpa folder. During startup I got the error "Package compat is unavailable. Is the package name misspelled?"
I installed compat manually with package-install.

The error is now gone and SPC h d **f** finds compat-assoc now.u

No idea why the automatic install failed.

**Comment by noidi** [comment]
Based on @bschwehn's comment (thanks!) I managed to fix this problem without deleting the `elpa` directory by running `package-reinstall` and selecting the `compat` package.

**Comment by Zlopez** [comment]
@bschwehn advice fixed the issue for me.

**Comment by creasyw** [comment]
I deleted the `elpa` and reinstalled everything, but the problem still prevailed... @noidi advice above fixed the issue for me.

**Comment by tanyabouman** [comment]
I had the same problem and `package-reinstall` with `compat` didn't work.  Instead, I got it to work with `package-reinstall` and `magit`.

Thanks for the hints in this issue.
