### ISSUE TITLE
For simplicity the documentation always refers to the leader key as SPC

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1561]
Wouldn't it make more sense to refer to the leader key as `<leader>` ?

**Comment by syl20bnr** [comment]
:-) There are literally thousands of key binding reference to update and I don't feel that it will be more readable with `<leader>` everywhere. See `SPC` as a more readable shortcut for `<leader>`.

**Comment by geo7** [comment]
Well I don't see how a sub for `<leader>` is more readable than `<leader>` but hey ho ;) Been going through it a bit today (coming from vim), thanks for the work... Separate issue I guess but it'd be ace if there was a guide on converting vimrc bindings to Spacemacs / Emacs or whatnot. Just basic things like `jf` exits insert mode (for me) and `J` saves a file (in normal)

Thanks though! :)

**Comment by syl20bnr** [comment]
@geo7 there was a lot of demand lately for a guide for vimmers and I [believe one is on its way](https://github.com/syl20bnr/spacemacs/pull/1565) :-)
