### ISSUE TITLE
Mu4e layer breaks with upgrade to 1.8.1

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#15618]
#### Description :octocat:
The mu4e layer breaks when upgrading to mu 1.8.1

#### Reproduction guide :beetle:
- Start Emacs
- Watch it not load completely

*Observed behaviour:* :eyes: :broken_heart:
Error message in `*Messages*`:

```
File mode specification error: (file-missing Cannot open load file No such file or directory mu4e-meta)
```

Since it fails to load completely quite a few things are broken in other layers too.

*Expected behaviour:* :heart: :smile:
That everything loads and works well

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. c9db02842)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash docker evil-commentary evil-snipe
 (git :variables git-enable-magit-todos-plugin t)
 (helm :variables helm-no-header t)
 (lsp :variables lsp-lens-enable nil lsp-use-lsp-ui t lsp-use-upstream-bindings nil)
 mu4e multiple-cursors restclient
 (shell :variables shell-default-shell 'ansi-term)
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak)
 spacemacs-editing-visual spacemacs-visual
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking templates tree-sitter vinegar
 (xclipboard :variables xclipboard-enable-cliphist t)
 (c-c++ :variables c-c++-backend 'lsp-ccls)
 (clojure :variables clojure-enable-sayid t clojure-enable-clj-refactor t clojure-enable-linters 'clj-kondo clojure-backend 'lsp)
 emacs-lisp
 (go :variables go-backend 'lsp go-format-before-save t)
 (haskell :variables haskell-completion-backend 'lsp haskell-process-type 'cabal-repl)
 (python :variables python-formatter 'yapf)
 rust shell-scripts csv graphviz html json latex markdown
 (org :variables org-enable-reveal-js-support t org-enable-roam-support t org-roam-enable-protocol nil org-enable-github-support t)
 nixos spacemacs-org
 (sql :variables sql-auto-indent nil)
 pandoc systemd terraform yaml direnv mt-misc projectile-extra roam-extra)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS WEBP XIM XWIDGETS GTK3 ZLIB

**Comment by BenedictHW** [comment]
This may sound obvious, but can mu4e-meta.el be found at
"/usr/share/emacs/site-lisp/mu4e"? `mu4e-installation-path'.

**Comment by magthe** [comment]
No, I can't find it there.

It looks like they renamed it, https://github.com/djcb/mu/commit/cf0f72e4a48ac7029d7f6758b182d4bb559f8f49

**Comment by NSchweers** [comment]
This seems to do the trick:

```diff
-        (require 'mu4e-meta)
+        (if (version<= "1.8.2" mu4e-mu-version)
+            (require 'mu4e-config)
+          (require 'mu4e-meta))
```

**Comment by jajpater** [comment]
@NSchweers Please make it a PR

**Comment by motevets** [comment]
@jajpater correct. @NSchweers 's patch worked for me.

**Comment by jajpater** [comment]
I get a new error: 
`An error occurred while pre-configuring org in layer mu4e (error: (void-variable mu4e-mu-version))`

**Comment by NSchweers** [comment]
> @NSchweers It doesn´t work here. (I guess this patch should be applied in packages.el of the mu layer?)

Yes, that’s where I made the change.

**Comment by motevets** [comment]
@NSchweers are you going to submit a PR?

**Comment by NSchweers** [comment]
> @NSchweers are you going to submit a PR?

At first I was about to do so, but then @jajpater got a new error.  I have not worked on this layer before (I only use it), so I have no idea how drastic it is.  I guess I’ll just create one, and then the maintainers can decide :slightly_smiling_face:

**Comment by NSchweers** [comment]
I have no idea how this could happen, but now I havea similar problem to the one @jajpater mentioned: `Error in dotspacemacs/user-config: Symbol’s value as variable is void: mu4e-mu-version`

Should this issue be re-opened?

**Comment by smile13241324** [comment]
Hmm I think so, can you check if this is called by your last PR?

**Comment by NSchweers** [comment]
It was my commit, yes.  I’ve worked out a solution.  I’m not very happy with it, but it works.  I’m working on creating a new PR right now.
