### ISSUE TITLE
configuration-layer/create-layer does not respect dotspacemacs-configuration-layer-path

### ISSUE THREAD

**Issue by idbrii** [syl20bnr/spacemacs#1562]
When I run configuration-layer/create-layer, it creates the layer in ~/.emacs.d/private. I would expect it to respect dotspacemacs-configuration-layer-path so I can point it to a git repository instead of inside spacemacs config.

I want to version control my private layers as part of a larger dotfile repository. Doing so is messy if they're inside the spacemacs git repo. I'd prefer to avoid using links (simplicity of setup and for actual machine-local and unversioned private layers).

Is there a way to have create-layer use my configuration-layer-path? I'm setting configuration-layer-path like this:

     dotspacemacs-configuration-layer-path '("~/data/settings/spacemaconfigs/")

Spacemacs appears to be correctly reading my configuration-layer-path (I got it working in #1550).

**Comment by louy2** [comment]
The variable is a list, so in case there are more paths in it, it's not clear which path does `configuration-layer/create-layer` should respect. The var is not designed to do this. We need a new variable.

In the meantime I think you can make do with a symlink.

**Comment by idbrii** [comment]
Seems like the first one would be a good choice. Do people generally have many items in that list? If you wanted to use private/, would you put it in that list?

Or maybe another function that prompts you to pick an element from the list as the destination for the new layer?

**Comment by syl20bnr** [comment]
The documentation of the function is clear:

> Ask the user for a configuration layer name and create a layer with this
name in the private layers directory.

Using the first entry of the variable `dotspacemacs-configuration-layer-path` can be confusing and it will be harder to explain, i.e. if `dotspacemacs-configuration-layer-path` is nil then it will create it.... etc

I prefer to always create it in private directory (which works out of the box without adding it to the layer path variable) and let the user move it around if needed.

**Comment by TheBB** [comment]
This function now asks for a path.
