### ISSUE TITLE
Highlight trailing whitespace in text-mode instead of only in prog-mode

### ISSUE THREAD

**Issue by real-or-random** [syl20bnr/spacemacs#15621]
Currently we do this only in `prog-mode`:
https://github.com/syl20bnr/spacemacs/blob/c9db028421a74eb8339152ae3c2fe694dc322216/layers/%2Bspacemacs/spacemacs-defaults/packages.el#L513

The config option just describes it as "Show trailing whitespace":
https://github.com/syl20bnr/spacemacs/blob/c9db028421a74eb8339152ae3c2fe694dc322216/core/templates/.spacemacs.template#L495-L496

I think people who want to have this functionality, typically would also want to have it in `text-mode`. This will be consistent with line numbers, which are also enabled in `prog-mode` and in `text-mode`. But I wanted to ask here first before opening a PR, not sure if everyone agrees.

In any case, the docs could be improved. They should explain in which modes this is enables (similar to the docs for line numbering, which clearly state the modes:

https://github.com/syl20bnr/spacemacs/blob/c9db028421a74eb8339152ae3c2fe694dc322216/core/templates/.spacemacs.template#L406-L408

**Comment by emacs18** [comment]
Following comment change clarifies this.
```diff
diff --git a/core/templates/.spacemacs.template b/core/templates/.spacemacs.template
index 564c442bb..e899e8416 100644
--- a/core/templates/.spacemacs.template
+++ b/core/templates/.spacemacs.template
@@ -486,8 +486,9 @@ It should only modify the values of Spacemacs settings."
    ;; (default nil - same as frame-title-format)
    dotspacemacs-icon-title-format nil
 
-   ;; Show trailing whitespace (default t)
-   dotspacemacs-show-trailing-whitespace t
+   ;; Color highlight trailing whitespace in all prog-mode derived modes such as
+   ;; c++-mode, python-mode, emacs-lisp, etc. (default t)
+   dotspacemacs-show-trailing-whitespace t 
 
    ;; Delete whitespace while saving buffer. Possible values are `all'
    ;; to aggressively delete empty line and long sequences of whitespace,
```

**Comment by emacs18** [comment]
Following enables highlighting of trailing whitespaces even for text-mode:
```diff
diff --git a/layers/+spacemacs/spacemacs-defaults/packages.el b/layers/+spacemacs/spacemacs-defaults/packages.el
index 501ac9e1e..60c4ab137 100644
--- a/layers/+spacemacs/spacemacs-defaults/packages.el
+++ b/layers/+spacemacs/spacemacs-defaults/packages.el
@@ -511,6 +511,7 @@
          'trailing-whitespace nil
          :background (face-attribute 'font-lock-comment-face :foreground)))
       (add-hook 'prog-mode-hook 'spacemacs//trailing-whitespace)
+      (add-hook 'text-mode-hook 'spacemacs//trailing-whitespace)
 
       (spacemacs|add-toggle whitespace
         :mode whitespace-mode
```
Perhaps we should document somewhere that adding one line like this is all that is needed to enable trailing whitespace mode for other mode.

**Comment by real-or-random** [comment]
@emacs18 

> I think people who want to have this functionality, typically would also want to have it in `text-mode`. This will be consistent with line numbers, which are also enabled in `prog-mode and in `text-mode`. But I wanted to ask here first before opening a PR, not sure if everyone agrees.

So you disagree with this?

**Comment by emacs18** [comment]
I'm not sure mainly because I don't  seem to run into text-mode that often and so I have not made up my mind as whether trailing whitespace mode would be useful in text-mode derived major modes.  I would be ok if my second patch above is applied to enable trailing whitespace mode for text-mode.  If folks object to this change, then it would be easy enough to revert.

I suppose we could add another user option to list modes to enable trailing white space, but I'm not sure that would be warranted.  I would not add such option myself.

**Comment by tko** [comment]
If memory serves some text formats like markdown and yaml have significant trailing whitespace and as such would benefit from the highlight. Then again, one could argue such highlighting should be covered by dedicated modes themselves.
