### ISSUE TITLE
Org babel Python code block with :session hangs Emacs 28.

### ISSUE THREAD

**Issue by srgkoshelev** [syl20bnr/spacemacs#15620]
#### Description :octocat:
Org babel Python code block with :session hangs Emacs 28. This happens on brew cask aka emacsformacos.com, emacs-plus, and emacs-mac. It works on emacsformacos.com version 27 and emacs-plus@27.

It is worth mentioning that starting python with M-x `run-python` and inputing any commands there leads to input echoed to the output. Online search led to some recommendations of installing gnureadline (using brew) or pyreadline (using pip), none of which helped =(

Also, if python has been started using M-x `run-python` and the code block executed after, this kind of error is returned instead of freezing:
`: __PYTHON_EL_eval("try:\n with open('/var/folders/rq/v68ffv5s7lgc370y5pg65vgm0000gr/T/babel-optvAh/python-A9aezU') as __org_babel_python_tmpfile:\n exec(compile(__org_babel_python_tmpfile.read(), __org_babel_python_tmpfile.name, 'exec'))\nexcept:\n raise\nfinally:\n print('`

#### Reproduction guide :beetle:
- Start Emacs
- Create an org-mode file
- Add any python code with :session header arg, e.g.:
  ```
  #+begin_src python :results output :session test
  print(2)
  #+end_src
  ```
- `,,` or `C-C C-C` the code block
- Get emacs frozen
- Try singing "Let it go" to it to no avail

*Observed behaviour:* :eyes: :broken_heart:
Emacs is frozen.

*Expected behaviour:* :heart: :smile:
Code block executed, results obtained, salary paid.

#### System Info :computer:
- OS: darwin
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. c9db02842)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml html markdown csv helm auto-completion emacs-lisp finance python git
      (org :variables org-enable-org-journal-support t org-enable-roam-support t org-enable-reveal-js-support t)
      spell-checking syntax-checking latex epub pandoc)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER THREADS TOOLKIT_SCROLL_BARS ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by codelahoma** [comment]
I just ran into this myself (same system info as @srgkoshelev, other than layers). If I start up a python REPL using `spacemacs/python-start-or-switch-repl` (triggered with `,'` while in an edit buffer for one of the code blocks, then the session works.

If I forget to do that, I end up having to Force Quit.

**Comment by lebensterben** [comment]
Cannot produce this bug on Linux.
