### ISSUE TITLE
Graphical Spacemacs fails on Thinkpad T500

### ISSUE THREAD

**Issue by stellarskylark** [syl20bnr/spacemacs#15633]
#### Description :octocat:
When launching graphical Spacemacs on my Thinkpad T500, it appears to begin loading correctly, and then after the loading bar fills completely, it hangs. The problem does not occur on my desktop (which has modern hardware), or in terminal Spacemacs. Only thing I can guess is that my Thinkpad doesn't support OpenGL 3, but I don't know if Spacemacs uses anything there. The problem occurs on a fresh install of `spacemacs-base`.

#### Reproduction guide :beetle:
- Start Emacs in graphical mode on a Thinkpad T500.

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs no longer accepts input and entirely ceases rendering; when I switch workspaces in i3 and switch back, the window is replaced with a blank gray screen.

*Expected behaviour:* :heart: :smile:
Doesn't hang, Spacemacs is usable.

#### System Info :computer:
- OS: gnu/linux (Void Linux)
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 7af1a2172)
- Graphic display: nil (I'm running it in the terminal right now because no graphical version of Emacs works)
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion dtrt-indent elfeed emacs-lisp git helm
                 (languagetool :variables langtool-default-language "en-US" langtool-language-tool-jar "/usr/share/java/languagetool/languagetool-commandline.jar" langtool-java-classpath "/usr/share/java/languagetool/*")
                 lsp markdown multiple-cursors nim outshine org ranger shell-scripts spell-checking spotify syntax-checking treemacs xclipboard)
```
- System configuration features: ACL GMP GNUTLS JSON LCMS2 LIBXML2 MODULES NOTIFY INOTIFY PDUMPER SECCOMP SOUND THREADS XIM ZLIB

**Comment by thanhvg** [comment]
Does `emacs -Q` work?

**Comment by stellarskylark** [comment]
Yes, I get a similar result to graphical Emacs without Spacemacs.

**Comment by thanhvg** [comment]
Can you try:

- back up and delete `~/.spacemacs.env`

- `emacs --debug-init` hopefully it would throw some errors

**Comment by stellarskylark** [comment]
No errors, this is all the output I get in the terminal:
```
Loading /home/skylar/.emacs.d/core/core-early-funcs.el (source)...
Loading /home/skylar/.emacs.d/core/core-early-funcs.el (source)...done 
```

**Comment by thanhvg** [comment]
ok try to run in daemon mode 
- enable daemon: `emacs --daemon` 
- connect to it: `emacsclient --create-frame`

**Comment by stellarskylark** [comment]
The daemon starts correctly but the client hangs just like before.

**Comment by thanhvg** [comment]
then `emacsclient --create-frame -nw` to connect to daemon in terminal mode. Then `spc b m` to select the *message* buffer see if any errors there. Also check for other suspicious buffers with `spc b b`.

you can start over again with `emacs --daemon --debug-init` too.

**Comment by stellarskylark** [comment]
No errors in `emacs --daemon --debug-init`. No errors in the messages buffer, though I actually can't check for messages after killing the graphical client. If I kill the client after it hangs, the window does not go away until I also kill the daemon. 

There was an `*Async-native-compile-log*` which was apparently compiling a variety of packages. After letting it finish, the buffer no longer appears and the error still occurs.

**Comment by stellarskylark** [comment]
Here is the output from `emacs --daemon --debug-init` just in case there's anything there I missed that might be important: https://gist.github.com/stellarskylark/502047c542fcf1d054a8fbb9b2a8dcb6

**Comment by stellarskylark** [comment]
Update: I compiled Emacs manually from the 28.1 release source, and it has inexplicably begun working. Maybe there's some kind of problem with Void's packaged version of Emacs.
