### ISSUE TITLE
MacOS install failed

### ISSUE THREAD

**Issue by zhumingpassional** [syl20bnr/spacemacs#15641]
Method 1

$ brew install emacs-mac --with-spacemacs-icon

it raises error:
Error: No such file or directory @ rb_sysopen - /Users/xxx/Library/Caches/Homebrew/downloads/7d0352be7245648d93bcdde92042e89cd80327103bfcc1b2d170b0e147076b35--gmp-6.2.1.big_sur.bottle.tar.gz

Method 2
$ cd ~/.emacs.d
$ git clone https://github.com/syl20bnr/spacemacs.git
Then open emacs. the spacemacs does not come out. 

could you pls provide any help?

thanks.

**Comment by BenedictHW** [comment]
I don't have a mac so maybe others can comment on method 1. For method 2, just to get the obvious out of the way,

~/.emacs.d/init.el

and not

~/.emacs.d/spacemacs/init.el

right? Can you be more specific than spacemacs does not come out?

**Comment by zhumingpassional** [comment]
thanks for your response.

when installing spacemacs, it has not relationship with init.el.

after executing the commands:
$ cd ~/.emacs.d
$ git clone https://github.com/syl20bnr/spacemacs.git

I open emacs, there is no spacemacs, i.e., it is the same as without executing the above commands. I did see any spacemacs related things in the screen of emacs.
