### ISSUE TITLE
[Ruby] Support Sorbet LSP

### ISSUE THREAD

**Issue by sir4ur0n** [syl20bnr/spacemacs#15644]
Currently Spacemacs [ruby layer](https://develop.spacemacs.org/layers/+lang/ruby/README.html) only supports [Solargraph LSP](https://emacs-lsp.github.io/lsp-mode/page/lsp-solargraph/).

Would it be possible to add support for [Sorbet LSP](https://emacs-lsp.github.io/lsp-mode/page/lsp-sorbet/) please? :pray:

**Comment by alexey0308** [comment]
Hi Julien @sir4ur0n,  please take a look at the documentation of [lsp-mode](https://emacs-lsp.github.io/lsp-mode/page/faq/#i-have-multiple-language-servers-registered-for-language-foo-which-one-will-be-used-when-opening-a-project): different backends have different priority values. It should be possible to disable `solargraph` by including it into lsp-disabled-clients (see e.g. M-x customize-variable) or just uninstall it, so it does not get precedence over the `sorbet`.

**Comment by lebensterben** [comment]
we can add some documentations to ruby layer, and optionally make it configurable via a layer variable.

**Comment by sir4ur0n** [comment]
Thank you @alexey0308 for the link, I don't know how I had missed that FAQ part :bow: 

That being said I agree with @lebensterben : I think it would be worth at least documenting how to use and potentially configure it too :+1:
