### ISSUE TITLE
Coding system complaint on opening image

### ISSUE THREAD

**Issue by Kazark** [syl20bnr/spacemacs#15650]
#### Description :octocat:
When I go to open an image, this pops up:

```
These default coding systems were tried to encode the following
problematic characters in the buffer ‘ *temp file*’:
  Coding System           Pos  Codepoint  Char
  utf-8                     1  #x3FFF89   �
                           20  #x3FFFC0   �
                           24  #x3FFFB4   �
                           31  #x3FFF94   �
                           32  #x3FFFD1   �
                          ...             

However, each of them encountered characters it couldn’t encode:
  utf-8 cannot encode these: � � � � � � � � � � ...

Click on a character (or switch to this window by ‘SPC w o’
and select the characters by RET) to jump to the place it appears,
where ‘SPC u C-x =’ will give information about it.

Select one of the safe coding systems listed below,
or cancel the writing with C-g and edit the buffer
   to remove or modify the problematic characters,
or specify any other coding system (and risk losing
   the problematic characters).

  raw-text no-conversion
```

The image does display; I get this in a new buffer. The image buffer is not
named ` *temp file*`; it is, say, `future.png`.

This didn't "used to" happen but I don't have a sense of when it changed.

#### Reproduction guide :beetle:

- Start Emacs
- Open a PNG

*Observed behaviour:* :eyes: :broken_heart:

Get an additional annoying popup. (Particularly annoying if you are rebuilding
the PNG, or opening many files.)

*Expected behaviour:* :heart: :smile:
Emacs just displays the image without any annoying popups. Who said it's just a
_text_ editor? 😁

#### System Info :computer:
- OS: darwin
- Emacs: 29.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: keith (rev. 03d745885)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 helm helpful
 (org :variables org-todo-dependencies-strategy 'semiauto org-enable-verb-support t org-enable-appear-support t)
 emoji agda c-c++
 (clojure :variables clojure-enable-linters
          '(joker clj-kondo)
          clojure-enable-fancify-symbols t clojure-backend 'cider)
 emacs-lisp fsharp graphviz
 (haskell :variables haskell-completion-backend 'ghci)
 html
 (java :variables java-backend nil)
 javascript jsonnet kotlin markdown prolog rust
 (scala :variables scala-auto-treeview nil scala-enable-gtags nil scala-backend nil)
 scheme sql typescript yaml
 (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
 osx
 (git :variables evil-collection-magit-use-y-for-yank t evil-collection-magit-want-horizontal-movement t git-enable-magit-delta-plugin t)
 version-control
 (colors :variables colors-colorize-identifiers 'variables)
 themes-megapack gtags
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 evil-better-jumper search-engine)
```
- System configuration features: ACL GIF GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS WEBP XIM ZLIB

**Comment by lebensterben** [comment]
does this happen to any PNG file?
can you attach one so can I try?

**Comment by Kazark** [comment]
However, when I tried to generate a MWE just now, it didn't pop up. So this might be something rather more arcane than I expected. Unfortunately, the images that have been triggering it have proprietary information, so I can't upload them.

**Comment by Kazark** [comment]
![image](https://user-images.githubusercontent.com/3661051/179624465-71b8e18c-b2fc-4b1a-b9e1-b880fb75fda8.png)

If you aren't able to reproduce it with this, try naming it `sysarch.png`. It should happen then. Without that being the name, it shouldn't happen. That's what I'm seeing.

**Comment by lebensterben** [comment]
Cannot reproduce even after I renamed it.

**Comment by Kazark** [comment]
Okay, it's really not about the name being `sysarch.png`. I definitely open others files without that name, and it happens. But if I move the directory somewhere else, it does not happen. Exceedingly bizarre.

**Comment by Kazark** [comment]
https://user-images.githubusercontent.com/3661051/179760398-db3bc6ec-f3ff-4219-a907-b43439a90f05.mov

**Comment by lebensterben** [comment]
use stable emacs

**Comment by Kazark** [comment]
That's a good idea. Magit forced me to upgrade a version; the compat stuff wasn't working right for me. I also wanted to keep `native-comp` working. I'm on a Mac for this and it's a little hard to get Emacs working sometimes, particularly with those extra strictures. But you may have a good point there, thanks.

**Comment by Kazark** [comment]
Evidently this is a Heisenbug.
