### ISSUE TITLE
`vim-powerline` startup error

### ISSUE THREAD

**Issue by caiquefigueiredo** [syl20bnr/spacemacs#15654]
#### Description :octocat:
After updating emacs to the latest development branch, I was getting the following error on every startup:
```
(Spacemacs) --> installing package: vim-powerline@spacemacs-modeline... [1/1]
Fetcher: file
Source: nil

/Users/haru/.emacs.d/.cache/quelpa/build/vim-powerline/vim-colors.el -> /var/folders/ts/5p4gxt6941q3mbmflmmrqm2w0000gn/T/vim-powerlineA7SmZK/vim-powerline-20220721.194245/vim-colors.el
/Users/haru/.emacs.d/.cache/quelpa/build/vim-powerline/vim-powerline-theme.el -> /var/folders/ts/5p4gxt6941q3mbmflmmrqm2w0000gn/T/vim-powerlineA7SmZK/vim-powerline-20220721.194245/vim-powerline-theme.el
Error getting PACKAGE-DESC: (file-missing Opening input file No such file or directory /Users/haru/.emacs.d/.cache/quelpa/packages/vim-powerline-20220721.194245.tar)
(Spacemacs) Error: 
An error occurred while installing vim-powerline (error: (wrong-type-argument package-desc nil))
```

#### Reproduction guide :beetle:
- Start Emacs with latest develop release

*Observed behaviour:* :eyes: :broken_heart:
Emacs starts and is otherwise functional

*Expected behaviour:* :heart: :smile:
Emacs starts without errors

#### System Info :computer:
- OS: darwin
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: fix-vim-powerline (rev. baf1256b0)
- Graphic display: nil
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 (c-c++ :variables c-c++-backend 'lsp-clangd)
 (clojure :variables clojure-backend 'cider clojure-enable-clj-refactor t clojure-enable-linters
          '(clj-kondo joker)
          clojure-indent-style 'always-indent)
 coffeescript
 (colors :variables colors-enable-nyan-cat-progress-bar nil colors-colorize-identifiers nil)
 command-log d
 (dhall :variables dhall-format-at-save nil dhall-use-header-line nil dhall-command nil)
 (docker :variables docker-dockerfile-backend 'lsp)
 emacs-lisp emoji git
 (go :variables go-tab-width 2 go-backend 'lsp)
 (haskell :variables haskell-completion-backend 'lsp)
 helm html
 (java :variables java-backend 'lsp)
 javascript
 (json :variabels json-backend nil)
 (lsp :variables lsp-enable-file-watchers t lsp-file-watch-threshold 10000 lsp-log-io t)
 markdown multiple-cursors
 (osx :variables osx-right-command-as 'super)
 pass pdf perl5 python racket
 (ruby :variables ruby-backend 'nil)
 rust
 (scala :variables scala-backend 'scala-metals)
 (scheme :variables scheme-implementations
         '(guile racket))
 (shell :variables shell-default-shell 'vterm shell-default-term-shell "zsh" vterm-clear-scrollback-when-clearing t)
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak)
 (sql :variables sql-backend 'lsp sql-capitalize-keywords t)
 syntax-checking
 (terraform :variables terraform-backend 'lsp)
 themes-megapack
 (treemacs :variables treemacs-use-scope-type 'Perspectives)
 unicode-fonts
 (version-control :variables version-control-diff-side 'left)
 xclipboard yaml
 (zig :variables zls-backend 'lsp))
```
- System configuration features: ACL GLIB GMP GNUTLS JPEG JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS ZLIB

**Comment by lebensterben** [comment]
you're on the wrong branch.

**Comment by caiquefigueiredo** [comment]
Reported the issue in the PRs branch by mistake. This happened on `develop`

**Comment by lebensterben** [comment]
try clearing ~/.emacs.d/.cache/quelpa/packages first.

**Comment by caiquefigueiredo** [comment]
Same error. I did clear the entire `~/.emacs.d/.cache` before trying syl20bnr/spacemacs#15653. Would that have unwanted side-effects?

**Comment by lebensterben** [comment]
try a fresh install then...

**Comment by caiquefigueiredo** [comment]
Took a while, but same error. If I'm the only one facing this issue, I'm cool with closing it. I'll just keep my build with my fork.

**Comment by caiquefigueiredo** [comment]
Although this was from a clean `develop` (not counting my `.spacemacs`)

**Comment by lebensterben** [comment]
Note that your changes are erroneous....

**Comment by caiquefigueiredo** [comment]
Maybe worth nothing: the error only showed up after restarting emacs. During the reinstall, everything was ok. But after I've closed emacs and reopened it, the error showed up.

**Comment by caiquefigueiredo** [comment]
> Note that your changes are erroneous....

In the sense it breaks? I took that fix out of code I've seen around the repo. Such as this [one](https://github.com/syl20bnr/spacemacs/blob/c49e80d7946a6fac0b802ad93c1134cdeabcf74f/layers/%2Bcompletion/ivy/packages.el#L42)

**Comment by lebensterben** [comment]
🧐

**Comment by caiquefigueiredo** [comment]
There might be something a little deeper at play here. Using a clean `develop` branch, I'm now getting the following:
```
(Spacemacs) --> installing package: zonokai-emacs@themes-megapack... [1/2]
Fetcher: github
Source: ZehCnaS34/zonokai-emacs

Updating /Users/haru/.emacs.d/.cache/quelpa/build/zonokai-emacs/
/Users/haru/.emacs.d/.cache/quelpa/build/zonokai-emacs/zonokai-blue-theme.el -> /var/folders/ts/5p4gxt6941q3mbmflmmrqm2w0000gn/T/zonokai-emacsI6O7tw/zonokai-emacs-20160321.2325/zonokai-blue-theme.el
/Users/haru/.emacs.d/.cache/quelpa/build/zonokai-emacs/zonokai-red-theme.el -> /var/folders/ts/5p4gxt6941q3mbmflmmrqm2w0000gn/T/zonokai-emacsI6O7tw/zonokai-emacs-20160321.2325/zonokai-red-theme.el
/Users/haru/.emacs.d/.cache/quelpa/build/zonokai-emacs/zonokai-theme.el -> /var/folders/ts/5p4gxt6941q3mbmflmmrqm2w0000gn/T/zonokai-emacsI6O7tw/zonokai-emacs-20160321.2325/zonokai-theme.el
/Users/haru/.emacs.d/.cache/quelpa/build/zonokai-emacs/zonokai.el -> /var/folders/ts/5p4gxt6941q3mbmflmmrqm2w0000gn/T/zonokai-emacsI6O7tw/zonokai-emacs-20160321.2325/zonokai.el
Error getting PACKAGE-DESC: (file-missing Opening input file No such file or directory /Users/haru/.emacs.d/.cache/quelpa/packages/zonokai-emacs-20160321.2325.tar)
(Spacemacs) Error: 
An error occurred while installing zonokai-emacs (error: (wrong-type-argument package-desc nil))

(Spacemacs) --> installing package: vim-powerline@spacemacs-modeline... [2/2]
Fetcher: file
Source: nil

/Users/haru/.emacs.d/.cache/quelpa/build/vim-powerline/vim-colors.el -> /var/folders/ts/5p4gxt6941q3mbmflmmrqm2w0000gn/T/vim-powerlineKRATVB/vim-powerline-20220721.205145/vim-colors.el
/Users/haru/.emacs.d/.cache/quelpa/build/vim-powerline/vim-powerline-theme.el -> /var/folders/ts/5p4gxt6941q3mbmflmmrqm2w0000gn/T/vim-powerlineKRATVB/vim-powerline-20220721.205145/vim-powerline-theme.el
Error getting PACKAGE-DESC: (file-missing Opening input file No such file or directory /Users/haru/.emacs.d/.cache/quelpa/packages/vim-powerline-20220721.205145.tar)
(Spacemacs) Error: 
An error occurred while installing vim-powerline (error: (wrong-type-argument package-desc nil))
```
Basically the same error, but with the `github` fetcher involving `ZehCnaS34/zonokai-emacs`

**Comment by lebensterben** [comment]
Rather strange.

**Comment by lebensterben** [comment]
@caiquefigueiredo 

What do you get from `tar --show-defaults`

**Comment by lebensterben** [comment]
please install gnu tar and retry.

**Comment by humorForus** [comment]
The same error, it seems cannot get package from github.

**Comment by prepor** [comment]
the same error for me

**Comment by caiquefigueiredo** [comment]
Indeed. Adding `gnutar` from `nixpgks` into my home-manager setup made it work 🎉 
Thanks for the help, @lebensterben

**Comment by lebensterben** [comment]
@prepor @humorForus 

Are you running bugOS? Try to install gnu tar and retry.

**Comment by ograycode** [comment]
I had the same issue, `brew install gnu-tar` solved it for me. Thanks.

**Comment by lebensterben** [comment]
Although installing `gnu-tar` fixes the issue, it turns out that I made a mistake in a recent commit.

The latest commit should have fixed it without requiring of `gnu-tar` on macOS or Windows.

**Comment by mirkov** [comment]
I just recently experienced the same problem on macOS, and installing `gnu-tar` fixed it. Here are the details as best I recall (I was not taking notes).

**Started with Emacs 28.1** where I don't recall having the error.

**Updated Emacs to 28.2 and got errors**. Here are snippets from the `*Messages*` buffer:

```
Error getting PACKAGE-DESC: (wrong-type-argument stringp nil)
(Spacemacs) Error:
An error occurred while installing vim-powerline (error: (wrong-type-argument package-desc nil))
...
Error getting PACKAGE-DESC: (wrong-type-argument stringp nil)
(Spacemacs) Error:
An error occurred while installing inspector (error: (wrong-type-argument package-desc nil))
```
**Updated Spacemacs/develop to `913962b3e`**, restarted, and had the same errors.

**Installed `gnu-tar`** and Spacemacs _started cleanly_, no errors in ~*Messages*~ buffer.

**Comment by Prometheus77** [comment]
I'm on Windows and am having this same issue with a fresh install of emacs 28.1, Spacemacs develop branch (commit f1c7979b6). But I can't figure out how to install gnu-tar on Windows.

**Comment by lebensterben** [comment]
> I'm on Windows and am having this same issue with a fresh install of emacs 28.1, Spacemacs develop branch (commit f1c7979b6). But I can't figure out how to install gnu-tar on Windows.

There is a section in readme about installing GNU tar on Windows via scoop.sh

**Comment by adeltby** [comment]
I had the same issue on MacOS and `brew install gnu-tar` solved that.
