### ISSUE TITLE
Disable lsp-mode under certain conditions

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#15668]
I am often using `poly-mode` to work with markdown documents that contain code chunks. The issue is that `lsp-mode` breaks `poly-mode` hard so that it is unusable. Is there a way to prevent `lsp-mode` from loading if `poly-mode` is detected as a minor-mode?

https://github.com/polymode/polymode/issues/316

**Comment by lebensterben** [comment]
@gdkrmr 

Note that we don't have poly-mode in Spacemacs. So it's up to either lsp-mode or poly-mode to fix the issue.

But I'm willing to accept PR that add poly-mode to Spacemacs, as long as it doesn't have issue with evil-mode. (It was mentioned in #5126 but probably not applicable now.)
