### ISSUE TITLE
LSP documentation minibuffer: recurrent error message term-cursor--immediate

### ISSUE THREAD

**Issue by pradyparanjpe** [syl20bnr/spacemacs#15667]
##### Python mode
      Following error is thrown continuously, this causes emacs to hang.
      ```
      Error processing message (wrong-number-of-arguments #<subr term-cursor--immediate> 2). [14 times]
      ```

#### Reproduction guide :beetle:
- Start Emacs
- Python settings:
  ```elisp
  (python :variables
          python-backend 'lsp
          python-lsp-server 'pyright
          python-test-runner 'pytest
          python-formatter 'yapf
          python-format-on-save t
          python-sort-imports-on-save t)
  ```
- Open a python-script.py
- Hover on a symbol (function/class) in anticipation of lsp-ui-doc minibuffer

*Observed behaviour:* :eyes: :broken_heart:
- Emacs Frequently Hangs, seriously affecting productivity.
- **I had to switch to vim!**

*Expected behaviour:* :heart: :smile:
- Shouldn't throw error

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 13cb1e0f1)
- Graphic display: t
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((mu4e :variables mu4e t mu4e-installation-path "/usr/share/emacs/site-lisp" mu4e-account-alist t mu4e-enable-notifications t mu4e-enable-mode-lineu4e-enable-mode-line t)
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 pass
 (org :variables org-directory
      (expand-file-name "org/"
                        (or
                         (getenv "XDG_DATA_HOME")
                         "~/.local/share"))
      org-capture-templates
      `(("m" "Email Workflow")
        ("mf" "Follow up" entry
         (file+olp ,(expand-file-name "Mail.org" org-directory)
                   "Follow up")
         "* TODO: Follow up with %:fromname on %:subject\n  %a\n  %i" :immediate-finish t)
        ("mr" "Read later" entry
         (file+olp ,(expand-file-name "Mail.org" org-directory)
                   "Read later")
         "* TODO: Read %:subject sent on %:date\n  %a\n  %i" :immediate-finish t))
      org-enable-appear-support t org-enable-github-support t org-enable-notifications t org-enable-org-journal-support t org-enable-reveal-js-support t org-enable-roam-protocol t org-enable-roam-support t org-journal-dir
      (expand-file-name "org/journal/"
                        (or
                         (getenv "XDG_DATA_HOME")
                         "~/.local/share/"))
      org-journal-file-format "%Y-%m-%d" org-mime-export-options
      '(:section-numbers nil :with-author nil :with-toc nil)
      org-projectile-file "plan.org" org-start-notification-daemon-on-startup t :packages
      (not org-roam))
 (git :variables git-enable-magit-delta-plugin t git-enable-magit-todos-plugin t git-enable-magit-gitflow-plugin t)
 finance
 (spell-checking :variables spell-checking-enable-by-default t)
 spacemacs-defaults
 (shell :variables shell-default-height 40 close-window-with-terminal t shell-default-position 'bottom)
 helpful better-defaults
 (treemacs :variables treemacs-use-git-mode 'extended treemacs-use-all-the-icons-theme t)
 (exwm :variables exwm-enable-systray t exwm-autostart-xdg-applications t exwm-terminal-command "foot" exwm-locking-command nil exwm-hide-tiling-modeline nil exwm-workspace-switch-wrap t exwm-randr-command nil)
 eww
 (unicode-fonts :variables unicode-fonts-enable-ligatures nil)
 theming emoji colors
 (auto-completion :variables auto-completion-use-company-box t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t company-emoji-insert-unicode nil)
 yaml systemd nginx sphinx restructuredtext pandoc mermaid markdown html csv vimscript
 (shell-scripts :variables shell-scripts-backend 'lsp)
 rust php
 (python :variables python-backend 'lsp python-lsp-server 'pyright python-test-runner 'pytest python-formatter 'yapf python-format-on-save t python-sort-imports-on-save t)
 (lsp :variables lsp-lens-enable t lsp-use-lsp-ui t lsp-ui-doc-show-with-cursor t)
 kivy javascript
 (ess :variables ess-r-backend 'lsp ess-assign-key "\255")
 c-c++ lua emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM XWIDGETS GTK3 ZLIB

#### Backtrace :paw_prints:
```

```

**Comment by lebensterben** [comment]
Cannot reproduce.

**Comment by pradyparanjpe** [comment]
# Addition:
(Correction)

The error is thrown upon hovering on a variable. (May be while its docstring is being sought.)
The documentation sub-window doesn't appear.

This has started happening since I upgraded to emacs v 28.1.

**Comment by pradyparanjpe** [comment]
# General issue

This appears  to be a general issue with display of docstrings;
since the same error message appears with R (ess-r-mode) and bash scripts (shell-script-mode) while hovering over documented symbols.

# lsp configuration:
```elisp
     (lsp :variables
          lsp-lens-enable t
          lsp-use-lsp-ui t
          lsp-ui-doc-show-with-cursor t)
```

**Comment by lebensterben** [comment]
Not reproducible.

**Comment by lebensterben** [comment]
You have not mentioned that you are running emacs in a daemon.

I tried it nevertheless and still the problem cannot be reproduced.

Note that `term-cursor` mode is loaded on when you there's no graphical system. So I also tried daemon + terminal Emacs. Still not reproducible.

**Comment by psisis** [comment]
Strange. I got this error just a few hours ago when I noticed lsp getting nonresponsive and a symbol was kept selected after moving the cursor away.

The only change I did was in layers
`html`
to
`(html :variable css-enable-lsp t less-enable-lsp t scss-enable-lsp t html-enable-lsp t web-fmt-tool 'web-beautify)`
Disabling term-cursor-mode made the issue go away. Those layer variables set global-term-cursor-mode to 1.

**Comment by pradyparanjpe** [comment]
## Narrowed down
### As you said,
  - I too don't get the error running emacs without daemon. *(I plan to work this way till the problem is resolved)*
  - Running daemon and connecting a cli client too, doesn't throw this error.

### But,
  - The error is thrown when I start daemon and connect a **graphical client** to it.
  - I have been launching emacsclient by the following command:
```sh
emacsclient -c -a=""
```

## System info
Apology for not having mentioned that I am running emacs in a daemon. Following is my system info.

System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. https://github.com/syl20bnr/spacemacs/commit/13cb1e0f12379909c8291dada6a5684b6eb65180)
- Graphic display: t
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Window manager: Sway (Wayland: XWayland)
- OS: Fedora 36

# Not immediately actionable.
I plan not to use the graphical daemon mode. So you may mark this issue and close it as *not-planned*.

**Comment by lebensterben** [comment]
I will check html layer.

**Comment by psisis** [comment]
Maybe I was wrong about the html layer, it doesn't make sense for it to affect any cursors.

Another layer I added recently, but not sure if it was days ago or yesterday, was `spacemacs-editing-visual` which has this in packages.el:

`(term-cursor :location (recipe :fetcher github :repo "h0d/term-cursor.el"))`

**Comment by lebensterben** [comment]
term-cursor is only turned on in terminal. It is installed by default unless you use spacemacs-base.

**Comment by psisis** [comment]
Alright, I admit I'm not knowledgable enough. All I know is that it's loaded at GUI start `Loading term-cursor (native compiled elisp)...done` and when I checked customize, it said `global-term-cursor-mode` was changed outside customize. What I don't know is whether it was always enabled and just the error is recent, but I haven't upgraded any packages in a while.

**Comment by lebensterben** [comment]
@psisis 

https://github.com/syl20bnr/spacemacs/blob/ba33309327e278a5fe7c12e095ed3a314523484f/layers/%2Bspacemacs/spacemacs-editing-visual/packages.el#L160

Impossible. It never loads in GUI Emacs.

**Comment by psisis** [comment]
Well I don't know. That layer, by rgrep, is the only one that uses package `term-cursor`. Commenting out that func in packages.el will uninstall term-cursor. Even disabling the layer but keeping the files original, will insist on installing (and for me) loading it.

I just saw that it's a recent commit, made by you. I did git pull a few days ago, so it must be responsible.

**Comment by psisis** [comment]
Checking out the layer pre-commit will uninstall `term-cursor`, install `evil-terminal-cursor-changer` and solve this specific issue.

**Comment by lebensterben** [comment]
@psisis 

deleting that line won't uninstall it. It just never gets loaded.

removing spacemaca-editing won't have any effect unless you use spacemacs-base as I explained before.

So there's no bug.

**Comment by psisis** [comment]
> @psisis
> 
> deleting that line won't uninstall it. It just never gets loaded.
> 
> removing spacemaca-editing won't have any effect unless you use spacemacs-base as I explained before.
> 
> So there's no bug.

What are you talking about. I just said that undoing your commits from 17 days ago will solve this issue.

**Comment by lebensterben** [comment]
@psisis 

> Commenting out that func in packages.el will uninstall term-cursor. Even disabling the layer but keeping the files original, will insist on installing (and for me) loading it.

These two sentences are both false.

**Comment by psisis** [comment]
You want me to screenshare?

**Comment by psisis** [comment]
Fact A: your commit caused this. What more is there to say.

**Comment by psisis** [comment]
@pradyparanjpe 

If you want a solution. Cd to .emacs.d and run `git checkout 77ba076f697d270b011586944004ce8dfb6f61a4 -- .\layers\+spacemacs\spacemacs-editing-visual\*` in shell.

**Comment by lebensterben** [comment]
@psisis  I cannot reproduce this issue.

**Comment by psisis** [comment]
@lebensterben I know, you've stated that already. That doesn't mean your commit is blameless. If OP didn't have the same issue I wouldn't have known this, but your arrogance really astounds me.

Let's wait for OP, if checking out pre-commit will solve it for him then at the very least I'll always know to check your commits next time I get a bug.

**Comment by lebensterben** [comment]
Read that commit carefully, you will see the only change is that term-cursor would not be installed if you use evil, but after the commit it's always installed.

Installing the package won't get it loaded automatically. It takes two more steps to have it loaded.

First it must be declared in a layer's xxx-packages list and that layer must be enabled. In this case it's in spacemaca-editing-packages, and spacemaca-editing layer is always enabled unless you use spacemacs-base which requires manual enabling.

Second there must be a package init function, in which the package is loaded via a use-package call. And in this case the `:if` argument makes sure it won't be loaded in GUI Emacs.

Why do you say I am arrogant? I'm walking over these facts again and again with you without making any judgement on you.

**Comment by lebensterben** [comment]
Also note that reverting that commit IS NOT A FIX, it's not even a workaround.

term-cursor would still be installed for non-evil users.

**Comment by psisis** [comment]
So if I understand this correctly. There are two commits, d48bc8d90bb834fee2140499fee3b3f43f170320 and 99933b1fb37a51a41656a6c3d8cdbdbb02449bfc. Before these we had

```
(term-cursor :location (recipe :fetcher github :repo "h0d/term-cursor.el")
                  :toggle (not (configuration-layer/package-used-p 'evil)))
```
now we have 

```(term-cursor :location (recipe :fetcher github :repo "h0d/term-cursor.el"))```

There is no toggle anymore to install the package (since I used evil, it wouldn't install before). Meaning it will always be installed now but not necessarily loaded. So the main issue is, why is it loaded.

Since `spacemacs-editing-visual/init-term-cursor` wasn't changed at all, the problem is not here (it probably would have thrown an error if package was not found). Something else is loading term-cursor. I even added `(setq graphicp (display-graphic-p))` to that func to debug, and it was accurately `t`.

The only files I have that ever mention the phrase "term-cursor" are:

"term-cursor/*" , "spacemacs-editing-visual/packages.el" and dotspacemacs/custom-settings/`'(package-selected-packages ...term-cursor)`

Nothing else in .emacs.d/ I have wants to remotely enable term-cursor. I even searched for non-.el files.

This is the only information I can give to this issue. I don't know what's responsible, but when editing-visual installs term-cursor, it gets loaded for me. I think you're arrogant because even if you didn't mean for it to be loaded your commit was a big change for evil users and highly relevant and you could have mentioned it.

**Comment by psisis** [comment]
> @psisis
> 
> > Commenting out that func in packages.el will uninstall term-cursor. Even disabling the layer but keeping the files original, will insist on installing (and for me) loading it.
> 
> These two sentences are both false.

How are they false. So you think I'm lying. In the second sentence I stated (for me). In the first I said commenting out use-package will uninstall it, which it still does. This is arrogance.

```
(Spacemacs) Warning: package term-cursor not initialized in layer spacemacs-editing-visual, you may consider removing this package from the package list or use the :toggle keyword instead of a `when' form.
(Spacemacs) --> deleting term-cursor... [1/1]
Package ‘term-cursor-20190515.41’ deleted.
```

**Comment by pradyparanjpe** [comment]
> @pradyparanjpe
> 
> If you want a solution. Cd to .emacs.d and run `git checkout 77ba076f697d270b011586944004ce8dfb6f61a4 -- .\layers\+spacemacs\spacemacs-editing-visual\*` in shell.

@psisis, 

## I may be late
I'm travelling to my hometown this weekend, so I'll be on and off my computer(s) sporadically. I'll try that solution and get back as soon as I can.

Thanks for the prospective solution. :thumbsup:

## I'm Irritated

By the attitude.
(And that's a parliamentary word)

While in my hometown, I'll evaluate a prospective switch to doom-emacs, crafted-emacs or even vanila-emacs. But even if I do switch, I'll try your solution and confirm if it solves the problem.

**Comment by pradyparanjpe** [comment]
> @pradyparanjpe
> 
> If you want a solution. Cd to .emacs.d and run `git checkout 77ba076f697d270b011586944004ce8dfb6f61a4 -- .\layers\+spacemacs\spacemacs-editing-visual\*` in shell.

:+1:

## Verified the workaround solution
I could reproduce that.
- This stops throwing the issue.

## Close
I'm closing the issue, If anyone wants to repoen it, they are welcome; I am dropping out from the discussion.

**Comment by jpathy** [comment]
This issue is still present, should be reproducible with daemon + gui frame(i use `pgtk`). I changed the condition to `(unless (or (daemonp) (display-graphic-p)) (global-term-cursor-mode))` as a workaround.

As to why: See: https://stackoverflow.com/a/5801740 . `display-graphics-p` is `nil` in daemon mode, so checking that alone is not ideal.

**Comment by real-or-random** [comment]
> This issue is still present, should be reproducible with daemon + gui frame(i use `pgtk`). 

I can confirm this. A more user-friendly workaround is to add `term-cursor` to `dotspacemacs-excluded-packages`.

Wouldn't be a proper fix be to change `term-cursor` such that it is only active in GUI frames?

By the way, this issue me figure out that my spacemacs is so much snappier after disabling `term-cursor-mode` (also in GUI, where the mode was active but not effective). Maybe it's just my config, but if others have the same experience, it could make sense to get rid of it entirely.

**Comment by viviicat** [comment]
I also have this issue. Seems the fix that StreakyCobra has done in their fork might be a good way to resolve the issue. Though, for now I may blacklist term-cursor as that seems the simplest fix.

**Comment by chaos95** [comment]
I have been having this issue with LSP lens in rust-mode (running 29.0.91 daemon + gui frame on darwin); I can confirm that applying the change from StreakyCobra's fork has fixed it.

**Comment by niklas** [comment]
I have been having that issue too (only in client mode), in particular purescript lsp-ui-doc not showing up the popup window, but showing the above error message.
Adding `term-cursor` to the `dotspacemacs-excluded-packages` fixes that for me.

**Comment by xu-shawn** [comment]
Got the same error, freezes emacs on daemon mode

**Comment by fnussbaum** [comment]
I've also added term-cursor to excluded packages a long time ago, but I think it would be nice to fix this, and in particular have term-cursor-mode disabled by default if there is no terminal frame. I'm working on it.
