### ISSUE TITLE
[xclipboard] add support for wl-copy/wl-paste

### ISSUE THREAD

**Issue by epsilon-0** [syl20bnr/spacemacs#15664]
xclipboard layer doesn't have support for wayland, which has wl-copy/wl-paste as the most widely used clipboard tools for the command line.

**Comment by lebensterben** [comment]
it shouldn't support Wayland. xclipboard requires X.

**Comment by epsilon-0** [comment]
Obviously not, it also supports windows and macos. There's no reason why it shouldn't be able to support wayland.

**Comment by lebensterben** [comment]
Good point. Windows and macOS support should be removed from xclipboard layer.

**Comment by lebensterben** [comment]
workaround: https://www.emacswiki.org/emacs/CopyAndPaste#h5o-4

**Comment by lebensterben** [comment]
- Note that you don't need xclipboard layer for X. It simply works out-of-box.
- You do need the workaround for Wayland. But this should not be in xclipboard layer. If it's added to Spacemacs, it should be added in `spacemacs-editing` layer.
- Support for macOS and Windows has nothing to do with X Clipboard so this layer is confusing.
