### ISSUE TITLE
Problem with dap-mode (ptvsd)

### ISSUE THREAD

**Issue by josearivar** [syl20bnr/spacemacs#15670]
So, I've been trying to setup dap-mode to work for a few days and I keep getting this error whenever I have a breakpoint in my Python code:
![2022-07-29_12-50](https://user-images.githubusercontent.com/109873936/181797155-4d5ea2da-c644-408c-8c46-e035b12c234f.png)

Without the break point it works fine:
![2022-07-29_12-50_1](https://user-images.githubusercontent.com/109873936/181797214-a4cd06d9-ecf5-4521-8074-e79db47d65f1.png)

What is curious is that despite the error, it execute the whole code, even what is after the breakpoint.

Here is my config:
```
dotspacemacs-configuration-layers
   '(rust
     themes-megapack
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press `SPC f e R' (Vim style) or
     ;; `M-m f e R' (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     ;; auto-completion
     ;; better-defaults
     emacs-lisp
     git
     helm
     lsp
     dap
     ;; markdown
     multiple-cursors
     ;; org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     syntax-checking
     version-control
     treemacs
     debug
     (python :variables
             python-backend 'lsp
             python-lsp-server 'pyright
             python-formatter 'black
             python-format-on-save t
             python-sort-imports-on-save t
             python-pipenv-activate t
             python-fill-column 99
             python-test-runner 'pytest)
     )
```

I've tried with Poetry instead of pipenv and had the same error. Is there a way to use debugpy instead of ptvsd?

Thanks

**Comment by lebensterben** [comment]
this doesn't seem like a Spacesmacs issue.

**Comment by josearivar** [comment]
the problem only appears when I set a breakpoint on the code in spacemacs.

**Comment by lebensterben** [comment]
you need to follow the issue template.

**Comment by josearivar** [comment]
Ok, i've subtmitted a new one with the correct template:
https://github.com/syl20bnr/spacemacs/issues/15671
is there a way to delete this one or should I just close it?
