### ISSUE TITLE
Package started uninstalling

### ISSUE THREAD

**Issue by mkcode** [syl20bnr/spacemacs#1567]
Commit https://github.com/syl20bnr/spacemacs/commit/56a0a9437735edf0a16235ddeafecd7353265efe introduces a change that uninstalls dash-at-point, from the dash package.  

`develop` up to commit https://github.com/syl20bnr/spacemacs/commit/07e246586867b1a7ccd3b854e85699a0cfc688be does not change anything.

To reproduce:

 * add dash to `dotspacemacs-configuration-layers`
 * `git checkout 07e246586867`
 * Open emacs. package will  install
 * Close emacs
 * `git checkout 56a0a9437735ed`
 * Open emacs. Package will uninstall.

@syl20bnr - could you let me know if this is the desired behavior and if I should change some part of the dash package? - https://github.com/syl20bnr/spacemacs/tree/develop/contrib/tools/dash

**Comment by mkcode** [comment]
```
(Spacemacs) Warning: Duplicated layer detected: dash! Keeping only the layer in directory /Users/chris/.emacs.d/contrib/
```

does appear in the log in https://github.com/syl20bnr/spacemacs/commit/56a0a9437735edf0a16235ddeafecd7353265efe

**Comment by mkcode** [comment]
Ah - it's probably b/c of a naming conflict between the elpa dash package and the dash configuration layer.

@syl20bnr - looks like changing the name of the dash configuration layer will fix this. Please advise.

**Comment by syl20bnr** [comment]
Check again the warning message with last develop, I improved it to tell where is the duplicated layer.

**Comment by mkcode** [comment]
New warning message:
```
(Spacemacs) Warning: Duplicated layer dash detected in directory "/Users/chris/.emacs.d/contrib/tools/", keeping only the layer in directory "/Users/chris/.emacs.d/contrib/"
```

Ok! So for some reason the 'dash' dir that was in contrib did not not get deleted when I moved from master to develop branch. I deleted it from contrib and now it's working well.

Thanks @syl20bnr

**Comment by mkcode** [comment]
The 'dash' dir in contrib was empty...so it looks like git removed the contents but not the dir itself...which is also why it didn't show up as modified in `git status`.
