### ISSUE TITLE
Problem with dap-mode - Python + ptvsd

### ISSUE THREAD

**Issue by josearivar** [syl20bnr/spacemacs#15671]
#### Description :octocat:
ptvsd gives an error whenever there is a breakpoint in the Python code. Works fine without the breakpoint.
Is there a way to fix it or to use debugpy instead?

#### Reproduction guide :beetle:
- Start Emacs
- Open python project with environment activated on pipenv (needs to have packages: python-lsp-server ptvsd pytest)
- set a breakpoint on the python code (SPC d b a)
- Open python console (C-c C-p)
- Debug file (SPC d d d)

*Observed behaviour:* :eyes: :broken_heart:
ptvsd ignores the breakpoint and shows an error unrelated to the code. Works fine if no breakpoint is set.

![2022-07-29_12-50](https://user-images.githubusercontent.com/109873936/181811791-5a4cbab3-a16f-4294-98a6-39070789a0c5.png)
![2022-07-29_12-50_1](https://user-images.githubusercontent.com/109873936/181811830-c4dd2cb7-84fb-4fc6-8304-9990377e5757.png)

*Expected behaviour:* :heart: :smile:
ptvsd stops at the breakpoint for debugging.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 13cb1e0f1)
- Graphic display: t
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(rust themes-megapack emacs-lisp git helm lsp dap multiple-cursors syntax-checking version-control treemacs debug
      (python :variables python-backend 'lsp python-lsp-server 'pyright python-formatter 'black python-format-on-save t python-sort-imports-on-save t python-pipenv-activate t python-fill-column 99 python-test-runner 'pytest))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by josearivar** [comment]
I still couldn’t figure out how to fix it on spacemacs, but I tried using doom emacs and it worked, so I am really convinced that it is some problem with spacemacs here.

**Comment by lebensterben** [comment]
You gotta improve the reproduction guide section.

- You claim that `python-lsp-server` is needed. But both the UI and your config shows that you're using pyright.
- After `SPC d d d` you gotta choose a debugger config, what is it?

**Comment by josearivar** [comment]
Sorry, I thought that python-lsp-server was also a requirement to use pyright, could that be the cause?
After  SPC d d d you can choose "run file" to get the error above.

**Comment by lebensterben** [comment]
python-lsp-server has nothing to do with pyright.

Also, you need to provide the FULL steps to use pipenv.
