### ISSUE TITLE
Emacs startup fails due to unkown function unicode-fonts//setup-fonts

### ISSUE THREAD

**Issue by kassick** [syl20bnr/spacemacs#15681]
#### Description :octocat:

Emacs startup fails with undefined symbol unicode-fonts//setup-fonts
This bug was introduced in commit 37bad602e21eff3cfd02ab79b31355c9eb588495

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Emacs opens the messages buffer with an error complaining about the missing function

*Expected behaviour:* :heart: :smile:
Emacs starts without errors

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1.90
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 7d60d894a)
- Graphic display: t
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv html
     (unicode-fonts :variables unicode-fonts-enable-ligatures t)
     (ibuffer :variables ibuffer-group-buffers-by 'projects)
     nav-flash theming helm
     (auto-completion :variables auto-completion-front-end 'company auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip nil auto-completion-use-company-posframe t)
     multiple-cursors
     (git :variables git-enable-magit-gitflow-plugin t magit-bury-buffer-function 'magit-mode-quit-window)
     (version-control :variables version-control-diff-tool 'git-gutter version-control-global-margin nil version-control-diff-side 'left)
     (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t)
     dtrt-indent
     (lsp :variables lsp-keymap-prefix "C-c C-l" lsp-ui-doc-enable nil lsp-ui-doc-position 'at-point lsp-ui-doc-max-height 15 lsp-use-upstream-bindings nil)
     emacs-lisp shell-scripts
     (python :variables lsp-pyright-venv-path "/home/kassick/.pyenv/versions" python-auto-set-local-pyenv-version nil python-test-runner 'pytest python-backend 'lsp python-lsp-server 'pyright python-spacemacs-indent-guess nil python-formatter 'yapf)
     rust
     (c-c++ :variables c-c++-backend 'lsp-clangd)
     cmake javascript
     (typescript)
     (groovy :variables groovy-lsp-jar-path "/home/kassick/Sources/user/groovy-language-server/build/libs/groovy-language-server-all.jar")
     terraform yaml
     (markdown :variables markdown-live-preview-engine 'vmd)
     org
     (latex :variables latex-enable-folding t latex-enable-auto-fill nil)
     (bibtex)
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     kzk-general kzk-evil kzk-window-management kzk-projectile kzk-code-tweaks kzk-mc kzk-embrace kzk-magit kzk-org kzk-lsp kzk-makefile kzk-python kzk-ahs kzk-visual-editing kzk-helm kzk-company kzk-persp spacemacs-editing)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ IMAGEMAGICK JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM XWIDGETS GTK3 ZLIB

**Comment by lebensterben** [comment]
sorry for the inconveniences...

I accidentally pushed a that line while not pushing the function... you can find it here https://github.com/rolandwalker/unicode-fonts/issues/3#issuecomment-1205911213

I will add it once I get home.

**Comment by lebensterben** [comment]
It should be fixed in https://github.com/syl20bnr/spacemacs/commit/4f6413e82ff9778e7ac1e85ece6b3218f0c888e4
