### ISSUE TITLE
clojure layer "," key now just says "no previous search" rather then giving me more options like "cider-jack-in"

### ISSUE THREAD

**Issue by drewverlee** [syl20bnr/spacemacs#15683]
#### Description :octocat:

clojure layer "," key now just says "no previous search" rather then giving me more options like "cider-jack-in"

#### Reproduction guide :beetle:
- Start Emacs
- Load .clj file
- press ','

*Observed behaviour:* :eyes: :broken_heart:

mini buffers says "no previous search"

*Expected behaviour:* :heart: :smile:

mini buffer should say "," followed by other keys like listed here https://develop.spacemacs.org/layers/+lang/clojure/README.html#starting-a-repl-from-spacemacs

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 7d60d894a)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
if it happens recently, then mostly likely a recent commit break it.

**Comment by drewverlee** [comment]
I'm not able to reproduce this on a friends dotfile setup, so even though i don't see the issue there it's probably on my end...

**Comment by lebensterben** [comment]
If you friend is running on latest develop and everything is fine, then it's likely problem on your config.

**Comment by drewverlee** [comment]
yep, the issue was my config. I had removed a letter so none of the layers loaded. Sorry about the noise!
