### ISSUE TITLE
daemon font size bug re-appears

### ISSUE THREAD

**Issue by winsphinx** [syl20bnr/spacemacs#15689]
After commit 4f6413e82ff9778e7ac1e85ece6b3218f0c888e4, the issue #15295 re-appears.

**Comment by lebensterben** [comment]
@winsphinx 

Cannot reproduce it...

Try restart Emacs.

**Comment by winsphinx** [comment]
I tested on 2 PCs, both appear.
and I git reset back to the before commits, start Emacs and exit it, then git pull to the latest, start Emacs once more, the bug disappears.
I dont know why, but it's now OK.

**Comment by lebensterben** [comment]
@winsphinx 

Before ths commit, when your system's font has changed, Emacs will update Unicode font block mapping when Emacs starts. But it doesn't happen when Emacs is running in daemon.

This commit let Emacs update the font blocks also in daemon. This is the only change.

When you found the issue with font size, did you happen to updated your system or install/uninstall some fonts?
