### ISSUE TITLE
screen blinking in emacs spacemacs

### ISSUE THREAD

**Issue by llllbarcodellllllllll** [syl20bnr/spacemacs#15698]
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>
screen blinking

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>
open any document and just reading it.

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
Open any file and read it
In random time screen blink very similar to this
issue https://github.com/syl20bnr/spacemacs/issues/12009
there are the screen video with blink
but I don't make any event ( click , scroll, etc )

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>
screen don't blink in random time during read document

#### System Info :computer:
- OS: darwin
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 4c027d0ab)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm lsp multiple-cursors
            (org :variables org-agenda-include-diary t org-enable-notifications t org-start-notification-daemon-on-startup t org-enable-org-brain-support t org-image-actual-width nil org-default-notes-file "~/org/notes_mobile.org" org-enable-org-journal-support t)
            syntax-checking treemacs)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER THREADS TOOLKIT_SCROLL_BARS ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
does their solution work for you?

**Comment by llllbarcodellllllllll** [comment]
> does their solution work for you?

Solution was switch to another emacs distributive such as emacs-plus etc.
However I find another solution: compile the latest emacs from emacs git 
0.999.0@29.0.50 (spacemacs) , I test it atm  and I don't see  any screen blink.
