### ISSUE TITLE
error message "Package ‘all-the-icons’ isn’t installed"

### ISSUE THREAD

**Issue by sunlin7** [syl20bnr/spacemacs#15691]
Hi @lebensterben 
There is an error message in the `*Message*` buffer afer I start the Spacemacs with deubg init option:
```$ emacs --debug-init
Package ‘all-the-icons’ isn’t installed
```
It caused by the very early detection in line 1374, for `all-the-icons` is not loaded at early startup, until loading the layers.
https://github.com/syl20bnr/spacemacs/blob/9acd3411128dd85a2538c962dab61f2597b6cdf7/core/core-spacemacs-buffer.el#L1369-L1375

It maybe related to 8262481 spacemacs-buffer: bug fix and improvement

**Comment by lebensterben** [comment]
I've found a way to fix it. This message is harmless.

**Comment by sunlin7** [comment]
Yes, this message is harmless. Thank you.

**Comment by lebensterben** [comment]
The fix is very simple, just replacing these lines https://github.com/syl20bnr/spacemacs/blob/9acd3411128dd85a2538c962dab61f2597b6cdf7/core/core-spacemacs-buffer.el#L1374-L1376

by

```elisp
        (when (and spacemacs-initialized
                   (not (configuration-layer/package-used-p 'all-the-icons)))
          (message "Package `all-the-icons' isn't installed")
          (setq dotspacemacs-startup-buffer-show-icons nil))
```

You can try it. I'll push the fix later.

**Comment by rommeswi** [comment]
That error message has bugged me for a while. Thank you for fixing it!

**Comment by svenpanne** [comment]
If I see this correctly, the fix above is not yet in `develop`, or am I missing something? 🤔

**Comment by sunlin7** [comment]
The message not exist on the latest develop branch. Close this ticket.

**Comment by Khoulaiz** [comment]
Maybe reopen this? Because I am on the newest development and I have this error message in the second line of my message buffer currently.
(And the package _is_ installed including the fonts.) So it's only about the message here.

**Comment by RaghuNaik** [comment]
yes I am also seeing this message despite being on the newest version.

**Comment by mijoharas** [comment]
In addition, I don't see icons in the `*spacemacs*` buffer next to recent files and projects when they used to be there (along with seeing this error message).

**Comment by practicalli-johnny** [comment]
I can confirm that the error message "Package ‘all-the-icons’ isn’t installed" is no longer showing in the `*messages*` buffer after pulling the latest `develop` branch today.  Thank you.

@mijoharas if icons are not shown in the Spacemacs home buffer, then run the `all-the-icons-install-fonts`command
```emacs
SPC SPC all-the-icons-install-fonts
```
