### ISSUE TITLE
haskell-interactive remap

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#1569]
My quick attempt to remap:

    (eval-after-load "interactve-haskell"
      '(progn
        (define-key haskell-interactive-mode-map [up] 'haskell-interactive-mode-history-previous)
        (define-key haskell-interactive-mode-map [down] 'haskell-interactive-mode-history-next)))

Not working

**Comment by syl20bnr** [comment]
Check if your code is correctly evaluated by adding a `message` sexp in the `progn`.
