### ISSUE TITLE
Markdown puts "folding" on S-Tab

### ISSUE THREAD

**Issue by idbrii** [syl20bnr/spacemacs#1570]
Opening a markdown document and using `zM` gives an error:

    user-error: Folding is not supported for any of these major/minor modes

However, using Tab/S-Tab (backtab) folds text by cycling between different fold styles.

Does it make sense to map that to folding instead? (Although I don't [see](http://jblevins.org/projects/markdown-mode/markdown-mode.el) how you could do that properly: we don't want to cycle we want to expand and collapse.)

Or should [contrib/lang/markdown/packages.el](https://github.com/syl20bnr/spacemacs/blob/master/contrib/lang/markdown/packages.el) include a leader mode map for cycling instead? (If so, how would I remove the mode map for Tab/S-Tab?)

**Comment by syl20bnr** [comment]
Folding on `tab` makes sense because this is how it is done in `org`. Having a good symmetry between markdown and org is a good thing.

**Comment by idbrii** [comment]
Shouldn't all folding be done on Tab then?

Shouldn't `za` also fold in org and markdown?

-David

**Comment by TheBB** [comment]
Evil decides how to fold for each major mode by using `evil-fold-list`. There's no markdown there. I've made a PR to evil to add it. It works the same as org (basically outline mode).

https://bitbucket.org/The-BB/evil/pull-requests/1/add-folding-to-markdown-mode

**Comment by TheBB** [comment]
The patch was merged upstream. It should work when Evil is updated.
