### ISSUE TITLE
No such file or directory, diff

### ISSUE THREAD

**Issue by simohauml** [syl20bnr/spacemacs#15714]
Windows 10
Emacs 28.1

- `SPC f e D`

Error message: "Searching for program: No such file or directory, diff"

Here is message buffer:
![spacemacs1](https://user-images.githubusercontent.com/6779322/187131769-37ef7f9f-ec08-4860-9d4e-8f289b9082fc.png)

**Comment by simohauml** [comment]
I install Git and after set C:\Program Files\Git\usr\bin to system path, the issue is gone. 
Close this issue

**Comment by wanglian1913** [comment]
in   .spacemacs.env  add    C:\Program Files\Git\usr\bin
