### ISSUE TITLE
`SPC m s i ` doesn't start the python terminal 

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1571]
From the Python Layer doc : 

> Start a Python or iPython inferior REPL process with <kbd>SPC m s i</kbd>.

I have installed the Python layer, and in a `.py` file (that's been saved) pressing `<leader> m s i ` doesn't bring up any terminal, what it does do is put me in insert mode (and inserts `i`) 

I have installed the layer with `C-c C-C` and restarted emacs, still doesn't work.

**Comment by cpaulik** [comment]
Works perfectly for me. 

What happens if you press the command slowly? Is guide key showing the correct commands? [i] should be bound to `python-start-or-switch-repl`. If this does not work what happens if you press `SPC :` and run `python-start-or-switch-repl` manually?

**Comment by geo7** [comment]
Cheers cpaulik - `<leader> :` then `python-start-or-switch-repl` works for me. 

`<leader> m s i` doesn't though. 

If I type `<leader>` in the python buffer I then get the guide key suggestions, `m` isn't even on that list. 

thanks!

**Comment by person808** [comment]
Do you have the python layer enabled?

**Comment by geo7** [comment]
@person808  yeah the python layer is enabled. 

I have just tried `<leader> s i ` and this works, I guess that `m` was some kind of `<leader>` short hand...? 

`<leader> s i` brings up the python REPL ( and I can use vim keys in it :dancer: ) 

Thanks

**Comment by person808** [comment]
`SPC m s i` is how to do it using the default leader key. `, s i` is using the `dotspacemacs-major-mode-leader-key`.

**Comment by geo7** [comment]
@person808 Ok, that's where the confusion was I guess. I thought that the default leader key was `SPC`, and that by remapping that to something else I could just drop in `,` instead of `SPC`

I will note that I have the following : 

```text
   ;; The leader key
   dotspacemacs-leader-key ","
   ;; Major mode leader key is a shortcut key which is the equivalent of
   ;; pressing `<leader> m`. Set it to `nil` to disable it.
```

Maybe the confusion came from there though ;)

**Comment by tboquet** [comment]
Hello all,

Sorry to reopen this thread but I have a fresh install of emacs 24.5 and I run into a similar problems when using SPC m s i. No inferior python process is launched but I see the warning message `no inferior python process running`. I guess that the shortcut is working but the behaviour of the command run is not right. I have tried @cpaulik suggestion `SPC : python-start-or-switch-repl` but indeed, it led to the same result. When I use the same configuration on emacs 24.4 compiled from source, everything is working as expected.

**Comment by mattalhonte** [comment]
Having the exact same problem  Running Windows 10 and emacs 24.5.  Everything else in the python layers is working fine.

**Comment by geo7** [comment]
@mattalhonte it might not be the same problem - looking at my issue on this it seemed to be because I had tried to remap my leader key to `,` which is the shorthand for `SPC m`, I'm using Linux, so It might be a different issue to what you and @tboquet are experiencing, I'm not sure though.

**Comment by syl20bnr** [comment]
@mattalhonte can you open a new issue ?
