### ISSUE TITLE
Correct usage of "spacemacs/set-leader-keys"?

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#15716]
I've been avoiding updating for quite a while because `evil-leader/set-key` is deprecated and I couldn't figure out how to use `spacemacs/set-leader-keys`.

I am trying to bind `SPC SPC` to the old `avy-goto-word-or-subword-1` (like original spacemacs had it), I have tried this:

```elisp
  ;; Bind up user functions
  (spacemacs/set-leader-keys
    "ow" 'ao/what-face
    "ob" 'ao/show-file-name
    "oa" 'avy-goto-char-2
    "sp" 'ao/project-literal-search
    "SPC" 'avy-goto-word-or-subword-1
    "w <SPC>" 'ace-window
    )
```

I don't get any error on startup, but none of the keybindings work. What am I doing wrong here?

**Comment by lebensterben** [comment]
"SPC" 'avy-goto-word-or-subword-1

this translates to SPC SPC SPC, is this what you want?

**Comment by lebensterben** [comment]
"ob" this for example should translate to SPC SPC o b, does it work

**Comment by synic** [comment]
It does not work, none of them work

**Comment by lebensterben** [comment]
have you declared "o" prefix with spacemacs/declare-prefix

**Comment by synic** [comment]
No, is there documentation somewhere on how to use the new system?

**Comment by synic** [comment]
This does not seem like it will allow me to bind `SPC SPC` to `avy-goto-word-or-subword-1`, since there is no prefix, how would I do that? The other ones might work because they have the "o" prefix, but this one is different

**Comment by lebensterben** [comment]
> allow me to bind SPC SPC to avy-goto-word-or-subword-1

You should not do this anyway.

**Comment by synic** [comment]
I've been doing this since 2015, so I will go ahead and disagree

**Comment by lebensterben** [comment]
you can use define-key or evil-define-key directly on spacemacs-default-map I think.

**Comment by BenedictHW** [comment]
Set `dotspacemacs-emacs-command-key` to nil or `""` in addition to something like,

``` emacs-lisp
(spacemacs/set-leader-keys
  "SPC" #'helm-for-files)
```

**Comment by synic** [comment]
I have the following in my comfig:

```
   dotspacemacs-leader-key "SPC"

   ;; The key used for Emacs commands `M-x' (after pressing on the leader key).
   ;; (default "SPC")
   dotspacemacs-emacs-command-key ":"
```

**Comment by lebensterben** [comment]
just don't use spacemacs/set-leader-keys

**Comment by BenedictHW** [comment]
I have tried setting `dotspacemacs-emacs-command-key` to ":" and I was
still able to bind "SPC SPC" to `avy-goto-word-or-subword-1`. And it
works. "SPC SPC" is a special case, I'm more intrigued that none of your
other bindings are working. Toggling debug-on-error on and evaling the
`spacemacs/set-leader-keys` form gives no backtrace? Are you maybe
overriding the bindings with a mode specific keymap?

**Comment by synic** [comment]
hrmm, it is working now. There was an earlier error in my config regarding `evilified-state-evilify` that was causing the config to abort. I commented that for now, everything else seems to be working so far. Thank you for your help.

**Comment by lebensterben** [comment]
use spacemacs/declare-prefix or which-key-add-keymap-based-replacements on spacemacs-default-map instead

they both declare prefix keys and define bindings.

spacemacs/set-leader-keys is thus unnecessary.
