### ISSUE TITLE
Starting atril (or other applications like libreoffice) with shell-command causes symbol lookup error

### ISSUE THREAD

**Issue by berchas** [syl20bnr/spacemacs#15728]
#### Description :octocat:
Starting atril (or other applications like libreoffice) with shell-command causes symbol lookup error.  
The error message is: atril: symbol lookup error: /snap/emacs/1609/usr/lib/x86_64-linux-gnu/gio/modules/../../../../../lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
Starting the application in a normal terminal works fine.
Ubuntu 22.04 LTS. Emacs was freshly installed from snap and then spacemacs cloned. The issue does not occur if spacemacs is omitted.

#### Reproduction guide :beetle:
- Start Emacs
- Spc+! and atril

*Observed behaviour:* :eyes: :broken_heart:
Application does  not start and error message appears.

*Expected behaviour:* :heart: :smile:
Running application.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. acab040c7)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
> The issue does not occur if spacemacs is omitted

why do you mean here?

**Comment by lebensterben** [comment]
this seems like a problem caused by snap.

**Comment by beruchris** [comment]
Thank you for your response. When I delete emacs.d and start emacs as such, the issue does not occur.

It is related to the spacemacs.env file that I just discovered. When I delete all snap related entries in the file, the issue is gone and spacemacs works normally.

(If I delete the file completely, and spacemacs recreates it, the issue reappears. This is even the case if I reboot in between (starting from a working set-up). Apparently there is an issue with my environment variables. However, printenv does not give me any of the snap related variables that spacemacs is exporting to spacemacs.env )

**Comment by lebensterben** [comment]
can you elaborate more on what snap-related entries you have removed?

**Comment by beruchris** [comment]
Following lines (it was easier to remove all).  

FONTCONFIG_FILE=/home/myuser/snap/emacs/common/fonts.conf
GDK_PIXBUF_MODULEDIR=/snap/emacs/1609/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders
GDK_PIXBUF_MODULE_FILE=/home/myuser/snap/emacs/common/.cache/gdk-pixbuf-loaders.cache
GIO_MODULE_DIR=/snap/emacs/1609/usr/lib/x86_64-linux-gnu/gio/modules
PATH=/home/myuser/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/emacs/current/usr/bin
PATH=/home/myuser/.local/bin:/home/myuser/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/emacs/current/usr/bin
SNAP=/snap/emacs/1609
SNAP_ARCH=amd64
SNAP_COMMON=/var/snap/emacs/common
SNAP_CONTEXT=DnDB8aK1DBdBySuqz13eiatC4l6yz0CaX9ZLTWMWGJwT6aUNzLCt
SNAP_COOKIE=DnDB8aK1DBdBySuqz13eiatC4l6yz0CaX9ZLTWMWGJwT6aUNzLCt
SNAP_DATA=/var/snap/emacs/1609
SNAP_INSTANCE_KEY=
SNAP_INSTANCE_NAME=emacs
SNAP_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void
SNAP_NAME=emacs
SNAP_REAL_HOME=/home/myuser
SNAP_REEXEC=
SNAP_REVISION=1609
SNAP_USER_COMMON=/home/myuser/snap/emacs/common
SNAP_USER_DATA=/home/myuser/snap/emacs/1609
SNAP_VERSION=28.1
XDG_DATA_DIRS=/usr/share/xubuntu:/usr/share/xfce4:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/usr/share

**Comment by lebensterben** [comment]
can you try to remove GDK_PIXBUF_MODULEDIR and/or GIO_MODULE_DIR?

the rest variables (especially those SNAP_*) doesn't seem to be the cause.

**Comment by beruchris** [comment]
I have to remove 
GDK_PIXBUF_MODULE_FILE=/home/myuser/snap/emacs/common/.cache/gdk-pixbuf-loaders.cache
and
GIO_MODULE_DIR=/snap/emacs/1609/usr/lib/x86_64-linux-gnu/gio/modules

**Comment by lebensterben** [comment]
@beruchris 

you mean removing both of them (and keep all the rest) works?

If so I can simply avoid automatically setting them in .spacemacs.env.

**Comment by beruchris** [comment]
Yes, exactly
