### ISSUE TITLE
golden-ratio doesn't resize windows when the window is changed with evil-window-next or evil-window-prev

### ISSUE THREAD

**Issue by riclima** [syl20bnr/spacemacs#1572]
When pressing `C-w w` (or, `C-w C-w`), which calls `evil-window-next`, the point moves to the next window, but the windows are not resized according to `golden-ratio`. Pressing `SPC w w`, which calls `other-window`, moves the point to the next window and the windows resize according to `golden-ratio`. Same issue happens on `evil-window-prev` (`C-w W` or `C-w C-S-w`) Interestingly enough, the other `evil-window-*` seem to work correctly; by calling `evil-window-left` (`C-w h` or `SPC w h`), the point moves to the window to the left and the windows are resized correctly.

OS and software versions:
Kubuntu 15.04
Spacemacs v.0.101.3
GNU Emacs 24.4.1
evil-git-ae343bb

**Comment by riclima** [comment]
I just dug around and found #497 and #566, the fix is actually quite simple. I've added to my .spacemacs the following lines which solved this issue:

      (setq golden-ratio-extra-commands
               (append golden-ratio-extra-commands
                             '(evil-window-next
                               evil-window-prev)))

Perhaps those should be added to https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L1128, as well as the other evil-window-* commands?

**Comment by syl20bnr** [comment]
@riclima you are right, can you PR this ?

**Comment by riclima** [comment]
No problem; I'll send it when I have a bit of free time.
