### ISSUE TITLE
Unclear recentf-exclude variable description

### ISSUE THREAD

**Issue by rommeswi** [syl20bnr/spacemacs#15727]
This is something very minor but potentially confusing for new users.

When using `SPC h d recentf-exclude` or `customize-variable` the variable description is ambiguous.

The data field is denoted by "Regexp" but the default entries are clearly not regular expressions, for example "~/.emacs.d/.cache/.custom-settings" is actually the (unescaped) string that the regexp is supposed to be searching for.

Therefore, either the default values are not properly entered as regexp and matches are just coincidental or the value of the variable should actually not be a regular expression but just a string (in which case more documentation should be provided how the string is matched).

**Comment by lebensterben** [comment]
seems to be a bug but easy to fix.

**Comment by rommeswi** [comment]
This seems to be an issue that has to be fixed upstream since recentf is emacs built-in, or? Then this can probably be closed.
