### ISSUE TITLE
Can't use C-j and C-k to scroll helm completion buffer

### ISSUE THREAD

**Issue by ebanner** [syl20bnr/spacemacs#15720]
#### Description :octocat:
Can't use `C-j` and `C-k` to scroll helm completion buffer.

Digging into this, it seems that the variable `hybrid-mode-enable-hjkl-bindings` is not defined...

#### Reproduction guide :beetle:
- Start Emacs
- `SPC f f `
- Press `C-j` and `C-k` to scroll helm completion buffer (nothing happens)
- Evaluate `hybrid-mode-enable-hjkl-bindings` in minibuffer and see it is not defined

*Observed behaviour:* :eyes: :broken_heart:
Cannot use `C-j` and `C-k` to scroll completion buffer
Variable `hybrid-mode-enable-hjkl-bindings` is undefined

*Expected behaviour:* :heart: :smile:
`hybrid-mode-enable-hjkl-bindings` should be defined and I should be able to set it to `t` so that `C-j` and `C-k` scrolls the helm completion buffer.

#### System Info :computer:
- OS: darwin
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 1ed08595b)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(html emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER THREADS TOOLKIT_SCROLL_BARS ZLIB

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-variable hybrid-mode-enable-hjkl-bindings)
  eval(hybrid-mode-enable-hjkl-bindings t)
  eval-expression(hybrid-mode-enable-hjkl-bindings nil nil 127)
  funcall-interactively(eval-expression hybrid-mode-enable-hjkl-bindings nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)

```

**Comment by ebanner** [comment]
Nevermind! Looks like the variable got renamed to `hybrid-mode-enable-hjkl-bindings`.

The documentation [here](https://develop.spacemacs.org/doc/DOCUMENTATION.html#browsing-files-in-completion-buffer) has it labeled as `hybrid-mode-enable-hjkl-bindings`

**Comment by lebensterben** [comment]
Let's keep it open until the documentation is updated.
