### ISSUE TITLE
Killing *scratch* on startup breaks *spacemacs* recent files and projects

### ISSUE THREAD

**Issue by rommeswi** [syl20bnr/spacemacs#15734]
#### Description :octocat:
I never use the scratch buffer so I wanted to kill it on startup. Unfortunately, this breaks the *spacemacs* buffer as it no longer shows the recent files and projects.

 Killing the message buffer on startup does not have this effect.

#### Reproduction guide :beetle:
- Place `(kill-buffer "*scratch*") ` into `.spacemacs` file under `user-config`
- Restart emacs

*Observed behaviour:* :eyes: :broken_heart:
- The `*spacemacs*` buffer no longer shows recent files and projects.
- The loading bar at the bottom also gets stuck.

*Expected behaviour:* :heart: :smile:
Spacemacs closes the `*scratch*` buffer but I can still use recent files and projects.

**Comment by drlkf** [comment]
Not a contributor, but if I may suggest trying:

```emacs-lisp
(advice-add 'spacemacs-buffer/goto-buffer
            :after (lambda (&rest args)
                     (let ((buffer (get-buffer "*scratch*")))
                       (when buffer (kill-buffer buffer)))))
```

**Comment by rommeswi** [comment]
Thank you for your suggestion. It works but creates the error "Warning: Unused lexical argument `args'" when compiling the dotfile.

I also think that the *spacemacs* buffer should somehow work independently of the *scratch* buffer.

**Comment by lebensterben** [comment]
spacemacs buffer doesn't seem to use scratch buffer.

but the setup requires it:

https://github.com/syl20bnr/spacemacs/blob/c5c69ce239577ce1e0fb468698d7aeb2453a6cbb/core/core-spacemacs.el#L242-L245

**Comment by rommeswi** [comment]
Thank you both for your helpful replies.

For now, I simply set `dotspacemacs-scratch-mode` to nil which allows me to kill the buffer just normally.

Perhaps one could insert the additional check
`(when (get-buffer "*scratch*")
  (with-current-buffer "*scratch*"
.....
))`

Perhaps it would even make sense to create a configuration option to run spacemacs without a scratch buffer. Or to kill the scratch buffer if `dotspacemacs-scratch-mode` is nil. But I don't know what the policy is on adding/changing configuration options.

This issue can be closed in case people find that no change is necessary.

**Comment by rommeswi** [comment]
The above pull request solved the issue.
