### ISSUE TITLE
`spacemacs-buffer` opens remote connection to `org-directory`

### ISSUE THREAD

**Issue by drlkf** [syl20bnr/spacemacs#15739]
#### Description :octocat:
`spacemacs-buffer` opens remote connection to `org-directory`

#### Reproduction guide :beetle:
- Install `org` layer
- Set `org-directory` to remote location, such as `/ssh:org.host:/org/directory`
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs will try to expand `org-agenda-files` which causes `tramp` to attempt
establishing a remote connection to `org-directory`.

This is annoying because when you start `emacs` in daemon mode, it might not have
immediate access to the necessary authentication to establish the connection,
and this causes a cascade of failures that can prevent `emacs` from finishing
startup properly.

The culprit is the following code, in `core/core-spacemacs-buffer.el`:

```emacs-lisp
(defun spacemacs-buffer//insert-recent-files (list-size)
  (unless recentf-mode (recentf-mode))
  (setq spacemacs-buffer//recent-files-list
  ;; --- BEGIN
        (let ((agenda-files (if (fboundp 'org-agenda-files)
                                (mapcar #'expand-file-name (org-agenda-files))
                              nil)))
          (cl-delete-if (lambda (x)
                          (or (when (and (bound-and-true-p org-directory) (file-exists-p org-directory))
                                (member x (directory-files org-directory t)))
                              (member x agenda-files)))
                        recentf-list)))
  ;; --- END
  (setq spacemacs-buffer//recent-files-list
        (spacemacs//subseq spacemacs-buffer//recent-files-list 0 list-size))
  (when (spacemacs-buffer//insert-file-list
         (spacemacs-buffer||propertize-heading
          (all-the-icons-octicon "history" :face 'font-lock-keyword-face :v-adjust -0.05)
          "Recent Files:" "r")
         spacemacs-buffer//recent-files-list)
    (spacemacs-buffer||add-shortcut "r" "Recent Files:"))
  (insert spacemacs-buffer-list-separator))
```

*Expected behaviour:* :heart: :smile:
I'm not sure what the ideal behavior is here. My own workaround is to simply
redefine the function with this code removed, and simply filter out all the
remote files from my `recentf`.

#### System Info :computer:
- OS: Debian GNU/linux Bullseye
- Emacs: 27.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 1fde8719e)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((keyboard-layout :variables kl-layout 'qwerty)
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t)
 (japanese :variables helm-migemo-mode 1)
 (ranger :variables ranger-cleanup-on-disable t ranger-show-hidden t ranger-max-preview-size 2 ranger-cleanup-eagerly t)
 git helm lsp markdown multiple-cursors graphviz
 (shell :variables shell-default-position 'bottom shell-default-height 40 shell-default-shell 'vterm)
 pass mu4e vim-empty-lines reddit lobsters syntax-checking auto-completion
 (org :variables org-roam-enable-protocol nil org-enable-roam-support nil)
 emoji ibuffer debug go html lua haskell imenu-list perl5 sql vimscript
 (shell-scripts :variables shell-scripts-format-on-save t)
 systemd yaml rust nginx csv ruby
 (python :variables python-format-on-save t python-formatter 'black)
 (terraform :variables terraform-backend 'lsp terraform-auto-format-on-save t)
 java javascript emacs-lisp php salt cmake scala)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```

```

**Comment by lebensterben** [comment]
thanks for reporting. this indeed is a bug.
