### ISSUE TITLE
Error loading helm on develop branch

### ISSUE THREAD

**Issue by mahaha** [syl20bnr/spacemacs#1573]
After switching the `develop` branch, I have been encountering the following errors when spacemacs starts:
```
Error (use-package): helm :init: Symbol's function definition is void: advice-add
Error (use-package): spray :init: Symbol's function definition is void: advice-add
```
I have already tried starting spacemacs without my `.spacemacs` and deleted all packages in the `elpa` folder, but the problem still persists.

**Comment by cpaulik** [comment]
What version of emacs are you using? I think these functions where added in emacs 24.4

**Comment by tuhdo** [comment]
I've deleted everything and updated again. Spacemacs starts without any problem. Probably you should upgrade to Emacs 24.4 or above,

**Comment by mahaha** [comment]
Seems like Ubuntu's Emacs version is still 23.x. I have now upgraded to 25.x and everything is working fine! Thanks again!

**Comment by syl20bnr** [comment]
@mahaha 23.x ? I believe last LTS of ubuntu ships with 24.3.

**Comment by mahaha** [comment]
Yeah, for some reason Emacs was loading 23.x and 24.3 had to be executed by `emacs24`. In any case, using 25.x didn't really seem to work so well, so I compiled 24.4 and now all is good.

**Comment by syl20bnr** [comment]
Should be fixed in develop.
