### ISSUE TITLE
Rust LSP backend uses RLS even when configured to use rust-analyzer

### ISSUE THREAD

**Issue by Gabryx64** [syl20bnr/spacemacs#15748]
Rust LSP backend uses RLS even when configured to use rust-analyzer.
The relevant parts of my config are:
```elisp
(setq-default
  ...
  dotspacemacs-configuration-layers '(
    (lsp :variables lsp-rust-server 'rust-analyzer)
    ...
    (rust :variables rust-format-on-save t)
  ))
```

**Comment by Gabryx64** [comment]
oddly enough i figured out that using emacs does work, but doing using emacsclient (even after killing all emacs processes) does still make it use rls

**Comment by lebensterben** [comment]
you need to make sure whether rust-analyzer is in your PATH.

also, rls should be removed soon since it's deprecated.

**Comment by Gabryx64** [comment]
how can i check if it is in emac's path? it is in my path and i also have updated .spacemacs.env

**Comment by Gabryx64** [comment]
ok i have checked .spacemacs.env, it does have rust-analyzer's dir

**Comment by lebensterben** [comment]
if you start emacsclient as a systemd service, and rust-analyzer is not in the PATH *at that point*, emacsclient won't see rust-analyzer.

**Comment by Gabryx64** [comment]
i do not start it as a systemd service, i run `emacs --daemon` in my wm's config, but i'll try with a systemd service

**Comment by Gabryx64** [comment]
nope, still not work, also rust-analyzer was always in my PATH

**Comment by lebensterben** [comment]
if you use a custom window manager, you need to make sure it (or the login shell) sources your shell dotfiles before calling emacs --daemon.

**Comment by Gabryx64** [comment]
ok, apparently it didn't actually souce the dotfiles, after cp'ing rust-analyzer to /usr/bin to test it did work

**Comment by Gabryx64** [comment]
even after adding rust-analyzer to /usr/bin (where it should be in path), it does not work

**Comment by Gabryx64** [comment]
ok after adding rust-analyzer to /usr/bin, it works
