### ISSUE TITLE
Spacemacs fails to start when an unknown theme is declared

### ISSUE THREAD

**Issue by bvanslyke** [syl20bnr/spacemacs#1574]
Following the instructions on Emacs 24.4.1 on Fedora21 results in a blank emacs window with a "Spacemacs is ready" message.

After manually evaluating the startup code I found that it failed when trying to load the first theme from dotspacemacs-themes because monakai was not present. I replaced the list of themes from .spacemacs with a theme I did have installed (wombat), restarted emacs, and then spacemacs installation worked.

**Comment by CarlQLange** [comment]
Did you `git submodule update --init && git submodule sync`? I forget which one of these the readme says to do, but iirc the monokai theme is a submodule...

**Comment by brvs** [comment]
Oh no I didn't. I just did `git clone --recursive http://github.com/syl20bnr/spacemacs ~/.emacs.d`. I didn't realize I was supposed to update right away. Thanks.

**Comment by CarlQLange** [comment]
Mmm, `git clone --recursive` does the same job, I believe. Anyway, I was wrong, the monokai theme isn't a submodule.

So is the only issue theme-related? Does everything else in Spacemacs work?

**Comment by brvs** [comment]
Right. Nothing works (I just get that blank screen saying 'Spacemacs is ready') until I comment-out the themes in `dotspacemacs-themes`  and restart. Then everything works, including the themes it couldn't find on start-up.

**Comment by syl20bnr** [comment]
@brvs Try with `monokai` instread of `monakai` :-)

I keep this issue opened because spacemacs should fallback in case of an unknown theme.

**Comment by CarlQLange** [comment]
:laughing:

**Comment by brvs** [comment]
D'oh! Fallback and display "If you like that theme so much you should learn how to spell it" :P

**Comment by syl20bnr** [comment]
Should be fixed in develop, `spacemacs-dark` is now a fallback theme distributed with Spacemacs. If a theme is unknown a warning appear when loading is finished.
