### ISSUE TITLE
treemacs remap request

### ISSUE THREAD

**Issue by odysseyalive** [syl20bnr/spacemacs#15755]
This is mainly a feature request.  I'm not sure if this applies to many?

I've noticed when hitting SPC-0 that treemacs-select-window doesn't always work all the time, where nothing will pull up in the treemacs at all.

I've since remapped SPC-0 to  treemacs-display-current-project-exclusively which in my case always seems to work.

Perhaps this is user error as to what this binding was originally intended for?  It seems to me that this key binding might be better served remapped to the treemacs-display-current-project-exclusively symbol instead?

**Comment by lebensterben** [comment]
> when hitting SPC-0 that treemacs-select-window doesn't always work all the time, where nothing will pull up in the treemacs at all.

can you describe how to reproduce this behavior?

**Comment by odysseyalive** [comment]
> > when hitting SPC-0 that treemacs-select-window doesn't always work all the time, where nothing will pull up in the treemacs at all.
> 
> can you describe how to reproduce this behavior?

A blank window is really intermittent.  I'll keep an eye on that and see what I can do to reproduce it.

On the other hand, if you select a file from a project and use treemacs-select-window.  Then select a file from another project and use treemacs-select-window, most of the time the other project will show up in the tree.  After some time (I don't know the variables there) the tree will eventually latch onto the current project.

treemacs-display-current-project-exclusively doesn't appear to have either issue.  A treemacs window always displays with the proper project in view.

**Comment by odysseyalive** [comment]
I should note, I have both treemacs-follow-mode and treemacs-project-follow-mode set to t with-eval-after-load of the treemacs package.  That doesn't seem to make a difference, either.

I'm not sure why treemacs is so project heavy, since there are other packages that are designed to manage project scope.  In any case, I prefer treemacs to snap to the current project when opened regardless how many files or different projects are open.

**Comment by lebensterben** [comment]
> I'm not sure why treemacs is so project heavy

that's why I stopped using it and switch back to neotree....

**Comment by odysseyalive** [comment]
> > I'm not sure why treemacs is so project heavy
> 
> that's why I stopped using it and switch back to neotree....

Yeah, that's what I was using prior.  I've started to use the lsp package pretty heavily now, and they seemed to be married to treemacs.
