### ISSUE TITLE
The compleseus layer doesn't take advantage of consult-imenu's narrowing feature for LSP (Java)

### ISSUE THREAD

**Issue by ir210** [syl20bnr/spacemacs#15752]
By default, consult-imenu (`SPC j i`) comes with narrowing enabled only for `emacs-lisp-mode`.

I work with Java and use LSP as the backend. I have to customize `consult-imenu-config` to enable narrowing for java-mode like the following:

```
(custom-set-variables
 '(consult-imenu-config
   '((emacs-lisp-mode :toplevel "Functions" :types
                      ((?f "Functions" font-lock-function-name-face)
                       (?m "Macros" font-lock-function-name-face)
                       (?p "Packages" font-lock-constant-face)
                       (?t "Types" font-lock-type-face)
                       (?v "Variables" font-lock-variable-name-face)))
     (java-mode :toplevel "Classes" :types
                ((?m "Methods" font-lock-function-name-face)
                 (?f "Fields" font-lock-variable-name-face)
                 (?c "Classes" font-lock-type-face)
                 (?p "Packages" font-lock-constant-face)
                 (?C "Constants" font-lock-constant-face)
                 (?M "Constructors" font-lock-function-name-face)
                 (?E "Enums" font-lock-type-face)
                 (?e "Enum Members" font-lock-constant-face)
                 (?i "Interfaces" font-lock-type-face))))))
```

This narrowing feature of consult-imenu really helps me a lot. Especially when dealing with a very large class with inner classes, enums, etc. It would be great to see it preconfigured by default in Spacemacs.

I am unsure if including this config (of course, not exactly like that) in the compleseus layer makes sense, though. For fairness' sake, it must also provide support for the other languages that Spacemacs supports.  Maybe in the Java layer?

Edit: You have to set `lsp-imenu-index-function` to `lsp-imenu-create-categorized-index` in order for the narrowing to work.

**Comment by lebensterben** [comment]
PR is welcomed.

**Comment by ir210** [comment]
@lebensterben Let's see... I've never touched the built-in layers.

In which layer do you suggest I add this config?

**Comment by lebensterben** [comment]
compleseus is best. no need to check whether java layer is used.
