### ISSUE TITLE
add sonarlint in spacemacs

### ISSUE THREAD

**Issue by lebensterben** [syl20bnr/spacemacs#15751]
### Discussed in https://github.com/syl20bnr/spacemacs/discussions/15750

<div type='discussions-op-text'>

<sup>Originally posted by **chavalife17** September 27, 2022</sup>
I tried to install a package that is about sonarlint (https://github.com/emacs-lsp/lsp-sonarlint)

I've used this config after installed this package

```
 dotspacemacs-additional-packages '(
                                      lsp-sonarlint
                                      )

(defun dotspacemacs/user-config ()
  "Configuration for user code:
This function is called at the very end of Spacemacs startup, after layer
configuration.
Put your configuration code here, except for variables that should be set
before packages are loaded."
  (setq lombok-jar-path
        (expand-file-name
         "/Users/mypc/lombok/lombok.jar"
         )
        )

  (setq lsp-java-vmargs `(
                          "-XX:+UseParallelGC"
                          "-XX:GCTimeRatio=4"
                          "-XX:AdaptiveSizePolicyWeight=90"
                          "-Dsun.zip.disableMemoryMapping=true"
                          "-Xmx1G"
                          "-Xms100m"
                          ,(concat "-javaagent:" lombok-jar-path)
                          )
        )
 
  (use-package lsp-sonarlint
    :defer t)
  (use-package lsp-sonarlint-java
    :after lsp-java
    :custom (lsp-sonarlint-java-enabled t))
  (global-set-key (kbd "C-c m c") 'mc/edit-lines)
  (global-set-key (kbd "C->") 'mc/mark-next-like-this)
  (global-set-key (kbd "C-<") 'mc/mark-previous-like-this)
  (global-set-key (kbd "C-c C-<") 'mc/mark-all-like-this)

 )
```

my problem is spacemacs can enabled jdtls and lsp-sonarlint but I can't see a suggestion of my code.
When I start spacemacs, I can see a jdtls started message but in sonarlint always has started.
In this image example, in another ide, I can receive a suggestion about method references instanced of lambdas but in spacemacs no
<img width="730" alt="image" src="https://user-images.githubusercontent.com/26732598/192450038-8adace9c-e108-4816-8377-0ead38239204.png">

Can someone helps me?

thanks for your answers</div>

**Comment by ir210** [comment]
I just tried it (thank you for introducing me to this lsp-sonarlint) via both `package-install` and `(use-package)` and basically did what you did there.

lsp-sonarlint works for me:

![image](https://user-images.githubusercontent.com/354800/192601078-876f4390-f495-4fd6-aa5c-ac1ea29a3b19.png)

I am not really sure what happened but it didn't work for me once, but after restarting spacemacs it worked again. I'll try to use this package for my daily work and will report if I find anything.

**Comment by ir210** [comment]
So, after a restart, `lsp-sonarlint` didn't work anymore for me. So, I did an investigation and found that since you use `:defer t` for `lsp-sonarlint`, `lsp-sonarlint-java` was loaded and configured too soon. Here is the configuration that works for me so far.

```
(use-package lsp-sonarlint
    :defer t)
(use-package lsp-sonarlint-java
    :after (lsp-sonarlint lsp-java)
    :custom (lsp-sonarlint-java-enabled t))
```

**Comment by lebensterben** [comment]
@chavalife17

please verify whether it works.

**Comment by smile13241324** [comment]
Still valid

**Comment by smile13241324** [comment]
This should be adding basic support for sonarlint via the lsp layer. I personally think it will need some polishing but so need the lsp-sonarlint package as well. If you need it please consider helping at the package level.
