### ISSUE TITLE
Error after trying to modifie .spacemacs file

### ISSUE THREAD

**Issue by Thanatos0173Unnoficial** [syl20bnr/spacemacs#15756]
I got an error after editing the .spacemacs file.

I am running ubuntu 22.04, on Virtual Box. I recently tried to develop with spacemacs, and, because I wanted auto-completion, I tried to add it to my .spacemace file. But, when I want to reload it with the keystroke combination `M-m f e R`, it gives me this error message: `Error in dotespacemacs/layers: Wrong type argument: symbolp, 'nil`. And now I get this message every time I run spacemacs

I tried to update the packages, but it didn't work. I couldn't find a solution on the Internet.

What can I do?

Thanks if you help me.

**Comment by lebensterben** [comment]
don't quote nil.

**Comment by Thanatos0173Unnoficial** [comment]
Fix it by just load a snapshot of my VM.
Overkill, I know.

**Comment by Thanatos0173Unnoficial** [comment]
I haven't see your comment. Sorry :-)
