### ISSUE TITLE
No indentation after inserting a new row below a node of a tree

### ISSUE THREAD

**Issue by Coder-DG** [syl20bnr/spacemacs#15764]
Using `GNU Emacs 28.2` and latest spacemacs as of today (commit `264a8ffc203a3215623330576941d1722bbee1e4`).

I wrote `* Notes` hit enter but there's no indentation right after that.
I'm not sure what setting do I need to enable. I can obviously indent myself with `>>` but AFAIK it should happen automatically.

Is there some setting I'm missing?

Thanks!

**Comment by lebensterben** [comment]
you need to follow the instructions on issue template.

**Comment by Coder-DG** [comment]
I see what part I missed in the issue creation. My bad, closing this one.
