### ISSUE TITLE
evil-escape is not in melpa. fails to install. Many spacemacs commands don't work.

### ISSUE THREAD

**Issue by truthseekers** [syl20bnr/spacemacs#15768]
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>
Spacemacs fails to install the package "evil-escape" and provides the following message:

"Package evil-escape is unavailable. Is the package name misspelled?"

the evil-escape githup repo claims its available in Melpa:

https://github.com/syl20bnr/evil-escape

However, it doesn't appear to be. https://melpa.org shows no "evil-escape" when searching with their filter.

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

1. delete / rename .emacs/d folder
2. git clone https://github.com/syl20bnr/spacemacs $HOME/.emacs.d
3. open emacs so it installs all spacemacs defaults. (should fail to install evil-escape)

Not sure if reproduction steps will work if you already have evil-escape from an older version of melpa, but mine fails due to not having evil-escape in melpa.

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

Cannot run SPC f   or a variety of sapcemacs commands.

#### System Info :computer:
- OS: windows-nt
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 264a8ffc2)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: ACL GIF GMP GNUTLS HARFBUZZ JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY W32NOTIFY PDUMPER PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XPM ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by boaf** [comment]
+1. Received the same error on startup. Additionally, when initiating `which-key` with `SPC`, only some of the key prefixes are defined and the error "Cannot open load file: No such file or directory, evil-escape" is shown in the minibuffer.

Also, on my system it is impossible to resize the emacs window without emacs (seemingly) freezing and becoming unresponsive.

**System Info** 💻

- OS: macOS 11.7
- Emacs: 28.2 (https://github.com/d12frosted/homebrew-emacs-plus)
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. https://github.com/syl20bnr/spacemacs/commit/264a8ffc203a3215623330576941d1722bbee1e4)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: `()` (I disabled all layers in `.spacemacs`)

**Comment by purcell** [comment]
Please see discussion in the related MELPA ticket https://github.com/melpa/melpa/issues/8227

**Comment by boaf** [comment]
FWIW, as a **workaround** until melpa/melpa#8227 is resolved, I found adding the following to `dotspacemacs-additional-packages` allowed Emacs to initialize properly:

```
(evil-escape :location "~/evil-escape")
```

Where `~/evil-escape` is a local copy of the [`evil-escape` repo](https://github.com/syl20bnr/evil-escape)

**Comment by tarsius** [comment]
It's back at https://melpa.org/#/evil-escape.

**Comment by purcell** [comment]
Rather than now close this issue as fixed, I would strongly recommend it be re-titled "evil-escape is unmaintained", and kept open until a proper maintainer steps up for that package. As I wrote in https://github.com/melpa/melpa/issues/8227

> It's worth noting that Jonas has done some extra work here for the community by making a fork and applying this fix. An ideal outcome now would be that someone who cares about this package would take over maintainership of the original package (ideally at its original location, or via a repo transfer from that place to a new home), then we would be delighted to change the recipe to build from there instead.

**Comment by smile13241324** [comment]
I have made a fork and provided a new version of this package. Spacemacs has already been changed to refer to my github repo, still I have not yet tried to upload it to Melpa.

I will keep this issue open till a replacement is online.

**Comment by practicalli-johnny** [comment]
Is there the same issue with string-edit and evil-ediff packages?

I did a clean install yesterday (wiped .emacd.d and cloned Spacemacs) and I get the following when starting up Emacs (several times)

```
--> installing package: string-edit@spacemacs-editing... [1/2]
Package string-edit is unavailable. Is the package name misspelled?
--> installing package: evil-ediff@spacemacs-evil... [2/2]
Package evil-ediff is unavailable. Is the package name misspelled?
```

Update: string-edit has been renamed to string-edit-at-point on 2nd August
https://github.com/magnars/string-edit.el/commit/4a25dc7168b4df62b9f83bf273dee92bb2ae39a6
- as discussed in https://github.com/syl20bnr/spacemacs/issues/15648

**Comment by tarsius** [comment]
From `evil-ediff`'s readme:

> This project has been merged into the larger [Evil Collection](https://github.com/emacs-evil/evil-collection) project and will no longer be maintained here.

Therefore, spacemacs should drop the dependency on `evil-ediff`. I assume it already depends on `evil-collection`.

**Comment by smile13241324** [comment]
Dependency is dropped
