### ISSUE TITLE
Chinese characters in Recent Files

### ISSUE THREAD

**Issue by rschuetzler** [syl20bnr/spacemacs#15766]
I'm not sure why, but my spacemacs Recent Files list includes seemingly random (Chinese?) characters before each file. There is also an "fi" ligature before some of the projects, but not all of them. I have Source Code Pro and Variable installed on my machine, and haven't changed anything about the default fonts from the default installation. Below is the text and a screenshot of how it appears in my Emacs.

## System info
* MacOS 12.6
* Emacs: 28.2 (installed cask from homebrew)
* Spacemacs: 0.999.0@28.2

```
          Recent Files: (r)
              1   ~/.spacemacs
              2   ~/code/chattr-lab/docker-compose.yml
              3   ~/code/chattr-lab/frontend/src/App.vue
              4   ~/code/chattr-lab/frontend/public/chattr-logo.svg
              5   ~/code/chattr-frontend/src/App.vue
         
          Projects: (p)
              6   ~/code/chattr-lab/
              7   ~/code/chattr-lab/frontend/
              8   ~/code/chattr-frontend/
              9   ~/.emacs.d/
             10   ~/code/chattr-lab/backend/
```

<img width="508" alt="Screenshot of spacemacs recent files list (contents listed above)" src="https://user-images.githubusercontent.com/600775/194897361-465ba7af-dbc3-4010-8b47-d7c6e490713d.png">

**Comment by lebensterben** [comment]
@rschuetzler 

have you done M-x all-the-icons-install-fonts?

**Comment by rschuetzler** [comment]
Nope. That was it. Thank you
