### ISSUE TITLE
Evaluating lisp problems 

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1576]
Earlier today I was evaluating lisp using `<leader> m e e`, this is no longer working. 

I have `<leader>` mapped to `,` 

I'm not sure if that will make any conflicts with the following : 

```text
       ;; The leader key
       dotspacemacs-leader-key ","
       ;; Major mode leader key is a shortcut key which is the equivalent of
       ;; pressing `<leader> m`. Set it to `nil` to disable it.
       dotspacemacs-major-mode-leader-key ","
```

Here is the code that I'm trying to evaluate in Spacemacs

    (defun greeting (from-name)
      (let ((your-name (read-from-minibuffer "Enter your name : ")))
        (switch-to-buffer-other-window "*tester")
        (erase-buffer)
        (insert (format "hello %s\n i am %s" your-name from-name))
        (other-window 1)
        ))

    (greeting "Mike")

When I move the cursor to the end of the `greeting` function or the end of the `greeting` function call It just moves me down a couple of lines (as `e` is searching to the end of the word) rather than evaluating the lisp.

**Comment by jasoncyu** [comment]
@geo7 I think the idea is to have two leader keys: one for global commands and one for major mode commands. you can bind one of the two as `,`, but you should bind the other one to something else

**Comment by geo7** [comment]
@jasoncyu Right, I'm not too sure what major mode is at the moment tbh. 

I found a problem with starting Python REPL before, that turned out to be something to do with `<leader>` / `SPC` or something

**Comment by tuhdo** [comment]
Buffer is just text. You can think major mode is simply a classification of your buffers and each such class has its own features. For example, if a buffer is classified as Python buffer, it has certain features enabled on it i.e. syntax highlighting, code evaluation commands (similar to the one you tried with Emacs Lisp) but specific to Python etc...

**Comment by geo7** [comment]
thanks all, closed :)
