### ISSUE TITLE
magit status buffer didn't show when I visit file and close file

### ISSUE THREAD

**Issue by luozikuan** [syl20bnr/spacemacs#15763]
#### Description :octocat:
When I access the file in unstaged list of magit status buffer, and then close the file, the magit status buffer does not display. It shows the buffer before I opened the magit status.

#### Reproduction guide :beetle:
- Start Emacs
- Open a git repo with unstaged content by pressing `SPC g s`
- Move cursor to one of unstaged files
- Press <return> key to visit file
- Close file buffer with `SPC b x` or `C-x k`

*Observed behaviour:* :eyes: :broken_heart:
After close file buffer, spacemacs go back to the buffer before I open magit-status.

*Expected behaviour:* :heart: :smile:
After close file buffer, spacemacs show magit-status buffer, just like before visit the file.

#### System Info :computer:
- OS: darwin
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 264a8ffc2)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(better-defaults ibuffer
                 (lsp :variables lsp-lens-enable t)
                 (docker :variables docker-dockerfile-backend 'lsp)
                 html yaml
                 (cmake :variables cmake-backend 'lsp cmake-enable-cmake-ide-support t)
                 javascript typescript
                 (python :variables python-backend 'lsp python-lsp-server 'pyright)
                 dap emacs-lisp
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-lsp-enable-semantic-highlight t c-c++-lsp-semantic-highlight-method 'overlay c-c++-adopt-subprojects t)
                 git helm
                 (keyboard-layout :variable kl-layout 'colemak-hnei kl-disabled-configurations
                                  '(org magit))
                 markdown
                 (osx :variables osx-swap-option-and-command t)
                 multiple-cursors org
                 (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left version-control-global-margin t)
                 (treemacs :variables treemacs-lock-width t treemacs-use-git-mode 'deferred))
```
- System configuration features: ACL GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM ZLIB

**Comment by lebensterben** [comment]
confirmed.

**Comment by alexey0308** [comment]
Hi @luozikuan, does it help if you set the variable to nil?

```
(setq spacemacs-useless-buffers-regexp nil)
```

**Comment by luozikuan** [comment]
> Hi @luozikuan, does it help if you set the variable to nil?
> 
> ```
> (setq spacemacs-useless-buffers-regexp nil)
> ```

Thanks, It works! :ok_hand:
