### ISSUE TITLE
Auto Completion Not Working Anymore

### ISSUE THREAD

**Issue by Thanatos0173Unnoficial** [syl20bnr/spacemacs#15760]
I'm on ubuntu.
I've modified my .spacemacs file in order to add copy-paste layer, but just remove it after. 
However, after I do that, the auto-completion layer just stop working.

What do I do ?

[spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/9701079/spacemacs.txt)
My .spacemacs config

**Comment by lebensterben** [comment]
restart emacs and retry.

also you should follow the instructions on issue template.

**Comment by Thanatos0173Unnoficial** [comment]
Already do both of it. That didn't work.

**Comment by lebensterben** [comment]
I said, you should follow the instructions on the issue template.

There is no way to reproduce what you observed without more detailed information.

**Comment by Thanatos0173Unnoficial** [comment]
Ok, so.

> If you are posting about a *bug* please close this issue and open a new one from within Spacemacs using:
> - `SPC h I`
> - `M-m h I`
> 
> (I = capital i)
> 

 -> My problem is not a bug, but me who screwed up (I think)

> if the bug makes Spacemacs unusable, you can find the bug report template [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template).

 -> The bug don't make it unusable

> A few optional steps that might help:
> - Update `emacs` to latest stable release.
> - [Update](https://github.com/syl20bnr/spacemacs#update) `spacemacs`.

 -> I don't know how to do it.


> - Update all emacs packages. 
>   -`M-x configuration-layer/update-packages`. When seeing the prompt, type `y` and then restart emacs with `SPC q r`.

 -> Already did it, that didn't work.


What append:
    I wanted to add the xclip layer to my .spacemacs file. So, I put it on the file(at dotspacemacs-configuration-layers) , and download it using apt. But, this didn't work. So, I removed it. (Using the shortcut SPC-f-e-R both time to "reload" the .spacemacs file) But, I noticed one hour after that I lose the autocompletion on python. However, the auto-completion for OCaml is still here.

Do you need more information? Do you know what could possibly have gone wrong ?

**Comment by lebensterben** [comment]
You need to follow the issue template. I won't say it again.
