### ISSUE TITLE
The package `aggressive-indent` is failing to install on every start of Emacs

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#15765]
#### Description :octocat:
The package `aggressive-indent` is failing to install on every start of Emacs.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
This appears in `*Messages*`:

```
(Spacemacs) --> installing package: aggressive-indent@spacemacs-editing... [1/1]
Contacting host: melpa.org:443
  INFO     Scraping files for loaddefs... 
(Spacemacs) Error: 
An error occurred while installing aggressive-indent (error: (wrong-type-argument stringp :lighter))
```

*Expected behaviour:* :heart: :smile:
No errors!

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 264a8ffc2)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash docker evil-commentary evil-snipe
 (git :variables git-enable-magit-todos-plugin t)
 (helm :variables helm-no-header t)
 (lsp :variables lsp-lens-enable nil lsp-use-lsp-ui t lsp-use-upstream-bindings nil)
 mu4e multiple-cursors restclient
 (shell :variables shell-default-shell 'ansi-term)
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t persp-autokill-buffer-on-remove 'kill-weak)
 spacemacs-editing-visual spacemacs-visual
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking templates tree-sitter vinegar
 (xclipboard :variables xclipboard-enable-cliphist t)
 (c-c++ :variables c-c++-backend 'lsp-ccls)
 (clojure :variables clojure-enable-sayid t clojure-enable-clj-refactor t clojure-enable-linters 'clj-kondo clojure-backend 'lsp)
 emacs-lisp
 (go :variables go-backend 'lsp go-format-before-save t)
 (haskell :variables haskell-completion-backend 'lsp haskell-process-type 'cabal-repl)
 (python :variables python-formatter 'yapf)
 rust shell-scripts csv graphviz html json latex markdown
 (org :variables org-enable-reveal-js-support t org-enable-roam-support t org-roam-enable-protocol nil org-enable-github-support t org-enable-transclusion-support t)
 nixos spacemacs-org
 (sql :variables sql-auto-indent nil)
 pandoc systemd terraform yaml direnv mt-misc projectile-extra org-extra)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS WEBP XIM XWIDGETS GTK3 ZLIB

**Comment by lebensterben** [comment]
similar issues had been reported on gitter channel.

possible cause is the latest commit which updates the quelpa package.

**Comment by ir210** [comment]
Here is the issue from the mainstream https://github.com/Malabarba/aggressive-indent-mode/issues/158

**Comment by lebensterben** [comment]
@ir210 

thanks!

**Comment by emacs18** [comment]
This should be marked as fixed now that upstream checked in the fix, i.e.,
https://github.com/Malabarba/aggressive-indent-mode/commit/f376cdc

**Comment by lebensterben** [comment]
thanks
