### ISSUE TITLE
helm-ag-edit replaces occurences of searched pattern with message [Omitted long matching line]

### ISSUE THREAD

**Issue by tomekowal** [syl20bnr/spacemacs#15777]
#### Description :octocat:
helm-ag (using ripgrep backend) displays `[Omitted long matching line]`
After hitting Ctrl-c Ctrl-e to helm-ag-edit, I still see the `[Omitted long matching line]`.
After hitting Ctrl-c Ctrl-c to finish editing the long lines are replaced in the source files
with the message `[Omitted long matching line]`

#### Reproduction guide :beetle:
- Start Emacs
- Edit a file to create a very long line
- Search for that line using SPC / and see the `[Omitted long matching line]` message
- Use Ctrl-c Ctrl-e to enter helm-ag-edit
- Do not edit anything
- Use Ctrl-c Ctrl-c to save changes (no real changes were made)

*Observed behaviour:* :eyes: :broken_heart:
- Actual line is substituted with text `[Omitted long matching line]`

*Expected behaviour:* :heart: :smile:
- No substitution should happen
Or alternatively
- helm-ag-edit should display the original long line instead of the long line message

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 264a8ffc2)
- Graphic display: nil
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(graphviz python haskell typescript yaml csv javascript rust purescript html erlang sql
          (elixir :variables elixir-backend 'lsp elixir-ls-path "/home/tomaszkowal/elixir-lsp/elixir-ls/release/")
          major-modes
          (ruby :variables ruby-backend 'robe)
          auto-completion better-defaults emacs-lisp git helm lsp dap markdown multiple-cursors
          (org :variables org-enable-roam-support t org-enable-roam-server t org-enable-roam-protocol t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'vterm)
          spell-checking syntax-checking version-control treemacs)
```
- System configuration features: CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XAW3D XDBE XIM XPM LUCID ZLIB

#### Backtrace :paw_prints:
```
not relevant
```

**Comment by BenedictHW** [comment]
Possible duplicate of https://github.com/syl20bnr/spacemacs/pull/10310 ?

**Comment by tomekowal** [comment]
I see it is related. My lines were longer than 512 characters (I've searched CSV exports).
For the "edit all" action in helm, it would be best to display complete lines even if they are omitted in the initial search, but I am not sure it is possible now in the helm project.
