### ISSUE TITLE
Spacemacs doesn't start because of melpa.org being down

### ISSUE THREAD

**Issue by tkossak** [syl20bnr/spacemacs#15774]
When I start specemacs, it hangs at `Contacting host: melpa.org:443`. The host is down currently (at least for me) but I would like to still use my spacemacs. How to prevent spacemacs from contacting melpa at startup?

**Comment by lebensterben** [comment]
remove it from package-archives

**Comment by tkossak** [comment]
I know I can do it with `M-x RET customize-variable` but how to do it when spacemacs doesn't start (because melpa is already down, or you don't have internet connection)?

**Comment by lebensterben** [comment]
manually edit your emacs custom file, or the last section of .spacemacs where all custom variables are set.
