### ISSUE TITLE
Symbol’s function definition is void: helm-mode--in-file-completion-p 

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#15783]
Directly after starting emacs I usually directly open a project with `SPC p l`.

Since this morning I get the following error:

```
progn: Symbol’s function definition is void: helm-mode--in-file-completion-p 
```

After I open a helm buffer with e.g. `SPC SPC` it suddenly works.

**Comment by jia-j-chen** [comment]
I have the same issue after I update spacemacs just now.

**Comment by sunlin7** [comment]
You have to upgrade the `helm` and `helm-core` packages together. 
https://github.com/emacs-helm/helm/commit/0211c57425bb989965419aeebb7dd52476fcb2b0

**Comment by jia-j-chen** [comment]
> You have to upgrade the `helm` and `helm-core` packages together. [emacs-helm/helm@0211c57](https://github.com/emacs-helm/helm/commit/0211c57425bb989965419aeebb7dd52476fcb2b0)

Thanks! How do I do that?

I update spacemacs with these steps:
1. `git pull` in folder ~/.emacs.d/
2. Open emacs and `SPC f e U`
3. Re-start emacs.

Should I do something else to upgrade `helm` and `helm-core` together?

**Comment by sunlin7** [comment]
It's helm-core-20221022.2056 in my local, you can check the version in your local.
And, you maybe need clear the *.elc for the helm in your local.

**Comment by gdkrmr** [comment]
It seems that the problem sorted itself out. Just upgrading all packages solved it for me.
