### ISSUE TITLE
Creating new YaSnippets

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1578]
I have tried to make a new YaSnippet doing the following : 

From within a (saved) file `test.py`

`M-x yas-new-snippet`

Snippet content : 

```text
# -*- mode: snippet -*-
# name: Test snippet for Spacemacs
# key: test
# --
this is a test
```
Then in the python file

```text
yas-recompile-all
yas-reload-all
```

After doing this and entering `test` I'm not able to use `<tab>` to expand the snippet. 

I am able to use pre existing snippets (ones that come with yasnippet (I tried `for`)), and I have tried restarting spacemacs. 

Would be cool to work this out, thanks

**Comment by jasoncyu** [comment]
@geo7 After you type out the snippet in your buffer what do you do? You *should* save the snippet with `C-c C-c`. After that command, yasnippet will prompt you for a place to save your snippet (picking your `yasnippet-dirs` by default).
