### ISSUE TITLE
[RFC] Projectile new command: `projectile-find-references`

### ISSUE THREAD

**Issue by pataquets** [syl20bnr/spacemacs#15789]
Projectile just got the command  `projectile-find-references` added recently:
https://github.com/bbatsov/projectile/commit/93c61a98f2ee983d856f1c419caea7fb2ab1ad19

Is this command worth adding to Spacemacs projectile keymap? I mean, will it be redundant or overlap with any other?
If it's deemed worth adding, bind suggestions are welcome and I'll try to add it.

**Comment by smile13241324** [comment]
Adding the new command would be a useful change, I would suggest to bind it to <kbd>SPC p E</kbd>. Please don't forget to document it in "DOCUMENTATION.org" see line 3669 for the table.
