### ISSUE TITLE
How to make spacemacs work offline? (in case of next melpa outage)

### ISSUE THREAD

**Issue by tkossak** [syl20bnr/spacemacs#15784]
So, last melpa outage showed me, that spacemacs seems to be always online app. When melpa goes down again (or whatever other host on the internet) is there anything I can do, to make my local spacemacs app work without other servers being online or even without internet?

One possible solution somebody suggested (and quickly closed the [ticket](https://github.com/syl20bnr/spacemacs/issues/15774)) is to remove melpa from `package-archives`. Can somebody explain to me, how I can do it when my spacemacs doesn't start at all? Are there any other solutions?

**Comment by lebensterben** [comment]
I replied to you in the original issue.

But in general, you should not ask any question by opening an issue.

Issues are for bug reports or feature requests.

Questions can be asked in discussion.

**Comment by tkossak** [comment]
Thank you, I'll use discussions next time.
