### ISSUE TITLE
push-button (widget) not working on mouse left click - Emacs 28.1 and Emacs 28.2

### ISSUE THREAD

**Issue by mrmodolo** [syl20bnr/spacemacs#15799]
#### Description :octocat:
push-button (widget) not working on mouse left click

#### Reproduction guide :beetle:
- Start Emacs
- On the opening screen, just click on any link whose widget is of the push-button type
- For example, the "Update Packages" push-button

*Observed behaviour:* :eyes: :broken_heart:
To make the push-button work, it is first necessary to select with the left mouse button and then click with the right mouse button.
Interestingly, url-link widgets work perfectly.

*Expected behaviour:* :heart: :smile:
Same behavior as Emacs 27.1.
I compiled Emacs 28.1 and 28.2 and both had the same problem.

```
export CC=/usr/bin/gcc-11 && export CXX=/usr/bin/gcc-11
export CFLAGS='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wall'
export CPPFLAGS='-Wdate-time -D_FORTIFY_SOURCE=2' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'
```

`./configure --with-pop=yes --with-sound=alsa --without-gconf --with-mailutils --with-pop=yes --with-sound=alsa --without-gconf --with-mailutils --with-x=yes --with-x-toolkit=gtk3 --with-toolkit-scroll-bars`

I copied the build options used by the Ubuntu distribution in Emacs 27.1

`M-x describe-variable RET system-configuration-options`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 0acf65c4c)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XAW3D XDBE XIM XPM LUCID ZLIB

**Comment by mrmodolo** [comment]
Hi!

If you're patient and click on several different locations closer together, at some point the left click works.
Today I tried to compile the Emacs version of git (29) and the behavior was the same.

**Comment by jleonard-r7** [comment]
Any progress on this? Would be nice to have clickable links on the start page again...

**Comment by mrmodolo** [comment]
I thought it could be a compilation error on my part, but after installing NixOS, which uses Emacs 8.0 by default, the problem was repeated. With some effort I managed to install version 7.2 and the operation returned to normal.

What is more strange is the fact that links and buttons in Emacs 8 without any configuration work without problem. The problem happens after installing Spacemacs.
