### ISSUE TITLE
Starting Emacs produces an error related to `evil-escape`.

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#15792]
#### Description :octocat:
Starting Emacs produces an error related to `evil-escape`.

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
![image](https://user-images.githubusercontent.com/94545627/199495771-2180a0f4-355e-4c32-ba80-9719de08dd71.png)
Emacs is unusable: when one tries to do a thing the minibuffer says
```
Cannot open load file: No such file or directory, evil-escape
```

*Expected behaviour:* :heart: :smile:
There are no errors.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 0acf65c4c)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS XWIDGETS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

**Comment by mrmodolo** [comment]
Hi!
I'm getting the same error on Ubuntu 22.04 with Emacas 27.1
It seems that evil-escape only supports Emacs 28.

You can force install with M-X package-install evil-escape, but when you update the packages the problem return.

**Comment by svenpanne** [comment]
Well, https://github.com/smile13241324/evil-escape/commit/0383191899ecc903d9d8db78096db506638ba2db effectively broke Spacemacs for all Emacs 27 users. The project doesn't even have an issue tracker. Can Spacemacs itself somehow fix this and/or pin the package to a prior version?

**Comment by svenpanne** [comment]
Quick hack: Edit `.emacs.d/.cache/quelpa/packages/evil-escape-20221101.203531.el` by hand, changing the `Package-Requires:`-line back to `emacs "27"`. This seems to unbreak Spacemacs for now, but is of course not a real solution.

**Comment by mrmodolo** [comment]
I tried compiling emacs 28 on Ubuntu. What happens is that the links on the Spacemacs splash page no longer work.

**Comment by srgkoshelev** [comment]
I'm getting the same error on 27.2. Emacs 28 seems to work but has issues with python :session which I need for my workflow.

Solution [above](https://github.com/syl20bnr/spacemacs/issues/15792#issuecomment-1302503156) seems to be working OK.

**Comment by svenpanne** [comment]
https://github.com/smile13241324/evil-escape/commit/3b6983686aa1a1ae973f45185fca3de7f5ad1f24 has fixed this, so updating the packages will make the problem go away.

I think this issue can be closed.
