### ISSUE TITLE
ycmd completion unavailable while parsing is in progress

### ISSUE THREAD

**Issue by eyesfrog** [syl20bnr/spacemacs#1581]
![image](https://cloud.githubusercontent.com/assets/7132922/7588764/b30f9b80-f8f1-11e4-8dac-e85a00098068.png)

As the screenshots shows.

**Comment by syl20bnr** [comment]
Seems not related to spacemacs config, I looked a bit upsteam and found this: https://github.com/abingham/emacs-ycmd/issues/121
