### ISSUE TITLE
buffer-menu-mode doesn´t work

### ISSUE THREAD

**Issue by rcdeoliveira** [syl20bnr/spacemacs#15811]
#### buffer-menu-mode doesn´t work

I want to use buffer-menu but when I try to it with `buffer-menu-mode` the current buffer
remains with weird behavior

#### Reproduction guide :beetle:
- Start Emacs
- Call `buffer-menu-mode`

*Expected behaviour:* :heart: :smile:

Get buffer menu as shown in https://www.emacswiki.org/emacs/BufferMenu

#### System Info :computer:
- OS: gnu/linux
- Emacs: 27.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 0acf65c4c)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git helm lsp markdown multiple-cursors terraform python treemacs themes-megapack)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by alexey0308** [comment]
You probably want to use `buffer-menu` rather than `buffer-menu-mode` command. The latter activates the buffer-menu-mode in the current buffer and it is expected.

**Comment by rcdeoliveira-awaytravel** [comment]
> You probably want to use `buffer-menu` rather than `buffer-menu-mode` command. The latter activates the buffer-menu-mode in the current buffer and it is expected.

That worked, thanks.
