### ISSUE TITLE
Feature Request: Mastodon Layer

### ISSUE THREAD

**Issue by rommeswi** [syl20bnr/spacemacs#15830]
With the impending/surmised demise of twitter there is currently much interest in the decentralized open source alternative to twitter, mastodon. For example, there is an [emacs mastodon server](https://emacs.ch).

There is a spacemacs layer [here](https://github.com/ksonney/spacemacs-mastodon) and emacs package for mastodon [here](https://codeberg.org/martianh/mastodon.el). I find that there are still things that can be improved on the layer to make it useful for spacemacs users (for example evilification?).

**Comment by ghost** [comment]
I agree, considering Mastodon's popularity now (and the Mastodon package being relatively stable, imo at least), it's a worthwhile addition to the current layers. Especially because we already have a Twitter, a Reddit and a Hacker News layer.
