### ISSUE TITLE
tree-sitter layer auto-loading doesn't work correctly

### ISSUE THREAD

**Issue by seriousbusinessuser** [syl20bnr/spacemacs#15835]
#### Description :octocat:
`tree-sitter` layer's auto-loading doesn't seem to be functioning properly. I managed to work around this issue by commenting out `:defer t` in `tree-sitter/init-tree-sitter` function or by evaluating `(global-tree-sitter-mode)` two times - it thinks it's enabled but it's not, at least not completely.

#### Reproduction guide :beetle:
- Start Emacs
- Either open some `tree-sitter` supported file with code or try to eval `tree-sitter-major-mode-language-alist`.

*Observed behaviour:* :eyes: :broken_heart:
`tree-sitter` mode isn't loaded / `tree-sitter-major-mode-language-alist` is undefined.

*Expected behaviour:* :heart: :smile:
`tree-sitter` mode is loaded / `tree-sitter-major-mode-language-alist` defined.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. be9b1c89b)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(better-defaults emacs-lisp git helm markdown multiple-cursors spell-checking syntax-checking tree-sitter)
```
- System configuration features: CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XAW3D XDBE XIM XPM LUCID ZLIB

**Comment by sid-kap** [comment]
This is still a problem, it happens to me every day

**Comment by smile13241324** [comment]
I'll have a look

**Comment by sid-kap** [comment]
Thank you so much!!
