### ISSUE TITLE
No diagnostics and treemacs error list not updating

### ISSUE THREAD

**Issue by JoshTRN** [syl20bnr/spacemacs#15842]
#### Description :octocat:
I've been having issues with vue lsp and I've been in contact with the volar dev (who merged his code into lsp-mode). He concluded that the issue was with is with configuration as DOOM Emacs seems to work with his configuration. I'm going to link the issue because it's described in more detail and there's a whole thread of questions and responses when I posted the issue in the lsp mode repo. [No diagnostics and error list not updating](https://github.com/emacs-lsp/lsp-mode/issues/3830). Note: The issue is closed because the volar dev concluded that this is a configuration error. 

#### Reproduction guide :beetle:
- Start Emacs
1. Create a vite project with vue (and typescript although I suspect typescript isn't directly relevant) `yarn create vite`
2. `M-x lsp-install-server RET vue-semantic-server RET` (must have latest lsp installed)
3. Enter Project so `lsp-mode` starts.
4. Edit project creating lsp error

*Observed behaviour:* :eyes: :broken_heart:
Diagnostics do not appear and treemacs error list does not reflect the errors accurately.

*Expected behaviour:* :heart: :smile:
Diagnostics should appear and treemacs error list should reflect the errors accurately.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. be9b1c89b)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 better-defaults dap debug docker eaf elm
 (elm :variables elm-format-on-save t elm-sort-imports-on-save t)
 unicode-fonts
 (unicode-fonts :variables unicode-fonts-enable-ligatures t)
 emacs-lisp eww pandoc
 (vue :variables vue-backend 'lsp)
 git
 (go :variables go-backend 'lsp go-tab-width 2)
 tree-sitter
 (tree-sitter :variables)
 html
 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp")
 haskell helm java javascript
 (javascript :variables js2-mode-show-strict-warnings nil)
 kubernetes lsp markdown multiple-cursors nixos org
 (org :variables org-enable-verb-support t org-enable-transclusion-support t org-enable-appear-support t org-enable-valign t org-enable-epub-support t org-enable-roam-protocol t org-enable-roam-ui t org-enable-roam-support t)
 prettier search-engine shell-scripts
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-vterm)
 slack spell-checking syntax-checking
 (typescript :variables javascript-backend 'lsp typescript-fmt-tool 'typescript-formatter typescript-fmt-on-save t typescript-backend 'lsp typescript-tsx-mode t typescript-linter 'tslint)
 terraform themes-megapack treemacs version-control yaml)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBSYSTEMD LIBXML2 MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

**Comment by smile13241324** [comment]
Thanks for reporting the issue, I will have a look into it. In general it looks like the linters are not properly set, according to your diagnostic settings in the linked issue. I have also noticed that vue layer seems to be pretty old and needs an update i.e. current documentation only suggests lsp modes for vue2.

I keep you posted.

**Comment by JoshTRN** [comment]
I found the bug for flycheck @smile13241324. I haven't had the chance to put in a PR yet, but insofar as treemacs error list not updating is concerned, I haven't figured that out, nor even really looked into it at all.

**Comment by smile13241324** [comment]
I have noticed that too with the python layer, I am pretty sure there is something wrong with the lsp-treemacs plugin but I had not yet have the time to investigate. Anyway the vue layer lsp setup is creative to say the least so I am going to revise this anyway.

By the way I have noticed the layer is hard coding eslint as linter ignoring all diagnostics from lsp claiming the results are not usable, is this still the case? Right now I would like to move this setting behind a switch which is off by default.

**Comment by JoshTRN** [comment]
I agree. I think the default should be lsp if you set your backend to lsp and don't specify that you want a different flychecker. That's what I coded anyway.

Btw, I couldn't get eslint to work with my system to save my life.

**Comment by smile13241324** [comment]
I am sorry to hear that :( anyway let me sort this out I am sure I will get this to work. Once I have a stable version on my branch would you mind having a look at it and post how it performs after the changes?

**Comment by smile13241324** [comment]
I have finished the commit in this branch https://github.com/syl20bnr/spacemacs/tree/vue-update, care to see how it works on your side?

**Comment by JoshTRN** [comment]
Everything works great on my end! But I think you should change the comments to reflect the change in this file on lines 46 and 47:
https://github.com/syl20bnr/spacemacs/blob/f30c1943c037ea67bfcecaf167a30f2a1cb84b38/layers/%2Bframeworks/vue/funcs.el#L46

**Comment by smile13241324** [comment]
Thanks for the feedback I have adapted my comments and merged my changes. I have also had a look at your issues with lsp-treemacs, however these seems to be gone after updating my packages. Can you update your Spacemacs and packages and tell me whether the issue persists?

**Comment by smile13241324** [comment]
This should be gone please reopen if it isn't.
