### ISSUE TITLE
ipython check in python layer is not robust

### ISSUE THREAD

**Issue by emacs18** [syl20bnr/spacemacs#15847]
The `python` layer has the following code to setup `python-shell-interpreter` variable.

    (defun spacemacs//python-setup-shell (&rest args)
      (if (spacemacs/pyenv-executable-find "ipython")
          (progn
            (setq python-shell-interpreter "ipython")
            (let ((version (replace-regexp-in-string "\\(\\.dev\\)?[\r\n|\n]$" ""
                                                     (shell-command-to-string
                                                      (format "\"%s\" --version"
                                                              (string-trim (spacemacs/pyenv-executable-find "ipython")))))))
              (if (or (version< version "5")
                      (string-blank-p version))
                  (setq python-shell-interpreter-args "-i")
                (setq python-shell-interpreter-args "--simple-prompt -i"))))
        (progn
          (setq python-shell-interpreter-args "-i"
                python-shell-interpreter "python"))))

The problem with this code is that it seems to assume that virtual environments do not exist, i.e., `python-shell-interpreter` is set to be `"ipython"` when it may not exist in some python virtual environments which may be selected later on.

My initial python environment may have `ipython`, but when I later switch to another virtual python environment, then there is no guarantee that `ipython` exist. Thus many python related features such as name completions, jump-to-definition, etc. may not work reliably since `ipython` from my first virtual environment may be trying to provide information for a completely different python environment currently in use.

I think the check for `ipython` in the code shown above should be either removed or fenced with a user option, so that I can make sure that `python-shell-interpreter` is always `"python"` which will work for all virtual environments.

**Comment by sunlin7** [comment]
I have the enhancement in my local, for a while. I'll pull the change for review today.

**Comment by emacs18** [comment]
After learning a bit more about how spacemacs setup things, it could be that the problem was my error.  It appears that spacemacs has the proper hooks to call `spacemacs//python-setup-shell` when virtual environment is changed.  For example `python/init-pyenv` advises `pyvenv-activate` so that `spacemacs/python-setup-everything` is called afterwards.  This in turn calls `spacemacs//python-setup-shell`.  Thus my user error may have been that I changed python environments without going through spacemacs supported methods.

**Comment by smile13241324** [comment]
I have merged the enhancements from @sunlin7's branch, please give it a try @emacs18

**Comment by smile13241324** [comment]
I think this is fixed, please reopen if not. Thanks.
