### ISSUE TITLE
How to keep position and size of spacemacs window after last used?

### ISSUE THREAD

**Issue by WallaceYYLi** [syl20bnr/spacemacs#1585]
I want to record spacemacs window position and size.

**Comment by syl20bnr** [comment]
There is no official support for persistent sessions in spacemacs right now. You can try to use [desktop.el](http://www.emacswiki.org/emacs?action=browse;oldid=DeskTop;id=Desktop) to achieve this. You can enable it in your `dotspacemacs/config` function of `~/.spacemacs`.

**Comment by johanatan** [comment]
Is there anything better than desktop.el to support this nowadays? Also, seems more like a feature request than a 'question' (although it was worded as a question).

**Comment by nixmaniack** [comment]
@johanatan You can checkout `spacemacs-layouts` which support this functionality.
