### ISSUE TITLE
Can't activate virutalenv: 'Wrong type argument: listp, "/home/itamarst/venv"'

### ISSUE THREAD

**Issue by itamarst** [syl20bnr/spacemacs#15852]
#### Description :octocat:
Can't activate a virtualenv anymore

#### Reproduction guide :beetle:
- Start Emacs
- Open a Python file
- SPC m v a
- Choose a directory that is a virtualenv

I was able to reproduce with completely regenerated `.spacemacs`.

*Observed behaviour:* :eyes: :broken_heart:

An error occurs:
spacemacs/python-setup-everything: Wrong type argument: listp, "/path/to/my/virtualenv/"

*Expected behaviour:* :heart: :smile:
Virtualenv should activate.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. f1c7979b6)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((sql :variables sql-backend 'lsp)
 csv windows-scripts ruby auto-completion better-defaults emacs-lisp git helm markdown
 (rust :variables rust-backend 'lsp lsp-rust-server 'rust-analyzer)
 treemacs
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'vterm)
 (spell-checking :variables spell-checking-enable-by-default nil)
 (syntax-checking :variables syntax-checking-enable-tooltips nil)
 (version-control :variables version-control-diff-tool 'diff-hl version-control-diff-side 'left)
 (python :variables python-formatter 'black python-backend 'lsp python-test-runner 'pytest pyvenv-tracking-mode nil)
 javascript yaml shell-scripts
 (go :variables gofmt-command "goimports")
 c-c++
 (html :variables html-enable-lsp nil)
 org docker deft dap lsp ipython-notebook spacemacs-purpose dash
 (languagetool :variables langtool-default-language "en-US" langtool-language-tool-jar "/home/itamarst/apps/LanguageTool-5.8/languagetool-commandline.jar"))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by itamarst** [comment]
This appears to be due to recent commit 3afc9afa4cd113f1bafee74c4ecf04af58b20372 (FYI @sunlin7), if I revert it the problem goes away.

**Comment by sunlin7** [comment]
Hi @itamarst 
I can reproduce it, will update minutes later.

**Comment by sunlin7** [comment]
The #15853 will fix this issue.
And the https://github.com/syl20bnr/spacemacs/commit/3afc9afa4cd113f1bafee74c4ecf04af58b20372 improve the startup speed a lot.

**Comment by itamarst** [comment]
Thank you!

**Comment by itamarst** [comment]
Fixed, thank you.
