### ISSUE TITLE
DAP Locals wont stay unfolded and then hangs Emacs if you try to reopen it

### ISSUE THREAD

**Issue by stevenhay** [syl20bnr/spacemacs#15850]
#### Description :octocat:
DAP locals resets to folded after each debug step, then hangs emacs if you try to re-open it

#### Reproduction guide :beetle:
- Start Emacs
- Load a Java project
- Set a breakpoint
- Start debugging
- Open 'Locals' fold to see local variables
- Step over breakpoint, notice 'Locals' folds itself again
- Attempt to re-open 'Locals' either using mouse or keyboard
- Emacs hangs and the terminal must be restarted

*Observed behaviour:* :eyes: :broken_heart:
DAP 'Locals' folds itself after every single step over after hitting a breakpoint and then hands emacs

*Expected behaviour:* :heart: :smile:
'Locals' should stay open once unfolded, and definitely should not hang emacs if you try to re-open it

#### System Info :computer:
- OS: darwin
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. f1c7979b6)
- Graphic display: nil
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp java dap helm multiple-cursors treemacs)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE PDUMPER THREADS ZLIB

**Comment by nvhai245** [comment]
I'm having the same issue with dap-go

**Comment by smile13241324** [comment]
dap mode or lsp mode issue please report to upstream
