### ISSUE TITLE
Warning: (...) :foreground of face (...) nil value is invalid

### ISSUE THREAD

**Issue by real-or-random** [syl20bnr/spacemacs#15862]
#### Description :octocat:
I see a lot of warnings like
```
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-insert-face’: nil value is invalid, use ‘unspecified’ instead.
```
(see below for full list)

`git grep :foreground nil` and `git grep :background nil` give me a few instances but none of these seem to be relevant to the warnings. (These instances should probably be fixed nevertheless but that's a different issue.) 

#### Reproduction guide :beetle:
- Start Emacs
- Open a new frame

*Observed behaviour:* :eyes: :broken_heart:
```
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-iedit-insert-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-iedit-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-lisp-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-motion-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-visual-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-evilified-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-replace-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-hybrid-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-emacs-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-insert-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-normal-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-iedit-insert-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-iedit-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-lisp-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-motion-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-visual-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-evilified-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-replace-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-hybrid-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-emacs-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-insert-face’: nil value is invalid, use ‘unspecified’ instead.
Warning: setting attribute ‘:foreground’ of face ‘spacemacs-normal-face’: nil value is invalid, use ‘unspecified’ instead.
```

*Expected behaviour:* :heart: :smile:
No warnings

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.0.60
- Spacemacs: 0.999.0
- Spacemacs branch: nil (rev. 025e9f7e3)
- Graphic display: t
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(better-defaults
 (unicode-fonts :variables unicode-fonts-enable-ligatures t unicode-fonts-ligature-modes
                '(prog-mode text-mode)
                unicode-fonts-ligature-set
                '("<---" "<--" "<<-" "<-" "->" "-->" "--->" "<->" "<-->" "<--->" "<---->" "<!--" "<==" "<===" "<=" "=>" "=>>" "==>" "===>" ">=" "<=>" "<==>" "<===>" "<====>" "<!---" "<~~" "<~" "~>" "~~>" "::" ":::" "==" "!=" "===" "!==" ":=" ":-" ":+" "<*" "<*>" "*>" "<|" "<|>" "|>" "+:" "-:" "=:" "<******>" "++" "+++"))
 theming
 (ivy :variables ivy-enable-advanced-buffer-information t)
 (auto-completion :disabled-for org)
 spell-checking syntax-checking treemacs shell
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (org :variables org-enable-github-support t org-enable-roam-support t org-enable-roam-ui t org-enable-sticky-header t org-want-todo-bindings t)
 deft
 (latex :variables latex-enable-auto-fill nil lsp-headerline-breadcrumb-enable nil lsp-enable-imenu nil lsp-ui-doc-enable nil lsp-eldoc-enable-hover nil)
 bibtex
 (languagetool :variables langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*")
 (lsp :variables lsp-rust-server 'rust-analyzer lsp-enable-indentation nil lsp-enable-on-type-formatting nil)
 (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-lsp-enable-semantic-highlight t lsp-lens-enable nil)
 ansible csv html
 (shell-scripts :variables shell-scripts-backend nil)
 javascript systemd emacs-lisp git
 (version-control :variables version-control-diff-side 'left)
 markdown major-modes yaml lua rust php python)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM GTK3 ZLIB

**Comment by real-or-random** [comment]
> Emacs: 29.0.60

see
https://github.com/emacs-mirror/emacs/commit/824a139434855919073d6ea3c93d57ebd24fc75c

**Comment by lebensterben** [comment]
what theme are you using

**Comment by real-or-random** [comment]
Oh yes, I should have included that information.

 I use `solarized-light`.

```
   dotspacemacs-additional-packages '( [...]  (solarized-theme) [...] )
```

```
   dotspacemacs-themes '(solarized-light solarized-dark)
```


<details>
<summary>Some modification (I don't think they're relevant but leaving here for completeness)</summary>

```
  (setq solarized-use-variable-pitch nil)
  (setq x-underline-at-descent-line t)
  (setq solarized-scale-org-headlines nil)
  (setq-default theming-modifications '(
    (solarized-light
     (mode-line :box nil)
     (mode-line-inactive :box nil)
     (spacemacs-mode-line-new-version-lighter-warning-face :box nil)
     (spacemacs-mode-line-new-version-lighter-error-face :box nil)
     (spacemacs-mode-line-new-version-lighter-success-face :box nil)
     (highlight-parentheses-highlight :weight ultra-bold)
     ;; because the underline isn't nice with the org category icons
     (ivy-current-match :underline nil)
     ;; only set line number background to a different color, not fringe
     (linum :weight extra-light :background "#EEE8D5")
     (line-number :weight extra-light :background "#EEE8D5")
    )
    (solarized-dark
     (mode-line :box nil)
     (mode-line-inactive :box nil)
     (spacemacs-mode-line-new-version-lighter-warning-face :box nil)
     (spacemacs-mode-line-new-version-lighter-error-face :box nil)
     (spacemacs-mode-line-new-version-lighter-success-face :box nil)
     (highlight-parentheses-highlight :weight ultra-bold)
     (linum :weight extra-light)
     (line-number :weight extra-light)
    )
   ))
```
</details>

**Comment by lebensterben** [comment]
Can you first try:

on https://github.com/syl20bnr/spacemacs/blob/a46e7ce022cd43cab23b475cfec58b60ffe4e8d7/layers/%2Bdistributions/spacemacs-bootstrap/funcs.el#L73
change `'mode-line` to `mode-line`

restart. if this doesn't help, then

on https://github.com/syl20bnr/spacemacs/blob/a46e7ce022cd43cab23b475cfec58b60ffe4e8d7/layers/%2Bdistributions/spacemacs-bootstrap/funcs.el#L72
change

`,(face-background 'mode-line)` to `,(or (face-background 'mode-line) 'unspecified)`

**Comment by real-or-random** [comment]
Thanks, that was the right direction.

This makes the warnings disappear:
https://github.com/real-or-random/spacemacs/commit/61dbfe2857956aa6e6f50428ba522a9a25895f8e

But see https://github.com/emacs-mirror/emacs/commit/824a139434855919073d6ea3c93d57ebd24fc75c, which was the result of  https://debbugs.gnu.org/cgi/bugreport.cgi?bug=51595. Does that mean we better don't specify `:foreground` at all?

**Comment by lebensterben** [comment]
> Apart from the values given below, each face attribute can have the value unspecified. This special value means that the face doesn’t specify that attribute directly. An unspecified attribute tells Emacs to refer instead to a parent face (see the description :inherit attribute below); or, failing that, to an underlying face (see Displaying Faces). The default face must specify all attributes.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html

Only the **default** face needs to specify all attributes.

( And I do believe you also need to change from 'mode-line to mode-line )

**Comment by real-or-random** [comment]
> > Apart from the values given below, each face attribute can have the value unspecified. This special value means that the face doesn’t specify that attribute directly. An unspecified attribute tells Emacs to refer instead to a parent face (see the description :inherit attribute below); or, failing that, to an underlying face (see Displaying Faces). The default face must specify all attributes.
> 
> [gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html](https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html)
> 
> Only the **default** face needs to specify all attributes.

https://github.com/emacs-mirror/emacs/commit/824a139434855919073d6ea3c93d57ebd24fc75c updates exactly this paragraph and adds: `(However, @code{unspecified} is not a valid value in @code{defface}.)` The maintainer says in https://debbugs.gnu.org/cgi/bugreport.cgi?bug=51595 that " Using 'unspecified' in user code is an error. "

> ( And I do believe you also need to change from 'mode-line to mode-line )

ok, that one didn't make an observable difference in my testing

**Comment by lebensterben** [comment]
> ok, that one didn't make an observable difference in my testing

if you try to (describe-face spacemacs-insert-face) for example, you will see the inherit field wrongly points to an unidentified symbol "'mode-line" before this change.

**Comment by real-or-random** [comment]
see also https://github.com/nashamri/spacemacs-theme/pull/200/files

**Comment by tokisuno** [comment]
I'm on timu-rouge and I am getting this
