### ISSUE TITLE
How change the default split window orientation when using magit

### ISSUE THREAD

**Issue by jackgris** [syl20bnr/spacemacs#15884]
After one update when every time I open magit to see the status of my project, this split the window horizontally. 
Before when magit opened the new frame vertically, I felt more comfortable that way.

I can't find a way to change that default behavior at least in the git layer documentation.

**Comment by lebensterben** [comment]
you can use git bisect to find the commit that introduced the change

**Comment by jackgris** [comment]
Ok, thanks Lucius for your answer. I'll try to find it.

**Comment by jackgris** [comment]
At least for now, I ended up using this: 
(setq split-width-threshold 1 ) in my dotspacemacs/user-config
