### ISSUE TITLE
Code layout is totally broken when using LSP in no-window mode

### ISSUE THREAD

**Issue by radrow** [syl20bnr/spacemacs#15889]
#### Description :octocat:
Code layout is totally broken when using LSP in -nw mode.

A preview can be seen under this [asciinema link](https://asciinema.org/a/551217). I used emacsclient there, but it reproduces the same way with `emacs -nw`. 

#### Reproduction guide :beetle:
- Install LSP-using layer (erlang or rust in my case)
- Launch spacemacs in no-window mode
- Open a file in a project (so that LSP interface is used)

*Observed behaviour:* :eyes: :broken_heart:
The interface is mashed with the content of the file. Some lines are
duplicated, some are missing, some are just empty. Moving cursor up
and down mixes the mess around, so some lines become visible, some not,
some move around. Generally the line where the cursor is seems to be
displayed correctly, interestingly.

*Expected behaviour:* :heart: :smile:
File is displayed normally. The LSP interface does not interfere with
the content.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. fb3b56616)
- Graphic display: nil
- Running in daemon: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(windows-scripts better-defaults themes-megapack docker sql javascript html elm
                 (solidity :variables solidity-flycheck-solc-checker-active t)
                 ruby python
                 (erlang :variables erlang-backend 'lsp)
                 elixir octave
                 (scala :variables scala-backend 'scala-metals)
                 yaml csv markdown org pdf
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (rust :variables rust-backend 'lsp)
                 asm
                 (c-c++ :variables c-c++-backend 'lsp-clangd c-c++-enable-clang-support t c-c++-enable-clang-format-on-save nil)
                 coq
                 (haskell :variables haskell-enable-hindent t haskell-completion-backend 'dante haskell-enable-hindent-style "johan-tibell")
                 emacs-lisp prolog bibtex
                 (latex :variables latex-backend 'LSP latex-build-command "LaTeX" latex-enable-auto-fill t latex-enable-magic t latex-refresh-preview t latex-enable-folding t)
                 dap semantic syntax-checking
                 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup nil auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior nil auto-completion-idle-delay nil :disabled-for org erc)
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 (languagetool :variables langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*"))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by lebensterben** [comment]
what's the terminal emulator you are using?

**Comment by radrow** [comment]
Konsole and terminator

**Comment by lebensterben** [comment]
I cannot reproduce this behavior.

**Comment by lebensterben** [comment]
try

https://github.com/emacs-lsp/lsp-docker#spacemacs

**Comment by radrow** [comment]
Retried without font ligatures, but no success (it's a single window):
![image](https://user-images.githubusercontent.com/35342116/212277730-231de312-92bb-45e3-9cc4-7efb49210373.png)

**Comment by lebensterben** [comment]
please try the docker image.

btw, if you use Konsole, you should set TERM to konsole-direct or konsole-256

**Comment by radrow** [comment]
Okay, it turns out that it was indeed wrong font configuration. When I obliterated fira code from my config it just started to work. Thank you for your suggestions anyway!
