### ISSUE TITLE
error when installing some packages 

### ISSUE THREAD

**Issue by winsphinx** [syl20bnr/spacemacs#15893]
While installing some packages, it fails as below:
```
(Spacemacs) --> installing package: inspector@emacs-lisp... [6/11]
(Spacemacs) Error: 
An error occurred while installing inspector (error: (end-of-file c:/Users/***/.emacs.d/init.el))
```
But the same config files in other PC works well. I don't have any mind.

**Comment by lebensterben** [comment]
Can you run "emacs --debug-init"

**Comment by winsphinx** [comment]
That log is from `emacs --debug-init`.
![image](https://user-images.githubusercontent.com/5674054/213390698-8ef0356e-cf30-4c43-ad3b-18a20e38210e.png)

**Comment by lebensterben** [comment]
make sure your emacs has access to github

**Comment by winsphinx** [comment]
surely. for most others packages can be installed correctly.

**Comment by lebensterben** [comment]
other packages are not installed from GitHub

**Comment by winsphinx** [comment]
some of them are also from Github, which are stored in `.cache\quelpa\`. such as `font-lock+`, `ligature`, etc.

**Comment by lebensterben** [comment]
try to delete them from you elpa/develop/<emacs-version>/ and probably also from your quelpa cache. let's see whether emacs is able to install them.

**Comment by winsphinx** [comment]
After I cleaned up them and restarted emacs, it works. 
Thanks a lot!
