### ISSUE TITLE
org layer no longer working emacs 28.2 + recent spacemacs

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#15897]
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>
Clean install of spacemacs, add org layer
invalid-function: org-assertion-version

I had to go back to older version to get org-mode to work again.

Tried several times and failed each time (emacs 28.2):
1. Install .emacs.d and delete .spacemacs
Add org layer, then there is a failure and org-mode does not work
<<BE AWARE YOU NEED A GITHUB ACCOUNT TO SEND THIS REPORT>>

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. d08822c61)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Duplicated.

See https://github.com/syl20bnr/spacemacs/issues/15896

**Comment by ghost** [comment]
thanks!
