### ISSUE TITLE
error in process filter: magit-blame--format-time-string: Symbol’s function definition is void: string-search

### ISSUE THREAD

**Issue by RCoeurjoly** [syl20bnr/spacemacs#15892]
#### Description :octocat:
When executing magit-blame, nothing happens

#### Reproduction guide :beetle:
- Start Emacs
- Go to a file under git
- M-x magit-blame

*Observed behaviour:* :eyes: :broken_heart:
Nothing happens, in the Messages buffer I see many lines like this:
error in process filter: magit-blame--format-time-string: Symbol’s function definition is void: string-search
error in process filter: Symbol’s function definition is void: string-search

*Expected behaviour:* :heart: :smile:
I see the commits info in the file.

<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 9e3fc598a)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(protobuf php sml javascript rust lua d
          (c-c++ :variables c-c++-enable-clang-support t)
          haskell lua html python imenu-list shell-scripts
          (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
          yaml ruby
          (helm :variables history-delete-duplicates t)
          better-defaults sql semantic cscope csv syntax-checking emacs-lisp git gtags ess
          (colors :variables colors-enable-nyan-cat-progress-bar t)
          markdown
          (org :variables org-enable-roam-support t)
          spell-checking github version-control cucumber docker coq ocaml go elixir nixos)
```
- System configuration features: XPM JPEG TIFF GIF PNG CAIRO SOUND GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS GTK2 X11 XDBE XIM MODULES THREADS JSON PDUMPER GMP

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by alexey0308** [comment]
Hi @RCoeurjoly, it looks like you have to try with a newer version of emacs, because this function was introduced only in 28.1, search [here](https://www.gnu.org/software/emacs/news/NEWS.28.1) for the `string-search`.

**Comment by lebensterben** [comment]
see solution above.

also this is not our bug. you should report it to magit.
