### ISSUE TITLE
Issue with clangd in ubuntu

### ISSUE THREAD

**Issue by xyderos** [syl20bnr/spacemacs#15909]
Hi!

I am having an issue with clangd for cpp in spacemacs. I have sucessfully installed clangd locally via snap but for some reason spacemacs downloaded its own version of clangd under .emacs.d/.cache/... .I believe that due to that, I get errors like undefined headers eg <string> <iostream> although they compile. I am assuming that since spacemacs is "looking" at the wrong executable that itself downloaded, I should make it to point to the default one provided by snap. Does anyone know how to do that? Anyone had a similar issue?

**Comment by lebensterben** [comment]
> I have sucessfully installed clangd locally via snap

Is it visible from Emacs?

> I believe that due to that, I get errors like undefined headers eg although they compile.

Nope. You need to set up comile flags.

See https://clangd.llvm.org/design/compile-commands#where-do-compile-commands-come-from

**Comment by xyderos** [comment]
> Is it visible from Emacs?

Probably yes, it is exported to path so I am assuming that it is, although when I tried to use the one from snap it would never be initialised, only when I installed it locally at .emacs.d/.cache/...

> Nope. You need to set up comile flags.

I can definitely check it out! (edit sorry for the previous reply, apparently clangd from snap is behaving differently from the one from apt, the apt one works)

**Comment by lebensterben** [comment]
1. It's in PATH but Spacemacs uses .spacemacs.env to handle environment variable which is not automatically updated. You need to check whether conda is in the PATH there.

2. No. It's all manual.

**Comment by xyderos** [comment]
> 1. It's in PATH but Spacemacs uses .spacemacs.env to handle environment variable which is not automatically updated. You need to check whether conda is in the PATH there.
> 
>     2. No. It's all manual.

Thank you for your time! I will check out the compile commands!

**Comment by ccruquan** [comment]
You can use [bear](https://github.com/rizsotto/Bear) for generate `compile_commands.json`
