### ISSUE TITLE
Recent Files do not work on fresh install

### ISSUE THREAD

**Issue by rromoli** [syl20bnr/spacemacs#15901]
#### Description :octocat:
Recent` Files do not work on fresh install

#### Reproduction guide :beetle:
- Start Emacs
- Open several files, close Spacemacs and open it again and no recent files list is present. Do it several time but nothing changes. I see that .emacs.d/cache/recentf is present and polulated with the files I opened but it is not visualized in the home buffer.

*Observed behaviour:* :eyes: :broken_heart:
No recent files list present

*Expected behaviour:* :heart: :smile:
List of recently viewed files to be populated

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 58a52ae6e)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM XWIDGETS GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
Go to home buffer and SPC b d.
Then SPC b h.
Does it appear?

**Comment by rromoli** [comment]
No, it doesn't appear.

**Comment by emacs18** [comment]
Using vanilla spacemacs files (i.e., without making any changes whatsoever to any files), I too see this behavior.
`*spacemacs*` buffer does not show recent files.  Typing `SPC b d` followed by `SPC b h` does not show recent files.
However if now do `M-x load-library` followed with `org` so that org mode is loaded, then subsequent `SPC b d` followed by `SPC b h` shows recent files.

Thus displaying of recent files seems to require org mode to be loaded.

**Comment by emacs18** [comment]
I was using few days old emacs 29 on ubuntu.

**Comment by emacs18** [comment]
I narrowed this down further to `org-directory`.  If this is set to any path, then recent files show up.  My analysis of the code in `spacemacs-buffer//insert-recent-files` follows as to the root cause of this.

When `org-directory` is not set, then `ignore-directory` is set to empty string.
Later `(string-prefix-p ignore-directory full-path)` evaluates to `non-nil` regardless of what `full-path` is.
Hence all files are filtered out.

Following could be a potential fix.
```diff
diff --git a/core/core-spacemacs-buffer.el b/core/core-spacemacs-buffer.el
index 13ac69b79..f266b7d2a 100644
--- a/core/core-spacemacs-buffer.el
+++ b/core/core-spacemacs-buffer.el
@@ -1307,7 +1307,7 @@ startup list.")
         ;; we also need to skip sub-directories of `org-directory'
         (ignore-directory (or (when (bound-and-true-p org-directory)
                                 (expand-file-name org-directory))
-                              ""))
+                              "/tmp"))
         (recent-files-list))
     (cl-loop for rfile in recentf-list
              while (> list-size 0)
```

**Comment by lebensterben** [comment]
> Later (string-prefix-p ignore-directory full-path) evaluates to non-nil regardless of what full-path is.

Instead of changing it to `/tmp`, I think we should change this test so that it checks whether ignore directory is empty first.

(or better, make ignore directory nil if org-directory is not available)

**Comment by emacs18** [comment]
You mean something like this?

```diff
diff --git a/core/core-spacemacs-buffer.el b/core/core-spacemacs-buffer.el
index 13ac69b79..027434f30 100644
--- a/core/core-spacemacs-buffer.el
+++ b/core/core-spacemacs-buffer.el
@@ -1312,7 +1312,8 @@ startup list.")
     (cl-loop for rfile in recentf-list
              while (> list-size 0)
              do (let ((full-path (expand-file-name rfile)))
-                  (unless (or (string-prefix-p ignore-directory full-path)
+                  (unless (or (and (not (string-empty-p ignore-directory))
+                                   (string-prefix-p ignore-directory full-path))
                               (member full-path agenda-files))
                     (cl-pushnew rfile recent-files-list)
                     (setq list-size (1- list-size))))
```

**Comment by lebensterben** [comment]
@emacs18 yes

（but it's even better if we set it to nil in the first place)

**Comment by emacs18** [comment]
You mean this?

```diff
diff --git a/core/core-spacemacs-buffer.el b/core/core-spacemacs-buffer.el
index 13ac69b79..4ea4b4d1d 100644
--- a/core/core-spacemacs-buffer.el
+++ b/core/core-spacemacs-buffer.el
@@ -1307,12 +1307,13 @@ startup list.")
         ;; we also need to skip sub-directories of `org-directory'
         (ignore-directory (or (when (bound-and-true-p org-directory)
                                 (expand-file-name org-directory))
-                              ""))
+                              nil))
         (recent-files-list))
     (cl-loop for rfile in recentf-list
              while (> list-size 0)
              do (let ((full-path (expand-file-name rfile)))
-                  (unless (or (string-prefix-p ignore-directory full-path)
+                  (unless (or (and ignore-directory
+                                   (string-prefix-p ignore-directory full-path))
                               (member full-path agenda-files))
                     (cl-pushnew rfile recent-files-list)
                     (setq list-size (1- list-size))))
```

**Comment by emacs18** [comment]
I guess following is simpler.

```diff
diff --git a/core/core-spacemacs-buffer.el b/core/core-spacemacs-buffer.el
index 13ac69b79..ef2aa6552 100644
--- a/core/core-spacemacs-buffer.el
+++ b/core/core-spacemacs-buffer.el
@@ -1305,14 +1305,14 @@ startup list.")
                            (org-agenda-files))))))
            (mapcar #'expand-file-name files)))
         ;; we also need to skip sub-directories of `org-directory'
-        (ignore-directory (or (when (bound-and-true-p org-directory)
-                                (expand-file-name org-directory))
-                              ""))
+        (ignore-directory (when (bound-and-true-p org-directory)
+                            (expand-file-name org-directory)))
         (recent-files-list))
     (cl-loop for rfile in recentf-list
              while (> list-size 0)
              do (let ((full-path (expand-file-name rfile)))
-                  (unless (or (string-prefix-p ignore-directory full-path)
+                  (unless (or (and ignore-directory
+                                   (string-prefix-p ignore-directory full-path))
                               (member full-path agenda-files))
                     (cl-pushnew rfile recent-files-list)
                     (setq list-size (1- list-size))))
```

**Comment by lebensterben** [comment]
exactly

**Comment by svenpanne** [comment]
Hmmm, I have the exact same problem, using Emacs 29.1 from Ubuntu 23.10 and a fresh spacemacs checkout. The fix above is already included (I've checked that), but I only see the projects in the list, without any files. The recentf file looks OK IMHO. Any tips on how to debug this further?
