### ISSUE TITLE
unnecessary y-or-no pop-up dialog box regarding org-agenda-files being a string

### ISSUE THREAD

**Issue by emacs18** [syl20bnr/spacemacs#15907]
Due to a change made in spacemacs few weeks ago (detailed below), I get the same pop-up dialog box twice each time I start emacs.  The diaglog box asks whether to continue because `org-agenda-files` is  a string! The value of this variable for me has not changed in many  years.  For now I set `dotspacemacs-startup-lists` to `nil` to prevent these dialog boxes from popping on not only at startup, but also when I switch into or away from the spacemacs buffer.

The code in question is the following lines added in `spacemacs-buffer//insert-recent-files` function a weeks ago:

```elisp
                       (if (listp org-agenda-files)
                           ;; if it's a list, we take that value directly
                           org-agenda-files
                         ;; but if it's a string, it must be file where the list
                         ;; of agenda files are stored in that file and we have
                         ;;to load `org-agenda' to process the list.
                         (when (y-or-n-p "`org-agenda-files' is a string and \
not a list. Load `org' and continue?")
                           (require 'org)
                           (org-agenda-files)))
```

**Comment by lebensterben** [comment]
I made this change and it's intended.

as explained, if org-agenda-files is a string we **have to** load org during startup, which can be slow for some people.

**Comment by lebensterben** [comment]
you can

1. remove agenda from the startup list
2. change the value of the said variable

**Comment by emacs18** [comment]
If that is the case then why just print a warning to the user that org is being loaded due to org-agenda-files being a string?
In my case org is *always* loaded and very early on so there will be no slow down at all.
Forcing me to use mouse to click on diaglog boxes is not right.

In my opinion the change is question is not necessary which is trying to be too smart and causing problems
My hope is that it will be reverted.

**Comment by emacs18** [comment]
Also you could check if org was already loaded first rather than using y-or-no call.

**Comment by emacs18** [comment]
Following is what I mean.

```diff
diff --git a/core/core-spacemacs-buffer.el b/core/core-spacemacs-buffer.el
index c88192ad9..e92d68b7d 100644
--- a/core/core-spacemacs-buffer.el
+++ b/core/core-spacemacs-buffer.el
@@ -1295,8 +1295,9 @@ LIST-SIZE is specified in `dotspacemacs-startup-lists' for recent entries."
                          ;; but if it's a string, it must be file where the list
                          ;; of agenda files are stored in that file and we have
                          ;;to load `org-agenda' to process the list.
-                         (when (y-or-n-p "`org-agenda-files' is a string and \
-not a list. Load `org' and continue?")
+                         (when (and (not (featurep 'org))
+                                    (y-or-n-p "`org-agenda-files' is a string and \
+not a list. Load `org' and continue?"))
                            (require 'org)
                            (org-agenda-files))))))
            (mapcar #'expand-file-name files)))
```

**Comment by lebensterben** [comment]
you can go ahead and make a PR and I will merge it.

**Comment by yantar92** [comment]
> as explained, if org-agenda-files is a string we **have to** load org during startup, which can be slow for some people.

The message presented to user sounds like `org-agenda-files` must not be a string. It is at least confusing.

**Comment by lebensterben** [comment]
@yantar92 what's your suggestion?

**Comment by yantar92** [comment]
My suggestion is
1. (preferred) Just issue a warning and load org instead of querying user
2. "\`org-agenda-files' is a string and not a list. Loading \`org' may slow down startup. Continue?"

**Comment by lebensterben** [comment]
the intent is to irk the user enough so that he will change the value to a list. I can modify the message to make it clearer.

**Comment by yantar92** [comment]
> the intent is to irk the user enough so that he will change the value to a list. I can modify the message to make it clearer.

Are you considering this to be so much of a problem that users cannot decide themselves? Org loading times are not __that much__ large.

**Comment by tsdye** [comment]
I use emacsclient and load time is not an issue, but this dialogue is an issue.  Perhaps just write something to the log so users bothered by the slowdown in startup can investigate and make the change?

**Comment by lebensterben** [comment]
I just pushed a fix to the develop branch.
The question is now replaced by a warning with a little more details.

**Comment by emacs18** [comment]
Why do you think that `(org-agenda-files)` need to be called explicitly?  Is it not called automatically as needed?

**Comment by emacs18** [comment]
If `(org-agenda-files)` is not called explicitly, what feature breaks?  I would like to know so that I can look into it.

**Comment by lebensterben** [comment]
read the comments except

> If org is already loaded, then we assume that the user has already called org-agenda-files.

I forget to delete it.

**Comment by lebensterben** [comment]
btw I never find it slow to startup. the idea of postponing loading of org starts from https://github.com/syl20bnr/spacemacs/pull/15851
