### ISSUE TITLE
Error installing `vim-powerline` and `inspector` on Windows 10 (fresh install, Spacemacs develop branch, Emacs 28.2)

### ISSUE THREAD

**Issue by Prometheus77** [syl20bnr/spacemacs#15903]
#### Description :octocat:
Error installing `vim-powerline` and `inspector` on Windows 10 (fresh install, Spacemacs develop branch, Emacs 28.2)

#### Reproduction guide :beetle:
- Start Emacs
- Error happens during auto-install

*Observed behaviour:* :eyes: :broken_heart:
Get the following messages:

```
(Spacemacs) --> installing package: vim-powerline@spacemacs-modeline... [1/2]
Fetcher: file
Source: nil

c:/Users/foo/.emacs.d/.cache/quelpa/build/vim-powerline/vim-colors.el -> c:/Users/foo/AppData/Local/Temp/vim-powerline6T7XnC/vim-powerline-20230124.192505/vim-colors.el
c:/Users/foo/.emacs.d/.cache/quelpa/build/vim-powerline/vim-powerline-theme.el -> c:/Users/foo/AppData/Local/Temp/vim-powerline6T7XnC/vim-powerline-20230124.192505/vim-powerline-theme.el
Error getting PACKAGE-DESC: (file-missing Opening input file No such file or directory c:/Users/foo/.emacs.d/.cache/quelpa/packages/vim-powerline-20230124.192505.tar)
(Spacemacs) Error: 
An error occurred while installing vim-powerline (error: (wrong-type-argument package-desc nil))

(Spacemacs) --> installing package: inspector@emacs-lisp... [2/2]
Fetcher: github
Source: mmontone/emacs-inspector

Updating c:/Users/foo/.emacs.d/.cache/quelpa/build/inspector/
c:/Users/foo/.emacs.d/.cache/quelpa/build/inspector/inspector.el -> c:/Users/foo/AppData/Local/Temp/inspectorSB184x/inspector-20230119.55816/inspector.el
c:/Users/foo/.emacs.d/.cache/quelpa/build/inspector/tree-inspector.el -> c:/Users/foo/AppData/Local/Temp/inspectorSB184x/inspector-20230119.55816/tree-inspector.el
Wrote c:/Users/foo/.emacs.d/.cache/quelpa/packages/inspector-readme.txt
Error getting PACKAGE-DESC: (file-missing Opening input file No such file or directory c:/Users/foo/.emacs.d/.cache/quelpa/packages/inspector-20230119.55816.tar)
(Spacemacs) Error: 
An error occurred while installing inspector (error: (wrong-type-argument package-desc nil))
```

*Expected behaviour:* :heart: :smile:
Everything installs properly

#### System Info :computer:
- OS: windows-nt
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 58a52ae6e)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(syntax-checking
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
 helm
 (org :variables org-agenda-todo-ignore-scheduled t org-agenda-todo-ignore-deadlines t org-insert-heading-respect-content t org-startup-indented t org-directory
      '("~/Dropbox/org")
      org-agenda-files
      '("~/Dropbox/org")
      org-want-todo-bindings t org-hide-emphasis-markers t org-todo-keywords
      '((sequence "TODO" "NEXT" "FOLL" "|" "DONE" "CANC"))
      org-startup-truncated nil org-ellipsis "▼" org-babel-load-languages
      '((emacs-lisp . t)
        (R . t)
        (python . t))
      org-confirm-babel-evaluate nil org-file-apps
      '(org-file-apps-windowsnt))
 treemacs emoji clojure emacs-lisp
 (ess :variables ess-r-backend 'lsp)
 html java latex lua
 (python :variables python-backend 'lsp)
 git
 (spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t)
 lsp
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (xclipboard :variables xclipboard-enable-cliphist t))
```
- System configuration features: ACL GIF GMP GNUTLS HARFBUZZ JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY W32NOTIFY PDUMPER PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS XPM ZLIB

I've tried deleting .emacs.d/.cache to no avail. I've added c:/MyPrograms/git/usr/bin to my path so that it can access tar.exe, to no avail. Running out of options here.

**Comment by lebensterben** [comment]
do you have gnu tar?

**Comment by Prometheus77** [comment]
From other threads, it seems people have solved this by adding to the path the folder with the tar.exe that is part of git (in my case in c:/MyPrograms/git/usr/bin), but that did not work for me. I have not found a way to install gnu tar from the gnu website on Windows. (You know how those guys feel about proprietary OSes...)

**Comment by Prometheus77** [comment]
Updated: Just installed tar with scoop, added the directory to path, and even added `(setq-default quelpa-build-tar-executable "~/scoop/apps/tar/current/bin")` to my `dotspacemacs/user-config` function and cleared out the .emacs.d/.cache as well for good measure. All to no avail.

**Comment by lebensterben** [comment]
try using the absolute path instead of using ~

**Comment by Prometheus77** [comment]
Tried it with absolute path as well as `~`, tried with `tar.exe` as well as just `tar`, nothing is working.

Looking at the messages buffer, is the intended behavior to put files into `c:/Users/foo/AppData/Local/Temp` during the install, instead of in `c:/Users/foo/.emacs.d/.cache`? I don't understand the startup process/scripts well enough to know what it's trying to do. Should I change my system's TEMP variable?

**Comment by lebensterben** [comment]
I haven't used windows for a long time so I don't know.

**Comment by andrecbarros** [comment]
What version of git for Windows did you install?

**Comment by andrecbarros** [comment]
If it was from https://git-scm.com/download/win, then I suggest you to download the tar package from msys2, store it on a subdir of your git dir, together with the few other packages it needs to run, and be good with it.

May you need precise instructions, let me know.

**Comment by andrecbarros** [comment]
OK, did a test now and installed git from above link, tar and batteries are included, if you can, use it.

**Comment by LukeDRussell** [comment]
Same problem on MacOS, installed via `brew`, with the roughly the same fix.
I did `brew install gnu-tar`, with the following hint:
```sh
GNU "tar" has been installed as "gtar".
If you need to use it as "tar", you can add a "gnubin" directory
to your PATH from your bashrc like:

    PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"
```
