### ISSUE TITLE
Entering visual state from evil-lisp-state should preserve hjkl bindings

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#1591]
Currently, if you enter visual state from evil-lisp-state, hjkl are the normal visual motion commands, and when you exit visual state, you're thrown back into evil-lisp-state.

**Comment by dsdshcym** [comment]
IMHO, different state having different motion behaviours is normal.

**Comment by rpglover64** [comment]
@dsdshcym Agreed, but that's not the problem I was trying to express (admittedly, the bug report is rather opaque). Consider the following scenario:

I'm editing a section of code heavy in parentheses, so I've entered `evil-lisp-state`. Let's say I want to delete from the point to 2 close parentheses forward (a la <kbd>2f)</kbd> if I weren't in `evil-lisp-state`). <kbd>d</kbd> doesn't take a motion command, so <kbd>d2j</kbd> is out, and <kbd>f</kbd> is unbound; I could exit `evil-lisp-state`, but instead I decide to press <kbd>v</kbd>, hoping to do <kbd>2jd</kbd>. To my annoyance, this deletes 2 lines (not 2 parentheses), and to my confusion puts me back in `evil-lisp-state`; this behavior could be improved by just saying that visual state kicks you out of `evil-lisp-state`, but I think the better solution would be something like an `evil-lisp-visual-state` which has motion commands taken from `evil-lisp-state`.

**Comment by dsdshcym** [comment]
Yes, I understood your point. 

And I also agree with the `evil-lisp-visual-state` part.
