### ISSUE TITLE
All text is white on update from develop

### ISSUE THREAD

**Issue by vatrat** [syl20bnr/spacemacs#15917]
#### Description :octocat:
Spacemacs appears black-and-white / grayscale / monochromatic. Some colors work, but most do not.

#### Reproduction guide :beetle:
- Start Emacs
- Do nothing

*Observed behaviour:* :eyes: :broken_heart:
During start, colors work properly. By the time startup is done, all fg colors are white instead of the appropriate coloration, both on the home buffer and others like org-mode. The text at the top of this buffer (SPC h I) is red, but otherwise only the modeline has working colors.

*Expected behaviour:* :heart: :smile:
Buttons and text are color coded according to face settings and themes

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. f3f0d6e6d)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(clojure
 (auto-completion variables auto-completion-enable-help-tooltip t)
 emacs-lisp git helm lsp markdown csv org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking treemacs pandoc graphviz evil-snipe major-modes command-log erc html c-c++ python elixir
 (scheme :variables scheme-implementations
         '(gambit guile racket))
 haskell dash docker systemd)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM XWIDGETS GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by lebensterben** [comment]
not reproducible.

if you believe this is caused by Spacemacs, use git bisect to find which commit introduced this issue.

**Comment by vatrat** [comment]
Understood. I'll look into it when I have time. All I know is it worked two days ago. As such, it might be package-related.

**Comment by lebensterben** [comment]
> All I know is it worked two days ago

Spacemacs was last updated 8 days ago
