### ISSUE TITLE
Chinese input issue

### ISSUE THREAD

**Issue by lazyjean** [syl20bnr/spacemacs#15916]
#### Description :octocat:
Input issue: got an extra input character when press any normal key(a-z, 0-9 etc.)
e.g.
Press: 'k', got 'fk'
Press: 'm', got 'fm'

#### Reproduction guide :beetle:
- Start Emacs
- Use system Chinese input method input some Chinese character
- repeat switch English input method with Chinese input method. The bug will appear sometimes.

*Observed behaviour:* :eyes: :broken_heart:
1. When this issue appeared, all actions that require character combinations are affected.
2. The extra character is not fixed, It depend on the characters pressed during the last operation
3. It will disappear when I restart emacs
4. This problem may occur when switching input methods quickly and entering Chinese characters
5. I first encountered this problem probably a year or two ago

This is the screenshot when the problem occurs, the redundant input letter here is 'f'
<img width="238" alt="image" src="https://user-images.githubusercontent.com/163140/218321896-4f46ff4f-3036-4848-911f-08c72d2b3e4d.png">

*Expected behaviour:* :heart: :smile:
got correct input character

#### System Info :computer:
- OS: darwin
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 5b8a25a6b)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(python ruby javascript yaml emacs-lisp helm lsp dap html protobuf imenu-list swift
        (latex :variables latex-backend 'lsp latex-refresh-preview t)
        (multiple-cursors :variables multiple-cursors-backend 'mc)
        (org :variables org-agenda-files
            ...)
        (go :variables go-backend 'lsp go-tab-width 4 go-format-before-save t gofmt-command "goimports" go-use-golangci-lint t)
        (osx :variables osx-command-as 'meta osx-option-as 'hyper osx-control-as 'control osx-function-as nil osx-right-command-as 'left osx-right-option-as 'left osx-right-control-as 'left osx-swap-option-and-command nil)
        (shell :variables shell-default-shell 'term)
        treemacs)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER THREADS TOOLKIT_SCROLL_BARS ZLIB

**Comment by lebensterben** [comment]
please follow the instructions on issue template and attach the required information

**Comment by lazyjean** [comment]
> please follow the instructions on issue template and attach the required information

I has

**Comment by lazyjean** [comment]
> please follow the instructions on issue template and attach the required information

I have update the issue, I will update backtrace section when it occurs next time.

**Comment by lebensterben** [comment]
I don't use bugOS so I cannot re-produce the issue.

this layer may help: https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bintl/chinese

**Comment by lebensterben** [comment]
Also:

`osx-right-command-as 'left osx-right-option-as 'left osx-right-control-as 'left`

these are all invalid values.

**Comment by lazyjean** [comment]
> I don't use bugOS so I cannot re-produce the issue.
> 
> this layer may help: https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bintl/chinese

thanks

**Comment by lazyjean** [comment]
> 

I will fix these configurations, and try to use again.

**Comment by lazyjean** [comment]
> Also:
> 
> `osx-right-command-as 'left osx-right-option-as 'left osx-right-control-as 'left`
> 
> these are all invalid values.

I will fix these configurations, and try to use again.
I still have this problem today, and can't submit the issue via emacs. I can't do anything further when input system is broken. Is there any documents introduce the spacemacs's input system? I will try to debug locally.

**Comment by lebensterben** [comment]
> Is there any documents introduce the spacemacs's input system? I will try to debug locally.

Spacemacs doesn't ship any input method.

**Comment by lazyjean** [comment]
> > Is there any documents introduce the spacemacs's input system? I will try to debug locally.
> 
> Spacemacs doesn't ship any input method.

ok, thanks

**Comment by lazyjean** [comment]
> Also:
> 
> `osx-right-command-as 'left osx-right-option-as 'left osx-right-control-as 'left`
> 
> these are all invalid values.

I have test these values, they are all correct in my system. https://develop.spacemacs.org/layers/+os/osx/README.html

**Comment by lebensterben** [comment]
> > Also:
> 
> > 
> 
> > `osx-right-command-as 'left osx-right-option-as 'left osx-right-control-as 'left`
> 
> > 
> 
> > these are all invalid values.
> 
> 
> 
> I have test these values, they are all correct in my system. https://develop.spacemacs.org/layers/+os/osx/README.html

yes you're right. i misread it.

**Comment by zj793039327** [comment]
i met the same problem ,do you fix it finally?

**Comment by lazyjean** [comment]
> i met the same problem ,do you fix it finally?

No. But I never met this problem when I update my emacs to 29.1.
