### ISSUE TITLE
DAP layer keybindings for inspecting stuff don't work

### ISSUE THREAD

**Issue by rihardsk** [syl20bnr/spacemacs#15918]
#### Description :octocat:
Some of the dap layer keybindings – ones related to inspection – don't work. This happens at least for Rust code, I haven't tested anything else. The underlying commands, like `dap-ui-inspect` and `dap-ui-inspect-thing-at-point` aren't available.

#### Reproduction guide :beetle:
- Start Emacs
- Open some Rust code with `rust`, `lsp` and `dap` layers enabled
- Start a gdb debug session through dap
- Stop the execution at a breakpoint
- Attempt to inspect a variable with `SPC d I t` or any other inspection shortcut or run a command directly, e.g., `M-x dap-ui-inspect`.

*Observed behaviour:* :eyes: :broken_heart:
An error message is displayed, e.g.,
```
command-execute: Wrong type argument: commandp, dap-ui-inspect-thing-at-point
```

*Expected behaviour:* :heart: :smile:
Something variable inspection related happens

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. f3f0d6e6d)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml vimscript javascript emacs-lisp git helm
      (lsp :variables lsp-rust-server 'rust-analyzer)
      dap rust python cmake nixos
      (ipython-notebook :variables ein-backend 'jupyter)
      docker
      (search-engine :variables search-engine-config-list
                     '((kagi :name "Kagi" :url "https://kagi.com/search?q=%s")))
      markdown multiple-cursors org
      (shell :variables shell-default-shell 'vterm shell-default-width 40 shell-default-position 'right)
      (spell-checking :variables spell-checking-enable-by-default nil)
      treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by allentiak** [comment]
Could you please share your full `.spacemacs` file, please?
