### ISSUE TITLE
Symbolic links trigger "Error running timer 'lsp--on-idle' : (wrong-type-argument stringp nil)"

### ISSUE THREAD

**Issue by vitaminace33** [syl20bnr/spacemacs#15939]
#### Description :octocat:
Symbolic links trigger "Error running timer 'lsp--on-idle': (wrong-type-argument stringp nil)"
Openning a file under a symbolic path triggers "Error running timer 'lsp--on-idle': (wrong-type-argument stringp nil)" and breaks lsp-mode.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file under a symbolic path

*Observed behaviour:* :eyes: :broken_heart:
"Error running timer 'lsp--on-idle': (wrong-type-argument stringp nil)" appears constantly in the mini-buffer.

*Expected behaviour:* :heart: :smile:
No error messages in the mini-buffer and first line shows the file/function where you are at.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. a529b0bfa)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults bibtex
                 (c-c++ :variables c-c++-backend 'lsp-clangd)
                 emacs-lisp git helm html
                 (julia :variables julia-backend 'lsp julia-repl-switches "--threads 32")
                 (latex :variables latex-enable-auto-fill nil latex-enable-magic nil)
                 (lsp :variables lsp-julia-default-environment "~/.julia/environments/v1.8")
                 markdown multiple-cursors octave
                 org
                 (shell :variables shell-default-position 'right shell-default-shell 'vterm)
                 shell-scripts spacemacs-org spell-checking syntax-checking version-control treemacs
                 (yaml :variables yaml-enable-lsp t))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  f-exists\?(nil)
  lsp-f-same\?("/home/user/symbolic/path/to/fi...." nil)
  lsp-headerline--path-up-to-project-root("/home/user/symbolic/path/to/fi...." "/home/user/true/path/to/fi...")
  lsp-headerline--build-path-up-to-project-string()
  #f(compiled-function (segment) #<bytecode 0x1e672f2c62b49e59>)(path-up-to-project)
  mapconcat(#f(compiled-function (segment) #<bytecode 0x1e672f2c62b49e59>) (path-up-to-project file symbols) "")
  lsp-headerline--build-string()
  lsp-headerline--check-breadcrumb()
  run-hooks(lsp-on-idle-hook)
  lsp--on-idle(#<buffer file.c>)
  apply(lsp--on-idle #<buffer file.c>)
  timer-event-handler([t 0 0 500000 nil lsp--on-idle (#<buffer file.c>) idle 0 nil])
```

**Comment by vitaminace33** [comment]
This is disturbing since I heavily depend on symbolic links to path/files on the cloud.

**Comment by lebensterben** [comment]
i think you need to report to lsp-mode

**Comment by smile13241324** [comment]
Hi :),

It looks like this is fixed in lsp-mode. Please reopen when the issue persists.

mfg
Maxi
