### ISSUE TITLE
Allow timeout "command" to inherit variables || Make quelpa & package-build inherit GIT_EXEC_PATH variable

### ISSUE THREAD

**Issue by imme-emosol** [syl20bnr/spacemacs#15933]
Hi, I have a weird GIT-configuration to allow me to run some customized git programs by default.

However, the usual `GIT_EXEC_PATH="/usr/lib/git-core" emacs` did not work for spacemacs, perhaps because of the timeout wrap around git.

I can make the startup errors go away by replacing `command` in `package-build--run-process` ( `core/libs/package-build.el` ) & in `quelpa-build--run-process` ( `core/libs/quelpa.el` ) with: `"env" "GIT_EXEC_PATH=/usr/lib/git-core" command`

Would it be possible (and sensible) to allow variables to be "known" to the (git) command? So that, for example `GIT_EXEC_PATH="/usr/lib/git-core" emacs` would work.

**Comment by lebensterben** [comment]
wrong repository.

should ask melpa/package-build
