### ISSUE TITLE
magit/forge fails to compile SQLite binary

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#15931]
#### Description :octocat:
Can't use forge (`@`) commands in magit as magit/forge fails to compile SQLite binary.

#### Reproduction guide :beetle:
- Start Emacs
- Open magit status
- Start forge (`@`)

*Observed behaviour:* :eyes: :broken_heart:
> No EmacSQL SQLite binary available, aborting

On further investigation `(emacsql-sqlite-compile 2)` fails to find `.../sqlite/Makefile`
the whole `sqlite/` folder is missing.

I had a rollback stash made on `2023-02-21` containing
`emacsql-sqlite-20230118.2015` where the `sqlite/` folder was present. Copying
the folder into the current elpa extract enabled the binary to be built.

*Expected behaviour:* :heart: :smile:
transient menu for forge commands

#### System Info :computer:
- OS: darwin
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 0e4cd2f2e)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml auto-completion csv dash docker emacs-lisp
      (git :variables git-enable-magit-delta-plugin t)
      (go :variables go-backend 'lsp go-format-before-save t go-use-golangci-lint t gofmt-command "goimports")
      graphviz helm helpful
      (html :variables web-mode-enable-auto-quoting nil)
      javascript json lsp org
      (osx :variables osx-option-as nil osx-right-option-as 'meta)
      (plantuml :variables plantuml-default-exec-mode 'jar plantuml-jar-path "/opt/homebrew/opt/plantuml/libexec/plantuml.jar" org-plantuml-jar-path "/opt/homebrew/opt/plantuml/libexec/plantuml.jar")
      prettier
      (python :variables lsp-pylsp-plugins-pydocstyle-enabled nil)
      react restclient shell-scripts sql syntax-checking tko-json treemacs tree-sitter typescript version-control)
```
- System configuration features: ACL GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE PDUMPER THREADS TOOLKIT_SCROLL_BARS XWIDGETS ZLIB

#### Backtrace :paw_prints:
```

```

**Comment by tko** [comment]
Maybe relates to https://github.com/syl20bnr/spacemacs/pull/15874 or https://github.com/syl20bnr/spacemacs/pull/15900 🤷

**Comment by lebensterben** [comment]
why are they related?

**Comment by tko** [comment]
The `sqlite/` directory is included in the tarball downloaded from melpa, so it's not a change in packaging as far as I can guess. On quick glance those PRs seemed to be doing something around tarballs in the approximate date range I'm guessing something changed in spacemacs.

I said maybe, could be totally unrelated.

**Comment by lebensterben** [comment]
if they are related, it can be fixed by installing gnu tar.

**Comment by tko** [comment]
Not fixing it for me. I've installed `gnu-tar` and done enough additional tweaks around PATH so that `(executable-find "tar")` locates the GNU one. Still, after deleting emacsql in elpa and restarting, it gets created _without_ the `sqlite/` directory in it. And magit complains about missing binary.

**Comment by tko** [comment]
Going back in spacemacs history I couldn't find a commit that would've worked so I'm guessing it's not spacemacs code that changed, but some of the other packages, except emacsql. Don't really know how to narrow it down.

**Comment by lebensterben** [comment]
you need to report it to upstream.

**Comment by tko** [comment]
What would you suggest the upstream is exactly? As I said, the tarball from melpa does have the necessary files so the problem is definitely _not_ in emacsql as far as I can tell. While _I_ could not pinpoint a commit in spacemacs to cause this so it doesn't look to be spacemacs either, that is not to say I'm missing something.
In between my next best guess would be `use-package` but go figure, I've no idea where or by what tarballs are getting extracted in the process.

**Comment by lebensterben** [comment]
@tko 

how about 

1. make a copy of the BSD tar
2. copy the GNU tar as the BSD tar and retry

**Comment by tko** [comment]
Earlier I had `(executable-find "tar")` coming back with the GNU tar I had, I figure if that's still not using GNU tar I don't know what to do about it.

Having said that I just did a startup from scratch (`env -i HOME=/tmp/scratch PATH=$PATH emacs`) and while that setup was still using `bsdtar` it did manage to build the SQLite binary. I'm getting a feeling my spacemacs setup is caching something it shouldn't, though I'm unfamiliar with how to trace what really happens after I delete `emacsql` files and restart spacemacs / let it reinstall it.

**Comment by lebensterben** [comment]
you can start with removing .emacs.d/.cache/* and any emacsql in elpa directory.

**Comment by tko** [comment]
That's what I've been doing, deleting `elpa/**/emacsql-*` and restarting, and it kept coming back incomplete. I've now finished restarting after deleting all of `elpa` and now `emacsql` is complete and the SQLite binary got built. Something pretty weird happening through upgrades. 🤷 🙈
