### ISSUE TITLE
org-mode cannot be invoked for .org files - "File mode specification error: (invalid-function org-assert-version)"

### ISSUE THREAD

**Issue by RidaAyed** [syl20bnr/spacemacs#15934]
Copy of  #15869

Even deleting rm -r ~/.emacs.d/elpa + disabling every org-related layer doesn't help. After re-adding the org layer the problem remains. Any further ideas?

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 8645f21cb)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy

**Comment by lebensterben** [comment]
closing in favor of https://github.com/syl20bnr/spacemacs/issues/15896
