### ISSUE TITLE
Terminal escape code printed when I execute cargo

### ISSUE THREAD

**Issue by mindgitrwx** [syl20bnr/spacemacs#15943]
#### Description

When running cargo-process related function in Spacemacs, strange characters appear in the buffer as below.

![screenshot 2023-03-08 at 2 57 54 PM](https://user-images.githubusercontent.com/37054916/223632168-4858a58d-2120-4baa-8d01-dcd303706728.png)

#### Reproduction guide

Install [cargo](https://github.com/kwrooijen/cargo.el) mode package, and execute any function

#### System Info :computer:
- OS: darwin
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. a529b0bfa)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(protobuf yaml go ruby graphviz typescript csv html javascript haskell rust d
          (python :variables python-lsp-backend 'lsp python-lsp-server 'pyright python-fill-column 99 python-test-runner 'pytest python-sort-imports-on-save t python-pipenv-activate t)
          emacs-lisp auto-completion better-defaults git helm lsp markdown multiple-cursors org
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          spell-checking syntax-checking version-control docker search-engine neotree treemacs)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER THREADS TOOLKIT_SCROLL_BARS ZLIB

**Comment by lebensterben** [comment]
they are escape code for ansi colors. I cannot reproduce them.

and you need to report it to https://github.com/kwrooijen/cargo.el

**Comment by smile13241324** [comment]
This is an upstream issue and will therefore be closed here, please contact the maintainers of cargo.el.
