### ISSUE TITLE
[nixos] `run-hooks: Symbol’s function definition is void: nixfmt-on-save-mode`

### ISSUE THREAD

**Issue by sir4ur0n** [syl20bnr/spacemacs#15956]
#### Description :octocat:
When opening a Nix file, I get this error:
```
run-hooks: Symbol’s function definition is void: nixfmt-on-save-mode
```

#### Reproduction guide :beetle:
- Start Emacs
- Open a Nix file

*Observed behaviour:* :eyes: :broken_heart:
```
run-hooks: Symbol’s function definition is void: nixfmt-on-save-mode
```

*Expected behaviour:* :heart: :smile:
No error.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 3512e43c9)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t)
 csv dap docker emacs-lisp ess
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 eww git
 (groovy :variables groovy-backend 'company-groovy)
 (haskell :variables haskell-completion-backend 'lsp)
 (html :variables css-enable-lsp t html-enable-lsp t web-fmt-tool 'prettier)
 ivy
 (java :variables java-backend 'lsp)
 (javascript :variables javascript-backend 'lsp javascript-fmt-tool 'prettier js2-basic-offset 2)
 (json :variables json-backend 'lsp json-fmt-tool 'prettier)
 latex lsp markdown
 (nixos :variables nix-backend 'lsp nixos-format-on-save t)
 (org :variables org-enable-roam-support t org-enable-roam-ui t org-enable-github-support t org-enable-reveal-js-support t org-enable-org-journal-support t org-journal-dir "~/google-drive-tweag/org/journal/" org-journal-file-type 'daily org-journal-file-format "journal-%Y-%m-%d.org" org-journal-date-format "%A, %Y-%m-%d")
 purescript prettier
 (python :variables python-backend 'lsp python-lsp-server 'pyright python-test-runner 'pytest python-formatter 'black python-format-on-save t python-save-before-test t python-sort-imports-on-save t)
 react
 (ruby :variables rubocop-format-on-save t)
 scala semantic
 (shell-scripts :variables shell-scripts-backend 'shell-script-mode)
 slack sql syntax-checking
 (terraform :variables terraform-auto-format-on-save t terraform-backend 'lsp)
 theming
 (treemacs :variables treemacs-use-git-mode 'simple)
 (typescript :variables typescript-backend 'lsp typescript-fmt-on-save t typescript-fmt-tool 'prettier)
 (version-control :variables version-control-diff-side 'left version-control-global-margin t)
 (yaml :variables yaml-enable-lsp t))
```
- System configuration features: CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XAW3D XDBE XIM XPM LUCID ZLIB

#### Backtrace :paw_prints:
N/A.

**Comment by 15cm** [comment]
I fix it locally by adding the hook by myself for now https://github.com/15cm/spacemacs-config/commit/6d494d6f529a1804d848539264e088c2d8daa8be

**Comment by 15cm** [comment]
I fix it locally by adding the hook by myself for now https://github.com/15cm/spacemacs-config/commit/6d494d6f529a1804d848539264e088c2d8daa8be
```
(add-hook 'before-save-hook 'nix-format-before-save)
```

**Comment by lebensterben** [comment]
this could be fixed by adding

    :commands nixfmt-on-save-mode

to the use-package call

**Comment by sir4ur0n** [comment]
I think the root cause is https://github.com/NixOS/nix-mode/commit/c18a24e9ac569a221e88ba9d74d52c7b02b6eb77

If I'm not mistaken, `nixfmt-on-save-mode` was reverted (`reformatter-define nixfmt`) and instead one now must use `nix-format-before-save` (the same command @15cm uses in his hack).

So the actual fix for Spacemacs is to revert https://github.com/syl20bnr/spacemacs/commit/821bd9cc683575af0996c8e2b3e42452bb9c684a

I will open a PR to fix this.
