### ISSUE TITLE
Missing `N` prefix (forge) from magit-status interface

### ISSUE THREAD

**Issue by august-feng** [syl20bnr/spacemacs#15957]
#### Description :octocat:
`N` seems to be missing from the the magit-status interface, however it still
correctly brings up the forge buffer. Other key bindings using forge don't work though. 

e.g: `b N` is supposed to create a branch off of a fork, but I get an error:
```
Unbound suffix: ‘N’ (Use ‘C-g’ to abort, ‘?’ for help) [forge-dispatch]
```

#### Reproduction guide :beetle:
- Start Emacs
- Visit a git repository
- Open magit-status (M-m g s)

*Observed behaviour:* :eyes: :broken_heart:
- Notice `N` is not in the list of commands

*Expected behaviour:* :heart: :smile:
- `N` should be in the list of commands

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 5600e4f1e)
- Graphic display: nil
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(go yaml rust javascript ivy better-defaults emacs-lisp git
    (lsp :variables lsp-rust-server 'rust-analyzer)
    markdown multiple-cursors org
    (shell :variables shell-default-height 30 shell-default-position 'bottom)
    treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM XWIDGETS GTK3 ZLIB%

**Comment by august-feng** [comment]
Oh OK, I think `@` is used as Forge transient key now, but only available in vim editing style. I must've last used Forge when `N` was still available (pre https://github.com/syl20bnr/spacemacs/commit/44894c7132e9853d86ab1a8088b91f903954f04d).

Would there be a way to set `forge-add-default-bindings` to nil for only evil users so that holy mode users could keep the default `N` transient key from the forge package?

**Comment by bcc32** [comment]
(this is a comment just to get the bot to remove the stale label)
