### ISSUE TITLE
mmm-mode breaks with-editor-finish 

### ISSUE THREAD

**Issue by AlanPeters** [syl20bnr/spacemacs#15951]
I am using a custom version control package that the commit-mode derives from gfm-mode. with-editor is triggered to handle the commit message and markdown-mode is used for formatting. 

with-editor adds a hook to the buffer to prevent the buffer from being deleted, this variable applies to both the temporary commit buffer and the mmm-mode-temp buffer. with-editor-finish attempts to clear this hook, but only one buffer's hook is cleared, preventing either buffer from being closed.

It looks like there is already an exemption to enabling mmm for markdown for git-commit-mode, which although created to address another issue, may fix this issue for git commits.

https://github.com/syl20bnr/spacemacs/blame/develop/layers/%2Blang/markdown/funcs.el#L24

Adding a check for with-editor-mode to this predicate fixes this for my use-case but may cause issues for other packages.

**Comment by lebensterben** [comment]
> this variable applies to both the temporary commit buffer and the mmm-mode-temp buffer.

what variable?

**Comment by lebensterben** [comment]
> Adding a check for with-editor-mode to this predicate fixes this for my use-case but may cause issues for other packages.

what do you mean? can you show me the code?

I've no idea what you're talking about especially given that

> I am using a custom version control package that the commit-mode derives from gfm-mode. 

what is the custom version control package?

**Comment by AlanPeters** [comment]
Thanks for the response!

> > this variable applies to both the temporary commit buffer and the mmm-mode-temp buffer.
> 
> what variable?

I may be using the wrong terminology. It is the hook added here: https://github.com/magit/with-editor/blob/59867aebe16454be4d8c0c858f3b00b8a34f3f61/lisp/with-editor.el#L422 
This hook is added to to both buffers but when it is removed: https://github.com/magit/with-editor/blob/59867aebe16454be4d8c0c858f3b00b8a34f3f61/lisp/with-editor.el#L367
it is only removed from the buffer where with-editor-finished is evoked, not the mmm-temp buffer.

> > Adding a check for with-editor-mode to this predicate fixes this for my use-case but may cause issues for other packages.
> 
> what do you mean? can you show me the code?
```
(defun spacemacs/activate-mmm-mode ()
  (unless (or
           (bound-and-true-p git-commit-mode)
           (bound-and-true-p with-editor-mode))
    ;; Enable `mmm-mode'.
    (mmm-mode 1)))
```

> 
> I've no idea what you're talking about especially given that
> 
> > I am using a custom version control package that the commit-mode derives from gfm-mode.
> 
> what is the custom version control package?

It is our company's internal package for a Mercurial-based repository.

**Comment by lebensterben** [comment]
with-editor-mode can be used for any buffers, not just the buffer where you write commit message.

so your proposed change would cause unintended effects when mmm-mode is actually desired for some people.

since you're using your company's private package, you can modify it.
