### ISSUE TITLE
Setting auto-completion-tab-key-behavior to 'complete doesn't work

### ISSUE THREAD

**Issue by trishume** [syl20bnr/spacemacs#1596]
For some reason setting `auto-completion-tab-key-behavior 'complete` doesn't work for me. It acts as if I had set it to nil. Reading the code I can't see why this would be happening, but I haven't looked that hard. 

So far I have just manually been evaluating this as a workaround:
`(define-key company-active-map (kbd "TAB") 'company-complete-selection)`

See here for how I set this variable and my other dotfile stuff:
https://github.com/trishume/dotfiles/blob/master/emacs%2B/spacemacs.symlink#L9

**Comment by trishume** [comment]
Can anyone else reproduce this? Because if so then it should probably be fixed before the next release.

**Comment by trishume** [comment]
NVM I'm dumb I was using the layer `:variables` thing like a `setq` and double-quoting by putting `'complete` instead of `complete`.

A nice user experience feature might be to automatically unquote double-quoted symbols in that form.

**Comment by syl20bnr** [comment]
@trishume you are right, passing it unquoted does not feel right and might confuse beginners.

**Comment by syl20bnr** [comment]
It is not in develop, I did not offer to have both syntax valid though, only the quoted syntax will work so we have `:variables` acting exactly like a `setq` which should feel more natural.
I added this fact in the startup release note. Hopefully users will not get mad about it :-)
