### ISSUE TITLE
Unable to set keybindings

### ISSUE THREAD

**Issue by Midnight1938** [syl20bnr/spacemacs#15963]
Unable to set custom keybindings using emacs mode, tried using the following:

- (define-key global-map (kbd "C-c C-l") 'org-insert-link)
- (define-key evil-emacs-state-map (kbd "C-c C-l") 'org-insert-link)
- (global-set-key (kbd "C-c C-l") 'org-insert-link)

Also unable to change leader key to C-c

**Comment by lebensterben** [comment]
What do you mean by cannot set key bindings?

What do you see `M-x describe-key C-c C-l`?

---

You should not change leader key to `C-c` because by Emacs convention it's special. See https://www.gnu.org/software/emacs/manual/html_node/emacs/Prefix-Keymaps.html

**Comment by Midnight1938** [comment]
> What do you mean by cannot set key bindings?
> 
> What do you see `M-x describe-key C-c C-l`?
> 
> You should not change leader key to `C-c` because by Emacs convention it's special. See https://www.gnu.org/software/emacs/manual/html_node/emacs/Prefix-Keymaps.html

The description states: `C-c C-l is undefined`

**Comment by 88-percent** [comment]
have you tried:

```
(define-key evil-normal-state-map (kbd "C-c C-l") 'org-insert-link)
(define-key evil-insert-state-map (kbd "C-c C-l") 'org-insert-link)
```

**Comment by smile13241324** [comment]
Basically you can set keybindings in your dotfile, you just need to hit the right keymap and you have to make sure that you don't create any issues by accessing resources which are not yet existing, if this happens your code is only partially executed and you will see no results, check your message buffer for exceptions if this happens.

Here is a small example how you would set keybindings:
```elisp
(defun dotspacemacs/user-config ()
  "Configuration for user code:
This function is called at the very end of Spacemacs startup, after layer
configuration.
Put your configuration code here, except for variables that should be set
before packages are loaded."
  (define-key global-map (kbd "C-c C-l") 'org-insert-link)
  (define-key evil-emacs-state-map (kbd "C-c C-l") 'org-insert-link)
  (global-set-key (kbd "C-c C-l") 'org-insert-link)
```
