### ISSUE TITLE
Odd dots in Org Mode

### ISSUE THREAD

**Issue by Midnight1938** [syl20bnr/spacemacs#15973]
Odd dots visible when running org mode, tried a fresh spacemacs install too.

![image](https://user-images.githubusercontent.com/58230351/231219568-eaa231de-fc28-47c6-aa13-fa304210e7cc.png)

**Comment by lebensterben** [comment]
you need to learn to follow instructions when opening an issue.

also, this is not the place for customer support. if you have a question, ask it in discussion.
