### ISSUE TITLE
Spaces emacs can't load svg on dired or treemacs invocation

### ISSUE THREAD

**Issue by rcdeoliveira** [syl20bnr/spacemacs#15972]
#### Description :octocat:
After pull latest update and upgrade packages, dired and treemacs doesn't work anymore

<<DESCRIPTION OF THE PROBLEM>>
<<BE AWARE YOU NEED A GITHUB ACCOUNT TO SEND THIS REPORT>>

#### Reproduction guide :beetle:
- Start Emacs
- Invoke treemcas or dired from menu or recent projects

*Observed behaviour:* :eyes: :broken_heart:
It doesn't open treemacs or dired

*Expected behaviour:* :heart: :smile:
Display dired or treemacs

#### System Info :computer:
- OS: darwin
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 7ace73873)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(systemd yaml auto-completion emacs-lisp git helm lsp markdown multiple-cursors terraform python treemacs themes-megapack)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER THREADS TOOLKIT_SCROLL_BARS ZLIB

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (error "Invalid image type ‘svg’")
  signal(error ("Invalid image type ‘svg’"))
  error("Invalid image type `%s'" svg)
  image-type("/Users/rcdeoliveira/.emacs.d/elpa/28.1/develop/tre..." svg nil)
  create-image("/Users/rcdeoliveira/.emacs.d/elpa/28.1/develop/tre..." svg nil :ascent center :width 22 :height 22)
  byte-code("\305\306\307\310\311$\305\306\307\310\311$\312\313\314\315\10\316\"\5\5%\317\320\2\"\210\211\31\321\322\323\"\324\11!\n>\2040\0\325\326\313\11D\"\210\11\327..." [treemacs-dir treemacs--current-theme cl-struct-treemacs-theme-tags treemacs--icon-size treemacs-file-extension-regex make-hash-table :size 300 :test equal record treemacs-theme "Default" treemacs-join-path "icons/default" add-to-list treemacs--themes mapcar #f(compiled-function (it) #<bytecode -0x1deb3897afdd3b8d>) (root-closed) type-of signal wrong-type-argument 2 "vsc/root-closed.png" image-type-available-p png "" s-starts-with\? "root-" round 0.909 1.1818 imagemagick create
```

**Comment by lebensterben** [comment]
try to evaluate 

(image-type-available-p 'svg)

**Comment by lebensterben** [comment]
your emacs doesn't seem to have svg support.

refer to README on repository page to install Emacs.

**Comment by manukall** [comment]
I'm running into this same error, after upgrading macOS to Ventura. [It looks like this is a bug in Emacs and will be fixed in Emacs 29](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=59081), but that's not released yet. I've installed Emacs through https://emacsformacosx.com/. Any ideas on how to work around this until the Emacs 29 release?

**Comment by lebensterben** [comment]
compile Emacs 29.0.90 pretest from source.

**Comment by manukall** [comment]
@lebensterben Thanks! Since I'm new to MacOS (coming from Linux), I had to figure out how to do this. So for anyone in the same situation, here's how you can install Emacs Pretest on MacOS:

```bash
brew install --cask homebrew/cask-versions/emacs-pretest
```
