### ISSUE TITLE
Change Python key bindings for sending code to REPL for consistency

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1597]
I think the bindings under `SPC m s` should be changed to `SPC m e` for consistency, since we actually evaluate code. Every languages that have a REPL and can interact should just use the same `SPC m e` in my opinion.

**Comment by tuhdo** [comment]
Seems like non-Lisp languages use `s` and Lisp languages use `e`. Probably if we can stick to only these two, than no need to change. But I still think that a single `e` key is better.

**Comment by syl20bnr** [comment]
`SPC m e` is for evaluating and ` SPC m s` is for sending code to the REPL. They are two different thing, check the convention file.

**Comment by tuhdo** [comment]
I see.
