### ISSUE TITLE
Base16 theme errors

### ISSUE THREAD

**Issue by Midnight1938** [syl20bnr/spacemacs#15970]
Ive installed the `base16-theme` through `dotspacemacs-additional-package`

Then set the theme to it through:
```elisp
dotspacemacs-themes '(base16-catppuccin-macchiato)
```

But every time i launch an emacs instance, it tries to install:
![image](https://user-images.githubusercontent.com/58230351/230756766-5910b560-f2f3-463a-bdc8-ecb6832b836d.png)

Then gives up, and sets the theme to catppuccin-macchiato

**Comment by lebensterben** [comment]
link to this theme?

**Comment by Midnight1938** [comment]
> link to this theme?

Base16-Catppuccin-Macchiato ?

Im not sure what you mean by a link to it

**Comment by lebensterben** [comment]
give me the link to the repository of the theme

**Comment by Midnight1938** [comment]
Probably [this](https://github.com/catppuccin/base16) one?

**Comment by lebensterben** [comment]
it is not.

**Comment by lebensterben** [comment]
this is the base16 theme https://github.com/tinted-theming/base16-emacs/tree/4843c8bb359746ed3a5dd269b1ab86410f9fffc1

there is no base16-catppuccin-macchiato

**Comment by Midnight1938** [comment]
> this is the base16 theme https://github.com/tinted-theming/base16-emacs/tree/4843c8bb359746ed3a5dd269b1ab86410f9fffc1
> 
> there is no base16-catppuccin-macchiato


I dont know what to give you, I simply installed the Base16-theme via additional packages and it gave me one. 
Catppuccin has the following [theme for emacs](https://github.com/catppuccin/emacs) which is given as a seperate package.

Theme after installing base16 package:
![image](https://user-images.githubusercontent.com/58230351/231220624-27487b52-020b-4a71-82e8-00dfe7d5d72b.png)

**Comment by lebensterben** [comment]
when you added base16 theme to the additional packages list, as I showed you above, it contains no catppuccin theme.

i don't know where is the base16-catppucchin theme you talk about. show me the source code.
