### ISSUE TITLE
Introduction of AI APIs into spacemacs

### ISSUE THREAD

**Issue by rommeswi** [syl20bnr/spacemacs#15971]
I think with the current boom in artificial intelligence, it is important for spacemacs to keep up and provide easy access to AI APIs. Integrating an AI into spacemacs should be as easy as adding "openai" to the layers list and configuring the login data

In pull request #15969 I proposed a first draft of a layer for access to openai and their popular chatgpt engine. It still had some flaws such as poor evilification and too long keybindings and was rightfully rejected.

I open this feature request in case an experienced spacemacs contributor finds it worth it to create an openai layer that meets the standards of spacemacs.

**Comment by smile13241324** [comment]
Jup adding an AI layer would definitiv be useful.

Just some design principles for a possible impl. 

* the sdks and request logic must be encapsulated in maintained emacs packages, we do not want big chunks of logic being stored in Spacemacs only layers
* the layer should include a mechanism to allow other layers to opt in, see the auto complete layer for examples.
* the layer should not bind global bindings, at least not too much, instead other layers should bind a kind of 'eval block of code' function which is sent to the specific api, by this the AI advisor can implement nicely.

Anyway thats all pretty vague, so feel free to make a draft and discuss it later.

**Comment by rommeswi** [comment]
- The first point is well taken and won't be a big issue. There seem to be more and more chatgpt clients being created for emacs, for example [chatgpt-shell](https://github.com/xenodium/chatgpt-shell). It might make sense to wait for a while to see which would be best to integrate into spacemacs and which packages remain well-maintained.
- I still need to understand better what is special about the opting-in solution of for example auto-complete. I've looked through the code but don't have a clear idea yet how to transfer that to an openai layer.
- I think global bindings for dall-e and chatgpt applications (that open a separate chat window) would make sense. I would suggest `SPC a i d` and `SPC a i c`, respectively. Code completion/commenting/etc. that inserts text into the current buffer should probably be layer-specific. However, I am worried that creating bindings in each layer would be a lot of work.

**Comment by smile13241324** [comment]
I have merged the open ai layer and moved the AI bindings to "spc $" if we add more providers we can think of introducing feature wise bindings and leave the source bindings for shorter key combinations but lets keep it simple for now and see how the new bindings work.

Feedback welcome, and contributions of free alternatives too of course :)
