### ISSUE TITLE
Can't seem to load `org-modern` on Spacemacs

### ISSUE THREAD

**Issue by nicolasshu** [syl20bnr/spacemacs#15980]
I did an update today and for some reason, Spacemacs is not downloading `org-modern` from ELPA. 

```
   dotspacemacs-additional-packages '(
      ...
      org-modern
      ...
      )
```
And it always seems to need me to go through `M-x package-install` to get `org-modern`. 
Do you know why that would be the case?

**Comment by lebensterben** [comment]
https://github.com/syl20bnr/spacemacs/blob/8d7a5db62c9c4429f7c2e18de439b33d3b52ea3e/layers/%2Bemacs/org/config.el#L77

you should enable it via this.

**Comment by nicolasshu** [comment]
Ah, should I just set it to true?

**Comment by lebensterben** [comment]
yes

**Comment by nicolasshu** [comment]
Thank you very much!
