### ISSUE TITLE
website: (www.)spacemacs.org should be the same as develop.spacemacs.org 

### ISSUE THREAD

**Issue by real-or-random** [syl20bnr/spacemacs#15995]
I'm aware that none of the currently active maintainers have the technical permission to make this change happen. But that doesn't make the problem go away, so I think there should be an open issue to track this.

**Comment by smile13241324** [comment]
Hi :),

yes this would definitely be desirable, still I have no rights to do so. I think this has to be kept open until @syl20bnr finds the time to react to this.

Until this has happened all documents should point to develop.spacemacs.org instead.

mfg
Maxi
