### ISSUE TITLE
`fd` bugs in minibuffer if pressed quickly enough

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#16]
Say I want to type `flycheck` in the minibuffer, a bunch of `fffffffffffffffffffff` are printed in the minibuffer. If I type more slowly it is ok.

**Comment by vladh** [comment]
I am still experiencing this for normal files on a new installation.

**Comment by syl20bnr** [comment]
@vladh sorry for the late reply. Do you have a repo step so I can test on my side ?

**Comment by vladh** [comment]
It must have been an old version or something, sorry, seems to be fixed now!
