### ISSUE TITLE
evil-mode deprecated

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#16005]
`evil-mode` is deprecated. Are there any plans to replace it?

**Comment by lebensterben** [comment]
what are you talking? why is it deprecated?

**Comment by gdkrmr** [comment]
It says so here in the first paragraph: https://www.emacswiki.org/emacs/Evil

**Comment by gdkrmr** [comment]
My fault, I should have investigated a bit further before scaring everyone https://github.com/erikw/vim-keybindings-everywhere-the-ultimate-list/issues/10
