### ISSUE TITLE
When I use sqlite3 I get db-error "sqlite_open_v2() failed" 14

### ISSUE THREAD

**Issue by jakshi** [syl20bnr/spacemacs#16014]
When I use sqlite3 backend in magit in spacemacs and try to open magit buffer with C-x g - I get the error:

```
(db-error "sqlite_open_v2() failed" 14)
```

How to debug/fix that?

**Comment by yastanotheruser** [comment]
Same issue here, it turns out the SQLite3 module ends up opening a file containing a literal `~` character.

**Comment by lhernanz** [comment]
I bumped into this last week. The sqlite3 backed does not like relative paths. I solved it by moving the forge path to an absolute path:
``` elisp
(setq forge-database-file (expand-file-name (concat spacemacs-cache-directory "forge-database.sqlite")))
```

**Comment by piotrbujakowski** [comment]
Hi.

What with that?

gost fetch ubuntu --dbpath=/usr/share/vuls-data/gost.sqlite3
INFO[08-31|17:22:22] Initialize Database 
Failed to open DB. err: Failed to open db. err: Failed to open DB. dbtype: sqlite3, dbpath: /usr/share/vuls-data/gost.sqlite3, err: unable to open database file: out of memory (14)

How can be out of memory?
