### ISSUE TITLE
Sphinx cannot use conf.py

### ISSUE THREAD

**Issue by Paulswith** [syl20bnr/spacemacs#16015]
#### Description :octocat:
I use Sphinx to generate docstrings for Python. My team uses the numpydoc style, so I installed `numpydoc` in my Anaconda environment.

Here is the `conf.py` file in the root folder of my Python workspace:

```python
extensions = ["sphinx.ext.autodoc", "numpydoc"]
```

My code file:

```python
class A(object):
    def __init__(
        self,
        a: str,
        b: int,
        c: list,
        d: dict,
        e: str,
        f: int,
        g: int,
        h: int,
        i: int,
        j: int,
        k: int,
    ) -> None:
        pass

    def p(self) -> str:
        return "1"
```

After typing `SPC m S d`:

```python
class A(object):
    def __init__(
        self,
        a: str,
        b: int,
        c: list,
        d: dict,
        e: str,
        f: int,
        g: int,
        h: int,
        i: int,
        j: int,
        k: int,
    ) -> None:
        """
        TODO: Describe the function.

        :param a:
        :param b:
        :param c:
        :param d:
        :param e:
        :param f:
        :param g:
        :param h:
        :param i:
        :param j:
        :param k:
        :returns:
        """
        pass

    def p(self) -> str:
        return "1"
```

#### Reproduction guide :beetle:
- Start Emacs
- openproject, project structure looks like below
 ├── conf.py
 └── main.py 
- enter `main.py`
- go to `__init__` function, type `SPC m S d`

*Observed behaviour:* :eyes: :broken_heart:
I don't know if Sphinx uses `conf.py` or not, but the result didn't meet my expectations.

*Expected behaviour:* :heart: :smile:
generate numpydoc style docstrings

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 66128ffba)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(game csv better-defaults emacs-lisp helm multiple-cursors org spell-checking version-control yaml html json markdown sql debug
      (sphinx :variables rst-sphinx-target-parent "~/Workspace" rst-slides-program "chromium" rst-sphinx-target-projects
              '(("pyproject" html "pyproject/_build")))
      (syntax-checking :variables syntax-checking-enable-tooltips nil)
      (xclipboard :variables xclipboard-enable-cliphist t)
      (git :variables git-enable-magit-delta-plugin t)
      (ipython-notebook :variables ein-backend 'jupyter)
      (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-private-snippets-directory nil)
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (treemacs :variables treemacs-use-all-the-icons-theme t treemacs-use-git-mode 'deferred)
      (conda :variables conda-anaconda-home "/opt/env/conda")
      (python :variables python-backend 'lsp python-lsp-server 'pyright python-test-runner 'pytest python-formatter 'black python-format-on-save t python-save-before-test t python-fill-column 90 python-sort-imports-on-save t)
      (rust :variables rust-backend 'lsp rust-format-on-save t)
      (lsp :variables lsp-rust-server 'rust-analyzer cargo-process-reload-on-modify t lsp-rust-analyzer-server-display-inlay-hints t)
      (scala :variables scala-auto-treeview t scala-indent:use-javadoc-style t flycheck-scalastylerc t scala-enable-gtags t scala-auto-insert-asterisk-in-comments t)
      (java :variables java-backend 'meghanada)
      (go :variables go-backend 'lsp go-format-before-save t gofmt-command "goimports" go-use-golangci-lint t))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
nothing

### The End
I'm new here but I really love Spacemacs and I want to help make it awesome. I hope my issue report is alright, but please let me know if I need to make any changes.

**Comment by smile13241324** [comment]
Hi :),

I am really unsure if this is an issue for us. 

I have almost no experience with Sphinx but I have made a quick internet search and found this https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html, which I think is the module you are trying to use. 

Please run this module manually, as described in the Sphinx documentation, and see if you get better results than what you did when you run it via Spacemacs. Only if this is the case reopen this issue.

If you are getting the same results you need to talk to the provider of the Sphinx module instead.

mfg
Maxi
