### ISSUE TITLE
ol-notmuch issue no such file or directory

### ISSUE THREAD

**Issue by gaurav-iitgn** [syl20bnr/spacemacs#16025]
Issue: When trying to create an org-link from a notmuch message, an error "no such file or directory: ol-notmuch" is popped up.

Steps to reproduce:
1. Open notmuch
2. Go to a message
3. Try to store a link using `org-store-link`

System information (`SPC h d s`):
#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 66128ffba)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: (compleseus spell-checking treemacs)
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git helm multiple-cursors org notmuch compleseus spell-checking treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM XWIDGETS GTK3 ZLIB

Related to: [this issue](https://github.com/syl20bnr/spacemacs/issues/13139l)

Solution: While org-notmuch has been changed to ol-notmuch in the above mentioned issue, the package ol-notmuch is not installed and configured as part of the notmuch layer. The problem was resolved by adding the following to: [spacemacs/layers/+email/notmuch/packages.el](https://github.com/syl20bnr/spacemacs/blob/71d4e15e67feda18692ee35d50f3d98216cd90aa/layers/%2Bemail/notmuch/packages.el)

1. Add `ol-notmuch` to the `setq notmuch-packages` [line 24]. The updated definition is as follows:
```elisp
(setq notmuch-packages
  '(
    (counsel-notmuch :requires ivy)
    (helm-notmuch :requires helm)
    notmuch
    org
    ol-notmuch
    persp-mode
    window-purpose))
```
2. Adding the corresponding init for `ol-notmuch` as follows:
```elisp
(defun notmuch/init-ol-notmuch ()
    (use-package ol-notmuch
        :ensure t))
```

Since this is my first post, please guide me in case this was supposed to be done in a different manner.

**Comment by smile13241324** [comment]
Hi :),

you are right the dependency was missing, I have added it to the layer, please give it a try and reopen if it does not work as expected.

mfg
Maxi
