### ISSUE TITLE
"company-mode" not providing expected completions in "sh-mode"

### ISSUE THREAD

**Issue by sfavazza** [syl20bnr/spacemacs#16022]
#### Description :octocat:
Working with shell scripts I noticed that only `company-shell` and `company-shell-env` company back-ends are used.

#### Reproduction guide :beetle:
- Start Emacs
- open a shell script
- define a function
- try to type the first characters of the just defined function

*Observed behaviour:* :eyes: :broken_heart:
The last created function is not suggested among proposed completions.

To reproduce the issue I tried with a simply dummy file with the following content (where `|` is the position of the pointer):

```shell
#!/usr/bin/env bash

function dzz_1 {
    echo "dzz_1" \
}
function dzz_2 {
    echo "dzz_2" \
}

dz|
```

`company-mode` does not suggest anything and it is explicable looking at the `company-diag` output:

```
Emacs 28.1 (x86_64-pc-linux-gnu) of 2022-10-23 on 750b0088b3f1
Company 0.9.13

company-backends: ((company-shell company-shell-env :with company-yasnippet)
 (company-semantic company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev :with company-yasnippet))

Used backend: (company-shell company-shell-env :with company-yasnippet)

Major mode: sh-mode
Prefix: #("dz" 0 2
  (fontified t ws-butler-chg chg))

Completions: none
```

For testing I tried to execute `company-other-backend` (which I believe selects the second group of backends depicted in the `company-diag` output) and I got the expected suggestion, like showed in the screenshot below:

![image](https://github.com/syl20bnr/spacemacs/assets/36377461/0353f99b-d4e1-4273-a360-add268dcff3e)

I wonder whether this is an issue with `company-mode` or rather the configuration of the shell-layer. I tried to debug the issue with company-mode but I got lost. If someone knows where exactly the backends are evaluated would be helpful to better understand the issue on my side.

*Expected behaviour:* :heart: :smile:
The suggested completions should always include (at least) the function and variables defined in the current
script.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 66128ffba)
- Graphic display: t
- Running in daemon: mars
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip 'manual auto-completion-private-snippets-directory "~/snippets" company-selection-wrap-around t)
 bm cmake
 (docker :variables docker-compose-command "docker compose" docker-dockerfile-backend 'lsp)
 emacs-lisp git
 (helm :variables helm-no-header nil helm-position 'top)
 (lsp :variables lsp-navigation 'peek lsp-ui-remap-xref-keybindings t lsp-ui-doc-include-signature t lsp-lens-enable t lsp-headerline-breadcrumb-segments
      '(project file symbols))
 (dap :variables dap-python-debugger 'debugpy)
 markdown multiple-cursors
 (neotree :variables neo-theme 'nerd neo-vc-integration
          '(face))
 org python rust
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'term shell-default-term-shell "/bin/bash" multi-term-program "/bin/bash" shell-enable-smart-eshell t)
 (shell-scripts :variables shell-scripts-backend nil)
 (spacemacs-language :variables google-translate-default-target-language "en")
 (spell-checking :variables enable-flyspell-auto-completion nil ispell-dictionary "en_US" ispell-program-name "hunspell")
 systemd yaml)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by smile13241324** [comment]
Hi :),

I have had a look into this and in my opinion this is an issue with `company-shell` rather than with the layer setup. In principle the layer defines the following:

```elisp
(defun spacemacs//shell-scripts-setup-company ()
  "Conditionally setup company based on backend."
  ;; Activate lsp company explicitly to activate
  ;; standard backends as well
  (if (eq shell-scripts-backend 'lsp)
      (spacemacs|add-company-backends
        :backends company-capf
        :modes sh-mode)
    (spacemacs|add-company-backends
      :backends (company-shell company-shell-env)
      :modes sh-mode)))
```
This is in case of a non lsp setup, `company-shell` and `company-shell-env` are asked for an answer, if they both return nil the next in the line is asked, this would then be `semantic` which would provide better suggestions in your case. However we cannot set `semantic` as primary backend as this layer is optional.

This means `semantic` completions are only considered when `company-shell` answers with nil, however this seems not to be the case therefore the other checkers are never considered.

You should either try to open an issue with `company-shell` or switch to the more complete `lsp` based modes which provide completions the way you are expecting them in your ticket.

mfg
Maxi

PS: I have updated the README to make sure that LSP based backends are the preferred ones from our point of view, as these are shared between various IDE projects and allow for more sharing of code and effort.

**Comment by sfavazza** [comment]
Hello!

Thank you for the detailed answer, I totally agree with your points. I wanted to suggest adding `company-dabbrev` to the backends list as work-around (even if part of the default completion group), but the right way would be to open an issue for `company-shell`.

Though I always use the `lsp` layer for completions and I totally miss the fact that I can use it also for the shell layer. I will definitely use that instead.

Thanks again for the assistance!
Sam
