### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by A1ex-N** [syl20bnr/spacemacs#16021]
#### Description :octocat:

I install emacs via scoop on windows, open it and then after a few seconds it closes. I ran emacs with `--debug-init` and i see 
```
Loading c:/Users/alexn/.emacs.d/core/core-early-funcs.el (source)...
Loading c:/Users/alexn/.emacs.d/core/core-early-funcs.el (source)...done
```
and then emacs closes

#### Reproduction guide :beetle:
- Install emacs via the command `scoop install emacs`
- Clone spacemacs using `git clone https://github.com/syl20bnr/spacemacs $HOME/.emacs.d`
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
emacs closes

*Expected behaviour:* :heart: :smile:
i expect emacs to not randomly close

#### System info
Windows 10 version 22H2 (OS build 19045.2965)
Emacs version 28.2

**Comment by smile13241324** [comment]
Sorry this is an emacs issue not a spacemacs issue, please address your issue to the provider of your emacs build. On windows I would suggest you use WSL2 to run emacs in a real linux environment, everything else will crash randomly at one point.

EDIT:
Have a look at https://github.com/smile13241324/spacemacs-InstallerAndConfig, which does exactly this and runs stable in Windows environments.
