### ISSUE TITLE
[git] add CodeReview package to layer

### ISSUE THREAD

**Issue by practicalli-johnny** [syl20bnr/spacemacs#16020]
Feature request

Add the https://github.com/wandersoncferreira/code-review package to the Git layer to enable code reviews from Spacemacs

CodeReview is integrated into the Magit & Forge UI and provides code review capabilities for Github and basic Gitlab and Bitbucket workflows

The package is available via MELPA https://melpa.org/#/code-review

Thank you

**Comment by smile13241324** [comment]
Hi :),

I have added `code-review` to the `git` layer however I was not able to properly start a code review, nor did I see the bindings in the `magit` transient state.

Can you give it a try and give me a short feedback if something is missing?

mfg
Maxi

**Comment by pataquets** [comment]
I keep getting ```(Spacemacs) Error in dotspacemacs/user-config: Given parent class emacsql-sqlite-connection is not a class``` on Spacemacs boot since `code-review` is present. I've worked around it temporarily by adding it to `dotspacemacs-excluded-packages`.
I had the package pending to enable until wandersoncferreira/code-review#245 is settled, as it was affecting me.
I suggest to make it optional, disabled by default in the meantime.

Spacemacs `HEAD` (as of 2023-06-18), Emacs 27.1, Ubuntu Bionic.

**Comment by smile13241324** [comment]
Ups I haven't seen this error on startup, just when I have called some functions of it, I have thought it would be some kind of setup issue but as nobody is forced to execute anything I have just kept it in there.

With the linked issue though I would disable the package again until the linked issue is resolved.

**Comment by pataquets** [comment]
Since the upstream fix looks far from being fixed, perhaps an alternative to consider is [Doom Emacs' fork](https://github.com/doomelpa/code-review), as proposed here: https://github.com/wandersoncferreira/code-review/issues/251#issuecomment-1760993416

**Comment by smile13241324** [comment]
I have added the doom-emacs fork to spacemacs but could not test it as the git layer is currently broken due to https://github.com/magit/magit/issues/5206

**Comment by tarsius** [comment]
Note that that fork is currently broken too. See https://github.com/doomelpa/code-review/pull/2.
