### ISSUE TITLE
CPU at 100% - max-lisp-eval-depth

### ISSUE THREAD

**Issue by tigerjack** [syl20bnr/spacemacs#16034]
#### Description :octocat:
Emacs freezes with `error "Lisp nesting exceeds ‘max-lisp-eval-depth’"`, CPU usage goes up to 100%.

While searching, I found a similar bug https://github.com/syl20bnr/spacemacs/issues/9409. My history file was not so large, but I deleted it anyway. I still have the same issue.

#### Reproduction guide :beetle:

I am not totally sure this happens only in this situation, but for me the trigger is pressing `M-q` (`fill-paragraph`) on a `.tex` file. After that, emacs become unasable, since it hangs every few seconds.

*Expected behaviour:* :heart: :smile:
Fluent experience, low CPU usage.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 2cb4f092f)
- Graphic display: nil
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html ruby git
      (version-control :variables version-control-diff-side 'left version-control-diff-tool 'diff-hl)
      dap lsp rust emacs-lisp common-lisp
      (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-lsp-enable-semantic-highlight 'rainbow c++-enable-organize-includes-on-save t c-c++-adopt-subprojects t c-c++-enable-clang-support t c-c++-enable-clang-format-on-save t c-c++-enable-rtags-support t c-c++-default-mode-for-headers 'c++-mode)
      (python :variables python-backend 'lsp python-lsp-server 'pyright python-formatter 'black python-pipenv-activate t python-fill-column 79)
      ipython-notebook yaml themes-megapack asciidoc
      (helm :variables helm-enable-auto-resize t)
      (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence-delay 0 auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory nil)
      (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
      (languagetool :variables languagetool-show-error-on-jump t langtool-default-language "en-GB" langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*")
      better-defaults markdown ranger
      (org :variables org-projectile-file "TODOs.org" org-enable-roam-support t org-roam-directory "/mnt/internal/SharedData/Documents/org-roam" org-roam-v2-ack t org-roam-v2-ack t org-enable-roam-ui t org-enable-org-brain-support t)
      gtags
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/bash" multi-term-program "/bin/bash")
      (latex :variables latex-enable-auto-fill -1 latex-enable-folding t)
      (bibtex)
      deft
      (spell-checking :variables spell-checking-enable-by-default nil))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
  window-normalize-window(#<window 72 on expres.tex> t)
  unrecord-window-buffer(#<window 72 on expres.tex> #<buffer  *temp*-381604>)
  replace-buffer-in-windows(#<buffer  *temp*-381604>)
  kill-buffer(#<buffer  *temp*-381604>)
  #f(compiled-function () #<bytecode -0x1c8cb86db3d79fa3>)()
  url-generic-parse-url("file:///mnt/internal/LinuxData/vc/papers_reports/2...")
  lsp--uri-to-path-1("file:///mnt/internal/LinuxData/vc/papers_reports/2...")
  lsp--uri-to-path("file:///mnt/internal/LinuxData/vc/papers_reports/2...")
  lsp--on-diagnostics-update-stats(#s(lsp--workspace :ewoc nil :server-capabilities #<hash-table equal 14/14 0x1588ecee7593> :registered-server-capabilities nil :root "/mnt/internal/LinuxData/vc/papers_reports/2021_TQu..." :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn workspace) #<bytecode -0x25620c0
```

#### Additional info - profiler

[cpu_report.txt](https://github.com/syl20bnr/spacemacs/files/11679232/cpu_report.txt)
[mem_report.txt](https://github.com/syl20bnr/spacemacs/files/11679233/mem_report.txt)

**Comment by tigerjack** [comment]
From further inspection, it seems that the bug arises when the `latex-backend` is set to `'lsp`; after switching to `'company-auctex`, spacemacs became usable again for LaTeX editing.
Maybe the problem is related to `texlab` itself. I will report back after further analysis.

**Comment by jgrosso** [comment]
I'm having the same issue—has anyone found a solution?

**Comment by tigerjack** [comment]
> I'm having the same issue—has anyone found a solution?

In my case, the problem was also arising because of a bad configuration of the major mode (`LaTeX-mode` instead of `latex-mode`) that was resulting in an endless recursion.

**Comment by jgrosso** [comment]
Thanks! I don't think I've customized my setup very much at all—I'm mostly using whatever Spacemacs `latex` does by default. I'll suppose I'll enable debug-on-error and try to get a specific backtrace....
