### ISSUE TITLE
Fails to install `ts-ls`

### ISSUE THREAD

**Issue by OZoneGuy** [syl20bnr/spacemacs#16046]
#### Description :octocat:
Typescript LSP fails to installs on a fresh spacemacs install.

#### Reproduction guide :beetle:
- Start Emacs
- Open a typescript file in a project
- Choose `ts-ls` as the server to install when prompted (or attempt to install it via `lsp-install-server`)

*Observed behaviour:* :eyes: :broken_heart:
Returns with the error:
```
Unable to install typescript via `npm' because it is not present
```

And produces the following messages:
```
LSP :: Download ts-ls started.
LSP :: Server ts-ls install process failed with the following error message: Unable to find a way to install typescript.
Check `*lsp-install*' and `*lsp-log*' buffer.
```

*Expected behaviour:* :heart: :smile:
Install the LSP without any issues

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 26629bf3a)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp
 (c-c++ :variables c-c++-backend 'lsp-clangd)
 (java :variables java-backend 'meghanada)
 haskell
 (agda :variables agda-mode-path "/usr/share/agda/emacs-mode/agda2.el")
 (rust :variables rust-format-on-save t)
 (go :variables go-format-before-save t)
 (csharp :variables csharp-backend 'lsp)
 (lsp :variables lsp-ui-doc-enable nil lsp-lens-enable nil lsp-rust-server 'rust-analyzer)
 javascript
 (typescript :variables typescript-backend 'lsp typescript-fmt-tool 'prettier typescript-fmt-on-save t typescript-indent-level 2)
 (vue :variabels vue-backend 'lsp)
 (python :variables python-backend 'lsp)
 shell-scripts markdown
 (latex :variables latex-enable-folding t latex-build-engine 'xetex latex-enable-magic t)
 html bibtex asciidoc yaml graphviz
 (plantuml :variables plantuml-jar-path "~/applications/jars/plantuml.jar")
 (org :variables org-directory "~/org-files/" org-enable-org-brain-support t org-brain-path "~/org-brain/" org-ellipsis " ⮷" org-export-with-sub-superscripts '{} org-export-with-toc nil org-export-with-todo-keywords nil org-export-with-date nil org-list-allow-alphabetical t org-pretty-entities t org-export-in-background nil org-latex-pdf-process
      '("pdflatex -shell-escape %f" "biber %b" "pdflatex -shell-escape %f" "pdflatex -shell-escape %f")
      org-enable-reveal-js-support t org-enable-github-support t org-publish-project-alist
      '(("docs" :base-directory "~/projects/org-docs/" :publishing-directory "~/projects/org-docs/html/" :publishing-function org-html-publish-to-html :exclude "code_snippets.org" :recursive t :with-toc t))
      org-default-priority 67 org-lowest-priority 71 org-agenda-todo-list-sublevels t org-projectile-file "TODOs.org" org-todo-keywords
      '((sequence "TODO(t)" "NEXT(n!)" "ASSIGNED(a@!/@!)" "WAIT(w@/@)" "|" "DONE(d@!/@)" "CANCELLED(c@/@!)"))
      org-agenda-skip-scheduled-if-deadline-is-shown t org-capture-templates
      '(("t" "Task")
        ("tt" "Today" entry
         (file+olp "~/org-files/tasks.org" "Tasks")
         "* TODO %?\nSCHEDULED: %t")
        ("tw" "Work" entry
         (file+olp "~/org-files/tasks.org" "Work")
         "* TODO %?\nSCHEDULED: %t")
        ("p" "project idea" entry
         (file "~/org-files/projects.org")
         "* %?\n%U")
        ("b" "Blog idea" entry
         (file+headline "~/org-files/notes.org" "Blog Ideas")
         "* %?\n%U"))
      org-enforce-todo-dependencies t org-enable-notifications t org-start-notification-daemon-on-startup t org-agenda-skip-scheduled-if-done t org-agenda-skip-deadline-if-done t org-agenda-skip-deadline-prewarning-if-scheduled t org-agenda-skip-scheduled-if-deadline-is-shown t org-plantuml-jar-path "~/applications/jars/plantuml.jar")
 better-defaults helpful helm spell-checking syntax-checking auto-completion version-control git multiple-cursors
 (ranger :variables ranger-overrid-dired 'ranger ranger-show-preview t ranger-enter-with-minus 'ranger ranger-clean-on-disable t ranger-clean-eagerly t ranger-show-hidden t)
 (shell :variables shell-default-height 60 shell-default-position 'bottom shell-default-shell 'vterm)
 csv docker
 (latex :variables latex-enable-folding t latex-refresh-preview t)
 (languagetool :variables langtool-bin "/usr/bin/languagetool" langtool-default-language "en-CA")
 treemacs emoji)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

#### NOTE :eyes:

I am using nvm with fish shell. The locations for the nvm data is different than other posix shells. I added the nvm environment variables to `.spacemacs.env`.

```env
nvm_data=/home/omar/.local/share/nvm
nvm_mirror=https://nodejs.org/dist
```

I couldn't find information on this issue. If someone knows a workaround or a solution, let me know. Thanks.

**Comment by MaxIDgis** [comment]
Can you run `npm --version` in a terminal?
If not, you may not have node.js installed.
Node.js is used to install both typescript and ts-ls, so you'll need to install it first if you don't already have it.

**Comment by OZoneGuy** [comment]
```
npm --version
9.6.7
```

And here are the global packages:
```
npm list -g
/home/omar/.local/share/nvm/v20.3.0/lib
├── @volar/vue-language-server@1.6.5
├── corepack@0.18.0
├── eslint@8.43.0
├── npm@9.6.7
├── prettier@2.8.8
├── typescript-formatter@7.2.2
├── typescript-language-server@3.3.2
└── typescript@5.1.3
```

`npm` and `node` are installed via `nvm`. And Emacs can use that npm install, it is the only install in the system.

Now, it is not detecting npm nor node. Even though they are installed and running on the system
```
which node
/home/omar/.local/share/nvm/v20.3.0/bin/node
```

Is there a config that I am missing?

**Comment by OZoneGuy** [comment]
Last resort. Set the environment variable for the default node version, then reinstalled spacemacs. That solved it.

Not entirely sure what was going on.

**Comment by tko** [comment]
Sounds like the `PATH` variable in `.spacemacs.env` was missing the path to `npm` and so it was not found from within emacs. Reinstalling may've recreated `.spacemacs.env` with an updated `PATH`

**Comment by komali2** [comment]
If you have this issue and suspect it's because you installed node on your system via NPM, this fixed it for me:

Edit `~/.spacemacs.env`

Add your nvm directory to the `PATH` environment variable in `~/.spacemacs.env`

It's probably like

`/home/USERNAME/.nvm/versions/node/v18.17.0/bin`

You can find out your specific version by doing `echo $PATH` and seeing what your nvm path looks like

**Comment by am-p** [comment]
> Last resort. Set the environment variable for the default node version, then reinstalled spacemacs. That solved it.
> 
> Not entirely sure what was going on.

How do you do that? Because I use fish also and jorge Bucaramn nvm/fish
