### ISSUE TITLE
Undo-Tree discarding undo history: "No further undo information"

### ISSUE THREAD

**Issue by maptv** [syl20bnr/spacemacs#16047]
#### Description :octocat:

Undo-Tree discarding undo history leads to "No further undo information" message.

I cannot get persistent undo to work consistently in spacemacs.
Here is a link to my config: https://github.com/maptv/setup/blob/main/.spacemacs
I am installing in the typical location (`.emacs.d`).
I tried re-installing Spacemacs with different Emacs versions.
I have tried all sorts of undo settings, but took them all out of my config because nothing was working.

#### Reproduction guide :beetle:

1. Start Emacs with my config: https://github.com/maptv/setup/blob/main/.spacemacs
2. Open a file
3. Make a change
4. Exit the current session
5. Start a new session
6. Press u

*Observed behaviour:* :eyes: :broken_heart:

The message "No further undo information" is displayed.

By pressing `SPC w p m`, I find this error:
```
Buffer has been modified since undo-tree history was saved to
	  "~/.emacs.d/.cache/undo-tree-history/.!Users!uname!uname!repo!.file.~undo-tree~"; could not load undo-tree history
```
I believe this error means that Undo-Tree has missed a beat and gave up completely.
Is there some way to ensure that this never happens?
Hooks that save/load undo history when closing/opening a file?

*Expected behaviour:* :heart: :smile:

Press u in normal state to undo the most recent change.

#### System Info :computer:

- OS: darwin
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 26629bf3a)
- Graphic display: nil
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(vimscript lua auto-completion emacs-lisp evil-snipe git helm markdown multiple-cursors osx version-control treemacs)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE PDUMPER THREADS ZLIB

#### Backtrace :paw_prints:

```
Buffer has been modified since undo-tree history was saved to
	  "~/.emacs.d/.cache/undo-tree-history/.!Users!uname!uname!repo!.file.~undo-tree~"; could not load undo-tree history
```

**Comment by smile13241324** [comment]
Undo-tree is not longer supported due to its unmaintained state. Please switch to undo-fu and reopen when the issue is still there
