### ISSUE TITLE
Type error in `space-doc` 

### ISSUE THREAD

**Issue by bryce-carson** [syl20bnr/spacemacs#16049]
`../elpa/28.2/develop/space-doc-20230617.190139/space-doc.elc: Error: Wrong type argument: listp, #<subr spacemacs//space-doc-font-lock-fontify-region-function>`

For some time, perhaps a month, I've been seeing this *Compile-Log* warning whenever I open the Spacemacs Documentation from the quick-help (`SPC h SPC Enter/Return`).

In the moment I'm just reporting the issue, I don't have time to investigate it.

**Comment by smile13241324** [comment]
@JAremko could you have a look?

**Comment by JAremko** [comment]
@smile13241324  sure

**Comment by JAremko** [comment]
Looks like we compile the whole space-doc  so the code that compiles specific functions should be removed.  I'll fix it

**Comment by JAremko** [comment]
Should be fixes with https://github.com/syl20bnr/spacemacs/commit/6fd09d315e1959055f43d1390867a61c6f9c4deb

(I used wrong issue in the commit message)

**Comment by bryce-carson** [comment]
https://github.com/syl20bnr/spacemacs/commit/6fd09d315e1959055f43d1390867a61c6f9c4deb fixed this issue, so I'm closing it now.
