### ISSUE TITLE
Why is my fresh install of spacemacs using org 9.4.4?

### ISSUE THREAD

**Issue by bobf32** [syl20bnr/spacemacs#16058]
As title really. I'm on develop spacemacs branch, and have updated packages but I seem to have a rather outdated version of org.

**Comment by TheDohn** [comment]
There are probably better ways to handle this, but I often have org mode issues and 99% of the time just deleting org and restarting Spacemacs fixes it. Specifically I go to `~/.emacs.d/elpa/28.1/develop/` and delete the org mode folder which for me right now would be `org-9.6.7/`. Depending on your installation, Emacs version,  Spacemacs version, and org version the exact path will be different.

**Comment by Dietr1ch** [comment]
Related to #15896. On my end I just moved to emacs 29, but removing those directories did the trick for me on v28

**Comment by smile13241324** [comment]
Please see the linked ticket, this is related to a package.el issue and handled in this issue.
