### ISSUE TITLE
avy-org-refile-as-child failing with error

### ISSUE THREAD

**Issue by bobf32** [syl20bnr/spacemacs#16057]
```avy-org-refile-as-child``` is failing with ```Symbol's value as variable is void: org-after-refile-insert-hook```.

Emacs version 27.2
Org version 9.4.4

**Comment by smile13241324** [comment]
I have just tried this and all seems to be working fine. Please upgrade org and retry.

**Comment by smile13241324** [comment]
Closed as no response
