### ISSUE TITLE
Org Modern not respected by `dotspacemacs-additional-packages`

### ISSUE THREAD

**Issue by JoshTRN** [syl20bnr/spacemacs#16063]
#### Description :octocat:

The `org-modern` package is ignored by `dotspacemacs-additional-packages`.

#### Reproduction guide :beetle:
- Start Emacs
- In your .spacemacs, add `org-modern` inside the `dotspacemacs-additional-packages` list.
- Restart to install

*Observed behaviour:* :eyes: :broken_heart:
Nothing is installed
If you install the package yourself with `package-install` the package is deleted on restart.

*Expected behaviour:* :heart: :smile:

Spacemacs installs the `org-modern` package.
If you install the package yourself with `package-install` the package does not get deleted.

*Note:*
This is the only package I've seen that has this issue. it's very oddly specifid.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 30.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. bdc9d0bec)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(nginx systemd lua rust csv
       (auto-completion :variables auto-completion-enable-snippets-in-popup t)
       better-defaults csv dap debug docker
       (elm :variables elm-format-on-save t elm-sort-imports-on-save t)
       emacs-lisp eww
       (git :variables git-enable-magit-delta-plugin t)
       (go :variables go-backend 'lsp go-tab-width 2)
       haskell
       (helm :variables helm-position 'top)
       html java
       (javascript :variables js2-mode-show-strict-warnings nil)
       kubernetes
       (lsp :variables lsp-lens-enable t)
       markdown multiple-cursors nixos
       (node :variables node-add-modules-path t)
       (org :variables org-enable-appear-support t org-enable-epub-support t org-enable-roam-protocol t org-enable-roam-support t org-enable-roam-ui t org-enable-transclusion-support t org-enable-valign t org-enable-org-journal-support t org-enable-verb-support t)
       pandoc prettier search-engine shell-scripts
       (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-vterm)
       slack spell-checking syntax-checking terraform themes-megapack treemacs tree-sitter
       (typescript :variables javascript-backend 'lsp typescript-backend 'lsp typescript-fmt-on-save t typescript-fmt-tool 'lsp typescript-linter 'tslint typescript-tsx-mode t)
       (unicode-fonts :variables unicode-fonts-enable-ligatures t)
       (version-control :variables version-control-diff-side 'left version-control-global-margin t)
       vimscript
       (vue :variables vue-backend 'lsp)
       yaml)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBSYSTEMD LIBXML2 MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

**Comment by smile13241324** [comment]
Packages which are owned by layers cannot be installed via additional packages, instead you need to activate the respective layer.

Spc h spc org-modern will show which layer is responsible.

**Comment by JoshTRN** [comment]
Omg thank you so much. I will close this issue. I thought that might be the case, but I didn't see any documentation on the website that showed how to activate it.

**Comment by JoshTRN** [comment]
![image](https://github.com/syl20bnr/spacemacs/assets/33141876/770c25b6-7f3c-4ef6-94a2-9f8c49b64abb)

@smile13241324  Do you know how to activate it? here is the layer that's said to own it:

```elisp
                      (org :variables
                           org-enable-appear-support t
                           org-enable-epub-support t
                           org-enable-roam-protocol t
                           org-enable-roam-support t
                           org-enable-roam-ui t
                           org-enable-transclusion-support t
                           org-enable-valign t
                           org-enable-org-journal-support t
                           org-enable-verb-support t)
```

![image](https://github.com/syl20bnr/spacemacs/assets/33141876/d4241214-fd0c-42a9-8018-bec1a270552a)

**Comment by JoshTRN** [comment]
Never mind. I found it through searching that file. 

`org-enable-org-modern-support t`

Thank you so much for everything!
