### ISSUE TITLE
`org-toc-show` stop working

### ISSUE THREAD

**Issue by spacegoing** [syl20bnr/spacemacs#16069]
#### Description :octocat:
My all keys for `org-toc-show` stop working on current develop commit

#### Reproduction guide :beetle:
- Start Emacs
- Start an org file
- call `org-toc-show`
- the window pop up all texts without folding, keys not working

*Observed behaviour:* :eyes: :broken_heart:
keys like 1 2 3 4 to control folding level / Enter Tab to goto
content all stops working

You can see screen shot below. Upper window is org file, Bottom
window is org-toc-show window. Pressing `?` will not pop helper window not, it asks for input on the bottom instead
<img width="1068" alt="image" src="https://github.com/syl20bnr/spacemacs/assets/5180020/a5910ea7-553f-49c5-a3cb-d4e8c4ec024e">

#### System Info :computer:
- OS: darwin
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 42b04a5f1)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown org sdefaults sdired sorg c-c++ python
      (python :variables python-backend 'lsp python-lsp-server 'pylsp python-formatter 'yapf)
      html yaml sql csv docker
      (latex :variables latex-enable-auto-fill t latex-enable-folding t)
      semantic lsp spell-checking syntax-checking)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER THREADS TOOLKIT_SCROLL_BARS ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
When I call this function I am seeing the following error in the message buffer:
`helm-M-x-execute-command: Calling ‘org-fold-core-region’ with missing SPEC`

I think this is related to an upstream issue, please report to the maintainers of `org-toc.el`.
