### ISSUE TITLE
spacemacs-evil layer accidentally damaged by recent PR

### ISSUE THREAD

**Issue by dankessler** [syl20bnr/spacemacs#16066]
A recently accepted PR (#16053) which was primarily about removing superfluous `progn`'s seems to have inadvertently made broad changes to the spacemacs-editing layer's `packages.el` file. 

[This link](https://github.com/syl20bnr/spacemacs/commit/4ec0b8b88f10fa9ac9c42811b65030532664d64d#diff-1cb355d2a8f6cd984f656c92fdef1400c375fd9b1c50bb68af74eb812109213d) will take you to the relevant diff (although it takes a while to load). Based on the changed copyright date, I think that a very old version of that file accidentally snuck in, and since the diff is so big it was probably just overlooked.

One of the consequences was to break the binding of `SPC j j` to `evil-avy-goto-char-timer` which was fixed in #16065, but the damage is much bigger than that. For example, a whole bunch of packages (e.g., `password-generator`, `evil-easymotion`, and many more) were removed from that layer. Indeed, I noticed the issue because `g s` no longer brought up `evil-easymotion`, and I went digging to figure out where it went.

It looks like some of the other accidental changes have already been addressed, e.g., 4d86d5c3cdb9bf8c5662c250de7a52f48d760c47 fixes damage to the `undo-tree` config, but there's still a lot of other unintended edits that need to be adddressed.

4ec0b8b88f10fa9ac9c42811b65030532664d64d's edits to the spacemacs-editing layer's `packages.el` file should probably be wholesale rolled back and then, to bring the file into line with what #16053 was trying to do, it should have its superfluous `progn`'s removed. Perhaps @equwal, the author of #16053, is in a good position to remedy this?

**Comment by smile13241324** [comment]
Should be fixed
