### ISSUE TITLE
Custom dumps `custom-set-variables` within `dotspacemacs/user-init`, borking `.spacemacs`

### ISSUE THREAD

**Issue by bryce-carson** [syl20bnr/spacemacs#16071]
I have observed Custom dumping its variables into the wrong spot multiple times today.

As far as I can tell, the steps to reproduce the issue are:

1. Have some stuff inside your `dotspacemacs/user-init`
2. Open your dotspacemacs for editing, and make some changes
3. Open the Customize interface, and make some changes and APPLY AND SAVE THEM FOR FUTURE SESSIONS
4. Quit Emacs, with or without saving .spacemacs
5. Reopen Emacs and your .spacemacs should be borked, with the following paragraph describing **_where_** `custom-set-variables` was dumped improperly.

It seems that `custom-set-variables` is inserted into `dotspacemacs/user-init` just before _the first trailing `s` character_ in a variable value of the `setq` form.

Previously, I had witnessed this occurring multiple times with `rmail-movemail-variant-in-use 'mailutil*s`, where `*` indicates where `custom-set-variables` was inserted. This happened multiple times, remember.

I have added a new variable, which happens to have a trailing `s` character in it's value: `rmail-movemail-flags (list "--tl*s")`, with `*` again indicating where `custom-set-variables` is inserted.

I already updated my packages and pulled the latest changes in an attempt to see if that would resolve it, with no such luck.

What a strange bug.

The portion the Custom inserts is the form beginning with `(custom-set-variables [...]` and ending with the final parenthesis in the file.

**Comment by smile13241324** [comment]
Strange 🤔, can you post your system details i.e. emacs version for further analysis?

**Comment by bryce-carson** [comment]
- GNU Emacs 28.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.38, cairo version 1.17.8) of 2023-06-05

What other information may be helpful?
#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. ef5c55dcf)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion
 emacs-lisp
 common-lisp
 git
 themes-megapack
 helm
 markdown
 info
 (shell :variables
        shell-default-height 30
        shell-default-position ’bottom
        shell-default-shell "vterm"
        terminal-here-linux-terminal-command ’gnome-terminal)
 syntax-checking)

```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM XWIDGETS GTK3 ZLIB
