### ISSUE TITLE
Python project : not part of any project prompt appears everytime

### ISSUE THREAD

**Issue by Corentin-pro** [syl20bnr/spacemacs#16070]
#### Description :octocat:
Spacemacs forget project files, when opening a file from a project the prompt `[file] is not part of any project` appears everytime.

The prompt shows the following options:
```
i ==> Import project root [...]
I ==> Import project by selecting root directory interactively
. ==> Import project at current directory [...]
d ==> Do not ask again for the current project by adding [...] to lsp-session-folders-blacklist
D ==> Do not ask again for the current project by selecting ignore path interactively
n ==> Do nothing: ask again when opening other files from the current project
```

After choosing an `Import project` option the prompt will still appear the next time the file is opened.
This bugs has been occurring for the past 3 years in the develop branch of spacemacs (fresh install included).

#### Reproduction guide :beetle:
- Start Emacs
- Open a python project's file that was already imported to a project (option `i`)

*Observed behaviour:* :eyes: :broken_heart:
`[file] is not part of any project` prompt appears.

*Expected behaviour:* :heart: :smile:
No prompt should appear (Spacemacs remembering projects)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 6fd09d315)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(go systemd rust javascript auto-completion better-defaults emacs-lisp csv yaml ivy
    (lsp :variables lsp-disabled-clients
         '(pyright))
    markdown multiple-cursors
    (shell :variables shell-default-height 30 shell-default-position 'bottom)
    syntax-checking
    (python :variables python-backend 'lsp python-fill-column 120)
    evil-commentary docker semantic treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by kassick** [comment]
I could not reproduce with a vanilla spacemacs, using the provided layers (python-language-server as lsp backend)

After I imported the file once, lsp would correctly memorize the project root and use it whenever I opened that file.

Does your `$HOME/.emacs.d/.cache/lsp/.lsp-session-v1` file gets updated when you ask to import the project root?

**Comment by Corentin-pro** [comment]
Using `cat $HOME/.emacs.d/.cache/lsp/.lsp-session-v1` I get

```
#s(lsp-session ("[path/to/project1]" "[path/to/project2]" "[path/to/project3]" [...]) nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ()))
```

I redacted the paths to `[path/to/projectX]` and added `[..]` because the list is quiet long.

If I exit emacs and start again then opening a file in [path/to/project1] (from recent open files or normally) the prompt appears.

Thanks to your insight on the session file I know now why the prompt is appearing : all my projects are inside a `~/work` directory. But because of the total size of this directory I created a symbolic link to an other storage (`/data/work`) so opening `/data/work/[path/to/project1]` will not prompt but `~/work/[path/to/project1]` will, although both open the same file.

Maybe the path should be resolved first.

Note : the path is always resolved somewhere as `~/work/[path/to/project1]` would never appear in the prompt (whether the file is open from ~/work or /data/work).

**Comment by Corentin-pro** [comment]
This seems to come from lsp-mode package from elpa (https://github.com/emacs-lsp/lsp-mode). I am digging the code to create a PR there. The issue doesn't come from spacemacs. Feel free to close this issue, I will if/when a PR is ready there (will link here).

**Comment by Corentin-pro** [comment]
PR created in the relevant package : https://github.com/emacs-lsp/lsp-mode/pull/4100
