### ISSUE TITLE
Vue layer kills nxml-mode

### ISSUE THREAD

**Issue by iinov** [syl20bnr/spacemacs#16084]
#### Description :octocat:
When I activate Vue layer, nxml mode is no longer linked to XML files 

#### Reproduction guide :beetle:
- activate Vue Layer
- open an XML file (*.xml)

*Observed behaviour:* :eyes: :broken_heart:
- web-mode is activated, not xml-mode

*Expected behaviour:* :heart: :smile:
- nxml-mode is activated

- I haven't found a workaround

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 4882f70e6)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion git helm lsp
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 version-control
                 (treemacs :variables treemacs-use-git-mode 'deferred)
                 spacemacs-base spacemacs-completion
                 (spacemacs-layouts :variables persp-autokill-buffer-on-remove t)
                 spacemacs-editing spacemacs-modeline spacemacs-navigation spacemacs-org nginx yaml protobuf
                 (python :variables python-test-runner 'pytest python-formatter 'yapf python-fill-column 79)
                 rust
                 (javascript :variables javascript-fmt-tool 'prettier)
                 (json :variables json-fmt-tool 'prettier)
                 vue iinov personal)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by iinov** [comment]
Actually, the problem seems to lie with the HTML layer.

**Comment by iinov** [comment]
Perhaps, you could simply remove the line` ("\\.xml\\'" . web-mode)` in the HTML layer.

**Comment by smile13241324** [comment]
still relevant

**Comment by iinov** [comment]
No. That's no longer the case.

Thank you.
