### ISSUE TITLE
YaSnippets broken

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1608]
# down to the `edit` might give best information 
I can no longer use `YaSnippets`

I don't really know why, for some reason no one else is talking about this.

This is my process of creating a snippet : 

In  a python file / buffer
`M-x` then `yas-new-snippet`
Create this snippet : 
```text
# -*- mode: snippet; require-final-newline: nil -*-
# name: something
# key: something
# binding: direct-keybinding
# --
just testing the snippets
```
`C-c C-c` to save the snippet
Choose python mode
`y` to new library or snippet
create file in `~/.emacs.d/private/snippets/python-mode` as `something`
that has saved

Then I'm back in the Python file. 
*`M-x yas-recompile-all` (not sure what the difference is between this command and `yas/recompile-all`)
This gives me an error (that doesn't hang around long enough to remember) about there not being a `~/.emacs.d/snippets` directory. 

What am I meant to do here? 

There was some sporadic advice in chat yesterday when I first encountered this issue but I'm not sure what it really was. 

I have tried making a `~/.emacs.d/snippets` dir. It stops the error message but I still can't complete anything from there

******

## edit

I had made the following change to my packages.el https://github.com/syl20bnr/spacemacs/pull/1601/files

I've changed this back. 

I have made the directory `snippets` in `~/.emacs.d/snippets` and a simple script that copies everything from `~/.emacs.d/private/snippets` to `~/.emacs.s/snippets`

I've then restarted spacemacs
I no longer have the command `yas-new-snippet` when running `M-x`
`SPC f e d` to go to config then going back to the python gave me this command (loaded yas?)

So then I make a new snippet: 

```text
# -*- mode: snippet; require-final-newline: nil -*-
# name: ben
# key: mike
# binding: direct-keybinding
# --

this is another test

```
`C-c C-c` to save snippet
python mode, new snippet, save as `ben`
Saves without error
Copy files from `private/snippets` to `~/.emacs.d/snippets`
Then from python file run `yas-recompile-all`
Then `yas-reload-all` - brings up about buffers editing live snips, say yes to close
******
I still can't `TAB` complete snippets, I get no prompt about snippets either. 
### But what DOES work 
is 
* writing the snippets trigger (eg `mike`) 
* exiting insert mode
* going to the end of the line
* adding an extra space
* exiting insert mode
* making sure that the cursor is at `mike|` not `mik|e`
* pressing `M-/` 
The snippet then completes, but this is a completely unusable work flow. 

Here's a link to a paste with my directory structure in it : 

http://vpaste.net/fyxsb

**Comment by TheBB** [comment]
Talked about this briefly on gitter and leaving my comments here for posterity. I do not have this problem, newly created snippets expand just fine (with `M-/`, mind, not `TAB`).

You shouldn't have to dance around insert and normal state to expand snippets. Just typing the key and hitting `M-/` in insert state is fine. Try that.

**Comment by autosquid** [comment]
```M-/``` expands keywords, but did not insert snippet in my case.

**Comment by person808** [comment]
@autosquid Are you typing out the snippet fully? For example, in `emacs-lisp` type `def` then `M-/` and it should expand the function snippet. Alternatively, use put this in your `.spacemacs` to show snippets in the autocomplete popup so you can select and expand them:

```elisp
(defun autocomplete-show-snippets ()
  "Show snippets in autocomplete popup"
  (let ((backend (car company-backends)))
    (unless (listp backend)
      (setcar company-backends `(,backend :with company-yasnippet)))))
```

**Comment by geo7** [comment]
@autosquid doesn't work for me either I just tried. 

@person808 don't really like the idea of some people having to add extra functions whilst other people claim it's working fine. 

Just tried one that's not working, process : 

In `.tex` file : 

`M-x` then `yas-new-snippet`


now in snippet buffer enter the following : 

```text
# -*- mode: snippet; require-final-newline: nil -*-
# name: test
# key: test
# binding: direct-keybinding
# --

is this actually going to work
```

then press `C-c C-c`


Select `latex-mode`

Say `yes` to new library / snippet option

Choose given name of `test`

Now back in `.tex` file 

`yas-recompile-all`

`yas-reload-all` --- as a note I'm not sure that these steps are needed?? I've just been doing them, UltiSnips loaded automatically as soon as one was entered though... 

On reload it mentions about some buffers having live snippets, I say `yes` to closing them

Yas says that it's reloaded everything

then I enter `test` onto a text line

* no prompt to indicate that there's a snippet available
* After pressing `M-/` it just puts a double asterisk. 


So they aren't working as far as I can see, unless there's something that I'm missing here.

**Comment by tuhdo** [comment]
It is currently broken and I fixed it with this PR: https://github.com/syl20bnr/spacemacs/pull/1676

**Comment by geo7** [comment]
@tuhdo OK cool. 

Is there anywhere that I should be checking in order to view what's broken / being fixed / recently fixed? I feel as though I might be being a bit negligent with the maintenance aspect. 

Re the PR: #1676 - I can just open up `contrib/auto-completion/packages.el` and alter the code as you have there? 

Thanks :)

**Comment by tuhdo** [comment]
Yes, the code is simple and you can add it yourself, then restart Emacs to see if yasnippet is now working.

**Comment by geo7** [comment]
not working with the snippet i made previously, i'll try making another one...

**Comment by tuhdo** [comment]
But does it expand properly now at least with the built-in snippets? If it can expand the built-in snippets, you will never be able to expand yours.

**Comment by geo7** [comment]
`yas-new-snippet`

```text
# -*- mode: snippet; require-final-newline: nil -*-
# name: test
# key: test
# binding: direct-keybinding
# --

this is yet another
test of something 
```


Yes to latex mode

new library or snippet ---> Weird seeing as its the same name as the previous one but `yes`

file name `test`, this should be a collision

let me save over test...

`yas-recompile-all`

`yas-reload-all` (closing live snippets)

enter `test` -> no popup appears to indicate there is a completion option

press `M-/` ---> the snippet completes.

**Comment by tuhdo** [comment]
So, you can expand your custom snippets now? Sound good.

And if you want to explore all available snippets in a major mode, use `SPC i s`. When you remember the frequently used one, just type the prefix of that snippet and `M-/`.

**Comment by geo7** [comment]
yep thanks @tuhdo 

I also found `yas/describe-tables`, but `SPC i s` is easier to enter... It's a shame that there isn't an info element to them as well, I guess I'll have to make more descriptive names for them for now

cheers

**Comment by tuhdo** [comment]
Great to hear that. Thanks.

You should not close this issue until the PR is merged and is in the master branch.

**Comment by geo7** [comment]
@tuhdo oh right no worries, re-opened it

**Comment by hijarian** [comment]
@geo7 Regarding your comment about the maintenance - it's a `develop` branch, regression errors are expected. Basically `git fetch; git checkout -b develop --track origin/develop` is signing the agreement to suffer. Cheers. ;)

**Comment by geo7** [comment]
@hijarian yes I understand that :) I was just wondering whether there were best daily practices whilst on this brach.
