### ISSUE TITLE
[shell] multi-vterm not work as expected

### ISSUE THREAD

**Issue by sunlin7** [syl20bnr/spacemacs#16086]
Use the `shell` layer with `multi-vterm` enabled, change to different directories and start the mutil-vterm with the key `SPC-a-t-s-M` (or `spacemacs/shell-pop-multivterm`), it only one vterm instance, it should has different vterms for different directories.

Layers configuration:
```emacs-lisp
(shell :variables shell-default-shell 'multi-vterm)
```

Or use follow lines to simulate the behavior, just one instance:
```emacs-lisp
(progn
  (let ((default-directory "~"))
    (spacemacs/shell-pop-multivterm nil))
  (let ((default-directory "/tmp"))
    (spacemacs/shell-pop-multivterm nil)))
```
For `multi-vterm`, two vterms will be created:
```emacs-lisp
(progn
  (let ((default-directory "~"))
    (multi-vterm))
  (let ((default-directory "/tmp"))
    (multi-vterm)))
```

@JoshTRN

**Comment by JoshTRN** [comment]
I'm worried that this is going to come off rude, so please know that I mean this is the best possible way, but I'm not sure where you got your expectations. To be fair, you may have gotten them from the multi-vterm docs as I haven't read them thoroughly.

Before I integrated multi-vterm, I was using multi-term. The same behavior exists there. You have to create multiple terminals at your leisure. It's not automatically creating a new terminal based on the directory you're currently in when you pop the shell, which is what I think you're asking for. Instead, when you pop the terminal, it will cd to your current directory. This is the same for the predecessor multi-term.  If you want a new terminal, then, while in a multi-vterm buffer, you can use the major mode key bindings (`SPC m` or I use `,` the default binding) to do various multi-vterm operations and which key to figure out what they are.

For example, `SPC m c` will create a new terminal. `SPC m n` will cycle to the next terminal etc.

I think you're proposing a feature that may be helpful to some users, but I use multi-vterm every day at work and the behavior you're describing is not how I use it. I use `SPC '` to open the shell and if I need separate terminals (for example, I run docker compose a lot), I'll create a new terminal using the major mode key bindings from the default multi-vterm buffer, start some process and then switch back to my main terminal.

If you wanted to develop this further and create a new feature that would be really cool!

Good luck!

**Comment by sunlin7** [comment]
Hi @JoshTRN 

Thanks for comment, I had run the `multi-vterm` function manually, it will create vterm for different directories, that's why the behavior of `spacemacs/shell-pop-multivterm` supirised me.

If current behavior is expected, it's OK for me. 

Close this ticket. Thanks.
