### ISSUE TITLE
"Package <x> is unavailable. Is the package name misspelled?"

### ISSUE THREAD

**Issue by bobf32** [syl20bnr/spacemacs#16098]
Hi, 

I've tried to install spacemacs on three different distros in the last day, including EndeavourOS, Debian 12 (fresh install) and Ubuntu 20.04. In every case once I start emacs and the initial package load starts, I get the following errors:

```
<snip>
--> installing package: overseer@emacs-lisp... [50/130]
Package overseer is unavailable. Is the package name misspelled?
--> installing package: open-junk-file@spacemacs-navigation... [52/130]
Package open-junk-file is unavailable. Is the package name misspelled?
--> installing package: multi-line@spacemacs-editing... [54/130]
Package multi-line is unavailable. Is the package name misspelled?
--> installing package: link-hint@spacemacs-editing... [57/130]
Package link-hint is unavailable. Is the package name misspelled?
--> installing package: indent-guide@spacemacs-editing-visual... [60/130]
Package indent-guide is unavailable. Is the package name misspelled?
--> installing package: hungry-delete@spacemacs-editing... [61/130]
Package hungry-delete is unavailable. Is the package name misspelled?
--> installing package: hl-todo@spacemacs-visual... [62/130]
Package hl-todo is unavailable. Is the package name misspelled?
--> installing package: highlight-numbers@spacemacs-editing-visual... [64/130]
Package highlight-numbers is unavailable. Is the package name misspelled?
<snip>
```

I've found a number of references to installing ```gnu-elpa-keyring-update``` which I have tried, but I'm not sure I'm doing exactly what is required. Unsurprisingly it's had no discernible effect.

Judging from the numbers, some packages are installed but many are not.

**Comment by smile13241324** [comment]
I am not able to reproduce your issue I have updated emacs to 29.1 two days ago and all packages installed without issues on my linux box.

Unfortunately you have not provided your system details so I don't know on which system you are running but mind that most missing packages issues come from gnu tls issues or conflicts with system packages.

Can you retry on linux and report back here?

**Comment by bobf32** [comment]
I think this issue was ultimately caused by the Malwarebytes app. I normally run the free version, but for some reason the full version was running at the time I was getting the above behaviour. Deactivating the full version and reverting to free fixed the issue in all cases.
