### ISSUE TITLE
Problem with helm

### ISSUE THREAD

**Issue by js-denton** [syl20bnr/spacemacs#16097]
Hello. I try started use spacemacs.
I added git layer then sync config and nothing changes - magit don't appear (i tryed also restart emacs and update packages)
Then i decided reinstall spacemacs from scratch: remove .spacemacs* and .emacs.d
Cloning spacemacs like firs.

Now i can't use emacs command like C-x f or M-x. I have only one message:
require: Symbol’s value as variable is void: helm-info-source
recompile elpa (M-m f e c) is not working from same error

What broken?
varsion: 0.999.0@28.2 (spacemacs-base)

**Comment by phenix-factory** [comment]
I have the same issue on a fresh install of spacemacs on a 29.1 emacs

**Comment by sunlin7** [comment]
Met similar issue, and I removed the `helm-info-*-*-.eln` then it works again. 
You can give a try on deleting the eln file for helm-info.

**Comment by js-denton** [comment]
Yea. Thanks @sunlin7 ! After remove this file - all works.
File placed on `~/.emacs.d/eln-cache/<emacs_version_number>-*/helm-info-*-*-.eln`
