### ISSUE TITLE
Issue of lsp-mode with dart-mode

### ISSUE THREAD

**Issue by hem1t** [syl20bnr/spacemacs#16094]
#### Description :octocat:
- lsp for flutter wouldn't start and gives out the following error in *Messages* buffer
```
[LSP Dart] Flutter command not found in path ’nil’
Error processing message (wrong-type-argument stringp 91).
```

- And *lsp-log* looks like:
```
Command "/home/hem1t/Applications/flutter/bin/cache/dart-sdk/bin/dart language-server --client-id emacs.lsp-dart --client-version 1.24.2" is present on the path.
Command "semgrep lsp" is not present on the path.
Command "/home/hem1t/Applications/flutter/bin/cache/dart-sdk/bin/dart language-server --client-id emacs.lsp-dart --client-version 1.24.2" is present on the path.
Command "semgrep lsp" is not present on the path.
Found the following clients for /home/hem1t/STORAGE/00_PROGRAMMING/01_PROJECTS/quicknews/lib/main.dart: (server-id dart_analysis_server, priority 1)
The following clients were selected based on priority: (server-id dart_analysis_server, priority 1)
This server does not support foldingRangeProvider
```

- running `lsp` gives out this error `helm-M-x-execute-command: Wrong type argument: stringp, 91`

- opening any another file after the first file, it gives out `Error running timer: (wrong-type-argument stringp 91)`

#### Reproduction guide :beetle:
- Start Emacs
- open a file from a flutter project.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 4882f70e6)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(shell-scripts themes-megapack auto-completion emacs-lisp git helm lsp multiple-cursors
               (shell :variables shell-default-height 15 shell-default-position 'bottom)
               syntax-checking neotree
               (kotlin :variables kotlin-backend 'lsp)
               (dart :variables 
                lsp-dart-sdk-dir "/home/hem1t/Applications/flutter/bin/cache/dart-sdk/" 
                flutter-sdk-path "/home/hem1t/Applications/flutter/"))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by smile13241324** [comment]
Hmmm this sounds like an issue with lsp-mode rather than with our code. Please have a look in the dart layer and open an issue for the package that builds the lsp server call command in their project.
