### ISSUE TITLE
Unexpected 'motion' state (e.g. instead of normal state); post Emacs 29 update

### ISSUE THREAD

**Issue by qazwsxpawel** [syl20bnr/spacemacs#16103]
I've just updated to emacs 29 (tried both emacs for osx and emacs-plus) and spacemacs seems to be 'randomly' switching from normal to motion states (cursor colour from orange to purple). 

This happens in all kinds of buffers (clojure, spacemacs config etc.). 

So far I've not observed any other abnormal behaviour (related to this switching or otherwise). Unfortunately I've not observed any regularity in this behaviour that might help troubleshooting (will keep this updated, if I have).

**Comment by qazwsxpawel** [comment]
One case I've identified where this happens is when eldoc information is displayed in echo area, i.e. whenever there is eldoc info associated with the symbol at point in the buffer I'm editing (NOTE: the point is in e.g. clojure buffer, but when eldoc info is displayed it goes from orange to purple).

**Comment by smile13241324** [comment]
I have seen this too but thought this came from my own emacs 29 build 🤔, so far I have not noticed any other side effects though.

If someone has the time a fix would be appreciated.

**Comment by polydevuk** [comment]
I'm also having this problem but with me (Ventura/Spacemacs devel/Emacs OS X 29.1) it's compounded by extremely janky vertical and horizontal motion whether I use h,j,k,l or arrow keys. I use Spacemacs mainly for Clojure dev and with a .clj file open the cursor is permanently pink/purple instead of yellow. I don't recall experiencing this with Emacs 28.2.

**Comment by einsiedlerspiel** [comment]
This is probably an evil mode issue https://github.com/emacs-evil/evil/issues/1835

**Comment by fnussbaum** [comment]
Fixed upstream in https://github.com/emacs-evil/evil/commit/d7c0f8f7f7f1a9469f35acd55d1dcb48b8989eb1. (As noted above this was a purely cosmetical issue, only the cursor colour was affected, not the actual evil state.)
