### ISSUE TITLE
How to maximize Emacs 29 at startup?

### ISSUE THREAD

**Issue by winsphinx** [syl20bnr/spacemacs#16106]
In Emacs 29, when set `dotspacemacs-maximized-at-startup t`, it dispears a maximized frame and shows a normal window with a broken white window at startup.

![image](https://github.com/syl20bnr/spacemacs/assets/5674054/87c78588-5eed-45c6-8db9-55f9382b8006)

Before Emacs 29, this option works well, but now how to maximize it?

**Comment by sunlin7** [comment]
I'm running the Emacs 29, didn't met this issue. Maybe special version issue? Switch your emacs version maybe help.

**Comment by winsphinx** [comment]
I think this is an atypical case, so i'll close this issue.

**Comment by SamHasler** [comment]
I'm seeing this to with emacs 29.4. I've worked around it by starting it up with:

```
runemacs.exe --geometry=235x70
``` 

which at least resize the window to almost full screen on my monitor before maximising it. I still get some white background but the frame is big enough that it's still readable during startup.
