### ISSUE TITLE
Shouldn't develop.spacemacs.org point to the develop branch?

### ISSUE THREAD

**Issue by tuxayo** [syl20bnr/spacemacs#16108]
Reading #15995 I though "yes, because develop.spacemacs.org likely points to the actual recommended and maintained branch: develop and it's a while no one should use the master branch IIUC."

But no. The install instructions still point to the master.zip and the git clone is a default one so the master branch.

**Comment by practicalli-johnny** [comment]
`develop` has been the default branch for several years, so the clone command on the main spacemacs.org and on develop.spacemacs.org will clone the correct branch.

If someone does download the zip install approach, they will still get version 0.200 the older stable release though, from 17th September 2022.
