### ISSUE TITLE
Adopt org-project-capture over direct use of org-projectile

### ISSUE THREAD

**Issue by colonelpanic8** [syl20bnr/spacemacs#16126]
org-projectile has been generalized into org-project-capture, which supports both projectile and project as backends.

The variables and functions defined in org-projectile other those related to the `org-project-capture-projectile-backend`  class are now all deprecated. They should be replaced with the equivalent ones from org-project-capture.

Also, it might make sense to allow users to use org-project-capture with the project backend which may require slightly different configuration.

**Comment by bcc32** [comment]
I think this is still a good idea.

**Comment by smile13241324** [comment]
Still relevant
