### ISSUE TITLE
Can I update all packages by bash script?

### ISSUE THREAD

**Issue by JaydenFish** [syl20bnr/spacemacs#16133]
I want to update packages and spacemacs by bash script. click update button is troublesome. 
I can update spacemacs by `git pull --rebase`. But how to update packages by bash script?

**Comment by real-or-random** [comment]
The button is bound to the function `configuration-layer/update-packages`, which you can also run via `SPC f e U`.

If you want to run it from the command line, you should try `emacs --funcall=configuration-layer/update-packages`. (Or `emacs --eval=<expr>` if you need a more flexible alternative that takes arbitrary expressions, see `man emacs`.) I haven't tried this, and I'm not sure if this works. Updating packages is a somewhat involved operation, so something is at odds when you call it from the command line. But it's worth a try, and I agree that it could be convenient after `git pull`.

**Comment by McPhale** [comment]
I was able to do that by following this stack exchange post:  https://emacs.stackexchange.com/a/45923
