### ISSUE TITLE
How to launch spacemacs?

### ISSUE THREAD

**Issue by delaaxe** [syl20bnr/spacemacs#16139]
The documentation doesn't say anything about how to open spacemacs. There are no executables in the repo nor build instructions. The readme just saying "launch it" doesn't help either.

Vim may be notoriously hard to quit but spacemacs is even harder to open.

**Comment by henriquenj** [comment]
You launch your locally installed Emacs. Spacemacs will then be loaded.

**Comment by practicalli-johnny** [comment]
If more of a guide to Spacemacs is required, take a look at https://practical.li/spacemacs/

This is a free online book covering a range of aspects of Spacemacs.

**Comment by delaaxe** [comment]
thanks, wasn't clear to me spacemacs was just a plugin and not a standalone
