### ISSUE TITLE
spacemacs-layouts are broken

### ISSUE THREAD

**Issue by catesandrew** [syl20bnr/spacemacs#16138]
I retrieved latest from develop about a week ago and started noticing the layouts were broken. Tried getting latest packages from melpa, new clone from spacemacs develop, and it continues to be broken. Anyone else noticing `SPC l p` and its ilk are broken too?

**Comment by practicalli-johnny** [comment]
`SPC l p` is working using the latest commits from Spacemacs and updated Emacs packages.  I've never used that key binding before, so not experienced any braking changes.

> I typically use `SPC TAB` to jump between current and previous layouts, or `SPC l l` and use helm to narrow to the desired layout name (I have a lot of layouts, anywhere from 10-30+

**Comment by andrew-hm** [comment]
Please close this now, you saved me, thank you. I did just get latest again and its working. Must of been an elpa package bug up the chain somehwhere.
