### ISSUE TITLE
Modeline is broken

### ISSUE THREAD

**Issue by rihardsk** [syl20bnr/spacemacs#16150]
#### Description :octocat:
After spacemacs upgrade and package upgrade, modeline doesn't show anything in the active window, it's just a blank line. Every other window (non-focused) shows stuff as expected, though. In \*Messages\* I get
```
Error during redisplay: (eval (spaceline-ml-main)) signaled (void-function treesit-available-p) [45 times]
```
which seems related.

#### Reproduction guide :beetle:
- Start Emacs
- Notice broken modeline

*Observed behaviour:* :eyes: :broken_heart:
Broken modeline

*Expected behaviour:* :heart: :smile:
Modeline shows stuff

#### System Info :computer:
- OS: gnu/linux
- Emacs: 28.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. b86a07443)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(typescript yaml vimscript java
            (groovy :variables groovy-backend 'lsp groovy-lsp-jar-path "/home/rihards/.local/lib/groovy-language-server-all.jar")
            javascript emacs-lisp git helm
            (lsp :variables lsp-rust-server 'rust-analyzer)
            dap rust python cmake nixos
            (ipython-notebook :variables ein-backend 'jupyter)
            docker
            (search-engine :variables search-engine-config-list
                           '((kagi :name "Kagi" :url "https://kagi.com/search?q=%s")))
            markdown multiple-cursors org
            (shell :variables shell-default-shell 'vterm shell-default-width 40 shell-default-position 'right)
            (spell-checking :variables spell-checking-enable-by-default nil)
            treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11 XDBE XIM XPM GTK3 ZLIB

**Comment by spt29** [comment]
I have the same problem. I update spacemas + all packages every morning, yesterday things worked, now they don't. Spacemacs itself didn't change, but the package update pulled in 3 new package versions:

- centered-cursor-mode-20230911.1503 => centered-cursor-mode-20230914.1358
- helm-20230909.1649 => helm-20230919.442
- helm-core-20230910.424 => helm-core-20230916.1702

Rolling back those packages make the modeline work again, so it must be a new bug in one of those packages.

**Comment by ghost** [comment]
Same here.

Spacemacs ver. 0.999
Emacs ver. 29.1

Last thing I did before logging off yesterday was to update with update-packages.

Today I open my Emacs session and the modeline is empty. 
![modeline_gone_1](https://github.com/syl20bnr/spacemacs/assets/131940764/0182f86b-de9f-459a-af6b-8090cb226144)

If I call find-file the modeline reappears, at least until I quit the Helm window.
![modeline_gone_2](https://github.com/syl20bnr/spacemacs/assets/131940764/97d4f473-e8a0-45c0-9940-fff2a2443f77)

Warnings thrown

Error during redisplay: (eval (spaceline-ml-main)) signaled (void-variable treesit-inspect-mode) [9 times]
Error during redisplay: (eval (spaceline-ml-main)) signaled (void-variable treesit-inspect-mode) [5 times]

**Comment by prestancedesign** [comment]
Same here.

Temporary fix that I use, disable `treesiter-inspect`  using `spaceline-toggle-treesit-inspect-off` function.

The bug is coming from `spaceline-segments.el` package.
An issue has already been opened: https://github.com/TheBB/spaceline/issues/240

**Comment by rihardsk** [comment]
The upstream issue is closed https://github.com/TheBB/spaceline/issues/240, updating to latest spaceline resolves the issue. Closing.
