### ISSUE TITLE
Warning (emacsql): Since your Emacs does not come with built-in SQLite support [1], but does support C modules, the best EmacSQL backend is provided by the third-party `sqlite3' package [2].

### ISSUE THREAD

**Issue by SamuelBanya** [syl20bnr/spacemacs#16159]
Description:
On Linux Mint 21.2 using the default Cinnamon desktop, I used the 'git clone' install instructions for Spacemacs.

Observed Behavior: 
I get these annoying messages from Magit that warn about sqlite3:
```
⛔ Warning (emacsql): Since your Emacs does not come with
built-in SQLite support [1], but does support C modules, the best
EmacSQL backend is provided by the third-party `sqlite3' package
[2].

Please install the `sqlite3' Elisp package using your preferred
Emacs package manager, and install the SQLite shared library
using your distribution's package manager.  That package should
be named something like `libsqlite3' [3] and NOT just `sqlite3'.

In the current Emacs instance the legacy backend is used, which
uses a custom SQLite executable.  Using an external process like
that is less reliable and less performant, and in a few releases
support for that might be removed.

[1]: Supported since Emacs 29.1, provided it was not disabled
     with `--without-sqlite3'.
[2]: https://github.com/pekingduck/emacs-sqlite3-api
[3]: On Debian https://packages.debian.org/buster/libsqlite3-0
```

Expected Behavior: 
Spacemacs should stop warning me about this.

System Info 💻

    OS: Linux Mint 21.2 Cinnamon
    Emacs: 29.1
    Spacemacs: 0.999.0
    Spacemacs branch: Whatever the default is
    Graphic display: t
    Running in daemon: nil
    Distribution: Spacemacs
    Editing style: Vim
    Completion: Helm
    Layers:

     auto-completion
     better-defaults
     emacs-lisp
     git
     graphql
     helm
     html
     lsp
     json
     markdown
     multiple-cursors
     org
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     spell-checking
     syntax-checking
     version-control
     themes-megapack
     (typescript :variables
                 typescript-linter 'eslint
                 typescript-fmt-tool 'prettier
                 typescript-backend 'lsp)
     treemacs
     (ranger :variables
             ranger-show-preview t)
     spacemacs-prettier

Backtrace:
None

**Comment by wallrj** [comment]
I was annoyed too, but I finally took the time to read the instructions in the message and managed to compile the sqlite3 package on my Ubuntu environment.

```
sudo apt install libsqlite3-dev
```
Added the following to my `.spacemacs` file

```lisp
...

dotspacemacs-additional-packages '(
                                      sqlite3
                                      )
...

(defun dotspacemacs/user-config ()
  (require 'sqlite3)
)

```

When I restarted emacs, it prompted me to compile `sqlite3-api` and I no longer get the annoying warning.

**Comment by SamuelBanya** [comment]
That worked, thanks for this.

On Wed, Oct 11, 2023, at 7:52 AM, Richard Wall wrote:
> 
> 
> I was annoyed too, but I finally took the time to read the instructions in the message and managed to compile the sqlite3 package on my Ubuntu environment.
> 
> `sudo apt install libsqlite3-dev
`
