### ISSUE TITLE
Spaceline reverts separator to default upon moving the window

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#16152]
#### Description :octocat:
When Spacemacs starts I see the separator I set in .spacemacs
When moving the window Spacemacs inmediately changes the separator and the height back to the default

#### Reproduction guide :beetle:
- Edit .spacemacs
- dotspacemacs-mode-line-theme '(spacemacs :separator arrow-fade)
- Save file and quit the program
- Start Spacemacs again

*Observed behaviour:* :eyes: :broken_heart:
- Separator arrow-fade is there after starting Spacemacs
- Move the window
- Default separator replaces arrow-fade

This also happens when opening any file
- SPC f f
- Default separator replaces arrow-fade

*Expected behaviour:* :heart: :smile:
- Move the window
- Separator defined in .spacemacs stays

#### System Info :computer:
- OS: gnu/linux (Kubuntu 23.04)
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. b86a07443)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html javascript rust python
      (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete)
      emacs-lisp git helm multiple-cursors syntax-checking version-control treemacs
      (helm :variables helm-enable-auto-resize t helm-no-header t)
      helpful
      (org :variables org-enable-roam-support t)
      themes-megapack
      (auto-completion :disabled-for org git))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM XWIDGETS GTK3 ZLIB

#### Backtrace :paw_prints:
- None, Spacemacs doesn't throw any errors or warnings.
- There's no *Warnings* buffer on startup.
- emacs --debug-init doesn't throw errors or warnings.
- Combing through *Messages* doesn't show any package had an error.

**Comment by smile13241324** [comment]
Given that this is almost a year old I am going to close it and ask the author to reopen if this issue is still relevant
