### ISSUE TITLE
Smartparens mode gets disabled after auto-completing with yasnippet in Go mode.

### ISSUE THREAD

**Issue by rinconjc** [syl20bnr/spacemacs#16155]
#### Description :octocat:
Smartparens mode gets disabled after auto-completing with yasnippet in Go mode.

#### Reproduction guide :beetle:
- Start Emacs
- Ensure you have Go and auto-complete layers enabled
- Create a Go buffer
- Type `func` and press `M-/`. The function snippet will be activated.
- Type the function name, then press TAB to enter the func arguments, type  any argument e.g. `x int` press TAB again
- Type the return type, e.g. `int` press TAB. It should activate the comments line, and pressing again should move the caret to function body
- Press ESC and type any paired char, e.g. `{` `"`. It should automatically insert the closing char, but it doesn't, because the smartparens mode is off now.
- Pressing SPC+t+p will enable the smartparens mode

*Observed behaviour:* :eyes: :broken_heart:

- Smartparens becomes disabled when the auto-complete is triggered for multi-level yasnippet snippets.

*Expected behaviour:* :heart: :smile:
- Smartparens mode should still be enabled after the yasnippet/auto-completion has finished.

*Potential solution:*
- I found a possible solution for the above and it seems to work, so I'm keen to raise a PR for it.
- Basically, given that the smartparens is disabled in the auto-completion hook, the `spacemacs--smartparens-enabled-initially` seems to lose its original value when there's are nested snippets. So the fix is to ensure that the original value (enabled) is preserved.

```elisp
(defvar spacemacs--smartparens-enabled-initially nil
  "Stored whether smartparens is originally enabled or not.")

(defun spacemacs//smartparens-disable-before-expand-snippet ()
  "Handler for `yas-before-expand-snippet-hook'.
Disable smartparens and remember its initial state."
  ;; Remember the initial smartparens state only once, when expanding a top-level snippet.
  (setq spacemacs--smartparens-enabled-initially (or spacemacs--smartparens-enabled-initially smartparens-mode smartparens-strict-mode))
  (spacemacs//deactivate-smartparens))
```

#### System Info :computer:
- OS: darwin
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. b86a07443)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((haskell :variables haskell-completion-backend 'lsp)
 docker
 (clojure :variables clojure-backend 'lsp clojure-enable-fancify-symbols nil clojure-enable-linters 'clj-kondo cider-save-file-on-load t clojure-enable-clj-refactor t cider-default-cljs-repl 'figwheel-main)
 sql csv nginx typescript ruby
 (rust :variables rust-format-on-save t)
 (go :variables godoc-at-point-function 'godoc-gogetdoc go-backend 'lsp go-format-before-save t go-use-golangci-lint t)
 html
 (javascript :variables javascript-repl `nodejs js-indent-level 4)
 web-beautify
 (yaml :variables yaml-enable-lsp t)
 python java
 (kotlin :variables kotlin-backend 'lsp kotlin-lsp-jar-path "/opt/kotlin-lsp/bin/kotlin-language-server")
 (groovy :variables groovy-backend 'lsp groovy-lsp-jar-path "/opt/groovy-language-server-all.jar")
 auto-completion better-defaults emacs-lisp git helm lsp dap markdown multiple-cursors org
 (shell :variables shell-default-height 30 shell-default-shell 'vterm shell-default-position 'bottom)
 (shell-scripts :variables shell-scripts-format-on-save t)
 spell-checking syntax-checking treemacs
 (terraform :variables terraform-backend 'lsp terraform-auto-format-on-save t)
 search-engine plantuml)
```
- System configuration features: ACL GLIB GMP GNUTLS JPEG JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
Solution sounds good PR would be welcome
