### ISSUE TITLE
clang-format not loaded 

### ISSUE THREAD

**Issue by janemba** [syl20bnr/spacemacs#16163]
Hello,

Spacemacs doesn't seem to load my clang-format config which uses `Allman` style formatting.\

My C code is formatted that way:

```
while (1)
   {
   }
```

It look like google style and I don't know where to check in spacemacs.

My config variables is the following:
```
     (lsp :variables lsp-lens-enable t
          :variables lsp-modeline-diagnostics-scope :file
          :variables lsp-headerline-breadcrumb-segments '(project file symbols))
     (c-c++ :variables c-c++-backend 'lsp-clangd
            :variables c-c++-lsp-enable-semantic-highlight 'rainbow
            :variables c-c++-lsp-semantic-highlight-method 'overlay
            :variables c-c++-backend 'rtags
            :variables c-c++-enable-clang-format-on-save t
            :variables  clang-format-style "auto")
```

How can I fix it ?

**Comment by alexey0308** [comment]
Hi @janemba,  in the config you set the backend twice: clangd and rtags. Does it work if you remove the rtags line?

**Comment by janemba** [comment]
@alexey0308 

Thanks it works.
