### ISSUE TITLE
Android Development

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#1616]
Any emacs (spacemacs) guru could please give some ideas on how to use emacs (spacemacs) for android development. I don't want to use android-mode couse is based on ant and I want to use the latest graddle build tool that Android is using. I've heard that I can be done with ensime but haven't found any docs explaining how to write pure java android projects with that in emacs.

**Comment by jupl** [comment]
[Looks like Gradle support was added to android-mode nearly a year ago](https://github.com/remvee/android-mode/pull/39)
