### ISSUE TITLE
How to disable documentation lookup in Python layer?

### ISSUE THREAD

**Issue by mixmixmix** [syl20bnr/spacemacs#16161]
Whenever I open a parenthesis after a name of an existing function in Python I get a massive popup with possible arguments. Example below. It is super annoying. I think this isn't any of the minor modes but (maybe?) pylookup which is built into the major layer.

How can I disable it?

![Screenshot 2023-10-13 at 09 16 17](https://github.com/syl20bnr/spacemacs/assets/9990867/e1a160d8-34eb-4ef2-8f9e-413724306a57)

**Comment by alexey0308** [comment]
does setting the configuration of the lsp mode in the dotspacemacs-layers as
```
     (lsp :variables
          lsp-signature-auto-activate nil)
```

or doing M-x `lsp-toggle-signature-auto-activate` solve the problem?

Also you can tweak the number of lines with `lsp-signature-doc-lines`.

**Comment by mixmixmix** [comment]
Thanks. Though, I don't have lsp layer active. I'll try toggle it and see if it'll override the lookup I have now.

Otherwise, is there maybe an option when running in debug mode to find out where this pop-up is coming from?

**Comment by alexey0308** [comment]
you can take a look on eldoc-mode, or you may consider using issue template with posting your setup - it might be that some of the maintainers could help you with it then.

You can use M-x profiler-start profiler-stop profiler-report commands to find out what are the functions being called.

**Comment by mixmixmix** [comment]
Thanks so much @alexey0308. Profiler was just what I needed to understand what is going on. It is indeed `eldoc-mode` and now I can configure/disable it to my liking.

**Comment by mixmixmix** [comment]
I cannot find the way to disable it automatically. Any help would be appreciated. I tried 
```
(defun dotspacemacs/user-config ()
  (global-eldoc-mode -1)
  (add-hook 'python-mode-hook (lambda () (flycheck-mode -1)))
  (add-hook 'python-mode-hook (lambda () (anaconda-eldoc-mode -1)))
  (add-hook 'python-mode-hook (lambda () (eldoc-mode -1)))
)
```
But whenver I open python file it is active and I have to manually disable it by running `M-x eldoc-mode`

I guess it is fairly simple but configuring modes is black magic to me and cannot find any approchable documentation

**Comment by alexey0308** [comment]
You can try to remove the function hook which is responsible for the setting (I just found it by grepping the configuration of spacemacs - you can check how eldoc is set in the python layer code)
```
   (remove-hook 'python-mode-local-vars-hook 'spacemacs//python-setup-eldoc)
```

**Comment by mixmixmix** [comment]
That worked! Many thanks @alexey0308.
