### ISSUE TITLE
How disable `semantic-idle-summary-mode` in `emacs-lisp-mode`

### ISSUE THREAD

**Issue by sfavazza** [syl20bnr/spacemacs#16179]
*Cotext*

Recently I enabled the `semantic` layer. Working on lisp files I realized that Eldoc does not show documentation in the echo area anymore. 

*Root cause*

I could trace the issue to the `semantic-idle-summary-mode` . When manually disabled, Eldoc works again.

*Possible solution*

I dig into the `emacs-lisp` layer and tried the following code:
```emacs-lisp

(defun emacs-lisp/post-init-semantic ()
  (add-hook 'emacs-lisp-mode-hook 'semantic-mode)
  ;; (with-eval-after-load 'semantic
  ;;   (semantic-default-elisp-setup))
  )

``` 

Though I don't know what is the consequence of removing `(semantic-default-elisp-setup)`. Any thoughts about the consequences?

I also tried, w/o success:
```emacs-lisp
(with-eval-after-load 'semantic
    (semantic-default-elisp-setup)
    (semantic-idle-summary-mode -1))
``` 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. b86a07443)
- Graphic display: t
- Running in daemon: mars
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-idle-delay 0.0 auto-completion-minimum-prefix-length 1 auto-completion-enable-help-tooltip 'manual auto-completion-private-snippets-directory "~/snippets" company-show-quick-access 'left company-selection-wrap-around t)
 bm
 (c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-clangd c-c++-lsp-enable-semantic-highlight 'rainbow)
 (cmake :variables cmake-enable-cmake-ide-support t)
 cscope csv
 (dap :variables dap-auto-configure-features
      '(tooltip)
      dap-python-debugger 'debugpy)
 (docker :variables docker-container-shell-file-name "/bin/bash" docker-compose-command "docker compose" docker-tramp-use-names t docker-dockerfile-backend 'lsp)
 emacs-lisp eww git go graphviz
 (helm :variables helm-no-header nil helm-position 'top)
 html javascript
 (lsp :variables lsp-pylsp-configuration-sources
      ["pydocstyle"]
      lsp-enable-indentation nil lsp-navigation 'peek lsp-ui-remap-xref-keybindings t lsp-ui-doc-include-signature t lsp-lens-enable t lsp-headerline-breadcrumb-segments
      '(project file symbols)
      lsp-warn-no-matched-clients nil lsp-clients-clangd-args
      '("--header-insertion=never"))
 lua
 (markdown :variables markdown-live-preview-engine 'vmd)
 multiple-cursors org
 (python :variables python-fill-column 112)
 (ranger :variables ranger-enter-with-minus nil ranger-override-dired nil ranger-cleanup-on-disable nil ranger-show-hidden t ranger-parent-depth 1 ranger-show-literal nil)
 rust semantic
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-vterm shell-default-term-shell "/bin/bash" multi-term-program "/bin/bash" shell-enable-smart-eshell t)
 shell-scripts
 (spacemacs-language :variables google-translate-default-target-language "en")
 (spell-checking :variables enable-flyspell-auto-completion nil ispell-dictionary "en_US" ispell-program-name "hunspell")
 systemd yaml vue)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XAW3D XDBE XIM XINPUT2 XPM LUCID ZLIB

**Comment by Sergey-Makarov** [comment]
Hey! Just my 5 cents after some digging into the code.

When enabling `semantic-idle-summary-mode`, the following line of code is executed.

    (add-hook 'eldoc-documentation-functions #'semantic--eldoc-info nil t)

The `semantic--eldoc-info` function essentially makes `eldoc-mode` useless (at least inside elisp buffers) by returning `t` instead of `nil` and thus not allowing the consecutive functions inside `eldoc-documentation-functions` to provide an actual result. Not sure what is the reasoning behind that.

Anyways, this dirty code fixes the problem for me:

    (eval-after-load 'semantic/idle
      (advice-add #'semantic--eldoc-info
                  :filter-return (lambda (res)
                                   (if (eq res t)
                                       nil
                                     res))))

This issue seems to be related to Emacs itself rather than Spacemacs distro though, but I currently don't have time to figure out where and how to open that issue (have never done that before :) )

**Comment by sfavazza** [comment]
Hi, thanks for your reply. To be honest I already turned the layer off, its periodic function frequently clog the echo area with not so meaningful error messages about buffers I'm not even working on.

That said, as it seems not related to spacemacs, this issue might be closed.

What's your opinion @smile13241324?

**Comment by emacs18** [comment]
I'm wondering if the following could actually be a bug fix:
```diff
diff --git a/lisp/cedet/semantic/idle.el b/lisp/cedet/semantic/idle.el
index 58f162e67f7..746c714ca88 100644
--- a/lisp/cedet/semantic/idle.el
+++ b/lisp/cedet/semantic/idle.el
@@ -736,15 +736,16 @@ specific to a major mode.  For example, in jde mode:
   "Return the eldoc info for the current symbol.
 Call `semantic-idle-summary-current-symbol-info' for getting the
 current tag to display information."
-  (or (eq major-mode 'emacs-lisp-mode)
-      (not (semantic-idle-summary-useful-context-p))
-      (let* ((found (save-excursion
-                      (semantic-idle-summary-current-symbol-info)))
-             (str (cond ((stringp found) found)
-                        ((semantic-tag-p found)
-                         (funcall semantic-idle-summary-function
-                                  found nil t)))))
-        str)))
+  (if (eq major-mode 'emacs-lisp-mode)
+      nil ;; returning t breaks eldoc.  See https://github.com/syl20bnr/spacemacs/issues/16179 
+    (or (not (semantic-idle-summary-useful-context-p))
+        (let* ((found (save-excursion
+                        (semantic-idle-summary-current-symbol-info)))
+               (str (cond ((stringp found) found)
+                          ((semantic-tag-p found)
+                           (funcall semantic-idle-summary-function
+                                    found nil t)))))
+          str))))
 
 (define-minor-mode semantic-idle-summary-mode
   "Toggle Semantic Idle Summary mode.
```

The key change is to return `nil` in `emacs-lisp-mode` rather than returning `t`.  If folks agree that this could be a bug fix, I can submit this patch to `emacs-devel` email list.

**Comment by smile13241324** [comment]
I think this would be a bug fix @emacs18

**Comment by smile13241324** [comment]
As this is no Spacemacs bug I am closing it for now.
