### ISSUE TITLE
Using a "Spacemacs/restart" function results in a  wrong number of arguments error (Emacs 29.1)

### ISSUE THREAD

**Issue by ViktorHaag** [syl20bnr/spacemacs#16185]
#### Description :octocat:
Using one of the "spacemacs/restart" calls results in a "wrong number of
arguemnts (0.0), 1" error.

#### Reproduction guide :beetle:
- Start Emacs 29
- Use "M-m q r" to quit

*Observed behaviour:* :eyes: :broken_heart:
- Quitting using one of the "spacemacs/restart-" functions does not quit, but
throws the wrong number of arguments error.

It appears that spacemacs is attempting to pass a "--resume-layouts" argument
down into the Emacs fundamental "restart-emacs" method, which in 29.1 seems to
be a method that does not take any parameters.

This seems like a core bug.

I have tried doing this from a fresh install of both Emacs _and_ Spacemacs and the error occurs.

I _believe_ that this commit here might be involved: https://github.com/syl20bnr/spacemacs/commit/91f6b2d1668811a0b78353c421c0719d261a7653 (see PR #16178).

Reverting that change seems to fix the issue.

*Expected behaviour:* :heart: :smile:
Emacs should restart

#### System Info :computer:
- OS: darwin
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: old-local-python-mode (rev. 8d3fb1704) (Personal fork)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: (compleseus denote-personal emacs-lisp git html ibuffer-personal javascript local-functions markdown multiple-cursors org osx python-personal restructuredtext syntax-checking tern theming treemacs yaml)
- Layers:
```elisp
(compleseus denote-personal emacs-lisp git html ibuffer-personal
            (javascript :variables js-switch-indent-offset 4)
            local-functions markdown multiple-cursors
            (org :variables org-enable-github-support t org-enable-org-journal-support t)
            (osx :variables osx-command-as 'meta osx-option-as 'super osx-control-as 'control osx-function-as nil)
            python-personal restructuredtext syntax-checking tern theming
            (treemacs :variables treemacs-use-icons-dired nil)
            yaml)
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE PDUMPER SQLITE3 THREADS TOOLKIT_SCROLL_BARS TREE_SITTER XWIDGETS ZLIB

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (wrong-number-of-arguments (0 . 0) 1)
  restart-emacs(("--resume-layouts"))
  spacemacs/restart-emacs(("--resume-layouts"))
  spacemacs/restart-emacs-resume-layouts()
  funcall-interactively(spacemacs/restart-emacs-resume-layouts)
  call-interactively(spacemacs/restart-emacs-resume-layouts nil nil)
  command-execute(spacemacs/restart-emacs-resume-layouts)

```

**Comment by ViktorHaag** [comment]
I notice that [this open issue](https://github.com/iqbalansari/restart-emacs/issues/23) on `restart-emacs` suggests the source of the problem is a function naming collision with a core Emacs function introduced with Emacs 29.

I wonder if the suggestion in that issue of requiring `files` as a dependency of loading `restart-emacs` is expedient here? So, instead of 
```
defun spacemacs-navigation/init-restart-emacs ()
  (use-package restart-emacs
    ;; :after files ;; this was what we had before the recent commit
    :defer (spacemacs/defer)
    :init
    (spacemacs/set-leader-keys
...
```

we could instead have
```
defun spacemacs-navigation/init-restart-emacs ()
  (use-package restart-emacs
    :require files
    ;; :defer (spacemacs/defer) ;; was switched to defer in recent commit
    :init
    (spacemacs/set-leader-keys
...
```

A quick test of this code-change locally seems like it would work, but I'm no expert about package loading complexities nor am I set up to do thorough testing of changes to spacemacs.

**Comment by sunlin7** [comment]
The PR #16186 should fix the issue.

**Comment by ViktorHaag** [comment]
> The PR #16186 should fix the issue.

Thank you very much!

**Comment by ViktorHaag** [comment]
The PR does seem to address this issue, so I'm comfortable closing.

**Comment by sunlin7** [comment]
Thanks for your confirmation.
