### ISSUE TITLE
spacemacs|use-package-add-hook does not work anymore on emacs 29.1.90

### ISSUE THREAD

**Issue by zylthinking** [syl20bnr/spacemacs#16189]
Same configuration, works on emacs 28.2 and does not work any more on 29.1.90.
helm/pre-init-auto-highlight-symbol  has been called, but the hook will not be called.

I can make it work again by calling it in .spacemaces explicitly. 

```lisp
(defun helm/pre-init-auto-highlight-symbol ()
  (spacemacs|use-package-add-hook auto-highlight-symbol
    :post-init
    ;; add some functions to ahs transient states
    (setq spacemacs--symbol-highlight-transient-state-doc
          (concat
           spacemacs--symbol-highlight-transient-state-doc
           "  Search: [_s_] swoop  [_b_] buffers  [_f_] files  [_/_] project"))
    (spacemacs/transient-state-register-add-bindings 'symbol-highlight
      '(("s" spacemacs/helm-swoop-region-or-symbol :exit t)
        ("b" spacemacs/helm-buffers-smart-do-search-region-or-symbol :exit t)
        ("f" spacemacs/helm-files-smart-do-search-region-or-symbol :exit t)
        ("/" spacemacs/helm-project-smart-do-search-region-or-symbol :exit t)))))
```

**Comment by emacs18** [comment]
Can you explain what you mean by "works"?  What does above code do?  I tried enabling auto-highlight-symbol-mode.  This indeed highlights the symbol under cursor with red background for me.  With symbol highlighted like this, am I supposed to be able to type s to execute spacemacs/helm-swoop-region-or-symbol command?  If so, then this does not work for me.  Typing s, b, f, or / with highlighted symbol does nothing different, i.e., enabling auto-highlight-symbol-mode makes no difference.

I tried emacs 28.2 and 29.1.  Both behave the same for me.

**Comment by zylthinking** [comment]
It seems the post-init section does not get called. So the swoop/buffers/... does not show in the panel.

While, I made it worked by copying the code of

```
(setq spacemacs--symbol-highlight-transient-state-doc
      (concat
       spacemacs--symbol-highlight-transient-state-doc
       "  Search: [_s_] swoop  [_b_] buffers  [_f_] files  [_/_] project"))
(spacemacs/transient-state-register-add-bindings 'symbol-highlight
  '(("s" spacemacs/helm-swoop-region-or-symbol :exit t)
    ("b" spacemacs/helm-buffers-smart-do-search-region-or-symbol :exit t)
    ("f" spacemacs/helm-files-smart-do-search-region-or-symbol :exit t)
    ("/" spacemacs/helm-project-smart-do-search-region-or-symbol :exit t)))
```

and adding it to .spacemacs file, e.g. call it by myself when initialization.

**Comment by emacs18** [comment]
Can you explain what you mean by "make it work"?

**Comment by zylthinking** [comment]
I called the code by myself, not by post-init, which seems does not get called

**Comment by zylthinking** [comment]
What I got by default:
![2024-01-02_23-42](https://github.com/syl20bnr/spacemacs/assets/1066931/5a296cd0-7564-463e-8fcf-65b02496e618)

What I got by calling it by myself
![2024-01-02_23-44](https://github.com/syl20bnr/spacemacs/assets/1066931/e825dba7-9204-41cf-b280-cf3a92559397)

**Comment by emacs18** [comment]
Thanks for your info.  How do you enter this "Symbol Highlight Transient State"?  After I type `M-x global-auto-highlight-symbol', I can see that the symbol under cursor is highlighted.  However I don't know how to activate this transient state.

**Comment by zylthinking** [comment]
M-x spacemacs/enter-ahs-forward

**Comment by emacs18** [comment]
Thanks.  So the entry point of this transient statie is * which is bound to spacemacs/enter-ahs-forward or # which is bound to spacemacs/enter-ahs-backward.  This works in all versions of emacs that I tested, i.e., if I were to 
- load a C++ file
- M-x auto-highlight-symbol-mode RET
- hit * while the symbol under the cursor is hilighted

The last step enters the symbol hilight transient state showing s, b, f, and / key bindings among others.

I tested emacs 28.2, 29.1, 29.1.90, and 30.0.50 on Ubuntu 22.04.
If your 29,.1.90 does not work, perhaps you should try rebuilding it with latest source code.

**Comment by smile13241324** [comment]
Seems to be an issue with the user's environment, as this is a manually compiled emacs version I would close this ticket until there is some indication that this is our bug.
