### ISSUE TITLE
Incompatibility with latest typescript-language-server CLI arguments

### ISSUE THREAD

**Issue by programmador** [syl20bnr/spacemacs#16195]
Spacemacs is on latest revision of `develop` branch at 2023-11-20.

ts-ls stderr contents:
```
error: unknown option '--tsserver-path'

Process ts-ls stderr finished
```
Reason:
* https://github.com/typescript-language-server/typescript-language-server/blob/master/CHANGELOG.md#410-2023-11-08
* https://github.com/typescript-language-server/typescript-language-server/pull/790

Similar issue:
* https://github.com/doomemacs/doomemacs/issues/7540

**Comment by alexey0308** [comment]
Hi @programmador, is not this covered with [this](https://github.com/emacs-lsp/lsp-mode/pull/4202/files) fix upstream? does it help to update the packages?

**Comment by programmador** [comment]
TS LSP seems to work after running `configuration-layer/upate-packages` Thank You!
