### ISSUE TITLE
Words in README for mu4e layer

### ISSUE THREAD

**Issue by davidpiano** [syl20bnr/spacemacs#16193]
Installation instructions are contradictory:

* Install
In order to use this layer you must install =mu= and =mu4e= separately.
Typically =mu4e= will be bundled with =mu= (this is the case on many Linux
distributions).

Something like the following might be better:

* Install
In order to use this layer you must install two applications on your system, =mu= and =mu4e=.
On many Linux distributions they are bundled together, but make sure you have both before proceeding.

**Comment by smile13241324** [comment]
Sounds good, would you mind opening a PR for it?

**Comment by davidpiano** [comment]
I'm willing, but have never opened a PR before, or made any contribution to anything. I'll go and try it - I assume it's not difficult.

**Comment by smile13241324** [comment]
Yeah its really pretty easy just do your work in your fork based on develop, then propose the PR you can do this via githubs web ui and I will have a look.
