### ISSUE TITLE
Layer subdirectories

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#1619]
Currently, some layers can be found in subdirectories (`lang`, `irc`, etc.). This is a great idea, but the allowable subdirectories are [hardcoded](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L99), preventing the user from organising e.g. private layers in a similar fashion.

It would not be difficult to discover layers in arbitrary subdirectories, since a layer is (presumably) uniquely identified by the existence of `packages.el` or `extensions.el`.

**Comment by syl20bnr** [comment]
As we discussed in the PR spacemacs is not yet ready for such feature.
I keep the issue opened and add it to the milestone since we will be able to provide such feature in the v2 of the configuration layers (planned for the v1.0.0 of spacemacs).
