### ISSUE TITLE
Empty buffer opens when selecting a help-git-grep result

### ISSUE THREAD

**Issue by JuanCaicedo** [syl20bnr/spacemacs#16201]
Hi everyone!

#### Description :octocat:
When I'm trying to search within my code base and open a result, an empty buffer opens instead.

#### Reproduction guide :beetle:
- run a search with `SPC g /` from within a git project
- type in some text
- highlight a result and press `enter`

*Observed behaviour:* :eyes: :broken_heart:
- An empty buffer opens with this name
    ```
    mouse-1: select candidate
    mouse-3: menu actions
    ```

*Expected behaviour:* :heart: :smile:
- The selected code should open in a new buffer

#### System Info :computer:
- OS: darwin
- Emacs: 28.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 8f7019340)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go
 (typescript :variables typescript-backend 'tide typescript-linter 'eslint typescript-fmt-tool 'prettier typescript-lsp-linter nil)
 sql python elixir html clojure emoji typescript nginx docker csv helm emacs-lisp elm git
 (node :variables node-add-modules-path t)
 javascript tide
 (keyboard-layout :variables kl-layout 'dvp)
 markdown neotree org osx ruby yaml shell-scripts)
```
- System configuration features: ACL GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

#### Other info
I've tried to disable all mouse actions within my editor by adding this code.
```emacs
(defun dotspacemacs/user-config ()

  (define-key evil-normal-state-map (kbd "<C-down-mouse-1>") 'nothing)
  (define-key evil-normal-state-map (kbd "<M-down-mouse-1>") 'nothing)
  (define-key evil-normal-state-map (kbd "<mouse-2>") 'nothing)
  (define-key evil-normal-state-map (kbd "<M-drag-mouse-1>") 'nothing)
  (define-key evil-normal-state-map (kbd "<M-mouse-1>") 'nothing)
  (define-key evil-normal-state-map (kbd "<M-mouse-2>") 'nothing)
  (define-key evil-normal-state-map (kbd "<M-mouse-3>") 'nothing)
  (define-key evil-normal-state-map (kbd "<S-mouse-1>") 'nothing)
  (define-key evil-normal-state-map (kbd "<S-mouse-2>") 'nothing)
  (define-key evil-normal-state-map (kbd "<S-mouse-3>") 'nothing)
  (define-key evil-normal-state-map (kbd "<mouse-3>") 'nothing)
  (dolist (mouse '("<down-mouse-1>" "<mouse-1>"))
    (global-unset-key (kbd mouse)))

```

However I still see the same behavior even if I comment that out

**Comment by alexey0308** [comment]
Hi @JuanCaicedo,

it seems to be an upstream issue, please check the solution mentioned here https://github.com/yasuyk/helm-git-grep/issues/52. 

Although not a direct solution, but I find using e.g. `ag` much faster to search the code base.

**Comment by JuanCaicedo** [comment]
Thanks for that tip! I added `  (setq helm-allow-mouse nil)` to my spacemacs file and that fixed it 😀
