### ISSUE TITLE
How to set keys with left/right option keys in dotfile

### ISSUE THREAD

**Issue by OlekRia** [syl20bnr/spacemacs#16209]
I am using a USA standard keyboard layout on my MacOS, but also I use a lot of German text. How may I bind :
ä to right-option-a
ü to right-option-u
ö to right-option-o
?

P.S. For MacOS usually I use Karabiner to assign keys. However, it doesn't work in Emacs; so I switched it off for Emacs.

**Comment by alexey0308** [comment]
Hi @OlekRia, I'm afraid emacs does not recognize left/right option keys, but you can [map](https://emacs.stackexchange.com/questions/24902/for-macos-how-to-bind-left-and-right-option-keys-separately) the right option key to e.g. `hyper` or `meta`.

Then adding to the `user-config` the bindings should work:

```
(define-key evil-insert-state-map (kbd "H-a")
  '(lambda () (interactive) (insert "ä")))

(define-key evil-insert-state-map (kbd "H-A")
  '(lambda () (interactive) (insert "Ä")))
```

**Comment by smile13241324** [comment]
@OlekRia did this work for you or do you need further help? If it did help please close the ticket.

**Comment by smile13241324** [comment]
No answer in 4 days, ticket will be closed.
