### ISSUE TITLE
`SPC *` not working with ripgrep 14

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#16200]
#### Description :octocat:

`SPC *` `(spacemacs/helm-project-smart-do-search-region-or-symbol)` stopped working.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file in a project, say `.emacs.d/init.el`
- Move cursor over any word
- Press `SPC *`

*Observed behaviour:* :eyes: :broken_heart:
`Invalid CLI arguments: unexpected argument for option '--ignore': ".#*"`

*Expected behaviour:* :heart: :smile:
Search results based on the pattern.

#### System Info :computer:
Brand new spacemacs install with just the defaults.
- OS: darwin
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 8f7019340)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: ACL GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE PDUMPER SQLITE3 THREADS TOOLKIT_SCROLL_BARS TREE_SITTER XWIDGETS ZLIB

- ripgrep 14.0.2

(Fairly sure it broke with update to 14 and was working with 13.)

**Comment by gbastkowski** [comment]
I "fixed" it for now by removing `rg` from dotspacemacs-search-tools.
Last night I saw that I could get it working with rg by setting another variable from `t` to `nil`. But have no idea anymore which variable that was.

**Comment by humitos** [comment]
I'm experimenting the same issue and I wasn't able to solve it by myself exploring the Emacs code.

**I solved it for now by downgrading ripgrep to version 13.** In Archlinux I ran the following command and selected version 13.

```
sudo downgrade ripgrep
```

**Comment by gbastkowski** [comment]
My quick workaound: `(setq helm-ag-use-grep-ignore-list nil)`

**Comment by emlun** [comment]
I have the same issue. Seems related to emacsorphanage/helm-ag#388: notice that [`helm-ag--grep-ignore-list-to-options`](https://github.com/emacsorphanage/helm-ag/blob/501af5cc7d9e9ae4473d84ba1ffb047ad8ef7fae/helm-ag.el#L189-L198) adds `--ignore` arguments, but ripgrep needs these to be `--glob` or `--iglob` arguments.

**Comment by BenedictHW** [comment]
I use ag and not rg, does https://github.com/emacsorphanage/helm-ag/pull/394 work with rg 14? Seems to pass the right arguments.
```
    (let ((got (helm-ag--construct-command nil))
          (expected '("rg" "--no-heading" "--glob=!*.md" "--glob=!*.el" "foo")))
```

**Comment by JoshTRN** [comment]
I have the same issue with `SPC /`, but  @gbastkowski's suggestion worked for me as well.

**Comment by johnnywalker** [comment]
@BenedictHW I can confirm that https://github.com/emacsorphanage/helm-ag/pull/394 works with rg 14. Here's my solution:

1. Override `helm-ag` to use branch from PR:

```elisp
   dotspacemacs-additional-packages
   '(
     ;; support rg 14
     ;; https://github.com/syl20bnr/spacemacs/issues/16200
     (helm-ag :location (recipe
                         :fetcher github
                         :repo "zozowell/helm-ag"
                         :branch "further-support-rg")))
```

2. Remove existing package: `SPC SPC package-delete` and type/select `helm-ag`

3. Restart Emacs: `SPC q r`

**Comment by smile13241324** [comment]
Thanks for the analysis guys :), I am going to change our target to https://github.com/emacsorphanage/helm-ag/pull/394 to keep spacemacs working.

**Comment by fred-apex-ai** [comment]
I updated to the latest develop branch including cb5f5b2, restarted spacemacs but still had the issue, so I downgraded ripgrep to v13.0.0 instead. Now I can search again

**Comment by metaspace** [comment]
> I updated to the latest develop branch including cb5f5b2, restarted spacemacs but still had the issue, so I downgraded ripgrep to v13.0.0 instead. Now I can search again

I had to uninstall `helm-ag` and reload spacemacs to make the change take effect. The package is not reinstalled automatically. Maybe the version number was not bumped or something :shrug:

**Comment by pataquets** [comment]
Confirmed:
Simply deleting `helm-ag` package and letting Spacemacs reinstall it fixed the problem right away.
Thanks!

``` console
$ rg --version
ripgrep 14.1.0 (rev e50df40a19)
```
