### ISSUE TITLE
"No bookmark name given for record" when setting bookmark from dired buffer

### ISSUE THREAD

**Issue by shedatc** [syl20bnr/spacemacs#16212]
#### Description :octocat:
Trying to set a bookmark via `helm-filtered-bookmarks` from a dired buffer fail
due to `helm-pattern` being the empty string. The error message displayed is `No
bookmark name given for record`.

The current action for `helm-source-bookmark-set` is:
```elisp
(lambda (candidate)
  (if (string= helm-pattern "")
      (message "No bookmark name given for record")
      (bookmark-set candidate)))
```
The following change looks OK to me:
```elisp
(lambda (candidate)
  (bookmark-set (read-string "Bookmark name: " nil nil helm-pattern)))
```

#### Reproduction guide :beetle:
- Start Emacs
- Jump into some dired buffer
- Hit `SPC f b` to run `helm-filtered-bookmarks`
- Select the `Enter a bookmark name to record` entry and hit `RET`

*Observed behaviour:* :eyes: :broken_heart:
It yell at me saying `No bookmark name given for record`!

*Expected behaviour:* :heart: :smile:
IMHO it should either guess or ask for the bookmark name to record.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. c46a22da1)
- Graphic display: t
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp
                 (git :variables git-gutter-use-fringe t)
                 helm lua
                 (org :variables org-directory "~/ens/org")
                 python yaml sheda-core sheda-org sheda-coding
                 (keyboard-layout :variables kl-layout 'bepo :packages
                                  (not twittering-mode)))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

#### Backtrace :paw_prints:
Not relevant.

**Comment by alexey0308** [comment]
Hi @shedatc, it looks like an upstream issue of `helm`, maybe it makes sense to create a PR with your fix there?

**Comment by shedatc** [comment]
OK @alexey0308, will do!

**Comment by smile13241324** [comment]
Thanks guys, @shedatc please open an upstream issue and link it here. I am going to close this ticket until there is some work for us to do.
