### ISSUE TITLE
Setting vterm as default shell doesn't work with SPC ' shell-pop

### ISSUE THREAD

**Issue by manjaroblack** [syl20bnr/spacemacs#16210]
#### Description :octocat:
VTerm not working in shell pop.

#### Reproduction guide :beetle:
- Start Emacs
- SPC f e d
- dotspacemacs-configuration-layers
   '((shell :variables shell-default-shell 'vshell))
- SPC f e R
- SPC '

*Observed behaviour:* :eyes: :broken_heart:
shell-pop does not open, generates an error:
wrong type argument: commandp, spacemacs/shell-pop-vshell

*Expected behaviour:* :heart: :smile:
SPC ' should open vterm in the shell-pop
SPC a t s v works just fine and open vterm

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 8f7019340)
- Graphic display: t
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm javascript lsp markdown multiple-cursors org
                 (shell :variables shell-default-shell 'vshell shell-default-term-shell "/home/linuxbrew/.linuxbrew/bin/nu" shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking typescript version-control treemacs web-mode)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
Your config is wrong! You have used vshell but it is vterm. The layer will subsequently try to access a non existent function hence the error.

**Comment by manjaroblack** [comment]
Wow, thank you. I can’t believe I was blind to that. It is working now.
