### ISSUE TITLE
invalid CLI arguments: unexpected argument for option '--ingore': ".#*"

### ISSUE THREAD

**Issue by tkossak** [syl20bnr/spacemacs#16214]
When I try to search using eg: `SPC s r f` (or others like `SPC s r b`, `SPC s d`, etc) I get error:
```
invalid CLI arguments: unexpected argument for option '--ingore': ".#*"
```

Any ideas how to fix it? Thank you

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. c46a22da1)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors org treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

**Comment by BenedictHW** [comment]
Good evening,

Please check out this issue and confirm if your issue is a duplicate: https://github.com/syl20bnr/spacemacs/issues/16200

Merry Christmas and a happy new year,

**Comment by tkossak** [comment]
Yes, this is duplicate, I'm closing it. 
Thank you and God bless you and yours.
