### ISSUE TITLE
Support lexical as a language server provider for Elixir

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#16219]
Currently the Elixir layer only supports `alchemist` or `elixir-ls`. [lexical](https://github.com/lexical-lsp/lexical) is a new language server that has worked for me on some larger projects where `elixir-ls` fails (e.g. autocompletion list doesn't pop up). It would be great to have lexical support as well.

**Comment by x-ji** [comment]
For now I have been able to make it work by manually adding

```
  (use-package elixir-mode
    :ensure t
    :custom
    (lsp-elixir-server-command '("~/Projects/Elixir/lexical/_build/dev/package/lexical/bin/start_lexical.sh")))
```

in `dotspacemacs/user-config`.

**Comment by smile13241324** [comment]
I have added some instructions for using lexical. Can you do a short test and close this ticket when its ok?

**Comment by smile13241324** [comment]
Please reopen when its not working, thanks.

**Comment by x-ji** [comment]
Hi @smile13241324 thanks for the update. Though just setting 

```
  (elixir :variables elixir-backend 'lsp
                     lsp-elixir-server-command "*path to folder*/lexical/bin/start_lexical.sh")
```

 as described in the instructions doesn't seem to work for some reason. I get the error

```
Error running timer: (wrong-type-argument listp "~/Projects/Elixir/lexical/_build/dev/package/lexical/bin/start_lexical.sh")
```

I had to also add 

```
  (use-package elixir-mode
    :ensure t
    :custom
    (lsp-elixir-server-command '("~/Projects/Elixir/lexical/_build/dev/package/lexical/bin/start_lexical.sh")))
```

under `user-config` as I described.

Did that work for you?

**Comment by x-ji** [comment]
(And seems that I don't have the permission to reopen it. I can only add comments.)

**Comment by smile13241324** [comment]
Ups, that variable needs a list not a string....

Ok the correct line for your dotfile should be:
```elsip
     (elixir :variables elixir-backend 'lsp
             lsp-elixir-server-command '("*path to folder*/lexical/bin/start_lexical.sh"))
```

Can you have another go @x-ji?

**Comment by x-ji** [comment]
@smile13241324 Thanks, this works!
