### ISSUE TITLE
shifting left/right shifts a block inconsistent number of spaces

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#1621]
Given multiple lines that are properly aligned, e.g.
```python
hello(test,
      world)
```
and shifting those right with visual selection or line count followed by <kbd>>></kbd> shifts the first line the right amount but the second one is left behind breaking the alignment, e.g. from above you get
```python
    hello(test,
        world)
```
Similarly when shifting left the first line is shifted the right amount but the followup lines are shifted less. Seems like they're always re-aligned as off by 2 spaces regardless of number of times <kbd>>></kbd> is repeated. Apparently the lines are realigned correctly only when the initial indentation on the followup lines is a multiple of the shift width.

**Comment by syl20bnr** [comment]
In which mode do you see this behavior ?

**Comment by tko** [comment]
vi + visual/normal

**Comment by tko** [comment]
Looks like
```elisp
(setq-default evil-shift-round nil)
```
fixes/works around this issue.

**Comment by syl20bnr** [comment]
Interestig finding.
What I meant by `mode` is `major-mode` of Emacs, for instance `python-mode` or `haskell-mode` etc...
To prevent confusion we prefer to call vi modes, `evil states` instead.

**Comment by tko** [comment]
Ah. Got similar behavior at least in python, c, and javascript modes.
