### ISSUE TITLE
Warning: Ignoring :requires for package counsel-projectile because layer spacemacs-layouts does not own it.

### ISSUE THREAD

**Issue by bebound** [syl20bnr/spacemacs#16229]
Show this message when start up.
I'm using the latest version on Mac.

Repro step:
1. Clone spacemasc
2. Start emacs
3. Select vim - standard distribution 
4. This warning appears
<img width="550" alt="Screenshot 2024-01-02 at 21 31 14" src="https://github.com/syl20bnr/spacemacs/assets/2227874/e19a6303-ac83-4e02-b108-ae16faa5e61a">

**Comment by sebhahn** [comment]
the warning comes from PR #16215 containing the commit 3afe307aa92c4eca819c5a698a540b5509952ec7

**Comment by smile13241324** [comment]
@bcc32 can you have a look?

**Comment by bcc32** [comment]
Sorry about that.  20cded5 looks like the correct fix, thanks :)
