### ISSUE TITLE
Request To Update Readme For 'EditorConfig' With Mention Of 'dotspacemacs-additional-packages'

### ISSUE THREAD

**Issue by SamuelBanya** [syl20bnr/spacemacs#16230]
I would like to request a revision for the Readme for Spacemacs to please mention 'EditorConfig' in terms of 'HOW' to actually install it.

There is no mention of if its a Spacemacs layer, because whenever I tried to declare it as a layer, it told me it was an 'unknown' layer.

Therefore, the readme should be updated to include the fact that you have to add this as an additional package.

The only way I got this to work was to add this within the 'Additional Packages' section, aka the 'dotspacemacs-additional-packages' section via this snippet:
```
   ;; List of additional packages that will be installed without being wrapped
   ;; in a layer (generally the packages are installed only and should still be
   ;; loaded using load/require/use-package in the user-config section below in
   ;; this file). If you need some configuration for these packages, then
   ;; consider creating a layer. You can also put the configuration in
   ;; `dotspacemacs/user-config'. To use a local version of a package, use the
   ;; `:location' property: '(your-package :location "~/path/to/your-package/")
   ;; Also include the dependencies as they will not be resolved automatically.
   ;; NOTE: Adding sqlite3 to force Spacemacs to shut up about Magit Mode:
   dotspacemacs-additional-packages '(
                                      sqlite3
                                      vterm
                                      editorconfig)
```

Thanks.

**Comment by SamuelBanya** [comment]
Specific README section:
- https://develop.spacemacs.org/doc/DOCUMENTATION.html#editorconfig

**Comment by smile13241324** [comment]
Sorry this package is part of `spacemacs-editing` which is automatically loaded. So if you follow the instructions this is install the binary package required for this, Spacemacs will take care to provide the necessary emacs files for this to work.

This is at least true when you are using the standard distribution, if you are using base this package may not be included.

Unfortunately I cannot provide any assistance as I am missing the asked for system information during the ticket workflow, in other words please add your system information and retry with an empty user config, then reopen if the issue persists.
