### ISSUE TITLE
Helm error "invalid function: add-function" for Emacs 24.4 on develop branch

### ISSUE THREAD

**Issue by drmikehenry** [syl20bnr/spacemacs#1624]
Hi,

I tried to upgrade Emacs from 24.3 to 24.5, at which point when I launch Helm I get the following error:
``Error (use-package): helm :config: Invalid function: add-function``
In addition, the mapping of TAB in helm windows reverts back to toggling the action menu.

The same thing occurs in Emacs 24.4.  New in Emacs 24.4 is the package ``nadvice.el`` which provides ``add-function`` and ``remove-function``, which may have something to do with this problem.  I've downgraded back to Emacs 24.3 as a work-around.

Michael Henry

**Comment by syl20bnr** [comment]
When you upgrade the version of Emacs, be sure to wipeout the `~/.emacs.d/elpa` directory and relaunch Emacs in order to reinstall all the packages with the new version.

**Comment by drmikehenry** [comment]
Thanks!  That fixed the problem, both for Emacs 24.4 and 24.5.  I hadn't realized that the Emacs version would influence the contents of ```~/.emacs.d/elpa```.  Is this documented somewhere that I missed?  I'm just getting started with Spacemacs, so I may well have overlooked this piece of advice.  It also might be helpful to mention this trick in the installation notes, perhaps near this section: https://github.com/syl20bnr/spacemacs#emacs-version

Thanks again for the help; this answers my question completely.

**Comment by TheBB** [comment]
The packages are all bytecode compiled upon installation, so it's not so far fetched that they are bound to a particular version of Emacs after that. I haven't seen it stated explicitly, however.

**Comment by cies** [comment]
Made the same mistake. Google'ing for the error already points here :)

**Comment by pscollins** [comment]
For future people who stumble on this from Google: it's enough to go into your `~/emacs.d` and run

    find -name "*.elc" -delete

After that, I was able to run emacs fine.
