### ISSUE TITLE
Can't use ripgrep/rg search symbol in project

### ISSUE THREAD

**Issue by ccruquan** [syl20bnr/spacemacs#16243]
#### Description :octocat:
Can't use ripgrep/rg search symbol in project

#### Reproduction guide :beetle:
- Start Emacs
- Open a project
- Use rg search symbol in project "SPC s r p"
- Type a word 

*Observed behaviour:* :eyes: :broken_heart:
A message says `rg: invalid CLI arguments: unexpected argument for option '--ignore': ".#*"`

*Expected behaviour:* :heart: :smile:
Use ripgrep/rg search symbol in project

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 3d84b0117)
- Graphic display: t
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(windows-scripts auto-completion
                 lsp
                 git
                 (git :variables git-enable-magit-delta-plugin t git-enable-magit-delta-plugin t git-enable-magit-gitflow-plugin t)
                 helm
                 emacs-lisp
                 go
                 (go :variables go-backend 'lsp go-tab-width 4 go-format-before-save t godoc-at-point-function 'godoc-gogetdoc gofmt-command "goimports")
                 python
                 (python :variables python-backend 'lsp python-lsp-server 'pyright python-formatter 'black python-format-on-save t python-save-before-test t)
                 evil-better-jumper
                 )
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by ccruquan** [comment]
I check the key binding 'SPC s r p' and find the function `spacemacs/helm-project-do-rg`.
https://github.com/syl20bnr/spacemacs/blob/3d84b01172d68f09791210d7de385f596ccf26b7/layers/%2Bcompletion/helm/funcs.el#L173

Then I read the code of `helm-ag`.

`helm-ag` use '--ignore' option for ignore files:
https://github.com/emacsorphanage/helm-ag/blob/501af5cc7d9e9ae4473d84ba1ffb047ad8ef7fae/helm-ag.el#L189

Then I find the option '--ignore' is not used for ignore files in `ripgrep` doc.
https://github.com/BurntSushi/ripgrep/blob/648a65f1976cc3b7eb66425024649d71d5befe1e/doc/rg.1.txt.tpl#L90C38-L90C38

`ripgrep` use '--iglob'/'--glob' option for ignore files.

**Comment by alexey0308** [comment]
it looks like a duplicate https://github.com/syl20bnr/spacemacs/issues/16200

**Comment by ccruquan** [comment]
thanks
