### ISSUE TITLE
In Hybrid mode, `set-mark-command' in Emacs mode switches to evil normal mode.

### ISSUE THREAD

**Issue by jaeyeom** [syl20bnr/spacemacs#16251]
#### Description :octocat:
In Hybrid mode, `set-mark-command' in Emacs mode switches to evil normal mode.

It should remain in Emacs mode.

#### Reproduction guide :beetle:
- Make sure you're in hybrid mode by setting `dotspacemacs-editing-style' value
to 'hybrid.
- Start Emacs
- Switch to scratch buffer with SPC b s.
- Press i to switch to insert mode.
- Type a few lines of text
- Press C-SPC or C-@ to invoke set-mark-command.
- Try to navigate with "hjkl" or C-"fbnp".

*Observed behaviour:* :eyes: :broken_heart:
- It moves cursor with "hjkl" as in evil normal mode.
- It triggers other functions with C-"fbnp" instead of forward, backward characters.

*Expected behaviour:* :heart: :smile:
- It should still be in Emacs mode, so "C-fbnp" should work and "hjkl" shouldn't
move the cursor.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 3d84b0117)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t c-c++-enable-clang-format-on-save t)
                 dart docker emacs-lisp eww git
                 (go :variables go-backend 'lsp go-use-golangci-lint t go-format-before-save t gofmt-command "goimports")
                 (helm :variables helm-show-completion-display-function #'helm-show-completion-default-display-function)
                 html
                 (javascript :variables js2-strict-missing-semi-warning nil)
                 lsp markdown multiple-cursors
                 (notmuch :variables notmuch-spacemacs-layout-name "@Notmuch" notmuch-spacemacs-layout-binding "n")
                 (org :variables org-agenda-files
                      (directory-files-recursively
                       (file-truename "~/Documents/projects")
                       "\\.org$")
                      org-enable-roam-support t org-enable-roam-ui t org-roam-directory
                      (file-truename "~/Documents/roam/"))
                 pass
                 (python :variables python-formatter 'yapf python-format-on-save t)
                 react reddit search-engine
                 (shell :variables shell-default-full-span nil shell-default-shell 'eshell)
                 slack spacemacs-org syntax-checking treemacs
                 (typescript :variables typescript-fmt-on-save t typescript-fmt-tool 'typescript-formatter)
                 version-control w3m yaml)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

**Comment by bcc32** [comment]
Maybe try `M-x debug-on-entry evil-normal-state`?  I can't reproduce this, and I use hybrid-mode.

**Comment by jaeyeom** [comment]
I think this bug is fixed now. I could reproduce it no matter how many times I restart Emacs 2 days ago. I could still reproduce it today (Emacs was still running), and the issue disappeared after I restart Emacs today to try out `emacs -nw`. After that it works on both terminal and GUI. I saw some update after the restart and that probably fixed it.

@bcc32, Thank you for taking a look at the issue. I think we can close it, since it works now.
