### ISSUE TITLE
nishimaki10/emacs-phpcbf doesn't exist anymore?

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#16259]
Hello,

Got an error updating packages, turnout https://github.com/nishimaki10/emacs-phpcbf return a 404 error.

**Comment by smile13241324** [comment]
hmpf, looks like this package is gone for good. I am removing it from the php layer.

**Comment by pataquets** [comment]
Experienced this, too.
@smile13241324 It would have saved quite some time at troubleshooting this to have some sort of progress information message in the message buffer, such as `Checking package XXXX` to quickly pinpoint the offending package.
I can either file an issue for the FR or even try tackling the issue myself, if some guidance is provided (mainly, which function would be the outermost one to add the message to).

**Comment by differentMonster** [comment]
@smile13241324 Hi, may i know how do you remove from php layer ? is kind bugging my spacemacs keep telling me is error, thanks you.

**Comment by smile13241324** [comment]
> @smile13241324 Hi, may i know how do you remove from php layer ? is kind bugging my spacemacs keep telling me is error, thanks you.

You can remove the entire layer from your dotfile. If you have an issue with a specific package you should post your error message and I can have a look.

**Comment by differentMonster** [comment]
Oh i found a way for spacemacs to prevents installing those unavailable package, by adding the package name into 

`   dotspacemacs-excluded-packages
   '(phpcbf
   )
`

so the error is gone now :D, thanks your @smile13241324 , your comment lead me to found it.
