### ISSUE TITLE
Julia latex tab-complete not working in julia-mode

### ISSUE THREAD

**Issue by john-waczak** [syl20bnr/spacemacs#16265]
#### Description :octocat:
Julia latex substitution is not working in julia-mode. Usually when working on julia code I can substitute typical latex symbols by typing the latex equivalent and then hitting tab. This behavior does work in a julia-repl mode but I can not seem to make it work in the standard julia-mode.

#### Reproduction guide :beetle:
- Start Emacs
- Open a julia file (ending in .jl) in julia-mode
- Type a known latex symbol, e.g. \psi, and then hit TAB

*Observed behaviour:* :eyes: :broken_heart:
- Nothing happens

*Expected behaviour:* :heart: :smile:
- \psi should be replaced with ψ

#### System Info :computer:
- OS: darwin
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. b2511bba4)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(lua d rust csv javascript octave yaml html auto-completion better-defaults emacs-lisp helm markdown multiple-cursors
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking python julia docker treemacs)
```
- System configuration features: ACL GLIB GMP GNUTLS JPEG JSON LIBXML2 MODULES NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by alexey0308** [comment]
Hi @john-waczak, please take a look at https://github.com/JuliaEditorSupport/julia-emacs/issues/193

This behaviour was removed, but it might be merged back.
You still can [activate](https://github.com/gcv/julia-snail/issues/124#issuecomment-1605855363) `abbrev-mode` and after hitting space it will automatically substitute the symbol for you.

It does not look like spacemacs issue then.

**Comment by john-waczak** [comment]
Thank you!
