### ISSUE TITLE
Enabling OpenAI layer constantly raising errors on start-up or when I try to call dall-e directly

### ISSUE THREAD

**Issue by SemyonSinchenko** [syl20bnr/spacemacs#16270]
#### Description :octocat:
Errors in openai layer

#### Reproduction guide :beetle:
- Start Emacs
- Have an openai layer enabled

*Observed behaviour:* :eyes: :broken_heart:
Error on startup or on a trying to call `dall-e/new`:
```
Error (use-package): dall-e/:catch: Eager macro-expansion failure: (wrong-number-of-arguments (4 . 4) 6)
```

Maintainer of `dall-e` package told me that the problem is not in the `dall-e` package itself, but in how spacemacs works with `tblui`.

Link to the his comment in issue, that I raised in dall-e repository:
[https://github.com/emacs-openai/dall-e/issues/3#issuecomment-1920221981](https://github.com/emacs-openai/dall-e/issues/3#issuecomment-1920221981)

*Expected behaviour:* :heart: :smile:
No error.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. b86a07443)
- Graphic display: nil
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml
 (html :variables css-enable-lsp nil less-enable-lsp nil scss-enable-lsp nil html-enable-lsp nil web-fmt-tool 'web-beautify)
 web-beautify json
 (python :variables python-formatter 'black python-backend 'lsp python-lsp-server 'pylsp lsp-disabled-clients
         '(pyright)
         lsp-pylsp-plugins-black-enabled nil lsp-pylsp-plugins-flake8-enabled nil lsp-pylsp-plugins-isort-enabled t lsp-pylsp-plugins-mccabe-enabled nil)
 (nixos :variables nix-backend 'lsp)
 lsp
 (rust
  (setq-default dotspacemacs-configuration-layers
                '(lsp :variables lsp-rust-server 'rust-analyzer)))
 emacs-lisp git helm markdown multiple-cursors
 (org :variables org-enable-roam-support t org-enable-roam-ui t)
 spell-checking syntax-checking version-control
 (neotree :variables neo-theme 'nerd neo-vc-integration
          '(face)
          neo-window-fixed-size nil)
 (scala :variables scala-auto-treeview t scala-sbt-window-position 'bottom scala-auto-insert-asterisk-in-comments t)
 (common-lisp)
 hugo
 (elfeed :variables rmh-elfeed-org-files
         (list "~/Nextcloud/ORG/blogs.org")
         elfeed-enable-web-interface nil)
 ranger
 (java :variables java-backend 'lsp)
 openai)
```
- System configuration features: CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XAW3D XDBE XIM XPM LUCID ZLIB

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (error "Eager macro-expansion failure: (wrong-number-of-ar...")
  error("Eager macro-expansion failure: %S" (wrong-number-of-arguments (4 . 4) 6))
  internal-macroexpand-for-load((tblui-define openai-image "OpenAI Image" "Display image information from OpenAI." (lambda nil openai-image-entries) [("URL" 200 nil)] nil) nil)
  load-with-code-conversion("/home/sem/.emacs.d/elpa/29.1/develop/openai-202401..." "/home/sem/.emacs.d/elpa/29.1/develop/openai-202401..." nil t)
  require(openai-image)
  load-with-code-conversion("/home/sem/.emacs.d/elpa/29.1/develop/dall-e-202401..." "/home/sem/.emacs.d/elpa/29.1/develop/dall-e-202401..." nil t)
  command-execute(dall-e-new record)
  helm-M-x-execute-command(dall-e-new)
  helm-execute-selection-action-1()
  helm-execute-selection-action()
  helm-internal((((name . "Emacs Commands history") (init #f(compiled-function () #<bytecode -0x543e6b7fb535d09>)) (candidates . helm-candidates-in-buffer) (cleanup . helm-M-x--unwi
```

**Comment by smile13241324** [comment]
I am sorry but it seems I am not able to reproduce your issue, I have loaded the openai layer and I am not seeing any error at startup, I can also call `dall-e-new` without causing an error, except that I am not having an api key.

I have also looked for `tblui` and noticed that this is non of the packages owned by one of the layers in Spacemacs, instead its a sub package called from the `openai` package, which is required by `dall-e`.

Therefore I don't think that this is our bug, instead its an issue in the interaction between the `openai`, `dall-e` and `tblui` packages and must be resolved there.
