### ISSUE TITLE
[JS/TS] LSP :: Error from the Language Server: Request initialize failed with message: Could not find a valid TypeScript installation. Please ensure that the "typescript" dependency is installed in the workspace...

### ISSUE THREAD

**Issue by stradicat** [syl20bnr/spacemacs#16286]
#### Description :octocat:
Whenever I load a javascript project, I see this message _and_ `lsp` fails to autocomplete or syntax-check:
>`LSP :: Error from the Language Server: Request initialize failed with message: Could not find a valid TypeScript installation. Please ensure that the "typescript" dependency is installed in the workspace or that a valid 'tsserver.path' is specified. Exiting. (Internal Error)`

As `lsp` backend for the `javascript` layer, I'm using `ts-ls` as recommended.

Node is installed via _NVM_, and its path is already both in `~/.zshrc` and `~/.spacemacs.env`; `node` is available:

```sh
> which node
/Users/my_user/.nvm/versions/node/v18.19.1/bin/node
```

NVM's `bin` location was already picked up in `spacemacs.env`:
```sh
NVM_BIN=/Users/my_user/.nvm/versions/node/v18.19.1/bin
NVM_CD_FLAGS=-q
NVM_DIR=/Users/my_user/.nvm
NVM_INC=/Users/my_user/.nvm/versions/node/v18.19.1/include/node
```

Inside Emacs, the `typescript` package is installed by `lsp-install-server` along `typescript-language-server` when choosing `ts-ls` as backend (expected, correct behaviour), and both are stored by default under `~/.emacs.d/.cache/lsp/npm/`.

For comparison, installing `javascript-language-server` brings some basic autocompletion and syntax-checking, although it's deprecated already.

I've removed every `lsp` language server under `~/.emacs.d/.cache/lsp` to freshly install `ts-ls`.

For reference, here are my user session's globally installed node modules, in case any of them could interfere:
```sh
├── @angular/cli@17.2.0
├── @angular/language-server@17.2.2
├── @apollo/server@4.10.0
├── @bazel/bazelisk@1.19.0
├── @vue/cli@5.0.8
├── ajv@8.12.0
├── avd-launcher@0.3.0
├── browserify@17.0.0
├── core-js@3.36.0
├── corepack@0.22.0
├── express-generator@4.16.1
├── flow-bin@0.229.0
├── git-standup@2.3.2
├── grunt-cli@1.4.3
├── gulp-cli@2.3.0
├── html-minifier@4.0.0
├── import-js@5.1.0
├── js-beautify@1.15.0
├── jsdoc@4.0.2
├── marked@12.0.0
├── minify@11.0.1
├── node-gyp@10.0.1
├── nodemon@3.0.3
├── npm@10.4.0
├── pm2@5.3.1
├── prettier-eslint-cli@8.0.1
├── prettier-eslint@16.3.0
├── prettier@3.2.5
├── pug-cli@1.0.0-alpha6
├── sqlite3@5.1.7
├── strong-ursa@0.11.0
├── typescript@5.3.3
├── uglify-js@3.17.4
├── uuid@9.0.1
├── volar@0.0.2
└── vue@3.4.19
```

#### Reproduction guide :beetle:
- Start Emacs
- Open a `.js` file from a project
- Try to call a method on a variable, see if auto-complete pops up; press `TAB` to bring up completion pop-up.

*Observed behaviour:* :eyes: :broken_heart:
No completion or syntax-checking

*Expected behaviour:* :heart: :smile:
Auto-completion and syntax-checking

#### System Info :computer:
- OS: darwin
- Emacs: 29.2
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 2dadee571)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((c-c++ :variables c-c++-adopt-subprojects t c-c++-backend 'lsp-clangd c-c++-dap-adapters
        '(dap-lldb dap-gdb-lldb dap-cpptools)
        c-c++-enable-clang-format-on-save t c-c++-lsp-enable-semantic-highlight 'rainbow)
 csv
 (dart :variables dart-backend 'lsp lsp-dart-sdk-dir "/Users/my_user/flutter/bin/cache/dart-sdk" lsp-enable-on-type-formatting t)
 emacs-lisp
 (go :variables go-backend 'lsp go-dap-mode 'dap-go go-format-before-save t go-tab-width 4 go-use-golangci-lint t go-use-test-args "-race -timeout 15s" godoc-at-point-function 'godoc-gogetdoc gofmt-command "gofumpt")
 (html :variables web-fmt-tool 'prettier)
 (java :variables java-backend 'lsp)
 (javascript :variables javascript-backend 'lsp javascript-fmt-on-save t javascript-fmt-tool 'prettier javascript-import-tool 'import-js javascript-lsp-linter nil js2-mode-show-parse-errors nil js2-mode-show-strict-warnings nil js-indent-level 4 js2-basic-offset 4 js2-include-node-externs t)
 (json :variables json-fmt-on-save t json-fmt-tool 'prettier)
 (kotlin :variables kotlin-backend 'lsp)
 major-modes
 (php :variables php-backend 'ac-php-core)
 protobuf
 (python :variables python-backend 'lsp python-lsp-server 'pyright python-test-runner
         '(pytest nose))
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rbenv)
 (rust :variables lsp-rust-server 'rust-analyzer rust-backend 'lsp rustic-format-on-save t)
 swift
 (typescript :variables typescript-backend 'lsp typescript-fmt-on-save t typescript-fmt-tool 'prettier typescript-lsp-linter nil)
 (zig :variables zls-backend 'lsp)
 (node :variables node-add-modules-path t)
 react
 (svelte :variables svelte-backend 'lsp)
 (vue :variables vue-backend 'lsp)
 ansible apache graphql markdown nginx
 (shell-scripts :variables shell-scripts-backend 'lsp shell-scripts-format-on-save t)
 (yaml :variables yaml-enable-lsp t)
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 better-defaults chrome
 (geolocation :variables geolocation-enable-automatic-theme-changer t geolocation-enable-location-service t)
 (helm :variables spacemacs-helm-rg-max-column-number 1024)
 helpful
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 imenu-list
 (lsp :variables lsp-lens-enable t lsp-ui-remap-xref-keybindings t lsp-ui-sideline-show-symbol t)
 multiple-cursors nav-flash
 (org :variables org-enable-appear-support t org-enable-asciidoc-support t org-enable-bootstrap-support t org-enable-github-support t org-enable-hugo-support t org-enable-jira-support t org-enable-org-journal-support t org-enable-valign t org-journal-dir "/Users/my_user/Documents/org-journal" org-todo-dependencies-strategy 'naive-auto)
 (osx :variables osx-command-as 'super osx-control-as 'control osx-function-as 'none osx-option-as 'meta osx-right-command-as 'control osx-right-control-as 'control osx-right-option-as 'none osx-swap-option-and-command nil)
 pdf
 (shell :variables close-window-with-terminal t multi-term-program "/usr/local/bin/zsh" shell-default-height 30 shell-default-position 'bottom shell-default-shell 'vterm shell-default-term-shell "/usr/local/bin/zsh" spacemacs-vterm-history-file-location "~/.zsh_history")
 (spell-checking :variables enable-flyspell-auto-completion t spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
 (treemacs :variables treemacs-use-all-the-icons-theme t treemacs-use-collapse-dirs 3 treemacs-use-git-mode 'deferred treemacs-use-scope-type 'Perspectives)
 (tree-sitter :variables spacemacs-tree-sitter-hl-black-list
              '(js2-mode rjsx-mode))
 (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
 (cmake :variables cmake-backend 'lsp cmake-enable-cmake-ide-support t)
 colors dap debug
 (docker :variables docker-dockerfile-backend 'lsp)
 (git :variables git-enable-magit-delta-plugin t git-enable-magit-gitflow-plugin t git-enable-magit-svn-plugin t git-enable-magit-todos-plugin t)
 gtags import-js openai pandoc prettier quickurl
 (syntax-checking :variables syntax-checking-auto-hide-tooltips 3)
 templates
 (version-control :variables version-control-diff-tool 'diff-hl)
 (xclipboard :variables xclipboard-enable-cliphist t))
```
- System configuration features: ACL GIF GLIB GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM XWIDGETS ZLIB

**Comment by alexey0308** [comment]
It looks like an upstream issue? https://github.com/emacs-lsp/lsp-mode/issues/4254

**Comment by stradicat** [comment]
As a workaround, I fiddled with my `PATH` variables in `.zshrc`, and reimported them into `.spacemacs.env`, so `lsp` detects `nvm` and makes `ts-ls` work.

Since it's an upstream issue, I'm closing this.
Thanks for the heads-up! I'll follow your referenced issue.

_Edit:_ I'll reopen it to add more feedback, in case macOS behaves a bit differently from Linux.

**Comment by alexey0308** [comment]
Hi @stradicat,

1) Do you get a message in the lsp-log buffer with something like 
```
Typescript specified through user setting ignored due to invalid path ..completely_wrong_path..
```
?

If you get this information, I would suggest to close this issue and report your PATH problem to the linked issue, since you also consider it to be not a spacemacs but upstream one.

2) For the nvm installation it looks like you have to update the .spacemacs.env anyway, unless you find a package which would manage the node PATH for you, so basically you did solve your problem. But I suspect that the LSP is probably using the globally installed `typescript` and not the one from `.emacs.d/.cache/...`.

**Comment by stradicat** [comment]
Hey @alexey0308,

I am indeed getting the error on 1. :
> `[lspserver] Typescript specified through user setting ignored due to invalid path "/Users/my_user/Projects/Project_Dir/lib/tsserver.js"`

In the end, changing the order of the `PATH` exports in `.zshrc` to be picked up by Emacs in `.spacemacs.env` kind of made `lsp` pick up `typescript` (probably the global install).

I've also had problems with `vue-semantic-server` and `rust-analyzer`, which were apparently resolved with the `PATH` reorder.

I guess I'm closing the issue. Thanks again for looking into it.

**Comment by differentMonster** [comment]
@stradicat 

I am facing the same problem could you share what you .zshrc and .spacemacs.env change in here, it will help making it clear about what you change, thanks ya.
