### ISSUE TITLE
Feature Request: Add option for recentf buffers for compleseus layer

### ISSUE THREAD

**Issue by fleimgruber** [syl20bnr/spacemacs#16301]
Using the [compleseus layer](https://develop.spacemacs.org/layers/+completion/compleseus/README.html) a `SPC b b (compleseus-switch-to-buffer)` contains "Buffer", "File", "Bookmark", "Project Buffer", and "Project File" sections, but is missing a "Recent File" section. What would be the recommended way to add this section and make it configurable in the layer?

**Comment by fnussbaum** [comment]
The "File" section by default exclusively shows recent files as collected by the built-in `recentf-mode` (which provides some customization options).

**Comment by fleimgruber** [comment]
Sorry for the noise. FWIW, I realize that I tested this during a vicious cycle of recompiling Emacs where it apparently crashed before saving the recentf information. Clean exits or recentf writing at other times lead to the expected completions being present.
