### ISSUE TITLE
Php Mode keep show this error.

### ISSUE THREAD

**Issue by differentMonster** [syl20bnr/spacemacs#16330]
Hello i am facing a error keep pop up and i have no idea why, may someone help me look into it ?
```
ac-php: Unable to resolve project root
Company: An error occurred in auto-begin
Company: backend (company-ac-php-backend company-phpactor :with company-yasnippet) error "Wrong type argument: stringp, nil" with args (candidates daadaada)
ac-php: Unable to resolve project root
eldoc error: (wrong-type-argument stringp nil)

```

**Comment by smile13241324** [comment]
Hi :),

I am sorry but I would need a bit more information before I can even try to help you. Basically the php layer should be working as is, given that you are using a proper LSP server. However I am not using PHP at all so I will need some guidance to reproduce you error.

For the beginning please run `spacemacs/report-issue` and post your system specs, then provide a step by step instruction how to reproduce your error best based on a publicly available php project.

Please ping me when you have posted the necessary info and I will gladly have a look at your issue.

Thanks.
Maxi

**Comment by smile13241324** [comment]
No reaction therefore closed
