### ISSUE TITLE
c-c++ layer requires semantic layer

### ISSUE THREAD

**Issue by herbertjones** [syl20bnr/spacemacs#1634]
Unless semantic is enabled in ```dotspacemacs-configuration-layers```, extra c-c++ packages do not appear to be added nor are they initialized correctly when other layers have enabled the packages.  There is no error or warning accompanied by this behavior.  Unless the semantic layer is enabled, c++ files will have missing functionality such as:

- yasnippet minor mode is not initialized
- srefactor keybindings are missing and the package is not installed

ycmd, however, still works if that layer is enabled.

Observed in ```develop 5b72221```.

**Comment by tuhdo** [comment]
About semantic, it's intended since some people like it, some don't. Also, it's not specific to C++ so we separate it in its own layer.

**Comment by syl20bnr** [comment]
@herbertjones If I understand well, only yasnippet has a wrong behavior right ?

**Comment by herbertjones** [comment]
Sounds like it.  Perhaps it would be nicer for some kind of warning for users updating so that they know that they only need to add the semantic layer.  Anyone finding the problem documented here in this github issue might be enough if the documentation for the layer is updated.

**Comment by StreakyCobra** [comment]
The `c-c++` layer now contains notes about the `semantic` layer, and also about `srefactor` only available on `emacs >= 24.4`. `yasnippet` is working fine here even without the `semantic` layer. 

All points being solved, I close this issue. Feel free to open a new issue in case of trouble :relaxed:
