### ISSUE TITLE
`git grep` is preferred over `rg` but is massively deficient

### ISSUE THREAD

**Issue by zenspider** [syl20bnr/spacemacs#16370]
Without any config, if any project I use that is backed by git, then dumb-jump prefers to use `git grep` to find definitions via `dumb-jump-pick-grep-variant`. The problem, in C or ruby or anything else I've tried, is that it doesn't find ANYTHING... 0% hit rate. If I set `'(dumb-jump-force-searcher 'rg)` then everything works well. I don't know if `git grep` regexps are deficient or broken because I find dumb-jump hard to navigate but the problem certainly lies with the searcher. For some reason I can't figure out, it chooses `git-grep` over `dumb-jump-prefer-searcher`, so I'm not sure what the `prefer` vs `force` distinction is for.

I would also suggest that rg be preferred over ag.

**Comment by bcc32** [comment]
Spacemacs does pretty minimal configuration for dumb-jump (it just adds integrations for ivy, helm, and xref).  I'd suggest filing an issue on that package's [repo](https://github.com/jacktasia/dumb-jump) instead.

**Comment by zenspider** [comment]
OMG what was I smoking when I filed this??? Sorry! So many tabs open.
