### ISSUE TITLE
Windows 7 Install: Does Not Appear To Even Attempt Automatic Package Install

### ISSUE THREAD

**Issue by mentalisttraceur** [syl20bnr/spacemacs#1637]
I have emacs 24.5.1 installed, the official GNU build for windows.

I also have busybox-w32 and Git Bash (msysgit) installed, providing all of the basic Unix commandline tools. (My console is ConEmu, but I imagine that shouldn't change anything.) I typically run busybox ash in ConEmu as my default shell - this sets up the variables that you would expect, such as HOME and SHELL, etc. Since msysgit provides a few utilities that busybox doesn't (ssh, curl, git, vim, gpg), I have wrapper shell scripts in my path which point to those, so that I have access to them when I'm inside the busybox shell.

Anyway, I do the recursive git clone, it all seems to work fine. Then I run emacs - and nothing seems to happen. Emacs loads as normal, as if nothing changed. I've tried both launching the GUI through `emacs` and the CLI version through `emacs -nw`. No modeline turning red, nothing.

I have tried running with --debug-init, and nothing at all gets printed.

I have tried running emacs from inside the msysgit bash shell, instead of busybox-w32's ash. No difference.

I thought maybe it's my ~/.emacs file, so I moved it out of my home folder - not change. My HOME envar is typically set to `C:/wintools` - could that be an issue? I tried invoking it as `HOME=$USERPROFILE emacs`, after having moved .emacs.d to that folder. Also no joy.

I've tried this all both with and without the template .spacemacs copied to ~/.spacemacs.

I am not particularly experienced with emacs, so any pointers on debugging would be great, and all questions for me to provide ore information that might be useful are welcome.

**Comment by TheBB** [comment]
@Andrea provided some help for Windows users earlier today that seems like it would benefit you. Try going through the steps described #1632 (unfortunately not merged yet), about getting the user home dir right. [Direct link](https://github.com/Andrea/spacemacs/blob/patch-1/README.md#windows)

**Comment by mentalisttraceur** [comment]
@TheBB Thanks for the suggestion, but near as I can tell, my HOME environment variable is definitely set. As described, my setup ensures that those variables are set in the environment. E.g. `echo %HOME%` works fine from cmd (and `echo $HOME` works fine from within busybox-w32's ash or mysgit's bash). I tested this many times with HOME being set to `C:/wintools` and a handful of times with HOME being set  to `C:/users/myusername` (in each case I made sure I had the .emacs.d directory in whichever directory HOME was set to at the time).

**Comment by mentalisttraceur** [comment]
Follow up: I've now also tested with HOME set to the same value as APPDATA, since it seemed from a few comments that that's where emacs might try to go by default....

Also I verified/ensured that the .emacs.d folder, and that every folder I set "HOME" to, was owned by my user (as opposed to the "Administrators" group). No luck with that either.

**Comment by syl20bnr** [comment]
Your issue is definetly an issue of `HOME` variable. Either you did not set it correctly (try to hardcode it instead of using the environment variable) or Emacs does not see it for some reason.

I don't see any other possible explaination to your issue.

**Comment by mentalisttraceur** [comment]
@syl20bnr Funny story: Running it with HOME _not set at all_ and .emacs.d in the APPDATA folder caused it to start working - at least until it ran into the fact that doing that leaves git out of my PATH. (I popped open a raw `cmd`, as opposed to though the conemu -> busybox ash entrypoint I'd normally use which sets and exports HOME, and ran emacs).

What's noteworthy is that `M-x getenv HOME` prints `C:\Users\<my username>\AppData\Roaming`, but invoking emacs with HOME set to that exact string from my busybox does not work, even though `M-x getenv HOME` reports exactly the same string...

If neither of these are sufficient to set HOME, then something is buggy, because all three of these ought to produce identical results to having the HOME variable set through the Windows envar editing/setting menu.
```
$ FOO=bar
$ export FOO
$ qux #qux executes with envar FOO with value "bar"
```
```
$ export FOO=bar #on shells that allow this syntax, which is most modern Bourne-family shells
$ qux #qux executes with envar FOO with value "bar"
```
```
$ FOO=bar qux #qux executes with envar FOO with value "bar"
```

Do the emacs builds for Windows treat something else as authoritative sources of what the HOME envar should be set to? Is there any variable besides HOME which plays a deterministic role?

busybox-w32 changes all the envars to have *nix-like pathnames - converting paths to forward slashes instead of backslashes. Besides HOME (which I made sure had backslashes in many of the tests), are there any other variables where this could matter?

**Comment by mentalisttraceur** [comment]
Noteworthy: Editing the HOME environment variable through the "proper" Control Panel way to set it as what I ultimately wanted my HOME envar to be, "C:\wintools", also did not work.

**Comment by syl20bnr** [comment]
When you set it up to "C:\wintools". Does this folder contains the
".emacs.d" directory ?

Inside Emacs what is the output of `M-! echo %HOME%` ?

Le mardi 19 mai 2015, mentalisttraceur <notifications@github.com> a écrit :

> Noteworthy: Editing the HOME environment variable through the "proper"
> Control Panel way to set it as what I ultimately wanted my HOME envar to
> be, "C:\wintools", also did not work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/1637#issuecomment-103625064>
> .
>


-- 
-syl20bnr-

**Comment by mentalisttraceur** [comment]
Yes, C:\wintools contains a copy of .emacs.d:
```
C:/wintools $ echo $HOME
C:/wintools
C:/wintools $ ls "$HOME"/.emacs.d
CHANGELOG.org   auto-save-list  doc             spacemacs
README.md       contrib         init.el         travis
assets          core            private
C:/wintools $
```
When I go through my busybox ash setup, `M-! foo` does not work, saying it can't find "/bin/sh"
When I go through gitbash, emacs is executing bash instead of cmd, and `M-! echo $HOME` prints `/c/wintools` (which is correct, given how gitbash/msys mangles Windows paths)
When I go through a cmd launched independent of any of those, set HOME=C:\wintools from inside it, then run emacs, `M-! %HOME%` prints `C:\wintools` (exactly what I'd expect).

**Comment by mentalisttraceur** [comment]
Here's an interesting detail:

When I launch it with HOME set to C:\wintools, load-path only has contents from C:/Program Files (x86).

When I launch it from the independently launched cmd, the load-path ALSO includes all of the APPDATA .emacs.d files, and then some. So somehow, it's "deciding" to have all of the relevant folders, including all of the spacemacs stuff, in the load-path, when I leave HOME alone, but failing to include it when I set HOME explicitly.

Thoughts?

**Comment by mentalisttraceur** [comment]
Well, the emacs newb (myself) has figured out their problem: I had a `C:/wintools/.emacs` file. If emacs finds `~/.emacs` it does _not_ load `~/.emacs.d/init.el`.
