### ISSUE TITLE
Slow opening of tex files

### ISSUE THREAD

**Issue by tigerjack** [syl20bnr/spacemacs#16372]
#### Description :octocat:
Opening any tex files takes seconds.

#### Reproduction guide :beetle:
To debug the issue
- Start Emacs
- `toggle-debug-on-quit`
- Open/Create a `.tex` file
- After a few seconds, press `C-g`
- Observe the debug output

*Observed behaviour:* :eyes: :broken_heart:
Opening any tex files takes seconds.

*Expected behaviour:* :heart: :smile:
Opening any tex files takes way less.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.3
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. a58a7d79b)
- Graphic display: nil
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv tigerjack javascript html ruby git
     (version-control :variables version-control-diff-side 'left version-control-diff-tool 'diff-hl)
     dap lsp rust emacs-lisp common-lisp
     (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-lsp-enable-semantic-highlight 'rainbow c++-enable-organize-includes-on-save t c-c++-adopt-subprojects t c-c++-enable-clang-support t c-c++-enable-clang-format-on-save t c-c++-enable-rtags-support t c-c++-default-mode-for-headers 'c++-mode)
     (python :variables python-backend 'lsp python-lsp-server 'pyright python-formatter 'black python-pipenv-activate t python-fill-column 79)
     ipython-notebook yaml themes-megapack asciidoc
     (helm :variables helm-enable-auto-resize t)
     (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
     (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence-delay 0 auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory nil)
     (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
     (languagetool :variables languagetool-show-error-on-jump t langtool-default-language "en-GB" langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*")
     better-defaults markdown ranger themes-megapack
     (org :variables org-projectile-file "TODOs.org" org-enable-roam-support t org-roam-directory "/mnt/internal/SharedData/Documents/org-roam" org-roam-v2-ack t org-roam-v2-ack t org-enable-roam-ui t org-enable-org-brain-support t)
     gtags
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/bash" multi-term-program "/bin/bash")
     (latex :variables latex-backend 'company-auctex latex-enable-auto-fill t latex-enable-folding t)
     (bibtex)
     deft
     (spell-checking :variables spell-checking-enable-by-default nil))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (quit)
  require(evil-embrace nil t)
  evil-tex-mode()
  run-hooks(change-major-mode-after-body-hook text-mode-hook TeX-mode-hook LaTeX-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook TeX-mode-hook LaTeX-mode-hook))
  run-mode-hooks(LaTeX-mode-hook)
  LaTeX-mode()
  set-auto-mode-0(latex-mode t)
  #f(compiled-function (var val) "Set local variable VAR with value VAL.\nIf VAR is `mode', call `VAL-mode' as a function unless it's\nalready the major mode." #<bytecode -0xc0cd9b4aaa588c1>)(mode LaTeX)
  apply(#f(compiled-function (var val) "Set local variable VAR with value VAL.\nIf VAR is `mode', call `VAL-mode' as a function unless it's\nalready the major mode." #<bytecode -0xc0cd9b4aaa588c1>) (mode LaTeX))
  hack-one-local-variable(mode LaTeX)
  hack-local-variables-apply()
  hack-local-variables(no-mode)
  run-mode-hooks(LaTeX-mode-hook)
  LaTeX-mode()
  set-auto-mode-0(latex-mode t)
  #f(compiled-function (var val) "Set local variable VAR with value VAL.\nIf VAR is `mode', call `VAL-mode' as a function unless it's\nalready the major mode." #<bytecode -0xc0cd9b4aaa588c1>)(mode LaTeX)
  apply(#f(compiled-function (var val) "Set local variable VAR with value VAL.\nIf VAR is `mode', call `VAL-mode' as a function unless it's\nalready the major mode." #<bytecode -0xc0cd9b4aaa588c1>) (mode LaTeX))
  hack-one-local-variable(mode LaTeX)
  hack-local-variables-apply()
  hack-local-variables(no-mode)
```

**Comment by arifer612** [comment]
It might be helpful to run a profiler to check what's going on under the hood. My LaTeX files are humongous an even despite using LSP as the backend, it takes about a second (two tops) to load them all up.

**Comment by tigerjack** [comment]
@arifer612 

Here is the CPU profiling, which shows a 70% of CPU time spent on `evil-tex-mode`
[cpu_profile.txt](https://github.com/syl20bnr/spacemacs/files/14976708/cpu_profile.txt)

**Comment by arifer612** [comment]
Yep, 70% just for `evil-tex-mode` is quite significant. Unfortunately, I am not
able to reproduce this issue with my setup, nor on a fresh setup with the most
basic configurations. It might just be an unexpected issue or perhaps something
amongst your currently installed packages are interfering with it. I would
suggest upgrading all your packages first to see if there's improvement, and if
there isn't then to delete the contents of `~/emacs.d/elpa/29.3` to force Emacs
to re-download all the packages again.

**Comment by tigerjack** [comment]
@arifer612 thanks for your help.
After further investigation, I discovered that the issue was due to the following (now commented) line in `.dir-locals.el`

```elisp
((latex-mode
  ;; (mode . latex )
))```

I don't why it got there first of all, or if it was used before the recent auctex upgrade.

**Comment by tigerjack** [comment]
@arifer612 thanks for your help.
After further investigation, I discovered that the issue was due to the following (now commented) line in `.dir-locals.el`, probably firing a recursive activation of function calls.

```elisp
((latex-mode
  ;; (mode . latex )
))
```

I don't why it got there first of all, or if it was used before the recent auctex upgrade.

**Comment by arifer612** [comment]
You're welcome! On another note, that's quite a nasty recursive hell you ended up in :rofl:, good thing you caught that. Hope your TeX experience on Emacs/Spacemacs goes smooth from now on!

**Comment by tigerjack** [comment]
> You're welcome! On another note, that's quite a nasty recursive hell you ended up in 🤣, good thing you caught that. Hope your TeX experience on Emacs/Spacemacs goes smooth from now on!

It's incredible how fast a file is opening now XD for the last month or so, I got used to incredible amount of delays!
