### ISSUE TITLE
Many shortcuts broken (byte-code: Key sequence M-m h d m starts with non-prefix key M-m)

### ISSUE THREAD

**Issue by wthe2004** [syl20bnr/spacemacs#16400]
#### Description :octocat:
I've been using Emacs on Endeavour OS smoothly for weeks without any changes to my configuration file. Suddenly, I encountered an issue where several shortcuts, such as `SPC b b` or `SPC f s`, stopped functioning properly. The warning message displayed is: `byte-code: Key sequence M-m h d m starts with non-prefix key M-m.` I attempted to resolve the problem by reinstalling Emacs and Spacemacs, which initially seemed to work fine. However, after one or two hours, the same issue resurfaced.

![240514_16h32m08s_screenshot](https://github.com/syl20bnr/spacemacs/assets/45729885/b0a13c17-2b89-48ac-ae45-591aec26df9c)

#### Reproduction guide :beetle:

I do not know. I use the same config on Ubuntu 20.04 with emacs 29.3 and the same problem did not exist.
 
*Observed behaviour:* :eyes: :broken_heart:
`SPC b b` or `SPC f s` or some other shortcuts outputs `byte-code: Key sequence M-m h d m starts with non-prefix key M-m.`. Some shortcuts liike `SPC b h` works fine.

*Expected behaviour:* :heart: :smile:
The short cuts works normally.

#### System Info
- OS: Endeavour OS
- emacs-version: emacs-wayland 29.3 (I have already tried to switch to emacs-git 29.3 and the same problem occurs)
- My config: https://github.com/goodmorning-hwt/.spacemacs.d 

#### Backtrace :paw_prints:
```
%BACKTRACE%
```

**Comment by nicorikken** [comment]
I had the same issue today but after updating packages it is back to working again. I know my comment isn't helpful in debugging, but maybe updating packages (again) will help?

**Comment by bcc32** [comment]
This was fixed in #16397.

**Comment by wthe2004** [comment]
I updated `.emacs.d` and it fixed.  Thanks!

**Comment by fperies** [comment]
Hello,

It looks like the issue has just came back.
Could you confirm?
Thanks!
