### ISSUE TITLE
Error (use-package) : org-projectile/:init:  -- no such file or directory : org-projecticle

### ISSUE THREAD

**Issue by Kan-Rup** [syl20bnr/spacemacs#16428]
I activated org in the configuration and get this error now when I restart Emacs.

Error (use-package) : org-projectile/:init: cannot open loadfile:  no such file or directory : org-projectile

"an error occured while installing org-projectile (error: (error package 'emacs-28' is unavailable))

Any help with this? thanks.

**Comment by fnussbaum** [comment]
As of b7fa0e29e7ad73b12930986109965aeff326adfc, Spacemacs requires Emacs >= 28.2.

**Comment by smile13241324** [comment]
Not sure whats happening on your system, there is no `org-projecticle` mentioned anywhere in our code. 
The error message `an error occured while installing org-projectile (error: (error package 'emacs-28' is unavailable))` is very strange, do you have some custom config in your dotfile causing this?

I assume you are running debian 12 with emacs 28.2. Please retry with a clean config and share your system details.

**Comment by Kan-Rup** [comment]
sorry typo, its "org-projectile", not org-projecticle... does that help?
I have emacs 27.1

**Comment by Kan-Rup** [comment]
rawr fear me! I installed emacs from source!

anyway there doesn't appear to be the warnings now...so,
thanks.
