### ISSUE TITLE
Is it possible to write a config file in project

### ISSUE THREAD

**Issue by lufeihaidao** [syl20bnr/spacemacs#1643]
Like `.sublime-project` in sublime, perhaps we can put a `.emacs-project` file in project. In this file, programmer can put settings here. For example, I can put `rsync` settings here(from path, to path, etc)

**Comment by syl20bnr** [comment]
In Emacs there is a mechanism to declare file or directory local variables.
More info here:
- file local variables: http://www.gnu.org/software/emacs/manual/html_node/elisp/File-Local-Variables.html
- directory local variables: http://www.gnu.org/software/emacs/manual/html_node/elisp/Directory-Local-Variables.html#Directory-Local-Variables

**Comment by lufeihaidao** [comment]
@syl20bnr Thank you. I was noticed that local variables may cause same security warnings. Anyway, it's the best solution now.

**Comment by CestDiego** [comment]
@lufeihaidao when you enter any file you are warned that the contents of the .dir-locals.el is gonna be executed, but if you trust it and you've made it, then pressing `!` will make it remember that it's safe to execute

**Comment by lufeihaidao** [comment]
@CestDiego Ah, that's good. Thank you :)
