### ISSUE TITLE
Cannot create new file if similar name exists

### ISSUE THREAD

**Issue by tigerjack** [syl20bnr/spacemacs#16443]
#### Description :octocat:
I think this bug is related to the following two issues, that were solved at some point.
https://github.com/syl20bnr/spacemacs/issues/13551 and https://github.com/syl20bnr/spacemacs/issues/8571

Basically, when I try to  create a new file in Spacemacs `SPC f f` or rename an existing
one `SPC f R`, if a file with a similar name exists, I cannot select the new name.

For instance, if I want to rename `_cmds.tex` to `cmds.tex`, I cannot select
`cmds.tex` using the down arrow as before.

#### Reproduction guide :beetle:
- Start Emacs
- Create a file `_cmds.tex` and save it
- Rename (`SPC f R`) the file `cmds.tex` to `cmds.tex`.

*Observed behaviour:* :eyes: :broken_heart:
I cannot select the new name from the minibuffer with down arrow. The mouse left-click works.
![image](https://github.com/syl20bnr/spacemacs/assets/8199216/5f0d7d48-86fb-4e9c-bd7f-17043f28e0be)

*Expected behaviour:* :heart: :smile:
I can select the new name from the minibuffer using the down arrow.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.3
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. fadba3059)
- Graphic display: nil
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript better-defaults ranger yaml csv
            (org :variables org-projectile-file "TODOs.org" org-enable-roam-support t org-roam-directory "/mnt/internal/SharedData/Documents/org-roam/")
            (helm :variables helm-enable-auto-resize t)
            (multiple-cursors :variables multiple-cursors-backend 'evil-mc)
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence-delay 0 auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory nil)
            (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
            (spell-checking :variables spell-checking-enable-by-default nil)
            (languagetool :variables languagetool-show-error-on-jump t langtool-default-language "en-GB" langtool-java-classpath "/usr/share/languagetool:/usr/share/java/languagetool/*")
            lsp gtags git
            (version-control :variables version-control-diff-side 'left version-control-diff-tool 'diff-hl)
            (c-c++ :variables c-c++-backend 'lsp-ccls c-c++-lsp-enable-semantic-highlight 'rainbow c++-enable-organize-includes-on-save t c-c++-adopt-subprojects t c-c++-enable-clang-support t c-c++-enable-clang-format-on-save t c-c++-enable-rtags-support t c-c++-default-mode-for-headers 'c++-mode)
            emacs-lisp
            (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/bash" multi-term-program "/bin/bash")
            (python :variables python-formatter 'black python-enable-yapf-format-on-save t python-backend 'lsp python-lsp-server 'pyright python-formatter 'yapf python-pipenv-activate t python-fill-column 79)
            deft
            (latex :variables latex-backend "company-auctex" latex-enable-auto-fill t latex-enable-folding t)
            (bibtex)
            ipython-notebook tigerjack)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

**Comment by emacs18** [comment]
Did you try Control-o  while selecting with helm?
This is how I select the new name being typed rather than any other name.

**Comment by tigerjack** [comment]
@emacs18 thanks, it seems to work indeed. Still, before, it was working by just using the down arrow. Is this the expected behavior?

**Comment by emacs18** [comment]
For me Control-o or UP arrow work.  DOWN arrow moves the cursor even further away from the top item which you are typing.
I've been using helm for many years.  I don't think anything changed recently.

**Comment by fnussbaum** [comment]
In https://github.com/emacs-helm/helm/commit/a4380caef3a9e4b1e8d11458852ab67ba9b4cf58, the default value of `helm-move-to-line-cycle-in-source` was changed to `t`. Spacemacs does not customize this variable.

**Comment by tigerjack** [comment]
> For me Control-o or UP arrow work.

Thank you for pointing out an alternative. 


> In [emacs-helm/helm@a4380ca](https://github.com/emacs-helm/helm/commit/a4380caef3a9e4b1e8d11458852ab67ba9b4cf58), the default value of `helm-move-to-line-cycle-in-source` was changed to `t`. Spacemacs does not customize this variable.

And that should be the culprit I guess. I will try to change this variable and test it soon. Many thanks!

**Comment by emacs18** [comment]
The value of the variable does not matter much in that the new item being typed can be reached.
Whether it is t or nil, Control-o works.
Up/down arrows work slightly differently depending on the value of the variable.
If the variable is nil, then down arrow needs to be used to reach the item being typed.
If the variable is t, then up arrow needs to be used to reach the item being typed.
Thus the new item being typed can be reached either via Control-o or via up/down arrows.

**Comment by smile13241324** [comment]
If this variable is not true control-j and control-k does not longer work as expected breaking the evil workflow. I have noticed that too but did not come around to investigate.

I'll let the helm layer customise this var.
