### ISSUE TITLE
 (error "Key sequence m - m starts with non-prefix key m")

### ISSUE THREAD

**Issue by tstohne** [syl20bnr/spacemacs#16458]
When I start emacs I get the  (error "Key sequence m - m starts with non-prefix key m"):

debug-init shows the following:

Debugger entered--Lisp error: (error "Key sequence m - m starts with non-prefix key m")
  define-key((keymap #^[nil nil keymap 
#^^[3 0 set-mark-command move-beginning-of-line backward-char mode-specific-command-prefix delete-char move-end-of-line forward-char keyboard-quit help-command indent-for-tab-command electric-newline-and-maybe-indent kill-line recenter-top-bottom ...] #^^[1 0 #^^[2 0 
#^^[3 0 set-mark-command move-beginning-of-line backward-char mode-specific-command-prefix delete-char move-end-of-line forward-char keyboard-quit help-command indent-for-tab-command electric-newline-and-maybe-indent kill-line recenter-top-bottom ...] self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command ...] self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command ...] self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command self-insert-command ...] ... ... ... ... ... ... ... ... ... ... ... ... ...) "m-m" spacemacs-cmds)
  global-set-key("m-m" spacemacs-cmds)
  (let ((key (car tail))) (when t (define-key spacemacs-default-map-root-map key 'spacemacs-cmds)) (global-set-key key 'spacemacs-cmds) (setq tail (cdr tail)))
  (while tail (let ((key (car tail))) (when t (define-key spacemacs-default-map-root-map key 'spacemacs-cmds)) (global-set-key key 'spacemacs-cmds) (setq tail (cdr tail))))
  (let ((tail (bind-map-kbd-keys (list dotspacemacs-emacs-leader-key)))) (while tail (let ((key (car tail))) (when t (define-key spacemacs-default-map-root-map key 'spacemacs-cmds)) (global-set-key key 'spacemacs-cmds) (setq tail (cdr tail)))))
  (dolist (key (bind-map-kbd-keys (list dotspacemacs-emacs-leader-key))) (when t (define-key spacemacs-default-map-root-map key 'spacemacs-cmds)) (global-set-key key 'spacemacs-cmds))
  (progn (defvar spacemacs-default-map (make-sparse-keymap)) (unless (keymapp spacemacs-default-map) (error "bind-map: %s is not a keymap" 'spacemacs-default-map)) (defvar spacemacs-cmds nil) (setq spacemacs-cmds spacemacs-default-map) (setf (symbol-function 'spacemacs-cmds) spacemacs-default-map) (defvar spacemacs-default-map-root-map (make-sparse-keymap)) (bind-map-put-map-properties 'spacemacs-default-map :root-map 'spacemacs-default-map-root-map :active-var 'spacemacs-default-map-active :prefix-cmd 'spacemacs-cmds :override-minor-modes 't :override-mode-name 'spacemacs-leader-override-mode :keys '(dotspacemacs-emacs-leader-key) :evil-keys '(dotspacemacs-leader-key) :evil-states '(normal motion visual) :minor-modes 'nil :major-modes 'nil) (with-no-warnings (defun turn-on-spacemacs-leader-override-mode nil "Enable `spacemacs-leader-override-mode' except in ..." (unless (minibufferp) (spacemacs-leader-override-mode 1))) (define-globalized-minor-mode global-spacemacs-leader-override-mode spacemacs-leader-override-mode turn-on-spacemacs-leader-override-mode) (define-minor-mode spacemacs-leader-override-mode "Minor mode that makes spacemacs-default-map overri...") (global-spacemacs-leader-override-mode 1)) (add-to-list 'emulation-mode-map-alists (list (cons 'spacemacs-leader-override-mode spacemacs-default-map-root-map))) (dolist (key (bind-map-kbd-keys (list dotspacemacs-emacs-leader-key))) (when t (define-key spacemacs-default-map-root-map key 'spacemacs-cmds)) (global-set-key key 'spacemacs-cmds)) (eval-after-load 'evil '(progn (dolist (key (bind-map-kbd-keys (list dotspacemacs-leader-key))) (dolist (state '...) (when t (push ... bind-map-evil-local-bindings)) (evil-global-set-key state key 'spacemacs-cmds))) (evil-normalize-keymaps))) 'spacemacs-default-map)
  (bind-map spacemacs-default-map :prefix-cmd spacemacs-cmds :keys (dotspacemacs-emacs-leader-key) :evil-keys (dotspacemacs-leader-key) :override-minor-modes t :override-mode-name spacemacs-leader-override-mode)
  spacemacs-bootstrap/init-bind-map()
  funcall(spacemacs-bootstrap/init-bind-map)
  (let* ((pkg-name (eieio-oref pkg ':name)) (owner (car (eieio-oref pkg ':owners)))) (spacemacs-buffer/message (format "%S -> init (%S)..." pkg-name owner)) (funcall (intern (format "%S/init-%S" owner pkg-name))))
  configuration-layer//configure-package(#<cfgl-package cfgl-package-170b04262e10>)
  mapc(configuration-layer//configure-package (#<cfgl-package cfgl-package-170b04262de2> #<cfgl-package cfgl-package-170b044d61f0> #<cfgl-package cfgl-package-170b04262e10> #<cfgl-package cfgl-package-170b044d6214> #<cfgl-package cfgl-package-170b04262930> #<cfgl-package cfgl-package-170b04262954> #<cfgl-package cfgl-package-170b04262968> #<cfgl-package cfgl-package-170b0426298c>))
  (let (packages-to-configure) (let ((tail packages)) (while tail (let ((pkg-name (car tail))) (let ((pkg (configuration-layer/get-package pkg-name))) (cond ((eieio-oref pkg ...) (spacemacs-buffer/message ...)) ((and ... ...) (spacemacs-buffer/message ...)) ((null ...) (spacemacs-buffer/message ...)) ((not ...) (spacemacs-buffer/message ...)) ((not ...) (spacemacs-buffer/message ...)) (t (let ... ...) (if ... nil ...) (cond ... ...)))) (setq tail (cdr tail))))) (setq packages-to-configure (reverse packages-to-configure)) (mapc 'configuration-layer//configure-package packages-to-configure) (mapc 'configuration-layer//post-configure-package packages-to-configure))
  configuration-layer//configure-packages-2((async bind-key bind-map diminish evil hydra use-package which-key))
  configuration-layer//configure-packages((abbrev ac-ispell ace-jump-helm-line ace-link ace-window add-node-modules-path aggressive-indent all-the-icons anaconda-mode ansi-colors archive-mode async auctex auctex-latexmk auto-compile auto-complete auto-highlight-symbol auto-yasnippet avy bind-key bind-map blacken bookmark buffer-menu centered-cursor-mode clean-aindent-mode code-cells column-enforce-mode company company-anaconda company-auctex company-box company-go company-math company-posframe company-quickhelp company-reftex company-statistics company-web compile conf-mode css-mode cus-edit cython-mode dash debug default-helm-config default-ivy-config default-org-config define-word ...))
  configuration-layer//load()
  (cond (changed-since-last-dump-p (configuration-layer//load) (if (spacemacs/emacs-with-pdumper-set-p) (progn (configuration-layer/message "Layer list has changed since last dump.") (configuration-layer//dump-emacs)))) (spacemacs-force-dump (configuration-layer//load) (if (spacemacs/emacs-with-pdumper-set-p) (progn (configuration-layer/message (concat "--force-dump passed on the command line or configu..." "been reloaded, forcing a redump.")) (configuration-layer//dump-emacs)))) ((spacemacs-is-dumping-p) (configuration-layer//load)) ((and (spacemacs/emacs-with-pdumper-set-p) (spacemacs-run-from-dump-p)) (configuration-layer/message "Running from a dumped file. Skipping the loading p...")) (t (configuration-layer//load) (if (spacemacs/emacs-with-pdumper-set-p) (progn (configuration-layer/message (concat "Layer list has not changed since last time. " "Skipping dumping process!"))))))
  (let (changed-since-last-dump-p) (if (file-exists-p configuration-layer--last-dotspacemacs-configuration-layers-file) (progn (configuration-layer/load-file configuration-layer--last-dotspacemacs-configuration-layers-file))) (let ((layers dotspacemacs-configuration-layers)) (progn (if "Calling dotfile layers..." (progn (spacemacs-buffer/message "Calling dotfile layers..."))) (if (fboundp 'dotspacemacs/layers) (progn (condition-case err (dotspacemacs/layers) ((debug error) (configuration-layer//increment-error-count) (spacemacs-buffer/append ... t)))))) (setq dotspacemacs--configuration-layers-saved dotspacemacs-configuration-layers) (setq changed-since-last-dump-p (not (equal layers dotspacemacs-configuration-layers))) (spacemacs/dump-vars-to-file '(dotspacemacs-configuration-layers) configuration-layer--last-dotspacemacs-configuration-layers-file)) (cond (changed-since-last-dump-p (configuration-layer//load) (if (spacemacs/emacs-with-pdumper-set-p) (progn (configuration-layer/message "Layer list has changed since last dump.") (configuration-layer//dump-emacs)))) (spacemacs-force-dump (configuration-layer//load) (if (spacemacs/emacs-with-pdumper-set-p) (progn (configuration-layer/message (concat "--force-dump passed on the command line or configu..." "been reloaded, forcing a redump.")) (configuration-layer//dump-emacs)))) ((spacemacs-is-dumping-p) (configuration-layer//load)) ((and (spacemacs/emacs-with-pdumper-set-p) (spacemacs-run-from-dump-p)) (configuration-layer/message "Running from a dumped file. Skipping the loading p...")) (t (configuration-layer//load) (if (spacemacs/emacs-with-pdumper-set-p) (progn (configuration-layer/message (concat "Layer list has not changed since last time. " "Skipping dumping process!")))))))
  configuration-layer/load()
  (let ((please-do-not-disable-file-name-handler-alist nil)) (require 'core-spacemacs) (spacemacs/dump-restore-load-path) (configuration-layer/load-lock-file) (spacemacs/init) (configuration-layer/stable-elpa-init) (configuration-layer/load) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (spacemacs/dump-eval-delayed-functions) (if (and dotspacemacs-enable-server (not (spacemacs-is-dumping-p))) (progn (require 'server) (if dotspacemacs-server-socket-dir (progn (setq server-socket-dir dotspacemacs-server-socket-dir))) (if (server-running-p) nil (message "Starting a server...") (server-start)))))
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (error (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (let ((please-do-not-disable-file-name-handler-alist nil)) (require 'core-spacemacs) (spacemacs/dump-restore-load-path) (configuration-layer/load-lock-file) (spacemacs/init) (configuration-layer/stable-elpa-init) (configuration-layer/load) (spacemacs-buffer/display-startup-note) (spacemacs/setup-startup-hook) (spacemacs/dump-eval-delayed-functions) (if (and dotspacemacs-enable-server (not (spacemacs-is-dumping-p))) (progn (require 'server) (if dotspacemacs-server-socket-dir (progn (setq server-socket-dir dotspacemacs-server-socket-dir))) (if (server-running-p) nil (message "Starting a server...") (server-start))))))
  eval-buffer(#<buffer  *load*> nil "/home/ts/.emacs.d/init.el" nil t)  ; Reading at buffer position 3366
  load-with-code-conversion("/home/ts/.emacs.d/init.el" "/home/ts/.emacs.d/init.el" t t)
  load("/home/ts/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x118dc22f5c8df52f>) #f(compiled-function () #<bytecode -0x1f3c61addc0b8a75>) t)
  command-line()
  normal-top-level()

**Comment by fnussbaum** [comment]
What is the value of `dotspacemacs-emacs-leader-key` in your configuration? At first glance it looks like it could be "m-m" which should probably be the default "M-m" instead and seems like it could explain the error.

Otherwise it could be helpful to post your system info.

**Comment by tstohne** [comment]
Where do * find the definition for *dotspacemacs-emacs-leader-key? Which
file?

**Comment by fnussbaum** [comment]
In the main spacemacs configuration file, usually ~/.spacemacs (or ~/.spacemacs.d/init.el).

**Comment by tstohne** [comment]
;; the leader key (default "spc")
   dotspacemacs-leader-key "spc"

   ;; the key used for emacs commands `m-x' (after pressing on the leader
key).
   ;; (default "spc")
   dotspacemacs-emacs-command-key "spc"

   ;; the key used for vim ex commands (default ":")
   dotspacemacs-ex-command-key ":"

   ;; the leader key accessible in `emacs state' and `insert state'
   ;; (default "m-m")
   dotspacemacs-emacs-leader-key "m-m" <--- This seems to be the source of
the error

   ;; major mode leader key is a shortcut key which is the equivalent of
   ;; pressing `<leader> m`. set it to `nil` to disable it. (default ",")
   dotspacemacs-major-mode-leader-key ","

   ;; major mode leader key accessible in `emacs state' and `insert state'.
   ;; (default "c-m-m" for terminal mode, "<m-return>" for gui mode).
   ;; thus m-ret should work as leader key in both gui and terminal modes.
   ;; c-m-m also should work in terminal mode, but not in gui mode.
   dotspacemacs-major-mode-emacs-leader-key (if window-system "<m-return>"
"c-m-m")

**Comment by fnussbaum** [comment]
It seems that at least this part (or maybe all) of your .spacemacs file has been converted to lower case by mistake? Do you have it under version control? [This is](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/.spacemacs.template) what it should look like without any customisation.

**Comment by tstohne** [comment]
Thank yoo! It is working now.
