### ISSUE TITLE
Key bindings for hide-show (hs)

### ISSUE THREAD

**Issue by mijoharas** [syl20bnr/spacemacs#1645]
working with a few files with large api's I'm starting to use [hide-show](https://www.gnu.org/software/emacs/manual/html_node/emacs/Hideshow.html). I think it could be handy if we added some spacemacs-ey bindings to these. Opening this issue to ask what the binding should be?

I was thinking that we would want to include:

```
hs-hide-all
hs-show-all
hs-show-block
hs-hide-block
```
I'd say probably in a group under `SPC h s` with some bindings under that. That is currently used by the function `hl-save-highlights` I'd suggest we use `A` and `a` for hide/show all and `B` and `b` for hide/show block.

What do you think?

**Comment by tuhdo** [comment]
I think the `z_` commands in Evil uses these by default.

**Comment by mijoharas** [comment]
awesome, wasn't aware of that. Thanks @tuhdo. I'm gonna close this issue.
