### ISSUE TITLE
built-in org package used. why?

### ISSUE THREAD

**Issue by vibrys** [syl20bnr/spacemacs#16464]
I'm running:
- emacs 29.3
- spacemacs latest develop, SHA1: 554d5cd16ee75cd03c065eb9b1e37907d54a5ee4 (Fri Jun 14 20:46:13 2024)
- Linux

org layer is enabled.
org-version returns: 
```
org-version is a variable defined in ‘org.el’.
Its value is "9.6.15"

```

in `.emacs.d/layers/+emacs/org/README.org`, I can read:

```
Spacemacs uses the =org= version from the ELPA repository
instead of the one shipped with emacs. Then, any =org= related code should not
be loaded before =dotspacemacs/user-config=, otherwise both versions will be
loaded and will conflict.

```

package-archives:
```
package-archives is a variable defined in ‘package.el’.

Its value is
(("melpa" . "https://melpa.org/packages/")
 ("gnu" . "https://elpa.gnu.org/packages/")
 ("nongnu" . "https://elpa.nongnu.org/nongnu/"))

```

from https://elpa.gnu.org/packages/org.html:
```
Description
    Outline-based notes management and organizer
Latest
    [org-9.7.5.tar](https://elpa.gnu.org/packages/org-9.7.5.tar) ([.sig](https://elpa.gnu.org/packages/org-9.7.5.tar.sig)), 2024-Jun-22, 9.69 MiB
Maintainer
    Bastien Guerry <bzg@gnu.org>

```

I also don't see org package present `elpa/29.3/develop` directory.

What did I miss?

I'd like to have newer org version installed into my spacemacs (at least newest 9.6.X) and I don't understand packages update doesn't take the newest version.

**Comment by nixmaniack** [comment]
I had a similar issue and `org-version` was stuck on `9.6.15`. Spacemacs defines the minimum version of `org` to be used [here](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bemacs/org/packages.el#L36). I am not sure if it's getting cached somewhere (compiled lisp files?) but what I did was changed the `:min-version` on that line to `9.6.30` and then restarted Spacemacs (`SPC q R`) which installed latest `org-version` **`9.7.5`**.

After that, I reverted that `:min-version` change without any issues.

**Comment by vibrys** [comment]
did the job for me! Thank you

**Comment by meritamen** [comment]
https://github.com/syl20bnr/spacemacs/blob/3b795ff4733a00f04ad07ced8e086ac968e7af1f/core/core-configuration-layer.el#L1744

`(configuration-layer//install-package ... 'org ... ...)` won't install `org` from elpa because of invoking`(package-installed-p 'org (version-to-list "9.6.15"))` returns true.

**Comment by smile13241324** [comment]
That's a bug, I'll put it in my queue
