### ISSUE TITLE
Enlarging font overlaps the line numbers

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1647]
I'm not sure if this is default emacs behaviour or not. 

Font is enlarged using `SPC z x +`

[See this image](https://lh3.googleusercontent.com/PXDHEsCxzThqvfjSNNYuyQK3RRhSGcfIyWjb397coHfJ=w707-h473-no)

Just thought I'd mention it

**Comment by tuhdo** [comment]
The fringe should be enlarged as well.

**Comment by StreakyCobra** [comment]
@geo7 Is this bug still appearing? :-)

**Comment by TheBB** [comment]
Yes it is. :-P

**Comment by StreakyCobra** [comment]
Oh crap, I was having several issues open at the same time and I confused this one with another. I was thinking of an OS X bug... I could have tested myself. Sorry for the disturbance.

**Comment by mmcnl** [comment]
I was having a similar issue and was able to fix it with this snippet I grabbed from StackOverflow:
```lisp
;; http://unix.stackexchange.com/a/237023
(require 'linum)
(defun linum-update-window-scale-fix (win)
  "fix linum for scaled text"
  (set-window-margins win
                      (ceiling (* (if (boundp 'text-scale-mode-step)
                                      (expt text-scale-mode-step
                                            text-scale-mode-amount) 1)
                                  (if (car (window-margins))
                                      (car (window-margins)) 1)
                                  ))))
(advice-add #'linum-update-window :after #'linum-update-window-scale-fix)

```

**Comment by TheBB** [comment]
Should be fixed in master.
