### ISSUE TITLE
Compilation buffer/window closes automatically

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#1648]
The default behaviour in spacemacs at the moment is to open a popwin window with the output from the compilation command, and if it returns with an error, leave this window open. If the compilation succeeds, the window is immediately closed.

In my workflow I prefer to keep a dedicated window with the `*compilation*` buffer open, whether with errors or not. Currently, even this window (created manually) is deleted upon a successful compilation.

This is pretty annoying. Is there a workaround?

**Comment by tuhdo** [comment]
For a workaround, you can customize `popwin:special-display-config` and remove compilation buffer entry, so `popwin` won't manage it and let you manage it.

**Comment by mijoharas** [comment]
Hi, btw, I have some long running compiles and I have use this workflow that keeps the compliation buffers open, it does require that the compile lasts at least a few seconds though.

when the buffer opens I go to it with `SPC w j` and then move it to the side next to the rest of my buffers with `SPC w L`. This will keep it open after it completes. Obviously this is not a solution, but thought I'd mention it in case you needed something in the short term.

**Comment by syl20bnr** [comment]
This auto-closing stuff can be removed, it feels out of place in spacemacs.

**Comment by TheBB** [comment]
I agree. I made a PR for that (#1677). There's always `SPC w p p`.

**Comment by shuber** [comment]
@TheBB Would it be possible to make this behavior configurable somehow? I like this default for most compilation related things, but when I run rspec I'd like for the window to automatically close on successful runs.

I'm coming from tmux + vim-dispatch + vim-rspec so that's why I'm used to that behavior.
