### ISSUE TITLE
[c-c++] There is no command under 'compile' leader key.

### ISSUE THREAD

**Issue by zongtaowang** [syl20bnr/spacemacs#16504]
#### Description :octocat:
[c-c++] layer the compile command is not defined

#### Reproduction guide :beetle:
- Start Emacs
- Open any .c file, for example test.c
- Press `,c`, then the minibuffer shows ", c-  which-key: There are no keys to show"

*Observed behaviour:* :eyes: :broken_heart:
There is no command under "compile" leader key
*Expected behaviour:* :heart: :smile:
I think it should show a pop window that lists the candidate command for compile the test.c file, and then another pop up windows to run the compiled file.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. d8d45287d)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(windows-scripts octave pdf json rust
                 (julia :variable julia-backend 'lsp julia-mode-enable-ess t)
                 (markdown :variables markdown-live-preview-engine 'vmd)
                 html emoji systemd yaml csv javascript spell-checking latex
                 (spacemacs-editing-visual :packages
                                           (not indent-guide))
                 (conda :variables conda-anaconda-home "/home/wangzongtao/anaconda3")
                 emacs-lisp
                 (bibtex :packages
                         (not helm-bibtex))
                 multiple-cursors ivy git
                 (python :variables python-backend 'lsp python-lsp-server 'pyright python-formatter 'black python-sort-imports-on-save nil python-format-on-save t)
                 (c-c++ :variables c-c++-backend 'lsp-clangd)
                 (org :variables org-enable-roam-support t org-enable-roam-ui t org-enable-roam-protocol t)
                 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-minimum-prefix-length 2 auto-completion-idle-delay 0.2 auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-use-company-box t auto-completion-enable-sort-by-usage t)
                 (shell :variables shell-default-shell 'vterm shell-default-height 60 shell-default-position 'bottom shell-default-term-shell "/bin/bash" shell-enable-smart-eshell t close-window-with-terminal t)
                 (better-defaults :variables better-defaults-move-to-beginning-of-code-first t better-defaults-move-to-end-of-code-first t)
                 (wzt :variables org-clock-watch-work-plan-file-path "/home/wangzongtao/research/org/gtd.org"))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
no
```

**Comment by smile13241324** [comment]
Please confirm that your lsp environment is properly loaded and your lsp server is connected.

This is when you enter "," you should see the which key window.

If not there is an issue in loading your config and you have to check your message buffer for errors.

**Comment by zongtaowang** [comment]
> Please confirm that your lsp environment is properly loaded and your lsp server is connected.
> 
> This is when you enter "," you should see the which key window.
> 
> If not there is an issue in loading your config and you have to check your message buffer for errors.

Thank you for your suggestion. I believe that the lsp environment has been properly loaded. I am able to utilize other lsp commands. For instance, by typing `,=b`, I can successfully run `lsp-format-buffer` command. Additionally, I have inspected the message buffer and found no errors either. By the way, what is displayed when you type `,c`? In my situation, it shows the key window, but there is no command under the 'compile' leader key.

**Comment by smile13241324** [comment]
This seems to be working for me. When I do SPC c I am seeing cmake-ide-compile.
Here is my config:
```elisp
     (c-c++ :variables
            c-c++-default-mode-for-headers 'c++-mode
            c-c++-backend 'lsp-clangd
            c-c++-lsp-enable-semantic-highlight 'rainbow
            c++-enable-organize-includes-on-save t
            c-c++-enable-clang-format-on-save t
            c-c++-adopt-subprojects t)
```

I have used this simple c file for testing:
```c
#include <stdio.h>
#include <stdlib.h>

int main(void) {
  char buffer[5];
  FILE *fp = fopen("myfile", "rb");

  if (fp == NULL) {
    perror("Failed to open file \"myfile\"");
    return EXIT_FAILURE;
  }

  if (fread(buffer, 1, 5, fp) < 5) {
    fputs("An error occurred while reading the file.\n", stderr);
    return EXIT_FAILURE;
  }

  fclose(fp);

  printf("The bytes read were: ");
  for (int i = 0; i < 5; ++i) {
    printf("%02X ", buffer[i]);
  }
  putchar('\n');

  return EXIT_SUCCESS;
}
```

I am also running clangd as lsp server.

Is there an error message in your message buffer?
