### ISSUE TITLE
Unable to Plot Graphs in R

### ISSUE THREAD

**Issue by ThePsychoBuck** [syl20bnr/spacemacs#16503]
#### Description :octocat:
Unable to plot graphs with R in ess layer.

#### Reproduction guide :beetle:
- Start Emacs
- Run SPC SPC R RET to open R REPL
- Run the command plot(1, 1) in the REPL

*Observed behaviour:* :eyes: :broken_heart:

```
Authorization required, but no authorization protocol specified

Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  : 
  unable to start device X11cairo
In addition: Warning message:
In (function (display = "", width, height, pointsize, gamma, bg,  :
  unable to open connection to X11 display ''
```

*Expected behaviour:* :heart: :smile:
A plot appears like the one when you run the command from a terminal.

#### System Info :computer:
- OS: gnu/linux (Fedora 40)
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. d0083f473)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion common-lisp emacs-lisp
                 (ess :variables ess-r-backend 'lsp)
                 git helm lsp
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM XWIDGETS GTK3 ZLIB

#### Backtrace :paw_prints:
```
```

**Comment by smile13241324** [comment]
It looks like your display var is empty can you double check your env file there should be an entry for it if not please add one manually and retry.

You could also open a terminal from spacemacs and run your repl there, if this is not working the issue is surely the missing display var.

Edit:
This assumes that the repl is using the env vars of emacs of course, if this is wrong some additional config would be necessary in Spacemacs

**Comment by ThePsychoBuck** [comment]
@smile13241324 thanks the issue is now fixed.
