### ISSUE TITLE
Spacemacs Loads .Rprofile when LSP is ON

### ISSUE THREAD

**Issue by ThePsychoBuck** [syl20bnr/spacemacs#16505]
#### Description :octocat:

Spacemacs loads .Rprofile 8-10 times when LSP is used.

#### Reproduction guide :beetle:
- Start Emacs
- Add this to .Rprofile:
  library(httpgd)
  hgd()
  hgd_browse()
- Open a .r file

*Observed behaviour:* :eyes: :broken_heart:
8-10 Tabs of hgd are opened in the browser when lsp is being used

*Expected behaviour:* :heart: :smile:
no tabs are opened.

#### System Info :computer:
- OS: gnu/linux (fedora 40)
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 36b52f1b7)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(common-lisp emacs-lisp
             (ess :variables ess-r-backend 'lsp)
             auto-completion git helm lsp
             (shell :variables shell-default-height 30 shell-default-position 'bottom)
             treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PGTK PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM XWIDGETS GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by smile13241324** [comment]
I don't think this is our bug, I assume the lsp server loads your rprofile with every new file.

You should open an issue in your lsp server project
