### ISSUE TITLE
display-buffer-alist not respecting window settings

### ISSUE THREAD

**Issue by 88-percent** [syl20bnr/spacemacs#16507]
In mu4e displaying the main-view removes all windows in the frame by calling `delete-other-windows`. This is apparently a [feature not a bug](https://github.com/djcb/mu/issues/2382#issuecomment-1498602874). I'm trying to get the mu4e main view to open in the window it is called.

The dev [helpfully suggests](https://www.djcbsoftware.nl/code/mu/mu4e/Buffer-display.html#Fine_002dtuning-the-main-buffer-display) updating `display-buffer-alist` to disable this behavior with the following elisp:

```elisp
(add-to-list 'display-buffer-alist
             `(,(regexp-quote mu4e-main-buffer-name)
               display-buffer-same-window))
```
While this seems to be [allowing most users to keep their window setup](https://github.com/djcb/mu/issues/2382#issuecomment-1499511114), it isn't working for me. This leads me to believe it may be an issue with how Spacemacs deals with `display-buffer-alist`.

I can see I've successfully stored the mu4e main buffer to the buffer alist because describing the variable returns:

```elisp
display-buffer-alist is a variable defined in ‘window.el’.

Its value is
(("\\*mu4e-main\\*" display-buffer-same-window)
 ("^ \\*org-contact\\*" display-buffer-below-selected)
 ("^\\*Ilist\\*$" imenu-list-display-buffer))
Original value was nil
```
Because this wasn't working for me I tried updating the Spacemacs-specific buffer alist.
```elisp
  (add-to-list 'spacemacs-display-buffer-alist
               `(,(regexp-quote mu4e-main-buffer-name)
                 display-buffer-same-window))
```
I noticed it needed the value stored to both variables to stick, but it looks like I've managed to store it appropriately:
```elisp
spacemacs-display-buffer-alist is a variable defined in ‘../../config.el’.

Its value is
(("\\*mu4e-main\\*" display-buffer-same-window)
 ("^ \\*org-contact\\*" display-buffer-below-selected)
 ("^\\*Ilist\\*$" imenu-list-display-buffer))

Not documented as a variable.
```
Even with these changes, every time mu4e's main view is displayed it wipes all my windows in the same frame. 

Why can't I get the main window displayed in the same window as called?

OS: Pop!OS 22.04
Emacs: 29.4
Spacemacs:  _latest develop_
mu4e: 1.12.5

**Comment by 88-percent** [comment]
I've been able to get the functionality working (more or less).

It seems there's nothing wrong with the above elisp, but that mu4e doesn't respect the settings on first launch.

For anyone else having this issue I got mu4e working within the window called in Spacemacs with the following 2 steps:

1) add the following elisp to `dotspacemacs/user-config`

```emacs lisp
  ;; stop mu4e decimating windows on launch
  (add-to-list 'display-buffer-alist
               `(,(regexp-quote mu4e-main-buffer-name)
                 display-buffer-same-window))
  (add-to-list 'spacemacs-display-buffer-alist
               `(,(regexp-quote mu4e-main-buffer-name)
                 display-buffer-same-window))
```
2. never quit mu4e. This can be done my simply switching from the `main-view` buffer instead of hitting q or alternatively using `space u q` to bury the `main-view` buffer. 

note: running mu4e the 1st time in each session will still wipe all windows in the frame.

**Comment by fnussbaum** [comment]
I don't use the spacemacs-purpose layer myself but can reproduce the problem on a default installation. `purpose-mode` seems to ignore `display-buffer-alist`, see for example https://github.com/bmag/emacs-purpose/issues/191 and https://github.com/bmag/emacs-purpose/issues/82. The following might help:
```elisp
(add-to-list 'purpose-action-function-ignore-buffer-names (regexp-quote mu4e-main-buffer-name))
```
I think the variable `spacemacs-display-buffer-alist` is not supposed to be changed manually, it seems to be an implementation detail of the Helm layer.
