### ISSUE TITLE
Deleting a file drops you into an InactiveMinibuffer with no spacemacs keybinds

### ISSUE THREAD

**Issue by nightkr** [syl20bnr/spacemacs#16513]
#### Description :octocat:
Deleting a file drops you into an InactiveMinibuffer with no spacemacs keybinds.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file
- Save it (if it doesn't already exist)
- Delete it (`SPC f d`)
- Confirm (`y`)

*Observed behaviour:* :eyes: :broken_heart:
The window switches to a "trap" InactiveMinibuffer with no regular Spacemacs keybinds available.
Clicking in the buffer opens a secondary window with the `*Messages*` buffer open, and the following new message:

    Error during redisplay: (eval (spaceline-ml-main)) signaled (error "Invalid face" spacemacs-nil-face)

*Expected behaviour:* :heart: :smile:
The window reverts to the previous buffer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 9ec2da8d3)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((sql :variables sql-capitalize-keywords nil)
 restclient
 (plantuml :variables plantuml-jar-path "/home/n/opt/plantuml-1.2024.3.jar")
 tabs react prettier nginx protobuf docker asciidoc php
 (csharp :variables csharp-backend 'lsp)
 systemd elixir erlang ansible kubernetes go csv dap
 (lsp :variables lsp-use-lsp-ui t)
 spacemacs-purpose pdf
 (typescript :variables typescript-backend 'lsp typescript-fmt-on-save t typescript-fmt-tool 'prettier typescript-linter 'eslint)
 ruby
 (python :variables python-backend 'anaconda)
 mu4e clojure lua graphviz graphql shell-scripts ranger
 (rust :variables rust-backend 'lsp)
 asm c-c++
 (haskell :variables haskell-completion-backend 'dante haskell-enable-hindent-style "gibiansky")
 idris auto-completion better-defaults yaml emacs-lisp git markdown org nixos
 (shell :variables shell-default-term-shell "/usr/bin/fish")
 java
 (scala :variables scala-backend 'scala-metals)
 html javascript
 (syntax-checking :variables syntax-checking-window-position 'bottom)
 version-control spacemacs-visual terraform)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

**Comment by henriquenj** [comment]
I can't reproduce this problem, I always end up in the previous buffer. But to me it looks like some problem with a spaceline theme. Have you tried another modeline? i.e. by customizing `dotspacemacs-mode-line-theme`. Or have you customize something related with the spaceline?

**Comment by smile13241324** [comment]
I can also not reproduce this when I start Spacemacs it starts in my project.org file when I then create a new file, i.e. new.org, and then remove it again I end up in the previous buffer.

I also assume this is a side effect of a config issue with your spaceline theme.

**Comment by smile13241324** [comment]
Not reproducible, possible configuration issue.

Please reopen when still relevant.
