### ISSUE TITLE
SPC o-  which-key: There are no keys to show

### ISSUE THREAD

**Issue by peter-lyr** [syl20bnr/spacemacs#16516]
![image](https://github.com/user-attachments/assets/4e49da0f-09f0-45cd-8628-0e8c84623bf7)

**Comment by fnussbaum** [comment]
This is expected in a default installation, as the <kbd>SPC o</kbd> prefix is reserved for user-defined bindings. Have you tried to define a custom key binding under that prefix?

**Comment by smile13241324** [comment]
Basically SPC o is a reserved pre-fix key intended for user bindings. If you don't add any binding it will be empty and not do anything. Therefore this is not a bug.
