### ISSUE TITLE
xclipboard layer does not work

### ISSUE THREAD

**Issue by yashaswikarnati** [syl20bnr/spacemacs#16518]
spacemacs version - 0.999.0@29.3
Ubuntu 24.04

I add xclipboard layer by adding line -   (xclipboard :variables xclipboard-enable-cliphist t)

I can see that the layer gets loaded (screenshot). But I cant see any of the key bindings SPC x p. SPC x y etc. 

At SPC x y i see something called - link-hint-copy-link-at-point but nothing exist for SPC x p. 

![image](https://github.com/user-attachments/assets/656da9ea-1707-4ebe-9470-4997604423a2)

**Comment by henriquenj** [comment]
Try to restart emacs with debug on and see if something shows up. You can use `spacemacs/restart-emacs-debug-init` or `SPC q d` for that.

**Comment by smile13241324** [comment]
I have loaded the layer and it seems to be working ok. I have found an issue with the binding of SPC x R but all other bindings work correctly.

Please double check the OS level requirements for this package and double check that the applications are available from emacs i.e. from a terminal opened with Spacemacs. 

You should also double check your message buffer and double check that your config is working properly if not it will stop the loading process and cause a lot of missing bindings in the end.

**Comment by smile13241324** [comment]
Config issue, please reopen when still relevant.
