### ISSUE TITLE
internal-macroexpand-for-load error when doing `M-x magit-status` after latest update

### ISSUE THREAD

**Issue by komali2** [syl20bnr/spacemacs#16524]
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>
<<BE AWARE YOU NEED A GITHUB ACCOUNT TO SEND THIS REPORT>>

Immediately after updating today, whenever I run `M-x magit-status`, I get the following error, and the magit status buffer doesn't display.

```
internal-macroexpand-for-load: Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 5) [2 times]
```

Could this possibly be related to this commit? https://github.com/syl20bnr/spacemacs/commit/54cccbec8bc4a22d7347f83e0cd743b282f8be72 (edit: possibly not? Reverting it locally didn't seem to resolve, though it's weird that the error only started happen right after I updated)

#### Reproduction guide :beetle:
- Start Emacs
- Navigate to a file in an initialized git repository
- Do `M-x magit-status`
- Observe error

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
The above listed error

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>
The display of the magit status buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 30.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. a7ed59787)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby php nginx csv lua emacs-lisp helm (lsp :variables lsp-idle-delay 1.0)
      treemacs rust yaml go better-defaults git markdown
      (org :variables org-directory "~/Org" org-projectile-file
           "~/Org/projects.org" org-enable-roam-support t
           org-enable-org-journal-support t org-roam-directory "~/Org/notes/"
           org-roam-index-file "~/Org/notes/20200526213916-index.org"
           org-default-notes-file (concat org-directory "/inbox.org")
           org-roam-v2-ack t org-enable-hugo-support t org-startup-indented t
           org-refile-targets
           '((nil :maxlevel . 9) (org-agenda-files :maxlevel . 9))
           org-outline-path-complete-in-steps nil org-refile-use-outline-path t
           org-startup-with-inline-images t org-image-actual-width '(300))
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (spell-checking :variables spell-checking-enable-by-default nil) c-c++
      semantic syntax-checking version-control javascript python sql html
      (typescript :variables typescript-indent-level 2)
      (node :variables node-add-modules-path t) racket tern common-lisp colors
      react (svelte :variables svelte-backend 'lsp))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ IMAGEMAGICK JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
Loading /home/caleb/.spacemacs...done
(Spacemacs) Warning: could not find banner ~/Downloads/Pics/cyberpunk1.png
.emacs.legacy/elpa/30.0/develop/evil-iedit-state-20220219.1432/evil-iedit-state-autoloads.el: Warning: ‘defadvice’ is an obsolete macro (as of 30.1); use ‘advice-add’ or ‘define-advice’
Spacemacs is ready.
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-next-line’ originally mapped on ‘C-n’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-toggle-time-grid’ originally mapped on ‘G’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-filter-remove-all’ originally mapped on ‘|’
Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
   - ‘org-agenda-filter-by-tag’ originally mapped on ‘\’
org-super-agenda-mode enabled.
Skipping check for new version (reason: dotfile)
(Spacemacs) Warning: could not find banner ~/Downloads/Pics/cyberpunk1.png
Loading /home/caleb/.emacs.legacy/.cache/recentf...done
[yas] Prepared just-in-time loading of snippets successfully. [2 times]
internal-macroexpand-for-load: Eager macro-expansion failure: (wrong-number-of-arguments (3 . 4) 5) [2 times]

```

**Comment by meritamen** [comment]
I cannot reproduce this issue.

**Comment by komali2** [comment]
> I cannot reproduce this issue.

Hm, not sure. I was able to resolve it by deleting the `magit` packages and reinstalling them. Perhaps I will close the issue with that and reopen if it happens when I update my other machine tomorrow, which runs the same OS.
