### ISSUE TITLE
Modeline RHS missing when viewing info help

### ISSUE THREAD

**Issue by Zoybean** [syl20bnr/spacemacs#16521]
#### Description :octocat:
Right-hand side of the modeline (notably including the screen position) disappears when viewing info's "getting started" help. I only noticed because the help file specifically mentioned to expect the "Top" to show in the modeline.

If I change the spacemacs distribution to `spacemacs-base`, this no longer occurs, with the position remaining in the modeline. This only appears to be an issue in the `spacemacs` distribution. 

#### Reproduction guide :beetle:
- Start Emacs
- `SPC SPC info RET`
- `C-z h`

*Observed behaviour:* :eyes: :broken_heart:
Right-hand side of the modeline disappears from info buffers. Does not appear to be resolved by restarting emacs, (whether restarting the client or server, or running standalone), or restarting the computer. Ordinary file buffers appear unaffected.

*Expected behaviour:* :heart: :smile:
Modeline is unaffected by viewing info's 'getting started' help

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.3
- Spacemacs: 0.999.0
- Spacemacs branch: nil (rev. eb6bd5e11)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git helm lsp multiple-cursors org treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

**Comment by fnussbaum** [comment]
This sounds like the intended behaviour of the Spacemacs modeline in info buffers (though the mode-line-format should not change when viewing a specific page like "Getting Started"). The info modeline displays two segments for me, in particular in the "Getting Started" buffer: "INFO info" and the breadcrumbs "Top > Getting Started > Help".

You could instead use the default Spacemacs modeline also in info buffers with the following:
```elisp
(spaceline-info-mode -1)
(Info-breadcrumbs-in-mode-line-mode -1)
```

Or you could overwrite the info modeline with additional segments, for example:
```elisp
(spaceline-compile 'info
  '(info-topic (info-nodes :separator " > "))
  '(which-function
    ((point-position
      line-column))
    (buffer-position)
    (hud)))
```
See https://github.com/TheBB/spaceline?tab=readme-ov-file#tweaking-or-defining-your-own-mode-line and https://github.com/TheBB/spaceline/blob/086420d16e526c79b67fc1edec4c2ae1e699f372/spaceline-config.el#L144-L169

**Comment by smile13241324** [comment]
Intended behaviour, can be solved with use config.
