### ISSUE TITLE
[Haskell] Autocomplete not working

### ISSUE THREAD

**Issue by thunklife** [syl20bnr/spacemacs#1652]
I recently enabled the Haskell layer and ran into a number of problems. Most of them were corrected by updating to 0.101.4, and by using the hotfix described in https://github.com/syl20bnr/spacemacs/issues/1136. The problem I have now is there is no more autocomplete. Everything else appears to be working (auto-indentation is all messed up but that's already been documented).

When I open a Haskell file, I get the following error
```File mode specification error: (void-function electric-indent-local-mode)```

**Comment by wilhelmson** [comment]
I was able to get around this by commenting out ```(electric-indent-local-mode -1)``` in ```~/.emacs.d/contrib/lang/haskell/packages.el```



From what I could find, ```electric-indent-local-mode``` was introduced with Emacs 24.4.

**Comment by syl20bnr** [comment]
Thank you for the feedback I will push the fix for #1136 in the current release.

For the other issue, you are using 24.3 ?

**Comment by d12frosted** [comment]
@thunklife do you still experience described problem?

**Comment by d12frosted** [comment]
@syl20bnr I think it's already solved by 7f24d019a129b2552b5d3a33c6f6f80e71e24469.

**Comment by thunklife** [comment]
Sorry, I've been on vacation. I'm no longer having an issue.

**Comment by d12frosted** [comment]
@thunklife Welcome back :smile: 

> I'm no longer having an issue.

Good to hear :smile:
