### ISSUE TITLE
links don't open

### ISSUE THREAD

**Issue by Kossak-esky** [syl20bnr/spacemacs#16560]
#### Description :octocat:
Links in org mode don't open. I tried pressing enter on links, `SPC x o`, clicking the link with LMB, but nothing works. How to fix it?

#### Reproduction guide :beetle:
- Start Emacs
- open org file with an links
- click any link (or press enter on any link)

*Observed behaviour:* :eyes: :broken_heart:
no new tab is opened in current browser

*Expected behaviour:* :heart: :smile:
new tab opens with the url I clicked

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. f436be6ed)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm org treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

**Comment by fnussbaum** [comment]
I cannot reproduce this, for me links open with either <kbd>SPC x o</kbd>, <kbd>RET</kbd> or left click. Are there any errors in your \*Messages\* or \*Warnings\* buffers? What is the value of the variable `org-version` on your system, and are packages up to date?

**Comment by Kossak-esky** [comment]
In \*Warnings\* I have lot's of:
`⛔ Warning (org-element): ‘org-element-at-point’ cannot be used in non-Org buffer #<buffer *helm org inbuffer*> (helm-major-mode)`

My `org-version` is 9.7.11

I installed new os (CachyOS) and it is like this from the begining. On my old os (Manjaro) links worked as they should.

**Comment by tomichec** [comment]
I have a same problem on Debian 12, spacemacs develop rev f436be.

when I run `M-x shell` and try to open the link, i get the following output:
```
 $  xdg-open https://duckduckgo.com
 $  Authorization required, but no authorization protocol specified
Error: cannot open display: :0
```

**Comment by tomichec** [comment]
So for me the problem was solved by removing `spacemacs.env` (as `mv ~/.spacemacs.env{,.backup}`) and restarting spacemacs. Now the links open `, x o` (I hope it will be persistent)

Inspired by https://github.com/syl20bnr/spacemacs/issues/11812

**Comment by smile13241324** [comment]
Please remove your spacemacs.env file and retry.

**Comment by tkossak** [comment]
> So for me the problem was solved by removing `spacemacs.env` (as `mv ~/.spacemacs.env{,.backup}`) and restarting spacemacs. Now the links open `, x o` (I hope it will be persistent)
> 
> Inspired by #11812

It works (the file was recreated). Thank you. We'll see if it works across reboots.
I checked the differences between old and new env file, and some env vars that were different were XAUTHORITY or env vars pointing to session type (like `XDG_SESSION_TYPE`) - wayland vs x11.

**Comment by Kossak-esky** [comment]
> So for me the problem was solved by removing `spacemacs.env` (as `mv ~/.spacemacs.env{,.backup}`) and restarting spacemacs. Now the links open `, x o` (I hope it will be persistent)
> 
> Inspired by #11812

It works (the file was recreated). Thank you. We'll see if it works across reboots.
I checked the differences between old and new env file, and some env vars that were different were XAUTHORITY or env vars pointing to session type (like `XDG_SESSION_TYPE` - wayland vs x11)

**Comment by tomichec** [comment]
Unfortunatelly it was not persistent for me... After reboot I needed to remove the `~/.spacemacs.env` again.

Here the difference between current (links working) and previous version (`diff .spacemacs.env .spacemacs.env.2024-09-09\@15-16`)
[.spacemacs.env.diff](https://github.com/user-attachments/files/16931544/spacemacs.env.txt)

**Comment by Kossak-esky** [comment]
Not persistent for me either. `diff .spacemacs.env .spacemacs.env.old`: (same session type - x11)
```diff
32c32
< DESKTOP_STARTUP_ID=lman4;1725952683;339126;1041_TIME2064106
---
> DESKTOP_STARTUP_ID=lman4;1725879405;747236;1027_TIME15202338
39,41c39,41
< ICEAUTHORITY=/run/user/1000/iceauth_LWDoVD
< INVOCATION_ID=63c6c19a4a1041e2b2c76fe8d31e86e7
< JOURNAL_STREAM=9:8945
---
> ICEAUTHORITY=/run/user/1000/iceauth_RNbljT
> INVOCATION_ID=02c7c8c10f1f477cb263c17068b73426
> JOURNAL_STREAM=9:15781
59c59
< MANAGERPID=924
---
> MANAGERPID=900
72c72
< SESSION_MANAGER=local/lman4:@/tmp/.ICE-unix/1014,unix/lman4:/tmp/.ICE-unix/1014
---
> SESSION_MANAGER=local/lman4:@/tmp/.ICE-unix/989,unix/lman4:/tmp/.ICE-unix/989
75c75
< SYSTEMD_EXEC_PID=1041
---
> SYSTEMD_EXEC_PID=1027
78c78
< XAUTHORITY=/tmp/xauth_WSnYSp
---
> XAUTHORITY=/tmp/xauth_WXIykE
```

**Comment by fnussbaum** [comment]
I don't know which environment variable is responsible here, so there might be a better way to fix this. In any case you could try using the [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) package to manage the environment variables instead of the `.spacemacs.env` file. See also https://develop.spacemacs.org/doc/DOCUMENTATION.html#managing-environment-variables-by-yourself.

**Comment by smile13241324** [comment]
@Kossak-esky I have tweaked the env generation file a bit to try to remove all volatile storage values which could break your system if they are saved between two sessions.

Can you remove your env file again and see if the issue persists after a restart?
If it does I would be very happy about another diff between your two files, the one working and the one not.

**Comment by Kossak-esky** [comment]
@smile13241324 It worked across reboots, thank you!
