### ISSUE TITLE
evil-visual-state-map "<" keybinding makes cursor jump

### ISSUE THREAD

**Issue by bmillwood** [syl20bnr/spacemacs#16573]
#### Description :octocat:
evil-visual-state-map "<" keybinding makes cursor jump to the location of the previous selection, which can be somewhere completely different in the document.

#### Reproduction guide :beetle:
- Start Emacs
- Open scratch buffer (SPC b s)
- Write two lines of text
- Shift-V to visual-select one line and > to indent it
- Escape to exit visual-line mode
- Move to the other line, shift-V, >

*Observed behaviour:* :eyes: :broken_heart:
- Line is indented but then cursor jumps to first line

*Expected behaviour:* :heart: :smile:
- Line is indented and cursor stays put (preferably still in visual-line mode, but not too fussed either way)

#### Commentary
If I enter visual-line mode and press SPC SPC describe-key <, I get:
```
< runs the command (lambda nil (interactive) (progn (call-interactively
'evil-shift-left) (execute-kbd-macro "gv"))) (found in evil-visual-state-map),
which is an interactive Lisp function.
```
If I press v and scroll through the pop-up, it seems like `g v` is bound to `evil-visual-restore`, for which the doc is simply "Restore previous selection". Just running `evil-shift-left` in visual mode (e.g. by rebinding the key) exits me from visual mode, and I wonder if the point here is to keep me in the same visual mode, and indeed running `g v` after the rebound key does put me back in the "correct" visual mode. Perhaps what's happening here is that the "gv" keyboard macro is being run before the "previous" selection has been updated to the current one?

I'm working around this by rebinding those keys, but I can't imagine this behaviour is deliberate. I think I reproduced it on a fresh Spacemacs install with default options, but it's possible my install was somehow not entirely fresh.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 2cb35317a)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion emacs-lisp markdown multiple-cursors org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     syntax-checking)
```
- System configuration features: CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XAW3D XDBE XIM XINPUT2 XPM LUCID ZLIB

#### Backtrace :paw_prints:
not relevant

**Comment by fnussbaum** [comment]
Thanks for the thorough report! Should be fixed in https://github.com/syl20bnr/spacemacs/pull/16574.
