### ISSUE TITLE
macOS installation thinks I am under linux 

### ISSUE THREAD

**Issue by moritzschaefer** [syl20bnr/spacemacs#16587]
#### Description :octocat:
I installed `d12frosted/emacs-plus/emacs-plus@29`, and cloned spacemacs to .emacs.d (develop branch). However, when starting, I can only select whether I want the "vim" or "emacs" keybindings and afterwards it crashes with the error

`(Creating directory. Operation not supported /home/moritz)`

The obvious reason being that under macOS, there is no /home (rather /Users). 

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

```
Warning (initialization): An error occurred while loading ‘/Users/moritz/.emacs.d/init.el’:

File error: Creating directory, Operation not supported, /home/moritz
```

*Expected behaviour:* :heart: :smile:
.spacemacs initializes as expected

**Comment by alexey0308** [comment]
Hi Moritz @moritzschaefer, is it happening with the default `.spacemacs` as well? Just to exclude the case that you might have some hand-coded paths in your config with "/home" in it.

You can also set `(setq debug-on-error t)` in the beginning of you init.el file and see what is the error source.

**Comment by moritzschaefer** [comment]
Thanks, it was due to .spacemacs.env! I got heavily confused because the error arose from init.el (instead of my .spacemacs.d config).
