### ISSUE TITLE
layouts-transient-state/body returns function definition is void: lexical-let

### ISSUE THREAD

**Issue by RidaAyed** [syl20bnr/spacemacs#16604]
#### Description :octocat:
`M-x layouts-transient-state/body` is not working anymore. Error `let: Symbol’s function definition is void: lexical-let`

#### Reproduction guide :beetle:
- Start Emacs
- Hit `SPC l` or `M-x layouts-transient-state/body`

*Observed behaviour:* :eyes: :broken_heart:
Ttransient state is shown though **not working at all** and alongside this error:
`let: Symbol’s function definition is void: lexical-let`

*Expected behaviour:* :heart: :smile:
layouts-transient is shown in minibuffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 844de3153)
- Graphic display: t
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t)
 systemd graphviz
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t enable-flyspell-auto-completion t)
 yaml
 (json :variables json-fmt-tool 'web-beautify)
 latex pass csv prodigy
 (treemacs :variables treemacs-use-all-the-icons-theme t)
 search-engine
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-sort-by-usage t auto-completion-idle-delay 0.2 auto-completion-minimum-prefix-length 2)
 exwm emacs-lisp git helm finance
 (org :variables org-enable-hugo-support t org-enable-github-support t)
 (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'right spacemacs-vterm-history-file-location "~/.bash_history")
 (version-control :packages
                  (not git-gutter))
 mu4e pdf
 (python :variables python-backend 'lsp python-lsp-server 'pyright python-test-runner 'pytest))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

#### Backtrace :paw_prints:
Debugger entered--Lisp error: (void-function lexical-let)
  (lexical-let ((on-exit on-exit)) #'(lambda nil (setq exwm-input-line-mode-passthrough nil) (if on-exit (progn (funcall on-exit)))))
  (let ((on-exit (lexical-let ((on-exit on-exit)) #'(lambda nil (setq exwm-input-line-mode-passthrough nil) (if on-exit (progn ...)))))) (funcall fun keymap on-exit foreign-keys))
  ...
```

**Comment by emacs18** [comment]
I can't find any use of `lexical-let` within spacemacs or emacs 29.

Also revision `844de3153` does not seem to exist within spacemacs git repo.

**Comment by smile13241324** [comment]
I cannot reproduce your error, however from your stacktrace I can see that your issue happens in exwm not in Spacemacs. Please retry without exwm and reply here. I have made a small change to fix the setup of exwm for the latest version which was referring to an obsolete exwm-config file.

Unfortunately I cannot test with exwm as I am running a pure wayland build.

**Comment by RidaAyed** [comment]
Indeed. No issue with an installation from scratch. :small_airplane:
