### ISSUE TITLE
Python buffers cannot be formatted on saving if `python-formatter` is `'lsp`

### ISSUE THREAD

**Issue by JohnADawson** [syl20bnr/spacemacs#16632]
#### Description :octocat:
The Python layer's documentation states

> To enable automatic buffer formatting on save set the variable `python-format-on-save` to `t`. The formatter specified by `python-formatter` will be used.

https://develop.spacemacs.org/layers/+lang/python/README.html#automatic-buffer-formatting-on-save

But Python buffers are not formatted on saving when `python-format-on-save` is `t` and `python-formatter` is `'lsp` (even if `SPC m = =` and `SPC m = b` do format the buffer).

#### Reproduction guide :beetle:
- In Bash run
```bash
mkdir ~/Documents/play
cd ~/Documents/play
python3 -m venv .venv
source .venv/bin/activate
pip install python-lsp-server ruff
```
- In .spacemacs put
```elisp
(setq-default
 dotspacemacs-configuration-layers
 '((python :variables
           python-format-on-save t
           python-formatter 'lsp)
   lsp))
```
- Restart Emacs.
- Do `SPC f f ~/Documents/play/play.py`.
- If prompted choose the project of `play.py`.
- Write `x=['a' ]`.
- Do `SPC f s`

*Observed behaviour:* :eyes: :broken_heart:
`x=['a' ]` remains unchanged.

*Expected behaviour:* :heart: :smile:
`x=['a' ]` becomes `x = ["a"]`. (This is the change effected by `SPC m = =` or `SPC m = b`.)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.3
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 4d7be229a)
- Graphic display: t
- Running in daemon: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((python :variables python-format-on-save t python-formatter 'lsp)
 emacs-lisp helm lsp multiple-cursors treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

**Comment by fnussbaum** [comment]
Thanks for the report, this should be simple to fix. Though we need to take into account that the pyright lsp server does not support formatting, only pylsp does.

**Comment by JohnADawson** [comment]
@fnussbaum, thank you. Note that `SPC SPC lsp-format-buffer` appears to take into account the distinction you mention, as it works correctly. This bug appears to be with formatting _on saving_ specifically.
