### ISSUE TITLE
Helm-posframe seems to break completely the display on the terminal.

### ISSUE THREAD

**Issue by blaa** [syl20bnr/spacemacs#16644]
If you are posting about a *bug* please close this issue and open a new one from within Spacemacs using:
- `SPC h I`
- `M-m h I`
Will this even work in the terminal (emacs -nw)? It opens the Github, but seems impossible to login.

ANYWAY:

#### Description :octocat:
helm-posframe in new spacemacs completely wrecks the terminal (emacs -nw) each time it's called.
It also ignores the controlling variable, maybe because there's a typo in packages.el:
    (helm-posframe :toogle helm-use-posframe)
note the oo instead of og.

#### Reproduction guide :beetle:
- Start Emacs in terminal (-nw, or over SSH) while configured for Helm.
- Press SPC SPC
- Display breaks

*Observed behaviour:* :eyes: :broken_heart:
SPC SPC breaks the display.

*Expected behaviour:* :heart: :smile:
Like it was before - working. ;)
I think it should not be default if it breaks the terminal/SSH users. Should be documented in README and possible to disable. helm-posframe on github looks really abandoned BTW, with calls for new maintainer. Maybe it should not be used at all? 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 31.0.50
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 60dcd8cf9)
- Graphic display: nil
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((shell :variables shell-default-height 30 shell-default-position 'bottom) helm
 emacs-lisp better-defaults multiple-cursors
 (tree-sitter :variables tree-sitter-syntax-highlight-enable t
              tree-sitter-fold-enable t tree-sitter-fold-indicators-enable t)
 python javascript asm html markdown sql csv protobuf dap graphviz docker yaml
 latex plantuml
 (mu4e :variables mu4e-installation-path
       "/usr/share/emacs/site-lisp/elpa-src/mu4e-1.12.6")
 xclipboard helm
 (auto-completion :variables auto-completion-private-snippets-directory
                  "~/.emacs.custom/snippets/")
 git markdown
 (org :variables org-enable-github-support t org-enable-roam-support t
      org-enable-org-journal-support t org-enable-bootstrap-support t
      org-enable-reveal-js-support t org-enable-sticky-header t
      org-enable-epub-support t org-roam-v2-ack t)
 (c-c++ :variables c-c++-backend 'lsp-clangd c-c++-enable-clang-format-on-save
        nil c-c++-enable-auto-newline t c++-enable-organize-includes-on-save nil
        c-c++-default-mode-for-headers 'c++-mode)
 (lsp :variables lsp-ui-doc-delay 2 lsp-ui-doc-max-height 10 lsp-ui-doc-enable
      nil lsp-ui-imenu-auto-refresh t lsp-ui-imenu-auto-refresh-delay 1.0
      lsp-rust-server 'rust-analyzer)
 (rust :variables rust-backend 'lsp) themes-megapack syntax-checking
 version-control)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ IMAGEMAGICK JPEG LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODU\
LES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XAW3D XDBE XIM XINPUT2 XPM LUCID ZLIB

**Comment by svenpanne** [comment]
... and even when it work's, it makes the UX horrible. Try e.g. `M-m s p` (a project-wide smart search), and you get that ridiculously small frame in the middle, making the search results basically unreadable due to tons of line wrapping. The same happens for basic stuff like e.g. `C-x b`, the buffer list is unreadable, too, because of heavy wrapping.

IMHO it's OK to leave that package in Spacemacs, but the default should definitely be "off", as it breaks far too many things.

**Comment by svenpanne** [comment]
Related question: How can the new feature be disabled in the config file?
```elisp
 (helm :variables helm-use-posframe nil)
```
doesn't seem to have any effect.

**Comment by blaa** [comment]
> Related question: How can the new feature be disabled in the config file?
> 
> ```emacs-lisp
>  (helm :variables helm-use-posframe nil)
> ```
> 
> doesn't seem to have any effect.

You need to fix the typo in packages.el for helm - toogle to toggle. As stated in my report.

**Comment by svenpanne** [comment]
Sorry, I didn't read your report closely enough. So in a nutshell: When the typo is has been fixed, we get the right default, i.e. the new feature is off. :smile:

**Comment by jaeyeom** [comment]
The fix is already here. Review is pending.

https://github.com/syl20bnr/spacemacs/pull/16645
