### ISSUE TITLE
"load-hints" feature leaves behind autoload.el files in buffer list after rebuilding

### ISSUE THREAD

**Issue by ViktorHaag** [syl20bnr/spacemacs#16646]
#### Description :octocat:

After commit bd37f169c74f541a07729d209d7b1b1adfa77a5d ("Speedup the Spacemacs
startup/loading with load-hints"), after installing one or more packages,
Spacemacs leaves around a bunch of buffers for the rebuilt autoload.el files.
These should get cleaned up so that they don't pollute the user's buffer
workspace.

#### Reproduction guide :beetle:
- Start Emacs
- Go to your .spacemacs file and ;; comment out a package to auto-remove it on
next startup
- Restart (package gets removed)
- Go to your .spacemacs file and uncomment to re-install the package you removed
- Restart (package should get re-installed)

Note that updating the current packages (and restarting to install the updates),
or installing a new package will do the same thing.

*Observed behaviour:* :eyes: :broken_heart:
After the repro steps rebuilt autoload files associated with the package
installed/updated will be in the buffer list after restart.

*Expected behaviour:* :heart: :smile:
Autoload elisp files that were involved in the rebuilding should be cleaned up
and not appear in the buffer list after startup sequence is complete.

#### System Info :computer:
- OS: darwin
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: legacy-local-develop (rev. 7870794cb)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: compleseus
- Layers:
```elisp
(auto-completion compleseus denote-personal emacs-lisp git html ibuffer-personal
                 (javascript :variables js-switch-indent-offset 4)
                 local-functions markdown multiple-cursors
                 (org :variables org-enable-github-support t org-enable-org-journal-support t)
                 (osx :variables osx-command-as 'meta osx-option-as 'super osx-control-as 'control osx-function-as nil)
                 (python :variables python-backend 'lsp python-formatter 'black python-format-on-save t python-lsp-server 'pyright python-shell-interpreter "~/.pyenv/shims/ipython3")
                 restructuredtext spacemacs-editing syntax-checking tern theming
                 (treemacs :variables treemacs-use-icons-dired nil)
                 yaml)
```
- System configuration features: ACL GLIB GMP GNUTLS JSON LCMS2 LIBXML2 MODULES NOTIFY KQUEUE PDUMPER RSVG SQLITE3 THREADS TOOLKIT_SCROLL_BARS TREE_SITTER WEBP XIM XWIDGETS ZLIB

**Comment by smile13241324** [comment]
@sunlin7 can you take a look? I think some more tweaking is required to make the load hints work properly

**Comment by sunlin7** [comment]
Hi @smile13241324 @ViktorHaag 

It won't affect the load-hints feature.

Yeh, I didn't close the `*-autoloads.el` buffers for don't know it was opened before the operation or not. I'm searching a better way to modify a `*-autoloads.el` when it already opened by Emacs,
give me some time, will push a new MR to fix that.

Currently please close these `*-autoloads.el` buffers manually. Thanks. If possible, please let me know does the `load-hints` works for you or not (I tested on Windows 11/Ubuntu 20.04, but don't have the result from a macOS).

**Comment by sunlin7** [comment]
Okay, actually the function `package-generate-autoloads` will close the `*-autoloads.el`, so open the `*-autoloads` file to apply patch then close it after the function is acceptable. 

Please help review the changes. Thanks

**Comment by sunlin7** [comment]
@smile13241324  Thank you so much! Appreciate it !

**Comment by smile13241324** [comment]
@ViktorHaag I have merged @sunlin7 fix, please double check and confirm if it is working.
