### ISSUE TITLE
Keybinds missing if compleseus is enabled.

### ISSUE THREAD

**Issue by shanff** [syl20bnr/spacemacs#16649]
#### Description :octocat:
Keybinds under SPC a are lost with compleseus enabled 

#### Reproduction guide :beetle:
- Start Emacs
- enable games and compleseus.  Restart emacs and allow games and compleseus to install.
- hit SPC a f - it will say there are no keybinds available.
- comment out compleseus, restart, and keybinds are there.

*Observed behaviour:* :eyes: :broken_heart:
SPC a f and SPC a c don't work if compleseus layer is enabled

*Expected behaviour:* :heart: :smile:
All keybinds should work that which-key knows about (unless manually bound incorrectly)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 6581c82b3)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp syntax-checking games git ivy lsp markdown multiple-cursors org templates outshine unicode-fonts multiple-cursors parinfer spacemacs-defaults spacemacs-project spotify csv json spacemacs-base markdown yaml shell-scripts major-modes sql go lua python elfeed epub pdf themes-megapack theming colors docker eww pandoc pass prettier restclient shell tree-sitter xclipboard evil-better-jumper evil-commentary evil-snipe vim-empty-lines hackernews
                 (llm-client :variables llm-client-enable-ellama t llm-client-enable-gptel t)
                 reddit search-engine version-control treemacs)
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by fnussbaum** [comment]
Adding support for compleseus to the games layer should be relatively simple, if anyone is interested in doing that. Which key bindings exactly (or which layer's keybindings) are you missing under the <kbd>SPC a c</kbd> prefix?

**Comment by shanff** [comment]
I was mistaken on the `SPC a c` binding, I just had no chat-layers installed.  I'm a bit confused about your comment on adding support for compleseus to the games layer though.  Might just be misunderstanding what you're saying.  I went through the config, and it 'seems' as though the bindings are configured properly to show up.  I just don't understand how adding the compleseus layer disables the games bindings, when they're configured separately under differing layers.  I've been using Doom for a while and haven't used Spacemacs for any long period of time in the past, so I may just be misunderstanding the loading of things in Spacemacs.

**Comment by fnussbaum** [comment]
The local package helm-games is only installed and loaded when the helm package is used:
https://github.com/syl20bnr/spacemacs/blob/6f15f8774f087b5851dcc7c73cc782f252f159a0/layers/%2Bfun/games/packages.el#L26-L27

You could add helm to `dotspacemacs-additional-packages` which should make the keybindings work (while still using compleseus instead of helm for everything else).

**Comment by shanff** [comment]
That indeed did fix it.  Not sure why having a completion framework (helm in this case) as a dependency for games, but it's doing the expected now.  Thanks!
