### ISSUE TITLE
evil-iedit-state/iedit-mode', not defined

### ISSUE THREAD

**Issue by jonesberg** [syl20bnr/spacemacs#1665]
Using spacemacs 0.101.4, evil-iedit-state/iedit-mode doesn't seem to be working.

How to reproduce : 

`M-x describe-key` `<spc> - s - e`

```
SPC s e runs the command evil-iedit-state/iedit-mode, which is an alias for 
`evil-iedit-state/iedit-mode', which is not defined.  Please make a bug report.

[back]
```

---

`C-;` doesn't seem to work either. I can use `iedit-mode` (tried on a temp buffer) after doing `M-x iedit-mode`

**Comment by TheBB** [comment]
Can you still produce this? I can't.

**Comment by jonesberg** [comment]
Good evening!

Using version 0.103.6, `<spc>-s-e` works correctly on my machine.
I guess we can close it. (May I?)
