### ISSUE TITLE
undefined method in rails project 

### ISSUE THREAD

**Issue by lufeihaidao** [syl20bnr/spacemacs#1666]
Ruby mode shows `render`, `respond_to`, `before_action` as undefined method, and shows model name like `User` as undefined constant. Is it a known problem?

**Comment by jesenko** [comment]
These errors are probably reported by `ruby-lint` gem. My ruby files got cluttered by such errors when I installed `ruby-lint` gem. Once installed `flycheck` package from `syntax-checking` layer automatically starts running `ruby-lint`.

I fixed my issue by simply running `gem uninstall ruby-lint` as I did not need it anyways.

**Comment by ralesi** [comment]
There is also support for config files in for `ruby-lint` by supplying `flycheck-rubylintrc`.  https://github.com/flycheck/flycheck/issues/424

**Comment by lufeihaidao** [comment]
@ralesi thanks~

**Comment by StreakyCobra** [comment]
All this seems to be a normal behaviour that need some user configurations. It probably needs to be documented in the FAQ or in the ruby layer's README. I let ruby people decide what's the best solution :-)
