### ISSUE TITLE
After commit 5ff44b Spacemacs shows light theme before selected theme is loaded

### ISSUE THREAD

**Issue by niontrix** [syl20bnr/spacemacs#16683]
Hi folks!

I updated Spacemacs today and am using `doom-one` as my default theme. 
Since the recent commit [5ff44b](https://github.com/syl20bnr/spacemacs/commit/5ff44b284f8b251d45e7c90ddc020c3a23f6a47b) Spacemacs now starts up with the light theme until the package load is done and only after that switches to the configured theme.
The behavior is the same for all themes except when using `spacemacs-dark`.
I know it is a minor issue, but it is a regression from the previous state.
How can we fix this?

KR, niontrix

**Comment by sunlin7** [comment]
Hi @niontrix 
The commit `5ff44b` fixed 3 issues as I list in the MR #16650, and these issues affect Spacemacs a lot. 

For loading theme early, we maybe need research a new way to do that.

**Comment by sunlin7** [comment]
@niontrix  Could you past your theme configuration, then I  can reproduce the issue on my local? Thanks

**Comment by niontrix** [comment]
Hi @sunlin7!
Thanks for getting back to me so fast :smile: 
My theme configuration is:
```
   dotspacemacs-themes '(doom-one
                         monokai-pro
                         spacemacs-dark
                         spacemacs-light)
```

**Comment by sunlin7** [comment]
Will try on my local and update later.

**Comment by niontrix** [comment]
I read you comments on your PR. You wrote that the default fallback theme should be `spacemacs-dark`, right?
But now it looks like this when I start up Emacs:

![image](https://github.com/user-attachments/assets/599e4c77-b9fd-4e21-b942-7ad959c58e43)

**Comment by niontrix** [comment]
Also it seems, that now the light theme is applied as default on the mode line, too, which changes the colors of the evil state indicators.

![image](https://github.com/user-attachments/assets/516972a6-da87-4f44-8aec-f746043e5702)

**Comment by sunlin7** [comment]
The [5ff44b](https://github.com/syl20bnr/spacemacs/commit/5ff44b284f8b251d45e7c90ddc020c3a23f6a47b) will apply the fallback theme at last if failed to load the desired theme, while previous behavior will apply the fallback theme after first failed on theme and apply the fallback theme again after second failed on theme.

I'm going to create a MR to try best to compatible with previous behavior.

**Comment by niontrix** [comment]
But why would the current theme (which is `doom-one` in my case) not be loaded, after the package has been installed?
The white background is always the first thing to be seen until the packages are loaded. If I understood you right, then my preferred theme should be loaded first and only if it can't be loaded should the fallback theme be applied.
But as I am writing this, I think that is the problem already. The custom theme is not loaded at that point so the fallback theme is applied. But furthermore, like I asked before, why is the background white, which seem to imply that `spacemacs-light` is loaded, but as I understood it, the fallback should be `spacemacs-dark`, right?

**Comment by sunlin7** [comment]
Hi @niontrix Please review the MR #16685, should be able to act like previous behavior.
And you're right for the fallback theme should be `spacemacs-dark`, but actually the light theme you saw on the startup is the `default` theme. 

And you can image that, if a user prefer a light theme in a package, who will see a theme flashing.

The PR give a change to customer to set a light theme as the fallback theme or set a nil.
