### ISSUE TITLE
`C-k` and `C-j` is not usable for holy-mode in Python REPL

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1668]
Since `comint-previous-input` is bound to `C-k` and `comint-next-input` is bound to `C-j`.

**Comment by robbyoconnor** [comment]
Why not fix it?

**Comment by tuhdo** [comment]
So maybe I won't forget it and may fix it later or someone may fix it in the meantime. This is related to evilified that I don't know as much as @syl20bnr does.

**Comment by robbyoconnor** [comment]
:+1:
