### ISSUE TITLE
undo-tree not working anymore :(

### ISSUE THREAD

**Issue by dfridovi** [syl20bnr/spacemacs#16699]
#### Description :octocat:
I cannot seem to use `undo-tree` anymore. I don't know when it stopped working, but at some point in the last month or two I pulled latest develop and *poof* no more `undo-tree`. I have it in my "additional packages" list like usual, but it never installs. When I install it manually, then the next time I load emacs it is detected as an orphan and deleted.

#### Reproduction guide :beetle:
- Start Emacs
- open `~/.spacemacs` and add `undo-tree` to the list of additional packages beneath where you add layers
- save and close Emacs
- open emacs again
- type stuff, then C-u

*Observed behaviour:* :eyes: :broken_heart:
After the above, it won't be using `undo-tree` and will just do a normal Emacs undo.

*Expected behaviour:* :heart: :smile:
It should be showing me the undo-tree you get here https://elpa.gnu.org/packages/undo-tree.html

#### System Info :computer:
- OS: darwin
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. c3269f6a3)
- Graphic display: nil
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(javascript python
            (lsp :variables lsp-enable-folding t)
            pandoc ruby rust html csv cscope semantic
            (c-c++ :variables c-c++-enable-google-style t c-c++-enable-google-newline t c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t clang-format-style "{BasedOnStyle: Google,\n                                 Standard: Cpp11,\n                                 DerivePointerAlignment: false,\n                                 PointerAlignment: Left,\n                                 IncludeBlocks: Preserve}")
            (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
            emacs-lisp markdown yaml octave
            (latex :variables latex-enable-auto-fill t latex-enable-folding t)
            bibtex
            (julia :variables julia-backend 'lsp)
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            syntax-checking vagrant treemacs
            (helm :variables helm-use-fuzzy 'source))
```
- System configuration features: ACL GMP GNUTLS JSON LIBXML2 MODULES NOTIFY KQUEUE PDUMPER SQLITE3 THREADS TREE_SITTER ZLIB

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by sunlin7** [comment]
`undo-tree` is  phased out in https://github.com/syl20bnr/spacemacs/commit/c8da713c6986e2c9236cb3d520a75beb0b64fb9d .

**Comment by dfridovi** [comment]
Thanks! You just made my day. 

For anyone else with this issue: [vundu](https://github.com/casouri/vundo) seems to be the replacement package for `undo-tree` for all intents and purposes.
