### ISSUE TITLE
New feature to specify theme package fails when not already installed

### ISSUE THREAD

**Issue by downward-funarg** [syl20bnr/spacemacs#16731]
#16691 allows one to specify the theme location like this: 

`(modus-operandi-tinted :package modus-themes)`

This fails if the package isn't yet installed, e.g. if it is specified in `dotspacemacs-additional-packages` on a fresh install or package update, with the error

`Wrong type argument: symbolp, (modus-operandi-tinted :package modus-themes)`

**Comment by sunlin7** [comment]
I'm trying to reproduce it...

**Comment by sunlin7** [comment]
Solution pushed, please help verify it. Thanks

**Comment by downward-funarg** [comment]
Works for me, thanks!
