### ISSUE TITLE
Ruby layout: inf-ruby-console-run: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by kirill-snap** [syl20bnr/spacemacs#16743]
#### Description :octocat:
I just updated packages in Spacemacs. And inf-ruby was updated since ruby layout using it https://github.com/syl20bnr/spacemacs/blob/e7c5b0d187f1731dad017ff62cb8bfbdc59139b8/layers/%2Blang/ruby/funcs.el#L116

#### Reproduction guide :beetle:
I have this error when I try to run ruby console with robe-start:
`inf-ruby-console-run: Wrong type argument: stringp, nil`

But it works fine when I revert to the previous version of the package

*Observed behaviour:* :eyes: :broken_heart:
I have this error when I try to run ruby console with robe-start:
`inf-ruby-console-run: Wrong type argument: stringp, nil`

*Expected behaviour:* :heart: :smile:
robe-start should work

#### System Info :computer:
- OS: darwin
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. e7c5b0d18)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(protobuf typescript sql
          (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
          better-defaults coffeescript
          (ruby :variables ruby-version-manager 'rvm ruby-test-runner 'rspec)
          react github-copilot themes-megapack terraform ruby-on-rails emacs-lisp docker git helm markdown
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          spell-checking syntax-checking
          (version-control :variables version-control-diff-tool 'diff-hl)
          yaml
          (json :variables json-fmt-tool 'prettier)
          html
          (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
          javascript osx csv treemacs)
```
- System configuration features: ACL GIF GLIB GMP GNUTLS JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER XIM ZLIB

**Comment by bcc32** [comment]
I think the Spacemacs code still matches how that package recommends to be configured:

```
(add-hook 'compilation-filter-hook 'inf-ruby-auto-enter)
```

(well, Spacemacs adds it buffer-locally, but that shouldn't be an issue).

I have commented on your issue on the package's repo, closing this one.

**Comment by kirill-snap** [comment]
yes, it was fixed. Thank you!
https://github.com/nonsequitur/inf-ruby/commit/dad78a13f162200a0f6720fe40e0726525424bba
