### ISSUE TITLE
Troubles regarding ocaml layer

### ISSUE THREAD

**Issue by ChingfanTsou** [syl20bnr/spacemacs#1674]
Since ocaml layer's `merlin` package heavily rely on `fuzzy` and `auto-complete`, it is strange to find that the `package.el` in ocaml layer actually doesn't include `fuzzy` neither turn on `auto-complete-mode`.

I found `auto-completion` layer has perfectly instructed how to enable `company-mode` for a specific mode, but I can't figure out how to do the same with `auto-complete`. Can anybody give me a hint?

I am expecting to use spacemacs for ocaml code editing. Any help would be appreciated.

Thanks!

**Comment by syl20bnr** [comment]
Try the `develop` branch, there is a lot of improvements for ocaml in there.

**Comment by ChingfanTsou** [comment]
Thank you for your help.

Actually I tried out the `develop` branch but still got some problems:

1. In the function `ocaml/init-merlin`, `merlin-mode` has been hooked to `tuareg-mode-hook`, `(add-hook 'tuareg-mode-hook 'merlin-mode)`, but when editing ocaml code, ie, when `tuareg-mode` is on, `merlin-mode` isn't enabled.
2. this layer config in the `develop` branch disable `auto-complete` and use company backend instead. However, `merlin` heavily rely on `auto-complete` and `fuzzy`, `company` doesn't make the best completion. Is there a way to actually turn them on instead using `company` like right now?

**Comment by redline6561** [comment]
Paging @edwintorok?

**Comment by edwintorok** [comment]
@ChingfanTsou do you have opam and merlin installed and did you run `eval $(opam config -env)`? I see `merlin (default) utop` in my status bar, and the merlin commands definitely work for me.

I'll take a look at using `auto-complete` instead of `company`, I just went with company because that is what spacemacs's autocompletion/README.md had an example for.

**Comment by edwintorok** [comment]
@ChingfanTsou Please try my `ocaml-auto-complete` branch: https://github.com/edwintorok/spacemacs/tree/ocaml-auto-complete

**Comment by ChingfanTsou** [comment]
@edwintorok Thanks for the update.

Yes, I have `opam` and `merlin` installed and worked pretty well, and my own emacs config about `tuareg` and `merlin` worked just fine as well.
After trying out your branch, I found that `merlin` was automatically enabled and `auto-complete` worked as expected.

It seemed strange, I guess disabling `auto-complete` in the `develop` branch has something to do with it?

**Comment by edwintorok** [comment]
Can you also try [this branch](https://github.com/edwintorok/spacemacs/tree/ocaml-tweaks)? It doesn't have auto-complete enabled, but fixes some errors with flycheck initialization.

**Comment by ChingfanTsou** [comment]
@edwintorok `ocaml-tweaks` branch works fine. Thanks for the excellent work!

It looks strange though. `auto-complete` was commented out within `ocaml-packages`, `merlin-use-auto-complete-mode` was still set to `t`, and `spacemacs|enable-auto-complete` was still invoked.

It won't cause too much troubles, although it made both `company` and `auto-complete` enabled.

BTW, how did you manage to make merlin work with company? Just curious.

**Comment by edwintorok** [comment]
On 05/24/2015 06:13 AM, Chingfan Tsao wrote:
> @edwintorok <https://github.com/edwintorok> |ocaml-tweaks| branch works fine. Thanks for the excellent work!
> 
> It looks strange though. |auto-complete| was commented out within |ocaml-packages|, |merlin-use-auto-complete-mode| was still set to |t|, and |spacemacs|enable-auto-complete| was still invoked.
> 
> It won't cause too much troubles, although it made both |company| and |auto-complete| enabled.

I've commented out the auto-complete initialization here (i.e. it uses company):
https://github.com/edwintorok/spacemacs/tree/ocaml-tweaks

And I've commented out the company mode initialization here (i.e. it uses auto-complete):
https://github.com/edwintorok/spacemacs/tree/ocaml-auto-complete

Please try these two branches and let me know how they work for you.

Apparently Merlin prefers company-mode slightly over auto-complete: https://github.com/the-lambda-church/merlin/issues/55#issuecomment-105018478

> 
> BTW, how did you manage to make merlin work with company? Just curious.

Merlin supports both auto-complete and company, I only followed the spacemacs documentation: https://github.com/syl20bnr/spacemacs/tree/develop/contrib/auto-completion#add-auto-completion-in-a-layer, and Merlin's documentation: https://github.com/the-lambda-church/merlin/wiki/emacs-from-scratch#company-mode on how to enable it.

BTW which version of Merlin do you have? I'm testing my layer with Merlin 2.2.

**Comment by ChingfanTsou** [comment]
@edwintorok both `ocaml-auto-complete` and `ocaml-tweaks` work fine. I'm currently use `merlin 2.1.2`. It looks like `merlin` works well with `company`.

Thanks for the excellent work!

**Comment by syl20bnr** [comment]
> It looks like merlin works well with company.

@ChingfanTsou so what do we do here ? If company if fine then we prefer to use company is spacemacs, but if there is a big missing feature in the company backend then we might consider auto-complete. What's your current thought about auto-completion for ocaml ?

**Comment by ChingfanTsou** [comment]
@syl20bnr Actually according to [this](https://github.com/the-lambda-church/merlin/issues/55#issuecomment-105018478) given by @edwintorok , `company` is definitely fine.

**Comment by TheBB** [comment]
I'm assuming I can close this, then. I'm a bit confused whether there is actually a problem that needs to be solved. If there is, please let us know.
