### ISSUE TITLE
Guide-key breaks truncate lines

### ISSUE THREAD

**Issue by yangj1e** [syl20bnr/spacemacs#1680]
When the cursor is in the visual line, press some key (e.g. `SPC`)  to trigger guide-key frame, then the lines become untruncated. Press navigation keys (e.g. `j`, `k`), the lines resume truncated.

**Comment by TheBB** [comment]
Guide-key has been replaced in develop, and I can't reproduce this there. Tentatively labeling as fixed in develop.
