### ISSUE TITLE
Just wanted to give some love

### ISSUE THREAD

**Issue by shaiguitar** [syl20bnr/spacemacs#1688]
Really having a great time with this. :tada: :balloon: :smiley: Appreciate the work and effort you put into this!

**Comment by stormpat** [comment]
:+1:

**Comment by hijarian** [comment]
:+1:

**Comment by robbyoconnor** [comment]
:+1: :100:

**Comment by syl20bnr** [comment]
💛💙💜💚❤️

**Comment by TheBB** [comment]
We're all loved out. Please open more issues for more love if necessary. :-)

**Comment by robbyoconnor** [comment]
I love that @syl20bnr
