### ISSUE TITLE
Making Anaconda aware of virtualenvs

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#170]
I used pyvenv to tell emacs I'm working in a certain virtual env... but the thing is that then using Anaconda's go-to (<kbd> < SPC m g</kbd> ) I got to the definitions of my functions inside the buffer and at most in between buffers inside of my Project, but I want more, want to go to the source code at times :) so it should be noted in the documentation the the only thing you need to use for this feature to work is to add this line to you config files
``` elisp
  (setq python-shell-virtualenv-path "~/.virtualenvs")
```
Or replace `~/.virtualenvs` with whatever location you chose to store your venv at. With this using <kbd> SPC m g</kbd> will take you to the definition of say `django.models.Document` inside  of your working virtualenv.

I'm using virtualenvwrapper.sh and I haven't really used pyvenv.py utility, so I don't know what is your python setup but for me this feature is a must. 

Somehow [docummentation of pyvenv-mode](https://github.com/proofit404/pyenv-mode) says pyvenv sets this automatically but it doesn't work for me.

**Comment by syl20bnr** [comment]
@danielwuz @CestDiego Any news on this ?

**Comment by danielwuz** [comment]
I think we can close this discussion now.

**Comment by syl20bnr** [comment]
@CestDiego @danielwuz last thing, do we need to put something in the layer README?
