### ISSUE TITLE
Prefix layer category directories

### ISSUE THREAD

**Issue by trishume** [syl20bnr/spacemacs#1701]
Currently when browsing looking for layers in Github or otherwise it is nearly impossible to tell which directories are layers and which are categories. For example recently I thought my `ycmd` layer had been removed from Spacemacs but I eventually found it in the `tools` folder. This really hurts the discoverability of layers. 

I propose that the category folders be prefixed with something that makes it clear they contain other layers. 

I suggest that this should be something early in asii but still a valid filename character so that they sort first. If the prefix is a symbol I suggest `!` but again for discoverability perhaps it should be readable like `cat-`

**Comment by trishume** [comment]
The tricky thing for this is that it might cause a bunch of merge conflicts in open PRs, but maybe git is smart enough about renaming, I don't know.

I still think we should do it anyways, its super important that people can easily browse spacemacs layers.

**Comment by tuhdo** [comment]
Do you use `SPC f e h` to quickly jump to a layer? I never have to navigate manually.

**Comment by CestDiego** [comment]
^this, I think `SPC f e h` should be MORE encouraged as a discoverability method.

**Comment by tuhdo** [comment]
To navigate layers, users are expected to use `SPC f e h` and in the future, it will have an action to automatically install layers, so users don't have to manually change their `.spacemacs`, similar to how `customize-*` functions do.

**Comment by CestDiego** [comment]
yay. BTW is there a way to change the default action from `SPC f e h` I'm reaaally hating the gh-mode that renders poorly (no images) the README.md of each page...If it was org mode it could show images but most of the time when I want to navigate to a layer I want to modify it's contents, not read it's doc...also if I really want to read the docs I read them in github. Maybe a better way is to redirect people to the github page?

**Comment by tuhdo** [comment]
But open in plain markdown does not have image either, as markdown is not installed by default. So, it looks even more ugly for first time users. I guess we can leave it for now and start converting everything to `org-mode` in the next release after the current `develop` becomes `master`. That's the definitive solution.

For now, you can press `C-u` before pressing `RET` to open the doc.

**Comment by tuhdo** [comment]
@trishume if you use `SPC f e h` from the first place, you can just type in `ycmd`, switch to the next source with `C-o` and jump to any package in the layer instantly without doing anything further.

**Comment by trishume** [comment]
Ok but that doesn't solve the problem that it is hard to navigate in Github and file browsers. I still think they should be prefixed so that workflow works much better, it doesn't harm any other workflows.

Even if you use `SPC f e h` if you are creating a layer and placing the folder in the source tree you have to decide if you want to put it into a category folder, except you can't tell which folders are categories without investigating them all.

**Comment by tuhdo** [comment]
When I was new to Spacemacs, it was difficult to find the documentation for a layer because it is buried inside the `contrib` directory. Luckily I did spend time to look at it but I don't think any new user would spend time to understand how Spacemacs is structured and they shouldn't have to. For that reason, we have `SPC f e h` and it is also the fastest way to check the existence of a layer. I think any user would want to use that instead of manually navigating the `contrib` directory with a file browser or with Github.

That's why viewing document inside Emacs is higher priority, and we are planning it: https://github.com/syl20bnr/spacemacs/issues/1568

**Comment by trishume** [comment]
You're arguing that there are other (perhaps better) ways to browse layers and I totally agree with you.

That doesn't mean we shouldn't make life better for contributors and other people browsing the source code by prefixing categories.

I just created a PR, lets move discussion there.
