### ISSUE TITLE
Reset indentation in haskell after an empty line

### ISSUE THREAD

**Issue by meditans** [syl20bnr/spacemacs#1704]
Hi, when hitting enter in haskell-mode, the cursor is usually in the middle of the line (in the most consistent place indentation-wise).

Before using spacemacs, however, I remember setting an option which resets the indentation when the user skips a line (in this way it's possible to start a new function without hitting `S-Tab`). However I don't find that option again.

Do you have the same problem?

**Comment by d12frosted** [comment]
No, I don't have such problem. Does it still occur for you?

**Comment by d12frosted** [comment]
@meditans could you please post the result of `spacemacs/describe-system-info`? Are you using `shm`?

**Comment by TheBB** [comment]
This seems to have the desired effect for me.

```lisp
(defun bb/stuff ()
  (when (and (< 1 (line-number-at-pos))
             (save-excursion
               (forward-line -1)
               (string= "" (s-trim (buffer-substring (line-beginning-position) (line-end-position))))))
    (delete-region (line-beginning-position) (point))))

(advice-add 'haskell-indentation-newline-and-indent
            :after 'bb/stuff)
```

Just dumping that here so I won't forget it.

**Comment by d12frosted** [comment]
Ok, looks like it was me who had some funky configs - I am able to reproduce it as well. So will work on solution.

**Comment by d12frosted** [comment]
Updated documentation in #3544.
