### ISSUE TITLE
`SPC p v` says `command-execute: Wrong type argument: commandp, helm-projectile-vc`

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#1706]
I'm on the latest `develop` branch as of 0cb6acb

**Comment by tuhdo** [comment]
The key binding should be changed to `projectile-vc`. `helm-projectile-vc` is a function to be used by `helm-projectile-switch-project` command. It's an action. This key binding was made long ago and remains unnoticed.

**Comment by swaroopch** [comment]
@tuhdo I've created a PR for the same - https://github.com/syl20bnr/spacemacs/pull/1709
