### ISSUE TITLE
C-p and C-n not passed through to Ansi-term in evil insert mode

### ISSUE THREAD

**Issue by herbertjones** [syl20bnr/spacemacs#1707]
When in ansi-term, pressing ```C-p``` results in evil expansion, or hippie expansion if the auto-completion layer is enabled.  If in holy mode, ```C-p``` and ```C-n``` will correctly be passed through, so that, for example if running bash, previous commands can be scrolled through.  However in evil mode, even evil insert mode, these keypresses are instead mapped to evil or hippie expand so that program running in the terminal never receives them.

Workarounds include:
- Pressing ```C-z``` to disable evil mode in the buffer.
- Pressing the up or down arrows, if the program in the terminal uses these as aliases of ```C-p``` and ```C-n```.
- Enabling holy mode.

**Comment by tuhdo** [comment]
The problem is because `evil-insert-state` is active in `ansi-term`, not the default term key mappings. We should solve this by enable `evil-emacs-state` in `term-mode` instead of `evil-insert-state`. That way we could avoid potential clashings.
