### ISSUE TITLE
expand-region no longer working

### ISSUE THREAD

**Issue by 3marcusw** [syl20bnr/spacemacs#1711]
Previously, `SPC v` activated expand-region, however when I try to use expand-region i get the following error: 
`er--expand-region-1: Invalid function: save-mark-and-excursion`

**Comment by hiddenlotus** [comment]
I've found the same question when I `expand-region'.

**Comment by cheunghy** [comment]
Same problem

**Comment by bmag** [comment]
Should be fixed upstream, see https://github.com/magnars/expand-region.el/issues/160
Try updating your packages (specifically expand-region). Does it fix your problem?

**Comment by 3marcusw** [comment]
just updated packages, it appears to be fixed

**Comment by cheunghy** [comment]
Still not fixed after upgrading
