### ISSUE TITLE
Compile error after install

### ISSUE THREAD

**Issue by lvicentesanchez** [syl20bnr/spacemacs#1715]
I'm getting this error:

```
Compiling file /home/luisvicente/.emacs.d/elpa/helm-projectile-20150513.1448/helm-projectile.el at Mon May 25 14:25:23 2015
helm-projectile.el:43:1:Error: Required feature `projectile' was not provided
```

I don't know if that's a real issue or not.

**Comment by ddwo** [comment]
I'm getting this as well on emacs 24.5.1, and the "projectile.el" file is empty in the package directory.

This happens with the latest master and develop branches

**Comment by TheBB** [comment]
Gut instinct is that this is a problem with connection to MELPA. Is it still happening?

**Comment by TheBB** [comment]
Closing due to no response. Please reopen or re-report if it's still a problem.
