### ISSUE TITLE
Spc - f - F stuck

### ISSUE THREAD

**Issue by lvicentesanchez** [syl20bnr/spacemacs#1716]
Just after installing spacemacs, Spc - f - F works, but after restarting emacs the combination Spc - f - F makes the cursor show a never ending spinning wheel until it eventually works (> 1min)

I can see the following message at the bottom:

`ad-handle-definition: 'find-function-search-for-symbol' got redefined`

**Comment by moesasji** [comment]
I see the same message, but Space-f-F works fine for me (on . This probably has more to do with the fact that somehow your helm isn't installed properly as you report in #1715. 

Is this on master or are you using develop? Did you try a clean reinstall of spacemacs?

**Comment by robbyoconnor** [comment]
You should try using develop -- typically most bugs are fixed there before they're fixed in master..but you're living on the edge...which means bugs are fixed but also there may be more bugs..

**Comment by lvicentesanchez** [comment]
I tried with a clean installation, I think I will try the develop branch.

2015-05-25 17:07 GMT+01:00 robbyoconnor <notifications@github.com>:

**Comment by lvicentesanchez** [comment]
I have tried with a clean spacemacs installation and as soon as I add haskell and scala to:

```
   dotspacemacs-configuration-layers
   '(
     auto-completion
     better-defaults
     emacs-lisp
     markdown
     org
     shell
     syntax-checking
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     ;; (git :variables
     ;;      git-gutter-use-fringe t)
     )
```
SPC f F or (SPC f f in develop branch) stop working as they should.

**Comment by lvicentesanchez** [comment]
How to reproduce the issue under Ubuntu 15.04 with emacs 24.5 (compiled from the gnu repository).

Checkout spacemacs using:

`git clone --recursive http://github.com/syl20bnr/spacemacs ~/.emacs.d`

Start emacs, wait until all packages are installed. You would get this error:

```
Compiling file /home/luisvicente/.emacs.d/elpa/helm-projectile-20150513.1448/helm-projectile.el at Mon May 25 20:47:58 2015
helm-projectile.el:43:1:Error: Required feature `projectile' was not provided
```

Stop emacs. Restart emacs. SPC f F would not work properly.

**Comment by lvicentesanchez** [comment]
so... it seems to be an issue with my emacs 24.5; I have just installed the version available in Ubuntu repository (24.4) and everything works just fine.

**Comment by robbyoconnor** [comment]
Yeah same issue...I'm gonna downgrade

**Comment by syl20bnr** [comment]
Closing this old issue, if it is still happening feel free to re-open it.
