### ISSUE TITLE
haskell: Modules loaded differently than emacs/haskell-mode

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#1725]
After navigating to a module source file in a cabal project and using `haskell-process-load-or-reload` via `SPC m s b` for some reason my libraries unexported functions can't be accessed. In the emacs/haskell-mode configuration I have that seems to be the same I can type unexported functions into the repl if I just loaded that file.

**Comment by codygman** [comment]
This was in develop. I switched back to master and everything worked as expected.

**Comment by d12frosted** [comment]
@codygman is it still happening?
