### ISSUE TITLE
fill-column-indicator mode strange cursor jumping

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#1726]
When turned on I'm getting strange jumping of the cursor.

It appears at the end of the line a way off, then when I type it jumps back into place and types the letter, then goes back to the end of the line.

Have this in haskell, not sure if it's related to the standard indent or hindent ?

Thanks

**Comment by andyque** [comment]
@fatlazycat  I also met this issue sometimes but not in haskell, I'm in c++-mode and python-mode, I have no idea why this happening. I'm not sure whether it is related to fill-column-indicator or not.

But it is weird when the cursor jumping.

**Comment by syl20bnr** [comment]
What emacs build are you using ?

**Comment by fatlazycat** [comment]
GNU Emacs 24.5.3 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) from 

then emacs-mac from cask within homebrew emacs-24.5-z-mac-5.7

**Comment by fatlazycat** [comment]
Hmm, thought this was the same as railwaycat/emacsmacport. Let me put it back.

**Comment by fatlazycat** [comment]
ok now have GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, Carbon Version 157 AppKit 1347.57) via railwaycat and still get the same issue

**Comment by Tritlo** [comment]
I have this as well. Happens especially in web-mode in html, and does not happen when the fci is turned off.

**Comment by syl20bnr** [comment]
I have weird issue with `fci` as well. Have to investigate if it is an issue with spacemacs or not.

**Comment by d12frosted** [comment]
Is this still valid?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.

**Comment by fatlazycat** [comment]
Sorry completely forgot to reply. Haven't seen this for a long time.
