### ISSUE TITLE
exiting insert mode in iedit behaves differently than evil

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#1730]
In normal evil pressing `i` and `Esc` repeatedly will move the cursor backwards. This is not the case in `iedit` which leads to problems with macros.

Maybe this is an issue for iedit upstream?

**Comment by syl20bnr** [comment]
That's interesting, yes it's probably an issue upstream where `evil-iedit-insert-state` is defined or maybe there is some conditional stuff about `insert state` in the Evil package .
