### ISSUE TITLE
Stacking highlights

### ISSUE THREAD

**Issue by h3dkandi** [syl20bnr/spacemacs#1732]
All these seem not to be working - [doc link](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#stacking-highlights). When I use `/` to search then next and previous have some highlights to work with. However they make you enter visual mode on the first next or previous execution. Don't know if that is default behavior. At least one more person in the spacemacs chat had the same problem.

**Comment by syl20bnr** [comment]
Oh yeah ! I have to contribute upstream to make it work in Spacemacs. Thank you for mentioning it.

**Comment by StreakyCobra** [comment]
@h3dkandi Do you still have this problem? `/`, `n` and `N` are working correctly for me, both on `master` and `develop`. If yes, can you give some steps on how to reproduce? If not, this issue can probably be closed :relaxed:

**Comment by TheBB** [comment]
@StreakyCobra We disabled the `hl-anything` package to work around this bug. It's still documented as working and has been for a while.

**Comment by Compro-Prasad** [comment]
@sdwolfz This can be closed.
