### ISSUE TITLE
[discussion] Addition to documentary for new users - difference between spacemacs and emacs

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1733]
@tuhdo 
@syl20bnr 

I know that there's a [for whom](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#who-can-benefit-from-this-) section in the docs.

The [philosophy](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#philosophy) section doesn't appear to link anywhere. 

For new users to Spacemacs it probably won't be obvious what aspects are general
Emacs and what are specific to Spacemacs. As a result they may go to Emacs
related IRC channels and pollute the stream a bit with questions that relate to
spacemacs and would be better placed on the Gitter channel or within an Issue
thread.

By having a concise introduction to this concept and some kind of suggested
"incubation" period for new users where they stay within Spacemacs help channels
it might remove these annoyances for new users, help them receive help quicker and 
familiarise themselves with where the line between spacemacs and emacs is. 

Perhaps this could be added into the docs as either a new section or within the
for whom (though it doesn't seem to quite fit in there). This could then be
linked to new users as a starting point.

**Comment by syl20bnr** [comment]
> pollute the stream

I'm not sure I get the idea here, redirecting people to the good channel should not be a problem. Users on #emacs (I don't go there unfortunately) can do it or the bot could provide useful info on spacemacs.

Since the gitter chat is mentioned at several places in the documentation and the badge should be obvious on the front-page, I don't see this as a problem. 

We have to fix the link and maybe update the mentioned sections though.

**Comment by geo7** [comment]
> Users on #emacs (I don't go there unfortunately) can do it or the bot could
> provide useful info on spacemacs.

They do, and there is a bot to do it (though it needs prompting), i just think
they're getting bored of doing it :)

> Since the gitter chat is mentioned at several places in the documentation and
> the badge should be obvious on the front-page, I don't see this as a problem.


This is just re something that I had read and thought that perhaps there could
be some kind of obvious starting point for new users with regards to realising
the difference between spacemacs and emacs.

The Gitter is a suitable place to start though I agree.

**Comment by syl20bnr** [comment]
I would prefer that Spacemacs does not bother the users of #emacs but I don't know what I can do about it. Same thing go for reddit etc... Spacemacs is just Emacs so it is hard to tell people to not ask about it on the legacy Emacs channels. Maybe we should mention this explicitly in the README, the fact that #emacs is not the best place to ask questions about Spacemacs.

**Comment by geo7** [comment]
I don't think that there's a particularly large period before one realises that there are of course large differences between Spacemacs and Emacs, though something like eLisp could (generally) be asked anywhere. 

I'm not sure what can be done about it either, other than having it mentioned explicitly in the docs somewhere as a starting point or something along those lines.
