### ISSUE TITLE
[documentation] Tutorial / walk through of `.vimrc` to `.spacemacs`

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1735]
There are often questions about key bindings and such when people are
transitioning from VIm to Spacemacs. Having a solid walk-through of implementing
basic `.vimrc` functionality within `.spacemacs` might make the transition easier
and explain terms in a familiar way to new comers (from VIm). 

Examples of `.vimrc` files are not hard to find, though
[here's mine](http://vpaste.net/GB4sQ) for the use of this post. This isn't a
very complicated `vimrc` file, and there aren't any functions either (which
could be a useful area perhaps).

However in this `vimrc` there are somethings that could be covered and "*walked
through*" for new comers. Talking about Vundle and its similarities to layers, how to
map keys in a manner similar to 

```text
" Make L go to the start of the line
nnoremap L $
```

and other items could be covered.

Of course, anything covered already in the documentation should be referenced
rather than duplicated, I think this might provide a readable introduction for
VIm users though.

**Comment by jupl** [comment]
syl20bnr/spacemacs#1565

**Comment by TheBB** [comment]
I think VIMUSERS.org addresses this. Feel free to PR specific content there.
