### ISSUE TITLE
Disabling leader-key temporarily 

### ISSUE THREAD

**Issue by usharf** [syl20bnr/spacemacs#1737]
I was looking at `org-present` support in the `org` layer to see if it was possible to use the `SPC` key to advance slides, but I see that next/prev is handled with h/l keys. Is it possible to disable evil-leader for the duration of a presentation, or in other modes in which it might be needed, until something like `q` was pressed to quit and go back to normal...?

**Comment by syl20bnr** [comment]
I see why you want this. Try this in your `dotspacemacs/config`:

```elisp
(evilify nil org-present-mode-keymap "<SPC>" 'org-present-next)
```

**Comment by usharf** [comment]
Great. Thanks!

Is there also away to disable leader activation while waiting on a prompt ie with read-input-sequence, where I'd like SPC to be picked up by the reader loop...?
