### ISSUE TITLE
status bar  can not display correctly, with messy code, when using an ssh cli like putty or xshell

### ISSUE THREAD

**Issue by liugangnhm** [syl20bnr/spacemacs#1742]
status bar  can not display correctly, with messy code, when using an ssh cli like putty or xshell on windows. when i use an  ssh client on ubuntu, i works fine.so is there a way to fixing this??

**Comment by liugangnhm** [comment]
http://mschulte.nl/posts/using-powerline-in-PuTTY.html fixed this.:)

**Comment by syl20bnr** [comment]
Thank for posting the solution, I will add it to the FAQ.

**Comment by d12frosted** [comment]
[This](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#powerline-font-installation-for-terminal-mode-users) is a good place for this.
