### ISSUE TITLE
Modeline intermittently breaks when syntax checking layer is disabled

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#1743]
I finally found out what's causing this problem. In `spacemacs/mode-line-prepare-left` the local binding [`flycheckp`](https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L2248-2250) can be true even if the syntax checking layer is disabled. (How that happens is not entirely clear to me.) The effect is that [these lines](https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L2294-2301) may take effect, even if [`spacemacs|custom-flycheck-lighter`](https://github.com/syl20bnr/spacemacs/blob/develop/contrib/syntax-checking/packages.el#L68-75) is undefined.

I've seen this most often in LaTeX and C++. I have the `auctex` and `c-c++` layers enabled.

**Comment by syl20bnr** [comment]
Great finding, do you have a repro step or disabling the layer is enough ?

**Comment by TheBB** [comment]
I'll get back to you on that when it happens next.

**Comment by s3bs** [comment]
@TheBB I get this error too. My search revealed that `layers/+distribution/spacemacs/packages.el` is using the macro `spacemacs|custom-flycheck-lighter`. 
The way to reproduce it is, that one does not enable the syntax-checking layer, where that macro is defined, but still loads flycheck through other means. Therefore causing an error. The configuration of the powerline for flycheck should be done in the `syntax-checking` layer.

**Comment by TheBB** [comment]
It must be due to this, however, if you don't have the syntax-checking layer enabled, how do you have flycheck installed in the first place? Presumably it is pulled in as a dependency of another package in that case, but which?

**Comment by s3bs** [comment]
I was doing some coding on flycheck so i have it loading from a different directory via user-config. Also I'm new to spacemacs and didn't even know about the syntax-checking layer.
