### ISSUE TITLE
Some text manipulation commands broken (on dev)

### ISSUE THREAD

**Issue by stormpat** [syl20bnr/spacemacs#1745]
Moving lines up/down dont work with the commands, ```SPC x m j``` and ```SPC x m k```

**Comment by sooheon** [comment]
On dev these key bind have been moved to `spc x K` and `spc x J`, with micro-states. Can go ahead and close.

**Comment by tko** [comment]
Hmm, guide-key for `SPC x` doesn't mention either of the keys though they do work if you happen to know to press them. On the other hand guide-key mentions `SPX x m` but there's nothing there.

**Comment by tko** [comment]
Regarding guide-key it seem `spacemacs/init-move-text` and/or `spacemacs|define-micro-state` isn't working properly with multiple `:evil-key-leader` entries. That is
```elisp
:evil-key-leader "xJ" "xK"
```
hides *both* keys from the <kbd>SPC x</kbd> guide key menu. If you only give one or the other it gets documented similar to `[J] spacemacs/move-text-micro-state` which is somewhat suboptimal especially if it worked for both keys.

**Comment by CestDiego** [comment]
that is an issue from `spacemacs|define-micro-state`. Also regarding the javascript issue defining `SPC x m j` and `SPC x m k` it's due to these lines https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/javascript/packages.el#L168-L169

**Comment by CestDiego** [comment]
I would also like to point that moving regions with this command doesn't work with evil. If one does the marking with Emacs it works but if one selects stuff with evil it breaks: here is a gif
[![alt](http://i.imgur.com/zlzohdS.gif)](http://i.imgur.com/zlzohdS.gif)

**Comment by Immortalin** [comment]
@CestDiego how do you get the fancy symbols for elisp mode?

**Comment by CestDiego** [comment]
@Immortalin just put  ` (global-prettify-symbols-mode)` somewhere in `dotspacemacs/user-config`

**Comment by aaronjensen** [comment]
> I would also like to point that moving regions with this command doesn't work with evil. If one does the marking with Emacs it works but if one selects stuff with evil it breaks: here is a gif

Just found this one, it seems like there are two issues here. Should we split this out into two issues?

**Comment by aaronjensen** [comment]
I opened another issue for the move-text-down issue https://github.com/syl20bnr/spacemacs/issues/5365

**Comment by aaronjensen** [comment]
By the way, this original issue is fixed in develop (at least, maybe master) @StreakyCobra

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
