### ISSUE TITLE
No buffer-local variable completions for elixir with auto-complete?

### ISSUE THREAD

**Issue by koudelka** [syl20bnr/spacemacs#1748]
With `erlang-elixir` and `auto-completion` (with `company-mode`) layers enabled, library functions are completed correctly, but local buffer completions (functions, variables, etc) aren't.

If I manually enable `auto-complete-mode` in the buffer, I get local completions. But I'm guessing that's going to make company and auto-complete fight.

Opening an issue per @syl20bnr at https://gitter.im/syl20bnr/spacemacs?at=55660b594aa53f5626064e7e

**Comment by koudelka** [comment]
Likely related to https://github.com/tonini/alchemist.el/issues/66

**Comment by d12frosted** [comment]
Does it still happen to you? Looks like The upstream issue is fixed.

**Comment by koudelka** [comment]
fixed! :)
