### ISSUE TITLE
Deficient Windows install instructions.

### ISSUE THREAD

**Issue by h3dkandi** [syl20bnr/spacemacs#1754]
Not knowing anything about Emacs I decided to start my adventure directly with Spacemacs. I found the install instructions lacking. To get the search functionality in Spacemacs you have to have grep or some other unix tool. It is difficult for a beginner to find a way to make grep and other unix functions to run on windows. 

TL;DR: For Windows users it would be helpful if there were some instructions to set up the needed unix tools for better Spacemacs/Emacs experience.

**Comment by syl20bnr** [comment]
@h3dkandi I pushed a Windows section in the Emacs prerequisite of the README, see here: https://github.com/syl20bnr/spacemacs/tree/develop#windows
Feel free to improve it :-)
