### ISSUE TITLE
iPython (notebook) layer 

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1757]
Currently there isn't a layer for iPython, there is a repo here : 

~~https://github.com/tkf/emacs-ipython-notebook~~

The above is no longer maintained see : 

https://github.com/millejoh/emacs-ipython-notebook

That seems to offer the functionality, would be cool to have in Spacemacs :)

Example ([further examples](https://github.com/millejoh/emacs-ipython-notebook/wiki/Screenshots)) : 

![Image of notebook](https://raw.githubusercontent.com/wiki/millejoh/emacs-ipython-notebook/images/demo_plotnormal.PNG)

**Comment by tuhdo** [comment]
Actually, the above repo (the original) is not maintained anymore. This fork is actively maintained: https://github.com/millejoh/emacs-ipython-notebook

You can see a set of different screenshots in Solarized light: https://github.com/millejoh/emacs-ipython-notebook/wiki/Screenshots

**Comment by jgmize** [comment]
An ipython-notebook layer is availabe in [v0.103.0](https://github.com/syl20bnr/spacemacs/releases/tag/v0.103.0) and above-- see the [README](https://github.com/syl20bnr/spacemacs/blob/master/contrib/!lang/ipython-notebook/README.org) for more details and current status (WIP as of this writing).

**Comment by pedrovanzella** [comment]
Autocomplete doesn't seem to be working in this layer.
