### ISSUE TITLE
Move Julia into a new layer and enhance its REPL with ESS

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1758]
The feature of Julia REPL should be integrated for Julia: https://github.com/emacs-ess/ESS/wiki/Julia

**Comment by mjs2600** [comment]
:+1: I've tried both julia mode and the one included in ESS. And the one in ESS is **much** better.

**Comment by geo7** [comment]
is this still an issue? @robbyoconnor I know you use Ruby - is this still relevant ?

**Comment by StreakyCobra** [comment]
Does #3342 close this one?

**Comment by timofeytt** [comment]
How is this supposed to work? The R bindings don't work for Julia :/
https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/ess
