### ISSUE TITLE
Highlight glitch

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#1767]
It doesn't look like major mode-specific issue because it's reproducible on EnhRuby and Ruby modes.
Basically you need to type `{`, then Spacemacs will create `{}` for you and will place cursor inside curly braces. To reproduce you need to press `RET` while your cursor is within braces and then you'll notice that for some reason whole block(from opening `{` til closing `}` is highlighted:
![issue](http://i.imgur.com/grH48JO.png)

Even if you move you cursor or type something within block - highlighting won't go away:
![issue](http://i.imgur.com/x5ePegR.png)

Color theme is `monokai`.

**Comment by person808** [comment]
Its not a bug, its a feature! This comes from smartparens. I can look for the variable to disable it, but it should be on the smartparens wiki.

**Comment by Eilie** [comment]
@person808, Could you please tell me which variable should I use to disable it? Can't find it on wiki.

**Comment by Eilie** [comment]
@person808 Found it - `(setq sp-highlight-pair-overlay nil)`. Thank you!.
@syl20bnr We have ~300 open issues and ~400 closed ones, but some of these issues are labeled with various flavors of "fixed" label, why not just close those?

**Comment by syl20bnr** [comment]
@Elie It's possible to close them but not required, in all cases they will be closed when the next version is released.
