### ISSUE TITLE
Wrong display of popup buffer when that buffer is already selected

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#1768]
When I have a popup buffer open in a popup window, and that window is selected, and I perform on operation that should display that buffer again, the buffer is displayed in the wrong place.

I expect the buffer to remain in the popup window. Instead, the popup window is closed, and the buffer is displayed as if it is a regular buffer.

For example:
![spacemacs-wrong-popup](https://cloud.githubusercontent.com/assets/4334375/7881442/a9ac96a2-060b-11e5-9f67-e312a3b1c28f.gif)

Also, if I open a grep buffer (with `find-grep`), then a help buffer, the popup windows stack one underneath the other. Closing them with <kbd>C-g</kbd> works. Is it intended or a bug?

![spacemacs-stacked-popup-windows](https://cloud.githubusercontent.com/assets/4334375/7881540/c8f22288-060c-11e5-85e1-bc2000a008a4.gif)

Using develop branch on Lubuntu 14.04.

**Comment by tuhdo** [comment]
The first case seems like a `popwin` bug.

The stacking window is expected because otherwise your grep buffer would close immediately if point moves to other window, in which case it is not undesirable. And it's a feature that your temporary window is not immediately close without your permission. In the second case, you can just press `C-g` until all temporary windows close. And when you open a Helm command, the previous window is raised above Helm window because when Helm is entered, `popwin-mode` is temporary disabled until that Helm session finishes. Without disabling `popwin` in Helm, it would mess up Helm commands that open extra windows when executing persistent action, lie `helm-M-x` or `helm-descbinds` or `helm-apropos`.

**Comment by bmag** [comment]
So, no way around the first case?

Thanks for explaining the stacking :smiley:

**Comment by sooheon** [comment]
I think I may have a related issue:

Starting with one frame, 
1. `spc g s` to open magit status in split
2. `L l` to show magit log, replacing magit status
3. `enter` on any entry to show commit information in other split
4. `qqq` to quit out of magit entirely, and you are left with a split window, when you should go back to original single window state.

**Comment by tuhdo** [comment]
@sooheon That's the default behaviour of Emacs. Magit is not under the control of `popwin`, so that's why you are left with a split window.

**Comment by sooheon** [comment]
Strange then, because if I only go 1 level deep into magit (just `magit-status`, for example), q will take me back to the original window configuration. Do you mean this discrepancy is the intended behaviour?

**Comment by tuhdo** [comment]
Yes, with only `magit` installed in stock Emacs, it behaves that way. Probably we need to put the magit buffers under the control of `popwin`.

**Comment by sooheon** [comment]
I see. I wonder if things may be improved in the new magit.. that would save us having to wrangle it into popwin.

**Comment by StreakyCobra** [comment]
@bmag Can you check if there is any update on this issue :smiley: ?

**Comment by bmag** [comment]
The bug still exists. I don't encounter it anymore because I use the `window-purpose` layer.

**Comment by StreakyCobra** [comment]
Ok thanks :+1: Do you think it should be reported upstream to popwin?

**Comment by bmag** [comment]
This is definitely a popwin bug - the same thing happens to me also when using popwin with an empty emacs config. The only difference is that with powin and bare emacs, I end up with a vertical split instead of a horizontal split. I couldn't figure out what causes this difference.
I will report it upstream, but I don't know if I'll get any answer. There are quite a few issues there with no response.

**Comment by sooheon** [comment]
@bmag to be clear, you are using `window-purpose` the package but it's not officially a spacemacs layer yet, right? If it's fixed this problem for you, would you mind contributing your config as a PR?

**Comment by syl20bnr** [comment]
There is already a PR for it (very old), originally planned for 0.105 I moved it to 0.106.

**Comment by StreakyCobra** [comment]
@bmag If you can do it it's really nice of you. I just wanted to be sure if it was a Spacemacs issue or not.

**Comment by bmag** [comment]
@StreakyCobra Reported upstream: https://github.com/m2ym/popwin-el/issues/131 just now

**Comment by StreakyCobra** [comment]
@bmag Awesome :relaxed: Thanks

**Comment by Compro-Prasad** [comment]
I this is fixed. Or am I misunderstanding it?

**Comment by Compro-Prasad** [comment]
Upstream repository is not been actively maintained for a long time. We need to have it as an internal Spacemacs elisp file with the fixed changes as mentioned https://github.com/m2ym/popwin-el/issues/131 .

**Comment by bmag** [comment]
@Compro-Prasad this is fixed in Spacemacs, but still not fixed upstream. We fixed it by using `window-purpose` and a local package that implements popup buffers by extending `window-purpose` (see `spacemacs-purpose` layer). The configuration of popup buffers is still done through `popwin:special-display-config`, but other than that we mostly avoid popwin entirely. Hence, I'm closing the issue.
