### ISSUE TITLE
.jsx not set to Web-mode

### ISSUE THREAD

**Issue by Tritlo** [syl20bnr/spacemacs#1769]
.jsx files (used for react mainly), work nicely with special support in web-mode, and yet web-mode is not toggled on in .jsx files.

**Comment by tko** [comment]
At some point in the past I'd made a private layer for jsx which in essence contains
```emacs
(defun jsx/init-web-mode ()
  (use-package web-mode
    :defer t
    :mode
    (("\\.jsx\\'" . web-mode))
    :config
    (progn
      (defadvice web-mode-highlight-part (around tweak-jsx activate)
        (if (equal web-mode-content-type "jsx")
            (let ((web-mode-enable-part-face nil))
              ad-do-it)
          ad-do-it)))))

(defun jsx/init-flycheck ()
  (use-package flycheck
    :defer t
    :config
    (progn
      (flycheck-add-mode 'javascript-eslint 'web-mode))))
```
Don't really know how/if one should merge these into the existing layers; quickly checking javascript is using js2-mode instead of web-mode.
