### ISSUE TITLE
Creating bindings for certain modes and certain states

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1771]
It doesn't seem that theres anyway to have functionality like VIms `after` directory (or not an obvious one).

In vim, within `~/.vim/after/ftplugin/python.vim` one could enter commands
which would only be active for python files. 

```vim
" normal mode mapping
nnoremap gg dG
" insert mode mapping
inoremap j gg
" macros
let @s = "I'jfA'jfV:s: :', ':
,hlIsubprocess.call([jfA])jf"
```

Or whatever (probably something more sensible...)

Is there a way to get this behaviour from Evil / Spacemacs?

**Comment by syl20bnr** [comment]
This is called `major-mode` specific key bindings and they start with `SPC m` prefix or `,` which is a shortcut for it.

**Comment by syl20bnr** [comment]
For discoverability note that for now guide-key does not work with major-mode specific key bindings, you have to use `SPC ?` and enter `SPC\ m` to refine the search.
They should also be in the README file of the corresponding layer.

**Comment by geo7** [comment]
@syl20bnr can you be explicit or point me to the right docs for this please? 

As I'm reading that I can't map keys in the same way, I'm forced to use `,` or `SPC m` as a prefix. 

TBH, using `,` as a major mode leader isn't a nightmare, I'm just trying to work out how this actually works....

Could one define a normal mode mapping just for python mode that had `pp` mapped to `gg`, or something trivial like that as an example?

**Comment by syl20bnr** [comment]
First you can choose the keys for the leaders: https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/.spacemacs.template#L81-L94

Then you can set bindings for a specific mode using its key binding map:
https://github.com/syl20bnr/spacemacs/blob/develop/elpa/omnisharp-20150505.1234/example-config-for-evil-mode.el#L11

In this case it is for C#:
```elisp
(evil-define-key 'normal omnisharp-mode-map (kbd "g R") 'omnisharp-rename)
```

Fore more info look at the code in spacemacs with `SPC f e h` and `SPC /`, this is the best source of example.

**Comment by geo7** [comment]
This doesn't load for me @syl20bnr : 

https://github.com/syl20bnr/spacemacs/blob/develop/elpa/omnisharp-20150505.1234/example-config-for-evil-mode.el#L11

*******

`(evil-define-key 'normal omnisharp-mode-map (kbd "g R") 'omnisharp-rename)`

This example maps `gR` to `omnisharp-rename`

Thanks for the guidence though, I'll go through them

**Comment by syl20bnr** [comment]
This is because the map is not yet available, you have to defer it with

```elisp
(eval-after-load 'omnisharp
  `(evil-define-key 'normal omnisharp-mode-map (kbd "g R") 'omnisharp-rename))
```

With several expression you have to use a progn:

```elisp
(eval-after-load 'omnisharp
  `(progn
      (evil-define-key 'normal omnisharp-mode-map (kbd "g R") 'omnisharp-rename)
      (evil-define-key 'normal omnisharp-mode-map (kbd "g R") 'omnisharp-rename)))
```

**Comment by geo7** [comment]
when i said it didn't load I was referring to the hyperlink, I just got a 404 message from that. 

******

I'm not finding this obvious at all from reading the `.spacemacs` file

**Comment by syl20bnr** [comment]
I forgot to remove the link :-)
You've got the idea now so you should be good to go.
For the leader keys we need a better documentation, right now it is documented but at different places.

**Comment by geo7** [comment]
Oh right no worries :)

Yeah, I can have a play with what's here thanks

And yes I agree - I proposed here https://github.com/syl20bnr/spacemacs/issues/1735#issuecomment-105592873 that there was a walk through of a basic `.vimrc` to `.spacemacs` conversion made. I think this would be really useful and cover many questions around this kind of thing. I know person808 has made a migration guide, perhaps integrating it to that would be the most appropriate place for it, or stand alone idk. 

cheers though :)
