### ISSUE TITLE
Helm micro-state does not exit properly

### ISSUE THREAD

**Issue by dtreiter** [syl20bnr/spacemacs#1774]
To reproduce:
Open a helm buffer (i.e. helm-M-x)
Press C-SPC to enter the helm micro-state
Press C-g to send a keyboard-quit, closing the helm buffer

Now basic navigation will be messed up.

If it makes any difference, I'm using vim keybindings -- not holy-mode.

**Comment by TheBB** [comment]
I can't reproduce this problem on develop. Since the issue has been open for a while, I will close. If this is still a problem for you, please reopen.
