### ISSUE TITLE
"def" doesn't trigger automatic "end" using Ruby layer

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#1775]
Either `class` `SPC` or `module` `SPC` will add closing `end` automatically but for some reason it doesn't work with `def` `SPC`.

**Comment by exitface** [comment]
This is probably related to/duplicate of #518

**Comment by Eilie** [comment]
@exitface You're right, closing this one. Workaround mentioned in #518 did help by the way, would be cool to fix evil-escape tho.
