### ISSUE TITLE
Evil command d+<motion> broken with ","

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#1780]
Specifically, `dt,` or `df,` when the major-mode leader key is set as ",". It used to work before the latest round of develop branch updates, but not it seems to register the comma as leader, and waits for another input.

**Comment by syl20bnr** [comment]
In which major-mode do you have this behavior ?

**Comment by sooheon** [comment]
This was in org-mode and markdown mode, I have tested again and the issue if fixed
