### ISSUE TITLE
Smooth scrolling [Enhancement]

### ISSUE THREAD

**Issue by ReneFroger** [syl20bnr/spacemacs#1781]
[Smooth scroll plugin](http://www.emacswiki.org/emacs/smooth-scroll.el). 

With the following settings: 

```
( require 'smooth-scroll                        ) ;; Smooth scroll 
( smooth-scroll-mode 1                          ) ;; Enable it 
( setq smooth-scroll/vscroll-step-size 5        ) ;; Set the speed right
```

Try scroll option, or with page-up and page-down. It gives 

I believe this is a big improvement. Because when I'm scrolling, I have difficulties to recognize in which way the file was scrolling and where I exactly am. This package helps me with that.

**Comment by tuhdo** [comment]
We had a PR a while ago: https://github.com/syl20bnr/spacemacs/pull/1670

But thank you :+1:

**Comment by syl20bnr** [comment]
We are using `smooth-scrolling` plugin, is this really the same thing as `smooth-scroll` ?

**Comment by sooheon** [comment]
Just tested it. They address different issues. The `smooth-scrolling` we have currently is like vim's scrolloff margin feature, which lets you scroll off screen without the cursor jumping to the center of the screen. `smooth-scroll` is literally a smoother (graphically), non-instantaneous scroll. Therefore, it cannot replace `smooth-scrolling`, but it could be an addition for those who want it. Personally I could take it or leave it, this is what I added to my config to make it work if @ReneFroger wants to improve and submit a layer:

```
(defun sooheon/init-smooth-scroll ()
  (use-package smooth-scroll
    :defer
    :init
    (progn
      (require 'smooth-scroll)
      (smooth-scroll-mode 1)
      (setq smooth-scroll/vscroll-step-size 5))))
```

**Comment by tuhdo** [comment]
@sooheon you are right. I've tested it. It works nicely even on large file. I think this would make a user friendly addition for new comers.

@ReneFroger Thank you for this awesome suggestion. Sorry for not testing it and jump to the conclusion so quickly.

**Comment by ReneFroger** [comment]
@tuhdo it's not a problem, I was surprised by your first comment, because I considered `smooth-scroll` to provide much more smooth scrolling than `smooth-scrolling`. But glad to read that you like it. 

By the way, everyone, when you compare it with his [Vim counterpart Smooth Scroll](https://github.com/terryma/vim-smooth-scroll) , it's even actually bad.

Let me demonstrate it for you:

https://www.youtube.com/watch?v=GCwZnBgR4DM

I couldn't figure out how I could get the scrolling in Emacs so nicely as in Vim.

**Comment by tuhdo** [comment]
@ReneFroger If you want Emacs scroll faster, try setting `smooth-scroll/vscroll-step-size` to `10` or higher.

**Comment by ReneFroger** [comment]
Yes, I'm aware of that. But that's not the problem. It's not so smooth as in Vim.

**Comment by sooheon** [comment]
That I think is a limitation of emacs, at least from my experience with cocoa emacs on OS X. Even scrolling with the trackpad gives linewise scroll.

**Comment by syl20bnr** [comment]
For reference I mention here that there is pixel based scrolling with [homebrew-emacsmacport](https://github.com/railwaycat/homebrew-emacsmacport) version. There is even support for swipe gesture to switch buffer. Very nice version on OS X and one of the ingredient to make some users switch to emacs.

**Comment by Profpatsch** [comment]
I have the following in my config:

``` elisp
  ;;; scroll one line at a time (less "jumpy" than defaults)
  (setq mouse-wheel-scroll-amount '(2 ((shift) . 1))) ;; two lines at a time
  (setq mouse-wheel-progressive-speed nil) ;; don't accelerate scrolling
  (setq mouse-wheel-follow-mouse 't) ;; scroll window under mouse
```

Works reasonably well.

**Comment by Profpatsch** [comment]
yeah

**Comment by ReneFroger** [comment]
Any status of this?

**Comment by nixmaniack** [comment]
I guess someone needs to make a PR!

**Comment by syl20bnr** [comment]
PR opened: https://github.com/syl20bnr/spacemacs/pull/14542
