### ISSUE TITLE
git recursive clone missing many submodules; evil-org not loading?

### ISSUE THREAD

**Issue by msarahan** [syl20bnr/spacemacs#1787]
Fresh install on Arch Linux, emacs 24.5.1.

Git clone misses many submodules:

08:55 ~ git clone --recursive http://github.com/syl20bnr/spacemacs ~/.emacs.d
Cloning into '/home/msarahan/.emacs.d'...
remote: Counting objects: 19347, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 19347 (delta 6), reused 0 (delta 0), pack-reused 19335
Receiving objects: 100% (19347/19347), 13.83 MiB | 264.00 KiB/s, done.
Resolving deltas: 100% (12488/12488), done.
Checking connectivity... done.
Submodule 'spacemacs/extensions/emoji-cheat-sheet' (http://github.com/ShingoFukuyama/emacs-emoji-cheat-sheet) registered for path 'spacemacs/extensions/emoji-cheat-sheet'
Submodule 'spacemacs/extensions/revive' (http://github.com/vedang/revive-mode.git) registered for path 'spacemacs/extensions/revive'
Submodule 'spacemacs/extensions/spray' (http://github.com/syl20bnr/spray) registered for path 'spacemacs/extensions/spray'
Submodule 'spacemacs/extensions/yasnippet-snippets' (http://github.com/AndreaCrotti/yasnippet-snippets.git) registered for path 'spacemacs/extensions/yasnippet-snippets'
Cloning into 'spacemacs/extensions/emoji-cheat-sheet'...
remote: Counting objects: 891, done.
remote: Total 891 (delta 0), reused 0 (delta 0), pack-reused 891
Receiving objects: 100% (891/891), 1.59 MiB | 282.00 KiB/s, done.
Resolving deltas: 100% (40/40), done.
Checking connectivity... done.
Submodule path 'spacemacs/extensions/emoji-cheat-sheet': checked out 'e6ced968c646dad7288f506fc61662f2636a5e56'
Cloning into 'spacemacs/extensions/revive'...
remote: Counting objects: 13, done.
remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 13
Unpacking objects: 100% (13/13), done.
Checking connectivity... done.
Submodule path 'spacemacs/extensions/revive': checked out '4ede71f582ed195ac51d763c522e62cffd52851c'
Cloning into 'spacemacs/extensions/spray'...
remote: Counting objects: 178, done.
remote: Total 178 (delta 0), reused 0 (delta 0), pack-reused 178
Receiving objects: 100% (178/178), 864.82 KiB | 258.00 KiB/s, done.
Resolving deltas: 100% (80/80), done.
Checking connectivity... done.
Submodule path 'spacemacs/extensions/spray': checked out '70bf09465080294835afd09780b055d206ff0065'
Cloning into 'spacemacs/extensions/yasnippet-snippets'...
remote: Counting objects: 3594, done.
remote: Total 3594 (delta 0), reused 0 (delta 0), pack-reused 3594
Receiving objects: 100% (3594/3594), 559.83 KiB | 261.00 KiB/s, done.
Resolving deltas: 100% (697/697), done.
Checking connectivity... done.
Submodule path 'spacemacs/extensions/yasnippet-snippets': checked out '32bbd36d9a774b9cab6207523ffb5b24179b6505'

I noted that evil-org mode was missing, but is present in .gitmodules 

I used this ruby script to force installation:
https://gist.github.com/frimik/5125436

evil-org-mode is now present in spacemacs/extensions, but when I edit a .org file, it is not activated.  I tried to find the evil-org-mode command, or anything like that, but it doesn't seem to be present.  What am I missing?

**Comment by Funnnny** [comment]
can you try to do a clone in master?, yas-snippets has been removed and it appears in your log, so I think yours is not current.
evil-org should be in the org layer, did you enable org layer in .spacemacs file ?

**Comment by msarahan** [comment]
Thank you! I was missing the activation of the org layer.  I found this helpful tutorial after your suggestion:

http://thume.ca/howto/2015/03/07/configuring-spacemacs-a-tutorial/

Would a PR for the README pointing to or presenting this information be helpful?

**Comment by fedragon** [comment]
Hello,
I think I'm facing an issue similar to the one described above. `org` is not loaded at startup (although it is included in my `.spacemacs`). I tried to delete `.emacs.d` and clone again and only two submodules are registered (`revive` and `spray`):

```
git clone --recursive https://github.com/syl20bnr/spacemacs ~/.emacs.d

Cloning into '/Users/freidereikhs/.emacs.d'...
remote: Counting objects: 20906, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 20906 (delta 12), reused 0 (delta 0), pack-reused 20881
Receiving objects: 100% (20906/20906), 15.40 MiB | 2.84 MiB/s, done.
Resolving deltas: 100% (13424/13424), done.
Checking connectivity... done.
Submodule 'spacemacs/extensions/revive' (https://github.com/vedang/revive-mode.git) registered for path 'spacemacs/extensions/revive'
Submodule 'spacemacs/extensions/spray' (https://github.com/syl20bnr/spray) registered for path 'spacemacs/extensions/spray'
Cloning into 'spacemacs/extensions/revive'...
remote: Counting objects: 13, done.
remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 13
Unpacking objects: 100% (13/13), done.
Checking connectivity... done.
Submodule path 'spacemacs/extensions/revive': checked out '4ede71f582ed195ac51d763c522e62cffd52851c'
Cloning into 'spacemacs/extensions/spray'...
remote: Counting objects: 178, done.
remote: Total 178 (delta 0), reused 0 (delta 0), pack-reused 178
Receiving objects: 100% (178/178), 864.82 KiB | 1.17 MiB/s, done.
Resolving deltas: 100% (80/80), done.
Checking connectivity... done.
Submodule path 'spacemacs/extensions/spray': checked out '70bf09465080294835afd09780b055d206ff0065'
```

```
less .emacs.d/.gitmodules

[submodule "spacemacs/extensions/projmake-mode"]
        path = extensions/projmake-mode
        url = https://github.com/ericbmerritt/projmake-mode
[submodule "spacemacs/extensions/revive"]
        path = spacemacs/extensions/revive
        url = https://github.com/vedang/revive-mode.git
[submodule "spacemacs/extensions/helm-c-moccur"]
        path = extensions/helm-c-moccur
        url = https://github.com/syl20bnr/helm-c-moccur
[submodule "spacemacs/extensions/evil-org-mode"]
        path = spacemacs/extensions/evil-org-mode
        url = https://github.com/syl20bnr/evil-org-mode
[submodule "spacemacs/extensions/helm-rcirc"]
        path = spacemacs/extensions/helm-rcirc
        url = https://github.com/syl20bnr/helm-rcirc
[submodule "spacemacs/extensions/spray"]
        path = spacemacs/extensions/spray
        url = https://github.com/syl20bnr/spray
```

```
ls .emacs.d/spacemacs/extensions/

centered-cursor      holy-mode            solarized-theme      zoom-frm
evil-evilified-state paradox              spacemacs-theme
helm-spacemacs       revive               spray
```
