### ISSUE TITLE
capital u not working

### ISSUE THREAD

**Issue by SkuliJohannsson** [syl20bnr/spacemacs#1795]
I'm going through the evil tutor. Why is it that capital u is not working ( shift-u) ?

In vim it should revert all changes to a line.

**Comment by syl20bnr** [comment]
Can you check what command is bound to `U` ? 
`SPC h d k` then type `U`.

**Comment by SkuliJohannsson** [comment]
It is undefined.

**Comment by TheBB** [comment]
Evil doesn't have that functionality. You can report to evil, if you like. If you do, please comment so we can keep track of the issue.
