### ISSUE TITLE
how to disable changelog/release notes in 0.102.x?

### ISSUE THREAD

**Issue by buster** [syl20bnr/spacemacs#1798]
Hi,

in the version prior to 0.102 the changelog was quite small. but with the new release it moves my recent files far away. My .spacemacs file did contain "dotspacemacs-always-show-changelog t" in the version before, but commenting it out or setting it to "nil" keeps displaying the changelog..

How do i disable the changelog in the spacemacs buffer?

**Comment by jupl** [comment]
Just select/click/tap on `[Release Notes]` in the Spacemacs buffer to hide it. It persists the change when you close and repoen emacs.

**Comment by buster** [comment]
Thanks, somehow i didnt figure that out..
