### ISSUE TITLE
Where Did Git Layer Go?

### ISSUE THREAD

**Issue by mentalisttraceur** [syl20bnr/spacemacs#1799]
Trying to figure out where the git layer went in the source tree:

https://github.com/syl20bnr/spacemacs/blob/master/contrib/git

I did a fresh install of spacemacs and enabled the git layer and it loaded it fine, so spacemacs is still aware of it near as I can tell, but I can't tell where it went in the source.

**Comment by mentalisttraceur** [comment]
My apologies, I spoke too soon. I just found it here:
https://github.com/syl20bnr/spacemacs/tree/master/contrib/!tools/git

**Comment by mentalisttraceur** [comment]
That said, this still need updating, because it points to the old link: https://github.com/syl20bnr/spacemacs/blob/master/README.md <-- just search for "git layer" to find where.

**Comment by tuhdo** [comment]
You can use the built-in `SPC f e h` to get access to all layers, with its documentation and code. To open documentation in plain markdown, press `C-u` before pressing `RET`. You can use `C-o` to switch between the two lists in `SPC  f e h`.

**Comment by mentalisttraceur** [comment]
@tuhdo Thank you - I was aware of `SPC f e h` but not the `C-u` or `C-o`. Anyway, that last comment was more to note that that readme needs updating for the benefit of less experienced users, for whom the main/root readme on github is presumably intended to be helpful.
