### ISSUE TITLE
Pressing `s` to stage visually selected lines in magit not working

### ISSUE THREAD

**Issue by hafenr** [syl20bnr/spacemacs#1802]
If I'm in the magit-status window (`SPC g s`) I should be able to visually select lines that I want to have staged and then stage them by pressing `s`.  This doesn't work, however, since evil seems to wait for an additional key press.

Screenshot: http://cl.ly/image/3l1Y0W0Y1B3X

If I do `M-x magit-stage-item RET` while having the line selected, the line gets staged correctly. So it seems to be a problem with evil and that mode.

**Comment by tuhdo** [comment]
As a workaround, you can press `C-z` to temporary switch to Emacs state and press `s`.

**Comment by tuhdo** [comment]
But it seems like it was fixed in this issue: https://github.com/syl20bnr/spacemacs/issues/1462

Are you on the latest master? If not, then you should update and see.

**Comment by hafenr** [comment]
Updating via the [Update] shortcut in the spacemacs main window didn't work initially. A complete reinstall did however indeed fix the problem on master. s is now working with selected lines.
