### ISSUE TITLE
Line-background extending outside linum-mode numbers

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#1803]
So for example here
[![alt](https://i.imgur.com/zyKd46F.png)](https://i.imgur.com/zyKd46F.png)

[![alt](https://i.imgur.com/61dhldQ.png)](https://i.imgur.com/61dhldQ.png)

**Comment by jupl** [comment]
Looks like it's related to monokai because it changes the background when you select a matching pair. Other themes where the highlighting pair does not change the background don't appear to have the same issue.

**Comment by CestDiego** [comment]
I see it in gotham as well.. 
[![alt](https://i.imgur.com/26IAPdX.png)](https://i.imgur.com/26IAPdX.png)
and zenburn
[![alt](https://i.imgur.com/U0cQEmY.png)](https://i.imgur.com/U0cQEmY.png)

**Comment by CestDiego** [comment]
Solarized is the only one that doesn't have it.

**Comment by jupl** [comment]
Ah I see. I guess since I'm using relative linum I don't get that extra space in the linum. NVM

**Comment by CestDiego** [comment]
@jupl I have it too with relative linum.
> kek

**Comment by CestDiego** [comment]
I have these variables though. It seems that git-gutter-use-fringe has some trouble existing and not existing ;_; 
```elisp
     (git :variables
          git-magit-status-fullscreen t
          git-enable-github-support t
          git-gutter-use-fringe nil)
```

**Comment by jupl** [comment]
Forgot to mention I also set `linum-relative-current-symbol` to `""` so I get an absolute linum for the current line.

**Comment by CestDiego** [comment]
oh that makes sense... Another issue here is that this git status doesn't show if I don't enable linum-mode

**Comment by TheBB** [comment]
Is this still a bug?

**Comment by CestDiego** [comment]
I don't see this anymore

**Comment by TheBB** [comment]
Okay, begone with ye, issue!!

**Comment by CestDiego** [comment]
Oh wait....it still is here... https://i.imgur.com/vVuPuxv.png but only when the first character is `[` or `(` or `{` i guess it has to do with parens?

**Comment by jupl** [comment]
Yarp. 
<img width="68" alt="screen shot 2015-09-15 at 11 12 14 am" src="https://cloud.githubusercontent.com/assets/2065876/9882534/b10e6954-5b9a-11e5-8820-58b348b2c97f.png">

**Comment by TheBB** [comment]
Okay. :-(

**Comment by CestDiego** [comment]
onm y end it looks pretty though :P

**Comment by jupl** [comment]
I'm using relative line numbers.

**Comment by CestDiego** [comment]
I see it now I don't mind this one either :P 
[![alt](https://i.imgur.com/m7nqKe3.png)](https://i.imgur.com/m7nqKe3.png)
