### ISSUE TITLE
Magit status discard item K does not work in visual state

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#1804]
In Magit status when I make a selection of text I can stage/unstage with `s` and `u`, like how I can stage/unstage hunks with `s` and `u`. I can discard a hunk with `K` but I am unable to discard a selection of text with `K` and get a prompt for `Manual entry:` instead, making things inconsistent.

**Comment by person808** [comment]
What does `SPC h d k K` output in `magit-status`?

**Comment by jupl** [comment]
In visual mode `evil-lookup`.

**Comment by cpaulik** [comment]
This was fixed for me with commit https://github.com/syl20bnr/spacemacs/commit/3a829ce89e7b347f317d0263794e93c02bdeb995

**Comment by justin808** [comment]
I'm still seeing this on master. Is there some special configuration to make this work?
