### ISSUE TITLE
New buffer keybindings violate spacemacs core pillars

### ISSUE THREAD

**Issue by saghaulor** [syl20bnr/spacemacs#1809]
As per https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#mnemonic,

key bindings should be mnemonic. Previously, switching a buffer used a mnemonic keybinding, <kbd> Space b  b</kbd> However, since https://github.com/syl20bnr/spacemacs/commit/22afdf25b44a0eb545ac6a20405f201e6c59f8e2 it no longer does, it instead uses <kbd>Space Tab</kdb>

I would also like to comment that changing the behavior of an existing keybinding is confusing and undesirable. Previously, switch to alternate buffer used

<kbd> Space  b  b </kbd>

Now that behavior is used for 'switch to a buffer using helm'.

Perhaps to follow the core pillars, alternate buffer switching should be <kbd>Space b Tab</kbd>

Moreover, in the aforementioned commit it was mentioned that the <kbd>Space b s</kbd> keybinding was removed to be used in the future for buffer searching. It seems to me that using <kbd>Space b / </kbd> would be more consistent and intuitive.

**Comment by syl20bnr** [comment]
This is a good question.

`SPC b b` is now consistent with `SPC f f` (open file) and `SPC p p` (switch project) and free up `SPC b s`.

`SPC b s` is reserved for potential `search in opened buffers` commands, they will follow the same template as key bindings for `SPC s` and `SPC p s`, see the documentation for more info on this template: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#searching-in-an-arbitrary-directory
`SPC b /` is part of this template. (Note that there is an exception in this template, `SPC p /` is `SPC /`).

I was the first "victim" of these change, I had more that 2 years of `SPC b s` in my muscle memory, but I think the new layout is better and more consistent.
