### ISSUE TITLE
mardown layer not triggered when opening a `.md` file

### ISSUE THREAD

**Issue by emmanueltouzery** [syl20bnr/spacemacs#1811]
when opening a `.md` file (for instance README.md) the markdown layer is not triggered, rather the major mode is displayed as being `GFM`.
When opening a `.markdown` file things work as expected. This is on 0.102.1, confirmed by others on the gitter chat too:
https://gitter.im/syl20bnr/spacemacs?at=556d6d52463d0c7c066db0c0

**Comment by tuhdo** [comment]
`GFM` means `GitHub Flavoured Markdown`. I think it was chosen as default because people usually use Markdown with Github.

**Comment by emmanueltouzery** [comment]
hmm ok but none of the markdown layer shortcuts work... like `SPC m i l` and others documented in [the markdown layer documentation](https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/markdown). That sounds like a terrible shame. Is there no way to get the shortcuts also for the GFM? I don't see any docs for the GFM, and since `SPC m` doesn't work, I'm not expecting much from it :/

What does that layer provide?

**Comment by tuhdo** [comment]
The key bindings work for me. Note that I'm using `holy-mode`. You should try `M-x markown-` to see whether all the markdown commands have key bindings or not. But in my case, they have.

**Comment by emmanueltouzery** [comment]
I'm seeing the emacs shortcuts yes. `C-c C-j`, `C-c C-c o` and so on. But I would like to use the spacemacs layer shortcuts, under `SPC m`. I'm a vim convert and I really think I'll never use the original emacs shortcuts :-/

**Comment by tuhdo** [comment]
You're right. Currently the key bindings are set for `markdown-mode` but we use `gfm-mode`, so the `markdown-mode` bindings won't be loaded. I had Spacemacs bindings because I first load `markdown-mode` then switched to `gfm-mode`.

**Comment by hijarian** [comment]
@tuhdo So, what is the conclusion? Markdown mode loading is messed up in 0.102.1?

**Comment by hijarian** [comment]
I support that we should probably default to gfm-mode but at least let's make it consistent.

**Comment by cpaulik** [comment]
I have to say that I can not reproduce this. When I open a *.md file like e.g. the README.md of the python layer spacemacs uses markdown-mode for me. How/when does this happen? I also haven't found the code that is supposed to switch to gfm-mode automatically.

**Comment by syl20bnr** [comment]
I have GFM now as well, used to be plain markdown, I think some `auto-mode-alist` has been modified in a package somewhere. I don't see any modification at the spacemacs level that could have introduced this behavior.

**Comment by cpaulik** [comment]
This change was [introduced upstream 12 days ago](http://jblevins.org/git/markdown-mode.git/commit/?id=0b34b76b2ef62a9d86d68030fd5a05bff77ee6e3) and now [reverted](http://jblevins.org/git/markdown-mode.git/commit/?id=f1632bc37dfe84ce67417685587bbcdc61431a2f). So updating your packages again should solve this for now. 

Of course we should probably add the keybindings also to `gfm-mode` to avoid the same problem in the future.

**Comment by syl20bnr** [comment]
Thank you @cpaulik :+1:
