### ISSUE TITLE
Having problems in the Python REPL

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1813]
This gives me an error within the REPL in emacs :

```python
lst = []
>>> for d,s,f in os.walk('TESTER'):
...     lst.append(s)
  File "<stdin>", line 1
    lst.append(s)
    ^
IndentationError: unexpected indent
>>>
```

This works fine in the terminal :

```python
>>> lst = []
>>> for d,s,f in os.walk('TESTER'):
...     lst.append(s)
...
>>>
```
Doesn't seem to be picking up some stuff as it's giving an indent error? 

os module imported on both examples

**Comment by tuhdo** [comment]
Currently, Emacs inserts spaces when you press `TAB`. You have to make Emacs actually inserts tab character in Python REPL. Add this to your `dotspacemacs/config` function:

```elisp
(add-hook 'inferior-python-mode-hook (lambda ()
                                       (setq indent-tabs-mode t)))
```

You can also write in a temporary Python buffer (created with `SPC b b`, if there's some candidate, switch to `Create Buffer` source at the bottom with `C-o`) then send to the Python REPL. You have many commands for sending i.e. send a function definition at point with `SPC s f`.

**Comment by axg-ux** [comment]
I'm facing a similar problem at the moment and have no idea how I can get repr to work as normal. I don't use the tab buttor at all and only use spaces for indentation. It already strange with how we can just backspace over the prompt and the space in front of it. Is that space counted as part of the indentation in for loops? I would like some guide as how to best use this repr. At thet moment I'm having to simply resort to opening a buffer with ansi-term and then running python interpreter in there manually.

**Comment by zhexuany** [comment]
@tuhdo Do you have other way around? I already did what you wrote in this post. But, it still did not work at all.

**Comment by mbertheau** [comment]
@zhexuany he meant <kbd>SPC m s f</kbd> to send the function to the REPL. Try that. You might also have to make the python buffer visible for you (create a window and switch to the `*Python*` buffer in it). When I just tried it `*Python*` didn't make itself visible automatically.

**Comment by zhexuany** [comment]
@mbertheau  Thanks for your kindly reply. But the key bindings you mentioned did not work in my spacemacs. I used M-m m s f.  Did you mean C-c C-p?
