### ISSUE TITLE
cuda support

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#1815]
Is there any cuda language mode in emacs/ spacemacs? just use c++-mode only the highlight syntax, but the syntax checking hook like flycheck will give many false alarm, which is annoying in daily work. Is there any better solution? for example, Nvidia Nsight tool in visual studio or eclipse? 

As we all know, GPU computing grows rapidly, it will benefit a lot emacsers.
http://www.nvidia.com/object/nsight.html

**Comment by syl20bnr** [comment]
In spacemacs `0.102.0`++ you can press `SPC t s` to toggle syntax checking.
You can install a cuda mode by putting `cuda-mode` in the variable `dotspacemacs-additional-packages` and then configure it in `dotspacemacs/config`.

Here is a gist (`;; ...` denote some code that you may have before or after): https://gist.github.com/syl20bnr/a33e77f7107a36c248b6

```elisp
(defun dotspacemacs/layers ()
"Configuration Layers declaration."
(setq-default
;; ...
;; List of additional packages that will be installed wihout being
;; wrapped in a layer. If you need some configuration for these
;; packages then consider to create a layer, you can also put the
;; configuration in `dotspacemacs/config'.
dotspacemacs-additional-packages '(cuda-mode)
;; ...
))
 
(defun dotspacemacs/config ()
"Configuration function.
This function is called at the very end of Spacemacs initialization after
layers configuration."
;; ...
(use-package cuda-mode
:defer t)
;; ...
) 
```

**Comment by dzhwinter** [comment]
thank you, syl.  that's really helpful.



dzhwinter@gmail.com
 
From: Sylvain Benner
Date: 2015-06-04 00:57
To: syl20bnr/spacemacs
CC: dzhwinter
Subject: Re: [spacemacs] cuda support (#1815)
In spacemacs 0.102.0++ you can press SPC t s to toggle syntax checking.
You can install a cuda mode by putting cuda-mode in the variable dotspacemacs-additional-packages and then configure it in dotspacemacs/config.
Here is a gist (;; ... denote some code that you may have before or after): https://gist.github.com/syl20bnr/a33e77f7107a36c248b6
(defun dotspacemacs/layers ()
"Configuration Layers declaration."
(setq-default
;; ...
;; List of additional packages that will be installed wihout being
;; wrapped in a layer. If you need some configuration for these
;; packages then consider to create a layer, you can also put the
;; configuration in `dotspacemacs/config'.
dotspacemacs-additional-packages '(cuda-mode)
;; ...
))
(defun dotspacemacs/config ()
"Configuration function.
This function is called at the very end of Spacemacs initialization after
layers configuration."
;; ...
(use-package cuda-mode
:defer t)
;; ...
)

**Comment by whcn** [comment]
thanks, but It isn't compeletly helpful, why those api functions ( just like cudaMalloc() ) don't highlight?

**Comment by dzhwinter** [comment]
cuda mode写得很简单，没人维护。你可以看看它的源码，能用就不错了。切c++mode 还好一些。chinese layer是子龙山人热心给提上去的，我没用过，感觉用处不大吧。

**Comment by whcn** [comment]
chinese layer用起来还可以，汉字跳转和有道查单词
vim里填上cuda.vim貌似也不能高亮cudaMalloc这些函数，你现在搞定了么

**Comment by dzhwinter** [comment]
没搞定，影响不大
