### ISSUE TITLE
Visual Profiler tool support

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#1816]
this feature always contains in many modern programming editors, And it is useful in daily code polish  work when ask to optimal the performance. If there is an common layer that one can add third-party profiling tool into spacemacs without any knowledge,about elisp., which will be great.

**Comment by dzhwinter** [comment]
e.g python https://github.com/what-studio/profiling
e.g c# https://github.com/what-studio/profiling

**Comment by cpaulik** [comment]
I'm not quite sure how this should work since the profilers you linked have quite different setup/calling procedures. I doubt that this could be generalized in a way that makes it possible to add profilers without knowledge of elisp. 

Regarding the python profiler: have you tried using the `python -m profiling profile your-program.py` in compile mode? Does this work interactively?

**Comment by syl20bnr** [comment]
@dzhwinter Do you have examples of editors where this feature is available so I can try it ?

**Comment by dzhwinter** [comment]
![cputime](https://cloud.githubusercontent.com/assets/6687176/7984984/e07afa68-0aff-11e5-8293-8a1f6b0c2de7.jpg)

here is my code
![code](https://cloud.githubusercontent.com/assets/6687176/7985004/1067be6e-0b00-11e5-9d52-1b3d308cd619.jpg)
@cpaulik

**Comment by dzhwinter** [comment]
I'm explore the possible to integrated performance and diagnose tools in spacemacs.
take those profiling tools just for example.
Github reject my screenshot uploading request  again and again. Only can i post an example here. 
http://www.zhihu.com/question/27768721/answer/38014129 forget the chinese, just take a look at the image.  
editors like eclipse or visual studio both have this feature. 
for c#, c++, in Visual Studio 2015 community(free), clink on Performance and diagnose. it only support MS language c#, of course, c++.  
for cuda
https://developer.nvidia.com/nvidia-nsight-visual-studio-edition

Actually, profile tools  have little value in python, but it really matters when improve c++ and cuda  interact with hardware language code. 
So, my question is, how to hook c++ or cuda profiling tools in spacemacs? or intergrated them in? 
: )

**Comment by tuhdo** [comment]
As for C/C++ profiling, Emacs does not go that far. Maybe you should have a look at a dedicated application [Kcachegrind](http://kcachegrind.sourceforge.net/html/Screenshots.html) or [gprof](https://sourceware.org/binutils/docs/gprof/) that comes with GNU Binutils then use [gprof2dot](https://github.com/jrfonseca/gprof2dot) to view it in graph format. I don't see any difference except you have to use two OS windows.

**Comment by StreakyCobra** [comment]
As it's a 4 months old discussion that nobody is looking at anymore, it will not be answered nor continued. I'm closing it then, but in any case feel free to open a new one to re-up the discussion :relaxed:
