### ISSUE TITLE
[gdb] blocking call to accept-process-output with quit inhibited!

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#1818]
My situation is it not only occur in ipython, but also in gdb many windows mode. when in gdb mode i press "[]", The message buffer repeat "blocking call to accept-process-output with quit inhibited!" many times, nothing else. may be parens match package?

 I find that some users also come across that  window will freeze when the message occur. as far as i find in the issues, they stuck into this situation in ipython mode, and the anaconda author give an solution is remove it from his package. 

  have fix it in newer version? 

my version is 0.101.3
emacs 25.1-nox
ubuntu 14.04
thx

**Comment by TheBB** [comment]
Since this issue is (a) old, (b) inactive, (c) for a very old version of Spacemacs and (d) for an unsupported version of Emacs, I will close it. Please reopen if you find that it persists with a newer version and up to date packages.

**Comment by atwoz** [comment]
I'm having the same Issue in GDB many-windows. When I type some text (some times numeric) it freezes and displays that error.

I have the latests spacemacs
0.200.7@25.1.1 
OSX 10.12.3
