### ISSUE TITLE
Changing sentence delimiter

### ISSUE THREAD

**Issue by tapichu** [syl20bnr/spacemacs#1819]
Hi, how can I restore the *two space* sentence delimiter?

I always use vim with `set cpoptions+=J`, as the single space delimiter quickly shows limitations when using punctuation inside a sentence (abbreviations, titles, etc.)

Is this something I can configure in dotspacemacs/init?

I don't mind what the default value is, as long as I can choose the one I want.

**Comment by syl20bnr** [comment]
Put this in your `dotspacemacs/config` function:

```elisp
(setq-default sentence-end-double-space t)
```

**Comment by tapichu** [comment]
Thanks!
