### ISSUE TITLE
Org clock commands broken by recent commit

### ISSUE THREAD

**Issue by conklech** [syl20bnr/spacemacs#1821]
306d284f369ac3261cf9bea00541e0538e077e67 broke `org-clock-in` and some other functions; `SPC m I` in an org buffer just gives `Symbol's function definition is void: org-clock-in`. Reverting to v0.102.0 and restarting solves the problem.

Does that commit change the load order somehow? I found [this StackOverflow answer](http://stackoverflow.com/a/23087333/1186208) which suggests that initializing `org` too late can cause this problem. (I know virtually nothing about this.)

**Comment by syl20bnr** [comment]
Thank you for the report, I think it is related to #1800.

**Comment by conklech** [comment]
You're right; exact duplicate. Sorry!
