### ISSUE TITLE
Docs have some notation inconsistencies

### ISSUE THREAD

**Issue by MerelyAPseudonym** [syl20bnr/spacemacs#1823]
There are two consistency problems that I've come across:
1. Sometimes keybindings are just written in backticks (example: `M-m f f`) and other times they're written using HTML `<kbd>` markup (example: <kbd>M-m f f</kbd>).
2. Sometimes the spacebar is written in keybindings with angle brackets (example: <kbd>&lt;SPC&gt; f f</kbd>) and other times without (example: <kbd>SPC f f</kbd>).

**Comment by cpaulik** [comment]
While this should probably be consistent I think it might be not worth it to fix this in markdown in light of https://github.com/syl20bnr/spacemacs/issues/1568

**Comment by MerelyAPseudonym** [comment]
@cpaulik good to know about. Thanks!

**Comment by syl20bnr** [comment]
The export script will surely take care about the conversion so it is OK to fix them in markdown too. I'll make sure to merge the markdown fixes before converting to org :-)

**Comment by person808** [comment]
I believe I have fixed these inconsistencies in #1939

**Comment by StreakyCobra** [comment]
There is only few places left in the documentation containing either `<kbd>` or `<SPC>`. I'll let this issue for beginners.
