### ISSUE TITLE
org clock not shown in modeline

### ISSUE THREAD

**Issue by edwintorok** [syl20bnr/spacemacs#1827]
I don't have the clock in my modeline.
It is [supposed to be there](https://github.com/syl20bnr/spacemacs/issues/267), but [this commit hides it?](https://github.com/syl20bnr/spacemacs/commit/f8ae1051507edcddcd183d0556e625e26163b627)

**Comment by syl20bnr** [comment]
The global-mode-string should work fine, to show the clock you can use `SPC t m c`.

**Comment by edwintorok** [comment]
Indeed, thanks
