### ISSUE TITLE
Private snippets are only loaded after manually executing `yas-reload-all`

### ISSUE THREAD

**Issue by hafenr** [syl20bnr/spacemacs#1830]
So here's the problem:

I created some snippets for javascript and python in the `private` dir, like so:

```
 private/
   angularjs/
   snippets/
     js-mode/
       beforeEach
       describe
       describeMidway
       it
       test
       wrapperFunction
     python-mode/
     README.md
   README.md
```

Now if I open a javascript or python file, the snippets won't show up. If I execute `yas-reload-all` from within the buffer, they do show up though and I can insert them.

The content of my `yas-snippets-dirs` variable:

```
("/Users/hafenr/.emacs.d/private/snippets/" "/Users/hafenr/.emacs.d/private/angularjs/angularjs-mode/snippets" "~/.emacs.d/snippets" yas-installed-snippets-dir)
```

**Comment by duerrp** [comment]
Same here...

Btw., thanks for the great work! Spacemacs is fantastic!
