### ISSUE TITLE
python mode multi-line indentation fails pep8

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#1831]
The automatic indentation and manual reindenting with <kbd>=</kbd> in vi-mode puts the closing bracket in wrong place that makes pep8/flake8 flycheck complain:
```python
print("hello",
      "world",
)
```
`E124 closing bracket does not match visual indentation`

The bracket needs to align with the first thing after the opening bracket if it's on the same line i.e.:
```python
print("hello",
      "world",
      )
```
The automatic indentation doesn't cause any errors if there's a newline after the opening bracket though: 
```python
print(
    "hello",
    "world",
)
```

**Comment by syl20bnr** [comment]
Does it happen on a stock Emacs ?
If it is happening also in a stock Emacs then this is a bug that should be reported in Emacs bug tracker since python mode is a built-in mode.

**Comment by tko** [comment]
Yes, I can replicate it with `emacs -Q` and `indent-according-to-mode` on "GNU Emacs 24.5.3 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2015-04-11 on Atago.local"

**Comment by syl20bnr** [comment]
So its a bug to report to Emacs contributors, here is the procedure to report a bug: https://debbugs.gnu.org/Emacs.html

Same thing as the other issue, if you open a bug there then link it here so we can track it.
Thank you!

**Comment by tko** [comment]
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=20742

**Comment by kiniou** [comment]
I was also experiencing this issue and I'm now using some piece of code i've found in [this stackoverflow question](
http://stackoverflow.com/questions/4293074/in-emacs-python-mode-customize-multi-line-statement-indentation) which i put in my `dotspacemacs/config`.

**Comment by tko** [comment]
@kiniou that thing did nothing for me, there's no `python-calculate-indentation` from what I can tell.

I'm currently testing this thing I put together, putting the closing paren horizontally aligned next to the opening one when the indentation of the _previous_ line matches (or perhaps rather doesn't match) some magic keywords. I haven't the foggiest idea about emacs/python indentation, though.
```elisp
  (defadvice python-indent-calculate-indentation (after unbreak-pep8-brackets)
    ;; correct:              original:
    ;;   print("hello",        print("hello",
    ;;         )               )
    (save-excursion
      (let ((this (python-indent-context))
            (prev (progn (forward-line -1) (python-indent-context))))
        (if (and (eq (car this) :inside-paren-at-closing-paren)
                 (memq (car prev) `(:inside-paren :after-line)))
            (progn
              (goto-char (cdr this))
              (setq ad-return-value (+ 1 (current-column)))
              )
          ))))
  (ad-activate 'python-indent-calculate-indentation))
```

**Comment by kiniou** [comment]
@tko : I think i misread your OP as i was thinking the stackoverflow answer was related and where it was not the same issue sorry.

As a former vim user, I'm still in the middle of the learning curve with emacs and I've to admit i'm a bit disoriented with the different indentation handled by emacs modes.

A bit after my post, I've switched from [`contrib/!lang/python`](http://github.com/syl20bnr/spacemacs/tree/8dadfc1494544bb152e80c2a436e43bc3713b389/contrib/!lang/python) to [`python-mode.el`](https://github.com/emacsmirror/python-mode) which seems to take an another (IMO and AFAICT better :smile:) approach with indentation and might fix your issue since i'm not able to reproduce your issue with the later.

**Comment by tko** [comment]
@kiniou so far other than the broken indentation in one case I haven't noticed anything annoying in the emacs default python mode.

The earlier workaround doesn't really work. This seems better.
```elisp
  (defun tko--python-indent-unbreak-pep8-E124 (&rest args)
    ;; correct:              original:
    ;;   print("hello",        print("hello",
    ;;         )               )
    (save-restriction
      (widen)
      (save-excursion
        (pcase (python-indent-context)
          (`(,(or :inside-paren-at-closing-paren
                  :inside-paren-at-closing-nested-paren) . ,start)
           (goto-char (+ 1 start))
           (if (not (looking-at "[ \t]*\\(?:#\\|$\\)"))
               (current-column)))))))
  (advice-add 'python-indent-calculate-indentation
              :before-until 'tko--python-indent-unbreak-pep8-E124)
```

**Comment by CestDiego** [comment]
this doesn't have to do with Spacemacs. Should be reported upstream though.

**Comment by TheBB** [comment]
As far as I can tell this is actually fixed.

**Comment by leviroth** [comment]
This seems not to be in fact fixed: Problem still persists both in vanilla Emacs and Spacemacs. There was a patch posted in the upstream bugtracker, but it appears that it has not been merged in by the maintainer.
