### ISSUE TITLE
spacemacs gets stuck in replace/change mode

### ISSUE THREAD

**Issue by edwintorok** [syl20bnr/spacemacs#1832]
Sometimes spacemacs just overwrites existing characters instead of inserting new ones (like in Vim's replace and change commands) and I don't know how to get out of it.
`fd`, `C-g`, `ESC`, `SPC feR` or using Vim change word/replace commands don't get me out.
Is there a way to debug what mode/state this is and how I got there?

There should be a fail-safe way to reset the overwrite mode (bound to `fd` perhaps), right now all I can do is restart spacemacs.

**Comment by syl20bnr** [comment]
Can you provide some reproduction steps ?
Maybe the keyboard (hardware) state is not in insert for some reason ?

**Comment by edwintorok** [comment]
After some testing it looks like it is the `<insert>` key (which I sometimes typo when I want to press `<home>`): in Vim it just takes me from normal mode to insert mode, but in Spacemacs it activates overwrite mode, which seems like a hybrid between insert mode and replace mode: most characters get overwritten but some characters like `f` are inserted.

In Vim once I'm in normal mode I don't expect to have any other persistent modes/states that change the way typing works, could you document other such 'Emacs surprises' in DOCUMENATION.md?
Also `fd` or going back to normal mode should probably disable overwrite mode.

**Comment by syl20bnr** [comment]
Since it is a different behavior than Vim it can be reported upstream here: https://bitbucket.org/lyro/evil/issues?status=new&status=open
If you report it, be sure to link the issue here so we can track it.

**Comment by edwintorok** [comment]
Here you go: https://bitbucket.org/lyro/evil/issue/528/enters-overwrite-mode-and-doesnt-exit-from

The `f` key seems to be a spacemacs "feature" though, even in replace mode `R` it inserts instead of overwriting, is this due to the mapping of `fd`?

**Comment by syl20bnr** [comment]
the `f` key is a bug in evil-escape :-) You can _another_ bug in evil-escape repo here: https://github.com/syl20bnr/evil-escape/issues

**Comment by edwintorok** [comment]
https://github.com/syl20bnr/evil-escape/issues/28

**Comment by syl20bnr** [comment]
Thank you very much!

**Comment by edwintorok** [comment]
New version of evil with the fix has been released: pressing `<insert>` once enters insert mode, pressing it again enters overwrite mode, but pressing `<esc>` goes to normal state and disables overwrite mode.
