### ISSUE TITLE
Weird org + git gutter indentation bug

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#1833]
1. Have `git` and `org` layers enabled.
2. Initialize an empty git repository somewhere.
3. Open an org file in this repository. Fill it with a heading followed by a handful of content lines.
4. Save, stage and commit it.
5. Scroll around a bit (it's a short file so you may have to use `C-e` and `C-y`). Note that indentation is fine.
6. Make a change to each line (you don't need to do all of them, but I don't know exactly the conditions that will reproduce this). Save the file, so that the git gutter will show.
7. Scroll until the first visible line is a non-heading. The indentation will be messed up.

Temporary workaround: `(remove-hook 'org-mode-hook 'git/load-git-gutter)`.

In other news, don't browse more than one issue page at the same time while tired. You might accidentally [misreport](https://github.com/JuliaLang/julia/issues/11562). :-(

**Comment by TheBB** [comment]
Some screenshots if you can't be bothered to walk through the hoops. Initial file contents:

![](http://i.imgur.com/0YA2OkK.png)

Scrolling works fine:

![](http://i.imgur.com/570g4sp.png)

Change content and trigger the gutter:

![](http://i.imgur.com/E5UjVVS.png)

Now scroll:

![](http://i.imgur.com/B0A249O.png)

**Comment by tuhdo** [comment]
I think it's better to remove `git-gutter` and use `diff-hl`: https://github.com/dgutov/diff-hl

It works for me. `diff-hl` has the same functionality as `git-gutter`.

**Comment by syl20bnr** [comment]
@tuhdo After a quick look at `diff-hl` it does not seem to be able to draw in the right fringe, does it play well with flycheck and other icons ?

We have to compare the commands available in `git-gutter` and `hl-diff`, seems that `hl-diff` only proposes to revert a hunk. I believe that `git-gutter` has more commands which are bound in Spacemacs (I don't use them).

**Comment by tuhdo** [comment]
> After a quick look at diff-hl it does not seem to be able to draw in the right fringe, does it play well with flycheck and other icons ?

If a flycheck marker is on the fringe, it overrides `diff-hl` marker. But I think this should be not much of a problem, since flycheck usually takes 1 or 2 lines.

AFAIK, `diff-hl` only shows diff status on the left fringe, but maybe there's a way to make it on the right. Personally, I think it's more convenient to see diff status on the left, so you don't have to move your eyes.

>  seems that hl-diff only proposes to revert a hunk.

These are the supported commands in `diff-hl`:

- diff-hl-next-hunk
- diff-hl-revert-hunk
- diff-hl-previous-hunk
- diff-hl-diff-goto-hunk

It can also be used in Dired.

**Comment by dgutov** [comment]
> I believe that git-gutter has more commands

`git-gutter`'s advantage is that it had a "stage hunk" command. I'm not inclined to implement it in `diff-hl` until VC learns this operation, which is in all likelihood never, since it doesn't make sense outside of Git.
