### ISSUE TITLE
TAB does not work in helm action menu

### ISSUE THREAD

**Issue by liangwang** [syl20bnr/spacemacs#1834]
When in the action menu of a helm-find-files session, the modeline suggests that TAB will take me back to candidate list. However, TAB is locked to helm-execute-persistent-action which will open an dired buffer of the previously selected direcoty, while the action menu is still there.

spacemacs: 102.1
emacs 24.4.1

**Comment by tuhdo** [comment]
The current key binding to switch between action menu and Helm buffer is `C-z`. `TAB` is for executing persistent action.

**Comment by liangwang** [comment]
Thanks, C-z works! So the modeline of the action menu is misleading. I guess it is hard-coded in helm, therefore the swap of C-z and TAB is not reflected accordingly.

**Comment by syl20bnr** [comment]
Maybe it is time to customize the mode-line ? :-)
cf. #502

**Comment by StreakyCobra** [comment]
This has been solved in `develop`. Now spaceline shows `C-z` in action screen.
