### ISSUE TITLE
helm-projectile-grep fails to respect projectile-use-git-grep variable

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#1835]
In a git project setting `projectile-use-git-grep` significantly increases the performance of `projectile-grep` but that does not seem to have any effect on `helm-projectile-grep`. This is rather unfortunate as while the latter has reasonable <kbd>SPC p s g</kbd> keyboard shortcut assigned the former does not making it relatively inconvenient to use.

**Comment by syl20bnr** [comment]
I wonder if this is something to handle in spacemacs or upstream in `helm-projectile` (I think it comes from the `projectile` repo).

**Comment by tko** [comment]
Comparing https://github.com/bbatsov/projectile/blob/master/projectile.el#L1700 and https://github.com/bbatsov/projectile/blob/master/helm-projectile.el#L630 it looks like an upstream issue; helm-projectile only supports ack and "grep -r" currently.

**Comment by syl20bnr** [comment]
Can you report this upstream and link to the issue here so we can track its status ?

**Comment by StreakyCobra** [comment]
It looks like the issue has been fixed upstream. If it is not the case, feel free to ping me here, I'll reopen it :relaxed:
