### ISSUE TITLE
Update installation documentation in README

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#1837]
Many users had trouble when updating with a `git pull`.

Update the documentation to mention that `master` is not meant to be pulled or forked, updating is a matter of `git fetch` + `git reset --hard` to a specific tag version.

Only the `develop` branch is "fork and pull safe".

**Comment by Immortalin** [comment]
@syl20bnr is the `revert to specific version` guide master-friendly?

**Comment by Immortalin** [comment]
@StreakyCobra @syl20bnr merge and add `fixed in develop label`?
