### ISSUE TITLE
Enable Company Globally by default

### ISSUE THREAD

**Issue by trishume** [syl20bnr/spacemacs#1841]
As discussed in https://github.com/syl20bnr/spacemacs/pull/1762 I think it would be a good idea to enable company-mode globally-ish (for any mode derived from `prog-mode`, c mode and maybe some other base modes), or alternatively globally but with a blacklist of modes such as markdown.

This is a problem as evidenced by all the issues popping up about specific niche modes missing completion (#1789, #1762, #1760), why not solve them all in one fell swoop right now, and make them proper later.

#### What happens if you enable company globally
Modes that don't have explicit company setups (of which there are many) get fairly intelligent `company-dabbrev` completion or completion from one of company's built in backends that Spacemacs doesn't yet use (like `company-nxml`). IMO this is a much better user experience than just getting no completion.

Having it enabled globally appears to have no adverse effects as I have been using it for months.

#### What I am *NOT* arguing
- I am not arguing that it shouldn't be an option, I'm saying it should be the *default*.
- I am not arguing that layers shouldn't explicitly use company, I only care about layers that have no support in them.

#### Background

@syl20bnr previously said in #1762 "It provides better isolation and it is a good thing, for instance it will allow some nice features like being able to exclude a package for a specific layer". I do not consider this a good argument:

Part of my suggestion is implementing a list of modes where it is known that auto-completion is a bad thing, or putting explicit *exclusion* in those modes. Something like an `auto-completion-layer-blacklist` variable that defaults to `markdown-mode ...` and the user can add stuff to would serve the same purpose and be easy to implement immediately.

"it provides better isolation and it is a good thing" are not clear arguments and seem to be addressed at the idea that I don't think layers should have explicit auto-completion support, which I already mentioned is not what I'm arguing.

"The user should be able to read a packages.el and understand what feature we provide." this property is preserved by this change, if there is no mention of company then a layer doesn't provide any special auto-completion and the basic stuff that is everywhere will apply, because you enabled `auto-completion` so that's what you should get.

#### Rules of engagement
Any argument against making global company the default must either:
- Argue that having no auto-completion in unsupported modes will be better for the user
- Argue that having no auto-completion in unsupported modes will be better for contributors
   - I consider this one even a bit fishy because I don't think the experience of now thousands of users should be sacrificed for tiny gains in contributor niceness.

Here are some possible avenues of argument:
- Spacemacs defaults should not be what most users would prefer.
- Globally enabled company will do something really bad
- Globally enabled company will or make something really good impossible.
- Explicit company setup for every one of the hundreds of modes one would likely desire completion in will be completed extremely soon.

I think these are some pretty reasonable guidelines for keeping arguments valid. If an argument isn't for the benefit of users and isn't for the benefit of contributors, who the heck is is for?

#### Summary

I think Spacemacs should strive to provide the best possible user experience by default for all possible situations and currently global company is a big hole where many more niche modes just don't have auto-completion when they easily could, providing a worse experience for users. I think that if every user knew how to enable global company, almost all would, so it should be the default.

As you can see from the length of this issue and my persistence I really care about this. I think not having global company when you enable the auto-completion layer is complete negligence on our part in giving users a great experience. My experience when starting out with Spacemacs was great because everything just worked out of the box, with the un-globalization auto-completion has moved away from that ideal and I think that's a tragedy for our users.

cc @tuhdo @mijoharas @rphillips as they were involved in earlier discussion

**Comment by tuhdo** [comment]
@syl20bnr You may want to look at my proposal for global company without breaking current company architecture in Spacemacs: https://github.com/syl20bnr/spacemacs/issues/1797#issuecomment-107406962

**Comment by syl20bnr** [comment]
I'm sorry but I won't change my mind on this topic, I thought I was clear on this.

Company must be enabled *explicitly* in all layers supporting it. This is the same approach for other packages like flycheck and it is a core principal of the spacemacs architecture.

Global mode + exclusion list is a no go, when I have some declarations in my code I always prefer the approach showing me what is _used_ (like layers), I don't care about what is not used. When looking at a layer we have to be able to see the declaration of any used package, again this is at the core of spacemacs layers.

Now it does not prevent a user to have company enabled globally but it  is a *user consciously made choice* like @trishume did. It is a matter of adding `(global-company-mode)` in the dotfile.

**Comment by tuhdo** [comment]
@syl20bnr But we can have a controlled global backends. Even a global backend with just `company-dabbrev`, it is still useful. That is, if a layer is not supported directly, it uses `company-dabbrev`, and only use that backend. What's the problem here?

Btw, my proposal works even without globally enabling company. Basically it's just a refactoring for current company architecture.

**Comment by syl20bnr** [comment]
@tuhdo company must be enabled explicitly for each layer supported it. Another global variable is not required, we can use the stock one, see what it takes to enable regular company for a layer (lua in this case): https://github.com/syl20bnr/spacemacs/blob/develop/contrib/!lang/lua/packages.el#L26-L27

**Comment by syl20bnr** [comment]
When I look at the lua layer I can see clearly that it support `flycheck` and `company` and I will be able to code the feature to exclude a package for a given layer which will be a very nice feature to have.

**Comment by tuhdo** [comment]
@syl20bnr not another global variable but a variable to replace the current macro that generates a company variable for each major mode, and this is unneeded. As I said, it's just a refactoring of current company architecture.

Enabling company globally doesn't mean that we can't see support for a layer. Surely if a layer has support for company, I can clearly see it with `SPC f e h`. What is losing here? Even if we do it this way, gradually we add company everywhere and effectively it becomes "global". i.e. we can enable `company` even in `text mode` and `fundamental-mode`. So, we can save some troubles by having default company backends in place where `company` is not directly supported, with very simple backends like `company-dabbrev`, `company-file`.

`flycheck` is a different case. And you can say that the "generic flycheck" that simply checks for text typos is `flyspell`, and we have it enabled globally.

**Comment by syl20bnr** [comment]
I agree that global company is convenient and the user can enable this convenience and thus be aware of it. Spacemacs does not prevent anyone from having this convenience.

At the stock spacemacs level, to have company enabled in a layer it has to be declared explicitly, there is nothing to argue at this point, to handle so many packages we **need** isolation, it comes at a DRY violation, this is fine to me.

Should be the same for flyspell, but I don't see it enabled in elisp and C# on my current system.

**Comment by tuhdo** [comment]
> I agree that global company is convenient and the user can enable this convenience and thus be aware of it

What if a new user never knows about `company`. Think of someone coming from Vim. It would take them a long time before they can be comfortable with Elisp.

But I mean, what's the harm of having only `company-dabbrev` everywhere?

**Comment by syl20bnr** [comment]
> What if a new user never knows about company.

Then this user:
1) does not read the [README](https://github.com/syl20bnr/spacemacs/tree/master/contrib/auto-completion#enable-company-or-auto-complete-globally)
2) does not post any question anywhere
3) does not read any blog post saying that "spacemacs should enable company globally so here is how to do it" :-)

> But I mean, what's the harm of having only company-dabbrev everywhere?

The harm is that company must be declared explicitly in each layer using it.

**Comment by tuhdo** [comment]
> The harm is that company must be declared explicitly in each layer using it.

I mean, with a global company and its default backend is just `company-dabbrev`, so you don't have to enable company for every layer, what's the harm? 

> 2) does not post any question anywhere

The thing is, this user is a new Vim convert and he does not know anything about Emacs ecosystem to read that REAMDE in auto-completion layer or to ask. Heck, he may not even know that `company` sits  in there.

**Comment by syl20bnr** [comment]
> so you don't have to enable company for every layer, what's the harm?

The harm is exactly that. I want to enable company explicitly.

No company declaration = no company for this layer.

I know that this is the exact opposite of what you do in a personal configuration, fact is spacemacs is not a personal configuration, it has to stay manageable even with 1000 packages, at this scale the convenience of global states can badly hurt and increase complexity (especially when we start to exclude things). I don't know what spacemacs will look like in 2 years but I know that explicit declaration will always tell me what a layer is made of, that I won't have to remember that something important is enabled elsewhere and that it could be inhibited at some other place for something where the documentation of why it is excluded will be lacking.

This is not specific for company, as I mentioned flycheck is in the same boat, and flyspell should be too and more and more. The idea is not to save line of codes the idea is to make a configuration that will scale and welcome new packages easily, the idea is to have isolated layers where I can look at and see everything that the layer has to offer.

Moreover I like the idea of incremental configurations.

**Comment by trishume** [comment]
You are still arguing against the one thing I made explicitly clear I am not talking about. From my original issue: "I am not arguing that layers shouldn't explicitly use company, I only care about layers that have no support in them."

I have said now many many times **I AGREE WITH YOU** that layers should explicitly declare company support. Every one of your arguments is arguing for a point which I already agree with you on.

This proposal is fundamentally about a limitation in our ability. We do not have the man-power to explicitly add company to every mode emacs supports. We should try, but we'll never make it the whole way, there are just too many modes especially with the dotspacemacs packages variable.

My argument is *only* for the layers that don't have support yet to make the user experience better in the mean time for the thousands of existing users while we build out explicit support. Unless you can tell me that you will personally add explicit company declaration for *every* programming language I can possibly use within Spacemacs by the next release we should enable it for all programming modes so these modes have a nice user experience.

If we eventually build out support such that almost no emacs programming modes don't have explicit company support then we change the default back, but in the mean time we should strive to make the experience of using Spacemacs the best we can by not withholding auto-completion on niche languages for no good reason.

**Comment by syl20bnr** [comment]
@trishume How is it even possible ? My position is `company not declared explicitly == no company`. Tell me how you can enable company blindly for niche language without breaking this principle and not replying on global company. The only possible way to not rely on global company is to use hooks which is what we do when we declare company explicitly.

I see 2 possible situations here:
1) there is a layer for mode X then company must be declared explicitly
2) there is not layer for it then it is not supported by spacemacs and the user must either declared it explicitly by looking to official layers or enable company globally (things we cannot do for him).

**Comment by mijoharas** [comment]
I have one simple idea for a middle ground. create an extra configuration layer: `global-auto-completion` or `global-compnany-mode` which simply enables company-mode globally, this could solve the contention in that it keeps this kind of stuff out of personal config and pushes it into configuration layers, (which I prefer maintaining as it's simpler to just copy that to your new .spacemacs every once in a while) and would provide additional discoverability for users, and allow maybe a blanket prog-mode derived company (or whatever is wanted).

**Comment by trishume** [comment]
@mijoharas you can already just enable company globally with a line in `.spacemacs`, I'm saying it should be the default because it is more user-friendly.

@syl20bnr I can't understand what you what argument you just tried to make. "My position is company not declared explicitly == no company. Tell me how you can enable company blindly for niche languages without breaking this principle and not replying on global company" this isn't an argument and doesn't address anything I said, it simplifies to "because I say so".

I also have no idea what you are saying about "relying on global company". With this default not a single layer will rely on global company, they don't have to care at all. You include the `auto-completion` layer and things get auto-completion and if a layer doesn't explicitly support it they get basic completion without having to care.

I would really appreciate it if you could tell me which of the following points you disagree with and why, together these form all the premises of a complete logical argument for enabling global company by default:
- Most users would want basic auto-completion in unsupported modes rather than nothing.
- Having a global company default would come at no other cost to users 
    - evidence: I've been using it for months and it was the default up to v0.100
- Having a global company default would come at no other cost to contributors or code cleanliness. 
    - evidence: it is already an option that users are allowed to enable, enabling it by default would be as simple as copying those lines into the layer. If all the code in spacemacs must be written such that this code can be put in the dotfile, it can just as easily be written such that this code can be put in the `auto-completion` layer.
- The union of users and contributors are the only stakeholders in Spacemacs.
- Spacemacs defaults ought to be things that most users would want, that don't inflict costs that outweigh their benefits.

I don't know if it is a language barrier but you seem to be completely misunderstanding what I am arguing for. Or I'm not understanding what you are saying because all your arguments appear to not be addressing what I'm saying.

**Comment by sooheon** [comment]
I am one of those who have enabled company globally in dotspacemacs to no great catastrophe. Still, I see why @syl20bnr values explicitness over convenient defaults. As the number of layers and number of contributors grows, it becomes more important to consider each layer in isolation.

>Most users would want basic auto-completion in unsupported modes rather than nothing.

Agreed.

>Having a global company default would come at no other cost to users.

There are actually some surprising interactions. Company and org-mode, for example, will often move your cursor mid-writing if the completion occurs near eol. To this, you would answer: "enable global company mode, then put org-mode into an exclusion list". Now here's where any contributor or user would have to keep three things in their head: company mode support in the org layer, whether it is enabled globally or not, and whether it is included in the exclusion list or not. Or, you could have it explicitly declared only in the layer by default, and that would be the first and only place any user would have to look on principle. *Then*, should the user feel the need, for all the conveniences you've laid out, they can choose to enable company globally in their own config.

> Spacemacs defaults ought to be things that most users would want, *that don't inflict costs that outweigh their benefits.*

This is a value judgement on the cost of losing explicitness of layer configs, and isn't as clear cut as you make it out. There is a cost of complexity by bringing some configuration state out of the layer, and I think @syl20bnr is right to put the burden of managing that complexity on the user.

>"I am not arguing that layers shouldn't explicitly use company, I only care about layers that have no support in them."

You understand the value of defaults, and the inertia they can bring. You also understand the need for discipline and manpower in being diligent about declaring explicit support per layer. If company is enabled globally by default, that is one less reason for contributors to be explicit in the layer, even if it's the right thing to do. "Eh, it'll work anyway, why don't I add that later." The contributor's behaviour tips over to "on by default, config when needed turn it off" which encourages exactly the opposite of what the maintainer wants.

People coming from vim aren't idiots, they can (most of us did, remember?) google "emacs autocomplete package", and then "how to enable company for every filetype?". Remember all the steps involved in getting YouCompleteMe to work, *after* the decision is made to use it. Here, once the users *decide* for themselves that they want to use it, it's a matter of adding one extremely well documented line to their personal config.

**Comment by trishume** [comment]
Ok that's good enough reasoning for me. Thank you for laying out a clear argument.

I still think it should be enabled globally by default but that's because my weightings of user vs. contributor sanity in various situations seem to be different. Given that it's not my project and so not my place to determine what the correct user/contributor sanity weightings should be, I'll admit defeat on this one.

I'm always happy to go along with decisions I disagree with, provided the alternative position is explained and justified well.
