### ISSUE TITLE
[BUG]web-mode micro-state rename a tag some keys not work

### ISSUE THREAD

**Issue by BlinkD** [syl20bnr/spacemacs#1846]
when i press `SPC m . r` in web-mode,to rename a tag, all micro-state keys are not available to work.

**Comment by StreakyCobra** [comment]
@BlinkD What the current status of this bug? For me `SPC m . r` exits the micro-state (which is a bug indeed)

**Comment by justbur** [comment]
@StreakyCobra I vote to close issues like this. You asked for feedback a long time ago

**Comment by StreakyCobra** [comment]
@justbur Indeed, thx!
