### ISSUE TITLE
[Question] Search at point with helm-ag

### ISSUE THREAD

**Issue by PierreR** [syl20bnr/spacemacs#1848]
Is there a way to have `SPC /` that would search the word at point (maybe `SPC *`) ?
Somehow I have the feeling that `SPC /` used to behave that way.

Thanks for your help.

**Comment by tuhdo** [comment]
You can set this option:

```elisp
(setq helm-ag-insert-at-point 'symbol)
```

And I agree this is really useful.

Yes, it was used to be that way until a PR was merged in Projectile to make non-inserting symbol the default.

**Comment by PierreR** [comment]
Thanks so much ! This is so useful it deserves to be in the documentation somehow.

**Comment by base698** [comment]
What's the key or command for it?
