### ISSUE TITLE
Haskell hlint : HLint.hs not taking into account

### ISSUE THREAD

**Issue by PierreR** [syl20bnr/spacemacs#1853]
I am trying to disable some hlint errors by using a HLint.hs file at the root of the project:

```
import "hint" HLint.HLint

ignore "Redundant lambda"
```
Unfortunately it does not work. I stil get a red point on:
```
let queryfunc = \node -> ....
```
On the command line if I use `hlint` it does work (it is telling me a suggestion has been ignored).

Is there a way to disable these hlint errors ?

At least it would  be handy to use another color than red to show the hlint "errors" (the code compiles just fine after all).

**Comment by syl20bnr** [comment]
Related to https://github.com/syl20bnr/spacemacs/issues/753

**Comment by d12frosted** [comment]
@PierreR what does running `hlint path/to/file` returns? Does it say anything about lambda?

By the way, for me to disable hlints about lambda I need to put following into `HLint.hs`:

```
import "hint" HLint.HLint

ignore "Avoid lambda"
ignore "Redundant lambda"
```

**Comment by PierreR** [comment]
@d12frosted As already described, `hlint path/to/file` is working fine (it is telling me a suggestion has been ignored).

Do you want me to test it again ?  I haven't done so for a while so it might be fixed now.

**Comment by d12frosted** [comment]
@PierreR oh, right you already said that it's working when invoking from terminal. But yeah, could you please test again? Because I remember previously it didn't work for me in Emacs, but it's working.

**Comment by PierreR** [comment]
Yep this is working now. Thanks.

**Comment by d12frosted** [comment]
Great! Good to hear :smile:
