### ISSUE TITLE
evil-snipe settings set in `.spacemacs` not registered in 102+

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#1857]
I have always had the following lines in my `.spacemacs`:

```elisp
(defun dotspacemacs/config ()
  ;; Make evil-snipe override evil fFtT;,
  (setq evil-snipe-override-evil t)
  (setq evil-snipe-repeat-keys t)
  (setq evil-snipe-scope 'whole-buffer)
  (setq evil-snipe-repeat-scope 'whole-buffer)
  ...
 ```

But from version `102+` these settings do not work anymore. The standard `evil-snipe` settings are used, not those I request in my `.spacemacs`.

This is not because the package does not load; `s<two search letters>` still works.

I have tried applying the settings above afterwards with `C-x e`, but that does not help either.

However, if I use `M-x <RET> evil-snipe-f <RET> <search letter>` everything works well, both with `whole-buffer` scope and repeat searches.

The only changes I can see is that `evil-snipe` has moved from `contrib` to `contrib/!vim/` but that should not matter since the package loads just fine...

**Comment by endrebak** [comment]
Definitively some strange, strange stuff happening...

I have gotten it working by running `M-x global-evil-snipe-mode <RET>`. Then afterwards, the first search fails due to the settings not working, but when I try it once more it starts working.

Adding `(global-evil-snipe-mode 1)` to my `.spacemacs` did not work. Then I just had to run `M-x global-evil-snipe-mode` twice to first disable it, then enable it. Then it worked again after a first failing search.

Tried this several times with 102+ versions, happens consistently. Do not have time to investigate more closely until about a month unfortunately...

**Comment by syl20bnr** [comment]
@endrebak Do you confirm that it happen only in 0.102 with the same evil-snipe package version ?

**Comment by endrebak** [comment]
Nope, I tried downgrading to `101.x` (`git checkout 2450b7e276634ece07b6b7ec6ca6c287af86caf3`) and it happened again and the fix was the same.

At least it happens consistently. 

Paging @hlissner to see if he has any idea what might be wrong. Three days ago there was a commit: `No more global-evil-snipe-mode, evil-snipe-mode is global now`

**Comment by hlissner** [comment]
Oh, this might be my fault! I've made two small changes in lieu of an upcoming rewrite of evil-snipe (don't worry, no loss of backwards compatibility here on out): 

1) I've phased out `global-evil-snipe-mode` in favor of `evil-snipe-mode`, which is now, itself, global. So use `(evil-snipe-mode 1)` instead.

2) evil-snipe-override-mode is now a minor mode. Activate it with `(evil-snipe-override-mode 1)`.

See if those two fix your problem.

**Comment by endrebak** [comment]
Thanks, going away soon, but will make sure to do after weekend and report back. (Thanks for `evil-snipe` by the way. Was really frustrated just trying to do without it for a few minutes.)

**Comment by hlissner** [comment]
You're very welcome. Once I get around to the rewrite, I'll update the config layer for snipe again.

**Comment by endrebak** [comment]
This seems fixed in develop, about an hour before I started looking at it. Good start on a Monday morning.

Currently I have to add `(global-evil-snipe-mode 1)` to my `.spacemacs` to have it work on startup, but I guess this is desired behavior.
