### ISSUE TITLE
Remove . and .. entires in helm-find-files

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#1863]
Or put them at the end.
It prevents quick navigation in a tree where there are some directories with only one sub-directory.

**Comment by nashamri** [comment]
:+1: to that!

**Comment by TheBB** [comment]
Apparently it's not recommended, although the Helm maintainer seems unable to explain why, precisely. https://github.com/emacs-helm/helm/issues/924

I tried advising `helm-ff-sort-candidates` but I couldn't get it to work.

**Comment by syl20bnr** [comment]
I agree, if these entries are mandatory then at least we can try put them out of the way for quicker navigation.

Other possibility instead of sorting could be to automatically select the 3rd entry. I think this is the behavior of dired, I cannot check for now.

**Comment by syl20bnr** [comment]
Oh I agreed with myself it seems :-D

**Comment by Peaker** [comment]
I hacked helm files to allow ignoring /. /.. after all and now find-files is sooo much nicer! :-)

**Comment by zilongshanren** [comment]
cool @Peaker  could you send a PR?

**Comment by TheBB** [comment]
Yes, please share how you did it.

**Comment by Peaker** [comment]
I can't make a PR because I did it as a complete hack:

https://github.com/Peaker/helm/commit/1b554125ecc8629aa0f1dd5aca9665044c937f42

+ adding "/\\.$" "/\\.\\.$" to helm-boring-file-regexp-list in my custom.el

**Comment by TheBB** [comment]
Thanks @Peaker, even if you can't make a PR doesn't mean it's not helpful. It's actually possible to do with function advice without hacking Helm (or rather, the Helm source). I made a [layer](https://github.com/TheBB/spacemacs-layers/tree/master/no-dots) for it.

If desired I can put together a PR for Spacemacs. I didn't because I'm not sure how serious https://github.com/emacs-helm/helm/issues/924 is, even though I haven't come across that problem myself yet.

**Comment by StreakyCobra** [comment]
As nobody asked for this functionality last 4 months, upstream are not going to do anything on this, and the only existing solution is too hacky, it's a wontfix. People really wanting this can try @TheBB solution. I'm closing this issue then.

**Comment by PrgrmAtCeleritas** [comment]
@TheBB your link for the layer that addresses this is broken. Could you provide an updated one? I would love to address this issue.

**Comment by nixmaniack** [comment]
@PrgrmAtCeleritas https://github.com/TheBB/spacemacs-layers/tree/master/layers/no-dots

**Comment by CeleritasCelery** [comment]
I have been messing around with this and made a solution keeps the current directory hardlink at the bottom and removes the parent directory hardlink. Based on @TheBB's solution.
```elisp
(defun cel/helm-ff-dot-hardlink-p (file)
  (s-ends-with? ".." file))

(defun cel/helm-ff-return-true (&optional _arg) t)

(defun cel/helm-ff-up-one-level (fcn &rest args)
  (prog2
      (advice-add 'helm-file-completion-source-p
                  :override 'cel/helm-ff-return-true)
      (apply fcn args)
    (advice-remove 'helm-file-completion-source-p
                   'cel/helm-ff-return-true)))

(defun cel/helm-ff-dots-at-bottom (ret-val)
  (if (listp ret-val)
      (-rotate (- (--count (s-ends-with? "." it) (-take 2 ret-val)))
               ret-val)
    ret-val))

(with-eval-after-load 'helm-files
  (advice-add 'helm-ff-filter-candidate-one-by-one
              :before-until 'cel/helm-ff-dot-hardlink-p)
  (advice-add 'helm-find-files-up-one-level
              :around 'cel/helm-ff-up-one-level)
  (advice-add 'helm-find-files-get-candidates
              :filter-return 'cel/helm-ff-dots-at-bottom))
```
