### ISSUE TITLE
Loading snippets from private/snippets requires yas-reload-all

### ISSUE THREAD

**Issue by kevincolyar** [syl20bnr/spacemacs#1867]
Trying to use snippets in my `private/snippets/ruby-mode` requires me to call `yas-reload-all` before the snippets are available.  I'm using `SPC i s` to access the snippets.

**Comment by KenetJervet** [comment]
Can confirm this bug. In contrib/auto-completion/package.el, yas-global-mode is activated before the yas-snippet-dirs is set.

**Comment by TheBB** [comment]
Closing as duplicate of https://github.com/syl20bnr/spacemacs/issues/1830.
