### ISSUE TITLE
Workflow discussion

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#1871]
After the merging of #1630 I felt it was good to go over the new 'best' workflow, particularly since there's been a fair amount of discussion about it in other issues and PRs, including (but probably not limited to) in no particular order #1861, #1620, #1619, #1639 and #1850.

Now that #1630 is merged, I feel this simplifies things a lot and many of the things raised in these issues are voided, since you can now have whatever structure you feel like in the `private` directory and things will 'just work'.

* Private layers in `private` will work
* Cloning repositories containing layers (or a single layer) directly into `private` will work, which should simplify installation of, and collaboration on layers outside of the spacemacs repo
* There is no need to treat `snippets` as a special case, it can stay in `private`, and it's still possible to make a layer called `snippets`
* You can replicate this setup in any directory other than `private` just by adding a *single* entry to `dotspacemacs-configuration-layer-path`

**Comment by syl20bnr** [comment]
Indeed everything you mentioned is now possible, I'm not sure that we have to define what's the best workflow though. I just see that know it is even more flexible and simple so this is a very good thing, kudos for the PR :+1: 

Where do we have a special case for `snippets` ? I think we never treat it as special so we may had a bug previously :-)

**Comment by syl20bnr** [comment]
I will bump the new discovery in the `Hot nea features` sub-section of the change log since I now realize the full benefit of it.

**Comment by TheBB** [comment]
Yes, I realized after posting this maybe it wasn't too useful. I was sure there was a special case for `snippets` in the old code to prevent `private/snippets` from being interpreted as a layer. I can't really find it now… oh, well.

**Comment by justbur** [comment]
The special case for the snippets directory was here: https://github.com/syl20bnr/spacemacs/commit/a5a294cb33fe9852258cb51a5f328cb6f2881400#diff-2d7025db7d7e8c7c4cc1dee8c1e90ba8L212 . 

I think I'll give up on #1861, since in addition to the changes introduced by #1630, there is now a conflict with the commit https://github.com/syl20bnr/spacemacs/commit/7d53585795f3cea3c9b27f83f6d34cbea81fa92b as well. 

So I can now have private/snippets and private/layers. Then I just need to symlink to .spacemacs and I can almost have all of my spacemacs code in one directory. I know that people have suggested using GNU stow, which I've never tried, but managing symlinks across linux, windows and possibly cygwin and osx makes me uncomfortable (probably just because I don't understand any differences completely).

**Comment by trishume** [comment]
Sorry the close was an accidental click.

Btw @justbur you can use `dotspacemacs-configuration-layer-path` to avoid symlinks.

**Comment by justbur** [comment]
@trishume Right, but there was not a configurable variable for the location of my snippets until recently (looks like 7d53585 does this), and it has always been true that .spacemacs must be in the home folder. So if I wanted all of that to be together I needed some symlinks (not the biggest problem in the world, just a little annoying). 

The idea behind #1861 was to have a simple hierarchy of search paths that started with ~/.spacemacs, and then looked for .spacemacs.d/init.el if the first didn't exist (the directory .spacemacs.d could then be configured with an environment variable). When .spacemacs.d is being used it added new defaults for the layers and snippets. This just introduced a little more flexibility and made things easier for me without imposing that organization on others. That being said, the current setup is almost there for me. I was thinking this morning of making my private directory location configurable or using an environment variable for the location of .spacemacs, but I'll keep that code for myself if there's no interest here.

**Comment by syl20bnr** [comment]
> The idea behind #1861 *was* ...

Why "was" ? :-)

I'm thinking about it and I like the fact that this is consistent with the Emacs configuration mechanism.
