### ISSUE TITLE
Replace git-gutter with diff-hl

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1872]
Now `diff-hl` supports right fringe after this issue is closed: https://github.com/dgutov/diff-hl/issues/45

You can set this option:

```elisp
(setq diff-hl-side 'right)
```

to display the diff status to the right. Here is my full setup, which is very simple (remember to add `diff-hl` to your private layer package list):

```elisp
(defun tuhdo/init-diff-hl ()
  (use-package diff-hlt
    :defer t
    :init
    (setq diff-hl-side 'right)
    (add-hook 'prog-mode-hook 'diff-hl-mode)
    (add-hook 'dired-mode-hook 'diff-hl-dired-mode)))
```

**Comment by CestDiego** [comment]
How do you disable git-gutter for this?

**Comment by syl20bnr** [comment]
@CestDiego You can create a layer and `git-gutter` and `git-gutter-fringe` have to be added to `hl-diff-excluded-packages`.
Or you can add them to `dotspacemacs-excluded-packages`.

**Comment by syl20bnr** [comment]
@tuhdo I think we can replace git-gutter with it but I don't know where to put it. `git` layer is not the right place. I'm starting to think about renaming `git` layer to the more general `version-control` name.
It will match the `auto-completion` and `syntax-checking` abstract names.
