### ISSUE TITLE
Losing vim key bindings between evil-evilified-state and evil-normal-state

### ISSUE THREAD

**Issue by zimbatm** [syl20bnr/spacemacs#1874]
How to reproduce:
- Open a text file. vim emulation is working fine.
- Hit "M-x evil-evilified-state"
- Hit "M-x evil-normal-state"
- Try common vim normal-mode keys like i,d,D or : and notice that they aren't working anymore

This is a simplification from an issue I was seeing when switching between org-present back to org mode because of these hooks: https://github.com/syl20bnr/spacemacs/blob/da1a953878bfb4c41dc9d2350891def681476609/contrib/org/packages.el#L158

**Comment by robbyoconnor** [comment]
This is still an issue...

**Comment by gfZeng** [comment]
The same issue, please fix it

**Comment by TheBB** [comment]
I can't reproduce this.

**Comment by Miciah** [comment]
I cannot reproduce the issue using the reported steps, but I can reproduce it with one tweak:

1. Open a text file.
2. Enter `M-x evil-evilified-state`.
3. Enter `M-x evil-normal-state`.
4. **Press `ESC`.**
5. Try `a`, `A`, `b`, `B`, `c`, `C`, `d`, `D`, `e`, `E`, `f`, `F`, `H`, `i`, `I`, `J`, `K`, `L`, `m`, `M`, `o`, `O`, `p`, `P`, `q`, `Q`, `r`, `R`, `s`, `S`, `t`, `T`, `u`, `U`, `w`, `W`, `x`, `X`, `y`, `Y`, `z`, `Z`, `!`, `@`, `#`, `$`, `%`, `^`, `&`, `*`, `(`, `)`, `_`, `+`, `-`, `=`, grave, `~`, `[`, `]`, `\`, `{`, `}`, or `|`.

It seems that `ESC` gets bound to `evil-evilified-state` in `evil-normal-state-map`.

**Comment by Miciah** [comment]
This may be the same issue as #7766.
