### ISSUE TITLE
Variable binding depth exceeds max-specpdl-size

### ISSUE THREAD

**Issue by aVolpe** [syl20bnr/spacemacs#1880]
Hello

I am a new emacs user (long time vim user).

On a Fresh Install on a OpenSuse 13.2 with emacs `24.3.1` I get this error during the first start of spacemacs:

    Variable binding depth exceeds max-specpdl-size

I try to change the max level with `(setq max-specpdl-size 10000)` but it doesn't work.

**Comment by person808** [comment]
Could you launch emacs using `emacs --debug-init` and post the output?

**Comment by aVolpe** [comment]
@person808 yes, it's the first thing I try, but it doesn't print anything, see:

![preview](https://cloud.githubusercontent.com/assets/1097701/8021299/e1dd1cf6-0c67-11e5-8e80-dad90918f1b1.png)

The position of the error is diferent, but I can't do anything.

**Comment by syl20bnr** [comment]
@aVolpe can you try a more recent version of Emacs to see if the issue persists ?

**Comment by jhedev** [comment]
Same problem here. Also running OpenSuse 13.2 and Emacs 24.3.1. I'm not able to try a more recent version of Emacs currently, but I found out that using `v0.100.0` or `v0.100.1` of spacemacs just works fine.

**Comment by aVolpe** [comment]
The latest [emacs](ftp://ftp.gnu.org/pub/gnu), spacemacs works perfect!.
