### ISSUE TITLE
Can't uninstall themes-megapack layer

### ISSUE THREAD

**Issue by lmartins** [syl20bnr/spacemacs#1884]
I've added this layer to have a look around but now I can't remove it.
Tried by removing its reference on `dotspacemacs-configuration-layers` and once I do that I start to get error messages on launch:
```
Warning (initialization): An error occurred while loading `/Users/luismartins/.emacs.d/init.el':

File error: Renaming, not a directory, /Users/luismartins/.emacs.d/elpa/zen-and-art-theme-20120622.737, /Users/luismartins/.Trash/emacs/zen-and-art-theme-20120622.737
```
Adding this package to `dotspacemacs-excluded-packages` makes no difference either.

Any tips?

**Comment by syl20bnr** [comment]
Interesting, I assume that you are on OS X, do you have `trash` installed on you system ? It should be optional but maybe we have a bug if it's not there.
You can install it with homebrew.

**Comment by lmartins** [comment]
I had a shell utility also named `trash` already installed. Just to be sure removed and installed the one mentioned in the docs and repeated the process.

When I reload `.spacemacs` I immediately get an error on the status bar:
 
![screen shot 2015-06-07 at 21 36 38](https://cloud.githubusercontent.com/assets/151981/8025913/a4e5de7c-0d5d-11e5-91c4-8fdba03788b3.png)

And when relaunching the app:
![screen shot 2015-06-07 at 21 39 44](https://cloud.githubusercontent.com/assets/151981/8025923/d1e4b6c8-0d5d-11e5-958f-ff3fe7c4d4bc.png)

Thanks for your help.

**Comment by syl20bnr** [comment]
Do you have some kind of symlink somewhere ?

**Comment by lmartins** [comment]
Yes, the `.spacemacs` file is a symlink to a folder where I keep my dot files to sync with github. Can that be the reason for it?

**Comment by syl20bnr** [comment]
Yes it is likely to be the bug, Emacs provides specific functions to follow symlinks.
I flag it as a bug to be fixed. Thank you!
In the mean time you can `cp` the dotfile from your install script.

**Comment by lmartins** [comment]
I moved my `.spacemacs` file to my home folder, removing the symlink. Im still getting the same errors. Is there anything else I can do about this?

**Comment by geo7** [comment]
@lmartins did this sort itself out?

**Comment by lmartins** [comment]
Sorry @geo7, I have since stopped using SpaceMacs and forgot to close this issue. I didn't got it sorted then.
Cheers.
