### ISSUE TITLE
Make expand-region work like Vim

### ISSUE THREAD

**Issue by lmartins** [syl20bnr/spacemacs#1885]
Must say im quite enjoying spacemacs, some minor annoyances though.
One of those, is it possible to have the command `expand-region` to behave more like Vim, where I could just press `v` instead of `SPC v` every time?

**Comment by TheBB** [comment]
What are you after, exactly? In vim, as in evil/spacemacs, `v` enters visual mode. If you prefer entering visual mode through `expand-region` instead of the usual way, you can bind `v` to `er/expand-region`.

**Comment by lmartins** [comment]
I was looking to have a way so that after the first `SPC v` subsequently `v` would keep expanding the region. I just noticed that on Vim this is actually not default behaviour but a plugin I used there.

**Comment by TheBB** [comment]
> I was looking to have a way so that after the first `SPC v` subsequently `v` would keep expanding the region.

That's the default behaviour in spacemacs. After the first `SPC v`, you should see the following message in the minibuffer

    Type v to expand again, V to contract, r to reset, e to edit

Does this not happen?

**Comment by lmartins** [comment]
oh damn, not sure why it didn't worked first time. Yeah!!
Thanks @TheBB
