### ISSUE TITLE
Company-dabbrev-code-modes Initialization error

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#1891]
I don't know if this happenes to me, but I already started with fresh spacemacs and get this error with auto-completion layer.

```An error occurred while initializing company (error: (void-variable company-dabbrev-code-modes))```

**Comment by tuhdo** [comment]
By fresh Spacemacs, do you mean `master`? If so, maybe deleting `elpa` and reinstalling again.

**Comment by CestDiego** [comment]
no, this happened just after I updated the develop local branch.

**Comment by tuhdo** [comment]
I updated to latest develop (few minutes ago) and with my usual .spacemacs, everything is normal.

**Comment by CestDiego** [comment]
It's weird, I tried deleting elpa again, and starting from default .spacemacs and it works now, so it must be some stuff in my .spacemacs that is incompatible with latest update. Will confirm.

**Comment by syl20bnr** [comment]
I just pushed a commit to fix it.

**Comment by syl20bnr** [comment]
I was not able to reproduce though.

**Comment by CestDiego** [comment]
@syl20bnr that did it! :) it's weird I must inspect what I do in my config
