### ISSUE TITLE
Can't type `\` in LaTeX layer without a frustrating prompt

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1896]
I'm trying to write in a LaTeX buffer and it won't allow me to enter a `\` without a prompt. 
I can see situations where this prompt might be useful, but it can also be very annoying. 

If I have a block of text and want to `C-v` for visual block and insert `\item ` in front of all the lines this is very difficult at the moment when it should be most basic

**Comment by cpaulik** [comment]
What does the prompt say? Inserting `\item` in front of a visual block selection works for me.

**Comment by syl20bnr** [comment]
Can you provide a gif of the behavior ?

**Comment by geo7** [comment]
@syl20bnr hrmm, no i can't. I have the tools but not the means, i'll have a little google for something and get back :)
@cpaulik I'll post back an example cheers :)

**Comment by geo7** [comment]
Quality is a bit crap (I'm open to suggestions on better stuff to use for screen recording! kazam is what i have at the mo) 

here though @syl20bnr @cpaulik 

https://vid.me/Yjfo

**Comment by cpaulik** [comment]
`tex-insert-macro` is bound to `M-RET \` for me. So I don't see why this would interfere.

What keys do you press when inserting in front of visual block? I just use `I`

**Comment by geo7** [comment]
@cpaulik yep just `I` here as well, I'm going to update, haven't done that today :)

**Comment by geo7** [comment]
This is fine now btw - just thought I'd mention that and close :+1:
