### ISSUE TITLE
Spacemacs hangs in auto-complete(haskell) layer on "Loading symbols for"

### ISSUE THREAD

**Issue by razvan-panda** [syl20bnr/spacemacs#1905]
One CPU core is constantly used and it seems to hang forever (more than 5 minutes for sure).

To reproduce add a type annotation for main (main :: IO()) for example in https://github.com/fionnan/warp-pool/blob/master/Main.hs. It will hang on loading symbols for some random library.

Active layers:
     auto-completion
     better-defaults
     emacs-lisp
     themes-megapack
     syntax-checking
     haskell

There seem to be other people (ahem, same person) having similar issues:

http://cowboyjob.com/post/5001805/Im-using-spacemacs-and-have-found-that-the-haskell-layer-presents-a-problem-for-me

![](http://i.imgur.com/HPT4mFX.png)

![](http://i.imgur.com/MY3YoYg.png)

**Comment by razvan-panda** [comment]
This seems to be related to the auto-completion layer as disabling it no longer causes a freeze.

**Comment by razvan-panda** [comment]
I used `C-g` to unfreeze Spacemacs (multiple times, as each run of the command canceled a symbol load freeze/cpu hog) and after that I ~~could no longer reproduce the problem~~ just reproduced it again. The message buffer after cancelling the loading does mention that all of the symbols have been loaded (including the cancelled ones):

    Loading symbols for Network.Wai.Handler.Warp...done
    Loading symbols for Network.Wai...done
    Loading symbols for Network.HTTP.Types.Header...done
    Loading symbols for Network.HTTP.Types...done
    Loading symbols for Database.HDBC.PostgreSQL...done
    Loading symbols for Database.HDBC...done
    Loading symbols for Data.ByteString.Lazy.Char8...done

**Comment by syl20bnr** [comment]
I think it is expected on a big project, but it should happen only once after each restart of Emacs.
cc @chrisbarrett @bjarkevad

**Comment by razvan-panda** [comment]
It seems the company-ghc plugin is failing regardless of wether autocomplete hangs or not:

    * company-ghc backend found: (company-ghc company-dabbrev-code company-yasnippet)
    * automatic scan module is enabled
    * ghc-boot process seems to have failed

    Module                                  Alias               Candidates
    -------------------------------------------------------------------------------
    Network.Wai.Handler.Warp                W                        nil
    Network.Wai                             -                        nil
    Network.HTTP.Types.Header               -                        nil
    Network.HTTP.Types                      -                        nil
    Database.HDBC.PostgreSQL                HP                       nil
    Database.HDBC                           H                        nil
    Data.ByteString.Lazy.Char8              LBS                      nil
    Prelude                                 -                        0

Running `ghc-mod debug boot Main.hs` ends with no errors.

**Comment by bjarkevad** [comment]
@razvan-panda which GHC version are you running? I've personally seen the issue with the newest Haskell platform on Arch Linux. It seems to work with GHC 7.10.1.

**Comment by razvan-panda** [comment]
@bjarkevad I only tested with 7.8.3 and 7.8.4 (can't use 7.10.1 yet). The problem is that it does not say exactly why the boot process fails, and running ghc-boot in the folder outputs a list of things without errors.

**Comment by bjarkevad** [comment]
I saw the exact same thing, but I was unable to resolve the issue. If you
figure anything about, please report back!

**Comment by razvan-panda** [comment]
I will gladly report back if I figure it out.

**Comment by buckie** [comment]
@bjarkevad @razvan-panda I had this issue for a while, which was fixed about an hour ago -- did you happen to have a library & an executable that depended on that lib in your cabal file? 

https://github.com/kazu-yamamoto/ghc-mod/issues/501#issuecomment-127067097

**Comment by buckie** [comment]
Here's what I did to fix the issue, which I stole from company-go's readme -- add this to your `dotsmacemacs/config` section:

```
  (setq company-tooltip-limit 20)                      ; bigger popup window
  (setq company-idle-delay .3)                         ; decrease delay before autocompletion popup shows
  (setq company-echo-delay 0)                          ; remove annoying blinking
  (setq company-begin-commands '(self-insert-command)) ; start autocompletion only after typing
```

**Comment by d12frosted** [comment]
@razvan-panda Hm. Looks like a pain issue. I couldn't reproduce it. Since 'a lot of' stuff changed lately in `ghc-mod`, could you check if it's still happening?

**Comment by razvan-panda** [comment]
@d12frosted Haven't used Spacemacs in a while as it got slower than IDEs with all the plugins and too many issues like this one. It might be best to close the issue until someone else reproduces it. Thank you
