### ISSUE TITLE
ad-handle-definition errors at startup

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#192]
When spacemacs starts the following lines are logged in `*Messages*`:

> ad-handle-definition: `evil-mode' got redefined

> ad-handle-definition: `tramp-read-passwd' got redefined

**Comment by yangj1e** [comment]
I find
> ad-handle-definition: `tramp-read-passwd' got redefined

since upgrade to 0.103.0

**Comment by screamish** [comment]
I too now get this after upgrading to 0.103.0

```
ad-handle-definition: `find-tag-noselect' got redefined
ad-handle-definition: `tramp-read-passwd' got redefined
```

**Comment by jvillasante** [comment]
I have these two warnings on Message buffer upon startup:

ad-handle-definition: `find-tag-noselect' got redefined
ad-handle-definition: `tramp-read-passwd' got redefined

I notice that this don't has anything to do with my own configurations, so I silenced them with:

(setq ad-redefinition-action 'accept)

in dotspacemacs/init function. But the question remains. Is this bad, some kind of bad error or would I be ok silencing them?

**Comment by Malabarba** [comment]
I think it's not an error. It's just the advice system telling you that the definition of an advised function changed and so the advice has been applied to the new definition.

**Comment by forrestchang** [comment]
I find

> ad-handle-definition: `tramp-read-passwd' got redefined

since upgrade to 0.103.5

**Comment by beanwonder** [comment]
I got this warning too when startup
> ad-handle-definition: `tramp-read-passwd' got redefined

version 0.103.5

**Comment by CestDiego** [comment]
I always got that but only as a message, never a warning. Is this too critical?

**Comment by TheBB** [comment]
I don't think this is a bug. We can consider silencing the warnings as @jvillasante mentioned.

**Comment by Nicholas-Mitchell** [comment]
Someone else has the same solution here: http://andrewjamesjohnson.com/suppressing-ad-handle-definition-warnings-in-emacs/

They mention where the warnings come from.
