### ISSUE TITLE
Yasnippet expand should select first snippet automatically

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#1922]
Right now when I hit `M-/` to expand a snippet key with multiple snippets, a dropdown menu appears.

I have to then, click `down` twice to select the first snippet, and then hit `RET` to expand it. 

The first snippet should be selected by default so that one can at least `M-/ RET` to expand it.

**Comment by StreakyCobra** [comment]
@gnzlbg Do you have an example of a mode and snippets to reproduce this?

**Comment by TheBB** [comment]
Try for example `df M-/` in elisp mode.

**Comment by StreakyCobra** [comment]
Ok, thx :-) I see it now

**Comment by TheBB** [comment]
I just fixed it, actually. https://github.com/syl20bnr/spacemacs/commit/ee2442d8ce5772592525e3241b5dd2dddf6b0674

See... autumnal cleanup is working!

**Comment by gnzlbg** [comment]
nice :)
