### ISSUE TITLE
There should be a way to opt-out of Yasnippet default snippets

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#1923]
When I create a private snippet, is because I intend to use it often. That is, I want to write the snippet key, hit `M-/` and have it expanded. 

However, when the key has a name clash with one of the default snippets, I have to `M-/`, hit `down` multiple times to select the snippet, and then hit `RET`. 

This is a real pain at least with c++ default snippets since they have keys with extremely common names that I would like to also use (`for`, `once`, `ns`, `struct`, ....).

**Comment by tuhdo** [comment]
You can customize `yas-snippet-dirs` to exclude the default snippet dir. If you want to use other snippets, then after deleting the path in `yas-snippet-dirs`, then clone the snippet in this [repo](https://github.com/AndreaCrotti/yasnippet-snippets) somewhere and delete `c++` snippets there. Then add the path to that directory to `yas-snippet-dirs`.

**Comment by CestDiego** [comment]
Why not contribute back to the upstream snippets?

**Comment by syl20bnr** [comment]
I understand the pain since snippet are meant to be quick.
At spacemacs level it would be really complex to offer such functionalilty, the dumbiest solution would be to add a layer variable to opt out the default snippets but what if you just want to opt out for a specific language ?
So I think like @CestDiego, it is an issue to resolve at the package level, there are a lot of possilities so opening a discussion upstream would be a good start.

**Comment by gnzlbg** [comment]
@CestDiego The snippets I use are already in the default C++ snippets. For example the "official" `ns` expands to:

```c++
namespace name {

}
```

while my version expands to 

```c++
namespace name {

}  // namespace name
```

and probably somebody elses version expands to:

```c++
namespace name
{

}
```

@syl20bnr I think that a variable to opt-out of the default snippets would be a great start (it is simple and it would work for me). One could add a variable for each default snippet package to make it more fine grained in the future if there is interest.

I will open [a discussion upstream](https://github.com/capitaomorte/yasnippet/issues/585).

**Comment by gnzlbg** [comment]
@tuhdo 

I've put the following in my `.spacemacs`:

```elisp
(setq-default yas-snippet-dirs '("~/.emacs.d/private/snippets"))
```

However, yasnippet still loads snippets from `.emacs.d/spacemacs/extension/yasnippet-snippets/c++-mode`.

**Comment by jasoncyu** [comment]
why don't you just use `setq` at the end of your `dotspacemacs/config` instead of `setq-default`? nothing should be writing to that variable's value after `dotspacemacs/config`

**Comment by person808** [comment]
> However, yasnippet still loads snippets from ~/.emacs.d/spacemacs/extension/yasnippet-snippets/c++-mode.

I believe those were removed a while ago. It should be safe to delete the folder.

**Comment by gnzlbg** [comment]
@jasoncyu 

> why don't you just use setq at the end of your dotspacemacs/config instead of setq-default? nothing should be writing to that variable's value after dotspacemacs/config

I tried this too but the problem persists.

@person808 
> I believe those were removed a while ago. It should be safe to delete the folder.

Thanks, that fixes it.

**Comment by evgeniysharapov** [comment]
I know the issue is closed but I just stumbled upon this problem myself. What I did is before loading yasnippet I create `.yas-skip` file inside `c++-mode` directory with default snippets

    (let ((file (concat yas-installed-snippets-dir "/c++-mode" "/.yas-skip")))
      (when (not (file-exists-p file))
        (write-region "" nil file)))
