### ISSUE TITLE
Easy Cross Platform Installation? 

### ISSUE THREAD

**Issue by serapath** [syl20bnr/spacemacs#1927]
For [`slap-editor`](https://github.com/slap-editor/slap), i just need to type
* **$> `npm install -g slap`**  
on any operating system and then open the `slap editor` by typing e.g.
* **$> ` slap .`**  
in my terminal.

Compared to that, `Spacemacs` seems to be quite complex to set up (**see [`here`](https://github.com/syl20bnr/spacemacs#prerequisites)**). For a first time user, who transitions from an IDE like `Visual Studio` or `Eclipse` or even an editor like `sublime text2`, it looks pretty scary.

**Comment by tuhdo** [comment]
By most OSes, do you mean Windows as well?

**Comment by serapath** [comment]
That would be pretty cool. And even though i didn't try, it might work in windows.
If not immediately, then maybe after the installation of [git-scm](https://git-scm.com/) on windows which can transform your `cmd` into something more "unixy"

**Comment by syl20bnr** [comment]
I don't know if it is complex, in a nutshell it is two commands:
- unzip or install emacs binaries distribution from the OS package manager
- clone spacemacs

**Comment by louy2** [comment]
I am using Spacemacs on Windows as my primary editor for some time. It's the same set and go.

Don't get spoiled by the package managers. For me they are conveniences, not replacement for good old manual copy paste.

**Comment by TheBB** [comment]
At the moment it's probably not feasible to provide a simpler way of installation.

I'm closing this issue due to age. Please open a new one if you want to start a fresh discussion.
