### ISSUE TITLE
Magit-Cherry keybinding not working properly

### ISSUE THREAD

**Issue by liujoey** [syl20bnr/spacemacs#1928]
Develop branch:
in magit cherry picking buffer, it supposed to press `A` to pick a commit or `a` to apply the commit changes to working tree, and some others like `Tab` to toggle section, `Ret` to visit and `Space` to view an item. For now in spacemacs, none works.

The work around is press `Ctrl-z` to switch to emacs mode first, and use emacs way to navigate, then all keys mentioned above should work as expected.

**Comment by CestDiego** [comment]
Also, using `y` now is evil-yank and `Y` is undefined so no way to cherrypick either.

**Comment by syl20bnr** [comment]
This is a big issue, I have to find an elegant way to support this.

**Comment by justbur** [comment]
Fixed in #3578
