### ISSUE TITLE
Feature Request: eyebrowse alias within modeline

### ISSUE THREAD

**Issue by rphillips** [syl20bnr/spacemacs#1935]
It would be slick to have the alias from eyebrowse within the spacemacs modeline. The benefit would be  to quickly see which project is being worked on.

**Comment by CestDiego** [comment]
^ this

**Comment by syl20bnr** [comment]
I would see it as the first element of the modeline to replace the actual workspace number.

**Comment by TheBB** [comment]
I implemented this in spaceline. https://github.com/TheBB/spaceline/commit/65e978a4aa0801b270bbd9928f9680a87909ef89
