### ISSUE TITLE
Use magit-status for git project

### ISSUE THREAD

**Issue by QiBaobin** [syl20bnr/spacemacs#1943]
When opening a project in git from *spacemacs* buffer or calling helm-projecttile-switch-project, could we open it in magit-status?

**Comment by cpaulik** [comment]
You can already do that. Press `SPC p p` then select your project. Do not press `RET` but `F3`.

There are also other options for opening a project see `C-z` in helm-projectile

**Comment by tuhdo** [comment]
You can set `projectile-switch-project-action` to `magit-status`, so whenever switching to a project it opens a `magit-status` buffer.

**Comment by QiBaobin** [comment]
Thank you all. Glad to see the options to do that.
