### ISSUE TITLE
Colorize cursor according to state not working

### ISSUE THREAD

**Issue by Kernael** [syl20bnr/spacemacs#1944]
Cursor color doesn't change with state although `dotspacemacs-colorize-cursor-according-to-state` is correctly set to `t` (never did since I use Spacemacs in fact). Any idea where it could come from ?

**Comment by syl20bnr** [comment]
Are you in the terminal ? This feature works only in the GUI for now.

**Comment by Kernael** [comment]
Indeed, had no idea it was for GUI only, thank you.

**Comment by syl20bnr** [comment]
I flag it as documentation, we have to mention it in the docstring of the variable.
