### ISSUE TITLE
ssh connection struggling 

### ISSUE THREAD

**Issue by dab** [syl20bnr/spacemacs#1945]
Trying to discover `emacs` area. Usually I'm working on my remote server over ssh. With vim I easy can connect with or without plugins, like `:VimFiler ssh://host`. Tried to do thing like this in `spacemacs` with no success. 

Used `C-x C-f /:ssh:host:` — got `Waiting for remote prompts` message and then `timeout error`. Also tried `SPC-f-f/:ssh:host` with same result. At the same time I can use ssh in vim, so the problem is not the network itself. 

How I can make the ssh with `spacemacs` working?

Thanks.

**Comment by cpaulik** [comment]
The correct syntax should be `SPC-f-f` `/ssh:host:/path/to/file`

See the [quickstart guide](http://www.emacswiki.org/emacs/TrampMode) for the various syntax possibilities.

I've got the host in my `.ssh/config` file and `helm` offers autocompletion for the hosts.

**Comment by dab** [comment]
@cpaulik thanks! tried this combination already, but it's hanging on and does not respond to keys except `C-g`. Reading troubleshooting guide now.

**Comment by syl20bnr** [comment]
Do you use any special shell on the remote host ?

**Comment by dab** [comment]
@syl20bnr using zsh there, tried to add lines from `tramp` troubleshooting guide to `.zshrc` with no success yet.

**Comment by dab** [comment]
@syl20bnr removed `prompt` on remote host and this fixed connection timeout issue.

**Comment by puffnfresh** [comment]
I have this problem - I do not want to remove prompt from the remote host. What we do to fix this?

**Comment by puffnfresh** [comment]
I've read the Emacs wiki and copied a solution from http://www.emacswiki.org/emacs/TrampMode#toc6

```zsh
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ '
```

**Comment by tfiala** [comment]
@puffnfresh This one worked better for me on my end, adding it to the top of the .zshrc file:
```
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return
```

I was still hitting a problem with my oh-my-zsh setup using just the first option.
