### ISSUE TITLE
SPC h t is undefined

### ISSUE THREAD

**Issue by doubleagent** [syl20bnr/spacemacs#1948]
Spacemacs produces this message when trying to run the vim tutor.  Just chose Spacemacs yesterday as a base configuration and wanted to learn how to use it.

**Comment by cpaulik** [comment]
The correct keybinding is `SPC h T`. Does this work?

**Comment by cpaulik** [comment]
You can see the defined keybindings by waiting a bit. then the guide-key buffer should show you all the keybindings.

**Comment by doubleagent** [comment]
Ah yes.  I am a dumbass.  Thank you.
