### ISSUE TITLE
"Unable to check for new version"

### ISSUE THREAD

**Issue by crinklywrappr** [syl20bnr/spacemacs#1949]
Spacemacs produces this message on startup.  Windows platform.

**Comment by syl20bnr** [comment]
What's your spacemacs version ? I thought I fixed this in `0.102.2`.

**Comment by doubleagent** [comment]
0.102.2.

**Comment by porzechowski** [comment]
Same on Linux, with Emacs 24.5.1 and Spacemacs 0.103.2. These are the last lines of my ```*Messages*``` buffer after startup:
```
Start checking for new version...
Open the quickhelp.
Spacemacs is ready.
Unable to check for new version.
ad-handle-definition: `tramp-read-passwd' got redefined
```

**Comment by doubleagent** [comment]
Still a problem on 0.103.2

**Comment by porzechowski** [comment]
On the other hand, I do not have this problem on Mac OS X. I use vanilla Emacs 24.5 from homebrew with Spacemacs 0.103.2. I have shell and haskell layers enabled for both Linux and OS X installations.

**Comment by porzechowski** [comment]
@syl20bnr, is there any way I can help you with tracking this bug? I don't know (E)Lisp, though.

**Comment by doubleagent** [comment]
Same offer here.  I would have indicated that earlier but I assumed it was implicit.

**Comment by doubleagent** [comment]
This only occurs on Windows if I install spacemacs by unzipping one of the releases posted on github eg https://github.com/syl20bnr/spacemacs/releases

If I do the quickinstall option then there aren't any problems.  The quickinstall instructions aren't "out-of-the-box copy-pastable" for Windows users, though.

After digging about in core-release-management I noticed that version checking appeared to assume git access to master.  I suggest a simpler approach if spacemacs is going to continue offering zipped releases.

...or maybe at least note it in the FAQ

**Comment by porzechowski** [comment]
@doubleagent, and very likely my problems were related to having git compiled without libcurl ssl support. Anyways, after reinstallation of Spacemacs and using properly compiled git, I don't see this problem now.

**Comment by fladd** [comment]
I have this on a MacBook, after updating to El Capitan. Any idea what causes this?

**Comment by StreakyCobra** [comment]
Can someone provide a backtrace of this (`emacs --debug-init` and/or `SPC t D`)?

**Comment by mitchellgordon95** [comment]
Same problem. Not sure if this is relevant, but after startup I always have a buffer named "git-get-current-branch" that says

fatal: Not a git repository: ../.git/modules/.emacs.d

**Comment by et2010** [comment]
I have the same problem with 0.104.2, windows platform.
I run ```git status``` and it shows:
```fatal: bad config file line 1 in .git/config```
So it was caused by a broken git configuration file. So I reclone spacemacs to a temporary location, copy the new config file to overwrite the broken one, and problem solved. Hope this helps.

**Comment by StreakyCobra** [comment]
Thanks @et2010 for the information.

@syl20bnr All problems here seems to were `git`-related issues, but the question here is relevant:

> After digging about in core-release-management I noticed that version checking appeared to assume git access to master. I suggest a simpler approach if spacemacs is going to continue offering zipped releases.
> 
> ...or maybe at least make a note in the FAQ.

Do we:

1. Explicit in the documentation than an `git clone` is needed for version check and update (and eventually add a guard for it).
2. Update version-checking code to work with non-git `~/.emacs.d`

**Comment by StreakyCobra** [comment]
After discussing this on gitter with @syl20bnr, for now only `git` version of `~/.emacs.d` folder are supported for checking/update. This should be documented where the `update` mechanism is presented (at least in the `README` and in the documentation.)

**Comment by kpanic** [comment]
Hi, more info:
If I click on "Update Spacemacs" I get:
```
Getting version information...
An error occurred while switching to version 
```

**Comment by DCPRevere** [comment]
@kpanic, Have you tried specifying `0.200` as the version?

**Comment by kpanic** [comment]
now yes, seems to work! Thanks!
