### ISSUE TITLE
Documentation: Problem with customizing evil-escape-key-sequence

### ISSUE THREAD

**Issue by robbinch** [syl20bnr/spacemacs#1960]
In https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#escaping, instructions for changing escape key sequence does not work properly for me. I changed to "ht" (I'm using dvorak layout), and everytime I type 'f' in insert mode, 'h' appeared.

What works for me is using kbd():
(defun dotspacemacs/init ()
  (setq-default evil-escape-key-sequence (kbd "ht")))

**Comment by syl20bnr** [comment]
I cannot reproduce it, maybe a restart of Emacs was needed ?

**Comment by robbinch** [comment]
Restart of Emacs did not work for me. Perhaps it only occurs on my NixOS setup. Closing this.
