### ISSUE TITLE
org layer does not install properly

### ISSUE THREAD

**Issue by sotte** [syl20bnr/spacemacs#1965]
I was updating spacemacs and afterwards I had some trouble (missing bindings, functions, no agenda anymore) with org and spacemacs. While trying to debug it I found out that even with a fresh install (no `~/.spacemacs`, no `~/.emacs.d`) installing org yields errors.

So here is how you can reproduce it:
```
git clone --recursive https://github.com/syl20bnr/spacemacs ~/.emacs.d
emacs &  # start spacemacs for the first time; installing lots of stuff; use `vim` editor style
# add `org` to `dotspacemacs-configuration-layers`, then `SPC f e R`
```
This results in lots of warning like the following (don't know if that is bad or not)
```
In evil-org-recompute-clocks:
evil-org.el:70:14:Warning: `next-line' used from Lisp code
That command is designed for interactive use only
```
and errors like
```
Compiling file /home/stefan/.emacs.d/elpa/org-20150608/ox-ascii.el at Fri Jun 12 13:38:35 2015
ox-ascii.el:31:1:Error: Symbol's value as variable is void: org-list-allow-alphabetical
```
I guess something is already fucked here.
If I open an org file, add it to the agenda list `C-c [`, and start the agenda view `C-c a` I get the error: `invalid function: ord-with-silent-modifications`.

Pretty clueless about how to fix it. I also tried `develop` with the same results.

**Comment by syl20bnr** [comment]
Check this #1807
Also try to remove the org directory in `~/.emacs.d/elpa`, you can also try to reinstall the whole thing by deleting the entire `~/.emacs.d/elpa`.

**Comment by sotte** [comment]
Regarding #1807: I started `emacs -q` and installed the org package via elpa. Then I started spacemacs which installed some more org packages which threw an error while compiling. However, org is installed, the agenda is being displayed but the spacemacs bindings for orgmode don't exist.

@syl20bnr I already removed the org and elpa folder, didn't help. Is there any other folder that has build/install artifacts that potentially break this?

I tried everything with emacs 24.3 and 24.5.

Also, this happens with a pristine spacemacs install (master and develop) with default config. In both scenarios when adding `org` to `dotspacemacs-configuration-layers` and installing it(`SPC f e R`) compiling fails.

**Comment by sotte** [comment]
Am I really the only one who can't install and use org? I can reliably reproduce this error and it (sadly) renders spacemacs invaluable to me.

**Comment by sbergot** [comment]
I had the same issue this morning. The message was `Error: Symbol's value as variable is void: org-list-allow-alphabetical` while compiling `ox-gfm`. I ran `git clean -fdx`, commented the three lines mentioning this library in `contrib/org/packages.el`, restarted emacs and org-mode started working again.

**Comment by sbergot** [comment]
actually now org-mode loads correctly but I am also getting the bug mentionnned in #1807: http://comments.gmane.org/gmane.emacs.orgmode/70880

**Comment by sbergot** [comment]
upgrading to emacs-24.5 from 24.3 fixed this issue

**Comment by sotte** [comment]
My workaround to get a more or less working org: `dotspacemacs-excluded-packages '( org-pomodoro)`.

(I'm on develop. Not tested on master.)

**Comment by syl20bnr** [comment]
We have to figure out why pulling org from the ELPA repo is problematic.
@sotte what's your emacs version ?

**Comment by sotte** [comment]
I tried 24.3 and 24.5 and got the same problems when installing org. I didn't test 24.4.

**Comment by EricCrosson** [comment]
I have been experiencing this problem for ages, with stock emacs. The issue comes from the source of org - not all versions floating around are identical. 

To reiterate, the issue is not with the emacs version but with the content of the downloaded org package - one of the org mirrors has the issues with `org-with-silent-modifications`. Historically, fixes for me included custom-patching my downloaded version to containing the necessary defuns or try different sources until you find one that isn't buggy and remember to use that one. I definitely forgot which version I marked as 'cleared'... but one of them, somewhere, doesn't have this issue. If elpa/melpa are on the offending list, try cloning from git.

@sotte can you give us information about your version of org? Let's compare.

**Comment by sotte** [comment]
@EricCrosson I don't think I can give a proper answer. After lot's of trial and error I ended up manually downloading org, changing some files, excluding some other packages, etc.. I'm not willing to touch anything because I'm afraid I'll break it. Sorry.

**Comment by sotte** [comment]
Of course I ended up trying to reinstall it :) Here are the org folders and versions `in elpa/`

```
org-20150727/
org-bullets-20140918.1137/
org-pomodoro-20150621.552/
org-present-20141109.1756/
org-repo-todo-20141204.1341/
```

As before, org is not working properly. I'm currently using the develop branch and emacs 24.5.1.

**Comment by sotte** [comment]
When I exclude `org-bullets` and `org-pomodoro` I get working orgmode.

**Comment by andrewsanchez** [comment]
I had the same problem.  Deleting `elpa/org/` and reinstalling seems to have done the trick for me.

**Comment by geo7** [comment]
@sotte is this all good now?

**Comment by sotte** [comment]
I stopped using spacemacs because of the problems with orgmode.

I reinstalled the stable version of spacemacs a few days ago and it seems to work now. Thanks!

**Comment by morgado-jb** [comment]
I'm also having this bug.
I'm using the latest spacemacs version, installed today.

Org mode fails with the described bug in emacs-mac 24.3, version and in emacs version 24.5
