### ISSUE TITLE
Should helm be deferred?

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#1967]
I don't know about others, but the first command I want to run when I open spacemacs is almost always something that uses helm. Deferring helm introduces a small, but noticeable delay with that first command. It seems to me that if this is the common usage pattern helm should be loaded right away (despite the slightly longer load time). It was annoying me enough that I disabled the deferral mechanism for helm, and I think the experience is better.

Sorry for nitpicking.

**Comment by syl20bnr** [comment]
You are right :-)

One of the explanation: in the emacs community we have an inferiority complex about loading time and helm is not very quick to load, it is even worth on a windows machine.

Another explanation is about marketing: while spacemacs is fairly optimized and the loading time is big then people will have a bad perception of it and we will see it on the screenshots.

We could make an exception for helm and simply remove the number of seconds displayed after emacs is loaded but I don't want to do that to keep a fast as possible startup time. Then the explicit metric tries to remove the biased perception by showing explicitly that even if it's not instantaneous "it's only 2 seconds" and often better in the terminal (I had sub-second loading time in the terminal with raw spacemacs). It also shows that we care about loading time and we try to optimize it as much as we can.

We can imagine a feature to disable the lazy-loading per package but it may be some work to make it slick and general enough.

**Comment by justbur** [comment]
I never expected such a detailed answer :-), and I see your point. 

In that case, would changing `:defer t` to `:defer 1` (or some small number) at least bump helm up in priority so it doesn't get stuck behind other packages?

**Comment by syl20bnr** [comment]
Oh `:defer n` does this ? `:defer t` packages are loaded after any `:defer n` ? Nice :-)

**Comment by justbur** [comment]
I could be wrong, but here's what the documentation says 

> Defer loading of a package -- this is implied when using
>   `:commands', `:bind', `:bind*', `:mode' or `:interpreter'.
>   This can be an integer, to force loading after N seconds of
>   idle time, if the package has not already been loaded.

**Comment by syl20bnr** [comment]
Ok so it is not really a priority queue, it is just a timer value :-( I don't think it has any value when the package is requested before the time out.

**Comment by syl20bnr** [comment]
I have to test it, this is some kind of middle ground between user perception and marketing bullshit :-)

**Comment by justbur** [comment]
Yes, not strictly speaking. I interpreted it as a hacky way to get helm to load before other packages.

**Comment by justbur** [comment]
I would need someone else to confirm this, but it looks like all `:defer t` does is to setup autoloads for the package, meaning the package will never get loaded if you just sit and do nothing. I waited for 30 secs after starting spacemacs and then ran a helm command and still got the delay, which agrees with this theory. 

In that case, `:defer n` would load helm while I'm doing nothing.

**Comment by cpaulik** [comment]
Since a recent update `SPC f f` loads pretty much instantly for me. How long does it take for you @justbur ?

**Comment by syl20bnr** [comment]
@cpaulik recent update of helm or spacemacs ? It could be the effect of broken lazy loading of helm :-)

**Comment by justbur** [comment]
@cpaulik Not long, but I'd rather it load instantly like it does the second time I use the command. This is on my windows laptop at work, so that might be a factor. 

I just thought there might be a way to improve the experience

**Comment by justbur** [comment]
@syl20bnr Now that I think about it, if I'm right about how `:defer t` works then I think a lot more packages should use `:defer n` (for some appropriate `n`) instead. My reasoning is that if I launch emacs in the background (or as a daemon), emacs should take advantage of the time I'm not using it to load all of those packages that I expect to use at some point. No? 

I had assumed earlier that's how `:defer t` would work, but I don't think it is.

**Comment by syl20bnr** [comment]
Given the number of packages I surely don't want to play with `:defer n`. Maybe for some key packages like helm, I have to try it,

**Comment by CestDiego** [comment]
There is also the `:idle` tag for packages that are *not* that utterly important.

**Comment by justbur** [comment]
I think `:idle` is gone now

**Comment by cpaulik** [comment]
@syl20bnr I think it was a recent update of helm, but I might be mistaken, it could also have been a update of use-package. Because until recently my org-config was loaded when helm was started the first time which was strange.

Anyway, I have helm set to load after 5s of idle time using the `:defer` keyword and it works nicely.

**Comment by syl20bnr** [comment]
I pushed `:defer 1` in develop so users can test it.

**Comment by justbur** [comment]
`:defer 1` has been working fine for me. I'll close this for now, unless someone else wants to chime in.
