### ISSUE TITLE
Python 3 Company error

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#1973]
Code : 

```python
#! /usr/bin/python3.4

import requests
import bs4

res = requests.get('http://google.com/search?q={}'.format(sys.argv[1:]))
res.<error comes up here> 
```

Error : 

http://i.imgur.com/gPeRXst.png

This occurs with the above code after typing `res.`, 

I've been told to ask if you know @CestDiego :)

**Comment by CestDiego** [comment]
This was reported upstream some time ago, https://github.com/proofit404/anaconda-mode/issues/88 . Sry m8 ;_;

**Comment by CestDiego** [comment]
@geo7 did you ever hear back from this? D:

**Comment by TheBB** [comment]
The appropriate upstream is here: https://github.com/davidhalter/jedi/issues/592

Closing this since it seems a minority problem which is not caused by us.
