### ISSUE TITLE
Add clojure-semantic support to clojure layer

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#1977]
https://github.com/kototama/clojure-semantic

Currently, the repository doesn't have a MELPA listing, so I'm not sure what the correct way to add it would be. Just bundle it in the layer? Anyway, it's useful if you use something like `lispy`, and its cumbersome to have it sitting somewhere else on your disk and manually load it.

**Comment by tuhdo** [comment]
A while ago Spacemacs has a plan to use [Quelpa](https://github.com/quelpa/quelpa) to simplify the process of installing packages, so there's no distinction between a package and an extension anymore. You can see the issue here: https://github.com/syl20bnr/spacemacs/issues/5. Probably after this Org conversion is taken care of, we should start migrating to [Quelpa](https://github.com/quelpa/quelpa).

**Comment by syl20bnr** [comment]
I have to work on the merge of extensions and packages first. Then we will be able to add solutions like Quelpa. The first step is something I can start to tackle in 0.104.0. For the current release I want to finisher org migration and the update mechanism of Spacemacs. I'm 60% done with the update, we can already update Spacemacs from the mode-line button.

**Comment by StreakyCobra** [comment]
@sooheon AFAIK you can now install packages from github, as shown here: https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#packagesel

You should be able to include it in the clojure layer :relaxed:

**Comment by sooheon** [comment]
Thanks. Got it working with the following if anyone else is curious, I'll hold off on a PR until there is more actual demand, due to the hacky nature of the file loading currently.

    (use-package clojure-semantic
        :defer t
        :init
        (with-eval-after-load 'clojure-mode
          (load "~/.emacs.d/elpa/clojure-semantic-20130323.2/clojure.el")))

**Comment by TheBB** [comment]
Maybe someone can push upstream to turn it into a MELPA package with a suitable name?
