### ISSUE TITLE
[BUG]vim-empty-lines-mode && org export to html

### ISSUE THREAD

**Issue by tshemeng** [syl20bnr/spacemacs#1978]
when enable `vim-empty-lines-mode` package , export an org file to html, code blocks  with a lot of `~` in tail
![_001](https://cloud.githubusercontent.com/assets/8343797/8144313/dc4ed4e4-1209-11e5-90e9-f475e54ce6cb.png)

**Comment by sooheon** [comment]
vim-empty-lines actually has quite a few issues, and I'm considering asking to take it out of spacemacs. It looks better, but there are problems with folding in org, navigation and recentering using `g` and `z`, company candidate list frontend, and I guess this problem as well. You can submit a report upstream, but the developer has been completely unresponsive after the initial release as well.

**Comment by syl20bnr** [comment]
I'm actually using it but the reason why I did not replaced `vi-tilde-fringe` it the complexity of the package which is a lot more complicated than `vi-tilde-fringe`. The implementation is prone to multiple side effects that will increase this complexity. In spacemacs we have a patched version of it which fixes the company issue.

I'm not sure we should remove it though. We can wait a bit more and see what happen with this package.
