### ISSUE TITLE
helm-spacemacs "eval-buffer: Cannot open load file: no such file or directory, f"

### ISSUE THREAD

**Issue by mrmargolis** [syl20bnr/spacemacs#1980]
On develop SPC f e h  is not working for me.  I see
"eval-buffer: Cannot open load file: no such file or directory, f"

The issue persists after completely removing spacemacs .emacs.d and .spacemacs) and starting fresh on develop.  Helm is working in other scenarios, like helm-recentf and spacemacs/helm-find-files.

**Comment by TheBB** [comment]
A workaround for now is to add `f` to your `dotspacemacs-additional-packages`.

**Comment by person808** [comment]
This is fixed by #2046
