### ISSUE TITLE
C-f C-b not working in paradox-list-packages 

### ISSUE THREAD

**Issue by eefano** [syl20bnr/spacemacs#1982]
At the moment the only way to page up/down in paradox is by using PgUp and PgDn keys. Adding more consistent vim keybindings would be nice. thank you for spacemacs!

**Comment by syl20bnr** [comment]
In _evilified_ buffers we try to shadow as few bindings as possible. Did you try the `scroll` micro state on `SPC n ,` or `SPC n .` ?

**Comment by eefano** [comment]
Thanks, but I have some problems with that:
1) it's not documented anywhere
2) it doesn't work: the micro state gets activated but the keys suggested for scrolling don't work as expected. I tried some combinations of , . < > but with no avail. 
3) It's still inconsistent, but it's just my opinion, man :)

**Comment by StreakyCobra** [comment]
As of today `C-f` and `C-b` are working both on `develop` and `master`. Vim `C-d` and `C-u` are also available. I'm closing this issue then, but feel free to open a new one in case of trouble :smiley:

**Comment by eefano** [comment]
Thank you! Sorry for the late feedback, good work!
