### ISSUE TITLE
Cannot insert space after C-rx in insert mode

### ISSUE THREAD

**Issue by duerrp** [syl20bnr/spacemacs#1983]
After pasting a register in insert mode via C-r, typing space triggers the leader command instead of inserting a space. Any other character works fine.

Any idea how to debug this?

Best
Peter

P.S. keep up the awesome work, I love spacemacs!

**Comment by syl20bnr** [comment]
Thank you for the report, was caused by the paste micro-state which was triggered after the paste. Should be fixed in develop.
