### ISSUE TITLE
semantic layer breaks major-mode-leader-key in elisp-mode

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#1985]
In vim mode
0. set `dotspacemacs-major-mode-leader-key` to ","
1. start spacemacs
2. press <kbd>SPC f e d</kbd> to open .spacemacs file (or any other elisp file)
3. press <kbd>,</kbd>

When only `emacs-lisp` layer is installed that brings up the major mode guide-key.

When both `emacs-lisp` and `semantic` layers are installed that gives a `No previous search` error instead.

**Comment by syl20bnr** [comment]
I cannot reproduce it :-(

**Comment by mindphaze** [comment]
I get this behavior also but I haven't tracked down what is causing it.  For some reason the leader key is being bound to evil-repeat-find-char-reverse no matter what file I'm in.  I have a very similar .spacemacs file at work and home but things work properly at work but give me this same behavior at home.  The only major difference is one is emacs 24.4 and the other is 24.5

**Comment by mindphaze** [comment]
Ok, my problem turned out to be I had a package name misspelled.  I had emacs-lisp spelled emacs-elisp.  The misspelling I don't think was the actual culprit but the fact that emacs-lisp not being loaded is somehow related to the leader key not functioning properly.

**Comment by tko** [comment]
Seems to be working now, no idea why.

**Comment by hhxjzyr** [comment]
I encountered the same problem, I found maybe it was because you chose a wrong main mode.
I fixed it by switch to the right main mode (my file is .tex file and I switch to the right Tex-latex-mode)
