### ISSUE TITLE
SPC / -related keybindings with grep broken in develop

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#1987]
<kbd>SPC /</kbd> just gives an error `Wrong type argument: commandp, helm-project-do-grep`

**Comment by justbur** [comment]
It's a bug in the smart search function at the moment. `SPC psg` should work. The function you want to call is `helm-projectile-grep`.

**Comment by tko** [comment]
On further note <kbd>SPC b /</kbd>, <kbd>SPC s /</kbd>, and <kbd>SPC f /</kbd> are also giving similar errors.

(Is "s /" intentionally bound to same function as "b /"? The ag functions are different.)

**Comment by justbur** [comment]
The basic problem is that @syl20bnr recently added/changed the search functions using functions defined in helm-ag for ag, pt and ack. The grep functions for helm are defined elsewhere and don't map one-to-one with the helm-ag ones. Your smart search is defaulting to grep and looking for the non-existent functions. We just need to add appropriate ones for grep.

**Comment by tko** [comment]
Right, I figured as much, but I don't know enough elisp to quite figure out what was going on. Your patch is a good pointer.

**Comment by syl20bnr** [comment]
It requires the last version of helm for grep. For the other tools it should be ok.

**Comment by syl20bnr** [comment]
Ah yes grep is broken for project scope, it needs a wrapper `helm-project-do-grep`.
I don't really checked grep because for project at is way superior and easy to install, on windows or is really easy to install as well (made in go).

**Comment by syl20bnr** [comment]
Should be fixed in develop, thanks @justbur !

**Comment by tko** [comment]
FWIW for _grep_ the keybindings are working.

In the meantime I installed 'ag' to see what the fuzz is all about and now it seems all the "b /", "s /", and "f /" bindings are failing with `Wrong type argument: commandp, helm-buffers-do-ag` and similar... (I'm not actually using any of those, just thought to try them out.)

**Comment by syl20bnr** [comment]
Should be better in develop now.
Don't forget to check the new bindings: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#with-an-external-tool
