### ISSUE TITLE
Spacemacs in iTerm2 change the term cursor to underscore style

### ISSUE THREAD

**Issue by lululau** [syl20bnr/spacemacs#1989]
Hi, I'm using Spacemacs in iTerm2 build 2.1.1, the cursor becoms to underscore style from its original block style after launching emacs, even after quit emacs, it still keeps the underscore style. How could I fix this problem? Thanks.

**Comment by syl20bnr** [comment]
I cannot reproduce it on iTerm 2.1.1.
I launch emacs with `emacs -nw` then I get a blinking block cursor which transforms to a bar in insert state. When I quit the cursor is still OK.

**Comment by syl20bnr** [comment]
Mmmh do you use `emacs` or `vim` editing style ?

**Comment by lululau** [comment]
I'm using `vim` style, the cursor shape keeps unchanged after quitting emacs. It keeps hbar shape if the last state before quiting emacs is emacs state. It keeps bar shape if the last state is evil insert state.

**Comment by introom** [comment]
I can confirm this, too. iTerm2.1.1, with vim style.

**Comment by dsdshcym** [comment]
@lululau I can't reproduce this bug on iTerm 2.1.4. Maybe it's fixed by iTerm?

**Comment by lululau** [comment]
I haven't been use Emacs in terminal for a while, and I tried to check this problem on iTerm2.9(beta) & iTerm2.1.4 with the latest develop revision  just now, and the issue did not recur, so I think it maybe should be closed.
