### ISSUE TITLE
Spacemacs Improvement Proposal™ 

### ISSUE THREAD

**Issue by ianks** [syl20bnr/spacemacs#199]
It would be interesting to automate feedback from users in this project. Freeform Github issues are good for some things such as reporting bugs/improvements, but lack in areas like coming to a consensus on best practices.

For example, what if there was a conflict on where to include FOO package? We could have some sort of standard Spacemacs Improvement Proposal ™ ( :laughing:) and voting process to find what users would prefer. 

```
Which package would be best for solving this spacemacs feature?
  1. A pretty-ok package that is popular
  2. A not-so-good package
  3. Neither, they are both terrible.
```

I think this process would be also especially useful to discover the optimal key-bindings early on before things get too set-in-stone.

SIP would be a Github issue which presents a set of choice in a poll. There is then a X day period (14 days?) where users can vote. We need to figure out a good mechanism for creating polls that integrates nicely with Github (to prevent double-voting, etc.).

Another thing to mention is that all proposals *must* be agreeable to the core-contributors as they have significantly more domain knowledge than the average user. They can sniff out possible collisions, and have a better understanding of the philosophy. 

Thoughts?

**Comment by syl20bnr** [comment]
I close the discussion for now since we have now [conventions](https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.md) which make the PR proposal for new language easier when it comes to key bindings choice. Also enhancement proposals are discussed directly in the opened issue thread.
