### ISSUE TITLE
Cursor as indicator for insert/command mode. 

### ISSUE THREAD

**Issue by ReneFroger** [syl20bnr/spacemacs#1992]
Hi there! I was wondering if Spacemacs does have a indicator in the cursor for entering the insert mode, and command mode? If not, then I would like to share this snippet from my configuration: 

```
;; -----------------------------------------------------------------------------------
;; Evil no blinking cursor when normal, blinking when insert 
;; -----------------------------------------------------------------------------------
(blink-cursor-mode (- (*) (*) (*)))
(defun enable-blinking ()
(interactive)
(blink-cursor-mode t)
;;(cursor-type `box)
)   
```

Might be an useful indicator for Spacemacs users.

**Comment by syl20bnr** [comment]
Thank you for the snippet.
This is a good question, depending on the terminal we have some feedback of not.
In iTerm the cursor is a block in normal state and a bar in insert state. With urxvt it seems that we have no feedback.
The feeback is handled by  `evil-terminal-cursor-changer`

**Comment by a13ph** [comment]
Gnome-terminal 3.14.2 - no cursor change, only color in modeline

**Comment by kimonoki** [comment]
I don' find this snippet working on GUI now. 
I am using
```
  (add-hook 'evil-hybrid-state-entry-hook   #'blink-cursor-mode )
  (add-hook 'evil-hybrid-state-exit-hook   #'blink-cursor-suspend )
```
for blinking cursor in the hybrid state
