### ISSUE TITLE
dotspacemacs-default-font doesn't affect org mode titles

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#1994]
For some reason it stays something other than specified in default-font, same goes for custom-face-tag in customize-group screen. Font specified in default-font is terminus and works fine in other modes.

**Comment by cpaulik** [comment]
Could be related to your theme. Which one are you using?

**Comment by Eilie** [comment]
@cpaulik monokai.

**Comment by cpaulik** [comment]
Yeah, it [looks like](https://github.com/oneKelvinSmith/monokai-emacs/blob/master/monokai-theme.el#L3739-L3745) monokay is using a variable-pitch font for some text.

But you should be able to set [this](https://github.com/oneKelvinSmith/monokai-emacs/blob/master/monokai-theme.el#L63) variable to disable the behaviour.

**Comment by Eilie** [comment]
@cpaulik That works, thank you!
