### ISSUE TITLE
Please don't disable on-the-fly syntax checking

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#1996]
Reasons:

- It then will be no better than Vim. You don't have on-the-fly syntax checking, which is a core feature. This sucks.
- If syntax checking degrades performance, after saving you still have that problem anyway, especially on huge file.

What we need to do is turning off `lfycheck-mode` completely when a file exceeds some threshold, i.e. 3MB, and prints a message to let user knows and adjust to his preference.

**Comment by syl20bnr** [comment]
You are right, we should restore the default.

**Comment by syl20bnr** [comment]
Should be fixed on develop.
