### ISSUE TITLE
Could spacemacs related directory  be separate other than user-emacs-directory?

### ISSUE THREAD

**Issue by xor3** [syl20bnr/spacemacs#1998]
As the title says, I want my emacs share same spacemacs's configuration on Gnu/Linux and Windows but keep other things like projectile cache independent. 
Aother good reason is  that This keeps my spacemacs project tree much more cleaner.

**Comment by syl20bnr** [comment]
It should not be a problem, the `.cache` directory is ignored by git so it won't be shared by your different OSes.

**Comment by xor3** [comment]
That's exactly what I want. Thanks for your great work.

**Comment by StreakyCobra** [comment]
This question has been answered, I'm closing this issue then. Feel free to open a new one in case of troubles :relaxed:
