### ISSUE TITLE
Consider breaking spacemacs modeline out in to its own package

### ISSUE THREAD

**Issue by IvanMalison** [syl20bnr/spacemacs#2000]
Is there any chance that you would consider this? Is there any techincal reason that this might be difficult?

**Comment by tuhdo** [comment]
Do you to exclude `powerline` package or do you want to use it in your own Emacs configuration?

**Comment by IvanMalison** [comment]
I'd like to use it in my own configuration without using the rest of spacemacs. It's easier enough to simply copy the code that creates it into my own .emacs.d, but I'd rather not maintain my own separate version.

**Comment by eigengrau** [comment]
This would be highly welcome. :)

**Comment by joehillen** [comment]
:+1: 

I think think spacemacs is cool, but I don't need it. I just want to try out that cool modeline.

**Comment by IvanMalison** [comment]
@joehillen @eigengrau Its not too hard to break it out to just try it out, but some stuff doesn't work properly/depends on spacemacs internals.

https://github.com/IvanMalison/dotfiles/blob/master/dotfiles/emacs.d/load.d/powerline.el

works, but could use a lot of work.

**Comment by IvanMalison** [comment]
@syl20bnr I would volunteer to do the breakout if you agree to use it.

**Comment by syl20bnr** [comment]
I have no problem with that but it seems not to be a trivial task.
Important point to consider is that the current code for the powerline is the ugliest code of the whole configuration and it is planned to be replaced by something much cleaner see #524.

**Comment by IvanMalison** [comment]
What makes it non trivial other than some dependency on other powerline stuff? Seems like it wouldn't be too hard.

**Comment by alxndr** [comment]
@TheBB has extracted [spaceline](https://github.com/TheBB/spaceline).

**Comment by eigengrau** [comment]
Awesome! :+1:

**Comment by TheBB** [comment]
Probably good enough to close this, even if the package isn't used in Spacemacs yet.
