### ISSUE TITLE
helm-descbinds gets shadowed by helm-make at `SPC h k`

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#2001]
https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L1955-L1962

THis get's shadowed by another command that uses a Makefile.. I'm not sure what it does but it happened today.

**Comment by TheBB** [comment]
Yo, you blind. It's literally right beneath. :-D

https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L1968

Easy way to find such things: `SPC h d k` (`describe-key`) `SPC h k` (what you're interested in), see that it runs `helm-make`, search for `helm-make` in Spacemacs repo.

**Comment by CestDiego** [comment]
I didn't know it was helm make. Thanks @TheBB 

>kek

Anyway, the helm-descbinds shuold be sth that doesn't get shadowed, I think `SPC h d K` should be gud.

What do you think, @syl20bnr

**Comment by luxbock** [comment]
Wasn't `helm-descbinds` bound previously to `SPC-?`? I have been using that happily for a while, and I was glad that it was in such an easy to reach key combination for how useful it is. Now `SPC-?` does `spacemacs/helm-project-smart-do-search-region-or-symbol`, which I don't like at all for the following reasons:
- This binding is only useful when working in project, and therefore shouldn't occupy such prime keyboard real estate.
- The `SPC-?` had the perfect mnemonic for what it used to do with `helm-descbinds`
- It seems like functionality of `spacemacs/helm-project-smart-do-search-region-or-symbol` could just as well be served by having its sister binding of `SPC-/`, i.e. `spacemacs/helm-project-smart-do-search` take a universal-argument for this particular use case.

**Comment by tuhdo** [comment]
@luxbock I agree. This is the key binding that shouldn't be touched. `helm-descbinds` is meant to discover major mode key bindings (and every other key bindings that follow) and play with them easily.. Else, we should train Vim users to use `C-h` key bindings i.e. `C-h b` or `C-h f`. I don't understand why Spacemacs has to use such a long key sequence like `SPC h d b`.

**Comment by syl20bnr** [comment]
For now it is SPC h k and not SPC h d b. We can leave it like this.

Le mardi 16 juin 2015, Tu Do <notifications@github.com> a écrit :

> @luxbock <https://github.com/luxbock> I agree. This is the key binding
> that shouldn't be touched. helm-descbinds is meant to discover major mode
> key bindings (and every other key bindings that follow) and play with them
> easily.. Else, we should train Vim users to use C-h key bindings i.e. C-h
> b or C-h f. I don't understand why Spacemacs has to use such a long key
> sequence like SPC h d b.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/2001#issuecomment-112366017>
> .
>


-- 
-syl20bnr-

**Comment by CestDiego** [comment]
@luxbock the universal prefix argument is is made to have `SPC-/` search for only a type of file in the whole project:Say all files ending with `*.org` that contain the search pattern. *maybe* having it to double preffix argument  `SPC u SPC u SPC-/` could do it, One for having the symbol at point and the other to search in specific file extensions. But I'm finding the current usage ok. and @syl20bnr is ok with that too, also I think that people may want to search specific file extensions without needing to search for symbol at point. (this is getting messy).... 

Regarding 
>For now it is SPC h k and not SPC h d b. We can leave it like this. 

@syl20bnr no it's not bound to that. In my setup I have `SPC h k` bound to `helm-make` and you can see it here that `SPC h k` is bound twice.
https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L1938-L1951
I get why is `SPC h d` the equivalent of `C-h` in Spacemacs, and it's that `SPC h` has many keybindings for `helm` there too, so to differientiate between help and helm the extra `d` was added... Maybe we could experiment with `SPC H v` `SPC H k`?  or sth like that? 

Other comment I have on this, is that, even though we are in the `develop` branch. the releases haven't been that frequent which has lead to more people to come to the develop branch (I think, correct me if I'm wrong) and that makes the `develop` not be that good of a feature testing site. Big breaking up changes that are not well established or written in stone should maybe go into a temp `feature` branch for contributors to test and share ideas, without compromising other people in the develop branch. it's a waaay more complicated way of managing it because we now have just two branches and that's neat. But it may lead to less confusion among people using the develop branch as their stable because they don't want to be left behind on master x3 Or, maybe we should just do little releases more. that was working before, no pressure though, it's just a thought.

**Comment by syl20bnr** [comment]
>  the releases haven't been that frequent which has lead to more people to come to the develop branch

This is not a solvable issue. More frequent releases means a master branch less stable.

As I said earlier, `develop` is `develop` and I may break at some point but it should not break fro too long. It is always possible to switch in detached head state in git if someone wants to use `develop` but not the last changes.

We should _never_ tell people to switch to the `develop` branch for a new feature or a bug fix. When this is an important bug I can cherry-pick into the mainenance branch and publish a new release.

**Comment by syl20bnr** [comment]
Moreover I want as many people as possible to try new development, making branches won't help in this regards. The idea is to be agile with the changes and I try to listen to feedback and fix things in a timely fashion. I want as many people as possible on `develop` but it has to be a decision made by the users, we should not tell them to use it, otherwise there is no point in having a master branch and we only push the issue further (by asking for new branches etc...).

**Comment by CestDiego** [comment]
Ok I get it now :) sounds sound. Ok but regarding this issue, the helm-descbinds function that "is bound" to `SPC h k` is shadowed by helm-make and now we don't have either` SPC ?` nor `SPC h k` ... Should we go with `SPC h d b` or try` `SPC H k` or `SPC H b`

**Comment by syl20bnr** [comment]
Sorry guys, lot of ink for this change. After thinking about it and reading your feedback I decided to revert `SPC ?` to `helm-descbinds`. `SPC /` is now a shortcut for `searching in project with things under point or active region`.

**Comment by syl20bnr** [comment]
I close the issue, feel free to comment if it needs to be reopened.
