### ISSUE TITLE
NeoTree somehow messes up the eyebrowse configuration?

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#2008]
Now whenever I have NeoTree open, and I use `SPC W 2`(or any number) to try to create a new `eyebrowse` workspace, Emacs just says `window is dedicated to *NeoTree*`, and shows the `NeoTree` buffer from the previously open workspace in full. I can't switch to any other workspace because the same message shows, and when I press `q` Emacs says "Attempt to delete minibuffer or sole ordinary window" and won't let me do it. The only way to get out of it seems to be `SPC b b` etc. to open another buffer and then close NeoTree. However my workspace configuration is already ruined by then.

**Comment by bmag** [comment]
I also get the `window is dedicated to ...` - happens whenever I have a dedictated window (doesn't have to be neotree). Does it happen also with stock emacs and eyebrowse? Maybe it's  a bug in eyebrowse...

**Comment by x-ji** [comment]
Hmm... It's just that I didn't see this bug a while ago. I guess it could be some new functionality in eyebrowse which caused the issue?

**Comment by dab** [comment]
working the same way on `develop` — `Window is dedicated to *NeoTree*`

**Comment by bmag** [comment]
Reported upstream ([here](https://github.com/wasamasa/eyebrowse/issues/36)). This is a bug with eyebrowse and `window-state-put`.

**Comment by bmag** [comment]
Fixed upstream. Update your eyebrowse package and you should be ok.

**Comment by x-ji** [comment]
Thanks.
