### ISSUE TITLE
Keybindings missing in Debugger mode

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#2012]
In (elisp) Debugger mode none of the evil / spacemacs bindings seem to work.

**Comment by StreakyCobra** [comment]
@tko Do you still have this problem? If yes, can you provide a few more details on how to reproduce? :smile:

**Comment by tko** [comment]
Seems to work now. It was the debugger window that pops up to show the elisp backtrace, can't recall how to trigger it, `(debug)` maybe?
