### ISSUE TITLE
spacemacs/helm-files-smart-do-search inconsistent ammount of arguments?

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#2016]
When I try to access `SPC f /` which is bounded to this:
```
SPC f / runs the command spacemacs/helm-files-smart-do-search, which is an
interactive Lisp function in `init.el'.

It is bound to SPC f /, M-m f /.

(spacemacs/helm-files-smart-do-search &optional ARG DEFAULT-INPUTP)
```

I get
`spacemacs/helm-files-smart-do-search: Wrong type argument: commandp, helm-files-do-ag`

**Comment by tko** [comment]
Just made the same comment in #1987

**Comment by syl20bnr** [comment]
Should be ok in develop now.

**Comment by syl20bnr** [comment]
Also be sure to check the new bindings scheme: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#with-an-external-tool
