### ISSUE TITLE
eshell aliases

### ISSUE THREAD

**Issue by gguimaraesbr** [syl20bnr/spacemacs#2018]
What is the recommended approach to handle with eshell aliases? I didn't find a way to set the variable `eshell-aliases-file` to an external file so I guess I'm forced to use the default `~/.emacs.d/.cache/eshell/alias`. Does it make sense?

**Comment by CestDiego** [comment]
what about 
`      (defalias 'emacs 'find-file)`

**Comment by CestDiego** [comment]
@gguimaraesbr I found the issue, if you want to use that you have to require the em-alias file

`      (require 'em-alias)
`

**Comment by gguimaraesbr** [comment]
Thanks!
