### ISSUE TITLE
Getting stuck in the helm microstate

### ISSUE THREAD

**Issue by icambron** [syl20bnr/spacemacs#2020]
Edited description: Once in the helm microstate, I can't get back out! It persists across uses of helm and makes it hard to do stuff with numbers.

---------

I have a file in my project called "oauth2" which I'd like to open. I hit `spc p f` and start typing "oauth2". When I enter the "2" the helm buffer takes up the whole screen. Other numbers have different behaviors: "1" or "3" closes it, "4" brings up some kind of completion-algorithm chooser, "5" some kind of regex thingy, and so on. I guess it's some way to switch between helm...things. But it should really be finding the file with the character 2 in it, right?

**Comment by jasoncyu** [comment]
You activated the helm micro-state. https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#helm-micro-state

**Comment by syl20bnr** [comment]
I cannot reproduce it, are you using the Vim or Emacs style ?
Does it happen all the time ?

**Comment by icambron** [comment]
I guess I don't know what Vim vs Emacs "style" is...but I do use the default Evil keybindings everywhere and my `.spacemacs` is here: https://github.com/icambron/dotfiles/blob/master/.spacemacs

I restarted Emacs and it went away. From looking at the micro-state docs, it does appear to be that. I may accidentally be hitting shift-command-space while in Helm (I have command space bound to Spotlight and afaik command on Mac = Meta). Anyway, I can reproduce it by doing that.

However, I'm not able to *leave* the micro-state, except by restarting Emacs. Hitting s-m-spc again doesn't seem to do anything, and, though perhaps I don't understand Helm Micro-state, I don't expect it to keep me in that state next time I bring up helm, which it's doing.

**Comment by jasoncyu** [comment]
yeah, that state does seem to be a little buggy, I've only entered it on accident, which *should* be impossible because its two keybindings are already bound to other osx things, like alfred. I've never had a problem getting out of it though. Basically, if I'm in an inconsistent state, I just mash <Esc> and <C-g> until I get back to a normal state. Does that work for you @icambron ?

**Comment by icambron** [comment]
@jasoncyu No, it doesn't, at least every way I've tried so far.

**Comment by BlinkD** [comment]
@syl20bnr it's `key-map` bug when micro-state ask user input strings. same happend when rename a tag in web-mode micro-state

**Comment by codedmart** [comment]
@icambron I seem to have hit this issue as well. More related to you original title. I can't find files `SPC p f` or search for functions/methods with numbers in them `SPC s a p`. As soon as I hit the number the corresponding Helm micro-state keybinding happens ([Helm micro-state](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#helm-micro-state)), but I can type letters that correspond to the Helm micro-state keybinding fine. @syl20bnr I am new to emacs/spacemacs. Where could I look to try and help solve it possibly?

**Comment by a13ph** [comment]
possibly related (was trying to reproduce that bug):
`SPC s a p`, `some query` `RET` enters C-u for me (while not displaying any results, maybe cause I don't particularly use projects)
if I try to enter any number afterwards, it reveals that I'm indeed in universal-argument entry

**Comment by StreakyCobra** [comment]
It can already be helpful to have a visual indicator of being in the `helm-micro-state`. Right now, nothing allows to differentiate the micro-state and normal-state. Maybe @TheBB can include this information in the `spaceline`?
