### ISSUE TITLE
jump to unit test 

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#2026]
I'm not sure it is reasonable to open an issue here. My question is, is there any function or tool can jump to the place in the source code or unittest code where the unit test failed? Just like the compliation buffer does, hightlight the failed unitest and bind a key for jumping to unittest code.

**Comment by cpaulik** [comment]
Are you thinking about a specific language? I would guess that this would be different for different languages.

**Comment by dzhwinter** [comment]
Thanks for the rapid reply.
no. just c++ gtest frame work. take a look at this screen shot. 
![test](https://cloud.githubusercontent.com/assets/6687176/8184552/96f1b0d2-1471-11e5-9ca1-984794bb3537.jpg)

**Comment by dzhwinter** [comment]
I wanna to jump from failed runtest to runtest case source code or *the source code*.

**Comment by tuhdo** [comment]
Seems like `pooling_layer.cpp` is the test case? If so, you can move point on that and use `SPC p g`. I assume that your project is recognized by Projectile. Or you can manually use `SPC f f` and type the name of your test file that contains the test case.

If you use `gtags` with GNU Global, then you can enable `helm-gtags-mode` in the compilation buffer and use `SPC m g g` on a specific symbol to jump there.

**Comment by tuhdo** [comment]
Unfortunately, `SPC m g g` does not recognize `filename:line` format, so you may need to select a region with only filename. If you use `helm-gtags`, you need to enable `helm-gtags` key bindings in compilation buffer like this:

```elisp
 (spacemacs/helm-gtags-define-keys-for-mode 'tcl-mode)
```

in your `dotspacemacs/config` function in `.spacemacs` file.

**Comment by dzhwinter** [comment]
https://code.google.com/p/googletest/wiki/FAQ#How_do_I_jump_to_the_line_of_a_failure_in_Emacs_directly? 
some guy help me with that, but the failure cannnot click. I get my answer. Thanks for your response

**Comment by StreakyCobra** [comment]
@dzhwinter Do you need some more help on this issue? If not, it can probably be close :relaxed:
