### ISSUE TITLE
[BUG]Eval error in the `c-lang-defconst' for `c-simple-stmt-kwds' in php-mode

### ISSUE THREAD

**Issue by BlinkD** [syl20bnr/spacemacs#2034]
failed to launch web-mode, and i got 
```
Eval error in the `c-lang-defconst' for `c-simple-stmt-kwds' in php-mode
```
it's seems a bug of  `php-mode`, when i delete `php-mode.elc` and `php-mode-pkg.elc`, the error message not shown again.

**Comment by syohex** [comment]
This is known issue. https://github.com/ejmr/php-mode/issues/243

If you updated Emacs version, you should recompile `php-mode.el` by newer Emacs.

**Comment by BlinkD** [comment]
@syohex  thanks

**Comment by syl20bnr** [comment]
@BlinkD Is this OK after recompiling ?

**Comment by BlinkD** [comment]
@syl20bnr it's ok :)

**Comment by wolfgangwayland7** [comment]
I found if you change all the single quotes ->'   to  left slanted  single quotes,  (the `~ key to the left  of the '1' key),   that all the errors went away.   I am using "arduino-mode-20151017.2335" on Linux Mint 18.
