### ISSUE TITLE
Develop branch: New install says No support found to parse buffer \"org-loaddefs.el\""

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#2042]
I get these errors:

```
Not enabling jit-lock: it does not work in indirect buffer
Loading semantic/db-file...done
Parsing org-loaddefs.el (LL)...
Error running timer `semantic-idle-scheduler-function': (error "No support found to parse buffer \"org-loaddefs.el\"")
Parsing org-loaddefs.el (LL)...
Idle Work Parse Error: "#<buffer org-loaddefs.el> - No support found to parse buffer \"org-loaddefs.el\""
```

With these layers enabled:

```
     auto-completion
     better-defaults
     emacs-lisp
     git
     markdown
     org
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     syntax-checking
     version-control

     c-c++
     clojure
     dash
     github
     html
     osx
     python
     rust
     semantic
     sql
```

**Comment by MerelyAPseudonym** [comment]
+1
I've been seeing the same messages

**Comment by syl20bnr** [comment]
What's your Emacs version ? I presume it comes from the semantic layer, can you test without the `semantic` layer ?

**Comment by swaroopch** [comment]
@syl20bnr Yes, you're right, it looks like this issue happens only when `semantic` layer is enabled, I don't see the error on a new install without it.

**Comment by x-ji** [comment]
I also had this error. At the same time I had another error `Symbol's value as variable is void: org-planning-line-re`. I disabled both `org` and `semantic` layers, and reinstalled them. Seems both errors are gone for now.

**Comment by x-ji** [comment]
Ah no. The issue `Symbol's value as variable is void: org-planning-line-re` resurfaced after Spacemacs is launched next time.

**Comment by x-ji** [comment]
Well according to discussions [here](https://lists.gnu.org/archive/html/emacs-orgmode/2014-09/msg00224.html), the issue `Symbol's value as variable is void: org-planning-line-re` is caused by using things from org before load-paths is set up. I moved all my org-related customizations from `spacemacs/init ()` to `dotspacemacs/config ()`, and the issues seem to be gone.

**Comment by jtmoulia** [comment]
:beers: to @x-ji -- moving org related config to `dotspacemacs/config` also fixed this issue for me.

**Comment by StreakyCobra** [comment]
Do you still have this problem @swaroopch?

**Comment by swaroopch** [comment]
Seems to be fixed now!

**Comment by swaroopch** [comment]
Hmm, not sure what combination of layers cause this, but this just happened when I had more than just `org` and `semantic` layers:

```
Parsing org-loaddefs.el<org-plus-contrib-20151005> (LL)...
Error running timer `semantic-idle-scheduler-function': (error "No support found to parse buffer \"org-loaddefs.el<org-plus-contrib-20151005>\"")
```

This is what I actually have now:

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 3fb38773b326db1d18a811e229bf9054c349b696)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org
                 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking version-control c-c++ clojure go html
                 (python :variables python-fill-column 99)
                 sql dash github osx semantic yaml)
```

**Comment by dzannotti** [comment]
just seen this with
```
(auto-completion :variables
                      auto-completion-enable-snippets-in-popup t
                      auto-completion-enable-sort-by-usage t
                      auto-completion-enable-company-help-tooltip t
                      :disabled-for
                      html)
     better-defaults
    syntax-checking
     colors
     eyebrowse
     gtags
     dash
     dockerfile
     elm
     git
     evil-snipe
     org
     semantic
     markdown
     emacs-lisp
     clojure
     common-lisp
     javascript
     react
     pandoc
     php
     python
     ruby
     c-c++
     html
     haskell
     (ibuffer :variables
              ibuffer-group-buffers-by 'projects)
     shell
     shell-scripts
     search-engine
     spell-checking
     spotify
     vinegar
     xkcd
     yaml
  )
```

on master branch, emacs 25.5.15, osx

**Comment by jb55** [comment]
`rm -rf .cache/semanticdb` fixed this for me

**Comment by swaroopch** [comment]
I haven't seen this issue happen off late, so closing.

**Comment by bb4242** [comment]
Actually, I just noticed this happening again in 0.200.3.  Removing `.cache/semanticdb` seems to help.
