### ISSUE TITLE
Slow performance when searching large files (solved)

### ISSUE THREAD

**Issue by topher200** [syl20bnr/spacemacs#2043]
Viewing a semi-large log file with default spacemacs settings results in very slow searching. In my example log file (https://transfer.sh/kphuQ/test.log), running /get then n and n (so evil-search-forward, then two evil-search-nexts) takes 17 seconds.

The issue is with `global-evil-search-highlight-persist`. According to @syl20bnr, it should be disabled in fundamental-mode.

**Comment by geo7** [comment]
gitter chat link : :point_up: [June 17 2015 9:32 PM](https://gitter.im/syl20bnr/spacemacs?at=5581d94807d7cb5335b2ead3)

**Comment by syl20bnr** [comment]
PR submitted upstream: https://github.com/juanjux/evil-search-highlight-persist/pull/10

**Comment by syl20bnr** [comment]
The PR has been merged upstream.

**Comment by Devagamster** [comment]
I am amused by the kills kittens tag

**Comment by StreakyCobra** [comment]
As it has been merged upstream long time ago, it should have been corrected in all installations by now. I close this issue, but keep the `Fixed upstream` label though.
