### ISSUE TITLE
0.102.0 or later: init.el fails: Wrong type argument: stringp, ~/.emacs.d/private

### ISSUE THREAD

**Issue by jeremyjh** [syl20bnr/spacemacs#2044]
I get this after upgrading to 0.102.0 or later. 

Debugger entered--Lisp error: (wrong-type-argument stringp ~/\.emacs\.d/private)
  directory-files(~/\.emacs\.d/private nil nil nosort)
  (let* ((files (directory-files dir nil nil (quote nosort))) (result (quote nil))) (progn (let ((--dolist-tail-- files) f) (while --dolist-tail-- (setq f (car --dolist-tail--)) (let ((full (file-name-as-directory ...))) (if (and (not ...) (not ...) (file-directory-p full)) (progn (spacemacs-buffer/message "-> Discovered configuration layer: %s" f) (setq result ...)))) (setq --dolist-tail-- (cdr --dolist-tail--))))) result)
  configuration-layer//discover-layers-in-dir(~/\.emacs\.d/private)
  (append discovered (configuration-layer//discover-layers-in-dir dir))
  (setq discovered (append discovered (configuration-layer//discover-layers-in-dir dir)))
  (while --dolist-tail-- (setq dir (car --dolist-tail--)) (setq discovered (append discovered (configuration-layer//discover-layers-in-dir dir))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- (append contrib-cat-dirs dotspacemacs-configuration-layer-path)) dir) (while --dolist-tail-- (setq dir (car --dolist-tail--)) (setq discovered (append discovered (configuration-layer//discover-layers-in-dir dir))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (progn (let ((--dolist-tail-- (append contrib-cat-dirs dotspacemacs-configuration-layer-path)) dir) (while --dolist-tail-- (setq dir (car --dolist-tail--)) (setq discovered (append discovered (configuration-layer//discover-layers-in-dir dir))) (setq --dolist-tail-- (cdr --dolist-tail--)))))
  (let ((contrib-cat-dirs (configuration-layer//get-contrib-category-dirs)) (discovered (quote nil)) (result (make-hash-table :size 256))) (setq discovered (append discovered (configuration-layer//discover-layers-in-dir configuration-layer-contrib-directory configuration-layer-contrib-categories))) (progn (let ((--dolist-tail-- (append contrib-cat-dirs dotspacemacs-configuration-layer-path)) dir) (while --dolist-tail-- (setq dir (car --dolist-tail--)) (setq discovered (append discovered (configuration-layer//discover-layers-in-dir dir))) (setq --dolist-tail-- (cdr --dolist-tail--))))) (setq discovered (append discovered (configuration-layer//discover-layers-in-dir configuration-layer-private-directory (quote ("snippets"))))) (puthash (quote spacemacs) (expand-file-name user-emacs-directory) result) (mapc (function (lambda (l) (if (ht-contains\? result (car l)) (spacemacs-buffer/warning (concat "Duplicated layer %s detected in directory \"%s\", " "keeping only the layer in directory \"%s\"") (car l) (cdr l) (ht-get result (car l))) (puthash (car l) (cdr l) result)))) discovered) result)
  configuration-layer//discover-layers()
  (setq configuration-layer-paths (configuration-layer//discover-layers))
  configuration-layer/init-layers()
  configuration-layer/sync()
  (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (require (quote core-configuration-layer)) (spacemacs/init) (configuration-layer/sync) (spacemacs/setup-after-init-hook) (spacemacs/maybe-install-dotfile) (require (quote server)) (if (server-running-p) nil (server-start)))
  (if (spacemacs/emacs-version-ok) (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (require (quote core-configuration-layer)) (spacemacs/init) (configuration-layer/sync) (spacemacs/setup-after-init-hook) (spacemacs/maybe-install-dotfile) (require (quote server)) (if (server-running-p) nil (server-start))))
  eval-buffer(#<buffer  *load*> nil "/home/jeremy/.emacs.d/init.el" nil t)  ; Reading at buffer position 912
  load-with-code-conversion("/home/jeremy/.emacs.d/init.el" "/home/jeremy/.emacs.d/init.el" t t)
  load("/home/jeremy/.emacs.d/init" t t)
  #[0 "\205\262

**Comment by justbur** [comment]
Just a hunch: What's in your `dotspacemacs-configuration-layer-path`? That's set in .spacemacs

**Comment by jeremyjh** [comment]
Yep, the path was unquoted. Thanks!
