### ISSUE TITLE
In Lua buffer, the parentheses highlighting is strange

### ISSUE THREAD

**Issue by andyque** [syl20bnr/spacemacs#2048]
Here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/785541/8230577/268dae52-15f4-11e5-99f8-4701fcc6e2ac.png)

How could I get rid of it?

**Comment by tuhdo** [comment]
Try turning off either show-smartparens-mode or highlight-parentheses to see which one causes the problem. Then you add a hook to lua-mode to turn it off.

**Comment by JP-Ellis** [comment]
I've seen this before when rainbow-delimiters has a mismatched parenthesis (or any kind of delimiter) somewhere which then causes every subsequent parenthesis to also be seen as mismatched.  This could be a bug in your code, or a bug in Lua-mode (as rainbow-delimiters takes the delimiter pairs from the mode), or it could even be a bug in rainbow-delimiters.

Either way, you can toggle rainbow-delimiters with `SPC t C d`.

**Comment by andyque** [comment]
@tuhdo  @JP-Ellis  
After calling `SPC t C d`, the issue was gone. The problem seems related to the rainbow-delimiters just as @JP-Ellis  said.

Thanks guys :+1:
