### ISSUE TITLE
yasnippet not shown in company-complete popup

### ISSUE THREAD

**Issue by lululau** [syl20bnr/spacemacs#2051]
yasnippet snippets are not shown in the auto-popped completion menu.

**Comment by CestDiego** [comment]
This is a feature, see https://github.com/syl20bnr/spacemacs/issues/999. We separated the completions between everything else and snippets. If you want to explore snippets, try `SPC i s`. Also To expand a snippet you already know it's abbreviation, just type the snippet i.e. `def` and press `M-/`

**Comment by lululau** [comment]
@CestDiego Thanks for reply, but how could I do configurations if I just want both buffer words and snippet abbreviations to be shown in the auto popup menu?

**Comment by andyque** [comment]
@lululau 
Add this into your `dotspacemacs/config()`
```
 (defun autocomplete-show-snippets ()
    "Show snippets in autocomplete popup."
    (let ((backend (car company-backends)))
      (unless (listp backend)
        (setcar company-backends `(,backend :with company-yasnippet company-files)))))

  ;; See http://www.gnu.org/software/emacs/manual/html_node/emacs/Hooks.html
  ;; for what this line means
  (add-hook 'after-change-major-mode-hook 'autocomplete-show-snippets)
```

**Comment by lululau** [comment]
@andyque Thanks, but it does not work for me.

**Comment by andyque** [comment]
@lululau  Are you using `company mode`?

**Comment by andyque** [comment]
@lululau  I think you should  add the upper code and quit emacs and try it again.

**Comment by lululau** [comment]
@andyque Yes, I'm using `company mode`, not `auto-complete mode`, I have tried restarting Emacs, but not work.

**Comment by person808** [comment]
@andyque I actually made that function, but I'm not sure that it works anymore. It stopped working for me a few days ago. I made a PR (#2036) that adds the feature to spacemacs using an answer off of stackoverflow, but even that doesn't work sometimes. I think something funky might be going on with the company backends, but I don't know enough about company to debug it.

**Comment by andyque** [comment]
@person808  Yeah, I have tried it now. It is not working, but a few days ago, it still works... Weird..

**Comment by lululau** [comment]
@person808 @andyque PR([#2036](https://github.com/syl20bnr/spacemacs/pull/2036)) works for me, Thanks all~

**Comment by jvillasante** [comment]
I'm using spacemacs to not have to press M-/. The hook for showing yas snippets on company dropdown works perfect for me, however, I would like to show first snippets completions, and then the rest. Anyone??

**Comment by geo7** [comment]
@TheBB is this not fixed? 

I'm pretty sure I get snippets with 

```
     (auto-completion :variables
                      auto-completion-enable-snippets-in-popup t
                      )


```

**Comment by CestDiego** [comment]
Me too.

**Comment by nixmaniack** [comment]
Works for me too!

**Comment by TheBB** [comment]
The ayes have it.
