### ISSUE TITLE
Can't bind `evil-escape-key-sequence` to <kbd>C-c C-g</kbd>

### ISSUE THREAD

**Issue by MerelyAPseudonym** [syl20bnr/spacemacs#2052]
~~On both the `master` and `develop` branches, if I write `(setq evil-escape-key-sequence (kbd "C-c C-g"))` at the end of `dotspacemacs/init`, then I see an error on startup like this: `Error (use-package): helm :init: Key sequence C-c C-l starts with non-prefix key C-c`~~
(I figured out that the above error was caused by wrapping `"C-c C-g"` with `(kbd …)`)

I've added `(setq evil-escape-key-sequence "C-c C-g")` to the end of the `spacemacs/init` _and_ verified that `describe-variable` returns:
```
evil-escape-key-sequence is a variable defined in `evil-escape.el'.
Its value is "C-c C-g"
Original value was "fd"
```

Nevertheless, when I type <kbd>C-c C-g</kbd> I see `C-c C-g is undefined` in the minibuffer.

**Comment by MerelyAPseudonym** [comment]
Even if I put `(setq-default evil-escape-key-sequence "C-c C-g")` as the first line of `~/.emacs.d/init.el`, it doesn't work.

**Comment by MerelyAPseudonym** [comment]
Feel free to close this issue in favor of https://github.com/syl20bnr/evil-escape/issues/29

**Comment by syl20bnr** [comment]
Unfortunately `C-c C-g` is not supported by `evil-escape` this is an implementation limitation.
The supported keys are listed in the readme: https://github.com/syl20bnr/evil-escape#first-key

**Comment by syl20bnr** [comment]
As written in upstream issue, evil-escape cannot support such key sequence, so I close this issue.
