### ISSUE TITLE
How to do search in Guide key buffer?

### ISSUE THREAD

**Issue by andyque** [syl20bnr/spacemacs#2054]
As we know, there are tons of feature in spacemacs and many more are added everyday.
And sometimes the keybindings will change from time to time.
So it's a little bit tricky for me to remember all the shortcuts.

I know guide key is very helpful, but when the popup window contains many commands, it's very difficult for me to find the right command and its key binding .

What if we could search in the guide key buffer?
And how about converting a existing Guide key buffer into a helm buffer and we could simply type a few keywords to filter the right command.

This feature would be very helpful for the lazy person like me who can't remember all the keybindings.

@tuhdo @syl20bnr   Thoughts?

**Comment by tuhdo** [comment]
You switch to `helm-descbinds` by adding a `?` or `C-h`. Then, you will be able to use Helm to search for a command or key.

**Comment by syl20bnr** [comment]
Off topic, in develop I will revert back SPC ? for helm-descbind, I think
you are right @tuhdo.


Le vendredi 19 juin 2015, Tu Do <notifications@github.com> a écrit :

> You switch to helm-descbinds by adding a ? or C-h. Then, you will be able
> to use Helm to search for a command or key.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/2054#issuecomment-113520310>
> .
>


-- 
-syl20bnr-

**Comment by andyque** [comment]
@syl20bnr  @tuhdo  It works like a charm :+1:
