### ISSUE TITLE
For loops don't work on the python interactive shell

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#2061]
Ubuntu 14.04
Python 3 running from a virtualenv

code : 

```python

import openpyxl
>>> wb = openpyxl.Workbook()
>>> sheet = wb.get_active_sheet()
>>> for i in range(1,11):
...     sheet['A' + str(i)] = i
  File "<stdin>", line 1
    sheet['A' + str(i)] = i
    ^
IndentationError: unexpected indent
>>> 
```

however this does work : 

```python
for i in range(5):
... 	print(i)
... 
0
1
2
3
4
>>> 
```

**Comment by cpaulik** [comment]
I would recommend to use `IPython` as your interactive shell since it is smarter handling multiline code blocks.

```python

In [5]: import openpyxl

In [12]: wb = openpyxl.Workbook()

In [16]: sheet = wb.get_active_sheet()

In [20]: for i in range(1, 11):
   ....: sheet['A'+str(i)] = i
   ....: 
```

Having said that why are you typing multiline codeblocks into the interactive shell? Would it not be easier to type them in the buffer you want them and then send them to the REPL?

**Comment by geo7** [comment]
> I would recommend to use IPython as your interactive shell since it is smarter
  handling multiline code blocks.

Fair, I have this in my `.spacemacs` :

```lisp
  ;; set the default python terminal to Python 3
  (setq python-shell-interpreter "ipython3")
```

But when I run `SPC m s B` it opens a standard python REPL


> Having said that why are you typing multiline codeblocks into the interactive
> shell? Would it not be easier to type them in the buffer you want them and then
> send them to the REPL?

Yeah in general, but If I'm already doing something in the REPL and want to run
something multiline it's easier to be able to do it there than move everything
into a buffer and run that.

**Comment by cpaulik** [comment]
Is the `setq` in your `dotspacemacs/init` or `dotspacemacs/config`. If it is in `init` it might get overwritten by the python layer see https://github.com/syl20bnr/spacemacs/blob/develop/contrib/!lang/python/packages.el#L164 

What does `(executable-find "ipython")` evaluate to for you?

**Comment by geo7** [comment]
> Is the setq in your dotspacemacs/init or dotspacemacs/config. If it is in init

Its in the config

> What does (executable-find "ipython") evaluate to for you?

Nothing, I don't actually have anything come up when I enter
`M-x` then `executable-find`. It's not an option for me

**Comment by cpaulik** [comment]
Taking a second look at the code it does not seem to matter where you have the `setq` because the function is run in the `python-mode-hook`

`executable-find` is not an interactive function so you can not call it from `M-x`. You have to evaluate it in a lisp buffer. I normally set my `*scratch*` buffer to `emacs-lisp mode` and evaluate in there. You can evaluate a expression by putting the cursor after it and pressing `SPC m e e` or `C-x C-e`.

**Comment by geo7** [comment]
> executable-find is not an interactive function so you can not call it from M-x.
> You have to evaluate it in a lisp buffer. I normally set my *scratch* buffer to
> emacs-lisp mode and evaluate in there. You can evaluate a expression by putting
> the cursor after it and pressing SPC m e e or C-x C-e.

OK how I've tried is using `M-:` then entering
```lisp
(executable-find "ipython")
```

which returns `nil`

But I'm pretty sure that It's installed?

Emacs is using a virtualenv :

```bash
vco@geoHP:~/virtualenvs$ /home/vco/virtualenvs/emacs_stuff/bin/pip3 install ipython
Requirement already satisfied (use --upgrade to upgrade): ipython in ./emacs_stuff/lib/pyth
on3.4/site-packages
Cleaning up...
vco@geoHP:~/virtualenvs$ /home/vco/virtualenvs/emacs_stuff/bin/pip3 install ipython3
Downloading/unpacking ipython3
  Could not find any downloads that satisfy the requirement ipython3
Cleaning up...
No distributions at all found for ipython3
Storing debug log for failure in /home/vco/.pip/pip.log
vco@geoHP:~/virtualenvs$

```

The virtualenv is in the `.spacemacs` as
```lisp
  ;; Virtual environment for Python usage
  (setq python-shell-virtualenv-path "/home/vco/virtualenvs/emacs_stuff/")
```

**Comment by cpaulik** [comment]
Ah yeah `M-:` is of course another way which I always forget. So it looks like emacs does not recognize your virtualenv. Check the actual value of `python-shell-virtualenv-path` when trying to execute the command. Maybe it is not set correctly. 

You could also try setting the `WORKON_HOME` environment variable to `/home/vco/virtualenvs/` then `SPC m V` should let you switch to `emacs_stuff`

**Comment by geo7** [comment]
> So it looks like emacs does not recognize your virtualenv.

But it does seem to recognise it - as when I enter `SPC m s B` the path that
comes up is

```
Run Python: /home/vco/virtualenvs/emacs_stuff/bin/python -i
```

> Check the actual value of python-shell-virtualenv-path when trying to execute
> the command. Maybe it is not set correctly.

I *think* i answered this above? 

> You could also try setting the WORKON_HOME environment variable to
> /home/vco/virtualenvs/ then SPC m V should let you switch to emacs_stuff

How is this done?

cheers

**Comment by cpaulik** [comment]
you can also check the files in your `/home/vco/virtualenvs/emacs_stuff/bin/` folder and see if `ipython` is in there. 

What is returned when you run `SPC ! which ipython`

Set `WORKON_HOME` in your `.bashrc` or whatever you are using. Maybe you could also use `setenv` in emacs but I've never tried that.

**Comment by geo7** [comment]
> you can also check the files in your /home/vco/virtualenvs/emacs_stuff/bin/
> folder and see if ipython is in there.

> What is returned when you run SPC ! which ipython

When I enter this I get something along the lines of `Shell command failed`, it goes
away too quick though!

If I enter `which ipython` in by default shell I get nothing in return. 

If (from the standard shell again) I run
```
source /home/vco/virtualenvs/emacs_stuff/bin/activate
```
*then* run `which ipython` I get
```
/home/vco/virtualenvs/emacs_stuff/bin/ipython
```
though `/home/vco/virtualenvs/emacs_stuff/bin/ipython` is also present.

******

I've set the `WORKON_HOME` in bashrc now and running `SPC ! which ipython` doesn't
return anything different.
