### ISSUE TITLE
[python] print(this,end=' ') is highlighted as syntax error

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#2064]
The first instance of 

```
print(something,end='')
```

Is highlighted as a syntax error, all others in the file are fine

**Comment by cpaulik** [comment]
For me if I switch to a python 3 environment then this is not highlighted as an error.

In python 2 this is highlighted as a syntax error as you explained. It seems that the `flycheck` checker stops after the first `invalid syntax` error. If you enter any invalid syntax before your print statement it will no longer be highlighted.

I think your syntax checker is not the python 3 version.

**Comment by geo7** [comment]
right, so I'm running python 3 REPL and stuff but flychecker is using the system default for python version? 

Maybe the other issue will iron this one out at the same time!

**Comment by cpaulik** [comment]
Yes if pyflakes is not installed in your python 3 environment it will only find the one of the system installation.

**Comment by geo7** [comment]
oh right cool - I've just installed that in the venv

**Comment by syl20bnr** [comment]
Is it ok ?

**Comment by geo7** [comment]
nope - still have the issue

**Comment by StreakyCobra** [comment]
@geo7 What's the current status of this issue?

**Comment by geo7** [comment]
@StreakyCobra still present for me. 

Simply writing 

```python
print("hellooo", end=' ')
```

should reproduce

**Comment by StreakyCobra** [comment]
I can't. What does the error say?

**Comment by nixmaniack** [comment]
It says following.
`SyntaxError: invalid syntax [E901]`

I assume it's related to python 2/3 being not detected properly as cpaulik has mentioned.

**Comment by StreakyCobra** [comment]
This is an issue with `flake8` as I saw. What does `flake8 --version` gives you?

**Comment by nixmaniack** [comment]
On my system
```
2.2.4 (pep8: 1.5.7, pyflakes: 0.8.1, hacking.core: 0.0.1, ProxyChecker: 0.0.1, mccabe: 0.2.1) CPython 2.7.5 on Darwin
```

**Comment by StreakyCobra** [comment]
`CPython 2.7.5` Here is your problem :-) Either:

1. Install a more recent version of `flake8`; or
2. Disable the `flake8` checker in `flycheck`

**Comment by nixmaniack** [comment]
2.7.5 is for legacy reasons!

Anyhow, it's a `non-issue` for me! The OP should take a note of above instructions and report if it fixes.
