### ISSUE TITLE
Version the .spacemacs template for easier "diffing"

### ISSUE THREAD

**Issue by nwolfe** [syl20bnr/spacemacs#2065]
The short of this is:
- Replace the file/text-diffing between `.spacemacs.template` and your `.spacemacs` with a version-string pairing.

It is a common problem that your `.spacemacs` gets out of sync with the template, I agree we should ideally do something to help with this.

We kind of started down this path with the recent "template diff" behavior, which just does a naive file diff.  This is a step in the right direction, but I don't like that it just does a text diff as I like to re-order and re-word things in that file.  What's important is not that the text is the same, but that we have all the variables defined.

I was thinking about this, and something that came to mind was a simple version string that could be hard-coded in two places: in your personal `.spacemacs` and in Spacemacs core.  Whenever something is added to the template, the version in core should be bumped.  Then on startup, the version in your `.spacemacs` is compared to the version in core.  If there's a difference, then you need to update your `.spacemacs`! And when you do, bump the version string in it to match that in core.

I've seen this pattern in things like the new magit, where you have to tell it what version you saw last in your .spacemacs so it will stop bothering you with new feature pop-ups during runtime.

**Comment by justbur** [comment]
There are two parts to the problem. One is detecting the update in the template and notifying about it. The other is providing a mechanism to deal with the change. 

In #2063 I use a change in the template file (not a diff with your personal file) to indicate an update is needed and then provide a link to the diff to accomplish the second step. The two steps are completely independent from one another. 

#2063 is a simple solution and the one you provide is another option for dealing with the detection step if I understand correctly. 

I guess you could write code to find the missing variables and add them to your personal file but that seems much more involved. Like a diff on the symbols or something. 

Anyway I'm interested in fixing this problem

**Comment by syl20bnr** [comment]
@justbur I commented in your PR. While I was for a single `.spacemacs` file, when I merge your PR to support `.spacemacs.d` we can start thinking about letting only dotspacemacs variables in `.spacemacs` and move the user specific stuff in `.spacemacs.d/init.el`. This way the diff will be even more useful. The downside is that I find this complicated (the user has `.emacs.d` then `.spacemacs.d` and `.spacemacs).

**Comment by justbur** [comment]
@syl20bnr honestly I think the simple diff works fine and is very quick with ediff. If you're going to change the organization of .spacemacs then you're asking for a more complicated merge of new elements in that file. I don't know of a better system for integrating new config files.

**Comment by syl20bnr** [comment]
I agree and I was not saying to remove the diff but more about removing personal configuration from the dotfile to make the diff even more straight forward. I've been thinking about it but it is likely that the .spacemacs.d will remain optional. It's too late to refactor the .spacemacs :-( Another possibility to focus the diff is to narrow the buffer ?

**Comment by d12frosted** [comment]
@syl20bnr 

> The downside is that I find this complicated (the user has .emacs.d then .spacemacs.d and `.spacemacs).

Why not `.emacs.d`, `.spacemacs.d/spacemacs.el`, `.spacemacs.d/init.el` (`user.el`, `config.el`)? But yeah, when file contains only dotspacemacs variables, diff is much more valuable. Also I believe it's not that hard to find much more intelligent diff by parsing used variable names in template and user config file - and show what's redundant and what's missing.
