### ISSUE TITLE
Installation of org-drill not working as expected

### ISSUE THREAD

**Issue by DoctorTeeth** [syl20bnr/spacemacs#2067]
Have been trying to get org-drill working with no success. Have seen other people mention this in the Gitter chat but have not seen anyone actually resolve the issue. 

See Jun 20th at 8:22 PT in the Gitter chat for details on the different approaches I tried. I'm probably just doing something silly, but I certainly can't figure out what it is.

**Comment by cpaulik** [comment]
Which version of org-mode are you using? The `org-contrib` packages, of which `org-drill` is part of, are not included in the org-mode that ships with emacs (see [here](http://orgmode.org/manual/Installation.html)). Did you follow [installation instructions](http://orgmode.org/worg/org-contrib/org-drill.html) for `org-drill`? Specifically making sure that the `contrib/lisp` directory is in your `load-path`

**Comment by DoctorTeeth** [comment]
Hi, thanks for the help. 

I assume that I am using the default install of org-mode, since I didn't do any extra work to install a newer version (it is possible that a newer version was installed "behind my back" - this is all a little opaque to me). 

I did follow the advice on that page for non-manual install, specifically:

"The easiest way is to customise the variable 'org-modules' (M-x customize-variables RET org-modules) and make sure 'drill' is ticked. Org-drill will then be loaded when you restart Emacs or restart Org-mode."

and it wrote some stuff to my .spacemacs, specifically, it wrote 

    '(org-modules                                                                                                                                                
   (quote                                                                                                                                                     
    (org-bbdb org-bibtex org-docview org-gnus org-info org-irc org-mhe org-rmail org-w3m org-drill)))

to custom-set-variables. 

This method was presented as mutually exclusive with the other method - are you saying that I should undo my previous action and follow the manual instructions?

**Comment by cpaulik** [comment]
As for which org version you are using. You can call `M-x org-version` which should give you the version and path of the currently loaded org version. It it is somewhere in `~/.emacs.d/elpa` then you are using the `ELPA` version which should include `org-drill.el`. 

Basically what you must do is make sure that `org-drill.el` is in your `load-path` then you can `require` it or load it using `use-package` or whatever you like. I would install in manually since I don't know how `org-modules` works.

**Comment by x-ji** [comment]
See this issue https://github.com/syl20bnr/spacemacs/issues/1218 here. Basically `org-drill.el` is not included in the original emacs distribution, so one way you can include the file is to now add `org-plus-contrib` under `dotspacemacs-additional-packages`, which will download all `org-contrib` files, including `org-drill.el`

**Comment by DoctorTeeth** [comment]
@x-ji Works for me - thanks for the help.
