### ISSUE TITLE
Coffeescript highlight not working

### ISSUE THREAD

**Issue by idoo** [syl20bnr/spacemacs#2068]
By default coffeescript highlight, provided by js-mode not working

**Comment by oppenlander** [comment]
Can you confirm you have the `javascript` layer enabled?  
I am not having any problems with Coffeescript highlighting.

**Comment by idoo** [comment]
@ocharles yep, but i had made mistake with my config file
May be better add this row ``` cp ~/.emacs.d/core/templates/.spacemacs.template ~/.spacemacs``` to main screen?

**Comment by syl20bnr** [comment]
@idoo the dotfile is automatically installed at the first launch of emacs.

**Comment by idoo** [comment]
@syl20bnr thank you!
