### ISSUE TITLE
Guide key is broken in small frames because of long function name

### ISSUE THREAD

**Issue by person808** [syl20bnr/spacemacs#2071]
The `spacemacs/helm-project-smart-do-search-region-or-symbol` function name causes this error in `guide-key` in smaller frames:
 `Error running timer guide-key/popup-function': (error "Window #<window 3 on config.el> too small for splitting 5")`. 
For some reason `guide-key` works fine only in the startup buffer, but is very inefficient with its space:
![image](https://cloud.githubusercontent.com/assets/6396431/8273000/15f0c09e-17f6-11e5-91ba-b886177e3cd1.png)

I think we should use a shorter alias and map that to `SPC /` instead.

**Comment by duerrp** [comment]
+1, this often bites me in small terminals

**Comment by person808** [comment]
The introduction of `which-key
