### ISSUE TITLE
spacemacs/eval-region activates evil-normal-state irrespective of current mode

### ISSUE THREAD

**Issue by miabrahams** [syl20bnr/spacemacs#2074]

**Comment by miabrahams** [comment]
I use holy mode so removing (evil-normal-state) is OK for me, but if it serves a purpose in evil mode I do not know what the alternative procedure should be.
```
(defun spacemacs/eval-region ()
  (interactive)
  (eval-region (region-beginning) (region-end))
  ;; (evil-normal-state)
  )
```

**Comment by syl20bnr** [comment]
Thank you for the report, I don't understand the meaning of this function, I reverted to plain `eval-region` so it should be fixed on develop branch.
