### ISSUE TITLE
Freeze on mouse scroll

### ISSUE THREAD

**Issue by kvelicka** [syl20bnr/spacemacs#2076]
As much as I hate reporting bugs as vaguely as this, I've had it happen twice in the last 2-3 hours so I want to see whether I'm the only one getting this issue.

**The bug**: spacemacs freezes, becomes unresponsive to any action and can only be terminated forcefully. It also starts running one CPU core 100%, so I expect there's an infinite loop happening somewhere.

**The trigger**: Mouse scrolling. both times I've encountered the issue I was simply mouse scrolling through Haskell source files (300-1000 LoC).

**Other details**: I'm using spacemacs 0.102.2 with almost all default settings (vim mode) except for using solarized-dark colorscheme and the following configuration layers: emacs-lisp, haskell, editorconfig, c-c++. In both cases the emacs window was split into 3 parts (C-x 3 C-x 3) and maximized.

I would be happy to provide more information about the crash if I knew how to obtain it - suggestions for that are very welcome.

EDIT: seems that the crash can be triggered quite easily now, on my machine it happens when I have 3 vertical buffers visible and scroll through them quickly. Spacemacs then crashes within seconds, in the same way as I described above.

EDIT 2: the issue is easy to tease out on a Linux (CentOS 6.6) system but I couldn't get it to crash on OS X 10.10.

**Comment by benmos** [comment]
I'm not sure if what I'm seeing is the same, but I've also been seeing a bunch of Spacemacs hangs.

At first I thought I was probably seeing https://github.com/syl20bnr/spacemacs/issues/1300 (because I'm on OS X 10.10), but I'm not convinced as my **savehist** doesn't appear to be large (5865 bytes).

CPU usage is 100%. An ActivityMonitor sample shows (for the only thread doing anything - the others are idle):

![spacemacs_hang](https://cloud.githubusercontent.com/assets/1526455/8334051/c37c6e7c-1a8d-11e5-810e-efec4244dc6c.png)

The other thing that caught my eye is that I'm also using the **haskell** layer.

**Comment by benmos** [comment]
Expanding the stack trace to show some more detail:

![untitled 12](https://cloud.githubusercontent.com/assets/1526455/8334258/ce02f0b8-1a8e-11e5-9bd6-ef6bbc71db88.png)
![untitled 13](https://cloud.githubusercontent.com/assets/1526455/8334261/cfbe4f88-1a8e-11e5-9aad-26d757b5bdd2.png)

Spacemacs: 0.102.2
Using: emacs-mac-port
(version): **"GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, Carbon Version 157 AppKit 1347.57)\n of 2015-06-23 on Zorba.local"**

**Comment by benmos** [comment]
These were my configuration layers:

```
     emacs-lisp
     benmos
     extra-langs
     haskell
     ibuffer
     html
     org
     sql
     shell
     (git :variables
          ;; git-magit-status-fullscreen f
          git-enable-github-support t
          git-gutter-use-fringe t)
     themes-megapack
```

I'll update here if I manage to isolate it any more - eg if I can confirm it's related to a particular layer (eg haskell).

**Comment by benmos** [comment]
Happened again. Similar stack traces showing up in Sample. Repeated Ctrl-Gs ineffective.

Three frames open. Two windows in each:
1. Dired + Shell
2. Haskell + Haskell
3. Dired + Haskell

After hang, frame 1 went blank... which seems to suggest that something was up with redrawing either the Dired or Shell windows?

**Comment by benmos** [comment]
![badframe](https://cloud.githubusercontent.com/assets/1526455/8405899/ce3b46e2-1e4f-11e5-98cc-68617f01e757.png)

That's a screenshot of frame 1 taken almost immediately before it went blank.
...all windows had line number display turned on.
... wonder if it's a coincidence that things went bad when the shell buffer got to exactly 1024 lines of output....

**Comment by benmos** [comment]
Update on last failure: It _did_ eventually come back to life ... after a few minutes and some more "C-g"s.

**Comment by benmos** [comment]
I'm afraid I'm going to have to give up on Spacemacs ... I don't currently have time to debug this issue.

**Comment by hhagblom** [comment]
I experience the same issue running spacemacs on Kubuntu 14.04

**Comment by kvelicka** [comment]
I've been using Spacemacs for Haskell development on OSX for the last year or two with no issues, so should definitely be something to do with Linux  (or Ubuntu and its derivatives) specifically. I've got a Xubuntu box available too, so if someone experienced with the codebase would like to help us by into this further, I'd like to try and help in some way.

**Comment by shenxs** [comment]
I have the same issue.When I open two windows and accidently  scroll the mouse wheel.
The left windows for `Racket`(racket mode), the right one for markdown .
The operate system is Ubuntu 16.04LTS
with emacs-24.5.1 spacemacs 0.105.21
anything more that i can provide?

**Comment by abhishiv** [comment]
Same issue. Happens after enabling mouse scrolling

```
  ;; Enable mouse support
  (unless window-system
    (global-set-key (kbd "<mouse-4>") 'scroll-down-line)
    (global-set-key (kbd "<mouse-5>") 'scroll-up-line))
```

**Comment by kennymalac** [comment]
Please fix this! This is NOT just Haskell mode. This bug kills kittens, I tell you!
For all of the people that suffer under this bug — use desktop-mode

**Comment by sdwolf** [comment]
You might have better luck trying to debug with the instructions from here: https://github.com/syl20bnr/spacemacs/wiki/Debugging#debug-a-freezing-instance. Also, try building emacs master from source, it contains some fixes that addresses infinite loops. Also try it together with latest spacemacs develop.

**Comment by Tyrion85** [comment]
This bug alone is making my Windows 10 Spacemacs installation completely unusable. Works fine on iOS and Ubuntu, for some reason - which only makes it worse when I'm on W10 and scroll down on a large file out of habit! Ctrl-G never helps, for the record.

**Comment by sdwolf** [comment]
Are you still able to reproduce this with newer versions of `emacs` and `spacemacs`? Try `25.3` or building `master` from source, also try with spacemacs `develop` branch. This might be an old bug that was fixed since I see old versions in the comments so far.

**Comment by srid** [comment]
I still see this happening. Using Emacs 26.
