### ISSUE TITLE
[Haskell]  `SPC m u` (find uses of identifier) missing

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#2078]
`SPC m u is undefined`
`haskell-mode-find-uses` gives `unknown command :uses`
This feature is too important to be missed!

**Comment by d12frosted** [comment]
`SPC m u is undefined`, because it's defined only when you enable `ghci-ng` support. Are you sure that you enabled it? 

As per another error - AFAIK, only `ghci-ng` supports `:uses`. Checkout it's [documentation](https://github.com/chrisdone/ghci-ng).

**Comment by d12frosted** [comment]
@TheBB what do you think?

**Comment by TheBB** [comment]
I think I can close this. It's old and you have the likely solution.
