### ISSUE TITLE
Use Helm header line for entering query

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#2082]
Recently Helm was added with an awesome feature that is outright better than all our current hacks: entering query in the header line, so the input is close to the best matches. Here is a demo:

![helm-echo-header-line-demo](https://cloud.githubusercontent.com/assets/4818719/8297961/a6618b3a-198c-11e5-9b54-98c86d36d796.gif)

According to Helm maintainer, you can use this function hook to hide the minibuffer during Helm session:

```elisp
(defun helm-hide-minibuffer-maybe ()
  (when (with-helm-buffer helm-echo-input-in-header-line)
    (let ((ov (make-overlay (point-min) (point-max) nil nil t)))
      (overlay-put ov 'window (selected-window))
      (overlay-put ov 'face (let ((bg-color (face-background 'default nil)))
                              `(:background ,bg-color :foreground ,bg-color)))
      (setq-local cursor-type nil))))

(add-hook 'helm-minibuffer-set-up-hook 'helm-hide-minibuffer-maybe)
```

How to try this feature:

- Update to latest Helm.
- Enable the feature: `(setq helm-echo-input-in-header-line t)`.
- Run the above code.
- Use it.

**Comment by tuhdo** [comment]
We can remove all the Helm entries in `display-buffer-alist` and actually use `helm-split-window-in-side-p`, so Helm window always opens in current window we are working on, and we will never have to move the eyes elsewhere.

**Comment by syl20bnr** [comment]
Nice, the referenced PR is merged, let's keep this issue open to discuss about the change here.

**Comment by person808** [comment]
Hmm... I'm not a fan of this change. With `helm-autoresize-mode` the prompt is constantly jumping around.

**Comment by tuhdo** [comment]
You have to set `helm-autoresize-max-height` and `helm-autoresize-min-height` to 40, which is 40% of current frame height. So, no more prompt constantly jumping around.

**Comment by person808** [comment]
@tuhdo Thats not what I use autoresize mode for though. I use it so I dont always have a large buffer at the bottom of my window.

**Comment by tuhdo** [comment]
Well you can always change backh `helm-echo-input-in-header-line` to `nil`. But I think this is a better default for everyone, since not many people use `helm-autoreisze-mode` and are even aware of it.

**Comment by sooheon** [comment]
Nice, this brings the UI more inline with ido or ivy.

**Comment by sooheon** [comment]
Hm, the only thing I would change is for the styling to inherit from the minibuffer, not helm's header bar.

**Comment by syl20bnr** [comment]
I would experiment with an empty line after the header to make a clear separation between the pattern and the first section header and have better symmetry overall (there is an empty line between sections).

**Comment by syl20bnr** [comment]
I wonder if at this point we are able to provide several UX for helm in spacemacs, I would love to see a dotfile variable to set the look'n feel for helm like `dotspacemacs-helm-interface` with possible values `regular`, `compact` where compact could be a merge of this issue with http://www.reddit.com/r/emacs/comments/2z7nbv/lean_helm_window/

What do you think ? Any other ideas ?
