### ISSUE TITLE
Any way to re-spellcheck the whole buffer after a dictionnary change?

### ISSUE THREAD

**Issue by StreakyCobra** [syl20bnr/spacemacs#2088]
After doing a `SPC S d` and changing the dictionary, the buffer keeps words coloured as mistakes until the cursor is placed on them. Is there a way to refresh the spell checking?

**Comment by tomekowal** [comment]
What I did, is `M-x` `flyspell-buffer`

**Comment by StreakyCobra** [comment]
:+1: Nice, I will try to do a PR to call `(flyspell-buffer)` after a dictionary change!
