### ISSUE TITLE
Add "evil-matchit" to the !vim layer

### ISSUE THREAD

**Issue by quartz55** [syl20bnr/spacemacs#2093]
Just saw a post from Chen Bin on g+, thought it would be a nice addition! :+1: 

https://github.com/redguardtoo/evil-matchit

**Comment by robbyoconnor** [comment]
Make a PR ;)

**Comment by TheBB** [comment]
Isn't `evil-matchit` in the core layer already?

**Comment by quartz55** [comment]
Oh that's right, my bad. Last time I tried in lua mode it didn't seem to be working :P

**Comment by redguardtoo** [comment]
@quartz55 , raise a issue on my github if you got any lua bug,

**Comment by hosh** [comment]
@redguardtoo I tried in Ruby mode and it didn't seem to be working. But I am not even sure if the evil-matchit-ruby is even loaded in Ruby mode. (I'm a newbie Spacemacs user). Is there something I can try to check?

**Comment by robbyoconnor** [comment]
@redguardtoo  raised an issue -- I just tested it.

**Comment by syl20bnr** [comment]
evil-matchit is only enabled in html and latex modes.
I'm still not convinced by evil-matchit, I tried it several time but found the behavior not intuitive, it does not what I expect. If someone can explain it to me clearly so I can see how it is useful, it would be great :-)

**Comment by robbyoconnor** [comment]
Is there an alternative to evil-matchit in spacemacs?

**Comment by TheBB** [comment]
You can try it out in Ruby:

```elisp
(add-hook 'ruby-mode-hook 'evil-matchit-mode)
```

**Comment by robbyoconnor** [comment]
@TheBB, to my .spacemacs?

**Comment by TheBB** [comment]
Yeah, in the `dotspacemacs/config` function.

**Comment by robbyoconnor** [comment]
No, it does not work.

**Comment by mrmargolis** [comment]
spacemacs uses enh-ruby-mode so you need to do something like this

     (global-evil-matchit-mode 1)
     (plist-put evilmi-plugins 'enh-ruby-mode '((evilmi-ruby-get-tag evilmi-ruby-jump)))

**Comment by robbyoconnor** [comment]
I would prefer this just work -- or at least add a config option to the other layers to use evil-matchit...or have an alternative...

**Comment by redguardtoo** [comment]
evilmi-plugins is the config options you can tweak any time.

**Comment by robbyoconnor** [comment]
@redguardtoo, could you pop on the gitter chat -- be much easier to ask questions there

**Comment by robbyoconnor** [comment]
Getting this: `if: Symbol's value as variable is void: evilmi-ruby-extract-keywords-howtos `

**Comment by redguardtoo** [comment]
evilmi-ruby-extract-keyword-howtos, typo in my README.

**Comment by robbyoconnor** [comment]
:heart: it works!!!!!

**Comment by hosh** [comment]
This works for me too, thanks! :+1:

**Comment by hosh** [comment]
@syl20bnr I'll take a stab at it.

I'm using `evil-matchit` for what I do with vim, and more specifically, the `%` operator. I'm new enough about this that I don't know how `evil-matchit` might differ. The highlighting isn't really that important to me. However, being able to use `%` to jump between the beginning of a method definition and the end of a method definition is very important for me.

I find that I use this the most when I wrote `rspec`. In `rspec`, I tend to write deeply-nested `context` blocks. Unlike the main Ruby code I like to write, with short method definitions, `rspec` can sometimes get very long.

I often need a reliable way to make sure the end of one context matches the context block I think it is, even if it is several pages up.

The second use I have for this is when I need to take one context block and move or copying it elsewhere. The level of nesting may not always be apparent, and the `%` allows me to check that. It also allows me to define the area I want to copy. 

Perhaps there are other tools that does the same thing. Because I can hit `%` with a single key stroke though, it's something I reach for first.

Obviously, this is very specialized. I write a lot of `rspec` code. I don't use this as much outside of `rspec`. If I have to guess, if I were writing deeply nested code that spans over a large area, I'd be more likely to use `%`.

**Comment by robbyoconnor** [comment]
I've added support already in the layers...it needs custom support depending on the major mode @hosh See #2233, #2239, #2242, and #2243

**Comment by hosh** [comment]
@robbyoconnor  When I said, "I'll take a stab at it", I am referring to "I'll take a stab at explaining why it is useful". It is in reply to https://github.com/syl20bnr/spacemacs/issues/2093#issuecomment-118462097

I do need to figure out how to get the `%` movement to work while in visual mode though.

**Comment by robbyoconnor** [comment]
@hosh -- sorry I really need to learn to read...does it even work in visual mode?

**Comment by hosh** [comment]
@robbyoconnor On my setup, the highlighting works, but it doesn't move to the matching brace (or whatever).

**Comment by redguardtoo** [comment]
I recommend `evilmi-jump-items` (whose hotkey is '%'), `evilmi-select-items`, `evilmi-delete-items`

Use them in *evil-normal-state*.

jump in visual state is a new feature added recently, so there may be some rough edges.

There are two reasons why '%' is perfect in normal state but has issues in visual state
- evil has some issue (see https://github.com/redguardtoo/evil-matchit/commit/62cef4f91a813a03d6d2df35fe4727757e94e530, the `evilmi--get-char-at-position` how I work around some issue)
- I don't use evil-matchit in visual state

Anyway, I will fix all the issue if you submit them on my github site.

**Comment by robbyoconnor** [comment]
@hosh -- pull in my PRs -- I tested those extensively...granted manual testing but still

**Comment by redguardtoo** [comment]
please note since v2.1, visual line state is perfectly supported.

**Comment by robbyoconnor** [comment]
I have open PRs for this...just look [here](https://github.com/syl20bnr/spacemacs/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3Arobbyoconnor+evil-matchit)

**Comment by hosh** [comment]
@redguardtoo @robbyoconnor matchit visual line state works great :+1:

**Comment by robbyoconnor** [comment]
I just added support code :)

**Comment by robbyoconnor** [comment]
The remaining ones #2242 and #2243 need to be tweaked; but the support is kinda there -- and quite frankly not convinced of their need...need to still work on them but by far the most requested seems to be #2233 and #2239 (both of which are now in `develop`. -- I figured I'd comment.

**Comment by TheBB** [comment]
Yeah, I agree. The discussion here has been jumping back and forth but I consider this essentially done, and remaining work on evil-matchit can be picked up in other issues.

**Comment by robbyoconnor** [comment]
It's pretty easy to add support for other languages, just follow the lead of the ruby and python layers. You might have to dig into the [evil-matchit](https://github.com/redguardtoo/evil-matchit) codebase to see how things work but @redguardtoo is VERYwilling to help. In some cases, it just works(tm).
