### ISSUE TITLE
Change of font in helm-org-headings

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#2096]
Candidates show in org-mode faces but when highlighted they change to another font, another size.

![](https://i.imgur.com/4Gg6znr.png)

**Comment by CestDiego** [comment]
This is still a thing.... ;_; anyone has any idea on how to debug this? @nashamri you have experience with faces in helm don't ya?

**Comment by nashamri** [comment]
I had some issues with org markup in heading lines. It probably is an emacs issue and how it combines different faces. I filed a similar issue on https://github.com/bbatsov/solarized-emacs/issues/201
and here's something that could be of help from emacs manual:
http://www.gnu.org/software/emacs/manual/html_node/elisp/Displaying-Faces.html

**Comment by justbur** [comment]
Just a guess but it looks like it may be falling back to a different font for bold face.

**Comment by StreakyCobra** [comment]
Could this issue have been solved with #3769 by any chance?

**Comment by TheBB** [comment]
No, sorry. This is something else.

**Comment by TheBB** [comment]
It's really just helm's problem to be honest. Should be reported upstream.

**Comment by CestDiego** [comment]
This *is* a helm problem. Helm candidates have some faces in them..but the selected item also has a face defined in Helm and that overrides the thing.......I guess changing the helm-item-selected-sth-sth to just inherit size,color, and just change the background should be enough.

**Comment by StreakyCobra** [comment]
Ok ok, I was just asking' when passing by :relaxed:

**Comment by TheBB** [comment]
Nobody seems to be interested in reporting this so closing.
