### ISSUE TITLE
TAB don't move block of code

### ISSUE THREAD

**Issue by idoo** [syl20bnr/spacemacs#2104]
When i press Shift + TAB — block moved to left
but when i pressed just TAB — block don't moved

I this this behavior isn't good.

**Comment by syl20bnr** [comment]
Do you use Vim or Emacs style ?
In Vim style you can use `<` and `>`.

**Comment by idoo** [comment]
@syl20bnr i know about `>` and `<`
but what about `TAB` ?
Thank you.

**Comment by TheBB** [comment]
Thanks, but neither tab nor backtab have any indenting effects here, whichever editing style.

It wouldn't be a problem to map tab and backtab to `>` and `<` in vim visual state, anyway, but since there doesn't seem to be a lot of support for this feature I will close this issue until there's a PR.
