### ISSUE TITLE
TAB vs <tab> and RET vs <return> in *spacemacs* buffer

### ISSUE THREAD

**Issue by sheijk** [syl20bnr/spacemacs#2105]
In the *spacemacs* buffer the tab key (<tab>) is bound to `forward-button` while Control-i (TAB in Emacs) is bound to `indent-for-tab-command` which will just signal an error. Usually those two keys behave the same in Emacs and I think they should do so here, too. Simply changing the binding from <tab> to TAB would be enough for this.

The same applies to Control-m (RET) vs <enter>.

**Comment by syl20bnr** [comment]
Thank you for reporting, a PR is welcome to fix this.

**Comment by StreakyCobra** [comment]
There is an ongoing more general discussion about how to handle difference between `<tab>`, `TAB` and other keybindings in #3472. I've reported and linked this issue there, so closing this one to avoid dispersing discussions.
