### ISSUE TITLE
ORG mode vim keys

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#2108]
I'm wondering if this is design or an issue so I'm happy to be corrected. 

In Org mode `>` and `<` move back and forwards a word, which seems pointless given that `w` and `b` do the same thing. 

It would be more useful imo if they indented lines like they usually do, but perhaps there's something greater going on that I'm unaware of.

**Comment by cpaulik** [comment]
`<` and `>` are bound to `org-metaleft` and `org-metaright` which means they indent headlines, move table columns etc. These functions are context aware so if there is nothing else to do they will move by words. If the binding is same for you than I think that is alright.

**Comment by geo7** [comment]
i have `command-evil-shift-right` and `left` actually. I turned off `evil-org` though as it interfered with `t` movements

**Comment by syl20bnr** [comment]
We should fix these key bindings then and use `org-metaleft/right` instead.

**Comment by StreakyCobra** [comment]
I don't think it should be changed. The goal of `evil-org` is exactly to improve `org` support for `evil` mode. If an user wants to disable this package, then it's up to him to rebind keys he is missing.

**Comment by TheBB** [comment]
I just tried disabling evil-org and the `<` and `>` keys do in fact dedent and indent respectively, as in regular evil. With `evil-org` they behave as @cpaulik mentioned.

I think we can close this then.
