### ISSUE TITLE
Reserve SPC m o for  user customization

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#2112]
This would be useful for exactly the same reasons `SPC o` is reserved.

Should be just a documentation change, unless some layers actually define a `SPC m o` prefix. I'm not sure if any do?

CC @mistnim.

**Comment by TheBB** [comment]
List of conflicting bindings I could find:

- [`gnus: message-mode`](https://github.com/syl20bnr/spacemacs/blob/42dc33ad66e711122da402865d60f24210a0618f/contrib/!email/gnus/packages.el#L97)
- [`org: org-mode`](https://github.com/syl20bnr/spacemacs/blob/42dc33ad66e711122da402865d60f24210a0618f/contrib/org/packages.el#L37)
- [`go: go-mode`](https://github.com/syl20bnr/spacemacs/blob/42dc33ad66e711122da402865d60f24210a0618f/contrib/!lang/go/extensions.el#L42-L53)
- [`agda: agda2-mode`](https://github.com/syl20bnr/spacemacs/blob/42dc33ad66e711122da402865d60f24210a0618f/contrib/!lang/agda/extensions.el#L66)
- [`ipython-notebook: ein:notebook-multilang-mode](https://github.com/syl20bnr/spacemacs/blob/42dc33ad66e711122da402865d60f24210a0618f/contrib/!lang/ipython-notebook/packages.el#L142)
- [`markdown: markdown-mode`](https://github.com/syl20bnr/spacemacs/blob/42dc33ad66e711122da402865d60f24210a0618f/contrib/!lang/markdown/packages.el#L98)

**Comment by syl20bnr** [comment]
I agree that it should be reserved as well.

**Comment by ralesi** [comment]
Is chance in changing user reserved bindings to `SPC .`? #1296
