### ISSUE TITLE
some dead link in the documentation

### ISSUE THREAD

**Issue by tevino** [syl20bnr/spacemacs#2115]
Some links in this page is dead:
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md

An example in **Python** section:
https://github.com/syl20bnr/spacemacs/tree/master/contrib/lang/python

Cause's the prefix `!`, the correct of above is:
https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/python

**Comment by TheBB** [comment]
I can't find any such dead links any more. The link you give is to the markdown version, which has been replaced by org for a while. I'm closing this.
