### ISSUE TITLE
add support for tao-theme

### ISSUE THREAD

**Issue by elais** [syl20bnr/spacemacs#2126]
[tao-theme](https://github.com/11111000000/tao-theme-emacs)

Right now when I attempt to initialize either its light or dark themes as my default, spacemacs stops loading and I'm left with default emacs. Here's the init output.

```emacs-lisp
Debugger entered--Lisp error: (error "Package `tao-yin-theme-' is unavailable")
  signal(error ("Package `tao-yin-theme-' is unavailable"))
  error("Package `%s-%s' is unavailable" tao-yin-theme "")
  package-compute-transaction(nil ((tao-yin-theme)))
  package-install(tao-yin-theme)
```

**Comment by cpaulik** [comment]
There is a list in Spacemacs that does the lookup between theme-names and MELPA packages if the package is not named `theme-name`-`theme`. See https://github.com/syl20bnr/spacemacs/pull/1981 for an example of how to add support for the tao-theme

**Comment by elais** [comment]
Added the theme, thanks for the advice! https://github.com/syl20bnr/spacemacs/pull/2129
