### ISSUE TITLE
Add rspec-mode in favor of ruby-test-mode in ruby layer

### ISSUE THREAD

**Issue by Naomarik** [syl20bnr/spacemacs#2128]
The current ruby-test mode is extremely outdated and doesn't utilize spring. Rspec mode has way more features and is up to date

https://github.com/pezra/rspec-mode

**Comment by StreakyCobra** [comment]
@robbyoconnor You ruby specialist, what do you think of this? :smiley:

**Comment by robbyoconnor** [comment]
See #3067 which addresses this.

**Comment by StreakyCobra** [comment]
@robbyoconnor :+1: Thx

**Comment by syl20bnr** [comment]
You can now choose rspec by setting the layer variable `ruby-test-runner`.
