### ISSUE TITLE
clear command doesn't work in eshell

### ISSUE THREAD

**Issue by chengyi** [syl20bnr/spacemacs#2133]
I use `SPC '` to enter the `eshell`, but `clear` command does not clear the screen
I check the shell configuration layer, however it has code to make `clear` command work in eshell.
is there something wrong? 
PS: I am a beginner in spacemacs :-)

**Comment by syl20bnr** [comment]
Thank you for the report, it should be fixed in develop.

**Comment by ale-batt** [comment]
`clear` work, but the prompt appear on the bottom of the screen rather than the top.
