### ISSUE TITLE
Toggle warnings off and on?

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#2134]
How about `SPC e w` to toggle warnings off/on permanently?

**Comment by codygman** [comment]
I'd be careful to not ignore too many warnings and advise enabling incomplete-patterns by putting `:set -fwarn-incomplete-patterns` in your ~/.ghci configuration file (on linux and mac, not sure where windows ghci config is).

You can also put any of these in your ghci configration file: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/options-sanity.html

I think just giving you a list of warnings would answer your question, but overall do you a disservice. What are you trying to hide or get rid of that is bothering you?

**Comment by xged** [comment]
Option to hide warnings (not disable them completely) would not hurt.
Like `Top level binding with no type signature` are no use when you are prototyping/heavy-editing or arguments that `shadows the existing binding` are no problem to me.

**Comment by TheBB** [comment]
From a cursory check it doesn't seem possible in flycheck to disable showing *all* warnings. You can turn off the individual checkers that produce them, or possibly configure the checkers themselves, but there doesn't seem to be a flycheck setting for: I only want to see errors, not warnings.

@lunaryorn?

**Comment by TheBB** [comment]
Removing the Haskell label as this is actually a flycheck feature request.

**Comment by d12frosted** [comment]
@TheBB yeah, good call.

**Comment by lunaryorn** [comment]
@TheBB You can filter the error list by level, see [`flycheck-error-list-minimum-level`](http://www.flycheck.org/manual/latest/Listing-errors.html#index-flycheck_002derror_002dlist_002dminimum_002dlevel).  A similar option exists for navigation, too. There's no way to inhibit warnings from being shown in the buffer itself, though, and I don't plan to add such a feature.

**Comment by TheBB** [comment]
Okay, so the answer becomes:

* To remove warnings from the error list, see :point_up:
* To remove warnings from the modeline, set `spaceline-flycheck-warning-p` to `nil` (in develop)
* To remove warnings *in general* (also from the buffer), you can advise `flycheck-relevant-error-p`.

We can possibly include such an advise as a toggle.

**Comment by lunaryorn** [comment]
@TheBB You forgot navigation :wink:

As for the advice, speaking as the maintainer of Flycheck I'm _strictly_ against any advices for Flycheck functionality—actually, against any advises at all, fwiw.  If you add advises for Flycheck I'll assume that you also take responsibility for _all_ Flycheck issues that appear in Spacemacs, for I'll refuse to deal with them. 

I'm sorry for the harsh words, but I've had my share of fun with broken and crappy advises, and I just don't feel like dealing with that anymore :relaxed:

If you'd like to have this feature then please implement it in Flycheck itself.  I said that I don't plan to add such a feature myself—I just don't need it—but that shouldn't stop anyone from giving it a shot and opening a corresponding pull request for Flycheck.  It's a reasonable feature, and nothing stands against merging it :relaxed:

**Comment by TheBB** [comment]
Okay, I interpreted your "don't plan to add such a feature" the wrong way, then.

**Comment by lunaryorn** [comment]
@TheBB I see, I'm sorry for the misunderstanding :blush:  I should have said that in a different way. Sorry
