### ISSUE TITLE
puppet indentation gets confused by 'if'

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#2136]
This is the indentation I'm getting with only puppet layer enabled.
```puppet
if $foo {
  42
  } else {
  10
  }
```

**Comment by syl20bnr** [comment]
It may be a conflict with `smartparens`, you can try to disable it with `SPC t p`.

**Comment by tko** [comment]
Makes no difference. I noticed puppet-mode is in progress of rewriting the indentation though lunaryorn/puppet-mode#7 isn't terribly active.

**Comment by StreakyCobra** [comment]
Either this is an upstream bug that has already been reported and we can't do anything about it, or it's a general problem about indentation which is discussed in a more general way in #3203. I'm closing this issue then, but feel free to open a new one in case of troubles :relaxed:
