### ISSUE TITLE
Flycheck do not fly

### ISSUE THREAD

**Issue by axyz** [syl20bnr/spacemacs#2138]
I'm trying to fine tune my react layer, however I have a problem with on the fly syntax checking:

I'm using eslint on web-mode and it works well, but only when i save the file, not as I type.

If I activate `js2-minor-mode` i get on the fly check, but with the internal js2-mode checker, not eslint.

I have no real previous experiences with the emacs ecosystem, however flycheck should be an on the fly checker, so I guess I'm doing something wrong in my configuration, or there is some kind of compatibility problem.

here it is a gist with the relevant parts of my (not yet finished) react layer:

https://gist.github.com/axyz/1fcad8c0f3b4e8b03840

**Comment by Funnnny** [comment]
Might be because of the configuration is save and mode enable only:

    contrib/syntax-checking/packages.el:      
    (setq flycheck-check-syntax-automatically '(save mode-enabled)

For it to check automatically, just add idle-change to the list

**Comment by axyz** [comment]
great now it works!

however is that intentional? I mean is a spacemacs policy to not check on the fly with fly-check by default?

in that Case the issue can be closed, but maybe it should be pointed out on the doc.

So, adding it to a layer may be an antipattern? shuld be added as a personal config on the `.spacemacs` file appending idle-change to `flycheck-check-syntax-automatically`?

**Comment by Funnnny** [comment]
You can add it into your .spacemacs config.

I don't really know why they did this, maybe because of performance, or a feature-match to vim.

**Comment by syl20bnr** [comment]
@axyz it should be fixed in 0.103 which is in production, can you confirm ?

**Comment by axyz** [comment]
now it seems to work correctly
