### ISSUE TITLE
Fancy frame-title-format

### ISSUE THREAD

**Issue by usharf** [syl20bnr/spacemacs#2139]
I wasn't able to find anything relating to setting up a title format. 

I'm using something like the following, which I've adapted from someone's dotemacs to remove dependency on `cl-lib` (sorry, but did't keep record). 

It'll set the title on an Emacs frame (GUI) to the `abbreviated-file-name [projectile-project-name]` - if projectile is enabled and there's an active project, otherwise, set title to buffer name.

for example

```
"~/spacemacs-private/.spacemacs [spacemacs-private]"
```

Taught it might be useful.

```emacs-lisp
  (defun spacemacs//frame-title-format ()
    "Return frame title with current project name, where applicable."
    (let ((file buffer-file-name))
       (if file
           (concat (abbreviate-file-name file)
                   (when (and (bound-and-true-p projectile-mode)
                              (projectile-project-p))
                     (format " [%s]" (projectile-project-name))))
           "%b")))

  (when (display-graphic-p)
    (setq frame-title-format '((:eval (spacemacs//frame-title-format)))))
```

**Comment by syl20bnr** [comment]
This is great :+1:  I would suggest to make it a dotspacemacs variable taking some sort of format where we invent that `%f` is the filename, `%F` is the filepath, `%p` the project name etc...

**Comment by usharf** [comment]
Looking into that!

**Comment by usharf** [comment]
@syl20bnr looking into that!

**Comment by usharf** [comment]
@syl20bnr tentative PR at #2299
