### ISSUE TITLE
C-g doesn't display the file path

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#2140]
In vim hitting <kbd>C-g</kbd> shows the path to the file relative to the current directory in the modeline(?). In spacemacs hitting it shows only `Quit`. I discovered <kbd>SPC f y</kbd> for show-and-copy but it's somewhat excessive for a quick reorientation and messes up the clipboard.

**Comment by chrisbarrett** [comment]
Yep, `C-g` is Emacs for 'quit'. My gut tells me it would be a bad idea to change this.

**Comment by hijarian** [comment]
@tko <kbd>C-g</kbd> is the Emacs keybinding for "_Cancel right **NOW**_". It's not for displaying the file path.

**Comment by syl20bnr** [comment]
You can also use `SPC f y` which will show the filepath in the minibuffer (as well as copy it).

**Comment by StreakyCobra** [comment]
As explained, `C-g` is an important emacs bindings, and for this reason it will not be changed in Spacemacs. Nothing prevents you to change this binding in your `.spacemacs` though :smile: 

I'm closing this issue. Feel free to open a new one in case of troubles (link this issues in it). :relaxed:

**Comment by teh0xqb** [comment]
I was using `SPC !` and then running the `pwd` cmd 😅
