### ISSUE TITLE
Suggestion for zooming key bindings

### ISSUE THREAD

**Issue by xfq** [syl20bnr/spacemacs#2144]
Currently, Spacemacs uses `SPC z x/f +` for zooming in, `SPC z x/f -` for zooming out, and `SPC z x/f =` for resetting.

In vanilla Emacs, `C-x C-+` and `C-x C-=` zoom in, `C-x C--` zooms out, and `C-x C-0` restores the default (global) face height. In DocView Mode, `+` and `=` enlarges the document, `-` shrinks the document, and `0` resets the document size/zoom level to the initial one.

In Firefox, `Ctrl/command` + `+`  and `Ctrl/command` + `=` zooms in, `Ctrl/command` + `-` zooms out, and `Ctrl/command` + `0` resets the zoom to 100%.

In Chromium and Google Chrome, `Ctrl/command` + `+`  and `Ctrl/command` + `=` enlarges everything on the page, `Ctrl/command` + `-` makes everything on the page smaller, `Ctrl+0` (and `⌘-0`) returns everything on the page to normal size.

In Internet Explorer, `Ctrl` + `+`  and `Ctrl` + `=` increases zoom (+10%), `Ctrl` + `-` decreases zoom (-10%), and `Ctrl` + `0` zooms to 100%.

IMHO Spacemacs should use `SPC z x/f +/=` for zooming in and `SPC z x/f 0` for resetting. Reasons:

* `=` is easier to type than `+`
* The behavior will be more consistent with other software.

Comments?

**Comment by shaief** [comment]
In my .spacemacs i added the following under `dotspacemacs/config`:
```
   (global-set-key (kbd "C-=") 'text-scale-increase)
   (global-set-key (kbd "C--") 'text-scale-decrease)
   (global-set-key (kbd "C-0") 'text-scale-mode)
```
IMHO it's better and more intuitive to use that `SPC z x/f +/=` which is long and very different than how people use it daily in their browsers.

**Comment by xfq** [comment]
@shaief Personally, I use single keys and key sequences as much as possible. I don't like key chords because they are bad for hand health. And that's the main reason I use Spacemacs.

**Comment by syl20bnr** [comment]
@xqf I agree with your proposal :+1:
