### ISSUE TITLE
Why is helm-spacemacs under SPC-f-e-h?

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#2145]
It opens a menu for displaying help for spacemacs layers as I see it, so wouldn’t make `SPC-h-<something>` and calling it `spacemacs-layers` more sense?

**Comment by syl20bnr** [comment]
At first it was just used to navigate in the configuration files so it has been put on `SPC f e` which is the prefix for Emacs files. We can find a binding for it under `SPC h` , maybe `SPC h s`. I would still keep around `SPC f e h` though.

**Comment by StreakyCobra** [comment]
@syl20bnr Do you want this change? If yes we can label it as `beginner friendly`, if no it can probably be closed :relaxed:

**Comment by syl20bnr** [comment]
If `SPC h s` is available then yes (even if `hs` in french is not really positive :-)).

**Comment by StreakyCobra** [comment]
`SPC h s` is bind **in the code only** to `'hl-save-highlights`, but as this package is excluded for 3 months now (because of a bug) we can probably chose another prefix for it the day we will bring it back.

**Comment by syl20bnr** [comment]
I thought about one maybe better, `SPC h h` ?

**Comment by syl20bnr** [comment]
I believe it is used for hl-anything too :-D

**Comment by syl20bnr** [comment]
oh I know !....

**Comment by syl20bnr** [comment]
`SPC h SPC` :-D

**Comment by TheBB** [comment]
You type github comments like @CestDiego types in IRC. :-P

**Comment by StreakyCobra** [comment]
Indeed for `SPC h h`, also used. I like `SPC h SPC` :+1:

Sold!

**Comment by CestDiego** [comment]
@TheBB lel.
