### ISSUE TITLE
problem in update 

### ISSUE THREAD

**Issue by chengyi** [syl20bnr/spacemacs#2147]
I click `update` in spacehome 
then it report it has 12 package to update 
I press y
it shows that
`no such file or directory, /home/osboxes/.emacs.d/elpa/org-20150622.nil`
is it a bug?

**Comment by syl20bnr** [comment]
Indeed it is a bug, can you reproduce it easily ?

**Comment by StreakyCobra** [comment]
@chengyi Have you been able to reproduce it?

**Comment by chengyi** [comment]
@StreakyCobra No, It seems work properly...

**Comment by StreakyCobra** [comment]
Ok, thanks for the response. I'm closing the issue as we can't do more for now. Feel free to open a new one in case of troubles :relaxed:
