### ISSUE TITLE
Search layers with Helm

### ISSUE THREAD

**Issue by zachlatta** [syl20bnr/spacemacs#2149]
Apologies for the simple question – just getting started with Spacemacs.

In the ["Discoverability" section of the documentation](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#discoverability) it mentions that Spacemacs includes "dedicated [helm][] sources to quickly find layers," but I'm having trouble finding the keybinding to search for layers with helm.

I'm probably missing something simple. Any thoughts?

**Comment by syl20bnr** [comment]
The key bindings is not very intuitive, it is `SPC f e h`, `f e` are for "file emacs" :-)

**Comment by zachlatta** [comment]
Awesome – thanks so much!
