### ISSUE TITLE
There is no rebase or merge functionality in the git layer

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2150]
Any reason why there is no functionality via the leader key for rebase and merge in the git layer?

**Comment by chrisbarrett** [comment]
You can access that functionality through `magit-status` (`SPC g s`), which is a good place to hang out when doing involved git stuff anyway.

- Rebase: `R`
- Merge: `m`

**Comment by robbyoconnor** [comment]
Weird
