### ISSUE TITLE
Look at ssh-agency for magit

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#2151]
From @tarsius
> ````
  ;; On Windows, we must use Git GUI to enter username and password
      ;; See: https://github.com/magit/magit/wiki/FAQ#windows-cannot-push-via-https
      (when (eq window-system 'w32)
        (setenv "GIT_ASKPASS" "git-gui--askpass"))
``` 
> Also see @npostavs' new ssh-agency package (also magit/magit#1911). He also wrote the Pushing with Magit from Windows wiki page a while ago.

**Comment by StreakyCobra** [comment]
There is a whole page of explanation [here](https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows). This should probably be documented/linked somewhere in the documentation.

Also the package is now [there](https://github.com/magit/ssh-agency).

@syl20bnr What do you want to do with this? Integrating it? Documentation only?

**Comment by StreakyCobra** [comment]
@syl20bnr Up
