### ISSUE TITLE
magit-next: `f` hangs emacs

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#2152]
Latest develop.
Pressing the `f` button in `magit-status` hangs emacs. `C-g` is still possible.

Also does the new evilification rebind `f`?

**Comment by robbyoconnor** [comment]
I got hit by something similar -- maybe I don't know emacs well yet

**Comment by chrisbarrett** [comment]
@syl20bnr : `M-x describe-key f` shows: 

    f runs the command evil-escape-evilified-state

**Comment by syl20bnr** [comment]
Thank you for the report. I had to add the support for wrappers in `evil-escape` which will be available on MELPA soon (version 2.28). You'll have to update develop when the new version of evil-escape is supported.

**Comment by syl20bnr** [comment]
mmmh maybe the magit-next support will be broken in the meantime so be sure to wait for the new evil-escape before updating develop, well you can still hard reset your git repo :-D

**Comment by cpaulik** [comment]
I've just updated and I still get the error
`Error in post-command-hook (evil-escape--evilified-state-passthrough): (void-variable evil-iedit-state-map)`.

But just the first time and it does not hang emacs. 

Is it on purpose that `f` does nothing? I would assume that we want it to run `git fetch` but these bindings are rebound according to the `f``-> `F` -> `C-f` rules.

**Comment by cpaulik** [comment]
After a restart `f` seems to work as intended so that should be fine
