### ISSUE TITLE
Not be able to enable relative number line by default

### ISSUE THREAD

**Issue by yejianye** [syl20bnr/spacemacs#2161]
Environment:
* spacemacs version: 0.102.2
* emacs version: 24.5.1
* OS: ubuntu 12.04

Steps:
I added 
``` elisp
(global-linum-mode)
(linum-relative-toggle)
```
in `dotspacemacs/config`. But when I started Emacs, it enables line numbers but not relative numbers.

**Comment by duerrp** [comment]
I use this:
```
  ;; Make linums relative by default
  (with-eval-after-load 'linum
    (linum-relative-toggle))
```

**Comment by yejianye** [comment]
That works, thanks!

**Comment by honza** [comment]
Works for me, too

**Comment by diego-alvarez-hs** [comment]
doesn't work for me.

Am I doing something wrong?
```
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
 This function is called at the very end of Spacemacs initialization after
layers configuration. You are free to put any user code."
  )

(defun dotspacemacs/config ()
  ;; Make linums relative by default
  (with-eval-after-load 'linum
    (linum-relative-toggle))
  )

```

**Comment by person808** [comment]
@diego-alvarez-hs Delete the `dotspacemacs/config` function and stick the code in the `dotspacemacs/user-config` function

**Comment by justbur** [comment]
That's correct

**Comment by diego-alvarez-hs** [comment]
It doesn't work :(
This is my current [.emacspace](http://pastebin.com/YcuH9WW5)

**Comment by diego-alvarez-hs** [comment]
If I start it manually with ```SPC :  linum-mode``` it works

**Comment by d1egoaz** [comment]
:dancer: This conf worked for me:
```
 ;; Make linums relative by default
  (global-linum-mode nil)
  (linum-relative-toggle)
```

**Comment by xoltar** [comment]
Any attempt to use linum-relative (including @d1egoaz 's solution above) now triggers cascades of this for me:
Error (use-package): linum-relative :config: Lisp nesting exceeds `max-lisp-eval-depth'

Though the autoload solution used to work, it doesn't anymore for some reason.

**Comment by justbur** [comment]
The max-lisp-eval-depth message is usually an infinite recursion error

**Comment by d1egoaz** [comment]
@xoltar maybe it's something failing before enabling linum.

Try to move  those lines at the beginning of user-config.

**Comment by justbur** [comment]
Just checked out the init function for this package, and it wasn't set up well. Hopefully #3416 will fix these issues.

**Comment by syl20bnr** [comment]
@yejianye should be fixed in develop, can you test it when you get a chance ?
