### ISSUE TITLE
Request to add notmuch

### ISSUE THREAD

**Issue by kvaneesh** [syl20bnr/spacemacs#2163]
Can we add a new layer for notmuch ?

**Comment by swaroopch** [comment]
@kvaneesh There is already a gnus layer - https://github.com/syl20bnr/spacemacs/tree/master/contrib/!email/gnus - please feel free to contribute a layer for notmuch - https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#configuration-layers

**Comment by kvaneesh** [comment]
I am not sure how a gnus layer would help. I currently have a private layer which does minimal stuff. But I don't enough to remap (SPC) which is used by notmuch layer.

NOTE: I solved that by using different keybinding instead of SPC in notmuch.

**Comment by cpaulik** [comment]
I've been playing with notmuch a little bit in the last weeks and have started a [private layer](https://github.com/cpaulik/dotfiles/blob/master/.spacemacs-config/config-layers/notmuch/packages.el) for it. But there is a lot of stuff that is not working. 

There are also issues with the starting page of notmuch and evil-movement keys.

**Comment by StreakyCobra** [comment]
@cpaulik Does your `notmuch` layer improved? :smile:

**Comment by cpaulik** [comment]
No. I'm using mu4e now.

**Comment by StreakyCobra** [comment]
@cpaulik Ok thanks.

@kvaneesh can `mu4e` solve your needs? (PR in progress:  #2514)

**Comment by kvaneesh** [comment]
I won't be switching to mu4e, and I am also not in a position to contribute the notmuch layer. So if you are looking at closing this issue, because nobody is going to look at this soon, please feel free to do so.

-aneesh

**Comment by StreakyCobra** [comment]
No no, your request is valid, I was just trying to see if there was some news on this side :relaxed:

**Comment by a13ph** [comment]
There's some work on it done by @lehoff

It will be linked or backlinked here when it's published :D

**Comment by lehoff** [comment]
I have raised #5239 re the collision I have with key bindings.

If someone finds my notmuch layer of any use, then I could clean it up.
But I think some work has to go into how to provide sensible key bindings for the layer. I would need some help on that.

**Comment by babilen** [comment]
@lehoff It would definitely be appreciated!

**Comment by lehoff** [comment]
Hi,

I have put something together, but it might be too specific for my usage to
generally shareable...

https://github.com/lehoff/dotfiles/tree/master/my-notmuch

E.g., I have my sendmail info in there,  I use msmtp to queue my mail and I
use offlineimap to fetch my mail. And I have nottoomuch-addresses hooked
into my post-sync hook outside emacs.

If someone has a good recommendation on how to separate those things out
then I could turn the generic things into a layer.
I don't fully grok the layers, so advice on how this could be done would be
nice. If I move the generic parts into a public notmuch layer, how should I
then do my personal configuration?

And I am open to changing some of the keymappings. I am using T to trash a
mail thread (only in the search window) or an individual mail. Would be
nice if it could would more like a and A - i.e., when viewing a mail "a"
archives the current message and "A" archives the entire thread. Maybe I
should just use "d" and "D" to get the same behaviour as archiving.

Thoughts are most welcome.

With some guidance we can have a layer for notmuch out very soon.

Cheers,
Torben



On 31 May 2016 at 22:33, Wolodja Wentland <notifications@github.com> wrote:

> @lehoff <https://github.com/lehoff> It would definitely be appreciated!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/2163#issuecomment-222811235>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AALyChlAnlTPBXekfvURDts0_lM1RE25ks5qHJsUgaJpZM4FQWN7>
> .
>



-- 
http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by awesomeaniruddh** [comment]
Any progress on this?

**Comment by jb55** [comment]
I wish!

**Comment by FrancescElies** [comment]
I'm also quite interested on this one, I am putting some stuff together most of the code coming from @lehoff 
Is there any place where things could be discussed? I would like to open a pull request with what I've done so far, and discuss the changes over there.

What I did so far lives in this commit https://github.com/FrancescElies/spacemacs/commit/359a7c10

Would someone be interested in helping out?

**Comment by jb55** [comment]
> Would someone be interested in helping out?

Yes! I have some time this week to test this.

**Comment by jb55** [comment]
I have limited connectivity (I'm in the middle of the woods somewhere)
so I can't do an extensive review via GitHub's interface. So I'll do
that here. I have a few comments:

## Message archiving

`spacemacs/notmuch-message-archive`:

I noticed when archiving from the search view it was using a custom
archiving routine (+archive -inbox -unread). This shouldn't be necessary
since `notmuch-search-archive-thread` does the same thing and can be
customized by changing `notmuch-archive-tags`. This also makes
`spacemacs/archive-by-removing-inbox-tag` redundant as well.

## zz bindings

Another thing that I think we should do is make the zz,zt,zb,etc evil
bindings work in notmuch-show. I use these a lot when reading email and
having to `f d z t` is a bit annoying. Right now z is bound to tree view
search so we could rebind that.

## custom hooks

```elisp
  ;; from https://github.com/fgeller/emacs.d/blob/master/email.org
  (add-hook 'notmuch-show-hook 'spacemacs/notmuch-show-prefer-html-over-text)
```

Should the notmuch layer be opinionated about how email is shown? There is
already a bunch of customizable options in notmuch-show for this.

## message-sendmail-f-is-evil

```elisp
    (setq message-sendmail-f-is-evil 't)
```

The notmuch layer probably shouldn't be opinionated about how email is sent...


## fixed previous buffer issue

```elisp
  ;; fixes: killing a notmuch buffer does not show the previous buffer
  (push "\\*notmuch.+\\*" spacemacs-useful-buffers-regexp)
```

OMG this was such a pain! Thanks!



I have some of my working patches at `github/jb55/spacemacs/notmuch-layer`,
mostly with respect to the message archiving issue for now. Let me know what you
think. Other than that it seems to be working great! I've just started testing
this so I'll add more comments if I have any more.

**Comment by mpe** [comment]
William Casarin <notifications@github.com> writes:
> ## fixed previous buffer issue
>
> ```elisp
>   ;; fixes: killing a notmuch buffer does not show the previous buffer
>   (push "\\*notmuch.+\\*" spacemacs-useful-buffers-regexp)
> ```
>
> OMG this was such a pain! Thanks!

I also have:

       (push "\\*unsent mail.*\\*" spacemacs-useful-buffers-regexp)

Though I suspect that buffer naming doesn't come from notmuch, so maybe
it's not the notmuch layers business to push that regexp. It is useful
though.

cheers

**Comment by FrancescElies** [comment]
@jb55, I agree with your points, I added a commit two more commits on top of yours addressing your suggestions. 
One to removing stuff and the other one addressing the `zz bindings`.

@mpe do you also have a branch with your configurations and stuff you would like to share?
If I understand correctly I believe `usent` name comes from gnus

**Comment by jb55** [comment]
> @jb55, I agree with your points, I added a commit two more commits on top of yours addressing your suggestions. 
> One to removing stuff and the other one addressing the `zz bindings`.

After thinking about it some more I'm a bit reluctant about the zz
bindings. My "real" goal was to have normal-mode-like feel when reading
email. Such as jumping around paragraphs with { and }, etc. I'm not sure
if there's a way to retain normal-mode bindings somehow.

I'm not that familiar with evilified states so I'm not even sure if this
is possible. For now I think we shouldn't re-add normal mode mappings to
the notmuch-show evilified state as that seems a bit ad-hoc...

**Comment by braham-snyder** [comment]
> I'm not that familiar with evilified states so I'm not even sure if this is possible. For now I think we shouldn't re-add normal mode mappings to the notmuch-show evilified state as that seems a bit ad-hoc...

FWIW, I've actually been trying to do basically just that a bit more generally: i.e., in evilified state, fall back to motion-state keybindings before global keybindings. This might be useful: https://github.com/syl20bnr/spacemacs/issues/9451#issuecomment-324407407

**Comment by FrancescElies** [comment]
> After thinking about it some more I'm a bit reluctant about the zz bindings. My "real" goal was to have normal-mode-like feel when reading email. Such as jumping around paragraphs with { and }, etc. I'm not sure if there's a way to retain normal-mode bindings somehow. I'm not that familiar with evilified states so I'm not even sure if this is possible. For now I think we shouldn't re-add normal mode mappings to the notmuch-show evilified state as that seems a bit ad-hoc...

@jb55 I am also not sure how to address that, the `zz` feels like a workaround to me too. By the way, I rebased my branch on top of yours.

**Comment by FrancescElies** [comment]
> FWIW, I've actually been trying to do basically just that a bit more generally: i.e., in evilified state, fall back to motion-state keybindings before global keybindings. The second half of this comment might be useful: #9451 (comment)

@braham-snyder Interesting, thanks for sharing! If I understand correctly this changes are in your fork only, right?

**Comment by braham-snyder** [comment]
> @braham-snyder Interesting, thanks for sharing! If I understand correctly this changes are in your fork only, right?

correct, though I'm currently hoping those changes (or something similar) will be adopted by upstream Spacemacs eventually

**Comment by FrancescElies** [comment]
@jb55 I picked @braham-snyder's https://github.com/braham-snyder/spacemacs/commit/24e91f874a4d4d696deb881aced162cd07a361e5, I will give it a shot during this week.

**Comment by jb55** [comment]
btw me and Francesc have been working on the new layer (albeit slowly). If anyone wants to contribute feel free to mail patches to `francesc.elies@gmail.com` and `jb55@jb55.com` (who needs github, we're in notmuch land now fam)... or we can pull from your tree ;)

We're coordinating at `git fetch https://github.com/FrancescElies/spacemacs cesc/notmuch-layer`

**Comment by jb55** [comment]
https://github.com/syl20bnr/spacemacs/pull/9927

**Comment by syl20bnr** [comment]
The layer has been merged in develop branch.

**Comment by jb55** [comment]
this can be closed

**Comment by d12frosted** [comment]
It will be closed with next release :)

P. S. Missclick

**Comment by jb55** [comment]
oh right
