### ISSUE TITLE
Request to add helm-ls-git

### ISSUE THREAD

**Issue by kvaneesh** [syl20bnr/spacemacs#2164]
Very useful when looking for files in a git repo

**Comment by swaroopch** [comment]
@kvaneesh Why not use `SPC p f` instead? (`helm-projectile-find-file`)

**Comment by kvaneesh** [comment]
ok good will switch to that.  Closing this.

**Comment by andyque** [comment]
@swaroopch  `SPC p f` is very slow compared to `helm-ls-git`, I have use it in my configure for months now and it works great. I also use the binding `SPC p f`.

**Comment by swaroopch** [comment]
@andyque Oh that is interesting!
