### ISSUE TITLE
run pytest automatically

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#2165]
Thanks for the new pytest variable cpaulik! Excellent work.

I have some thoughts about running these tests automatically below.

### pytest allows for automatic test running with the xdist add-on

With the excellent (and official afaik) [xdist](https://pytest.org/latest/xdist.html) addition to pytest (`pip install pytest-xdist`) you can watch a folder (i.e. the projectile root) and have the tests run anew automatically on every change in the folder or subdirectories. This is insanely great and makes testing much easier; no need to run the tests after each change. For this to work we should ideally have an icon in the mode line to tell whether you are red or green though, having the test buffer pop up each time would be annoying.

I currently have achieved automatic testing in spacemacs, but do not know whether the following is something worth (or possible) to add to the python layer:

### How I currently achieve automatic testing in spacemacs

Automatic python testing is possible to achieve currently by having a shell buffer open in spacemacs and running `py.test -f <project root>` from there. The buffer max size should be set much lower though since it will grow quickly (haven't found a way to do that yet). Is such an "emacs shell script" something that is worth adding to spacemacs? (`, t f "input folder" <RET>` for `tests-run-forever`). 

Another good thing about running the tests in an emacs shell is that you can split the window in two and have unit tests run in one window and integration tests in another (the latter are much slower and should not be mixed with unit tests). py.test makes separating unit and integration tests easy with the decorator `@pytest.mark` i.e. `@pytest.mark.integration`.
(`, t F "input folder" <RET> "input mark" <RET>`) for `tests-run-forever-with-mark`.

Just throwing it out there. I haven't got the time to package my recipies above yet, but that does not matter since it would probably be nice to discuss this first anyways.

**Comment by cpaulik** [comment]
I'm intrigued, automatic testing like that sounds nice. I think we could add it
as a simple command that runs the `pytest -f` command in a `comint` buffer,
similar to the current compilation command. I guess that with some window management we
could set the sizes and run two next to each other.

Do you think that this should be a spacemacs only feature or should we talk
about this upstream?

**Comment by endrebak** [comment]
It is trivial to implement I think; just add a shell script that runs the tests. Adding this would mostly be to expose this wonderful functionality to others.

I think just opening a shell window in the path of the project and then running `PYTHONPATH=. py.test -f` should be enough. This would trigger the tests to run on any change to the folder*. I do not know whether comint has any advantages over just a regular shell buffer? 

Afaics three things need to be done:
1. open new buffer
2. run shell script
3. limit the size of the buffer, since it would grow quickly. 1000 lines should be enough.

I just got a second monitor to run tests on so I won't be using emacs for this after all, but for those that only have one screen, having 1/4 dedicated to automatic tests might be very helpful. 

I should probably close this, since I'm not that interested after all.

Ps. if anyone knows how to automatically crop a buffer, please reply. I might do this in the end even if I do not need it myself.

*(This has many more benefits than you first think of; for example, when you have failing tests you add print statements to the code. Now you can just save and then the code is reexecuted automatically, showing the desired output.)
