### ISSUE TITLE
Symbol's value as variable is void: evil-escape-inhibit

### ISSUE THREAD

**Issue by dsdshcym** [syl20bnr/spacemacs#2167]
I got this message when I use magit 2.1 in version 0.103.0. 

When I hit ```K``` I got this message and the cursor wouldn't go up a line.

Something is wrong with ```spacemacs//evilify-wrapper```. Since there is only one appearance of ```evil-escape-inhibit``` in the whole project, which is this function.

**Comment by cpaulik** [comment]
Have you tried updating evil-escape from MELPA?

**Comment by tko** [comment]
Saw the same problem, upgrading/reinstalling evil-escape worked for me.

**Comment by dsdshcym** [comment]
@cpaulik @tko I exclueded ```evil-escape``` since I started using spacemacs. So that's why this symbol is void.

**Comment by andyque** [comment]
I also have this issue, I just re-include the `evil-escape` again to resolve this issue.

**Comment by syl20bnr** [comment]
Oops sorry I forgot to made it optional, I'll fix this tonight.

**Comment by syl20bnr** [comment]
Should be fixed in 0.103.1

**Comment by dsdshcym** [comment]
@syl20bnr Thank you for the quick fix. I'll close my PR.
