### ISSUE TITLE
Some UI elements appear fuzzy on a Retina display

### ISSUE THREAD

**Issue by avendael** [syl20bnr/spacemacs#217]
Here's a screenshot of how the `~` at the gutter and the powerline waves look like on a Retina screen:

![screen shot 2014-12-07 at 03 50 58](https://cloud.githubusercontent.com/assets/53690/5328680/a8b2ac16-7dc4-11e4-8080-111c790fa398.png)

It would be nice if they also appear sharp on a retina screen.

**Comment by bebound** [comment]
@person808 This screenshot looks pretty nice, how could you make this? Thank you.  ![](https://raw.githubusercontent.com/syl20bnr/spacemacs/develop/doc/img/powerline-update.png)

**Comment by d12frosted** [comment]
Yeah, I don't like waves on retina as well. That's why I use `utf-8` separator:

<img width="137" alt="screenshot 2015-12-07 12 19 37" src="https://cloud.githubusercontent.com/assets/6507913/11624483/e87b8c68-9cdc-11e5-8eb9-34389cff5058.png">

```
(setq powerline-default-separator 'utf-8)
```

**Comment by bebound** [comment]
@d12frosted Thanks for your advice, it looks better now. But person808's separator looks fancy and clear.
@syl20bnr Do you have any idea?
