### ISSUE TITLE
Anyone else unable to open projectile projects?

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#2170]
Downloaded `103.0` and when I try to select a project in `helm-projectile` with enter it just skips to the first project in the list.

Happens with `C-c p p` and `helm-projectile`.

I both updated a lot of packages from `paradox` and updated `spacemacs` at the same time.

Just wondering if anyone else has this problem.

**Comment by endrebak** [comment]
When I try to do things like invalidate the cache the following message shows:

`projectile-dirconfig-file: Symbol's value as variable is void: it`

It happens for a lot of other `projectile` commands too.

It seems like all other helm commands work in the `helm-projectile` menu except enter.

**Comment by endrebak** [comment]
This happens in `102.2` also, so must have something to do with my `paradox` updates, not `spacemacs`.

**Comment by endrebak** [comment]
Reinstalling `spacemacs` from scratch seemed to work.

**Comment by rpglover64** [comment]
I'm experiencing a similar issue; reinstalling didn't work for me.

**Comment by rpglover64** [comment]
It looks like it has to be a problem with the anaphoric forms from `dash`.

**Comment by endrebak** [comment]
Yeah, I cleared the projectile cache, updated all paradox packages from scratch and downgraded spacemacs and then upgraded. Did all of the above several times plus manually uninstalling `projectile` from `paradox`. Dunno what finally made it work again.

I have `dash` installed but do not use it from emacs. Perhaps I should remove.

**Comment by rpglover64** [comment]
`dash` is basically a library; `projectile` uses it.

I found this other issue that seems relevant: Fuco1/smartparens/issues/154

**Comment by endrebak** [comment]
Happened again on another machine. :/

**Comment by rpglover64** [comment]
Please reopen the issue.

**Comment by endrebak** [comment]
If you insist 😀

**Comment by ecocode** [comment]
same here :(

**Comment by Banashek** [comment]
Had the same thing happen to me after installing a new package and updating at the same time.

What fixed it for me was to delete both projectile AND dash (dependency), and reinstall projectile.

Reference issues that got me up and running:

* [Projectile 788](https://github.com/bbatsov/projectile/issues/788)
* [Spacemacs 2282](https://github.com/syl20bnr/spacemacs/issues/2282)

**Comment by StreakyCobra** [comment]
Is anyone still experiencing this issue?

**Comment by endrebak** [comment]
Prolly not :)

**Comment by StreakyCobra** [comment]
:smile: :+1:

**Comment by chukcha2** [comment]
I started experiencing this issue or something that is very similar of that. Reinstalling projectile and dash did not help. I get the same error (`Symbol's value as variable is void: it`) when I execute `helm-find-files` from org mode. Executing this command from other files/modes seems to work fine.
