### ISSUE TITLE
ENSLIME does not ask for subproject

### ISSUE THREAD

**Issue by alexanderkjeldaas** [syl20bnr/spacemacs#2175]
I am not sure what the bug is here, but I am not getting ENSLIME to work for a `build.sbt` file containing subproject.

The ENSLIME documentation indicates that it should prompt for which subproject to use in this case.  I see no such prompt.

**Comment by chrisbarrett** [comment]
You're better off asking the ENSIME maintainers for help on issues like this. :)

https://gitter.im/ensime/ensime-server

**Comment by alexanderkjeldaas** [comment]
Ok, will do.
