### ISSUE TITLE
0.103: getting diff-hl in the margin also in a GUI setup

### ISSUE THREAD

**Issue by emmanueltouzery** [syl20bnr/spacemacs#2180]
since 0.103 version-control uses diff-hl not anymore git-gutter.
in my .spacemacs I put:

      (setq diff-hl-side 'left)

same as I had left-fringe for git-gutter. But I doubt it has anything to do with my problem. The problem is that when just starting `emacs` diff-hl displays in the fringe as expected. However if I start it with `emacsclient -c "$@" --alternate-editor= &` then I get diff-hl consistently in the margin instead of the fringe.

if I comment these lines in the `version-control` layer then it's again all ok:

    (unless (display-graphic-p)
       (setq diff-hl-side 'left)
       (diff-hl-margin-mode))

it looks like emacsclient somehow triggers `display-graphic-p` to be false. I attempted changing the condition to `window-system` instead of `display-graphic-p` but the problem remains.

**Comment by emmanueltouzery** [comment]
now added `(diff-hl-margin-mode 0)` in my `.spacemacs` as a workaround.

**Comment by emmanueltouzery** [comment]
this might be related to this: http://stackoverflow.com/a/5801740/516188

> You can start emacs in daemon mode, then later tell it to create a graphical frame. [..]
> As a result of this, avoid putting code in your .emacs that depends on window-system. Instead, put code like your set-frame-size example in a hook function which runs after a frame is created

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
