### ISSUE TITLE
Documentation for updating Spacemacs needs updating

### ISSUE THREAD

**Issue by xfq** [syl20bnr/spacemacs#2189]
In the release notes for 0.103.0:

> Clicking on the up arrow in the mode-line will now update Spacemacs.

If so, `README.md` and `doc/DOCUMENTATION.org` needs updating:

* https://github.com/syl20bnr/spacemacs/blob/master/README.md#update
* https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#update-and-rollback

**Comment by syl20bnr** [comment]
I have to update it indeed. I will do it a the next few days.

**Comment by geo7** [comment]
Can this be closed now?

**Comment by StreakyCobra** [comment]
This has been fixed in `develop` and `master` already. Closing it then.
