### ISSUE TITLE
magit-next - k kills in visual mode

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#2192]
Thanks for all the other fixes but I think I've discovered another problem with this pesky `k` key.

Trying to stage a region, navigate to a hunk, press `S-v`, `k` is now bound to kill again. Same behaviour if trying to select multiple files for some action.

**Comment by syl20bnr** [comment]
The visual state is a tricky one. I'm not sure to be able to fix this but I will try.

**Comment by cpaulik** [comment]
This was fixed for me with https://github.com/syl20bnr/spacemacs/commit/3a829ce89e7b347f317d0263794e93c02bdeb995

Seems to be the same as https://github.com/syl20bnr/spacemacs/issues/1804 but for magit 2.0 which was released July 1st if I remember correctly
