### ISSUE TITLE
no keybinding to finish magit commit

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#2196]
in vim style
1) bring up magit <kbd>SPC g s</kbd>
2) stage some changes <kbd>s</kbd>
3) commit <kbd>c c</kbd>
4) write commit message
5) ???

COMMIT_EDITMSG is in Text mode and there are no obvious keybindings to finish the commit. <kbd>,</kbd> says `No previous search` and <kbd>SPC m</kbd> says `SPC m is undefined`

**Comment by justbur** [comment]
`C-c C-c` to commit and `C-c C-k` to abort both work for me. I'm not sure if there are other bindings for these.

**Comment by kRITZCREEK** [comment]
Before 0.103 there was `, c c`

**Comment by tko** [comment]
Hmm, so commit and abort are in with-editor-mode(-map) and bunch of commit helpers (adding Acked-by and other git conventions) are in git-commit-mode(-map) -- they're both minor modes which I guess leads to all major mode leader keys being left unmapped :-/

**Comment by mightybyte** [comment]
I have this problem too.  The docs say to use SPC m c c, but as this issue says, SPC m is undefined.

**Comment by schmooser** [comment]
Same thing for me. Using `C-c C-C` but that's not obvious at all.

**Comment by TheBB** [comment]
The echo area does say "When done with a buffer, type C-c C-c". The git layer documentation (in develop at least) also says this.

Unfortunately there's no easy way to make a leader key binding just for this buffer any more.

**Comment by justbur** [comment]
@TheBB I think you should close this

**Comment by tasmo** [comment]
This is not a keybinding what I expect from SPACEmacs.

**Comment by kRITZCREEK** [comment]
tasmo , c works. Just escape to normal Mode and hit , c

**Comment by tasmo** [comment]
@kRITZCREEK Wow, that works. Thank you!

**Comment by deb0ch** [comment]
I usually use `SPC b d`, just closing the buffer works like a charm because it is the way it works in command-line git

**Comment by tasmo** [comment]
@deb0ch  `SPC f s` followed by `SPC b c` didn't work for me. It just does when I call git from the command line but not with magit.

**Comment by deb0ch** [comment]
@tasmo I was talking of `SPC b d` with a 'd', but maybe you made a typo ?

I'm talking of doing that after editing the commit message when in the COMMIT_EDITMSG buffer-file, opened when pressing `c` in the `*magit-commit-popup*` buffer.

**Comment by tasmo** [comment]
@deb0ch Thank you. It was not a typo. Strange is that `SPC b k` is killing the buffer and it won't work but with `SPC b d`. Don't see the logic behind.

**Comment by dhanjit** [comment]
C-c C-c doesn't work as it does write the commit message however when I do git status from terminal it still says staged but not comited.

**Comment by robbert-vdh** [comment]
I just close the buffer with `ZZ` (evil-mode), just like you'd do in command line git.

**Comment by HaoZeke** [comment]
I think the canonical binding is `, ,` or `, c` which seem semantic and are still working as of the develop branch. (0.300)

**Comment by kreimben** [comment]
Save commit messages, press ```,```.
It works.
