### ISSUE TITLE
Ess can not startup.

### ISSUE THREAD

**Issue by hujianxin** [syl20bnr/spacemacs#2197]
I added ess to layers and enter 'space e s s'.  but when I try to run any of the commands with SPC-m-whatever, I get SPC-m isn't defined.

**Comment by TheBB** [comment]
What is `SPC e s s` supposed to do? I don't see this keybinding anywhere in the `ess` layer.

**Comment by hujianxin** [comment]
@TheBB I get it in the readme file of ess layer.`In order to speed up the boot time of Spacemacs, ESS must be loaded manually via the key binding: SPC e s s`

**Comment by hujianxin** [comment]
My os is ubuntu 15.04

**Comment by TheBB** [comment]
Right, I'm blind, sorry.

**Comment by hujianxin** [comment]
@TheBB  I reinstall Emacs, and it works. WHF!!!hahhahah
