### ISSUE TITLE
Spacemacs ignores .projectile file

### ISSUE THREAD

**Issue by AgIt0** [syl20bnr/spacemacs#2199]
Projectile allows you to create a `.projectile` which has ignore patterns for your search: https://github.com/bbatsov/projectile#ignoring-files

But after the last release it no longer is taking the `.projectile` file into account.
I don't know nearly enough elisp to fix it, but was able to narrow it down to this commit:
https://github.com/syl20bnr/spacemacs/commit/2feaeb9fbaaef564029022e8246fdd21618539e5

**Comment by syl20bnr** [comment]
I see, ideally we have to add the support for it in `helm-ag`.

**Comment by mosic** [comment]
@AgIt0 I encountered the same problem and fixed it for myself by creating an [`.agignore` file](https://github.com/ggreer/the_silver_searcher/wiki/Advanced-Usage), which seems to work nicely with `helm-ag`. Hope that helps.

**Comment by d12frosted** [comment]
From my experience, `.projectile` doesn't play nice when you have `.gitignore`. I would try asking for help upstream.

**Comment by fatlazycat** [comment]
Is there anyway currently to get it to pick up .projectile ? trying to get excludes into .projectile for helm projectile grep

**Comment by AgIt0** [comment]
well I don't think so.. I switched to using .agignore like @mosic mentioned and I use helm-projectile-ag

**Comment by fatlazycat** [comment]
thanks - yeah installed ag and seems to work with the .gitignore
