### ISSUE TITLE
Magit 2 support

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#2203]
A lot of stuff is broken, "K" doesn't discard, "k" doesn't move cursor upwards.

**Comment by cpaulik** [comment]
Which version are you using? the `k` issues should be solved in the latest release. see https://github.com/syl20bnr/spacemacs/issues/2183

**Comment by Eilie** [comment]
@cpaulik Oh great, updated just couple of hours prior to the fix. Works now, thank you!
