### ISSUE TITLE
Missing characters in terminal spacemacs

### ISSUE THREAD

**Issue by jamiecollinson** [syl20bnr/spacemacs#2207]
Forgive me if this is obvious, or not really a spacemacs issue (I could well believe it to be the case, though I don't seem to get it with regular emacs).

I'm running the latest spacemacs on emacs 24.3.1 on the slightly esoteric setup of a Chromebook Pixel 2 running Ubuntu 12.04 in a chroot via the excellent https://github.com/dnschneid/crouton.

I'm missing lots of characters which are replaced by ?s. See screenshot:

![screenshot 2015-07-03 at 18 11 03](https://cloud.githubusercontent.com/assets/3263722/8502940/efd71c74-21ae-11e5-92b6-aa45876a4ce6.png)

I assume this may be a font, locale or character encoding issue, but no amount of googling variants on "spacemacs missing characters" or "emacs terminal question marks" has turned anything up, so I hoped someone might be able to point me in the right direction or recognise the issue.

**Comment by hijarian** [comment]
Question marks mean that renderer (whether it's Emacs or terminal) cannot find correct glyph for character code point in the selected font. What is the font used in your terminal? Screenshot looks like it's Source Code Pro or DejaVu Sans but if it's really "esoteric" computer setup you can easily have damaged fonts stripped of non-ASCII glyphs.

Also, of course you should make sure that you have *everything* set to UTF-8. Before output on screen you have `LANG`, `LC_LOCALE`, maybe something other environment vars I am not aware of, Emacs and your terminal settings.

**Comment by jamiecollinson** [comment]
@hijarian - thanks for the hint in the right direction. I exported a `LANG` environment variable and managed to switch the question marks to unicode codes (e.g. `\u2517`) so I'm pretty sure it'll fix it with a bit more playing.

I'll post back once I have it sorted in case it's useful to someone else.

**Comment by hijarian** [comment]
@jamiecollinson If it's `LANG` issue, then probably your systemwide `LANG` is set to some single-byte encoding, which you should nuke from orbit as soon as possible, and switch to Unicode based one. In your case it's probably `en_GB.UTF-8` ;)

**Comment by jamiecollinson** [comment]
@hijarian - thanks again :-)

Turns out I had a very limited language pack, so did:
`sudo apt-get install language-pack-en`
`sudo update-locale LANG=en_GB.UTF-8`

Now I'm just missing a few characters in the status bar, which I'm guessing is a font issue:

![screenshot 2015-07-06 at 18 20 39](https://cloud.githubusercontent.com/assets/3263722/8528625/07018cfe-240c-11e5-846e-b56faba4c3cd.png)

**Comment by TheBB** [comment]
@jamiecollinson The powerline separators need a patched font. See e.g. [here](https://github.com/powerline/fonts).

**Comment by StreakyCobra** [comment]
All the question of @jamiecollinson seems to have been answered, so I close this issue. Feel free to open an new one in case of troubles :relaxed:

**Comment by adrianbrink** [comment]
I am on Ubuntu Server 16.04. I've updated the locale as described above by installing the package. I've also installed the powerline fonts but I still see the question marks as in the first screenshot.

**Comment by thirdknife** [comment]
I have installed on Mac, I have some fonts missing. I am also unable to submit a bug from with in spacemacs. C-c is undefined. 

<img width="1440" alt="screen shot 2017-07-24 at 11 27 37 am" src="https://user-images.githubusercontent.com/885125/28511462-bd4cf2fc-7066-11e7-9bbc-056521a47428.png">

**Comment by thirdknife** [comment]
I figured it out, it was an iterm related font rendering in Unicode issue. You have to set the font Source code pro for Unicode inside profile settings.
