### ISSUE TITLE
Enter, Backspace broken with structured haskell mode

### ISSUE THREAD

**Issue by ajnsit** [syl20bnr/spacemacs#2211]
I enabled structured haskell mode to try it out and see some strange issues -
1. Backspace would only delete variables, not keywords or operators!
2. Enter key introduces newlines even in normal mode, just like it would in insert mode

I enabled structured haskell mode by adding the following to my configuration layers -

    (haskell :variables
             haskell-enable-hindent-style "johan-tibell"
             haskell-ghci-ng-support t
             haskell-enable-shm-support t
             )

These may be errors in structured-haskell-mode itself (I'm not sure yet). However I believe we should atleast mention it in the documentation for haskell layer that SHM may cause this behaviour.

**Comment by d12frosted** [comment]
It's structured-haskell-feature :smile: It always was so - but it's not even documented in `structured-haskell-mode` documentation. In any case, I don't really think that Haskell layer's README file is a good place for this.

About the enter key - structured-haskell-mode doesn't play well with evil - see #1048.

@TheBB I think it should be closed.

P. S. it's not Helm, but Haskell :-p
