### ISSUE TITLE
Cannot open load file: no such file or directory, magit

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#2214]
NOTE: I'm using master

```shell
~/.emacs.d $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	srecode-map.el

nothing added to commit but untracked files present (use "git add" to track)
~/.emacs.d $ git remote -v
checkversion	https://github.com/syl20bnr/spacemacs (fetch)
checkversion	https://github.com/syl20bnr/spacemacs (push)
origin	https://github.com/syl20bnr/spacemacs (fetch)
origin	https://github.com/syl20bnr/spacemacs (push)
~/.emacs.d $ git pull
Already up-to-date.
```

The issue:

I try opening magit with `SPC g s`, but I get:

```
command-execute: Cannot open load file: no such file or directory, magit
```

So I try using M-x magit-status, same result.

So I try looking at help for magit-status with C-h f magit-status:

```
magit-status is an interactive autoloaded Lisp function.

It is bound to M-m g s, SPC g s.

[Arg list not available until function definition is loaded.]

Not documented.
```

Apparently it's not being loaded somehow?

Update: I checked to make sure magit is there.

```shell
~/.emacs.d $ find -iname "*magit*"
./elpa/magit-20150701.1326
./elpa/magit-20150701.1326/magit-bisect.elc
./elpa/magit-20150701.1326/magit-section.el
./elpa/magit-20150701.1326/magit-utils.el
./elpa/magit-20150701.1326/magit-blame.el
./elpa/magit-20150701.1326/magit-autoloads.el
./elpa/magit-20150701.1326/magit-extras.el
./elpa/magit-20150701.1326/magit-pkg.el
./elpa/magit-20150701.1326/magit-ediff.elc
./elpa/magit-20150701.1326/magit-git.el
./elpa/magit-20150701.1326/magit-apply.el
./elpa/magit-20150701.1326/magit.el
./elpa/magit-20150701.1326/magit-remote.elc
./elpa/magit-20150701.1326/magit-commit.elc
./elpa/magit-20150701.1326/magit-utils.elc
./elpa/magit-20150701.1326/magit-extras.elc
./elpa/magit-20150701.1326/magit-process.elc
./elpa/magit-20150701.1326/magit-wip.el
./elpa/magit-20150701.1326/magit-remote.el
./elpa/magit-20150701.1326/magit.info
./elpa/magit-20150701.1326/magit-git.elc
./elpa/magit-20150701.1326/magit-stash.elc
./elpa/magit-20150701.1326/magit.elc
./elpa/magit-20150701.1326/magit-core.el
./elpa/magit-20150701.1326/magit-ediff.el
./elpa/magit-20150701.1326/magit-log.el
./elpa/magit-20150701.1326/magit-apply.elc
./elpa/magit-20150701.1326/magit-log.elc
./elpa/magit-20150701.1326/magit-blame.elc
./elpa/magit-20150701.1326/magit-stash.el
./elpa/magit-20150701.1326/magit-diff.el
./elpa/magit-20150701.1326/magit-commit.el
./elpa/magit-20150701.1326/magit-diff.elc
./elpa/magit-20150701.1326/magit-bisect.el
./elpa/magit-20150701.1326/magit-wip.elc
./elpa/magit-20150701.1326/magit-core.elc
./elpa/magit-20150701.1326/magit-process.el
./elpa/magit-20150701.1326/magit-sequence.elc
./elpa/magit-20150701.1326/magit-sequence.el
./elpa/magit-20150701.1326/magit-mode.el
./elpa/magit-20150701.1326/magit-mode.elc
./elpa/magit-20150701.1326/magit-section.elc
./contrib/!source-control/github/extensions/magit-gh-pulls

./contrib/!source-control/github/extensions/magit-gh-pulls/magit-gh-pulls.el
```

**Comment by codygman** [comment]
I'm trying to think of differences between now and the last time I used spacemacs where magit worked fine. I think I may have clicked Update, ran into #839, then updated manually with:

SPC-a-P, U, x (using Paradox).

**Comment by codygman** [comment]
So I uninstalled magit manually with paradox, closed spacemacs, the re-opened it. Upon opening it reinstalled magit and everything seems to work. I'm sure it's of interest how this ever happened though.

**Comment by syl20bnr** [comment]
I have no idea about what could cause that, although you gave a lot of info this is not enough, I hope we will be able to reproduce it one more time.

**Comment by codygman** [comment]
@syl20bnr 

I'm going to try and reproduce it. Luckily I actually freshly recloned spacemacs today and haven't been using it long. The only steps I can remember are (on an ubuntu 15.04 machine without spacemacs and with emacs 24.4.1):

1. `git clone --recursive https://github.com/syl20bnr/spacemacs ~/.emacs.d1
2. Open spacemacs, let it install everything
3. close spacemacs
4. re-open spacemacs
5. run magit-status on an existing project, it should work
6. click update, wait for it to fail with nil version error.
7. update manually using Paradox with `SPC-a-P, U, x`
8. hopefully we've reproduced it, since I can't remember *anything* else I've done.

Hopefully in a bit I'll be able to try these out again.

**Comment by codygman** [comment]
Looking through issues, it appears that  #1915 could be related? Something wasn't provided after the user tried using the update functionality, so there is one commonality.

The Haskell programmer in me wants to ask where is the mutation in the update function that could affect the loading of these modules?

**Comment by antoinelyset** [comment]
I get the same error too. I don't know how to help, I'm new to the (spac)emacs ecosystem, but if you want me too provide more information, don't hesitate.

**Comment by JoshTGreenwood** [comment]
I had the same issue listed here.  Manually updating packages (`SPC-a-P, U, x (using Paradox).` fixed it for me.

**Comment by StreakyCobra** [comment]
@codygman @antoinelyset @JoshTGreenwood Does anyone of you encountered this issue on a recent release?

**Comment by codygman** [comment]
I don't think I do, but can verify later.

**Comment by StreakyCobra** [comment]
Ok. Try it, and if it is not a problem anymore, then we can probably close the issue, as it's an old one without activity for last 3 months :relaxed:

**Comment by codygman** [comment]
@StreakyCobra It's not happening anymore!

**Comment by phfrohring** [comment]
It's happening to me... :disappointed: :

**Comment by phfrohring** [comment]
Well... It's corrected. For some reason `list-packages` deleted the magit directory.  Rolled back to previous commit of my `.emacs.d` re-update the thing and the error was gone and the updated magit dir happily sitting where it should have.

=> this bug may have nothing to do with magit, cannot reproduce it.

Magit is great btw :+1: I secretly thank you every day :smile:
