### ISSUE TITLE
evil-matchit not working for Ruby

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2215]
[evil-matchit](https://github.com/redguardtoo/evil-matchit) is not working for ruby files.

**Comment by syl20bnr** [comment]
related to #2093 (see https://github.com/syl20bnr/spacemacs/issues/2093#issuecomment-118462097)

**Comment by robbyoconnor** [comment]
Fixed in #2233 so I'm closing this.
