### ISSUE TITLE
yank to system clipboard

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#2222]
i use suggestion in #1504 , "*y for cut text into system clipboard, but it run in wrong behaviour. And pop up an message "x-set-selection: Symbol's funtion definition is void: x-own-selection-internal " 
anyone have ideas?

**Comment by dzhwinter** [comment]
emacs 24.5
ubuntu 14.04
spacemacs 1.01.3
nothing else in message buffer. 
thanks advance

**Comment by dzhwinter** [comment]
sorry but, is there any progress in yank context into X-clipboard?
i update my spacemacs to 0.103 bump v2. 
I use still just pop a message "x-set-selection: Symbol's funtion definition is void: x-own-selection-internal "  and yank nothing in my clipboard.
i found what is going wrong.
i use emacs 24.5-nox in terminal (ssh to server ), of course emacs has no knowledge about X11 system clipboard.
As a result, unless use third tool like 'xclip' here. And i found someone has done that. 
http://www.emacswiki.org/emacs/download/xclip.el.

**Comment by StreakyCobra** [comment]
@dzhwinter Are you more lucky with the last spacemacs release about this?

Normally `y` and `p` use directly the system clipboard, IIRC, except if you are using emacs in terminal.

**Comment by dzhwinter** [comment]
i have solved that. 
I am using emacs in terminal.  In fact, I my daily work, i always connect to server with ssh and I have no choice but emacs-nox (with GUI always failed and freeze window because of the unstable connection). 
I use xsel with this config for clip and paste content in terminal. For who search here.
 
```
(defun configlayer/init-xclip ()
  (use-package xclip
    :defer t
    :init
    (defun copy-to-clipboard ()
      "Copies selection to x-clipboard."
      (interactive)
      (if (display-graphic-p)
          (progn
            (message "Yanked region to x-clipboard!")
            (call-interactively 'clipboard-kill-ring-save)
            )
        (if (region-active-p)
            (progn
              (shell-command-on-region (region-beginning) (region-end) "xsel -i -b")
              (message "Yanked region to clipboard!")
              (deactivate-mark))
          (message "No region active; can't yank to clipboard!")))
      )

    (defun paste-from-clipboard ()
      "Pastes from x-clipboard."
      (interactive)
      (if (display-graphic-p)
          (progn
            (clipboard-yank)
            (message "graphics active")
            )
        (insert (shell-command-to-string "xsel -o -b"))
        )
      )

 ```

**Comment by robbyoconnor** [comment]
It works fine for me without this change...

**Comment by nightscape** [comment]
@dzhwinter sorry for that silly question, Emacs noob here.
Where does one put that code snippet? At the end of `~/.spacemacs`?
And does one have to activate it manually somehow? To which keys is it bound then?

**Comment by nightscape** [comment]
Ok, I think I can answer this myself now:
I put the above code snippet in `.spacemacs` in the section `(defun dotspacemacs/user-config () ...)` and added the following two lines from https://github.com/syl20bnr/spacemacs/issues/2347
```
  (evil-leader/set-key "o y" 'copy-to-clipboard)
  (evil-leader/set-key "o p" 'paste-from-clipboard)
```
Now when I press `SPC` there is a new `o → +prefix` entry in the menu which contains `p → paste-from-clipboard y → copy-to-clipboard `.
So `SPC o y` copies the selection to the system clipboard and `SPC o p` pastes the system clipboards contents at the current cursor position.
Nice!!

**Comment by qiuwei** [comment]
@nightscape 's code snippets great for me.

I only need to use pbcopy/pbpaste instead of xsel to make it work on a Mac.

Thanks.

**Comment by ninrod** [comment]
@qiuwei have you managed to integrate pbcopy within the above snippet? thanks in advance.

**Comment by qiuwei** [comment]
@ninrod yes, pbcopy and pbpaste work great on my mac.

**Comment by ninrod** [comment]
nice. just for posterity's sake, if you want to make it work for mac, it is easy enough: (you could even query the system type and make it work anywhere).

```lisp
(defun dotspacemacs/user-config ()

    ; ...

    (defun copy-to-clipboard ()
      "Copies selection to x-clipboard."
      (interactive)
      (if (display-graphic-p)
          (progn
            (message "Yanked region to x-clipboard!")
            (call-interactively 'clipboard-kill-ring-save)
            )
        (if (region-active-p)
            (progn
              (shell-command-on-region (region-beginning) (region-end) "pbpaste")
              (message "Yanked region to clipboard!")
              (deactivate-mark))
          (message "No region active; can't yank to clipboard!")))
      )

    (defun paste-from-clipboard ()
      "Pastes from x-clipboard."
      (interactive)
      (if (display-graphic-p)
          (progn
            (clipboard-yank)
            (message "graphics active")
            )
        (insert (shell-command-to-string "pbpaste"))
        )
      )
  (evil-leader/set-key "o y" 'copy-to-clipboard)
  (evil-leader/set-key "o p" 'paste-from-clipboard)
)
```

**Comment by andreicristianpetcu** [comment]
Can this be added to Spacemacs? I think this should be a builtin feature.

**Comment by aniketd** [comment]
This feature is a basic need for sure.

**Comment by TheBB** [comment]
Just make a PR!

**Comment by xged** [comment]
@ninrod not always works well.

**Comment by jameskolce** [comment]
The snippet @ninrod posted has a little error in the `copy-to-clipboard` function, it calls `pbpaste` instead of `pbcopy`. The fixed version would be:

```elisp
(defun dotspacemacs/user-config ()

    ; ...

    (defun copy-to-clipboard ()
      "Copies selection to x-clipboard."
      (interactive)
      (if (display-graphic-p)
          (progn
            (message "Yanked region to x-clipboard!")
            (call-interactively 'clipboard-kill-ring-save)
            )
        (if (region-active-p)
            (progn
              (shell-command-on-region (region-beginning) (region-end) "pbcopy")
              (message "Yanked region to clipboard!")
              (deactivate-mark))
          (message "No region active; can't yank to clipboard!")))
      )

    (defun paste-from-clipboard ()
      "Pastes from x-clipboard."
      (interactive)
      (if (display-graphic-p)
          (progn
            (clipboard-yank)
            (message "graphics active")
            )
        (insert (shell-command-to-string "pbpaste"))
        )
      )
  (evil-leader/set-key "o y" 'copy-to-clipboard)
  (evil-leader/set-key "o p" 'paste-from-clipboard)
)
```

**Comment by robbyoconnor** [comment]
it already yanks to my system clipboard without this...

**Comment by jameskolce** [comment]
That's weird, I don't know how that can be possible if it is calling `pbpaste` in both commands:

**I changed this:**

```elisp
(shell-command-on-region (region-beginning) (region-end) "pbpaste")
```

**to this:**

```elisp
(shell-command-on-region (region-beginning) (region-end) "pbcopy")
```

Just in case someone else has the same problem. I needed this for me because I was unable to copy/paste and the solution posted before wasn't working.

**Comment by robbyoconnor** [comment]
I didn't have to do anything... What OS?

**Comment by jameskolce** [comment]
MacOS using Terminal.

---

Here is the story:

Previously, using plain Emacs I just used <kbd>cmd+c</kbd> to copy from Emacs to other applications and <kbd>cmd+v</kbd> to paste from other applications, that was possible because of Terminal and not Emacs itself. But those weren't working with Spacemacs. <kbd>c-y</kbd> and <kbd>m-y</kbd> work only within Spacemacs but not with other applications.

I think it would work as before by disabling `xterm-mouse-mode` but I kind of like that feature now. So I had to find a way to copy/paste to/from other applications, and this is the thing that worked after changing the command mentioned in my previous comment. I also changed the keybindings to:

```elisp
(global-set-key (kbd "M-w") 'copy-to-clipboard)
(global-set-key (kbd "C-y") 'paste-from-clipboard)
```

Since I just started to use Emacs I don't know if that will have side-effects, but is working well so far.

---

But maybe all this is because I'm doing something wrong, how do you do copy and paste usually?

**Comment by robbyoconnor** [comment]
That'd be why it works for me -- I use the gui

**Comment by andreicristianpetcu** [comment]
@jameskolce M-w and C-y seem totally non-intuitive. Y is associated with yank (copy) not paste and you have M- and C- for copy and paste why not C-M-c and C-M-p? Control+alt+c/p from copy/paste?

**Comment by jameskolce** [comment]
@andreicristianpetcu I got those from this table from [EmacsWiki](https://www.emacswiki.org/emacs/CopyAndPaste):

![image](https://cloud.githubusercontent.com/assets/2559808/21508679/454f3aa0-cc40-11e6-97e1-eeecab91df34.png)

Also, those are the commands I have been using in Emacs before installing Spacemacs.

I just checked the Yank term and Wikipedia says:

> Yank, the name for the **copy command in vi** and the **paste command in Emacs**, two commonly used UNIX/Linux text editors

So perhaps you are associating it with Vi (or Vi mode) instead of Emacs?

<kbd>C-M-c</kbd> and <kbd>C-M-P</kbd> also make sense to me though, so I might consider changing at some point, although I also like that the default key combinations of Emacs work with the clipboard. 

But as I said, I'm just starting to use Emacs and I still have a lot to learn, so I appreciate the suggestions.

**Comment by andreicristianpetcu** [comment]
Sorry for the misinformation. I never used vanilla Emacs and I started using Spacemacs from the start. I used Vim and Neovim before Spacemacs and that's where the confusion over yank comes from :) I see your point and your proposal sounds fine.

**Comment by jameskolce** [comment]
Alright thanks, and no worries!

**Comment by cweill** [comment]
If anyone is having problems copying to the X clipboard when ssh'ing with X-forwarding, i.e. `ssh -Y hostname`, I had to change @nightscape's solution from `xsel -i -b` to `xsel -ib` and similarly `xsel -o -b` to `xsel -ob`.

In my case I was ssh'ing from OSX to Ubuntu when I encountered this error. The following code now allows you to copy and paste seamlessly over `ssh -Y` connections to remote hosts:

```lisp
(defun dotspacemacs/user-config ()

    ; ...

    (defun copy-to-clipboard ()
      "Copies selection to x-clipboard."
      (interactive)
      (if (display-graphic-p)
          (progn
            (message "Yanked region to x-clipboard!")
            (call-interactively 'clipboard-kill-ring-save)
            )
        (if (region-active-p)
            (progn
              (shell-command-on-region (region-beginning) (region-end) "xsel -ib")
              (message "Yanked region to clipboard!")
              (deactivate-mark))
          (message "No region active; can't yank to clipboard!")))
      )

    (defun paste-from-clipboard ()
      "Pastes from x-clipboard."
      (interactive)
      (if (display-graphic-p)
          (progn
            (clipboard-yank)
            (message "graphics active")
            )
        (insert (shell-command-to-string "xsel -ob"))
        )
      )
  (evil-leader/set-key "o y" 'copy-to-clipboard)
  (evil-leader/set-key "o p" 'paste-from-clipboard)
)
```

**Comment by quangv** [comment]
fyi I could not get above to work (using Xshell on Windows 10, connecting to Ubuntu)

But this worked for me.

`(xterm-mouse-mode -1)`

https://stackoverflow.com/questions/37631440/spacemacs-using-the-mouse-to-copy-paste

**Comment by cweill** [comment]
Try the `xclipboard` layer in the [develop branch](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/xclipboard).

**Comment by drewLo** [comment]
I wasn't able to 'copy' (in emacs lingo: kill-ring-save) from the terminal (opened with M-') and paste into other programs (or buffers). However I was able to accomplish it by marking the desired text and use middle-mouse button. It pastes (ie. yanks) the marked text to the terminal prompt, but it also makes it paste-able both in and outside of emacs. hopefully this helps someone who was looking for a quick and dirty(?) way to copy/paste to-and-from the spacemacs terminal.

**Comment by bigfish** [comment]
in Ubuntu, 
`sudo apt install xsel`

in .spacemacs, I added 'xclip' package to list of additional packages, &
`(xclip-mode 1)`
in dotspacemacs/user-config fn. 

Now I can paste into emacs buffer from system clipboard with 'p' in evil mode (normal).  
And anything I yank ('y') I can paste into other apps.

**Comment by biocyberman** [comment]
Finally this itching problem is solved. This is working code with OS check for Linux and MacOS. I don't use Windows so I don't know how it works

```elsip
(cond
 ;; OS X
 ((string-equal system-type "darwin") ; Mac OS X
  (progn
    (setq save-to-clipboard-cmd "pbcopy")
    (setq paste-from-clipboard-cmd "pbpaste")
    )
  )
 ;; Linux
 ((string-equal system-type "gnu/linux") ; linux
  (progn
    (setq save-to-clipboard-cmd "xsel -i -b")
    (setq paste-from-clipboard-cmd "xsel -o -b")
    )
  )
 )

(defun copy-to-clipboard ()
  "Copies selection to x-clipboard."
  (interactive)
  (if (display-graphic-p)
      (progn
        (message "Yanked region to x-clipboard!")
        (call-interactively 'clipboard-kill-ring-save)
        )
    (if (region-active-p)
        (progn
          (shell-command-on-region (region-beginning) (region-end) save-to-clipboard-cmd)
          (message "Yanked region to clipboard!")
          (deactivate-mark))
      (message "No region active; can't yank to clipboard!")))
  )

(defun paste-from-clipboard ()
  "Pastes from x-clipboard."
  (interactive)
  (if (display-graphic-p)
      (progn
        (clipboard-yank)
        (message "graphics active")
        )
    (insert (shell-command-to-string paste-from-clipboard-cmd))
    )
  )
(evil-leader/set-key "o y" 'copy-to-clipboard)
(evil-leader/set-key "o p" 'paste-from-clipboard)
```

**Comment by yanowitz** [comment]
I've done this integration in a different way, dropping it here for posterity. I want any cutting and yanking to work with pbcopy/pbpaste (on my mac). I'm new to Spacemacs, but I've used this with emacs (in tty mode) on my mac for years. YMMV. I prefer this to be seamless without my thinking about it.

Obviously, you can just wire up copy or paste, not both.

```
  (defun dotspacemacs/user-config ()
;...
    (if (eq system-type 'darwin)
        (progn
          (defun mac-copy ()
            (shell-command-to-string "pbpaste"))

          (defun mac-paste (text &optional push)
            (let ((process-connection-type nil))
              (let ((proc (start-process "pbcopy" "*Messages*" "pbcopy")))
                (process-send-string proc text)
                (process-send-eof proc))))

          (setq interprogram-cut-function 'mac-paste)
          (setq interprogram-paste-function 'mac-copy)
          ))
  )
```
