### ISSUE TITLE
vi bindings missing in magit-log buffer

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#2224]
1. open magit log with <kbd>SPC g l</kbd>
2. try moving around with <kbd>j</kbd> / <kbd>k</kbd>

Just getting `j/k is undefined` instead.

**Comment by syl20bnr** [comment]
I cannot reproduce it, it may have been fixed with last commits. Can you try on last release (0.103.2) or develop branch ?

**Comment by tko** [comment]
Caught up with latest develop and elpa.

The keys seem to work only after running magit-status first. But if the first magit thing I try is the log the keys are undefined.

**Comment by justbur** [comment]
shouldn't be a problem after #3578
