### ISSUE TITLE
Noinvert comment on spc-c-[pl] invert comment on spc-c-[PL]?

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#2225]
I do not think it makes any sense to have to toggle a switch to decide whether to invert comments or not.

You have some text selected that you want to comment or uncomment. Sometimes you want to invert the comments, sometimes not. It would have made sense to have a switch for this if people always did one thing or another, but since this varies each time, it would probably be better to have dedicated buttons for each case. I propose `SPC c p/l` for non-inversion and `SPC c P/L` for inversion.

Yay or nay?

I tried implementing this myself because it seems simple, but just calling `evil-commenter` from another function lead to strange errors.

**Comment by syl20bnr** [comment]
Seems like a good convention to me.
You may have to use `call-interactively` for `evil-commenter` to behave correctly, also check `evil-nerd-commenter` which is the package spacemacs uses by default for commenting.

**Comment by endrebak** [comment]
Will try agian when I finish some stuff at work - need to get better at `elisp`. Thanks for the pointers.

**Comment by endrebak** [comment]
Now I have doubled the number of functions, i.e. `comment-or-uncomment-lines` becomes

```
(defun comment-or-uncomment-line-by-line-invert (&optional NUM)
  (interactive "p")
  (let ((evilnc-invert-comment-line-by-line t))
    (evilnc-comment-or-uncomment-lines NUM)))

(defun comment-or-uncomment-line-by-line (&optional NUM)
  (interactive "p")
  (let ((evilnc-invert-comment-line-by-line nil))
    (evilnc-comment-or-uncomment-lines NUM)))
```

Is it okay if I create two of these for every commenting function? If so, where do I put them - `spacemacs/funcs.el`?

(I guess this is some amount of code duplication, but if you create a `comment-or-uncomment-line` with an `invert` as an argument to handle both cases, the function won't play well with the universal argument nor interactive (I guess).

**Comment by endrebak** [comment]
Here is what I want to do:

For each commenting function, create two functions, one for inversion, one for non-inversion, like below:

```elisp
(defun comment-or-uncomment-lines-inverse (&optional NUM)
  (interactive "p")
  (let ((evilnc-invert-comment-line-by-line t))
    (evilnc-comment-or-uncomment-lines NUM)))

(defun comment-or-uncomment-lines (&optional NUM)
  (interactive "p")
  (let ((evilnc-invert-comment-line-by-line nil))
    (evilnc-comment-or-uncomment-lines NUM)))
```

(This is some amount of code duplication, but if you create a `comment-or-uncomment-line-by-line` with an `invert` bool argument to handle both cases, I do not see how to set the keybindings since `evil-leader/set-key` takes a function name, but no arguments.)

Anyways, if it is okay that I create two functions for each commenting function like above, I have three questions:

1) Where do I put the functions?
2) Should I update the `:commands` in `(defun spacemacs/init-evil-nerd-commenter ()`? 
3) Should I set the keymappings within the `(defun spacemacs/init-evil-nerd-commenter ()`

Example:

```elisp
(defun spacemacs/init-evil-nerd-commenter ()
  (use-package evil-nerd-commenter
    :commands (evilnc-comment-operator
                         comment-or-uncomment-lines
                         comment-or-uncomment-lines-invert
                         ...)
    :init
    (progn
      (evil-leader/set-key
        ";"  'evilnc-comment-operator
        "cl" 'comment-or-uncomment-lines
        "cL" 'comment-or-uncomment-lines-invert
       ...))))
```

**Comment by endrebak** [comment]
https://github.com/syl20bnr/spacemacs/pull/2302
