### ISSUE TITLE
How to rebind M-m?

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#2229]
Right now it does the same as `space`. I'd like to use it for `helm-all-mark-rings` like so:

```
(define-key my-keys-minor-mode-map (kbd "M-m") 'helm-all-mark-rings)   
```

No rebinding seems to work; I even tried remapping `M-m` in a minor mode, which should make it near impossible for other packages to interfere.

**Comment by syl20bnr** [comment]
I guess you have to set `dotspacemacs-emacs-leader-key` to nil in your dotfile.

**Comment by endrebak** [comment]
I guess I should rather find keycombo then :)
