### ISSUE TITLE
setting east-asian-ambiguous

### ISSUE THREAD

**Issue by hyuna917** [syl20bnr/spacemacs#2231]
i want to set the cjk font going to be double width. 
so, i try to set gist “east-asian-ambiguous” : https://gist.github.com/9580569.git 
however, it doesn’t work well. 
there is someone to know about it?
it’s really helpful to me if someone make a “contrib”.

**Comment by syl20bnr** [comment]
Who may needs it and what are the advantages of doing this ?
Do you think you could make a PR with this ?  What would be the name of the layer ?

**Comment by StreakyCobra** [comment]
@hyuna917 As there was no answer from you last 4 months and your link is a 404 now, I'm closing this issue. If you want to answer the questions and give an existing link, I'll reopen it with pleasure :relaxed:
