### ISSUE TITLE
Flycheck unnecessary line marks

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#2234]
*Flycheck* line marks (dots at the left side) are unnecessary and distracting at least to my eyes. Lower underscores are enough IMO. Couple that with difficulty to configure *Flycheck* (casual) warnings and absence of #2134 you usually get an ugly looking buffer.

**Comment by syl20bnr** [comment]
I propose to improve the flycheck fringe indicator support in spacemacs with a layer variable `syntax-checking-fringe-indicators` taking 3 possible values `nil`, `default` and `dot`.

**Comment by endrebak** [comment]
I was thinking of looking into this for another reason: in `bzg-big-fringe-mode`, the fringe is widened so the flycheck marks cover ~25% of the screen.

Anyways, this does not look too hard to achieve; all the neccessary changes are just in `spacemacs/contrib/syntax-checking/packages.el`, I guess.

Does `dot` mean that only the dot should show? I imagine just setting the values `fringe-bitmap` and `fringe-face`  to `nil` should remove the flycheck fringe completely.

**Comment by endrebak** [comment]
After playing around it seems as trivial as I outflined above both to achieve `dot` and `nil`. I'll do it if no-one else is working on it. Can't do it until after the weekend though.

**Comment by lunaryorn** [comment]
@xged Set `flycheck-indication-mode` to `nil` to prevent Flycheck from creating fringe indicators.  See [Reporting results](http://www.flycheck.org/manual/latest/Reporting-results.html#Reporting-results) in the Flycheck manual for more information.

**Comment by TheBB** [comment]
That seems to close this issue. :-)

**Comment by lunaryorn** [comment]
@endrebak I mean no offense, but _please_ do _not_ guess.  Please read the manual:  Flycheck already [provides an option](https://github.com/syl20bnr/spacemacs/issues/2234#issuecomment-151142987) for this purpose.
