### ISSUE TITLE
Chinese layer font not found

### ISSUE THREAD

**Issue by autosquid** [syl20bnr/spacemacs#2236]
`(spacemacs//set-monospaced-font   "Source Code Pro" "Hiragino Sans GB" 14 16)`

This one in 'config.el' stops me from installing since `source code pro` is not installed.
 I think the above line should be remove from 'configl.el' and leave options to user even on mac.  (just like all other platforms). 

And the youdao dict thing should be separated from this layer for KISS. And since youdao dict. is a commercial software, I don't think it is proper to include by default.

**Comment by andyque** [comment]
@autosquid  Yes, I think we should remove `(spacemacs//set-monospaced-font "Source Code Pro" "Hiragino Sans GB" 14 16)` in case someone haven't installed "Source Code Pro".

But Youdao dict is free to use, why not keep it?

**Comment by andyque** [comment]
@autosquid  Fixed at here https://github.com/syl20bnr/spacemacs/pull/2237

**Comment by autosquid** [comment]
thanks for your fix.
As to youdao, it is not essential, and I suggest a separate new layer. It is good, but you just can not force others to use it. Like `Dash`, it is useful for programmer, but just not essential. And like `Flyspell`, there is an option not to enable it.

**Comment by andyque** [comment]
@autosquid  Make youdao a separate layer might not be good. It is a translation service only useful for people who speak Chinese. I will try to add a option to toggle it. 
Thanks.

**Comment by andyque** [comment]
@autosquid  I have already add Youdao Dict an optional , please check.

**Comment by autosquid** [comment]
@andyque  thanks for your work. It looks like you are planning to put everything related with Chinese into  a single layer. Though I think it is a better idea to have small "atomic" layers under a same directory, but maybe it could be left just what it is now and wait for possible upcoming changes.

**Comment by andyque** [comment]
make all packages related to Chinese together is what a layer means in Spacemacs.

**Comment by syl20bnr** [comment]
When we create a layer we have to wonder what's the goal of the layer, the Chinese layer goal is to provide support for Chinese related packages in Spacemacs. It answers the question "What is the Chinese support in Spacemacs ?". This goal is a very strong one which absorbs any package related to Chinese so I agree with @zilongshanren on this.

**Comment by StreakyCobra** [comment]
The original issue has been fixed long time ago, the request concerning youdao has been addressed, and the discussion is finished. I'm closing this issue then, but feel free to open a new one in case of troubles :-)
