### ISSUE TITLE
magit does not works

### ISSUE THREAD

**Issue by zekzekus** [syl20bnr/spacemacs#2238]
at some point my magit stopped working. when i execute `magit-status` returning message is `wring type of argument: arrayp, nil`

i completely wiped out my spacemacs installation and the result is same. 

NOTE: when i execute `magit-log-all` on a version controlled file it says that not in a git repository. 

Second NOTE: i outputs that arrayp error while installing the magit package within git layer

**Comment by robbyoconnor** [comment]
Is this against `master` or `develop`? Try `develop` if it's `master`

**Comment by zekzekus** [comment]
i tried with develop branch. summary: i checked out to develop branch and run spacemacs then update packages and trid again. 

at first there was no arrayp error but magit was asking to init a new repository via helm-magit-status . then i restarted emacs and the old arrayp error returned. 

now i made a fresh install with develop branch and... again arrayp error.

now i am checking my git version from inside emacs: 1.8.1.3 aha! pretty old. probably mac os x's system git. let's add /usr/local/bin/ to exec path then... no. i could not make this work. 

and i used the variable called magit-git-executable to set my homebrewed git executable for magit. it worked like a charm. 

still <Space>! -> git --version shows old git but at least magit is working. any way to show emacs (emacs-mac on mac os) the latest and greatest git version?

NOTE: i am sorry for the monologue :)

**Comment by alex-glv** [comment]
Brew installs executables to /usr/local/bin
These are the steps I would take to troubleshoot.
Make sure you do ```brew upgrade``` ,  or ```brew remove git && brew install git```
Your path should be ```/usr/local/bin:$PATH```

Then, if you still have issues, remove custom configuration from spacemacs and run it only with git layer.

**Comment by robbyoconnor** [comment]
git *AND *version-control layer

**Comment by robbyoconnor** [comment]
`git` and `version-control`

**Comment by StreakyCobra** [comment]
@zekzekus Is your problem solved, or do you need more help on this?
