### ISSUE TITLE
ruby-on-rails layer doesn't include haml-mode

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#2245]
Probably because it's got ruby-packages got redefined.
https://github.com/syl20bnr/spacemacs/blob/develop/contrib/!lang/ruby/packages.el#L13
https://github.com/syl20bnr/spacemacs/blob/develop/contrib/!frameworks/ruby-on-rails/packages.el#L13

**Comment by TheBB** [comment]
That's a bit of a blunder. I fixed this in #2248.

**Comment by robbyoconnor** [comment]
It's in the html layer
