### ISSUE TITLE
How do I disable the yasnippets that come with spacemacs?

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#2246]
I'd like to just use my private snippets, but can't find out how. Thanks.

**Comment by endrebak** [comment]
I know I can just move the folder, but this will create a headache when I want to pull spacemacs again, I'm sure git will complain.

**Comment by endrebak** [comment]
https://github.com/syl20bnr/spacemacs/issues/1923

**Comment by endrebak** [comment]
TL;DR

1. Delete obsolete folder `~/.emacs.d/spacemacs/extension/yasnippet-snippets/`
2. Use `(setq yas-snippet-dirs '("~/.emacs.d/private/snippets"))`

**Comment by emad-elsaid** [comment]
Instead of deleting the directory in point 1 I added `yasnippet-snippets` to the excluded packages list: 
```emacs-lisp
   dotspacemacs-excluded-packages '(yasnippet-snippets)
```
