### ISSUE TITLE
latex layer keybinding conventions for errors

### ISSUE THREAD

**Issue by edwintorok** [syl20bnr/spacemacs#2250]
The latex layer still requires use of Emacs-mode specific <kbd>C-c  `</kbd> and <kbd>C-c C-l</kbd> to see the output of LaTeX compilation (triggered by <kbd>SPC m b</kbd>).
It should follow the spacemacs conventions and provide either Vim keybindings, or <kbd>SPC</kbd> keybindings (would <kbd>SPC e n</kbd> be appropriate here, even if its not using flycheck?).

**Comment by geo7** [comment]
@TheBB tags - LaTeX Discussion / Proposal

**Comment by benquebec** [comment]
I haven't thought about using `SPC e n` but I did modify my latex layer so that the output is at `SPC m o`. I chose this keybinding because  `m` is related to the major mode (it keeps everything TeX neatly together) and `o`for output...

**Comment by moesasji** [comment]
Using `SPC e n` is not a good idea as that is reserved for flycheck, which I do use. The suggestion from @benquebec  to use `SPC m o` would work well with the current keybindings of the major mode. 

btw) An alternative could be to use `SPC c w` short for "compile window" or alternative `SPC c o` for "compile output" (develop has `SPC c q` to close this window). However this feel less logical for LaTex mode as it doesn't use `SPC c C` to compile it. I'm not sure why that is though...

**Comment by benquebec** [comment]
Tried `SPC c C` on a .tex file. Could this binding be more appropriate for those times where a .tex file is compiled using a makefile?
