### ISSUE TITLE
ESC breaks magit status mode vim bindings

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#2251]
In vim style
1. open magit status <kbd>SPC g s</kbd>
2. press <kbd>ESC</kbd>

Now <kbd>j</kbd> still moves down, but <kbd>k</kbd> is discarding things. (And the other window got closed as well, making magit status essentially maximised.)

Hitting <kbd>ESC</kbd> should be a safe escape hatch to normal-ish mode.

**Comment by cpaulik** [comment]
On which release or branch are you?

It's possible that this was fixed already. See https://github.com/syl20bnr/spacemacs/issues/2183

**Comment by tko** [comment]
Oh, sorry. Had some custom keyboard-escape-quit+evil-normal-state binding for escape. I'm sure it made sense at the time.

Works fine with spacemacs bindings.
