### ISSUE TITLE
Edebug integration in elisp layer

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#2254]
It would be nice to have some commands for edebug funcitonality in the `SPC m d` namespace, e.g. for instrumenting functions.

**Comment by travisbhartwell** [comment]
+1

**Comment by Miciah** [comment]
Looks like https://github.com/syl20bnr/spacemacs/commit/6e713ed89f5433842ecdba1bfc1bc3422d51ce55 added the requested functionality.  Can this issue be either closed or labeled as "Fixed in develop"?
