### ISSUE TITLE
Discussion: How important is flycheck syntax checking for jade-mode

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2268]
This is about [flycheck](https://github.com/flycheck/flycheck)  syntax checking for [jade-mode](https://github.com/brianc/jade-mode), which currently doesn't seem to exist, and whether or not it needs to.

I have everything *except* flycheck integration implemented in #2249, but I'd like flycheck integration to make it whole...but I want to know how important it is to have support for editing [jade](http://jade-lang.com) files. I just wanted to open a dialogue with the community. This integration arose out of a need. There is full support in vim, but not in emacs (which is quite alarming to me, to be blunt).

**Comment by robbyoconnor** [comment]
Going to implement it but flycheck has to accept my PR so it's blocked until then

**Comment by robbyoconnor** [comment]
This issue is completely pointless as jade support exists for flycheck.

**Comment by vimniky** [comment]
I can't get jade indentation right

**Comment by TheBB** [comment]
@vimniky Open a new issue, then. This one is closed and done with.

**Comment by robbyoconnor** [comment]
This isn't related to flycheck at all, but with jade-mode. The jade flycheck checker works.

**Comment by robbyoconnor** [comment]
@vimniky -- This isn't related to flycheck at all, but with [jade-mode](https://github.com/brianc/jade-mode). The jade flycheck checker works. If you are going to file a bug report, at least make it somewhat related to the actual problem.

**Comment by robbyoconnor** [comment]
@vimniky -- This isn't related to flycheck at all, but with [jade-mode](https://github.com/brianc/jade-mode) -- if it is an actual problem. The jade flycheck checker works. If you are going to file a bug report, at least make it somewhat related to the actual problem.
