### ISSUE TITLE
Disable modeline state colors

### ISSUE THREAD

**Issue by mkaito** [syl20bnr/spacemacs#2273]
I'm not a big fan of colors. Yes, I'm weird like that. My entire system is themed to base16-grayscale, except for the spacemacs modeline. Can I disable state indication via modeline colorization?

**Comment by syl20bnr** [comment]
You can `setq` this variable in `dotspacemacs/init`:

```
(defvar spacemacs-evil-cursor-colors '((normal . "DarkGoldenrod2")
                                             (insert . "chartreuse3")
                                             (emacs  . "SkyBlue2")
                                             (evilified . "LightGoldenrod3")
                                             (visual . "gray")
                                             (motion . "plum3")
                                             (lisp   . "HotPink1")
                                             (iedit  . "firebrick1")
                                             (iedit-insert  . "firebrick1"))
        "Colors assigned to evil states.")
```

**Comment by mkaito** [comment]
That worked like a charm, thanks!

Any thoughts on something like `(setq spacemacs-colorize-for-state nil)`?

**Comment by StreakyCobra** [comment]
The issue has been addressed, and as nobody commented here last 4 months, there is probably not a lot of interest for the proposed functionality. I'm closing this issue then, but feel free to open a new one in case of troubles. :relaxed:

**Comment by TheBB** [comment]
Actually, in develop you can do

```elisp
(setq spaceline-highlight-face-func 'spaceline-highlight-face-default)
```

Since Spacemacs sets this variable you have to do it in `dotspacemacs/user-config`.

**Comment by mkaito** [comment]
@TheBB That doesn't seem to work for me.

Actually, can the faces in the modeline be addressed in themes? I'd like to try and theme it in base16.

**Comment by UndeadLeech** [comment]
So I've found this and couldn't really get it working myself.
If anyone stumbles upon this and has the same issue try this out in the `user-init` section:
```
(setq spacemacs-evil-cursors '(("normal" "#ff00ff" box)
                                   ("insert" "chartreuse3" (bar . 2))
                                   ("emacs" "SkyBlue2" box)
                                   ("hybrid" "SkyBlue2" (bar . 2))
                                   ("replace" "chocolate" (hbar . 2))
                                   ("evilified" "LightGoldenrod3" box)
                                   ("visual" "gray" (hbar . 2))
                                   ("motion" "plum3" box)
                                   ("lisp" "HotPink1" box)
                                   ("iedit" "firebrick1" box)
                                   ("iedit-insert" "firebrick1" (bar . 2))))
```

**Comment by keatondunsford** [comment]
Yeah, I can't stand the orange insert color and would love to be able to change it. Seems like since the dotspacemacs has changed over the last year or so, this command should be different. How exactly can I change these colors?

Thanks!
