### ISSUE TITLE
C-t after C-] doesn't pop

### ISSUE THREAD

**Issue by agriffis** [syl20bnr/spacemacs#2274]
I am probably missing something here, but in Vim one can follow a tag with `C-]` and then pop to previous position and buffer with `C-t`.  In Spacemacs that doesn't seem to work: the `C-t` just says "No marker available."

**Comment by dsdshcym** [comment]
@agriffis `C-t` works well here. Can you confirm this issue again?

**Comment by agriffis** [comment]
At this point `C-t` doesn't cause the error I reported. It doesn't work quite right either--at least not how vim handles it--but I've just gotten used to `C-o` in its place, so it's fine.
