### ISSUE TITLE
It gets stuck installing packages using gnutls-cli (using Windows 8)

### ISSUE THREAD

**Issue by rafaelgp** [syl20bnr/spacemacs#2280]
Hello,

I'm using Emacs 24.5.1 in Windows 8

Yesterday I upgraded to Spacemacs 0.103.2 but soon something started going wrong.

First Spacemacs failed to install the extensions 'spray' and 'revive'.
I thought it would be easier to install everything from scratch, so I cloned the whole repository from scratch. Unfortunately Spacemacs wasn't able to start up. It got stuck installing all the necessary packages, showing the following message:

Opening TLS connection with 'gnutls-cli --insecure -p 443 elpa.gnu.org' ... done

I tried Emacs 25.0.50.1 and this time it installed 94 packages successfully. But after re-start, it got stuck installing some packages again! Here is a screenshot:

![Spacemacs error message](http://clients.tourvista.co.uk/vt/zip/tmp/emacs-stuck.jpg)

Any ideas what's happening?

Many thanks.

**Comment by ncihnegn** [comment]
Same problem here

**Comment by ncihnegn** [comment]
After I remove gnutls, it still reports errors for elpa, but continues to work fine with other repos.

**Comment by ncihnegn** [comment]
One workaround is to redefine package-archives with HTTP instead of HTTPS for elpa.

**Comment by rafaelgp** [comment]
@ncihnegn Are you using msys2?
I solved the problem after installing gnutls

```
pacman -S gnutls
```
I had some errors when I started Spacemacs, so I deleted everything in the 'melpa' directory and let spacemacs reinstall everything again.

**Comment by ncihnegn** [comment]
Interesing. I tried to install i686-gnutls but it didn't help.

**Comment by ncihnegn** [comment]
Alright. It works now after I change PATH=/mingw64/bin:$PATH to PATH=$PATH:/mingw64/bin. It will be nice if we figure out why.

**Comment by justbur** [comment]
It means you have another gnutls-cli program in your path somewhere I
believe

**Comment by ncihnegn** [comment]
In that case, msys/gnutls works for me but mingw64/gnutls didn't.

**Comment by StreakyCobra** [comment]
Anyone still experiencing this issue?

**Comment by casimir** [comment]
Tried the different solution but still experiencing it @StreakyCobra.

**Comment by StreakyCobra** [comment]
What I don't really get is why it needs TLS as all repositories are using `http` and not `https` (https://github.com/syl20bnr/spacemacs/blob/master/core/core-configuration-layer.el#L27-L29). Do you have the last spacemacs version (0.104.5)? If yes, can you give the output of `SPC h d s`?

**Comment by casimir** [comment]
Didn't notice it was the Spacemacs repo, I end up here by searching bugs with gnutls from msys2. I use the emacs version from msys2 too. It looks like this is more a _mingw64/gnutls_ bug. For me, when refreshing/installing package `gnutls-cli` goes crazy and I have to kill it.

Anyway if you don't use the https version you shouldn't have this problem anymore. Sorry for the noise.

**Comment by StreakyCobra** [comment]
No problem :-) @rafaelgp @ncihnegn Do you still have this problem with last spacemacs release?

**Comment by rafaelgp** [comment]
I moved to work with Emacs inside a Virtual Box, so sorry I don't know if this issue is still happening.

**Comment by StreakyCobra** [comment]
Ok, thanks for your comment :-) @ncihnegn on your side?

**Comment by ncihnegn** [comment]
No issues here. I don't even have gnutls-cli at all.

**Comment by StreakyCobra** [comment]
Ok thanks for your answer.

As nobody has currently this problem, we can not help any further. I'm then closing this issue. Anyway, feel free to open a new one in case of troubles. Please include a link to this one if you thinks it's related :relaxed:

**Comment by mihaelS** [comment]
Same error.

Windows 10
emacs 26.0.91 x86_64
spacemacs 0.200.13


* Get this error (without gnutls):
 'gnutls-cli --insecure -p 443 elpa.gnu.org' ... done

 * With installed gnutls (added libgnutls-30.dll to the /bin/ folder), get this message:
![image](https://user-images.githubusercontent.com/11715774/35670891-db4e0f22-074a-11e8-8ba6-86929edf6453.png)

   * and same error, when trying to translate with google-ui
![image](https://user-images.githubusercontent.com/11715774/35671044-4471082e-074b-11e8-8247-fc05758b144e.png)

   * And then emacs hangs up and I have to kill the emacs process.

Seems that there is some kind of problem with the gnutls on Windows.

Can anyone help to fix it?

**Comment by StreakyCobra** [comment]
@mihaelS I'm not a spacemacs contributor anymore, sorry.

**Comment by mihaelS** [comment]
@syl20bnr, reopen this issue, please.

**Comment by ygol** [comment]
having the same problem under windows 10.
