### ISSUE TITLE
magit-blame: Missing key binding to get out

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [syl20bnr/spacemacs#2281]
When I `SPC g b`, I get into `magit-blame-mode`. Unfortunately, it is not documented on how to get out again. Seems like `SPC : magit-blame-quit` can be used to get out, but it does not seem to be bound to any key (according to `SPC ?`). Would be nice to have it bound to `q` or something…

If you agree that it is missing (and I am not just failing to find the feature), I can try to make a PR for this as well.

Edit: According to @TheBB, `q` is shadowed by `evil-record-macro` but works from insert mode. I guess `evil-record-macro` is not that useful in `magit-blame-mode`.

**Comment by jenanwise** [comment]
@Leonidas-from-XIV See #2171

**Comment by Leonidas-from-XIV** [comment]
@jenanwise Thanks, looks like that obsoletes this issue.
