### ISSUE TITLE
Projectile broken

### ISSUE THREAD

**Issue by radziej** [syl20bnr/spacemacs#2282]
Projectile is broken on the latest develop branch with fully updated melpa packages.
The error message when invoking a projecticle command is the following:
`helm-projectile-hack-actions: Wrong type argument: listp, helm-find-files-actions`

**Comment by travisbhartwell** [comment]
With `SPC t D` (or `toggle-debug-on-error`) on, I get this:

```elisp
Debugger entered--Lisp error: (wrong-type-argument listp helm-find-files-actions)
  copy-alist(helm-find-files-actions)
  helm-projectile-hack-actions(helm-find-files-actions helm-ff-browse-project helm-insert-file-name-completion-at-point helm-ff-find-sh-command helm-ff-cache-add-file (helm-ff-switch-to-eshell . helm-projectile-switch-to-eshell) (helm-ff-etags-select . helm-projectile-ff-etags-select-action) (helm-find-files-eshell-command-on-file . helm-projectile-find-files-eshell-command-on-file-action) (helm-find-file-as-root . "Find file as root `C-c r'") (helm-projectile-dired-files-new-action . "Create Dired buffer from files `C-c f'") (helm-projectile-dired-files-add-action . "Add files to Dired buffer `C-c a'"))
  byte-code("\301\302\206\n\303\304\305\"\236A\306\307\310\311\312\313\314\315\316\317&\207" [helm-source-find-files helm-projectile-hack-actions action helm-make-source "Find files" helm-source-ffiles helm-ff-browse-project helm-insert-file-name-completion-at-point helm-ff-find-sh-command helm-ff-cache-add-file (helm-ff-switch-to-eshell . helm-projectile-switch-to-eshell) (helm-ff-etags-select . helm-projectile-ff-etags-select-action) (helm-find-files-eshell-command-on-file . helm-projectile-find-files-eshell-command-on-file-action) (helm-find-file-as-root . "Find file as root `C-c r'") (helm-projectile-dired-files-new-action . "Create Dired buffer from files `C-c f'") (helm-projectile-dired-files-add-action . "Add files to Dired buffer `C-c a'")] 12)
  (defvar helm-projectile-file-actions (byte-code "\301\302\206\n\303\304\305\"\236A\306\307\310\311\312\313\314\315\316\317&\207" [helm-source-find-files helm-projectile-hack-actions action helm-make-source "Find files" helm-source-ffiles helm-ff-browse-project helm-insert-file-name-completion-at-point helm-ff-find-sh-command helm-ff-cache-add-file (helm-ff-switch-to-eshell . helm-projectile-switch-to-eshell) (helm-ff-etags-select . helm-projectile-ff-etags-select-action) (helm-find-files-eshell-command-on-file . helm-projectile-find-files-eshell-command-on-file-action) (helm-find-file-as-root . "Find file as root `C-c r'") (helm-projectile-dired-files-new-action . "Create Dired buffer from files `C-c f'") (helm-projectile-dired-files-add-action . "Add files to Dired buffer `C-c a'")] 12) ("/home/nafai/.emacs.d/elpa/helm-projectile-20150621.1322/helm-projectile.elc" . 12455))
  autoload-do-load((autoload "helm-projectile" nil t nil) helm-projectile-switch-project)
  command-execute(helm-projectile-switch-project)
```

I had a (potentially) similar error with `flycheck-ledger` recently when `flycheck` was updated.  The bytecode for `flycheck-ledger` didn't match the new `flycheck`.  I had to remove the `finance` layer and the re-add it, forcing a re-byte-compile of `flycheck-ledger` and then it worked.

Is there any way to force packages to be re-byte-compiled when one of their deps has been updated?

If that is what is truly going on here.  Sorry if it is tangential.

**Comment by robbyoconnor** [comment]
@travisbhartwell, yeah but he said he nuked his `elpa` dir already...

**Comment by travisbhartwell** [comment]
@robbyoconnor Oh, I missed that.  Okay, ignore the second half of my rambling. :)

**Comment by sewkokot** [comment]
I've got similar error today with vanilla emacs. It seems to be related with recent helm updates. Perhaps helm-projectile must be fixed to adapt helm changes... https://github.com/emacs-helm/helm/issues/1088

**Comment by zachlatta** [comment]
Running into this on stable after removing my `elpa` directory and reinstalling all packages.

**Comment by robbyoconnor** [comment]
I'm gonna guess this is a problem with a package rather than in spacemacs itself...at least based on current discussion

**Comment by syl20bnr** [comment]
If you updated via `[Update]` button on the home page then you can `[rollback]` to a previous version of projectile.
When you want to wipe out your elpa directory in a ultimate try, rename your `elpa` folder instead so you can keep the previous state around.

**Comment by csaura** [comment]
I have installed spacemacs in a new machine and is broken... the helm-projectile seems is broken

**Comment by tuhdo** [comment]
There is a proposed fix here: https://github.com/bbatsov/projectile/pull/795

**Comment by csaura** [comment]
Seems the fix is here: https://github.com/bbatsov/projectile/pull/796 and is merged, how can we try this to have `helm-find-files-actions` fixed?

**Comment by travisbhartwell** [comment]
I've verified by doing an update from the `*spacemacs*` buffer pulls in the latest `helm-projectile` and that fixes the above error.

**Comment by avendael** [comment]
Confirmed working with a fresh `.emacs.d/elpa`.

**Comment by radziej** [comment]
Works fine now. I'm closing this.
