### ISSUE TITLE
Powerline truncated with many vertical windows

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#2283]
When I have three vertical windows open, the modeline is truncated and some vital info is not showing like `git branch`, `line-nb` and `col-nb`. Turning off unicode symbols and renaming my minor modes to two-letter names helps.

I'd especially like to turn off `major` and `minor` mode indicators.

Probably not possible as of now, just something to think about for the next version.

https://github.com/syl20bnr/spacemacs/issues/524

**Comment by TheBB** [comment]
This should be relatively easy to do on a user level after #2252.

**Comment by endrebak** [comment]
Neat. Closing this, now that its out there (with a reference in 524).

Looking forward to trying it, thanks.

**Comment by TheBB** [comment]
Completely off topic, but I just saw your name in the e-mail notificaiton. You're not related to Roar Bakken Stovner, are you? I know him from NTNU, he was three years below me I think.

**Comment by endrebak** [comment]
Lols, yes. Trondhjem representin'.

**Comment by TheBB** [comment]
I just realized `SPC t m m` toggles the minor mode indicators. I'll add toggle for the major mode in #2252.

**Comment by syl20bnr** [comment]
WOW can't wait to review this ! :+1: (must go to bed now :-D)
