### ISSUE TITLE
Tables not aligned correctly in documentation view mode

### ISSUE THREAD

**Issue by travisbhartwell** [syl20bnr/spacemacs#2284]
If I view a layer's documentation using `SPC f e h`, the tables showing key bindings are rendered incorrectly, as shown here:

![docs-view-mode](https://cloud.githubusercontent.com/assets/10110/8579522/53c3fd44-2572-11e5-89bb-42a8b38ca524.png)

If I open the file directly, just in regular org-mode, it is rendered correctly:

![normal-mode](https://cloud.githubusercontent.com/assets/10110/8579550/7dd5e6ce-2572-11e5-8660-bf3acd2cb2fc.png)

It appears that rendering the key description as an image makes the column narrower than when it is just rendered as text in normal org-mode.

**Comment by robbyoconnor** [comment]
I've noticed this as well -- view it on github

**Comment by qpowell** [comment]
@robbyoconnor Stop. Collaborate and listen.

**Comment by robbyoconnor** [comment]
@qpowell, not going to pick a fight but seriously...delete that comment.

**Comment by person808** [comment]
Its the face thats used for keybindings that does this. I believe @tuhdo made a PR to fix it.

**Comment by travisbhartwell** [comment]
@person808 Thanks!  I probably should have looked through bugs and pull requests to see if this has been addressed.

**Comment by cpaulik** [comment]
Yes this was discussed in https://github.com/syl20bnr/spacemacs/issues/1568 starting [here](https://github.com/syl20bnr/spacemacs/issues/1568#issuecomment-111558767) and also in https://github.com/syl20bnr/spacemacs/pull/2039

**Comment by d12frosted** [comment]
The same here.

**Comment by JAremko** [comment]
@StreakyCobra  Can we reopen it :shipit:

**Comment by StreakyCobra** [comment]
![screenshot](https://i.imgur.com/mRup4U8.png)

**Comment by syl20bnr** [comment]
Seems already opened to me ;-)

**Comment by syl20bnr** [comment]
:joy:

**Comment by JAremko** [comment]
For moments like this I really  with we had :facepalm: emoji...

**Comment by syl20bnr** [comment]
![glasses](https://cloud.githubusercontent.com/assets/1243537/14532678/e4bbcf30-022f-11e6-9417-157ddd00a42f.jpg)

You are welcome :-)

**Comment by StreakyCobra** [comment]
> For moments like this I really wish we had :facepalm: emoji...

@JAremko Come on, you have accustomed us to better than that, I'm sure you can find or compose a  face palm kaomoji.

**Comment by JAremko** [comment]
One day one day... [1F926](http://blog.unicode.org/2015/05/unicode-90-candidate-emoji.html)
*Unicode9.0.0 Scheduled for Release: 2016 June*

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
