### ISSUE TITLE
Blank minibuffer text in lastest spacemacs for some dark themes

### ISSUE THREAD

**Issue by qqldd** [syl20bnr/spacemacs#2295]
After I upgrade to lastest spacemacs, 0.103. My favourite theme tangotango does not show mini buffer text in terminal. I also try spacemacs-dark and zenburn. They cannot show the minibuffer text. I attached the image to show this. 
![theme2](https://cloud.githubusercontent.com/assets/233128/8610225/5a78b7f4-2664-11e5-9637-fae29c61815d.png)
![theme1](https://cloud.githubusercontent.com/assets/233128/8610226/5a7a71c0-2664-11e5-99af-ead5cb96b0e7.png)

**Comment by mbertheau** [comment]
@qqldd which action were you doing that showed no text in the minibuffer? Most probably it's just showing black on black.

Please report issues with the spacemacs-dark theme to https://github.com/nashamri/spacemacs-theme.
Issues with tangotango should go to https://github.com/juba/color-theme-tangotango. (You can find that out by searching for "melpa tangotango" which gives you https://github.com/milkypostman/melpa/blob/master/recipes/tangotango-theme from where you arrive at https://github.com/juba/color-theme-tangotango)
Zenburn is here: https://github.com/bbatsov/zenburn-emacs

Thanks for your effort!

**Comment by qqldd** [comment]
@mbertheau Yes. I guess it just showing black on black. I can see the cursor moves when typing. But it is still strange to me. Since I do not have this problem before updating the spacemacs with dark themes. 

I have tested this on my OSX instead of server. With same configuration and same version of spacemacs. The OSX command line does not have strange -> on the top and show text correctly. I am not sure why/which plugin causes this.

**Comment by syl20bnr** [comment]
The input is shown in the *helm header* now. I don't know why you can see the cursor moving in the minibuffer though.
See on your screenshot, you entered `space` in the first and `tan` in the second :-D

**Comment by syl20bnr** [comment]
> I am not sure why/which plugin causes this.

This is just helm which has an option to use the header to enter the pattern instead of minibuffer, in spacemacs this option is activated by default, set `helm-echo-input-in-header-line` to `nil` in your `dotspacemacs/config` function.

**Comment by qqldd** [comment]
@syl20bnr  Thanks for you answer. This solved my problem!

> set helm-echo-input-in-header-line to nil in your dotspacemacs/config function to restore the old behavior

Yes, I am not sure why the cursor still move. It is interesting that OSX does not have this by default. (I need to test when I get my OSX)
