### ISSUE TITLE
`SPC l` should go to the start of a line

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#2300]
This would be the only use case over `SPC SPC` for me.

**Comment by endrebak** [comment]
This seems to be the default in `avy-goto-line` so it will be the default in `spacemacs` in a while I presume.

**Comment by sooheon** [comment]
@endrebak is the whole ace-jump system being re-done with avy? Do you know who's making the PR?

**Comment by xged** [comment]
@sooheon  #1534

**Comment by geo7** [comment]
@xged is this still an issue? AFAIK the default behaviour is to enter a char to jump to after SPC SPC, so if I want to jump to something that starts with `l` this method wouldn't work?

**Comment by xged** [comment]
After `avy` replaced `ace-jump` this is no longer an issue.
