### ISSUE TITLE
$ (move to end of line) then % (match parentheses) not working properly in visual mode

### ISSUE THREAD

**Issue by liujoey** [syl20bnr/spacemacs#2304]
Say we have code like this:

```java
public void foo(String bar) {
    blabla();
}
```

My cursor is at char 'f' of the function name 'foo', a quick way to select the whole function will be `Shift-v` to enter Visual-Line mode to select the first line, then press `$` move cursor to the end of the line, then press `%` to match the close brace. This `Shift-v` `$` `%` sequence works perfectly in Vim, but not in Evil.
When in Evil visual mode, if you press `$`, the cursor moves one char further than the last char of '{', just as same as it does in Vim, but then `%` does nothing. In Vim even the cursor is one char right to the last char, `%` can still jump to the close curly brace. But in Evil, I have to press `h` key once, move my cursor one char back to make `%` to work. I've also submitted an issue on Evil's issue tracking site. This bugs me a lot because my muscle memory is so strong about this one.

**Comment by sooheon** [comment]
Definitely an issue for `evil`, not spacemacs. I understand the frustration though. Until you get an answer from there, you could learn the spacemacs way, which would be (starting from the same place) `$` `SPC` `v`, which is the same number of commands and even easier imo. Part of the reason for spacemacs is so you can learn hybrid ways to do things, so experiment :)

**Comment by TheBB** [comment]
Another workaround is to do things in visual state first (where in my experience `%` works fine), and then later use `V` to enter visual line state from visual state.

**Comment by liujoey** [comment]
@sooheon Thanks, but `SPC` `v` only selects the braces, not including the function name.

**Comment by StreakyCobra** [comment]
I can't reproduce the bug anymore. @liujoey Is this still the case for you?

**Comment by liujoey** [comment]
@StreakyCobra The bug is gone, I guess the recent evil updates fixed this issue.
