### ISSUE TITLE
Things broke atomic undo

### ISSUE THREAD

**Issue by liujoey** [syl20bnr/spacemacs#2305]
In Vim there's a very important concept called atomic undo, that says when user enter insert mode and add some text to the file, he can later undo his edit atomically.

Today I found that company-mode will break it. (not sure if it's just company-mode or it applies to all auto-complete packages)

So if I'm typing `Som` and if company-mode showing a completing suggestion of `SomeFunction`,  then later if I wish to undo this edit, I have to press `u` twice, the first undo only removes 'eFunction`, and the second one returns my file to the original status.

Some other things like auto-indent when pasting. Emacs is smart enough to auto-indent a block when I do pasting. But if I want to undo that paste, I have to press `u` twice, the first one undo indentation, the second one removes the text. Which is not consistent with Vim's behavior.

**Comment by sooheon** [comment]
What is the value of `evil-want-fine-undo`?

**Comment by liujoey** [comment]
@sooheon Thank you, you saved my day. By change this to nil, it acts like vim now. So many things need to learn, it makes me exciting :-)
