### ISSUE TITLE
Proper way to set a default font and size

### ISSUE THREAD

**Issue by drj42** [syl20bnr/spacemacs#231]
Spacemacs resets the font size to 12, no matter where I set the font in my private config layers or .spacemacs.  When initializing all the packages, it will temporarily switch to my preferred font size, then switch back to 12 when initialization is complete.  Is there a way around this?  It might be nice to have a default font list configurable in the .spacemacs file, that gracefully fails when a font is not installed on the system.

**Comment by vijaykiran** [comment]
FYI as of 27-Jan-2015 I'd to use  the set-font as follows 

`(spacemacs/set-font '("Menlo" :size 12))`

**Comment by andresmrm** [comment]
Hello! I placed a `dotspacemacs-default-font` in `.spacemacs`, and it works fine after startup. But when I switch theme (e.g.: `SPC T n`) the font size gets reseted. Others font parameters seem to remain untouched. Any ideas?

**Comment by vijaykiran** [comment]
Does it happen for every theme ? Do you see any other font setting in (custom-set-variables in emacs)?

**Comment by andresmrm** [comment]
Thanks for the reply!

Yes, for every theme when using `SPC T h` too.
And no, I seem to have no other font setting...

**Comment by j127** [comment]
I'm having trouble with this too. The only thing I changed in `.spacemacs` is the font size (to 17), but the font size doesn't change, even after restart.

```lisp
   dotspacemacs-default-font '("Source Code Pro"
                               :size 17
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
```

**Comment by TheBB** [comment]
@j127 You have SCP installed?

**Comment by j127** [comment]
@TheBB Secure copy? Yes.

**Comment by StreakyCobra** [comment]
I think he meant "Source Code Pro" :-)

**Comment by j127** [comment]
Hmmmm... that would make more sense. Downloading that font worked, and now choosing Source Code Pro doesn't make my editors' fonts look bad any more. :)

Thanks!

**Comment by TheBB** [comment]
Good. If the font specified in `dotspacemacs-default-font` does not exist, then none of the settings will be applied either (size, weight etc.)

**Comment by andru255** [comment]
I try to setting like this: `dotspacemacs-default-font '("Source Code Pro"
                               :size 18
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)` but don't works, I restarted spacemacs but nothing, I use spacemacs on lubuntu distro.

**Comment by kyp0717** [comment]
Hi.  New to spacemacs.  Love it.  So, I know that you are suppose to put this function inside the .spacemacs file.  But need more specific.  Need the exact function.  Is it in dotspacemacs/user-config ?

**Comment by TheBB** [comment]
It should already be in your dotfile. Just change the value that is already there.

**Comment by SeAL80s** [comment]
How to set a Bold font ,like YaHei Consolas Hybrid Bold . YaHei Consolas Hybrid does have Bold font,but it's not woking in emacs .

**Comment by SeAL80s** [comment]
@kyp0717 
It's already in .spacemacs file . Like this .In line 135

dotspacemacs-default-font '("YaHei Consolas Hybrid"
                               :size 16
                               :weight normal
                               :width normal
                               :powerline-scale 1.2)

**Comment by bersace** [comment]
Hi,

I'm wondering why do we need to use higher font size in Emacs rather than the desktop (I'm using GNOME). Here i have terminator and gnome-terminal at 12 and i need emacs to be at 16 to have similar font size. Do you have a clue ?

Regards,

**Comment by robbert-vdh** [comment]
Presumably because Emacs defines font sizes in pixels while GTK uses points, and 12 points equals 16 pixels at 96 pixels per inch.

**Comment by bersace** [comment]
@robbert-vdh so `:size` and `:pixel-size` are the same ?

**Comment by robbert-vdh** [comment]
I couldn't find anything about `:pixel-size`, but I did find the [font specification](https://www.gnu.org/software/emacs/manual/html_node/elisp/Low_002dLevel-Font.html):

> **:size**
>     The font size—either a non-negative integer that specifies the pixel size, or a floating-point number that specifies the point size. 

So it's a bit of a weird case. `:size 12.0` should apparently be equivalent to `:size 16`.

**Comment by bersace** [comment]
@robbert-vdh Good point !! Actually, i suggest to use float in documentation. With the raise of HiDPI screen, it's better to use point rather than pixel, isn't it ?

**Comment by GrimPixel** [comment]
Hi, I have a problem. In my `.spacemacs`:
```
(defun dotspacemacs/init ()
  (setq-default
   dotspacemacs-default-font '("Source Code Pro"
                               :size 24.0
                               :weight normal
                               :width normal
                               :powerline-scale 1.2
                               )))
```

It doesn't work. Could you find anything wrong there?

A few moments later

I edited the file at `/home/user/.emacs.d/.circleci/web` instead of that one at `/home/user/`. Problem solved.

**Comment by wravoc** [comment]
I reviewed this and other issues.

## Setup
* Macbook Pro Ventura
* Compiled from [GitHub emacs](https://github.com/emacs-mirror/emacs) using autogen.sh, nextstep INSALL
* Cloned Spacemacs into .emacs.d

## Incident
Everything was working great until I tried to resize the font in my `.spaceamcs` > `dotspacemacs-default-font` > `:size 14.0` also tried `:size 14`

## Result
1. Reboots into minibuffer asking "Pick your editing style for recovery`
2. Select emacs
3. Starts up with 10 size font
4. Set Font in Options to 14, Click "OK" 
5. Restart - GOTO 1
