### ISSUE TITLE
Create shortcut for projectile-find-other-file

### ISSUE THREAD

**Issue by sunesimonsen** [syl20bnr/spacemacs#2314]
I would really like a shortcut for `projectile-find-other-file` - it would make sense to have it on `SPC p a` (think alternate).

**Comment by tuhdo** [comment]
It already is the case. You can check by pressing `C-h k` and press `SPC p a`. Emacs will show you help buffer for `projectile-find-other-file`.

**Comment by sunesimonsen** [comment]
I'm on an updated master and I get `SPC p a is undefined`.

**Comment by sunesimonsen** [comment]
@tuhdo are you sure you didn't configured the shortcut your self, I'm on a newly installed spacemacs and  `SPC p a` is undefined?

**Comment by tuhdo** [comment]
You are right. Actually I am using `C-c` as Emacs leader key, so it fits the default `C-c p a` comes with Projectile.

**Comment by bmag** [comment]
@sunesimonsen the `c-c++` layer binds `projectile-find-other-file` and `projectile-find-other-file-other-window` to <kbd>SPC m g a</kbd> and <kbd>SPC m g A</kbd>. Didn't test it myself, but looking in the code it should work.

**Comment by sunesimonsen** [comment]
Thanks @tuhdo and @bmag, I still think it would be nice to bind it to the more general key combination - hope you agree :-)

**Comment by bmag** [comment]
Apparently it was decided to make this a per-mode shortcut and not a global one. See https://github.com/syl20bnr/spacemacs/pull/869#issuecomment-85331474 and https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.org#code-navigation. Personally I don't have an opinion on the matter.

**Comment by sunesimonsen** [comment]
@bmag thanks for clearing that up, then I'll just close the issue.
