### ISSUE TITLE
*Async Shell Command* buffer opens in insert mode

### ISSUE THREAD

**Issue by ocharles** [syl20bnr/spacemacs#2318]
This seems a little weird to me - surely this buffer shouldn't be editable at all?

Steps to reproduce:

* Open a file from a project
* Hit `Spc p &`
* Type a command. For example `date`
* Observe that a buffer opens in insert mode.

Maybe we should have a "micro-mode" (or whatever it's called?) that lets the user hit `q` to close the buffer? That is my expectation as a user, I'm not sure how others feel.

If this sounds like a good idea, let me know and I'll try and provide a pull request.

**Comment by bmag** [comment]
I see that "\*Async Shell Command\*" uses the `shell-mode` major-mode, which is the mode used for shell buffers (see <kbd>SPC a s i</kbd> if you have the `shell` layer, or the `shell` command).
For a shell buffer it does make sense to open in insert state, so that explains why "\*Async Shell Command\*" also opens in insert state.
I don't know why the async buffer uses `shell-mode`, there may be a reason. But if you want to change it, you'd probably want it in motion state.
If all you want is to close the window, you can type <kbd>C-g</kbd>. It works because Popwin is used to open the window.

**Comment by ocharles** [comment]
While `C-g` does help, it messes up the buffer ordering. This means if you edit `A`, then `B`, then call an async command, after hitting `C-g`, `Spc Tab` returns you to the compilation buffer, not `A`. The buffer should probably be entirely destroyde, rather than the window hidden.

**Comment by bmag** [comment]
If you insist on using <kbd>q</kbd> then I don't know if there is a good solution to this situation. However, there are alternatives:
- use <kbd>C-x 4 0</kbd>, which runs `kill-buffer-and-window` - it will kill the buffer and close the window
- bind `quit-window` to some key, possibly <kbd>SPC w q</kbd>, and use that. This is what <kbd>q</kbd> usually does in similar buffers (such as \*Help\*).

If you insist on <kbd>q</kbd>, then the following hack can be applied, but it's not very pretty:
```elisp
(defun maybe-set-quit-key ()
  (when (string= (buffer-name) "*Async Shell Command*")
    (local-set-key (kbd "q") #'quit-window)))

(add-hook 'shell-mode-hook #'maybe-set-quit-key)
```

**Comment by ocharles** [comment]
I'm not trying to insist on something, I'm simply trying to find a more natural flow that fits with Spacemacs. I have solutions that work with me, but they don't feel natural. I only suggest `q` because in other similar buffers, `q` does what I mean. It also feels strange to me that this buffer can be edited, despite it's intention to be read-only.

**Comment by EricCrosson** [comment]
Back to your original comment, what else would the micro-state be used for? `q` would be a dangerous key as it would kill the external program too. The open buffer seems to be normal stdio, this is useful in many situations.

**Comment by ocharles** [comment]
Oh, I hadn't considered I/O - I only use it with commands that run to completion (like refreshing a projects sandbox environment). That's a fair point. For me, the microstate would be useful for navigation (e.g., jumping to the top of the output with `gg`)

**Comment by EricCrosson** [comment]
This is oddly specific, breaks the congruity of spacemacs and is personal to your desires. I see no reason for a micro state - I believe this works against the majority of async buffer use cases.  if you desire to implement these changes they can always remain in your personal conigs. Consider adding to one of the shell-mode hooks to force your buffers to normal mode. 

I've always considered one of the great things about spacemacs to be how much is accomplished with how little code. I feel like this change would add lots of edge-case code with very little added functionality.

Binding `quit-window` is the correct approach here.

**Comment by ocharles** [comment]
Ok, I'll go with a local binding to `quit-window`. Thanks for providing a snippet that shows how to do that, @bmag!
