### ISSUE TITLE
Unable to use spacemacs|add-toggle macro with custom setup for imenu-list

### ISSUE THREAD

**Issue by usharf** [syl20bnr/spacemacs#2319]
Any idea why this code does not work as expected?
It will toggle on, but not off.

`imenu-list-minor-mode` used in status is `t` or `nil` and is set by calling the toggle function by the same name.

```emacs-lisp
  (spacemacs|add-toggle imenu-list-minor-mode
                        :status imenu-list-minor-mode
                        :on (imenu-list-minor-mode)
                        :documentation "Toggle imenu-list sidebar"
                        :evil-leader "Tim")
```

Also tried with :off, but it did not work.

PS I'm aware of helm-imenu, but just needed something that can stay visible.

**Comment by bmag** [comment]
Did you try `(imenu-list-minor-mode -1)` for :off?
When you call minor-mode functions from elisp code, it works like this:
```elisp
(foo-mode) ;; turn on foo mode
(foo-mode 1) ;; turn on foo mode
(foo-mode -1) ;; turn off foo mode
(foo-mode 'toggle) ;; toggle foo mode
```

**Comment by usharf** [comment]
I think I've tried (with nil) and it didn't work, regardless, wan't aware of the difference between calling it interactively or from code.

10x!
