### ISSUE TITLE
Company backends should be grouped

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#2323]
I think company backends should be grouped and not pushed to the beginning of the list.

e.g. in python `company-anaconda` is pushed to the beginning of the `company-backends` which means all the other backends are never used even if `company-anaconda` can not find a completion candidate. It would however be great if `company-dabbrev-code` could be used in tandem with `company-anaconda`

Per default the value of `company-backends-python-mode` is 

``` elisp
(company-anaconda
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)
```

I think it should be 

``` elisp
((company-anaconda
 company-dabbrev-code company-gtags company-etags company-keywords
 company-files company-dabbrev))
```

Unless I misunderstood how company works and this should be handled by `company-anaconda`

**Comment by nookiepl** [comment]
Is there way to override this variable in configuration? (excuse me, total emacs newbie, coming from VIM :D)

**Comment by zilongshanren** [comment]
@cpaulik
If a company backend can't complete at the point, it will fallback to the next backend.
If you input something in the Python comments, it will use `company-dabbrev` backend.

Am I wrong?

**Comment by nookiepl** [comment]
Ok, with trial and error method I've added to dotspacemacs/config this

     (setq company-backends-python-mode '((company-anaconda
                                        company-dabbrev :with company-yasnippet)))

And it's working.

@zilongshanren, AFAIK, you are wrong (https://github.com/proofit404/company-anaconda/issues/8).

**Comment by cpaulik** [comment]
@zilongshanren That is what I thought too, but according to one of the company-mode developers in the discussion at https://github.com/proofit404/company-anaconda/issues/8# this is not the case

**Comment by cpaulik** [comment]
@zilongshanren actually you are partly correct. If point is in a region where a backend can not complete then it will move to the next backend. If however a backend could complete in theory but can not come up with any completion candidates then it will not choose the next backend.

**Comment by zilongshanren** [comment]
@cpaulik  @nookiepl 
Thanks,  I have read the discussion in (proofit404/company-anaconda#8), it is more clearer to me now.
But it we group `company-anaconda` and `company-dabbrev`, wouldn't it be many candidates in the list?

**Comment by zilongshanren** [comment]
@cpaulik  I have modified my company backends to 
```
(setq company-backends-c-mode-common '((company-c-headers
                                          company-ycmd
                                          company-dabbrev :with company-yasnippet)))
```

It's a bit win, thanks.

**Comment by cpaulik** [comment]
After trying this for a while I actually think that there might be too many candidates mixed. It seems that the completion candidates are not ordered by backend which I see as a problem.

**Comment by cpaulik** [comment]
We could fix this by changing the `company-transformers` variable to use `company-sort-by-backend-importance` instead of `company-sort-by-occurance`.

@syl20bnr Do you think it makes sense to add a option for it or should this become the default if we decide to group backends?

**Comment by cpaulik** [comment]
@syl20bnr Have you had a chance to look at this? I've been using grouped backends sorted by backend importance for a while now and it works well. At least in python.

**Comment by syl20bnr** [comment]
I totally missed this issue, sorry about that.

None of the options listed above are OK to me but we can damage control by trying your last proposition to sort by backends. What I don't like at all is that it implies a lot of computing for nothing and it does not scale very well.

**Comment by syl20bnr** [comment]
With the sorting by backend importance, what about backends declared with `:with` ?

**Comment by cpaulik** [comment]
I see your point about the computation. The thing is that at least for python the other backends are hardly ever used since `company-anaconda` can often find no completion candidate but tries. 

At the moment I use 
```elisp
    (setq company-backends-python-mode '((company-anaconda :with company-dabbrev :with company-yasnippet)))
    (setq company-transformers '(spacemacs//company-transformer-cancel
                                 company-sort-by-backend-importance))
```

If now get completion for variable names and module names that anaconda can not resolve but that I have used before. This is IMHO way superior to the current system. 

I think that the main completion mode and `company-dabbrev-code` might be a good group. 

As far as I can tell the backends are sorted properly only if `:with` is used.
