### ISSUE TITLE
Indent text objects are broken

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#2326]
Spacemacs includes the [evil-indent-textobject](https://github.com/cofi/evil-indent-textobject) package, which provides the `ii`, `ai` and `aI` text objects based on indentation level. 

Unfortunately, as per https://github.com/cofi/evil-indent-textobject/issues/1, it is broken.

* It treats empty lines as having zero indentation, when in reality they have 'any' indentation.
    ```python
    if condition:
        do_one_thing()

        do_another_thing()
    ```
With cursor on `do_one_thing()`, try `vii`, `do_another_thing()` will not be selected.

* It does not select lines with higher indentation.
    ```python
    if condition:
        if another_condition:
            do_one_thing()
        do_another_thing()
    ```
With cursor on `if another_condition:`, try `vii`, neither function calls will be selected.

I have a fork of the package [here](https://github.com/TheBB/evil-indent-textobject) which fixes both issues. It's provided in a layer [here](https://github.com/TheBB/spacemacs-layers). It uses slightly different semantics from `evil-indent-textobject`, however.

Options can be:
* Use a fixed version of the package in Spacemacs as an extension.
* Remove the package from Spacemacs, since it doesn't do what it says it does. (And what it does do is nearly useless.)
* Push harder to get @cofi out of hibernation and fix it upstream. The cited issue has been open for a year with no resolution.

CC @cofi @endrebak

**Comment by endrebak** [comment]
When I read through the docs, this seemed like a killer feature of spacemacs - was disappointed and surprised to see how badly it worked for Python (where indentation is syntax). Even if you do not merge this for some reason, it might be a good idea to remove the original because it really does nothing but steal keyboard space for other sensible text-objects.

**Comment by endrebak** [comment]
Is the following supposed to work: 
Put cursor on `r = R()` and press `d i i` and the whole thing between `try` and `except` should be deleted?

```Python
try:
    from widediaper import R
    r = R()

    r.load_library("rafalib")
    r.send(weight_controls, "y")
    print(r("popvar(unlist(y))"), "r popvar")
except ImportError:
    pass
```

**Comment by TheBB** [comment]
Yeah, that's supposed to work, and *does* work for me.

**Comment by endrebak** [comment]
Thanks, will look into if anyone else can confirm that they are unable to do this. Otherwise I guess it is just me.

**Comment by a-sk** [comment]
Yeah, I copy-pasted your example and `d i i` deleted the whole thing between try and except.
