### ISSUE TITLE
editorconfig layer

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#2330]
What happened to editorconfig layer?

**Comment by tko** [comment]
Deleted as obsolete, just add `editorconfig` in `dotspacemacs-additional-packages` instead, I think. See https://github.com/syl20bnr/spacemacs/pull/1526

**Comment by jasoncyu** [comment]
it was decided that it didn't need a layer b/c there was almost no setup involved besides requiring the package. So if you just add it to `dotspacemacs-additional-packages`, and do the setup in the spacemacs config function, you're good

**Comment by EricCrosson** [comment]
Closed?

**Comment by jvillasante** [comment]
Yeah

**Comment by EricCrosson** [comment]
Can you mark as such? I am not allowed - not the creator/repo owner.
Please and thank you!

Happy hacking.
