### ISSUE TITLE
How to adjust indent level of Javascript and JSON?

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#2333]
Thing I've tried that didn't work:
- `js-indent-level`
- `json-reformat:indent-width`

**Comment by travisbhartwell** [comment]
For Javascript, if you are using the `javascript` layer, it uses the `js2-mode`.  To adjust the indentation level, set `js2-basic-offset`.  I just tested on a JSON file, and it is indeed `js-indent-level`.

If you wish to set values for these globally, add this to your `dotspacemacs/init` function in `.spacemacs`:

```emacs-lisp
(setq-default js2-basic-offset 2
                     js-indent-level 2)
```
After each of these have been set appropriately, highlight the region you wish to reindent, then hit `SPC j =`.

Hope this helps.

**Comment by travisbhartwell** [comment]
I've created a pull request here syl20bnr/spacemacs#2303 that addresses the Javascript issue, perhaps I should also augment it to specify how to indent JSON files.

**Comment by louy2** [comment]
Thank you! :+1: :heart:

**Comment by santiagobasulto** [comment]
This is old, but thanks @travisbhartwell.

**Comment by bandagriss** [comment]
Genial gracias me ayudo bastante :+1:
