### ISSUE TITLE
evil-mode breaks when the mini-buffer is not empty.

### ISSUE THREAD

**Issue by benjamintanweihao** [syl20bnr/spacemacs#2334]
I finally managed to reproduce this:

<img width="626" alt="_spacemacs_and_1__emacs__guile__and_desktop" src="https://cloud.githubusercontent.com/assets/861236/8714166/6f92f498-2ba4-11e5-905d-725b3841eeed.png">

Deleting a single line isn't the only command that has issues. Deleting multiple lines for example will only delete the line on the cursor. 

I'm not sure if this is the intended behavior, but I'm glad I figured out the problem :dancers:

**Comment by paulhenrich** [comment]
I get this too from time to time and can fix by going down to the mini-buffer with ^w commands and aborting with ^g. I think I have also recovered from it by cycling <space>:turn-[off|on]-evil-mode.

For what it's worth, I have also seen additional weirdness with vim bindings when it gets in this state that are parallel to the behavior you have described.

**Comment by benjamintanweihao** [comment]
Thanks @paulhenrich ! I thought I was the only one with this issue, and had to restart Emacs each time. For now, clearing the mini-buffer seems like the way to go.

**Comment by paulhenrich** [comment]
My pleasure. I'd love to figure out what actually triggers this state and track down the bug, but so far I haven't been able to intentionally reproduce it.

**Comment by StreakyCobra** [comment]
I can't reproduce this bug. Each time the focus is lost from the mini-buffer, it exits, so I can't press `d` while the minibuffer is open. Do you still have this problem?

**Comment by TheBB** [comment]
I use `SPC w b` to get back to the minibuffer when I accidentally focus another window. We have documented that as (for now) the "official" solution to this issue, however unsatisfactory that may be.

**Comment by d12frosted** [comment]
@TheBB didn't know about `SPC w b`. Thanks for nice advice.
