### ISSUE TITLE
How can I setting the number of "Recent Files" in the *spacemacs* buffer?

### ISSUE THREAD

**Issue by young40** [syl20bnr/spacemacs#2335]

**Comment by fandag** [comment]
Currently, it is hardcoded in the core-spacemacs-buffer.el file on line 493:
https://github.com/syl20bnr/spacemacs/blob/master/core/core-spacemacs-buffer.el#L493

**Comment by young40** [comment]
@fandag Thank u, 

hope it can be in config

**Comment by TheBB** [comment]
Fixed by #2342.
