### ISSUE TITLE
[Proposal] add evil-ranger

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2336]
Should i make a PR to add [evil-ranger](https://github.com/ralesi/evil-ranger) to spacemacs? Would it be useful?

**Comment by cpaulik** [comment]
https://github.com/syl20bnr/spacemacs/pull/2325

**Comment by robbyoconnor** [comment]
Okay -- sorry about that @cpaulik -- I should have done a search first... closing this
