### ISSUE TITLE
Can't leave magit-blame using SPC g b

### ISSUE THREAD

**Issue by shaief** [syl20bnr/spacemacs#2337]
I use `SPC g b` to enter `magit-blame` and i used to use the same key sequence to leave `magit-blame`. On recent `develop` with `emacs 24.5` i can't leave.
I can leave using both:
`SPC : magit-blame-quit RET`
or
`i` and then `q`.

It was verified with other users as well.

Thanks!

**Comment by cpaulik** [comment]
Thanks, but this seems to be a duplicate of https://github.com/syl20bnr/spacemacs/issues/2281 and https://github.com/syl20bnr/spacemacs/issues/2171

**Comment by shaief** [comment]
Yes and no. I reported that this sequence used to work but now it is not. I didn't ask for a new key sequence...

**Comment by StreakyCobra** [comment]
`magit-blame` has now its own micro-state that allows to exit with `q` (only on `develop` yet)
