### ISSUE TITLE
structured haskell mode does not expand current node

### ISSUE THREAD

**Issue by kRITZCREEK** [syl20bnr/spacemacs#2338]
When pressing `)` in structured-haskell-mode the current node should be expanded but currently the cursor just moves. This prevents usage of the many shm features on the current node.

Steps to reproduce:
``` haskell
    (ret|urn ())
```

1. Move Cursor to `|` 
2. press `)` multiple times.

Expected:

![output2](https://cloud.githubusercontent.com/assets/6189397/8723038/e142bdf0-2bca-11e5-86a2-350d6ecc71be.gif)

Actual:

![output](https://cloud.githubusercontent.com/assets/6189397/8723044/ee3daba0-2bca-11e5-80de-2ff2ce126512.gif)

Explanation: The grey background shows the currently selected node.

**Comment by d12frosted** [comment]
@TheBB I would close it in favour of #1048 (the same as it was with #3171). Oh and also, please, add 'haskell' label.

**Comment by kRITZCREEK** [comment]
Closing in favor of #1048
