### ISSUE TITLE
Disable auto-expansion of snippets

### ISSUE THREAD

**Issue by morhekil** [syl20bnr/spacemacs#2339]
After one of recent updates, ruby mode started expanding some abbreviation automatically as I type. At first I thought that it is coming from abbrev-mode, but the expansions look more like the ones from yasnippet (as the cursor is being put in the middle, etc).

The problem is that they are not really the same as the ones that I get when I trigger a snippet expansion manually (via M-/), and they behave weirdly - TAB doesn't move the cursor anywhere, and the highlighting over the expansion area stays intact, until I just move the cursor out of it. The expansion looks like this:

<img width="181" alt="expansion" src="https://cloud.githubusercontent.com/assets/13393/8726030/fb01a7ce-2c1a-11e5-9f89-815b1b8d8147.png">

I'd really like to disable it, as it is very annoying to have it triggered every time by itself, but I can't identify which package triggers this behaviour. It seems to be mostly affecting ruby mode - e.g. I don't see the same problem in go mode, as snippets are not auto-expanded in that one.

Could anyone give me any hints about where this might be coming from, and how to disable it?

**Comment by jasoncyu** [comment]
i think it's from smartparens since it's a matching pair kind of completion. It might be defined in one of the more advanced ruby mode, which is called something like enh-ruby-mode. you could try turning that off or looking into the documentation for it

**Comment by morhekil** [comment]
@jasoncyu thank you! It was smartparens indeed, looks like it ships with [some ruby completions](https://github.com/Fuco1/smartparens/blob/master/smartparens-ruby.el) by default.
