### ISSUE TITLE
Holy-mode: C-n is broken in magit-status buffer

### ISSUE THREAD

**Issue by Peeja** [syl20bnr/spacemacs#2340]
In holy-mode, inside a magit-status buffer, <kbd>C-n</kbd> is bound to `magit-section-forward--evilified-magit-mode-map-C-n`, which sounds pretty useful, but appears to do nothing. <kbd>C-p</kbd>, meanwhile, is bound to `previous-line`, and works as expected.

**Comment by CestDiego** [comment]
Try binding it to what `C-j` and `C-k` are.

**Comment by TheBB** [comment]
Duplicate https://github.com/syl20bnr/spacemacs/issues/2277

**Comment by tuhdo** [comment]
To temporary fix this problem, add this to your `dotspacemacs/config` function:

```elisp
(with-eval-after-load 'magit
    (define-key magit-mode-map (kbd "C-n") 'next-line))
```

**Comment by Peeja** [comment]
@tuhdo Thanks!

Closing as dupe.
