### ISSUE TITLE
The Vim shortcut 'y' does not work correctly

### ISSUE THREAD

**Issue by fladd** [syl20bnr/spacemacs#2344]
In Vim, when I select a region in visual mode, and then hit 'y', it copies the whole selection. A subsequent 'p' will hence paste the whole selection.

In Spacemacs, only the last line of the selection will be pasted.

**Comment by sooheon** [comment]
Strange bug. I can reproduce, only if there is no cursor movement between `y` and `p`. Moving the cursor in any way allows expected `p` behaviour. You should report the bug to `evil-mode` upstream.

**Comment by ReneFroger** [comment]
I don't have this in my custom config (with no Spacemacs configuration, only Emacs and Evil with bunch of packages). So I guess this is more related to Spacemacs than Evil itself.

**Comment by cpaulik** [comment]
I can not reproduce this. Are you on master or on the develop branch?

**Comment by fladd** [comment]
Yes, I am on Master. However, the problem does not occur consistently. Right now, it works correctly. But when I reported this problem, Emacs was in a state where it consistently behaved that way.

**Comment by robbyoconnor** [comment]
@fladd try on `develop`?

**Comment by geo7** [comment]
@fladd what's the current state on this? Report any news, if alls good close the issue please :+1:

**Comment by robbyoconnor** [comment]
I been using both `y` and `Y` -- and both work fine for me. @fladd -- Update to the latest `develop` and try again?

**Comment by fladd** [comment]
I haven't encountered this problem anymore. I don't know what happened back then. I'm still on master.

**Comment by TheBB** [comment]
Then I choose to be optimistic.
