### ISSUE TITLE
C-r doesn't work as expected in term mode

### ISSUE THREAD

**Issue by alexandergitter** [syl20bnr/spacemacs#2345]
Using emacs's term mode (`M-x term`), I can't find a way to send a literal "Ctrl + r" to the terminal. Shells like Bash and Zsh use it for searching commands in the history.

This works fine with the default emacs settings (`$ emacs -q`)

**Comment by EricCrosson** [comment]
What mode are you working in, inside of term mode? If you're using the evil layers... well, C-r isn't search backward in vim at all. This is to be expected. Did you try dropping into emacs mode in the term?

**Comment by alexandergitter** [comment]
Yes, this is about term mode.
I tried switching to holy-mode, but still C-r doesn't work as expected.

You are of course right that C-r has nothing to do with backward search in vim. What I was referring to is sending C-r to the shell, because Bash and Zsh for example use it to search the history (https://www.gnu.org/software/bash/manual/html_node/Searching.html)
This works in vanilla emacs.

**Comment by EricCrosson** [comment]
I'm going to restate myself.

We both agree: 
C-r works in stock emacs as reverse search, like shells usually do.
You disabled stock emacs mode in favor of vim editing.
Your C-r is upholding the vim responsibility.

This is not an issue. What you are missing is some personal configuration tweaks.

**Comment by alexandergitter** [comment]
Fair enough, I'll look at tweaking my configuration like you suggested.
Thanks!

**Comment by TheBB** [comment]
Putting this here for the future.

```elisp
(defun bb/setup-term-mode ()
  (evil-local-set-key 'insert (kbd "C-r") 'bb/send-C-r))

(defun bb/send-C-r ()
  (interactive)
  (term-send-raw-string "\C-r"))

(add-hook 'term-mode-hook 'bb/setup-term-mode)
```

**Comment by streichman** [comment]
@TheBB Thanks for that fix - was trying to get zsh fzf working in multi-term mode.
