### ISSUE TITLE
Paste micro-state behavior

### ISSUE THREAD

**Issue by Kernael** [syl20bnr/spacemacs#2346]
With `dotspacemacs-enable-paste-micro-state t`, pasting will effectively iterate over the kill ring while pressing 'p', but it doesn't delete the previous content each time 'p' is pressed.

Isn't it supposed to paste & replace the content everytime 'p' is pressed ?

**Comment by louy2** [comment]
I have tested and it works as expected, with the iteration going on in-place. Could you provide more details on reproducing?

**Comment by Kernael** [comment]
Nothing special I'm afraid, just yanking several lines, then hitting 'p' repeatedly, correctly iterates over the kill ring but doesn't replace the previous content.

**Comment by louy2** [comment]
Strange. Have you updated to the latest `develop`? Do you see anything in `*Messages*`?

**Comment by Kernael** [comment]
Noticed that it is working correctly in Fundamental major mode, I saw in *Messages* that `Undo !` was called every time, but with at least Elixir, Ruby and JS majors, `Undo !` is not called.

**Comment by louy2** [comment]
My `js2-mode` is working fine though. Can you undo manually in your affected buffers?

**Comment by Kernael** [comment]
Didn't see good :  `Undo !` actually appears in `*Messages*` when pasting repeatedly, but  it doesn't seem to take effect.
But I think I found the culprit, the incorrect pasting seems to occur when the line yanked is not indented as the same level as the current block, hence why it works every time in `Fundamental`, no "forced" indentation. When pasting, it always try to indent the line.

**Comment by louy2** [comment]
Oh! Bug replicated! Indeed, when a reindentation is applied, the undo only undoes the indentation, not the paste. I wonder how to fix this... probably have to keep track of the undo-tree and remember a postition or count undo points creations. Have to consult undo-tree doc.

**Comment by syl20bnr** [comment]
This bug have been annoying me for a long time, it should be fixed in develop.
