### ISSUE TITLE
emacs-nox yank to X-11 clipboard

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#2347]
as the problem in  #2222 
when i ssh to server, 
  emacs has no knowledge about X11 system clipboard. in my daily work, i always yank my buffer's content to search engine or somewhere. 
but with out X11 support. emacs complain "x-set-selection: Symbol's funtion definition is void: x-own-selection-internal"

with package gnu 'xclip' from melpa and apt-get  install xclip in linux can solve this problem.How can I  integrate xclip into spacemacs elegantly? 
Any ideas?
thank you.

**Comment by duerrp** [comment]
I use xsel for that purpose:

```
(defun peter/init-xclip ()
  (defun copy-to-clipboard ()
    "Copies selection to x-clipboard."
    (interactive)
    (if (display-graphic-p)
        (progn
          (message "Yanked region to x-clipboard!")
          (call-interactively 'clipboard-kill-ring-save)
          )
      (if (region-active-p)
          (progn
            (shell-command-on-region (region-beginning) (region-end) "xsel -i -b")
            (message "Yanked region to clipboard!")
            (deactivate-mark))
        (message "No region active; can't yank to clipboard!")))
    )

  (defun paste-from-clipboard ()
    "Pastes from x-clipboard."
    (interactive)
    (if (display-graphic-p)
        (progn
          (clipboard-yank)
          (message "graphics active")
          )
      (insert (shell-command-to-string "xsel -o -b"))
      )
    )

  (evil-leader/set-key "o y" 'copy-to-clipboard)
  (evil-leader/set-key "o p" 'paste-from-clipboard)
  )
```

**Comment by dzhwinter** [comment]
Nice work! 
I'm stuck in xclip's ugly solution for days!

**Comment by Evidlo** [comment]
In case anyone's interested, you can change `xsel -i -b` to `xsel -i -p` and `xsel -o -b` to `xsel -o -p` to have it go to the primary buffer instead of the clipboard.
