### ISSUE TITLE
Robe-mode does not work properly for ruby files

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2349]
So I was working with a ruby file and noticed that `robe-mode` did not work properly using <kbd>SPC m g g</kbd> and I fell back to the regular emacs keybindings of <kbd>M-</kbd> -- Why is this the case?

**Comment by StreakyCobra** [comment]
Is this bug still appearing in last `develop`?

**Comment by robbyoconnor** [comment]
Somewhat, yes.
