### ISSUE TITLE
Delete-trailing whitespace--enable by default

### ISSUE THREAD

**Issue by chrisbarrett** [syl20bnr/spacemacs#235]
It's pretty common for Emacs users to add `delete-trailing-whitespace`to `before-save-hook`. Spacemacs doesn't have that set up, and I've seen at least one PR that has heaps of unrelated whitespace changes (#230) because the Spacemacs codebase has trailing whitespace throughout.

I propose we automatically delete trailing spaces on save in this configuration, and run a whitespace cleanup over this codebase. I can submit a PR. Any objections?

**Comment by syl20bnr** [comment]
I'll keep an eye on it and we will reconsider it.

Where is highlight-changes-mode used ?

**Comment by chrisbarrett** [comment]
When I use undo in spacemacs I get highlights in modified regions--is that using highlight-changes-mode?

**Comment by syl20bnr** [comment]
Nope that's volatile-highlight but maybe it uses this under the hood ?

**Comment by syl20bnr** [comment]
We may reconsider using ws-butler.

**Comment by StreakyCobra** [comment]
I just tried `ws-butler` by adding it to `additional-packages` and enabling `ws-butler-mode`. It seems to work seamlessly now. Even works when undoing changes, i.e. it keep the initial trailing space!

**Comment by nixmaniack** [comment]
I have been using `ws-butler` with spacemacs since quite some time. We should defintely have this! :+1:

**Comment by nixmaniack** [comment]
PR #3431 might be interesting for this case.
