### ISSUE TITLE
Web-mode auto complete is confusing

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#2350]
Auto complete in `web-mode`, when typing without prefix, only triggers html tag completion. Prefix `"` will let two letters after it trigger completion based on words from all buffers, but add a space and it goes back to html tag.

**Comment by louy2** [comment]
`company-web-html` backend also for some reason disabled `company-tern`. After `(pop company-backends)` returns `company-web-html` I was relieved to see `company-tern` working.

**Comment by louy2** [comment]
No, the problems is which comes first in `company-backends` shadows the other.

**Comment by louy2** [comment]
OK, grouping is the key. Still would like some advice on `company-web`.

**Comment by StreakyCobra** [comment]
As it is a pretty old issue, I ask :smile: : Is it still valid with current `develop` version of spacemacs?

**Comment by louy2** [comment]
It is not. Thanks for reminding me.
