### ISSUE TITLE
Major mode keybinds gone from Ruby

### ISSUE THREAD

**Issue by mkaito** [syl20bnr/spacemacs#2352]
I'm not entirely sure what happened. I was writing some ruby, and reading the docs for the Ruby layer. I added the `ruby-version-manager` setting to my `.spacemacs`, reloaded, and the keybinds were gone. So I removed the setting, reloaded, still gone. Restarted emacs, still gone. Reverted the spacemacs tree from github, still gone. Removed my spacemacs, still gone.

In a ruby buffer:

* `SPC m` is not defined.
* `,` seems to be bound to `(evil-repeat-find-char-reverse &optional COUNT)`.

I don't think I've left anything to try, but I'd welcome any hints.

**Comment by StreakyCobra** [comment]
Do you still have this bug? Also in case of problem like this, try to wipe the `~/.emacs.d` folder (be sure to backup everything needed in there), it may help :-)

**Comment by mkaito** [comment]
Nope, seems to have fixed itself at some point.
