### ISSUE TITLE
Mysterious symbol before heading in CONVENTIONS.org makes TOC link fail

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#2353]
Getting 'No match - create this as a new heading?' for all TOC. Opening an issue in case it is the problem of the conversion script or pandoc.

Related to #1568

**Comment by person808** [comment]
This is expected when in emacs. We can either use headers that work in emacs or github, not both. I think `SPC s l` is one way to navigate in emacs.

**Comment by louy2** [comment]
Oh wait... I used `toc-org-insert-toc` and still get this type of heading. Is that function customized?

**Comment by louy2** [comment]
OK that is not a org native function, but specifically for creating such links.
