### ISSUE TITLE
Clojure layer cider debugging evil key bindings

### ISSUE THREAD

**Issue by nbren12** [syl20bnr/spacemacs#2356]
I have been learning clojure using the wonderful spacemacs contrib layer, and just started exploring the debugging capabilities. One issue is that the evil-normal-state keybindings like `n`, `c`, etc conflict with the `cider--debug-mode` bindings. I am a bit of an emacs newb, but would it be possible to enable`evil-motion-state` or something whenever `cider--debug-mode` is present?

**Comment by hookercookerman** [comment]
yep would be great for us new to emacs how to get this working; I know its probably emac basics but if someone can show their magic and lead me to the magic that would be pretty dame cool; cos with evil on debug is on the edge of impossible;

**Comment by sooheon** [comment]
Just tried to use this, and either it is completely non-functional or I don't understand how it should work. Can anybody who actually has this working (@ppold?) chime in please?

**Comment by ppold** [comment]
I actually just flund out about that issue a few hours ago! I'll give it a check tomorrow if possible

**Comment by asyncsrc** [comment]
I'm not sure if it's worth mentioning, but i, as of about 5 minutes ago, realized the '\' key acts as "evil-execute-as-emacs-state" -- this allows you to press this key then one of the cider-debug keys (n, i, c, l, etc), and it seems to work well for stepping through debugged code and so forth.

For for instance, i'll split the buffers/windows into 1 repl window and 1 source code window.  On the function that I want to debug, I'll hit M-x (alt-x) to initiate helm then execute the "cider-debug-defun-at-point" command.  Within your source code, you'll see a box around the function that now has a breakpoint set.  You execute the function within the REPL, and you'll see the stepping options above the top of the function you were in when you executed the "cider-debug-defun-at-point" command that look like "*n*ext *c*ontinue *o*ut *l*ocals *i*nject *q*uit."  

At this point, i'll hit '\' and then 'n' to take a step through the method.  I'm at least somewhat happy about this as it makes the debugging usable.

**Comment by hookercookerman** [comment]
@asyncsrc perfect thanks;
