### ISSUE TITLE
Go layer fails loading because it can't find GOPATH on OSX

### ISSUE THREAD

**Issue by nyc** [syl20bnr/spacemacs#2358]
I get the warning

    (Spacemacs) Warning: GOPATH variable not found, go-oracle configuration skipped.

while loading a Go file in Spacemacs with the Go layer enabled. It's because the PATH is not being set, and while I can fix the issue by hardcoding `(setenv "GOPATH" <some_path_here>)` in the user initialization, I'd really rather not have to do that and would rather have Spacemacs or the Go layer pick up the variables from my shell environment. 

I know about the existence of the `exec-path-from-shell-copy-env` function, but I can only run them in the post-initialization configuration, at which point the Go layer has already failed to load go-oracle. Is there something I'm missing, or a way we can get this fixed? Perhaps the Go layer can call `exec-path-from-shell-copy-env` for GOPATH in its initialization?

**Comment by nyc** [comment]
Actually, I found a way to get around the fact that `exec-path-from-shell` isn't loaded until after the `init` function in `.spacemacs` by redefining the `exec-path-from-shell-variables` group in the `init` function.

```lisp
(defun dotspacemacs/init ()

  ...

  ;; Pick up shell variables.
  (setq exec-path-from-shell-variables '("PATH"
                                         "MANPATH"

                                         ;; Go path variables.
                                         "GOPATH"
                                         "GOROOT"
                                         "GOBIN"
                                         ))
  )

```

This solves my issue for now, but unless I'm missing something, this still seems like something the Go layer should do.

**Comment by jenanwise** [comment]
I made a pull request #1878 a while ago that should fix it.
