### ISSUE TITLE
inferior python process not launched

### ISSUE THREAD

**Issue by tboquet** [syl20bnr/spacemacs#2360]
Hello all,

Sorry to reopen this thread but I have a fresh install of emacs 24.5 and I run into a similar problems when using SPC m s i. No inferior python process is launched but I see the warning message no inferior python process running. I guess that the shortcut is working but the behaviour of the command run is not right. I have tried SPC : python-start-or-switch-repl but indeed, it led to the same result. When I use the same configuration on emacs 24.4 compiled from source, everything is working as expected.

**Comment by sooheon** [comment]
Was this closed because it was simply a 24.5 problem and unsupported? I'm having the same thing and wondering if you found a solution.

**Comment by tboquet** [comment]
Sorry I closed this issue because nobody was answering it :'(.
For me, the solution was to install emacs 24.5 and spacemacs first and then install the Anaconda distribution of Python.
When I compiled emacs 24.4 from source, I had issue with libpng15 (again because of Anaconda) and I managed to install libpng16 to resolve the errors.

**Comment by StreakyCobra** [comment]
I can't reproduce this bug. Does it still appears with the last version of spacemacs and packages updated? If no, this issue can be closed. If yes, can you include the output of `SPC h d s` ? :smile:

**Comment by tboquet** [comment]
I reinstalled emacs and spacemacs several times without bug so I close this issue :smile: .

**Comment by StreakyCobra** [comment]
:+1:
