### ISSUE TITLE
an issue installing Sml-mode

### ISSUE THREAD

**Issue by ahmadseleem** [syl20bnr/spacemacs#2361]
I was trying to install it as an extension...

**Comment by ahmadseleem** [comment]
The problem I found I had when trying to install SML-mode was the naming convention wasn't clear to me/

I added:
(setq ViMacs-packages
...
simpleclip
sml
...
)

To my private packages... and it didn't work without adding <name>-mode but worked for simpleclip.

Is it okay if I exclude -mode as it's name in melpa all the time or I should add "-mode" or "-theme" all the time.

**Comment by Devagamster** [comment]
There is an sml mode contrib layer in the develop branch which should just work with sml

**Comment by StreakyCobra** [comment]
As said, there is now a `sml` layer both on `master` and `develop` that should work out-of-the-box. so closing this one :smile: If you have still issue using this layer, feel free to open new issues!
