### ISSUE TITLE
Backtick autoclose bug in markdown layer

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#2363]
Backticks/backquotes aren't auto-closing properly in markdown mode.

Example: if you type 

    `foo`

you get 

    `foo``

instead of

    `foo`

Typing the second backtick doesn't skip over the auto-inserted closing backtick from the first backtick.

**Comment by x-ji** [comment]
Same here. It seems there should be code in there to deal with it
```
    (when (fboundp 'sp-local-pair)
      (sp-local-pair 'markdown-mode "`" nil :actions '(:rem autoskip))
      (sp-local-pair 'markdown-mode "'" nil :actions nil))
```
 but it is not working.

**Comment by x-ji** [comment]
Actually just commenting out that section makes both backtick and quote work normally. I'm not sure what was that introduced for but it seems to not work with the newest markdown packages anyways. I'll do a PR to try to change this.
