### ISSUE TITLE
Sourceforge is down

### ISSUE THREAD

**Issue by eusebe** [syl20bnr/spacemacs#2364]
Hi, 

I've just discovered spacemacs and would like to try it out on windows.
Unfortunatly, sourceforge is down, with no information on the "why" and the "when" (http://emacsbinw64.sourceforge.net/)

Is there another way to install spacemacs on windows ?

Thank you very much.
Best, 
David

**Comment by robbyoconnor** [comment]
https://chocolatey.org/packages/Emacs

**Comment by rgaloppini** [comment]
Project Web actually is still to be restored, but you can access project's files at http://sourceforge.net/projects/emacsbinw64/

**Comment by Devagamster** [comment]
you could also try installing the official emacs for windows, it just won't have image support but other than that runs fine.

**Comment by syl20bnr** [comment]
Since Sourceforge seems to be restored I close this ticket.
