### ISSUE TITLE
Can't use evil-escape keybind in Deft mode

### ISSUE THREAD

**Issue by xHN35RQ** [syl20bnr/spacemacs#2366]
I have this issue using stock spacemacs and emacs-snapshot on Ubuntu 14.04. Pushing `f` in Deft mode does nothing.

Other reports of this problem here: https://github.com/syl20bnr/spacemacs/pull/1205#issuecomment-102385826

**Comment by Devagamster** [comment]
I have been meaning to try and fix this but haven't gotten around to it unfortunately

**Comment by StreakyCobra** [comment]
Can anyone using deft try to reproduce this issue? It's pretty old and in the cited PR it seems to have been fixed (or not :stuck_out_tongue: )

**Comment by ageorgo** [comment]
Actually now pressing `f` causes double f-s being entered.

**Comment by xHN35RQ** [comment]
Sorry I'm not using emacs anymore. Is there any way to transfer this issue to someone more relevant? Thanks.

**Comment by StreakyCobra** [comment]
@xHN35RQ There is probably no way to transfer it. But keep this issue open and click on `Unsuscribe` from this issue on the right sidebar if you want. We will take care to close it once resolved :relaxed:

**Comment by xHN35RQ** [comment]
Ok thanks!

**Comment by ccmtaylor** [comment]
I can confirm @ageorgo's issue: I also get duplicated `f`'s whenever I type `f` in deft.

**Comment by ccmtaylor** [comment]
fwiw, I commented out the line 
```lisp
(`deft-mode (call-interactively 'deft-filter-increment))
```
 in `~/.emacs.d/elpa/evil-escape-20150926.2152/evil-escape.el`

and that fixed the problem.

**Comment by xHN35RQ** [comment]
closing because this was fixed upstream: https://github.com/syl20bnr/evil-escape/pull/57#issuecomment-196022005
