### ISSUE TITLE
magit-status is not shown after finishing a commit

### ISSUE THREAD

**Issue by env0der** [syl20bnr/spacemacs#2369]
After upgrade to 0.103.2 (and magit 2.1 within it):

1. ```SPC g s```
2. ```cc```
3. Write commit message
4. ```C-c C-c``` to finish the commit
5. Instead of seeing magit status buffer and doing a push straight away (as it was with magit 1.4) I'm back to my buffer with code

Is it a Spacemacs issue or Magit issue?

**Comment by env0der** [comment]
I've quickly fixed it in my configuration: https://github.com/env0der/dotfiles/commit/d699ad7bb20e7b1b40e718c829c5d7459fb14940

Maybe something similar should be done in ```git``` contrib layer as well?

**Comment by justbur** [comment]
Can't reproduce this with #3578

**Comment by StreakyCobra** [comment]
Indeed `evil-magit` doesn't seems to have this (pretty old) issue anymore.

**Comment by env0der** [comment]
Yes, it works correctly now without the workaround.
