### ISSUE TITLE
Spacemacs finds orphan packages every time

### ISSUE THREAD

**Issue by Pradeek** [syl20bnr/spacemacs#237]
I updated spacemacs yesterday after a while and now I'm noticing that 6 packages are being removed every time I start Emacs. This is the welcome message.

```
Loading.........................................................OK!
Found 6 orphan package(s) to delete...
--> deleting gh... [6/6]
Ready!
[217 packages loaded in 5.759s]
```

This is not causing any problems, but wondering why this is happening every time.

**Comment by Ornataweaver** [comment]
https://emacs.stackexchange.com/questions/30843/spacemacs-themes-auto-deleted

**Comment by Ornataweaver** [comment]
It says:

"
Don't install packages with package install. See the FAQ here: https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org#why-are-packages-installed-with-package-install-automatically-deleted-by-spacemacs-when-it-boots

Instead, install packages with dotspacemacs-additional-packages, or create a layer, or set the variable dotspacemacs-install-packages to used-but-keep-unused which will prevent Spacemacs from removing the packages you installed manually.

As for themes, just install the themes-megapack layer to get a bunch of different themes. The page for it is here: https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bthemes/themes-megapack
"
