### ISSUE TITLE
spinner is unavailable

### ISSUE THREAD

**Issue by doubleagent** [syl20bnr/spacemacs#2371]
just started with 0.103.2

http://imgur.com/3lw0oWw

**Comment by cpaulik** [comment]
Are you sure that you have a connection to http://elpa.gnu.org/packages/?

**Comment by doubleagent** [comment]
Your link works, and Emacs appears to.  http://imgur.com/1GJ7ngY

**Comment by doubleagent** [comment]
Switching the connection from https://elpa.gnu.org/packages to http://elpa.gnu.org/packages in core/core-configuration-layer.el appears to have resolved it.  I will leave this ticket open for now.  Maybe elpa.gnu.org is working on their ssl connection?

**Comment by louy2** [comment]
But browser visit https is fine.

**Comment by louy2** [comment]
I suggest all affected people @doubleagent @WildBamboo check if your emacs has HTTPS capability by `M-:` then:
```
(gnutls-available-p)
```

If it is actually about HTTPS, we should document this in FAQ.

**Comment by louy2** [comment]
Reference about HTTPS in Emacs: https://www.gnu.org/software/emacs/manual/html_mono/emacs-gnutls.html

**Comment by WildBamboo** [comment]
(gnutls-available-p) returns nil for me. Seems like I need to place a separate DLL in my emacs folder. Bit surprised that this isn't included in the official Emacs release for Windows.

**Comment by WildBamboo** [comment]
Dropped the GnuTLS DLLs in my emacs\bin folder alongside emacs.exe, restarted Emacs and (gnutls-available-p) now returns t.

**Comment by doubleagent** [comment]
Performed the same procedure as @WildBamboo .  Many thanks for the step-by-step details.  Experienced the same result.  An entry in the FAQ about this would be appreciated by Spacemacs Windows users, I'm sure.

**Comment by person808** [comment]
@doubleagent I would leave this open until this issue is fixed with the docs.

**Comment by doubleagent** [comment]
No problem.
