### ISSUE TITLE
ESS smart equals dissabled by default

### ISSUE THREAD

**Issue by izahn** [syl20bnr/spacemacs#2373]
I think it would be best to disable ESS "smart" equals by default, as it really isn't smart enough and gets in the way. Furthermore many people prefer `=` for assignment, and smart equals makes that hard. I know it can be turned off, but IMO this is surprising behavior and should be opt-in. If people are open to this I'll be happy to submit a pull request.

**Comment by sooheon** [comment]
I was the one who put in the ess-smart-equals package, and iirc it was simply to replace another worse default (ess-smart-underscore or something). I agree that a opt-in variable would be nicer.
