### ISSUE TITLE
running spacemacs as daemon, use emacsclient to edit a python file, the client was blocked

### ISSUE THREAD

**Issue by zackshen** [syl20bnr/spacemacs#2375]
when i running spacemacs as daemon server , use emacsclient to edit a python file, then the client was blocked. error message as below:
Blocking call to accept-process-output with quit inhibited!!

my python mode is anaconda-mode. all packages were installed. pip install  jedi==0.8.1 json-rpc==1.8.1 service_factory==0.1.2.

but when i run emacs without daemon, it's correctly running.

**Comment by louy2** [comment]
Have you put `(server-start)` in your `dotspacemacs/config`?

**Comment by zackshen** [comment]
@louy2  i run as emacs --daemon, run client as emacsclient -t

**Comment by louy2** [comment]
@zackshen Found it! Hopefully you can just update the package to get the fix. https://github.com/proofit404/anaconda-mode/issues/54

**Comment by zackshen** [comment]
@louy2 my package version is anaconda-mode-20150626.441

**Comment by louy2** [comment]
Maybe you need to follow the instructions there to manually install dependencies. They are `jedi`, `json-rpc`, `service_factory`.

**Comment by zackshen** [comment]
@louy2 i have manually installed the dependencies already.

**Comment by louy2** [comment]
@zackshen Oh my bad. I don't know any more though. Good luck from here.

**Comment by zackshen** [comment]
@louy2 it's my fault, i started emacsd with proxychains4, the anaconda_mode started with 127.0.0.1 default ,
