### ISSUE TITLE
save buffer on focus lost

### ISSUE THREAD

**Issue by murtaza52** [syl20bnr/spacemacs#2376]
Hi,

One feature I sorely miss from emacs prelude is the ability to save buffers whenever focus changes to another buffer or window. This is very valuable as the file is automatically saved, and I dont have to manually save them.

Is there such a feature in sapcemacs ?

Thanks,
Murtaza

**Comment by sooheon** [comment]
No, afaik, but you can add a naive version yourself very easily:
```
(defun sooheon--save-all ()
  (interactive)
  (save-some-buffers t))
;; Auto-save on focus out
(add-hook 'focus-out-hook 'sooheon--save-all)
```

**Comment by EricCrosson** [comment]
I have very similar code
```lisp
  (add-hook 'focus-out-hook
            (defun save-current-buffer-if-needed ()
              (interactive)
              (when (and (buffer-file-name) (buffer-modified-p))
                (save-buffer))))
```
This only saves the current buffer, if it belongs to a file and has changes that need to be saved. 
Is this issue closed?

**Comment by sooheon** [comment]
Nice improvement, will be using it. Thanks.

**Comment by Profpatsch** [comment]
I looked at my config and it’s just one line there:

```elisp
  (add-hook 'focus-out-hook (lambda () (save-some-buffers t)))
```

Maybe it makes sense to include [the function](https://github.com/bbatsov/prelude/blob/d073402257ebc8cfb3c75443177152f354cd2415/core/prelude-editor.el#L153) from Emacs Prelude, too.

**Comment by StreakyCobra** [comment]
The main question of this issue has been answered. If someone thinks it's used widely enough to be included in Spacemacs, feel free to open a PR with this change, it will be better discussed there :smile: Closing this issue in the meantime

**Comment by martin-liu** [comment]
Hi guys, I have the same requirement and I don't think this question is answered.

The documentation of `focus-out-hook` says 
>Normal hook run when a frame loses input focus.

It's not when switch buffer/window.

I found a solution here http://batsov.com/articles/2012/03/08/emacs-tip-number-5-save-buffers-automatically-on-buffer-or-window-switch/

Code like below:
```
(defadvice switch-to-buffer (before save-buffer-now activate)
  (when buffer-file-name (save-buffer)))
(defadvice other-window (before other-window-now activate)
  (when buffer-file-name (save-buffer)))
```

It works for me. So I paste it here.

**Comment by steshaw** [comment]
Did a pull request ever get raise for this?

In Emacs, I use use:

    (ensure-packages-installed 'focus-autosave-mode)
    (focus-autosave-mode)

I've only just downloaded Spacemacs today, but it seems that I may expect to have a configuration variable in my ~/.spacemacs file:

    dotspacemacs-save-all-buffers-on-lost-focus nil

which I could toggle to `t`. It arguably should default to `t`.

**Comment by xged** [comment]
@martin-liu It auto-saves after every paste as well :(

**Comment by adius** [comment]
Pull request for this highly appreciated! 😅
