### ISSUE TITLE
The state of Spacemacs

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#2378]
I know I am being silly asking this after only two weeks, but it seems like ages in the pace Spacemacs was being developed.  Has anyone heard anything?

**Comment by louy2** [comment]
Nope. It is indeed strange compared to the former daily update pace. I was always caught off a bit by the flood of commits if I did not check for two days. Now I kinda miss that.

Anyway, if you like whatever function you like, add that repo as remote and merge it in yourself would be what you can do in the status quo. Or do we need a better platform for layer distribution?

**Comment by zilongshanren** [comment]
I also wondering about this, what was happening during the pass two weeks?

**Comment by person808** [comment]
Only @syl20bnr knows :)

**Comment by TheBB** [comment]
I know @syl20bnr said he prefers to be the bottleneck but I don't think he had this in mind. An organization with a handful of trusted mergers would be handy.

**Comment by justbur** [comment]
It would make a lot of sense to me to add support for remote layers in .spacemacs. That way they could progress in another repo and be submitted to spacemacs after they are more complete. 

The idea would be to be able to list justbur/mylayer in the layer list. Of course you could clone the layer into your private folder, but this would automate the process.

**Comment by justbur** [comment]
Could also use the wiki to make people aware of these unofficial layers

**Comment by stormpat** [comment]
Maybe @syl20bnr is on a summer vacation? He has def earned it!

**Comment by trishume** [comment]
I think a family summer vacation really is the most plausible scenario at this point. He does have a wife and kid and it is beautiful outside in Canada this time of year.

If he isn't back in a couple more weeks then that scenario becomes less plausible and you can ping me back in here and I'll check to see if I have commit access and not just issue tagging access (I have no idea where to see in Github other than actually trying). :stuck_out_tongue_winking_eye: 

I'm on a spacemacs-cation myself but of a different kind. I'm working full time this summer so I don't have much time for open source, and I'm also trying out Atom and Sublime Text to see what features Spacemacs is missing.

**Comment by jb55** [comment]
Seconded what @TheBB said. People tend to contribute more when they have commit access. Halting development over a single vacation is a bit silly for an open source project.

**Comment by cpaulik** [comment]
Not to stalk @syl20bnr but the last time he was active on twitter was the 15th of July. So only 1 week back. I also think that summer vacation is the most probable scenario. I guess he didn't announce it because he did not think we would panic so fast :smile:

**Comment by Devagamster** [comment]
I'm very glad that there is a group in the case that @syl20bnr goes of the grid. The show must go on!!!

**Comment by syl20bnr** [comment]
Sorry for the late reply, no need to panic I'm indeed in vacation, I
thought that I would have some spare time to allocate to Spacemacs but it
is not the case.

Good news is that I'm reaching the end of my vacation, thank you for your
patience!

Le mercredi 22 juillet 2015, Christoph Paulik <notifications@github.com> a
écrit :

> Not to stalk @syl20bnr <https://github.com/syl20bnr> but the last time he
> was active on twitter was the 15th of July. So only 1 week back. I also
> think that summer vacation is the most probable scenario. I guess he didn't
> announce it because he did not think we would panic so fast [image:
> :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/2378#issuecomment-123812467>
> .
>


-- 
-syl20bnr-

**Comment by robbyoconnor** [comment]
@syl20bnr -- that's okay -- we're still churning out PRs for you to review :)

**Comment by robbyoconnor** [comment]
Also folks: keep in mind that we DO NOT want @syl20bnr to burn out!

**Comment by ralesi** [comment]
Even if we are only going to have one primary commiter, is there any value in the group going through the existing commits to test their effectiveness and make sure that they're mergable? Sort of a ranking system I guess we can use +1?

**Comment by robbyoconnor** [comment]
@ralesi -- some of us do go through -- and at least :+1:  on some commits -- I got yelled at for being strict with the one commit rule but I did spellcheck one PR -- if I see a good PR -- I will :+1: it...so as a community we do occasionally do code review if we really care about the PR :smile_cat:

**Comment by ralesi** [comment]
No,  I have seen you on a few of mine given advice,  thanks.   I guess I just need to try doing that as well.   There are so many domains and languages Spacemacs works with,  I find it hard to not just block out the changes that wont affect me.

**Comment by robbyoconnor** [comment]
We do that now :smile_cat:

**Comment by ralesi** [comment]
He's back!
