### ISSUE TITLE
Clean install of 0.103.2 on Windows; packages unavailable

### ISSUE THREAD

**Issue by WildBamboo** [syl20bnr/spacemacs#2379]
I was trying to update from version 0.102.x but clicking the update link on the spacemacs page produced and error along the lines of 'Invalid version nil'. Rather than attempt to sort this out, it seemed easier for me to simply delete my .emacs.d and .spacemacs and do a fresh install, since I can easily recreate the .spacemacs file.

So I did this. However, some packages are not found:

```
--> installing let-alist... [2/5]
Package let-alist is unavailable. Is the package name misspelled?
--> installing spinner... [3/5]
Package spinner is unavailable. Is the package name misspelled?
--> installing (spacemacs):adaptive-wrap... [4/5]
Package adaptive-wrap is unavailable. Is the package name misspelled?
--> installing (spacemacs):paradox... [5/5]An error occurred while installing paradox (error: (error Package `let-alist-1.0.3' is unavailable))
```

Ignore the [x/5] - this log is from subsequent reloads. All the other packages did install ok (80-something from memory).

I've taken ownership of the .emacs.d folder, and all files and folders under that, and reloaded again. No change.

**Comment by bmag** [comment]
Could it be related to #2371 ?

**Comment by EricCrosson** [comment]
I'd wager that it is. I installed spacemacs on a friend's Windows computer this weekend and received a similar list of 'misspelled?' packages.

**Comment by WildBamboo** [comment]
Sorry for the duplicate, I didn't notice #2371. I've worked around it for now as described in that issue by using http.
