### ISSUE TITLE
Smartparens-strict-mode not working

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#238]
`smartparens-strict-mode` does not work as expected.
1. In the scratch buffer, M-x `smartparens-strict-mode`
2. Typing `(` will result in `(|)`
3. Moving out of parens to `()|` and then backspacing while in insert mode should result in `(|)`, but instead results in `(|`. 

`smartparens-strict-mode` works fine with emacs -q. It also works in `emacs-lisp-mode`, strangely, but not for any others (`fundamental`, `clojure`...).

**Comment by GEverding** [comment]
I just installed spacemacs today and the issue seems to be back. Can some confirm?

**Comment by sooheon** [comment]
@GEverding Is `dotspacemacs-smartparens-strict-mode t` in your .spacemacs?

**Comment by GEverding** [comment]
Yes I do. Here is my spacemacs config https://gist.github.com/GEverding/969d2be11696178d1fa4

**Comment by logaan** [comment]
This still appears to be an issue, at least for Clojure files.

**Comment by rasensio1** [comment]
Still an issue for Clojure files - fresh install.

**Comment by kommen** [comment]
@rasensio1 I don't have the problem with Clojure in the `develop` branch. You might want to try that. 

Probably unrelated, but there's also a new "Structuraly safe editing" option for lisps in the develop branch: https://github.com/syl20bnr/spacemacs/blob/2cb98447afa3230d579d349b42e03c23017f43f5/layers/%2Blang/clojure/README.org#structuraly-safe-editing
