### ISSUE TITLE
the dot repeat in spacemacs take effect only once

### ISSUE THREAD

**Issue by zackshen** [syl20bnr/spacemacs#2382]

**Comment by EricCrosson** [comment]
Can you provide a description? Steps to reproduce?

Traditionally, a bug report consists of the following:
- the action you did
- what you expected to happen
- what happened instead

**Comment by zackshen** [comment]
@EricCrosson in vim , press the dot key will repeat the previous action, but in spacemacs no effect, it displays the message " . is undefined".
for example: in vim i copy a word, then press 'p' key, then press '.' key, it will repeat press 'p' key action.

**Comment by EricCrosson** [comment]
I use the dot command every day, in my evil-normal-state `.` is bound to `evil-repeat`. Can you start with the most basic spacemacs install possible and see if the problem persists?

**Comment by robbyoconnor** [comment]
I'd suggest trying with both `master` and `develop` branch -- the `develop` branch has fixes long before they appear in `master`

**Comment by izahn** [comment]
It works as expected on the master branch here.

**Comment by zackshen** [comment]
@robbyoconnor @izahn  thanks

**Comment by spattersongt** [comment]
`Vjjj>.`
Doesn't work. It says ". is undefined"

However, 

`Vjjjyp....` works

**Comment by TheBB** [comment]
@spattersongt https://github.com/syl20bnr/spacemacs/issues/2382

**Comment by TheBB** [comment]
@spattersongt https://github.com/syl20bnr/spacemacs/issues/5273
