### ISSUE TITLE
Ag is not available

### ISSUE THREAD

**Issue by jcswart** [syl20bnr/spacemacs#2383]
I'm running spacemacs on OS X, with `fish shell v2.1.2` and `Ag v0.30.0` in `/usr/local/bin/ag` and running `<C-c> p s s` gives the error "Ag is not available". 

`which ag` => `/usr/local/bin/ag`

Switching to Bash and running `which ag` => `/usr/local/bin/ag`

Is there something else I need to configure?

**Comment by cpaulik** [comment]
What does `M-: (executable-find "ag")` give you?

**Comment by TheBB** [comment]
I actually get the same error. I definitely have ag (all the regular Spacemacs keybindings can find it) and I haven't run into this problem just because I never launch `C-c p s s`. The `executable-find` invocation finds ag just fine.

**Comment by cpaulik** [comment]
Yes you are right. I did not notice the unusual keybinding. It does also not work for me. 

Looking in the `projectile` source file [here](https://github.com/bbatsov/projectile/blob/master/projectile.el#L1820) a function `ag-regexp` is needed. I have no idea where this should be defined. 

@jcswart In the meantime you can try `SPC s p` which should search with `ag` if you have it installed. Or also `SPC s a p` which chooses `ag` explicitly.

**Comment by TheBB** [comment]
You beat me to it by a minute. The `ag-regexp` function is defined in the `ag` package, which is not part of the Spacemacs install. You can install it additionally if you like (I have, now). The spacemacs search functions invoke helm sources from packages like `helm-ag`, which it appears doesn't need the `ag` package at all.

**Comment by robbyoconnor** [comment]
is there a PR to fix this...or should I make one?

**Comment by jcswart** [comment]
Awesome, thanks for the input.  I'm using this with the suggested hotkeys and avoiding `C-c p s s` which is how I used to use `ag` via Prelude emacs.

**Comment by cpaulik** [comment]
@robbyoconnor I think there is no need to fix this since the Spacemacs keybindings work without the `ag` package

**Comment by robbyoconnor** [comment]
Ah :)
