### ISSUE TITLE
Highlight remote buffer name in mode line

### ISSUE THREAD

**Issue by izahn** [syl20bnr/spacemacs#2386]
I'm a long-time emacs user, using spacemacs for only a couple of days. So far I miss very little from my old emacs configuration, and am really impressed with spacemacs.

One small thing I do miss is highlighting remote buffers in the mode-line. This way if you are visiting a remote file with the same name as a local file you are also visiting you never get confused about which is which. 

I tried adding the relevant bit from my old config so I could submit this as a pull request, but I couldn't figure out where/how exactly the mode line is configured in spacemacs. The relevant bit from my config are below. The important bits are defining the format string (`(defconst my-mode-line-buffer-identification ...`) and adding `(powerline-raw my-mode-line-buffer-identification nil 'l)` to the `(lhs (list ...` in `mode-line-format`.

If someone can point me toward the entry point for modifying the mode-line in spacemacs I'll be happy to submit a PR, or feel free to grab anything useful from the code below if you want to implement this in spacemacs.

Thanks.

```elisp
;; face for remote files in modeline
(defface my-mode-line-attention
'((t (:foreground "magenta" :weight bold)))
 "face for calling attention to modeline")

;; highlight hostname if on remote
(defconst my-mode-line-buffer-identification
  '(:eval
    (list
     (propertize
      (if (file-remote-p default-directory 'host)
          (progn
      (let ((host-name
             (or (file-remote-p default-directory 'host)
                 (system-name))))
        (if (string-match "^[^0-9][^.]*\\(\\..*\\)" host-name)
            (substring host-name 0 (match-beginning 1))
          host-name)))
        "")
      'face
      (if (file-remote-p default-directory 'host)
          'my-mode-line-attention
        'mode-line-buffer-id))
   (propertize ": %b"
               'face
                 (if (file-remote-p default-directory 'host)
                     'my-mode-line-attention
                   'mode-line-buffer-id)))))

;; powerline theme using above info about remote hosts.
(defun powerline-my-theme ()
  "Setup the default mode-line."
  (interactive)
  (setq-default mode-line-format
                '("%e"
                  (:eval
                   (let* ((active (powerline-selected-window-active))
                          (mode-line (if active 'mode-line 'mode-line-inactive))
                          (face1 (if active 'powerline-active1 'powerline-inactive1))
                          (face2 (if active 'powerline-active2 'powerline-inactive2))
                          (separator-left (intern (format "powerline-%s-%s"
                                                          powerline-default-separator
                                                          (car powerline-default-separator-dir))))
                          (separator-right (intern (format "powerline-%s-%s"
                                                           powerline-default-separator
                                                           (cdr powerline-default-separator-dir))))
                          (lhs (list (powerline-raw "%*" nil 'l)
                                     (powerline-buffer-size nil 'l)
                                     (powerline-raw mode-line-mule-info nil 'l)
                                     (powerline-raw mode-line-remote nil 'l)
                                     (powerline-raw my-mode-line-buffer-identification nil 'l)
                                     (when (and (boundp 'which-func-mode) which-func-mode)
                                       (powerline-raw which-func-format nil 'l))
                                     (powerline-raw " ")
                                     (funcall separator-left mode-line face1)
                                     (when (boundp 'erc-modified-channels-object)
                                       (powerline-raw erc-modified-channels-object face1 'l))
                                     (powerline-major-mode face1 'l)
                                     (powerline-process face1)
                                     (powerline-minor-modes face1 'l)
                                     (powerline-narrow face1 'l)
                                     (powerline-raw " " face1)
                                     (funcall separator-left face1 face2)
                                     (powerline-vc face2 'r)))
                          (rhs (list (powerline-raw global-mode-string face2 'r)
                                     (funcall separator-right face2 face1)
                                     (powerline-raw "%4l" face1 'l)
                                     (powerline-raw ":" face1 'l)
                                     (powerline-raw "%3c" face1 'r)
                                     (funcall separator-right face1 mode-line)
                                     (powerline-raw " ")
                                     (powerline-raw "%6p" nil 'r)
                                     (powerline-hud face2 face1))))
                     (concat (powerline-render lhs)
                             (powerline-fill face2 (powerline-width rhs))
                             (powerline-render rhs)))))))

(powerline-my-theme)
```

**Comment by TheBB** [comment]
The modeline is defined by `spacemacs/mode-line-prepare-left` [here](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L2657-2757) and a corresponding function for the right side [here](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L2779-2845). There's a PR open at #2252 to replaces these monoliths with simper definitions, e.g. something like [this](https://github.com/TheBB/spacemacs/blob/mode-line/spacemacs/packages.el#L2633-2667). Making changes like what you're suggesting would be a lot easier after that is merged, in whatever form it ends up in eventually.

Doesn't uniquify already differentiate the buffer names for you, though?

**Comment by izahn** [comment]
Thank you @TheBB perhaps I'll wait to see what happens with #2252. 

uniquify does give the buffers unique names, but what this adds is a visual indicator that the file is remote, and an explicit indicator of which remote host the file is on. See screenshots below. I admit it is a subtle improvement, but I find it really helpful.

Current spacemacs:
![spacemacs_local_remote](https://cloud.githubusercontent.com/assets/321235/8862088/17052978-315c-11e5-8bf7-ba0025dcefc1.png)

My mode-line config:
![emacs_local_remote](https://cloud.githubusercontent.com/assets/321235/8862166/95fb17ce-315c-11e5-8e96-e47390e9cb91.png)

**Comment by TheBB** [comment]
Yeah, I agree, it's a good idea to show this.

**Comment by izahn** [comment]
I'm still planning to wait and see what happens with #2252, but for now I've hacked this in to the develop branch; https://github.com/izahn/spacemacs/commit/2658a280a29855847ccff17a622d1019901fa915.

**Comment by izahn** [comment]
The implementation of this in develop is fantastic, thanks @TheBB! Closing since this now works exactly as I'd hoped.
