### ISSUE TITLE
"Show snippets in auto-completion popup" has no effect

### ISSUE THREAD

**Issue by worldsayshi** [syl20bnr/spacemacs#2387]
At least for me the described configuration seems to have no effect. Also, the variable described by [the documentation](https://github.com/syl20bnr/spacemacs/tree/master/contrib/auto-completion#show-snippets-in-auto-completion-popup) `auto-completion-enable-snippets-in-popup` is defined in `contrib/auto-completion` but is read in `core`. Is this an incomplete refactorization? Will this cause the variable to be defined after use? Not sure how elisp deals with this.

I have only tried the master branch.

**Comment by person808** [comment]
Auto completion macros are all in core, so I put the functions for that variable in the same place. I think you would have to ask @syl20bnr why they are located there. As for why it has no effect, I have no idea. It is a little bit unreliable, though it works for me perfectly.

**Comment by person808** [comment]
This should probably be documented because it doesn't always work.

**Comment by beardedprojamz** [comment]
Is this backend (auto-complete vs company) dependent perhaps? I don't see it working at all for me - using latest develop.

**Comment by person808** [comment]
Only works for company which is what spacemacs uses in all of the layers

**Comment by beardedprojamz** [comment]
Okay, so unless I was monkeying with the backend, it should work by default?

**Comment by person808** [comment]
It should. What filetype are you trying it in?

**Comment by beardedprojamz** [comment]
A python file - `utf8` was the example I was trying, but it wasn't showing up in the auto complete window.

**Comment by person808** [comment]
Could you post the output of `SPC h d v company-backends-python-mode`? Just to check nothing funky happened there.

**Comment by beardedprojamz** [comment]
```
company-backends-python-mode is a variable defined in `config.el'.
Its value is (company-anaconda
 (company-anaconda :with company-yasnippet)
 (company-anaconda :with company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev :with company-yasnippet))


Documentation:
Company backend list for python-mode
```

**Comment by person808** [comment]
I just checked and its broken for me in python too :p

The correct value should be this:
```
((company-anaconda :with company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev :with company-yasnippet))
```

You can use this for now: `(setq company-backends-python-mode '((company-anaconda
 company-dabbrev-code company-gtags company-etags company-keywords
 company-files company-dabbrev)))` in your `dotspacemacs/config`

Seems like #2323 could be related

**Comment by beardedprojamz** [comment]
The first block worked like a charm in the setq - the second one you mentioned to add in my `dotspacemacs/config` didn't fix it up.

So:

```
  ;; Fix Python Company Mode
  (setq company-backends-python-mode
        '((company-anaconda :with company-yasnippet)
          (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
          (company-files :with company-yasnippet)
          (company-dabbrev :with company-yasnippet)))
```

**Comment by AngelTerrones** [comment]
I have the same problem using the C/C++ layer, using the develop branch.

company-backends-c-mode-common:

```
company-backends-c-mode-common is a variable defined in `config.el'.
Its value is (company-c-headers company-clang
                   (company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
                   (company-files :with company-yasnippet)
                   (company-dabbrev :with company-yasnippet))
```

BTW, using `company`.

**Comment by YulongNiu** [comment]
Same problem in the C/C++ layer with the stable version (0.103.6).

**Comment by person808** [comment]
Finally figured this our #2993

**Comment by hem1t** [comment]
@person808 This is not working for typescript either
here's the output you asked @ deybhayden for ( but for typescript )
```
company-backends-typescript-tsx-mode’s value is
((company-tide . #1=(:with company-yasnippet))
 (company-semantic company-dabbrev-code company-gtags company-etags company-keywords . #1#)
 (company-files . #1#)
 (company-dabbrev . #1#))

Company backend list for typescript-tsx-mode.
```

**Comment by hem1t** [comment]
@person808 Ok, weird it started working for new files, so I deleted the `App.tsx` created a new one and now it works there as well.
