### ISSUE TITLE
spacemacs/ace-buffer-links: Symbol's function definition is void: ali-generic

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#2389]
I have updated spacemacs to the latest develop branch and in the scratch buffer, press `o` will issue this error.

**Comment by louy2** [comment]
Totally fine here. Any `*Messages*`?

**Comment by zilongshanren** [comment]
@louy2

```
spacemacs/ace-buffer-links: Symbol's function definition is void: ali-generic
```

**Comment by louy2** [comment]
Strange…what is your `o` binding to?

**Comment by axyz** [comment]
I can confirm the bug 

```
spacemacs/ace-buffer-links: Symbol's function definition is void: ali-generic
```

when pressing `o` in the home screen

**Comment by swaroopch** [comment]
+1, can confirm - https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L157

**Comment by TheBB** [comment]
Indeed, `ali-generic` was removed from `ace-link` [here](https://github.com/abo-abo/ace-link/commit/5701fea0788943a2b6c83c5e6b5727c2520313fd#diff-b52556c07bf3f3da75f9e7a0d43d119d).

**Comment by louy2** [comment]
OK, can confirm in home screen.

**Comment by zilongshanren** [comment]
fixed in the latest develop version.

**Comment by hugows** [comment]
This happened to me today. Windows, Emacs 25, Git clone recursive like the Github page says. Press o on the first screen.
