### ISSUE TITLE
haskell layer behaves badly if ghc-mod is not available

### ISSUE THREAD

**Issue by dbbnrl** [syl20bnr/spacemacs#2397]
(Ubuntu, Spacemacs 0.103.2, Emacs 25.0.50.1)

## To reproduce:

 - Rename or otherwise hide the ghc-mod executable so Emacs and haskell-mode can't find it.

 - Open a .hs file.

 - Open *another* .hs file.  (This seems to help with reproduceability).

 - Hit the space bar and wait.

## Expected results:

Basic editing and spacemacs infrastructure such as evil-leader should work.  Compiler-interaction features such as live syntax checking, error reporting, type queries may not work.  In regard to my example scenario, hitting space should pop up the key guide.

## Observed result:

After a longish pause, an empty *popwin-dummy* pane will appear.  Briefly, it's possible to see an error at the bottom regarding ghci.  Hitting additional keys to complete a sequence may or may not work (seems to depend on the timing).

## Notes

I'm not suggesting that the key guide functionality is the only thing affected by this problem, it's just easy to reproduce and document.

I understand that much of the functionality of haskell-mode depends on ghc-mod.  I think it's fine that it doesn't work in every respect in this scenario.  But this is not a graceful failure.  As an Emacs newbie, if I get into a state where the leader key no longer responds, I don't know how to recover other than by killing Emacs.

After much experimentation, I discovered that if I'm careful to hit the keys quickly, I can usually issue leader commands such as `SPC b d` to recover.  Any amount of delay causes a brief lockup.  Even if recovery is possible by closing the .hs file, it sure would be nice to be able to at least edit Haskell code without a functioning ghc-mod.

**Comment by bgamari** [comment]
I have also been bitten pretty badly by this.

**Comment by PierreR** [comment]
:+1:

**Comment by jb55** [comment]
So this is what was happening! I spent all last night trying to figure out why things were randomly freezing on my nixos box when jumping between compile errors, which I never experienced before. I was getting random errors like `ghc-check-syntax: ghc process may have hung or exited with an error` Now that I think about it I don't think I had ghc-mod in my shell at the time.

**Comment by martinmr** [comment]
I have a similar problem. I have ghc-mod installed and it works when I type stuff but when I save open multiple files and try to save one of them emacs freezes until the `ghc process may have hung` message appears. Hitting C-g unfreezes emacs.

**Comment by k0001** [comment]
I'm affected by this issue too. I found this patch which seems to solve the problem (it works for me): https://github.com/michelk/spacemacs/commit/0799246a378816af3c1d3005497da4737638de7a#diff-135c3ed8b45c43701986c234e3e2ce27

I think `nil` is a saner default for `haskell-enable-ghc-mod-support`, though.

**Comment by k0001** [comment]
Looks like that was merged already: https://github.com/syl20bnr/spacemacs/pull/2035

**Comment by dbbnrl** [comment]
That patch is great for the scenario where you don't *want* to use ghc-mod (or you know you can't because it's currently broken).  It may be a good enough fix to close this issue, but.... it really would be nice if Spacemacs behaved sanely when you've got your path set up wrong and ghc-mod can't be found, or ghc-mod is misbehaving, etc.
