### ISSUE TITLE
set: Invalid function: (quote purescript-font-lock-keywords)

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#2402]
I'm using 0.103.2, here are my versions of purescript-mode and psci:

psci-20150328.1201
purescript-mode-20150316.1828

I visited `~/.emacs.d/elpa/psci-20150328.1201/psci.el` and did `M-x eval-buffer` and there were no errors. I'm guessing the loading isn't working correctly somewhere, but I'm very new to elisp and I'm not sure how to debug further.

**Comment by louy2** [comment]
`purescript-font-lock-keywords` obviously should be a variable, not a function. Grep this variable in your .emacs.d to see if anywhere wrongly referenced it as a function.

**Comment by TheBB** [comment]
Closing this since there appears to be no action. If it's still a problem please reopen or report upstream.
