### ISSUE TITLE
Update elpa packages returns error 

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2404]
Clicking `[Update]` in the spacemacs buffer causes this: 
```
Importing package-keyring.gpg...done
Contacting host: melpa.org:80 [2 times]
Contacting host: orgmode.org:80
Contacting host: elpa.gnu.org:443 [2 times]
version-to-list: Invalid version string: 'nil'
```

**Comment by syl20bnr** [comment]
Great ! This is a known bug which I struggle to replicate, can you provide the list of updated packages that should be in `~/.emacs.d/.cache/.rollback/<last_date>/rollback-info`.

**Comment by syl20bnr** [comment]
When I say `<last_date>` I mean the date corresponding to the time when you click the `[Update]` button and got the error.

**Comment by robbyoconnor** [comment]
last successful run was: `15-07-20_06.03.04`

**Comment by robbyoconnor** [comment]
```elisp
(setq update-packages-alist (quote ((cider . "cider-20150718.1022") (projectile . "projectile-20150717.530"))))
```

**Comment by robbyoconnor** [comment]
I see how elusive this is...I nuked my `elpa` dir and the error no longer happens...This should probably remain open because others will encounter it...not sure what the cause is...

**Comment by afronski** [comment]
@robbyoconnor Thanks! I tried to update from `0.101.2` to the most recent one (`0.103.5`) and I've ran over this issue - after removing completely `elpa` directory, update went smoothly.

**Comment by robbyoconnor** [comment]
You should use `develop`, while there is a good chance it will break briefly -- it's fixed rapidly -- There's a lot of stuff in `develop` that isn't in `master` :)
