### ISSUE TITLE
shell mode - leaving cursor on a outside of command prompt causes unexpected behavior

### ISSUE THREAD

**Issue by voltecrus** [syl20bnr/spacemacs#2410]
Here's how to reproduce:

1) Open a shell mode
2) Type a few commands
3) Move cursor up(it doesn't matter where, just somewhere other then the shell prompt)
4) :q out of shell window
5) Change file
6) Open shell window by calling (shell-pop-shell)
7) At this point shell-pop tries to switch directory corresponding to your current buffer by printing cd directory/of/file. However, because the cursor was left on the command output, when Enter is pressed shell takes the entire line as a command. All the "junk" that is not related to the cd command gets called as a command.

I looked through shell-pop docs, it doesn't look like shell-pop mode is responsible for it. At the same time I can't figure out where inside shell contrib that cd behavior is(Lisp beginner).

Thanks!

**Comment by myrjola** [comment]
shell-pop changes the working directory for shell-mode buffers in `shell-pop--cd-to-cwd-shell` https://github.com/kyagi/shell-pop-el/blob/master/shell-pop.el#L206-L211.

**Comment by voltecrus** [comment]
Awesome, thanks you!

**Comment by myrjola** [comment]
@voltecrus the fix for shell-pop is now in Melpa. Could you update your packages and validate that the fix works for you?

**Comment by voltecrus** [comment]
@myrjola It does. However, when it compiles it gives the following error message:

> In shell-pop--cd-to-cwd-shell:
> shell-pop.el:207:36:Warning: `end-of-buffer' is for interactive use only; use
>     `(goto-char (point-max))' instead.

I don't know if it makes sense to change it.

**Comment by myrjola** [comment]
@voltecrus Good find that byte-compile warning! I should really pay more attention. I fixed the warning in https://github.com/kyagi/shell-pop-el/pull/37.

**Comment by myrjola** [comment]
@voltecrus The fix is merged and available in MELPA. Can this issue be closed?

**Comment by voltecrus** [comment]
Yes. Thank you for you work!

**Comment by myrjola** [comment]
You're welcome! I think only you who opened the issue or the maintainer can
close issues.

-- 
Martin Yrjölä
martin.yrjola@gmail.com
+358 44 040 7895
