### ISSUE TITLE
Can we have screenshots for each theme in themes-megapack

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#2418]
It would be nice to have a screenshot for each theme for viewing in one place. Currently when I want to explore what possible themes are out there I'm cycling through them one by one.

**Comment by TheBB** [comment]
There's about 100 themes in that layer. I know there are some screenshots in the various READMEs already, but that might be stretching it.

**Comment by cpaulik** [comment]
I think a list of the themes with a link to the main repo would make sense. We could also link to a screenshot if the main repo hosts one. Including all the screenshots in the spacemacs git repo seems unnecessary to me and would bloat the repository.

**Comment by x-ji** [comment]
Sure. I didn't mean to necessarily put all the screenshots here. But the point is maybe there would be a way to see them all at once.

**Comment by bmag** [comment]
This website of emacs themes may be relevant: http://emacsthemes.caisah.info/

**Comment by syl20bnr** [comment]
We have one almost ready thanks to @robmerrell :-)
http://themegallery.robdor.com/

**Comment by x-ji** [comment]
Cool :+1:
