### ISSUE TITLE
projectile error: Package iswitchb is obsolete!`

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2423]
getting the following when I open a file under a projectile project: 
```
Package iswitchb is obsolete!
```

**Comment by TheBB** [comment]
Closing this. It's a core Emacs package that has been deprecated, but usage of it must be phased out in upstream packages (of which there aren't many, at least not from a cursory glance through my own `elpa`). It seems to be more a warning.
