### ISSUE TITLE
`SPC c r` conflict

### ISSUE THREAD

**Issue by xfq** [syl20bnr/spacemacs#2430]
In https://github.com/syl20bnr/spacemacs/blob/5f0c70636a4f8ea06cab6fad01a6c2b62732d9cc/doc/DOCUMENTATION.org#commenting :

* `SPC c r	`  comment region

In https://github.com/syl20bnr/spacemacs/blob/5f0c70636a4f8ea06cab6fad01a6c2b62732d9cc/doc/DOCUMENTATION.org#compiling :

*  `SPC c r` recompile

**Comment by TheBB** [comment]
The commenting binding doesn't exist any more from what I can see. Probably just a documentation bug.
