### ISSUE TITLE
Long bibtex files are slow due to show-smartparens-mode

### ISSUE THREAD

**Issue by jcpetkovich** [syl20bnr/spacemacs#2432]
I get an enormous amount of lag when viewing bibtex files using `show-smartparens-mode`. Turning it off eliminates the lag.

To reproduce:
1. clone development version of spacemacs
2. run spacemacs without a .spacemacs file
3. open a large bibtex file.
4. search for something with `C-s` or similar.

**Comment by pennyan** [comment]
I have experienced something similar. With a 100K emacs lisp file(auto generated file), while navigating and encounter a big block with ')'. It is so slow. 

I do not want to modify the spacemacs/packages.el file, which has a (show-smartparens-global-mode +1). I have to exclude the smartparens package from .spacemacs.

I want to know if there is a config that can only disable show-smartparens-mode. Or it can stop search maching parens if out of the screen would be better. 
Add it to the dotspacemacs/config does not disable it.

**Comment by TheBB** [comment]
@pennyan The mode is enabled unless the argument is a negative integer, you need `(show-smartparens-global-mode -1)`.

You can now open large files with `SPC f l`, which will disable all special behaviour, including what causes this problem.

There is a feature planned in https://github.com/syl20bnr/spacemacs/issues/3491#issuecomment-150478925 to include an automatic prompt for this, as well.

With that in mind I'm closing this issue.
