### ISSUE TITLE
dash option for zeal on mac

### ISSUE THREAD

**Issue by autosquid** [syl20bnr/spacemacs#2439]
`Zeal` can also be build on Mac, and it runs well. An option to use zeal on mac can make life better.

**Comment by ntcong** [comment]
the author of Dash doesn't want Zeal to be in OSX (fair because he helped Zeal a lot), and Zeal's author also stated that he won't even support building on OSX.

So I think staying with Dash is the real way here.

**Comment by autosquid** [comment]
@ntcong   oh, the story behind... However it sounds dirty to me to be frank. Does a promise like that still makes `zeal` GPL?

**Comment by ntcong** [comment]
it's still is, you can freely support it if you can, it's up to the author to do what his want.
