### ISSUE TITLE
Support keyboards with cursor keys in sensible places

### ISSUE THREAD

**Issue by mbertheau** [syl20bnr/spacemacs#2444]
I'm using this keyboard: https://www.kinesis-ergo.com/shop/advantage-pro-for-pc-mac/ and hopefully soon this keyboard: https://www.keymouse.com/about

Both have cursor keys in ergonomic places. However, unlike vim, cursor keys don't work in spacemacs.

So far I just have these mappings in my config:
```elisp
  (evil-leader/set-key
    "w <left>"  'evil-window-left
    "w <right>" 'evil-window-right
    "w <up>"    'evil-window-up
    "w <down>"  'evil-window-down)
```

But there's a lot more where cursor keys should work, if we want to support keyboards with the cursor keys in ergonomic places.

**Comment by Devagamster** [comment]
What do you mean by the cursor keys don't work in spacemacs? They seem to work fine in both insert and normal mode for me...

**Comment by mbertheau** [comment]
@Devagamster Good point. I'm missing them in particular for `C-w h/j/k/l` and `SPC b m h/j/k/l`.

**Comment by Devagamster** [comment]
I think you're gonna find it hard to convince people around here to fix using arrow keys as hjkl are pretty fantastic for ergonomics. I too have a kinesis and reaching down for those arrows is way harder than just keeping my fingers on the home row. If you really want to though I am sure you could rebind more of the keys like you did for the window navigation. I just doubt it will be officially supported as a toggle option.

**Comment by mbertheau** [comment]
@Devagamster Well, I also use this keyboard layout http://www.neo-layout.org/ (site seems to be down at the moment) which is awesome for programming, and horrible for hjkl navigation.

**Comment by Devagamster** [comment]
In that case it is definitely something you will have to configure on your own :)
