### ISSUE TITLE
Projectile-rails keybindings need to work for haml and slim as well. 

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2448]
Currently projectile-rails keybindings do not work for slim and haml files.

**Comment by abernardes** [comment]
I'm seeing this issue too. I see projectile-rails is loading since the traditional bindings like `C-c r m` work fine, but spacemacs ones don't 😕.

**Comment by exitface** [comment]
The mode is also lost in javascript, css and sass files

**Comment by pacuna** [comment]
+1

**Comment by smarquezs** [comment]
:+1:

**Comment by robbyoconnor** [comment]
Pull requests Welcome -- Also use the github reactions -- don't add +1 to every post.

**Comment by minusoneman** [comment]
I'm a vim user trying out spacemacs (interesting stuff), so I can't really say if it's a viable solution or not, but I managed to get the projectile-rails bindings to work with slim and coffee files by adding the modes to the layers/+frameworks/ruby-on-rails/packages.el:30

`(dolist (mode '(ruby-mode enh-ruby-mode slim-mode coffee-mode web-mode))`

Maybe that will help someone getting to the bottom of this.

**Comment by robbyoconnor** [comment]
Perhaps do a PR upstream?

**Comment by asok** [comment]
Hi guys,
that's happening because `projectile-rails` since version 0.12.0 is a global mode. It had to be changed since projectile is not a global mode also (at least on master).

This should fix this issue: https://github.com/syl20bnr/spacemacs/pull/7541

**Comment by jamieorc** [comment]
Now do I enable this in a custom fashion until this makes it into the main distribution? I need it for haml and erb files.

**Comment by asok** [comment]
@jamieorc add something like that your init file:
```el
(with-eval-after-load 'projectile-rails
  (projectile-rails-global-mode))
```

**Comment by jamieorc** [comment]
Thanks @asok, it looks like what I'm missing is how to `erb` and `haml` files into this, per https://github.com/syl20bnr/spacemacs/pull/7735/commits/7cb462df95c114086051d3954761b080c8ed6785

**Comment by asok** [comment]
@jamieorc you should have the mode enabled in erb and haml files once you enable the global mode. If the mode is not enabled for you, can you provide the repo so I can download it and debug?

**Comment by asok** [comment]
@jamieorc actually you should not run the mode inside `with-eval-after-load`. That was my bad. Instead you should simply do:
`(projectile-rails-global-mode)`

**Comment by jamieorc** [comment]
I'm clearly missing something. Haml files still do not register as part of the rails project, even if I call `(projectile-rails-global-mode)` manually in the mini buffer. When I look in the projectile-rails layer, it's missing `haml` and the other file types listed in pull #7735. From a ruby file in the project, I'm able to access projectile-rails context (`Spc - m`).

**Comment by robbyoconnor** [comment]
Just pull in #7735 and work :) It may be a while until it's merged.

**Comment by jamieorc** [comment]
@robbyoconnor Thanks, I just modified the local file in the layer. If there's a better way, I'm all ears.

**Comment by robbyoconnor** [comment]
@jamieorc the better way would be to cherry-pick the PR i mentioned above ;)

**Comment by juanibiapina** [comment]
How about from `.gitignore`, `.rspec-local`, `Makefile` or any other file you can possible have in your rails directory?

**Comment by asok** [comment]
This is covered by https://github.com/syl20bnr/spacemacs/pull/7541

**Comment by asok** [comment]
@sdwolfz I think it can be closed.
