### ISSUE TITLE
Support arrow keys

### ISSUE THREAD

**Issue by mbertheau** [syl20bnr/spacemacs#2451]
Vim supports cursor keys (arrow keys), so should spacemacs.

A start for now is:
```elisp
(evil-leader/set-key
    "w <left>"  'evil-window-left
    "w <right>" 'evil-window-right
    "w <up>"    'evil-window-up
    "w <down>"  'evil-window-down)
(define-key evil-window-map (kbd "<left>") 'evil-window-left)
(define-key evil-window-map (kbd "<right>") 'evil-window-right)
(define-key evil-window-map (kbd "<up>") 'evil-window-up)
(define-key evil-window-map (kbd "<down>") 'evil-window-down)
```

Missing are `C-w <arrow key>` in magit and probably other modes and `SPC b m <arrow key>`. I'll add more when I notice.

**Comment by aeschylus** [comment]
Ctrl-w h/j//k/l works just as it does in vim for me. Am I missing something?

**Comment by mbertheau** [comment]
@aeschylus I meant that the corresponding bindings with the arrow keys are missing. I updated the description to clarify.

**Comment by Devagamster** [comment]
I have the beginnings of a contrib layer that adds the keys you want. I will post it when I get home from work later tonight. If you can come up with some other bindings you are missing just let me know and I will add them :)

**Comment by mbertheau** [comment]
I opened #2829 with a PR. Discussion should probably continue there.
