### ISSUE TITLE
`SPC /`: jump to the next match?

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#2452]
How to jump to the next (previous) match with `SPC /` (`spacemacs/helm-project-smart-do-search-region-or-symbol`) or with one of other search tools (`SPC s ...`) after you selected a candidate.

Vim (grep) equivalent: `:cn`.

**Comment by justbur** [comment]
These are close to what you are asking for:

- TAB on each match in the helm buffer will open the file showing the match in another window without closing helm.

- C-c C-f enables follow mode which automatically shows the match in another window as you C-j C-k through the possible matches.

- C-c ? will show all of the options for the current helm session.

**Comment by mmcnl** [comment]
If you haven't opened another Helm buffer in the meantime, you can return to the last search results using `SPC h l`. 

I too, however, would love it to have an way (like in Vim) to easily switch to the next matching file without having to explictly re-visit the search.

**Comment by xged** [comment]
All good tips. This minimizes the issue, nonetheless I do too think the functionality is needed. One more tip -
`F3`: in a *helm* buffer, convert a *helm* search buffer into a regular buffer.

**Comment by syl20bnr** [comment]
I would like to have such feature too.
It should be provided by `SPC e n` (next-error) but somehow the search with helm is not compatible with next-error :-(
