### ISSUE TITLE
python-mode: fill does not auto-format strings

### ISSUE THREAD

**Issue by gleber** [syl20bnr/spacemacs#2456]
For example:

```
a = 'very-very-very outrageously long string'
```

after hitting M-q on it, I'd like it to be formatted according to fill-column and look like, assuming fill-column is very small, this:

```
a = 'very-very-very '
    'outrageously '
    'long string'
```

**Comment by TheBB** [comment]
I doubt we can help with that. Sounds like a feature request for `python-mode`. Seems to work fine with multiline strings, for the record.

I should also note that in your example, the 'after' code is illegal python syntax.

**Comment by gleber** [comment]
Good catch. I've used Prelude before and there it did something like that. It would allow me to write

    a = ('a b c d e f g')

hit `M-q` and get

    a = ('a b c d '
        'e f g')

**Comment by TheBB** [comment]
Okay, then maybe we could figure out how they do it.
