### ISSUE TITLE
Generate Tags and Search Does Not Honor Ignored Dirs in .projectile

### ISSUE THREAD

**Issue by jophde** [syl20bnr/spacemacs#2457]
I am working a large project.  It has a lot of generated code and bins that I don't want included in searches or tags.  However, I can't find a way to do this.  I have a .projectile file setup and even switched to native indexing.  The files are filtered correctly but it doesn't have any effect on tags or search.  The project is so large that search doesn't even work source in a deep directory.  Let me know how I can help.  Thanks.

**Comment by syl20bnr** [comment]
I suggest to use [pt](https://github.com/monochromegane/the_platinum_searcher) or [ag](https://github.com/ggreer/the_silver_searcher) which parse the `.gitignore` file (create one if you the project is not in a git repository), spacemacs will automatically pink one of them when you press `SPC /`.
If you are on windows then `pt` is my recommendation.
