### ISSUE TITLE
electric-indent is no longer disabled in Python

### ISSUE THREAD

**Issue by danshapero** [syl20bnr/spacemacs#2459]
I'm getting lots of unwanted indentation when editing Python with emacs 24.3, which I think is due to `electric-indent-mode`. For example, after the return statement of a function, as soon as I try to define a new function I get indented up to the level of the previous function.

I saw from a [previous issue](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/funcs.el#L830) that `disable-electric-indent-mode` was added to the `python-mode-hook` in an older version of spacemacs. The `disable-electric-indent-mode` function is still in the spacemacs distribution [here](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/funcs.el#L830), but it isn't called anymore in `python/init-python`.

I tried forking spacemacs and adding `disable-electric-indent-mode` to the list of python-mode hooks, but I get an error and don't know enough emacs lisp to fix it.

Finally, I've found that the problem only appears with emacs 24.3. I tried editing Python on a different machine with emacs 24.4 with no issue.

**Comment by CestDiego** [comment]
is this still an issue in Emacs 24.3? We are trying to clear up issues and this seems to be solved by having this in your config.

```
  (add-hook 'python-mode-hook '(lambda () (electric-indent-mode 0)))
```

**Comment by danshapero** [comment]
I upgraded all my systems to 25.1 so I'm not sure. Either way, I'll close the issue.
