### ISSUE TITLE
Some symbols almost invisible in ruby-mode with zenburn

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#246]
Note the symbols in the conserved_sequences function. Can you make out the "=", "+", "*" etc?

![screen shot 2014-12-11 at 06 52 38 3](https://cloud.githubusercontent.com/assets/5526486/5389834/70602784-8103-11e4-98c8-cdb12014ba20.png)

(Sorry for the large pic, do not have any image manipulation tools and select-region screenshots aren't working on my Yosemite version.)

**Comment by marcjeanson** [comment]
I just switched to spacemacs and I'm experiencing this behaviour as well. My themes are configured like this:
dotspacemacs-themes '(zenburn leuven)

Am I doing something wrong? zenburn-theme displays ruby code differently outside of spacemacs.
thanks

**Comment by mosic** [comment]
@marcjeanson There's an open issue you can subscribe to if you still experience this problem: https://github.com/syl20bnr/spacemacs/issues/1332

**Comment by marcjeanson** [comment]
@mosic Thanks!

**Comment by syl20bnr** [comment]
@marcjeanson I removed the work around in `develop`, give it a try if you're ok to use the `develop` branch (which is pretty stable right now, a release will be published this week).

**Comment by marcjeanson** [comment]
Works great, thanks!
