### ISSUE TITLE
Using QUELPA for treating extensions as packages

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#2468]
Old issue: https://github.com/syl20bnr/spacemacs/issues/5

Since `quelpa` is merged into MELPA: https://github.com/milkypostman/melpa/pull/2968, maybe it is the time to use `quelpa`, so we can add useful packages not on MELPA for layers.

**Comment by justbur** [comment]
We could also use quelpa to support installing layers in third-party github repositories. This would allow people to try different implementations of the same layer and to help layer development progress faster before they are merged.

**Comment by syl20bnr** [comment]
Thank you for notifying about this, this is a good news :+1: 

Be patient, I have some ground to prepare in core first :-)

**Comment by syl20bnr** [comment]
Noted as a duplicate of #5

**Comment by TheBB** [comment]
https://github.com/quelpa/quelpa-use-package/

**Comment by justbur** [comment]
That looks perfect.

**Comment by CestDiego** [comment]
:hype: I'm looking forward to this so

**Comment by syl20bnr** [comment]
Indeed!
I'll look tonight to bootstrap quelpa in spacemacs so you can start to play with it :-)

**Comment by TheBB** [comment]
:tada:

**Comment by CestDiego** [comment]
Awesume :+1:  thanks @syl20bnr

**Comment by syl20bnr** [comment]
This is pushed to develop. `:quelpa` and all its goodies should be available. :-)

**Comment by CestDiego** [comment]
@syl20bnr how shall we do this? is it docummented?

**Comment by syl20bnr** [comment]
For now it is not documented. You can read the documentation of the repo: https://github.com/quelpa/quelpa-use-package
