### ISSUE TITLE
Distraction free mode/centered buffer in Spacemacs?

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#247]
I usually try to make my emacs as beautiful and noiseless as possible, think Sublime text in the distraction free mode or something like [emacs strip-tease](http://bzg.fr/emacs-strip-tease.html).

When I try to emulate this with the following function in Spacemacs, I am only half successful:

```
  ;; Added to .spacemacs in the dotspacemacs/config section.
  (defun my-resize-margins ()
  (let ((margin-size (/ (- (frame-width) 160) 2)))
    (set-window-margins nil margin-size margin-size)))

  (add-hook 'window-configuration-change-hook #'my-resize-margins)
  (my-resize-margins)
```

The problem (apart from the ugly edges around the buffer) is that when pressing space the menu looks all weird:

![screen shot 2014-12-11 at 07 41 30 3](https://cloud.githubusercontent.com/assets/5526486/5390358/4fbdb314-810a-11e4-878b-4450715d7b92.png)
![screen shot 2014-12-11 at 07 42 04 3](https://cloud.githubusercontent.com/assets/5526486/5390359/4fbf79ba-810a-11e4-942e-b0876a4b97a8.png)

I hereby suggest a distraction-free mode in Spacemacs. 

I will post updates here if I find workarounds for the problems above, but my elisp skills and understanding of emacs is pretty limited ATM.

**Comment by jezenielzapanta** [comment]
@endrebak :+1: on this, and I agree with @syl20bnr.

**Comment by kini** [comment]
Possibly related: #481

**Comment by nixmaniack** [comment]
As of current state, you can achieve almost distraction free mode with `SPC w M` and `SPC t m t` which maximizes and centeres buffer, and hides the modeline.

**Comment by cocodrino** [comment]
Hi guys, I'm getting this error everytime than I try SPC w M

jump-to-register: Register doesn't contain a buffer position or configuration

what could be the reason?...I'm trying to get a distraction free mode

thanks

**Comment by StreakyCobra** [comment]
PR Pending: #4262

**Comment by arronmabrey** [comment]
I have a silly question. does this mode work in the terminal version or only gui? I have tried enabling it in the terminal, and I see no change. Except the message that it's now "enabled"

**Comment by xerron** [comment]
I like the features of this plugin Vim: 
https://github.com/junegunn/goyo.vim

**Comment by sebhahn** [comment]
What is the latest status on the distraction free mode?

**Comment by nothingmuch** [comment]
[writeroom-mode](https://github.com/joostkremers/writeroom-mode) seems to work nicely out of the box.

**Comment by sebhahn** [comment]
@nothingmuch How can I add it to my spacemacs config?

**Comment by nothingmuch** [comment]
I just did `package-install writeroom-mode` for now, but I will probably add to my [dotspacemacs-additional-packages](http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline21).

There's also focus-mode, I haven't tried that one yet.

**Comment by JAremko** [comment]
I added something like distraction free mode. Try `SPC` `w` `C` with develop branch :wink:

**Comment by superquest** [comment]
This is a relevant issue: https://github.com/syl20bnr/spacemacs/issues/9488

**Comment by adimit** [comment]
I must say, I prefer `writeroom-mode` to the current `SPC` `w` `C` feature. It is nicer for writing prose, as it center-justifies the text, and really hides every distraction.

`auto-fill-mode` needs to be activated for together with `writeroom-mode`.

**Comment by freddie-freeloader** [comment]
I agree with @adimit. Also `writeroom-mode` seems to handle bigger font-sizes better.
