### ISSUE TITLE
the vim 'dd' short cut does not delete the line

### ISSUE THREAD

**Issue by kgwinnup** [syl20bnr/spacemacs#2472]

**Comment by sooheon** [comment]
For me it always has. Any more details as to how to reproduce? This not enough information to help fix the bug.

**Comment by a13ph** [comment]
Damn, it happened to me now. I can delete with dj/dk, but dd works rarely if ever.

**Comment by shonfeder** [comment]
This is happening to me periodically as well. I'll report back if I can figure out what's causing it...

**Comment by shonfeder** [comment]
Ah, for me, it actually seems to this open issue affecting salt-mode: #9707
