### ISSUE TITLE
magit stages one line too many with evil-visual-line

### ISSUE THREAD

**Issue by mbertheau** [syl20bnr/spacemacs#2476]
In the magit status buffer when I want to stage a single line, if I mark it with <kbd>V</kbd> and then hit <kbd>s</kbd> to stage, the marked line **and the next line** get staged. You can see the region extend one line down after hitting <kbd>s</kbd>.

Workaround is to mark just one character in the line with <kbd>v</kbd> and stage then.

Now <kbd>v</kbd> is actually simpler than <kbd>V</kbd>, but <kbd>V</kbd> makes much more sense for staging a whole line.

**Comment by sooheon** [comment]
I think this may have something to do with the newline character being marked at the end of the line. With `V` you're selecting the entire line and the newline which begins the next line as well. I guess we can advice the magit state function, but like you said, just using `v` may be the simpler solution. FWIW, pure emacs users begin marking with C-SPC, and they don't have the linewise marking equivalent, hence the discrepancy.

**Comment by mbertheau** [comment]
There's a similar issue in magit-log, where I select commits with <kbd>V</kbd> in order to diff them with <kbd>d d</kbd>.

**Comment by syl20bnr** [comment]
I noticed this too and I use the same workaround with `v` instead of `V`, it is not really a big deal but it should be mentioned in the documentation.

**Comment by jb55** [comment]
This got me as well, I didn't realize you could use `v` until I read this issue.

**Comment by justbur** [comment]
Should be fixed with #3578
