### ISSUE TITLE
Unable to disable org-bullets

### ISSUE THREAD

**Issue by honza** [syl20bnr/spacemacs#2477]
Yes, I know I can change the bullets to other unicode characters but how can I disable this to get the normal ascii bullets?

**Comment by sooheon** [comment]
Add `org-bullets` to `dotspacemacs-excluded-packages`.
```
(dotspacemacs-excluded-packages '(org-bullets))
```

**Comment by honza** [comment]
Most excellent, thank you!

**Comment by tommyjiang** [comment]
Thanks for providing the solution @sooheon

**Comment by muusik** [comment]
Since org-bullets has been replaced by org-superstar, disabling bullets can now be achieved thus:
`(dotspacemacs-excluded-packages '(org-superstar))`
