### ISSUE TITLE
BUG: numeric prefix in evil mode works for j, but not k

### ISSUE THREAD

**Issue by spencerlyon2** [syl20bnr/spacemacs#2478]
If I enter `1 0 0 j` the point correctly moves 100 likes down.

If I then do `1 0 0 k` the point only moves 5 lines up?

If I try do do a double digit prefix for `k` (e.g. `5 1 k`) the point only moves up the number of lines equal to the first digit. 

I'm on current `develop`. Can anyone replicate?

**Comment by TheBB** [comment]
Duplicate: #1103.

**Comment by spencerlyon2** [comment]
Yep, definitely a duplicate. Closing now.
