### ISSUE TITLE
SPC t <letter> connection to minor mode letters in status line missing from docs

### ISSUE THREAD

**Issue by mbertheau** [syl20bnr/spacemacs#2482]
I read in https://github.com/syl20bnr/spacemacs/issues/1114#issuecomment-92556012

> You can disable the mode listed in the mode line with circled letter by pressing on SPC t <letter> where letter corresponds to the circled letter. If you disable auto-completion with SPC t a is it better ?

This is a gem of information, not only for toggling, but more so for finding out what these letters mean. Maybe it can be in a prominent place in the documentation?

**Comment by robbyoconnor** [comment]
@mbertheau if you wanna get rid of the unicode symbols set `dotspacemacs-mode-line-unicode- symbols` to nil. in `dotspacemacs/init` in `.spacemacs`

**Comment by robbyoconnor** [comment]
However, it's [already documented](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#minor-modes).

**Comment by mbertheau** [comment]
Ah, ok, sorry for missing that. Thanks for pointing it out, @robbyoconnor! :)
