### ISSUE TITLE
Make toggles more useful

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#2485]
Right now, toggles just toggle. A frequent question in gitter is how to set a toggle default to on or off. This is particularly relevant for the global toggles like line numbers. They are often told to toggle it in `dotspacemacs/config`, but this messes with `SPC f e R` unless you add a condition for the existing state. (For other reasons, `SPC u SPC f e R` may be undesirable.)

Proposals:
* add some `.spacemacs` variables for defaulting the most requested toggles on or off at startup.
* make the generated toggle function accept an optional argument to enforce on or off.

**Comment by robbyoconnor** [comment]
Make toggles stateful, that is they save -- when I toggle something on...it stays on until I turn it off.

**Comment by syl20bnr** [comment]
The macro could generate 2 additional functions to force the state: `spacemacs/toggle-<name>-on` and `spacemacs/toggle-<name>-off`.
