### ISSUE TITLE
how to set flycheck-mode  enabled only when i press write to file key?

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#2488]
how to set flycheck-mode  enabled only when i press write to file key?
Just like golang format code command active time. Only toggle when i save the file.
Because scirpt language such as python, lua. Such a red line trialing flash is so annoy when i write code.

For example, how to do it in python-mode?
Thanks for any ideas.

**Comment by syl20bnr** [comment]
This is a settings at the flycheck level package:

[User Option: flycheck-check-syntax-automatically](http://www.flycheck.org/manual/latest/Checking-buffers.html#Checking-buffers)

Put this in your `dotspacemacs/config`:

```elisp
(setq flycheck-check-syntax-automatically '(mode-enabled save))
```

**Comment by dzhwinter** [comment]
Oops, sorry for such an simple question which I should turn to their documentation.
Thanks
