### ISSUE TITLE
Enter “space-mode“ from insert mode

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#2491]
Maybe I just missed it in the documentation, but is there a simple way to access the space menu from insert mode?

I’m thinking about <kbd>C-SPC</kbd>.

**Comment by TheBB** [comment]
Do you mean `M-m`?

**Comment by Profpatsch** [comment]
@TheBB Ha, you were faster than me typing the content (accidentally hit enter). :)

**Comment by TheBB** [comment]
Okay :-). Well in any case, the leader key is bound to `M-m` in Emacs editing style, and that keybinding also works in insert state.

**Comment by Profpatsch** [comment]
@TheBB How would I redefine that to <kbd>C-SPC</kbd>? <kbd>C-h k M-m</kbd> is of no help.

**Comment by TheBB** [comment]
Your dotfile should have a variable for it. It's called `dotspacemacs-emacs-leader-key`.

**Comment by Profpatsch** [comment]
Ah, okay. Thanks, then!
