### ISSUE TITLE
String formatting is broken in Go.

### ISSUE THREAD

**Issue by isaiah** [syl20bnr/spacemacs#2495]
Shown as in the screen shot, it prevents me from typing `,`
![screenshot](http://i.imgur.com/nAiD92M.png)

**Comment by isaiah** [comment]
This is the stacktrace, hope it helps:
```elisp
Debugger entered--Lisp error: (wrong-type-argument commandp 1)
  call-interactively(1)
  go-mode-insert-and-indent(",,")
  call-interactively(go-mode-insert-and-indent nil nil)
  command-execute(go-mode-insert-and-indent)
```

**Comment by bogdanteleaga** [comment]
Can confirm this happens on the latest develop. Seems to not be a problem if there's another error on the same line. Also the bug only happens when the tooltip is up.

**Comment by isaiah** [comment]
Before an official fix is in place, you can disable `flycheck` mode for now:

```diff
diff --git a/contrib/!lang/go/packages.el b/contrib/!lang/go/packages.el
index 28e9b7b..90ad034 100644
--- a/contrib/!lang/go/packages.el
+++ b/contrib/!lang/go/packages.el
@@ -7,8 +7,8 @@
     go-eldoc
     ))

-(defun go/post-init-flycheck ()
-    (add-hook 'go-mode-hook 'flycheck-mode))
+;;(defun go/post-init-flycheck ()
+;;    (add-hook 'go-mode-hook 'flycheck-mode))
```

**Comment by robbyoconnor** [comment]
That's flycheck, not spacemacs.

**Comment by StreakyCobra** [comment]
@bogdanteleaga Does this still happen? The flycheck tooltip library has been changed, if it was the issue it may be solved.

**Comment by isaiah** [comment]
It works now.
