### ISSUE TITLE
magit-gitflow C-f command shadowed by new Evil scrolling

### ISSUE THREAD

**Issue by gilbertkennen** [syl20bnr/spacemacs#2496]
In [6dc3ea3](https://github.com/syl20bnr/spacemacs/commit/6dc3ea3393562c8dc0d7c6077713b797ef7b8c42), C-f gets assigned to 'evil-scroll-page-down and is active in magit mode. 'magit-gitflow-popup is normally accessed via C-f in this mode and currently requires manual calling.

**Comment by sooheon** [comment]
Any ideas for the best way to handle this? I would imagine another modifier (C-s-f or whatever) is against the spacemacs way, so would putting the command under leader somehow be preferred?

**Comment by syl20bnr** [comment]
We should evilify the magit mode map after magit-gitflow has been loaded then. Then __currently__ `C-f` will become `C-S-f`.

But I would propose another solution that is to rebind `magit-gitflow-popup` to an entirely new bindings following the "convention" introduced by `magit-gh-pulls` which is to have a prefix command `#`. So `magit-gitflow-popup` can be `#f`.
