### ISSUE TITLE
[develop] With the new modularized mode line, org-pomodoro clock is shown twice

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#2500]
As of https://github.com/syl20bnr/spacemacs/commit/e075e21faa39cefd0d5bbfaabfb9516cd6f7e098 : 

<img width="1097" alt="screen shot 2015-07-31 at 6 25 21 pm" src="https://cloud.githubusercontent.com/assets/42988/9020147/8b743eba-37b1-11e5-9ec5-cd77d6a07de0.png">

**Comment by syl20bnr** [comment]
Ooooooooh indeed, @TheBB fixed the global mode string too, such awesomeness :-)

**Comment by TheBB** [comment]
Which one do we keep? I'm kind of a fan of our custom one... the other one is so long.

**Comment by TheBB** [comment]
@swaroopch This is fixed in develop, if you can confirm please close.

**Comment by swaroopch** [comment]
@TheBB Yes, confirm it is fixed. Thank you!
