### ISSUE TITLE
Package `dash-' is unavailable

### ISSUE THREAD

**Issue by twlz0ne** [syl20bnr/spacemacs#2508]
- os x 10.9
- emacs 24.5.1
- spacemacs release-0.103

```sh
➜  emacs -nw -l ~/.emacs.d/init.el
Loading term/xterm...done
For information about GNU Emacs and the GNU system, type C-h C-a.
Loading ~/.emacs.d/core/core-load-paths.el (source)...done
Loading ~/.spacemacs...done
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:80 [3 times]
package-compute-transaction: Package `dash-' is unavailable
```

```sh
➜  curl -sL http://elpa.gnu.org/packages/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
<head>
  <title>GNU ELPA Packages</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<h1 align="center">GNU ELPA Packages</h1>
<table cellpadding="3" border="1">
<tr><th>Package</th><th>Version</th><th>Description</th></tr>
<tr><td><a href="ace-window.html">ace-window</a></td><td>0.9.0</td><td>Quickly switch windows.</td></tr>
<tr><td><a href="ack.html">ack</a></td><td>1.3</td><td>Interface to ack-like source code search tools</td></tr>
<tr><td><a href="ada-mode.html">ada-mode</a></td><td>5.1.8</td><td>major-mode for editing Ada sources</td></tr>
...
```

[Switching the connection from https://elpa.gnu.org/packages to http://elpa.gnu.org/packages in core/core-configuration-layer.el](https://github.com/syl20bnr/spacemacs/issues/2371#issuecomment-123539604) not work for me :(

**Comment by chrisbarrett** [comment]
If you haven't tried it already, deleting `~/.emacs.d/elpa` sometimes fixes these issues. The Emacs package manager can get into a flaky state sometimes.

**Comment by twlz0ne** [comment]
The problem is still persist.

**Comment by chrisbarrett** [comment]
Also, I don't know if `dash` is even on ELPA. Emacs needs To download it from MELPA, which is the package archive for GitHub projects. 

Make sure you haven't overriden `package-archives` anywhere in your config, and check the value of that variable to make sure MELPA is in there. `M-x describe-variable package-archives`. 

https://www.gnu.org/software/emacs/manual/html_node/efaq/Packages-that-do-not-come-with-Emacs.html#Packages-that-do-not-come-with-Emacs

**Comment by chrisbarrett** [comment]
If you can't figure it out from there, tell us:
- your Emacs version 
- the steps you've followed to install Spacemacs

**Comment by chrisbarrett** [comment]
Ah, I see you've posted your version. Apologies, on mobile, etc. :p

**Comment by twlz0ne** [comment]
You'er right， `package-archives` had overriden，but i didn't do that :|

```elisp
package-archives is a variable defined in `package.el'.
Its value is (("gnu" . "http://elpa.gnu.org/packages/"))
```

Here is my solution:

```sh
$ cd /path/to/fakehome
$ ll -a
total 24
drwxr-xr-x    7 gqj  staff   238B Aug  3 10:48 ./
drwxr-xr-x  117 gqj  staff   3.9K Aug  3 10:37 ../
-rw-r--r--    1 gqj  staff   345B Aug  3 10:46 .spacemacs
drwxr-xr-x   25 gqj  staff   850B Aug  3 10:44 spacemacs/

$ export HOME=$PWD
$ ln -s ~/spacemacs ~/.emacs.d
$ emacs -nw
```

It's work!

**Comment by chrisbarrett** [comment]
Weird. Maybe you have a `.emacs` file sitting in your home directory or something.
