### ISSUE TITLE
SPC shift+TAB

### ISSUE THREAD

**Issue by srid** [syl20bnr/spacemacs#2513]
As `SPC TAB` already switches to recent buffer, would it make sense to add an additional `SPC shift+TAB` that works, instead, on windows?

i.e., if I have two windows split in a single frame, I would like the similar TAB binding to switch back and forth between them.

**Comment by TheBB** [comment]
Doesn't `SPC w w` do this?

**Comment by srid** [comment]
Oh that will work!
