### ISSUE TITLE
Major mode commands not working in ClojureScript

### ISSUE THREAD

**Issue by malchmih** [syl20bnr/spacemacs#2515]
In develop and master branches when I press "," I got "No previous search" and there is no SPC-m item. Not sure when exactly, but it worked two weeks ago. ClojureScript files end with ".cljs"

**Comment by syl20bnr** [comment]
I can confirm this bug.

**Comment by kevincolyar** [comment]
Can confirm.  I found a workaround for starting my cider repl by switching to a .clj file, SPC-m-s-i, to start the repl and my figwheel server, then switching back to my .cljs file.

**Comment by malchmih** [comment]
Sure, all .clj files work just fine. But it is critical for me, since now you can connect to both clj and cljs repls from Cider.

**Comment by kevincolyar** [comment]
Same here, that's just been my work-around since losing the bindings in cljs mode.  Not ideal.

**Comment by darker0n** [comment]
It's fixed in #2559 :+1:

**Comment by malchmih** [comment]
@syl20bnr Could you please take a look at the pull request?

**Comment by darker0n** [comment]
Yes, please because it's very disagreeable

**Comment by malchmih** [comment]
Thanks a lot!

**Comment by malchmih** [comment]
I should probably close it since it's fixed now
