### ISSUE TITLE
Errors from clean install

### ISSUE THREAD

**Issue by channingwalton** [syl20bnr/spacemacs#2518]
Hi,
I am trying out spacemacs (pulled yesterday) but there are errors when starting:

```
Error (use-package): evil-jumper :init: Symbol's function definition is void: cl-struct-define
Error (use-package): undo-tree :init: Symbol's function definition is void: cl-struct-define
```

If I try to open files (org) or quit emacs I get
```
Warning (emacs): recentf mode: Symbol's function definition is void: undo-tree-save-history-hook
```
which prevents me quitting - had to force quit.

spacemacs version: (Release 0.103.x)
OS: Mac OSX 10.10
Emacs: 24.5 (9.0) from http://emacsformacosx.com

**Comment by syl20bnr** [comment]
I cannot reproduce it, can you try the version from homebrew to see if it fixes the missing standard library ?

https://github.com/syl20bnr/spacemacs#os-x

**Comment by channingwalton** [comment]
Hi, I've tried that with the same result, and also a nightly build from emacsformacosx

**Comment by sooheon** [comment]
Also unable to reproduce. There is also emacs-mac from brew cask, as another option to try.

**Comment by channingwalton** [comment]
The emacs-mac from brew cask has the same issue for me.
ok, I will try on another mac - perhaps something is wrong with mine.

**Comment by channingwalton** [comment]
I did a clean install of spacemacs and it works now - I am not sure what happened. A cosmic ray perhaps.

Sorry for the false alarm.

**Comment by louwers** [comment]
I had the same issue. This was due to the fact that `.spacemacs` was not created (again). You can copy it from here https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template
