### ISSUE TITLE
evilify helm

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#2520]
Do #1900 on all _helm-_*s.

**Comment by syl20bnr** [comment]
Can you give some usage example ? I don't know what buffers you have in mind.

**Comment by xged** [comment]
I want to look at a bunch of functions with search query "face". It could be threw `SPC :` (`helm-M-x`) or `C-h f` (`describe-function`) or `SPC ?` (`helm-descbinds`). Pretty basic usage.

**Comment by syl20bnr** [comment]
Ok, you want evilified bindings for any helm search buffer turned into a stand alone buffer ?

**Comment by xged** [comment]
Yes :-)
