### ISSUE TITLE
Have guide key use lambda function documentation-string

### ISSUE THREAD

**Issue by srid** [syl20bnr/spacemacs#2521]
i.e., replace "??" with "Open Inbox.org" in the screenshot below.

<img width="486" alt="screen shot 2015-08-02 at 6 19 02 pm" src="https://cloud.githubusercontent.com/assets/3998/9029161/27aadb8a-3943-11e5-8cf8-cf9d2d2e20c0.png">

**Comment by syl20bnr** [comment]
`guide-key` is deprecated in the upcoming 0.104.0, Spacemacs now uses [which-key](https://github.com/justbur/emacs-which-key).

Can you test your key binding in `develop` branch ?

**Comment by srid** [comment]
Similar behaviour with the develop branch using which-key:

<img width="256" alt="screen shot 2015-08-03 at 9 25 51 am" src="https://cloud.githubusercontent.com/assets/3998/9042155/c34d5710-39c1-11e5-85d1-1b79909a7e13.png">

**Comment by TheBB** [comment]
Ping @justbur.

**Comment by justbur** [comment]
Does it make sense to give lambdas docstrings? This can't be typical. Even if I did this, you'd have to go through and give every lambda a docstring. I would think it would make more sense to just define a function first and bind the key to that function. Then it's easy to find the function's definition through the emacs documentation.

**Comment by justbur** [comment]
By the way, the reason the behavior is the same is that both guide-key and which-key use `describe-buffer-bindings` as the source of the current keybindings. You can see that that's where the `??` comes from.

**Comment by EricCrosson** [comment]
I agree with justbur -- naming each defun is a lot more sensible than adding docstrings to lambda functions. Then, once a defun is named, might as well give it some love by adding a docstring...

**Comment by srid** [comment]
Fair enough.

```elisp
  (defun org-open-inbox ()
    (interactive)
    (find-file-existing "~/Dropbox/org/Inbox.org"))
  (evil-leader/set-key
    "oc" 'org-capture
    "oi" 'org-open-inbox
  )
```

**Comment by justbur** [comment]
You gave me an idea though. I think I will replace `??` with `lambda` by default, so it's clear what the problem is.

**Comment by EricCrosson** [comment]
@justbur Smooth idea, looking forward to it.
@srid, you can also retain the structure of your OP with something like the following:

```lisp
(evil-leader/set-key
  "oc" 'org-capture
  "oi" (defun org-open-inbox () (interactive) (find-file-existing "~/Dropbox/org/Inbox.org")))
```
That is, simply change the `lambda` to a named `defun.`
*Although*, technically the specs say the return value of a `defun` is undefined. I use this technique all day long, though, so you and me will be in the same boat together should anybody decide to change the current return value of `defun`.
One advantage of this snippet over your latest snippet is that the `evil-leader/set-key` sexp will only be called once, and not each time your method is invoked. 

Happy hacking
