### ISSUE TITLE
Project-regenerate-tags returns an error

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2526]
```
projectile-regenerate-tags: ctags: invalid option -- 'e'
	Try `ctags --help' for a complete list of options.
```

Is this an error in spacemacs or upstream?

**Comment by syohex** [comment]
Do you install [Exuberant Ctags ](http://ctags.sourceforge.net/) ?
Please see https://github.com/bbatsov/projectile#regenerate-tags

**Comment by robbyoconnor** [comment]
This needs to be documented somewhere...but thank you SOOOOO much :heart:
