### ISSUE TITLE
Neotree 0 window bug

### ISSUE THREAD

**Issue by darker0n** [syl20bnr/spacemacs#2527]
When I open neotree window 0 doesn't work, it's window 1, but then (after change file) all works fine: it's in 0 window

**Comment by darker0n** [comment]
Note: I tried it in develop branch. Not sure about master.

**Comment by syl20bnr** [comment]
I can reproduce it and it is very annoying. I'll try to get some time to look at it.

**Comment by malchmih** [comment]
+1
