### ISSUE TITLE
[develop] org agenda lines lose theme colors when navigating lines

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#2529]
If I run `org-agenda-list`, the display is as per expected theme colors, but when I navigate down using `j`, the lines *lose color* and become plain. It gets "fixed" by hitting `r` to refresh the display.

**Comment by syl20bnr** [comment]
This is a regression introduced by my fix to actually activate `hl-anything`, it also happen on the home buffer.
cc @boyw165

**Comment by CestDiego** [comment]
It also happens on ERC ... :(

**Comment by travisbhartwell** [comment]
I've noticed this in the gnus group and summary buffers as well.

**Comment by syl20bnr** [comment]
I'll deactivate the package for now then.

**Comment by zilongshanren** [comment]
@syl20bnr  Maybe we could disable `hl-anything` in some major mode, http://emacs.stackexchange.com/questions/24767/how-to-disable-a-hl-anything-in-orgmode

Now the `hl-anything` is excluded, I can't simply install it, any suggestions?

**Comment by lebensterben** [comment]
Given the age of this bug, despite it's closed, I've decided to remove `hl-anything` in an upcoming PR completely.
