### ISSUE TITLE
TAB, Shift-TAB behave identically while re-indenting org list items

### ISSUE THREAD

**Issue by EricCrosson** [syl20bnr/spacemacs#2530]
Greetings,

I just noticed how batty this behavior drives me. Say I have a list like follows:

![selection_003](https://cloud.githubusercontent.com/assets/1596818/9046341/9fa971bc-39ef-11e5-92c5-e674b320f27e.png)

and I wish to add (yet another) child to the current list item. Pressing `o` does this nicely.
Now, if I wish to give franz a child, I may press `o TAB`, resulting in the following:

![selection_004](https://cloud.githubusercontent.com/assets/1596818/9046376/d85c2284-39ef-11e5-8b35-81b6d2f9e46c.png)

BUT, if I wish to insert list item 3 instead of giving franz a child, I would naturally reach for the traditional inverse-tab, aka the `Shift-TAB`. However, `Shift-TAB` does not function as inverse-tab here. Actually, `o Shift-TAB` results in the same end state as `o TAB`, meaning to insert list item 3 instead of franz' child I need to press `o TAB TAB TAB`, three times! (or more, with deeper nesting) which really adds up to a large number of strokes. Interestingly, both `Shift-TAB` and `TAB` seem to just cycle the bullet all the way forwards and then all the way back -- meaning if the user was to go too far just once, he/she would have to press nearly `TAB` a total of 2 * the_nesting_level just to go back, or else use insert mode nastily. 

Seems like making the `Shift-TAB` go the opposite direction than shift would make more intuitive sense here. 

Discussion?

**Comment by sooheon** [comment]
Had the same experience and hated it. `C-h k TAB` will show you just how overloaded this key is in org, as it also deals with folding. I've taken to using `M-h` `M-j` `M-k` `M-l` to deal with list item indentation and ordering. This avoids the headache of remapping or advising the `org-cycle` function. To do what you want, I'd press `o M-h`. It's the same number of key presses, with the advantage of having a common modifier key for also reordering and in/outdenting the item.

**Comment by EricCrosson** [comment]
Woah! I didn't know about these keys. Badass, thanks for the tip @sooheon.

Good enough for me, marking as closed. Cheers
