### ISSUE TITLE
problem on srefactor in c/c++ layer

### ISSUE THREAD

**Issue by autosquid** [syl20bnr/spacemacs#2542]
problem on srefactor: in a c++ file, press spc m rand then press 'q' or select 'cancel' to return to the c++ file, then all general key-bindings changed. That happens each time I repeat the steps before. It seems the leader-key changes from spc to `M-m'. If I kill that c++ buffer, and reopen it, everything comes back right.

**Comment by tuhdo** [comment]
Oh it seems `evil-emacs-state` has a global effect. I will need to fix this.

**Comment by tuhdo** [comment]
I fixed it in the latest commit. Please try again.

**Comment by autosquid** [comment]
The fix seems to work. The problem disappears. Thanks.
