### ISSUE TITLE
Evil lisp commands add indentation in Haskell mode

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#2547]
In haskell-mode, running any evil lisp command, either by key binding or by name (e.g. <kbd>SPC k w</kbd>) will cause the current line to be indented one additional space.

**Comment by syl20bnr** [comment]
evil lisp command may have different behavior in non-lisps, to achieve `SPC k w` I suggest using `SPC v s )`, repeat `v` until you get the whole thing you want to wrap.
`(` will insert spaces between the parens.

**Comment by rpglover64** [comment]
Yes, that works for wrapping, but e.g. <kbd>SPC k r</kbd> (`evil-lisp-state-sp-raise-sexp`) doesn't have a nice vim equivalent. Also, the note at the end of [this](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#editing-lisp-code) section of the spacemacs documentation suggests that the evil lisp state keybindings are intended to be useful in editing things that aren't only lisp.

This might be an issue with smartparens; it looks like calling `sp-raise-sexp` directly has the same buggy behavior.

**Comment by syl20bnr** [comment]
The only smartparens functions trying to work in other languages are behind `` SPC k ` ``, these functions are called `hybrid`.
There is no `raise` available unfortunately it would require some kind of awareness of the underlying AST.

**Comment by rpglover64** [comment]
But `raise` does exactly what I want, except that it also inserts exactly 1 space every time it is called.

Also, reading the smartparens [documentation](https://github.com/Fuco1/smartparens/wiki/Hybrid-S-expressions) on its `hybrid` commands, that's not the impression I got; specifically, I got the impression that the hybrid commands are for manipulating "hybrid sexp"s, which are distinct from "sexp"s in a way that makes them more useful in non-lisp languages, but that if you wanted to manipulate "sexp"s, you could do so just fine using the standard commands.

Finally, calling the `hybrid` commands results in the same incorrect behavior.

This looks like it's a bug in haskell-mode, so I've filed it there: haskell/haskell-mode/issues/796.
