### ISSUE TITLE
SPC tab behavior

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#2548]
@mbertheau brought this up in gitter and I realized it's been bugging me too. `SPC tab` switches to the last visited buffer regardless of windows, but I suspect most people expect it to switch to the previously visited buffer *in the current window*.

I implemented this in my dotfile and I found it vastly preferable.

Thoughts?

**Comment by syl20bnr** [comment]
I'm open to give it a try.
I believe that I have once been caught by this but not sure about what caused the discomfort exactly.

**Comment by sooheon** [comment]
Just tested it, I much prefer this behaviour. With previous, if I switch to and then back from a repl, space tab will give me two repls, almost certainly what you don't want.

**Comment by stormpat** [comment]
+1

**Comment by felipe-barros** [comment]
:+1:
