### ISSUE TITLE
Capital r deletes a char inappropriately when mixed with evil-escape

### ISSUE THREAD

**Issue by EricCrosson** [syl20bnr/spacemacs#2549]
With a buffer like this:

![selection_005](https://cloud.githubusercontent.com/assets/1596818/9095674/1f17e4b2-3b7e-11e5-956c-b2e8ff940ab4.png)

Hitting `R ESC` gives me this buffer:

![selection_006](https://cloud.githubusercontent.com/assets/1596818/9095697/49ca709e-3b7e-11e5-91c6-de81ce283e19.png)

I would assume hitting `R fd` would give me the same buffer, but instead I am given this (with a subtle bug in the code!):

![selection_007](https://cloud.githubusercontent.com/assets/1596818/9095700/56ab3bcc-3b7e-11e5-958c-284c429b49e3.png)

one of my chars has been deleted.

**Comment by syl20bnr** [comment]
This is an [evil-escape](syl20bnr/evil-escape) bug, can you open an issue on the repo and link to it here ?

**Comment by EricCrosson** [comment]
Issue syl20bnr/evil-escape#37 has been opened

**Comment by bmag** [comment]
@syl20bnr can be closed as fixed upstream.

**Comment by syl20bnr** [comment]
@bmag thanks ;-)
