### ISSUE TITLE
Unique clipboard integrated with system clipboard ?

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#255]
On https://github.com/syl20bnr/spacemacs/pull/253 we started a discussion on the topic of having only one clipboard which will be the system clipboard. This feature would have a toggle and would be turned on by default. Ideally, it should be cross-platform.

**Comment by StreakyCobra** [comment]
This issue is dying alone in the cave. Let's close this, we will discuss it when the question will come back.
