### ISSUE TITLE
Missing face for replace state

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#2550]
When trying to reproduce #2549 I noticed this.

Anyone with a sense of aesthetics who want to suggest a colour?

**Comment by sooheon** [comment]
When I press `R`, my cursor changes to a little underscore. Isn't this good enough? Or what do you mean by face?

**Comment by TheBB** [comment]
Does your modeline work in replace state? Mine doesn't. The messages buffer says it's because `spacemacs-replace-state` is undefined.

**Comment by sooheon** [comment]
It looks like this:
<img width="690" alt="screen shot 2015-08-07 at 6 17 07 pm" src="https://cloud.githubusercontent.com/assets/302945/9132721/8a81de5c-3d30-11e5-86cf-efc2bf5891ae.png">

So I guess you mean the black window number square, which needs a color. I thought black was fine, but sure maybe some other shade to alert text will be overwritten is good.

**Comment by TheBB** [comment]
I get no modeline at all... There's no warning about a missing face in your \*Messages\*?

**Comment by sooheon** [comment]
Ah I do get this. 

<img width="690" alt="screen shot 2015-08-07 at 6 45 40 pm" src="https://cloud.githubusercontent.com/assets/302945/9133182/866f104c-3d34-11e5-842a-791193c69d05.png">

**Comment by TheBB** [comment]
Okay, it's strange then that you get a modeline at all. But okay, in any case there's a missing face. :-)

**Comment by syl20bnr** [comment]
I have no mode-line as well (develop HEAD).
