### ISSUE TITLE
update error! it always say: version-to-list : Invalid version string: 'nil'

### ISSUE THREAD

**Issue by freestyle4568** [syl20bnr/spacemacs#2557]
I don't know why it happen. My version is 0.103.2
![problem](https://cloud.githubusercontent.com/assets/10106571/9107718/32da9be6-3c5c-11e5-8cb5-dca61767503c.png)

**Comment by syl20bnr** [comment]
This is a known error that I struggle to reproduce, I try on 0.103.2, thank you for the report.

**Comment by freestyle4568** [comment]
all right，i really like spacemacs，it is cool^_^
although it has some bug now，it still perfect combine emacs with vim perfectly. waiting for version 1.0.0^_^
