### ISSUE TITLE
Feature Request: Insert function definition (at point) into the buffer

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#2560]

**Comment by syl20bnr** [comment]
I'm not sure to understand the feature, can you provide more info on the feature and a use case to be sure there is no missunderstanding ?

**Comment by xged** [comment]
E.g. I get a list of *faces* (defined by `defface`) and for each one of them >> go to their definition (`gd`) >> copy definition >> paste it in my *.spacemacs* file/buffer >> modify it. (Definitions are scattered).

But I would use the feature even just for exploring for the convenience of not leaving the current buffer.

**Comment by tuhdo** [comment]
If you add `emacs-lisp` layer,  it will show you the definition at point in the echo area without doing anything.

**Comment by xged** [comment]
@tuhdo Isn't that too much of a visual noise and a performance penalty to have it all the time? But I would use it as a *toggle* when heavy exploring.

**Comment by tuhdo** [comment]
@xged nope. It is because if a symbol is shown, it is already loaded into Emacs, and is only triggered when you place point on a symbol. I don't think it's a visual noise since it's only shown at the bottom and only when you place point on a symbol.

This is Emacs, not Vim :)

**Comment by xged** [comment]
@tuhdo Point can be moved very fast :-), but it probably waits a second or a half for the definition to show up as most of the similar tools do, so that solves my silly concerns. Still a very different problem then pasting.

**Comment by tuhdo** [comment]
For your problem, I think it's easier to create a window that is clone of the current window (by simply splitting with `:vs` or `:sp`, then move point there and jump to function definition.

**Comment by xged** [comment]
@xged I did it fast enough with macros. Nonetheless, I think the feature is important (because function definitions in general are super important).

**Comment by sooheon** [comment]
Take a look at lispy. Specifically [these](https://github.com/abo-abo/lispy#ide-like-features) features, as well as `M-.` and `M-,`, which will do exactly what you want.

**Comment by syl20bnr** [comment]
That's nice :-)

**Comment by beta1440** [comment]
This issue appears to have been resolved.

**Comment by d12frosted** [comment]
I don't agree that the initial feature request was satisfied. But I don't see much traction here. So I am not sure what to do. 😸 😿
