### ISSUE TITLE
`q` (evil-record-macro) does not function across buffers unlike `C-x (` (kmacro-start-macro)

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#2561]

**Comment by syl20bnr** [comment]
Can you provide a repro step ?
I tested to record a macro in one buffer and then use it in anothre buffer, it works, but I'm not sure thisi is exactly what you meant.

**Comment by syl20bnr** [comment]
Also it is really useful to specify your environments when submitting bugs, i.e. OS and emacs build.

**Comment by xged** [comment]
Sorry, looks like it does work. I did not investigate the case properly.
