### ISSUE TITLE
Python close all folds doesn't terminate

### ISSUE THREAD

**Issue by mbertheau** [syl20bnr/spacemacs#2562]
(These steps are probably not correct elisp, reproduce manually :))

1. `(new-empty-buffer)`
2. `(python-mode)`
3. `(insert "def")`
4. `(evil-close-folds)` (<kbd>zM</kbd>)

Actual: function doesn't terminate, hogs CPU
Expected: function terminates

Debugger output (obtained with `(setq debug-on-quit t)` and then <kbd>C-g</kbd> while the function runs):
```
Debugger entered--Lisp error: (quit)
  re-search-forward("^[[:space:]]*\\_<\\(?:class\\|def\\)\\_>[[:space:]]+\\([_[:alpha:]][_[:word:]]*\\)" nil t)
  python-nav--beginning-of-defun(-1)
  python-nav-beginning-of-defun(-1)
  python-nav-end-of-defun()
  #[257 "\300 \207" [python-nav-end-of-defun] 2 "\n\n(fn ARG)"](1)
  hs-forward-sexp((1 4 #<buffer untitled>) 1)
  hs-hide-block-at-point(t)
  hs-hide-all()
  funcall(hs-hide-all)
  evil-fold-action((((hs-minor-mode) :open-all hs-show-all :close-all hs-hide-all :toggle hs-toggle-hiding :open hs-show-block :open-rec nil :close hs-hide-block) ((hide-ifdef-mode) :open-all show-ifdefs :close-all hide-ifdefs :toggle nil :open show-ifdef-block :open-rec nil :close hide-ifdef-block) ((outline-mode outline-minor-mode org-mode) :open-all show-all :close-all #[nil "\300\301!\207" [hide-sublevels 1] 2] :toggle outline-toggle-children :open #[nil "\300 \210\301 \207" [show-entry show-children] 1] :open-rec show-subtree :close hide-subtree)) :close-all)
  evil-close-folds()
  call-interactively(evil-close-folds nil nil)
  command-execute(evil-close-folds)
```

**Comment by TheBB** [comment]
This must be reported to Emacs. It's not our bug.

**Comment by CestDiego** [comment]
This is a very nasty bug. Still an issue as well, but it's not an Spacemacs Issue.

**Comment by TheBB** [comment]
@mbertheau Any plans to report this further?

I'm of a mind to close this issue since it's not our problem and it's not very critical for us.

**Comment by mbertheau** [comment]
@TheBB Yeah, I didn't get around to reporting this upstream. Not sure if I ever will, since I'm spending more and more time with other programming languages now.

In any case the issue can be closed here.
