### ISSUE TITLE
pt,es,find does not work with spacemacs under windows7,64bit

### ISSUE THREAD

**Issue by LuoPX-15510486969** [syl20bnr/spacemacs#2564]
i hava installed pt,es,find programe on my computer and (executable-find) shows the right path.which confused me is that grep is in the same directory and it work well. I use these tools with helm. I have test master spacemacs version and develop spacemacs version.

**Comment by LuoPX-15510486969** [comment]
with the help of syl20bnr at gitter, i get a result :SPC / and SPC s f can work allways . M-x helm-do-ag and helm-find works sometimes .helm-locate never works.

**Comment by syl20bnr** [comment]
Since you get it to work by using regular search Spacemacs key bindings instead of calling manually `helm-do-ag` (which behavior is as expected), I close this issue.
