### ISSUE TITLE
python repl: no completion for module names

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#2568]
When using the python repl (IPython), enter this input: ("|" is the position of the cursor)
```python
In [4]: import itert|
```
I expect "itertools" to be available for completion, but hitting TAB doesn't complete anything.
I'm using emacs 24.5.2.

**Comment by tuhdo** [comment]
There's `ipython-notebook` layer that provides proper `ipython` REPL. Currently `run-python` does not work properly with `ipython` REPL.

**Comment by bmag** [comment]
Thanks, I managed to fix it, but I'll look in `ipython-notebook` anyway.
