### ISSUE TITLE
Magit unbinds 'f'

### ISSUE THREAD

**Issue by Kernael** [syl20bnr/spacemacs#2571]
Magit's **git remote update** command, `f a` seems to unbind the **f** key for `helm`.

* Open Spacemacs
* Select project with `SPC p p F3`
* update remote with `f a`
* try `SPC /` -> pressing **f** in `helm` yields `f is undefined`

I can reproduce this bug almost every time with this procedure, do you guys have the same ?

**Comment by bgamari** [comment]
Yes, I have also found this to be the case. I think the problem may apply to all minibuffer uses.

**Comment by edvail** [comment]
Same for me.

**Comment by ocharles** [comment]
I believe I'm seeing this too, when I hit `/` to search and type "I love falafels" I end up with "I love alaels" :)

**Comment by justbur** [comment]
I can't reproduce this. Is this an evil-escape thing?

**Comment by edpaget** [comment]
Chiming in to say I am also experiencing the same issue.

**Comment by StreakyCobra** [comment]
I can't reproduce this, not on `develop` nor on `master`. @ocharles @edpaget can you put here the output of `SPC h d s` to have more info about your config?

**Comment by justbur** [comment]
Can someone having this issue disable `evil-escape` and see if the problem goes away?

**Comment by edpaget** [comment]
@StreakyCobra 

```
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.4
- Spacemacs branch: master (rev. f04bb61)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults
                 (git :variables git-gutter-use-fringe t)
                 python markdown org syntax-checking ruby clojure html scala spotify javascript rust rcirc react yaml ruby-on-rails gnus purescript)
```

**Comment by edpaget** [comment]
@justbur when I try to disable evil-escape-mode I get this error `evil-escape--undefine-keys: Symbol's value as variable is void: evil-iedit-state-map` after that I still see the problem of my f-key not working.

**Comment by StreakyCobra** [comment]
I reproduced your environment, i.e. Linux + emacs 24.5.1 + rev. f04bb61 + spacemacs + all your layers: can't reproduce. I'm kind of out of idea right now.

**Comment by justbur** [comment]
@edpaget try adding evil-escape to excluded packages and restarting so it's completely out of the picture

**Comment by edpaget** [comment]
@justbur doing that fixed the problem for me.

**Comment by justbur** [comment]
@edpaget I'm not surprised but I also don't have a solution for you besides disabling evil-escape and reporting the issue unfortunately

**Comment by edpaget** [comment]
Thanks I've opened https://github.com/syl20bnr/evil-escape/issues/56

**Comment by edpaget** [comment]
This was solved upstream

**Comment by StreakyCobra** [comment]
:+1: thx for the info
