### ISSUE TITLE
`evil-repeat` (`.`) does not work after Ace-jump when two chars are needed

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#2573]
After `SPC SPC a b` (`evil-ace-jump-word-mode`) command `.` (`evil-repeat`) does no work.

**Comment by syl20bnr** [comment]
Ace-jump integration in Evil is done by Evil itself. You can open an issue on the Evil repo: https://bitbucket.org/lyro/evil/issues?status=new&status=open
If you do, please add a link of the issue here so we can track it.

**Comment by TheBB** [comment]
Since we don't use ace any more, this is presumably fixed. At least, I'm unable to reproduce.
