### ISSUE TITLE
Shell pop with incorrect character display

### ISSUE THREAD

**Issue by geekplux** [syl20bnr/spacemacs#2580]
I just added a new layer `shell`, but when I pop the zsh shell in spacemacs, it showed some incorrect character:
![5c858765-358e-4543-bb2c-46fc630d3109](https://cloud.githubusercontent.com/assets/3816105/9150071/30c0f6c6-3dfa-11e5-9d9a-d2ad45e986ec.png)

and I start zsh in iTerm:
![eaad36e2-997c-4c88-830a-0aca0aec6663](https://cloud.githubusercontent.com/assets/3816105/9150069/26302f60-3dfa-11e5-87ab-a692969dfa3d.png)

How can I fix it? 
thanks

**Comment by mayersj1** [comment]
I had this same issue with zsh prompts in multi-term.  Two things I did to resolve this:

1. set the TERM variable to 'eterm-color'

2. execute 'stty -ixon -ixoff' as the last thing my shell configuration does.

Hope those help

**Comment by geekplux** [comment]
@mayersj1 thank you, but I didn't find the option to set it to 'eterm-color'.

![05f03dc3-d476-413f-b930-3ec81c2dbd69](https://cloud.githubusercontent.com/assets/3816105/9188797/1b08002a-4013-11e5-8a84-f16807863a78.png)

**Comment by mayersj1** [comment]
Sorry I wasn't clear about that.  I'm referencing code within my shell initialization script that is doing this (in my case zsh):

```
if [ -n "$INSIDE_EMACS" ]; then
    export TERM=eterm-color
    export PAGER=cat
else
    export TERM=xterm-256color
fi
stty -ixon -ixoff
```

**Comment by geekplux** [comment]
@mayersj1 thank you very much! According to your method, I fixed it.

**Comment by mayersj1** [comment]
Great! Glad that helped!

**Comment by TheBB** [comment]
Can this be closed then?

**Comment by geekplux** [comment]
@TheBB OK, thanks

**Comment by TheBB** [comment]
I can't close it. I'm asking you to do it. :-)

**Comment by kissgyorgy** [comment]
This did not solved it for me. I have dynamic coloring with [prezto](https://github.com/sorin-ionescu/prezto) and when color would change, I got strange characters like this:
![image](https://cloud.githubusercontent.com/assets/244203/11543144/5554587e-993b-11e5-9f3f-f8a2d218da9d.png)
Any idea?
