### ISSUE TITLE
Error on closing `term` buffer

### ISSUE THREAD

**Issue by aviralg** [syl20bnr/spacemacs#2584]
When I execute

    M-x term

and then exit from it, I am brought back to the previous buffer with the following error messge in the minibuffer -

    error in process sentinel: Attempt to delete minibuffer or sole ordinary window

Its definitely not hindering my work, but it is odd.

**Comment by sooheon** [comment]
What command are you using to "exit" the terminal window? That error message is a generic response to `delete-window` when there focus is on the mini buffer or there is only one window (like it says). It should have nothing to do with terminal. I suggest looking at the `shell` layer and reading the docs.

**Comment by aviralg** [comment]
@sooheon Thanks so much for `space '`. I didn't realize it persists the shell. You are right. If I have a single window in which I open the term(zsh) and then type `exit`, I get the message. For multiple windows, typing `exit` in the term buffer of a particular window just kills that window and moves focus to a new window.
