### ISSUE TITLE
How to change the cursor style from char block to bar in evil-insert mode.

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#2586]
There is a same issue here #1543 . I open a new issue to provide some clue.
AFAIK,  (setq-default cursor-type 'bar) can change the cursor style to bar, but in spacemacs, the settings is not working.

ubuntu 14.04
spacemacs 103.2 beta
zsh 5.0.2 (with oh-my-zsh )

**Comment by sooheon** [comment]
Are you using terminal or graphical emacs? What you are trying to do isn't supposed to work in the terminal. It should work in graphical emacs.

**Comment by dzhwinter** [comment]
I use emacs-no-x In terminal. I used it for years before it break . 
By the way, I forget the emacs version
emacs-nox 24.5

**Comment by cmccloud** [comment]
@dzhwinter you may need to set the cursor for the appropriate evil state, e.g. 
```
(setq-default evil-insert-state-cursor 'bar)
```

**Comment by dzhwinter** [comment]
this issue missing after i upgrade my spacemacs to 0.104 develop branch magically. But I think it's nothing to do with spacemacs because I had met that long before.
Thanks anyway @cmccloud
