### ISSUE TITLE
I had some problems for using flymake-google-cpplint and google-c-style in spacemeacs

### ISSUE THREAD

**Issue by zhexuany** [syl20bnr/spacemacs#2590]
As I stated in subject, I cannot make them work very well in spacemacs.
I install c/c++ mode and add the following code in package.el, but spacemacs return some erros. 
(setq c-c++-packages
  '(
    cc-mode
    clang-format
    cmake-mode
    company
    company-c-headers
    company-ycmd
    flycheck
    gdb-mi
    helm-gtags
    semantic
    srefactor
    stickyfunc-enhance
    ycmd
    google-c-style
    flymake-google-cpplint
    flymake-cursor
    ))

(defun c-c++/init-google-c-style ()
 (use-package flymake-google-ccplint )
  (custom-set-variables
   '(flymake-google-cpplint-command "/System/Library/Frameworks/Python.framework/Versions/2.7/bin/cpplint"))
  (flymake-google-cpplint-load)
  )
(add-hook 'c-mode-hook 'c-c++/init-google-c-style)
(add-hook 'c++-mode-hook 'c-c++/init-google-c-style )
;; enable google-c-style
(use-package google-c-style)
(add-hook 'c-mode-common-hook 'google-set-c-style)
(add-hook 'c-mode-common-hook 'google-make-newline-indent)

Can anyone help me out?
Any partial help will be fully appreciated.

**Comment by person808** [comment]
In your `.spacemacs` look for the `dotspacemacs-additional-packages` variable and add `google-c-style`,
`flymake-google-cpplint`, and `flymake-cursor` to it. Then inside the `dotspacemacs/config` section of your `.spacemacs` add

```elisp
(use-package flymake-google-ccplint
  :defer t
  :init
  (setq flymake-google-cpplint-command "/System/Library/Frameworks/Python.framework/Versions/2.7/bin/cpplint")
  :config
  (add-hook 'c-mode-hook 'flymake-google-cpplint-load)
  (add-hook 'c++-mode-hook 'flymake-google-cpplint-load))
(use-package google-c-style
  :defer t
  :config
  (add-hook 'c-mode-common-hook 'google-set-c-style)
  (add-hook 'c-mode-common-hook 'google-make-newline-indent))
```

No need to edit the layer itself

**Comment by zhexuany** [comment]
Thanks. It looks like my problem has been solved. Thanks @person808. Btw, If  I want to learn lisp, do you have any advice?

**Comment by zhexuany** [comment]
I tried. But, still does not work. @person808 
(use-package flymake-google-ccplint
  :defer t
  :init
  (setq flymake-google-cpplint-command "/System/Library/Frameworks/Python.framework/Versions/2.7/bin/cpplint")
  :config
  (add-hook 'c-mode-hook 'flymake-google-cpplint-load)
  (add-hook 'c++-mode-hook 'flymake-google-cpplint-load))
(use-package google-c-style
  :defer t
  :config
  (add-hook 'c-mode-common-hook 'google-set-c-style)
  (add-hook 'c-mode-common-hook 'google-make-newline-indent))

**Comment by zhexuany** [comment]
I tried. But still does not wrok.
![screen shot 2015-08-08 at 8 05 50 pm](https://cloud.githubusercontent.com/assets/13320708/9153085/eea6105a-3e08-11e5-85e2-cef7f8931de6.png)

**Comment by robbyoconnor** [comment]
Why not use [flycheck](http://flycheck.org)?

**Comment by zhexuany** [comment]
@robbyoconnor  but how? flycheck is new to me.

**Comment by dzhwinter** [comment]
Just a recommand. Use syntax check layer with flycheck is better than flymake

**Comment by robbyoconnor** [comment]
@zhexuany -- flycheck is included in spacemacs ;)

**Comment by robbyoconnor** [comment]
As it stands, you're not using spacemacs properly -- This isn't a place to get generic support for emacs -- use spacemacs properly ;) 

Spend some time reading the [docs](https://github.com/syl20bnr/spacemacs/tree/develop/doc/DOCUMENTATION.org) and each layer's `README.org` file. It's REALLY a great framework...your trouble isn't necessary! Just use flycheck :D

**Comment by zhexuany** [comment]
My real question is actually how can I use google-c-style? For syntax checking, flycheck works just fine in my spacemacs.

**Comment by dzhwinter** [comment]
you can take a look at my configuration of c-c++-layer
https://github.com/dzhwinter/spacemacs-private/blob/master/c-c%2B%2B-enhance/packages.el
Please check the docs which had clearly answer your question.

**Comment by StreakyCobra** [comment]
The different issues having been answered by @person808 and @dzhwinter, I'm closing it. @zhexuany feel free to open a new one in case of trouble :smile:
