### ISSUE TITLE
using tern - getting it to work

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#2592]
# solution

This is on Ubuntu 14.04

I was having errors getting autocomplete to work for me in Javascript.
[Using NVM](https://github.com/syl20bnr/spacemacs/issues/2592#issuecomment-129226626)
enabled this to work.

After installing `nvm` just running `nvm install 0.12` [as here](https://github.com/syl20bnr/spacemacs/issues/2592#issuecomment-129233711)
did the trick, thanks :)

******

## errors

The error that I get when entering any text in a JS file is;

```
Request failed: (:failed . Could not start Tern server
/usr/bin/env: node: No such file or directory
)
```

If I enter `which tern` at the terminal I get : 

```
└─[$]› which tern
/usr/local/bin/tern
```

I'm not sure if I'm meant to have the path set to this one or what. 

I can't see anything about this in
`/home/vco/.emacs.d/elpa/company-tern-20150525.216/company-tern-pkg.el`

******

## .spacemacs

```
dotspacemacs-additional-packages '(
                                    tern-auto-complete
                                    )
```

## tern docs

From the tern docs:

> Make Emacs aware of emacs/tern.el. For example by adding this to your .emacs file:

```
(add-to-list 'load-path "/path/to/tern/emacs/")
(autoload 'tern-mode "tern.el" nil t)
```

I'm not sure where this `/path/to/tern/emacs/` is actually located. 

I've tried adding:

```
;; this is the path that was given from cmd 'which tern'
(add-to-list 'load-path "/usr/local/bin/tern")
(autoload 'tern-mode "tern.el" nil t)
```

The next thing from the emacs doc is

> Optionally set tern-mode to be automatically enabled for your JavaScript mode of
> choice. Here’s the snippet for js-mode...

But this isn't the issue; `tern-mode` *is* loaded automatically, it just doesn't
actually work.

In the tern docs it refers to `The bin/tern binary...`, so I'm not sure if
something has gone wrong with the install or what?

******

[From here](https://gitter.im/syl20bnr/spacemacs?at=55490cd12cab4b157ffc18c6) jupl mentions "*If you are using company mode you don't need to additional work*" (after [this comment](https://gitter.im/syl20bnr/spacemacs?at=55490adf52bceea22c381776) about running `npm install -g tern`). I have `company` running, as when I enter `C-h m` i can see it in the list ([here's a link to the full list of minor modes running](http://vpaste.net/NgowR))

So it's still looking in `/usr/bin/env` for the `tern` stuff? Is that the issue?

cheers

**Comment by tomprogrammer** [comment]
The error message says that the `env` helper couldn't find `node`. Do you have nodejs installed?

Without knowing anything about tern, I guess it needs nodejs to be fully functional.

**Comment by geo7** [comment]
@tomprogrammer cheers, I think that I already have it installed though, as trying to install just now gave: 

```
└─[$]› sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version.

```

**Comment by oppenlander** [comment]
Older versions of Ubuntu used to package Node.js as `nodejs` instead of `node`.  
You might be running into problems because of this.

You can try installing an updated version through the [nodesource repository](https://github.com/nodesource/distributions#installation-instructions).

**Comment by geo7** [comment]
@oppenlander thanks - I've just tried running `node` in the terminal and it doesn't work, though if I enter `nodejs` I get a JavaScript REPL that I can use... does this sound like what you're talking about? 

I guess I need to wipe everything that's `nodejs` and reinstall?

**Comment by oppenlander** [comment]
@geo7 Yes, the binary the default Ubuntu/Debian package installs is`nodejs`, which is not the standard name. 
If you install through nodesource, you should get a binary called `node` in your PATH.

You don't even need to reinstall. You just need to follow the install directions [here](https://github.com/nodesource/distributions#installation-instructions).

I don't know if this will completely fix your issues, but it will at least get you closer.

**Comment by geo7** [comment]
@oppenlander cheers I'm confused though, as when I run the command from that script I get : 


```
Reading state information... Done
nodejs is already the newest version.
```

should that be `node` ? (not `nodejs`)

**Comment by robbyoconnor** [comment]
You should use [nvm](https://github.com/creationix/nvm).

**Comment by oppenlander** [comment]
Ah, my mistake. The PPA doesn't solve the `nodejs`/`node` naming issues. 
You can either resolve this yourself, by doing something like adding a `node` to your PATH, or you can do as @robbyoconnor suggests, and use nvm.

**Comment by robbyoconnor** [comment]
You really SHOULD use nvm -- because sometimes you want and really **SHOULD** test  your app against different node versions.

**Comment by geo7** [comment]
@robbyoconnor thanks - just reading the GitHub page now :+1:

**Comment by robbyoconnor** [comment]
@geo7 it's super easy to install :-)

**Comment by geo7** [comment]
@robbyoconnor I've tried setting that up by

```sh
mkdir ~/.nvm
cd ~/.nvm

git clone https://github.com/creationix/nvm.git ~/.nvm && cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`

. ~/.nvm/nvm.sh
```

After that I've run 

```
└─[$]› nvm install 0.12
######################################################################## 100.0%
Now using node v0.12.7 (npm v2.11.3)
```

**Now** when I enter `node` in a terminal I get a prompt :) 

and 

```sh
└─[$]› node --version
v0.12.7

```


Ok! 

And now when I load up Emacs it seems to be working :)

**Comment by geo7** [comment]
@robbyoconnor  it really was! I was trying to sort things out for ages with `node` and `nodejs` etc etc `>.<`

**Comment by robbyoconnor** [comment]
:heart:
