### ISSUE TITLE
Evilify indent-rigidly-map

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#2593]
After calling `indent-rigidly` (<kbd>C-x TAB</kbd>), emacs lets you use arrow keys to control the indentation of the region. Adding <kbd>h</kbd>, <kbd>l</kbd>, <kbd>H</kbd>, and <kbd>L</kbd> to the keymap would make it more useful.

**Comment by syl20bnr** [comment]
I did not know about that, that's really nice.
Can replace https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L759-L761

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
