### ISSUE TITLE
bookmark-default-file is defined differently in two different places

### ISSUE THREAD

**Issue by travisbhartwell** [syl20bnr/spacemacs#2594]
`bookmark-default-file` and its associated `bookmark-save-flag` are set in two different places, and in the case of `bookmark-default-file`, to two different values.  I'm not seeing any bad behavior as such, but I noticed this when checking for something else.

Linking to the most recent commit, they are in:
https://github.com/syl20bnr/spacemacs/blob/88143a33faab7086c78a64d4755645b91defef5d/spacemacs/packages.el#L431-L433

and

https://github.com/syl20bnr/spacemacs/blob/88143a33faab7086c78a64d4755645b91defef5d/spacemacs/config.el#L269-L271

I would offer a pull-request but I'm unsure which is the correct place to set it.  I think putting it in the cache would be right.

**Comment by travisbhartwell** [comment]
I filed this because my bookmarks file was showing up in my recent file list and I was wondering why.

It is partially due to the fact I have the spacemacs repo checked out to `~/Projects/spacemacs` and then symlinked to `~/.emacs.d`, partially so it can show up with `magit-repository-directories`.

**Comment by syl20bnr** [comment]
The configuration in `config.el` should be moved to `init-bookmark`, the right place for this kind of file is the cache directory.
