### ISSUE TITLE
Unable to initialize flyspell mode

### ISSUE THREAD

**Issue by zhexuany** [syl20bnr/spacemacs#2597]
Please see picture for more details. 
![screen shot 2015-08-09 at 7 55 04 pm](https://cloud.githubusercontent.com/assets/13320708/9157804/b3922184-3ed0-11e5-9dc9-0d9b58b2b777.png)

**Comment by zhexuany** [comment]
Even I delete ~/.spacemas and ~/.emacs.d. Flyspell still can not be enable normally. It is so weird.

**Comment by person808** [comment]
Install `aspell` and the english dictionary using your os package manager. I know on arch the packages are `aspell` and `aspell-en`

**Comment by zhexuany** [comment]
The reason is that I did not install aspell. I installed it by using homebrew.  The following is the command:
brew install--with-lang-en aspell.

**Comment by justbur** [comment]
@syl20bnr #2553 makes it so that you don't have to install aspell
