### ISSUE TITLE
Symbolicly linking directories into contrib does not work

### ISSUE THREAD

**Issue by Wolfy87** [syl20bnr/spacemacs#26]
I have my personal overlay within my dotfiles respository, I keep that in my home directory because it's used by multiple applications. I have tried using `ln -s ~/dotfiles/emacs/Wolfy87 ~/.emacs.d/contrib/Wolfy87` but it doesn't pick any of my configuration up.

If I copy the directory in it works fine though. I'm running Arch Linux with Emacs 24.4. I'll see if I can work it out too, I'd really like to help maintain this project as I think I'm going to be using it a lot.

**Comment by syl20bnr** [comment]
I close this issue since nobody seems to have this issue anymore.
