### ISSUE TITLE
When scrolling buffers, skip ones that are located in other windows of the same frame

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#2600]
Scrolling threw buffers located in other windows with `SPC b n` (`spacemacs/next-useful-buffer`), `SPC b p` and `SPC TAB`, which usually are at the top of the buffer list, is tiresome. Skip them or change their position in the buffer list.

**Comment by syl20bnr** [comment]
#2551 partially resolve this for `SPC TAB`.

**Comment by a13ph** [comment]
Applies to microstate as well, I guess? same kind of sifting-through behavior, duplicating already visible buffers doesn't seem sought after (when you want that, you do exactly that, usually)
