### ISSUE TITLE
Consider using SVG modelines

### ISSUE THREAD

**Issue by bgamari** [syl20bnr/spacemacs#2602]
Using something like [svg-mode-line-themes]https://github.com/sabof/svg-mode-line-themes) might be an alternative to the current rather fragile situation.

**Comment by syl20bnr** [comment]
If by fragile you mean the mess in master branch regarding the powerline then it is not fragile anymore. @TheBB wrote a clean API on top of powerline in develop branch to be able to define segment and compose them into a nice to the eyes mode-line.

**Comment by sooheon** [comment]
Just for the sake of discussion, I have to say these examples are just aesthetically terrible. But I'm someone who actually disables power line and uses the emacs modeline, so...
![](https://github.com/sabof/svg-mode-line-themes/raw/master/screenshot.png)

**Comment by syl20bnr** [comment]
The bars are OK, the font style not so much.
To be able to support SVG modelines we'll need to support them with the segments.

**Comment by bgamari** [comment]
I also dislike the aesthetics of the themes offered by the package. It was the general idea that I was proposing.

**Comment by TheBB** [comment]
This is a fairly old discussion so I'm closing it now. If this is still desired the correct place to report would be to the spaceline repo. Thanks!
