### ISSUE TITLE
Powerline in develop branch still isn't quite right

### ISSUE THREAD

**Issue by bgamari** [syl20bnr/spacemacs#2606]
@syl20bnr noted in #2602 that powerline should be more robust in the `develop` branch due to a rework by @TheBB. Sadly it seems that things still aren't quite right (or there is still something wrong with my configuration, running on Debian `testing`). See the attached screenshot take with spacemacs 8ea8b65c82aa22dd100c2f2fcc3cef3b47f95191.

![emacs-powerline](https://cloud.githubusercontent.com/assets/1010174/9177090/7b42b626-3f8f-11e5-80ce-7d00299bc66c.png)

The circled K symbol looks as though it might be the culprit although I don't know why.

**Comment by syl20bnr** [comment]
Do you have `nanum-fonts` package installed in your distro ?

**Comment by bgamari** [comment]
Sylvain Benner <notifications@github.com> writes:

> Do you have `nanum-fonts` package installed in your distro ?
>
Nope.

**Comment by TheBB** [comment]
The modeline refactoring was strictly on the segment generation side. It shouldn't have caused or fixed any such problems. This looks like a font issue—you might have an inappropriate fallback for those symbols. I'm willing to bet that it looks fine if you turn the unicode symbols off—not that I'm suggesting that as a genuine workaround, of course.

**Comment by bgamari** [comment]
@TheBB how would one go about doing that?

**Comment by TheBB** [comment]
There's a setting in the dotfile for it. Just open that and search for "unicode".

**Comment by bgamari** [comment]
@TheBB indeed you are right, disabling unicode characters in the modeline does resolve the issue.

How would one go about further debugging this?

**Comment by syl20bnr** [comment]
> There's a setting in the dotfile for it. Just open that and search for "unicode".

or `SPC f e d unicode RET` :-)

**Comment by syl20bnr** [comment]
Actually one has to select the second entry...
