### ISSUE TITLE
ox-taskjuggler

### ISSUE THREAD

**Issue by chrismcv** [syl20bnr/spacemacs#2609]
Hi, 
I'm trying to get taskjuggler working.

http://orgmode.org/w/?p=org-mode.git;a=blob_plain;f=contrib/lisp/ox-taskjuggler.el;hb=HEAD

I've added `require('ox-taskjuggler)` to the contrib/org package, but this doesn't seem to yield the export mode.  

I'm rather new here, so any advice would be much appreciated.

Chris

**Comment by robbyoconnor** [comment]
Contribute back :D

**Comment by robbyoconnor** [comment]
I would be interested in this <3

**Comment by TheBB** [comment]
I'm sorry. This has been open for a month and no action. If it's still a problem, please open a new issue. Check out `doc/LAYERS.org` in the develop branch for tips on how to get stuff like this working.

**Comment by Plancalkuele** [comment]
ox-taskjuggler is included in the org-plus-contrib package.
So add org-plus-contrib to dotspacemacs-additional-packages in .spacemacs:
`
dotspacemacs-additional-packages '(org-plus-contrib)
`

The problem I have now is that I can't use the export function: http://orgmode.org/worg/exporters/taskjuggler.html
