### ISSUE TITLE
[develop] `gh` doesn't work in OrgMode files when Spacemacs freshly opened

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#2615]
As of https://github.com/syl20bnr/spacemacs/commit/350f809055d26fa4503b2bf8471650ce3c3d6661 in `develop` branch:

1. Exit and Open Spacemacs again
2. Navigate to an OrgMode file
3. Press `gh` - it says `g h is undefined`
4. Press `i` (get into insert mode) and `Esc` (back into normal mode)
5. Press `gh` - now works as expected

**Comment by robbyoconnor** [comment]
I would look to see if any commits introduced after that introduced this regression...

**Comment by TheBB** [comment]
Is this still an issue? I can't reproduce. The org layer is enabled, right?

**Comment by swaroopch** [comment]
Still happens for me. Yes, org layer is enabled.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.104.0
- Spacemacs branch: develop (rev. 21146f4)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp org)
```

**Comment by moesasji** [comment]
@BB: Bug is present for me on 0.104.4 as well, so this one can be reproduced for the current stable release. 

Note that this PR might be related to #3596 (same way to reproduce and also mention `gh`)

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.4
- Spacemacs branch: master (rev. f04bb61)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion emacs-lisp latex org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking)
```

**Comment by TheBB** [comment]
Thanks for pointing that issue out. Since it's older I will close this as a duplicate, let's move the discussion there.

This is a strange error, but I still can't repro it.

**Comment by TheBB** [comment]
Sorry, this one is the older one. :-D

**Comment by moesasji** [comment]
I switched to the development branch to check and on the develop I can't reproduce this issue. So it looks like this issue might be fixed on develop, while it is a valid bug for the 0.104 branch.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 9e5e309)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion emacs-lisp latex org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking)
```

**Comment by TheBB** [comment]
That's good. If you feel so inclined you can bisect to find out when it was fixed. I'm guessing it was in https://github.com/syl20bnr/spacemacs/commit/48edef1.

Since it sounded like it was very easily reproduced on master, I believe it's fixed so I will label it as such.

**Comment by swaroopch** [comment]
I can confirm that this is fixed in `develop`.
