### ISSUE TITLE
Solarized themes are broken in 39f508a on develop

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2628]
Commit 39f508a0a17ac92a13ec1869b0ea2dac456c4746 introduced a regression where my themes weren't loaded properly.  I traced this by manually testing each of the newest commits pushed to `develop`.

**Comment by TheBB** [comment]
> I traced this by manually testing each of the newest commits pushed to `develop`.

Just for the future, this is what `git bisect` optimises and partially automates for you. You give it a 'good' and a 'bad' commit and then it drops you off at various commits inbetween and you have to answer whether it's good or bad. After a while it tells you which commit is the first bad one.

**Comment by TheBB** [comment]
Anyway, the bug is [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-themes-support.el#L185-L186).
