### ISSUE TITLE
Graphical glitches

### ISSUE THREAD

**Issue by darker0n** [syl20bnr/spacemacs#2631]
I have some graphical glitches in bottom panel:

![screen shot 2015-08-12 at 10 54 32](https://cloud.githubusercontent.com/assets/11329474/9219085/eb11735a-40e0-11e5-9ef5-a0c382fa3722.png)
![screen shot 2015-08-12 at 10 54 10](https://cloud.githubusercontent.com/assets/11329474/9219086/eb190e4e-40e0-11e5-9914-0655986e2cc1.png)
![screen shot 2015-08-12 at 10 53 46](https://cloud.githubusercontent.com/assets/11329474/9219087/eb281038-40e0-11e5-81fd-28fad9d234e3.png)

**Comment by TheBB** [comment]
Is this on develop or master?

**Comment by syl20bnr** [comment]
Can you provide more info on your environment ?
If you are on OS X you can consider this FAQ: https://github.com/syl20bnr/spacemacs#os-x-1

**Comment by darker0n** [comment]
Yes, it's helped me: https://github.com/milkypostman/powerline/issues/54
Thank you very much
