### ISSUE TITLE
Spacemacs Freezing in El Capitan Os x

### ISSUE THREAD

**Issue by hamhut1066** [syl20bnr/spacemacs#2632]
After installing emacs using the recommended method, and using the default spacemacs config file,

Emacs freezes as soon as it reaches _ready_ state.

I have attempted to run with `--debug-init` yet I have not received any additional information through this.

**Comment by ivanbokii** [comment]
Have the same issue. Launched it without any problems a couple of times, on all next attempts freezes right after the start.

**Comment by cmccloud** [comment]
@ivanbokii are you also using the emacs macport? 
@hamhut1066 do you get the same behavior when using emacs installed via http://emacsformacosx.com/ ?

**Comment by ivanbokii** [comment]
@cmccloud yes, macport. Just tried to use emacsformacosx and it has the same problem

**Comment by hamhut1066** [comment]
Have you moved to using the Xcode7-beta? `sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer`.

I found this would at least stop the freeze from breaking permanently.
I was still waiting around 30-40 seconds before I could do anything with emacs.

Additional _emacsclient_ connections were instant though, and I didn't come across any major issues.
I did have to strip out all of my layers and add them incrementally. Some didn't work at all.

**Comment by ivanbokii** [comment]
@hamhut1066 I didn't install Xcode at all

**Comment by lucca65** [comment]
+ 1 on this

**Comment by mclearc** [comment]
I've been using el cap and spacemacs has been working fine *except* when I try and download additional packages using the `dotspacemacs-additional-packages` section. It will freeze on update of the `.spacemacs` file and I will have to force quit and restart, upon which time it downloads the package and works fine. I'm now on ElCap GM.

**Comment by koppa** [comment]
I'm also experiencing the same? issue under archlinux.
With CTRL-g I am able to regain control.

Setup is pretty vanilla. Emacs version 24.5.1.

**Comment by BirdEggegg** [comment]
+1 spacemacs 0.104.2 freezing after starting up on El Capitan.

**Comment by avovsya** [comment]
+1 for the bug. 
Spacemacs 0.104.2 with "vanilla" config
Tried with: 
brew emacs, brew emacs-mac, and http://emacsformacosx.com.

**Comment by d12frosted** [comment]
@ivanbokii wow, is it possible to install command-line-tools without Xcode?

**Comment by hamhut1066** [comment]
@d12frosted should be, I think they have been allowing it for a while now.

Re: bug. Are people running beta, or stable?

**Comment by d12frosted** [comment]
@hamhut1066 didn't know about it - I usually install Xcode first and then CLT :smile: 

Re: bug. I am running stable. Currently `10.11.1 (15B42)`.

**Comment by mclearc** [comment]
I am now seeing this happen repeatedly. Sometimes 4 or 5 times in one afternoon. I'm on the El Cap most recent public beta (10.11.2 Beta (15C27e)). I am using the homebrew railwaycat version.


#### System Info
- OS: darwin: 10.11.2 Beta (15C27e)
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 0567f5c)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion deft emacs-lisp eyebrowse games git helm-bibtex latex markdown org osx pandoc pdf-tools
                 (ranger :variables ranger-show-preview t)
                 (shell :variables shell-default-term-shell "/usr/local/bin/zsh" shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
                 shell-scripts spell-checking sr-speedbar syntax-checking themes-megapack version-control yaml)
```

**Comment by nixmaniack** [comment]
@d12frosted I just have CLT and no Xcode.

**Comment by magicmonty** [comment]
I have the same problem. However, if I check my processes with `ps ax`then I get the following entry:
```
94564   ??  Ss     0:00.01 /usr/bin/ssh -o ControlPath=%C host.does.not.exist
```

If I kill this process, then emacs runs normally. This seems to be related to the following entries, which appear shortly before:
```
95174   ??  Ss     0:00.00 /usr/local/bin/git fetch checkversion
95175   ??  R      0:00.04 git-remote-https checkversion https://github.com/syl20bnr/spacemacs
```

**Comment by StreakyCobra** [comment]
@magicmonty I'm pretty sure your issue is [helm/1000](https://github.com/emacs-helm/helm/issues/1000#issuecomment-119293891), the solution is given it [the FAQ](https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-is-spacemacs-hanging-on-startup)

All other people having the problem, can you also try the FAQ's solution?

**Comment by magicmonty** [comment]
@StreakyCobra Yeah, that fixed it for me. Thanks

**Comment by spencerlyon2** [comment]
Also worked for me, thanks @StreakyCobra

**Comment by d12frosted** [comment]
@StreakyCobra ultimate solution is `helm/1000`. I like that number. The number of issues it fixes :-P

**Comment by StreakyCobra** [comment]
@d12frosted Indeed :-)

Does this solve the problem for other people? or not?

**Comment by olivierverdier** [comment]
For me it does not solve the problem.

I can reproduce the freezing completely reliably:
Start emacs, wait until initialization is finished (or don't wait). Hit `SPC b b`: freeze.

(It does not freeze if I first move the cursor, so emacs is still usable, but it inevitably freezes at some later point).

System info (Mac OS 10.11.3, emacs installed via `brew install emacs --with-cocoa --with-librsvg`)
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion colors coq cscope deft emacs-lisp
                 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
                 fasd git gtags haskell html ipython-notebook javascript markdown org python ranger search-engine semantic shell-scripts spell-checking syntax-checking themes-megapack unimpaired
                 (latex :variables latex-enable-auto-fill nil latex-build-command "LaTeX")
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (theming :variables theming-headings-inherit-from-default 'all theming-headings-same-size 'all theming-headings-bold 'all)
                 version-control yaml)
```
What is more, I tracked down the offending line in my `.spacemacs`, it is:
```elisp
(setq powerline-default-separator nil)
```
(Perhaps @theBB could help?)

My full config file is at https://github.com/olivierverdier/dotspacemacs
(You will have to remove the `coq` layer, which is a private one, but the freezing still occurs)

Feel free to move (or to tell me to move) that bug report elsewhere if needed.

**Comment by StreakyCobra** [comment]
> (setq powerline-default-separator nil)

By reading this, I just tilted: https://github.com/syl20bnr/spacemacs/issues/3090#issuecomment-174306045

@TheBB As milkypostman said on the other thread it's not a `powerline` issue. It is possible we have an issue with this variable set to `nil` in spacemacs.

**Comment by olivierverdier** [comment]
Ah, thanks a lot, that is indeed what is already reported #3090.

**Comment by TheBB** [comment]
I can't reproduce this problem with `powerline-default-separator` as `nil`, either. Although I will have a look through the Spaceline source code and see if I make any assumptions about it.

**Comment by olivierverdier** [comment]
In light of #3090, some more information: if I try to set any other variable to `nil`, no freeze occurs after loading. So it seems to be specific to `powerline-default-separator`.

**Comment by yilihong** [comment]
still hangs as of now when I compile a latex file. any ideas?

**Comment by hamhut1066** [comment]
I think this bug report has become a meta (something has frozen and I'm running OS X) issue.

I'll close it in a week unless there is a reason to keep it around

**Comment by syl20bnr** [comment]
To prevent this thread from evolving further I'll shut it down, after being "meta" who knows in what form it could evolve.
