### ISSUE TITLE
YaSnippet unable to open file with `f2`

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#2633]
## error

When trying to open snippet from `SPC i s` (`spacemacs/helm-yas`) with `f2` (found in the menu from running `C-z` within `spacemacs/helm-yas`) the following error is given:

```
not found snippet file
```

## spacemacs version

I'm on commit ; 

```
commit ba47013e3250fb32dc0bb62c5f444916192ad072
Author: syl20bnr <sylvain.benner@gmail.com>
Date:   Mon Aug 10 09:11:14 2015 -0400
```

## snippets file

I'm not sure if this is related but; 

Yesterday I had to add the directory `~/.emacs.d/snippets` as I was getting an error when trying to reload snippets. 

If I remove this directory and try to run the command `yas-recompile-all` I get the error: 

```
yas--subdirs: Opening directory: no such file or directory, /home/vco/.emacs.d/snippets
```

Adding the `.emacs.d/snippets` directory prevents this error, but I'm not sure if `yas` is trying to find snippets from `f2` above using this directory I've created. 

*******

**Comment by StreakyCobra** [comment]
@geo7 Do you still have this error? I can't reproduce it :-(

**Comment by geo7** [comment]
@StreakyCobra I'll have a look when I get back later. I've a *feeling* that it's now working alright, though whether that's anything ot do with the reloaction of my yas snippets directory I'm not too sure (from .emacs.d to ~/dotfiles), If yours are in the deault (.emacs.d) location then perhaps the issue has sorted itself out! 

I'll close this now and reopen if I find it's not working. 

cheers.

**Comment by StreakyCobra** [comment]
Ok, let me know and feel free to reopen it in any case :relaxed:

**Comment by geo7** [comment]
:+1:
