### ISSUE TITLE
Error (use-package): holy-mode :init: Symbol's value as variable is void: evil-evilified-state--modes

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#2639]
On latest develop.

**Comment by syl20bnr** [comment]
I was not able to reproduce it but I fixed the last occurrence of this variable, hopefully it will fix the issue.

**Comment by tuhdo** [comment]
It turned out that it was an old compiled `holy-mode.elc` in `extensions/holy-mode/`. I deleted it and everything is fine now.
