### ISSUE TITLE
spacemacs used too much mem in Windows10 when install a new package 

### ISSUE THREAD

**Issue by wogaokui** [syl20bnr/spacemacs#2646]
When i act a new layer , it will install some new package. At this time, the mem spacemacs used grows fast . It can use more than 2g mem.

**Comment by ralesi** [comment]
I don't see this issue with windows 10 64 bit.  What version of Emacs are you using?

**Comment by Devagamster** [comment]
I too use spacemacs on win 10. No issue for me either.

**Comment by wogaokui** [comment]
24.5 , now it's ok now , But it also use more than 1g mem when install a new package !

**Comment by syl20bnr** [comment]
I experienced this once when using version from http://emacsbinw64.sourceforge.net/
I then sticked with version https://plus.google.com/+FabricePopineau/posts/TffBNwirXGH
Had no problem with it.

**Comment by syl20bnr** [comment]
Note: it was on Win7 not Win10

**Comment by fiveNinePlusR** [comment]
probably should be closed
