### ISSUE TITLE
spacemacs/quick-ahs-backward error in org-mode

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#265]
Calling `spacemacs/quick-ahs-backward` with `#` or `*` in an `org-mode` buffer returns the following error:
`ahs-decorated-current-plugin-name: Wrong type argument: stringp, none`

The same functions work fine in other modes.

**Comment by syl20bnr** [comment]
Fixed by c21bd2d2cf965e32be3eac4239b3b97795969e61
