### ISSUE TITLE
Pinging clock.be (The Kingdom of Belgium)...

### ISSUE THREAD

**Issue by aviralg** [syl20bnr/spacemacs#2654]
In the screenshot below, I have a `clock` object with a method named `begin`.  Now when I type `clock.be` and then press tab,  I get stuck with the following message in minibuffer -
    
     Pinging clock.be (The Kingdom of Belgium)...

![spacemacs-bug](https://cloud.githubusercontent.com/assets/4531751/9270778/eed1d590-4291-11e5-8280-01e037fc9b49.png)

**Comment by bmag** [comment]
Sounds a lot like this [reddit thread](https://www.reddit.com/r/emacs/comments/3cpoys/uh_do_what_you_need_to_do_i_guess/) and this [issue](https://github.com/technomancy/emacs-starter-kit/issues/39). Does adding this line to your `dotspacemacs/config` solve the problem? (taken from https://github.com/technomancy/emacs-starter-kit/issues/39#issuecomment-323467)
```elisp
(setq ffap-machine-p-known 'reject)
```
If it doesn't solve the issue, can you post the value of `company-backends`? (use <kbd>SPC h d v company-backends</kbd> to find it)

**Comment by syl20bnr** [comment]
That's a funny bug :space_invader:

**Comment by aviralg** [comment]
Actually if I write 

    clock.in

then it pings my country, `India`

**Comment by robbyoconnor** [comment]
This is so cute! I love this bug...kinda.

**Comment by aviralg** [comment]
@bmag I did as you said in my dotspacemacs/config. I am not able to reproduce the issue now. 
Thanks.

**Comment by syl20bnr** [comment]
Maybe we need to set as default. I need to investigate what this variable does first though :-)

**Comment by StreakyCobra** [comment]
I can not reproduce this bug. Is it still valid?

**Comment by robbyoconnor** [comment]
I've reproduced this recently... I don't remember how

**Comment by TheBB** [comment]
I have too. I also don't remember how, but I fixed it as advertised in this thread.

**Comment by StreakyCobra** [comment]
@TheBB Should this fix be included in Spacemacs?

**Comment by TheBB** [comment]
I'm not sure but leaning towards... yes?

**Comment by robbyoconnor** [comment]
Is it currently in spacemacs?

**Comment by StreakyCobra** [comment]
`SPC p p spacemacs C-s ffap-machine` tell me that… no :smile:

**Comment by robbyoconnor** [comment]
Leave this issue open until it is actually fixed then :P

**Comment by StreakyCobra** [comment]
It's why I asked if we should fix it in Spacemacs :stuck_out_tongue:

**Comment by robbyoconnor** [comment]
FYI I hit this while coding this weekend.

**Comment by StreakyCobra** [comment]
I think this is a bad default. We can probably use what's proposed in [this mail](https://lists.gnu.org/archive/html/emacs-devel/2008-01/msg01453.html), and document in the FAQ how to revert it.

**Comment by syl20bnr** [comment]
Almost one year later, should be fixed in develop :-)

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
