### ISSUE TITLE
Navigating links in *Help* buffer loses focus

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#2659]
Whenever a *Help* buffer pops up, it has focus at first by default, to make it easy to escape with a single `q` keypress. However, if you navigate to a link and press enter, your point will move to another window, and the new *Help* window will not have focus. This breaks flow, because you can't keep navigating through links, and you can't easily close the window.

**Comment by sooheon** [comment]
I've found that `(setq help-window-select 't)` resolves this issue. @syl20bnr, what do you think about adding this to spacemacs config.el?

**Comment by syl20bnr** [comment]
Testing it... I' m not sure to understand the use case :-)

**Comment by syl20bnr** [comment]
I don't see any difference, can you provide a repro step ?

**Comment by sooheon** [comment]
On spacemacs develop branch with no personal layers settings:

1. `q` to dismiss spacemacs-buffer
2. `C-h v emacs-lisp-mode-map` to open a help buffer
3. `o b` to select a link, now point moves to scratch buffer. The desired behaviour is that point stays in help.

Eval `(setq help-window-select t)` and repeat above steps, you will see that traversing links keeps point in help buffer, so you can dismiss at any time with q, and go back and forth in history easily.

**Comment by syl20bnr** [comment]
Ok I understand now, this is nice, we can add it.
For the issue of the changing layout (when pression `ob` on a vertically split layout, the layout changes from 3 windows to 2 windows) I think we will be able to stabilize it with windows purpose package (planned to be configured for 0.105.0).

**Comment by mkcode** [comment]
:+1: - This has slightly annoyed me for a while as well. Thanks @sooheon
