### ISSUE TITLE
The latest versions don't have c/c++ layer, how can i add layer for c or c++

### ISSUE THREAD

**Issue by wogaokui** [syl20bnr/spacemacs#2664]

**Comment by sooheon** [comment]
Here you go:
https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/c-c%2B%2B

Find it in emacs with `space f e c !lang c-c++`

**Comment by syl20bnr** [comment]
This is `c-c++` layer not `c/c++` ;-)

**Comment by beta1440** [comment]
This issue should be closed.

**Comment by d12frosted** [comment]
Closing this issue as the question was answered. 

Thanks @beta1440 for pinging. 😸
