### ISSUE TITLE
How to display current-input-method-title in mode line?

### ISSUE THREAD

**Issue by joonhwan** [syl20bnr/spacemacs#2671]
Hi, spacemacs newbie. How do i display `current-input-method-title` in my mode line by which i'm noted which input method currently being used(i.e, in my non-spacemacs environment, I've used `toggle-input-method` in my daily uses to switch between English and Korean, and whenever I started using korean-hangul input method, mode line displayed `current-input-method-title` there)

Any help or hint would be appreciated.

**Comment by TheBB** [comment]
https://github.com/TheBB/spaceline/issues/45

**Comment by lunaryorn** [comment]
@joonhwan I'd appreciate if you could test https://github.com/TheBB/spaceline/pull/47 and provide feedback for it.

**Comment by TheBB** [comment]
This was implemented upstream. Should be out on MELPA soonish.
