### ISSUE TITLE
Scroll Images in Emacs

### ISSUE THREAD

**Issue by aviralg** [syl20bnr/spacemacs#2673]
I opened a jpeg file in Emacs. I am unable to use `j` and `k` to scroll down and up.  In Helm `S-SPC` is listed as the keybinding for `image-scroll-down`. That does not work. I tried scrolling via standard emacs keybindings for going up and down in a file. They also refuse to work.

**Comment by syl20bnr** [comment]
I'm not sure if it is possible to do this, Emacs has no per pixel scrolling support I believe (except for some special builds like brew emacs-mac).

**Comment by aviralg** [comment]
@syl20bnr So if the image is big, there is no way for me to see it at 100%? I will have to minimize it to fit the buffer ? But then,  I remember seeing images in an org file and I was able to scroll through the document without any problem.

**Comment by a13ph** [comment]
`SPC h d d` "scale image" group of symbols might help somewhat. I even wonder why scaling down is not default behavior
