### ISSUE TITLE
Evil mode nonfunctional in `whitespace-report` buffer

### ISSUE THREAD

**Issue by aviralg** [syl20bnr/spacemacs#2674]
**OS: Lubuntu 15.04**
**WM: XMonad**
**Emacs: 24.5.1** (manually compiled)

When I execute `whitespace-report` and navigate to the new window in which the buffer opens, evil mode stops working.

**Comment by TheBB** [comment]
Could be related to #2665.

**Comment by bmag** [comment]
If #2665 is indeed the issue here, please see solution in https://github.com/syl20bnr/spacemacs/issues/2665#issuecomment-132325427

**Comment by TheBB** [comment]
This is fixed by upstream.
