### ISSUE TITLE
Undo granularity with insert-mode operation?

### ISSUE THREAD

**Issue by demon386** [syl20bnr/spacemacs#2675]
Let's say I type in insert-mode, with company-mode's hints and completion. Then if I enter normal mode and press "u" to undo things, in Vim it's my whole operation in this one insert-mode, but in spacemacs it would be multiple ones. (probably split by company-mode's triggers).

Any possibility to keep the granularity the same as Vim's?

**Comment by mkcode** [comment]
@demon386 - You probably want

```
(setq evil-want-fine-undo nil)
```
From the docs:

```
evil-want-fine-undo is a variable defined in `evil-vars.el'.
Its value is fine

Documentation:
Whether actions like "cw" are undone in several steps.
There are three possible choices. "No" means all chances made
during insert state including a possible delete after a change
operation are collected in a single undo step. If "Fine" is
selected, insertion commands create several undo steps as Emacs
would do and the delete after a change operation is merged with
the first undo step of the insertion. "Very fine" is the same
but the delete operation is a separate undo step.
```

**Comment by demon386** [comment]
@mkcode 

Work like a charm! Thanks a lot!

**Comment by rakyi** [comment]
IMHO `(setq evil-want-fine-undo nil)` should be default when using evil-mode.

**Comment by viccuad** [comment]
> IMHO (setq evil-want-fine-undo nil) should be default when using evil-mode.

++

**Comment by a13ph** [comment]
Setting it as default would be more similar to vim, but i'd argue that this constitutes loss of additional information, so care should be applied if this decision arises.

Most unreasonably perfect solution would be to write two undo logs with different granularity and on-the fly change which undo log to read from
