### ISSUE TITLE
Spacemacs launches vanilla emacs after an out of range font value in .spacemacs

### ISSUE THREAD

**Issue by etergo** [syl20bnr/spacemacs#2678]
Hi,

I just installed spacemacs today and am configuring it (I am on OSX with a fresh homebrew version of emacs). I entered a value that was obviously wrong when replacing the default font and emacs launched as vanilla emacs. I went back and restored the value to one I knew worked and it still wont run as spacemacs.

**Comment by syl20bnr** [comment]
Hi,

I need more info, like the stack trace when launching emacs with `emacs --debug-init`.
Also what were the values you put for font ?

**Comment by etergo** [comment]
Hi,

Thanks for the response. After playing around for a few hours I saw that I had actually changed another part of my .spacemacs in an earlier edit without reloading it and so when this happened I was blaming the problem on the wrong edit. 

Sorry to have wasted your time, but I just couldn't make sense of it. That --debug-init flag will probably be helpful in the future. By the way, after a few more days of playing with it I have decided to make the switch from vim. I can see that you have an owner tag and just wanted to say that it's really well done so thanks!

**Comment by TheBB** [comment]
This can be closed, then?

**Comment by etergo** [comment]
Yep.

**Comment by TheBB** [comment]
Then do it, please. :-)
