### ISSUE TITLE
Diminish feature of use-package macro doesn't work properly with private-layer

### ISSUE THREAD

**Issue by farseer90718** [syl20bnr/spacemacs#2683]
Specifically, auto-dim-other-buffers-mode & color-identifiers-mode added in my private-layer won't be affected. And if I add `(diminish foo bar)` explicitly to the init part of use-package, emacs will complain about not finding function named diminish, so I guess the reason may be these sub-mode packages are alphabetically less than "diminish" so that they are loaded before it ?

**Comment by person808** [comment]
I think `diminish` should be part of `:config` not `:init`. Use-package also has a built-in `:diminish` keyword

**Comment by farseer90718** [comment]
@person808 I mean the `:diminish` keyword doesn't take effect. neither `:config` nor `:init`, since the diminish package isn't loaded at that time.

**Comment by person808** [comment]
Thats odd. I'm pretty sure the `:diminish` keyword automatically requires `diminish`. Anyway, you could do `(with-eval-after-load 'diminish (diminish foo bar))`

**Comment by farseer90718** [comment]
@person808 That works well, many thanks!

**Comment by TheBB** [comment]
> Thats odd. I'm pretty sure the `:diminish` keyword automatically requires `diminish`.

It doesn't, you can check with `macroexpand`. You'll get something like this:

    (if (fboundp (quote diminish))
        (diminish (quote smartparens-mode)))
