### ISSUE TITLE
Ranger not updating file preview automatically?

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#2687]
Not sure if this is an issue with Ranger or with Spacemacs, or something went wrong with my machine's configurations. Anyways, the file preview in Ranger is not updated when I am browsing using `j` and `k`. I have to press `i` twice, or press `L`, in order to show the content of the file I'm currently pointing at, otherwise the previous file's content will remain on the right.

**Comment by x-ji** [comment]
Seems to be caused by `vinegar`'s evilification of `dired` buffers. https://github.com/ralesi/ranger/issues/30

**Comment by ralesi** [comment]
This is now fixed by explicitely specifying normal state in ranger.  Ranger and vinegar should now be able to coexist.
