### ISSUE TITLE
evil-indent-textobjects fork is causing an error when installing

### ISSUE THREAD

**Issue by mahinshaw** [syl20bnr/spacemacs#2688]
Refers to #2656.  When updating spacemacs, evil-indent-textobject throws an error when installing

using version - `GNU Emacs 24.5.1 (x86_64-w64-mingw32) of 2015-04-12 on KAEL`

```
Debugger entered--Lisp error: (error "Package lacks a \"Version\" or \"Package-Version\" header")
  signal(error ("Package lacks a \"Version\" or \"Package-Version\" header"))
  error("Package lacks a \"Version\" or \"Package-Version\" header")
  package-buffer-info()
  byte-code("\303\304!rq\210\305\216\306	!\210\n\307=\203\310 \2024
  quelpa-get-package-desc("c:/Users/Mark/.emacs.d/.cache/quelpa/packages/evil-indent-textobject-20140918.707.el")
  quelpa-package-install((evil-indent-textobject :fetcher github :repo "TheBB/evil-indent-textobject"))
  quelpa((evil-indent-textobject :fetcher github :repo "TheBB/evil-indent-textobject"))
  (if recipe (quelpa recipe) (spacemacs-buffer/warning (concat "Cannot find any recipe for package %S! Be sure " "to add a recipe for it in alist %S.") pkg-name recipes-var))
  (let* ((pgk-name (eieio-oref pkg (quote :name))) (layer (eieio-oref pkg (quote :owner))) (recipe (cons pkg-name (cdr (eieio-oref pkg (quote :location)))))) (if recipe (quelpa recipe) (spacemacs-buffer/warning (concat "Cannot find any recipe for package %S! Be sure " "to add a recipe for it in alist %S.") pkg-name recipes-var)))
  configuration-layer//install-from-recipe([object cfgl-package "evil-indent-textobject" evil-indent-textobject spacemacs nil nil (recipe :fetcher github :repo "TheBB/evil-indent-textobject") nil nil])
  (cond ((or (null pkg) (eq (quote elpa) location)) (configuration-layer//install-from-elpa pkg-name)) ((and (listp location) (eq (quote recipe) (car location))) (configuration-layer//install-from-recipe pkg)) (t (spacemacs-buffer/warning "Cannot install package %S." pkg-name)))
  (condition-case err (cond ((or (null pkg) (eq (quote elpa) location)) (configuration-layer//install-from-elpa pkg-name)) ((and (listp location) (eq (quote recipe) (car location))) (configuration-layer//install-from-recipe pkg)) (t (spacemacs-buffer/warning "Cannot install package %S." pkg-name))) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append (format (concat "An error occurred while installing %s " "(error: %s)\n") pkg-name err))))
  (if (package-installed-p pkg-name) nil (condition-case err (cond ((or (null pkg) (eq (quote elpa) location)) (configuration-layer//install-from-elpa pkg-name)) ((and (listp location) (eq (quote recipe) (car location))) (configuration-layer//install-from-recipe pkg)) (t (spacemacs-buffer/warning "Cannot install package %S." pkg-name))) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append (format (concat "An error occurred while installing %s " "(error: %s)\n") pkg-name err)))))
  (let* ((pkg (object-assoc pkg-name :name configuration-layer-packages)) (layer (if pkg (progn (eieio-oref pkg (quote :owner))))) (location (if pkg (progn (eieio-oref pkg (quote :location)))))) (spacemacs-buffer/replace-last-line (format "--> installing %s%s... [%s/%s]" (if layer (format "%S:" layer) "dependency ") pkg-name installed-count noinst-count) t) (if (package-installed-p pkg-name) nil (condition-case err (cond ((or (null pkg) (eq (quote elpa) location)) (configuration-layer//install-from-elpa pkg-name)) ((and (listp location) (eq (quote recipe) (car location))) (configuration-layer//install-from-recipe pkg)) (t (spacemacs-buffer/warning "Cannot install package %S." pkg-name))) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append (format (concat "An error occurred while installing %s " "(error: %s)\n") pkg-name err))))))
  (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (let* ((pkg (object-assoc pkg-name :name configuration-layer-packages)) (layer (if pkg (progn (eieio-oref pkg (quote :owner))))) (location (if pkg (progn (eieio-oref pkg (quote :location)))))) (spacemacs-buffer/replace-last-line (format "--> installing %s%s... [%s/%s]" (if layer (format "%S:" layer) "dependency ") pkg-name installed-count noinst-count) t) (if (package-installed-p pkg-name) nil (condition-case err (cond ((or (null pkg) (eq ... location)) (configuration-layer//install-from-elpa pkg-name)) ((and (listp location) (eq ... ...)) (configuration-layer//install-from-recipe pkg)) (t (spacemacs-buffer/warning "Cannot install package %S." pkg-name))) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append (format (concat "An error occurred while installing %s " "(error: %s)\n") pkg-name err)))))) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- noinst-pkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (let* ((pkg (object-assoc pkg-name :name configuration-layer-packages)) (layer (if pkg (progn (eieio-oref pkg ...)))) (location (if pkg (progn (eieio-oref pkg ...))))) (spacemacs-buffer/replace-last-line (format "--> installing %s%s... [%s/%s]" (if layer (format "%S:" layer) "dependency ") pkg-name installed-count noinst-count) t) (if (package-installed-p pkg-name) nil (condition-case err (cond ((or ... ...) (configuration-layer//install-from-elpa pkg-name)) ((and ... ...) (configuration-layer//install-from-recipe pkg)) (t (spacemacs-buffer/warning "Cannot install package %S." pkg-name))) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append (format ... pkg-name err)))))) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (progn (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" noinst-count)) (spacemacs-buffer/append "--> fetching new package repository indexes...\n") (spacemacs//redisplay) (package-refresh-contents) (setq installed-count 0) (let ((--dolist-tail-- noinst-pkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (let* ((pkg (object-assoc pkg-name :name configuration-layer-packages)) (layer (if pkg (progn ...))) (location (if pkg (progn ...)))) (spacemacs-buffer/replace-last-line (format "--> installing %s%s... [%s/%s]" (if layer (format "%S:" layer) "dependency ") pkg-name installed-count noinst-count) t) (if (package-installed-p pkg-name) nil (condition-case err (cond (... ...) (... ...) (t ...)) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append ...))))) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n"))
  (if noinst-pkg-names (progn (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" noinst-count)) (spacemacs-buffer/append "--> fetching new package repository indexes...\n") (spacemacs//redisplay) (package-refresh-contents) (setq installed-count 0) (let ((--dolist-tail-- noinst-pkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (let* ((pkg (object-assoc pkg-name :name configuration-layer-packages)) (layer (if pkg ...)) (location (if pkg ...))) (spacemacs-buffer/replace-last-line (format "--> installing %s%s... [%s/%s]" (if layer ... "dependency ") pkg-name installed-count noinst-count) t) (if (package-installed-p pkg-name) nil (condition-case err (cond ... ... ...) (... ... ...)))) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n")))
  (let* ((candidates (configuration-layer/filter-packages packages (function (lambda (x) (and (not ...) (not ...) (not ...)))))) (noinst-pkg-names (configuration-layer//get-uninstalled-packages (mapcar (quote car) (object-assoc-list :name candidates)))) (noinst-count (length noinst-pkg-names))) (if noinst-pkg-names (progn (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" noinst-count)) (spacemacs-buffer/append "--> fetching new package repository indexes...\n") (spacemacs//redisplay) (package-refresh-contents) (setq installed-count 0) (let ((--dolist-tail-- noinst-pkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (let* ((pkg ...) (layer ...) (location ...)) (spacemacs-buffer/replace-last-line (format "--> installing %s%s... [%s/%s]" ... pkg-name installed-count noinst-count) t) (if (package-installed-p pkg-name) nil (condition-case err ... ...))) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n"))))
  configuration-layer//install-packages(([object cfgl-package "ac-ispell" ac-ispell auto-completion nil nil elpa nil nil] [object cfgl-package "ace-link" ace-link spacemacs nil nil elpa nil nil] [object cfgl-package "ace-window" ace-window spacemacs nil nil elpa nil nil] [object cfgl-package "adaptive-wrap" adaptive-wrap spacemacs nil nil elpa nil nil] [object cfgl-package "aggressive-indent" aggressive-indent spacemacs nil nil elpa nil nil] [object cfgl-package "align-cljlet" align-cljlet clojure nil nil elpa nil nil] [object cfgl-package "auto-complete" auto-complete auto-completion nil nil elpa nil nil] [object cfgl-package "auto-dictionary" auto-dictionary spacemacs nil nil elpa nil nil] [object cfgl-package "auto-highlight-symbol" auto-highlight-symbol spacemacs nil nil elpa nil nil] [object cfgl-package "auto-yasnippet" auto-yasnippet auto-completion nil nil elpa nil nil] [object cfgl-package "avy" avy spacemacs nil nil elpa nil nil] [object cfgl-package "bind-key" bind-key spacemacs nil nil elpa nil nil] [object cfgl-package "bookmark" bookmark spacemacs nil nil elpa nil nil] [object cfgl-package "buffer-move" buffer-move spacemacs nil nil elpa nil nil] [object cfgl-package "centered-cursor" centered-cursor spacemacs nil nil local nil nil] [object cfgl-package "cider" cider clojure nil nil elpa nil nil] [object cfgl-package "cider-eval-sexp-fu" cider-eval-sexp-fu clojure nil nil elpa nil nil] [object cfgl-package "clean-aindent-mode" clean-aindent-mode spacemacs nil nil elpa nil nil] [object cfgl-package "clj-refactor" clj-refactor clojure nil nil elpa nil nil] [object cfgl-package "clojure-mode" clojure-mode clojure nil nil elpa nil nil] [object cfgl-package "coffee-mode" coffee-mode javascript nil nil elpa nil nil] [object cfgl-package "company" company auto-completion (shell) (clojure csharp emacs-lisp html javascript) elpa nil nil] [object cfgl-package "company-quickhelp" company-quickhelp auto-completion nil nil elpa nil nil] [object cfgl-package "company-statistics" company-statistics auto-completion nil nil elpa nil nil] [object cfgl-package "company-tern" company-tern javascript nil nil elpa nil nil] [object cfgl-package "company-web" company-web html nil nil elpa nil nil] [object cfgl-package "css-mode" css-mode html nil nil elpa nil nil] [object cfgl-package "define-word" define-word spacemacs nil nil elpa nil nil] [object cfgl-package "desktop" desktop spacemacs nil nil elpa nil nil] [object cfgl-package "diff-hl" diff-hl version-control nil nil elpa nil nil] [object cfgl-package "diff-mode" diff-mode version-control nil nil elpa nil nil] [object cfgl-package "diminish" diminish spacemacs nil nil elpa nil nil] [object cfgl-package "doc-view" doc-view spacemacs nil nil elpa nil nil] [object cfgl-package "ediff" ediff spacemacs nil nil elpa nil nil] [object cfgl-package "eldoc" eldoc spacemacs nil (emacs-lisp) elpa nil nil] [object cfgl-package "elisp-slime-nav" elisp-slime-nav emacs-lisp nil nil elpa nil nil] [object cfgl-package "emacs-builtin-emacs-lisp" emacs-builtin-emacs-lisp emacs-lisp nil nil local post nil] [object cfgl-package "emacs-builtin-process-menu" emacs-builtin-process-menu spacemacs nil nil local nil nil] [object cfgl-package "emmet-mode" emmet-mode html nil nil elpa nil nil] [object cfgl-package "esh-help" esh-help shell nil nil elpa nil nil] [object cfgl-package "eshell" eshell shell nil nil elpa nil nil] [object cfgl-package "eshell-prompt-extras" eshell-prompt-extras shell nil nil elpa nil nil] [object cfgl-package "eval-sexp-fu" eval-sexp-fu spacemacs nil nil elpa nil nil] [object cfgl-package "evil" evil spacemacs nil (emacs-lisp) elpa nil nil] [object cfgl-package "evil-anzu" evil-anzu spacemacs nil nil elpa nil nil] [object cfgl-package "evil-args" evil-args spacemacs nil nil elpa nil nil] [object cfgl-package "evil-commentary" evil-commentary evil-commentary nil nil elpa nil nil] [object cfgl-package "evil-escape" evil-escape spacemacs nil nil elpa nil nil] [object cfgl-package "evil-exchange" evil-exchange spacemacs nil nil elpa nil nil] [object cfgl-package "evil-iedit-state" evil-iedit-state spacemacs nil nil elpa nil nil] ...))
  (let ((layers (reverse configuration-layer-layers)) (warning-minimum-level :error)) (configuration-layer//set-layers-variables layers) (configuration-layer//load-layers-files layers (quote ("funcs.el" "config.el"))) (configuration-layer//load-layers-files layers (quote ("packages.el" "extensions.el"))) (setq configuration-layer-packages (configuration-layer//sort-packages (configuration-layer/get-packages layers t))) (setq spacemacs-loading-dots-chunk-threshold (/ (configuration-layer/configured-packages-count) spacemacs-loading-dots-chunk-count)) (configuration-layer//install-packages configuration-layer-packages) (configuration-layer//configure-packages configuration-layer-packages) (configuration-layer//load-layers-files layers (quote ("keybindings.el"))))
  configuration-layer/load-layers()
  configuration-layer/sync()
  (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (require (quote core-configuration-layer)) (spacemacs/init) (configuration-layer/sync) (spacemacs/setup-startup-hook) (spacemacs/maybe-install-dotfile) (require (quote server)) (if (server-running-p) nil (server-start)))
  (if (spacemacs/emacs-version-ok) (progn (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (require (quote core-configuration-layer)) (spacemacs/init) (configuration-layer/sync) (spacemacs/setup-startup-hook) (spacemacs/maybe-install-dotfile) (require (quote server)) (if (server-running-p) nil (server-start))))
  eval-buffer(#<buffer  *load*> nil "c:/Users/Mark/.emacs.d/init.el" nil t)  ; Reading at buffer position 998
  load-with-code-conversion("c:/Users/Mark/.emacs.d/init.el" "c:/Users/Mark/.emacs.d/init.el" t t)
  load("c:/Users/Mark/.emacs.d/init" t t)
  #[0 "\205\262gg
```

**Comment by Devagamster** [comment]
It is still throwing the same issue for me as well. I have tried it on two windows 10 machines same version as above. Also it appears that I can't run package-buffer-info from M-x menu as it doesn't exist? I'm pretty new to emacs so I might be missing something. Could it possibly be related to the new use-package quelpa feature?

**Comment by TheBB** [comment]
You may have to `M-: (require 'package)` before running `package-buffer-info`.

**Comment by Devagamster** [comment]
gotchya. I'll see what I can do.

**Comment by TheBB** [comment]
Ah sorry, `package-buffer-info` isn't an interactive command. You have to do it with `M-: (package-buffer-info)` and not `M-x`.

**Comment by TheBB** [comment]
@mahinshaw When this happens, can you grab the file in the backtrace (c:/Users/Mark/.emacs.d/.cache/quelpa/packages/evil-indent-textobject-20140918.707.el) and post it somewhere so I can see?

**Comment by mahinshaw** [comment]
@TheBB - https://gist.github.com/mahinshaw/649b0f45b5a2a2dd8a40

**Comment by Devagamster** [comment]
Interestingly enough, the error does not seem to show up on my win 7 work machine.

**Comment by mahinshaw** [comment]
@Devagamster - I am on Windows 7 - what emacs build are you using?

**Comment by Devagamster** [comment]
http://emacsbinw64.sourceforge.net/ for both machines having the issue and my one machine that is not displaying the issue. They all have the same .spacemacs.d folder as well.

**Comment by mahinshaw** [comment]
That is what I am using as well.  I tried an old build of 24.3 from gnu for windows, and I had the same issue.

**Comment by TheBB** [comment]
I can't reproduce this issue, not even with @mahinshaw's file. It must be OS/build related. I'll ask the quelpa maintainer to chip in.

**Comment by steckerhalter** [comment]
This is **probably** caused by Git for Windows defaulting to auto convert line endings to CR/LF (see https://github.com/quelpa/quelpa/issues/72#issuecomment-102652819) on checkout.

Try disabling autocrlf:

```
git config --global core.autocrlf true
```

See https://github.com/quelpa/quelpa#windows-instructions for Windows specific quelpa instructions (if the git change still didn't help, try if it works with any of the methods specified there)

**Comment by louy2** [comment]
@steckerhalter Changing autocrlf to false did not solve the problem.

**Comment by syl20bnr** [comment]
@louy2 did you also wipe out the quelpa cache ? (~/.emacs.d/.cache/quelpa)

**Comment by TheBB** [comment]
I was able to reproduce this issue on my Windows computer. Setting `core.autocrlf` to false fixed it, but I did have to clean the quelpa cache, as @syl20bnr said.

**Comment by TheBB** [comment]
I take that back, I was able to reproduce this with the `php-extras` package as well. I'm betting that @louy2 fixed the problem but simply didn't clean his cache, and that's why `php-extras` worked for him.

**Comment by steckerhalter** [comment]
@TheBB you can disable line-ending conversion in `.gitattributes`: http://stackoverflow.com/a/10017566

most people won't have this set so disabling autocrlf will be still required for other repos

**Comment by TheBB** [comment]
Thanks @steckerhalter, so after some mucking about, here are my findings.

* Setting `core.autocrlf` to false allowed me to install `evil-indent-textobject`
* Setting `core.autocrlf` to false **did not** allow me to install `php-extras`, I'm getting another error with that package.
* The file in `.cache/quelpa/build/` does **not** appear to have CRLF line endings no matter the `core.autocrlf` setting. Why?
* The file in `.cache/quelpa/packages/` **does** have CRLF line endings with `core.autocrlf` set to true, but I couldn't check with `core.autocrlf` set to false (because then the error doesn't occur and the file is deleted, as it should be).

**Comment by steckerhalter** [comment]
As long as `(package-buffer-info)` can run there shouldn't be a problem with CRLF. CRLF line-endings cause that to fail. What is the other error you are getting with php-extras?

**Comment by TheBB** [comment]
I don't know, I couldn't run with `--debug-init`. I'll try later as I'm at work now.

**Comment by TheBB** [comment]
I'm getting a `(wrong-type-argument stringp nil)` with `php-extras`. No backtrace, though, even with `--debug-init`. (With the error message "An error occured while *installing* `php-extras`.)

I can consistently get `evil-indent-textobjects` to succeed or fail by setting core.autocrlf to true or false. It seems @louy2 still has problems. I'd like to wait for feedback from @Devagamster and @mahinshaw.

**Comment by TheBB** [comment]
@steckerhalter Is there a reason you're using `insert-file-contents-literally` instead of `insert-file-contents`? The latter would make these problems go away.

If there is a reason, is there an function for getting Emacs do to automatic line ending conversion after the fact (on the current buffer)? I'm looking but having no luck so far.

@louy2 got it working by the way, so I guess we know what the problem is.

Sorry for spamming this issue. :-D

**Comment by steckerhalter** [comment]
@TheBB is php-extras installing with `insert-file-contents`?

I think I used `insert-file-contents-literally` to avoid some unexpected results when Emacs (or some hook) modifies the content.

I could test with `insert-file-contents` if that works better

**Comment by TheBB** [comment]
No, I'm just talking about single-file packages right now. I haven't looked at php-extras yet, something else must be wrong there.

I'm thinking about something along these lines

```patch
--- a/quelpa.el
+++ b/quelpa.el
@@ -167,10 +167,11 @@ On error return nil."
   (let* ((kind (quelpa-package-type file))
          (desc (with-demoted-errors "Error getting PACKAGE-DESC: %s"
                  (with-temp-buffer
-                   (insert-file-contents-literally file)
                    (pcase kind
-                     (`single (package-buffer-info))
-                     (`tar (tar-mode)
+                     (`single (insert-file-contents file)
+                              (package-buffer-info))
+                     (`tar (insert-file-contents-literally file)
+                           (tar-mode)
                            (if (help-function-arglist 'package-tar-file-info)
                                ;; legacy `package-tar-file-info' requires an arg
                                (package-tar-file-info file)
-- 
```

**Comment by mahinshaw** [comment]
I have` autocrlf = false`, and always have.  I also cleared the quelpa cache, yet the issue remains for me.

**Comment by louy2** [comment]
@mahinshaw Try removing `core.autocrlf` in `<git install path>/etc/gitconfig`.

**Comment by steckerhalter** [comment]
@TheBB I have created a PR for that change: https://github.com/quelpa/quelpa/pull/85

maybe you could test if things work well with that before we merge

**Comment by TheBB** [comment]
@steckerhalter Sure, I'll have a go.

**Comment by steckerhalter** [comment]
merged the PR. new version should be on melpa soon

**Comment by TheBB** [comment]
Oh okay, I hope you tested it because I haven't had time yet.

**Comment by steckerhalter** [comment]
build is ok and tests with my config also good, so yes I think that should do

**Comment by mahinshaw** [comment]
Quelpa updated.  Still running into this issue.  All previous steps attempted.

**Comment by TheBB** [comment]
I think I'm going to need some help on this problem then. @syl20bnr? We could revert the change in the meantime.

**Comment by syl20bnr** [comment]
@mahinshaw are you behind a proxy ? Is it possible that a corrupted file has been cached ? Do you have multiple versions of git on your system (git bash, cygwin, etc...) ? What are the versions of those git ? Are you sure that Emacs sees the correct git executable ? Can you clone the evil-indent-textobjects by hand, replace the file in cache by hand and rerun Emacs ?

**Comment by mahinshaw** [comment]
git version - `git version 2.5.0.windows.1`
No proxy
Cleared all of `.cache/*`
in eshell, I can call git
When I get back into work tomorrow, I will clone the repo and add it to the cache as noted.

**Comment by syl20bnr** [comment]
2.5 seems to be a very high number, the git packed in official git for windows is 1.9.x I believe.

If the manual copy does not work you could try this version instead.

**Comment by louy2** [comment]
@syl20bnr Git for windows 2.5.0 has just been released Aug 18.
Anyway I met the problem on 1.9.5. 
With `autocrlf=false` in my `~/.gitconfig`, deleting `autocrlf=true` in `<git install>/etc/gitconfig` and cleaning cache by deleting `~/.emacs.d/.cache/quelpa`, I am fine now. So maybe it's 2.5.0 specific.
In that case I guess git for windows team knows more?

**Comment by steckerhalter** [comment]
@louy2 I haven't tested on Windows yet but with the change in quelpa it should also work now without setting autocrlf to false

**Comment by mahinshaw** [comment]
Works for me.  Just as a side note - `autocrlf=true` will still cause this problem.  It might be worth putting that in the windows docs.  Also, the git version was not an issue, I had a tramp config file overriding my `.gitconfig`. Sorry for making this more of an issue than it should be.

**Comment by steckerhalter** [comment]
@mahinshaw it causes the same error as before with `autocrlf=true`?

**Comment by TheBB** [comment]
@steckerhalter I see it too, but I don't think it originates from the same location. Before, I got a backtrace on `--debug-init`, and after the patch I don't. So my best guess is that this has simply moved the problem from quelpa to somewhere else.

That's all I've found out for now.

**Comment by mahinshaw** [comment]
@steckerhalter Yes.  I just tested it again myself, and the issue is still there when `core.autocrlf = true`

**Comment by steckerhalter** [comment]
Ok, can you post the error if possible?

**Comment by mahinshaw** [comment]
@steckerhalter I don't get a dump from the debugger, but the error from spacemacs is:
```
--> installing spacemacs:evil-indent-textobject... [1/1]An error occurred while installing evil-indent-textobject (error: (error Package lacks a "Version" or "Package-Version" header))
```
I started from a fresh clone of spacemacs to make sure there were not any cache issues regarding spacemacs.  I am also back to using `git version 1.9.5.msysgit.1`

**Comment by steckerhalter** [comment]
Thanks. I will see if I can reproduce on Windows

**Comment by steckerhalter** [comment]
I know why I used `insert-file-contents-literally`, I took that from Emacs core:

```cl
(defun package-install-file (file)
  "Install a package from a file.
The file can either be a tar file or an Emacs Lisp file."
  (interactive "fPackage file name: ")
  (with-temp-buffer
    (insert-file-contents-literally file)
    (when (string-match "\\.tar\\'" file) (tar-mode))
    (package-install-from-buffer)))
```

So now it is failing in Emacs core because `package-install-file` is doing the same thing as I had in quelpa and then fails with CRLF files.

**Comment by steckerhalter** [comment]
it's here in the emacs source code: http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/emacs-lisp/package.el#n1961

**Comment by TheBB** [comment]
Yeah I thought it would be something like that. There's probably not much we can do about it, then. Thanks for your help @steckerhalter!

**Comment by syl20bnr** [comment]
Can we advice install-from-buffer and do the conversion ?

**Comment by steckerhalter** [comment]
Advicing is quite dangerous as it may break other things (a good example is what happened with emacs-async that was advicing `package--compile` which broke quelpa as a side-effect (and the advice was enabled by requiring `helm-config` so a few people ran into that.)

I wrote some code using `cl-letf`: https://github.com/quelpa/quelpa/pull/86/files
Don't have Windows here right now so maybe you could test?

**Comment by syl20bnr** [comment]
I see, I will disable async compilation as we don't need it in Spacemacs (the update process of Spacemacs already forces a deletion of the packages to update and a restart to complete the installation, especially to fix the issue that async compilation tries to resolve).

Nice solution, replacing the bound function locally is great.

I cannot test for now unfortunately :-(

**Comment by syl20bnr** [comment]
This is with hack like this that elisp shines as a configuration language, having so much code that don't clash without namespace support is just epic :-)

**Comment by steckerhalter** [comment]
I could test in the meantime. Seems to work. The problem with async compilation was fixed btw by the maintainer a few days ago so that shouldn't be a an issue anymoe, but it was a good reminder to me never to advice any Emacs internals in public packages because it's impossible to know all the side-effects the changes could possibly have.

**Comment by steckerhalter** [comment]
Lisp is awesome... too bad it's not more popular and the world is stuck in the non-REPL world

**Comment by louy2** [comment]
I went through a new installation of Git for Windows today, and noticed that to change the checkout behavior, it is enough to change `autocrlf` to `input`. Yep that's not a boolean. `autocrlf=false` will commit Windows style CRLF, which makes diff all crazy if the repo was using LF only.

**Comment by steckerhalter** [comment]
@louy2 Yes, that's better probably, although one should see when committing that there's a huge diff and if there is a PR with that it will probably be rejected.

The change I made in quelpa now (not merged yet) should make this problem go away so we can all forget about it. Then it will work no matter what someone chooses to have for autocrlf.

**Comment by TheBB** [comment]
I just tested https://github.com/quelpa/quelpa/pull/86 and it works beautifully here.

**Comment by steckerhalter** [comment]
Thanks, merged as well

**Comment by mahinshaw** [comment]
@steckerhalter - I tested this again this morning.  Works like a champ!
