### ISSUE TITLE
Internal documentation links are broken in org 8.3

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#2689]
Relevant discussion in #2368. It's been reported upstream to @snosov1 at https://github.com/snosov1/toc-org/issues/8, but I figured best to have an open tracking issue.

**Comment by snosov1** [comment]
It can, probably, be closed, since now, both most recent versions of toc-org (20150820.633) and Org (20150824) contain the fixes and seem to work fine.

**Comment by TheBB** [comment]
Thanks! I'll have a look in a bit.

**Comment by TheBB** [comment]
Confirmed. Thanks a lot @snosov1!

**Comment by snosov1** [comment]
:+1:
