### ISSUE TITLE
E-mail mode in spacemacs?

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#269]
A good mail setup for emacs hinges on several tools such as `offline-imap` and `mu` (IMO, if you have plenty of mail to handle).

Is creating a mail-mode a futile endeavour for spacemacs? Will probably be a lot of hassle to get the same stuff to work on win/linux/os x. 

Furthermore, I do not know if the contrib layers can hinge on external programs? (I use `brew install` for some of my emacs e-mail stuff.)

**Comment by syl20bnr** [comment]
I close this discussion and let #386 opened since it may be a good idea to first support Gnus.
