### ISSUE TITLE
ort/capture-todo-check broken

### ISSUE THREAD

**Issue by erikcw** [syl20bnr/spacemacs#2691]
Looks like something is broken in org-mode.

```
command-execute: Autoloading failed to define function ort/capture-todo-check
```

**Comment by geo7** [comment]
@erikcw how do I try to reproduce this?

**Comment by sooheon** [comment]
@erikcw If this is still an issue could you let us know how to reproduce?

**Comment by StreakyCobra** [comment]
There is no information on how to reproduce this, the issue is old, nobody else reported it, and the original poster is not responding, so I close this one. If anybody encounters this issue again, feel free to open a new issue :relaxed:
