### ISSUE TITLE
`cfgl-*` classes only allow one `layer/init-*` function

### ISSUE THREAD

**Issue by jcpetkovich** [syl20bnr/spacemacs#2694]
As far as I can tell, the new classes only call a single init function for any given package. As an example, consider two layers, `A`, and `B`. If `A` installs package `x` and `B` also installs `x`, and they both have init functions for this package, i.e., `A/init-x`, `B/init-x`, only `B/init-x` will be called.

Is this the intended semantics of the new class based loading system? If so, it would mean that there should only be one definitive init function for each package, and layer creators should be extremely careful in initializing packages, since they can only be initialized once, and worse than that, duplicate init functions are ignored silently, so it can be very confusing to debug.

If these are the intended semantics of the new layer loading system, I recommend adding some checks that there are no more than one init function for any package so that we can have meaningful warnings/errors from doing this. Otherwise it is fairly challenging to track down these problems.

**Comment by syl20bnr** [comment]
This is intended. Only on layer can take ownership on a package, the owner is the only one to initialize the package.

The other layer can extend the configuration by using `pre-init` and `post-init` functions that are called respectively before and after `init.`

The last layer to have an `init` function (layers are loaded in order of declaration) wins the ownership and it can override the package properties (`:location`, `:step`, etc...) so someone could use her own fork of a package for instance (by override `:location elpa` to `:location (recipe :fetcher github...)`). Inheritance can be obtained by calling the init function of another layer in the owner layer `init` function.

There is a warning in the message buffer when a layer steal the ownership, I'll add a mechanism later to allow to silence this warning when the change of owner is expected.

**Comment by jcpetkovich** [comment]
Ah, I see, somehow I missed those warnings although I have no idea how I managed to do so.

Thanks for the quick reply!

I'm going to close this.
