### ISSUE TITLE
Normal mode commands work strangely when you leave a : prompt hanging

### ISSUE THREAD

**Issue by chrismcg** [syl20bnr/spacemacs#2701]
This is using `emacs-mac` as recommended in the documentation.

To reproduce:

1. Make sure your buffer is in Normal mode
1. Type `:` to start command mode
1. Use the mouse to move the cursor back into the buffer at the start of a line with text
1. Press c

Instead of waiting for the motion to act on the line is deleted. If you click back into the command window and exit the `:` command things go back to normal.

I couldn't find an issue related to this so I've opened this. (There may be one I'm not sure what to search for.)

**Comment by Devagamster** [comment]
If I were to give a guess I'd say this is probably an evil issue.

**Comment by Profpatsch** [comment]
So, has this been forwarded to the evil project?

**Comment by chrismcg** [comment]
I haven't had a chance to do that yet. Go ahead please if you've more time than me atm.

**Comment by Profpatsch** [comment]
https://bitbucket.org/lyro/evil/issues/569/normal-mode-commands-work-strangely-when

**Comment by bjeanes** [comment]
omg this has been driving me crazy because I didn't know what was the cause. I kept restarting Emacs because I didn't notice the ex mode prompt!

**Comment by chrismcg** [comment]
This has been marked as resolved upstream https://bitbucket.org/lyro/evil/issues/569/normal-mode-commands-work-strangely-when

**Comment by TheBB** [comment]
Thanks for the heads up!
