### ISSUE TITLE
n repeats *-search incorrectly

### ISSUE THREAD

**Issue by mbertheau** [syl20bnr/spacemacs#2710]
With this document, pointer at |:

```
|foo
foo_bar
```
1. Hit <kbd>*</kbd>
2. Observe there's only one match, so <kbd>n</kbd> doesn't move the point
3. <kbd>Esc</kbd> out of the micro-mode
4. Hit <kbd>n</kbd>

Expected: Only one match as before, <kbd>n</kbd> doesn't move the point

Actual: Two matches, <kbd>n</kbd> moves to the second match.

Apparently <kbd>*</kbd> performs the equivalent of `/\<foo\>`, whereas <kbd>n</kbd> just does `/foo`.

**Comment by StreakyCobra** [comment]
`n` is a functionality of `evil` for searching for text occurences, `*` is a functionality of `auto-highlight-symbol` to look for symbols. So what you described seems a normal behaviour for me, but having `n` repeating the last `ahs` search may be an improvement :smile:
