### ISSUE TITLE
Scala: Document the “Prefix Command” groups

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#2713]
i.e. give them names, like <kbd>SPC m r</kbd>`: refactor `

**Comment by justbur** [comment]
Why don't you propose a list of names for the missing prefixes?

**Comment by Profpatsch** [comment]
@justbur The list is here: https://github.com/syl20bnr/spacemacs/tree/master/contrib/!lang/scala

I’m not sure how to tag prefix commands, though.

**Comment by justbur** [comment]
I think you want `spacemacs/declare-prefix-for-mode`

**Comment by Profpatsch** [comment]
@justbur That function doesn’t exist anymore, and `spacemacs/declare-prefix` is the wrong one. Looking through other language files I can’t find how to declare names for prefixes.

**Comment by justbur** [comment]
What do you mean? It's defined here https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/funcs.el#L83

**Comment by Profpatsch** [comment]
Oh, there was an issue with it (https://github.com/syl20bnr/spacemacs/commit/23533d0c5667d427a0a0e9551b9d20a335af9b81) and it got reactivated.

Yet, it’s used (and commented out) only in two places: https://github.com/syl20bnr/spacemacs/search?q=declare-prefix-for-mode&type=Code&utf8=%E2%9C%93
And my Emacs doesn’t know about it, which is strange.

**Comment by Profpatsch** [comment]
Ah, it’s only in develop branch for now, grrr git-flow.

**Comment by justbur** [comment]
Oh that's right. I forgot it was commented out for a while. I guess you're out of luck for the master branch right now. You could use `define-prefix-command` directly. I'm going to try and streamline the prefix stuff, so it doesn't require a declaration, but that will take a little work.

**Comment by Profpatsch** [comment]
@justbur I’m still not sure how I can add a label when the function only takes a *mode*, a *prefix* and a *name*.

**Comment by justbur** [comment]
Try copying that function into your `dotspacemacs/config` function and then adding a declaration, so something like this

```elisp
(defun spacemacs/declare-prefix-for-mode (mode prefix name)
  ;;   "Declare a prefix PREFIX. MODE is the mode in which this prefix command should
  ;; be added. PREFIX is a string describing a key sequence. NAME is a symbol name
  ;; used as the prefix command."
  (let ((command (intern (concat spacemacs/prefix-command-string name))))
    (define-prefix-command command)
    (evil-leader/set-key-for-mode mode prefix command)))
(spacemacs/declare-prefix-for-mode 'scala-mode2 "mr" "refactor")
```

I don't use scala or the master branch, but I don't see why that won't work.

**Comment by Profpatsch** [comment]
Uhm, if I understand correctly: `NAME is a symbol name used as the prefix command.`

So this doesn’t work, since it wants a function name, like `'myfunc`.

**Comment by justbur** [comment]
Did you try it? If you look at the function definition name is used as a string and then interned.

**Comment by Profpatsch** [comment]
Hm, you are right. Silly me, coming from statically typed languages …

**Comment by justbur** [comment]
Actually, that would explain why the docstring is commented out. It might have applied to a previous version.

**Comment by syl20bnr** [comment]
Those functions should be moved to core-funcs.el, weird to have them in spacemacs layer.
