### ISSUE TITLE
'spc :' fails when emacs daemonized 

### ISSUE THREAD

**Issue by usharf** [syl20bnr/spacemacs#2715]
I'm getting `SPC : undefined`  though `M-x` seems to work fine.

I'm on the develop branch of `spacemacs`, on nixos-unstable with emacs running daemonized under systemd as a *user* controled service.

**Comment by TheBB** [comment]
There's a number of problems with the daemon at the moment. There's https://github.com/syl20bnr/spacemacs/pull/2652 for fixing parts of it.

**Comment by d12frosted** [comment]
Isn't it fixed already? @usharf does it still happen to you?

**Comment by usharf** [comment]
I don't have the same setup anymore to report on...

**Comment by tidux** [comment]
This is still impacting Emacs 25.1 with latest Spacemacs on Windows 10.

**Comment by bmag** [comment]
@tidux `SPC :` isn't bound by default anymore, you should make sure Spacemacs and your personal configuration are up-to-date, and if the problem persists you can open a proper bug report.
