### ISSUE TITLE
Unclear documentation and perhaps an issue with org layer

### ISSUE THREAD

**Issue by ipsod** [syl20bnr/spacemacs#2721]
The documentation is unclear - to enable the org layer, should I just uncomment `;; org` under `dotspacemacs-configuration-layers` in my `.spacemacs` file??

If so, that doesn't seem to be working.  I'm editing a file, `test.org`, and I'm able to use org mode, but the evil-org-mode keybindings are not functional, and the minor mode is `guide-key mode`, and evil-org-mode is not an option when I click it with mouse3.  How do I use `evil-org-mode`?

**Comment by thefucker** [comment]
hi , uncomment org , like this
dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     auto-completion
     better-defaults
     emacs-lisp
     (colors :variables
             colors-enable-rainbow-identifiers t
             colors-enable-nyan-cat-progress-bar t)
     git
     markdown
     org
     (shell :variables
             shell-default-height 30
             shell-default-position 'bottom)
      syntax-checking
     version-control
     )

**Comment by person808** [comment]
> The documentation is unclear - to enable the org layer, should I just uncomment ;; org under dotspacemacs-configuration-layers in my .spacemacs file??

Yup. Did you restart emacs after? In an org file try `SPC : evil-org-mode` to toggle it on and off.

**Comment by ipsod** [comment]
>Yup. Did you restart emacs after? In an org file try SPC : evil-org-mode to toggle it on and off. It should be installed if your .spacemacs is correct.

That fixed it, thank you.  How would I turn evil-org-mode on by default in org files?

**Comment by robbyoconnor** [comment]
exclude it in your `.spacemacs`

**Comment by geo7** [comment]
@ipsod here's mine: 

```elisp
   dotspacemacs-excluded-packages
   '(
     ;; this stopped `t' working in Org mode. Not sure what it's actually meant
     ;; to do though
     evil-org
     )
```

**Comment by ipsod** [comment]
@geo7 I was trying to get it enabled by default - you mean to exclude it to keep it from ever being enabled?  Something broke org mode for me - you think it was that?

**Comment by ipsod** [comment]
Org layer is broken in emacs 24.3 - see https://github.com/syl20bnr/spacemacs/issues/2725

**Comment by robbyoconnor** [comment]
If you are able to use Emacs and vim -- you should be fully capable of running emacs >= 24.4 -- it can even run from your homedir if you setup `PATH` correctly.
