### ISSUE TITLE
cursor invisible if launching spacemacs inside tmux session

### ISSUE THREAD

**Issue by jrmiller82** [syl20bnr/spacemacs#2724]
I don't get a cursor, no matter my tmux settings. I see the whole line highlighted, but no box, underline, etc. If I run spacemacs outside of tmux, it works fine. 

I have not changed a single thing in the default .spacemacs file. Thanks.

**Comment by jrmiller82** [comment]
Resolved. It was an issue with iTerm version; not spacemacs. Apologies.

**Comment by schmooser** [comment]
Could you please describe, how you resolved this problem? I have the same issue.

**Comment by jrmiller82** [comment]
I just updated my iTerm to the latest version and it resolved it.

**Comment by schmooser** [comment]
Thanks, that also helped me.

**Comment by arnm** [comment]
Thanks, updated iTerm to latest and everything is OK!
