### ISSUE TITLE
folding/unfolding glitch in org mode

### ISSUE THREAD

**Issue by ipsod** [syl20bnr/spacemacs#2726]
Steps to reproduce:

* Enter this text in an org file
```
* heading
text
text
```
![snapshot1](https://cloud.githubusercontent.com/assets/2526835/9428835/639894f4-4981-11e5-9295-5d8d62b0b74d.png)

* Place cursor on `text`, and `zc` to fold.
![snapshot2](https://cloud.githubusercontent.com/assets/2526835/9428837/63b4feb4-4981-11e5-8abf-f817ab5c95be.png)

* With cursor still on `heading`, `zv` to unfold.
![snapshot3](https://cloud.githubusercontent.com/assets/2526835/9428836/63b249ee-4981-11e5-89f7-905b0b4c9aa6.png)

* Subsequently hitting `zv` will still fail to unfold, but if the cursor goes off of `heading`, then back on to it, `zv` will unfold properly.
![snapshot1](https://cloud.githubusercontent.com/assets/2526835/9428835/639894f4-4981-11e5-9295-5d8d62b0b74d.png)

**Comment by TheBB** [comment]
What's `zv`? That's not a folding binding here.

Can't reproduce this with `zc` and `zo` or `za`.

**Comment by ipsod** [comment]
Oh, `zv` is a custom binding I made to preserve old vim habits.  I changed it to do the same thing `zo` does, and that fixed it.  Thank you.
