### ISSUE TITLE
Scala: ? is shadowed

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#2729]
`?` normally is a global spacemacs menu keybinding that recursively lists all commands in that submenu. It shouldn’t be shadowed.

**Comment by chrisbarrett** [comment]
`SPC ?` is bound correctly to `helm-descbinds` for me. Got any steps to reproduce the issue?

**Comment by Profpatsch** [comment]
`SPC m ?`

If you hit `?` in any other sublevel, it only shows (and filters) the commands of that sublevel.

**Comment by TheBB** [comment]
I don't see that behaviour anywhere, scala or not.

**Comment by chrisbarrett** [comment]
Oh yep, https://github.com/syl20bnr/spacemacs/blame/master/contrib/!lang/scala/packages.el#L92

That setting would probably have preceded any conventions around what `?` does. I note `ensime-scalex` isn't even a thing anymore. Feel free to submit a PR to remove that bad boy.
