### ISSUE TITLE
avy word and golden ratio

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2730]
This is on develop (up-to-date):

When using ace-window (SPC w SPC) to move between windows, the golden ratio toggle works.  However, if I am in one window, and use avy-word (SPC SPC) to jump to another window, the golden ratio doesn't work.

**Comment by TheBB** [comment]
I guess the relevant avy commands have to go in `golden-ratio-extra-commands`.

**Comment by synic** [comment]
I've tried the following as a workaround with no luck:

```lisp

(add-advice `avy-goto-word`
  :after (lambda (&rest args)
    `(golden-ratio)))
```

```lisp

  (eval-after-load 'golden-ratio
    '(setq golden-ratio-extra-commands
           (append '(avy-goto-word-or-subword-1))))
```

```lisp

  (eval-after-load 'golden-ratio
    '(setq golden-ratio-extra-commands
           (append '(avy--generic-jump))))
```

I've put this in my `dotspacemacs/init` at the end.  Perhaps that's the wrong place?

**Comment by TheBB** [comment]
You can't use `append` in `setq` like that. Try this.

```lisp
(eval-after-load 'golden-ratio
  '(progn
     (push 'avy-goto-word-or-subword-1 golden-ratio-extra-commands)
    ))
```

Then see if `SPC SPC` works.

**Comment by synic** [comment]
@TheBB Did not work, but maybe it's just trying to run it too fast or something.  The following from @cmccloud works:

```lisp

  (advice-add 'avy--done
    :after (lambda (&rest args)
      (run-at-time 0.1 nil #'golden-ratio)))
```

**Comment by TheBB** [comment]
Looks like that will enable `golden-ratio` unconditionally. I doubt that will be a big hit with those of us who don't use it.

**Comment by cmccloud** [comment]
This might be another option:
```
(with-eval-after-load "golden-ratio"
  (push 'avy-goto-word-or-subword-1 golden-ratio-extra-commands))
```
