### ISSUE TITLE
State where normal mode is broken

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#2735]
I sometimes get into a state, where all operations like `dd`, `yy` &c. are changed to `d`, `y`, &c.
This also means that I cannot use combinations like `d3w` anymore.

I’m not sure what is causing this. If it is intended, it’s highly annoying.

**Comment by Devagamster** [comment]
Can you give more information? I can't seem to reproduce your state. Can you find a situation where it is consistently happening?

**Comment by chrismcg** [comment]
Is it the same as this? https://github.com/syl20bnr/spacemacs/issues/2701

**Comment by Devagamster** [comment]
That does seem to be very similar

**Comment by Profpatsch** [comment]
Yes, it’s the cause.
