### ISSUE TITLE
helm-ag doesn't set mark as I-search and evil-search

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#2736]
https://github.com/syohex/emacs-helm-ag/issues/157

As a result `` ` ` `` is not able to jump back after a helm-ag jump. Instead helm-ag provides `helm-ag-pop-stack`. How shall we incorporate this?

**Comment by syl20bnr** [comment]
I propose ``SPC s ` ``, `s` being mainly used to search with helm-ag.
