### ISSUE TITLE
visual mode `s` key broken?

### ISSUE THREAD

**Issue by ipsod** [syl20bnr/spacemacs#2740]
In vim, it's possible to highlight a selection, then delete it and go into insert mode using the `s` key.  The `s` key works in normal mode, but seems not to in visual mode.

**Comment by TheBB** [comment]
`s` is used for evil-surround. Doesn't `c` do what you want?

**Comment by ipsod** [comment]
It does.  Evil-surround is awesome.  Fun stuff.  Thank you.
