### ISSUE TITLE
Cleaning up issues

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#2741]
Currently almost half the issues are still open. Many of them are labeled "fixed in develop" and will be closed on next release, but there are many others that in my opinion should be closed, not just bugs that are actually fixed but also questions and discussions that remain open long after they've been answered, discussed to death and/or abandoned.

I don't think this is ideal. It makes it difficult to get an overview.

I've looked through a few and found some candidates. I will update as I find more, and I invite everyone else with spare time to go treasure hunting.

For abandoned issues that we're not sure are fixed or not (the relevant code may have gone through heavy refactoring, or several versions of an upstream package have gone by since then, for example), it can be an option to close them with an invitation to reopen or re-report with fresh information if necessary.

Consider also whether it's worth to add a trusted collaborator or two with the go-ahead to do this for you, @syl20bnr. I know there's @trishume but he's ~~now one of *THEM*~~ not active at the moment.

- ~~#102: See my comment~~
- ~~#192: Maybe not a bug?~~
- ~~#354: Discussion has run its course~~
- ~~#435: Should be fixed in develop~~
- ~~#464: Should be fixed in develop~~
- ~~#510: Unsupported version, old and probably fixed in develop~~
- ~~#524: Should be fixed in develop~~
- ~~#554: Fixed upstream~~
- ~~#624: Should be fixed in develop~~
- ~~#677: Outdated, no such thing as haskell-move-nested shows up with grep~~
- ~~#695: Ediff is in Spacemacs now~~
- ~~#732: Should be fixed in develop~~
- ~~#771: Discussion has run its course (and company is disabled in org now)~~
- ~~#814: Fixed upstream~~
- ~~#826: Discussion has run its course (and problem is upstream)~~
- ~~#923: MPD: java layer is in, eyebrowse does tabs~~
- ~~#1002: Should be fixed in develop~~
- ~~#1004: Fixed~~
- ~~#1043: Discussion has run its course~~
- ~~#1091: Probably fixed~~
- ~~#1101: Fixed (magit is evilified, not emacs state)~~
- ~~#1112: Discussion has run its course~~
- ~~#1113: Discussion has run its course~~
- ~~#1117: Can't reproduce, fixed in the meantime?~~
- ~~#1119: Git-gutter has been removed~~
- ~~#1172: Fixed~~
- ~~#1173: Should be fixed in develop~~
- ~~#1214: Fixed (no references to clone http in docs, no more submodules)~~
- ~~#1228: No response~~
- #1261: Discussion has run its course (and is wontfix)
- ~~#1263: Should be fixed in develop~~
- ~~#1275: Fixed upstream~~
- ~~#1311: Fixed~~
- ~~#1314: Should be fixed in develop~~
- ~~#1321: Discussion has run its course~~
- ~~#1351: Discussion has run its course (wontfix?)~~
- ~~#1358: Fixed~~
- ~~#1505: Git-gutter has been removed~~
- ~~#1741: Git-gutter has been removed~~
- #2741: When it's taken care of. :wink:

**Comment by justbur** [comment]
@syl20bnr Would it be possible to give @TheBB the ability to do this himself? He seems pretty reasonable ;-)

**Comment by trishume** [comment]
:+1: replacing me as assistant Issue Traffic Controller.

**Comment by syl20bnr** [comment]
So @trishume has designated his successor, congratulations @TheBB !

@trishume Thank you for all the help and contributions you provided during the first year of Spacemacs. Special thanks for being the first contributor to the project :+1: I hope one day I'll be able to replace Spacemacs with your own editor ;-)

**Comment by TheBB** [comment]
Thanks! I'll get to it momentarily.

**Comment by justbur** [comment]
Yes, @TheBB you're on the clock now. Unfortunately, we can't provide much in the way of benefits.

**Comment by cmccloud** [comment]
A few more possibilities for your list.

#517 - discussion has run it's course
#563 - last updated > 6mo
#1357 - env issue?
#1505 - git-gutter no longer used
#1741 - git-gutter no longer used

**Comment by justbur** [comment]
@TheBB We should ask those people with lots of open issues to go through the old ones and close any that aren't relevant any more (they should be able to do this quicker than you or anyone else). I can't figure out how to find out who has the most issues open easily, but at least the people who actively contribute should be able to do this quickly. Just quickly going through it to find who has the most:

@tuhdo has 33 
@xged 16
@tko 14
@cpaulik 11
@CestDiego 10
@geo7 10
@TheBB 9!!

**Comment by TheBB** [comment]
Yes, good idea. I'll have you know that 4 of mine are due to be closed upon release and there's a PR open for the fifth. :wink:

**Comment by geo7** [comment]
is there a page where we can see all the issues we've made?

**Comment by TheBB** [comment]
@geo7 https://github.com/syl20bnr/spacemacs/issues/created_by/geo7

**Comment by justbur** [comment]
You can filter on author or click issues at the top of the page

**Comment by cpaulik** [comment]
Good idea. I've checked mine and was able to close a some. For edge cases I pinged @TheBB and he can decide if they should be closed.
