### ISSUE TITLE
Newbie (to spacemacs) question about custom config/lisp

### ISSUE THREAD

**Issue by madhat2r** [syl20bnr/spacemacs#2744]
What is the general practice for adding your own lisp functions/bindings in spacemacs. 

I am coming from self-configured emacs and am trying to find what is the accepted way to accomplish this? I have several lisp functions that I have written and have keybindings for, they are not packages so a layer would not make much sense, but nonetheless I need to have them loaded.

Thanks for your help!

**Comment by TheBB** [comment]
You can still make a layer, they're not just for packages. But initially you can make use of the `dotspacemacs/config` function. It's run last in he loading process.

**Comment by madhat2r** [comment]
Thanks @TheBB. 
So I should make a layer, then just define my custom functions in a func.el,conifg.el, bindings.el file? Will these load regardless of the packages.el file not loading packages?

**Comment by Devagamster** [comment]
I believe a config file loads after everything else and should run regardless of when there is a packages.el file or not.

**Comment by madhat2r** [comment]
Okay, so I should just stick my defuns/advices etc. in a config.el file and that will work.

Do you know if the bindings.el file is also ran? I would like to keep the definitions separate from the bindings.

**Comment by Devagamster** [comment]
I haven't tested it as I don't use the bindings file on my own config layer, but I believe it should as well. Also remember to add the layer you create to your dotspacemacs-configuration-layers list in your .spacemacs file (or init.el if you use the .spacemacs.d structure which I would highly recommend)

**Comment by madhat2r** [comment]
Okay that sounds good, thanks for all the help.
@Devagamster you have me curios about the .spacemacs.d directory structure, I don't recall anything about that in the Docs, did I miss something?

**Comment by TheBB** [comment]
It's a recent addition, it only works in master and the docs aren't updated yet.

#1861

**Comment by madhat2r** [comment]
Thanks @TheBB, I do like the look of that, from the discussions that were mentioned that seems a good way to address those issues, which I have not yet run up against, but imagine I will.

This may seem like a dumb question but how do we set this up exactly? Emacs will not recognize .spacemacs.d as a init dir. Do we need to bootstrap this via one of the normal files (i.e. .emacs)?

**Comment by TheBB** [comment]
Emacs won't recognize it, but Spacemacs will—in the same way it recognizes your `~/.spacemacs`, which is also not recognized by Emacs by the way.

All you have to do is move `~/.spacemacs` to `~/.spacemacs.d/init.el`. Nothing else.

**Comment by madhat2r** [comment]
I have been trying this, but every time I launch emacs it regenerates the .spacemacs file. I appears to not recognize the .spacemacs.d/init.el

I even did a fresh install of spacemacs to make sure I had the latest version.

Any ideas?

**Comment by justbur** [comment]
I think @TheBB meant to say it only works on the develop branch. Are you on develop?

**Comment by TheBB** [comment]
Ah yes, by "it works in master" I meant "it doesn't work in master". :wink:

**Comment by madhat2r** [comment]
Ahh, no. That would be the issue then :) 

Is the develop branch stable enough to use without fear? Does anybody use it as their main setup?

**Comment by justbur** [comment]
I do but I also expect to have to fix issues here and there.

**Comment by cmccloud** [comment]
I do as well and I think it's stable enough - occasionally new features are introduced that break things, but its easy enough to pick a commit that works well and designate it as your develop-stable and only update when a feature/fix that you need gets added.

**Comment by Devagamster** [comment]
Especially at the moment there hasn't been a release to master recently, so there is a fair amount of new goodies in develop. I would recommend it if you are brave :smile:

**Comment by madhat2r** [comment]
I do like goodies :) I am most certainly going to be using the develop
branch. I especially like the .spacemacs.d setup, very nice indeed. I
wonder why that is taking so long to getting merged into master, seems like
a win-win kinda thing.

Thanks everyone for all your help!! 

On Aug 25 at 05:17 PM, Devagamster <notifications@github.com> had thus
to say:

**Comment by Devagamster** [comment]
Spacemacs has releases periodically. The reason it hasn't been moved to master yet is because the next release isn't quite ready yet (there is some documentation stuff being worked on). The .spacemacs.d thing has only been around for a couple of weeks so not too long.
