### ISSUE TITLE
NeoTree - can't ignore .pyc files (or any other files you might want to ignore)

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2751]
This is true in both master and develop.

The configuration variable `neo-hidden-regexp-list` should make NeoTree ignore any files that match that list, however, it doesn't work.

The default is `"^\\." "\\.pyc$" "~$" "^#.*#$" "\\.elc$"`, but `.pyc` files are still displayed.  Setting it manually does not work either:

```elisp

  (eval-after-load "neotree"
    '(setq neo-hidden-regexp-list '("^\\." "\\.pyc$" "~$" "^#.*#$" "\\.elc$"))
    )
```

**Comment by TheBB** [comment]
I found it... finally.  You need to `(setq neo-show-hidden-files nil)`.

**Comment by bmag** [comment]
Actually, there's a toggle for it: press <kbd>s</kbd> in NeoTree's window to show/hide the hidden files.
You can set `neo-show-hidden-files` in your `dotspacemacs/config` to control the toggle's initial state.
In Spacemacs, the default is to show the hidden files - that's why NeoTree didn't ignore the hidden files.

**Comment by synic** [comment]
Well, I guess this is a non-issue.  Thanks folks!

**Comment by mmcnl** [comment]
Is there any way to always prevent certain files (e.g. `.DS_Store`) from being displayed even when showing other hidden files?

**Comment by StreakyCobra** [comment]
@mmcnl https://github.com/jaypei/emacs-neotree/blob/7ac86e96f1a0eb542ba38da741b4abd21312c7dd/neotree.el#L261-L265

**Comment by mmcnl** [comment]
Thanks @StreakyCobra, I've seen that var but my ideal behavior is to blacklist certain files (e.g. `.DS_Store`) from ever being displayed even when neotree is in the mode where it's showing other hidden files (e.g. `.gitignore`). Neotree's current behavior is to either hide files (using the regex) or show *all* files without exception.

**Comment by StreakyCobra** [comment]
@mmcnl Then you probably have to ask this upstream :-)

**Comment by mmcnl** [comment]
Will do -- thanks!

**Comment by brandonparsons** [comment]
@mmcnl Did you figure out how to do that?

**Comment by mmcnl** [comment]
I'm currently using a very ugly hack that's something like this:
```
(with-eval-after-load 'neotree
  (setq-default neo-show-hidden-files t)
  (add-to-list 'neo-hidden-regexp-list "TAGS$")
  (add-to-list 'neo-hidden-regexp-list "__pycache__")

  ;; patched to allow everything but .DS_Store
  ;; this must be run after neotree loads in order to monkeypatch
  (defun neo-util--walk-dir (path)
    "Return the subdirectories and subfiles of the PATH."
    (let* ((full-path (neo-path--file-truename path)))
      (condition-case nil
          (directory-files
           path 'full "^\\([^.]\\|\\.[^D.][^S]\\).*")
        ('file-error
         (message "Walk directory %S failed." path)
         nil))))
  )
```

**Comment by brandonparsons** [comment]
@mmcnl Thanks!
