### ISSUE TITLE
Spacemacs freezes on LaTeX compilation

### ISSUE THREAD

**Issue by jsfr** [syl20bnr/spacemacs#2752]
I have a rather large TeX document, spread across multiple files, in a git repository.

Normally I would start a terminal with the command `latexmk -pvc main.tex` which then compiles my document every time it is saved.

However when using spacemacs it completely freezes (and uses ~50-100% CPU) during the compilation of the document. This also seems to occur if I run the build command from Spacemacs `SPC m b`.

I suspect this may be something to do with the amount of files which are changed at once in the repository (all the aux files, etc.).

My config is relatively clean. I have no private or custom layers and no extra configuration. My enabled layers are: `auto-completion, emacs-lisp, syntax-checking, version-control, latex, go`

EDIT: I have now tried removing any customization in `dotspacemacs/config` and also comment out all layers in `dotspacemacs/layers` and the problem still persists. When running latexmk in another seperate terminal, Spacemacs freezes.

The version of Spacemacs is v.0.103.5

**Comment by jsfr** [comment]
The issue only seems to occur if I am in a buffer with a file for for that project. If I e.g. edit a TeX file in the project, save it and then switch to a buffer not in the project (e.g. *Messages*) Spacemacs does not freeze.

This further strengthens my suspicion that the issue is with some background process of spacemacs which scans the files of the project. Currently though I am out of ideas on how to gather more information.

I have disabling projectile by running `SPC : projectile-mode`. This however seemed to have no effect.

**Comment by jsfr** [comment]
Switching to the develop branch, I still see Emacs eating a lot of CPU during compilation, but the freezes seems to be gone.

**Comment by rpls** [comment]
You could reduce the number of changed files by using something to the tune of `latexmk -outdir=/tmp`. This will put all aux files into a temporary dir (although some latex packages have problems with this, namely packages that generate files with a shell-escape, but so far I encountered only few). Does this help?

**Comment by jsfr** [comment]
Unfortunately I used `minted` which requires shell-escape, so this would no work for me. However when running the develop branch I feel no slow-down (It is only through inspection using `top` that I can see Emacs uses extra CPU when I compile).

I am a bit unsure whether this issue should just be closed, as the issue has not been fixed per say, but is not really noticeable in develop.

**Comment by justbur** [comment]
When you say you commented out all layers does that include latex? Were you still using auctex? 

How many files that are being touched by latexmk are open in some buffer?

Is flycheck enabled?

**Comment by justbur** [comment]
It could have partly been spell checking. that was recently split from syntax checking in develop

**Comment by jsfr** [comment]
I disabled all layers, yes. By auctex do you mean the auctex layer or the package?

I have at no point used the auctex layer (is this not deprecated?), but only the latex layer.

As for the auctex package unless Spacemacs on its own, without the latex layer, loads auctex then no, I did not use auctex.

On the develop branch I use both the spell checking and syntax checking layers so I do not think spell-checking was the issue. I also fail to see how spell checking would be affected by the compilation?

As this is currently a non-issue I am closing this. Should the problem re-emerge it can be re-opened or created anew.

**Comment by justbur** [comment]
Auctex is the package used by the latex layer. Spell checking is
notoriously slow in emacs on some platforms, and flycheck which is the
package used in the syntax checking layer had been a source of slowness for
me in latex

That was the rationale behind those questions.
