### ISSUE TITLE
gist.el: if: Invalid slot type: gh-gist-gist, id, string, nil

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2753]
This is on develop:

Trying to do anything with `gist.el` results in the following error:

`gist.el: if: Invalid slot type: gh-gist-gist, id, string, nil`

From `*Messages*`:

```
Contacting host: api.github.com:443
Opening TLS connection to `api.github.com'...
Opening TLS connection with `gnutls-cli --insecure -p 443 api.github.com'...done
Opening TLS connection to `api.github.com'...done
if: Invalid slot type: gh-gist-gist, id, string, nil
```

**Comment by synic** [comment]
I've been watching a lot of chat in the magit channel about this one.   Everyone seems to think `gist.el` is cacheing bad credentials.

**Comment by cmccloud** [comment]
Thanks for the update - I just ran into this issue myself.

**Comment by StreakyCobra** [comment]
Do you still have this bug? I can't reproduce it anymore.

**Comment by synic** [comment]
Just worked for me.

**Comment by terakilobyte** [comment]
I'm now receiving this bug as well when I try to gist a buffer.

**Comment by talexand** [comment]
Confirmed.
