### ISSUE TITLE
Emacs says the first column in a line is character 0, it should be 1 

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2754]
This is on develop at least, haven't checked master.

Here's a screenshot:

http://d.pr/i/wSQG/1vnAOCEH

As you can see, my cursors is on column 79.  The line ends at char 79, but flycheck is telling me that it's too long (80 > 79). 

This seems to happen anywhere in the code, not just docstrings.  Using `gq` obviously does nothing, as the code is correctly wrapped and indented correctly to begin with.

**Comment by syl20bnr** [comment]
Are you sure that flake8 check for 80 columns ? I believe it is set by default to 78.

**Comment by synic** [comment]
If it's set to 78, it should probably say (80 > 78), no?

**Comment by cpaulik** [comment]
The default according to the python pep8 is 79 characters so the error message is fine. 

I can not really reproduce this based on the screenshot. Could you maybe give a example we could copy and paste?

Also what does flake8 give you in the command line for the same file?

**Comment by synic** [comment]
I believe I found the "problem" - I think the ruler in emacs is starting at 0, when it should start at 1.

```python
@job('periodic_calendar')
def send_checkin_notifications():
    """
    Runs through and sends notifications for `calendars.TentativeCheckin` if
    they are needed.

    If an event belongs to a basic calendar, doesn't have a tentativecheckin,
    and `expires` has been reached, an email will be send.

    `recapture_stale_reservations` will go through the
    `calendars.TentativeCheckin` items and cancel all events where the tentative
    checkin's expired field is not null.
    """
```

This is a screenshot of emacs, with the ruler visible at the bottom:

http://d.pr/i/rvg3/5HqfzsbM

As you can see, it's the same text.  My cursor is on the last character of the line, on the `e` in tentative.  Emacs reports it's on character 79.

This is the same file in vim:

http://d.pr/i/1akmy/48pWA8bT

Cursor is on the same character, vim reports I'm on column 80.

The problem is that emacs is starting a 0, while `flake8` and `vim` are starting at 1.

**Comment by cpaulik** [comment]
I think this is might be a confusion about how evil positions the cursor.

If you look at it in insert state it makes more sense. Position 0 is actually before the first character whereas position 1 is after the first character. AFAIK vim does not have a conception of this since the cursor is just on a character or column.

You will also notice that you can move the cursor to column 80 in your problematic line in normal mode because this is where the line actually ends. After the last character.

Since your line is actually 80 characters it is too long and flake8 is correct to report it.

**Comment by cpaulik** [comment]
Regarding the issue with `gq` not working: This might be because of the setting of fill-column. 
For me the value of `SPC h d v fill-column` is 80 which is not what pep8 needs. Setting it to `79` solves this problem for me.

**Comment by synic** [comment]
Ah, I think that will fix the autowrap too, won't it?

Should the default for python-mode be 79 instead of 80?  Everything else about it seems to cater to pep8 (indenting, etc).

**Comment by cpaulik** [comment]
Yes it should fix the autowrap. 

I think it would be best to set the default fill-column for python mode to 79 by introducing a layer variable. Some people might want to set it differently and a layer variable would allow that easily. 

I also noticed that pep8 actually recommends a 72 character wrap for comments and multi-line strings. But AFAIK this is currently not possible in the standard emacs python mode.
