### ISSUE TITLE
HTML layer web-mode config mistake

### ISSUE THREAD

**Issue by madhat2r** [syl20bnr/spacemacs#2766]
one of the regexes for the modes for web-mode is misconfigured

Current:
```emacs-lisp
("\\.as[cp]x\\'"    . web-mode)
```
Needs to be:
```emacs-lisp
("\\.as[cp]x?\\'"    . web-mode)
```
This is to support classic ASP, which I have the misfortune to maintain a large codebase of. :smile:

**Comment by CestDiego** [comment]
nice catch! :) :+1:

**Comment by TheBB** [comment]
Thanks. That was quick. :-)
