### ISSUE TITLE
yas-snippet-dirs  value is wired, many numbers in it

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#2772]
I'm using the latest develop branch, however when I open a org file, the yas-snippet-dirs  value is wired.
It prevents me from creating new snippets.

```
/Users/guanghui/.emacs.d/private/snippets/" 47 85 115 101 114 115 47 103 117
 97 110 103 104 117 105 47 46 115 112 97 99 101 109 97 99 115 46 100 
47 115 110 105 112 112 101 116 115 . "/Users/guanghui/.emacs.d/contrib/auto-completion/snippets"
```

Any help would be appreciated.

Thanks.

**Comment by syl20bnr** [comment]
```
(concat '(47 85 115 101 114 115 47 103 117 97 110 103 104 117 105 47 46 115 112 97 99 101 109 97 99 115 46 100 47 115 110 105 112 112 101 116 115)) => "/Users/guanghui/.spacemacs.d/snippets"
```

This path may be added automatically by Spacemacs, I did not investigate yet.

**Comment by StreakyCobra** [comment]
I can't reproduce this. @zilongshanren Is this still the case for you?

**Comment by TheBB** [comment]
I forgot, I fixed this in develop.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/commit/cd7bf33278cc3b200e2a6000c696ad282defa5e3 if you're interested.
