### ISSUE TITLE
Something strange on Python when I use logging

### ISSUE THREAD

**Issue by hujianxin** [syl20bnr/spacemacs#2774]
For example, my code is:
```python
import logging
logging.basicConfig(level = logging.ERROR, format = '[%(asctime)s %(levelname)s] %(message)s', datefmt='%Y%m%d %H:%M:%S')
print()
logging.debug('debug log')
logging.info('info log')
logging.warning('warning log')
logging.error('error log')
logging.critical('critial log')
```
After typing `C-c C-c`, I got:
```python
[20150827 18:38:57 ERROR] error log
[20150827 18:38:57 CRITICAL] critial log
```

*But*, when I change the logging level to another one, such as using `logging.basicConfig(level = logging.WARNING, format = '[%(asctime)s %(levelname)s] %(message)s', datefmt='%Y%m%d %H:%M:%S')`, I also got:
```python
[20150827 18:38:57 ERROR] error log
[20150827 18:38:57 CRITICAL] critial log
```
Until I restart the ipython in emacs.

**Comment by hujianxin** [comment]
And when I change it using `logging.basicConfig(level = logging.WARNING)` again, I also got:
```python
[20150827 18:38:57 ERROR] error log
[20150827 18:38:57 CRITICAL] critial log
```

**Comment by bmag** [comment]
This is a python issue. `basicConfig` will only do something the first time it is called. See python documentation [here](https://docs.python.org/2/library/logging.html#logging.basicConfig).

If you want to change the log level after it was already configured, use `getLogger().setLevel`:
```python
import logging
logging.basicConfig(format = '[%(asctime)s %(levelname)s] %(message)s', datefmt='%Y%m%d %H:%M:%S')
logging.getLogger().setLevel(logging.ERROR)
print()
logging.debug('debug log')
logging.info('info log')
logging.warning('warning log')
logging.error('error log')
logging.critical('critial log')
```

**Comment by hujianxin** [comment]
@bmag Thanks very much, I have solved this problem thanks to your help. I'll close this issue.

**Comment by hujianxin** [comment]
@bmag Well, I reopen this issue. I have other question. 
When i write 
```python
logger = logging.getLogger('example')
logger.setLevel(logging.INFO)
```
Everytime i type `C-c C-c`, the logging info will increase one beause of the question as you said.
For example:
```python
import logging

# 创建一个logger
logger = logging.getLogger('mylogger')
logger.setLevel(logging.DEBUG)

# 创建一个handler，用于写入日志文件
fh = logging.FileHandler('test.log')
fh.setLevel(logging.DEBUG)

# 再创建一个handler，用于输出到控制台
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)

# 定义handler的输出格式
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
fh.setFormatter(formatter)
ch.setFormatter(formatter)

# 给logger添加handler
logger.addHandler(fh)
logger.addHandler(ch)

# 记录一条日志
logger.info('foorbar')
```
The first time when i evaluate the buffer using `C-c C-c`, I got:
```python
 In [5]: ()
2015-08-27 19:44:02,276 - example - INFO - foorbary
```
And next time ：
```python
In [6]: ()
2015-08-27 19:44:02,959 - example - INFO - foorbar
2015-08-27 19:44:02,959 - example - INFO - foorbar
```
And then:
```python
 In [7]: ()
2015-08-27 19:44:06,065 - example - INFO - foorbar
2015-08-27 19:44:06,065 - example - INFO - foorbar
2015-08-27 19:44:06,065 - example - INFO - foorbar
```
How can I solve this problem? THANKS VERY MUCH~

**Comment by hujianxin** [comment]
I know restarting Python can solve this problem. I won't meet this problem when using Pycharm because everytime I click run button, Pycharm will start a new python interpretor, but Emacs won't.

**Comment by bmag** [comment]
Well, every time you run `C-c C-c` you create and add new handlers to the same `logger` object (`getLogger('mylogger')` returns the previously defined "mylogger" logger, not a new one).

Starting a new interpreter when you press `C-c C-c` may be the best solution for your workflow. I can help you with that, but you'd probably be better off asking this at http://emacs.stackexchange.com/ or http://stackoverflow.com/

**Comment by hujianxin** [comment]
@bmag Thank you, I understand your meaning.
