### ISSUE TITLE
evil-iedit deferred loading breaks evil-escape

### ISSUE THREAD

**Issue by cmccloud** [syl20bnr/spacemacs#2782]
I'm getting the following error on latest develop, which seems to have been introduced by 4bd9cda0190c25c50366aa7ad444f444cac20757

```
Error in post-command-hook (evil-escape--emacs-state-passthrough): (void-variable evil-iedit-state-map)
```
Afterwards I can no longer use the first key of my evil escape key sequence.

Steps to reproduce:

On latest develop (40fba3ac4d07b76adf5b933910ef2f9af83ab46a)
Using the 'vim editing style
Load spacemacs  (or otherwise be sure that iedit state has not yet loaded)
Switch to emacs state
Press the first key of your evil-escape-key-sequence (sequence is 'df' in my case)

For the time being I've disabled deferred loading of evil-iedit-state which fixes the problem here.

**Comment by CestDiego** [comment]
I find that my own config for `nj` is deactivated as well when reloading the config with `SPC f e R`

**Comment by syl20bnr** [comment]
May be related to #2813
I can safely say that this particual bug is fixed in evil-escape and available on MELPA.
