### ISSUE TITLE
`gg` doesn't work in NeoTree, other keybindings do.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2783]
This is for `develop`.

In the spacemacs documentation, it doesn't give you the keybindings for navigating to the top and bottom of the NeoTree buffer.   I tried to use vim keybindings, and while most of them work, there's one glaring exclusion.  

`S-g` works to go to the bottom of the file, but `gg` does nothing.  It should go to the top of the file.

**Comment by bmag** [comment]
I know this doesn't solve your issue, but `<` and `>` go to the beginning and end of the buffer. You can find these bindings by typing `SPC ?` and looking under the "Major Mode Bindings" header.

I think what you want is to evilify `neotree-mode`.

**Comment by StreakyCobra** [comment]
In my personal config I have:

```elisp
  (add-hook 'neotree-mode-hook (lambda ()
    (define-key evil-motion-state-local-map (kbd "g") nil)
    (define-key evil-motion-state-local-map (kbd "f") 'neotree-refresh)))
```

to allow `gg` to work, and I map back the refresh functionality to `f`.

If it is enough for you, you can then use this. If you think it's worth sharing, make a PR from it (with keybindings documentation). In either case I think we can close this issue :smile:

**Comment by synic** [comment]
I don't really view this as an enhancement.  If you are going to make `NeoTree` vim compatible, then keys like `G` and `gg` can't really be bound to something else.  The fact that `G` works just highlights this fact.  Sure, you could just remove that keybinding, but in what other buffers does `<` and `>` work to jump to the top and bottom of the window?  

Developers coming from `NerdTree` are going to think it's broken.

**Comment by synic** [comment]
Also, I don't think closing tickets just because you are having a "cleanup" isn't the best option.  This is a valid ticket.  Either `gg` is broken, or `G` is broken.  Make a decision.

**Comment by StreakyCobra** [comment]
The goal is not to close because of the cleanup. From your first message I was thinking you were just wanting to make `gg` work, and I gave you a solution that fix it, it's why I was suggesting to close.

If you think it is worth to share because other people will saw this as a bug, then someone should do a PR with this change. Here is the incriminated line: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distribution/spacemacs/packages.el#L1566.

**Comment by bmag** [comment]
> in what other buffers does < and > work to jump to the top and bottom of the window?

magit-status, flycheck's error list, ibuffer, Paradox's package list, and more. It's very common in non-edit buffers, actually. By the way, in regular Emacs, `g` is also very common for doing a "refresh" in such buffers,

> Either gg is broken, or G is broken. Make a decision and I will try and make a PR.

I agree with @synic here. I don't know what keys NerdTree uses in Vim, but what we should at least be consistent with itself. There are the `evilify` and `spacemacs|evilify` macros, but for some reason NeoTree's config doesn't use them.

**Comment by synic** [comment]
> magit-status, flycheck's error list, ibuffer, Paradox's package list, and more. It's very common in non-edit buffers, actually. By the way, in regular Emacs, g is also very common for doing a "refresh" in such buffers,

At least in `magit-status`, `flycheck`, `paradox`, `list-faces-display`, etc, `gg` and `G` still work as expected.

NERDTree uses the following:

    o.......Open files, directories and bookmarks....................|NERDTree-o|
    go......Open selected file, but leave cursor in the NERDTree.....|NERDTree-go|
    t.......Open selected node/bookmark in a new tab.................|NERDTree-t|
    T.......Same as 't' but keep the focus on the current tab........|NERDTree-T|
    i.......Open selected file in a split window.....................|NERDTree-i|
    gi......Same as i, but leave the cursor on the NERDTree..........|NERDTree-gi|
    s.......Open selected file in a new vsplit.......................|NERDTree-s|
    gs......Same as s, but leave the cursor on the NERDTree..........|NERDTree-gs|
    O.......Recursively open the selected directory..................|NERDTree-O|
    x.......Close the current nodes parent...........................|NERDTree-x|
    X.......Recursively close all children of the current node.......|NERDTree-X|
    e.......Edit the current dif.....................................|NERDTree-e|

    <CR>...............same as |NERDTree-o|.
    double-click.......same as the |NERDTree-o| map.
    middle-click.......same as |NERDTree-i| for files, same as
                      |NERDTree-e| for dirs.

    D.......Delete the current bookmark .............................|NERDTree-D|

    P.......Jump to the root node....................................|NERDTree-P|
    p.......Jump to current nodes parent.............................|NERDTree-p|
    K.......Jump up inside directories at the current tree depth.....|NERDTree-K|
    J.......Jump down inside directories at the current tree depth...|NERDTree-J|
    <C-J>...Jump down to the next sibling of the current directory...|NERDTree-C-J|
    <C-K>...Jump up to the previous sibling of the current directory.|NERDTree-C-K|

    C.......Change the tree root to the selected dir.................|NERDTree-C|
    u.......Move the tree root up one directory......................|NERDTree-u|
    U.......Same as 'u' except the old root node is left open........|NERDTree-U|
    r.......Recursively refresh the current directory................|NERDTree-r|
    R.......Recursively refresh the current root.....................|NERDTree-R|
    m.......Display the NERD tree menu...............................|NERDTree-m|
    cd......Change the CWD to the dir of the selected node...........|NERDTree-cd|

    I.......Toggle whether hidden files displayed....................|NERDTree-I|
    f.......Toggle whether the file filters are used.................|NERDTree-f|
    F.......Toggle whether files are displayed.......................|NERDTree-F|
    B.......Toggle whether the bookmark table is displayed...........|NERDTree-B|

    q.......Close the NERDTree window................................|NERDTree-q|
    A.......Zoom (maximize/minimize) the NERDTree window.............|NERDTree-A|
    ?.......Toggle the display of the quick help.....................|NERDTree-?|

**Comment by robbyoconnor** [comment]
This sounds like a candidate for Evilization :)

**Comment by synic** [comment]
This is fixed!
