### ISSUE TITLE
Some themes have trouble with higlighting the current line

### ISSUE THREAD

**Issue by wraithan** [syl20bnr/spacemacs#2786]
![screen shot 2015-08-27 at 2 30 12 pm](https://cloud.githubusercontent.com/assets/90898/9533990/65153dae-4cca-11e5-8442-4f1a73e33eed.png)
![screen shot 2015-08-27 at 2 30 07 pm](https://cloud.githubusercontent.com/assets/90898/9533989/6512eac2-4cca-11e5-8ff3-3936b15b4209.png)

You can see what happens when I highlight a line while I have wombat enabled, this happens regardless of what type of code I happen to have open. Other themes like monokai do not have this problem. Spent a little bit trying to fix it in my own config and wasn't able to solve it. Others in the gitter agreed that they've seen this issue though.

Versions:
Emacs: GNU Emacs 24.5.1 (x86_64-apple-darwin14.4.0, Carbon Version 157 AppKit 1348.17) of 2015-08-19
OSX: 10.10.5
Spacemacs: (defconst spacemacs-version          "0.103.5" "Spacemacs version.")
All packages up to date as of 3-4 hours ago.

**Comment by Devagamster** [comment]
My impression is that it is intentional in this theme.

**Comment by wraithan** [comment]
manoj-dark and tango dark and a number of others also have this issue.

**Comment by cpaulik** [comment]
for manoj-dark this seems to be on purpose see [here](https://github.com/tovbinm/emacs-24-mac/blob/master/etc/themes/manoj-dark-theme.el#L515).

**Comment by wraithan** [comment]
I realize this may mean it isn't a bug for spacemacs but would like to ask (and maybe it'll help others in the future who also feel this is a problem) if there are a couple lines I could add to my config to fix it. If I use `:foreground 'inherit` on `hl-line` fontface or whatever the exact syntax is it will grab the bad override.

Am I stuck with having to fork the theme?

**Comment by TheBB** [comment]
Here's how to do this.

```lisp
(custom-set-faces '(hl-line ((t (:foreground nil)))))
```

Or if you hate the underline too (as I do),

```lisp
(custom-set-faces '(hl-line ((t (:foreground nil :underline nil)))))
```

Outside of this, I consider this simply bad theming.

**Comment by TheBB** [comment]
This is technically an upstream issue. The post above shows how to fix this locally. It works for me with both the themes mentioned. It's not at all unusual for people to tweak themes like this, so I consider this solved.

**Comment by jonathanunderwood** [comment]
For the Wombat theme at least, the proposed workaround also disables the background colour setting, so you lose the nice feature of the current line having a different background colour.

**Comment by d12frosted** [comment]
There a wonderful [theming layer](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+themes/theming/README.org) that can be used just for this kind of modifications. Hooray.

@jonathanunderwood you can use `describe-face` to get `background` value of that face and set `:foreground` to `nil` and `:background` to value you got from `describe-face`.

**Comment by jonathanunderwood** [comment]
Thanks @d12frosted. I tried a variety of things, such as 

```
(defun set-hl-line-color-based-on-theme ()
  "Sets the hl-line face to have no foregorund and a background
    that is 10% darker than the default face's background."
  (set-face-attribute 'hl-line nil
                      :foreground nil
                      :background (color-darken-name (face-background 'default) 10)))

(set-hl-line-color-based-on-theme)

(custom-set-faces '(hl-line ((t (:foreground nil :underline nil :background (color-darken-name (face-background 'default) 10)   )))))
```

None of which worked. What worked for me was:

```
(set-face-foreground 'highlight nil)
```

Can't say I really understand it. I'll have a look at the layer you link to.
