### ISSUE TITLE
Magit checkout (SPC g s b b) does not work as expected.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2788]
When trying to check out a branch using:

`SPC g s` and then `b b`, it doesn't actually switch branches, instead, it checks out the last commit in the branch.  

So, I type `SPC g s` and then `b b`, I pick the branch `dylan/eb-1326-remove-webinar`.  Then I go to the terminal and type `git status` in my git repository, and I see this:

```bash

[synic@elbows eventboard.io (g:b183368)]$ git status
HEAD detached at dylan/eb-1326-remove-webinar
```

**Comment by synic** [comment]
Sorry, this is on develop.

**Comment by cpaulik** [comment]
You need to press `b B` because you want to checkout and create a new local branch. That is the same difference than between `git checkout dylan/eb-1326-remove-webinar` and `git checkout -b branch-name dylan/eb-1326-remove-webinar`

**Comment by syl20bnr** [comment]
Is `dylan/eb-1326-remove-webinar` a local branch ?
If not then you may want to create the local branch and make it track the remote branch.

**Comment by synic** [comment]
You are right!  Thank you!
