### ISSUE TITLE
etcc--apply-to-terminal: Device 1 is not a termcap terminal device

### ISSUE THREAD

**Issue by kdheepak89** [syl20bnr/spacemacs#2790]
It seems like I'm getting an error with evil-terminal-cursor-changer

```
Loading /Users/$USER/.spacemacs...done
Loading /Users/$USER/.emacs.d/spacemacs/funcs.el (source)...done
Loading /Users/$USER/.emacs.d/spacemacs/config.el (source)...
etcc--apply-to-terminal: Device 1 is not a termcap terminal device
```

This only occurs when I try `SPC f e R` and with emacsclient in GUI.

This does not occur with emacsclient in the terminal, nor does it happen with Emacs.app (I'm on OSX btw). This also does not occur during Emacs.app startup or during emacs --daemon initialization. It occurs only when attempting to reload the configuration in the emacsclient GUI mode.

I'm able to replicate on master as well as develop. Any suggestions on how to debug?

**Comment by mnick** [comment]
Also happens for me on Arch Linux

**Comment by justbur** [comment]
@TheBB should be fixed in develop since that package is gone now

**Comment by TheBB** [comment]
Right, we'll have to keep it in mind if we enable it again though.

**Comment by justbur** [comment]
Absolutely, I was thinking you could tag it though

**Comment by gttiankai** [comment]
Also happens for me on Mac os x 10.11 and the  emacs version is gnu-emacs 24.5.1.

logs:

line-move-visual: Beginning of buffer [7 times]
spacemacs has auto save data; consider M-x recover-this-file
When done with a buffer, type C-x #
line-move-visual: End of buffer [7 times]
Modified buffers exist; exit anyway? (y or n) y
apply: Device 1 is not a termcap terminal device

**Comment by syl20bnr** [comment]
This is another issue when quitting Emacs. This is due to  bracketed-paste-terminal package (not sure about the name of the package). We have to look at it.

**Comment by syl20bnr** [comment]
@gttiankai can you open a new issue ?

**Comment by hemanta212** [comment]
I am having this issue in wsl2 archlinux while launching spacemacs in vcxrv. --debug-init doesnot give any error besides 

error: Device 1 is not a termcap terminal device

However it works fine in termnal.

**Comment by robinsrk** [comment]
I also have this same issue while running various options, like exporting org mode to pdf, trying the org-notifications etc. how to fix this problem? i am on arch linux
