### ISSUE TITLE
[update error] Invalid version string: 'nil'

### ISSUE THREAD

**Issue by darker0n** [syl20bnr/spacemacs#2795]
In develop branch I can't update spacemacs

**Comment by robbyoconnor** [comment]
Give me <kbd>SPC hds</kbd> please?

**Comment by robbyoconnor** [comment]
I know that the ruby-on-rails layer is currently broken...

**Comment by bmag** [comment]
Please see https://github.com/syl20bnr/spacemacs/issues/839#issuecomment-135028793.
If you uncomment this [line](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L691) then you will be able to see in the `*Messages*` buffer which package causes this error. You can exclude that package as a temporary workaround.

**Comment by darker0n** [comment]
@bmag's working for me :+1:
