### ISSUE TITLE
company-quickhelp-mode is off

### ISSUE THREAD

**Issue by malchmih** [syl20bnr/spacemacs#2811]
Don't know why, but while company mode is on (e.g. in .spacemacs file), company-quickhelp-mode is off.
I have
* auto-completion layer
* auto-completion-enable-help-tooltip t
* NOT console Emacs running ( (display-graphic-p) evaluates to true)
* 24.4.1 Emacs version

Could anyone help, please?

**Comment by usharf** [comment]
It works for me, though depending of the frame's width, the placement of the tooltip menu can be really frustrating, as it makes it impossible to see the menu options themselves...

**Comment by malchmih** [comment]
@usharf You can make it appear only manually, as described here: https://github.com/expez/company-quickhelp#usage
Still can't make this mode to be on automatically.

**Comment by usharf** [comment]
@malchmih OK. Taught it was the same as `auto-completion-enable-help-tooltip` ...?

**Comment by usharf** [comment]
I have something like this in my dotspacemacs (only first option is relevant of course):

```emacs-lisp
     (auto-completion :variables
                      auto-completion-enable-help-tooltip t
                      auto-completion-enable-sort-by-usage t)
```

**Comment by malchmih** [comment]
Thanks @usharf . I've checked my .spacemacs file and realized that I've misplaced the config for auto-completion layer. It works now.
