### ISSUE TITLE
python-send-shell-buffer not working and C-u C-c C-c not working as expected

### ISSUE THREAD

**Issue by rafaelgp** [syl20bnr/spacemacs#2820]
Hello,

Using Emacs 24.5.1 in a Virtual Box with Debian Stretch and LXMD
Spacemacs v 0.103.5
Python 2.7.10 and 3.4.3+ installed
My current [emacs configuration] (https://github.com/rafaelgp/dotspacemacs)

This is what I do:

- Open file `test.py`
- SPC m s i (it opens ipython, for some reason it starts in the 4th command, but it doesn't matter)
- SPC u m s b 

This is the output:
![](http://clients.tourvista.co.uk/vt/zip/tmp/python-s-u-m-s-b.jpg)

Note the message `Beggining of buffer` at the bottom

If I run `C-u C-c C-c` this is what I get:

![](http://clients.tourvista.co.uk/vt/zip/tmp/python-c-u-c-c-c-c.jpg)

It didn't run the function main.
If I run this command opening emacs like `emacs -q` it prints all 3 messages as expected.

Is there something I'm doing wrong?

**Comment by bmag** [comment]
You mention that you type `SPC u m s b`. It should be `SPC u SPC m s b`.

**Comment by cpaulik** [comment]
I think you need to use `SPC u C-c C-c` since `C-u` is bound to `evil-scroll-up`.

For me both `SPC m s b` and `SPC u C-c C-c` execute the main function.

**Comment by rafaelgp** [comment]
@bmag You're right. `SPC u SPC m s b` works as expected.
@cpaulik You're right too. `SPC u C-c C-c` runs what's inside the main function.

Now it's time to me to make a keybinding to run these commands quicker ;-)

Thank both of you!

**Comment by TheBB** [comment]
I assume you know that `,` is bound to `SPC m`.

**Comment by rafaelgp** [comment]
Just looked this up by using `SPC h d k` and `,` is bound to `evil-repeat-find-char-reverse`

**Comment by TheBB** [comment]
If you're in a mode with mode-specific bindings, `,` should be bound to `SPC m`. Which mode were you in when you did that?

**Comment by rafaelgp** [comment]
Python-mode

**Comment by TheBB** [comment]
Hm, that should work then.

**Comment by rafaelgp** [comment]
Sorry but when I press `,` I get `No previous search` at the bottom

**Comment by cpaulik** [comment]
@rafaelgp Have you tried opening a second python file? I've had this issue in the past on the first python file I opened in a session.

**Comment by rafaelgp** [comment]
I tried by opening other python file but `,` is still bound to `evil-repeat-find-char-reverse`.
Also tried by restarting emacs just in case but still same thing.

**Comment by syl20bnr** [comment]
@rafaelgp did you change the variable `dotspacemacs-major-mode-leader-key` in your dotfile ?

**Comment by rafaelgp** [comment]
Look what I've found in my .spacemacs file:

```
   dotspacemacs-major-mode-leader-key "nil"
```

Thanks @syl20bnr
