### ISSUE TITLE
parentheses highlighting inconsistent on closing parentheses

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#2823]
show-smartparens-mode behavior is inconsistent on closing parens.

On opening parens:

    *    *
    ((()))
    ^

When the cursor is at the caret, the two starred parens are highlighted, but for closing parens it does this:

     *  *
    ((()))
         ^

The fix is to set `sp-show-pair-from-inside` to `t`:

    *    *
    ((()))
         ^

**Comment by TheBB** [comment]
Maybe you can PR this?

**Comment by sooheon** [comment]
This was a conscious decision, related to the change with `evil-move-beyond-eol`. Can't find the commit right now, but I think syl20bnr's decision was to simply adhere a bit closer to the emacs idea of cursor location, which is important for evaluating sexps.

While it may be unnatural when you move between parens by `%`, it is completely natural and correct if you use paredit/smartparens/lispy commands to move my sexps. In other words, it's not really a bug, but there is room for personal taste and I think a documented toggle may be needed.

**Comment by darkfeline** [comment]
Derp, this is basically a variant on the other issue I made: https://github.com/syl20bnr/spacemacs/issues/2525

I don't know what, if anything, should be done for this.  Maybe spacemacs needs a toggle that sets up everything properly depending on whether `evil-move-beyond-eol` behavior is wanted or not?

**Comment by sooheon** [comment]
I think this paren highlighting behaviour is already dependant on `evil-move-beyond-eol`, so theoretically simply setting that to nil should take care of both issues.

**Comment by TheBB** [comment]
The user still has to set both, because there's no user code that runs between `(setq evil-move-beyond-eol nil)` in `init-evil` and `(setq sp-show-pair-from-inside (not evil-move-beyond-eol))` in `init-smartparens`.

**Comment by syl20bnr** [comment]
@TheBB I believe that `dotfile/post-init-xxx` should work out of the box :-)

What I would like in Spacemacs is the alternative fix: the parens behind the cursor block should be always highlighted. It is better for dealing with lisps and I feel that sane natural defaults in Spacemacs should go towards lisps as Emacs is the host.
For now this is a mix of the two approaches and it sucks...

We should have a settings in Spacemacs to choose to highlight `current` or `previous` pair, with a default setup to `previous`.

It may require some PR for smartparens/evil (I don't know exactly where is the inconsistency - if there is one).

**Comment by syl20bnr** [comment]
For the `evil-move-beyond-eol` issue, I think we can get best of both worlds, I'll look into evil to propose a PR to have consistent `$` and `x` even with `evil-move-beyond-eol` set to `t`.

**Comment by TheBB** [comment]
> @TheBB I believe that `dotfile/post-init-xxx` should work out of the box :-)

I confess I didn't actually try, but that's not what I see. It's off topic for this issue though, so I can look at it later.

**Comment by syl20bnr** [comment]
(@TheBB indeed, doftile owner is a special case: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L723-L726 should be trivial to add support for an optional init function)

**Comment by syl20bnr** [comment]
This is a pretty old report, @darkfeline do you still have this behavior ?

**Comment by darkfeline** [comment]
Nope, it's fixed for me.
