### ISSUE TITLE
Can't refresh magit status window on develop

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#2826]
Previously one could refresh `magit-status` by pressing `g`, now `g` acts as in vim. Reproducible on develop.

**Comment by bmag** [comment]
The `magit-status` buffer is evilified, as explained in https://github.com/syl20bnr/spacemacs/blob/4bec7fb74a8e7b4fb973a2733262b0905a24aaa7/doc/CONVENTIONS.org#evilify-buffers. Refresh is now bound to `C-S-g`.

**Comment by TheBB** [comment]
@bmag got it right. This is not a bug.

**Comment by person808** [comment]
@TheBB Maybe it should be documented?

**Comment by TheBB** [comment]
Yeah, I suppose.

**Comment by justbur** [comment]
The key for refresh is in the magit popup after #3578 which should resolve this
