### ISSUE TITLE
Improve Info reading experience

### ISSUE THREAD

**Issue by xfq** [syl20bnr/spacemacs#2828]
I'm aware of #902, but using Info mode in Spacemacs is still a PITA.  For example:
- I can't use `l` to go back to the last node I was at.
- `b` goes to beginning of node instead of the beginning of the previous word, and I can't use `g g` to go to the first line (of the node).
- Visual mode can't be entered with `v`.
- `n` doesn't repeat the last search.

**Comment by sooheon** [comment]
Yep, this is one of those cases where the modal keys defined by info-mode and evil really clash, and it's unclear which is the best way to reconcile them. FWIW, I think that `l` behaviour is replicated by `C-o`, but then `C-i` is something different, and there isn't any kind of mnemonic symmetry like `l` and `r` or `C-i` and `C-o`. It's just a complete mixup right now.

I actually think the modal keys of info-mode are well thought out, and prefer just learning them and minimizing vi keys, but others may disagree. Just getting used to emacs keys isn't bad (i.e. `M-f M-b` for your second point, and `C-spc` for selection`).

**Comment by felipe-barros** [comment]
In my experience I always switch to Holy when browsing Info files. Maybe there could be some sort of warning for the user that in this mode Evil isn't "supported"? Like a red-something in the modeline?

**Comment by sooheon** [comment]
@felipe-barros yeah, just going to holy-mode and doing it the emacs way does seem more "pure" and edge-case free, for things like info-mode or magit. But the vinegar layer here, for example, is a case of evil integration done right, imo.

**Comment by felipe-barros** [comment]
@sooheon although after switching to Spacemacs from Vim I see myself more and more inclined to using regular Emacs keybindings everywhere and Vim only for text editing (using Hybrid for now) I'm not against Evil integration at all. But I agree with you that with Magit/Info, default means better, at least for now. I hope it changes somewhere in the future, but for now, I think the only thing missing is a nice warning "hey, this is unexplored land, be careful and if you need help, press h for emacs intro" or something :)

**Comment by myrjola** [comment]
What about not evilifying Info-mode at all? I would like to have it modal. In-buffer navigation and visual-mode selections is most comfortable in the normal state. Navigating the Info hierarchy can be done effectively with the standard info-mode keybindings. There was probably some clashes between info-mode and the insert-state, so maybe emacs-state should be used instead of insert state.
