### ISSUE TITLE
org-capture opening helm buffer

### ISSUE THREAD

**Issue by JoshTGreenwood** [syl20bnr/spacemacs#2830]
# The behavior I expect
run `org-capture`
hit the key for the relevant template
temporary buffer named *Capture* opens in insert mode

# The behavior I'm seeing
run `org-capture`
hit the key for the relevant template
temporary buffer named *Capture* opens
cursor is in a helm buffer located in the current working directory running `basic-save-buffer`

screenshot: https://files.gitter.im/syl20bnr/spacemacs/ZJj2/Screen-Shot-2015-08-30-at-3.43.26-PM.png

@CestDiego and I traced this behavior back to the `toc-org` package.  Here is the relevant backtrace:
https://files.gitter.im/syl20bnr/spacemacs/DCUP/Screen-Shot-2015-08-30-at-6.23.09-PM.png

The temporary solution for me is to just add:   `dotspacemacs-excluded-packages '(toc-org)`.

**Comment by TheBB** [comment]
Does this happen if you set `org-default-notes-file`?

**Comment by snosov1** [comment]
There was a very short time period (a day or two), when toc-org was immediately saving the file upon opening. It doesn't work like this for several weeks already. 

So, my guess is that you have this "immediately saving" version. Simple updating should resolve it.

**Comment by JoshTGreenwood** [comment]
Confirmed working after re-including `toc-org` and updating spacemacs.

**Comment by CestDiego** [comment]
Great this thing got resolved :D
