### ISSUE TITLE
motion f is not defined?

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#2831]
When in normal mode, the `f` motion is not defined?

It's really a critical bug...

**Comment by syl20bnr** [comment]
You are not the first to say this, there is another issue opened on this, we are several persons which are not able to reproduce the bug. If you have upgraded your packages recently, can you try an older version of evil ? Check your rollback directory in ~/.emacs.d/.cache/.rollback and look for an older version and replace it in your elpa folder.

**Comment by syl20bnr** [comment]
duplicate of #2813

**Comment by zilongshanren** [comment]
@syl20bnr  
My workaround is by disable `evil-escape` package.

**Comment by syl20bnr** [comment]
@zilongshanren I rewrote evil-escape from scratch, grab the version 3.0 and give it a try. It removes all the limitations of the previous implementation:
- can now be used in macros
- can now use any key sequence

**Comment by syl20bnr** [comment]
May take some time before being available in MELPA.

**Comment by zilongshanren** [comment]
@syl20bnr 
Thanks, I will give it a try.
