### ISSUE TITLE
Documentation link on spacemacs start up screen broken

### ISSUE THREAD

**Issue by yeonsh** [syl20bnr/spacemacs#2833]
When I click the link, github returns 404 not found. 

https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md

There are files with '.org' extension on https://github.com/syl20bnr/spacemacs/blob/master/doc/

**Comment by robbyoconnor** [comment]
Which link? Try on `develop` and see if it's fixed.

**Comment by robbyoconnor** [comment]
Are you up to date? do `git pull --rebase origin master`

**Comment by yeonsh** [comment]
Sorry for the confusion. I think I am using recent version. I was using 0.102.x.

**Comment by robbyoconnor** [comment]
:smile_cat:
