### ISSUE TITLE
Prefix command names must be unique

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#2839]
We need to implementation auto-detection of duplicated prefix command names and warn about them in the messages buffer.

**Comment by syl20bnr** [comment]
`which-key` has a feature to rename prefix command names so we could decide about a convention that resolve clashes and is easy to rename by `which-key`.

**Comment by justbur** [comment]
I'd say just name the prefix by it's key sequence, like "spacemacs-prefix-s", "spacemacs-prefix-sa", etc. For major-mode specific bindings, "spacemacs-prefix-[major-mode]-s".

We can handle the translation in which-key like you suggest. Of course, abstracting the key binding code like in #2731 will help in this ;-)

**Comment by justbur** [comment]
Even better I can just go around the builtin declare prefix stuff and create a which key specific declare prefix command that doesn't require unique names. It would be an alist with the key sequence mapped to a name that's all.

**Comment by justbur** [comment]
I just added it as an option to which-key. Here's a sample
```elisp
(which-key-declare-prefix-names
  "a"   "applications"
  "ai"  "applications-irc"
  "as"  "applications-shells"
  "b"   "buffers"
  "bm"  "buffers-move"
  "c"   "compile/comments"
  "C"   "capture/colors")
```
There's a corresponding
```elisp
(which-key-declare-prefix-names-for-mode 'emacs-lisp-mode
  "SPC m e" "eval"
  "SPC m i" "ielm")
```

**Comment by syl20bnr** [comment]
oh yeah :+1:
