### ISSUE TITLE
Running SPC m r d f to run js-doc-insert-function-doc causes Emacs to hang

### ISSUE THREAD

**Issue by bzalasky** [syl20bnr/spacemacs#2840]
This occurs if the cursor isn't positioned right on a function (say it's right above it). While it can certainly be worked around, at the very least, it should probably provide some kind of feedback and not hang. I'll take a look at the repo that supplies this functionality and see if a solution jumps out at me.

**Comment by TheBB** [comment]
This seems to be an upstream problem. The binding calls `js-doc-insert-function-doc`, which is part of the [js-doc](https://github.com/mooz/js-doc) package.

**Comment by StreakyCobra** [comment]
As there are no news from the original author, as requested, I'm closing this issue.
