### ISSUE TITLE
setting python venv does not automatically specify virtualenv shell path

### ISSUE THREAD

**Issue by ipsod** [syl20bnr/spacemacs#2841]
I was unable to get spacemacs to use a python virtual environment, but found some help in the chat.

In order to get spacemacs to use a python virtual environment, it's required to run:
`(setq python-shell-virtualenv-path "~/path/to/env/")`

This should be noted in the documentation until `pyvenv-workon` sets the path automatically (as it ought to).

**Comment by CestDiego** [comment]
Also why are we having `pyvenv` and `pyenv` if `pyvenv` works most of the time?

**Comment by TheBB** [comment]
Yeah, that *is* confusing.

**Comment by cpaulik** [comment]
`pyvenv-workon` does set the path correctly. At least for me. You need to have set the `$WORKON_HOME` environment variable however. `pyvenv-activate` on the other hand queries for a folder that is not dependent on this environment variable.

´pyenv` is also very handy. I would not remove one but maybe we can set one as default and let users choose the other one if they want to like with the python test runner.

**Comment by CestDiego** [comment]
what does `pyenv` has that `pyvenv` doesn't?

**Comment by cpaulik** [comment]
`pyenv` can switch python versions without need for a virtualenv. It can also automatically switch python versions when you enter a folder. 

See https://www.brianthicks.com/2015/04/10/pyenv-your-python-environment-automated/ for a practical example.

**Comment by autosquid** [comment]
> pyenv can switch python versions without need for a virtualenv.

AFAIK, `pyenv` and `virtualenv` serves different purpose, and I need `virutalenv` for *environment* isolation.

As @ipsod , the way to use only virtualenv should really be noted in the documentation.

I think `pyenv` should only be made an option in this layer for those like me who dislike `pyenv` every much due to mess in tackling system-side-package well.

There are too many packages for python in emacs, and too many are doing it wrong. A clean and right solution needs real experts.

**Comment by TheBB** [comment]
The reporter said

> This should be noted in the documentation until pyvenv-workon sets the path automatically (as it ought to).

Pyvenv does this, and apparently already did at the time of reporting.

**Comment by autosquid** [comment]
@TheBB  but `pyvenv-workon` is not in doc. neither. so, there is actually nothing in the doc. on how to setup virtualenv except the two links of pyenv and pyvenv.

**Comment by TheBB** [comment]
Well... open a new issue then. I don't want to reopen old issues just because something else vaguely related to the original problem is still unsolved.
