### ISSUE TITLE
What is the appropriate function to disable auto-completion with a mode hook

### ISSUE THREAD

**Issue by x-ji** [syl20bnr/spacemacs#2848]
Since a few days ago, whenever I type anything in org-mode, Emacs tries to supply me with autocompletion from *every single word* in the document, which is quite crazy. I added  `(add-hook 'org-mode-hook (lambda() (auto-complete-mode -1)))` to no avail. And if I write `(add-hook 'org-mode-hook (lambda() (spacemacs/toggle-auto-completion)))`, all I get is:

```
Enabled auto-completion (using company).
auto-completion enabled.
```

which seems to not change anything. Which is the function I should call in the hook in this case?

**Comment by robbyoconnor** [comment]
Don't load the auto-completion layer? Alternatively (this only works if you don't do the latter), <kbd>SPC t a</kbd> will toggle it off...you can toggle it easily...

**Comment by person808** [comment]
https://github.com/syl20bnr/spacemacs/blob/master/doc/HOWTOs.org#disable-company-for-a-specific-major-mode

**Comment by x-ji** [comment]
@robbyoconnor Sure that's why I said I was trying to disable it automatically. I had to literally press that combination every time I open an org buffer...

**Comment by x-ji** [comment]
@person808 Thanks. Guess I haven't read the updated docs for a long time

**Comment by norcalli** [comment]
The link is broken for the HOWTO now.

**Comment by StreakyCobra** [comment]
@norcalli http://spacemacs.org/doc/FAQ.html#orgheadline23 , available under `SPC f e f` where you can search in the FAQ.

**Comment by norcalli** [comment]
Ah and it looks like the FAQs have updated. Thanks! Sorry for an easy question. I'll consult fef next time

Sent from Outlook Mobile




On Sun, Apr 3, 2016 at 2:37 PM -0700, "Fabien Dubosson" <notifications@github.com> wrote:












@norcalli http://spacemacs.org/doc/FAQ.html#orgheadline23 , available under SPC f e f where you can search in the FAQ.
