### ISSUE TITLE
Switch JavaScript from web-beautify to esformatter based system

### ISSUE THREAD

**Issue by Akkuma** [syl20bnr/spacemacs#2850]
Currently jsbeautify is vastly inferior in capabilities than something based on https://github.com/millermedeiros/esformatter. There is https://github.com/brettlangdon/jsfmt.el, which should provide a starting point for spacemacs.

**Comment by kRITZCREEK** [comment]
If this doesn't make it into the JS layer it would still be really nice to have it in the React layer as it can format JSX.

**Comment by gavocanov** [comment]
+1

jsbeautify does not even talk ES6 yet, it's almost unusable for React, been using esformatter/esformatter-js along with eslint/eslint-plugin-react in VIM for months, beautiful combo.
