### ISSUE TITLE
Helm breaks when losing focus

### ISSUE THREAD

**Issue by baem-universe** [syl20bnr/spacemacs#2851]
When switching out ouf helm-find-files to another buffer one cannot switch back. Trying to select the helm window  with <spc-2> wont work. According to the orange square spacemacs maybe assumes that the helm buffer is a normal file.

![helm](https://cloud.githubusercontent.com/assets/4263821/9609554/82400a4a-50d4-11e5-8073-b368acd5113d.PNG)

**Comment by Devagamster** [comment]
I've encountered this as well. I find triggering helm afterwards gets it to close. A related problem: if you kill the helm window after it gets glitched, you are unable to move the cursor until you move the cursor with the mouse. To get helm to pop again you have to trigger it twice.

**Comment by robbyoconnor** [comment]
I also encounter this -- It's never been enough for me to file an issue but it's annoying as hell...@tuhdo?

**Comment by TheBB** [comment]
Yeah, me too. I just do as @Devagamster and fire up a quick `SPC b b ESC` to get it away. You can also get to the minibuffer with an appropriate number of `SPC w j` at which point you can also `ESC` out. But it would be nice if there was some kind of "bring me to the minibuffer" binding.

**Comment by TheBB** [comment]
Actually, turns out there is one: `SPC w b` brings you back to the minibuffer if you happen to be out of it. I think that's the best way to deal with this problem.

**Comment by robbyoconnor** [comment]
I would much rather have had the text input for helm had remained in the minibuffer...The way it is right now breaks shit.

**Comment by justbur** [comment]
I also vote to use the minibuffer again for helm. I always look in the wrong place for the helm input :-)

**Comment by Devagamster** [comment]
Is this a setting that was changed?

**Comment by TheBB** [comment]
Yes, you can set `helm-echo-input-in-header-line` to `nil`.

**Comment by syl20bnr** [comment]
This is one quirk of the UI that we have to live with. Personally I don't mind such issue which results on a mistake on my part, when I learn my editor I also learn how to get out bad situations and rough edges :-) 
My solution to this issue was not as elegant as yours, I used to focus the helm buffer back then `SPC w c` and `fd` to get out the minibuffer.

Thank you for the tips `SPC w b` works like a charm :-)

We should document this.

**Comment by robbyoconnor** [comment]
Works like a charm!

**Comment by zilongshanren** [comment]
+1 for `SPC w b`  :+1:
