### ISSUE TITLE
Using tern in web-mode via company

### ISSUE THREAD

**Issue by madhat2r** [syl20bnr/spacemacs#2854]
Has anyone gotten tern completion via company to work in web-mode? When I add company-tern to the backends, it works, but nothing else completes in company-web (i.e. no html, css, completions). I am new to company, coming from auto-complete. I had my old configs working with ac with tern and all the other completions worked great.

Does anyone have any ideas on how to get this working.

**Comment by TheBB** [comment]
You need the `company-web-html` backend for HTML and `company-css` for CSS. I don't know if the latter is smart enough to work embedded in HTML.

You can add them all to `company-backends-web-mode`.

**Comment by madhat2r** [comment]
@TheBB `company-web-html`  seem to work fine as it is configured by default. However, adding another backend seems to take over everything. If I add `company-tern` or `company-css` to the `company-backends-web-mode` then that is all I get, not a combination of backends.

Perhaps I am doing something wrong, I am not sure, like I said new to company. All I know is that `auto-complete` works fine, as-in, completes html in html, css in css, and tern in javasctipt blocks.

Maybe company is just not capable. I was trying to make the switch as it seems that is the preferred auto-complete engine for spacemacs.

**Comment by TheBB** [comment]
Use a list of backends together.

`(push '(company-web-html company-tern company-css) company-backends-web-mode)`

**Comment by madhat2r** [comment]
Thanks @TheBB !! that did the trick.
