### ISSUE TITLE
Symbol's value as variable is void: golden-ratio-exclude-buffer-regexp

### ISSUE THREAD

**Issue by srid** [syl20bnr/spacemacs#2855]
`M-x golden-ratio-mode` opens a buffer with this message:

```
Error (use-package): golden-ratio :config: Symbol's value as variable is void: golden-ratio-exclude-buffer-regexp
```

**Comment by syohex** [comment]
https://github.com/roman/golden-ratio.el/pull/58

That variable was introduced 2 weeks ago.  Do you use latest golden-ration ? If not, please upgrade golden-ration(`M-x package-install`, `golden-ratio`) and retry.

**Comment by srid** [comment]
Latest version works.
