### ISSUE TITLE
Strange faces in spacemacs/helm-find-contrib-file

### ISSUE THREAD

**Issue by d12frosted** [syl20bnr/spacemacs#2862]
When I call that function (`SPC f e c`) I see following in emacs.

![](https://www.dropbox.com/s/ldwnm1afhp81yao/Screenshot%202015-09-02%2018.05.10.png?dl=1)

As you can see the `..` directory looks strange. It's not selected, but has different faces. For example, when I `SPC f f` I see following thing in emacs.

![](https://www.dropbox.com/s/del1gk822g3e8k7/Screenshot%202015-09-02%2018.06.08.png?dl=1)

I am using `spacemacs-light` theme. But I could also reproduce it in `apropospriate-light`, `spacemacs-dark`.

![](https://www.dropbox.com/s/a07iymn4e1a7ky6/Screenshot%202015-09-02%2019.05.06.png?dl=1)

![](https://www.dropbox.com/s/yqysulrkcpe54m5/Screenshot%202015-09-02%2019.10.17.png?dl=1)

Looks pretty annoying.

**Comment by robbyoconnor** [comment]
That's an actual exclamation mark....I see nothing wrong. The exclamation mark is there for categories.

**Comment by TheBB** [comment]
He's talking about the different color for the `.emacs.d/contrib/..` entry.

**Comment by d12frosted** [comment]
Yeah. Sorry for confusion. I thought that 

> As you can see the .. directory looks strange. It's not selected, but has different faces.

is clear enough.

**Comment by d12frosted** [comment]
@TheBB pointed out that helm has special face for dotted symlinked directories. My `emacs.d` is symlink, that's why it's looking in this way. So it's not a bug :smile: Thanks for help!
