### ISSUE TITLE
Can't scale up text (but can scale it down)

### ISSUE THREAD

**Issue by nhll** [syl20bnr/spacemacs#2865]
So using the `osx` layer I can make the text in the current buffer smaller by pressing `⌘` and `-`, but scaling it up with `⌘` and `+` doesn't work for me. It says "s-+ is undefined".

According to the `osx` layer's README, all it really does in that respect is setting `⌘` to `super`, so I'm assuming `osx` has nothing to do with my problem.

**Comment by sooheon** [comment]
This is a typo in the readme. The binding is actually `S-=`. You can check for yourself by going into keybindings.el.

**Comment by nhll** [comment]
You're right, this works. Wouldn't it be much more intuitive to have it bound to `S-+` by default?

**Comment by sooheon** [comment]
You can easily add it yourself with `(global-set-key (kbd "s-+") 'spacemacs/scale-up-font)`. `S-=` is the default in OS X applications, so it's reasonable to have it that way in the OS X layer. The docs should be fixed, though.

**Comment by StreakyCobra** [comment]
For the record: #3768
