### ISSUE TITLE
Spacemacs develop branch frozen when using Emacs 24.5

### ISSUE THREAD

**Issue by lvicentesanchez** [syl20bnr/spacemacs#2869]
I have been using the develop branch for a while and suddenly is not working any more with my emacs 24.5 (compiled from source).

I was working fine until a few days ago, now no matter what I try, the UI is frozen and literally nothing works.. not even key bindings.

Is there anything I can do to debug the issue? Anything that doesn't involve accessing emacs buffers,...

Btw... v103.6 works flawlessly.

**Comment by lvicentesanchez** [comment]
Actually I have the same problem with v103.6 ... so it might be one of the packages :/ I will disable everything.

**Comment by lvicentesanchez** [comment]
Didn't make a different. I had to rollback to emacs 24.4 and now everything works normally.

**Comment by stormpat** [comment]
I have the same problems with 24.5

**Comment by jgmize** [comment]
I'm running 24.5 and spacemacs 0.104.2 and when I first launch I get the same behavior-- completely frozen UI, no response to any keybindings. Based on the comments on this issue I was about to downgrade to emacs 24.4, but when switched back it was responsive again. I tried opening and closing multiple times in both the console and the gui, and the same behavior is repeated. The delay is variable, but it usually becomes responsive after a minute or two.

**Comment by justbur** [comment]
Sounds to me like it's trying to install one of the "preloaded" packages and something it failing. Probably the network.

**Comment by lvicentesanchez** [comment]
that happens the first time you open Emacs after everything has been
installed and happens every single time so it can't be a network issue

**Comment by justbur** [comment]
Well you can try `emacs --debug-init --timed-requires` If there's an error it will popup a debugger with a backtrace that you can post. If there's a package that is taking a long time to load, it will be recorded in the *load-times* buffer

**Comment by TheBB** [comment]
I can't link as I'm on mobile but if you check out helm bug number 1000 I can almost guarantee that is what you are experiencing, @jgimze

**Comment by jgmize** [comment]
@TheBB you were right, thanks! https://github.com/jgmize/dotfiles/commit/3c3239e8601c929d472ac1bf3fddf42c9bdf5171 resolved the issue for me. Thanks!

@justbur FYI `emacs --debug-init --timed-requires` didn't work for me; I got  `Unknown option: --timed-requires` and based on your comment https://github.com/syl20bnr/spacemacs/issues/3317#issuecomment-146881410 I believe that's because it's a develop feature

**Comment by justbur** [comment]
It is a develop feature. Sorry I should have mentioned that

**Comment by lvicentesanchez** [comment]
The workaround also works for me; one curious thing is that I only have
this problem under Ubuntu 15.04; my macosx 24.5 installation works without
having to do any workaround.

2015-10-31 17:11 GMT+00:00 Justin Burkett <notifications@github.com>:

**Comment by StreakyCobra** [comment]
As it's an upstream bug already reported, there is nothing more that we can do on our side, so I'm closing the issue. In any case, feel free to open a new one in case of troubles :relaxed:
