### ISSUE TITLE
develop - `fd` no longer works to escape helm windows

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2871]
Steps to reproduce:

1.  Open up your project
2.  Type `SPC s p`
3.  Try to escape with `fd`.  No dice.  

Seems to work fine with `C-[`, `ESC`, and `CTRL-G` but not `C-c` or `fd`.  

I am using `hybrid` mode.

**Comment by robbyoconnor** [comment]
Update packages maybe...I think @syl20bnr rewrote evil-escape...at least I remember him talking about it the other day

**Comment by CestDiego** [comment]
yep this might be actually good...but it's actually a bug...if you `fd` quickly the succession is recognized, it's just that it doesn't take action.

**Comment by synic** [comment]
This is something new, it seems to coincide with evil-escape 3.x, but I'm not sure.  Prior to that it worked fine.

**Comment by synic** [comment]
This appears to be fixed now, commit b53b5db9674c4beaab7eceb4bd080515628f0293, and evil-escape 20150907.2227.

**Comment by geo7** [comment]
@synic if this is all good now can you close the issue please :+1:

**Comment by robbyoconnor** [comment]
:+1:

--Rob
