### ISSUE TITLE
Swank.js for the JS layer

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2873]
I wanted to open a dialogue about potentially integrating [Swank.js](https://github.com/swank-js/swank-js) into the JS layer...Is it worth the effort?

**Comment by oppenlander** [comment]
See #483 for previous discussion. 
I haven't put any more thought into it. Last time I tried nothing worked well enough.

**Comment by robbyoconnor** [comment]
@oppenlander I guess I didn't do a search too well...eeek

**Comment by robbyoconnor** [comment]
Should this be closed?

**Comment by mbertheau** [comment]
Yes! :)

**Comment by robbyoconnor** [comment]
Motion carries. Yays have it -- This is dead...now where do I dump the body?
