### ISSUE TITLE
Elisp TODO Doesn't work nicely with current Yas Snippet (Prog Mode)

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#2875]
Currently the YasSnippet for `TODO` in Elisp will format things poorly when using
`gg=G` as it only uses one ` ; ` at the start of the line.

## Current snippet: 

```text
# -*- mode: snippet -*-
# name: todo
# key: t
# --
`(yas-with-comment "TODO: ")`
```

#### Formatted output (todo is forced far right):

```elisp
(defun somecoolfunction ()
  (foo
   (bar
                                        ; TODO: Something todo
    baz)))
```

## Edited snippet :

```text
# -*- mode: snippet -*-
# name: todo
# key: t
# --
`(yas-with-comment "; TODO: ")`
```

#### Formatted output:

```elisp
(defun somecoolfunction ()
  (foo
   (bar
    ;; TODO: Something todo
    baz)))
```

### Temp solution

Opening snippets in an elisp file with `SPC i s` then `f2` to
edit the snippet, change it to the second example then `C-c C-c`
to save, when asked whether to save to a new file say `no` (or
`n`) and it'll just over write the old one.

**Comment by TheBB** [comment]
This is yasnippet's bug, not ours. Single-semicolon comments in elisp are for inline comments to the right of code, and double-semicolon comments are for comments that take up a whole line.

**Comment by geo7** [comment]
@TheBB cool - shall I close?

**Comment by TheBB** [comment]
If you report it to yasnippet drop a link here.
