### ISSUE TITLE
php-extras package miss

### ISSUE THREAD

**Issue by netroby** [syl20bnr/spacemacs#2878]
installing (php): php-extras... [1/1]
Package php-extras is unavailable. Is the package name misspelled?

so we can not load php-extras package,

**Comment by robbyoconnor** [comment]
Seriously, Duplicate of [all of these](https://github.com/syl20bnr/spacemacs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+php)

**Comment by robbyoconnor** [comment]
Also report your version number...which you didn't do...for example are you on `master` or `develop`?

**Comment by netroby** [comment]
I am using master

git clone --recursive https://github.com/syl20bnr/spacemacs ~/.emacs.d

**Comment by robbyoconnor** [comment]
@netroby, 

The fix is to use `develop`. 

`cd ~/.emacs.d && git checkout develop && rm -de elpa/`

**Comment by robbyoconnor** [comment]
@netroby, 

The fix is to use `develop`. 

`cd ~/.emacs.d && git checkout develop && rm -fr elpa/`

**Comment by netroby** [comment]
Thanks, i know it. already fixed it

**Comment by robbyoconnor** [comment]
Ah, great :heart:
