### ISSUE TITLE
"Paste" mode?

### ISSUE THREAD

**Issue by hosh** [syl20bnr/spacemacs#2881]
Is there a "paste" mode? 

Activating it means the editor doesn't do anything special. I can paste things without things like smarparens or syntax assist doing anything.

**Comment by geo7** [comment]
> I can paste things without things like smarparens or syntax assist doing anything.

I'm not sure what they *should* do in this context? Can you elaborate a bit more please? 

If you search the docs for `paste` you'll find info about `Paste Micro-State`, I'm not sure if this is what you're referring to though .

**Comment by hosh** [comment]
@geo7 It's the vim "paste" mode, which turns off all formatting, auto indenting, smartparens, etc in insert mode. This allows things pasted from the web to go straight in. I usually turn this on in vim with:

`:set paste`

and then re-enable everything with

`:set nopaste`

**Comment by geo7** [comment]
Oh right yeah  

```
" toggle Vim pastemode
set pastetoggle=<F3>
```


I don't need anything like that in Emacs - I just paste and It's fine, this is using the GUI version. I think that the terminal Emacs in version 24.5 has this sorted using bracketed paste or something - I don't use terminal emacs though.

**Comment by agriffis** [comment]
See #3064

**Comment by hosh** [comment]
@agriffis @geo7 I can give that a shot, though it isn't just indentation that's the problem.

**Comment by geo7** [comment]
> though it isn't just indentation that's the problem

Can you please just write out exactly what the problem is, what you want to happen etc etc otherwise it's quite difficult to actually help with anything. System info, emacs version, spacemacs commit would probably be relevant as well. :+1:

**Comment by geo7** [comment]
@TheBB think this can be closed

**Comment by hosh** [comment]
`nopaste` mode set means when I paste something in there, there are zero autoformatting. So no, "just pasting it and it is fine" isn't fine when I don't want any changes to the formatting to happen.

At this point, I just open up the file with vim and nopaste it into there.

**Comment by acbox** [comment]
@hosh Try setting the major mode to plaintext with `text-mode` before pasting. That seemed to work for me to emulate Vim's `:set paste`. If you're not sure what the existing mode is (to revert it after pasting), you can check it with `M-x describe-variable` and entering `major-mode`.
