### ISSUE TITLE
iedit not working

### ISSUE THREAD

**Issue by fkjogu** [syl20bnr/spacemacs#2884]
This is spacemacs on *develop* (82c905559) with just the *emcas-lisp* layer activated. The video below shows what's happening in text-mode. I observe the same effect in LaTeX-mode.

https://vid.me/pxfo
First I was typing `*` `e` `I` test and then `vwhh` `SPC s e`

Description of the video:
- First command just changes background color of all occurrences of the word under the cursor, `e` has no effect and `I` just inserts text in front of the next occurence
- Second command just produces an red block cursor on the last letter of the selected word. Nothing else happens.

In no cases above the iedit mini-buffer is shown.

In emacs-lisp it was working. Can reproduce it every time.
What else do you need to know?

Here is the `.spacemacs` config file http://pastebin.com/SK27ad4k.

**Comment by zilongshanren** [comment]
@syl20bnr  +1 for this issue.

**Comment by justbur** [comment]
I can reproduce the problem in the second case (`SPC se`), but not the first.

**Comment by justbur** [comment]
Try this: `(evil-leader/set-key "se" 'evil-iedit-state/iedit-mode)` and see if it still happens

**Comment by justbur** [comment]
Oh I see that key binding was moved to `SPC sE` in dc224788c7c70988405d23ef0ee6758e447bcde2

**Comment by CestDiego** [comment]
Also can't exit from iedit-state with `nj` now :(

**Comment by syl20bnr** [comment]
I reverted the changes, iedit behaves like previously now. Closing this issue.
