### ISSUE TITLE
"An error occurred while initializing evil-terminal-cursor-changer" after upgrade to 0.103.6

### ISSUE THREAD

**Issue by royseto** [syl20bnr/spacemacs#2890]
I just upgraded to spacemacs 0.103.6 from an older 0.103.x release. This is running on emacs 24.3.1 on Ubuntu 14.04. I run emacs in command-line mode with unicode fonts in my terminal session.

On emacs startup, I now get the error: "An error occurred while initializing evil-terminal-cursor-changer (error: (file-error Cannot open load file evil-terminal-cursor-changer))"

Spacemacs does appear to work, though.

**Comment by royseto** [comment]
My personal dotfiles including my .spacemacs file are here: https://github.com/royseto/dotfiles

**Comment by royseto** [comment]
This issue went away after I removed my .emacs.d directory and reinstalled spacemacs from scratch (instead of doing the upgrade). It must be an upgrade issue.

**Comment by robbyoconnor** [comment]
0.104 will be released any day now. If you wanna try with `develop`, you can and should do it
