### ISSUE TITLE
Visual word selection not working as intended

### ISSUE THREAD

**Issue by madhat2r** [syl20bnr/spacemacs#2892]
When using visual word selection `vw` it selects past the `W` boundary and including the first letter of the next `w`. All other machinations of  `w` appear to be working properly: `dw`, `cw`,`yw`, etc...

@geo7 also confirmed this behavior.

![lastimg](https://cloud.githubusercontent.com/assets/4122449/9694294/e7d71d22-531c-11e5-92be-0846fc99789e.png)

**Comment by sooheon** [comment]
This seemed like a bug to me as well, but with a little testing I can see this behaviour exists in default evil, *and* default vim. So it's not an issue for spacemacs. I'm curious what the rationale behind it is, but it's accurate vim emulation.

**Comment by cpaulik** [comment]
Yes this behavior is correct. For selection of a word try `viw` or the `SPC v` micro state.

**Comment by justbur** [comment]
Technically, I think you want `vaw` which will capture the following space too as `dw` does

**Comment by madhat2r** [comment]
Well I be damned, it is that way in VIM. What the heck is the purpose of that? The `w` action moves by "words" and never skips white-space or punctuation. This just doesn't jive with the the way it works in all other scenarios. 

I do usually use `viw` or `vaw` but for some reason issued `vw` and expected a different behavior. I guess I learned something new, I never noticed using Vim for years.

Thanks for your help guys!
