### ISSUE TITLE
ad-handle-definition error when running emacs daemon

### ISSUE THREAD

**Issue by 526avijitgupta** [syl20bnr/spacemacs#2893]
`emacs --daemon` throws the following error and then fails to load after that:  
`ad-handle-definition: 'tramp-read-passwd' got redefined`

**Comment by robbyoconnor** [comment]
I've seen that message -- doesn't actually seem to be fatal.

**Comment by 526avijitgupta** [comment]
@robbyoconnor But while starting the `emacs daemon` - after this message is displayed, there is no further progress visible even though the process does not terminate.

**Comment by justbur** [comment]
It's a coincidence then because I get that message every time helm loads

**Comment by TheBB** [comment]
Yes, the `ad-handle-definition` warnings are unlikely to cause your problem. See #192. If you run it normally (not as a daemon) you should have several such warnings as well.
