### ISSUE TITLE
Python: Cannot define function in run-python. 

### ISSUE THREAD

**Issue by zhexuany** [syl20bnr/spacemacs#2894]
The following is code:
>>> def print_lyrics():
def print_lyrics():
... print("dededed")
print("dededed")
dededed
>>> print print_lyrics
print print_lyrics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'print_lyrics' is not defined

And  also, I try to send code to python shell, it doesn't work at all. The error info is the following:
import codecs, os;__pyfile = codecs.open('''/var/folders/p5/j14r5gfj0gn2p26_r1kw41280000gn/T/py28919vam''', encoding='''utf-8''');__code = __pyfile.read().encode('''utf-8''');__pyfile.close();os.remove('''/var/folders/p5/j14r5gfj0gn2p26_r1kw41280000gn/T/py28919vam''');exec(compile(__code, '''/Users/yzx/dropbox/cs/CSCI1913/practice_python.py''', 'exec'));

**Comment by cpaulik** [comment]
What exactly are you trying to do? 

I have the buffer 

```python
def main():
    print("Hello from main")

main()
```
Pressing `SPC m s B` sends the code to a Python REPL and prints:

```
Process Python[/home/cp/test.py] finished
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: 
In [2]: 
In [3]: 
In [4]: Hello from main

In [5]: 
```

In this Python REPL I can also do the following:

```

In [6]: def test():
   ...:     print "test"
   ...: 

In [7]: test()
test

In [8]: 
```

Be sure to indent the code in your function correctly. Defining functions might also be a problem in a regular python, try ipython which works better in my experience.

**Comment by zhexuany** [comment]
@cpaulik  thanks a lot. I fixed my issue.  But how can I use ipython?

**Comment by cpaulik** [comment]
Ipython should be detected automatically if it is installed. Yes `SPC` is the prefix key for `evil` editing style. If you use emacs editing style the prefic is `M-m` if I'm not mistaken

**Comment by zhexuany** [comment]
@cpaulik  I already found the key bindings and it should start with M-Ret. Thanks.

**Comment by liujoey** [comment]
@zhexuany would you mind share how did you fix it? I get exactly the same issue. Sending code to REPL get a bunch of 
```
import codecs, os;__pyfile = codecs.open('''/var/folders/p5/j14r5gfj0gn2p26_r1kw41280000gn/T/py28919vam''', 
```

**Comment by zhexuany** [comment]
@liujoey Just try to do things said in `python`'s readme.
