### ISSUE TITLE
Is Auto-save working correctly ?

### ISSUE THREAD

**Issue by PierreR** [syl20bnr/spacemacs#2897]
After 30 sec, I can see the line `Auto-saving...done`. The file is there in the `autosave-dir` but the buffer is not saved. If I kill emacs, it never proposes me to recover the file.

Is this intended ?

I am using 0.103.6 (latest master) on arch linux.

**Comment by cmccloud** [comment]
How did you kill emacs?
I tested this twice just now. In the first case I modified a buffer and auto-saved, then killed via (spacemacs/prompt-kill-emacs) (Spc q q). When asked whether I wanted to save changes, I said no. After a restart, I didn't get a mention of an auto-save filed, and M-x recover this file returned gave me nothing. 
In the second case, I modified a buffer, autosaved, and then used force quit to kill emacs through OSX. When I restarted, I got the prompt and was able to recover normally.

**Comment by PierreR** [comment]
@cmccloud I am just using the `kill` command.

I was actually expecting `auto-save` to write the file on disk. Note that many editors today would recover your state in case of a crash without asking you if you wish to recover.

**Comment by PierreR** [comment]
What I wish for is probably something which is not really `auto-save` in emacs but more:

http://batsov.com/articles/2012/03/08/emacs-tip-number-5-save-buffers-automatically-on-buffer-or-window-switch/

As far as emacs `auto-save` goes, I will have to double-check. Maybe it does work alright.

**Comment by geo7** [comment]
Any progress on this @PierreR ?

**Comment by TheBB** [comment]
Since there's no movement here I'm closing this for now.

**Comment by PierreR** [comment]
Maybe I should open a new issue requesting such enhancement to make it more clear. Something like "Automatic save 'ala' intellij" ?

**Comment by TheBB** [comment]
Yeah, you could do that. The more specific you are, the better.

**Comment by timofeytt** [comment]
@PierreR Is there a new issue?
