### ISSUE TITLE
why spacemacs helm mini does not use regexp to filter the candicate

### ISSUE THREAD

**Issue by LuoPX-15510486969** [syl20bnr/spacemacs#2899]
just like the the document show:
Example:

If I enter in pattern prompt: *lisp ^helm @moc, Helm will narrow down the list by selecting only buffers that are in lisp mode, start by helm and match "moc" in their contents.
If I want to specify more than one major-mode, separate them with ,, e.g *!lisp,!sh,!fun will list all buffers but the ones in lisp-mode, sh-mode and fundamental-mode.
If I enter in pattern prompt: *lisp ^helm moc. Notice there is no @ this time helm will look for lisp mode buffers starting by "helm" and have "moc" in their name.
If I enter in pattern prompt: *!lisp !helm Helm will narrow down to buffers that are not in "lisp" mode and that do not match "helm".
If I enter in pattern prompt: /helm/ w3 Helm will narrow down buffers that are in any "helm" sub-directory and matching w3.
helm-mini is like an interactive version of ibuffer.

Demo:
![helm-mini](https://cloud.githubusercontent.com/assets/13256245/9699273/463190d0-540f-11e5-804c-c2538ba0e0eb.gif)

**Comment by TheBB** [comment]
Most of this seems to work for me now.

**Comment by LuoPX-15510486969** [comment]
are you sure you could reproduce it? how did you do that?

**Comment by TheBB** [comment]
Sorry, what I meant was that I could reproduce the *problem* (that it *doesn't* work), but now I can't, which is to say that it *does* work.

**Comment by StreakyCobra** [comment]
@LuoPX-15510486969 Do you still have this problem with the latest spacemacs release and the packages up-to-date?

**Comment by StreakyCobra** [comment]
This old issue has been waiting for a response for more than one month. As no answer has been provided, we can not help further or know if the issue is still relevant. We are then closing it. Feel free to open a new issue if there is any news on this side, be sure to [read this guide](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) first and link this issue in the new one.
