### ISSUE TITLE
Spacemacs -nw + Tilda + Zsh

### ISSUE THREAD

**Issue by mekarpeles** [syl20bnr/spacemacs#2905]
On Debian 9 alpha 2 (4.1.0-1-amd64 #1 SMP Debian 4.1.3-1 (2015-08-03) x86_64 GNU/Linux)

Scenario:
When running spacemacs with no windows (e.g. `emacs -nw`) when using the tilda terminal with (oh my) zsh.

Symptom(s):
The zsh session becomes corrupted and prints a strange string after each command: "[a q". Strange characters occasionally also appear within the spacemacs itself and interrupt the session.

Work-around:
If I modify my init.el as follows by excluding spacemacs/setup-after-init-hook (core-spacemacs.el) when run as -nw, the problem does not occur

    (when (spacemacs/emacs-version-ok)
      (load-file (concat user-emacs-directory "core/core-load-paths.el"))
      (require 'core-spacemacs)
      (require 'core-configuration-layer)
      (spacemacs/init)
      (when window-system
        (spacemacs/setup-after-init-hook))  ;; fix: omitting this line when run as -nw
      (spacemacs/maybe-install-dotfile)
      (require 'server)
      (unless (server-running-p) (server-start)))
    )

**Comment by beneyal** [comment]
I am experiencing the same symptoms.
Using Gnome Terminal with oh-my-zsh, the workaround suggested by @mekarpeles doesn't work for me.

This is how it looks after executing `emacs -nw`, pressing down until the 2nd recent file, and pressing right a few times. Note that this only happens visually, so if I edit a file, I see gibberish, but the content is what I typed.
![screenshot-emacs -nw](https://cloud.githubusercontent.com/assets/3891274/9705565/077f4ec8-54d1-11e5-8602-42a9e98cbe7f.png)

**Comment by mekarpeles** [comment]
Sorry @beneyal , I made a mistake, it appears to be happening during
(configuration-layer/load-layers) in core-configuration-layer.el which is called from init.el

If you change the line (configuration-layer/sync) in init.el to (configuration-layer/sync window-system) and then update core-configuration-layer.el configuration-layer/sync as follows, it should stop the problem (but also the spacemacs confics won't load):

(defun configuration-layer/sync (ws)
  "Synchronize declared layers in dotfile with spacemacs."
  (dotspacemacs|call-func dotspacemacs/layers "Calling dotfile layers...")
  (configuration-layer/init-layers)
  (when (ws)
    (configuration-layer/load-layers))
  (when dotspacemacs-delete-orphan-packages
    (configuration-layer/delete-orphan-packages)))

**Comment by grokful** [comment]
I experienced similar symptoms, particularly severe from within tmux. I seem to have made the problem go away by disabling evil-terminal-cursor-changer.

**Comment by mekarpeles** [comment]
@grokful -- you're right, updating spacemacs/packages.el to only setq
'evil-terminal-cursor-changer when window-system t fixed the issue for me.

I'm also running emacs -nw within tmux.

next-window(defun spacemacs/init-evil-terminal-cursor-changer ()
  (unless (display-graphic-p)
    (when (not window-system)
      (require 'evil-terminal-cursor-changer)
      (setq evil-visual-state-cursor 'box) ; █
      (setq evil-inser<0;24;43m[t-state-cursor 'bar) ; ⎸
      (setq evil-emacs-state-cursor 'hbar) ; _
    )))

best wishes,

- mek

**Comment by JohnLunzer** [comment]
I have a similar problem, i'm using Gnome-Terminal and Tmux and Bash and when I make your change in the last post to my packages.el file it removes my ability to use the completion functionality and a host of other issues. Any idea what I'm doing wrong and do I need to make another change in addition to this one?

Also if I try to run emacs in a window now I cannot use the spacebar, it says end-of-buffer... any advice? I clearly have no clue what i'm doing.

**Comment by JohnLunzer** [comment]
Just an update, installing the develop branch fixed this and also when I checked packages.el and the "next-window" bit isn't there.
