### ISSUE TITLE
Cursor tutorial not working

### ISSUE THREAD

**Issue by montogeek** [syl20bnr/spacemacs#2908]
Hi! I want to learn Spacemacs. I discovered by myself the initial tutorial by typing `:help` then `t`. Unfortunately the basic cursor tutorial does not work. I hit `C-p` or `C-b` and the cursos just dont move. I am doing it with my arrow keys but that is not the idea.

I am using iTerm2 build 2.1.1 on OSX Yosemite, executing Spacemacs by running emacs on the terminal.

**Comment by mbertheau** [comment]
Use `SPC f e h` and open the Spacemacs Starter Guide.

If you're not very familiar with vim keybindings, use `SPC h T` instead - this opens the Emacs Evil Tutor. `:help t` opens the Emacs tutorial; however the spacemacs keybindings are quite different from the default emacs keybindings.

**Comment by mbertheau** [comment]
I added an entry to this FAQ: https://github.com/mbertheau/spacemacs-faq/wiki

**Comment by montogeek** [comment]
Great, thanks!
