### ISSUE TITLE
spacemacs/init-evil rebinds K after loading buffer

### ISSUE THREAD

**Issue by jschaf** [syl20bnr/spacemacs#2909]
I rebound `K` in a private layer to move up 5 lines.  After I load any buffer, spacemacs rebinds `K` to `spacemacs/evil-smart-doc-lookup`.

Is there a way to prevent that from happening?

**Comment by person808** [comment]
Try wrapping your code with `(with-eval-after-load 'evil some-code)`

**Comment by jschaf** [comment]
I have a function `my:evil-keybindings` that sets up my evil config.  I created a private layer to do most of my customization.  I tested running `my:evil-keybindings` a in a couple ways.  Here was the order that I got:

1. Private Layer - bare call - `(my:evil-keybindings)`
2. Private Layer use-package :config - `(use-package evil :config (progn (my:evil-keybindings)))`
3. Private Layer  with-eval-after-load - `(with-eval-after-load 'evil (my:evil-keybindings))`
4. Spacemacs use-package 'evil :init in ~/.emacs.d/spacemacs/packages.el
5. dotspacemacs/user-config in .spacemacs

I don't understand why 2 & 3 run before 3.  That doesn't make sense to me.

**Comment by person808** [comment]
In your private layer add this to your packages.el (assuming `evil` is already in the `<layer>-packages` variable):

```elisp
(defun <layer>/pre-init-evil ()
  (spacemacs|use-package-add-hook evil
    :post-config
    (progn
      (my:evil-keybindings))))
```

**Comment by syl20bnr** [comment]
> I don't understand why 2 & 3 run before 4. That doesn't make sense to me

You are right, this is a big bug, going to fix it ASAP, thank you !

**Comment by jschaf** [comment]
@person808 the pre-init-evil worked, thank you.

**Comment by syl20bnr** [comment]
Indeed but it should not be necessary, OTOH what @person808 told you is the correct way to override lazy loaded settings, so always good to know :-)

**Comment by syl20bnr** [comment]
@jschaf Actually there is no bug at all :-) Did you put your evil stuff in a pre-init function ?
Can you paste here your configuration layer as well as your `dotspacemacs-configuration-layers` variable ?

**Comment by jschaf** [comment]
The evil stuff was not originally in a pre-init function.  I tried use-package :config and with-eval-after-load.

I'll link to my code:

https://github.com/jschaf/dotfiles/blob/master/spacemacs-layers/joe/packages.el
https://github.com/jschaf/dotfiles/blob/master/home/.spacemacs

`joe` is my private layer.

**Comment by syl20bnr** [comment]
Ok I see, now all `keybindings.el` files are called before loading the `packages.el` files of the layers, this is why your bindings were overwritten. `keybindings.el` should not define bindings for packages, this file is here to provide a place where to put key bindings for stock emacs functions.

The order of loading is (from a file point of view):
- for all layers: load funcs.el
- for all layers: load config.el
- for all layers: load keybindings.el
- for all layers: load packages.el

I think that we should remove `funcs.el` and `keybindings.el` to keep only `config.el` which is called before loading any `packages.el`.

**Comment by jschaf** [comment]
> I think that we should remove funcs.el and keybindings.el to keep only config.el which is called before loading any packages.el.

I agree.  It's confusing to figure out what goes where.  I would add a paragraph to the documentation on the precise order that the files are loaded and guidelines for how to separate functionality between the files.

**Comment by TheBB** [comment]
I think this can be closed.
