### ISSUE TITLE
How do I turn off vi-tilde-fringe-mode ?

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#291]
I've tried acking the code for relevant switches but I can't find any.

`(vi-tilde-fringe-mode -1)` in my config almost works, but when I open another buffer they are back.

I have also tried setting the tilde bitmap to all 0 in `vi-tilde-fringe.el`, but that did not work either.

Is it possible to turn off the tildes in the gutter?

**Comment by jschaf** [comment]
That didn't work for me.  This did:

    dotspacemacs-excluded-packages '(vi-tilde-fringe)
