### ISSUE TITLE
Setting dotspacemacs-startup-banner to nil has no effect

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#2911]
Due to commit 8440a38. Not sure why it breaks this, but reverting this commit fixes the issue.

**Comment by TheBB** [comment]
Ping @d12frosted

**Comment by justbur** [comment]
Same problem here

**Comment by d12frosted** [comment]
Sorry for that.

**Comment by syl20bnr** [comment]
Fix is merged, thank you for the report and the quick fix :+1:
