### ISSUE TITLE
develop - python auto-complete is broken

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2915]
Ran an update today.  On commit c43a8e958eb539370324d04e25cd90bb315a0dc3, anaconda-mode no longer works.

There is no *anaconda-mode* window, these messages are displayed in the *Messages* buffer:

```
Company: An error occurred in auto-begin
127.0.0.1%3anil/80 nodename nor servname provided, or not known
eldoc error: (error 127.0.0.1%3anil/80 nodename nor servname provided, or not known) [3 times]
```

**Comment by cpaulik** [comment]
seems related to https://github.com/syl20bnr/spacemacs/issues/2917 and the new anaconda-mode version.

**Comment by synic** [comment]
Yes, it's the same error.
