### ISSUE TITLE
Spacemacs buffer no longer shows at startup

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2923]
Why does the spacemacs buffer no longer show at startup...but the scratch buffer does?

**Comment by robbyoconnor** [comment]
This is related to #2845 -- so I'm not sure if we should keep it open since -- only those who decided to cherrypick #2845 into their local branch will encounter this...

**Comment by TheBB** [comment]
Then that should be dealt with in #2845 I think.
