### ISSUE TITLE
possible el capitan related bug using helm

### ISSUE THREAD

**Issue by mclearc** [syl20bnr/spacemacs#2924]
I'm running the most recent version of the el cap public beta. Spacemacs has been working like a champ except for one odd bug. In order to get a command like `SPC h d` to work (specifically, the `d`) I have to change focus from the app to something else (e.g. Finder) and then back. Otherwise I'll get `d is undefined` or it will sometimes perform some other random (at least to me) command. Any idea what might be causing this?

**Comment by d12frosted** [comment]
Wow, really strange bug. Also on El Capitan (not public beta thought). Have few questions to you

1. Does it still occur? 
2. How have you installed emacs?

**Comment by mclearc** [comment]
It is super weird. And it still happens. I've gone so far as to not only do a clean spacemacs install but I even nuked my computer (I was due for a clean reinstall). Still happens. No idea what's up. I think this is a duplicate of another ticket i opened (#3355), so maybe close this and stick with that one?
