### ISSUE TITLE
ox-pandoc causes a warning during startup

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2927]
#2310 causes issues on my system and now get a warning on startup

```
Warning (ox-pandoc): This Pandoc may not support org-mode reader.
```

**Comment by robbyoconnor** [comment]
@TheBB , @syl20bnr

**Comment by robbyoconnor** [comment]
Seems I had an old version of pandoc installed...

**Comment by vv111y** [comment]
If anyone else finds this, Anaconda can conflict with brew on Mac. kSee https://hashrocket.com/blog/posts/keep-anaconda-from-constricting-your-homebrew-installs
Post recommends a script as a hack
```
export SANS_ANACONDA="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# added by Anaconda3 4.4.0 installer
export PATH="/Applications/anaconda/bin:$SANS_ANACONDA"

alias perseus="export PATH="\$SANS_ANACONDA" && echo Medusa decapitated."
alias medusa="export PATH="/Applications/anaconda/bin:\$SANS_ANACONDA" && echo Perseus defeated."

brew () {
  perseus
  command brew "$@"
  medusa
}
```

**Comment by QikeLi** [comment]
The following command solved my problem:
conda install -c conda-forge pandoc
