### ISSUE TITLE
neotree bug when opening a file or switching window

### ISSUE THREAD

**Issue by qleonetti** [syl20bnr/spacemacs#2932]
When I navigate in neotree and open a file, the cursor looks like it's switching window non stop and i cannot do anything.
Same issue if I try to C-x o from neotree.
It was working fine before and I haven't done anything special between restart expect adding javascript layer.

Someone knows what can cause that /how to fix?

Thanks

**Comment by syl20bnr** [comment]
Do you have the last version of neotree?

**Comment by qleonetti** [comment]
yes, latest is installed here

**Comment by qleonetti** [comment]
Fixed by moving to the develop branch of spacemacs
