### ISSUE TITLE
Dot command isn't working as expected

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#2938]
To reproduce: 

* Open scratch buffer
* Change mode to `shell-script-mode`
* copy following text (or whatever) 

```
echo "something"
echo "another.."
```
 
Move point to start of first echo, then `A` to append text and type the following before `esc`

```
echo "something" # this is some text
echo "another.."
```

Then move the cursor down to the second echo - then (from normal mode) press `.` (dot) to repeat last action. Rather than the test `# this is some text` being appended to the end of the line the point just moves. 

I initially thought that this was related to the `hybrid` mode, but after changing back to 

```elisp
   dotspacemacs-editing-style 'vim
```

The problem still exists. 

[video of error in spacemacs](https://vid.me/Kryb)

[video of expected behaviour in vim](https://vid.me/6vEm)

This action has previously worked in spacemacs. 

```text
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.0
- Spacemacs branch: develop (rev. 3760916)
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'complete)
 ansible better-defaults c-c++ colors emacs-lisp emoji erc evil-snipe eyebrowse git github html ipython-notebook javascript latex markdown org php python shell syntax-checking themes-megapack version-control home-row-keys latex-key-maps org-key-maps python-key-maps
 (ranger :variables ranger-show-preview t ranger-cleanup-on-disable t ranger-show-dotfiles t ranger-ignored-extensions
         '("mkv" "iso" "mp4")
         ranger-max-preview-size 10))
```

```

**Comment by justbur** [comment]
@geo7 I can't reproduce this problem and I'm using hybrid mode

**Comment by justbur** [comment]
Did you use `C-[` by chance?

**Comment by geo7** [comment]
@justbur ah right, ole evil-escape rears it's head again :P 

I can confirm that it works if using `C-[` but I never use that... I've just about conditioned myself to use it for macros

**Comment by garry-cairns** [comment]
I'm experiencing this too. Is there a workaround?

**Comment by nwolfe** [comment]
This is destroying my productivity!!!! 

@syl20bnr halp us please

**Comment by TheBB** [comment]
Yeah, I noticed this too, today.

Labeling as high priority ~~now that it's affecting me~~. ;-)

**Comment by syl20bnr** [comment]
I have an opened issue upstream: https://github.com/syl20bnr/evil-escape/issues/40
