### ISSUE TITLE
Develop - Spacemacs homescreen - project list is broken.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2939]
I have the following set:

```elisp
   dotspacemacs-startup-lists '(recents projects bookmarks)
```

The `projects` section only shows on the homepage if `~/.emacs.d/.cache/bookmarks` exists.  It doesn't matter if you have the following:

```elisp
   dotspacemacs-startup-lists '(recents projects)
```

OR:

```elisp
   dotspacemacs-startup-lists '(projects)
```

Even if `projects` is the the only one listed, it doesn't show unless you have a bookmarks file.

**Comment by duien** [comment]
I'm also having trouble getting recents and projects to show up in my homescreen on the latest develop (b8f3d39). Creating the bookmarks file didn't fix it, and so I assumed it was something messed up in my `.spacemacs` file, since I'd just made some big updates. 

I started selectively stashing bits of it to try to narrow it down, and my findings leave me more confused that before. I discovered that if I remove the following from the end of the `dotspacemacs/init` function, I stop getting projects and files. If it's there, they show up:

```
(add-hook 'text-mode-hook
          (lambda () (visual-line-mode t)))
```

I can't see how the actual contents of that hook could possibly be related, but the behavior is consistent. I can move the hook into the new `dotspacemacs/user-init` function instead, which also allows my recent project list to work correctly. My [full `.spacemacs` file is on GitHub](https://github.com/duien/dotfiles/blob/master/home/.spacemacs) in case it's useful.

**Comment by synic** [comment]
Bump?

**Comment by synic** [comment]
I'm pretty new to elisp, so I'm not super sure how to help, but I have found this by putting `(message)` commands in `core-spacemacs-buffer.el`:

```elisp

(defun spacemacs-buffer/insert-startupify-lists ()
  (interactive)
  (with-current-buffer (get-buffer-create "*spacemacs*")
    (let ((buffer-read-only nil)
          (list-separator "\n\n"))
      (goto-char (point-max))
      (page-break-lines-mode)
      (spacemacs-buffer/insert-page-break)
      (mapc (lambda (el)
              (progn
                (message "Trying to load %s" el)
                (cond
                    ((eq el 'recents)
                        (recentf-mode)
                        (when (spacemacs-buffer//insert-file-list "Recent Files:" (recentf-elements 5))
                        (spacemacs//insert--shortcut "r" "Recent Files:")
                        (insert list-separator)))
                    ((eq el 'bookmarks)
                        (helm-mode)
                        (when (spacemacs-buffer//insert-bookmark-list "Bookmarks:" (bookmark-all-names))
                        (spacemacs//insert--shortcut "m" "Bookmarks:")
                        (insert list-separator)))
                    ((eq el 'projects)
                        (projectile-mode)
                        (message "Projects: %s" projectile-relevant-known-projects)
                        (when (spacemacs-buffer//insert-file-list "Projects:" (projectile-relevant-known-projects))

                        (message "Projects: %s" projectile-relevant-known-projects)
                        (spacemacs//insert--shortcut "p" "Projects:")
                        (insert list-separator)))))) dotspacemacs-startup-lists))))
```

I get the following messages:

```
Spacemacs is ready.
Trying to load recents
Loading /Users/synic/.emacs.d/.cache/recentf...done
Trying to load projects
cond: Symbol's value as variable is void: projectile-relevant-known-projects
Symbol's value as variable is void: projectile-relevant-known-projects
```

Using `M-x`, I can see that there is no `projectile-relevant-known-projects`, even though it is defined in the projectile package in the elpa directory.

I tried typing `SPC p p`, and I got the message "Symbolic link to Git-controlled source file; follow link?" - it seems `SPC p p` is causing emacs to try and load `~/.spacemacs`, which is indeed under source control.  

The project list loads fine, but `projectile-relevant-known-projects` is still undefined.

**Comment by justbur** [comment]
I'm not having difficulty with this and I don't have a bookmarks file in my cache. 

@synic You're tests are not quite right. `projectile-relevant-known-projects` is a function, so you can't use `message` like you do, but it's not interactive, so it won't show up under `M-x`. 

This is a way to test for that function being available. 
```elisp
(message "projectile-relevant-known-projects is defined? %s" (fboundp 'projectile-relevant-known-projects))
```

Although that shouldn't be a problem.

**Comment by synic** [comment]
Maybe it has something to do with `~/.spacemacs` being a symlink

**Comment by d12frosted** [comment]
Mine `spacemacs` is also a symlink, but it works fine here.

**Comment by justbur** [comment]
@synic see what that function returns `M-: (projectile-relevant-known-projects)`

**Comment by synic** [comment]
It says `no match`.  

Things like `SPC p p` still work just fine, though.

**Comment by justbur** [comment]
No match? What does `SPC hdv projectile-known-projects RET` say?

**Comment by synic** [comment]
Just kidding, I read it wrong.  It says 

`("~/.dotfiles ~/.emacs.d"/)`

Which is minus one project that `SPC p p` shows

**Comment by justbur** [comment]
that makes sense. Here's the docstring for that function  "Return a list of known projects except the current one (if present)."

**Comment by justbur** [comment]
Did you try this? https://github.com/syl20bnr/spacemacs/issues/2939#issuecomment-142003327

**Comment by synic** [comment]
```
ad-handle-definition: `find-tag-noselect' got redefined
Starting new Ispell process /usr/local/bin/aspell with default dictionary...
Spacemacs is ready.
projectile-relevant-known-projects is defined? nil
Loading /Users/synic/.emacs.d/.cache/recentf...done
projectile-relevant-known-projects is defined? nil
projectile-relevant-known-projects is defined? t
ad-handle-definition: `tramp-read-passwd' got redefined
Skipping check for new version because you are on develop.
Open the quickhelp.
```

Only, now, projects are appearing.

**Comment by justbur** [comment]
That looks right. The line `(projectile-mode)` should load the projectile package and define that function.

I don't see where the problem could be now, and since they're showing up it's going to be hard to debug this.

**Comment by synic** [comment]
I don't know what's going on now, it's working for me, and I don't feel like anyone has fixed anything regarding this yet, which is a bit worrying ;-)
