### ISSUE TITLE
`SPC : is undefined` in emacsclient GUI and terminal

### ISSUE THREAD

**Issue by kdheepak89** [syl20bnr/spacemacs#2941]
I get the following error when I create a daemon  and run a GUI or terminal client.

`SPC : is undefined`

I do not see this issue with I open the Emacs app directly. I'm on the develop branch

**Comment by TheBB** [comment]
Thanks! It's already reported: #2715.

**Comment by kdheepak89** [comment]
Thanks! I looked for a similar issue before posting, but it didn't show up.

**Comment by tidux** [comment]
This issue is still present on Emacs 25.1 x86_64 w64 mingw32 on Windows 10.

**Comment by praduca** [comment]
Also present on Ubuntu 16.04 LTS with emacs 25.1
