### ISSUE TITLE
Develop - Latest NeoTree is painfully slow.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2943]
Expanding and collapsing nodes, searching is now a LOT slower than it used to be.

**Comment by synic** [comment]
https://github.com/jaypei/emacs-neotree/issues/126

**Comment by synic** [comment]
This appears to be spacemacs specific.  It only happens in directories with a lot of git history.  

On vanilla emacs with neotree and projectile installed, it is still fast.

**Comment by synic** [comment]
This is because spacemacs sets `neo-vc-integration` to '`face'.  From the `neotree` github issues - author `jaypei`:

```
Yes, this feature is indeed slow, so it is closed by default.
It can speed up when NeoTree support the sub-tree refresh feature.
```

Setting `neo-vc-integration` to `nil` solves the issue for me.  Since the author admits the feature is slow, maybe it's more appropriate to make the default `nil` in spacemacs until this `sub-tree refresh feature` is available?

**Comment by quangquach** [comment]
@synic Thanks, you saved my day. To be more specific, in `.spacemacs`, I need to add
```emacs-lisp
(defun dotspacemacs/config ()
…
(setq neo-vc-integration nil)
)
```

**Comment by josepjaume** [comment]
I'm trying to disable this by putting `(setq neo-vc-integration nil)` in spacemacs' config but I still see the highlighting and it's still slow. Is anyone having the same issue?

**Comment by synic** [comment]
Where are you setting it?

**Comment by josepjaume** [comment]
That's odd. It ended up working, but only if I put it first in my config variables, like this:

```elisp
(defun dotspacemacs/config ()
  "Configuration function.
 This function is called at the very end of Spacemacs initialization after
layers configuration."
  (setq neo-vc-integration nil)

  (setq indent-tabs-mode nil)
  (setq-default tab-width 2)
  (setq evil-shift-width 2)
  (setq js-indent-level 2)
  (setq ruby-indent-level 2)
  (setq html-indent-level 2)

  (setq web-mode-code-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-enable-auto-indentation t)
  (setq web-mode-indent-style 2)
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-sql-indent-offset 2))
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-markup-indent-offset 2)

  (setq js-indent-level 2)
  (setq css-indent-level 2)
  (setq css-indent-offset 2)
  (setq js2-basic-offset 2)
  (setq js2-indent-switch-body t)
  (setq evil-shift-width 2)
```

If I put it on the end, right after `evil-shift-width`, it doesn't work. How strange.

**Comment by AlbertGazizov** [comment]
I have the same issue with neotree, setting the neo-vc-integration to nil doesn't help.

**Comment by AlbertGazizov** [comment]
placing neo-vc-integration to the user-config helped for me:
```
(defun dotspacemacs/user-config ()
  (setq neo-vc-integration nil)
   ...
)
```

**Comment by synic** [comment]
So, if I wanted to make a PR, would it just be a documentation update, or change the default, or both?

**Comment by joehillen** [comment]
:+1: for changing the default
