### ISSUE TITLE
[develop] Cannot stage files in Magit

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#2945]
As of b8f3d395fd2ac6b969d4b19cc47d37663056803a : 

In magit `SPC g s`, if I hit `s` I get a `magit-mode-get-buffer: Wrong type argument: stringp, nil` error.

This works as of 82c9055.

**Comment by igorepst** [comment]
Same thing (magit-20150908.806)

**Comment by ntcong** [comment]
I can't reproduce with lastest develop and magit. Can you do a git bisect to find the problematic commit? https://github.com/syl20bnr/spacemacs/commit/b8f3d395fd2ac6b969d4b19cc47d37663056803a doesn't seem to do anything.

**Comment by cpaulik** [comment]
I had the same problem, updating magit to `20150908.1621` fixed this for me.

**Comment by swaroopch** [comment]
Yep, updating Magit fixed this.
