### ISSUE TITLE
Experiencing full lockups, loss of focus

### ISSUE THREAD

**Issue by cdlm** [syl20bnr/spacemacs#2946]
Spacemacs often locks up to the point where `C-g` does nothing, the main frame does not redraw, and the process uses a full CPU. (Spacemacs master + daily updated packages, on emacs-24.5-z-mac-5.10 installed via Homebrew)

I've seen it happen when calling org-capture from the home buffer on a freshly launched Spacemacs, when trying to recover a file (`M-x recover-this-file` or `M-x recover-file`), or with minibuffer completions (via Helm, I suppose).

Another symptom is that Helm somehow loses focus (because I clicked somewhere else, or closed the window where it was showing completions, or just because) and there is no way to regain focus or invoke commands. Helm still seems active, but at the same time is not accessible anymore.

I'm not sure Helm is the real culprit here, and not even that all symptoms are of a single problem. I will try to note what I did next time it manifests, but it's partly random…

**Comment by Devagamster** [comment]
Dunno about the freezing thing, but the helm issue can be fixed by pressing `SPC` `w` `b` to get back to the minibuffer and get helm working again. For the related issue: https://github.com/syl20bnr/spacemacs/issues/2851

**Comment by cdlm** [comment]
Is `semantic-mode` on when updating packages or loading them at boot time?
Last lockup, I tried to keep `C-g` pressed for a long time (10-20 sec); after a while the frame redraws, and there was an error message in the minibuffer about semantic not having support to parse `org-loaddefs.el`. I tried quitting Emacs, but semantic would trigger again for 10-20 seconds, making it unresponsive. Disabling `semantic-mode` stopped the unresponsiveness.

I've disabled semantic in my `.spacemacs` file. We'll see if this fixes the problem…

**Comment by sooheon** [comment]
Hm, I think I may have come across a similar issue, where typing some prefix (like `ev`-il) echoes in the mini buffer a whole bunch of source files being parsed, which I'd have to `c-g` out of. But I don't have semantic installed, just company-mode.

**Comment by valrus** [comment]
Just had this happen while trying to do a routine buffer switch with `SPC b b`. Screenshot shows the state of Helm at the time Emacs became unresponsive; I assume the blank modeline is unrelated but I included it for posterity. No amount of `C-g` has any effect, and resizing the frame causes it to become permanently blank. This is on Windows 7.
![screenshot 70](https://cloud.githubusercontent.com/assets/343665/12122233/97fd3908-b38e-11e5-9457-35299dc86434.jpg)

I have also had Emacs go completely unresponsive a couple times in the last couple days immediately after starting Emacs upon trying to switch to a layout using the `spacemacs-layouts` command `SPC l`, which I don't believe involves Helm.

**Comment by braham-snyder** [comment]
regarding semantic freezing and constant source file parsing messages, what I posted here might fix it: https://github.com/syl20bnr/spacemacs/pull/7736
