### ISSUE TITLE
Develop - Having NeoTree open makes `SPC w =` (equalize windows) a noop

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2947]
`SPC w =` normally equalizes your window sizes.  However, if you have NeoTree open, `SPC w =` does nothing.

**Comment by syl20bnr** [comment]
Neotree locks its windows size on purpose, you can use `tab` to expand it temporarily.

**Comment by synic** [comment]
I don't care if NeoTree resizes, but it should probably still resize the other windows.

**Comment by TheBB** [comment]
This should be a feature request for neotree: https://github.com/jaypei/emacs-neotree.

**Comment by synic** [comment]
I think you guys are misunderstanding the issue.  This is not a neotree thing, I don't think the neotree author has any control over what `SPC w =` does. 

`SPC w =` doesn't resize any windows when neotree is open.  I don't want it to equalize the neotree window - but it should equalize the other windows.

**Comment by TheBB** [comment]
I was able to reproduce the problem in stock Emacs, so if it's not Neotree's issue, I don't know what. Reported upstream: https://github.com/jaypei/emacs-neotree/issues/132

**Comment by TheBB** [comment]
I haven't gotten any response from the neotree maintainer for a month now. For those interested I recommend you nag @jaypei on https://github.com/jaypei/emacs-neotree/issues/132.

**Comment by jaypei** [comment]
Hi TheBB,

The implementation of balance-windows is horizontal balance and vertical balance,
the trigger condition of these is the "window--resize-apply-p" function return t.
By default, NeoTree window width is locked by using window-size-fixed, so the horizontal balance is ignored.

I will solve this issue ASAP.

jaypei

**Comment by TheBB** [comment]
Cool, thanks! :+1:
