### ISSUE TITLE
yanking and multiple pasting does not work as expected

### ISSUE THREAD

**Issue by svalaskevicius** [syl20bnr/spacemacs#2948]
in vim, when a line is yanked `yy`, then any amounts of subsequent pastes with `p` will paste the same line

in spacemacs however, starting from the second `p` strange things start to happen...

**Comment by Devagamster** [comment]
This is from the paste micro state. The idea is that it will cycle through previous yanks in your kill ring with subsequent presses of p. You can disable the functionality in your .spacemacs file by changing the line: dotspacemacs-enable-paste-micro-state to nil. 

Alternatively you can paste once with p and then press . for any subsequent pastes on the same line. If you move lines or hit escape while in the micro state it will disable and return to normal.

**Comment by svalaskevicius** [comment]
thanks!

**Comment by mbertheau** [comment]
I added this to an FAQ: https://github.com/mbertheau/spacemacs-faq/wiki#pasting-using-p-two-and-more-times-does-strange-things

**Comment by veverjak** [comment]
I have my `.spacemacs` set to `dotspacemacs-enable-paste-micro-state nil` but I still get this cycling pasting thing.
Its nice to have some yank history, but I find it disturbing when I want to copy one thing and paste it on multiple places (replacing file). 

I would love to set default behavior to paste without remembering text that was replaced or to move this text to 2nd place and not replacing originaly yanked text. 
Is there any way to do that?

**Comment by StreakyCobra** [comment]
@veverjak It would be better if you can open a new issue as this one is pretty old. Please follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) for doing so :-) Thanks
