### ISSUE TITLE
.emacs.d/init.el -- Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by srid** [syl20bnr/spacemacs#2951]
Something is broken in spacemacs develop. This is all I see when launching emacs:

```
Warning (initialization): An error occurred while loading `/Users/sratnakumar/.emacs.d/init.el':

Wrong type argument: stringp, nil
```

When I launch emacs with `--debug-init` this is all I see in `*Messages*` buffer:

```
Loading /Users/sratnakumar/.emacs.d/.cache/spacemacs-buffer.el (source)...done
Mark set
Saving file /Users/sratnakumar/.emacs.d/.cache/spacemacs-buffer.el...
Wrote /Users/sratnakumar/.emacs.d/.cache/spacemacs-buffer.el
Entering debugger...
Open the quickhelp.
button-at: Args out of range: 0
```

How can I help debug this? 

I'm running OSX 10.10.

**Comment by srid** [comment]
I did bisect to narrow down the offending form in my `.spacemacs`. The error seems to appear here:

```
add-to-list: Wrong type argument: listp, "/Users/sratnakumar/.emacs.d/layers/auto-completion/snippets"
byte-code: Wrong type argument: arrayp, nil
```

**auto-completion** layer is at fault?

**Comment by srid** [comment]
Oh well ... problem goes away once I restart emacs. 

To anyone experiencing this: simply comment out all of your layers, launch emacs, and then uncomment them again followed by a relaunch of emacs.

**Comment by bmag** [comment]
Happened to me too just now. In my case, I had `slime` in my `dotspacemacs-configuration-layers`. Removing it and restarting emacs solved the issue.

Maybe it has to do something with `slime` layer not existing any more? I was able to reproduce the bug by adding a non-existent layer `foo` to my `dotspacemacs-configuration-layers`.

I debugged by adding `(message "maybe make layer: %S" layer-name)` to the `dolist` in `configuration-layer//declare-layers`.

**Comment by kendall** [comment]
I had this problem too. I tried to fixeit by following @srid's advice. Didn't work.

@toshism on Gitter is having the same problem.

**Comment by bmag** [comment]
@kendall check the value of `dotspacemacs-configuration-layers` (in your `.spacemacs` file or `.spacemacs.d/init.el` file). Are you sure all of the layers included there exist? You may have misspelled a layer, or it may not exist any more.

**Comment by syl20bnr** [comment]
@kendall can you run `dotspacemacs/test-dotfile` interactive command and check for any error ?

**Comment by kendall** [comment]
It's hard to know which layers may no longer exist...Is there a list?

**Comment by syl20bnr** [comment]
@kendall I hope you can run `M-x dotspacemacs/test-dotfile`, it will detect any unknown layer in your dotfile.

**Comment by kendall** [comment]
@syl20bnr I don't seem to have that interactive command...

**Comment by kendall** [comment]
My layers:

   dotspacemacs-configuration-layers `(spacemacs
                                       my-web-dev
                                       (colors :variables
                                               colors-enable-rainbow-identifiers t
                                               colors-enable-nyan-cat-progress-bar t)
                                       osx
                                       git
                                       github
                                       latex
                                       version-control
                                       markdown
                                       themes-megapack
                                       html
                                       asciidoc
                                       shell
                                       extra-langs
                                       syntax-checking
                                       define-word
                                       emacs-lisp
                                       ibuffer
                                       vim-empty-lines
                                       auto-completion
                                       syntax-checking
                                        (org :variables
                                            org-bullets-bullet-list '("■" "◆" "▲" "▶")
                                            org-enable-github-support t)
                                       shell-scripts
                                       javascript
                                       perspectives
                                       snippets
                                       ruby
                                       python
                                       smex
                                       rust
                                       finance
                                       haskell
                                       erlang
                                       elixir
                                       java
                                       dash
                                       ranger
                                       clojure
                                       scala
                                       eyebrowse
                                       evil-snipe)

**Comment by syl20bnr** [comment]
@kendall it is only available on develop, let me run it for you with your layers.

**Comment by syl20bnr** [comment]
@kendall here is the result:

```org
** TEST: Each layer in [[file:c:/Users/sbenner/.spacemacs::dotspacemacs-configuration-layers][dotspacemacs-configuration-layers]] can be found
*** PASS: spacemacs
*** FAIL: my-web-dev
*** PASS: colors
*** PASS: osx
*** PASS: git
*** PASS: github
*** PASS: latex
*** PASS: version-control
*** PASS: markdown
*** PASS: themes-megapack
*** PASS: html
*** PASS: asciidoc
*** PASS: shell
*** PASS: extra-langs
*** PASS: syntax-checking
*** FAIL: define-word
*** PASS: emacs-lisp
*** PASS: ibuffer
*** PASS: vim-empty-lines
*** PASS: auto-completion
*** PASS: syntax-checking
*** PASS: org
*** PASS: shell-scripts
*** PASS: javascript
*** PASS: perspectives
*** FAIL: snippets
*** PASS: ruby
*** PASS: python
*** PASS: smex
*** PASS: rust
*** PASS: finance
*** PASS: haskell
*** PASS: erlang
*** PASS: elixir
*** PASS: java
*** PASS: dash
*** PASS: ranger
*** PASS: clojure
*** PASS: scala
*** PASS: eyebrowse
*** PASS: evil-snipe
```

**Comment by syl20bnr** [comment]
`my-web-dev`
`define-word`
`snippets`

are unkown on my machine (develop branch)

**Comment by kendall** [comment]
Thanks guys!
my-web-dev is my private layer, so that exists on my machine.
I will remove the other two.
Cheers, Kendall

On Wed, Sep 9, 2015 at 9:30 AM, Sylvain Benner < notifications@github.com > wrote:
my-web-dev
define-word
snippets

are unkown on my machine (develop branch)

**Comment by kendall** [comment]
Works for me now. Thanks again.
