### ISSUE TITLE
Error starting spacemacs when non-existent layer is used

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#2952]
Having a non-existent layer in `dotspacemacs-configuration-layers` causes an error during emacs startup: "Wrong type argument: stringp, nil", as reported in #2951. Spacemacs home buffer is shown and a warning buffer, but otherwise it seems like spacemacs didn't load - no key-bindings and no elpa packages have been loaded. To reproduce, add `foo` to `dotspacemacs-configuratoin-layers` and start emacs.

This situation can happen if a user misspells a layer name, or if a layer is removed or renamed. In my case, I had the old `slime` layer enabled. I had the `slime` layer enabled for quite a time now, using develop, so probably a recent change is the source this issue. Debugging showed the error rises from `configuration-layer//declare-layers`. I may have time later to look into this further and submit a patch, but I can't guarantee it.

**Comment by ralesi** [comment]
This one hit me during the recent  update as well.
