### ISSUE TITLE
Develop - layout-double-columns

### ISSUE THREAD

**Issue by malchmih** [syl20bnr/spacemacs#2953]
`SPC-w-2` doesn't work in develop. I get `Symbol's function definition is void: spacemacs/layout-double-columns` in Messages buffer

**Comment by syohex** [comment]
NOTE That command was removed at 6b33031dc5e6e08acea16881f67bcbe4c78e0e65

https://github.com/syl20bnr/spacemacs/commit/6b33031dc5e6e08acea16881f67bcbe4c78e0e65#diff-827687883dd92d9d153d7f51829973e2L327

**Comment by syl20bnr** [comment]
Oops, seems like I was heavy-handed, I'll add it back, thank you.

**Comment by syl20bnr** [comment]
`spacemacs/new-empty-buffer` is also missing.

**Comment by syl20bnr** [comment]
The functions mentioned above are now back into the repo, thank you !

**Comment by malchmih** [comment]
Great, thanks!
