### ISSUE TITLE
`r` entry in Spacemacs Documentation

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#2954]
Pressing `SPC f e h` gives me an `r` entry in the Spacemacs Documentation section right below `Quick HOW-TOs for Spacemacs`

**Comment by Devagamster** [comment]
I'm not seeing this in the develop branch.

**Comment by cpaulik** [comment]
It might have been a fluke. I'm not seeing this here on my work PC. I'll check again back home on my laptop.

**Comment by syl20bnr** [comment]
Maybe you have a file called `r` in `doc` :-)

**Comment by cpaulik** [comment]
Thanks for reminding me. I just checked again and it is gone on latest develop. There is no `r` file in `doc` :smile: and I have no idea what it was.

**Comment by person808** [comment]
IIRC, `r` is a placeholder if `helm-spacemacs` finds a file that it doesn't have a description for. All the descriptions for the `doc/` files are hard coded.
