### ISSUE TITLE
Fullscreen mode extremely slow

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#2957]
When I switch into the Fullscreen mode with `SPC T F` it is extremely slow. However, switching into to transparent mode by using `SPC T T` the problem is gone.

**Comment by Devagamster** [comment]
Are you on a mac? If so take a look here: https://github.com/syl20bnr/spacemacs/issues/1114 near the end of the thread. Some people have noticed perf improvements in weird circumstances by switching to fira mono https://github.com/mozilla/Fira/tree/master/ttf or by turning off unicode in the modeline by setting dotspacemacs-mode-line-unicode-symbols to nil. Dunno if either of these are related but it might help and would give more data.

**Comment by sebhahn** [comment]
No I'm using Ubuntu 15.04, but I'll test unicode symbol settings.

**Comment by Devagamster** [comment]
Another thing to try is run emacs without spacemacs and call toggle-frame-fullscreen and see if its similarly slow. That way we could rule out if its something peculiar to spacemacs.

**Comment by geo7** [comment]
@sebhahn to run emacs without spacemacs enter `emacs -Q` at the terminal.

**Comment by sebhahn** [comment]
I tried `emacs -Q` and the issue exists as well without loading spacemacs...

**Comment by StreakyCobra** [comment]
This has to be reported upstream. This is not a spacemacs bug as the problem persist with `emacs -Q` :unamused:
