### ISSUE TITLE
typo in "Quick Help" 

### ISSUE THREAD

**Issue by YulongNiu** [syl20bnr/spacemacs#2959]
I found a typo in the "Quick Help" (by clicking the [?] button) when Spacemacs starts. To open the .spacemacs file, the help text is " Press SPC f e d (Vim) or Alm-m f e d (Emacs) to access .spacemacs file.". I think the "Alm-m f e d (Emacs)" should be "Alt-m f e d (Emacs)".  I am using the Spacemacs version 0.103.6.

**Comment by mbertheau** [comment]
This was fixed on develop in https://github.com/syl20bnr/spacemacs/commit/8a72da7372a3f7d654184ae218bf968f5ea9069c already. Thanks for the report!
