### ISSUE TITLE
New anaconda-mode completion window is very hard to read

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2960]
It's a dark maroon color with low contrast to the background.  It's very hard to read in most themes.

![Completion](http://synicworld.com/media/out.gif)

**Comment by cpaulik** [comment]
This is a theme specific setting. I'm not sure we can do much about it.

**Comment by synic** [comment]
It looks fine in the two spacemacs themes.  Most of the others it's unreadable.  I don't feel like this is a theme problem, really, but I don't think it's spacemacs either.

 I feel like whatever populating that dropdown is just picking a bad color.  The colors it used before worked on most of the themes I tried.

**Comment by cpaulik** [comment]
I think it is the `company-tooltip-annotation` face. You can check using `M-x describe-face` and then also change it for your theme.
