### ISSUE TITLE
Python layer  --  Anaconda mode will cause Emacs frozen

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#2961]
I'm using the latest develop branch and Emacs-mac branch.

It's really wired.

And the error messages are:

```
error in process sentinel: apply: Wrong type argument: integer-or-marker-p, nil
```

**Comment by zilongshanren** [comment]
I have installed the Anaconda dependencies.  And the configure it working before.
Anything changed here?

**Comment by cpaulik** [comment]
Did it work already after the big anaconda-mode update three days ago or did it break in the meantime?

**Comment by zilongshanren** [comment]
@cpaulik 
I have no idea. It's a long time since the last time I edited the Python files.

**Comment by cpaulik** [comment]
The only thing I can recommend is to try the latest anaconda-mode. In there the major spacemacs related error seems to be fixed.

**Comment by zilongshanren** [comment]
@cpaulik 
Thanks, I will give it a try.

**Comment by zilongshanren** [comment]
@cpaulik 
After uninstall jedi and anaconda-mode from pip.
And upgrade anacond-mode to the latest version from MELPA.

Resolve

```
remove prefix option from distutils.cfg
```


And it works fine now.

Thanks.

**Comment by zilongshanren** [comment]
For anyone who use shadowsocks proxy:

you should also disable it , otherwise the anacond-mode won't work.

```
 ;;(setq socks-server '("Default server" "127.0.0.1" 1080 5))
  ;; (setq url-gateway-method 'socks)

```

**Comment by cpaulik** [comment]
yes proxies can be an issue with anaconda mode.

I've set 

```elisp
(setenv "NO_PROXY" "127.0.0.1")
(setenv "no_proxy" "127.0.0.1")
```

to make it work

**Comment by zilongshanren** [comment]
@cpaulik 

Does the settings break proxy?

**Comment by cpaulik** [comment]
@zilongshanren no, it just sets the no_proxy environment variable which tells programs to contact these IP's directly. It works for my work proxy. Don't know about shadowsocks

**Comment by zilongshanren** [comment]
@cpaulik  I have tested now, it doesn't work with shadowsocks.

I'm planing to create a shadowsocks-proxy minor mode and add a toggle option to this minor mode.

**Comment by dzhwinter** [comment]
For who else search here, I just upgrade anaconda-mode using pip, And it works well for me.
