### ISSUE TITLE
Navigation is borked

### ISSUE THREAD

**Issue by yungstorm** [syl20bnr/spacemacs#2964]
Everytime I try and navigate in spacemacs It  adds >[2 q to the lines..This really annoying because it doesn't allow me to navigate. 
![2015-09-09-134623_598x374_scrot](https://cloud.githubusercontent.com/assets/12653273/9769674/90bf909c-56f9-11e5-86a3-19991fa2d35c.png)

**Comment by cmccloud** [comment]
@yungstorm are you running in terminal?

**Comment by yungstorm** [comment]
@cmccloud yes I'm running it in terminal.

**Comment by cpaulik** [comment]
Probably a  duplicate of https://github.com/syl20bnr/spacemacs/issues/2707 and https://github.com/syl20bnr/spacemacs/issues/2940 . 

Try adding `evil-terminal-cursor-changer` to your `dotspacemacs-exlude-packages`

**Comment by Tritlo** [comment]
I had the same issue in terminal, and @cpaulik's suggestion worked for me.

**Comment by syl20bnr** [comment]
Maybe we should remove this package ?

**Comment by TheBB** [comment]
I think so.

**Comment by dzhwinter** [comment]
same problem+1. It seems no benefits in my opinion. Make cursor become block when browse file and bar edit file.is enough.  .
