### ISSUE TITLE
org layer gives error

### ISSUE THREAD

**Issue by spradnyesh** [syl20bnr/spacemacs#2967]
default "org" layer in ~/.spacemacs gives error:-
"Symbol's value as variable is void: org-planning-line-re"
when trying to do org-clock-in

can be avoided by following the following steps
1. remove/comment "org" layer from ~/.spacemacs
2. add "personal" layer
3. add "org" to "personal-packages" in ~/.emacs.d/private/personal/packages.el
4. add following lines to ~/.emacs.d/private/personal/packages.el
(defun personal/init-org()
  (use-package org
    ;; :mode ("\\.org$" . org-mode) ; see below
    :mode "\\.org$"                      ; see below
    :config
    (progn
      (setq org-drawers '("PROPERTIES" "LOGBOOK" "CLOCK"))
      (setq org-log-into-drawer t)
      (setq org-log-done 'time)
      (setq org-clock-in-resume t)
      (setq org-clock-into-drawer "CLOCK")
      (setq org-clock-out-remove-zero-time-clocks t))))

note that if i do ***:mode ("\\.org$" . org-mode)***, then
1. org-mode is activated automatically when i open a .org file
2. but clock-in does *not* work as expected (add a new entry in the CLOCK drawer)
3. agenda view works

however, if i do ***:mode "\\.org$"***, then 
1. org-mode needs to be activated manually (via M-x org-mode) for any .org file
2. agenda view does *not* work (unless i manually activate org-mode for all .org files)
3. clock-in *works* as expected (add a new entry in the CLOCK drawer)

**Comment by TheBB** [comment]
I can't reproduce this. Have you updated org? Which branch are you on? In which context are you using `org-clock-in`?

**Comment by pdvyas** [comment]
Just encountered this, I am on `develop` (latest)

**Comment by spradnyesh** [comment]
i'm using 
spacemacs v-0.103.6 (updated via "update" on *spacemacs*)
org 20150907

what do you mean by "context" for using org-clock-in?
i'm in "emacs" mode of spacemacs, so i do a C-c C-x TAB to do org-clock-in

**Comment by spradnyesh** [comment]
i'm able to reproduce this in develop branch too. but i think this is happening because i'm using *both* the "org" layer, and "org" package in "personal" layer, and the :init and :config of org/init-org and personal/init-org are conflicting/overriding

the way i solved this is
1. put "org" layer *before* "personal" in ~/.spacemacs 'dotspacemacs-configuration-layers
2. re-write all (necessary for you) parts (setq, hook, bind-key, etc) for both :init and :config again in personal/init-org

things are now working fine. so dunno if this is a bug, or mis-configuration on my part

however, it'll be beneficial if the documentation contains a section on when someone wants a layer, but wants to re-configure 1 (or more) package(s) in his own personal layer

**Comment by TheBB** [comment]
You should probably use `personal/post-init-org` or `pre-init` instead. There can only be one `init` function, but several `pre-init` and `post-init` functions.

See [here](https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#the-spacemacs-loading-process)

**Comment by spradnyesh** [comment]
Super! thanks :)
