### ISSUE TITLE
Hybrid mode weirdness

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#2971]
Maybe it's me but this seems all very hard to understand, especially the part about the key binding depending on whether or not hybrid-mode is active. 

``` elisp
(dotimes (i 10) (eval `(defun ,(intern (format "m%s" i)) () (interactive) (message "m%s" ,i))))
```

Command | Resulting keymap when hybrid-mode on | Keymap when off | Avail in hybrid insert/emacs state | Avail in vim insert
--------|----------------------------|-----------------|------------------------------------|-------------------
`(evil-global-set-key 'insert "\C-r" 'm1)` | hybrid-mode-emacs-state-map | evil-insert-state-map | yes if hybrid mode on when defined | no if hybrid-mode on when defined
`(evil-global-set-key 'emacs "\C-r" 'm2)` | evil-emacs-state-map | evil-emacs-state-map | no in my tests | no
`(define-key evil-insert-state-map "\C-r" 'm3)` | evil-insert-state-map | evil-insert-state-map | no | yes
`(define-key evil-emacs-state-map "\C-r" 'm4)` | evil-emacs-state-map | evil-emacs-state-map | yes but shadowed by m1 | no
`(evil-define-key 'insert emacs-lisp-mode-map "\C-r" 'm5)` | emacs-lisp-mode-map | emacs-lisp-mode-map | yes and shadows previous | yes
`(evil-define-key 'emacs emacs-lisp-mode-map "\C-r" 'm6)` | emacs-lisp-mode-map | emacs-lisp-mode-map | no | no

Update: Not to mention that spacemacs still says `--Insert--` in the echo area even though the documentation says you're in emacs state after exiting normal state.

**Comment by syl20bnr** [comment]
Thank you for all the info.

It is way too much complicated right now, let's go back to what I understood from the beginning about what an hybrid style: it simply being in emacs state when pressing `i` instead of insert.

It reduce to this implementation: https://github.com/syl20bnr/spacemacs/issues/1244#issuecomment-126183700

```elisp
defadvice evil-insert-state (around hyrid-insert-state activate)
  "In Hybrid style this advice is run to switch in emacs state instead of insert state."
  (evil-emacs-state))
```

It is dead easy to explain, no side effects, no surprise, and it is dea easy to switch style by activating/deactivating the advices. It is more over symetric with holy-mode implementation.

**Comment by justbur** [comment]
Sorry @syl20bnr but that's not true. Things do break with that implementation, see for example https://github.com/syl20bnr/spacemacs/issues/1244#issuecomment-131184317

**Comment by justbur** [comment]
and https://github.com/syl20bnr/spacemacs/issues/1244#issuecomment-126230055

**Comment by syl20bnr** [comment]
You are right, can we replace the advice by:

```elisp
(evil-put-property 'evil-state-properties 'insert
                     :mode 'evil-insert-state-minor-mode
                     :keymap 'evil-emacs-state-map
                     :local 'evil-insert-state-local-minor-mode
                     :local-keymap 'evil-emacs-state-local-map))
```

And just add `[escape]` binding like it is [already done in holy mode](https://github.com/syl20bnr/spacemacs/blob/develop/layers/!distribution/spacemacs/local/holy-mode/holy-mode.el#L61) ?

**Comment by justbur** [comment]
That was one of the points I was making in the table above. In this case, 
```elisp
(evil-global-set-key 'insert "\C-r" 'm1)
```
would put the binding in `evil-emacs-state-map` if hybrid-mode is active but in `evil-insert-state-map` if it's not. The problem is the dynamic lookup of the keymap which would change depending on state.

**Comment by justbur** [comment]
I really think the best thing to do is to stick to evil's structure as much as possible. I'd also be willing to entertain just defining a brand new state, but I think swapping keymaps but keeping the rest of the state is just weird and has weird side-effects

**Comment by justbur** [comment]
By the way, holy-mode breaks stuff like evil-repeat too, so I don't think it's a good model for hybrid mode. If people are starting in normal mode, I think they expect things like evil-repeat to work.

**Comment by syl20bnr** [comment]
That's ok with me, if a user uses hybrid mode then he binds to emacs state. In your case if he binds to insert then it ends up being still available in hybrid. It may be an issue when switching the style dynamically though but I don't think any user will run in this issue in practice.

**Comment by syl20bnr** [comment]
Emacs style is not meant to have evil repeat etc... emacs style is plain emacs with an access to normal state to go wild :-) But it is just emacs.

**Comment by justbur** [comment]
Let's just define a new state. We can call it hybrid-emacs state with it's own keymap, and under the covers it will function like insert state without any vim-keybindings. 

I feel like all of this effort is just to get something called "emacs state". The solution I came up with before was functionally equivalent to what everyone is after but used different names, and didn't have all of these weird edge cases. 

If people want to bind to emacs state, they can then bind in hybrid-emacs-state-map (it's more specific and also obvious what you're doing). Does that work?

**Comment by justbur** [comment]
Also something like this would work

That was one of the points I was making in the table above. In this case, 
```elisp
(evil-global-set-key 'hybrid-emacs "\C-r" 'm1)
```
would put the binding in `evil-emacs-state-map` if hybrid-mode is active but in `evil-insert-state-map` if it's not. The problem is the dynamic lookup of the keymap which would change depending on state.

**Comment by justbur** [comment]
Here's most of the code for insert state that we would copy and then redefine for hybrid-emacs

```elisp
;;; Insert state

(evil-define-state insert
  "Insert state."
  :tag " <I> "
  :cursor (bar . 2)
  :message "-- INSERT --"
  :entry-hook (evil-start-track-last-insertion)
  :exit-hook (evil-cleanup-insert-state evil-stop-track-last-insertion)
  :input-method t
  (cond
   ((evil-insert-state-p)
    (add-hook 'pre-command-hook #'evil-insert-repeat-hook)
    (unless (eq evil-want-fine-undo t)
      (evil-start-undo-step t)))
   (t
    (remove-hook 'pre-command-hook #'evil-insert-repeat-hook)
    (setq evil-insert-repeat-info evil-repeat-info)
    (evil-set-marker ?^ nil t)
    (unless (eq evil-want-fine-undo t)
      (evil-end-undo-step t (eq evil-want-fine-undo 'fine)))
    (when evil-move-cursor-back
      (when (or (evil-normal-state-p evil-next-state)
                (evil-motion-state-p evil-next-state))
        (evil-move-cursor-back))))))

(defun evil-insert-repeat-hook ()
  "Record insertion keys in `evil-insert-repeat-info'."
  (setq evil-insert-repeat-info (last evil-repeat-info))
  (remove-hook 'pre-command-hook #'evil-insert-repeat-hook))
(put 'evil-insert-repeat-hook 'permanent-local-hook t)

(defun evil-cleanup-insert-state ()
  "Called when Insert state is about to be exited.
Handles the repeat-count of the insertion command."
  (when evil-insert-count
    (dotimes (i (1- evil-insert-count))
      (when evil-insert-lines
        (evil-insert-newline-below))
      (when (fboundp 'evil-execute-repeat-info)
        (evil-execute-repeat-info
         (cdr evil-insert-repeat-info)))))
  (when evil-insert-vcount
    (let ((buffer-invisibility-spec buffer-invisibility-spec))
      ;; make all lines hidden by hideshow temporarily visible
      (when (listp buffer-invisibility-spec)
        (setq buffer-invisibility-spec
              (evil-filter-list
               #'(lambda (x)
                   (or (eq x 'hs)
                       (eq (car-safe x) 'hs)))
               buffer-invisibility-spec)))
      (let ((line (nth 0 evil-insert-vcount))
            (col (nth 1 evil-insert-vcount))
            (vcount (nth 2 evil-insert-vcount)))
        (save-excursion
          (dotimes (v (1- vcount))
            (goto-char (point-min))
            (forward-line (+ line v))
            (when (or (not evil-insert-skip-empty-lines)
                      (not (integerp col))
                      (save-excursion
                        (evil-move-end-of-line)
                        (>= (current-column) col)))
              (if (integerp col)
                  (move-to-column col t)
                (funcall col))
              (dotimes (i (or evil-insert-count 1))
                (when (fboundp 'evil-execute-repeat-info)
                  (evil-execute-repeat-info
                   (cdr evil-insert-repeat-info)))))))))))
```

**Comment by justbur** [comment]
It's obvious that a lot more is going on there than this

```elisp
(evil-define-state emacs
  "Emacs state."
  :tag " <E> "
  :message "-- EMACS --"
  :input-method t
  :intercept-esc nil)
```

**Comment by syl20bnr** [comment]
+1 for a new state :-)

**Comment by justbur** [comment]
ok I'll throw together something to test out

**Comment by syl20bnr** [comment]
Hybrid mode has now its own state which should remove all the ambiguities. Thank you @justbur !

**Comment by justbur** [comment]
Closing, because I don't think hybrid exists on master yet
