### ISSUE TITLE
Completion: C-k not working consistently

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#2974]
`C-j` and `C-k` are bound to select completion candidates. But after the company quickhelp window popped up `C-k` is no longer working correctly. It is only producing `^K` in the buffer. 

Disabling `company-quickhelp` is a partial workaround but the same problem happens after pressing `C-d` to get to the documentation.

https://github.com/expez/company-quickhelp/issues/17 suggested a possible solution of putting the keybindings into the `company-completion-finished/cancelled/started-hook`'s but this did not work for me.

**Comment by nixmaniack** [comment]
This works pretty fine with me in hybrid state.
```elisp
(evil-define-key 'hybrid company-active-map (kbd "C-j") 'company-select-next)
(evil-define-key 'hybrid company-active-map (kbd "C-k") 'company-select-previous)
```

**Comment by StreakyCobra** [comment]
@nixmaniack With `company-quickhelp-mode` activated?

**Comment by nixmaniack** [comment]
@StreakyCobra  I have `auto-completion-enable-help-tooltip` set to `t` which activates `company-quickhelp-mode` if I'm not wrong. So yes. 
A point to be noted, I've only used this with hybrid style though.

**Comment by StreakyCobra** [comment]
Ok, so it may be a clue about the bug :-)

**Comment by al3xandru** [comment]
Updating this ticket with what I've learned on #5817:

1. `company-quickhelp-mode` seems to be on (value is `t`). Is this enabled by setting `auto-completion-enable-help-tooltip`?

2.  if  `auto-completion-enable-help-tooltip` is `nil` then `C-k` seems to work as expected.

3. based on the above, after setting the following, `C-k` continues to behave as expected:

```
(evil-define-key 'insert company-quickhelp-mode-map (kbd "C-k") 'company-select-previous)
```

**Comment by abcdw** [comment]
@al3xandru thanks for workaround.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by cmlaverdiere** [comment]
Still happens to me.

**Comment by abcdw** [comment]
@d12frosted Reopen this issue plz.

**Comment by eullerborges** [comment]
Seconding @cmlaverdiere, still happens to me.

**Comment by malchmih** [comment]
@eullerborges @cmlaverdiere @abcdw Workaround mentioned here works for me: https://github.com/expez/company-quickhelp/issues/63#issuecomment-312481562
```elisp
  (add-hook
   'company-completion-started-hook
   (lambda (&rest ignore)
     (when evil-mode
       (when (evil-insert-state-p)
         (define-key evil-insert-state-map (kbd "C-k") nil)))))
```

**Comment by eullerborges** [comment]
@malchmih Works like a charm. Thanks a lot.
I'm having problems with spacemacs crashing with SIGSEV (somehow related to auto-complete and anaconda), but I get not output in the terminal I've launched it from. Do you know of any ways to log the crash info?

**Comment by sdwolf** [comment]
See this link on how to debug segmentation faults:

https://github.com/syl20bnr/spacemacs/wiki/Debugging#debugging-segmentation-faults-with-gdb

**Comment by FieryCod** [comment]
@TheBB Are there any plans to include @malchmih suggestion to the develop branch?

**Comment by richarddewit** [comment]
*Spongebob's narrator: "One Year Later"*

While the workaround by @malchmih works, this is still an issue in the latest develop (commit b00767cd6ec718df969bb1b7f713e5030ecf3c3e)

**Comment by sdwolfz** [comment]
If somebody opens a PR with it then we can merge it. We have more active maintaiers now so it should not take long.

**Comment by smile13241324** [comment]
Merged the fix from duianto on develop just now. @cpaulik would you mind checking that this solves the issue for you and close it when it does?

On my system it solved the issue in emacs and python mode.
