### ISSUE TITLE
Develop - Behavior of `:` in Ranger is not consistent

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2976]
The docs do not say what `:` is supposed to do in spacemacs.  In regular emacs, it's supposed to create an input for advanced ranger commands, like `:mkdir`.  

In spacemacs, it *sometimes* does that.  I'm not sure what conditions cause it to behave that way, it seems very random.  Other times it does this:

http://d.pr/i/1b4xv/1j6EdyXr

Since the documentation doesn't say what `:` is supposed to do, I'm not sure what the actual bug is here.  However, the behavior of `:` should probably at least be consistent.

**Comment by syl20bnr** [comment]
@ralesi can you look at it ?

**Comment by synic** [comment]
This was fixed upstream.
