### ISSUE TITLE
Develop - Ordering by name in Ranger is broken.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#2977]
Steps to reproduce:

1. Press `SPC a r` to open ranger.
2. Press `o` for ordering
3. Press `n` for name.

The directory listing will go away.  I'm not sure at this point how to get it back other than restarting ranger. 

There is a message: "insert-directory: Listing directory failed but `access-file' worked".

**Comment by syl20bnr** [comment]
It may be useful to report this upstream: https://github.com/ralesi/ranger/issues
If you do, please add a link to the issue here so we can track it.

**Comment by synic** [comment]
This is fixed upstream.
