### ISSUE TITLE
Getting an error on latest develop (b45911f)

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#2980]
```
progn: Symbol's value as variable is void: hybrid-mode
```

This is happening since b45911f3d538538e33b0ad86e81a6b1d4a095cc0 and likely related to #2973, which broke things and left `develop` in a broken state.

**Comment by malchmih** [comment]
+1

**Comment by robbyoconnor** [comment]
[This line](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bdistribution/spacemacs-core/packages.el#L38) -- what the heck?!

**Comment by bmag** [comment]
With latest develop, the directory `layers/+distribution/spacemacs-core/local/hybrid-mode` is missing - probably has been deleted by accident at a recent commit.
As a temporary work-around, adding `hybrid-mode` to `dotspacemacs-excluded-packages` prevents this error.

**Comment by robbyoconnor** [comment]
@bmag -- #2973 did it likely...but it's a problem for anyone who uses hybrid-mode -- for me it's not an issue...I don't mind breakage...I expect it...such is the price of using bleeding edge -- but this is bad lol

**Comment by robbyoconnor** [comment]
For anyone having issues, cherrypick #2983 and things will work.

**Comment by syl20bnr** [comment]
Merged, thanks for the report and the fix.

**Comment by robbyoconnor** [comment]
@syl20bnr things happen -- This is why I never worry about using `develop` -- things are always fixed fast :)

**Comment by justbur** [comment]
@robbyoconnor sorry for breaking your spacemacs. I just wanted to mention that any time you get a void variable error (or wrong type error) it can be really helpful to have a backtrace to look at. It's also not clear from your report if you use hybrid-mode, have it excluded in your .spacemacs, or are doing something else with it in your personal config, all of which can be relevant.

**Comment by robbyoconnor** [comment]
Yeah...I use vim editing mode...sorry about that :) it's cool <3

--Rob
