### ISSUE TITLE
Specifying filetype in `SPC+/`

### ISSUE THREAD

**Issue by jesenko** [syl20bnr/spacemacs#2982]
When using this command, it would be very handy to filter search results based on filetype / part of path+filename. 

I found no easy solution for this in documentation or searching on the Gitter...

**Comment by justbur** [comment]
This search function is based on [helm-ag](https://github.com/syohex/emacs-helm-ag) which appears to support passing command line options. It will depend on what external tool you are using though

**Comment by syl20bnr** [comment]
`helm-ag` supports extension specification by using the universal argument prefix (`C-u` in Emacs, `SPC u` in Spacemacs). When a base directory is provided to `helm-ag` then `SPC u` is ignored. I opened a merge request for this here: https://github.com/syohex/emacs-helm-ag/pull/165

**Comment by jesenko** [comment]
@syl20bnr Great, thank you!

**Comment by syl20bnr** [comment]
The PR has been merge, update your packages when [the new version of helm-ag](http://melpa.org/#/helm-ag) is available.

**Comment by justbur** [comment]
I came up with a new way to do this and submitted a pr at helm-ag. It lets you narrow by file name after starting a search. I don't know if it will be accepted but it could also be implemented on the Spacemacs side if people here are interested

**Comment by justbur** [comment]
https://github.com/syohex/emacs-helm-ag/pull/166

**Comment by TheBB** [comment]
Closing this as fixed. If you need to discuss your PR, @justbur, you can open another one.
