### ISSUE TITLE
python layer: can't start 'anaconda-mode' server

### ISSUE THREAD

**Issue by geekplux** [syl20bnr/spacemacs#2992]
I use the master branch of spacemacs and install the python layer.

and there was a error when I open a python file first time... ( python is new to me )
Is this because of my python version?
or `anaconda-mode`  causing it..

![70c62910-a49e-407d-801c-6e79005a6c3a](https://cloud.githubusercontent.com/assets/3816105/9830347/554925f8-595d-11e5-8c10-f7f4a3d0a848.png)

**Comment by TheBB** [comment]
Not sure, but anaconda mode has had a major update recently, and there are a number of fixes regarding it that only exist in the develop branch at the moment. You might have better luck there.

**Comment by geekplux** [comment]
nothing changes just like before, when switched to `develop` branch

**Comment by cpaulik** [comment]
@geekplux Do you have `anaconda-mode.py` and ancillary files in your `~/.emacs.d/anaconda-mode` folder? This should be installed automatically by `anaconda-mode` when first started.

**Comment by geekplux** [comment]
@cpaulik  I find the `anaconda-mode` folder in my `~/.emacs.d`, but I can't find the `anaconda-mode.py`..

**Comment by geekplux** [comment]
@TheBB @cpaulik 
It works well after I remove prefix option from `distutils.cfg`.
And the cause of this problem is that I installed the pip and python with `brew`

refrence issue: [can't start 'anaconda-mode' server #114](https://github.com/proofit404/anaconda-mode/issues/114)

**Comment by chrissound** [comment]
I've run into this issue again - solved it by the solution posted in https://github.com/proofit404/anaconda-mode/issues/114
