### ISSUE TITLE
Candicates in company popup will be shifted when overlap with org headings

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#2994]
![image](https://cloud.githubusercontent.com/assets/785541/9830403/5b06f018-595f-11e5-8d87-9dbfec5f80d9.png)

As from the above pic, we could see that "code" is shift right a little bit.

And if we write after the heading, the shifting issue is gone.

**Comment by zilongshanren** [comment]
![image](https://cloud.githubusercontent.com/assets/785541/9830406/91fbe358-595f-11e5-86f2-a7ab212a0028.png)

**Comment by TheBB** [comment]
Yeah, I disabled company in org because of this.

**Comment by zilongshanren** [comment]
@TheBB 
So you don't enable any auto complete feature in your org buffer?

**Comment by TheBB** [comment]
Nope. Frankly, it's pretty useless anyway, isn't it?

**Comment by zilongshanren** [comment]
@TheBB 
:smile:  Yeah, all completion could be replaced with hippie-expand.
Thanks for the info, I will disable it from now on.
