### ISSUE TITLE
ace-jump not working in develop

### ISSUE THREAD

**Issue by malchmih** [syl20bnr/spacemacs#2995]
Getting `SPC SPC is undefined` now

**Comment by TheBB** [comment]
What's the output of your `SPC h d s`? Have you made any custom leader bindings? If you're on develop, which distribution have you chosen?

**Comment by malchmih** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.104.0
- Spacemacs branch: develop (rev. 139b323)
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t)
 (clojure :variables clojure-enable-fancify-symbols t)
 dash emacs-lisp evil-commentary eyebrowse games git html ibuffer org scala
 (shell :variables shell-default-shell 'multi-term shell-enable-smart-eshell t)
 syntax-checking themes-megapack user)
```
I'm using Ubuntu. I've made a few, but only for clojure layer. ace-jump doesn't work on startup screen for me.
It worked yesterday.

**Comment by malchmih** [comment]
The same thing on my Mac (with the same .spacemacs).

**Comment by TheBB** [comment]
If it worked yesterday, what commit were you on then? Any chance you can bisect this problem?

**Comment by malchmih** [comment]
Did git bisect (heh, first time in my life :smile: : )
```
6e0ca23db8886b12fe8ed43f2fd66e08c0373374 is the first bad commit
commit 6e0ca23db8886b12fe8ed43f2fd66e08c0373374
Author: syl20bnr <sylvain.benner@gmail.com>
Date:   Fri Sep 11 23:00:33 2015 -0400

    core: set default distribution in template to spacemacs-core
    
    Also remove version-control layer from template and add emacs-lisp
    to initial value for dotspacemacs-configuration-layers
```

**Comment by darker0n** [comment]
+1

**Comment by justbur** [comment]
@syl20bnr this is probably the default choice of distro for people who don't have this variable in their dotfile.

**Comment by TheBB** [comment]
Yeah, set `dotspacemacs-distribution` to `spacemacs` in your `dotspacemacs/layers` function. See the updated dotfile template for details.

**Comment by justbur** [comment]
The fix should be to set dotspacemacs-distribution to 'spacemacs in dotspacemacs/init

**Comment by malchmih** [comment]
Thank you, ace-jump works now with `dotspacemacs-distribution 'spacemacs`. But why `spacemacs-core` doesn't work? Is it WIP?

**Comment by TheBB** [comment]
`spacemacs-core` doesn't include avy.

**Comment by TheBB** [comment]
See #2937 for some discussion on how to improve the granularity.

**Comment by justbur** [comment]
Reference for this problem https://github.com/syl20bnr/spacemacs/pull/2984#issuecomment-139706997

**Comment by malchmih** [comment]
Thanks again!

**Comment by malchmih** [comment]
But now `,` doesn't work in clojure file. `SPC m` works. On `,` I get `No previous search`
Can it be somehow connected with the issue above? If not, I'll create another issue.

**Comment by TheBB** [comment]
It's another issue. The major mode leader key is bugged in clojure.
