### ISSUE TITLE
Help doesn't work in Helm minibuffer

### ISSUE THREAD

**Issue by sindikat** [syl20bnr/spacemacs#3003]
I'm using develop branch from 12/09/2015, <kbd>SPC f e v</kbd> returns `Spacemacs v.0.104.0`.

Try pressing <kbd>SPC f C-h</kbd> or <kbd>SPC b C-h</kbd>. The help window won't appear, the echo area would show:

    unrecord-window-buffer: Lisp nesting exceeds `max-lisp-eval-depth'

If you try to press <kbd>SPC f</kbd>, Helm mini-window won't even appear, so you would need to first run some command, like <kbd>SPC f f</kbd>, and then Helm mini-window would start to appear again.

**Comment by TheBB** [comment]
Have you updated your packages?

I can't reproduce this. @justbur might have to take a look.

**Comment by sindikat** [comment]
I updated 2 packages:

- `anzu` from `anzu-20150912.406` to `anzu-20150912.1939`
- `evil` from `evil-20150908.0` to `evil-20150912.1655`

The problem is gone, <kbd>C-h</kbd> works in Helm now.
