### ISSUE TITLE
Top row of buttons missing in spacemacs buffer

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#3004]
commit 77161bd causes the top row of button to be missing when dotspacemacs-startup-banner is nil.

<img width="683" alt="screen shot 2015-09-13 at 7 57 56 am" src="https://cloud.githubusercontent.com/assets/302945/9834249/911c12da-59ed-11e5-956b-d7b0264ad0f3.png">

**Comment by TheBB** [comment]
#3008 fixes this.
