### ISSUE TITLE
source-code-pro font not working

### ISSUE THREAD

**Issue by rebcabin** [syl20bnr/spacemacs#3006]
On a Yosemite mac book pro, I clone `https://github.com/adobe-fonts/source-code-pro` and install *all* the ttf fonts in the `Roman` and `Italic` directories using mac FontBook app and start emacs.  All glyphs appear as rectangular blocks in spacemacs.  

Not blocking because I just remove the fonts from FontBook and spacemacs uses whatever it falls back to (I think it's menlo on my box, but it's workable).

**Comment by robbyoconnor** [comment]
This isn't a bug with Spacemacs. This is an issue of [PEBKAC](http://www.urbandictionary.com/define.php?term=pebkac).

**Comment by rebcabin** [comment]
I'm sure it is PEBKAC (I suffer from a fatal case); I'd still be grateful for advice.

**Comment by sooheon** [comment]
What's the value of dotspacemacs-default-font? What about fontset-alias-alist?

**Comment by rebcabin** [comment]
respectively

    ("Source Code Pro" :size 13 :weight normal :width normal :powerline-scale 1.1)

```
(("-*-Menlo-normal-normal-normal-*-*-*-*-*-m-0-fontset-startup" . 
  "-*-menlo-normal-normal-normal-*-12-*-*-*-m-0-iso10646-1") 
("-*-Menlo-normal-normal-normal-*-*-*-*-*-m-0-fontset-startup" . "fontset-startup") 
("-ns-*-*-*-*-*-10-*-*-*-*-*-fontset-standard" . "fontset-standard") 
("-*-*-*-*-*-*-*-*-*-*-*-*-fontset-default" . "fontset-default"))
```

**Comment by sooheon** [comment]
Have you tried all the usual ways to adjust font settings? http://emacs.stackexchange.com/questions/2501/how-can-i-set-default-font-in-emacs

**Comment by TheBB** [comment]
Is there a reason you aren't just installing the releases and must build from source?

**Comment by rebcabin** [comment]
@TheBB the link in spacemacs DOCUMENTATION.org sent me to the build site for source-code-pro.  I didn't actually have to build the fonts---the .ttf files were in the distro after I cloned it.

https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#font

**Comment by rebcabin** [comment]
@sooheon I'm confused.  The link shows several ways to hack around emacs customization facilities.  I'm using nothing but spacemacs, no other emacs settings or configs, so I wouldn't want to work around the spacemacs way of setting fonts, would I?  My `.spacemacs` has this line
```
   dotspacemacs-default-font '("Source Code Pro"
                               :size 13
                               :weight normal
                               :width normal
```

**Comment by sooheon** [comment]
Just tried installing SCP from that source just to see if it works for me, also Yosemite MBP. Setting the dotspacemacs-default-font variable works, as does using set-fontset-font like so:
```
(let ((fontset "fontset-default"))
    (set-fontset-font fontset 'latin '("Input Mono Narrow" . "unicode-bmp"))
    (set-fontset-font fontset 'hangul '("NanumBarunGothic" . "unicode-bmp"))
    (set-face-attribute 'default nil
                        :font fontset
                        :height 120))
```

However, I downloaded the release from the repo, and I *didn't* clone it. Looking in the repo, the ttf font in the directory is simply called `font.ttf` maybe it's a naming problem? Try just downloading the latest release and copying the font filed over from there into Font Book.

**Comment by rebcabin** [comment]
ok, i'll close it for spacemacs.  I appreciate the help; i think I have enough clues to diagnose.

**Comment by lulin** [comment]
I got the same problem, but I can't fix it. I'll try DejaVu Sans Mono instead.

**Comment by marcoslhc** [comment]
If you are in macOS X make sure you install the font in the global folder `/Library/Fonts` instead of `~/Library/Fonts`
You can do that by using:
```
$ brew tap caskroom/fonts
$ brew cask install font-source-code-pro --fontdir=/Library/Fonts
```

**Comment by digizeph** [comment]
@marcoslhc this works perfectly on my mac (macOS Sierra 10.12.4). Thank you!

**Comment by robbyoconnor** [comment]
Perhaps add to the docs?

**Comment by marcoslhc** [comment]
@robbyoconnor definitively a good idea. I'll send a PR

**Comment by waltervargas** [comment]
Thank you @marcoslhc.

```
$ brew tap caskroom/fonts
$ brew cask install font-source-code-pro --fontdir=/Library/Fonts
```

worked for me: 

```
Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by ilidio** [comment]
```
% brew tap homebrew/cask-fonts 
% brew install font-source-code-pro --cask      
```

**Comment by lebensterben** [comment]
locking since this is not a bug.
also note that there's guide on how to install source code pro font in https://github.com/syl20bnr/spacemacs/blob/290d873f916d5d0a030342ffb91a4ccb06bb9f26/README.md
