### ISSUE TITLE
Evil/Vim = register not working

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#3010]
The = register doesn't seem to work.  Unfortunately I don't have time to dig into this right now.

Reproduce:

Type

    "=p2*2<Enter>

or

    i<ctrl-R>=2*2<Enter>

Should insert 4 into the buffer but nothing is inserted.  Might be interfering with the paste cycling mini mode.

**Comment by TheBB** [comment]
In vim, the expression register evaluates vimscript. Evil doesn't have a vimscript engine, so the expression register evaluates elisp. If you try `(* 2 2)` it should work.

**Comment by darkfeline** [comment]
Thanks, that makes sense.

**Comment by sillyg00se** [comment]
Thanks, it works!

**Comment by MoHKale** [comment]
so it's an alternative for `C-u M-:` where you also have C-r available to access other register values... epic :)
