### ISSUE TITLE
gc-cons-threshold startup time speedup

### ISSUE THREAD

**Issue by CarlQLange** [syl20bnr/spacemacs#3011]
Hey,

I guess this is more a system-specific thing, in that it probably shouldn't be set by default, but setting `(setq gc-cons-threshold 100000000)` as the first line in `init.el` took my startup time from 5.5s to 3.5, which is a pretty decent improvement. (Yes, I use emacs as a persistent server, emacsclient etc, but still, I like short startup times)

I guess just a thought? [I'm sure everyone's seen the thread on reddit I got the idea from.](https://www.reddit.com/r/emacs/comments/3kqt6e/2_easy_little_known_steps_to_speed_up_emacs_start/)

Cheers

**Comment by bmag** [comment]
There already is a similar line in https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bdistribution/spacemacs-core/config.el#L229, but I guess it's executed a bit too late to help startup time? Moving that line to `init.el` didn't help much in my case (from ~3.7s to ~3.3s)

**Comment by CarlQLange** [comment]
Didn't help much? Maybe it's the old game dev in me coming out, but 400ms is a super long time! :)
In any case, I think you're right - that should be moved to very early in `init.el`.

I also experimented with compiling all the elisp in .emacs.d/, and while i did come out of that with a 200ms improvement I don't think it's worth the hassle.

**Comment by CarlQLange** [comment]
Also, man the Spacemacs architecture has changed since I last contributed in like March... `+distributions`? Are there gonna be others?

**Comment by TheBB** [comment]
See #2937 for that.

**Comment by syl20bnr** [comment]
I made the change, thank you :-)

**Comment by person808** [comment]
It may be good to restore it to be closer to the default after init finishes. See this [comment](https://www.reddit.com/r/emacs/comments/3kqt6e/2_easy_little_known_steps_to_speed_up_emacs_start/cv05c2j)

**Comment by syl20bnr** [comment]
Indeed, thank you ! PR welcome :-)

**Comment by synic** [comment]
I guess you all saw the same reddit thread I did.  After I read it, I went searching for the **proper** value to set it to, and found this:

http://lists.gnu.org/archive/html/help-gnu-emacs/2007-09/msg00241.html

It makes me wonder if manually setting `gc-cons-threshold` will end up disabling this other feature, which was created to solve this issue.

**Comment by syl20bnr** [comment]
Good question I think it does not, or it would be surprising it does. Setting this variable should set the initial amount but not prevent the % feature to happen.
It has to be verified by monitoring the amount of GCed memory. This is the kind of metric that would be helpful to plot with `dotspacemacs-configuration-layers` set to `all`.
