### ISSUE TITLE
Eclim server isn't working properly

### ISSUE THREAD

**Issue by LuoPX-15510486969** [syl20bnr/spacemacs#3012]
filrst,when i and java layer and have set the eclim variables i have to open a java file to use the keybinding, it seems not so good . And in holy mode M-m does not work while SPC can work.
second , it seems that eclimed server does not work with java mode ,for example when i use auto-complete it does not complete the library function it can only complete in comtext.

**Comment by geo7** [comment]
@LuoPX-15510486969 sorry I can't help - other than to say that titling the issue something along the lines of "*Eclim server isn't working properly*" might help others find this and maybe others help solve. I initially thought you were just commenting that it was working well ;)

**Comment by LuoPX-15510486969** [comment]
i put all config in the docspacemacs/config function which comes from the auther [document](https://github.com/senny/emacs-eclim)  and i do not know it is related with spacemacs.

**Comment by Devagamster** [comment]
I use eclim every day and although pretty slow it works fine. Do you have eclim installed properly in eclipse?

**Comment by LuoPX-15510486969** [comment]
thanks for your comment that let me know the default java layer can work. it is possilbe my incorrect setting to result in eclim working badly. I will check it out.

**Comment by LuoPX-15510486969** [comment]
thanks for these guys ,  i have find the reason: after i set auto-completion-enable-snippets-in-popup to t , it works well.

**Comment by geo7** [comment]
@LuoPX-15510486969 :+1: maybe close this if alls good ;)

**Comment by LuoPX-15510486969** [comment]
but there is still another question here: when i edit xml files in the same project ,the auto-complete does not work.any body who know how to fix it ?

**Comment by TheBB** [comment]
Well, this issue was about eclim, not XML. But anyway... what kind of completions are you expecting in XML? XML is a meta-language where basically anything goes. There are no keywords, variables or functions to complete. What is it you're typing and what is it you're expecting to see?

For example, I get HTML autocompletion in XML mode:

![XML](http://i.imgur.com/ixWPKx1.png)

Do you have the `html` layer enabled?

**Comment by LuoPX-15510486969** [comment]
this is the screenshot in eclipse, what i expect is just auto-complete something like keywords and some constants. i have add html layer ,but it seems none of android xml files.
![image](https://cloud.githubusercontent.com/assets/13256245/9904238/d244dd14-5cae-11e5-93c1-3e2bb2553112.png)

**Comment by TheBB** [comment]
Okay, you want some kind of special auto-completion for android XML. I'm not sure something like that exists for comany-mode. You can probably get some of it done by using the `company-capf` backend, e.g. something like

```lisp
(push '(company-web-html company-capf) company-backends-web-mode)
```

But it's not going to be as good as a specific backend for the language you're working with.

**Comment by TheBB** [comment]
It sounds like it shouldn't be so hard to write such a backend yourself, though, so long as you have a list of all the valid attributes and tags.

**Comment by LuoPX-15510486969** [comment]
sorry, i am new to emacs and elisp ,so it sounds hard for me to write something .what is worse my major is civil engeering . so you know.....

**Comment by TheBB** [comment]
Yeah, sorry... I didn't mean to suggest that it had to be you, necessarily. Maybe it's a feature request for eclim(d).

**Comment by Devagamster** [comment]
emacs-eclim doesn't have that much in the way of support for other languages than java at the moment. Eclim proper does have some support, so it might be possible in the future, but at the moment I don't think it is supported. That on top of the fact that the emacs-eclim project appears to be losing steam :(

**Comment by Devagamster** [comment]
@TheBB is totally right though, its likely that you could add a separate company backend to fill the gap. I'd be interested to hear if you find something.

**Comment by StreakyCobra** [comment]
As the original issue was solved and the discussion moved to some points not directly related to Spacemacs, I'm closing this issue. Anyway, feel free everybody to open a new issue in case of problem :relaxed:
