### ISSUE TITLE
auto-completion layer: company-mode/more-than-prefix-guesser not defined in C++ mode

### ISSUE THREAD

**Issue by rebcabin** [syl20bnr/spacemacs#3015]
In the develop branch, steps to repro

* ensure `auto-completion` is in `dotspacemacs-configuration-layer`
* edit an existing C++ file
* start typing the name of a variable that exists elsewhere in the file
* observe error `Symbol's function definition is void: company-mode/more-than-prefix-guesser`
* `find-grep-dired ~/.emacs.d/layers/auto-completion` for `more-than-prefix-guesser`, observe that it seems not to be defined anywhere in the configuration layer

**Comment by TheBB** [comment]
Thanks. This should be fixed in develop now.

**Comment by TheBB** [comment]
The function is defined in the `c-c++` layer if you enable clang support.

**Comment by rebcabin** [comment]
ty :)
