### ISSUE TITLE
Symbol's function definition is void: evil-alternate-buffer

### ISSUE THREAD

**Issue by jmcarthur** [syl20bnr/spacemacs#3017]
`SPC TAB` gives this error in the develop branch.

**Comment by TheBB** [comment]
Something must be wrong with your evil installation. That function certainly exists, line 3433 of `evi-commands.el`. Try deleting evil and reinstalling it. (That's the evil-xxx folder in `.emacs.d/elpa`)

**Comment by jmcarthur** [comment]
I just did what you suggested and have the same problem. I also tried with a fresh .spacemacs file. I still see the same result.

**Comment by TheBB** [comment]
Does the same happen if you `(require 'evil-commands)` manually?

**Comment by TheBB** [comment]
Anything out of the ordinary in `*Messages*`?

**Comment by jmcarthur** [comment]
Yes, it still happens with `(require 'evil-commands)`. I don't see anything strange in `*Messages*`. I will try a totally fresh .emacs.d and .spacemacs to be absolutely sure of all this in a second.

**Comment by TheBB** [comment]
Have you checked that your `evil-commands.el` actually does contain this function?

**Comment by jmcarthur** [comment]
Confirmed that `evil-commands.el` contains the function. However, it looks like there is no `evil-commands.elc`. I don't know what would cause that.

**Comment by syl20bnr** [comment]
@jmcarthur What is your OS and Emacs version ?

**Comment by jmcarthur** [comment]
Even if I start a totally fresh Spacemacs, including installing all necessary packages from Elpa from scratch, this still happens.

OS: Arch Linux x86_64, kernel 4.1.6
Emacs: 24.5.1

**Comment by jmcarthur** [comment]
When I try to byte compile evil-commands manually, I get the following error:

evil-commands.el:1364:1:Error: Unknown interactive code: `<addr>'

**Comment by jmcarthur** [comment]
I just found a bunch of old emacs packages sitting around that I had installed with my package manager a long time ago. Among them was some old version of evil. Removing the packages fixed the problem. I think there is no bug here.
