### ISSUE TITLE
Convention for remapping layer's key bindings?

### ISSUE THREAD

**Issue by arnm** [syl20bnr/spacemacs#3018]
I prefer `jkl;` to `hjkl` and would like to apply this as much as possible across all layers. It is easy enough to remap the evil motion keys in `dotspacemacs/config` but I don't know if it's that simple for bindings specified in other layers.

I specifically want to override the `gh` `gj` `gk` `gl` in the org layer right now but I do see myself needing to remap other bindings specified in other layers.

So my questions are:
1. How can I go about remapping those org layer commands?
2. Is there a common way to remap keybindings specified in layers?

P.S I'm new to spacemacs...I see there are a lot of conventions and was wondering if there was one for remapping bindings specified in layers.

**Comment by arnm** [comment]
I was able to remap the org-mode bindings but I had to look though evil-org code instead of just the org layer. I guess question 2 depends on the layer itself...

```
(evil-define-key 'normal evil-org-mode-map
    "gj" 'outline-up-heading
    "gk" 'org-forward-heading-same-level
    "gl" 'org-backward-heading-same-level
    "g;" 'outline-next-visible-heading)
```

**Comment by syl20bnr** [comment]
Look at key translation, for instance:

```elisp
(define-key key-translation-map (kbd ";") (kbd "l"))
```

**Comment by arnm** [comment]
Haven't looked too into to much yet but as of now the key translation works but it also takes affect in insert mode which is not desired.

**Comment by syl20bnr** [comment]
Try:

```elisp
(evil-define-key 'normal key-translation-map (kbd ";") (kbd "l"))
```

This should work only in `normal` state, rince and repeat for other states :-)

**Comment by arnm** [comment]
hmm I see what you are trying to do but it doesn't seem to work for me :(

```elisp
  ;; remappings
  (evil-define-key 'normal key-translation-map (kbd "j") (kbd "h"))
  (evil-define-key 'normal key-translation-map (kbd "k") (kbd "j"))
  (evil-define-key 'normal key-translation-map (kbd "l") (kbd "k"))
  (evil-define-key 'normal key-translation-map (kbd ";") (kbd "l"))


```

**Comment by mmlac-bv** [comment]
I tried this and I get the following error:

    Wrong type argument: symbolp, (evil-define-key (quote normal) key-translation-map (kbd r) (kbd h))

when adding this to the end of  ```(defun dotspacemacs/init ()```

    (evil-define-key 'normal key-translation-map (kbd "r") (kbd "h"))

Any ideas why this is happening?
emacs 24.5.1 on mac, latest spacemacs

**Comment by mmlac-bv** [comment]
@arnm 
I found why the remappings did not work. The keymap param is missing.

http://comments.gmane.org/gmane.emacs.vim-emulation/1275

**Comment by nugend** [comment]
I'm trying to add the following binding:
```emacs
(evil-define-key 'normal evil-org-mode-map
  "C-o" 'org-insert-heading-after-current
  "C-O" 'org-insert-heading
  )
```

Doesn't seem to work. Also tried using `(with-eval-after-load 'org-mode ...)` to make sure it ran after any other bindings were defined. That didn't work either.

**Comment by jason** [comment]
This works under user-configuration. If you're wondering, these are keybindings for the Workman keyboard.

(define-key evil-normal-state-map "h" 'evil-yank)
(define-key evil-normal-state-map "n" 'evil-next-line)
(define-key evil-normal-state-map "e" 'evil-previous-line)
(define-key evil-normal-state-map "o" 'forward-char)


(define-key evil-normal-state-map "k" 'evil-forward-WORD-end)
(define-key evil-normal-state-map "l" 'evil-open-below)
(define-key evil-normal-state-map "L" 'evil-open-above)
(define-key evil-normal-state-map "j" 'evil-search-forward)
(define-key evil-normal-state-map "H" 'evil-yank-line)

**Comment by sampablokuper** [comment]
Before using Spacemacs (i.e. just using Evil), I used the following with some success:

```
;; Modify evil-mode keybindings from hjkl motion to jkl;
(define-key evil-normal-state-map "H" 'evil-join)
(define-key evil-motion-state-map "j" 'evil-backward-char)
(define-key evil-motion-state-map "J" 'evil-window-top)
(define-key evil-motion-state-map "k" 'evil-next-line)
(define-key evil-motion-state-map "l" 'evil-previous-line)
(define-key evil-motion-state-map ";" 'evil-forward-char)
;; (define-key evil-motion-state-map ":" 'evil-window-bottom)
(define-key evil-motion-state-map "h" 'evil-repeat-find-char)
(define-key evil-window-map "j" 'evil-window-left)
(define-key evil-window-map "J" 'evil-window-move-far-left)
(define-key evil-window-map "k" 'evil-window-down)
(define-key evil-window-map "K" 'evil-window-move-very-bottom)
(define-key evil-window-map "l" 'evil-window-up)
(define-key evil-window-map "L" 'evil-window-move-very-top)
(define-key evil-window-map ";" 'evil-window-right)
```

Haven't yet tried it in Spacemacs, but it might help someone.

**Comment by syl20bnr** [comment]
We could leverage the new keyboard-layout layer in develop branch.

**Comment by sampablokuper** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=26659732)](https://www.bountysource.com/issues/26659732-convention-for-remapping-layer-s-key-bindings?utm_source=26659732&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by YayConnolly** [comment]
To make *some* evil-org keybinding overrides, I had to use `with-eval-after-load` and plain `define-key` (not `evil-define-key`):
```
(with-eval-after-load 'evil-org
    (define-key evil-org-mode-map (kbd "<insert-state> M-t") #'my-insert-sub-todo)
    (define-key evil-org-mode-map (kbd "<normal-state> M-t") #'my-insert-sub-todo))
```
Strangely, remapping `T` works without any of that:
```
(evil-define-key 'normal evil-org-mode-map "T" #'my-insert-todo)
```

Which I don't understand, even after a quick look at https://github.com/syl20bnr/spacemacs/blob/a298a5a311dfe8b449b5f538740303f1ab3d5695/layers/org/extensions/evil-org/evil-org.el

Both are in the body of `dotspacemacs/user-config` in my `.spacemacs` file

**Comment by LeMikaelF** [comment]
@arnm This is an old post, but I spent hours trying to get this to work. The solution is:

    (evil-define-key` 'normal global-map (kbd "j") (kbd "h"))

**Comment by LeMikaelF** [comment]
@arnm This is an old post, but I spent hours trying to get this to work. The solution is:

    (evil-define-key` 'normal global-map (kbd "j") (kbd "h"))

(cross-posted from my [answer on Stackoverflow](https://emacs.stackexchange.com/a/51934/18569))

**Comment by duianto** [comment]
@LeMikaelF Thanks for posting a solution.

A note about github comments, you can edit one of your comments or even delete it (for example the duplicate without the stackoverflow link), by clicking on the three dots `...` in the top right corner of your comment. That opens a menu where you can choose an action.

**Comment by LeMikaelF** [comment]
@duianto Oops! Thanks for pointing that out, my mistake.

**Comment by mfierro0** [comment]
@LeMikaelF Thanks for posting! Probably saved me a few hours too :)
