### ISSUE TITLE
clojure: infinite loop when entering a closing parenthesis

### ISSUE THREAD

**Issue by lincoln310** [syl20bnr/spacemacs#3020]
Hi, i used clojure layer, and meet this problem:
i typed in "(map #(conj % 1) #{2 3}". You see, i missed a ")" to close it. And then i pressed "enter", then it looped forever, no response for any input, and i have to kill emacs using system tools.

When i use emacs-live, it auto complete the () {} [], how to implement it in spacemacs?

By the way, the colors of () in cider repl is only white, not 7 colors.

**Comment by geo7** [comment]
`SPC t p` runs the command spacemacs/toggle-smartparens, which will
automatically put `)` after a `(`.

I'm not sure if this is what you're after. You can add a hook to a major mode using 

`(add-hook '<major-mode> '<function>)`

From the docs - 

> It is possible to enable it easily for /all programming modes/ with the variable
> `dotspacemacs-smartparens-strict-mode` of you `~/.spacemacs`.

I'm not sure about the colors of the REPL for cider I've not used it

**Comment by lincoln310** [comment]
Thank you for correct me, and sorry for bad English.  
The smartparens do helped, thank you very much.
But it is still a bug, right? I don't know how to fix it, otherwise i will do it.....

**Comment by TheBB** [comment]
Hi @lincoln310. Nobody has replied here for almost a year and it seems nobody can reproduce this problem. Therefore I'm closing this. Feel free to reopen with more information if this is still an issue.
