### ISSUE TITLE
 Could not apply yapf. Check *yapf Errors* for details

### ISSUE THREAD

**Issue by xuehao** [syl20bnr/spacemacs#3023]
@kennethlove I follow the config tutorial. I install `yapf` using `pip`, but I still cannot solve this problem.
And the `*yapf Errors*` is empty.

**Comment by a-sk** [comment]
It looks like a problem with yapf.
py-yapf does not work with yapf >=0.2.8

**Comment by xuehao** [comment]
Nice!! @a-sk

**Comment by xuehao** [comment]
@a-sk Do you know how to set default Python Interpreter to Python 3 when startup? Not use `pyvenv`

**Comment by a-sk** [comment]
Something like
`(setq python-shell-interpreter "python3")`
in python-mode hook, I guess.

**Comment by a-sk** [comment]
yapf now returns 1 if the source code changed. https://github.com/google/yapf/commit/ffb8d734618ba3a073892a72df436c68258f171d

**Comment by ntcong** [comment]
any update on this ? yapf 0.3.0 now return 2 if source code changed

**Comment by a-sk** [comment]
I created new PR: #3095
