### ISSUE TITLE
How to hide whitespace in buffer

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#3024]
![image](https://cloud.githubusercontent.com/assets/785541/9847988/d6289254-5b0f-11e5-9e0f-999c87fa61ee.png)

I could disable whitespace mode, but it doesn't work.

**Comment by TheBB** [comment]
That's not `whitespace-mode`. Try `(setq show-trailing-whitespace nil)`. To deactivate globally, `(setq spacemacs-show-trailing-whitespace nil)` in `dotspacemacs/config`.

**Comment by geo7** [comment]
Note - to *remove* all trailing whitespace you can enter `SPC x d w`

See [text manipulation](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#text-manipulation-commands) for more along these lines.

**Comment by zilongshanren** [comment]
Thanks,  @TheBB  It works. :+1: 
@geo7  Thanks for the tip.

**Comment by geo7** [comment]
whoop, [you'll be at 400 issues in no time](http://i2.kym-cdn.com/entries/icons/original/000/016/729/large.jpg) @TheBB

**Comment by jordwalke** [comment]
I would recommend another setting to only show trailing whitespace when in normal mode, and not in snippet expansion/population mode. Usually snippets leave temporary white space lying around which you will eventually fill by the time you're done tabbing through the snippets. Only when you're done with the snippet, and you've gone back to normal mode, is it very useful to see the trailing whitespace.
