### ISSUE TITLE
M-RET keybinding in Org-mode when using holy-mode.

### ISSUE THREAD

**Issue by Arbitrageur** [syl20bnr/spacemacs#3027]
Some useful keybinding is defined as M-RET + ? when using holy-mode, i guess. 
But M-RET is defined as enter a new entry.
Maybe I can change the leader key to another like C-c. However, I'm very satisfied with M-RET.
So, is there any solution?

**Comment by syl20bnr** [comment]
You could change the key binding of org instead of the ubiquitous major mode leader.

**Comment by Arbitrageur** [comment]
Oh, you're right. 
But I found some spacemacs keybindings, like 'M-RET :' for org-set-tags.
However, it is not functional. So I'm thinking there's something missing.

Thanks.

**Comment by StreakyCobra** [comment]
`M-RET` is bind to `org-meta-return` in `org-mode` for all Spacemacs modes (vim (insert-state), hybrid (insert-state), emacs).

In vim and hybrid mode, usual `M-RET` menu can be accessed with `,` from the normal state and `C-o ,` from the insert state, and through `M-m m` from all modes. It could be a little bit annoying (especially for users not used to normal state), but it's not really breaking the functionality.

`org-mode` being an important part of emacs, I don't think users will want to change `M-RET` behaviour.

@Arbitrageur Are these alternative keybindings enough for you? If not, can you elaborate on the changes you are expecting?

**Comment by Arbitrageur** [comment]
'M-m m' is good enough. I just missed it. Thanks!
