### ISSUE TITLE
Error when using `spacemacs/helm-yas`

### ISSUE THREAD

**Issue by node-ex** [syl20bnr/spacemacs#3029]
Hello. I have a problem with listing yasnippet snippets with helm (function: spacemacs/helm-yas, shortcut: SPC i s). When I try to use it in c-mode, the following message is displayed:

```
helm-yas-build-cur-snippets-alist: Symbol's function definition is void: yas--template-file
```

But snippet expansion works without a problem (hippie-expand, M-/).

I use Linux Mint 17.2 and `spacemacs` is the only package that I've installed.

What I've already done:

1) deleted everything that is somehow connected to 
    emacs (`apt-get purge emacs; apt-get autoremove`)
    spacemacs (deleted `.emacs.d` and `.spacemacs`)
2) installed emacs from `ubuntu-elisp` ppa (contains newest version of emacs)
    `version output: GNU Emacs 25.0.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.8)`
3) downloaded `spacemacs` using `git`
4) copied `.spacemacs.template` to `~/` and renamed it to `.spacemacs`
5) uncommented `auto-completion`
6) tried to use `spacemacs/helm-yas` in `*scratch*` buffer in `c-mode`

I recieve this error on both Emacs 24.3 and 25.

**Comment by TheBB** [comment]
Actually I just updated my packages and can confirm this. It's a recent update in yasnippet that helm hasn't caught up to yet.

**Comment by mbertheau** [comment]
Can we version-pin yasnippet in develop until helm has caught up?

**Comment by TheBB** [comment]
Reported upstream with fix: https://github.com/emacs-helm/helm-c-yasnippet/pull/13

**Comment by TheBB** [comment]
An easy solution for now is:

```lisp
(defalias 'yas--template-file 'yas--template-load-file)
```

**Comment by node-ex** [comment]
Yes, that alias works, thank you :+1:

**Comment by TheBB** [comment]
@mbertheau You inspired me to do #3034. Let's see what comes of it.

**Comment by TheBB** [comment]
This was finally merged upstream.
