### ISSUE TITLE
Develop - Ranger - `pp` doesn't do what's advertised

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3030]
`pp` after marking files with `dd` just moves the cursor up one line.

https://github.com/ralesi/ranger.el/issues/37

**Comment by ralesi** [comment]
I commented upstream.  If anyone is able to reproduce this, please comment on the referenced issue.

**Comment by synic** [comment]
This has been fixed upstream.  Will reopen if I have the issue again.
