### ISSUE TITLE
Odd ^[[2004h characters with shell and ZSH

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#3035]
The new 5.1.1 release of ZSH adds support for bracketed paste.  This results in the odd effect of printing the bracketed paste control sequences `^[[2004h` and `^[[2004l` when running ZSH in shell mode.

I believe comint already supports the necessary escaping and pasting, so bracketed paste is redundant.

Workaround is to disable bracketed paste when inside Emacs, by adding the following to `.zshrc`:

```shell
if [ -n "$INSIDE_EMACS" ]; then
    export EDITOR=emacsclient
    unset zle_bracketed_paste  # This line
fi
```

This is sort of an upstream bug since ZSH shouldn't be attempting bracketed paste on `TERM=dumb`, but oh well.

**Comment by TheBB** [comment]
So, what do we do here?

**Comment by darkfeline** [comment]
Forgot to close.  I don't think there's anything for Spacemacs to do here unless there are more misbehaving programs that do this on `TERM=dumb`.  I meant to document this in case anyone else ran into it.

**Comment by TheBB** [comment]
Ah, no problem. :+1:

**Comment by douglas-larocca** [comment]
Thanks for mentioning this despite it being an upstream bug. I've been trying to fix this for weeks!
