### ISSUE TITLE
buffer-face-mode might want to be on by default?

### ISSUE THREAD

**Issue by CarlQLange** [syl20bnr/spacemacs#3041]
Allows creating buffer-local faces, which is handy for eg variable-pitch org-mode documents.

Example screenshot from my rpg game:

<img width="1440" alt="screen shot 2015-09-16 at 00 09 13" src="https://cloud.githubusercontent.com/assets/859820/9892488/3ac2f752-5c07-11e5-811e-df62a315410a.png">

Without buffer-face-mode, the help text would also have the variable-pitch font Avenir associated with it.

**Comment by syl20bnr** [comment]
I did not know about this mode. Is there something in Spacemacs that requires this mode ? We need to be sure that performance wise it does not slow down the whole experience.
My first thoughts is that to follow the principle of least astonishment (people expect to have the same font everywhere) we should not enable it but we should document it. Since it is not beginner stuff (user must know about faces) it should be OK to just document it.

**Comment by CarlQLange** [comment]
Yeah, it was news to me also. There's nothing in Spacemacs that requires this mode. The reason I came across it is that by default org-mode headings are in a `variable-pitch` face (ie not monospaced) but the ordinary text is not (under the `default` face). Setting the `default` face to be `variable-pitch` then fucks with things like helm, the mode-line, etc. That's where this mode comes in, changing faces specifically for this buffer.

It could be useful to have a function that changes fonts buffer-locally, but I don't know how much it's wanted. However I do think it's reasonably common to want to change fonts in org-mode buffers (there's a few reddit posts asking about how to do it etc) so maybe just adding a bit in the org-mode layer doc?

Bit more info on the mode:
http://www.emacswiki.org/emacs/FacesPerBuffer

**Comment by StreakyCobra** [comment]
We can let this issue open for a few weeks, waiting to see if anybody else need this kind of functionality. If not, we will probably close it, but PRs will still be welcome :relaxed:

**Comment by CarlQLange** [comment]
Nah, I'd close it - this isn't useful enough for enough people.. But maybe someone should write a post about how to enable it and what it does, because it _is_ a really cool emacs feature.

**Comment by StreakyCobra** [comment]
It seems there is not a lot of people interested in this for now, so I'm closing it. Anyway, PRs are welcome :-)
