### ISSUE TITLE
Latex: When I tried to use C-c C-c for making a pdf file, emacs returned an error. /bin/sh: pdflatex: command not found

### ISSUE THREAD

**Issue by zhexuany** [syl20bnr/spacemacs#3046]
I did  not have any clue. Google did not give me any help. I already tried each method provided in similar problem, but they did not work for me. I wish can get help from you guys.

**Comment by person808** [comment]
Sounds like you need to install `pdflatex`

**Comment by chrisbarrett** [comment]
You need to install LaTeX.

**Comment by zhexuany** [comment]
*I did*.  I already installed *Mactex*. But the default directory of pdftex was not in */usr/bin/sh*. I tried to link these two file but my shell said, there was no such file.

**Comment by mclearc** [comment]
`pdflatex` should be in `/Library/TeX/texbin/`. Symlink it from there.

**Comment by zhexuany** [comment]
@mclearc  link which file? /usr/bin or /usr/bin/sh

**Comment by mclearc** [comment]
@zhexuany Sorry -- probably neither. I should have read your OP more closely. Are you sure that `pdflatex` is in your `PATH`? Try `echo $PATH` and make sure that you see `/Library/TeX/texbin` somewhere in there.

**Comment by zhexuany** [comment]
I am pretty sure my pdflatex is in /usr/texbin. And I already symlinked /usr/bin and /usr/texbin. But, when I tried to run getenv in my spacemacs, it returned /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by mclearc** [comment]
The standard install for MacTex installs in `/Library/TeX/texbin`. But you can just run `which pdflatex` from  your terminal to find out for sure. Whatever directory you find out it is in, make sure it is in your `PATH`. Run `export PATH=$PATH:/path/to/your/texbin` from terminal.

**Comment by zhexuany** [comment]
@mclearc It still did not work out. When I run genet path in my spacemacs, the path is /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin. However, when I run env in my terminal, the path is ATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin. It is so wired.

**Comment by mclearc** [comment]
Have your tried adding it to your `exec` path in the `dotspacemacs/init` section of your `.spacemacs` file? Something like:

`````lisp
(add-to-list 'exec-path "/usr/texbin")
``````

**Comment by zhexuany** [comment]
@ mclearc I did. That is why I feel so upset. I tired everything from Google. It just did not work for my case.

**Comment by mclearc** [comment]
It's strange that you emacs config isn't loading your `PATH` correctly from the shell. It should be using  [this function](https://github.com/syl20bnr/spacemacs/blob/93e3b883c061c1fd685e9ef588b979704ca95c78/spacemacs/packages.el#L1032-L1035). You could try putting it in manually. Another option is just to nuke and reinstall spacemacs. You should be on the `develop` branch if you're not already. Sorry I can't help more!

**Comment by mclearc** [comment]
Oh - one last thing to try. Have you tried opening emacs from your terminal? Is the `PATH` still showing up wrong there?

**Comment by zhexuany** [comment]
Just tried open emacs from terminal, PATH is still wrong. When I run env from terminal, however, the PATH is now PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin. I came out of an idea: I gonna edit my ~/.zshrc file and try these things again.

**Comment by zhexuany** [comment]
It worked now. Thank for you guys.

**Comment by hoosierEE** [comment]
@zhexuany what did you change between your last 2 comments?  I am experiencing the same issue - spacemacs' PDF message buffer says `/bin/bash: pdflatex: command not found` but `which pdflatex` shows it is on my path.
