### ISSUE TITLE
Remove tromey archive

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#3049]
We need to handle `asciidoc` layer which uses a package in tromey. We can either try to use Quelpa or submit a reicipe to MELPA or use an alternative package like `adoc-mode` which is already available on MELPA.

**Comment by syl20bnr** [comment]
Related topic: https://github.com/syl20bnr/spacemacs/issues/209

**Comment by justbur** [comment]
I'm confused. It looks like the asciidoc layer already uses `adoc-mode`

**Comment by syl20bnr** [comment]
Perfect then :-D

**Comment by justbur** [comment]
I think it's safe to do. I just tried installing all the layers without the tromey repository. If someone needs it for a specific layer or in their personal config, they can add it back, right?
