### ISSUE TITLE
Is it possible to override load-path for packages installed from layers?

### ISSUE THREAD

**Issue by usharf** [syl20bnr/spacemacs#3051]
Is it possible to make layers load packages from alternative directories (i.e. a checked-out version of a packages which was already installed via a contribed layer)? Do I need to manipulate the load-path and if so, where's the best place  to do it. Again, the idea is that once the package version in MELPA is updated, I can simply remove the localy sourced path to that package from my configuration.

**Comment by TheBB** [comment]
We're working on a way to do this in #3034.

**Comment by usharf** [comment]
Ok, didn't see that issue. Thanks!
