### ISSUE TITLE
neotree is broken with new updates

### ISSUE THREAD

**Issue by svalaskevicius** [syl20bnr/spacemacs#3053]
when I update my packages in spacemacs, and then try to open any from from the neotree (or just switch to another file from it), the cursor starts jumping between neotree and and the file and I cannot do anything in emacs (even to exit it I have to kill the process).

(rolled back all packages for now and it seems working again, but this means I cannot update it anymore..)

**Comment by svalaskevicius** [comment]
my spacemacs config: https://github.com/svalaskevicius/dotfiles/blob/users/svalaskevicius-osx/rc/spacemacs (if useful to replicate)

**Comment by synic** [comment]
Are you on master?

**Comment by svalaskevicius** [comment]
yes, on v0.103.6

**Comment by robbyoconnor** [comment]
I am on `develop` and neotree works just fine. Try `develop`?

**Comment by robbyoconnor** [comment]
Also 0.104 will be released any day now -- so it should also work for you.

**Comment by svalaskevicius** [comment]
just checked develop, works fine :)

thanks!

**Comment by robbyoconnor** [comment]
Great :+1:
