### ISSUE TITLE
develop - django layer - django template syntax highlighting doesn't work

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3058]
Open a django template html file just activates web-mode.

**Comment by mbertheau** [comment]
@synic Which mode should be activated? And does that happen with certain packages/configuration on a non-spacemacs emacs? Or is this more of a feature request?

**Comment by TheBB** [comment]
But web-mode supports django templates. Here's one of mine…

![Django](http://i.imgur.com/ducsCd2.png)

**Comment by synic** [comment]
Yeah, mine definitely doesn't look like that.  It doesn't know they are django templates

**Comment by TheBB** [comment]
Maybe you need to configure `web-mode-engine-file-regexps` if you have a nonstandard file extension.

**Comment by synic** [comment]
It's just .html.  Does it need to be something else?

**Comment by TheBB** [comment]
Yes, like I said, check `web-mode-engine-file-regexps`. The regexp for django files is

```
\.\(djhtml\|tmpl\|dtl\|liquid\|j2\)\'
```

Anything matching this should be interpreted as a django HTML file. If you don't want to change the names of your files, you should change this regexp.

**Comment by TheBB** [comment]
You can also call `SPC : web-mode-set-engine` manually.

**Comment by synic** [comment]
Hrmm, perhaps this is part of the problem.

This is my configuration layers:

```elisp
   dotspacemacs-configuration-layers
   '(
     xkcd
     auto-completion
     evernote
     emacs-lisp
     git
     yaml
     github
     javascript
     csharp
     dash
     html
     markdown
     extra-langs
     python
     ruby
     org
     osx
     python
     django
     syntax-checking
     spell-checking
     version-control
     evil-snipe
     lua
     colors
     (ranger :variables
             ranger-show-dotfiles nil
             ranger-preview-file nil)
     perspectives
     (c-c++ :variables
            c-c++-enable-clang-support t)
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     )
```

`web-mode` should be installed. I can see it in the elpa directory.  However, I have no `web-mode-set-engine` command.  In fact, if I `SPC :` and type web-mode, this is what I see:

http://d.pr/i/YqaR/2rPF5X3O

This seems to be the second layer that I have installed that is missing functions, almost as if the layers aren't getting initialized properly.

**Comment by TheBB** [comment]
Are you sure web-mode is loaded when you do that? It won't be loaded until needed. Make sure you open a file in web-mode, then try it.

**Comment by TheBB** [comment]
Here's what I see. Before loading:

![](http://i.imgur.com/QAoIstI.png)

After loading:

![](http://i.imgur.com/1LQoLDg.png)

**Comment by synic** [comment]
You are correct.  It wasn't loaded.  Seems to be working great now, thank you!
