### ISSUE TITLE
question - develop - how to hide changelog on startup?

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3059]
How do you hide the changelog on startup in develop?

**Comment by person808** [comment]
Click the `[Release Notes]` button. It should persist until you click the button again.

**Comment by synic** [comment]
Awesome, thank you.

**Comment by syl20bnr** [comment]
@synic it will show up again when you update Spacemacs and the version number changed.

**Comment by diego-alvarez-hs** [comment]
:+1:
