### ISSUE TITLE
develop - perspective-enable-persp-projectile errors

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3060]
With the following in my `dotspacemacs-configuration-layers`:

```elisp
     (perspectives :variables
                   perspective-enable-persp-projectile t)
```

When I open a project from `SPC p p`, a new perspective is not created.  Instead I see this error in `*Messages*`:

```
spacemacs/persp-switch-project: Wrong type argument: arrayp, nil
```

**Comment by robbyoconnor** [comment]
This is fixed in #2845

**Comment by synic** [comment]
That sounds like it won't be in until at least the release after this one.  

Meaning that it'll be broken in the next release - perhaps that feature should be removed until It's fixed?

**Comment by robbyoconnor** [comment]
Nah leave it be...it's not exactly going to break shit...why bother...it
does work sometimes.

--Rob

**Comment by synic** [comment]
My concern is that broken features, especially if they are discoverable and
advertised, put a bad taste in people's mouths, especially new users.

If I were to start using spacemacs today and ended up coming across more
than a few broken features in the first few hours, I'd probably just move
on.

**Comment by robbyoconnor** [comment]
That is a concern, but this isn't exactly a deal breaker...it's a rapidly
moving project which hasn't even reached 1.0 yet.

--Rob

**Comment by robbyoconnor** [comment]
In addition, the fixes in #2845 are worth the wait!

--Rob

**Comment by synic** [comment]
I'm reopening, since it is still a problem.  If the perspectives branch isn't going to get merged, we should maybe come up with another solution.

**Comment by StreakyCobra** [comment]
@synic #2845 having been merged 2 days ago (:tada:) does it solves you issue? If yes I can label this issue as Fixed in develop :smile:

**Comment by synic** [comment]
Yeah, new perspectives is awesome!  Only had a problem on first launch, but I love it.  Especially the automatic loading part.  Good work @CestDiego

**Comment by CestDiego** [comment]
@StreakyCobra you might want to label this as fixed in develop as well?

**Comment by StreakyCobra** [comment]
@CestDiego As it's closed there is no need for marking it `Fixed in develop` :-) Theses labels are even removed when issues are closed.

**Comment by nixmaniack** [comment]
Why not `Fixed in develop`?  People using `master` might browse through this issue and come across issues like this which are only Fixed in develop. The idea of this label is to have this separation and close only when it's released/merged in `master`.

**Comment by robbyoconnor** [comment]
@StreakyCobra, @syl20bnr , @TheBB --  opinions on :point_up:

**Comment by TheBB** [comment]
Typically I mark these kinds of issues fixed in develop, but if the reporter wants to close it instead that's up to him.

**Comment by StreakyCobra** [comment]
@nixmaniack @robbyoconnor Before answering @CestDiego I asked @TheBB on gitter about this because I was also unsure :smile:

**Comment by nixmaniack** [comment]
I would still say, even if the user closes it, have the label as it clearly states it's not yet in master for users bumping in such issues.

**Comment by StreakyCobra** [comment]
@nixmaniack Make sense

**Comment by syl20bnr** [comment]
@nixmaniack and @TheBB are right. Any fix in develop should have the Fixed in develop tag and the issue should remain opened but if the OP closes it that's fine, the important tag is still here. If the issue is also in current release then we add Fixed in current release instead. When a new release comes out we clean those tags.
