### ISSUE TITLE
move org-mime package initialization to org layer

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#3062]
now it is in the gnus layer where it also [binds a key](https://github.com/katshinka/spacemacs/blob/develop/layers/%2Bemail/gnus/packages.el#L99). This is a position where developers that are not aware of it can not see the keybinding. 

I'll do that when nobody else gets to it first.

**Comment by robbyoconnor** [comment]
Actually I will do this :)

**Comment by robbyoconnor** [comment]
@cpaulik -- I think this should be closed -- there is no sane DRY way to do this beyond the way it is done.

**Comment by cpaulik** [comment]
I'll wait for closing it until it is merged.
