### ISSUE TITLE
Add `goimports` support to go layer

### ISSUE THREAD

**Issue by vise890** [syl20bnr/spacemacs#3065]
Goimports adds required imports and removes unneeded ones on file save (and gofmts the buffer). It is a drop-in replacement fro `gofmt` with this extra functionality. I find it extremely convenient.

Any thoughts on adding it to the `go` layer?

The go layer already has a bunch of dependencies on external tools, so adding another one shouldn't be much of a hassle?

**Comment by ntcong** [comment]
It can be easily added with `(setq gofmt-command "goimports")`. Personally I think gofmt is good enough for a baseline configuration, there's no need to add goimports.

Adding a guide in go layer's documentation is more than enough.

**Comment by codygman** [comment]
@ntcong Perhaps the best option would be to let the user have a configuration option, then apply your ```(setq gofmt-command "goimports")``` recommendation if the user wants to use goimports.

> Personally I think gofmt is good enough for a baseline configuration, there's no need to add goimports.

Is spacemacs about providing a baseline configuration to customize, or something featureful out of the box? My impression is that Spacemacs is more about the latter while trying it's best not to sacrifice speed or customization ability.

**Comment by ntcong** [comment]
in order to know the configuration variable, the user will have to read the README, it is just 1 line of command, so configuration variable or a documented user-config is no different.

Adding a new configuration pollutes the layer, and doesn't offer anything better, so I'm against this.

**Comment by codygman** [comment]
This is my opinion:

From a user perspective a user config is much less opaque. The one line command requires more indepth knowledge of spacemacs/emacs whereas the configuration option will let any user think "yes, I want to add goimports support" and follow typical spacemacs layer configuration style.
