### ISSUE TITLE
org-repo-todo creates inaccessible capture templates and other issues

### ISSUE THREAD

**Issue by gleber** [syl20bnr/spacemacs#3066]
As in waymondo/org-repo-todo#5

Additionally `ort/capture-todo-check` is not defined in `org-repo-todo` but used in `spacemacs/contrib/org/packages.el`. Was it meant to be ` ort/capture-todo-checkitem`?

**Comment by TheBB** [comment]
Looks like it. I will push a fix for the function name.

**Comment by fladd** [comment]
This is still broken in the current Spacemacs version. Once you use `SPC C t` or `SPC C T`, capturing in org is not possible at all anymore!

**Comment by syl20bnr** [comment]
`org-repo-todo` has been replaced by `org-projectile`.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
