### ISSUE TITLE
evil-matchit hang (easy to repro)

### ISSUE THREAD

**Issue by agriffis** [syl20bnr/spacemacs#3068]
Too easy to hang evil-matchit (100% CPU uninterruptible) with an unclosed paren. This happens in more complex code easily, but here's the one-character reproducer `paren.py`
```python
(
```
Position point after the paren and hit `%`... After a while, head off to another terminal to `pkill emacs`

**Comment by agriffis** [comment]
This is on develop at 9daac9b306d9b83ff65eab8712a8659cbf304112

**Comment by TheBB** [comment]
Yeah, I can reproduce it. Although `C-g` is more elegant than killing Emacs (with the bonus that it doesn't kill your Emacs).

Ping @robbyoconnor.

**Comment by agriffis** [comment]
`C-g` didn't work for me.

**Comment by syl20bnr** [comment]
This is why I did not want evil-matchit in the first place. It's my fault, I did not review the PR for evil-matchit to see if this behavior was corrected. We can disable back evil-matchit in the modes where it has issues.

**Comment by syl20bnr** [comment]
I opened a bug long time ago here https://github.com/redguardtoo/evil-matchit/issues/18
Said it was fixed and it was not when I had the chance to test it, so I stopped using it (this was before spacemacs was popular).

**Comment by syl20bnr** [comment]
I opened a new issue upstream: https://github.com/redguardtoo/evil-matchit/issues/58
Should have done that a long time ago but I never grasped the usefulness of evil-matchit (I was biased by the fact that I did a lot python at this time).

**Comment by robbyoconnor** [comment]
Shit...sorry -- it's been working fine for me -- I been using it in ruby for a while now with no hitches!

**Comment by robbyoconnor** [comment]
Kill the python commit -- Leave ruby please @syl20bnr

**Comment by robbyoconnor** [comment]
I was never convinced that python was worth it. It works amazingly for Ruby though

**Comment by TheBB** [comment]
Well, let's hear with @redguardtoo has to say first. I've known him to be pretty quick to respond to bug reports.

**Comment by robbyoconnor** [comment]
I was gonna do a PR to kill it...but I'll wait.

**Comment by robbyoconnor** [comment]
Opened a PR anyways...didn't remove it completely.

--Rob

**Comment by redguardtoo** [comment]
fixed in 2.1.1

**Comment by robbyoconnor** [comment]
I can't for the life of me get cycling through conditional statements to work and I stopped caring...matchit.vim works just fine.

**Comment by robbyoconnor** [comment]
Figured it out :heart: See #3089 @syl20bnr

**Comment by robbyoconnor** [comment]
I have checked and this bug is now fixed: redguardtoo/evil-matchit#58

**Comment by agriffis** [comment]
I'll let @TheBB or @syl20bnr close this out when they're ready. I don't personally care about matchit except that it froze my emacs, so I'm not going to bother reenabling/testing.

**Comment by robbyoconnor** [comment]
@agriffis, shame -- it actually works really well now :)

**Comment by robbyoconnor** [comment]
@syl20bnr, @TheBB: this is fixed, I tried it. Soon as #3089 is merged, and 0.104 is released, this should probably be closed.
