### ISSUE TITLE
Explicitly set projectile-indexing-method to alien

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#307]
The indexing method on other OSes except Windows is `'alien`, while on Windows it's `'native`. 

`'native` uses Emacs Lisp to retrieve the file list.

`'alien` uses external tools (like `git`) to retrieve the file list.

Emacs Lisp engine on Windows is much slower compare with Linux (on Linux, it took me 10 seconds to load start my Emacs while it took me 80 seconds to start Windows). Using `'native` indexing method took forever on non-trivial projects while it took 6 seconds to get the file list using `'alien` method for a Git repo with 30k-40k files.

I think Spacemacs should explicitly set `projectile-indexing-method` to `'alien`:

```lisp
(setq projectile-indexing-method 'alien)
```

**Comment by syl20bnr** [comment]
The method is now set to alien in develop :-)
