### ISSUE TITLE
use-package hooks are not executed when there is no :init or :config blocks

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#3070]
Reported upstream: https://github.com/jwiegley/use-package/issues/250

**Comment by darkfeline** [comment]
Does Spacemacs have a policy for adding code to fix upstream bugs?

For example, adding advice before `use-package` to insert empty `:init` and `:config` if they are missing.

**Comment by TheBB** [comment]
We're not above advising functions from upstream but it should be done with care, especially in this case I think.

**Comment by StreakyCobra** [comment]
![xkcd](https://imgs.xkcd.com/comics/workflow.png)

Maybe there are people relying of the fact that a `post-config` block is not executed if there is no `config` block.

**Comment by syl20bnr** [comment]
Actually this makes sense that hooks are not executed if there is no `:init`. We forgot that we can just use multiple `:init` too.

"post hooks" are more useful for `:config` because of lazy loading.

**Comment by syl20bnr** [comment]
I think we can close this one, any objection ?

**Comment by darkfeline** [comment]
Objection.  The user needs a way to be able to configure packages before and after Spacemacs, for both `:init` and `:config` (lazy loading).  Furthermore, these should run regardless of whether or not said blocks are used by the relevant layer.

The implementation doesn't matter (whether we use `use-package` to do this or we roll our own), but Spacemacs should present this feature.

**Comment by syl20bnr** [comment]
If we want to users to be able to use blindly use-package hooks in every occasion then it is impossible to do.

Unfortunately the user must introspect the package configuration to know how it is configured and how lazy loading is implemented for this package. For instance use-package may not be used. This is even more mission impossible because the way the package is implemented can influence the choice of init time (some packages using macros require settings to be defined before the package is required for instance). I could go on and on.

Two possibilities for us:
- always add `:init` and `:config` but I don't like it
- open an issue upstream to know their point of view on the subject. It might be accepted because use-package hooks feature must be explicitly enabled via a variable.

**Comment by TheBB** [comment]
There is an issue open upstream but I couldn't get a clear answer from John Wiegley on whether he considers it a bug, and frankly I don't think he has the time to really care about it now that he's the lead Emacs maintainer.

Personally I think it's a bug from the perspective of use-package, but you're right that it's not so critical from our PoV since we don't always use use-package anyway.

**Comment by syl20bnr** [comment]
We can change our strategy by sending a PR then. Anyone wants to do it ?

**Comment by TheBB** [comment]
I had a look at the use-package source code once to try to fix it but it's not very easy to understand. I can have another go.

**Comment by darkfeline** [comment]
@syl20bnr I think at the very least the user should have the option to hook the following without worrying about implementation:

1. Running code after Spacemacs's package initialization code.
2. Running code after Spacemacs's package loading code.

In the event that a package isn't lazily loaded, 2. happens directly after 1., but the user shouldn't need to worry about that.

I understand that for the respective `pre-` hooks, one could argue introspection is needed to understand their effects on Spacemacs's code.

**Comment by syl20bnr** [comment]
I don't see how it is possible, there is no silver bullet for this, any construct has a potential risk failure, be it no construct, `with-eval-after-load`, `pre-init`, `post-init` layer functions or `use-package` hooks.

**Comment by darkfeline** [comment]
Could you give me an example of failure using `with-eval-after-load`?

**Comment by syl20bnr** [comment]
- Some packages need a setting to be set before requiring the package. 
- A key binding for an autoload function.

**Comment by darkfeline** [comment]
Sorry, I retract my objection.

If I'm not mistaken, ignoring `use-package` for the moment, Spacemacs does provide the following methods for users to run their configuration:

1. `user-init` and `pre-init-foo` will run before all Spacemacs code (possibly depending on layer order).
2. `user-config` and `post-init-foo` will run after all Spacemacs code (possibly depending on layer order).
3. `with-eval-after-load` in `user-init` and `pre-init-foo` will run before all Spacemacs `eval-after-load` stuff, including `use-package`'s `:config`.  (`eval-after-load` works in a FIFO manner.)
3. `with-eval-after-load` in `user-config` and `post-init-foo` will run after all Spacemacs `eval-after-load` stuff, including `use-package`'s `:config`.

This covers the four points where a user should be able to add configuration code.

**Comment by syl20bnr** [comment]
It should cover most of the cases. In all the different cases `with-eval-after-load` is the most likely to what the user wants, not sure if we mentioned it clearly in the docs.

But I would like to have the feature mentioned here where use-package hooks are guaranteed to be executed. Especially because use-package hooks are an opt-in setting.

**Comment by ohspite** [comment]
Having this fixed or at least having the issue mentioned in the LAYERS documentation would have saved me quite a bit of time today.  I say that without any complaint--I'm just saying that it might save other people quite a bit of time as well.  Seems like it might be a common issue to run into if you're setting up your own layers.

**Comment by TheBB** [comment]
Fixed upstream! :tada:
