### ISSUE TITLE
cannot use YASnippet in Python mode

### ISSUE THREAD

**Issue by xuehao** [syl20bnr/spacemacs#3077]
How to use `Tab` to complete Python snippet in Spacemacs?

**Comment by cpaulik** [comment]
Snippet completion is not bound to `tab` by default. You can try `M-/` or `SPC i s`. If you want to show snippets in the autocompletion popup then you can configure this in the auto-completion layer, see [here](https://github.com/syl20bnr/spacemacs/tree/master/contrib/auto-completion#show-snippets-in-auto-completion-popup).
But this does only work on the `develop` branch at the moment.
