### ISSUE TITLE
holy-mode | Unable to use C-n in magit modes 

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#3078]
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.0
- Spacemacs branch: develop (rev. ff2ff60)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t)
 better-defaults emacs-lisp
 (git :variables git-gutter-use-fringe t git-magit-status-fullscreen t)
 github markdown yaml shell spell-checking syntax-checking erc python ruby ruby-on-rails django clojure go gtags shell-scripts html javascript dash
 (eyebrowse :variables eyebrowse-display-help nil)
 colors deft finance
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 restclient themes-megapack version-control ansible emoji cscope ranger prodigy  bh-org-mode gnus)
```
`C-n` isn't working in `magit-status-mode` or `magit-stash-mode` while using `holy-mode`.

It is bound to `(magit-section-forward--evilified-magit-mode-map-C-n)`
whereas `C-p` is bound to `(previous-line &optional ARG TRY-VSCROLL)`

I could use `n` and `p` which are bound to `(magit-section-forward-or-evil-search-next--evilified-magit-mode-map-n)` and `(magit-section-backward)` respectively but using `C-n` and `C-p` is just natural in `holy-mode`.

Also, `C-f` executes `(magit-gitflow-popup &optional ARG)` while `C-b` works fine which is bound to `(backward-char &optional N)`

**Comment by justbur** [comment]
this is bizarre. @nixmaniack what does `C-h v evil-state` say in this case?

**Comment by nixmaniack** [comment]
@justbur Its value is emacs

**Comment by justbur** [comment]
@nixmaniack #3140 fixes this problem. @syl20bnr said he would look at it tonight.

**Comment by syl20bnr** [comment]
Should be fixed in develop, thank you @justbur
