### ISSUE TITLE
Spacemacs freezes between "is ready" and "is up to date" 

### ISSUE THREAD

**Issue by user471** [syl20bnr/spacemacs#3079]
There is a freezing for 7 seconds between "is ready" and "is up to date"
![spacemacs](https://cloud.githubusercontent.com/assets/5988253/9976417/ff8856cc-5eeb-11e5-8824-2cc4ca18be7d.gif)
0.103.6 windows 8.1 emacs 24.5.1
Also I tried develop version and two emacs version http://sourceforge.net/projects/emacsbinw64/ and https://ftp.gnu.org/gnu/emacs/windows/
Is there any way to fix it?

**Comment by user471** [comment]
I enabled dotspacemacs-verbose-loading and got this
```
Spacemacs is ready.
Configuring package helm... [2 times]
ad-handle-definition: `tramp-read-passwd' got redefined
Configuring package helm...done (4.858s) [2 times]
Spacemacs is up to date.
```
I guess "Configuring package helm...done (4.672s) [2 times]" could be the problem.
Does helm configuration suppose to freeze the UI?

**Comment by robbyoconnor** [comment]
@user471 -- [2 times] just means you scrolled and hit that line twice...not that it ran twice.

**Comment by user471** [comment]
@robbyoconnor No, it isn't about [2 times]. There is only ```Configuring package helm...``` between "is ready" and "is up to date" so I think it freezes the spacemacs UI. Other packages don't cause such problem. Maybe there is something wrong with helm.

**Comment by syl20bnr** [comment]
Spacemacs cannot do anything about helm being long to load on Windows. To mitigate this I will add a new variable to specifiy a speed profile for a machine, for slow machines we will force the loading of helm at load time. We won't defer it since it is too much noticable while spacemacs is actually running.
