### ISSUE TITLE
Run `load-auctex-on-demand` automatically

### ISSUE THREAD

**Issue by bjarkevad** [syl20bnr/spacemacs#309]
When using the `auctex` contrib layer, it's necessary to run `load-auctex-on-demand` (currently bound to <kbd>SPC e l</kbd>) manually before entering any LaTeX files. It would be more convenient if this was done automatically.

**Comment by syl20bnr** [comment]
Fixed by https://github.com/syl20bnr/spacemacs/commit/c09641ba9604efbf593e296a6b46ab705c43489d
