### ISSUE TITLE
Spacemacs freezes and must be killed if helm-filtered-bookmarks is called just after loading

### ISSUE THREAD

**Issue by lbgaml** [syl20bnr/spacemacs#3090]
This happens on a mac, using emacsmacport. All plugins up to date as well as spacemacs itself. I am following origin/develop but it happens in head also.

I thought this was limited to just before loading completes, but after some experimentation I have found I actually have to issue another command (like cursor movement), otherwise it will freeze upon < spc >hb.

**Comment by StreakyCobra** [comment]
Hi, is this bug still appearing with your installation on the latest `develop` version? If yes can you paste the output of `SPC h d s`?

**Comment by etergo** [comment]
Yes, it still happens with the latest version of develop. SPC h d s returns the result "Not enough arguments for a format string."

**Comment by StreakyCobra** [comment]
What version of emacs do you have?

**Comment by etergo** [comment]
24.5.1 emacsmacport via homebrew

**Comment by d12frosted** [comment]
Can't reproduce on `OS X 10.11.1 (15B42)`, `emacs-24.5-z-mac-5.13` and develop branch of Spacemacs. Both `SPC h b` and `SPC h d s` work. 

@etergo are you sure that you are running `24.5.1`?

**Comment by StreakyCobra** [comment]
@etergo `M-x version RET` will give you the version from within emacs, just to be sure :-)

**Comment by etergo** [comment]
Yes, the version information is what emacs reports. I am running OS X 10.10.4. Perhaps that's the key.

**Comment by etergo** [comment]
Okay, I've figured out what the problem is. I wanted to have a straight powerline separator, so I used the following code:

(setq powerline-default-separator 'nil)

Once I disabled this code emacs no longer freezes when I call helm-bookmarks on startup, but freezes when I re-enable it.

**Comment by StreakyCobra** [comment]
@etergo Does changing your configuration from `'nil` to `nil` helps?

**Comment by toctan** [comment]
Same here. With `powerline-default-separator` set to `nil`, spacemacs hangs at `describe-function`, `describe-variables` or something like that. @milkypostman Would you have a look at this? Thanks.

**Comment by milkypostman** [comment]
why would you set it to nil? it kinda makes sense it would cause an error, not sure why it'd hang.

**Comment by milkypostman** [comment]
So I tried this on the source (not compiled) and it didn't hang. It just showed no separator...  

I just tried installing powerline from MELPA and didn't have an issue setting `powerline-default-separator` to `nil`. Sorry, I don't think powerline is the issue?

**Comment by TheBB** [comment]
I can't reproduce this problem with `powerline-default-separator` as `nil`, either. Although I will have a look through the Spaceline source code and see if I make any assumptions about it.

**Comment by olivierverdier** [comment]
I can reproduce the problem with 100% reliability by

* using the stock spacemacs config file from version 105.9
* setting the font size to 17
* have the sole line   `(setq powerline-default-separator nil)` in `user-config`

It is a combination of the font size, and setting `powerline-default-separator` which causes the problem.

**Comment by StreakyCobra** [comment]
There may be a platform problem also, as (all?) people having this are on OS X.

**Comment by olivierverdier** [comment]
I think it also has to do with the `:powerline-scale` argument set to 1.1. If I set it to 1, the problem disappears. The problem also disappears with other fonts. For instance, with `Menlo` instead of the standard font (and with scaling 1.1), the problem disappears as well.

**Comment by yilihong** [comment]
any updates?
