### ISSUE TITLE
Deft configuration and file extensions

### ISSUE THREAD

**Issue by mclearc** [syl20bnr/spacemacs#3092]
Currently the Deft layer is set to recognize and write only `txt` using `deft-extension "txt"`. However `deft-extension` is deprecated in favor of `deft-extensions '("txt" "md" "org" "whatever")`. It would be nice to have this reflected in the `deft/packages.el` file. Otherwise using `(setq deft-extensions '("txt" "tex" "org")` doesn't work as expected when put in the user's config file (in `.spacemacs`).

**Comment by robbyoconnor** [comment]
Why not fix it and update the code. This is community-driven...I've been updating the evil-matchit code lately and just tonight got it actually work to the point where I see the value :D -- so yeah..moral: get your hands dirty :P

**Comment by mclearc** [comment]
No problem -- :+1:  Just wanted to check if there was a reason against doing it. So I'll send a pull request when ready.

**Comment by robbyoconnor** [comment]
I mean no harm in making a PR -- worst case...it needs to be refactored or it's rejected...check your ego at the door and all will be cool :)

**Comment by robbyoconnor** [comment]
Just remember: do it against `develop` and you won't incur my wrath :stuck_out_tongue_winking_eye:

**Comment by mclearc** [comment]
Sounds good - will do!
