### ISSUE TITLE
Setting org-refile-use-outline-path to 'file in org-mode, prevent any refiling other than main tree level

### ISSUE THREAD

**Issue by Mayeu** [syl20bnr/spacemacs#3094]
Hello,

I have configured my org-mode to also refile on the main tree level ([following this example](https://stackoverflow.com/questions/21334817/emacs-org-mode-refile-to-main-tree-and-not-as-a-subtree)].

But now I only see filename in my completion list when refilling, and I can't refile to subtree anymore.

Here are my related config in my org configuration layer:
```elisp
 ;; Setup the org folder
(setq org-directory "~/org")
(setq org-agenda-files (list "~/org/"))

 ; Refile on top of file max
(setq org-refile-use-outline-path 'file)
; use a depth level of 6 max
(setq org-refile-targets
      '((org-agenda-files . (:maxlevel . 4))))
```

If I remove the `org-refile-use-outline-path` option I'm able to refile on subtree level again. (but not anymore on main tree, which is something I want :) )

What can I provide/activate to help fixing this? (Emacs noob here :) )

OS: NixOS 15.09
GNU Emacs 24.5.2
Spacemacs v.0.103.6

**Comment by Mayeu** [comment]
So it seems it was not a bug but a feature... Apparently I had to setup:
```elisp
(setq org-outline-path-complete-in-steps nil)
```
Which basically list everything instead of stepping through each level gradually. While I'm fine with that, it is not as fast as the previous configuration.

Any clue if this is the expected behavior or if something is actually wrong here?

**Comment by TheBB** [comment]
I have no idea, sorry! But since this is fixed on your side with some simple configuration, and nobody has answered in a week, I'm going to close this. Thanks for letting us know the fix, though. :-)

**Comment by Mayeu** [comment]
Did not find new info on this myself in the mean time. At least it works, even if not exactly like I want :)

**Comment by sathlan** [comment]
Hi there,

I do not want to re-open this, just pointing out the solution for this problem.

To have:
```elisp
(setq org-refile-use-outline-path 'file)
```
works with helm, you have to add

```elisp
(setq org-outline-path-complete-in-steps nil)
```

Have a good day.
