### ISSUE TITLE
Show file before initialization

### ISSUE THREAD

**Issue by user471** [syl20bnr/spacemacs#3096]
Right now I need to wait 15 seconds before I can start working with file. At the same time gvim opens files immediately. Is it possible to open file in some basic edit mode so I can start working with it and then start initialization in parallel process?

**Comment by syl20bnr** [comment]
Are you on Windows ?

**Comment by user471** [comment]
Yes. 0.104 windows 8.1 emacs 24.5.1
Does Spacemacs have different behavior on Linux?

**Comment by syl20bnr** [comment]
The loading is slower on Windows except if you have a "high-end" PC with SSDs.
There is not much we can do about it but in a future version of Emacs (25.1 I believe), emacs server will be supported on Windows which means you launch an Emacs instance as a service and then you launch clients, the startup is instantaneous. I don't know when Emacs 25.1 will be released but you can try it here: http://emacsbinw64.sourceforge.net/ (use a snapshot)
There is no guarantee that Spacemacs will work with it but some users are using Emacs 25 with Spacemacs.

**Comment by user471** [comment]
> "high-end" PC with SSDs
I guess it isn't enough. I have SSD, AMD FX 8350 and 8 Gb memory.
>There is no guarantee that Spacemacs will work with it
Is there any plans to support it?

**Comment by syl20bnr** [comment]
This is not normal then, Emacs loads in about than 2 seconds on my best PC with SSD. There must be something that prevent helm from loading effectively, maybe check https://github.com/syl20bnr/spacemacs/issues/2705

The plan is to support Emacs 25 when it is released.
