### ISSUE TITLE
Racket mode: run.rkt process isn't killed automatically after closing emacs

### ISSUE THREAD

**Issue by zmnp** [syl20bnr/spacemacs#3097]
When I'm closing spacemacs with opened racket file and racket repl spacemacs asks this:
"Please answer y or n. Active processes exist; kill them and exit anyway? (y or n)"
I press "y" and spacemacs closes. But run.rkt process is still running. 
I waited several minutes but it's still there in memory.
Is it a bug or maybe I improperly configured racket mode?
Maybe someone else has this issue?

**Comment by mbertheau** [comment]
Maybe better report this upstream: https://github.com/greghendershott/racket-mode

**Comment by zmnp** [comment]
https://github.com/greghendershott/racket-mode/issues/158
