### ISSUE TITLE
Consistent eval functions in Vim style

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#3103]
To be consistent with the eval functions behavior in elisp we have to advice the eval functions of other lisp modes to be able to eval the expressions when the point is on their closing parens in Vim style
- [ ] clojure

**Comment by vkz** [comment]
this also makes behaviour of `expand-region` inconsistent:
```clojure
(println "hello world")
```
with point on last `)` invoking `er/expand-region` it will initially select `"hello-world"`. Not sure what's the right approach here.

**Comment by emidln** [comment]
I started working some on this last week. I'd like to introduce an evil operator motion for eval that is generic and can be hooked into with whatever mode's particular eval-region or send-region. This gives us a nice way to compose generic sexp-based evaluation functions around standard emacs, evil, and smartparens functionaltiy that will apply equally to scheme, elisp, common lisp, clojure, hy, pixie, etc. Further, most of this is also useful (in particular something like eval-paragraph or eval-line) in any language with an interpreter (Python, Ruby, Javascript, etc). I bind `SPC m e o` to be the generic-eval-region operator, and then I can define other things in terms of generic eval region. What's more, users can use this motion for precision evaluation using any evil motions

Right now, I have this snippet in my startup file:

```elisp
(defun spacemacs//emacs-lisp-eval-region-and-print (beg end)
  (interactive)
  (let* ((raw-result (with-output-to-string
                       (eval-region beg end standard-output)))
         (result (when (>= (length raw-result) 1)
                   (substring raw-result 1 -1))))
    (when result
      (cider--display-interactive-eval-result result end))))

(defvar spacemacs--generic-eval-region-alist
  '((clojure-mode . cider-eval-region)
    (emacs-lisp-mode . spacemacs//emacs-lisp-eval-region-and-print)
    (python-mode . python-shell-send-region)))

(defun spacemacs//get-eval-region-for-current-mode ()
  (interactive)
  (catch 'break
    (dolist (test spacemacs--generic-eval-region-alist)
      (let ((mode (car test))
            (val (cdr test)))
        (when (and (symbolp mode)
                   (derived-mode-p mode)
                   (symbolp val))
          (throw 'break val)))))) 

(defun spacemacs//generic-eval-region (beg end)
  (interactive)
  (let ((f (spacemacs//get-eval-region-for-current-mode)))
    (when (functionp f)
      (funcall f beg end))))

(evil-define-operator spacemacs//generic-evil-eval-operator (beg end)
  (spacemacs//generic-eval-region beg end))

(defun spacemacs//generic-eval-line ()
  "Evals the current line as though you did (kbd \"ma^ SPC meo $`a\")"
  (interactive)
  ;; we don't use execute-kbd-macro here, because popping the mark kills the overlay
  (save-excursion
    (let* ((beg (progn (beginning-of-line) (point)))
          (end (progn (end-of-line) (point))))
      (spacemacs//generic-eval-region beg end))))

(defun spacemacs//generic-eval-paragraph ()
  "Evals the current paragraph as though you did (kbd \"ma SPC meo ap`a\")"
  (interactive)
  ;; we don't use execute-kbd-macro here, because popping the mark kills the overlay
  (save-excursion
    (let* ((graph (evil-inner-paragraph))
          (beg (first graph))
          (end (second graph)))
      (spacemacs//generic-eval-region beg end))))

;; Enable highlighting of the area to be eval'd
(define-eval-sexp-fu-flash-command spacemacs//generic-eval-region
  (eval-sexp-fu-flash (cons beg end)))

```

There are a couple issues with it. The flashing should be optional and obey a toggle, as should the eval result overlay. The flashing doesn't rely on anything we don't already depend on, but I'm using the clojure-specific `cider--display-interactive-eval-result` for the overlays which would need factoring out.

**Comment by syl20bnr** [comment]
@emidln what is the progress on this ? Can you send a PR ?

**Comment by emidln** [comment]
@syl20bnr I haven't had time to dress up a proper PR. Hoping to get to that somewhat soon. Sorry for the super late response.

**Comment by kommen** [comment]
We have this in our user config and seems to work fine:

```elisp
  ;; Fix cider-eval-last-sexp in normal mode
  ;; https://github.com/syl20bnr/spacemacs/issues/646#issuecomment-106037404
  (defadvice cider-last-sexp (around evil activate)
    "In normal-state or motion-state, last sexp ends at point."
    (if (or (evil-normal-state-p) (evil-motion-state-p))
        (save-excursion
          (unless (or (eobp) (eolp)) (forward-char))
          ad-do-it)
      ad-do-it))
  ;; fix green highlighting when eval-ing last-sexp
  ;; original cider-eval-sexp-fu (comes with the clojure layer)
  ;;   https://github.com/clojure-emacs/cider-eval-sexp-fu/blob/5687e7b33e17f2be40b036dac82da4a5bc6705fb/cider-eval-sexp-fu.el#L38
  (defadvice cider-esf--bounds-of-last-sexp (around evil activate)
    "In normal-state or motion-state, last sexp ends at point."
    (if (or (evil-normal-state-p) (evil-motion-state-p))
        (cons (save-excursion
                (unless (or (eobp) (eolp)) (forward-char))
                ad-do-it))
      ad-do-it))
```

**Comment by syl20bnr** [comment]
PR welcome :-)

**Comment by Miciah** [comment]
Does `evil-operator-eval` from [evil-extra-operator](https://github.com/Dewdrops/evil-extra-operator) satisfy requirements?  If so, I would be happy to make a PR to add evil-extra-operator to the spacemacs-evil layer.

I'm not sure about the `SPC m e o` binding though.  Having evil operators under the leader key seems cumbersome.  On the other hand, finding available keys to bind to the extra operators will be tricky.  evil-extra-operator adds 9 new operators (although we probably would not bind all of them) and binds `g r` to `evil-operator-eval` by default, but I bind `g !` to `evil-operator-eval` so that I can bind `g r` to `evil-replace-with-register` (which by default is bound to `g R`, which evil-extra-operators binds to `evil-operator-remember` by default...). It's kind of a mess.

**Comment by syl20bnr** [comment]
I'm not sure it fixes the issue. What we need to fix is to be able use
`eval-last-sexp` with point on the closing parenthesis.

**Comment by Miciah** [comment]
`evil-operator-eval` provides a Vim-style way to evaluate sexps, namely an operator that can be used with a motion.  I thought https://github.com/syl20bnr/spacemacs/issues/3103#issuecomment-201482552 was moving the issue in that direction, but you're right that my comment does not address the original problem statement.
