### ISSUE TITLE
add refresh current buffer to magit

### ISSUE THREAD

**Issue by rubic** [syl20bnr/spacemacs#3104]
Magit help advertises:

```
    g      refresh current buffer
```

However, pressing the **g** key results in:

```
    evil-goto-first-line
```

**Comment by robbyoconnor** [comment]
Why not add it...it's pretty easy to do...Dig in and get your hands dirty :)

**Comment by cpaulik** [comment]
This is mapped to `C-S-g` according to the [rules of evilification](https://github.com/syl20bnr/spacemacs/blob/4bec7fb74a8e7b4fb973a2733262b0905a24aaa7/doc/CONVENTIONS.org#evilify-buffers)

**Comment by robbyoconnor** [comment]
:heart:  @cpaulik

**Comment by rubic** [comment]
@robbyoconnor   No, I didn't type gg.  When I pressed the 'g' key I was prompted with `evil-goto-first-line`.  I got my hands dirty.  Within 24 hours of learning to use spacemacs, I filed an issue indicating that the magit help screen doesn't match expected behavior.  Feel free to close this ticket.

@cpaulik Thanks.

**Comment by mbertheau** [comment]
@rubic Please excuse robbyoconnor's behaviour. It is not indicative of and in fact contrary to the attitude of the spacemacs community in general.

Let me also direct your attention at #3022, which discusses this mismatch of on-screen documentation and actual key bindings.

If you have no further questions in this issue, please close it :)

**Comment by robbyoconnor** [comment]
(I apologize for coming off the way I do)

**Comment by rubic** [comment]
@robbyoconnor No problem, all is cool. @mbertheau Thanks.
