### ISSUE TITLE
"Starting new Ispell process" on every word in Markdown mode though flyspell is disabled

### ISSUE THREAD

**Issue by valrus** [syl20bnr/spacemacs#311]
I get the following in my `*Messages*` buffer on just about every word I type in a Markdown buffer, even though I have `flyspell` excluded in one of my contrib layers:

```
Starting "egrep" process...
Starting new Ispell process [ispell::default] ... [4 times]
Starting "egrep" process...
Starting new Ispell process [ispell::default] ...
Starting "egrep" process...
Starting new Ispell process [ispell::default] ...
Starting "egrep" process...
Starting new Ispell process [ispell::default] ... [4 times]
```

It seems to be drastically slowing down Emacs to the point where the text appearing in the window doesn't keep up with my typing. What do I have to do to stop this?

**Comment by Devagamster** [comment]
I tried have been encountering performance issues especially when deleting characters in org files with spell check turned on. I saw this comment about flyspell-lazy and added it with some slight customization and found it to fix all of the problems. It makes the spell check act much more like office in that the corrections take a moment to appear, which is great because that is what I am used to. @syl20bnr Would a pull request that adds this be useful?

**Comment by sooheon** [comment]
@Devagamster if you could add your flyspell-lazy config to the `spell-checking` layer, that'd be great! Thanks.

**Comment by skparkes** [comment]
I've had `flyspell-lazy` configured in my personal emacs setup for some time and have been very pleased.  I'm trying out spacemacs at the moment and can definitely notice the degradation of having it missing.  I don't feel confident trying to customize spacemacs at this point, but maybe after playing some more with it I'll either figure out how to integrate it into my `.spacemacs` at least, or perhaps the main `spell-checking` layer.

**Comment by skparkes** [comment]
I recreated my old settings in spacemacs by adding the following to my `dotspacemacs/user-config`:
```
  (with-eval-after-load 'flyspell
    (require 'flyspell-lazy)
    (flyspell-lazy-mode 1)
    (setq ;; Be a little more aggressive than the lazy defaults
     flyspell-lazy-idle-seconds 2 ;; This scans just the recent changes
     flyspell-lazy-window-idle-seconds 6 ;; This scans the whole window
     )
    )
 ```

I'd send out a pull request for the actual spell checking layer, but it looks like there's a large backlog of pull requests right now...

**Comment by sooheon** [comment]
@skparkes It'd be nice if that could toggle on and off with flyspell-mode; there doesn't seem to be a flyspell-mode hook though.
