### ISSUE TITLE
e binding in expand-region for iedit only works after using iedit

### ISSUE THREAD

**Issue by xificurC** [syl20bnr/spacemacs#3110]
Running `SPC v e` on a fresh buffer doesn't start iedit mode. Running `SPC s e ESC SPC v e` (i.e. starting iedit up, quit, try from expand-region again) kicks it in for use.

**Comment by xificurC** [comment]
Based on some gitter discussion @bmag pointed out this is probably an upstream bug in `evil-iedit-state` at https://github.com/syl20bnr/evil-iedit-state/blob/master/evil-iedit-state.el#L152

**Comment by TheBB** [comment]
I believe https://github.com/syl20bnr/evil-iedit-state/pull/7 should fix this.

**Comment by kommen** [comment]
The upstream issue was fixed and the problem doesn't reproduce any more. I think this can be closed.

**Comment by syl20bnr** [comment]
Thank you. Closed.
