### ISSUE TITLE
How to show eldoc like function-args

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#3112]
The eldoc show documents in the minibuffer which is harmful to programmer's neck... :(

I want something like https://github.com/abo-abo/function-args

How could I hack eldoc to display documents right above the function?

Is there any plan for Spacemacs to support this feature? It would be helpful for Emacsers' health. < 3

thanks.

**Comment by TheBB** [comment]
Not that this isn't a good idea, but if you need to physically move your head to glance at the echo area, you could probably take a few steps away from that monitor.

**Comment by syl20bnr** [comment]
:-)
I like the idea but I don't know how to do it globally.

**Comment by zilongshanren** [comment]
@TheBB yeah, move around the echo area is not intuitive and sometimes distraction, I will try to step away from my monitor...

**Comment by sooheon** [comment]
If you install lispy, it supports this feature (as well as documentation string lookup) for elisp and clojure at least.

**Comment by zilongshanren** [comment]
@sooheon 
Yeah, I do like the feature lispy provided to show inline doc above the function.
