### ISSUE TITLE
3rd-level Org-bullet Problem in Solarized

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#3113]
![2015-09-24_00-16-18](https://cloud.githubusercontent.com/assets/2263580/10050966/8cd931e6-6251-11e5-8b5a-8e00819e05e9.png)

The screenshot shows the actual 3rd level org-bullet should be an eight-pointed star. The heading font in solarized-dark doesn't have the symbol.

One solution is to change the symbol whenever the theme is solarized.

**Comment by TheBB** [comment]
Would it really be sustainable to fix such issues in Spacemacs? My gut reaction is that this is in user configuration scope.

**Comment by syl20bnr** [comment]
There is something wrong with your font, be sure to have the last version of Source Code Pro, this symbol is definitely here.

**Comment by TheBB** [comment]
His headings are displayed in a different font. As you can see the symbol displays fine in the help buffer below there, using SCP.

**Comment by justbur** [comment]
Here are two solutions. Tell solarized not to use a different font for headings
```elisp
(setq solarized-use-variable-pitch nil)
```
or customize your default variable-pitch font to find one that has the symbol (deja vu sans should have it for example)
`M-x customize-face RET variable-pitch RET`

**Comment by robbyoconnor** [comment]
I use solarized dark and have no such issue: 
![image](https://cloud.githubusercontent.com/assets/23088/10062856/3d5ba796-6235-11e5-9335-19fb7be0eba8.png)

**Comment by justbur** [comment]
@robbyoconnor It just depends on what your default sans serif font is, so it's system specific.

**Comment by louy2** [comment]
@robbyoconnor Your headings are still not Source Code Pro

@justbur Thanks for your solutions. Maybe it's better that I just change my system settings.

@TheBB In my opinion, Spacemacs is already recommending Source Code Pro, so disable variable-pitch by default doesn't lose as much as it would gain on user experience. Consider also that solarized-light is the first default theme.

**Comment by syl20bnr** [comment]
I may remove the solarized theme forks from spacemacs in a future version since the official theme from 0.104.0 is the spacemacs theme.

**Comment by robbyoconnor** [comment]
I use solarized -- don't get rid of it completely!

**Comment by TheBB** [comment]
Since this is a theming and font configuration issue, and we are now using a different theme on master, I'm closing this.
