### ISSUE TITLE
Propose to change Chinese layer default font

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#3120]
@zilongshanren
Since Spacemacs is promoting Source Code Pro as its default font, I propose Source Han Sans or Noto Han Sans as Chinese layer default to keep things aligned.

**Comment by zilongshanren** [comment]
@louy2 
`Source Han Sans` and `Noto Han Sans` is for Chinese only or both ?

**Comment by louy2** [comment]
Those are actually the same font, `Source` published by Adobe while `Noto` published by Google. Chinese only, they contain normal `Source Sans` glyphs for other things.

**Comment by zilongshanren** [comment]
@louy2 
The default chinese font doesn't enable by default.

```
;; If the Hiragino Sans GB font is not found in your system, you could call this
;; method in dotspacemacs/config function with a different Chinese font name.
;; If you are using mac, you could put the following code in your dotspacemacs/config function.
;; (when (spacemacs/system-is-mac)
;;   (spacemacs//set-monospaced-font "Source Code Pro" "Hiragino Sans GB" 14 16))
```

I think you could change it to whatever you want.

**Comment by louy2** [comment]
I know and I've done exactly that. But what you do you think if we actually enable Source Han Sans by default? I was a bit confused when I installed Chinese layer and still had codepoint glyphs displayed, and had to dig to the document. Source Han Sans is already recommended among font enthusiasts, so I think it is good enough to be made default.

**Comment by StreakyCobra** [comment]
Any news on this discussion? Are you planing to PR it, or it is an abandoned idea?

**Comment by louy2** [comment]
If changing the font in Chinese layer still ensures a safe fallback when Source Han Sans is not installed, then I'd like to PR. So question: how does Emacs resolve its fonts?

**Comment by StreakyCobra** [comment]
I'm not sure to understand your question?

**Comment by louy2** [comment]
For example in CSS I can specify a number of fonts and have the browser fallback in order. Do I need to write some logic to achieve that in Emacs?

**Comment by StreakyCobra** [comment]
I looked a little bit and it seems related to fontset:
- https://www.gnu.org/software/emacs/manual/html_node/emacs/Fontsets.html
- https://stackoverflow.com/questions/6083496/how-do-you-specify-a-fallback-font-in-emacs
- https://emacs.stackexchange.com/questions/17205/how-do-i-set-up-font-fallback-in-a-robust-way

**Comment by eitazhou** [comment]
Use Source Code Pro only , and I can't align Chinese character and English character in a table when I edit under Org mode.

**Comment by louy2** [comment]
@eitazhou It is possible to set different font sizes for Chinese and English with `(spacemacs//set-monospaced-font "Source Code Pro" "Hiragino Sans GB" 14 16)`. You'd need to find a proper combo to make them align.

**Comment by kingFighter** [comment]
@louy2 Do you find how to set font fallback in spacemacs just like css?
I tried 
```
  (set-fontset-font t 'unicode "Symbola")
  (set-fontset-font t 'unicode "Symbola" nil)
  (set-fontset-font t 'unicode "Symbola" nil 'append)
  (set-fontset-font t 'unicode "Symbola" nil 'prepend)
 (set-fontset-font "fontset-default" nil 
                  (font-spec :size 20 :name "Symbola"))
```
with `dotspacemacs/user-config`.
Not work for me.

**Comment by louy2** [comment]
@kingFighter 
I have not been actively on it. For now you can try `(set-fontset-font "fontset-startup" nil "Symbola" nil 'append)`. 

Ref: https://www.gnu.org/software/emacs/manual/html_node/emacs/Modifying-Fontsets.html#Modifying-Fontsets

**Comment by kingFighter** [comment]
@louy2 Thanks. I tried 
```
(set-fontset-font "fontset-startup" 'unicode (font-spec :name "Consolas"
                                                          :size 20
                                                          :width `normal'
                                                          :weight `normal'
                                                          :powerline-scale 1.1) nil 'prepend)
(set-fontset-font "fontset-startup" 'unicode (font-spec :name "Source Code Pro"
                                                          :size 20
                                                          :width `normal'
                                                          :weight `normal'
                                                          :powerline-scale 1.1) nil 'prepend)
```
with `dotspacemacs/user-config`. It seems work.But properities like `width` and `weight`( `normal` or `'normal'` or ``` `normal' ``` not working.

**Comment by louy2** [comment]
@kingFighter 
For `:width` and `:weight` properties you need to choose from a list of *symbols*, which means you need to specify them as `:width 'normal` and `:weight 'normal`. Symbol is a special type, not string. 

Ref:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html#Face-Attributes
https://www.gnu.org/software/emacs/manual/html_node/elisp/Creating-Symbols.html#Creating-Symbols
https://www.gnu.org/software/emacs/manual/html_node/elisp/Quoting.html#Quoting

**Comment by kingFighter** [comment]
@louy2 
Really thanks for your suggestion and refs. It worked now.
Thanks again.
