### ISSUE TITLE
Issue on org export to latex

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#3121]
I noticed some issues with org export on the latest develop. Calling org export dispatch and asking to export to pdf give the following error. Could this be due to org-plus-contrib in the org layer?

```
Debugger entered--Lisp error: (wrong-number-of-arguments #[(templates) "\212eb\210\306\307\310\306\311#\205\\\312 \313	!\314=\203X\315	
\"\316\317	\"\211	\316\320	\"E\211\235\203<\321\322\316\323	\"\"\210\202W\203W
B\316\324	\"b\210\325\306x\210`|\210\212c\210)+)\202*\207" [record object templates value begin signature nil re-search-forward "{{{[-A-Za-z0-9_]" t org-element-context org-element-type macro org-macro-expand org-element-property :begin :args error "Circular macro expansion: %s" :key :end " 	"] 6 ("/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/org/org-macro.elc" . 3784)] 3)
  org-macro-replace-all((("modification-time" . "(eval (format-time-string \"$1\" '(22019 45819 0 0)))") ("input-file" . "investments.org") ("time" . "(eval (format-time-string \"$1\"))") ("property" . "(eval (org-entry-get nil \"$1\" 'selective))")) nil ("DESCRIPTION" "KEYWORDS" "SUBTITLE" "DATE" "TITLE" "DATE" "AUTHOR"))
  org-export-as(latex nil nil nil (:output-file "./investments.tex"))
  org-export-to-file(latex "./investments.tex" nil nil nil nil nil #[(file) "\301!\207" [file org-latex-compile] 2])
  org-latex-export-to-pdf(nil nil nil nil)
  (org-open-file (org-latex-export-to-pdf nil s v b))
  (if a (org-latex-export-to-pdf t s v b) (org-open-file (org-latex-export-to-pdf nil s v b)))
  (lambda (a s v b) (if a (org-latex-export-to-pdf t s v b) (org-open-file (org-latex-export-to-pdf nil s v b))))(nil nil nil nil)
  org-export-dispatch(nil)
  funcall-interactively(org-export-dispatch nil)
  call-interactively(org-export-dispatch nil nil)
  command-execute(org-export-dispatch)
```

**Comment by myrjola** [comment]
I also get this and a related warning e.g. when pressing `M-RET`:

```
byte-code: Symbol's value as variable is void: org-planning-line-re
```

This is usually because Emacs' builtin org-mode is loaded before the Elpa-version. In my case this was due to wrongly configured private layer.

I solved it by deleting the org-folder from my Emacs distribution to more easily flag all error situations when starting spacemacs. My quick fix was to wrap all my org specific configurations with:

```
(eval-after-load 'org
  '(progn
     ;; Configuration goes here.
  ))
```

Maybe someone knows The Right Way™ to do this? How to customize org-mode in private layers so that org is loaded from the correct place i.e. ~/.emacs.d/elpa/org-plus-contrib.

**Comment by cpaulik** [comment]
I'm working from a git submodule of the org-mode repo without major problems.

Setting the `load-path` in `dotspacemacs/init` to e.g.

```elisp
  (add-to-list 'load-path "~/dotfiles/.spacemacs-config/org-mode/lisp")
  (add-to-list 'load-path "~/dotfiles/.spacemacs-config/org-mode/contrib/lisp" t)
```
works for me. 

When updating packages it can however happen that spacemacs installs org-mode into the `elpa` directory which I then have to delete to go back to my version.

**Comment by sooheon** [comment]
@myrjola I tried your way, (wrapping all org config in `with-eval-after-load`) and it didn't work for me. Excluding `org-plus-contrib` fixed the problem for me. Any idea what org-plus-contrib package is supposed to accomplish? I wonder if there was discussion about adding it I can refer to.

@cpaulik Previous to this update I also did it your way, loading the latest org I'd downloaded. By deleting org-mode from elpa, do you mean `org-plus-contrib` as well? That seems to be causing the problem for me.

**Comment by mclearc** [comment]
Excluding `org-plus-contrib` also worked for me.

**Comment by cpaulik** [comment]
@sooheon Ok, it seems that I was not on the latest develop. No I have the same problem :cry:

**Comment by cpaulik** [comment]
But to answer the original question, @sooheon Org export to latex/pdf still works for me using the org-plus-contrib version that is installed from elpa. So it might be something else. 

Have you tried exporting a minimal org mode example?

**Comment by syl20bnr** [comment]
`org-plus-contrib` is org with additional feature. I'll dig to find how to properly install it and take precedence over the built-in one.

**Comment by cpaulik** [comment]
I had no problem with it taking precedence over the built in org-mode.

@myrjola You might want to use a `post-init-org` function in your custom config layer to overwrite any settings with your private settings. This has worked well for me.

**Comment by sooheon** [comment]
@cpaulik all of my config for org and related are inside `post-init...` functions, and this problem persists for me. I'm not sure that by itself is sufficient to fix this?

**Comment by cpaulik** [comment]
@sooheon This might be related. Doing org-config in a post-init function overrides the settings of the org ayer if necessary and should also make sure that org is not required too soon. See the [FAQ on mixed installations of org-mode](http://orgmode.org/worg/org-faq.html#mixed-install). What does your `M-x org-version` tell you?

Is your problem the usage of the wrong org version or that export does not work with the one provided by ELPA?

**Comment by sooheon** [comment]
@cpaulik org version is the org-plus-contrib version. However, the call to latex export seems to reference `"/usr/local/Cellar/emacs/HEAD/share/emacs/25.0.50/lisp/org/org-macro.elc"` somewhere (from the error msg) which may be the cause orf the problem.

**Comment by sooheon** [comment]
`org-plus-contrib` also breaks auto-fill and manually calling fill-paragrah, telling me there is an unrecognized character in the line.

**Comment by syl20bnr** [comment]
I doubt that it will fix the issue but get the last develop and delete org from your elpa directory to reinstall it. See if the installation is in a better shape.

Basically I just added org-plus-contrib to the pre step.

**Comment by cpaulik** [comment]
@sooheon Could this be an issue with emacs 25.0.50?

**Comment by sooheon** [comment]
Whatever @syl20bnr did to the latest develop fixed the issue for me! Can others who had the issue check as well?

@cpaulik maybe, because it was referencing some el files from the emacs25 org distro, but that's been fixed with syl20bnr's commit for me.

**Comment by TheBB** [comment]
Since this is apparently fixed for the original reporter, and nobody said otherwise for four days, I'm closing. If anyone is still experiencing problems, please open a new issue.
