### ISSUE TITLE
is it possible to automatically insert semicolons in js2-mode?

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#3123]
http://stackoverflow.com/questions/9241523/emacs-is-it-possible-to-automatically-insert-semicolons-in-js2-mode

I have tried the above solution, but it failed.

Any suggestions would be appreciated.

**Comment by zilongshanren** [comment]
I have wrap a simple method to insert ; at the end of current line.

```
  (defun zilongshanren/insert-semicolon-at-the-end-of-this-line ()
    (interactive)
    (save-excursion
      (end-of-line)
      (insert ";")))
  (bind-key* "s-;" 'zilongshanren/insert-semicolon-at-the-end-of-this-line)
```

But it has limit usage, hopefully it could helps.

**Comment by TheBB** [comment]
This seems to be a little too specific, and not a very sought-after feature. Since we're trying to cut down on the less important issues, I'm closing this. Feel free to re-submit if you want a more general semicolon feature, or something like that.
