### ISSUE TITLE
deft defaults

### ISSUE THREAD

**Issue by BrianHicks** [syl20bnr/spacemacs#3128]
Just as a user, I found it very confusing that when I hit "enter" in deft it names the note `deft-0.txt`. After a little digging, I came up with what are better defaults for me (naming the note after the search query, to start.) This made deft _so_ much more usable for me, and so I thought I'd open up a ticket here to discuss. What would y'all think of these defaults? These make it more like the defaults of Notational Velocity.

``` elisp
(setq deft-extensions '("txt" "md")
      deft-use-filter-string-for-filename t)
```

And by way of explanation:
- `deft-extensions` should include Markdown files by default. Mine actually sets "md" first but I realize that may cause some surprises for upgrades, as the first in order will be the default for new notes.
- `deft-use-filter-string-for-filename` means that if you search for "foobar" and hit enter, you get a note named "foobar.txt". This means you get descriptive filenames, which helps especially when editing on mobile (e.g. through the Dropbox app.)

Any thoughts?

**Comment by mclearc** [comment]
I just pushed a change to the default extensions (#3093), which includes org and markdown as values. If you think that the title should be defaulted to a particular value you might open a pull request with the relevant setting.

**Comment by BrianHicks** [comment]
How funny we should be thinking of this at the same time. So that's one half of the question down. But for the other half, is it useful for people who use the layer to have nicer note titles by default? I think it is.

**Comment by mclearc** [comment]
I think you're probably right. If you don't mind making the pull request it seems worth it. :+1:
