### ISSUE TITLE
Improve table related keybinding in org-mode according to vim-table-mode

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#3131]
Ref: https://github.com/dhruvasagar/vim-table-mode

**Comment by sooheon** [comment]
Which specific changes would you like? Org does have a rich standardised way to deal with and edit tables, are you looking to add to these, replace them? I looked at the demo and it looks like a *different* way to do things, but I don't see any clear advantage.

**Comment by robbyoconnor** [comment]
I'm gonna go with :-1:

**Comment by louy2** [comment]
Revamp is probably too heavy a word here. I was thinking more like adding the easier cell-wise motion binding based on brackets to the current leader only options, and see what more are common and can be added.

**Comment by robbyoconnor** [comment]
Still :-1: , org mode has plenty of support...

**Comment by louy2** [comment]
@robbyoconnor Are you sure? https://github.com/jceb/vim-orgmode :tongue:

**Comment by robbyoconnor** [comment]
Why is this better...we have table related keybindings now?

--Rob

**Comment by louy2** [comment]
Yes we do, and a lot of them. I'm sure you can find them useful from time to time. You can see them in `layers/org/README.org`.

It's not that vim-table-mode way is better. It's that we have this gap that it can fill. On second thought, I should make this another package.

**Comment by robbyoconnor** [comment]
Why do we have to mimic EVERYTHING vim does? This is a case where I feel like it's a bit too much...so what there's a vim plugin...big deal...this is addressing a shortcoming in vim (yay) -- but in emacs, we do not have this shortcoming, so I feel like it's utterly useless.

**Comment by louy2** [comment]
> @robbyoconnor 
> but in emacs, we do not have this shortcoming

How do you move about your table now?

**Comment by robbyoconnor** [comment]
Cut/paste?

**Comment by louy2** [comment]
> move about your table
 
My bad, I mean "navigate inside your table" by that.

**Comment by robbyoconnor** [comment]
I can tab between fields in org-mode dude :P

**Comment by louy2** [comment]
Wow, thanks for introducing me to `orgtbl-*`. No keybinding is revealing it and because it doesn't contain `table` I did not find it. How are they bound? I see nothing in text properties either.

**Comment by louy2** [comment]
Oh nevermind. It is hardcoded into `org-cycle`.

**Comment by robbyoconnor** [comment]
@louy2 -- there are keybindings...#2922 introduced them

**Comment by louy2** [comment]
#2922 introduced the shortcuts I mentioned to you -- those in `layers/org/README.org`. Navigation in tables is hardcoded in `org.el` in the corresponding functions, or enabled by hijacking the keys if you enable `orgtbl-mode` in other modes. A side-effect is shadowing the original binding for `describe-key`.
