### ISSUE TITLE
[Meta Issue] Link to the contribution guidelines when opening an issue or a pull request

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#3135]
It annoys me to no end when people do PRs against `master` -- I think we should link to the [contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONTRIBUTE.org). I know this is possible, just not sure what settings to add -- besides, I can't do it. Nobody bothers to read the rather short document!

**Comment by cpaulik** [comment]
@robbyoconnor We habe to add a `CONTRIBUTING` or `CONTRIBUTING.md` file to the root of the project. See https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by robbyoconnor** [comment]
Then we should move that file to the root. I show absolutely zero mercy for people who pull it -- ignorance is not an excuse for being stupid.

**Comment by robbyoconnor** [comment]
can .org work I wonder?

**Comment by robbyoconnor** [comment]
PR coming.

**Comment by cpaulik** [comment]
I think it would make sense to make an extra document that is really, really short and also talks about raising issues. e.g. That it would be very helpful if people could include the branch/or commit on which the error occurs as well as emacs version and OS.

**Comment by person808** [comment]
We also want CONTRIBUTING.org to show up in `helm-spacemacs` which only searches in `doc/` so it may not be the best idea to completely move the file to the root.

**Comment by robbyoconnor** [comment]
I'm thinking of just linking to it

**Comment by bmag** [comment]
https://github.com/rails/rails/blob/master/CONTRIBUTING.md looks like a suitable example - a short intro with links to other resources. In our case "other resources" would be files in the `doc/` directory

**Comment by robbyoconnor** [comment]
I opted to just link to the contribution org file -- quite frankly -- copying it is more work than I wanna do right now...it's also after 4am :P

**Comment by robbyoconnor** [comment]
I think #3138 should be cherrypicked into both `master` and `develop` -- it doesn't warrant a new version being released -- but it's useful as it will show the link since `master` is the default branch. I believe we should keep `doc/CONTRIBUTE.org` -- since it has a lot more information than I feel like porting to markdown (exporting to github flavored markdown seems broken at the moment) and `helm-spacemacs` should be able to find it.

**Comment by robbyoconnor** [comment]
Fixed in #3138
