### ISSUE TITLE
Git extremely slow with Spacemacs

### ISSUE THREAD

**Issue by ntcong** [syl20bnr/spacemacs#3136]
Magit staging is extremely slow in a large repository, magit used to have problem with mode-line calling it too much, maybe spacemacs have the same problem now.

<img width="831" alt="screen shot 2015-09-25 at 10 14 39" src="https://cloud.githubusercontent.com/assets/167336/10092292/e21c9418-636e-11e5-95de-6d7fd3f31779.png">

**Comment by robbyoconnor** [comment]
There is nothing spacemacs can do about this. Raise an issue upstream with the magit folks...

**Comment by ntcong** [comment]
I included the profiler, it was spacemacs/mode-line problem, no?

**Comment by robbyoconnor** [comment]
What OS are you running on? when you report performance bugs, the OS can affect things. Windows is known to be rather slow for example.

**Comment by ntcong** [comment]
I'm using OSX. Tried profiling again and different things show up

```
               - magit-diff-highlight-recursive                 57782  98%
                - if                                            57782  98%
                 - let*                                         57782  98%
                  - cond                                        57782  98%
                   - let                                        57782  98%
                    - magit-diff-highlight-list                 57782  98%
                     - let                                      57782  98%
                      - if                                      57782  98%
                       - if                                     57782  98%
                        - let                                   57782  98%
                         - while                                57782  98%
                          - magit-diff-highlight-recursive              57782  98%
```

**Comment by syl20bnr** [comment]
Can you exclude the powerline package and see if you have better performance in your repo ?

**Comment by ntcong** [comment]
disable powerline won't help, so maybe a general magit performance issue? The profiling report is not really that helpful

**Comment by syl20bnr** [comment]
Is the repo public ? Also which commands are slow ? Everything or just some buffers opening etc ?

**Comment by d12frosted** [comment]
I found that in one huge project (unfortunately, not public) stashing commands are very very very slow. Usually I switch to terminal to perform stash actions (like `stash` and `stash pop`), because it's much faster. But this is the project that makes 'projectile' freeze :D 

Once I have a chance I'll profile it.

Btw, I am on OS X, dev branch, `emacs-24.5-z-mac-5.10`.

**Comment by justin808** [comment]
FWIW, this is a problem even on moderate size repos on very fast macs (2015 maxed MBP).

**Comment by d12frosted** [comment]
FYI, doesn't happen anymore.

**Comment by StreakyCobra** [comment]
Does anyone still have this issue after updating packages and an up-to-date spacemacs?

**Comment by d12frosted** [comment]
As I told - everything is fine now for me.

**Comment by StreakyCobra** [comment]
@ntcong @justin808 Do you still have this problem?

**Comment by justin808** [comment]
@StreakyCobra It doesn't seem as bad anymore, but FWIW, I'm using VIM a quite a bit when I don't want to wait for magit, and I'm on the fastest MBP available.

**Comment by ntcong** [comment]
I'll try to generate a big changes like the original report

**Comment by hamhut1066** [comment]
Magit is being pretty slow for me too. Profile is linked. I can help narrow down the problem if given directions to look in
<img width="1680" alt="screen shot 2015-12-16 at 03 24 23" src="https://cloud.githubusercontent.com/assets/1742172/11831291/19fd74b2-a3a5-11e5-8805-10e1b566b732.png">

**Comment by kommen** [comment]
Not having this problem on macOS with latest magit 0.2.12, Emacs 25.3 (installed via brew emacs-plus) and latest spacemacs develop branch.

**Comment by syl20bnr** [comment]
This is a known bug and there is a patch available with `emacs-plus` tap
when installing with homebrew. The patch is applied by default so if you
reinstall emacs from homebrew using the tap, you should be good.

**Comment by syl20bnr** [comment]
Closing, feel free to reopen if the `emacs-plus` tap does not fix it.

**Comment by kommen** [comment]
To clarify, the patch @syl20bnr mentioned is the vfork patch:

https://github.com/d12frosted/homebrew-emacs-plus/blob/c5ab351aa4773f6bb62450b1e66485cf54faee84/Formula/emacs-plus.rb#L131-L140

It will ship built-in with Emacs 26.1 (which is at release candidate stage already and due soon), so with that the issue should be resolved regardless how people install their Emacs.
