### ISSUE TITLE
Error (use-package): web-mode :config: Symbol's function definition is void: sp-local-pair

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#3137]
error message when opening a html file with web-mode enabled.

**Comment by TheBB** [comment]
Do you have smartparens excluded? The web-mode configuration apparently depends on it. That's a bug.

**Comment by zilongshanren** [comment]
@TheBB
No, I don't exclude smartparens.

**Comment by syl20bnr** [comment]
@zilongshanren can you check if the issue still happens on last develop ?

**Comment by zilongshanren** [comment]
@syl20bnr  @TheBB 
the error is still exists :(

**Comment by StreakyCobra** [comment]
Do you still have this error after updating packages?

**Comment by emmanueltouzery** [comment]
well I have this error here too. I updated the packages, but the error is still present for me.

**Comment by sebhahn** [comment]
I'll get the same error when I try to export an org-mode file using org-reveal

**Comment by TheBB** [comment]
There was a commit recently in develop which should have fixed this (finally). At least with regards to web-mode.

There is indeed also a bug that prevents smartparens from being excluded. I'm not sure if it caused your problem @emmanueltouzery but I have submitted a PR in https://github.com/syl20bnr/spacemacs/pull/4050/files.

About org-reveal I know nothing, but if the error message was literally the same (it also mentioned web-mode) then it shoulda lso be fixed in develop.

**Comment by skebanga** [comment]
This seems to have reappeared in develop

```
Error (use-package): company-anaconda :init: Symbol's function definition is void: spacemacs|add-company-backends
Error (use-package): company-c-headers :init: Symbol's function definition is void: spacemacs|add-company-backends
Error (use-package): company-go :init: Symbol's function definition is void: spacemacs|add-company-backends
Error (use-package): company-lua :init: Symbol's function definition is void: spacemacs|add-company-backends
Error (use-package): company-web :init: Symbol's function definition is void: spacemacs|add-company-backends
```

**Comment by TheBB** [comment]
That's a bug, but not the same bug.

**Comment by skebanga** [comment]
Does an issue exist, or should I create a new one?

**Comment by TheBB** [comment]
In fact, it's this bug: https://github.com/syl20bnr/spacemacs/issues/9134

**Comment by skebanga** [comment]
Ha, race condition in cyberspace!

Thanks!
