### ISSUE TITLE
ag.el is not included in package

### ISSUE THREAD

**Issue by bgvianyc** [syl20bnr/spacemacs#3141]
spacemacs includes projectile and helm which make use of ag.el (helm-do-ag) (projectile-ag - C-c p s s), but does not include the package necessary to run these commands, which is ag.el.

**Comment by justbur** [comment]
Helm-ag is the package required for these commands, and yes it is included.

**Comment by TheBB** [comment]
Indeed, and for the record, `helm-ag` does *not* depend on `ag`.

https://github.com/syohex/emacs-helm-ag/blob/master/helm-ag.el#L8

**Comment by TheBB** [comment]
This is not a bug, so I'm closing this. If you have any actual problems with ag-related commands, please reopen.

**Comment by simendsjo** [comment]
I'm having some issues here too. `ag` exists on my system (running `:!ag` lists the usage), and `helm-do-ag` and `helm-projectile-ag` works fine. `projectile-ag`, however, says `Package 'ag' is not available`.

**Comment by zachdaniel** [comment]
Same here.  Any ideas?

**Comment by lvh** [comment]
Same here; although I'm not sure if #7868 is a better description; there might be more than one issue at play.
