### ISSUE TITLE
evil-ace-line-jump-mode with multiple windows open is very slow.

### ISSUE THREAD

**Issue by askreet** [syl20bnr/spacemacs#3143]
If I have just one window, it's fast. If I have multiple it appears to jump focus back and forth between them very rapidly. I did see there was another issue closed referencing it being slow as a motion for delete, but I'm experiencing it without an action as well.

That issue is #963.

**Comment by askreet** [comment]
Please let me know what additional information I can provide.

**Comment by bmag** [comment]
I'm guessing you're using master branch. In develop branch, ace-jump-mode was replaced by avy, and `evil-ace-line-jump-mode` was replaced by `evil-avy-goto-line`. FWIW I don't experience any slowness when using avy in develop branch.

About additional information, typing `SPC h d s` will copy to the clipboard information regarding your setup that you can paste here, but I think it isn't in master yet.

**Comment by TheBB** [comment]
Closing this since ace has been removed. If you experience the same problems with avy, please reopen.
