### ISSUE TITLE
centered-point not honoured in :s//

### ISSUE THREAD

**Issue by mbertheau** [syl20bnr/spacemacs#3145]
Steps to reproduce:
1. Open file that has at least twice as many lines as your window and many letters `e` in it.
2. Enable `centered-point` with <kbd>SPC t -</kbd>
3. Scroll around and observe how the point stays in the vertical center of the window and the file scrolls around it.
4. <kbd>:%s/e/E/gc</kbd>

Observe:
as you confirm or reject the replacement, the point doesn't stay in the vertical center of the window as in step 3.

Expected:
The point stays in the vertical center of the window even during search/replace confirmation

**Comment by louy2** [comment]
Strange. My centered-point doesn't even work when I manually move the cursor.

**Comment by StreakyCobra** [comment]
@mbertheau I can't reproduce this bug, not on `develop` nor on `master`. Can you verify it still happens for you, I may do something wrong while trying to reproduce it.

**Comment by mbertheau** [comment]
@StreakyCobra I still happens for me as of master a few minutes ago.

It happens for ClojureScript and Python files for me. Note that the point stays in the vertical middle when just searching for a letter and scrolling through the matches with `n`. It does not stay in the middle after `:%s/e/E/gc` when scrolling through replacement confirmations with `n`. When I abort the replacement with `Esc`, the point returns to the vertical middle.

**Comment by StreakyCobra** [comment]
Indeed, I can reproduce it now! I think the `%` is missing in the `:s/e/E/gc` of your first post then :relaxed:

**Comment by mbertheau** [comment]
Indeed, added that now! Thanks :)
