### ISSUE TITLE
helm-M-x doesn't accept prearg given before invoking it

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#3147]
This is definitely an upstream problem, but I think it affects the experience here. It would be most natural for helm-M-x to take the arg and set it no different than using `C-[0-9]` inside.

**Comment by louy2** [comment]
Duplication of #1206

**Comment by justbur** [comment]
You could try the smex layer

**Comment by louy2** [comment]
Thank you so much!
