### ISSUE TITLE
develop - `.` is not repeating actions

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3149]
To reproduce:

1. Open `*scratch*`
2. Enter insert mode
3. Type `hello world`
4. Press `fd`
5. Type `ciw test`, press `fd`.  It should replace `world` with `test`.
6. Press `^` to move to the beginning of the line (and over the word `hello`)
7. Press `.` to repeat `ciw test`

I get this error in `*Messages*`:

```
After 0 kbd macro iterations: evil-read-key: Args out of range: "", 0 [2 times]
```

Expected:  It should replace `hello` with `test`.

EDIT: Changed `ESC` to `fd`, using `ESC` produces the desired results.

**Comment by justbur** [comment]
Need more information. Are you actually using the escape key? I assume your editing mode is vim. Did you try debug-on-error for a backtrace?

**Comment by synic** [comment]
Yes, I am using the vim editing mode.  No, I didn't actually press `ESC`, I am using `fd`.  Looks like `ESC` actually works.

Here is the backtrace:

```
Debugger entered--Lisp error: (args-out-of-range "" 0)
  byte-code("\306\307\310	\311\"#\210\306\312\310	\313\"#\210\314\315\316\"\211\235\203\"\210\202(\317\nC\")\320!\210\321\322\323#\211\324H\325\f!\326!\203Q\324H\325!\202<\316=\203Z
\207\203d\327!\207\330\331!\207" [new-global-map global-map x prompt seq char define-key [menu-bar] lookup-key [menu-bar] [tool-bar] [tool-bar] make-char-table display-table self-insert-command append use-global-map read-key-sequence nil t 0 key-binding arrayp call-interactively user-error "No replacement character typed" cmd] 7)
  evil-read-key()
  (if (evil-operator-state-p) (save-restriction (widen) (narrow-to-region (car (car evil-restriction-stack)) (cdr (car evil-restriction-stack))) (let ((evil-restriction-stack (cdr evil-restriction-stack))) (evil-read-key))) (evil-read-key))
  (list (if current-prefix-arg (progn (prefix-numeric-value current-prefix-arg))) (if (evil-operator-state-p) (save-restriction (widen) (narrow-to-region (car (car evil-restriction-stack)) (cdr (car evil-restriction-stack))) (let ((evil-restriction-stack (cdr evil-restriction-stack))) (evil-read-key))) (evil-read-key)))
  call-interactively(evil-find-char nil nil)
  command-execute(evil-find-char)
  execute-kbd-macro([102])
  evil-execute-repeat-info(([102]))
  evil-execute-repeat-info-with-count(nil ([102]))
  evil-repeat(nil nil)
  call-interactively(evil-repeat nil nil)
  command-execute(evil-repeat)
```

**Comment by justbur** [comment]
That's what I figured. Thank you for the backtrace. There's some work being done on fixing repeat for evil-escape. Here's a recent update

https://github.com/syl20bnr/evil-escape/pull/49

**Comment by syl20bnr** [comment]
Fixed in version 3.10 of evil-escape thanks to @justbur :-)
Should be available in a few hours in MELPA.

**Comment by synic** [comment]
:+1: Fixed for me!

**Comment by TheBB** [comment]
Confirmed.
