### ISSUE TITLE
add anaconda-mode-go-back keybinding

### ISSUE THREAD

**Issue by rubic** [syl20bnr/spacemacs#3150]
Anaconda navigation has a useful "go back" operation, bound to the M-* key.  Add a `SPC m g b` keybinding to match the other `mg` keys in the layer.

**Comment by TheBB** [comment]
Wouldn't it be better to make it work with `C-o` and `C-i` of `evil-jumper`?

**Comment by TheBB** [comment]
I just checked and `C-o` works fine. I don't think we need this.

**Comment by rubic** [comment]
Sorry, I wasn't familiar with `evil-jumper`.   Closing this ticket.

**Comment by nixmaniack** [comment]
I think `<leader> m g b` would be useful addition when in emacs state or insert state of hybrid mode. Hitting `M-RET g b` to go back is according to conventions of spacemacs to have consistency. Thoughts?
