### ISSUE TITLE
`SPC b K` breaks `which-key` on develop

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3153]
To reproduce: 

1.  Open spacemacs
2.  Type `SPC b K` to to call `spacemacs/kill-other-buffers`

`which-key` is now broken.  Looks like it also kills `*scratch*`.

```elisp
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  which-key--show-page(0)
  which-key--create-buffer-and-show([32])
  which-key--update()
  apply(which-key--update nil)
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 0 1 0 t which-key--update nil idle 0])
```

**Comment by justbur** [comment]
Thanks for the report. Which-key will check to see if the buffer was killed before it shows the popup now, but I think this is also an issue with the kill-other-buffers function being too aggressive. Do we really need it to kill hidden buffers?

**Comment by TheBB** [comment]
I admit I don't really see the purpose with `SPC b K` in the first place.

**Comment by synic** [comment]
I like `SPC b K` because after a while, there's lots of open buffers that need to get auto-reverted every time I switch branches in git.  Eventually it starts getting slow, so I just kill all the buffers and start over.

**Comment by justbur** [comment]
Just seems risky because which-key is not the only mode to use hidden buffers to store information. They shouldn't fail when killed but I wouldn't want to kill those buffers randomly either.

**Comment by justbur** [comment]
Plus a buffer not visiting a file doesn't get reverted

**Comment by justbur** [comment]
@synic Try `SPC p k` to kill all buffers associated with a project
