### ISSUE TITLE
can not expand ycmd results automatically, and M-x company-ycmd can show results.

### ISSUE THREAD

**Issue by kekeadou** [syl20bnr/spacemacs#3157]
I'm working on mac, with emacs-mac port. 
Problem is like this:
![image](https://cloud.githubusercontent.com/assets/9260768/10126028/bc8c6db0-65ba-11e5-89b4-62505dc3bdd2.png)
if i type TAB after dd, it shows [No matches].
But if I execute 'M-x company-ycmd',  it can show the result normally.
And 'M-x ycmd-display-completions', can also get the right results.

My settings are:
after downloading spacemacs, I added two layers ycmd,osx in dotspacemacs/layers.
and add global-ycmd-mode global-company-mode in dotspacemacs/config.

I can not figure out where the problem is, any help will be appreciated :)
Thank you.

**Comment by CandySunPlus** [comment]
@kekeadou How to resolve this problem?
