### ISSUE TITLE
Redefining evil-open-above for Haskell

### ISSUE THREAD

**Issue by PierreR** [syl20bnr/spacemacs#3162]
Whenever you press `shift-o` in Haskell, you get an extra indentation:

To make it clear, if `^`  indicates the cursor position:

```haskell
import           Text.Parsec.Error (ParseError)
import           Text.Parsec.Expr
^
-- after shift-o
import           Text.Parsec.Error (ParseError)

  ^
import           Text.Parsec.Expr
```
There is a trick that can be found in a couple of places on the internet which is to redefine `evil-open-above` as such:
```
(add-hook 'haskell-mode-hook 'redef-evil-open-below)
(defun redef-evil-open-below ()
    (defun evil-open-above (count)
      "Insert a new line above point and switch to Insert state.
    The insertion will be repeated COUNT times."
      (interactive "p")
      (evil-insert-newline-above)
      (setq evil-insert-count count
            evil-insert-lines t
            evil-insert-vcount nil)
      (evil-insert-state 1)
      (add-hook 'post-command-hook #'evil-maybe-remove-spaces)
 ))
```
It works nicely but the change feels gross. Would it be accepted as a PR ?

**Comment by TheBB** [comment]
I would not accept that. At least make it an advice that only takes effect in the relevant mode.

On the other hand, this happens with `o` as well, and it's quite normal for `o` and `O` to indent in various modes. You can `TAB` to get back as is typical in Haskell. I don't think this is a bug. Or if it is, it should be reported to Haskell mode.

**Comment by PierreR** [comment]
Yes I meant to redefined both like [here](https://github.com/Russell91/emacs/blob/master/my-haskell.el)

Note that in Haskell in the default indentation mode I actually need to press TAB twice. `o TAB TAB` is kind of too much but maybe there is a better way to do this ? (a part from  `+/- i` which is also awkward with an azerty keyboard ;-))

**Comment by PierreR** [comment]
I am closing this issue then. I believe it is indeed a bug but related to `haskell-mode`.

**Comment by gracjan** [comment]
Note that setting `evil-auto-indent: nil` prevents `indent-according-to-mode`.
