### ISSUE TITLE
React layer jsx indentation on .js files

### ISSUE THREAD

**Issue by dvcrn** [syl20bnr/spacemacs#3163]
react layer PR - https://github.com/syl20bnr/spacemacs/pull/2399
and ping to @axyz since it's 'his' layer. 

I noticed that jsx tag indentation on normal `.js` files does not work, even when forced with `react-mode` manually executed. 

I messed a bit around and noticed that if I manually add the `/** @jsx React.DOM */` pragma, even though I am already in forced `react-mode` it will magically change syntax color of jsx tags and indentation starts to work. 

Is there a way to force proper jsx indentation when manually going into `react-mode`?

**Comment by shangsunset** [comment]
is there a way to make react layer activated in .js files automatically?

**Comment by TheBB** [comment]
`(push '("\\.js\\'" . react-mode) auto-mode-alist)`

**Comment by shangsunset** [comment]
Thanks. so that makes react layer overrule javascript layer? ideally i would want javascript layer for normal js or node and react layer just for react. is that possible?

**Comment by TheBB** [comment]
There are mechanisms in Emacs for deciding what mode to use based on the filename or the text at the beginning of the file. If you want anything more complicated than that you will probably have to code it yourself.

**Comment by TheBB** [comment]
https://github.com/TheBB/spacemacs/blob/develop/layers/+frameworks/react/packages.el#L66-L70

This is what the react layer currently does.

**Comment by shangsunset** [comment]
@TheBB Thanks.
