### ISSUE TITLE
TAB key is not working as expected in *Help* buffers

### ISSUE THREAD

**Issue by lislon** [syl20bnr/spacemacs#3165]
In the \*Help\* buffers my `TAB` key is not jumps to the next button as I expect. 

`S-TAB`  (`backward-button`) works normally though.

**Comment by sooheon** [comment]
I think this is due to a conflict with `C-i` for evil jumping and `tab`.

`(evil-define-key 'motion help-mode-map (kbd "<tab>") 'forward-button)` fixes it for me, while also keeping the `C-i` binding intact. Not quite sure where this should go in spacemacs @syl20bnr ?

**Comment by lislon** [comment]
Thank you! Works for me.

**Comment by StreakyCobra** [comment]
There is an ongoing more general discussion about how to handle difference between <tab>, TAB and other keybindings in terminal in #3472 I've reported and linked this issue there, so closing this one to avoid dispersing discussions. Feel free to continue the discussion there :relaxed:
