### ISSUE TITLE
font-lock issue with links?

### ISSUE THREAD

**Issue by mclearc** [syl20bnr/spacemacs#3169]
I'm getting a persistent bug using the package  [org-ref](https://github.com/jkitchin/org-ref) where links to citations (e.g. `cite:xyz`) won't show up once the file is closed and reopened. However, if I insert another citation next to the original one, it will then show as a link. I've also found that sometimes adding an extra `[` to the beginning of a `cite:xyz` entry will turn it back into a link. The extra `[` can then be deleted. This works also sometimes just by adding an extra space and deleting it, and even putting the cursor at the end of the link and going from normal to insert mode and back. The org-ref developer thinks it might be a font-lock issue. Any idea as to how this might get tested and fixed?

I'm using GNU Emacs 24.5.1, org 8.3.1, and spacemacs on the most recent develop branch.

**Comment by TheBB** [comment]
I'll leave this open a bit in case someone knows or it happens to be our bug. However, this is an additional/external package, so the problem might not be in Spacemacs.

**Comment by mclearc** [comment]
I haven't figured out what the problem is, but I've moved on to another package for managing bibtex. So I'll close this.
