### ISSUE TITLE
Wanted - ability to change default directory handler away from `dired`.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3170]
There are lots of cool filemanagers for emacs, and a few of them are available in layers for spacemacs, including `ranger`, and `neotree`. 

Learning one of these, however, is not sufficient for using emacs, because the default directory handler is `dired`, and spacemacs doesn't change it.  So even if you learn everything about `ranger`, you're still going to need to learn `dired` and switch back and forth between them.

Links on the spacemacs homepage provided by `projectile` open in `dired`.  Typing `:e ~/` sometimes loads it in `dired`, sometimes in `ranger`.  Sometimes it's a minimal version of `dired`, sometimes it's a full buffer version of `dired`.  I have not figured out what changes this.

IMHO, people should only have to learn to use one file manager.  It should be easy to change what file manager that is.

**Comment by ralesi** [comment]
I am baking something into ranger to optionally default to opening in deer,  but do we want to develop a handler in spacemacs to cover all managers?

**Comment by synic** [comment]
@ralesi has put this into ranger.  I'm going to leave this ticket open as I still think it's probably something people will be looking for in spacemacs.  If someone wants to use `neotree`, they are going to want to use `neotree` for all file operations.  It seems strange to install a file manager that you can't use everywhere a file manager is required.

**Comment by robbyoconnor** [comment]
@ralesi -- yes :D

**Comment by ralesi** [comment]
@synic, @robbyoconnor, I have something working as a macro,  what directory handlers would we like outside of dired,  ranger / deer,  and neotree?  I need to test the possible options to make sure it works.

**Comment by synic** [comment]
@ralesi Looked around in the layers.   The only other one I know is a file manager is vinegar: https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bvim/vinegar

**Comment by ralesi** [comment]
Right now,  with neotree,  it forces as a sidebar ,  so adding it as a handler disrupts the flow.   Vinegar is hooked  into dired much the same way as ranger,  so if you open a directory in dired,  it will automatically show.   We can disable that, and make it a separate minor mode in the layer though.

**Comment by syl20bnr** [comment]
I put this one on the side for now as I see it as an advanced feature, let's keep it open for a future version.
