### ISSUE TITLE
Enabling structured haskell mode breaks vim indentation

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#3171]
With plain haskell layer hitting <kbd>= =</kbd> in normal mode indents as one would expect. With `(haskell :variables haskell-enable-shm-support t)` it just produces an error instead:

> haskell-mode-suggest-indent-choice: You tried to do an indentation command, but an indentation mode has not been enabled yet.
>
> Run M-x describe-variable haskell-mode-hook for a list of such modes.

and the description doesn't have anything to say about indentation modes:

> haskell-mode-hook is a variable defined in `haskell-mode.el'.
> Its value is (spacemacs/init-haskell-mode structured-haskell-mode ghc-init flycheck-mode spacemacs//init-company-haskell-mode company-mode)
>
>
>    This variable may be risky if used as a file-local variable.
>
> Documentation:
> Hook run after entering Haskell mode.
> No problems result if this variable is not bound.
> `add-hook' automatically binds it.  (This is true for all hook variables.)

**Comment by tko** [comment]
Related: https://github.com/chrisdone/structured-haskell-mode/issues/81

**Comment by d12frosted** [comment]
Since officially Chris Done marked `shm` and `evil` as mode-conflict and wont-fix, I think we should close this issue. But I would like to leave #1048 open, because I believe that we could add some workaround for evil users. Gonna think about it in the near future. 

@TheBB what do you think?

**Comment by TheBB** [comment]
Yeah, I'm liable to agree. Let's do SHM stuff in #1048.

**Comment by syl20bnr** [comment]
We finally removed it from haskell layer in develop branch.
It may come back in a better shape at some point :-)

**Comment by syl20bnr** [comment]
oops already closed :-D
