### ISSUE TITLE
keyboard macro replays munged text

### ISSUE THREAD

**Issue by rubic** [syl20bnr/spacemacs#3178]
I'm having problems whenever I replay on-the-fly keyboard macros.  As a test case consider the following code:

![kbdmac1](https://cloud.githubusercontent.com/assets/198470/10147889/412a158c-65f6-11e5-8d79-194aa6c987d8.png)

Starting in insert mode, I type in the necessary keystrokes to wrap `pulse_lower` as a property, using mark region, copy and paste:

![kbdmac2](https://cloud.githubusercontent.com/assets/198470/10147893/46e40140-65f6-11e5-89a5-208d798f2c42.png)

However when I attempt to replay the keyboard macro that I've just created on `pulse_higher`, the replay in munged in the following manner:

![kbdmac3](https://cloud.githubusercontent.com/assets/198470/10147907/4ee93fe0-65f6-11e5-8284-91e86ac625f3.png)

In my vanilla emacs environment, I use keyboard macros 20-50 times a day, so I'm reasonable proficient in using them productively, but I can't seem to get them to work in spacemacs.  I'm using the latest develop branch in hybrid insert mode, if that matters.  emacs 24.4.5.

Final output as code text:

``` python
    def _pulse_lower(self):
        return self.pulse_lower or ''
    pulse_lower = property(_pulse_lower)

    def __pulse_upper


(self):
return self.pulse_upper


 or ''
```

**Comment by TheBB** [comment]
I was able to do this without any problems. Even in hybrid. What was your macro? Mine was (starting from the first `p`):

    qqvEyidef _<ESC>A(self):<RET>return self.<ESC>a or '<C-f><RET><ESC>pa = property(_<ESC>pq

**Comment by rubic** [comment]
I'm using emacs keystrokes to record the macro, not vim.

**Comment by syl20bnr** [comment]
Can you post a more precise repro step including the key bindings to start the recording and ending it ?
Maybe with a simpler macro if you can find one that fails.

**Comment by justbur** [comment]
@rubic I can run a basic emacs macro if I stay in hybrid state to record and run it. If I record in hybrid but switch back to normal something weird happens it seems. Is that what you're doing?

**Comment by rubic** [comment]
If I switch the major mode from ```python-mode``` to ```text-mode```, keyboard replay works, so something in python mode (or one of its associated minor modes) may be causing the munged replay.

I'll work on a simpler example, but for current reference I've pasted the saved macro below.

```lisp
(fset 'pulse
      (lambda (&optional arg) "Keyboard macro."
        (interactive "p")
        (kmacro-exec-ring-item
         (quote ([100 101 102 32 95 134217760 backspace 67108896 5
                      134217847 40 115 101 108 102 41 58 return
                      32 32 32 32 114 101 116 117 114 110 32 115
                      101 108 102 46 112 117 108 115
                      backspace backspace backspace backspace 25
                      32 111 114 32 39 39 return
                      backspace backspace backspace backspace 25
                      32 61 32 112 114 111 112 101 114 116 121 40 95 25
                      41 1 14 14 6 6 6 6]
                      0 "%d")
                )
         arg)
        )
      )
```

**Comment by rubic** [comment]
Definitely a problem due to python-mode.  My current work-around is to:

 1. switch python-mode -> text-mode
 2. record macro
 3. playback macro
 4. switch back to python-mode

I've tried disabling anancoda and flycheck minor modes, but that doesn't seem to help.
