### ISSUE TITLE
Mention `dotspacemacs/test-dotfile` in doc/DOCUMENTATION.org

### ISSUE THREAD

**Issue by xfq** [syl20bnr/spacemacs#3181]
`dotspacemacs/test-dotfile` is a very useful command, since it can test settings in the dotfile for correctness.  I think it should be mentioned in doc/DOCUMENTATION.org.

**Comment by robbyoconnor** [comment]
it will run when you do `SPC f e R`

**Comment by xfq** [comment]
@robbyoconnor But users don't have to run `SPC f e R` after changing the dotfile.  E.g., I always restart Emacs after changing my dotfile.

**Comment by justbur** [comment]
@xfq I agree. It should be mentioned. We missed some things in getting the docs ready.

**Comment by robbyoconnor** [comment]
I will write this documentation if nobody gets to it.

**Comment by justbur** [comment]
Thanks @robbyoconnor . It would be great to have a nice troubleshooting
section.

**Comment by robbyoconnor** [comment]
@justbur -- Nice touch -- wasn't sure how to do this -- I'll do it later.
