### ISSUE TITLE
Current command line overlaps help

### ISSUE THREAD

**Issue by fl00r** [syl20bnr/spacemacs#3190]
See my screenshot

https://www.dropbox.com/s/gomptsvemjromgz/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-09-29%2014.22.57.png?dl=0

**Comment by robbyoconnor** [comment]
I do not have this issue. What OS? Please give the output of `SPC hds`.

**Comment by fl00r** [comment]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.104.1
- Spacemacs branch: master (rev. 2cfc9a5)
- Distribution: spacemacs
- Layers:
```elisp
(clojure ruby markdown syntax-checking
         (git :variables git-gutter-use-fringe t)
         ruby-on-rails)
```

**Comment by robbyoconnor** [comment]
This is not a bug -- your minibuffer is still visible at the bottom. I fail to see why this was even raised...it's working like it should.

**Comment by fl00r** [comment]
In previous version this minibuffer was under help buffer, but not over it, isn't it?

**Comment by justbur** [comment]
@fl00r this looks like a which-key problem. Can you report it at https://github.com/justbur/emacs-which-key?

**Comment by robbyoconnor** [comment]
@fl00r -- ah! I never noticed that -- I guess the fact I been using the same version for awhile...I just don't pay attention..

**Comment by fl00r** [comment]
Installation of osx layer fixed this behavior.

**Comment by justbur** [comment]
Reported here too https://github.com/roman/golden-ratio.el/issues/60
