### ISSUE TITLE
Symbol's function definition is void: gh-md-render-buffer

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#3192]
0. enable markdown layer
1. open a README.md or something
2. press <kbd>SPC m c r</kbd>

Expected result: html preview

Actual result: `Symbol's function definition is void: gh-md-render-buffer` error

**Comment by syl20bnr** [comment]
I removed the `gh-md` package which was in `spacemacs` layer, I thought it was not used anymore since the migration to org files.
Seems it should be added back to markdown layer.
