### ISSUE TITLE
iedit-state and evil-change/evil-delete

### ISSUE THREAD

**Issue by jdwaterson** [syl20bnr/spacemacs#3193]
It looks to me like there is a problem when using iedit-state when words are space-delimited (ie, most, but not all of the time).

Specifically, in these cases, the evil-change and evil-delete commands (on keys <kbd>c</kbd> and <kbd>d</kbd>) drop out of iedit altogether, so my changes are applied at the current cursor position only, and all of the iedit highlighting disappears (although the cursor remains red, so iedit-state still thinks it is active).

Here is an example, showing both working and non-working behaviour. My initial buffer (in fundamental mode) contains just:

```
foobar.qux
foobar.qux
```

I move to the "b" in the first foobar, and then hit <kbd>SPC s e d w</kbd>. In this case, everything works fine and I end up with:

```
foo.qux
foo.qux
```

...which is what I want. On the other hand, if my starting buffer is just one character different, and I replace that first period with a space, viz:

```
foobar qux
foobar.qux
```

...and then, once again I hit <kbd>SPC s e d w</kbd> then I get dumped out of iedit (highlights disappear) and my buffer looks like this:

```
fooqux
foobar.qux
```

I get essentially the same problem if I use <kbd>c w</kbd> instead of <kbd>d w</kbd>. It looks like a bug to me, but not sure if I'm the only person seeing this behaviour?

My spacemacs setup:
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.104.1
- Spacemacs branch: master (rev. 2cfc9a5)
- Distribution: spacemacs
- Layers:

``` elisp
(emacs-lisp git markdown osx themes-megapack clojure html auto-completion :variables auto-completion-return-key-behaviour 'complete auto-completion-tab-key-behaviour 'complete)
```

**Comment by TheBB** [comment]
You should probably report this to https://github.com/syl20bnr/evil-iedit-state for completeness.

**Comment by bmag** [comment]
I've tested a bit and turns out it's a bug in iedit itself: https://github.com/victorhge/iedit/issues/53

**Comment by PierreR** [comment]
Same issue for me while using `c-w`.

**Comment by namdnguyen** [comment]
According to the issue @bmag posted to iedit, it's not a bug but expected behavior. `c-w` and `d-w` are deleting the space in your example between "foobar" and "qux" because "foobar" is the selection when iedit is triggered. Since the space is outside of the selection, iedit aborts. 

Try using `M-x query-replace-regex` instead? `M-x pcre-query-replace-regex` is currently bound to `SPC R %`. There's also `M-x replace-regex` if you don't want to be prompted for each occurrence.

I like using [visual-regexp](https://github.com/benma/visual-regexp.el), which gives you incremental highlighting updates, so I made a private layer for it. It's good for people like me who are still learning regex. I pretty much copied [this configuration](https://github.com/syl20bnr/spacemacs/issues/1550).

**Comment by jdwaterson** [comment]
Ah, that makes sense. And in that case, there is a much simpler solution than using `query-replace-regexp` or similar: just use `SPC s e d e` instead of `SPC s e d w`. That's still a bit tricky, because the `d w` command to delete the current word is not something I really think about, it's a muscle-memory response in my fingers. But I guess I can train myself out of that.

Two thoughts on remaining problems though:

1 - If iedit aborts, then either iedit or spacemacs itself should provide a message in the echo area, to explain what happened. Something like "iedit failed because a command affected text outside of iedit scope" would make it instantly clear to the user what has gone wrong.

2 - The fact that the spacemacs cursor remains red when iedit aborts (ie, indicating that it still thinks iedit is active) is clearly still a bug. It's fairly minor, since pressing escape will fix it. But still, it's definitely misreporting the internal state of the application.

Thoughts on this?
