### ISSUE TITLE
New default theme and Python highlighting

### ISSUE THREAD

**Issue by fladd** [syl20bnr/spacemacs#3195]
The new default theme is suboptimal for Python highlighting.

- class names/properties, strings and line numbers have the same colour
- keywords and parentheses have very similar colours

![screenshot_spacemacs_theme](https://cloud.githubusercontent.com/assets/2971539/10170693/77758898-66d6-11e5-9553-02b85af3db88.png)

Compare this to the solarized theme.

![screenshot_solarized_theme](https://cloud.githubusercontent.com/assets/2971539/10170692/7757c222-66d6-11e5-8965-160e9bcde9fd.png)

**Comment by TheBB** [comment]
This would be better reported to https://github.com/nashamri/spacemacs-theme.

**Comment by fladd** [comment]
I am also curious to lear why the official screenshot of the new release, shows Python highlighting with completely different colours?
https://raw.githubusercontent.com/syl20bnr/spacemacs/master/doc/img/spacemacs-python.png

**Comment by robbyoconnor** [comment]
Because of [this](https://github.com/syl20bnr/spacemacs/tree/develop/layers/colors).

**Comment by fladd** [comment]
Ah thanks. Was already wondering.

But the issue with the normal colouring still stands.

**Comment by robbyoconnor** [comment]
:) It's a problem definitely -- I use solarized-dark personally.

**Comment by fladd** [comment]
So do I :-)
But since they just made this theme the new default, they might want to have this work out of the box for all languages. I guess the idea is to have an own spacemacs theme for branding and recognition. I would in general also be fine with the original theme, if it was as easy to read.

**Comment by TheBB** [comment]
This appears to have been fixed upstream.
