### ISSUE TITLE
C-C++mode, I just updated to 0.104.1, but ac and syntax-checking did not set globally. 

### ISSUE THREAD

**Issue by zhexuany** [syl20bnr/spacemacs#3200]

**Comment by zhexuany** [comment]
Do I need add some hooks?

**Comment by robbyoconnor** [comment]
`SPC hds` please?

**Comment by robbyoconnor** [comment]
Install the [syntax-checking](https://github.com/syl20bnr/spacemacs/tree/master/layers/syntax-checking) layer. And if you have not done do so, the `c-c++` layer.

**Comment by zhexuany** [comment]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.104.2
- Spacemacs branch: master (rev. 074f425)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory t auto-completion-enable-help-tooltip t)
 better-defaults
 (colors :variables colors-enable-rainbow-identifiers t colors-enable-nyan-cat-progress-bar t)
 (git :variables git-magit-status-fullscreen t)
 emacs-lisp markdown org prodigy
 (python :variables python-test-runner 'pytest :variables python-enable-yapf-format-on-save t)
 gtags deft smex latex
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking semantic pandoc syntax-checking version-control eyebrowse evernote puppet slime ycmd zhexuany)
```

**Comment by zhexuany** [comment]
@robbyoconnor  I did. But does not work at all. I need enable manually.

**Comment by robbyoconnor** [comment]
You don't have the c-c++ layer enabled do you?

**Comment by zhexuany** [comment]
@robbyoconnor  I added now. But still have the same problem. I gonna comment all layer and add them again.

**Comment by zhexuany** [comment]
I fixed. It was totally my fault.

**Comment by geo7** [comment]
@zhexuany :+1:  If you could edit the post saying how you fixed it and close this that'd be ace
