### ISSUE TITLE
Disabling line numbers on Neotree

### ISSUE THREAD

**Issue by angrygoats** [syl20bnr/spacemacs#3202]
Hey everyone,

I was enabling line numbers and it seems that if you use the code 

```
   (global-linum-mode)
```

It will enable line numbers as expected, however it also enables them in neotree! Its not critical or anything, but it seems pointless to have them in there. Is there anything I can add to remove them just for neotree, or is this intended behavior?

Thanks!

**Comment by robbyoconnor** [comment]
`SPC t n`

**Comment by angrygoats** [comment]
@robbyoconnor Yeah that's what I have been doing, I was curious if there was anything I could add to my `.spacemacs` file. I'm still pretty new to emacs, so you'll have to forgive me.

**Comment by justbur** [comment]
Try this in your dotfile 
```Elisp 
(with-eval-after-load 'neotree
  (with-current-buffer " *NeoTree*"
    (setq-local linum-mode nil)))
```

**Comment by angrygoats** [comment]
@justbur Thank you for your help. I am getting `No buffer named *NeoTree*` now.

**Comment by justbur** [comment]
Probably need to use a mode-hook. I can't test this right now but i edited my previous comment to show how.

**Comment by angrygoats** [comment]
@justbur Very weird. I can play around with it a little, seems to be giving me the same error.

**Comment by syohex** [comment]
@angrygoats How about this ?

```lisp
(defun my/neotree-hook (_unused)
  (linum-mode -1))
(add-hook 'neo-after-create-hook 'my/neotree-hook)
```

**Comment by angrygoats** [comment]
@syohex Where should I put this in my dotfile?

**Comment by syl20bnr** [comment]
Put in `dotspacemacs/user-config`

**Comment by angrygoats** [comment]
@syohex @syl20bnr 

That worked! awesome!

Thanks everyone.

**Comment by robbyoconnor** [comment]
This really should be default imho.

**Comment by dvcrn** [comment]
Oddly enough, I don't have this problem. `(global-linum-mode t)` is in my `.spacemacs`, but no line numbers in neotree. 

Doing a live reload with `f e R` is adding them to neotree temporarily but after a clean restart of emacs, they are gone and only in my other buffers.

**Comment by synic** [comment]
I've seen it too with `global-linum-mode`,  but they are off by default.  Certain actions will turn them on and then they stay on until you restart emacs or toggle them off.

**Comment by StreakyCobra** [comment]
#3557 will solve this.
