### ISSUE TITLE
Find a solution to the indent level pain point

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#3203]
Is there any package to address this paint point ?
Do we implement something from scratch in Spacemacs ?
I guess an alist `mode . indent-level` would be the most convenient.

**Comment by TheBB** [comment]
Editorconfig has [this](https://github.com/editorconfig/editorconfig-emacs/blob/master/editorconfig.el#L68-L109) alist, which is fairly complete. I uesd it in my [evil-shift-width](https://github.com/TheBB/spacemacs-layers/blob/master/evil-shift-width/config.el#L6-L35) layer to set that varible depending on the current mode's indentation settings. I think this is very close to a solution, but of course we can't get something that is both general and able to cover the advanced settings in a mode such as Haskell.

**Comment by TheBB** [comment]
I don't know how the UI for such a feature would look. I want to stress that we make it possible to opt-out of using this in certain modes, because some of them have very thorough and detailed indentation settings that we might not want to mess with (unless asked).

**Comment by syl20bnr** [comment]
I wonder if we could use the layer abstraction instead of the package. I believe I see this proposition pop out in the chat. Would make sense to have `(layer . indent-level)`.

**Comment by syl20bnr** [comment]
Raising it as high priority because I can see in google that it is a very recurrent paint point for users.

**Comment by aaronjensen** [comment]
I came across https://github.com/jscheid/dtrt-indent which seems to work well and is pretty slick. It could likely be extended to support most major modes.

**Comment by a13ph** [comment]
Indentation style wars are second only to modal vs non-modal editing arguments. Well, maybe block style is up there too, but I've never heard anyone asking about that one.

And even if some projects use some special convention for indentation, most people probably have some preferred setting (their default for personal files etc), which can be asked about once easily - or be presented in homepage? toggles?... config file, I guess? Since many similar non-toggles go there. 

Having specific settings for particular layers/mode/languages in one place would be nice and would probably require just finding all those disparate variables, so that'd be great to add. Not sure how hard it would be to make possible project-specific overrides though, but that does seem like up EditorConfig alley

**Comment by andschwa** [comment]
For what it's worth, [dtrt-indent](https://github.com/jscheid/dtrt-indent) now supports setting generic indentation variables as well, implemented in jscheid/dtrt-indent#23, mostly so I could automatically set `evil-shift-width`. It's very extensible and the maintainer is great.

**Comment by DanielFGray** [comment]
I've been struggling with Emacs altering my indentation as I'm working, and [dtrt-indent](https://github.com/jscheid/dtrt-indent) solved all of the issues I'd been having. I'm kinda surprised it's not already a default package.

**Comment by deb0ch** [comment]
Is there any plans for integrating [dtrt-indent](https://github.com/jscheid/dtrt-indent) shortly ?

Integrating it is dead simple, it basically boils down to just

```
(add-hook 'prog-mode-hook #'(lambda ()
                                (dtrt-indent-mode)
                                (dtrt-indent-adapt)))
```

and that's it.

**Comment by CMCDragonkai** [comment]
Since the last post was 2/3 months ago, I think it really is waiting for a PR.

**Comment by syl20bnr** [comment]
PR welcome! Please check also https://github.com/syl20bnr/spacemacs/issues/7939

**Comment by chasinglogic** [comment]
Wouldn't a layer that fits this violate the docs on contributing a layer?

```
Layer with no associated configuration will be rejected. For instance a layer
with just a package and a hook can be easily replaced by the usage of the
variable =dotspacemacs-additional-packages=.
```

**Comment by xarkes** [comment]
I allow myself to ping here because I feel like this is horrible not to have this by default in 2018.

**Comment by retiform** [comment]
Is there currently a PR for this? It seems like the work that needs to be done is just add in dtrt-indent or something to spacemacs, or is that an incorrect assessment.

**Comment by keevindoherty** [comment]
Totally new to this, but I tried making a Spacemacs layer wrapping [dtrt-indent](https://github.com/jscheid/dtrt-indent), which just implements the suggestion by @deb0ch located [in this repo](https://github.com/keevindoherty/dtrt-indent).

**Comment by retiform** [comment]
@keevindoherty if it works, I would recommend just making an issue or PR about it with the sugestion to merge. The Spacemacs maintainers probably want language specific defaults, but it cant hurt

**Comment by keevindoherty** [comment]
@retiform It seems like it would likely be rejected, based on the following contributing guidelines:
> Layer with no associated configuration will be rejected. For instance a layer with just a package and a hook can be easily replaced by the usage of the variable dotspacemacs-additional-packages.

Happy to try, though, if it would be helpful to people.

**Comment by Compro-Prasad** [comment]
@keevindoherty It is worth trying. The maintainer is the author of the issue. It will likely be merged if your PR fixes this issue.

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Add dtrt-indent layer for automatic indentation detection #12101
