### ISSUE TITLE
Cursor scrolling interfering with term behavior

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#3204]
(If you know the name of the package/variable causing this, please tell me since I can't find it.)

The behavior that makes the screen scroll when the cursor reaches N lines close to either the top or bottom edge of the screen is interfering with term behavior (both `ansi-term` and `multi-term`).

    ^
    |
    |       -   aaaaaaaaaaaa
    |       |   aaaaaaaaaaaa
    |   -   |   aaaaaaaaaaaa
    |   |   |   aaaaaaaaaaaa
    |   |   |   aaaaaaaaaaaa
    |   |   |   aaaaaaaaaaaa
    |   |   |   aaaaaaaaaaaa
    |   |   -   Xaaaaaaaaaaa
    |   |   C   ~
    -   -       ~
    A   B

`A` is the Emacs buffer.  `B` is the portion that is visible in the current
window. `C` is what the program running in term mode *thinks* is visible in the
window.  `X` is where the cursor is.  `a` covers the area where the ncurses
program is painting itself.  `~` is the Vim/Evil empty line marker.

**Comment by TheBB** [comment]
This will presumably be fixed together with #3098.
