### ISSUE TITLE
Broken powerline update image in the main README.md

### ISSUE THREAD

**Issue by cbowdon** [syl20bnr/spacemacs#3208]
In the automatic update section:

    [[file:doc/img/powerline-update.png]]

Should be something like 

    ![powerline_update](doc/img/powerline-update.png) 

I think? This is on master and develop.

**Comment by TheBB** [comment]
Indeed. Fixed in https://github.com/syl20bnr/spacemacs/commit/9e794df0f8cb549730364e13119d5c11c840a69d.
