### ISSUE TITLE
Cannot rename file by deleting some characters in Dired

### ISSUE THREAD

**Issue by yangj1e** [syl20bnr/spacemacs#3210]
In Dired mode, when I try to rename a file by pressing "R", I cannot rename the file by deleting some characters from the original file name.

For example, if the file name is "test.txt", renaming it to "tes.txt" results in 

    Cannot move to same file: /Users/xxx/test.txt

But renaming it to "test1.txt" works fine.

**Comment by TheBB** [comment]
When you type in `tes.txt`, there are two entries in the Helm list. One is `test.txt` (the existing filename), and the other is `[?] tes.txt`, which is exactly what you wrote. You have to pick the latter one.

![Helm](http://i.imgur.com/hoRJppB.png)

**Comment by yangj1e** [comment]
Ah I see. Didn't notice that. Thank you.
