### ISSUE TITLE
yasnippet error when creating files

### ISSUE THREAD

**Issue by Linuus** [syl20bnr/spacemacs#3213]
When time I run `SPC f f ` and write a filename it errors with:
`yas-expand-snippet needs properly setup yas-minor-mode`

Then I do the exact same thing again and it works. So, to create a file I have always have to do it twice...

Is this a known issue and is there a fix?
If not, can I turn off yasnippet somehow?

I'm on OSX Yosemite and running latest develop of Spacemacs.

**Comment by robbyoconnor** [comment]
Is this still a bug? I know we chatted on the gitter chat and I think we arrived at the conclusion it wasn't a bug.

**Comment by Linuus** [comment]
It was a bug  but it was resolved by pulling in the latest from develop and updating my packages. I forgot to close this.

**Comment by robbyoconnor** [comment]
:+1:
