### ISSUE TITLE
Cannot open new window (horizontally or vertically) in `ido-find-file`

### ISSUE THREAD

**Issue by PierreR** [syl20bnr/spacemacs#3214]
With `ido-find-file`, when I want to accept the selection and have the file open in a new window, I can use `c-v`, `c-s` or `c-o` but none of these bindings works. They all fail with a message such as this one:
```
ad-Advice-ido-read-internal: Symbol's function definition is void: spacemacs/split-window-horizontally-and-switch 
```
The function `spacemacs/split-window-horizontally-and-switch` does not seem to exist.

**Comment by PierreR** [comment]
Oh it works if I first enter the micro-state with `M-SPC`. It is really required to go first in a micro-state ofr this ? This is unlike `helm-find-file` and `c-c o`

**Comment by TheBB** [comment]
For the record: this function existed once but was deleted. Should be simply to dig up the commit where it was removed and add it back.

**Comment by PierreR** [comment]
I have found it.  I guess it goes in `layers/+distribution/spacemacs-base/funcs.el`. 
Shall I PR this ?
