### ISSUE TITLE
vim-powerline is missing README.org

### ISSUE THREAD

**Issue by rakyi** [syl20bnr/spacemacs#3218]
`SPC f e h` finds `vim-powerline` but opens empty buffer. There is https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bvim/vim-powerline/extensions/vim-powerline/README.md, which could be adapted.

**Comment by robbyoconnor** [comment]
That's not the README for the layer.

**Comment by robbyoconnor** [comment]
I am writing it right now
