### ISSUE TITLE
ESS: not clear where to set (ess-toggle-underscore nil)

### ISSUE THREAD

**Issue by dewarrn1** [syl20bnr/spacemacs#3222]
ESS's default behavior in R is to replace a typed underscore with R's assignment operator ```<-```.  Many users do not like this.  Setting (ess-toggle-underscore nil) should disable this behavior, but because Spacemacs lazy-loads ESS and the variable needs to be set after ESS loads (or at least after its init phase), it is not clear where to set the ess-toggle-underscore variable.

**Comment by TheBB** [comment]
You can set it where ever. It's safe to set variables before a package is loaded so long as it's not explicitly changed by the loading code, which, as far as I can tell, is not the case here (that is, Spacemacs does *not* set this variable).

**Comment by TheBB** [comment]
Although, for the record, this is how to do postpone code until something loads.

`(with-eval-after-load 'ess (setq ess-toggle-underscore nil))`

**Comment by dewarrn1** [comment]
Thanks for the feedback.  For the record, I've tried a bunch of variations (including adding your recent suggestion to dotspacemacs/user-config), and I still can't suppress the <- for _ behavior.  I don't know if this is an ESS problem or a Spacemacs-plus-ESS problem.

**Comment by TheBB** [comment]
First thing you can check is whether the value of `ess-toggle-underscore` actually *is* `nil` when that happens.

**Comment by dewarrn1** [comment]
OK, and now is when I reveal my massive ignorance of Emacs: how do I check that value?

**Comment by justbur** [comment]
`SPC hdv` allows you to see the docs and value of any variable.

**Comment by dewarrn1** [comment]
OK, got it.  So, some new insight: I appear to have misinterpreted the ```(ess-toggle-underscore nil)``` suggestion I mentioned above.  Instead of setting a variable ```ess-toggle-underscore``` to ```nil```, what I need to do is run the ESS function ```ess-toggle-underscore``` with ```nil``` as the argument.  I tried ```(with-eval-after-load 'ess (ess-toggle-underscore nil))``` and a couple of variations, but that throws a "File mode specification error" for the function.

**Comment by TheBB** [comment]
Okay, maybe you have to do that with an active ESS buffer. Try putting it in a hook

```lisp
(add-hook 'ess-mode-hook
          (lambda () (ess-toggle-underscore nil)))
```

**Comment by dewarrn1** [comment]
That did it — you guys rock!  Thanks a bunch.

**Comment by TheBB** [comment]
Actually we could maybe document this, or provide a feature if this is a common thing to do.

**Comment by dewarrn1** [comment]
I think that it's a great idea to document it.  Judging by a Google search, I'm not the only user who finds this default ESS behavior unappealing, but the ESS layer is the easiest way to add R syntax highlighting and other goodies to Spacemacs.

**Comment by michelk** [comment]
Couldn't we have this as an option, similar to `ess-enable-smart-equals`? Eg `ess-enable-smart-underscore` with default to `nil`?

**Comment by TheBB** [comment]
I wouldn't mind.
