### ISSUE TITLE
Decent folding like in Vim

### ISSUE THREAD

**Issue by ReneFroger** [syl20bnr/spacemacs#3226]
One of the things that I miss in Spacemacs, was the decent folding like Vim have. I opened [a topic about it](http://emacs.stackexchange.com/questions/14781/how-can-i-replicate-vims-code-folding) on Emacs Stackexchange. 

@mrkkrp took the challenge, and developed the package [Vimish fold](https://github.com/mrkkrp/vimish-fold) that succesfully emulates nearly all the abilities of Vim folding method. 

See this screenscast to see it in the action:

![72bfce16-6795-11e5-8c46-ffb3559cdc1d](https://cloud.githubusercontent.com/assets/5211845/10233609/d3bdce70-688f-11e5-8c73-c3ee4f8e93e6.gif)

I was wondering if this could be included with Spacemacs, given the fact that one of the goals of Spacemacs is to emulate Vim. 

Given the fact that Vim creates the folding in visual mode with the key `zf`, I remapped the features of Vimish fold, might be some inspiration for you? : 

```
(key-seq-define evil-normal-state-map "sf" 'vimish-fold-toggle) 
(key-seq-define evil-visual-state-map "sf" 'vimish-fold) 
(key-seq-define evil-normal-state-map "sd" 'vimish-fold-delete) 
(key-seq-define evil-normal-state-map "sj" 'vimish-fold-next-fold) 
(key-seq-define evil-normal-state-map "sk" 'vimish-fold-previous-fold) 
```

Note that you will be still able to use the key `s`, but with another timing.

**Comment by TheBB** [comment]
Can't we get this to work with the regular `z` keys by making the necessary adjustments to `evil-fold-list`?

**Comment by robbyoconnor** [comment]
Yeah I don't see any value in adding this as it can be done with the `z` keys...and it ***DOES*** emulate vim just fine...

**Comment by alexmurray** [comment]
How about
```
(add-to-list 'evil-fold-list '((vimish-fold-mode)
                               :open-all   vimish-fold-unfold-all
                               :close-all  nil
                               :toggle     vimish-fold-toggle
                               :open       vimish-fold-unfold
                               :open-rec   vimish-fold-refold
                               :close      vimish-fold))

```

**Comment by robbyoconnor** [comment]
I personally don't see value but I'm stubborn as hell.

**Comment by alexmurray** [comment]
Also to create a fold with `zf`:
```
(define-key evil-visual-state-map (kbd "zf") #'vimish-fold)
```

**Comment by alexmurray** [comment]
Am hoping to add this to evil itself - first need a little help from vimish-fold - https://github.com/mrkkrp/vimish-fold/pull/16 - and then can add support to evil itself for create, delete and other fold commands: https://bitbucket.org/alexmurray/evil/commits/7523bda77b74a5be2766629bc8a9cf6bfcee3c67 
https://bitbucket.org/alexmurray/evil/commits/e2f6948ff92f41ce2023efb6756f77d747065bc3
https://bitbucket.org/alexmurray/evil/commits/1f9ed7e95e69c1b2edd5e189445ef53449f56cd4

**Comment by alexmurray** [comment]
Update - PR for evil itself (without the need for the change to vimish-fold) - https://bitbucket.org/lyro/evil/pull-requests/24/add-vimish-fold-folding-support-and-fold

**Comment by TheBB** [comment]
@robbyoconnor Vim can do a whole lot more with folds than any of the currently implemented fold methods. It's one of the few remaining feature gaps between Emacs/Evil/Spacemacs and Vim. If this package does what is advertised it's a no-brainer for me to include it.

Good job on the PR @alexmurray, exactly what I had in mind.

**Comment by robbyoconnor** [comment]
:+1:

**Comment by ralesi** [comment]
This is handy,  but how does the work with hideshow as well? The capability to collapse all folds is valuable.   I am also working on package to extend evil and hs to be more like vim, that I will release once I figure out how I am going to maintain multiple ranger frames simultaneously.

**Comment by syl20bnr** [comment]
WOW you guys are amazing :+1: 
@ReneFroger thank you for pointing it out.

**Comment by stormpat** [comment]
:+1:

**Comment by nashamri** [comment]
Ohh nice! this was indeed missing from spacemacs!! good job guys!!

**Comment by alexmurray** [comment]
Since this doesn't appear to be landing in evil just yet - for the impatient have a look at https://github.com/alexmurray/evil-vimish-fold

**Comment by cataclysmic** [comment]
Hey Guys,

great work. I'm loving it. I am really missing the code folding capabilities from Vim.
I do have 2 questions that you might be able to help me with.

1) Do you have plans for adding the "Manual" ( {{{ }}} ) code folding option? I know there is folding.el but I only have troubles with it and I am so used to the nice and quick way in Vim.

2) I try code folding on existing folding marks (I just recently moved from Vim to Emacs and my codes are full of folding marks.) but I only get an error message saying: "Folding is not supported for any of these major / minor modes." Is there any way I can add that mode (ESS) ?
[ I know this might be more of a stackexchange question but you have looked into the evil-code in detail and might be the best to help me. ;-) ]

Anyway thanks again for the package.

**Comment by ReneFroger** [comment]
@cataclysmic 

http://emacs.stackexchange.com/questions/14781/how-can-i-replicate-vims-code-folding

One of these packages have the capability to fold the `{{{` marks.

**Comment by cataclysmic** [comment]
Thanx for the reply.
Sadly all those packages try to mimic the "non-manual" folding of Vim. Which I don't need. The *folding.el* can work with `{{{ }}}` folds but it's pretty messy as it needs the fold in empty lines except for the {{{ and }}}. 
Than apparently it removes the linebreaks somehow and presents the code in a more compact way. Not really folding to me.
I am used to something like this:
`# code segment description #{{{`
`code`
`foo `
`bar`
`#}}}`

when folded turning into:
`# code segment description #{{{ ..........`

I work mainly with statistical software which requires doing the same things many times over with only minor changes. So the recommended "Search for the function you need" approach really doesn't work for me as it produces too many results.

**Comment by ReneFroger** [comment]
@cataclysmic what if you open an issue on the issue tracker of [Vimish Fold](https://github.com/mrkkrp/vimish-fold/issues)?

**Comment by cataclysmic** [comment]
Great idea. I wanted to check all the options first. There just soooo many packages out there. ;-)

**Comment by mkomitee** [comment]
FYI, the PR to evil got declined. Maybe evil-vimish-fold integration in spacemacs is a good idea?

**Comment by cataclysmic** [comment]
Hm Sad.

Thank you for trying.

**Comment by StreakyCobra** [comment]
> Maybe evil-vimish-fold integration in spacemacs is a good idea?

PR welcome :-)

**Comment by hh** [comment]
@cataclysmic did you ever find a nice approach for getting folding working? vimish-fold  doesn't seem that great for ruby code (just trying to fold do/end blocks for chef resources).

**Comment by cataclysmic** [comment]
Hi there,

honestly I moved to using outline-(minor)-mode.
It's a hassle to convert from my old vim-folds but was the best solution 
for me.

**Comment by StreakyCobra** [comment]
You may try  to set `dotspacemacs-folding-method` to `'origami` on the `develop` branch. It has been reported to work better than `evil`'s one.

**Comment by mrkgnao** [comment]
@StreakyCobra doing that gives me a `symbol's value as variable is void: p` for some reason.

**Comment by TheBB** [comment]
Show us your code please.

**Comment by cataclysmic** [comment]
Not sure if you meant me but here:

`;;* Folding  in LaTeX
  (add-hook 'LaTeX-mode-hook 'outline-minor-mode)
  (eval-after-load 'outline
    '(progn
       (require 'outline-magic)
       (define-key outline-minor-mode-map (kbd "<tab>") 'outline-cycle)))

  ;;* Folding in R
  (add-hook 'ess-mode-hook
            '(lambda ()
               (outline-minor-mode)
               (setq outline-regexp "[*#]+")
               ))
  (eval-after-load 'outline
    '(progn
       (require 'outline-magic)
       (define-key outline-minor-mode-map (kbd "<tab>") 'outline-cycle)))
`

In the code it looks like:

# First level fold
.....
## Second level fold
....
### third level fold
.....

**Comment by challsted** [comment]
@mrkgnao I just started learning to edit my `.spacemacs` file about 2 days ago, and was having this very error appear when i made a change to `dotspacemacs-line-numbers`. I found out my issue was that i was missing a single quote before the word you add to the end. 

Example of what i was doing (wrong):  
`dotspacemacs-line-numbers relative`

Example of what I had to change it to to make it work (correct):
`dotspacemacs-line-numbers 'relative` (the extra `'` at the beginning of the word made that error go away for me. Hopefully it will do the same for you. 

@cataclysmic do you have a sample of what you used to fold your tripple braces? (`{{{/}}}`). I maintain a dotfiles repo which includes a .vimrc and init.vim (neovim's vimrc equivilent) and would love to edit them in emacs too :), but its quite annoying editing a very long file with no manual folds set when they dont fold.

**Comment by nixmaniack** [comment]
@challsted Take a look at [dotspacemacs-folding-method](https://github.com/syl20bnr/spacemacs/blob/034f2ea059411e39de9241c6a9327283653e7a8e/core/templates/.spacemacs.template#L259-L261) for more information. You have two options `'origami` which looks more matured as compared to `'evil` which is default. YMMV.

**Comment by costa** [comment]
I hope someone within the project will look into this soon, since it's the *only* feature of Spacemacs that I'm currently missing — coming from me after several years of usage, it's incredible.

I'm particularly interested in this for Ruby DSLs (this may be helpful: https://gist.github.com/littlemove/5c55dfe0bb724f4420c0).

**Comment by costa** [comment]
I'm actually not sure about "Vim-style" folding; I will be absolutely happy with a kinda org minor mode (for Ruby or whatever), with functionality like dragging blocks/methods etc.

**Comment by Kazark** [comment]
I've attempted to integrate `evil-vimish-fold`: https://github.com/syl20bnr/spacemacs/pull/14047

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
[editing] Integrate evil-vimish-fold via dotspacemacs-folding-method #14047
