### ISSUE TITLE
dotspacemacs/user-config run after file is loaded

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#3233]
When Emacs is started with, for example `emacs main.cpp`, `dotspacemacs/user-config` is run after the file is loaded, so c++-mode hooks added in `dotspacemacs/user-config` don't get run.

**Comment by syl20bnr** [comment]
I think this is because of the changed hook from `after-init-hook` to `emacs-startup-hook`.

emacs-startup-hook:

> Normal hook run after loading init files and handling the command line.

after-init-hook

> Normal hook run after initializing the Emacs session.

cc @vkz

**Comment by StreakyCobra** [comment]
@syl20bnr Maybe you want to milestone this on for 0.105?

**Comment by syl20bnr** [comment]
Pretty sure this bug is fixed in 0.200 :-D

**Comment by hrldcpr** [comment]
As discussed in #7202, as far as I can tell this is no longer fixed or was never actually fixed.
