### ISSUE TITLE
helm-projectile-ag doesn't work as helm-ag

### ISSUE THREAD

**Issue by zsoltika** [syl20bnr/spacemacs#3235]
I'm on Windows, with GNU Emacs Windows version installed (and cygwin tools, like git, bash, but not emacs) and latest ˛`latest` spacemacs version every package is up-to-date.

I have to search large project directories (mainly `.java`/`.(PL)sql` files. This requires a lot of `ag` usage (before `spacemacs` I had used CLI `ag` with `vim`). 

Now with `spacemacs`, if I use `helm-projectile-ag`, the result set appears as:

    LINE NRx: matching line
    LINE NRy: matching line

The problem (and bug) with this, is that if I hit `<ENTER>` on a match a new empty buffer gets created with the `LINE NR(n)` as its' name.

However with `helm-ag`:

    FILENAME:LINE NRx: matching line
    FILENAME:LINE NRy: matching line

If I hit `<ENTER>` on a match on this list, the proper file gets opened (at the proper line position).

**Comment by justbur** [comment]
Do any other of the ag commands work? From what you've said here, my guess is that you are using a cygwin version of ag and the paths are not getting converted correctly. 

My suggestion would be to try https://github.com/monochromegane/the_platinum_searcher as a native installation on windows (not cygwin)

**Comment by justbur** [comment]
I can help you get a native installation of ag setup too. It's just a little more involved. I have a working setup for ag on Windows that doesn't have this problem

**Comment by zsoltika** [comment]
I did copy pt.exe to my `/usr/local/bin` under cygwin and symlinked it as `ag`. Now I'm getting an `apply: Spawning child process: exec format error` message :-(

**Comment by justbur** [comment]
You're not using Cygwin emacs right? Just put pt in your windows path, look for the variable `dotspacemacs-search-tools` in the dotfile and put pt first. Then you can use `SPC s p` to search a project with pt

**Comment by justbur** [comment]
It's your choice, but it's possible to avoid using cygwin tools outside of cygwin and you avoid these path translation problems. I stopped using cygwin tools for things like this a long time ago.

**Comment by zsoltika** [comment]
Now this got weird. I did copy `pt.exe` to the very first folder in my `exec-path` (which is the same as the first dir in my windows `PATH`. Set `dotspacemacs-search-tools` in the dotfile and put `pt` first. Restarted `emacs`. When I do a `helm-projectile-ag` now, still an `ag.exe` pops up in the windows process list(?). The same is true for `helm-ag`.

**Comment by justbur** [comment]
Sorry `helm-projectile-ag` and `helm-ag` will both run `ag` by default. You have to use the spacemacs versions to get the selection in `dotspacemacs-search-tools`. The spacemacs versions are listed under `SPC s`. You can also force the pt selection with the commands under `SPC s t`

**Comment by justbur** [comment]
you can also modify `helm-ag-base-command` to use pt. That would be the "non-spacemacs" way to do it.

**Comment by zsoltika** [comment]
You don't have to appologize :-) morover thanks for your help! It's much better to use and memorize shorter (`spacemacs`-default) keybindings. Now I can use `SPC /` which did not work either for me! One more time thanks for taking the time to help me out, this ticket could be either closed or reported upstream (since helm-projectile-ag is still not usable with this environment setup) IMO.

**Comment by justbur** [comment]
Great I don't have the ability to close it so you'll have to. 

I'm not sure it'll go anywhere reporting this upstream but it couldn't hurt. ag works for me with those commands but I don't use a Cygwin version so I think it has something to do with the fact that it's Cygwin. Different paths or something like that.

**Comment by syohex** [comment]
@zsoltika Hi, I'm author of `helm-ag`. Could you show me value of `helm-ag--last-command` after your issue occurred ? You can see it by `M-x eval-expression [RETURN] helm-ag--last-command [RETURN]` This is list of command which is last executed. And could you show me output of these command from command line(`cygwin`) if feasible ?

**Comment by zsoltika** [comment]
@syohex first of all thanks for your work (as a long time Vimer, now I get used to see the Emacs potential and it is only the beginning!):
This is the result after `helm-projectile-ag`:

    ("ag" "--nocolor" "--nogroup" "--line-numbers" "--ignore" "TAGS" "--ignore" ".#*" "--ignore" "*.o" "--ignore" "*~" "--ignore" "*.bin" "--ignore" "*.bak" "--ignore" "*.obj" "--ignore" "*.map" "--ignore" "*.ico" "--ignore" "*.pif" "--ignore" "*.lnk" "--ignore" "*.a" "--ignore" "*.ln" "--ignore" "*.blg" "--ignore" "*.bbl" "--ignore" "*.dll" "--ignore" "*.drv" "--ignore" "*.vxd" "--ignore" "*.386" "--ignore" "*.elc" "--ignore" "*.lof" "--ignore" "*.glo" "--ignore" "*.idx" "--ignore" "*.lot" "--ignore" "*.fmt" "--ignore" "*.tfm" "--ignore" "*.class" "--ignore" "*.fas" "--ignore" "*.lib" "--ignore" "*.mem" "--ignore" "*.x86f" "--ignore" "*.sparcf" "--ignore" "*.dfsl" "--ignore" "*.pfsl" "--ignore" "*.d64fsl" "--ignore" "*.p64fsl" "--ignore" "*.lx64fsl" "--ignore" "*.lx32fsl" "--ignore" "*.dx64fsl" "--ignore" "*.dx32fsl" "--ignore" "*.fx64fsl" "--ignore" "*.fx32fsl" "--ignore" "*.sx64fsl" "--ignore" "*.sx32fsl" "--ignore" "*.wx64fsl" "--ignore" "*.wx32fsl" "--ignore" "*.fasl" "--ignore" "*.ufsl" "--ignore" "*.fsl" "--ignore" "*.dxl" "--ignore" "*.lo" "--ignore" "*.la" "--ignore" "*.gmo" "--ignore" "*.mo" "--ignore" "*.toc" "--ignore" "*.aux" "--ignore" "*.cp" "--ignore" "*.fn" "--ignore" "*.ky" "--ignore" "*.pg" "--ignore" "*.tp" "--ignore" "*.vr" "--ignore" "*.cps" "--ignore" "*.fns" "--ignore" "*.kys" "--ignore" "*.pgs" "--ignore" "*.tps" "--ignore" "*.vrs" "--ignore" "*.pyc" "--ignore" "*.pyo" "--ignore" ".idea/" "--ignore" ".eunit/" "--ignore" ".git/" "--ignore" ".hg/" "--ignore" ".fslckout/" "--ignore" ".bzr/" "--ignore" "_darcs/" "--ignore" ".tox/" "--ignore" ".svn/" "--ignore" ".stack-work/" "--ignore" "SCCS" "--ignore" "RCS" "--ignore" "CVS" "--ignore" "MCVS" "--ignore" ".svn" "--ignore" ".git" "--ignore" ".hg" "--ignore" ".bzr" "--ignore" "_MTN" "--ignore" "_darcs" "--ignore" "{arch}" "--" "vo_error" "./")

I can assure you, that within the `./` directory (a not so large SVN repo) there are `.pks` PLSQL files which contains "`vo_error`" however the popped up(!) results were in the format as `linenumber:match` on which if I hit `ENTER` a new buffer (name == `linenumber` as described above) was created.

And this was the result after `helm-ag`, same `vo_error` pattern, same directory:

    ("ag" "--nocolor" "--nogroup" "--line-numbers" "vo_error")

and this normally popped up a list (with `filename:linenumber:match` format (and I can use `ENTER` in the list the matching file got open on the matching line).

**Comment by syohex** [comment]
@zsoltika Which ag do you use ? Compiled on Windows or Cygwin ?

**Comment by zsoltika** [comment]
It was compiled by myself via Cygwin (since I used to use it in terminal sometimes too - although I'm drifting towards eshell...)

**Comment by syohex** [comment]
Thanks for information. I'll test.

**Comment by syohex** [comment]
@zsoltika I confirmed your issue. Could you try again after adding following configuration to your init.el.

```lisp
(setq helm-ag-base-command "ag --nogroup --nocolor --vimgrep")
```

**Comment by syohex** [comment]
And I confirmed there is no problem if `pt`(the platinum searcher) is used.

**Comment by syohex** [comment]
I have changed that helm-ag sets `--vimgrep` option for Windows(https://github.com/syohex/emacs-helm-ag/pull/176)

**Comment by zsoltika** [comment]
@syohex thanks for the fix, now (after setting `helm-ag-base-command` as advised) it works as expected!
