### ISSUE TITLE
Can't type numbers into helm-find-files

### ISSUE THREAD

**Issue by jneen** [syl20bnr/spacemacs#3237]
To reproduce: `SPC f f` (or `M-x helm-find-files`), type any number 0-9

Expected: the number appears in the search query string

Actual: The nth helm action is run.

The offending code seems to be here:

https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs-base/packages.el#L786

Would it be possible just to delete this, or rebind with a prefix (say, `C-c`)?

**Comment by TheBB** [comment]
You may have accidentally enabled the [Helm micro-state](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#helm-micro-state).

**Comment by syl20bnr** [comment]
@jneen Thank you for the report :+1: 

Seems that the micro-state kicked in and then the state was not reverted for some reason.
I may be able to better isolate those mappings by leveraging Evil (something like the simplification for evilified buffer).

**Comment by jneen** [comment]
If so it was definitely accidental.  But if I intentionally activate the helm micro-state, every subsequent helm I open executes it outside of the micro-state.

**Comment by jneen** [comment]
:]

**Comment by icambron** [comment]
@jneen see also #2020
