### ISSUE TITLE
Add a SPARQL mode

### ISSUE THREAD

**Issue by Dietr1ch** [syl20bnr/spacemacs#3242]
There is currently no extended support for SPARQL. Although it's use it's far from massive it would be nice to add support at least for highlighting.
I think that this should be done on `extra-langs` until a new Query Language Layer is created grouping support for SQL, SPARQL and other NoSQL modes (Neo4j, MongoDB, CouchDB, ArangoDB (AQL), OrientDB, ...)
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.2
- Spacemacs branch: nil (rev. 074f425)
- Distribution: spacemacs
- Layers:

``` elisp
(auto-completion syntax-checking c-c++ clojure d emacs-lisp haskell html javascript latex markdown python ruby rust scala sql colors
                 (git :variables git-enable-github-support t git-gutter-use-fringe t)
                 version-control gtags org
                 (shell :variables shell-default-width 120 shell-default-height 30 shell-default-position 'right shell-default-term-shell "/bin/zsh"))
```

**Comment by robbyoconnor** [comment]
Can't hurt to just make a PR -- worst case scenario you move the directory :stuck_out_tongue_winking_eye:

**Comment by Dietr1ch** [comment]
I'm looking on how to contribute ;), but I'm new on EMACS.

I don't want to miss something important while just adding more packages to the list, I suppose I may break things if I don't review what is actually being done.

**Comment by robbyoconnor** [comment]
@Dietr1ch pop onto the gitter chat -- we have a [guide for that](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONTRIBUTE.org) ;)

**Comment by fleimgruber** [comment]
https://github.com/syl20bnr/spacemacs/pull/3248 says it fixes this.  This was put into `+lang/extra-langs` which was later moved to `+lang/major-modes`.  sparql-mode is missing from there though.  I will try to patch with #3248 there.

**Comment by fleimgruber** [comment]
This is obsolete as sparql-mode is in http://develop.spacemacs.org/layers/+lang/semantic-web/README.html
