### ISSUE TITLE
Emacs opens in scratch buffer in daemon mode

### ISSUE THREAD

**Issue by Immortalin** [syl20bnr/spacemacs#3244]
Emacs always open in the scratch buffer instead of the default spacemacs buffer when ran in daemon mode and accessed using emacsclient via the command "emacslient -c".

**Comment by robbyoconnor** [comment]
Did you read the guidelines which github linked? This is very insufficient. 

`SPC hds` please.

**Comment by Immortalin** [comment]
@robbyoconnor oops sorry

**Comment by Immortalin** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 9e794df)
- Distribution: spacemacs
- Layers:
```elisp
(shell :variables shell-default-shell 'term)
```

**Comment by TheBB** [comment]
Isn't this standard Emacs behaviour?

**Comment by robbyoconnor** [comment]
@Immortalin [CONTRIBUTING.md](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.md) -- it was linked when you opened this issue...we expect you to read it.

**Comment by TheBB** [comment]
This sets the initial buffer for clients. Put this in your `.spacemacs`.

```lisp
(setq initial-buffer-choice
      (lambda ()
        (get-buffer "*spacemacs*")))
```

**Comment by TheBB** [comment]
I made a PR for this: #3257.

**Comment by Immortalin** [comment]
@TheBB thanks!

**Comment by StreakyCobra** [comment]
#3257 is in `develop` now, marking it as `Fixed in develop` then
