### ISSUE TITLE
Org export fails with #+Title and #+Author

### ISSUE THREAD

**Issue by rrottier** [syl20bnr/spacemacs#3246]
After updating to the latest Spacemacs org export started failing for any Latex export with a #+TITLE or #+AUTHOR field.  

I did a fresh clone and install of Spacemacs 0.104.2 but this did not help.  The error message is:

```
Wrong type argument: listp, #("201424155" 0 9 (:parent (#0)))
```

It seems somewhat related to #3121 but did not resolve with the reinstall as for the original poster.

**Comment by robbyoconnor** [comment]
Thank you for the report, please when you report a bug like this, ***ALWAYS*** include output of `SPC hds`

**Comment by rrottier** [comment]
Sorry, done now.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.104.2
- Spacemacs branch: master (rev. 074f425)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion emacs-lisp git markdown latex org osx
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control)
```

**Comment by robbyoconnor** [comment]
did you test this in `develop`? I just did and it worked.

**Comment by robbyoconnor** [comment]
Here is my `SPC hds` output: 

#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 9e794df)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-show-snippets-in-popup t)
 better-defaults emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 github gnus version-control markdown syntax-checking
 (latex :variables latex-enable-auto-fill t)
 (colors :variables colors-enable-rainbow-identifiers t colors-enable-nyan-cat-progress-bar t)
 dockerfile ansible puppet evil-commentary
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 fasd finance floobits xkcd autohotkey
 (c-c++ :variables c-c++-enable-clang-support t)
 (clojure :variables clojure-enable-fancify-symbols t)
 extra-langs go
 (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "andrew-gibiansky")
 html java javascript
 (python :variables python-enable-yapf-format-on-save t)
 racket
 (ruby :variables ruby-version-manager `rvm)
 ruby-on-rails rust scala shell-scripts restclient themes-megapack tmux vim-empty-lines spotify pandoc vagrant
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 semantic deft
 (shell :variables shell-default-shell 'eshell shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh")
 typescript
 (eyebrowse :variables eyebrowse-display-help t)
 (perspectives :variables perspective-display-help t)
 erc chrome d extra-langs smex emoji gtags prodigy evernote
 (org :variables org-enable-github-support t)
 search-engine evil-little-word yaml sql nim ipython-notebook lua scheme purescript sml common-lisp ranger wakatime dash spell-checking jabber deft cscope vinegar unimpaired rcirc games react)
```

**Comment by robbyoconnor** [comment]
Here is my testing file
```
#+TITLE: Testing 123
#+AUTHOR: Robert O'Connor 
* Hi 
** Hey
```

Here is the associated generated TeX: 

```latex
% Created 2015-10-03 Sat 04:21
\documentclass[11pt]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{fixltx2e}
\usepackage{graphicx}
\usepackage{grffile}
\usepackage{longtable}
\usepackage{wrapfig}
\usepackage{rotating}
\usepackage[normalem]{ulem}
\usepackage{amsmath}
\usepackage{textcomp}
\usepackage{amssymb}
\usepackage{capt-of}
\usepackage{hyperref}
\author{Robert O'Connor}
\date{\today}
\title{Testing 123}
\hypersetup{
 pdfauthor={Robert O'Connor},
 pdftitle={Testing 123},
 pdfkeywords={},
 pdfsubject={},
 pdfcreator={Emacs 24.4.1 (Org mode 8.3.2)}, 
 pdflang={English}}
\begin{document}

\maketitle
\tableofcontents

\section{Hi}
\label{sec:orgheadline2}
\subsection{Hey}
\label{sec:orgheadline1}
\end{document}
```

And the PDF output: 
![image](https://cloud.githubusercontent.com/assets/23088/10262079/e185a292-6986-11e5-82b3-07953e4e8d6a.png)

**Comment by robbyoconnor** [comment]
I suspect this is a case of not having the proper executables on your system...if I am wrong, I'll accept that but I'm not sure I am in this case...

**Comment by rrottier** [comment]
Switched to develop:

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: nil (rev. 9e794df)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion emacs-lisp git markdown latex org osx
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control)
```

Works now, I had tried it before but this time also trashed my elpa directory.  Thanks

**Comment by robbyoconnor** [comment]
I'd love to know what the issue is...

**Comment by robbyoconnor** [comment]
I just looked, there are literally no commits in `develop` that changed the `org` layer..so I'm curious what would cause this...

**Comment by TheBB** [comment]
If he also upgraded the packages when he switched to develop, that's probably what solved it.

**Comment by robbyoconnor** [comment]
That could do it...whatever packages he was using, must have been ancient...

**Comment by rrottier** [comment]
I have no idea what it was but it could not have been a package upgrade.  I deleted the entire .emacs.d folder for both the 0.104 install and the 0.105 install and cloned the repo again.  I tried to update from 0.104 to 0.105 in place and this did not resolve the issue.  Then I posted this issue and after robbyoconnor's comment I tried again this time wiping the folder and resyncing.

I just looked through the entire changelist and there is nothing that looks like it explains while this works.  But also looking at #2856 it seems like the issue can disappear and re-appear by itself.

**Comment by robbyoconnor** [comment]
In the future before you wipe your entire install -- try updating packages by clicking the `[Update]`' button on the home directory...if you are away from it...type `SPC b h` -- another way to do it is to wipe `elpa/`, but it's the more radical solution -- updating packages will work just as well.

**Comment by rrottier** [comment]
Sure thing.  That would be my normal way of updating but I was getting desperate...

**Comment by jm2dev** [comment]
After installing spacemacs I cannot export orgmode files which start with the TITLE tag. I experienced this issue when I loaded org layer.

Sample document that doesn't export to anything, I tried html and utf-8 text.
```
#+TITLE: Sample title
* Overview
Lorem ipsum
```

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp git org scala python)
```

**Comment by jm2dev** [comment]
As per issue #3314 and following @liangwang recommendation I deleted all org-* directories under $HOME/.emacs.d/elpa and restarted Emacs. I was able to export again orgmode files with title tag.

**Comment by dmusican** [comment]
Confirmed that the solution from @jm2dev worked for me.

**Comment by Emiluren** [comment]
Worked for me too :smile:

**Comment by joshcho** [comment]
I am getting this error again. Anyone have any idea why this is happening?

**Comment by jonpither** [comment]
Getting this error also.

**Comment by diadochos** [comment]
I have this since yesterday too. I've re-installed all `org-`, `ob-`, and `ox-` libraries.

### Procedure to reproduce
#### Minimum working example
1. Create `test.org` with the content below:
```
#+TITLE: Foo
```
2. `M-x org-latex-export-as-latex`
#### What I get
- The export stops there (Emacs does not halt)
- An error in the `*Messages*` buffer:
`apply: Wrong type argument: listp, #("Foo" 0 3 (:parent (#0)))`

### My info
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv bibtex
     (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-private-snippets-directory "~/.emacs.d.bak/snippets/")
     better-defaults ipython-notebook emacs-lisp
     (org :variables org-enable-github-support t)
     osx spell-checking syntax-checking
     (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rbenv ruby-test-runner 'rspec)
     python javascript latex yaml php gtags ess version-control git html clojure extra-langs dash docker my-keybindings my-config-from-spacemacs-base realgud)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by angry-bird** [comment]
same errer here, and also i have the similar problem when using ```org-ref``` to ```get bibtex entry ```: ```doi-link-menu: Wrong number of arguments: #[(doi bibfile) blablablabla...```
 And all these problems are related to my org updating, and i guess there are many other tiny tricky problems with org 9.0, even with ```with-eval-after-load``` in ```.spacemacs```

**Comment by shersk2** [comment]
I get the same error. Is there some workaround for this so I can export documents until the bug is fixed? Or will I have to reinstall Emacs?

**Comment by diadochos** [comment]
@angry-bird @shersk2
Upgrade to the latest version, and try commenting out org-mode settings in your personal .emacs.d .
(i.e. use the latest org-mode with the default settings of spacemacs)
In my case the problem is gone. I'll try to figure out which part of my config is causing the problem, when I get the time.

**Comment by angry-bird** [comment]
@diadochos Thanks! I removed all folders under ~.emacs.d/elpa/~, and now it works fine.

**Comment by alecstein** [comment]
The problem appeared for me immediately upon installing `org-ref`. I tried uninstalling `org-ref` but the issue stuck around. Once I removed my `org` folder I was able to use the `#+TITLE` tag again.

**Comment by adimit** [comment]
I am not sure why this issue is closed. I can reproduce it with the current develop HEAD and all recent packages, no user configuration, all executables that need to be present, etc. Deleting `org-ref` is not an option for me, as I do need it.

My reproduction instructions:
- clone spacemacs repo to `.emacs.d`, switch to `develop`
- don't have a `~/.spacemacs`, just install everything with a default setup
- export an org-mode file with `#+TITLE:` or `#+AUTHOR:` set to LaTeX
I'm getting `Wrong type argument: listp, #("My title…" 0 89 (:parent (#0)))`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. e11f7bad)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp neotree)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS

**Comment by Atman50** [comment]
Me too. Seems to have broken recently. Completely removed elpa, reloaded. Getting org from https://orgmode.org/packages.
Seems to always fail with #+TITLE or #+AUTHOR

**Comment by reconmaster** [comment]
I am also getting the same issue with #+AUTHOR and then #+TITLE after removing the #+AUTHOR entry. Fresh .emacs.d/elpa as well. Definitely would like to know why this happened and how to fix. Current version being pulled is:

release_9.1.7-18-g2f587d

**Comment by glumanda99** [comment]
Same issue :crying_cat_face: 

The solution of @jm2dev works tho.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.3.1
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a7)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(html ivy auto-completion better-defaults emacs-lisp git markdown mu4e org finance syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by xanalogica** [comment]
Oddly I have it here only when I use #+TITLE: but if I use #+TITLE (without the colon) it works and I also get the correct title displayed.  All my other #+BLAH: lines have colons, just not TITLE.

And the syntax coloring for my .org buffer is showing the error color on my #+TITLE: line but when I remove the trailing colon the color switches to non-error.  And all the other #+BLAH: lines (with colon) are showing with the correct non-error color.

I can live without the trailing colon but it is mystifying.

Running emacs 25.3-r4:25 under Gentoo Linux.

**Comment by harlandski** [comment]
As far as I can see the problem lies somewhere in org-plus-contribs. I recently installed org-plus-contrib-20180611 on GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11), and immediately encountered the problems described with exporting #+TITLE: #+DATE: and #+AUTHOR:. If I remove this directory, then export works as normal again. The workaround with removing the colons does not work for me.

**Comment by irbin-b** [comment]
I have updated my emacs libraries and remove unnecessary with M-x package-autoremove. After this restart emacs, and the export works fine.

**Comment by gkbio** [comment]
I got this problem when I upgraded my Org package from the default version. 

I fixed the problem without deleting any org folders and just by reloading uncompiled org.

**System Config:**
I am running WSL on windows 10 - > Emacs 25.3.2 and Org 9.1.14 

**Solution:**

> Emacs File Menu -> Org -> Refresh/Reload ->**Reload Org Uncompiled  C-u C-c C-x !**

**Comment by mijail73** [comment]
This worked for me.
Best way that I have seen to work is to delete (M)Elpa installed Org completely and install it again, but in an emacs -Q session, or do _C-u M-x org-reload_, and then delete->reinstall Org.
[https://www.reddit.com/r/emacs/comments/6jeu74/getting_error_exporting_org_doc_because_it_has/](url)
