### ISSUE TITLE
Add evil-matchit

### ISSUE THREAD

**Issue by ctjhoa** [syl20bnr/spacemacs#325]
Hi all,
Since vim 6.0, matchit.vim has been included in the standard vim distribution.
Even [tpope/vim-sensible] (https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim) load the plugin by default for older vim version.

It could be great to integrate [evil-matchit](https://github.com/redguardtoo/evil-matchit) to spacemacs.

Thanks

**Comment by ctjhoa** [comment]
@syl20bnr we can base it on the [official vim plugin](http://www.vim.org/scripts/script.php?script_id=39), web-mode and latex seems to be the most popular usage in my opinion.

Lua, shell are relevant choices too.

**Comment by syl20bnr** [comment]
Added in develop branch, activated for `web-mode` and `auctex`, will be in next release 0.48.0

**Comment by syl20bnr** [comment]
0.48.0 is now live, closing this issue.
