### ISSUE TITLE
Break out evilified state

### ISSUE THREAD

**Issue by justmytwospence** [syl20bnr/spacemacs#3252]
Spacemacs' evilified state is very useful for general users of evil-mode outside of Spacemacs users. I myself don't want to run Spacemacs, but would love it if there was a package on melpa that would give me easy access to the evilified state macro. I've noticed a general trend toward breaking out useful pieces of Spacemacs functionality, and thought I might as well put in a request.

**Comment by TheBB** [comment]
Yes, this would be very useful for a lot of people and shouldn't be very difficult I suspect. It will have to be loaded in the bootstrap process, of course.

**Comment by syl20bnr** [comment]
I think it is now in a "packageable" shape, I'll look into it.

**Comment by TheBB** [comment]
I'm willing to do some of the lifting, but you should own the repo.

**Comment by syl20bnr** [comment]
I'll setup a first extraction. Maybe configuring the package as a pre-step will be sufficient to make it available soon enough.

**Comment by bling** [comment]
:+1: 

i just copied `evil-evilified-state.el` deleted references to `dotspacemacs-leader-key`, evaled it, and it works like a charm!

**Comment by sooheon** [comment]
This would still be very much appreciated ;)

**Comment by bling** [comment]
@syl20bnr @TheBB any thoughts on this?  a lot has happened since and evil is on github now, so it should be much easier getting this merged into upstream evil so non spacemacs users can benefit.
