### ISSUE TITLE
Useful buffer list

### ISSUE THREAD

**Issue by user471** [syl20bnr/spacemacs#3255]
Is there any way to show list of only useful buffers? Similar to ```SPC b b``` but without special buffers

**Comment by person808** [comment]
You can add regexes to `helm-boring-buffer-regexp-list`. You could also do `(setq helm-boiring-buffer-regexp-list spacemacs-useless-buffers-regexp)` but that will hide some useful buffers because of the default value of `spacemacs-useless-buffers-regexp`.

**Comment by user471** [comment]
What is the difference between special/useless buffers and boring buffers?
Can I somehow use "helm-boring-buffer-regexp-list" only with special key binding? Something like this
```
 (evil-leader/set-key "bl" show-buffers-with-boring-filter)
```
So I could still use ```SPC b b``` for all buffers?

**Comment by robbyoconnor** [comment]
Assuming you do not remap it -- Yes.

**Comment by person808** [comment]
> What is the difference between special/useless buffers and boring buffers?

They are effectively the same thing, buffers that most users would want to ignore. They are defined by different variables (`spacemacs-useless-buffer-regexp` and `helm-boring-buffer-regexp-list`)

> Can I somehow use "helm-boring-buffer-regexp-list" only with special key binding? 

```elisp
(defun helm-mini-filtered ()
  (let ((helm-boring-buffer-regexp-list '(REGEX here))
    (helm-mini))
(evil-leader/set-key "bl" 'helm-mini-filtered)
```

**Comment by user471** [comment]
>They are effectively the same thing, buffers that most users would want to ignore. 

Why did Spacemacs create its own variable instead of using helm-boring-buffer-regexp-list?

I added this to dotspacemacs/user-config
```
(defun helm-mini-filtered ()
		(let ((helm-boring-buffer-regexp-list 'spacemacs-useless-buffers-regexp)
					(helm-mini))))
(evil-leader/set-key "bl" 'helm-mini-filtered)
```
But it return an error ```Wrong type argument: commandp, helm-mini-filtered```
I tried to add (interactive) but it doesn't help.

**Comment by TheBB** [comment]
Your let form is ill formed. Also you shouldn't quote `spacemacs-useless-buffers-regexp`. This should work.

(defun helm-mini-filtered ()
  (interactive)
  (let ((helm-boring-buffer-regexp-list spacemacs-useless-buffers-regexp))
    (helm-mini)))
(evil-leader/set-key "bl" 'helm-mini-filtered)

**Comment by user471** [comment]
@TheBB thanks. Do you think such function could be useful for everyone?

**Comment by TheBB** [comment]
I would rather configure `helm-boring-buffer-regexp-list` directly, and use another way to reach a 'boring' buffer, if that should be necessary.
