### ISSUE TITLE
Command to open file external application

### ISSUE THREAD

**Issue by danielwuz** [syl20bnr/spacemacs#326]
Is there any command in spacemacs to open file in system default application? For example, when I edit html file, I'd like to be able to open it in a browser.

I can make a PR if we don't have similar function yet.

**Comment by syl20bnr** [comment]
@danielwuz is it ok for this question ?

**Comment by tuhdo** [comment]
If you use `helm-find-files`, `C-c C-x` prompts for an external application from the list of all applications seen by Emacs. Once you choose, `helm-find-files` remembers that choice the next time you open file of that type until you run the command with prefix argument, then you will be prompted again.

**Comment by syl20bnr** [comment]
Thank you @thudo for the precision, `helm` is almost like an app launcher then, this package will never stop to surprise me.

**Comment by a13ph** [comment]
just for reference, there's also emacs-friends package

**Comment by pietrodito** [comment]
> If you use `helm-find-files`, `C-c C-x` prompts for an external application from the list of all applications seen by Emacs. Once you choose, `helm-find-files` remembers that choice the next time you open file of that type until you run the command with prefix argument, then you will be prompted again.

Is there anyway to do that in one keystroke from a dired buffer?

**Comment by pietrodito** [comment]
> > If you use `helm-find-files`, `C-c C-x` prompts for an external application from the list of all applications seen by Emacs. Once you choose, `helm-find-files` remembers that choice the next time you open file of that type until you run the command with prefix argument, then you will be prompted again.
> 
> Is there some way to do that in one keystroke from a dired buffer?

Ok I have found that `W` do the trick...
