### ISSUE TITLE
User assignment of private directory

### ISSUE THREAD

**Issue by rubic** [syl20bnr/spacemacs#3261]
The spacemacs private directory is effectively hard-coded to ```~/.emacs.d/private```.  It would be useful to allow the user to assign it to a different directory (e.g. ```~/.spacemacs.d```) to keep private layers, bookmarks, snippets, etc. out of ~/.emacs.d, which is effectively "owned" by spacemacs.

Snippets and bookmarks directories can currently be reassigned via:

 * ```bookmark-default-file```
 * ```auto-completion-private-snippets-directory```

But there is no way to specify a separate private layers directory.

**Comment by justbur** [comment]
See https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#alternative-setup

**Comment by rubic** [comment]
@justbur I understand that private is ignored by git, but I'd prefer to have my private configuration files outside of the ~/.emacs.d directory structure.

**Comment by justbur** [comment]
Just put them in `~/.spacemacs.d/` if they're layers you can add the base path to `dotspacemacs-configuration-layer-path`. There's already support for what you're asking for, unless I'm misunderstanding.

I don't use source control. I just use Dropbox. My setup is roughly
```
export SPACEMACSDIR=~/Dropbox/spacemacs
```
```elisp
(auto-completion
:variables
auto-completion-private-snippets-directory
"~/Dropbox/spacemacs/snippets/")
```
My dotfile is `~/Dropbox/spacemacs/init.el` and my private layers are in `~/Dropbox/spacemacs/layers/`

Is there something you're doing in private that's not covered by this?

**Comment by rubic** [comment]
@justbur I totally missed ```dotspacemacs-configuration-layer-path```.  That would solve the issue of private layers.  Thanks.

**Comment by justbur** [comment]
By the way if you use a spacemacs directory spacemacs will search it recursively for layers in it by default.
