### ISSUE TITLE
Org-table : Symbol's value as variable is void: org-planning-line-re using 0.104.2

### ISSUE THREAD

**Issue by jonesberg** [syl20bnr/spacemacs#3262]
Using the new `org` layer with spacemacs, whe you're in a table, pressing `[tab]` cause the following error :  

`Symbol's value as variable is void: org-planning-line-re`

How to reproduce :
- Put the `org` layer in your .spacemacs (I placed it first, to make sure org wasn't prematurely loaded from another layer)
- Create a table in an org buffer
- Press `[tab]`

How to get a sensible behavior :
- Remove the org layer and restart Spacemacs
- Create a table in an org buffer
- Press `[tab]`

The org-version is different depending on the case (unsurprisingly) :

With org-layer : Org-mode version 8.2.10 (release_8.2.10 @ /home/jonathan/.emacs.d/elpa/org-20150929/)
Without org-layer : Org-mode version 8.2.10 (release_8.2.10 @ /usr/share/emacs/24.5/lisp/org/)

Checking this, my hunch would be that spacemacs calls org-mode before loading the layer
https://lists.gnu.org/archive/html/emacs-orgmode/2014-09/msg00224.html

I don't know if this could help.

**Comment by robbyoconnor** [comment]
`SPC hds` please.

**Comment by robbyoconnor** [comment]
Just for completeness...try in `develop` to see if it's still an issue...I don't see this issue in `develop` -- I suspect it's an issue of you typing before everything is fully loaded.

**Comment by TheBB** [comment]
I can't reproduce, either. Same org version.

**Comment by robbyoconnor** [comment]
Keep in mind that everything in spacemacs is lazy-loaded

**Comment by syl20bnr** [comment]
Did you try to remove all the org related directories in `elpa` and restart ?

**Comment by jonesberg** [comment]
Good evening everybody,

Removing everything in the elpa directory and restarting did the trick.

What was happening is (thanks to robbyoconnor) I was setting some org-babel things in a private layer (which I know now I shouldn't).

Thank you so much for the rapid answers!

**Comment by robbyoconnor** [comment]
@jonesberg -- what you can do is wait until it's loaded and THEN set the org-babel shit.

**Comment by jonesberg** [comment]
Thank you so much Robby!

Sorry for the distraction. At least this bug report will help if someone runs through a similar issue.

**Comment by robbyoconnor** [comment]
every report helps -- even if it's invalid on its basis.

**Comment by skinney6** [comment]
I'm having the same problem even after removing elpa directory and restarting (2x).
```
(auto-completion better-defaults emacs-lisp games git github ibuffer latex markdown org python
                 (shell :variables shell-default-height 30 shell-default-shell 'eshell shell-default-position 'bottom)
                 spell-checking syntax-checking themes-megapack yaml)

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
elisp
(auto-completion better-defaults emacs-lisp games git github ibuffer latex markdown org python
                 (shell :variables shell-default-height 30 shell-default-shell 'eshell shell-default-position 'bottom)
                 spell-checking syntax-checking themes-megapack yaml)


Information has been copied to clipboard.
You can paste it in the gitter chat.
Check the *Messages* buffer if you need to review it
```

**Comment by TheBB** [comment]
Can I see your dotfile? I want to see if you are also inadvertently loading org before you should.

**Comment by skinney6** [comment]
Here is a gist of my [.spacemacs](https://gist.github.com/skinney6/ae7af01f737b6590549d) or should I dump the file contents here?

**Comment by TheBB** [comment]
Hm, no, I don't see anything bad.

**Comment by skinney6** [comment]
I restarted emacs again and orgs working now. Third times a charm? .. i guess. Thanks for looking. And thanks for the spacemacs youtube vids. I'm going thru them now. Well done!

**Comment by agzam** [comment]
I confirm, I see the same bug when trying to toggle checkboxes, or change tags. Basically anything related to `C-C C-C` hook is not working!

**Comment by cyberthal** [comment]
I also had to delete and reinstall elpa.  Then it worked.
