### ISSUE TITLE
Wrong $PATH in GUI Emacs

### ISSUE THREAD

**Issue by d12frosted** [syl20bnr/spacemacs#3268]
Hey, 

I am having troubles with value of `$PATH` in GUI Emacs. Calling `(shell-command-to-string "echo $PATH")` in GUI returns different value than calling this in terminal. Also, when I call `$ env` I see desired value of `$PATH` there. Has anyone encountered anything similar?

I am on OS X 10.11 (15A284), `emacs-24.5-z-mac-5.11`. Tested on 'bare' `.spacemacs` file.

**Comment by robbyoconnor** [comment]
This is an OSX issue I believe and not found in Linux (I can't speak for windows)

**Comment by d12frosted** [comment]
Hm. Tried with regular `emacs` (HEAD) - it works. Probably something is broken with `emacs-mac` and El Capitan.

FYI, `GNU Emacs 25.0.50.1` works like a charm with Spacemacs right now. There are two warning at startup, but other than this - everything is fine.

**Comment by syl20bnr** [comment]
What are the differences between the two PATH values exactly ? It should give us an hint about what is happening.

**Comment by d12frosted** [comment]
The difference is that `emacs-mac` GUI shows me the default `$PATH`. While it should contain some appended values like `~/.local/bin` etc.

But as I told it's only in `emacs-mac` GUI. In `emacs-mac` in terminal, in `emacs 25.0.50.1` GUI / nonGUI everything is fine. 

I was on fresh install of El Capitan, installed brew, and then `emacs-mac` (and some other tools required at runtime for different modes). And then I realised that emacs doesn't see those executables. Tried from terminal - but couldn't reproduce. Tried again in GUI - the problem haven't gone anywhere. Then I uninstalled `emacs-mac` and installed `emacs --HEAD`. Now it works perfectly both in GUI and Terminal. 

If you need more information on this issue - just ask me :smile:

**Comment by syl20bnr** [comment]
So `emacs-mac` only sees the default PATH. In which file(s) are you setupping your PATH ?

**Comment by d12frosted** [comment]
I am setting my `PATH` variable in `config.fish` file. I am using `set -x`, so it's exported to environment. So when I call `$ env` I see the desired value of `$PATH` (with `~/.local/bin`).

**Comment by syl20bnr** [comment]
Can you duplicate it in `~/.bashrc` or whatever bash file you have in your home ?

**Comment by d12frosted** [comment]
Nothing changes. It still doesn't have `~/.local/bin`.

**Comment by syl20bnr** [comment]
In emacs-mac what it the value of `$SHELL` ?

**Comment by d12frosted** [comment]
Also wrong shell. It points to `bash` instead of `fish`. But in `env` I see that my `SHELL` is `fish`.

**Comment by syl20bnr** [comment]
Be sure to put PATH in the correct bash configuration file and it will work.

**Comment by syl20bnr** [comment]
I also use fish but my default shell is still bash, I defined an alias `f` to start fish.

**Comment by d12frosted** [comment]
Ah well, after I installed `emacs`, `emacs-mac` doesn't start properly - it throws errors about something wrong in `init.el`. It's not related to this issue. I am going to test it a bit later, when I am home.

But anyway, when exception is thrown, emacs-mac GUI sees right value of `PATH` (without any modifications to bash config file). 

In any case, I don't think that it should be something related to `bash` config. AFAIK, it gets environment which is not tided to shell. Since running `emacs-mac` in terminal under fish or bash without any configurations works fine, but GUI doesn't work at all - it doesn't look like env problem. I think it could be something with latest version of `emacs-mac`. 

But anyway - I'll test what you asked at home, cause right now don't have ability to mess too much with installations.

**Comment by d12frosted** [comment]
Oh well. Now `emacs` (`HEAD`) is broken as well. And only in GUI version. That's very strange. I tried as you said - updated `~/.bashrc`, but it didn't help.

**Comment by d12frosted** [comment]
Well, it's definitely something strange with OS X. When I run `Emacs.app` from `/usr/local/Cellar/emacs/HEAD` everything is fine. When I run it from Dock - path is all wrong.

**Comment by d12frosted** [comment]
Yeah, that's it indeed. When I run `Emacs.app` from Dock or Launchpad - it's broken. No matter if it's symlink or real app. On the other hand, when I run it from Finder or spotlight - everything works like a charm.

Since it doesn't look like problem on Spacemacs or Emacs side, feel free to close it. But I wonder if someone else can reproduce it. 

P. S. Sorry for spamming :smile_cat:

**Comment by syl20bnr** [comment]
Let's keep it open for now.

**Comment by fintelkai** [comment]
I don't have this issue. Spacemacs develop (whether started from Finder or from Dock), El Capitan, emacs-mac installed via homebrew, zsh shell. I take it the path gets read from my .zshrc via exec-path-from-shell.

**Comment by robbyoconnor** [comment]
@fintelkai what version of emacs? 

What's the HEAD revision on `develop`?

**Comment by fintelkai** [comment]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 3a2bd94)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-use-tab-instead-of-enter t)
 emacs-lisp git
 (haskell :variables haskell-enable-hindent-style "johan-tibell")
 (latex :variables latex-enable-auto-fill nil)
 markdown org osx pandoc
 (python :variables python-enable-yapf-format-on-save t)
 version-control)
```

**Comment by stormpat** [comment]
@d12frosted I have the same issue. Its kind of annoying because in haskell-mode i cannot find ghc-mod. It works fine in the terminal...

**Comment by d12frosted** [comment]
While I am glad to hear that I am not the only one with this problem, it's a pity that you also face this problem.

**Comment by syl20bnr** [comment]
I upgraded to El Capitan but use GNU emacs in XQuartz, I'll try to reproduce it.
To reproduce this I just have to install emacs-mac and launch it ?

**Comment by d12frosted** [comment]
Cool. I've installed emacs using following command:

```
# emac-mac
$ brew install emacs-mac --with-spacemacs-icon --with-gnutls --with-imagemagick
# emacs HEAD
$ brew install emacs --HEAD --use-git-head --with-cocoa --with-gnutls --with-rsvg --with-imagemagick
```

**Comment by d12frosted** [comment]
This was fixed after latest update. Doesn't happen any more. Feel free to close, @syl20bnr.

**Comment by kevincolyar** [comment]
This was fixed after the latest version of spacemacs or OSX?   I'm still having this issue but I'm on Yosemite.

Emacs is loading /etc/paths before my zsh custom paths, so emacs can't see my pyenv python.

**Comment by msuess** [comment]
I am having the same problem as @kevincolyar. For now, I've put all my custom paths into /etc/paths to fix the problem quick-and-dirty.

**Comment by d12frosted** [comment]
I found that the best way (at least for me) to run emacs in GUI on OS X is by running it from terminal. To be accurate I have following fish function to run emacs.

```
function em
  emacs --insecure $argv &
end
```

It can be easily translated to bash function. The main idea of this function is passing all arguments from `em` call to `emacs` and then calling `emacs` asynchronously. 

Also you can create custom runner application using Automator.
