### ISSUE TITLE
ad-Advice-ido-read-internal: Symbol's function definition is void: spacemacs/split-window-horizontally-and-switch

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3272]
To reproduce, type `SPC p y` and then `C-v` (I thought it was going to page down).

`layers/+distribution/spacemacs-base/packages.el` has several references to it, but it has been removed.

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.104.2
- Spacemacs branch: master (rev. 074f425)
- Distribution: spacemacs
- Layers:
```elisp
(unscroll auto-completion emacs-lisp git yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors eyebrowse
          (c-c++ :variables c-c++-enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by syl20bnr** [comment]
related to https://github.com/syl20bnr/spacemacs/issues/3214
