### ISSUE TITLE
load org file with find-file in user-config() does not enable org-evil minor mode

### ISSUE THREAD

**Issue by Xixiao007** [syl20bnr/spacemacs#3276]
I have this code snippet in my user-config() function
``` 
  (find-file "~/org/work-tasks.org")
```
it loads a org file into visible buffer and put the default spacemacs splash buffer into background.
The org file buffer has yasnippet, auto-complete and which-key-mode enabled automatically, but not have evil-org minor model enabled

If I manually load the file into buffer, evil-org mode is enabled. 

I can see the evil-org mode code in spacemacs-helm search:
```
(defun org/init-evil-org ()
  (use-package evil-org
    :commands evil-org-mode
    :init
    (add-hook 'org-mode-hook 'evil-org-mode)
```

**Comment by Xixiao007** [comment]
This seems was caused by something wired in my `.spacemacs` file, I tried @TheBB 's configuration, the issue vanished.. I dont know why, but it seems not spacemacs related bug but my own code. how can I close this issue?

**Comment by robbyoconnor** [comment]
Just click "close issue" ;)
