### ISSUE TITLE
Add FAQ about Org loading limitations

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#3277]
Since Spacemacs uses the org version from the org ELPA repository we must inform users that they should not define Org related stuff that require Org to be loaded before `dotspacemacs/user-config`.

**Comment by robbyoconnor** [comment]
We could just add a note to the README in the org layer. Want me to do that?

**Comment by StreakyCobra** [comment]
(Sorry for the double commit reference)
