### ISSUE TITLE
Python layer: Anaconda's functions are void

### ISSUE THREAD

**Issue by numkem** [syl20bnr/spacemacs#3281]
Hello,

I've been running the latest version of spacemacs and I cannot seem to be able to use any of the anaconda functions in the python layer:

I get stuff like this in my message buffer:
```
command-execute: Symbol's function definition is void: anaconda-mode-show-doc
command-execute: Symbol's function definition is void: anaconda-mode-find-definitions
command-execute: Symbol's function definition is void: anaconda-mode-find-references
command-execute: Symbol's function definition is void: anaconda-mode-find-references
```

Thank you!

**Comment by TheBB** [comment]
Most likely you have an out-of-date version of anaconda mode installed. Please make sure to update your packages (the update button on the home screen).

**Comment by numkem** [comment]
That fixed it indeed. For some reasons I was sure that the packages were updated at the same time as the spacemacs versions.

Thanks!
