### ISSUE TITLE
Improving filter by extension in under `SPC s` [not critical ... yet ]

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#3282]
There are some rough edges with the searching feature :
- [ ] When filtering search in `helm-ag` (for example using `SPC u SPC s f` the first buffers says `helm-grep` and after selecting extensions to be searched it changes to `helm-ag`
- [ ] One cannot do this trick for searching through a project with `SPC s p` maybe because the universal argument is already used by helm-projectile.

I don't know how this might be assessed, any ideas?

**Comment by syl20bnr** [comment]
Weird I believed I fixed it with https://github.com/syohex/emacs-helm-ag/commit/5fa7bd3dbb9bf58f2b6ae970457467c2b1fa20dc

For the helm grep I don't think it is really an issue, even when pt is used it is still helm-ag so it is inconsistent.

**Comment by justbur** [comment]
Yes it works now see https://github.com/syohex/emacs-helm-ag/pull/167

**Comment by CestDiego** [comment]
the functionality is there. but helm-projectile might take the universal argument and not letting it through the helm-ag thing.

**Comment by justbur** [comment]
No you can do this with helm-do-ag now. Just add the command line arg to the helm pattern

**Comment by CestDiego** [comment]
what argumient? D:

**Comment by CestDiego** [comment]
oh after seeing that issue it makes sense and it works.. but it's not pretty. xD and not even close to the helm listing all available extensions in the project for `SPC u SPC s f` :(

**Comment by CestDiego** [comment]
I'm grateful for the command line arg working though

**Comment by justbur** [comment]
For me I like waiting to see how many matches there are for a search and then if there are a lot using the filter to narrow down.

**Comment by CestDiego** [comment]
it's just that it doesn't really go with conventions . :(

**Comment by syl20bnr** [comment]
I must admit that this `-G` option is terrific, I just tried it and I agree with @justbur and find it more natural.

**Comment by syl20bnr** [comment]
@CestDiego From the mentioned PR thread I believed that `-G` should be at the start of the helm pattern but actually you can use it anywhere in the pattern!

**Comment by CestDiego** [comment]
Yeah but what about self discoverability? I'm using it a lot now but still think about the kidz. xD

**Comment by syl20bnr** [comment]
Bah it's advanced option, I see it as a feature above spacemacs bindings conventions, i.e. provided at the package usage level.

Neat to actually search for `-G` one has only to escape it to `\-G` :-)

Hard to beat this UI to be honest.

**Comment by justbur** [comment]
Well...we could document it somewhere (@TheBB)

**Comment by StreakyCobra** [comment]
Fixed in 8c8da65
