### ISSUE TITLE
Behavior of M-RET in Org-mode in GUI and Terminal 

### ISSUE THREAD

**Issue by ghost355** [syl20bnr/spacemacs#3283]
Hi!
In Org-mode:
when I use GUI emacs - M-RET work fine in org-mode for making new task same level, but in terminal emacs - when I press M-RET  it doesn't work  - just show bottom window for commands shortcuts without any actions. Is it normal or not?

###### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.104.2
- Spacemacs branch: master (rev. 074f425)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp
                 (git :variables git-enable-github-support t)
                 markdown themes-megapack org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh")
                 syntax-checking version-control osx
                 (haskell :variables haskell-enable-hindent-style "chris-done" haskell-enable-ghci-ng-support t haskell-enable-shm-support t))
```

**Comment by syohex** [comment]
In terminal, we cannot input `M-RET`. You can check this by `M-x describe-key` and type `M-RET`, then terminal recognizes it as `C-M-j`, not `M-RET`.

**Comment by ghost355** [comment]
Thanks. I didn't know it.
