### ISSUE TITLE
Add a timeout for elpa repositories when downloading packages

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#3284]
If one of the elpa repositories is down for any reason...bootstrapping, package updates and/or new package install fails. 

**Proposal**: add a timeout -- and gracefully fail (if possible). 

This issue is based on a discussion in #3270, specifically see https://github.com/syl20bnr/spacemacs/issues/3270#issuecomment-145844754.

**Comment by syl20bnr** [comment]
We should now have a basic timeout of 5 seconds when fetching the elpa archives.

**Comment by Malabarba** [comment]
As someone who would like to improve package.el itself, could I ask for more information on this?
What exactly happens for you when an archive is down? 
Is it that Emacs hangs indefinitely while trying to update? Or is it that the error message is uninformative?

**Comment by mb-dev** [comment]
This is still not fixed. Elpa is down at the moment and when spacemacs load I get this error:
```
Warning (initialization): An error occurred while loading ‘/Users/moshe/.emacs.d/init.el’:

error: Could not create connection to elpa.gnu.org:443

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```
Afterwards, spacemacs fails to load, syntax highlighting gets turned off, and i'm back to emacs shortcuts.

<img width="582" alt="screen shot 2016-02-19 at 11 32 57 am" src="https://cloud.githubusercontent.com/assets/807807/13186771/95a0d624-d6fc-11e5-881b-4a6dbd351242.png">

**Comment by syl20bnr** [comment]
@mb-dev this is fixed in 0.105.11 :-)

**Comment by syl20bnr** [comment]
@Malabarba Sorry for the late reply, Emacs starts normally, the issue was the default time of the time out which seems hard coded and not available to the end user. If I recall correctly the time out was something like 90sec. or 120sec. What I did in Spacemacs is a pre-step to GET the repo URL with a `with-time-out` and I mark the not unavailable archives.

**Comment by mb-dev** [comment]
Great @syl20bnr! thanks for fixing it. Spacemacs is becoming my favorite editor.
