### ISSUE TITLE
Disable flycheck by default

### ISSUE THREAD

**Issue by mkollaro** [syl20bnr/spacemacs#3286]
I want to use the syntax-checking layer, but only enable it when I actually want it for some file. Right now, if you add the layer, it will enable syntax checking by default. Setting `(global-flycheck-mode -1)` doesn't seem to do anything, and toggling it with `SPC t s` only disables it for that file - it will be enabled when I open another one.

**Comment by TheBB** [comment]
Yeah, I wanted to introduce something for this in #2810 but @syl20bnr wasn't too keen on it.

Instead, put this in `dotspacemacs/user-config` to do what you are after:

```lisp
  (mapatoms (lambda (atom)
              (when (and (string-suffix-p "-hook" (symbol-name atom))
                         (boundp atom)
                         (listp (eval atom)))
                (remove-hook atom 'flycheck-mode)
                (remove-hook atom 'flyspell-mode))))
```

It looks through every variable which is a hook, and removes flycheck (and flyspell) from it. It's sort of a nuclear option, but it has worked well for me.

**Comment by syl20bnr** [comment]
@TheBB I cannot reopen #2810 because the branch has been deleted but you should be able to retrieve it with:

```sh
$ git pull origin pull/2810/head:global_flag_check
```

**Comment by TheBB** [comment]
Sure, but even if I retrieve it, the reservations you had presumably still stand, no?

**Comment by syl20bnr** [comment]
With a fresh take on this use case I don't see how we can handle it better than your PR. The `:disabled-for` is not suitable for a `global toggle off by default`, I did not see the initial use case correctly at that moment...

**Comment by TheBB** [comment]
Okay, I'll see about it tonight.

**Comment by syl20bnr** [comment]
Thank you :+1:

**Comment by TheBB** [comment]
#3289

**Comment by mkollaro** [comment]
Thanks, that patch looks like it should do what I want. It doesn't apply cleanly on master yet, but I can wait.

**Comment by tasmo** [comment]
Isn't it that what you want? [Disabling spell checking by default](http://spacemacs.org/layers/+checkers/spell-checking/README.html#disabling-by-default)

```lisp
(setq-default dotspacemacs-configuration-layers
  '((spell-checking :variables spell-checking-enable-by-default nil)))
```

**Comment by roryokane** [comment]
@tasmo No, this issue is about syntax checking, not spell checking. But yes; after this issue was created, a similar section [in the documentation for the `syntax-checking` layer](http://spacemacs.org/layers/+checkers/syntax-checking/README.html#disabling-by-default) was added:

> ### 2.3 Disabling by default
> 
By default, syntax-checking is enabled in all available major modes and may be toggled off with `SPC t s`. You can default this to off by setting the variable `syntax-checking-enable-by-default` to `nil`:
> 
> […]
> 
> If you want more fine-grained control, you can configure the variable `flycheck-global-modes` instead. […]
