### ISSUE TITLE
Add support for workgroups2 or similar

### ISSUE THREAD

**Issue by bjarkevad** [syl20bnr/spacemacs#329]
It would be cool if we had the possibility of saving window splits, open files and so on, for example by using [workgroups2](https://github.com/pashinin/workgroups2).

I suggest that it's added as a contrib layer.

**Comment by StreakyCobra** [comment]
The PR #2990 will close this issue, if merged.

**Comment by syl20bnr** [comment]
Spacemacs has now support for this via Spacemacs Layouts, I don't see the need to support another backend for this feature. For this reason I'm closing this.
