### ISSUE TITLE
org-capture (SPC o c) getting unbound in org mode

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#3294]
My evil leader binding for `org-capture` on `SPC o c` is getting unbound in Org mode.

I'd appreciate any advice for debugging this, or if anyone else is running into this or can reproduce it.  It's a horrible heisenbug: it's fixed on a fresh start, but randomly `SPC o c` gets unset in Org mode.  I haven't found a way to reliably reproduce it.  I would update Spacemacs, update my packages, delete all package and reinstall them fresh, and this will keep happening randomly.

An errant timer?  Some delayed package loading?  Does Emacs/Spacemacs have anything that can help debug this?

EDIT: my binding of `org-agenda` on `SPC o a` is also getting unset.  I have bound a non-org command onto `SPC o s`, updated Spacemacs and packages, and will wait to see if I can pin this down.

**Comment by robbyoconnor** [comment]
When reporting bugs: ALWAYS include`SPC hds`

if you are on `master`, try `develop` -- because if the bug does not exist there...this issue is moot.

**Comment by robbyoconnor** [comment]
Also, if you are trying to get us to debug code, paste the code.

**Comment by darkfeline** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: master (rev. 4f3102c)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 syntax-checking
 (shell :variables shell-default-shell 'shell shell-default-height 50)
 perspectives gtags erc org finance ibuffer
 (chrome :variables edit-server-new-frame nil)
 git version-control c-c++ emacs-lisp go html javascript latex lua markdown python ruby sql yaml mir-bbdb mir-elfeed mir-magit-annex mir-mu4e mir-plus mir-ranger mir-remind-to-diary mir-mpc)
```

Uh, I'm on `develop` though.  The "code", for what it's worth, is:

  (evil-leader/set-key "o c" 'org-capture)
  (evil-leader/set-key "o a" 'org-agenda)

**Comment by TheBB** [comment]
Does it work if you exclude `evil-org`?

**Comment by darkfeline** [comment]
@TheBB I'll try that, and great suggestion.

It looks like `evil-org` binds `SPC o` to something, and Spacemacs binds it back.  Here's the code: https://github.com/syl20bnr/spacemacs/blob/develop/layers/org/packages.el#L60

Is it possible this is causing it?  It looks like `evil-org` is loaded lazily, and I'm binding my `SPC o` keys in `dotspacemacs/user-config`.

**Comment by TheBB** [comment]
Well, it's *possible*, as far as I know. That's why I wanted you to try it. :-)

**Comment by fintelkai** [comment]
I'm struggling with this as well. All my org-mode "o" bindings (set with `evil-leader/set-key-for-mode 'org-mode` in an `(with-eval-after-load 'org ...)` block in my user customization are gone. This seems to happen if I load my org-file "late". For a while I had one of my org-files set as the `initial-buffer-choice` but lately that doesn't work anymore (making me wonder why that's not working, btw). I haven't had time to troubleshoot, but I can definitely confirm that this is an issue.

**Comment by TheBB** [comment]
I think we should just pull the plug on the evil-org package, make it a local package and rip out the things we don't need.

**Comment by TheBB** [comment]
That's not to say that it's 100% definitely the source of this problem. Maybe just 80%. :-)

**Comment by syl20bnr** [comment]
Maybe it is time to desing our own evil-org :-)

**Comment by fintelkai** [comment]
Disabling evil-org does indeed fix the issue of the "o" bindings disappearing.

**Comment by TheBB** [comment]
Okay, so make that 100% then.

**Comment by justbur** [comment]
Just fork it and pull out the key bindings. It's mostly just that it uses evil-leader right?

**Comment by TheBB** [comment]
@fintelkai @darkfeline #3305 should solve the problem.

**Comment by darkfeline** [comment]
https://github.com/syl20bnr/spacemacs/pull/3305 has been merged.
