### ISSUE TITLE
[develop] Auto-completion in Python

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#3299]
When I press any key in python mode buffer, there is no complete candidates, and the editor window will be frozen at the same time.
My message buffer give me cues ,
```
Company: An error occurred in auto-begin
Completion needs an inferior Python process running
Company: An error occurred in auto-begin
Completion needs an inferior Python process running
```
Obviously, It complain about the inferior RPC , but my anaconda-mode buffer run smoothly, works well. 
I don't know where the problem is.
I check my  install packages, all are  lastest
```
#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.104.2
- Spacemacs branch: develop (rev. 4d72062)
- Distribution: spacemacs
- Layers:
((org :variables org-enable-github-support t)
 (python :variables python-enable-yapf-format-on-save t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
 (c-c++ :variables c-c++-enable-clang-support t)
 (haskell :variables haskell-enable-ghci-ng-support t)
 (haskell :variables haskell-enable-shm-support t)
 (haskell :variables haskell-enable-hindent-style "johan-tibell"))

```

**Comment by bmag** [comment]
Your layers info is weird. First of all, `auto-completion` is missing. You should use the `auto-completion` layer for getting auto-completion in spacemacs. You may need to remove conflicting parts in your configuration, if any.

Second of all, and probably not related to your problem, you have `c-c++` and `haskell` layers listed more than once. The layers info should look something like this:
```
- Layers:
((auto-completion
 (org :variables org-enable-github-support t)
 (python :variables python-enable-yapf-format-on-save t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "johan-tibell"))
```
You may want to re-read the documentation about installing and configuring layers.

**Comment by TheBB** [comment]
:point_up: Minor correction (one paren too many):
```
(auto-completion
 (org :variables org-enable-github-support t)
 (python :variables python-enable-yapf-format-on-save t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "johan-tibell"))
```

**Comment by dzhwinter** [comment]
thanks for your cues, But the issue still sits in there. 
```
Company: An error occurred in auto-begin
Completion needs an inferior Python process running
Company: An error occurred in auto-begin
Completion needs an inferior Python process running
Saving file /home/dzh/code/python/test.py...
Wrote /home/dzh/code/python/test.py
Can't guess python-indent-offset, using defaults: 4
Make dedicated process? (y or n) y
Sent python-shell-completion-setup-code
Sent python-ffap-setup-code
```
after i send the buffer to ipython, the company cycle can show up, but i can feel pause when i typed candidate letters. in other words, feel stuck when there is company cadidates pop up.

now my system info looks like
```
#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.104.2
- Spacemacs branch: develop (rev. 4d72062)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion
 (org :variables org-enable-github-support t)
 (python :variables python-enable-yapf-format-on-save t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "johan-tibell"))
```

**Comment by bmag** [comment]
For some reason, Company is not using anaconda-mode to get candidates. Instead, it looks uses the interpreter. I tried to reproduce your error with the settings you provided but couldn't.
When you're inside a python file, what is the value of `company-backends`? (to check, `C-h v company-backends`)

**Comment by dzhwinter** [comment]
__company-backends__ show ```Its value is (company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-files company-dabbrev)
```
and another variable __company-backends-python-mode__ value is ```
Its value is (company-anaconda
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)
```

**Comment by dzhwinter** [comment]
As a comparison, the __inferior Python mode__ same variables:
__company-backends__ show 
```
Value: ((company-files company-capf)
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)

Original value was 
(company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-files company-dabbrev)

Local in buffer *Python[/home/dzh/Documents/yanzhenma/mykeras.py]*; global value is 
(company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-files company-dabbrev)


```

 __company-backends-python-mode__ value is 
```
Its value is ((company-files company-capf)
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)

```

**Comment by bmag** [comment]
@dzhwinter just in case, did you restart emacs after making the changes?
Otherwise, it could be something in your config that interefers with the configuration of `anaconda-mode`, `company-mode` or `company-anaconda`. Can you try commenting out different parts in your `.spacemacs` to find out which part causes the bug?

**Comment by dzhwinter** [comment]
~~I did have restarted emacs, I can confirm that emacs read from new config file. the variables value keep the same with what i had paste ~~

__update__ 
I just reinstall python all the dependency such as ```anaconda-mode, json-rpc, jedi``` , and my issue disappear. I am run after project pressure and have no time to dig in why reinstall packages trigger anaconda-mode, but it works well and feel so better.
