### ISSUE TITLE
error after removing themes-megapack layer

### ISSUE THREAD

**Issue by lerrua** [syl20bnr/spacemacs#3302]
i have this following error:
![screen shot 2015-10-08 at 10 40 04 am](https://cloud.githubusercontent.com/assets/154603/10367859/1e30cfac-6da9-11e5-9526-44d7d61c1313.png)

**Comment by lerrua** [comment]
in case, it can't deleting anything.
![screen shot 2015-10-08 at 11 12 53 am](https://cloud.githubusercontent.com/assets/154603/10368848/b2f6662a-6dad-11e5-872b-07e8fb4ce6e9.png)

**Comment by lerrua** [comment]
Damm... i solve this using `brew install trash`

**Comment by TheBB** [comment]
Great! :+1:

Should this be documented? You mac people?

**Comment by syl20bnr** [comment]
We have a bug here, trash should be optional.
We should also move the doc to the layer (https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#deleting-files).

**Comment by syl20bnr** [comment]
Introducing `Beginner friendly` tag ! :-D

**Comment by TheBB** [comment]
Aw okay, I'll move mine then. :-P

**Comment by lerrua** [comment]
:+1:

**Comment by StreakyCobra** [comment]
Isn't `trash` [already optional](https://github.com/syl20bnr/spacemacs/blob/383b1bec20954c67ce4fbd80475e211c58e28c51/layers/osx/packages.el#L17) for OSx (with `osx` layer)? Or is it for another OS?

**Comment by TheBB** [comment]
If @lerrua gets an error without trash and no error with trash, then it is *in practice* not optional. Since it *should* be optional, it's a bug.

**Comment by StreakyCobra** [comment]
Of course, but to try fixing it we need to know if it's on OS X or not, and if osx layer was activated, no? At least I need :stuck_out_tongue:

**Comment by TheBB** [comment]
Probably OSX since @lerrua used brew.

I don't know of the `osx` layer was enabled or not but the error seems to originate from somewhere in core.

**Comment by lerrua** [comment]
@TheBB i'm using brew and my `osx` layer is enable.
