### ISSUE TITLE
org-babel-load-languages has issues in v104.2

### ISSUE THREAD

**Issue by liangwang** [syl20bnr/spacemacs#3314]
To enable python code evaluation in org-mode, the org-babel document suggests the following:

```emacs
     (org-babel-do-load-languages
      'org-babel-load-languages
      '((python . t)))
```

Prior v104.x, it works by putting the above code in dotspacemacs/config. After upgrade to v104.2, if the above code is put in dotspacemacs/user-config, emacs throws the following error at startup:

```
Invalid function: org-babel-header-args-safe-fn
```

When move the code into dotspacemacs/user-init, emacs starts without any error messages. But autofill within org file does not work. Emacs will show the error message as follows:

```
An element cannot be parsed line xxx
```

BTW, is dotspacemacs/user-config and/or dotspacemacs/user-init the right place to put org-mode related customizations?

**Comment by TheBB** [comment]
I'm not sure why it doesn't work, but certainly it has to go in `user-config`. Otherwise org will not yet have been configured by Spacemacs.

Can I ask for your `SPC hds` output?

**Comment by TheBB** [comment]
https://lists.gnu.org/archive/html/emacs-orgmode/2015-08/msg00254.html

Might be an error in `org-plus-contrib`. Try updating it and see if it works for you. It does for me...

**Comment by liangwang** [comment]
It seems related to the old "org" package installed by spacemacs v103, and after upgrade to v104, the "org" package is not deleted automatically, and messes up with new org-plus-contrib package. It works for me right now. 

Besides, I would really appreciate if the document (either spacemacs or org layer) can provides some examples/tutorials on how to wrap customized org settings into a personal private layer. Putting everything within user-config seems a little messy to me.

**Comment by TheBB** [comment]
Thanks! You can read `doc/LAYERS.org` for some info about how to write layers. It doesn't cover org specifically, but it might still help you. I think #3277 should cover the org specific documentation problems. I'm closing this, then.

**Comment by liangwang** [comment]
Update on this issue:

I could reproduce the issue with the following steps:

1. Make a fresh spacemacs install using `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
2. Make sure the spacemacs configuration enables the org layer. and has the following settings in `spacemacs/user-config`
```emacs
     (org-babel-do-load-languages
      'org-babel-load-languages
      '((R . t)
        (python . t)))
```
3. Launch emacs. After spacemacs installs all packages, exit spacemacs. Then you can find both `org` and `org-plus-contrib` under `~/.emacs.d/elpa`
4. Launch emacs again, you will see `Invalid function: org-babel-header-args-safe-fn` at the bottom shortly after it says `spacemacs is ready`.

The following workaround works for me:
1. Delete `org` and `org-plus-contrib` under `~/.emacs.d/elpa`
2. Launch emacs again, and this time, spacemacs will only install `org-plus-contrib`. Then exit emacs
3. Launch emacs, no `org-babel-header-args-safe-fn` error anymore.

**Comment by tommyjiang** [comment]
Thanks @liangwang for providing this solution to solve this problem.

**Comment by markhuyong** [comment]
if you have ob-R in your config, then remove it.[ob-R](http://orgmode.org/worg/org-tutorials/org-R/org-R.html)

**Comment by devminz** [comment]
for my case ( emacs newbie < 1m )  I faced same issue for elixir layer. 
Got it resolved just by removing all  *.elc files  in  .emacs and restarting  emacs.

**Comment by biocyberman** [comment]
This single error has caused me quite a headache. I finally found a specific solution for my case (because `org` is not installed, and `org-plus-contrib` has been installed correctly). Thanks to this blog post:
https://sort-care.github.io/Emacs-Invalid-function-org-babel-header-args-safe-fn/
In essence, the evil line was:

     (org-babel-do-load-languages
      'org-babel-load-languages
      '(
        (python . t)
        (R . t) ; this one is causing problem.
       )
       )

The solution is to run `SPC SPC byte-compile-file ./elpa/org-plus-contrib-20180625/ob-R.el`. You have to run this, even though you might see the .elc file there already.

**Comment by QikeLi** [comment]
solution from @ biocyberman solved my problem.

**Comment by penn201500** [comment]
https://emacs.stackexchange.com/questions/32001/org-babel-9-spacemacs-unable-to-evaluate-org-babel-src-blocks
