### ISSUE TITLE
Why spacemacs is too slow?

### ISSUE THREAD

**Issue by lerrua** [syl20bnr/spacemacs#3317]
Hi there,

I'm a vim user and spacemacs do a great job for me when i'm try to migrating to emacs.
Anyway, my vimrc has many many plugins and running in terminal it starts after 1 second more or less, using spacemacs with standard config and branch master i have [203 packages loaded in 5.601s].
You guys did a amazing job, spacemacs is great but why so slow? And how can i improve the boot speed?.

**Comment by TheBB** [comment]
You can try `emacs --debug-init --timed-requires --profile` and then have a look at the load times buffer to see what takes an especially long time to load.

I should say that depending on your computer, five seconds for 200 packages isn't unreasonable. Mine boots in 2.5 seconds with 270 packages, but this computer is quite powerful. Spacemacs is designed to be started once and then left open. You can then launch clients with `emacsclient -c`, which should be almost instant.

**Comment by lerrua** [comment]
@TheBB thanks, but i had some problems.

My output after running your example. `Unknown option --timed-requires`
And emacsclient -c gave me `emacsclient: can't find socket; have you started the server?`.

Sorry for my emacs noob questions.

**Comment by TheBB** [comment]
What's your Emacs version? Maybe `--timed-requires` is too recent.

In any case, you need to have Emacs running first when you try `emacsclient`. When Spacemacs boots it starts a server for you, so that you can attach additional windows to the same Emacs process without going through the booting process again. But the first one still has to be done normally.

**Comment by lerrua** [comment]
```
$ emacs --version
GNU Emacs 24.5.1
```

**Comment by justbur** [comment]
@TheBB that's a develop feature. Check out core-debug.el

**Comment by justbur** [comment]
@lerrua 5.6 sec seems a bit slow, and you can probably improve it. But you shouldn't expect to get vim startup speeds unless you cheat and use a persistent server in the background.

**Comment by TheBB** [comment]
Oh, I thought it was stock Emacs. :-P

**Comment by justbur** [comment]
I figured out how to add command line arguments which turn out to be really convenient for doing stuff like this

**Comment by Tyler-Anderson** [comment]
keeping a server open in the bg is a good suggestion. Is there a reason you can't just leave emacs open? I rarely find myself restarting it

**Comment by justbur** [comment]
No no reason really unless something screws up the state of emacs

**Comment by lerrua** [comment]
Great, thanks for help guys.

Well, i'm a Vim user, so normally open several terminal tabs, editing some files, then other open in another tab... normally `Ctrl+Z` and `fg` later and back to vim.
But now I understand the emacs way, it's new for me.

**Comment by Tyler-Anderson** [comment]
The great thing about spacemacs is you get a seamless modal editing experience while keeping the emacs benefits like repl integration and a much better plugin architecture. It does take a bit to get used to how to get/keep it fast.

**Comment by nrolland** [comment]
180 packages in 32s here 

> 
> Threshold set at 0.150 seconds
> 
> File /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/emacs/24.5/lisp/org/ob-emacs-lisp.elc: Required ob: 0.246 sec
> File /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/emacs/24.5/lisp/org/org.elc: Required ob-emacs-lisp: 0.254 sec
> File /Users/nrolland/.spacemacs.d/init.el: Required org: 0.856 sec
> File /Users/nrolland/.emacs.d/init.el: Loaded /Users/nrolland/.spacemacs.d/init.el: 0.870 sec
> File /Users/nrolland/.emacs.d/core/core-configuration-layer.el: Required eieio: 0.187 sec
> File /Users/nrolland/.emacs.d/init.el: Required core-configuration-layer: 0.386 sec
> package-initialize took 0.492 sec
> File /Users/nrolland/.emacs.d/elpa/evil-20160312.1042/evil.elc: Required evil-commands: 0.195 sec
> File /Users/nrolland/.emacs.d/init.el: Required evil: 0.450 sec
> File /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/emacs/24.5/lisp/gnus/ietf-drums.elc: Required mm-util: 0.156 sec
> File /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/emacs/24.5/lisp/gnus/mail-parse.elc: Required ietf-drums: 0.168 sec
> File /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/emacs/24.5/lisp/gnus/mm-decode.elc: Required mail-parse: 0.219 sec
> File /Users/nrolland/.emacs.d/elpa/package-build-20160129.1332/package-build.elc: Required mm-decode: 0.252 sec
> File /Users/nrolland/.emacs.d/init.el: Required package-build: 0.326 sec
> File /Users/nrolland/.emacs.d/init.el: Loaded /Users/nrolland/.emacs.d/layers/+distribution/spacemacs/config.el: 0.167 sec
> File /Users/nrolland/.emacs.d/init.el: Required diff-hl: 0.319 sec
> File /Users/nrolland/.emacs.d/init.el: Required eval-sexp-fu: 0.227 sec
> File /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/emacs/24.5/lisp/net/tramp.elc: Required tramp-compat: 0.214 sec
> File /Users/nrolland/.emacs.d/elpa/git-gutter+-20151204.923/git-gutter+.elc: Required tramp: 0.336 sec
> File /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/emacs/24.5/lisp/vc/log-edit.elc: Required message: 0.370 sec
> File /Users/nrolland/.emacs.d/elpa/git-gutter+-20151204.923/git-gutter+.elc: Required log-edit: 0.455 sec
> File /Users/nrolland/.emacs.d/elpa/with-editor-20160223.1155/with-editor.elc: Required tramp-sh: 0.216 sec
> File /Users/nrolland/.emacs.d/elpa/git-commit-20160130.649/git-commit.elc: Required with-editor: 0.440 sec
> File /Users/nrolland/.emacs.d/elpa/git-gutter+-20151204.923/git-gutter+.elc: Required git-commit: 0.544 sec
> File /Users/nrolland/.emacs.d/elpa/s-20160115.58/s.elc: Required ucs-normalize: 0.384 sec
> File /Users/nrolland/.emacs.d/elpa/spaceline-20160229.1115/spaceline-segments.elc: Required s: 0.391 sec
> File /Users/nrolland/.emacs.d/elpa/spaceline-20160229.1115/spaceline-config.elc: Required spaceline-segments: 0.519 sec
> File /Users/nrolland/.emacs.d/init.el: Required spaceline-config: 0.524 sec
> File /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/emacs/24.5/lisp/url/url.elc: Required url-proxy: 0.369 sec
> File /Users/nrolland/.emacs.d/elpa/helm-20160307.2253/helm-net.elc: Required url: 0.759 sec
> File /Users/nrolland/.emacs.d/elpa/helm-20160307.2253/helm-external.elc: Required helm-net: 0.941 sec
> File /Users/nrolland/.emacs.d/elpa/helm-20160307.2253/helm-files.elc: Required helm-external: 0.973 sec
> File /Users/nrolland/.emacs.d/elpa/helm-20160307.2253/helm-files.elc: Required helm-grep: 0.287 sec
> File /Users/nrolland/.emacs.d/elpa/helm-20160307.2253/helm-bookmark.elc: Required helm-info: 0.337 sec
> File /Users/nrolland/.emacs.d/elpa/helm-20160307.2253/helm-files.elc: Required helm-bookmark: 0.589 sec
> File /Users/nrolland/.emacs.d/elpa/helm-20160307.2253/helm-files.elc: Required ffap: 0.179 sec
> File /Users/nrolland/.emacs.d/elpa/helm-20160307.2253/helm-mode.elc: Required helm-files: 2.873 sec
> File nil: Required helm: 3.228 sec
>
