### ISSUE TITLE
new version and install evil-mc error

### ISSUE THREAD

**Issue by DaSea** [syl20bnr/spacemacs#3323]
In the morning, I update the spacemacs repository through **git pull** order, but when start it, it occurs the error:
**Found 1 new package(s) to install...
--> fetching new package repository indexes...
--> installing spacemacs:evil-mc... [1/1]An error occurred while installing evil-mc (error: (wrong-type-argument stringp nil))**

My system is windows, and who can tell me the reason?

**Comment by stshine** [comment]
Same here. Quelpa seems still does not work on windows.

**Comment by DaSea** [comment]
my repository is develop branch!

**Comment by mukhali** [comment]
melpa have evil-mc http://melpa.org/#/evil-mc, why need Quelpa

**Comment by DaSea** [comment]
I manual download, place it into ".emacs.d/elpa", and start emacs,  then no error!
