### ISSUE TITLE
Multiterm exit sends SIGQUIT to other terms

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#3324]
When one multi-term exits, SIGQUIT is sent to other terms that are still running.

To reproduce:

1. Start one multi-term.
2. Run a continuous process, like `tail -f file`.
3. Start another multi-term.
4. Exit, either by using the `exit` command or sending CTRL-D.
5. Check first multi-term.  `tail -f file` has been killed by SIGQUIT.

**Comment by CarlQLange** [comment]
I can't reproduce this using the exact steps you suggested... `SPC h d s`? I feel like this must be a system thing - I assume the same doesn't happen with another terminal?

**Comment by darkfeline** [comment]
Ah, I keep forgetting about that new feature.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: master (rev. 053eefd)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 syntax-checking
 (shell :variables shell-default-shell 'shell shell-default-height 50)
 perspectives gtags erc org finance ibuffer
 (chrome :variables edit-server-new-frame nil)
 git version-control c-c++ emacs-lisp go html javascript latex lua markdown python ruby sql yaml mir-bbdb mir-elfeed mir-magit-annex mir-mu4e mir-plus mir-ranger mir-remind-to-diary mir-mpc)
```

Okay, this is kind of odd.  I don't have `multi-term-program` set, so `multi-term` is using my `SHELL` variable, which is `/usr/bin/zsh`.  This bug happens.  If I start bash in the first term and try it, this bug doesn't happen.

Actually, scratch that.  I *think* what's happening is that if I exit one `multi-term`, and the window automatically switches to a different `multi-term` buffer, the second buffer send SIGQUIT.  Maybe.

I tried different combinations of ZSH and Bash in different multi-terms and sometimes it happens and sometimes it doesn't.  I haven't seen it happen to Bash yet, so it's probably limited to ZSH, somehow.

I'll try to post something more concrete when I've figured it out, but you probably can reproduce this by using ZSH.

**Comment by CarlQLange** [comment]
Aha! Yes!

**Comment by CarlQLange** [comment]
OK, I've been able to reproduce, and yeah, it's your last paragraph. Here are some steps:

1. `multi-term`
2. `tail -f /var/log/system.log`
3. `multi-term`
4. `C-c C-d`

observe as your second multi-term exits, and the one it switches to also gets SIGQUIT.

**Comment by CarlQLange** [comment]
https://github.com/emacsmirror/multi-term/blob/master/multi-term.el

In case you feel like reading through the source (it's really well-documented actually)

**Comment by CarlQLange** [comment]
I think I found the issue. https://github.com/syl20bnr/spacemacs/blob/develop/layers/shell/packages.el#L250

**Comment by CarlQLange** [comment]
Yeah, if you comment out that hook, behaviour makes sense again and this issue doesn't happen. This hook was added by @tuhdo - can you enlighten us on why this is here? I suspect it's because you use `ansi-term`, which doesn't have this behaviour built-in, while `multi-term` does.

**Comment by darkfeline** [comment]
Thanks for finding the problem.  I have a couple questions about this too.

1. Aren't processes associated with a buffer killed along with it anyway?  @tuhdo Is there a need for this hook?
2. Why is this leaking to other buffers?  This suggests that `kill-buffer-hook` is doing something strange, which could cause other unintended behavior.

**Comment by CarlQLange** [comment]
Well, in regard to 2, it's leaking to `term-mode` buffers, which both `ansi-term` and `multi-term` use. As far as I can see, there's no sensible way to distinguish between the two. `(when (eq major-mode 'term-mode)` seems to be the only way to do it that's not tied to the buffer name. I don't believe this hook is doing anything else strange - this seems to just be a feature of `multi-term` that was wanted in `ansi-term`. I think regarding 1, `ansi-term` does not kill buffers if the process in the buffer is killed, which is what this hook is for. So in a way, there is a use for this hook. The only real issue is that it's getting other terms, not just ansi-terms, so the filter needs to be updated. However, I amn't aware of a way to check if a buffer is `ansi-term` vs `multi-term`.

**Comment by darkfeline** [comment]
>1, ansi-term does not kill buffers if the process in the buffer is killed, which is what this hook is for. So in a way, there is a use for this hook.

In my mind, the flow is:

    kill-buffer -> kill-buffer-hook -> spacemacs//term-kill-buffer-hook

That is, the direction of causation is kill buffer -> kill process, not kill process -> kill buffer.

With regards to 2., the problem is that killing term <1> -> kill-buffer-hook -> SIGQUIT in term **<2>**, that is, when kill-buffer-hook is called, it is affecting not the buffer that was killed, but a different buffer entirely.

It's not actually a problem that `spacemacs//term-kill-buffer-hook` doesn't discriminate between `ansi-term` and `multi-term`, since if the buffer is being killed, any process connected to that buffer should be killed anyway, `multi-term` or `ansi-term` or `foo-term`.  The problem is that `kill-buffer-hook` from killing buffer A affects buffer B.

I think it is because `term-kill-subjob` doesn't discriminate between buffers, although I'm not familiar with Emacs's job management.

**Comment by CarlQLange** [comment]
Actually, I think this is because there are two kill-buffer hooks. It's more like:

```
kill-buffer-hook -> multi-term-kill-buffer-hook -> (term-kill-subjob current-buffer)
                `-> spacemacs//term-kill-buffer-hook -> (term-kill-subjob current-buffer)
```

So what's happening is that both of these hooks are killing a subjob. The buffers are switched _between_ these two hooks, then the second hook fires, killing the subjob. Does that make sense?

**Comment by darkfeline** [comment]
I see.  So the reason is because @tuhdo isn't loading `multi-term.el`, so he added this, unaware of the duplicated behavior.  In that case, this should be removed.

**Comment by darkfeline** [comment]
Fixed with https://github.com/syl20bnr/spacemacs/pull/3340

**Comment by darkfeline** [comment]
Fixed in https://github.com/syl20bnr/spacemacs/commit/1f3a6a0941c11b301141a0dbe74d93a7b8e3558f
