### ISSUE TITLE
tab doesn't work in magit in spacemacs for the most recent version

### ISSUE THREAD

**Issue by wqhhust** [syl20bnr/spacemacs#3326]
After I press SPACE + g + s, it shows the git status, previously press a tab, it will show the different between the changed file and the stage. but now it doesn't work. Maybe I pressed some special key and make TAB doesn't work, but how to make it work again?

**Comment by bmag** [comment]
Works for me with most recent version. What command is <kbd>TAB</kbd> bound to? For me, it's bound to `magit-section-toggle`. (check by hitting <kbd>SPC h d k TAB</kbd>)

**Comment by wqhhust** [comment]
Thanks. it works now and it's bind to magit-section-toggle. Not sure what happens previously. I could use you command to check again when it doesn't work next time. thanks very much
