### ISSUE TITLE
New haskell mode broken without proper setup?

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#333]
When I open spacemacs I get the following message:

```
(Spacemacs) Package: Initializing haskell:company-ghc...
Initializing...
"ghc-mod" not found
```

This is a strange error because I have ghc-mod available on my path:

```
endrebakkenstovner@endres-MacBook-Pro ~> echo $PATH
/Users/endrebakkenstovner/anaconda/bin/ /Users/endrebakkenstovner/Library/Haskell/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin
```

Furthermore, I have added the following line to my `.spacemacs` (as per kazus instructions
@ https://github.com/kazu-yamamoto/ghc-mod/issues/100):

`(add-to-list 'exec-path "/Users/endrebakkenstovner/Library/Haskell/bin")`

I'm guessing there are a lot of paths that need to be set for the current Haskell mode to work. These should probably be included in the `packages.el` file with instructions. 

Furthermore, as it requires an external package to work (`ghc-mod`), we should proably add a line about how to install this (`cabal install ghc-mod`).

**Comment by syl20bnr** [comment]
I consider this fixed. Reopen it if there are still missing steps in 0.40.0 and above.
