### ISSUE TITLE
ruby configuration layer interfering with macro and replays

### ISSUE THREAD

**Issue by askreet** [syl20bnr/spacemacs#3330]
I put together this example:

```
# qq
# /should<RET>
# 3w "ayw
# /foo<RET>
# dw "aP a<SPACE><ESC> b guw "ayw
# n dw "aP x
# n dw "aP x
# q
# @q @q
# start cursor here
it 'should do a THING' do
  foo = Class1.foo('zone')
  foo.client.do_stuff
end

it 'should do a STUFF' do
  foo = Class1.foo('zone')
  foo.client.do_stuff
end
```

In this example, I want to replace the 3 foos with a lowercase version of the capitalized string in the it description. Following the keystrokes yields me:

```
it 'should do a THING' do
  thing = Class1.thing('zone')
  thing.client.do_stuff
end

it 'should do a STUFF' do
  sywnndw"aPxndw"aPxtuff = Class1.foo('zone')
  foo.client.do_stuff
end
```

It seems as though the ESC portions of the macro may not be getting recorded, resulting in the remainder of commands being input as part of my append action. Please let me know what other data I can gather. I've seen similar issues with simpler actions like using `/` to search, executing a `ciw` with a simple string, using `n` to find the next match and using `.` to apply my `ciw` again resulting in a random bonus letter prefixing the paste.

**Comment by askreet** [comment]
As a follow-up, I'm having really basic repeat issues with things like `c3w<text><ESC>` then trying to use `.` to repeat them resulting in "c3w" being included in the string. Not sure how to dive in and debug this further. It is happening on OS X and Linux, for what it's worth.

**Comment by StreakyCobra** [comment]
What version are you using? You can do `SPC h d s` and paste the result in a comment here.

I tested it with the following configuration and it worked. I had to change the 3rd line (`3w "ayw`) to `3w "ayj'` because otherwise the `w` was also copying the trailing `'`, but it is not related to your bug it seems. (It may be a configuration on my side though).

----

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. e72dd8a)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion bepo better-defaults colors dockerfile emacs-lisp emoji erc eyebrowse finance git github haskell html
                 (ibuffer :variables ibuffer-group-buffers-by 'projects)
                 ipython-notebook javascript latex markdown ocaml org python ranger restclient semantic shell streakycobra syntax-checking themes-megapack version-control yaml)
```

**Comment by TheBB** [comment]
It works fine here too. I followed your keystrokes exactly in (I assume) ruby mode, and no problems.

Maybe try updating your packages?

**Comment by askreet** [comment]
Hi, sorry for the delay. My configuration is:
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.104.2
- Spacemacs branch: master (rev. 074f425)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 emacs-lisp git
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking semantic version-control php ruby rust go puppet yaml themes-megapack osx)
```

**Comment by askreet** [comment]
And, just confirmed it's still occuring, I opened a junk buffer called .rb (using M-x open-junk-file) which activated ruby-mode and got up to the first `@q`:

```ruby
# instructions omitted for brevity
it 'should do a THING' do
  thing = Class1.thing('zone')
  thing.client.do_stuff
end

it 'should do a STUFF' do
  sywnndw"aPxndw"aPxtuffa = Class1.foo('zone')
  foo.client.do_stuff
end
```

**Comment by askreet** [comment]
Some data: I just replaced my list of layers with yours @StreakyCobra and did not have the issue. I'm going to spend some time slowly adding in layers I have that you do not (e.g. ruby -- I still had ruby-mode without the ruby layer, though, just not EnhRuby).

**Comment by askreet** [comment]
Simply adding the ruby layer to your configuration (on `master`, as shown in my paste above) causes the error to return. I had to remove the `bepo` and `streakycobra` layers to avoid `SPC f e R` from failing checks.

@TheBB were you using the ruby configuration layer, or the stock ruby-mode? Would you mind trying the ruby configuration layer with my example and see if you are able to reproduce?

**Comment by TheBB** [comment]
I will check when I get home. I should note that the ruby layer has just been changed to use stock ruby (by default) and not enhanced ruby mode.

**Comment by StreakyCobra** [comment]
Can't reproduce on `develop` with `ruby` layer activated in a buffer in `ruby-mode` :-(
