### ISSUE TITLE
company mode error in sh-mode

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#3336]
when I input something in sh-mode, the company mode can't work and give me the following error.

```Company: backend company-capf error "No items suitable for an index found in this buffer" with args (candidates i)```

**Comment by yu-yuxuan** [comment]
I have the same problem. My emacs version is 25.0.5

**Comment by TheBB** [comment]
We don't have auto completion in `sh-mode`. How did you get that?

**Comment by TheBB** [comment]
I'm closing this since we don't support auto-completion in `sh-mode`. If you have more information, please reopen.

**Comment by HQingYi** [comment]
I also need the auto-complete in sh-mode. :cry:

**Comment by zilongshanren** [comment]
@HQingYi 

Add the following code snippets into your own layer.

```
(spacemacs|defvar-company-backends sh-mode)
(spacemacs|add-company-hook sh-mode)

```

**Comment by joehillen** [comment]
@zilongshanren If that works, then why isn't in the layer already?

Is there any reason _not_ to autocomplete in sh-mode?

**Comment by syl20bnr** [comment]
Can you open a new issue so we can investigate ?

**Comment by tuhdo** [comment]
I got this error also. But it comes from one my packages, which are `nasm-mode` and `pdf-tools`. Pretty sure stock Spacemacs works fine.

**Comment by tuhdo** [comment]
It is because of a bug in Imenu: https://github.com/skeeto/nasm-mode/issues/5
