### ISSUE TITLE
Emacs freezes for 10-12 seconds

### ISSUE THREAD

**Issue by manfredlotz** [syl20bnr/spacemacs#3338]
Running Fedora 22, Emacs 24.5.1 and spacemacs-0.104.2. 

If I start Emacs, then do   SPC f e h, then select org, and do a search for some string Emacs freezes for 10-12 seconds. CPU is at 100%.

If I start Emacs then load ~/.emacs.d/layers/org/README.org directly, and do the same search for a string then there is no freeze.

I observed that when doing SPC f e h emacs seems to load every layer available which looks weird.
Here the beginning of the messages.

Open the quickhelp.
PNG warning: Interlace handling should be turned on when using png_read_image
Loading /home/manfred/.emacs.d/layers/+fun/games/config.el (source)...done
Loading /home/manfred/.emacs.d/layers/+vim/unimpaired/funcs.el (source)...done
Loading /home/manfred/.emacs.d/layers/+vim/evil-snipe/config.el (source)...done
Loading /home/manfred/.emacs.d/layers/+vim/vinegar/funcs.el (source)...done
Loading /home/manfred/.emacs.d/layers/+vim/vinegar/config.el (source)...done
...

Any idea what could cause it? 
Thanks, Manfred

**Comment by FiloSpaTeam** [comment]
Emacs freeze too with | char in a lambda function in Ruby files.

**Comment by manfredlotz** [comment]
I just observerd that the freeze takes place if I search for the string 'link'. I searched for other strings and no freeze happened. If I search for 'link' in other documents, e.g. in the Django documentation, no freeze.
-- Manfred

**Comment by manfredlotz** [comment]
I found out something new. I download the emacs tar ball and experimented with build options in order to see if I could find something where Emacs won't freeze. I did.

In the end font aliasing seems to be the cause of the problems. If I configure like this there is no freeze

./configure  --without-all     \
        --with-m17n-flt        \
	--with-jpeg            \
	--with-dbus            \
	--with-freetype        \
	--without-xft             \
	--with-xpm             \
	--with-xaw3d           \
	--with-xiim            \
	--with-libotf          \
	--with-selinux         \
	--with-gpm             \
        --with-imagemagick     \
	--with-x-toolkit=yes   \
	--with-png             \
	--with-tiff            \
	--with-gif             \
	--with-gsettings       \
	--with-gnutls          \
	--with-rsvg            \
	--with-xml2            \
	--with-gconf           \
	--with-gpm   

Observe that I have used without-xft. I have no idea what the solution will be as without aliasing things are more or less ugly.

**Comment by manfredlotz** [comment]
One more observation. It seems that the freeze is dependant upon the font chosen in .spacemacs.

I had defined Lucida Grande Mono when the freezes happened. Changing this to DejaVu Sans Mono, and no freeze in README.org.

**Comment by manfredlotz** [comment]
I don't know how to pursue this bug. I have no clue if it is a bug in Emacs, Evil, Spacemacs or in the Lucida Font.

**Comment by FiloSpaTeam** [comment]
With last update, 105, emacs freezes during Ruby autocomplete. I launched Ruby console with C-c C-k as always

**Comment by manfredlotz** [comment]
I had the same today (also update to 105) with auto-comple and nim-mode. I think this is a new issue. It has nothing todo with the fonts.
