### ISSUE TITLE
idris: "error in process filter: Selecting deleted buffer" crash when saving a proof

### ISSUE THREAD

**Issue by juxtin** [syl20bnr/spacemacs#3344]
The Idris layer is working _much_ better these days (thanks!), which means I've been using it long enough to notice what seems like a rather serious bug. Saving a proof from the interactive prover causes Emacs to crash on two of my computers, so I'm wondering whether others can reproduce it and/or help me narrow down the cause.

Steps to reproduce:
With the following code in an idris-mode buffer: 

```
test_proof : 1 = 1
test_proof = ?prove_me
```
1. Use `SPC m s b` to eval the buffer, which will pop up an `*idris-holes*` buffer challenging you to prove that 1 does, in fact, equal 1.
2. Click the `[P]` button to enter the interactive prover.
3. Enter `trivial` in the `*idris-proof-script*` buffer and advance to it with `M-n`.
4. Use `C-c C-q` to save the completed proof, answering `y` at the prompt.

On both of my computers, these steps leave Emacs in a totally unresponsive state with `error in process filter: Selecting deleted buffer` appearing at the bottom.

**Comment by holguinj** [comment]
Well, deleting elpa and reinstalling all my Emacs packages seems to have fixed the issue.

**Comment by joom** [comment]
I have [the same problem](https://xkcd.com/979/), and deleting elpa and reinstalling the packages didn't help. Can we reopen this issue?

**Comment by blinky3713** [comment]
Same problem, tried wiping .emacs.d and reinstalling all packages but no luck

**Comment by syl20bnr** [comment]
Reopened.
