### ISSUE TITLE
haskell-cabal-mode bindings not enabled if *.cabal file is opened before *.hs file

### ISSUE THREAD

**Issue by bjarkevad** [syl20bnr/spacemacs#335]
Bindings defined for `haskell-cabal-mode` is only enabled if a *.hs file is opened, and therefore `haskell-mode` settings loaded, before any *.cabal file is opened.

**Comment by syl20bnr** [comment]
@bjarkevad  This bug is still here ?

**Comment by bjarkevad** [comment]
I assume so

**Comment by d12frosted** [comment]
@TheBB please, add 'haskell' label here :smile:
