### ISSUE TITLE
evil-mc fails to install

### ISSUE THREAD

**Issue by rebcabin** [syl20bnr/spacemacs#3370]
on a fresh clone of developer branch and a freshly updated git:

```
$ git --version
git version 2.6.1
```

and a fresh clone of spacemacs develop branch, with .spacemacs deleted:
```
System Info

    OS: darwin
    Emacs: 24.5.1
    Spacemacs: 0.105.0
    Spacemacs branch: develop (rev. e72dd8a)
    Distribution: spacemacs
    Layers:

    (emacs-lisp)
```

I get errors installing evil-mc:

```
    (Bootstrap) Installing evil...
    (Bootstrap) Installing evil-leader...
    Found 71 new package(s) to install...
    --> fetching new package repository indexes...
    --> installing spacemacs:evil-mc... [22/71]An error occurred while installing evil-mc (error: (wrong-type-argument arrayp nil))
    --> installing spacemacs:window-numbering... [71/71]
    Found 1 new package(s) to install...
    --> fetching new package repository indexes...
    --> installing spacemacs:evil-mc... [1/1]An error occurred while installing evil-mc (error: (wrong-type-argument arrayp nil))

[110 packages loaded in 229.076s]
```
here is backtrace from `emacs --debug-init

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  tar--check-descriptor(nil)
  tar-get-file-descriptor("PaxHeader/PaxHeader-pkg.el")
  package-tar-file-info()
  byte-code("\303\304!rq\210\305\216	\306=\203

**Comment by rebcabin** [comment]
This repros easily on one of my two machines (a yosemite mac), but does not repro on another of my machines (an El-Capitan mac).

**Comment by rebcabin** [comment]
Ok, the problem just went away on my triple-check of repro this morning.  Go figure.

**Comment by justbur** [comment]
Looking around online it seems like it could be an issue with the version of `tar` used on your computer. what does `tar --version` say?

**Comment by justbur** [comment]
Actually, that `PaxHeader-pkg.el` file seems to have been created by mistake. I think there's a bug here somewhere, but it's going to be hard to pin down, because I can't recreate it. Glad it's working at least

**Comment by TheBB** [comment]
I can reproduce this (or something similar) on my Windows laptop. I will reopen.

**Comment by justbur** [comment]
@TheBB do you get the paxheader files? They aren't produced for me

**Comment by TheBB** [comment]
I'll look at it when I can. I don't use that computer very often. :-)

**Comment by louy2** [comment]
I met this problem on Windows, too, but I don't need it so I just added it to excluded.

**Comment by zenmoto** [comment]
For what it's worth, I've been having this same problem.  I added evil-mc to the excluded list, launched emacs, installed it via package-install, removed it from the excluded list, and everything seems to load correctly.

I am now getting a message in `*Warnings*` with the same (albeit common) elisp error, not sure if it points the way at all towards the problem.
`Error (use-package): theme-changer :config: Wrong type argument: arrayp, nil`

This is also on a Yosemite mac.

**Comment by louy2** [comment]
May I ask what's the reasoning behind adding it to the core in the first place? It is not even enabled by default, and no mapping of toggling it is setup. It is now residing in the core as if it is added via additional package, which seems to me meaningless.

**Comment by justbur** [comment]
The commit says it was added for testing purposes https://github.com/syl20bnr/spacemacs/commit/31229cb1f5a556a1d368658aa52b0d8482d1c04e. @syl20bnr it would probably be better to add this to a testing layer, even if it is meant to be added to the core eventually.

**Comment by rebcabin** [comment]
I've had this come back since I did a `git pull --rebase` on the develop branch of spacemacs.  OSX Yosemite, as documented in my first posting.  It went away when I switched to the master branch of spacemacs.

**Comment by rebcabin** [comment]
The workaround by @zenmoto worked for me.  I will keep an eye out for recurrence.  Note I have other macs that do not exhibit the problem!

**Comment by louy2** [comment]
Ahh, I see, for testing github fetcher of quelpa it seems. 

I didn't check debug trace, but on this laptop which I can reproduce it, a PaxHeader folder is installed at `%HOME%\AppData\Local`, with no `.el` files in it. It contains a `.meteor` folder, on the other hand.

**Comment by syl20bnr** [comment]
This has been added to test evil-mc which is an important package.
I was not able to reproduce the install bug of this package for now but I will let it in develop since this error should not compromise Spacemacs and we should not silence it to have a better chance to fix it.

**Comment by justbur** [comment]
If you google it pax headers have something to do with versions of tar which would explain why not everyone sees the bug.

**Comment by syl20bnr** [comment]
So this bug is more critical than expected, seems like evil-mc is the first compressed archive we try to install with quelpa. mmmmmhh but what is different with basic MELPA/packages.el management ?

**Comment by justbur** [comment]
I think this should be reported to quelpa

**Comment by rebcabin** [comment]
I am now getting similar failures for other packages on one of my machines (but not on others).  I can no longer "Upgrade Packages" reliably with spacemacs on that machine.  Will report details when I can get back to that machine.

**Comment by vkz** [comment]
same bug here on a freshly installed `develop` branch on OSX Yosemite. Do I need it? I excluded it for now but would this compromise my experience of **Spacemacs**?

**Comment by xificurC** [comment]
Same issue here for more than a week on a Win7. No issues on an Arch Linux.

@vkz as noted by @louy2 above the package isn't enabled yet, just pulled in for testing, so excluding it shouldn't pose any issues for now.

**Comment by h1kka** [comment]
You can manually install evil-mc via `SPC : package-install [RET] evil-mc [RET]`. Error will gone after Spacemacs reload. But if you will press "Update Packages" on Spacemacs home buffer, error will come back.
Tested on win7.

**Comment by xificurC** [comment]
@h1kka that's because [you're not supposed to install packages through package-install](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#new-packages-from-elpa-repositories).

**Comment by h1kka** [comment]
@xificurC yeah, not recommended, but recommended ways doesn't work :)

**Comment by xificurC** [comment]
@h1kka I'm just saying the documentation clearly states if you install a package through `package-install` or `paradox` it won't persist. So we need to wait for a fix. As noted previously if you don't use this package you can put it in the excluded packages list for now or disregard the error.

**Comment by justbur** [comment]
#3727 should resolve this, although this seems to be a problem with using quelpa on certain people's machines

**Comment by louy2** [comment]
@xificurC 
It's not that all the packages installed via `package-install` and `paradox` won't persist. Packages don't persist because by default Spacemacs purges packages not configured on start. In this case `evil-mc` is already configured, so it will persist. The rollback part is what would be lost, but it being a new package is not that important.

@justbur 
Thanks for the fix, but yeah, I am kinda worried about cross-platform problems quelpa may pose. It is good enough to have it as a way to install local private packages though.
