### ISSUE TITLE
ESS no completions for julia

### ISSUE THREAD

**Issue by izahn** [syl20bnr/spacemacs#3376]
With the `ess` and `autocomplete` layers enabled I would expect company completion in ess-julia-mode, but this does not currently work since R company sources are pushed to `company-backends` for all ess modes. When typing in a `ess-julia-mode` buffer I get 
```
Company: An error occurred in auto-begin
Company: backend (company-R-args company-R-objects) error "Wrong type argument: stringp, nil" with args (candidates si)
```

A straightforward solution is to stop messing with the ESS autocompletion features and just let ESS set it up for us (which ESS does by default). I've implemented that solution in PR https://github.com/syl20bnr/spacemacs/pull/3372. Please consider merger https://github.com/syl20bnr/spacemacs/pull/3372 so we can have completion working correctly in ESS.

**Comment by mashu** [comment]
Hi, what is the status of this ? Can we get completion using company setup instead of auto-complete ?

**Comment by izahn** [comment]
The status of this is that it is fixed and working as expected. If it
doesn't work for you please open a new bug report.
