### ISSUE TITLE
Suggestion: Use Different ELPA Directories for Different Emacs Versions

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#3379]
Using the same `.emacs.d/elpa/` directory for different versions of Emacs causes errors, since the `.elc` files of one version can be incompatible with other other versions. I propose to set the `package-user-dir` in `core-configuration-layer.el` according to the variable `emacs-version`. Instead of a single `elpa` directory, we will have `elpa/24.3`, `elpa/24.4`, etc. The end result is to be able to use the same `.emacs.d` directory for different Emacs versions.
This probably requires some other changes to the core and to the tests as well.

**Comment by StreakyCobra** [comment]
Pending PRs: #3384 #4312

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
