### ISSUE TITLE
linum-relative has changed its toggle to a minor-mode

### ISSUE THREAD

**Issue by StreakyCobra** [syl20bnr/spacemacs#3387]
A new `linum-relative` version ended in melpa today and this version doesn't have `linum-relative-toggle` any longer but a `linum-relative-mode`, as it can be seen [here](https://github.com/coldnew/linum-relative/commit/8f4f4836dc834d159b6e5116d41bd6a6ccb7f49e#diff-645091e7ee5ccd60ec79422bccd16294L162).

**Comment by zilongshanren** [comment]
fixed,  please check

**Comment by StreakyCobra** [comment]
Hum, I was going to try your change, and I just noticed they [added back the toggle](https://github.com/coldnew/linum-relative/commit/730607108c87fab59535215ec7571ea0169cc6c2). So, it's working again.

Closing, thanks anyway :-)
