### ISSUE TITLE
sheme in orgmode

### ISSUE THREAD

**Issue by autosquid** [syl20bnr/spacemacs#3388]
This is my config:
```
(setq geiser-default-implementation 'guile)


(org-babel-do-load-languages
'org-babel-load-languages
'((scheme . t)
 (emacs-lisp . t)
 (ruby . t)
 (R . t)
 (python . t)
 (C . t)
 (sh . t)))
```

Here is a test source code block in orgmode:

```
#+begin_src scheme :results output
(write "hello world")
#+end_src
```

When I press `C-c C-c` to execute the code block, a new window(buffer) opens and become selected.

**Comment by sooheon** [comment]
I had the same problem, and made a question on emacs stack exchange [here](http://emacs.stackexchange.com/questions/17240/org-babel-evaluation-of-code-block-always-creates-new-window)

**Comment by sooheon** [comment]
As per wvxvw's comment in there, customising `geiser-repl-use-other-window` to `nil` fixed this issue for me.

**Comment by StreakyCobra** [comment]
@autosquid Does @sooheon's solution solved your issue?

**Comment by autosquid** [comment]
@StreakyCobra  yes, many thanks to @sooheon  for letting me know.
