### ISSUE TITLE
Error after reinstalling spacemacs

### ISSUE THREAD

**Issue by Immortalin** [syl20bnr/spacemacs#3389]
I deleted my .emacs.d and reinstalled spacemacs and have been getting all sorts of errors. I tried reinstalling and even recompiling but to no avail. All of the errors are variations of the same type. This is the latest one:
```
Error (use-package): evil-anzu :init: Symbol's function definition is void: global-anzu-mode
Warning (initialization): An error occurred while loading `/home/immortalin/.emacs.d/init.el':

error: Required feature `anzu' was not provided

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

I did not copy down all of the errors but all of them revolves around functions that seem to be missing and errors that occured while loading .emacs.d/init.el even though I already have a .spacemacs.d.  Evil mode also seems to be completely broken. `SPC-hds` does not work. The errors change every time I try to reinstall spacemacs.

Emacs version 24.5, spacemacs develop branch c5e01eb7811... Ubuntu 14.04.3 running Xfce.

**Comment by justbur** [comment]
The error you posted means that emacs can't find the anzu package. Is there an anzu folder with a date in ~/.emacs.d/elpa?

**Comment by syl20bnr** [comment]
This seems like a network issue. Can you paste the whole message buffer or use a gist ? Don't be afraid to post all the errors you get.

**Comment by Immortalin** [comment]
Purged .spacemacs.d and rebuilt init.el, problem is fixed. Suspected reason is the large number of configuration layers enabled or corrupted line endings due to multiple transfers between different operating systems. Have yet to test out either hypothesis.
