### ISSUE TITLE
Cannot activate bepo layer

### ISSUE THREAD

**Issue by brabalan** [syl20bnr/spacemacs#3392]
I'm on the branch develop and I tried adding `(setq-default dotspacemacs-configuration-layers '(bepo))` to my .spacemacs file, but the new keybindings are not taken into account. I tried putting the line at the end of the file (before the last comment), in the `dotspacemacs/user-init` function, and in the `dotspacemacs/user-config` function, to no avail. When I lookup the variable, I see that it is set correctly to `(bepo)`.

**Comment by d12frosted** [comment]
Please, checkout `.spacemacs` [template](https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template). 

You need to put that into `dotspacemacs/layers` function.

**Comment by StreakyCobra** [comment]
The `setq-default dotspacemacs-configuration-layers` already exists at the top of the file, just add a line with `bepo` there :-)

**Comment by brabalan** [comment]
@StreakyCobra Doh, of course! It works great. Sorry for the noise.

**Comment by CyrilWaechter** [comment]
> The `setq-default dotspacemacs-configuration-layers` already exists at the top of the file, just add a line with `bepo` there :-)

Writing bepo alone is not enough. I'm sure it is pretty clear for you guys but for newcomers (like me) it is not clear enough. So if you don't mind I just write down the full line here in case someone else needs it : 
`(keyboard-layout :variables kl-layout 'bepo)`

**Comment by duianto** [comment]
There might have been a separate `bepo` layer when this issue was posted (2015), but your right it's now part of the `keyboard-layout` layer as a `kl-layout` variable.
https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bintl/keyboard-layout

Thanks for posting the current solution. I'm sure it will be helpful for anyone else that finds this issue.
