### ISSUE TITLE
iedit-mode is no longer available as C-;, even in holy-mode

### ISSUE THREAD

**Issue by Peeja** [syl20bnr/spacemacs#3402]
I've been using `iedit-mode` on <kbd>C-;</kbd>, the default binding, and as of a recent update Spacemacs blocks that binding, even in holy-mode. It would be nice to have it back in holy-mode, or at least have an easy way to turn it back on again globally for those of us who use it.

**Comment by d12frosted** [comment]
Could you please tell what is bound to `C-;` for you (`SPC h d k C-;`)? For me it's `flyspell-auto-correct-previous-word`.

**Comment by Peeja** [comment]
It's undefined.

**Comment by Peeja** [comment]
To clarify, what's happening here is that [the `iedit` package is configured with `iedit-toggle-key-default nil`](https://github.com/syl20bnr/spacemacs/blob/074f425dc5d233f24195ecc3021eb96ac9d55d4d/layers/%2Bdistribution/spacemacs/packages.el#L1374), meaning [no keybinding should be added](https://github.com/tsdh/iedit/blob/fd801e77dfdcfa0bdeadc153a9fb637dab2b4bb4/iedit.el#L97). A user's config can set that variable back to `(kbd "C-;")`, but at that point it's too late: [the moment](https://github.com/tsdh/iedit/blob/fd801e77dfdcfa0bdeadc153a9fb637dab2b4bb4/iedit.el#L216) has passed.

Although, I don't have my head firmly wrapped around the order of Spacemacs initialization, so maybe there's still a place the user can add that config?

**Comment by AlejandroCatalina** [comment]
So, should we just initialize `iedit` with `iedit-toggle-key-default "\C-;"`?
