### ISSUE TITLE
Assess org-projectile; consider replacing org-repo-todo with it

### ISSUE THREAD

**Issue by MerelyAPseudonym** [syl20bnr/spacemacs#3405]
Honestly, I'm not sure that one is better than the other, but I noticed that [the `org-projectile` project](https://github.com/IvanMalison/org-projectile) seems to be more actively developed.

**Comment by TheBB** [comment]
Since org-repo-todo is [broken](https://github.com/waymondo/org-repo-todo/issues/5), seems promising (assuming org-projectile *isn't* broken, obviously).

**Comment by ridget** [comment]
@TheBB this is something Im interested in, what's involved/required for the evaluation? Happy to submit a PR for the org mode layer if this has already been done?

**Comment by AdrieanKhisbe** [comment]
*Up :)*
Interested in that too!

**Comment by mkaito** [comment]
:+1:

**Comment by syl20bnr** [comment]
Done in develop thanks to @TheBB 💜

**Comment by leezu** [comment]
Thanks for the work!

It seems however that

      (org-projectile:per-repo)

is called even if `org-projectile-file` is [set to an absolute path](https://github.com/syl20bnr/spacemacs/blob/8f9914903dbca24e01e15aa8bf7628471a016dcf/layers/%2Bemacs/org/packages.el#L516). Calling `per-repo` means that org-projectile is [used in per-repo mode](https://github.com/IvanMalison/org-projectile/blob/9e7453874e472ade60b95af44167d5a6d4e24317/org-projectile.el#L79). Looking at the [documentation](https://github.com/IvanMalison/org-projectile#per-repo-todo-files) this seems like an optional feature that should only be enabled if `org-projectile-file` is set to a relative path.

For me this results in the behaviour that `org-projectile-file` is ignored, if set to an absolute path.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
