### ISSUE TITLE
What's the file finder plugin it uses?

### ISSUE THREAD

**Issue by azer** [syl20bnr/spacemacs#3406]
Hi there,

I loved the experience, and would like to get some of the simple features that spacemacs, in my emacs configuration.

What is the file finder plugin that you use ? I want to get the same thing working in my emacs. 

Thanks

**Comment by louy2** [comment]
It is [emacs-helm/helm](https://github.com/emacs-helm/helm).

**Comment by TheBB** [comment]
Specifically, `helm-find-files`.
