### ISSUE TITLE
clang-format wrong command line

### ISSUE THREAD

**Issue by EricTing** [syl20bnr/spacemacs#3408]
Tried to use `clang-format-region` or `clang-format-buffer` to format my c++ code and had the error

```
clang-format-region: (clang-format failed with code 1: clang-format: Unknown command line argument '-sort-includes'.  Try: '/usr/local/bin/clang-format -help')
```
Had no problem using `clang-format` in the terminal.

system: Mac OSX 10.11
emacs:  24.5.1 
clang-format: clang-format version 3.8.0 (tags/google/testing/2015-07-31)

my settings for c++ in `~/.spacemacs`

```
     (c-c++ :variables
            c-c++-default-mode-for-headers 'c++-mode
            c-c++-enable-clang-support t)

```

**Comment by TheBB** [comment]
This is an upstream problem. It's in the [source](https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/clang-format.el). Report it to LLVM or whoever runs this project please.

**Comment by TheBB** [comment]
Closing in favor of #3584 which has more information.
