### ISSUE TITLE
`magit-blame-mode` interferes with `linum-relative`

### ISSUE THREAD

**Issue by bjarkevad** [syl20bnr/spacemacs#341]
When `magit-blame-mode` is active and `linum-relative` is enabled, relative line number do not reflect the correct amount of lines you'd need to jump to hit that line.

To reproduce:
- Open a file currently under git source control
- Press `SPC g b` to enable `magit-blame-mode`
- Try to navigate around the file using both `#{j,k}` movements as well as press `{j,k}` multiple times
- Observe that the number put in front of `#{j,k}` does not match the amount of keypresses needed when doing single movements `{j,k}`

I'm not sure if this is a bug in `spacemacs`, `magit`, `linum`, `linum-relative` or `evil-mode`, but I thought I'd put it here to shed some light on the issue.

**Comment by syl20bnr** [comment]
@bjarkevad Did you report this issue in magit repo ?

**Comment by bjarkevad** [comment]
I haven't no, been busy unfortunately :-)

**Comment by TheBB** [comment]
No movement on this in over a year, and nobody seems to want to report this upstream, so for now I will close this.
