### ISSUE TITLE
Document Each Individual Package Used in Layer README

### ISSUE THREAD

**Issue by louy2** [syl20bnr/spacemacs#3421]
Currently the normal is to mention the front-facing packages in the _Features_ section. A list of all the packages used linking to the homepage of each would offer convenience and a better picture of how the layer operates. More elaborate documentation on how each package is configured can take this as a start point.

**Comment by syl20bnr** [comment]
We have to be sure to not paraphrase the code too much. We could add a helm action for helm-spacemacs which would go to the list of packages.
