### ISSUE TITLE
When I start spacemacs

### ISSUE THREAD

**Issue by ZhouXiaolin** [syl20bnr/spacemacs#3422]
the start message show "218 packages loaded in 1.977s"
but spacemacs no response  <-20s->  i think
why?  i can see emacs use net  
or it's normal situation?

i wish you can understand what i say

**Comment by TheBB** [comment]
This is probably due to Helm. SSee https://github.com/emacs-helm/helm/issues/1000

**Comment by ZhouXiaolin** [comment]
i close net
then all fine
......😓
maybe when start spacemacs will check version,it make my emacs hangs

**Comment by TheBB** [comment]
Yep, that sounds like the same issue. You can follow the instructions in https://github.com/emacs-helm/helm/issues/1000 to fix it.

**Comment by syl20bnr** [comment]
Seems like a FAQ is needed for this recurring issue.
