### ISSUE TITLE
Disabling clj-refactor removes also cider menu

### ISSUE THREAD

**Issue by kotarak** [syl20bnr/spacemacs#3424]
After disabling clj-refactor, eg. with `(setq clojure-excluded-packages '(clj-refactor))`, or only by removing the minor mode via `(spacemacs|use-package-add-hook clj-refactor :post-init (remove-hook 'clojure-mode-hook 'clj-refactor-mode))` the menu settings for cider are gone. Only `SPC m T` and `SPC m f` are still available. Calling eg. `cider-connect` directly still works.

**Comment by sooheon** [comment]
Can confirm, but no clue as to why this could be happening.

**Comment by jasonij** [comment]
This appears to be resurfacing for me at least in the develop branch. I have not excluded clj-refactor but it does not appear to be loading and the result is no Cider.

I get this error `File mode specification error: (void-function clj-refactor-mode)`. It was working until fine a day or two back.

**Comment by jasonij** [comment]
Version bumping and wiping elpa got me Cider mode without any refactoring, new error message `File mode specification error: (void-variable cljr-inject-dependencies-at-jack-in)`.

**Comment by zane** [comment]
Still having this issue in 2018.

**Comment by jr0cket** [comment]
@zane the Clojure layer has been updated to make clj-refactor optional, in https://github.com/syl20bnr/spacemacs/pull/11397 

This pull request excludes clj-refactor by default, so removing any previous config in .spacemacs should resolve this issue.

Suggest this issue be closed if there are no further issues.  Thank you

**Comment by zane** [comment]
Sounds good, and thank _you_!
