### ISSUE TITLE
git/magit: gg shadows buffer reload

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#3425]
Magit uses `g` to reload the buffer.

It should be changed when vim mode is active, or `G` and `gg` deactivated.

**Comment by stshine** [comment]
See this : 
https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#evilified-modes

**Comment by TheBB** [comment]
Yep, this is standard evilified behaviour.

**Comment by Profpatsch** [comment]
Ah, I didn’t know that. Thanks!
