### ISSUE TITLE
smart search (SPC-/): Don’t insert current word

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#3429]
I noticed that nearly everytime I want to use smart search I first have to delete the input field.

I also noticed that when you hit `*` you can directly search for that input argument in that micromode with `/`, this renders the auto-insert of `SPC-/` moot.

**Comment by StreakyCobra** [comment]
`SPC s p` does the same as `SPC /` without pre-filing the input field.

**Comment by justbur** [comment]
Yes, and this is easy to change in your own config
```elisp
(evil-leader/set-key "/" 'spacemacs/helm-project-smart-do-search)
```

**Comment by StreakyCobra** [comment]
Thinking more about it, it could be nice to have `/` and `*` equivalent to `SPC /` and `SPC *`.

- `*` search the word under cursor (or region) in the current buffer, enter micro-mode
- `/` ask for an expression and search it in the current buffer, enter micro-mode
- `SPC *` search the word under cursor (or region) in the current project
- `SPC /` ask for an expression and search it in the current project

**Comment by justbur** [comment]
@StreakyCobra I like it! Open a pr please

**Comment by syl20bnr** [comment]
@StreakyCobra :+1:

**Comment by d12frosted** [comment]
Related: #3432

**Comment by krizex** [comment]
I still have the same issue when I use `ag` instead of `grep`.
When I use `grep`, (SPC-/) works fine, it automatically insert the current word, but it does not work with `ag`.
I add `(evil-leader/set-key "/" 'spacemacs/helm-project-do-ag-region-or-symbol)` to my .spacemacs as a workaround.
Wish someone here could solve this issue.
