### ISSUE TITLE
Function location of spacemacs/ functions is missing

### ISSUE THREAD

**Issue by Profpatsch** [syl20bnr/spacemacs#3430]
When you describe-function a function that spacemacs defines, the link in the help buffer points to the wrong location.

Example:
`spacemacs/helm-project-smart-do-search-region-or-symbol is an interactive Lisp function in`init.el'.`

A click on `init.el` leads to the spacemacs initialization file instead of the line where the function is defined (which is the behaviour for normal emacs functions).

**Comment by justbur** [comment]
Technically, that function is not defined where you think it is, because the defun in inside another defun (the init function), which is not called right away. This is probably the reason emacs is not "finding it". There are a couple of ways to correct this, but I'm not sure what (if anything) @syl20bnr will want to do about it.

**Comment by syl20bnr** [comment]
This is the case when the functions are defined by macros, Emacs does not go to the macro location. This can confuse the user. Not much we can do on our side except explicitly define the functions outside of a macro which is not practical in most cases depending on the usefulness of the macro (I.e. How many times it is really used ?).

**Comment by d12frosted** [comment]
What if we use some naming policy for macros functions, so users can distinguish macros and regular functions? For example, `spacemacs-macro/xxx`.

**Comment by TheBB** [comment]
You mean functions created in macros as opposed to functions created normally? I don't see that adding much value. (And it's verbose as hell.) If you mean a naming policy for macros, we have that already.

I think this is just something we have to live with. It's Emacs' problem.

**Comment by justbur** [comment]
Here's a simple way to change the way functions are defined so that they are discoverable
In "layers/+distribution/spacemacs/packages.el":
```elisp
(defun spacemacs/init-foo ()
  (use-package foo
    :config
    (require 'spacemacs-foo-funcs)))
```
In "layers/+distribution/spacemacs/extra-funcs/spacemacs-foo-funcs.el":
```elisp
(defun spacemacs/foo-do-bar ())
```

**Comment by StreakyCobra** [comment]
Is this issue a `Wontfix` or a `Enhancement`?

**Comment by StreakyCobra** [comment]
@syl20bnr Up

**Comment by nixmaniack** [comment]
justbur's way sounds good to me, I've always faced issues when functions are defined inside `use-package` and `gd` doesn't work in that case.

**Comment by olejorgenb** [comment]
Sorry for the spam, but I want to voice my support for this issue. Quick access to help and easy navigation into the code depths are one of the reasons emacs is great. It's also much easier to contribute to projects where the source code is easily navigable. 

For discoverability: `elisp-slime-nav-find-elisp-thing-at-point`

**Comment by Profpatsch** [comment]
yeah

**Comment by nixmaniack** [comment]
Let's keep this open? This is still an issue and would be better if all code becomes navigable with standard emacs tooling.

**Comment by syl20bnr** [comment]
Mmhhh do we still have this issue ? We moved all the functions to `funcs.el` files to avoid the issue where Emacs could not locate the function's definition. If we still encounter functions with no location we should move them to `funcs.el`.

**Comment by lebensterben** [comment]
Not able to reproduce at current develop branch.
