### ISSUE TITLE
How to disable   fetching new package repository indexes (internet update packages)

### ISSUE THREAD

**Issue by ghost355** [syl20bnr/spacemacs#3438]
I have not an internet connection on one of my computers. How to start Spaceacs?
I see fetching new package repository indexes message and my emacs freeze.

**Comment by syl20bnr** [comment]
That's a good question, surprisingly enough we have no toggles for now! Seems to me a fundamental variable to add.

**Comment by ghost355** [comment]
Is any way to starting Spacemacs without Internet? )))

**Comment by syl20bnr** [comment]
This is a weird issue, fetching of package repository indexes happen only if some packages are missing, so obviously you need an internet connection to install them.
We can add a variable to disable this behavior but it may result in surprising missing packages.
