### ISSUE TITLE
<SPC k> is unconveniently reserved for lisp code

### ISSUE THREAD

**Issue by PierreR** [syl20bnr/spacemacs#3441]
The pink state aka `Lisp code state` (as the name implies) is meant for editing lisp files.

Because it quickly shows up when trying `SPC k` I have tried to exclude the `evil-lisp-state` package.

Then to my surprise `SPC k` was no more available anymore.

This is a bit unfortunately because:
- some `smartparens` keybindings useful for every file type could be made available there. For instance I miss a binding for `sp-unwrap-sexp`.
- `SPC k` name does not imply lisp, does it ?

Could the `lisp code state` be made less easily accessible and `SPC-k` reserved for general `smartparens`and other related features that work across all file type ?

**Comment by syl20bnr** [comment]
`lisp state` already include functions that works in all modes under ``SPC k ` ``. `sp-unwrap-sexp` is under `SPC k W` I believe.

**Comment by PierreR** [comment]
> lisp state already include functions that works in all modes under SPC k `
Well that's what I am complaining about. We have some specific (the lisp state mode) that works for all modes. This is quite confusing. You quickly end up in a pink state that makes no sense for non-lisp files.

**Comment by Spadavecchia** [comment]
Was `SPC k` removed? I'm trying use it, but is not assigned. In documentation there is reference to  shortcut. https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#editing-lisp-code

**Comment by TheBB** [comment]
It's not removed, but please make sure you are fully updated, both Spacemacs and packages, as some changes were made to it recently.

**Comment by Spadavecchia** [comment]
I updated Spacemacs and nothing. Delete it and reinstall. Now all is working again. Thank you.
Amazing work by the way.

**Comment by TheBB** [comment]
Good :+1:. Note that when I say update both Spacemacs *and* packages it's *not* enough to just update Spacemacs.
