### ISSUE TITLE
a typo

### ISSUE THREAD

**Issue by ForrestAlfred** [syl20bnr/spacemacs#3446]
![screen shot 2015-10-18 at 5 57 15 pm](https://cloud.githubusercontent.com/assets/8122371/10563586/d7d870e8-75c1-11e5-8900-fe5e4e5c364f.png)

**Comment by ForrestAlfred** [comment]
I figure that the avy word  may be any word.

**Comment by TheBB** [comment]
No, it's [avy](https://github.com/abo-abo/avy). :-)

**Comment by TheBB** [comment]
You may like to set `ns-use-srgb-colorspace` to `nil` to fix your modeline colors, by the way.

**Comment by ForrestAlfred** [comment]
thanks , by the way , but hows the normal color looks like? I have set ns-use-srgb-colorspace to nil just now, and it seems no difference.

**Comment by TheBB** [comment]
Your separators have different colors. Typically that's due to a problem with color spaces. If that doesn't make a difference for you then I'm not sure.

**Comment by ForrestAlfred** [comment]
![screen shot 2015-10-18 at 6 15 30 pm](https://cloud.githubusercontent.com/assets/8122371/10563664/52cd7f62-75c4-11e5-922d-cfa4e2bcdaa3.png)

**Comment by TheBB** [comment]
Yeah, now it looks better. See the difference between the modeline in your last screenshot and the earlier one.

**Comment by ForrestAlfred** [comment]
Thanks, it helps indeed,  looking better indeed !
![screen shot 2015-10-18 at 6 18 42 pm](https://cloud.githubusercontent.com/assets/8122371/10563674/db3958d0-75c4-11e5-95cd-7f169329b590.png)

**Comment by ForrestAlfred** [comment]
You helped me master the avy-goto-char, avy-goto-line and the color of modeline.

**Comment by ForrestAlfred** [comment]
:-)

**Comment by TheBB** [comment]
You're welcome. :+1:
