### ISSUE TITLE
Option to disable C-h new behavior in helm mode, or other solution

### ISSUE THREAD

**Issue by xoich** [syl20bnr/spacemacs#3448]
I use C-h to backspace, which is a standard in vim and terminals with:

```
  (define-key key-translation-map (kbd "C-h") (kbd "<DEL>"))
```

I was accustomed to the previous behavior that backspace and so C-h goes up one level in helm mode. But now C-h does actually delete previous character for me.
I would prefer the previous behavior.

**Comment by syl20bnr** [comment]
Actually you can remove your line now because `C-h` effectively goes up one directory since 0.104.

**Comment by mistnim** [comment]
@syl20bnr I didn't redefine `C-h` to go up a directory in Helm, I redefined it to use it as backspace in insert mode or anywhere else, as is default in vim.
Now I have no way to go up a directory in Helm.

**Comment by TheBB** [comment]
You can define another key to go up a directory in Helm, then. Just map it in `helm-find-files-map`.

**Comment by StreakyCobra** [comment]
@mistnim The behaviour you want seems to be a personal preference, and will probably not be a spacemacs default. Do you need some help to rebind this "go up one directory" in helm, or is this issue solved :relaxed:?

**Comment by mistnim** [comment]
Yes, you can close this. But maybe as a different issue, it could be argued that spacemacs should support `C-h` for backspacing as default? Being the keybinding a standard used on vim, terminals and the like, and being of much more use than the help function.

**Comment by StreakyCobra** [comment]
There is an ongoing more general discussion about this in #3472, i.e. how to deal with keybindings that are sending the same keycode in terminal. I reported this one there, so if it is fine for you I let you close this one :-)

**Comment by StreakyCobra** [comment]
I misunderstood what you was asking, my bad. I reopen this issue as it's not really a similar problem as #3472. What you want is a spacemacs option that allows to use `C-h` as backspace, everywhere (terminal, GUI), right?

**Comment by mistnim** [comment]
I would like to use `C-h` as backspace in general. But especially when editing text, be in insert mode or command mode.

**Comment by hosh** [comment]
So I'm a newbie when it comes to customizing emacs. How would someone go about defining a keybinding for `helm-find-files-map` so it goes up a level?

**Comment by StreakyCobra** [comment]
@hosh Something like this in `user-config`:

```elisp
  (with-eval-after-load 'helm
    (dolist (keymap (list helm-find-files-map helm-read-file-map))
      (define-key keymap (kbd "<DEL>") 'helm-find-files-up-one-level)))
```

**Comment by kvelicka** [comment]
Is there any updates or a solution to this? I'd also like `C-h` to act as backspace in insert mode.

**Comment by braham-snyder** [comment]
This seems to work after a restart:

```
  ;; translate C-h to backspace, and M-h to C-h
  (keyboard-translate ?\C-h ?\C-?)
  (define-key key-translation-map (kbd "M-h") (kbd "C-h"))
```

**Comment by YuMS** [comment]
(global-set-key (kbd "C-h") 'delete-backward-char)

**Comment by invsblduck** [comment]
FWIW, a few years later... 

I achieve this with:
```elisp
  (evil-define-key nil helm-find-files-map (kbd "C-h") 'delete-backward-char)
```

I've always used `(global-set-key (kbd "C-h") 'delete-backward-char)` with Spacemacs, but it never affected Helm minibuffer behavior; the line above is also needed to achieve what OP and I want.

I am able to delete individual path words in Helm by default using `M-DEL` (for which I actually use `M-backspace` on my system and Emacs translates it to `M-DEL`, but that is possibly a whole 'nother historical Unix/Emacs topic ;)).

**Comment by lebensterben** [comment]
The design choice is, in minibuffer

- C-h will be bound to delete the last word or go up one level in a file path
- C-l will he bound to enter the current selection into minibuffer or go down one level in a file path

It's not quite universal for all completion frameworks now (at least not for compleseus), but it's a design choice.

I'm locking this issue. Please see above comments for workaround. Or one could open a new discussion instead of an issue.
