### ISSUE TITLE
Can't scroll more than two pages up, in scroll micro-state, when in Visual line Mode

### ISSUE THREAD

**Issue by mistnim** [syl20bnr/spacemacs#3450]
How to reproduce:
Enter visual line mode: `Shift-V`
scroll up two times `SPC n , ,`

**Comment by synic** [comment]
It just plain doesn't work for me at all in visual mode.  `SPC n .` shows the microstate menu, but pressing , acts as major mode leader, and . repeats the last action.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by mistnim** [comment]
Still have the issue in v0.201.
