### ISSUE TITLE
Holy-Mode <ESC> 

### ISSUE THREAD

**Issue by grubernaut** [syl20bnr/spacemacs#3453]
While in holy-mode, pressing `ESC` has some weird behavior on OSX.
This works fine in Linux, acting as a secondary Meta key as usual, but on OSX spacemacs exits holy mode while still leaving holy-mode still enabled. This prevents any `C-` navigation that normally exists in holy-mode.

The only two ways I've found to get back into holy-mode after pressing `ESC`, are to
* Disable holy-mode then re-enable it again. `M-m f E e` + `M-m f E e`.
* Press `i` to enter insert state of the hybrid-mode, then press `C-g` to return to the normal holy-mode state.

This behavior doesn't seem to happen in a client mode launched from the terminal. 

Holy-Mode:
<img width="672" alt="screen shot 2015-10-18 at 2 11 12 pm" src="https://github-cloud.s3.amazonaws.com/assets/3082319/10565609/a57b4c7a-75a2-11e5-8d20-51aeb06f7542.png">

After Pressing `ESC`:
<img width="672" alt="screen shot 2015-10-18 at 2 11 18 pm" src="https://github-cloud.s3.amazonaws.com/assets/3082319/10565611/b4be98e0-75a2-11e5-9228-7529f8823131.png">

Notice that `holy-mode` is still enabled in the status-bar, yet spacemacs is in the Normal mode of Vim, based on the orange color of the status-bar.

**Comment by TheBB** [comment]
This is a feature, that escape should work in Emacs state as if it were an insert state.

See https://github.com/syl20bnr/spacemacs/issues/1244#issuecomment-126182504

**Comment by justbur** [comment]
> Notice that holy-mode is still enabled in the status-bar, 

Holy mode being enabled does not prevent Emacs from getting into the evil normal state. I don't know if that's part of the confusion here.

**Comment by grubernaut** [comment]
Using Emacs without Evil mode, ESC acts as a second Meta key.

In Spacemacs, ESC does _not_ act as a secondary Meta key.

**Comment by justbur** [comment]
```elisp
(define-key evil-emacs-state-map [escape] nil)
```

I'm curious. What's the advantage of having a second meta key?

**Comment by grubernaut** [comment]
It's easier for me to hit `ESC` on my keyboard than it is to hit `Alt` :)

**Comment by grubernaut** [comment]
@justbur Awesome, that works perfectly. Thanks.

**Comment by justbur** [comment]
Ah, ok. Actually, this might work better in `dotspacemacs/user-init` to disable the behavior
```elisp
(add-hook 'holy-mode-hook (lambda () (define-key evil-emacs-state-map [escape] nil)))
```

**Comment by grubernaut** [comment]
Ah yeah, that would leave Evil mode still functioning for any pairing sessions.
Basically, my hands are too big to effectively use the `Alt` keys for any effective purpose. :(

**Comment by justbur** [comment]
That's actually the default behavior in evil's emacs state (escape is not intercepted). I don't know why it's changed in holy-mode
