### ISSUE TITLE
The borders of the modeline are gone

### ISSUE THREAD

**Issue by ernestas** [syl20bnr/spacemacs#3456]
The borders are gone in the develop branch. If this is a feature, please close this issue.

![spacemacs-no-borders](https://github-cloud.s3.amazonaws.com/assets/315700/10566418/a5670c92-75de-11e5-86d8-d6ae87aec329.jpg)

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. bd6716b)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git github restclient org markdown
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (clojure :variables clojure-enable-fancify-symbols t)
                 javascript)
```

**Comment by TheBB** [comment]
We moved away from using our solarized fork and went with the solarized that's on MELPA. What you're probably seeing is the lack of those local modifications we had made. You can modify the modeline faces yourself, of course:

* `mode-line`
* `mode-line-inactive`
* `powerline-active1` and `2`
* `powerline-inactive1` and `2`

**Comment by ernestas** [comment]
I have added this:

```emacs-lisp
  (set-face-attribute 'mode-line nil :box '(:color "#839496" :line-width 1))
  (set-face-attribute 'mode-line-inactive nil :box '(:color "#586e75" :line-width 1))
  (set-face-attribute 'powerline-active1 nil :box '(:color "#839496" :line-width 1))
  (set-face-attribute 'powerline-inactive1 nil :box '(:color "#586e75" :line-width 1))
  (set-face-attribute 'powerline-active2 nil :box '(:color "#839496" :line-width 1))
  (set-face-attribute 'powerline-inactive2 nil :box '(:color "#586e75" :line-width 1))
```

but still not getting the full borders

![spacemacs-no-borders-2](https://cloud.githubusercontent.com/assets/315700/10621440/c93b82d8-7778-11e5-87b1-6b6d7e3e6d6f.jpg)

Will it be possible to pass in the `:line-width` value with the new theming layer #3486 ?

**Comment by TheBB** [comment]
That's strange. I don't know why that's not working for you. As for your question, `:line-width` works fine for me with #3486 and the Monokai theme.

**Comment by TheBB** [comment]
For the record, that layer is implemented using `custom-set-faces` and not `set-face-attribute`. I don't know if it matters. The docstring of the latter seems to imply it's primarily for internal use so I didn't want to touch it.

**Comment by TheBB** [comment]
I just tried with solarized light and I can reproduce your issue. Must be something weird about that theme. I get the same with solarized dark.

**Comment by razum2um** [comment]
same with solarized (both themes)
it's definitely something wrong with them as `sanityinc-solarized-dark` works (both)

![emacs macpro local 2015-10-22 06-58-58](https://cloud.githubusercontent.com/assets/122018/10654297/0ceea640-7882-11e5-96b3-29cb776a36ad.png)

**Comment by ernestas** [comment]
bbatsov/solarized-emacs#174 looks related.

**Comment by robbyoconnor** [comment]
I have since moved away from solarized -- I didn't like how it handled magit...so I now use [monokai](https://github.com/oneKelvinSmith/monokai-emacs)...It's not my favorite but it doesn't make my eyes bleed either...

**Comment by TheBB** [comment]
I think this can be closed now.
