### ISSUE TITLE
Spacemacs overwrites clipboard on startup with its version

### ISSUE THREAD

**Issue by vashirov** [syl20bnr/spacemacs#3457]
To reproduce:
1. copy some text to clipboard
2. start spacemacs
3. switch to scratch buffer and paste from the clipboard, it will be something like 

                                                                 (0.104.2)
instead of the original clipboard content.

**Comment by boj** [comment]
I believe there is something lower down in the Haskell layer still causing this problem.  While editing in haskell-mode `master` gives me the above reported error when trying to yank and paste text, but `develop` tells me that the kill ring is empty.  Other major modes I use seem to work fine on either branch.

**Comment by TheBB** [comment]
@boj The `dd` problem is likely #3527. Haskell mode has been updated and we haven't caught up yet.
