### ISSUE TITLE
literate haskell keybindings

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#3458]
Steps to reproduce using Windows 8.1 and (spacemacs-0.104.2):

1. Create literate haskell file or [download one](http://www.seas.upenn.edu/~cis194/spring13/lectures/01-intro.lhs)
2.  `SPC m` and get `SPC m is undefined`

However things work with `M-x haskell-process-load-or-reload`, which is interesting since earlier I had an issue using interactive Haskell at all in #3443.

**Comment by codygman** [comment]
Made a patch and will PR soon if git would work on windows :S

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
