### ISSUE TITLE
auto-complete doesn't work on OS X 10.11

### ISSUE THREAD

**Issue by maplewizard** [syl20bnr/spacemacs#3469]
I installed as the document said. Then, I added auto-completion to dotspacemacs-configuration-layers, but when I edit python file, no completion appear. It said:

    Completion need an inferior python processing running

I want to know is there any wrong?

**Comment by synic** [comment]
Is there anything else in your *Messages* ?  I am using El Capitan and python auto-completion is working well.

**Comment by d12frosted** [comment]
You did enabled [python layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/python), didn't you? Just a guess. :smile:

**Comment by maplewizard** [comment]
I added python layer into  dotspacemacs-configuration-layers, and It solved all my question.
