### ISSUE TITLE
Question .. or request.  Loading layers from github.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3471]
Is there a way to load layers straight from github?  Something like:

``` #!elisp

dotspacemacs-configuration-layers '(
  "synic/somelayer"
  auto-complete
  python)
```

If not, is there a way to make that happen?  It seems like a good idea for specific-use layers that don't necessarily need to be in spacemacs proper.

**Comment by TheBB** [comment]
No, but you can clone them to your private directory and load them normally.

**Comment by syl20bnr** [comment]
This is a feature we can add, a `:location` keyword would be consistent with the package one. Ideally we should support a similar DSL than MELPA recipes. This is the "easy" part.

The less easy part is the management of those layers (update etc...).

**Comment by PhilipDaniels** [comment]
I would like to write in support of this feature. In my case, I am developing a layer which I think might be useful for others (Windows style keybinding conventions) but it is rather immature and certainly not ready to be a pull request against the main code base.

However, I would like to be able to allow people to test it and review it easily, and I think saying "Just fetch it from Github like this...." would help a lot.

**Comment by bernsie** [comment]
this is something I could get behind. as far as implementation goes, I would like to know peoples thoughts regarding a separate function for remote layer repositories vs having all layers in the same function so

```elsip
dotspacemacs-configuration-layers '(
  "synic/somelayer"
  auto-complete
  python)
```

vs

```elisp
dotspacemacs-configuration-layers '(
  auto-complete
  python
)

dotspacemacs-configuration-remote-layers `(
  "synic/somelayer"
)
;; or something...
```
