### ISSUE TITLE
Use <tab> keycode rather than TAB

### ISSUE THREAD

**Issue by elemakil** [syl20bnr/spacemacs#3472]
For historic reasons emacs treats the `TAB` and `C-i` keycodes as the same thing. Specifically, those historic reasons are that a terminal does not distinguish between the physical <kbd>Ctrl</kbd> + <kbd>i</kbd> and <kbd>tab</kbd> keys: They send the same code. As a workaround there's the function key code `<tab>` which is **not** mapped to `TAB` if it has a binding of its own; note: this only works in terminals with extended capability or non-terminal versions of emacs.

If the following scheme is used separate bindings for <kbd>tab</kbd> and <kbd>Ctrl</kbd> + <kbd>i</kbd> (the physical keys) can be used when emacs runs in a window system.
- <kbd>tab</kbd> maps to `<tab>`  
- <kbd>Ctrl</kbd> + <kbd>i</kbd> maps to `TAB` or `C-i`

There are a few places in the `spacemacs` source, where the `TAB` keycode is used instead of the `<tab>` version event though they are intended to be bound to the physical <kbd>tab</kbd> key.

Fixing those (and ensuring that this becomes part of the contribution guidelines) will allow users to have separate binding for <kbd>Ctrl</kbd> + <kbd>i</kbd> and <kbd>tab</kbd>. Take Issue #3165 as an example of the resulting problem.

This is of special importance for an `evil` based configuration because traditionally <kbd>Ctrl</kbd> + <kbd>i</kbd> is used to step through the jump list.

I suggest two things:
1. Fix the existing mentions of `TAB` to use `<tab>` instead whenever emacs is launched in non-terminal mode.
2. Add an entry to the [contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/master/CONTRIBUTING.md) / [convention guidelines](https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.org)

**Comment by sooheon** [comment]
I wholeheartedly agree with this, I've personally encountered this issue in the help buffers and in org-mode

**Comment by StreakyCobra** [comment]
Same problem append with `S-BACKSPACE` and `C-H` #1443

**Comment by StreakyCobra** [comment]
This problem have also been reported in #2105, with an additional keybinding: `RET` vs `<enter>`.

**Comment by StreakyCobra** [comment]
Same problem with `TAB` in help buffers on #3165. Workaround proposed and working for this special case in the issue.

**Comment by StreakyCobra** [comment]
#3448 is another variant of this problem. It's asking if Spacemacs can support `C-h` to act as `Backspace` in terminals, or at least to have an option for this.

**Comment by mistnim** [comment]
I want it to act as `C-h` everywhere.

**Comment by StreakyCobra** [comment]
Oh, sorry for the misunderstanding.
