### ISSUE TITLE
SPC mga not working for opening header files for corresponding cxx files

### ISSUE THREAD

**Issue by dmsurti** [syl20bnr/spacemacs#3480]
I cannot open a header file for a '.cxx' file. I am working on VTK project which uses CMake. `https://gitlab.kitware.com/vtk/vtk`.

For example, opening: `Rendering/Core/OpenGL2/vtkPolyDataMapper.cxx`, then `vtkPolyDataMapper.h` is not opened with `SPC mga`. 

To make this work, I had to update my `dotspacemacs/config` as such:

```
  (add-to-list 'projectile-other-file-alist '("cxx" . ("h" "hxx" "ixx")))
  (add-to-list 'projectile-other-file-alist '("h" . ("c" "cpp" "cxx" "ipp" "hpp" "m" "mm")))

```

I referred to this for updating the alist: https://github.com/bbatsov/projectile/blob/master/projectile.el#L1198

**Comment by StreakyCobra** [comment]
This should probably be added to the `c-c++` layer, or at least documented.

**Comment by StreakyCobra** [comment]
Hum, looking at it more carefully, I think it should be reported upstream first.

**Comment by StreakyCobra** [comment]
I reported it upstream: https://github.com/bbatsov/projectile/issues/918

**Comment by StreakyCobra** [comment]
PR'ed upstream: https://github.com/bbatsov/projectile/pull/934
