### ISSUE TITLE
Updated magit-gh-pulls breaks keybindings for gh-pulls and gitflow

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#3481]
`magit-gh-pulls` has taken over the binding `#` to show magit like popup which shadows spacemacs' gitflow and magit-gh-pulls keybindings which were bound to `#f` and `#gg`. 

Since the upstream change is nice, I was thinking of remapping the default spacemacs keybindings elsewhere for these features if that's what all want. If so, any suggestions?

**Comment by syl20bnr** [comment]
I just moved them to `#g` and `#f` so they are consistent with the defaults.

**Comment by nixmaniack** [comment]
`#f` is bound to `magit-gitflow-popup` so the current rebinding doesn't seem to have any effect. I don't even see the `#g` binding with the latest pull of develop. That's the reason I had suggested moving `gitflow` and `magit-gh-pulls` on different bindings in `magit-mode`. 

I'm currently using following config to get both working on `#` and mostly consistent with current defaults, the only caveat is once you start `magit-gh-pulls` you won't be able to access `gitflow`(as it takes over `#` in `magit-mode-map`). To access `gitflow` you'll have to re-open `magit-status`.

```elisp
(defun spacemacs/load-gh-pulls-mode ()
  "Start `magit-gh-pulls-mode' only after a manual request."
  (interactive)
  (magit-gh-pulls-mode)
  (magit-gh-pulls-popup))
(define-key magit-mode-map "#g" 'spacemacs/load-gh-pulls-mode))
```

Reason for not using gh-pulls hook in magit mode is that for repos with large PRs it becomes slow when I essentially need magit-status only and not other minor modes.
