### ISSUE TITLE
void-function ad-Advice-evil-insert-state

### ISSUE THREAD

**Issue by avdv** [syl20bnr/spacemacs#3495]
I'm using the Emacs editing style. But I'm used to use `Esc-w` to run `kill-ring-save`.

Alas, when hitting Esc, spacemacs (evil) enters the "orange" state (and I cannot get back to the Emacs style. How do I do that?).

When trying to use the Vim bindings instead, when hitting `a` the following error is shown:

```
Debugger entered--Lisp error: (void-function ad-Advice-evil-insert-state)
  ad-Advice-evil-insert-state(#[(&optional arg) "^H\247\203b
  apply(ad-Advice-evil-insert-state #[(&optional arg) \247\203b
  evil-insert-state(1)
  evil-insert(1 nil nil)
  evil-append(1 nil)
  call-interactively(evil-append nil nil)
  command-execute(evil-append)
```

---

```
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.2
- Spacemacs branch: master (rev. 074f425)
- Distribution: spacemacs
- Layers:
```elisp
(asciidoc emacs-lisp git html javascript markdown scala spell-checking version-control yaml)
```

**Comment by justbur** [comment]
You probably need to disable holy-mode with `M-x holy-mode`

**Comment by justbur** [comment]
This is the third issue I've seen like this. @syl20bnr @TheBB maybe we should not be binding escape in holy mode.

https://github.com/syl20bnr/spacemacs/issues/3473
https://github.com/syl20bnr/spacemacs/issues/3453

**Comment by avdv** [comment]
> You probably need to disable holy-mode with M-x holy-mode

When I did that, it said `Holy mode enabled` in the message line. So, it already was disabled?

Additionally, I already tried to use `M-m t E e` where it said `holy-mode disabled`, but the state color remained the same. Doing it again, resulted in `holy-mode enabled.` and the color turned to blue.

Thanks!

**Comment by justbur** [comment]
The first issue is because ESC puts you in evil normal state even in holy mode. You can see one of the referenced issues for how to disable that. 

For the second you're saying that if you change editing style to vim and restart emacs you get that error?

**Comment by justbur** [comment]
Fixed in develop
