### ISSUE TITLE
What are the requirements of the Ruby contrib layer?

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#350]
When I open a ruby-file, the line below the modeline tells me 
`[rbenv] could not locate .ruby-version or rbenv-version`

When I press `, i` and answer yes to open a REPL, I get `No matching directory found`.

When I press `, t b` to run tests (with a test buffer open) I get a message `No test among visible buffers or run earlier`.

I have run `gem install pry --verbose`.

I have also started installing rbenv (will see if I am able to get it to work in the end).

Is there anything obvious I am missing since nothing in this layer seems to work for me? If so please tell me, and I'll add it to the README.md.

**Comment by syl20bnr** [comment]
Since rvm and rbenv are mutually exclusive in the layer I close this. Feel free to reopen if needed.
