### ISSUE TITLE
Search is broken in evilified magit-status buffer

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#3501]
Reproduce:

1. Find a file in a git repository
2. Do `SPC g s` to open the magit-status buffer
3. Type `/` to begin evil incremental search
4. Type `k`

Expected behavior: the letter "k" should be added to the search term

Actual behavior: point moves up one line

**Comment by xged** [comment]
I can confirm that (*Develop* branch).

**Comment by justbur** [comment]
Fixed in #3578
