### ISSUE TITLE
haskell-interactive-switch-back doesn't work

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#3503]
This seems to happen every time I want to switch back to the source file I'm editing from the repl.

Steps to reproduce using master:

1. Open Haskell file
2. `, s b`
3. `, s s`
4. `, s S`

In some previous version I actually got the error `No previous buffer.` quite often, but now it seems to give no errors while staying in the repl.

**Comment by d12frosted** [comment]
It looks like `, s s` is bound to `haskell-interactive-bring`, and this function doesn't work with `, s S` from REPL (`haskell-interactive-switch-back`). Instead of using `, s s`, use `, s S`, this will call `haskell-interactive-switch`. But this is frustrating a little bit.

**Comment by d12frosted** [comment]
Ok, changed it a bit: #3504. What do you think?

**Comment by d12frosted** [comment]
@TheBB could you, please, add `haskell` label here?

@codygman I little update. My previous PR seems to be wrong, so I opened new one: #3533.
