### ISSUE TITLE
Ranger bug

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#3505]
It seems that ranger can't get its windows set up properly all the time. See [this video](https://vid.me/nnMY), where I try to invoke `SPC a r` three times, and it only works as expected the last time. This is quite reproducible for me, on at least two different installations.

CC @ralesi

**Comment by ralesi** [comment]
@TheBB,  will look into it.  Do you have ranger-override-dired set in your config?

**Comment by TheBB** [comment]
Ah, no, I don't, but your comment reminded me I did something else that apparently screwed it up. Is that the recommended way to get deer instead of dired? I had `(add-hook 'dired-mode-hook 'deer)` which was clearly bogus. Anyway, thanks. :-)

**Comment by ralesi** [comment]
Yes, I need to work more on improving the readme. Just set that in your layer declaration until I update the help.
