### ISSUE TITLE
Please add a useful function for East Asian people

### ISSUE THREAD

**Issue by erstern** [syl20bnr/spacemacs#3506]
We Chinese, Japanese and Koreans use a software called input method to typing in Chinese Characters. The input method software can translate alphabet letters to Chinese like 「一二三」. 
The most popular input method engine may be fcitx (or iBus).
I know a very useful script named "fcitx.vim" for vim, but spacemacs had not have the function.
When I use fcitx.vim, it can detect the mode I am using. For instance, I typed Chinese characters in insert mode, then type Esc to normal mode, the fcitx.vim will shift fcitx to English so that I can use vim key-bingdings.
The creator lilydjwg descript the script: Keep and restore fcitx state for each buffer separately when leaving/re-entering insert mode. Like always typing English in normal mode, but Chinese in insert mode.
Here: http://www.vim.org/scripts/script.php?script_id=3764

**Comment by robbyoconnor** [comment]
Welcome! Why not do it ;) We are community-driven after all.

**Comment by robbyoconnor** [comment]
Welcome! Why not do it :stuck_out_tongue_winking_eye:  We are community-driven after all. :heart:

**Comment by erstern** [comment]
In a word, this script(fcitx.vim) will let any fcitx (or iBus ,etc) state before to English, when we typed Esc.

**Comment by linktohack** [comment]
I have something like this in `init.el`

```emacs-lisp
(when (provide 'link/switch-input)
  (defvar link/switch-input-binary "/Users/link/Downloads/input-source-switcher/build/issw"
    "Switch input binary.")
  (defvar link/switch-input-us-method "com.apple.keylayout.US"
    "US input method.")
  (defvar link/switch-input-last-method nil
    "Last input method.")
  (defun link/switch-input-to-us ()
    "Switch input method to US.
Save last method into `link/switch-input-last-method'."
    (interactive)
    (setq link/switch-input-last-method
          (shell-command-to-string
           (format "%s" link/switch-input-binary)))
    (shell-command (format "%s %s"
                           link/switch-input-binary
                           link/switch-input-us-method)))
  (defun link/switch-input-to-alternate ()
    "Restore last input method."
    (interactive)
    (when link/switch-input-last-method
      (shell-command
       (format "%s %s"
               link/switch-input-binary
               link/switch-input-last-method))))
  (define-minor-mode link/switch-input-mode
    "Switch input."
    :global t
    :lighter " xkb"
    (if link/switch-input-mode
        (progn
          (add-hook 'evil-insert-state-entry-hook #'link/switch-input-to-alternate)
          (add-hook 'evil-insert-state-exit-hook #'link/switch-input-to-us))
      (remove-hook 'evil-insert-state-entry-hook #'link/switch-input-to-alternate)
      (remove-hook 'evil-insert-state-exit-hook #'link/switch-input-to-us))))

(use-package link/switch-input
  :if (featurep 'ns)
  :diminish link/switch-input-mode
  :demand
  :config (link/switch-input-mode 1))
```

Have no time to extract that part into a dedicated package but it should work, even under Linux with little to no modification. For the Linux binary you can find it here: https://github.com/ierton/xkb-switch

**Comment by syl20bnr** [comment]
cc @zilongshanren @louy2

**Comment by bmag** [comment]
Emacs has its own feature called that is also called "input methods", see http://www.gnu.org/software/emacs/manual/html_node/emacs/Input-Methods.html (entry in Emacs manual) and http://www.gnu.org/software/emacs/manual/html_node/elisp/Input-Methods.html (entry in Emacs-Lisp manual).
I don't know how it relates to your software, but maybe it's worth a try.

**Comment by kuangdash** [comment]
Here is chinese layer, but I think that https:github.com/tumashu/chinese-fonts-setup should be included in order to align org-mode table with chinese characters.

But in order to intergrate chinese-fonts-setup into spacemacs, there are some codes needed to be hacked. (It refers to "set-fontset-font")

**Comment by louy2** [comment]
For those interested in using and improving the Chinese layer in Spacemacs please read files in `/layers/chinese` (especially `README.md`) and create pull request against it. The layer now comes with a elisp pinyin IME which is aware of the Evil states. To use the layer just add it to your `dotspacemacs-configuration-layers`. 

@kuangdash Chinese layer currently doesn't set the font by default. Improve it as you wish.

**Comment by xuchunyang** [comment]
> In a word, this script(fcitx.vim) will let any fcitx (or iBus ,etc) state before to English, when we typed Esc.

You might want to give @cute-jumper's [fcitx.el](https://github.com/cute-jumper/fcitx.el) a try.

**Comment by erstern** [comment]
Thanks to @xuchunyang , I have tried to add "fcitx" in the funcion in .spacemacs like this:
```
(defun dotspacemacs/layers ()
   dotspacemacs-additional-packages '(fcitx)
)
```
and set the "fcitx-evil-turn-on".

Then the problem is resolved.

**Comment by StreakyCobra** [comment]
@zilongshanren @louy2 Would it be useful to add this `fcitx` package and turn it on in the chinese layer? If yes, can someone PR it, it seems to be a trivial change⁽¹⁾. If not, I'll close the issue.

⁽¹⁾ I can't really to do it myself as I can't test it :-/

**Comment by zilongshanren** [comment]
@StreakyCobra 
Sure, I will send a PR today.

**Comment by zilongshanren** [comment]
@erstern  @StreakyCobra 

Here is the PR: https://github.com/syl20bnr/spacemacs/pull/3847

**Comment by StreakyCobra** [comment]
:+1: Nice, thank you :-)

**Comment by lazywei** [comment]
@linktohack I'm wondering where I can get the binary `/Users/link/Downloads/input-source-switcher/build/issw`? I am on Mac OS X, and thus fcitx will not work for me. And hence I prefer your appraoch. But I just can't find that binary.
Thanks.

**Comment by linktohack** [comment]
I extracted the code to its own repo, you can find it here: https://github.com/linktohack/evil-xkbswitch, the `issw` you can get from here https://github.com/vovkasm/input-source-switcher
