### ISSUE TITLE
Key binding for list-processes?

### ISSUE THREAD

**Issue by usharf** [syl20bnr/spacemacs#3507]
Finding `list-processes` (list Emacs' sub-process) useful when running into problems with REPLs , if I need to find exact command line invocation when it was setup automatically, i.e. inferior haskell process in this example, which shows me that the option I've setup to prefer `ghci-ng` over stock `ghc` was not picked up (needs `stack exec ghci-ng`).

Right now we have `ap` for `proced` and `aP` for `paradox-list-packages`. 

Thought we might want to have:

`ap` `list-processes

`aP` `proced

`a\` 'pardox-list-packages   --- '\' or something else

```sh
ispell          run     --              --           aspell -a -m -B --encoding=utf-8
server        listen  --              --           (network server on /var/folders/c0/4fzwf9wx4qvdj10z6c52_s_m0000gn/T/emacs501/server)
demo         run     --              /dev/ttys001 stack ghci --ghc-options=-ferror-spans

```

**Comment by StreakyCobra** [comment]
PR: #3896
