### ISSUE TITLE
disable automatic update check

### ISSUE THREAD

**Issue by shelper** [syl20bnr/spacemacs#3526]
sometimes users may use this package behind corporation firewall, which does not allow internet connection from emacs. 
would it be nice if there is an option to disable the automatic update check?

**Comment by usharf** [comment]
:+1:

**Comment by EmuxEvans** [comment]
:+1:

**Comment by signalpillar** [comment]
(y)

**Comment by tenthousandfailures** [comment]
:+1:

**Comment by StreakyCobra** [comment]
FTR: PR pending #3908

**Comment by StreakyCobra** [comment]
FIxed in develop by #3913
