### ISSUE TITLE
symbol-highlight not working on words terminating with an apostrophe

### ISSUE THREAD

**Issue by PierreR** [syl20bnr/spacemacs#3528]
`symbol-highlight` does not seem to work on words terminating with a `'` (like foo').
##### How to reproduce it:

On a scratch buffer (or anywhere else):
- enable `automatic-symbol-highlight` (`SPC tha`)
- copy twice the word `foo'`,
- press `*` on one of them => `symbol-highlight` has zero match.
##### System Info

``````
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: haskell-indentation (rev. 94af1e2)
- Distribution: spacemacs
- Layers:
```elisp
(asciidoc auto-completion emacs-lisp erc dash dockerfile emacs-lisp extra-langs git markdown
          (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-ghc-mod-support t)
          org
          (shell :variables shell-default-term-shell "/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
          salt syntax-checking spell-checking puppet python version-control yaml)
``````

Could be related with #2706

**Comment by StreakyCobra** [comment]
Reproduced here. It's a bug because either:
- Symbols don't contain `'` and then the symbol is `foo` and it should recognize the other `foo`
- Symbols contain `'` and then the symbol is `foo'` and it should recognize the other `foo'`

**Comment by jb55** [comment]
:wave: [codetriage](http://codetriage.com/syl20bnr/spacemacs) time

Is this still an issue? If so how should we proceed?

**Comment by syl20bnr** [comment]
Well I suppose that's a bug to fix in the ahs package which is quite an old package, not sure there is a maintainer for it.
Or maybe that's not a bug in ahs and this is the major mode which does not define symbols correctly ?

**Comment by syl20bnr** [comment]
I suppose we are talking about Haskell here ?

**Comment by PierreR** [comment]
The original bug is not `Haskell` related. As I mentioned it even happens in a scratch buffer.

I could try again and see if it is still an issue with the latest version though.

**Comment by gracjan** [comment]
Note that in haskell-mode we try really hard to put symbol constituent property on apostrophes that are symbol constituent, so inside or at the end of an identifier. What regexp does ahs use to find symbols?

**Comment by TheBB** [comment]
(defconst ahs-default-symbol-regexp "^[0-9A-Za-z/_.,:;*+=&%|$#@!^?-]+$"
      "Default symbol regular expression.")

I'm not sure why this doesn't use `\_<` and `\_>`

**Comment by gracjan** [comment]
So if there is somebody willing to customize ahs for Haskell all the info needed is in [`haskell-lexeme.el`](https://github.com/haskell/haskell-mode/blob/master/haskell-lexeme.el).
