### ISSUE TITLE
quotation marks in html strings messes up "select inside quotes" in tags

### ISSUE THREAD

**Issue by ipsod** [syl20bnr/spacemacs#3531]
`That's it.
<div class='ham'>`

Type this into an html file, put the cursor on `ham` and hit `vi'`, and `ham` will not be selected.  Do the same in Vim, and `ham` will be selected.

**Comment by robbyoconnor** [comment]
Can you give `SPC hds` -- In the future please, read the [contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.md) when reporting issues from now on :stuck_out_tongue:

**Comment by robbyoconnor** [comment]
I just tested on develop and it works fine for me. 

#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. bf4cb35)
- Distribution: spacemacs
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-show-snippets-in-popup t)
 better-defaults emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 github gnus version-control markdown syntax-checking
 (latex :variables latex-enable-auto-fill t)
 (colors :variables colors-enable-rainbow-identifiers t colors-enable-nyan-cat-progress-bar t)
 dockerfile ansible puppet evil-commentary
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 fasd finance floobits xkcd autohotkey
 (c-c++ :variables c-c++-enable-clang-support t)
 (clojure :variables clojure-enable-fancify-symbols t)
 extra-langs go
 (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "andrew-gibiansky")
 html java javascript
 (python :variables python-enable-yapf-format-on-save t)
 racket
 (ruby :variables ruby-version-manager `rvm)
 ruby-on-rails rust scala shell-scripts restclient themes-megapack tmux vim-empty-lines spotify pandoc vagrant
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 semantic deft
 (shell :variables shell-default-shell 'eshell shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh")
 typescript
 (eyebrowse :variables eyebrowse-display-help t)
 (perspectives :variables perspective-display-help t)
 erc chrome d extra-langs smex emoji gtags prodigy evernote
 (org :variables org-enable-github-support t)
 search-engine evil-little-word yaml sql nim ipython-notebook lua scheme purescript sml common-lisp ranger wakatime dash spell-checking jabber deft cscope vinegar unimpaired rcirc games react geolocation idris sml
 (elm :variables elm-reactor-port "3000" elm-reactor-address "0.0.0.0")
 elixir)
```

**Comment by ipsod** [comment]
Oops, sorry!  Here you go:

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. f9f12c2)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp git markdown org spell-checking unimpaired python html php django version-control auto-completion syntax-checking evil-snipe search-engine)
```

**Comment by TheBB** [comment]
@robbyoconnor I can reproduce. Maybe you forgot the `That's it` before the tag?

**Comment by TheBB** [comment]
Evil provides this text object. You should report to them.

https://bitbucket.org/lyro/evil/wiki/Home

**Comment by d12frosted** [comment]
Any update on this one, @ipsod ?

**Comment by TheBB** [comment]
This was still valid last I checked. Doubt it's been fixed.

**Comment by ipsod** [comment]
I've opened this issue: https://bitbucket.org/lyro/evil/issues/593/quotation-marks-in-html-strings-messes-up

They say it works for them, but it's still broken for me.  I don't know how to provide what they're asking for.

**Comment by d12frosted** [comment]
Yeah it also doesn't work for me :-/ I asked about updates on reporting side. Thanks for sharing link to issue in their issue tracking system.
