### ISSUE TITLE
Type 'F' 'D' quickly will bring emacs into vim `normal-mode`

### ISSUE THREAD

**Issue by qgymib** [syl20bnr/spacemacs#3535]
Hi

I've set editing-style to `emacs`, but when in any buffer and type the key `f` `d` quick enough, spacemacs would went into vim `normal-mode` and do the `search` `delete` action.

It is much more easily to  reproduce if you press `f` without releasing the key and then type `d`.

Any idea about it ?

**Comment by TheBB** [comment]
This is a "feature" but #3497 may fix it. @justbur?

**Comment by justbur** [comment]
Yes, I think the next version of `emacs` editing style will not assume people want easy ways to go into normal mode

**Comment by qgymib** [comment]
Really glad to hear that :-)

'cause for pepole who develop server or driver, `fd`(file descriptor) is really a high frequency word.

**Comment by justbur** [comment]
You can also disable evil-escape now.

**Comment by justbur** [comment]
This should be fixed in develop now

**Comment by junfx** [comment]
This is what i want. How to bring it back for the latest master (0.200.10)?
