### ISSUE TITLE
Helm Swoop shows double line numbers

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#3539]
if line numbers are enabled, helm swoop (SPC s s) shows the numbers again.

[![alt](https://i.imgur.com/2xepT58.png)](https://i.imgur.com/2xepT58.png)

**Comment by TheBB** [comment]
This is my new favourite bug. Let's leave it in.

**Comment by dtreiter** [comment]
I think it's important that the line numbers on the right in the screenshot stay -- they are useful for telling where the candidate came from in the source file at a glance.

The numbers on the left seem less useful. Removing them, though, raises other questions like if the line numbers in other helm windows (ie. helm-M-x) should be removed.

**Comment by CestDiego** [comment]
yes totally! they don't serve any purpose...thing is I can't make them disappear ;_; no matter what I've tried.... The linenumbers from the right are not fron linum mode, they are gathered from buffer info

**Comment by TheBB** [comment]
Should be fixed in develop now. Set `dotspacemacs-global-line-numbers` to `t` to get line numbers the way they should be.

**Comment by CestDiego** [comment]
isn't this a global togle anymore?

**Comment by TheBB** [comment]
No, the toggle is local. There's a dotspacemacs variable for global line numbers.

**Comment by CestDiego** [comment]
Okay this makes more sense now :) thank you :D
