### ISSUE TITLE
How to add a dependency on xmpfilter not available in paradox?

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#354]
I want to add xmpfilter to the ruby layer (see http://devblog.avdi.org/2013/06/24/rubytapas-freebie-xmpfilter/ for an intro to xmpfilter - beware your mind will be blown).

The external dependency is a trivial cross-platform install, namely 
```
gem install rcodetools
```
If you now write 
```
gem env
```
you'll get a list of where your gems are installed. In the `gems/rcodetools` folder there is a `rcodetools.el` file (should be the same as this one: https://github.com/tnoda/rcodetools-x/blob/master/rcodetools.el )

Since this file is not in paradox, it needs to come bundled with spacemacs as a file in the ruby folder. Is this okay? The file is teensy – only 15 kb.

Anyways, after adding the `rcodetools.el` file to `~/.emacs.d/contrib/lang/ruby/`, how do I include the `rcodetools` file? The code below did not work...

```
(add-to-list 'load-path "~/.emacs.d/contrib/lang/ruby/")
(require 'rcodetools)
```
I hope that I have done at least a little bit of what is needed to get xmpfilter working and that it should be trvial to implement for someone who knows elisp... 

Would be nice if this could get a low-priority, but desirable feature-tag.

**Comment by TheBB** [comment]
Closing this as it seems abandoned.
