### ISSUE TITLE
Configure rainbow-delimiters package

### ISSUE THREAD

**Issue by quimrstorres** [syl20bnr/spacemacs#3541]
I am probably missing the documentation, but I wanted to know how can I use the rainbow-delimiters package for Clojure but not for Ruby (for example). I couldn't find the proper way to configure a built-in package. Is it possible to do this?

**Comment by nixmaniack** [comment]
Add this in your `~/.spacemacs` under `user-config` 
`(add-hook 'rainbow-delimiters-mode 'clojure-mode)`

**Comment by TheBB** [comment]
`(add-hook 'clojure-mode-hook 'rainbow-delimiters-mode)` ;-)

**Comment by nixmaniack** [comment]
That's terrybily gone wrong while not in Emacs and suggesting! :stuck_out_tongue_winking_eye:

**Comment by quimrstorres** [comment]
Thanks guys! @TheBB , I tried that, but after I do it, the rainbow delimiters remain active in Ruby. Probably because the default configuration enables it for all kinds of modes?

**Comment by TheBB** [comment]
Okay, then `(add-hook 'ruby-mode-hook (lamba () (rainbow-delimiters-mode -1)) t)`

**Comment by quimrstorres** [comment]
Thanks, that was it. Only a small correction for future reference. It must be `(add-hook 'enh-ruby-mode-hook (lambda () (rainbow-delimiters-mode -1)) t)` because the default mode for ruby files is `enh-ruby-mode` and not `ruby-mode`. Thanks guys

**Comment by nixmaniack** [comment]
It shouldn't be active for all modes unless you specfically turned on with `SPC t C d` which adds the hook to all programming modes.

**Comment by TheBB** [comment]
Okay. In next release that will change... it's a configurable option at the moment. So keep that in mind. :-)

**Comment by nixmaniack** [comment]
@quimrstorres with latest develop spacemacs will be suing `ruby-mode`!

**Comment by quimrstorres** [comment]
@nixmaniack what I meant is that it is active for both Ruby and Clojure major modes by default at least. So adding it the hook for Clojure mode would not remove it from Ruby mode, right?

Thanks for letting me know about the change in ruby mode. That's good news. Thanks for all the help.
