### ISSUE TITLE
How to use MELPA Stable  as default repository

### ISSUE THREAD

**Issue by robsonpeixoto** [syl20bnr/spacemacs#3542]
I'd like to use stable version, but I'd like to use unstable version if the package aren't available on stable.

Is possible to configure MELPA Stable as default repository?

Thanks

**Comment by robsonpeixoto** [comment]
Maybe it can help https://github.com/jwiegley/use-package#for-packageel-users

**Comment by bmag** [comment]
In Emacs 25 you can do so by setting `package-archive-priorities`. Right now Spacemacs doesn't use Melpa Stable, so you will also need to add Melpa Stable to `configuration-layer--elpa-archives`.
