### ISSUE TITLE
spacemacs slow at startup, enforces checking for updates at startup.

### ISSUE THREAD

**Issue by rihenperry** [syl20bnr/spacemacs#3547]
Hi,
I am using spacemacs for 2 weeks so far. I have noticed that spacemacs unnecessarily checks for updates of its packages from its remote sources like marmalade, org.mode, elpa, melpa, etc.I believe that updating spacemacs should be left to user. how do I disable spacemacs from checking its sources at startup ?

**Comment by ljj038** [comment]
I have the same problem. Can we disable it.

**Comment by StreakyCobra** [comment]
Could this be related to #3534 and be resolved now? I mean, if it is always removing and reinstalling `s`, then it will synchronize with repository like `melpa`, etc…  at lunch time. That could explain your bug :smile:
