### ISSUE TITLE
Cannot change font size in .spacemacs

### ISSUE THREAD

**Issue by elvis-sik** [syl20bnr/spacemacs#3550]
Hi. I am under Ubuntu 15.10 and I installed Spacemacs a few days ago. I like huge fonts (maybe I should see my eye doctor?). Trying to achieve that, I have tried both methods discussed in this issue
#231 

I reload the `.spacemacs` file both through `SPC f e R` and restarting emacs. The font size does not change.

With `M-x` I can call `spacemacs/scale-up-font` and it works as a charm.

**Comment by TheBB** [comment]
Does the font name you have specified exist? If it doesn't, none of the other settings are applied.

**Comment by elvis-sik** [comment]
That was the problem. Many thanks.

**Comment by programer5566** [comment]
I have the same problem on ubuntu 15.10

**Comment by d12frosted** [comment]
@programer5566 

> Does the font name you have specified exist? If it doesn't, none of the other settings are applied.

**Comment by programer5566** [comment]
@d12frosted  Thank you so much ! 
I change the font name. It works!
I love you~
