### ISSUE TITLE
Evilify map callback for processed events

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#3555]
This is a feature request for the `spacemacs|evilify-map` macro.

I would like some way to inspect the final list of moved bindings. For example in form of a callback I can define for each binding that is moved, or as a return value or something...

I just wasted a bunch of time trying to work out how this thing works currently. I think I got the gist of it but I wasn't able to change it satisfactorily. For example, `v` and `V` have different bindings in `magit-status-mode-map`, but when invoking `C-v` and `C-S-v` in `magit-status-mode` they execute the same command. I'm not sure if this is a bug or just me not getting it.

The proposed use case is to tweak interactive documentation, particularly in magit as laid out in https://github.com/syl20bnr/spacemacs/issues/2086#issuecomment-151170338.

**Comment by TheBB** [comment]
CC keybinding experts @justbur and of course @syl20bnr.

**Comment by justbur** [comment]
@TheBB I'm sure you know about `help-fns+`? Describe keymap is the best way I've found to inspect these things. I also support the idea of having an easy way to inspect the keybindings moved.

As far as magit is concerned, my opinion now is that magit shouldn't be "evilified". I think the concept of automatic evilification works fine for simple keymaps, but breaks down in magit's case. Ignoring the fact that it is currently broken, having a complex set of keymaps get altered on the fly is more mental effort than just learning a new one for me at least. I gave up on using evilified state for magit a while ago.

I would rather see a conscious effort to design new keymaps for magit in accordance with vim keys and submitting it upstream. If you look through the magit keymaps, there are conventions, with upper and lower case for example, that are just broken by evilification. A designed keymap could follow these conventions and make it easier to remember where things are. There's also the problem which I don't see being solved soon of fixing the magit popups, which don't reflect evilification at all.

**Comment by TheBB** [comment]
I have that package and I use that function a lot.

> There's also the problem which I don't see being solved soon of fixing the magit popups, which don't reflect evilification at all.

...that's what brought this issue up. It's not hard to do so long as I have this data of moved bindings. See the link in the opening comment.

**Comment by justbur** [comment]
@TheBB If you describe what you want exactly, I can take a shot at implementing it. I mostly understand the evilify stuff. Sorry to dump my opinion on your issue.

**Comment by TheBB** [comment]
No worries, I realize evilification is controversial and I'm about to make it more so. :-s

What I wanted was an additional keyword argument to the `spacemacs|evilify-map` macro, called something like `:callback`. The value of this argument is a function that accepts (at least) two arguments: `from` and `to`, each of which are events. This callback is called for each binding in the original map which is moved to a corresponding key in the resulting evilified map.

However I suspect I can get the same information by comparing the generated evilified map and the original one. So maybe I can do this myself.

**Comment by TheBB** [comment]
I guess we don't need this any more.
