### ISSUE TITLE
Consistent expand-region behaviour in Vim-style

### ISSUE THREAD

**Issue by vkz** [syl20bnr/spacemacs#3556]
Source of inconsistency is the same as in #3103 so solution might just be the same.

``` clojure
(println "hello world")
```

with point on last `)` invoking `er/expand-region` will initially select `"hello-world"`. We might want to advise it to start at point rather than before.

**Comment by StreakyCobra** [comment]
Can this be related somehow to #2525? Using `evil-move-beyond-eol` as a workaround maybe :smile:
