### ISSUE TITLE
Add hi2-mode indentation to haskell layer?

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#356]
hi2-mode is a mode I find superior for haskell-indentation, see https://github.com/nilcons/hi2. 

It allows S-TAB to move a line to the left, while with the regular indentation you just have to keep on pressing tab to go full circle to move to the left (it seems to me).

Furthermore, it allows for a teensy sign like tilde to show at all possible indentation positions on the current line. Not necessarily pretty, but useful.

Lastly, it just feels better/more intuitive to me.

To try it just add hi2 in the package list in the haskell file and then start hi2-mode with `SPC : hi2-mode`.

I will not add a pull-request before getting a few yays or nays (this is low-priority stuff, I realize).

**Comment by syl20bnr** [comment]
@bjarkevad @chrisbarrett I saw that `hindent` integration in Emacs is now available on MELPA. Maybe a useful tool to add to the layer.
