### ISSUE TITLE
Helm micro-state does not exit properly with keyboard-quit

### ISSUE THREAD

**Issue by dtreiter** [syl20bnr/spacemacs#3561]
This is a continuation of #1774. It seems the issue was partly fixed -- typing letters works properly but not numbers.

_Note_: I'm unable to reopen the old issue, so I just made a new one.

To reproduce
------------------
- Open helm (ie. helm-M-x)
- Press M-SPC to enter helm-micro-state
- Press C-g to keyboard-quit and exit helm
- Open helm again
- Type a number such as '2'

Expected behavior
-------------------------
Inputs the number you type. (ie. '2')

Actual behavior
---------------------
Tries to execute the helm action corresponding to the number as if you were still in helm-micro-state (ie. the second action).

**Comment by nixmaniack** [comment]
I can confirm this.

**Comment by StreakyCobra** [comment]
Reproduced here using `vim` mode.

Can someone used to emacs reproduce this on a fresh emacs (i.e. not spacemacs) and see if it happens? If yes it's an upstream `helm` bug that should be reported there, if no it means we have an issue :smile:

**Comment by TheBB** [comment]
The micro-state is quite Spacemacs-specific, so this is certainly our bug.

**Comment by icambron** [comment]
I also reported this as #2020
