### ISSUE TITLE
byte-code: Symbol's value as variable is void: org-clock-line-re

### ISSUE THREAD

**Issue by csdrane** [syl20bnr/spacemacs#3562]
I'm fully updated with Spacemacs (0.104.2) + the org layer (8.2.10). Emacs is version 24.5.1. 

I get this error from various unrelated actions, such as trying to export as markdown, and from hitting `M-RET` for `org-meta-return`. A cursory google search shows that this is common error resulting from an installation error.

http://stackoverflow.com/questions/7548813/byte-code-symbols-value-as-variable-is-void-org-babel-tangle-lang-exts
http://stackoverflow.com/questions/16281359/org-mode-broken-dynamic-clock-symbols-function-definition-is-void-org-defvara

Didn't feel comfortable tweaking the layer in my own install for fear of breaking updates, so posting this here.

**Comment by TheBB** [comment]
Maybe you have violated [this](https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-do-some-of-my-org-related-settings-cause-problems)?

**Comment by csdrane** [comment]
My only reference to org in the .spacemacs is adding it to
dotspacemacs/layers, so I don't think so?

**Comment by TheBB** [comment]
You seem to have an older org version that me though, so at least it could be worth updating your packages.

**Comment by syl20bnr** [comment]
@csdrane do you have some news about this issue ?

**Comment by csdrane** [comment]
No updates. `M-RET` still produces the error. `org-export-as-markdown`
produces a different, unrelated error:

```
progn: Wrong number of arguments: #[(templates) "ŠebˆÆ ÇÈÆÉ#…\\Ê Ë !Ì=ƒXÍ
\" ÎÏ \"‰ ÎÐ \"E‰ ƒ<ÑÒÎÓ \"\"ˆ‚W ƒW
B ÎÔ \"bˆÕÆxˆ`|ˆŠ cˆ)+)‚ *‡" [record object templates value begin signature
nil re-search-forward "{{{[-A-Za-z0-9_]" t ...] 6
("/Applications/Emacs.app/Contents/Resources/lisp/org/org-macro.elc" .
3797)], 3

```

**Comment by StreakyCobra** [comment]
@csdrane It would help if you can give more information, such as in the template presented [here](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report).

**Comment by jvillasante** [comment]
Same issue here. Actually my org-mode is unusable and everything was working about 2 weeks ago. Emacs sucks, just look at how many issues spacemacs has.
Best solution is vim/markdown!!

**Comment by StreakyCobra** [comment]
> just look at how many issues spacemacs has

We use Github issues for bug tracking, mailing list and forum, so it's not surprising if there are a lot of issues.

**Comment by nrolland** [comment]
same here, both error `byte-code: Symbol's value as variable is void: org-clock-line-re` and `progn: Wrong number of arguments: #[(templates) "ŠebˆÆ....`

**Comment by StreakyCobra** [comment]
@nrolland If you have some customization for `org` in your `.spacemacs`, be sure to follow [this](https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-do-some-of-my-org-related-settings-cause-problems).

**Comment by nrolland** [comment]
@StreakyCobra merci

**Comment by StreakyCobra** [comment]
de rien :-)

**Comment by pksn** [comment]
Two versions of ORG mode exist, fix is to delete the old version. 
My environment: Msys2; emacs_64
I installed GNU version of ORG (  8.3.4 ) which was installed at  .emacs.d\elpa\org-20160530 
**Fix:** I had to rename/delete **ORG folder** msys64\mingw64\share\emacs\24.5\lisp\org

**Comment by c089** [comment]
For me the problem was an outdated `org` package. Seems I have a builtin org-mode 8.2, but manually installing an up-to-date package and restarting emacs helped.
