### ISSUE TITLE
Mac error -1700 and graphical issues.

### ISSUE THREAD

**Issue by m3nthal** [syl20bnr/spacemacs#3570]
Installed using official instructions: https://github.com/syl20bnr/spacemacs#os-x

I am using iTerm and zsh.

Enabled some layers:
![image](https://cloud.githubusercontent.com/assets/414766/10764449/8dea78e6-7cce-11e5-8ad5-fd621bb488ef.png)

Result:
![image](https://cloud.githubusercontent.com/assets/414766/10764405/46f7aa6c-7cce-11e5-948e-f4f2f880168a.png)

The other issue that the UI looks weird compared to the screenshots in the official repo:
![image](https://cloud.githubusercontent.com/assets/414766/10764497/dd28ca5c-7cce-11e5-805c-80a5ed3dd284.png)
Doesn't look good.

And also whenever I press, for example, ALT+M I get: µ is undefined.

**Comment by TheBB** [comment]
For the first, install trash.

For teh second, I assume you're running in the terminal? You may need a font that supports the appropriate unicode symbols.

**Comment by m3nthal** [comment]
Thank you, TheBB. Installing trash with $ brew install trash solved the first part of the issue.

Yes, I am running from terminal as I don't know how to run in a window.

As for terminal run, I was running Monaco font which seems doesn't have UTF-8 support.
Switched to Monospaced with UTF-8 support:
![image](https://cloud.githubusercontent.com/assets/414766/10766825/8e228186-7cd9-11e5-95ce-f566fc67b650.png)
I am still concerned with this part:
![image](https://cloud.githubusercontent.com/assets/414766/10766837/9d56a7e0-7cd9-11e5-915e-0ec53a16a165.png)

The other question: how to run emacs not from terminal given that I've installed it using official instructions?

**Comment by TheBB** [comment]
I just pushed a fix today on the develop branch for that bug, I believe. How updated are you?

**Comment by TheBB** [comment]
AFAIK `emacs` should run a GUI. I don't know if there's any specific OS X instructions.

**Comment by mclearc** [comment]
In order to run emacs as a GUI on OS X, installed via homebrew, you have to run `Emacs.app`. Homebrew either linked it to `/Applications` or it is in `usr/local/opt/emacs-mac` (assuming that was the version gotten from homebrew).

**Comment by m3nthal** [comment]
mclearc, thank you! found Emacs.app in usr/local/opt/emacs-mac
