### ISSUE TITLE
Yasnippet configuration bug (can't append to the yas-snippet-dirs variable)

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#3572]
the `add-to-list` function accepts a parameter to append at the end of the list passed, so with
```
(add-to-list 'yas-snippet-dirs "some-path" t)
```
it should append it to the last, but this doesn't do that. So I went and looked at what the variable value was, and found this:

```
("~/.spacemacs.d/snippets" "~/.emacs.d/snippets" yas-installed-snippets-dir 
"/home/jarvis/.emacs.d/elpa/ansible-20150319.133/snippets" 
"/home/jarvis/.emacs.d/elpa/haskell-snippets-20150612.1239/snippets" . "/home/jarvis/.emacs.d/layers/auto-completion/snippets")
```
That final `.` doesn't make sense ;_;

**Comment by TheBB** [comment]
Thanks, fixed in https://github.com/syl20bnr/spacemacs/commit/cd7bf33278cc3b200e2a6000c696ad282defa5e3.
