### ISSUE TITLE
golden-ratio + toggle-centered-point does not keep cursor in center after window switch

### ISSUE THREAD

**Issue by gleber** [syl20bnr/spacemacs#3573]
With both these enabled after you jump between windows (if they are split horizontally), cursor is not positioned in the center of window. Upon first vertical movement, cursor does center itself correctly.

**Comment by gleber** [comment]
That is on commit 074f425dc5d233f24195ecc3021eb96ac9d55d4d

**Comment by TheBB** [comment]
I'm either not able to reproduce or I don't understand this problem. Can you post some precise repro steps?

**Comment by StreakyCobra** [comment]
I also can't reproduce this bug. More details and reproduction steps welcome.

**Comment by gleber** [comment]
Here's a visual example:
http://i.imgur.com/5U9BGMB.gif

I this video I repeatedly do the following actions:
1. move few times down (`<down>`)
2. swtich to another window (`SPC w <up>` or `SPC w <down>` or `SPC 1` or `SPC 2`)

As you can see after the switch, cursor lands somewhere roughly 1/3 of the window height, but adjusts to be in the center as soon as I do a move. 

Here's my config: https://github.com/gleber/dotfiles/blob/master/emacs/.spacemacs (I do not have golden-ratio nor centered-cursor enabled here yet)
Here's spacemacs fork which HEAD I use: https://github.com/gleber/spacemacs

**Comment by StreakyCobra** [comment]
I was able to reproduce it, even on `develop`. In my case it's even worse, because the cursor don't adjust to be in the center, it stays at 1/3…
