### ISSUE TITLE
recentf-max-saved-items

### ISSUE THREAD

**Issue by duerrp** [syl20bnr/spacemacs#3575]
In my humble opinion, `recentf-max-saved-items` (currently set to 100) is way too low. Is there any reason to keep it below 1000 (I don't see any problem even on my slowest machine and disk space is no problem either).

Moreover, the value is currently set in the config section of `recentf`'s use-package, so that it may be confusing for new users who want to override the value in their .spacemacs (need to use `with-eval-after-load` for it to take effect). If there's a consensus, I can open a pull request moving it to the init section and increasing it accordingly.

As an aside, I have to say again how much I enjoy using spacemacs. Amazing work everyone!

**Comment by TheBB** [comment]
> If there's a consensus, I can open a pull request moving it to the init section and increasing it accordingly.

At least move it. :-)

**Comment by duerrp** [comment]
There you go... I split it in two commits, so if the 1000 recent files is too much, you can just use the first one by cherry-pick...
