### ISSUE TITLE
Something wrong in ipython in eshell.

### ISSUE THREAD

**Issue by maplewizard** [syl20bnr/spacemacs#3576]
I use up key and trying to get the previous command but it failed. It only shows 'Not found'. I also want to use tab to complete, but I just get a tab in ipython.

**Comment by TheBB** [comment]
Don't use ipython in eshell, lauch ipython directly from python mode instead.

**Comment by maplewizard** [comment]
Thanks,  And to those who has encontered the same problem like me, please follow steps below:
1. open a python file or just get into python mode
2. C-c C-c

use M-p to scroll to recent command.
But the tab will call helm which is not very convinient for me.
