### ISSUE TITLE
Show guidelines was removed from haskell-indentation-mode

### ISSUE THREAD

**Issue by gracjan** [syl20bnr/spacemacs#3580]
The lines in https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/haskell/packages.el#L176-L192 should disappear.

**Comment by d12frosted** [comment]
@gracjan Yeah, it's already in develop branch. Thanks for caring about Spacemacs configurations!

**Comment by d12frosted** [comment]
Reference: #3527

**Comment by gracjan** [comment]
I would love to connect spacemacs to haskell-mode TravisCI build so that if
my changes break spacemacs I can instantly know what happened. How do I do
this?

**Comment by d12frosted** [comment]
@gracjan 
I think it's possible. First of all you do have a good portion of tests that could also be used with Spacemacs configurations. For example, just running your tests with Spacemacs master branch after removing indentation guides would show that it's broken.

Spacemacs also has tests in `tests` directory, though they are not related to `haskell` layer at all. It would be nice to have some `haskell` layer tests there which could help.

On weekends I'll think on this more.
