### ISSUE TITLE
How are the keys in undo-tree-visualizer configured?

### ISSUE THREAD

**Issue by ReneFroger** [syl20bnr/spacemacs#3582]
Sometimes I install Spacemacs to see if I'm missing something. That's now the case. :smiley:

I was impressed by the `undo-tree-visualiser`, accessible with <kbd>SPC</kbd> <kbd>u</kbd> <kbd>u</kbd>.

When I try <kbd>M-x</kbd> `undo-tree-visualiser`, I noticed there are differences.

In Spacemacs, pressing <kbd>j</kbd> and <kbd>k</kbd> brings you back and forward in the history. My `undo-tree-visualiser` is not able of that. When I looked in the Spacemacs configuration, I couldn't find the specific setting which is responsible for that.

Perhaps could anyone tell me how you could configure such behaviour?

**Comment by ReneFroger** [comment]
Nevermind, it reminds me of the <kbd>C-h k</kbd> feature and then I could figure it out.

**Comment by nixmaniack** [comment]
It's configured in `evil` in `evil-integration.el` in case you want the source. :smile:
