### ISSUE TITLE
Magit 2.3 Installations Problem

### ISSUE THREAD

**Issue by jmfurlott** [syl20bnr/spacemacs#3583]
Recent update to magit 2.3 is causing start up/update problems.

```
Warning (emacs): Unable to activate package `magit-gitflow'.
Required package `magit-2.1.0' is unavailable
```

**Comment by TheBB** [comment]
This is probably a problem with the dependencies of `magit-gitflow`.

Please report upstream: https://github.com/jtatarik/magit-gitflow

**Comment by jmfurlott** [comment]
I think it's been fixed upstream, anyways
