### ISSUE TITLE
clang-format not working

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#3584]
I've installed `clang-format-3.5` on my system, using c++ this is the error I get when I try to run `clang-format-buffer`:

`clang-format-region: Searching for program: No such file or directory, clang-format`

Do I need to create a symlink or alias for clang-format-3.5?
Can I do it inside emacs?

**Comment by jvillasante** [comment]
I've resolved this with a symlink, now I have this error when trying to invoke clang:
`clang-format-region: (clang-format failed with code 1: clang-format: Unknown command line argument ’-sort-includes’.  Try: ’/usr/bin/clang-format -help’)`

How can I resolve this?

**Comment by syohex** [comment]
Duplicated #3408 

See also
- https://llvm.org/bugs/show_bug.cgi?id=25213

**Comment by jvillasante** [comment]
Cool, but how to patch in the meantime?

**Comment by syohex** [comment]
No way. We need to wait until clang fixes this issue or applies my patch or create new repository for supporting old clang.

**Comment by syohex** [comment]
@jvillasante @EricTing  I think `-sort-includes` option issue is fixed by following commit. Please upgrade `clang-format.el` and check again.

https://github.com/llvm-mirror/clang/commit/d27c92ca6f5fcafbe4c63f6e2bc440f0e86f881a#diff-e094070cb41c78c4a39f1b870dd8827b

**Comment by TheBB** [comment]
Can confirm :+1:
