### ISSUE TITLE
Add a git microstate 

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#3585]
It would be super handy if we had a microstate that we could have around that could help stage files, unstage files, etc. 

Opinions?

**Comment by tuhdo** [comment]
Isn't that Magit? You can do that easily with `magit-status`.

**Comment by CestDiego** [comment]
@robbyoconnor explain in further detail what you would like to do

**Comment by robbyoconnor** [comment]
True -- but I wanna be able to not have to kill my flow -- currently you can't stage from the spacemacs keybinding...

**Comment by CestDiego** [comment]
wat do you mean by that?

**Comment by nixmaniack** [comment]
I can think of one use case with microstate. When in a buffer, if you want to stage hunks interactively, activate microstate, use `n,p` to move around hunks, `s` to split the hunk, stage with `S`, commit with with `c`, push with `P`. 
There might be other interactive things which can do with this state.

**Comment by robbyoconnor** [comment]
Yeah, basically what @nixmaniack said -- allow me to stage things, unstage etc :) -- Seriously would be awesome.

**Comment by CestDiego** [comment]
That would be awesome indeed.

**Comment by robbyoconnor** [comment]
This is more of a feature request than anything else -- I expect nothing but figured it couldn't hurt to ask :-)

**Comment by syl20bnr** [comment]
This was available with git-gutter but web replaced ut ne cause or sas mot stable enough, especially in org buffer. We never tried git-gutter+ though.

**Comment by justbur** [comment]
How would this be different from using magit diff?

**Comment by robbyoconnor** [comment]
I more want a way to push, pull, rebase, stage/unstage etc

**Comment by d12frosted** [comment]
Wait, but it differs from what @nixmaniack described. Could you please be more specific from what you want? Because right now it sounds like you want `magit-state` but in `micro-state` flavour. :smile:

**Comment by robbyoconnor** [comment]
> Wait, but it differs from what @nixmaniack described. Could you please be more specific from what you want? Because right now it sounds like you want `magit-state` but in `micro-state ` flavour. :smile:

Basically, yes.

**Comment by ralesi** [comment]
@robbyoconnor, I am working on a hunk-microstate (stage hunk, next / prev hunk, reveert hunk, stage file, commit), but it sounds like we are also interested in a magit-microstate to commit, pull, fetch, push.  All of those commands are accessible through `magit-` commands so it should be relatively easy, I have found that some `magit-` commands don't work too well if not run from an existing magit screen.  i.e. commiting is much more seamless experience if I do it from `SPC g s` than if I just run `M-x magit-commit`.

**Comment by robbyoconnor** [comment]
@ralesi -- I make no demands -- I understand that nobody is entitled to anything :)

**Comment by ralesi** [comment]
@robbyoconnor, @nixmaniack  , latest update to #3632 .  You can choose between using `git-gutter` or `git-gutter+` (which allows staging), or `diff-hl` as the navigation backbone.  I have to flesh out some of the areas, but the `git-gutter+` section is the most complete right now as an all encompassing micro-state (`SPC g.` to access).

**Comment by nixmaniack** [comment]
@ralesi I tried it! Nice integration of all features. Thanks! :+1:

**Comment by robbyoconnor** [comment]
@ralesi I love you -- thank you :heart:
