### ISSUE TITLE
Proposal: New experimental branch please

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#3591]
Gitter discussion https://gitter.im/syl20bnr/spacemacs?at=56321d7d1eaef54003dd7a9e

I'd like it if there were a new branch that could accept new code much faster than the current `develop`. @TheBB would have complete freedom to merge to that branch without affecting `develop` and new ideas could be tried out much quicker. I think this would make it more fun to contribute, because at the moment there is a significant lag after submitting a pr. Speeding up `develop` would be another option, but I thought a new branch would have less impact on the goals of the project. See the gitter discussion for more thoughts.

**Comment by syl20bnr** [comment]
This is already hard to maintain release branches and adding a layer is just a no go for me, sorry.

**Comment by StreakyCobra** [comment]
@syl20bnr Do you have any idea of another way to improve the collaboration? Because working one somebody's branch for one functionality is fine, but when it's come to build a functionality over a waiting PR it's difficult.

**Comment by justbur** [comment]
What if you didn't have to look at it at all and PRs from the experimental branch were given higher priority?

**Comment by justbur** [comment]
To clarify, allow @TheBB to have a branch to accept stuff that you don't worry about. We test on that branch and PR to develop

**Comment by d12frosted** [comment]
So as far as I understand, the idea is to allow some people to write into experimental branch, but when feature is ready they will make regular PR and it will come into develop only via your or @TheBB review.

**Comment by justbur** [comment]
what @d12frosted said. Just a way for a small group to collaborate more and play with new ideas.

**Comment by syl20bnr** [comment]
Adding a level of indirection does not worth it, it will hurt the agility of the project, make the commits graph more complex leading to even harder cherry-pick.

@d12frosted this is the develop branch. I don't understand where this idea comes from but if the trigger is the magit key binding commit then I don't understand why it was not merged sooner when I explicitly write `when it is merged (by me or @TheBB`).

**Comment by justbur** [comment]
@syl20bnr it's not the evil-magit thing. It's my expectation that if I submit a PR I'll have to wait for a month. Sorry, but that's the way it has been

**Comment by StreakyCobra** [comment]
@syl20bnr It's a general impression, not for a specific PR. Some of them are hanging for a while without any reason, they seems to be forgotten.

**Comment by TheBB** [comment]
That's fine. Maybe it would help if I sped up movement on develop a bit? I've been perhaps too conservative when choosing what PRs to merge.

**Comment by syl20bnr** [comment]
Sorry guys but there won't be another level of indirection, I don't want to have PR that is merged in a vaccum for testing. We have not fix the issue of PR that should be merged in release branch as well.

**Comment by justbur** [comment]
ok, I respect your decision

**Comment by syl20bnr** [comment]
I can already feel the headache to add another question on PRs like `do we merge this in experimental ? Is this experimental ? How we can keep track of stuff in experimental ? How do we cleanup this branch ?` etc.... It smells a complete nightmare to me.

_BUT_ exceptionally we can create an accurately named branch to test something but I don't see a real use case of this, we have already the PR branches indirection where people can create branch locally themselves and merge the PR. Not a lot of people want to experiment so it seems OK to me.

**Comment by syl20bnr** [comment]
@TheBB I trust you so as long as you think `this is the good thing to do` I see no problem, if there is a mistake we can fix it.

**Comment by TheBB** [comment]
That'll work for me. :+1:

**Comment by justbur** [comment]
>if there is a mistake we can fix it.

yes, mistakes can be fixed very quickly
