### ISSUE TITLE
New Vim key bindings for Magit

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#3592]
Commit https://github.com/syl20bnr/spacemacs/commit/150e38e adds support for custom key bindings for Magit instead of the automatically defined evilified key bindings.

You can post your feedback here or in the official PR thread here: https://github.com/magit/evil-magit/pull/2 (recommended)

**Comment by justbur** [comment]
I just noticed the new reset key, `#`, conflicts with `magit-gh-pulls`. I like `#` for reset, but I'm open to suggestions on how to resolve this.

**Comment by PierreR** [comment]
I believe it is really useful to be able to switch branches without going through the status buffer and pressing `bb`. So I have this in my .spacemacs. 

```
(evil-leader/set-key "gc" 'magit-checkout)
```
Could we offer something similar in the standard `spacemacs` ?

**Comment by justbur** [comment]
@PierreR just do a PR for it. Seems reasonable to me. I think this issue was more about the decisions made within evil-magit.

**Comment by cpaulik** [comment]
Having 

```elisp
 (evil-snipe
  :variables
  evil-snipe-enable-alternate-f-and-t-behaviors t)
```

activated breaks the keybindings for `F` and `f` in magit

**Comment by TheBB** [comment]
For magit-gh-pulls and gitflow: well, `@` and `&` are available, if you want to stick to those kinds of keys.

**Comment by justbur** [comment]
The single letter keys are mostly take and are more of a pain to move. There are lots of modifier keys available and the "symbols". I like # for reset because of the analogy to gmail but C-r also works for me. I have no idea what the "natural keys" for gh-pulls and gitflow are. Is reset is moved the old ones can stay.

**Comment by syl20bnr** [comment]
`#` is the official key binding of magit-gh-pull, would be better to not touch it. We have plenty of room for a reset binding that does not conflict.

**Comment by syl20bnr** [comment]
> The single letter keys are mostly take and are more of a pain to move.

This is the price to pay for a custom evilification but it seems to worth it.

**Comment by syl20bnr** [comment]
> C-r also works for me

I like it too. I would not take a Google key bindings as a good reference in this context :-D
Otherwise @TheBB proposition of another symbol on the shifted number line could do it.

**Comment by justbur** [comment]
I think I like `C-r` the best, but I don't have a strong opinion

**Comment by justbur** [comment]
for what it's worth reset was on `x`

**Comment by syl20bnr** [comment]
`C-x` is not available and `C-r` is more mnemonic, looks good to me.

**Comment by justbur** [comment]
Ok. I made the change. Doesn't mean I can't change it again.

**Comment by syl20bnr** [comment]
If it changes it is for the better :-D

**Comment by herbertjones** [comment]
Does this mean evilification will be gone completely?  Window bindings seem to be gone, if I `M-1`, instead of jumping to window 1, now it does a `magit-section-show-level-1-all` and a `2gt` tries to switch to "Tracked files" instead of getting intercepted by the `eyebrowse` layer.

**Comment by justbur** [comment]
@herbertjones Those bindings were not provided by evilification. They just weren't being shadowed and now they are. It will be impossible to avoid all conflicts, so we'll just have to deal with the important cases. If you think "gt" for jump to tracked files is a bad binding, then propose an alternative. Otherwise we can disable that magit binding for the people who use the eyebrowse layer. 

Same goes for the window select one, but it's worth pointing out that `SPC 1` works fine

**Comment by herbertjones** [comment]
No, I'll just override them in my personal config as eyebrowse isn't a default layer.  `M-1` to `M-9` are important to me as shells do not respect `SPC-1` but do respect the Alt key.

**Comment by justbur** [comment]
We can easily override the M-[number] ones in spacemacs, depending on what
@syl20bnr thinks

**Comment by syl20bnr** [comment]
TBH, I'm really divided on this custom evil bindings, for now I want to believe that it worth the work put on them because Magit is such a central piece of the Emacs ecosystem that it could work.

But instead of stop the leaks I would rather make it possible to easily choose between Magit custom evil key bindings and auto-evilified buffer (which will be y choice obviously :-)).

I see that the work to adapt the help popup of Magit could be applied to the auto-evilifed buffer as well.
