### ISSUE TITLE
Make suggested Haskell REPL configs the default.

### ISSUE THREAD

**Issue by joehillen** [syl20bnr/spacemacs#3595]
I think it's odd that [these settings](https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/haskell#repl-is-stuck) aren't already part of the Haskell layer. I think they should be added to the layer.

I'll open a PR if anyone agrees with me.

CC @d12frosted

**Comment by d12frosted** [comment]
At some point I proposed this in #3292. But then we agreed that these configurations should not be part of Spacemacs. More info [here](https://github.com/syl20bnr/spacemacs/issues/445#issuecomment-149573890). If you have any questions or objections - let's talk :smile:

**Comment by joehillen** [comment]
Ah, thanks for the background info. I guess this needs to be fixed in haskell-mode instead.

**Comment by d12frosted** [comment]
You are welcome :smile: And yes, I think it should be fixed in `haskell-mode` and not here. In any case, I hope that users that run into problems with REPL will find solution in documentation :smile:

**Comment by joehillen** [comment]
> find solution in documentation

Stranger things have happened. :laughing:
