### ISSUE TITLE
evil-magit breaks bindings for `magit-gitflow` and `magit-gh-pulls` 

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#3603]
We need new keybindings for these! '#' is reset and '%' `evil-jump-item` since we're in evil motion state by default when in magit status buffer. 

Suggestions?

**Comment by TheBB** [comment]
Well, `@` and `&` are available, if you want to stick to those kinds of keys.

**Comment by justbur** [comment]
Can we keep these issues in #3592? I already mentioned this problem there

**Comment by TheBB** [comment]
Good call.
