### ISSUE TITLE
Set maximum number of rollbacks to save. 

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#3607]
Just noticed my rollback dir just got to 350mb.  Maybe we can set up a limit of number of rollbacks to save so it doesn't get overloaded?

**Comment by bmag** [comment]
:+1:

**Comment by TheBB** [comment]
Fixed by #3670.

**Comment by robbyoconnor** [comment]
> Fixed by #3670.

That is just freaky.
