### ISSUE TITLE
Python layer : more than one init function found.  

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#3608]
I get this warning when starting Spacemacs with the python layer enabled, I don't see anything in the python layer that could be causing it.  It doesn't just label `anaconda` but all packages used in the layer.  

````
(Spacemacs) Warning: More than one init function found for package anaconda-mode. Previous owner was python, replacing it with layer python.
````

**Comment by bmag** [comment]
Is it possible that `python` is listed more than once in your `dotspacemacs-configuration-layers`? I once had the same error but for a different layer, because I had the layer listed twice by mistake.

**Comment by ralesi** [comment]
@bmag, I don't know why I didn't think of this.  Thanks.
