### ISSUE TITLE
Menu, Toolbar, and Font usage

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#361]
I can't find any reference to toggle presence of toolbar and menubar in the frame.  I was thinking we should add that, and also custom variables to allow setting user preferences for toolbar, menubar, and font.  

I guess the alternative is to put all preferred user settings in the post-init section of the `.spacemacs` file; however at least the hard-coded font sizes in `spacemacs-mode.el` don't work with any of my resolutions.

**Comment by syl20bnr** [comment]
@ralesi for the font size it is possible to change it with `spacemacs/set-font` function put in `dotspacemacs/config`
