### ISSUE TITLE
Erase buffer functionality - should the user be prompted?

### ISSUE THREAD

**Issue by eipplusone** [syl20bnr/spacemacs#3610]
Here: https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bdistribution/spacemacs-base/funcs.el#L547

I was curious to why this was chosen as a _default_ behavior for the erase buffer functionality. Doesn't abide by the unix philosophy. I'd imagine if a user calls this function, they are prepare to get it erased. If that is no longer desired, a simple undo returns to where it was before.

Thoughts?

**Comment by a13ph** [comment]
[Never warn instead of providing undo, if you can](http://www.alistapart.com/articles/neveruseawarning)

For discoverability sake - have a reminder in echo, that user can actually undo and how, since we don't support Common User Access
