### ISSUE TITLE
*Helm Help* is not evilified

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#3616]
If you enter `*Helm Help*` buffer from helm using `C-c ?`,  can't use normal `hjkl` for navigation. It's not evilified.

**Comment by codygman** [comment]
Can anyone point to a simple helm mode that is evilified? This would drastically help anyone interested (possibly me) implement this feature.

**Comment by CarlQLange** [comment]
There's not a lot to do about this. `helm-help` uses its own keybindings, because it's actually an expanded helm session so you don't lose context when you're looking at the help. For more details, check this issue on helm: https://github.com/emacs-helm/helm/issues/1859

**Comment by nixmaniack** [comment]
Although I don't use helm, this is still an issue.

**Comment by lebensterben** [comment]
this is likely to be evilified now as we've recently evilified all special-mode buffer.

**Comment by nixmaniack** [comment]
@lebensterben I have switched to `ivy` but this is still an issue with `*Helm Help*`, confirmed on latest `develop`.

**Comment by nixmaniack** [comment]
If this isn't a sought after request, I'm OK if this remains closed.

**Comment by lebensterben** [comment]
@nixmaniack 
Thanks for reporting. I reopened the issue.
