### ISSUE TITLE
Location for private snippets

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#362]
Where is the suggested location for private `yasnippet` snippets?  I was thinking we could have an autoloaded folder in `private`, but I was also wondering if we should add a check for each layer for presence of snippet folder.  

For example, we could have additional python snippets added in the python contrib layer.

Each package can manage this separately, but it can also be if a feature of the configuration system.

**Comment by syl20bnr** [comment]
Fixed with #503
Thank you @ralesi
