### ISSUE TITLE
Git layer : defined git bindings for different use cases.  Visual, Diff, Hunk, Time, GH

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#3631]
This will keep hunks in `SPC g h` and the smeargle commands as `SPC g v`.

**Comment by ralesi** [comment]
Let me know, and I can submit a PR if this would be OK.

**Comment by syl20bnr** [comment]
Funny I was working on this because of a merge. I moved it under `gH` in commit https://github.com/syl20bnr/spacemacs/commit/96e7c8e

**Comment by ralesi** [comment]
I also have another PR making a hunk microstate. #3632.  I think hunk and diff should be clearly delineated,  i.e. Hunk performed within buffer,  diff in a separate pane.

**Comment by ralesi** [comment]
I am going to close this and state a discussion of different use cases.  I would like to make it to the point that I don't need to use an external git app for anything anymore.
