### ISSUE TITLE
Disabling anti-aliasing does not work as expected

### ISSUE THREAD

**Issue by AbelHeinsbroek** [syl20bnr/spacemacs#3638]
Disabling antialiasing in the OS-X GUI develop branch results in a weird mix of anti-aliased and aliased text:

![wierd](https://cloud.githubusercontent.com/assets/13994761/10884339/e1f0017e-8177-11e5-889e-16cfd6a51541.png)

Config used:

```
   dotspacemacs-default-font '("Monaco"
                               :size 10
                               :antialias nil
                               :weight normal
                              :width normal
                             :powerline-scale 1.1)
```

**Comment by agzam** [comment]
setting `ns-antialias-text` to nil seemed to work for me. Although frankly I quickly changed it back.

**Comment by davidpelaez** [comment]
Any way to solve this? I have very ugly separators in the powerline and don't know how to fix it :(

**Comment by bobthetoad** [comment]
@davidpelaez As for the separators try changing the `powerline-scale` attribute in your `.spacemacs` to something larger. I think they are a bit too small from the screenshot.
