### ISSUE TITLE
Go layer keeps looking in the wrong $GOROOT

### ISSUE THREAD

**Issue by honza** [syl20bnr/spacemacs#3640]
Every command fails due to the `$GOROOT` env var being set to a non-existent directory `/usr/local/Cellar/go/1.3.3/...`. Instead, it should look in 1.5.1 which is the version of Go currently installed. I never set the `$GOROOT` var anywhere in my shell or Emacs.

**Comment by TheBB** [comment]
CC @bogdanteleaga maybe?

**Comment by bogdanteleaga** [comment]
Hmm, it does not seem related to spacemacs for starters. Maybe take a look at go-mode?

Or you could try manually setting the var so it doesn't go to a default(seemingly erroneous) value.

**Comment by ntcong** [comment]
exec-path-from-shell-copy-env because on osx the program does not take bash's environment, I don't think it will affect GOROOT

Try to add GOROOT environment or add another exec-path-from-shell-copy-env with GOROOT

**Comment by honza** [comment]
I use the fish shell and set `GOPATH` there. But the GUI spacemacs doesn't pick that up because it uses the bash shell. I added `GOPATH` to `~/.bashrc` and all is well.
