### ISSUE TITLE
editing .spacemacs is no effect at all

### ISSUE THREAD

**Issue by sumyuga** [syl20bnr/spacemacs#3644]
I can't change any setting in my .spacemacs with effect (for example font size). Emacs is starting every time with all settings by default. Where is my fault?

**Comment by d12frosted** [comment]
Check that you don't have `~/.emacs` file.

**Comment by sumyuga** [comment]
I don't have any extra emacs files but I can't still change any parameters in (dotspacemacs-default-font). Meanwile I could change a theme.

**Comment by d12frosted** [comment]
Ah. You meant that emacs starts with default **Spacemacs** settings. Well, could you please show how you set `dotspacemacs-default-font`?

**Comment by TheBB** [comment]
Maybe you have specified an invalid font. If the font *name* you specify does not exist, then none of the font settings will be applied.

**Comment by sumyuga** [comment]
I have copied ~/.emacs.d/core/templates/.spacemacs.template file to ~/.spacemacs
And all settings are the same but when I try to change font size and font family etc – no effect at all

**Comment by d12frosted** [comment]
Are you running in terminal or GUI?

**Comment by sumyuga** [comment]
iTerm. Sorry it's my fault because of inattention. The problem is iTerm Profile

**Comment by TheBB** [comment]
Spacemacs can't set the font when running in terminal. You have to do that via your terminal emulator.

**Comment by sumyuga** [comment]
I got it. Thanks guys!
