### ISSUE TITLE
Switching themes breaks org-mode leading star hiding

### ISSUE THREAD

**Issue by sschuldenzucker** [syl20bnr/spacemacs#3651]
When I switch themes using `SPC T n` or `SPC T h` from e.g. `spacemacs-dark` to `spacemacs-light`, leading stars in Org-mode are not hidden as expected. Switching back to the previous theme does _not_ fix the issue. Deleting the buffer via `SPC b d`, then re-opening it _does_ fix it.
#### Pics

Before:

![before](https://cloud.githubusercontent.com/assets/1100776/10906123/3f9cdfd4-821f-11e5-9f45-49f68a100905.png)

After:

![after](https://cloud.githubusercontent.com/assets/1100776/10906125/46bd6dc4-821f-11e5-883c-7a0c9b2979e2.png)

Switching back:

![after](https://cloud.githubusercontent.com/assets/1100776/10906165/add249f8-821f-11e5-8c75-fd4bc35f653b.png)

Switching forth again, deleting and re-opening the buffer:

![after](https://cloud.githubusercontent.com/assets/1100776/10906213/f54e1f32-821f-11e5-90d6-7883d918e378.png)
#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.104.3
- Spacemacs branch: master (rev. 5dee44c)
- Distribution: spacemacs
- Layers:

``` elisp
(emacs-lisp markdown org latex spell-checking auto-completion)
```

**Comment by TheBB** [comment]
Yes, switching themes like this is not and will not be perfect. This is probably something we just have to live with.
