### ISSUE TITLE
Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by sumyuga** [syl20bnr/spacemacs#3652]
My host system is OS X and docker with Debian used to development. I have emacs 24.4.1 on Debian installed. After emacs starts I get this:

```
Warning (initialization): An error occurred while loading '/root/.emacs.d/init.el'
Wrong type argument: stringp, nil
```

As a result it's not working powerline with key bindings
But on my host system is all great.

**Comment by TheBB** [comment]
Do `--debug-init` to see where the error comes from.

**Comment by sumyuga** [comment]
after this command starts emacs shows "Entering debugger..." and it is frozen – no any reaction

**Comment by syl20bnr** [comment]
Is it with a vanilla `.spacemacs` ?

**Comment by sumyuga** [comment]
Of course. I have copied from template file ~/.emacs.d/core/templates/.spacemacs.template

**Comment by TheBB** [comment]
You can work around this error by opening `.emacs.d/elpa/archives/melpa/archive-contents` and deleting the `nil` at the end of the list. I'm not sure why that happens in the first place.

**Comment by sumyuga** [comment]
No, it doesn't work

**Comment by autosquid** [comment]
It looks like the same thing happened to me, and solution from @TheBB works.

**Comment by StreakyCobra** [comment]
@TheBB has documented this problem in the FAQ

**Comment by autosquid** [comment]
@StreakyCobra  In my case, delete the `elpa` and re-download did not solve the problem, but 
> by opening .emacs.d/elpa/archives/melpa/archive-contents and deleting the nil at the end of the list
 
works.

**Comment by sumyuga** [comment]
It's still not working for me. Guys, give a solution please.

**Comment by StreakyCobra** [comment]
Let me check if I have some ready-to-use solutions under my pillow… Nope, doesn't seem so.

If you want more help you will have to give us more information. Please provide us a comment following [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) to get started (backtrace in particular). Also you have a weird setup with docker, so it's not sure we can help much.

**Comment by sumyuga** [comment]
I have the same error:
`Warning (initialization): An error occurred while loading '/root/.emacs.d/init.el'
Wrong type argument: stringp, nil`
I've installed emacs (24.4.1) in my docker container (latest official debian image from hub.docker) and the way about deleting `nil` from archive-contents is not solution for me. And also any other one is not working for me. With `--debug-init` emacs freezes.
Spacemacs is up to date.

**Comment by sumyuga** [comment]
Backtrace:
```
Debugger entered--Lisp error: (void-function projectile-mode)
  (projectile-mode)
  (cond ((eq el (quote recents)) (recentf-mode) (if (spacemacs-buffer//insert-file-list "Recent Files:" (recentf-elements dotspacemacs-startup-recent-$
  (lambda (el) (cond ((eq el (quote recents)) (recentf-mode) (if (spacemacs-buffer//insert-file-list "Recent Files:" (recentf-elements dotspacemacs-st$
  mapc((lambda (el) (cond ((eq el (quote recents)) (recentf-mode) (if (spacemacs-buffer//insert-file-list "Recent Files:" (recentf-elements dotspacema$
  (let ((buffer-read-only nil) (list-separator "\n\n")) (goto-char (point-max)) (spacemacs-buffer/insert-page-break) (mapc (function (lambda (el) (con$
  (save-current-buffer (set-buffer (get-buffer spacemacs-buffer-name)) (let ((buffer-read-only nil) (list-separator "\n\n")) (goto-char (point-max)) ($
  spacemacs-buffer/insert-startupify-lists()
  (progn (spacemacs-buffer/insert-startupify-lists))
  (if dotspacemacs-startup-lists (progn (spacemacs-buffer/insert-startupify-lists)))
  (save-current-buffer (set-buffer (get-buffer spacemacs-buffer-name)) (if dotspacemacs-startup-lists (progn (spacemacs-buffer/insert-startupify-lists$
  (lambda nil (save-current-buffer (set-buffer (get-buffer spacemacs-buffer-name)) (if dotspacemacs-startup-lists (progn (spacemacs-buffer/insert-star$
  run-hooks(emacs-startup-hook)
  #[0 "\306 !^Q\n\204.^@^K\203.^@\f\307=\203#^@\310\311^K!\312\"\210\313\314^K!!\315P\202-^@\314\316\317^K\320 \321 $!^R^M\204?^@\322\323!\210^N^T\203$
  funcall(#[0 "\306 !^Q\n\204.^@^K\203.^@\f\307=\203#^@\310\311^K!\312\"\210\313\314^K!!\315P\202-^@\314\316\317^K\320 \321 $!^R^M\204?^@\322\323!\210$
  normal-top-level()
```

**Comment by StreakyCobra** [comment]
I don't think it's the problem described by @TheBB. Can you try to remove the `.emacs.d/elpa` directory and start with the `--insecure` flag?

**Comment by TheBB** [comment]
Yeah, I must have been mistaken. Sorry.

**Comment by sumyuga** [comment]
@StreakyCobra I've started with --insecure after deleting elpa dir and it's the same error:
```
Warning (initialization): An error occurred while loading '/root/.emacs.d/init.el'
Wrong type argument: stringp, nil
```

**Comment by sumyuga** [comment]
@syl20bnr Do you have some thoughts about my problem?

**Comment by AlejandroCatalina** [comment]
Could you paste the content of your `init.el` in pastebin and put here the link? There *must* be a problem somewhere. 

Anyway, why is it loading `init.el`? Shouldn't it be loading `.spacemacs`?

**Comment by sumyuga** [comment]
Here is the link http://pastebin.com/uGqcYtbC
I haven't any guess why it's happening

**Comment by syohex** [comment]
@sumyuga Could you try to set `SHELL` as below ?

```
# env SHELL=/bin/bash emacs
```

**Comment by sumyuga** [comment]
@syohex It's working! Thanks great for help. But I must run emacs with this command each time. How could I run emacs as usual with only `emacs`?

**Comment by TheBB** [comment]
@syohex Can you explain? We could turn this into documentation, at the very least.

**Comment by syohex** [comment]
(Sorry, I don't understand well about this), Some initialization is skipped if SHELL environment variable is not set and some functions/commands are called before its package initialization.

However this issues is a rare case. `SHELL` environment variable is always set via login process. Docker launches process directly without it, so SHELL environment variable is not set.

**Comment by natostanco** [comment]
I encountered this problem too.
If I `echo $SHELL`  I see it is set correctly, but to make the error go away I have to directly `export` the variable. Maybe it is the docker pseudo tty, I don't know.

**Comment by zv** [comment]
I had this issue with the `dot` language for Babel. Stepping through the error with edebug shows an issue with an uninterned symbol in the association list having a nil value.

I was able to fix this issue by running `org-element-cache-reset`.

**Comment by rltbennett** [comment]
Thanks for the tip. Note that you can also `(setq SHELL "/bin/bash emacs")` in your .spacemacs if you don't want to affect your shell's environment.
