### ISSUE TITLE
strange character in powerline

### ISSUE THREAD

**Issue by vantubk** [syl20bnr/spacemacs#3655]
![capture](https://cloud.githubusercontent.com/assets/12107448/10912949/5f584f5c-827e-11e5-9274-835b90c23dc8.JPG)

I use emacs 24.5.1 x64 on 64-bit windows 10, with spacemacs at lastest develop branch. 
I looked at #211, however this thread said that the error was already fixed.
Thanks for any help.

**Comment by TheBB** [comment]
You need to install a font that can display those unicode characters, or set `dotspacemacs-mode-line-unicode-symbols` to `nil`.

**Comment by vantubk** [comment]
I use Consolas (patched), and it worked fine with my Vim. AFAIK, patched fonts only use to beautify the  separate symbols, which is only needed in terminal mode.
I also try other fonts from https://github.com/powerline/fonts, but problem still occurs. also, Some other unicode symbols display correctly (sorry for not mention in the first post).
![capture](https://cloud.githubusercontent.com/assets/12107448/10914064/41f23108-8283-11e5-8308-15318c75abc5.JPG)

However, set `dotspacemacs-mode-line-unicode-symbols` to `nil` works, and I think I prefer this (which seems clearer with small font size). Many thanks !

**Comment by TheBB** [comment]
Yeah, I'm not talking about the separators. They are displayed as images. I'm talking about actual unicode symbols in the unicode standard. You sohuldn't need a patched font, just a font with good unicode support. I'm not sure why only some ringed symbols display while others do not, though. I also prefer the modeline without them. :-)

**Comment by Oxyrus** [comment]
I have the same issue, my powerline looks like this:

![http://i.imgur.com/NArJu9N.png?1](http://i.imgur.com/NArJu9N.png?1)

It was like that with the default font as well, tried with Consolas and the problem persists. My locale is set as en_US.UTF-8.

**Comment by JAremko** [comment]
@Oxyrus  try installing this font http://www.ffonts.net/NanumGothic.font.zip

**Comment by Oxyrus** [comment]
@JAremko Installed these fonts and my problem has not been solved

**Comment by a13ph** [comment]
@Oxyrus please provide your build of GNU Emacs for Windows. Do you use Cygwin or smth else?

**Comment by a13ph** [comment]
All interested in unicode issues might also take a look at https://github.com/rolandwalker/unicode-fonts which offers some hopeful pointers.

**Comment by Oxyrus** [comment]
@a13ph I'm using Emacs in Linux, should I provide my folders anyway?

**Comment by a13ph** [comment]
@Oxyrus Oh, sorry, you are not the OP. Folders? Contextual info should be provided ASAP anyways, why ask about it. I just found out that Cygwin has different font substitution system, so thought that might be the issue.
You should try link above.

**Comment by michael-stokley-tractmanager** [comment]
running `M-x all-the-fonts-install-fonts` resolved this for me.

**Comment by ngm** [comment]
I am using doom for `dotspacemacs-mode-line-theme`.  `M-x nerd-icons-install-fonts` fixed the issue for me.
