### ISSUE TITLE
holy-mode (randomly?) entering evil-mode

### ISSUE THREAD

**Issue by mattharrison** [syl20bnr/spacemacs#3657]
Sorry this is a lame bug report. I'm having a hard time reproducing this bug. But am seeing it often. I decided to give spacemacs holy-mode another attempt recently. In general I like it, but it is jumping back into evil-mode in both Python and JS modes. I'm trying to be cognizant of the keys that I'm typing to cause this to happen, but it is hard to reproduce. 

When it enters evil-mode, I have to type ``M-x holy-mode`` twice to get it back to holy mode. I also noticed that there is a log in messages when it flips into evil-mode ``Previous command was not an evil-paste...``

Here is some of my ``*Messages*`` buffer, with the errors prior to going back to holy mode:

    ...
    byte-code: Can't find f
    Auto-saving...done
    user-error: No replacement character typed
    user-error: Previous command was not an evil-paste: evil-backward-char
    user-error: Previous command was not an evil-paste: evil-paste-pop [2 times]
    user-error: Previous command was not an evil-paste: evil-paste-pop-next
    Holy mode disabled
    Holy mode enabled
    ...
    user-error: Previous command was not an evil-paste: evil-avy-goto-word-or-subword-1
    user-error: Previous command was not an evil-paste: evil-paste-pop [2 times]
    user-error: Previous command was not an evil-paste: evil-paste-pop-next
    user-error: Previous command was not an evil-paste: evil-paste-pop
    user-error: Previous command was not an evil-paste: evil-paste-pop-next [2 times]
    Holy mode disabled
    Holy mode enabled
    ...
    error in process filter: Quit [2 times]
    [No matches]
    Skip anaconda-mode eldoc response
    user-error: Previous command was not an evil-paste: next-line
    Holy mode disabled
    Holy mode enabled

**Comment by TheBB** [comment]
This is a known issue and will probably be fixed by #3497.

**Comment by mattharrison** [comment]
@TheBB Thanks for the update. I've probably been entering evil-mode by tapping my control key (which is mapped to escape when tapped....).

I will be following #3497 as disabling this escape behavior would be my preference.
