### ISSUE TITLE
spaceline issues in spaceline-prepare (persp-curr-name)

### ISSUE THREAD

**Issue by usharf** [syl20bnr/spacemacs#3658]
No mode line displayed.

Errors:

```emacs-lisp
Error during redisplay: (eval (spaceline--prepare spaceline-left spaceline-right)) signaled (void-function persp-curr-name)
Unable to load color "#292b2e"
Error during redisplay: (eval (spaceline--prepare spaceline-left spaceline-right)) signaled (void-function persp-curr-name) [6 times]
evil-record-macro: Invalid registerError during redisplay: (eval (spaceline--prepare spaceline-left spaceline-right)) signaled (void-function persp-curr-name)
QuitError during redisplay: (eval (spaceline--prepare spaceline-left spaceline-right)) signaled (void-function persp-curr-name)
Error during redisplay: (eval (spaceline--prepare spaceline-left spaceline-right)) signaled (void-function persp-curr-name)
```

Spacemacs v.0.105.0

.spacemacs contains

```emacs-lisp
     (perspectives :variables
                   perspective-enable-persp-projectile t)

**Comment by TheBB** [comment]
Lol... I added perspectives support to spaceline awaiting #2845, but I didn't expect that it would break on the current implementation would break. Apparently it has a minor mode called `persp-mode` which is different from the one used in #2845.

I'll fix it. It'll be up on MELPA soon, you can update your packages then.

**Comment by TheBB** [comment]
Oh dang, @CestDiego ... *you* implemented `persp-curr-name`. Prefix your functions man.

**Comment by CestDiego** [comment]
it was supposed to go upstream.. I'll change this

**Comment by TheBB** [comment]
Fixed in https://github.com/TheBB/spaceline/commit/8f79eee07cd3180a7318345cb3f2c3e2683c0d3b

No worries @CestDiego :+1:

**Comment by CestDiego** [comment]
also this doesn't have my PR enabled :( I changed it as well by prefixing everything in my PR

**Comment by joehillen** [comment]
This should be closed now that #2845 is merged.

**Comment by TheBB** [comment]
Indeed. It was actually fixed before that.

**Comment by usharf** [comment]
:+1:

**Comment by aborn** [comment]
good job!
