### ISSUE TITLE
Changelog for updated packages

### ISSUE THREAD

**Issue by wamaral** [syl20bnr/spacemacs#3659]
Using [vim-plug](https://github.com/junegunn/vim-plug) in Vim, after updating plugins you can press `D` to view a list of commits merged in last update, like so:

![image](https://cloud.githubusercontent.com/assets/279894/10917074/febaa934-8245-11e5-9adf-928427e8ff8b.png)

I think it could be a nice feature to have, after clicking the `[Update]` link.

**Comment by TheBB** [comment]
This would be great, but the vast majority of our packages don't come (directly) from repos.

**Comment by wamaral** [comment]
Oh I see, I assumed melpa was somehow linked to github or something :(

**Comment by TheBB** [comment]
In part it is (github, bitbucket, emacs wiki etc.), but I don't think all of the necessary information is exposed in the end-product which Spacemacs downloads.

**Comment by d12frosted** [comment]
Closing for being inactive. Would be nice to have anything like this though. But it's not really in Spacemacs scope (though you know, Spacemacs forces some progress) 😸
