### ISSUE TITLE
Python layer: Blocking call to accept-process-output with quit inhibited!!

### ISSUE THREAD

**Issue by bebound** [syl20bnr/spacemacs#366]
I add `python company-mode smex github` layers in .spacemacs .
Code completion works well on Windows, but on the Ubuntu, the code completion is not smart as windows, and here is a strange behavior:
Input the code:
```
if 1:
    pass
if 1:
```
After input RET, the line3 will add an needless indent at the beginning.
The "smart" means: on Windows, after input `pass` and RET, the next line will decrease indent, while on Ubuntu, it will keep the previous indent.

So is there any more steps to do on Ubuntu, or some layers are conflict on Ubuntu?
Thank you.

The complete .spacemacs is here: https://gist.github.com/bebound/505c2f6cb98deadf3db6

**Comment by proofit404** [comment]
Please try last `anaconda-mode`.

**Comment by kols** [comment]
still have the problem with latest (20150111.1101) `anaconda-mode`

**Comment by proofit404** [comment]
@kols please attach `*anaconda-mode*` buffer content.

**Comment by kols** [comment]
content in the buffer suggests a pip exception, and this is the corresponding pip log:

https://gist.github.com/kols/1d2cacb9d82dcb760309

finally solved by manually install `json-rpc` and `jedi` packages.

**Comment by proofit404** [comment]
Try to uninstall `json-rpc` and `jedi`, correct `distutils.cfg` (remove `prefix` option) and run anaconda ones again.

**Comment by kols** [comment]
@proofit404 I install python using homebrew, and didn't edit the `distutils.cfg` file which comes with it.
Thus I'm afraid changing this default setting will break other things.
Is there a way to work around it on anaconda side?

**Comment by proofit404** [comment]
You can try to comment this settings only for the anaconda-mode init  time.

**Comment by syl20bnr** [comment]
No solution has been found at the package level, @proofit404 added a section in the README about manual steps which must be performed to installed the dependencies of anaconda.

We have to put these steps explicitly in the README of the python layer.
