### ISSUE TITLE
anaconda-mode err.can't check md5 string correctly.

### ISSUE THREAD

**Issue by pr1n4ple** [syl20bnr/spacemacs#3662]
i solved this error by add one parameters to pip.main function.
in ~\.emacs.d\elpa\anaconda-mode-20150922.537\anaconda-mode.el
pip.main(['install', '-t', directory, 'anaconda_mode==' + version, '--no-cache-dir'])
" "Install `anaconda_mode' server.")

**Comment by TheBB** [comment]
Seems like you should ask [anaconda-mode](https://github.com/proofit404/anaconda-mode/), not us.
