### ISSUE TITLE
put magit-gitflow-popup binding back

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#3668]
`magit-gitflow-popup` keybinging disappeared (again) with the recent merges. If I’m remembering right it used to be `# f` and then someone changed it to `%`. Whatever you think would be the best combination, please put it back.

**Comment by nixmaniack** [comment]
We're tracking this in other issue #3592 https://github.com/syl20bnr/spacemacs/issues/3592#issuecomment-152237134

But yes, we definitely need some binding soon! @justbur?

**Comment by justbur** [comment]
It was being shadowed by the evil-magit bindings initially, but I fixed that. I am not responsible for changing the gitflow bindings

**Comment by nixmaniack** [comment]
I see. It's not being shadowed but now it's `ahs` and `evil-jump-item` that's being triggered. I think we need to add this to evil motion state now. I'll see if I can figure it out to fix it.

**Comment by justbur** [comment]
I figured out a simple way to fix this without messing with rebinding stuff. If you update evil-magit they should work again.

**Comment by nixmaniack** [comment]
@justbur Thanks! Updated packages. Back to normal bindings.

**Comment by nixmaniack** [comment]
@justbur Seems it doesn't play well. If I hit `#`, and the next binding is from motion state e.g. `g`, `which-key` pops up with option to press `r` i.e magit-refresh. Ideally `#g` is magit-gh-pulls-load.

**Comment by justbur** [comment]
Oh yes unfortunately the way magit pop ups work you have to manually adjust
them

**Comment by justbur** [comment]
And I haven't touched the pop ups outside of base magit.

**Comment by TheBB** [comment]
Seems this is working?
