### ISSUE TITLE
Difficulties with 0.104.x 

### ISSUE THREAD

**Issue by mgsloan** [syl20bnr/spacemacs#3669]
After blowing away `elpa`, I rather consistently get these two issues during package installation, on the develop branch:

> An error occurred while installing adaptive-wrap (error: (error Failed to verify signature adaptive-wrap-0.5.el.sig: ("Bad signature from 474F05837FBDEF9B GNU ELPA Signing Agent <elpasign@elpa.gnu.org>")))

> An error occurred while installing stan-mode (error: (cl-assertion-failed (or (= (buffer-size tar-data-buffer) (buffer-size)) (eq tar-data-swapped (> (buffer-size tar-data-buffer) (buffer-size))))))

More misc pastes: https://gist.github.com/mgsloan/f2bbed72e03084be075a https://gist.github.com/mgsloan/209f4f1305262b64e1c7

After initialization, it's frozen until I `C-g` a couple times.  After this rocky start, pretty much anything involving helm doesn't work.  For example, `SPC s a P` doesn't bring up helm ag.  Things seem sluggish and there are frequent freezes.

This originally started happening after hitting the Update button on the spacemacs screen.  I then tried with master, and got similar brokenness, and then tried with develop, and got more of the same.  Checking out the `v0.103.6` brought things back to working correctly.

Sorry for the lack of repro.  I have no idea what it is about my environment that could cause this.  I'm using `emacs 24.5.1` on `ubuntu 15.04`.

**Comment by StreakyCobra** [comment]
Con you try again today? I noticed some of these errors yesterday, but it went away for me today.

**Comment by mgsloan** [comment]
Yup, looks fixed!  I guess it really was some transient issue..
