### ISSUE TITLE
Better support for other non-included default themes

### ISSUE THREAD

**Issue by chenglou** [syl20bnr/spacemacs#367]
Themes in [here](https://github.com/syl20bnr/spacemacs/tree/master/contrib/themes-megapack) don't get the `dotspacemacs-default-theme` treatment, unlike the couple of officially supported ones. 

Guess this is very low-pri since currently I just enable it in `dotspacemacs/config`.

**Comment by syl20bnr** [comment]
all base16 themes are now supported from version 0.40.0

@chenglou Which theme is it ? From what package does it belong ?

**Comment by chenglou** [comment]
This one: https://github.com/syl20bnr/spacemacs/blob/master/contrib/themes-megapack/packages.el#L16

The tomorrow-night variant more specifically.

**Comment by syl20bnr** [comment]
Ok I'll give it a try, hopefullly I should be able to extract the common setup required for the non standard themes. Should not be so different than base16 ones.

**Comment by quartz55** [comment]
@syl20bnr yeee :D

**Comment by syl20bnr** [comment]
Should be OK for all the themes specified in this issue in 0.47.0
Related commit: https://github.com/syl20bnr/spacemacs/commit/acaf2c1c83c9cb8ce48b6c06ee4f1ed570074491
