### ISSUE TITLE
*help* buffer is very slow before popup

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#3671]
When I use `c-h v` or `c-h f` to open the `*help*` buffer, it will stuck for a moment, maybe 1-3s to finish.

After the `*help*` buffer is opened, I found that there are many minor mode activated in this buffer.

I think this is useless. 

How could I improve the speed of opening help buffer?

**Comment by StreakyCobra** [comment]
I didn't notice any delay when opening `*help*` buffer. Does it happens too with `SPC h d v` and `SPC h d f` ? Also can you run `SPC h d s` and paste the result here?

**Comment by zilongshanren** [comment]
@StreakyCobra 
This issue seems disappeared after I remove some of my own configs. I should close it here now.
Thanks.
