### ISSUE TITLE
Latest Spacemacs update breaks Evil mode

### ISSUE THREAD

**Issue by josiah14** [syl20bnr/spacemacs#3672]
I updated Spacemacs today and now Evil mode is not escaping into normal mode properly any longer.  It seems to drop me into Emacs mode, I think, and it seems most often when I'm editing a line of code and then try to get out into normal mode while there's some sort of syntax error being flagged by the editor.  It's causing me to accidentally delete paragraphs of code fairly frequently and makes the editor practically useless to me, at the moment.

This seems to be happening both in the console verson for Linux (running emacs -nw) and in the GUI version for OSX.

*note* I run the console spacemacs instance inside of Tmux, if that matters.

**Comment by joehillen** [comment]
Can you be more specific about what versions you are using? Are your packages up to date?

**Comment by josiah14** [comment]
I can only check my OSX install at the moment, but it says it's at version 0.101.x.

It's a fairly recent problem I've been noticing, and I didn't notice it on my linux install until I ran Update 2 days ago from the Spacemacs 'welcome' page that appears when I first start the editor.

**Comment by robbyoconnor** [comment]
Give `SPC hds` -- I run `develop` and see no issues. Also why run it in tmux -- emacs is capable of running a terminal emulator inside of it and many repls as well!

**Comment by robbyoconnor** [comment]
as @joehillen  said -- when reporting bugs ensure that your packages are up to date prior to reporting bugs, click `[Update]` -- `develop` has changed this behavior -- so it's not `[Update Packages]`

**Comment by gregpardo** [comment]
I personally have had issues in the past running spacemacs inside emacs. I can't remember what specifically but some things didn't seem to be working right. Could you try running in GUI application?

**Comment by josiah14** [comment]
@gregpardo: 

After some working at it, I was actually able to get things running smoothely again on OSX by completely deleting the .emacs.d directory and re-cloning Spacemacs.  Not sure why running update and pulling directly from origin master didn't work out well for me, but until I can get you guys some better information on how to reproduce this issue, I'm going to close it.

**Comment by gregpardo** [comment]
Yeah I've had to do such things before. Whenever something isn't working this is my first goto solution too. Re-clone and reinstall all modules. Glad you figured it out.
