### ISSUE TITLE
Imenu in elisp buffers stops working without semantic layer

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#3676]
Steps to reproduce:
1) Enable emacs-lisp layer in my .spacemacs file (note: the semantic layer is not activated)
2) start spacemacs
3) open a .el file
4) hit SPC s l (spacemacs/jump-in-buffer). A helm buffer with no imenu entries pops up.

**Comment by zilongshanren** [comment]
```
  (defun lisp-imenu-make-index ()
    (interactive)
    (save-excursion
      (imenu--generic-function '(("function" "\\s-*(defun\\s-*\\([a-zA-Z/-]+\\)" 1)))
      ))

  (add-hook 'lispy-mode-hook
            (lambda ()
              (progn
                (setq-local imenu-create-index-function 'lisp-imenu-make-index))))

```

I have written the above patch, but it's not working.

The `imenu-create-index-function` is always `semantic-create-imenu-index`.

@TheBB Thoughts?
Thanks.

**Comment by TheBB** [comment]
I can't reproduce the problem. I am fully updated as of a few hours ago. `SPC s l` works fine here.

**Comment by zilongshanren** [comment]
@TheBB 

What's the value of `imenu-create-index-function ` in a emacs-lisp buffer?

**Comment by TheBB** [comment]
It's `semantic-create-imenu-index`

**Comment by zilongshanren** [comment]
@TheBB 
Wired... Have you enabled semantic layer? or Have you enable `semantic-mode`?

**Comment by TheBB** [comment]
I have the semantic layer.

**Comment by zilongshanren** [comment]
@TheBB 
My issue is "imenu without semantic" can't work.

Is semantic a mandatory for imenu to working with elisp?

**Comment by TheBB** [comment]
Sorry, I thought the issue was *with* the semantic layer, since you mentioned that in step one of your repro.

**Comment by zilongshanren** [comment]
@TheBB  
My bad.. Is there any workaround for this issue?

**Comment by nixmaniack** [comment]
I hit this issue yesterday but mostly I'm using semantic.

**Comment by bmag** [comment]
I've hit a somewhat similar issue in Python buffers in the past, see the issue in #2569 and the solution in #2583. It's not the same bug as yours, but maybe it can give you an idea.

**Comment by zilongshanren** [comment]
@bmag 
I have brought semantic layer back again.
