### ISSUE TITLE
Spacemacs commands don't work in vc-annotate buffer

### ISSUE THREAD

**Issue by mmlac-bv** [syl20bnr/spacemacs#3687]
If I use vc-annotate and switch to the buffer none of the vim navigation keys as well at Space work.

**Comment by StreakyCobra** [comment]
It's probably a mode that is candidate for evilification at the same time. If someone want to go on it.

**Comment by deb0ch** [comment]
I just used vc-annotate and evil works just fine there.

I'm reporting this as fixed, let me know if it actually isn't so that we reopen this issue :smile:

**Comment by dvzubarev** [comment]
Hi, I use Emacs: 25.1.2 and Spacemacs: 0.200.2
I can confirm that none of vim's navigation keys work in vc-annotate buffer.
I tried it for files under svn and git.
I used C-x v g combination to get to the annotate buffer.

Info if needed.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.2
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 spacemacs-layouts ibuffer
 (colors :variables colors-enable-rainbow-identifiers t)
 emacs-lisp semantic my-dired my-diffs my-projects
 (dash :variables helm-dash-docset-newpath "~/.local/share/Zeal/Zeal/docsets")
 my-dash eww python my-python docker ansible my-ansible cypher
 (c-c++ :variables c-basic-offset 4 c-default-style "linux" c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support nil)
 c++ markdown html
 (org :variables org-enable-reveal-js-support t)
 my-org pandoc ob-ipython
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 my-shell
 (syntax-checking :variables syntax-checking-enable-by-default t)
 spell-checking
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 git github evil-cleverparens
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 finance sql edbi edit-utils imenu-list prog-utils vagrant vinegar yaml my-ycmd floobits exactus)
```
