### ISSUE TITLE
Error (use-package) in startup

### ISSUE THREAD

**Issue by 230v** [syl20bnr/spacemacs#3688]
Error (use-package): spaceline-config :config: Symbol's function definition is void: spaceline-info-mode

![_2015-11-06_09-31-01](https://cloud.githubusercontent.com/assets/9416005/10991832/36f4f4ce-8469-11e5-8862-1fd2b5f6987a.png)

**Comment by nixmaniack** [comment]
Update packages. #3675

**Comment by 230v** [comment]
Already up-to-date.

**Comment by TheBB** [comment]
What's your spaceline version? Check in `.emacs.d/elpa/`

**Comment by 230v** [comment]
@TheBB spaceline-20151025.613

**Comment by TheBB** [comment]
That's not updated. The latest version is from November 4th.

Go to your home buffer and click update packages.

**Comment by 230v** [comment]
Thanks, thats all i need :)

**Comment by StreakyCobra** [comment]
@230v If this solved your issue you can mark it as closed :smile:
