### ISSUE TITLE
Perspectives first launch issues

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3690]
After I installed the new perspectives layer, I restarted emacs.

The spacemacs home buffer was shown for a bit, and then it went blank.  

In messages I see:

```
[persp-mode] Error: No such file -- "/Users/synic/.emacs.d/.cache/perspectives/persp-auto-save".
```

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 3fb3877)
- Distribution: spacemacs
- Layers:
```elisp
(unscroll auto-completion xkcd emacs-lisp git gtags dash yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors eyebrowse perspectives vimscript
          (c-c++ :variables c-c++-enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by robbyoconnor** [comment]
@CestDiego

**Comment by synic** [comment]
This doesn't seem to be a thing anymore with the layouts layer.
