### ISSUE TITLE
Auto-compile-mode will automatically compile file when using flycheck-mode

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#3694]
@syl20bnr, @justbur Looks like the change to auto-compile-mode results in files being compiled if flycheck-mode is enabled.  When flycheck-mode is checking files, it creates a temp compiled file with the same name, a hash `.elc`, so it seems when `auto-compile-mode` sees this, it will compile the primary file.    Anyone see this issue?  I see it on my ms-windows machines.

**Comment by justbur** [comment]
Anyway to make flycheck create a file with a different name or in a different folder? @lunaryorn

**Comment by StreakyCobra** [comment]
We did notice sometimes `*.elc` file being generated without explicitly asked. That could be the cause.

**Comment by TheBB** [comment]
I wasn't able to create a spurious `.elc` this way on my first try, but I have seen random `.elc`s popping up, so I'm liable to agree there is a bug somewhere.

**Comment by justbur** [comment]
I'm also unable to reproduce this with flycheck. @ralesi are you sure flycheck is the cause.

**Comment by lunaryorn** [comment]
Flycheck uses a different name for its byte-compiled files, and it creates its `.elc` files in the temporary directory.  That's all I can say.  I'd like to see a step-by-step recipe to reproduce this issue in `emacs -Q` with Auto Compile and Flycheck before I'm willing to believe that it's actually a Flycheck issue.

**Comment by nixmaniack** [comment]
I did face this now, where `~/.spacemacs.elc` was created which I had never seen before. And changing `~/.spacemacs` didn't have any effect until I noticed this `.elc` file. Seems like recently introduced bug but I couldn't confirm if it's flycheck/autocompile.

**Comment by justbur** [comment]
Random guess but is it possible that a proper temp directory is not found or can't be accessed and it's defaulting to the current directory?

**Comment by justbur** [comment]
Disregard the last comment. I filed an issue upstream

**Comment by TheBB** [comment]
Good catch @justbur

**Comment by lunaryorn** [comment]
I'd like to thank everyone for finding and fixing this issue.  I'd thank you more so, if you had started searching for the issue _before_ bringing me in to listen to random guesses. 😒 No offense meant 😊

**Comment by justbur** [comment]
Already fixed

**Comment by tarsius** [comment]
I have created a new release `1.3.0` -- you might wanna depend on that.
