### ISSUE TITLE
FAQ updates

### ISSUE THREAD

**Issue by xificurC** [syl20bnr/spacemacs#3695]
A couple notes on this
- the [develop version](https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org) of the FAQ has broken links - Iget a `404`
- the [Windows section](https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#windows) would need update on at least 2 things
  - the MacType link points to a google code repo that is not maintained anymore. It states it moved to github but the gh repo has just 1 commit with 1 file - a `README`
  - the same subsection states one should disable smooth scrolling on Windows. I think it would be beneficial to state the why :)

**Comment by TheBB** [comment]
The 404s are expected. We are phasing out github as the official way to view documentation online.

**Comment by StreakyCobra** [comment]
Can you propose your Windows section changes as a PR maybe @xificurC ? :smiley:

**Comment by xificurC** [comment]
@StreakyCobra I'd love to but I'm not sure

- if people still recommend MacType. For me fonts look OK without it.
- what is the reason for recommending to turn off smooth scrolling.

If I can get someone's advise on this I'll gladly put it in a PR

**Comment by StreakyCobra** [comment]
Hum, as I haven't Windows I can't really verify. Let's tag this one as Windows, and ask windows user on gitter if they can help.

**Comment by lzhoucs** [comment]
I am on windows 7. The reason I can think of to disable smooth scrolling is that those two keys are not working as expected:
<kbd>H</kbd>	move cursor to the top of the screen
<kbd>L</kbd>	move cursor to the bottom of the screen

Instead of moving to the top/bottom of the screen, I can only move to 6th line to the top/bottom. Disabling smooth scrolling fix this issue. But I do get another issue #5325

**Comment by bleggett** [comment]
Fonts do look IMHO slightly better with MacFonts, but it's a rather drastic and invasive bit of software by necessity so as a Windows user I'd be OK with not recommending it.

**Comment by Miciah** [comment]
The recommendation to disable smooth scrolling may have come from reports of related performance issues: https://github.com/syl20bnr/spacemacs/issues/5884#issuecomment-323147400 https://github.com/syl20bnr/spacemacs/issues/6689#issuecomment-236832898 https://github.com/syl20bnr/spacemacs/issues/8710
