### ISSUE TITLE
Helm find files to the right

### ISSUE THREAD

**Issue by Calrama** [syl20bnr/spacemacs#3702]
I would like for the helm selection that pops up on "SPC f f" to be to the right of the selected window instead of below it. I have set ```helm-split-window-default-side``` to ```'right```, so when I manually call ```(helm-default-display-buffer "*Messages*")``` (or on any existing buffer) it will properly be shown to the right of the selected window. However, if I press "SPC f f" the helm selection buffer will still appear on the bottom of the selected window, despite it using helm-default-display-buffer internally. How can I make "SPC f f" (and for that matter all helm things) always appear to the right of the current selected window?

**Comment by TheBB** [comment]
There is a `dotspacemacs` variable for this. Have you tried that?

**Comment by ralesi** [comment]
The variable is dotspacemacs-helm-position.  Set it to `'right`

**Comment by Calrama** [comment]
Thank you, I'm still new to configuring things in dotspacemacs instead of at the packages itself. It works, though now the helm window at the right side takes nearly 80% of the availabe screen space. Closing, since this is a different issue.
