### ISSUE TITLE
Modeline wrapped when running in terminal

### ISSUE THREAD

**Issue by liangwang** [syl20bnr/spacemacs#3703]
The modeline wraps-up in the end, and overlap the text of status at the left bottom. 
![screen shot 2015-11-07 at 10 55 25 am](https://cloud.githubusercontent.com/assets/492743/11015910/6e200d14-853e-11e5-8082-c0f0c07c0e48.png)

Spacemacs is the latest v104.4, it is running in iTerm2 on MacOS 10.10

**Comment by Compro-Prasad** [comment]
Please update both spacemacs and Emacs and report back.
