### ISSUE TITLE
spc s L should find the last search

### ISSUE THREAD

**Issue by icambron** [syl20bnr/spacemacs#3707]
I could definitely be misunderstanding something, but if I use `spc s p` to search for something and then later do `spc s L`, I only see this message in the minibuffer:

```
No previous search buffer found
```

I expect it to bring up the previous search results in helm. If this expectation is correct and it's not trivial to fix, I'm happy to take a crack at it. In the meantime, I can use `spc h l` as a workaround (though since I also use `spc p f`, this isn't great).

As a total aside, it's a little weird that the search one uses `L` and the general helm one uses `l`. I don't use `jump-in-buffer` much so my preference would be to settle on `l` for both, but consistency is more important to me than any specific choice.

**Comment by nixmaniack** [comment]
Currently `SPC s L` only works if you have saved results after you searched and saved them using `F3`.
But yes, it would be nice addition to have `SPC s L` to work as `SPC h l` with last searched term.

**Comment by icambron** [comment]
Oh, thanks. I'll edit the title.
