### ISSUE TITLE
Problems with repeated SPC u

### ISSUE THREAD

**Issue by bonega** [syl20bnr/spacemacs#371]
Working case:
I tap "SPC u SPC".
The status field first displays "SPC u SPC u SPC -".
After a short while it reverts to "SPC u SPC -", after this it works as intented.

In several buffers it will not revert and therefore will produce incorrect results.

**Comment by syl20bnr** [comment]
Related to `key-chord`. It will work on removing it from Spacemacs, it does not play well with `evil`.

**Comment by tshort** [comment]
I'll miss those key chords!

**Comment by syl20bnr** [comment]
Which key chords ?
In spacemacs there are only 2 bindings using it, `fd` from `evil-escape` (I'm the maintainer of it) and `jk` for some experimental features.
I'll plan to replace completely `key-chord` but the 2 above bindings will remain functional.

If you have defined additional key chords then you'll still be able to install `key-chord` in your private layer, but you'll get side effects like the one mentioned here.

**Comment by tshort** [comment]
Just those. It was unclear if they were going away.

**Comment by bonega** [comment]
@syl20bnr Visually it seems to work, but I still don't get the expected behavior.
For example I am standing in a local git branch that I want to push to my repo with a specific target branch:

my-cloned-repo/local-branch -> github-repo/other-branch

I would usually do `C-u C-u` and be asked by magit to fill in the branch name.
To me it seems that `SPC u SPC u` doesn't do anything for the repeat.
`SPC u C-u` works fine.

**Comment by syl20bnr** [comment]
This is not the same bug but there is still an issue with repeated SPC u so I reopen it.

It may require some hackery to pass the first universal argument to the next u.
