### ISSUE TITLE
Unable to quit out of git-blame-micro-state if invoked on untracked file

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#3711]
Open any untracked file and do `SPC g b`. It'll error out with `user-error: Buffer isn't visiting a tracked file
` and it enters micro-state from which you can't exit out with `C-g`, `fd`, `ESC`, `ESC ESC ESC`, `q`.

**Comment by TheBB** [comment]
I was about to merge your PR but I actually don't have this problem in the first place...

**Comment by justbur** [comment]
I can't reproduce this either

**Comment by nixmaniack** [comment]
There's update in micro-state code. Perhaps it fixed it. I'll try it out now and if it has fixed, I'll close this.

**Comment by justbur** [comment]
What's the purpose of the blame micro state?

**Comment by nixmaniack** [comment]
You can keep blaming back in the history by successively hitting `SPC g b` and then `b` `b` `b`.. till the git history takes you back.

**Comment by justbur** [comment]
But doesn't calling `magit-blame` again and again already do that?

**Comment by nixmaniack** [comment]
Yes. f7a2f9c2cd8956aef84e1eca894a43b712d09256 fixes this issue. So only the ms "doc" was getting generated which I wasn't able to quit.

**Comment by nixmaniack** [comment]
@justbur How would you call magit blame in a buffer you're currently visiting? Micro state allows you to go back if you have gone far back in history with `q`

**Comment by justbur** [comment]
`M-x magit-blame`? I don't think I understand the question. `q` also works to step back

**Comment by nixmaniack** [comment]
Before the introduction of `evil-magit` and sophisticated evilification, keys like `q` were not working in normal state of emacs, so in essence it was impossible to quit out of magit-blame-mode. Now `q` works in normal mode fine with magit-blame buffer. There were open issues regarding this. 

Also, if I start with `M-x magit-blame` I have to hit `b` to open popup and `b` to go deeper in history, so two keystrokes(even though it's same key!), with micro-state once you enter, you can just use `qb` to go back and forth.

**Comment by justbur** [comment]
Hmm, I see. Thanks for the clarification @nixmaniack
