### ISSUE TITLE
Symbol's value as variable is void: auto-complete-mode after pressing SPC t a

### ISSUE THREAD

**Issue by tommyjiang** [syl20bnr/spacemacs#3713]
I use Emacs 24.5.1 & Spacemacs 0.104.4 on OS X 10.11.1. 

When I first add the layer `auto-completion` and restart Emacs to install the new packages including `company` and others, the auto completion function works well for me.

However, when I restart Emacs and open the `.spacemacs.d/init.el` file then press `SPC t a` to enable auto-complete-mode I get the error 
```
Symbol's value as variable is void: auto-complete-mode
```

I try this in LaTeX mode with AUCTeX but everything seems fine. I can not figure out what happens. Maybe it only breaks in Lisp mode?

**Comment by tommyjiang** [comment]
I update some packages yesterday and I find this issue is solved after the update. Still can not figure where is the problem.

**Comment by TheBB** [comment]
I'm not sure why you found the issue solved, but it's actually been there for quite a while.

Fixed by https://github.com/syl20bnr/spacemacs/pull/5383

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
