### ISSUE TITLE
avy jump signals args-out-of-range error in YAML buffer with vim-empty-lines layer

### ISSUE THREAD

**Issue by lunaryorn** [syl20bnr/spacemacs#3717]
With `yaml` and `vim-empty-lines` layers enabled, `evil-avy-goto-word-or-subword-1` (on `SPC SPC`) fails with the following error in a  [YAML buffer](https://github.com/flycheck/flycheck/blob/6fe7e08b595f726c80c433ebfbab7a3fb5450c8f/.travis.yml),:

```
Debugger entered--Lisp error: (args-out-of-range 1 1194)
  avy--find-visible-regions(1 1194)
  avy--regex-candidates("\\bs" nil nil)
  avy--generic-jump("\\bs" nil at-full)
  avy-goto-word-1(115 nil)
  call-interactively(avy-goto-word-1)
  avy-goto-word-or-subword-1()
  call-interactively(avy-goto-word-or-subword-1)
  evil-avy-goto-word-or-subword-1(nil)
  call-interactively(evil-avy-goto-word-or-subword-1 nil nil)
  command-execute(evil-avy-goto-word-or-subword-1)
```

Removing the `vim-empt-lines` layer solves the issue.

**Edit:** Name the guilty layers.

**Comment by StreakyCobra** [comment]
I can't reproduce it here with your file. `yaml` layer enabled, emacs 24.5.1, last `develop`, packages updated.

**Comment by lunaryorn** [comment]
@StreakyCobra I dug a little deeper:  You need to enable the `vim-empty-lines` layer as well.  Without this layer, everything works fine, but if the layer is enabled any fails.

**Comment by StreakyCobra** [comment]
Indeed, I can reproduce it with `vim-empty-lines`.

**Comment by StreakyCobra** [comment]
Also, it's not related to `yaml-mode`, but to the content of the buffer. Setting my `.spacemacs` in `yaml-mode` and `SPC SPC` works, but pasting your `travis.yml` content in scratch buffer make `SPC SPC` fails.
