### ISSUE TITLE
Spacemacs does not have a Lean major mode

### ISSUE THREAD

**Issue by 11Kilobytes** [syl20bnr/spacemacs#3721]
Hello everyone, I'm writing a major mode for the Lean proof assistant for Spacemacs. The official major mode is lean-mode, which requires the following packages in order to function: `dash dash-functional f s`
.
These packages are system packages that I feel I shouldn't own, as they will be needed by many layers other than mine. However, if these packages aren't installed then the mode won't work. How should I proceed?

**Comment by TheBB** [comment]
Just add them to `dotspacemacs-additional-packages`. It's harmless.
