### ISSUE TITLE
Anaconda-mode and issue #2917 returns?

### ISSUE THREAD

**Issue by rebcabin** [syl20bnr/spacemacs#3723]
I am getting strange behavior in anaconda mode, which seems to be related to autocompletion and also to some kind of rapid-keystroke keychording.  I'll describe he two problems separately, but they occur in the same buffer.  I'm on the develop branch, all packages freshly updated, and my .spacemacs is here https://gist.github.com/rebcabin/829790cecdd539e19d66

consider the following python code in a buffer all by itself (MVE):

```
def foo (x):
    with open("foobar.txt", "r") as fd:
        fd.
```
The trouble starts on the last line.  PROBLEM 1: if I type `fd.` slowly, I get the dreaded error message from issue #2917:

```
eldoc error: (error 127.0.0.1%3anil/80 nodename nor servname provided, or not known)
```
PROBLEM 2: if I type `fd` quickly, Emacs switches from the emacs keyset into the vim keyset and does not input `fd`

**Comment by TheBB** [comment]
The first one is probably this https://github.com/proofit404/anaconda-mode/issues/128

The second is known, there is a PR in the pipeline to fix it.

**Comment by rebcabin** [comment]
Ok. I'll try the suggested workarounds in the link and in #2917
