### ISSUE TITLE
Make C-c C-e in helm-find-files switch to wdired

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#3724]
Right now, `helm-ag` has `C-c C-e` built in, a handy way to edit ag results. To do the same from `helm-find-files` requires hitting <kbd>F2 C-x C-q</kbd>. Could we add a command to `helm-find-files` at `C-c C-e` to do this for consistency sake? Should I propose this to `emacs-helm` or is this more a spacemacs/user level issue?

**Comment by aaronjensen** [comment]
@TheBB I'd like to help close out an issue, maybe this one. Would helm be the right place for this or spacemacs-helm?

**Comment by AlejandroCatalina** [comment]
I think spacemacs-helm is the right place.

**Comment by TheBB** [comment]
Yep. Thanks :+1:

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
