### ISSUE TITLE
syntax-checker configuration for bundler

### ISSUE THREAD

**Issue by howdoicomputer** [syl20bnr/spacemacs#3726]
I'm just starting out with Spacemacs and the Flycheck plugin seems to be unable to correctly guess my path to RuboCop. I'm pretty sure Flycheck allows wrapping a command through its API but I'm just starting out with Emacs Lisp and am a little confused about how to configure Flycheck to use `bundle exec` for RuboCop. Do I need to define an entirely new checker? Can I just specify the check name and the command I want to wrap the check call with?

http://www.flycheck.org/manual/latest/Flycheck-hooks.html
https://github.com/flycheck/flycheck/pull/752#discussion_r42037713

**Comment by rashkov** [comment]
You can provide the path to rubocop by using SPC-e-S or flycheck-set-checker-executable. Then you select which checker you want to configure (rubocop), then you provide the full path to rubocop's executable.

**Comment by asymmetric** [comment]
@rashkov is there a way to configure it to use rbenv's shims? Even if I point `flycheck-set-checker-executable` to `~/.rbenv/shims/rubocop` I still get `rbenv: rubocop command not found` - although it's present in that ruby version.

**Comment by rashkov** [comment]
@asymmetric Not sure what the problem could be as I'm also using rbenv, and also pointing it to ~/.rbenv/shims/rubocop. Maybe you can try running rbenv rehash and then try again with spacemacs. Also make sure that you can invoke rubocop from the command-line against a ruby file and see that it works properly.

**Comment by asymmetric** [comment]
@rashkov how are you making spacemacs aware of rbenv? I'm running `eval $(rbenv init -)` inside my `~/.zshenv` file (which seems the right choice as that's what loaded by non-interactive shells), but still I get the error.

One more question: where have you installed your gems? I have them local to the project (i.e. I passed the `--path` option to bundler).

And yes, rubocop is available straight from the shell.

Thanks!

**Comment by rashkov** [comment]
I never made spacemacs aware of rbenv, it has always worked out of the box. In fact, I just turned off rbenv and tested out spacemacs, and rubocop still works when I point spacemacs to ~/.rbenv/shims/rubocop

I turned off rbenv by exporting my PATH without the rbenv directories. Running which ruby now pointed to my system ruby instead or rbenv's ruby. Then I launched spacemacs from that shell, pointed flycheck's rubocop to the wrong executable to "break it", then pointed it back to ~/.rbenv/shims/rubocop, and after editing the file a little and saving it rubocop woke up and started working again.

My gems are all installed to ~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems
I just do bundle install to take care of my project-specific gems, and I'm pretty sure they all install to that directory that I just listed. However I never installed rubocop through bundler. It is not even in my gemfile. I installed it via "gem install rubocop".

Also this comes to mind: recently my rbenv broke on another computer, and I had to delete (or move) the ~/.gems directory. The gems in that folder were interfering with rbenv. That might be something to try as well

**Comment by asymmetric** [comment]
I see. The difference between my setup and yours is that my rubocop is installed via bundler, so flycheck would need to run `bundle exec`. If I install rubocop wih `gem install`, it works from Emacs.

I suspect the solution involves implementing a function to pass to [`flycheck-command-wrapper-function`](https://github.com/flycheck/flycheck/blob/master/flycheck.el#L426), but I haven't been able to come up with one yet, as I've never written any Lisp :)

**Comment by rashkov** [comment]
Just realized that this entire github issue is about bundle exec, my bad. I've totally ignored that aspect.

Yes, flycheck-command-wrapper-function definitely appears to be the right place to fix this. Wish I could help with that but I would also need to pick up some elisp before that happens.

**Comment by bryan-ash** [comment]
👍 I've recently switched over to Spacemacs and would love to see this one fixed.

**Comment by yourpalal** [comment]
After trying a bunch of things with flycheck-command-wrapper, I realised that there's a much simpler solution!.

1. `mkdir ~/bin/`
2. ensure that ~/bin/ is in your PATH. (run spacemacs/edit-env for instance)
3. `echo '#!/bin/bash\n\nbundle exec rubocop "$@"' > ~/bin/rubocop`
4. `chmod +x ~/bin/rubocop`
5. restart emacs

Emacs will now use your wrapper script in ~/bin/rubocop, thereby running rubocop with `bundle exec`
