### ISSUE TITLE
new package or local package for evil-indent-textobject

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#3728]
@TheBB 

Updating through quelpa is slow and hopefully is a temporary solution. What are the chances we can make your version of evil-indent-textobject into a package that extends the original or just use it as a local package?

**Comment by TheBB** [comment]
We could make it local. I believe it's unlikely to be on MELPA since it's a fork, unless we do some rebranding.

**Comment by justbur** [comment]
there are packages that are "plus" versions. I wondered if it could be that. I think local would be preferable to using quelpa indefinitely

**Comment by justbur** [comment]
I was trying to get rid of all of the quelpa packages (at least the ones that are pulled in by my config) which is possible if we can do something else with this one. See #3727 #3696

**Comment by TheBB** [comment]
Yes, I understand.

**Comment by TheBB** [comment]
https://github.com/milkypostman/melpa/pull/3283

**Comment by justbur** [comment]
Seems reasonable to me

**Comment by syl20bnr** [comment]
Another solution than the rebranding is to take ownership of the package and just update the MELPA recipe to use your fork. I'm sure that MELPA maintainers will be opened to this solution given the current situation.

**Comment by TheBB** [comment]
Done as of https://github.com/syl20bnr/spacemacs/commit/8125ccea8f78d535af6f6bd8ea88e57d78a83a06.
