### ISSUE TITLE
Potential clash in `avy` when package in dotspacemacs-additional-packages depends on it

### ISSUE THREAD

**Issue by vkz** [syl20bnr/spacemacs#3729]
Adding [lispy.el](https://github.com/abo-abo/lispy) to `dotspacemacs-additional-packages` results in a weird bug related to `avy` commands. Since there may potentially be an issue with how dependencies play out for something you install as `dotspacemacs-additional-packages` I'm raising this issue for someone to review and decide there's something for Spacemacs folk to consider.

Here's the issue as reported in the `lispy` repo: https://github.com/abo-abo/lispy/issues/139

**Comment by nixmaniack** [comment]
I hit this issue after updating packages, but didn't know if it was my configuration even though I don't have any lispy specific configs. I can't reproduce consistently though. I also faced `hydra` bug and had to require it before lispy started working again then this `Args out of range error` kept popping up inconsistently.

**Comment by endrebak** [comment]
I have a different issue:

Trying to execute `M-x lispy-mode` I get the error: 

```
autoload-do-load: Symbol's value as variable is void: lh-knight
```

I have also installed lispy by just putting this in my `.spacemacs`:

```
   dotspacemacs-additional-packages '(lispy)
```

Mine is reproducible (for me at least). Anyone else experiencing the same thing? (I have never gotten lispy to work with spacemacs.)

**Comment by nixmaniack** [comment]
I did experience this then I have following in my configuration which works as of now. It's because of hydra package I think and lispy not being compiled correctly(wild guess). There are still couple of quirks like company mode pops up with "No completion found.." on repeatedly hitting backspace but it works pretty much fine. 

Be sure to remove hydra and lispy from your elpa before restarting emacs with following config. Since I use hybrid mode, it's tailored for it which also defines `lispy-mark-symbol` key at the end since `M-m` is used by spacemacs. 

```elisp
(use-package lispy
  :init
  (progn
    (spacemacs/load-or-install-package 'hydra)
    (defun turn-on-lispy-mode ()
      (when (member major-mode
                    '(emacs-lisp-mode lisp-interaction-mode clojure-mode racket-mode))
        (require 'hydra)
        (lispy-mode)))
    (defun turn-off-lispy-mode () (lispy-mode -1))

    (add-hook 'evil-hybrid-state-entry-hook  'turn-on-lispy-mode)
    (add-hook 'evil-hybrid-state-exit-hook 'turn-off-lispy-mode)
    (define-key evil-hybrid-state-map (kbd "s-m") 'lispy-mark-symbol)))
```

**Comment by endrebak** [comment]
Thanks! Do you put that in a `layer` or somewhere in your `.spacemacs` or what?

**Comment by nixmaniack** [comment]
@endrebak in `user-config` section of `.spacemacs`

**Comment by vkz** [comment]
Posted an update in abo-abo/lispy#139

Question to audience: how does one go about bisecting Spacemacs configuration? In my old hand-written configs I would simply comment stuff out.

**Comment by TheBB** [comment]
You can comment stuff out in Spacemacs too. If it's a package that breaks it, you can start by disabling layers and excluding packages until you find something.

**Comment by ryepesg** [comment]
The issue "void-variable lh-knight" on installing lispy occurs even with the standard installation of spacemacs. However, reinstalling and choosing just spacemacs-base solves the problem.
Related issue: https://github.com/abo-abo/lispy/issues/148
