### ISSUE TITLE
Problems with brackets in haskell-mode

### ISSUE THREAD

**Issue by simonjantsch** [syl20bnr/spacemacs#3734]
In haskell it is common to use anonymous function that are declared like this : 
\x -> x+x
When specifying a function over for list or tuple type, one would write: 
\\(x,y) -> foo or
\\[x,y,z] -> bar
When doing this however the bracket matching function of spacemacs escapes the first bracket sign after \ and thus all brackets in the document that come after are highlighted.

**Comment by d12frosted** [comment]
Do you mean that when you hit `\[` it inserts `\[\]` instead of `\[]`? If so, then you should share result of `SPC h d s` and also check that you don't have any funky settings for smartparens.

**Comment by simonjantsch** [comment]
What I mean is, if i write
\\[x,y,z] -> [x] 
then all bracket signs in the expression but the first one will be highlighted

**Comment by TheBB** [comment]
Because of unmatched parentheses? I can't reproduce this. Works fine here.

**Comment by d12frosted** [comment]
The same, works for me fine

<img width="255" alt="screenshot 2015-11-09 16 58 20" src="https://cloud.githubusercontent.com/assets/6507913/11037523/dd320eb8-8706-11e5-9613-32b1a4299815.png">

**Comment by simonjantsch** [comment]
Hm ok, im not sure why im having this but I'm using spacemacs out of the box pretty much. I am attaching a screenshot with the the file I was editing.
![screenshot_2015-11-09_16-25-49](https://cloud.githubusercontent.com/assets/13819379/11037595/cebe0d76-86fe-11e5-9765-c5531c60ea0f.png)

**Comment by d12frosted** [comment]
Could you, please, share your `.spacemacs` so I can check it out?

**Comment by StreakyCobra** [comment]
It would also be nice to share the problematic part of your file (if the content is not sensible). It will help to reproduce :relaxed:

**Comment by simonjantsch** [comment]
Thanks for trying to solve the problem. I'm attaching my .spacemacs file
[.spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/32288/default.spacemacs.txt)

**Comment by d12frosted** [comment]
Have terrible internet connection right now, so can't really reproduce it (MELPA is not available!). But when I think about your problem I remember having something very similar in JSX files. I haven't hunted that problem, that's why I haven't reported it yet. 

In any case, with my setup I don't see this problem in haskell file. Will try your spacemacs file later when I have better connection.

**Comment by d12frosted** [comment]
Still can't reproduce. Can you verify that it still happen with latest packages and Spacemacs?

**Comment by simonjantsch** [comment]
I have not had this problem for a while now, so I'm closing the thread.
