### ISSUE TITLE
`spacemacs-layouts` loading is broken.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3736]
The new `spacemacs-layouts` layer no longer persists the layouts.  It used to auto-load a default list of layouts, but now that no longer happens.

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. d14f10e)
- Distribution: spacemacs
- Layers:
```elisp
(unscroll auto-completion xkcd emacs-lisp git gtags dash yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors perspectives vimscript
          (c-c++ :variables c-c++-enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by d12frosted** [comment]
The same here.

**Comment by syl20bnr** [comment]
Should be fixed in develop branch, if this is OK on your side you can close this issue.

**Comment by synic** [comment]
Works!
