### ISSUE TITLE
org-set-tags only allows completing a single tag

### ISSUE THREAD

**Issue by elubeck** [syl20bnr/spacemacs#3738]
Hello,

Org-set-tags differs slightly from the expected behavior of being able to autocomplete multiple tags for a headline.  After autocompleting a single tag the minibuffer exits.  If multiple tags are in my history they can be completed, but novel combinations of multiple tags are not autocompleted.

Thanks

**Comment by tomjorquera** [comment]
Hi @elubeck ,

Sadly, this is a problem between org-mode and helm (see the discussion [here](http://comments.gmane.org/gmane.emacs.helm.user/457)).

A quick workaround is to disable helm completion for org-set-tags. It can be done by adding the following to your .spacemacs config:
`  (add-to-list 'helm-completing-read-handlers-alist '(org-set-tags))`
You will then have the "classic" completion for org tags, that works as expected.

Not sure if it would be relevant to add this to the org layer by default...

**Comment by tomjorquera** [comment]
I just noticed by directly adding `(add-to-list 'helm-completing-read-handlers-alist '(org-set-tags))` directly to the spacemacs config *does not* actually work. Spacemacs complains on startup that the `helm-completing-read-handlers-alist` variable does not exists (not sure why). 

Instead I added the following to my user config:
```
(add-hook 'org-mode-hook
            (lambda () (add-to-list 'helm-completing-read-handlers-alist '(org-set-tags))))
```
that correctly set the variable when launching org-mode.

**Comment by olejorgenb** [comment]
It doesn't seem to be possible to completely remove tags with the helm interface either. After testing the native function I'd vote to change the default to not use helm until the issues are fixed.

**Comment by edran** [comment]
I can still reproduce this behaviour in develop (95422ae).

As described in emacs-helm/helm#2063, it seems like the issue is on our side :(

**Comment by duianto** [comment]
>It doesn't seem to be possible to completely remove tags with the helm interface either. After testing the native function I'd vote to change the default to not use helm until the issues are fixed.

When editing org tags (`org-set-tags`) with `helm-mode` enabled.

The tags can be removed by pressing `C-RET` or `M-RET` which calls `helm-cr-empty-string`.

The keys are visible on the mode line, when not using Spacemacs or any mode line packages

![emacs_2020-06-15_16-29-04](https://user-images.githubusercontent.com/13420573/84670203-1ab66300-af26-11ea-841a-c7829f2f507c.png)

### In Spacemacs 

The keys are not visible with the mode line themes:
- `spacemacs` (default) (https://github.com/TheBB/spaceline)

![emacs_2020-06-15_16-22-24](https://user-images.githubusercontent.com/13420573/84670521-86003500-af26-11ea-98e2-543294cf4ab0.png)
- or `doom` (https://github.com/seagle0128/doom-modeline)

![emacs_2020-06-15_16-01-24](https://user-images.githubusercontent.com/13420573/84670534-8ac4e900-af26-11ea-8f31-9f64ae2e8069.png)

But the keys are visible with the `vanilla` mode line theme:

![emacs_2020-06-15_16-03-44](https://user-images.githubusercontent.com/13420573/84670472-797bdc80-af26-11ea-90f6-bda937245563.png)

**Comment by iliakur** [comment]
Thanks @duianto this resolved a long-standing inconvenience for me. Is there a way to include this keybinding in the spacemacs mode-line? I'd be willing to submit the relevant patch with a little guidance
