### ISSUE TITLE
micro-state broken in some places

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#3739]
Everything up to date.  

In `SPC b .` and `SPC n >` throws `while: Wrong type argument: stringp, 1 [14 times]`. 

The commands do get executed but the error in minibuffer keeps popping.

**Comment by StreakyCobra** [comment]
Yep, just reproduced it.

**Comment by TheBB** [comment]
Here's the relevant part of the backtrace. `spacemacs//micro-state-set-minibuffer-height` is called with an integer. Looks like it's caused by @syl20bnr (CC) messing with that code last night.

```
Debugger entered--Lisp error: (wrong-type-argument stringp 1)
  string-match("\n" 1 0)
  (while (string-match regexp str start) (setq start (match-end 0)) (setq count (+ count 1)))
  (let* ((start 0) (count 0)) (while (string-match regexp str start) (setq start (match-end 0)) (setq count (+ count 1))) count)
  how-many-str("\n" 1)
  (1+ (how-many-str "\n" str))
  (let ((line-count (1+ (how-many-str "\n" str)))) (if (and (> line-count max-mini-window-height) (> line-count 10)) (progn (setq max-mini-window-height line-count))))
  spacemacs//micro-state-set-minibuffer-height(1)
  (progn (spacemacs//micro-state-set-minibuffer-height (let ((bdoc) (defdoc "[n]ext [p]revious [K]ill [q]uit")) (if bdoc (apply (quote corelv-message) (list (spacemacs//micro-state-propertize-doc (format "%S: %s" ... bdoc)))) (when (and defdoc (quote spacemacs/next-useful-buffer) (not (plist-get ... :exit))) (spacemacs//micro-state-set-minibuffer-height defdoc) (apply (quote corelv-message) (list (spacemacs//micro-state-propertize-doc ...))))))) (let ((bdoc) (defdoc "[n]ext [p]revious [K]ill [q]uit")) (if bdoc (apply (quote corelv-message) (list (spacemacs//micro-state-propertize-doc (format "%S: %s" (quote buffer) bdoc)))) (when (and defdoc (quote spacemacs/next-useful-buffer) (not (plist-get (quote ...) :exit))) (spacemacs//micro-state-set-minibuffer-height defdoc) (apply (quote corelv-message) (list (spacemacs//micro-state-propertize-doc (format "%S: %s" ... defdoc))))))))
```

**Comment by nixmaniack** [comment]
As a workaround I've just modified the function being used [how-many-str](https://github.com/syl20bnr/spacemacs/blob/2670d01a7836c6f8cd40ce0bc53346dd2108c595/layers/%2Bdistribution/spacemacs-base/funcs.el#L904-L909) as follows. 
```elisp
(defun how-many-str (regexp input)
  (let ((str (if (numberp input)
                  (number-to-string input)
                input)))
    (loop with start = 0
          for count from 0
          while (string-match regexp str start)
          do (setq start (match-end 0))
          finally return count)))
```

**Comment by justbur** [comment]
Also having the problem. I traced it to the code for the micro-state wrapper function `spacemacs//micro-state-create-wrapper`, but gave up after that.

**Comment by ralesi** [comment]
I just submitted #3785 which seems to have fixed the issue.

**Comment by TheBB** [comment]
Closed by #3785.

**Comment by TheBB** [comment]
@ralesi This error still happens with e.g. the helm microstate.

**Comment by ralesi** [comment]
I haven't tried that state,  but I dont get the string-p error on the buffer micro-state anymore.

**Comment by TheBB** [comment]
Yeah, me neither, but I can produce it with: `SPC b b` (or anything else helm), `M-SPC` (enable the micro-state) and `?` (show documentation).

**Comment by syl20bnr** [comment]
Is this bug still here ?

**Comment by nixmaniack** [comment]
@syl20bnr yes as TheBB said you can reproduce with: `SPC b b` (or anything else helm), `M-SPC` (enable the micro-state) and `?` (show documentation).

**Comment by justbur** [comment]
I doubt this is a problem anymore, but there may be something new that crops up with the helm transient state because I haven't been able to test it much.

**Comment by nixmaniack** [comment]
@justbur You can't toggle the documentation anymore, but if that's going to stay as is,  it makes this transient state more prominent as opposed to previous one where it wasn't visible at all. 

Besides, I think you shouldn't be able to type any other character apart from what keybindings are present in transient state once you enter transient state. In current version I'm able to type(I think this was the case previously as well) which is kind of confusing.

**Comment by justbur** [comment]
@nixmaniack 

> You can't toggle the documentation anymore, but if that's going to stay as is, it makes this transient state more prominent as opposed to previous one where it wasn't visible at all.

I added toggles to the layouts transient state if we want to add that here we can

> Besides, I think you shouldn't be able to type any other character apart from what keybindings are present in transient state once you enter transient state. In current version I'm able to type(I think this was the case previously as well) which is kind of confusing.

I believe that was the previous behavior, but it's easy to change that by deleting [this line(https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bcompletion/spacemacs-helm/packages.el#L466)

**Comment by nixmaniack** [comment]
@justbur We should have it toggles for doc it's useful when you forget something but don't like have it always pop in. 

I tried by deleting the line, but every non-transient-state key exits, is there a way to make it stick unless you hit `q`

**Comment by justbur** [comment]
@nixmaniack Now I'm not sure what you're after. `:foreign-keys` controls whether keys not defined in the transient state are run while the transient state is open.

**Comment by nixmaniack** [comment]
@justbur No problem, I read about [`:foreign-keys`](https://github.com/abo-abo/hydra#foreign-keys) and I was after `:foreign-keys warn`.

**Comment by justbur** [comment]
hm, ok. It's @syl20bnr's call I guess. I don't ever use this one.

**Comment by nixmaniack** [comment]
I don't see the error anymore with the transition to hydra based transient state. Closing.
