### ISSUE TITLE
neotree broken (not displaying files, display issues, cursor jumps to bottom)

### ISSUE THREAD

**Issue by ysgard** [syl20bnr/spacemacs#3743]
Neotree appears broken in the current pull of spacemacs.  

Spc f t opens neotree as expected, but when I click on a folder, the entire file tree gets selected and no files appear in the opened folder.

If I use the keybindings to select a folder and hit enter, the cursor jumps to the bottom of the opened tree, and sibling folders below the opened folder disappear (but the sibling folders above the opened folder remain).

Sometimes files will appear in opened folders, sometimes not.  I cannot get this behaviour to reproduce in a consistent manner.

I'm using Emacs 20.0.50 on OS X 10.11.

I'm pretty sure this isn't a neo-tree specific issue because before I was using spacemacs (I began using it a week ago) I was using plain Emacs with Neotree, and that setup worked fine.

I tried deleting my elpa directory to refresh the packages, but no luck.  This is with a stock, unmodified .spacemacs.

**Comment by TheBB** [comment]
> I'm using Emacs 20.0.50

I seriously doubt that. :-D

**Comment by ysgard** [comment]
You're right, sorry, it's 25.0.50.  Anyways, I have a screenshot.  In this case, it decided to display the files.  I had just clicked on 'game-of-life', and the cursor is now at the bottom of the tree and the entire tree is selected.
![screen shot 2015-11-11 at 7 12 42 pm](https://cloud.githubusercontent.com/assets/1843137/11109709/3f5fa968-88a8-11e5-8704-34b56496eab6.png)

**Comment by ysgard** [comment]
This is a different machine (but still the same version of OS X and emacs), I'll see about getting a screenshot of the missing folders on the other one.

**Comment by ysgard** [comment]
Here's a 'before' and 'after' shot demonstrating the issue.  The 'after' screenshot is the result of clicking on the folder 'Swarm'.
![screenshot 2015-11-12 07 56 03](https://cloud.githubusercontent.com/assets/1843137/11123123/1b14071e-8913-11e5-9880-57156f3352ed.png)
after:
![screenshot 2015-11-12 07 56 13](https://cloud.githubusercontent.com/assets/1843137/11123133/22880dba-8913-11e5-901e-4610923d7aca.png)

**Comment by cmnth** [comment]
Same here - Linux Mint 17.2 Cinnamon 64-bit [2.6.13, 3.16.0-38-generic], GNU Emacs 25.1.50.2

Opening folder - files not visible & chops the rest of folders below the currently opened one

![screenshot from 2015-11-25 13 43 37](https://cloud.githubusercontent.com/assets/11830160/11386986/ad8155cc-937a-11e5-949f-2568655ce959.png)

**Comment by cmnth** [comment]
placing the following setting to user-config resolved the issue for me:

    (defun dotspacemacs/user-config ()
      (setq neo-vc-integration nil)
       ...
    )

**Comment by StreakyCobra** [comment]
@ysgard Does this snippet also works for you?

**Comment by ysgard** [comment]
It does!  Thank you!  Without the snippet, I experience the problem everywhere, not just git repos, so unfortunately it looks like vc integration is flat-out broken on OS X.

But at least with the snippet, I can use Neotree again. :+1:

**Comment by StreakyCobra** [comment]
:+1: For your information this change has been merged on develop (#3903), so it will be in the next release.
