### ISSUE TITLE
spacemacs-layouts | previous layout key in micro-state

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#3745]
Mostly old habit of hitting `p` for previous. And since we do support `p` for previous, in almost all micro-states, where there's `n`, this is inconsistent in layouts micro-state. 

Since we navigate more than create layouts, I suggest we use `p` for previous layout and move projects opening layout  on `P`. 

What everyone thinks?

**Comment by d12frosted** [comment]
:+1: as emacs editing style user I totally support it

**Comment by syl20bnr** [comment]
I know that it won't be a popular choice but I would like to keep `p` for project as default because in spacemacs `SPC p` is project.

We an hybrid micro-state here which lies between conventional namespaces key bindings and a micro-state. The conventional key bindings has a higher priority.

If we want `p` back then we should have to put decouple the micro-state and `SPC l` namespace.

**Comment by StreakyCobra** [comment]
As a vim-editing-style user, I… also agree with this change, as I start getting used to `n/p` :smiley:

Sidenote, for me `SPC p l` will even have more sense that `SPC l P`. Just saying…

**Comment by StreakyCobra** [comment]
Thinking of it… As you want 4 basic concepts (`buffer`, `files`, `projects` and `layout`), the `layouts` concept is not that different from `buffers` or `files` (as now `spacemacs-layout` is part of spacemacs):

For accessing project-related elements:
- `SPC p f` is for project's files (and not `SPC f p`)
- `SPC p b` is for project's buffers (and not `SPC b p`)
- `SPC p l` would be for project's layout (freeing `SPC l p` :relaxed:).

For navigating elements:
- `SPC b p` and `SPC b n` go on previous/next buffers
- `SPC l p` and `SPC l n` would navigate on previous/next layouts

**Comment by joehillen** [comment]
:+1: for `SPC l P` as well

I was fine with that setting before the spacemacs-layout refactor and I had gotten used to `n` and `p` rather quickly. I think it would be fine to have both `p` and `N` bound to `persp-prev`.

**Comment by syl20bnr** [comment]
> `SPC p l` would be for project's layout (freeing `SPC l p` :relaxed:).

This is an acceptable solution, since the scheme is a new `SPC <scope> <scope>` I guess the order of the scope is not very important. And this sequence is free so let's go for this solution :-)

**Comment by syl20bnr** [comment]
Actually we have already `SPC <scope> <scope>` if we consider `f` and `b` as scope but the distinction is rather blurry. `SPC l p` is really mixing two scopes together so... sorry of my previous sentence was not clear, the important thing is that we can go for the `SPC p l` solution :-)

**Comment by syl20bnr** [comment]
I note this issue as a regression then since we lost `SPC l p`.

**Comment by syl20bnr** [comment]
Done in commit https://github.com/syl20bnr/spacemacs/commit/3ff39f1

**Comment by nixmaniack** [comment]
Thank you! :smile:
