### ISSUE TITLE
helm-locate-library - SPC h L - is broken

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#3747]
Everything up to date on develop.

Fire up `SPC h L` and type something in input. Following error is generated.

```
Helm issued errors: helm-match-from-candidates in source `Elisp libraries (Scan)': wrong-type-argument (stringp (zonokai-blue-theme.el . /Users/user/.emacs.d/elpa/zonokai-theme-20150408.2002/zonokai-blue-theme.el)) [2 times]
```
Invoke `helm-locate-library` in clean Emacs (`emacs -Q)` which works. You can use script provided in helm to start helm cleanly.
```
/Users/user/.emacs.d/elpa/helm-20151106.2158/emacs-helm.sh
```
And then `M-x helm-locate-library RET cl-lib` should work without any errors.

**Comment by TheBB** [comment]
Turns out this is due to `helm-fuzzier`. Not a Spacemacs bug. :-)
