### ISSUE TITLE
File error: Cannot open load file, subr-x - on Ubuntu 14.04 with emacs 24.3.1

### ISSUE THREAD

**Issue by mwbutcher** [syl20bnr/spacemacs#375]
On Ubuntu 14.04 with emacs 24.3.1

after installing with: 
git clone --recursive http://github.com/syl20bnr/spacemacs ~/.emacs.d

and running:
emacs --debug-init

I get: 
Debugger entered--Lisp error: (file-error "Cannot open load file" "subr-x")
  require(subr-x)
  eval-buffer(#<buffer  *load*-143089> nil "/home/username/.emacs.d/core/spacemacs-mode.el" nil t)  ; Readi$
  load-with-code-conversion("/home/username/.emacs.d/core/spacemacs-mode.el" "/home/username/.emacs.d/core/space$
  load("~/.emacs.d/core/spacemacs-mode.el")
  eval-buffer(#<buffer  *load*> nil "/home/username/.emacs.d/init.el" nil t)  ; Reading at buffer position $
  load-with-code-conversion("/home/username/.emacs.d/init.el" "/home/username/.emacs.d/init.el" t t)
  load("/home/username/.emacs.d/init" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\31$
  command-line()
  normal-top-level()

This issue seems to have been introduced with the inclusion of (require 'subr-x) in:
ba3bd53f54b9ec83cd13b3d21dc0e6f8260d63d1

**Comment by jynnantonix** [comment]
Looks like subr-x was added in emacs 24.4, which means that now spacemacs doesn't work for any older version of emacs.  Any chance you could maintain backward compatibility with older versions until 24.4 is more easily available on distros?  For example, the only way to get 24.4 on Ubuntu right now is to build it from source, which I'm not particularly inclined to do.

**Comment by syl20bnr** [comment]
My bad, I should have known it. Will post a hotfix soon.
