### ISSUE TITLE
2-columns and 3-columns windows layout should not change golden-ratio

### ISSUE THREAD

**Issue by StreakyCobra** [syl20bnr/spacemacs#3750]
Using `SPC w 2` and `SPC w 3` to change to 2 or 3 columns windows layout also changes the golden-ratio mode. As it's an user preference, it shouldn't be touched.

[These are the incriminated lines](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distribution/spacemacs-base/funcs.el#L384-L397):

```elisp
(defun spacemacs/layout-triple-columns ()
  " Set the layout to triple columns. "
  (interactive)
  (golden-ratio-mode 0)
  (delete-other-windows)
  (dotimes (i 2) (split-window-right))
  (balance-windows))

(defun spacemacs/layout-double-columns ()
  " Set the layout to double columns. "
  (interactive)
  (golden-ratio-mode 1)
  (delete-other-windows)
  (split-window-right))
```

**Comment by TheBB** [comment]
Fixed by #3751.
