### ISSUE TITLE
NeoTree key bindings (editing style: Emacs)

### ISSUE THREAD

**Issue by microamp** [syl20bnr/spacemacs#3752]
Hi. I use Spacemacs with Emacs key bindings (i.e. `dotspacemacs-editing-style` set to `emacs`) and when I'm in a NeoTree buffer, `n` is bound to `evil-search-next` and `p` is to `neotree-previous-line`. I think the former should have been `neotree-next-line` instead. In other words, it looks like some of the NeoTree key bindings don't obey the editing style the user has set.

**Comment by StreakyCobra** [comment]
`neotree` bindings are currently not really well handled. [They are defined](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+distribution/spacemacs/packages.el#L1598) in the hook of `neotree-mode`, independently of the user-defined mode. You can use `C-n` and `C-p` in the meantime.
