### ISSUE TITLE
Deleting user packages every initilizing

### ISSUE THREAD

**Issue by abaddon-E** [syl20bnr/spacemacs#3754]
why it must be do like this and delete every packages that I add to spacemacs form packages ?
I like use spacemacs but this is the worst I ever seen, make me sad and angry about this beautiful project.

**Comment by syl20bnr** [comment]
Are you installing packages by yourself or do you use the dotfile variables ?

- `dotspacemacs-configuration-layers` to install packages from a layer (you can search for them with `SPC f e h`)
- `dotspacemacs-additional-packages` for installing packages which are not part of any layer.

**Comment by TheBB** [comment]
Also set `dotspacemacs-delete-orphan-packages` to `nil` to turn this behaviour off.
