### ISSUE TITLE
rainbow-delimiters-mode not working in molokai

### ISSUE THREAD

**Issue by lunik1** [syl20bnr/spacemacs#3756]
Delimiters aren't showing as rainbow coloured on the molokai colourscheme, but this is fixed for the session if `SPC f e R` is performed. I'm getting this issue on the template `.spacemacs`.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.4
- Spacemacs branch: master (rev. f04bb61)
- Distribution: spacemacs
- Layers:

``` elisp
(emacs-lisp)
```

**Comment by StreakyCobra** [comment]
It's only not working in molokai, or does it happen with other themes?

**Comment by lunik1** [comment]
Just molokai

**Comment by StreakyCobra** [comment]
I can't reproduce it with my config, but I can with a fresh install. I'll look later, if I find some time.
