### ISSUE TITLE
spacemacs-layout | Internal *Messages* buffer only visible on 1st layout in helm-mini

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#3758]
I don't know if this is a feature or not, but I think we should make the internal emacs buffers accessible on all layouts with `helm-mini`.  I can access the buffer with `C-x c-b`, but would prefer using the same command everywhere.  I know I can also use `SPC wpm`, but would like an option to open it in the current window.

**Comment by nixmaniack** [comment]
I can't reproduce this. I can access `*Messages*` using `SPC b b` which is bound to `helm-mini`. Are you using `SPC p b`  by any chance which is projectile-buffers.

**Comment by ralesi** [comment]
@nixmaniack, can you access *Messages* from all layouts,  or just the first one?

**Comment by nixmaniack** [comment]
All layouts. I created with `SPC p l` for project specific layout and other one with just hitting a number in `SPC l <not_used_number>`.

I do have following variables set if it matters.
```elisp
dotspacemacs-display-default-layout t
dotspacemacs-default-layout-name "@Home"
dotspacemacs-auto-resume-layouts t
```

**Comment by nixmaniack** [comment]
Again, I'm assuming you're not using any scope based search and are using `SPC b b`.
If you use `SPC l b` it'll scope that to that particular layout.

**Comment by ralesi** [comment]
OK,  I havent scoped any variables yet,  so I will try that.

**Comment by ralesi** [comment]
Ok,  with setting the above settings,  I now see all buffers on all layouts in helm-mini.   I will look into how these settings change things,  but would say this is closed.
