### ISSUE TITLE
Spacemacs-layout can't reload a dired buffer

### ISSUE THREAD

**Issue by dsdshcym** [syl20bnr/spacemacs#3762]
When I use spacemacs-layout to load a saved-layout and this layout has a dired
buffer, this buffer displays nothing. And most annoyingly, it can't be killed
and shows the error below:

```
dired-current-directory: No subdir-alist in Org
```

'Org' is the directory name.

A workaround to kill this buffer is to switch to another mode and it can be killed then.

I don't know if this is a perp-mode issue or a dired issue. And here is my system info:

#### System Info
- OS: darwin
- Emacs: 25.0.50.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. fde6c60)
- Distribution: spacemacs

**Comment by synic** [comment]
It seems there's a few "types" of buffers/windows that do not get saved.  For instance, `magit-status`, `NEOTree`, etc.

**Comment by ralesi** [comment]
I confirm the issue, the workaround works as well, but I think it would be better if we let layouts know this before closing.

**Comment by dsdshcym** [comment]
@synic @ralesi 
I was thinking, maybe we can ignore these type of buffers. Since we usually don't need to restore these buffers which are not files.

But I don't know how to deal with the layout part.

**Comment by mahinshaw** [comment]
@dsdshcym I just tested this out, and could not reproduce the problem.  Are you still seeing the aformentioned behavior?

**Comment by dsdshcym** [comment]
@mahinshaw I can't reproduce either. I think it's fixed.

Closing this for now.
