### ISSUE TITLE
How to fix the failed tests, when SPC f e R

### ISSUE THREAD

**Issue by Cifer-Y** [syl20bnr/spacemacs#3765]
The error page is very nice, but I have no idea how to fix the failed test.
I checked some issues, but still confused, there are my errors:
![image](https://cloud.githubusercontent.com/assets/4470516/11097769/0c641268-88dc-11e5-9393-9f0d9331ffdb.png)

**Comment by Cifer-Y** [comment]
I moved the three package into a custom layer, and the test passed, but I don't know if that was a good solution.

**Comment by justbur** [comment]
It means you have `company-mode`, `editorconfig`, and `whitespace` in the `dotspacemacs-configuration-layers` variable, but none of these are layers that can be found. Certainly none are provided by spacemacs. A package is not a layer.

**Comment by Cifer-Y** [comment]
@justbur :scream: Yeah, you are right...Thanks for your comment, very clearly.
