### ISSUE TITLE
python-rope/ropemacs in python layer

### ISSUE THREAD

**Issue by basveeling** [syl20bnr/spacemacs#3767]
[Ropemacs](/python-rope/ropemacs) is an emacs mode that uses the rope library to provide features like python refactorings and code-assists. I've been playing around with it in my spacemacs build and it seems to be very powerful. Is this something that would be considered for the python layer? If so, I can work on a pull request.

**Comment by synic** [comment]
I'd like it.  Seems like a hard layer to add because of all the external python dependencies and stuff

**Comment by bmag** [comment]
+1 for adding rope support.
I'm curious, though, doesn't ropemacs require pymacs to be installed? Last time I tried it wasn't very easy to install pymacs (on Lubuntu), so I'd like to hear how you did it.

**Comment by synic** [comment]
Yeah, seems like even some of the official releases in rope don't work, and you have to use a developer version that's been abandoned for years.

**Comment by nixmaniack** [comment]
+1 for rope! 
I was using hacked way of using rope with spacemacs but never got time to integrate with spacemacs. I don't use it anymore but would help if anyone starts.

**Comment by TheBB** [comment]
My experience with rope echoes that of the others. It's tricky but powerful. We will certainly entertain the idea of it if someone opens a PR. If it's too experimental it can go in a separate layer instead of directly in the python layer (which we need to keep fairly stable).

**Comment by cpaulik** [comment]
I'm all for it and curious since I've never tried it.

**Comment by rueberger** [comment]
Any updates with this? This was the best feature in my old emacs-for-python build and I'm pining for it. I think there are some problems with python 3 support right now though, which is a shame

**Comment by d12frosted** [comment]
@rueberger looks like no one worked on adding rope support. PRs are welcome :) If you already have good configs for rope then you could migrate them to Spacemacs and share them :) 💃

**Comment by shitikanth** [comment]
I would recommend trying the [traad](https://github.com/abingham/emacs-traad) package as well. It works and is certainly much easier to setup than ropemacs.

**Comment by beyondpie** [comment]
I try Ropemacs, and it confuses me a lot.
Finally I try the traad package, it is installed easily and works really well.

**Comment by an0** [comment]
Whatever we use I just want refactoring in python layer.

**Comment by rueberger** [comment]
It looks like [rope itself](https://github.com/python-rope/rope) is being maintained again and has started to add python 3 support. ropemacs looks dead. 

Does anyone who keeps their ear to the ground of the python open source community know what the current status quo for refactoring tools is?

**Comment by ryanpeach** [comment]
Unfortunately it's still rope, beyond the much better refactoring that Jetbrains provides.

**Comment by beyondpie** [comment]
> I try Ropemacs, and it confuses me a lot.
> Finally I try the traad package, it is installed easily and works really well.
> 
> I add some func into python-layer together with anaconda-mode. I know this issue is old enough, but still hope someone will benefit from it.
> [beyondpie@81d3653](https://github.com/beyondpie/spacemacs/commit/81d3653bc7a74d84d33df7c9fd02dd60c69e3512)

Now I am using lsp (pyright), seems that it works much better than traad. It can refactor the codes well.
 @ryanpeach  have you tried the newest pyright lsp, and compare it with rope?
