### ISSUE TITLE
disable automatic anaconda response

### ISSUE THREAD

**Issue by lufeihaidao** [syl20bnr/spacemacs#3772]
I'm learning bottle, but when I try to edit file, it automatically send anaconda request and automatically jump to anaconda response. It is really annoying.How can I disable it?

![image](https://cloud.githubusercontent.com/assets/1731864/11118026/c4c82c02-8979-11e5-8331-e7e4b23d08c7.png)

![image](https://cloud.githubusercontent.com/assets/1731864/11136861/5e4596bc-89ed-11e5-8942-4f9d7b5da838.png)

> Why from different nginx...

**Comment by cpaulik** [comment]
What does the anaconda response say? Normally if anaconda fails it will only show a message in the minibuffer but not popup a window.

**Comment by lufeihaidao** [comment]
@cpaulik Something is strange here... When I came back from the cafe this problem disappeared... And the new problem is:

![image](https://cloud.githubusercontent.com/assets/1731864/11123414/82b02d1c-899a-11e5-8eaa-27d81c813f93.png)


Peerhaps it's the network problem...

**Comment by cpaulik** [comment]
Do you by any chance work behind a proxy? The eldoc error will spam your minibuffer but should not in any way interfere with the autocompletion.

**Comment by lufeihaidao** [comment]
@cpaulik Yeah, but it took no effect when I disabled my proxy. I found an issue https://github.com/proofit404/anaconda-mode/issues/124. 

My environment:
Mac, pyenv, brew installed python 2.7.10
![image](https://cloud.githubusercontent.com/assets/1731864/11137062/67b95100-89ef-11e5-98af-90e09026b7a7.png)

**Comment by cpaulik** [comment]
I've had problems in the past with my proxy, and had to set the `no_proxy` environment variable in emacs for `127.0.0.1` see [here](https://github.com/cpaulik/dotfiles/blob/master/.spacemacs.symlink#L239-L240) for reference.

Another thing that might be the problem is the python version. There were subtle issues with the homebrew python version before.

Since you are using pyenv, can you try 

```shell
pyenv install miniconda-3.16.0
```

and use this version in emacs?

**Comment by lufeihaidao** [comment]
@cpaulik Now I've set the 'no_proxy', and installed `miniconda-3.16.0`, but it still not work...

**Comment by cpaulik** [comment]
@lufeihaidao Then I'm out of ideas unfortunately.

**Comment by synic** [comment]
@lufeihaidao I had to install jedi and anaconda-mode with pip, outside of emacs.  anaconda-mode tries to install it automatically, but does it incorrectly.

**Comment by phinicota** [comment]
I have the same issue, tried everything posted here with no success. Is there a way to disable when the python layer is loaded? The popup really turns python-mode unusable.

**Comment by cpaulik** [comment]
@phinicota Are your packages up to date? I thought that this problem was fixed upstream. If it does not work you can put `anaconda-mode` into your `dotspacemacs-excluded-packages` list.

**Comment by phinicota** [comment]
I'm running ubuntu 12.04 on the develop branch.
Python version is 2.7.3
I'm gonna try disabling it now.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 4f07ff2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm
 (auto-completion :variables auto-completion-complete-with-key-sequence-delay 0.04)
 emacs-lisp c-c++ semantic spotify git
 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by phinicota** [comment]
So, I don't know how or why, but I enabled anaconda-mode again and I don't get any kind of issue on the develop branch (same setup).

**Comment by autosquid** [comment]
Same here, the error message appearing in a buffer is:

```
# status: (:error (error connection-failed failed with code 22
 :host 127.0.0.1 :service 62580))
# point: 1
```

**Comment by xarthurx** [comment]
Same issue as @autosquid

**Comment by sr105** [comment]
I get the same connection-failed message, but anaconda-mode works as soon as Emacs starts. It starts popping up the `*anaconda-response*` buffers after a period of time (undetermined).

**Comment by marcwebbie** [comment]
I fixed by disabling the anaconda response hooks

```elisp
(remove-hook 'anaconda-mode-response-read-fail-hook
                 'anaconda-mode-show-unreadable-response)
```

**Comment by LZGH** [comment]
"(remove-hook 'anaconda-mode-response-read-fail-hook 'anaconda-mode-show-unreadable-response)"  doesn't work for me. I sovle it by revise anaconda-mode.el source file,find "(add-hook 'anaconda-mode-response-read-fail-hook 'anaconda-mode-show-unreadable-response)" and remove it,then recompile anaconda-mode.el or delete anaconda-mode.elc directly,then it worked.
