### ISSUE TITLE
layouts - removing a layout doesn't actually remove it

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3775]
Using `SPC l c`, `SPC l C`, `SPC l x`, or `SPC l X` doesn't remove the layout from the file that gets saved if you have automatic save on.  So, if you remove a layout, and then restart emacs, the layout will be back.

**Comment by nixmaniack** [comment]
I can confirm this.

**Comment by synic** [comment]
Seems to be a bug in upstream `persp-kill`

**Comment by synic** [comment]
Ok, I have a workaround from upstream.  Put this in your `user-config`:

```elisp
(setq persp-auto-save-persps-to-their-file nil)
```

Not entirely sure what that setting does, but it does fix the problem, and persistent perspectives still work.

**Comment by synic** [comment]
This has been fixed upstream.
