### ISSUE TITLE
`C-c C-e` no longer works in helm-ag for editing results

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3778]
You used to be able to type `C-c C-e` in the helm-ag results to edit the results and save them.  `C-c C-e` is now unbound.

**Comment by cpaulik** [comment]
The keybinding is still in `helm-ag` see [here](https://github.com/syohex/emacs-helm-ag/blob/master/helm-ag.el#L676). Can you check your elpa directory?

**Comment by StreakyCobra** [comment]
I tried just now and `C-c C-e` is still working on my side. You can maybe give the steps you exactly did to help reproducing.

**Comment by CestDiego** [comment]
same here it still works...

**Comment by synic** [comment]
Yup, working for me.  Sigh.
