### ISSUE TITLE
Customize spacemacs for terminal usage.

### ISSUE THREAD

**Issue by amosbird** [syl20bnr/spacemacs#3780]
Is there any existing configuration that works appropriately in a ssh terminal?

**Comment by cpaulik** [comment]
What are your problems? I'm working in a ssh terminal in tmux every few days.

**Comment by amosbird** [comment]
Highlights get messed up. Lines repeatedly draw on the screen.

![k25nxfcsmy ug5mu xsc e4](https://cloud.githubusercontent.com/assets/5085485/11140935/0b6dd3d6-8a1b-11e5-9f73-6c0b5179c7d4.png)

**Comment by cpaulik** [comment]
Which theme are you using? Some themes do not define proper terminal colors.

The mutliple lines in the modeline might be related to your font not supporting the unicode symbols used there. Try setting `    dotspacemacs-mode-line-unicode-symbols nil` in your `.spacemacs` file. There should already be an entry for this variable.

**Comment by amosbird** [comment]
@cpaulik I didn't change theme settings. Which theme should I use?

**Comment by cpaulik** [comment]
`spacemacs-dark` should look sane. `material` and `material-light` also have terminal colors setup (I know because I develop them). See if one of those looks good in your terminal. Then you can look for one you like with `SPC T h`.

**Comment by amosbird** [comment]
I've tested `spacemacs-dark`,  `spacemacs-light`, ` `solarized-dark`, ` `solarized-light`, they all looked exactly the same to me. I'm using XShell on Windows.

**Comment by cpaulik** [comment]
They should definitely not look the same. I can try XShell when I get to work later. No Windows PC at home.

**Comment by StreakyCobra** [comment]
What the value of "$TERM" in the shell just before you run emacs?

**Comment by cpaulik** [comment]
I just tried with XShell. I connected to my linux machine using ssh and started emacs -> no colors. Doing `export TERM=xterm-256color` solved the color issue for me. For a font you could try installing one of the [powerline fonts](https://github.com/powerline/fonts/pull/18) for windows. But I have no idea about the windows support. The [hack][http://sourcefoundry.org/hack/) font should also include the necessary symbols.

**Comment by amosbird** [comment]
@cpaulik Which Xshell's theme do you use?

**Comment by amosbird** [comment]
I've set `dotspacemacs-mode-line-unicode-symbols nil` and `export TERM=xterm-256color`. Themes do look better. However there are still drawing issues, and pop-up window looks weird.
![daw9h6 1n 17 hf1 j tnh](https://cloud.githubusercontent.com/assets/5085485/11143418/e67927c8-8a2f-11e5-95a4-b3ddea159293.png)

**Comment by cpaulik** [comment]
@amosbird I don't use a special theme

**Comment by syl20bnr** [comment]
@amosbird what is your terminal emulator ? `urxvt` has this behavior on my side, the more I use urxvt the less I find it pleasant to use.

**Comment by amosbird** [comment]
@syl20bnr I'm using CentOS 6 via XShell on Windows. XShell's terminal is set to `xterm` with UTF-8 support.

**Comment by cpaulik** [comment]
@jrhorn424 I think this is just a issue with the solarized theme spacemacs uses. See also https://github.com/syl20bnr/spacemacs/issues/1269#issuecomment-147193789

**Comment by cpaulik** [comment]
See also https://github.com/bbatsov/solarized-emacs/issues/18

**Comment by jrhorn424** [comment]
Thanks @cpaulik. Looks like the information on this is a bit distributed. 😉

**Comment by VMatrix1900** [comment]
Same Problem when using Spacemacs on Bash On Ubuntu on Windows 10. Lines redraw. Even in spacemacs-dark theme. Any fixes?

**Comment by fruitraccoon** [comment]
I know this issue has been closed, but I see the same behaviour as @VMatrix1900 - the rending doesn't seem to work correctly in a Bash On Ubuntu On Windows 10 terminal.  But interestingly, running Spacemacs inside the terminal in VS Code _does_ work properly.  Go figure...

**Comment by VMatrix1900** [comment]
@fruitraccoon The terminal in VS Code is connected to Bash On Ubuntu On Windows 10?

**Comment by fruitraccoon** [comment]
@VMatrix1900 In VS Code, I just use the `Terminal: Select Default Shell` and I get to choose from Cmd, PowerShell, WSL Bash and Git Bash.  Selecting WSL Bash, I can then use `emacs` in the terminal and it seems to render correctly, and seems to support 256 colours.

I havn't tried the other terminal emulators you mention, but what I have just tried:
- Bash on Ubuntu on Windows: This doesn't render correctly - lines overwrite each other, etc.
- Cmd: running `bash -c emacs` seems to work!
- Powershell: running `base -c emacs` doesn't have the rendering issue, but unicode doesn't seem to be supported (haven't dug into why)

Hope this helps!

**Comment by VMatrix1900** [comment]
@fruitraccoon I tried Cmd and Powershell, it's not working for me. Besides the line rendering issue. Bash On Windows 10 doesn't support solarized theme. So I given up and wait for the stable release of Bash On Windows 10

**Comment by ZhangYue-vhyt** [comment]
Same problem on Ubuntu 18.04 WSL. 

![2019-02-09_06-59-57](https://user-images.githubusercontent.com/9450184/52520592-0333df80-2c39-11e9-8b56-14ce862b6d98.gif)

**Comment by sc0ttwad3** [comment]
I haven't had a problem running Spacemacs in Microsoft Terminal...WSL2/Ubuntu-18.04. Have you tried that?

![Spacemacs-WSL](https://user-images.githubusercontent.com/1682691/75002609-04464200-5433-11ea-8c1a-a51d19fb32f2.jpg)
