### ISSUE TITLE
Use shield.io design for the badge.

### ISSUE THREAD

**Issue by StreakyCobra** [syl20bnr/spacemacs#3786]
#3784 is showing our new badge in the center of other ones, like paypal or travis.

![2015-11-13-100226_3360x1050_scrot](https://cloud.githubusercontent.com/assets/1587877/11142474/d1a4fb34-89ed-11e5-8b04-35d5b6f603ec.png)

I don't like how it looks as it doesn't have the same style as the other (gitter also, but this is not our problem). As a lot of projects use badges in the shape defined by [shields.io](http://shields.io/), can we adapt our to use the same style?

I just played a little bit to show you wat it can looks like (it's just hacky, someone (me if needed) have to do it properly):

![build-spacemacs](https://cloud.githubusercontent.com/assets/1587877/11142516/1a54f712-89ee-11e5-951a-2107ff886e5f.png)

**Comment by nashamri** [comment]
This one looks much better than the one I did :+1: time to update the badge :smile:

**Comment by robbyoconnor** [comment]
I did it in the center so it's not obtrusive :)

**Comment by robbyoconnor** [comment]
What's awesome is no need to change anything :D

**Comment by nashamri** [comment]
Yeah :smile: this allows us to do special badges for special occasions :+1: think like google doodle.

**Comment by robbyoconnor** [comment]
Yessssss....please!!!

--Rob

**Comment by gregpardo** [comment]
Built vs Build?

**Comment by nashamri** [comment]
The actual badge says "built" https://github.com/syl20bnr/spacemacs/issues/3793

**Comment by StreakyCobra** [comment]
Yeah, built, of course :sweat_smile:

**Comment by nashamri** [comment]
@robbyoconnor unfortunately rawgit (the service that I used to serve the badge asset) doesn't link directly to the asset, they cache it and serve the cached version forever, unless I do something like this #3807
