### ISSUE TITLE
Broken init-post-extension (commit 7a2e604)

### ISSUE THREAD

**Issue by boykov** [syl20bnr/spacemacs#3788]
I use simple private layer `eab-spacemacs`: extensions.el and packages.el, see attachment. The main feature of this example is that post extension `eab-dotemacs/lisp` calls `(require 'workgroups2)` (i.e. some package, which is in `eab-spacemacs-packages`).

 syl20bnr/spacemacs@7a2e604 breaks normal behavior, it produces error:
 require(workgroups2) => "cannot open load file" ...  workgroups2.

There is no path for workgroups2 package in `load-path`.
 It is interesting that for some packages (`docker`, `achievements`, ...) there is no error, but for packages `workgroups2`, `moz`,... it appears. 
extensions.el:

```emacs-lisp
(defvar eab-spacemacs-pre-extensions
  '(
    )
  "List of all extensions to load before the packages.")

(defvar eab-spacemacs-post-extensions
  '(
    eab-dotemacs/lisp
    ;; post extension eabs go here
    )
  "List of all extensions to load after the packages.")

(defun eab-spacemacs/init-eab-dotemacs/lisp ()
  (require 'workgroups2)
  )

```

packages.el:

```emacs-lisp
(defvar eab-spacemacs-packages
  '(
    workgroups2
  )
  "List of all packages to install and/or initialize. Built-in packages
which require an initialization must be listed explicitly in the list.")

(defvar eab-spacemacs-excluded-packages '()
  "List of packages to exclude.")


(defun eab-spacemacs/init-workgroups2 ())

```

[extensions.txt](https://github.com/syl20bnr/spacemacs/files/33767/extensions.txt)
[packages.txt](https://github.com/syl20bnr/spacemacs/files/33768/packages.txt)

**Comment by syl20bnr** [comment]
This is because packages are loading in alphabetical order so you have to `with-eval-after-load` your require.
Though the above will work, this case smells something wrong somewhere.

**Comment by boykov** [comment]
No,

```emacs-lisp
(with-eval-after-load
  (require 'workgroups2))
```
does not help. The problem is exactly in the commit, because before it everything was fine (I used git-bisect to detect it). The bug exists not only for this particular package, but also for many others: `load-path` does not contain necessary paths at all.

**Comment by StreakyCobra** [comment]
@boykov If your question is answered, then you can mark it as closed :relaxed: Otherwise let us know how we can help you more!

**Comment by boykov** [comment]
None the less I think there is something wrong with post extension initialization (it should be after the loading packages, but it breaks normal loading order), because before the commit syl20bnr/spacemacs@7a2e604 everything was fine (I used git-bisect to detect it). It is very common way to use `require` in extensions, I do not understand why I should use `with-eval-after-load`. The problem still exists and not only for this particular package `workgroups2`, but for many others (`moz`, etc).

**Comment by StreakyCobra** [comment]
Ok, so it's a core question/discussion, I'll let @syl20bnr handle this :-)

**Comment by TheBB** [comment]
Well, as the commit message says, we removed the post step. Now there's just pre and normal. So it's not surprising that code that relied on being in post would break.

Whether it should be brought back is another matter, but just to be clear: there's nothing *wrong* per se, this was intended.

**Comment by boykov** [comment]
Oh, I understood, thank you.
