### ISSUE TITLE
Emacs for mac

### ISSUE THREAD

**Issue by zeka0** [syl20bnr/spacemacs#3789]
Hello there? I have trouble installing the space emacs on mac using the GUI version of emacs downloaded from http://emacsformacosx.com. I have followed the steps using home-brew to install OS-X prerequisites and I have git-cloned the space-emacs to .emacs.d but when I launched the emacs.app nothing happened, so was the same when I relaunched it or using terminal to launch original emacs on OS-X(the older version). Can someone help?

**Comment by d12frosted** [comment]
First of all, don't mess `emacsformacosx` and emacs installed from brew. You need only one version.

After you install emacs via brew, call

```
$ brew linkapps emacs
```

or 

```
$ brew linkapps emacs-mac
```

As for your problem with launching Emacs.app - try to launch it via

```
$ open /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.13/Emacs.app
```

Just don't forget to make `emacs-mac/emacs-24.5-z-mac-5.13` part relevant for your installation.

**Comment by zeka0** [comment]
I have downloaded emacs via brew linked it, and erased the emacsformacosx(I find that if you don't erase it, the command ($ open /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.13/Emacs.app) won't work ). Using the 'open app' command to start the emacs, nothing happened again... I still can't see space-emacs effects... May be I should add the 'load-path' sentence to my .emacs file?

**Comment by d12frosted** [comment]
Ah I see. Remove `~/.emacs` file since it prevents Emacs from loading `~/.emacs.d/init.el`.

**Comment by StreakyCobra** [comment]
This should probably be FAQ'ed.

**Comment by d12frosted** [comment]
It's already [here](https://github.com/syl20bnr/spacemacs/tree/develop#install).

**Comment by StreakyCobra** [comment]
Ok, it would be nice to make a not there saying that `Spacemacs` will not start if there is an `.emacs` file present.

**Comment by zeka0** [comment]
It works!(Though I have to use the vpn to connect to melpha because the country I am in can only connect to stable-melpha...).
Actually I have got another trouble... After the space-emacs asked me to enter what is your favorite style I entered vi (Sorry I have completed no idea why it will ask me this...) and it then asked which distribution I prefer and I saw 'space-emacs recommended' and so I entered spaceemacs and then it jams...A warning is thrown saying that 'eieio-orf (nil: variables)'.  I wondered if it's because I didn't put the line '(setq-default dotspacemacs-configuration-layers '(osx))' since I have removed '.emacs'....

**Comment by StreakyCobra** [comment]
If you remove the `~/.spacemacs` file and restart, you can choose options again. Just use the default, should be fine if you want `vim` bindings :-)

**Comment by TheBB** [comment]
For the record, it's spacemacs, not space-emacs.

Sorry, it was bugging me.

**Comment by zeka0** [comment]
Thanks for your patience!
I have started spacemacs oh yeah! But I suddenly find that the .spacemacs file is empty, so I intend to add my original .emacs file contents into .spacemacs trying to add auto-complete, jdee, yasnippet plugins  , and when I restart spacemacs it says it has trouble with .spacemacs and it tries to re-intsall itself (because spacemacs asked me to re-input the preferred mode)...I wondered what is the functionality of the .spacemacs file...(is it called 'dotfile' in the documentation?)

**Comment by StreakyCobra** [comment]
Come on gitter to ask question like this, there will be more people to explain you how it works.
