### ISSUE TITLE
evil folding stopped working on C/C++ modes

### ISSUE THREAD

**Issue by quartz55** [syl20bnr/spacemacs#379]
After the 0.41 release (if I'm not mistaken) code folding in C and C++ modes stopped working, I get a message saying "Folding is not supported in any of these major/minor modes".

Apologies in advance if I missed something in the docs update :)

**Comment by syl20bnr** [comment]
mmmmhhhh that's really strange, I can't see what would trigger this. Do you have any other error reported in the message buffer ? Do you have some special configuration for folding or is this just plain evil fold feature ?

**Comment by chrisbarrett** [comment]
At some point I noticed hideshow was turned off by default for me, and I had to add hs-minor-mode to a few hooks. Might be a change upstream in evil?

**Comment by quartz55** [comment]
@syl20bnr Nope, that's the only message I get and I have the default config for folding.
Tho, as @chrisbarrett said, enabling hs-minor-mode worked :+1:
