### ISSUE TITLE
TOCs in org files no longer work when rendered by GitHub on the develop branch

### ISSUE THREAD

**Issue by mineo** [syl20bnr/spacemacs#3797]
https://github.com/syl20bnr/spacemacs/blob/bfd360440f0abb18ed47f123870d986deb2ad961/doc/CONTRIBUTE.org has links that work
https://github.com/syl20bnr/spacemacs/blob/13c5b1d24b7dab52d78aa236786cc6d4f3724d0a/doc/CONTRIBUTE.org has links that don't work

There are no commits to that file between 13c5b1d24b7dab52d78aa236786cc6d4f3724d0a and bfd360440f0abb18ed47f123870d986deb2ad961, so I guess 13c5b1d24b7dab52d78aa236786cc6d4f3724d0a broke it. AFAICT this affects the README files of all layers as well.

**Comment by TheBB** [comment]
Yes, this is intended. We're phasing out github as the officially recommended way to view documentation online. It will be taken over by the spacemacs.org website (see #3604). Preview: http://boyanangelov.com/spacemacs/

**Comment by mineo** [comment]
Ok, good to know :-) I don't want to spam #3604, so I'll just say it here: that website looks awesome :sparkles:
