### ISSUE TITLE
request: Log package updates and deletions

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#3798]
I would like to have a persistent log showing the dates that each package is updated and what the change in version is. At the moment it's not that easy to even figure out which packages get updated with "Update Packages" because all the information flies by in the spacemacs buffer and it's not easy to see in the messages buffer. Of course it doesn't have to grow indefinitely. I just want to be able to see what the recent changes were in packages.

**Comment by syl20bnr** [comment]
I'm all for it, an `update.log` will be useful both for users and for support.

**Comment by justbur** [comment]
closing in favor of #5200
