### ISSUE TITLE
NeoTree does not open file in last visited window

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3804]
If you have a setup like this:

```
NeoTree Window |   Middle Window   |  Right Window
```

And you want to open a file in "Right Window" - and your cursor is in "Right Window", you can click on a file in NeoTree and it will open it in the correct window.

However, if you do a key combination like `2 SPC w h` to get into the NeoTree window, and then you press enter on a file, it will NOT open in the last window you visited, it will most likely pick "Middle Window".

This is not the same behavior as `NERDTree`, and it makes it so you can't target a specific window for opening the file unless you use the mouse.

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.0
- Spacemacs branch: fix/3774-fix_layout_switch_by_pos (rev. 9c51c98)
- Distribution: spacemacs
- Layers:
```elisp
(unscroll auto-completion xkcd emacs-lisp git gtags dash yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors spacemacs-layouts vimscript
          (c-c++ :variables c-c++-enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by bmag** [comment]
@synic IIUC pressing `2 SPC w h` does `SPC w h` twice, so first it moves one window to the left, then another window. From NeoTree's point of view, it sees that the middle window is the most recent window, because technically it really is the most recent window. Pressing `SPC 0` should bring you directly to NeoTree's window (using the `window-numbering` package), so the right window will really be the most recent window and NeoTree will open the buffer in the correct window.

**Comment by TheBB** [comment]
Also, you can choose which window to open in with prefix arguments: `SPC u 4 RET` will open in window 4.

**Comment by TheBB** [comment]
Also I did this: https://github.com/jaypei/emacs-neotree/pull/138. Maybe that will be good?

**Comment by synic** [comment]
@bmag: But, you understand that, as I said, this is not how vim+nerdtree works.  

@theBB: Either one of those works for me!

**Comment by TheBB** [comment]
The neotree PR was merged by the way.

**Comment by jsmestad** [comment]
@TheBB it seems this issue is back if your using develop branch. I see the PR you made, but am I doing something dumb here?

**Comment by absrd** [comment]
I'm also seeing this issue in the develop branch.
