### ISSUE TITLE
Problems with spacemacs

### ISSUE THREAD

**Issue by zeka0** [syl20bnr/spacemacs#3805]
I want to find a way to toggle line-number in initialization to avoid using Spc+t+n...(I am quit lazy)

**Comment by zeka0** [comment]
Plus, I am looking for a mechanism to add bookmarks of files or directories, just like the functionality provided by NERDTree in vim, may be Cedet could do that job... I still have many things to learn in emacs.

**Comment by robbyoconnor** [comment]
Have you looked at the auto-completion layer?

**Comment by zeka0** [comment]
I just have added this to my .spacemacs file:
(defun dotspacemacs/user-init ()
    (setq-default dotspacemacs-configuration-layers '(auto-completion))
    (setq-default dotspacemacs-configuration-layers '(
  (auto-completion :variables
                   auto-completion-return-key-behavior 'complete
                   auto-completion-tab-key-behavior 'cycle
                   auto-completion-complete-with-key-sequence nil
                   auto-completion-private-snippets-directory nil)
                   ))
    (setq-default dotspacemacs-configuration-layers
              '((auto-completion :variables
                                 auto-completion-enable-snippets-in-popup t))
    (global-company-mode)
)
And then spacemacs jams throwing a warning about the .spacmacs file and start to re-configure itself...

**Comment by zeka0** [comment]
I get another trouble now... After I have installed magit according to spacemacs-doc, the key-binding spc+g is undefined...

**Comment by bmag** [comment]
> I am looking for a mechanism to add bookmarks

Emacs has a built-in bookmarks mechanism. <kbd>SPC h b</kbd> provides a Helm interface for setting and jumping to bookmarks.
Also, in your dotfile (`.spacemacs` or `.spacemacs.d/init.el`) there's this line:
```elisp
dotspacemacs-startup-lists '(recents projects)
```
If you change it to:
```elisp
dotspacemacs-startup-lists '(recents projects bookmarks)
```
then you will see the bookmarks in the home buffer as well.

> I just have added this to my .spacemacs file:
```elisp
(defun dotspacemacs/user-init ()
(setq-default dotspacemacs-configuration-layers '(auto-completion))
(setq-default dotspacemacs-configuration-layers '(
(auto-completion :variables
auto-completion-return-key-behavior 'complete
auto-completion-tab-key-behavior 'cycle
auto-completion-complete-with-key-sequence nil
auto-completion-private-snippets-directory nil)
))
(setq-default dotspacemacs-configuration-layers
'((auto-completion :variables
auto-completion-enable-snippets-in-popup t))
(global-company-mode)
)
```

That's not the correct way to do it. The layer docs are a bit confusing about this point. When the installation instructions say `(setq-default dotspacemacs-configuration-layers '(auto-completion))`, they actually mean "add `auto-completion` to the list `dotspacemacs-configuration-layers`".
You need only *one* `(setq-default dotspacemacs-configuration-layers <...>)` in your dotfile. In your case, I think you want this:
```elisp
(setq-default dotspacemacs-configuration-layers
              '((auto-completion :variables
                                 auto-completion-return-key-behavior 'complete
                                 auto-completion-tab-key-behavior 'cycle
                                 auto-completion-complete-with-key-sequence nil
                                 auto-completion-private-snippets-directory nil
                                 auto-completion-enable-snippets-in-popup t)
                ))
```
And you don't need `(global-company-mode)`, the `auto-completion` layer already takes care of enabling company-mode.

Now if you want to add the `git` layer, you need to add it to `dostpacemacs-configuration-layers`. The simple way is to change the previous snippet like this:
```elisp
(setq-default dotspacemacs-configuration-layers
              '((auto-completion :variables
                                 auto-completion-return-key-behavior 'complete
                                 auto-completion-tab-key-behavior 'cycle
                                 auto-completion-complete-with-key-sequence nil
                                 auto-completion-private-snippets-directory nil
                                 auto-completion-enable-snippets-in-popup t)
                git
                ))
```
If you want to configure some of the `git` layer variables, it should be done like this:
```elisp
(setq-default dotspacemacs-configuration-layers
              '((auto-completion :variables
                                 auto-completion-return-key-behavior 'complete
                                 auto-completion-tab-key-behavior 'cycle
                                 auto-completion-complete-with-key-sequence nil
                                 auto-completion-private-snippets-directory nil
                                 auto-completion-enable-snippets-in-popup t)
                (git :variables
                     git-magit-status-fullscreen t)
                ))
```
You may want to look at `QUICK_START.org`, in the `Dotfile` section.

> I want to find a way to toggle line-number in initialization

In develop branch, you need to set the `dotspacemacs-line-numbers` variable. If you're on master branch, it's a bit more complicated, in your dotfile, in the `dostspacemacs/user-config` function, you need to add these two lines:
```elisp
(add-hook 'prog-mode-hook 'linum-mode)
(add-hook 'text-mode-hook 'linum-mode)
```

**Comment by zeka0** [comment]
Thanks for your patience!
I changed my .spacemacs to contain this:
 ;AUTO-COMPLETE LAYER
    (setq-default dotspacemacs-configuration-layers
              '((auto-completion :variables
                                 auto-completion-return-key-behavior 'complete
                                 auto-completion-tab-key-behavior 'cycle
                                 auto-completion-complete-with-key-sequence nil
                                 auto-completion-private-snippets-directory nil
                                 auto-completion-enable-snippets-in-popup t
                                 auto-completion-config-default
                                 auto-completion-auto-start 2
                                 auto-completion-menu-height 12
                                 auto-completion-auto-show-menu 0.8
                                 auto-completion-use-menu-map t)
                ))
Because what I originally added in my .spacemacs file is:
    ;AUTO-COMPLETE
    (add-to-list 'load-path "~/.emacs.bak/plugins/auto-complete")
    (require 'auto-complete-config)
    (add-to-list 'ac-dictionary-directories "~/.emacs.bak/plugins/auto-complete/ac-dict")
    (ac-config-default)
    (setq ac-use-quick-help t)
    (setq ac-auto-start 2)
    (global-set-key "\M-/" 'auto-complete)
    ;; Show menu 0.8 second later
    (setq ac-auto-show-menu 0.8)
    (setq ac-use-menu-map t)
    (define-key ac-menu-map "\C-n" 'ac-next)
    (define-key ac-menu-map "\C-p" 'ac-previous)
    (setq ac-menu-height 12)
My original config in .spacemacs has the effect that when you type two letters, emacs automatically shades the possible completion or it shows a popup menu containing all the possible completion. After I have changed my .spacemacs to the layer-style one I can only complete it using M-/ key bindings...
I wonder why this could happen...
PS. Best wishes for Paris.

**Comment by TheBB** [comment]
>     auto-completion-config-default
    auto-completion-auto-start 2
    auto-completion-menu-height 12
    auto-completion-auto-show-menu 0.8
    auto-completion-use-menu-map t

We don't have any variables by these names. Please note that Spacemacs uses **company** to provide auto-completion, not **auto-complete**. It seems you have been using the latter until now and are trying to configure company the same way.

You should remove the above and if necessary find the corresponding company configuration options if you want to have these effects (whatever they are).

**Comment by zeka0** [comment]
Oh, that explains a lot...The problem is solved.
