### ISSUE TITLE
Fringe markers for diff-hl-mode don't scale with frame

### ISSUE THREAD

**Issue by kecman** [syl20bnr/spacemacs#3806]
Here's a screenshot at my default zoom (`SPC z f =`):

![before](https://cloud.githubusercontent.com/assets/1313794/11162918/9dc2bd92-8ab0-11e5-8b5d-3d63e54c3ea4.png)

Here's a screenshot after I zoom frame 3 times (`SPC z f + + +`):

![after](https://cloud.githubusercontent.com/assets/1313794/11162920/a3126a90-8ab0-11e5-88cd-3650c5bdc529.png)

I'm using color theme `cyberpunk` but the issue exists with other themes too

**Comment by TheBB** [comment]
Maybe related to #1647.
