### ISSUE TITLE
emacs file-name

### ISSUE THREAD

**Issue by kvaneesh** [syl20bnr/spacemacs#3808]
This doesn't result in us showing file-name buffer. Instead we always default to spacemacs buffer.

**Comment by TheBB** [comment]
If anyone else have difficulty understand (like myself), he is saying that giving a filename as an argument to `emacs` on the command line opens the file, but doesn't show it.

Probably related to #3233.

**Comment by kvaneesh** [comment]
That is correct. Thanks for explaining it better.

**Comment by fleimgruber** [comment]
I can confirm that this is fixed at least in current develop.
