### ISSUE TITLE
magit-blame and micro-state key display

### ISSUE THREAD

**Issue by kvaneesh** [syl20bnr/spacemacs#3809]
blame a buffer using magit-blame, we show in mini-buffer micro state key binding. Press Enter to show commit information of any of the blame region. Now 'q' key binding is confusing. First 'q' press remove the micro state information, next one kill the commit buffer and the third cause magit-blame-quit. 

I guess we have some bugs w.r.t to micro state key handling ?

-aneesh

**Comment by kvaneesh** [comment]
magit-blame is mostly used in multi-buffer scenarios. That is after blaming a buffer, we mostly end up looking at commit details using <RET> key. That doesn't work nicely with micro-state. For example if i want to search the commit buffer using helm-swoop and want to type key 'b'; that doesn't work at all. May be we should disable micro-state for magit-blame until we get it working.

**Comment by strout** [comment]
I frequently get a leftover blame mini-buffer after I've already quit the mode. Related to this? Should I open a separate issue for that?

**Comment by StreakyCobra** [comment]
@strout Can you test this on `develop` first? It may be already fixed. If it doesn't work there please open a new issue following [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report).

**Comment by tarsius** [comment]
@kvaneesh @strout: Is this still an issue with https://github.com/justbur/evil-magit? In that case you should bring it up there, I think.

**Comment by d12frosted** [comment]
@kvaneesh and @strout, ping-ping 😸 what is the status of this issue?

**Comment by kvaneesh** [comment]
I don't hit this issue any more. this can be closed.
