### ISSUE TITLE
error: The directory `~/.emacs.d/server' is unsafe

### ISSUE THREAD

**Issue by justinmk** [syl20bnr/spacemacs#381]
On a fresh install of spacemacs, emacs `GNU Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2014-10-08 on G75VW` reports:

```
Warning (initialization): An error occurred while loading `c:/Users/jkeyes/.emacs.d/init.el':

error: The directory `~/.emacs.d/server' is unsafe

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

**Comment by justinmk** [comment]
Thanks!

**Comment by davidpgil** [comment]
I am using your configuration from my work computer which I don't have admin rights. Is there a way to stop this message from popping up?

**Comment by fd-Joker** [comment]
> Thank you for reporting this, I'll add this issue to the FAQ.
> The fix is here: http://stackoverflow.com/questions/885793/emacs-error-when-calling-server-start
> 
> > Click R-mouse on ~/.emacs.d/server and select “Properties” (last item in menu). From Properties select the Tab “Security” and then select the button “Advanced”. Then select the Tab “Owner” and change the owner from “Administrators (\Administrators)” into “ (\”. Now the server code will accept this directory as secure because you are the owner.

quite useful! thanks a lot!
