### ISSUE TITLE
in python-mode, running `evil-open-fold` on an already-open fold breaks `evil-close-fold`

### ISSUE THREAD

**Issue by ipsod** [syl20bnr/spacemacs#3810]
Pressing `zo` (runs `evil-open-fold`) on an already-open fold locks it into a fold state.
Pressing `zc` (runs `evil-close-fold`) will not close the fold.
Pressing `zm` will close the fold.

To reproduce, find something foldable in a python file, open it with `zo`, hit `zo` again, and then try to close it with `zc`.

**Comment by TheBB** [comment]
I don't have a binding for `zv`?

**Comment by ipsod** [comment]
Oh, oops.

I've got `zv` bound to `evil-open-fold`, same as `zo`.

**Comment by StreakyCobra** [comment]
I reproduced it in python-mode.

**Comment by ipsod** [comment]
This seems to be fixed in the latest version.  Can anyone else confirm?

**Comment by StreakyCobra** [comment]
I can't reproduce it anymore too :+1: Closing it then :-)
