### ISSUE TITLE
Spacemacs hanging when entering commands with SPC

### ISSUE THREAD

**Issue by michaelbeaumont** [syl20bnr/spacemacs#3813]
Hi,

Around every 10-20 times I use a command with the leader key, most often switch buffer but also SPC m C, at least with the latex layer, spacemacs hangs. Sometimes I can get it to respond by simply minimizing and reopening emacs, othertimes I just wait a minute or two, but sometimes I have to kill the server and restart it.
How can I get more information about what's causing it?

**Comment by StreakyCobra** [comment]
You can provide the output of `SPC h d s`, it may already give some indications. Then are you noticing this in all modes, or only some specific ones?

**Comment by michaelbeaumont** [comment]
I notice it at least in HTML mode, Jade mode, Haskell mode and LaTeX mode. There aren't any others I use very much at the moment.

I've been having to `killall -9 emacs` lately to get rid of the hung instances.

Doesn't look like there's anything useful in `SPC h d s`:

```
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 7dd57eb)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion emacs-lisp extra-langs
                 (haskell :variables haskell-enable-ghc-mod-support t)
                 liquid-types c-c++ ocaml python html jade css ipython-notebook rust git markdown latex lua org shell spell-checking
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 version-control)
```

**Comment by ridget** [comment]
:+1: Also noticing this with ruby/rails projects, heres my output from `SPC h d s`:

Lots of hangs today, either from `SPC p f` or even `SPC p b` when I haven't had a lot of buffers open either.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp markdown syntax-checking erlang elixir github git dash osx html org colors ruby ruby-on-rails javascript themes-megapack erc spotify
                 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh"))
```

**Comment by mclearc** [comment]
I'm experiencing a similar problem.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.13
- Spacemacs branch: my-develop (rev. f5f2e62)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion better-defaults deft emacs-lisp
                (geolocation :variables geolocation-enable-osx-location-service-support t geolocation-enable-weather-forecast t geolocation-enable-automatic-theme-changer nil)
                html
                (git :variables git-gutter-use-fringe t)
                latex markdown org osx pandoc pdf-tools
                (ranger :variables ranger-override-dired t ranger-show-preview t ranger-cleanup-eagerly t ranger-show-dotfiles t ranger-ignored-extensions
                        '("mkv" "iso" "mp4")
                        ranger-dont-show-binary t ranger-max-preview-size 20)
                (shell :variables shell-default-term-shell "/usr/local/bin/zsh" shell-default-height 30 shell-default-shell 'ansi-term shell-default-position 'bottom)
                shell-scripts spacemacs-layouts
                (spell-checking :variables spell-checking-enable-by-default nil)
                syntax-checking version-control yaml helm-bibtex outshine sr-speedbar)
```

**Comment by ridget** [comment]
seem to be able to reproduce this on a regular basis this morning. 

Open a large-ish file @ 365 lines
Open a new vertical split
hit SPC p f
hang

Let me know if theres anything more I can do to help.

**Comment by syl20bnr** [comment]
@ridget which type of file ? a ruby file ?

Can you open it with `SPC f l` and do the repro steps ? `SpC f l` should open the file without any mode activated.

**Comment by ridget** [comment]
@syl20bnr Tried reproducing a number of times this morning. Frustratingly with and without opening the file with `SPC f l` haven't been able to recreate a hang.

**Comment by ridget** [comment]
@syl20bnr id hazard a guess that this revolves more around helm than anything else, given I've had a couple of hangs this morning with magit mode and its helm integration, ill check out the issues there.

**Comment by ridget** [comment]
yep third time in a row when trying to do a magit checkout the helm autocompletion has caused spacemacs to hang.

**Comment by syl20bnr** [comment]
@ridget Interesting, so when it happens one time it seems to be reproducible easily. I suppose your elpa packages are up to date ? Is pressing `C-g` help to unblock Emacs ?

**Comment by ridget** [comment]
@syl20bnr will double check the packages, `C-g` definitely helps, thanks!

**Comment by yilihong** [comment]
any updates? I am still getting these errors after the updates. very annoying.
