### ISSUE TITLE
better-defaults - is it working?

### ISSUE THREAD

**Issue by xelibrion** [syl20bnr/spacemacs#3814]
Hey guys,

I have a question about `better-defaults` layer - isn't it supposed to override `C-w` and `C-a`?
https://github.com/syl20bnr/spacemacs/blob/master/layers/better-defaults/keybindings.el

I have it enabled, but for some reason `C-w` is still bound to window management functions. I'm on Mac running spacemacs in a terminal if it makes any difference.

**Comment by nixmaniack** [comment]
It does work but it might the case that keybindings are shadowed by window management layer(eyebrowse specially). For me it's working and eyebrowse is on `C-c C-w`. What does `SPC h d k` `C-w` show you?

**Comment by xelibrion** [comment]
Okay, it seems to work, except for one part - `C-w` is still bound to evil commands in vim insert mode. Is this by design?

Vim mode:
```
C-w runs the command evil-delete-backward-word, which is an interactive compiled
Lisp function in `evil-commands.el'.

It is bound to C-w.

(evil-delete-backward-word)

Delete previous word.
```
Emacs mode:
```
C-w runs the command spacemacs/backward-kill-word-or-region, which is an
interactive Lisp function in `funcs.el'.

It is bound to C-w.

(spacemacs/backward-kill-word-or-region &optional ARG)

Calls `kill-region' when a region is active and
`backward-kill-word' otherwise. ARG is passed to
`backward-kill-word' if no region is active.
```

**Comment by nixmaniack** [comment]
In general we keep Vim Editing style as close as possible to the stock Vim. So in vim insert state, C-w will behave same as it behaves in stock Vim, bindings for which are provided by `evil`, so those are not overridden. 

But giving this a second thought, if the user includes `better-defaults` layer, should we modify Vim state defaults is another question to look at.

**Comment by TheBB** [comment]
> Okay, it seems to work, except for one part - C-w is still bound to evil commands in vim insert mode.

The better defaults layer is for Emacs editing style users, not Vim style users. As the readme says, it doesn't change anything for the latter group.

**Comment by xelibrion** [comment]
That's fair enough, I think just got confused by `global-set-key` which is not exactly global.

**Comment by StreakyCobra** [comment]
@xelibrion If all your questions have been answered, you can probably mark this issue as closed. Otherwise, let us know how we can help you more :relaxed:

**Comment by xelibrion** [comment]
Sure thing! Thanks for your help guys!
