### ISSUE TITLE
Use-package in Spacemacs

### ISSUE THREAD

**Issue by zeka0** [syl20bnr/spacemacs#3817]
Sorry for bothering you guys again...
I want to add cedet configuration into my spacemacs as this:
 ;;PACKAGE-LOAD
 (use-package cedet 
  :defer t
  :init
  (global-ede-mode 1)                      ; Enable the Project management system
  :config
  (semantic-load-enable-code-helpers)      ; Enable prototype help and smart completion 
  )
I have read about the vimmer-doc but I can't find instructions of where to put it. So I looked the use-package github and find it say to add it into your dot file. And then I tried and got several errors(I tried to put it in user-init function or in dotspacemacs/layers function). Can any one help?

**Comment by TheBB** [comment]
Put it in the user-config function.

Also forget about `:defer t`. If you are loading it in `:init` then there's no point.

Remember to add cedet as an additional package if you want this.

**Comment by zeka0** [comment]
It seems that the cedet bundled with emacs is outdated, and it seems that adding 'cedet ede' to the  dotspacemacs-additional-packages list can't help...Is there a way to use spacemacs to install the latest version of cedet?

**Comment by TheBB** [comment]
Well, is it available in a package repository on a source code repository somewhere?

**Comment by zeka0** [comment]
I used 'locate' command to search the cedet but only find it inside the original emacs directories, so it's originally born. Ps I have added cedet to dotspacemacs-additional-packages, spacemacs didn't download and install it, it seems spacemacs just used the outdated-cedet.

**Comment by TheBB** [comment]
Well, I don't know how CEDET distributes its software. If it's not in a package repository and not in an easily accessible source code repository, maybe you just have to download it and set it up manually?

**Comment by zeka0** [comment]
Yeah, I will try it. Anyway, is that possible to add that manually-downloaded version of cedet to the .emacs.d directory for the sake of consistency?

**Comment by TheBB** [comment]
You can put it wherever you want. Then add `(<packagename> :location <path>)` to `dotspacemacs-additional-packages`.

**Comment by zeka0** [comment]
Okay I gave it up...It seems that building cedet from source on mac OS X is just nightmare...It reports exactly 3 errors every time...may be it's because I installed emacs through home-brew...I hope spacemacs could replace the older version of cedet in emacs...

**Comment by zeka0** [comment]
Plus every time I start spacemacs it says 'evil-jump-file is obsolete', but nothing serious happened.

**Comment by TheBB** [comment]
That's been fixed in the development branch.

Unfortunately Spacemacs doesn't use CEDET and we don't really have any plans to do so. It's too monolithic. We passed on elpy for much the same reason.
