### ISSUE TITLE
C++ Syntax Error

### ISSUE THREAD

**Issue by zeka0** [syl20bnr/spacemacs#3818]
My matrix_iterator.h file as follows:
#ifndef MATRIX_ITERATOR_H_
#define MATRIX_ITERATOR_H_
#include <iterator>
#include "my_container_base.h"
template<class matrix>
class _Matrix_iterator_base
	:public _STD iterator<
	_STD random_access_iterator_tag,
	typename matrix::value_type,
	typename matrix::difference_type,
	typename matrix::const_pointer,
	typename matrix::const_reference
	>, public _Iterator_base	//multi inherit
{
};
//Hundreds of lines omitted
#endif
Problem 01:The syntax coloring shows that there is a syntax error in '#include <iterator>' Error:(file not found). (My gcc is 5.2.0, clang 700.0.72.)
Problem 02: In "template<class matrix>
class _Matrix_iterator_base
	:public _STD iterator<"
key-word "template" and "class" and "public" is not colored.
Well, emacs recognized it as a 'C' file...

**Comment by TheBB** [comment]
Please go to gitter for questions like these. These aren't Spacemacs bugs, but personal configuration issues.

**Comment by zeka0** [comment]
Oh, I see...
