### ISSUE TITLE
Add vim-empty-lines-mode when stable

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#382]
@sooheon I create this issue just for you ;-)

Thank you for working on it! :+1: 

Link: https://github.com/jmickelin/vim-empty-lines-mode

**Comment by syl20bnr** [comment]
@sooheon several fixes have been committed in the repo and company maintainer added support for vim-empty-lines-mode. Would be cool to test it again and replace vi-tilde-fringe if you find it stable enough.

Thank you !

**Comment by sooheon** [comment]
Yep, I'd set it aside after my initial bug reports. Will check it out again, thanks!

**Comment by syl20bnr** [comment]
Since we have a layer for this, I close it now.
Thank you @sooheon !
