### ISSUE TITLE
helm-spotify does not change track

### ISSUE THREAD

**Issue by axyz** [syl20bnr/spacemacs#3822]
I'm trying out the spotify layer, however while I'm able to do play/pause and next/previous on my current active playlist, when using helm-projectile and I press enter on a track it does not play that track, nor stop the current one. The command seems to be simply ignored and on message buffer I get `shell command succeded with no output`

I'm on develop branch, I have a free spotify account using the official linux client on arch linux (dbus installed)

**Comment by CestDiego** [comment]
I just tried this in my Emacs... :) it's so good to be able to control spotify from inside Emacs. Anyway...it works here and I get these messages:
```Spotify PlayPause [2 times]
Spotify Next
```

**Comment by TheBB** [comment]
I'm on Linux and it works fine. Spotify client 0.9.17.8.gd06432d7

**Comment by victorfonsec4** [comment]
I'm on arch and it's not working for me either.

**Comment by haakenlid** [comment]
With the latest version of the linux spotify client, the OpenUri method appears to be broken. It will not change tracks when there is another track already playing. 
A workaround that works for me (in a shell script) is to send a `Pause` signal just before `OpenUri`.

**Comment by Miciah** [comment]
Looks like the issue has been [fixed upstream](https://github.com/krisajenkins/helm-spotify/commit/35bf50a5bdd877fcb73c1dc0cd6abe4dda8fe027).  Can anyone confirm?
