### ISSUE TITLE
In org-mode, scrolling past inline images will sometimes skip many lines 

### ISSUE THREAD

**Issue by ipsod** [syl20bnr/spacemacs#3824]
# The problem

_A Concrete Example_
When moving the cursor line-wise (using `j`) past a large image on line 11, the cursor goes from line 11 to line 38 in a single jump, skipping lines 12-37.  It does not happen at first, and seems to only occur after some scrolling has happened on the page.
# To reproduce
1. Make a folder.
2. Save the image from https://i.ytimg.com/vi/dDBOl-SmbiE/maxresdefault.jpg in the folder as `maxresdefault.jpg`.
3. Edit a new `org-mode` file in the folder, maybe `test.org`, and add the text at the text at the bottom of the instructions.
4. Turn on inline images and try scrolling past the two images a few times.

`test.org`:

```
* Testing image scrolling
test
test
test
test
test
test
test
test
test
[[file:maxresdefault.jpg]]
[[file:maxresdefault.jpg]]
* test
test
test
test
test
test
test
test
test
test
test
* test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
test
```

**Comment by StreakyCobra** [comment]
I can reproduce this bug. Do you have the possibility to try on a raw emacs with org-mode to know if it is a spacemacs bug? :relaxed:

**Comment by cpaulik** [comment]
I just tried several times on emacs 24.5.1 and latest `org-plus-contrib` and could not reproduce this. Which versions of emacs and org are you using?

**Comment by ipsod** [comment]
I'm on emacs 24.5.1, also.

**Comment by StreakyCobra** [comment]
I'm on linux, emacs 24.5.1 too. Maybe there is a difference if your screen size is big enough to not have to scroll after second image, or maybe there is a difference with scroll-margin.

**Comment by cpaulik** [comment]
I have a HDPI screen on which both images fit easily. So it might be that

**Comment by StreakyCobra** [comment]
Probably, try to add more than 2 images then.

**Comment by cpaulik** [comment]
Tried with 4 images, and also increased the image size so that only one fits on the screen at a time. Still no problems with the scrolling.

**Comment by StreakyCobra** [comment]
Hum, do you have scroll-margin enabled at 5?

**Comment by cpaulik** [comment]
Ah, I had `dotspacemacs-smooth-scrolling` disabled. Enabling it reproduces the error.

**Comment by ipsod** [comment]
Cool, I'm glad to know that I can disable `dotspacemacs-smooth-scrolling` for a temp fix.

Disabling it avoids the error here, too.

**Comment by printfdebugging** [comment]
Hi, I am facing the exact issue with my emacs
