### ISSUE TITLE
disable show-smartparens-mode on large files

### ISSUE THREAD

**Issue by edwintorok** [syl20bnr/spacemacs#3828]
show-smartparens-mode freezes emacs when you have 'if (' in a C file that has 17969 lines (589536 bytes) and you try to move the cursor before/after, or above/below, or just type on that line. In fact I have to press `C-g` a few times to be able to continue editing.
Running `show-smartparens-mode` to toggle it off makes editing bearable again, although syntax checking is a bit slowish too (`-ferror-limit=2` in `.clang_complete` or `SPC t s` makes things faster).

I've added this workaround based on a flycheck PR to my spacemacs config to turn off `show-smartparens-mode` on large files (smartparens-mode itself is still on of course):
https://github.com/Fuco1/smartparens/issues/242#issuecomment-31254204

```
   (add-hook 'prog-mode-hook
            (lambda ()
              (when (> (buffer-size) 40000)
                (turn-off-show-smartparens-mode))))
```

**Comment by nixmaniack** [comment]
This is nice! I was experiencing the same but couldn't figure out what was the cause, had disabled flycheck, flyspell, smartparens and some more minor modes to work. This snippet goes in my config! Thanks.

**Comment by TheBB** [comment]
I think this would be good to have regardless of #3609 since this mode has a size threshold a lot lower than most of the other show-stoppers.

**Comment by bmag** [comment]
I'd like to point out that in the `spacemacs` distribution we also enable `highlight-parentheses` - see https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bdistribution/spacemacs/packages.el#L61. I'm not 100% sure, but maybe it's safe not to enable `show-smartparens-mode` and `show-smartparens-global-mode` in the first place?
In my config I disabled `show-smartparens-mode` and I still have highlighting thanks to `highlight-parentheses`.

**Comment by TheBB** [comment]
@bmag Yes, I do the same actually.

**Comment by StreakyCobra** [comment]
#1425 is about the same issue by the way.

**Comment by StreakyCobra** [comment]
So what do we do?

- Disable `show-smartparens-mode` on big files
- Use `show-paren-mode` instead, but it supports less pairs type:

    > show-smartparens-mode provides functionality similar to show-paren-mode, but works for all the user-defined pairs which are recognized by sp-get-sexp.

- Use `highlight-parentheses`, but I don't know if it supports only parenthesis or also other pairs.

**Comment by syl20bnr** [comment]
Maybe we can hack something to remove the need for `show-smartparens-mode` which is slow. By setting the face of `show-smartparens-mode` for the first level of parentheses of `highlight-parentheses` I guess we should be good. I like the underscore of the face defined by spacemacs theme for `show-smartparens-mode`, it works great with a block shape as a cursor.

**Comment by Apakollaps** [comment]
I still get hit by this issue. It's not just in large files, but in buffers like `shell-mode` buffers that might grow over time that `show-smartparens-mode` is causing issues. Since it freezes emacs I'm surprised that this it's been so quite about this one. Maybe people just turn it off, but it gives a bad first impression of spacemacs.

**Comment by asok** [comment]
I also experience a huge slowdown when opening a large log files (~18MB). When I disable `show-smartparens-global-mode` opening of the same file is instantaneous.

**Comment by osv** [comment]
Common, lets fix this bug, even fundamental mode is freeze on large file

**Comment by osv** [comment]
prog-mode-hook is not good, I think better use `change-major-mode-after-body-hook`
```lisp
  (add-hook 'change-major-mode-after-body-hook
            (lambda ()
              (when (> (buffer-size) 80000)
                (turn-off-show-smartparens-mode))))
```
