### ISSUE TITLE
curly quotes, smart quotes and spelling

### ISSUE THREAD

**Issue by justin808** [syl20bnr/spacemacs#3829]
Words like "isn't" that have smart quotes show up as spelling errors. 

Maybe the default should be for this to be enabled, to ignore differences of smart quotes.

http://www.emacswiki.org/emacs/InteractiveSpell#toc16

https://github.com/gareth-rees/smart-quotes

**Comment by StreakyCobra** [comment]
After looking more in details to this, I doesn't seems simple to do this for all dictionaries. Anyway it can be documented in the FAQ :-)
