### ISSUE TITLE
scala-mode2 - Indentation error 

### ISSUE THREAD

**Issue by mheider** [syl20bnr/spacemacs#383]
Indentation with tab is not possible inside of scala-files, when the contrib-layer scala was added to the dotspacemacs configuration.

Following Error occurs:
```
ad-Advice-scala-indent:indent-code-line: Invalid function: (scala-lib:delete-trailing-whitespace nil)
```

I found a workaround, by commenting out:
```lisp
(defun scala/init-scala-mode2 ()
   (use-package scala-mode2
     :defer t
     :init
     (dolist (ext '(".cfe" ".cfs" ".si" ".gen" ".lock"))
       (add-to-list 'completion-ignored-extensions ext))
     :config
     (progn
       (evil-define-key 'normal scala-mode-map "J" 'spacemacs/scala-join-line)

       ;; Compatibility with `aggressive-indent'
       (custom-set-variables
        '(scala-indent:align-forms t)
        '(scala-indent:align-parameters t)
        '(scala-indent:default-run-on-strategy scala-indent:operator-strategy))

        (defadvice scala-indent:indent-code-line (around retain-trailing-ws activate)
          "Keep trailing-whitespace when indenting."
          (noflet ((scala-lib:delete-trailing-whitespace ()))
                 ad-do-it)))))
```

out of the *packages.el* file in the *~/.emacs.d/contrib/lang/scala* folder.

**Comment by chrisbarrett** [comment]
Do you have `noflet` installed? `(package-installed-p 'noflet)`

**Comment by mheider** [comment]
Yeah i have `noflet` installed.

**Comment by 11Kilobytes** [comment]
@chrisbarrett Evaluating this in a scratch buffer temporarily fixes this error:

    (require 'noflet)
    (defadvice scala-indent:indent-code-line (around retain-trailing-ws activate)
              "Keep trailing-whitespace when indenting."
              (noflet ((scala-lib:delete-trailing-whitespace ()))
                     ad-do-it))

**Comment by chrisbarrett** [comment]
Thanks for that. That implies that `noflet` isn't being loaded.

**Comment by mateusz-gorski-hello** [comment]
It's still not working properly on newest version of spacemacs.

**Comment by josiah14** [comment]
Agreed.  I also can't get any of the functionality out of the scala-mode2 plugin in the scala configuration layer.

Error (use-package): scala-mode2 :config: Required feature `noflet' was not provided

I'm running version 0.104.4 on OSX through Emacs 24.5.1.

**Comment by mateusz-gorski-hello** [comment]
@josiah14 what helped me was removing `scala` from layers and add it according to this guide https://github.com/hvesalai/scala-mode2

**Comment by josiah14** [comment]
@mateusz-gorski-hello Shouldn't this ticket remain open until the `scala` declaration in layers installs scala-mode2 such that it works without further tinkering?

**Comment by mateusz-gorski-hello** [comment]
probably, but I didn't close it.
