### ISSUE TITLE
Subsequent calls of Ctrl-h v <xy> do not popup the *Help* buffer

### ISSUE THREAD

**Issue by triklsbg** [syl20bnr/spacemacs#3831]
Reproduce: Load spacemacs, display the *Help* buffer with Ctrl-h v <any_var>, visit a second file with Ctrl-x f -<file>, query a second var with Ctrl-h v <var> ... you have to change manually to the *Help* buffer to see the result.

**Comment by nixmaniack** [comment]
If you're opening the second file in help buffer itself, then I think it's expected behaviour. Don't know much about internals but I think it's a special window(popwin?) which is different from normal window.
