### ISSUE TITLE
Include currently activated virtualenv information in mode line

### ISSUE THREAD

**Issue by santiagobasulto** [syl20bnr/spacemacs#3837]
Hello guys, I've been tryings to add the currently activated virtualenv to the mode-line but I've not been lucky. I activate my virtualenv with `pyvenv-workon (M-RET V)`. It'd be cool to make the mode line indicate what virtualenv you're currently working on.

**Comment by TheBB** [comment]
We already have an issue about it upstream: https://github.com/syl20bnr/spacemacs/issues/3837

You should follow that, probably.

**Comment by santiagobasulto** [comment]
Thanks @TheBB . Should I close this one?

**Comment by TheBB** [comment]
No, you can leave it open.

**Comment by santiagobasulto** [comment]
Thanks! I'll keep trying to make it work :)

**Comment by TheBB** [comment]
Should be available once MELPA sets up the new version. Details in link above :point_up:
