### ISSUE TITLE
Use secure package endpoints?

### ISSUE THREAD

**Issue by koudelka** [syl20bnr/spacemacs#3843]
As far as I can tell, spacemacs is using non-TLS urls for its `package-archives`. Any thoughts on moving it to TLS?

It looks like the `org` source doesn't seem to respond to TLS at the moment, though.

Maybe some of the other bits from https://glyph.twistedmatrix.com/2015/11/editor-malware.html too?

**Comment by TheBB** [comment]
This was fixed six days ago: https://github.com/syl20bnr/spacemacs/pull/3749

**Comment by koudelka** [comment]
oh, i didn't see that while searching. thank you! :)
