### ISSUE TITLE
[org-mode] Provide option to highlight when no clock is running

### ISSUE THREAD

**Issue by kostajh** [syl20bnr/spacemacs#3844]
It would be nice to have a variable one could set in their `.spacemacs` to show "Not clocked in" prominently in the modeline, [like in this example](https://raw.githubusercontent.com/iqbalansari/emacs-emojify/master/screenshots/emojify-in-action.png).

**Comment by TheBB** [comment]
This should be a feature request to [spaceline](http://github.com/TheBB/spaceline). Please report it there instead.
