### ISSUE TITLE
Discussion file-management layer

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#3848]
I will be revising vinegar layer as a package and wondered if we want a configurable file mgmt layer with options, or keep as separate layers for packages? Options I am thinking of would be vinegar, dired,  diredp, ranger, dired-k, and sunrise-commander.

**Comment by ralesi** [comment]
Neotree is only the sidebar,  so I am thinking it should stay separate.

**Comment by StreakyCobra** [comment]
Does it imply there will be a limitation to use only one file-management package at a time? There is maybe people that like to use both vinegar and ranger. I'm not in this case, just askin' :-)

**Comment by ralesi** [comment]
No,  I think we make them all accessible for use,  but have a primary file manager using something like mentioned here:

**Comment by StreakyCobra** [comment]
I like it then :+1:

**Comment by a13ph** [comment]
I'd put them all together, including neotree - see shells layer and how search tools are done for possible inspiration.
Mapping layers and packages one-to-one sound not great to me, it's not hard to teach people to use blacklist/whitelist keywords, I hope, at least for those who care about "cruft" packages in their setup.
