### ISSUE TITLE
yasnippet autocomplete

### ISSUE THREAD

**Issue by mijoharas** [syl20bnr/spacemacs#385]
You can make yasnippet options be added to the autocomplete dropdown so you can see when one could be triggered. Is this a feature that would be welcomed? would this feature need to be replicated once for ac and once for company mode?

In addition, which is the recommended version for spacemacs, I had heard that company-mode offered some nicer features but never used it myself before.

**Comment by trishume** [comment]
This already exists in the company-mode layer

**Comment by mijoharas** [comment]
ok, well I'll have a look at whatever I had in my autocomplete that made it play well with yasnippet (on my other computer so can't do it now) and throw that in a PR provided it's relatively self-contained. I won't do much work on it though, anticipating the switch to company-mode.

**Comment by kallelindqvist** [comment]
Adding yasnippet as the primary default source
```elisp
(setq-default ac-sources (append '(ac-source-yasnippet) ac-sources))
```
After
```elisp
(ac-config-default) 
```
Makes sure whenever there is a snippet available, it will be the first candidate in the auto-complete menu. Yasnippets are colored with a different background so it's easier to spot in the completion candidate menu.

**Comment by syl20bnr** [comment]
@kallelindqvist Cool, you can submit a PR for this:

```elisp
(when (configuration-layer/package-declaredp 'yasnippet)
  (push 'ac-source-yasnippet ac-sources))
```

**Comment by syl20bnr** [comment]
Fixed with #404

**Comment by mijoharas** [comment]
* 's/#404/#403/' :+1:

**Comment by syl20bnr** [comment]
Thank you :-)

**Comment by cataclysmic** [comment]
How do I get this to work. Having yasnippet in the autocompletion would be a great speed up for me. Sorry, pretty new to spacemacs and haven't completed understood how it all plays together.

**Comment by TheBB** [comment]
Please read the documentation of the auto-completion layer. It's in there.
