### ISSUE TITLE
‘open the quickhelp’ suspended

### ISSUE THREAD

**Issue by tsimaa** [syl20bnr/spacemacs#3853]
OS: Slackware-current

When I start Emacs, bottom line prompt "open the quickhelp". Emacs suspended animation without response, about 1 ~ 2 minutes after only can response keyboard action, which is what reason?

Spacemacs for the first time, thank you.

**Comment by TheBB** [comment]
You probably have https://github.com/emacs-helm/helm/issues/1000

Try this in your `dotspacemacs/user-init` function.

```elisp
  (setq tramp-ssh-controlmaster-options
        "-o ControlMaster=auto -o ControlPath='tramp.%%C' -o ControlPersist=no")
```

**Comment by tsimaa** [comment]
Yes, I have modified the ~/.spacemacs.d/init.el, but the situation is still not changed.

**Comment by TheBB** [comment]
No, your `~/.spacemacs`, where your other settings are. Don't modify Spacemacs source code.

Can you do `emacs --debug-init --timed-requires --profile` to see what is taking a long time to load? You probably have to move to the develop branch to do this.

If you don't want to go to develop you can try `emacs --debug-init` and see in your `*Messges*` buffer if anything is taking a particularly long time to load.

**Comment by StreakyCobra** [comment]
@TheBB He modified `~/.spacemacs.d/init.el`, not `~/.emacs.d/` ;-)

**Comment by tsimaa** [comment]
I create file ~/.ssh/config and input:
Host *
    ControlMaster auto
    ControlPath ~/.ssh/master -%r@%h:%p
    ControlPersist = no

Then, the problem is solved.

**Comment by TheBB** [comment]
Should maybe put that in the FAQ as well then.

**Comment by StreakyCobra** [comment]
This has already been documented a few versions ago, closing it then.
