### ISSUE TITLE
A spacemacs Gnus environment

### ISSUE THREAD

**Issue by zv** [syl20bnr/spacemacs#386]
With the enormously positive response to spacemacs, I don't think it is an exaggeration to say @syl20bnr, @trishume, @ralesi  and the team are some of the most prominent thinkers on the structure of a text composition interface within the Emacs community and beyond. 

Many competing proposals for a reasonable Gnus configuration have emerged over the past decade and beyond, with virtually all of them lacking some essential feature or comprehensive structure to the keybindings and functionality.

Many of us here know that Gnus is an extremely powerful mail/news reader with an extremely comprehensive feature set, but without a reasonable configuration, Gnus floats in a murky sea of unusable configuration snippets and poorly specified minutiae.

Spacemacs has distinguished itself with an extremely well thought out interface and usability philosophy, which I personally think is **burning** to be adapted to Gnus.

##### So where to begin?

* HKJL-ified article, group and summary bindings
* A generic Gmail setup method
* A `<SPC> feg` command for `find-file ~/.gnus`
* Custom group/summary line formats
* [org-mime](http://orgmode.org/worg/org-contrib/org-mime.html) - Easily compose great looking HTML emails
* Autosigning

**Comment by trishume** [comment]
Could be cool, I don't think I'd work on this though since being able to render HTML fancy emails and having a badge on the OSX dock are two of my main requirements for a mail client.

Also I'm flattered that you mention me as one of the main forces behind Spacemacs but really @syl20bnr  does like 2 orders of magnitude more work on Spacemacs than I do, I just submitted a few PRs and frequently weigh in on issues. In fact, I think @ralesi has now contributed more than me, but is still listed lower since Github only counts commits and not actual changes and code.

**Comment by endrebak** [comment]
I also want to look into this, I'd love to have a great e-mail config in emacs. I guess just getting something simple up and running should be the main priority since then people can complain about non-intuitive stuff/make suggestions etc and we'll take it from there.

**Comment by zv** [comment]
I have been extensively working on this and have come to the point where I have something that uses spacemacs-style bindings and mode-specific leaders extensively.

Before I submit a PR, here are some very hastily composed thoughts I would love if @syl20bnr & friends commented on. 

1. Some of `gnus` configuration *should* be stored in `gnus.el`, configuration layers hitherto have not made any such provisions for introducing new file templates, beyond adding a function to copy our own `gnus.el`, what solution seems to resonate with `spacemacs` community?

2. The organization of the gnus configuration themselves could be logically divided in many different ways, however the existing functions/configuration/keybindings paradigm of `contrib` configuration is probably not ideal. Are you in favor of using `.gnus.el` as an `init.el`-alike file and organize the structure of the configuration layer as my preference dictates and modify the `load-path` accordingly? (This of course entails diverging from spacemacs's existing organization format & philosophy)

3. My gnus configuration is quite large and will not be used by the majority of spacemacs users. Would it make sense to package this in such a way that we intend for it to be run through an addition to the ` dotspacemacs-configuration-layer-path` rather than being packaged in `/contrib`?

**Comment by syl20bnr** [comment]
That's a good news!

Your questions are all about the gnus configuration. I would let the user provide the configuration file and define a layer variable to point to it. The layer would then load this file.

The layer would only define the key bindings, integrate gnus with the other packages (golden-ratio, powerli r, etc...) and eventually if it makes sense some helper functions or configuration templates to enhance gnus (for instance to easily configure gnus to access a gmail account - it could be just some documentation).

**Comment by rpglover64** [comment]
The issue seems to be closed, but it seems that no change has been contributed. Reopen the issue until there is at least a pull request?

**Comment by kini** [comment]
:+1:

**Comment by syl20bnr** [comment]
@rpglover64 Indeed, I reopen it.

**Comment by cpaulik** [comment]
Hi, I do have a [gnus config layer](https://github.com/cpaulik/dotfiles/blob/master/.spacemacs-config/config-layers/gnus/packages.el) that works pretty well. But I mainly use it for RSS feeds right now since the pure IMAP setup is to slow for email for my taste.

I also have no idea if it is any good since my main reason for setting it up was to test the color theme I am developing.

But I would be happy to add a Readme and open a PR if nothing better is available.

**Comment by syl20bnr** [comment]
@cpaulik We have to start somewhere so a PR is very welcome.

**Comment by TheBB** [comment]
We actually have a gnus layer now so I think this can be closed?

**Comment by simplygood** [comment]
Current spacemacs evil-mode interferes with standard gnus key bindings. For example, 'g' to get new news and mails does not work. Is there a way to disable evil-mode temporarily in gnus? Or, any workaround keybindings?

**Comment by TheBB** [comment]
@simplygood You can set modes to open in various states by using `(evil-set-initial-state)`. You can set the state of gnus to `emacs`.

**Comment by TheBB** [comment]
I see gnus maps are mostly evilified, so you can recover the gnus bindings according to the rules of evilification. https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#evilified-modes

**Comment by simplygood** [comment]
@TheBB 

(defun dotspacemacs/config ()
  (evil-set-initial-state 'gnus-article-mode 'emacs)
  (evil-set-initial-state 'gnus-group-mode 'emacs)
  (evil-set-initial-state 'gnus-server-mode 'emacs)
  (evil-set-initial-state 'gnus-summary-mode 'emacs)
)
This didn't solve the issue.

Could you point me where to look at for examples of evilification?

**Comment by simplygood** [comment]
I just added to my .gnus.el and it worked.
(evil-set-initial-state 'gnus-article-mode 'emacs)
(evil-set-initial-state 'gnus-browse-mode 'emacs)
(evil-set-initial-state 'gnus-group-mode 'emacs)
(evil-set-initial-state 'gnus-server-mode 'emacs)
(evil-set-initial-state 'gnus-summary-mode 'emacs)

**Comment by sindikat** [comment]
`g` is not evilified in Gnus, `C-S-g` doesn't work. Isn't it supposed to be evilified automatically? See also: #2533

**Comment by gour** [comment]
So, how to check for new mail/news within Gnus, using snippet referenced by @simplygood ?

**Comment by songpeng** [comment]
@simplygood 
I think chen bin has a better solution by Hydra.
See this [hydra for gnus key bindings ](https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/gnus-guide-en.org)
I directly use is under spacemacs. It works well.
