### ISSUE TITLE
emacs freezes (100% CPU Usage) in org agenda view

### ISSUE THREAD

**Issue by xiaoxinghu** [syl20bnr/spacemacs#3861]
To reproduce:
Press `e` (org-set-effort) on org-mode agenda view to a task.

I don't know if it is my setup only. But it happens every time.

**Comment by StreakyCobra** [comment]
I can't reproduce it. Can you paste the output of `SPC h d s` here? It may help identifying the issue. You can also try to update your packages if not already done recently.

**Comment by xiaoxinghu** [comment]
Here you go.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.104.4
- Spacemacs branch: master (rev. f04bb61)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion vim-empty-lines emacs-lisp markdown javascript react ruby python git version-control deft org x-org x-publish osx)
```

**Comment by StreakyCobra** [comment]
@d12frosted Could you try to reproduce this with the given list of layers maybe?

**Comment by xiaoxinghu** [comment]
@StreakyCobra This is the last info shown from emacs, because it is frozen, I cannot switch to Message buffer to see more.
<img width="580" alt="screenshot 2015-11-19 09 58 15" src="https://cloud.githubusercontent.com/assets/1196745/11254201/46383d02-8ea4-11e5-8f6c-44e112fb6bef.png">

**Comment by StreakyCobra** [comment]
Oh, I remember having seen an issue about org-export problem with `vim-empty-lines`, but here it seems to be different.

**Comment by riatzukiza** [comment]
I've been getting an issue simmilar to this. It seems to happen when ever my machines overall load is high.

**Comment by dudelson** [comment]
I've also encountered a similar issue, although I do not use OSX. To reproduce:

1. Press `SPC a o t` to open the org agenda todo list
2. Press `//`

On my system, this completely locks up emacs, and I see 100% CPU usage on a single core indefinitely. Pressing `/` followed by a character other than `/` results in a normal `evil-search-forward`. Pressing `//` in buffers other than the org agenda todo list buffer (even other org agenda buffers) results in a normal `evil-search-forward`.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle :disabled-for org)
 c-c++ fasd emacs-lisp git gtags lua org rust semantic shell-scripts syntax-checking unimpaired)
```
I'm quite new to emacs and haven't been able to make heads or tails of this. Please let me know if it would be better for me to open a separate issue.
