### ISSUE TITLE
[question] how to disable indent in namespace c++-mode

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#3868]
I have a multiply nested namespace in c++-mode:
```
namespace first {namespace second {namespace third {
              // emacs indents three times
// I want to intend here
} } }
```
so emacs indents to the third position. However I just want a single indentation. And I googled this solution. http://stackoverflow.com/questions/2619853/emacs-override-indentation

But unfortunately it does not work in spacemacs. Is it possible to accomplish this effect simply?

**Comment by TheBB** [comment]
That solution works fine for me. Have you remembered to actually *set* the style you made?

[This](https://github.com/TheBB/spacemacs-layers/blob/master/bb-c-styles/config.el#L9) is what I use, for the record. Note I have `0` instead of `[0]`.

**Comment by dzhwinter** [comment]
works now. my config 

```
(defconst my-cc-style
  '("cc-mode"
    (c-offsets-alist . ((innamespace . [0])))))

(c-add-style "my-cc-mode" my-cc-style)
```
()

**Comment by melspectrum** [comment]
@dzhwinter,

where did you put this in your .spacemacs? I tried several places and it still doesn't work....
