### ISSUE TITLE
Undo behaves abnormally

### ISSUE THREAD

**Issue by dsdshcym** [syl20bnr/spacemacs#3869]
Today I suddenly find my evil-undo doesn't work well as normal.

Here is an example:
1. Insert 'a' (using <kbd>i</kbd>, then <kbd>ESC</kbd>)
2. Insert 'b' (using <kbd>i</kbd>, then <kbd>ESC</kbd>)
3. undo (using <kbd>u</kbd>)

But it undoes both 1 and 2.

Here is my system info:
#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 7c160e8)
- Distribution: spacemacs
- Layers:
```elisp
((colors :variables colors-enable-nyan-cat-progress-bar t)
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-enable-sort-by-usage t auto-completion-show-snippets-in-popup t)
 (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/local/bin/zsh")
 git github version-control emacs-lisp common-lisp fasd osx org markdown
 (c-c++ :variables c-c++-enable-clang-support t)
 python ruby pandoc syntax-checking
 (spell-checking :variables spell-checking-enable-by-default nil)
 html dash
 (rcirc :variables rcirc-enable-authinfo-support t)
 rcirc-accounts dsdshcym)
```

**Comment by nixmaniack** [comment]
Was bit confused with repro steps, here's what I tried. 
1. I started `vim /tmp/sample.txt`, `i` for insert mode, typed `ab`, `ESC` to get back in normal mode, hit `u`, it clears `ab`. In short `i a b ESC u` clears `ab`. Expected as you described. (Seems same in spacemacs)
2. Started `vim /tmp/sample.txt`, `i a ESC i b ESC u`, clears only `b` (Seems same in spacemacs)

**Comment by StreakyCobra** [comment]
Same @nixmaniack here.

**Comment by dsdshcym** [comment]
@nixmaniack @StreakyCobra 
Sorry, it's my fault. I set `evil-want-fine-undo` to nil. So I went into this strange issue.

But, after I set `evil-want-fine-undo` to `'fine`. I still have the some issues.

**It just doesn't behave totally like vim.** In most cases, it works fine, but I just want it to be like vim.

1. I tried this in `*scratch*`:

    `i a ESC i b ESC u`

    But both `a` and `b` were cleared.

2. Or this:

    `i test ESC >> u`

    It supposed to just undo the indent. But `test` was cleared too.

3. Last one:

    `i a RET RET RET b ESC u`

    It supposed to undo `a`, 'b' and three `RET`s. But it just cleared `b`.

I don't know if this is a Emacs 25's issue, since I just changed to 25 several weeks ago.
Or maybe it's an issue due to evil.

**Comment by nixmaniack** [comment]
I can confirm 3rd one, but 1st and 2nd are working as you described in the expected behaviour.

**Comment by StreakyCobra** [comment]
Keeping the default value of `evil-want-fine-undo` works as @nixmaniack described, i.e. 1 and 2 working, 3 not working. If set to `nil`, then the 3 works as expected.

Doing it on emacs 25 works exactly like you explain, so it probably an evil issue with emacs 25. I saw you already reported it [here](https://bitbucket.org/lyro/evil/issues/594/undo-doesnt-behave-like-vim).

**Comment by dsdshcym** [comment]
@StreakyCobra Thank you for your tests :smile:. I will report this to evil side.

**Comment by emmanueltouzery** [comment]
The upstream bug is marked as closed, I upgraded my MELPA packages now and it seems to work, at least the basic ia<esc>ib<esc>uu... so probably this bug can now be closed.

**Comment by d12frosted** [comment]
@emmanueltouzery thanks for the heads up! So everyone affected by this issue just upgrade packages. If the problem persist, feel free to reopen this issue.
