### ISSUE TITLE
Installation just installed same old emacs

### ISSUE THREAD

**Issue by yoeluk** [syl20bnr/spacemacs#387]
Hi, I think I'm missing a thing with the installation. I just get the same old emacs, if any differences a little bit uglier. No vim powers.

Install emacs-port -- check
Copy the repo to ~/.emacs.d -- check
Start emacs from terminal -- check

--> No vim powers :(

**Comment by syl20bnr** [comment]
What's the version of Emacs ?

Can you check if there is a Warning buffer ?
Also launch emacs with `emacs --debug-init` to get a stack of any error.

**Comment by yoeluk** [comment]
I get no errors at all and no warnings either. It's as if emacs is totally ignoring the ~/.emacs.d/ dirs that contains the repo (I checked the repo is there). I also cp the ```~/.emacs.d/core/templates/.spacemacs.template``` to ```~/.spacemacs```

emacs version? I followed the install instructions:
```
$ brew tap railwaycat/emacsmacport
$ brew install emacs-mac
```
that gave me --This is GNU Emacs 24.4.1 (x86_64-apple-darwin14.1.0, Carbon Version 157 AppKit 1344.6) of 2015-01-08 on Yoels-iMac-OSX-8.local--

No errors/stack trace with ```emacs --debug-init```

**Comment by syl20bnr** [comment]
What is the value of the variable `user-emacs-directory` ?

```
M-x describe-variable user-emacs-directory RET
```

**Comment by yoeluk** [comment]
On 8 January 2015 at 09:40, Sylvain Benner <notifications@github.com> wrote:

> user-emacs-directory


Actually that seems fine also ```user-emacs-directory is a variable defined
in `subr.el'.
Its value is "~/.emacs.d/"```

**Comment by syl20bnr** [comment]
> Actually that seems fine

Is it working now somehow ?

What did you copy in `~/.emacs.d` ? Just to be sure, you should have the `init.el` file directly in `~/.emacs.d` not a `spacemacs` sub-directory.

**Comment by yoeluk** [comment]
No, not working. I meant that it knows about ~/.emacs.d/
```
$ ls ~/.emacs.d/
.git/           .projectile     contrib/        elpa/           spacemacs/
.gitignore      README.md       core/           init.el
.gitmodules     auto-save-list/ doc/            private/
```
I have not idea why it doesn't call it but actually I just thought that it might have to do with what I have in the ```~/.emacs``` file. Let me double check that. I'm not at all an expert of emacs ways.

**Comment by yoeluk** [comment]
I don't think it is the ```~/.emacs``` file. It looks pretty basic
```
(require 'package)

(add-to-list 'package-archives
             '("marmalade" . "http://marmalade-repo.org/packages/") t)

(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)

(package-initialize)

(unless package-archive-contents
  (package-refresh-contents))

(global-font-lock-mode t)
     (transient-mark-mode t)
(global-font-lock-mode t)
(transient-mark-mode t)

(load-file (let ((coding-system-for-read 'utf-8))
                (shell-command-to-string "agda-mode locate")))
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(agda2-include-dirs (quote ("." "/Users/yoelusa/agda-stdlib/src"))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

**Comment by syl20bnr** [comment]
Did you try to rename the .emacs file ?

**Comment by yoeluk** [comment]
No I didn't try that. How do you suggest I do that for example? I thought that I need this file for my custom settings to be applied, is that wrong?

**Comment by syl20bnr** [comment]
You don't need the suff about package.el, spacemacs take care of it.

For the rest of your file content there is a ~/.spacemacs file where you can put it in a function called `dotspacemacs/config`, there is also the possibility to create your own configuration layer if you want to install new packages etc...:

Read about it in this section:
https://github.com/syl20bnr/spacemacs#configuration

**Comment by yoeluk** [comment]
Spot on, that was it! I appreciate you taking the time to help me out! Cheers.
