### ISSUE TITLE
Project tree incredibly slow

### ISSUE THREAD

**Issue by lnwdr** [syl20bnr/spacemacs#3878]
The project file tree (the one you open with `SPC p t` behaved incredibly sluggish. At first I thought it was because of a slow NFS mount I was working on but it's also very slow on my local SSD.

Things that take really long: opening the tree, opening and closing directories.

Actually opening files is not affected.

I'm using:
* Emacs 24.5.1 (x86_64-apple-darwin14.5.0, Carbon Version 157 AppKit 1348.17
* spacemacs-0.104.4

**Comment by synic** [comment]
Probably a duplicate of https://github.com/syl20bnr/spacemacs/issues/2943

**Comment by lnwdr** [comment]
Yes, the workaround posted one there helped. Thanks.
