### ISSUE TITLE
Move spray package to its own layer

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#3882]
After a lot of sweat and hard thought, we can move to the layer names `speed-reading`.

**Comment by robbyoconnor** [comment]
I will do this.

**Comment by StreakyCobra** [comment]
@robbyoconnor Any update on this?

**Comment by robbyoconnor** [comment]
If somebody else wants to do this -- by all means.

**Comment by declanqian** [comment]
I saw this new layer in the develop branch and tried it out. I add "speed-reading" to "dotspacemacs-configuration-layers" and restart emacs. Nothing happened, no spray package was downloaded. Then I look into the packages.el, and change the "spacemacs/init-spray" to "speed-reading/init-spray". The it works as I expected.
