### ISSUE TITLE
ipython notebook completion

### ISSUE THREAD

**Issue by locojay** [syl20bnr/spacemacs#3883]
Hi,
when i press tab in an ipython notebook cell nothing get's completed.
if i run   `ein:completer-complete` i get the following error

```
Error (websocket): in callback `on-message': Symbol's value as variable is void: ein-direct
```

What am i missing?
Thanks

**Comment by endrebak** [comment]
I tried to reproduce this, but I cannot even open `ein` if I have one of the following set to `t` in my `.spacemacs`:

```
ein:use-auto-complete
ein:use-auto-complete-superpack
```

I get a `symbol's value as variable is void: ein-direct` after pressing `SPC a i n 8888 RET`.

**Comment by StreakyCobra** [comment]
I tried just now and it work*, at least on `develop`. Can you try to update your packages, and give the output of `SPC h d s`?

* it works because autocompletion is triggered, but it's not inserting text correctly: `np.` and select `array` insert `np.np.array`, but it's another story.

**Comment by endrebak** [comment]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.104.4
- Spacemacs branch: master (rev. f04bb61)
- Distribution: spacemacs
- Layers:
```elisp
((c-c++ :variables c-c++-enable-clang-support t))
```

Will try again when 105 comes out. Thanks.

**Comment by locojay** [comment]
```
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 42d1135)
- Distribution: spacemacs
- Layers:
```elisp
((git :variables git-gutter-use-fringe t)
 auto-completion osx loco python ipython-notebook
 (ess :variables ess-enable-smart-equals t)
 syntax-checking org pandoc dash
 (shell :variables shell-default-shell 'eshell)
 eyebrowse semantic smex gtags ranger theming tmux
 (c-c++ :variables c-c++-enable-clang-support t)
 fasd)
```

**Comment by abcdw** [comment]
found C-c TAB hotkey for opening helm-buffer with autocompletion.

**Comment by tutysara** [comment]
I can see this list using C-c TAB. But auto complete doesn't work in spacemacs yet
