### ISSUE TITLE
Company contrib raises an error on master branch

### ISSUE THREAD

**Issue by danielwuz** [syl20bnr/spacemacs#389]
I see below error message when launching spacemacs on master branch.
```
Loading /Users/dawu/.emacs.d/contrib/company-mode/funcs.el (source)...
Compiler-macro error for cl--block-wrapper: (error "(flycheck-error-message err) is not a valid place expression")
Eager macro-expansion failure: (error "(flycheck-error-message err) is not a valid place expression")
```

**Comment by danielwuz** [comment]
@trishume I think this is caused by recent update in https://github.com/syl20bnr/spacemacs/blame/master/contrib/company-mode/funcs.el#L77-L78

Can you take a look? thanks,

**Comment by danielwuz** [comment]
Looks like a known issue from before https://github.com/syl20bnr/spacemacs/issues/169. I'll take a look since I can reproduce this one

**Comment by trishume** [comment]
I'm also going to attempt to "fix" this by switching to the now much better emacs-ycmd and adding a contrib layer for it.

**Comment by CestDiego** [comment]
YES! ymcd rocks! :D

2015-01-09 15:18 GMT-05:00 Tristan Hume <notifications@github.com>:

**Comment by danielwuz** [comment]
Actually regardless of this error message, `company-mode` works just fine, and I couldn't find anything more interesting out from debugging, so I'll let this go.

@trishume I think it's a good idea to move this function to other contrib layer, i.e. C/C++ related layer, and I'm looking forward to emacs-ycmd!
