### ISSUE TITLE
Issues trying to use local version of a package in a layer

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#3890]
I had a bug I patched in haskell-mode and wanted to try it out, so I checked out the documentation on [layers](https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org#packagesel)

After quite a bit of reading I did the following:

```shell
# clone haskell-mode
git clone git@github.com:haskell/haskell-mode.git ~/.emacs.d/private/local/haskell-mode

# reset to specific revision so this repro works for everyone
cd ~/.emacs.d/private/local/haskell-mode
git reset --hard a8e924b5138e2ebc767ad60e78d26f5fba219017

# create copy of haskell layer, then modify haskell-mode to use local package
cd ~/.emacs.d/private
cp -R ~/.emacs.d/layers/+lang/haskell/ ~/.emacs.d/private/

# modify haskell layer's packages.el to use local package of haskell-mode
cd ~/.emacs.d/private/haskell/
sed -i '22s/haskell-mode/(haskell :location local)/' packages.el

# fix bug, then recompile haskell-mode
cd ~/.emacs.d/private/local/haskell-mode/
make EMACS=$(which emacs)
```

restart spacemacs & open eshell

```
~ λ echo "main = putStrLn \"hello\"" > /tmp/hello.hs
~ λ find-file /tmp/hello.hs 
#<buffer hello.hs>
```

within hello.hs buffer, `SPC h d m`, search for haskell mode, click (haskell-mode.el). When it opens haskell-mode.el, press `SPC f f`

This shows me I'm opening the haskell-mode.el in:

`~/.emacs.d/elpa/haskell-mode-20151113.1304/haskell-mode.el`

rather than the desired:

`~/.emacs.d/private/local/haskell-mode/haskell-mode.el`

What is the issue? How can I debug the issue?

Thanks!

**Comment by codygman** [comment]
I just saw my question answered in gitter.

> @joehillen in .spacemacs add dotspacemacs-additional-packages '((haskell-mode :location "~/path/to/haskell-mode")

Will try, then close this issue if it works.

**Comment by codygman** [comment]
I get the following error:

```
eieio--validate-slot-value: Invalid slot type: cfgl-package, :location, (satisfies (lambda (x) (or (member x (quote (built-in local elpa))) (and (listp x) (eq (quote recipe) (car x)))))), "~/source/unsorted/haskell-mode"
```

**Comment by codygman** [comment]
More information:

I then tried `SPC f e h` and searched for `package: haskell` and saw this:

![1447996388](https://cloud.githubusercontent.com/assets/225847/11292415/313f7194-8f13-11e5-9a0a-71aaae48a5bb.png)

**Comment by syl20bnr** [comment]
This is a feature available in develop branch.

**Comment by syl20bnr** [comment]
What you can do is to use a quelpa recipe instead. Make it point to your fork of the repo.

You can see example of such recipe for package evil-indent in master branch (as well as php-extras).

**Comment by codygman** [comment]
Thanks

**Comment by TheBB** [comment]
Is this issue closed then?

**Comment by codygman** [comment]
I can verify it works on develop later.
