### ISSUE TITLE
After running emacs for a while, it starts to become laggy and consumes much CPU

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#3891]
After running emacs for a few days, you start to accumulate a bunch of stuff in `~/.cache`.  As this happens, emacs starts becoming very slow.  Opening helm buffers takes forever, and it will spike to 100% CPU for 5-10 seconds at a time.

Blowing `~/.cache` away helps a LOT.

I *believe* it may be related to auto-loading layouts, however, I deleted all my layouts and deleted all the open buffers.  Reloading emacs only opens the initial startup buffers, but it remains very slow.

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 659d585)
- Distribution: spacemacs
- Layers:
```elisp
(unscroll auto-completion xkcd emacs-lisp jabber git gtags dash yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors spacemacs-layouts vimscript
          (c-c++ :variables c-c++-enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by syl20bnr** [comment]
When it is slow, what are the biggest file in `.cache` ? Also what the most recently modified files ?

**Comment by synic** [comment]
I figured out what this is:

`auto-revert-check-vc-info`, from this bug: https://github.com/syl20bnr/spacemacs/issues/2172

Setting that to `t` has been confirmed to have caused this issue.
