### ISSUE TITLE
how to avoid using `require` on org-modules

### ISSUE THREAD

**Issue by xiaoxinghu** [syl20bnr/spacemacs#3895]
In [no require](https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org#no-require) section in the layers doc, it claims that if you ever need to use `require` at some point, you are probably doing something wrong. But in my scenario, I need to add `(require 'org-protocol)` within `post-init-org` hook (of my own layer) to make org-protocol to work. Is there a better way of doing this? I've tried to add `org-protocol` in `<layer>-packages`, and defun a `init-org-protocol` function that does nothing. Doesn't work for me. I think the reason is that `org-protocol` is not a `package`, but a `module` of package `org`.

**Comment by nixmaniack** [comment]
I'm not sure about this as I haven't tested but some suggestions.
Add org-protocol as built-in in your layer-packages and in the init function add autoloads to the functions your're going to use using use-package. Also bind them to keys in :init of use-package if you want.

Following is just a snippet and I don't know what those commands do in reality, they're just an example so modify appropriately. 

```elisp
(setq my-org-mode-packages
  '(
     (org-protocol :location built-in)
   )
)

(defun my-org-mode/init-org-protocol ()
  (use-package org-protocol
    :defer t
    :commands (org-protocol-capture org-protocol-create) ;; this adds autoloads
    :init
    (progn
      (evil-leader/set-key-for-mode 'org-mode
        "mp" 'org-protocol-capture))))
```

**Comment by StreakyCobra** [comment]
@nixmaniack Just wondering, wouldn't the built-in version of `org-protocol` load the builtin version of `org` that conflicts with the version used by spacemacs?

**Comment by nixmaniack** [comment]
@StreakyCobra I doubt that unless you load your custom layer before loading spacemacs'. As long as you're loading `org` before `my-org-mode` layer, it shouldn't conflict. I may be wrong but layers are loaded in the order specified in your `~/.spacemacs` file so it should be fine.

**Comment by StreakyCobra** [comment]
Ok :-)

**Comment by tonyday567** [comment]
>  may be wrong but layers are loaded in the order specified in your ~/.spacemacs file so it should be fine.
True, but Package references are collected up and then loaded alphabetically.
The difference between an elpa package and a 'package' as a thing that needs a require is confusing. 
My guess is that using (require 'org-protocol) is a better strategy in your use case, as it isn't an elpa package. Awesome if others could confirm that guess or otherwise.

**Comment by xiaoxinghu** [comment]
I agree with @tonyday567, `org-protocol` is more of a "library" rather than a "package". it's like a ".rb" file to a "gem" in ruby. I think it make sense to just `require` it whenever it is needed.

**Comment by gragusa** [comment]
I am trying to setup `org-protocol` within `spacemacs`. This is the only piece of information about it. I have tried few things and I am not able to make it work. Does anybody can provide an example of a working configuration?

**Comment by xiaoxinghu** [comment]
@gragusa  I created my own private layer, called x-org. The packages.el file looks like this:

```elisp
(setq x-org-packages
    '(
      (org :location built-in)
      ))

(defun x-org/post-init-org ()
  (setq org-modules (quote (org-protocol)))
  (require 'org-protocol)

;; the rest of my org mode config
)
```

When you have emacs running, or like me, running emacs as daemon in the background. You run command like this:

```bash
emacsclient -c -F "((name . \"emacs-capture\") (height . 10) (width . 80))" org-protocol://capture://t/\\=
```

You will be prompted by a small emacs window to capture an org entry.
I am not an elisp expert, but I manage to gather all the info I can find online and make it work on my Mac. Good luck.

**Comment by binjo** [comment]
@gragusa i just tried the way @nixmaniack mentioned, and confirm it works. @xiaoxinghu 's method works, but it against the rule to not `require' packages in layers imo.
