### ISSUE TITLE
Bespoke command not opening buffer

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#3899]
The snippet I use to have worked.

    (evil-leader/set-key "ota" '(lambda () (interactive)
        (projectile-with-default-dir (projectile-project-root)
        (call-interactively (shell-command "stack test --test-arguments=--rerun-update")))))

and opened a buffer and displayed the output.

The command runs but I only see 

let: Wrong type argument: commandp, 0

If I manually switch to messages or shell command output it shows the output from the command.

Excuse my lack of emacs knowledge - any obvious pointers ?

Thanks

**Comment by bmag** [comment]
Hey, you have an error in the `call-interactively` call. Emacs runs `(shell-command "stack test --test-arguments=--rerun-update")`, which returns 0, and then `call-interactively` tries to call 0 and fails (0 is not a command, obviously). You probably don't need `call-interactively` at all.

**Comment by fatlazycat** [comment]
Thanks ! That works :)
