### ISSUE TITLE
Evil lisp state bindings gone

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#3901]
This is due to #3860. Tracking this here.

**Comment by TheBB** [comment]
I have added a workaround for this issue to keep evil-lisp-state working.

**Comment by syl20bnr** [comment]
I updated the lisp state to use bind-map, as usual we have to wait for MELPA to process it.

**Comment by CestDiego** [comment]
aww yiisssss

**Comment by TheBB** [comment]
Working now.
