### ISSUE TITLE
Clojure and Rainbow Delimiters

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#3902]
I have the following set in my `.spacemacs`

```
dotspacemacs-highlight-delimiters 'current
```

It works well with my elisp files, but when I open a Clojure file all parens are still highlighted as if it is set as `'all` instead. I need to invoke `rainbow-delimiters-mode` again so that it works as expected. I'm not invoking `rainbow-delimiters-mode` anywhere in my configuration.

**Comment by StreakyCobra** [comment]
@jupl Can you test if #3979 solves your issue?

**Comment by jupl** [comment]
It does.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
