### ISSUE TITLE
Make use-package/init- methods monoidal

### ISSUE THREAD

**Issue by tonyday567** [syl20bnr/spacemacs#3909]
I really struggle with writing a solid, robust layer when I don't know exactly what other layers are going to be also loaded.  If I code it up to just hijack any packages that have already been specified - aka taking ownership - I lose out on someone elses well thought out plans to intergrate in with the wider spacemacs ecology.  And if I go for the use-package-hook methods, I'm relying on some other layer to actually exist in a users config.
An alternative approach would be to go through the layers, collect up use-package specifications, and add them together at the end.  An extra flag in the use-package/init- API could be 'overwrite (throw away other inits), 'add (the monoidal bit) or 'ignore (dont run if another init exists).
The 'add option would still have the potential to do harm, but no differently to the current pre-, post-init hook methods.
Pie-in-sky I know, but if there's some interest in exploring this possibility, I'll take the idea upstream and see whether it's doable.

**Comment by syl20bnr** [comment]
I'm not sure at which level you want to apply this, `use-package` or the spacemacs `init` functions ?
What do you mean by going through the layers and collect the `use-package` to add them together ? Is this different from executing the functions in the right order (pres/init/posts) ?

**Comment by tonyday567** [comment]
Ok, I'll try and get more concrete.  Let's say you make a layer called foo that uses package bar.  There may or may not be another layer that also uses bar.  You have some opinions about how to setup foo, but, if there is another init of bar out there, it's probably best to not overwrite it.

So your foo layer could look like this:

    (defun foo/init-bar ()
      (spacemacs|add-to-use-package bar 'add
        :defer t
        :init (setq bar-enable-awesome t)
    )

If there's no other init-bar, spacemacs|add-to-use-package just turns into a plain use-package.  But let's say there is another layer called baz that looks like this:

    (defun baz/init-bar ()
      (spacemacs|add-to-use-package bar 'add
        :defer nil
        :init (progn
                 (setq important-spacemacs-integration t)
                 (setq bar-enable-awesome nil)
    )

The load process collects these two spacemacs|add-to-use-package and (using the order of the layers) makes this:

      (use-package bar
        :defer t
        :init (progn
                 (progn
                   (setq important-spacemacs-integration t)
                   (setq bar-enable-awesome nil))
                 (setq bar-enable-awesome t)))

Because layer foo came after baz, it overwrites the :defer, and the :init from foo gets added after the :init from baz, so bar-enable-awesome gets set to t, effectively overwriting the baz setup.  But the important-spacemacs-integration is still set.

If all layers are set up like this, there's no need for the owner method, and no having to switch between use-package and use-package-add-hook depending on whether other layers exist.

**Comment by StreakyCobra** [comment]
Interesting idea.

How do you ensure the ordering, as monoids are **not commutative**? Loading layers alphabetically is not possible as names are fixed, using the user-defined ordering is error-prone. Imagine saying to the user:

    The layer A, if used, should be placed after D, but before C.
    The layer B, if used, should be placed after D and A, but before C.

It will be a nightmare with more than 3 layers :stuck_out_tongue: 

Also if I am not mistaking, the monoidal approach is only working at package level when you can order packages loading *individually*. As we are activating layer by layer (that have more than one package each), it will probably not be possible to find a satisfiable solution.

Imagine having:

    Layer AB: load A (no req); load B (req: before BC layer)
    Layer BC: load B (no req); load C (req: before CA layer)
    Layer CA: load C (no req); load A (req: before BA layer)

You will have a cyclic dependencies between layer: `AB -> BC -> CA -> AB -> …`. You can satisfy `A` package ordering, you can satisfy `B` package ordering, you can satisfy `C` package ordering, but you **can't** satisfy layer ordering.

This mean you need a way to specify ordering at package level, and for this you need to know what are the other layers using a package to specify if it should be loaded *before* of *after*. This is not really improving the current situation as you need to be aware if other layers are using the package.

**Comment by TheBB** [comment]
This strikes me as a lot of complexity for little gain. At least, little gain with the current landscape.

**Comment by tonyday567** [comment]
> This strikes me as a lot of complexity for little gain

I hear that, and it's a tricky problem, but I think it actually simplifies things for the writers of layers (and most regulars will want to write layers).  An example: I just saw a query on gitter about how to force a package to load which was specified as :defer in another layer.  Can't be done given the current methods.

The main gain I see is to break the tight-coupling between layers and how things can break very easily if you guess wrong about this coupling.  But I haven't had much experience with spacemacs and it may well be imaginary on my part.

> How do you ensure the ordering, as monoids are not commutative?

I might have gotten the load method wrong in my head, but it looked like layers are inspected in order, and then packages are loaded alphabetically based on what was found.  This idea doesn't alter that at all, and I didn't mean to imply that packages should be ordered in any way, or that layer ordering becomes critical.  The only ordering that pops out is the :init and :config code, and I'm just suggesting that it gets built up in the same order of the layers - nothing tricky about that. The resultant :init and :config blocks might be nonsensical, but no differently to other complexities between layers.

**Comment by TheBB** [comment]
> An example: I just saw a query on gitter about how to force a package to load which was specified as :defer in another layer. Can't be done given the current methods.

This should do it if the other layer defines an `:init` phase.

```elisp
(defun my-layer/pre-init-package
  (spacemacs|use-package-add-hook 'package
    :post-init
    (require 'package)))
```

**Comment by StreakyCobra** [comment]
Monoid are not commutative AFAIK, and we can see it in your example:

If your `baz` layer is named `baz`, then the result is:

```elisp
  (use-package bar
    :defer t
    :init (progn
             (progn
               (setq important-spacemacs-integration t)
               (setq bar-enable-awesome nil))
             (setq bar-enable-awesome t)))
```

If your `baz` layer is named `zab`, then the result is:

```elisp
  (use-package bar
    :defer t
    :init (progn
             (setq bar-enable-awesome t)
             (progn
               (setq important-spacemacs-integration t)
               (setq bar-enable-awesome nil)))
)
```

The value of `bar-enable-awesome` would be different just because of the name of the layer, i.e. because of the ordering of the layers. Monoids are not commutative, and just changing the name/order of the layers would change the packages behaviour.

This implies that you should know about all other uses of a package in order to define its ordering correctly, which means it's not really better than the actual solution :-)

**Comment by syl20bnr** [comment]
As @TheBB pointed out `:defer t` can be overwritten with a `require`. It can be even simpler by just putting this `require` in a `pre-init` function.

I already thought about the ability to aggregate `use-package` forms and it ended up in the request of hooks which are the advantages of being both natural in the elisp landscape and easy to implement. John implemented it in one day. More over hooks allow to hook code before of after init and config blocks. The other use-package keywords can be overwritten by directly using the expanded form.

**Comment by syl20bnr** [comment]
I'm not found of the over usage of use-package. Use-package is a helper but not the obligatory entry point for any elisp feature.

I prefer a use-package agnostic configuration layer system which seems not to be the case here.

**Comment by tonyday567** [comment]
Points well made - you've convinced me it's not very useful. I had assumed use-package was a compulsory part of the machinery.

Thanks for all the feedback :)
