### ISSUE TITLE
Quit key binding not working in Anaconda show doc

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#3914]
In Python mode, running `SPC m h h` opens Anaconda help window `anaconda-mode-show-doc`. This should close by pressing `q` but nothing happens:
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/python/packages.el#L52-L53

See: https://github.com/proofit404/anaconda-mode/issues/144

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 659d585)
- Distribution: spacemacs
- Layers:
```elisp
(extra-langs emacs-lisp ranger python ipython-notebook
             (shell :variables shell-pop-autocd-to-working-dir nil)
             (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
             (syntax-checking :variables syntax-checking-enable-by-default t)
             unimpaired latex git org c-c++ haskell html javascript ruby ycmd smex dash colors lua markdown finance ibuffer)
```

**Comment by StreakyCobra** [comment]
I can't reproduce this bug. `q` is hiding the help window.

**Comment by jluttine** [comment]
Hmm.. Does it require some other layer in addition to `python`?

**Comment by StreakyCobra** [comment]
No, as far as I know.

**Comment by jluttine** [comment]
Ah, now I updated to the recent develop (I was a few days behind), and this seems to be fixed. Nice. Thanks!
