### ISSUE TITLE
Adding to auto-mode-alist in user-config does not work

### ISSUE THREAD

**Issue by joefiorini** [syl20bnr/spacemacs#3919]
### Description

Using `(add-to-list 'auto-mode-alist '("\\.blah\\'" . conf-mode))` does not apply conf-mode when opening a file ending in extension `.blah`.

### Reproduction Steps

Most recently reproduced on a fresh checkout of master, with a brand new `.spacemacs.d/init.el`. Add:

```emacs
(add-to-list 'auto-mode-alist '("\\.blah\\'" . conf-mode))
```

to the `user-config` section of  `.spacemacs.d/init.el`. I then created a file called `diddy.blah` to a test directory.

#### Expected behavior

Looking up `major-mode` in `C-h v` shows the value is `conf-mode`

#### Actual behavior

Value of `major-mode` is `Fundamental`.

Note: I ran into this issue trying to set `.js` files to `react-mode` automatically. In troubleshooting I found this seems to be a more general problem and reproduced using the example above on a fresh installation of `master`. On Gitter.im @TheBB could not reproduce this, so I'm curious if this is something with my machine or an issue with Spacemacs.

**Comment by joefiorini** [comment]
I found today that if I add the `add-to-list` line at the end of `~/.emacs.d/init.el` (yes, the main Spacemacs init file, not my dotspacemacs file) it works great. I took it out (but it's still in `user-config` section of `~/.spacemacs.d/init.el`) and my `.js` files do not get `react-mode` again.

**Comment by StreakyCobra** [comment]
I can't reproduce it. With a clean `.spacemacs`, adding your line at the end of `user-config` works and set mode to for `diddy.blah` to `conf-unix-mode`.

**Comment by mkomitee** [comment]
Are you using the auto-layouts feature?

**Comment by joefiorini** [comment]
It seems to be working okay for me now after a couple updates. Closing this issue.

**Comment by baig** [comment]
This is not working for me as of today.

**Comment by ShaneKilkelly** [comment]
I've just encountered a similar problem. Adding to `auto-mode-alist` doesn't work in the `user-config` function in `.spacemacs`, but it does work if the same expression is added to the end of `.emacs.d/init.el`

For reference, mine was `(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))`

**Comment by d12frosted** [comment]
I know it sounds silly, but I have to ask. Did you evaluate that expression or reload configuration? 😸

**Comment by ShaneKilkelly** [comment]
Yeah, I closed emacs entirely and reloaded between edits to test :)

**Comment by d12frosted** [comment]
What is the value of `auto-mode-alist` after you restart emacs? Does it have `("\\.vue\\'" . web-mode)`? 

P. S. adding that pair to `auto-mode-alist` in `user-config` works for me.

**Comment by mshogin** [comment]
I'm having the same issue

  (add-to-list 'python-shell-extra-pythonpaths "/path/to/lib1/")
  (add-to-list 'python-shell-extra-pythonpaths "/path/to/lib2/")

**Comment by laosb** [comment]
Same issue exactly with the same exactly expression given by @ShaneKilkelly . Of course I reloaded my conf and the variable does contain `("\\.vue\\'" . web-mode)`.

**Comment by itaiferber** [comment]
Also running into this with

```elisp
(add-to-list 'auto-mode-alist '("\\.m$" . objc-mode))
(add-to-list 'auto-mode-alist '("\\.mm$" . objc-mode))
```

Despite both those additions making it into my `auto-mode-alist` at the very front of the list:

```elisp
(("\\.mm$" . objc-mode)
 ("\\.m$" . objc-mode)
 ("\\.djhtml\\'" . web-mode)
 ("\\.ejs\\'" . web-mode)
 ("\\.eco\\'" . web-mode)
 ("\\.hbs\\'" . web-mode)
 ("\\.handlebars\\'" . web-mode)
 ("\\.mustache\\'" . web-mode)
 ("\\.erb\\'" . web-mode)
 ("\\.eex\\'" . web-mode)
 ("\\.as[cp]x?\\'" . web-mode)
 ("\\.[gj]sp\\'" . web-mode)
 ("\\.htm\\'" . web-mode)
 ("\\.html\\'" . web-mode)
 ("\\.xml\\'" . web-mode)
 ("\\.twig\\'" . web-mode)
 ("\\.tpl\\.php\\'" . web-mode)
 ("\\.phtml\\'" . web-mode)
 ("zshrc\\'" . sh-mode)
 ("zshenv\\'" . sh-mode)
 ("zprofile\\'" . sh-mode)
 ...
```

opening up `.m` files still prompts me to install the Octave layer, and regardless of whether I install it or not, sets `octave-mode`.

So it's not that these settings are not reflected in `auto-mode-alist`, but that they're either being ignored, or overridden by a setting elsewhere with higher priority.

**Comment by rambo-panda** [comment]
> I've just encountered a similar problem. Adding to `auto-mode-alist` doesn't work in the `user-config` function in `.spacemacs`, but it does work if the same expression is added to the end of `.emacs.d/init.el`
> 
> For reference, mine was `(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))`

I have a similar problem

in my `~/.spacemacs` add ` (add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))` 

When I open it through the terminal, it has no syntax coloring.
But l open it through the `Emacs` application， it’s normal work!


in my `.emacs.d/init.el` add  `(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))`

terminal and application is normal work!

**Comment by MarcoSero** [comment]
Is there an update on this? I'm running into the same issue with 
`(add-to-list 'auto-mode-alist '("\\.m$" . objc-mode))`

**Comment by Frahwst** [comment]
Seems like this question crops up every now and again, so here's my solution: 
I had this issue with `(add-to-list 'auto-mode-alist '("\\.mk\\'" . makefile-mode))`

and I solved the problem by moving the line from `user-config` to `user-init` in `.spacemacs`.

**Comment by countvajhula** [comment]
Another solution to this issue: note that `add-to-list` does not change the list if the value being added is already present in the list. This is especially relevant for `auto-mode-alist` because the order of elements in the list is in decreasing order of priority. So if the entry is already in the list but at a lower position than a competing major mode for the same extension, then that other major mode will be used for the extension rather than the one you think you've just added. You can verify if this is happening by checking the value of `auto-mode-alist` after your call to `add-to-list`. If the function invocation added anything to the list, it would (by default) be at the head position.

Ways to resolve this if this is happening: (1) Use `push` instead of `add-to-list`. This always adds the element, without checking for membership, so it would add a duplicate entry if already present, which should be fine. (2) Find out what is adding the original entry, and ensure either that it doesn't do that, or that the entry that you want is added at a late stage in your config initialization so that it has a higher priority.

**Comment by xuhdev** [comment]
I found that adding `add-to-list` to `user-config` would only be effective in buffers opened after Emacs starts. If you run

```
emacs myfile.blah
```

This will not be effective.

**Comment by jdeveloperw** [comment]
For me, adding the following to `dotspacemacs/user-init`:

```lisp
(add-to-list 'auto-mode-alist '("\\.trig\\'" . ttl-mode))
```

worked for files passed as a CLI arg (e.g. `emacs foo.trig`) whereas the same block in `dotspacemacs/user-config` only worked for files opened after I started emacs.

My `dotspacemacs/user-init`:

```lisp
(defun dotspacemacs/user-init ()
  "Initialization for user code:
This function is called immediately after `dotspacemacs/init', before layer
configuration.
It is mostly for variables that should be set before packages are loaded.
If you are unsure, try setting them in `dotspacemacs/user-config' first."
  (add-to-list 'auto-mode-alist '("\\.trig\\'" . ttl-mode)))
```
