### ISSUE TITLE
Missing keybindings for TeX-font-list (evil only)

### ISSUE THREAD

**Issue by benquebec** [syl20bnr/spacemacs#3923]
On emacs' side, AUCTeX provides keybindings to insert font specifiers ( e.g. `C-c C-f C-i`to insert italics).
On evil's side, `f`is bound to `TeX-font` which means one still has to indicate which specifier is desired (e.g. `, f C-i`).

 I did some leg work to add bindings in the form `, f i`. I added a macro for each font specifier.

     (fset 'my-set-textit
       (lambda (&optional arg) "Keyboard macro." (interactive "p") (kmacro-exec-ring-item `(,(kbd "C-c C-f C-i") 0 "%d") arg)))

    (fset 'my-set-textbf
       (lambda (&optional arg) "Keyboard macro." (interactive "p") (kmacro-exec-ring-item `(,(kbd "C-c C-f C-b") 0 "%d") arg)))

then I added the binding for each macro (e.g. `"fi" 'my-set-textit`). Now I can use `, f i` for italics, etc.

For now, I have the following shortcuts:

    "fb" 'my-set-textbf : bold
    "fc" 'my-set-textsc : small caps
    "fe" 'my-set-textemph : emphasis
    "ff" 'my-set-textsf : sans serif
    "fi" 'my-set-textit : italic
    "fn" 'my-set-textnormal : normal
    "fr" 'my-set-textrm : roman
    "fs" 'my-set-textsl : slanted

I'd like to know if there's a neater/better way to approach this before I submit a PR.

**Comment by TheBB** [comment]
Please see `doc/CONVENTIONS.org` for the Spacemacs key conventions for this kind of thing:

* `SPC m x b` or `, x b` to make bold
* `SPC m x c` or `, x c` to make code

etc.

**Comment by TheBB** [comment]
Also please figure out how to run this using just function calls instead of keyboard macros. :-)

**Comment by benquebec** [comment]
thanks for your input @TheBB.

- On my setup `SPC m` is broken
- Regarding the convention, I followed AUCTeX. I'll have a look though once I master function calls :)

**Comment by justbur** [comment]
@benquebec 
```elisp
(spacemacs/set-leader-keys-for-major-mode 'latex-mode
  "f"  nil
  "fb" 'my-set-textbf                   ;bold
  "fc" 'my-set-textsc                   ;smallcaps
  "fe" 'my-set-textemph                 ;emphasis
  "ff" 'my-set-textsf                   ;sansserif
  "fi" 'my-set-textit                   ;italic
  "fn" 'my-set-textnormal               ;normal
  "fr" 'my-set-textrm                   ;roman
  "fs" 'my-set-textsl)                  ;slanted
```
you need the nil one first because `f` is already bound for `latex-mode`

**Comment by TheBB** [comment]
I actually found myself doing a lot of LaTeX recently, and these keybindings are life savers (thanks for the tip).

I implemented this in my dotfile.

```elisp
  (spacemacs/set-leader-keys-for-major-mode 'latex-mode
    "xb" (lambda () (interactive) (TeX-font nil ?\C-b)) ; Bold
    "xB" (lambda () (interactive) (TeX-font nil ?\C-f)) ; Medium
    "xc" (lambda () (interactive) (TeX-font nil ?\C-t)) ; Code
    "xe" (lambda () (interactive) (TeX-font nil ?\C-e)) ; Emphasis
    "xi" (lambda () (interactive) (TeX-font nil ?\C-i)) ; Italics
    "xr" (lambda () (interactive) (TeX-font nil ?\C-d)) ; Remove formatting
    "xfa" (lambda () (interactive) (TeX-font nil ?\C-a)) ; Calligraphic math
    "xfc" (lambda () (interactive) (TeX-font nil ?\C-c)) ; Small caps
    "xff" (lambda () (interactive) (TeX-font nil ?\C-f)) ; Sans serif
    "xfn" (lambda () (interactive) (TeX-font nil ?\C-f)) ; Normal
    "xfr" (lambda () (interactive) (TeX-font nil ?\C-r)) ; Serif
    "xfs" (lambda () (interactive) (TeX-font nil ?\C-s)) ; Oblique or blackb
    "xfu" (lambda () (interactive) (TeX-font nil ?\C-u)) ; Upright
    )
```

We can maybe move some of the `xf` bindings down to `x` too.

**Comment by benquebec** [comment]
Go ahead and submit a PR!
I was able to transform the macro into function calls. I don't use lambda though. I'll have a look thanks for posting your bindings :+1

(Since I only write in LaTeX and switched to spacemacs for org-mode, I'm not very fond of the keybindings  in the convention that's why I did not post earlier.)

**Comment by benquebec** [comment]
Just a minor heads-up if you go ahead with the PR:

you have 3 different bindings for  `\C-f`. I think `normal`is `\C-n`

I have `roman`for `\C-r`

**Comment by TheBB** [comment]
Yeah it was just a quickie, I'll fix it up.

**Comment by TheBB** [comment]
:point_right: #3957
