### ISSUE TITLE
[ranger] Leader key broken

### ISSUE THREAD

**Issue by nwolfe** [syl20bnr/spacemacs#3926]
`SPC` is no longer bound to the evil leader key in ranger buffers; instead it just moves the cursor down a line.  This isn't useful, and makes it difficult to get out of ranger buffers.

**Comment by StreakyCobra** [comment]
@ralesi What the best way to correct this?

**Comment by StreakyCobra** [comment]
Is

```elisp
(set-keymap-parent ranger-mode-map evil-normal-state-map)
```

a good solution?

**Comment by dsdshcym** [comment]
I'm using `pdf-tools`. 
And I found the same problem for `pdf-view-mode`.

I got a workaround from @justbur : 
```
(define-key pdf-view-mode-map (kbd "SPC") spacemacs-default-map)
```

**Comment by justbur** [comment]
What state are you in in each of these cases? SPC should be available in motion visual and normal.

**Comment by dsdshcym** [comment]
@justbur Normal state.

Maybe it wasn't bound properly? I can use SPC key after the workaround above.

**Comment by justbur** [comment]
@dsdshcym `pdf-tools` is not in spacemacs is it. The reason SPC doesn't work is this https://github.com/politza/pdf-tools/blob/e2f2eb62d6fc955322cb80bd822e401505ce1155/lisp/pdf-view.el#L229

**Comment by justbur** [comment]
For the ranger issue, @ralesi the SPC binding is coming from `dired-mode-map` which is an overriding map in evil. That means we'll have to bind the SPC key explicitly in the layer. 

The precedence of the bindings has changed slightly since the move away from evil-leader. SPC is in `evil-normal-state-map` which is correctly overriden by anyone who uses `evil-make-overriding-map`

**Comment by dsdshcym** [comment]
@justbur 
Yes, it's my private layer. Here is how I override the pdf-view keybindings:

```
(evil-make-overriding-map pdf-view-mode-map 'normal)
(add-hook 'pdf-view-mode-hook #'evil-normalize-keymaps)
```

According to what you said, SPC should be overridden correctly.

**Comment by justbur** [comment]
@dsdshcym That will make the leader key unavailable because `pdf-view-mode-map` has a keybinding for `SPC` and `evil-make-overriding-map` gives `pdf-view-mode-map` a higher precedence than `evil-normal-state-map` which is where the leader key binding is.

**Comment by dsdshcym** [comment]
@justbur Oh, I forgot that. Thanks for your explanation! :smile:

**Comment by duerrp** [comment]
FYI, here's my configuration for pdf-view:

```
(use-package pdf-tools
    :defer t
    :init
    ;; (pdf-tools-install)
    :mode ("\\.pdf\\'" . pdf-view-mode)
    :config
    (pdf-tools-install)
    (spacemacs|evilify-map pdf-view-mode-map
      :mode pdf-view-mode
      :bindings
      (kbd "j") 'pdf-view-next-line-or-next-page
      (kbd "J") 'pdf-view-next-page
      (kbd "k") 'pdf-view-previous-line-or-previous-page
      (kbd "K") 'pdf-view-previous-page
      (kbd "l") 'image-forward-hscroll
      (kbd "h") 'image-backward-hscroll
      (kbd "/") 'isearch-forward
      (kbd "?") 'isearch-backward
      )
    (add-to-list 'pdf-view-mode-hook
                 'pdf-view-midnight-minor-mode)
    (add-to-list 'pdf-view-mode-hook
                 #'(lambda () (setq pdf-view-display-size 'fit-page)))
    )
```

**Comment by dsdshcym** [comment]
@duerrp Thank you. Mine is almost as same as yours. :smile:

**Comment by TheBB** [comment]
I'm closing this in favour of #3981 which is now the collective go-to issue for this problem.
