### ISSUE TITLE
`M-` bindings no longer works in an ansi-term buffer

### ISSUE THREAD

**Issue by joehillen** [syl20bnr/spacemacs#3927]
I like to try to keep the ansi-term in insert-state, so I typically use the emacs-leader-key to switch windows or buffers.

Pressing the emacs-leader-key in the ansi-term buffer in insert-state no longer has any effect.

I'm on 881ac191147c01348b9cc8d862b24b3a6c032c31 and my packages are up to date.

**Comment by joehillen** [comment]
Actually, I just noticed that all `M-` bindings don't work in any evil state in the ansi-term buffer.

**Comment by nixmaniack** [comment]
Same here. Regression.

**Comment by StreakyCobra** [comment]
It probably appears after the switch to `bind-key`. Linking a maybe [relevant comment](https://github.com/syl20bnr/spacemacs/issues/3926#issuecomment-159123864)

**Comment by syl20bnr** [comment]
. @justbur made a hack in `bind-map` to simulate the old behavior of `evil-leader`, can you update your spacemacs and packages and test again ?

**Comment by justbur** [comment]
Nothing I did would have caused *all* meta key bindings to fail.

**Comment by StreakyCobra** [comment]
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
ee6a486d4cf837cfd340b8fd4715ce92cce95737
9befd20a1a81da0b4b94c69e35951f907bee4615
We cannot bisect more!

**Comment by StreakyCobra** [comment]
It's one of these two, but I can not know which one as there is one in a non-working state.

**Comment by justbur** [comment]
This works for me
```elisp
(define-key term-raw-map "\M-m" spacemacs-default-map)
```
The purpose of ansi-term I believe is to send as many raw keystrokes as possible to the terminal emulator without being intercepted by emacs. If this was working with evil-leader it was entirely by accident.

**Comment by StreakyCobra** [comment]
On last `develop` the bindings like `M-t`, `M-1`, `M-2`, … are working, just `M-m` is problematic

**Comment by justbur** [comment]
Those are probably provided by a minor mode.

I can add an option to bind-map to make the non-evil keys overriding
(almost the highest precedence). @syl20bnr is that what you want? Or do you
want to manually fix cases like this?

**Comment by justbur** [comment]
Added the option anyway and made a PR in #4003.

**Comment by TheBB** [comment]
Closing since this issue is not on master.
