### ISSUE TITLE
C-x in ido-buffer does not work

### ISSUE THREAD

**Issue by danielwuz** [syl20bnr/spacemacs#393]
`C-x` is supposed to open current file in another window as documented [here](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#ido). But in fact it's running as a prefix command and does not work.

**Comment by syl20bnr** [comment]
Seems that the key bindings need some rework:
- C-x ==> C-o
- C-v ==> C-s
- C-b ==> C-v
- C-t ==> C-f

**Comment by danielwuz** [comment]
Can I ask what's the reason of rebinding most of the default key bindings in ido? rather than keep the default as much as possbile?

**Comment by syl20bnr** [comment]
C-x to C-o because does not make sense, and the action is to open in _other_ window.
C-v to C-s because splitting horizontally is on `SPC w s`
C-b to C-v because splitting horizontally is on `SPC w v`
C-t to C-f because nowhere in spacemacs `t` refers to a frame, so better stick with mnemonic.

**Comment by syl20bnr** [comment]
C-w may be a better choice instead of C-o in order to keep symmetry with C-f

**Comment by danielwuz** [comment]
The first three sound good to me, but the last one, `C-f`, to my knowledge is the key to trigger ido fallback to default `find-file`, it'll be useful to prevent ido from fuzzy match when creating files. I propose to use a different key bindings for the last one(or just keep `C-t` for it)

**Comment by syl20bnr** [comment]
`C-f` is missing from the doc, we can keep `C-t` then.
`C-o` for other window may be easier to type than `C-w` and it feels more natural to me.

**Comment by danielwuz** [comment]
Cool. Also I'd like to bind `isearch-backward` to `C-r`. It's useful to be able to search in visited file history. This one has a sibling `C-s` to search forward, but as we decide to bind splitting horizontally to `C-s` and is less as useful as searching backward in my opinion. we can leave it off for now.

How does that sound to you?

**Comment by syl20bnr** [comment]
isearch can be bound to `C-/`, to be complete the backward could also be bound to `C-?`

**Comment by syl20bnr** [comment]
@danielwuz  What is the expected behavior of `C-r` and `C-s` ? I tried them in ido and it just select the next item of the list.

**Comment by danielwuz** [comment]
@syl20bnr you should be able to search backward and forward in ido-opened history by fuzzy matching, very much like searching commands history in a shell by `C-r`. 

You can try with `emacs -Q`, then `M-x load-library`, then `ido-find-file` to open couple files, then in a `ido-find-file` buffer, do `C-r`.

**Comment by danielwuz** [comment]
After using `ido-mode` for a while, I'm quite happy with current key bindings now. I don't see any functionality missing here. We can probably keep ido as it is for now. If you still think it's necessary to rebind all keys, we can open a new thread for it.

**Comment by syl20bnr** [comment]
`C-v` is problematic because it means the inverse of the `SPC w v`, I'll open a issue for this.

**Comment by syl20bnr** [comment]
@danielwuz I don't get the `C-s` and `C-r` you are describing, I looked in ido source code and those key bindings are bound to `ido-next-match` and `ido-prev-match` which are on `C-j` and `C-k` in spacemacs.

I will switch the split functions to `C-s` and `C-v` to mirror `SPC w` behavior, if they shadow something you find useful you can send a PR for binding them on another key.

**Comment by danielwuz** [comment]
Sure. I'll keep my eyes on it.

**Comment by syl20bnr** [comment]
It's in develop
