### ISSUE TITLE
how to load shell PATH when launch emacs daemon through launchd?

### ISSUE THREAD

**Issue by xiaoxinghu** [syl20bnr/spacemacs#3930]
I launch emacs as daemon through `~/Library/LaunchAgents/homebrew.mxcl.emacs.plist`. Then I loss the "PATH" from my shell settings (which is `zsh`). How can I load the right path without specifically change the `exec-path` in user-config.
`exec-path-from-shell` works for the GUI, but it doesn't work for launchd.

PS: I don't want to change `~/Library/LaunchAgents/homebrew.mxcl.emacs.plist` either. Unless it is the most sensible way, then we can contribute to the homebrew formula instead.

**Comment by Miciah** [comment]
This sounds like the sort of problem that the recently added `~/.spacemacs.env` is intended to solve.  See [Environment variables and PATH](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#environment-variables-and-path) in the Spacemacs documentation.  Does that resolve this issue?
