### ISSUE TITLE
Persistent error for initializing org mode

### ISSUE THREAD

**Issue by mclearc** [syl20bnr/spacemacs#3933]
With a clean `.spacemacs` on develop branch and OS X I get the following error:

`(Spacemacs) Org features were loaded before the 'org' layer initialized.
Try removing org code from user initialization and private layers.`

There are no other problems that I can see other than that it makes my modeline go red every time I reload my config file. 

here's my other info:

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. a363504)
- Distribution: spacemacs
- Layers:
```elisp
(org)
```

**Comment by robbyoconnor** [comment]
:+1:

**Comment by autosquid** [comment]
Same Here. It looks like something improper about `agenda`. Here is my warning info:

```
(Spacemacs) Org features were loaded before the `org' layer initialized.
Try removing org code from user initialization and private layers.
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':
   - `org-agenda-next-line' originally mapped on `C-n'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':
   - `org-agenda-toggle-time-grid' originally mapped on `G'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':
   - `org-agenda-filter-remove-all' originally mapped on `|'
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':
   - `org-agenda-filter-by-tag-refine' originally mapped on `\'
(Spacemacs) Error in dotspacemacs/user-config: Selecting deleted buffer

```

**Comment by TheBB** [comment]
Those warnings are not a problem. Basically the message tells you what the problem is. You have some config that loads org before it should be loaded. This is bad because it will load the built-in org which will cause a version conflict.

**Comment by TheBB** [comment]
The reason you get it from a clean `.spacemacs` with just the org layer is probably because org must be loaded to compile some of the packages. That was not intended, and I'm not sure what to do about it. Maybe we have to disable this check until we figure out how to fix it.

**Comment by TheBB** [comment]
I have disabled the offending check for now.

**Comment by TheBB** [comment]
We can discuss this in #3742.
