### ISSUE TITLE
A strange question about zshenv and spacemacs

### ISSUE THREAD

**Issue by Cifer-Y** [syl20bnr/spacemacs#3939]
Today, I upgrade my spacemacs to 0.104.5, and I got a warning:
```
Warning (emacs): You appear to be setting environment variables ("PATH") in your .bashrc or .zshrc: 
those files are only read by interactive shells, so you should instead set environment variables in startup 
files like .bash_profile or .zshenv.  Refer to your shell's man page for more info.  In future, exec-path-
from-shell will not read variables set in the wrong files.

```

So I moved my environment variables from .zshrc to .zshenv, and the warning gone,
but my spacemacs become very very slow, press j, wait 1 sec, then the cursor move down 1 line.
That's so strange, beyond my ability, I don't want to complain about that, but I'm quite confused about that.

By the way, I'm using OS X 10.11.1, and using emacs GUI

**Comment by StreakyCobra** [comment]
Thanks for your issue. This bug has already been reported in #3920. Feel free to discuss it there :relaxed: I'm closing this one as it's a duplicate.
