### ISSUE TITLE
Keymap issues in Python Nose

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#3940]
When running nosetests, normal `SPC` key bindings do not work in the nose window. Pressing `SPC` prints `End of buffer` in the status line. Is this expected or a bug? For instance, to maximize the nose window, one must press `C-x 1` instead of `SPC w m`.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. a363504)
- Distribution: spacemacs
- Layers:
```elisp
(extra-langs emacs-lisp ranger python ipython-notebook
             (shell :variables shell-pop-autocd-to-working-dir nil)
             (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
             (syntax-checking :variables syntax-checking-enable-by-default t)
             unimpaired latex git org c-c++ haskell html javascript ruby ycmd smex dash colors lua markdown finance ibuffer spacemacs-layouts)
```

**Comment by jluttine** [comment]
Actually, I'm not sure if this is related to Compilation mode more generally. So it might not be Python/Nose specific? Don't know.

**Comment by TheBB** [comment]
I'm closing this in favour of #3981 which is now the collective go-to issue for this problem.
