### ISSUE TITLE
Indent region broken in Python layer

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#3941]
`SPC j =` runs `indent-region-or-buffer`. However, it doesn't do anything in Python mode. It seems to work at least on some other modes (e.g., C/C++ files). Indenting works line-by-line in insert mode with `TAB` and in normal mode with `SPC j k`, but `SPC j =` does nothing.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. a363504)
- Distribution: spacemacs
- Layers:
```elisp
(extra-langs emacs-lisp ranger python ipython-notebook
             (shell :variables shell-pop-autocd-to-working-dir nil)
             (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
             (syntax-checking :variables syntax-checking-enable-by-default t)
             unimpaired latex git org c-c++ haskell html javascript ruby ycmd smex dash colors lua markdown finance ibuffer spacemacs-layouts)
```

**Comment by nixmaniack** [comment]
Major mode code formatting is available under `SPC m =`. 
Python being indent sensitive it's excluded from generic indent-region function available under `SPC j =`. Other modes which are excluded from this which I know are haml and makefile. 
If you really want to use indent-region, you can as well execute it using `C-M-\` (you might need to select region first)

**Comment by jluttine** [comment]
Ok, thanks! `SPC m =` is ok, didn't know about it.

**Comment by nixmaniack** [comment]
Also `SPC m` = `,` in normal mode. One less keystroke.

**Comment by jluttine** [comment]
Oh, nice! Thanks!

**Comment by jluttine** [comment]
Hmm.. That Yapf seems to process the whole buffer even though I have a region selected. Also, it does a bunch of other stuff in addition to indenting. But `C-M-\` works. Can I easily bind `indent-region` to `SPC j =` in Python mode? Or maybe there could be some key binding for it under `SPC m`..? I can make a pull request of that key binding, but do you have any opinion what it should be (if any)?

**Comment by nixmaniack** [comment]
`C-M-\` is generic function. `SPC j =` uses that internally. So I'm not sure if we need another binding for it. I don't know concrete reasons except that python-mode was removed from `SPC j =` as it's indent-sensitive and py-yapf does better job (although opinionated).

A quick fix to get `SPC j =` working in python-mode would be to remove it from `spacemacs-indent-sensitive-modes`
So following in `user-config` would allow you to use `SPC j =`. 
```
(setq spacemacs-indent-sensitive-modes
      (delete 'python-mode spacemacs-indent-sensitive-modes))
```

On another note, yes I do know yapf works on whole buffer instead of region but that's just to keep the whole buffer consistent(I think so) which might be an annoyance sometimes.

**Comment by tom4everitt** [comment]
Mark a region, then use `C-x` `TAB' and then indenting with `h`, `l`, `H`, `L` was what I was looking for. 

Allows you to "manually" shift a piece of code into the right indent, after copy-past for example.
