### ISSUE TITLE
Key binding to open/toggle compilation window

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#3945]
Currently, there's no key binding to open a compilation window once it has been closed. There could be a key binding to open or toggle it. There's a key binding to close it: `SPC c q`.

**Comment by jluttine** [comment]
A workaround for nosetests compilation window by @nixmaniack:

```
(defun open-nosetests-compilation-buffer ()
  (interactive)
  (when (get-buffer "*nosetests*")
    (popwin:popup-buffer "*nosetests*"))
  )

(spacemacs/set-leader-keys
  "cs" 'open-nosetests-compilation-buffer)
```

**Comment by jb55** [comment]
Concept ACK

**Comment by xypnox** [comment]
Just a minor correction, the keybinding for closing the compilation window is `SPC c d` and not `SPC c q`

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Replace close-compilation-window with show-hide-compilation-window. #13477

This issue can be closed if either the issue author or someone else can test that it's working as expected.
