### ISSUE TITLE
Add option for where focus goes when splitting a window

### ISSUE THREAD

**Issue by calebmeyer** [syl20bnr/spacemacs#3947]
Currently, splitting a window (for example with `SPC w /`) leaves the focus in the current window. This behavior seems awkward to me.

I propose we add an option (possibly with a keybinding to toggle if we think it would be toggled frequently) to change this behavior. Something along the lines of:

```el
;; If non-nil, when you create a new window, it gets keyboard focus.
;; Otherwise keyboard focus remains in the same window
dotspacemacs-focus-new-windows t
```

**Comment by nwolfe** [comment]
:+1:

**Comment by TheBB** [comment]
`SPC wV` and `SPC wS` as opposed to `SPC wv` and `SPC ws` do this.
