### ISSUE TITLE
Helm company C-/ only works in GUI mode

### ISSUE THREAD

**Issue by bogdanteleaga** [syl20bnr/spacemacs#3952]
I was watching @TheBB's first video on spacemacs and I saw the C-/ functionality, it looked really cool so naturally I wanted to try it out.

Turns out I can only do it when using GUI emacs, but terminal emacs just defaults to undo when I press C-/.

**Comment by StreakyCobra** [comment]
This is another variant of #3472. In terminals, `C-/` is interpreted by the shell as `C-_`, which is bound to `undo-tree-undo` in emacs. This can be verified by doing this in command-line: `C-v` (insert the next keypress verbatim), then `C-/`. It inserts `^_`.

So nothing unexpected here, and nothing we can do on Spacemacs side `¯\_(ツ)_/¯`

**Comment by bogdanteleaga** [comment]
Fair enough, it seemed weird enough to not necessarily be related to spacemacs. It seems C-SPC also doesn't mark items in helm in terminals. I probably have to figure out a way to make the terminal inster the proper character.

I'll close this though, we don't need bugs lying around, especially since the cleanup *just* finished :)

**Comment by StreakyCobra** [comment]
You can also try with `C-i`/`TAB` and `C-BACKSPACE`/`C-h`. And if you find a way to do this, please report it to the previously linked issue :smile: 

> I'll close this though, we don't need bugs lying around, especially since the cleanup just finished :)

:+1: :joy:
