### ISSUE TITLE
Pasting content in webmode inserts content in incorrect place

### ISSUE THREAD

**Issue by ashervb** [syl20bnr/spacemacs#3960]
``` html
<div></div>
<div |id="foo"></div>
```

Cursor is at `|`, deleting `id=foo` and attempting to paste into the first div will result in

``` html
 id="foo"<div></div>
<div></div>
```

rather than the expected

``` html
<div id="foo"></div>
<div></div>
```

**Comment by CestDiego** [comment]
I can confirm this.

**Comment by StreakyCobra** [comment]
What are the steps you are using for delete and paste? I tried it here by using `v` to select the ` id="foo"`, then `d` to delete it, then `p` on the line above to paste it and it worked.

**Comment by exitface** [comment]
```html
<div></div>
<div |id="foo"></div>
```

Cursor is at `|`, type ```dt>```, move to the `<` above and hit `P` results in the above error. Curiously enough if I move to the `v` in `div` and hit `p` I get the following result::

```html
<div></div>
 id="foo
<div>
```

**Comment by TheBB** [comment]
I definitely can't confirm any of your behaviour. It works as expected here.

**Comment by exitface** [comment]
I did some additional testing, the error only occurs for me when I have the `html` layer enabled in my `   dotspacemacs-configuration-layers`

**Comment by StreakyCobra** [comment]
Same as @TheBB, I can't reproduce, with html layer enabled too. Can you paste here the result of `SPC h d s` ?

**Comment by exitface** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.6
- Spacemacs branch: master (rev. 50ec30b)
- Distribution: spacemacs
- Layers:
```elisp
(html)
```

I should also note that it seems the behavior doesn't occur with a fresh buffer (e.g. just paste the above in). In order to trigger, it seems that you need to work within the buffer for a bit. The most reliable way I've found is to paste in the above, then swap the lines twice by typing `gg ddp k ddp` before attempting the above steps.

**Comment by StreakyCobra** [comment]
Ok I was able to reproduce it, by playing indeed a few time with the buffer. Looks like an upstream bug for me, probably between `web-mode` and `evil`…

**Comment by tbo** [comment]
I am not a spacemacs user, but I am experiencing the same issue. I was able to confirm @StreakyCobra's web-mode<->evil theory. I already filed a bug in the web-mode bugtracker (https://github.com/fxbois/web-mode/issues/756), but the maintainer couldn't help me out and pointed me to stackoverflow, where I posted the problem as well (http://emacs.stackexchange.com/questions/24542/pasting-text-doesnt-work-properly-in-evil-web-mode). After one month without any comments, I reposted it in the evil bugtracker (https://bitbucket.org/lyro/evil/issues/703/pasting-text-doesnt-work-properly-in). To this day, i haven't got any answers.

Any ideas, what I could try next?

**Comment by TheBB** [comment]
Well, there's always reading the source code and figuring it out yourself, if all else fails.

**Comment by honmaple** [comment]
Confirm this.I can reproduce this bug,the code:
```
     <li style="padding:0 20px;border-left:1px solid #666;border-right:1px solid #666;">
        <a href="">
        <span class="item-count"><b>100</b></span>
        <span class="item-name">category</span>
        </a>
    </li>
```
when I use evil-visual-state to copy `padding:0 20px;`,and then use `p` to paste text,it's would be normal.
```
    <li style="padding:0 20px;padding:0 20px;border-left:1px solid #666;border-right:1px solid #666;">
        <a href="">
        <span class="item-count"><b>100</b></span>
        <span class="item-name">category</span>
        </a>
    </li>
```
but when I use `yy` to copy first line,the code:
```
    <li style="padding:0 20px;border-left:1px solid #666;border-right:1px solid #666;">
    <li style="padding:0 20px;border-left:1px solid #666;border-right:1px solid #666;">
        <a href="">
        <span class="item-count"><b>100</b></span>
        <span class="item-name">category</span>
        </a>
    </li>
```
then use evil-visual-state to copy `padding:0 20px;` and use `p` to paste text,the bug was reproduced.
```
    <li style="padding:0 20px;border-left:1px solid #666;border-right:1px solid #666;">
    <li style="padding:0 20px;border-left:1px solid #666;border-right:1px solid #666;">
padding:0 20px
        <a href="">
        <span class="item-count"><b>100</b></span>
        <span class="item-name">category</span>
        </a>
    </li>
```
I read the evil code and test it,and I found the bug was caused by 
```
          (if (functionp yank-handler)
              (let ((evil-paste-count count)
                    ;; for non-interactive use
                    (this-command #'evil-paste-after))
                (insert-for-yank text))
```

`(functionp yank-handler)` should be `nil` If I use evil-visual-state to copy text,but it's `t` after I use `yy` to copy some text.

Unfortunately,I don't konw how to fix it?:joy:

**Comment by bschwehn** [comment]
As a workaround I changed evil-common function evil-yank-characters to 

```
(defun evil-yank-characters (beg end &optional register yank-handler)
  "Saves the characters defined by the region BEG and END in the kill-ring."
  (let ((text (filter-buffer-substring beg end)))
		(unless yank-handler
			(setq text (propertize text 'yank-handler nil)))
    (when yank-handler
      (setq text (propertize text 'yank-handler (list yank-handler))))
```
This seems to work so far, but not sure of any possible side-effects. 
Also could not figure out why this happens with web mode only.

**Comment by bschwehn** [comment]
As far as I can tell, this is caused by web-mode setting yank-excluded-properties to t. 

Not sure if this is required by web-mode. Disabling this also solves the issue (again, not sure about any possible side effects)
