### ISSUE TITLE
Quitting `org-present` breaks evil-bindings  

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#3961]
to reproduce: 

- open/create a buffer in org-mode with a list of things
- enable `org-present` - `M-x org-present` 
- try navigating between slides - `h` and `l`
- quit `org-present` - `q`
- try to use evil bindings, like `i` or `dd`

re-enabling `org-mode` fixes it. Maybe it should be added/fixed in `org-present-mode-quit-hook`

**Comment by StreakyCobra** [comment]
Duplicate of #1874
