### ISSUE TITLE
[question] is it possible to add an  indicate feature for updating?

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#3962]
once I update my spacemacs, my dependency is broken and give me error messages. I'm wondering that is there any way indicate  how many dependencies may be broken before update? 
Because sometimes fix the error will consume a lot of time, which not a good idea when I start busy work in morning. I know there is rollback, but still want to know is there someone else thought this like me.

Error (use-package): discover-my-major :init: Symbol's function definition is void: evilify
Error (use-package): evil-lisp-state :config: Symbol's function definition is void: evil-lisp-state-leader
Error (use-package): org-present :init: Symbol's function definition is void: evilify

System Info
```
#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. cc31e7f)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion
 (org :variables org-enable-github-support t)
 (python :variables python-enable-yapf-format-on-save t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "johan-tibell"))
```

```

**Comment by StreakyCobra** [comment]
I don't think so. When you update packages, you are getting changes that are not part of Spacemacs. There is no way we can know in advance if it will break something or not. The best is to try it, and if it breaks to rollback them.

**Comment by dzhwinter** [comment]
hmm... forget it.
