### ISSUE TITLE
Update thrisume blog post about Spacemacs

### ISSUE THREAD

**Issue by StreakyCobra** [syl20bnr/spacemacs#3965]
As @geo7 pointed out on gitter, [trishume blog post about Spacemacs](http://thume.ca/howto/2015/03/07/configuring-spacemacs-a-tutorial/) is highly ranked on Google results. Some users coming in the past to gitter were having questions/problems after having read this article because it starts to be outdated.

I wrote a mail to @trishume with some basic changes, asking him also to put a notice at the top saying that information can be outdated. He already did some modifications (thanks to him :+1:) but there is still some parts that are not exact. He is open to PR as his blog is on github.

It would be nice to [PR the changes](https://github.com/trishume/trishume.github.com/blob/master/_posts%2F2015-03-07-configuring-spacemacs-a-tutorial.md) needed to adapt the article to last version of Spacemacs.

**Comment by syl20bnr** [comment]
Good initiative :+1: 
I'll check it again when I can. 

Thanks @trishume for keeping up to date the article, it is greatly appreciated!

**Comment by LemmingAvalanche** [comment]
<https://github.com/syl20bnr/spacemacs/issues/7334#issuecomment-252802531>
marked this issue as “valid”.

Some changes have been merged upstream.

Please review if more changes should be done.
