### ISSUE TITLE
[question] evilify macro had gone in develop branch?

### ISSUE THREAD

**Issue by dzhwinter** [syl20bnr/spacemacs#3967]
My private config used evilify macro below, and worked well.
```
 (evilify makey-key-mode makey-key-mode-get-key-map ))))
```
now it trigger a error of 
```
Symbol's function definition is void: evilify
```
surely evilify is delete in develop branch. Then I find that there is a issue of #3555 , now i'm confused, which macro is available to replace in my config?

```
#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. cc31e7f)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion
 (org :variables org-enable-github-support t)
 (python :variables python-enable-yapf-format-on-save t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "johan-tibell"))
```

**Comment by nixmaniack** [comment]
`evilified-state-evilify`

**Comment by TheBB** [comment]
Yep, `evilify` is `evilified-state-evilify` and `spacemacs|evilify-map` is `evilified-state-evilify-map`.

**Comment by syl20bnr** [comment]
@dzhwinter we started to decouple evilified state from core of spacemacs so hopefully at some point I will make it a package on its own, this is why the API changes.

**Comment by dzhwinter** [comment]
:+1: @syl20bnr
