### ISSUE TITLE
Updating Powerline Theme for Terminal mode

### ISSUE THREAD

**Issue by medismailben** [syl20bnr/spacemacs#3972]
Hey, 

I've started using Spacemacs for few days now and i'm already blown away. It's a really complete solution for people who wants a great IDE straight out the box. However, since I use it via SSH, it launches in no window mode and powerline does some weird stuff :/ ! I've seen that there is a terminal "theme" for this packages that fixes it. Could you add it to the default packages ? 

Once again, well done for this emacs distribution ! Keep up the good work bro !!

M|B

**Comment by cpaulik** [comment]
What kind of weird stuff? 
I'll just guess and recommend setting 
`(setq powerline-default-separator 'nil)` in your `spacemacs/user-config` function.

see [here](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#powerline-separators) for all options.
