### ISSUE TITLE
Evilify bindings getting overridden

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#3978]
I'm getting a weird case of evilified state bindings getting overridden (I'm on develop branch).

Relevant private layer code:

~~~ emacs-lisp
(defun mir-elfeed/init-elfeed ()
  (use-package elfeed
    :defer t
    :init
    (progn
      (evil-leader/set-key "ae" 'elfeed)
      (evilified-state-evilify-map elfeed-search-mode-map
        :mode elfeed-search-mode
        :eval-after-load elfeed
        :bindings
        (kbd "gR") 'elfeed-update
        (kbd "gr") 'elfeed-search-update--force))
    ))
~~~

Reproduce:

1. Start elfeed. `g r` is bound to `elfeed-search-update--force` and `g R` is bound to `elfeed-update`.
2. Start org-agenda.  `g r` is bound to `org-agenda-redo` and `g R` is bound to `elfeed-update`.
3. Restart elfeed. `g r` is bound to `org-agenda-redo` and `g R` is bound to `elfeed-update`.

**Comment by darkfeline** [comment]
It looks like the prefix map on `g` is being shared between all evilified maps.

**Comment by darkfeline** [comment]
Attempted fix https://github.com/syl20bnr/spacemacs/pull/4010

Works for me, but I'd like a code check please.

**Comment by syl20bnr** [comment]
@darkfeline I modified the implementation of evil evilified state to work on a copy of the whole map, can you check if you have any regression ?

**Comment by darkfeline** [comment]
No regression, thanks.
