### ISSUE TITLE
Use flycheck instead of flycheck-rust for rust

### ISSUE THREAD

**Issue by globin** [syl20bnr/spacemacs#3985]
flycheck supports rust now itself without flycheck-rust (flycheck/flycheck#772) and fixes flycheck/flycheck-rust#8. Might be an improvement to the current setup.

**Comment by lunaryorn** [comment]
@globin Uhm, I'm sure that there's a misunderstand somewhere.  You still need both libraries for a seamless Rust setup.

**Comment by globin** [comment]
Hm OK I don't get this but I'll believe you \o/

**Comment by lunaryorn** [comment]
@globin I'm sorry; it seems that we fail to properly explain the purpose of flycheck-rust.  I'd like to address this issue with better documentation.  Would you mind to explain what is unclear?

**Comment by lunaryorn** [comment]
By the way, @globin, https://github.com/syl20bnr/spacemacs/issues/4109 is why you'll still need both.
