### ISSUE TITLE
No themed pos tip any more

### ISSUE THREAD

**Issue by romanofski** [syl20bnr/spacemacs#3993]
My flycheck pos tip is not themed anymore:
![flycheck_error](https://cloud.githubusercontent.com/assets/121047/11460685/c164a934-973c-11e5-95c1-ce230b206eee.png)

Furthermore, it takes quite a while until the pos tip goes away, which can sometimes be annoying when you need to see the code it's covering.

My .emacs.d is currently at: 50ec30be6dd6be709a742dad51dfb016af1c37f0
My spacemacs config can be found here: https://github.com/romanofski/emacsrc/blob/master/spacemacs
Installed emacs is: emacs-24.5-6.fc23 (on Fedora 23)

I tried to use `customize-variable` to adjust the flycheck relevant bits towards pos-tip but no effect.

**Comment by TheBB** [comment]
This is, if anything, an issue with `flycheck-pos-tip`. Relvant reading: https://github.com/syl20bnr/spacemacs/issues/2110#issuecomment-155156220 and https://github.com/flycheck/flycheck-pos-tip/issues/6. Please report this upstream instead of here.

**Comment by TheBB** [comment]
This was closed upstream.
