### ISSUE TITLE
Default diff margin tool

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#3996]
The new vcs micro-state set `git-gutter+` as the default, I would like to know why this is the case in practice and why the change from `diff-hl`.

The version 0.105 will have a lot of semi-breaking changes I would like to limit the scope, but if `git-gutter+` has really good new feature we can consider it.

**Comment by ralesi** [comment]
@syl20bnr, sorry for not responding.  The primary reason for the old switch was to all staging of the selected hunks while in the buffer.  This functionality was not present in `diff-hl`
