### ISSUE TITLE
org:org-plus-contrib does not tar cleanly into directory

### ISSUE THREAD

**Issue by icymist** [syl20bnr/spacemacs#4000]
I get this error at spacemacs startup. I only have the emacs-lisp, org layers.

installing org:org-plus-contrib... [1/1]An error occurred while installing org-plus-contrib (error: (error Package does not untar cleanly into directory org-plus-contrib-20151123/))

(Spacemacs) --> installing org:org-plus-contrib... [1/1]
Contacting host: orgmode.org:80
Parsing tar file...
Warning: premature EOF parsing tar file

**Comment by rzetterberg** [comment]
I have the same problem but I'm using emacs _without_ spacemacs, so this issue should be unrelated to spacemacs.

**Comment by StreakyCobra** [comment]
Looks like a package downloading/extraction problem yes.

**Comment by rzetterberg** [comment]
Ok, I resolved the problem by actually using the right URL:

```diff
-        ("org" . "http://org-mode.org/elpa/")
+        ("org" . "http://orgmode.org/elpa/")
```

*facepalm*

Here's what I did to try to debug the problem:

Show the list of packages:
```
M-x list-packages
```

Search for `org-plus-contrib` using `C-s`, click on the package to bring up the details. I noticed the detail buffer was filled with HTML, so I thought maybe I had the wrong URL since that should not happen. Lo and behold I was using wrong URL according to http://orgmode.org/elpa.html

I don't think that's the issue for @icymist since the right URL is used in [core-configuration-layer.el](https://github.com/syl20bnr/spacemacs/blob/master/core/core-configuration-layer.el#L28).

**Comment by StreakyCobra** [comment]
Thanks for the feedback. Indeed we are using `orgmode.org` both in `master` and `develop`, so it's not this :-/

**Comment by StreakyCobra** [comment]
@icymist Does it work now? Maybe it was a temporary `orgmode.org` issue…

**Comment by icymist** [comment]
Yep. The problem still persists.

I completely removed Emacs and Spacemacs, reinstalled both again, and finally only enabled the org layer. That was the only change I did in .spacemacs.

See attachments.

![04-dec-15 17-25-07](https://cloud.githubusercontent.com/assets/3083343/11594807/4d80a4f0-9aac-11e5-8240-a739b224196b.png)
![04-dec-15 17-24-06](https://cloud.githubusercontent.com/assets/3083343/11594808/4d9678e8-9aac-11e5-9109-3298f8d21e4d.png)

**Comment by StreakyCobra** [comment]
Can you paste here the result of `SPC h d s`?

**Comment by icymist** [comment]
#### System Info
- OS: windows-nt
- Emacs: 25.0.50.1
- Spacemacs: 0.104.6
- Spacemacs branch: master (rev. 50ec30b)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp org)
```

**Comment by StreakyCobra** [comment]
Sadly I can't reproduce this environment to help further. Emacs 25.0 is not officially supported, and we know there are some problem with it :-)

**Comment by icymist** [comment]
Just a suggestion. Maybe it should be mentioned in the pre-requisites that 25.0 is not supported. It says that 24.4 or higher is recommended. And, 25.0 > 24.4 ;)

**Comment by icymist** [comment]
Issue persists. This is what I have from SPC h d s.

#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.104.6
- Spacemacs branch: master (rev. 50ec30b)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp org)
```

**Comment by StreakyCobra** [comment]
@icymist I created a PR to specify Emacs 25 could be buggy :+1:

For me it seems like a platform problem, and as I don't have any windows I can't help more, sorry. I hope some windows users will take over!

**Comment by justbur** [comment]
@icymist what tar do you have on your machine in the PATH

**Comment by icymist** [comment]
I did not have any tar before. I added \usr\bin from PortableGit to the path. Now, I think that 'tar' is being used.

From cmd.exe, this is what I get.
```
C:\Users\cande>which tar
/usr/bin/tar

C:\Users\cande>tar --version
tar (GNU tar) 1.28

C:\Users\cande>which git
/cmd/git

C:\Users\cande>which git
/cmd/git
```

I am not sure, if the same tar is accessible from emacs. If someone can tell me how to do that, I will report back.

The issue still persists, after the above tar is accessible from cmd.exe.

**Comment by StreakyCobra** [comment]
You can try to look at the `PATH` within emacs `M-: (getenv "PATH")`

**Comment by icymist** [comment]
I do have access to the tar provided by Git (see below).

C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Riverbed\Steelhead Mobile\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Users\cande\Applications\Continuum\Anaconda3;C:\Users\cande\Applications\Continuum\Anaconda3\Scripts;C:\Users\cande\Applications\Continuum\Anaconda3\Library\bin;C:\Users\cande\Applications\Continuum\Anaconda3;C:\Users\cande\Applications\Continuum\Anaconda3\Scripts;C:\Users\cande\Applications\PortableGit\cmd;**\Users\cande\Applications\PortableGit\usr\bin;**C:\Users\cande\AppData\Local\Pandoc\

**Comment by justbur** [comment]
hmm ok. 

This is the only place in the emacs source that I can find that warning
https://github.com/emacs-mirror/emacs/blob/acfb5cd0353406784f085ddb6edfb0d0587048c8/lisp/tar-mode.el#L588-L592

To me that suggests that it's a bad tar file somehow, but it also is not an error. It's just producing a message.

**Comment by icymist** [comment]
Ok. I think I found the issue. The issue might not actually be spacemacs. Can someone give me the full url of the org-plus-contrib package that is being downloaded by spacemacs? I can then verify and report back.

**Comment by justbur** [comment]
@icymist http://orgmode.org/elpa.html is the information and http://orgmode.org/elpa/ is the listing

**Comment by icymist** [comment]
Looks like some access restrictions on my side (see screenshot). I see that when I try to download the package from the browser. So, definitely not an issue from spacemacs. Sorry for the noise.

Either it is the anti-virus (McAfee) or something else, that is blocking access. I will try to figure out. If someone has an idea, please let me know.

![09-dec-15 00-15-39](https://cloud.githubusercontent.com/assets/3083343/11671724/97a389d8-9e0a-11e5-835c-79fe5097df29.png)

**Comment by icymist** [comment]
Just a suggestion. I might have figured out this was the problem if I had access to the full url from the error logged in the 'messages' buffer. Maybe it's a good idea to echo the full url in case of an issue.

**Comment by StreakyCobra** [comment]
The displayed message is not handled by Spacemacs so we can't do anything :-(

It's a `cisco` message, so probably not your machine but the configuration on some parts of your network.
