### ISSUE TITLE
Can we have a lorem ipsum generator in spacemacs by default?

### ISSUE THREAD

**Issue by ikhthiandor** [syl20bnr/spacemacs#4002]

**Comment by TheBB** [comment]
We have one. `SPC i l`. It's in the develop branch for now.

**Comment by ikhthiandor** [comment]
Nice. How about making it a bit more customizable...like how many paragraphs/sentences/lists I want.

**Comment by StreakyCobra** [comment]
It is. `5 SPC i l p` :-)

**Comment by syl20bnr** [comment]
You cal already insert several paragraphs at once with a numeric prefix argument, for instance: `8 SPC i l p` will insert 8 paragraphs.

**Comment by ikhthiandor** [comment]
Oh thanks! Didn't know that. Neat :D This issue can be closed I think.

**Comment by equwal** [comment]
It does not generate Lorem ipsum though (really) so I made a new issue:
https://github.com/syl20bnr/spacemacs/issues/12468
