### ISSUE TITLE
git-gutter warnings in develop

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#4004]
In the `*warnings*` buffer:

```elisp
Error (use-package): git-gutter :init: git-gutter-mode is not currently registered as a minor mode
```

As a result, the gutter on the right now uses characters to display the changes, `+`, `-`, etc.

**Comment by TheBB** [comment]
I'm not getting that warning, but this is not why you get `+` and `-` in the fringe, that's because of https://github.com/syl20bnr/spacemacs/pull/3632. See the new variables in the `version-control` layer for determining which fringe tool to use.

**Comment by synic** [comment]
Ah, I will change the ticket.  I set it to this:

```elisp
     (version-control :variables
                      version-control-diff-tool 'diff-hl)
```

And now I get two warnings:

```elisp
Error (use-package): git-gutter :init: git-gutter-mode is not currently registered as a minor mode
Error (use-package): git-gutter+ :init: git-gutter+-mode is not currently registered as a minor mode
```

However, the git gutter now works like it used to.

**Comment by TheBB** [comment]
Well, I'm not getting the warnings, but I know how to fix them.

**Comment by synic** [comment]
Perhaps this will help?  

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 4d87ea6)
- Distribution: spacemacs
- Layers:
```elisp
(unscroll auto-completion xkcd emacs-lisp git gtags dash yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking
          (version-control :variables version-control-diff-tool 'diff-hl)
          lua colors spacemacs-layouts vimscript
          (c-c++ :variables c-c++-enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by TheBB** [comment]
Can you check if https://github.com/syl20bnr/spacemacs/pull/4007 solves this?

**Comment by synic** [comment]
Yes, it does.
