### ISSUE TITLE
Implement keymap for DocView mode

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#401]
It would be nice to have vim-like keys for DocView mode, or at least hjkl navigation keys.

**Comment by js947** [comment]
:+1:

**Comment by syl20bnr** [comment]
@kini @js947 Available in develop branch, can you test it ?
Corresponding documentation: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.md#docview-mode
