### ISSUE TITLE
Proposal: Enable line numbers with evil-ex

### ISSUE THREAD

**Issue by duerrp** [syl20bnr/spacemacs#4015]
As I am slowly transitioning into the vim-way I start to use `evil-ex` more and more (especially the t-command is super cool). As I don't like to see line numbers all day though, I added a little hack that enables them during ex commands (obviously leaving them on if they are already enabled, and not touching relative / absolute):

```
  (defun show-linum-advice (orig-fun &rest args)
    (let ((before (if global-linum-mode 1 -1)))
      (unwind-protect
          (progn
            (global-linum-mode 1)
            (let ((res (apply orig-fun args)))
              res))
        (global-linum-mode before)
        )))
  (advice-add 'evil-ex :around #'show-linum-advice)
```
If enough people like it, I can prepare a pull request...

**Comment by agzam** [comment]
Wouldn't be better to submit this directly to evil maintainers? https://bitbucket.org/lyro/evil. 
Just asking. I like evil-ex and would love to have this and maybe a few more things there.

**Comment by duerrp** [comment]
Sure, I can try that, but if I understand correctly, the goal of evil is just to emulate vim's behaviour. Do you know if plain vim has this feature?

**Comment by agzam** [comment]
@duerrp what feature? enabling line numbers when you're at the command panel and hiding them when you're back to editor window? Honestly I don't know. I guess it's possible.

**Comment by duerrp** [comment]
@agzam As you suggested, I posted the issue over at evil: https://bitbucket.org/lyro/evil/issues/597/enable-line-numbers-with-evil-ex
