### ISSUE TITLE
Proposal: configurable cache directory

### ISSUE THREAD

**Issue by puzl** [syl20bnr/spacemacs#4018]
I like to keep my .emacs.d in my home directory which is NFS mounted, but I'd like to use a local cache for speed reasons.  Would it be possible to have an override for the cache directory.  I don't mind having to specify it as some custom elisp in a startup script, but obviously it would be cleaner in the .spacemacs file.

**Comment by duerrp** [comment]
I assume you could override `spacemacs-cache-directory` if you do it in your init.el before `(load-file (concat user-emacs-directory "core/core-load-paths.el"))` is called. As far as I remember `defconst` is just a hint, not a real restriction in elisp.

**Comment by puzl** [comment]
I don't want to go editing the init.el in my .emacs.d

**Comment by syl20bnr** [comment]
Did you try to set it in the user-init function of the dotfile ?

**Comment by StreakyCobra** [comment]
@syl20bnr I tried, it works for most of them, but not *all* cached files. Probably there are some cache paths that are defined before `user-init` is called.

**Comment by syl20bnr** [comment]
This is surprising, the call to init and init-user is made pretty early, I'll look into it.

**Comment by StreakyCobra** [comment]
( or maybe I tested, *again*, something in the wrong way :sweat_smile: )

**Comment by puzl** [comment]
So I've moved my entire .emacs.d to the local disk, removed my $HOME/.emacs.d.  Everything seems to work fine but I do get this odd error rigt after initialisation

Loading c:/cygwin-1.7.31-3/home/hjw/.emacs.d/layers/shell/packages.el (source)...done
Loading c:/cygwin-1.7.31-3/home/hjw/.emacs.d/layers/syntax-checking/packages.el (source)...done
Loading //irlcor-fil01/home/hjw/.rcm/spacemacs/hjw/packages.el (source)...done
Loading //irlcor-fil01/home/hjw/.rcm/spacemacs/hjw/extensions.el (source)...done
The variable 'evil-jumper-file' is obsolete.  Persistence is done with 'savehist' now.
Loading c:/cygwin-1.7.31-3/home/hjw/.emacs.d/init.el (source)...done
Loading c:/cygwin-1.7.31-3/home/hjw/.emacs.d/.cache/recentf...done
Start checking for new version...
Open the quickhelp.
**error in process sentinel: async-handle-result: Cannot open load file: no such file or directory, //irlcor-fil01/home/hjw/.emacs.d/core/core-load-paths.el
error in process sentinel: Cannot open load file: no such file or directory, //irlcor-fil01/home/hjw/.emacs.d/core/core-load-paths.el**





I invoke emacs with runemacs.exe -q --load=~/.rcm/spacemacs/init-local.el

and init-local.el looks like:
=====
(load-file (expand-file-name "~/.rcm/spacemacs/hjw/cygwin-emacs.el"))
(load-file (expand-file-name "~/.rcm/spacemacs/hjw/cygwin-mount.el"))
(cygwin-mount-activate)

(setq-default user-init-file "/home/hjw/.emacs.d/init.el")
(setq-default user-emacs-directory "/home/hjw/.emacs.d/")
(load user-init-file)
====

I have to force the cygwinification before loading spacemacs-core because quelpa doesn't work on cygwin properly.

**Comment by pataquets** [comment]
#15499 might be of interest
