### ISSUE TITLE
Trailing blank line is always deleted

### ISSUE THREAD

**Issue by nmk** [syl20bnr/spacemacs#4019]
I would like to have each edited file end with a single trailing blank line. Whenever I save a file, or use `delete-trailing-whitespace`, trailing blank lines are deleted.

This seems to happen in any major mode. I am using the develop branch, pulled this morning.

I have
```
(setq require-final-newline t)
(setq mode-require-final-newline t)
```
in `dotspacemacs/user-config`. If I disable ws-butler mode with `M-x ws-butler-mode` trailing blank lines are left alone. According to the ws-butler README, it should respect `require-final-newline`.

Is there anything special that Spacemacs is doing which is preventing ws-butler from seeing `require-final-newline`? Or is perhaps a case of me putting the above settings in the wrong place?

**Comment by StreakyCobra** [comment]
I think `require-final-newline` is to have a line return at the end of the last *non-empty* line, it doesn't mean to have is a trailing *blank line*.

**Comment by nmk** [comment]
@StreakyCobra You are right! Is there a way to force a trailing blank line though?

**Comment by StreakyCobra** [comment]
I don't know if there is an emacs way, but it will probably be overwritten by `ws-butler` hooks anyway. Maybe @TheBB knows? Otherwise the best is probably to ask `ws-butler` if the can add an option to support this functionality.

**Comment by TheBB** [comment]
I don't think there's a way, other than disabling all whitespace stuff and just doing it yourself. Seems like quite a niche feature request.

**Comment by nmk** [comment]
Alright, thanks for your help.
