### ISSUE TITLE
support ssh in git clone

### ISSUE THREAD

**Issue by co-dh** [syl20bnr/spacemacs#4023]
I got the following error from a dev machine:
fatal: Unable to find remote helper for 'https', 
according to http://stackoverflow.com/questions/8329485/git-clone-fatal-unable-to-find-remote-helper-for-https, 
it's because my git don't have libcurl. 
However, I'm not able to install it on that machine because I'm not super user, and that machine need to keep sync with production machine, so the cost to install package is high.
I'm wondering if we can support ssh if https failed in git clone.

**Comment by StreakyCobra** [comment]
You can try to clone with SSH yes: `git clone git@github.com:syl20bnr/spacemacs.git ~/.emacs.d`

**Comment by co-dh** [comment]
I did that and it works.
The problem is the when I re evaluate .spacemacs, it gives the error message, and failed to eval.

**Comment by StreakyCobra** [comment]
Which error message?

**Comment by co-dh** [comment]
fatal: Unable to find remote helper for 'https',

**Comment by TheBB** [comment]
It would be helpful if you stated in the beginning that this error message originated from within Spacemacs, and when cloning it.
