### ISSUE TITLE
Terminal - Symbol's function definition is void: set-fontset-font

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#4026]
I recently opened Emacs in terminal on OS X and I get the following error message on startup:

```
Warning (initialization): An error occurred while loading `~/.emacs.d/init.el`:

Symbol's function definition is void: set-fontset-font
```

**Comment by TheBB** [comment]
What's your Emacs version?

**Comment by TheBB** [comment]
The one in the terminal, that is.

**Comment by StreakyCobra** [comment]
Do you use `set-fontset-font` function in your `.spacemacs`? Can you try if it happen againg without the `osx` layer? Can you run emacs with the `--debug-init` flag and give us the backtrace here?

**Comment by jupl** [comment]
@TheBB 24.5.1

@StreakyCobra I'm not calling it and yes I am using the `osx` layer which appears to call it in `config.el`. I need it in the terminal for `pbcopy` functionality.

Looks like a PR needs to be done to wrap that call in a conditional with something like `(display-graphic-p)` or `window-system`.

**Comment by StreakyCobra** [comment]
I was asking to try without the `osx` layer to see if the problem was indeed this call to the function, or if it was coming from the core functions.

What is weird is that `set-fontset-font` exists even in terminal version on my computer.

What does `SPC h d v set-fontset-font RET` gives you?

**Comment by jupl** [comment]
Yes the issue is with the `osx` layer which I need in the terminal for `pbcopy`.

`SPC h d v` gives `[No match]`.

**Comment by StreakyCobra** [comment]
Maybe there is some differences between linux and OS x, or some emacs compilation options that are different… I don't know.

**Comment by gowikel** [comment]
I am having exactly the same problem with emacs 27.1 on Mac OS.

Probably, there are differences between Linux and Mac, but, if you anyone is facing the same issue, try to change the font size on the Mac's terminal. From there it works as a charm. It seems that the values of the font are inherited from it instead of being applied by the editor.
