### ISSUE TITLE
python layer on spacemacs v0.104.6

### ISSUE THREAD

**Issue by frank0512** [syl20bnr/spacemacs#4027]
I add the  the 'python' layer in 'dotspacemacs-configuration-layers', but i get the below error message.

pytest.el:68:1:Warning: cl package required at runtime
Compiling no file at Wed Dec  2 09:41:33 2015
Leaving directory `/Users/John/.emacs.d/elpa/pyvenv-20151105.1519'

Compiling file /Users/John/.emacs.d/elpa/pyvenv-20151105.1519/pyvenv-autoloads.el at Wed Dec  2 09:41:33 2015
Entering directory `/Users/John/.emacs.d/elpa/pyvenv-20151105.1519/'

Compiling file /Users/John/.emacs.d/elpa/pyvenv-20151105.1519/pyvenv-pkg.el at Wed Dec  2 09:41:33 2015

Compiling file /Users/John/.emacs.d/elpa/pyvenv-20151105.1519/pyvenv.el at Wed Dec  2 09:41:33 2015

In pyvenv-activate:
pyvenv.el:153:9:Warning: assignment to free variable
    `python-shell-virtualenv-root'

In pyvenv-deactivate:
pyvenv.el:209:9:Warning: assignment to free variable
    `python-shell-virtualenv-root'
pyvenv.el:251:1:Warning: Unused lexical argument `unbound'
pyvenv.el:251:1:Warning: Unused lexical argument `value'
pyvenv.el:251:1:Warning: Unused lexical argument `widget'

**Comment by bmag** [comment]
When installing a new layer, usually Spacemacs also needs to install some new packages. When a package is installed, it is also compiled. What you posted are compilation warnings. These warnings usually can be safely ignored, and so is the case here (maybe the warning for pytest.el should be fixed, though).
You should see warnings like these only when you install or update packages. Do you get these warnings also in other circumstances?

**Comment by TheBB** [comment]
Yes, these are regular compilation warnings when installing packages. They are normal and can largely be ignored. You should have seen many like these when installing Spacemacs for the first time, and similarly each time you update your packages.

**Comment by frank0512** [comment]
I switch spacemacs from master to branch. It worked, thanks
