### ISSUE TITLE
x11 mouse copy & paste fail with emacs -nw

### ISSUE THREAD

**Issue by co-dh** [syl20bnr/spacemacs#4028]
In X windows
* emacs -nw
* select in emacs with left mouse button
* paste to another application with middle mouse button will fail

tested with emacs -nw -Q , this bug does not exists
I noticed that mouse are not handled in -nw -Q version by describe-key
* emacs -nw -Q
* M-x describe-key
* click left mouse
* nothing happen

while in the Non -Q version
* emacs -nw
* SPC h d k
* click left mouse
* it shows down-mouse-1 at that spot runs command evil-mouse-drag-region,

so the spacemacs didn't respect -nw options to not handle mouse event
I also tested with bare emacs + evil, this bug do not exists.

**Comment by TheBB** [comment]
@StreakyCobra and I had a chat on gitter and it turns out you just need to disable it in your `dotspacemacs/user-config` function:

```elisp
(xterm-mouse-mode -1)
```

We can add a FAQ about this.

**Comment by co-dh** [comment]
It works, thank you BB. saved my time and saved my life.

**Comment by StreakyCobra** [comment]
Fixed in ff2b87d
