### ISSUE TITLE
Git time machine keybindings clashing with evil

### ISSUE THREAD

**Issue by rahulmutt** [syl20bnr/spacemacs#4032]
If I use 'SPC g t' to access git timemachine and go back certain commits and want to search within that commit either with C-s or /, I am unable to move between commits anymore. Before search, 'N' means to go to a previous commit in the timemachine microstate. After search, 'N' will take you to previous search results. I think this means by pressing / I have canceled the microstate, but the display of the microstate is still shown below and it permanently stays there even after killing the timemachine buffer. And if I try to revive the microstate by pressing 'SPC g t' again it takes me to the first commit so I have to start all over again.

**Comment by StreakyCobra** [comment]
Try `SPC w b` to refocus the micro mode.

**Comment by nixmaniack** [comment]
This is a bug and I doubt `SPC w b` re-focuses the micro-state. I have had this issue where micro-state was lying around particularly in git-blame-miro-state. There was issue around this IIRC. 

As a workaround, I use `(spacemacs//micro-state-close-window)` to close that annoying window.

**Comment by StreakyCobra** [comment]
Ok, was on my phone so couldn't test :-)

**Comment by syl20bnr** [comment]
I believed I fixed this in develop branch. Are you on master or develop ?

**Comment by nixmaniack** [comment]
On develop I can confirm.

**Comment by d12frosted** [comment]
Should be fixed with latest major release.
