### ISSUE TITLE
Develop version-control micro state throws error when using diff-hl.

### ISSUE THREAD

**Issue by geksilla** [syl20bnr/spacemacs#4034]
I'm using emacs 24.5, spacemacs from develop branch. Got this error when hit <kbd>SPC g .</kbd>

```
let: Wrong type argument: commandp, diff-hl-margin-minor-mode
```

Quick fix that works for me, change **diff-hl-margin-minor-mode** to **diff-hl-margin-mode** in [funcs.el](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bsource-control/version-control/funcs.el)

**Comment by StreakyCobra** [comment]
I don't have this error. Have you something special concerning this in your config?

**Comment by geksilla** [comment]
@StreakyCobra yes, sorry forgot to mention:

```
     (version-control
      :variables
      version-control-diff-tool 'diff-hl)
```

**Comment by jpcirrus** [comment]
I am getting this error with Spacemacs v.0.105.8 with the same config as @geksilla and using `hg` as the VCS.

**Comment by justbur** [comment]
Yep I ran into this too. I fixed it in the hydra pr by the way.

**Comment by justbur** [comment]
#4606

**Comment by geksilla** [comment]
@justbur, cool! Thanks!

**Comment by geksilla** [comment]
Closing this since it was fixed in referenced issue.
