### ISSUE TITLE
LiveScript support?

### ISSUE THREAD

**Issue by immigrantsheep** [syl20bnr/spacemacs#4038]
I've been trying to figure it out but it seems livescript isn't supported out of the box or am I missing something? CoffeeScript works just fine. Any tips? Thank you.

**Comment by jupl** [comment]
If all you need is LiveScript syntax support you can add [`livescript-mode`](https://github.com/bdowning/livescript-mode) to `dotspacemacs-additional-packages`. If more customizations than that are required then code needs to be written and added to the `javascript` layer for a PR.

**Comment by immigrantsheep** [comment]
thank you @jupl 
that's good enough

**Comment by kryptt** [comment]
I wrote my own personal layer for this... 

you might want something like:

```emacs-lisp
(defun web/init-livescript-mode ()
  (use-package livescript-mode
    :defer t
    :init
    (progn
      (add-to-list 'auto-mode-alist '("\\.ls\\'" . livescript-mode))
      (evil-leader/set-key-for-mode 'livescript-mode
        "mc" 'livescript-compile-buffer
        "mC" 'livescript-compile-region
        "mr" 'livescript-repl)
      (add-hook 'livescript-mode-hook '(lambda ()
                                         (setq livescript-command "lsc"))
                ))))
```
to evilify some of the nicer commands...

**Comment by immigrantsheep** [comment]
thank you @kryptt ! this is awesome
