### ISSUE TITLE
[diff] [bindings] N as previous - not working

### ISSUE THREAD

**Issue by adrsta** [syl20bnr/spacemacs#4045]
for example if I press
SPC f e D ?
p is bound to "prefious diff" instead of N

**Comment by StreakyCobra** [comment]
`ediff` is not evilified, so bindings there are traditional emacs one, so `n` for `next` and `p` for `previous`.

I don't think this will change, and getting used to `n` and `p` is not really difficult. Actually this is used on other spacemacs places.

**Comment by jb55** [comment]
Got [codetriage'd](http://www.codetriage.com/syl20bnr/spacemacs) here. What's the word on this? If there are no plans on changing it, can this be closed?

**Comment by syl20bnr** [comment]
codetriage :+1: 

This is not a trivial issue to fix, we can close it for now, I don't see us fixing it in the near future.

**Comment by bmag** [comment]
Actually it's fixed in develop - https://github.com/syl20bnr/spacemacs/commit/2f94ada233d38a39788b1f502b429fe6e75df5ea
Both `N` and `p` are bound to `ediff-previous-difference` for me on develop.

**Comment by adrsta** [comment]
Yes, it's fixed with evil-ediff by justbur

**Comment by syl20bnr** [comment]
Oops sorry, seems that I should not have stopped the test to the point color :-D
