### ISSUE TITLE
Keys are overriden in Helm buffer

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#4047]
With the latest `develop`, Helm key bindings are overridden with evil-leader ones. For example, in `helm-mini` or `helm-find-files` or most Helm commands, `C-c o` is for opening file/buffer in other window. But now, it shows key bindings from evil-leader. I use `C-c` as my leader key for `holy-mode`.

**Comment by justbur** [comment]
@tuhdo if you update bind-map from melpa this issue should be resolved. It no longer overrides keys when in the minibuffer.

**Comment by TheBB** [comment]
Then I will close. :-)

**Comment by tuhdo** [comment]
That fixed it. Thanks.
