### ISSUE TITLE
golden-ratio-mode is incompatible with helm-gtags

### ISSUE THREAD

**Issue by amosbird** [syl20bnr/spacemacs#4048]
There is a bug with `golden-ratio-mode`.  `helm-gtags-dwim-other-window` will create a new window instead of reusing existing one.
![sxov taa wurzbf9_d5c wc](https://cloud.githubusercontent.com/assets/5085485/11556070/663cec1a-99df-11e5-9f54-1669989012f7.png)

**Comment by tuhdo** [comment]
You should report it upstream, so the author can fix it: https://github.com/syohex/emacs-helm-gtags
