### ISSUE TITLE
er/expand-region and C-g to deselect sometimes moves point strangely

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#4049]
I haven't found a clear way to reproduce this, but `spc v` followed by some number of `v` or `V` to grow or shrink region, and then cancel with `C-g`, sometimes leaves the cursor at a seemingly random point. I especially notice this when I start with the point at beginning of line containing an indented sexp, `spc v` should select the first sexp with point at opening paren, and `C-g` should deselect and put me back at beginning of line. However, it sometimes puts me about half a screen up or down, usually at a different opening paren.

**Comment by d12frosted** [comment]
Hey @sooheon 

Thanks for the report. I can easily reproduce it, though not sure how to fix it. To be honest, I never used this functionality before 💃
