### ISSUE TITLE
Elixir layer keybinding error

### ISSUE THREAD

**Issue by Immortalin** [syl20bnr/spacemacs#4055]
I am getting `SPC m is undefined` when using the elixir layer. 

```sh
#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. c9de044)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion emacs-lisp clojure git go python elixir markdown org shell html javascript mu4e)
```

**Comment by mosic** [comment]
Same here. `SPC m` works after running `elixir-mode` manually.

This happens when using only elixir layer too:

> #### System Info
> - OS: gnu/linux
> - Emacs: 24.5.1
> - Spacemacs: 0.105.0
> - Spacemacs branch: develop (rev. 8191a66)
> - Distribution: spacemacs
> - Layers:
> ```elisp
> (elixir)
> ```

**Comment by justbur** [comment]
Possibly related to #4135. Try updating packages

**Comment by mosic** [comment]
@justbur Can confirm, this is fixed now. The issue can be closed @Immortalin?
