### ISSUE TITLE
Pyenv and Spaceline incompability with visual mode

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#4056]
I have a very strange issue.

In Python mode press `SPC m v s` and enable any `pyenv` version other than `system` e.g. `2.7.10` or `miniconda-3.16.0`. After that try `v j j j` or `v k k k`. Visual mode does no longer work for me. Interestingly it does work with `v arrow-keys`.

Visual mode works fine in non-python buffers during this broken state.
Deactivating the virtual environment restores normal visual mode function.
Not installing `spaceline` makes the whole issue go away.

@TheBB tried to reproduce after discussion on Gitter but was not able to on a first attempt.

`SPC t D` shows no errors.

I also tried with all layers but the `python` layer disabled with the same result.

My [.spacemacs](https://github.com/cpaulik/dotfiles/blob/master/.spacemacs.symlink)

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 8191a66)
- Distribution: spacemacs
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip nil)
 chrome c-c++ clojure colors custom_org_config django emacs-lisp emoji erc eyebrowse games
 (git :variables git-gutter-use-fringe t)
 github gnus html ipython-notebook javascript latex lua markdown my-mu4e my_python org org-ipython pandoc spacemacs-layouts pdf-tools
 (python :variables python-enable-yapf-format-on-save nil python-test-runner 'pytest)
 ranger research-config ruby search-engine semantic
 (shell :variables shell-default-shell 'term shell-default-term-shell "/bin/zsh")
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking themes-megapack tmux vagrant version-control yaml)
```

Edit: I've tried this on two machines. One Antergos the other Ubuntu 14.04.

**Comment by StreakyCobra** [comment]
Reproduced here.

**Comment by StreakyCobra** [comment]
Also, `SPC t m t` to hide spaceline is enough to make it work or not.

**Comment by cpaulik** [comment]
I also noticed that it slows my editing down to a crawl. 

Removing the call to `(pyenv-mode-full-path name)` from https://github.com/TheBB/spaceline/blob/master/spaceline-segments.el#L432 solved the issue for me.

**Comment by TheBB** [comment]
Thanks for the fix! Closing.
