### ISSUE TITLE
Spacemacs doesn't open file given as commandline argument

### ISSUE THREAD

**Issue by Immortalin** [syl20bnr/spacemacs#4057]
When ` emacs <file name>` is ran, spacemacs goes directly to the home screen. The file that it was suppose to open shows up in the `Recent Files` section.

```sh
#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. c9de044)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion emacs-lisp clojure git go python elixir markdown org shell html javascript mu4e)
```

**Comment by person808** [comment]
I'm pretty sure its caused by [this](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-spacemacs.el#L83) line. I think doing something like this

```elisp
(unless file-argument-exists
    (switch-to-buffer (get-buffer-create spacemacs-buffer-name)))
```

would work, but I don't know how to detect a file argument (Note: `command-line-args` contains all arguments passed to emacs).

**Comment by choppsv1** [comment]
A work around is to put the following into (defun dotspacemacs/user-config ()...

    (if inhibit-startup-screen
        (quit-window))

**Comment by anakimluke** [comment]
Just letting you know I still get this bug when using the rolling release on emacs 27.1

**Comment by lebensterben** [comment]
@anakimluke 

See https://github.com/syl20bnr/spacemacs/issues/15887
