### ISSUE TITLE
elixir-mode adds extra end in ruby-mode rspec files

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#4059]
Similar to #644, but the fix applied for that does not appear to work in rspec files. It is unclear what is triggering `ruby-end-mode`, removing the `rspec-mode` package does not help. Commenting out the two autoload hooks in `ruby-end-mode` does not help.

![end](https://cloud.githubusercontent.com/assets/8588/11596061/c357e688-9a67-11e5-8397-6b49bc04b0df.gif)

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 8191a66)
- Distribution: spacemacs
- Layers:
```elisp
(better-defaults emacs-lisp markdown syntax-checking
                 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle)
                 erlang elixir git dash html org colors spacemacs-layouts osx github javascript react deft floobits ruby semantic unimpaired
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking ranger)
```

To repro, open a file with the suffix `_spec.rb`

**Comment by robbyoconnor** [comment]
This happens is ALL mode ruby files -- it's so weird. I usually saw the error correct itself usually -- I dunno WHY it happens

**Comment by abernardes** [comment]
Yep, I leave the elixir package commented out in my config file when editing Ruby, otherwise it keeps adding and extra `end`. :cry:

**Comment by grassdog** [comment]
I see this too. Have also commented out elixir mode in the meantime.

**Comment by robbyoconnor** [comment]
This is super annoying and happens regardless of `elixir` being present or not

**Comment by Layzie** [comment]
I have same problem in `*.rb` files. But I commented out `elixir` layer then no extra `end` too...

**Comment by robbyoconnor** [comment]
Did anybody report upstream?

**Comment by aaronjensen** [comment]
To where?

**Comment by robbyoconnor** [comment]
https://github.com/elixir-lang/emacs-elixir

**Comment by aaronjensen** [comment]
I don't think it is their problem. The elixir layer includes the ruby-end package and attempts to disable it for ruby but fails.

**Comment by robbyoconnor** [comment]
hmm That's why I didn't report it -- I wasn't 100% sure it's their problem...I'd love to debug this but I don't even use it so it's one less thing spacemacs has to load

**Comment by aaronjensen** [comment]
The problem is that this doesn't work: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/elixir/packages.el#L138-L139

/cc @syl20bnr

**Comment by TheBB** [comment]
It works, it just doesn't do enough. Those hooks are autoloaded so turning them off in the config phase is too late. But since they are also inserted at load time, they have to be turned off in both phases, init and config.

Please see if https://github.com/syl20bnr/spacemacs/pull/4349 fixes your problem.

**Comment by aaronjensen** [comment]
@TheBB Thanks, that seemed to fix it. Once I tested it on your branch, however, I could no longer repro it on develop. I'm sure there's something I don't understand going on--some sort of load order race condition or compiled layer cache or something. Maybe @robbyoconnor can test your fix as well just to verify it makes a difference. Thanks!

**Comment by TheBB** [comment]
Based on what I can see, on develop you should get `ruby-end-mode` only in the first ruby file you open, and only if that file is opened before any elixir files.

**Comment by aaronjensen** [comment]
@TheBB that was it. I can repro on develop but not on your branch. :shipit: Thanks!
