### ISSUE TITLE
stacking-highlights bindings no longer present

### ISSUE THREAD

**Issue by Xyc0** [syl20bnr/spacemacs#4060]
https://github.com/syl20bnr/spacemacs/blob/afa537d3414fa786d4b7ccd1d2678ff69bade287/doc/DOCUMENTATION.org#stacking-highlights

unbound in master

**Comment by nixmaniack** [comment]
The feature was disabled because of the bug in `hl-anything`. https://github.com/syl20bnr/spacemacs/issues/2529

**Comment by Xyc0** [comment]
The referenced leader key has been assigned to helm.
