### ISSUE TITLE
There is no mention of where to put the configuration bits

### ISSUE THREAD

**Issue by dstcruz** [syl20bnr/spacemacs#4061]
In the documentation of the javascript layer, under the "Configuration" header, there is no mention of where one should put the settings mentioned there. It is not clear where settings for packages loaded by a layer should be set by the user.

**Comment by robbyoconnor** [comment]
in `dotspacemacs/user-config` in your `.spacemacs`

**Comment by StreakyCobra** [comment]
Closing as the fix has been merged in 0.105.9
