### ISSUE TITLE
Configuration Java Layer in Mac

### ISSUE THREAD

**Issue by zhexuany** [syl20bnr/spacemacs#4064]
I was wondering how many mac users get this layer work? Even I started use this layer since the beginning of its creation, but I never get eclim work. If there is someone can get this layer work, can you tell me how to add correct codes to make it work?

**Comment by shwsun** [comment]
Well, I am able to make it running, but I am not a heavily Java programmer. What I can say is that, Eclim and keybindings in Spacemacs are both working fine. 

Few tips:
**To get eclim running**
```brew cask install eclipse-java```
```git clone git://github.com/ervandew/eclim.git```
```cd eclim```
```ant -Declipse.home=/opt/homebrew-cask/Caskroom/eclipse-java/4.5.2/Eclipse.app/Contents/Eclipse```
**And of cause, you need to change the path in ```dotspacemacs/user-config```**

**Comment by nixmaniack** [comment]
If it's not clear in docs, what @shwsun has mentioned should go in docs.

**Comment by jachaf6746** [comment]
This was very helpful. Slight update - by default, the latest version of Cask will now automatically move apps to the application folder (see [here](https://caskroom.github.io)), so if you've updated after Aug 11, 2016, `ant -Declipse.home=/Applications/Eclipse.app/Contents/Eclipse` will likely be your command.
