### ISSUE TITLE
J bound to org-shiftdown in Org mode

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#4072]
The `J` key is getting bound to `org-shiftdown` in Org mode, which is annoying as `J` is used for joining lines in Vim/Evil.

**Comment by syl20bnr** [comment]
Indeed I encountered it, I will revert the commit that introduces it.

**Comment by syl20bnr** [comment]
Done :-)

**Comment by jrmiller82** [comment]
Thanks for fixing this one. Was driving me nuts a few minutes ago until I updated spacemacs.
