### ISSUE TITLE
Packages not be installed in user-emacs-directory/elpa

### ISSUE THREAD

**Issue by zwb-ict** [syl20bnr/spacemacs#4076]
I'm using lastest develop branch, I load spacemacs's init.el as below:

```
(setq user-emacs-directory "~/.space.d/")
(add-to-list 'load-path "~/.space.d/")
(message user-emacs-directory)
(load "init")
(message user-emacs-directory)
 ```

All things works very well, but I find all packge installed into "~/.emacs.d/elpa" not "~/.space.d/elpa".
So if I set  **dotspacemacs-delete-orphan-packages** to true, spacemacs will delete my own packages.

My os is Mac OS X 10.11
Emacs's version 24.5 (installed with brew)

**Comment by deb0ch** [comment]
Status on this ? Can you still reproduce the bug ?

**Comment by d12frosted** [comment]
`dotspacemacs-delete-orphan-packages` (now `dotspacemacs-install-packages`) is not related to elpa location. You can configure package installation dir by changing value of `package-user-dir`. 

Closing this as old issue. If you need any help with it, just let me know 😸
