### ISSUE TITLE
Large ⓚ spoils powerline on Gnome 3

### ISSUE THREAD

**Issue by nagi** [syl20bnr/spacemacs#4078]
When a `ⓚ` is displayed on the powerline, it looks like this:

![big-k](https://cloud.githubusercontent.com/assets/1297635/11613281/1c132178-9c13-11e5-901b-b3ec90ac0621.png)

When I left click the ⓚ, and click `Turn Off minor mode`, then the powerline looks good again.

Here is a little system information:

![about](https://cloud.githubusercontent.com/assets/1297635/11613295/c3526fe8-9c13-11e5-80d7-f1e0d3d818c9.png)

#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.104.6
- Spacemacs branch: master (rev. 50ec30b)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 ruby-on-rails spell-checking syntax-checking version-control)
```

P.S. When I checkout origin/develop, the `ⓢ` has the same problem:
![s](https://cloud.githubusercontent.com/assets/1297635/11613407/f27d9510-9c16-11e5-8872-6cee7b79655d.png)

**Comment by dilas** [comment]
On Debian 8.2 (jessie), i just installed the `unifont` package and everything its fine now (as the user TheBB pointed out on issue #1012 - install a good unicode fallback). :grinning:

![image](https://cloud.githubusercontent.com/assets/86712/12188685/c79eaca2-b59e-11e5-9233-8815bce96a36.png)

**Comment by TheBB** [comment]
Thanks @dilas for pointing this out. I will close this as a duplicate and try to use #1012 for this popular problem.
