### ISSUE TITLE
`helm-M-x` doesn't show results at first

### ISSUE THREAD

**Issue by bjarkevad** [syl20bnr/spacemacs#408]
When using `helm-M-x` no results are shown before a few characters have been input.
I've only been able to reproduce this bug on Arch Linux, whereas it works fine on OS X. 

To reproduce:
- `SPC :`
- Observe that the helm buffer list is empty
- Type something (e.g. `iel`)
- Observe that the buffer list gets filled

Emacs version is 24.4.1.

**Comment by syl20bnr** [comment]
Are you sure that Arch Linux was 24.4.1 ? There are bleeding edge packages on Arch Linux so I won't be surprised that it is a 25.x release.

I don't see this behavior on Windows 7, OS X Yosemite and Ubuntu 14.04 so I don't know what I can do. You should post the issue on the helm repo. as well.

**Comment by bjarkevad** [comment]
Completely sure yes. :) Arch does indeed run bleeding edge, but not packages that are not considered stable (e.g. Emacs development versions).
I'll look into the issue and try to find the culprint.
I just noticed that `helm-M-x` behaves correctly when using `emacs -nw`, so I have a place to start looking.

**Comment by bjarkevad** [comment]
So I tried reinstalling again, and now it magically works. Will close the issue for now.

**Comment by syl20bnr** [comment]
@bjarkevad I had issues with helm in the past when upgrading it, several times I had to wipe out `helm` directory from `elpa` to fix it. The behavior I had is that the first item of the list was not selected, I always had to press down arrow. Reinstalling always fixed the issue.

If it happens again after an upgrade, open a ticket in the helm repo to get useful feedback.

**Comment by priyadarshan** [comment]
You may also check this https://github.com/emacs-helm/helm/issues/789
