### ISSUE TITLE
Elfeed hijacking bookmarks

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#4087]
Elfeed is hijacking bookmarks.

Reproduce:

1. Start `elfeed`.
2. Switch to another buffer.
3. Set a bookmark in that buffer.

Expected: New bookmark points to current file of buffer.
Actual: Bookmark points to elfeed search buffer.

I think triggering elfeed's autoload causes this.

This is on develop branch.

**Comment by syl20bnr** [comment]
Need investigation to know if this should be reported upstream or not.

**Comment by darkfeline** [comment]
This only started happening when I switched from my personal elfeed layer to the newly introduced elfeed layer.  In particular, that layer adds `elfeed-org` and `elfeed-goodies`.  Will investigate further.
