### ISSUE TITLE
fresh checkout of `develop` fails

### ISSUE THREAD

**Issue by agriffis** [syl20bnr/spacemacs#4097]
I just tried a fresh checkout of develop:

```
rm -rf .emacs.d
mv .spacemacs .spacemacs.mine
git clone --recursive https://github.com/syl20bnr/spacemacs .emacs.d
cd .emacs.d
git checkout develop
```

and first run of emacs fails with `error: Package spacemacs-theme- is unavailable`:

![screenshot from 2015-12-07 11-07-45](https://cloud.githubusercontent.com/assets/50637/11631979/c76b5ada-9cd2-11e5-8bdd-4100946e59ea.png)

This is ec8250ea1de9b2cd2f1439432e9eddf3d476b7fc with 24.5.1 on Fedora 23

**Comment by agriffis** [comment]
I bisected and found that 61707e593d4dc84b15be102ef415808e0512f2f8 introduced the problem.

**Comment by agriffis** [comment]
Here's the full backtrace:
```
Debugger entered--Lisp error: (error "Package `spacemacs-theme-' is unavailable")
  signal(error ("Package `spacemacs-theme-' is unavailable"))
  error("Package `%s-%s' is unavailable" spacemacs-theme "")
  package-compute-transaction(nil ((spacemacs-theme)))
  package-install(spacemacs-theme)
  (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg)))
  (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)
  (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)))
  (let ((warning-minimum-level :error)) (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append ...) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir))))
  spacemacs/load-or-install-package(spacemacs-theme)
  (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (spacemacs/load-or-install-package pkg))) (if (or (eq (quote moe-light) theme) (eq (quote moe-dark) theme)) (progn (load-file (concat pkg-dir "moe-light-theme.el")) (load-file (concat pkg-dir "moe-dark-theme.el")))) (add-to-list (quote custom-theme-load-path) pkg-dir))
  (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (spacemacs/load-or-install-package pkg))) (if (or (eq (quote moe-light) theme) (eq (quote moe-dark) theme)) (progn (load-file (concat pkg-dir "moe-light-theme.el")) (load-file (concat pkg-dir "moe-dark-theme.el")))) (add-to-list (quote custom-theme-load-path) pkg-dir))) (t (let ((pkg (spacemacs//get-theme-package theme))) (spacemacs/load-or-install-package pkg))))
  (if (memq theme (custom-available-themes)) nil (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (spacemacs/load-or-install-package pkg))) (if (or (eq (quote moe-light) theme) (eq (quote moe-dark) theme)) (progn (load-file (concat pkg-dir "moe-light-theme.el")) (load-file (concat pkg-dir "moe-dark-theme.el")))) (add-to-list (quote custom-theme-load-path) pkg-dir))) (t (let ((pkg (spacemacs//get-theme-package theme))) (spacemacs/load-or-install-package pkg)))))
  spacemacs/load-theme(spacemacs-dark)
  (let ((default-theme (car dotspacemacs-themes))) (spacemacs/load-theme default-theme) (setq configuration-layer--protected-packages (append (delq nil (mapcar (quote spacemacs//get-theme-package) dotspacemacs-themes)) configuration-layer--protected-packages)) (setq-default spacemacs--cur-theme default-theme) (setq-default spacemacs--cycle-themes (cdr dotspacemacs-themes)))
  spacemacs/init()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %d or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat user-emacs-directory "core/core-load-paths.el")) (if init-file-debug (progn (require (quote core-debug)))) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/aron/.emacs.d/init.el" nil t)  ; Reading at buffer position 1165
  load-with-code-conversion("/home/aron/.emacs.d/init.el" "/home/aron/.emacs.d/init.el" t t)
  load("/home/aron/.emacs.d/init" t t)
  #[0 "\205\262
```

**Comment by StreakyCobra** [comment]
It's the commit I expected :/

**Comment by syl20bnr** [comment]
@agriffis Are you behind a proxy ?

**Comment by syl20bnr** [comment]
@agriffis do you have an existing `.spacemacs` ? Try with `dotspacemacs-elpa-https` set to `nil`.

**Comment by StreakyCobra** [comment]
It's not the first one having this problem: https://gitter.im/syl20bnr/spacemacs?at=566017089a969fd24f3c4a8a

**Comment by syl20bnr** [comment]
I cannot reproduce it, in 3 different environments, except the https issue behind my corporate proxy.

**Comment by StreakyCobra** [comment]
Maybe it's because of the selected theme, or because the `themes-megapack` layer is not enabled?

**Comment by syl20bnr** [comment]
This is the default theme, I have the exact same error if I use https, setting `dotspacemacs-elpa-https` to nil fixes the issue but... the default value is `t`...

**Comment by agriffis** [comment]
I'm not behind a proxy and I've moved my `.spacemacs` aside. But if there's a certs issue, I wonder if it's distro-specific

**Comment by agriffis** [comment]
Huh, new info: it only happens with the GUI version on Fedora `emacs-24.5-6.fc23.x86_64` and not the terminal-only version (compiled without GUI libs) `emacs-nox-24.5-6.fc23.x86_64`

**Comment by agriffis** [comment]
Setting `dotspacemacs-elpa-https` doesn't seem to change anything.

Launching the GUI binary of emacs with `-nw` also fixes the problem, so it's not a difference in the binaries, but rather a difference in the initialization sequence with the GUI enabled.

**Comment by syl20bnr** [comment]
@agriffis thanks for the feedback, I changed the way elpa repositories availability is checked, it may fix this issue, can you test again a fresh install of spacemacs in a GUI with the last develop ?

**Comment by agriffis** [comment]
@syl20bnr Working now! Tested a few times and couldn't make it fail.

**Comment by syl20bnr** [comment]
@agriffis excellent! So I suspect that the issue was that `request.el` was trying to use curl behind the scene and for some reason in GUI it was not available. I removed the unnecessary dependence on `request.el` and used the builtin `url.el` of Emacs instead. Glad that it works, thank you for testing.

**Comment by syl20bnr** [comment]
@StreakyCobra :joy:

**Comment by dptd** [comment]
@syl20bnr Where / how do you set dotspacemacs-elpa-https to nil? I checked out master branch and have the same issue. However I am behind the corporate proxy. Cannot find this symbol anywhere.

**Comment by StreakyCobra** [comment]
@dptd This change is only in `develop` for now. It will be in the next release.

In `master` [repositories are set on `http`](https://github.com/syl20bnr/spacemacs/blob/master/core/core-configuration-layer.el#L27-L29)

**Comment by dptd** [comment]
@StreakyCobra I was afraid of that... Thanks for the fast reply.

**Comment by roman** [comment]
I'm having this issue inside a vagrant machine :-(, it works if branch out v0.104.8

**Comment by StreakyCobra** [comment]
@roman Have you tried running emacs with the `--insecure` flag?

**Comment by noncom** [comment]
Same issue, Windows 7 platform. Just today I had a successful spacemacs installation on another Windows 7 machine (on my job). At home now I am having this problem. Launching with `--debug-init` gives the same info as quoted above, in the 3rd post. Launching with `--insecure` fixes the issue, spacemacs begins its normal initialization. Both spacemacs and emacs versions are the latest available.

**Comment by intel-iot-roadshow** [comment]
I can confirm that I'm also having this same issue on Windows 7.

**Comment by GingaNinja** [comment]
I've got a feeling that for windows, this might be an issue to do with command line tools on your environment. The install only seems to be working on my mingw environment on Windows 7. Powershell, dos prompt, and git for windows must be using a bad version of something - curl perhaps?

**Comment by noncom** [comment]
@GingaNinja Hmm.. well, Windows does not even have curl by default... Don't know..But why then `--insecure` helps? Or rather it helped the first time. Now I cannot replicate the success on the same machine :/

**Comment by GingaNinja** [comment]
Yep, I too have found that --insecure helps. I had other issues which meant that it was easier to delete ~/.emacs.d/elpa first, so that it re-installed all the packages. Then using --insecure worked, even from a powershell prompt.

**Comment by zhexuany** [comment]
@syl20bnr https://github.com/syl20bnr/spacemacs/issues/6701 This issue may be related.

**Comment by anmoljagetia** [comment]
@zhexuany Thanks. Can't seem to reproduce this as well 😞
But this sure is related to the problem I am facing. I'll follow up with all the changes and progress I make here.

Thanks 👍
