### ISSUE TITLE
`dotspacemacs/sync-configuration-layer` disable fullscreen when `dotspacemacs-fullscreen-at-startup` enabled

### ISSUE THREAD

**Issue by rach** [syl20bnr/spacemacs#4100]
When I reload my config and I had fullscreen enabled and `dotspacemacs-fullscreen-at-startup` to `t` then it exit the fullscreen on OSX

**Comment by TheBB** [comment]
Thank you, but this is a known bug: https://github.com/syl20bnr/spacemacs/issues/1088.

**Comment by nixmaniack** [comment]
Yes it's a bug! There's a fix, it's now time to get it in!

**Comment by TheBB** [comment]
I *know*, I *know*. :-P

**Comment by rach** [comment]
Sorry for the duplicate. Thanks for letting me know
