### ISSUE TITLE
Dired motions gg and G

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#4104]
In Dired, the Vim motions gg and G are overridden with Dired commands.

This is problematic as 1. Dired is in Normal state and 2. a user who instinctively uses those motions is frustrated by unexpected behavior.

**Comment by mahinshaw** [comment]
The afoermentioned motions work for me. @darkfeline  is this still an issue for you?

**Comment by darkfeline** [comment]
Still experiencing it, although I've gotten used to using `M-<`,  `M->`.  I've stopped using Spacemacs as of late, so getting a reproduction and debug is not high on my list.  If no one else can reproduce, maybe we should close this.

**Comment by ElessarWebb** [comment]
I have the same problem on develop. "G" motion open a ChGrp helm menu. "gg" seems to do nothing.

**Comment by darkfeline** [comment]
That sounds like the behavior I was experiencing.  I suspect "gg" is running the default dired refresh command (which is bound to "g") twice.
