### ISSUE TITLE
Rust "Suspicious state from syntax checker rust-cargo" error

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#4109]
Hello, getting this error when cargo project has more than 1 binary.

```
Suspicious state from syntax checker rust-cargo: Checker rust-cargo returned non-zero exit code 101, but no errors from output: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target

Checker definition probably flawed.
```

**Comment by TheBB** [comment]
Probably upstream problem.

https://github.com/flycheck/flycheck-rust

**Comment by lunaryorn** [comment]
It has already been reported, see flycheck/flycheck-rust#16.

**Comment by ccmtaylor** [comment]
seems like this was fixed upstream in https://github.com/flycheck/flycheck-rust/commit/e802d78a509bd8927464d29e1a8ba8ea355f6ea1

**Comment by robbyoconnor** [comment]
Typically, these kinds of errors are the fault of upstream and not us -- typically either it can't find the executable because your `PATH` is borked or something else that is the fault of upstream.

**Comment by TheBB** [comment]
Okay, closing. :+1:
