### ISSUE TITLE
Suggestion: use `inverse-video` for region highlighting

### ISSUE THREAD

**Issue by bjarkevad** [syl20bnr/spacemacs#411]
Having ` '(region ((t (:inverse-video t))))` in `.spacemacs` greatly improves visibility of selected regions when using darker themes. If this was the default, themes would have equal contrast between selected and unselected regions.

Thoughts?

**Comment by kini** [comment]
Unless the visibility issues are spacemacs-specific, wouldn't it make sense to report them to the theme authors?

**Comment by syl20bnr** [comment]
May be accepted as a dotfile variable, something like `dotspacemacs-force-inverse-colors-for-selection` ?

**Comment by syl20bnr** [comment]
I close this because it is a function of the user theme.
