### ISSUE TITLE
flycheck-pos-tip throws error in console emacs

### ISSUE THREAD

**Issue by gigawhitlocks** [syl20bnr/spacemacs#4111]
When running Spacemacs in the console, Flycheck emits an error when the cursor is placed over a bug it has detected in code.

The error displayed is the following:
```Flycheck error display error: (error Window system frame should be used)```

This appears to emanate from the `flycheck-pos-tip` package, which I've excluded in my `.spacemacs` file to allow flycheck to work normally as a workaround, but this issue should probably be tracked down and either reported upstream and/or worked-around within Spacemacs so that this does not occur by default.

**Comment by StreakyCobra** [comment]
If the package is excluded it shouldn't happen :-/ It's probably on our side.

**Comment by gigawhitlocks** [comment]
It's included by default. I merely excluded it in my personal config as a workaround (and wanted to document that for anyone who winds up here from Google)

**Comment by StreakyCobra** [comment]
Oh sorry, I understood it was still happening after excluding it.

**Comment by gigawhitlocks** [comment]
Nope, excluding the package fixed the issue. If the issue is happening upstream, fixing it from Spacemacs' perspective may be as simple as detecting whether the user is running emacs in console & not loading `flycheck-pos-tip` in that case.

**Comment by StreakyCobra** [comment]
Yes I got it. I remember having seen a discussion about this somewhere, but I can't find it back right now.

**Comment by gigawhitlocks** [comment]
Awesome, just wanted to be sure y'all were aware :+1:

**Comment by CestDiego** [comment]
There is a PR by @travisbhartwell that addresses this I think: https://github.com/syl20bnr/spacemacs/pull/2652

**Comment by StreakyCobra** [comment]
This issue "follows" a recent change in the library explained here: https://github.com/syl20bnr/spacemacs/issues/2110#issuecomment-155156220

@CestDiego It happens even when not in daemon mode, so it's not linked to this PR.

@lunaryorn It seems `pos-tip` doesn't support non-GUI frame and throws an error. Do we need to handle this on Spacemacs side, or is it better to solve it in `flycheck-pos-tip` directly? I suppose it's better to handle it in `flycheck-pos-tip` (or even `pos-tip`?) as in daemon mode there can be both Terminal & GUI on the same instance.

**Comment by lunaryorn** [comment]
@StreakyCobra I think that flycheck-pos-tip should not fail on TTYs.  I can't show a popup either, though, because pos-top is explicitly about GUI tooltips.  And I don't want to use popup.el as fallback, lest I introduce all those display issues again that I hoped to fix by moving back to pos-tip.

I think it'd be best to fall back to the standard echo area display, but make the fallback customisable.

Please open an issue in flycheck-pos-tip.

**Comment by nixmaniack** [comment]
Fallback to echo area is be better. On my remote ssh session where I don't have display, there as well I hit similar issue. I skipped using flycheck-pos-tip and added following for a workaround.
```
(setq flycheck-display-errors-function 'flycheck-display-error-messages-unless-error-list)
```

**Comment by StreakyCobra** [comment]
Reported upstream: https://github.com/flycheck/flycheck-pos-tip/issues/11

**Comment by StreakyCobra** [comment]
This issue has been fixed upstream one hour ago, and the update will be available on MELPA in a few hours (3-4). Let us know if this is the problem still persist after the update.
