### ISSUE TITLE
evil normal state substitute problem

### ISSUE THREAD

**Issue by ltn614** [syl20bnr/spacemacs#4114]
I was try to add a line number to each line of my text file like I did in Vim by use:
:%s/^/\=line(".") . ". "/g
then I get this msg "Expected @ after \=" and my substitute operation didn't work out.
Am I missing something or this thing didn't work as well as vim.

**Comment by d12frosted** [comment]
Hey @ltn614 

Sorry for the long silence. It would be nice to have more information about how exactly you are trying to achieve your goal. For example, which function / command you use to substitute.
