### ISSUE TITLE
How do I make helm-swoop to open at bottom with full window width? 

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#4117]
At present, helm-swoop opens helm buffer at the bottom of the same buffer when there is (literal) vertical split.

```
+---------+---------+
|         |         |
|         |  point  |
|         |         |
|         +---------+
|         |  helm   |
|         |  swoop  |
+---------+---------+
```

I want it to behave like normal helm buffers where it opens at bottom with any window configuration. I tried understanding `spacemacs-helm-display-buffer-regexp` which currently controls this behaviour according to [this](https://www.reddit.com/r/emacs/comments/345vtl/make_helm_window_at_the_bottom_without_using_any/) but couldn't get it working with helm-swoop(which I assumed should've worked for helm-swoop in the first place)

**Comment by justbur** [comment]
Try this
```elisp
(setq helm-swoop-split-window-function 'spacemacs//display-helm-window)
```

**Comment by nixmaniack** [comment]
Awesome! Thanks @justbur. That solved it.
