### ISSUE TITLE
Support Emacs lisp keybindings in Clojure mode

### ISSUE THREAD

**Issue by aaronkavlie-wf** [syl20bnr/spacemacs#4124]
Emacs lisp has some [useful keybindings](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#emacs-lisp-specific-key-bindings) like "go to end of line and evaluate last sexp" that are absent from the Clojure mode keybindings.

**Comment by bmag** [comment]
Some of these bindings already exist, see here: https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/clojure/packages.el#L215
I see that Clojure is missing `e l` and `e $` (both mean "go to end of line and evaluate last sexp"), and `e c` ("evaluate current form"). Did you have more bindings in mind?

**Comment by aaronkavlie-wf** [comment]
The "go to end of line" bindings are the ones I noticed missing. Didn't have any other specifics in mind, just bring it to parity with the elisp bindings  :-)

**Comment by duianto** [comment]
The following PRs changes have been applied to the develop branch:
[clojure] Add goto end of line eval sexp function and keybindings #13320
