### ISSUE TITLE
Package deletion failing on OSX with trash installed via Homebrew

### ISSUE THREAD

**Issue by shanesveller** [syl20bnr/spacemacs#4125]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 98c0702)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp osx)
```

#### Summary

I decided to dip my toes into `develop` again, and am seeing a repeat of the `Mac error -1700` portion of [this closed GitHub issue](https://github.com/syl20bnr/spacemacs/issues/3570). It may also be related to [this open issue](https://github.com/syl20bnr/spacemacs/issues/3302)
I'm on OSX 10.11.1, Emacs 24.5.1 from Homebrew `emacs-mac` as recommended. I do not see this behavior on the current released version (`v0.104.6`), and didn't see any changes to `configuration-layer/delete-orphan-packages` or `configuration-layer//package-delete` that seemed relevant or even recent in git-blame. I do not see this behavior if the `osx` layer isn't enabled in my `.spacemacs` file, but it similarly doesn't appear to have any recent/relevant changes.

`exec-path` within Emacs appears to match my shell `$PATH`, and `trash` is installed via brew, such that `which trash` gives the expected output.

This appears to affect the functionality of `configuration-layer/rollback` as well.

**Comment by shanesveller** [comment]
Possibly worth noting that this appears to only effect Emacs in the terminal, but the GUI version might be working as intended? I will work on a minimal `$PATH` value to see if that makes a difference.

**Comment by StreakyCobra** [comment]
Can you try excluding the `exec-path-from-shell` and try again?

**Comment by shanesveller** [comment]
@StreakyCobra Thanks for the suggestion, but that does not appear to help. If I manually install an orphan package, exclude `exec-path-from-shell` and make sure it's absent, the next time I start emacs I still get the `Mac error -1700` behavior if the `osx` layer is enabled.

**Comment by StreakyCobra** [comment]
Ok. I've tried at least :wink: I'm not an OS X guy, so I'll let other people handle this one :-)

**Comment by lazywei** [comment]
How's this going?

**Comment by shanesveller** [comment]
@lazywei I'm not good enough with elisp yet to pursue finding a fix on my own, but I've tried excluding packages, etc. and the only thing that helped me personally was either staying on master/release tag or checking out the `osx` layer from master after pulling from `develop`. I'm happy to help test/debug further if someone else has time to look into it.

**Comment by shanesveller** [comment]
@StreakyCobra is there anything I can do without skill in elisp to help troubleshoot this error further? Happy to help any way I can.

**Comment by StreakyCobra** [comment]
Let's try calling some OS X people :-)

@d12frosted My dear, would you mind trying to help?

**Comment by wicliff** [comment]
Still having issues with this, tried different solutions for last one week. Not able to upgrade/change packages because of this problem 

`Removing old name: Mac error -1700`

brew trash is installed. I have removed trash and reinstalled again just to be sure.

Config:
Spacemacs - 0.105.1
Emacs - Installed through brew install emacs-mac

**Comment by lazywei** [comment]
My temporary and stupid workaround is commenting out osx before upgrading...
Praveen Wicliff <notifications@github.com>於 2016年1月5日 週二，下午4:25寫道：

> Still having issues with this, tried different solutions for last one
> week. Not able to upgrade/change packages because of this problem
>
> Removing old name: Mac error -1700
>
> brew trash is installed. I have removed trash and reinstalled again just
> to be sure.
>
> Config:
> Spacemacs - 0.105.1
> Emacs - Installed through brew install emacs-mac
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/4125#issuecomment-168933060>
> .
>
-- 
Chih-Wei (Bert)

**Comment by wicliff** [comment]
@lazywei - Thank you. That works
Commented out OSX layer, reloaded spacemacs. 
Upgraded packages. 
Enabled OSX again.

**Comment by yeongsheng-tan** [comment]
Confirmed the above as well.
Steps taken:
1. remove osx layer
2. exit spacemacs
3. startup spacemacs
4. perform package upgrade
5. WORKS!!!
6. exit spacemacs
7. startup spacemacs
8. re-enable osx layer
9. exit and re-enter spacemacs

**Comment by shanesveller** [comment]
I've been using `git checkout v0.104.8 layers/osx` after each version update to use the old `osx` layer behavior.

**Comment by shanesveller** [comment]
The very kind @davoclavo came up with the following solution that fixed my problems!

> First make sure you have `trash` installed doing `which trash` if not, install it via `brew install trash` or `brew install oxsutils` (I installed `osxutils`).. then add this to your `user-init`:

```elisp
 (if (executable-find "trash")
      (defun system-move-file-to-trash (file)
        "Use `trash' to move FILE to the system trash.
Can be installed with `brew install trash', or `brew install osxutils`''."
        (call-process (executable-find "trash") nil 0 nil file))
    ;; regular move to trash directory
    (setq trash-directory "~/.Trash/emacs"))
```
Here's some extra explanation:
> Basically whenever a file has to be deleted, the `system-move-file-to-trash` function is called at some point, I don't really understand where it is defined, but it fails when trying to delete a folder, which is what spacemacs does when removing a plugin

> Before adding that fix, in order to replicate this issue in a smaller scale, create an empty folder... eg. `mkdir ~/Desktop/test_folder` and then eval this `(move-file-to-trash "~/Desktop/test_folder")` by writing it in a file and positioning your cursor at the end of the line and press `,ee` (which calls `eval-last-sexp`), it should show you the same error message (-1700 error blah blah)

I personally used `brew unlink trash && brew install osxutils`, and tested the fix by restarting and disabling/enabling a few layers.

Thanks again, @davoclavo!

**Comment by yeongsheng-tan** [comment]
Awesome. Seems to work nicely in my user-config:
`(if (executable-find "trash")
      (defun system-move-file-to-trash (file)
        "Use `trash' to move FILE to the system trash.
Can be installed with `brew install trash', or `brew install osxutils`''."
        (call-process (executable-find "trash") nil 0 nil file))
    ;; regular move to trash directory
    (setq trash-directory "~/.Trash/emacs"))`

**Comment by ivar** [comment]
Just a note - I still had this issue on spacemacs 0.105.21
I solved it by commenting the `osx` layer, restarting emacs, updating my packages, then reinstating the `osx` layer.
Since this is likely to come up for other users, would it make sense to include the `if (executable-find "trash")..` script directly in the `osx` layer ?
