### ISSUE TITLE
`SPC :` not working after some updates

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#4127]
After some updates I see this when pressing `SPC :`:

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "helm-command")
  autoload-do-load((autoload "helm-command" "Preconfigured `helm' for Emacs commands.\nIt is `helm' replacement of regular `M-x' `execute-extended-command'.\n\nUnlike regular `M-x' emacs vanilla `execute-extended-command' command,\nthe prefix args if needed, are passed AFTER starting `helm-M-x'.\n\nYou can get help on each command by persistent action.\n\n(fn ARG &optional COMMAND-NAME)" t nil) helm-M-x)
  command-execute(helm-M-x)
```

It would be nice to have it fixed so I can use `restart-emacs` when upgrading.

**Comment by nixmaniack** [comment]
I think this is the case where `helm` is updated and by default if there's update to the package it's directory is deleted and replaced with the upgraded one. This will also come up if `restart-emacs` get updated where you won't be able to use it. 
I don't know of a solution, so it'd be nice if someone can suggest a solution.

**Comment by magthe** [comment]
Well, `SPC q r` continues to work, I'm guessing that's good enough :)

**Comment by don-han** [comment]
I actually have the same error. @magthe Did you get to resolve it? It gives me "Cannot open load file: no such file or directory, helm-command" error. Also, in the org-mode, if I try `t` in `org-mode`, it executes `evil-find-char-to`, instead of `org-todo`. I am not sure if two are related, so I will open an issue for the latter problem.

**Comment by don-han** [comment]
Actually, nevermind. Restarting emacs solved the problem. It started installing packages, but it's odd since I have already restarted it several times before. Oh well.

**Comment by d12frosted** [comment]
Closing this issue in favour of #6583.
