### ISSUE TITLE
pyenv related error

### ISSUE THREAD

**Issue by ikhthiandor** [syl20bnr/spacemacs#4129]
I am getting this error when I mouse click on a Python(flask) file.

>error in process sentinel: Can't create /home/ikhthiandor/.emacs.d/.cache/anaconda-mode/0.1.1 >directory(in Messages buffer)

>emacs: /home/ikhthiandor/.pyenv/versions/bin/python: No such file or directory(in ananconda-mode buffer)

The directory structure is different in my system for pyenv.
It's like this
/home/ikhthiandor/.pyenv/versions/3.5.0/bin

pyenv version: 20151105
OS: Manjaro Linux
Spacemacs: 0.105.0(develop branch)

**Comment by cpaulik** [comment]
What is your `PATH` variable inside emacs? You can get it with `SPC : getenv`. 

Mine starts like this 

```
/home/cp/.pyenv/plugins/pyenv-virtualenv/shims:/home/cp/.pyenv/libexec:/home/cp/.pyenv/plugins/python-build/bin:/home/cp/.pyenv/plugins/pyenv-virtualenv/bin:/home/cp/.pyenv/plugins/pyenv-update/bin:/home/cp/.pyenv/plugins/pyenv-installer/bin:/home/cp/.pyenv/plugins/pyenv-doctor/bin:/home/cp/.pyenv/shims:/home/cp/.pyenv/bin
```

**Comment by ikhthiandor** [comment]
My PATH inside emacs is 
>/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/smlnj/bin

But PATH inside gnome-terminal is different.
>/home/ikhthiandor/.pyenv/shims:/usr/bin:/opt/android-sdk/tools:/opt/android-sdk/platform-tools:/opt/android-sdk:/opt/android-ndk-r10d:/home/ikhthiandor/Downloads/cocos2d-x-cocos2d-x-3.4/templates:/home/ikhthiandor/Downloads/cocos2d-x-cocos2d-x-3.4/tools/cocos2d-console/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/smlnj/bin:/home/ikhthiandor/.local/bin::/usr/lib/node_modules:/home/ikhthiandor/.pyenv/bin

Anyway, this is after I've updated my PATH environment variable. I longer see the errors after the update. You can see the history if interested here.

https://github.com/ikhthiandor/vcsh_zshenv/commits/master

I'll now check if I can work with pyenv without any further issues.

**Comment by ikhthiandor** [comment]
Closing this issue since I'm no longer getting error with pyenv. Not really sure what changed.
