### ISSUE TITLE
Visible whitespace in some spacemacs buffers.

### ISSUE THREAD

**Issue by 526avijitgupta** [syl20bnr/spacemacs#4140]
Recently I had changed my `.spacemacs` config for some whitespace settings, since then I am encountering this problem.

![screenshot from 2015-12-11 04 10 17](https://cloud.githubusercontent.com/assets/7583815/11730771/2a68494e-9fbd-11e5-8078-ec65c02b44a8.png)

A possible solution would be to remove the whitespace rather than hiding it, since fellow developers may also face such problems if they manually change their whitespace settings like I did!

**Comment by StreakyCobra** [comment]
The bottom part is `which-key`, and it's probably @justbur who can do something about it.

The right window is magit, it should probably be reported upstream. I'll wait for @justbur confirmation because it *may* be due by `evil-magit` (but I'm pretty sure not ;-) )

**Comment by justbur** [comment]
I'm not going to remove the white space but I can add a hook that's run when the buffer is created so you can disable any mode you want in that buffer. 

That's also not an evil magit problem but I doubt it's worth reporting upstream. You need to disable that mode in the buffers you don't care about or conversely only enable it in the buffers you do care about. 

By the way don't you think it would be helpful to tell us what your settings actually are?

**Comment by justbur** [comment]
Added a `which-key-init-buffer-hook` just now. It will take a couple hours or so to update on melpa

**Comment by tuhdo** [comment]
I agree with @justbur. You should just enable `whitespace-mode` in the buffers that you actually care, not the unnecessary buffers that are used for read-only purpose. The magit menu text is automatically generated, so I double it's worth to add extra logic to remove spaces at the end.

**Comment by 526avijitgupta** [comment]
@justbur @StreakyCobra @tuhdo  Thanks. Solved my issue by removing the whitespace settings altogether and enabling `whitespace-mode` only in a few buffers.
