### ISSUE TITLE
init is defined for dired+, but not loaded

### ISSUE THREAD

**Issue by s3bs** [syl20bnr/spacemacs#4141]
The spacemacs layer defines  spacemacs/init-dired+ [here](https://github.com/syl20bnr/spacemacs/blob/50ec30be6dd6be709a742dad51dfb016af1c37f0/layers/%2Bdistribution/spacemacs/packages.el#L468)

But dired+ is not listed in `spacemacs-packages` so it is not loaded. 
I guess either remove the init or add the package....

**Comment by syl20bnr** [comment]
Nice catch!
I'm for removing it.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
