### ISSUE TITLE
ws-butler messes my indentation

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#4143]
In addition to killing trailing whitespaces, it also changes the indentation format i.e. tabs -> spaces. Sometimes my commit got messed up because I was editing `.patch` file, and it converts all my tabs to spaces. Should not be enabled by default imo.

**Comment by StreakyCobra** [comment]
This should probably be reported upstream, I suppose it's not an intended behaviour.

**Comment by nixmaniack** [comment]
If ws-butler is changing tabs -> spaces then it shouldn't have done that which is bug then and should be reported upstream. Also I think it does that change based on `indent-tabs-mode` in which case need customization variable at upstream. 

But keeping this default sounds quite sane IMO!

**Comment by TheBB** [comment]
I haven't seen any other reports on this and @tuhdo appears not to be interested in reporting upstream, so I'm closing this.

**Comment by lewang** [comment]
https://github.com/lewang/ws-butler/issues/25
