### ISSUE TITLE
projectile-enable-caching, set it to nil by default

### ISSUE THREAD

**Issue by gabor** [syl20bnr/spacemacs#4147]
hello,

here:
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs-base/packages.el#L1192-L1193
the index-method is set to alien, and caching is enabled. but if you check this comment:
https://github.com/syl20bnr/spacemacs/issues/1256#issuecomment-96982146

"The caching exists mostly for the benefit of people using native indexing, as it's pretty slow."

could we default to have the caching disabled, when we use the 'alien' method?

the way i got to here to write this issue was this problem: spacemacs was unable to find a file in the repository (by using the space-p-f shortcut). i started googling and found out that probably the cache is incorrect, so i could just remove the cache, or disable it, then i've found that for the 'alien' method no caching is probably needed, so i am here writing this issue :)

**Comment by StreakyCobra** [comment]
It has been corrected in `develop`: #3802

**Comment by gabor** [comment]
oh, i see. sorry, i assumed `master` is where things are developed, did not check `develop`. how long does it take for my spacemacs install to get the changes from `develop`?

**Comment by StreakyCobra** [comment]
It depends on the progress, on the availability of the maintainer, etc. so I don't really know. Anyway you can give a try to `develop`, it's kind of stable if you are not updating your branch too often :-)
