### ISSUE TITLE
Spacemacs no longer compatible with Emacs 24.3

### ISSUE THREAD

**Issue by bral** [syl20bnr/spacemacs#415]
Due to paradox dropping compatibility with 24.3

Correct me if I'm wrong.

Reference: https://github.com/milkypostman/melpa/pull/2392

Upon updating Spacemacs with Emacs 24.3,
Spacemacs would stall on installing the paradox package and not recover.

Updating to Emacs 24.4 resolved this issue.

It states that Spacemacs is compatible with 24.3 and 24.4 here: 
https://github.com/syl20bnr/spacemacs#emacs-version

**Comment by syl20bnr** [comment]
Reopen due to wrong push.
