### ISSUE TITLE
Pinning specific packages to alternative repository?

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#4165]
Make it easier to set packages which are to be installed from melpa-stable (or org elpa, or smth else even) - there is no information on where to put those, while attempts to do so by usual ways fail

As @grammati [said in gitter](https://gitter.im/syl20bnr/spacemacs?at=566c9283187e75ea0e485cbf)

> user-init is too early (package-archives not defined), and 
> user-config is too late (already got an error about melpa-stable not being an archive)

Of course one could hijack spacemacs files to inject those settings at appropriate part of loading process, but we better do so collectively :)

**Comment by a13ph** [comment]
#3034 might be relevant, but I can't wrap my head around whether it is

**Comment by a13ph** [comment]
[Old solution](https://github.com/syl20bnr/spacemacs/issues/2057#issuecomment-137960576) doesn't seem to work anymore

> package-archives is undefined in dotspacemacs/init

**Comment by a13ph** [comment]
I actually think this should be reported upstream to be handled by Paradox itself, since it [will have](http://endlessparentheses.com/new-in-emacs-25-1-archive-priorities-and-downgrading-packages.html) or already has archive priorities and downgrading - very close features

**Comment by gfZeng** [comment]
I found most Clojure developer need this feature. We need use stable cider

**Comment by tonylotts** [comment]
See the temporary fix for #6531 as an example of how to pin CIDER.
