### ISSUE TITLE
Any plans to have gitlab support?

### ISSUE THREAD

**Issue by ikhthiandor** [syl20bnr/spacemacs#4174]
relevant package https://github.com/nlamirault/emacs-gitlab

**Comment by cpaulik** [comment]
Have you tried it? I was not able to connect to any of the gitlab CE instances I have access to.

**Comment by ikhthiandor** [comment]
Sorry for late reply. I didn't test the package earlier. I've been able to get it work today for the gitlab.com edition(gitlab-host "https://gitlab.com") though. 

Here is a screenshot.

http://i.imgur.com/N5k1d51.png

Note: The repo was private earlier. (I've only one repo in Gitlab now.) So when I ran M-x helm-gitlab-projects at first it showed nothing. I made the repo public but had to restart and M-x gitlab-login then M-x helm-gitlab-projects to see the repo listed.

**Comment by ikhthiandor** [comment]
Oops I closed the issue by mistake :angry:

**Comment by paynito** [comment]
so, I guess that I could put this in a private layer, but not into ~/.spacemacs??

    (defun dotspacemacs/user-config ()
      "Configuration function for user code.
    This function is called at the very end of Spacemacs initialization after
    layers configuration. You are free to put any user code."

      (unless (package-installed-p 'gitlab)
        (package-install 'gitlab))

**Comment by cpaulik** [comment]
@paynito If you want to just install the gitlab package from melpa you can put it in `dotspacemacs-additional-packages` 

Have you read https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org ? It should explain layers.

For my testing of gitlab I made a private layer using `M-x configuration-layer/create-layer` with the following `packages.el`

```
(setq gitlab-packages
    '(
      ;; package names go here
      gitlab
      ))

;; List of packages to exclude.
(setq gitlab-excluded-packages '())

;; For each package, define a function gitlab/init-<package-name>
;;
(defun gitlab/init-gitlab ()
  "Initialize my package"
  (use-package gitlab
    :defer t
    :init
    (setq gitlab-host "HOST"
          gitlab-username "USERNAME"
          gitlab-token-id "TOKEN"))
  )
```

**Comment by syl20bnr** [comment]
Closing in favor of more recent issue: https://github.com/syl20bnr/spacemacs/issues/7687
