### ISSUE TITLE
dot and C-v repeat are broken in hybrid mode

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#4177]
Even for evil-specific commands. 

Switching to vim-style - and everything works

as per @mysyljr [gitter question](https://gitter.im/syl20bnr/spacemacs?at=566e6912cffd648a05555483)

**Comment by justbur** [comment]
Not that I'm aware of. Would be nice to have steps to reproduce...

**Comment by a13ph** [comment]
I'll get back to it as soon as elpa's back. For now, quote from that chat

mysyljr Dec 14 2015 10:02
> I use hybrid mode and ctrl-v choose multiple lines and shift-i, when I put ", I got "", so I ctrl-f and backspace, the result is that other line just repeat " backspace, without ctrl-f
if I use [right] instead of ctrl-f ,the same

a13ph Dec 14 2015 10:06
> honestly, i don't understand how do you repeat
with dot? (.)

mysyljr Dec 14 2015 10:08
> yes, just like dot
ctrl-v I
dot broken too, the same

**Comment by justbur** [comment]
ok, the first bit has nothing to do with repeat and it's working correctly for me
```
one
two
three
```
`<escape> gg C-v jjj$ I " C-f <backspace> <escape>` gives me
```
"one
"two
"three
```
as expected. I also checked `.` and it inserts a new column of double quotes as expected.

**Comment by justbur** [comment]
of course the paired quotes are coming from smartparens so the above assumes that smartparens is on.
