### ISSUE TITLE
org-mode laggy with large file

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#4178]
If I open the spacesmacs doc org file then then the system runs very slowly.

I get lag using the movement keys and things such as helm-find-files takes a while to open etc.

If I switch to a different workspace then the lag goes etc.

**Comment by Andre0991** [comment]
It might have to do with line numbers.

Does it get better when you disable them?

**Comment by fatlazycat** [comment]
Yeah thanks that solved it. Is there a way to disable linum mode just for org-mode ?

**Comment by StreakyCobra** [comment]
This is a way (in your `user-config`):
```
(add-hook 'org-mode-hook (lambda () (spacemacs/toggle-line-numbers-off)) 'append)
```

**Comment by fatlazycat** [comment]
Thanks, should this be left open or you have this recorded elsewhere, nothing to be done etc ?

Thanks again !

**Comment by TheBB** [comment]
(add-hook 'org-mode-hook 'spacemacs/toggle-line-numbers-off 'append)

Better... no need to wrap single functions in lambdas. :-)

Can probably close this, linum is a known performance criminal and no solution has been forthcoming for years. It's at least not our problem.

**Comment by StreakyCobra** [comment]
> Better... no need to wrap single functions in lambdas. :-)

Wait, what do I have this in my config :fearful: ?

**Comment by fatlazycat** [comment]
Hmm that appears to turn off line numbers globally, can you just disable for org-mode ?

**Comment by StreakyCobra** [comment]
It doesn't for me, but maybe it's because I'm on `develop`.

**Comment by fatlazycat** [comment]
Yeah same here with develop. Thanks
