### ISSUE TITLE
Don't override dotspacemacs-leader-key in info-mode

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#4180]
Currently pressing `SPC` for me scrolls the page.

**Comment by justbur** [comment]
I did `C-h i` then `SPC` and the leader bindings are there

**Comment by luxbock** [comment]
You are right. Not sure if I should close this, or keep it open to prod someone to make this the default when opening info files.

**Comment by justbur** [comment]
I don't understand what you mean. When are the key bindings not there for you?
