### ISSUE TITLE
Docview have a strange yellow line

### ISSUE THREAD

**Issue by fewtime** [syl20bnr/spacemacs#4189]
Spacemacs version: 0.104.7

When reading PDF file in Emacs, zooming in the PDF, there is a yellow line shown in the screen.

I use _(turn-on-fci-mode)_ in my dotspacemacs, is it caused this situation?

![Yellow line](http://i4.tietuku.com/0f4edf9ade94ca54.png)

**Comment by cmr** [comment]
I can't seem to reproduce this, with or without fci.

**Comment by d12frosted** [comment]
@fewtime could you please try with latest Spacemacs and latest packages (don't forget to update them)?

**Comment by d12frosted** [comment]
Closing this as potentially fixed. Let us know if you still experience this issue.
