### ISSUE TITLE
C-c P S S should be bound to helm-projectile-ag

### ISSUE THREAD

**Issue by bgvianyc** [syl20bnr/spacemacs#4192]
Given that projectile-ag is already accessible using other methods including `SPC-/` it seems intuitive to bind helm-projectile-ag to C-c P S S instead of projectile-ag given that helm-projectile-ag has no default keybinding.

**Comment by TheBB** [comment]
We don't really mess around with the default Emacsy keybindings, as a matter of principle.

**Comment by bgvianyc** [comment]
I could be wrong, however I believe is should become bound to helm-projectile-ag when helm-projectile is enabled, which it is by default in spacemacs.

**Comment by syl20bnr** [comment]
As @TheBB said we do not setup `C-c` key bindings.
