### ISSUE TITLE
Haskell layer - Wrong type argument listp

### ISSUE THREAD

**Issue by Superpat** [syl20bnr/spacemacs#4194]
So I'm trying spacemacs out and liking what I'm seeing. But while I have been able to activate the layers for c, html and others, I still cant make haskell work, whenever I try to add it to the layers it starts compiling and then ends with an error.

    Wrong type argument: listp, "/home/patrick/.emacs.d/layers/auto-completion/snippets"

If this is an error in the auto completion layer why does it only popup when activating haskell?

**Comment by syl20bnr** [comment]
Do you have anything snippet related in your dotfile ?

**Comment by Superpat** [comment]
dotspacemacs-configuration-layers
       '(
        ;; ----------------------------------------------------------------
        ;; Example of useful layers you may want to use right away.
        ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
        ;; <M-m f e R> (Emacs style) to install them.
        ;; ----------------------------------------------------------------
        auto-completion
        better-defaults
        emacs-lisp
        git
        markdown
        syntax-checking
        html
         c-c++
         colors
         ;; org
         ;; (shell :variables
         ;;        shell-default-height 30
         ;;        shell-default-position 'bottom)
         ;; spell-checking
         ;; version-control
         )


    (defun dotspacemacs/user-init ()
      "Initialization function for user code.
    It is called immediately after `dotspacemacs/init'.  You are free to put any
    user code."
      (setq-default dotspacemacs-configuration-layers '(haskell))
      (setq-default dotspacemacs-configuration-layers
                    '((haskell :variables haskell-enable-ghc-mod-support t)))
      )

**Comment by StreakyCobra** [comment]
@Superpat Can you paste here the result of `SPC h d s`?

@d12frosted Maybe you can have a look at this one.

**Comment by d12frosted** [comment]
Yeah, `SPC h d s` could be helpful. I am on develop (latest update - 3 days ago) and don't see any problems.

**Comment by Superpat** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.7
- Spacemacs branch: master (rev. 878f517)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown syntax-checking html c-c++ colors haskell)
```

**Comment by Superpat** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.8
- Spacemacs branch: master (rev. 44d4525)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown syntax-checking html c-c++ colors scheme rust php csharp)
```

**Comment by d12frosted** [comment]
So when you have `(auto-completion better-defaults emacs-lisp git markdown syntax-checking html c-c++ colors scheme rust php csharp)` layers enabled you don't have any problems, but when you enable `haskell` layer the problem appears? Do I understand it right?

**Comment by Superpat** [comment]
Exactly

**Comment by d12frosted** [comment]
@Superpat does this problem still persist after upgrading to latest Spacemacs release and all packages?

**Comment by Superpat** [comment]
I've since reformated my computer and have been using neovim, so I cant
say right now. Sorry!

**Comment by d12frosted** [comment]
No worry. Waiting for you to return to Spacemacs :D 

But for now I am closing this issue. If you ever encounter it again, let us know. 💃 😸 

Cheers
