### ISSUE TITLE
Incorrect set-up of environment variables

### ISSUE THREAD

**Issue by ethanluoyc** [syl20bnr/spacemacs#4195]
I am starting Spacemacs from the teriminal, which I use Conda as a package manager.

Conda allows me to change my python environment similar to that of Virtualenv. It dose this by changing the PATH variable. 

When I start the GUI Spacemacs after I checked out a particular virtual env from Conda, the changes to the PATH variable is reflected in the terminal, however, it is not observed in the GUI Spacemacs.

I tried to use GUI Vanilla Emacs and it works correctly.

**Comment by ethanluoyc** [comment]
I have figured out the problem is due to `exec-from-shell-path` which sets the env to be the same as that of the **initial** shell environment, please close this issue

**Comment by syl20bnr** [comment]
If you report it upstream we can keep this issue open to track it (post the link back in this thread).

**Comment by ethanluoyc** [comment]
I think this is similar to the problem found in https://github.com/purcell/exec-path-from-shell/issues/34. This is one of the edge case of wanting to have different PATH in interactive and non-interactive shell.

I guess we should see how the upstream issue goes.

**Comment by purcell** [comment]
That's not the same issue. In this case, you simply don't want to be using `exec-path-from-shell` at all.

**Comment by TheBB** [comment]
Yep, if you need this kind of functionality, exclude the `exec-path-from-shell` package.
