### ISSUE TITLE
Very long hangs when loading specific file

### ISSUE THREAD

**Issue by landaire** [syl20bnr/spacemacs#4196]
I'm on the latest dev (78bdfd0b0ed73e3b2b96dfdaa9d77f5ed6d8226b) and when trying to load [this file](https://github.com/D-Programming-Language/dmd/blob/master/src/doc.d) emacs severely hangs and uses 100% CPU. Really all I have to do to trigger it now is restart emacs, select doc.d from the recent files, and let it hang. It didn't hang the first time I opened it but after performing some project searches and trying to modify a line it would hang. In my log below my main buffer (status I guess?) I can see it loads yas-snippet and then hangs.

I only got it to break out of the hang once. Not sure what was different that time but it lasted about 30s.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 78bdfd0)
- Distribution: spacemacs
- Layers:

``` elisp
(emacs-lisp version-control d go rust elixir swift yaml latex markdown auto-completion osx spacemacs-layouts)
```

**Comment by landaire** [comment]
Renaming the parent directory (the dmd git repo root) and re-opening the file seems to have fixed it. Is there another cache besides projectile cache? I tried clearing that originally with no luck.

**Comment by landaire** [comment]
This has *something* to do with the d layer itself I think. I disabled all plugins and loading the file worked. I enabled all but D, still worked. Enabled it and it hangs.

**Comment by landaire** [comment]
Alright, finally narrowed it down. It's a combination of having the `syntax-checking` and `d` layers active. If I enable the `d` layer by itself, no problem. If I enable both `d` and `syntax-checking` it must *really* dislike that file and just decides to kill emacs.

**Comment by StreakyCobra** [comment]
I can reproduce it, so it's not only your config. Also just having the `d` layer alone make this problem appears. Can you also test to be sure it's really the case?

**Comment by landaire** [comment]
I just disabled all packages and the file loaded successfully. Enabled the `d` layer and that file breaks. I haven't found any other files that cause the same behavior (although I haven't really been actively looking).

**Comment by StreakyCobra** [comment]
So we need to find out what is causing the problem. There is only a few packages of code in the `d` layer. As it's also happening without other layers, there is only the `d-mode` packages that is activated in this case.

I don't know how to be sure if it is an upstream issue or not, but it looks like so.

**Comment by landaire** [comment]
I reported the issue in the `emacs-d-mode` repo as shown above, but in the meantime I've also done some profiling. Is this info useful?

<img width="1280" alt="screen shot 2015-12-20 at 16 12 59" src="https://cloud.githubusercontent.com/assets/1313522/11921071/27a0ea98-a735-11e5-9e5e-c20dca49a36e.png">

**Comment by TheBB** [comment]
So if you turn off line numbers, is it faster?

**Comment by landaire** [comment]
Not really. I noticed a very slight speed increase when I'm in the file trying to make changes it still has delays like crazy to where it's unusable for anything serious. When loading the file I let it load for about 20 seconds before just hitting `C-g`.
