### ISSUE TITLE
helm-do-grep is removed

### ISSUE THREAD

**Issue by kvaneesh** [syl20bnr/spacemacs#4197]
https://github.com/emacs-helm/helm/wiki#faq

https://github.com/emacs-helm/helm/commit/013ee11b695f52c68b0a0648dbd143b3592e2ef3

**Comment by StreakyCobra** [comment]
I'm not sure if there is any impact on Spacemacs, as we are using `helm-do-grep-1` and this one hasn't been removed.

**Comment by kvaneesh** [comment]
for me space s f started giving error

**Comment by StreakyCobra** [comment]
Not on my side. Can you paste here the result of `SPC h d s`?

**Comment by kvaneesh** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop-track (rev. d0fe3113679c)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp gtags notmuch dash helm-git-grep helm-ls-git
            (git :variables magit-revision-insert-related-refs nil magit-revision-show-xref-buttons nil magit-backup-mode nil)
            eyebrowse)
```

And this is the error i get

helm-read-file-name: Symbol's value as variable is void: helm-do-grep-preselect-candidate

**Comment by justbur** [comment]
@StreakyCobra try with `SPC sgf ` I think it should be. `SPC sf` selects the first took it finds.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/4308

**Comment by StreakyCobra** [comment]
@justbur Indeed, `SPC s f` is selecting `ag`, I should have though about this.
