### ISSUE TITLE
SPC f f doesn't work in a yaml buffer

### ISSUE THREAD

**Issue by danielwuz** [syl20bnr/spacemacs#420]
For some reason, `SPC f f` doesn't work in yaml buffer, while it works fine in other buffers.  I got an error message as below:
```
spacemacs//ido-vertical-define-keys: To bind the key M-RET, use "\M-\r", not [M-RET]
```

Just to open an issue to remind myself.

**Comment by syl20bnr** [comment]
I'm pretty sure that `yaml` mode has an advice that perturbs `ido`.

**Comment by syl20bnr** [comment]
oh... it is in the define-keys ido setup hook.... very weird.
