### ISSUE TITLE
Error enabling Flyspell mode

### ISSUE THREAD

**Issue by angel1a** [syl20bnr/spacemacs#4202]
I have seen this in https://github.com/syl20bnr/spacemacs/issues/9.

Is it seems to be wrong again? Or there is a problem with my configuration but I don't know how to fix it?

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 3507bc7)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp osx chinese
                 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers nil)
                 (git :variables git-magit-status-fullscreen t)
                 (ranger :variables ranger-show-preview t)
                 org c-c++ python spell-checking syntax-checking)
```

* *message*

Loading /Users/lihaoxuan/.emacs.d/core/core-load-paths.el (source)...done
Loading /Users/lihaoxuan/.spacemacs...done
Mark set
Loading /Users/lihaoxuan/.emacs.d/.cache/spacemacs-buffer.el (source)...done
Open the quickhelp.
Loading /Users/lihaoxuan/.emacs.d/layers/+distribution/spacemacs/config.el (source)...
Loading /Users/lihaoxuan/.emacs.d/layers/+distribution/spacemacs-base/funcs.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+distribution/spacemacs-base/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+distribution/spacemacs-base/keybindings.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+window-management/spacemacs-layouts/funcs.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+window-management/spacemacs-layouts/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+distribution/spacemacs/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/auto-completion/funcs.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/auto-completion/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/better-defaults/funcs.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/better-defaults/keybindings.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+lang/emacs-lisp/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/osx/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/osx/keybindings.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/chinese/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/colors/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+source-control/git/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/org/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+lang/c-c++/funcs.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+lang/c-c++/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+lang/python/funcs.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+lang/python/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/spell-checking/funcs.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/spell-checking/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/syntax-checking/funcs.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/syntax-checking/config.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+window-management/spacemacs-layouts/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+distribution/spacemacs-base/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+distribution/spacemacs/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/auto-completion/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/osx/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/chinese/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/colors/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/colors/extensions.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+source-control/git/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+tools/ranger/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/org/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/org/extensions.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+lang/c-c++/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+lang/python/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/+lang/python/extensions.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/spell-checking/packages.el (source)...done
Loading /Users/lihaoxuan/.emacs.d/layers/syntax-checking/packages.el (source)...done
Starting new Ispell process ispell with default dictionary...
Error enabling Flyspell mode:
(Searching for program no such file or directory ispell)
Spacemacs is ready.

**Comment by StreakyCobra** [comment]
You have to install `ispell` and be sure it is in your `$PATH`.

**Comment by angel1a** [comment]
Thanks ^^
