### ISSUE TITLE
Spacemacs hangs under normal usage (moving the cursor, etc)

### ISSUE THREAD

**Issue by auser** [syl20bnr/spacemacs#4208]
I've been using spacemacs for the past year and have had very few issues, but when reseting my spacemacs to head and reseting my `.spacemacs` file, all of a sudden I get 'hiccups' when moving the cursor where spacemacs pauses and hangs briefly until it can "catch" up. It basically renders spacemacs useless for development right now. Has anyone else experienced this problem?

`SPC h d s`:
#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.104.7
- Spacemacs branch: master (rev. 878f517)
- Distribution: spacemacs
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp html yaml dockerfile lua osx
                 (clojure :variables clojure-enable-fancify-symbols t)
                 colors themes-megapack)
```

My emacs port was installed via Homebrew: 

`brew install emacs --HEAD --use-git-head --cocoa --srgb`

Any ideas?

**Comment by StreakyCobra** [comment]
Do you have the possibility to try emacs 24.5 with the same config? We know there are some problems on emacs 25, it may be the case here.

**Comment by auser** [comment]
Thanks for the suggestion/idea @StreakyCobra 

When running on 24, I get the following error (I think this is a helm error?)

```
byte-code: Symbol's function definition is void: eieio-make-class-predicate
```

**Comment by StreakyCobra** [comment]
Hum, can you try to move (or remove) the `~/.emacs.d/elpa` folder, byte-compiled code could be different between versions.

**Comment by auser** [comment]
@StreakyCobra Unfortunately it doesn't fix it. I ended up recompiling/reinstalling everything and the problem still persists.

**Comment by StreakyCobra** [comment]
Yes, when installing another emacs version it's better to recompile all bytecode files because it may be incompatible. Removing the `elpa/` dir force redownload and recompilation of packages, but you can also do: `M-: (byte-recompile-directory package-user-dir nil 'force)`

**Comment by auser** [comment]
@StreakyCobra Okay, after a complete uninstall/reinstall, the problem _still_ exists. 

I've noticed that it happens _after_ I `Cmd+Tab`. It exists on both 25 and 24.

**Comment by StreakyCobra** [comment]
Clojure + Emacs 25 + OS X :wink: Nothing that I'm using, so I don't know how to help more, sorry :pensive:

**Comment by voeler** [comment]
I had considerable lag in spacemacs for pretty much any input. Finally, after disabling minor modes one by one, I found that flycheck caused the issue. After disbling spacemacs is really responsive. I'd sugggest trying a similar approach to isolate the issue. See also  #1114.

**Comment by xetra11** [comment]
Hey guys,

I also have those "hiccubs". Mostly when I'm navigating down/up for a while. I switched to Use `M+g g` to jump directly to a line number but that's not always the best solution for me.

**System Info:**

OS: Linux Mint
Emacs: 24.5.1
Spacemacs: spacemacs-0.105.22
Spacemacs branch: master 
Distribution: spacemacs
Layers:
-      html
-      java
-      auto-completion
-      search-engine
-      better-defaults
-      emacs-lisp
-      latex
-      c-c++
-      extra-langs
-      git
-      markdown
-      org
-      rust
-      javascript
-      syntax-checking
-      version-control

**Comment by voeler** [comment]
@xetra11 Did you try disabling the syntax-checking layer (flycheck)? Alternatively disable all layers and see if the problem persists.

**Comment by CMCDragonkai** [comment]
I'm getting as well, but I don't have the flycheck, and I'm running emacs 64 bit on Windows 10.
