### ISSUE TITLE
How do I make spacemacs/helm-persp-switch-project to open at bottom with full window width? 

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#4210]
Similar to https://github.com/syl20bnr/spacemacs/issues/4117

I tried wrapping the [function body](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+window-management/spacemacs-layouts/funcs.el#L101-L119) after `(interactive "P")` in
```elisp
(let ((helm-display-function spacemacs//display-helm-window))
  ...function body..
  )
```
But it errored out with following.
```
Debugger entered--Lisp error: (void-function nil)
  nil("*Projectile Layouts*")
  helm-display-buffer("*Projectile Layouts*")
```

**Comment by TheBB** [comment]
You have to quote `spacemacs//display-helm-window` probably.

**Comment by nixmaniack** [comment]
Tried quoting it, although now I don't see the error but helm behaviour is same and it doesn't open full width at bottom.

**Comment by nixmaniack** [comment]
I'm not exactly sure what might have fixed this but now I get full width helm buffer for this function at bottom. The only addition I have right now is `window-purpose` layer (which at the moment is in PR).
