### ISSUE TITLE
Javascript Layer - jsbeautify editorconfig conflicts

### ISSUE THREAD

**Issue by gregpardo** [syl20bnr/spacemacs#4211]
This might be out of scope since editorconfig is not a layer anymore.

This issue is that when editorconfig is being used jsbeautify I believe editorconfig configuration should override whatever default jsbeautify indents and formatting are. Looking for input and thoughts on this. If this sounds reasonable I could probably hack it in. Thanks

**Comment by StreakyCobra** [comment]
It would be much more helpful if you can give us more informations. See [this](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report).

**Comment by gregpardo** [comment]
#### Description
With editorconfig installed, jsbeautify ignores formatting rules set in the '.editorconfig' file. For example if you have tabs set to 2 spaces in .editorconfig file and you press 'SPC m =', jsbeautify will ignore the rules set in the editorconfig. Indentation with with 'SPC j =' does use the correct indent rules from editorconfig. 

#### Reproduction guide
- Add 'editorconfig' to dotspacemacs-additional-packages in .spacemacs
- Install editorconfig 'brew install editorconfig'
- Start Emacs
- Create an .editorconfig file to a project
```
[*.js]
indent_style = space
indent_size = 2
```
- Open a javascript file in that folder
- Make sure editorconfig is enabled with (editorconfig-mode t)
- Indent with 'SPC j =' (will use editorconfig rules)
- Beautify with 'SPC m =' (will ignore editorconfig rules)
- Notice they have different behavior with their rulesets

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. fbc6bc5)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org syntax-checking version-control osx javascript themes-megapack react)
```

**Comment by StreakyCobra** [comment]
I'm not used to javascript, but if I understand correctly `jsbeautify` is an external tool right?

**Comment by gregpardo** [comment]
Looks like someone else had the same idea

https://github.com/beautify-web/js-beautify/issues/551

**Comment by Delapouite** [comment]
Option support for editorconfig has been added to js-beautify: https://github.com/beautify-web/js-beautify/commit/9e2dcca4621c8e2dff278ab799f60fece62f7a5e

**Comment by d12frosted** [comment]
@Delapouite thanks for heads up! Closing this issue as fixed upstream.
