### ISSUE TITLE
Layouts key is unresponsive after running `dotspacemacs/sync-configuration-layers`

### ISSUE THREAD

**Issue by joehillen** [syl20bnr/spacemacs#4214]
After running `SPC f e R` (`dotspacemacs/sync-configuration-layers`)

I get the following error and `SPC l` no longer does anything. Manually running `spacemacs/layouts-micro-state` also has no effect.

```
Error (use-package): eyebrowse :init: Key sequence l w starts with non-prefix key l
```

Here is my [.spacemacs](https://gist.github.com/1bce6b193a552b44d4d0) file.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 3507bc7)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults dockerfile emacs-lisp evil-commentary eyebrowse floobits git github haskell ...)
```

**Comment by syl20bnr** [comment]
Confirmed, I wanted to fix it the other day and I forget about it.

**Comment by TheBB** [comment]
Yeah I didn't think about re-syncing when I did that trick. #4217 should fix it I think.
