### ISSUE TITLE
spelling-checking on js (and maybe other modes)

### ISSUE THREAD

**Issue by axyz** [syl20bnr/spacemacs#4215]
Recently I've noticed that on js files spell-checking is turned on by default, that is quite annoying and creates confusion with errors and warnings.

Someone stated that it is probably related to recent efforts to have spell checking only on comments.
Probably somewhere `flyspell-mode` is used in place of `flyspell-prog-mode` (suggested by @justbur )

@joehillen also stated that it happens on haskell mode as well.

**Comment by TheBB** [comment]
Thanks. Went a bit quick there. Fixed by https://github.com/syl20bnr/spacemacs/commit/11daa77866b1b71f4385388cf901c01191782e8c

**Comment by StreakyCobra** [comment]
You didn't even let me time to label this issue :disappointed:
