### ISSUE TITLE
SPC x a a does nothing?

### ISSUE THREAD

**Issue by nugend** [syl20bnr/spacemacs#4218]
This is supposed to invoke the emacs align command to align on spaces but doesn't seem to do anything.

Maybe I'm using it wrong?

Steps to repeat:

1. Open scratch buffer
2. add text (taken from http://www.emacswiki.org/emacs/AlignCommands): 
```
lastname firstname
Smith John 33-88
Gere Alan    24-23
Verne Bill 12-34
```
3. Visual Highlight all text
4. SPC x a a

**Comment by justbur** [comment]
Did you read the side note on the page you linked to?

**Comment by nugend** [comment]
Nope. Missed it. Thank you.

Would be nice if there was a help text if you used it without SPC u

**Comment by justbur** [comment]
It's behavior depends on the context like the major mode so many times you
don't need the C-u. It's a dwim type command. If you want to align to a
specific character it's better to specify that character using one of the
other SPC xa commands.

**Comment by nugend** [comment]
Yeah, I had just found out about one of the other align commands from the Spacemacs Rocks blog and was looking at the interactive shortcut command listing to see what was available under SPC-x in general and going through each one. I couldn't figure out what align was doing, so I googled "emacs align" and skimmed down to the entry (just below the side note, d'oh!)
