### ISSUE TITLE
Helm config causing insanely long load time

### ISSUE THREAD

**Issue by elken** [syl20bnr/spacemacs#4220]
Not sure whether it's an issue with helm specifically or spacemacs but I'm posting here first. Everything loads fine until it hits helm config, at which point it stalls for, on average, 2 minutes.

`SPC h d s`

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.104.8
- Spacemacs branch: master (rev. 44d4525)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults
                 (colors :variables colors-enable-rainbow-identifiers t colors-enable-nyan-cat-progress-bar t)
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
                 emacs-lisp
                 (git :variables git-enable-github-support t git-gutter-use-fringe t)
                 github latex markdown org
                 (shell :variables shell-default-height 30 shell-default-term-shell "/bin/zsh" shell-default-position 'bottom)
                 shell-scripts spell-checking syntax-checking)
```

[Load log](http://dpaste.com/2EV75CN), note the `Configuring package helm...done (127.745s) [2 times]` line. 

Issue is prevalent on both Linux and Windows with different conf files. [Primary .spacemacs](http://dpaste.com/196MJBR).

**Comment by StreakyCobra** [comment]
99% sure it's [this](https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-is-spacemacs-hanging-on-startup).

**Comment by elken** [comment]
Wow I did a quick skim through some issues to see if it was known and must've glanced right over them. Thanks.
