### ISSUE TITLE
how about add Circe to spacemacs as a layer?

### ISSUE THREAD

**Issue by wqhhust** [syl20bnr/spacemacs#4231]
Current there are 2 options for irc in spacemacs, how about add Circe as another option? it's easy to use and have more features.

**Comment by StreakyCobra** [comment]
Yes, we just need someone writing it :-)

**Comment by robbyoconnor** [comment]
Write it and make a PR.

**Comment by aijony** [comment]
I've been using @chrisbarrett 's [circe layer](https://github.com/chrisbarrett/spacemacs-layers/tree/master/cb-circe/local/circe-show-channels). It works very well. I don't feel comfortable writings a PR of someone else's work, but I will someone wants me to and @chrisbarrett is okay with it (or is unresponsive). There are a few things that need to cleaned up to make it a bit more generalized and up to date with Spacemac's standards. However, it is a mostly well functioning package.

**Comment by braham-snyder** [comment]
@aijony FWIW, assuming Chris is okay with it, I would indeed be interested in such a PR
