### ISSUE TITLE
 File mode specification error: (void-variable elm)

### ISSUE THREAD

**Issue by terakilobyte** [syl20bnr/spacemacs#4234]
#### Description
After updating Emacs to the latest version and updating packages, the elm layer doesn't work. Upon loading an elm file, the error
`File mode specification error: (void-variable elm)` pops up.

#### Reproduction guide
- Start Spacemacs
- Ensure Spacemacs is updated to the latest version.
- Enable the elm layer in the .spacemacs file
- Restart Spacemacs
- Open a file with a `.elm` extension.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.104.8
- Spacemacs branch: master (rev. 44d4525)
- Distribution: spacemacs
- Layers:
```elisp
(markdown syntax-checking auto-completion company-mode erlang elixir git github dash osx html org colors editorconfig themes-megapack javascript js2-jsx erc elm)
```

#### Backtrace
```
Debugger entered--Lisp error: (void-variable elm)
  #[nil "\302\303\304	BD\"\207" [elm elm-oracle--pattern ac-define-source (candidates elm-oracle--get-completions ac-prefix t) prefix] 5]()
  eval-after-load(auto-complete #[nil "\302\303\304	BD\"\207" [elm elm-oracle--pattern ac-define-source (candidates elm-oracle--get-completions ac-prefix t) prefix] 5])
  require(elm-interactive)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\207" [require elm-format elm-indent elm-interactive elm-font-lock] 2)
  elm-mode()
  set-auto-mode-0(elm-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer SeatSaver.elm> "~/elixir/seat_saver/web/elm/SeatSaver.elm" nil nil "~/elixir/seat_saver/web/elm/SeatSaver.elm" (38324945 16777220))
  find-file-noselect("/Users/terakilobyte/elixir/seat_saver/web/elm/SeatSaver.elm" nil nil nil)
  find-file("/Users/terakilobyte/elixir/seat_saver/web/elm/SeatSaver.elm")
  neo-open-file("/Users/terakilobyte/elixir/seat_saver/web/elm/SeatSaver.elm" nil)
  neo-buffer--execute(nil neo-open-file neo-open-dir)
  neotree-enter(nil)
  call-interactively(neotree-enter nil nil)
  command-execute(neotree-enter)
```

**Comment by StreakyCobra** [comment]
I can reproduce it. Needs further investigations to know if it an upstream bug, or an upstream change that requires update on Spacemacs side.

@terakilobyte :cookie: for the great reporting :metal:

**Comment by Sinouplen** [comment]
I have exactly the same trouble with the version 0.104.0 of spacemacs

**Comment by jonatan-branting** [comment]
This only occurs with the auto-completion layer enabled.

**Comment by magthe** [comment]
Yupp, easy to reproduce on my (Arch) Linux box too.  Also that disabling *auto-completion* layer removes the problem :(

**Comment by codedmart** [comment]
I can confirm this and also can confirm this is an upstream issue. If I reset my elm-* files in elpa to this [commit](https://github.com/jcollard/elm-mode/commit/e0318ebb288be638f4a98cfd56a516b20ed5e723) all works fine again. Haven't pinpointed the upstream change that caused the problem yet.

**Comment by StreakyCobra** [comment]
@codedmart Let us know if you find the cause of the bug. It's an upstream change that causes the problem, but I don't know if it is an upstream **bug** that should be reported and corrected there, or an upstream **change** that require some adaptation on Spacemacs' side…

**Comment by StreakyCobra** [comment]
I had a quick look, probably coming from here: https://github.com/jcollard/elm-mode/commit/493b82aa16629fefb22894f9e555b9fd382bf4aa#diff-c3633a01c792e88846f0ecf0214a49e0R686

**Comment by TheBB** [comment]
This has probably been fixed upstream, see discussion in https://github.com/jcollard/elm-mode/issues/50 (thanks @codedmart for reporting). Waiting for it to arrive in MELPA.

**Comment by StreakyCobra** [comment]
Should be fixed upstream by now, marking it as is. Let us know if it's not the case.

**Comment by codedmart** [comment]
@TheBB @StreakyCobra I can confirm this has been fixed now with a package update of elm-mode. Thanks

**Comment by terakilobyte** [comment]
Yep, everything looks good.
