### ISSUE TITLE
Hide additional caret in helm

### ISSUE THREAD

**Issue by jordwalke** [syl20bnr/spacemacs#4236]
![screen shot 2015-12-19 at 3 13 14 pm](https://cloud.githubusercontent.com/assets/977348/11915608/1c6ece7e-a663-11e5-9d19-5eaf7966e41b.png)

You can see in this screenshot that there is an additional hollow yellow cursor caret on the current highlighted line and it's very visually distracting. It would be great if spacemacs could configure helm to disable that caret.

**Comment by nixmaniack** [comment]
I couldn't find a hook which you can use to disable this behaviour particularly for helm buffer. If you want to hide cursor from non-selected windows globally, you can do following in `user-config`
```elisp
(setq-default cursor-in-non-selected-windows nil)
```

There's [upstream issue](https://github.com/emacs-helm/helm/issues/1277) for this but it's closed.

**Comment by syl20bnr** [comment]
To be sure to set it in the correct buffer `with-helm-buffer` macro must be used.
Should be fixed in develop.

**Comment by nixmaniack** [comment]
@syl20bnr Thanks!

**Comment by jordwalke** [comment]
Glad this is getting fixed one way or another - it's really distracting otherwise.
I'll use the global setting in the mean time.
