### ISSUE TITLE
Java Layer/Zsh parse error

### ISSUE THREAD

**Issue by pgoggijr** [syl20bnr/spacemacs#4240]
Trying to do any operations in the java configuration layer outputs the following:

`zsh:1: parse error near '-command'`

I cannot connect to eclim, and any static analysis attempts fail.  

I don't know how to debug this, or where to start, but I'm sure if I had a little bit of guidance I could pinpoint the problem (Bit of a spacemacs/emacs noob, coming from vim)

I'm using
- Railwaycat's emacs-mac-port v24.5.1
- Spacemacs v0.104.6
- zsh v5.2
- OS X El Capitan

**Comment by Towerism** [comment]
Having same problem. I'm using zsh v5.2 on Arch Linux.

**Comment by TheBB** [comment]
They were incorrect in a previous version, at least.

Is this still a problem for you @pgoggijr?
