### ISSUE TITLE
`c-w` should delete word backwards in insert mode even if autocomplete is open.

### ISSUE THREAD

**Issue by jordwalke** [syl20bnr/spacemacs#4243]
When the autocomplete window is open, `c-w` no longer deletes backwards. This seems like a pretty big bug, though it's likely the result of some conflict of packages/layers (again, I'm new to Emacs).

This is my entire config:

```
  (load-theme 'spacemacs-light t)
  (set-face-attribute 'mode-line nil :box nil)
  (set-face-attribute 'mode-line-inactive nil :box nil)
  ;; Don't highlight line
  (global-hl-line-mode -1) ; Disable current line highlight
  (setq evil-want-fine-undo nil)
  (setq evil-move-cursor-back nil)
  (global-set-key (kbd "s-p") 'helm-M-x)
  ; (setq powerline-default-separator 'utf-8)
  (setq powerline-default-separator nil)
  (global-vi-tilde-fringe-mode -1)
```

These are my enabled layers:

```
     company
     ;; To toggle autocompletion on:
     ;; space t a 
     auto-completion
     ;; better-defaults
     emacs-lisp
     themes-megapack
     ;; Basic mac keybindings. (Cmd is super, alt is meta)
     osx
```

The version of spacemacs I'm using is master as of today.

**Comment by jordwalke** [comment]
I noticed the same issue with Helm as well.

**Comment by nixmaniack** [comment]
Yes, that's quite annoying! :smile: I have this in my config now. 
```elisp
(define-key company-active-map (kbd "C-w") 'evil-delete-backward-word)
(define-key helm-map (kbd "C-w") 'evil-delete-backward-word)
```
I'm not aware of any consequences of this.

**Comment by nixmaniack** [comment]
Okay, the `C-w` binding in helm-map has some consequences which I remember now. By default, emacs copies the thing(symbol) at point in input area if you hit `C-w` so you're essentially overriding that behaviour.

**Comment by jordwalke** [comment]
I wonder if it makes sense to at least have a spacemacs config option for this. Since you're already giving up that emacs style consistency in Vim insert mode, you would likely want the same in other input areas.

**Comment by jordwalke** [comment]
BTW: When I try that mapping in my user config (for `company-active-map`) I get an error:
```
Error in dotspacemacs/user-config: Symbol's value as variable is void: company-active-map
```

**Comment by jordwalke** [comment]
For the record, I had to put this in my user config:
```
  (with-eval-after-load 'company
    (define-key company-active-map (kbd "C-w") 'evil-delete-backward-word)
  )
  (with-eval-after-load 'helm
    (define-key helm-map (kbd "C-w") 'evil-delete-backward-word)
  )
```

**Comment by nixmaniack** [comment]
@jordwalke :+1:  That's correct way.

**Comment by jeaye** [comment]
I'm experiencing this issue now as well, and @jordwalke's config did the trick. I agree that this should be provided as an option within spacemacs.

**Comment by Profpatsch** [comment]
Same issue here, that is a pretty major dealbreaker especially in latex mode, where ispell tries to complete nearly every word.

**Comment by gdkrmr** [comment]
FYI: `C-w` in the `company-active-map` is bound to `company-show-location` and in d `helm-map` it shows some weird strings of bytes.

**Comment by Profpatsch** [comment]
yeah

**Comment by nixmaniack** [comment]
As gdkrmr mentioned above, if users use the `C-w` to temporarily show the code then it would break that workflow. We might need to find a different binding for `company-show-location` in that scenario before binding `C-w` to delete backward.

**Comment by Profpatsch** [comment]
I think this is still relevant
