### ISSUE TITLE
Is there a way to customize powerline Vim mode colors?

### ISSUE THREAD

**Issue by jordwalke** [syl20bnr/spacemacs#4244]
The default colors for the segment that shows (insert/normal/replace/visual) seem to clash with just about every color scheme I've tried and it's very distracting (the colors are very saturated). Is there a way to customize those colors? Maybe there should be a nice fallback where you grab some colors from the color scheme to generate them if the color scheme itself has not customized them.

**Comment by nixmaniack** [comment]
Look at this [comment](https://github.com/syl20bnr/spacemacs/issues/2273#issuecomment-119824103)

**Comment by jordwalke** [comment]
Thanks. Any thoughts on exposing this to color themes?

**Comment by TheBB** [comment]
All the tools that can change faces in regular Emacs still work with Spacemacs.

**Comment by TheBB** [comment]
I recommend you use `custom-set-faces` (see docstring for more information). Use `list-faces-display` for a list of faces you can change.
