### ISSUE TITLE
A way to use tab to expand snippets.

### ISSUE THREAD

**Issue by jordwalke** [syl20bnr/spacemacs#4245]
I don't use tab to expand word completion, I use `<enter>` entirely. Luckily for me, that frees up the ability to use the ultra-convenient `<tab>` for another highly valuable interaction - expanding snippets. This means I get to experience the same "feel" that virtually every modern editor has for snippet expansion (Xcode, Sublime, (Textmate RIP), Atom, others).

What can be done in `spacemacs` to accommodate this modern editing interaction (tab for snippet expansion, assuming I'm willing to give up tab for completion).

**Comment by cpaulik** [comment]
You can set that up by doing the following:

- set `auto-completion-tab-key-behavior nil` in the autocompletion layer.
- put `(global-set-key (kbd "TAB") 'hippie-expand)` in your `spacemacs/user-config`

This worked for me for a few quick tests.

**Comment by jordwalke** [comment]
Thanks, I will try this. Again, I'm new to emacs so apologies if this should have been obvious.

**Comment by jordwalke** [comment]
Seems to have worked, thanks! I might suggest documenting this very common preference on the `autocomplete` layer readme. (I wonder if most people would want this to even be the default). Closing!
