### ISSUE TITLE
OSX layer - command+w should kill the frame if only one window remains.

### ISSUE THREAD

**Issue by jordwalke** [syl20bnr/spacemacs#4246]
It would be very natural to osx users if `command+w` would kill the frame if only a single window remains.
(Super new to emacs, I apologize if I'm not using the correct terminology here).

**Comment by ngortheone** [comment]
I would like to disable `command+w` in emacs completely, but I don't know how.
Often when switching windows with SPC w <direction> I can hit command instead of space and it will kill my frame!

**Comment by nixmaniack** [comment]
Given the lack of traction on this issue, it might seem that this behaviour is not much desired by everyone. Hence, instead of proposing an enhancement to Spacemacs, here's a piece of code that'll achieve what you want. 

```elisp
(defun delete-frame-if-one-window (orig-fun &rest args)
  (if (one-window-p t)
      (delete-frame)
    (apply orig-fun args)))

(advice-add 'delete-window :around #'delete-frame-if-one-window)
```
