### ISSUE TITLE
orgmode capture doesn't work

### ISSUE THREAD

**Issue by pangwa** [syl20bnr/spacemacs#4252]
I tried to use the key "~SPC~-C-T" (capture ort/checkitem) to capture a todo item in org mode. But there is no popup window show. "Capture template `ort/todo` : outline-show-all" was shown in the status line.

I'm using the master branch under osx.

**Comment by pangwa** [comment]
Looks like an installation issue, It worked after I reinstalled all the packages.

**Comment by spinpx** [comment]
I met the same problem. but it still exists after I reinstalled all the packages.
