### ISSUE TITLE
[SOLVED]Help! spacemacs hang ~50s on startup. spacemacs require network when startup?

### ISSUE THREAD

**Issue by Treri** [syl20bnr/spacemacs#4255]
When spacemacs startup, it will hang ~30-50s, and I have to force quit emacs everytime

Firstly I think the problem is I installed wrong version spacemacs. Then I used up-to-date master branch. And the problem is still exist. Then I switched to develop branch, the problem is still exist sadly.

Then i moved `.emacs.d` to `emacs.d`, and started emacs without any config, the problem is gone.

Then I want to fresh install spacemacs again. Because my network is blocked for some foreign website or resource, so I turned on my VPN to download packages quickly. Then the problem is gone.

I test spacemacs when I turned on VPN, it will not hang. But if I turned off VPN, spacemacs hang again. So I think the problem is spacemacs will access some resource which is blocked or is very very very slow in my network. So spacemacs hang on every startup.

Anyone have the problem same? I'm a vimer, but I really want to use spacemacs, anyone could help me? Thanks very much!!

**Comment by dsdshcym** [comment]
- melpa.org
- orgmode.org
- elpa.gnu.org
- github.com/syl20bnr/persp-mode.el
- github.com/syl20bnr/spacemacs

I'm at Shanghai and these website are nearly unreachable through pure ChinaNet
network. But spacemacs may check these website to get update info. So you may
need to use VPN or other proxy methods to get package updates. And set
`dotspacemacs-check-for-update` to nil will also do some help. (This is a new 
variable in develop branch)

**Comment by Treri** [comment]
@dsdshcym Thanks very much. I set `dotspacemacs-check-for-update` to nil, but spacemacs hang only a little short, I still have to wait very long time.

Maybe I should run spacemacs as daemon mode, so I can wait very long just one time. Then I use `emacsclient` to run.

**Comment by TheBB** [comment]
Could be this? https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-is-spacemacs-hanging-on-startup

**Comment by Treri** [comment]
@TheBB Amazing! spacemacs not hang any more! Thanks very much!

And thanks @dsdshcym also for your quick reply!
