### ISSUE TITLE
Issue with develop and bind-map

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#4257]
On emacs 24.5.1 on redhat 6, attempting a clean install from develop I get 

Warning (initialization): An error occurred while loading `/home/linuxuser/.emacs.d/init.el':

File error: https://melpa.org/packages/bind-map-20151217.829.el, Bad Request

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

# with debug

Debugger entered--Lisp error: (file-error "https://melpa.org/packages/archive-contents" "Bad Request")
  signal(file-error ("https://melpa.org/packages/archive-contents" "Bad Request"))
  url-insert-file-contents("https://melpa.org/packages/archive-contents")
  package--download-one-archive(("melpa" . "https://melpa.org/packages/") "archive-contents")
  #[0 "\301\300\302\"\207" [("melpa" . "https://melpa.org/packages/") package--download-one-archive "archive-contents"] 3 "\n\n(fn)"]()
  funcall(#[0 "\301\300\302\"\207" [("melpa" . "https://melpa.org/packages/") package--download-one-archive "archive-contents"] 3 "\n\n(fn)"])
  package-refresh-contents()
  (let ((package-archives (list archive))) (package-refresh-contents))
  (if (eq (quote error) (let ((-with-timeout-value- (catch (quote timeout) (let* (... ...) (unwind-protect ... ...))))) (if (eq -with-timeout-value- (quote timeout)) (progn (progn (spacemacs-buffer/append (format "\nError while contacting %s repository!" ...)) (quote error))) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents)))
  (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let ((-with-timeout-value- (catch (quote timeout) (let* ... ...)))) (if (eq -with-timeout-value- (quote timeout)) (progn (progn (spacemacs-buffer/append ...) (quote error))) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- package-archives) archive) (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let ((-with-timeout-value- (catch ... ...))) (if (eq -with-timeout-value- (quote timeout)) (progn (progn ... ...)) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((count (length package-archives)) (i 1)) (let ((--dolist-tail-- package-archives) archive) (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let ((-with-timeout-value- ...)) (if (eq -with-timeout-value- ...) (progn ...) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (package-read-all-archive-contents) (if quiet nil (spacemacs-buffer/append "\n")))
  (if (and configuration-layer--package-archives-refreshed (not force)) nil (setq configuration-layer--package-archives-refreshed t) (let ((count (length package-archives)) (i 1)) (let ((--dolist-tail-- package-archives) archive) (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let (...) (if ... ... -with-timeout-value-))) nil (let ((package-archives ...)) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (package-read-all-archive-contents) (if quiet nil (spacemacs-buffer/append "\n"))))
  configuration-layer/retrieve-package-archives(quiet)
  (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg)))
  (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)
  (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)))
  (let ((warning-minimum-level :error)) (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append ...) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir))))
  spacemacs/load-or-install-package(bind-map t nil)
  spacemacs/load-or-install-protected-package(bind-map t)
  spacemacs/init()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %d or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat user-emacs-directory "core/core-load-paths.el")) (if init-file-debug (progn (require (quote core-debug)))) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/linuxuser/.emacs.d/init.el" nil t)  ; Reading at buffer position 1165
  load-with-code-conversion("/home/linuxuser/.emacs.d/init.el" "/home/linuxuser/.emacs.d/init.el" t t)
  load("/home/linuxuser/.emacs.d/init" t t)
  #[0 "\205\262

Any ideas ?
Thanks

**Comment by TheBB** [comment]
It complains that it can't reach that URL. Can you? (Check with a browser, for example.)

Try setting `dotspacemacs-elpa-https` to `nil`, that might help. You may have to edit your ~/.spacemacs file with another editor to do this when you haven't installed Spacemacs yet. If it's not created for you already you can copy it from .emacs.d/core/templates/.spacemacs.template.

**Comment by fatlazycat** [comment]
Well I am behind a proxy, which doesn't help but if I use master and then update packages within spacemacs it's all fine.

Yeah can reach that with a browser though that's a diff route. wget from the shell also works.

**Comment by fatlazycat** [comment]
There is definitely something up with develop for me.

If I start with clean 'git clone' for each of these attempts and no spacemacs file. 

Then with master and when I start emacs it's fine - packages start downloading.

With develop it has an issue resolving through the proxy ( for whatever reason ) and then dies and spacemacs won't download / run etc.

Would appear something in develop is trashing the proxy ?

**Comment by TheBB** [comment]
If it works with master but not develop, any chance you can bisect the issue?

**Comment by fatlazycat** [comment]
Sure, though am about to leave the office for xmas so probably new year before I get anywhere

**Comment by fatlazycat** [comment]
Is there a way of disabling https for all calls ?

**Comment by fatlazycat** [comment]
Ah found the command line option --insecure and all runs fine. The company proxy is doing something odd a by intercepting https traffic and buggering it up somehow.

Not worth really looking into what new changes in develop show this up as it's not at your end.

**Comment by StreakyCobra** [comment]
If you don't want having to use a command line flag for this:
https://github.com/syl20bnr/spacemacs/blob/374e37e32c71295aec87d8207380e9ab019b5ba3/core/templates/.spacemacs.template#L60-L66

**Comment by fatlazycat** [comment]
That didn't work when I tried it before.

**Comment by StreakyCobra** [comment]
Oh sorry I didn't read the whole thread. Maybe there is some `https` left somewhere else.

**Comment by nugend** [comment]
Is this working in with the new release now? I used insecure and got my spacemacs working again. (So I don't have any out of date packages to test now. Presumably the configuration setting only worked with the new version?)

**Comment by fatlazycat** [comment]
I had to use insecure to get the new release to work also

**Comment by edgarwang** [comment]
After I update to 0.105.0, I had to use `--insecure` to install bind-map.

**Comment by kitech** [comment]
--insecure +1 for 0.105.0

**Comment by fatlazycat** [comment]
@thebb should this be reopened ?

**Comment by TheBB** [comment]
Are you saying that for some packages (bind-map), `dotspacemacs-elpa-https` does not work, but `--insecure` does?

**Comment by fatlazycat** [comment]
actually trying now on master '''dotspacemacs-elpa-https''' works
