### ISSUE TITLE
Add keybinding for quick switching to "Messages" buffer

### ISSUE THREAD

**Issue by ikhthiandor** [syl20bnr/spacemacs#4259]

**Comment by TheBB** [comment]
`SPC w p m`?

**Comment by ikhthiandor** [comment]
@TheBB that didn't work.

**Comment by TheBB** [comment]
Er, okay. Can you be more specific? Is it bound to anything? Are you getting an error message?

**Comment by ikhthiandor** [comment]
Oh sorry, I just had installed eyebrowse before trying this. I'm not used to it. So I don't know what I was doing wrong. I disabled eyebrowse. The keybinding seems to work ok.

http://i.imgur.com/auzKo8z.png

Does it also work with eyebrowser enabled on your end?

**Comment by TheBB** [comment]
Yes, it works with eyebrowse.

Note: `SPC w p m`, not `SPC p w m`.
