### ISSUE TITLE
Loading AucTeX on demand keybinding

### ISSUE THREAD

**Issue by legendre6891** [syl20bnr/spacemacs#426]
The key `SPC e l` no longer loads AucTeX on demand; spacemacs waits for another key after the `l`. However, if you quit this keysequence via `C-g`, then `SPC e l` again works.

**Comment by bjarkevad** [comment]
There's a PR incoming which should deprecate the use of `SPC e l` all together.

**Comment by syl20bnr** [comment]
Fixed by https://github.com/syl20bnr/spacemacs/commit/c09641ba9604efbf593e296a6b46ab705c43489d
