### ISSUE TITLE
Dropbox sync

### ISSUE THREAD

**Issue by sho-87** [syl20bnr/spacemacs#4265]
What is the correct way to set up spacemacs using dropbox so I can get access to the exact same config on each of my systems?

Without spacemacs, I would just put my entire .emacs.d directory on dropbox, and symlink to that dir in my home directory

In seems tha spacemacs, on Windows at least, doesn't store all the config within the .emacs.d directory, as there is also a .spacemacs file in my home directory (not sure if theres anything else)

How does one set up dropbox syncing? What should I put in the cloud so I can work on different machines?

**Comment by TheBB** [comment]
You just need your .spacemacs file, and whatever other files you've written yourself. The spacemacs repo can be cloned, so you don't need to store that.

**Comment by sho-87** [comment]
@TheBB But what if I want to add a custom package from github? Do I not need to add that to the packages file, ala: https://github.com/syl20bnr/spacemacs/blob/5f756be832841268dc70e1cc54c4ac860b0eccdf/spacemacs/packages.el#L45 ?

I'm hoping to get to a point where if I install a package on one system, that will automatically install and load on another computer after syncing with dropbox. Or is there also a place in the .spacemacs file where I can load these new/custom packages?

**Comment by TheBB** [comment]
You add it to `dotspacemacs-additional-packages`. You shouldn't have to edit Spacemacs source code.
