### ISSUE TITLE
how can I put dotspacemacs/user-config and dotspacemacs/user-init to private layer?

### ISSUE THREAD

**Issue by Treri** [syl20bnr/spacemacs#4268]
How can I put `dotspacemacs/user-config` and `dotspacemacs/user-init` to private layer?

So I can always use spacemacs per version's auto-generated `~/.spacemacs` file(in this way, I can always track upstream `~/.spacemacs` changes), and the only thing i have to do is adding a private layer name to `dotspacemacs-configuration-layers`.

Can I define `dotspacemacs/user-config` or `dotspacemacs/user-init` in a private layer?
Or is there any way to do this to guarante to load private layer's config(this config is original in dotspacemacs/user-config section)?

**Comment by Treri** [comment]
Additionally, maybe spacemacs users can have a local file to list his own prefered layers. So every user have not to modify .spacemacs, and the file go into spacemaces repo via version control.

Another idea, `.spacesmacs` file only include user-specific configs. and put `dotspacemacs/init` and `dotspacemacs/layers` somewhere else. Users can override default layers list or configuration(now these in `dotspacemacs/init` and `dotspacemacs/layers`) in .spacemacs

**Comment by StreakyCobra** [comment]
Taking care of maintaining configuration file up-to-date is a complicate task, whatever is the way you do it. What you propose for the layers list is working, but it doesn't solve the problem for all others configurations variables. The way most of the people use to deal with this is `SPC f e D` that will diff your `.spacemacs` against the template version.

In short:

- `SPC f e D` to run the diff
- `n` or `p` to go to next or previous change in the file
- If there is a change on the template you want to include in your `.spacemacs`, press `b`.

If you do this without pressing `b` for the changes concerning `dotspacemacs-configuration-layers`, `dotspacemacs/user-config` and `dotspacemacs/user-init`, then you can update all you configuration file without touching those parts :-)

**Comment by Treri** [comment]
I got it. Thanks for your patient reply very much :+1:

**Comment by justbur** [comment]
@Treri also you can always load an external file from user-init or user-config using `(load "path/to/elisp.el")`

**Comment by Treri** [comment]
@justbur Thank you~ I will try 😄

**Comment by vonpupp** [comment]
Hello,

I am also dealing with this exact same idea: put my configs outside of the .spacemacs config (actually I converted it to a directory config, so I use `.spacemacs.d/init.el`).

This is how init.el related section looks like:
```
(defun dotspacemacs/user-config ()
  "Configuration for user code:
This function is called at the very end of Spacemacs startup, after layer
configuration.
Put your configuration code here, except for variables that should be set
before packages are loaded."

  (add-to-list 'load-path "~/.spacemacs.d/myinit")
  (require 'myinit)
  (myentrypoint)
  )
```
And `myinit/myinit.el` file reside also within the `.spacemacs.d` folder. Here is the header:

```
(defun myinit/myentrypoint ()
  ;; ----------------------------------------------------------------
  ;; Org mode
  ;; ----------------------------------------------------------------
  (setq org-modules (quote (org-habit)))
  (setq org-log-into-drawer "LOGBOOK")
  ...
)

(provide 'myinit)
```

It seems to work, but I would like to ask, is this the right way to do it, or there is a better way?

Thanks.
