### ISSUE TITLE
Two layers sharing the same package

### ISSUE THREAD

**Issue by jordwalke** [syl20bnr/spacemacs#4269]
I have two layers, one of them I am developing and the other is a built in layer. My layer is basically a fork of the other and I'm okay with that fact. Naturally, my fork shares many of the same package dependencies as the built in layer. Unfortunately, it seems that spacemacs doesn't like this. It gives me the following error:

```
(Spacemacs) Warning: More than one init function found for package X. Previous owner was Y, replacing it with layer Z.
```

Is it really true that no two layers may have dependencies on the same packages, and that they both can't define initializers for them?

**Comment by StreakyCobra** [comment]
There can be only one layer "owning" a package, but you can use one `init-…` and several `post-init-…` as explained [here](https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#packagesel) to add some initializations. Example:

- https://github.com/syl20bnr/spacemacs/blob/374e37e32c71295aec87d8207380e9ab019b5ba3/layers/syntax-checking/packages.el#L20
- https://github.com/syl20bnr/spacemacs/blob/374e37e32c71295aec87d8207380e9ab019b5ba3/layers/%2Blang/ruby/packages.el#L90-L92

**Comment by jordwalke** [comment]
Okay, thanks. I wish there was a way to have two separate layers "factor out" the initialization of a dependency package, such that two independent layers can count on a dependency being initialized in a particular way.
