### ISSUE TITLE
s-Z undo-tree-undo instead of undo-tree-redo

### ISSUE THREAD

**Issue by Peeja** [syl20bnr/spacemacs#4272]
In my install (just updated) <kbd>s-Z</kbd> performs `undo-tree-undo`. Emacs tells me it's translating <kbd>s-Z</kbd> to <kbd>s-z</kbd>. That's odd, because [<kbd>s-Z</kbd> is bound to `undo-tree-redo` by Spacemacs](https://github.com/syl20bnr/spacemacs/blob/074f425dc5d233f24195ecc3021eb96ac9d55d4d/layers/osx/keybindings.el#L32), but it doesn't appear to take for some reason.

However, if I add my own `(global-set-key (kbd "s-Z") 'undo-tree-redo)` to my `dotspacemacs/config`, it works.

I'm curious if anyone else has the same issue, or if this is just a weird conflict I'm somehow running into.

**Comment by nixmaniack** [comment]
I faced something similar on OS X recently where `M->` wasn't detected by Emacs at all, later after some debugging I found out one of the OS X application was intercepting `Meta Shift` and Emacs didn't receive modifier `Shift`.

So in your case it might possible that , `Command Shift` is shadowed/intercepted.

**Comment by Peeja** [comment]
It works when I add the `global-set-key` myself, though.
