### ISSUE TITLE
help for "follow link" should be at the top of the documentation

### ISSUE THREAD

**Issue by vitiral** [syl20bnr/spacemacs#4273]
Hello, I just installed spacemacs and I am trying to read the documentation provided from the start page while using emacs. Unfortunately, I can't seem to follow the links! [Vim's standard](http://vim.wikia.com/wiki/Learn_to_use_help) `Ctrl ]` doesn't work (why not?) and searching for "follow link" brings up nothing. Can this be added to the documentation?

**Comment by justbur** [comment]
In org buffers and help buffers it's the return key. In the home buffer you can jump to any link with "o" (this is described under Quick Help (the [?] button)).

**Comment by nixmaniack** [comment]
For org buffers, you will need `org` layer for `RET` key to work to follow links, which also adds `,l` to follow link. But yes, `C-]` seems like Vim convention to follow link under point, and `C-t` to go back which  is missing at the moment.

**Comment by justbur** [comment]
I suppose without the org layer you need to use the org default of `C-c C-o`

**Comment by vitiral** [comment]
Installed the org mode layer and now both `o` and plain-ol `RET` seems to be openeing the link in my web browser, which is the opposite of helpful in a text editor haha.

**Comment by StreakyCobra** [comment]
@vitiral If the links you are opening are `http://` ones, Spacemacs can't open them within the editor (without 3-party extensions), so it make sense to open them in the browser.

**Comment by vitiral** [comment]
hmm... ok. It would be nice to get that to work in either emacs or github... but I can see how that might be difficult!

Thnaks @StreakyCobra
