### ISSUE TITLE
powerline fonts not quite working (urxvt in Arch Linux)

### ISSUE THREAD

**Issue by vitiral** [syl20bnr/spacemacs#4276]
I'm having problems with the powerline fonts not rending correctly in urxvt. I think I am probably just missing some configuraiton line.

My current `~/.Xresources` font configuration is (based on powerline's [tips and tricks](http://powerline.readthedocs.org/en/master/tips-and-tricks.html)):
```
URxvt.font: xft:inconsolata:size=13,xft:Terminus,xft:Inconsolata\ for\ Powerline,-*-unifont-*-*-*-*-*-*-*-*-*-*-*-*
```
Edit: also I have **otf-inconsolata-powerline-git** installed from the AUR
Edit: I also tried Source Code pro from the same FAQ with the same problem

but my font looks like this:
![powerline](http://i.imgur.com/Oan9ZBi.png?1)

As you can see, it is picking up the arrows but not the `(!)` style symobols.

Two questions:
- can someone share their working ~/.Xresrouces file? I'm thinking I just need more fonts from the [powerline fonts](https://github.com/powerline/fonts) package, but I don't know in what order to do them.
- if not, is it possible to replace the special symbols with regular text ones?

**Comment by justbur** [comment]
I can answer the last one. Look in your dotfile for this setting
```elisp
   ;; If non nil unicode symbols are displayed in the mode line.
   dotspacemacs-mode-line-unicode-symbols nil
```

**Comment by vitiral** [comment]
Awesome! Thanks, that worked like a charm.
