### ISSUE TITLE
I think the basic configuration of org should be in the spacemacs layer

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#4277]
It's awkward to me at least that basic org mode stuff changes depending on whether you are using the org layer or not, especially since all of the docs are in org format now.

It would make more sense to me to have org be included in the spacemacs layer, and then have the extras in the current org layer become an org-extras or org-goodies layer. That way we can ensure that people have the same basic org configuration. See #4273 for example, where the method for following links depends on whether you use the layer.

**Comment by nixmaniack** [comment]
I agree totally! I think this was mentioned in gitter as well with same issue of following links in org buffers. Since org is built-in package, it makes much sense to configure it in spacemacs in the spacemacs way. The chances of jumping into org files are more as we have documentation in org files and having consistent way of moving around should be configured in spacemacs layer or probably core itself.

**Comment by syl20bnr** [comment]
Indeed.

What kind of rule can we make to decide whether a given org configuration should be in spacemacs or extra layer ?

**Comment by justbur** [comment]
To start anything useful for the docs should be in spacemacs

**Comment by TheBB** [comment]
Anything that is useful for someone who just drops into org mode on a casual basis should be in the org layer. If it's for people who are actually using org as a workflow tool I think it can stay in the org layer (e.g. the agenda).

**Comment by vitiral** [comment]
@TheBB I think you meant "on a casual basis should be in the **spacemacs** layer."

**Comment by TheBB** [comment]
Yep, thanks!

**Comment by justbur** [comment]
Maybe org is sufficiently important to warrant its own spacemacs-org layer that is included in spacemacs by default?

**Comment by a13ph** [comment]
It surely is sufficiently large to be modularized on it's own. It can match helm in numbers of plugins and such.

Some support for reading documentation in org format is important. Jump-to-heading certainly is (though it's not quite as advertised as it should be + I'm not sure about current status of it without org layer enabled)

**Comment by justbur** [comment]
I guess no one wants to implement this

**Comment by d12frosted** [comment]
No-no, reopen it. I was going to address it on these weekends (at least give it a try) :)

**Comment by justbur** [comment]
Oh ok

**Comment by justbur** [comment]
Closing now, because we have the PR for it now #5372
