### ISSUE TITLE
Spacemacs freezing when I try to save/load a layout while using helm

### ISSUE THREAD

**Issue by masnes** [syl20bnr/spacemacs#4282]
I'm using `spacemacs-layouts` layer. When I try to save my layouts to a file, spacemacs freezes. If I ctrl-g, it eventually comes back to life, but my cursor is no longer located in the helm buffer.

Saving layouts works fine with helm mode disabled.

**Comment by StreakyCobra** [comment]
It would be possible to help you better if your issue follows [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) :-)
