### ISSUE TITLE
auto-completion-complete-with-key-sequence not works

### ISSUE THREAD

**Issue by lazywei** [syl20bnr/spacemacs#4284]
Hi,

I used this config for auto completion:
```
     (auto-completion :variables
                      auto-completion-return-key-behavior 'complete
                      auto-completion-tab-key-behavior 'cycle
                      auto-completion-complete-with-key-sequence "jk"
                      auto-completion-private-snippets-directory nil)
```
but the "jk" sequence didn't work.

I'm on the develop branch 374e37e32c71295aec87d8207380e9ab019b5ba3.

I'm not sure how to debug this?

Thanks.

**Comment by izahn** [comment]
Doesn't work for me either. I'll try to find time to look at the code, but if someone familiar with the autocomplete layer code can take a look that would be great.

**Comment by izahn** [comment]
Well, I took a look at the code but it is a pretty complicated mess. I think it would be worthwhile to clean it up and provide a simpler implementation. I will try to find time to do that, but it may not be soon. I certainly will not complain if someone beats me to it.

**Comment by syl20bnr** [comment]
I wrote the code and I agree that it is a mess. A clean way to handle it would be to install a pre-command-hook like evil-escape does. The hook could be installed when the popup appears and removed when the popup disappear, I'm pretty sure there are hooks for this in company.

Thank you for looking into this!

**Comment by izahn** [comment]
After looking at the code again I think I totally misunderstood the point of `auto-completion-complete-with-key-sequence`. Basically I want to bind a key to `company-complete`; I thought that's what `auto-completion-complete-with-key-sequence` was for, but after looking at the implementation it seems that it's purpose is to complete the selected candidate once completion is already initiated. I just use `ret` for that, so I guess `auto-completion-complete-with-key-sequence` is not what I want anyway.

After all that I just added
```
  (add-hook 'company-mode-hook
            (lambda()
              (global-set-key (kbd "S-SPC") 'company-complete)))
```
 to my `.spacemacs` and I'm a happy camper. 

@lazywei I'm not sure if you suffered the same confusion as me, but if so, I suggest just binding `company-complete` to a key of your choice.

**Comment by lkyhfx** [comment]
auto-completion-complete-with-key-sequence '"jk",there must be a ' behind the ".

**Comment by ChrisChen3121** [comment]
`auto-completion-complete-with-key-sequence (kbd "jk")` should work.
