### ISSUE TITLE
helm input line behavior confusing

### ISSUE THREAD

**Issue by vitiral** [syl20bnr/spacemacs#4288]
First of all, I aboslutely love spacemacs.

One of the first things I noticed that was confusing for me (as a new user) was the helm behavior for inputting text.

The problem is that when you start searching for things, the input text is at the top of the search window, like this:
![current behavior](http://i.imgur.com/n1Lg5U9.png?1)

However, the "default" (and in my opinion better) helm behavior keeps the text input at the bottom of the screen:
![default helm behavior](https://github.com/emacs-helm/helm/raw/master/doc/helm-buffers-list.gif)

Is there a reason this was changed? Is there an easy way to change it back? Can the default be changed to be the same as default helm?

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/2082

Set `helm-echo-input-in-header-line` to `nil`.

**Comment by vitiral** [comment]
Hey @TheBB, thanks for the response.

I tried to put that both in my `dotspacemacs/init` and `dotspacemacs/user-init` files, neither of which changed the behavior.

```
(defun dotspacemacs/user-init ()
  (setq helm-echo-input-in-header-line nil)
... other code
````

**Comment by TheBB** [comment]
Yes, you have to do it later: in `dotspacemacs/user-config`. Otherwise Spacemacs will override this setting when it loads.

**Comment by vitiral** [comment]
@TheBB thanks a lot!

I think I was confused because I thought you generally set varables in init. I guess that depends on whether the variables are for "pre configuration" or are used dynamically. Thanks a ton!
