### ISSUE TITLE
rvm-activate-corresponding-ruby not added to ruby-mode-hook 

### ISSUE THREAD

**Issue by hagmonk** [syl20bnr/spacemacs#4289]
Running on spacemacs/develop and emacs-25.1.50.1 on OS X.

At some point I found that visiting Ruby files no longer ran rvm-activate-corresponding-ruby, which caused all sorts of problems in my setup.

My configuration layer for Ruby is:

```
(ruby
  :variables
  ruby-version-manager 'rvm
  ruby-enable-enh-ruby-mode nil)
```

When investigating, I found that ruby/init-rvm was being run, but (use-package rvm …) appeared to not run. Or at least, the :init form was not being executed because this was the form in which rvm-activate-corresponding-ruby was being added to ruby-mode-hook.

Looking at the :if predicate supplied to this use-package call:

```
(equal 'rvm 'ruby-version-manager)
```

I figured somehow ruby-version-manager wasn't being set. But placing a debug message in there confirmed it was being set! I believe the actual culprit is that ruby-version-manager is quoted, meaning that the symbol "rvm" is being compared to the symbol "ruby-version-manager". This will always be false.  By unquoting ruby-version-manager, you check to see whether the symbol ruby-version-manager when evaluated contains the symbol rvm.

Anyway, I made this change and it fixed my problem. It appears to have been introduced in 9eb8f86b.

**Comment by hagmonk** [comment]
Oh, and this bug - if it turns out to be a bug - would also affect chruby and rbenv, since they have predicates that perform similar comparisons. I grepped through the entire layers subdirectory and could not find other predicates affected outside +lang/ruby

**Comment by nixmaniack** [comment]
Indeed that is a bug. PR would be welcome. :smile:

**Comment by hagmonk** [comment]
I raised PR #4291 earlier for this ... what's the official way of linking the issue and the PR?

**Comment by StreakyCobra** [comment]
You linked them in both side, and the `PR pending` label is already there, nothing more to do here :-)

**Comment by nixmaniack** [comment]
[This](https://help.github.com/articles/closing-issues-via-commit-messages/) might be helpful if you want to close the PR/issue when the PR gets merged in `default` branch of the repo.

**Comment by hagmonk** [comment]
Ah-ha, got it. I thought the "PR pending" label indicated "we're waiting for a PR", rather than "this issue is pending PR approval". Thanks for clarifying! :)
