### ISSUE TITLE
Can zap-up-to-char function be added to spacemacs

### ISSUE THREAD

**Issue by fuzihaofzh** [syl20bnr/spacemacs#4290]
I'm using the function zap-to-char. However, it can only delete chars forward. Can you please add the back deletion to spacemacs?

some reference:
https://github.com/keithhamilton/spacemacs

**Comment by StreakyCobra** [comment]
It would be possible to help you better if your issue follows [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) :-) (i.e. reproduction guide especially)

**Comment by nixmaniack** [comment]
If you can get into `normal` state you can do `dt``<char>` . I'm not sure how you can achieve this in `emacs` state.

**Comment by lazywithclass** [comment]
I believe OP's suggestion is this:

```
(defun zap-up-to-char (arg char)
    "Kill up to, but not including ARGth occurrence of CHAR.
  Case is ignored if 'case-fold-search' is non-nil in the current buffer.
  Goes backward if ARG is negative; error if CHAR not found.
  Ignores CHAR at point."
    (interactive "p\ncZap up to char: ")
    (let ((direction (if (>= arg 0) 1 -1)))
      (kill-region (point)
                   (progn
                     (forward-char direction)
                     (unwind-protect
                         (search-forward (char-to-string char) nil nil arg)
                       (backward-char direction))
                       (point)))))
```

which he implemented in the linked repo.
