### ISSUE TITLE
Searching for program error

### ISSUE THREAD

**Issue by sho-87** [syl20bnr/spacemacs#4292]
I keep seeing this show up in my messages:
```
Error running timer `tern-reparse-on-idle': (file-error "Searching for program" "no such file or directory" "node") [3 times]

Error running timer `savehist-autosave': (file-error "Searching for program" "no such file or directory" "node")
```

The context surrounding that is often different (unused variables, undeclared variables, most likely due to some unrelated linting package?)

What could I look at to diagnose this problem?

**Comment by oneKelvinSmith** [comment]
I had this issue because I was using [nvm](https://github.com/creationix/nvm) and didn't load a node before starting emacs. So emacs couldn't find the tern binary. 

It solved it by including `nvm use stable --silent` in my shell config (i.e. config.fish, .bashrc or .zshrc)

**Comment by Peeja** [comment]
I have the same issue. Am I supposed to install `tern` globally as an npm package? It looks like it's supposed to come with the Emacs package.

**Comment by Peeja** [comment]
Oh, no, I misread the error. I have `"no such file or directory" "tern"`. Looks like I'm hitting something slightly different. :)

**Comment by TheBB** [comment]
No, you have to install tern separately.

**Comment by edrex** [comment]
I see this message when opening some Javascript files, and emacs becomes unresponsive. I installed tern with `npm install -g tern`, and now emacs doesn't lock up, but this is not ok behavior. It seems like the javascript layer should probe for tern and silently disable whatever functionality it is supposed to provide.

**Comment by Peeja** [comment]
I agree (although it might also be nice to give a message explaining that the functionality is off because tern is missing, and offering an option to explicitly turn off the functionality and the message).

**Comment by bgamari** [comment]
I am also seeing `emacs` hang on opening javascript files when `tern` is not installed. Features like tern are nice, but it seems to me like they should really be disabled if they can't robustly handle something as simple as a missing executable.

**Comment by nixmaniack** [comment]
@bgamari There _is_ such provisioning of conditional enabling of packages/layers (e.g. check [this](https://github.com/syl20bnr/spacemacs/blob/63df395975f336d09e4b3adc389f1de3dd82fb0c/layers/+lang/python/packages.el#L166)) but AFAIK there's no such convention in Spacemacs. You can surely go ahead and propose a PR if it's an issue with tern causing emacs to hang and make it unusable. 

IMO, If we go for disabling such features in case a particular executable is not found, then there has to be a better UX to let user know of what's missing and how to make better use of feature set provided by Spacemacs.

**Comment by Peeja** [comment]
Maybe a warning if it's not installed, with a variable to turn off the warning?

**Comment by felipe-barros** [comment]
This is really, really annoying.

**Comment by Peeja** [comment]
Thanks, @syl20bnr! 🍻

**Comment by NicoGim** [comment]
Hi! I am using the `develop` branch of Spacemacs and still facing similar issues:
`Error running timer: (file-missing "Searching for program" "No such file or directory" "tern") [2 times]
Error running timer ‘tern-reparse-on-idle’: (file-missing "Searching for program" "No such file or directory" "tern")`
Was solved by running `npm install -g tern`. That seems odd, it is an old bug.

**Comment by nixmaniack** [comment]
@NicoGim Just a couple troubleshooting instructions.

1. Is the binary present in your `$PATH`?
2. Is the PATH updated in your `.spacemacs.env` file — available via `SPC f e e`?
