### ISSUE TITLE
Ruby on rails layer key binginds doen't work

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#4296]
Key bingdings described in https://github.com/syl20bnr/spacemacs/tree/master/layers/+frameworks/ruby-on-rails#code-navigation doesn't work.

**Comment by StreakyCobra** [comment]
Can you please provide more explanations, like described [here](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? Especially the reproduction guide and the system description.

**Comment by Eilie** [comment]
@StreakyCobra Sure, sorry for late response.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion git ruby-on-rails yaml syntax-checking
                 (ruby :variables ruby-version-manager 'rbenv))
```
#### Reproduction guide
- Open controller file in Rails project and press `SPC m r f`.
- You'll get `SPC m r f in undefined error`.

**Comment by StreakyCobra** [comment]
You'll need help of ruby guys here, as I haven't any clue about this language :-) @brandoncc @robbyoconnor

**Comment by Eilie** [comment]
Created new issue with better description(less misleading and more concrete) - #4804.
