### ISSUE TITLE
undo behavior inconsistent with vim

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#4298]
First, `(setq evil-want-fine-undo 'No)`.

`u` after an atomic insert does not bring cursor back to where insert state was entered, but to some "Undo branch point!". Checking the undo tree with `spc a u` shows that undo tree is consolidating the buffer state when the text is the same into one node--if you return to this node with an undo operation, emacs brings you back to exactly that state, ignoring where your cursor should be. In vim, every undo brings your cursor back exactly where you entered the insert state (or delete operation, etc.).

Say you start with a block of text with point at "|":
```
Nullam eu ante vel est convallis dignissim. |Fusce suscipit, wisi nec facilisis
facilisis, est dui fermentum leo, quis tempor ligula erat quis odio. Nunc porta
vulputate tellus. Nunc rutrum turpis sed pede. Sed bibendum. Aliquam posuere.
Nunc aliquet, augue nec adipiscing interdum, lacus tellus malesuada massa, quis
varius mi purus non odio. Pellentesque condimentum, magna ut suscipit hendrerit,
ipsum augue ornare nulla, non luctus diam neque sit amet urna. Curabitur
vulputate vestibulum lorem. Fusce sagittis, libero non molestie mollis, magna
orci ultrices dolor, at vulputate neque nulla lacinia eros. Sed id ligula quis
est convallis tempor. Curabitur lacinia pulvinar nibh. Nam a sapien.
```
Press the following in quick succession: `ohello<esc>3johello<esc>`

As you have entered insert state from normal state twice, pressing `u` should undo the "hello"s typed during each insert state session one by one. However, they both get undone at once.

If you now delete some lines with `djujjjdju` etc., you will see some strange behavior with cursor placement and undos, not consistent with how vim behaves at all.

**Comment by robbyoconnor** [comment]
Not questioning the validity at all... but wouldn't this be an issue with evil, not spacemacs?

**Comment by sooheon** [comment]
@robbyoconnor that's true, and a quick search in the evil bitbucket led me to a previous issue. I'll continue discussion there. :)

**Comment by robbyoconnor** [comment]
:+1:

**Comment by TheBB** [comment]
The valid values for `evil-want-fine-undo` are `nil`, `fine` and `t`. `No` will be interpreted as `t` I believe. The docstring for this variable is misleading.

**Comment by TheBB** [comment]
Ref. the definition.

![](http://i.imgur.com/wihy3KF.png)
