### ISSUE TITLE
ediff mode

### ISSUE THREAD

**Issue by vitiral** [syl20bnr/spacemacs#4300]
When I type `SPC f e D` it opens an `*Ediff Control Panel*` buffer on my `.spacemacs` file. However, vim-like commands do not work, including `SPC` commands.

I looked at #695, and from that it looks like "ediff mode" is supposed to be in the core, however it doesn't appear to be for me.

I have the `version-control` layer enabled, and from `f e h` it looks like that is the only layer that does anything with ediff. Is there something else I need to be doing to get evil-mode like commands in diff?

In particular, I would like to be able to use emacs similar to vimdiff (but hopefully better, like every other feature I've seen so far!)

**Comment by TheBB** [comment]
Ediff is configured but not evilified in any way. At the moment it only works with Emacs key bindings.

**Comment by justbur** [comment]
Just curious. What would evilified ediff look like exactly?

**Comment by vitiral** [comment]
I'm not super experienced with ediff and it's power (I would like to learn more) but as for "evilfied" bindings I would think the following would be good:
- `j/k` moves normally (allowing you to manually edit text by going to insert mode, like in vimdiff -- is this possible?)
- `C j/k` moves up/down between diffs in the current window (similar to helm functionality)
- `SPC m` commands that deal with layer specific functionality:
    - maybe `SPC m h/l` merged the selected diff to the buffer on the left/right (diffput) and `SPC m H/L` pulls FROM the left/right into the current diff (diffget)
    - `SPC m g` is the "get" macro -- `SPC m g 1` gets from window 1 into the current window diff (windows would always be organized `1 | 2 | 3`). This can also be done with `SPC m g h` to get from the left.
    - `SPC m p` is the "put" macro -- `SPC m p 1` puts the current diff into window 1. Could also be done with `SPC m p h` to put left.

Those are some initial thoughts

**Comment by justbur** [comment]
@vitiral I made a simple package to make the ediff bindings a little more evil friendly. Let me know what you think https://github.com/justbur/evil-ediff

**Comment by vitiral** [comment]
Hey @justbur, ya those all look pretty reasonable. Unforuntely I can't install it because I'm not sure how to install from github (I will read into it more, but `use-package` doesn't seem to work, which is what I've been using!)

**Comment by justbur** [comment]
@vitiral just download the .el file or clone the repo through git and load it in user-config with `(load "path/to/evil-ediff.el")`

**Comment by vitiral** [comment]
everything looks really good. Only thing that could be added would be the `SPC m` functionality... but honestly I think that people should just learn `ediff`, because (besides movement keys) it looks like a better interface than vimdiff ever was.

Thanks @justbur!

**Comment by justbur** [comment]
@vitiral There are some things I miss from vimdiff (mainly the folding), but they're not simple to add unfortunately. Overall I think ediff is easier to use once you get the hang of it.

**Comment by StreakyCobra** [comment]
@justbur Are you planning to add your package to the default spacemacs layer? It would be very valuable :-)

**Comment by justbur** [comment]
Submitted to Melpa. I can add it after it's available

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by achikin** [comment]
I still have no idea what keybindings are in ediff mode.
Standard one does not work, evil-ediff does not work either.

**Comment by bobpaul** [comment]
@achikin First, make sure you're in the ediff window. You'll see it says to press ? for help. Pressing ? will show the full list of keybindings. But the main ones are:

 h j k l in the ediff window will navigate both windows together.

Ctrl+j and C+k will jump between differences (and highlite them green/red). This synchronizes the windows.

a/b to select the chunk for the left or the right. ra/rb to restore the original chunk on the left or the right.

**Comment by i-am-the-slime** [comment]
How do you finish at the end?
