### ISSUE TITLE
support multi emacs?

### ISSUE THREAD

**Issue by declanqian** [syl20bnr/spacemacs#4302]
I hava a scenario: I hava multi version emacs installed on mac. One from the brew install emacs --HEAD and one from brew install emacs-mac. When I installed all the packages using the head version emacs, then sometimes I decided to switch to emacs-mac for some reason. The previously installed and compiled package just won't work. Then I have to backup the ./elpa  and ./.cache foler, and reinstall the packages. I guess this is the right way to do this, right? Is there any possibilities to add a sub directory in
the elpa with the name of current emacs version number? I see this because I notice that the Cask https://github.com/cask/cask does this way.
![Cask package dir]
(https://pbs.twimg.com/media/CXRSQ6-VAAAQmTG.png:large)

Ignore this if think this the wrong way!

**Comment by TheBB** [comment]
See #3379 and #3384. Especially the latter has some discussion on the pros and cons of this, and possible workarounds. Closing this as a duplicate.
