### ISSUE TITLE
Inputting "fd" fast in INSERT mode causes exiting INSERT mode.

### ISSUE THREAD

**Issue by zentorwie** [syl20bnr/spacemacs#4306]
This bug occurs when I am writing a C program about socket.

I want to input the following code:
```
int fd; // file descriptor
int qlen;
// ...
```
and in INSERT mode, if I input "fd" fast, the string "fd" is deleted and the Emacs exits INSERT mode immidiately.

To avoid this I have to input "fd" not so fast. It's really annoying!

Anyone has the same problem? Your can try inputting "fd" **fast**.

Newly installed spacemacs. Reinstalling can't fix it.

Spacemacs version: 0.104.8
Emacs version: 24.5

**Comment by zentorwie** [comment]
Inputting "fd" in VISUAL mode is similar. I return to NORMAL mode at once.

**Comment by cpaulik** [comment]
I think this is because [evil-escape](https://github.com/syl20bnr/evil-escape) is enabled by default.

You can put the package in your `dotspacemacs-excluded-packages` variable to disable it

**Comment by cpaulik** [comment]
Or for configuration you can find more information in the Documentation in [this section](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#escaping)

**Comment by TheBB** [comment]
As @cpaulik says, this is a feature. You can follow his advise for changing the shortcut or disabling it entirely.

**Comment by zentorwie** [comment]
@cpaulik @TheBB Thanks!

**Comment by padraic00** [comment]
Has anyone come up with a better keybinding than 'fd'?
