### ISSUE TITLE
Clojure mode: unable to delete single parens in comments

### ISSUE THREAD

**Issue by huahaiy** [syl20bnr/spacemacs#4315]
E.g. 

;; This is in comment :-)

Deleting the above line still leaves ")" in place

**Comment by TheBB** [comment]
You probably have smartparens strict mode turned on.

**Comment by huahaiy** [comment]
Yes. Wouldn't it be nice that smartparens strict mode ignores comments?

**Comment by TheBB** [comment]
https://github.com/Fuco1/smartparens

**Comment by huahaiy** [comment]
OK. Reported upstream. Thanks!
