### ISSUE TITLE
Expose keymaps created by macros and document them

### ISSUE THREAD

**Issue by vkz** [syl20bnr/spacemacs#4319]
Things like `spacemacs|define-micro-state` hide maps being created so the only way to customize bindings is copy-paste the entire thing with your modifications.

Case in point is `layouts` layer.

**Comment by justbur** [comment]
This can be done now on develop. It's not well documented at the moment, but to add key bindings you just have to set the right variable

```elisp
(setq spacemacs-layouts-transient-state-add-bindings '(("a" func1 "hint for func1")
                                                       ("b" func1 "hint for func2")))

(setq spacemacs-layouts-transient-state-remove-bindings '("a" "b"))
```
