### ISSUE TITLE
Regular hangs / crashes in OS X.

### ISSUE THREAD

**Issue by noelwelsh** [syl20bnr/spacemacs#432]
At least once a day I'm seeing Spacemacs hang with a spinning beachball in OS X. It becomes unresponsive to all input, including C-g, and I have to Force Quit Emacs. Funnily enough, the first time I try to restart Emacs it will also hang before it even displays a window. I have to Force Quit again and then finally I can successfully restart Emacs.

I have recently switched to both Spacemacs and Yosemite. I never experienced this sort of instability beforehand. 

I doubt anyone can actually suggest anything useful to resolve the problem, but it would be interesting to know if others see this issue. It's getting to the stage where I'm considering running Emacs within a Linux VM to see if that makes it more stable.

I have been using Emacs for OS X. I'm now trying emacs-mac-port to see if it behaves differently.

**Comment by chrisbarrett** [comment]
FWIW, startup hangs on the official Mac app have been been a recurrent issue for me for a couple of OS versions. I don't have that issue with `emacs-mac-port`.

**Comment by bjarkevad** [comment]
@chrisbarrett :+1: Same here

**Comment by syl20bnr** [comment]
@noelwelsh thanks for the report. Another user add crashes with a particular font, I think it is @smt (sorry if that person is not you).

Let us know if you have still crashes with `emacs-mac-port`.

**Comment by noelwelsh** [comment]
No crashes after two days with `emacs-mac-port`, so I'm closing this. Thanks for the helpf!

**Comment by srid** [comment]
What is emacs-mac-port? Are you all referring to [this](https://github.com/railwaycat/emacs-mac-port)? Because even that doesn't fix this problem.

**Comment by noelwelsh** [comment]
I install `emacs-mac-port` via homebrew. The repo you linked to is out of date but the homebrew install should be up-to-date.
