### ISSUE TITLE
documentation toc inside spacemacs broken

### ISSUE THREAD

**Issue by mnlgn** [syl20bnr/spacemacs#4322]
When I try to read the documentation using the table of contents, spacemacs won't jump to the corresponding section. It seems like org can't find the target id: "No match - create this as a new heading?"

Emacs version: 24.3.1

**Comment by mnlgn** [comment]
![bildschirmfoto vom 2015-12-30 06 25 58](https://cloud.githubusercontent.com/assets/1057526/12046704/3816f2ec-aebe-11e5-9039-083c41510d38.png)

**Comment by mnlgn** [comment]
They're all broken, doesnt matter which doc or readme I try.

**Comment by StreakyCobra** [comment]
You can try:

- enabling the `org` layer if not already
- updating your packages (`[Update]` button on *spacemacs* buffers)

but it may also be related to your emacs version.

**Comment by mnlgn** [comment]
enabled org layer and updated to latest 24.5.1, works there!
