### ISSUE TITLE
Laggy scrolling using railwaycat/emacs-port

### ISSUE THREAD

**Issue by landaire** [syl20bnr/spacemacs#4323]
I know this has been discussed many times over but I think that this is a deeper problem with Spacemacs in some way.

Here's a video of out of the box scrolling (no emacs plugins): https://youtu.be/05Svv4Erkz8
And with spacemacs, same file: https://youtu.be/fIpGkjX3dVk

The difference is pretty clear. The D layer I think is just poorly optimized or something since there's other issues with it and scrolling is _slightly_ better for some random Go file I tried.

Does anyone have any tips for debugging what might be the offending layer(s)? Even with all extra packages disabled I still get some slight lag when scrolling.

It's worth noting that I do not have the same issue when building from HEAD with `brew install emacs --HEAD --use-git-head --with-cocoa --srgb`... but that doesn't give pixel scrolling.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. dee5d73)
- Distribution: spacemacs
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp git
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking version-control d go rust elixir swift yaml latex markdown osx spacemacs-layouts)
```

**Comment by louwers** [comment]
Native scrolling with `mac-emacs`is indeed very jerky and nearly unusable. Some related discussion [here](https://github.com/syl20bnr/spacemacs/issues/1114). I get the same result regardless of language.

**Comment by landaire** [comment]
Wow, I had seen that thread before but figured that I should be getting similar results with Fira Code. I just tried Fira Mono and got better results. Messing with unicode symbols doesn't seem to have a big affect.
