### ISSUE TITLE
Spacemacs should use `ido-grid-mode` instead `ido-vertical-mode`

### ISSUE THREAD

**Issue by gfZeng** [syl20bnr/spacemacs#4324]
<https://github.com/larkery/ido-grid-mode.el>

**Comment by syl20bnr** [comment]
Why ? :-)

**Comment by tuhdo** [comment]
It saves spaces, especially on large screen. It's better to navigate files with that package.

**Comment by gfZeng** [comment]
@syl20bnr 
list item can keep static. And need not reorder.
<https://github.com/creichert/ido-vertical-mode.el/issues/19>

**Comment by syl20bnr** [comment]
Ok I understand now, seems that static list implementation in `ido-vertical-mode` has been stopped in favor of this new package: https://github.com/creichert/ido-vertical-mode.el/pull/29

I'll try it :-)
