### ISSUE TITLE
react layer company-tern not work

### ISSUE THREAD

**Issue by chenxs110** [syl20bnr/spacemacs#4326]
#### Description
react layer's auto-completion backend company-tern not work.

#### Reproduction guide
- Enable react layer
- Start emacs
- Edit one jsx or react.js file

#### System Info
- OS: darwin
- Emacs: 24.4.1
- Spacemacs: 0.104.8
- Spacemacs branch: nil (rev. 44d4525)
- Distribution: spacemacs
- Layers:
```elisp
(org markdown javascript syntax-checking perspectives semantic
     (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode :variables c-c++-enable-clang-support t)
     scheme emacs-lisp html deft gtags ycmd osx ranger xkcd react
     (auto-completion :variables auto-completion-enable-snippets-in-popup t)
     (python :variables python-enable-yapf-format-on-save t python-test-runner 'pytest)
     (git :variables git-magit-status-fullscreen t)
     (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh")
     chenxuesong)
```

#### Backtrace
Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-frontend error "Company: backend (company-tern :with company-yasnippet) error "Wrong number of arguments: (1 . 2), 3" with args (pre-render React nil)" on command post-command

**Comment by StreakyCobra** [comment]
Can you update your message to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? It will be easier to help you :-) Thanks

**Comment by chenxs110** [comment]
ok.
it's bug of company-tern package.
https://github.com/company-mode/company-mode/issues/441

**Comment by StreakyCobra** [comment]
:+1: Thanks
