### ISSUE TITLE
input quotation marks not consistent when empty string or not empty string

### ISSUE THREAD

**Issue by Treri** [syl20bnr/spacemacs#4327]
In insert mode, if I input a single `'` quotation mark, spacemacs will output a pair `''`. Then I input some content normally. Then I input another `'`, the cursor just jump out the quotation mark pair. This is also I wanted.

But If I input a empty string using `''`, when I input a single `'`, spacemacs will output a pair `''`, and the cursor is in center of quotation mark pair. Then at this time, if I input another single `'`,  another pair quotation marks appears. now I have four single quotation mark `''''`, and my cursor is in center.

Can I just jump out quotation marks even if empty string in quotation mark when I input another quotation mark?

**Comment by d12frosted** [comment]
In which mode do you experience this? Also, could you please paste the output of `SPC h d s`? :)

**Comment by Treri** [comment]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: doc-fix (rev. 82c5ce9)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp auto-completion better-defaults
            (chinese :variables chinese-default-input-method 'wubi chinese-enable-fcitx t)
            git version-control html
            (javascript :variables js2-basic-offset 2 js-indent-level 2)
            lua markdown org php python shell shell-scripts sql typescript yaml osx)
```

in php-mode

@d12frosted

**Comment by TheBB** [comment]
Yes, this is annoying sometimes. See https://github.com/syl20bnr/spacemacs/issues/2097 and the linked smartparens issue.

I'm closing this as a duplicate.

**Comment by Treri** [comment]
Thanks
