### ISSUE TITLE
projectile commands should respect buffer isolation promised by layouts (perspectives)

### ISSUE THREAD

**Issue by vkz** [syl20bnr/spacemacs#4330]
#### Description
- `projectile-kill-buffers` removes buffers from all layouts (perspectives) and therefore breaks the promise:
  
  > window configurations that have buffer isolation between each other
- same project buffers explicitly opened via say `helm-projectile` (but not limited to that command) will only exist in one layout with the exception of a single common buffer
#### Reproduction guide
- create **project1** layout
- open several files from some git-tracked project
- create **project1-copy** layout
- open several files from the same git-tracked project, make two sets of files in both layouts have at least two files in common

DESCRIPTION OF THE OBSERVED BEHAVIOUR
- `spacemacs/persp-helm-mini` in **project1-copy** shows buffer corresponding to a single common file
- `projectile-kill-buffers` removes project buffers from all layouts that have them

DESCRIPTION OF THE EXPECTED BEHAVIOUR
- files opened explicitly in several layouts should persist in those layouts
- `projectile-kill-buffers` should respect buffer isolation promised by layouts and therefore effect only current layout. This should probably be true of all or most `projectile-...` commands
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 9642c35)
- Distribution: spacemacs
- Layers:

``` elisp
(spacemacs-layouts eyebrowse clojure
                   (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip nil auto-completion-enable-sort-by-usage t :disabled-for org erc)
                   emacs-lisp
                   (haskell :variables haskell-process-type 'stack-ghci haskell-enable-shm-support t haskell-enable-hindent-style "chris-done" haskell-enable-ghc-mod-support t)
                   git github
                   (shell :variables shell-default-shell 'eshell shell-default-position 'full shell-default-term-shell "/bin/bash" shell-enable-smart-eshell t)
                   themes-megapack theming colors version-control restclient sexy key-seq)
```

**Comment by StreakyCobra** [comment]
It would be nice to update your issue to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) :-)
