### ISSUE TITLE
`K` is not mapped to discard changes in magit status buffer

### ISSUE THREAD

**Issue by micahbf** [syl20bnr/spacemacs#4331]
The git layer docs specify:

> `hjkl` navigation is enabled in all Magit buffers. The default Magit keys on `hjkl` (if they exist) are remapped on `HJKL`.

Magit help specifies that `k` discards the changes of the specified file or hunk (`magit-discard`). However, pressing `K` on a file in a magit status buffer runs `magit-file-untrack`.

**Comment by StreakyCobra** [comment]
On the `master` branch, the support of magit is not optimal. The `develop` branch uses [`evil-magit`](https://github.com/justbur/evil-magit) that integrates better `magit` with `evil`. Should be released soon :-)

**Comment by micahbf** [comment]
Great, thanks!
