### ISSUE TITLE
The tab width can not set 4 spaces for existing java codes

### ISSUE THREAD

**Issue by chaozhn** [syl20bnr/spacemacs#4333]
I'm not sure if this is a problem but I can not google a solution for it.
I'm rookie for Emacs and starting to transfer from vim to spacemacs, I used eclim+eclipse to edit java in vim before, so I tried to configure the same things in spacemacs and looks like it works well except tab width.
I googled how to set tab width with 4 and followed other guy's setting:
````   
(setq-default tab-width 4)
(setq-default c-basic-offset 4)
(setq-default indent-tabs-mode t)
````
I put these codes under *(defun dotspacemacs/user-config ()*, but when I opened a java file, the tab width is still 2 spaces for existing codes, if you click 'RET' to insert new line, the tab width is right with 4 spaces, I don't know why the existing codes still use 2 spaces for tab width, is something wrong with my settings? 
BTW, the spacemacs is gorgeous, love it and thanks for your dedication!

**Comment by Treri** [comment]
Maybe this?
```lisp
(add-hook 'prog-mode-hook
    (lambda ()
      (setq-default tab-width 4
                    c-basic-offset 4)
      (setq tab-width 4
            c-basic-offset 4)))
```

**Comment by chaozhn** [comment]
@Treri Thanks a lot, I put it in *user-init()* section and it works now. BTW, do you know this warning when start spacemac:
````
Wrong type argument: symbolp, (quote (eclim-executable "~/eclipse-luna/eclim"))
````
I followed java setting guide from spacemac to enable eclim and put the following setting in my .spacemac:
````
(setq eclim-eclipse-dirs '("~/eclipse-luna") '(eclim-executable "~/eclipse-luna/eclim"))
````
Seems, the eclim can work, but I don't know why it is showing, if you know, please tell me, thanks a lot!

**Comment by TheBB** [comment]
It's a documentation bug. It has been fixed in develop.

https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/java#installation

Sounds like this can be closed, then? Let me know if not. :-)

**Comment by chaozhn** [comment]
@TheBB Thank you. It's ok now
