### ISSUE TITLE
error: Required feature `dash' was not provided

### ISSUE THREAD

**Issue by derekcn** [syl20bnr/spacemacs#4336]
I upgrade spacemacs, and when restart emacs, found:

**Warning (initialization): An error occurred while loading `/home/user/.emacs.d/init.el':**

**error: Required feature `dash' was not provided**

**To ensure normal operation, you should investigate and remove the**
**cause of the error in your initialization file.  Start Emacs with**
**the `--debug-init' option to view a complete error backtrace.**

So, how to fix this.

**Comment by TheBB** [comment]
> Start Emacs with the `--debug-init' option to view a complete error backtrace.

This is a start…

**Comment by derekcn** [comment]
yes, thanks. I found dash.el and dash.elc in elpa/dash-20151216.1315/ were both corrupted. so i download dash.el from melpa.org manually and remove dash.elc, now it works.
