### ISSUE TITLE
Django layer won't start server or run tests

### ISSUE THREAD

**Issue by jschnurr** [syl20bnr/spacemacs#4338]
After enabling the `Django` layer via `.spacemacs`, and following the configuration at [deadpansincerity.com](http://www.deadpansincerity.com/docs/pony/configuration.html), I'm unable to get the pony-mode functions to work correctly. 

My .dir-locals.el is as follows:

``` elisp
((nil . ;; This applies these settings regardless of major mode
      ((pony-settings (make-pony-project
                       :python "/home/jschnurr/.virtualenvs/djvid/bin/python"
                       :pythonpath "/home/jschnurr/dev/djvid"
                       :settings "settings")
                      ))))
```

**Symptoms include:**
1.  `SPC m j i s` (pony-shell) and `SPC m j r u` (pony-runserver) exit with TypeError: relative imports require the 'package' argument (full trace below)
2.  `SPC m j t t` (pony-tests) exits with `split-string: Wrong type argument: stringp, nil`
Pony mode will not start successfully.

Interestingly, `SPC m j f s` (pony-goto-settings) works correctly - it opens my settings file.

I'm assuming the errors are related to some setup-related common cause, but despite my experimentation with different settings, I've not been able to spot a pattern.  Any ideas? 

**Environment:**
Emacs: _GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2015-12-19_
Spacemacs: _spacemacs-0.104.8_

**Subset of my folder structure:**

``` bash
── .dir-locals.el
├── djvid
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
── manage.py
── spider
│   ├── admin.py
│   ├── models.py
│   ├── tests
│   │   └── testspiders.py
│   └── views.py
```

**Steps to reproduce:**
1.  Start emacs from the command line with `emacs &`
2.  `M-x pyvenv-workon`, select `djvid`
3.  `SPC f f` to select `urls.py` 
4.  Answer `y` to the Emacs prompt _The local variables ... do you want to apply it?_
5.  `SPC m j i s`

**Result:**

``` bash
Traceback (most recent call last):
  File "/home/jschnurr/dev/djvid/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jschnurr/.virtualenvs/djvid/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/jschnurr/.virtualenvs/djvid/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/home/jschnurr/.virtualenvs/djvid/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/jschnurr/.virtualenvs/djvid/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/jschnurr/.virtualenvs/djvid/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 30, in import_module
    raise TypeError("relative imports require the 'package' argument")
TypeError: relative imports require the 'package' argument

Process ponysh exited abnormally with code 1
```

**Comment by StreakyCobra** [comment]
May [this](http://stackoverflow.com/a/22176915/2311626) help (I really don't know, just googled it :-) )

**Comment by jschnurr** [comment]
That error is produced when ```pony-manage-pop``` outputs this: 
```elisp
Result: ("/home/jschnurr/dev/djvid/manage.py" "shell" "--settings=.settings" "--pythonpath=/home/jschnurr/dev/djvid")
```
import_module interprets the leading ```.``` as a file path, prompting the error.

```pony-manage-pop``` should return ```--settings=djvid.settings```, but ```djvid``` isn't being returned by ```pony-project-package``` as expected; instead, I'm getting NIL.

Tracing that further, I discovered that ```pony-project-package``` returns NIL when called from some project buffers, but not others.  

To debug that, I need to step through ```pony-project-package```, but I can't figure out how to step into a lambda.  When a lambda function is assigned to a variable, how do you step into the function when that variable is evaluated?
