### ISSUE TITLE
`K` runs `org-agenda-previous-line` instead of hiding habits in org-agenda

### ISSUE THREAD

**Issue by Andre0991** [syl20bnr/spacemacs#4339]
Steps to reproduce: 

Add `org-habit` to `org-modules` using the customize interface.

By default, when using `org-habits`, in org's agenda view, `K` (upper case `k`) hides tasks that are habits (see the last sentence of [this page](http://orgmode.org/manual/Tracking-your-habits.html)).

However,  currently `K` activates `org-agenda-previous-line` in agenda view.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: nil (rev. dee5d73)
- Distribution: spacemacs
- Layers:

``` elisp
(osx emacs-lisp git
     (shell :variables shell-default-shell 'eshell)
     eyebrowse erc python themes-megapack semantic
     (c-c++ :variables c-c++-enable-clang-support t)
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for org erc latex)
     org markdown latex spell-checking syntax-checking version-control)
```

**Comment by StreakyCobra** [comment]
For the record, the functionality seems to be bound to `K` in `org-habit` ([line 419](http://orgmode.org/cgit.cgi/org-mode.git/tree/lisp/org-habit.el#n419)). It's maybe not used, or it is maybe overridden by some Spacemacs configurations. Need further analyses.

**Comment by Andre0991** [comment]
Oh, yeah, `org-habits` has to be used to get `K` to hide habits in the agenda view. I edited the post to clarify this, thanks.
