### ISSUE TITLE
A question about ycmd, Ycmd server is timeout

### ISSUE THREAD

**Issue by chaozhn** [syl20bnr/spacemacs#4340]
I have vim working with ycmd. And now I'm trying the spacemacs with ycmd. I followed the  guid in Youcompleteme homepage to compile it and no error found. Then I configured the ycmd in .spaceemacs, First, I added layer ycmd in:
````
dotspacemacs-configuration-layers
'(
  ycmd
````
Second, I set the ycmd-server-command:
````
  (add-hook 'objc-mode-hook 'ycmd-mode)
  (add-hook 'c-mode-hook 'ycmd-mode)
  (set-variable 'ycmd-server-command '("python" "~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd"))
````
When I open a objective-c file, the message told me that **Ycmd server time out**, I turned on ycmd-log and it reported:
````
/usr/bin/python: can't open file '~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd': [Errno 2] No such file or directory

Process ycmd-server exited abnormally with code 2
````
I don't know why, I can make sure the path is ok, but I'm not sure if I give a right path for ycmd server. Could you please help me? 
BTW, vim can work with YCM. Spacemacs and YCM are both latest version.
Thanks a lot!

**Comment by StreakyCobra** [comment]
> `/usr/bin/python: can't open file '~/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd': [Errno 2] No such file or directory`

This message seems pretty clear to me, it says the file doesn't exist. Maybe it's not the right path (2 times `ycmd` at the end?) or maybe `~` is not accepted (`/home/…/.vim/…` being needed?).

**Comment by chaozhn** [comment]
@StreakyCobra Thanks. This is the content under this path:
````
__init__.py            handlers.py            identifier_utils.pyc   server_state.py        utils.py
__init__.pyc           handlers.pyc           request_validation.py  server_state.pyc       utils.pyc
__main__.py            hmac_plugin.py         request_validation.pyc server_utils.py        watchdog_plugin.py
completers             hmac_plugin.pyc        request_wrap.py        server_utils.pyc       watchdog_plugin.pyc
default_settings.json  hmac_utils.py          request_wrap.pyc       tests
extra_conf_store.py    hmac_utils.pyc         responses.py           user_options_store.py
extra_conf_store.pyc   identifier_utils.py    responses.pyc          user_options_store.pyc
````
Is this folder right? I don't know which folder I should give, just referred to other guys' configurations and changed to my path accordingly. Seems I can't find more details about it in **emacs-ycmd** guide. Thanks a lot!

**Comment by chaozhn** [comment]
@StreakyCobra Sorry, my mistaken. You're right, the **~** can't be recognized. Thanks again. I will close it.

**Comment by StreakyCobra** [comment]
I don't know, I'm not using this tool, it's the first time I hear about it. For sure it's a PATH problem, but you will need help from someone else that actually knows it :pensive:
