### ISSUE TITLE
[Add Issue] page should link to Bug Report Template

### ISSUE THREAD

**Issue by vkz** [syl20bnr/spacemacs#4346]
Please consider adding [link to bug report template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) to the Add Issue page on GitHub alongside you **guidelines for contributing** if you want people actually using it to submit bugs. Thx

**Comment by TheBB** [comment]
As far I know this isn't possible, but we can add it to the contribution guidelines instead.

**Comment by StreakyCobra** [comment]
I've already added this link to the [new `CONTRIBUTING.org` file](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#reporting-issues) that will be linked on the issues/PR creation page with the next release.

The page is not correctly named and the template has to be discussed and improved, so for now the template is not forced, just pointed to when issues are incomplete. When I'll have enough time I'll finalize this and we will think about making the template mandatory. Also some techniques would be used to help people, like using a link that pre-fill the issue (https://github.com/isaacs/github/issues/99#issuecomment-24584307) with the template.
