### ISSUE TITLE
nix-mode reindents multi-line yanks

### ISSUE THREAD

**Issue by zopa** [syl20bnr/spacemacs#4348]
Say I have this nix snippet: 

```
options = {

   enable = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Whether to sync mail with offlineimap
      '';
    };
};
```

and starting from 'enable' I do `7yyP`. I get:

```
    enable = mkOption {
              type = types.bool;
                        default = false;
                                  description = ''
                                              Whether to sync mail with offlineimap
                                                        '';
                                                                };
```

with the helpful message "Indenting region...done". So the first line aligns correctly, and subsequent lines are indented, leading whitespace and all.

Vanilla emacs with nix-mode.el loaded does not do this (using C-u 7 C-k and C-y).
#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.104.8
- Spacemacs branch: master (rev. 44d4525)
- Distribution: spacemacs
- Layers:

``` elisp
(chrome emacs-lisp haskell markdown nixos org)
```

**Comment by CestDiego** [comment]
this is a problem from the nix-mode package...can you reproduce with a barebones emacs?

**Comment by CestDiego** [comment]
I'm at a loss, I thought this was `nix-mode` package's fault.
