### ISSUE TITLE
rcirc-track-minor-mode not showing in modeline?

### ISSUE THREAD

**Issue by TrisMcC** [syl20bnr/spacemacs#435]
I am looking for where rcirc-track-minor-mode (which is enabled, and seems to get enabled by default) inserts a notification in the modeline. Is it not supported, or is it so subtle I don't notice it?

**Comment by MaxMartin** [comment]
Yeah, seems like this is clobbered by the powerline stuff. Is there any way to toggle that off so that you can see the rcirc-track-minor-mode display?

**Comment by TheBB** [comment]
Since rcirc-track uses global-mode-string, this should have been fixed with the recent modeline refactoring.
