### ISSUE TITLE
pdf-tools layer

### ISSUE THREAD

**Issue by Andre0991** [syl20bnr/spacemacs#4350]
[pdf-tools](https://github.com/politza/pdf-tools) renders `pdf` files and has features like loading pages on demand (`docview`, on the other hand, loads the whole file at once), annotation and outline navigation.

Currently, it doesn't work well with `evil-mode`, as its keybindings are overwritten. It would be nice to define `j`, `k`, etc. to do what we are used to have in other modes. We could discuss the keybindings here.

One problem is that its installation requires external packages, so I think we could make a layer just for the keybindings, assuming that the user already installed it properly.

What do you guys think about it?

**Comment by QiuMP** [comment]
Yes, I agree with you. I installed it in my Spacemacs, but the default keybindings are not proper with `evil-mode`. It's helpful if having a layer with it.

**Comment by robbyoconnor** [comment]
PRs welcome and appreciated!

**Comment by Andre0991** [comment]
Nice, I'll start it today then.

**Comment by Andre0991** [comment]
Pull request:

https://github.com/syl20bnr/spacemacs/pull/4627

**Comment by agzam** [comment]
Can someone tell me how to use it on OS X?

**Comment by izahn** [comment]
@agzam https://github.com/politza/pdf-tools#compiling-on-os-x

**Comment by agzam** [comment]
@izahn it didn't work for me. I had to install both `poppler` and `clisp` through brew.

**Comment by izahn** [comment]
@agzam If you think the pdf-tools documentation is incorrect or incomplete you can open an issue at https://github.com/politza/pdf-tools/issues. The dependency on `poppler` is documented; I don't see any mention of `clisp` at all in the pdf-tools repository.

**Comment by syl20bnr** [comment]
Fixed in develop
