### ISSUE TITLE
spacemacs/write-file doesn't working in indirect buffers

### ISSUE THREAD

**Issue by jschaf** [syl20bnr/spacemacs#4353]
`<Space-fs>`, `spacemacs/write-file` prompts for a file name in [indirect buffers](http://www.gnu.org/software/emacs/manual/html_node/emacs/Indirect-Buffers.html).  Indirect buffers are clones, so saving should be exactly the same as the original buffer.

`save-buffer`, `C-x C-s` works appropriately and saves the underlying file without prompting.

To reproduce:

1. Open a buffer
2. `M-x clone-indirect-buffer-other-window` or `C-x 4c`
3. Make a change in the indirect buffer.
4. Save file with `<Space>fs`, Emacs will prompt for the file to save to.

**Comment by cpaulik** [comment]
Please see the PR. I think using the built-in `save-buffer` function is the way to go.

**Comment by CestDiego** [comment]
@syl20bnr the PR mentioned seems to be the solution
