### ISSUE TITLE
Error in python layer

### ISSUE THREAD

**Issue by woonchao** [syl20bnr/spacemacs#4357]
Hi, I have some problems when I add python layer to my dotfile, when I open a python file, anaconda-mode get error log like this. 
```
Traceback (most recent call last):
  File "/usr/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 45, in <module>
    from .config.loader import Config
  File "/usr/lib/python2.7/dist-packages/IPython/config/__init__.py", line 16, in <module>
    from .application import *
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 32, in <module>
    from IPython.config.configurable import SingletonConfigurable
  File "/usr/lib/python2.7/dist-packages/IPython/config/configurable.py", line 32, in <module>
    from .loader import Config, LazyConfigValue
  File "/usr/lib/python2.7/dist-packages/IPython/config/loader.py", line 34, in <module>
    from IPython.utils.path import filefind, get_ipython_dir
  File "/usr/lib/python2.7/dist-packages/IPython/utils/path.py", line 22, in <module>
    import tempfile
  File "/usr/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
ImportError: cannot import name Random
```
But I didn't do anything to import random.
Anyone have idea to this?

**Comment by a-sk** [comment]
1. Could you please provide more information about your setup - paste the output of `SPC h d s` here.
2. Does, by any chance, there is a file called `random.py` in the same directory as the file you want to edit?

**Comment by woonchao** [comment]
ok, the messages are as follows:
```
error in process sentinel: anaconda-mode-install-sentinel: Can't install `anaconda-mode' server
error in process sentinel: Can't install `anaconda-mode' server
```
Maybe, there is something wrong about the installation of anaconda.

**Comment by cpaulik** [comment]
Do you have a working `pip` installation? Anaconda-mode can not install itself without it.

**Comment by woonchao** [comment]
yes, to be sure I have just upgrade `pip`, but it dosen't work.

**Comment by woonchao** [comment]
I have install `anaconda-mode` in `pip`, and add the layer of `python` in dotfile.
I wonder what does ‘**can't install**’ mean? 
```
Can't install `anaconda-mode' server
```

**Comment by cpaulik** [comment]
It means that the following python code does not exist with status 0.
```python
import sys
import pip
directory = sys.argv[-2]
version = sys.argv[-1]
pip.main(['install', '-t', directory, 'anaconda_mode==' + version])
```

What is the output of
```elisp
(executable-find "ipython")
```
or 
```elisp
(executable-find "python")
```
?

Do you have more than one python version installed?

**Comment by woonchao** [comment]
yes,  I have python2.7.9 and python3.4.2 in my system, when I run 
```
$ >which python
$ > /usr/bin/python
```
It refer to python2.7.9
I don't have ipython.
What should I do to solve the problem? Thank you for your patience.

**Comment by cpaulik** [comment]
You must have Ipython since it is mentioned in the original error.

The first step that I would take is to make sure that emacs uses the correct python version. You can then also try to run the code anaconda mode tries to run manually to see if it works. 

Since you claim to not have IPython but the error refers to an IPython installation this might indicate a broken IPython installation?

**Comment by woonchao** [comment]
Thx for your patience, I try to re-install pip, ipython and anaconda-mode, but it doesn't work. 
It's this a bug for anaconda-mode? Emacs do have write access to the directory of `~/.emacs.d/.cache/` but the message said can't make directory, I don't know why. 

After remove the layer of python, it's ok, but I can't use auto-complete now.

**Comment by woonchao** [comment]
Well, after I do as `https://github.com/proofit404/anaconda-mode/issues/153`and re-install spacemacs it works.  It seems a broken package caused by my poor proxy. :) thx
