### ISSUE TITLE
When window recentering while region-staging in magit one loses selection

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#4362]
to replicate bug, have many lines not staged and try to select them by `v C-j` or `v <down>`, the lines have to be enough so that they occupy more than one "page".

You'll see that your selection that you took time to make is unselected, every time. If you center the whole selection you want in one "page" this doesn't happen, so it's not about the length in lines of the selection as much as just whether it's on more than one page or not.

**Comment by tarsius** [comment]
What's a "page"? Do you mean "hunk", i.e. the unit beginning with a line that begins with `@@` and ends before the next such line, the next file in the diff, or the end of the diff?

If so, then that is intentional/expected. You cannot stage ranges that span across multiple hunks.
