### ISSUE TITLE
Spacemacs doesn't require helm-config

### ISSUE THREAD

**Issue by jschaf** [syl20bnr/spacemacs#4363]
In the helm [README](https://github.com/emacs-helm/helm/blob/master/README.md), helm says you have to `(require 'helm-config)` in your config.

I didn't see helm-config loaded in any spacemacs files.

Here are two bugs that run into this issue:

1. https://github.com/tmalsburg/helm-bibtex/pull/84
2. https://github.com/emacs-helm/helm-mu/issues/10

To reproduce:

* Add `helm-bibtex` as a package to load.
* restart emacs and get the following error trace:

```
Debugger entered--Lisp error: (wrong-type-argument keymapp nil)
  define-key(nil [menu-bar Tools Helm Tools] ("Tools" keymap "Tools"))
```

**Comment by TheBB** [comment]
I don't quite see the problem. If helm-bibtex needs helm-config to be loaded, it should require it. If helm-bibtex explicitly requires the user to load helm-config instead, then the user should require it. The helm-bibtex package is not (yet) supported by Spacemacs (https://github.com/syl20bnr/spacemacs/pull/4316), and none of the bugs you cited are Spacemacs bugs.

**Comment by TheBB** [comment]
Then again, from what I can see, it doesn't seem *harmful* to load it either.

**Comment by jschaf** [comment]
The problem right now is that responsibility for loading helm-config is unclear.

Here's what https://github.com/emacs-helm/helm docs state: 

> Then you should need only in your init file
> `(require 'helm-config)`
> [...]
> Some people are installing helm with their own config using diverses require, autoload and other hacks, not using helm-config. Expect failures and slowdown at startup unless you really know what you are doing when you do so.

helm-config is user customization so I can see the argument for making Spacemacs load it.  But a package should declare and make sure it's dependencies are loaded.

@thierryvolpiatto just created a separate helm-easymenu.  I think the best solution is for helm-bibtex to require helm-easymenu.

Since this bug is at a weird intersection between helm, helm-bibtex and Spacemacs, I figured I see what thoughts were here.

**Comment by jschaf** [comment]
This was fixed upstream.
