### ISSUE TITLE
dotspacemacs/user-config is not loaded when spacemacs run as client in a emacs server

### ISSUE THREAD

**Issue by cocodrino** [syl20bnr/spacemacs#4365]
Hi, I'm running emacs as daemon using emacs --daemon then I try connect to it using /usr/bin/env emacsclient -c -a..this works ok as expected, but I notice than my config inside dotspacemacs/user-config is not loaded, how can I fix it?  thanks!!!...

**Comment by StreakyCobra** [comment]
I'm also using this config and it works. What's the difference?

**Comment by syl20bnr** [comment]
@cocodrino are you sure ? can you put a debug `(message "foo")` in your `user-config` function to verify ?

**Comment by magnetophon** [comment]
I have a similar problem: when ran as a client, [these lines](https://github.com/magnetophon/.dot/blob/master/common/.spacemacs#L253-L258)  get called, but [this one](https://github.com/magnetophon/.dot/blob/master/common/.spacemacs#L260) doesn't.

When I run emacs standalone, all is good.

**Comment by StreakyCobra** [comment]
@magnetophon `user-config` is called once when emacs start. In daemon mode it means when the emacs daemon is starting. Mapping some keybindings or setting variable there will have effect in the whole session, but changing the background only affect the current frame, so it's changing the background color of the daemon :wink: (yes this doesn't have any effect).

If you want all new frames to have this background, you can either change the theme you are using, or use something like:

```elisp
(setq default-frame-alist '((background-color . "white")))
```

to tell that frames is to have a white background by default.

**Comment by StreakyCobra** [comment]
@cocodrino Can you show us the code that's not working?

**Comment by magnetophon** [comment]
@StreakyCobra Thanks.  Unfortunately that line has no effect in client nor in normal mode...

**Comment by StreakyCobra** [comment]
@magnetophon Have you restarted the daemon? For me it seems to work (not the really first client though, but all subsequent client yes).

**Comment by magnetophon** [comment]
@StreakyCobra ah, yes, after the first client it starts working, thanks.
Any suggestions to get it working on the first one too?

**Comment by StreakyCobra** [comment]
Nope, but it may be related to last @travisbhartwell change maybe?

**Comment by syl20bnr** [comment]
Nope, actually @travisbhartwell's function is a solution to this kind of issue.

I'm wondering if we could introduce a new user function for graphical display related config, this function would be correctly called by the first GUI client. 

Maybe something like `dotspacemacs-user-GUI-config`

cc @TheBb @justbur

**Comment by syl20bnr** [comment]
Actually the fact that it does not work for the first frame is related to this but this due to my addition to reload the theme when the first GUI client connects, for the same reason as this thread. So the first GUI client background colour is overridden by the reloading of the theme.

We can fix this with the proposition above of a new user function.

**Comment by raawaa** [comment]
In the `user-config` function, you may add a hook every time a new frame is created. Like below:
``` elisp
(add-hook 'after-make-frame-functions
           (lambda (frame)
             (select-frame frame)
             (spacemacs//set-monospaced-font "Hack" "文泉驿等宽微米黑" 13 16)))
```

**Comment by hghwng** [comment]
Same problem here. `SPC C c` is undefined when Emacs is running as daemon.

I found that restarting the server (`SPC q R`) makes it work again. I don't know the mechanism, but I guess `--resume-emacs-desktop` is the magic. Is it a possible workaround?
