### ISSUE TITLE
improvement: go layer autocomplete must show function signature

### ISSUE THREAD

**Issue by cocodrino** [syl20bnr/spacemacs#4368]
Hi guys, I think than would be cool than the autocomplete in the go layer would show the signature (expected arguments and result for every function) inside the box or in other windows (similar to how ternjs works) 

in my emacs config this works and show the function signature but I don't know why the spacemacs layer is  different, I suppose than must be a configuration in the layer because scala with ensime works as expected.

thanks!!!...

**Comment by carlosgaldino** [comment]
@cocodrino Could you check if the changes proposed on #4960 work for you?

Thanks.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
