### ISSUE TITLE
Automatic activation of local pyenv version in python layer chokes on extended syntax

### ISSUE THREAD

**Issue by azmd** [syl20bnr/spacemacs#4371]
#### Description
Using the new `python-auto-set-local-pyenv-version` variable in the python layer does not work when the local pyenv version in .python-version is set to use the `<python-version>/envs/<virtualenv-name>` syntax.

#### Reproduction guide
- create virtualenv with `pyenv virtualenv 3.5.1 test`
- create new empty directory and switch to it
- active local virtualenv switch with `pyenv local 3.5.1/envs/test`
- opening file in directory results in `pyenv: version '3' is not installed (set by /home/azmo/tmp/spacemacs-test/.python-version)`

Changing `current-word` to `current-line` in [`pyenv-mode-set-local-version`](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/python/funcs.el#L56) seems to fix this issue for both the short as well as the extended syntax.

**Comment by TheBB** [comment]
I believe this has been fixed. Can you confirm?

**Comment by TheBB** [comment]
Or maybe @fbergroth can confirm, this was your code right?

**Comment by azmd** [comment]
Indeed this has been fixed, thanks.

**Comment by fbergroth** [comment]
Right, this was fixed in #4518 and released in 0.105.7. I hadn't noticed spacemacs defined  the `current-line` function though :)
