### ISSUE TITLE
Spacemacs help errors out

### ISSUE THREAD

**Issue by kot-behemoth** [syl20bnr/spacemacs#4372]
Just upgraded to v.0.105.0.

Tried to have a look at the help for the new typography layer, executed `SPC f e h`, which resulted in a deprecation warning: "Warning (emacs): The 'SPC f e h' (or 'M-m f e h') binding is now deprecated and will be remove in the next release. Please use 'SPC h SPC' (or 'M-m h SPC') instead."

At the same time, it also errored saying `let*: Wrong number of arguments: (3 . 3), 1`.

I also tried the seemingly new `SPC f e f`, but that resulted in the same error.

**Comment by TheBB** [comment]
Please update your packages when you upgrade Spacemacs. This should go away with the newest version of Helm.

**Comment by kot-behemoth** [comment]
Totally forgot about that — still fairly new to spacemacs! Thanks, that fixed it.

Issue closed.

**Comment by StreakyCobra** [comment]
> Issue closed.

Really closing the issue then ;-)
