### ISSUE TITLE
link to HOWTOs.org is broken

### ISSUE THREAD

**Issue by hyOzd** [syl20bnr/spacemacs#4378]
At the end of this page:

http://spacemacs.org/doc/QUICK_START.html#orgheadline12

The link http://spacemacs.org/doc/HOWTOs.html is broken. It gives 404 error.

**Comment by xfq** [comment]
`HOWTOs.org` has been merged into `FAQ.org`.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
