### ISSUE TITLE
Documentation confusion for Vim users (what is a major mode?)

### ISSUE THREAD

**Issue by kqr** [syl20bnr/spacemacs#438]
The documentation starts off by explaining that

> `Spacemacs` comes with a dedicated major mode `spacemacs-mode`.

As a Vim user trying to understand how to use spacemacs, I feel like this sentence warrants an explanation of what it means to have a dedicated major mode. I have a feeling "mode" in "dedicated major mode" does not mean the same thing as the "mode" I am used to talk about as a Vim user, although I might be wrong.

**Comment by tuhdo** [comment]
A major mode is simply a command in Emacs. it defines behaviors of a buffer. It includes syntax highlighting, indentation and a set of commands *specialized* in that mode. For example, in major modes specific to Lisp (i.e. emacs-lisp-mode, scheme-mode, common-lisp-mode), they usually have specific commands for evaluate expressions at cursor by sending to an integrated interpreter for executing and printing result. Major modes are used to specialize a buffer.

A buffer is an object in Emacs for holding text. Just plain text. Major modes classify buffers. That is, once a major mode is activated on a buffer, the text in that buffer is treated according to the rules that a major mode define. For example, you open a Python source file; buffer hold plain text Python, but major mode understands what strings are keywords in Python and highlight them accordingly.

A minor mode defines a set of features that are not necessary peculiar to a category of text. In other words, minor mode defines functionality that can be shared between buffers, and is not specialized to a class of buffer like major mode. You can use the same minor mode in Python major mode or C major mode or Lisp major mode... It's up to you in which major mode to activate a minor mode and depend on minor mode writer as well.

Hope that help.

**Comment by syl20bnr** [comment]
To complete @tuhdo's great answer: `vim mode` == `evil state` so you should not be confused with emacs major and minor modes and evil states.

**Comment by kqr** [comment]
@tuhdo Just to clarify I have understood... does this mean that the "spacemacs-mode" major mode is a mode that makes editing spacemacs configuration files convenient?

**Comment by syl20bnr** [comment]
@kqr I will reply for @tuhdo because I'm not sure that he know what is the `spacemacs-mode`.

Major modes are very general purpose things and they are not only tied to editionm they can be used to only set basic properties of a buffer (read-only etc...).

In this case `spacemacs-mode` is a major mode for the `*spacemacs*` buffer which is read-only, it is only a loading screen.
Spacemacs configuration files are emacs lisp files and the major mode for them is `emacs-lisp-mode`.

There can be only one major mode active per buffer whereas you can activate as much minor mode as you want for a given buffer.

**Comment by syl20bnr** [comment]
@kqr more info here: http://www.gnu.org/software/emacs/manual/html_node/elisp/Major-Modes.html

**Comment by TheBB** [comment]
I think #1565 closes this issue.

**Comment by kqr** [comment]
It totally does. (And thanks for bringing my attention to what looks like an awesome text!)
