### ISSUE TITLE
[org] Switch to insert mode after selecting template in org-capture

### ISSUE THREAD

**Issue by kostajh** [syl20bnr/spacemacs#4380]
If I press `SPC C c`, and select the default `Task` option from the org capture templates, I'm in a buffer with these contents, where `$` is the cursor:

```
*** TODO$ 
  [2016-01-04 Mon]
```

However, I'm not in insert mode, so I always have to press `i SPC` or `shift A` to start typing. Obviously two characters isn't a huge deal but it would be nice to have the cursor (`$`) like so and in insert mode:

```
*** TODO $ 
  [2016-01-04 Mon]
```

**Comment by nixmaniack** [comment]
I use `hybrid` style so this works for me. You'll need `evil-insert-state` in case of vim style.
```
(add-hook 'org-capture-mode-hook 'evil-hybrid-state)
```
For a space after `TODO`, you need to customize the necessary `org-capture-templates`.

**Comment by kostajh** [comment]
` (add-hook 'org-capture-mode-hook 'evil-insert-state)` is perfect, actually. Adds the extra space and everything. Thanks @nixmaniack! So, what if anything would it make sense to add to the `org` layer?

**Comment by TheBB** [comment]
If that adds a space, the space was already there to begin with. If the cursor was off you were probably entering insert state with `i` and not `a`.

**Comment by nixmaniack** [comment]
I assume vimmers like everything to start in normal state hence it's this way. It's personal choice I think. :)
