### ISSUE TITLE
Initial load of @Org custom layout fails

### ISSUE THREAD

**Issue by fintelkai** [syl20bnr/spacemacs#4381]
I just started trying out the new spacemacs-layouts layer. After a fresh start, if I select the @Org custom layout, defined in [spacemacs/layers/org/packages.el](https://github.com/syl20bnr/spacemacs/blob/a9f9c1bd97fb9c678ef0ab42e5ce333a1d4b3cd0/layers/org/packages.el#L380-L384), I get the error: "Symbol's value as variable is void: org-agenda-files".

Of course, once I have loaded some org file (and thus org-agenda-files is defined), I can switch to the custom layout.

I suppose switching to the layout presupposes that org-mode has already been loaded and so org-agenda-files is already defined, but wouldn't it make sense for org-mode to be loaded if it hasn't already been loaded?

**Comment by CestDiego** [comment]
@fintelkai do you have files in your agenda? you can add files with `C-c [` and remove them with `C-c ]`

**Comment by jmiven** [comment]
@fintelkai if I understand correctly and you're setting `org-agenda-files` in an `(with-eval-after-load 'org ...)` (or similar), https://github.com/syl20bnr/spacemacs/pull/5169 should indirectly solve your problem.
