### ISSUE TITLE
Suggestion: ignore keyboard layout

### ISSUE THREAD

**Issue by TheGreenHabi** [syl20bnr/spacemacs#4382]
Hello everyone! 
Thanks for amazing spacemacs!
Is there a way to ignore current keyboard layout and treat every keypress as if it were in US keyboard layout?
Currently I have 4 languages and it's a pain to always switch to US keyboard layout to execute commands while typing in another.

Maybe there is some config variable that I'm missing?

**Comment by StreakyCobra** [comment]
As far as I know, emacs is dealing with keys, not keycodes. So I don't think there is a way to treat keypress as it were in US keyboard. I think it's *eventually* possible to create a translation map for a given keyboard layout, and activate it when entering `normal-state`, but even this will not allow to handle multiple keyboard layout.

**Comment by nixmaniack** [comment]
How about switching to US keyboard layout when in normal state and switch back to previous layout when in insert state? Hooks can help here.

**Comment by TheGreenHabi** [comment]
@nixmaniack That's an amazing idea!

**Comment by TheGreenHabi** [comment]
Here is my solution. Even though it's not what I was looking, it's even better:
https://www.gnu.org/software/emacs/manual/html_node/emacs/Select-Input-Method.html

I can select input method inside Spacemacs with 
```C-x RET C-\ method RET```
Select a new input method for the current buffer (set-input-method).

and for commands Spacemacs still uses US keyboard layout. And for input in __insert mode__ I can even toggle current input method between other language and English with ```C-\```

Found how to display current input method:
https://github.com/TheBB/spaceline/pull/47
