### ISSUE TITLE
Change default value for dotspacemacs-whitespace-cleanup

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#4386]
We should change it to `nil`, it can be surprising for some users.
Source: https://www.reddit.com/r/emacs/comments/3ze6gf/spacemacs_0105_released_new_website_and_layouts/cylowm2

**Comment by StreakyCobra** [comment]
:cry: A soooooo sane default gone

**Comment by xfq** [comment]
It also needs better documentation.  For example, what are the differences between `all` and `trailing`?

Maybe I should report this as another issue.

**Comment by echohack** [comment]
Gonna weigh in on this one. This was a poor change IMO -- hunting down this default and changing it was not a delightful experience. As a new user, this not being enabled was surprising.

VS Code has this enabled by default, for instance.

<img width="593" alt="Screen Shot 2019-03-19 at 22 03 26" src="https://user-images.githubusercontent.com/3253989/54660252-e76ef500-4a92-11e9-98ca-3691a9bc4477.png">

**Comment by Compro-Prasad** [comment]
@echohack For your kind information, not all projects have linters that remove unneeded whitespace but most of them use a version control software. Providing this default will produce large diffs which is not good practise.
