### ISSUE TITLE
Tab to show section in Magit doesn't work in 0.105.0

### ISSUE THREAD

**Issue by zachlatta** [syl20bnr/spacemacs#4387]
Previously I could hit `TAB` in Magit to expand a section, like the diff of a file.

![recorded](https://cloud.githubusercontent.com/assets/992248/12096969/cde4ccfa-b2cd-11e5-8f92-fda156db688f.gif)

In the latest version of Spacemacs, hitting tab no longer works. I assume this is because of the `evil-magit` addition, but I couldn't find anything in the [`evil-magit` keybindings](https://github.com/justbur/evil-magit#key-bindings) about this keybinding being changed.

I'm not sure if this is a bug or if I'm missing something obvious. Thoughts?

**Comment by StreakyCobra** [comment]
It's working here. Have you updated your packages (i.e. `[Update packages]` on `*spacemacs*` buffer) ?

**Comment by mclearc** [comment]
I'm seeing this problem as well, though `shift-TAB` works to fold/unfold everything. All packages are up to date and am on current develop branch.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 0f7a2e1)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion deft emacs-lisp
                 (geolocation :variables geolocation-enable-osx-location-service-support t geolocation-enable-weather-forecast t geolocation-enable-automatic-theme-changer nil)
                 html
                 (git :variables git-gutter-use-fringe t)
                 latex markdown org osx pandoc
                 (ranger :variables ranger-show-preview t)
                 (shell :variables shell-default-term-shell "/usr/local/bin/zsh" shell-default-height 30 shell-default-shell 'multi-term shell-default-position 'bottom)
                 shell-scripts spacemacs-layouts
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 syntax-checking themes-megapack version-control yaml)
```

**Comment by zachlatta** [comment]
Hmm, odd. I've updated my packages and regenerated my `.spacemacs` file and
it still doesn't work.

On Mon, Jan 4, 2016 at 10:40 AM, Fabien Dubosson <notifications@github.com>
wrote:

> It's working here. Have you updated your packages (i.e. [Update packages]
> on *spacemacs* buffer) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/4387#issuecomment-168763127>
> .
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by mclearc** [comment]
Looks like `C-tab` does what `tab` used to...

**Comment by zachlatta** [comment]
Ah, I should probably post that info as well. Here we go:


*System info*

   - OS: Linux
   - Emacs: 24.5.1
   - Spacemacs: 0.105.0
   - Spacemacs branch: master (tag v0.105.0)
   - Distribution: spacemacs
   - Layers:
      - chrome
      - emacs-lisp
      - finance
      - git
      - github
      - html
      - javascript
      - markdown
      - org
      - shell
      - spell-checking
      - syntax-checking
      - yaml


On Mon, Jan 4, 2016 at 11:45 AM, Colin McLear <notifications@github.com>
wrote:

> I'm seeing this problem as well, though shift-TAB works to fold/unfold
> everything. All packages are up to date and am on current develop branch.
> System Info
>
>    - OS: darwin
>    - Emacs: 24.5.1
>    - Spacemacs: 0.105.0
>    - Spacemacs branch: develop (rev. 0f7a2e1
>    <https://github.com/syl20bnr/spacemacs/commit/0f7a2e1166af3a911088426062f045618d6ddf9d>
>    )
>    - Distribution: spacemacs
>    - Layers:
>
> (auto-completion deft emacs-lisp
>                  (geolocation :variables geolocation-enable-osx-location-service-support t geolocation-enable-weather-forecast t geolocation-enable-automatic-theme-changer nil)
>                  html
>                  (git :variables git-gutter-use-fringe t)
>                  latex markdown org osx pandoc
>                  (ranger :variables ranger-show-preview t)
>                  (shell :variables shell-default-term-shell "/usr/local/bin/zsh" shell-default-height 30 shell-default-shell 'multi-term shell-default-position 'bottom)
>                  shell-scripts spacemacs-layouts
>                  (spell-checking :variables spell-checking-enable-by-default nil)
>                  syntax-checking themes-megapack version-control yaml)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/4387#issuecomment-168780551>
> .
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by syl20bnr** [comment]
Can you try adding `evil-magit` to `dotspacemacs-excluded-packages` and restart Emacs ?
Note that this is not a recommended solution, it is just to see if the issue comes from the `evil-magit` package.

**Comment by StreakyCobra** [comment]
@justbur Your last change (`evil-magit-use-y-for-yank`) seems to break `magit`. This bug can be avoided by setting this variable to `nil` in `user-init`. I also have some problems with my bepo layers that are solved by changing this.

**Comment by syl20bnr** [comment]
@StreakyCobra Great, will deploy a minor release tonight with the fixes.

**Comment by StreakyCobra** [comment]
Or maybe @justbur can fix it upstream soon

**Comment by justbur** [comment]
It's not broken for me. Try this `(add-hook 'magit-mode-hook (lambda () (evil-jumper-mode -1)))`

**Comment by justbur** [comment]
evil-jumper binds to TAB and it looks like it's overriding TAB for you in the magit buffers. That's my guess at least. 

The better fix is to move the evil-jumper binding into the global map.

**Comment by StreakyCobra** [comment]
@justbur Your snippet seems to work.

**Comment by justbur** [comment]
It's [this](https://github.com/bling/evil-jumper/blob/master/evil-jumper.el#L239-L241)

We should unbind these and move them down in precedence. I've have this package excluded for a while.

**Comment by justbur** [comment]
In other words, it's not evil-magit's fault. I switched to using normal state in evil-magit so that visual state works properly. That's the reason for the recent change. Evil-jumper goes and binds to TAB with a high precedence globally (not good in my opinion)

**Comment by TheBB** [comment]
Thanks for the workaround. Apparently `(evil-jumper-mode -1)` errors if `evil-jumper-mode` isn't enabled, so you have to do this.

```lisp
  (add-hook 'magit-mode-hook
            (lambda ()
              (when evil-jumper-mode
                (evil-jumper-mode -1))))
```

**Comment by justbur** [comment]
@TheBB I think the evil-jumper bindings should go in `evil-normal-state-map`, which is the logical place to put a global binding

**Comment by CestDiego** [comment]
this also affects me after updating pakages

**Comment by zachlatta** [comment]
The latest release seems to have fixed this for me, thanks @syl20bnr!
