### ISSUE TITLE
Frame transparency no longer works

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#4388]
Typing `SPC T T` results in the error:

```
or: Wrong type argument: number-or-marker-p, (90)
```

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 0f7a2e1)
- Distribution: spacemacs
- Layers:
```elisp
(unscroll auto-completion xkcd emacs-lisp git dash yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors spacemacs-layouts vimscript
          (c-c++ :variables c-c++-enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by StreakyCobra** [comment]
It works on my setup. Have you updated the packages? If yes, can you provide [a backtrace](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)

**Comment by justbur** [comment]
What are your transparency settings in .spacemacs?

**Comment by synic** [comment]
My settings are the default (90 for both active and inactive).

With `debug-on-error` enabled, when I type `SPC T T`, I get the following stacktrace:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p (90))
  =((90) 100)
  (or (null alpha) (= (cdr-safe alpha) 100))
  (if (or (null alpha) (= (cdr-safe alpha) 100)) (cons dotspacemacs-active-transparency dotspacemacs-inactive-transparency) (quote (100 . 100)))
  (set-frame-parameter frame (quote alpha) (if (or (null alpha) (= (cdr-safe alpha) 100)) (cons dotspacemacs-active-transparency dotspacemacs-inactive-transparency) (quote (100 . 100))))
  (let* ((frame (selected-frame)) (alpha (frame-parameter frame (quote alpha)))) (set-frame-parameter frame (quote alpha) (if (or (null alpha) (= (cdr-safe alpha) 100)) (cons dotspacemacs-active-transparency dotspacemacs-inactive-transparency) (quote (100 . 100)))))
  spacemacs/toggle-transparency()
  (if (and (or (and (symbolp (quote nil)) (boundp (quote nil))) (listp (quote nil))) nil) (progn (message "transparent-frame disabled.")) (spacemacs/toggle-transparency) (message "transparent-frame enabled."))
  (if (or (null (quote nil)) (and (or (and (symbolp (quote nil)) (boundp (quote nil))) (listp (quote nil))) nil)) (if (and (or (and (symbolp (quote nil)) (boundp (quote nil))) (listp (quote nil))) nil) (progn (message "transparent-frame disabled.")) (spacemacs/toggle-transparency) (message "transparent-frame enabled.")) (message "This toggle is not supported."))
  spacemacs/toggle-transparent-frame()
  call-interactively(spacemacs/toggle-transparent-frame nil nil)
  command-execute(spacemacs/toggle-transparent-frame)
```

**Comment by justbur** [comment]
@synic What does `M-: (frame-parameter (selected-frame) 'alpha) RET` show?

**Comment by synic** [comment]
@justbur: `(90,90)`.

It appears just the toggling doesn't work.  If I set it to transparent by default in `user-config`, it works, but I cannot turn it off using `SPC T T`.

**Comment by justbur** [comment]
@synic `(90,90)` is not a valid value. Do you mean `(90 . 90)`? How are you setting it in user-config? It appears to be something wrong on your side, but I can't tell why yet

**Comment by synic** [comment]
Sorry, `(90 90)`.  I am setting it like so:

```elisp
  ;; Transparency by default
  (set-frame-parameter (selected-frame) 'alpha
                       (list dotspacemacs-active-transparency
                             dotspacemacs-inactive-transparency))
```

**Comment by justbur** [comment]
That's wrong. The parameter takes a cons cell as a value, not a list. It should be
```elisp
  ;; Transparency by default
  (set-frame-parameter (selected-frame) 'alpha
                       (cons dotspacemacs-active-transparency
                             dotspacemacs-inactive-transparency))
```

**Comment by synic** [comment]
Welp, that was it.  Thank you!

**Comment by justbur** [comment]
In your defense, you probably copied that from the old toggle-transparency code which had the same mistake.

**Comment by synic** [comment]
Yeah, I remember grabbing it from somewhere, I thought it was the documentation.  

I would have just called `spacemacs/toggle-transparency`, but that opens a micro-state.  I wonder if the micro state would be better on another command, since it isn't really a toggle at that point.

**Comment by justbur** [comment]
Try `(spacemacs/toggle-transparent-frame)`

**Comment by synic** [comment]
That also opens the micro-state

**Comment by justbur** [comment]
Ah, you're right. Why don't you open an issue for this? I think there should be a proper toggle.
