### ISSUE TITLE
Smex won't work when evil-escape is excluded.

### ISSUE THREAD

**Issue by dsdshcym** [syl20bnr/spacemacs#439]
I excluded ```evil-escape``` when I first started using spacemacs.

But today, after I installed ```smex```, Emacs didn't respond to ```<SPC> :``` or ```M-x```. And emacs says "Symbol's definition is void: key-chord-define".

After I included ```evil-escape``` again, the ```smex``` worked fine. It seems to be a bug with smex or evil-escape layer.

**Comment by syl20bnr** [comment]
Fixed with 2654319
