### ISSUE TITLE
Modeline separator aesthetics

### ISSUE THREAD

**Issue by danielcnorris** [syl20bnr/spacemacs#4390]
I just installed spacemacs and haven't customized it. The mode line separators in my installation don't agree with what I see on spacemacs.org. My installation has curved lines with colors that don't match the other parts of the modeline. I prefer how it looks on the website -- should that be the default or do I need to set it up?

My installation:
<img width="656" alt="screen shot 2016-01-04 at 3 26 19 pm" src="https://cloud.githubusercontent.com/assets/3018129/12100028/53e1c868-b2fa-11e5-9ce1-8930a4f7ab81.png">

Website:
<img width="477" alt="screen shot 2016-01-04 at 3 35 23 pm" src="https://cloud.githubusercontent.com/assets/3018129/12100030/54d645be-b2fa-11e5-841f-660b5574c13a.png">

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. 0f7a2e1)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp)
```

Thanks for your hard work!

**Comment by nixmaniack** [comment]
Have you checked [this](https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-are-the-powerline-colors-not-correct-on-os-x)? From within spacemacs you can search with `SPC f e f` `powerline`

**Comment by CestDiego** [comment]
you have to modify:   `powerline-default-separator`

I have :
```elisp
  (setq powerline-default-separator 'alternate)
```

**Comment by nixmaniack** [comment]
And here's the complete [list](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#powerline-separators). The screenshot on website uses `'slant`

**Comment by danielcnorris** [comment]
Excellent. Thank you. I looked at the FAQ but not carefully enough!
