### ISSUE TITLE
How to enable org-babel ?

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#4392]
I keep getting this error `Symbol's value as variable is void: org-babel-safe-header-args?`

**Comment by CestDiego** [comment]
I fixed this by doing `SPC : org-reload C-u <return>` and then deleted the `org-plus-contrib` directory under `~/.emacs.d/elpa/`

**Comment by CestDiego** [comment]
@syl20bnr I think this should be in the FAQ as well. @AlejandroCatalina has experienced the same issue  and it got resolved with this, this is probably because old enough users still had the problems from the `org` version that comes bundled with Emacs.

**Comment by syl20bnr** [comment]
There is no way to work around the issue without deleting the `org-plus-contrib` package ?

**Comment by CestDiego** [comment]
I think doing `org-reload` and restarting also makes it work

**Comment by StreakyCobra** [comment]
It doesn't seem that other people had this issue. It was probably a one-time problem with an `org` update so there is no need to document it for now. I'm closing this issue, but feel free to open a new one if it appears again :relaxed:
