### ISSUE TITLE
Error when launching Spacemacs

### ISSUE THREAD

**Issue by tgkokk** [syl20bnr/spacemacs#4394]
I'm getting an error when launching Spacemacs (emacs mac port 24.5.1, spacemacs 0.105.0, OS X 10.11). The error is [this](https://gist.github.com/tgkokk/2680831d8ee53a775e9f). Initial Spacemacs configuration, no changes.

**Comment by StreakyCobra** [comment]
Probably a problem with https. Try running `emacs --insecure`.

**Comment by derekparker** [comment]
Same issue here, running the above suggested command did not solve the issue for me.

**Comment by BohrShaw** [comment]
Same here, tag-v0.104.8 has no such problem.

**Comment by syl20bnr** [comment]
Seems to be an issue with `exec-path-from-shell`. Can you try to add `exec-path-from-shell` to `dotspacemacs-excluded-packages` ? 
This is a not a viable solution but it will narrow the issue to this package if the error disappear.

Also is this a blocking error or Spacemacs is able to load completely ?

**Comment by tgkokk** [comment]
Version 0.105.1 fixes this for me.

**Comment by NotBrianZach** [comment]
had a similar problem running 0.105.2, fixed it, heres what I did
added exec path from shell to excluded packages
re started spacemacs, new permissions with a savehist file
recursively made permissions of my .emacs.d very liberal
re started spacemacs, it worked
removed exec-path-from-shell from excluded packages
restarted spacemacs, downloaded some stuff, it still worked.

**Comment by StreakyCobra** [comment]
@tgkokk If the issue is fixed for you, then it can probably be closed, as it is generally dependent from the configuration of the user.

If anyone has the same kind of issue, please open a new issue and be sure to provide the output of `SPC h d s` and the complete backtrace ([info here](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report))
