### ISSUE TITLE
`SPC f J` should be documented in doc/DOCUMENTATION.org

### ISSUE THREAD

**Issue by xfq** [syl20bnr/spacemacs#4398]
`SPC f J` (`spacemacs/helm-open-junk-file`) is a very useful command.  Although I often use the `*scratch*` buffer (`SPC b s`) for things like testing programming language features, sometimes one buffer isn't enough.

I think this command should be documented in `doc/DOCUMENTATION.org`.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
