### ISSUE TITLE
After upgrade to 105 dired buffer is no longer being switched to

### ISSUE THREAD

**Issue by xelibrion** [syl20bnr/spacemacs#4404]
Prior to the upgrade if I launched emacs using the following command
```
my-dir> emacs .
```
dired buffer in `my-dir` would be activated after emacs launches. After the upgrade it's no longer the case and `Spacemacs` buffer remains active, even though dired buffer is created.

**Comment by TheBB** [comment]
I think this is a duplicate of https://github.com/syl20bnr/spacemacs/issues/4057. Closing this one. I'll transfer the labels.
