### ISSUE TITLE
0.105 sync-configuration-layers error

### ISSUE THREAD

**Issue by yangguang760** [syl20bnr/spacemacs#4406]
emacs-24.5.1
orgmode 8.3.2 (8.3.2-59-g3d4c46-elpaplus @ org-plus-contrib 20160104)
After updating to 0.105.1, sync-configuration-layers no longer work, which says "invalid function: org-with-silent-modifications".

**Comment by syl20bnr** [comment]
I cannot reproduce it, can you share your dotfile for quick examination ?

**Comment by yangguang760** [comment]
After deleting all *.elc files and re-compiling them, emacs works well!
@syl20bnr 
Thx!
