### ISSUE TITLE
0.105-- orgmode major mode map "SPC m" disappeared.

### ISSUE THREAD

**Issue by yangguang760** [syl20bnr/spacemacs#4407]
emacs-24.5.1
orgmode 8.3.2 (8.3.2-59-g3d4c46-elpaplus @ org-plus-contrib 20160104)

After updating to 0.105, the map "SPC m" for major mode in orgmode disappeared.

**Comment by syl20bnr** [comment]
May be related to your previous issue #4406 since it seems to involve org as well.

**Comment by yangguang760** [comment]
After deleting all *.elc files and re-compiling them, emacs works well!
@syl20bnr 
Thx!
