### ISSUE TITLE
spacemacs-theme unavaliable & can't connect melpa.org:443

### ISSUE THREAD

**Issue by HIKALU-Z** [syl20bnr/spacemacs#4408]
![111.png-8.8kB](http://static.zybuluo.com/HIKALU/udz60dep57378gkj5zhqk911/111.png)
![234.png-7.9kB]( http://static.zybuluo.com/HIKALU/kfjr3pn0pd2azf6d3zyoluvg/234.png)

**Comment by StoneJiaJia** [comment]
It happened to when I Updated

**Comment by StreakyCobra** [comment]
Can you try running `emacs --insecure` and see if it helps?

**Comment by HIKALU-Z** [comment]
![2016-01-05 21-11-18 的屏幕截图.png-138.6kB](http://static.zybuluo.com/HIKALU/w0qgb6j502zq2xzbtzetav19/2016-01-05%2021-11-18%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)
![2016-01-05 21-10-45 的屏幕截图.png-94.5kB](http://static.zybuluo.com/HIKALU/6rap1ufrunt3wmrzcved4kmf/2016-01-05%2021-10-45%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png)
---
do you mean I do like this?or what can i do?
this bug happened at WIN7&Linux.

**Comment by StreakyCobra** [comment]
If your are in china it may be related to this: https://github.com/syl20bnr/spacemacs/issues/4375#issuecomment-168729040

**Comment by eefano** [comment]
I'm in Europe. Same problem. It's very serious, spacemacs cannot bootstrap at all.

**Comment by eefano** [comment]
emacs --insecure fixed it thanks

**Comment by HIKALU-Z** [comment]
`emacs --insecure`sometime can fix it but somtime doesn't work. now I use VPN to solve this problem.thanks for your help
