### ISSUE TITLE
`ci'` doesn't work as expected in Ruby major mode

### ISSUE THREAD

**Issue by dhgwilliam** [syl20bnr/spacemacs#441]
```
@dhgwilliam ok this is related to one of the modes enabled with ruby files, I have a direct error when activating enh-ruby-mode:

apply: Wrong number of arguments: (3 . 3), 0Invalid face reference: erm-syn-errline
wait...
@dhgwilliam open an issue, there is an error in ruby layer preventing the whole layer from loading correctly
```

**Comment by syl20bnr** [comment]
@dhgwilliam For the error `Wrong number of arguments: (3 . 3)`

What theme do you use ?
Do you use the layer `colors` ?

**Comment by dhgwilliam** [comment]
I use Zenburn, and no i don't have the colors layer enabled. but maybe i should also point out that the exact error message above was actually from your environment, I just copied it from gitter

**Comment by syl20bnr** [comment]
Ok, it can be misleading, can you post a repro step ?

The fix for the error `Wrong number of arguments: (3 . 3)` is documented in the README for `enh-ruby-mode` but we know for sure that it is not related to this issue.

**Comment by TheBB** [comment]
No response from reporter, closing due to age.
