### ISSUE TITLE
Add C-x C-f behaviour for Vim users

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#4411]
In Vim, when you press `C-x C-f`, it auto-completes paths. We can have the same feature by using `company-files`. Unfortunately, `company` is not allowed to enable globally. Maybe we can make it works:
1. Create a command that stores previous `company-mode` variable, then add a hook to `company-completion-finished-hook` to restore the mode back to how it was.
2. Enable `company` globally, but for non-officially supported buffers, we only allow rudimentary backends that are related to text. If we do this, it would be much easier.

**Comment by syl20bnr** [comment]
I would go for 1, should be easy enough with a macro `with-temp-mode` that we could store in core-funcs.el.
