### ISSUE TITLE
Mode line not shown after layout change (running emacs -nw)

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#4414]
Starting emacs in the shell with `emacs -nw` and switching to a new layout/workspace `SPC l` does leave an empty mode line. I've recently upgraded to v0.105.0

**Comment by TheBB** [comment]
I can't reproduce this.

Please show us the error messages you get (the `*Messages*` buffer).

**Comment by TheBB** [comment]
I'm guessing this is a duplicate of #4413.

**Comment by syl20bnr** [comment]
@sebhahn are you able to reproduce after updating to 0.105.2 ?

**Comment by sebhahn** [comment]
No I haven't experienced this issue again. Thanks for fixing it!

**Comment by TheBB** [comment]
Closing as fixed, now.
