### ISSUE TITLE
How do I configure spacemacs for python 3?

### ISSUE THREAD

**Issue by YjyJeff** [syl20bnr/spacemacs#4415]
Hi,I would like to use  python 3 .But the default python layer is for python 2.7. So how can I configure the spacemacs for python 3? Thanks a lot!

**Comment by TheBB** [comment]
The python layer isn't configured for Python 2.7. It just uses the system python install. If you want to switch between versions, use a virtual env.

**Comment by YjyJeff** [comment]
@TheBB OK! Thanks a lot !

**Comment by TheBB** [comment]
I'll close this then. :-)

Remember to install any syntax checkers or external tools you might need in the virtual env as well, otherwise you get the system installs.
