### ISSUE TITLE
Proposal to swap Spotify and mail -layer keys

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#4416]
Using email feels a lot more fundamental than listening to Spotify, so I think the mail layers should get to use the `SPC am` binding instead of `SPC aM`, or what do you think?

**Comment by StreakyCobra** [comment]
Agreed (see also #4389)

**Comment by d12frosted** [comment]
:+1: totally agree

**Comment by choppsv1** [comment]
:+1: agree

**Comment by numkem** [comment]
:+1: it would make a lot more natural.

**Comment by nwolfe** [comment]
:+1:

**Comment by nixmaniack** [comment]
:+1: Yes please!

**Comment by robbyoconnor** [comment]
:+1:

**Comment by numkem** [comment]
I will commit the change in #4389 as a separate commit.

**Comment by kostajh** [comment]
:+1: here as well.

**Comment by StreakyCobra** [comment]
For people wanting to change this behaviour before the PR #4725 being merged:

```elisp
(defun dear-leader/swap-keys (key1 key2)
  "Swap two leader keys."
  (let ((map1 (lookup-key spacemacs-default-map key1))
        (map2 (lookup-key spacemacs-default-map key2)))
    (spacemacs/set-leader-keys key1 map2 key2 map1)))

;; Swap mail and music keys
(dear-leader/swap-keys "aM" "am")
```

BTW this `dear-leader/swap-keys` can work for almost any leader keys you want to swap.
