### ISSUE TITLE
Blank powerline when switching between frames using other-frame / C-x 5 o.

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#4417]
Powerline blanks out if the frame is not in focus and remains completely blank until I activate a different frame with the mouse cursor.

I'm using Emacs from the standard brew formula: `emacs: stable 24.5 (bottled), HEAD`, `Built from source with: --with-cocoa --with-gnutls --with-imagemagick --with-librsvg --with-mailutils`

**Comment by TheBB** [comment]
Can't reproduce. Please let me know the error you get (in the `*Messages*` buffer).

**Comment by TheBB** [comment]
I'm guessing this is a duplicate of #4413.

**Comment by 3rd3** [comment]
I've updated to 0.105.1 but the bug persists. Sometimes even clicking does not help.

**Comment by 3rd3** [comment]
Didn't read it carefully enough, only 0.105.2 will fix it. This issue can be closed as duplicate of #4413.

**Comment by TheBB** [comment]
If you could actually tell me the error you are getting I could tell you for sure.

**Comment by syl20bnr** [comment]
> only 0.105.2 will fix it

You've got a DeLorean ? Version `0.105.2` has just been published, it was not 2 hours ago. :-)

**Comment by StreakyCobra** [comment]
Closing as duplicate then :-)
