### ISSUE TITLE
C-C++-related modes sometimes changes to strange tab width and indentation behavior when editing C++ source files.

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#4418]
It sometimes happens that the tab width changes to 8 spaces like this:

```
void foo() {
        if (true) {
                return;
        }
}
```

Sometimes and so far unpredictably it switches to a different indentation mode altogether in which the the braces are indented by half the indentation width like this:

```
void foo()
  {
    return;
  }
```

Edit: I had some configurations regarding indentation in my .spacemacs file:

```
(indent-guide-global-mode)
(setq
      c-default-style "bsd"
      c-basic-offset 4)
(setq tab-width 4)
(setq indent-tabs-mode nil)
```

I've removed all of them, except c-basic-offset and see whether it improves the situation. I will just leave this issue here in case someone else has same problems.

**Comment by TheBB** [comment]
`tab-width`, `indent-tabs-mode` and `c-basic-offset` all become buffer-local when you set them, so you should use `setq-default` and not `setq` for those.

For the half indentation problem, use a different C default style.

**Comment by 3rd3** [comment]
That sounds important to know. Thanks!

**Comment by 3rd3** [comment]
I've changed it to set-default, specifically it's this now:

And it still switches to the GNU defaults with 2-spaces tabs.

**Comment by TheBB** [comment]
Where are you setting these variables?

**Comment by 3rd3** [comment]
In `dotspacemacs/user-config`.

**Comment by TheBB** [comment]
I don't know. I can't reproduce this problem. Setting `c-default-style` and `tab-width` works fine for me. BSD style is loaded and the value of `tab-width` doesn't change.

**Comment by 3rd3** [comment]
Perhaps Emacs sessions (desktop-mode) doesn't store and/or restore it correctly? But I think it also happened during a session. I will keep an eye on it.

**Comment by sebhtml** [comment]
I think I reproduced this.

If I add 

```lisp
  (setq-default c-default-style "bsd")
  (setq-default c-basic-offset 4)
  (setq-default tab-width 4)
```

in **dotspacemacs/user-init**, I get the desired Allman style.

If I remove these 3 lines from **dotspacemacs/user-init** and put them in **dotspacemacs/user-config**, the GNU style persists.

My dotspacemacs: (link)[https://github.com/sebhtml/dot-files/blob/master/spacemacs/dotspacemacs]

**Comment by spott** [comment]
I too see this issue, and have the corresponding values in user-config.

I'll move them into user-init, but I feel like that isn't the correct way to solve this.

**Comment by ejmg** [comment]
Experiencing similar problem. I had this previously in emacs 25.1 vanilla but fixed with similar patches above (except I used "Linux" style formatting). Will try migrating to configurations to `user-init` section and see if problem is solved.

**Comment by zaript** [comment]
I am having similar issue. Whether I (setq-default indent-tabs-mode nil) or not, the local indent-tabs-mode gets set to t in any source file I open (emacs-lisp, python, c).

**Comment by Seanmatthews** [comment]
I see this issue all over the spacemacs repo. Has it been solved? I've been through several of the solutions proposed and still cannot get my cpp files to place tabs that are 4 spaces wide. Seems like such a simple thing...

**Comment by derkling** [comment]
Same problem here, I need to use "Linux" style which I try to set with a `c-set-style` in a buffer but nothing change, tabs are still 2 spaces and are always expanded when I add them.
The result is the same independently from any other style I try.

It's a pity that such a great distro fails miserably on such a supposedly simple thing.

**Comment by f380cedric** [comment]
Same issue here, Linux style for c/c++-mode. `tab width` is 2 while `c-basic-offset` is 8.
If you change the `tab width` in `layers/+spacemacs/spacemacs-defaults/config.el`, `tab width` will take this value in c/c++ buffers, as if the style had no effect on this variable. That is not the case for other layers (eg. Python) because the `tab width` is "hardcoded" in the `config.el` of the related layer.
Strangely, the `tab width` and the `c-basic-offset` are not aliased (while recommended in [Indentation Basics](https://www.emacswiki.org/emacs/IndentationBasics)).
I have a workaround that __seems__ to work (but not sure about the possible side effects):
 - add these lines in *user-config* in `~/.spacemacs`
```Lips
	(defvaralias 'c-basic-offset 'tab-width)
	(defvaralias 'cperl-indent-level 'tab-width)
```
 - set (& save) variable `c-old-style-variable-behavior` to `t` (e.g. using customize-variable)
