### ISSUE TITLE
helm-spacemacs is broken

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#4420]
I'm getting:
```
Wrong number of arguments: (3 . &rest), 1
```

Quick inspection shows that `helm-org-get-candidates` here is getting called with a single argument when its signature is: `(helm-org-get-candidates FILENAMES MIN-DEPTH MAX-DEPTH &optional (PARENTS nil))`

https://github.com/syl20bnr/spacemacs/blob/7d0ba07cefb038ae4a358545948efea8cb389535/layers/+distribution/spacemacs-base/local/helm-spacemacs/helm-spacemacs.el#L339

**Comment by StreakyCobra** [comment]
Have you updated your packages recently?

**Comment by luxbock** [comment]
Appears to have been an issue with my outdated Helm from November. After updating it works again, so I'll close this. Sorry for the confusion.
