### ISSUE TITLE
"gt" and "gT" bindings for Spacemacs Layout when eyebrowse is not available

### ISSUE THREAD

**Issue by nugend** [syl20bnr/spacemacs#4425]
Those are the common tab-switching bindings for vim. They work when you use the eyebrowse micro-state. If eyebrowse is disabled (and since Spacemacs Layout _seems_ to completely subsume eyebrowse's features, I'm not sure why you'd use eyebrowse), then gt and gT bindings should be available for Spacemacs layout.

**Comment by joehillen** [comment]
> eyebrowse micro-state

Do you mean "eyebrowse layer"?

What is the desired behaviour? 

When eyebrowse is disabled, `gt` should switch between layouts. When eyebrowse is enabled, `gt` should switch between workspaces. 

That could work.

**Comment by joehillen** [comment]
Another option might be to switch between layouts whenever there is only one workspace in a layout.

That would be convenient sometimes, but it could also be confusing.

**Comment by nugend** [comment]
Eh, sorry, was going off some language on http://spacemacs.org/layers/+window-management/eyebrowse/README.html

I thought the whole thing was a global micro state.

**Comment by nugend** [comment]
Actually, is there anywhere to get a good explanation of the differences between workspaces and layouts? i3wm seems to conflate the terms (which is what I think eyebrowse was based off of? https://i3wm.org/docs/layout-saving.html)

**Comment by joehillen** [comment]
spacemacs' layouts have nothing to do with i3.

Layouts are just [perspectives](https://github.com/nex3/perspective-el)

Workspaces (eyebrowse) are sub-elements of layouts.

**Comment by nugend** [comment]
The documentation for the perspectives mode makes no meaningful distinction between what a perspective and what a workspace is. Workspace never appears in the source code for the perpsectives mode except to use it as a synonym for perspective.

I'm just trying to understand how the two modes differ in terms of behaviors and usage (and this may be important if gt and gT should be remapped).

Like, is there any reason you would *want* eyebrowse installed now if you hadn't had it installed before?

**Comment by joehillen** [comment]
> is there any reason you would want eyebrowse installed now if you hadn't had it installed before?

Yes, layouts are named and workspaces are not and a set of workspaces is bound to their layout. Layouts also have buffers associated with them, which you can see using `SPC l b`.

For example, let's say you create a new layout named `foo`. You can then create workspaces within that layout and switch between them using `SPC l w`. If I create another layout named `bar`, there will only be one workspace again. If you switch back to `foo`, there will be multiple workspaces again.

Does that make sense?

Feel free to update the documentation in a way that makes this more clear.

**Comment by joehillen** [comment]
Here's a diagram:

```
|-- Default
|\
| |-- <1>
|
|-- foo
|\
| |--<1>
| |--<2>
| |--<3>
|
|-- bar
|\
| |-- <1>
```

**Comment by joehillen** [comment]
This gives me an idea for a 3rd option for the `gt` binding. It could switch between workspaces across layouts. This would make the behavior the same when eyebrowse is disabled or enabled.

So, in the example about this would mean `gt` would:

```Default<1> -> foo<1> -> foo<2> -> foo<3> -> bar<1> -> Default<1>```

**Comment by jajpater** [comment]
The gt and gT match the :tabnext and :tabprev ex-commands in vim. I really miss them. They should be standardly implemented. Indeed it would be a good idea to make them cycle workspaces. They could also be mapped to switching buffers though. I don't know what would fit the spacemacs philosophy better. But man do I miss these shortcuts!

**Comment by nugend** [comment]
I remember thinking to myself after @joehillen's last reply that maybe changing the behavior wouldn't actually be good. The fact that vi's tabs are normally named based on whatever window is focused conflicts with the layout/workspace split notion.

I'm still not really sure what tabnext/tabprev should actually do because of the semi-hierarchy. If it was a full hierarchy, I'd say there should be a tabup/tabdown (or something like that) and then tabnext/prev would navigate siblings on a branch.

**Comment by jajpater** [comment]
You're right about that. It would be a confusion of concepts so to speak. It is a pitty that a more vim-tab-like structure isn't available. If only someone would clean up the elscreen/evil-tab package mess. Maybe another way around it would be to implement tabbar mode:   https://www.emacswiki.org/emacs/TabBarMode or something that's similar. It seems people have been trying to do this here: https://github.com/mullr/spacemacs-custom/tree/master/layers/tabbar and here:  https://github.com/evacchi/tabbar-layer

**Comment by vendethiel** [comment]
I'd like to know how to do that as well. Working with layouts and all that jazz has been very much a mystery in spacemacs up to now...
