### ISSUE TITLE
Funny colors and glitches in the spaceline/powerline.

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#4426]
I'm using the latest Emacs version from Homebrew on OS X and there are these kinds of color and position glitches visible on the spaceline:

![](https://i.imgur.com/Mdh3pPK.png)

**Comment by TheBB** [comment]
* Set `ns-use-srgb-colorspace` to `t`
* Increase `powerline-scale` in your dotfile.

**Comment by 3rd3** [comment]
Thanks, that helped! Here are my settings for the Menlo font type:

    dotspacemacs-default-font '("Menlo"
                               :size 13
                               :weight normal
                               :width normal
                               :powerline-scale 1.2)

**Comment by 3rd3** [comment]
Update: The color problems persist even with `(setq ns-use-srgb-colorspace t)` in my .spacemacs file (in `dotspacemacs/user-config`).

**Comment by TheBB** [comment]
Are you using the recommended `emacs-mac-port` brew recipe?

**Comment by syl20bnr** [comment]
@3rd3 `ns-use-srgb-colorspace` should be set to nil, not t ;-) Note that the colors won't be as bright with this setting but your powerline colors will be consistent.

**Comment by 3rd3** [comment]
It works, thanks. This can be closed.

**Comment by StreakyCobra** [comment]
As requested :-)

**Comment by TheBB** [comment]
Ah, sorry. `nil`... `t`... what's the difference really...

**Comment by meydjer** [comment]
Fix without losing brightness: https://github.com/milkypostman/powerline/issues/54#issuecomment-331265490

**Comment by doomsbuster** [comment]
@meydjer the URL you point to fixed the issue, without loosing the fidelity of the colors for entire screen on my retina mac.

![image](https://user-images.githubusercontent.com/4811092/44295787-106da400-a27e-11e8-9225-f11df77f7772.png)
