### ISSUE TITLE
Add a key binding for creating new buffer and gives it alias "enew"

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#4428]
Vim users might be creating new buffers with `:enew` command. So, we can easily have such command by making an alias of our existing command:

```elisp
(defalias 'enew 'spacemacs/new-empty-buffer)
```

We can also give the command `SPC b N`, since the key binding is free.

**Comment by synic** [comment]
:+1:  I still do this, after months of using spacemacs, haha.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
