### ISSUE TITLE
Since 0.105, modeline is blank on focused buffer

### ISSUE THREAD

**Issue by quarterto** [syl20bnr/spacemacs#4429]
![emacs](https://cloud.githubusercontent.com/assets/631757/12121986/52f4c3d4-b3d0-11e5-8866-7f489529c592.gif)

I don't see anything in the changelog about this. Is there some setting for this?

**Comment by TheBB** [comment]
Probably a duplicate of https://github.com/syl20bnr/spacemacs/issues/4413

But please check the messages buffer to ensure that you have the same error.

**Comment by syl20bnr** [comment]
Should be fixed in 0.105.2.

**Comment by quarterto** [comment]
Fixed in 0.105.2, thanks!
