### ISSUE TITLE
[auto-complete] Hangs in windows when typing into a file

### ISSUE THREAD

**Issue by travis2861** [syl20bnr/spacemacs#443]
Sometimes the problem is as bad as about half a second per key stroke and about 3 seconds to open just a 5 line file.

it also starts up slower on windows then on my older macbook 2.6 seconds vs 5 - 7. This however is something I can live with but opening files and typing is a deal breaker.

**Comment by syl20bnr** [comment]
I need more info:

- What is the build of Emacs you are using ?
- What type of files are you editing ?
- If you start Emacs with a blank emacs.d, is it still slow ?

I use spacemacs on Windows sometimes and while Emacs is slower on Windows there is no such latency when typing.

**Comment by travis2861** [comment]
Version: 24.4
files I've opened so far are .spacemacs and .cpp/.h
while it's slow to open both of those, typing is as it should be in .spacemacs
with a blank emacs.d it's speedy as ever

**Comment by rphillips** [comment]
I saw significant lag when I was editing source files with company-mode enabled. Is that layer enabled?

**Comment by syl20bnr** [comment]
Do you use the c-c++ layer ? If yes, does removing it speeds up things ?

**Comment by travis2861** [comment]
company-mode is not enabled.
I'm afraid I'm an emacs noob and not sure what you mean by c-c++ layer.

**Comment by syl20bnr** [comment]
Can you test by removing your `.spacemacs` file ?

**Comment by travis2861** [comment]
I miss understood what rphillips said, it's been a long night. Auto complete is enabled and disabling it makes typing zippy again, quite odd that's it's slowing it down by so much.

**Comment by syl20bnr** [comment]
@travis2861 @rphillips @codyhan94 @kini I changed some AC configuration here e73fce6fbcfbea8d06539fa89f4b69deeed703cb
It may fix the issue with lag with AC enabled, especially on Windows, the delay was aggressively set to 0 ! Apologies for this. Thanks @kini for pointing me in the right direction.
