### ISSUE TITLE
SPC f e R reset spacemacs layouts

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#4433]
Pretty annoying, when re-syncing the dotfile the layouts are reset and must be explicitly reloaded with `SPC l L`

**Comment by d12frosted** [comment]
:+1:

**Comment by StreakyCobra** [comment]
Closing as duplicate of #3875 (I hope I'll not be fired :grin:)

**Comment by syl20bnr** [comment]
@StreakyCobra your knowledge of the issue database is impressive! (so no you are not fired :-D)
