### ISSUE TITLE
Help (SPC-h-SPC) is broken in 0.105.2

### ISSUE THREAD

**Issue by prashantv** [syl20bnr/spacemacs#4434]
When I do SPC - h - SPC, I get `Wrong number of arguments: (3 . 3), 1`

**Comment by numkem** [comment]
Did you update all your packages?

I'm running latest version of spacemacs and packages and it got it to open without issues.

**Comment by syl20bnr** [comment]
Should be fixed once you update your packages.

**Comment by prashantv** [comment]
That fixed it, thanks!
