### ISSUE TITLE
Toggles (specifically spacemacs/toggle-transparency) should be proper toggles

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#4435]
This is in reference to #4388

Anything added via `spacemacs/add-toggle` or things available in `SPC t` and `SPC T` should be proper toggles.  This way, you can toggle them in `user-config` if you want to change the default state.

Specifically, `spacemacs/toggle-transparency` (and the related `spacemacs/toggle-transparent-frame`) both open a micro-state (in addition to toggling the setting).  This means, that, if you want to have a transparent frame by default, you cannot just add `(spacemacs/toggle-transparency)` to your `.spacemacs`, because it will open the micro-state instead of just toggling transparency.

I'm not sure what other toggles do this, if there are any at all.

**Comment by sineer** [comment]
I would also like to know how to permanently toggle transparency in my .spacemacs.d/init.el :-)

Thanks!!

**Comment by synic** [comment]
Ah, for now, I'm using this code in my `user-config` as a workaround:

```elisp
  ;; Transparency by default
  (set-frame-parameter (selected-frame) 'alpha
                       (cons dotspacemacs-active-transparency
                             dotspacemacs-inactive-transparency))
```

**Comment by justbur** [comment]
`(spacemacs/toggle-transparency)` in `user-config` should work for this now

**Comment by TheBB** [comment]
Please open an issue if it does not!

**Comment by TheBB** [comment]
Actually let's say fixed in develop.

**Comment by synic** [comment]
Confirmed, works

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by Ethergeist** [comment]
Tried using this in dotspacemacs/user-config, but to no avail (possibly due to running in daemon mode)
`(spacemacs/enable-transparency)`
The following works for me in dotspacemacs/user-config:
`(add-hook 'after-make-frame-functions 'spacemacs/enable-transparency)`

I'm putting this here only because 'spacemacs enable transparency' returns this as a top result (if it should go into the docs somewhere please let me know, and I'd be willing to help out with that.

**Comment by simpsonw** [comment]
I had the same issue as @Ethergeist  and am also using daemon mode.  Their solution worked for me as well.
