### ISSUE TITLE
Freeze related to go layer

### ISSUE THREAD

**Issue by derekparker** [syl20bnr/spacemacs#4437]
Setup:

emacs - 24.5.1
spacemacs - 0.105.2

When I have the `go` layer enabled, and navigate to a `.go` file, shortly after emacs will freeze and become completely unresponsive. After removing the `go` layer and navigating to the same file, the problem is fixed.

**Comment by StreakyCobra** [comment]
Can you provide some more information, like the problematic file, eventually the reproductions steps, and also the output of `SPC h d s`?

**Comment by derekparker** [comment]
@StreakyCobra 

I'm running Ubuntu Linux.

The file is: https://github.com/derekparker/delve/blob/master/proc/proc.go. Interestingly I opened a different file and the editor did not freeze.

Also, here is the output you asked for:

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.2
- Spacemacs branch: master (rev. 29a7eab)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown spell-checking syntax-checking version-control go)
```

**Comment by derekparker** [comment]
Something else of note, when I opened the file that _didn't_ freeze immediately, when I started typing and the typed a `.` to invoke a method, it froze. So maybe something to do with syntax/autocomplete?

**Comment by derekparker** [comment]
@StreakyCobra I've disable both spell check and autocomplete and the issue still happens.

**Comment by StreakyCobra** [comment]
Thanks. I can't reproduce it because I don't have the go tools installed on my system (probably). Let's try to call some `go`-guys to the rescue.

CC @bogdanteleaga @swaroopch (PS: let me know if you don't want being pinged on issues)

**Comment by derekparker** [comment]
@StreakyCobra one other thing of note, it seems the following is being called:

```
/home/derek/code/go/bin/gocode -f=emacs autocomplete /home/derek/code/go/src/github.com/derekparker/delve/proc/breakpoints.go c1636
```

and when running that myself on the command line, it never returns. Maybe that is blocking emacs and causing it to hang?

**Comment by StreakyCobra** [comment]
Certainly, so it's probably a problem to report upstream

**Comment by derekparker** [comment]
@StreakyCobra actually, this might be due to an unrelated issue, I think I may have fixed it. Will reopen if that's not the case. Sorry for any wasted time!

**Comment by bogdanteleaga** [comment]
Started getting this today after I updated spacemacs, any tips on how you fixed it?

I'm experiencing the same thing with gocode.

**Comment by derekparker** [comment]
@bogdanteleaga I rm'ed everything in $GOPATH/bin and recompiled tooling. For me I think it was a weird permissions problem, I screwed up permissions in my $GOPATH due to having to run a complex test suite, long story. Anyways, could be worth rebuilding some of the binaries.

**Comment by bogdanteleaga** [comment]
Yeah, I did try reinstalling gocode and it seems to have fixed it. What I forgot to do then, was to kill the lingering gocode process.
