### ISSUE TITLE
`TAB` in magit status buffer no longer works

### ISSUE THREAD

**Issue by micahbf** [syl20bnr/spacemacs#4438]
`TAB` to expand/collapse diffs in the magit status buffer no longer works. `TAB` does nothing.

**Comment by StreakyCobra** [comment]
This has been corrected in 0.105.1 (https://github.com/syl20bnr/spacemacs/releases/tag/v0.105.1)

**Comment by StreakyCobra** [comment]
(#4387)

**Comment by TheBB** [comment]
Closing as duplicate of https://github.com/syl20bnr/spacemacs/issues/4387 (and also, it is fixed).
