### ISSUE TITLE
turn on hungry-delete globally?

### ISSUE THREAD

**Issue by Treri** [syl20bnr/spacemacs#4440]
is there any way to turn on hungry-delete mode globally?

I saw spacemacs-base and spacemacs, only `spacemacs|add-toggle hungry-delete` exists

Now I use this way

```lisp
(add-hook 'prog-mode-hook
  (lambda()
    (spacemacs/toggle-hungry-delete-on)))
```

because if I put `(spacemacs/toggle-hungry-delete-on)` in `dotspacemacs/user-config` section, it is just buffer local. So I enable hungry-delete mode on every prog-mode-hook

**Comment by TheBB** [comment]
There's no global minor mode for this, no.

By the way, this is equivalent (and better):

```lisp
(add-hook 'prog-mode-hook 'spacemacs/toggle-hungry-delete-on)
```

**Comment by Treri** [comment]
Thanks very much~ I will use your version :+1:
