### ISSUE TITLE
A link is invaild

### ISSUE THREAD

**Issue by fenxian** [syl20bnr/spacemacs#4441]
The link is invaild. This link can be access in below of Quick start page.

http://spacemacs.org/doc/HOWTOs.html

and the below link in Spacemacs documentation page.

http://spacemacs.org/CONTRIBUTING.html

**Comment by robbyoconnor** [comment]
PRs welcome!

**Comment by fenxian** [comment]
I am a rookie. I am reading all documents. 
I can't understand the "PRs welcome!" ... sorry

**Comment by StreakyCobra** [comment]
>  I can't understand the "PRs welcome!" ... sorry

It means you are welcome to contribute to this project by sending a **P**ull **R**equest to correct these problems (if you want/can of course) :-)

**Comment by fenxian** [comment]
@StreakyCobra Thanks for your help. I will try to do it.

**Comment by StreakyCobra** [comment]
Don't forget to have a look at [`CONTRIBUTING.org`](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org) :-)

**Comment by fenxian** [comment]
Ok, I am learning the spacemacs. It's great!
Thank you~
