### ISSUE TITLE
There is a incorrect key binding in the doc/DOCUMENTATION.org

### ISSUE THREAD

**Issue by Clarence-pan** [syl20bnr/spacemacs#4442]
In line 2524:     | ~SPC s p p~ | run =pt=                                              |
The actual key is ~SPC s t p~.

**Comment by StreakyCobra** [comment]
For the people interested to contribute: you will find info in [`CONTRIBUTING.org`](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#contributing-code) :relaxed:

**Comment by Clarence-pan** [comment]
@StreakyCobra thanks. When I'm free, I will make a PR.

**Comment by d12frosted** [comment]
Already in [master](https://github.com/syl20bnr/spacemacs/commits/master/doc/DOCUMENTATION.org), so closing this.
