### ISSUE TITLE
helm-flx do not support emacs-24,3

### ISSUE THREAD

**Issue by was4444** [syl20bnr/spacemacs#4443]
Fail to install, according to [helm-flx] (http://melpa.org/#/helm-flx), which needs emacs-24.4.
And I find a lot of issues about version compatible problem. Is there a way to check version dependencies?

**Comment by tuhdo** [comment]
You can exclude `helm-flx` with `dotspacemacs-excluded-packages` in your `.spacemacs` file. Just add the package name into the list there, and restart.

**Comment by robbyoconnor** [comment]
Update your emacs, either compile it on your own, or download emacs 24.4+

**Comment by was4444** [comment]
Hi @tuhdo, try to exclude `helm-flx`, but not work for me, it complains about:
 `Variable binding depth exceeds max-specpdl-size` and `List nesting exceeds 'max-lisp-eval-depth'`

@robbyoconnor, do we have to upgrade frequently to keep step with all the packages? That sounds not that good. I will try old spacemacs versions first.

**Comment by tuhdo** [comment]
@was4444 Emacs 24.3 was old. It was released March 11, 2013. The latest stable version is Emacs 24.4, released April 2015. Also, Spacemacs does not officially support Emacs 24.3 yet.

**Comment by StreakyCobra** [comment]
See https://github.com/syl20bnr/spacemacs/issues/3198#issuecomment-169247889

**Comment by was4444** [comment]
@tuhdo, @StreakyCobra, I am using RHEL/SL/CentOS 6.x and 7, and just upgrade to 24.3 on 6.x. It's time to make another thorough upgrade .
P.S.
 > Spacemacs is operational with Emacs 24.3, but Emacs 24.4 and above are highly recommended to enjoy a full experience.

**Comment by StreakyCobra** [comment]
> Spacemacs is operational with Emacs 24.3, but Emacs 24.4 and above are highly recommended to enjoy a full experience.

I know. The decision was taken yesterday to stop the support for 24.3 because we saw there was too  many reported problems with upstream packages not supporting 24.3 any longer :-)

**Comment by robbyoconnor** [comment]
You can build it from source, and you should.

**Comment by was4444** [comment]
upgrade to 24.5.
