### ISSUE TITLE
Unable to install spacemacs 0.105

### ISSUE THREAD

**Issue by rahulmutt** [syl20bnr/spacemacs#4445]
I'm running emacs behind an authenicated proxy. In the older versions of spacemacs, I would add the settings just before all the code in init.el and re-add the settings on each pull. That method fails for spacemacs 0.105 with the following errors when running emacs --debug-init:
<pre>
Debugger entered--Lisp error: (file-error "https://melpa.org/packages/archive-contents" "Not implemented")
  signal(file-error ("https://melpa.org/packages/archive-contents" "Not implemented"))
  url-insert-file-contents("https://melpa.org/packages/archive-contents")
  package--download-one-archive(("melpa" . "https://melpa.org/packages/") "archive-contents")
  #[0 "\301\300\302\"\207" [("melpa" . "https://melpa.org/packages/") package--download-one-archive "archive-contents"] 3 "\n\n(fn)"]()
  funcall(#[0 "\301\300\302\"\207" [("melpa" . "https://melpa.org/packages/") package--download-one-archive "archive-contents"] 3 "\n\n(fn)"])
  package-refresh-contents()
  (let ((package-archives (list archive))) (package-refresh-contents))
  (if (eq (quote error) (let ((-with-timeout-value- (catch (quote timeout) (let* (... ...) (unwind-protect ... ...))))) (if (eq -with-timeout-value- (quote timeout)) (progn (progn (spacemacs-buffer/append (format "\nError while contacting %s repository!" ...)) (quote error))) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents)))
  (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let ((-with-timeout-value- (catch (quote timeout) (let* ... ...)))) (if (eq -with-timeout-value- (quote timeout)) (progn (progn (spacemacs-buffer/append ...) (quote error))) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- package-archives) archive) (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let ((-with-timeout-value- (catch ... ...))) (if (eq -with-timeout-value- (quote timeout)) (progn (progn ... ...)) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  (let ((count (length package-archives)) (i 1)) (let ((--dolist-tail-- package-archives) archive) (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let ((-with-timeout-value- ...)) (if (eq -with-timeout-value- ...) (progn ...) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (package-read-all-archive-contents) (if quiet nil (spacemacs-buffer/append "\n")))
  (if (and configuration-layer--package-archives-refreshed (not force)) nil (setq configuration-layer--package-archives-refreshed t) (let ((count (length package-archives)) (i 1)) (let ((--dolist-tail-- package-archives) archive) (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let (...) (if ... ... -with-timeout-value-))) nil (let ((package-archives ...)) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (package-read-all-archive-contents) (if quiet nil (spacemacs-buffer/append "\n"))))
  configuration-layer/retrieve-package-archives(quiet)
  (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg)))
  (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)
  (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)))
  (let ((warning-minimum-level :error)) (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append ...) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir))))
  spacemacs/load-or-install-package(spacemacs-theme)
  (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (spacemacs/load-or-install-package pkg))) (if (or (eq (quote moe-light) theme) (eq (quote moe-dark) theme)) (progn (load-file (concat pkg-dir "moe-light-theme.el")) (load-file (concat pkg-dir "moe-dark-theme.el")))) (add-to-list (quote custom-theme-load-path) pkg-dir))
  (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (spacemacs/load-or-install-package pkg))) (if (or (eq (quote moe-light) theme) (eq (quote moe-dark) theme)) (progn (load-file (concat pkg-dir "moe-light-theme.el")) (load-file (concat pkg-dir "moe-dark-theme.el")))) (add-to-list (quote custom-theme-load-path) pkg-dir))) (t (let ((pkg (spacemacs//get-theme-package theme))) (spacemacs/load-or-install-package pkg))))
  (if (memq theme (custom-available-themes)) nil (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (spacemacs/load-or-install-package pkg))) (if (or (eq (quote moe-light) theme) (eq (quote moe-dark) theme)) (progn (load-file (concat pkg-dir "moe-light-theme.el")) (load-file (concat pkg-dir "moe-dark-theme.el")))) (add-to-list (quote custom-theme-load-path) pkg-dir))) (t (let ((pkg (spacemacs//get-theme-package theme))) (spacemacs/load-or-install-package pkg)))))
  spacemacs/load-theme(spacemacs-dark)
  (let ((default-theme (car dotspacemacs-themes))) (spacemacs/load-theme default-theme) (setq configuration-layer--protected-packages (append (delq nil (mapcar (quote spacemacs//get-theme-package) dotspacemacs-themes)) configuration-layer--protected-packages)) (setq-default spacemacs--cur-theme default-theme) (setq-default spacemacs--cycle-themes (cdr dotspacemacs-themes)))
  spacemacs/init()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %d or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat user-emacs-directory "core/core-load-paths.el")) (if init-file-debug (progn (require (quote core-debug)))) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/rahulmutt/.emacs.d/init.el" nil t)  ; Reading at buffer position 1512
  load-with-code-conversion("/home/rahulmutt/.emacs.d/init.el" "/home/rahulmutt/.emacs.d/init.el" t t)
  load("/home/rahulmutt/.emacs.d/init" t t)
  #[0 "\205\262
</pre>

What is the proper place to specify my proxy settings?

**Comment by d12frosted** [comment]
Have your tried running emacs using `emacs --insecure`?

**Comment by StreakyCobra** [comment]
Indeed it may be the change to `https`. Try either `emacs --insecure` or set `dotspacemacs-elpa-https` to `nil`.

**Comment by rahulmutt** [comment]
Thanks! That helped. A section in the docs about accommodating proxies would be nice.

**Comment by Bost** [comment]
I just realized setting `dotspacemacs-elpa-https nil` helps and `emacs --insecure` does not help!

**Comment by ndland** [comment]
Using `dotspacemacs-elp-https nil` worked for me as well. Thanks!

**Comment by Sn0rt** [comment]
@ndland 

how to set the value ?

is it like this ?

```
diff --git a/core/core-dotspacemacs.el b/core/core-dotspacemacs.el
index dba0489c..84138f11 100644
--- a/core/core-dotspacemacs.el
+++ b/core/core-dotspacemacs.el
@@ -55,7 +55,7 @@ exists. Otherwise, fallback to ~/.spacemacs"))
 `+distributions'. For now available distributions are `spacemacs-base'
 or `spacemacs'.")
 
-(defvar dotspacemacs-elpa-https t
+(defvar dotspacemacs-elpa-https nil
   "If non nil ELPA repositories are contacted via HTTPS whenever it's
 possible. Set it to nil if you have no way to use HTTPS in your
 environment, otherwise it is strongly recommended to let it set to t.")

```

**Comment by ndland** [comment]
@Sn0rt, I changed that value in  my `.spacemacs` file. I would revert the change you made to `core-dotspacemacs.el`.
