### ISSUE TITLE
Statusline disappears

### ISSUE THREAD

**Issue by ElessarWebb** [syl20bnr/spacemacs#4451]
Since I've updated to master my statusline is empty.
The only debug message is (void-function seq-find), so this may be related to #4138

Current version: 723a7921d7ee

**Comment by edwintorok** [comment]
My statusline becomes empty everytime there is an update to Spacemacs available.
This happened with `v0.105.2` and `v0.105.3`. After updating to `v0.105.3` statusline is back, not sure if its the same problem as yours though...

**Comment by TheBB** [comment]
@edwintorok That should have been fixed in 0.105.2.

You can find out if it's the same problem by checking your messages buffer and reading the error message.

**Comment by syl20bnr** [comment]
> This happened with v0.105.2 and v0.105.3

@edwintorok  It should have been fixed in 0.105.2.
Can you try something for me ? Edit your `init.el` file (SPC f e i) and lower the spacemacs version to 0.105.2 then restart Emacs. Do you see the up arrow or the mode-line still disappear ?

**Comment by ElessarWebb** [comment]
Actually my statusline is back now. I have no idea what changed. I'll close and reopen if it resurfaces.

**Comment by edwintorok** [comment]
@syl20bnr works fine now I see the up arrow.
I double checked my `git reflog` and it looks like I went from `v0.105.1` straight to `v0.105.3`:
on `v0.105`, `v0.105.1` released - statusline disappears
on `v0.105.1`, `v0.105.2` released - statusline disappears
on `v0.105.1`, `v0.105.3` released - statusline disappears
update to `v0.105.3` - all good
