### ISSUE TITLE
spacemacs error since 0.105.2 upgrade

### ISSUE THREAD

**Issue by simonjantsch** [syl20bnr/spacemacs#4455]
Since I upgraded spacemacs I get a strange error when starting emacs. This is 
the output when starting whith emacs --debug-init:

[emacserror.txt](https://github.com/syl20bnr/spacemacs/files/79907/emacserror.txt)

No idea what it is... Any help is appreciated!

**Comment by danielberkompas** [comment]
I'm getting this error on all versions of Spacemacs newer than 0.104.8

**Comment by TheBB** [comment]
Am I reading this error correctly? Can you upload a screenshot maybe?

**Comment by TheBB** [comment]
If you're getting the `require(s)` error, you need to update your packages.

**Comment by simonjantsch** [comment]
Here is a screenshot:
![emacs_error](https://cloud.githubusercontent.com/assets/13819379/12145565/4605e940-b48f-11e5-9dce-2c5ee80ecb2f.png)

**Comment by d12frosted** [comment]
To make things easier - you could wipe out `elpa` folder from `~/.emacs.d/`:

```
$ rm -r ~/.emacs.d/elpa
```

**Comment by danielberkompas** [comment]
How do you update packages?

**Comment by StreakyCobra** [comment]
Pressing `[Update packages]` on the `*spacemacs*` buffer.

**Comment by TheBB** [comment]
Click the update packages button on the home buffer, or, as @d12frosted says, just wipe out you elpa directory and restart.

**Comment by d12frosted** [comment]
@danielberkompas 

there are several ways:

1. Spacemacs updates them automatically
2. You ask Spacemacs to update them by calling `configuration-layer/update-packages`
3. You remove `~/.emacs.d/elpa` and restart emacs - this is ultimate solution that helps to solve some very strange problems

**Comment by d12frosted** [comment]
Haha, so much activity

**Comment by simonjantsch** [comment]
Haha, yeah :D thanks for the fast support, I'm trying it now and closing if it works.

**Comment by simonjantsch** [comment]
Yes, that fixed it, thanks again!

**Comment by d12frosted** [comment]
@danielberkompas did it work for you?

**Comment by danielberkompas** [comment]
@d12frosted Yes, after a couple attempts.
