### ISSUE TITLE
How do I rebind eyebrowse

### ISSUE THREAD

**Issue by hosh** [syl20bnr/spacemacs#4464]
I used to be able to switch to different windows using:

`spc W 2` 

Now I have to use `spc l w 2`

I use Eyebrowse *a lot*, since it functions as a replacement for Vim tabs (only better). `spc W` made sense, `spc l w` does not. How do I change those keybindings back?

**Comment by hosh** [comment]
It's especially aggravating that `spc W` isn't bound to anything else.

**Comment by hosh** [comment]
Ok. I see. The new code adds an extra layer called layouts, and that is why it is bound to `spc l`. I can see how that is useful.

However, wouldn't it make sense to bind `spc W` to the current layout?

**Comment by TheBB** [comment]
As you would any other keybinding.

`(spacemacs/set-leader-keys "W" <function here>)`

The function you are after is `spacemacs/workspaces-micro-state`.

> spc W made sense, spc l w does not.

Workspaces solve a similar problem to layouts so it makes sense to group them together. It's also not more difficult to hit two lowercase keys than one uppercase key. But that's just my two cents, of course.

**Comment by TheBB** [comment]
More information: http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline42

**Comment by hosh** [comment]
There is an extra, discernable lag that happens when you press two keys vs. an upper-case. I also use Emacs within Tmux, and have a lot of window keys set up to `w`, `W` and `^W` making it easier to remember for my setup.

Layouts might solve a similar problem, but it looks like workspaces are grouped within layouts. That is actually useful for me. However, most of my projects uses Rails, where I'm working on different parts of the code. To really make use of layout + workspaces, I would be using grouping different projects per layout, and within the layout, I have the code broken out into different workspaces. I rarely switch between projects, so `spc W` -> `spc l w` makes a lot more sense.

**Comment by hosh** [comment]
@TheBB ok that works well. Thanks for your help on this.

**Comment by TheBB** [comment]
:+1: No problem. Please close the issue if you feel it's ok.

**Comment by StreakyCobra** [comment]
For completeness: https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#change-or-define-an-alias-for-a-leader-key
