### ISSUE TITLE
Bootstrap failure on OS X

### ISSUE THREAD

**Issue by hstm** [syl20bnr/spacemacs#4465]
Hi,

I'm just trying to install Spacemacs on my Mac.

- GNU Emacs 24.5.1 (x86_64-apple-darwin15.2.0, Carbon Version 157 AppKit 1404.34)
- Spacemacs master (Latest commit 723a792)

After cloning the Spacemacs repo and starting Emacs, 78 of 78 packages are being downloaded and installed. After the last package (78 of 78), I'm getting the following error:

Debugger entered--Lisp error: (void-variable closed)
  require(window-numbering nil noerror)
  (not (require (quote window-numbering) nil (quote noerror)))
  (if (not (require (quote window-numbering) nil (quote noerror))) (ignore (message (format "Could not load %s" (quote window-numbering)))) (let ((now (current-time))) (message "%s..." "Configuring package window-numbering") (prog1 (progn (if (condition-case err (run-hook-with-args-until-failure (quote use-package--window-numbering--pre-config-hook)) ((debug error) (ignore ...))) (progn (condition-case err (progn ... ... ... ...) (... ...)) (condition-case err (run-hooks ...) (... ...)))) t) (let ((elapsed (float-time (time-subtract ... now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package window-numbering" elapsed) (message "%s...done" "Configuring package window-numbering"))))))
  (prog1 (if (not (require (quote window-numbering) nil (quote noerror))) (ignore (message (format "Could not load %s" (quote window-numbering)))) (let ((now (current-time))) (message "%s..." "Configuring package window-numbering") (prog1 (progn (if (condition-case err (run-hook-with-args-until-failure ...) (... ...)) (progn (condition-case err ... ...) (condition-case err ... ...))) t) (let ((elapsed (float-time ...))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package window-numbering" elapsed) (message "%s...done" "Configuring package window-numbering")))))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package window-numbering" elapsed) (message "%s...done" "Loading package window-numbering"))))
  (let ((now (current-time))) (message "%s..." "Loading package window-numbering") (prog1 (if (not (require (quote window-numbering) nil (quote noerror))) (ignore (message (format "Could not load %s" (quote window-numbering)))) (let ((now (current-time))) (message "%s..." "Configuring package window-numbering") (prog1 (progn (if (condition-case err ... ...) (progn ... ...)) t) (let ((elapsed ...)) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Configuring package window-numbering" elapsed) (message "%s...done" "Configuring package window-numbering")))))) (let ((elapsed (float-time (time-subtract (current-time) now)))) (if (> elapsed 0.1) (message "%s...done (%.3fs)" "Loading package window-numbering" elapsed) (message "%s...done" "Loading package window-numbering")))))
  spacemacs/init-window-numbering()
  funcall(spacemacs/init-window-numbering)
  (let* ((pkg-name (eieio-oref pkg (quote :name))) (owner (eieio-oref pkg (quote :owner))) (owner-layer (object-assoc owner :name configuration-layer--layers)) (disabled-for-layers (eieio-oref owner-layer (quote :disabled-for)))) (spacemacs-buffer/message (format "Configuring %S..." pkg-name)) (mapc (function (lambda (layer) (if (memq layer disabled-for-layers) (spacemacs-buffer/message (format "  -> ignored pre-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern ...)) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append ...)))))) (eieio-oref pkg (quote :pre-layers))) (spacemacs-buffer/message (format "  -> init (%S)..." owner)) (funcall (intern (format "%S/init-%S" owner pkg-name))) (mapc (function (lambda (layer) (if (memq layer disabled-for-layers) (spacemacs-buffer/message (format "  -> ignored post-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> post-init (%S)..." layer)) (condition-case err (funcall (intern ...)) ((quote error) (configuration-layer//set-error) (spacemacs-buffer/append ...)))))) (eieio-oref pkg (quote :post-layers))))
  configuration-layer//configure-package([object cfgl-package "window-numbering" window-numbering spacemacs nil nil elpa nil nil nil])
  (cond ((eq (quote dotfile) (eieio-oref pkg (quote :owner))) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg)))
  (cond ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg (quote :protected)))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) (t (let ((location (eieio-oref pkg (quote :location)))) (cond ((stringp location) (if (file-directory-p location) (setq load-path (cons ... load-path)) (spacemacs-buffer/warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq (quote local) location) (eq (quote dotfile) (eieio-oref pkg ...))) (setq load-path (cons (file-name-as-directory ...) load-path))) ((eq (quote local) location) (let* ((owner ...) (dir ...)) (setq load-path (cons ... load-path)) (setq load-path (cons ... load-path)))))) (cond ((eq (quote dotfile) (eieio-oref pkg (quote :owner))) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg)))))
  (let ((pkg-name (eieio-oref pkg (quote :name)))) (cond ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg (quote :protected)))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) (t (let ((location (eieio-oref pkg (quote :location)))) (cond ((stringp location) (if (file-directory-p location) (setq load-path ...) (spacemacs-buffer/warning "Location path for package %S does not exists (value: %s)." pkg location))) ((and (eq ... location) (eq ... ...)) (setq load-path (cons ... load-path))) ((eq (quote local) location) (let* (... ...) (setq load-path ...) (setq load-path ...))))) (cond ((eq (quote dotfile) (eieio-oref pkg (quote :owner))) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg))))))
  (while --dolist-tail-- (setq pkg (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg-name (eieio-oref pkg (quote :name)))) (cond ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg (quote :protected)))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) (t (let ((location (eieio-oref pkg ...))) (cond ((stringp location) (if ... ... ...)) ((and ... ...) (setq load-path ...)) ((eq ... location) (let* ... ... ...)))) (cond ((eq (quote dotfile) (eieio-oref pkg ...)) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message (format "%S is configured in the dotfile." pkg-name))) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (let ((--dolist-tail-- packages) pkg) (while --dolist-tail-- (setq pkg (car --dolist-tail--)) (spacemacs-buffer/loading-animation) (let ((pkg-name (eieio-oref pkg (quote :name)))) (cond ((and (eieio-oref pkg (quote :excluded)) (not (eieio-oref pkg ...))) (spacemacs-buffer/message (format "%S ignored since it has been excluded." pkg-name))) ((null (eieio-oref pkg (quote :owner))) (spacemacs-buffer/message (format "%S ignored since it has no owner layer." pkg-name))) (t (let ((location ...)) (cond (... ...) (... ...) (... ...))) (cond ((eq ... ...) (configuration-layer//activate-package pkg-name) (spacemacs-buffer/message ...)) (t (configuration-layer//activate-package pkg-name) (configuration-layer//configure-package pkg)))))) (setq --dolist-tail-- (cdr --dolist-tail--))))
  configuration-layer//configure-packages-2(([object cfgl-package "ace-jump-helm-line" ace-jump-helm-line spacemacs nil nil elpa nil nil nil] [object cfgl-package "ace-link" ace-link spacemacs nil nil elpa nil nil nil] [object cfgl-package "ace-window" ace-window spacemacs nil nil elpa nil nil nil] [object cfgl-package "adaptive-wrap" adaptive-wrap spacemacs nil nil elpa nil nil nil] [object cfgl-package "aggressive-indent" aggressive-indent spacemacs nil nil elpa nil nil nil] [object cfgl-package "auto-compile" auto-compile emacs-lisp nil nil elpa nil nil nil] [object cfgl-package "auto-highlight-symbol" auto-highlight-symbol spacemacs nil nil elpa nil nil nil] [object cfgl-package "avy" avy spacemacs nil nil elpa nil nil nil] [object cfgl-package "bind-key" bind-key spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "bookmark" bookmark spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "buffer-move" buffer-move spacemacs nil nil elpa nil nil nil] [object cfgl-package "centered-cursor" centered-cursor spacemacs nil nil local nil nil nil] [object cfgl-package "clean-aindent-mode" clean-aindent-mode spacemacs nil nil elpa nil nil nil] [object cfgl-package "company" company nil nil (emacs-lisp) elpa nil nil nil] [object cfgl-package "define-word" define-word spacemacs nil nil elpa nil nil nil] [object cfgl-package "desktop" desktop spacemacs nil nil elpa nil nil nil] [object cfgl-package "diminish" diminish spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "doc-view" doc-view spacemacs nil nil elpa nil nil nil] [object cfgl-package "ediff" ediff spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "eldoc" eldoc spacemacs-base nil (emacs-lisp) elpa nil nil nil] [object cfgl-package "electric-indent-mode" electric-indent-mode spacemacs-base nil nil built-in nil nil nil] [object cfgl-package "elisp-slime-nav" elisp-slime-nav emacs-lisp nil nil elpa nil nil nil] [object cfgl-package "emacs-lisp" emacs-lisp emacs-lisp nil nil built-in nil nil nil] [object cfgl-package "eval-sexp-fu" eval-sexp-fu spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil" evil spacemacs-base nil (emacs-lisp) elpa nil nil nil] [object cfgl-package "evil-anzu" evil-anzu spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-args" evil-args spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-escape" evil-escape spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "evil-exchange" evil-exchange spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-iedit-state" evil-iedit-state spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-indent-plus" evil-indent-plus spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-jumper" evil-jumper spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-lisp-state" evil-lisp-state spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-matchit" evil-matchit spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-mc" evil-mc spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-nerd-commenter" evil-nerd-commenter spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-numbers" evil-numbers spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-search-highlight-persist" evil-search-highlight-persist spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-surround" evil-surround spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "evil-terminal-cursor-changer" evil-terminal-cursor-changer spacemacs nil nil elpa nil nil t] [object cfgl-package "evil-tutor" evil-tutor spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-visualstar" evil-visualstar spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "exec-path-from-shell" exec-path-from-shell spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "expand-region" expand-region spacemacs nil nil elpa nil nil nil] [object cfgl-package "eyebrowse" eyebrowse nil nil (spacemacs-layouts) elpa nil nil nil] [object cfgl-package "fancy-battery" fancy-battery spacemacs nil nil elpa nil nil nil] [object cfgl-package "fill-column-indicator" fill-column-indicator spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "flx-ido" flx-ido spacemacs nil nil elpa nil nil nil] [object cfgl-package "flycheck" flycheck nil nil (emacs-lisp) elpa nil nil nil] [object cfgl-package "golden-ratio" golden-ratio spacemacs nil nil elpa nil nil nil] ...))
  configuration-layer//configure-packages(([object cfgl-package "ace-jump-helm-line" ace-jump-helm-line spacemacs nil nil elpa nil nil nil] [object cfgl-package "ace-link" ace-link spacemacs nil nil elpa nil nil nil] [object cfgl-package "ace-window" ace-window spacemacs nil nil elpa nil nil nil] [object cfgl-package "adaptive-wrap" adaptive-wrap spacemacs nil nil elpa nil nil nil] [object cfgl-package "aggressive-indent" aggressive-indent spacemacs nil nil elpa nil nil nil] [object cfgl-package "auto-compile" auto-compile emacs-lisp nil nil elpa nil nil nil] [object cfgl-package "auto-highlight-symbol" auto-highlight-symbol spacemacs nil nil elpa nil nil nil] [object cfgl-package "avy" avy spacemacs nil nil elpa nil nil nil] [object cfgl-package "bind-key" bind-key spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "bind-map" bind-map spacemacs-base nil nil elpa pre nil nil] [object cfgl-package "bookmark" bookmark spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "buffer-move" buffer-move spacemacs nil nil elpa nil nil nil] [object cfgl-package "centered-cursor" centered-cursor spacemacs nil nil local nil nil nil] [object cfgl-package "clean-aindent-mode" clean-aindent-mode spacemacs nil nil elpa nil nil nil] [object cfgl-package "company" company nil nil (emacs-lisp) elpa nil nil nil] [object cfgl-package "define-word" define-word spacemacs nil nil elpa nil nil nil] [object cfgl-package "desktop" desktop spacemacs nil nil elpa nil nil nil] [object cfgl-package "diminish" diminish spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "doc-view" doc-view spacemacs nil nil elpa nil nil nil] [object cfgl-package "ediff" ediff spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "eldoc" eldoc spacemacs-base nil (emacs-lisp) elpa nil nil nil] [object cfgl-package "electric-indent-mode" electric-indent-mode spacemacs-base nil nil built-in nil nil nil] [object cfgl-package "elisp-slime-nav" elisp-slime-nav emacs-lisp nil nil elpa nil nil nil] [object cfgl-package "emacs-lisp" emacs-lisp emacs-lisp nil nil built-in nil nil nil] [object cfgl-package "eval-sexp-fu" eval-sexp-fu spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil" evil spacemacs-base nil (emacs-lisp) elpa nil nil nil] [object cfgl-package "evil-anzu" evil-anzu spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-args" evil-args spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-escape" evil-escape spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "evil-evilified-state" evil-evilified-state spacemacs-base nil nil local pre t nil] [object cfgl-package "evil-exchange" evil-exchange spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-iedit-state" evil-iedit-state spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-indent-plus" evil-indent-plus spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-jumper" evil-jumper spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-lisp-state" evil-lisp-state spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-matchit" evil-matchit spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-mc" evil-mc spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-nerd-commenter" evil-nerd-commenter spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-numbers" evil-numbers spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-search-highlight-persist" evil-search-highlight-persist spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-surround" evil-surround spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "evil-terminal-cursor-changer" evil-terminal-cursor-changer spacemacs nil nil elpa nil nil t] [object cfgl-package "evil-tutor" evil-tutor spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-visualstar" evil-visualstar spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "exec-path-from-shell" exec-path-from-shell spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "expand-region" expand-region spacemacs nil nil elpa nil nil nil] [object cfgl-package "eyebrowse" eyebrowse nil nil (spacemacs-layouts) elpa nil nil nil] [object cfgl-package "fancy-battery" fancy-battery spacemacs nil nil elpa nil nil nil] [object cfgl-package "fill-column-indicator" fill-column-indicator spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "flx-ido" flx-ido spacemacs nil nil elpa nil nil nil] ...))
  configuration-layer//load-packages(([object cfgl-package "ace-jump-helm-line" ace-jump-helm-line spacemacs nil nil elpa nil nil nil] [object cfgl-package "ace-link" ace-link spacemacs nil nil elpa nil nil nil] [object cfgl-package "ace-window" ace-window spacemacs nil nil elpa nil nil nil] [object cfgl-package "adaptive-wrap" adaptive-wrap spacemacs nil nil elpa nil nil nil] [object cfgl-package "aggressive-indent" aggressive-indent spacemacs nil nil elpa nil nil nil] [object cfgl-package "auto-compile" auto-compile emacs-lisp nil nil elpa nil nil nil] [object cfgl-package "auto-highlight-symbol" auto-highlight-symbol spacemacs nil nil elpa nil nil nil] [object cfgl-package "avy" avy spacemacs nil nil elpa nil nil nil] [object cfgl-package "bind-key" bind-key spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "bind-map" bind-map spacemacs-base nil nil elpa pre nil nil] [object cfgl-package "bookmark" bookmark spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "buffer-move" buffer-move spacemacs nil nil elpa nil nil nil] [object cfgl-package "centered-cursor" centered-cursor spacemacs nil nil local nil nil nil] [object cfgl-package "clean-aindent-mode" clean-aindent-mode spacemacs nil nil elpa nil nil nil] [object cfgl-package "company" company nil nil (emacs-lisp) elpa nil nil nil] [object cfgl-package "define-word" define-word spacemacs nil nil elpa nil nil nil] [object cfgl-package "desktop" desktop spacemacs nil nil elpa nil nil nil] [object cfgl-package "diminish" diminish spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "doc-view" doc-view spacemacs nil nil elpa nil nil nil] [object cfgl-package "ediff" ediff spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "eldoc" eldoc spacemacs-base nil (emacs-lisp) elpa nil nil nil] [object cfgl-package "electric-indent-mode" electric-indent-mode spacemacs-base nil nil built-in nil nil nil] [object cfgl-package "elisp-slime-nav" elisp-slime-nav emacs-lisp nil nil elpa nil nil nil] [object cfgl-package "emacs-lisp" emacs-lisp emacs-lisp nil nil built-in nil nil nil] [object cfgl-package "eval-sexp-fu" eval-sexp-fu spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil" evil spacemacs-base nil (emacs-lisp) elpa nil nil nil] [object cfgl-package "evil-anzu" evil-anzu spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-args" evil-args spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-escape" evil-escape spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "evil-evilified-state" evil-evilified-state spacemacs-base nil nil local pre t nil] [object cfgl-package "evil-exchange" evil-exchange spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-iedit-state" evil-iedit-state spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-indent-plus" evil-indent-plus spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-jumper" evil-jumper spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-lisp-state" evil-lisp-state spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-matchit" evil-matchit spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-mc" evil-mc spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-nerd-commenter" evil-nerd-commenter spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-numbers" evil-numbers spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-search-highlight-persist" evil-search-highlight-persist spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-surround" evil-surround spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "evil-terminal-cursor-changer" evil-terminal-cursor-changer spacemacs nil nil elpa nil nil t] [object cfgl-package "evil-tutor" evil-tutor spacemacs nil nil elpa nil nil nil] [object cfgl-package "evil-visualstar" evil-visualstar spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "exec-path-from-shell" exec-path-from-shell spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "expand-region" expand-region spacemacs nil nil elpa nil nil nil] [object cfgl-package "eyebrowse" eyebrowse nil nil (spacemacs-layouts) elpa nil nil nil] [object cfgl-package "fancy-battery" fancy-battery spacemacs nil nil elpa nil nil nil] [object cfgl-package "fill-column-indicator" fill-column-indicator spacemacs-base nil nil elpa nil nil nil] [object cfgl-package "flx-ido" flx-ido spacemacs nil nil elpa nil nil nil] ...))
  configuration-layer/sync()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %d or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat user-emacs-directory "core/core-load-paths.el")) (if init-file-debug (progn (require (quote core-debug)))) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/Users/hstm/.emacs.d/init.el" nil t)  ; Reading at buffer position 1165
  load-with-code-conversion("/Users/hstm/.emacs.d/init.el" "/Users/hstm/.emacs.d/init.el" t t)
  load("/Users/hstm/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()

**Comment by syl20bnr** [comment]
Seems to be a corrupted download, can you wipe out the `windows-numbering` folder in `.emacs.d/elpa`directory and restart Emacs ?

**Comment by hstm** [comment]
I've tried that, but without success. I also wiped out .emacs.d completely and made a fresh install - no change.

**Comment by TheBB** [comment]
There was someone in gitter having the same error message but with a different package.

**Comment by TheBB** [comment]
Have you tried wiping elpa and starting with --insecure?

**Comment by hstm** [comment]
Thanks for the tip! That did the trick. Strange issue though.
Should I close this issue now or should I keep it open for further investigations?

**Comment by TheBB** [comment]
I think you can close it.

Remember to set `dotspacemacs-elpa-https` to `nil` in your dotfile. That is equivalent to starting with `--insecure` and should keep you from experiencing this problem again.

**Comment by hstm** [comment]
Thanks to everyone for your help!
