### ISSUE TITLE
[org] add common global keyboard shortcuts from docs

### ISSUE THREAD

**Issue by mankoell** [syl20bnr/spacemacs#4467]
Please add the widespread used, global keyboard shortcuts accordding to the org mode [manual](http://orgmode.org/org.html#Activation):

```
 (global-set-key "\C-cl" 'org-store-link)
 (global-set-key "\C-ca" 'org-agenda)
 (global-set-key "\C-cc" 'org-capture)
```

I would assume it within the builtin org layer.This would make it alot easier if you come from emacs to spacemacs.

**Comment by nixmaniack** [comment]
:+1: I still have have it from my old emacs configs!

**Comment by manlegn** [comment]
What does the beginner friendly label mean? Do you wanna tell me im newb? :smile_cat:

**Comment by StreakyCobra** [comment]
Nope, it's mean this issue is an easy problem to address for new contributors.

**Comment by manlegn** [comment]
Oh, I better gonna do a pull request then?

**Comment by StreakyCobra** [comment]
If you feel motivated you're welcome! [Necessary reading first](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org) :smiley:

**Comment by AlejandroCatalina** [comment]
@mankoell I just checked and I have those keybindings by default (except `C-c c`), along with the Spacemacs ones. Don't you?

**Comment by mankoell** [comment]
Nope, just tried with `emacs 25.1.50.2` and `spacemacs-0.150.7`. I've to switch to developer branch, right?
