### ISSUE TITLE
Command to add layer

### ISSUE THREAD

**Issue by Andre0991** [syl20bnr/spacemacs#4468]
Currently we have to manually edit our init file to install a layer. This seems simple, but it can be very confusing for a user that just started to use Emacs or that doesn't know anything about Elisp. One advantage in this approach is that they learn about the init file.

I think it would be nice to have a `spacemacs/layer-install` command, though.
Something like `package-install`, in which  you can type and filter the options.

What do you guys think about this?

**Comment by syl20bnr** [comment]
You can already to it thanks to @CestDiego 

`SPC h SPC` select your layer then `C-z` and choose `Add layer` (or you can press `F4`).

@CestDiego We should rename the action "Install layer"

**Comment by CestDiego** [comment]
@syl20bnr I agree. I think also we should specify a convention for listing layers. As well as, once a user is in a README.org from a layer and she does `SPC : install-this-layer` or sth it also installs it. :P I wanted also to make it able to go through the available variables and modify the thing as the user would want, not sure how to approach this though.

**Comment by syl20bnr** [comment]
Feel free to PR, very good idea.

For the layer variables we will need a function or macro to declare them in order to gather lists of them, then we could display a buffer with check boxes widgets and `C-c C-c` to apply and install, but this requires some work. For check boxes inspiration you can check https://github.com/bodil/ohai-emacs/blob/master/ohai/ohai-module-selector.el

**Comment by CestDiego** [comment]
OMG Sounds like a very fun weekend.

**Comment by syl20bnr** [comment]
Actually for the layer variable if we could leverage the customization variables of Emacs it would be great.

**Comment by CestDiego** [comment]
can't we just use defcustom for all defvars? D: and assign them groups for layers or sth

**Comment by CestDiego** [comment]
there was a thing regarding defvar that didn't let us do this though.. I think it interfered with the reload capability.

**Comment by syl20bnr** [comment]
The issue is that Emacs will put them in the customized variable list :-( not so great.

**Comment by CestDiego** [comment]
we should really keep custom variables in a diferent file. Why is it again that we have it on .spacemacs? (also we could `(require "custom.el")` at the bottom of user-config.. dunno

**Comment by syl20bnr** [comment]
Maybe it is simple to add ourselves the good type of widget, we basically need 3 types:
- check boxes
- input text
- combo box

**Comment by CestDiego** [comment]
we could also go full javascript: https://github.com/kiwanami/emacs-widget-mvc

**Comment by CestDiego** [comment]
this looks interesting... I'll check

**Comment by syl20bnr** [comment]
@CestDiego The customize variable location is another topic :-) I don't even remember why I was opposed to a new location, I will have to read the threads about it.

**Comment by CestDiego** [comment]
it was added here: https://github.com/syl20bnr/spacemacs/pull/3470

**Comment by syl20bnr** [comment]
Oh... :-) Thank you for the reminder!

**Comment by TheBB** [comment]
I think this is sufficiently fixed.
