### ISSUE TITLE
Change the cursor globally 

### ISSUE THREAD

**Issue by oles** [syl20bnr/spacemacs#4469]
I'd love to change the cursor globally.

I've tried to change it using (setq cursor-type 'bar) and it almost works. 

For example, in HELM, the cursor changes back to the default square. 
I tried to change bunch of different cursor-related variables, but no dice.

I'm using Spacemacs with X and GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.23)

**Comment by StreakyCobra** [comment]
What you did seems correct. I think you'll have to look in the packages directly to find how to change the cursor if `cursor-type` is not working.

**Comment by hedning** [comment]
Seems like [this is the issue](https://github.com/emacs-helm/helm/issues/1198), which means it's an issue with helm itself, and non-trivial to fix too.

**Comment by StreakyCobra** [comment]
@oles Can you confirm it's the same issue, i.e. you problem is regarding the Helm buffers? If yes this can probably closed as it seems to be a won't fix/can't fix upstream.

**Comment by oles** [comment]
@StreakyCobra Correct, it's just the helm buffers :)
