### ISSUE TITLE
A weird blank space appears before a '}' after being auto-indented

### ISSUE THREAD

**Issue by dsdshcym** [syl20bnr/spacemacs#447]
In c++-mode, after I auto-indented my code, there always be a blank space before a '}'.

Like this:

```cpp
while (condition) {

 } // a space appeared before this brace, it's weird

for (;;) {

 } // a space appeared too
```

According to @syl20bnr , this function seems suspicious: https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L2007

It's not a big problem, but kind of weird.

**Comment by syl20bnr** [comment]
ping @trishume Do you have any idea on this ? Maybe we can hack the current function to reach this additional whitespace and delete it in the `save-excursion` form ?

**Comment by trishume** [comment]
I can't reproduce this, C++ auto-indent works fine for me on 64ffdf6f1132de1991501e8bd78e9cead6070090.

Might have to do with my `.spacemacs` where I have the following lines, maybe you can try these and see if it fixes the problem @dsdshcym:
```
  (setq-default c-default-style "java"
                c-basic-offset 2
                c-toggle-hungry-state 1
                c-toggle-auto-newline -1)
```

**Comment by dsdshcym** [comment]
@trishume Yeah, this setting fixed that. Thanks!

I forgot to mention that I have this line in my ```.spacemacs``` before:

```
(setq-default c-basic-offset 4)
```

(May not be helpful)

**Comment by trishume** [comment]
Interesting, I wonder which of those 4 settings fixes it. Could you check by just having one at a time?
That would help us figure out which one to use to make non-brokenness the default.

**Comment by dsdshcym** [comment]
I think this issue is caused by my mistake now. Because when I start emacs without that four settings, I found the wired space only appeared outside the functions. Like this:

```cpp
#include <iostream>

using namespace std;

for (i = 0; i < N; i++) {
  
 } // This line has a space


int main(int argc, char *argv[])
{
  
  for (i = 0; i < N; i++) {
    
  } // This line don't

  return 0;
}
```

So maybe it's just my fault to cause this issue.

**Comment by dsdshcym** [comment]
And I did some test, found that this setting can fix that:

```
(setq-default c-default-style "java")
```

This is the code after indent:

```
#include <iostream>

using namespace std;

for (i = 0; i < N; i++) {
  
} // No space anymore


int main(int argc, char *argv[])
{
  
    for (i = 0; i < N; i++) {
    
    }

    while (condition) {
        
    }

    return 0;
}
```

**Comment by TheBB** [comment]
So it seems this can be closed now.
