### ISSUE TITLE
tagging workspaces(eyebrowse) is transient

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#4470]
Steps to reproduce:
 1. Create new layout at unused slot, `SPC l 9` with name `test`
 2. Tag workspace with `SPC l w` `r` `foo` `RET`
 3. Switch to other layout `SPC l h`(Default) and switch back to last layout `SPC l <tab>`

Tag `foo` isn't there anymore.

**Comment by TheBB** [comment]
@bmag save us :-)

**Comment by bmag** [comment]
I'm sorry, I'm swamped with school work right now, so I don't have much time to contribute (it's the busiest time of the semester, except for the exams), but here's what you need to do:

All the relevant code is at the bottom of [spacemacs-layouts/funcs.el](https://github.com/syl20bnr/spacemacs/blob/v0.105.4/layers/%2Bwindow-management/spacemacs-layouts/funcs.el#L141):
- in `spacemacs/save-eyebrowse-for-perspective`: this is called after switching to a new workspace, and saves relevant Eyebrowse state as perspective parameters: find out how Eyebrowse stores its tags, and save them as a persp parameter.
- in `spacemacs/load-eyebrowse-for-perspective`: this is called after switching to a new perspective (layout), and loads relevant Eyebrowse state according to current perspective parameters: here you set Eyebrowse tags according to the data you save in the previous function. It should go near the calls to `eyebrowse--set`.
- in `spacemacs/update-eyebrowse-for-perspective`: this is called before switching out of the current perspective (layout) to another perspective. You probably don't need to change this one, but you should verify this assumption.

**Comment by bmag** [comment]
Turns out my code had a bug in it, sorry. #4808 should fix it.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
