### ISSUE TITLE
Keybinding `b` does not work in home (*spacemacs*) buffer 

### ISSUE THREAD

**Issue by kccai** [syl20bnr/spacemacs#4471]
In the home buffer of spacemacs, the quick help in `[?]` shows that `b` jumps to bookmark list if it is enabled. However, pressing `b` only moves backward to the beginning of word even if I enabled the bookmark list in the `.spacemacs` file with 

```dotspacemacs-startup-lists '(recents bookmarks projects)```

I created a pull request ( #2677 ) to change this keybinding to `a`, but in this commit b426098f2e7d3ccd706f536130e0eaa42cda4516 , @syl20bnr changes it to `b` for mnemonic reasons. Now the keybinding `b` seems to be shadowed. But I cannot figure out why ... 

Any help is appreciated!

**Comment by StreakyCobra** [comment]
@syl20bnr [told us he will look at it](https://gitter.im/syl20bnr/spacemacs?at=568a20733c6894026925ea24) :grin: :green_heart: 

@kccai Thanks for the reminder.

**Comment by syl20bnr** [comment]
Oops sorry guys, I will look at it tomo... errr _soon_ :smiling_imp:

**Comment by justbur** [comment]
Fixed in #4476

**Comment by kccai** [comment]
Yes, @justbur 's PR works! You guys are awesome!
