### ISSUE TITLE
reproducible freeze in ediff after pressing n

### ISSUE THREAD

**Issue by magnetophon** [syl20bnr/spacemacs#4474]
#### recipe:

- checkout [this commit](https://github.com/magnetophon/nixosConfig/commit/37b71d08af8d41c4f501276b79713c8be3a9412c#diff-b4bd447d7bd6f0b183ae39e5ac53c6df)
- edit [like this](https://github.com/magnetophon/nixosConfig/blob/970124eae0602f6945071707254be9c97b71386e/common.nix)
- hit ```SPC g e RET```
- hit ```n``` untill no more diffs

#### result:

100% cpu usage.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.4
- Spacemacs branch: nil (rev. da94a25)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion erc emacs-lisp eyebrowse fasd git github markdown nixos org ranger search-engine spell-checking syntax-checking version-control)
```

#### .spacemacs

[here](https://github.com/magnetophon/.dot/blob/master/common/.spacemacs)

**Comment by spacegoing** [comment]
Met the same issue

**Comment by magnetophon** [comment]
Seems fixed on `8825a06`.

**Comment by Kha** [comment]
Can still reproduce in `ad40bae`, using a different file:
* check out `4de7184` of https://github.com/Kha/rustabelle
* open `thys/core/thy.lean`
* `SPC g e @^ RET`
* hitting `n` freezes at region 4

**Comment by fredRos** [comment]
I also observe 100 % CPU usage, reproducibly after hitting `n` a few times in the ediff buffer with three windows. On the same file with `magit-ediff-show-unstaged`, the problem does not occur. Haven't tried on many files, so I don't know if that's a general workaround

**Comment by CeleritasCelery** [comment]
setting `(setq  dotspacemacs-mode-line-unicode-symbols nil)` should fix it.
