### ISSUE TITLE
v0.105.x no longer applies Ruby syntax highlighting to certain expected file types without enh-ruby-mode

### ISSUE THREAD

**Issue by shanesveller** [syl20bnr/spacemacs#4475]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.4
- Spacemacs branch: master (rev. da94a25)
- Distribution: spacemacs
- Layers:

``` elisp
(osx ruby)
```

Under 0.104.x and previously, certain file types that don't end in `.rb` were correctly assigned to `enh-ruby-mode` for syntax highlighting, such as `Gemfile`, `Thorfile`, `Berksfile`, etc.

In 0.105.x, `enh-ruby-mode` is disabled by default, and such files now default to `fundamental-mode` unless `enh-ruby-mode` is re-enabled via the documented variable, i.e.

``` elisp
  (defun dotspacemacs-configuration-layers ()
     '((ruby :variables ruby-enable-enh-ruby-mode t)))
```

This is still the case on `develop` as of da94a257d94734b7cc093498ca6a14ce3a5e5169.

Probably relevant layer source lines:
https://github.com/syl20bnr/spacemacs/blob/da94a257d94734b7cc093498ca6a14ce3a5e5169/layers/%2Blang/ruby/packages.el#L78-L79

https://github.com/syl20bnr/spacemacs/blob/da94a257d94734b7cc093498ca6a14ce3a5e5169/layers/%2Blang/ruby/packages.el#L191-L192

My fledgling understanding of elisp/`use-package` make this seem to work, but I couldn't quickly find the right syntax to make it conditional on `ruby-enable-enh-ruby-mode`.

``` elisp
(defun ruby/init-ruby-mode ()
  (use-package ruby-mode
    :mode (("\\(Rake\\|Thor\\|Guard\\|Gem\\|Cap\\|Vagrant\\|Berks\\|Pod\\|Puppet\\)file\\'" . ruby-mode)
            ("\\.\\(rb\\|rabl\\|ru\\|builder\\|rake\\|thor\\|gemspec\\|jbuilder\\)\\'" . ruby-mode))
```

**Comment by nwolfe** [comment]
Related: PR for doing this specifically for Puppetfiles https://github.com/syl20bnr/spacemacs/pull/4216

**Comment by syl20bnr** [comment]
> My fledgling understanding of elisp/use-package make this seem to work, but I couldn't quickly find the right syntax to make it conditional on ruby-enable-enh-ruby-mode.

@shanesveller why do you want to make it conditional on this variable ? Seems that you don't need to.

**Comment by shanesveller** [comment]
@syl20bnr the thought process was that I wanted to make sure that the behavior stayed consistent whether the `ruby-enable-enh-ruby-mode` variable was set or not, so that those *files would get set to `enh-ruby-mode` or `ruby-mode` as appropriate. I'm not at all familiar with how layers initialize, or in what order, so I wasn't sure if having the `:mode [...]` line on `init-ruby-mode` would or would not be overridden by `init-enh-ruby-mode`.
