### ISSUE TITLE
version-control doesn't work for CVS (or any other backends besides git?)

### ISSUE THREAD

**Issue by valrus** [syl20bnr/spacemacs#4477]
I know, I know, CVS is old and terrible, but I'm at work and I have no choice.

The `version-control` layer [claims](https://github.com/syl20bnr/spacemacs/tree/a9f9c1bd97fb9c678ef0ab42e5ce333a1d4b3cd0/layers/%2Bsource-control/version-control) it "should work with all VC backends," but to all appearances it's actually Git-centric. E.g.:
- trying to do `SPC g . C` in a CVS-controlled buffer gives `Wrong type argument: stringp, nil`
- `SPC g . l` gives `Not inside a Git repository`
- the implementation of the layer looks like most of the bindings go to magit commands

I don't really expect any layers to actually support CVS in this day and age—I can make my own private layer for that—so maybe this can just be regarded as a documentation bug, but I think `version-control`'s documentation is misleading if not outright wrong.

**Comment by TheBB** [comment]
The magit commands don't work outside of a git repository. The others should work in all repositories that your chosen [margin program](https://github.com/syl20bnr/spacemacs/tree/a9f9c1bd97fb9c678ef0ab42e5ce333a1d4b3cd0/layers/+source-control/version-control#differences-between-margin-programs) supports, so make sure you have chosen one with extended VCS support (that is, something other than the default value of `git-gutter+`).

To see which commands are from magit and which are from elsewhere, check the documentation of the microstate (use `?`)

@ralesi This distinction should probably be made more clear. I also note that the VCS microstate will provide magit bindings even if the magit package is not installed, which is probably something we need to change.

**Comment by TheBB** [comment]
`git-gutter` supports git, mercurial, subversion and bazaar. `diff-hl` claims to be tested with all of these and that it "may" also support other backends.

In other words, you are probably out of luck for CVS support.

**Comment by ralesi** [comment]
Any currently supported method of conditionally adding bindings to a microstate? 


Rich






On Thu, Jan 7, 2016 at 2:41 PM -0800, "Eivind Fonn" <notifications@github.com> wrote:












git-gutter supports git, mercurial, subversion and bazaar. diff-hl claims to be tested with all of these and that it "may" also support other backends.



In other words, you are probably out of luck for CVS support.

**Comment by TheBB** [comment]
No there isn't. :-( Can of course hack it in a different way.

@syl20bnr This would be really handy.

**Comment by yifange** [comment]
It would be nice to have some Perforce support too. I saw the perforce package and was hoping for it.
