### ISSUE TITLE
Disable tab-completion on empty string

### ISSUE THREAD

**Issue by ajrouvoet** [syl20bnr/spacemacs#4478]
Manual indenting in web-mode is terrible because on pressing 'tab' the editor will look for completions. In my opinion this should not be the default behaviour. If it should be, is there a documented workaround?

**Comment by amardeep** [comment]
This really bugs me a lot too. I have to manually turn off emmet-mode to get back indentation on tab.

**Comment by ElessarWebb** [comment]
The same actually applies to python mode. I'm not familiar enough with the completion architecture in emacs. Anyone?

**Comment by bmag** [comment]
Don't know if I can help, but I'll try. @ElessarWebb @amardeep can you provide some more info? Right now it's not clear to me what you are experiencing. Can you please:
- provide your system information (`SPC h d s`) and any personal configuration you may have that is related to auto completion or to the modes in which you face this error
- provide a simple recipe to reproduce the bug. Describe the observed behaviour and the desired behaviour. Especially I'd like to understand what do you mean by "the editor will look for completions" (emacs has several completion interfaces).
- check what is tab bound to - `C-h k <tab>` (if you use vim/hybrid editing style, make sure you're in insert/hybrid state when checking this)

I will try to reproduce the bug on my machine and see what's up.

**Comment by ElessarWebb** [comment]
Sure

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults exec-path-from-shell emacs-lisp git syntax-checking version-control markdown agda python django guess-style scala javascript haskell html latex react shell)
```

## Recipe

Edit a javascript file in js2-mode (Javascript-IDE), like this one:

```
function test() {
    X
}
```

Put your cursor where the X is (remove X) and press tab (assuming indent is set to 4).
Even though there is nothing to complete here, a helm autocomplete buffer is opened instead of inserting an indent.
This is annoying because there are quite a few cases where the indent that the js2-mode thinks is correct is not actually correct and when manually trying to correct, I get this buffer instead.

<tab> is bound to indent-for-tab-command from `indent.el`.

**Comment by bmag** [comment]
Thanks, I managed to reproduce the bug. The reason for this is that the variable `tab-always-indent`, which tells Emacs what to do when TAB is pressed, is set to `complete`. This means that Emacs will first indent the current line, and if the line is already indented then Emacs will perform a completion (by calling `completion-at-point`). A workaround is to set `tab-always-indent` to `t` or `nil` - see its documentation for details (`SPC h d v tab-always-indent`).

The default value for `tab-always-indent` is `t`, but Spacemacs sets it to `complete` in the [init block for `auto-complete` package](https://github.com/syl20bnr/spacemacs/blob/v0.105.9/layers/auto-completion/packages.el#L54). This code runs even if the user uses `company-mode` (the default) and not `auto-complete-mode`. This is potentially a bug, and I'm not sure if this setting is really related to `auto-company-mode` or just happens to be there for lack of a better place. We'll need someone familiar with the reasoning behind this setting to determine if it's indeed a bug or not.

**Comment by ElessarWebb** [comment]
Thanks!

Setting it to `t` seems to be slightly better, because it doesn't load auto-complete on empty lines. But for the given example it still does not insert indentation when it's 'already indented'. In fact it still completes when I type `func<tab>`. The latter is the behaviour I'd expect, but seems to contradict the documentation. The former is still annoying.

**Comment by jaysoifer** [comment]
Not sure it is related but it seems relevant to mention that there it also affect the React Layer and there's a [workaround mentioned here](https://github.com/syl20bnr/spacemacs/issues/8222) on #8222. According to @zanemayo:

What did work was adjusting company-minimum-prefix-length in the source code of the html layer.

Go to `.emacs.d/layers/+lang/html/funcs.el` and change
    (set (make-local-variable 'company-minimum-prefix-length) 0))
to
    (set (make-local-variable 'company-minimum-prefix-length) 2))

Then restart emacs.

•••••

This also worked for me.

**Comment by osv** [comment]
@ElessarWebb , I remove TAB because dont like behaivour. I use C-RET emmet-expand-line when need emeet expanding:

```diff
diff --git INDEX:/layers/+lang/html/packages.el WORKDIR:/layers/+lang/html/packages.el
index e5b7c73..37192a2 100644
--- INDEX:/layers/+lang/html/packages.el
+++ WORKDIR:/layers/+lang/html/packages.el
@@ -95,12 +95,12 @@
                                                 web-mode-hook))
     :config
     (progn
-      (evil-define-key 'insert emmet-mode-keymap (kbd "TAB") 'spacemacs/emmet-expand)
-      (evil-define-key 'insert emmet-mode-keymap (kbd "<tab>") 'spacemacs/emmet-expand)
-      (evil-define-key 'emacs emmet-mode-keymap (kbd "TAB") 'spacemacs/emmet-expand)
-      (evil-define-key 'emacs emmet-mode-keymap (kbd "<tab>") 'spacemacs/emmet-expand)
-      (evil-define-key 'hybrid emmet-mode-keymap (kbd "TAB") 'spacemacs/emmet-expand)
-      (evil-define-key 'hybrid emmet-mode-keymap (kbd "<tab>") 'spacemacs/emmet-expand)
+      ;; (evil-define-key 'insert emmet-mode-keymap (kbd "TAB") 'spacemacs/emmet-expand)
+      ;; (evil-define-key 'insert emmet-mode-keymap (kbd "<tab>") 'spacemacs/emmet-expand)
+      ;; (evil-define-key 'emacs emmet-mode-keymap (kbd "TAB") 'spacemacs/emmet-expand)
+      ;; (evil-define-key 'emacs emmet-mode-keymap (kbd "<tab>") 'spacemacs/emmet-expand)
+      ;; (evil-define-key 'hybrid emmet-mode-keymap (kbd "TAB") 'spacemacs/emmet-expand)
+      ;; (evil-define-key 'hybrid emmet-mode-keymap (kbd "<tab>") 'spacemacs/emmet-expand)
       (spacemacs|hide-lighter emmet-mode))))
 
 (defun html/post-init-evil-matchit ()
```
