### ISSUE TITLE
semantics layer - pops up autocomplete window that can't be closed

### ISSUE THREAD

**Issue by moesasji** [syl20bnr/spacemacs#4484]
With just the layers enabled that are present in the standard .spacemacs file enabled autocomplete works as expected. In insert mode it brings up a selection window that can be closed by escape for any position on the string, including on the first character. This changes when I add the semantic layer.

In that case hitting tab on the first character of a string opens a completion-window what can't be closed with escape. Strangely enough this only happens for strings that do not contain a dash. 
#### To reproduce.

1) Open a default .spacemacs file and enable all layers given by default. 
2) Try with tab in insert mode on the first character of org; that works as expected
3) add the semantics layer and restart emacs
4) Try with tab in insert mode on the first character of org; for me a window pops up that I can't close with escape. I need to select one of the given options with the mouse to close the window.
*) it works fine it the string has a dash in it....
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.4
- Spacemacs branch: master (rev. da94a25)
- Distribution: spacemacs
- Layers:

``` elisp
(auto-completion emacs-lisp eyebrowse git markdown mu4e org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 semantic spell-checking syntax-checking version-control)
```

**Comment by StreakyCobra** [comment]
> it works fine it the string has a dash in it....

:joy: Debugging should be classified as an art.

**Comment by moesasji** [comment]
I would have a completely different word for debugging this type of weird issues with code that shouldn't interact with tabs and autocompletion. 

Looking at the code in the semantics layer it is hard to see what actually interacts with Tab-completion. The only thing that looks suspicious to me with my limited lisp skills is the hack starting on line 118 of semantics-stickyfunc: https://github.com/tuhdo/semantic-stickyfunc-enhance/blob/master/stickyfunc-enhance.el

**Comment by StreakyCobra** [comment]
Not sure it's a bug actually.

```elisp
	(add-hook 'completion-at-point-functions
		  'semantic-completion-at-point-function)
```

it's a line in `semantic.el` from emacs itself

and doing:

```elisp
	(remove-hook 'completion-at-point-functions
		  'semantic-completion-at-point-function)
```

Remove the behaviour.

**Comment by StreakyCobra** [comment]
@tuhdo Maybe you have more knowledge about all this?
