### ISSUE TITLE
Ugly/Incorrect minor mode icon fonts

### ISSUE THREAD

**Issue by psamim** [syl20bnr/spacemacs#4489]
Hi

I am using Spacemacs on Archlinux. The icons for minor modes are ugly and I cannot find the reason. I have Source Code Pro font installed.

Thanks,

![2016-01-08-11 44 45](https://cloud.githubusercontent.com/assets/1868679/12193415/622023f6-b5fd-11e5-9a0a-acef63dc576a.png)

**Comment by TheBB** [comment]
Install a good unicode fallback font for these symbols, or disable them by setting `dotspacemacs-mode-line-unicode-symbols` to `nil`. You can paste e.g. ⓗ in a buffer and do `SPC hdc` on it to see which fallback Emacs is currently using.

**Comment by TheBB** [comment]
More information: https://github.com/syl20bnr/spacemacs/issues/1012

I will close this as a duplicate. If you have more questions you can address them in that issue. Thanks!

**Comment by danielbarter** [comment]
A nice fallback unicode font for spacemacs is symbola. `pacman -S ttf-symbola` does the trick.
