### ISSUE TITLE
Local bindings overridden by evil-escape-key

### ISSUE THREAD

**Issue by chrisbarrett** [syl20bnr/spacemacs#449]
In emacs state, `f` now appears to be universally bound to `evil-escape-emacs-state`. This overrides whatever the key is meant to be bound to.

As a concrete example, in Magit, `f` is meant to fetch, but it is now overridden.

**Comment by chrisbarrett** [comment]
Not sure if this is a spacemacs or evil regression :(

**Comment by syl20bnr** [comment]
This is a regression since 0.48.0

**Comment by syl20bnr** [comment]
Rollbacking to a previous version won't work because the regression is in `evil-escape`

**Comment by chrisbarrett** [comment]
In the meantime, what's the best way to disable evil-escape? Toggling the mode doesn't work.

**Comment by chrisbarrett** [comment]
FYI I edited the source so that `evil-escape-mode` is a no-op.

**Comment by syl20bnr** [comment]
It was a non-trivial one, I had to find a way to pass through the `f` key temporarily, I hope we have a working `key-chord` free evil-escape.
