### ISSUE TITLE
mu4e - autoevilification makes it difficult to work with; needs better keybindings

### ISSUE THREAD

**Issue by moesasji** [syl20bnr/spacemacs#4490]
The auto-evilification of mu4e makes the layer rather difficult to work with as some of the more important bindings get very inconvenient compared to the ones in the mu4e manual (http://www.djcbsoftware.nl/code/mu/mu4e/Keybindings.htm)
# Problems:

1) Moving to previous/next message from the search results is pretty important to process email quickly. Without evilification this is bound to `n`,`p`. Both easily accessible; after evilification this become `C-n` and `p`. Note the lack of symmetry and moreover it makes one of the most used commands a difficult emacs-like key combo, i.e. `C-n` instead of `n`. Way too painful.

2) Automatic remapping of keys in the mu4e layer fails for some of the keys as the mu4e layer emits the following warning message in the message buffer:

```
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `mu4e-headers-mode-map':
   - `mu4e-headers-query-prev' originally mapped on `\'
```

Moving back to the previous search result is used often, so painful that it gets lost. So probably worth mapping this to something more sensible than the `M-left` it now defaults to.  

btw) The key-bindings changed are rather extensive compared to the mu4e manual. It would be good to get the full list of the actual keybindings in the documentation. 
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.4
- Spacemacs branch: master (rev. da94a25)
- Distribution: spacemacs
- Layers:

``` elisp
(auto-completion emacs-lisp eyebrowse git markdown mu4e org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 semantic spell-checking syntax-checking version-control)
```

**Comment by TheBB** [comment]
1. We should have `C-j` and `C-k` for these then? Or something similar.
2. Same here, we should find another keybinding for it.

**Comment by TheBB** [comment]
I don't use mu4e so I invite anyone familiar with it to PR.

**Comment by StreakyCobra** [comment]
The best would be to have an independent `evil-mu4e` package that handle this well (à la `evil-magit`). We *just* need to find someone interested by this :sweat_smile:

**Comment by moesasji** [comment]
@TheBB Hitting `n` to see the next email is probably one of the most used commands in mu4e, so it needs to be easy to hit and preferentially a single key close to the home-row. `C-j` and `C-k` would be fine for me, but that is with caps-lock remapped. 

@StreakyCobra I'm new to both emacs and mu4e, so don't count on me. Sorry!

**Comment by StreakyCobra** [comment]
@moesasji No worries, I was just thinking out loud :-)

**Comment by pmagwene** [comment]
I ran into the same problem. I "solved" it by adding the following to my dotspacemacs/user-config. I don't know if this is idiomatic spacemacs style but it seems to work and keep me from tearing out my hair...

```lisp
(evilified-state-evilify-map mu4e-headers-mode-map
  :mode mu4e-headers-mode
  :bindings
  (kbd "n") 'mu4e-headers-next)

(evilified-state-evilify-map mu4e-view-mode-map
  :mode mu4e-view-mode
  :bindings
  (kbd "n") 'mu4e-view-headers-next)
```

**Comment by JorisE** [comment]
@StreakyCobra Your comment got me inspired :). I've made a evil-mu4e extension that I think makes sense at https://github.com/JorisE/evil-mu4e/blob/master/evil-mu4e.el.

My experience with Emacs Lisp is limited, so comments from someone in the Spacemacs communitiy would be much appreciated, before I integrate this in the mu4e layer. Comments about the chosen keys are also welcome @moesasji ... :)

**Comment by StreakyCobra** [comment]
@darkfeline @nixmaniack @AlejandroCatalina :point_up:

@JorisE I'm not using `mu4e`, but let's call some regular contributors to check this :-)

**Comment by jtmoulia** [comment]
See related PR for nav changes (C-j, C-k bindings) #3922

**Comment by AlejandroCatalina** [comment]
I'm taking a look at evil-mu4e @JorisE . It actually makes sense but I don't get some keybindings (`I` seems to be next in mu4e-view-mode, for instance). I think it is not consistent with the rest of the keybindings in the other modes.

I am mainly on this section 
```elisp
(,evil-mu4e-state mu4e-view-mode-map "J"      mu4e~headers-jump-to-maildir)
    (,evil-mu4e-state mu4e-view-mode-map "l"      mu4e-view-headers-next)
    (,evil-mu4e-state mu4e-view-mode-map "h"      mu4e-view-headers-prev)
    (,evil-mu4e-state mu4e-view-mode-map "?"      mu4e-display-manual)
    (,evil-mu4e-state mu4e-view-mode-map "u"      mu4e-view-mark-for-unread)
    (,evil-mu4e-state mu4e-view-mode-map "r"      mu4e-view-mark-for-read)
    (,evil-mu4e-state mu4e-view-mode-map "x"      mu4e-view-mark-for-trash)
    (,evil-mu4e-state mu4e-view-mode-map "e"      mu4e-mark-execute-all)
```

The other modes seem nice to me. I'd change here the so-well-known `C-j` for next and `C-k` for previous. I'd go for `n` and `p`, but `n` is bound to `evil-search-next`, and it is consistent with other packages, so i'd leave it that way. 

The PR #3922 is nice but it isn't passing travis build, so it'd need to be updated.

Is that make sense?

**Comment by nixmaniack** [comment]
@JorisE Cool! I'll definitely give it a try soon. But here's some initial feedback on keybindings.
Keeping consistency in across such packages, it would make sense to add `gr` to update instead of `u`
Also, `gm` to `goto maildir` instead of `J` (I happen to use `J` for joining lines, not sure if current keybinding will conflict). If you look at evil-magit, it uses `g` for jump mnemonic.

**Comment by StreakyCobra** [comment]
@AlejandroCatalina The output of travis suggests that this was a problem on travis side, not in the PR.

**Comment by AlejandroCatalina** [comment]
Thanks for the clarification @StreakyCobra , and sorry for the misunderstanding!

**Comment by JorisE** [comment]
Thanks all!
Specifically @AlejandroCatalina: I changed next and prev for C-j and C-k at your suggestion. I think you misread `l` for `I`, or am I missing something?

and @nixmaniack: I like your suggestions, but all these modes are in evil-motion-state with no text that can be editied, so I don't think that can conflict with your `J`. I like `J` and `u` because of the known mnemonics for mu4e users, but added `gm` and `gr` as secondary keybindings.

**Comment by moesasji** [comment]
Looking through the mu4e-evil keybindings not all make sense to me as a regular user of mu4e

1) narrow-search has a different role than jumping to a next or previous result in a search through the text in a message which can be open at the same time. In my opinion `n` and `p `should keep their expected role, so for me `n` isn't appropriate for the narrow search as that is bound to confuse. The `/` it got bound to actually makes sense to me due to the symmetry with the search function in vim.  

2) The `h` in the message-view should be the normal cursor movement to the left. So why does it get rebound to move to the next message? It shouldn't. 

3) Updating a large maildir can take many minutes with no escape, so I would prefer the `U` as that is harder to hit by mistake.

**Comment by AlejandroCatalina** [comment]
@JorisE yes I misread it :P. 

I also agree with @moesasji observations, it'd be nice to have it that way.

**Comment by nixmaniack** [comment]
Yes, how can I forget that! `C-j` and `C-k` while viewing messages. (Since I use it already I thought it's default!) :+1:

**Comment by darkfeline** [comment]
I don't use enough of mu4e's features to give any specific comments; the default `j`, `k` is good enough for me.  https://github.com/syl20bnr/spacemacs/pull/3922 looks good.

If/when someone makes a PR with more comprehensive re-bindings, I'll be happy to take a look at it, for what it's worth.

**Comment by AlejandroCatalina** [comment]
Could http://github.com/JorisE/evil-mu4e be the package to put an end to this discussion? I see it updated and I think it covers all the needs we have been discussing here.

**Comment by StreakyCobra** [comment]
If you reach a consensus for using this package feel free to PR it. I think it's better to have the evilification of mu4e outside of Spacemacs, it will be easier to maintain :-)

**Comment by jtmoulia** [comment]
Would spacemacs leader keybindings, e.g. <kbd>SPC m j</kbd> or something, be specified in the mu4e layer itself or `evil-mu4e`?

**Comment by nixmaniack** [comment]
@jtmoulia `SPC m` belongs with Spacemacs.

**Comment by AlejandroCatalina** [comment]
That would be set in the layer yes. I'm for PRing the package into we layer if everyone agrees. I'd leave it to @JorisE if he wants, or anyone.

**Comment by moesasji** [comment]
Overall moving things over to evil-mu4e seems a good strategy, although I'm not yet convinced of the key-bindings picked. 

1) 'x' is used for deleting messages, which is a hard to reach key on any keyboard, making it a bad choice for one of the most used keys when processing emails. Better option is to keep it as `d' (delete), which would be consistent with vim.

2) What happened with the unset marks and global unset for setting flags in message-view? That was on 'u' and 'U' respectively. Those are important and get overwritten with the "mark unread" as far as I can tell.

**Comment by AlejandroCatalina** [comment]
Actually, I agree in the two pointed things. I miss `u` to unmark. If
@JorisE is okay with this changes we can move on.

Moesasji writes:

> Overall moving things over to evil-mu4e seems a good strategy, although I'm not yet convinced of the key-bindings picked. 
>
> 1) 'x' is used for deleting messages, which is a hard to reach key on any keyboard, making it a bad choice for one of the most used keys when processing emails. Better option is to keep it as `d' (delete), which would be consistent with vim.
>
> 2) What happened with the unset marks and global unset for setting flags in message-view? That was on 'u' and 'U' respectively. Those are important and get overwritten with the "mark unread" as far as I can tell. 
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/syl20bnr/spacemacs/issues/4490#issuecomment-183685395


-- 
Un saludo,
Alejandro Catalina Feliu

**Comment by JorisE** [comment]
After seeing the discussion, I have changed most keybindings bact to the default mu4e bindings. Only where they are obviously conflicting with evil, something else as been chosen. 

I'd like to change the layer to use this package when it's up on MELPA and make a PR for that.

In the meantime I've opened an issue to discuss the keybindings for evil-mu4e at https://github.com/JorisE/evil-mu4e/issues/1.

**Comment by AlejandroCatalina** [comment]
I think the keybindings as they're now are fine. The thing that most troubled me was the C-j C-k in mu4e-view.

After that, sure we can discuss some little tweaks, but i think it'd be nice to have this package as a base and add it to spacemacs. What do you think? @moesasji @JorisE and others interested in mu4e ofc.

**Comment by nixmaniack** [comment]
I'm not convinced with the bindings which `evil-mu4e` has chosen(e.g. update, `u`, jump to maildir `J`). And it seems users have different opinion here if they have used mu4e previously. 

The purpose of having `evil-XYZ` package is to adhere to `vim`/`evil`/spacemacs convention/mnemonics(look at `evil-magit` or `evil-ediff`). I think it needs more thought and discussion as @JorisE pointed here https://github.com/JorisE/evil-mu4e/issues/1

There was a long thread of discussion while deciding bindings for evil-magit, it might be helpful to take a look https://github.com/justbur/evil-magit/pull/2

**Comment by AlejandroCatalina** [comment]
I agree, there are changes to do. I'd set `U` to update instead of `u` and `j` instead of `J`. The current evilification of mu4e is pretty nice, we could follow some of its keybindings. Using mu4e on emacs (not evil) feels pretty natural, it will not be easy to fully adapt it.

**Comment by JorisE** [comment]
I opened a pull request to use evil-mu4e instead of the currently defined keybindings, but we may have to wait merging untill we are clear on the keybindings...

@nixmaniack: Seeing that thread, I'm starting to doubt if I understood what I signed up for :D. I'll read up on the evil-magit thread.

**Comment by JorisE** [comment]
I have started an issue on the evil-mu4e package, but I might as well as it here again first.

> On the issue of j vs J for jumping to maildir. My preference goes toward using J so that j is free for the movement we know and love from VIM.
> 
> When on a bookmark (or maildir, if you use maildir-extension), hitting enter will bring you to the expected location.
> 
> For me personally, I rarely if ever use the concept of maildirs since I use mu4e, so having the jump-to-maildir under a key without having to press <shift> is not really an issue for me.
> 

If no one has problems with the evil-mu4e package as it is, we might as well merge that?

**Comment by deisi** [comment]
Any updates on this matter? I'm currently on spacemacs master, the mu4e layer and emacs 25.1. Instead of the here discusses `C-j` for down and `C-k` for up, I have `C-k` down and `k` up o.O is that the intended behavior?

**Comment by TheBB** [comment]
Is there some consensus from the mu4e crowd on this?

**Comment by syl20bnr** [comment]
see my comment here: https://github.com/syl20bnr/spacemacs/pull/5114#issuecomment-359146980
