### ISSUE TITLE
Org agenda from the command line

### ISSUE THREAD

**Issue by mbrgm** [syl20bnr/spacemacs#4504]
I was trying to get my org agenda from the command line using `emacs -l ~/.emacs.d/init.el -eval '(org-batch-agenda "a")'`, but all I got was an empty agenda... I suspect this has to do with the async start, but I'm not sure about that. is there something to pay attention to when trying to run cli commands in combination with spacemacs?

**Comment by duerrp** [comment]
Your command works for me. Do you have `org-agenda-files` set?

**Comment by mbrgm** [comment]
Here's what I have in my `.spacemacs`: When I include the setq with the _command line_ call to org-batch-agenda, it works fine, i.e. `/usr/local/bin/emacs -q --batch --eval '(progn (setq org-agenda-files (quote ("~/.deft/"))) (org-batch-agenda "a"))' 2> /dev/null`  -- but why is the .spacemacs config not being used?

```
(defun dotspacemacs/user-config ()
...
  (setq org-agenda-files (quote ("~/.deft/")))
...
)
```

**Comment by halvorlu** [comment]
It seems that `dotspacemacs/user-config` is called by `emacs-startup-hook` (see `core/core-spacemacs.el`). This hook is not called when running emacs in batch mode, see e.g. [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Init-File.html#Init-File). You can run the hook explicitly,

`emacs -l ~/.emacs.d/init.el --eval "(run-hooks 'emacs-startup-hook)" --eval '(org-batch-agenda "a")'`

This seems to work for me at least.

**Comment by concretevitamin** [comment]
@halvorlu It doesn't seem to work for me:
```
~ » emacs -batch -l ~/.emacs.d/init.el -eval '(org-batch-agenda "a" org-agenda-span 7)'                                                                                                                 255 ↵

Loading /Users/me/.emacs.d/core/core-versions.el (source)...
Loading /Users/me/.emacs.d/core/core-load-paths.el (source)...
Symbol's value as variable is void: user-emacs-directory
```

**Comment by halvorlu** [comment]
Did you try to run the `emacs-startup-hook` by including `--eval "(run-hooks 'emacs-startup-hook)"`?

**Comment by concretevitamin** [comment]
@halvorlu Yes. Using `/Applications/Emacs.app/Contents/MacOS/Emacs`, which is 25+, solved the issue for me.

**Comment by glumanda99** [comment]
@halvorlu What about `org-agenda-batch-csv`? I tried

```
#!/bin/bash
emacs -batch -l ~/.emacs.d/init.el --eval "(run-hooks 'emacs-startup-hook)" --eval '(org-batch-agenda-csv "a")' # 2> /dev/null
```

but it won't return anything. If I try the same function in emacs scratch buffer and use `eval-buffer` I only get the agenda but no csv.

**Comment by halvorlu** [comment]
I haven't tried `org-batch-agenda-csv`, so I'm not sure what could be the cause...

**Comment by mbrgm** [comment]
I switched to plain Emacs from Spacemacs in the meantime, so this is "resolved" for me.
