### ISSUE TITLE
initial binding for TAB in org mode wrong (evil-jumper/forward)

### ISSUE THREAD

**Issue by choppsv1** [syl20bnr/spacemacs#4505]
Get fresh repo, start with template dotfile, enable org mode in addition to emacs-lisp. Launch emacs with org file, hit SPC h d k TAB see that it's wrong. Hit "i" to enter insert mode, hit "ESC" to exit, SPC h d k TAB see that it's now correctly org-cycle.

**Comment by moesasji** [comment]
I can't reproduce this on a clean org-file. Hitting `SPC h d k TAB` brings up the help for `TAB` immediately as expected.

**Comment by Andre0991** [comment]
@moesasji I think @choppsv1 meant that `TAB` is not binded to `org-cycle`.

**Comment by choppsv1** [comment]
On a clean org file I am not seeing the bug.. I'm seeing with a medium size 99k org file.. Trying to narrow this down currently.

**Comment by choppsv1** [comment]
Here's the smallest org file that triggers the bug AFAICT, the "emacs-lisp" is important as is the indent startup flag, SRC is not important (i.e., could use BEGIN_FOOBAR)

#+STARTUP: indent
* Foo
#+BEGIN_SRC emacs-lisp
#+END_SRC

**Comment by moesasji** [comment]
Also with that file I can't reproduce it on 0.105.4; for me the TAB-key cycles as expected and also `SPC h d k TAB` immediately gives the correct information. This is with the org layer and the emacs-lisp layer enabled. 

btw) What is your system-info? You can get that information using `SPC h d s`.

**Comment by choppsv1** [comment]
You started with fresh clone of develop, template .spacemacs, only add org layer, and the exact file from above? I dunno. It happens for me. :)

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.4
- Spacemacs branch: develop (rev. a5be67b)
- Distribution: spacemacs
- Layers:
```elisp
(emacs-lisp org)
```

**Comment by justbur** [comment]
Possibly related https://github.com/syl20bnr/spacemacs/pull/4379

**Comment by syl20bnr** [comment]
I cannot reproduce it with the above repro steps :-(

**Comment by choppsv1** [comment]
FWIW, I've been putting some debug stuff in, and in user-config the buffer is available and in org mode and the key is incorrectly mapped, but if I then do a evil-normalize-keymaps it fixes it. I'm not sure how to debug this though. Presumably something is aborting at some point  due to the file format which avoids the proper keymap modifications being made, but the error is being caught and ignored.

I'm not sure what could be different between mine and other systems to make it not reproducible. :(

**Comment by syl20bnr** [comment]
So we have another instance #4379 as @justbur mentioned but the symptoms are a bit different.
Looks like a serious bug to me.

**Comment by choppsv1** [comment]
I'm running in terminal mode. This is also reproducible under archlinux; however, if I run emacs under X11 in archlinux (i.e., no -nw argument) then the bug is not present. Is everyone else not able to reproduce this running GUI/X11? Can you please try "emacs -nw foo.org" when you load the test file?

**Comment by moesasji** [comment]
That is it, this is specific to running Emacs in terminal mode; with emacs -nw I can indeed reproduce (while the bug doesn't occur under GUI/X11)
