### ISSUE TITLE
Question: How to enable fill-column-indicator when startup

### ISSUE THREAD

**Issue by chaozhn** [syl20bnr/spacemacs#4506]
It's very disappointed that there is no document to guide you how to configure this, I googled and tried some suggestion but failed. Seems the spacemacs document only mentioned **SPC t f** to enable it, but I want to configure my .spacemacs to enable it when emacs start. Could someone can tell me how? Really really appreciate you!
My req:
1. Enable fill-column-indicator when startup
2. Customize fill-column width, I know the default is 80, maybe I want to set it with 100
I tried:
````
(set-fill-column 100) # or (setq-default fill-column 100)
(spacemacs/toggle-fill-column-indicator)
````
But it doesn't work
Thanks!

**Comment by chaozhn** [comment]
OK, I got it. put these in your add-hook for different file type:
````
(set-fill-column 100)
(spacemacs/toggle-fill-column-indicator-on)
````

**Comment by StreakyCobra** [comment]
FYI I have this in my config:
```elisp
  ;; Activate column indicator in most mode, except for org-mode
  (add-hook 'prog-mode-hook 'turn-on-fci-mode)
  (add-hook 'text-mode-hook 'turn-on-fci-mode)
  (add-hook 'org-mode-hook 'turn-off-fci-mode 'append)
```
For the value of `fill-column`, You can probably use
```elisp
(setq-default fill-column 100)
```
only once in `user-init` to set its default value. this will also allow some mode (like python) to override it :-)
