### ISSUE TITLE
"async-handle-result: no such file or directory, git" ignoring exec-path?

### ISSUE THREAD

**Issue by dmich2** [syl20bnr/spacemacs#4507]
#### Description

Just installed spacemacs. I ran into issue #4367 so I put
`(add-to-list 'exec-path "C:/Program Files (x86)/Git/bin")`
in my `(defun dotspacemacs/user-init ()` as I didn't want to put git in my PATH.

I now get the following error:
`error in process sentinel: async-handle-result: Searching for program: no such file or directory, git
error in process sentinel: Searching for program: no such file or directory, git`

Is this related to issue #3390 ?

> brabalan commented on Oct 15, 2015
> @justbur I did not know of async till yesterday, and it seems we have to worry about it anyway (as in: any use of a variable defined outside of the async should be injected). 

as in maybe the value of `exec-path` has to also be "injected"?
#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.4
- Spacemacs branch: master (rev. da94a25)
- Distribution: spacemacs
- Layers:

``` elisp
(emacs-lisp)
```

**Comment by luxbock** [comment]
I'm having this same issue. I'm on Windows as well. I have tried adding git to my `Path` as well which didn't work either.

**Comment by sungam94** [comment]
Problem still exists under windows if custom git path is added to exec-path.

**Comment by rosso-** [comment]
Same problem here on Freebsd 13. Using magit from emacs works fine, but from emacsclient - same issue. Maybe this irrelevant, but maybe not

**Comment by lebensterben** [comment]
@rosso- 
(executable-find "git") ?
