### ISSUE TITLE
When updating packages: copy-directory: Read error: Input/output error

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#4508]
#### System Info
- OS: gnu/linux
- Emacs: 25.1.50.2
- Spacemacs: 0.105.5
- Spacemacs branch: master (rev. b3106c4)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'right)
                 syntax-checking haskell idris purescript clojure eyebrowse)
```

**Comment by StreakyCobra** [comment]
Can you give a backtrace (see [here](https://github.com/syl20bnr/spacemacs/wiki/Debugging))? For me it looks like a problem specific to your installation, or maybe a emacs 25.1 issue.
