### ISSUE TITLE
Remove reference to `haskell-cabal-hook` as a function

### ISSUE THREAD

**Issue by chrisbarrett** [syl20bnr/spacemacs#4512]
The Haskell layer attempts to call `haskell-cabal-hook` as a function. This function is not defined, so an error is raised.

Resolve by removing the reference to `haskell-cabal-hook` [here](https://github.com/syl20bnr/spacemacs/blob/a9f9c1bd97fb9c678ef0ab42e5ce333a1d4b3cd0/layers/%2Blang/haskell/packages.el#L111).

**Comment by syl20bnr** [comment]
Fixed in 0.105.7!
