### ISSUE TITLE
v0.105.x python layer error(pyenv)

### ISSUE THREAD

**Issue by scloudyy** [syl20bnr/spacemacs#4514]
After update to 0.105.x, when I open .py file where pyenv have set a local version(3.5.0) I will get this
![2](https://cloud.githubusercontent.com/assets/15358886/12219757/cdf69aee-b78b-11e5-982a-9febee04f405.png)

If I change the version(2.7.9) this message will also appear.
![1](https://cloud.githubusercontent.com/assets/15358886/12219760/d72a191a-b78b-11e5-9cef-0a6caabaa046.png)

And in my computer both 2.7.9 and 3.5.0 have installed
![3](https://cloud.githubusercontent.com/assets/15358886/12219776/ffdb3402-b78b-11e5-873e-4176728298d1.png)

And besides, "*Python Internal [792caf12c778150badeeede64c068cee]* while let-bound!
" is "*Python Internal [127.0.0.1]* while let-bound!" in 0.104.x, it also changed.

**Comment by syl20bnr** [comment]
Thank you for the report, cc @cpaulik @TheBB

**Comment by fbergroth** [comment]
Sorry, that was from my code. I always use named environments so I didn't run into this. Should be fixed in #4518.

**Comment by cpaulik** [comment]
@fbergroth Thanks, I was just about to submit a PR fixing that.

**Comment by scloudyy** [comment]
@fbergroth Thanks! And do you hava any idea about [127.0.0.1] change to the [792caf12c778150badeeede64c068cee]? It seems not good.

**Comment by syl20bnr** [comment]
Fixed in 0.105.7!

**Comment by fbergroth** [comment]
> @fbergroth Thanks! And do you hava any idea about [127.0.0.1] change to the [792caf12c778150badeeede64c068cee]? It seems not good.

@scloudyy sorry, no idea, but it's probably fine.
