### ISSUE TITLE
Show function signature when autocompleting Rust code

### ISSUE THREAD

**Issue by carlosgaldino** [syl20bnr/spacemacs#4519]
Following #4368, why when autocompleting rust code the function signature doesn't appear?

Is it a configuration problem from spacemacs? Therefore why not provide the required configuration for showing the function signature? Or should it be something configured manually by each user in the `.spacemacs` file? How could I do that?

Thanks.

**Comment by fbergroth** [comment]
Please try my updates to the rust layer in #4516.

**Comment by carlosgaldino** [comment]
@fbergroth With your changes the signatures appear just fine. Thank you.

**Comment by carlosgaldino** [comment]
@StreakyCobra I will close this issue since the changes from @fbergroth are already in the `develop` branch. Thank you both.

**Comment by carlosgaldino** [comment]
@fbergroth What was the change responsible for making the function signature appear in the tooltip?

I'm asking it because the Golang layer has the same problem and I can't find why.

Thank you.

**Comment by fbergroth** [comment]
That's not a general feature, but has to be implemented in every company backend.

For Golang, try `(setq company-go-show-annotation t)`. It should probably be set in the Golang layer or mentioned in the readme.

**Comment by carlosgaldino** [comment]
@fbergroth Yeah, minutes after posting the question I found it and [opened a PR](https://github.com/syl20bnr/spacemacs/pull/4960).

Thank you.
