### ISSUE TITLE
Markdown highlighting does not support triple-tic (```) pre-blocks

### ISSUE THREAD

**Issue by athanclark** [syl20bnr/spacemacs#4527]
The triple-tic ``` syntax is useful for explicitly designating the highlighting language. For instance:

    ``` javascript
    function foo() {
    ...
    }
    ```

However, spacemacs doesn't recognize this as a `pre` block. Ideally of course, we would like to sub-syntax highlight the pre-block, knowing which language should be used (in this case, Javascript), but this is a far cry. I would still be happy with the opaque default for normal `pre` blocks, though.

**Comment by syl20bnr** [comment]
You can add support for languages here: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/markdown/packages.el#L151-L185

PR welcome :-)

**Comment by AlejandroCatalina** [comment]
Please review the PR, I think that will be it.

**Comment by syl20bnr** [comment]
Fixed in 0.105.8
