### ISSUE TITLE
On first init, get Error: "Invalid face" error

### ISSUE THREAD

**Issue by freedryk** [syl20bnr/spacemacs#453]
emacs errors on init with "Invalid face".  On debian wheezy.

Running emacs in debug mode gives:
```
Debugger entered--Lisp error: (error "Invalid face" error)
  internal-get-lisp-face-attribute(error :foreground nil)
  face-attribute(error :foreground nil nil)
  face-foreground(error)
  (let* ((fname ...) (foreground ...)) (eval (\` ...)) (set-face-attribute fname nil :foreground foreground :box (face-attribute ... :box)))
  spacemacs//deffaces-new-version-lighter(error)
  mapcar(spacemacs//deffaces-new-version-lighter (error warning success))
  spacemacs/set-new-version-lighter-mode-line-faces()
  eval-buffer(#<buffer  *load*<2>> nil "/home/freedryk/.emacs.d/core/spacemacs-mode.el" nil t)  ; Reading at buffer position 12848
  load-with-code-conversion("/home/freedryk/.emacs.d/core/spacemacs-mode.el" "/home/freedryk/.emacs.d/core/spacemacs-mode.el" nil t)
  require(spacemacs-mode)
  eval-buffer(#<buffer  *load*> nil "/home/freedryk/.emacs.d/init.el" nil t)  ; Reading at buffer position 405
  load-with-code-conversion("/home/freedryk/.emacs.d/init.el" "/home/freedryk/.emacs.d/init.el" t t)
  load("/home/freedryk/.emacs.d/init" t t)
  #[nil "^H\205\264^@   \306=\203^Q^@\307^H\310Q\2027^@ \311=\2033^@\312\307\313\314#\203#^@\315\2027^@\312\307\313\316#\203/^@\317\2027^@\315\2027^@\307^H\320Q^Z\321^S\322\n\321$
  command-line()
  normal-top-level()
```

**Comment by syl20bnr** [comment]
@freedryk what is the installed version of Emacs on wheezy ?

**Comment by syl20bnr** [comment]
Does it prevent spacemacs from completety booting each time or is it only the first time ?

**Comment by freedryk** [comment]
GNU Emacs 23.4.1

It fails each time.  I tried it several times, and also blew away the .emacs.d/ directory and re-cloned the git repository a couple of times.

**Comment by syl20bnr** [comment]
Do you mean 24.3.1 instead of 23.4.1 ?
I'll give it a look tonight.

**Comment by syl20bnr** [comment]
Ok, I was surprised that your version is `23.4.1` and you get an error from spacemacs instead of a raw Emacs without any error.

Spacemacs is [only compatible with 24.3 and above](https://github.com/syl20bnr/spacemacs#emacs-version).

**Comment by syl20bnr** [comment]
@freedryk Can you retry with the last version 0.48.3 ? You should not have any error and end up with a raw emacs since your emacs version is not supported.

Thank you!

**Comment by freedryk** [comment]
Confirmed, 0.48.3 no longer shows an error message.

**Comment by syl20bnr** [comment]
Yeah ! Thank you @freedryk.
