### ISSUE TITLE
Command to select current function

### ISSUE THREAD

**Issue by cremacs** [syl20bnr/spacemacs#4531]
Emacs has mark-defun, to select the function that point is in. This functionality varies between major modes, obviously, but mark-defun leverages mode knowledge to make it work. Can spacemacs support a text object that knows about functions, particularly for python? https://github.com/bps/vim-textobj-python is a vim attempt.

**Comment by cremacs** [comment]
Sorry, emacs has a special implementation for python: https://github.com/emacs-mirror/emacs/blob/91917dd58ec5278e555b9c693a830749083e8f89/lisp/progmodes/python.el has an implementation of python-mark-defun which is remapped

**Comment by skparkes** [comment]
I too would like to see this happen.  You can get close with the indentation-objects, but they're very sensitive as to what line you start on.  I'd love to see a port of vim-textobj-python.
