### ISSUE TITLE
Org-mode: action of keybinding `t` behaves strange

### ISSUE THREAD

**Issue by kccai** [syl20bnr/spacemacs#4533]
The following is my spacemacs configuration:
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.7
- Spacemacs branch: develop (rev. 59319f9)
- Distribution: spacemacs
- Layers:

``` elisp
(
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
 better-defaults
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 emacs-lisp emoji ess evil-commentary
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 eyebrowse git gtags html ibuffer
 (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill t)
 markdown
 (org :variables org-enable-github-support t)
 (python :variables python-enable-yapf-format-on-save t)
 ranger
 (shell :variables shell-protect-eshell-prompt nil shell-enable-smart-eshell t shell-default-shell 'eshell)
 spell-checking spacemacs-helm semantic syntax-checking unimpaired
 (version-control :variables version-control-diff-tool 'git-gutter)
 ycmd)
```

In the `org` mode, the action of keybinding `t` changed after the buffer is reverted.  Specifically, when I open an org file **just after starting Emacs**, I find the keybinding `t` always runs the command `evil-snipe-t`. But when I run `revert-buffer` on the org file, I find the keybinding`t` runs the command `org-todo`.  The different behaviours of `t` have been bugging me for a while. 

I wonder if this problem is caused by `evil-snipe`. Thus I turn off `evil-snipe` in `org` mode in my `user-config` with

```
  (add-hook 'org-mode-hook 'turn-off-evil-snipe-override-mode)
  (add-hook 'org-mode-hook 'turn-off-evil-snipe-mode)
```

Now a much more strange problem occurred in the `org` mode buffer. When I open an org file **just after starting Emacs**, the first pressing of `t` binds to `evil-find-char-to`, and the following pressings of `t` bind to `org-todo`. 

Do you guys have the same problem? Is there any way to set `t` just binds to `org-todo` on the first pressing of `t`?

**Comment by TheBB** [comment]
This is due to a missing evil keymap normalization in some modes, see https://bitbucket.org/lyro/evil/issues/301/evil-define-key-for-minor-mode-does-not for details. We fixed this for ledger-mode [here](https://github.com/syl20bnr/spacemacs/blob/develop/layers/finance/packages.el#L51). Presumably the same applies for org.

**Comment by kccai** [comment]
@TheBB Thanks for the information. Sounds like I hit an evil bug ...
