### ISSUE TITLE
Javascript issues with latest v.0.105.8

### ISSUE THREAD

**Issue by stormpat** [syl20bnr/spacemacs#4534]
When editing a javascript file i get a lot of warnings, and finally spacemacs wont go to normal mode. I just "hangs in insert-mode" 

I get the following error message: 

`fringe-helper-modification-func: Invalid search bound (wrong side of point)`

I have the following packages installed

``` lisp
   dotspacemacs-configuration-layers
   '(
     better-defaults
     emacs-lisp
     git
     evil-commentary
     rust
     evil-snipe
     vim-empty-lines
     haskell
     javascript
     themes-megapack
     react
     elm
     php
     elixir
     ;;vim-powerline
     (auto-completion
      :variables
      auto-completion-private-snippets-directory "~/.emacs.d/private/snippets/yasnippet-snippets"
      auto-completion-enable-sort-by-usage t
      auto-completion-enable-snippets-in-popup nil
      auto-completion-enable-help-help-tooltip t)
     syntax-checking
     version-control
     html
     )
```

**Comment by stormpat** [comment]
Ok, the issue seems to be gone after i updated all my packages too.. Ill close this for now..

**Comment by stormpat** [comment]
Nope this is back again. I deleted everything inside elpa, and updated to the latest tagged release (0.105.8) Seems to be similar to #1654

**Comment by stormpat** [comment]
Ok i found a way to repro.

This issue seems to happen when in a project with version-control (git).

Steps:

- open any javascript file, add a few lines of code and commit the changes.
- close the buffer open with the file you just saved
- re-open the buffer and make some changes (e.g. empty lines) and save the buffer, now you see the green plus signs in the fringe
- deliberately make syntax errors, inside the changed code area (where there are plus signs)

Now evil is dead, and you cannot exit the normal mode.

Heres a gif:

![error gif](http://i.imgur.com/2MdZWap.gif)

**Comment by gabrielalmeida** [comment]
Exact same issue here after upgrading to `v.105.9`. Disabling `version-control` layer seems to be a temporary workaround.

**Comment by JuanCaicedo** [comment]
@gabrielalmeida Have you found a way to quickly toggle `version-control`? I'm having the same problem and would like to I'd like to disable without editing my `.spacemacs` :smiley:

**Comment by justbur** [comment]
A few things:

 1. version-control uses one of three "backends" so you can try the others. See the    readme
 2. This could easily be an upstream issue with one of them, so it would be helpful to narrow it down. 
 3. When there's an error a backtrace is really helpful. See [here](https://github.com/syl20bnr/spacemacs/wiki/Debugging#enable-debug)
 4. Yes, you can toggle the underlying mode, but you need to know which one you are using. Then it's just `SPC :` (or `M-x`) with the name of the mode. `git-gutter+-mode` for example.

**Comment by JuanCaicedo** [comment]
@justbur sad to not be able to use git gutter, but number 4 definitely solved my pain point for now :+1: Thanks!

If it's helpful, this is an error I saw following the instructions above:

```
Debugger entered--Lisp error: (cl-assertion-failed (eq 10 (char-before)))
  signal(cl-assertion-failed ((eq 10 (char-before))))
  #[0 "`Sf\304=\204\305\306\307C\"\210\203\310`\311\300!Z`\"\210\212\302b\210\312 \210\313\314!\2034\315 \316V\2034`\317 |\210)\301\206=\320\321\322\"\207" [nil nil 85 use-hard-newlines 10 signal cl-assertion-failed (eq 10 (char-before)) set-hard-newline-properties prefix-numeric-value beginning-of-line looking-at "[ 	]$" current-left-margin 0 line-end-position move-to-left-margin nil t] 4 "\n\n(fn)"]()
  self-insert-command(1)
  call-interactively(self-insert-command nil nil)
  command-execute(self-insert-command)
``

**Comment by justbur** [comment]
@JuanCaicedo It could be a config problem or a problem with the upstream package. Unfortunately, that backtrace doesn't indicate which package the error is coming from.

**Comment by d12frosted** [comment]
Any updates with the latest Spacemacs? 😸

**Comment by stormpat** [comment]
This issue seems to be fixed. Im using the latest master.
