### ISSUE TITLE
0.105: issues with daemon mode

### ISSUE THREAD

**Issue by emmanueltouzery** [syl20bnr/spacemacs#4537]
I have this in my `.spacemacs`:

    (setq powerline-default-separator 'nil)

and also:

    ;; the fringe having a different background color than the
    ;; frame looks ugly to me, especially when you start splitting
    ;; the window with several buffers
    ;; http://emacs.stackexchange.com/a/5343/2592
    (set-face-attribute 'fringe nil
                      :foreground (face-foreground 'default)
                      :background (face-background 'default))

Both are in my `dotspacemacs/user-config`.

They work after startup if I start spacemacs using `emacs`. They do not work however if I start it using `emacsclient -c "$@" --alternate-editor=`. That used to work fine in v0.104.

Both commands do work if I run them manually after startup.

**Comment by TheBB** [comment]
Try delaying it until after the frame is created.

```lisp
(spacemacs|do-after-display-system-init
  ;; ...
  )
```

**Comment by emmanueltouzery** [comment]
yes, that works. So that's a change in behaviour, but probably it's not a bug after all... closing then. Thank you!
