### ISSUE TITLE
Open the quick help. and than Spacemacs freeze few minutes

### ISSUE THREAD

**Issue by arstum** [syl20bnr/spacemacs#4554]
Loading /Users/xxx/.emacs.d/core/core-load-paths.el (source)...done
Loading /Users/xxx/.spacemacs...done
(Spacemacs) Warning: Cannot find font "Source Code Pro"!
Loading /Users/xxx/.emacs.d/.cache/spacemacs-buffer.el (source)...done
Saving file /Users/xxx/.emacs.d/.cache/spacemacs-buffer.el...
Wrote /Users/xxx/.emacs.d/.cache/spacemacs-buffer.el
Open the quickhelp.
Loading /Users/xxx/.emacs.d/layers/+distribution/spacemacs-base/funcs.el (source)...done
Loading /Users/xxx/.emacs.d/layers/+distribution/spacemacs-base/config.el (source)...done
Loading /Users/xxx/.emacs.d/layers/+distribution/spacemacs-base/keybindings.el (source)...done
Loading /Users/xxx/.emacs.d/layers/+lang/emacs-lisp/config.el (source)...done
Loading /Users/xxx/.emacs.d/layers/+distribution/spacemacs-base/packages.el (source)...done
Loading /Users/xxx/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done
Spacemacs is ready.

**Comment by arstum** [comment]
Spacemacs version "0.105.7"

**Comment by arstum** [comment]
Just installed

**Comment by arstum** [comment]
It`s done.

problem is
(Spacemacs) Warning: Cannot find font "Source Code Pro"!

app is fine after installed Source Code Pro with Font book

**Comment by TheBB** [comment]
Closing, then. Thanks!

**Comment by TheBB** [comment]
You can set it to a different font in your dotfile by the way.
