### ISSUE TITLE
0.105.x releases made too frequently

### ISSUE THREAD

**Issue by KenetJervet** [syl20bnr/spacemacs#4556]
Have to (or am obsessive) restart my emacs instances after each release :(

Maybe create a "stable" branch (more thoroughly tested) or something alike?

**Comment by syl20bnr** [comment]
You can update at your own peace, nobody forces you to update at each new release :-)

It would be cool to be able to fetch the change log so people can read about it and then decide if they want to update or not.

This is funny that no matter what we do, people will always complain :joy:

**Comment by chrisbarrett** [comment]
I, for one, like bug fix releases. ;)

**Comment by StreakyCobra** [comment]
But to be honest we went from 1 release each month with bugfix only, to one release per day with new features :joy: We probably have to find an in-between pace.

**Comment by darkfeline** [comment]
I think frequent bugfix releases are fine.  Users are free to stay on their current version until they hit a bug, then they can just update to the latest version.

On a tangent, can Spacemacs officially support semantic versioning http://semver.org/?  It seems like we're doing this already, only need to make it official/documented.

**Comment by syl20bnr** [comment]
> to one release per day with new features :joy: We probably have to find an in-between pace.

We have the in between already, current 0.105 releases are for bug fixes mainly, coupled to small improvements that would be bad to keep in develop for the next major release. Big changes like Ivy or changes I judge risky stays in develop. This new approach brings the new file CHANGELOG.next which allow me to cherry-pick more easily.

We'll work on a blog for the website so we will be able to communicate with users about such changes and the motivations.

As @darkfeline said, users are free to stay on their current version so the old release cycle still hold for people willing less frequent updates.

But the most important thing in this new pace is the smaller is the delta between versions the easier it is to revert back to a working state and bissect. Thanks to git people can switch the version of Spacemacs very easily, if 0.105.n breaks then in a matter of seconds users can switch to n-1 with `spacemacs/switch-to-version`.

**Comment by scloudyy** [comment]
Open a blog is a nice idea!👍

**Comment by robbyoconnor** [comment]
I use `develop` and regularly fetch before I pull in changes...and will look at each commit...`master` will always be the latest release...so you can do the same.

**Comment by robbyoconnor** [comment]
As many have said, nobody is forcing you to update. Why this is even brought up is beyond me.

**Comment by nwolfe** [comment]
> I use develop and regularly fetch before I pull in changes...and will look at each commit...master will always be the latest release...so you can do the same.

Yes, this is how I stay up to date as well.  Never do a `git pull`, instead `fetch` the commits, and then you can go through the commits/changes as you like or switch to `origin/develop` and try it out.

Perhaps some docs on various ways you can stay up to date would be worthwhile.

**Comment by robbyoconnor** [comment]
> Yes, this is how I stay up to date as well. Never do a git pull, instead fetch the commits, and then you can go through the commits/changes as you like or switch to origin/develop and try it out.
>
> Perhaps some docs on various ways you can stay up to date would be worthwhile.

This boils down to knowing git well and not in the scope of this project honestly...let's assume people know that much.

**Comment by d12frosted** [comment]
Yeah, there are things that we have to document (`A`) and things that we can document (`B`). It would be great to avoid documenting `B \ A`. But we cal always point to the knowledge. :)
