### ISSUE TITLE
SPC-: (M-x) typing out-of-order?

### ISSUE THREAD

**Issue by m3hr** [syl20bnr/spacemacs#456]
I recently switched from Prelude to Spacemacs, but one of the things I sorely miss is being able to run the helm M-x and type in commands out of order and still get suggestions. In Spacemacs it seems I am unable to do this even with helm? Sorry if this is a duplicate question.

**Comment by syl20bnr** [comment]
Can you provide a repro step ?

**Comment by m3hr** [comment]
It seems you have to preserve the order of the characters *generally* in Prelude, but *specifically and consecutively* in Spacemacs:
![screenshot from 2015-01-20 12 17 59](https://cloud.githubusercontent.com/assets/700679/5822086/f22c24b0-a09e-11e4-8bf8-d55206a424d7.png)
![screenshot from 2015-01-20 12 21 02](https://cloud.githubusercontent.com/assets/700679/5822090/f429d8ac-a09e-11e4-831f-9b75d01310b2.png)

**Comment by syl20bnr** [comment]
Oooh OK, in prelude it is `ido`.

Use the [smex layer](https://github.com/syl20bnr/spacemacs/tree/master/contrib/smex).

Enjoy :-)

**Comment by syl20bnr** [comment]
@m3hr Note: the `leader on jk` experimental feature mentioned in the README of the layer has been removed. I just pushed a commit to update the README.

**Comment by m3hr** [comment]
Sorry for such an obvious question there, hope it helps others. I'm about to make a pull req for a different but simple thing.

**Comment by syl20bnr** [comment]
Your question are welcome.
