### ISSUE TITLE
Unable to quit spacemacs 

### ISSUE THREAD

**Issue by rahulmutt** [syl20bnr/spacemacs#4564]
When I press C-x C-c, it prevents me from quitting emacs by showing 'Text is read-only' in the mini-buffer. I also notice that I'm unable to modify anything in eshell (my default shell) if this happens. I am using emacs-24.5.2 and spacemacs-0.105.8. I am not able to reproduce this consistently, it'll be very random. I don't know if I'm pressing any key combination by mistake. Which elisp package will create the 'Text is read-only' message?

**Comment by syl20bnr** [comment]
Can you provide a repro step that we can follow to see if we end up with the same behavior ?

**Comment by syl20bnr** [comment]
> I am not able to reproduce this consistently, it'll be very random.

I missed this, tell us when you find something that we can test.

**Comment by kRITZCREEK** [comment]
Love the issue title. I have the same problem... spacemacs really is THAT good

**Comment by robbyoconnor** [comment]
Can't quit, Won't quit.

**Comment by rahulmutt** [comment]
So I made a observation today. This happens when I'm running a process from emacs shell that doesn't terminate right away (like a server) and if by accident I shift to that window and forget to type SPC before the other letters, a weird situation happens where I'm unable to delete the garbage characters. Then that error 'Text is read-only' comes up and I can't quit. Now if I do SPC b k and kill the shell buffer, I'm able to quit properly. I'll update with more observations next time it happens.

**Comment by Tinker-S** [comment]
I come across the same problem too. I can't kill my eshell buffer or exit emacs. My message buffer show the message below

`(No files need saving)
eshell-save-some-history: Text is read-only`

**Comment by bersace** [comment]
Running `emacs -nw` with spacemacs prevent me to quit with `C-x C-c` too :( 

0.200.3@24.5.1

**Comment by jwintz** [comment]
Hello,

> On 24 Oct 2016, at 13:49, Étienne BERSAC <notifications@github.com> wrote:
> 
> Running emacs -nw with spacemacs prevent me to quit with C-x C-c too :(
> 

Had the same issue, it seems to come from persp-mode. Try upgrading this package and it should be fine.

  - ju

**Comment by bersace** [comment]
I workaround with `ESC : q RET` ;-)

**Comment by mravery** [comment]
Check to see if in your .spacemacs file `dotspacemacs-persistent-server` is set to true. If it is, using C-x C-c won't quit spacemacs.

**Comment by simendsjo** [comment]
I got the same issue with eshell. I managed to get around the issue by changing the buffers mode to `fundamental-mode`, and then quit. Not sure how I got into that mess though.

**Comment by robbyoconnor** [comment]
Sorry, I had to do this: 
![](https://media1.tenor.com/images/20958059502f390276c3cf64cfcc25d8/tenor.gif?itemid=4607884)

**Comment by Tinker-S** [comment]
I have no idea for the root cause. But I found a solution to resolve this problem.

First, use 'M-x text-mode' to change the eshell-mode to text-mode, then 'SPC b d' can work as we expect.

**Comment by tabesc** [comment]
@Tinker-S Your solution works for me.

**Comment by tabesc** [comment]
@syl20bnr I reproduced this issue:

**Comment by raventid** [comment]
There is an older issue #3565 with another hacky solution, just FYI.
