### ISSUE TITLE
[SPC f J] open-junk-file doesn't create date-format sub-directory

### ISSUE THREAD

**Issue by ianbattersby** [syl20bnr/spacemacs#4566]
Just having a play with open-junk-file and notice it now defaults to YYYY/MM sub-directory suffix to `.cache/junk`, however when completing the filename and hitting RET it doesn't create the directory should it not exist. Am I missing something?

* [SPC f J]
* `~/.emacs.d/.cache/junk/2016/01/12-115705.<test.js>` RET
* "no such file or directory, /Users/ian/.emacs.d/.cache/junk/2016/01"

**Comment by ianbattersby** [comment]
Apologies, I just realised this is related to the in-development ivy layer.

**Comment by ikhthiandor** [comment]
Can we reopen this issue, please? Ivy doesn't work with `open-junk-file`. Helm works and it asks whether it should create the directory for junk file. I am happy with ivy. This is the only case I've found so far that ivy doesn't work for me.

**Comment by d12frosted** [comment]
It doesn't ask me to create dir, but still creates and finds file without any errors. Are you on master or develop?

**Comment by ikhthiandor** [comment]
I'm on develop(commit dfad604faaa542080d252902babfdd392e354eea)

**Comment by ikhthiandor** [comment]
Sorry to bother. It's working after disabling ivy layer and then re-enabling and syncing configuration. Weird.

**Comment by TheBB** [comment]
Could have been your packages that were out of date then?

**Comment by ikhthiandor** [comment]
Possibly. I updated my packages yesterday though. Maybe was using cached package?

**Comment by d12frosted** [comment]
AFAIK, if you don't evaluate new package (by reloading Emacs or manual sync) after upgrade you are still using old version. I could be wrong, but this is how it works in my opinion. 

I wonder if anything was changed in `ivy` that could break / fix `SPC f J`
