### ISSUE TITLE
search-engine layer does not work with spacemacs-ivy

### ISSUE THREAD

**Issue by algernon** [syl20bnr/spacemacs#4568]
When using `spacemacs-ivy`, and enabling the `search-engines` layer, trying to use it yields the following error:

```
spacemacs/search-engine-select: Symbol's function definition is void: helm
```

**Comment by StreakyCobra** [comment]
Thanks for the report! `ivy` support is still in progress, so not all function are replaced for now. Can you please report this enhancement (`ivy` support for `spacemacs/search-engine-select`) to https://github.com/syl20bnr/spacemacs/issues/4540 ? We are trying to centralize all `ivy` suggestions there :smiley:

Thanks :+1:

**Comment by algernon** [comment]
Sure thing, copying it there!
