### ISSUE TITLE
Exporting org files break when they have a title or author

### ISSUE THREAD

**Issue by mistnim** [syl20bnr/spacemacs#4571]
This should be the same bug as: http://emacs.stackexchange.com/questions/14763/exporting-org-file-breaks-when-upgrading-to-orgmode-8-3

The answer gives a fix for emacs, but I don't know how to apply it in spacemacs.
(I thought this issue was specific to spacemacs because personally I don't have it when installing org 8.3 on vanilla emacs)

**Comment by gforsyth** [comment]
Hey @mistnim -- I had the same issue -- exports breaking and also I couldn't use `org-preview-latex-fragment`.  Following the instructions in the stackexchange post fixed it for me.
