### ISSUE TITLE
Cannot find directories ending in `.svn` or `.git`

### ISSUE THREAD

**Issue by bluezio** [syl20bnr/spacemacs#4572]
While finding files with `C-x f``, directories ending in`.svn`or`.git`(but not exactly those strings), such as`org.hawk.svn`or`org.hawk.git` cannot be found.

**Comment by d12frosted** [comment]
@bluezio does it still happen to you?

**Comment by bluezio** [comment]
No, this seems to work fine now. Thank you for reminding me!
