### ISSUE TITLE
What's effect of Enable Clang support?

### ISSUE THREAD

**Issue by jcppython** [syl20bnr/spacemacs#4573]
In c-c++ layer, it has a custom variable:
```
(setq-default dotspacemacs-configuration-layers
  '((c-c++ :variables c-c++-enable-clang-support t)))
```
I want to know what's effect after add this support? 
Now, i feel emacs become visibly after adding it... ...

Is it used to support auto-completion? Do we have other option?.. It may be slow ..

**Comment by scloudyy** [comment]
Use clang to complete C-C++ code, you should install clang in your system. It's precise but slow if project is big. You can also use ycmd which use libclang to do the same thing, and ycmd is a bit quick.

**Comment by fenxian** [comment]
@scloudyy Thank you~
I can have a better candidate for auto-completion with it. But .. visibly, it have some delay and higher cpu. Sometimes, I have to perform `company-complete`.

**Comment by fenxian** [comment]
Sometimes, auto-completion doesn't work... I find that `company-clang` can provide better candidate. Why it doesn't work automatic? What it needs configuration?... I have some fault？
:question:

**Comment by TheBB** [comment]
I'm closing this as the original question is answered and there's little to go on with your last comment. Please open a new issue with more precise questions if you wish.
