### ISSUE TITLE
Just one more issue... Gemfile, rakefile,etc should be in ruby-mode by default

### ISSUE THREAD

**Issue by m3hr** [syl20bnr/spacemacs#458]
Spacemacs should have those filetypes and more (like Podfile, etc) syntax highlight as a ruby file would be syntax highlighted.

**Comment by m3hr** [comment]
The code for this is on https://github.com/syl20bnr/spacemacs/blob/b65eecf57f02d86bbb27ef609d384256eb779a92/spacemacs/packages.el#L1929 but I don't know enough about ELisp to know if this is case-sensitive or not.

**Comment by syl20bnr** [comment]
This is dead code, the ruby stuff is in a contrib layer now, see here: https://github.com/syl20bnr/spacemacs/tree/master/contrib/lang/ruby

I'll have to remove those dead code :-)

**Comment by syl20bnr** [comment]
@m3hr What's the status on this issue ?

**Comment by m3hr** [comment]
If I just move that code into the contrib layer, it won't work, where do I hook it in?

**Comment by m3hr** [comment]
Oh that code is already in the contrib layer's package.el, but it's not activating for me.

**Comment by m3hr** [comment]
Enhanced ruby mode also seems somewhat abandoned compared to the regular ruby mode which gets active development, don't you think?

**Comment by m3hr** [comment]
Wait, it seems like my version's outdated.

**Comment by m3hr** [comment]
Of spacemacs that is. Updating via the update button wouldn't bump me from 0.48.2 to 0.60

**Comment by m3hr** [comment]
So after a git pull, even on the newest version my Gemfile does not get ruby highlighting, so it doesn't seem to work for those files, but it still works for .rb files. Also I can add the "podfile" case to the contrib code.

**Comment by m3hr** [comment]
Also, doing the git pull breaks changes in the .spacemacs file (my default theme variable was outdated and I had to figure out why)

**Comment by m3hr** [comment]
Oh I realized I had messed up my .spacemacs for the ruby thing. Sorry!

**Comment by syl20bnr** [comment]
@m3hr np.
@bru what do you think about `ruby-mode`, I think you replaced it by `enh-ruby-mode` because it is better than `ruby-mode` isn't it ?

**Comment by syl20bnr** [comment]
@m3hr for the version bump issue, for now the `[Update]` only update the ELPA packages, not spacemacs repository. I will work on it soon.

**Comment by bru** [comment]
@syl20bnr @m3hr the reason for `enh-ruby-mode` was that it allegedly has better support for ruby 1.9+; 
However, now that we're close to the 1.9 end of life (it'll stop being supported on 25/02/2015), I'll check whether `ruby-mode` has caught up and take it from there. 

By the way, Gemfile and Rakefile should already be recognised as Ruby (together with Thor/Guard/Vagrant files).

**Comment by m3hr** [comment]
Yeah I realized I was using an old version of spacemacs. I added Podfile support for the 4 OS X users that use Cocoapods and emacs :-) lol

**Comment by bru** [comment]
@m3hr actually that's a good point, I also realised we're missing a couple other file types (e.g. `.rabl` and `Berksfile`). I'm going to add that now in a PR
