### ISSUE TITLE
Magit: "eval-buffer: Cannot open load file: no such file or directory, magit-autorevert"

### ISSUE THREAD

**Issue by microamp** [syl20bnr/spacemacs#4585]
With the latest updates, none of the Magit commands works anymore in my Emacs reporting the following error message:
```
eval-buffer: Cannot open load file: no such file or directory, magit-autorevert
```

**Comment by syohex** [comment]
Please see https://github.com/milkypostman/melpa/issues/3488

**Comment by microamp** [comment]
Thanks for the info, @syohex

**Comment by malchmih** [comment]
Is there a workaround for this?

**Comment by syohex** [comment]
Download the file and put it under load-path directory.

**Comment by malchmih** [comment]
Thanks :smile:

**Comment by syohex** [comment]
MELPA PR has been merged. This issue will be fixed when magit on MELPA is updated.

**Comment by oskarizu** [comment]
I've just updated package magit in spacemacs and can confirm that the issue is solved for me, `magit` is working fine again, thanks!

**Comment by StreakyCobra** [comment]
:+1: Closing as fixed upstream

**Comment by microamp** [comment]
Awesome, thanks guys :+1:
