### ISSUE TITLE
Conflicting window number assignment for neotree and grizzl

### ISSUE THREAD

**Issue by chrisbarrett** [syl20bnr/spacemacs#459]
I use [grizzl][] as the completion system for projectile. When neotree is open and I call a command that reads with completions (e.g. `projectile-find-file`) I get the following error:

```
Number 0 assigned to two buffers (#<window 58 on  *NeoTree*> and #<window 4 on  *Minibuf-1*>) [3 times]
```

[grizzl]: https://github.com/grizzl/grizzl

**Comment by syl20bnr** [comment]
It is not related to `grizzl`, I guess that any popup will generate this message. Does it happen at every keystroke or only when the popup... popups ?

This error is generated by the code to force the number 0 on the `neotree` window. While annoying it should not have consequences. I can see that the `minibuffer` is assigned to 0 which is not expected, I may have to fix this in `window-numbering.el`.

**Comment by chrisbarrett** [comment]
In grizzl, it happens every keystroke that changes the completion list, so I expect a new popup is being generated with each keypress.

**Comment by syl20bnr** [comment]
oh ok, I'll give it a look, the fact that minibuffer has a number assigned to it is weird.
