### ISSUE TITLE
'spacemacs/toggle-line-numbers-on' under  'user-config' not working since v0.105.0

### ISSUE THREAD

**Issue by kingFighter** [syl20bnr/spacemacs#4594]
Put `(spacemacs/toggle-line-numbers-on) ` under `dotspacemacs/user-config` not working since v0.105.0.(v0.104.8 work but v0.105.0 not). No error in `*Message*` and it says `line-numbers enabled` 

Though I can make it work by `M-X spacemacs/toggle-line-numbers(-on) / linum-mode` or put ` (global-linum-mode)` under `dotspacemacs/user-config`, I wonder if it is a bug.

My env:
OS: `ubuntu 14.04`
emacs: `25.1.50.2`
I tried `v0.105.X` including `v0.105.8` (not work) and `v0.104.X`  including  `v0.104.8` (work)

**Comment by StreakyCobra** [comment]
There is now a `dotspacemacs-line-numbers` setting in the `.spacemacs` that can be set to `t` to activate it, or to `'relative` for relative line numbers. You should use this instead. If it is not in your `.spacemacs` yet, you have to synchronize it with the template (`SPC f e D` may be helpful).

**Comment by kingFighter** [comment]
Really thanks, it works.

Will other `toggles` stop working just like `line-numbers`?

**Comment by StreakyCobra** [comment]
No no, it's case by case. It's just there was a lot of problems for users to toggle globally line numbers and relative line numbers, so we added a variable for this :-)

**Comment by StreakyCobra** [comment]
If this is fine for you this issue can probably be closed :+1:

**Comment by xahon** [comment]
I have the same issue.  
Here is my `dotspacemacs/user-config` defun

```Lisp
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
  (custom-set-variables
   '(initial-frame-alist (quote ((fullscreen . maximized)))))

  (set-face-attribute 'default nil :font "Inconsolata-10")
  (setq-default dotspacemacs-line-numbers t)
  )
```
I also tried to comment that definition in `(defun dotspacemacs/layers`

**Comment by chongchonghe** [comment]
> I have the same issue.
> Here is my `dotspacemacs/user-config` defun
> 
> ```lisp
> (defun dotspacemacs/user-config ()
>   "Configuration function for user code.
> This function is called at the very end of Spacemacs initialization after
> layers configuration.
> This is the place where most of your configurations should be done. Unless it is
> explicitly specified that a variable should be set before a package is loaded,
> you should place your code here."
>   (custom-set-variables
>    '(initial-frame-alist (quote ((fullscreen . maximized)))))
> 
>   (set-face-attribute 'default nil :font "Inconsolata-10")
>   (setq-default dotspacemacs-line-numbers t)
>   )
> ```
> 
> I also tried to comment that definition in `(defun dotspacemacs/layers`

I had the same issue. Putting `(setq-default dotspacemacs-line-numbers t)` in user-config didn't work. Moving it into user-init works.
