### ISSUE TITLE
On OSX flycheck messages show up on the monitor where the cursor is

### ISSUE THREAD

**Issue by carloscheddar** [syl20bnr/spacemacs#4595]
Using OSX `flycheck` popup messages for errors and warnings show up on the `monitor` that has the `cursor` instead of only displaying on top of the spacemacs window.

**Comment by StreakyCobra** [comment]
What's your emacs version? 

In Emacs < 24.4 this is a known behaviour. Either update Emacs or add `flycheck-pos-tip` to the `dotspacemacs-excluded-packages` list :-)

**Comment by StreakyCobra** [comment]
Reference: https://github.com/flycheck/flycheck-pos-tip/issues/6#issuecomment-156394030

**Comment by carloscheddar** [comment]
Thanks I'll check that out but my version is 24.5.1.

**Comment by StreakyCobra** [comment]
Weird. It's known that the tooltip goes over all windows, but there is normally a hook that disable the tooltip when the focus is exited from Emacs.

Or maybe are you in a situation where Spacemacs has the focus and another window is overlapping it on a side?

**Comment by carloscheddar** [comment]
In my case Emacs has the focus but the cursor is on the second monitor which makes the tooltip show up where the cursor is located. When emacs loses focus the tooltip disappears so that's working correctly.

**Comment by StreakyCobra** [comment]
Oh, the mouse cursor, not the emacs cursor :-) Ok I got it.

This is probably an upstream issue, but let's ask @lunaryorn to be sure.

The package providing the tooltip is `flycheck-pos-tip`, but it's using another library (`pos-tip`) to show the tooltips, so I suppose it should be reported there.

**Comment by lunaryorn** [comment]
It sure sounds like an upstream issue.  I'd appreciate if you could report this issue to `flycheck-pos-tip`, lest I forget about it.

Thank you very much

**Comment by carloscheddar** [comment]
Oh my bad I should've been more specific. Thanks for the help, I'll report there.

**Comment by StreakyCobra** [comment]
@carloscheddar When you have done this, please put a link back here :-)

**Comment by carloscheddar** [comment]
@StreakyCobra Here it is https://github.com/flycheck/flycheck-pos-tip/issues/15
