### ISSUE TITLE
Request for yet another user initialization function

### ISSUE THREAD

**Issue by zot** [syl20bnr/spacemacs#4597]
**REQUEST:** Would you please call a new user init function like dotspacemacs/user-packages-loaded or something, or maybe call dotspacemacs/user-config right after the call to configuration-layer//load-packages?

**REASON:** I just had to add a patch to flycheck because of a loading problem that was hanging Emacs when it turned flycheck-mode on for a buffer.  Putting the patch into user-init was too early because require couldn't find flycheck.el and putting it into user-config was too late because the desktop had already been loaded, flycheck turned on, and Emacs completely hung.  My solution was to advise configuration-layer//load-packages like this in my user-init function:

```
(defun dotspacemacs/user-init ()
  "Initialization function for user code.
It is called immediately after `dotspacemacs/init'.  You are free to put almost any
user code here.  The exception is org related code, which should be placed in
`dotspacemacs/user-config'."
  (advice-add 'configuration-layer//load-packages :after
              (lambda (&rest args)
                (dotspacemacs/patch-flycheck))))
```

Adding advice to configuration-layer/sync did not work, by the way.

**Comment by zot** [comment]
Actually, the problem was that I needed the patch before the initial desktop was restored, so the init function could be called right before that.

**Comment by syl20bnr** [comment]
Is there any desktop hook that you could use ?

**Comment by zot** [comment]
There may be, but doesn't it make sense to call a user function right after packages have loaded?  There may be many other cases like this that aren't desktop.
