### ISSUE TITLE
evil-mode typing 'fd' in quick succession takes me out of insert mode

### ISSUE THREAD

**Issue by logorrhea** [syl20bnr/spacemacs#4598]
While in insert mode in evil-mode, typing the characters `fd` in quick succession undoes the typing and takes me out of insert mode.

Information for reproduction:
- Using `spacemacs` standard (not `spacemacs-base`)
- Modes: `evil-mode`, seems to affect all modes that I've tried
- Spacemacs version: `0.105.8`
- Emacs version: `24.4.1`

**Comment by nixmaniack** [comment]
That's the feature of spacemacs to enter normal state. Check [this](http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline78). You can customize the bindings as stated there.
If you don't like this feature, you can exclude `evil-escape` by adding it to `dotspacemacs-excluded-packages` in `~/.spacemacs`

**Comment by logorrhea** [comment]
Oh, strange. Thanks @nixmaniack
