### ISSUE TITLE
Consider adding support for evil-anzu

### ISSUE THREAD

**Issue by legendre6891** [syl20bnr/spacemacs#460]
A new package that enables `anzu` for `evil-mode` popped up. 

https://github.com/syohex/emacs-evil-anzu

Could it be considered to be added :)?

EDIT: Ah I see that it's added, but I overlooked that because I have the following error when I use `n` or `N`:

`spacemacs/anzu-evil-search: Wrong number of arguments: (1 . 1), 0`

**Comment by syl20bnr** [comment]
I already checked it and it seems more intrusive than the Anzu integration in spacemacs (ie. `evil-anzu` uses a set of hooks).
I'll take a second look at it.
Thank you!

**Comment by syl20bnr** [comment]
@legendre6891 update both spacemacs and `anzu` package and it should be ok.

**Comment by syl20bnr** [comment]
Let's keep this issue opened because ideally I would like to replace the `anzu` integration of spacemacs for evil with `evil-anzu`. I need to look more closely at it.
