### ISSUE TITLE
Is there a way to see a list of updated packages?

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#4602]
When I update the packages, all I get is a very quickly updating line in the log in the `*spacemacs*` buffer which shows each package name briefly:

```
--> performing backup of package(s) to update...
--> preparing update of package which-key... [48/48]
--> 48 package(s) to be updated.
```

Is there a way to see a list like this instead?

```
--> performing backup of package(s) to update...
--> preparing update of package magit... [1/3]
--> preparing update of package evil-mc... [2/3]
--> preparing update of package which-key... [3/3]
--> 3 package(s) to be updated.
```

I would prefer the same for the installing process after restarting Emacs.

**Comment by TheBB** [comment]
We already have this, no? Are you sure you tried on the latest version?

**Comment by 3rd3** [comment]
Was it just added in 0.105.8? Then it was a coincidence, or I've always missed this before:

    --> Found 2 package(s) to update:
    magit
    haskell-mode

**Comment by TheBB** [comment]
There's not really a whole lot more we can write there. Most of the stuff that happens in this loop is stock Emacs package behaviour.

**Comment by 3rd3** [comment]
Is the `[1/3]` output which overrides the line yours?

**Comment by TheBB** [comment]
Which? I'm not sure I know what you're talking about.

**Comment by 3rd3** [comment]
Is this output produced by Emacs or by Spacemacs?

    --> installing package: haskell-mode@haskell... [2/2]

**Comment by TheBB** [comment]
By Spacemacs.

**Comment by 3rd3** [comment]
It would be convenient to have a list in the logs instead of a line that gets overwritten and ends at `[n/n]`, because it could serve as a change log up the package updating:

--> installing package: magit... [1/2]
--> installing package: haskell-mode@haskell... [2/2]

**Comment by TheBB** [comment]
Yeah, okay, we can do that.

**Comment by nixmaniack** [comment]
:+1: for making the package installation log verbose. Also I think it should go in `*Messages*` and keep it the way it is in spacehome.

**Comment by 3rd3** [comment]
This feature is now present when fetching the updates (which is great) but not on start-up when the packages are installed.

**Comment by duianto** [comment]
Agreed, it would be useful to see a summary list of which packages were updated.

Currently there are at least two ways to find out which packages were updated:
- Check in the messages buffer `SPC b m`, but there are multiple installation lines for each package.
Here's an example when I removed the `ace-jump-helm-line` package and restarted:
```
(Spacemacs) --> installing package: ace-jump-helm-line@helm... [1/1]
Contacting host: melpa.org:443 [2 times]
Generating autoloads for ace-jump-helm-line.el...done
Wrote c:/Users/username/.emacs.d/elpa/26.3/develop/ace-jump-helm-line-20160918.1836/ace-jump-helm-line-autoloads.el [2 times]
Checking c:/Users/username/.emacs.d/elpa/26.3/develop/ace-jump-helm-line-20160918.1836... [3 times]
Compiling c:/Users/username/.emacs.d/elpa/26.3/develop/ace-jump-helm-line-20160918.1836/ace-jump-helm-line.el...done
Wrote c:/Users/username/.emacs.d/elpa/26.3/develop/ace-jump-helm-line-20160918.1836/ace-jump-helm-line.elc
Checking c:/Users/username/.emacs.d/elpa/26.3/develop/ace-jump-helm-line-20160918.1836...
Done (Total of 1 file compiled, 2 skipped)
```
Anyone that knows about HELM Swoop `SPC s s`, can filter the results by searching for:
`installing package`

But others that don't know about HELM swoop will have to scroll through the messages buffer to find out which packages were installed.

- Check the rollback directory:
`c:/Users/username/.emacs.d/.cache/.rollback/26.3/develop/20-03-13_11.35.35/`
my latest update shows:
```
  c:/Users/username/.emacs.d/.cache/.rollback/26.3/develop/20-03-13_11.35.35:
  total used in directory 89 available 37334056
  drwxrwxrwx  1 username None  4096 03-13 11:35 ..
  drwxrwxrwx  1 username None  4096 03-13 11:35 .
  drwxrwxrwx  1 username None 32768 02-09 14:48 cider-20200208.809
  drwxrwxrwx  1 username None  4096 02-28 08:36 doom-modeline-20200227.1432
  drwxrwxrwx  1 username None 40960 03-07 17:53 magit-20200307.319
  drwxrwxrwx  1 username None  4096 02-26 20:11 magit-section-20200226.1251
  -rw-rw-rw-  1 username None   200 03-13 11:35 rollback-info
```
But it requires digging through the file system to get there.

---

Another issue is that the installing package lines on the home buffer are temporary. They disappear when the home buffer is redrawn. An example where this happens automatically, is when the variable:
`dotspacemacs-maximized-at-startup` is set to: `t`

Then at least in Windows, the home buffer is left aligned while the packages are installing and the messages are shown, but when it's done, then the home buffer is redrawn which centers it and the recent files, projects and bookmarks are inserted.

**Comment by kommen** [comment]
Maybe related: I actually want to know which packages are outdated **before** I to start updating. This seemed to find them all:

```elisp
(configuration-layer//get-packages-to-update 
 (configuration-layer//filter-distant-packages
  configuration-layer--used-packages t))
```

**Comment by duianto** [comment]
Here's a first pass:
```elisp
  (defun spacemacs/list-packages-with-updates ()
    (interactive)
    (let ((packages-with-updates
           (configuration-layer//get-packages-to-update
            (configuration-layer//filter-distant-packages
             configuration-layer--used-packages t))))
      (if packages-with-updates
          (message "Packages with updates:\n%s"
                   packages-with-updates)
        (message "All packages are up to date."))))
  (global-set-key (kbd "<f8>") 'spacemacs/list-packages-with-updates)
```
It first said:
>All packages are up to date.

After replacing the current versions of: `evil-collection` and `magit`
with the previous versions from the rollback directory.
And restarting Spacemacs.

Now `F8` shows:
>Packages with updates:
(evil-collection magit)
