### ISSUE TITLE
Cannot update spacemacs

### ISSUE THREAD

**Issue by mastokley** [syl20bnr/spacemacs#4603]
Hello,

I've been unable to update Spacemacs. Here's the error I'm given:

"Your Emacs directory is not clean.
git status:
?? notes"

I can't seem to find any existing discussion of this error message. Can anyone point me in the right direction?

I'm currently on 0.105.0.

I appreciate any help/hints you may have!

-Michael

**Comment by justbur** [comment]
Did you try `git status` on the command line in your .emacs.d directory?

**Comment by mastokley** [comment]
Justbur, thank you! That did it.
