### ISSUE TITLE
define-key stopped working correctly in new version

### ISSUE THREAD

**Issue by morgado-jb** [syl20bnr/spacemacs#4611]
You can no longer `define-key` correctly.

The code in `user-config`:
```
(define-key evil-normal-state-map (kbd "C-+") 'spacemacs/evil-numbers-increase)
```

Doesn't work anymore in the new version of spacemacs.

**Comment by StreakyCobra** [comment]
This exact line in `user-config` works here.

**Comment by TheBB** [comment]
Since we have been unable to reproduce I'm closing this now. The cited line should certainly work.
