### ISSUE TITLE
Add way to stop spacemacs from updating on startup

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#4612]
Sometimes I have no internet connection at all or am in a very slow internet connection.

Spacemacs will always try for a while to update itself on startup.

AFAIK there is no way to stop this from happening.

It would be nice if this process could be easily stopped, and the instructions to do so where clearly visible when the update starts and while the update is proceeding.

**Comment by mayersj1** [comment]
If not using 'develop', set

~~~
dotspacemacs-check-for-update nil
~~~

in your .spacemacs file

**Comment by TinySong** [comment]
@gnzlbg   Strongly suggest you use the "develop" branch

**Comment by gnzlbg** [comment]
The thing is in general I like everything to be updated automatically on
start up, it is just in some occasions that I don't, like when.I don't have
an Internet connection or the connection is very slow.

If I switch to develop I would have to opt in to updates always right?

**Comment by syl20bnr** [comment]
I can provide a command line argument and an environment variable to disable it so you'll be able to make a script or just set the environment variable. Would this be ok ?

**Comment by StreakyCobra** [comment]
A `--offline` flag would be nice :-)

**Comment by tidux** [comment]
I have `spacemacs-check-for-update nil` set in `~/.spacemacs` and I still get the DNS related stalls on startup when I attempt to start spacemacs without a network connection.  An `--offline` flag should disable ALL attempts to contact the network before the editor is fully started.

**Comment by JAremko** [comment]
I run Spacemacs inside a docker container. It means that all the updates will be lost after restarts.  
:+1:

**Comment by MiaoDX** [comment]
Hi,
I am rather confused since there seems no answer or response at all. So, how can we just skip the refreshing phase currently?

**Comment by MiaoDX** [comment]
Oh!
Sorry, maybe I used it the wrong way, we can `emacs` once and then use `emacsclient` to open files/directories instantly.
Will close it.
