### ISSUE TITLE
git-commit find-file-hook broken

### ISSUE THREAD

**Issue by bgamari** [syl20bnr/spacemacs#4615]
For quite some time I have noticed that magit's commit functionality does not work. Finally tonight I broke down and did some digging.

# The problem
For instance, take this example session,

 1. Start emacs
 2. Open a file, make and edit, save with `:w`
 3. Enter `magit-status` with `Space g s`
 4. Stage the change with `s`
 5. Commit with `c c`
 6. Enter a commit message
 7. Commit with `C-c C-c`, observe error `C-c C-c is undefined`
 8. Alright, instead try `, c`. observe error `No previous search`

Hmm, odd. After speaking with some other users, I realized that the major mode of the commit message buffer is `fundamental-mode` whereas it should be `text-mode` with a `with-editor-mode` minor mode. If I manually run `M-x with-editor-mode` after entering the commit message buffer things seem to work as expected.

# More hunting
It appears that `git-commit.el` is responsible for entering `with-editor-mode`, namely `git-commit-setup`. This function is called by `git-commit-setup-check-buffer` when an appropriate buffer name is seen. After adding some tracing, I concluded that `git-commit-setup-check-buffer` is not being called when the commit message buffer is created. `git-commit-setup-check-buffer` is supposed to be registered as a `find-file-hook` hook in the `global-git-commit-mode` minor mode initializer.

Further tracing revealed that the problem is in the registration of the hook. Namely, if I replace the line,
```lisp
(add-hook 'find-file-hook 'git-commit-setup-check-buffer)
```
in the `global-git-commit-mode` initializer with,
```lisp
(add-hook 'find-file-hook (lambda () (git-commit-setup-check-buffer)))
```
things seem to work.

Moreover, if I replace this line with,
```lisp
(add-hook 'find-file-hook 'git-commit-setup-check-buffer)
(message "added hook local=%s" find-file-hook)
(message "added hook global=%s (default-value 'find-file-hook))
```
in the initializer I find that the hook is added to the global `find-file-hook` list during initialization. However, if I `describe-variable` this list after initialization, I find that  `git-commit-setup-check-buffer` is no-where to be found.

This is all I know at the moment but my hypothesis is that someone is removing the hook (although I have no idea who).

**Comment by bgamari** [comment]
If I set a breakpoint inside the initializer (with `(debug)`), I see the following backtrace,
```
... [global-git-commit-mode custom-initialize-default debug add-hook find-file-hook git-commit-setup-check-buffer] 5 "\n\n(fn SYMBOL EXP)"](global-git-commit-mode (funcall (function #[0 "\300\207" [t] 1])))
  custom-declare-variable(global-git-commit-mode (funcall (function #[0 "\300\207" [t] 1])) "Non-nil if Global-Git-Commit mode is enabled.\nSee the command `global-git-commit-mode' for a description of this minor mode.\nSetting this variable directly does not take effect;\neither customize it (see the info node `Easy Customization')\nor call the function `global-git-commit-mode'." :set custom-set-minor-mode :initialize #[514 "\301\"\210\302 \210\205
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\306\307\310\311\312\313\314\315&\210\316\317\320\321\322DD\323\324\325\326\327\314\307\330\331&\207" [require dash log-edit ring server with-editor custom-declare-group git-commit nil "Edit Git commit messages." :prefix "git-commit-" :group tools custom-declare-variable global-git-commit-mode funcall function #[0 "\300\207" [t] 1] "Non-nil if Global-Git-Commit mode is enabled.\nSee the command `global-git-commit-mode' for a description of this minor mode.\nSetting this variable directly does not take effect;\neither customize it (see the info node `Easy Customization')\nor call the function `global-git-commit-mode'." :set custom-set-minor-mode :initialize #[514 "\301\"\210\302 \210\205
  require(git-commit)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312\313\314#\207" [require cl-lib dash with-editor git-commit magit-core magit-diff magit-apply magit-log format-spec package nil t] 4)
  autoload-do-load((autoload "magit" "Show the status of the current Git repository in a buffer.\nWith a prefix argument prompt for a repository to be shown.\nWith two prefix arguments prompt for an arbitrary directory.\nIf that directory isn't the root of an existing repository\nthen offer to initialize it as a new repository.\n\n(fn &optional DIRECTORY)" t nil) magit-status)
  command-execute(magit-status)
```
If I step out of each of these frames in succession, I find that `git-commit-setup-check-buffer` is removed from `find-file-hook` after stepping out into `require(git-commit)`.

**Comment by StreakyCobra** [comment]
Can you do `SPC h d s` and paste the result here?

**Comment by bgamari** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 25.1.50.1
- Spacemacs: 0.105.8
- Spacemacs branch: nil (rev. 8447005)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion syntax-checking latex notmuch python extra-langs c-c++ html javascript markdown git github emacs-lisp shell idris asciidoc rust purescript
                 (haskell :variables haskell-enable-ghc-mod-support nil))
```

**Comment by bgamari** [comment]
Note that this is not due to emacs-25 (which I use in order to work around an unrelated issue). The issue is also reproducible with emacs-24.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.8
- Spacemacs branch: nil (rev. 8447005)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion syntax-checking latex notmuch python extra-langs c-c++ html javascript markdown git github emacs-lisp shell idris asciidoc rust purescript
                 (haskell :variables haskell-enable-ghc-mod-support nil))
```

**Comment by StreakyCobra** [comment]
I just tried your reproduction step but I don't have this problem. Have you updated your packages recently?

**Comment by bgamari** [comment]
@StreakyCobra I updated tonight as well as several times in the past several months.

**Comment by StreakyCobra** [comment]
Ok, so I'm clueless then, sorry :pensive:

Some random idea you can try:
- Try with a fresh `.spacemacs` to see if it happens,
- Try to start with a completly fresh install (`.spacemacs` and `.emacs.d`), it will force reinstall and recompile of all packages, as it seems there is some bytecode involved.
- Try magit on a raw emacs (without spacemacs at all), to see if the problem com from spacemacs.

**Comment by bgamari** [comment]
Well, I am in fact a complete idiot. It was only after three hours of digging through `.emacs` that I noticed the
```
  (eval-after-load "git-commit" '(remove-hook 'find-file-hook 'git-commit-setup-check-buffer))
```
in my `.spacemacs`. I haven't the slightest idea what I was thinking when I wrote that.

Sorry for the noise!
