### ISSUE TITLE
Can't use R in babel

### ISSUE THREAD

**Issue by maxigit** [syl20bnr/spacemacs#4618]
I'm trying to use R and babel and I get the following error message : 

```
Error in dotspacemacs/user-config: Invalid function: org-babel-header-args-safe-fn
```

I only get this error message when I add `(R . t)` in the `orb-babel-do-load-languages` section. If I use python or ruby it works fine.

**Comment by tboby** [comment]
Are you sure you have git on your path?

**Comment by Andre0991** [comment]
Have a look at "Important Note" in the org layer docs, it might have to do with that too.

Basically, you have to wrap everything that is related to org in `  (with-eval-after-load 'org
 ...)`

**Comment by maxigit** [comment]
I suppose so. Everything but R works. Also I get spacemacs updates and
everything. But I can double check, how can I do that ?

**Comment by maxigit** [comment]
It is in the right section. I can get other language work (sql, python,
ruby etc ...). Only R causes this error ...

**Comment by maxigit** [comment]
I upgraded to 0.105.8 and updated all the packages and know it's workingi :-)

**Comment by maxigit** [comment]
I had the problem again (after upgrading to 0.105.9) the solution was to clear the `elpa` subdirectory.

**Comment by izahn** [comment]
This is an upstream bug in org-mode, see http://comments.gmane.org/gmane.emacs.orgmode/99644 and https://www.mail-archive.com/emacs-orgmode@gnu.org/msg98762.html. I think this issue should be closed and an upstream bug reported to org-mode.

**Comment by cpaulik** [comment]
Just had the same issue. Removing `ob-R.elc` fixed it.

**Comment by GregorySchwartz** [comment]
I have this issue and no amount of recompiling, restarting, removing org-* folders, or anything of that sort work. The only solution for me is to remove `R . t` from my configuration, but then I can't use R in babel. Is there some other solution?

**Comment by TheBB** [comment]
@GregorySchwartz The solution of @cpaulik should work. Remove *only* the file ob-R.elc.

I don't know for sure but I *assume* this happens because ob-R.elc is byte-compiled with the old version of org.

**Comment by GregorySchwartz** [comment]
@TheBB Unfortunately that solution did not work for me. I should mention that these techniques of removal did work a few weeks ago--this just started happening.

**Comment by izahn** [comment]
It usually happens in spacemacs that you end up with both org and org-plus-contrib package, making it harder to know where the broken `ob-R.elc` file is. Start package manager with `M-x paradox`, delete org and org-plus-contrib, then install only prg-plus-contrib. This usually works for me.

**Comment by syl20bnr** [comment]
@izahn do you think we can automate these steps in Spacemacs to have a clean org installation ?

Also moving org to `:step pre` would ensure that the above steps are executed prior to other packages.

**Comment by izahn** [comment]
I think the right thing is to fix this in upstream org-mode. I'm super busy now but I will look into it when I get a free moment.

**Comment by GregorySchwartz** [comment]
@izahn That solution using paradox worked. It must be because deleteing just org-plus-contrib or both org and that package repeated installs, but with your way it works.

**Comment by bmag** [comment]
Just adding two links to (slightly) better understand possible problem in compiling packages during installation of new packages:
- http://emacs.stackexchange.com/questions/13574/technical-considerations-for-package-maintainers-to-not-use-the-emacs-package-ma
- https://github.com/magit/magit/issues/2154
