### ISSUE TITLE
Error in ansi-term: "toe: couldn't open terminfo file 8859-10.map"

### ISSUE THREAD

**Issue by norcalli** [syl20bnr/spacemacs#4619]
I'm using zsh with purity prompt installed, and after generating the terminfo from the tic command `tic -o ~/.terminfo /Applications/Emacs.app/Contents/Resources/etc/e/eterm-color.ti`, it did fix some issues. However, I'm still getting an error, which I'm hoping could fix the rest:

![](https://i.gyazo.com/e8bda0871d76142d6e35e35d034b43d6.png)
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.8
- Spacemacs branch: master (rev. ef5a2ad)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-complete-with-key-sequence-delay 0.05)
 emacs-lisp spotify git markdown colors python html org
 (shell :variables shell-default-height 30 shell-default-term-shell "/usr/local/bin/zsh" shell-default-position 'bottom)
 syntax-checking)
```

**Comment by AbyChan** [comment]
hi,man, are you resolved?

**Comment by anicholson** [comment]
I'm having the same issue with a vanilla Emacs 24.5 running Prelude on OSX, so I doubt it's a spacemacs problem. @norcalli, did you end up getting anywhere with this?
