### ISSUE TITLE
auto-complete popup text not properly aligned

### ISSUE THREAD

**Issue by landaire** [syl20bnr/spacemacs#4624]
In the rust major mode I don't have proper alignment between the member/function name and type. For example:

<img width="352" alt="screen shot 2016-01-15 at 12 14 17" src="https://cloud.githubusercontent.com/assets/1313522/12364239/5ac996d4-bb82-11e5-88d2-e36dc8414a53.png">

These should be showing up as they do [here](https://github.com/racer-rust/emacs-racer). I don't think it's an issue with my theme as I get the same result for `spacemacs-dark`.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.6
- Spacemacs branch: develop (rev. 4be19ef)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking version-control d go rust elixir swift yaml latex markdown osx spacemacs-layouts)
```

**Comment by bmag** [comment]
The alignment is controlled by the variable `company-tooltip-align-annotations`, which is nil by default.
```elisp
(setq company-tooltip-align-annotations t)
```

**Comment by landaire** [comment]
That did the trick! Thanks @bmag. Is there any reason why that's nil by default, or is there any downsides to setting it to true?

**Comment by bmag** [comment]
I've had it set like this for several months, didn't notice any problem, and I don't know why it's nil by default. Why don't you make a PR, then we can discuss the change there?

**Comment by fbergroth** [comment]
This should be fixed by #4516, try the develop branch.

**Comment by bmag** [comment]
@fbergroth good to see that, I wasn't aware of it (I don't use Rust). But, why set `company-tooltip-align-annotations` locally and not globally? Isn't it weird that in all languages the annotations are on the left, and only in Rust they are on the right?

**Comment by fbergroth** [comment]
I guess it depends on what info the backend presents along with the candidates. For some backends it (subjectively) looks better to align them, for some it doesn't. It's probably personal preference in most cases.

**Comment by landaire** [comment]
@fbergoth great, works with the latest develop without explicitly setting it (swear I updated earlier today but must not have restarted spacemacs). Thanks to both of you for the help!
