### ISSUE TITLE
diff-hl not working on the terminal

### ISSUE THREAD

**Issue by morgado-jb** [syl20bnr/spacemacs#4626]
diff-hl doesn't work on the terminal

Putting in `user-config()`:
```
'(version-control :variables
                  version-control-diff-tool 'diff-hl
                  version-control-global-margin t)
```

Doesn't show anything.

When saving the buffer some symbols appear on the left side messing the line numbers but that's it.

**Comment by robbyoconnor** [comment]
Shouldn't that be in your `dotspacemacs/layers` function ;)

**Comment by morgado-jb** [comment]
Yes, you are right.

I found a bug with that tough that I had fixed in my "pure" Emacs configuration.

When in TTY having the diff-hl on the rigth margin only works for the rightmost window.

This code must be added to fix that:
```
  (when (not (display-graphic-p))
    (add-hook 'window-configuration-change-hook
              (lambda ()
                (set-window-margins (car (get-buffer-window-list (current-buffer) nil t)) 1 2))))
```

But I'm not sure how to contribute that, if I should put it in the version control layer and submit it or send it to some other place.

**Comment by robbyoconnor** [comment]
probably in the version-control layer -- I'm not sure @ralesi would know more than me

**Comment by morgado-jb** [comment]
Ok, thank you :) I'll try it to the version-control layer and then if that doesn't get accepted try something else.

**Comment by robbyoconnor** [comment]
Do it against `develop` please
