### ISSUE TITLE
Many things freeze when auto-completion layer is enabled

### ISSUE THREAD

**Issue by Zenith-One** [syl20bnr/spacemacs#4629]
If I open spacemacs in a folder whose length is 15 characters or longer, and that folder has subfolders, and I have auto-completion enabled, neotree freezes on open.

Also, SPC B B, SPC P F, and several other things cause spacemacs to become unresponsive. Only when auto-completion is enabled, and the root directory's name is 15 characters or more.

I'm on Windows 10, running emacs 24.5.1 built for 64-bit windows. I'm running the latest version of spacemacs (I installed it today, Jan 15).

**Comment by Zenith-One** [comment]
Appears to be loosely related to having some ligatures set up as well. Probably not auto-completion's fault. Closing

**Comment by stormpat** [comment]
Im having the same exp. Freezes with 100% cpu for 10-30 secs, sometimes longer. Seems to happen very often (for me) when editing html (html-mode). It seems connected to auto-complete, but im not 100% sure...
