### ISSUE TITLE
The `~` signaling the end of buffer are present in GUI but not in TUI

### ISSUE THREAD

**Issue by viccuad** [syl20bnr/spacemacs#4635]
well, that's it.

**Comment by TheBB** [comment]
I don't think there's anything to do about this. The tilde package uses images in the fringe, and in the terminal you can't display images.

**Comment by viccuad** [comment]
We have the [vim-empty-lines-mode](https://github.com/syl20bnr/spacemacs/tree/master/layers/+vim/vim-empty-lines), that uses chars and follows vim behaviour.

Closing this.

**Comment by TheBB** [comment]
Yes, thanks. I was searching for tilde and I couldn't find it.

**Comment by louwers** [comment]
Does it work for you?

**Comment by viccuad** [comment]
@louwers yep, it works for me.
