### ISSUE TITLE
Windows instructions unclear (possibly don't work)

### ISSUE THREAD

**Issue by jjoedouglas** [syl20bnr/spacemacs#4638]
Installed emacs from here: http://sourceforge.net/projects/emacsbinw64/files/release/
I'm able to start emacs up.

However when I run `emacs --insecure`, the emacs window pops up with an error reading "Unknown options --insecure".  No downloading of anything takes place and it looks like I'm still in regular old emacs.

This might be an issue with the emacs build linked in the instructions, but this is just guesswork on my part.  I've tried whatever version comes from `cinst emacs` but get the same exact issue.

**Comment by jjoedouglas** [comment]
Whoops.  Looks like somehow the git clone failed earlier on and I hadn't noticed.  Sorry for the noise.

**Comment by pradhyu** [comment]
Alternative way to trigger the spacemacs installation after cloning. 
M-x load-file 
~/.emacs.d/init.el

**Comment by DoSeek** [comment]
> Alternative way to trigger the spacemacs installation after cloning.
> M-x load-file
> ~/.emacs.d/init.el

You are right, thks!
