### ISSUE TITLE
Private snippets are only loaded after manually executing `yas-reload-all` when on Inf-Ruby mode

### ISSUE THREAD

**Issue by victorfonsec4** [syl20bnr/spacemacs#4639]
This is very similar to #1830, but it's only happening when on `Inf-Ruby mode` on the buffer created by `projectile-rails-console`, it's happening both on master and on develop branches.

**Comment by victorfonsec4** [comment]
Sorry,  I think this is not a bug but intended behavior. 
`Inf-Ruby mode` does not derive from `prog-mode`, `markdown-mode` or `org-mode` so if I want to enable `yas-minor-mode` on it automatically I should use something like:
`(spacemacs/add-to-hooks 'spacemacs/load-yasnippet  '(inf-ruby-mode-hook) ` 
I guess this makes sense since yas is disabled for console type of buffers and `projectile-rails-console` is one.
Guess I can close this?

**Comment by robbyoconnor** [comment]
Yeah...why would you want it for a console buffer?

**Comment by victorfonsec4** [comment]
Just a dumb way to create aliases, closing it now.

**Comment by robbyoconnor** [comment]
uh you want it for ruby-mode -- not console buffers...it's kinda a really stupid thing to even want
