### ISSUE TITLE
Spacemacs isn't actually an Emacs Distribution, let's fix those references.

### ISSUE THREAD

**Issue by jasonm23** [syl20bnr/spacemacs#4640]
I think there are signs that suggest some people are taking the wording of the Spacemacs blurb a bit too literally.  To avoid unwanted noise and pointless discussions in various places around the web, I think it's important to remove mentions of Spacemacs as an **"Emacs Distribution"**.

I'm not sure why this was ever added, and I don't want to be inflammatory and make speculations as to why.

Please remove these references and replace them with "Community Driven Configuration" or something equally legitimate and valid.

**Comment by CestDiego** [comment]
I greped the project and nowhere is there the verbatim reference to `Emacs Distribution`. There is the concept of distribution as of `spacemacs` or `spacemacs-base` but never of Emacs Distribution. If you can find the line in which this is cited, please do and then it'll be removed.

**Comment by jasonm23** [comment]
- Project description on Github.

I don't think it's greppable

**Comment by robbyoconnor** [comment]
@syl20bnr is one of the only people who can change that -- I think @TheBB and @StreakyCobra  can as well...

**Comment by StreakyCobra** [comment]
Nope, only @syl20bnr can, and it should be it choice to change it anyway :-)

**Comment by d12frosted** [comment]
Actually I agree on that. And I also don't know where confusion came from. For example, [Prelude](https://github.com/bbatsov/prelude) also states that it's Emacs distribution. This might be the right word, but looks like somehow for some users (and mostly probably for non-English speakers) 'distribution' sounds more like a fork or something alike. Oh and also new citizens of Emacs world also can be easily confused. Spacemacs is Emacs + Vim. Indeed a brand new ~~fork~~ distribution.

There was some discussion on https://github.com/syl20bnr/spacemacs/pull/6085 regarding this issue.

**Comment by jasonm23** [comment]
The perception of confusion / lack of it is subjective of course.  I don't think it's too much of a stretch to assume it's pretty confusing to someone, relatively inexperienced, coming fresh to Spacemacs.

After a reasonable amount of time anyone will understand what Spacemacs is, and is not.

This issue was opened with the single goal of removing any obstacles to this understanding.
