### ISSUE TITLE
Required package `request-0.1.0' is unavailable

### ISSUE THREAD

**Issue by daleione** [syl20bnr/spacemacs#4642]
Warning (emacs): Unable to activate package `helm-gitignore'.
Required package `request-0.1.0' is unavailable

**Comment by zentorwie** [comment]
You can install `request` via paradox.

**Comment by erwan** [comment]
I'm having the same error. I'm fine installing a package manually, but is it normal? Shouldn't spacemacs have its dependencies automatically installed?

**Comment by robbyoconnor** [comment]
Melpa handles this

**Comment by Linuus** [comment]
I also have this issue. Each time I restart spacemacs it goes and try to install the package, can't find it and shows the error. A bit annoying as it slows down the startup time quite a bit :)

```
Warning (emacs): Unable to activate package `helm-gitignore'.
Required package `request-0.1.0' is unavailable
```

**Comment by gguimaraesbr** [comment]
As mentioned in #4609, removing `elpa/` and restarting spacemacs solved the problem

**Comment by StreakyCobra** [comment]
@daleione @erwan @Linuus Can you try what @gguimaraesbr suggested and report here if it works?

**Comment by erwan** [comment]
@StreakyCobra yes, that fixed it for me

**Comment by robbyoconnor** [comment]
Close this issue then @erwan

**Comment by Linuus** [comment]
Yes, it worked for me as well. Thanks.

**Comment by robbyoconnor** [comment]
Whenever you have issues like this, typically nuking `elpa/` will resolve the problem, sometimes not...but typically it will.

**Comment by erwan** [comment]
@robbyoconnor I don't have the rights to close it, I didn't open it

**Comment by robbyoconnor** [comment]
@daleione close it ;)

**Comment by TheBB** [comment]
Closing due to popular request. :-)

**Comment by alexanderkjeldaas** [comment]
Should nuking `~/.emacs.d/elpa` be something spacemacs can do for me, since this is "what people do"?

**Comment by StreakyCobra** [comment]
Nope it's not wanted. Deleting the `elpa` folder is not a needed step in the normal workflow of Spacemacs. It can be tried in case of bugs though.

**Comment by rihbyne** [comment]
I faced the similar issue. I took backup of `~/.emacs/elpa` and restarted emacs. It took off from there and now compiling packages as I updated package index previously.

**Comment by cpjolicoeur** [comment]
you dont need to nuke all of elpa just `.emacs.d/elpa/helm-gitigore`

**Comment by panagiotious** [comment]
Downloading all packages takes more than 5 minutes for me; I assume that might be the case for anyone working with three or four programming languages and enables themes! I would rather not having to nuke `elpa` quite often apparently.

**Comment by Softsapiens** [comment]
For me only works to nuke all of elpa.
@cpjolicoeur only heml-gitigore was not enough   :-(
Thanks!

**Comment by 3rd3** [comment]
rm -rf $HOME/.emacs.d/elpa/helm-gitignore*

For the lazy.

**Comment by stephenway** [comment]
Removing helm-gitignore directoried from elpa doesn't fix it for me.

**Comment by 3rd3** [comment]
@stephenway Try `rm -rf $HOME/.emacs.d/elpa` and restart as other people have suggested.

**Comment by stephenway** [comment]
@3rd3 That did the trick, thanks!

**Comment by aBathologist** [comment]
I tried starting up Emacs without an internet connection, thus without the luxury of needlessly downloading ~50mbs of packages I already had, and Spacemacs was basically broken: I couldn't do `space f f` to find files, let alone any other key sequences. I am deeply grateful for this beautiful tool, but if reports of breaking bug are closed on the basis of a hacky workaround like nuking one's entire library of installed packages, I don't know that I can trust my workflow to the reliability and stability of the software. If there's not enough person-power to fix the issue now, that's totally understandable, and I'm not saying any user is entitled to quick fixes. But I do worry that hiding breaking bugs because of a pretty horrible workaround is a bad practice for the culture around this beautiful collection of software.... I hope I don't seem out of line here....

**Comment by agrafix** [comment]
I also run into this issue frequently. This always happens after upgrading packages. Is there anything I can to to prevent this?

**Comment by bhilburn** [comment]
I also run into this pretty regularly with updates. Blowing away the `helm-gitignore-*` elpa directory does the trick, but it is a bit obnoxious.

**Comment by sunlightlj** [comment]
1. Start spaceemacs
1. : list-packages
1. search&install "request" (i x)
1. restart emacs (SPC feR)

Note: check the file ~/.emacs.d/elpa/helm-gitignore-20150517.2056 for more infomation
