### ISSUE TITLE
Snippet placeholders won't be replaced in Orgmode

### ISSUE THREAD

**Issue by yejianye** [syl20bnr/spacemacs#4643]
To reproduce, try entering 'code_' and expand that snippet. Here is a screencast for the issue
![placeholder issue](http://g.recordit.co/dkmeWMifa4.gif)

It seems the issue only happens in orgmode not other major modes.

**Comment by Andre0991** [comment]
Yeah, I had the same problem today. 

It's an upstream bug. 

Have a look at Yasnippet issues.

**Comment by StreakyCobra** [comment]
If someone can put a link here to the upstream issue :-)

**Comment by Andre0991** [comment]
Here's it: https://github.com/capitaomorte/yasnippet/issues/644

**Comment by StreakyCobra** [comment]
Thanks :+1: @Andre0991

**Comment by duerrp** [comment]
This seems to be fixed upstream and (at least in my case) it works now in spacemacs.
