### ISSUE TITLE
orgmode H and L mapping should be removed

### ISSUE THREAD

**Issue by maxigit** [syl20bnr/spacemacs#4645]
In orgmode H and L are mapped to start and end of line.
This conflict with normal vim behavior (and therefore other mode) where H and L go at the top and bottom of the page.
Moreover, these mapping are unnecessary as the same can already by achieved with ^,0 and $.
Unless I'm missing something ...

**Comment by tboby** [comment]
Perhaps it's a frequency thing? I find it's *really* important to use org-beginning-of-line and org-end-of-line before code motion/structure editing in orgmode. $ and ^ aren't particularly easy to use and I go to beginning and end of line far more than beginning and end of document.

**Comment by maxigit** [comment]
Why do you go at the beginning and line for ? If it's to edit the line,
then just use `A` and `I`.
Anyway, I'm sure you have your reason, I just think having that as a
default is a not good thing as it breaks existing key-binding.
If you really need those mapping can't you just set them in your
configuration file ?

**Comment by tboby** [comment]
I didn't set the bindings, I'm just speculating.

Because org end of line and visual character end of line are not the same. In evil-org-mode it's probably more important that org-mode works properly with default keybinds.

**Comment by maxigit** [comment]
I understand that the begining and end of line needs to be tweaked for
orgmode which is why   ^ and $ are already set to `org-beginning-of-line`
and `org-end-of-line`. I don't think there is a need to double it up to H
and L.
(If people feel the need to map H and L to ^ and $ then they should feel it
not only for orgmode but every mode and set it in their personal
preferences).

**Comment by TheBB** [comment]
I tend to agree with @maxigit. However I don't see that 0, ^ and $ are rebound to anything org-specific. If we can do that I'm all for removing `H` and `L`.

**Comment by tonylotts** [comment]
evil-org-mode provides the following bindings:
’$’	org-end-of-line
’^’	org-beginning-of-line

**Comment by choppsv1** [comment]
+1. "H" and "L" have specific vi motions that I (and presumably many other vi users) are quite used to and aren't anywhere near beginning of line or end of line, they are top of window and bottom of window. Remapping these to motions that already have keys associated with them seems like a user specific mapping by the package author, who must not normally use H and L. We should remove these odd remappings in spacemacs and be true to vi.

**Comment by jb55** [comment]
Yeah he even went further and rebound J and K [awhile back](https://github.com/edwtjo/evil-org-mode/commit/4d7251202572c62c2cfc3d780717771675486598) which we [reverted](https://github.com/syl20bnr/spacemacs/commit/a5ce15f03f6de5d71c342b51a39b14ed3ea93471). This seem like the author's personal bindings creeping into his library. :+1: for remove.
