### ISSUE TITLE
All links in documentation are 404.

### ISSUE THREAD

**Issue by justinkirby** [syl20bnr/spacemacs#4652]
To reproduce:
1. https://github.com/syl20bnr/spacemacs
2. Follow link to general documentation to https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org
3. Click on any link and it will be a 404, e.g. "Core Pillars", https://github.com/syl20bnr/spacemacs/blob/master/doc/Core%20Pillars

Expected:
Links in documentation would go to a valid url.

**Comment by robbyoconnor** [comment]
All documentation is now on (spacemacs.org)[http://spacemacs.org].

**Comment by robbyoconnor** [comment]
All documentation is now on [http://spacemacs.org](http://spacemacs.org))

**Comment by justinkirby** [comment]
@robbyoconnor perhaps the readme should link to that?

**Comment by robbyoconnor** [comment]
***PRs welcome!**** Do it against `develop` please and [read our contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org).

**Comment by robbyoconnor** [comment]
But I should point one thing out: That the docs are generated from the org files we use...it's done knowing that it will break on github  -- but it works in `helm-spacemacs` :) `SPC h SPC` is how you trigger that :)

**Comment by darkfeline** [comment]
It's nice that Github pretty-displays stuff like READMEs and Org files, but ultimately this repo should be for the actual code, not offline documentation (as in, you don't browse it from within Spacemacs).

The included documentation works fine when you clone it and browse locally via Emacs (online documentation), and kudos for migrating everything to Org files.

**Comment by StreakyCobra** [comment]
This issue has already been reported: #4399. I'm closing as duplicate, feel free to add there any relevant comments from this discussion :-)
