### ISSUE TITLE
magit updates currently borked due to missing dependency not on melpa 

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#4654]
This is just so noone else reports it. See https://github.com/magit/magit/issues/2497

**Comment by robbyoconnor** [comment]
Update: their seemed to be time zone issues

**Comment by robbyoconnor** [comment]
Fixed in melpa now. Killing this issue.

**Comment by robbyoconnor** [comment]
Not so fast...

**Comment by pwalsh** [comment]
Def. not fixed in MELPA.

**Comment by robbyoconnor** [comment]
@pwalsh -- yup :)

**Comment by robbyoconnor** [comment]
Still not fixed it seems...

**Comment by robbyoconnor** [comment]
See https://github.com/magit/magit/issues/2497#issuecomment-172447982  -- next melpa build

**Comment by robbyoconnor** [comment]
Working now. So closing this.

**Comment by kccai** [comment]
I have this problem ... again

**Comment by syl20bnr** [comment]
For people upgrading their packages, you can rollback to the previous version with the Rollback button on the home buffer.
Magit will be OK in a few hours.

**Comment by robbyoconnor** [comment]
I reported it again #4699 -- just in case...it's technically the same issue

**Comment by robbyoconnor** [comment]
This will likely happen again -- just rollback your changes. Reporting here doesn't do much.
