### ISSUE TITLE
Any demand for github-issues.el?

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#4655]
I found [github-issues.el](https://github.com/inkel/github-issues.el) randomly on melpa...is it worth adding to the github layer?

**Comment by StreakyCobra** [comment]
PR welcome :grin:

**Comment by robbyoconnor** [comment]
it's on my list now :)

**Comment by CestDiego** [comment]
:D I love this interaction

**Comment by kommen** [comment]
https://github.com/inkel/github-issues.el is not maintained any more, so I guess it should not be added.

**Comment by syl20bnr** [comment]
I think we have better now with magithub. Closing this. Feel free to re-open it if needed.
