### ISSUE TITLE
New layer: clipboard support on terminal for multiple systems

### ISSUE THREAD

**Issue by viccuad** [syl20bnr/spacemacs#4662]
Right now, there doesn't seem to be clipboard support with spacemacs TUI on Linux, and from the gitter chat I get that it doesn't work on other systems too.

Maybe is a good idea to gather here together the relevant configs to make a layer with them, with some layer docs on external dependencies.

**Comment by robbyoconnor** [comment]
:+1: If you make a PR, i'm sure people would love you.

**Comment by thang1thang2** [comment]
The only stuff I can find about the terminal so far is stuff involving custom functions that call out to xclip or some other external plugin. [This](https://github.com/rolandwalker/simpleclip) might be interesting to look at, though. [The wiki seems mildly useful](http://www.emacswiki.org/emacs/CopyAndPaste). And lastly, as further research, [this answer](http://stackoverflow.com/questions/28403647/emacs-25-yank-from-x-windows-primary-clipboard-buffer-with-keyboard) which gives a nice useful hint as to how yanking behavior changes from emacs 24 to emacs 25 (notably that `x-get-selection` is obsolete in 25.1 and a new method `gui-get-primary-selection`, deriving from `gui-get-selection` becomes available)

**Comment by StreakyCobra** [comment]
Possibly useful link: https://wiki.archlinux.org/index.php/emacs#Clipboard_support_for_emacs-nox

**Comment by viccuad** [comment]
Well, color my surprised. I have tried defining `interprogram-cut-function` and `interprogram-paste-function`  myself and couldn't get it to work. I report it works with those definitions in the Arch wiki: (on Linux, with xclip installed in the system)

```elisp
(unless window-system
  (when (getenv "DISPLAY")
    (defun xclip-cut-function (text &optional push)
      (with-temp-buffer
	(insert text)
	(call-process-region (point-min) (point-max) "xclip" nil 0 nil "-i" "-selection" "clipboard")))
    (defun xclip-paste-function()
      (let ((xclip-output (shell-command-to-string "xclip -o -selection clipboard")))
	(unless (string= (car kill-ring) xclip-output)
	  xclip-output )))
    (setq interprogram-cut-function 'xclip-cut-function)
    (setq interprogram-paste-function 'xclip-paste-function)
    ))
```

Looking forward to see other working configs in other SOs, to bundle them in a layer.

**Comment by StreakyCobra** [comment]
https://github.com/syl20bnr/spacemacs/issues/3064 may as well be included here (instead of in `spacemacs` layer as I suggested there).

**Comment by jamesla** [comment]
+1

**Comment by cweill** [comment]
I have some custom elisp code that does just this and would be happy to make a pull request to fix this. I also works across remote machines using xsel, and also works gracefully inside tmux when reattaching from different machines. 

Where would be the appropriate place to put such code for custom spacemacs layer?

**Comment by viccuad** [comment]
I'm personally glad that you are willing to share that code :), many thanks.

From what I know, You can use the `configuration-layer/create-layer` command from the contributing docs: 
https://github.com/syl20bnr/spacemacs/blob/master/CONTRIBUTING.org#contributing-a-layer

This will create a all the needed file templates. For the layer structure, the read is:
https://github.com/syl20bnr/spacemacs/blob/master/doc/LAYERS.org

**Comment by cweill** [comment]
Thanks, I'll put a layer together. Which spacemacs/layers/ directory should this go under?

**Comment by wilhelmy** [comment]
Any updates on this?

Looking forward to see it merged eventually.

**Comment by mgsloan** [comment]
:+1: I want convenient access to this too

**Comment by cweill** [comment]
I've just updated the PR to resolve the comments. PTAL.

**Comment by cweill** [comment]
[This post](https://github.com/syl20bnr/spacemacs/pull/8864) on hacker news today is relevant to this topic. Maybe it will be useful for someone else here.

**Comment by syl20bnr** [comment]
Thank you ! 👍 

I made a local package to make it more idiomatic, see commit https://github.com/syl20bnr/spacemacs/commit/1befcad00

I just tested that the key-bindings are correctly installed.

Cherry-picked into develop branch, you can safely delete your branch.

**Comment by syl20bnr** [comment]
Oops wrongly closed it.
Thank you @cweill, merged in develop branch.

**Comment by cweill** [comment]
@syl20bnr: My pleasure. Thank you for your review.

**Comment by NightMachinary** [comment]
Any way to make this work on macOS? I have `xclip` installed, but it doesn't work.

**Comment by NightMachinary** [comment]
@syl20bnr https://github.com/joddie/osx-clipboard-mode works great. I think it should be added to the osx layer.

**Comment by suonlight** [comment]
@NightMachinary, @syl20bnr : I had a PR to add osx-clipboard-mode to osx layer: https://github.com/syl20bnr/spacemacs/pull/11215

**Comment by wilhelmy** [comment]
I think the correct OS X commands to use instead of `xclip` (which is X11 specific) are `pbcopy` and `pbpaste`, there's no need for a separate mode.

**Comment by elmarlee** [comment]
Is it possible to have this layer support cygwin terminal like https://github.com/ArthurTu/cygwin-terminal-clipboard
