### ISSUE TITLE
problems updating to latest spacemacs develop branch

### ISSUE THREAD

**Issue by mankoell** [syl20bnr/spacemacs#4665]
I'm on develop branch trying to update to latest spacemacs from 105.7. 

```
  .emacs.d [develop] LC_ALL=C git pull --rebase
First, rewinding head to replay your work on top of it...
Applying: yasnippet: add support for dotspacemacs directory
Using index info to reconstruct a base tree...
M	layers/auto-completion/README.org
M	layers/auto-completion/packages.el
Falling back to patching base and 3-way merge...
Auto-merging layers/auto-completion/README.org
CONFLICT (content): Merge conflict in layers/auto-completion/README.org
error: Failed to merge in the changes.
Patch failed at 0001 yasnippet: add support for dotspacemacs directory
The copy of the patch that failed is found in: /home/manu/.git/modules/.emacs.d/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

I dont know what to do next. So I tried to start spacemacs again  and it seems I'm on `105.9` now, according to the upper right expression. Back to the `.emacs.d` folder:

```
☁  .emacs.d [a8ce785] ⚡ LC_ALL=C gss 
UU layers/auto-completion/README.org
☁  .emacs.d [a8ce785] ⚡ LC_ALL=C git branch
* (no branch, rebasing develop)
  develop
  master
```

Looks dirty, seems to have a detached branch. I'm not really happy with, did spacemacs update succesfully or something went wrong?

**Comment by robbyoconnor** [comment]
Not a bug. This is a git conflict.

**Comment by robbyoconnor** [comment]
`git reset --hard upstream/develop`

**Comment by mankoell** [comment]
```
☁  .emacs.d [a8ce785] ⚡ git reset --hard upstream/develop
fatal: ambiguous argument 'upstream/develop': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

May I try origin/develop?

**Comment by justbur** [comment]
Yes it's probably origin develop. You need the remote that points to the main spacemacs repo

**Comment by justbur** [comment]
By the way that command will delete any local changes you've made.

**Comment by mankoell** [comment]
work dir is clean now but im still with detached head. `git checkout develop`? I'm scared so I ask, I did this before and it rolled back to 105.7

**Comment by robbyoconnor** [comment]
git reset --hard origin/develop

**Comment by justbur** [comment]
to setup a tracking branch
```
git checkout origin/develop -b develop
```
if the develop branch already exists, you can delete it with
```
git branch -D develop
```
then run the first command. After that
```
git pull
```
will pull in changes. The `--rebase` flag can be used if you have local changes that you want to rebase on top of any new commits that are pulled, but given that you're not aware of merge conflicts this is probably not what you want.

**Comment by mankoell** [comment]
thanks guys :kissing_cat:
