### ISSUE TITLE
Mouse click not working for spell check

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#4666]
I use the `spell-checking` layer and the mouse cursor changes to a hand when hovering a misspelled word with it. However, when I click on it nothing appears to happen.

**Comment by StreakyCobra** [comment]
Try to click on the middle button (wheel).

**Comment by 3rd3** [comment]
I have tried that as well. Is that button-2? Perhaps this is not supported in the Emacs build for OS X?

**Comment by StreakyCobra** [comment]
Maybe, I don't know, you'll need help from OSX guys for this :pensive:

**Comment by rowandavies** [comment]
With a trackpad I found I needed to explicitly set up a modifier plus mouse button via an OSX app.

Try, e.g., Karabiner https://pqrs.org/osx/karabiner/index.html.en or anther options from:

http://superuser.com/questions/416981/middle-mouse-button-click-via-hotkey-modifier-in-osx

**Comment by syl20bnr** [comment]
I also use Karabiner to simulate a middle click by pressing Ctrl+click. This is how I paste text in urxvt on a MacBook.

**Comment by agzam** [comment]
Does anyone know how to make Emacs produce a middle-click when holding a modifier key and clicking left button? e.g.: `M-mouse1` or `C-mouse1` - will actually produce `mouse2`. Without using any other software?
