### ISSUE TITLE
Possible to have a 3-way merging thing?

### ISSUE THREAD

**Issue by Magicloud** [syl20bnr/spacemacs#4673]
For example, I use Spacemacs to keep a task list with alarm. The task list is maintained by a couple of sources in the same time: Me (manually editing), some programs (fetching some information from web and editing).
Without me editing, the global-revert-mode works well that I can always see the latest tasks when I switch to the window.
But if I edited without saving, the content would not be updated and a saving would overwrite the changes by the programs.

So my question is, is it possible to do a 3-way merging when the buffer is not saved and the file is changed? Better be prompted or start automatically.

Thanks.

**Comment by TheBB** [comment]
Looks like nobody has an answer for you. Sorry. :-/
