### ISSUE TITLE
disable evil escape while selecting text

### ISSUE THREAD

**Issue by mankoell** [syl20bnr/spacemacs#4674]
I've set `evil-escape-key-sequence` to `jj` as I got used to it from my vim config. In vim, while in visual line I can press multiple times `jj` to select the text I wanna yank, without leaving this mode. In spacemacs it is working wrong and escape to normal mode/state.

**Comment by mankoell** [comment]
Nvm, according to [evil-escape](https://github.com/syl20bnr/evil-escape#excluding-a-major-mode):

```
  (setq-default evil-escape-excluded-major-modes "visual")
```

**Comment by mankoell** [comment]
I tried to set:

```
  (setq-default evil-escape-excluded-major-modes 'visual)
```

and

```
  (setq-default evil-escape-excluded-major-modes "visual")
```

but this will break the whole evil escape and `jj` is no longer working.

**Comment by TheBB** [comment]
As the name of the variable suggests, it is a list of *major modes*, not evil *states*.

I believe the problem you are experiencing is the reason why `jj` is not a good escape sequence, therefore this is bordering on a user configuration problem. However it wouldn't be unreasonable to be able to exclude evil states, either. You can probably make a feature request to https://github.com/syl20bnr/evil-escape

**Comment by TheBB** [comment]
In fact it wasn't so hard: https://github.com/syl20bnr/evil-escape/pull/61

**Comment by mankoell** [comment]
Wow thank you @TheBB :heart_eyes_cat:
