### ISSUE TITLE
org-mode cann't output Chinese to pdf

### ISSUE THREAD

**Issue by reboothit** [syl20bnr/spacemacs#4676]
who can fix it?

**Comment by duerrp** [comment]
I export to pdf via latex and use the CJKutf8 package for Japanese... maybe that helps
```
(add-to-list 'org-latex-packages-alist '("" "CJKutf8" t))
```

**Comment by TheBB** [comment]
I'm assuming that solves it. Please let us know if not.

**Comment by luixiao1223** [comment]
#+LaTeX_HEADER: \usepackage{CJK}
#+LaTeX_HEADER: \begin{CJK}{UTF8}{gbsn}

Try this code (I tested it on emacs 25.2)
