### ISSUE TITLE
How to release C-z from Evil?

### ISSUE THREAD

**Issue by Magicloud** [syl20bnr/spacemacs#4677]
I am used to press C-z to suspend (not only emacs). Now it is occupied and I mis-used a lot that is annoying. Googling did not give me a usable solution. May I know how to release the key binding and get it back to suspend?
Thanks.

**Comment by TheBB** [comment]
Please see `evil-toggle-key`. You have to set this before evil loads, so during `dotspacemacs/user-init`, for example.

**Comment by Magicloud** [comment]
OK. So I put it in wrong place. Thanks.
