### ISSUE TITLE
How to hide the symbols of kybrid-mode and which-key-mode in spaceline?

### ISSUE THREAD

**Issue by scloudyy** [syl20bnr/spacemacs#4679]
I want to hide the symbols of kybrid-mode and which-key-mode in spaceline, because there is not much function in these symbols, but I can't...

Anyone know about that?

**Comment by nixmaniack** [comment]
I had the same issue with failed attempts using `diminish` and `spacemacs|diminish`

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/4696

**Comment by TheBB** [comment]
After that PR is merged, this will work:

```lisp
(with-eval-after-load 'hybrid-mode
  (spacemacs|diminish hybrid-mode))
(spacemacs|diminish which-key-mode)
```

**Comment by scloudyy** [comment]
It works! Thank you!
