### ISSUE TITLE
anaconda/jedi error when type 'lambda'

### ISSUE THREAD

**Issue by scloudyy** [syl20bnr/spacemacs#4683]
when I wwant to use lambda in python file it will always appear 
"error in process filter: apply: Wrong type argument: stringp, ((data . "KeyError('resullt',)") (message . "Server error") (code . -32000))
error in process filter: Wrong type argument: stringp, ((data . "KeyError('resullt',)") (message . "Server error") (code . -32000))"
over and over again, and it will freeze
![qq 20160119213423](https://cloud.githubusercontent.com/assets/15358886/12420004/ac2d4c12-bef4-11e5-9619-efab9b08a958.png)

![qq 20160119213640](https://cloud.githubusercontent.com/assets/15358886/12420014/bd3d7e50-bef4-11e5-9ed3-c51686803cc9.png)

**Comment by scloudyy** [comment]
when I type 'lambda', it whil appear 'invalid syntax', and then is 
'error in process filter: apply: Wrong type argument: stringp, ((data . "KeyError('result',)") (message . "Server error") (code . -32000))
error in process filter: Wrong type argument: stringp, ((data . "KeyError('result',)") (message . "Server error") (code . -32000))'
And these two error repeat rapidly that I can even hardly move cursor.
Other seems fine at the moment, and I have already  pip install  jedi==0.8.1 json-rpc==1.8.1 service_factory==0.1.2
@fbergroth @cpaulik

**Comment by fbergroth** [comment]
This is likely the same issue as in #4170 / davidhalter/jedi#572. I'm using elpy instead of anaconda, which won't freeze emacs on issues like these (but also stops completions from working), but that's not an option to toggle in spacemacs currently.

**Comment by scloudyy** [comment]
It seems no one working around with this bug, both anaconda and jedi. Is elpy will faster than anaconda?

**Comment by cpaulik** [comment]
You should really raise these issues with anaconda and/or jedi. There is not a lot we can do in spacemacs. I think that anaconda should take care not to block emacs. And jedi should fix the underlying problem. This would benefit the most people, also outside of spacemacs.

**Comment by cpaulik** [comment]
It seems @proofit404 is aware of the problem. See https://github.com/proofit404/anaconda-mode/issues/148

**Comment by scloudyy** [comment]
Author of anaconda-mode said he will fix it when he has time, so we should wait. Close now.

**Comment by proofit404** [comment]
Thanks for your patience guys.
