### ISSUE TITLE
Unable to replace text in visual mode with paste

### ISSUE THREAD

**Issue by kubaracek** [syl20bnr/spacemacs#4685]
#### Description

When I `y`ank a word and then in visual mode select a text that I want to replace pressing `p` seems to delete the highlighted text which yanks it and paste it instead of the originally yanked text making it impossible to replace a text.
#### Update

Seems like `osx` layer causes this weird behaviour.
#### Reproduction guide

Highlight a word in visual mode.
press `y` to yank the selection
go to a word that you want to replace
go to visual mode and select this word
press `p`

Right now the word should be replaced with the yanked text but it's replaced with itself == makes no change to the word.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.7
- Spacemacs branch: master (rev. 8a94bbf)
- Distribution: spacemacs
- Layers:

``` elisp
     '(
     auto-completion
     better-defaults
     ;; Languages
     emacs-lisp
     ruby
     scala
     markdown
     javascript
     shell-scripts
     yaml
     html
     dockerfile
     ruby-on-rails
     ;; org
     (shell :variables
             shell-default-height 30
             shell-default-position 'bottom)
     ;; spell-checking
     syntax-checking
     ;; version-control
     git
     github
     ;; themes
     themes-megapack
     colors
     ;; system
     osx
     tmux
     ;; chat
     erc
     )
```

**Comment by TheBB** [comment]
I can't reproduce this. It works as expected here.

**Comment by JacobJakub** [comment]
Just tried to comment out all my layers and it works. So there must gotta be a one that causes this. Let me debug it

**Comment by JacobJakub** [comment]
Ok debugged it by commenting out my active layers and this is caused by `osx` layer.

**Comment by nixmaniack** [comment]
I can confirm this and was surprised with this behaviour and wondered this must be the Vim way and continued using it! :smiling_imp:

**Comment by nixmaniack** [comment]
I faced this in hybrid style(hybrid state). I think `delete-selection-mode` would be useful in `hybrid-state`.

**Comment by aspett** [comment]
Have been having this issue for ages. Did you find any good way to configure the osx layer to fix the issue?

**Comment by aspett** [comment]
Actually, just tried disabling the `osx` layer. Issue is still present for me

Steps I used to reproduce:
- Copy some text from website
- Visual line mode on some text in a buffer
- p
- Doesn't paste what I copied



- OS: osx yosemite
- Emacs: 24.5.1
- Spacemacs: 0.105.6
- Spacemacs branch: master
- Distribution: spacemacs
- Layers:

```
     emacs-lisp
     git
     ;; osx
     markdown
     org
     ruby-on-rails
     elixir
     restclient
```

**Comment by JacobJakub** [comment]
Hi @aspett do you have any layer that uses your system clipboard in emacs? When I copy anything from web/(any other app) then `p` uses another (emacs) clipboard. Which is what I would except.

I have this simple config defined in `dotspacemacs/user-config`

```
(defun pbcopy ()
    (interactive)
    (call-process-region (point) (mark) "pbcopy")
    (setq deactivate-mark t))

  (defun pbpaste ()
    (interactive)
    (call-process-region (point) (if mark-active (mark) (point)) "pbpaste" t t))

  (defun pbcut ()
    (interactive)
    (pbcopy)
    (delete-region (region-beginning) (region-end)))

  (global-set-key (kbd "C-c c") 'pbcopy)
  (global-set-key (kbd "C-c v") 'pbpaste)
  (global-set-key (kbd "C-c x") 'pbcut)
```

This allows me to copy, paste and cut from/to my system clipboard using `C-c c` for copy `C-c v` for paste and `C-c x` for cut

**Comment by aspett** [comment]
Heya @JacobJakub. No, I've tried disabling all layers and reverting to a stock config, but no joy. I was expecting that copying to system clipboard would allow me to paste via `p`. I'd rather not set up special keybinds for pbcopy etc- having system clipboard copy into another register would be an ideal alternative.

**Comment by idrozd** [comment]
Same issue here

While this is not yet solved, one can use kill-ring (SPC r y) to avoid looking for and copying source of attempted paste second time

**Comment by Grimi94** [comment]
I am having the same issue with the ``` osx ``` layer

**Comment by felipeagc** [comment]
I was having the same issue with spacemacs and my own configuration on Arch Linux. Found this solution [here](http://emacs.stackexchange.com/questions/14940/emacs-doesnt-paste-in-evils-visual-mode-with-every-os-clipboard/15054#15054). It worked for me, hope it helps.

**Comment by braham-snyder** [comment]
this is a duplicate of https://github.com/syl20bnr/spacemacs/issues/3735

**Comment by FieryCod** [comment]
@felipeagc Thank you so much bro :)

**Comment by bobdanek** [comment]
I'm having a similar problem that sounds like the same root cause.

If I `y` something in visual mode, or yank a line while not in visual mode, move elsewhere, delete a word or line (`d w` or `D`), then `p`, the thing that gets pasted is the thing I just deleted, not thing thing I yanked.


System:
* OS: macOS 10.14.2 (18C54)
* SpaceMacs version: 0.200.13@26.1
* Emacs version: d12frosted/emacs-plus/emacs-plus: stable 26.1 (bottled), devel 26.1-rc1, HEAD

**Comment by kubaracek** [comment]
> I'm having a similar problem that sounds like the same root cause.
> 
> If I `y` something in visual mode, or yank a line while not in visual mode, move elsewhere, delete a word or line (`d w` or `D`), then `p`, the thing that gets pasted is the thing I just deleted, not thing thing I yanked.
> 
> System:
> 
> * OS: macOS 10.14.2 (18C54)
> * SpaceMacs version: 0.200.13@26.1
> * Emacs version: d12frosted/emacs-plus/emacs-plus: stable 26.1 (bottled), devel 26.1-rc1, HEAD

This is a default vim behavior :D https://vim.fandom.com/wiki/Remembering_previous_deletes/yanks

type :reg to see all the registers
