### ISSUE TITLE
Reduce gc-cons-threshold for responsiveness

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#4687]
It's worth to have a look at this the article in this thread and its discussion: https://www.reddit.com/r/emacs/comments/41m7x3/why_are_you_changing_gcconsthreshold/. In summary, higher `gc-cons-threshold` speed up Emacs, but lower `gc-cons-threshold` gives more responsiveness. Given Spacemacs sometimes causes random freeze, I think it's worth to try setting `gc-cons-threshold` back to its default value after Spacemacs done initializing.

**Comment by CestDiego** [comment]
this ^ I approve. @tuhdo what do you think of the fix that they propose though?

**Comment by syl20bnr** [comment]
I repeat: https://github.com/syl20bnr/spacemacs/issues/3011#issuecomment-139950569

:-)

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
