### ISSUE TITLE
org bullets mess up when switching themes

### ISSUE THREAD

**Issue by mankoell** [syl20bnr/spacemacs#4688]
When I switch themes with `SPC T n` while beeing in an org file, some weird bullets appear in front of. The only way to get rid of them is to restart spacemacs. I dont know exactly if it has to do with `org-bullets`.

![bildschirmfoto vom 2016-01-19 17 08 52](https://cloud.githubusercontent.com/assets/1057526/12424249/8d7498d6-becf-11e5-9d93-0a7b3fbbd5b4.png)
![bildschirmfoto vom 2016-01-19 17 08 02](https://cloud.githubusercontent.com/assets/1057526/12424255/981229b6-becf-11e5-93ef-7a45047c3172.png)
![bildschirmfoto vom 2016-01-19 17 08 17](https://cloud.githubusercontent.com/assets/1057526/12424273/b048d886-becf-11e5-948c-5484ac422a38.png)

**Comment by TheBB** [comment]
This is a limitation of `org-bullets-mode` that I'm not sure we can fix. It sets the foreground of hidden bullets according to the background of the current theme, but doesn't update them afterwards. If you re-enable org-mode after changing theme, it'll be fixed. I'm leaning towards saying this is an org-mode problem and you should report it there, and not here.

**Comment by mankoell** [comment]
I'm sorry, I didn't know. I guess you mean it is a problem of `org-bullet`, not org-mode itself?

**Comment by TheBB** [comment]
Sorry, I think I'm confused. :-D

I believe this is `org-indent-mode`, not `org-bullets-mode`. This mode is part of the org package proper. It has a lot of problems, this is only one of them.

**Comment by TheBB** [comment]
Actually I'm not even sure if that's the case any more.

**Comment by mankoell** [comment]
So how do I disable `org-bullets` then? I tried:
```
  (setq org-excluded-packages '(org-bullets))
```

**Comment by pmagwene** [comment]
@mankoell 
You can disable org-bullets by adding it to this line in `.spacemacs`:

```
   dotspacemacs-excluded-packages '()
```

**Comment by mankoell** [comment]
@pmagwene Thanks, this works great!

**Comment by joonro** [comment]
I don't have a solution for this, but you can refresh the local setup to make it look right after a theme change instead of restarting emacs. For example, you can go to the `#+TITLE` line and then do `C-c C-c` and the annoying stars should be gone.

**Comment by kconner** [comment]
Based on @joonro's idea, we can get the behavior used by C-c C-c on a `#+TITLE:` and run it at the time the theme is changed. I'm running vanilla, not Spacemacs, but maybe this will help someone.

```elisp
;; light and dark themes
(defvar my/light-theme 'base16-one-light)
(defvar my/dark-theme 'base16-phd)

(defun my/org-refresh ()
  (when (eq major-mode 'org-mode)
    ;; borrowed from org.el, org-ctrl-c-ctrl-c, in the `keyword case.
    ;; this is the refresh operation done when you C-c C-c on a
    ;; keyword like #+TITLE:. maybe not all of it is necessary.
    (let ((org-inhibit-startup-visibility-stuff t)
	  (org-startup-align-all-tables nil))
      (when (boundp 'org-table-coordinate-overlays)
	(mapc #'delete-overlay org-table-coordinate-overlays)
	(setq org-table-coordinate-overlays nil))
      (org-save-outline-visibility 'use-markers (org-mode-restart)))
    (message "Local setup has been refreshed")))

;; thanks to https://emacs.stackexchange.com/a/66477
(defun my/apply-theme (appearance)
  "Load theme, taking current system APPEARANCE into consideration."
  (mapc #'disable-theme custom-enabled-themes)
  (pcase appearance
    ('light (load-theme my/light-theme t))
    ('dark (load-theme my/dark-theme t)))
  (my/org-refresh))

(add-hook 'ns-system-appearance-change-functions #'my/apply-theme)
```
