### ISSUE TITLE
Pressing backspace in helm doesn't update search term anymore

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#4690]
Type `SPC p f`, and then start typing a search term, like `calv4`.  Press backspace to remove `v4`. 

The search results update, but `v4` doesn't actually get removed from the search terms.  Pressing something like `M-BACKSPACE` does update them.

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. a8ce785)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(unscroll auto-completion xkcd emacs-lisp git dash yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors spacemacs-layouts vimscript themes-megapack spacemacs-helm
          (c-c++ :variables c-c++-enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by AlejandroCatalina** [comment]
I think that is a reported bug, see #4538.

**Comment by synic** [comment]
You are correct!
