### ISSUE TITLE
spacemacs slowing to a crawl when printing mongodb documents

### ISSUE THREAD

**Issue by Clamwinds** [syl20bnr/spacemacs#4694]
I'm printing 2000 documents that have only 20ish fields and it slows down so much I have to reset the repl. Any one have any guidance for how I might alleviate this issue? This happens with congomongo and monger.

**Comment by StreakyCobra** [comment]
It would be nice if you can update your issue to follow [this format](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report).

**Comment by robbyoconnor** [comment]
Yes, your issue is actually missing ***A LOT** of information necessary.

**Comment by TheBB** [comment]
Please come back and reopen when you have some more information.
