### ISSUE TITLE
smartparens not work in python layer

### ISSUE THREAD

**Issue by winkar** [syl20bnr/spacemacs#470]
I'm on Linux Mint 17,emacs24
Things went well before I 've added the python layor to get better auto-completion.
After I've got the new layer and restart emacs, smatparens didn't work well in python.But it still work on markdown or other mode.

**Comment by syl20bnr** [comment]
Can you provide more information or an example in order to be able to reproduce the wrong behavior ?

**Comment by winkar** [comment]
I use ~/.emacs.d/core/templates/.spacemacs.template as my .spacemacs.
 I add 
    dotspacemacs-configuration-layers '(python)
into the end of the end of the second "setq-default" in order to get support of python layer and git layer.

After add above into .spacemacs, I restart emacs, and it will install 6 new packages. This time smartparens work

But when I restart emacs again, I cannot found a "(S)" at minor mode bar, and smartparens didn't work

**Comment by syl20bnr** [comment]
When you open a python file `smartparens` should be loaded.
Check for any error in the `*Message*` buffer. Change buffer with `<SPC> b s` then `mess RET` (RET = return).

**Comment by winkar** [comment]
File does not exist, create buffer? (y or n)  y
(New file)
Can't guess python-indent-offset, using defaults: 4
Sent python-shell-completion-setup-code
Sent python-ffap-setup-code
Sent python-eldoc-setup-code
Loading semantic/db-file...done
byte-code: Beginning of buffer
Blocking call to accept-process-output with quit inhibited!! [6 times]

Above are info in message buffer when I load a .py file

**Comment by Funnnny** [comment]
You might want to use pip to instal jedi and jsonrpc. Anaconda will try to install it but it doesn't have permission to do so (if you don't use virtualenv).

Then try again, it will just fix "Blocking call to accept-process-output with quit inhibited", but one problem at a time :)

**Comment by winkar** [comment]
this time it didn't show "block call  ..."

(New file)
Can't guess python-indent-offset, using defaults: 4
Sent python-shell-completion-setup-code
Sent python-ffap-setup-code
Sent python-eldoc-setup-code
Loading semantic/db-file...done

but still not work

**Comment by syl20bnr** [comment]
@winkar can you post your `~/.spacemacs` file content ?

**Comment by winkar** [comment]
;; -*- mode: emacs-lisp -*-
;; This file is loaded by Spacemacs at startup.
;; It must be stored in your home directory.

;; Configuration Layers
;; --------------------

(setq-default
 ;; List of additional paths where to look for configuration layers.
 ;; Paths must have a trailing slash (ie. `~/.mycontribs/')
 dotspacemacs-configuration-layer-path '()
 ;; List of configuration layers to load.
 dotspacemacs-configuration-layers '()
 ;; A list of packages and/or extensions that will not be install and loaded.
 dotspacemacs-excluded-packages '()
)

;; Settings
;; --------

(setq-default
 ;; Specify the startup banner. If the value is an integer then the
 ;; banner with the corresponding index is used, if the value is `random'
 ;; then the banner is chosen randomly among the available banners, if
 ;; the value is nil then no banner is displayed.
 dotspacemacs-startup-banner 'random
 ;; Default theme applied at startup
 dotspacemacs-default-theme 'monokai
 ;; The leader key
 dotspacemacs-leader-key "SPC"
 ;; Major mode leader key is a shortcut key which is the equivalent of
 ;; pressing `<leader> m`
 dotspacemacs-major-mode-leader-key ","
 ;; The command key used for Evil commands (ex-commands) and
 ;; Emacs commands (M-x).
 ;; By default the command key is `:' so ex-commands are executed like in Vim
 ;; with `:' and Emacs commands are executed with `<leader> :'.
 dotspacemacs-command-key ":"
 ;; Guide-key delay in seconds. The Guide-key is the popup buffer listing
 ;; the commands bound to the current keystrokes.
 dotspacemacs-guide-key-delay 0.4
 ;; If non nil the frame is fullscreen when Emacs starts up (Emacs 24.4+ only).
 dotspacemacs-fullscreen-at-startup nil
 ;; If non nil `spacemacs/toggle-fullscreen' will not use native fullscreen.
 ;; Use to disable fullscreen animations in OSX."
 dotspacemacs-fullscreen-use-non-native nil
 ;; If non nil the frame is maximized when Emacs starts up (Emacs 24.4+ only).
 ;; Takes effect only if `dotspacemacs-fullscreen-at-startup' is nil.
 dotspacemacs-maximized-at-startup nil
 ;; A value from the range (0..100), in increasing opacity, which describes the
 ;; transparency level of a frame when it's active or selected. Transparency can
 ;; be toggled through `toggle-transparency'.
 dotspacemacs-active-transparency 90
 ;; A value from the range (0..100), in increasing opacity, which describes the
 ;; transparency level of a frame when it's inactive or deselected. Transparency
 ;; can be toggled through `toggle-transparency'.
 dotspacemacs-inactive-transparency 90
 ;; If non nil unicode symbols are displayed in the mode line (e.g. for lighters)
 dotspacemacs-mode-line-unicode-symbols t
 ;; If non nil smooth scrolling (native-scrolling) is enabled. Smooth scrolling
 ;; overrides the default behavior of Emacs which recenters the point when
 ;; it reaches the top or bottom of the screen
 dotspacemacs-smooth-scrolling t
 ;; If non-nil smartparens-strict-mode will be enabled in programming modes.
 dotspacemacs-smartparens-strict-mode nil
 ;; If non nil advises quit functions to keep server open when quitting.
 dotspacemacs-persistent-server nil
 ;; The default package repository used if no explicit repository has been
 ;; specified with an installed package.
 ;; Not used for now.
 dotspacemacs-default-package-repository nil
 dotspacemacs-configuration-layers '(git)
 dotspacemacs-configuration-layers '(python)
 )



;; Initialization Hooks
;; --------------------

(defun dotspacemacs/init ()
  "User initialization for Spacemacs. This function is called at the very
 startup."
  )

(defun dotspacemacs/config ()
  "This is were you can ultimately override default Spacemacs configuration.
This function is called at the very end of Spacemacs initialization."
(spacemacs/set-font "DejaVu Sans Mono" 13)
)

;; Custom variables
;; ----------------

;; Do not write anything in this section. This is where Emacs will
;; auto-generate custom variable definitions.

**Comment by syl20bnr** [comment]
@winkar The mistake is here:

```elisp
dotspacemacs-configuration-layers '(git)
dotspacemacs-configuration-layers '(python)
```

It should be:

```elisp
dotspacemacs-configuration-layers '(git python)
```

Also note that the template already declared this variable at the top of the file in the section:
```elisp
;; Configuration Layers
;; --------------------
```

**Comment by syl20bnr** [comment]
@winkar hmmm it will not fix your smartparens issue though...

Paste your whole `*Message*` buffer once you loaded the first python file

**Comment by winkar** [comment]
already fixed，I think I put it in wrong position

**Comment by dzhwinter** [comment]
@winkar  how do you fix it? can you post the details? thx

**Comment by tuhdo** [comment]
@dzhwinter it should work with latest `master`? It is working for me here.

**Comment by dzhwinter** [comment]
Is smartparens import this error? which version are you use before?  Post it, and your solution may guide other guys like me,



dzhwinter@gmail.com
 
From: Tu Do
Date: 2015-06-03 00:20
To: syl20bnr/spacemacs
CC: dzhwinter
Subject: Re: [spacemacs] smartparens not work in python layer (#470)
@dzhwinter it should work with latest master? It is working for me here.
