### ISSUE TITLE
C struct member autocomplete not working

### ISSUE THREAD

**Issue by dexafree** [syl20bnr/spacemacs#4707]
#### Description
If there is a struct declared in a C source code file, autocomplete does not work for trying to access members of that struct.

#### Reproduction guide
- Start Emacs
- Create a new C source file (ie test.c)
- Add the following content (for test purposes)

```c
#include <stdio.h>

typedef struct {
    int x;
    int y;
} Point;

int main(int argc, char **argv){
    Point p;
    return 0;
}
```

- Inside the main function, below `Point p` try to write `p.`. You can press tab if you want, but the autocomplete popup is not appearing. (You can test adding `stdlib.h` and changing it by a pointer with `malloc`, won't work either).

I also tried generating the CTags, but dodn't work either.

DESCRIPTION OF THE OBSERVED BEHAVIOUR

The autocompletion engine doesn't show the struct members.

DESCRIPTION OF THE EXPECTED BEHAVIOUR

If you wrote `p.`, or if it was a pointer, `p->`, the autocomplete should show the options *x* and *y*.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp c-c++ haskell html latex markdown org
                 (osx :variables osx-use-option-as-meta nil)
                 python rust shell syntax-checking themes-megapack my-monokai-theme)
```

**Comment by TheBB** [comment]
Is basic company expected to be able to do this kind of thing? Don't you need to use clang or ycmd (which uses clang)?

**Comment by TheBB** [comment]
I should also note that by default in Spacemacs, company will not try to complete if the prefix isn't at least two characters. So just `p.` shouldn't react.

**Comment by tuhdo** [comment]
@TheBB  `p.` should be enough to trigger completion.

@dexafree are you doing it on an unsaved buffer? Try saving to a file, because I had this problem only in unsaved buffer. Also, you should install `clang` if you haven't.

**Comment by dexafree** [comment]
Just found this issue that talks about a similar problem: 
https://github.com/company-mode/company-mode/issues/43

There, it talks about the clang version, so I suppose you actually need clang.

I thought it was supposed to do so.

If it's not, feel free to close the issue as it's not a real one, sorry!

**Comment by dexafree** [comment]
@tuhdo Forgot to add the step of saving the file, but I've tried with projects, single files (saved), unsaved ones and the behaviour is the same.

Also, I have clang installed:

Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by TheBB** [comment]
@tuhdo Then what's the purpose of `company-minimum-prefix-length`?

**Comment by tuhdo** [comment]
Maybe you should try running the command `company-clang` just after `p.` to see if it actually works?

**Comment by tuhdo** [comment]
@TheBB `p.` is already 2 characters.

**Comment by TheBB** [comment]
Yeah, but is that a prefix? I assumed the prefix had to be part of what you actually needed to complete.

At least in HTML, `<` does not count as part of the prefix.

**Comment by TheBB** [comment]
I must be wrong. Rust allows completion on `.` right off the bat. Sorry.

**Comment by dexafree** [comment]
@tuhdo should `company-clang` be available?

If I press `SPC :` , company-clang doesn't show up :worried:

**Comment by TheBB** [comment]
http://spacemacs.org/layers/+lang/c-c++/README.html#orgheadline7

You have to configure it.

**Comment by dexafree** [comment]
Thanks @theBB , that was it!

I had not read that part, sorry :(

Solved!

**Comment by fbergroth** [comment]
>Then what's the purpose of company-minimum-prefix-length?

@TheBB, the prefix handler in a company backend may return two types of values. Either it is a plain string, which will then be compared with `company-minimum-prefix-length`. The other case (quoting from `company-backends` docstring):

> Instead of a string, the backend may return a cons where car is the prefix
> and cdr is used instead of the actual prefix length in the comparison
> against `company-minimum-prefix-length'.  It must be either number or t,
> and in the latter case the test automatically succeeds.

In rust, we return `("prefix" . t)` if there is a `.` or `::` before the prefix to force a completion.
