### ISSUE TITLE
Opening file from terminal in GUI in OSX with: open -a Emacs.app file.name opens 2 emacs windows

### ISSUE THREAD

**Issue by jbmorgado** [syl20bnr/spacemacs#4708]
Hello,
when trying to open a file from OSX terminal in emacs: `open -a Emacs.app file.name` spacemacs opens 2 emacs windows. One, the normal startup window with the recent files and projects and another actually with the `file.name` pretended.

The recent files and projects opens first and when opening in fullscreen mode this is the window that will actually show, and the window with `file.name` will stay hidden in the back.

**Comment by tonylotts** [comment]
Are you using emacs-mac from homebrew?

**Comment by ricardolee** [comment]
I have the same problem too, that emacs install with "brew install emacs --with-cocoa"

**Comment by ricardolee** [comment]
@morgado-jb 

(setq ns-pop-up-frames nil)
