### ISSUE TITLE
php-extras: wrong-type-argument sequencep

### ISSUE THREAD

**Issue by mankoell** [syl20bnr/spacemacs#4709]
Just enabled php layer:

```
Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: php-extras@php... [1/1]

An error occurred while installing php-extras (error: (wrong-type-argument sequencep php-extras))
```

**Comment by TheBB** [comment]
Can you please run with `--debug-init` to provide a backtrace?

**Comment by arstum** [comment]
the same problem.

Found 1 new package(s) to install...
--> installing package: php-extras@dotfile... [1/1]
Package php-extras is unavailable. Is the package name misspelled?

**Comment by mankoell** [comment]
@TheBB I did, the above message is all what I get. 

@arstum Not the same problem!

**Comment by mankoell** [comment]
Can't reproduce on my other machine.
