### ISSUE TITLE
Remap <Esc>.

### ISSUE THREAD

**Issue by dvorobiov** [syl20bnr/spacemacs#471]
Hi!
Can you please tell me how to remap Escape to jj in configuration? Is there also a way to run imap jj \<Esc>? 
Thanks!

**Comment by syl20bnr** [comment]
@dvorobiov you'll find the documentation here: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#escaping

Note that `jj` instead of `fd` is not recommended (details in documentation above).

**Comment by dvorobiov** [comment]
Thank you, @syl20bnr! The documentation is great!

**Comment by alimavrakis** [comment]
Link is dead. New link: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#escaping
