### ISSUE TITLE
Emacs key bindings: spacemacs/symbol-highlight

### ISSUE THREAD

**Issue by microamp** [syl20bnr/spacemacs#4720]
In `spacemacs/symbol-highlight`'s pop-up window, `n` and `N` are used for finding the next and previous occurrence respectively. IMHO, it should use `p` instead of `N` when it's configured to use Emacs key bindings instead of Vim's. Alternatively, `p` can be made to behave the same as `N` if it simplifies things.

**Comment by nixmaniack** [comment]
If any beginner is willing to make a PR, relevant line to add for new binding https://github.com/syl20bnr/spacemacs/blob/a8ce785dc8c70ec28d5daec9764cab57661dfb0d/layers/+distribution/spacemacs/packages.el#L371

**Comment by microamp** [comment]
Thanks. I can certainly have a look unless someone else chimes in first.

**Comment by microamp** [comment]
Fixed via #4763
