### ISSUE TITLE
Default emacs theme question

### ISSUE THREAD

**Issue by gguimaraesbr** [syl20bnr/spacemacs#4723]
What if I want to use the default emacs theme? Is it possible? I tried setting `dotspacemacs-themes` to nil but it doesn't work.

Thanks!

**Comment by izahn** [comment]
You can get part of the way there with 

```elisp

  (while custom-enabled-themes
    (disable-theme (car custom-enabled-themes)))

```

**Comment by cpaulik** [comment]
I think this is a bug. In `SPC T h` the `default` theme is an option. But putting `default` in `dotspacemacs-themes` gives an error because spacemacs looks for a melpa package `default-theme`

**Comment by izahn** [comment]
I don't think this counts as a bug, though possibly a missing feature. The thing is, there is no "default" theme. The "default" theme is just what you get when you disable all custom themes. If you look at  `helm-themes`  [1] you'll see that it first disables any custom themes with `(mapc 'disable-theme custom-enabled-themes)` (this being a smarter version of my `while` loop in the earlier comment), and then it does nothing if the selected them is "default".

All that said, it probably is a good idea to have a way of running spacemacs without a custom them. I've submitted a PR (https://github.com/syl20bnr/spacemacs/pull/4757) that allows setting `default` in  `dotspacemacs-themes`, in which case no theme will be enabled.  

[1] https://github.com/syohex/emacs-helm-themes/blob/7d0d457f1f14492805b2766937a2df55fe665375/helm-themes.el#L34

**Comment by syl20bnr** [comment]
Built-in themes are supported. I don't recall the name of the default theme but I'm pretty sure it has another name than default.

Can you try with another built-in theme name ?

**Comment by izahn** [comment]
I think what we're after here is the "theme" you get if you start emacs with `emacs -Q`. There is no theme for that; it is the absense of a custom theme. The problem is not that built-in themes don't work, but rather that we want to be able to starr emacs without enableing any theme.

**Comment by MadAnd** [comment]
The fix is also in `master`. The code
```emacs-lisp
dotspacemacs-themes '(default)
```
works as expected. So the issue may be closed.

**Comment by shankmittal** [comment]
dotspacemacs-themes '(default)  doesn't work anymore on new spacemacs

**Comment by dangom** [comment]
Any updates on this?

**Comment by TheBB** [comment]
I pushed a fix, check now.

**Comment by duianto** [comment]
It seems to be working:

![emacs_2017-06-16_17-36-31](https://user-images.githubusercontent.com/13420573/27233669-8b99b728-52ba-11e7-89c1-3b68b2f9d238.png)

This is probably a separate issue, but I switched to an older branch while I was testing, and the message:
>error: (error Unable to find theme file for ‘default’)

appears twice in the `*Messages*` buffer, 3rd from the top
>Loading c:/Users/Username/AppData/Roaming/.emacs.d/core/core-load-paths.el (source)...done
Loading c:/Users/Username/AppData/Roaming/.spacemacs...done
error: (error Unable to find theme file for ‘default’)
Setting the font...
PNG warning: Interlace handling should be turned on when using png_read_image
Open the quickhelp.

and line 60-70 something (the Spacemacs home buffer was open before restarting, therefore it opened on startup):
>Loading c:/Users/Username/AppData/Roaming/.emacs.d/layers/+source-control/version-control/keybindings.el (source)...done
Loading c:/Users/Username/AppData/Roaming/.emacs.d/.cache/spacemacs-buffer.el (source)...done
Spacemacs is ready.
error: (error Unable to find theme file for ‘default’)
Loading c:/Users/Username/AppData/Roaming/.emacs.d/.cache/recentf...done
Open the quickhelp.
Skipping check for new version (reason: dotfile)
[yas] Prepared just-in-time loading of snippets successfully.

is the theme loading twice?

The message
>Open the quickhelp

also appears twice.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 94244302)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git markdown
      (org :variables org-agenda-files
           '("c:/Users/Username/Documents/"))
      version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by TheBB** [comment]
> error: (error Unable to find theme file for ‘default’)

That's exactly what I fixed. Not surprising that you see it on a different branch that doesn't have the fix.

**Comment by duianto** [comment]
The question was, since it's reported twice in the messages buffer, is the theme loaded twice? Or since the "Open the quickhelp" message also appears twice, is there something else going on?

**Comment by dangom** [comment]
It works now, but my modeline is still messed up, i.e., black fonts on a black background.

<img width="1278" alt="screen shot 2017-06-17 at 12 18 16" src="https://user-images.githubusercontent.com/7881842/27252152-15674ee2-5357-11e7-9139-fb4b885540ef.png">

**Comment by TheBB** [comment]
@duianto If the theme fails to load early in the boot process, it will load the fallback theme (spacemacs-dark) and attempt to load it again after packages have been fully initialized. So yeah, if there's an error, it will try to do it twice.

**Comment by TheBB** [comment]
@dangom Those are the default colours for the powerline faces, I believe.

**Comment by glumanda99** [comment]
I also have issues with choosing the default theme as default :D A workaround for me is to just put the default theme on the 2nd to last position in `dotspacemacs-themes` and switch to it once emacs starts with `SPC T n`.

**Comment by AlexDaniel** [comment]
Yeah, and it seems like it needs something like this also:
```
   dotspacemacs-mode-line-theme '(spacemacs)
```
Otherwise the modeline is sorta broken.

**Comment by gnumonk** [comment]
This is still not working with the latest 
Warnings:
- An error occurred while applying the theme "default", fallback on theme
"spacemacs-dark". Error was: (error Unable to find theme file for ‘default’)      
- Please check the value of "dotspacemacs-themes" in your dotfile or open an issue
so we can add support for the theme "default".

Spacemacs v.0.200.13

Below variable set in .spacemacs

dotspacemacs-themes '(default)

**Comment by Compro-Prasad** [comment]
@gnumonk I don't think master has the same changes as in develop. For me, it works on the develop branch.

**Comment by equwal** [comment]
This works on the current spacemacs.
