### ISSUE TITLE
magit ediff on unstaged file leads to emacs freeze.

### ISSUE THREAD

**Issue by vibrys** [syl20bnr/spacemacs#4730]
#### Description

magit ediff command on unstaged file leads to emacs freeze.
This does not happen at every ediff command. Roughly 30% visits lead to freeze. Remaining ones behave correctly.
It never happened when ediffing file change from an already commited change.
This also does not happen on my non-spacemacs configuration, where ediff is also within the same single window.
#### Reproduction guide
- Start Emacs
- visit project directory
- SPC g s  - magit-status
- edit some project file
- go back go magit status buffer.
- g  to refresh.
- point the unstaged file changed.
- e   - ediff session will popup.
- visit next/previous differences with n/p

at some point emacs stops responding on n/p keypresses and it starts consuming 100% CPU.
Subsequent C-g makes emacs back from freeze, but cursor is left within most left source code window, not within ediff bottom line.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp git syntax-checking python c-c++ cscope themes-megapack)
```
#### Backtrace

after toggle-debug-on-quit, C-g tells:

Debugger entered--Lisp error: (quit)
  redisplay_internal\ (C\ function)()

**Comment by duerrp** [comment]
Ediff from magit is a nice feature, thanks for reminding me of it. I cannot reproduce your problem though - seems to work nicely...

**Comment by duerrp** [comment]
Could this be related to Issue #4474?

**Comment by vibrys** [comment]
I do confirm, #4474 gets reproduced on my setup.
There is one difference:
freeze happens at 2nd diff chunk, not after the 7th one.

best regards.

**Comment by magnetophon** [comment]
@vibrys I tested again on `8825a06`, and it seems fixed here.

**Comment by deb0ch** [comment]
Checking on this for the Automnal cleanup (#7344), what is the status on this ?

@vibrys Can you please confirm if it is fixed or not so we can close it (or not) ?

**Comment by vibrys** [comment]
Sorry for late answer.

I switched to spacemacs devel a few months ago to make sure I'm working with right code.
Unfortunatelly I'm still observing freezes.

regards,
Mat

**Comment by vibrys** [comment]
to be more precise, the last spacemacs devel version I observed freezes on is cf951a5.

**Comment by d12frosted** [comment]
@vibrys could you please checkout on the latest Spacemacs version (v0.200.x) or on latest develop?

**Comment by vibrys** [comment]
I did happen today again.
I working with version 72d87de (develop branch). SHould it contain the fix?

Tomorrow, I'll use newest version (f0803bc) and test it.

regards

**Comment by vibrys** [comment]
I did happen again today on f0803bc develop.

regards,
Mat

**Comment by bmag** [comment]
In #7366, @randre03 has also been experiencing freezes with ediff, but from `SPC f e D` and not magit. @vibrys just to make sure, if you create two files with the same content as the two versions of the same file that magit-ediff choked on, and run a regular ediff (`M-x ediff`) on them, does it also freeze? (I suspect it will)
If you can upload a pair of files that cause ediff to freeze, and an up-to-date `SPC h d s` info, I'll try to repro it on my machine.

**Comment by PrgrmAtCeleritas** [comment]
I have also experienced the same issue (magit ediff freezes Spacemacs at 2nd diff hunk, Emacs CPU at 100%). However, as @bmag hypothesized, I have had this same issue with just regular ediff so I don't think it is a magit problem.

**Comment by vibrys** [comment]
I copied two files, the one before change and the one after change, then opened these two buffers within two adjacent emacs windows, then did M-x ediff-buffers, and no freeze happened.

Unfortunatelly I cannot send buffer contents. I have prepared branch which is 100% reproducible. I'll try to start magit without spacemacs. Then I'll try to see the difference with magit, but after change has been staged, then commited. Maybe I should send some signal to emacs while it is in feeze, with some debug-on-quit? Then see what is emacs stack trace?

**Comment by PrgrmAtCeleritas** [comment]
I am able to reproduce the problem on the two files located below. seems to break after the 5th diff. I ran a crypto-algorithm over the files so they are not readable. Would be useful if someone could download these files and see if they can reproduce the same problem.
[file1.txt](https://github.com/syl20bnr/spacemacs/files/543052/file1.txt)
[file2.txt](https://github.com/syl20bnr/spacemacs/files/543053/file2.txt)

 The files differ only in white space.

**Comment by bmag** [comment]
@PrgrmAtCeleritas thanks for the files. Unfortunately, for some reason I am still unable to reproduce the bug on Emacs 24.5.1 with Spacemacs 0.200.3. Since @vibrys discovered that the display engine hangs (in `redisplay-internal`), I suspect the combination of major mode's syntax highlighting, Ediff's highlighting, and maybe also Flycheck (from syntax-checking layer), somehow confuses the display engine.

This is the setup I tried to repro with:
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

@PrgrmAtCeleritas can you try and repro with this minimal setup? If it doesn't repro, then bisecting your config should lead you to the problematic (combination of) layers/config. If you can share your system information (`SPC h d s`), that would be nice.

Also, are these really `txt` files when you repro, or do they actually have a different extension? (I didn't recognize what prog language that was)

**Comment by PrgrmAtCeleritas** [comment]
They are perl (It won't let me upload files with that extension). However I still encounter the bug weather they are txt or pl. The major mode doesn't seem to make a difference.   

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.1
- Spacemacs branch: nil (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv javascript helm auto-completion better-defaults tmux ranger vinegar emacs-lisp git
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     syntax-checking version-control)
```
I will try with a minimal setup and see what happens.

**Comment by PrgrmAtCeleritas** [comment]
I tried it with the minimal setup below.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.3
- Spacemacs branch: nil (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
I still encounter the same problem. I also tried it with stock Emacs 24.5.1 and it has no problems, so it is not something wrong with my Emacs itself.

**Comment by PrgrmAtCeleritas** [comment]
I went ahead and used `debug-on-quit` and got a pretty detailed backtrace. `spacemacs/linum-update-window-scale-fix` seems to show up right before the call to the `redisplay_internal`, which freezes the program. 

@bmag or @d12frosted is there someone within the Spacemacs project who knows enough to look at this backtrace and get more insight about what may have caused the problem?

[backtrace file](https://github.com/syl20bnr/spacemacs/files/558928/fail.txt)
(FYI the backtrace has a lot of unprintable characters)

**Comment by PrgrmAtCeleritas** [comment]
I have another update which will hopefully help resolve this issue. I did some more debugging (This issue is really painful) and I tracked down the source of the problem to the `which-key` package. If I add `which-key` to my `dotspacemacs-excluded-packages` then I do not encounter this bug and ediff works fine. However if I use `restart-stock-emacs-with-packages` and only include `which-key` then I also don't encounter this bug, which is weird. I am using `which-key` version `20161005.1154`. I would be very interested to see if @vibrys can produce the same results by excluding that package. 

 @bmag, I am not sure where to go from here and need some input from someone with more knowledge of this package and its integration into Spacemacs. Perhaps there is some way to disable this package when using ediff? If I can't generate visibility in this old thread I will probably open a new Issue.

**Comment by bmag** [comment]
According to the backtrace provided by @PrgrmAtCeleritas (thank you!), `C-g` was pressed during the execution of `spacemacs/linum-update-window-scale-fix`, which is an `:after` advice of `linum-update-window`, inside `linum-after-scroll` inside the redisplay engine. This suggests that our advice might cause an infinite loop of calling the redisplay engine. `spacemacs/linum-update-window-scale-fix` calls `set-window-margins`, which calls `apply_window_adjustment`, which calls `wset_redisplay`, which might trigger a new redisplay (but I'm not familiar with the code, so take it with a grain of salt). However, I was not able to reproduce the issue even with `dotspacemacs-line-numbers` set to `t` or `relative`. @PrgrmAtCeleritas, can you confirm that the bug is reproducible with `dotspacemacs-line-numbers` set to `nil`, so we can rule it out?

> If I remove the line ediff-window-setup-function 'ediff-setup-windows-plain from defaults

Instead, you can add this line to `user-config`: (it will override Spacemacs' settings)
```elisp
(setq ediff-window-setup-function 'ediff-setup-windows-default)
```
Can anyone else who is facing this problem confirm that setting `ediff-window-setup-function` in `user-config` is a valid work-around?

> I am not sure what the Spacemacs Collaborators want to do about this issue since it is clearly not affecting everyone.

We'd like to fix the issue, of course, but I fear it might take some serious expertise, especially regarding the display engine. Since we barely have a clue of what's wrong, our concern right now is to isolate the cause for the issue as much as possible. Unfortunately I still can't reproduce the issue, so I have to ask you to take on yourself most of the burden of debugging.

Can you reproduce it with spacemacs-base? Change `dotspacemacs-distribution` to `spacemacs-base` and add these layers to ``:
```
spacemacs-completion
spacemacs-layouts
spacemacs-editing
spacemacs-editing-visual
spacemacs-evil
spacemacs-language
spacemacs-misc
spacemacs-purpose ;; only if you're on develop, doesn't exist on master
spacemacs-ui
spacemacs-ui-visual
spacemacs-org
```
This has the same effect as using the default `spacemacs` distribution. Once you've done this, you can start disabling layers (by commenting them out) to test which ones are necessary to reproduce the bug. `which-key` and `ediff` packages belong to `spacemacs-base`, and `evil-ediff` belongs to `spacemacs-evil`, so you might be able to reproduce the bug with only the `spacemacs-evil` layer enabled. Be sure to **change `dotspacemacs-install-packages` to `used-but-keep-unused`** beforehand, so you don't have to reinstall packages every time you change the configuration.

You can also try to reproduce the issue with plain Emacs, `which-key` and `evil-ediff`. This `~/.emacs` file might help:
```elisp
(require 'package)
;; if you use a non-nil `dotspacemacs-elpa-subdirectory':
;; (setq package-user-dir "path/to/elpa")
(package-initialize)

(require 'which-key)
(require 'evil-ediff)

;; which-key configuration goes here
;; ediff configuration goes here
;; evil-ediff configuration goes here
```

@vibrys we would like to hear your feedback as well.

**Comment by vibrys** [comment]
@bmag, the following workaround works ok:
`(setq ediff-window-setup-function 'ediff-setup-windows-default)`

The following does not reproduce the problem. ~/.emacs
```
(require 'package)
(package-initialize)

  (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
  (add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/") t)
  (add-to-list 'package-archives '("elpy" . "https://jorgenschaefer.github.io/packages/"))
(require 'which-key)   ;; I also installed this package of course
(require 'evil-ediff)     ;; the same here
```

Additionally I installed magit.
then
1. restarted emacs
2. started ediff session (from magit, because this one does the reproduction).

No reproduce.

additionally I did
2. M-x ediff-toggle-multiframe    #. this makes ediff control window be part of main frame (ie not the separate one).

no reproduce.

what do You want me to do as next step?

regards

**Comment by bmag** [comment]
@vibrys the `~/.emacs` needs to contain configuration for ediff, which-key and evil-ediff, similar to what Spacemacs has. For example, it needs to set `ediff-window-setup-function` to what Spacemacs sets it. By the way, in normal usage `package-archives` is modified before calling `package-intialize`, but in this case you don't need to change `package-archives` at all. (I assume the packages were already installed by Spacemacs)

If you can't repro with a `~/.emacs`, I'd prefer you try the `spacemacs-base` approach: change `dotspacemacs-install-packages` to `used-but-keep-unused`, change `dotspacemacs-distribution` to `spacemacs-base`, add the `spacemacs-*` layers (they are listed above). This setup should reproduce the bug. Now start disabling (commenting-out) some of the `spacemacs-*` layers, so we know which parts of Spacemacs we can ignore. The goal is to reproduce with `spacemacs-base` and the minimal number of layers. It is possible that you only need the `spacemacs-evil` layer to reproduce the bug. (if this works we can start eliminating packages)

**Comment by vibrys** [comment]
@bmag,

spacemacs-ui-visual ;; problem appears after adding this layer.

**Comment by vibrys** [comment]
@PrgrmAtCeleritas, configuring the following does not help on my config:

   `dotspacemacs-excluded-packages '(which-key)`

version used:
which-key-20161031.1056

There is one thing I don't like though.
Even after I ?disabled? which-key, it is still reachable through M-x find-library. Can it be like that?

**Comment by vibrys** [comment]
@bmag,

Additionally it is enough to enable spacemacs-ui-visual to have problem reproduced, ie. no other packages need to be added to spacemacs-base.

**Comment by bmag** [comment]
@vibrys thank you, the next step is to filter the packages. In the layer list, replace `spacemacs-ui-visual` with: (these are all the packages in that layer)
```elisp
(spacemacs-ui-visual :packages (ansi-colors
                                fancy-battery
                                fill-column-indicator
                                golden-ratio
                                hl-todo
                                neotree
                                popup
                                popwin
                                smooth-scrolling
                                spaceline
                                zoom-frm))
```
The bug should reproduce with this setting. Now start disabling some of these packages (by commenting them out), so we know what packages are needed for the repro.

@PrgrmAtCeleritas can you confirm that the bug reproduces with `spacemacs-base` and `spacemacs-ui-visual`?

**Comment by PrgrmAtCeleritas** [comment]
I can confirm what @vibrys found, I can reproduce the bug with `spacemacs-base` and `spacemacs-ui-visual` only. I dug a little deeper based on the debugging suggestion and the culprit package is `spaceline`. If I comment that package out of `spacemacs-ui-visual` I do not encounter the hang. I would imagine that @vibrys can produce the same result. @bmag, what is our next step? Anything better then a brute force approach to see what part of `spaceline` is causing the issue?

**Comment by TheBB** [comment]
I'm not sure we're looking at the same line here, can you link to it on github?

**Comment by PrgrmAtCeleritas** [comment]
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bspacemacs/spacemacs-ui-visual/funcs.el#L137

**Comment by vibrys** [comment]
@PrgrmAtCeleritas, commenting out the line You mention gets things to work.

**Comment by TheBB** [comment]
I thought that was the line but it's a very odd thing to comment out. I suspect you can achieve the same effect much cleaner by setting `dotspacemacs-mode-line-unicode-symbols` to `nil`.

**Comment by PrgrmAtCeleritas** [comment]
@TheBB, setting `dotspacemacs-mode-line-unicode-symbols` to `nil` works as well.

**Comment by Bost** [comment]
> https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bspacemacs/spacemacs-ui-visual/funcs.el#L137
> If I comment out that line I can get it to work
> 

Doesn't work for me. SRY

**Comment by PrgrmAtCeleritas** [comment]
@Bost, you don't need to byte compile. Have you tried to set `ediff-window-setup-function` to `'ediff-setup-windows-default` or set  `dotspacemacs-mode-line-unicode-symbols` to `nil`?

**Comment by Bost** [comment]
> Have you tried to set `dotspacemacs-mode-line-unicode-symbols` to `nil`?

This does not work.

> Have you tried to set `ediff-window-setup-function` to `'ediff-setup-windows-default`?

But this works: `(setq ediff-window-setup-function 'ediff-setup-windows-default)` Thx!

**Comment by PrgrmAtCeleritas** [comment]
@Bost, what happens if you set `ediff-window-setup-function` to `'ediff-setup-windows-plain` (the Spacemacs default) and exclude the `spaceline` package? Does that address the freezing problem as well?

**Comment by Bost** [comment]
`dotspacemacs-excluded-packages '(spaceline)` with `(setq ediff-window-setup-function 'ediff-setup-windows-plain)` leads to freeze.

**Comment by vibrys** [comment]
I added the following to my user-config(). this leads to freeze. 

`(setq ediff-window-setup-function 'ediff-setup-windows-default)`

Leaving the config untouched (what was the reason of this issue) does not freeze, so it looks like these are two different problems.

More; excluding spaceline while still having the following does NOT freeze.

`(setq ediff-window-setup-function 'ediff-setup-windows-default)`

Currently, I'm testing. I'll get back after a few days.
`(setq dotspacemacs-mode-line-unicode-symbols nil)`

**Comment by azuwis** [comment]
I have the same problem as @vibrys described, spacemacs freezes when `f e D n`.

When

    (setq dotspacemacs-mode-line-unicode-symbols nil)

the problem goes away.

**Comment by agzam** [comment]
@azuwis I have 
`(setq dotspacemacs-mode-line-unicode-symbols nil)` 
yet it still freezes. Hate that!

**Comment by PrgrmAtCeleritas** [comment]
@agzam have you tried `(setq ediff-window-setup-function 'ediff-setup-windows-default)`?

**Comment by SteveJobzniak** [comment]
`(setq dotspacemacs-mode-line-unicode-symbols nil)` freezes for me.

```
$ emacs --version
GNU Emacs 25.1.1
```

From Homebrew on macOS Sierra. With the latest Spacemacs develop branch.

I freeze almost every time I do `<SPC f e D>`...

**Comment by PrgrmAtCeleritas** [comment]
@SteveJobzniak what happens if you exclude the `spaceline` package?

**Comment by SteveJobzniak** [comment]
@PrgrmAtCeleritas How?

I am looking at ~/.emacs.d/layers/+spacemacs/spacemacs-ui-visual/packages.el which is the only thing in the entire source tree that has the words spacemacs-ui-visual. It's not in my .spacemacs.

**Comment by agzam** [comment]
@SteveJobzniak I believe everything prefixed with `spacemacs-` is in included into default distro. @PrgrmAtCeleritas telling you to try adding `spaceline` package into `dotspacemacs-excluded-packages`

**Comment by SteveJobzniak** [comment]
@agzam @PrgrmAtCeleritas Okay... I went into the file I just mentioned, and I commented out the reference to "spaceline" under "spacemacs-ui-visual-packages". Now Ediff works.

Yes, "spaceline" is the problem.

**Comment by agzam** [comment]
@SteveJobzniak Ok. now we need to figure out what the problem is. Obviously you'd like `spaceline` to be included. And btw. I just tried ediffing with the dotspacemacs template and indeed - it frezes

**Comment by SteveJobzniak** [comment]
@agzam This is too strange for me. Before disablign Spaceline, the freezes happened 100% of the time the first time I pressed `<SPC f e D n>` (the n key locked it up).

Then I disabled Spaceline (which made spaceline and powerline packages uninstall) and was able to diff without issues.

Then I re-enabled Spaceline (which made spaceline and powerline packages re-install) and had the bug re-appear. But then a few restarts later I can now diff without issues 90% of the time, but sometimes it freezes...

Sorry I haven't got time for this. I don't know if the "spaceline" clue is correct after all but it certainly changed something massive the first time I disabled it. Before that, I could never diff at all (it died instantly every time).

**Comment by agzam** [comment]
I've created issue upstream https://github.com/TheBB/spaceline/issues/123
hope @TheBB would be able to investigate. This has been very mysterious and frustrating bug.

**Comment by SteveJobzniak** [comment]
I felt bad, so I decided to do the "full reset" test anyway, to see if I can make the bug re-appear:

```bash
rm -rf ~/.emacs.d
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
cd ~/.emacs.d
git checkout develop
```

Waited a few minutes for it to download and rebuild all packages...

I know packages aren't properly loaded now. So I hit `<SPC f e D n>` and it **INSTANTLY FROZE**.

Then I restarted Emacs to let all new packages load properly.

Hit `<SPC f e D n>`... and it worked for about 10 steps... Then it **froze**.

Then I restarted Emacs again...

Hit `<SPC f e D n>`... and it worked... no problems.

No idea what's going on here or why it's so intermittent.

**Comment by agzam** [comment]
What if we try to disable spaceline *everytime* we go to Ediff? `SPC t m T`?

**Comment by PrgrmAtCeleritas** [comment]
That's a really interesting thought @agzam. We could add the disable to `ediff-before-setup-hook` And renable after `ediff-quit-hook`. I will try that tomorrow.

**Comment by SteveJobzniak** [comment]
@PrgrmAtCeleritas @agzam Clever idea. If that solves it, then it's worth doing.

**Comment by PrgrmAtCeleritas** [comment]
So I uncovered something really interesting while doing some testing with the mode-line this morning. I can cause or prevent the issue by changing my `powerline-scale` in `dotspacemacs-default-font`. if it is at `1.1` it works fine and if it is at `1` it freezes. I have `(setq dotspacemacs-mode-line-unicode-symbols t)` and `(setq ediff-window-setup-function 'ediff-setup-windows-plain)` both set. I would be curious if others can achieve the same results by varying their `powerline-scale`. Pick a good range of values.

**Comment by PrgrmAtCeleritas** [comment]
also the adding 
```
  (add-hook 'ediff-before-setup-hook 'spacemacs/toggle-mode-line-off)
  (add-hook 'ediff-quit-hook 'spacemacs/toggle-mode-line-on)
```
does not seem to fix the problem and only toggle the mode line back on for 1 window if there are more then one.

**Comment by SteveJobzniak** [comment]
@PrgrmAtCeleritas My own powerline scale is 1.3 and I use utf8 separators and the source code pro font. Just throwing this out there to let you know 1.3 crashes. I have not tried 1.1.

So the scale may be a false lead. Unless you have fully tested for hours to ensure that powerline scale 1.1 is fully stable. The intermittent nature of the file and the time it takes to verify config changes is why I don't have time to test.

**Comment by agzam** [comment]
@PrgrmAtCeleritas I have `:powerline-scale 1.1` and it still sometimes freezes. So that's not the cause.

**Comment by PrgrmAtCeleritas** [comment]
I think it also depends on the font. Some fonts are fine with 1.1 and others are not. At least in my testing.

**Comment by SteveJobzniak** [comment]
@PrgrmAtCeleritas I would be careful about assuming things like that. This bug is extremely random (probably a race condition somewhere). So you can go for hours without seeing it and then suddenly it happens again.

I was just editing a diff with magit and ediff and had no problem for 20 minutes, then it froze.

For now I will type "w c" (write buffer C to disk) a lot to save my work as I progress through the file.

**Comment by PrgrmAtCeleritas** [comment]
Very consistent for me. When I have created a condition where it will freeze I make it freeze every single time. Seems to be the same for the others as well. You are the only one that has mentioned inconsistency.

**Comment by SteveJobzniak** [comment]
Well yeah it isn't consistent for me. `<SPC f e D n>` froze **every time** _90% of the time_. ;)

**Comment by PrestanceDesign** [comment]
Hi !

I'm Spacemacs user about 1 month and the ediff freezing bug are the only things is annoying me a lot and that I had to take time to fix on my todo list .
Whenever I used ediff, I would squeeze the buttocks :)

I don't have tested more than 1 hour but `toggle-mode-line-off` seems the best workaround...this keeps same windows positions, doesn't touch modeline unicode, etc.

```lisp
  (add-hook 'ediff-before-setup-hook 'spacemacs/toggle-mode-line-off)
  (add-hook 'ediff-quit-hook 'spacemacs/toggle-mode-line-on)
```

Thx !

**Comment by SteveJobzniak** [comment]
@PrestanceDesign Cool. Is that 100% a solution against the hangs?

**Comment by PrestanceDesign** [comment]
@SteveJobzniak Yes that seems. Yesteday afternoon, only one freeze when I ediff a local file against this remote version via this package https://github.com/cjohansson/emacs-ssh-deploy.
I guess, I must adapt the hook when I ediff with this tool.

I'll see on a longer use this week to see if this fix fixes that at 100% and keep you up to date.
Have a nice day !

**Comment by SteveJobzniak** [comment]
@PrestanceDesign Cool, thanks for the information! 👍

**Comment by Apakollaps** [comment]
I have been going crazy from ediff freezes for a long time now, too bad I failed to find this issue earlier. I work mainly with hg repos, but from what I've read so far it's not git-related. 

Toggling the mode line did not work for me, but excluding package `spaceline` did (so far at least...).

Guess I have to live with the uglier mode line for now, cheers everyone for your efforts!

**Comment by Apakollaps** [comment]
Toggling the mode line did not do the trick, unfortunately. Locks became much more rare, but didn't take long for a lockup to happen. Disabling `spaceline` altogether (as described in one of the comments) seems to do the trick.

**Comment by agzam** [comment]
It's definitely happens less often than it used to. It just froze when I tried to  search in ediff middle window.

**Comment by agzam** [comment]
goddamit... ediff has become just completely unusable... can't do anything anymore... try for example resizing one of the windows... sigh... whoever finds nice workaround I'll send them nice bottle of scotch.

**Comment by CeleritasCelery** [comment]
@agzam Does disabling `spaceline` not do the trick?

**Comment by duianto** [comment]
I'm unable to reproduce the crash or freezing in Ubuntu 16.10
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. a213729)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git org version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES XWIDGETS LIBSYSTEMD

It's running in virtual box with windows 10 as the host, if that could be preventing the crash some how. It doesn't happen in windows 10 either, but the reports here are for Linux, so it might not be relevant, but it's another data point:

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. a2137299)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey markdown ranger emacs-lisp git github helm org syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by CeleritasCelery** [comment]
This is a "works fine for some people" issue. I think it is system dependent as best I can figure.

**Comment by agzam** [comment]
@CeleritasCelery yup, it might be affecting only Mac users. My Linux laptop not with me right now. Can't confirm if that breaks there.

**Comment by yatesco** [comment]
I am still seeing hard locks on macos High Sierra running latest develop.

**Comment by braham-snyder** [comment]
Have you tried adding the following to `dotspacemacs/user-init` (note that -- unintuitively -- setting this in `dotspacemacs/user-config` will succeed at setting this variable to `nil`, but will **not** have any other effects whatsoever)?

`(setq dotspacemacs-mode-line-unicode-symbols nil)`

In the unlikely event that that trick does not avoid the freezes, you might try double checking whether your mode-line includes any unicode *after* it has already frozen (since some unicode symbols are only conditionally displayed, like workspace numbers -- which incidentally also happens to make `dotspacemacs-mode-line-unicode-symbols`'s above quirk more difficult to catch).

**Comment by marcoslhc** [comment]
Still happening to me 100% of the time. I've tried disabling spaceline, mode-line and setting `dotspacemacs-mode-line-unicode-symbols` to `nil` to no avail.
It happens in master and develop
Also Spacemacs won't load my settings well (like color scheme) Now it's practically unusable.
#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f3b6a22c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(haskell helm emacs-lisp git markdown html react javascript clojure common-lisp csv php ruby typescript vimscript go yaml java nginx docker ansible vagrant osx colors git github themes-megapack)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by braham-snyder** [comment]
@marcoslhc where did you change `dotspacemacs-mode-line-unicode-symbols`? Unintuitively -- setting this in `dotspacemacs/user-config` (or interactively, after starting Spacemacs) will succeed at setting the variable to `nil`, but will not fix the issue.

Did you already try changing the line in `dotspacemacs/init` that sets `dotspacemacs-mode-line-unicode-symbols` to `t`? If you change that existing line in your dotfile (or at least the default dotfile) to instead set the variable to `nil`, then it ought to work (because only then will it be modified early enough during startup to take effect).

If that does not work (after a restart), and `toggle-debug-on-quit` -> "C-g" still gives:

```
Debugger entered--Lisp error: (quit)
redisplay_internal\ (C\ function)()
```

My best guess is that you have unicode symbols somewhere else that are causing issues -- maybe a file tree plugin that displays file icons, or something?
