### ISSUE TITLE
react mode shouldn't assume attribute values are always strings

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#4734]
In react mode when you type `<Elem attr=` there's some autocompletion involved and you end up with `<Elem attr=""` with the cursor placed between the quotes. This is fine if you're writing html but when writing react the chances of the value being a javascript expression (i.e. `<Elem attr={expr}`) instead of fixed string are quite high, so I think it would be better to insert the closing quote/paren only _after_ the opening one has been entered.

**Comment by TheBB** [comment]
This is due to us having react-mode derived from web-mode.

I'm not a javascripter but I'm increasingly of the opionion that we should have react rely on js2-jsx-mode instead.

**Comment by TheBB** [comment]
I'm closing this and moving the discussion to #4735, because this is really about more than just attributes and strings.

**Comment by tko** [comment]
*shrug* if you say so. FWIW I find react mode is mostly working just fine where it counts (indent + eslint) except for this case of treating jsx as html that's getting in the way a little bit.

**Comment by TheBB** [comment]
Okay, I can reopen then.

**Comment by TheBB** [comment]
To fix this you would have to set `web-mode-enable-auto-quoting` to `nil` in `react-mode`.

**Comment by TheBB** [comment]
Sorry for jumping the gun. Can you try #4744?

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
