### ISSUE TITLE
React layer implementation

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#4735]
Currently the react layer is implemented as a thin wrapper around web-mode. This causes some surprising behaviour: https://github.com/syl20bnr/spacemacs/issues/3661 and https://github.com/syl20bnr/spacemacs/issues/4734 among others.

Alternative implementations are available. It's not clear to me what the best choice is but I invite all the javascript and react people here to discuss. It would be good to solve this problem since react is evidently quite popular.

**Comment by robbyoconnor** [comment]
Yeah this is one of those problems -- and why I was kinda against this change to begin with...Why are we treating React differently than say Angular?

**Comment by jasoncyu** [comment]
Just going to copy an earlier comment summarizing pros/cons of the different modes:

### React
- formatting works well
- snippets uses web-mode so getting log to be console.log is annoying
- eslint works
- comments are just <!--

### Web-mode
- eslint doesn't work.
- snippets aren't js.
- comments work very well
- formatting works well

### js2-jsx
- eslint works well
- formatting is off, I get spaces added to multiline jsx tags
- snippets are awesome.
- comments work but they are only // so not as nice as web-mode

**Comment by robbyoconnor** [comment]
Why not fix the deficiencies upstream ?

--Rob

**Comment by TheBB** [comment]
I'm assuming [this](https://github.com/mooz/js2-mode/issues/291) patch would fix the formatting problem of js2-jsx-mode?

**Comment by TheBB** [comment]
Why do comments work well in web-mode but not react-mode, when react-mode is derived from it?

**Comment by TheBB** [comment]
Someone correct me if I'm wrong, but I just tried our built-in react mode, and I do get javascript snippets ([as I should](https://github.com/TheBB/spacemacs/blob/develop/layers/+frameworks/react/packages.el#L77)) and I also can't reproduce https://github.com/syl20bnr/spacemacs/issues/3661. I seem to get correct comments.

So… are there any problems at all here?

**Comment by kristian-puccio** [comment]
I've just tried it again with a freshly updated develop branch and it's working for me as well.

The only thing that would be nice is for the snippets to use javascript mode but other than that it's quite nice.

Thanks for looking into it!

**Comment by jasoncyu** [comment]
@TheBB I didn't get js snippets by react-mode by default, so I used .yas-parents to link react-mode to js2-mode.  Also, you get JS comments and not HTML comments when using `SPC c l` in buffers in react-mode?

**Comment by jupl** [comment]
A problem I have with `web-mode` is that writing JS code without semicolons always causes indentation and the author has stated many times it is something that will not be fixed.

**Comment by CestDiego** [comment]
can we have a react-mode that is a melpa package as well? it would help greatly. The creator of the layer should be the one that creates the package..it would be wonderful.

**Comment by robbyoconnor** [comment]
Did any of you see [reagent](https://github.com/reagent-project/reagent)? It's probably easier to work with than react-mode being in Clojurescript

**Comment by CestDiego** [comment]
Sure, it's easier and cooler. But what matters now is that things work :) . Clojure has good support for reagent as well.

**Comment by robbyoconnor** [comment]
:-)

**Comment by shangsunset** [comment]
I dont know any emacs-lisp but there is one thing i wish react layer could do better, which is being able to identify jsx syntax in `.js` file and turn on react mode automatically. 

the mechanisms for it in react layer is rather simple.
https://github.com/TheBB/spacemacs/blob/develop/layers/+frameworks/react/packages.el#L66-L70

Nowadays,  most people name their files in react or react native project with `.js` extension, instead of `.jsx` or `.react.js`.  also pragma `/** @jsx React.DOM */` is already deprecated in React 0.12.

**Comment by tko** [comment]
That's a pretty good idea @shangsunset. Not so sure about the "most" but for the few projects I've been working on I've just manually run `(add-to-list 'auto-mode-alist '("\\.js\\'" . react-mode))` once and forgot all about it.

As someone knowing very little about emacs lisp but a little about react I think this might work if you're using ES6 imports:
```elisp
(add-to-list 'magic-mode-alist '("^import React" . react-mode))
```

**Comment by joefiorini** [comment]
@TheBB I'm curious what you were referring to when you said:

> I also can't reproduce #3661. I seem to get correct comments.

When I'm in a `react-mode` file, if I hit `gcc` to comment a line, here's what I end up with:

![screen shot 2016-02-26 at 9 33 26 am](https://cloud.githubusercontent.com/assets/3648/13360048/08ef9362-dc6c-11e5-989c-d70e25453cef.png)

I would expect to see normal `// ` comments instead. If I switch to `web-mode` I get:

![screen shot 2016-02-26 at 9 35 00 am](https://cloud.githubusercontent.com/assets/3648/13360093/4498273a-dc6c-11e5-9e8e-3c567175137d.png)

I'd be fine if `react-mode` gave me that instead. Is this different from the behavior you see?

**Comment by TheBB** [comment]
Yep. Here's what I see when trying `gcc` and `SPC c l`.

https://vid.me/ILuA

**Comment by robbyoconnor** [comment]
Shouldnt this have the React tag?

**Comment by robbyoconnor** [comment]
Shouldn't this have the React label?

**Comment by robbyoconnor** [comment]
I think it also needs the Kills kitten label -- a few kittens are dead now. May be related to this, may not be.

**Comment by TheBB** [comment]
Closing in favor of https://github.com/syl20bnr/spacemacs/issues/5848.

**Comment by robbyoconnor** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67og6-e3&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=Htfbk4j1&invitationId=6130896986494287873








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67og6-e3&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGzuBS6URy93AAAAVRVSblfkHvK-NL_zXnePJAjrbbDRgxcKBgWM90bpROWG-QfeJSlrr7lZIwSn6P6OJ7m7ZpCtC9vCBEA1MRkclvPlO2AIUSZIhCuaLV6Vh6ieIvDATK0aJJM1GA3ALgJKfPQuiG5tz4GZnPHY0NmNefpTXPrwgxcqMGZmvczumCF1c0zJLXT&eid=0-ini67og6-e3


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67og6-e3&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
