### ISSUE TITLE
yapf on save not working

### ISSUE THREAD

**Issue by elvis-sik** [syl20bnr/spacemacs#4739]
I have `python-enable-yapf-format-on-save t` on my `.spacemacs`. It worked like a charm for quite some time. A few days ago it stopped automatically formatting my Python code on save.

I do not know if it was right after I upgraded everything through `Update packages` and `$ git pull --rebase`. I ran those commands again and it did not come back.

If I try `SPC ! yapf` there is no error message (as opposed to calling something like `SPC ! foo` which gives me `command not found`). Also, I can call `yapf foo.py` on the command line and it works as expected.

**Comment by robbyoconnor** [comment]
Is it on PATH properly, like can emacs see it?

**Comment by elvis-sik** [comment]
The fact that I can call it with `SPC ! yapf` doesn't show that? If not, how can I be sure?

**Comment by robbyoconnor** [comment]
weird -- are you using pyenv? what's your setup like?

**Comment by isphinx** [comment]
+1

**Comment by nixmaniack** [comment]
It looks like it got removed while removing deprecated extension functionality of layers and wasn't added in packages.el. 

https://github.com/syl20bnr/spacemacs/commit/33ead6fc42700a6000ef10a662ceff604f3f8e51#diff-3ec6308f6e383f33d1b217f51ded05a4L69

**Comment by TheBB** [comment]
Okay, so all we have to do is add that function back. Beginner friendly. :-)

**Comment by TheBB** [comment]
Fixed in https://github.com/syl20bnr/spacemacs/commit/0f5d576ada2c751ba7238f949519f122bfde09dd

**Comment by syl20bnr** [comment]
Oops thank you ;-)

**Comment by elvis-sik** [comment]
Thanks indeed!!! :dancer: viva spacemacs! hahaha
