### ISSUE TITLE
Spacemacs hangs with "making tags completation table" message

### ISSUE THREAD

**Issue by javierholguera** [syl20bnr/spacemacs#4747]
Related to this issue: https://github.com/syl20bnr/spacemacs/issues/3850

#### Description
Spacemacs hangs shortly after starting using it. The only visible message is, on the bottom:
"Making tags completion table for /Users/myuser/project/TAGS"

#### Reproduction guidee
1. Starts spacemacs
2. Open some files in a project
3. Edit something
4. Spacemacs hangs with previously explained message

#### Solutions discarded
- CTRL+G doesn't do anything
- Deleting TAGS file doesn't help. It generates it again, empty in all cases
- Project is really small (clojure koan exercise), so nothing to try there
- Waiting more doesn't help, I've waited more than 15 minutes without changes

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion clojure emacs-lisp osx)
```

**Comment by syl20bnr** [comment]
Do you have the prerequisite necessary to generate those tags ? Do you know the command line and can you try it in spacemacs in a term buffer ?

If the questions seem dumb for you sorry about this, I just try to gather more info.

**Comment by javierholguera** [comment]
It started using emacs / spacemacs last week, so I don't really know how these tags are internally generated. I'm using spacemacs as it is out-of-the-box, apart from enabling some extra layers.

How can I find out the answer to your questions?

One more thing that may be relevant is I've been using Vim with Exuberant Tags until recently. I don't know if spacemacs may be expecting to find a different tags generator than the one installed in my machine, or something similar.

**Comment by javierholguera** [comment]
Reinstalled the whole thing and had been working fine since that, so closing the ticket.

**Comment by StreakyCobra** [comment]
Glad to hear!

As you opened the issue and no collaborator closed/reopened it in the meantime, you normally should be able to close it :-)

Anyway, closing it as requested :+1:

**Comment by sulami** [comment]
So I have been experiencing the same problem, Spacemacs 0.105.12, Emacs 24.5.1. Opening a brand new Clojure project (created bei lein) and editing anything kicks of autocompletion which hangs the whole editor. I am able to abort autocompletion by holding C-g for a second or so though.

**Comment by blazeeboy** [comment]
I have the same problem now, installed spacemacs today working fine for couple hours, half an hour ago and it was suffering from this issue.

I'm working on rails project, not a small one (several thousand files), while editing a controller it hang and try to generate TAGS, I have Autocomplete layer enabled also i'm using these layers:
this is my `.spacemacs` file 
https://gist.github.com/blazeeboy/5de9e9bf0847f4054b560fe96f50ae54

sometimes it gets back to work when i press C-g for long time, and sometimes it doesn't, also when I was working on spec files it didn't happen, the time I started working on controllers it stopped working.

**Comment by blazeeboy** [comment]
This problem appear from time to time, can someone help me debug/trace the source of annoyance?

**Comment by StreakyCobra** [comment]
You'll get more help by opening a new issue following [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) probably :-)

**Comment by blazeeboy** [comment]
thank you, I will
