### ISSUE TITLE
cursor left/right in /? search mode broken

### ISSUE THREAD

**Issue by newhook** [syl20bnr/spacemacs#4749]
emacs version: GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.3.0, NS appkit-1347.57 Version 10.10.3 (Build 14D136)) of 2015-05-23 on may
spacemacs version: 0562f050b4b56470dc68744667794b20abe9570a

If I press /? to search enter some text cursor left/right terminates the search.

**Comment by StreakyCobra** [comment]
It would be nice if you can update your comment by following this [explanation](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) :-)

**Comment by newhook** [comment]
Updated, let me know if anything is unclear.

**Comment by StreakyCobra** [comment]
What would help us them most is not only the versions information, but also the output of `SPC h d s` and reproduction steps. The best is to use the template provided in the page I linked. Look at #4707 for an example of issue following the template :-)

**Comment by newhook** [comment]
#### System Info
- OS: darwin
- Emacs: 25.0.50.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go osx auto-completion better-defaults emacs-lisp git markdown org
    (shell :variables shell-default-height 30 shell-default-position 'bottom)
    spell-checking syntax-checking version-control)
```

The reproduction steps are exactly as I said:

press / to enter search.
Type some stuff, press cursor left and I get kicked out of search back into the buffer.

**Comment by TheBB** [comment]
You can type `M-e` to edit the search string in the minibuffer, and then `RET` to resume incremental search.
