### ISSUE TITLE
Is there any way to set the default mode for different filetype ?

### ISSUE THREAD

**Issue by scarletsky** [syl20bnr/spacemacs#4751]
In my case, I works on javascript projects, and some projects are related to `react`, and some are not.

In `react` projects, everytime I open the file(js) with spacemacs, it set `web-mode` by default, and I need to change to `react-mode`. It is inconvenience.

So I am wondering to know that is there any to set the default mode for different filetype?

**Comment by TheBB** [comment]
That's what `auto-mode-alist` is for.

> auto-mode-alist is a variable defined in `files.el'.
Its value is shown below.

  This variable may be risky if used as a file-local variable.

> Documentation:
Alist of filename patterns vs corresponding major mode functions.
Each element looks like (REGEXP . FUNCTION) or (REGEXP FUNCTION NON-NIL).
(NON-NIL stands for anything that is not nil; the value does not matter.)
Visiting a file whose name matches REGEXP specifies FUNCTION as the
mode function to use.  FUNCTION will be called, unless it is nil.

**Comment by scarletsky** [comment]
I see, thanks for your information!
