### ISSUE TITLE
OS X Deleting files/directories works in GUI but not terminal

### ISSUE THREAD

**Issue by rteabeault** [syl20bnr/spacemacs#4752]
In OS X using the emacs mac port I am unable to delete a directory if I opened emacs in a terminal. However it works fine if using the GUI.

`brew install emacs-mac`
`brew install trash`
1. Open emacs GUI 
2. Open a dired buffer and try to delete a file/directory
3. Success
4. Open emacs in the terminal
5. Open a dired buffer and try to delete a file/directory
6. Fails with error `(file-error Removing old name Mac error -1700 /Users/some/path/some/dir)`
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. a15f0f9)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp elixir erlang git markdown osx org syntax-checking themes-megapack version-control)
```

**Comment by lzulauf** [comment]
This looks related to https://github.com/syl20bnr/spacemacs/issues/4125

**Comment by StreakyCobra** [comment]
@rteabeault Can you try the solutions proposed in the linked PR and let us know if it works?

**Comment by rteabeault** [comment]
I already have installed trash via brew and that does not fix the problem.
I removed the `osx` layer and that fixes the problem. But that does not seem like a valid solution.

**Comment by StreakyCobra** [comment]
@rteabeault I was speaking about [this](https://github.com/syl20bnr/spacemacs/issues/4125#issuecomment-169006740) solution in the thread.

**Comment by rteabeault** [comment]
Is that not the same as the second thing I listed? Remove the `osx` layer and restart? If so then yes. After removing the `osx` layer and restarting it works fine.

**Comment by StreakyCobra** [comment]
They did more than this:

1. Remove the `osx` layer
2. Exit Spacemacs
3. Start Spacemacs
4. Perform a package update (`[Update packages]` button on the welcome screen)
5. Exit Spacemacs
6. Start Spacemacs
7. Re-enable `osx` layer
8. Exit Spacemacs
9. Start Spacemacs

And it may/should work.

**Comment by lzulauf** [comment]
@StreakyCobra That's just the steps needed to perform a package update if you have the osx layer. Basically the osx layer prevents deletions from working properly, so you have to temporarily disable it whenever you need to delete something. Those are not steps to fix the problem.

**Comment by rteabeault** [comment]
Yes, disabling the osx layer allows the deletes to work correctly. But as @lzulauf implied, that does not seem like a good workaround.

**Comment by StreakyCobra** [comment]
Ok, sorry for the bad understanding, I went a little bit too fast on the reading.

**Comment by rteabeault** [comment]
To get around this problem I am added the following to `dotspacemacs/user-config`:

  `(setq mac-system-move-file-to-trash-use-finder nil)`

**Comment by StreakyCobra** [comment]
Interesting, it's a worthwhile information for all people having this `-1700` issue, thanks!

**Comment by shanesveller** [comment]
@rteabeault That variable didn't appear to help my issues under Spacemacs 0.105.11 - I still get the same behavior as described in #4125 and this issue.
