### ISSUE TITLE
Add key binding for the `follow-mode`

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#4753]
The [`follow-mode`](http://www.gnu.org/software/emacs/manual/html_node/emacs/Follow-Mode.html) is a really neat Emacs feature that's often overlooked.  I propose adding binding for it into the Spacemacs core.
```elisp
  ;; toggle follow-mode
  (evil-leader/set-key "wf" 'follow-mode)
```

**Comment by StreakyCobra** [comment]
:+1: Nice find! It is a good opportunity to start contributing to Spacemacs. If you feel motivated, please read our [contributions guidelines](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org) and open a PR with this change :smile: If not, just let us know and we will do it on our side :relaxed:

PS: If you do it, don't forget to document the keybinding.

**Comment by JAremko** [comment]
Challenge accepted! :muscle:

**Comment by robbyoconnor** [comment]
@JAremko that's a way to do it -- dig in and help the community
