### ISSUE TITLE
ipython-notebook layer error compiling ein-jedi while installing 

### ISSUE THREAD

**Issue by jbmorgado** [syl20bnr/spacemacs#4759]
When installing `ipython-notebook` layer you get the compilation error:
`ein-jedi:31:1:Error: Symbol's value as variable is void: ein-direct`

**Comment by TheBB** [comment]
That's an error in `ein-jedi`. You should probably report it there.

**Comment by AlejandroCatalina** [comment]
I just sent a PR upstream and it solved my local case, hope it helps.

https://github.com/millejoh/emacs-ipython-notebook/pull/87

**Comment by millejoh** [comment]
Okay, just saw this. Thanks to some youthful indiscretions with Common Lisp I have a mild allergic reaction to the use of `eval` in code, but I don't see any true issue merging this in as is (at least it doesn't seem to break anything).

**Comment by AlejandroCatalina** [comment]
Yeah, it doesn't break anything and it turned to solve the issue, that's why I PR it. Thanks @millejoh !
