### ISSUE TITLE
pyenv seems miss one situation

### ISSUE THREAD

**Issue by scloudyy** [syl20bnr/spacemacs#4760]
When visit a .py file whose parent dir has .python-version pyenv can set local python version automaticly. But if there is no .python-version, just use global version, pyenv will not change to global version when switch from a buffer that has .python-version.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.3
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. 44fd52d)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(spacemacs-ivy spacemacs-helm better-defaults github semantic markdown org search-engine
               (syntax-checking :variables syntax-checking-enable-tooltips nil syntax-checking-enable-by-default t)
               (spell-checking :variables spell-checking-enable-by-default nil)
               python emacs-lisp ycmd gtags
               (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
               (ibuffer :variables ibuffer-group-buffers-by 'projects)
               (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
               (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup nil)
               (shell :variables shell-default-height 50 shell-default-shell 'eshell shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
               (chinese :variables chinese-default-input-method 'pinyin chinese-enable-youdao-dict t chinese-enable-fcitx t)
               prodigy ranger spacemacs-layouts extra-langs fasd pandoc
               (elfeed :variables rmh-elfeed-org-files
                       (list "~/.spacemacs.d/elfeed.org"))
               deft
               (clojure :variables clojure-enable-fancify-symbols t)
               scloudyy)
```

First visit a py file whose parent dir has a .python-version, maybe 3.5.0,and pyenv will set version to 3.5.0, and then switch to a py file does not have .python-version in parent dir , for instance, in HOME, just use the global version(global version is different from 3.5.0), and at this time, pyenv version will not change to the global version, still 3.5.0
@fbergroth @cpaulik

**Comment by robbyoconnor** [comment]
Hi there, thanks for your report please follow the template here: https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report

**Comment by scloudyy** [comment]
I am sorry for that, I have already updated the description. @robbyoconnor

**Comment by robbyoconnor** [comment]
This information is helpful to us

**Comment by cpaulik** [comment]
Should be solved after https://github.com/syl20bnr/spacemacs/pull/4764 this is merged

**Comment by cpaulik** [comment]
This discussion raised an interesting point. We actually slightly overmanage `pyenv` since it would automatically find the correct version because of how it uses shims. The only thing not changing correctly is anaconda mode. But it might be possible to remove all the management code and replace it by a simpler function that only restarts anaconda mode if necessary.

**Comment by cpaulik** [comment]
After trying this and the https://github.com/syl20bnr/spacemacs/pull/4764#issuecomment-174623642 from @fbergroth I don't think that this is really possible without some bigger effort. The commit that "fixed" this should be reverted since it effectively broke jump to definition. I've made https://github.com/syl20bnr/spacemacs/pull/4809 for that.
