### ISSUE TITLE
error occured when trigger html in dotspacemacs/layers

### ISSUE THREAD

**Issue by derekcn** [syl20bnr/spacemacs#4762]
*Error (use-package): web-mode post-:config hook: Symbol's function definition is void: sp-local-pair*

it seems sp-local-pair can not be called.

**Comment by TheBB** [comment]
What's your Spacemacs version? Can you post the output of `SPC hds`?

**Comment by derekcn** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.104.8
- Spacemacs branch: master (rev. 44d4525)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion emacs-lisp
                 (python :variables python-test-runner 'pytest)
                 racket go gtags git html javascript ycmd version-control
                 (colors :variables colors-enable-nyan-cat-progress-bar t)
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
                 (chinese :variables chinese-enable-youdao-dict t chinese-enable-fcitx t))
```
My os is debian 8

**Comment by TheBB** [comment]
> Spacemacs: 0.104.8

I suspected as much. Please upgrade to the latest version. This has been fixed.

**Comment by derekcn** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.104.8
- Spacemacs branch: master (rev. 44d4525)
- Distribution: spacemacs
- Layers:
```elisp
(auto-completion emacs-lisp
                 (python :variables python-test-runner 'pytest)
                 racket go gtags git html javascript ycmd version-control
                 (colors :variables colors-enable-nyan-cat-progress-bar t)
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
                 (chinese :variables chinese-enable-youdao-dict t chinese-enable-fcitx t))
```
thanks, i have upgraded spacemacs, it seems 0.104.8 is the latest version. i don't understand is there anything wrong?

**Comment by StreakyCobra** [comment]
@derekcn Last version is [`0.105.9`](https://github.com/syl20bnr/spacemacs/releases/tag/v0.105.9).

**Comment by derekcn** [comment]
git pull --rebase to get the latest version ?

**Comment by StreakyCobra** [comment]
Yes, but it may depend on you setup also (like if you changed to another branch, changed remotes, fork the original spacemacs, etc.)

**Comment by derekcn** [comment]
thx all, i update to 0.105.9 and there is no error.
