### ISSUE TITLE
Spacemacs logo not showing on startup

### ISSUE THREAD

**Issue by kmmankad** [syl20bnr/spacemacs#4767]
I just installed Spacemacs version **spacemacs-0.105.9** and have **emacs24.5.1** . Installation was smooth, except for libpng16, which I installed into /usr/local/lib and all was okay.

However, upon launching 'emacs', the startup screen does not have the logo, instead an empty rectangle.

![Screenshot](http://i.imgur.com/1V3jPCq.png?1)

**Comment by kmmankad** [comment]
Forgot to mention that dotspacemacs-startup-banner is set to official  
> dotspacemacs-startup-banner 'official

**Comment by kmmankad** [comment]
Found the issue - In the Messages buffer I see - 
PNG warning: Application built with libpng-1.2.50 but running with 1.6.21 [5 times]

**Comment by kmmankad** [comment]
This is because I installed spacemacs when I was on emacs 24.3, and then upgraded emacs to 24.5.1 because of the helm related error:
> **Error (use-package): helm pre-:config hook: Symbol's function definition is void: helm-flx-mode**
This [stackoverflow thread](http://stackoverflow.com/questions/34871974/spacemacs-installation-git-gutter-and-helm) advised updating emacs, and so I downloaded 24.5 from their FTP and built the source code and installed it.

During the emacs upgrade, I installed libpng16 as well. I think I might need to reinstall spacemacs.

**Comment by TheBB** [comment]
This appears to be just a mismatch in libraries for your Emacs build. Is there anything for us to do here?

**Comment by kmmankad** [comment]
Thanks for the prompt response guys. Anything I can do to fix this?

**Comment by StreakyCobra** [comment]
The problem is on the emacs installation on your side. You need to get emacs (or to build it) in a way it uses the correct linpng version.

**Comment by kmmankad** [comment]
Thanks. I did the following and things are fine now - I can see the PNG logo on the core-spacemacs-buffer.

> cd ~/Downloads/emacs*/ && make uninstall
> sudo apt-get install emacs24
