### ISSUE TITLE
[org-calendar] M-h keybinding doesn't work

### ISSUE THREAD

**Issue by mskorzhinskiy** [syl20bnr/spacemacs#4769]
How to reproduce:

1) Open org file;
2) Try to insert date, like pressing `SPC m .` or `C-c .`;
3) Try to hit M-h;
Expected: cursor will go to the previous day.
Reality: cursor stay at place.

Since this keybinding is working for some spacemacs users, there my .spacemacs file. I deleted from there some personal stuff like mail configuration and paths to a local filesystem, because I don't expect that this have any impact to the reproduction of problem.

[dotspacemacs.txt](https://github.com/syl20bnr/spacemacs/files/101969/dotspacemacs.txt)

**Comment by dilzeem** [comment]
Did you ever find out what was wrong? I am trying to figure it out as well.

**Comment by d12frosted** [comment]
Hey @mskorzhinskiy 

What do you mean by `2) Try to insert date, like pressing `? What exactly do you press? `C-c .`?

> Since this keybinding working for somebody

Could you elaborate on 'somebody'. Is somebody is Spacemacs user or non-Spacemacs user?

**Comment by mskorzhinskiy** [comment]
Oh, sorry for the delay.

> What do you mean by `2) Try to insert date, like pressing`? What exactly do you press? `C-c .`?
I mean try to insert some date with a calendar. For example `C-c .`, yes.

> Could you elaborate on 'somebody'. Is somebody is Spacemacs user or non-Spacemacs user? 
Spacemacs user. I'm not confident about when and who told me that it's everything OK with M-h, but I'm sure that was spacemacs user.

 > Actually try SHIFT - RIGHTARROW. The SHIFT and ARROW keys change the date. For org-capture anyway.
Shift + arrows are the default calendar keybindings. The point is that current keybinding with M-h is not working.

**Comment by d12frosted** [comment]
@mskorzhinskiy to be honest, I have never heard anything about `M-h` key bindings for shifting date. And I even don't understand what exactly you expect from `M-h` (I mean, how exactly should it change the date?).

**Comment by mskorzhinskiy** [comment]
The PR https://github.com/syl20bnr/spacemacs/pull/3856 introduces evilified key bindings for the calendar, such as `M-h`, `M-l` and so on. Everything but `M-h` is working.

**Comment by bmag** [comment]
I started using Org more seriously this week. In the calendar prompt I intuitively tried `M-h` and I can confirm that it doesn't do anything. I checked with `C-h c` and found that `M-h` is bound to `company-quickhelp-manual-begin`. After disabling `company-quickhelp-mode` manually, `M-h` works as expected. The problem is that `company-quickhelp-mode` is a global mode, but I want it to be activated in some modes and not in others (e.g. in the minibuffer). I think that should be possible by using a globalized minor-mode, perhaps we should report upstream at company-quickhelp.

**Comment by bmag** [comment]
Temporary work-around is to unbind `M-h` in `comapny-quickhelp-mode-map`
```elisp
(define-key company-quickhelp-mode-map (kbd "M-h") nil)
```

I think as a permanent solution we can unset `M-h` in `company-quickhelp-mode-map` and set it in `company-active-map` instead, since this bindings is only useful while Company popup is active.

**Comment by d12frosted** [comment]
Ok, I didn't know anything about `M-h` (and still don't quite understand how it works - I mean, how exactly it shifts the date). Thanks for information about upstream change. Now I can safely remove unbind call in my dotfiles, as I use `M-h` to hide Emacs to be consistent with OS X :D

**Comment by mskorzhinskiy** [comment]
If the `M-h` causing the problems, may be it is worth to change to something different? Like `C-<hjkl>`?

**Comment by bmag** [comment]
> If the `M-h` causing problems

It doesn't cause problems anymore, all you need to do is update the package `company-quickhelp-mode`. I guess we can label it as "Fixed Upstream".

> Like `C-<hjkl>`?

In this case we don't need to bind `C-h`, but I still want to point out `C-h` is an important Emacs prefix for help commands and thus is important for discoverability. We shouldn't shadow `C-h` unless we have a good reason or a good alternative (like `SPC h d` or `M-m h d`) in the relevant situation.

**Comment by mskorzhinskiy** [comment]
Oh, sorry, I didn't notice your update.
Yes, everything works just fine after update.
