### ISSUE TITLE
Warning (emacs): Unable to activate package `helm-core'. 

### ISSUE THREAD

**Issue by cjpoor** [syl20bnr/spacemacs#4772]
After new install over emacs 24 on UberStudent linux I get this message following Spacemacs' installation of packages:
**********

Warning (emacs): Unable to activate package `helm-core'.
Required package `async-1.6' is unavailable
Warning (emacs): Unable to activate package `packed'.
Required package `dash-2.10.0' is unavailable
Error (use-package): helm pre-:config hook: Symbol's function definition is void: helm-flx-mode
Error (use-package): helm pre-:config hook: Symbol's function definition is void: helm-flx-mode

*********
Restarting Spacemacs gives this;

Error (use-package): helm pre-:config hook: Symbol's function definition is void: helm-flx-mode
Error (use-package): helm pre-:config hook: Symbol's function definition is void: helm-flx-mode

********
Each new restart gives:
*********

Found 1 new package(s) to install...
--> refreshing package archive: gnu... [4/4]
--> installing package: helm-flx@spacemacs-base... [1/1]
An error occurred while installing helm-flx (error: (error Package `emacs-24.4' is unavailable))

[122 packages loaded in 12.667s]

*************

I note that there is another instance of Emacs installed (GNU Emacs 23)

Any help much appreciated,
Chris.

**Comment by syohex** [comment]
Which emacs version do you use ? `helm-flx` package requires Emacs 24.4 or higher version. So you have to install Emacs 24.4 or higher version for using `helm` completion style.

**Comment by Andre0991** [comment]
You are probably using Emacs 24.3, which is the version available on Ubuntu LTS repositories.

Spacemacs requires 24.4 or higher, so you probably will have to compile Emacs 24.4 or 24.5  (I don't know if someone has created a `deb` package, it would be simpler).

**Comment by Andre0991** [comment]
You are probably using Emacs 24.3, which is the version available on Ubuntu LTS (14.04) repositories.

Spacemacs requires 24.4 or higher, so you probably will have to compile Emacs 24.4 or 24.5 (I don't know if someone has created a deb package, it would be simpler).

**Comment by Andre0991** [comment]
By the way, `init.el` verifies the Emacs version

```
(if (not (version<= spacemacs-emacs-min-version emacs-version))
    (message (concat "Your version of Emacs (%s) is too old. "
                     "Spacemacs requires Emacs version %d or above.")
             emacs-version spacemacs-emacs-min-version)

```

Isn't this message supposed to show up?

**Comment by cjpoor** [comment]
The emacs version opened by Spacemacs is GNU Emacs 24.3.1
I attempted to remove this using Synaptic Package Manager (but did not mark for 'complete removal').
Synaptic appeared to remove and reinstall 24.3.1
Ubuntu Software Center (which I have never used before) gives me the option to install emacs24 24.3+1-2ubuntu1
and the option to remove emacs23 23.4+1-4.1ubuntu1

I am not sure how I should proceed.

I do not see a message on starting Spacemacs to the effect that "Spacemacs requires Emacs version ..."

**Comment by cjpoor** [comment]
Nonetheless, I followed the instructions at http://ubuntuhandbook.org/index.php/2014/10/emacs-24-4-released-install-in-ubuntu-14-04/
up to 

7. Finally compile the package by running commands below one by one.

chris@Totara:~/emacs-source$ ./configure

My system returns 
bash: ./configure: No such file or directory

**Comment by cjpoor** [comment]
Sorry. I needed to cd into the emacs dir.

**Comment by cjpoor** [comment]
Emacs 24.5.1 installed.
Starting emacs-24.5 from terminal:
Spacemacs starts with these messages:

***********
Compiling file /home/chris/.emacs.d/elpa/paradox-20160119.1827/paradox-core.el at Sun Jan 24 17:35:04 2016

Compiling file /home/chris/.emacs.d/elpa/paradox-20160119.1827/paradox-execute.el at Sun Jan 24 17:35:04 2016

In paradox--activate-if-asynchronous:
paradox-execute.el:114:14:Warning: package-activate-1 called with 2 arguments,
    but accepts only 1

In paradox--menu-execute-1:
paradox-execute.el:342:41:Warning: variable reference to constant `nil'
paradox-execute.el:303:25:Warning: package-install called with 2 arguments,
    but accepts only 1

In end of data:
paradox-execute.el:391:1:Warning: the function
    `package-menu--partition-transaction' is not known to be defined.

Compiling file /home/chris/.emacs.d/elpa/paradox-20160119.1827/paradox-github.el at Sun Jan 24 17:35:04 2016

In paradox--github-action:
paradox-github.el:351:21:Warning: reference to free variable
    `package--downloads-in-progress'
paradox-github.el:354:28:Warning: assignment to free variable
    `package--downloads-in-progress'

Compiling file /home/chris/.emacs.d/elpa/paradox-20160119.1827/paradox-menu.el at Sun Jan 24 17:35:04 2016

In end of data:
paradox-menu.el:934:1:Warning: the function `hydra-paradox-filter/body' is not
    known to be defined.

Compiling file /home/chris/.emacs.d/elpa/paradox-20160119.1827/paradox.el at Sun Jan 24 17:35:05 2016

In paradox-list-packages:
paradox.el:154:27:Warning: reference to free variable
    `package--downloads-in-progress'
paradox.el:154:27:Warning: assignment to free variable
    `package--downloads-in-progress'

In paradox-enable:
paradox.el:189:9:Warning: assignment to free variable `package-menu-async'

Compiling no file at Sun Jan 24 17:35:05 2016

***********
Note emacs 24.3 and 23.4 are still on system.

**Comment by cjpoor** [comment]
Created a launcher for emacs 24.5 and now Spacemacs starts with no messages.
Thank you for your help :)
