### ISSUE TITLE
:persistent in micro-states persists even for bindings that are not defined

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#4773]
So if someone adds the  `:persistent` property in a micro-state declaration, one expects that keybindings defined will not exit the micro-state unless they have the `exit` property, as indicated in the documentation:
```
`:persistent BOOLEAN'
    If BOOLEAN is non nil then the micro-state never exits. A binding
    with an explicitly set `exit t' property is required. Default is nil.
```

This holds true, but also holds true for any other key that the user presses, so if you never defined the key `'` or `m` when you press it, it will be recorded as a keybinding but will not exit the microstate. This means that if I wanted to write `mba` once I have moved to a new layout with the layout layer, the `m` would insert an `m` but the `b` press would pop a helm buffer with a list of buffers to switch(execute the action in the micro-state under the letter `b`) 

This is not a behavior we want @syl20bnr as this brings tons of headaches in the development of micro-states.

**Comment by TheBB** [comment]
Might be fixed by #4606?

**Comment by syl20bnr** [comment]
@CestDiego The new transient states (new name for micro-states) powered by hydra have been merged can you test if this issue still occurs ?

**Comment by justbur** [comment]
The persistent flag is gone now, and has been replaced with the more explicit foreign-keys flag. foreign-keys are keys without any definition in the transient-state. For any key in a transient state, you need to explicitly use `:exit`. Is that clearer @CestDiego ?

**Comment by justbur** [comment]
2 weeks should be enough time to respond. @StreakyCobra @syl20bnr I think you can close this.

**Comment by CestDiego** [comment]
I'm sorry for my absence, this is resolved indeed.

On Wed, Feb 17, 2016 at 7:35 PM Justin Burkett <notifications@github.com>
wrote:

> 2 weeks should be enough time to respond. @StreakyCobra
> <https://github.com/StreakyCobra> @syl20bnr <https://github.com/syl20bnr>
> I think you can close this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/4773#issuecomment-185478972>
> .
>
-- 
Diego Berrocal
http://cestdiego.github.io

**Comment by syl20bnr** [comment]
Thank you, closing this.
