### ISSUE TITLE
Eshell doesn't recognize PATH unless I `ls` into ~/.local/bin

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#4774]
Eshell is not recognizing my PATH in Spacemacs. Does someone have the same issue? I'm using NixOS maybe this is one of the reasons? @travisbhartwell 

```
Welcome to the Emacs shell

common $ node
node: command not found
common $ cd
~ $ cd .local/bin/
bin $ ls
_mocha  babel-doctor            babel-node  coffee        eslint  hey.sh         js-beautify  nosetests      npm        tern     webpack-dev-server
babel   babel-external-helpers  cake        css-beautify  gulp    html-beautify  mocha        nosetests-2.7  takeapeek  webpack  
bin $ node
> interrupt
bin $ 
```

**Comment by travisbhartwell** [comment]
I can't reproduce here.  Seems odd.

I remember at one time exec-path-from-shell doing some odd things (see #2294 for example), but I'm not seeing this particular thing right now.

**Comment by duerrp** [comment]
Try `echo $PATH` in the eshell. It probably does not contain `~/.local/bin`. As a workaround, you can use `addpath` or set `eshell-path-env` in your .spacemacs.
