### ISSUE TITLE
Forcing rspec-mode on plain ruby files breaks jump-in-file

### ISSUE THREAD

**Issue by morhekil** [syl20bnr/spacemacs#4775]
Ruby layer currently forces rspec-mode to be turned on for all ruby files, when ```ruby-test-runner``` is set to `rspec` value. 

This is incorrect, as `rspec-mode` package actually provides two minor modes - `Rspec` for editing spec files, and `Rspec-verifiable` for plain ruby files (to quickly run their tests, etc). Forcing Rspec mode for plain ruby files breaks `jump-in-buffer` function (`SPC s j`), as these minor modes [set different values](https://github.com/pezra/rspec-mode/blob/master/rspec-mode.el#L223) of `imenu-create-index-function` and `imenu-generic-expression`.

Rspec-mode [installs its own hook](https://github.com/pezra/rspec-mode/blob/master/rspec-mode.el#L822) for both ruby-mode and enh-ruby-mode, which enables correct minor mode. No additional initialisation is needed in spacemacs for this one at all, and just removing `:init` block from the layer configuration fixes the problem - which is done in the pull request.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
