### ISSUE TITLE
Buffers micro-state vim like bindings

### ISSUE THREAD

**Issue by Dietr1ch** [syl20bnr/spacemacs#4778]
I feel that mnemonics for [n]next and [p]previous should be dropped for [j]next [p]previous. Even while it goes a bit against an easy way to remember, it uses your vim muscle memory for movement keys (bonus j/k are next to each other on qwerty and dvorak).

Maybe this change should be applied only if the user is using evil-mode.
There are probably a few more microstates that go through lists, they should be modified too to keep consistency.

**Comment by Andre0991** [comment]
`j` and `k` are vertical movements. I think it would be weird to use them to go to, for example, the next and previous layouts, as it's a kind of horizontal movement. I think `n` and `p` are fine. Perhaps `h` and `l`, for that matter.

**Comment by justbur** [comment]
The convention used in some other transient states is to bind `p` and `N` to "previous" while keeping `n` for next

**Comment by StreakyCobra** [comment]
I think `n` and `p` are used a lot through Emacs and Spacemacs, and not only in micro/transient-state. For me we should keep these ones, but if you want to make (and maintain after) a layer that change these bindings, feel free to contribute :smiley:

**Comment by Dietr1ch** [comment]
You are right, it seems that n/p for iterating is way too deep into emacs, so changing it may break many workflows ([relevant xkcd](http://xkcd.com/1172/)).

I'll review the bépo layer and start a new one. I might be in need of an automated way to find n/p usages, theoretically most of the changes can be done automatically, only requiring review on bind collisions, but an explicit remap might be good enough.

**Comment by StreakyCobra** [comment]
I don't know if bepo will be really useful for this, as usages are listed manually and it doesn't deal with transient states for now.

Also, maybe before going too far into making it a layer, ask @syl20bnr if he is ready to merge this kind of changes.

**Comment by Dietr1ch** [comment]
It seems that `n/N/p` is actually better. I'll get used to it eventually.
