### ISSUE TITLE
Can't use python-mode because of an issue with pyenv

### ISSUE THREAD

**Issue by shaief** [syl20bnr/spacemacs#4779]
In python-mode with a python file opened not in a virtualenv, i receive the following error message:
`emacs: /bin/bash: pyenv: command not found/versions/bin/bash: pyenv: command not found/bin/python: No such file or directory`

It makes my spacemacs unusable and therefore i use prog-mode instead of python-mode.

This has started today, and i suspect that it's due to this pull request: https://github.com/syl20bnr/spacemacs/pull/4764

#### Update:
I removed this commit:
bddf9de - [2016-01-23]  Set global pyenv version if no .python-version file exists <Christoph Paulik>
And my spacemacs works fine.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. d69c40d)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults tmux eyebrowse
                 (git :variables git-gutter-use-fringe t)
                 github markdown version-control org syntax-checking speed-reading python ipython-notebook django yaml salt javascript html)
```

**Comment by fbergroth** [comment]
This might be fixed by adding `:if (executable-find "pyenv")` to the pyenv use-package form.
/cc @cpaulik

**Comment by cpaulik** [comment]
Sorry about the problem. Didn't think about people who don't have it installed. 

@fbergroth Makes sense. Are you preparing a PR?

**Comment by fbergroth** [comment]
@cpaulik nope, I won't be able to test it/submit a PR for a while.

**Comment by cpaulik** [comment]
OK, I've added the if to use-package in #4780

**Comment by shaief** [comment]
@cpaulik - it's ok, it's part of being on the develop branch. Thanks for the hard work!

**Comment by TheBB** [comment]
Fixed. :-)
