### ISSUE TITLE
Smooth Scroll and search-next

### ISSUE THREAD

**Issue by esiegel** [syl20bnr/spacemacs#478]
The Problem:
If you search for something and the result is within the smooth-scrolling-margin, then calling for the next or previous line causes the buffer to page up/down and the cursor point to jump to the top/bottom.

This could be solved by adding advice to the search-next, search-previous functions or something or perhaps something could be added to smooth-scrolling.

I'm new to the world of emacs, so I apologize if this issue should be directed at either the smooth-scrolling or evil packages.

**Comment by StreakyCobra** [comment]
Doesn't seem to be the case anymore.

**Comment by esiegel** [comment]
verified, seems to work now
