### ISSUE TITLE
spacemacs-layouts: erc doesn't play well with layouts

### ISSUE THREAD

**Issue by choppsv1** [syl20bnr/spacemacs#4781]
When creating a layout and then opening an erc connection, the erc buffers land in the default layout and not in the currently viewed one.

**Comment by StreakyCobra** [comment]
Related to #4517 probably.

**Comment by TheBB** [comment]
Er, we can do a bit better.

The buffers should be added to a named perspective. ERC in particular tends to open buffers at the most inconvenient times and the current persp might not be the ERC persp.

Secondly, the function should be added to `erc-mode-hook` and not `erc-mode`. o_O

**Comment by choppsv1** [comment]
yes, the hook is wrong, but it's also only gets run if you open that defined layout. I define my own [i]rc layout. I think we need to be adding this hook somewhere else.

**Comment by choppsv1** [comment]
IOW what TheBB said, plus add somewhere else :)

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
