### ISSUE TITLE
Org-bullets broken

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#4793]
Suddenly elfeed stopped working. initially I thought it's related to org-mode, but other .org files seemed to have no issues.

Here's the backtrace:

      Debugger entered--Lisp error: (wrong-type-argument listp org-level-3)
        org-activate-plain-links(209)
        font-lock-fontify-keywords-region(1 209 nil)
        font-lock-default-fontify-region(1 209 nil)
        font-lock-fontify-region(1 209 nil)
        byte-code("\212\303 \304\216\305ed	#\210\306 \210\307\211+\207" [save-match-data-internal verbose font-lock-fontified match-data ((byte-code "\301\302\"\207" [save-match-data-internal set-match-data evaporate] 3)) font-lock-fontify-region font-lock-after-fontify-buffer t] 4)
        font-lock-default-fontify-buffer()
        font-lock-fontify-buffer()
        org-bullets-mode()
        run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
        apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
        run-mode-hooks(org-mode-hook)
        org-mode()
        #[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5]("~/spacemacs_layers/elfeed-feeds.org")
        #[257 "\300!\207" [#[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5]] 3 "\n\n(fn IT)"]("~/spacemacs_layers/elfeed-feeds.org")
        mapcar(#[257 "\300!\207" [#[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5]] 3 "\n\n(fn IT)"] ("~/spacemacs_layers/elfeed-feeds.org"))
        -mapcat(#[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5] ("~/spacemacs_layers/elfeed-feeds.org"))
        rmh-elfeed-org-import-headlines-from-files(("~/spacemacs_layers/elfeed-feeds.org") "elfeed")
        rmh-elfeed-org-process(("~/spacemacs_layers/elfeed-feeds.org") "elfeed")
        ad-Advice-elfeed(#[0 "\301\302 !\210\303=\204\303 \210\304 \207" [major-mode switch-to-buffer elfeed-search-buffer elfeed-search-mode elfeed-search-update] 2 ("/Users/agibragimov/.emacs.d/elpa/elfeed-20151227.917/elfeed.elc" . 14366) nil])
        apply(ad-Advice-elfeed #[0 "\301\302 !\210\303=\204\303 \210\304 \207" [major-mode switch-to-buffer elfeed-search-buffer elfeed-search-mode elfeed-search-update] 2 ("/Users/agibragimov/.emacs.d/elpa/elfeed-20151227.917/elfeed.elc" . 14366) nil] nil)
        elfeed()
        call-interactively(elfeed nil nil)
        command-execute(elfeed)

**Comment by Andre0991** [comment]
I can reproduce it.

```
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. 0057df5)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx emacs-lisp common-lisp git
     (shell :variables shell-default-shell 'eshell)
     spacemacs-layouts erc html python pdf-tools ranger
     (elfeed :variables rmh-elfeed-org-files
             (list "/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds.org"))
     themes-megapack semantic
     (c-c++ :variables c-c++-enable-clang-support t)
     (auto-completion :variables auto-completion-private-snippets-directory "/Users/andre0991/Dropbox/backup/emacs/yasnippet-snippets/" auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for latex)
     org
     (ranger :variables ranger-show-preview t)
     markdown latex spell-checking syntax-checking version-control)
```



```
Debugger entered--Lisp error: (wrong-type-argument listp org-level-2)
  org-activate-plain-links(8504)
  font-lock-fontify-keywords-region(1 8504 nil)
  font-lock-default-fontify-region(1 8504 nil)
  font-lock-fontify-region(1 8504 nil)
  byte-code("\212\303 \304\216\305ed	#\210\306 \210\307\211+\207" [save-match-data-internal verbose font-lock-fontified match-data ((byte-code "\301\302\"\207" [save-match-data-internal set-match-data evaporate] 3)) font-lock-fontify-region font-lock-after-fontify-buffer t] 4)
  font-lock-default-fontify-buffer()
  font-lock-fontify-buffer()
  org-bullets-mode()
  run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
  run-mode-hooks(org-mode-hook)
  org-mode()
  #[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5]("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds.org")
  #[257 "\300!\207" [#[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5]] 3 "\n\n(fn IT)"]("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds.org")
  mapcar(#[257 "\300!\207" [#[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5]] 3 "\n\n(fn IT)"] ("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds.org"))
  -mapcat(#[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5] ("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds.org"))
  rmh-elfeed-org-import-headlines-from-files(("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds.org") "elfeed")
  rmh-elfeed-org-process(("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds.org") "elfeed")
  ad-Advice-elfeed(#[0 "\301\302 !\210\303=\204\303 \210\304 \207" [major-mode switch-to-buffer elfeed-search-buffer elfeed-search-mode elfeed-search-update] 2 ("/Users/andre0991/.emacs.d/elpa/elfeed-20151227.917/elfeed.elc" . 14366) nil])
  apply(ad-Advice-elfeed #[0 "\301\302 !\210\303=\204\303 \210\304 \207" [major-mode switch-to-buffer elfeed-search-buffer elfeed-search-mode elfeed-search-update] 2 ("/Users/andre0991/.emacs.d/elpa/elfeed-20151227.917/elfeed.elc" . 14366) nil] nil)
  elfeed()
  call-interactively(elfeed nil nil)
  command-execute(elfeed)
```

**Comment by StreakyCobra** [comment]
Confirmed here too. My setup isn't working anymore :-(

**Comment by StreakyCobra** [comment]
Soooo, first **workaround**: Add `org-bullets` to `dotspacemacs-excluded-packages`.

**Comment by agzam** [comment]
Also it seems 'org-jira' package stopped working as well

**Comment by Andre0991** [comment]
@StreakyCobra workaround works.

I tried to change my org file and I'm getting this now:

`org-element-headline-parser: Symbol's value as variable is void: org-planning-line-re`


````
Debugger entered--Lisp error: (void-variable org-planning-line-re)
  org-element--get-node-properties()
  org-element-headline-parser(559 nil)
  org-element--current-element(559 nil first-section nil)
  org-element--parse-elements(1 559 first-section nil nil nil (org-data nil))
  org-element-parse-buffer()
  rmh-elfeed-org-import-trees("elfeed")
  #[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5]("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds-2.org")
  #[257 "\300!\207" [#[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5]] 3 "\n\n(fn IT)"]("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds-2.org")
  mapcar(#[257 "\300!\207" [#[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5]] 3 "\n\n(fn IT)"] ("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds-2.org"))
  -mapcat(#[(file) "r\302\303!!q\210\304 \210\305\306\307\310	!!!\311	!\")\207" [file tree-id find-file-noselect expand-file-name org-mode rmh-elfeed-org-cleanup-headlines rmh-elfeed-org-filter-relevant rmh-elfeed-org-convert-tree-to-headlines rmh-elfeed-org-import-trees intern] 5] ("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds-2.org"))
  rmh-elfeed-org-import-headlines-from-files(("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds-2.org") "elfeed")
  rmh-elfeed-org-process(("/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds-2.org") "elfeed")
  ad-Advice-elfeed(#[0 "\301\302 !\210\303=\204\303 \210\304 \207" [major-mode switch-to-buffer elfeed-search-buffer elfeed-search-mode elfeed-search-update] 2 ("/Users/andre0991/.emacs.d/elpa/elfeed-20151227.917/elfeed.elc" . 14366) nil])
  apply(ad-Advice-elfeed #[0 "\301\302 !\210\303=\204\303 \210\304 \207" [major-mode switch-to-buffer elfeed-search-buffer elfeed-search-mode elfeed-search-update] 2 ("/Users/andre0991/.emacs.d/elpa/elfeed-20151227.917/elfeed.elc" . 14366) nil] nil)
  elfeed()
  call-interactively(elfeed nil nil)
  command-execute(elfeed)
````

**Comment by Andre0991** [comment]
Some of my org links are not being displayed as links, but with `[[][]]`.

I get this on startup:

`Error during redisplay: (jit-lock-function 1070) signaled (wrong-type-argument listp org-table)`

Seems that there's something wrong with org. Or I'm out of luck today :eyes:

**Comment by Andre0991** [comment]
Yeap, there's something wrong with org.

@jackbaty said this on the gitter chat:
>After a package update this morning I'm seeing some odd rendering of org mode files. Clock tables appear completely broken. Some TODO keywords are rendered without the usual face, while most look fine. Lots of these messages: Error during redisplay: (jit-lock-function 5129) signaled (wrong-type-argument listp org-level-2) Killed it all and installed from scratch with no improvement. Just me?

**Comment by fintelkai** [comment]
I just had the same kinds of issue with org-mode here after running package update. I rolled back the package update, which got me back to an earlier org installation. Problems gone. Probably an issue upstream with org?

**Comment by StreakyCobra** [comment]
> Probably an issue upstream with org?

Not necessarily an issue. It may be a an `org` change for which other packages didn't had time to adapt yet. It can also be the case for some spacemacs functionalities maybe.

**Comment by robbyoconnor** [comment]
It doesn't seem to always be broken which is weird -- I'm using org-mode right now

**Comment by Andre0991** [comment]
Consider this file:
```
** Emacs                                                             :emacs:
*** [[http://planet.emacsen.org/atom.xml][Planet Emacsen]]
```

If I open it with the latest org package, the link is showed literally (as presented above) instead of as an actual link. With `Org-mode version 8.2.10 (release_8.2.10 @ /Users/andre0991/.emacs.d/elpa/org-plus-contrib-20160125/)`, it works fine. All of this with the latest develop, by the way.

A few things I noticed
- This probably has to do with Spacemacs. I've been reading `#emacs` and `#org-mode` on freenode and nobody reported any error like those described here.
- This probably doesn't have to do with a recent commit. On the latest develop, as I said, it works with an older org package
- `org-bullets` is not the main problem. Excluding it prevents the elfeed error but some links are not displayed correctly (and there are possibly other strange things too like issues with tables).
- When opening the file I described above with `org-bullets` excluded, I get these errors:

```
Error during redisplay: (jit-lock-function 1070) signaled (wrong-type-argument listp org-table)
Truncate long lines disabled
truncate-lines disabled.
Error during redisplay: (jit-lock-function 1) signaled (wrong-type-argument listp org-level-3)
Error during redisplay: (jit-lock-function 526) signaled (wrong-type-argument listp org-level-3)
Error during redisplay: (jit-lock-function 1079) signaled (wrong-type-argument listp org-level-3)
Error during redisplay: (jit-lock-function 1588) signaled (wrong-type-argument listp org-level-3)
Error during redisplay: (jit-lock-function 2163) signaled (wrong-type-argument listp org-level-3)
Error during redisplay: (jit-lock-function 2676) signaled (wrong-type-argument listp org-level-3)

```

(actually a file similar to the above).

**Comment by noonie2k** [comment]
@Andre0991 As mentioned on the other issue; org-reload completes fine but I still get the wrong-type-argument error.

Thanks

**Comment by miabrahams** [comment]
Perhaps related to this? 
http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=9eface25da489cbb7b8c2f4951850b571f74f660

**Comment by noonie2k** [comment]
That patch description looks suspect; my issues were indeed related to links in some way.

I reverted my version of the org package to "org-20160118" by downloading the tarball from the GNU ELPA site; I'm not seeing the (wrong-type-argument listp org-whatever) error any more.

**Comment by Andre0991** [comment]
The errors I was getting have to do with faces and links so yeah, that commit may be the problem.

**Comment by Andre0991** [comment]
OK, based [on this Reddit thread](https://www.reddit.com/r/emacs/comments/43a3lt/orgmode_hyperlinks_showing_in_undecorated_form/), it's an upstream issue.

**Comment by syl20bnr** [comment]
Is this issue reported upstream ? It seems not.

**Comment by Andre0991** [comment]
I get the formatted links now. And Elfeed works. Seems that it's fixed now - as the guy from Reddit said, probably this was fixed some days ago but it took a while for it to get to the package manager.

**Comment by StreakyCobra** [comment]
@agzam Can you check if the issue is indeed fixed? If it is the case you may consider closing the issue :-)

**Comment by Stebalien** [comment]
FYI, I can confirm that #4834 (as reported by @noonie2k) appears to be fixed.

**Comment by noonie2k** [comment]
Indeed it is :)

**Comment by agzam** [comment]
Works now. Thank you everyone!
