### ISSUE TITLE
The FAQ and Documentation index links don't work

### ISSUE THREAD

**Issue by vr00m** [syl20bnr/spacemacs#4796]
The index links at
https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org
and
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org
return 404 error.

Sorry, this is a duplicate of:
 https://github.com/syl20bnr/spacemacs/issues/4399

**Comment by TheBB** [comment]
Yep, duplicate. :-)
