### ISSUE TITLE
change font config in .spacemacs, not work!

### ISSUE THREAD

**Issue by derekcn** [syl20bnr/spacemacs#4798]
```elisp
 dotspacemacs-default-font '("Source Code Pro"
                               :size 13
                               :weight ultra-bold
                               :width ultra-expanded
                               :powerline-scale 1.1)

**Comment by StreakyCobra** [comment]
We will need more information than this in order to help you. Looks [here](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) for a template. In particular the descripition of the system, and also how you start emacs (terminal, GUI, daemon, …)

**Comment by derekcn** [comment]
oh, thank u, i will post another issue after reading the template.
