### ISSUE TITLE
change font config in .spacemacs, but it does not work.

### ISSUE THREAD

**Issue by derekcn** [syl20bnr/spacemacs#4799]
#### Description
change font config in .spacemacs, but it does not work.

#### Reproduction guide
- Start Emacs, emacs & in terminal
- M-m f e d
- Modify it like this 
```elisp
   dotspacemacs-default-font '("Source Code Pro"
                               :size 13
                               :weight ultra-bold
                               :width ultra-expanded
                               :powerline-scale 1.1)
```

Observe: 
  after restart emacs, font no change and no error occurs.

Expect:
  font change.

#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp
                 (python :variables python-test-runner 'pytest)
                 racket go gtags git html javascript ycmd version-control
                 (colors :variables colors-enable-nyan-cat-progress-bar t)
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
                 (chinese :variables chinese-enable-youdao-dict t chinese-enable-fcitx t))
```

**Comment by TheBB** [comment]
Do you have Source Code Pro installed?

**Comment by derekcn** [comment]
exactly right, i didn't install Source Code Pro. After installed, it's ok.
thanks all.

**Comment by TheBB** [comment]
If you don't like SCP you can change it to a different font. The point is that if the font name doesn't exist, then *none* of the settings will take effect.
