### ISSUE TITLE
cperl-mode + smartparens issue

### ISSUE THREAD

**Issue by alexrkopp** [syl20bnr/spacemacs#480]
Hello,

If you switch into cperl-mode and type the following:

```
if (0) {
```

It will be automatically changed to

```
if (0) {}}
```

Note the two closing curly braces. Switching into perl-mode and typing that same line yields proper behavior.

Any ideas?

**Comment by alexrkopp** [comment]
Anyone have any idea what is causing this?

**Comment by jasonblewis** [comment]
I see this behaviour too. I think its related to smartparens as I don't use spacemacs

**Comment by spacebat** [comment]
I think its a conflict between cperl's electric braces and related options, and smartparens' auto pairing. I've disabled all of cperl's electric settings.

**Comment by Fuco1** [comment]
It might very well be what @spacebat describes.  Smartparens is quite aggresive in its own enforcing rules, since most of the time the "electric" stuff is quite, well, idiotic.  The apparently random order of execution of hooks doesn't help one bit either... it is most recomended to turn off any electric stuff while using SP.

**Comment by pasja** [comment]
My quick&dirty solution:
`(define-key cperl-mode-map "{" 'nil)`

**Comment by TheBB** [comment]
Since Spacemacs doesn't have a layer for this mode, and since there's an easy workaround from @pasja, I am liable to close this. If the time comes when Spacemacs has official Perl support we can revisit.

For future visitors, the workaround should be (in `user-config`):

```elisp
(with-eval-after-load 'cperl-mode
  (define-key cperl-mode-map "{" nil))
```

**Comment by benlind** [comment]
I recently had this problem. I have `electric-pair-mode` on with `cperl-mode`, and I was getting `{}}` when typing `{` on an empty line.

This solved my problem:

    (add-hook 'cperl-mode-hook (lambda () (local-unset-key (kbd "{"))))

**Comment by PrgrmAtCeleritas** [comment]
This solution will allow `electric-pair-mode` to still work when smartparens is toggled off

```
(with-eval-after-load 'cperl-mode
  (add-hook 'smartparens-enabled-hook  (lambda () (define-key cperl-mode-map "{" nil)))
  (add-hook 'smartparens-disabled-hook  (lambda () (define-key cperl-mode-map "{" 'cperl-electric-lbrace))))
```
