### ISSUE TITLE
`git-timemachine` broken in `coffee-mode` with `spacemacs-ivy`

### ISSUE THREAD

**Issue by danielwuz** [syl20bnr/spacemacs#4801]
Received below error message:

```
Debugger entered--Lisp error: (void-function helm-gtags-mode)
  helm-gtags-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook coffee-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook coffee-mode-hook))
  run-mode-hooks(coffee-mode-hook)
  coffee-mode()
...
```

will look into it later.

**Comment by StreakyCobra** [comment]
It would be nice if you can give more information such as with the template [presented here](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) (reproduction guide, system info, …) :-) Thx

**Comment by danielwuz** [comment]
Found the problem. It was a mistake I accidentally included in my personal config, has nothing to do with `spacemacs`.

@StreakyCobra thanks for you quick reply. I'll keep in mind next time.
