### ISSUE TITLE
add daylerees colour schemes 

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#4803]
Pls add daylerees/colour-schemes#155! I dont know if the `megapack` layer is the right place for to mix them up with. Wouldn't it be better to have a `+themes` folder then? There is still a PR open though they [look](http://daylerees.github.io/) so beautiful and I can't find similiar ones yet. :see_no_evil:

**Comment by StreakyCobra** [comment]
I don't want to kill your enthusiasm, but this PR is 1.5 years old now, without activity for more than 6 months :pensive:

**Comment by cloudbring** [comment]
I'd love to see the daylerees colours added to the emacs themes

**Comment by robbyoconnor** [comment]
PRs welcome!

**Comment by robbyoconnor** [comment]
If you have to use quelpa, do it.

**Comment by JAremko** [comment]
:+1:  Peacock and Mud Contrast looks sexy

**Comment by JAremko** [comment]
[This](https://github.com/emacsfodder/tmtheme-to-emacs) tool might help

**Comment by syl20bnr** [comment]
WOW seems that it now supports emacs theme, should provide a recipe on MELPA before we can support it in Spacemacs though.
