### ISSUE TITLE
Consider adding sublimity

### ISSUE THREAD

**Issue by legendre6891** [syl20bnr/spacemacs#481]
Please consider adding the `sublimity` package; this package adds a smooth scrolling effect (in terms of acceleration/deceleration) and a minimap.

https://github.com/zk-phi/sublimity

**Comment by bjarkevad** [comment]
This would be fine in a layer of its own :+1:

**Comment by syl20bnr** [comment]
+1 @bjarkevad

**Comment by syl20bnr** [comment]
I worked on a `sublime-text` layer but unfortunately available minimap packages are hard to integrate properly with other buffers like `neotree` and `guide-key` :-(

I'm not sure to have time to look more into it.

**Comment by bobbyangelov** [comment]
:+1: Great idea, would love to have it there!

**Comment by bru** [comment]
just my 2c, but it might be worth even just for the smooth scrolling.
Might try and make some time to look into this.

**Comment by bru** [comment]
actually scratch that, my fault I had spacemacs' own smooth scrolling disabled.

**Comment by serapath** [comment]
+1

**Comment by taizilongxu** [comment]
+1

**Comment by Andre0991** [comment]
+1. It would be cool to have an option to toggle a kind of centered mode in which the length of each line is ~70 visual characters and the text is centralized, expanding the side margins (using sublimity or any other suitable package). It makes the text much more readable.

**Comment by mclearc** [comment]
Bump   :+1:

**Comment by nimish** [comment]
What would it take to get this implemented? How hard is it to get just the minimap?

**Comment by roryokane** [comment]
If you want a minimap, as well as [sublimity](https://melpa.org/#/sublimity), there is also the [minimap](https://melpa.org/#/minimap) package. I have never tried either package. The minimap package seems to be more focused than sublimity – it implements a minimap but not smooth scrolling or buffer centering.

**Comment by a13ph** [comment]
For centering, there are some other packages as well: [centered-window-mode](https://github.com/anler/centered-window-mode) and automargin (old, got integrated into sublimity)

**Comment by gilch** [comment]
I tried the minimap packages. They seem to work correctly only in holy-mode. You can drag with the mouse to scroll, but it doesn't work with evil.

**Comment by JorisE** [comment]
:+1:  for a working minimap.

**Comment by danShumway** [comment]
Agreed, minimap support is... maybe not a killer feature. But certainly pretty close to one.

I've only recently started using spacemacs (I'm very new to emacs/vim in general), but I'll be looking for a solution for this and I am currently using evil mode - so if I get a working layer with either sublimity or minimap installed, I'll post back with results.

**Comment by d12frosted** [comment]
I don't understand how something like this can be killing feature, so please make this distracting 'feature' optional. Or as it was already mentioned - in separate layer.

**Comment by mclearc** [comment]
For what it is worth, I've found  [centered-window-mode](https://github.com/anler/centered-window-mode) to work much better than Sublimity, and also to work better with which-key.

**Comment by Compro-Prasad** [comment]
Its smooth scrolling works far better than pixel-scroll-mode

**Comment by dijonkitchen** [comment]
Any updates or should it be closed?

**Comment by Compro-Prasad** [comment]
Not worth it. Can be closed. Can be reopened when its a priority.
