### ISSUE TITLE
Sass flycheck Undefined mixin

### ISSUE THREAD

**Issue by kmiasko** [syl20bnr/spacemacs#4814]
I'm using bourbon and neat in my project. I've main.sass file that imports all the partials and it's compiled to main.css. When i open a partial file in spacemacs it's showing errors about  undefined mixin's from neat (main.sass compiles without problems).

```
Suspicious state from syntax checker sass: Checker sass returned non-zero exit code 65, but no errors from output: Error: Undefined mixin 'size'.
        on line 2 of standard input, in `size'
        from line 2 of standard input
  Use --trace for backtrace.

Checker definition probably flawed.
```

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp colors
                 (git :variables git-magit-status-fullscreen t)
                 org
                 (shell :variables shell-default-height 'full shell-default-position 'bottom shell-default-shell 'eshell)
                 gtags syntax-checking version-control react colors unimpaired evil-snipe evil-commentary evil-cleverparens javascript html)
```

**Comment by StreakyCobra** [comment]
It's probably either an issue with the sass checker, or with the `Flycheck` definition of the checker.

You can try to do this:

- Identify the checker with `SPC e v` (in the file)
- Run manually the checker on the file in command line (something like: `sass filename.sass` probably) and look if it succeed to analyze it.

If there is an error it's probably an error of the checker program.
If the output of the program looks correct, it probably means the flycheck definition of the checker is flawed.

**Comment by kmiasko** [comment]
Yeah, my bad. I need to include a mixins file in every partial that uses it to avoid syntax errors.
