### ISSUE TITLE
Font size and powerline separator are wrong when starting GUI frame from daemon

### ISSUE THREAD

**Issue by apaleslimghost** [syl20bnr/spacemacs#4816]
<img width="1187" alt="screenshot 2016-01-26 10 40 36" src="https://cloud.githubusercontent.com/assets/631757/12580954/8a761fd6-c42b-11e5-8596-bdbe31923657.png">

Left is started from daemon, right is standalone. The issue still occurs on develop. I realise several similar issues (#299, #1894, #2652) have been raised, but I'd thought they were all resolved :confused:
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: nil (rev. 5fab8e8)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp osx syntax-checking vinegar javascript version-control php shell-scripts html themes-megapack
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
            quarterto react markdown
            (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/local/bin/zsh"))
```

Edit: if it helps, [here](https://github.com/quarterto/.spacemacs.d/blob/master/.spacemacs) is my `.spacemacs`. My configuration layer is also in that repo.

**Comment by TheBB** [comment]
I can't see this screenshot.

**Comment by quarterto** [comment]
Apologies, reuploaded

**Comment by StreakyCobra** [comment]
` Fastly error: unknown domain: butt.githubusercontent.com. Please check that this domain has been added to a service.`

**Comment by TheBB** [comment]
https://github.com/quarterto/.spacemacs.d/blob/master/.spacemacs#L225

You have to do this after the GUI frame is created, not before.

```elisp
(spacemacs|do-after-display-system-init
  (setq powerline-default-separator 'slant))
```

**Comment by quarterto** [comment]
What about the font size?

**Comment by TheBB** [comment]
I don't know…

**Comment by quarterto** [comment]
Quick update: I tried `spacemacs/set-default-font` in `spacemacs|do-after-display-system-init` and it had no effect.

**Comment by spijet** [comment]
It seems that the only way for now is ~~to start Spacemacs with `emacsclient -c -a "" `~~. Just checked it, powerline separators get re-set to default ones after frame is created.

**Comment by shuokay** [comment]
I  incidentally find a way to solve this problem when trying to find a way to use the solaried theme, I record here in case someone need.

1. Disable the spacemacs ```themes-megapack``` by removing it from ```dotspacemacs-configuration-layers```
2. Add ```color-theme-solarized``` to ```dotspacemacs-additional-packages```
3.  add the following lines to ```dotspacemacs/user-config ()```

```
(set-terminal-parameter nil 'background-mode 'dark)  
(set-frame-parameter nil 'background-mode 'dark)   
(spacemacs/load-theme 'solarized)  
 ```
I think this problem is caused by the ```themes-megapack```, 
but I didn't confirm it.

**Comment by jcf** [comment]
To fix the font size issue I added the following snippet to my `dotspacemacs/user-init` function:

``` emacs-lisp
(setq default-frame-alist '((font . "Source Code Pro-14")))
```

http://superuser.com/questions/721634/different-font-size-when-running-emacs-and-emacsclient

HTH.

**Comment by panicbit** [comment]
Still valid.
