### ISSUE TITLE
Multiple words in helm-do-ag returns all lines as results

### ISSUE THREAD

**Issue by eltechnic0** [syl20bnr/spacemacs#4819]
As far as I have seen, writing more than one word in the input narrows the results fine for `helm-swoop` and `helm-ag-this-file`, however `helm-do-ag` returns all consecutive lines as results (where there is actually no match).

I don't know if this is unexpected or normal operation, but I haven't been able to find the answer.

**Comment by TheBB** [comment]
What you type is sent to ag verbatim, so if you want to search for multiple words you need to do it regexp style, e.g. `auto.*completion`.

If you want to do it fuzzy style, you need to set `helm-ag-fuzzy-match` to `t`.

**Comment by eltechnic0** [comment]
I have tried both with `helm-ag-fuzzy-match` to `t` and `nil` (using `setq`?) but I seem to only be able to search regexp style with `helm-do-ag`. I also get this error when I write two words separated by space:

```
Error during redisplay: (eval (spaceline--prepare (quote (helm-buffer-id helm-number helm-follow
 helm-prefix-argument)) (quote (helm-help)))) signaled (wrong-type-argument 
integer-or-marker-p nil) [8 times]
```

**Comment by TheBB** [comment]
Can you get me a backtrace for that error? (`SPC t D`)

**Comment by syohex** [comment]
@eltechnic0 Hi, I'm author of helm-ag.

Could you tell me how to reproduce this issue ?
- What word did you input as search query ?
- Could you show me screenshot when you got such result ?
- Which command did you use ? `ag`(the silver searcher), `pt`(the platinum search), etc(`ack`) ?

**Comment by eltechnic0** [comment]
With `debug-on-error` ON I get no backtrace, only the error message shown above. I can reproduce it with any combination of words I've used so far. I get this error when I use either `helm-project-do-ag` or `helm-project-do-ag-region-or-symbol`, but also using `helm-do-ag` with a function of my own (I'm using `ag`). I can't post an screenshot right now. I'll do it later.

**Comment by TheBB** [comment]
Ah of course, sorry. You can't get a backtrace from the modeline.

**Comment by eltechnic0** [comment]
Sorry for the delay. Here is the screenshot I promised.

![emacs-helm-ag-multi-word](https://cloud.githubusercontent.com/assets/1580073/12798139/15d400b4-cac8-11e5-82b6-2a1455ef9d70.png)

**Comment by syohex** [comment]
Thanks for taking screenshot.

And some questions.
- Could you show value of `helm-ag--last-command` after getting such result ?
- Your ag version ?

**Comment by syohex** [comment]
I can reproduce this issue with older ag. Please upgrade ag(0.25 or higher version) and try again.

**Comment by eltechnic0** [comment]
I was using version 0.27. I have upgraded to version 0.31 (latest as of now) and the problem is gone. Works great. Thanks.

**Comment by StreakyCobra** [comment]
@eltechnic0 This issue can probably be close then :-)

**Comment by syohex** [comment]
Oh, sorry. I'll check and update document later.
