### ISSUE TITLE
Layouts microstate help/info isn't dynamic anymore

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#4822]
Pressing `SPC l` triggers the layouts microstate, and shows a help buffer at the bottom:
![layouts-microstate](https://cloud.githubusercontent.com/assets/4334375/12582257/a2628382-c444-11e5-9e7c-4e287a27b36b.png)
I am talking about the "Layout Transient State: [1:Default]". Up until one or two days ago, pressing `?` would change the help text to show/hide available keys, but now it doesn't appear to do anything.
Also, if I open a new layout, the help text doesn't show the new layout, although I can switch to it without a problem.
Manually re-evaluating the `(spacemacs|define-transient-state layotus [...])` form does update the help text, so it means the help text no longer updates automatically as it used to :cry: 

Reproduction steps:
- start spacemacs
- use `SPC l 2` to create a new layout
- type `SPC l`

Result: help text doesn't show the new layout.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. 72e1413)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(spacemacs-ivy
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t company-tooltip-align-annotations t)
 emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control ranger evil-cleverparens python command-log eyebrowse smex themes-megapack c-c++ ibuffer)
```

**Comment by TheBB** [comment]
Thanks. This is a known problem but it's good to have an issue.

**Comment by bmag** [comment]
Ok, didn't know it was known.

**Comment by StreakyCobra** [comment]
@bmap, btw you should have tried `SPC h I` for easily opening the issue :-) (if it is not the case)

**Comment by justbur** [comment]
#4823

**Comment by justbur** [comment]
@bmag I think this can be closed

**Comment by bmag** [comment]
indeed, thank you
