### ISSUE TITLE
[suggestion] Evaluate JavaScript with node.js / io.js

### ISSUE THREAD

**Issue by stormpat** [syl20bnr/spacemacs#483]
It would be really cool if you could eval a buffer with node or io.js. This should be a part of the JavaScript contrib layer. Even better, if there was a way to evaluate just a block instead of the entire buffer. 

There is bindings in the clojure layer to eval a region or buffer, so i was thinking of something similar.

**Comment by oppenlander** [comment]
I used to have something like this in my last setup with [js-comint](http://js-comint-el.sourceforge.net/).  
It lets you evaluate code like this, but it was infuriatingly slow.

I was going add something like this once I had time to look in to other options.

**Comment by syl20bnr** [comment]
PR welcome. There are conventions for such actions: https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.md#interactions-with-repls

**Comment by stormpat** [comment]
I have never done any LISP before, im still learning. Ill definitely make a PR once i have something worth sharing.

**Comment by mkcode** [comment]
Checkout swankjs too.

https://github.com/swank-js/swank-js

**Comment by mkcode** [comment]
Wow. A video of swank! :) https://m.youtube.com/watch?v=qwtVtcQQfqc

**Comment by stormpat** [comment]
Thats just amazing! We really need to get that included in JS layer!

**Comment by esiegel** [comment]
There's also [skewer](https://github.com/skeeto/skewer-mode).  I haven't used either, but it seems that skewer is trying to replace swank with the claimed advantage of being easier to install.

[Here](https://www.youtube.com/watch?v=4tyTgyzUJqM&feature=youtu.be) is a video of it in action.

**Comment by oppenlander** [comment]
Skewer seems to have solved some usability issues with live coding in a browser, but I can't find anything about node.js/io.js REPL support.
There's [this issue](https://github.com/skeeto/skewer-mode/issues/37), which hasn't been updated in a year, but I also can't find any reference to an alternate engine in the source, other than `browser` and `phantom`.

Slime on the other hand seems like it is really good for nodejs/io.js, but the CSS/HTML eval is dreadful.

It would probably be best to have both available, but mixing them will likely be problematic.

**Comment by robbyoconnor** [comment]
Why has nobody done work on this?...I mean I'm not demanding, just am curious :)

**Comment by stormpat** [comment]
I have tried but failed, as I just suck at Lisp, and also am very new to the Emacs ecosystem. The solutions out there seems very big (swank) as it seems to be connected to the browser (via sockets) too. 

I would like to (start) with something very basic/minimal, im very fond of how to alchemist package evaluates your Elixir code and prints it to the buffer, as a comment. For now i have been using this to eval my buffer.


    (defun u/node-eval ()
      "Evaluate the current buffer (or region if mark-active),
       and return the result into another buffer,
       which is to be shown in a window."
     (interactive)
     (let ((debug-on-error t) (start 1) (end 1))
        (cond
          (mark-active
          (setq start (point))
          (setq end (mark)))
     (t
       (setq start (point-min))
       (setq end (point-max))))
     (call-process-region
       start end     ; seems the order does not matter
       "node"        ; node.js
       nil           ; don't delete region
       "node.js"     ; output buffer
       nil)          ; no redisply during output
    (message "Region or buffer evaluated!")
    (setq deactivate-mark t))) ; deactive the region, regardless


The snippet is from SO, http://stackoverflow.com/questions/19743105/how-to-evaluate-javascript-buffer-by-node-js-from-within-emacs-on-windows

It prints the result in a new buffer. Theres a lot of room for improvement, and i have some ideas and have been reading the source for the alchemist package to get a better understanding of how it works.

**Comment by v3ctr0n** [comment]
As a javascript/node developer, I really disappointed this hasn't been resolved despite being old and much in demand..

**Comment by stormpat** [comment]
@v3ctr0n The latest master now has skewer-mode included.

**Comment by v3ctr0n** [comment]
@stormpat how do I evaluate node.js code in the skewer repl?

**Comment by InvisibleTech** [comment]
Wow, I feel like I am retracing the steps of this issue.   I am okay with a little LISP not strong yet on emacs ecosystem.  Came over to spacemacs for everything I can but I am hitting the same wall here.  `skewer` is fine if I want front development with a nice code to browser flow.  However, I really want is node REPL to evaluate application.   Been grinding around various search hits.  Nothing yet.  What am I missing?

**Comment by stormpat** [comment]
@InvisibleTech @ghost If you want a more traditional REPL you could try https://melpa.org/#/nodejs-repl

**Comment by InvisibleTech** [comment]
Thanks @stormpat but my issue is twofold, I use spacemacs (not the issue IMO :-) ) and so it seems to have rules of engagement.  I tried to add use of noderepl-js setting up site-lisp to contain the required folder with some code used to tell "normal" Emacs how to do the Node REPL.  Issue seemed to be spacemacs ignored it.  So I would have to then install it use emacs commands.  I think it had to be done every restart - don't recall.  I tried (just hacking without knowing) to reference the file from the layers list and since it wasn't a proper layer.. rejected.    I am an emacs/spacemacs newb... so what do I do to "install" your suggested file?

**Comment by stormpat** [comment]
@InvisibleTech 

Heres something to get you started:

First add the package to your .spacemacs file.
``` dotspacemacs-additional-packages '(nodejs-repl) ```

The restart emacs to install ```SPC q R```

Optional:

Add some keybindings for easier use
``` (spacemacs/set-leader-keys "onr" 'nodejs-repl-send-region) ```

Note. The ```SPC o``` namespace is reserved for userland, so it will never conflict with spacemacs.

You can start the repl with ```nodejs-repl```

You will get this:

![](http://i.imgur.com/jtNs5Nx.gif)

**Comment by syl20bnr** [comment]
What don't we have node.js REPL in the layer ? Is it just because nobody submitted it or is there any other issue ?

**Comment by robbyoconnor** [comment]
I'm not entirely sure..

**Comment by madand** [comment]
@syl20bnr indeed, there is no Node REPL support in the layer at the moment. 

What makes this issue challenging is the fact that we need support for two different REPLs in most cases, within a single project, in the same major mode `js2-mode`: 

1. The browser REPL. It is already available in the layer with `skewer-mode`. 
2. NodeJS REPL. As previously mentioned, this can be added with `nodejs-repl`.

We need a way to define which set of REPL bindings should be activated for a given file within a project. So that conventional leader keybindigs like `,sb` and `,ss` will invoke the right commands.

Maybe the layer should provide some file/dir-local vars to define which REPL to use. Any hints on how to properly implement this in Spacemacs are welcome.

**Comment by robbyoconnor** [comment]
I would be in favor of a flag personally.

**Comment by beppu** [comment]
Here's something people can do while they wait for this to be properly integrated into the **javascript** layer.  (Thanks to @stormpat for the example above.)

https://github.com/abicky/nodejs-repl.el/wiki/Spacemacs-Configuration
