### ISSUE TITLE
"Search failed: dotspacemacs-editing-style 'vim"

### ISSUE THREAD

**Issue by cazzerson** [syl20bnr/spacemacs#4832]
After installing emacs on OSX as described in the documentation and installing the spacemacs packages and restarting emacs, I am able to select vim mode and the defaul spacemacs distribution, but see the following error:

    Warning (initialization): An error occurred while loading `/Users/XXX/.emacs.d/init.el':
    
    Search failed: dotspacemacs-editing-style 'vim

This also seems to prevent the .spacemacs file from being created. Do you have any suggestions for ways to solve this?

**Comment by person808** [comment]
Could you try installing but start emacs with `emacs --debug-init`?

**Comment by cazzerson** [comment]
```
Dotfile wizard installer
Debugger entered--Lisp error: (search-failed "dotspacemacs-editing-style 'vim")
  re-search-forward("dotspacemacs-editing-style 'vim")
  (while --dolist-tail-- (setq p (car --dolist-tail--)) (goto-char (point-min)) (re-search-forward (car p)) $
  (let ((--dolist-tail-- preferences) p) (while --dolist-tail-- (setq p (car --dolist-tail--)) (goto-char (p$
  (save-current-buffer (set-buffer (find-file-noselect (concat dotspacemacs-template-directory ".spacemacs.t$
  (let ((preferences (if arg (progn (list (list "dotspacemacs-editing-style 'vim" (format "dotspacemacs-edit$
  dotspacemacs/install(with-wizard)
  (if (dotspacemacs/install (quote with-wizard)) (progn (dotspacemacs/sync-configuration-layers (quote (16))$
  (if (file-exists-p dotspacemacs-filepath) nil (spacemacs-buffer/set-mode-line "Dotfile wizard installer") $
  spacemacs/maybe-install-dotfile()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%$
  eval-buffer(#<buffer  *load*> nil "/Users/XXX/.emacs.d/init.el" nil t)  ; Reading at buffer position $
  load-with-code-conversion("/Users/XXX/.emacs.d/init.el" "/Users/XXX/.emacs.d/init.el" t t)
  load("/Users/XXX/.emacs.d/init" t t)
```

**Comment by cazzerson** [comment]
Possibly more useful: after removed the `elpa` directory and re-running `emacs --debug-init`, I see:

    Symbol's function definition is void: projectile-mode

**Comment by robbyoconnor** [comment]
`SPC hds` please.

**Comment by robbyoconnor** [comment]
Also please [follow this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report).

**Comment by cazzerson** [comment]
#### Description
After installing emacs on OSX as described in the documentation and installing the spacemacs packages and restarting emacs, I am able to select vim mode and the defaul spacemacs distribution, but see the following error:

```
Warning (initialization): An error occurred while loading `/Users/XXX/.emacs.d/init.el':
    
Search failed: dotspacemacs-editing-style 'vim
```

This also seems to prevent the .spacemacs file from being created.

#### Reproduction guide
- Install emacs-mac-port using homebrew method described in the README
- Run emacs
- Restart emacs

```
Warning (initialization): An error occurred while loading `/Users/XXX/.emacs.d/init.el':

Search failed: dotspacemacs-editing-style 'vim
```
Additionally, I see the following error:

```
Symbol's function definition is void: projectile-mode
```

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: nil (rev. nil)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

I am running OSX 10.11.2 and iTerm2. I see the same error with the desktop emacs.

#### Backtrace
```
Dotfile wizard installer
Debugger entered--Lisp error: (search-failed "dotspacemacs-editing-style 'vim")
  re-search-forward("dotspacemacs-editing-style 'vim")
  (while --dolist-tail-- (setq p (car --dolist-tail--)) (goto-char (point-min)) (re-search-forward (car p)) $
  (let ((--dolist-tail-- preferences) p) (while --dolist-tail-- (setq p (car --dolist-tail--)) (goto-char (p$
  (save-current-buffer (set-buffer (find-file-noselect (concat dotspacemacs-template-directory ".spacemacs.t$
  (let ((preferences (if arg (progn (list (list "dotspacemacs-editing-style 'vim" (format "dotspacemacs-edit$
  dotspacemacs/install(with-wizard)
  (if (dotspacemacs/install (quote with-wizard)) (progn (dotspacemacs/sync-configuration-layers (quote (16))$
  (if (file-exists-p dotspacemacs-filepath) nil (spacemacs-buffer/set-mode-line "Dotfile wizard installer") $
  spacemacs/maybe-install-dotfile()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%$
  eval-buffer(#<buffer  *load*> nil "/Users/XXX/.emacs.d/init.el" nil t)  ; Reading at buffer position $
  load-with-code-conversion("/Users/XXX/.emacs.d/init.el" "/Users/XXX/.emacs.d/init.el" t t)
  load("/Users/XXX/.emacs.d/init" t t)
```

**Comment by cazzerson** [comment]
Hold off a minute--I'm using rcm to manage configs and setting it to symlink directly to the emacs.d directory looks like it may be improving things.

**Comment by cazzerson** [comment]
Yes, that did it--my apologies. Thanks for your help.
