### ISSUE TITLE
Make evil-scroll-*  behave like it supposed to (i.e.  like in Vim)

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#4833]
[Vim docs](http://vimdoc.sourceforge.net/htmldoc/scroll.html): 

```org

							*CTRL-D*
CTRL-D			Scroll window Downwards in the buffer.  The number of
			lines comes from the 'scroll' option (default: half a
			screen).  If [count] given, first set 'scroll' option
			to [count].  The cursor is moved the same number of
			lines down in the file (if possible; when lines wrap
			and when hitting the end of the file there may be a
			difference).  When the cursor is on the last line of
			the buffer nothing happens and a beep is produced.
			See also 'startofline' option.
			{difference from vi: Vim scrolls 'scroll' screen
			lines, instead of file lines; makes a difference when
			lines wrap}
```

[Evil's heresy](https://github.com/emacsmirror/evil/blob/2522e54c0eb9d4606f550d4d4d484deec579fc1a/evil-commands.el#L859)

```elisp
(evil-define-command evil-scroll-down (count)
  "Scrolls the window and the cursor COUNT lines downwards.
The default is half the screen."
  :repeat nil
  :keep-visual t
  (interactive "P")
  (evil-save-column
    (let ((p (point))
          (c (or count (/ (evil-num-visible-lines) 2))))
      (save-excursion
        (scroll-up (min (evil-max-scroll-down) c)))
      (forward-line c)
      (when (= (line-number-at-pos p)
               (line-number-at-pos (point)))
        (signal 'end-of-buffer nil)))))
```

In Vim you can set the speed with which `C-d` will scroll. This behavior is really useful for the reading stuff with "different density" or glancing over. But in Evil it doesn't remember the last argument so you have to press `5` `C-d` `5` `C-d` each time or it will scroll for a half of screen(default).

**How about canonizing its behavior with a wrapper ?**

**Comment by TheBB** [comment]
> How about canonizing its behavior with a wrapper ?

How about reporting it to evil first? Better if we don't have to write a wrapper.

https://bitbucket.org/lyro/evil/wiki/Home

**Comment by TheBB** [comment]
Word of advice though, don't go to Evil calling it useless and a heresy…

**Comment by JAremko** [comment]
@TheBB  Yeah I edited my issue after posting it. I agree, It was over the top. 
And good advice btw! I'll ask them why they don't respect Vim so much in a very respectful manner.

**Comment by JAremko** [comment]
Closing the issue for the time being

**Comment by philc** [comment]
For future reference, @JAremko filed the issue [here](https://bitbucket.org/lyro/evil/issues/612/).

**Comment by JAremko** [comment]
[Solved upstream](https://bitbucket.org/lyro/evil/commits/43aac5cf8f3604d56e27ac6b14ec7e22661eabdd)
