### ISSUE TITLE
Make gf not prompt with helm if file exists in normal state

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#4837]
#### Description

`gf` shouldn't prompt with `helm` if file already exits and visitable. The normal behaviour of vim is to visit that file directly.
#### Reproduction guide
- Start Emacs
- On a valid file under point(e.g. `~/.spacemacs`), in normal state, press `gf` 

_Observed behaviour:_
Opens up `helm` prompt where you have to hit return to visit the file.

_Expected behaviour:_
You shouldn't need to hit return in case file is present and readable.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. 72e1413)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip nil auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" :disabled-for org erc)
 semantic better-defaults emacs-lisp
 (git :variables git-gutter-use-fringe t git-magit-status-fullscreen nil)
 github markdown yaml shell
 (spell-checking :variables spell-checking-enable-by-default t spell-checking-enable-auto-dictionary t)
 syntax-checking
 (elfeed :variables rmh-elfeed-org-files
         (list "~/.emacs.d/private/elfeed.org"))
 lua python ruby ruby-on-rails
 (clojure :variables clojure-enable-fancify-symbols t)
 shell-scripts html javascript dockerfile eyebrowse spacemacs-layouts
 (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu4e/")
 nix-mu4e gnus colors deft finance
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (version-control :variables version-control-diff-tool 'diff-hl)
 ansible emoji ranger osx typography
 (theming :variables theming-headings-inherit-from-default 'all theming-headings-same-size 'all theming-headings-bold 'all)
 org)
```

**Comment by CestDiego** [comment]
this ^

**Comment by nixmaniack** [comment]
@StreakyCobra To me, it looks this is a bug rather than enhancement.

**Comment by TheBB** [comment]
http://stackoverflow.com/questions/12987483/emacs-function-automaticly-accepting-prompt

**Comment by StreakyCobra** [comment]
@nixmaniack As far as understand there is no wrong behavior here, no? I mean, it would be a better default and closer to vim of course, but currently this is the intended behavior.

Feel free to correct me if I'm wrong :-)

**Comment by Andre0991** [comment]
If someone creates a PR, please make this configurable. I actually like getting to a Helm session because I can choose other actions too.

**Comment by nixmaniack** [comment]
Okay, may be an enhancement at spacemacs but certainly a bug at evil! :smile: Should this be reported upstream?

**Comment by StreakyCobra** [comment]
Oh, I think I understand your point now, why you say it's maybe a bug.

Can you try in a raw emacs with `evil` only if `gf` directly open the file or if it prompts for it? If it prompts for it then it means that spacemacs is doing it correctly by just replacing the prompt with helm. If it opens directly the file, it means that we are doing it wrong as we ask for the file.

**Comment by zakkak** [comment]
`gf` both in spacemacs and *vanilla* emacs invokes `find-file-at-point` which prompts for the file, so I guess this should be *fixed* in `evil-mode`.

**Comment by nixmaniack** [comment]
Reported upstream: https://bitbucket.org/lyro/evil/issues/614/make-gf-not-prompt-if-file-exists-in

**Comment by StreakyCobra** [comment]
@nixmaniack :+1: Thanks

**Comment by nixmaniack** [comment]
Relocated upstream issue link: https://github.com/emacs-evil/evil/issues/614
