### ISSUE TITLE
Disable N (reverse search) in magit-status to enable activating magit-svn-mode

### ISSUE THREAD

**Issue by epitzer** [syl20bnr/spacemacs#484]
When invoking magit-status the N key should invoke the magit-svn submenu (if loaded), however it is overriden by evil-mode's N (reverse search).

**Comment by syl20bnr** [comment]
@epitzer since  0.50.0 `magit-svn` is now part of the `git layer`. To enable it set `git-enable-magit-svn-plugin` to `t` in your dotfile. See the updated README of the `git layer`.

This also fixes the `N` issue.

**Comment by cdlm** [comment]
This still seems to be broken… when in a magit-status buffer, typing `N` gets me the message `"svn": pattern not found`
