### ISSUE TITLE
Reconsider (progn) convention for :config and :init

### ISSUE THREAD

**Issue by peterhoeg** [syl20bnr/spacemacs#4843]
As per the docs, (progn) is supposed to be used for ```:init``` and ```:config```, however according to use-package itself, this is not necessary. In previous versions however, this was a requirement.

Maybe we can consider getting rid of that requirement to avoid one level of nesting?

Reference:
 - https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org#use-package

**Comment by nixmaniack** [comment]
For me, it allows easier navigation and structural editing of `:init` and `:config` that was one of the reasons to keep `progn`(I think) even though `use-package` makes it optional.

**Comment by TheBB** [comment]
Yep, the explicit `progn` makes it a lot easier to use structured editing tools in lisp.

**Comment by peterhoeg** [comment]
I'll just shut up then. ;-)

**Comment by noctuid** [comment]
@TheBB Could you explain what you mean by that?

**Comment by TheBB** [comment]
Like the bindings under `SPC k`. It's easier to use them if an `:init` block or a `:config` block is contained in one sexp rather than being several (but not all) sibling sexps.

**Comment by syl20bnr** [comment]
The :config value is just one list instead of multiple lists, it make it easier to use paredit and the like to edit the code. Sometimes we have a lot of stuff in just one :config. How do you know easily when you are inside the :config keyword or another one if there is more than one value (list) for :config ?

**Comment by noctuid** [comment]
I was considering doing this in my own use-package sexps initially for stylistic reasons. Use-package's non-standard use of keywords is kind of strange, and I can see how actions that involve acting on the entire argument to a keyword would be quicker when it is a single sexp. That said, I can't think of common example for when I'd want to do that. Normally I'm adding or deleting from these sections as opposed to doing something like deleting them entirely. As for the jump example, that doesn't involve acting on the entire section (unless you plan on acting on it as a whole after jumping). If I wanted to jump to a specific part of the :config section, I'd just jump directly to that sexp even if there was a progn.
