### ISSUE TITLE
Doesn't work with emacs-bin-w64-20151110-9145e79 in windows 10

### ISSUE THREAD

**Issue by sahinyanlik** [syl20bnr/spacemacs#4845]
I clone the code inside of /username/.emacs.d
When I run emacs I just see blank screen, there is nothing it hang up, and screen can not be closed

I am using windows 10

**Comment by TheBB** [comment]
Does it work without Spacemacs?

**Comment by chantisnake** [comment]
I have the exact same issue. It can work without spacemacs, I have installed evil and auxtex on it.

but not working for spacemacs...

**Comment by chantisnake** [comment]
my issue is here:
https://github.com/syl20bnr/spacemacs/issues/5284
