### ISSUE TITLE
php-extra package fails

### ISSUE THREAD

**Issue by emielvangoor** [syl20bnr/spacemacs#4849]
When I install the php layer the installation of php-extras fails with the following message:

```
--> installing package: php-extras@php... [1/1]
An error occurred while installing php-extras (error: (wrong-type-argument arrayp nil))

```

When I look at the messages buffer I see the following message:
```
Updating c:/Users/emiel/.emacs.d/.cache/quelpa/build/php-extras/
c:/Users/emiel/.emacs.d/.cache/quelpa/build/php-extras/php-extras-gen-eldoc.el -> c:/Users/emiel/AppData/Local/Temp/php-extras37632vGu/php-extras-20150127.2203/php-extras-gen-eldoc.el
c:/Users/emiel/.emacs.d/.cache/quelpa/build/php-extras/php-extras.el -> c:/Users/emiel/AppData/Local/Temp/php-extras37632vGu/php-extras-20150127.2203/php-extras.el
c:/Users/emiel/.emacs.d/.cache/quelpa/build/php-extras/dir -> c:/Users/emiel/AppData/Local/Temp/php-extras37632vGu/php-extras-20150127.2203/dir
Wrote c:/Users/emiel/.emacs.d/.cache/quelpa/packages/php-extras-readme.txt
Error getting PACKAGE-DESC: (file-error Opening input file no such file or directory c:/Users/emiel/.emacs.d/.cache/quelpa/packages/php-extras-20150127.2203.tar)

```

I'm running Windows 10 with emacs-24.5.1 and spacemacs-0.105.9. I also installed the same versions of emacs and spacemacs with the same layers on my Macbook without any problems...

**Comment by StreakyCobra** [comment]
Can you try to run `emacs --insecure`?

**Comment by emielvangoor** [comment]
@StreakyCobra I tried running with the insecure flag but got the same results.. I also tried deleting the cache before running the command but that didn't work either.

**Comment by bmag** [comment]
From http://spacemacs.org/doc/FAQ.html:
> 1.15 Why do I get (wrong-type-argument arrayp nil) errors on startup?
>
> This is most likely caused by a corrupted package archive. Try deleting your ~/.emacs.d elpa/archives/ folder and restart Emacs.

Have you tried that?

**Comment by emielvangoor** [comment]
@bmag Yes I did try that.. I even tried deleting the whole `~/.emacs.d/elpa/` folder and let Spacemacs compile all the packages again, but still got the same message..

**Comment by StreakyCobra** [comment]
Weird. It may be a stupid question, but do you have git installed and does emacs has the path correctly configured to find it?

**Comment by emielvangoor** [comment]
@StreakyCobra I do have git installed, I don't know how to check if emacs has the path correctly configured to it but when I run a shell command from emacs I can access git..

**Comment by emielvangoor** [comment]
I installed the git layer, and I can acces git..

**Comment by StreakyCobra** [comment]
Ok, I'm not really sure how quelpa works, but in my case it uses git to access php-extra:

```
Cloning into '/home/fabien/.emacs.d/.cache/quelpa/build/php-extras'...
HEAD is now at c269ab4 Merge branch 'release/2.2.1' into develop
'php-extras-20150127.2203/
php-extras-20150127.2203/php-extras-pkg.el
php-extras-20150127.2203/dir
php-extras-20150127.2203/php-extras.el
php-extras-20150127.2203/php-extras-gen-eldoc.el
2015-01-27 22:03:16 +0100'
```

and I don't have any `tar` file in `.emacs.d/.cache/quelpa/build`. It may be a different installation process for Windows.

**Comment by emielvangoor** [comment]
@StreakyCobra I don't have a `tar` files either.. If i look at the `*Messages*` buffer I can see that the fetcher for php-extra@php is Github.

**Comment by StreakyCobra** [comment]
So why is it looking for one?

```
Error getting PACKAGE-DESC: (file-error Opening input file no such file or directory c:/Users/emiel/.emacs.d/.cache/quelpa/packages/php-extras-20150127.2203.tar)
```

**Comment by StreakyCobra** [comment]
Let's wait for people used to quelpa, they may know the process.

**Comment by emielvangoor** [comment]
Still having the same problemens with version 0.105.14... Is there something I should try next?

**Comment by StreakyCobra** [comment]
I  don't know what to try next. And I don't know whom to ask for windows/quelpa help neither :-/ Sorry

**Comment by emielvangoor** [comment]
@StreakyCobra It's okay.. I forgive you ;-)

**Comment by bmag** [comment]
@emielvangoor Just to make sure, do you have `tar` installed? You can check by running `M-: (executable-find "tar")`. The requirements for windows are list in [quelpa's readme](https://github.com/quelpa/quelpa#windows-instructions) (although I guess you already went through them).

**Comment by emielvangoor** [comment]
@bmag Yes, I did have `tar` installed.. I didn't look at the quelpa's readme, I followed it by installing Emacs with Cygwin and now it works! Thanks

**Comment by CMCDragonkai** [comment]
I have `tar` installed from Cygwin, however I'm using the native build of Emacs 64 bit, so how is it going to find the `tar` necessary for quelpa?

**Comment by nlmayday** [comment]
I also encountered this problem. Has anyone solved it?
Windows 10 with emacs-25.3 and spacemacs-0.200.13@25.3.1

**Comment by nlmayday** [comment]
this may "makefile" command could not execute on windows, so there are no php-extras-20160518.2316.tar file in ".cache/quelpa/packages".
and i try to download this file from github, move it to ".cache/quelpa/packages", it works....skrrrrrrrr
