### ISSUE TITLE
Spacemacs introduction does not propose hybrid style

### ISSUE THREAD

**Issue by DamienCassou** [syl20bnr/spacemacs#4851]
When starting spacemacs for the first time, `emacs` and `vim` styles are proposed, but not `hybrid`.

**Comment by StreakyCobra** [comment]
I thought it has been corrected, it seems that no :-) Maybe there was a reason…

**Comment by nixmaniack** [comment]
`hybrid` is the spacemacs invented style(AFAIK) and people aren't aware of it until they try spacemacs. OTOH, `emacs` and `vim` are well known styles.

**Comment by izahn** [comment]
I think that in context the meaning of `hybrid` is clear. That is, given `vim/emacs/hybrid` most will correctly infer that hybrid uses both Emacs and Vim conventions and bindings. I don't think it will confuse to many people to include it, and IMO hybrid is actually the most useful of the three styles, so I would like to see if offered by the first-run wizard thingy.

**Comment by sooheon** [comment]
there is no mention of `hybrid` in the `dotspacemacs-editing-style` docstring, either.

**Comment by d12frosted** [comment]
Fixed by #5308
