### ISSUE TITLE
Error in init file: error: "Format specifier doesn't match argument type"

### ISSUE THREAD

**Issue by blazeeboy** [syl20bnr/spacemacs#4852]
i'm on OSX Elcapitan, GNU Emacs 22.1.1 is installed by default, tried to install spacemacs but when i start emacs it shows this error in the command area `Error in init file: error: "Format specifier doesn't match argument type"` tried to `brew install emacs` and it downloaded and installed emacs-24.5`, also when i execute `emacs` it gives me the the older version, and also spacemacs doesn't show up and shows the same error

**Comment by blazeeboy** [comment]
the emacs version problem solved by `brew doctor` it advised me to execute this line 
```
echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.zshrc
```
and then i reloaded this zshrc file
```
source ~/.zshrc
```
and then emacs version is 24 as expected.

**Comment by syl20bnr** [comment]
>  Error in init file: error: "Format specifier doesn't match argument type"

Reopening to investigate this error when spacemacs is used with Emacs 22

**Comment by iryan2** [comment]
Just here to say thanks, had the same problem and this solved it.

**Comment by TheBB** [comment]
Code triage sent me here and I think this can be closed. It's a rare error, only produced on Emacs 22 (!) so far and if it comes up again it's not a big problem to backtrace it.
