### ISSUE TITLE
HOWTOs pages doesn't exists anymore

### ISSUE THREAD

**Issue by blazeeboy** [syl20bnr/spacemacs#4853]
`http://spacemacs.org/doc/HOWTOs.html` doesn't exist and was referenced in [here](http://spacemacs.org/doc/QUICK_START.html#orgheadline2)

**Comment by malcook** [comment]
it is still referenced [here](http://spacemacs.org/doc/QUICK_START.html#orgheadline12)

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
