### ISSUE TITLE
Not clear how to show a right margin line.

### ISSUE THREAD

**Issue by amichail** [syl20bnr/spacemacs#4856]
I would like to limit most lines of code to 100 characters.

Is there a recommended package for making this easy to do by showing a right margin line? If so, maybe it should be mentioned in the documentation?

**Comment by JAremko** [comment]
[Column enforce mode](https://github.com/jordonbiondo/column-enforce-mode/)

![img](https://camo.githubusercontent.com/e777c61bb66bb40dbb119be6c62f0cc994c8a1b1/687474703a2f2f692e696d6775722e636f6d2f45657a614f6f392e706e67)

**Comment by JAremko** [comment]
Also `SPC` `t` `f`	display the fill column (by default the fill column is set to 80)

**Comment by StreakyCobra** [comment]
Yes, `SPC t f` is what you want. You can activate it on all relevant buffers with this:

```elisp
  ;; Activate column indicator in prog-mode and text-mode
  (add-hook 'prog-mode-hook 'turn-on-fci-mode)
  (add-hook 'text-mode-hook 'turn-on-fci-mode)
```

You can also press `M-q` to automatically fill paragraphs to the value of `fill-column`. Note it can be customized with:

```elisp
(setq-default fill-column 100)
```

in your `user-init`. Does this answer your question?

**Comment by amichail** [comment]
Is there a way to make the line color more subtle for fci-mode?

**Comment by nixmaniack** [comment]
@amichail `(setq fci-rule-color "#FF0000")`. You can choose the color you want instead of "#FF0000"

**Comment by amichail** [comment]
I got it working! Thanks!

**Comment by DanBurton** [comment]
Googled this up, and @StreakyCobra's answer is exactly what I was looking for.

Weirdly, `(setq-default fill-column 100)` in my `user-init` wasn't working, so I did this instead:

```elisp
(defun fill-column-100 ()
  (set-fill-column 100))

;; later, in user-init
  (add-hook 'prog-mode-hook 'fill-column-100)
  (add-hook 'text-mode-hook 'fill-column-100)
```
