### ISSUE TITLE
reStructuredText layer

### ISSUE THREAD

**Issue by gour** [syl20bnr/spacemacs#4860]
Hello,

moving back to (Spac)Emacs from Vim and it would be nice to have layer supporting reStructuredText using rst.el for writing docs using rst/Sphinx markup?

**Comment by StreakyCobra** [comment]
Indeed.

As a temporary workaround, you can try to add `rest` to the `dotspacemacs-additionnal-packages` list in your `.spacemacs`.

**Comment by robbyoconnor** [comment]
@gour, PRs welcome! If you want it, learn how to do it and make it happen.

**Comment by gour** [comment]
@StreakyCobra Thanks, that's good for a start. ;)
@robbyoconnor I will certainly try to help/contribute, just to convert my present vim/Evo/taskwarrior/... setup to Spacemacs/Gnus/Org... :-)

**Comment by robbyoconnor** [comment]
@gour :heart:

**Comment by wwguo** [comment]
I create a ReST layer which adds some functions to the built-in rst.el and supports Sphinx. 

See Pull request #6213.

**Comment by Miciah** [comment]
Looks like #6661 / https://github.com/syl20bnr/spacemacs/commit/9399de0ddc49aa8394fc55342156df9743ea237b resolve this issue.  Can we label the issue as "Fixed in develop"?
