### ISSUE TITLE
The package web-mode should be included in the php layer as well

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#4865]
`web-mode` has support for templating engines such as twig for php. As such, it'd be an improvement to the php layer to include the web-mode package. [Here is an example of a php developer's configuration with web-mode and php-mode](https://truongtx.me/2014/07/22/setup-php-development-environment-in-emacs/). Perhaps this can be used as a starting point for what to add to the configuration?

**Comment by robbyoconnor** [comment]
@thang1thang2, PRs welcome!

**Comment by robbyoconnor** [comment]
@thang1thang2, PRs welcome!  If you want it, learn how to do it and make it happen.

**Comment by natostanco** [comment]
https://www.reddit.com/r/emacs/comments/58p9dq/psa_please_use_web_mode_instead_of_php_mode/

**Comment by robbyoconnor** [comment]
@TheBB with @natostanco's  [comment](https://github.com/syl20bnr/spacemacs/issues/4865#issuecomment-255552364) -- I propose we close this issue.

**Comment by robbyoconnor** [comment]
@TheBB, @d12frosted , @syl20bnr  with @natostanco's  [comment](https://github.com/syl20bnr/spacemacs/issues/4865#issuecomment-255552364) -- I propose we close this issue.

**Comment by robbyoconnor** [comment]
Strike what I said
