### ISSUE TITLE
Annoying warning when starting up in windowed mode in a fresh OS X install

### ISSUE THREAD

**Issue by daghoidahl** [syl20bnr/spacemacs#4867]
I got this warning in `*messages*`  when starting emacs in a regular window (installed with `brew` from `railwaycat/homebrew-emacsmacport`, as suggested in the install docs):

```
Error (use-package): vi-tilde-fringe :init: Symbol's value as variable is void: closed
Warning (initialization): An error occurred while loading `/Users/dagh/.emacs.d/init.el':

Symbol's value as variable is void: closed
```

Looks similar to #50, but everything seems to work fine. It's just a nuisance to get a warning buffer in my face when I start Spacemacs.

**Comment by TheBB** [comment]
You probably have downloaded corrupted packages. Please delete your elpa folder and start Emacs using the `--insecure` flag to turn off HTTPS.

**Comment by TheBB** [comment]
See https://github.com/syl20bnr/spacemacs/issues/4410#issuecomment-170291177

**Comment by daghoidahl** [comment]
That solved it. Thanks!
