### ISSUE TITLE
~,~ not being correctly displayed in documentation

### ISSUE THREAD

**Issue by skebanga** [syl20bnr/spacemacs#4869]
In the documentation ~,~ is not being displayed correctly as `,`

I don't know what the correct escape sequence is to get it to display correctly. 

Eg: see [here](http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline54) - the text should read _"This leader key is commonly set to `,` by Vim users"_, but instead reads _"This leader key is commonly set to ~,~ by Vim users"_

This is likely due to a org mode to markdown conversion issue - perhaps `~,~` has a special meaning in org mode and needs to be escaped?

**Comment by zakkak** [comment]
[Related QA](https://stackoverflow.com/questions/24169333/how-can-i-emphasize-or-verbatim-quote-a-comma-in-org-mode) from stackoverflow. 

Customizing `org-emphasis-regexp-components` seems to be the workaround, but it might break something else (although I doubt it will).

**Comment by avit** [comment]
I tried looking into it to submit a patch but I'm too unfamiliar with Emacs and Org Mode to know how to fix it. I only found this: http://comments.gmane.org/gmane.emacs.orgmode/82571

**Comment by a13ph** [comment]
It probably won't work in github, since they use particular parser (in ruby), with particular settings fixed in. It's not like we export to markdown ourselves.

Maybe some alternative formatting can be used to the same effect, like =verbatim= one (though I suspect it has some other style translation)

**Comment by wood9366** [comment]
Find another document like that

![emacspace_err1](https://cloud.githubusercontent.com/assets/1407539/13072735/df08afc2-d4d5-11e5-82c6-669acf68ca2c.png)

**Comment by avit** [comment]
Oh, I've not even considered Github, I meant the HTML documentation on the official site only, as linked in the original description. The `=verbatim=` markup uses the same separator characters and is affected the same way (outputs `=,=`).
