### ISSUE TITLE
Moe theme in themes-megapack isn't automatically loaded

### ISSUE THREAD

**Issue by Ambrosia** [syl20bnr/spacemacs#487]
Additionally when it is loaded, the `moe` theme shows in the themes list when it shouldn't (not sure who's fault that is though!)

**Comment by syl20bnr** [comment]
I'm not sure to understand the issue. If `moe` does show up in list then it is OK no ?

**Comment by Ambrosia** [comment]
I had to load it manually to get it to show up in the theme list. Also need
to make sure 'moe' itself doesn't show in the theme list. This theme seems
to be pretty different from the rest!
