### ISSUE TITLE
Paging doesn't work in helm for holy-mode

### ISSUE THREAD

**Issue by landtuna** [syl20bnr/spacemacs#4870]
If you're in holy-mode, and you open something with multiple pages in helm, paging doesn't work. In my clean installation from today:

`M-m w` to get into "windows", which is long
`C-h` to get the paging menu
`n` to page down inserts mysterious characters into the buffer and dismisses helm rather than showing the next page

**Comment by justbur** [comment]
That's not helm. It's the which-key package window. Thanks for the report. I fixed the bug you found in the latest commit. The update should be available in a few hours.

**Comment by landtuna** [comment]
Great. Thanks!

**Comment by justbur** [comment]
Can be closed

**Comment by StreakyCobra** [comment]
Closing as requested
