### ISSUE TITLE
react layer doesnt recognize es7 syntax?

### ISSUE THREAD

**Issue by shangsunset** [syl20bnr/spacemacs#4871]
It seems like react layer cant recognize es7 syntax. it treats `spread operator` as a syntax error.  Is there a way to enable es7 support? or its just not there yet?

**Comment by robbyoconnor** [comment]
ES7 isn't official yet -- so make a pull request upstream, we don't actually do anything other than load the mode..

**Comment by robbyoconnor** [comment]
ES7 isn't official yet -- so make a pull request upstream, we don't actually do anything other than load the mode. There is literally nothing we can do.

**Comment by mosic** [comment]
Until `js2-mode` gets proper support for the spread operator you can try using `web-mode` for javascript files, I did that the other day and I'm pretty happy so far.

Just add this to your `.spacemacs` config:

    (add-to-list 'auto-mode-alist '("\\.js\\'" . web-mode))

**Comment by dan-weaver** [comment]
Hey.. Spacemacs / Emacs newcomer.  I'm curious about the responsibilities of js2-mode vs flycheck and eslint.  As shown in the installation for react layer: `npm install -g eslint babel-eslint eslint-plugin-react`.

What does js2-mode even do here?  Why does it have to support spread operator.  Babel already does that.

Thanks!

**Comment by robbyoconnor** [comment]
flycheck just runs the linters/compilers and parses the output using a regexp reports errors back to you -- nothing more. js2-mode is the major-mode for Javascript. There must always be one major-mode active.

**Comment by TheBB** [comment]
I'm closing this since we don't use js2-mode for react. We use web-mode, which does no linting on its own.
