### ISSUE TITLE
How to add company-ispell to company-backends for latex and org layers?

### ISSUE THREAD

**Issue by shivamkalra** [syl20bnr/spacemacs#4878]
I've been trying to add `company-ispell` back-end for  `latex` and `org` layers. I've tried adding:

```
(push 'company-ispell company-backends-LaTeX-mode)
(push 'company-ispell company-backends-org-mode)
```

But none of them seem to work, however I do get following error in my *message* buffer:

```
ispell-look-command not found
```

Any ideas, why this is happening? 

**Note**
There is a *TODO* in `auto-completion` layer regarding addition of `company-ispell` package. May be it has something to do with it?

https://github.com/syl20bnr/spacemacs/blob/develop/layers/auto-completion/packages.el#L30

**Comment by robbyoconnor** [comment]
:eyes: following

**Comment by duerrp** [comment]
Works without a problem here. Are you on linux? `ispell` relies on look and can be configured:
```
(defcustom ispell-look-command
  (cond ((file-exists-p "/bin/look") "/bin/look")
	((file-exists-p "/usr/local/bin/look") "/usr/local/bin/look")
	((file-exists-p "/usr/bin/look") "/usr/bin/look")
	(t "look"))
  "Name of the look command for search processes.
This must be an absolute file name."
  :type 'file
  :group 'ispell)
```

**Comment by shivamkalra** [comment]
@duerrp I'm on Linux and `ispell` command works works but not through company back-end.

**Comment by pA0k** [comment]
see [this page](http://blog.binchen.org/posts/emacs-auto-completion-for-non-programmers.html)

(setq company-ispell-available t) ; error without this
(setq company-ispell-dictionary "english-word.txt)

(defvar company-backends-text-mode '())
(spacemacs|add-company-hook text-mode)
(push 'company-ispell company-backends-text-mode)

**Comment by shivamkalra** [comment]
@pA0k That did the trick. Thanks!
