### ISSUE TITLE
Support symlinks

### ISSUE THREAD

**Issue by dagadbm** [syl20bnr/spacemacs#4881]
Hello all,

I am using spacemacs with latest emacs64b from recommended source in windows.
I have an .emacs.d symlink pointing to a different folder on my home path. 
Everything mostly works but when I open spacemacs it can't find .emacs.d\.cache\layouts\persp-auto-save. (I am using perspective features)
I have checked the real location on my computer and the file exists. 
Is this a bug or am I not doing something correctly?

Regards,

dagadbm.

**Comment by justbur** [comment]
As far as I can see symlinks work on windows. How are you adding them? MKLINK?

**Comment by dagadbm** [comment]
yes mklink /d.

I stopped using prespectives anyway.
Doesn't make sense when you understand how it all works together and SPC b b is miraculous.
