### ISSUE TITLE
Can we use `SPC B` mnemonic for bookmark related bindings?

### ISSUE THREAD

**Issue by balajisivaraman** [syl20bnr/spacemacs#4884]
EDIT: This was supposed to be an issue for the behaviour of the `SPC j b` keybinding. But it has since been established that the current way for searching bookmarks is using `SPC f b`.

Therefore, I am leaving this issue open to discuss the possibility of having mnemonic keybindings for bookmark operations on something like `SPC B`. For instance, `SPC B j` for `bookmark-jump`, `SPC B s` for `bookmark-set` and `SPC B l` for `bookmark-list`.

Thoughts?

**Comment by balajisivaraman** [comment]
Oops! My mistake. `SPC f b` is the keybinding in the current `develop` branch that replaced `SPC h b`.

However, I'd still like to discuss the possiblity of having mnemonic keybindings for bookmarks. If that is not necessary, this issue can be closed.

**Comment by nixmaniack** [comment]
`SPC f b` is better `SPC j b` IMO, probably we should use `helm-filtered-bookmarks` under `SPC j b`

**Comment by StreakyCobra** [comment]
@balajisivaraman It can be discussed, can you please update your issue then, it will be easier to find/follow :-)

**Comment by MarcoIeni** [comment]
I think that this whould be really nice. These are some key bindings that comes to my mind:

- `SPC B d` - `bookmark-delete`
- `SPC B J` - `bookmark-jump-other-window`
- `SPC B j` - `bookmark-jump`
- `SPC B l` - `helm-filtered-bookmarks`. This is already associated to `SPC f b`. `helm-bookmarks` also exists.
- `SPC B r` - `bookmark-delete`
- `SPC B s` - `bookmark-set`
