### ISSUE TITLE
mu4e: Enabling mu4e-maildirs-extension by default

### ISSUE THREAD

**Issue by zakkak** [syl20bnr/spacemacs#4892]
Hello @all,

In bb07eeccade0af51b15b7093d4856fe4f2fdb532 the [`mu4e-maildirs-extension`](https://github.com/agpchil/mu4e-maildirs-extension) is enabled by default in the mu4e layer.

I personally find this extension too intrusive/noisy to be enabled by default. I believe that the default options should reflect the common use case and I don't believe that most mu4e users do want mu4e-maildirs-extension, but I might be totally wrong so I would like to hear what the rest of you think.

**Comment by mskorzhinskiy** [comment]
I'm also found this extension too noisy, and I think that it should be disabled by default.

**Comment by jackbaty** [comment]
I'm curious what you mean by "common use case" that would cause most users to want it disabled. I find the extension a useful and obvious (to me) feature of my mail reader. I might have missed it if it needed to be enabled separately (yes, that would have been my fault, but still). 

My experience was improved by it being enabled by default.

**Comment by zakkak** [comment]
I also noticed that the navigation in `mu4e-main-mode` is broken for `evil-mode` users, since `j` is overridden to allow users to jump to directories (the default binding in `mu4e-main-mode`.  As a result, `evil-mode` users cannot navigate to the folders listing of `mu4e-maildirs-extension` using `evil-mode` navigation keybindings.

@jackbaty with "common use case" I refer to the perspective I have obtained about how people use and configure mu4e.  I have obtained this perspective by using mu4e and discussing with other users in its repository and mailing list.  As I point out in my first post, this perspective might be totally wrong and that is why I want to discuss it with everybody else here. Of course if most people think it should be enabled by default, then that should be the case.

PS: In general the use of folders, although intuitive, is

**Comment by jackbaty** [comment]
Thanks for the clarification, @zakkak. I'm (slowly) coming around to the archive-and-search mindset, after years of managing dozens of folders via fcc-hooks etc. in Mutt. 

Thinking about it further, having the maildirs extension enabled by default might encourage people to use mu4e in a way that it wasn't designed for. That, along with the idea of a "common use case" makes me lean toward your suggestion of disabling it by default.

**Comment by nixmaniack** [comment]
I already discussed my opinion about this in that commit comment thread. 

Apart from that, as @zakkak mentioned about mu4e being fully search based and its use of bookmarks, just because of this reason I disabled the default config of maildirs extension and used custom config which uses bookmarks to show the count. This feature of bookmark is very recent addition in maildirs extension and doesn't work fully. 

I think from UX pov, it's not a good default as user should first understand how configure it properly before using it.

**Comment by AlejandroCatalina** [comment]
I agree the default should have maildirs disabled. It's nice to see where are your unread mails, but it should be better in the bookmarks, as it is the center of mu4e.

**Comment by ksjogo** [comment]
We should disable maildirs and support some easier setup for the new multi account functions.

**Comment by paynito** [comment]
Oct 30, 2016 update of mu4e layer seemed to enable mu4e-maildirs-extension by default.  I now can't open mu4e.  This is my error message.

`mu4e-maildirs-extension-new-maildir: Wrong type argument: wholenump, -2 `

**Comment by ksjogo** [comment]
The last change on develop for the layers/+email/mu4e/ folder is from Jul 25, so I am not sure, what you are referring to. Could you point me to the code change. Or was it some elpa package update?

**Comment by paynito** [comment]
after adding this 
`(setq mu4e-maildirs-extension-custom-list '("/School/INBOX" "/Outlook/Inbox"))`
I can start mu4e again.
