### ISSUE TITLE
Visual Block mode with smart paren mode active

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#490]
I have noticed that I get a jumbled mess when I try inserting separators (like paren or quotes) when in visual block mode.  Does everyone else see this as well?  

I am thinking the quickest fix is putting hooks on entering and exiting visual block mode to take away smart paren.   

Anyone else have other suggestions?

**Comment by syl20bnr** [comment]
I have no issue with smartparens but I noticed a regression in `evil-escape` which break visual block insert when `f` is used inside the inserted characters.
I just fixed it and it will be in 0.51.0.

Can you check again with 0.51.0 when it wil be available ?

**Comment by syl20bnr** [comment]
Should be fixed.
Reopen the issue if it is not the case.
