### ISSUE TITLE
Leuven-theme/Org-mode layer conflict

### ISSUE THREAD

**Issue by SeanTAllen** [syl20bnr/spacemacs#4905]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(asciidoc
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
 better-defaults dockerfile emacs-lisp git markdown osx org ponylang python ruby
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking)
```

When using the `org-mode` layer and `leuven-theme` is installed, keybindings in `evil-org` do not get loaded (after restart). Note, this doesn't happen the first time you install org-mode, only after restarting. There's something that happen with installation that doesn't happen on restart that prevents the bug from happening.

Use `spacemacs` distribution (rather than `spacemacs-base` as it doesn't include the `leuven-theme`), turn on org-mode layer and install. Describe keybindings for `<LEADER>-g-j` and you will get `org-forward-heading-same-level`. Restart and return to org-mode, describe g j again and you will get `evil-next-visual-line` as the binding.

You can temporarily fix by deleting helm from elpa directory which when it gets reinstalled will leave you in a working state until you restart. To fix, you have to add leuven-theme to excluded layers.

`dotspacemacs-excluded-packages '(leuven-theme)`

**Comment by Andre0991** [comment]
On develop `gk` and `gj` work as expected here.

`gl` and `gh` don't, regardless of `leuven-theme`. I get `g l is undefined`. Actually, sometimes they work. I have no idea under which condition that happens.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. f386cbc)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx spacemacs-helm emacs-lisp syntax-checking common-lisp git
     (shell :variables shell-default-shell 'eshell)
     spacemacs-layouts erc html pdf-tools
     (elfeed :variables rmh-elfeed-org-files
             (list "/Users/andre0991/Dropbox/backup/emacs/elfeed-feeds.org"))
     themes-megapack semantic
     (auto-completion :variables auto-completion-private-snippets-directory "/Users/andre0991/Dropbox/backup/emacs/yasnippet-snippets/" auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t :disabled-for latex)
     org
     (ranger :variables ranger-show-preview t)
     markdown latex spell-checking version-control andre-common-lisp andre-elfeed andre-osx andre-erc andre-eww)
```
