### ISSUE TITLE
recentf is not updated on file rename

### ISSUE THREAD

**Issue by lislon** [syl20bnr/spacemacs#4909]
After renaming a file using `SPC f R` recentf is still shows old filename.
 
Steps to reproduce: 
1. Open some existing test file (`SPC f f`)
2. Rename it (`SPC f R`)
3. Open recentf (`SPC f r`)

Expected: new filename in the recentf list.
Actual result: old filename in the list.

**Comment by robbyoconnor** [comment]
`M-x recentf-cleanup` or `SPC : recentf-cleanup`

**Comment by lislon** [comment]
Yes, but still I don't see new file in list
