### ISSUE TITLE
Update reference to micro-states

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#4913]
From @balajisivaraman on #4883 

The term micro-state was still being referred to all over the codebase. So I've created this PR in-order to change all of them to transient-state in order to ensure consistency, and also for feedback in case I screw something up. :smiley: 
- [x] Change all `.org` files in `doc` folder to refer to transient states
- [x] Change all layer-specific `README` files to refer to transient states
- [ ] There are some variables across the codebase (For eg: some `faces` vars) that refer to micro-states. I can change these as well if it's OK with you folks.
- [ ] There are places such as `ido` and `workspaces` that refer to micro-states, even though they have been changed to transient states. These might need to be verified to ensure they are not bugs.
- [ ] Magit-blame mode is still a micro-state (only one left). So I've not changed anything related to it as of now.
- [ ] Right now the screenshot files used have simply been renamed. But they should probably be taken anew as well. I'll do that.

**Comment by deb0ch** [comment]
Autumnal cleanup: Is this issue still relevant ?
