### ISSUE TITLE
mu4e-ask-maildir: Symbol’s function definition is void: helm-completing-read

### ISSUE THREAD

**Issue by mrz** [syl20bnr/spacemacs#4917]
Hello,

I've been getting this error when trying to navigate to a maildir in mu4e. The function `helm-completing-read` does not actually exist in my version of helm (updated daily/every two days). I guess this regression was introduced in this commit 2d7d704c5b8bff6d991876672b9852f44d846518.
I grepped for `helm-completing-read` both in ~/.emacs.d and in my ~/.spacemacs.d and that one was the only occurence that I got back. 

#### System Info
- OS: gnu/linux
- Emacs: 25.1.50.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. 18874c9)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm

**Comment by StreakyCobra** [comment]
#4894 or #4813 will fix this

**Comment by mrz** [comment]
Thanks! And sorry for the noise, I searched helm-completing-read in the issues but I found nothing, I thought nobody had found this yet.

**Comment by StreakyCobra** [comment]
No problem, now other users will find it ;-)

**Comment by mrz** [comment]
Can confirm that the error was fixed! Thanks for that! Should I close the issue?

**Comment by StreakyCobra** [comment]
As you wish :-)
