### ISSUE TITLE
`fd` no longer exits magit buffers.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#4924]
From the documentation:

```
The choice of fd was made to be able to use the same sequence to escape from "everything" in Emacs:
```

One of the bullet points specifically mentions magit:

`quit magit buffers`

This no longer works.  Typing `f` opens a menu.

I realize that you can type `q` to exit magit buffers, but that's not what the documentation says.  It "seems" like `q` exits everything now, but I'm not totally sure.

Either `fd` in magit should be fixed, or the documentation should be fixed, it seems.
#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. d9cf37e)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(unscroll auto-completion xkcd emacs-lisp git dash yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors spacemacs-layouts vimscript spacemacs-helm
          (c-c++ :variables c-c++-enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by person808** [comment]
Think this is a documentation issue. `evil-magit` uses `f` for fetching

**Comment by StreakyCobra** [comment]
I tend to agree with @person808.

**Comment by nixmaniack** [comment]
Isn't `fd` based on timers? Like key-chords. If that's the case it should work everywhere if pressed quickly enough.

**Comment by synic** [comment]
I think there should be a sequence that exits everything.  It's not acceptable that `q`, or `fd` should exit one type of buffer, but not another, and the user isn't going to know which is which.  It's clear that having one way was the intention, but I don't know if it's truth anymore, and it's definitely not correct in the documentation.

**Comment by syl20bnr** [comment]
This is an issue between `evil-magit` and `evil-escape`, I'll have to check what's going on.
I don't use `evil-magit` so I did not catch this earlier and vice versa, the `evil-magit` author does not use `evil-escape` :-)

**Comment by syl20bnr** [comment]
An issue can be opened on the `evil-escape` repo.

**Comment by d12frosted** [comment]
Already fixed.
