### ISSUE TITLE
Can't left-click to draw in Artist mode

### ISSUE THREAD

**Issue by jschnurr** [syl20bnr/spacemacs#4926]
Anyone had a problem getting artist-mode to handle the left-click properly for drawing? It seems like it's conflicting with evil-mouse-drag-region. I can create shapes with shift-left-mouse, but anything requiring a simple left click doesn't work - it just highlights text.

**Comment by bmag** [comment]
artist-mode works fine when I'm in emacs state. You can toggle in and out of emacs-state by pressing `C-z`, or you can add this to your config:
```elisp
(defun artist-mode-toggle-emacs-state ()
  (if artist-mode
      (evil-emacs-state)
    (evil-exit-emacs-state)))

(unless (eq dotspacemacs-editing-style 'emacs)
  (add-hook 'artist-mode-hook #'artist-mode-toggle-emacs-state))
```

**Comment by jschnurr** [comment]
That did the trick, thanks @bmag.

**Comment by StreakyCobra** [comment]
@jschnurr If your question has been answered and your problem is fixed, you may consider closing this issue :-)
