### ISSUE TITLE
How to remap : to ; for Evil again?

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#4927]
For the longest time I had `(setq dotspacemacs-command-key ";")` so I can type `;` to trigger evil-ex. I switched to the develop branch and noticed that `dotspacemacs-command-key` is deprecated in favor of `dotspacemacs-emacs-command-key`. Typing `;` results with the message `No previous search` and no longer pops up evil-ex no matter which variable is set. What is the best practice now moving forward?

**Comment by jupl** [comment]
Settled on this new change:

```elisp
(define-key evil-motion-state-map ";" 'evil-ex)
```

**Comment by vyorkin** [comment]
so do I, thanks
