### ISSUE TITLE
No text, only 'rectangles' at first startup

### ISSUE THREAD

**Issue by nyqvist** [syl20bnr/spacemacs#4931]
Hi,

OS: Ubuntu 14.04
emacs version: 24.4.1

1. clone repo: git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
2. start emacs

After starting emacs I only see square characters instead of the real text:
![spacemacs_first_start2016-02-01](https://cloud.githubusercontent.com/assets/1544300/12742535/01e12358-c987-11e5-8e81-8932c2209d50.png)

Using normal emacs works fine.

**Comment by AlejandroCatalina** [comment]
Definitely seems a font issue. You have `Source Code Pro Font` installed? It comes inside an Adobe package whose name i don't recall but it's easy to find.

**Comment by nyqvist** [comment]
Thanks, I had the font installed. To make spacemacs display text I disabled the font.
