### ISSUE TITLE
toggling between normal and evilified state

### ISSUE THREAD

**Issue by manu09** [syl20bnr/spacemacs#4938]
Just for you @StreakyCobra :snake: 
#### Description

org-agenda is toggling between `evil-normal-state` and `evil-evilified-state`
#### Reproduction guide
- Start Emacs
- M-x org-agenda
- hit `evil-escape-key-sequence`
- watch minibuffer to change state

_Observed behaviour:_
I observe org-agenda is changing to `evil-evilified-state` for no reason.

_Expected behaviour:_
I expect org-agenda to not switch to `evil-evilified-state` at all.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Distribution: Arch x86_64
- Layers:

```
     auto-completion
     emacs-lisp
     git
     org
     syntax-checking
     version-control
     dockerfile
     finance
     colors
     emoji
     python
     django
     javascript
     restclient
     html
     php
```
#### Backtrace

no backtrace appeared

**Comment by StreakyCobra** [comment]
Have you updated your packages recently? Also, can you edit your issue with the information of [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? It will help us to help you :-)

For what I see, it seems that it's toggling between `evil-normal-state` and `evil-evilified-state`. But why, that's the question :-)

**Comment by fx3O2** [comment]
#### Description
org-agenda is toggling between `evil-normal-state` and `evil-evilified-state`

#### Reproduction guide
- Start Emacs
- M-x org-agenda
- hit `evil-escape-key-sequence`
- watch minibuffer to change state

*Observed behaviour:*
I observe org-agenda is changing to `evil-evilified-state` for no reason.

*Expected behaviour:*
I expect org-agenda to not switch to `evil-evilified-state` at all.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Distribution: Arch x86_64
- Layers:
```
     auto-completion
     emacs-lisp
     git
     org
     syntax-checking
     version-control
     dockerfile
     finance
     colors
     emoji
     python
     django
     javascript
     restclient
     html
     php
```
#### Backtrace
no backtrace appeared

**Comment by Andre0991** [comment]
Isn't `evilified` the expected Evil state for org agenda? Did you mean that it's changing to `normal`? Or am I confusing things here?

**Comment by fx3O2** [comment]
@Andre0991 I dont know what the default state of org-agenda is. I only know it is toggling between 2 states.

**Comment by StreakyCobra** [comment]
Whenever I press the `evil-escape-key-sequence` it's leaving org-agenda, so I can't reproduce :-/

**Comment by fx3O2** [comment]
@StreakyCobra I just noticed the same problem in `neotree`.

**Comment by StreakyCobra** [comment]
@fx3O2 I can't reproduce it there too.

**Comment by TheBB** [comment]
I can reproduce.

**Comment by StreakyCobra** [comment]
@TheBB Can you try to change the `evil-escape-key-sequence` to something else, totally different from `fd`? In my case it's `gq`, if it may behave differently.

**Comment by d12frosted** [comment]
Is it still reproducible?

**Comment by manu09** [comment]
@d12frosted Yes, still reproducible!

**Comment by d12frosted** [comment]
@TheBB is it a non-fix with described workaround or should it be fixed? 😸

**Comment by TheBB** [comment]
I honestly am not sure but we can postpone it until or if we have a discussion on this behaviour in evilified state.
