### ISSUE TITLE
emacs 24.5.1 freezes on archlinux

### ISSUE THREAD

**Issue by andysaini** [syl20bnr/spacemacs#4939]
Installation concluded successfully, upon launch emacs bar goes full, but it doesn't register *any* input after that... have to issue pkill emacs to close it.

**Comment by StreakyCobra** [comment]
I also have archlinux, so probably the same emacs version as you. Can you try [this](https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-is-spacemacs-hanging-on-startup)? It's an issue that make spacemacs wait for about 2 minutes, it may be the cause.

**Comment by andysaini** [comment]
worked, should I close the issue for now?

**Comment by StreakyCobra** [comment]
Glad to hear. Yes the issue can be closed, I can also do it actually :-)
