### ISSUE TITLE
`SPC t w` twice in magit buffer kills colors

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#4940]
As title. Expected behavior is that the previous colors in the window would return after toggling whitespace display back off, which is what usually happens in other modes.

**Comment by TheBB** [comment]
If this is reproducible in stock Emacs (+ magit) it should be reported to magit.

**Comment by lazywithclass** [comment]
Reproduced in stock Emacs + magit, colors killed. I've opened an issue in magit.

**Comment by d12frosted** [comment]
@lazywithclass thanks for reporting it upstream! Closing since already fixed there.
