### ISSUE TITLE
evil-jump-backward not working as expected after `SPC s h d`

### ISSUE THREAD

**Issue by eltechnic0** [syl20bnr/spacemacs#4942]
After doing a `symbol highlight` -> `go to definition`, `evil-jump-backward` does not jump back to the place before the jump to the definition. I guess the jump is not stored in the jump list, or no mark is set... I don't know the inner workings. Is this fixable?

**Comment by eltechnic0** [comment]
Apparently, `spacemacs/evil-smart-goto-definition` is not pushing the mark in `c-mode` and `c++-mode`, whereas in `emacs-lisp-mode` it works perfectly. The `evil-jump-hook` is set in evil's `pre-command-hook` and `evil-jumper-mode` is enabled - factory settings here. So I don't understand why I can't go back to the place before the jump. Any ideas?

**Comment by eltechnic0** [comment]
I've made some more research and this is what I got:

`evil-goto-definition` on its own sets the mark properly. It does so in the following way: when the command is executed, somewhere in the code (couldn't find where) the variable `this-command` is set to `evil-goto-definition` as expected. Then when evil's `pre-command-hook` executes`evil-jump-hook`, the variable `this-command` is used to check if the current command has the property `:jump`, and if it does, a jump is set.

I think that the problem comes with `spacemacs/evil-smart-goto-definition`, in that the `this-command` variable is no longer set to `evil-goto-definition` if the spacemacs' wrapper is used, but to `spacemacs/evil-smart-goto-definition`, which does not have a `:jump` property.

I am not a lisp expert, but I can think of two ways to fix this: either set the `:jump` property to the spacemacs' wrapper, if that is possible, or add a `(setq this-command 'evil-goto-definition)` somewhere. Please let me know if this is fine, thanks.

**Comment by eltechnic0** [comment]
Currently this is working for me:

`(evil-set-command-property 'spacemacs/evil-smart-goto-definition :jump t)`

**Comment by StreakyCobra** [comment]
@eltechnic0 Your solution seem legit, you can open a PR to discuss it. Please read [our contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org) first. The line should probably be added [here](https://github.com/syl20bnr/spacemacs/blob/a111f4802d850c32a2ef6ff6c2d62cc6c0861b84/layers/%2Bdistribution/spacemacs-base/packages.el#L313).

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
