### ISSUE TITLE
Autocompletiong popup window distorted in org mode

### ISSUE THREAD

**Issue by badders** [syl20bnr/spacemacs#4943]
Presumably due to org-indent-mode, but with global-company-mode enabled the completion popup seems to be all disjoined such as:

> **\* Some nested thing  sta[suggestion1]
>                                                 [suggestion2]
>                                   [suggestion3]

I.e. each suggestion line isnt aligned correctly, no problem in other modes. Possibly similar to company-mode#

**Comment by robbyoconnor** [comment]
@badders thanks for your bug report. Please follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)

**Comment by fbergroth** [comment]
Not any easy solutions, see company-mode/company-mode#207.
