### ISSUE TITLE
Can't read anaconda-mode server response

### ISSUE THREAD

**Issue by wulei** [syl20bnr/spacemacs#4952]
HTTP/1.1 200 OK
Server: nginx/1.7.10
Date: Thu, 04 Feb 2016 01:44:25 GMT
Content-Type: text/html
Content-Length: 683
Last-Modified: Fri, 20 Mar 2015 06:38:57 GMT
Connection: keep-alive
ETag: "550bc081-2ab"
Accept-Ranges: bytes

<html><head></head><script type="text/javascript">
var sa = "http://202.102.110.207:8080/"; var pp = "111&pre="+(new Date()).getTime();
var s=String(window.location.href); var host=escape(s.substring(7,s.indexOf('/',7)));
var ref=escape(document.referrer); var su = s+"&host="+host+"&refer="+ref+"&server="+pp;
s = escape(s); function loadfr(){ document.getElementById("fr1").src = sa+"3.htm?AIMT="+su; }
function refreshPage(){ document.location = sa+"2.htm?AIMT="+su; }
if (self.location == top.location){ document.location= sa+"1.htm?AIMT="+su; }
else { refreshPage(); }</script><frameset rows="*,0"><frame id="main" src="">
<frame id="fr1" src=""></frameset><body></body></html>

**Comment by StreakyCobra** [comment]
Please update your message to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report). It will help us to help you :-) Thanks

**Comment by wulei** [comment]
@StreakyCobra 
printscreen:
![aee51d5a-8d39-11e5-8951-fb22b7b27e52](https://cloud.githubusercontent.com/assets/1661601/13042965/cf9f27fe-d3ff-11e5-8de0-9327554758b8.png)

**Comment by wulei** [comment]
hi, I have the problem , python version 2.7.11
Can't read anaconda-mode server response

**Comment by wulei** [comment]
<html><head></head><script type="text/javascript">
var sa = "http://202.102.110.207:8080/"; var pp = "111&pre="+(new Date()).getTime();
var s=String(window.location.href); var host=escape(s.substring(7,s.indexOf('/',7)));
var ref=escape(document.referrer); var su = s+"&host="+host+"&refer="+ref+"&server="+pp;
s = escape(s); function loadfr(){ document.getElementById("fr1").src = sa+"3.htm?AIMT="+su; }
function refreshPage(){ document.location = sa+"2.htm?AIMT="+su; }
if (self.location == top.location){ document.location= sa+"1.htm?AIMT="+su; }
else { refreshPage(); }</script><frameset rows="*,0"><frame id="main" src="">
<frame id="fr1" src=""></frameset><body></body></html>
m?AIMT="+su; }
else { refreshPage(); }</script><frameset rows="*,0"><frame id="main" src="">
<frame id="fr1" src=""></frameset><body></body></html>

**Comment by xarthurx** [comment]
same problem!
