### ISSUE TITLE
with ivy, M-y is broken

### ISSUE THREAD

**Issue by nbecker** [syl20bnr/spacemacs#4959]
with ivy, M-y is broken. It's bound to helm-show-kill-ring and I get Debugger entered--Lisp error: (wrong-type-argument commandp helm-show-kill-ring)
call-interactively(helm-show-kill-ring nil nil)
command-execute(helm-show-kill-ring)

**Comment by AlejandroCatalina** [comment]
Actually, I would say that `M-y` binding is from your configuration when you used helm, am I right? I've been inspecting `spacemacs-ivy` bindings and `M-y` just isn't there.

**Comment by nbecker** [comment]
Yes, I had a stray binding in my .spacemacs, operator error :)
