### ISSUE TITLE
Python: anaconda "go to definition" keybinding

### ISSUE THREAD

**Issue by abaitam** [syl20bnr/spacemacs#496]
The Python documentation says that to go to a definition press the keybindings:
SPC m g
But this actually brings the key-guide with a single option to press "g" one more time to actually go to the definition (SPC m g g). Either the documentation or better the keybinding itself should be changed.

**Comment by syl20bnr** [comment]
In order to be able to use the prefix `<SPC> m g` for other go to action `<SPC> m g` is now `<SPC> m g g` for go to thing at point.
Basically twice the same letter means `thing at point`, this is the case for `<SPC> m h h` (documentation) and `<SPC> m t t` (tests) at least.

**Comment by syl20bnr** [comment]
I will update the python layer README
