### ISSUE TITLE
border of the modeline

### ISSUE THREAD

**Issue by zxcvbn97** [syl20bnr/spacemacs#4965]
Hi there,

Is there anyway to disable the border of the modeline with solarized dark theme. The border is the gray line under the smart modeline in the attached image. Thanks!
![image](https://cloud.githubusercontent.com/assets/9757976/12768763/a579cf7e-c9d7-11e5-84dc-66c2196537f5.png)

**Comment by StreakyCobra** [comment]
You can try to have a look in #3456 if there are some configurations that correct this.

**Comment by TheBB** [comment]
If you like solarized I recommend using sanityinc-solarized-dark instead of bbatsov's version.
