### ISSUE TITLE
* in find-file gives no result

### ISSUE THREAD

**Issue by magnetophon** [syl20bnr/spacemacs#4968]
#### Description
- * in find-file gives no result

#### Reproduction guide
- Start Emacs
- ```C-c C-f```
- ```*.txt```

*Observed behaviour:*
- helm displays ```[No match]```

*Expected behaviour:*
- open all files in ```~``` ending in ```.txt```

#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 91f653e)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t)
 dash erc emacs-lisp
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 eww extra-langs fasd git github gnus markdown mu4e nixos org ranger shell search-engine semantic
 (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
 spell-checking syntax-checking version-control vimscript)
```

#### Extra info

```find-file-wildcards``` is ```t```.

It works in `emacs -q` but not in bare Spacemacs v.0.105.9

Edit: [@StreakyCobra] Formatting

**Comment by StreakyCobra** [comment]
Could you please update your message to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? It will help us to help you :-)

**Comment by AlejandroCatalina** [comment]
Could you try `~/.txt`?

**Comment by magnetophon** [comment]
@AlejandroCatalina 
The 1st one shows the files in helm and opens the first one on enter.
The 2nd one opens a new file.

I'd like to be able to use this in my config.

**Comment by magnetophon** [comment]
@AlejandroCatalina 
The 1st one shows the files in helm and opens the first one on enter.
The 2nd one opens a new file.

I'd like to be able to use this in my config.

**Comment by AlejandroCatalina** [comment]
You just did. Those are emacs regular expresions. In emacs regular expressions a * is a normal symbol, unless it appears after a special symbol (such as `.`). You were trying to search *all files ending in* **.txt**. In emacs you can do so by the regex `.*\.txt`. Note the `\.` will match an actual dot, while the not escaped dot will mean *whatever*.

**Comment by magnetophon** [comment]
@AlejandroCatalina
We seem to have a miscommunication:
When I enter ```~/.*\.txt``` in ```find-file``` it opens up an new file in ```~```, named ```.*\.txt```.

**Comment by AlejandroCatalina** [comment]
Oh i get all the files ending in ".txt". Does the other regexp work?

**Comment by magnetophon** [comment]
```*.txt``` shows the files in helm and opens just the first one on enter.

When I do that in bare emacs, it opens all txt files in the dir.

**Comment by AlejandroCatalina** [comment]
In helm you need to select all the candidates with `M-a`. An then enter.

**Comment by magnetophon** [comment]
Sure, but then I can't do it from my config.
I'm trying:
```
  (spacemacs|define-custom-layout "faustlib"
    :binding "l"
    :body
    (find-file "/run/current-system/sw/lib/faust/*.lib" t)
    )

  )
```

**Comment by magnetophon** [comment]
I could just name the files individually, but I'd prefer wildcards, as there will be new files in there when I update the faust package.

**Comment by AlejandroCatalina** [comment]
I was thinking on doing a fast snippet. I guess you'll need to use some regex search or so to retrieve all the file names. Also take a look at `helm-find-files-1`.

**Comment by magnetophon** [comment]
NM, it just started working from my config. Maybe the auto-save was interferring, as I didn't close the workspace when I restarted emacs.

The interactive version still doesn't work.

**Comment by magnetophon** [comment]
@StreakyCobra Thanks for your fix.
It's edited according to the template now.

**Comment by magnetophon** [comment]
Tested on `8825a06`, and I still get no results when I enter `*.txt` in `helm-find-files`

**Comment by TheBB** [comment]
I don't think `helm-find-files` supports globs.

**Comment by TheBB** [comment]
I tried in Emacs + helm and nothing. So if you want this feature I suggest you take it to helm.

**Comment by magnetophon** [comment]
OK, thanks.
