### ISSUE TITLE
Cursor should never move when scrolling.

### ISSUE THREAD

**Issue by amichail** [syl20bnr/spacemacs#4970]
Currently, it starts moving when it gets close to the top or bottom margin.

This makes relative line numbering mode less useful.

**Comment by JohnDDuncanIII** [comment]
I use this (with the scroll-restore package from the ELPA) to fix that problem
```
;; scrollers - scroll buffer not point
(global-set-key "\M-n" "\C-u1\C-v")
(global-set-key "\M-p" "\C-u1\M-v")

;; Restore the cursor when you scroll past it on the buffer
(require 'scroll-restore)
(scroll-restore-mode 1)
;; Allow scroll-restore to modify the cursor face
(setq scroll-restore-handle-cursor t)
;; Make the cursor invisible while POINT is off-screen
;;(setq scroll-restore-cursor-type nil)
;; Jump back to the original cursor position after scrolling
(setq scroll-restore-jump-back t)
;; Toggle scroll-restore-mode with the Scroll Lock key
(global-set-key (kbd "<Scroll_Lock>") 'scroll-restore-mode)
```

**Comment by amichail** [comment]
Shouldn't this be the default behaviour though?

**Comment by JohnDDuncanIII** [comment]
In my opinion, yes! That scroll-restore package is buggy too. I don't think there is a clean way to let the cursor stay in its position outside of the buffer without hacks such as scroll-restore.

**Comment by sooheon** [comment]
@JohnDDuncanIII Thanks for the scroll-restore package, it improves the behavior at top of file. Still, scrolling down to the bottom is broken, because once the last line of file is in view, additional calls to `evil-scroll-down` or `evil-scroll-page-down` will do nothing, unlike in vim, where cursor will always travel to the end of the document. Do you have this behavior as well? Do you just live with it?

**Comment by darfink** [comment]
@sooheon I believe you are referring to this big: https://bitbucket.org/lyro/evil/issues/618/evil-scroll-down-cannot-make-it-to-the-end

**Comment by d12frosted** [comment]
@sooheon that upstream bug was resolved. Do you still experience bugs from proposed solution? 

This issue is old, so I am closing it. Let me know if you wish to reopen it!
