### ISSUE TITLE
ERC Unable to communicate with services

### ISSUE THREAD

**Issue by ankhers** [syl20bnr/spacemacs#4971]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(erc)
```

I have disabled all layers but erc for testing this. I also tested for this issue on the develop branch.

When using ERC, I seem to be unable to communicate with any of the services within freenode and mozilla (nickserv, chanserv, etc).

To reproduce, enable the erc layer, `SPC a i E` use either `irc.freenode.net` or `irc.mozilla.org`, port `6697`, whatever username, whatever password (or none).

Once you connect, `/query nickserv`, a new buffer should open. simply typing `help` should have `nickserv` respond to you with its options. I receive no messages.

Oddly enough, if I `(erc-services-mode -1)` in my `dotspacemacs/userconfig`, I am still unable to speak with the services.

However, if I edit the erc layer and remove `(erc-services-mode 1)`, restart emacs, I actually get a response from `nickserv`.

I'm unsure as to what is happening, but if I start up emacs without a config (`emacs -Q`), enable `erc-services-mode` and try to talk to `nickserv`, it works perfectly fine.

**Comment by wordempire** [comment]
I can confirm this behaviour on the current version of spacemacs. Any on what is causing this?

**Comment by ankhers** [comment]
I also just noticed that I am unable to see github bot messages on Freenode if I have `(erc-services-mode 1)` in the erc config.

**Comment by mwillsey** [comment]
I also just reproduced on develop (bb013ef99). Adding the following to `dotspacemacs/user-config` fixed it for me:

```elisp
(defun erc-services-mode (num))
```

This just prevents the layer from loading the mode without having to copy it into a private layer and edit it.

**Comment by ankhers** [comment]
I am still seeing this issue on current develop (e0aee1554454aff8183076b442b2903e5fa072c1).

**Comment by ankhers** [comment]
I'm closing this because it will be closed anyways and I no longer use spacemacs. At this point, if someone else cares about this, it may be better to open a new ticket and reference this one.
