### ISSUE TITLE
literate-haskell-mode doesn't have haskell-mode bindings

### ISSUE THREAD

**Issue by jb55** [syl20bnr/spacemacs#4974]
Tried to update the layer by adding `literate-haskell-mode-hook` in a few places but couldn't get it working :[

**Comment by StreakyCobra** [comment]
@d12frosted I think this can be nice to have. Do you have any information why this is currently not done?

**Comment by d12frosted** [comment]
Dunno honestly. I don't use literate haskell mode, so I never bothered myself with making configs for it. But we already have pending PR for it: https://github.com/syl20bnr/spacemacs/pull/3459.

**Comment by d12frosted** [comment]
So if that PR is abandoned we should create a new one :D

**Comment by jb55** [comment]
Didn't see that PR, will try to get it working in a bit

**Comment by StreakyCobra** [comment]
Oh, right there is already an issue about this. Closing this one as duplicate of #3458.
