### ISSUE TITLE
New layer format

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#4980]
I'd like clarification on the new layer format.  Relevant links:

Layers documentation: https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org
Relevant commit: https://github.com/syl20bnr/spacemacs/commit/09af60594c315b956b284bd58e5f2af1beddd011

## Old format

- `packages.el`: Set layer packages and configure packages (`init-<package>`).
- `funcs.el`: Function definitions, including named functions that are used in `init-<package>`.
- `keybindings.el`: Any keybindings that don't go into `init-<package>` (not package specific).
- `config.el`: All remaining configuration that don't go into `init-<package>` (not package specific).

## New format

- `packages.el`: Set layer packages.
- `packages-config.el`:  Configure packages (`init-<package>`).
- `packages-funcs.el`:  Function definitions, only named functions that are used in `init-<package>` (package related).
- `funcs.el`: Remaining function definitions (not package specific).
- `keybindings.el`: Any keybindings that don't go into `init-<package>` (not package specific).
- `config.el`: All remaining configuration that don't go into `init-<package>` (not package specific).

## Questions

1. Is my understanding correct?
2. Migrating existing layers involves: moving init functions `packages.el` -> `packages-config.el`, moving some definitions `funcs.el` -> `packages-funcs.el`?
3. Is having a separate `keybindings.el` necessary?  I believe these will be things like calls to `spacemacs/set-leader-keys`, `evil-define-key`, etc.  Can these not simply go into `config.el`?
4. Regarding where to put functions, say a function `my-layer-foo-function` gets used in `init-foo` as `(setq foo-function 'my-layer-foo-function)`, then it goes into `packages-funcs.el`.  An interactive command `my-layer-frob-paragraph` goes into `funcs.el`.  Does this sound right?
5. Is the new layer format "final"?  Should existing layers be migrated?
6. What's the motivation behind the change?

**Comment by StreakyCobra** [comment]
@syl20bnr is the best person to answer all this :-) But I can give some indications about what I know:

> What's the motivation behind the change?

It has to do with [lazy layers installation](https://github.com/syl20bnr/spacemacs/blob/f94263919b53faf0bd83910100185a29179e3281/core/templates/.spacemacs.template#L14-L16). It *seems* it could also help solving #3430.

> Should existing layers be migrated?

Quoting a discussion with @syl20bnr: `I’ll do the refactor for each layer after all PRs for each have been merged`.

**Comment by robbyoconnor** [comment]
I been doing my PRs against it. I updated the docs when I saw he did it. The wizard is updated [here](https://github.com/syl20bnr/spacemacs/pull/4906) -- he hasn't merged it yet.

**Comment by darkfeline** [comment]
Should the `layer/init-package` functions go into `packages.el` or packages-config.el`?  The wizard PR implies the former, the documentation implies the latter.

**Comment by robbyoconnor** [comment]
Yes. It should go in package.el

`package-config` just defines the packages

--Rob

**Comment by robbyoconnor** [comment]
For examples see the plantuml layer

--Rob

**Comment by darkfeline** [comment]
In that case, the following documentation fix is needed? https://github.com/syl20bnr/spacemacs/pull/4986

**Comment by syl20bnr** [comment]
Sorry for being late on this.

> Should the layer/init-package functions go into packages.el or packages-config.el? 

`init` functions go in `packages-config.el`.
Additional functions go to `packages-funcs.el`.
`packages.el` defines only the list of packages `<layer>-packages`.

@darkfeline So your **New format** section in OP looks quite accurate to me.

**Comment by darkfeline** [comment]
Given that, the following need fixing:

- plantuml layer
- create-layer wizard

**Comment by robbyoconnor** [comment]
@darkfeline what's wrong with the plantuml layer I followed the template when I saw it? The create-layer wizard has an open PR (See #4906)

**Comment by darkfeline** [comment]
As @syl20bnr says, you swapped what was supposed to go in `packages.el` and `packages-config.el`.  Thus both `plantuml` and the wizard PR https://github.com/syl20bnr/spacemacs/pull/4906 is wrong.

**Comment by syl20bnr** [comment]
My bad, I overlooked it when merging, thank you @darkfeline.

**Comment by robbyoconnor** [comment]
Join Robert O'Connor and over 300 million other professionals already on LinkedIn

Sign up to become Robert's newest connection.

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67ofr-qx&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=wfV0QZG3&invitationId=6130896981863776257








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67ofr-qx&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHMIbMWH39fWgAAAVRVScAcDnhY2MiEl2hXQZao81myE-tu1e-PHfyXt32_qJyzXyirCNsVjVOdcMXSC0QF-vnCMnShbgUMPdxN9BS9kyYxeZszqFVSYGxOC4RKM1u1UG4-Is-P4yzXUMJh4DdBthfu0Ku573rcDT5gR3rEdn2VKNWhvPIE-nh0en2D9aRQ4yb_&eid=0-ini67ofr-qx


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67ofr-qx&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by cmr** [comment]
@darkfeline do you have any further questions here?

**Comment by darkfeline** [comment]
No, this is out of date anyway.
