### ISSUE TITLE
Eyebrowse keybinds should use helm

### ISSUE THREAD

**Issue by enolan** [syl20bnr/spacemacs#4982]
One of the pillars is discoverability, but SPC l opens up a microstate that doesn't tell you what any of the relevant keybinds are. To figure it out you have to look up the documentation or know that you can hit ? and know the submenu you want is workspaces, even then the workspaces microstate doesn't have a help menu.

**Comment by robbyoconnor** [comment]
No, helm is slow as shit.

**Comment by robbyoconnor** [comment]
You can read the docs, which explain it quite well...but I am REALLY against using helm for this.

**Comment by robbyoconnor** [comment]
Also I should point out that the microstate does satisfy the discoverability tenent of spacemacs

**Comment by Andre0991** [comment]
@robbyoconnor Wait, what are you referring to? `SPC ?`? I think @enolan is talking about pressing `?` in the micro state, which pops up a list of keybindings.

**Comment by enolan** [comment]
Apparently I meant which-key and not helm. The menu that pops up when you press SPC and shows you the list of which keys you can press and what they do.

Currently, pressing `SPC` (and then waiting a little bit) opens up the which-key menu. One of the options is `l - layouts-micro-state`. Pressing `l` opens up the microstate.

I'm proposing this: pressing `SPC` opens the which-key menu. One of the options is `l - +layouts/workspaces`. Pressing it brings a second which-key menu, with options `1 - layout 1`, `2 - layout 2` and so on. Another is `w - +workspaces`. That gets you a third which-key menu, with `1 - workspace 1`, `2 - workspace 2` and so on, plus `TAB - switch to last workspace`, `c - close current workspace`, `n - next workspace` etc.

This is how practically all of the submenus work already.

**Comment by joehillen** [comment]
I think `[?] help` was lost in the move from micro states to transient states. I agree `?` should be shown to people know how to see the other bindings for the transient state.

**Comment by robbyoconnor** [comment]
@enolan transient states are kinda...a bit borked right now -- There is a pending PR fix and will appear in `develop` before it even sees the light of day in `master`

**Comment by robbyoconnor** [comment]
I do agree it's a bit broken right now -- sorry :( But using helm is not the answer...and it's also a bit heavy too...

**Comment by d12frosted** [comment]
It was already fixed 😸 If not, please let us know.
