### ISSUE TITLE
ess auto-complete

### ISSUE THREAD

**Issue by lengyueyang** [syl20bnr/spacemacs#4994]
I'm new to used spacemacs, and I know ess used company to company, but I want to use auto-complete to complete but company, 
I tryed to add the followed to the .spacemacs file, But the complete speed is very slow, I don't know why.

   (require 'auto-complete)
   (require ‘auto-complete-acr)
   (require 'auto-complete-config)
   (ac-config-default)
   (setq ess-use-auto-complete t)
   (ess-toggle-underscore nil)
   (define-key ac-completing-map (kbd "M-h") 'ac-quick-help)
   (define-key ac-completing-map "\r" nil)
   (define-key ac-completing-map [tab] 'ac-complete)
   (define-key ac-completing-map [return] nil)
   (set-face-attribute 'ac-candidate-face nil   :background "#00222c" :foreground "light gray")
   (set-face-attribute 'ac-selection-face nil   :background "SteelBlue4" :foreground "white")
   (set-face-attribute 'popup-tip-face    nil   :background "#003A4E" :foreground "light gray")
But the complete speed is slow, I don't know why.

**Comment by lengyueyang** [comment]
I solve the problem, add
    (setq ac-sources
      (append '(ac-source-features
        ac-source-functions
        ac-source-yasnippet
        ac-source-variables
        ac-source-symbols)
          ac-sources))

    (setq ac-delay 0.1)       
    (setq ac-auto-show-menu 0.2)
    (setq ac-quick-help-delay 0.2)
    (setq ac-quick-help-height 10)
    (setq ac-candidate-limit 100)

**Comment by StreakyCobra** [comment]
@lengyueyang If your problem is fixed you may consider closing the issue :-)
