### ISSUE TITLE
[IFTF]Add key bindings for evil-ud-scroll-count-reset

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#4996]
When(if) [this patch](https://bitbucket.org/lyro/evil/commits/43aac5cf8f3604d56e27ac6b14ec7e22661eabdd) trickles down to Spacemacs  there will be a new function:

`evil-ud-scroll-count-reset ()`
>  "Sets `evil-ud-scroll-count' to 0.
`evil-scroll-up' and `evil-scroll-down' will scroll
for a half of the screen(default)."

I think it should have a key binding.

*IFTF - Issue For The Future* - as a reminder.

**Comment by aaronjensen** [comment]
This function is there, at least for me, as of this morning.

**Comment by JAremko** [comment]
@aaronjensen  WOW! The Technology ` (•_•) / ( •_•)>⌐□-□ / (⌐□_□)`

**Comment by TheBB** [comment]
If I'm reading the code right, calling the scroll function with zero should reset it, no?

**Comment by JAremko** [comment]
@TheBB  Ya. Like in Vim.

**Comment by JAremko** [comment]
It's all kinda messed up if you ask me. So I prefer extra function. For clarity :smile:

**Comment by JAremko** [comment]
And sure you can't do something like `0` `C-d` because 0 is taken.

**Comment by TheBB** [comment]
Passing it explicitly with `SPC u 0 C-d` seems to work fine.

**Comment by JAremko** [comment]
@TheBB  Sure It should work and the reset function might be redundant, but I think `SPC u 0 C-d` and `SPC u 0 C-u` is a little bit counter intuitive and the function definition because a mess + you can't call it this way normally :confused:

It's your call.

**Comment by JAremko** [comment]
Also scrolling [seems to be broken](https://bitbucket.org/lyro/evil/issues/618/evil-scroll-down-cannot-make-it-to-the-end)  and [this](https://bitbucket.org/lyro/evil/issues/615/switching-visual-mode-to-insert-mode-with). Looks like when I opened [the original issue](https://bitbucket.org/lyro/evil/issues/612/evil-scroll-should-adhere-to-the-vim-docs) I involuntarily attracted  too much attention to those functions 


Anyway, looks like it's not my fault. I hope :smile:

**Comment by TheBB** [comment]
It just seems such a specific thing to want a binding for. I'm not even sure where it would go.

**Comment by JAremko** [comment]
The scroll value is buffer local so It's not that bad if it goes nowhere :smile:

**Comment by JAremko** [comment]
I might  bind it to `1` `C-d` in my `.spacemacs` it's not too insane for the personal settings.

**Comment by JAremko** [comment]
After using it for some time I came to conclusion that it's probably not the most useful feature. and it's really hard to bind it to a proper key sequence.
