### ISSUE TITLE
ess auto-complete

### ISSUE THREAD

**Issue by lengyueyang** [syl20bnr/spacemacs#4997]
How to use auto-complete for ess as
http://www.emacswiki.org/emacs/ESSAuto-complete
please.

**Comment by TheBB** [comment]
What's the relation between this and https://github.com/syl20bnr/spacemacs/issues/4994?

**Comment by hujianxin** [comment]
Using `SPC m s i` can solve it?

**Comment by lengyueyang** [comment]
thanks
