### ISSUE TITLE
Request for help with ivy documentation

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#4999]
If no one else is willing to help I will get to it eventually, but if there is someone who would like to work on the documentation, I can assist with any questions. 

Issue #4540 has some basic detail. 
PR #4969 is the most recent set of changes

**Comment by AlejandroCatalina** [comment]
The doc should be placed in `spacemacs-ivy` right?

**Comment by justbur** [comment]
@AlejandroCatalina I was thinking there should be a how to use and brief description of helm and ivy in the main documentation instead of the layer, but I'm not sure  if @syl20bnr would want to see something else.

**Comment by robbyoconnor** [comment]
I think we should add a separate file and link to it from the FAQ somewhere and make it discoverable via `SPC h SPC`

**Comment by robbyoconnor** [comment]
I think the docs should go over what makes ivy better than helm or vice versa -- there are drawbacks to both as far as I can tell.

**Comment by AlejandroCatalina** [comment]
Okay that sounds right, as it is *core* functionality it should be placed in the main DOCUMENTATION. A how-to-use seems nice, we could gather together some sort of feature list here and checkbox them as we move on.

**Comment by sooheon** [comment]
Is this still the appropriate place for suggestions as well, or just for documentation of existing functionality? If the former, I'm seeing `progn: Wrong type argument: commandp, spacemacs/helm-project-smart-do-search-region-or-symbol` for commands involving search with ivy and some prepopulated search term. What I've found so far: `spc sgP`, `*b`, `*/`, `*f` (searching from symbol highlight transient state).

**Comment by justbur** [comment]
@sooheon #4969 is where I'm putting the changes, so that's probably the most appropriate place. 

Anyway, I found a missing `(interactive)` in `counsel-git-grep-region-or-symbol` and fixed that, but I don't know why you are getting a helm function here. Are you on my ivy branch and are you using just `spacemacs-ivy`?

**Comment by sooheon** [comment]
@justbur Ah I apologize, I was testing against the latest develop, I can see there are many change not yet merged in there. Can confirm all those work in your ivy branch.

**Comment by robbyoconnor** [comment]
Why is this closed @justbur ?

**Comment by justbur** [comment]
Spring cleaning :smile:

**Comment by robbyoconnor** [comment]
It's still not documented !

**Comment by StreakyCobra** [comment]
@robbyoconnor So, help him with documentation then :-)

**Comment by justbur** [comment]
This issue was a polite way of notifying people that I don't have time to do this right now, so it's not really an "issue", more of an announcement.

**Comment by robbyoconnor** [comment]
I think it should have been left open as an issue that needs addressing -- I don't have the time to do it myself either

**Comment by syl20bnr** [comment]
It is better to close it because we have to rethink how to present Helm and Swiper (ivy) in the documentation. I guess I should take care of this, actually before getting to the documentation I have yet to decide on how to present completion front-ends to the user.

**Comment by robbyoconnor** [comment]
For me at least I found helm to be unusably slow -- I don't know if it's our fault or helm's fault..
