### ISSUE TITLE
Errors running in terminal emacs

### ISSUE THREAD

**Issue by Trepanated** [syl20bnr/spacemacs#50]
I'm running emacs 24.4 in Terminal.app on OS X 10.9 (Mavericks).  I've run into a series of issues that seem to be related to calling functions not available in terminal mode, starting with this appearing in the Warnings buffer:

Symbol's function definition is void: tool-bar-mode

That's from line 52 of spacemacs/config.el.  I changed it to the following which seems to resolve the issue:

(if (functionp 'tool-bar-mode) (tool-bar-mode 0))

Same error on line 56 with scroll-bar-mode, similar fix applied.

That gets me as far as fetching and installing packages, but then this appears:

Symbol's function definition is void: define-fringe-bitmap

That one seemed a bit more involved so I did not attempt a fix.

**Comment by jgm** [comment]
I get this error starting emacs in a terminal.
I installed emacs in the way recommended on the site:
```
$ brew tap railwaycat/homebrew-emacsmacport
$ brew install emacs-mac --with-spacemacs-icon  # OR, brew cask install emacs-mac
$ brew linkapps
```
I think I'm using the right emacs:
```
% which emacs
/usr/local/bin/emacs
% ls -l /usr/local/bin/emacs
lrwxr-xr-x  1 jmadmin  staff  30 Oct 20 12:25 /usr/local/bin/emacs -> ../Cellar/emacs/24.5/bin/emacs
```
It doesn't seem to matter whether I start with `-nw` or not.

**Comment by daghoidahl** [comment]
I got this error in `*messages*` even when starting emacs in a regular window. Installed from `railwaycat/homebrew-emacsmacport`.
