### ISSUE TITLE
Too many issues

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#5000]
:scream:

**Comment by StreakyCobra** [comment]
Please update your issue to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report).

:heart: :joy:

**Comment by syl20bnr** [comment]
:joy:

As long as we have more commits than issues it is OK  :suspect:

**Comment by nashamri** [comment]
LoL :joy:

**Comment by StreakyCobra** [comment]
So, guys, let's back to work!

Beginners -> [here](https://github.com/syl20bnr/spacemacs/issues?q=is%3Aopen+is%3Aissue+label%3A%22Beginner+friendly%22)
Regular contributors -> [here](https://github.com/syl20bnr/spacemacs/issues?q=is%3Aissue+is%3Aopen+label%3A%22Ready+for+work%22)
Everybody -> [here](https://github.com/syl20bnr/spacemacs/issues)

**Comment by justbur** [comment]
#### Description
There are more issues than I can hold in my head at once. 

#### Reproduction guide
- Start Emacs
- Open https://github.com/syl20bnr/spacemacs
- Click on Issues tab

*Observed behaviour:*
Observes 534 open issues on 22 pages.

*Expected behaviour:*
Expected to spend lunch eating instead of reading issues.

#### System Info
- OS: windows-nt
- Emacs: 25.0.90.1
- Spacemacs: 0.105.9
- Spacemacs branch: ivy (rev. ba6deea)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(spacemacs-helm spacemacs-ivy
                (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip nil auto-completion-private-snippets-directory "~/Dropbox/configs/spacemacs/snippets/")
                better-defaults
                (git :variables git-gutter-use-fringe t)
                shell syntax-checking spell-checking
                (version-control :variables version-control-diff-tool 'git-gutter+)
                emacs-lisp ess
                (latex :variables latex-enable-folding t)
                csv org python my-evil-cleverparens latex-extra jb-lispy spelling)
```

#### Backtrace
```
> reduce number of issues
VM279:2 Uncaught SyntaxError: Unexpected identifier(…)InjectedScript._evaluateOn @ VM157:878InjectedScript._evaluateAndWrap @ VM157:811InjectedScript.evaluate @ VM157:667
```

**Comment by JAremko** [comment]
Happy five thousand everyone ::tada:

**Comment by d12frosted** [comment]
Woo. Best issue description ever, @justbur :D
