### ISSUE TITLE
Php-extras error: wrong-type arguement stringp nil

### ISSUE THREAD

**Issue by zeka0** [syl20bnr/spacemacs#5007]
<img width="1279" alt="2016-02-09 14 30 04" src="https://cloud.githubusercontent.com/assets/13997167/12909403/a262df06-cf3b-11e5-968d-fb719fdcded1.png">
I got an error when start up the spacemacs. It seems to be unable to contact the gnu repository.
I have tried to use VPN to connect to USA LA but it reports the same problem.
My platform is win10-64bit-home and I have added git(2.6.4.windows.1) to my environment path.
Maybe putting that package in local versions of those packages will help?

**Comment by StreakyCobra** [comment]
http://www.downforeveryoneorjustme.com/elpa.gnu.org

> It's not just you! http://elpa.gnu.org looks down from here.

**Comment by jgertm** [comment]
It seems to be back up again, thus it works fine again.
It does seem like a problem to me that while any of the repositories are unreachable it's impossible to start spacemacs. Is there a way to disable checking them on every start?

**Comment by StreakyCobra** [comment]
@jgertm Indeed it's annoying. Have you tried changing `dotspacemacs-check-for-update` to `nil`?

**Comment by zeka0** [comment]
Now here is another serious issue. With the current problem unsolved, when I ran spacemacs without internet connection, the vim-mode seems to be disabled, i.e, the vim commands no longer works. That's quite surprising...

**Comment by zeka0** [comment]
Well, it seems that  http://elpa.gnu.org has been up. But I still have that problem: Php-extras error: wrong-type arguement stringp nil. But there are no message for unable to contact gnu.org this time. Any ideas?

**Comment by zeka0** [comment]
Okay, it seems that disable the php layer in spacemacs would eliminate this problem. As I'm not a php-user, it works for me. For those who use php, there might be a headache now...

**Comment by drew887** [comment]
Was there ever a solution found for this? elpa is up and accessable for me, but I'm still having the wrong-type-argument problem

**Comment by jfchevrette** [comment]
I'm having the same issue and elpa is up

**Comment by syl20bnr** [comment]
php-extras is fetched directly from github via a recipe. The gnu elpa repo issue should be unrelated. One can delete the quelpa cache in the .cache directory as well as the archives folder in elpa directory.

**Comment by drew887** [comment]
I tried deleting it a couple of times, and eventually looked at the files, they were full of weird symbols once downloaded (not a line endings thing I checked that) so I eventually"solved" it by commenting it out from the package list and just installing it from marmalade

**Comment by syl20bnr** [comment]
That's weird, if it happens again, can you paste the corrupted content of the file ?

**Comment by drew887** [comment]
Github seems to not be displaying the wierd character but heres an image from notepad++
![spacemacsphp](https://cloud.githubusercontent.com/assets/2347730/15964086/bec0d80c-2ee4-11e6-954b-876d2f4e9922.png)

**Comment by ventikus** [comment]
I have the same problem. 

> Found 6 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: php-extras@php... [3/6]
An error occurred while installing php-extras (error: (wrong-type-argument stringp nil))
--> installing package: phpunit@php... [6/6]

Im new to emacs and spacemacs so i don't have even idea what i'm supposed to post :D

**Comment by ubuntutest** [comment]
I also tried using spacemacs-develop, but I'm not able to solve the problem.
An error occurred while installing php-extras (error: (wrong-type-argument stringp nil))

i'm on windows 10,
any idea how to solve it?

**Comment by dl1ely** [comment]
I have to bump here...using Windows 7, Spacemacs 0.200.7@25.1.1 i get that exact error on every startup. I need the PHP layer...

Thank you!

**Comment by andrew-werdna** [comment]
I'm having the exact same issue

**Comment by arnested** [comment]
Hi, I'm the author of php-extras.

Just for the record. The "weird character" is a page break (ascii 12, `^L`) and is not uncommon in elisp code. See https://stackoverflow.com/questions/1576887/what-does-l-in-emacs-lisp-source-code-mean

So I guess the problem must be something else.
