### ISSUE TITLE
Font way too small

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#501]
After the upgrade to 0.51.0 from 0.49.x everything in my emacs is way smaller than before. I do have Source Code Pro installed and everything worked perfectly before. 

I do have a hdpi screen and use font scaling of 1.5 in Ubuntu to get everything to the correct size.
See the screenshot, the terminal is normal font size, emacs below is way to small to read:
![screenshot from 2015-01-28 21 58 11](https://cloud.githubusercontent.com/assets/380927/5946849/0e87aecc-a739-11e4-893e-a6231c4780dc.png)

**Comment by syl20bnr** [comment]
Check the logs in `*Messages*` you should have a deprecation warning.
Font is now specified with the variable `dotspacemacs-default-font` more info here: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#font

**Comment by cpaulik** [comment]
Oh, thank you, I did miss this change. 

For me setting dotspacemacs-default-font in .spacemacs only works outside of the dotspacemacs/config function. Is this the intended behaviour?

**Comment by syl20bnr** [comment]
Yes, all `dotspacemacs-` variables should be in a `setq` outside of `init` and `config`.
See the reference in the template here: https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template

**Comment by cpaulik** [comment]
Thanks, that solves this issue for me.

**Comment by t3chnoboy** [comment]
I have the same issue. However, setting ```dotspacemacs-default-font``` doesn't seem to work.
My config: [.spacemacs](https://github.com/t3chnoboy/dotfiles/blob/OSX/.spacemacs#L47-L51)
OS X 10.10, Emacs 24.4

**Comment by syl20bnr** [comment]
@t3chnoboy if you set the size bigger than 15 does it work ? In the past with `spacemacs/set-font` the passed size was not the exact size displayed by emacs (usually the true size was bigger than the requested one), whereas now if you put 15 you'll get 15 as intended.

**Comment by t3chnoboy** [comment]
No, it's still unchanged. Also, it's not just size – the font is not being changed either.

**Comment by syl20bnr** [comment]
ok, can you verify that you pass the correct font name ? Spacemacs will skip it when he cannot find it.

**Comment by syl20bnr** [comment]
@t3chnoboy Can you test the develop branch ? I just push a new way to detect the font.

**Comment by t3chnoboy** [comment]
sure

**Comment by t3chnoboy** [comment]
https://gist.github.com/t3chnoboy/26d428c50e5ac36862a0

**Comment by t3chnoboy** [comment]
Still doesn't work

**Comment by syl20bnr** [comment]
@t3chnoboy I pushed a new commit, should work :-) Thank you!

**Comment by t3chnoboy** [comment]
Well, it's not working :(

**Comment by t3chnoboy** [comment]
https://gist.github.com/t3chnoboy/0a24316e2a1d49ce9df2

**Comment by syl20bnr** [comment]
Change the font to see if it works with another font.
BTW, you don't need a powerline patched font with the emacs powerline, it does not use font characters.

**Comment by syl20bnr** [comment]
Also be sure that you don't have any other settings that rechange the font afterward.

**Comment by syl20bnr** [comment]
This line is suspicious: https://github.com/t3chnoboy/dotfiles/blob/OSX/.spacemacs#L206

**Comment by t3chnoboy** [comment]
Yup! Removed that line and now it works! :dancers:
Thank you!

**Comment by syl20bnr** [comment]
Great ! :-)

**Comment by person808** [comment]
I'm also having this problem on 0.52.1. This is after a clean install because I wanted to try spacemacs. Nothing was touched.
![screenshot from 2015-01-30 19 25 36](https://cloud.githubusercontent.com/assets/6396431/5986943/539ce152-a8b6-11e4-97c2-9c5757c40f11.png)

**Comment by syl20bnr** [comment]
@person808 in spacemacs install the dotfile with `SPC : dostpacemacs/install` then open the file with `SPC f e d` and change the size of the font (look for `:size`).
More info here: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#font

**Comment by syl20bnr** [comment]
@person808 what is your linux distribution ?

**Comment by person808** [comment]
@syl20bnr I doubled the font size to 26 and everything looks fine. I'm on Arch Linux.

**Comment by syl20bnr** [comment]
@person808 great !

**Comment by aaron-lebo** [comment]
I ran into asimilar issue on a fresh arch/spacemacs install.

With a size of "13", the font would not match the fonts on the rest of my system, it was too small. However, I noticed in the documentation this line:

" The font size—either a non-negative integer that specifies the pixel size, or a floating-point number that specifies the point size. "

Those of you having problems with small fonts, I'd suggest making sure you use a decimal value, "13.0", which will specify a size in points like the rest of the system.

Would a change like this being the default make things more consistent?

**Comment by mlongval** [comment]
I uncommented "org" in dotspacemacs-configuration-layers

Download and compilation seem to have gone well 

But I get:

SPC m is undefined 

When I try to start org-mode

**Comment by mlongval** [comment]
Ok fixed that last problem by starting a new file with .org

**Comment by TheBB** [comment]
This issue is closed and about something else entirely. You can start a new one if you have problems.

**Comment by mlongval** [comment]
Thanks,

Actually I wanted to post to Gitter and it ended up on that page.

Thanks again

Michael Longval, MD
mlongval@gmail.com

**Comment by isthisthat** [comment]
Hello, changing `dotspacemacs-default-font` doesn't do it for me on CentOS 6, spacemacs 0.104.3, emacs 24.5.1. Font stays the same size. Anything else I can try?

**Comment by isthisthat** [comment]
In fact, none of the font settings seem to have an effect...

**Comment by d12frosted** [comment]
@isthisthat Are you running GUI or in terminal?

**Comment by isthisthat** [comment]
Running GUI

**Comment by isthisthat** [comment]
Hello, could this ticket be re-opened?

**Comment by TheBB** [comment]
Are you sure the font name exists? If it does not, none of the other settings will apply.

**Comment by nixmaniack** [comment]
FWIW, even if font exists, the current implementation might not detect the font in which case this would be similar to #3643

**Comment by isthisthat** [comment]
Thanks to all for your help. The issue was the missing font indeed. Problem is that I don't have sudo privileges on my machine. Luckily there is a `~/.fonts` directory in my home to which I copied the Source Code Pro TTFs from https://github.com/adobe-fonts/source-code-pro and then ran `fc-cache -f -v` which registered the font on CentOS 6. I can now increase the font size :)

**Comment by isthisthat** [comment]
Spoke too soon. Font changed and now is too large. Font size in `~/.spacemacs` still has no effect. Also upgraded to the latest release. Still nothing.

**Comment by glimmercn** [comment]
I'm using ubuntu 15.04, emacs 24.5 and spacemacs develop branch. I have the same issue. No setting of font works. It says spacemacs can't fine "Source Code Pro". But I have SCP installed and have no issue when running "emacs -nw".

I think it's a x window issue. When running emacs, here is the warning 
Cannot convert string "-*-courier-medium-r-*-*-*-120-*-*-*-*-iso8859-*" to type FontStruct

Have to dig more to solve the problem.

**Comment by szilveszter99** [comment]
I've solved this issue by adding 
   (custom-set-faces '(default ((t (:height 160 :family "Consolas" :embolden t)))))
into the top of (defun dotspacemacs/user-config () ...
(using spacemac v0.200.2, and Arch GNU/Linux)

**Comment by a-y-khan** [comment]
> I ran into a similar issue on a fresh arch/spacemacs install.
> 
> With a size of "13", the font would not match the fonts on the rest of my system, it was too small. However, I noticed in the documentation this line:
> 
> "The font size—either a non-negative integer that specifies the pixel size, or a floating-point number that specifies the point size. "
> 
> Those of you having problems with small fonts, I'd suggest making sure you use a decimal value, "13.0", which will specify a size in points like the rest of the system.

Changing font size to 13.0 also worked for me on Ubuntu 18.04.
