### ISSUE TITLE
Clojure - Cider Mode Doesn't Enable

### ISSUE THREAD

**Issue by AshtonKem** [syl20bnr/spacemacs#5014]
# Steps to reproduce

You'll need a clean copy of spacemacs to reproduce this, with the clojure layer enabled, and the latest copy of cider installed from melpa.

1. Open clojure buffer.
2. M-x cider-jack-in
3. C-c C-k (evaluate buffer)
4. Open different Clojure buffer, from a file that you haven't opened yet.
5. C-c C-k (evaluate buffer)

# Expected results

Both buffers should evaluate correctly in cider.

# Actual Result

The first buffer evaluates, but the second one does not. It does not recognize the C-c C-k binding to evaluate file.

## Commentary

It appears that the new buffer does not get cider-mode enabled. After debugging a bit, it seems that installing the following packages via elpa solves the problem, although I bet there's a better solution.

* paredit
* multiple-cursors
* edn
* inflections

**Comment by codygman** [comment]
I'm also affected by this. Yesterday I thought id try out clojure with spacemacs but had no such luck.

**Comment by AshtonKem** [comment]
Adding those packages to 'dot-spacemacs-additional-packages is a decent temporary workaround. 

--
Ashton

**Comment by izahn** [comment]
It looks to me like this is a problem with MELPA. `clj-refactor` requires
those packages[1], but somehow MELPA doesn't pick it up[2].

[1]
https://github.com/clojure-emacs/clj-refactor.el/blob/ba7cc8cd199346497786c37c35e1d1c525fb8ab3/clj-refactor.el#L11
[2] http://melpa.org/#/clj-refactor

On Wed, Feb 10, 2016 at 11:09 AM, Ashton Kemerling <notifications@github.com
> wrote:

> Adding those packages to 'dot-spacemacs-additional-packages is a decent
> temporary workaround.
>
> --
> Ashton
>
> Sent from my iPhone
>

**Comment by izahn** [comment]
I opened a bug report against MELPA,
https://github.com/melpa/melpa/issues/3581

**Comment by malchmih** [comment]
Fixed here: https://github.com/clojure-emacs/clj-refactor.el/issues/291

**Comment by StreakyCobra** [comment]
@malchmih :+1: Thx for the information :-)
