### ISSUE TITLE
Ruby - Robe cannot find new methods

### ISSUE THREAD

**Issue by portOdin** [syl20bnr/spacemacs#5015]
I have `Robe` setup and it works with Ruby and Ruby on Rails methods which are already defined within libraries. But methods which I create cannot be located and do not show up in `company-robe`autocompletions. Is there a solution to this?

**Comment by portOdin** [comment]
Never mind, I had errors in my code which were preventing Robe from parsing the files.

**Comment by StreakyCobra** [comment]
Glad to hear :+1: You can probably close this issue is your problem is fixed.
