### ISSUE TITLE
Theme installed with quelpa can't be enabled the same way as one from MELPA

### ISSUE THREAD

**Issue by person808** [syl20bnr/spacemacs#5016]
#### Description
Can't install a theme using quelpa from `dotspacemacs-additional-packages` and enable it in `dotspacemacs-themes`

Installing and enabling the theme in `dotspacemacs/user-config` works, but causes issues with the theme.

#### Reproduction guide
- set `dotspacemacs-additional-packages` to
```elisp
'((gruvbox-dark-theme :location (recipe :fetcher github :repo "d125q/gruvbox-dark-emacs")))
```
- set `dotspacemacs-themes` to 
```elisp
'(gruvbox-dark
  monokai)
```
- restart
*Observed behaviour:*
- Spacemacs does not load
- If `gruvbox-dark` is commented from `dotspacemacs-themes` and spacemacs is restarted, the theme is installed. I can then uncomment the theme and it will be enabled.

*Expected behaviour:*
- https://github.com/d125q/gruvbox-dark-emacs is installed using quelpa and set as default theme

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. de7eb40)
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 colors emacs-lisp
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 git html javascript org
 (python :variables python-enable-yapf-format-on-save t)
 (ruby :variables ruby-version-manager 'rvm)
 ruby-on-rails semantic
 (shell :variables shell-default-shell 'multi-term)
 shell-scripts spacemacs-ivy syntax-checking theming
 (version-control :variables version-control-diff-tool 'git-gutter))
```

#### Backtrace
```
Debugger entered--Lisp error: (error "Package `gruvbox-dark-theme-' is unavailable")
  signal(error ("Package `gruvbox-dark-theme-' is unavailable"))
  error("Package `%s-%s' is unavailable" gruvbox-dark-theme "")
  package-compute-transaction(nil ((gruvbox-dark-theme)))
  package-install(gruvbox-dark-theme)
  (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg)))
  (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)
  (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)))
  (let ((warning-minimum-level :error)) (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append ...) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir))))
  spacemacs/load-or-install-package(gruvbox-dark-theme)
  (let ((pkg (spacemacs//get-theme-package theme))) (spacemacs/load-or-install-package pkg))
  (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (spacemacs/load-or-install-package pkg))) (if (or (eq (quote moe-light) theme) (eq (quote moe-dark) theme)) (progn (load-file (concat pkg-dir "moe-light-theme.el")) (load-file (concat pkg-dir "moe-dark-theme.el")))) (add-to-list (quote custom-theme-load-path) pkg-dir))) (t (let ((pkg (spacemacs//get-theme-package theme))) (spacemacs/load-or-install-package pkg))))
  (if (or (memq theme (custom-available-themes)) (eq (quote default) theme)) nil (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (spacemacs/load-or-install-package pkg))) (if (or (eq (quote moe-light) theme) (eq (quote moe-dark) theme)) (progn (load-file (concat pkg-dir "moe-light-theme.el")) (load-file (concat pkg-dir "moe-dark-theme.el")))) (add-to-list (quote custom-theme-load-path) pkg-dir))) (t (let ((pkg (spacemacs//get-theme-package theme))) (spacemacs/load-or-install-package pkg)))))
  spacemacs/load-theme(gruvbox-dark)
  (let ((default-theme (car dotspacemacs-themes))) (spacemacs/load-theme default-theme) (setq configuration-layer--protected-packages (append (delq nil (mapcar (quote spacemacs//get-theme-package) dotspacemacs-themes)) configuration-layer--protected-packages)) (setq-default spacemacs--cur-theme default-theme) (setq-default spacemacs--cycle-themes (cdr dotspacemacs-themes)))
  spacemacs/init()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %d or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "/home/kainalu/.emacs.d/init.el" nil t)  ; Reading at buffer position 1076
  load-with-code-conversion("/home/kainalu/.emacs.d/init.el" "/home/kainalu/.emacs.d/init.el" t t)
  load("/home/kainalu/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
```

**Comment by mclearc** [comment]
Put "gruvbox-theme" in additional packages and then put "gruvbox" in dotspacemacs themes, reload and all will be well.

**Comment by person808** [comment]
@mclearc that does work, but I think it would be preferable to have all themes treated the same regardless if it is on MELPA or not. Its a bit unexpected that recipes don't work in `dotspacemacs-themes` when they do in `dotspacemacs-additional-packages`. At the very least, I think the workaround for this should have a faq entry.

**Comment by mclearc** [comment]
So my understanding of `dotspacemacs-themes` was that it didn't download themes, but only set them for loading on start-up and for toggling. This is what is indicated in the  [documentation](http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline77). Loading the theme would then require either creating a layer or adding the theme in `additional-packages`. In both cases there is already documentation for specifying a source other than melpa. But maybe you're right that this could be made clearer in the docs on theming. Maybe you could create a pull request?

**Comment by person808** [comment]
@mclearc Spacemacs auto-appends `-theme` to the name in `dotspacemacs-themes` and installs the package from MELPA. If the theme's package name is different, `spacemacs-theme-name-to-package` is used to find the correct one. (see `spacemacs/load-theme`)

I noticed that startup broke whenever `gruvbox-dark-theme` was not already installed as an additional package and had to be commented out of `dotspacemacs-themes` to install. So it seems to me like the best solution is to use the configuration-layer system in `spacemacs/load-or-install-package` to support quelpa. @syl20bnr Is this possible?

**Comment by syl20bnr** [comment]
> Its a bit unexpected that recipes don't work in dotspacemacs-themes when they do in dotspacemacs-additional-packages.

Looks not unexpected to me. `dotspacemacs-themes` is a list of theme names, it is not a list of theme packages.

> Put "gruvbox-theme" in additional packages and then put "gruvbox" in dotspacemacs themes, reload and all will be well.

I'm surprised it works, I mean you have to add it to the additional package first, then restart to install, and only ofter all this you can use it right ? Or does it work right away when you both add the theme package to additional package and add the theme name to `dotspacemacs-themes` and restart ?

**Comment by person808** [comment]
> dotspacemacs-themes is a list of theme names, it is not a list of theme packages

Alright, I guess I got confused when MELPA themes were seemingly installed the same way as additional packages so I expected a recipe to work.

> I'm surprised it works, I mean you have to add it to the additional package first, then restart to install, then add the theme name to the dotspacemas-themes list and restart again right 

This is how it works unfortunately. One way to fix it would be to support recipes in dotspacemacs-themes, but if there is another way that would be awesome. :)

**Comment by person808** [comment]
using `:step bootstrap` mostly fixes this. Just have to restart twice when updating the theme
