### ISSUE TITLE
Dividing line in the status bar becomes curvy?

### ISSUE THREAD

**Issue by hanfeisun** [syl20bnr/spacemacs#5017]
I used `brew` to install Emacs according to the [INSTALL GUIDE for OSX](https://github.com/syl20bnr/spacemacs#os-x). 

However, I found the dividing line in the bottom status bar become curvy instead of straight somehow (see the screenshot).

<img width="693" alt="screen shot 2016-02-10 at 8 09 41 pm" src="https://cloud.githubusercontent.com/assets/922081/12946854/69beac46-d032-11e5-9d01-9c2ccc3f8804.png">

Does anyone have any idea about this?

**Comment by d12frosted** [comment]
It's supposed to be so :)

**Comment by hanfeisun** [comment]
Really.. I thought it was a bug as the dividing line in the screenshot on http://spacemacs.org is straight..

<img width="1147" alt="screen shot 2016-02-10 at 8 16 00 pm" src="https://cloud.githubusercontent.com/assets/922081/12946985/2c8c8bd0-d033-11e5-96a2-cdc9fb15e124.png">

**Comment by d12frosted** [comment]
Wow. Never seen such dividing line. @StreakyCobra how can one achieve it?

**Comment by StreakyCobra** [comment]
http://spacemacs.org/doc/DOCUMENTATION.html#outline-container-orgheadline72

**Comment by d12frosted** [comment]
Ah ok. Seems like documentation of `powerline-default-separator` (via `C-h v`) is not full :/

```
Valid Values: alternate, arrow, arrow-fade, bar, box, brace,
butt, chamfer, contour, curve, rounded, roundstub, wave, zigzag,
utf-8.
```

**Comment by hanfeisun** [comment]
Cool, it works when I set the value to `slant`!
