### ISSUE TITLE
rainbow identifier not work sometimes

### ISSUE THREAD

**Issue by zjhmale** [syl20bnr/spacemacs#5018]
when i enable `color layer` and get `rainbow identifier` to work, everything is fine at first.
but after some editing and debugging with spacemacs, `rainbow identifier` will be disabled and can not be enabled again, only restart emacs to get it back.
how can i fix it?

**Comment by StreakyCobra** [comment]
Could you update your issue to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) Thanks :-)
