### ISSUE TITLE
Helm buffers don't have powerline set up

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#502]
Noticed that Powerline isn't used on helm buffers.  Is this a feature or a bug?

**Comment by syl20bnr** [comment]
It would awful to have the powerline for helm buffer, the powerline is too much complicated.
See also neotree, it has it's own clean mode line.

**Comment by syl20bnr** [comment]
@ralesi Or a special powerline theme should be added for helm.

**Comment by syl20bnr** [comment]
@ralesi I re-open this issue because if we manage to get a good way to define powerlne segment it would be easy to provide ones for helm buffers and compose them into another mode line for them.

:+1:

**Comment by syl20bnr** [comment]
Linked to #524

**Comment by ralesi** [comment]
#524 addresses this
