### ISSUE TITLE
Feature request: add emojify to emoji layer

### ISSUE THREAD

**Issue by jb55** [syl20bnr/spacemacs#5023]
https://github.com/iqbalansari/emacs-emojify

maybe default off...

**Comment by Stebalien** [comment]
Could this be reopened? Personally, I'd like this feature (defaulted to on).

**Comment by iqbalansari** [comment]
Hi,

Is there something I can do, to help include emojify in Spacemacs?

**Comment by Miciah** [comment]
#8042 added the emojify package to the emoji layer; is anything else needed to close out this issue?
