### ISSUE TITLE
Reconsider buffer delete to be SPC b d

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#5031]
Just to let my opinion there, I wish spacemacs should've moved `SPC w c` to `SPC w d` and not `SPC b d` to `SPC b c`.
I don't think most people use dedication that often than deleting buffer/deleting window. For dedication it could have moved to `SPC w D`.

What others think? 

cc @StreakyCobra @robbyoconnor

**Comment by AlejandroCatalina** [comment]
I think it's more consistent with nmemonics, `d` standing for `delete`. I agree :+1:

**Comment by kRITZCREEK** [comment]
But you don't **d**elete the buffer, the content remains on disk, so you are **c**losing it. :-1:

**Comment by AlejandroCatalina** [comment]
I think you are referring to the file pointed by the buffer. The buffer doesn't exist in the computer, it's an emacs logic unit, that may or may not point to a file or other content. So yes, you actually *delete* the buffer, obviously the content remains in the disk, and the buffer never was there. In emacs the word *close* has been never related to any **killing** buffer function.

**Comment by StreakyCobra** [comment]
@nixmaniack I have the same opinion as you. `SPC b d` should be to delete buffer, `SPC w d` to delete window, `SPC w D` for window dedication.

@kRITZCREEK The **file** is closed, the **buffer** is deleted.

A really important argument is that `vim` and `evil-ex` corresponding command is `:bd`, so `SPC b d` should be the corresponding leader binding.

**Comment by syl20bnr** [comment]
I like the distinction between `delete` which is destructive and `close` which is not so as long as we have consistency I prefer `w c` and `b c` for closing and `f D` for delete. If we move `w d` to `w D` for dedication we have inconsistency between `f D` and `w D`.

**Comment by syl20bnr** [comment]
note: I'm not opposed to move `w d` for dedication to another sequence than `w d` or `w D` if we ever need it.

**Comment by robbyoconnor** [comment]
I personally got so used to `SPC b d` and it threw me off -- still does...it's muscle memory, which is harder to re-train

**Comment by StreakyCobra** [comment]
@syl20bnr Yes, but what about consistency with vim and `:bd` ? And from my point of view you **close** a file, but you **delete** its buffer.

Also for non-file buffers, like `*scratch*` or `*Backtrace*`. When you kill them, is the action a **close**, which means you can reopen it later, or a **delete** meaning they are gone?

I really think `SPC b d` is the way to go, either for consistency with vim, evil-ex and non-file buffers.

**Comment by robbyoconnor** [comment]
> @syl20bnr Yes, but what about consistency with vim and :bd ? And from my point of view you close a file, but you delete its buffer.
>Also for non-file buffers, like *scratch* or *Backtrace*. When you kill them, is the action a close, which means you can reopen it later, or a delete meaning they are gone?
>I really think SPC b d is the way to go, either for consistency with vim, evil-ex and non-file buffers.

:point_up: **_THIS THIS THIS_**

**Comment by syl20bnr** [comment]
OK I'm sold on `SPC b d` and `SPC w d`, but we have to find another key bindings for dedication because `SPC w D` will be taken for `ace-delete-window`. Also we should change `SPC l c `to `SPC l d`.

What kind of good binding can we find for dedication ? `s` for stick is already taken, `p` for pin too. `SPC w t` maybe ? We can say that `SPC w t` is window toggle ~dedication~ state :-D

**Comment by robbyoconnor** [comment]
Thank you -- I liked `SPC bd`

**Comment by robbyoconnor** [comment]
See #5043

**Comment by nixmaniack** [comment]
Thanks for reconsidering this! It makes much sense as others have already explained. :) :+1: Thanks @robbyoconnor for the PR!

**Comment by aaronjensen** [comment]
I believe this issue can be resolved now, :confetti_ball:

**Comment by robbyoconnor** [comment]
Not so fast, it hasn't been released but the "Fixed in develop" label should be applied.

**Comment by robbyoconnor** [comment]
It will automatically close when it's merged into master @aaronjensen

**Comment by aaronjensen** [comment]
Ah, ok my bad. Thanks.

**Comment by robbyoconnor** [comment]
I suppose that works

**Comment by TheBB** [comment]
I don't mind this from a vim consistency standpoint, but muscle memory? Really? It took me like two days at most to retrain to `SPC b c`.

**Comment by robbyoconnor** [comment]
Hey I just delivered the will of the people -- and after I made the PR -- i realized it was already becoming second nature :/

**Comment by StreakyCobra** [comment]
@TheBB It's important we do changes like this to train and keep our neuroplasticity.

**Comment by mosic** [comment]
Thanks for changing this back. I accepted the change as logical but found that `SPC b d` is noticeably more comfortable than `SPC b c`, especially since I use it dozens of times per day. This is pretty subjective though.

**Comment by robbyoconnor** [comment]
:+1:

**Comment by posva** [comment]
This is already working on current build, isn't it?

**Comment by nixmaniack** [comment]
@posva Yes.

**Comment by posva** [comment]
@TheBB I think this can be closed
