### ISSUE TITLE
Double import on completion in python mode

### ISSUE THREAD

**Issue by deterok** [syl20bnr/spacemacs#5033]
Situation:
![15](https://cloud.githubusercontent.com/assets/1702003/12974813/00890bea-d0c8-11e5-9b13-04d316d33907.png)

After tab pressed:
![15](https://cloud.githubusercontent.com/assets/1702003/12974830/2cb951ac-d0c8-11e5-830e-87c7c1cb07fd.png)

Once again:
![15](https://cloud.githubusercontent.com/assets/1702003/12974835/4166c8fa-d0c8-11e5-89c1-7cdbda571c2e.png)
(Now company popup is opened)

**Comment by bmag** [comment]
Thanks for the report. This is an Emacs bug, I was able to reproduce it with bare Emacs (version 24.5) by following these steps:
- start emacs: <kbd>emacs -Q</kbd>
- create an empty python buffer: <kbd>C-x b foo.py RET</kbd>
- turn on python mode: <kbd>M-x python-mode RET</kbd>
- start interpreter: <kbd>C-c C-z</kbd> (`python-shell-switch-to-shell`) and answer the prompts (I pressed <kbd>RET n</kbd>)
- switch back to python buffer: <kbd>C-x o</kbd> (`other-window`)
- type "from os import " (there is a space after "import")
- press <kbd>C-M-i</kbd> (`completion-at-point`)

_Observed behaviour_:  "import " is inserted in the buffer. The buffer now contains "from os import import ".
_Expected behaviour_: completion-at-point offers names from the `os` module as completion candidates.

@deterok please report this bug to the Emacs developer (via <kbd>M-x report-emacs-bug RET</kbd>).
Next time, please follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) when reporting bugs to Spacemacs.

**Comment by deterok** [comment]
Thanks for the help. I have sent a bug report.

**Comment by StreakyCobra** [comment]
Thanks @deterok. Can you please paste the link to the issue you opened so people can follow it? Thanks :-)

**Comment by nixmaniack** [comment]
Link to the report: https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-02/msg00732.html
