### ISSUE TITLE
Some (not all) characters in the modeline are small

### ISSUE THREAD

**Issue by meditans** [syl20bnr/spacemacs#504]
Hi all,
as you can see in the image below, some characters in the modeline are rendered smaller than others. 

![smallcharacter](https://cloud.githubusercontent.com/assets/4641445/5950260/1e8efb94-a758-11e4-9480-0eb09e888d3e.png)

Note that the number of the window on the left and the golden-ratio indicator are aptly sized. What could cause this problem (I installed the otf font from the adobe repo)?

Best regards
Carlo

**Comment by syl20bnr** [comment]
What is your OS and Linux distro if it applies ?

Also can you tell me what font is used for the following characters:
- ➊ [on this line](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L2103)
- ⊞ [on this line](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L1096)
- Ⓨ [on this line](https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L2146)

To retrieve the font name used for a character: put the point (cursor) on the character and enter `<SPC> : describe-char RET` then look for a font name in the popup.

On OS X mine is: `xft:-monotype-Arial Unicode MS-normal-normal-normal-*-13-*-*-*-*-0-iso10646-1 (#xFDE)` for Ⓨ

**Comment by meditans** [comment]
Sure, I'm running nixOS unstable, and these are the codes you requested:

➊  -> xft:-unknown-DejaVu
Sans-normal-normal-normal-*-24-*-*-*-*-0-iso10646-1 (#x100A)
⊞  -> xft:-unknown-DejaVu
Sans-normal-normal-normal-*-24-*-*-*-*-0-iso10646-1 (#xD23)
Ⓨ   -> xft:-Misc-Fixed-normal-normal-normal-*-18-*-*-*-c-90-iso10646-1
(#xEB8)

Obviously I can see the problem now: I'm not really using adobe source code
pro, although I added this snippet:

 dotspacemacs-default-font '("Source Code Pro"
                             :size 24
                             :weight normal
                             :width normal
                             :powerline-scale 1.1)

What to suggest to configure properly the font? I copied the fonts
from adobe repo in my `~/.fonts` and did `fc-cache -fv ~/.fonts`, then
spacemacs changed the font to the one I have now.

Bests
Carlo

2015-01-29 2:28 GMT+01:00 Sylvain Benner <notifications@github.com>:

**Comment by syl20bnr** [comment]
I don't have nixOS available. Can you try to tweak the font names [here](https://github.com/syl20bnr/spacemacs/blob/master/core/core-fonts-support.el#L30-68) to make them work with nixOS ?
You'll have to find a good fall back font that is installed by default on nixOS and that includes the circle letters like Ⓨ.
It's ok for ➊  and ⊞ since DejaVuSans is a good fallback font with good character sizes. You have to find one for the circled letters which are not included in DejaVuSans.

**Comment by syl20bnr** [comment]
If you find one, write it here and I'l be able to select them with nixOS.

**Comment by syl20bnr** [comment]
@meditans Can you tell me what the value of `system-type` for you ?

**Comment by meditans** [comment]
It's gnu/linux, I checked it before. I was tweaking around with fonts, but
no results for now.

2015-01-30 17:49 GMT+01:00 Sylvain Benner <notifications@github.com>:
