### ISSUE TITLE
Easy to reach key does nothing!

### ISSUE THREAD

**Issue by justbur** [syl20bnr/spacemacs#5041]
`SPC d` is really convenient to hit but does nothing. This is bad. I just don't know what it should do. :confused: Maybe `SPC dj` could play the theme song?

**Comment by StreakyCobra** [comment]
It's used as a mnemonic for «**d**o nothing» :-) Joke aside I already saw this when looking for placing the reporting function: I was thinking about `SPC d r` for **d**ebug **r**eport and saw it was not used.

More or less all direct access keys are already taken in spacemacs, and this can be the last opportunity to reserve a key for users. Having `SPC o` is already nice, but if you want to bind several functions you have to use `SPC o` as a prefix, and all functions are then at 2 or 3 key presses. Having `SPC d` would allow to have one prefix on `SPC o`, and one quick-access key on `SPC d`.

**Comment by syl20bnr** [comment]
We will find a use-case for it at some point, same for `y`.

@StreakyCobra We must be incredibly sure that we won't ever need `d` for Spacemacs. Maybe near the 1.0 but I won't take the risk until then.

**Comment by StreakyCobra** [comment]
Make sense :+1:

**Comment by justbur** [comment]
I'll bring it up again later then

**Comment by TheBB** [comment]
The dash layer places its bindings on `SPC d`.

**Comment by syl20bnr** [comment]
> The dash layer places its bindings on SPC d

Ouch this is not conventional, but it was one of the first layers and I guess the convention for documentation behind `h` was not yet a thing.

**Comment by StreakyCobra** [comment]
So it would be nice to have a PR proposing a move of dash bindings to `SPC h` prefix.
