### ISSUE TITLE
Error:invalid font name 

### ISSUE THREAD

**Issue by jinglunchn** [syl20bnr/spacemacs#5042]
I use     
    pacman -S emacs 
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

When I  open the emacs ,it shows   Error:invalid font name.-unknown-Oxygen-Sans-nolmal-normal-*-15-*-*-*-*-0-iso10646-1  

KDE5,Arch Linux

**Comment by StreakyCobra** [comment]
There isn't any mention of this font in the Spacemacs source code. How do you get this message without any special configuration? Have you modified your `.spacemacs`? Have you removed your old `.emacs` if any?

**Comment by jinglunchn** [comment]
![image](http://img.vim-cn.com/a0/fc2b177cce44fd8998a48b5b4f61b0b5a79775.png )

I donn't modify  .spacemacs   or   .emacs

**Comment by StreakyCobra** [comment]
So I'm clueless, maybe someone else can help on this…

You can try to install the Source-code-pro font to see if it helps:

```bash
pacman -S adobe-source-code-pro-fonts
```

**Comment by nixmaniack** [comment]
Just a hunch, as the error says, the font name isn't according to spec and that's why emacs font name parser is complaining about it. If possible try removing that font.

**Comment by jinglunchn** [comment]
It works.  Thank you! @nixmaniack

**Comment by corngood** [comment]
@jinglunchn What did you end up doing?  I got it to work by uninstalling `ttf-oxygen`, but that broke firefox, etc.  I ended up fixing it by moving to emacs 25, built by `emacs-git` from AUR.

**Comment by jinglunchn** [comment]
i uninstalled ttf-oxygen and choose other font. @corngood
