### ISSUE TITLE
Folding in Python Layer: `Folding is not supported in any of these major/minor modes`

### ISSUE THREAD

**Issue by djg321** [syl20bnr/spacemacs#5047]
How can I get folding to work while editing Python files?

Using `Spacemacs v.0.105.9` and `GNU Emacs 24.4.1`.

**Comment by djg321** [comment]
Fixed this by running "Update All Packages" from the home buffer!

**Comment by djg321** [comment]
Actually, it is broken again after updating packages again. Now I'm on `0.105.16` and the same version of emacs.

**Comment by StreakyCobra** [comment]
Could you update  your  issue to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? It will help us to help you :-)

**Comment by djg321** [comment]
@StreakyCobra I hope this helps:

#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.16
- Spacemacs branch: master (rev. cf8563b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv javascript sql python django auto-completion better-defaults emacs-lisp git markdown org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control)
```
#### Step by step reproduction guide
- Start emacs.
- Open a `.py` file that contains at least one function and/or class.
- Run `evil-toggle-fold` (you can just press `z a` while in normal state)
- Notice the message in the mini-buffer `Folding is not supported for any of the major/minor modes`. In messages, it shows up as a `user-error`. In `*Messages*`, it comes up as `user-error: Folding is not supported for any of these major/minor modes`.

`debug-on-error` doesn't seem to do anything for user errors, so I'm not sure how to go from here.

**Comment by StreakyCobra** [comment]
I can't reproduce this on `develop` with packages up to date. Can you try if it works for you there?

**Comment by mandarvaze** [comment]
I'm on 0.105.19
I can use ``z a`` to toggle the folds, yet this isn't as good as vim
e.g. I have a function (def) that has couple of "inner" functions (def inside def)
in spacemacs, ``z a`` folds only for the outermost function, where as in vim, If I am inside "inner" function, the ``z a`` will fold on the "inner" function correctly.

**Comment by nixmaniack** [comment]
@mandarvaze Have you tried new `origami` folding method? It's only available on `develop` though but much better than default one provided by `evil`.

**Comment by mandarvaze** [comment]
@nixmaniack I'm using ``yafolding`` for now. Seems good.
I'll wait for the release that contains ``origami`` - don't wanna switch to ``develop``
Tried adding it to ``additional-pacakges`` didn't work well (No built-in key bindings)

**Comment by hernrup-modelon** [comment]
This is still the primary issue that prevents me from moving to spacemacs from spacevim. As of now I dont know of any folding method that works for functions inside a class. Please dont close and please suggest a path forward.
