### ISSUE TITLE
elisp mode sometimes returns C help on ```,hh```

### ISSUE THREAD

**Issue by magnetophon** [syl20bnr/spacemacs#5056]
An example where this happens is ```concat```.
I'm on ```develop```.

**Comment by bmag** [comment]
What do you mean by "C help"? Can you please update your issue according to this [template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report), so it's easier to help you?
In this case, maybe a screenshot will help as well?

Keep in mind that parts of Emacs are implemented in C, including the `concat` function in `fns.c`. Here is what I see when I do `, h h` with the cursor on `concat`. I don't see any problem:
![help-on-concat](https://cloud.githubusercontent.com/assets/4334375/13028548/da3469b2-d27a-11e5-84dc-dceea693646a.png)

**Comment by TheBB** [comment]
Please reopen if you have more questions, @magnetophon.
