### ISSUE TITLE
spacemacs/restart-emacs should remember the open files

### ISSUE THREAD

**Issue by olejorgenb** [syl20bnr/spacemacs#5058]
Since emacs already have support for this (desktop-save) it shouldn't be particular hard?

**Comment by StreakyCobra** [comment]
What you are looking for is probably `dotspacemacs-auto-resume-layouts`, set it to `t`. If you don't have this variable in your `.spacemacs`, you can update it with `SPC f e D`. Let us know if it works.

**Comment by olejorgenb** [comment]
Well, wont that save and resume stuff when I quit and start it up later too?

My use case is when I fiddle with something that sometimes requires a restart of emacs to test. Isn't that when you typically would use spacemacs/restart-emacs? Or do people use it as way of cleaning out buffers and starting from scratch?

**Comment by StreakyCobra** [comment]
> Well, wont that save and resume stuff when I quit and start it up later too?

Yes, I see what you mean now. PR to change this in #5066

**Comment by olejorgenb** [comment]
Insanely responsive! Thanks :)

**Comment by sooheon** [comment]
@StreakyCobra Is it correct that this variable has no effect if `spacemacs-layouts` is not installed? I do not like all the other layouts stuff, but would like this behaviour.

**Comment by StreakyCobra** [comment]
@sooheon Yep, it's using `spacemacs-layout` for this purpose.

**Comment by olejorgenb** [comment]
It could fallback on desktop-save/read, but that might be a bit much complexity for a minor convenience?

**Comment by StreakyCobra** [comment]
If it is not too hacky and it's correctly documented I suppose @syl20bnr could accept it? Anyway I don't have time to work on this myself, but as usual, PR welcome :-)
