### ISSUE TITLE
How can I set keyboard shortcuts and registers globally and permanently?

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#5061]
I am trying to get a permanent and global shortcut for hiding Spacemacs on OS X. I have tried the following in `spacemacs/user-config`, but it does not appear to work in some modes, because they override "M-h":

```
(global-unset-key (kbd "M-h"))
(global-set-key (kbd "M-h") 'ns-do-hide-emacs)
```

Moreover, I make use of registers like this, to jump directly to certain files, however sometimes the registers appear to be cleared in new frames for some reason:

```
(set-register ?z (cons 'file "~/.zprofile"))
```

**Comment by StreakyCobra** [comment]
There are two issues here. For the first one can you try `(bind-map* …` instead?

For the second one I don't know. You'll probably be better to create a function that open you file, and then bind it in the `SPC o` prefix.
