### ISSUE TITLE
helm find files hangs spacemacs

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#5063]
When using helm for find files if you create a new file then you type SPC f f and helm opens, start typing the new file name and when the point gets to the end of the screem emacs hangs and I need to kill it and start again.

Is there a way to scroll the path that helm shows while you're typing? Sometimes you have some long paths and emacs just hangs.

I'm changing to ido for the moment, but I prefer helm for this.
Any help??

**Comment by robbyoconnor** [comment]
This is kinda known -- helm kinda sucks and is slow and clunky

**Comment by Andre0991** [comment]
Are you able to reproduce this with `~/.emacs.d/elpa/helm-[version]/emacs-helm.sh`?

**Comment by syl20bnr** [comment]
@jvillasante Do you have a repro step we can follow thoroughly to see if it can be reproduced ?
Do you think you can try without Spacemacs and only helm ?

**Comment by jvillasante** [comment]
It is easy to reproduce. Just SPC f f to open "helm find files" and start writing name of new file. When you get to the end of your screen horizontally emacs will hang and only kill the process will work.

The solution I'm using right now is using ido for find files, but helm is much better for me if it weren't for this issue.

**Comment by StreakyCobra** [comment]
@jvillasante Have you tried what's @Andre0991 suggested, i.e. running emacs with `~/.emacs.d/elpa/helm-[version]/emacs-helm.sh`?

Steps:

- Run `~/.emacs.d/elpa/helm-[version]/emacs-helm.sh` (change `[version]` to the right value).
- Press `M-x`.
- Enter `helm-find-files`.
- Try to reproduce your bug.

If the bugs is present here, it's **not** a problem on our side.
If the bug is **not** present, it a problem on our side.

**Comment by jvillasante** [comment]
@StreakyCobra, just run emacs as @Andre0991 suggested. The bug is not present there. It seems that it has to do with spacemacs and not helm itself.

Any suggestions??

**Comment by StreakyCobra** [comment]
@jvillasante I don't really know what to do, except maybe trying with system tools to see if you can identify a process/command that is blocked/consumming CPU/waiting/...

**Comment by jvillasante** [comment]
Does anyone have reproduced this issue or is it only happening to me?

**Comment by a3bhea** [comment]
I have the same problem after updating "lately" but with **projectile-find-file** . don't know what was my old version.

**Comment by jvillasante** [comment]
This is really odd, does anyone know how to debug emacs or see some kind of logs. I would really love to resolve this issue!

**Comment by jvillasante** [comment]
The problem persists, not only for creating new files. If you have a long path and want to open a file in there, helm will hang emacs when the path doesn't fit on the horizontal space of the helm prompt.

Dow anyone have this issue? Is there a solution?
It should be an option to scroll the input or have some kind of multiline support on the input.

I work with lots of devices and sometimes paths are really long, otherwise this shouldn't be too important. Right now I'm using ido or dired but sometimes I forget and use helm and have to restart emacs completely, maybe loosing some work!

TESTS:
'''
mkdir -p ~/tests/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/longpath/

touch ~/tests/.....<the holw path>.../file.txt
'''

Now try to use helm find files to open the file.txt at that long path!!!

**Comment by jvillasante** [comment]
I solved the issue, for now, adding this line to user-config

`(setq helm-echo-input-in-header-line nil)`

Now helm-find-files is not as beautiful as before but much more usable!

**Comment by StreakyCobra** [comment]
@jvillasante I still can't reproduce :-(

Can you try to:

1. Add `spaceline` to the `dotspacemacs-excluded-packages` in your `.spacemacs`
2. Comment your workaround line (i.e. `;; (setq helm-echo-input-in-header-line nil)`)
3. Restart emacs and test if the bug still happens?

It's like randomly shooting in the sky, but… who knows `¯\_(ツ)_/¯`

**Comment by robbyoconnor** [comment]
Sometimes the bullet hits something

--Rob

**Comment by jvillasante** [comment]
@StreakyCobra  the problem still persist after doing what you said. Right now the only thing working is setting helm-echo-input-in-header-line to nil.

**Comment by StreakyCobra** [comment]
@jvillasante It's not multiline, but it's scrolling horizontally without any problem.

![longpath](https://i.imgur.com/2z7AdiD.png)

**Comment by jvillasante** [comment]
@StreakyCobra thanks for showing me. I may be my build of emacs. emacs-25.1.50.2 (emacs-snapshot) directly from ubuntu repos. As soon as I have a time I wll compile my own build and see if that works.

**Comment by jbenden** [comment]
I am experiencing this bug too.

Each time I grab a backtrace of **Emacs**, it is looping infinitely on `redisplay_window` and `display_mode_lines`. I know it is stuck with `powerline` of **Spacemacs**, not upstream. I can reproduce the bug reliably, if anyone has any ideas on how to debug and patch this problem.

Best Regards,
-Joe

**Comment by Dridus** [comment]
@jvillasante thank you for posting your workaround. I've been experiencing this multiple times a day and been pretty frustrated, but so far the workaround is working for me (fingers crossed) and making helm faster even when it's not hanging.

**Comment by jvillasante** [comment]
This issue seems to be related to Emacs25. I just compiled from source and started using 24.5 and everything works as expected, I like helm better without the header-line. It seems that, on emacs, you can't be on the bleeding edge, it is better to wait 6+ months before jumping to a new release to give time to packages to catch up. Emacs25, by the way, was failing on so many things that I had to switch back to 24.5.

**Comment by Dridus** [comment]
FWIW I have:

`GNU Emacs 24.5.1 (x86_64-apple-darwin15.3.0, Carbon Version 157 AppKit 1404.34)`

by way of `brew install emacs-mac --with-spacemacs-icon`, so it doesn't seem to be purely Emacs 25.

**Comment by auser** [comment]
I'm also receiving this bug (and have been for a few weeks). Using `toggle-debug-on-quit`, most of the work is spent in helm.

**Comment by robbyoconnor** [comment]
Join Robert O'Connor and over 300 million other professionals already on LinkedIn

Sign up to become Robert's newest connection.

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67oj7-r6&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=DTEZwqZK&invitationId=6130896968165179393








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67oj7-r6&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQH3Z8GFWiWikwAAAVRVSbm_14qD2rTABo1oYEXu7qxxgQWDTt1Tin6cm0nj2AtLeiZl7Xqgw_FcFyvJbkLKPiwaZyM-nRoACDW5f_XfeGCXbyERZoCYluqeM0xF8YdNFhavlWF9JUKWzZqV_YvK8C655RfUECUBC82n_VcqDiORjO62Mc5bD96TqJBpx1otvjzY&eid=0-ini67oj7-r6


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67oj7-r6&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by qx** [comment]
+1 
<img width="1088" alt="2016-09-08 11 20 46" src="https://cloud.githubusercontent.com/assets/648406/18336021/73f23b68-75b6-11e6-8790-03dbeb4d8f91.png">

**Comment by robbyoconnor** [comment]
Please use the vote and don't +1 like this unless you have something to add. They added the ability to react with emojis -- use that.

**Comment by auser** [comment]
Okay... this has been a major blocker for me to use spacemacs. I've had to switch back to my old editor a few months ago as emacs/spacemacs literally blows up my computer after no more than 10 minutes of use (sometimes it's much less).

In any case, I'd love to get it debugged so I can get back on emacs. I can post my conf, if that would help?

**Comment by syl20bnr** [comment]
We have now the Ivy layer to replace helm, still on develop branch though.

**Comment by auser** [comment]
Oh man, that would be great... Is it close to release (in your opinion)?

**Comment by robbyoconnor** [comment]
Try out develop, if it's not stable (I have no issues) -- switch back to master (back up your elpa directory though so you dont have to download all packages again)

**Comment by qx** [comment]
helm removed.thanks

**Comment by JosephKiranBabu** [comment]
I am using Spacemacs on two identical MacBook Pro laptops (2015 model). I have this problem on only one of them. None of the workarounds worked for me in emacs version 25.1. After downgrading to emacs 24.5.1, I found there's an error which causes helm to not launch at all.

Seems like replacing helm with ivy may be a viable option. Can you please guide me on how to do that in my .spacemacs file?

**Comment by jvillasante** [comment]
@JosephKiranBabu 

Setting `helm-echo-input-in-header-line` to `nil` solves the `helm` issue. However, I ended up switching to `ivy` myself. For that you just need to  add `ivy` to `dotspacemacs-configuration-layers` and spacemacs will use `ivy` instead of `helm`. Everything works!!! The only feature I was missing from `helm` was `helm-c-yasnippet` which I use a lot (mostly for including header files in C++). I solved that adding this  to my spacemacs `user-config`:

```
  (spacemacs/set-leader-keys "is" 'yas/insert-snippet)
  (spacemacs/set-leader-keys "id" 'yas/describe-tables)
```

Hope that helps!

**Comment by JosephKiranBabu** [comment]
@jvillasante 
Thanks a lot for answering my newbie question.
Setting `helm-echo-input-in-header-line` to `nil` did not have any effect in my case. 
I've switched to ivy for now.

**Comment by d12frosted** [comment]
@JosephKiranBabu ivy is love, ivy is life

Sorry I just saw you message, so you was left on your own to switch to ivy. 😢

**Comment by robbyoconnor** [comment]
Everybody should switch to ivy.

**Comment by auser** [comment]
Isn't helm baked into spacemacs though? Or am I mistaken?
