### ISSUE TITLE
gtags layer "SPC m g is undefined"

### ISSUE THREAD

**Issue by istinspring** [syl20bnr/spacemacs#5064]
I activated gtags in .dotfile but "SPC m g is undefined". Any ideas?

**Comment by robbyoconnor** [comment]
That's major-mode dependent. I looked, the gtags layer doesn't define them. gtags defines a minor-mode, not a major-mode.

**Comment by robbyoconnor** [comment]
So it would help if you followed [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report) when reporting bugs. As it stands your report is woefully insufficient. What language were you using?

**Comment by istinspring** [comment]
yea, i see. It does not work in react mode.

JSX with ReactJS

**Comment by istinspring** [comment]
I wasn't sure if it's bug.

**Comment by robbyoconnor** [comment]
Okay, paste the output of `SPC hds`

**Comment by StreakyCobra** [comment]
@istinspring As @robbyoconnor say, you will get more help if you update your issue to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report).

**Comment by istinspring** [comment]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx org git gtags auto-completion better-defaults vim-powerline restclient syntax-checking
     (wakatime :variables wakatime-api-key "******" wakatime-cli-path "/usr/local/bin/wakatime")
     dash finance spacemacs-layout emacs-lisp markdown django react javascript python yaml html themes-megapack)
```

**Comment by tuhdo** [comment]
gtags layer does not support JS.

**Comment by istinspring** [comment]
even with ctags or pygments as a parser?

**Comment by tuhdo** [comment]
Yes, because gtags explicitly supports a few major modes, as Spacemacs policy. If you want gtags key bindings available in Js mode, you have to do it yourself and add a PR.

**Comment by TheBB** [comment]
Example:

```elisp
(spacemacs/helm-gtags-define-keys-for-mode 'js2-mode)
(spacemacs/helm-gtags-define-keys-for-mode 'react-mode)
```

I think we can close this, then.
