### ISSUE TITLE
Docs are Misleading

### ISSUE THREAD

**Issue by oliveratutexas** [syl20bnr/spacemacs#5071]
You can't straightup install spacemacs on ubuntu 14.04 LTS which is the current default distro for a lot of people. The default emacs version is 24.3.x when you need 24.4.x for a particular helm package. This should be corrected in the tutorial.

**Comment by izahn** [comment]
Which section of which tutorial?

**Comment by NJBS** [comment]
I believe he's referring to this section of the [README](https://github.com/syl20bnr/spacemacs#emacs).

**Comment by robbyoconnor** [comment]
http://emacs.link

**Comment by robbyoconnor** [comment]
I will correct this and make a PR tonight -- use http://emacs.link -- if you're using linux -- you should know how to compile software.

**Comment by robbyoconnor** [comment]
I will correct these docs

**Comment by robbyoconnor** [comment]
@oliveratutexas check out #5073, it links to the docs to build from source.

**Comment by oliveratutexas** [comment]
Sorry, I kinda got lost. 

I meant on the front page, it still lists 23.3 as compatible. I think under the quick install, you might want to warn users that they should either compile from source or use a version of their distro that has 24.4.

**Comment by StreakyCobra** [comment]
@oliveratutexas This has been addressed in the `develop` branch and will be in the next major release, except if @syl20bnr want to hotfix this in the next minor release.:

> Spacemacs is operational with Emacs 24.3, but Emacs 24.4 and above are highly recommended to enjoy a full experience. The next Emacs major release, Emacs 25, is not officially supported but is partially working (i.e. bugs should be expected).
> [...]
> Note: Ubuntu LTS 12.04 and 14.04 repositories have only Emacs 24.3 available. You are advised to build from source Emacs 24.4 or greater, as most packages require this version. The same may be true for other distributions as well.

Also, we will probably remove officially 24.3 support in the next major release.

**Comment by robbyoconnor** [comment]
@oliveratutexas I did precisely that. Check out the commits linked.

**Comment by syl20bnr** [comment]
Will be probably part of 0.105.10, I started to cherry-pick all the relevant docs improvements.

**Comment by robbyoconnor** [comment]
@oliveratutexas it's fixed :)
