### ISSUE TITLE
Allow delete-window on sole ordinary window in frame

### ISSUE THREAD

**Issue by edrex** [syl20bnr/spacemacs#5072]
You know, `Attempt to delete minibuffer or sole ordinary window`

It's core Emacs, but does anyone else find it really annoying? 

When I type `cmd-w` or `SPC w c` in a frame with only one window, I really do want to close the frame.

I think the reasoning is that you might want to keep emacs server running, but:

 - Arguably it should only care if this is the sole window *in the last frame*, since otherwise the server will stay up. I tend to have multiple Emacs frames open to different projects and value being able to quickly clean them up when not needed.
 - In OSX, where I live right now, closing the last window doesn't quit the app

Something I'm missing that would make this more ergonomic? Could spacemacs "advise" `delete-window` to be smarter (IDK what I'm talking about, just making up words that sound elispy)? Upstream? Thanks :)

**Comment by edrex** [comment]
discovered `delete-frame` is mapped to `s-W`, that's probably what I should be using. seems like it would be nice if it was available under the global leader somewhere, might come back to this later

**Comment by TheBB** [comment]
`SPC q z` may be what you are looking for.
