### ISSUE TITLE
Symbol's function definition is void: helm-mini

### ISSUE THREAD

**Issue by abaitam** [syl20bnr/spacemacs#508]
Spacemacs 0.51.0

Error in subject when trying to switch buffers: SPC b s

**Comment by syl20bnr** [comment]
There seems to be a lot of issues with helm and the update of packages, to be sure it is not related to one of these problems, can you wipe out your `elpa` directory and restart emacs ?

**Comment by abaitam** [comment]
Yes, that fixed it. Thanks a lot.

**Comment by syl20bnr** [comment]
Keeping track of this issues here: https://github.com/emacs-helm/helm/issues/853
