### ISSUE TITLE
[command] cursor does not follow slurp and barf

### ISSUE THREAD

**Issue by johanatan** [syl20bnr/spacemacs#5086]
... so subsequent slurps and barfs are harder than need be; i.e., repeated slurping or barfing is clumsy.

[I'm not quite sure which paredit, parinfer, etc setup Spacemacs has out of the box but this particular feature would be a nice to have].

**Comment by sooheon** [comment]
Not sure what the problem is with default, but I highly recommend the evil-cleverparens layer, and also looking into lispy (not a layer yet). They both have good parens wrangling.

**Comment by TheBB** [comment]
Can you provide an example? I haven't experienced any problems.

**Comment by johanatan** [comment]
Put your cursor on a closing brace. Invoke 'slurp'. Notice that the cursor does not follow the brace (although you can still press 's' additional times for consequent slurps). It would be easier to follow if the cursor actually followed the brace being moved (and I have seen others' emacs setups do this).

**Comment by TheBB** [comment]
You should report this to smartparens then.

**Comment by johanatan** [comment]
I realized that it is probably intentional and have in the meantime adjusted to the behavior. Having used someone else's emacs for a while before my own, I was accustomed to the other behavior (and still think it is better) but I have no idea how the other emacs was setup and am pretty sure the smartparens guys would not welcome this behavior change request.

**Comment by johanatan** [comment]
@TheBB Do you know the project link for smartparens? I am experiencing an even worse effect with barf. If you barf once, a subsequent keypress on 'b' does not continue to barf more forms from the just initiated form but will rather interpret it as a new barf on whatever (likely ending brace) char ends up under the [non-moving] cursor. This is very strange (and unhelpful) behavior.

Could SpaceMacs consider using a different smart parenthesis library (such as paredit or parinfer)?

**Comment by TheBB** [comment]
https://github.com/Fuco1/smartparens

**Comment by johanatan** [comment]
Thanks. What about the second part of my question?
