### ISSUE TITLE
Customize evil-tutor based on dotspacemacs-editing-style

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#5088]
The instructions on how to re-enter the evil-tutor (under the headline "1.2 ENTERING AND EXITING EMACS") is incorrect based on which editing style you are using. This can be confusing for beginners that haven't used either of the editors earlier.

I'm using evil-style, and the instructions I get is that I should type in `M-x evil-tutor-start`, then in Spacemacs I should use `<SPC> h T`.

I'm aware it's correct for emacs-style users trying to learn vim's style, but shouldn't they already have changed to evil-style because the tutorial is meant to be interactive and not just read?

I purpose that that line (number 3) should change based on the value of the `dotspacemacs-editing-style` variable.

**Comment by robbyoconnor** [comment]
If you are using `SPC` you are already using the vim editing style..using the emacs editing style the leader key is `M-m`

**Comment by Otterhall** [comment]
@robbyoconnor I'm aware that I use vim editing style, but the instructions assume that the user use emacs style (e.g. says to type in `M-x evil-tutor-start` to start the evil tutorial), and not evil-mode.

**Comment by TheBB** [comment]
I don't particularly see the problem. `M-x` will still work even in evil.

**Comment by YayConnolly** [comment]
I was also confused by this as a new user. Had to google what "M" stands for in emacs land. Tried both "option+x" and "esc, x" on my mac while in the vim tutor buffer, and neither worked. Eventually discovered that "esc, x" works from the home buffer (still not sure why...)

In general it would be good to err on the side of over-explaining in the tutorials. Otherwise enjoying spacemacs so far, thanks to all contributors!

**Comment by Nikolaiam** [comment]
For me also the `M-x` keybindings and learning saving with `:w` etc was a bit confusing, and I learned the (faster) Spacemacs way of `SPC f s` only later. In essence, the tutorial now introduces an absolute beginner with both some classic Emacs keybindings and vanilla Vi keybindings. These are by no means bad things to know, but in my opinion the tutorial should consistently introduce the beginners to the Spacemacs evil keybindings and only mention the other options as alternatives. This way the newcomer would learn the "Spacemacs way" right from the start and would have an easier time to learn only one "paradigm".

If I've understood correctly, the Evil tutorial is a separate package from Spacemacs. I would be happy to edit the text of the tutorial but don't know what is the best way to do it: should I fork the original evil-tutor repo and edit the text there, making a spacemacs-evil-tutor?
