### ISSUE TITLE
Document format issue

### ISSUE THREAD

**Issue by wood9366** [syl20bnr/spacemacs#5089]
I find a simple issues when reading spacemacs doc.

![emacspace_err1](https://cloud.githubusercontent.com/assets/1407539/13072735/df08afc2-d4d5-11e5-82c6-669acf68ca2c.png)

**Comment by AlejandroCatalina** [comment]
I think that was reported somehow. Seems like the comma is a special character and we haven't found a way to display it nicely.

**Comment by StreakyCobra** [comment]
@wood9366 Thanks for reporting it :smiley: This is a known issue (https://github.com/syl20bnr/spacemacs/issues/4869) I'm closing this one as duplicate then, but can you report your comment on the other thread so we don't forget it? :relaxed: Thanks
