### ISSUE TITLE
Howto get a persistent spacemacs window position and size?

### ISSUE THREAD

**Issue by triklsbg** [syl20bnr/spacemacs#5095]
What is the minimum action required to get a ...  between spacemacs restarts?  Shouldn't be this a faq-candidate ? or the default behaviour ?

**Comment by Andre0991** [comment]
I think the layer `spacemacs-layouts` can do that. It uses `persp-mode.el` to do it.

**Comment by synic** [comment]
This fellow made a layer to do it: https://github.com/aaronjensen/spacemacs.d/tree/master/layers/frame-geometry

**Comment by synic** [comment]
Also here is a gist if you just want to put it in your .spacemacs: https://gist.github.com/synic/0357fdc2dcc777d89d1e

**Comment by triklsbg** [comment]
Thanks synic! I didn't expected such an expensive solution. @Andre0991: I will take a look at spacemacs-layouts. 
@StreakyCobra: The faq- and default-part of the question remains open for me.

**Comment by StreakyCobra** [comment]
@triklsbg According to https://github.com/syl20bnr/spacemacs/issues/1585#issuecomment-185104479 it seems that `spacemacs-layout` offers this possibility. I have a tailing window manager so I can't test, but I suppose you can try it by setting `dotspacemacs-auto-resume-layouts` to `t` in your `.spacemacs`.

CC @nixmaniack

**Comment by nixmaniack** [comment]
In case it gets more confusing, I referenced spacemacs-layouts in #1585 considering that OP wants to restore `emacs` window layout posioning, not the OS window(frame in emacs jargon) positioning. If that's the case then what synic pointed is the way to go. I had that kind of snippet some time back, not anymore(as I use one frame with many layouts now)

**Comment by StreakyCobra** [comment]
Indeed it's confusing even in the linked issue. Ok, so `spacemacs-layout` is not a solution then.

@triklsbg As you just went through this configuration, you are the best person to write the FAQ entry :-) It's a nice way to get started if you want to contribute. Please just read the [guidelines](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org) first. If you can't or don't want to, I reopen it and mark it as beginner friendly documentation.
