### ISSUE TITLE
Non-logical comint/shell/repl history keybindings?

### ISSUE THREAD

**Issue by olejorgenb** [syl20bnr/spacemacs#5096]
We all agree that:
k = up
j = down

If this is what I've typed in the repl:

entry1
entry2
entry3 

I would expect that k should revive `entry3`, not `entry1`, right?

But the default keybindings are:

     (evil-define-key 'insert comint-mode-map
        (kbd "C-k") 'comint-next-input
        (kbd "C-j") 'comint-previous-input)
      (evil-define-key 'normal comint-mode-map
        (kbd "C-k") 'comint-next-input
        (kbd "C-j") 'comint-previous-input)

so what actually happens when I press C-k is that I get `entry1` back.

Is this actually intended? (probably not judging from https://github.com/syl20bnr/spacemacs/search?utf8=%E2%9C%93&q=comint-next-input)

All other shells and repls uses the convention that up/previous moves up in the history list.

C-p in bash and others,
k in zsh's vi emulation (in normal mode),
\<up\> in bash
...

**Comment by bmag** [comment]
Wow, I didn't even notice this until now because I'm used to `M-n` and `M-p`.
I think it's a bug.

**Comment by AlejandroCatalina** [comment]
Anyone addressing this one?

**Comment by bmag** [comment]
I can address this one tomorrow unless @olejorgenb wants to make a PR himself/herself

**Comment by olejorgenb** [comment]
@bmag I can do it. Not very efficient of course, but it's a nice excuse to get acquainted with the dev process :) (if I'm not done by sunday it's up  for grabs though)

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
