### ISSUE TITLE
Add/change JS modes to support template strings better

### ISSUE THREAD

**Issue by wraithan** [syl20bnr/spacemacs#5097]
ES6 added [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings) which don't appear to be supported at all with the current JS mode. If I have something like: 

```javascript
var stuff = `leaving an open paren for later: (`
```

It causes the rest of my braces to highlight with mismatch errors. These need to be treated as strings with extra syntax in them for variables.

**Comment by robbyoconnor** [comment]
This is an issue with [js2-mode](https://github.com/mooz/js2-mode) and not us.

**Comment by robbyoconnor** [comment]
Strike that nevermind

**Comment by wraithan** [comment]
My mistake. I assumed the `javascript` layer was enabled by default because I had syntax highlighting, but I guess I was wrong and it wasn't. Enabling it fixed template strings (and added some linting crap that I'll have to hunt down and eradicate since it doesn't match my lints).

**Comment by robbyoconnor** [comment]
It's using jshint or eslint via flycheck

--Rob

**Comment by robbyoconnor** [comment]
You can Add A Style Guide easy

--Rob

**Comment by wraithan** [comment]
@robbyoconnor actually, in this case it was built in lints to js2-mode. Specifically their `js2-strict-inconsistent-return-warning` that was causing the problem. Setting that to `nil` fixed it.

**Comment by robbyoconnor** [comment]
@wraithan ahhh!

**Comment by robbyoconnor** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67of1-hs&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=JXWhgECr&invitationId=6130896967385038848








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67of1-hs&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHrOWHz_MHhswAAAVRVScK2WuA7WAxUbwE-vDG8wcLFS4mP7nDLzbBjqnWVVRcVjVxY8P1gqOKul3kfNgoGhmPkKTZlqBDsblv4HBHOCNk44Nt9M-6WztAGQHRChSLB4ODnhzR4JDz9UI2MN5XXT3suJ55Y2qhxEw5e9BIhABANTZ2VqKiK0M3mZLngvfDwIU5H&eid=0-ini67of1-hs


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67of1-hs&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
