### ISSUE TITLE
Explain the basics of Org-mode for beginners

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#5098]
All documentation attached with Spacemacs is in org-files. Alas, knowing how to browse and read org files is necessary for a person to get a basic knowledge about Spacemacs.

But currently it's doesn't explain the very basics of org-mode. The only reason that I know how to expand the headlines and show their content is that I have read Org-modes' info files in an earlier adventure with Emacs.

I propose that the basics of browsing and reading org files should be added besides the Evil and Emacs tutorial in the "Quick Help" box on the start buffer. A relevant headline could be "How to read Spacemacs' documentation in Emacs".

**Comment by thang1thang2** [comment]
Possible solutions (other than, or in addition to, a guide in the quick help box) might be: 

1. Have a function determine when the first time someone ever opens an org file is. If they open an org file for the first time, pop open a friendly "click big red button to go to quick interactive tutorial" (implementation of button is left as an exercise to the reader)
2. Make the internal org documentation files open in fully expanded mode by default. People who know what they're doing can simply collapse whatever they don't want, probably with sparse tree or however they do it.
3. Make the start page itself an org file (or in org mode or whatever) and put some useful tips in it. That way all users see org mode at least once. It'd also have the added benefit of working nicely if you want the startup page to have, say, your org-agenda (currently it just pastes in the file as verbatim white text and it looks ugly if you have lots of links)

**Comment by syl20bnr** [comment]
> Make the start page itself an org file


Interesting idea.

**Comment by fbob** [comment]
yep excellent one !

**Comment by syl20bnr** [comment]
I thought about it and there is one inconvenient to do it, org must be installed and required before being used to prevent bugs due to the version of org that ships with Emacs and the version of org we use from the org Elpa repo.

**Comment by TheBB** [comment]
When opened via `SPC h SPC`, the documentation is opened in a special view mode which ensures that all the headlines are expanded.

**Comment by a13ph** [comment]
Possible workarounds/additions:
- provide links between web (browser) and orgmode versions of help files (all or most novice-critical ones, IDK)
- make a key for that and add it to [?] in home buffer
