### ISSUE TITLE
Font is changing when opening a new frame

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#5099]
I'm using the following code in my .spacemacs file to set a custom font, which works without a problem. But once opening a new frame with `C-x 5 2` the font is different in the new frame! Is this a bug?

```
    (when (string= system-name "shahn-T450s")
      (setq dotspacemacs-default-font '("Hack"
                                        :size 14
                                        :weight normal
                                        :width normal
                                        :powerline-scale 1.25))
      )
```

**Comment by sebhahn** [comment]
I already identified the problem. It is coming from

```
    ;; theming-modifications
    ;; '((sanityinc-tomorrow-eighties
    ;;    ;; Font locking
    ;;    (font-lock-string-face :foreground "#99cc99")
    ;;    (font-lock-type-face :foreground "#cc99cc")
    ;;    (font-lock-function-name-face :foreground "#6699cc"))
    ;;   (base16-tomorrow-dark
    ;;    (default :background "#2d2d2d")))
```

which is just written above. As soon as I uncomment the custom theme modification the bug occurs.

**Comment by StreakyCobra** [comment]
@TheBB Do you have any info about this?

**Comment by TheBB** [comment]
@sebhahn Can you show me exactly where you put that code in your dotfile?

**Comment by TheBB** [comment]
Actually I can reproduce something similar, but it appears to work (that is, to not work) independently of the `theming` layer. Instead I get a different font in the new frame if I set `dotspacemacs-default-font` to something that is not equal to the system monospace font.

**Comment by syl20bnr** [comment]
@sebhahn if you use the default Spacemacs font (Source Code Pro), do you still have the problem ?

**Comment by sebhahn** [comment]
yes, e.g. if I change the default font size, the font size will be different in the new frame

**Comment by microamp** [comment]
I have the same issue on OS X. The font in the other frame doesn't appear to be a monospace font.

**Comment by et2010** [comment]
I have the same issue on archlinux, with spacemacs on develop branch.

**Comment by TheBB** [comment]
I can't reproduce this any more in 0.200
