### ISSUE TITLE
The mode-line is empty

### ISSUE THREAD

**Issue by razcampagne** [syl20bnr/spacemacs#510]
Hi,

After a git clone and the first boot, the modeline doesn't show any text and an error message appear in the *Message* buffer: Error during redisplay: (eval (spacemacs/mode-line-prepare)) signaled (error "Bad bounding indices: 0, 1")

I am running emacs from git on an Archlinux.
Thanks for your help.

**Comment by syl20bnr** [comment]
What is the emacs version ?

**Comment by razcampagne** [comment]
This is the latest from git as of jan 30. emacs-version reports 25.0.50.1

**Comment by syl20bnr** [comment]
Spacemacs is not tested with the trunk, only 24.3 and 24.4 are officially supported.

**Comment by TheBB** [comment]
I'm closing this on the grounds that

* it's an old issue
* it's an unsupported version of Emacs
* the modeline has gone through a major refactoring, so this bug may or may not be reproducible any more

If you find it's still present, please reopen or report anew.
