### ISSUE TITLE
use evil-search in evil buffers

### ISSUE THREAD

**Issue by edrex** [syl20bnr/spacemacs#5101]
In Vim, I seem to be able to do `/ c-r 0 Enter` to search for the contents of the yank register, but this doesn't work in Spacemacs. I didn't find an issue for this specifically upstream, only https://bitbucket.org/lyro/evil/issues/166/some-key-bindings-are-missing-in-command.

Am I missing something?

**Comment by StreakyCobra** [comment]
Upstream maintainer says it is not possible in minibuffer (what is used by the search command):

> Please note that (currently) evil is not enabled in the minibuffer, so some commands may not work as expected.

But he also give a way to use it on buffers where evil is enabled:

    (define-key evil-ex-completion-map "\C-r" #'evil-paste-from-register)

So I don't really know what you want more from us?

**Comment by edrex** [comment]
`c-r` works as expected in command mode, so i wonder what is the difference from search mode? Where is the command mode shortcut defined, in evil or in the spacemacs layer for evil?

**Comment by StreakyCobra** [comment]
The search input field is in the  minibuffer, so it's not in evil mode as explained by the maintainer, so the binding is not working there.

**Comment by edrex** [comment]
From my reading of the upstream maintainer's comment, it sounds like both command mode and search mode use the minibuffer. So I wonder why the register substitution binding works in command mode but not search mode. If it was just overlooked, maybe it will be a simple fix.

**Comment by StreakyCobra** [comment]
AFAIK we are not modifying evil a lot, so I'm not sure it's a Spacemacs issue.

**Comment by edrex** [comment]
Confirmed it is the same with just evil mode, see https://bitbucket.org/lyro/evil/issues/166/some-key-bindings-are-missing-in-command#comment-25571090

**Comment by StreakyCobra** [comment]
Update: You can set-it up by adding the following line in the `dotspacemacs/user-init` function of your `.spacemacs`:

    (setq-default evil-search-module 'evil-search)

**Comment by syl20bnr** [comment]
Should we set it for evil users ?

**Comment by StreakyCobra** [comment]
@syl20bnr I asked myself the same question, and the answer is:

No, until https://github.com/syl20bnr/spacemacs/issues/1326 has been fixed.

**Comment by edrex** [comment]
proposing :arrow_up:

**Comment by syl20bnr** [comment]
@StreakyCobra thank you for the link, I'll look at it.

**Comment by StreakyCobra** [comment]
PR pending #5727

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by mikelui** [comment]
I'm still seeing this issue with version 0.200@25.1.1.

Yanking into register 'a' (`"ay`) and searching for it (`/C-r a`) only results in a search for the char '`a`'. Pasting still works in normal mode (`"ap`).

I didn't change any default init or configs. I've only enabled the syntax-checking, auto-completion, c-c++, and shell configuration layers, selecting evil and helm at the first spacemacs initialization.

**Comment by syl20bnr** [comment]
Should be fixed in develop branch, with commit https://github.com/syl20bnr/spacemacs/commit/c7e47de

**Comment by CMCDragonkai** [comment]
So is it set by default, or do we have to change something in our config?

**Comment by syl20bnr** [comment]
It is set by default but there are some minor regression with it, the face color is different and it appears on top of the selection face, also :noh does not work I believe.
