### ISSUE TITLE
Yanking and pasting in Haskell mode inserts spurious space at beginning of line

### ISSUE THREAD

**Issue by nmk** [syl20bnr/spacemacs#5106]
In haskell-mode yanking and pasting a line with `yyp` indents the newly pasted line by one space. So pressing `yypyypyyp` on a line containing `foo` results in
```
foo
 foo
  foo
   foo
```
Any idea what might be going on there? I can not see this in other modes, so I assume it is solely haskell-mode related.

I am using the develop branch and the latest haskell-mode from MELPA.

**Comment by kRITZCREEK** [comment]
this is actually really annoying...

**Comment by StreakyCobra** [comment]
There are already problems with haskell indentation:

https://github.com/syl20bnr/spacemacs/issues/621
https://github.com/syl20bnr/spacemacs/issues/5010

I'm pretty sure it's an upstream issue, but it would be nice if someone can try on a stock Emacs with just `haskell-mode` enabled.

CC @d12frosted

**Comment by fice-t** [comment]
Is this really an upstream issue? It appears that after pasting, `spacemacs/yank-advised-indent-function` gets called, which calls `indent-region`, which would produce this result.

This of course doesn't happen on my stock Emacs.

**Comment by StreakyCobra** [comment]
> This of course doesn't happen on my stock Emacs.

So it's a problem on our side

**Comment by syl20bnr** [comment]
Quick solution is indeed to add haskell-mode to `spacemacs-indent-sensitive-modes`.

Work around is to use the universal prefix argument when pasting to disable the indentation but I'm aware this is pretty inconvenient.

**Comment by spencerturkel** [comment]
How does one add haskell-mode to spacemacs-indent-sensitive-modes?

**Comment by rrottier** [comment]
I am having the same issue but with the stable branch (0.105.11)

**Comment by robbyoconnor** [comment]
I may be wrong but: 

`(add-to-list spacemacs-indent-sensitive-modes 'haskell-mode)`

**Comment by robbyoconnor** [comment]
PR coming

**Comment by robbyoconnor** [comment]
@nmk @spencerturkel, @kRITZCREEK: pull my PR local

**Comment by rpglover64** [comment]
@fice-t @StreakyCobra I consider this an upstream issue:

From https://github.com/haskell/haskell-mode/issues/796:
> rpglover64: I think this is a misfeature in `haskell-indentation-indent-region`.
> gracjan: Region indentation can be considered unimplemented feature. We do not have that working yet.

See also: https://github.com/haskell/haskell-mode/issues/1032

That said, I think this is the appropriate fix for now.

**Comment by fice-t** [comment]
While `indent-region` is indeed screwed right now, I'd still say that the main issue is that `yyp` shouldn't be indenting the region in `haskell-mode`, like it doesn't in `python-mode`.

**Comment by rpglover64** [comment]
Good point.

**Comment by robbyoconnor** [comment]
I missed a closing paren when reordering the list...that said, this should fix it -- it applies the fix proposed by @syl20bnr  just pull in #5167 local :)

**Comment by rrottier** [comment]
Tried it locally and it works for me.  Thanks.

**Comment by robbyoconnor** [comment]
Np :heart:

**Comment by spencerturkel** [comment]
Robby's fix works perfectly. Thanks!

**Comment by syl20bnr** [comment]
Fixed in 0.105.12
