### ISSUE TITLE
Setting - dotspacemacs-colorize-cursor-according-to-state nil - defaults to insert color

### ISSUE THREAD

**Issue by kRITZCREEK** [syl20bnr/spacemacs#5107]
#### System Info
- OS: windows-nt
- Emacs: 25.0.50.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop (rev. b3296d2)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
 emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh")
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 syntax-checking version-control
 (haskell :variables haskell-enable-ghc-mod-support t)
 (javascript :variables javascript-disable-tern-port-files nil)
 eyebrowse html purescript)
```

Steps to reprodude:

- Set `dotspacemacs-display-default-layout nil` and start emacs with the leuven theme 
- Get a green cursor. The default cursor color for leuven however is cyan. 
- Reload the theme using `SPC T h leuven`
- Get the cyan cursor

**Comment by jnboehm** [comment]
I also have this issue with Emacs 25.1.50.7 using spacemacs v.0.105.11 on the master branch.

I am using input method `emacs`, although that probably does not matter.

**Comment by kRITZCREEK** [comment]
I've not seen this for a while now.
