### ISSUE TITLE
helm-register is empty

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#511]
I can't see anything in `helm-register`.  There are no candidates, and no actions attached to the buffer.

Looking at the source candidates for this function, it seems to pull form `register-alist` which is populated. 

Using Emacs 24.4.1.

**Comment by syl20bnr** [comment]
Wipe elpa directory and restart. I bet this is another helm upgrade issue. I have yet to find where this issue comes from, I would be surprised that it comes from spacemacs but it is a possibility.

**Comment by syl20bnr** [comment]
BTW I tested on my spacemacs instances and it works.

**Comment by syl20bnr** [comment]
Keeping track of this issues here: https://github.com/emacs-helm/helm/issues/853

**Comment by syl20bnr** [comment]
I close this since I have no news and it is pretty sure that a wipe fixes it.
Reopen it if it is not the case.
