### ISSUE TITLE
feature request: expand nixos layer.

### ISSUE THREAD

**Issue by magnetophon** [syl20bnr/spacemacs#5117]
Would it be possible to include https://github.com/travisbhartwell/nix-emacs ?

@CestDiego I saw you are a contibutor there as well, so I assume you planned to do this anyway at some point?

**Comment by StreakyCobra** [comment]
@magnetophon I think it's already implemented in Spacemacs: https://github.com/syl20bnr/spacemacs/blob/de2c3cc724e0886dd8bce97c8fe5b00f5f237e75/layers/nixos/packages.el#L3-L5

Also @travisbhartwell is a regular Spacemacs contributor/user :-)

**Comment by travisbhartwell** [comment]
@magnetophon This is already includes the published modules from the nix-emacs repo (see https://github.com/syl20bnr/spacemacs/blob/develop/layers/nixos/packages.el#L1-L5).  Right now, all that's missing is nix-sandbox, which was just published last night on MELPA.

I'll go ahead and do a PR tonight to include that functionality.

Is there anything else that you find missing @magnetophon?  If there are any features you find missing  in general from nix-emacs, feel free to file a bug over there and we'll try to respond. :)

**Comment by puffnfresh** [comment]
@travisbhartwell did that PR ever land? I'd find it useful!

**Comment by travisbhartwell** [comment]
@puffnfresh Sorry!  I got distracted, you know how that goes.  I'll get to that this week.

**Comment by reckbo** [comment]
Has anyone managed to get spacemacs+haskell-mode+shell.nix working?

**Comment by reckbo** [comment]
Never mind, you just need to configure cabal in the nix shell and haskell-mode will work fine (although I have yet to get ghc-mod working)
