### ISSUE TITLE
Navigation/scrolling micro mode

### ISSUE THREAD

**Issue by MichaelMackus** [syl20bnr/spacemacs#5118]
What happened to [this](https://github.com/syl20bnr/spacemacs/pull/725)?

It looks like there's still functions for `spacemacs/scroll-half-page-down` and `spacemacs/scroll-half-page-up`. It would be nice to bring back the navigation micro state, though - much more comfortable when leisurly browsing code.

**Comment by syl20bnr** [comment]
`SPC n` does not work anymore ?

**Comment by MichaelMackus** [comment]
@syl20bnr ah my bad, that's the keybind I was looking for!
