### ISSUE TITLE
Missing autocomplete popup for c/c++ mode with clang_complete

### ISSUE THREAD

**Issue by paul-g** [syl20bnr/spacemacs#5122]
Hi, I've been following a tutorial on auto-complete for c/c++ with clang_complete and can't really get it to work. I think clang_complete is working since I can see autocomplete suggestions in the `clang_output` buffer. But the suggestions aren't displayed in a pop-up. auto-complete works for elisp files.

I am using: clang v 3.8.0, emacs 24.5.1, spacemacs 0.105.9.

To the clean checkout I only add the following to the configuration layers:

```
auto-completion
(c-c++ :variables c-c++-enable-clang-support t)
``` 

I also tried adding (global-company-mode) in dotspacemacs/user-config or enabling company-mode locally in the buffer but no effects.

Is there anything wrong I'm doing or is this a bug?

**Comment by paul-g** [comment]
Switching from clang 3.8 to clang 3.6 fixes this issue. If 3.6 is a requirement, maybe this should be included in the docs somewhere, I couldn't find any mention of this myself.

**Comment by syl20bnr** [comment]
We should report this bug in the appropriate place also.

**Comment by TheBB** [comment]
Clang 3.8 isn't even released yet from what I can see. I'm not sure this is something we need to care about until that happens.

**Comment by paul-g** [comment]
Yes you are right, sorry I lost track of this. Feel free to close from my part.
