### ISSUE TITLE
spacemacs/helm-persp-switch-project assumes projectile is loaded

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#5127]
The `spacemacs/helm-persp-switch-project` function (bound to `SPC p l` by default) assumes that the `projectile` package is loaded (specifically, it assumes that the `projectile-project-p` function is defined). This means that running `SPC p l` immediately after starting spacemacs yields an error. One solution is to add `(autoload 'projectile-project-p "projectile")` somewhere but I don't know if this is the "correct" solution or where this line should go.

**Comment by StreakyCobra** [comment]
See https://github.com/syl20bnr/spacemacs/issues/5388 for a more detailed bug report.

**Comment by bixuanzju** [comment]
Adding `projectile-project-p` under `:commands` in `spacemacs-base/init-projectile` fixes the problem for me. Not sure if it's the correct way to do. If so, I could open a PR.

**Comment by d12frosted** [comment]
@bixuanzju I just wanted to propose the exact fix. Please, send a PR :)

**Comment by bixuanzju** [comment]
@d12frosted done :)

**Comment by d12frosted** [comment]
Thanks!
