### ISSUE TITLE
Neotree broken after 0.52.1 update

### ISSUE THREAD

**Issue by stormpat** [syl20bnr/spacemacs#513]
After the latest update neotree is no longer working, when toggling ```SPC f t```

```elisp
Debugger entered--Lisp error: (void-function neotree-toggle)
  indirect-function(neotree-toggle)
  command-execute(neotree-toggle)
``` 

Im on OSX with homebrew Emacs version 24.4.1

**Comment by bjarkevad** [comment]
:+1: Observing the same behaviour here, it seems like `neotree-toggle` isn't bound to any key

**Comment by syl20bnr** [comment]
This is probably another case of helm upgrade which went wrong... wipe out `elpa` directory and restart spacemacs, I bet you'll be ok.
I have yet to find out what's going on with helm updates, I'm pretty sure that it is not caused by spacemacs.

**Comment by syl20bnr** [comment]
Keeping track of this issues here: https://github.com/emacs-helm/helm/issues/853

**Comment by tuhdo** [comment]
`neotree-toggle` works fine for me, with latest Helm, either in Spacemacs or in my own Emacs setup.

**Comment by syl20bnr** [comment]
I checked this morning and this is not related to Helm, I was checking several issues and made a mistake on this one.
On a side note: For now I won't be able to deal with Helm efficiently since unfortunately I'm not on good terms with the Helm maintainer, of course this is for stupid reasons but that's the current situation.

**Comment by syl20bnr** [comment]
It does not change anything with helm and spacemacs, helm is great and spacemacs would not be spacemacs without it.

**Comment by tuhdo** [comment]
@syl20bnr :+1: 

Helm maintainer expects that when you report an issue, it must be precise and reproducible to save his time, otherwise he will be confused, i.e. He can quickly decide if such issue like this is resolvable: https://github.com/emacs-helm/helm/issues/855

**Comment by syl20bnr** [comment]
You're the man ! Thank you :-)

**Comment by stormpat** [comment]
Fixed after emptying the elpa dir.
