### ISSUE TITLE
ycmd layer broken?

### ISSUE THREAD

**Issue by paul-g** [syl20bnr/spacemacs#5134]
I am trying to use the ycmd layer for auto-completion in c-c++ mode but I get a fairly cryptic error in the `ycmd-server` buffer:

```
AssertionError: Header name u'X-Ycm-Hmac' is not a string in (u'X-Ycm-Hmac', '1TuuczWfaKEYFGpT6qAOWbxwT8Pi/2LbJhFY8azXYGk=')
```

Any suggestions on this? I am using emacs 24.5.1, spacemacs 0.105.9, ycmd at revision 7a105f5.

My only changes of the stock `.spacemacs` are 

1. enable the auto-completion, ycmd and c-c++ layers  
2. add the path to the ycmd package 
3. whitelist ycm_extra_conf.py for my project.

**Comment by syl20bnr** [comment]
Is this linked to #5122 ?

**Comment by paul-g** [comment]
I don't know. I was using clang 3.6 and my layer configuration is: 

```
   dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     auto-completion
     ycmd
     c-c++
     ;; better-defaults
     emacs-lisp
     ;; git
     ;; markdown
     ;; org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     ;; syntax-checking
     ;; version-control
     )
```

**Comment by paul-g** [comment]
Maybe I'm not using the right revision of ycmd? Is there any known revision which should work out of the box with spacemacs?

**Comment by paul-g** [comment]
Actually, this was caused by ycmd, this is the related issue https://github.com/Valloric/ycmd/issues/377. 
Moving to the more recent ac86134 fixed the issue for me. 

To prevent these problems in the future, is there any way spacemacs could add something to check the configuration of external tools? It seems that anything which requires an external tool (like autocompletion, which I'd say is pretty important for programmers) requires the spacemacs user to jump through some hoops and figure out a lot of details. I think especially for tools installed from git it should be pretty easy, all we need to record is the url and revision for external tools used.
