### ISSUE TITLE
Hooks added to missing use-package sections don't work

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#5135]
`spacemacs|use-package-add-hook` added hooks to missing `use-package` sections don't work.

For example, if as I user I were to write:

~~~ emacs-lisp
(spacemacs|use-package-add-hook foo
  :post-config
  (setq foo-setting t)
  )
~~~

But the relevant layer uses

~~~ emacs-lisp
(use-package foo
  :init
  (setq foo-setting nil)
  ;; No :config block
  )
~~~

my hook would not run at all.

I don't think this is desirable because it forces the user to worry about the
implementation details.  `:post-config` should still run as if there were an
empty `:config` block.

This is on `develop` branch.

**Comment by TheBB** [comment]
Yep. See:

https://github.com/syl20bnr/spacemacs/issues/3070
https://github.com/jwiegley/use-package/issues/250
