### ISSUE TITLE
Change-Inner for expand-region

### ISSUE THREAD

**Issue by catesandrew** [syl20bnr/spacemacs#5136]
Any thoughts on adding [change-inner](https://github.com/magnars/change-inner.el) to enhance `expand-region`? 

---
## Using `change-inner`

I also came across [`change-inner`](https://github.com/magnars/change-inner.el) package by the `expand-region` author [**magnars**](https://github.com/magnars) (which uses `expand-region` as back-end) to do exactly what the Vim `ci` does (and also *change outer*).

From the package README:

> `change-inner` gives you vim's `ci` command, building on `expand-region`. It is most easily explained by example:

>     function test() {
>       return "semantic kill";
>     }

> With point after the word *semantic*

> `change-inner "` would kill the contents of the string  
> `change-outer "` would kill the entire string  
> `change-inner {` would kill the return-statement  
> `change-outer {` would kill the entire block

**Comment by bmag** [comment]
@catesandrew well, for users of vim or hybrid editing style there's obviously no use for this, since `ci` and `ca` are available.
For users of emacs editing style, I guess it's slightly quicker than `M-m v v ...` (expand-region) followed by `C-w` or `M-w`, so perhaps `change-inner` provides some value there.

**Comment by catesandrew** [comment]
@bmag i'm a big fan of `ci` and `ca` from vim days and this actually extends that to work with regions marked with expand-region. It extends the concept of `ci`, `ca` to work with context aware regions that extend region provides. Its an enhancement. Didn't think of emacs users, good point. But disagree with you that it doesn't provide any value for vi users.

**Comment by StreakyCobra** [comment]
@catesandrew Both `ci` and `ca` are already working in Spacemacs (with vim mode): `ci"`, `ca"`, `ci{`, `ca{`, and much more. Have you tried it? Or does this package do more??

**Comment by catesandrew** [comment]
i do use `ci"`, `ca"`, `ci{`, etc, and have been for years from vim days. this package selects based on regions from expand-region. do you use expand-region and understand the differences it offers vs selecting text via `va`, `vi`, `ca`, `ci` etc, and there lies its benefits. it extends the ability to use our loved keys, `ci`, `ca`, etc with better region selection. i'm playing around with extending the defadvice spacemacs currently offers in the expand-region package. it seems like a good fit there.

**Comment by justbur** [comment]
You can use expand-region and then change the text in the region with c by the way. 

Like this: `SPC v v c`
Which is similar to `viwc` for example

**Comment by syl20bnr** [comment]
@catesandrew do you have some examples to share ?

**Comment by catesandrew** [comment]
nothing i was able to put together was useful enough consider. my use case was when you have nested functions say in js/lisp, `outer(inner())` and wanted to strip `outer. stuff like that. but i wasn't successful enough to get it done. there's probably an easier way that will turn up at some point. i thought change-inner would of been it, and it kind of is, but it keeps asking for additional input. its not as automated as i would of liked. thanks for discussion, i close so i don't waste your guys time. awesome work, i tell people all the time they should just consider putting spacemacs directly into emacs.
