### ISSUE TITLE
Make emacs say that melpa is down - before it's too late.

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#5141]
All issues will be contaminated pretty soon with this  "connection refused" 
IT ALREADY BEGUN ╯°□°）╯︵ ┻━┻ #4138  
We should hotfix Spacemacs to say that "Emacs'es repository is down - please don't write to us"

**Comment by JAremko** [comment]
I better summon the elders  (∩｀-´)⊃━☆ﾟ.*･｡ﾟ @syl20bnr   @StreakyCobra  @TheBB

**Comment by StreakyCobra** [comment]
We are not going to hotfix Spacemacs for a temporary issue :-)

**Comment by carloscheddar** [comment]
I restarted emacs since melpa is down it stops the init and spacemacs doesn't get loaded. I think that we should catch this error instead of stopping execution because it basically breaks spacemacs.

**Comment by syl20bnr** [comment]
We have a big issue here. Unfortunately I cannot look into this before this evening and I don't have my laptop with me. :-(

Can someone post a screenshot of the error and also do a `emacs --debug-init` to get the call stack ?

**Comment by syl20bnr** [comment]
> I better summon the elders (∩｀-´)⊃━☆ﾟ.*･｡ﾟ

:joy:

**Comment by carloscheddar** [comment]
Haha hopefully the elders will be able to help. I found another issue with the `--debug-init` trace https://github.com/syl20bnr/spacemacs/issues/5139

**Comment by TheBB** [comment]
![](http://i.imgur.com/3ErfHEi.png)

    Debugger entered--Lisp error: (file-error "make client process failed" "connection refused" :name "elpa.gnu.org" :buffer #<buffer  *url-http-temp*> :host "elpa.gnu.org" :service 443 :nowait nil)
      make-network-process(:name "elpa.gnu.org" :buffer #<buffer  *url-http-temp*> :host "elpa.gnu.org" :service 443 :nowait nil)
      open-network-stream("elpa.gnu.org" #<buffer  *url-http-temp*> "elpa.gnu.org" 443)
      open-gnutls-stream("elpa.gnu.org" #<buffer  *url-http-temp*> "elpa.gnu.org" 443)
      network-stream-open-tls("elpa.gnu.org" #<buffer  *url-http-temp*> "elpa.gnu.org" 443 (:type tls :nowait t))
      open-network-stream("elpa.gnu.org" #<buffer  *url-http-temp*> "elpa.gnu.org" 443 :type tls :nowait t)
      byte-code("\306\211\n\307>\203$\n\310=\203\311\312\f
    \313\n\314\315\316\317\"&\202Y\n\320=\2034\321\f
    $\202Y\n\322=\203D\323\f
    $\202Y\n\324=\203T\325\f
    $\202Y\326\327\"*\306\207" [coding-system-for-write coding-system-for-read gw-method name buffer host binary (tls ssl native) native plain open-network-stream :type :nowait featurep make-network-process (:nowait t) socks socks-open-network-stream telnet url-open-telnet rlogin url-open-rlogin error "Bad setting of url-gateway-method: %s" service url-gateway-method conn] 11)
      url-open-stream("elpa.gnu.org" #<buffer  *url-http-temp*> "elpa.gnu.org" 443)
      url-http-find-free-connection("elpa.gnu.org" 443)
      url-http([cl-struct-url "https" nil nil "elpa.gnu.org" nil "/packages/" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
      url-https([cl-struct-url "https" nil nil "elpa.gnu.org" nil "/packages/" nil nil t nil t] #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil))
      url-retrieve-internal("https://elpa.gnu.org/packages/" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] (nil) nil nil)
      url-retrieve("https://elpa.gnu.org/packages/" #[128 "\302\303\304p#\210\300\305\240\210\301p\240\207" [(nil) (nil) url-debug retrieval "Synchronous fetching done (%S)" t] 5 "\n\n(fn &rest IGNORED)"] nil nil nil)
      url-retrieve-synchronously("https://elpa.gnu.org/packages/")
      (progn (url-retrieve-synchronously (cdr archive)))
      (unwind-protect (progn (url-retrieve-synchronously (cdr archive))) (cancel-timer -with-timeout-timer-))
      (let* ((-with-timeout-timer- (run-with-timer dotspacemacs-elpa-timeout nil (function (lambda nil (throw (quote timeout) (quote timeout)))))) (with-timeout-timers (cons -with-timeout-timer- with-timeout-timers))) (unwind-protect (progn (url-retrieve-synchronously (cdr archive))) (cancel-timer -with-timeout-timer-)))
      (catch (quote timeout) (let* ((-with-timeout-timer- (run-with-timer dotspacemacs-elpa-timeout nil (function (lambda nil (throw ... ...))))) (with-timeout-timers (cons -with-timeout-timer- with-timeout-timers))) (unwind-protect (progn (url-retrieve-synchronously (cdr archive))) (cancel-timer -with-timeout-timer-))))
      (let ((-with-timeout-value- (catch (quote timeout) (let* ((-with-timeout-timer- (run-with-timer dotspacemacs-elpa-timeout nil ...)) (with-timeout-timers (cons -with-timeout-timer- with-timeout-timers))) (unwind-protect (progn (url-retrieve-synchronously ...)) (cancel-timer -with-timeout-timer-)))))) (if (eq -with-timeout-value- (quote timeout)) (progn (progn (spacemacs-buffer/append (format "\nError while contacting %s repository!" (car archive))) (quote error))) -with-timeout-value-))
      (eq (quote error) (let ((-with-timeout-value- (catch (quote timeout) (let* ((-with-timeout-timer- ...) (with-timeout-timers ...)) (unwind-protect (progn ...) (cancel-timer -with-timeout-timer-)))))) (if (eq -with-timeout-value- (quote timeout)) (progn (progn (spacemacs-buffer/append (format "\nError while contacting %s repository!" (car archive))) (quote error))) -with-timeout-value-)))
      (if (eq (quote error) (let ((-with-timeout-value- (catch (quote timeout) (let* (... ...) (unwind-protect ... ...))))) (if (eq -with-timeout-value- (quote timeout)) (progn (progn (spacemacs-buffer/append (format "\nError while contacting %s repository!" ...)) (quote error))) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents)))
      (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let ((-with-timeout-value- (catch (quote timeout) (let* ... ...)))) (if (eq -with-timeout-value- (quote timeout)) (progn (progn (spacemacs-buffer/append ...) (quote error))) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--)))
      (let ((--dolist-tail-- package-archives) archive) (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let ((-with-timeout-value- (catch ... ...))) (if (eq -with-timeout-value- (quote timeout)) (progn (progn ... ...)) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--))))
      (let ((count (length package-archives)) (i 1)) (let ((--dolist-tail-- package-archives) archive) (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let ((-with-timeout-value- ...)) (if (eq -with-timeout-value- ...) (progn ...) -with-timeout-value-))) nil (let ((package-archives (list archive))) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (package-read-all-archive-contents) (if quiet nil (spacemacs-buffer/append "\n")))
      (if (and configuration-layer--package-archives-refreshed (not force)) nil (setq configuration-layer--package-archives-refreshed t) (let ((count (length package-archives)) (i 1)) (let ((--dolist-tail-- package-archives) archive) (while --dolist-tail-- (setq archive (car --dolist-tail--)) (if quiet nil (spacemacs-buffer/replace-last-line (format "--> refreshing package archive: %s... [%s/%s]" (car archive) i count) t)) (spacemacs//redisplay) (setq i (1+ i)) (if (eq (quote error) (let (...) (if ... ... -with-timeout-value-))) nil (let ((package-archives ...)) (package-refresh-contents))) (setq --dolist-tail-- (cdr --dolist-tail--)))) (package-read-all-archive-contents) (if quiet nil (spacemacs-buffer/append "\n"))))
      configuration-layer/retrieve-package-archives()
      (progn (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" noinst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (let ((--dolist-tail-- noinst-pkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (configuration-layer//install-package (object-assoc pkg-name :name configuration-layer--packages)) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n"))
      (if noinst-pkg-names (progn (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" noinst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (let ((--dolist-tail-- noinst-pkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (configuration-layer//install-package (object-assoc pkg-name :name configuration-layer--packages)) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n")))
      (let* ((noinst-pkg-names (configuration-layer//get-uninstalled-packages (mapcar (quote car) (object-assoc-list :name packages)))) (noinst-count (length noinst-pkg-names)) installed-count) (if noinst-pkg-names (progn (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" noinst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (let ((--dolist-tail-- noinst-pkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (configuration-layer//install-package (object-assoc pkg-name :name configuration-layer--packages)) (spacemacs//redisplay) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n"))))
      configuration-layer//install-packages(([object cfgl-package "2048-game" 2048-game games nil nil elpa nil nil nil nil nil] [object cfgl-package "ac-ispell" ac-ispell auto-completion nil nil elpa nil nil nil nil nil] [object cfgl-package "ace-jump-helm-line" ace-jump-helm-line spacemacs-helm nil nil elpa nil nil nil nil nil] [object cfgl-package "ace-link" ace-link spacemacs-ui nil nil elpa nil nil nil nil nil] [object cfgl-package "ace-window" ace-window spacemacs-ui nil nil elpa nil nil nil nil nil] [object cfgl-package "adaptive-wrap" adaptive-wrap spacemacs-editing-visual nil nil elpa nil nil nil nil nil] [object cfgl-package "aggressive-indent" aggressive-indent spacemacs-editing nil nil elpa nil nil nil nil nil] [object cfgl-package "alchemist" alchemist elixir nil nil elpa nil nil nil nil nil] [object cfgl-package "anaconda-mode" anaconda-mode python nil nil elpa nil nil nil nil nil] [object cfgl-package "arduino-mode" arduino-mode extra-langs nil nil elpa nil nil nil nil nil] [object cfgl-package "auctex" auctex latex nil (bb-latex) elpa nil nil nil nil nil] [object cfgl-package "auctex-latexmk" auctex-latexmk latex nil nil elpa nil nil nil nil nil] [object cfgl-package "auto-compile" auto-compile emacs-lisp nil nil elpa nil nil nil nil nil] [object cfgl-package "auto-complete" auto-complete auto-completion nil nil elpa nil nil nil nil nil] [object cfgl-package "auto-dictionary" auto-dictionary spell-checking nil nil elpa nil nil nil nil nil] [object cfgl-package "auto-highlight-symbol" auto-highlight-symbol spacemacs-editing-visual nil nil elpa nil nil nil nil nil] [object cfgl-package "auto-yasnippet" auto-yasnippet auto-completion nil nil elpa nil nil nil nil nil] [object cfgl-package "avy" avy spacemacs-editing nil nil elpa nil nil nil nil nil] [object cfgl-package "bind-key" bind-key spacemacs-base nil nil elpa nil nil nil nil nil] [object cfgl-package "bind-map" bind-map spacemacs-base nil nil elpa pre nil nil nil nil] [object cfgl-package "bookmark" bookmark spacemacs-base nil nil elpa nil nil nil nil nil] [object cfgl-package "bracketed-paste" bracketed-paste spacemacs-editing nil nil elpa nil nil nil nil nil] [object cfgl-package "buffer-move" buffer-move spacemacs-ui nil nil elpa nil nil nil nil nil] [object cfgl-package "bundler" bundler ruby nil nil elpa nil nil nil nil nil] [object cfgl-package "cc-mode" cc-mode c-c++ nil nil elpa nil nil nil nil nil] [object cfgl-package "chruby" chruby ruby nil nil elpa nil nil nil nil nil] [object cfgl-package "cider" cider clojure nil nil elpa nil nil nil nil nil] [object cfgl-package "cider-eval-sexp-fu" cider-eval-sexp-fu clojure nil nil elpa nil nil nil nil nil] [object cfgl-package "clang-format" clang-format c-c++ nil nil elpa nil nil nil nil nil] [object cfgl-package "clean-aindent-mode" clean-aindent-mode spacemacs-editing nil nil elpa nil nil nil nil nil] [object cfgl-package "clojure-mode" clojure-mode clojure nil nil elpa nil nil nil nil nil] [object cfgl-package "cmake-mode" cmake-mode c-c++ nil nil elpa nil nil nil nil nil] [object cfgl-package "cmm-mode" cmm-mode haskell nil nil elpa nil nil nil nil nil] [object cfgl-package "coffee-mode" coffee-mode javascript nil nil elpa nil nil nil nil nil] [object cfgl-package "command-log-mode" command-log-mode command-log nil nil (recipe :fetcher github :repo "bmag/command-log-mode" :branch "color") nil nil nil nil nil] [object cfgl-package "company" company auto-completion (shell) (yaml shell-scripts rust ruby python org markdown latex javascript html haskell erc emacs-lisp elixir csharp clojure c-c++) elpa nil nil nil nil nil] [object cfgl-package "company-anaconda" company-anaconda python nil nil elpa nil nil nil nil nil] [object cfgl-package "company-auctex" company-auctex latex nil nil elpa nil nil nil nil nil] [object cfgl-package "company-c-headers" company-c-headers c-c++ nil nil elpa nil nil nil nil nil] [object cfgl-package "company-cabal" company-cabal haskell nil nil elpa nil nil nil nil nil] [object cfgl-package "company-emoji" company-emoji emoji nil (org markdown erc) elpa nil nil nil nil nil] [object cfgl-package "company-ghc" company-ghc haskell nil nil elpa nil nil nil nil nil] [object cfgl-package "company-quickhelp" company-quickhelp auto-completion nil nil elpa nil nil nil nil nil] [object cfgl-package "company-shell" company-shell shell-scripts nil nil elpa nil nil nil nil nil] [object cfgl-package "company-statistics" company-statistics auto-completion nil nil elpa nil nil nil nil nil] [object cfgl-package "company-tern" company-tern javascript nil nil elpa nil nil nil nil nil] [object cfgl-package "company-web" company-web html nil nil elpa nil nil nil nil nil] [object cfgl-package "css-mode" css-mode html nil nil elpa nil nil nil nil nil] [object cfgl-package "cython-mode" cython-mode python nil nil elpa nil nil nil nil nil] [object cfgl-package "dactyl-mode" dactyl-mode vimscript nil nil elpa nil nil nil nil nil] ...))
      configuration-layer/sync()
      (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %d or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
      eval-buffer(#<buffer  *load*> nil "/home/eivindf/.emacs.d/init.el" nil t)  ; Reading at buffer position 1076
      load-with-code-conversion("/home/eivindf/.emacs.d/init.el" "/home/eivindf/.emacs.d/init.el" t t)
      load("/home/eivindf/.emacs.d/init" t t)
      #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
      command-line()
      normal-top-level()

**Comment by syl20bnr** [comment]
Thank you for the info.

**Comment by d12frosted** [comment]
> > I better summon the elders (∩｀-´)⊃━☆ﾟ.*･｡ﾟ

> :joy:

yeah, @JAremko is the master of smileys

**Comment by JAremko** [comment]
ELPA IS BACK!
============

# ᕕ( ᐛ )ᕗ

**Comment by d12frosted** [comment]
> ᕕ( ᐛ )ᕗ

This is my favorite

**Comment by syl20bnr** [comment]
Thank you @TheBB for the callstack, it should be fixed in 0.105.11. (∩｀-´)⊃━☆ﾟ.*･｡ﾟ

**Comment by TheBB** [comment]
Good job :+1:

**Comment by robbyoconnor** [comment]
> ᕕ( ᐛ )ᕗ

Also my favorite. This is one of my favorite issues in spacemacs -- not the bug but the quality content with all the comments. 

# ᕕ( ᐛ )ᕗ ᕕ( ᐛ )ᕗ ᕕ( ᐛ )ᕗᕕ( ᐛ )ᕗ
