### ISSUE TITLE
anaconda-eldoc-mode is highly disruptive

### ISSUE THREAD

**Issue by hynek** [syl20bnr/spacemacs#5142]
Hi

I understand that https://github.com/syl20bnr/spacemacs/commit/804f09098f94ff4a36b023e21a8157a5a98f64aa was well intentioned but it is highly disruptive when writing code.  Just by scrolling through a file, windows keep popping up, sometimes even my cursor jumps around.  Of course everything gets slower too.  And who wants to see the documentation for `dict()` or `ValueError`?

So could you *please* make this configurable (and ideally off by default but I don’t really care as long as I can switch it off somehow.  but it doesn’t seem like a good first impression…)?  I’m fresh back from vim so I’m not sure how to suppress this myself and `anaconda-eldoc-mode` can’t even be called interactively…

In general it would be nice if the changelog could mention how to switch something off, that has been switched on in a release…

**Comment by StreakyCobra** [comment]
To disable the part you linked, add this to `user-config` in your `.spacemacs`:

```elisp
(remove-hook 'python-mode-hook 'spacemacs//init-eldoc-python-mode)
```

**Comment by hynek** [comment]
Oh god thank you, I can work again! :)

**Comment by CestDiego** [comment]
I'm in with the part of the changelog specifying how to revert something that was done (if possible)

**Comment by syl20bnr** [comment]
> In general it would be nice if the changelog could mention how to switch something off, that has been switched on in a release…

Thanks I'll try to provide such info more often.

**Comment by fbergroth** [comment]
What windows are popping up? eldoc should just display information in the echoarea.

**Comment by hynek** [comment]
To be clear, it’s windows in Emacs parlance, aka splits in vim speak.

Before eldoc indeed just showed something in the echo area.  But with the new release, windows popped up with long form documentation for the symbol under the cursor.

**Comment by mattharrison** [comment]
I just updated to 0.105.10 and couldn't launch a python repl (``C-c C-c``) until I used @StreakyCobra code. Regression, or am I missing something?

**Comment by syl20bnr** [comment]
@mattharrison Did you update your packages ?

**Comment by StreakyCobra** [comment]
@mattharrison I just tried `C-c C-c` from a Python file. The REPL is started but its windows is not shown. I don't know from where it come from, but it seems my code snippet doesn't prevent this behavior :-(

**Comment by mattharrison** [comment]
Yes, it appears that I neglected to update my packages. Pardon my erroneous
report, REPL is now launching.

**Comment by TheBB** [comment]
I can't reproduce any such windows for the life of me…

**Comment by StreakyCobra** [comment]
I still have the problem with `C-c C-c` (window not showing?). `SPC a '` and `,'` work though.

**Comment by syl20bnr** [comment]
The issue with the REPL seems to be another issue, open a new issue for it.

**Comment by hynek** [comment]
Interestingly the windows stopped popping up after a few pkg updates and I’m back to having just the info are help.  Don't know what exactly caused it but it's gone so I’m closing this.

**Comment by jjlee** [comment]
To reproduce this:

* Ensure that python (python 2) module `setuptools` is not importable (e.g. on ubuntu `apt get remove python-setuptools`)
* `find-file` some .py file
* Move point around in the buffer a bit

Expect: no new window appears

Got: popup window opens showing this: 
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named setuptools.command
```

**Comment by jjlee** [comment]
So, on ubuntu (I'm on 18.04) for example, `apt get install python-setuptools` will stop this happening
