### ISSUE TITLE
Truncate line configuration don't work

### ISSUE THREAD

**Issue by whcn** [syl20bnr/spacemacs#5145]
#### Description
Truncate line configuration don't work

#### Reproduction guide
- Open terminal
- run emacs + filename

*Observed behaviour:*
truncate line configuration don't work

*Expected behaviour:*
truncate line configuration work, below is my configure :
/(add-hook 'org-mode-hook (lambda () (setq truncate-lines nil)))/

#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.9
- Spacemacs branch: develop
- Distribution: spacemacs
- Layers:
     emacs-lisp
     (chinese :variables
              chinese-enable-fcitx t
              chinese-enable-avy-pinyin t
              chinese-enable-youdao-dict t)

**Comment by StreakyCobra** [comment]
Can you please update issue to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? It would help us to help you :-)

**Comment by sooheon** [comment]
Your configuration should be `(add-hook 'text-mode-hook 'spacemacs/toggle-truncate-lines-off)`. Or if you don't want to use a spacemacs function, `(add-hook 'text-mode-hook (lambda () (toggle-truncate-lines 1)))`. Basically, you don't want to run `setq` on the hook, but rather the interactive function.

**Comment by whcn** [comment]
Thanks, it works

**Comment by sooheon** [comment]
You can go ahead and close the issue then :)
