### ISSUE TITLE
Dead link "Contribute" at homepage

### ISSUE THREAD

**Issue by olejorgenb** [syl20bnr/spacemacs#5148]
http://spacemacs.org/doc/CONTRIBUTE.html yields 404 (link at frontpage spacemacs.org)

Semirelated: I've come across dead links when browsing the documentation from within github too.

**Comment by xfq** [comment]
See syl20bnr/spacemacs.org#6 and #4399.

**Comment by StreakyCobra** [comment]
For your information: All links are broken on Github #4399, and for this precise case we have a problem with the website generation. All documentation files are supposed to be in the `doc/` folder, but `CONTRIBUTING.org` has to be at the root for Github to recognize it. This will probably be treated at the same time as #4399.

**Comment by TheBB** [comment]
Closing as duplicate.
