### ISSUE TITLE
paradox's github oauth facility breaks spacemacs by creating a .emacs file.

### ISSUE THREAD

**Issue by coventry** [syl20bnr/spacemacs#5154]
The other day I tried to set up paradox's github oauth facility.  Doing so resulted in the creation of the following .emacs file:

```elisp
;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(setq paradox-github-token "5ea328989883ba6ce6059bd762c0ceb07e9aad72")

(load-file "~/.emacs.d/init.el")
(put 'downcase-region 'disabled nil)
(put 'erase-buffer 'disabled nil)
```

The presence of this file broke spacemacs completely.  Even blowing away .emacs.d and checking out a fresh copy of spacemacs would lead to an error, because melpa was no longer being added to the list of package archives.  Moving the .emacs file out of the way caused spacemacs to start normally again.

**Comment by coventry** [comment]
While attempting to provide repro instructions as requested in the template generated by report-issue, I found that paradox no longer does this... if it ever did, but I don't recall putting the access token in ~/.emacs myself, and it would be strange if I had.

At any rate, the following steps expose a fragility in spacemacs.  Apparently whatever it's doing to get melpa on the package list doesn't work if someone gets there first, and the error message it reports is confusing.

- Copy the above .emacs file to ~/.emacs,
- Blow away ~/.emacs.d and clone in a new copy of spacemacs,
- Start emacs with --debug-init, and get the following confusing stack trace:

```
Debugger entered--Lisp error: (error "Package `spacemacs-theme' is not available for installation")
  signal(error ("Package `spacemacs-theme' is not available for installation"))
  error("Package `%s' is not available for installation" "spacemacs-theme")
  package-install(spacemacs-theme)
  (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg))$
  (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs$
  (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-$
  (let ((warning-minimum-level :error)) (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-dire$
  spacemacs/load-or-install-package(spacemacs-theme)
  (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (spacemacs/load-or-install-package pkg))) (if (or (eq (quote moe-light) theme) (eq (quote$
  (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg (spacemacs//get-theme-package theme)) (pkg-dir (spacemacs/load-or-install-package pk$
  (if (or (memq theme (custom-available-themes)) (eq (quote default) theme)) nil (cond ((assq theme spacemacs-theme-name-to-package) (let* ((pkg (spac$
  spacemacs/load-theme(spacemacs-dark)
  (let ((default-theme (car dotspacemacs-themes))) (spacemacs/load-theme default-theme) (setq configuration-layer--protected-packages (append (delq ni$
  spacemacs/init()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs$
  eval-buffer(#<buffer  *load*-497517> nil "/home/coventry/.emacs.d/init.el" nil t)  ; Reading at buffer position 1076
  load-with-code-conversion("/home/coventry/.emacs.d/init.el" "/home/coventry/.emacs.d/init.el" nil nil)
  load("/home/coventry/.emacs.d/init.el" nil nil t)
  load-file("~/.emacs.d/init.el")
  eval-buffer(#<buffer  *load*> nil "/home/coventry/.emacs" nil t)  ; Reading at buffer position 380
  load-with-code-conversion("/home/coventry/.emacs" "/home/coventry/.emacs" t t)
  load("~/.emacs" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320$
  command-line()
  normal-top-level()
```

**Comment by StreakyCobra** [comment]
From my point of view this is not a Spacemacs bug, in the sense that the official way of starting Spacemacs is to use the `.emacs.d/init.el` as entry-point. If people have an `~/.emacs` file with extra configuration that is breaking Spacemacs, it's not something that we can anticipate.

Spacemacs offers a `.spacemacs` file to configure emacs in a compatible ways, so for me this issue is a wontfix.

**Comment by coventry** [comment]
It doesn't matter whether you call it a bug in spacemacs, the important thing is that automation is creating a .emacs file and that breaks spacemacs in a mystifying and easily prevented way.  At the least, spacemacs could check for a .emacs file and error out if it finds one, unless the variable dotspacemacs-yes-i-have-dotemacs-yes-i-know-what-i-am-doing is set to true or something like that.

**Comment by syl20bnr** [comment]
Spacemacs cannot check this, Emacs will _completely_ bypass if there is a `.emacs`. if the content of `.emacs` redirect to `Emacs.d` then it is unconventional and so unsupported by Spacemacs. This issue must be fixed at the paradox level which uses an unconventional trick.

**Comment by TheBB** [comment]
The ayes have it then. Sorry. Please report this to paradox, as we all agree this is kind of an insane implementaiton.
