### ISSUE TITLE
Backspace does the wrong thing in replace state in tuareg-mode

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#5158]
#### Description

In `tuareg-mode`, <kbd><backspace></kbd> is bound to `sp-backward-delete-char` in replace state.
#### Reproduction guide
- Start Emacs
- Ensure that the `ocaml` layer is enabled
- Restart Emacs if necessary
- Open an OCaml file (or enter `tuareg-mode` some other way
- Type some text
- Enter `evil-replace-state` (<kbd>R</kbd>)
- Press <kbd><backspace></kbd>.

_Observed behaviour:_
Character before point is deleted.

_Expected behaviour:_
Point should move without affecting character (or deleting the overwriting character to reveal the original).
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.10
- Spacemacs branch: master (rev. 793b326)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp markdown
                 (org :variables org-enable-github-support t)
                 spell-checking
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 version-control markdown emacs-lisp
                 (latex :variables latex-enable-auto-fill nil latex-build-command "Rubber")
                 (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-ghc-mod-support nil)
                 (git :variables git-magit-status-fullscreen t git-gutter-use-fringe t)
                 github
                 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
                 ov ocaml hide-region unicode-fonts finance command-log speed-reading liquid-types)
```
#### Backtrace

```

```

**Comment by rgrinberg** [comment]
I confirm that this is a bug in develop as well.

**Comment by rgrinberg** [comment]
And it goes away if you get rid of this line:

https://github.com/ocaml/tuareg/blob/1e68a0addca6165b8f1cadfcd15c0b7ef5184e9a/tuareg-light.el#L2254
