### ISSUE TITLE
What are the Unicode characters used to create the diagonal dividers in the modeline?

### ISSUE THREAD

**Issue by bucaran** [syl20bnr/spacemacs#5162]
Hi. I searched several files and looked in a lot of different places, but I could not find where the Unicode characters used to create the "separators" shown in the snapshot below are defined:

![zzz](https://cloud.githubusercontent.com/assets/8317250/13195991/e89aeb5e-d804-11e5-8891-9ab0063226fa.png)

I was able to figure out the powerline-like angle separators Unicode points,

* \ue0b0 Right-facing filled angle
* \ue0b1 Right-facing empty angle
* \ue0b2 Left-facing filled angle
* \ue0b3 Left-facing empty angle

but I can't figure out the characters used to create the other parts of the modeline.

**Comment by TheBB** [comment]
Those aren't unicode characters, but images. They're defined in the powerline package: https://github.com/milkypostman/powerline/blob/master/powerline-separators.el

**Comment by bucaran** [comment]
That explains it. @TheBB And thanks a lot for saving me another hour. :smile:
