### ISSUE TITLE
Bug during instalation

### ISSUE THREAD

**Issue by Drup** [syl20bnr/spacemacs#5163]
I wanted to try spacemacs using http://spacemacs.org/doc/FAQ.html#orgheadline32 and I got an error during install, now I only get "error: Incompatible place needs recompilation: eieio-oref"

I also got the message "cond: Symbol's function definition is void: projectile-mode"

After that, spacemacs is non functional, so I couldn't comply with the bug report indications. The issue is reproducible on develop.

**Comment by StreakyCobra** [comment]
What's your Emacs version?

**Comment by Drup** [comment]
```
% emacs --version
GNU Emacs 24.5.1
```

**Comment by StreakyCobra** [comment]
Can you try to delete the whole `.emacs.d` folder inside the spacemacs home, and restart emacs with the `--insecure` flag?

**Comment by Drup** [comment]
You mean restart the install with fresh spacemacs repository with `emacs --insecure` ? It doesn't change anything.

**Comment by StreakyCobra** [comment]
Yes, but try removing the `.emacs.d/elpa` directory before restarting with `emacs --insecure`

**Comment by marc1006** [comment]
I had the same issue and I resolved it with deleting the compiled files related to eieio.
```
$ cd /usr/share/emacs/site-lisp/cedet/eieio
$ find . -iname '*.elc' -delete 
```

**Comment by r-darwish** [comment]
I also encountered this issue when trying to set up Spacemacs inside a Docker container.

@StreakyCobra - This [Dockerfile](https://gist.github.com/r-darwish/4a3afe1fdde32803a3bf) reproduces the problem. You can build the image with `docker build -t spacemacs .` and then run `docker run --rm -it spacemacs /bin/bash`. You can then launch emacs and choose the default options and the installation will fail at the end. Running with `--insecure` doesn't seem to help either.

**Comment by StreakyCobra** [comment]
I think the docker bug is different, probably related to this: https://github.com/syl20bnr/spacemacs/issues/3652#issuecomment-180946962

Using your `Dockerfile` and reproducing your steps (taking care of applying the solution shown in the above linked comment), I can't reproduce it. I have another bug regarding `define-fringe-bitmap` that is linked to the fact that `X` is probably not compiled in this version (discussed here: https://github.com/syl20bnr/spacemacs/pull/5497)

@Drup Can you try to set the `SHELL` variable also?
