### ISSUE TITLE
Org layer overrides user configuration set in org-customize

### ISSUE THREAD

**Issue by opie4624** [syl20bnr/spacemacs#5170]
Fixed in #5168

**Comment by opie4624** [comment]
This actually happens in other layers besides Org, it just hasn't affected me. This is why the fix proposed in #5168 includes a portion of code in `core-spacemacs.el` and a portion in `layers/org/packages.el`.

**Comment by syl20bnr** [comment]
Can you provide repro steps ?

Also can you try to put your customized settings inside a `with-eval-after-load` or a `use-package` post init hook ?

**Comment by opie4624** [comment]
Sorry for the super late response. :neutral_face: 

Reproducing the issue:

1. `M-x customize-variable org-default-notes-file`
2. Set any file you like; mine is set to `Inbox.org`.
3. Restart Emacs
4. `M-m a o c` (Org Capture) file's task into `notes.org`

Emacs moves customize'd settings to a known place in the .emacs file each time, so moving it doesn't seem to help.

**Comment by opie4624** [comment]
@syl20bnr My primary concern over blindly stepping on customized variables is that it effectively breaks documentation for the packages themselves. For example, the chapter on using and setting up Org Capture mode starts out encouraging users to use `M-x customize-variable` to configure the variables that Capture uses. Many of these are also set using `setq` in the layer files which execute after customize variables are setup.

Should this be a broader issue to establish a variable setting method used in layers other than `setq` that would respect any existing customized variables where appropriate?

**Comment by borgnix** [comment]
Moving auto-generated custom variables into `dotspacemacs/user-config` fixes this problem.

**Comment by opie4624** [comment]
Correct. This fixes the problem, but breaks any usage of customize.

**Comment by syl20bnr** [comment]
Should be fixed in develop with commit https://github.com/syl20bnr/spacemacs/commit/e699f18

**Comment by ksjogo** [comment]
This change broke some '--batch' '--eval' Emacs calls relying on customized values (e.g. 'paradox-github-token' for emacs upgrades via the command line). Is the function not called when in script mode?

 Also the application of unsafe dir locals and their writing seems to cause issue, but I need to further pin that down.

**Comment by ksjogo** [comment]
Any customization I try with the gui at the moment will result in a "selected deleted buffer".

**Comment by et2010** [comment]
> This change broke some '--batch' '--eval' Emacs calls relying on customized values (e.g. 'paradox-github-token' for emacs upgrades via the command line). 

> Any customization I try with the gui at the moment will result in a "selected deleted buffer".

I got the same issue: #7963
