### ISSUE TITLE
erc double login

### ISSUE THREAD

**Issue by meditans** [syl20bnr/spacemacs#5173]
#### Description
When I invoke the `erc` command, I get to insert the server, port, nickname (all these are cached) and my password. Then, I get this other message: `NickServ password for meditans on freenode (RET to cancel): `. I just press RET, and I get logged in anyway (because I inserted my password beforehand). I'd like to avoid that useless message?

#### Reproduction guide
- Start Emacs
- `M-x erc`
- Insert the credentials for your irc account
- After that, see the useless message

*Observed behaviour:*
The useless message: `NickServ password for meditans on freenode (RET to cancel): ` pops up, blocking the connection to the channels.

*Expected behaviour:*
Emacs connects directly to the channel.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 6689699)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git github version-control latex markdown spell-checking syntax-checking erc dash extra-langs elm
            (org :variables org-enable-github-support t)
            (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-scope 'visible)
            (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t)
            (haskell :variables haskell-enable-hindent-style "gibiansky" haskell-process-type 'stack-ghci haskell-tags-on-save t haskell-process-use-presentation-mode t haskell-process-suggest-haskell-docs-imports nil)
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence "jk" auto-completion-enable-snippets-in-popup t))
```

**Comment by CestDiego** [comment]
I can't reproduce this. What do you mean by 

> I get to insert the server, port, nickname (all these are cached)

Do you have extra config ?

**Comment by meditans** [comment]
Hi, all the configuration I have for `erc` is:

    (setq erc-hide-list '("JOIN" "KICK" "NICK" "PART" "QUIT" "MODE"))
    (setq erc-nick "meditans")
    (setq erc-autojoin-channels-alist '(("freenode.net" "#haskell")))

I mean that in the minibuffer, it prompts for server, port, nickname and password. Don't you have the same prompt?

**Comment by CestDiego** [comment]
I have all the prompts, but not the double thing.

On Sun, Feb 21, 2016 at 2:33 PM Carlo Nucera <notifications@github.com>
wrote:

> Hi, all the configuration I have for erc is:
>
> (setq erc-hide-list '("JOIN" "KICK" "NICK" "PART" "QUIT" "MODE"))
> (setq erc-nick "meditans")
> (setq erc-autojoin-channels-alist '(("freenode.net" "#haskell")))
>
> I mean that in the minibuffer, it prompts for server, port, nickname and
> password. Don't you have the same prompt?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/5173#issuecomment-186895542>
> .
>
-- 
Diego Berrocal
http://cestdiego.github.io

**Comment by Andre0991** [comment]
You can use `(setq erc-prompt-for-nickserv-password nil)`.

**Comment by meditans** [comment]
Thanks guys, @Andre0991 's last suggestion solved the problem

**Comment by a-schaefers** [comment]
THANKYOU @Andre0991

Would it be hard / why is this not default for people using something like .authinfo or .authinfo.gpg?
