### ISSUE TITLE
mark ring transient state

### ISSUE THREAD

**Issue by catesandrew** [syl20bnr/spacemacs#5175]
I have noticed a lot of transient states with spacemacs. A lot of them have similar keybindings to go back and forth through listings or time (as in git time machine). `n` for next, `N` for backwards, `p`, `C-n`, `C-p, etc. Is there any that deals with marks and the `pop-to-mark-command`? I didn't see any is why I'm asking or what is the considered best practice for navigating through a mark-ring?

**Comment by bmag** [comment]
For Helm users, `SPC r m` is bound to `helm-all-mark-rings`. You can use it to navigate both the local mark ring (`pop-to-mark-command`) and the global mark ring (`pop-global-mark`). I don't know of an Ivy equivalent.

There is also `evil-jumper` (now part of Evil), which binds `C-o` for jumping backward and `C-i` for jumping forward. However it uses its own mark list, not the local or global mark rings.

**Comment by catesandrew** [comment]
thanks bmag, closing issue now.
