### ISSUE TITLE
Spacemacs often doesn't respond for about 2-3 minutes.

### ISSUE THREAD

**Issue by jinglunchn** [syl20bnr/spacemacs#5176]
When I open spacemacs ,it often   no response  about  2-3 minutes，Only after normal .What should I do?    
![image](http://img.vim-cn.com/3e/208d0caf8484491d93390f202988d072c53070.jpg )

**Comment by StreakyCobra** [comment]
You probably have this problem: https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-is-spacemacs-hanging-on-startup

**Comment by StreakyCobra** [comment]
I'm changing the title as it's not related to `evil-jumper` :-)

**Comment by jinglunchn** [comment]
Thank you.
