### ISSUE TITLE
Python REPL conflicts with PYENV changes.

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#5178]
#### Description
Sending things to Python REPL resets the pyenv version

#### Reproduction guide
- Start Emacs
- Open a python file
- Have at least two python versions with pyenv.
- There should be a recognized default python version in themodeline,
- Change the python version with `, v s` 
- Do `, s B` in your python buffer

*Observed behaviour:*

- See how the python version in the modeline and therefore the path that you are asked for in the repl thing changes and be sad

*Expected behaviour:*
Emacs should just take the python version your buffer is in to suggest a repl
interpreter. what is this nonsense

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: add-helm-navigation-keys (rev. 74ba3d1)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(appearance org-cestdiego presentations soundcloud twitter utils gnus
            (elfeed :variables elfeed-enable-web-interface t rmh-elfeed-org-files
                    (list "~/Dropbox/Org-Notes/elfeed.org"))
            dash version-control
            (git :variables git-magit-status-fullscreen t)
            github prodigy
            (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers nil)
            chrome
            (erc :variables erc-enable-sasl-auth t)
            (rcirc :variables rcirc-default-nick "cestdiego" rcirc-default-user-name "cestdiego" rcirc-default-full-name "Diego Berrocal" rcirc-enable-znc-support t)
            restclient
            (org :variables org-mapping-style 'worf)
            emoji osx
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets" auto-completion-return-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence "jk")
            spell-checking syntax-checking
            (shell :variables shell-protect-eshell-prompt t shell-default-shell 'ansi-term shell-pop-autocd-to-working-dir nil shell-default-term-shell "zsh")
            eyebrowse clojure emacs-lisp scheme ansible markdown html latex lua c-c   python ipython-notebook sql haskell javascript react ruby extra-langs ranger selectric search-engine xkcd games spotify Monfoku vagrant)
```

**Comment by cpaulik** [comment]
I can not reproduce that. The thing that I observed was that if e.g. ipython is not installed in your pyenv versions then it will suggest the system ipython instead of the shim.

**Comment by CestDiego** [comment]
Oh wait... I don't have iPhone installed..... That might be it.

On Mon, Feb 22, 2016, 3:39 PM Christoph Paulik <notifications@github.com>
wrote:

> I can not reproduce that. The thing that I observed was that if e.g.
> ipython is not installed in your pyenv versions then it will suggest the
> system ipython instead of the shim.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/5178#issuecomment-187372990>
> .
>
-- 
Diego Berrocal
http://cestdiego.github.io
