### ISSUE TITLE
Smartparens not inserting closing delimiter on some filetypes

### ISSUE THREAD

**Issue by exitface** [syl20bnr/spacemacs#518]
Not sure if this is the intended behavior, but it's not what I would expect.

In certain filetypes and certain cases smartparens won't insert the closing delimeter. On a default install after cloning, two known instances for me are:
CSS - does not insert closing brace
Ruby - does not insert closing `end` after the `def` keyword, however it *does* insert it after the `class`, `module` and `do` keywords.

If I add the following to my .spacemacs then smartparens will start closing CSS braces, but it still does not close Ruby `def meth; end` blocks
```lisp
(defun dotspacemacs/config ()
  "This is were you can ultimately override default Spacemacs configuration.
This function is called at the very end of Spacemacs initialization."
   (progn
    (require 'smartparens-config)
    (smartparens-global-mode 1)
))
```
(Unrelated: Spacemacs is amazing with an ergodox.)

**Comment by exitface** [comment]
I've narrowed it down, at least for Ruby, to failing on `def` and `if` - all other keyword delimiters work as expected. I thought Yasnippet might be the culprit, but even when disabled the issue persisted. In trying to diagnose the issue I added a duplicate of the smartparens definition of `def` but swapping `foo` for `def`. This correctly inserted the closing `end` delimiter after typing `foo`. I even grepped the repo for instances of `def` but nothing jumps out at as a potential culprit.

**Comment by syl20bnr** [comment]
This is weird, I'll give it a look when I do a stabilization release.

**Comment by env0der** [comment]
```evil-escape``` is causing this - when ```f``` is pressed in the insert mode, the ```smartparens``` hooks (e.g ```sp--post-self-insert-hook-handler```) are not executed.

As a temporary workaround you can just: ```dotspacemacs-excluded-packages '(evil-escape)```

**Comment by syl20bnr** [comment]
@env0der Well spotted ! :+1: 
I'll see what I can do.

**Comment by jupl** [comment]
Had to work on some CSS today and I can confirm I have to turn on smartparens for CSS files manually or with a hook.

**Comment by TheBB** [comment]
This seems to be fixed.
