### ISSUE TITLE
hydra taking over 0 (zero) binding

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#5182]
#### Description

hydra takes over `0` (zero) binding, which should be used by evil for going to the beginning of the line.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: personal (rev. 8bdc80b)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults spell-checking syntax-checking semantic typography
 (chrome :variables edit-server-new-frame nil)
 elfeed finance gtags ibuffer mu4e org
 (shell :variables shell-default-shell 'shell shell-default-term-shell "/usr/bin/zsh" shell-default-height 50)
 spacemacs-layouts version-control git c-c   emacs-lisp go html javascript latex lua markdown python ruby shell-scripts sql yaml mir-bbdb mir-magit-annex mir-pass mir-remind-to-diary mir-rc mir-rc-org mir-rc-mail)
```

**Comment by StreakyCobra** [comment]
Probably related: https://github.com/syl20bnr/spacemacs/issues/4930

**Comment by TheBB** [comment]
Closing this since it's duplicate and also that was just fixed.
