### ISSUE TITLE
automatic-symbol-highlight conflict with vim's /

### ISSUE THREAD

**Issue by maplewizard** [syl20bnr/spacemacs#5183]
automatic-symbol-highlight use `/` to goto the next hight symbol while vim use / to highlight symbol. How can I stop vim's operation?

**Comment by maplewizard** [comment]
@StreakyCobra @TheBB @syl20bnr Can any one please tell me how to solve this?

**Comment by TheBB** [comment]
Can you explain precisely what you are doing, what happens and what you expect to happen instead?

**Comment by StreakyCobra** [comment]
@maplewizard The best is to use `SPC h I` (capital `i`) from within spacemacs to get the template. It will open in a new issue, but just copy the template, complete it, and replace this issues description with it :-) Thx

**Comment by maplewizard** [comment]
@TheBB When I move cursor on a word, it highlighted. When I pressed `/` in vim mode, it open vim's search, but the doc said that when the word is highlighted, `#` goes to previous same word and `/` goto the next.

**Comment by TheBB** [comment]
Which doc says that?

**Comment by TheBB** [comment]
I would expect `*` and `#` to work and it seems they do.

**Comment by maplewizard** [comment]
@TheBB  https://github.com/syl20bnr/spacemacs/blob/master/doc/Highlight%20current%20symbol 
The key said in this docs, please updated it. Thanks.

**Comment by StreakyCobra** [comment]
Link corrected: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#highlight-current-symbol

**Comment by TheBB** [comment]
Yep, looks like a documentation bug.

**Comment by d12frosted** [comment]
Fixed on master.
