### ISSUE TITLE
`M-1` for window switch no longer works in some buffers

### ISSUE THREAD

**Issue by lislon** [syl20bnr/spacemacs#5185]
#### Description
The `M-1`, `M-2`, ... not working in some buffer, i.e. `*help*`. 

#### Reproduction guide
- Start Emacs
- Open help buffer `C-h v RET`
- Press `M-1`

*Observed behaviour:*
M-1 is undefined

*Expected behaviour:*
Move focus to other window just like `SPC 1` works

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: develop (rev. fd93264)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion better-defaults emacs-lisp common-lisp chrome html lua shell-scripts git github playground colors java javascript python gnus semantic erc emoji xkcd org my-org syntax-checking version-control csharp spell-checking gtags)
```

**Comment by liaowang11** [comment]
I have the same issue. And switching to `Emacs State` with <kbd>Ctrl</kbd> + <kbd>z</kbd>, it works again.

**Comment by liaowang11** [comment]
Tracked a little down, and I found that this is relevant to this commit: 
https://github.com/syl20bnr/spacemacs/commit/a68cc582534aada5892535d6c57d6871d8f10b66#diff-7029ffb75eb55c012543d9cc2099a688R251
which maps `Esc` to `quit-window`. I don't know enough about Emacs, but maybe `M-1` have something todo with `Esc + ...` ?
