### ISSUE TITLE
German Keyboard on OSX: Symbols behind ⌥ - key are unreachable

### ISSUE THREAD

**Issue by marcopaga** [syl20bnr/spacemacs#5188]
#### Description
I want to enter '[' or ' ]' in OSX with a german keyboard. ⌥5 / ⌥6 doesn’t work. This will switch the window due to the `windows-numbering` package.

#### Reproduction guide
- Start Emacs
- Enter ⌥5 with a german keyboard

*Observed behaviour:*
- Will try to switch to window 5

*Expected behaviour:*
- Expected is [

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by marcopaga** [comment]
When deactivating the window-numbering package it doesn't work, too.

E.g. This config doesn't work: https://gist.github.com/marcopaga/c6b8f99f825d577c169a

**Comment by sooheon** [comment]
I think your problem is that the `osx-use-option-as-meta` doesn't work as intended. With that var set as nil, the value of `mac-option-modifier` is still `meta`. Try setting that explicitly to `nil`. You can set left and right option modifiers separately, so one side does the system option key, and the other side sends meta.

**Comment by tko** [comment]
FWIW for me `mac-option-modifier` has default value of `(:function alt :mouse alt)` and I can type special characters just fine (Finnish keyboard layout.) `window-numbering` also seems to work though I get to use `ESC` since I don't have meta.

Maybe the default value depends on which emacs build one uses? I have emacs-24.5-z-mac-5.15 from the emacs-mac brew cask.

**Comment by d12frosted** [comment]
I also relay on `OPTION-` symbols, so I have set in `dotspacemacs/user-config` function:

```
(if (spacemacs/system-is-mac)
      (setq mac-command-modifier 'meta
            mac-option-modifier  'none))
```

So CMD acts as `M` (meta) and Option is free for special symbols.

**Comment by d12frosted** [comment]
And another update.

In linked `.spacemacs` file there is `osx` layer enabled, but I don't see it in `SPC h d s` output. Try to restart emacs.

**Comment by marcopaga** [comment]
You are right. Needed to restart. This seems to be fine.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp
 (osx :variables osx-use-option-as-meta nil))
```

**Comment by StreakyCobra** [comment]
@marcopaga If your problem is fixed you may consider closing the issue :relaxed:

**Comment by marcopaga** [comment]
It doesn't work.
With the restart I just activated the OSX layer. But still I get an output of *M-5-*. @tko can you send me your .spacemacs config to try it out.
I'm not sure if I get your instructions right. My Spacemacs experience is ~ 24h. ;)

**Comment by marcopaga** [comment]
Two people pointed me to use this setting, which I put in the user-init function:

 (setq-default mac-right-option-modifier nil)

This works for me.

**Comment by marcopaga** [comment]
I put some information in the osx layer readme-File.
https://github.com/syl20bnr/spacemacs/pull/5189

**Comment by MatusGasparik** [comment]
Has this issue really been solved? I just pulled the `develop` branch and suddenly I cannot use the characters behind the ⌥ (option) key. OSX layer doesn't seem to help, nor does the  
`(setq-default mac-right-option-modifier nil)` in the `user-init`. When I switch back to the master branch everything works fine.

**Comment by erdmenger** [comment]
@MatusGasparik For me the afore mentioned `(setq-default mac-right-option-modifier nil)` works consistently on  my Mac with German Keyboard as expected.

This is what I inserted in the 'setq-default' section in my '.spacemacs' 
`
   ;; Make sure OPTION key is working correct on Mac with Germany keyboard
   ;; see also this Git issue:  https://github.com/syl20bnr/spacemacs/issues/5188
   mac-right-option-modifier nil
`

**Comment by lebensterben** [comment]
This needs to be added to templates of `.spacemacs`.
AltGr key is less known to users of US keyboard but exists in many other layouts.
