### ISSUE TITLE
Proposal to add :use keyword to layer declaration

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#5190]
In the spirit of being explicit about what you would like to use, rather than excluding what you don't want, a `:use` keyword for the `dotspacemacs-configuration-layers` list would be useful.

Specifically for adding on to `spacemacs-base`, currently the layers like `spacemacs-ui` `spacemacs-evil` etc. still come whole hog, and you end up adding most of `spacemacs` default back if you want something in the layers. This would allow you to be more selective, more easily.

```
'(better-defaults
  (spacemacs-ui :use '(info+ window-numbering))
  clojure)
```

**Comment by a13ph** [comment]
I suggest keyword "only" instead of "use".
In my opinion it is much more self-evident that "only" those packages are used, rather than additionally or selected from some optional ones (like choosing backend, for example).
However, if it's used somewhere else (use-package?) extensively and therefore will be more consistent, I'll retract

**Comment by sooheon** [comment]
I agree `:only` is more clear about the meaning.

**Comment by sooheon** [comment]
`:exclude` as a layer argument may also make sense, because this keeps layers atomic. Rather than putting the exclusions in a dotspacemacs variable, which can fall out of sync with the actual layers I'm using.

**Comment by a13ph** [comment]
@sooheon I very much agree on the `:exclude` proposition too. Global exclusion has it's merits, but it's not in line with layer way.

**Comment by justbur** [comment]
If I could add to this, I like the idea of having the ability to include or exclude packages but not the separate keywords because then you need to specify rules about what happens when both are used. If the choice were mine, I think I'd do something like this
```elisp
  (spacemacs-ui :packages (info+ window-numbering))
  (spacemacs-ui-visual :packages (not neotree))
```

**Comment by syl20bnr** [comment]
:+1: to @justbur's proposal.

**Comment by sooheon** [comment]
If I want spacemacs-ui, but just without `window-numbering`, I think the explicit `:exclude` will be useful.

```
(spacemacs-ui :packages '(ace-link
                          ace-window
                          buffer-move
                          (centered-cursor :location local)
                          desktop
                          (doc-view :location built-in)
                          flx-ido
                          info+
                          open-junk-file)

(spacemacs-ui :exclude '(window-numbering))
```

The rules for both being used should not be complicated, and it should be no different than if someone has defined `:packages` for a layer, and excluded some other package used by that layer globally, so we need to hash out the precedence anyway.

The benefit is that we gain atomicity for layer declarations, as said before. I don't need to include a whole layer, then exclude bits of it globally, which is brittle.

**Comment by justbur** [comment]
@sooheon you missed that I had a `not` at the head of the list in the second example. The idea was that `:packages (not ...)` would exclude packages.

**Comment by sooheon** [comment]
@justbur I did! That was much more elegant than what I had thought. Scratch my proposal above, yours in much improved.
