### ISSUE TITLE
Gather bad cherry-picking that went through 0.105.10

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#5191]
Hey guys,

I would like to fix the issues introduced by bad cherry-picking for 0.105.10, can you write down the issues you got ? From my head I believe something with bepo, spaceline and another thing about a key binding. Thank you!

@StreakyCobra @justbur @TheBB

**Comment by StreakyCobra** [comment]
https://github.com/syl20bnr/spacemacs/commit/482aa9f0c943031be8d9d6e7511b228c8e68e35d

**Comment by StreakyCobra** [comment]
https://github.com/syl20bnr/spacemacs/issues/5050

**Comment by syl20bnr** [comment]
Thank you @StreakyCobra.
I found back the spaceline one and actually it does not need a hotfix.

**Comment by syl20bnr** [comment]
I think I have all of them. I'll see what I can do.
