### ISSUE TITLE
org agenda shows old DONE items

### ISSUE THREAD

**Issue by fx3O2** [syl20bnr/spacemacs#5195]
#### Description
org agenda for current week or day shows some `DONE` items, scheduled months/years ago

#### Reproduction guide
- Start Emacs
- Open Agenda `C-c a a` (agenda for current week or day)
- I can't show you my org files or content in there :see_no_evil: 

*Observed behaviour:*
I observe some `DONE` items still appear in my agenda for current week or day. I scheduled them months/years ago, they're already marked as `DONE`, their scheduling date is also long time ago, but they're all marked as `DONE`. I don't see any difference compared to some other `DONE` items not showing up.
 
*Expected behaviour:*
I expect those `DONE` items to not show up in my agenda for current week or day. Please note: I do not like to set `org-agenda-skip-scheduled-if-done`. I still want to show up already `DONE` items scheduled this week. In default emacs (without spacemacs) those unwanted DONE items never show up. So this is definitely an issue with spacemacs.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Distribution: Arch x86_64
- Layers:
```
     auto-completion
     emacs-lisp
     git
     org
     syntax-checking
     version-control
     dockerfile
     finance
     colors
     emoji
     python
     django
     javascript
     restclient
     html
     php
```

#### Backtrace

no backtrace

**Comment by TheBB** [comment]
If you can't show us your org files can you at least produce a minimal reproducing example?

**Comment by fx3O2** [comment]
@TheBB Ok this is what I tried: Saved the file `test.org` in my `org-agenda-files` directory, which is currently set to `~/Documents/org` (I store all my org files in there).

I scheduled following example in the test file, 2 weeks ago:

```
* DONE Foo
SCHEDULED: <2016-02-09 Die>
```

This entry will still show up in spacemacs.

Try in plain emacs: 
- move `.emacs.d` to `.emacs.bak`
- start emacs
- M-x customize and set `org-agenda-files` dir
- M-x org-agenda, a (show current week/day)
- test file entry won't appear there

Now tell me what's wrong and why spacemacs messed up this behaviour? :speak_no_evil:

**Comment by TheBB** [comment]
I can't repro. I see the entry on February 9 marked DONE both in regular Emacs and in Spacemacs.

**Comment by TheBB** [comment]
Actually I **can** repro, but only with log mode turned on.

**Comment by TheBB** [comment]
Scratch that. That's how log mode is supposed to work. It shows you when you closed the entries, not when they were scheduled.

Can I see a screenshot?

**Comment by fx3O2** [comment]
screenies for @TheBB :penguin: 

![2016-02-26-165223_1280x800_scrot](https://cloud.githubusercontent.com/assets/1057526/13357358/22cfba6c-dcaa-11e5-93a4-2bf3744ee819.png)

**Comment by fx3O2** [comment]
Hmm, emacs is using orgmode 8.2.10, while spacemacs is using 8.3.4. Bug upstream?

**Comment by fx3O2** [comment]
I can't reproduce anymore, after I started my config from scratch.
