### ISSUE TITLE
Helm Themes: search doesn't work, list of themes is wrong

### ISSUE THREAD

**Issue by aldanor** [syl20bnr/spacemacs#5198]
#### Description
Themes can't be searched through helm; list of themes displayed in helm seems to be incorrect.

#### Reproduction guide
- Start Emacs
- `SPC T h`
- Start typing, e.g. `default`

*Observed behaviour:*
Cursor moves down one with each letter typed regardless of the letter. The status bar shows:

```
Error running timer: (wrong-type-argument sequencep default)
```

Another issues is that the list of themes seems to be wrong, e.g. I have `base16-eighties-dark` in my themes list, but it doesn't show up in `SPC T h` initially. However it's possible to activate it by cycling via `SPC T n`; when it's activated, subsequent `SPC T h` only shows the `default` and a bunch `base16-*` themes, all the other ones missing, which also seems wrong.

*Expected behaviour:*
Helm Themes should show all themes. Helm search should work in Helm Themes.

#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: develop (rev. fd93264)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion emacs-lisp git org python)
```
(this is a fresh installation from develop branch, almost nothing user-configured except for adding a few themes in the list).

**Comment by StreakyCobra** [comment]
I can reproduce it here. Impossible to copy the backtrace though :-/

**Comment by syohex** [comment]
I have sent PR(https://github.com/PythonNut/helm-flx/pull/15)

**Comment by syohex** [comment]
My PR has been merged. I suppose this issue is fixed with latest helm-flx.(You need to wait some hours until MELPA update)

**Comment by StreakyCobra** [comment]
@syohex It's indeed fixed now, thank you :smiley: !

@aldanor I'm closing the issue as it has been fixed. If it is not the case for you let me know, I will reopen it.

**Comment by aldanor** [comment]
Thanks @syohex, the search problem has indeed been fixed!

@StreakyCobra however the other part of this issue hasn't been -- I can't understand a logic behind what's shown in `SPC T h` list, some themes only appear in the list when you cycle to them via `SPC T n` (e.g. cycling to any solarized theme makes all other solarized themes appear in the list).

**Comment by StreakyCobra** [comment]
@aldanor This is a know issue https://github.com/syl20bnr/spacemacs/issues/4062

**Comment by aldanor** [comment]
@StreakyCobra gotcha, will continue there
