### ISSUE TITLE
`:e path` autocompletion doesn't use smartcase

### ISSUE THREAD

**Issue by viccuad** [syl20bnr/spacemacs#5199]
#### Description

When doing `:e foo` there isn't smartcase autocompletion, even if we have
all  `evil-*-case` vars set to `smart` (which is the default).

I'm assuming this is Evil's fault, and I have opened an issue in their bitbucket's repo: 
https://bitbucket.org/lyro/evil/issues/624/e-completion-is-case-strict-even-when
#### Reproduction guide
- Start Emacs
- Let's try to edit a file named Foobar 

_Observed behaviour:_
 `:e foo` + `tab`, it doesn't autocomplete with smartcase.

_Expected behaviour:_
 `:e foo` + `tab`, it autocompletes to `:e Foobar`
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t)
 syntax-checking git
 (version-control :variables version-control-global-margin t version-control-diff-tool 'diff-hl)
 (colors :variables)
 evil-cleverparens evil-commentary evil-snipe vinegar vim-empty-lines tmux
 (c-c   :variables c-c  -enable-clang-support t)
 extra-langs html
 (latex:variables latex-build-command "LatexMk -pdflatex='xelatex --shell-escape'")
 markdown vimscript cscope python django shell-scripts sql emoji selectric speed-reading themes-megapack typography
 (golden-ratio :variables setq golden-ratio-auto-scale t)
 gnus)
```

**Comment by a13ph** [comment]
Helm variables for case folding are `smart` by default and changing `read-file-name-completion-ignore-case` seems to have no effect either (though maybe i had to reload buffer? emacs?) - and it's only fold or no fold only, no `smart` option
