### ISSUE TITLE
Save lockfiles to a special dir instead of same as locked file

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#5202]
Reason: several issues related to emacs not handling those perfectly in some situations (gitter search for "lock file"), and it seems reasonable enough option anyways

_This might be much more suited to be a suggestion upstream, to emacs-dev, I suppose_

There was a [patch](https://gist.github.com/mrflip/2100737) to allow for this, but it needs testing and possibly rewriting, if to provide it as an option and not a change

Maybe there are other alternatives, which I've missed.

**Comment by mijoharas** [comment]
I'd like to suggest reviving this issue. We now have `lock-file-name-transforms` just like auto-save-transforms.

https://www.gnu.org/software/emacs/manual/html_node/efaq/Not-writing-files-to-the-current-directory.html

(I'm trying to grok how the autosave transforms work though.)
