### ISSUE TITLE
:s/from/to/g only replaces one occurence in markdown-mode

### ISSUE THREAD

**Issue by norcalli** [syl20bnr/spacemacs#5203]
#### Description
`:s/from/to/g` doesn't replace all occurences on the line, but the preview shows the correct replacement.

#### Reproduction guide
- Start Emacs
- Open a README.md
- Type `:.s/./x/g`

*Observed behaviour:*
Only the first occurence is replaced, but the preview shows all occurences being replaced.

*Expected behaviour:*
All occurrences should be replace with the `g` flag.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 6689699)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-complete-with-key-sequence-delay 0.1)
 emacs-lisp spotify yaml lua osx go
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
 (rust :variables rust-enable-racer t)
 git markdown colors python html org javascript
 (shell :variables shell-default-height 30 shell-default-term-shell "/usr/local/bin/zsh" shell-default-position 'bottom)
 syntax-checking)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by StreakyCobra** [comment]
Just to be sure, `dotspacemacs-ex-substitute-global` is set to `nil` in your `.spacemacs`?

**Comment by norcalli** [comment]
Yup, not present at all in my .spacemacs.

**Comment by sooheon** [comment]
Also check the value of `evil-ex-substitute-global` directly with `C-h v` rather than look in your .spacemacs, see what emacs has the value as.

**Comment by norcalli** [comment]
Ah gotcha. It is definitely `nil`.

**Comment by sooheon** [comment]
If it's still consistent, some better steps to reproduce starting from `emacs -Q` and initializing the minimum packages will be helpful.

**Comment by syohex** [comment]
markdown-mode had issue which overwrites match-data. I fixed it at https://github.com/jrblevin/markdown-mode/pull/105. Could you try with latest version ?

**Comment by norcalli** [comment]
@syohex Hooray! I can confirm that this is fixed. Thanks for the quick turnaround time!
