### ISSUE TITLE
html layer docs should mention the slim-mode

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#5206]
The HTML layer has[[1](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/html/packages.el#L27)] [slim-mode](https://github.com/slim-template/emacs-slim) support. I think it should be mentioned in the [features list](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/html/README.org#features).

**Comment by JAremko** [comment]
Also jade-mode

**Comment by SShrike** [comment]
I've taken a stab at the issue, tell me if I got it right or wrong.

**Comment by JAremko** [comment]
@SShrike  :+1:  You probably should squash commits

**Comment by SShrike** [comment]
@JAremko Yeah I forget to squash them sorry, I'll get onto it once I get home.

**Comment by JAremko** [comment]
Fixed in #5214
