### ISSUE TITLE
Cannot magit-rebase arbitrary ref with helm

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#5212]
#### Description
It seems like you can't magit-rebase an arbitrary ref with helm.

#### Reproduction guide
- You may need to clear helm caches first.
- Make a sacrificial repo.
- Make 4+ commits on a branch.
- Type `r e` (rebase elsewhere) `HEAD^^ <RET>`.  Assuming cache is empty, helm will use `HEAD^^`
- Type `r e HEAD^ <RET>`.  helm on `magit-rebase` will use `HEAD^^` from its history.  There will be no way to use any prefix of `HEAD^^`

*Observed behaviour:*
You cannot rebase on a ref that is a prefix of something in `magit-rebase` `helm`'s history

*Expected behaviour:*
You can rebase on arbitrary ref.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: personal (rev. 8bdc80b)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults spell-checking syntax-checking semantic typography
 (chrome :variables edit-server-new-frame nil)
 elfeed finance gtags ibuffer mu4e org
 (shell :variables shell-default-shell 'shell shell-default-term-shell "/usr/bin/zsh" shell-default-height 50)
 spacemacs-layouts version-control git c-c   emacs-lisp go html javascript latex lua markdown python ruby shell-scripts sql yaml mir-bbdb mir-magit-annex mir-pass mir-remind-to-diary mir-rc mir-rc-org mir-rc-mail)
```

**Comment by TheBB** [comment]
http://i.imgur.com/JbdnXQ4.png

I have two suggested lines, one with `HEAD^^` from history and one `HEAD^` which is exactly what I typed. Do you not?

**Comment by StreakyCobra** [comment]
You can do it by selecting the line starting with `[?]`, i.e.`[?] HEAD^` which is in the `magit-rebase` section, not in the `magit-rebase History` one.

![example](https://i.imgur.com/5fl2GxM.png)

**Comment by StreakyCobra** [comment]
@TheBB Oooooh pleeease, again

**Comment by StreakyCobra** [comment]
:joy:

**Comment by darkfeline** [comment]
I don't have the [?] line (I probably should have mentioned that).

**Comment by TheBB** [comment]
@tuhdo do you know why that might be?

**Comment by darkfeline** [comment]
Things so far:

- Yes, `dired-chmod` exhibits the same behavior.
- `<ESC>` **confirms in helm's** `magit-rebase`.  It's a good thing Git has a reflog, or I would have lost work.

**Comment by darkfeline** [comment]
Fixed by updating to latest `develop` and purging and reinstalling all packages.

It seems like I was also missing the `spacemacs-helm` layer, however I'm unsure about its effect on this problem.
