### ISSUE TITLE
Haskell Autocomplete With Stack

### ISSUE THREAD

**Issue by AshtonKem** [syl20bnr/spacemacs#5216]
#### Description
I cannot get company-ghc to auto-complete anything, even functions included in Prelude (like getLine). I'm using a brand new Stack haskell Project

#### Reproduction guide
- Create new stack project with ``` stack new my-project simple ```
- Setup GHC with ``` stack setup ```
- Install dev dependencies with ``` stack install stylish-haskell hlint hasktags ghc-mod ```
- Start Spacemacs
- Change to src/Main.hs
- Execute ``` haskell-change-session ```
- Attempt to auto-complete anything, function names, imports, anything.

*Observed behaviour:*
- No action I take can cause an auto-complete prompt to appear in a source directory.
- I can load files into GHCi with ``` C-c C-l ``` as you'd expect.
- Autocomplete works as expected in GHCi.

*Expected behaviour:*
- Autocompletion of functions, imports, and local variables should work as expected in Haskell source buffers.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git osx clojure java javascript yaml html ruby ruby-on-rails ansible markdown haskell spell-checking syntax-checking ibuffer version-control)
```

**Comment by d12frosted** [comment]
Auto-completion for haskell in Spacemacs is available via `company-ghc`, which works only with `ghc-mod`. So you have to use it. Don't forget to set `haskell-enable-ghc-mod-support` to `t`. 

This is not the only option though. But the only solution that comes out of box right now. 

P. S. If you are interested, I'll write you about other solutions lately.

**Comment by AshtonKem** [comment]
I installed ghc-mod via stack, and I was under the impression that
haskell-enable-ghc-mod-support is t by default, so I'm unclear on what I
should be doing as a user to enable haskell auto-completion.

Also note that company-ghc appears to be working in GHCi in Emacs, but
not in any source files, which indicates to me that something else is
happening.

-- 
Ashton

**Comment by AshtonKem** [comment]
I double checked, ``` haskell-enable-ghc-mod-support ``` is t in my setup. 

Looking back I didn't follow the instructions perfectly, as I didn't build ghc-mod from source. I'll try that later and see if that alleviates my problems.

**Comment by d12frosted** [comment]
@AshtonKem  So how is it going?

**Comment by AshtonKem** [comment]
I reinstalled ghc-mod from source (as in the instructions in the haskell layer readme), with no apparent change in behavior.

**Comment by omefire** [comment]
Did anyone figure out how to set this up ? Does anyone have a step-by-step guide on how to make it work ?

**Comment by d12frosted** [comment]
@omefire what exactly doesn't work for you? [Haskell layer readme file][1] provides almost all information needed to setup this. Just go through install part. Where it says to install something - just do `stack install` instead of `cabal install`. In case you have any particular problem - feel free to reach me in Gitter or here :smile_cat: 

P. S. BTW, @AshtonKem any luck with your setup? 

  [1]: https://github.com/syl20bnr/spacemacs/blob/master/layers/+lang/haskell/README.org

**Comment by omefire** [comment]
Thanks @d12frosted . I will check it out.

**Comment by AshtonKem** [comment]
I haven't tried in a few days, I'll record a video in a bit to show my issue  

--
Ashton

**Comment by AshtonKem** [comment]
For reasons I don't understand, it now works. It could've been a hiccup in some versioned software somewhere, or it might've been a mistake on my part. Either way, it now works.
