### ISSUE TITLE
emacsclient -t not work with 'emacs --daemon'

### ISSUE THREAD

**Issue by baobb** [syl20bnr/spacemacs#5219]
#### Description
emacsclient -t <file> does not work

#### Reproduction guide
- Start Emacs with --daemon
- emacsclient -t <file>

*Observed behaviour:*
The console flash and exit
*Expected behaviour:*
The console stay in emacs

#### System Info
- OS: gnu/linux
- Emacs: 25.0.90.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by syl20bnr** [comment]
I cannot reproduce it with 24.5 on OS X.

Anyone can reproduce it on Linux or with 25 ?

**Comment by d12frosted** [comment]
On Emacs 25. `emacsclient -t` works, but still have strange behaviour - sometimes it's like stuck. Also `emacsclient` leads to endless 'waiting for Emacs...`. I am going to upgrade Emacs tomorrow to see if it fixes the problem.

**Comment by izahn** [comment]
It works fine for me on Linux with Emacs 24.5.1

**Comment by a13ph** [comment]
I just recently gave up on emacsclient for now because of this, but I thought it was my fault somehow :hushed: 

#### System Info
- OS: gnu/linux (Ubuntu)
- Emacs: 25.1.50.2
- Spacemacs: 0.105.11
- Spacemacs branch: develop (rev. 5cf6ef8)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript colors deft fasd emoji erc clojure auto-completion better-defaults emacs-lisp git markdown org shell ranger)
```

**Comment by squireg** [comment]
I have the same behaviour on Linux with Emacs 25. Running emacsclient -t causes the console to flash and return to the prompt. 

It only appears to happen when starting with "emacs -daemon". If I start emacs normally and start the server, then "emacsclient -t" works as expected.

- OS: gnu/linux (ubuntu 14.04.4)
- Emacs: 25.1.50.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
`(auto-completion better-defaults clojure dockerfile emacs-lisp git github haskell html java javascript latex lua markdown org puppet python restclient shell shell-scripts spell-checking sql syntax-checking yaml)`

**Comment by d12frosted** [comment]
Just reinstalled Emacs 25 (with `--use-git-head` option) and everything works fine. But keep in mind that I am on OS X. 

Just incase you are interested in `SPC h d s`:

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.11
- Spacemacs branch: develop (rev. 8355671)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion :disabled-for org)
 better-defaults colors emoji eyebrowse
 (git :variables git-magit-status-fullscreen t)
 github
 (org :variables org-enable-github-support t org-bullets-bullet-list
      '("◉" "○" "✿" "❀" "✸"))
 pandoc ranger restclient syntax-checking spacemacs-layouts spacemacs-helm spell-checking
 (shell :variables shell-default-term-shell "/usr/local/bin/fish")
 version-control no-dots
 (elfeed :variables elfeed-feeds d12/elfeed-feeds rmh-elfeed-org-files 'nil)
 (csharp :variables omnisharp-server-executable-path "~/Developer/Other/omnisharp-roslyn/artifacts/build/omnisharp/omnisharp")
 emacs-lisp erlang
 (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "chris-done" haskell-tags-on-save nil haskell-process-log t haskell-process-reload-with-fbytecode nil haskell-process-use-presentation-mode t haskell-interactive-mode-include-file-name nil haskell-interactive-mode-eval-pretty nil haskell-process-suggest-haskell-docs-imports nil)
 (html :variables web-mode-markup-indent-offset 2 web-mode-attr-indent-offset 2 web-mode-code-indent-offset 2 web-mode-css-indent-offset 2 web-mode-sql-indent-offset 2 css-indent-offset 2)
 (javascript :variables js-indent-level 2 js2-basic-offset 2)
 lua markdown python ruby shell-scripts yaml react)
```

**Comment by Bad-ptr** [comment]
Very well) I have a longstanding bug report here https://github.com/Bad-ptr/persp-mode.el/pull/25 .
But for some reason no one seems to be interested to catch this bug, despite the fact that I gave a detailed instructions of how to debug it.
The algorithm described here https://github.com/Bad-ptr/persp-mode.el/pull/25#issuecomment-188099029 , must work for every issue with creating frames (the emacsclient command tries to create a frame).

So, I repeat the instructions here, and maybe some who have this error will do it and we will have more information about this issue:

If you can not create an emacs frame -- check the `before-make-frame-hook` and the `after-make-frame-functions` lists. Just remove functions from these lists one by one: `emacsclient --eval '(pop after-make-frame-functions)'` and see after which removed function you can create the frame. After the frame is created -- M-x toggle-debug-on-error RET and try to execute the last removed function manually(with eval-expression M-:) (You can run a function from the `before-make-frame-hook` list without arguments, but to run a function from the `after-make-frame-functions` you must pass the (selected-frame) as an argument).

if something is not clear, feel free to ask questions.

**Comment by aaronjensen** [comment]
The car of `evil-make-frame-functions` is `self`. If I pop that, `emacsclient` works fine.

**Comment by aaronjensen** [comment]
This is fixed upstream @syl20bnr so this can be closed imo

**Comment by mfdorst** [comment]
> On Emacs 25. `emacsclient -t` works, but still have strange behaviour - sometimes it's like stuck. Also `emacsclient` leads to endless 'waiting for Emacs...`. I am going to upgrade Emacs tomorrow to see if it fixes the problem.

I had this issue too. I found that if I had emacs open in one terminal then if I tried to do `emacsclient` in another terminal I got `wating for Emacs...`. The solution is to use `emacsclient -c`, which will open a new session instead of trying to attach to the one that's already open.

**Comment by lebensterben** [comment]
Incorrect, -c is just creating new frame, not a new session.

**Comment by mfdorst** [comment]
@lebensterben I don't know the lingo, I just know that `-c` fixed the problem.
