### ISSUE TITLE
pylookup bound to wrong key

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#5220]
https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/python/packages.el#L196

pylookup is getting bound to `SPC m m h H` instead of `SPC m h H`.

**Comment by fabianhjr** [comment]
Wait, if this was fixed in develop in march 12, then this should have already been released.

So fixed?

**Comment by darkfeline** [comment]
Nope =(

https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/python/extensions.el#L60

**Comment by TheBB** [comment]
There will be a release soon. :-)

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
