### ISSUE TITLE
Separators look as if they are set to nil even though they are set to slant

### ISSUE THREAD

**Issue by fomentia** [syl20bnr/spacemacs#5221]
Relevant `.spacemacs` code:

```
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration. You are free to put any user code."
       (setq powerline-default-separator 'slant))
```

Relevant iTerm 2 settings:

![screen shot 2016-02-24 at 5 29 25 pm](https://cloud.githubusercontent.com/assets/1526445/13303253/35e4717c-db1c-11e5-9e58-f66a7323e9d6.png)

Spacemacs status bar:

![screen shot 2016-02-24 at 5 30 23 pm](https://cloud.githubusercontent.com/assets/1526445/13303276/586c2a46-db1c-11e5-8977-131dff5be2b7.png)

Let me know if you need any more data!

**Comment by dgadling** [comment]
+1 seeing this as well but only on remote linux hosts that I ssh to, my OS X machine is fine.

**Comment by fomentia** [comment]
An interesting development! If I use the Emacs Mac app, the custom separators show up, even though they don't in iTerm.

**Comment by d12frosted** [comment]
`powerline` has a following function

```
(defun powerline-current-separator ()
  "Get the current default separator. Always returns utf-8 in non-gui mode."
  (if window-system
      powerline-default-separator
    'utf-8))
```

Which means - in terminal it will use `utf-8` separator only.

**Comment by fomentia** [comment]
@d12frosted Oh, my! How do I change that?

**Comment by d12frosted** [comment]
Honestly, I don't know :) I just thought that you can't use some of separators in non-gui. So I checked that inside of package. And here we are.

**Comment by fomentia** [comment]
@d12frosted Ah, ok. TYSM, at least now I know what the problem probably is.

**Comment by d12frosted** [comment]
Closing this issue as everything described in it works as expected 😸
