### ISSUE TITLE
Agda layer docs remove : in the "Some features" paragraph

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#5225]
I think `:` should be removed [here](https://github.com/syl20bnr/spacemacs/blame/master/layers/%2Blang/agda/README.org#L6) and [here](https://github.com/syl20bnr/spacemacs/blame/master/layers/%2Blang/agda/README.org#L15) for the consistency.  Also it will make solving #4399 easier.

**Comment by JAremko** [comment]
Same with the [go layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go)

**Comment by TheBB** [comment]
Just do it and PR. :-)

**Comment by TheBB** [comment]
Moving discussion to https://github.com/syl20bnr/spacemacs/issues/5253
