### ISSUE TITLE
Find or Write file problems

### ISSUE THREAD

**Issue by was4444** [syl20bnr/spacemacs#5234]
When open a file like `foo.txt`, use `Ctrl+x+w` cannot save it as file `foo`, Spacemacs keep auto-complete it as `foo[.txt]`

@jakuzure, Find or Write file `foo` problems:
* If there's a **file** named `foo.txt`;
* If there's a **directory** named `foo.d`;
* If there's a **file** named `bar-foo.txt`;
* If there's a **directory** named `bar-foo.d`;

P.S.
* `dotspacemacs-use-ido nil` set in `.spacemacs`;
* `C-x C-f` bind to `ido-find-file`;
* `C-x C-w` bind to `ido-write-file`;

**Comment by syohex** [comment]
If you use `helm` completion, then

1. `C-x C-w`
2. `C-x C-f` fallback
3. Type file name
4. Select line which starts with `[?]`

![write-file](https://cloud.githubusercontent.com/assets/554281/13313429/1d422d42-dbe1-11e5-87d1-da176ef1f35e.gif)

**Comment by TheBB** [comment]
I'll mark this as documentation so we can get this into the FAQ.

**Comment by was4444** [comment]
@syohex, thanks to the great gif guide, but that's strange. Why not just add a fallback item to the list?

**Comment by jakuzure** [comment]
`dotspacemacs-use-ido nil` is set in my dotfile, but for some reason `C-x C-f` is bound to ido-find-file and I can't manage to create a file that is similar to some already existing filename. I can create xyz just fine, no auto-completion (if there is no similar file) and it just asks if I want to create the file. But if there is already some file named xyz1 I can't create xyz because xyz1 is the only entry in the list.

**Comment by was4444** [comment]
@jakuzure, same in my case. but should we open another issue?

**Comment by syohex** [comment]
@jakuzure You can do it by same way.

1. C-x C-f(ido-find-file)
2. C-x C-f(ido-fallback-command)
3. Type file name
4. Open the file

![ido-find-file](https://cloud.githubusercontent.com/assets/554281/13384522/a97e9426-ded9-11e5-9132-f51f12792b8e.gif)

**Comment by izahn** [comment]
I have PR https://github.com/syl20bnr/spacemacs/pull/4461 open since the
beginning of January to use helm for C-x C-f. It seems like a simple and
uncontroversial change to me, maybe it just slipped through the cracks.

**Comment by was4444** [comment]
Thanks @syohex, we can do that by the way you point out, but that's a fallback, right? I think there should be a better way.

**Comment by syohex** [comment]
`C-<return>` or `M-<return>`. Sorry I missed them because ido-mode sets it(`ido-select-text`) to `C-j` however spacemacs remaps it another bindings.

**Comment by was4444** [comment]
@syohex, it's `C-<return>` in my case.

**Comment by syohex** [comment]
NOTE `C-<return>` cannot be used on no window emacs(`emacs -nw`).

**Comment by jakuzure** [comment]
@was4444 @syohex `C-<return>` works, thank you! The keybinds should use helm anyway though, like @izahn requested in #4461
