### ISSUE TITLE
Error in init.el "Cannot open load file, no such file or directory, s"

### ISSUE THREAD

**Issue by mkollaro** [syl20bnr/spacemacs#5235]
This happened after I updated to 0.105.11 and doesn't change even if I delete `~/.spacemacs`. Git bisect pointed me to a5022743e5d89e61 as being the commit that triggered the bug. I'm using emacs version 24.4.1.

```
Warning (initialization): An error occurred while loading `/home/mkollaro/.emacs.d/init.el':
File error: Cannot open load file, no such file or directory, s
```

**Comment by TheBB** [comment]
Are all your packages updated?

**Comment by mkollaro** [comment]
Ah, you're right, I didn't have them updated. I assumed that an update trough the arrow button does that automatically. Thank you, problem solved.
