### ISSUE TITLE
Reduce Home buffer clutter

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#5240]
At least grouping buttons by semantics would be nice, especially for novices.

Maybe I have some serious focus issues, but seeing 10 buttons makes me ignore them more often than not :D Too much buttons - didn't click.

That's not a superficious issue for novices for sure - there's such thing as directing flow of first use (or something like that under better name) in UX design.

**Comment by a13ph** [comment]
So, we have these buttons:
```
[?] [Homepage] [Documentation] [Gitter Chat] [Update Spacemacs]
          [Update Packages] [Rollback Package Update]
             [Release Notes] [Search in Spacemacs]
```

### Mild change, for now?
I propose we at least group them into 'help' and 'updating'
while separating browser actions
```
            [?] [Search in Spacemacs] [Homepage] [Documentation] [Gitter Chat] 

[Release Notes] [Update Spacemacs] [Update Packages] [Rollback Package Update]
```
### Maybe rearrange these buttons by flow instead
As in "use those buttons in this order" [for those who don't know what they need]
*Might be deprecated by improvements to `SPC h SPC`*

*TBH I'm tending towards first resolving many other problems I find with starting flow: from webpage till 'hello world' and its analogues for other use-cases. Including many other issues with home buffer, which may change buttons*

**Comment by bleggett** [comment]
I'd suggest a slight modification to the above - have `[Update Spacemacs] [Update Packages] [Rollback Package Update]` on their own line, as those are conceptually different than the others, which are basically info/help focused.
