### ISSUE TITLE
LaTeX-insert-item problem with end of line in evil mode

### ISSUE THREAD

**Issue by brabalan** [syl20bnr/spacemacs#5241]
#### Description

When using `LaTeX-insert-item` (`,i` in latex, https://github.com/syl20bnr/spacemacs/blob/f49792e1206895b7440e24c8193ac5af6c5548c7/layers/%2Blang/latex/packages.el#L93), the character under the cursor is put in the following item. As it's not possible to go right of this character, on has to make sure there is a space at the end of the line before using `,i`
#### Reproduction guide
- Start Emacs
- open a latex file
- insert an itemize environment `,e<RET>`
- type `afoo`, then hit escape
- type `,i`

_Observed behaviour:_
This is what we get:

``` latex
\begin{itemize}
\item fo
\item o
\end{itemize}
```

_Expected behaviour:_
This is what we should get

``` latex
\begin{itemize}
\item foo
\item 
\end{itemize}
```
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion elfeed emacs-lisp finance git gnus latex ocaml org
                 (spell-checking :variables spell-checking-enable-auto-dictionary t))
```
#### Backtrace

not relevant

**Comment by justbur** [comment]
I agree. I'll take this one.

**Comment by justbur** [comment]
try this

```elisp
      (defun spacemacs/latex-insert-item ()
        (interactive "*")
        (if (evil-normal-state-p)
            (progn (evil-open-below 1)
                   (beginning-of-line)
                   (call-interactively 'LaTeX-insert-item))
          (call-interactively 'LaTeX-insert-item)))
      (spacemacs/set-leader-keys-for-major-mode 'latex-mode
        "i" 'spacemacs/latex-insert-item)
```

**Comment by brabalan** [comment]
It works great, thanks.

**Comment by dlebrecht** [comment]
if you use autocompletion layer there's a snippet bound on "-" for that. 
Thus:
"- M-/"  or "- <TAB>" or "- <RET>" depending on your config

**Comment by brabalan** [comment]
@dlebrecht thank you for the suggestion. It works with `M-/` here, which is not very convenient.

**Comment by dlebrecht** [comment]
if that interests you, adding this to ur .spacemacs layer configuration, it
should work using tab key:
instead of simply auto-completion, you set variables

     (auto-completion :variables
                      auto-completion-enable-snippets-in-popup t
                      auto-completion-tab-key-behavior 'complete
                      )

**Comment by brabalan** [comment]
@dlebrecht Thanks for the hint, but I think I found another bug, which I'll report separately: one-letter snippets do not work, as for some reason the completion mechanism is not triggered for them. As soon as I enter two letters, I see both completions from company (usual words), and snippets.

**Comment by thang1thang2** [comment]
This is actually not LaTeX specific. This is rather a more general bug and issue with emacs in general. Since emacs is built around the idea of non-modal editing, it has no concept of modal editing. Thus, any command that acts to modify the state of the environment will do so with a "one character off" error. Making a new bullet point in org mode breaks the same way as inserting a new item does in LaTeX, for example. Anything sensitive to the position of the cursor will break this way.

The easiest fix that I can think of is to have commands like `$` go one character past the end of a line so that all of those things work as expected. Otherwise trying to fix each individual thing will be nearly impossible if you want them to implicitly cut the remainder of the line down to the next line.

**Comment by TheBB** [comment]
You can set `evil-move-beyond-eol` to `t` in your config if you want to be able to move past the end of the line.

**Comment by brabalan** [comment]
@TheBB I used so have that setting before switching to spacemacs. It may be nice to put it by default.

**Comment by TheBB** [comment]
We did have it as default for a while and it was quite contentious.

**Comment by brabalan** [comment]
Why? If there is a link to a discussion, I would really like to know what the problems could be with that setting.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/2525

**Comment by brabalan** [comment]
Very interesting read, thanks. So my understanding of the conclusion there is that we need to fix every function that relies on the character being after another character, and the fix by @justbur is the way to go.

**Comment by justbur** [comment]
My interpretation of this bug report was that you were expecting this function to open up a new line below the current one, when what it actually does is insert a new line into the current line, splitting the line if the point is not at the end of of the line.

My "fix" is not trying to reposition the point. It was actually rewriting the function to do something different in normal mode (open a new line below). 

I think it would be awful to try and manually "fix" functions by repositioning the point depending on context.

**Comment by dschrempf** [comment]
Hi,
I cannot see why this has been closed, I repeatedly run into this problem that functions which assume to be at the eol do not work as expected.
