### ISSUE TITLE
Org mode agenda view switch

### ISSUE THREAD

**Issue by lengyueyang** [syl20bnr/spacemacs#5244]
I have a problem after update the spacemacs today.

When I opended the agenda view, the RET, switch to the same window, but before its the other window

**Comment by TheBB** [comment]
Can you update your issue with precise reproduction steps, expected and actual effect?

**Comment by NJBS** [comment]
This seems like expected behavior if I understand your issue correctly. RET will open the org file in the same window while TAB will open it in another window.

**Comment by lengyueyang** [comment]
Thanks TheBB and NJBS
I want to use RET to open org file in another window.

**Comment by NJBS** [comment]
You can add the following to your .spacemacs configuration file:
``` elisp
  (with-eval-after-load 'org-agenda
    (define-key org-agenda-mode-map (kbd "RET") 'org-agenda-goto))
```

**Comment by TheBB** [comment]
`TAB` and `RET` are bound to the same function on my system, and it opens the entry in the other window.

**Comment by NJBS** [comment]
On my system 'TAB' is bound to 'org-agenda-goto' whilst 'RET' is bound to 'org-agenda-switch-to'. It seems like this is consistent with the documentation [here](http://orgmode.org/manual/Agenda-commands.html).

**Comment by StreakyCobra** [comment]
On my system I have the same behavior as @TheBB :stuck_out_tongue:

**Comment by StreakyCobra** [comment]
The only place in the code where `org-agenda-switch-to` is defined is in the org agenda transient state.

**Comment by NJBS** [comment]
I don't have the chance to test this on `develop` at the moment, do you still experience the same behavior on `master`?

**Comment by StreakyCobra** [comment]
Oh yeah `master`, I always forget about this one :sweat:

Indeed, in master they have the behavior you described. So this is fixed in `develop`. @lengyueyang If all your questions have been answered, you may consider closing the issue, otherwise let us know what you need more :-)

**Comment by lengyueyang** [comment]
Thanks for all guys, I sloved the problem as NJBS's comments

**Comment by tommyjiang** [comment]
Just want to remind someone else if wants to map TAB to `org-agenda-switch-to` can use the code as following:

```elisp
  (with-eval-after-load 'org-agenda
    (define-key org-agenda-mode-map (kbd "<tab>") 'org-agenda-switch-to))
```
