### ISSUE TITLE
Spacemacs dark theme :s face

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#5248]
When doing a `:s/foo/bar/` style command, Evil will highlight both the deleted and replacement text accordingly.  However, the deleted text isn't visibly changed when using Spacemacs's dark theme.

This is on `develop` 83556719

**Comment by darkfeline** [comment]
This is only a problem if you use visual mode to select text and use `:<',>'s` because the visual selection face is the same as the deleted text preview.

Simply doing a `:%s`, for example, this isn't a problem.

**Comment by cpaulik** [comment]
You might want to raise this upstream https://github.com/nashamri/spacemacs-theme

**Comment by darkfeline** [comment]
Thanks, didn't realize it was a separate repo. https://github.com/nashamri/spacemacs-theme/issues/40
