### ISSUE TITLE
Is there a way to kill a parent in Emacs Lisp layer ?

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#5249]
Let's say I have something like this:

```elisp
(defun foo ()
  (let ((bar "baz"))
    (message "do something")
    (message bar)
    (message "do something else")))
```

Then I decided that I don't want to print "baz" so I remove ` (message bar)`

```elisp
(defun foo ()
  (let ((bar "baz"))
    (message "do something")
    (message "do something else")))
```

But now I also don't need `let`  

```elisp
(defun foo ()
    (message "do something")
    (message "do something else"))
```

**Is there a way to remove enclosing block if cursor is on its child ? And what if instead I want to surround something (reverse situation) ?**

The `let` or `progn` case is pretty straightforward anyway. But I think it might be pretty powerful tool if you want to remove something like `if` and the other branch (without the cursor) keeping the one with the cursor on it.

**Comment by sooheon** [comment]
If your cursor is just before the opening paren of `(message "do something")`, you can `sp-splice-sexp-killing-backward`. Or you can `sp-splice-sexp`, `kdd`.

**Comment by sooheon** [comment]
> But I think it might be pretty powerful tool if you want to remove something like if and the other branch (without the cursor) keeping the one with the cursor on it.
This is just `sp-raise`

**Comment by JAremko** [comment]
@sooheon  It so cool. Thanks! :heart: 

And all this stuff and much more seems to have bindings under `m` `k`   but it isn't mentioned in [the docs](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/emacs-lisp)

*Now I understand why people love to wrap everything in `progn`. :)*

@StreakyCobra  Should it be mentioned or am I missing something?

**Comment by StreakyCobra** [comment]
https://github.com/syl20bnr/spacemacs/blob/e061b13eb5a37c5331b75da87fa82ae01032a31a/doc/DOCUMENTATION.org#lisp-state-key-bindings

**Comment by JAremko** [comment]
@StreakyCobra  I still think it should be in the layers docs.  At least explicitly mentioned that [those](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/emacs-lisp#key-bindings) aren't all the bindings available. 
I man how many people read DOCUMENTATION.org all the way down :sleeping:

**Comment by StreakyCobra** [comment]
`evil-lisp-state` is not made available through the `emacs-lisp` layer but it's directly installed by the spacemacs distribution itself, it's why it's in the official documentation.

**Comment by JAremko** [comment]
Sure but when I want to use Spacemacs for golang programming I'm reading golang layer docs. Wen TypeScript - typescript layer docs. For org mode - org mode docs. But when I want to use it for elisp... It's somewhat counter-intuitive to also read DOCUMENTATION.org for that :confused: 
After all Spacemacs supposed to be friendly for people who are new to Emacs.

**Comment by StreakyCobra** [comment]
In the "Key bindings" section of the emacs-lisp README you just linked, it's well explained that a special `lisp-state` exists, that it's documented in the official DOCUMENTATION because it's not emacs-lisp specific, and there is even a link pointing to it. The information is there, if people are not reading the doc we cannot do anything more.

If you still think it would be better in the layer's README, just create a PR and it will be discussed there.

**Comment by JAremko** [comment]
Hey it's in there... It's literally what I was asking for:
>As this state works the same for all files, the documentation is in global DOCUMENTATION.org. In general, use SPC k to interact with the lisp-state.   

And how exactly I didn't notice it. Probably should not just look at the table next time.
 I think it's time to stfu and commit something redeeming good. :confused: 

Interesting. How many users also simply skip right to the bindings table.
