### ISSUE TITLE
Malformed link in Vinegar layer's README.org 

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#5250]
[Malformed link](https://github.com/syl20bnr/spacemacs/blame/master/layers/%2Bvim/vinegar/README.org#L14) in Vinegar layer's README.org when viewing via GitHub

**Comment by StreakyCobra** [comment]
@JAremko Can't you just create a PR with all the documentation issues you have found instead of opening one issue per wrong link?

**Comment by AlejandroCatalina** [comment]
It would be a lot helpful, yes.

**Comment by JAremko** [comment]
But then the vast amount of work to be done can frighten beginners :confounded: 
 I want this issues to be the gateway drug :syringe: 

But okay, you're right, I'll create an aggregator issue.

**Comment by TheBB** [comment]
I don't think @StreakyCobra wanted *n* + 1 issues for *n* links. He just wants one PR…

**Comment by JAremko** [comment]
People are complicated :confused:

**Comment by TheBB** [comment]
Moving discussion to https://github.com/syl20bnr/spacemacs/issues/5253
