### ISSUE TITLE
Malformatted documentation issues aggregation 

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#5253]
Here I will link issues and refer links in README.org files that looks ugly when viewing via GitHub

### The list:
 - #5250
 - #5225 
 - #5224
 - #5247
 - #5227

**Comment by TheBB** [comment]
[Malformed link](https://github.com/syl20bnr/spacemacs/blame/master/layers/%2Bvim/vinegar/README.org#L14) in Vinegar layer's README.org when viewing via GitHub

**Comment by TheBB** [comment]
[this link](https://github.com/syl20bnr/spacemacs/blame/master/layers/%2Bconfig-files/terraform/README.org#L13) probably should be reformatted - it looks weird.

**Comment by TheBB** [comment]
I think `:` should be removed [here](https://github.com/syl20bnr/spacemacs/blame/master/layers/%2Blang/agda/README.org#L6) and [here](https://github.com/syl20bnr/spacemacs/blame/master/layers/%2Blang/agda/README.org#L15) for the consistency.  Also it will make solving #4399 easier.

**Comment by TheBB** [comment]
Same with the [go layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go), [Haskell](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/haskell), [js](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/javascript), [lua](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/lua)...  and [IPython Notebook layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/ipython-notebook) has this `Micro-state: =ipython-notebook=`  paragraph.  Might be we should stick to `a-z` `A-Z` `0-9` ` ` paragraphs?  This way they will be more readable, searchable and can work on the GitHub.

**Comment by TheBB** [comment]
Wakatime layer's [table of contents](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+tools/wakatime/README.org) is broken on GitHub.

**Comment by TheBB** [comment]
[The documentation](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/nim/README.org) doesn't show anything usefull via GitHub

**Comment by TheBB** [comment]
(All comments above originally by @JAremko in the linked issues.)

**Comment by JAremko** [comment]
And who's spamming now :smile:
