### ISSUE TITLE
Gitter-IRC intregration

### ISSUE THREAD

**Issue by stvndf** [syl20bnr/spacemacs#5255]
I propose the Freenode IRC channel (which usually has 40+ concurrent users) be linked with Gitter, which would mean users of both channels can communicate together without having to run two clients/servers concurrently. 

Neovim uses [Gitter IRC Bot](https://github.com/finnp/gitter-irc-bot) to do this, and it works really well (you can try it by going to https://gitter.im/finnp/gitter-irc-bot and #gitterircbot on Freenode).

I idle in #spacemacs and notice many people come by to ask a question and leave before people in the channel get the chance to respond -- judging by the activity of the Gitter channel, that problem would be eliminated. 

It'd also be good simply for the purpose of giving people the choice of preference with regard to how they connect with the Spacemacs community/chat. If people don't use Gitter, this would mean they don't miss out on the activity that happens on the Gitter channel and vice versa.

**Comment by DanielFGray** [comment]
Can I take credit for this? I totally suggested this in #spacemacs, @stvndf just beat me to filing the issue lol

Neovim gets a lot of activity in both areas and there doesn't seem to be much confusion, I struggle to think of a reason why this might be a bad idea.

:+1:

**Comment by JAremko** [comment]
:+1:

**Comment by alxndr** [comment]
:+1:

**Comment by a13ph** [comment]
:+1: :tired_face: 
Even though Gitter has IRC gateway, this will help some newcomers. Larger attack surface and all. 
Dunno if we have where to host it, but I suspect someone does

**Comment by liaowang11** [comment]
:+1:

**Comment by jb55** [comment]
> If people don't use Gitter/prefer IRC

but Gitter is IRC. I idle in the Gitter IRC with weechat just fine. I don't see the problem here...

**Comment by a13ph** [comment]
@jb55
- gitter is not irc, even if it does have gateway
- what was meant, I suppose, is: "if people prefer using #spacemacs channel, proper IRC, or not using this gateway"

**Comment by stvndf** [comment]
@jb55 

It’s not as straightforward as you suggest with IRC ‘being IRC’ as @a13ph mentions. It involves setting it up, having a Github/Gitter account and joining a different channel to the IRC one on another server. Not ideal if people just want to pop in and ask a question while on IRC. 

Furthermore #spacemacs doesn’t benefit from it — I’d understand disregarding the IRC channel if Spacemacs didn’t support it, but Spacemacs does officially support it and directs people there, making the lack of activity there an issue for visitors.

A significant point I am making is that it converges two discrete communities into one and in that respect makes it stronger through greater user participation and increased convenience (as discussed).

**Comment by jb55** [comment]
> It involves setting it up, having a Github/Gitter account and joining a different channel to the IRC one on another server

This took me like 30 seconds to do, is this really a concern?

> but Spacemacs does officially support it and directs people there

Is this true? I've only ever seen the gitter IRC referenced in the docs. If that's the case then sure, but I don't see how having two official IRC channels is productive.

**Comment by stvndf** [comment]
> This took me like 30 seconds to do, is this really a concern?

For the uninitiated, yes. 


> If that's the case then sure, but I don't see how having two official IRC channels is productive.

That's my point — converging the two channels (Gitter and #spacemacs) through the integration suggested would be more productive than having two completely discrete channels.

**Comment by nixmaniack** [comment]
I just saw [this](https://github.com/syl20bnr/spacemacs/#getting-help) in docs regarding spacemacs IRC. 

> If you prefer IRC, connect to the Gitter Chat IRC server and join the #syl20bnr/spacemacs channel.

Is there any reference to #spacemacs@freenode anywhere in the docs? @stvndf

**Comment by stvndf** [comment]
You're right in that there doesn't seem to be an explicit mention of it @nixmaniack, I'll edit my post to more accurately reflect this. 

The point still stands though about having a way that enables people who'll inevitably congregate on the Freenode channel (currently over 40 users on it, and after all it's generally considered de facto server for FOSS projects) a means of communicating with people on Gitter (and vice versa) as opposed to joining and not being able to get addressed adequately for whatever purpose they joined.

**Comment by syl20bnr** [comment]
While I'm always happy to see other communication channels put in place by the community, `#spacemacs` on freenode is an unofficial communication channel, the official promoted channel is on gitter. IRC is supported by gitter via the IRC bridge, lots of users already use it and it seems to work.

We can better document the bridge to make it easier for people to use it though.

**Comment by thang1thang2** [comment]
I believe the point is that the bridge is just that, a bridge. It would be better to not bother using the bridge (unless you really wanted to) and just use IRC natively and have the irc bot synchronize the two together. I see no reason to not make the `#spacemacs` freenode server an official extension of the chat. There's also very little indication that `#spacemacs` on freenode is NOT an official channel and having to explain to people that log in there that they should join the bridge or just visit a web url might be a bit confusing; additionally, people more strictly in alignment with FOSS might not want a github account.

Neovim is an excellent example of why this is a good idea. There's very few, if any, downsides and much more in the way of possible benefits.

**Comment by stvndf** [comment]
@syl20bnr It’s understandable to have a single point of communication so that a community doesn’t dilute, and I agree with that. However, consider that this wouldn’t detract from Gitter — instead it would augment it. 

I don’t know whether you’ve seen how Neovim’s Gitter/IRC works, but it interoperates really well and benefits everybody as a whole. 

And indeed @thang1thang2 makes a good point about not alienating fervent FOSS supporters averse to Github/Gitter.

**Comment by syl20bnr** [comment]
I thought about it during the week-end and I may be open to this for most of the reasons above and one additional reason which is to have a fallback in case of Gitter technical issues or worst.

**Comment by a13ph** [comment]
To play for the other side as well a bit, bridge or bot is mostly similar in terms of abstraction levels, they both are limited ways to access original (gitter) channel. Unless you run some additional code akin to ERC's Gitter support.

**Comment by alxndr** [comment]
I'd like to see some kind of connection between the Gitter room and the IRC room. Despite the Gitter room being the official communication channel, the IRC room on Freenode gets several people each week asking questions (which, more often than not, go unanswered).

(Anecdote time: I'm a not-incompetent IRC user, but I can't seem to get in to the Gitter room using the existing Gitter-IRC bridge. I'm connected to the Gitter IRC network (using IRCCloud), but I don't know what to `/join` to get in to the Spacemacs-specific room.)

**Comment by TheBB** [comment]
The channel name on the Gitter IRC bridge is `#syl20bnr/spacemacs`

**Comment by alxndr** [comment]
aha! thanks @TheBB

**Comment by divansantana** [comment]
@stvndf @DanielFGray so it seems like this is a good idea and the maintainers seem open to it. What steps is needed to get this done and who is going to run with them?

**Comment by jamrizzi** [comment]
+1

**Comment by oprypin** [comment]
@syl20bnr

**Comment by syl20bnr** [comment]
@oprypin :+1:

**Comment by oprypin** [comment]
It is done, the issue can be closed.

**Comment by syl20bnr** [comment]
Now it is setup, we should mention the freenode channel in the
documentation.
