### ISSUE TITLE
Request for outshine mode

### ISSUE THREAD

**Issue by meditans** [syl20bnr/spacemacs#5258]
It would be wonderful to have a package for [the outshine package](https://github.com/tj64/outshine) to be able to have workflows like [this](https://www.youtube.com/watch?v=kxFvpJPetaw&feature=youtu.be).
If I try to add manually `outshine` to the list of packages I don't get fontification or any functionality.

**Comment by StreakyCobra** [comment]
You can use it "easily" with this:

1. Add outshine to the `dotspacemacs-additional-packages` in your `.spacemacs`:

           dotspacemacs-additional-packages '(outshine)

2. To define the `outline-minor-mode-prefix` key before the package is loaded (as explained on the project's README), add this at the end of your `dotspacemacs/user-init` function in `.spacemacs`:

          (defvar outline-minor-mode-prefix "\M-#")

3. Setup `outshine` as explained on their README by adding this at the end of  `dotspacemacs/user-config` in your `.spacemacs`:

        (require 'outshine)
        (add-hook 'outline-minor-mode-hook 'outshine-hook-function)

4. Set `outline-minor-mode` to be automatically loaded for the mode you want, by appending (still to `dotspacemacs/user-config` in your `.spacemacs`) either:

        (add-hook 'prog-mode-hook 'outline-minor-mode)

    for enabling it in any programming mode, or 

        (add-hook 'emacs-lisp-mode-hook 'outline-minor-mode)
        (add-hook 'LaTeX-mode-hook 'outline-minor-mode)
        (add-hook 'picolisp-mode-hook 'outline-minor-mode)
        (add-hook 'clojure-mode-hook 'outline-minor-mode)
        (add-hook 'ess-mode-hook 'outline-minor-mode)
        (add-hook 'ledger-mode-hook 'outline-minor-mode)
        (add-hook 'message-mode-hook 'outline-minor-mode)

    for enabling this in the modes you want.

**Comment by meditans** [comment]
Hi, thanks for the detailed reply.

I did most of those things before opening the issue on github, I missed the fact that:

```elisp
(defvar outline-minor-mode-prefix "\M-#")
```

had to be put in the `dotspacemacs/user-init` function, and, for some reason, I skipped the line:

```elisp
(add-hook 'outline-minor-mode-hook 'outshine-hook-function)
```

Now it works better, for example I have the menu when I hit `M-#`.

Unfortunately, however, I still get no fontification, the commands don't do anything in the buffer (I tried this in both `haskell-mode` and `emacs-lisp-mode`). In most cases, I get the error `outline-back-to-heading: before first heading`. 

Did you manage to use some of outshine's features in a buffer?

**Comment by StreakyCobra** [comment]
I tried with both Python and Haskell: it works (cursor is at `|`):

```python
# * Headline
# |
```

For Haskell I noticed you need to **not** put a space between `--` and the `*`:

```haskell
--* Headline
--|
```

In both case `M-# #` worked at least.

**Comment by meditans** [comment]
Ok, not putting a space between `--` and `*` in haskell changes the color of the outline (although, not the dimension like in the video), and makes possible to collapse them.

However, unfortunately, this is not a viable approach, as then the source file doesn't compile (`--*` is seen as an operator). The odd thing is that, if I put the space between `--` and `*`, the export to the org-mode version works correctly, but to be able to do that export one has to have a first heading of the form `--*`, otherwise he gets the error I was mentioning before.

The curious thing is that none of these problems appear in the video I linked, so I wonder how to get that experience.

**Comment by meditans** [comment]
Ok, so, I took a look at the dotfile of the author of that video [here](https://github.com/acowley/dotfiles/blob/master/emacs), and saw that the incriminating variable is `'(outshine-preserve-delimiter-whitespace t)`. With that one set, at least one gets both the structure and the compilation.

**Comment by meditans** [comment]
I'm now sufficiently satisfied by this setup to close this issue :)
