### ISSUE TITLE
One letter snippets do not expand using TAB

### ISSUE THREAD

**Issue by brabalan** [syl20bnr/spacemacs#5259]
#### Description

I have the auto-completion layer enabled, and one letter snippets do not expand using TAB, they only expand using M-/.

Snippets with two or more characters work correctly, as they are proposed in the company popup and they can then be expanded.

I have reproduced this using latex and emacs-lisp modes.
#### Reproduction guide
- Start Emacs
- Open a latex file
- type '-' followed by TAB

_Observed behaviour:_
Nothing happens, or the `-` gets indented

_Expected behaviour:_
The snippet bound to `-` (namely `\item`) would expand
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'complete)
 elfeed emacs-lisp finance git gnus latex ocaml org
 (spell-checking :variables spell-checking-enable-auto-dictionary t))
```

**Comment by nixmaniack** [comment]
Check if setting `(setq company-minimum-prefix-length 1)` helps.

**Comment by brabalan** [comment]
It does not in this particular case because `-` does not start a company completion.

I guess that I want to decouple yasnippet from company …

**Comment by dlebrecht** [comment]
For me one letter snippet does not start the completion menu, but the one letter snippet is expanded when I hit TAB. 

Actually the variable auto-completion-tab-key-behavior 'complete does not change this behavior. 

I looked into the auto-completion documentation, and it says M-/ exand a snippet. So I don't actually know why TAB expands snippets on my setup.

**Comment by brabalan** [comment]
Could you say what `F1 k TAB` returns for you? Here it's `ident-for-tab`.

**Comment by dlebrecht** [comment]
as I said, it is `yas-expand` on my setup. I haven't set that up. I assume you have yas-minor-mode on.

**Comment by brabalan** [comment]
`yas-minor` is on, yes. Looking at the code, I see this: https://github.com/syl20bnr/spacemacs/blob/f49792e1206895b7440e24c8193ac5af6c5548c7/layers/auto-completion/packages.el#L214 which says that yas minor mode map is disabled and that hippie-expand is used instead. And a few lines above hippie-exp is set up with only the `M-/` keybinding.

I'm confused.

**Comment by fintelkai** [comment]
+1 for this issue.
