### ISSUE TITLE
Auto-completion for Elm not working in Elm layer

### ISSUE THREAD

**Issue by soundstruck** [syl20bnr/spacemacs#5264]
#### Description
Elm layer auto-completion is not working, for example, "List." (and wait) produces nothing. I noticed an error in *messages* buffer that occurs upon opening an.elm file:

File mode specification error: (invalid-function (function spacemacs//elm-find-root)) [2 times ]

NOTES: 
- elm-oracle is globally installed; "$: which elm-oracle" returns "/usr/bin/elm-oracle"
- within Spacemacs, eval of `(elm-oracle--get-completions-cached-1 "List.")` seems to return the correct payload
- within Spacemacs, eval of `(elm--has-dependency-file)` returns t

#### Reproduction guide
- Start Emacs
- Open .elm file in Elm project (elm-package.json in same directory as .elm file) with spacemacs editor

*Observed behaviour:*
- File mode specification error: (invalid-function (function spacemacs//elm-find-root)) [2 times ] in *messages* buffer on open of .elm file
- auto complete not working in .elm file

*Expected behaviour:*
Auto completion working in .elm files

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 company-mode better-defaults elixir elm emacs-lisp erlang eyebrowse git gtags html markdown org osx ranger semantic
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (syntax-checking :variables syntax-checking-enable-tooltips nil)
 unimpaired version-control)
```

#### Backtrace
```

```

**Comment by mrapogee** [comment]
This is just a typo. To fix, change this:

```
(defun elm/post-init-flycheck ()
  (add-hook 'elm-mode-hook 'flycheck-mode)
  (add-hook 'elm-mode-hook '#'spacemacs//elm-find-root))
```

To this:

```
(defun elm/post-init-flycheck ()
  (add-hook 'elm-mode-hook 'flycheck-mode)
  (add-hook 'elm-mode-hook 'spacemacs//elm-find-root))
```
in `layers/+lang/elm/packages.el

Can someone with the workflow for developing spacemacs submit a pull request?

**Comment by TheBB** [comment]
It's already fixed in develop by [this](https://github.com/syl20bnr/spacemacs/commit/388ea21e75a6af3efc4934bb9e1104e2598bd1c6#diff-206f29f4140d6f575cefa66d26ddd72d) commit, which does a lot more than just that. @syl20bnr would have to backport the relevant part.

**Comment by syl20bnr** [comment]
Backported in 0.105.19
