### ISSUE TITLE
react: % key doesn't work for html/jsx tags

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#5265]
Say you have the following, possibly being returned from a function or something
```html
<div>
    <h1>Hello world</h1>
</div>
```
with the cursor placed in the opening `div` pressing <kbd>%</kbd> should move the cursor to the closing tag and vice versa.

In `web-mode` it works as expected (including jumping between `{` and `}`) but not in `react-mode`. In `react-mode` the cursor jumps to the `v` in both tags instead.

**Comment by robbyoconnor** [comment]
You have to add evil-matchit hooks for react-mode -- PRs welcome.

**Comment by robbyoconnor** [comment]
Be sure however to do it against `develop` and not `master`.

**Comment by syl20bnr** [comment]
Fixed in 0.105.12
