### ISSUE TITLE
add chrome layer variable for plain text email ?

### ISSUE THREAD

**Issue by dwang20151005** [syl20bnr/spacemacs#5266]
I'd like to use the chrome layer, but I like my email in plain text.  

What do you think of adding a layer variable to the chrome layer to toggle between plain and rich text composition?  Rich text mode would be the current behavior, using gmail-message-mode to render markdown.  Plain text mode would use [edit-server-htmlize](https://github.com/frobtech/edit-server-htmlize) to support plain text email.  

I would be happy to submit a pull request if you approve of the general idea.

**Comment by jb55** [comment]
(triage) it looks like this didn't get much attention/support. should we close this for now?

**Comment by dwang20151005** [comment]
I actually wrote the pull request but closed it eventually.  I'm happy to re-open it if anyone would promise to look at it.  I would still like this to be included, so I don't have to maintain my own fork of the layer.

**Comment by dwang20151005** [comment]
I still want this.
