### ISSUE TITLE
Unable to paste things into editor in insert mode

### ISSUE THREAD

**Issue by hosh** [syl20bnr/spacemacs#5268]
#### Description
I am unable to paste certain strings in insert mode (whether activated with `A` or `I` or `O`).

#### Reproduction guide
- Start Emacs
- Copy `"361e5fdfeb48be1ef9ea864e1ab7dee6580a93106586d999e6bfd5aad618c633"`

*Observed behaviour:*
It would insert `"361e5` then complain about `Can't find e`

*Expected behaviour:*
The whole string is pasted in.

I have tried different strings, not sure why this is happening. Some shorter strings work, some longer strings don't. I have tried it on a Linux system with a similar build and this happens too.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: release-0.105 (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp eyebrowse ruby ruby-on-rails html javascript racket haskell erlang elixir
            (git :variables git-magit-status-fullscreen t)
            markdown org syntax-checking version-control themes-megapack)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment]
What's happening here is that you are in the terminal and you're pasting by pasting to the terminal program, which streams the characters to Emacs. Emacs then encounters the escape sequence `fd`, switches to normal state, and the following `fe` is interpreted as a normal state command.

If you want to paste like this in the terminal you might want to consider disabling `evil-escape-mode` first.

**Comment by hosh** [comment]
Great! I don't use `evil-escape-mode` at all. How do I completely disable it?

**Comment by TheBB** [comment]
Add `evil-escape` to your list of excluded packages.

**Comment by hosh** [comment]
Yep, got that. Works, thanks!

Ref: https://github.com/syl20bnr/spacemacs/issues/1270#issuecomment-94322084
