### ISSUE TITLE
Opening URLs from Spacemacs doesn't work

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#5271]
My browser opens, but with empty URL.
True for both Chromium and Chrome (unstable branch).
I would appreciate any pointers on where to look.

#### System Info
- OS: gnu/linux
- Emacs: 25.1.50.2
- Spacemacs: 0.105.11
- Spacemacs branch: develop (rev. e061b13)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(eyebrowse github themes-megapack javascript colors deft emoji erc auto-completion better-defaults emacs-lisp git github markdown org shell ranger spell-checking syntax-checking)
```

**Comment by StreakyCobra** [comment]
It's working here. Reproduction steps?

**Comment by a13ph** [comment]
That's more of a question to resolve this misconfiguration of mine (It worked before, but I've messed it up somehow) than to report issue with Spacemacs itself.

If I had repro steps, I wouldn't need to ask this :P

**Comment by StreakyCobra** [comment]
Reproductions steps in the sense of: «One example that does this in your configuration», like:

- Start emacs
- Open the scratch buffer
- Paste `http://google.ch`
- Use `SPC x o` to open the url

Or, is it with `org-mode`? or…? This already give us information.

**Comment by a13ph** [comment]
any way I try
- links in home buffer
- hints like `spc x o`

**Comment by a13ph** [comment]
Since then I've switched/changed a lot. I assume this issue is still lingering in the backup of custom.el which is the remnant of my bankruptcy on those variables.
Meanwhile it can be closed, @d12frosted

**Comment by beppu** [comment]
I had the same problem, and for me, it turned out that `xdg-open` was the problem.  Here is the solution.

http://askubuntu.com/questions/540939/xdg-open-only-opens-a-new-tab-in-a-new-chromium-window-despite-passing-it-a-url

**Comment by hackrole** [comment]
seems not work in mac.

**Comment by duianto** [comment]
@hackrole What's your system info?
Press `SPC h d s` to copy the system info to your clipboard.

I don't have mac to test with, but in Windows on both the Spacemacs `master` and `develop` branches, it works to open links with `SPC x o`.
- From the Spacemacs home buffer `SPC b h`
- Or from the `*scratch*` buffer `SPC b s` when it contains a link, for example: `https://google.com`
This opens the default browser google chrome with the target url.

#### System Info:
<details><summary>
master branch (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey
 (auto-completion :variables)
 emacs-lisp git ivy html javascript julia lsp markdown multiple-cursors org python shell spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

<details><summary>
develop branch
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. cff6b47e6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(autohotkey
 (auto-completion :variables)
 emacs-lisp git ivy html javascript julia lsp markdown multiple-cursors org python shell spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by hackrole** [comment]
# system info
#### System Info :computer:
- OS: darwin
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 58dcd6320)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible graphviz vimscript
         helm
         (ibuffer :variables ibuffer-group-buffers-by 'projects)
         nixos pass restclient
         (syntax-checking :variables syntax-checking-use-original-bitmaps t)
         (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior nil auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.2 auto-completion-private-snippets-directory "~/.spacemacs.d/snippets" auto-completion-enable-snippets-in-popup t spacemacs-default-company-backends
                          '(company-files company-capf)
                          require-final-newline nil auto-completion-enable-help-tooltip t)
         themes-megapack imenu-list
         (dash :variables helm-dash-browser-func 'eww)
         git github
         (plantuml :variables org-plantuml-jar-path "/usr/share/plantuml/plantuml.jar" plantuml-jar-path "/usr/share/plantuml/plantuml.jar")
         salt vimscript
         (latex :variables latex-build-command "LaTex" latex-enable-folding t latex-enable-magic t)
         (markdown :variables markdown-live-preview-engine 'vmd)
         terraform dap fasd
         (org :variables org-enable-org-journal-support t org-journal-dir "~/org/journal/" org-journal-file-format "%Y-%m-%d" org-journal-date-format "%A, %B %d %Y")
         (ranger :variables ranger-show-literal t ranger-show-hidden t ranger-cleanup-on-disable t ranger-parent-header-func 'ranger-parent-header-line ranger-cleanup-eagerly t ranger-parent-depth 2 ranger-ignored-extensions
                 '("mvk" "iso" "mp4"))
         (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh")
         emacs-lisp
         (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save nil python-formattr 'black python-format-on-save nil python-sort-imports-on-save nil python-backend 'anaconda flycheck-flake8-maximum-complexity 8)
         django scheme c-c++ erlang lsp
         (go :variables go-tab-width 2 go-format-before-save t go-use-golangci-lint t godoc-at-point-function 'godoc-gogetdoc go-fmt-command "goimports")
         haskell prettier
         (html :variables web-fmt-tool 'prettier)
         (typescript :variables typescript-fmt-on-save t)
         javascript react lua plantuml elixir clojure scala ruby yaml rust typescript javascript sql docker pdf chrome twitter
```
- System configuration features: JPEG RSVG IMAGEMAGICK GLIB NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2

# after try what you say, still not work
the error message
```
link-hint--apply: Wrong number of arguments: #[(url &rest args) "ÆÇ!
	C
È!É!Ê!ËÌ\")
7ËÍ\"57Î!AÉÏ!ÐÑÒ\";VÓÔÐÑÒ\"\":Õ!Ö2¥Ñ !!@ Ë @\"× A#ØÖÙ\"!A!r*ÚÛ\"0¥×#+" [args browse-url-new-window-flag url-handler-mode url process-environment browse-url-mailto-function called-interactively-p interactive file-name-absolute-p expand-file-name ...] 6 ("/usr/local/Cellar/emacs-plus/26.3/share/emacs/26.3/lisp/net/browse-url.elc" . 21293) (browse-url-interactive-arg "URL: ")], 0
```

**Comment by duianto** [comment]
`SPC x o` also works for me in Linux, on the latest develop branch with updated packages.


The next thing to try is to backup your current setup.
Then comment out your configurations.
If it's still happening then and try a fresh clone.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 57721d8e7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git helm markdown multiple-cursors org treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM THREADS LIBSYSTEMD LCMS2
