### ISSUE TITLE
Set reasonable default colors for company popup for all themes

### ISSUE THREAD

**Issue by aldanor** [syl20bnr/spacemacs#5276]
There's many great themes in the megapack, but many (most; e.g. all base16 ones) of them have horrible orange/red colors for company popup which leaves the impression that something's broken. Having to fix the colors on a per-theme basis is a questionable option.

Is it feasible to automatically set the default colors for the popup for an arbitrary theme if they are not provided explicitly by the theme? It could probably be done programmatically based on theme's font-face and background colors (e.g. slightly darken if colors is light, slightly brighten if dark; for selected item in the menu, darken twice or lighten twice). I'm only suggesting auto-fixing the themes that are broken this way, if it's the theme author's intention to make company popup stand out, it should be up to them. 

A related PR which seems to have been abandoned and closed: https://github.com/syl20bnr/spacemacs/pull/1502

A few examples are below, but this is applicable to many more themes.

Here's `wombat`... 
![screen shot 2016-02-27 at 20 37 13](https://cloud.githubusercontent.com/assets/2418513/13375234/3a90ea16-dd92-11e5-8599-169307e1c7e9.png)

... `spacegray` is also bad:
![screen shot 2016-02-27 at 20 38 06](https://cloud.githubusercontent.com/assets/2418513/13375220/189e3e22-dd92-11e5-8a85-540831700b9d.png)

... however `spacemacs-dark` is ok, that's how it should be for all themes:
![screen shot 2016-02-27 at 20 43 46](https://cloud.githubusercontent.com/assets/2418513/13375271/d2e622ea-dd92-11e5-833b-f99c562f2413.png)

**Comment by TheBB** [comment]
I don't think it's feasible to hack themes in Spacemacs. There's too many, it's too opinionated, and it's another layer of complexity we don't need.

**Comment by aldanor** [comment]
@TheBB I'm only asking if it's feasible to somehow set a few defaults for company popup in a reasonable manner if the colors are not provided explicitly in the theme (as opposed to "hacking themes" which was suggested in #1502). Given two/three base colors from the theme itself, it's possible to generate all the necessary colors for company, so it would look consistent.

You can't really make that yellow/red box any worse anyway...

**Comment by sooheon** [comment]
I think the difficulty there is if you customize those colors, then they are customized to override colors even for themes which have nice defaults. AFAIK there's no (sane) way to check whether a theme has defined those colors an *then* apply customizations only if they're missing.

**Comment by syl20bnr** [comment]
Unfortunately we cannot guess the correct colors for every theme on the planet.

If you like a theme, open an issue on the theme repo to ask for company support. I'm not in a different position than you, when Spacemacs themes need support for something I open an issue on the theme repo, last one was for swiper and ivy.

**Comment by aldanor** [comment]
@sooheon @sooheon Here's a thought:
- Before applying a theme, explicitly set the defaults for company colors to company defaults (i.e. yellow / darkred as of now).
- After applying the theme, check if those colors are still untouched at their defaults.
- If they still are, replace them with a saner set of colors, based on the foreground/background/selection color set by the theme.

This would:
- Be generic enough so if you add a new theme without company customizations it looks consistent with most everything else (addressing @syl20bnr concern).
- Not touch any customizations in the existing themes (addressing @sooheon's concern).
- Only do something in the situations where you currently get company default colors (i.e. the ugly yellow/red popup).

The only edge case I could think of is where a theme *explicitly* sets all company colors to be exactly the same as company defaults. But I can't think of a single theme that does that or would do that.

Would this be doable?

**Comment by louy2** [comment]
I like how @aldanor is approaching this, but I also think it is more appropriate to fix it on `company` side instead of here. I think you can create an addtional plugin or convince company to merge a pull request to try to adapt styles to the current theme.

**Comment by a13ph** [comment]
why guess color if you can derive (inherit) them from some common variables which are set by almost every theme?

**Comment by louy2** [comment]
@a13ph Such as?

**Comment by syl20bnr** [comment]
Closing this discussion as it is flagged as won't fix. While I like the idea I prefer theme maintainers to add support for popular packages instead, or implement the smart choice of colors at the company level with an advice.
