### ISSUE TITLE
Using $ in visual mode selects newline (or nonexistent whitespace?)

### ISSUE THREAD

**Issue by karljs** [syl20bnr/spacemacs#5278]
#### Description
When I am in visual mode and use `$` to move to the end of the line, it selects not only the rest of the line but seemingly also the newline character and (visually at least) a bunch of nonexistent whitespace.  If I want to, e.g., wrap from the cursor position to the end of the line in a pair of parentheses using visual mode and `$` then the closing paren ends up on the next line rather than the end of the current one.

#### Reproduction guide
- Start Emacs
- Open any buffer
- Enter two arbitrary lines of code or text
- Move somewhere in the middle of the first line
- Attempt to surround the remainder of the first line using evil-surround by doing `v$s(`
- Note that the closing paren is on the second line instead of the first

*Observed behaviour:*
When using `$` in visual mode, the newline character seems to be selected when it shouldn't be.

*Expected behaviour:*
Using `$` in visual mode only selects up through the last visible character.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(agda auto-completion c-c   emacs-lisp games git github haskell html idris javascript latex markdown ocaml org php python racket ruby rust spell-checking spotify themes-megapack xkcd)
```

#### Backtrace
```
Not relevant
```

**Comment by StreakyCobra** [comment]
I reproduced this with just the `evil` package enabled (without the Spacemacs configuration). You can reproduce this with:

- Press `SPC q D`, enter `evil` on the prompt, then `RET`
- This will restart emacs without Spacemacs, with just `evil` loaded.
- In the stock emacs, use `M-x evil-mode` to enable `evil`
- Enter a line, go in the middle, press `v$`, notice the end-of-line is selected.

So this looks like the default behavior of `evil`, this should be reported [upstream](https://bitbucket.org/lyro/evil/wiki/Home) then.

**Comment by nixmaniack** [comment]
It's quite annoying actually. Do link back when you report upstream. 

Strangely enough, if I goto visual mode using `v` and execute the function bound to `$` i.e. `evil-end-of-line` using `M-:` it doesn't select `eol`

**Comment by karljs** [comment]
I've filed a bug report upstream with Evil at the following URL:

https://bitbucket.org/lyro/evil/issues/629/using-in-visual-mode-selects-past-newline

**Comment by karljs** [comment]
After a comment from Evil's developer on the upstream bug report, I tested this in Vim and it turns out that it's expected behavior.  Although I think this is the incorrect implementation choice, it seems to be a conscious decision.
