### ISSUE TITLE
Python testing in debug mode not working with ipdb

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#528]
If I set a breakpoint in python it will automatically choose ipdb if available. These breakpoints do not work with nose.el testing in debug mode which seems to require pdb breakpoints.

**Comment by cpaulik** [comment]
This is partly fixed because it works with the py.test. I leave it up to you if you want to close the issue.

**Comment by cpaulik** [comment]
I meant I leave it up to @TheBB :smile:

**Comment by TheBB** [comment]
I'll go for close. We should maybe consider switching the default testrunner to pytest?

**Comment by cpaulik** [comment]
I use py.test more or less exclusively because I like it better than nose. But the current pytest on melpa is broken. I've been trying to get https://github.com/ionrock/pytest-el/pull/6 merged to fix it.

**Comment by cpaulik** [comment]
So I'm in general for changing the default to py.test but I don't know if other people share my preferences
