### ISSUE TITLE
cannot load on windows 

### ISSUE THREAD

**Issue by chantisnake** [syl20bnr/spacemacs#5284]
I have followed the instruction:

I have set the HOME dir:
![capture](https://cloud.githubusercontent.com/assets/10100995/13376840/7ad73746-dd93-11e5-8322-6dd4fd4edd1d.PNG)

I have cloned space emacs both in $HOME and AppData\Roaming:
![capture](https://cloud.githubusercontent.com/assets/10100995/13376851/c54603ac-dd93-11e5-9612-3f5769a3c754.PNG)

I have used the recommended windows setting and I have used the stable release version:
![capture1](https://cloud.githubusercontent.com/assets/10100995/13376852/d6fe640e-dd93-11e5-80a1-47c94ce71611.PNG)
(I also tried the mingw version...)
![capture](https://cloud.githubusercontent.com/assets/10100995/13376858/1194fede-dd94-11e5-9f7d-14b8a8d7d176.PNG)

the spacemacs is simply not loading when I started emacs... I don't know what to do...
There is no bug at all, it is just not loading...

**Comment by chantisnake** [comment]
I use the lower version and force load the init file, then everything works...
```
emacs -q -l "C:\Users\zcsxo\AppData\Roaming\.emacs.d\init.el"
```

god that feels good!

**Comment by chantisnake** [comment]
okay... another problem...
```
Symbol's function definition is void: projectile-mode
```
this is in latest version of spacemacs...

**Comment by chantisnake** [comment]
emacs 24.5.1 works with 104, but not 105...

**Comment by TheBB** [comment]
Try starting with `--insecure`. Wipe your elpa directory first.

**Comment by chantisnake** [comment]
That is actually another weird thing:
![capture1](https://cloud.githubusercontent.com/assets/10100995/13379238/488402be-ddee-11e5-9750-fc75cc11a518.PNG)
![capture](https://cloud.githubusercontent.com/assets/10100995/13379239/4b74b18a-ddee-11e5-9a60-1aa6c6ac7148.PNG)

**Comment by StreakyCobra** [comment]
be sure to remove your old `.emacs` file first, it's probably why `.emacs.d/init.el` of Spacemacs is not used. Also `--insecure` is a Spacemacs option, so be sure to use it when you start with the Spacemacs config. As @TheBB said, be sure to remove `elpa` first before starting again with `--insecure`

**Comment by chantisnake** [comment]
That is why!... thanks, sorry for wasting your time...
