### ISSUE TITLE
left-click link in org-modes highlight to jump point

### ISSUE THREAD

**Issue by irrevenant** [syl20bnr/spacemacs#5287]
#### Description

If I left-click on a link in an org file, it jumps to the destination and highlights (setting active region) everything between where I clicked and where I jumped to.
#### Reproduction guide
- Start Emacs
- SPC h SPC
- ENTER # or select any documentation, default is fine
- Left-Click link for "Update and Rollback" # again, any link will do

_Observed behaviour:_
The target of the link is displayed and everything above it (back to the character in the link I clicked on) is highlighted.

_Expected behaviour:_
no highlighting, no region changes, just follow the link.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp git markdown org
            (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
            themes-megapack)
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by nixmaniack** [comment]
I can reproduce it. I though it was my configuration that caused this.

**Comment by smallid** [comment]
I'm also hitting this issue- from what I can tell down-mouse-1 is bound to both `evil-mouse-drag-region` and `mouse--down-1-maybe-follows-link` in command mode. However in edit mode, the `evil-mouse-drag-region` binding is replaced by `mouse-drag-region` and the behavior is as expected.
