### ISSUE TITLE
How can I remap vim black hole register?

### ISSUE THREAD

**Issue by chantisnake** [syl20bnr/spacemacs#5288]
```vim
nnoremap d "_d
nnoremap dd "_dd
```

I don't know how to set that up in evil...

**Comment by TheBB** [comment]
It's not so simple. Maybe this will work?

```elisp
(evil-define-operator my-delete (beg end type)
  (interacive "<R><x><y>")
  (evil-delete beg end type ?_))

(define-key normal-state-map "d" 'my-delete)
(define-key visual-state-map "d" 'my-delete)
```

**Comment by StreakyCobra** [comment]
@TheBB "interac**t**ive"

**Comment by chantisnake** [comment]
I have tried, I don't think this is working ...

**Comment by StreakyCobra** [comment]
What about:

```elisp
(define-key evil-normal-state-map (kbd "d") (lambda ()
                                              (interactive)
                                              (evil-use-register ?_)
                                              (call-interactively 'evil-delete)))
```

**Comment by chantisnake** [comment]
I am sorry, but no, they all perform the same with nothing set...

**Comment by StreakyCobra** [comment]
As far as I understood what your code is supposed to do, the one I proposed is doing the same. Maybe I didn't understood it correctly, so can you provide us more information:

- Some reproduction steps
- The expected behaviour

**Comment by dvzubarev** [comment]
;;If you would like to remap more operators, you may find my [config](https://gist.github.com/dvzubarev/1c5ae51e17ebc9695a96) to be useful.

**Comment by TheBB** [comment]
It might be more fruitful for you to ask this at the evil repo instead of here.

**Comment by chantisnake** [comment]
i will try to ask the question there！

**Comment by katusk** [comment]
@chantisnake, did you manage to get an answer?

I have tried the evil-define-operator approach in the above for the bindings with keys "-d", but deleting lines with "-dd" does not work. In more detail:

- If I hit "-df)", text gets deleted as expected ending up in the black hole register.
- If I hit "-dd", nothing happens, and the message "Quit" appears at the bottom where the Ex command line is. I would expect "-dd" to delete the current line into the black hole register, just as normally the default "dd" would delete (and additonally yank) the current line.

Guys, is the latter behaviour expected, am I missing something? I noticed `basic-operators.el` of @dvzubarev has a separate function evil-destroy-line, and a separate binding, "D", for deleting lines. Do you have to set up a separate binding for deleting lines?

**Comment by katusk** [comment]
With my "-d" mapping:

- Strangely, if I hit "-d-", the whole line is deleted into the black hole register, which I would expect when hitting "-dd".

Maybe this has something to do with the following? Purely brainstorming here, I have truly no idea really. At [How do I change only what “dd” does in evil-mode's normal-state in a minor mode](http://emacs.stackexchange.com/questions/12605/how-do-i-change-only-what-dd-does-in-evil-modes-normal-state-in-a-minor-mode/14958), I have found the following comment:

> It's probably because evil hardcodes repetition of the operator as a line-wise operation

The next comment there points to the `evil-macros.el` file. I looked at it at bitbucket.org; if you search for "dd", you are going to find the following comments:
>             ;; Make linewise operator shortcuts. E.g., "d" yields the
>             ;; shortcut "dd", and "g?" yields shortcuts "g??" and "g?g?".

Unfortunately, I cannot make sense of the code below the comments, as I do not know Emacs Lisp at all.

**Comment by chantisnake** [comment]
I found the solution:

https://bitbucket.org/lyro/evil/issues/468/how-delete-to-the-register-in-a-keymap

```
  ;; delete without register
  (evil-define-operator evil-delete-without-register (beg end type yank-handler)
    (interactive "<R><y>")
    (evil-delete beg end type ?_ yank-handler))
  (define-key evil-normal-state-map (kbd "d") 'evil-delete-without-register)
  (define-key evil-visual-state-map (kbd "d") 'evil-delete-without-register)
  (define-key evil-normal-state-map (kbd "D") 'evil-delete)
  (define-key evil-visual-state-map (kbd "D") 'evil-delete)
```
