### ISSUE TITLE
Multiple Sources in `<kbd>SPC</kbd> f e c` (find-contrib-file).

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#529]
I think it would be neat to do a helm-spacemacs-ish way to go to any contrib file that can be found in the contrib files path, you know,  dotspacemacs-configuration-layer-path, /contrib/ and /private. Maybe a Tab for each? and also this would be useful to implementing a warning in the case of duplicate layer names. (if this isn't done already)

**Comment by syl20bnr** [comment]
Does it like: say I want to go to `packages.el` of python, I do  `SPC f e h` then "python" then `TAB pack RET"

The warning for duplicate layer names is in my todo list but I'm too lazy to implement it ^_^

**Comment by CestDiego** [comment]
omaigaaawd. Forgot about that :)  it's really cool. I should read the new documentation again. It's been so long since I read it the first time that I keep missing the new cool stuff :P Maybe just read the changelogs now and

**Comment by CestDiego** [comment]
Closed because functionality was already there :P
