### ISSUE TITLE
scheme layer keybinding not works

### ISSUE THREAD

**Issue by zhewuzhou** [syl20bnr/spacemacs#5294]
I am new to spacemacs, I enable scheme layer and using guile as scheme implementation, after I do run-geiser I found all keybindings regards to geiser-eval not works, for example SPC e b supposed to be geiser-eval-buffer

**Comment by StreakyCobra** [comment]
@zhewuzhou It's not `SPC e b`, but `SPC m e b` that cat also be accessed through `, e b`.

**Comment by zhewuzhou** [comment]
Thanks your for your response, but I am very sure it's not SPC m e b or SPC e b, because when I run helm-descbinds geiser-eval-buffer, I got:
_geiser-eval-buffer (C-c  C-b)_, 
but in scheme layout package.el it's(my understanding is <leader> e b):
 _"eb" 'geiser-eval-buffer_
actually I did experiment it's something todo with run-geiser, somehow it's overwrite the keybinding in scheme layer. The steps of that experiment are:
1. Uninstall scheme layer
2. load private elisp code from dotspacemacs/user-config and it works, the code is:
_(evil-leader/set-key-for-mode 'scheme-mode
    "eb" (xscheme-send-buffer))_

**Comment by StreakyCobra** [comment]
> but in scheme layout package.el it's(my understanding is &lt;leader&gt; e b):
"eb" 'geiser-eval-buffer

If you look at the function name it's setting the binding for a major-mode, so it places it in `SPC m e b`, which should be aliased as `, e b`.

Anyway I just tested and it seems to be working, i.e:

1. Start Spacemacs
2. `SPC f J scm RET` to open a temporary `scm` (scheme) file.
3. `M-x run-geiser RET guile RET`
4. `ESC SPC w w` to go back to the scheme buffer
5. `SPC m e b` (or `, e b`) is calling `geiser-eval-buffer`.

If it is not the case for you, please give us reproduction steps.

**Comment by zhewuzhou** [comment]
I changed evil \<leader\> from (SPC) to (,), in my case what geiser-eval-buffer?

**Comment by zhewuzhou** [comment]
Sorry, my fault to set leader as following:
dotspacemacs-leader-key ","
dotspacemacs-major-mode-leader-key "SPC"

**Comment by StreakyCobra** [comment]
Uh, I'm not sure if it's a good idea to set both to the same, they should be different, not sure we even support this officially.

CC @syl20bnr @justbur

**Comment by justbur** [comment]
There's going to be a lot of conflicts if you set them to the same key. You should be able to unset the major mode key and use `,m` for the major mode keys prefix.
