### ISSUE TITLE
Helm leaving temp files scattered around working directories

### ISSUE THREAD

**Issue by edrex** [syl20bnr/spacemacs#5296]
I keep ending up with files like this in random directories:
# %2AHelm%20Help%2A#181729Q1

Not sure what action causes these to be created, but I assume it has something to do with helm and help.

Writing to the working directory without user consent is kind of a violation of trust IMO.

**Comment by TheBB** [comment]
They look like [lockfiles](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Locks.html). They can be disabled by setting `create-lockfiles` to `nil`. Thought I don't understand what business a helm buffer has doing this kind of thing. I've never seen these.

**Comment by edrex** [comment]
Huh, I think I've been seeing them with low intensity since I started using Spacemacs a few months back. I'm guessing maybe I'm visiting some functionality that you're not, due to my newbity.

I actually already have (setq-default create-lockfiles nil) in my user-config, so double weird.

**Comment by edrex** [comment]
I was wondering if maybe they were left over from before I turned off lockfiles a few weeks ago, but their creation dates are within a couple of days.

**Comment by sooheon** [comment]
I'm seeing something similar using ivy, but they look like #foo.file#. I guess these are lockfiles as well?

**Comment by edrex** [comment]
@sooheon yeah, i think those are just regular lockfiles, and the setting above should stop them being created.
