### ISSUE TITLE
How to isolate *.cache* and *elpa* path?

### ISSUE THREAD

**Issue by exaos** [syl20bnr/spacemacs#5301]
I want to manage several profiles in one git repository. Each profile looks like something *user@host*. So, the convenient way is to put each profile into a directory and then link this directory as **~/.spacemacs.d**, and then link **spacemacs** as **~/.emacs.d**. The problem is that spacemacs installs packages into **ELPA** and keeps temporary files in **.cache**, which is not good for many profiles. How to isolate the two dirs and keep them as dirs in each profile?

**Comment by a13ph** [comment]
I raise you another valid concern - nuking /elpa kills some not-so-cachy .cache content, like bookmarks, too. Stuff which i would consider part of the config, tbh.

**Comment by exaos** [comment]
Maybe an alternative way is better: Link the spacemacs as **~/.spacemacs.d/** and user's own profile as **~/.emacs.d/**, then keeps caches and elps inside **~/.emacs.d/** as usual.

**Comment by robbyoconnor** [comment]
Docker was made for this.

**Comment by exaos** [comment]
I submit a pull request to solve my problem:
https://github.com/syl20bnr/spacemacs/pull/5331

**Comment by bmag** [comment]
To answer the original question, you can change the location of the cache directory by changing the value of `spacemacs-cache-directory` in `dotspacemacs/user-init`.
For example, if you want your cache directory to be in `.spacemacs.d/.cache`, add this line to `dotspacemacs/user-init`:
```elisp
(setq spacemacs-cache-directory (expand-file-name ".cache" dotspacemacs-directory))
```

If #5410 is merged, you should be able to the same thing for the elpa directory by changing the value of `package-user-dir`.

**Comment by syl20bnr** [comment]
I merge #5410 and closed #5331.
#5410 is a lot simpler and better fit Spacemacs.

**Comment by exaos** [comment]
Thanks! `package-user-dir` is good. But there are many hard-coded `user-emacs-directory`. I prefer this way: https://github.com/syl20bnr/spacemacs/pull/5501
:-)

**Comment by syl20bnr** [comment]
Not sure what you mean by "hard-coded", we use the variable, not a fixed value.

Spacemacs is meant to sit in emacs user directory. Since there are very simple ways to achieve what you need I won't introduce a new variable.
