### ISSUE TITLE
Twittering mode used SPC button

### ISSUE THREAD

**Issue by istinspring** [syl20bnr/spacemacs#5304]
I really don't like to leave my full screened emacs in iTerm2, so i added twitter here. But looks like twittering mode used (twittering-mode) spacemacs's SPC. Any suggestions?

**Comment by d12frosted** [comment]
¯\_(ツ)_/¯

**Comment by a13ph** [comment]
Remap keys used by twittering-mode which conflict with Spacemacs. This would make half a PR for twitter layer :D

**Comment by istinspring** [comment]
Ugh will try to read about layers at least.

**Comment by cpaulik** [comment]
There is already a PR for a Twitter layer https://github.com/syl20bnr/spacemacs/issues/2837 but is does not rebind the keys. I've made a very basic layer some time ago just to try twittering-mode. You can find it [here](https://github.com/cpaulik/dotfiles/tree/master/.spacemacs-config/config-layers/twitter)

**Comment by d12frosted** [comment]
Already fixed in master.
