### ISSUE TITLE
evil-escape-key-sequence inconsistent with behavior of escape key

### ISSUE THREAD

**Issue by calebmeyer** [syl20bnr/spacemacs#5313]
#### Description
The behavior of pressing the evil-escape-key-sequence (`jk` for me) and the behavior of escape are not aligned.

#### Reproduction guide
- Start Emacs
- Open the scratch buffer `SPC b s`
- Change the mode to ruby mode `SPC SPC ruby-mode RET`
- Type in two spaces (so we have some indentation) then this ruby code:
```ruby
def test
end
```
- Press the evil-escape-key-sequence. Note that the `end` moves back to the beginning of the line
- Erase the buffer `SPC b e`
- Type the same code as above, including the two space indentation
- Press `ESC`. Note that the end remains in place (expected behavior)

*Observed behaviour:*
Pressing `jk` outdents the line (and enters normal mode). This seems to happen only in ruby mode.
Pressing `ESC` does not outdent the line (and enters normal mode).

*Expected behaviour:*
Pressing `jk` or `ESC` change from insert mode to normal mode and perform no additional actions on the buffer.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: develop (rev. e061b13)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
 better-defaults
 (colors :variables colors-enable-rainbow-identifiers nil)
 emacs-lisp git javascript markdown osx python ruby ruby-on-rails themes-megapack shell-scripts
 (shell :variables shell-default-height 30 shell-default-position 'top)
 version-control)
```

**Comment by TheBB** [comment]
This is probably the same issue as https://github.com/syl20bnr/spacemacs/issues/5261.

**Comment by calebmeyer** [comment]
@TheBB that seems quite likely. I'll investigate @syl20bnr 's fix from there to see if it works for ruby mode.

**Comment by calebmeyer** [comment]
The workaround (reproducing here) is `(add-hook 'evil-insert-state-exit-hook 'indent-according-to-mode)`. Works like a charm. Thanks @TheBB . Closing this issue, since we can track from #5261.

**Comment by TheBB** [comment]
Great. It's actually kinda bothersome in Python to be honest.
