### ISSUE TITLE
Emacs freezes in Gitattributes-Mode when entering newline at end of buffer

### ISSUE THREAD

**Issue by datafux** [syl20bnr/spacemacs#5317]
#### Description
Emacs freezes in Gitattributes-Mode when entering newline at end of buffer

#### Reproduction guide
- Start Emacs
- open new gitattributes file (SPC f f) .gitattributes (yes)
- press i
- press return

*Observed behaviour:*
emacs freezes

*Expected behaviour:*
new line

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: nil (rev. 6689699)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion colors emacs-lisp clojure git markdown org c-c   semantic pandoc latex outline-magic ranger games ebib olivetti mu4e ibuffer deft ox-reveal)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by StreakyCobra** [comment]
Reproduced here. I think this should be reported upstream, as this can be reproduced on a stock emacs:

- Start Spacemacs
- Press `SPC q D`, enter `magit` then `RET`
- This will restart Emacs *without* Spacemacs and enable the `magit` package
- `C-x C-f` to open `.gitattributes`
- Press `RET`
- Emacs freezes
