### ISSUE TITLE
Why is evil-visual-state <escape> rebound in spacemacs-base?

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#5321]
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs-base/packages.el#L248

`evil-exit-visual-state` is the default. Unless there is a compelling reason, I believe we should keep it the default, just because of strange edge cases. For example, this current rebinding causes problems when entering and exiting visual state and using multiple cursors (yes this is already buggy, but it can be made usable with a in-development branch).

**Comment by sooheon** [comment]
Pinging @syl20bnr for an executive decision re this. git-blame points the finger to you :p

**Comment by syl20bnr** [comment]
You can only blame me for moving the line :-)
This was introduced by a PR to make `ESC` like `C-g`, see the commit pointed by the blame.

```elisp
;; Make <escape> quit as much as possible
  (define-key minibuffer-local-map (kbd "<escape>") 'keyboard-escape-quit)
 -(define-key evil-visual-state-map (kbd "<escape>") 'keyboard-quit)
  (define-key minibuffer-local-ns-map (kbd "<escape>") 'keyboard-escape-quit)
  (define-key minibuffer-local-completion-map (kbd "<escape>") 'keyboard-escape-quit)
  (define-key minibuffer-local-must-match-map (kbd "<escape>") 'keyboard-escape-quit)
 (define-key minibuffer-local-isearch-map (kbd "<escape>") 'keyboard-escape-quit)
```

Maybe we can remove it, I don't have any objection to do it :-)
