### ISSUE TITLE
ruby-mode not honoring deep paren option.

### ISSUE THREAD

**Issue by askreet** [syl20bnr/spacemacs#5322]
I'm having the same issue as described here:
http://stackoverflow.com/questions/2776317/like-vim-emacs-ruby-indentation

Setting `ruby-use-smie` to `nil` with `defvar` has no effect on whether or not this configuration option works. I'm using Spacemacs v0.105 on Emacs 24.5.1 (OS X).

**Comment by StreakyCobra** [comment]
Have you tried to put this:

    (setq ruby-deep-indent-paren nil)

in `dotspacemacs/user-config` of your `.spacemacs`?

**Comment by askreet** [comment]
@StreakyCobra I don't have a `dotspacemacs/user-config`, I have only `dotspacemacs/config` -- is my `.spacemacs` outdated?

I'll try adding it to `dotspacemacs/config`.

**Comment by askreet** [comment]
That did not work.

**Comment by StreakyCobra** [comment]
> is my `.spacemacs` outdated?

Slightly, you guessed it :wink: `SPC f e D` is helpful to keep it up to date :-)


> That did not work.

Ok, I don't know then, I'm not doing ruby stuff at all.

**Comment by StreakyCobra** [comment]
Have you tried to unset both in `user-config`, this seems to be needed:

     (setq ruby-deep-indent-paren nil)
     (setq ruby-use-smie nil)

And restarted Spacemacs?

**Comment by askreet** [comment]
@StreakyCobra Okay, now we're getting somewhere! It's not quite right, but I'm going to see if I can figure it out by using user-config.

**Comment by askreet** [comment]
Well, I now feel like ruby-mode is working-as-advertised and I just don't like it.

What I get:
```ruby
method_call({
    stuff: {
      things: 'hi'
    }
  })
```

What I want:
```ruby
method_call({
  stuff: {
    things: 'hi'
  }
})
```

Reading the indentation code in ruby-mode is challenging, but I'll try to see if I can make my own custom function.

**Comment by askreet** [comment]
Switching to the enh-ruby-mode option for the ruby layer fixed this issue. In the past, it had issues replaying vim macros. Wish me luck...

**Comment by ankitrg** [comment]
Did you make this work?

**Comment by vpokrityuk** [comment]
@StreakyCobra Thank you so much. Spent almost an hour googling trying to fix ruby indentation. Luckily saw your post mentioning "(setq ruby-use-smie nil)" that did help!

**Comment by asok** [comment]
It seems that this answers this https://stackoverflow.com/a/20733875/710003
`(setq ruby-align-to-stmt-keywords '(if begin case def))`. Maybe it should be added to the ruby layer?

**Comment by yurighensev** [comment]
Summing it up from previous answers:
```lisp
ruby-align-to-stmt-keywords '(if def begin case) ; set fixed indentation for these statements
ruby-deep-indent-paren nil                       ; set fixed indentation for arguments inside parenthesis
ruby-use-smie nil                                ; set fixed indentation for chained method calls
```
