### ISSUE TITLE
Renaming a file to an existing directory malfunctions

### ISSUE THREAD

**Issue by edrex** [syl20bnr/spacemacs#5323]
`spc f R` to rename file `foo`, select an existing directory `bar/`. I was hoping this would move `foo` to `bar/foo` and this is indeed what happens on-disk, but the live buffer now has path `bar`.

Could be tacked onto PR #3825.

**Comment by ksjogo** [comment]
Could you recreate/reopen with the changes from https://github.com/syl20bnr/spacemacs/pull/3825/files
