### ISSUE TITLE
evil-mc g r prefix conflicts with magit

### ISSUE THREAD

**Issue by edrex** [syl20bnr/spacemacs#5324]
In magit views, `g r` is mapped to refresh. This gets overridden by evil-mc's `g r` prefix.

**Comment by TheBB** [comment]
We haven't turned on `evil-mc-mode` anywhere?

**Comment by edrex** [comment]
I have `(global-evil-mc-mode)`. I guess my assumption was that flag was meant to be used to test evil-mc integration. Since it's not on by default or even documented, should I close this and just comment on https://github.com/syl20bnr/spacemacs/issues/2669?

**Comment by TheBB** [comment]
Well if you turn on `evil-mc-mode` globally, that's what you're going to get. :-)

This is what I did instead, and probably what we will do when we actually *do* turn it on in Spacemacs:

```elisp
(add-hook 'prog-mode-hook 'turn-on-evil-mc-mode)
(add-hook 'text-mode-hook 'turn-on-evil-mc-mode)
```

I do not get the conflict in magit this way. Closing this, as it seems like a user configuration problem.

**Comment by edrex** [comment]
Thanks for that snippet. I don't see the conflict with magit status when enabling evil-mc-mode that way.
