### ISSUE TITLE
latexpreview won't work once I loaded org layer

### ISSUE THREAD

**Issue by danielyang1009** [syl20bnr/spacemacs#5327]
`#+STARTUP: latexpreview` won't work once I loaded org layer. When I using `emacs -Q` or default out-of box spacemacs with no additional layer loaded, they both works.

**Comment by StreakyCobra** [comment]
Sorry, this was not closed on purpose (@syl20bnr is trying too see what tool could be responsible for this :-) ) I'm reopening it then.

Also, it would be helpful if you can update your issue to follow the bug report template (`SPC h I`), thanks!

**Comment by danielyang1009** [comment]
I only got this url link, however I just can't open it.
`https://github.com/syl20bnr/spacemacs/issues/new?body=%3CPLEASE%20REPLACE%20ALL%20UPPERCASE%20EXPRESSIONS%20AND%20DELETE%20THIS%20LINE%3E%0D%0A%23%23%23%23%20Description%0D%0ADESCRIPTION%20OF%20THE%20PROBLEM%0D%0A%0D%0A%23%23%23%23%20Reproduction%20guide%0D%0A-%20Start%20Emacs%0D%0A-%20REPRODUCTION%20STEPS%0D%0A%0D%0A*Observed%20behaviour:*%0D%0ADESCRIPTION%20OF%20THE%20OBSERVED%20BEHAVIOUR%0D%0A%0D%0A*Expected%20behaviour:*%0D%0ADESCRIPTION%20OF%20THE%20EXPECTED%20BEHAVIOUR%0D%0A%0D%0A%28%LAST_KEYS%%29%0D%0A%0D%0A%23%23%23%23%20System%20Info%0A-%20OS:%20windows-nt%0A-%20Emacs:%2025.0.91.1%0A-%20Spacemacs:%200.105.11%0A-%20Spacemacs%20branch:%20master%20%28rev.%2093e55bb%29%0A-%20Distribution:%20spacemacs%0A-%20Editing%20style:%20hybrid%0A-%20Completion:%20helm%0A-%20Layers:%0A%60%60%60elisp%0A%28auto-completion%20emacs-lisp%20org%20spell-checking%20syntax-checking%29%0A%60%60%60%0A%0D%0A%0D%0A%23%23%23%23%20Backtrace%0D%0A%60%60%60%0D%0ABACKTRACE%20IF%20RELEVANT%0D%0A%60%60%60%0D%0A`

**Comment by danielyang1009** [comment]
I feel like maybe it's a problem with org-bullet

**Comment by wigust** [comment]
I'm having the same problem.

**#+STARTUP: latexpreview** doesn't work well.

Latex fragments at the begging of the document **without headings are working**.
But if I add a heading, then latex fragment will not render.

![screenshoot](https://i.imgur.com/aVRxy6f.png)
