### ISSUE TITLE
<ESC> sometimes confirms in magit with helm

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#5329]
#### Description

Sometimes, when using `<ESC>` to exit from a magit command that is being completed with helm, the command executes instead, with whatever the current default selection is.

Unfortunately, I don't have a good way to reproduce it.  I've been experiencing it for a while now on both OSX and Linux, across a full package purge, so something's wrong.
#### Reproduction guide
- Start Emacs
- Open magit in a sacrificial repository with at least two branches and a clean working tree.
- `b b` to start checkout different branch
- `<ESC>` to cancel helm completing.

_Observed behaviour:_
Magit switches branches.

_Expected behaviour:_
Action is canceled.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: mu4e-complete (rev. a17952e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults spell-checking syntax-checking semantic typography
 (chrome :variables edit-server-new-frame nil)
 elfeed finance gtags ibuffer mu4e org
 (shell :variables shell-default-shell 'shell shell-default-term-shell
        (getenv "SHELL")
        shell-default-height 50)
 spacemacs-layouts prodigy restclient version-control git c-c   emacs-lisp go html javascript latex lua markdown python ruby shell-scripts sql yaml mir-bbdb mir-magit-annex mir-pass mir-remind-to-diary mir-rc mir-rc-org mir-rc-qualia mir-rc-mail)
```

**Comment by TheBB** [comment]
Huh, that's really funky. `C-g` definitely works better as a cancellation key so you might do well to train yourself to use it.

**Comment by darkfeline** [comment]
Trying out this new ivy package.  It "feels" a lot less buggy than helm, and so far I haven't experienced this bug yet.  I'm curious as to why this current Heisenbug happens, but if Spacemacs eventually adopts ivy over helm I have no qualms either.
