### ISSUE TITLE
Comma operator in LaTeX-mode

### ISSUE THREAD

**Issue by legendre6891** [syl20bnr/spacemacs#533]
In LaTeX mode, the usual comma operator in vim is replaced with another `<leader>`-like functionality. How can I restore the usual comma operator behavior?

**Comment by syl20bnr** [comment]
You can try to set `dotspacemacs-major-mode-key` to `nil` ?
https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template#L46

If it does not work, change it to something else.

**Comment by legendre6891** [comment]
Ah sorry, I did not see that option in `.spacemacs`. Thanks!
