### ISSUE TITLE
magit-status fails with "Unknown upattern `(quote magit-log-mode)'"

### ISSUE THREAD

**Issue by brabalan** [syl20bnr/spacemacs#5333]
#### Description
When starting magit-status I get the error `pcase--u1: Unknown upattern `(quote magit-log-mode)'`

#### Reproduction guide
- Start Emacs
- Go to a git directory
- `SPC g s`

*Observed behaviour:*
I get an error.

*Expected behaviour:*
`magit-status` starts.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'cycle)
 elfeed emacs-lisp finance git gnus javascript latex ocaml org
 (spell-checking :variables spell-checking-enable-auto-dictionary t))
```

#### Backtrace
```
  signal(error ("Unknown upattern `(quote magit-log-mode)'"))
  error("Unknown upattern `%s'" (quote magit-log-mode))
  pcase--u1(((match major-mode quote magit-log-mode)) #[257 "\302\301\242>\204

**Comment by fbergroth** [comment]
Fixed in https://github.com/magit/magit/commit/637f771893ed3b59036c7f1de687362343da97ba

**Comment by brabalan** [comment]
I updated the packages and everything works now.
