### ISSUE TITLE
Resuming vanilla describe-foo with ivy does not work

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#5335]
## To reproduce

With spacemacs-ivy layer:
`C-h v` to call `describe-variable`
`C-g` to cancel
`spc rl` to resume ivy completion
select any candidate, and the action will do nothing.

The same process called with `spc hdv` rather than `C-h v` works as intended.

PR incoming :)

**Comment by justbur** [comment]
I think this could actually be considered a bug in ivy, since `ivy-resume` does not seem to be restoring the correct state. @abo-abo what do you think?

`SPC hdv` and `C-h v` are bound to different functions at the moment. So it's not "incorrect" that the two commands behave differently.

**Comment by sooheon** [comment]
Yep, and I thought it'd be simpler just to remap all instances of `describe-foo` with the counsel equivalent, at least on our end.

**Comment by justbur** [comment]
I'm not sure that's a great solution though, because at some point we may want to allow helm and ivy to be used together and that would complicate things.

**Comment by sooheon** [comment]
Ah that's a good point. Enough to nix the current pr, at least.

**Comment by justbur** [comment]
@abo-abo To clarify, `SPC hdv` is bound to counsel-describe-variable, while `C-h v` is unchanged from the default. It seems that after ivy is triggered using completing-read, `ivy-resume` is not restoring the state properly (maybe it's not intended to here?).

**Comment by abo-abo** [comment]
@justbur It's intended. It's mentioned in [the manual](http://oremacs.com/swiper/#counsel-commands) that the non-counsel commands can do very little, basically just what the default completion can do.

This is related to a limitation in `completing-read` interface and can't be solved until that interface is upgraded. The same limitation applies to `helm-mode` and other back ends, I assume.

I suggest trying to use an `ivy-read` equivalent where possible to get all the features mentioned in the manual.

**Comment by justbur** [comment]
@abo-abo Thanks for the clarification. 

If I understand right, `ivy-resume` after a completing-read will set up a ivy session that will do nothing, correct? Is it not possible to detect that situation and refuse to set up the ivy session, maybe just with a message that says "The last ivy session cannot be resumed"?

**Comment by justbur** [comment]
@sooheon I expanded on your pr a little [here](https://github.com/abo-abo/swiper/pull/414)
