### ISSUE TITLE
Support org links with avy-open-url

### ISSUE THREAD

**Issue by pschorf** [syl20bnr/spacemacs#5338]
If I have an http/https link in an org link, e.g. [[my site][http://example.com]], there are two issues:

1. avy-open-url doesn't show it as a match
2. browse-url-at-point opens the text of the link as a url, not the link itself. org-agenda-open-link correctly opens the link.

Do you think it's desirable to support this with something generic like avy-open-url? Or should we write something similar but org-mode specific since the regex and open function will be different.

I'm happy to investigate either option based on what seems preferable.

**Comment by nixmaniack** [comment]
`SPC x o` which is bound to (`link-hint-open-link`) does detect such urls. Not sure about `avy-open-url`

Might be a mistake but just pointing out org links are of the form `[[link][description]]` and not the way you've described.

**Comment by pschorf** [comment]
`SPC x o` is bound to `avy-open-url` for me (version 0.105.12.) I don't seem to have link-hint installed. Is it in a separate layer?

**Comment by pschorf** [comment]
Nevermind, I just installed the package and bound the key. Works great! Thanks very much.

**Comment by StreakyCobra** [comment]
@pschorf `SPC x o` has been replaced by `link-hint` in `develop`, you'll get the change with the next major release :-)
