### ISSUE TITLE
helm describe-variable no longer functional

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#5344]
#### Description
Many helm functions are no longer functional.

#### Reproduction guide
- Start Emacs
- Type `SPC h d v`, choose `dotspacemacs-active-transparency`
- Press RET
- All you see in `*Messages*` is "Quit"

This happens if you type `M-m : describe-variable RET` as well.

*Observed behaviour:*
All you see is "Quit" in `*Messages*`

*Expected behaviour:*
I expect the function to actually work

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.12
- Spacemacs branch: develop (rev. 41e8a28)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(unscroll auto-completion xkcd emacs-lisp git dash yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors spacemacs-layouts vimscript spacemacs-helm
          (c-c   :variables c-c  -enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by StreakyCobra** [comment]
This has been reported upstream: https://github.com/emacs-helm/helm/issues/1414

**Comment by StreakyCobra** [comment]
For now, the only workaround is to use the `[Rollback package update]` button on the `*spacemacs*` buffer to go back to cancel last update and restor the previous `helm` version.

BTW **do not** delete your `.emacs.d` folder, especially not the `.emacs.d/.cache` folder as you **won't be able anymore to rollback to a working version**.

**Comment by TheBB** [comment]
This has been fixed upstream.
