### ISSUE TITLE
Executing Emacs commands through Helm does nothing

### ISSUE THREAD

**Issue by dbmikus** [syl20bnr/spacemacs#5346]
#### Description

Any Emacs command that I execute through Helm results in a no-op. These are the `SPC :` commands, not `SPC <key1> <key2> ...` commands.

#### Reproduction guide
- Start Emacs
- Open up a junk file with `SPC f J`. Use any extension. I used ".js".
- Insert text `var foo = "bar";` to confirm js-mode is on with syntax highlighting
- Type `SPC :` and type "text-mode" at prompt to change to text-mode. Nothing happens
- Type `M-:` and enter `(text-mode)` at prompt. Mode successfully changes

*Observed behaviour:*

Commands run through Helm prompt should work. In this case, typing in a command to change the major mode does not change the major mode.

*Expected behaviour:*

I would expect commands to successfully run. In this specific example case, I should be able to change the major-mode.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.12
- Spacemacs branch: master (rev. 531ec8e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git html markdown org php scala puppet ruby-on-rails spell-checking syntax-checking)
```

#### Backtrace

No relevant backtrace.

**Comment by dbmikus** [comment]
Whoops. Repeat of #5344. Closing as duplicate.

**Comment by StreakyCobra** [comment]
Thanks for the reporting. This has already been reported in https://github.com/syl20bnr/spacemacs/issues/5344. Closing as duplicate then :-)

**Comment by d12frosted** [comment]
Ah, just wanted to say it!

**Comment by StreakyCobra** [comment]
Haha, closed before I had a chance to do it.
