### ISSUE TITLE
Package :toggle is ignored

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#5347]
#### Description
`:toggle` entry in a package specification in a layer's package list is ignored. PR incoming.

#### Reproduction guide
- in `+layers/spacemacs-base/packages.el`, in `spacemacs-base-packages`, change this line:
```elisp
evil-escape
```
to:
```elisp
(evil-escape :toggle (= 0 1))
```
- start a new emacs instance

*Observed behaviour:*
`evil-escape-mode` is enabled

*Expected behaviour:*
`evil-escape-mode` is not defined

**Comment by TheBB** [comment]
Introduced and fixed in develop.
