### ISSUE TITLE
can't run command

### ISSUE THREAD

**Issue by huaoguo** [syl20bnr/spacemacs#5352]
#### Description
When I press M-x, the helm commands popup show. Then I type any command(such as quit-window) then press RET(enter), then it just show 'Quit' in bottom and nothing happened, just like I press ESC.

#### Reproduction guide
- Start Emacs
- M-x
- type quit-window or install-package or any other command
- press RET

*Observed behaviour:*
show Quit and nothing happended

*Expected behaviour:*
run the command

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.12
- Spacemacs branch: master (rev. 531ec8e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

#### Backtrace
```
no error message
```

**Comment by izahn** [comment]
Update your packages.

**Comment by huaoguo** [comment]
@izahn Thanks! This solved my problem.
