### ISSUE TITLE
Odd behaviour of evil-surround-region in visual line mode

### ISSUE THREAD

**Issue by fivethousand** [syl20bnr/spacemacs#5358]
#### Description
evil-surround-region behaviour has changed for visual line mode

#### Reproduction guide
- start Emacs
- write a couple of lines, (for example qwe, asd, zxc)
- select lines, press s (or S, whatever maps to evil-surround-region), press {

*Observed behaviour:*
{qwe
asd
zxc}

*Expected behaviour:*
{
qwe
asd
zxc
}

For visual and visual block mode, the observed behaviour is expected and correct, for visual line mode it is wrong imho. This has changed recently, before it did work as expected.

Is this a spacemacs issue or should we report it upstream?

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.12
- Spacemacs branch: master (rev. 531ec8e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t)
 emacs-lisp markdown org syntax-checking version-control themes-megapack latex python c-c   semantic shell)
```

**Comment by StreakyCobra** [comment]
I reproduced this on a stock Emacs with just `evil` and `evil-surround` installed, i.e.:

- `SPC q D` then `evil,evil-surround` then `RET`
- This restart emacs without spacemacs with just `evil` and `evil-surround` installed
- `M-x evil-mode RET` to enable the `evil` mode
- Reproduced the steps you provide, same behaviour

So this should be reported upstream, either in `evil` or `evil-surround`, I don't know.

**Comment by fivethousand** [comment]
Thanks.
Could you.... should I....? ;-)

**Comment by StreakyCobra** [comment]
I don't have time to dig further, so, feel free :-)

**Comment by JAremko** [comment]
Don't go there. They are asking for PR's :smile:

**Comment by fivethousand** [comment]
Done.
https://github.com/timcharper/evil-surround/issues/71

**Comment by fivethousand** [comment]
Unfortunately, noone seems to care there. Am I really the only one extremely annoyed by this change? How do others create a new block, e.g. transform
```
foo;
bar;
```
to
```
{
  foo;
  bar;
}
```
?

**Comment by fivethousand** [comment]
Ok, I identified the commit: https://github.com/timcharper/evil-surround/commit/8b2ca83b7cdc4ef76aa9a1af7797b70d1cb25a5e?diff=unified

After reverting, the correct behavior is back. I would submit a PR, but my elisp skills are too poor to figure out what the intention of the commit were and how I could fix it.
Maybe somebody else wants to chime in?

**Comment by hlissner** [comment]
This has been fixed upstream in timcharper/evil-surround@430c81f

**Comment by StreakyCobra** [comment]
@hlissner Thanks! :-)

**Comment by StreakyCobra** [comment]
Closing this as fixed upstream.

@fivethousand: Let me know if it's not solved for you after having updated your packages.
