### ISSUE TITLE
clojure-snippets broke CIDER

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#5361]
d3833db seems broke cider. it no longer works. [develop] branch

temporary workaround:
add clojure-snippets to excluded-packages

**Comment by TheBB** [comment]
Does it also break cider without the `:toggle`?

**Comment by AlejandroCatalina** [comment]
I have it and I didn't notice anything :O

On Mar 4, 2016 19:11, Eivind Fonn <notifications@github.com> wrote:

Does it also break cider without the :toggle?

**Comment by TheBB** [comment]
I mean if you change the package in the list to read just `clojure-snippets`, does it also break?

IOW, is it because of the `:toggle` keyword or is it the actual package that breaks it?

**Comment by TheBB** [comment]
Maybe this is the problem you're seeing? https://github.com/syl20bnr/spacemacs/issues/5373

I think that's probably it. There's not much code in clojure-snippets that could have broken things in more than one way.

**Comment by TheBB** [comment]
I'm assuming it's the same issue, in which case it's fixed now.
