### ISSUE TITLE
Projectile ag support?

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#5363]
`projectile-ag` depends in `ag`.  `ag` isn't needed for the helm variant, but being able to open a results buffer is sometimes more useful than making repeated helm searches.  So should we support `projectile-ag`?

(Related? https://github.com/syl20bnr/spacemacs/issues/3141)

**Comment by darkfeline** [comment]
Or one could do a helm-projectile-ag search and use `C-x C-s` to open a buffer with the results.   Silly me.

**Comment by a13ph** [comment]
Shows how bad current helm documentation visibility is

**Comment by darkfeline** [comment]
Actually, I think this deserves reconsideration since ivy, being a less ambitious kitchen sink than helm, doesn't have this feature.

**Comment by punchagan** [comment]
Also, given spacemacs is adding `projectile-ag` to the autoload commands list, users would expect it to work?

**Comment by sooheon** [comment]
@darkfeline I'm not sure what behavior you're referring to, as I haven't used projectile-ag, but is it anything like [ivy-occur](http://oremacs.com/2015/11/04/ivy-occur/)? I can call that on in-page search results or in project ag results, anything ivy lists it can print out to a buffer with live links.

**Comment by darkfeline** [comment]
@sooheon Yes, it's like that, but Spacemacs's current ivy project search doesn't support it (`SPC s p` with `spacemacs-ivy`)

**Comment by sooheon** [comment]
@darkfeline It works for me for any ivy instance, including `spc s p`. The binding should be under `C-o o`.

**Comment by darkfeline** [comment]
Okay, it does work, but it performs rather poorly.  It seems like I need to wait for `ivy` to populate all the results first, which takes a lot of time, especially for a large project, otherwise `ivy-occur` gives me a buffer containing:

~~~
-*- mode:grep; default-directory: "<snip>" -*-

2 candidates:
./
./3 chars more
~~~
Running `projectile-ag` or `ag` by itself is much faster.

For comparison, running `projectile-ag` on my large project is almost instant, while `SPC s p` then `C-o o` I need to wait three seconds after `SPC s p`.

**Comment by kain88-de** [comment]
actually it would be nice if this is activated with `ivy` and `counsel-projectile`. It uses just wraps the `counsel-ag` command that is included in `counsel`.
