### ISSUE TITLE
Internal links in DOCUMENTATION.org not work

### ISSUE THREAD

**Issue by fishmacs** [syl20bnr/spacemacs#5366]
The first directory item in document page:
[<a](url) href="/syl20bnr/spacemacs/blob/master/doc/Core Pillars">Core Pillars</a>

correct link should be:
[<a](url) href="/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#core-pillars">Core Pillars</a>

**Comment by punchagan** [comment]
The built documentation is available [here](http://spacemacs.org/doc/DOCUMENTATION.html).  Getting it working on GitHub along with the build may be tricky.

**Comment by TheBB** [comment]
#4399
