### ISSUE TITLE
`org-insert-heading+org-metaright` does newline twice instead of once

### ISSUE THREAD

**Issue by don-han** [syl20bnr/spacemacs#5369]
#### Description
`org-insert-heading+org-metaright` (`M-o`) leaves an empty line in between two headlines. 

#### Reproduction guide
- Start Emacs
- Open org file
- create a headline by `M-RET`
- create a sub-headline by `M-o`

*Observed behaviour:*
There is a gap between two headlines.
![image](https://cloud.githubusercontent.com/assets/5600864/13546102/11da53e4-e258-11e5-9026-80c3598de3c1.png)

*Expected behaviour:*
There shouldn't be any gap between two headlines.
![image](https://cloud.githubusercontent.com/assets/5600864/13546107/1a14aae6-e258-11e5-8cce-3284e1b0f7c1.png)

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.12
- Spacemacs branch: master (rev. 531ec8e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil)
 better-defaults emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control
 (latex :variables latex-enable-auto-fill t)
 themes-megapack python)
```

#### Backtrace
```

```

**Comment by TheBB** [comment]
I can't reproduce this. I get your expected behaviour, with or without my custom org config.

**Comment by StreakyCobra** [comment]
I cannot reproduce here too.

**Comment by don-han** [comment]
Interesting. I disabled the entire `user-config` but the bug still persists. [Here](https://github.com/don-han/dotfiles/blob/master/dotfiles/spacemacs) is my spacemacs dotfile.

**Comment by don-han** [comment]
Hm, the bug appears on some headlines but not on some. It's consistent,but I can't find the pattern. I don't know if this helps, but the most recent things I did outside of config file was install `ispell`and `source code pro`

**Comment by don-han** [comment]
Can you guys try with `C-RET` and `M-o`? That one also gives me double newlines

**Comment by fandag** [comment]
Perhaps something with orgs automatic detection of blank line preference from context? See the faq:

http://orgmode.org/worg/org-faq.html#blank-line-after-headlines-and-list-items

There's a variable you can set to override the auto behaviour... org-blank-before-new-entry

**Comment by don-han** [comment]
@fandag Thanks! That seems to be it.

**Comment by nhmacuk** [comment]
Did the behaviour change in between your latest post and today? The behaviour I am observing today in the developer version of spacemacs 26.1 for M-o in orgmode is opening the "facemap menu" instead of org-insert-heading+org-metaright as described in http://spacemacs.org/layers/+emacs/org/README.html .

**Comment by duianto** [comment]
The org layers documentation for the develop branch is here:
http://develop.spacemacs.org/layers/+emacs/org/README.html

And here's the org section of the changelog.develop:
https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop#org

**Comment by nhmacuk** [comment]
Thanks mate! That explains a lot :)
