### ISSUE TITLE
Unable to activate package `evil-anzu'.

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#537]
Updating to anzu 20150203.708, with the latest spacemacs results in the following error on startup.
```
Warning (emacs): Unable to activate package `evil-anzu'.
Required package `anzu-0.46' is unavailable
```

**Comment by syl20bnr** [comment]
I updated to this version and I don't have this error.
Recommendation: wipe out elpa directory and restart emacs.

What is your version of Emacs ?

**Comment by sooheon** [comment]
I will go ahead and close this, wiping out elpa fixed it.
