### ISSUE TITLE
Snippets acting strangely

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#5373]
This is a weird problem that I and @WillianPaiva have seen on gitter, and which @kRITZCREEK has seen [here](https://github.com/syl20bnr/spacemacs/pull/5368).

Upon starting Emacs and opening a file at `/some/path/to/file`, yasnippet tries to load snippets from the folder `/some/path/to/snippets/`. This folder doesn't exist, typically, which produces an error and which means that some of the hook functions that should run do not. The result is that many minor modes that are expected will not be switched on.

Some things I have noted:
- The spurious path **is** added to `yas-snippet-dirs` but not by Spacemacs, at least not during the yasnippet loading. When [this](https://github.com/TheBB/spacemacs/blob/fix-ensime/layers/auto-completion/packages.el#L250-L252) function runs the value of `yas-snippet-dirs` is okay. After the error has happened, it is not.
- The exact error is something along the lines of `File mode specification error: (file-error "Opening directory" "no such file or directory" "/home/eivindf/.emacs.d/snippets")`. As far as I know yasnippet should not produce such an error when a folder does not exist, it should merely warn about it and continue on. However no such warnings are produced.
- The error is produced on every file I open thereafter, but the value of `yas-snippet-dirs` does not change (i.e. it always complains about the same path, which depends only on the first file I open).
- If the first file I open happens to yield a spurious path that actually exists, nothing bad happens and I can use Spacemacs as normal.
- I've been unable to find where the error is thrown and to produce a backtrace.
- It is 100% reproducible on my work computer, with a fresh checkout and updated packages (including a clean cache).

**Comment by TheBB** [comment]
This is due to the clojure layer. It's the new snippets package that's creating problems.

**Comment by kRITZCREEK** [comment]
I can confirm! Disabling the clojure layer "fixes" it for me. Quote on quote because I'd like to use the clojure layer :D

**Comment by TheBB** [comment]
I made a PR to fix it https://github.com/mpenet/clojure-snippets/pull/7.

For now you can work around it by adding `clojure-snippets` to your list of excluded packages. There's no need to disable the whole clojure layer.
