### ISSUE TITLE
use private layers to customise layers?

### ISSUE THREAD

**Issue by xiaoxinghu** [syl20bnr/spacemacs#5375]
I really like the concept of layer. But sometimes it doesn't feel exactly right. E.g. I have tons of customisation on org-mode. You can't expect a "right" config for everyone in terms of org-mode. And it is too big to be in `.spacemacs` file. So I created my own layer for it. But it is not exactly a new module. It is a big customisation on an existing one -- the org layer. I assume for now the private layer is the best way of doing this. Am I right? I am expecting a mechanism to customise a layer. Maybe it is redundant design since the purpose of layer is to customise. Thoughts?

**Comment by StreakyCobra** [comment]
User configuration should be called in `user-config`, but it doesn't have to be in the `.spacemacs` file, if it is too big you can move related configurations to another file. For instance you can create a `my-org-config.el` with all you org-related tweaks, and then add this line to your `user-config` function:

      (load-file "my-org-config.el")

Using a layer is another, but heavier, solution.

**Comment by xiaoxinghu** [comment]
@StreakyCobra Excellent! Just what I wanted. One small question though. If I use the `load-file` method, can I use the existing package management feature for a layer? Like auto install, lazy loading etc. (given that I need to use additional packages). Or should I use `dotspacemacs-additional-packages`. For example `ox-reveal` for creating slides from org files.

**Comment by sooheon** [comment]
You can also create more than one private layer, so you can just split it out into xxh-org layer, for example.

**Comment by nixmaniack** [comment]
I would just add one more point to @StreakyCobra's suggestion. I do use `(load-file "my-org-config.el")` but I also add `with-eval-after-load` so I don't load all configs right at startup.

**Comment by StreakyCobra** [comment]
@xiaoxinghu Using and loading another file is for structuring your code. For the lazy loading part, you can use the same mechanism as used in the layers, i.e. `with-eval-after-load` for configuring already existing packages without forcing them to load. (as @nixmaniack suggested), or `(use-packages …` deferring capabilities for installing and lazy loading packages.

**Comment by d12frosted** [comment]
Closing this issue for being inactive. Also discussions contain possible solution. Also, there is somewhat [outdated answer for exact question](http://emacs.stackexchange.com/questions/22338/spacemacs-move-org-mode-customization-to-separate-file/22441#22441).
