### ISSUE TITLE
spacemacs/search-project-auto-region-or-symbol - counsel vs helm-ag - escaping

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#5378]
#### Description
`SPC s P` which is bound to `spacemacs/search-project-auto-region-or-symbol` when using ivy doesn't escape special chars(`* |` etc). 

#### Reproduction guide
- Start Emacs
- Place a point on a word containing special char e.g. `spacemacs|hide-lighter`
- Hit `SPC s P`

*Observed behaviour:*
word `spacemacs|hide-lighter` is selected without escaping of `|`

*Expected behaviour:*
word `spacemacs|hide-lighter` should have escaped `|` i.e `spacemacs\|hide-lighter`

The expected behaviour is observed while using helm.

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.12
- Spacemacs branch: develop (rev. a8bd6dc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(spacemacs-ivy better-defaults markdown org auto-completion spell-checking syntax-checking semantic
               (version-control :variables version-control-diff-tool 'diff-hl)
               git github eyebrowse emacs-lisp ruby ruby-on-rails python
               (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

#### Backtrace
```
BACKTRACE IRRELEVANT
```

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
