### ISSUE TITLE
Hybrid Mode Copy/Paste on Mac

### ISSUE THREAD

**Issue by spattersongt** [syl20bnr/spacemacs#5391]
In insert mode using Hybrid mode, Meta-V (Command-V on my Mac) scrolls up.  Is there a setting to turn this into Paste?

**Comment by d12frosted** [comment]
Using `osx` layer is a good starting point. But since you have `cmd` bound to `meta` you'll have to switch from `cmd` to `option`.

But you can also bind `M-v` to save :D

**Comment by nixmaniack** [comment]
Have you enabled `osx` layer?

**Comment by spattersongt** [comment]
Oh that's perfect.  Thanks!
