### ISSUE TITLE
--resume-layout error

### ISSUE THREAD

**Issue by disberd** [syl20bnr/spacemacs#5394]
#### Description
--resume-layout option gives unkown option error

#### Reproduction guide
- Start Emacs
- restart with resume layout with SPC q r

*Observed behaviour:*
emacs is restarted but the error projectile-project-root: Unknown option `--resume-layouts'
is thrown and the previously present layouts are not resumed

*Expected behaviour:*
layouts prior to restarting should be resumed

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.13
- Spacemacs branch: master (rev. 2c3e6b4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh")
                 syntax-checking version-control semantic unimpaired latex extra-langs eyebrowse c-c   ranger fasd)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by StreakyCobra** [comment]
I just reproduced it on `master` with my exact same config as on `develop` where it is working.

**Comment by syl20bnr** [comment]
Backported in 0.105.19
