### ISSUE TITLE
ESS layer help.start makes inferior ess read-only

### ISSUE THREAD

**Issue by izahn** [syl20bnr/spacemacs#5395]
#### Description

Starting an R repl and opening the help system in a browser makes the inferior-ess buffer read-only.
#### Reproduction guide
- Start Emacs
- `SPC a'` `R <ret>` to start an R repl (requires ess layer)
- At the R prompt type `help.start()` to launch R help in a browser
- Click on a link in the browser, e.g., "Packages".

_Observed behaviour:_
In the inferior ess buffer I see

```
> help.start()
starting httpd help server ... done
If the browser launched by '/usr/bin/xdg-open' is already running, it
    is *not* restarted, and you must switch to its window.
Otherwise, be patient ...
> 
Making 'packages.html' ... done
```

(which is expected), but further input is impossible. Any attempt to type in the inferior ess buffer results in `Text is read-only` being echoed in the minibuffer.

_Expected behaviour:_
The R repl should be usable after starting the help system in R.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.13
- Spacemacs branch: develop (rev. 895455d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:

``` elisp
(spacemacs-ivy auto-completion command-log emacs-lisp ess octave python sql latex git markdown org pdf-tools pandoc
               (shell :variables shell-default-height 35 shell-default-position 'bottom shell-default-shell 'multi-term)
               (mu4e :variables mu4e-headers-include-related t mu4e-headers-skip-duplicates t mu4e-headers-fields
                     '((:human-date . 12)
                       (:flags . 6)
                       (:mailing-list . 10)
                       (:from-or-to . 22)
                       (:thread-subject))))
(spacemacs-ivy auto-completion command-log emacs-lisp ess octave python sql latex git markdown org pdf-tools pandoc
               (shell :variables shell-default-height 35 shell-default-position 'bottom shell-default-shell 'multi-term)
               (mu4e :variables mu4e-headers-include-related t mu4e-headers-skip-duplicates t mu4e-headers-fields
                     '((:human-date . 12)
                       (:flags . 6)
                       (:mailing-list . 10)
                       (:from-or-to . 22)
                       (:thread-subject))))
```
#### Backtrace

No error is triggered, so no backtrace.

**Comment by izahn** [comment]
I can also reproduce this on the latest released version of spacemacs, i.e.,

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.13
- Spacemacs branch: master (rev. 2c3e6b4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(spacemacs-ivy auto-completion command-log emacs-lisp ess octave python sql latex git markdown org pdf-tools pandoc
               (shell :variables shell-default-height 35 shell-default-position 'bottom shell-default-shell 'multi-term)
               (mu4e :variables mu4e-headers-include-related t mu4e-headers-skip-duplicates t mu4e-headers-fields
                     '((:human-date . 12)
                       (:flags . 6)
                       (:mailing-list . 10)
                       (:from-or-to . 22)
                       (:thread-subject))))
```

**Comment by izahn** [comment]
OK, I've narrowed it down to an interaction with the `shell` layer. Without the shell layer enabled it works fine, with the shell layer enabled I have this problem. Digging in to the shell layer code now.

**Comment by izahn** [comment]
The `shell` layer sets `comint-prompt-read-only` to a non-nil value, which is enough to reproduce the problem after loading `ess-site` after starting with `emacs -q`. I've reported this upstream at https://github.com/emacs-ess/ESS/issues/300 but will leave this open pending a response from the ESS developers.

**Comment by StreakyCobra** [comment]
:+1: :-)

**Comment by jackkamm** [comment]
This same issue make it impossible to kill a `shinyApp()` running in ESS -- trying to send the kill signal with `C-c C-c` just results in the message `Text is read-only` in the minibuffer. The line `(setq comint-prompt-read-only t)` that @izahn identified in the `shell` layer causes the problem.

There is a solution in a comment on the corresponding issue page for ESS (https://github.com/emacs-ess/ESS/issues/300#issuecomment-231314374), to add the following to`inferior-ess-mode-hook`:
```
(setq-local comint-use-prompt-regexp nil)
(setq-local inhibit-field-text-motion nil)
```

I will submit this as a PR to the ess layer.
