### ISSUE TITLE
Cannot `git commit` using magit.

### ISSUE THREAD

**Issue by exaos** [syl20bnr/spacemacs#5404]
I can stash, add and watch logging, but fail to execute `git commit` using magit. I run spacemacs with `emacs --daemon`, and use `emacsclient`. Here is the error message:

```
*ERROR*: Wrong type argument: processp, nowait
error: There was a problem with the editor '/usr/sbin/emacsclient --socket-name=/tmp/emacs1001/server'.
Please supply the message using either -m or -F option.
```

**Comment by robbyoconnor** [comment]
Do you have git installed?

**Comment by robbyoconnor** [comment]
I'm not having issues with the latest `develop` so i'm suspecting this is a problem with your setup

**Comment by StreakyCobra** [comment]
You can maybe try to update your packages if not already done recently.

**Comment by exaos** [comment]
1. Git works fine in terminal.
2. Packages are all updated to the latest.

**Comment by sooheon** [comment]
Can you replicate issue with `emacs -Q` then initializing only magit? See if you can distinguish if its a spacemacs config issue or something else.

**Comment by StreakyCobra** [comment]
> Can you replicate issue with emacs -Q then initializing only magit? See if you can distinguish if its a spacemacs config issue or something else.

Quick how to:

- `SPC q D` then enter `magit` then `RET`
- This will restart stock emacs with just `magit` loaded
- `M-x magit-status RET`
- And try to commit from there (`?` in magit status window to have the help if needed).

**Comment by sooheon** [comment]
`SPC q D` just blew my mind. I feel like a caveman for having actually gone through package-initialize, etc.

**Comment by StreakyCobra** [comment]
@sooheon It's quite recent and went to master silently ;-)

**Comment by exaos** [comment]
If I invoke emacs directly, `magit` works fine. If I run emacs in daemon mode and start an emacsclient, then `magit` cannot commit. It must be something due to `emacsclient` and daemon mode. I have previous emacs settings using emacs-starter which works fine with daemon mode.

**Comment by exaos** [comment]
More detail:
- OS: Arch Linux
- Desktop: GNOME
- Emacs: 24.5.1
Hope it is not an environment-related issue.

**Comment by StreakyCobra** [comment]
Probably not, I'm on Archlinux, with the distribution's version of Emacs. I'm using i3 instead of gnome, but this shouldn't be related.

**Comment by ratheesh** [comment]
I am to able to see this issue if I start emacs with
`$ emacsclient -nc -a ""`

But If I start emacs with
`$ emacsclient -c -a ""`
this issue is not seen. I think magit is calling emacsclient in detached mode.

My EDITOR and GIT_EDITOR variable is set to `emacsclient -c -a ""`. magit does not
seem to take this.

I am on latest develop branch.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 00d13b4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion
 better-defaults emacs-lisp
 (git :variables git-magit-status-fullscreen t)
)
```

**Comment by ratheesh** [comment]
@exaos 
I tried removing **.cache** in **~/.emacs.d ** and restarted Emacs, It is working fine.
You can try this to check if it works for you as well.

**Comment by exaos** [comment]
Thanks. I do start emacsclient as `-nc -a`.

**Comment by exaos** [comment]
@ratheesh 
It is confirmed that this issue stays with `emacsclient -nc` but not `emacsclient -c`. Removing `.cache` doesn't help. So, I need to change the `Exec` line within `emacsclient.desktop`.

**Comment by mcg** [comment]
This just hit me today, seems like an upstream issue https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815067

**Comment by Stebalien** [comment]
@mcg For me, rolling back the persp-mode update fixed it so I don't think this is related to magit.

**Comment by Stebalien** [comment]
Commit: 859f28473b9e9d9535fcaab046ad67688c6e5a28

**Comment by mcg** [comment]
Thanks @Stebalien ran a full update, hit the error again. Reverted persp-mode and it's gone.

**Comment by Stebalien** [comment]
@mcg I've reported a bug (#5867)

**Comment by osmanmesutozcan** [comment]
For me, works when I save and then quit the editor using `:exit`

In my case commit editor was vim and I use spacemacs in evil mode. so there was some sort of a conflict.

**Comment by ChShersh** [comment]
> So, I need to change the Exec line within emacsclient.desktop

@exaos Could you please provide more details on that? What should I do if I don't have `emacsclient.desktop` file? I have only `emacs24.desktop` in `/usr/share/applications/`. And I have no idea how to use your solution for this problem :disappointed:
