### ISSUE TITLE
 Move the spacemacs badge to the spacemacs.org 

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#5409]
I think we can move [![Built with Spacemacs](https://cdn.rawgit.com/syl20bnr/spacemacs/442d025779da2f62fc86c2082703697714db6514/assets/spacemacs-badge.svg)](http://github.com/syl20bnr/spacemacs) and it's link to [spacemacs.org](http://spacemacs.org) so the web site will get more search engine love.  

For html:
```html
<a href="http://spacemacs.org">
<img src="http://spacemacs.org/img/spacemacs-badge.svg" />
</a>
```

Im not sure how popular spacemacs badges are, 
but I think it won't hurt https://github.com/syl20bnr/spacemacs  too much, while it should be a meaningful improvement for the site.

The only problem that I see is that spacemacs.org doesn't work via https and it will make badges less popular. But the site should have ssl anyway. [In 2016..](https://letsencrypt.org/)

**Comment by syl20bnr** [comment]
Good idea but why `move` and not `add` ?

**Comment by syl20bnr** [comment]
Oh I understand, this is about the link :-)

Indeed :+1:

**Comment by JAremko** [comment]
I decided to only changed the link.

**Comment by JAremko** [comment]
> syl20bnr changed the title from Move the spacemacs badge to the spacemacs.org to Move the spacemacs badge to the spacemacs.org

O_o

**Comment by JAremko** [comment]
How about that title

![](http://www.minecraftserver.com/forum/attachments/fyeah-png.3387/)
