### ISSUE TITLE
Status line disappeared when clicking in edit pane

### ISSUE THREAD

**Issue by lufeihaidao** [syl20bnr/spacemacs#5414]
![image](https://cloud.githubusercontent.com/assets/1731864/13624268/81e5156a-e5e7-11e5-841f-f6ab2ca9c9bb.png)

When I focus on it:

![image](https://cloud.githubusercontent.com/assets/1731864/13624273/8c5194a6-e5e7-11e5-8caf-d5725aebbadc.png)

**Comment by TheBB** [comment]
Please paste the error you get in the messages buffer.

**Comment by lufeihaidao** [comment]
Error during redisplay: (eval (spaceline--prepare spaceline-left spaceline-right)) signaled (void-variable spacemacs-mode-line-new-version-lighterp)

**Comment by TheBB** [comment]
What's your Spacemacs version? We fixed this i 0.105.2. The latest release is 0.105.14.

**Comment by lufeihaidao** [comment]
@TheBB Yes! It works now in 0.105.14
