### ISSUE TITLE
restart-emacs-resume-layouts function doesn't restore window size

### ISSUE THREAD

**Issue by jsonify** [syl20bnr/spacemacs#5416]
#### Description

The `restart-emacs-resume-layouts` function will resume the contents of the buffer I'm working in when I run this function, but the window size goes back to the standard default size, even though I have changed the window size to be larger.
#### Reproduction guide
- Start Emacs
- go to a Recent File
- change the window size
- invoke the `SPC q r` function 

_Observed behaviour:_
After restart, the file that I was working in is restored, but my window size has opened to the default size.

_Expected behaviour:_
I was expecting that upon this restore layouts function, that both the previously opened files would appear as well as the window size would have opened to the newly adjusted size that I set it to.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.13
- Spacemacs branch: fix/restart-emacs-resume-layouts (rev. 895455d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
```

**Comment by StreakyCobra** [comment]
Relevant comment to implement this: https://github.com/syl20bnr/spacemacs/issues/5095#issuecomment-184900782

**Comment by LukeXuan** [comment]
I've experience exactly the same problem, any progress?

**Comment by xged** [comment]
After I change window size and restart Emacs, it freezes under `emacs --resume-layouts` command. And yes, 'new' Emacs does not restore window size.

**Comment by xged** [comment]
@jsonify Is your Emacs on *fullscreen*?
