### ISSUE TITLE
layer/post-init-package function breaks some hooks and lazy initialisation

### ISSUE THREAD

**Issue by d12frosted** [syl20bnr/spacemacs#5417]
Just noticed a strange behaviour of `elfeed` layer. It uses `elfeed-goodies` package and configures it using `spacemacs|use-package-add-hook` function. 

```
(defun elfeed/init-elfeed-goodies ()
  (use-package elfeed-goodies
    :commands elfeed-goodies/setup
    :init (spacemacs|use-package-add-hook elfeed
            :post-config (elfeed-goodies/setup))))
```

So far it works nice. But when I try to add some configurations to `elfeed` in my private layer `(elfeed-goodies/setup)` is not called while my private configurations are executed. 

```
(defun private-layer/post-init-elfeed ()
  (use-package elfeed
    :config
    ;; do configs
))
```

I believe it's a bug.

**Comment by d12frosted** [comment]
Also I've noticed another thing. 

```
(defun private-layer/post-init-elfeed ()
  (use-package elfeed
    :config
    (message "Hello")
))
```

Forces `elfeed` to load on startup. So probably title of this issue is misguiding.

**Comment by d12frosted** [comment]
And here is result of `SPC h d s`:

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.13
- Spacemacs branch: develop (rev. 895455d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion :disabled-for org)
 better-defaults colors dash
 (deft :variables deft-directory
   (concat d12-path/dropbox "Apps/deft"))
 (elfeed :variables rmh-elfeed-org-files 'nil)
 emoji eyebrowse
 (git :variables git-magit-status-fullscreen t)
 github
 (org :variables org-enable-github-support t org-bullets-bullet-list
      '("◉" "○" "✿" "❀" "✸"))
 pandoc ranger restclient syntax-checking spacemacs-layouts spacemacs-helm spell-checking
 (shell :variables shell-default-term-shell "/usr/local/bin/fish")
 version-control no-dots d12frosted-core d12frosted-org
 (csharp :variables omnisharp-server-executable-path "~/Developer/Other/omnisharp-roslyn/artifacts/build/omnisharp/omnisharp")
 emacs-lisp erlang
 (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "chris-done" haskell-tags-on-save nil haskell-process-log t haskell-process-reload-with-fbytecode nil haskell-process-use-presentation-mode t haskell-process-suggest-remove-import-lines nil haskell-process-suggest-hoogle-imports nil haskell-interactive-mode-include-file-name nil haskell-interactive-mode-eval-pretty nil haskell-process-suggest-haskell-docs-imports nil)
 (html :variables web-mode-markup-indent-offset 2 web-mode-attr-indent-offset 2 web-mode-code-indent-offset 2 web-mode-css-indent-offset 2 web-mode-sql-indent-offset 2 css-indent-offset 2)
 (javascript :variables js-indent-level 2 js2-basic-offset 2)
 lua markdown python ruby shell-scripts yaml react)
```

**Comment by TheBB** [comment]
Indeed,

1. Elfeed runs its `init-elfeed` function. It defers the loading of elfeed and will run `use-package--elfeed--post-config-hook` when it loads.
2. Your layer runs its `post-init-elfeed` function. It triggers the loading of elfeed and thus runs the hook (which is empty).
3. Elfeed runs its `init-elfeed-goodies` function, which adds a function to the hook, which will now never be run.

To fix this, change your `post-init-elfeed` function so that it does not trigger elfeed to be loaded, or alternatively we change the elfeed-goodies to use more conventional means of loading.

**Comment by TheBB** [comment]
Use-package will load the package unless you explicitly defer it `:defer t` or implicitly with `:commands`, `:mode` or something similar.

**Comment by d12frosted** [comment]
> Use-package will load the package unless you explicitly defer it :defer t or implicitly with :commands, :mode or something similar.

You're fast - answered my new question. So it seems that I just forgot to defer :/ Makes sense. Thanks for help.

**Comment by d12frosted** [comment]
> or alternatively we change the elfeed-goodies to use more conventional means of loading.

What is more conventional? Calling `elfeed-goodies/setup` (which is exported via `commands`) in `elfeed`'s `config` section?

**Comment by TheBB** [comment]
No, this:

```elisp
(defun elfeed/init-elfeed-goodies ()
  (with-eval-after-load 'elfeed
    (require 'elfeed-goodies)
    (elfeed-goodies/setup)))
```

**Comment by d12frosted** [comment]
Ah, that straightforward :)

> Use-package will load the package unless you explicitly defer it :defer t

BTW, I thought that it's deferred by default. Makes me rethink some of my configs :smile_cat:
