### ISSUE TITLE
eshell clear leaves a line at top

### ISSUE THREAD

**Issue by joshcho** [syl20bnr/spacemacs#5419]
Entering clear leaves a line on top of eshell.

Reproducible by:
fresh install
enable shell layer
:eshell
type clear RET

![image](https://cloud.githubusercontent.com/assets/6498524/13629133/62e11d2a-e61a-11e5-9982-bc4a914cd805.png)

When you press `RET`,

![image](https://cloud.githubusercontent.com/assets/6498524/13629139/73ca1cae-e61a-11e5-8840-ebd896423160.png)

On the other hand, C-L, the equivalent command, works as intended.

System: OS X 10.11.3
Emacs: 24.5.1

**Comment by syl20bnr** [comment]
should be fixed in develop

**Comment by dieggsy** [comment]
@syl20bnr  I'm using the solution in develop for this (but not spacemacs), and I've noticed something sorta odd - If the last output had color sequences in it (as in `/usr/bin/git -c status.color=always status`), the prompt is colored with one of the colors in that output (I say one and not "the last" cause I haven't found it to be all that consistent). This doesn't happen with eshell's default clear function, and I'm not really sure how to troubleshoot from here.
