### ISSUE TITLE
eshell clear/ctrl-L in emacs 25 creates unwanted page of whitespace

### ISSUE THREAD

**Issue by joshcho** [syl20bnr/spacemacs#5424]
#### Description

Both clear commands in emacs 25 are very strange; clear RET creates a page of whitespace then prompts you. Ctrl-L creates half a page of whitespace, then cycles through three different positions of prompts.
#### Reproduction guide

a) clear
- Start Emacs
- Start eshell
- type "clear" then RET

b) Ctrl-L
- Start Emacs
- Start eshell
- Produce some command output
- Ctrl-L

_Observed behaviour:_
a) clear

![image](https://cloud.githubusercontent.com/assets/6498524/13635441/0db6ac82-e63f-11e5-8b6a-f6a8aba21115.png)

This is fresh load up of eshell in Emacs 25.

![image](https://cloud.githubusercontent.com/assets/6498524/13635448/22bedadc-e63f-11e5-81cd-5926c7cdba86.png)

This is what happens after `clear RET`

b) Ctrl-L

![image](https://cloud.githubusercontent.com/assets/6498524/13635480/54f55760-e63f-11e5-9d65-46c04a3437f3.png)

Some command history.

![image](https://cloud.githubusercontent.com/assets/6498524/13635493/6965601e-e63f-11e5-9466-129a13a9bca3.png)

![image](https://cloud.githubusercontent.com/assets/6498524/13635504/7573d8e0-e63f-11e5-8bea-182e435ddc1c.png)

![image](https://cloud.githubusercontent.com/assets/6498524/13635510/8028833a-e63f-11e5-9403-9eb899366261.png)

Pressing Ctrl-L cycles between these three images.

_Expected behaviour:_

![image](https://cloud.githubusercontent.com/assets/6498524/13635524/a4a84876-e63f-11e5-9690-3b55f12bfee6.png)

Both keystrokes should land in a cleared page.
#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.13
- Spacemacs branch: master (rev. 2c3e6b4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp)
```

**Comment by syl20bnr** [comment]
should be fixed in develop
