### ISSUE TITLE
Search with `helm-follow-mode` enabled

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#5425]
#### Description
Searching with `SPC /` for substrings that frequent in directory sub-tree fails 
#### Reproduction guide 
- set `(setq-default helm-follow-mode-persistent t)`
- open helm (e.g `SPC SPC`)
- enable follow mode - `C-c C-f`, close helm
- `SPC f e i`
- `SPC /`
- type 'spacemacs'

*Observed behaviour:*
```
Error during redisplay: (eval (spaceline--prepare spaceline-left spaceline-right)) 
signaled (error "Variable binding depth exceeds max-specpdl-size")
```

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.13
- Spacemacs branch: develop (rev. 895455d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp javascript html markdown org shell-scripts clojure react
            (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rvm)
            ruby-on-rails
            (auto-completion :variables auto-completion-enable-snippets-in-popup t)
            syntax-checking
            (shell :variables shell-enable-smart-eshell t)
            (deft :variables deft-directory "~/Google Drive/deft" deft-auto-save-interval 60)
            fasd ibuffer osx chrome evernote semantic restclient emoji bb-ibuffer ranger search-engine pdf-tools elfeed git
            (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
            (github :variables gist-view-gist t)
            agzam ag-dash synonyms floobits ag-4clojure dotspacemacs-additional-packages
            '(flycheck-package helm-flycheck tern-auto-complete writeroom-mode
                               (helm-fuzzier :location
                                             (recipe :fetcher github :repo "EphramPerdition/helm-fuzzier"))))
```

**Comment by TheBB** [comment]
It's probably unrelated but your dotfile is borked... You have `dotspacemacs-additional-packages` listed as a layer.

**Comment by a13ph** [comment]
I failed to reproduce this (develop emacs/spacemacs, stable ubuntu)

**Comment by agzam** [comment]
I got it. It only happens when you have helm's `follow-mode` enabled with `helm-follow-mode-persistent t
`. I guess this is upstream issue that need to be fixed in helm,
