### ISSUE TITLE
Create a compatibility sheet for Vim/NeoVim/Evil/Spacemacs

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#5427]
Mostly operators and motions/text-objects.

This would ease migrations, development orientation, may serve as a basis for compatibility Layers - so we may deviate, but still be able to enforce it...

Self-assigned, so feel free to remind/mention/gitter-pm me if that get's forgotten.

Any ideas on how to implement auto-generation & auto-update of such sheet would be welcome. I might be stuck on figuring it out after manual first version for a while otherwise.

**Comment by syl20bnr** [comment]
Not sure it worth the effort, the idea of Evil is to eliminate the need for this, at least for 80% of the use cases. Does the rest worth the maintenance of a paper ?

**Comment by a13ph** [comment]
@syl20bnr :speech_balloon: : [March 9, 2016 7:57 PM](https://gitter.im/syl20bnr/spacemacs?at=56e055f781bce261378ab6d6)
There was some willingness to have it. I'm doing closely related stuff anyways and would benefit from learning how to extract data like this (tips on which would be appreciated)
Many vim users would want to see how things compare, this is very useful thing to see on some github projects when researching alternatives

**Comment by TheBB** [comment]
I said I think it's a good idea but it's not in scope of Spacemacs in my opinion.

**Comment by a13ph** [comment]
Seeing as Spacemacs is a very juicy target for some Vim converts, compatibility coverage would be nice. Might also serve as `:help vim-feature/key/command` target for them.

If that's never gonna see another maintainer other than me, i'm fine with that. I'm not yet comfortable separating it to my repo or smth. Maybe when i'll write it down actually :laughing:
