### ISSUE TITLE
Add ability to open/resume project layout by `emacs /path/to/project/`

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#5431]
:speech_balloon: [March 10, 2016 12:31 AM](https://gitter.im/syl20bnr/spacemacs?at=56e0962a0055f8f35a81b8d2)

>  what sublime/atom do if you use subl . or atom . They open up the project in the current dir in a new frame with all the tabs/splits restored

suggested by @calebmeyer and @aaronkavlie-wf

**Comment by syl20bnr** [comment]
For people wanting to give this a try, Spacemacs provides the building blocks to do this with layouts which can be saved and restored manually.

**Comment by calebmeyer** [comment]
Note that in subl/atom terminology, you have a window (emacs frame) which contains tabs (roughly emacs buffers) and splits (which sort tabs into roughly emacs windows). So I misspoke when I called them frames in those two.

However, this is a pretty common ask for editors. My personal use case:
I have a number of projects (in folders, usually version controlled) which I can switch to with projectile (on `SPC p h`). When I open a project via projectile (or the command line `emacs .` in the folder), I'd like to have all of the above restored automatically.

**Comment by syl20bnr** [comment]
A first step would be to be able to identify layouts with an associated project. A simple way to do this would be to add a prefix to be name of the project layouts, could be a tilde for instance. 
The we add some hooks to save the layouts.
In the end we add a key binding/action/universal prefix/prompt/dotfile variable to enable this behaviour.
