### ISSUE TITLE
Going to the bottom of a file takes me to the middle of the window

### ISSUE THREAD

**Issue by ankhers** [syl20bnr/spacemacs#5432]
#### Description
When using vim editing mode and attempting to go to the end of a file (`G`), I am placed at the bottom of the file, however I am placed into the middle of the window, with the second half of the window appearing to be empty lines.

I am seeing this on both develop and master branches

This does not happen when using emacs editing mode.

#### Reproduction guide
- Start Emacs
- Open large file (needs to be at least as large as the window)
- Attempt to go to the bottom of the file (`G`)

*Observed behaviour:*
My cursor is at the end of the file, but it is in the middle of the window.

*Expected behaviour:*
I expect my cursor to be near the end of the window.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.13
- Spacemacs branch: develop (rev. 895455d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(c-c   common-lisp elixir emacs-lisp elm erlang go haskell html idris java javascript latex lua markdown purescript racket ruby rust sql yaml ruby-on-rails auto-completion better-defaults git github org colors jabber restclient dash erc gnus dockerfile spell-checking syntax-checking nixos)
```

**Comment by sooheon** [comment]
I don't understand the desired behaviour, because you say it does not happen in emacs editing mode. Are you saying you're calling `G` or `evil-goto-line` from emacs-state, and in that case you don't see this behavior? 

Also, this same cursor position is replicated with just `evil-mode` (no spacemacs config), so I think this issue should be opened at evil, not here.

**Comment by ankhers** [comment]
You are right, after testing with a blank emacs config and enabling `evil-mode`, I get the same position. I will report it there.

What I meant by it isn't happening in emacs editing mode, I meant using the emacs combination for `end-of-buffer` (`M->`).

I'm going to keep this open for the time being just to be able to link to the issue. If it should be closed as it is not an issue with spacemacs itself, feel free to close it.
