### ISSUE TITLE
latex highlighting problem with latex layer

### ISSUE THREAD

**Issue by disberd** [syl20bnr/spacemacs#5433]
#### Description
Editing tex files with latex layer active sometime messes up the text highlighting.
Attached a gif of the problem

#### Reproduction guide
Not reproducible for now

*Observed behaviour:*
While editing files in auctex using the latex layer, sometimes the edit of parts of the buffer completely messes up the text highlighting. Unfortunately this issue is not easy to reproduce reliably in my case. The removal of the latex layer from the .spacemacs file remove the appearance of this. Also reverting file brom buffer will fix the highlighting. Undo does not fix it usually but it does in some cases

*Expected behaviour:*

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.13
- Spacemacs branch: develop (rev. 895455d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion gnus emacs-lisp git themes-megapack org
                (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh")
                syntax-checking version-control semantic unimpaired latex extra-langs eyebrowse pdf-tools chrome c-c   ranger fasd)
```

#### Backtrace
```
![latexbug2](https://cloud.githubusercontent.com/assets/12846528/13655025/aa7b38e0-e65c-11e5-8675-db231d44b5a1.gif)
```

**Comment by TheBB** [comment]
This is likely auctex's problem. I see it too.

**Comment by kccai** [comment]
Yes, I see this too. It should be AucTeX's problem.

##### Temporary solution:
Every time when the latex highlight does not work normally, I will type `C-c C-n` to force AucTeX to re-highlight the .tex file.

**Comment by TheBB** [comment]
Nobody seems to be interested in reporting this to auctex.
