### ISSUE TITLE
Cursor disappears while scrolling

### ISSUE THREAD

**Issue by spattersongt** [syl20bnr/spacemacs#5434]
#### Description
Cursor disappears while scrolling with keyboard 
I have a fairly high key repeat rate but nothing crazy.

#### Reproduction guide
- Start Emacs

- While in insert mode or normal mode
- holding jklh and/or arrow keys
- the cursor disappears while scrolling. 
- cursor reappears when scrolling key is released

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org html web syntax-checking version-control osx)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by StreakyCobra** [comment]
I can't reproduce, it doesn't disappear on my side.

**Comment by TheBB** [comment]
Nobody can reproduce this it seems.
