### ISSUE TITLE
Auto paste into the files opened by mouse-click the item below Recent Files in Spacemacs buffer

### ISSUE THREAD

**Issue by hemcsec** [syl20bnr/spacemacs#5435]
#### Description

Auto yank into the files opened by mouse-click the item below Recent Files in Spacemacs buffer.
#### Reproduction guide
- Start Emacs
- Switch to Spacemacs buffer
- Use mouse click an item below Recent Files
- Some contents are yanked into the file just opened

_Observed behaviour:_
When use C-h k on the Click in Spacemacs buffer, it gives the following description.

down-mouse-1 (translated from mouse-1) at that spot runs the command
widget-button-click (found in spacemacs-buffer-mode-map), which is an
interactive compiled Lisp function in ‘wid-edit.el’.

It is bound to down-mouse-1.

(widget-button-click EVENT)

Invoke the button that the mouse is pointing at.

----------------- up-event ----------------

mouse-2 at that spot runs the command mouse-yank-primary (found in
global-map), which is an interactive compiled Lisp function in ‘mouse.el’.

It is bound to mouse-2.

(mouse-yank-primary CLICK)

Insert the primary selection at the position clicked on.
Move point to the end of the inserted text, and set mark at
beginning.  If ‘mouse-yank-at-point’ is non-nil, insert at point
regardless of where you click.

_Expected behaviour:_
Do not yank automatically in the opened file by click in Spacemacs buffer.
#### System Info
- OS: darwin
- Emacs: 25.0.92.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 1831d4c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults c-c   django emacs-lisp gtags git html javascript osx
                 (latex :variables latex-build-command "LatexMk")
                 python
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 (syntax-checking :variables syntax-checking-enable-by-default nil))
```
#### Backtrace

```

```

**Comment by HEMCSEC** [comment]
Under Windows or Ubuntu 14.04, the issue has gone. It may be specific to MAC OSX.

**Comment by HEMCSEC** [comment]
;; This problem may be related with wid-edit.el and mouse-1-click-follows-link. Now I can avoid automatic yank by putting the following config in spacemacs/user-config. 
(add-hook 'spacemacs-buffer-mode-hook (lambda ()
(set (make-local-variable 'mouse-1-click-follows-link) nil)))

**Comment by li-xinyang** [comment]
![](https://cloud.githubusercontent.com/assets/3349406/15097204/b32a8eb4-1546-11e6-8390-4e72b1e2b19f.gif)

**Comment by yilihong** [comment]
I was having the same issue after upgrading emacs to 25.1, @hemcsec 's approach addressed it.

**Comment by danstewart** [comment]
Having this issue on Fedora 24 - @hemcsec's fix sorted it for me too.

**Comment by renatomassaro** [comment]
Just to let you know, I'm also hitting this bug exactly as described. I'm on FreeBSD 11.0 with spacemacs 0.200.5 @ emacs 25.1.1

@hemcsec's snippet did not fix it.

Layers:

```
     auto-completion
     better-defaults
     emacs-lisp
     git
     markdown
     (org :variables
	evil-org-mode t)
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     spell-checking
     syntax-checking
     ;;version-control
     erlang
     elixir
     mu4e
     html
     php
     javascript
     ansible
     elm
     ruby
     python
```

**Comment by icaroperseo** [comment]
i'm also having the same issue on Arch Linux x64, Emacs 25.1 and Spacemacs stable (0.200.x). However, the fix proposed by @hemcsec works like a charm!

**Comment by natecox** [comment]
Having the same issue on macOS via emacs-plus. The solution proposed by @hemcsec seems to fix the issue.

**Comment by abingham** [comment]
Also seeing this on OS X, and the solution from @hemcsec seems to make it go away.

**Comment by xmao** [comment]
Seeing this on Mac OS X. @hemcsec solution works as a charm!

**Comment by sa1** [comment]
Duplicate of #5059

**Comment by craigstjean** [comment]
Observing the same issue on Arch with the latest Spacemacs on Emacs 25.1.1.  @hemcsec's change fixed it (thank you!!)

**Comment by wygulmage** [comment]
I have this issue on Ubuntu 16.04 and Windows 10 with Emacs 25.2 and a new vanilla Spacemacs installation. Hemcsec's solution also works for me. Unless we can get to the root of the problem, perhaps we should include it in the *spacemacs* buffer mode map.
Trace:
```
Debugger entered--Lisp error: (error "No selection is available")
  signal(error ("No selection is available"))
  error("No selection is available")
  gui-get-primary-selection()
  mouse-yank-primary((mouse-2 (#<window 3 on *Backtrace*> 405 (241 . 251) 1907771718 nil 405 (30 . 15) nil (1 . 11) (8 . 16))))
  funcall-interactively(mouse-yank-primary (mouse-2 (#<window 3 on *Backtrace*> 405 (241 . 251) 1907771718 nil 405 (30 . 15) nil (1 . 11) (8 . 16))))
  call-interactively(mouse-yank-primary nil nil)
  command-execute(mouse-yank-primary)
```
Clicking links in vanilla Emacs 25.2 does not have the same problem.

**Comment by yatesco** [comment]
Still seeing this on latest `develop` branch and up-to-date `macOS` and that @hemcsec's fix works (https://github.com/syl20bnr/spacemacs/issues/5435#issuecomment-195862080).

**Comment by jsmestad** [comment]
For anyone who is having this issue elsewhere when clicking links. I've modified @hemsec's fix to apply to all org modes:

```lisp
(add-hook 'prog-mode-hook (lambda () (set (make-local-variable 'mouse-1-click-follows-link) nil)))
```

**Comment by liuchong** [comment]
Fixed by @hemcsec 's suggestion https://github.com/syl20bnr/spacemacs/issues/5435#issuecomment-195862080 💯

**Comment by TakaakiFuruse** [comment]
Having the same issue on 0.300.0@25.3.2 (spacemacs) and was solved by https://github.com/syl20bnr/spacemacs/issues/5435#issuecomment-195862080.

I was kept annoying by this thanks @hemcsec.

**Comment by frankjonen** [comment]
@hemcsec's solution fixes nothing, Spacemacs launches in white recovery screen afterwards. Remove it again and it launches again. @jsmestad's mod does nothing but at least Spacemacs still launches with it in.

**Comment by jsmestad** [comment]
@frankjonen it should work just fine. Did you put inside the `user-config` ?

**Comment by frankjonen** [comment]
@jsmestad I put it in `(defun dotspacemacs/user-config ()
  "Configuration function for user code…` straight up copy and paste. While it doesn't do anything, it also doesn't crash it.

**Comment by frankjonen** [comment]
Got it to work (new to emacs) I read `prog-mode` as _"all modes that programatically affect text"_. Now that I added it to my Markdown rules it works there too. The other MD rules are now broken though, so there's that. :)

**Comment by frankjonen** [comment]
I had misread what `prog-mode` meant (new to emacs). Now I took it apart and added it to my `markdown-mode` rule as `(lambda () (set (make-local-variable 'mouse-1-click-follows-link) nil))` and it now stopped pasting the entire clipboard contents but it still pasts something. Haven't tracked down what exactly gets pasted but the text moves when I undo and it's not anywhere in the vicinity of where the cursor gets placed.

**Comment by jsmestad** [comment]
@frankjonen for markdown-mode I am guessing it would be: `(add-hook 'markdown-mode-hook (lambda () (set (make-local-variable 'mouse-1-click-follows-link) nil)))`

**Comment by frankjonen** [comment]
@jsmestad Thanks for checking. That's what I had in though. Removed it since it did nothing. I've given up on trying to fix it and just stopped using the mouse in emacs for opening files. 🤷‍♂️ Enough other issues to address to get hooked up on this one.

**Comment by bjonnh** [comment]
Still the case in the last develop. Should it be something integrated in spacemacs at some point?
