### ISSUE TITLE
linum-mode is too slow in large org-mode buffer

### ISSUE THREAD

**Issue by levindu** [syl20bnr/spacemacs#5436]
When in large org-mode buffer (6K+ lines), turning on linum-mode make cursor movement very slow, almost unbearable.

I suggest to use nlinum-mode, which works quite well in my situation.

Or provide an option of line number backend for user to choose linum-mode or nlinum-mode?

**Comment by a13ph** [comment]
I've seen some linum alternatives which posit they work well in large buffers (by jit display or smth else)
