### ISSUE TITLE
clojure/elisp support for paxedit

### ISSUE THREAD

**Issue by nha** [syl20bnr/spacemacs#5438]
It would be nice to have support for [paxedit](https://github.com/promethial/paxedit) bindings, in elisp/clojure modes.

Most importantly those (for me at least) :

```
      (define-key paxedit-mode-map (kbd "M-<right>")   'paxedit-transpose-forward)
      (define-key paxedit-mode-map (kbd "M-<left>")     'paxedit-transpose-backward)
      (define-key paxedit-mode-map (kbd "M-<up>")      'paxedit-backward-up)
      (define-key paxedit-mode-map (kbd "M-<down>") 'paxedit-backward-end)
```

There seem to be some interest, as asked there also : https://github.com/syl20bnr/spacemacs/issues/627

**Comment by arronmabrey** [comment]
I just found out about paxedit and decided to come look if it was implemented yet. Subscribing for updates. ;-)

**Comment by axg-vivo** [comment]
Any other developments on this? Seem to be a really powerful mode, useful for many people. Don't know why it's been neglected for a while now.
