### ISSUE TITLE
How hard is it to use spacemacs layers outside of spacemacs? 

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#5439]
To promote modular reusable sharing, they should be as easy as packages to reuse, no?

Posting this question as an issue as I don't really know who to ask, and mentioning whole top of contributors seems unwieldy.

**Comment by AlejandroCatalina** [comment]
Actually, I don't think reusing spacemacs layers outside spacemacs would be easy.

A layer is strongly affected by the core functions that handle the packages searching, the loading order, the package ownership.. etc.

We would need another package to extract that behavior. That package is spacemacs itself. IMHO.

**Comment by a13ph** [comment]
I'm all for Spacemacs core being a package. But as I remember @syn20bnr talking about it in another issue, where he talked about Spacemacs being in fact a first testbed for such package `crown` IIRC, it's far from being ready. Just forgot about that and that answers a big part of my question.

But maybe some sort of universal API would be useful for other loader packages? Many people just write and roll their own ones and that seems a bit of wasteful for me - being limited to two polar opposites - either use config distro or base your own loader/module manager/... off use-package and the like.

*This pertains much more than to Spacemacs community though, so I guess I have to ask this somewhere with a much wider reach (maybe crosspost into different community hubs too)*

**Comment by bmag** [comment]
>  where he talked about Spacemacs being in fact a first testbed for such package crown

I believe you're referring to https://github.com/syl20bnr/spacemacs/issues/3590#issuecomment-152538946

**Comment by a13ph** [comment]
@StreakyCobra Close as duplicate of #3590 (whoops.)

**Comment by syl20bnr** [comment]
To be clear on this, this is low priority as Spacemacs is not even 1.0. Once we have a stable layer system I will be happy to attempt to extract it.
