### ISSUE TITLE
spacemacs/jump-in-buffer doesn't work in orgmode

### ISSUE THREAD

**Issue by yejianye** [syl20bnr/spacemacs#5441]
#### Description
`SPC s j` doesn't work in orgmode buffers.

#### Reproduction guide
- Start Emacs
- Update all packages to latest
- Open any orgmode buffer
- Press `SPC s j` or execute `spacemacs/jump-in-buffer` command

*Observed behaviour:*
Got "wrong number of arguments" error

*Expected behaviour:*
List all headings in a helm buffer

#### System Info
- OS: darwin
- Emacs: 24.5.4
- Spacemacs: 0.105.13
- Spacemacs branch: master (rev. 2c3e6b4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup nil auto-completion-private-snippets-directory "~/toolbox/emacs/snippets")
 markdown python emacs-lisp javascript ansible yaml org osx syntax-checking
 (spell-checking :variables spell-checking-enable-by-default nil)
 git better-defaults eyebrowse)
```

#### Backtrace
```
apply: Wrong number of arguments: #[(&optional with-self use-cache) "~�ÂÃ!�Ä �ÅÆ	!!*" [with-self use-cache org-back-to-heading t org-up-heading-safe reverse org--get-outline-path-1] 3 ("/Users/ryan/.emacs.d/elpa/org-20160307/org.elc" . 398130)], 3
```

**Comment by TheBB** [comment]
https://github.com/emacs-helm/helm/issues/1421

By the way, you probably didn't mean `SPC h I`.

**Comment by yejianye** [comment]
Thanks, TheBB. It should be `SPC s j`, I've updated the description.

**Comment by brenogil** [comment]
Just for the sake of completeness
I can reproduce this using
emacs-25.1.50.1                                       
spacemacs-0.105.14

**Comment by aroig** [comment]
There is now an upstream PR at emacs-helm/helm#1429.

**Comment by TheBB** [comment]
Fixed upstream.
