### ISSUE TITLE
Documentation string follows a 'defun' name  or setq 'var'  in elisp but not in .spacem.template

### ISSUE THREAD

**Issue by triklsbg** [syl20bnr/spacemacs#5443]
In the setq sexp of the .spacemacs.template the documentation comment precedes (comes before) the coded variable name. In "normal" lisp the doc-string follows the definition. Depending on the chosen syntax highlighting this is more or less confusing in my opinion. Generally i would prefer the coded variable name before the docstring in this case the explaining comments.
You may call me nitpicking.;-)

**Comment by TheBB** [comment]
I think we'd be doing ourselves a disfavour by moving them. It's a fairly widespread convention that comments come before the code that they are explaining.

We can't change the Emacs Lisp docstring conventions, however.

**Comment by TheBB** [comment]
On the other hand, one thing I would like to see which I think would help is some empty lines.

**Comment by rgrinberg** [comment]
@TheBB This can be closed then right?

**Comment by TheBB** [comment]
Sure.
