### ISSUE TITLE
Add support for multiple evil-escape-key-sequences

### ISSUE THREAD

**Issue by al3xandru** [syl20bnr/spacemacs#5445]
This is just a _minor_ request: as a vimmer using `jk` as an escape sequence, it would be very helpful to allow defining multiple `evil-escape-key-sequences` that would ease the transition to the Spacemacs's default `fd`. 

Changing the `evil-escape-key-sequence` was one of the first things I've learned and done after starting Spacemacs. As I leaned more into Spacemacs `spc` prefix combined with `spc f s` I felt tempted to give a 2nd chance to `fd`. As a newbie, going the `key-chord` route sounds a bit scary/too complicated (maybe because what I have read was not very conclusive)

**Comment by al3xandru** [comment]
While I still think this could be an useful small feature, the workaround is quite easy:

1. add `key-chord` to `dotspacemacs-additional-packages`
2. in `dotspace/user-config ()` add

    ```
    (key-chord-mode 1)
    (key-chord-define evil-insert-state-map "fd" 'evil-escape)
    ```

The only downside is that this new sequence doesn't work in all buffers where the `evil-escape-key-sequence` is working (most probably because the sequence is added to the insert map only)

**Comment by StreakyCobra** [comment]
This should probably be asked upstream :-) Would be better supported there https://github.com/syl20bnr/evil-escape

**Comment by TheBB** [comment]
Reported upstream, this issue doesn't serve much purpose.
