### ISSUE TITLE
Error with smooth-scrolling-mode on start-up

### ISSUE THREAD

**Issue by ethanluoyc** [syl20bnr/spacemacs#5446]
#### Description
Error with smooth-scrolling-mode on start-up

#### Reproduction guide
- Start Emacs

*Observed behaviour:*
It reports the ERROR:

> Error (use-package): smooth-scrolling :init: Symbol's function definition is void: smooth-scrolling-mode

*Expected behaviour:*
It should finish the start-up with no errors

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: personal (rev. b376d3b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(ranger yaml markdown c-c   emacs-lisp javascript html
        (python :variables python-test-runner 'pytest)
        mit-scheme
        (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill t)
        (ruby :variable ruby-enable-enh-ruby-mode t ruby-version-manager 'rbenv)
        ess react ruby-on-rails shell-scripts
        (shell :variables shell-default-shell 'multi-term shell-default-height 40 shell-default-position 'bottom)
        gtags
        (version-control :variables version-control-diff-tool 'git-gutter version-control-global-margin t)
        dash git osx
        (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip t)
        org syntax-checking vagrant
        (matlab :variables matlab-indent-function t matlab-shell-command "/Applications/MATLAB_R2015a.app/bin/matlab"))
```

**Comment by NJBS** [comment]
Can you try updating your packages?

**Comment by doomsplayer** [comment]
Same issue

**Comment by ethanluoyc** [comment]
I am able to fix this with an upgrade. @doomsplayer you may want to try that as well?

**Comment by doomsplayer** [comment]
@ethanluoyc I'm trying

**Comment by StreakyCobra** [comment]
@doomsplayer Use the `[Update packages]` button on the `*spacemacs*` buffer :-)

**Comment by doomsplayer** [comment]
@StreakyCobra Thanks, I've fixed it via a update. 
@ethanluoyc I think you can close this issue now.

**Comment by ethanluoyc** [comment]
@doomsplayer No problem
