### ISSUE TITLE
evil-search-forward glitch in web-mode

### ISSUE THREAD

**Issue by Evidlo** [syl20bnr/spacemacs#5447]
#### Description

In `web-mode`, evil-search-forward (`/`) gives strange behavior when searching for content inside a fold.
#### Reproduction guide
- Start Emacs
- open html file (given below)
- enter `web-mode`
- fold the div with class `fold this div` (`SPC m z`)
- search for the string `search me`

_html file_

```
foo
<div class="fold this div">
  search me
</div>
bar
```

_Observed behaviour:_
It appears that once evil finds the string `search me`, spacemacs stops responding until I hit `ctrl G` a few times.

_Expected behaviour:_
It should be able to search for the string within a fold without freezing (preferably opening the fold automatically).
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(better-defaults c-c   django emacs-lisp gtags go html
                 (git :variables git-gutter-use-fringe t)
                 markdown org python shell syntax-checking yaml)
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by StreakyCobra** [comment]
For me it seems to be an upstream bug, but for now I can't even try to reproduce this on stock emacs because the folding of web-mode isn't working.

**Comment by kdelwat** [comment]
I was able to reproduce this on the latest version, so it's definitely still a problem.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 (clojure :variables clojure-enable-fancify-symbols t cider-font-lock-dynamically
          '(macro core deprecated function)
          cljr-suppress-middleware-warnings t)
 emacs-lisp git html javascript markdown org python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking themes-megapack
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t))
```
