### ISSUE TITLE
Smartparens creates an extra pair of quotes if you navigate while writing a string

### ISSUE THREAD

**Issue by exitface** [syl20bnr/spacemacs#545]
`"foo bar<Press backspace>"`
`"foo ba<Press quote>"`
Results in:
`"foo ba\"\""`

This behavior will also be triggered when hitting left/right

Additionally pressing quote at the end of an existing string after exiting, and reintering insert mode will trigger the same behavior:

`"foo bar"`
Exit, reenter insert mode
`"foo bar<CURSOR HERE, Press quote>"`
Results in:
`"foo bar\"\""`

The expected behavior is to just move to the right of the closing quote.

**Comment by quartz55** [comment]
Can confirm. It is specially annoying because 95% of the time I really just want to close the quotes and not insert a quote in a string :)

**Comment by razcampagne** [comment]
You just need to set sp-cancel-autoskip-on-backward-movement to nil in your .spacemacs

**Comment by CestDiego** [comment]
This works, I think this should be a default in spacemacs.... if you want to really put quotes, just pressing `\` before a quote puts `\"\"` so there is no need for this being enabled by default

**Comment by syl20bnr** [comment]
PR welcome :-)

**Comment by exitface** [comment]
Created. Based it off to the develop branch.

**Comment by syl20bnr** [comment]
Fixed by #584
