### ISSUE TITLE
ESS + ess-julia-mode julia-mode

### ISSUE THREAD

**Issue by gragusa** [syl20bnr/spacemacs#5450]
I am having problems with ESS and `julia-mode`. `julia-mode` has few extra features that are now integrated in ESS. For instance, `julia-mode` allows entering greek letter using latex syntax (e.g., \alpha, \beta, etc.).

However, it seems that with the elpa installation of spacemacs `julia-mode` is not loaded (even if I can load `julia-mode` from within emacs, but then I loose the `ess-julia-mode` features). 

Anybody has had the same problem?

**Comment by izahn** [comment]
Are you sure this works differently without spacemacs? What happens when
you start with `emacs -q` and load just ESS?

**Comment by gragusa** [comment]
Digging further I notice that `julia-mode.el` is actually loaded. The problem with latex completion is that in `julia-mode.el` <TAB? is bound using:

'''(define-key julia-mode-map (kbd "TAB") 'julia-latexsub-or-indent)'''

instead it should be bound when `ess-julia-mode-map`. I fixed it by adding to `dotspacemacs/user-init ()` the following:

```
  (add-hook 'ess-julia-mode-hook
            (lambda()
                  (define-key
                    ess-julia-mode-map (kbd "TAB") 'julia-latexsub-or-indent)
                  )
            )
```

**Comment by Immortalin** [comment]
@gragusa send a pull request?

**Comment by izahn** [comment]
This has already been reported on the ESS mailing list: thttp://emacs.1067599.n5.nabble.com/delta-for-julia-td397296.html. ESS devs (correctly IMO) don't think it makes sense for this functionality to be provided by julia-mode. Spacemacs already has `helm-ucs`. If you want pop-up completion use `company-math`.
