### ISSUE TITLE
Large file check breaks package update

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#5454]
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
      >(nil 1048576)
      (if (> (nth 7 (file-attributes (buffer-file-name))) (* 1024 1024 dotspacemacs-large-file-size)) (progn (if (y-or-n-p "This is a large file, open literally to avoid performance issues?") (progn (setq buffer-read-only t) (buffer-disable-undo) (fundamental-mode)))))
      spacemacs/check-large-file()
      run-hooks(find-file-hook)

**Comment by syl20bnr** [comment]
related to #5448

**Comment by TheBB** [comment]
Closing as duplicate.
