### ISSUE TITLE
Broken counsel fix

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#5460]
The recent counsel fix dfceb3d seems to have broken search commands such as `spacemacs/search-project-auto`.  When using the command:

~~~
rxt-string->pcre: Wrong type argument: arrayp, nil
~~~

**Comment by nixmaniack** [comment]
https://github.com/syl20bnr/spacemacs/pull/5457 should fix it.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
