### ISSUE TITLE
Updates seem to fail with (New file) if: Wrong type argument: number-or-marker-p, nil gnutls.c: [0] fatal error: The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by robbyoconnor** [syl20bnr/spacemacs#5468]
#### Description
Updates fail with (New file)
if: Wrong type argument: number-or-marker-p, nil
gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.

#### Reproduction guide
- Start Emacs (be on `develop`
- Press [Update Packages]
- Will fail 

*Observed behaviour:*
```
(Spacemacs) --> refreshing package archive: melpa... [1/3]
Contacting host: melpa.org:443
Importing package-keyring.gpg...done
Contacting host: melpa.org:443 [2 times]
(Spacemacs) --> refreshing package archive: org... [2/3]
Importing package-keyring.gpg...done
Contacting host: orgmode.org:80
(Spacemacs) --> refreshing package archive: gnu... [3/3]
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Fetcher: github
Source: syl20bnr/persp-mode.el

Updating /home/rob/.emacs.d/.cache/quelpa/build/persp-mode/
(Spacemacs) --> Found 4 package(s) to update:

(Spacemacs) evil-mc

(Spacemacs) go-mode

(Spacemacs) helm-core

(Spacemacs) julia-mode

Do you want to update 4 package(s) ? y
(Spacemacs) --> performing backup of package(s) to update...

(New file)
if: Wrong type argument: number-or-marker-p, nil
gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.
byte-code: End of buffer 
```

*Expected behaviour:*
Updates should happen successfully...not sure if it's my system or not but reporting anyways... 

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. d52eb41)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm asciidoc elfeed speed-reading swift plantuml
                (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-show-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets")
                better-defaults emacs-lisp
                (git :variables git-magit-status-fullscreen t)
                github gnus version-control markdown syntax-checking
                (latex :variables latex-enable-auto-fill t)
                (colors :variables colors-enable-rainbow-identifiers t colors-enable-nyan-cat-progress-bar t)
                dockerfile ansible puppet evil-commentary
                (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
                fasd finance floobits xkcd autohotkey csv
                (c-c   :variables c-c  -enable-clang-support t)
                (clojure :variables clojure-enable-fancify-symbols t)
                extra-langs go
                (haskell :variables haskell-enable-ghci-ng-support t haskell-enable-shm-support t haskell-enable-hindent-style "andrew-gibiansky")
                html java
                (javascript :variables javascript-disable-tern-port-files t)
                (python :variables python-enable-yapf-format-on-save t)
                racket
                (ruby :variables ruby-version-manager `rvm)
                ruby-on-rails
                (rust :variables rust-enable-rustfmt-on-save t)
                scala shell-scripts restclient themes-megapack tmux vim-empty-lines spotify pandoc vagrant
                (ibuffer :variables ibuffer-group-buffers-by 'projects)
                semantic deft
                (shell :variables shell-default-shell 'ansi-term shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh")
                typescript
                (eyebrowse :variables eyebrowse-display-help t)
                erc chrome d smex emoji gtags prodigy evernote
                (org :variables org-enable-github-support t)
                search-engine evil-little-word yaml sql nim ipython-notebook lua scheme purescript sml common-lisp ranger wakatime dash spell-checking jabber cscope vinegar rcirc games react geolocation idris
                (elm :variables elm-reactor-port "3000" elm-reactor-address "0.0.0.0")
                elixir
                (typography :variables typography-enable-typographic-editing t)
                evil-cleverparens pdf-tools)
```

#### Backtrace
```
n/a
```

**Comment by cpaulik** [comment]
I see the same error. So it is probably not system specific.

**Comment by NJBS** [comment]
I can reproduce this on Windows Emacs 24.5.1. However, my packages still update and build correctly after the error message.

**Comment by a13ph** [comment]
@robbyoconnor @cpaulik
Some versions of gnutls don't like some versions of emacs
https://github.com/nicferrier/elmarmalade/issues/55
workaround: https://github.com/nicferrier/elmarmalade/issues/55#issuecomment-166271364

**Comment by nixmaniack** [comment]
This is likely related to #5448 and should be fixed by #5453

**Comment by TheBB** [comment]
I don't know about that, I've been having this for a while before that bug was introduced.

**Comment by nixmaniack** [comment]
If you're talking about TLS error, then even I used to get it but I think I have ignored it since long.

**Comment by robbyoconnor** [comment]
I can't get updates :/

**Comment by bmag** [comment]
I also get the TLS error, but it doesn't prevent me from getting updates. I don't get the wrong-type-argument error, but maybe that's because I haven't updated in the past 2 or 3 days.

Also, I have managed to reproduce the TLS error with bare Emacs (Emacs 24.5.1, Ubuntu 15.10):
- move `~/.emacs.d` directory out of the way or delete it
- `emacs -Q`
- `M-: (setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")))`
- `M-x package-refresh-contents`
- observe error message: `gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.`

Note also that I don't get the error if I use `M-: (package-refresh-contents)` instead `M-x package-refresh-contents`, or if I use `("melpa . "https://melpa.org/packages/")` instead of `("gnu" . "https://elpa.gnu.org/packages/")`. This points to gnu.elpa.org causing the TLS error.

I suspect that @robbyoconnor's problem is due to the wrong type argument, not the TLS. Any chance to get a backtrace @robbyoconnor?

**Comment by robbyoconnor** [comment]
There was no backtrace sadly

**Comment by robbyoconnor** [comment]
#### Backtrace
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  >(nil 1048576)
  (if (> (nth 7 (file-attributes (buffer-file-name))) (* 1024 1024 dotspacemacs-large-file-size)) (progn (if (y-or-n-p "This is a large file, open literally to avoid performance issues?") (progn (setq buffer-read-only t) (buffer-disable-undo) (fundamental-mode)))))
  spacemacs/check-large-file()
  run-hooks(find-file-hook)
  after-find-file(t t)
  find-file-noselect-1(#<buffer rollback-info> "~/.emacs.d/.cache/.rollback/16-03-12_23.17.17/rollback-info" nil nil "~/.emacs.d/.cache/.rollback/16-03-12_23.17.17/rollback-info" nil)
  find-file-noselect("/home/rob/.emacs.d/.cache/.rollback/16-03-12_23.17.17/rollback-info")
  (let ((buf (find-file-noselect filename))) (set-buffer buf) (erase-buffer) (spacemacs/dump varlist buf) (make-directory (file-name-directory filename) t) (save-buffer) (kill-buffer))
  (save-excursion (let ((buf (find-file-noselect filename))) (set-buffer buf) (erase-buffer) (spac
```

**Comment by nixmaniack** [comment]
@robbyoconnor This clearly looks like #5448. Did you pull develop recently and tried again? Fix is in develop.

**Comment by robbyoconnor** [comment]
I thought I did...

--Rob

**Comment by robbyoconnor** [comment]
Confirming thta @nixmaniack fixed this bug...no longer see the error.  :100:

**Comment by asymmetric** [comment]
I still see this, and I'm on develop at commit `0248e384a2f6a210b9a8de6292ebb0e6a18072e4`.

**Comment by nixmaniack** [comment]
@asymmetric which error? 
```if: Wrong type argument: number-or-marker-p, nil``` 
or 
``` gnutls.c: [0] fatal error: The TLS connection was non-properly terminated.```. 

We had fixed the first one, wrong type argument.

**Comment by asymmetric** [comment]
@nixmaniack the `gnutls.c` error. 

Emacs 24.5.1 on Ubuntu Wily, Spacemacs 9368cba427a24dbeea82f28fc1f19b560545f0e6.

**Comment by nixmaniack** [comment]
@asymmetric You should open a new issue (unless there's already one) for this.

**Comment by robbyoconnor** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67o9b-da&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=CQbN36tV&invitationId=6130896966281949184








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67o9b-da&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEdmJDNOgV-9gAAAVRVSbaiouPDTZwApyS0kcc80YrhseGrWF5tBOxKOZE4RYI5a65JE-58hFOCI_bwlVcyn55OBUZD-5cGtc_gopZEGTEh1H8tTU67QxByxRWED9onl-V6HBJC2JdgtjM7NlVcKePjGf6qSMRZcIfl7wtL0SYgoKbQ_MYrgghITO-EbaNfID-0&eid=0-ini67o9b-da


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67o9b-da&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by robbyoconnor** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67omz-k9&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=Qb0epVdW&invitationId=6130896992349540352








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67omz-k9&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHZNttYYNRYcwAAAVRVScmYR71uJSlqtXw3uUSpO_mhFow6XDiwDylC8RfqN0sYerg2aJas5W8rKlGYnS_sC0jEDEGJgStvvndB7bwZlWfzkQ-u4YikxFPw-hOlRBB4LVdjz1z0TI-t0jmWtALCg-lDKnPBIqS27lD_ia2IJZkyxGYG1Yg65jdfCu54Ga71bNfr&eid=0-ini67omz-k9


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67omz-k9&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
