### ISSUE TITLE
`evil--jump-forward` does not work

### ISSUE THREAD

**Issue by eltechnic0** [syl20bnr/spacemacs#5471]
I have tried with both the latest master and develop branch but nothing. Apparently  `evil-jumps-struct-idx` always returns `-1`. I tried looking that symbol up but I am unable to find it anywhere... I am sure that the problem is there, since manually executing `evil--jumps-jump-to-index` does jump as expected.

**Comment by jkaye2012** [comment]
+1, any update on this?

**Comment by StreakyCobra** [comment]
Could anyone report more information using [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? It will help us to help you :-)

**Comment by jkaye2012** [comment]
Well, in filling out the template I realized that I was not hitting leader before C-i, so this is actually not a problem for me. Apologies :)

**Comment by StreakyCobra** [comment]
Uh? If you want to use `C-i` you should set `dotspacemacs-distinguish-gui-tab` to `t` in your `.spacemacs`.

**Comment by jkaye2012** [comment]
Do you recommend something else? Leader C-i seems to be the default binding (at least I don't believe I've changed it)

**Comment by TheBB** [comment]
I'm not sure what you're talking about. There is no `SPC C-i` binding.

**Comment by NathanLovato** [comment]
`evil-jump-forward` works here in the latest commit on the develop branch, but as explained above by @StreakyCobra, by default when you press `<C-i>` emacs acts as if you were pressing `TAB`. In your init.el file, set `dotspacemacs-distinguish-gui-tab t` in the `dotspacemacs/init` function and it should work.
