### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by Ps-Pencil** [syl20bnr/spacemacs#5473]
The links in the table of contents in the documentation seems broken. It is written using org (which I am not familiar). But the link it jumps to (in my Chrome and Firefox) is `https://github.com/syl20bnr/spacemacs/blob/master/doc/xxx` where it should be `https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#xxx`

**Comment by TheBB** [comment]
#4399
