### ISSUE TITLE
org-mode errors

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#5474]
I get this error all over the place when using org-mode

user-error: An element cannot be parsed line # 

I also can't set auto-fill on org-mode, can't break lines... almost unusable....
Thinking about getting back to vim, I expend more time configuring emacs/spacemacs than actually doing my job!!!

**Comment by d12frosted** [comment]
@jvillasante it would be a good starting point to share the output of `SPC h d s`. Steps to reproduce would hurt as well. Thanks :)

**Comment by StreakyCobra** [comment]
And as for every bug you can try the following actions:

- Update Spacemacs and restart
- Update your packages and restart
- Move `.emacs.d/elpa` to `.emacs.d/elpa-old` and restart (if this cause any problem you can still move back the old folder)
- Try to reproduce the bug without your `.spacemacs`

**Comment by jvillasante** [comment]
I'm sorry, I was angry yesterday. I just convinced everyone at work to write our internal documentation in org-mode and then it all started to fail. It was a rush post. Both emacs and spacemacs are great software. I solved the issue adding this to my dotspacemacs/user-init. I don't understand the why but somehow it now works.

```
  (with-eval-after-load 'org
    ;; org problems
    (setq org-planning-line-re "")
    (setq org-clock-line-re "")
    )
```

**Comment by StreakyCobra** [comment]
If you don't set these lines, what are the values of these variables?

    org-clock-line-re is a variable defined in `org.el'.
    Its value is "^[ 	]*CLOCK:"

    org-planning-line-re is a variable defined in `org.el'.
    Its value is "^[ 	]*\\(\\(?:CLOSED\\|DEADLINE\\|SCHEDULED\\):\\)"

**Comment by jvillasante** [comment]
If I don't define those variables myself then they not exists at all. I just defined them as you said and everything keeps working ok.

```
  (with-eval-after-load 'org
    ;; org problems
    (setq org-planning-line-re "^[    ]*\\(\\(?:CLOSED\\|DEADLINE\\|SCHEDULED\\):\\)")
    (setq org-clock-line-re "^[    ]*CLOCK:")
    )
```

**Comment by StreakyCobra** [comment]
These variables are defined by `org-plus-contrib`. Do you have the `org` layer enabled in your `.spacemacs`? Can you try what explained [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/info/release-notes/0.104.txt#L3-L5). Also what is the result of `M-x org-version RET`?

**Comment by d12frosted** [comment]
Also, as I said, `SPC h d s` :)

**Comment by namdnguyen** [comment]
@jvillasante did you also try moving out or deleting your `~/.emacs.d/elpa` and restarting? I also had some errors with those same variables with the last `org-plus-contrib` update. Org-capture was giving me errors as well as `M-RET` to make a new list entry. Removing my org folders and restarting fixed them for me with out having to set any variables.

I was initially tipped off by [this issue](https://github.com/syl20bnr/spacemacs/issues/3262).

**Comment by 0x3bfc9a1** [comment]
Same thing here, my org-version is 8.3.6.
