### ISSUE TITLE
Problems with Python mode, Anaconda mode

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#5478]
I tried using the `SPC h I ` but it didn't work [1] so I'm posting here

Note I've edited this!

## math.py in the ~/ dir

Massively daft error - I had a file named `math.py` in `~/` that was causing the
`anaconda` errors which made the buffer keep refocusing.

## full path not showing when running `SPC m s B`

I'm not too sure why this was - possibly because of the first error I'm not
sure. But after reinstalling stuff a couple of times and sorting out the first
error things are now working as expected.

********

# Running `SPC m s B` doesn't work properly

Usually i can run `SPC m s B` there will be a path to the iPython interpreter
that's going to be running, i no longer get this i just see 

```
run python: ipython -i
```

Which isn't what's wanted - it should display the path to the ipython

# I can't use anaconda virtual envs

Usually I can activate a virtual environment using `pyvenv-activate` , this is
no longer working. Though to be honest I'm not sure if I could actually tell
with all the other errors.

# Anaconda mode isn't working properly

When I'm in a python file i can't type for more than one key stroke before I'm
moved to a buffer with the following type of message

```
    from tempfile import mkdtemp
  File "/home/vco/anaconda/envs/all_project/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
ImportError: cannot import name Random
```

********

[1] It opened firefox, i had to sign in to github again then i got an nginx
error so gave up with that.

*******

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 00d13b4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'complete)
 better-defaults c-c++ colors emacs-lisp erc evil-snipe eyebrowse git github haskell html ipython-notebook javascript latex markdown org python
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 syntax-checking themes-megapack version-control yaml)
```

**Comment by geo7** [comment]
@StreakyCobra this can be marked solved - or deleted? As i think it's because of the first error noted in there (math.py)

**Comment by StreakyCobra** [comment]
If it is solved you can close it freely :-)

**Comment by geo7** [comment]
@StreakyCobra oh yeah i forgot ha, cheers
