### ISSUE TITLE
Hitting `zc` on a closed fold does not close parent fold

### ISSUE THREAD

**Issue by ipsod** [syl20bnr/spacemacs#5481]
In Vim, hitting `zc` on an already folded region will fold its parent region.

To reproduce, create a new buffer, activate python-mode, and paste this text:

```
class Test():
    def whatever():
        test = 'test'
        test = 'test'
```

Fold the method, and then hit `zc` again to try to fold the parent class.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. d52eb41)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp git markdown org spell-checking unimpaired python html php django version-control auto-completion syntax-checking evil-snipe search-engine gnus
            (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by TheBB** [comment]
Evil doesn't implement its own folding operations, but falls back on existing packages. This is very likely to be considered a wontfix by them and also by us.

**Comment by TheBB** [comment]
You can try installing vimish-fold, which is a folding backend that presumably works more closely to vim behaviour.

**Comment by ipsod** [comment]
I checked out `vimish-fold`, but it seems to be for manual folding, and I couldn't get it to do syntax-based folding.

**Comment by syl20bnr** [comment]
I'm in the impression to have already read this :-)

**Comment by a13ph** [comment]
@ipsod try `origami`. There are some dotfiles on github for "spacemacs origami" search as well, so you will be able to copypaste some parts of it. 


_That de ja vu sounds like a good nudge to make this a layer..._
