### ISSUE TITLE
How to set indent in xml to 4?

### ISSUE THREAD

**Issue by fuzihaofzh** [syl20bnr/spacemacs#5483]
I have set tab equal to 4 spaces. But when I use xml and lua mode, it turn out to set the tab as 2 spaces. How can I solve that?

**Comment by darfink** [comment]
In most cases each major-mode has mode-specific options for adjusting indentation:

1. [Web-mode](http://web-mode.org/) `(setq web-mode-markup-indent-offset 4)`
2. [Lua-mode](https://github.com/immerrr/lua-mode#customization): `(setq lua-indent-level 4)`

**Comment by maplewizard** [comment]
Hi, @darfink, I tried as you said, and the user-config is as follows:
```
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
 This function is called at the very end of Spacemacs initialization after
layers configuration. You are free to put any user code."
  ;;(xterm-mouse-mode 0)
  (global-hl-line-mode 0)
  ;;tab
  (setq-default tab-width 4)
  (setq web-mode-markup-indent-offset 4)
  (setq lua-indent-level 4)
  (setq nxml-child-indent 4 nxml-attribute-indent 4)
  (setq-default c-basic-offset 4)
  ;;neotree
  (global-set-key (kbd "<f9>") 'neotree-toggle)
  (global-set-key (kbd "C-j") 'avy-goto-word-or-subword-1)
  (spacemacs/toggle-automatic-symbol-highlight)
  )
```
But it still cannot work. How could that happen?

**Comment by darfink** [comment]
Have you configured a custom major-mode for XML files or are you using the default? (`nxml-mode`).
Using a complete vanilla version of Spacemacs I achieve the desired behavior by using:
```
(defun dotspacemacs/user-config ()
  (setq nxml-child-indent 4))
```

**Comment by TheBB** [comment]
Use `setq-default`, not `setq`. Then confirm that in the relevant buffer(s), the variables actually have the values that you expect.

**Comment by maplewizard** [comment]
@TheBB @darfink 
 This is my layer config and it seems still not work. 
```
dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     osx
     python
     ipython
     c-c++
     markdown
     auto-completion
     better-defaults
     emacs-lisp
     git
     markdown
     org
     lua
     nxml
     html
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     spell-checking
     syntax-checking
     version-control
     ido
     smex
     gtags
     )
```
```
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
 This function is called at the very end of Spacemacs initialization after
layers configuration. You are free to put any user code."
  ;;(xterm-mouse-mode 0)
  (global-hl-line-mode 0)
  ;;tab
  (setq-default tab-width 4)
  (setq-default web-mode-markup-indent-offset 4)
  (setq-default lua-indent-level 4)
  (setq-default nxml-child-indent 4 nxml-attribute-indent 4)
  (setq-default c-basic-offset 4)
  ;;neotree
  (global-set-key (kbd "<f9>") 'neotree-toggle)
  (global-set-key (kbd "C-j") 'avy-goto-word-or-subword-1)
  (spacemacs/toggle-automatic-symbol-highlight)
  )
```

**Comment by TheBB** [comment]
As I said, can you please confirm whether `web-mode-markup-indent-offset` actually has the value 4 in an XML file?

**Comment by TheBB** [comment]
Sorry, it seems xml files aren't in web-mode by default. That was a customization I had made myself.

**Comment by maplewizard** [comment]
@TheBB I don't have web-mode-markup-indent-offset. I ckecked lua-indent-level it's 4, but it work with still 2 indent.

**Comment by mrvon** [comment]
Yes, setq lua-indent-level can't work!
because function dotspacemacs/user-config() is run before lua-mode 's default setting function.

**Comment by maplewizard** [comment]
@mrvon How to run it after lua-mode's default setting function?

**Comment by yinlei** [comment]
@maplewizard Like this change the loader order of lua layer 

     c-c++
     lua
     markdown
     auto-completion
     better-defaults
     emacs-lisp
     git
     markdown
     org
     
setq lua-indent-level can work!!!

**Comment by mrvon** [comment]
@maplewizard  Sorry, I don't know. I am a spacemacs beginner.

**Comment by slowfeel** [comment]
you should change the lua-indent-level in file: layers/+lang/lua/package.el

**Comment by TheBB** [comment]
We shouldn't have that there in the first place.

**Comment by TheBB** [comment]
Fixed the lua stuff in https://github.com/syl20bnr/spacemacs/commit/ff8d4dada8b6e2b68523ef017cc849a40851d12f at least. Now it should work in `dotspacemacs/user-config`.

**Comment by siddharthist** [comment]
Is there no `'xml-mode-hook`? Here's how I do it for shell scripts. 
```lisp
  (defun siddharthist/sh-mode ()
    "My own personal preferences for sh-mode"
    (setq sh-basic-offset 2
          sh-indentation 2))
  (add-hook 'sh-mode-hook 'siddharthist/sh-mode)
```

**Comment by d12frosted** [comment]
@siddharthist there is `nxml-mode-hook`. So yeah, it's also possible to use hooks.

**Comment by d12frosted** [comment]
And also I can confirm that on `develop` branch setting `nxml-child-indent` to `4` works.

```
(defun dotspacemacs/user-config ()
  "Configuration function.
This function is called at the very end of Spacemacs initialization after
layers configuration."
  (setq nxml-child-indent 4))
```
