### ISSUE TITLE
Smart parentheses in ipython-notebook

### ISSUE THREAD

**Issue by aldanor** [syl20bnr/spacemacs#5491]
#### Description

Smart parentheses are not behaving well in `ipython-notebook` (proper modes not enabled?).
#### Reproduction guide
- Start Emacs
- Open an IPython notebook, connect to it via `SPC a i n`
- Type `print()` in a new cell, observe the error; you may or may not be able to close the parenthesis
- Alternatively: type

``` python
foo()
bar()
```

Then, delete the closing parenthesis of `foo()` and type it again. You then end up with something like this:

``` python
foo()
bar)()
```
- Alternatively: type `foo('bar')`. You will end up with

``` python
foo('bar)')
```

_Observed behaviour:_
`smartparens-mode` and `smartparens-global-mode` are enabled in Python buffers but not enabled in `ipython-notebook` layer. This leads to some weird behaviour when trying to close parentheses, sometimes extra parens are inserted or it won't let you close them at all. In any case, the error message is: "Search failed. This means there is an unmatched expression somewhere or we are at the beginning/end of file.", which seems to be an `:unmatched-expression` error thrown in `sp-get-paired-expression`. 

Enabling `smartparens-mode` and `smartparens-global-mode` seems to fix it, but I'm not sure how it should be fixed properly.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: origin/develop (rev. 82fdd9a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 csv deft emacs-lisp eyebrowse
 (git :variables git-magit-status-fullscreen t magit-save-repository-buffers 'dontask magit-revision-show-gravatars nil)
 (github :variables gh-profile-default-profile "aldanor")
 html javascript ipython-notebook markdown org
 (python :variables python-fill-column 99 python-test-runner 'pytest)
 rust search-engine
 (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t)
 shell-scripts spacemacs-helm syntax-checking themes-megapack version-control yaml aldanor dash osx)
```

**Comment by aldanor** [comment]
Looks like adding
```lisp
(add-hook 'ein:notebook-multilang-mode-hook 'smartparens-mode)
```
to `post-init-ein` should be sufficient to address the first problem.

The second problem (closing parenthesis on one line erroneously duplicates it and closes it on the next line) seems to also be present in `python-mode` which is quite sad.

**Comment by TheBB** [comment]
@StreakyCobra Does this have something to do with your trick?

**Comment by StreakyCobra** [comment]
Unless [`dotspacemacs-smart-closing-parenthesis`](https://github.com/syl20bnr/spacemacs/blob/82fdd9a511f1f5cc4f371b91ce691308686f8ec6/layers/%2Bspacemacs/spacemacs-editing/packages.el#L297-L313) is set to `t` (what [shouldn't be the case by default](https://github.com/syl20bnr/spacemacs/blob/82fdd9a511f1f5cc4f371b91ce691308686f8ec6/core/core-dotspacemacs.el#L252-L255)), it shouldn't have any effect on Spacemacs, buuut…

I can indeed reproduce the Python bug when it's activated, it's related to the use of `sp-navigate-close-if-unbalanced t` in the function, turning it off makes this bug disappear. So I would say it's a bug between smartparens and python as I don't notice this behaviour in other modes, like in `sh-mode` for instance.

@aldanor I suppose you also have `dotspacemacs-smart-closing-parenthesis` set to `t`, it's what is causing your bug, try turning it off.

-----

Keeping `sp-navigate-close-if-unbalanced` set to `t` is useful for this kind of case:

Starting with the following text (not in the last line of the file, this is a limitation of smartparens, no idea why…):

    ([auie

And pressing two times a closing parenthesis (`))`):

- When set to `t`:

        ([auie])

- When set to `nil`:

        ([auie))

**Comment by aldanor** [comment]
@StreakyCobra Indeed turning `dotspacemacs-smart-closing-parenthesis` off fixes the second problem. I was actually using it for another feature: in the following example
```
(auie
```
navigate the cursor between `au` and `ie`. and press `)`:
- If smart closing parenthesis is enabled: you get `(auie)` and the cursor jumps to the end.
- Otherwise, you get `(au)ie`.
Kind of sad to have to disable it in Python. Btw I couldn't find any matching issues in `smartparens` repo upstream.

**Comment by StreakyCobra** [comment]
Yes I added this feature recently because it was really useful for dealing with closing parenthesis (bracket, quote, etc.) in a lot of ways. The implementation is more like a hack on top of smartparens, but it's an elegant hack (from my point of view at least, but I'm probably biased :wink:)

I am able to reproduce this with a minimum configuration:

- Start Spacemacs
- Press `SPC q D`, enter `smartparens` and validate
- This restart a stock emacs with just `smartparens` loaded
- `C-x C-f test.py` to open a python file
- Enable smartparens with `M-x smartparens-mode`
- Turn on `sp-navigate-close-if-unbalanced` with `M-: (setq sp-navigate-close-if-unbalanced t)`
- Enter the following content:

        foo(
        bar()

- Go at the end of the first line
- Call `sp-up-sexp` with `M-x sp-up-sexp`
- You can observe the wrong behaviour giving this:

        foo(
        bar)()

So it seems to be a `smartparens` bug (if it is a bug at all, maybe it's the expected behaviour?).

I don't have a lot of time these days, so I encourage you to report it upstream to `smartparens` :smiley: You can give them the reproduction steps and eventually point them to this link if you do it.

**Comment by aldanor** [comment]
@StreakyCobra Yea, looks like it happens in all prog modes, not just Python (e.g. fire a scratch buffer with prog-mode and the error is the same).
