### ISSUE TITLE
A problem when I publish org into html

### ISSUE THREAD

**Issue by jcppython** [syl20bnr/spacemacs#5495]
* code-1
![lisp](https://cloud.githubusercontent.com/assets/5669903/13767306/08230b26-eaa4-11e5-99f6-7f971a962c28.png)

* code-2
![cpp](https://cloud.githubusercontent.com/assets/5669903/13767308/0ce08c7e-eaa4-11e5-860d-cea9cc97ab5a.png)

The org file contain the code-1 or code-2 snippet.
For code-1, it can be published into html file.
However, some error occured with code-2 as shown:

Wrote /home/usr/Documents/blog/Public/Cpp/temp.org
org-babel-exp process C++ at line 2...
eval-buffer: Required feature `deferred' was not provided

GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8)
Org-mode version 8.3.4 (8.3.4-15-gdd9be3-elpa @ /home/usr/.emacs.d/elpa/org-20160314/)
spacemacs-version: 0.105.14

**Comment by TheBB** [comment]
I can't reproduce this. I was able to export the second example to an HTML file without error, and no feature "deferred" was provided.

Please update your issue with exact reproduction steps.
