### ISSUE TITLE
Flycheck stopped working in Haskell mode

### ISSUE THREAD

**Issue by tranma** [syl20bnr/spacemacs#5496]
#### Description
`syntax-checking` in `haskell-mode` stopped working after updating spacemacs + packages. It fails to read the cabal file.

#### Reproduction guide
- Start Emacs
- Open any Haskell source file in a sandbox'd project

*Observed behaviour:*
- See message `File mode specification error: (void-function haskell-cabal-get-setting)`
- See message:
```
Suspicious state from syntax checker haskell-ghc:
Checker haskell-ghc returned non-zero exit code 1, but no errors from output:
<command line>: cannot satisfy -package <SOME-ADD-SOURCE-DEPENDENCY>
    (use -v for more information)

Checker definition probably flawed.
```
- No error reported from the `haskell-ghc` checker, save for a `!` in the gutter, which is probably from `flymake`.

*Expected behaviour:*
- Normal `flycheck` error reporting from the `haskell-ghc` checker, with highlighting and error tooltip.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx auto-completion themes-megapack syntax-checking c-c++ markdown haskell latex)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by tranma** [comment]
Looks like the versions of flycheck and haskell-mode isn't compatible, flycheck-haskell expects something that used to exist:
```
In end of data:
flycheck-haskell.el:306:1:Warning: the function `haskell-cabal-get-setting' is
    not known to be defined.
```

**Comment by TheBB** [comment]
Here: https://github.com/flycheck/flycheck-haskell

**Comment by tranma** [comment]
pending https://github.com/flycheck/flycheck-haskell/issues/54

**Comment by TheBB** [comment]
https://github.com/haskell/haskell-mode/pull/1215

This was fixed by haskell-mode by providing an alias.
