### ISSUE TITLE
Using emacs-nox, adding syntax-checking layer produces error on startup

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#5499]
Using emacs-nox, adding syntax-checking layer following error is seen on startup

```
Error in post-command-hook (flycheck-pos-tip-hide-messages): (void-function pos-tip-hide)
```
#### System Info
- OS: gnu/linux
- Emacs: 24.4.91.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 82fdd9a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:

``` elisp
(spacemacs-ivy auto-completion emacs-lisp git org
               (shell :variables shell-default-height 30 shell-default-position 'bottom)
               syntax-checking version-control ruby-on-rails python go javascript)
```

Related to #5498

**Comment by syl20bnr** [comment]
@nixmaniack Are there any more issues about this ?

If there are too much issues about Emacs built with no graphical support we may just skip them.

**Comment by nixmaniack** [comment]
No, I haven't faced any more issues apart from these couple of issues which I have reported. 

IMO, It'd be nice to address them as there are users who use it on remote systems with no X.

**Comment by nixmaniack** [comment]
`flycheck-pos-tip-hide-messages` handles this using `(display-graphic-p)` hence no more valid. Haven't faced issues on other system.
