### ISSUE TITLE
newly installed package(go-mode) was deleted as orphan

### ISSUE THREAD

**Issue by LER0ever** [syl20bnr/spacemacs#5500]
#### Description
I installed the emacs-w64 on sf.net and installed spacemacs without modifying any of the configuration. And then I use package-install to setup the ***go-mode***. After restarting the emacs, go-mode was automatically deleted as orphan package

#### Reproduction guide
Windows 10 10586.164 64-bit
- emacs binary from [https://sourceforge.net/projects/emacsbinw64](https://sourceforge.net/projects/emacsbinw64/)
- cd to where emacs is extracted. the folder contains bin, libexec, share, var
- git clone https://github.com/syl20bnr/spacemacs.git 
- make a new emacs.bat under emacs_directory inserting the following

> @echo off
> set HOME=%~dp0\spacemacs\
> bin\runemacs.exe %*

- and now the folder contains **bin, libexec, spacemacs, share, var, emacs.bat**
- and double click the bat. Spacemacs start to configure automatically and everything was ok
- Alt+X and type plugin-install to install go-mode
- restart emacs
- **and the go-mode was successfully deleted as orphan package :(**

**Is something wrong with my emacs setup?** cause I'm just a newbie of Emacs from vim.
I haven't tried on my Manjaro yet, hope that won't be a Windows problem.

**Comment by AlejandroCatalina** [comment]
Every package not included in spacemacs will be marked as orphan and so deleted.

To avoid this, just include it in your `dotspacemacs-additional-packages`, in your `.spacemacs` file or add it to the right layer. This is documented in the official documentation, I'd bet.

**Comment by TheBB** [comment]
Also, if you want to use go, just add the go layer instead of installing the packages yourself.

**Comment by LER0ever** [comment]
Thank you! So it's my problem, sorry that I haven't gone through the related manual. I did as you guys said and it works out OK!
