### ISSUE TITLE
Without org layer, `,` displays "No previous search" in org mode

### ISSUE THREAD

**Issue by edrex** [syl20bnr/spacemacs#5502]
I'd like to leave the org layer out, since it pulls in a bunch of optional packages I don't need. Unfortunately, without it the major mode leader doesn't work in org mode.

`spc ? ,` with org layer: `,         	spacemacs-org-mode-map-prefix`

without org layer: `,         	evil-repeat-find-char-reverse`

Maybe the solution is to split the org layer up a bit, with a minimal default to make org work nicely with evil mode, and then an `org-extra` layer with all the bling. Or, since org is built into Emacs, maybe the basic evil integration should be built into spacemacs?

**Comment by TheBB** [comment]
Yeah, this is entirely expected. If you want to use only parts of the org layer you should just exclude the packages you don't want.

**Comment by calebmeyer** [comment]
That seems reasonable, but since spacemacs documentation is all in org format, it's very hard to browse without the org layer. For example, pressing `RET` on a table of contents link doesn't follow it unless you have the org layer enabled.

**Comment by TheBB** [comment]
That will be fixed by https://github.com/syl20bnr/spacemacs/pull/5372

I don't see any reason to further split the org layer. After all that's exactly the kind of thing `dotspacemacs-excluded-packages` is for.

**Comment by edrex** [comment]
Ah, I didn't know about that PR, good to hear. I guess I'll leave this open till that lands.

**Comment by edrex** [comment]
Meh, closing.
