### ISSUE TITLE
Items are not aligned into columns 

### ISSUE THREAD

**Issue by ericgroom** [syl20bnr/spacemacs#5504]
#### Description
Items are not aligned into columns

#### Reproduction guide
- Start Emacs
- Go into any SPC menu

*Observed behaviour:*
Items are not aligned into columns but are just jumbled together, with the next one starting wherever the last item in it's row ended.

*Expected behaviour:*
On past installations on OSX the items have been arranged into columns

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp games java org ranger ruby spell-checking spotify syntax-checking themes-megapack)
```

This is a new install
![spacemacs_issue](https://cloud.githubusercontent.com/assets/16406453/13798040/6f02f9fc-eacf-11e5-8227-105463b315cf.png)

**Comment by StreakyCobra** [comment]
CC @justbur

**Comment by d12frosted** [comment]
My eyes might lie to me, but it looks like you don't use monospaced font.

**Comment by justbur** [comment]
> My eyes might lie to me, but it looks like you don't use monospaced font.

Yep that looks like the problem

**Comment by StreakyCobra** [comment]
@d12frosted You have good eyes it seems :-)

**Comment by syl20bnr** [comment]
SPC is not even needed, the home buffer is not right too. You have to use a monospace font like `source code pro` if you want text to be correctly aligned.

**Comment by ericgroom** [comment]
Thanks guys! I'm still setting up my first arch install so I can't believe I missed something this simple! The aur package must not install the default font or something.

**Comment by a13ph** [comment]
To be fair, expected by end-user behavior would be same regardless of font type.
I'm pursuing proportional font alignment solutions for Emacs for other purposes as well

**Comment by ericgroom** [comment]
I just got on my arch install and now everything is aligned but I didn't change the font yet so I have no idea what went wrong.
