### ISSUE TITLE
ESC after entering insert mode with o does not exit insert mode

### ISSUE THREAD

**Issue by raddevon** [syl20bnr/spacemacs#5507]
Escape should always exit insert mode when using the Vim keybindings, but I'm not getting that when I enter insert mode using `o` (newline below). Instead, I get the shortcut suggestion window for ESC
![esc shortcuts](https://cloud.githubusercontent.com/assets/2027711/13810293/7d534392-eb45-11e5-958d-aa7f8f6fba35.png)

**Comment by raddevon** [comment]
This occurs under different circumstances than I originally thought. It appears that, if I only add a newline (`Enter`), escape does not exit insert mode even if I enter insert mode with `i` or `a`. Escape works properly even with `o` as long as I enter something besides a newline before trying to exit insert mode. I can enter text in addition to a newline. The problem occurs if the newline is the only entry in insert mode.

**Comment by StreakyCobra** [comment]
Can you update your post to inculde the information shown [there](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? (System info, precise reproduction step, …) Thanks

**Comment by raddevon** [comment]
Thanks for being so responsive, @StreakyCobra. I'm not sure what happened, but, after having my computer in standby for a few hours and bringing it back up, I can't replicate this anymore. Can't think of anything else that has changed, but it seems something has. :smile:

**Comment by StreakyCobra** [comment]
Glad to hear :-)
