### ISSUE TITLE
Text objects "vig" and "yig" only work if you aren't on the last or first line of a file.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#5512]
#### Description
If you are on the last, or first line of a file, and you type `vig` to select the entire file, you will get one of the following messages:

`End of buffer`
`Beginning of buffer`

And the selection will not occur.

#### System Info
- OS: darwin
- Emacs: 24.5.7
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 82fdd9a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(unscroll auto-completion xkcd emacs-lisp git yaml github javascript html markdown extra-langs python ruby org osx python django syntax-checking spell-checking version-control lua colors spacemacs-layouts vimscript spacemacs-helm
          (c-c   :variables c-c  -enable-clang-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by StreakyCobra** [comment]
@TheBB :point_up: You are the specialist of text object.

**Comment by TheBB** [comment]
If so I can report it's fixed in https://github.com/syl20bnr/spacemacs/commit/6d5f55f09e65f46c93d35f812954f9c22d3e2066

**Comment by synic** [comment]
Can confirm, this is working much better.  Thanks!
