### ISSUE TITLE
`SPC h l f3` adds layer name to the wrong place

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#5514]
#### Description (and lack of Reproduction guide)
- Start Emacs
- ??? delete some comments in `init.el` aka `.spacemacs` ???
- try installing layers from `SPC h l` ... `f3` (in my case `xkcd` was one of those and first and only to be added, even if badly)

_Observed behaviour:_
Actual layer list wasn't changed at all, instead addition got jammed into the comment mentioning it

```
   ;; the list `dotspacemacs-configuration-layers'. (
   xkcd
default t)
```

![screenshot from 2016-03-17 02-36-37](https://cloud.githubusercontent.com/assets/577817/13832039/b8626182-ebf1-11e5-9b18-f9d98483c885.png)

_Expected behaviour:_
The added layers should obviously go to their proper list

_Speculations_
- parser got confused
- my lack of repro steps will be forgiven
- hopefully a trivial issue to fix despite no recipe
#### System Info
- OS: gnu/linux
- Emacs: 25.1.50.2
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. d723a7e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(eyebrowse org elfeed version-control git github markdown themes-megapack colors emoji erc deft emacs-lisp clojure python common-lisp javascript java spacemacs-helm auto-completion spell-checking syntax-checking ranger semantic
           (shell variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by StreakyCobra** [comment]
CC @CestDiego

**Comment by CestDiego** [comment]
This might be the parser being confused... I'm going to check it out. I would also love to have a more consistent install package thing... But I don't know partial sexp parsing.

**Comment by a13ph** [comment]
@CestDiego i think it spews out it's search (which iirc is pretty basic... http://www.xkcd.com/1171/ ) if you delete all mentions of layer variable in config file before installing from helm.
Installation is really basic one - `SPC h l` (choose one or some) `F3`/`C-z install`
...
This is what i get if I delete comments before layer declaration fully:
![screenshot from 2016-03-18 04-51-42](https://cloud.githubusercontent.com/assets/577817/13866331/c19a97b0-eccd-11e5-8a7b-3aa7ee3b9af3.png)

This shouldn't be so. 
Comments should have no influence on code not specifically related to them.

**Comment by a13ph** [comment]
And if whole thing gets much more consistent, it would improve chances at linking paradox UI to this method.

**Comment by a13ph** [comment]
Yeah, regex used there is not great (and in general regex is questionable).
Maybe use an actual parser?

**Comment by bmag** [comment]
For comparison, here are the regexps used by `helm-spacemacs-help//go-to-dotfile-variable` and `dotspacemacs/add-layer`:
```elisp
;; helm-spacemacs-help//go-to-dotfile-variable
(format "^[a-z\s\\(\\-]*%s" candidate) ; => "^[a-z\s\\(\\-]*dotspacemacs-configuration-layers"
;; dotspacemacs/add-layer
"dotspacemacs-configuration-layers *\n?.*\\((\\)"
```

Sources:
- [helm-spacemacs-help.el](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+completion/helm/local/helm-spacemacs-help/helm-spacemacs-help.el)
- [core-dotspacemacs.el](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-dotspacemacs.el)

P.S `ivy-spacemacs-help//go-to-dotfile-variable` uses the same regexp as `helm-spacemacs-help//go-to-dotfile-variable`
