### ISSUE TITLE
Themes appearing with dark blue background in terminal.

### ISSUE THREAD

**Issue by portOdin** [syl20bnr/spacemacs#5517]
#### Description
When I try to use a theme with a background which isn't black or grey, the background always appears as a dark blue. Though I also have the same problem using some themes which _do_ have dark backgrounds. Here is Spolsky in terminal Emacs for example: 
![screen shot 2016-03-17 at 12 23 52 am](https://cloud.githubusercontent.com/assets/5838941/13836345/995384ee-ebd6-11e5-8bb3-2043456456da.png)

And here it is in the GUI:
![screen shot 2016-03-17 at 12 22 36 am](https://cloud.githubusercontent.com/assets/5838941/13836341/934dd590-ebd6-11e5-8caa-89eab7e6fecb.png)

#### Reproduction guide
- Start Emacs in terminal.
- Select a theme with a non-black or grey background. For example, SPC-T-h solarized-dark. 

*Observed behaviour:*
Theme background isn't correct colour in terminal Emacs.

*Expected behaviour:*
Theme should have the correct colour for the current theme in terminal.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(themes-megapack react better-defaults github
                 (version-control :variables version-control-diff-tool 'git-gutter  version-control-global-margin t)
                 osx markdown
                 (vinegar :variables vinegar-reuse-dired-buffer t)
                 org prodigy search-engine
                 (syntax-checking :variables syntax-checking-enable-by-default nil)
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 yaml
                 (ruby :variables ruby-version-manager 'rvm)
                 ruby-on-rails python lua html command-log javascript emacs-lisp common-lisp
                 (clojure :variables clojure-enable-fancify-symbols t)
                 ranger gtags
                 (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
                 (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
                 (ibuffer :variables ibuffer-group-buffers-by 'projects)
                 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
                 auto-completion
                 (shell :variables shell-default-position 'full shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh"))
```

I doubt this is reproducible because I probably have something setup wrong. I could use the help in figuring out what that is.

**Comment by cpaulik** [comment]
This is known problem with themes that do not support the terminal. Which unfortunately are quite a lot in emacs. See also the [FAQ](http://spacemacs.org/doc/FAQ.html#orgheadline14) and [this existing issue](https://github.com/syl20bnr/spacemacs/issues/1269).

**Comment by TheBB** [comment]
Closing this as duplicate.

**Comment by portOdin** [comment]
Could you tell me the Spacemacs way to change the background colour of a theme? Or maybe how to remove the colour all together, so that my iTerm background colour shows through? It's strange that the only colour that isn't correct in all these themes is the background. Though at least that should be an easy fix.
