### ISSUE TITLE
Using multi-term with zsh, tab completion duplicates text

### ISSUE THREAD

**Issue by lionize** [syl20bnr/spacemacs#5519]
#### Description
Strange behavior in multi-term with zsh when using tab completion. Text artifacts like duplicating the original typed command appear.

#### Reproduction guide
- Start Emacs
- Open multi-term with `SPC a s m`
- Attempt to use TAB completion

*Observed behaviour:*
![duplicate text](https://cloud.githubusercontent.com/assets/1954752/13842214/65264788-ec03-11e5-801e-6d7952b681fb.gif)

Trying to use tab completion will duplicate the originally-typed command. This text cannot be deleted, though it doesn't have an effect on what is actually return when hitting enter.

*Expected behaviour:*
No duplicated text.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults colors syntax-checking themes-megapack osx shell git org react erlang elixir javascript html emacs-lisp
                 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

I suspect this has something to do with using oh-my-zsh. I get some sort of message in a popup window about my PATH when starting Emacs, but it disappears too quickly for me to read what it says.

**Comment by StreakyCobra** [comment]
I can't reproduce this on the `develop` branch with my config (also using zsh).

**Comment by zhengpd** [comment]
@lionize Have you solved this? I am facing the same issue on master branch, using multi-term and oh-my-zsh.

**Comment by zhengpd** [comment]
It turns out that the unicode characters in my shell prompt cause the problem. I fixed it by setting `export LANG='en_US.UTF-8'` in `~/.zshrc` .

**Comment by markg85** [comment]
Sorry for reviving this old topic, but i just ran into the very same issue. The solution here hinted to a proper fix in my solution.

I was having a system locale of en_US, but the desktop environment was set as en_NL for the region while everything was still English. So those locales need to match.

For reference, in your desktop environment do:
`env | grep LANG`
and do:
`sudo localectl`

You want both to output the same locale.If the former is wrong, it's your desktop Locale settings.
If the latter is wrong you need to edit /etc/locale.conf

Putting it in ~/.zshrc is imho not the solution as "something" had set it to something wrong which you merely overwrite in that case. You're not actually fixing it.

Hope this helps for anyone who has the same issue and finds this post via google :)
