### ISSUE TITLE
Using multi-term, typing too many characters make text disappear

### ISSUE THREAD

**Issue by lionize** [syl20bnr/spacemacs#5520]
#### Description
When typing a line to the end of the screen in multi-term, text is hard-wrapped. After deleting text, everything previously on the line is cleared.

#### Reproduction guide
- Start Emacs
- Open a shell using `SPC a s m`
- Type text past the end of the window, and then attempt to delete it

*Observed behaviour:*
![long line](https://cloud.githubusercontent.com/assets/1954752/13842538/0fea5eba-ec05-11e5-822e-ca782a8f3a4b.gif)

The text is still there, but it disappears. If you hit `RET` it will attempt to send the text, and if you hold delete you can delete all of it, but you can't see it or how much of it is still there.

*Expected behaviour:*
Text should behave like any other window, wrapping to further columns temporarily and then restoring to the start of the line when scrolling back in text.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults colors syntax-checking themes-megapack osx shell git org react erlang elixir javascript html emacs-lisp
                 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by StreakyCobra** [comment]
I can't reproduce this on the develop branch with my config.

**Comment by growlove** [comment]
@StreakyCobra Are you using oh-my-zsh? It looks like it might be related to that. I tried a fresh spacemacs install on the develop branch and had the same behavior, so I moved my zshrc to a different folder and then opened multi-term and couldn't reproduce the problem.

**Comment by StreakyCobra** [comment]
> Are you using oh-my-zsh?

Yes, with a slightly customized `agnoster` theme.

**Comment by growlove** [comment]
Interesting. Using `agnoster` I don't get this behavior, but with most of the other themes that I've tried so far, I am having this issue. The default `robbyrussell` theme does it.

**Comment by StreakyCobra** [comment]
So it's probably not a Spacemacs bug. This should be reported upstream, but I don't know where. The problem lie between oh-my-zsh themes and `multi-term`.

**Comment by nochiel** [comment]
This issue appears to be connected to the use of [zsh-users/zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting). A report on the issue can be found on [emacs-devel](http://lists.gnu.org/archive/html/emacs-devel/2016-11/msg00556.html).

Here is the code I use to prevent the syntax highlighting from messing up term.el.
In .zshrc:

```
if [[ -z ${INSIDE_EMACS} ]]; then
    # Bundles that break emacs/term.el
    # Syntax highlighting bundle.
    antigen bundle zsh-users/zsh-syntax-highlighting
fi

```

@lionize Are you using the syntax-highlighting plugin?

**Comment by lockie** [comment]
I'm also affected by this bug and code snippet posted by @nochiel fixes the problem. Thanks mate!
