### ISSUE TITLE
`SPC h I` not work in windows.

### ISSUE THREAD

**Issue by jmjoy** [syl20bnr/spacemacs#5521]
#### System Info
- OS: windows-nt
- Emacs: 25.0.92.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((haskell :variables haskell-enable-hindent-style "fundamental"))
```

When I press `SPC h I`, chrome is opend with the below link but just display a empty page.

https://github.com/syl20bnr/spacemacs/issues/new?body=%3CPLEASE%20REPLACE%20ALL%20UPPERCASE%20EXPRESSIONS%20AND%20DELETE%20THIS%20LINE%3E%0D%0A%23%23%23%23%20Description%0D%0ADESCRIPTION%20OF%20THE%20PROBLEM%0D%0A%0D%0A%23%23%23%23%20Reproduction%20guide%0D%0A-%20Start%20Emacs%0D%0A-%20REPRODUCTION%20STEPS%0D%0A%0D%0A*Observed%20behaviour:*%0D%0ADESCRIPTION%20OF%20THE%20OBSERVED%20BEHAVIOUR%0D%0A%0D%0A*Expected%20behaviour:*%0D%0ADESCRIPTION%20OF%20THE%20EXPECTED%20BEHAVIOUR%0D%0A%0D%0A(%LAST_KEYS%)%0D%0A%0D%0A%23%23%23%23%20System%20Info%0A-%20OS:%20windows-nt%0A-%20Emacs:%2025.0.92.1%0A-%20Spacemacs:%200.105.14%0A-%20Spacemacs%20branch:%20master%20(rev.%20a298a5a)%0A-%20Graphic%20display:%20t%0A-%20Distribution:%20spacemacs%0A-%20Editing%20style:%20vim%0A-%20Completion:%20helm%0A-%20Layers:%0A%60%60%60elisp%0A((haskell%20:variables%20haskell-enable-hindent-style%20%22fundamental%22))%0A%60%60%60%0A%0D%0A%0D%0A%23%23%23%23%20Backtrace%0D%0A%60%60%60%0D%0ABACKTRACE%20IF%20RELEVANT%0D%0A%60%60%60%0D%0A

**Comment by StreakyCobra** [comment]
It is because of the [`(%LAST_KEYS%)`](https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/REPORTING.template#L15) which is present in your description. This part should either be replaced by the last pressed key when `SPC u SPC h I` is used, or removed when `SPC h I` is called. Not sure why this is still there.

Because of the `%` sign, the URL is not interpreted correctly and the page is not displayed.

**Comment by jmjoy** [comment]
Is there somebody has the same problem in windows? I encounter this problem in two windows machine, but it's work well in my Ubuntu.

**Comment by uruk1993** [comment]
I also encounter this problem in my windows machine. And when I deleted `(%LAST_KEY%)` It works.

**Comment by StreakyCobra** [comment]
It seems to be a Windows problem, but for now I haven't found an explanation about why any of the used functions would behaves differently on this platform.
