### ISSUE TITLE
Sometimes C-n / C-p jumps too much

### ISSUE THREAD

**Issue by d12frosted** [syl20bnr/spacemacs#5522]
#### Description
At one point (can't remember, when exactly), `C-n` and `C-p` started to behave pretty strange. Instead of moving down or up by one line it jumped by half-screen or so. Now I can 100% reproduce it so opening new issue. 

#### Reproduction guide
- Start Emacs
- Open any buffer with large amount of text (at least 5 screens)
- Use `C-v` at least 3 times (amount is not related to bug, it just has to be big enough)
- Suppose that cursor is on line `A`. Press `M-v`.
- Press `M-v`.
- Cursor is on line `B` (which is less than `A`).
- Press `C-n`.

*Observed behaviour:*
Cursor is on line `C` which is not `B + 1`, but something much closer to `A`.

*Expected behaviour:*
Cursor is on line `B + 1`. 

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 6d5f55f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion :disabled-for org)
 better-defaults colors dash
 (deft :variables deft-directory
   (concat d12-path/dropbox "Apps/deft"))
 elfeed emoji eyebrowse
 (git :variables git-magit-status-fullscreen t)
 github
 (org :variables org-enable-github-support t org-bullets-bullet-list
      '("◉" "○" "✿" "❀" "✸"))
 pandoc ranger restclient syntax-checking spacemacs-layouts spacemacs-helm spell-checking
 (shell :variables shell-default-term-shell "/usr/local/bin/fish")
 version-control no-dots d12frosted-core d12frosted-org
 (csharp :variables omnisharp-server-executable-path "~/Developer/Other/omnisharp-roslyn/artifacts/build/omnisharp/omnisharp")
 emacs-lisp erlang
 (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "chris-done" haskell-tags-on-save nil haskell-process-log t haskell-process-reload-with-fbytecode nil haskell-process-use-presentation-mode t haskell-process-suggest-remove-import-lines nil haskell-process-suggest-hoogle-imports nil haskell-interactive-mode-include-file-name nil haskell-interactive-mode-eval-pretty nil haskell-process-suggest-haskell-docs-imports nil)
 (html :variables web-mode-markup-indent-offset 2 web-mode-attr-indent-offset 2 web-mode-code-indent-offset 2 web-mode-css-indent-offset 2 web-mode-sql-indent-offset 2 css-indent-offset 2)
 (javascript :variables js-indent-level 2 js2-basic-offset 2)
 lua markdown python ruby shell-scripts yaml react)
```

**Comment by d12frosted** [comment]
P. S. it doesn't happen if you `C-l` before `C-n`.

**Comment by StreakyCobra** [comment]
> P. P. S. I think I know what is it related to, but can't remember the name of the feature that allows severals line visible before scrolling screen. 

[`smooth-scrolling`](https://github.com/aspiers/smooth-scrolling/) ?

**Comment by d12frosted** [comment]
Yes, indeed. I was so close :) Haha.

Is it reproducible by anyone else?

**Comment by jramapuram** [comment]
Yes, I submitted a ticket for this: https://github.com/syl20bnr/spacemacs/issues/5456
The issue is with commit `e33a39c7356119cc7201ab16cef7478fdc5b8afa`

**Comment by d12frosted** [comment]
Ah great. Let's track it there then.
