### ISSUE TITLE
spacemacs/counsel-search does not color results, while counsel-ag does

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#5524]
<img width="683" alt="screen shot 2016-03-18 at 4 09 42 am" src="https://cloud.githubusercontent.com/assets/302945/13857880/4545fadc-ecbf-11e5-9be1-5f71df960585.png">
<img width="683" alt="screen shot 2016-03-18 at 4 09 48 am" src="https://cloud.githubusercontent.com/assets/302945/13857881/456cc6bc-ecbf-11e5-9c62-8ff74c700592.png">

To reproduce, simply try calling each function with spacemacs-ivy layer installed.

**Comment by StreakyCobra** [comment]
CC @justbur

**Comment by justbur** [comment]
This is a very recent change in counsel. [This is the line](https://github.com/abo-abo/swiper/commit/e8f516ec7ef27aac83ab4f2abe88bdb2266be514#diff-c7fad2f9905e642928fa92ae655e23d0R1277) that needs to be added.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
