### ISSUE TITLE
projectile-indexing-method 'alien breaks non-vcs exclusions in windows

### ISSUE THREAD

**Issue by JimmyHoffa** [syl20bnr/spacemacs#5527]
**In Windows**

When you use alien search it doesn't go through the whole ignore-directories flow. The VCS find commands use svn or git to list things which will apply your vcs ignores themselves, but the generic non-vcs flow has no way of applying the ignore filters. They should be bundled into the `find` command used for `projectile-generic-command` with something like `-path (ignored-directories) -prune -o` or some such.

Native works fine because it goes through the native indexing's lisp filters that apply the `ignored-directory-p` predicate filter. Alien however does not apply said exclusions.

Repro is simple:

**IN WINDOWS**
Make sure your `projectile-indexing-method` is `'alien` (it's the default in windows, but you can just `(setq projectile-indexing-method 'alien)` in scratch if needed.
 1. M-x shell ret (make sure it puts you in a folder that isn't under any source control)
 2. md foo
 3. cd foo
 4. md bar
 5. cd bar
 6. touch bla
 7. cd ..\
 8. C-x C-f .projectile ret ret
 9. put in the file -/bar
 10. C-x C-s
 11. M-m p f

Notice though your .projectile file has an exclusion for /bar, you still see the file ./bar/bla

If you `(setq projectile-indexing-method 'native)` and then `M-m p f` again, it will then hide the `./bar/bla` file.

**Comment by StreakyCobra** [comment]
What do you want us to do about that? If the problem come from `alien` vs `native`, it's probably an issue to report upstream (to `projectile`). If the problem is that Spacemacs set it to `alien` by default, it's because of performance reasons (https://github.com/syl20bnr/spacemacs/issues/307), but you're free to change it in your config if you prefer the other.

So can you be more clear about what you are expecting from this issue?

**Comment by JimmyHoffa** [comment]
Thanks! I wasn't precisely sure what to do with this since I figured it out; sounds like the right thing is to post it as an issue upstream! I'll go ahead and do that and close this.

Meanwhile:

**Workaround**

For anyone experiencing this issue in windows and perhaps disappreciating node_modules or some other bulky generated folder filling up your projectile files search, add to your `.spacemacs` configuration section:

`(setq projectile-indexing-method 'native)`
