### ISSUE TITLE
Yapf seems not work very well

### ISSUE THREAD

**Issue by uruk1993** [syl20bnr/spacemacs#5533]
#### Description

I use the python layer and apply the function py-yapf-buffer twice, it works but append a `^M` marker at the end of every line. And after I save the buffer, the `^M` markers disappear and insert a blank line beneath every line.  
#### System Info
- OS: windows-nt
- Emacs: 25.0.50.1
- Spacemacs: 0.105.14
- Spacemacs branch: nil (rev. 198436a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion github better-defaults emacs-lisp python git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking html version-control erc
                 (elfeed :variables rmh-elfeed-org-files
                         (list "~/.emacs.d/private/elfeed1.org")))
```

**Comment by cpaulik** [comment]
I would be surprised if this is a Spacemacs problem. Have you tried what happens when you use `yapf` in the command line? This seems to be a Windows only problem since `^M` are the Windows line endings.

**Comment by uruk1993** [comment]
Yes, you are right. Using yapf in command line make things done, there are no `^M`makers any more.And I make a mistake in the issue description, I actually apply py-yapf-buffer twice.In the first time it works very well,but in the second time, `^M` makers appear

**Comment by cmr** [comment]
WIth yapfify-buffer, I cannot reproduce on Linux.
