### ISSUE TITLE
Freeze with open file command (helm Spc f f  or :e <tab>)

### ISSUE THREAD

**Issue by kmiasko** [syl20bnr/spacemacs#5534]
#### Description
When i try to open a file with Spc f f helm buffer doesn't show and Emacs freezes
(with high cpu usage). Same happens with :e command. Size of the directory doesn't matter,
tried in directory with only few files.

#### Reproduction guide
- Start Emacs
- Spc f f or :e <tab>

*Observed behaviour:*
After Spc f f Emacs freezes and no helm buffer is shown (emacs uses 80-90% of the cpu)
If i try to open file with :e command, after tab completion only Quit text shows in command bar, and freeze happens.

*Expected behaviour:*
Open helm file open buffer or autocomplete file path with :e 

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults
                 (git :variables git-magit-status-fullscreen t)
                 org
                 (shell :variables shell-default-height 'full shell-default-position 'bottom shell-default-shell 'eshell)
                 gtags syntax-checking version-control react unimpaired evil-snipe evil-commentary javascript html markdown
                 (eyebrowse :variables eyebrowse-display-help nil)
                 (haskell :variables haskell-enable-shm-support t))
```

**Comment by StreakyCobra** [comment]
Probably a duplicate of https://github.com/syl20bnr/spacemacs/issues/5123

**Comment by kmiasko** [comment]
After switching to  `Spacemacs branch: nil (rev. 4f07ff2)` same behavior.

**Comment by kmiasko** [comment]
Ok. I'm lost. It seem that's not a HELM problem. Spacemacs is still unusable for me, even after switching from HELM to spacemacs-ivy. I get random freezes all the time. This doesn't happen with clean emacs.

Recently i've switched to older Radeon HD3850, so maybe thats some graphics problem.

`System:   Host: szuja Kernel: 4.4.6-1-ck x86_64 (64 bit gcc: 5.3.0) Desktop: Xfce 4.12.3 (Gtk 2.24.28)
                 Distro: ManjaroLinux 15.12 Capella`
`Machine:  Mobo: Gigabyte model: P35-DS3P Bios: Award v: F12 date: 06/19/2009`
`CPU:        Dual core Intel Core2 Duo E6750 (-MCP-) speed/max: 2000/2667 MHz`
`Graphics: Card: Advanced Micro Devices [AMD/ATI] RV670 [Radeon HD 3690/3850] bus-ID: 01:00.0
                 Display Server: X.Org 1.17.4 driver: radeon Resolution: 1920x1080@60.00hz
                 GLX Renderer: Gallium 0.4 on AMD RV670 (DRM 2.43.0, LLVM 3.7.1)
                 GLX Version: 3.0 Mesa 11.1.2 Direct Rendering: Yes`
`Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
                 driver: r8169 v: 2.3LK-NAPI port: d000 bus-ID: 05:00.0`
`Drives:      HDD Total Size: 120.0GB (63.7% used)`
`Info:          Processes: 158 Uptime: 2:50 Memory: 1643.3/3955.8MB Init: systemd Gcc sys: 5.3.0
                 Client: Shell (zsh 5.2) inxi: 2.2.36`

`.xsession-errors (xfwm4:1276): xfwm4-WARNING **: XSync timeout for client "emacs@szuja" (0x2e00120)`

or maybe it's a tempfiles thing, i'm using tempfs for /tmp and $HOME/.cache

[LSOF_URL](http://nopaste.linux-dev.org/?1033677)

**Comment by syl20bnr** [comment]
If this is 100% reproducible we have a good chance to track what's responsible for this.

First thing I would try is to reproduce the bug with a minimalistic Emacs with `SPC q D` and choose `helm`, it will restart Emacs with just `helm` enabled.

**Comment by kmiasko** [comment]
Aaaaand it's only my fault. I went line by line in `.spacemacs` and i even don't know when i've pasted some regexp to deal with special characters in a font, and the regex caused those hangs.

Your spacemacs bug reporting script should also include full config, you would noticed this in a moment. Sorry for trouble.
