### ISSUE TITLE
Ansible layer: Activate yaml mode for ansible-filename-re automatically

### ISSUE THREAD

**Issue by kepi** [syl20bnr/spacemacs#5537]
There is `ansible/ansible-filename-re` variable which defines patterns where should be ansible minor mode activated. Problem is that this is used in hook which is load after `yaml` mode is active - but it never happens for files not ending with .yaml extension.

I believe that this layer should be responsible for "full ansible experience". I expect it to automatically turn on `yaml` mode for files according to recommended ansible layout.

This code in user init provide expected behaviour:

    (add-to-list 'auto-mode-alist
                 '("\\(group_vars/.+\\|host_vars/.+\\)" . yaml-mode))

I'm not creating pull request as I'm not sure where and how exactly to add this code in right place.

Also I think that ansible mode should install `yaml` package and not rely on user to activate it. I'm not sure if there is way to depend on another layer or if it is problem to install one package from multiple layers. At least please add to README that `yaml` layer should be activated.

**Comment by nixmaniack** [comment]
Thanks for pointing this out. I have created a PR for it.

> Also I think that ansible mode should install yaml package and not rely on user to activate it. I'm not sure if there is way to depend on another layer 

This is already taken care of in ansible layer. If you enable ansible layer, yaml layer packages are already installed as a dependency. 
Dependency declaration: https://github.com/syl20bnr/spacemacs/blob/bc31eb48784f8af731b53c4f258244517b76a32f/layers/+config-files/ansible/config.el#L12
Also yaml-mode is also there in ansible packages.
https://github.com/syl20bnr/spacemacs/blob/bc31eb48784f8af731b53c4f258244517b76a32f/layers/+config-files/ansible/packages.el#L16

**Comment by kepi** [comment]
Thanks for PR! And also for pointing out those files so I can learn how to fix it next time myself :)

For dependency and yaml-mode - I checked only files in master branch and forgot to take a look into develop branch.

I'm not sure if I'm supposed to close this now when PR exists or leave this open until merged?

**Comment by nixmaniack** [comment]
> I'm not sure if I'm supposed to close this now when PR exists or leave this open until merged?

@kepi  Keep it open. Collaborators would take care of it once merged.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
