### ISSUE TITLE
Motion di( doesn't work when the cursor is on the paren

### ISSUE THREAD

**Issue by exitface** [syl20bnr/spacemacs#554]
This differs from the behavior of both vim and a basic evil install.

Evil, Vim will allow you place the cursor on the outer paren (bold) and type "di(" to remove a,b,c.

function**(**a,b,c){}

With spacemacs, this only works if you're inside the parens (bold)

function(**a**,b,c){}

**Comment by syl20bnr** [comment]
And it works with point on `)`. You should open an issue in the evil repo if there is not already one.
https://bitbucket.org/lyro/evil/issues

**Comment by ralesi** [comment]
`evil-inner-text-objects-map` is still mapped properly in Spacemacs to `evil-inner-paren`.  I would look there first.  Also, vi( works fine.  It is just the other operator maps.

**Comment by env0der** [comment]
I've checked that this bug is indeed inside ```evil``` itself and created an issue there: https://bitbucket.org/lyro/evil/issue/498/ci-and-di-are-not-working-anymore-when

**Comment by syl20bnr** [comment]
:+1:

**Comment by env0der** [comment]
Version ```20150321.908``` of ```evil``` on Melpa already includes a fix for this issue.
