### ISSUE TITLE
Racket Layer: Parentheses in REPL almost invisible

### ISSUE THREAD

**Issue by stonecauldron** [syl20bnr/spacemacs#5540]
#### Description
Parentheses in the Racket-REPL mode are very hard to distinguish from the background when using a dark colour theme.

#### Reproduction guide
- Install Racket layer
- Start Emacs
- Put a dark colour theme like spacemacs-dark
- Open a racket file and start the REPL (SPC  m s s)
- Write any S-expression: (+ 2 2) for example

*Observed behaviour:*
Parentheses should have a colour with sufficient contrast from the background.

*Expected behaviour:*
Parentheses are difficult to distinguish from the background.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
                 syntax-checking version-control c-c   lua osx scala latex
                 (racket :variables racket-pretty-lambda t)
                 themes-megapack lua javascript)
```

**Comment by StreakyCobra** [comment]
I can't reproduce this (on `develop` at least), and I don't see how it may be related to Spacemacs. It's probably either an issue of racket or an issue of themes.

**Comment by stonecauldron** [comment]
It was indeed related to themes, I've updated the packages and the problem is solved.
