### ISSUE TITLE
Cannot delete buffers in server-mode

### ISSUE THREAD

**Issue by sulami** [syl20bnr/spacemacs#5543]
#### Description

Cannot delete buffers in server-mode that have been opened after launch.
#### Reproduction guide
- Start an Emacs server (`dotspacemacs-persistent-server` doesn't matter)
- Open up `emacsclient -c` (The key here is without a file)
- Open up some file
- Hit `SPC b d`

_Observed behaviour:_

Nothing happens. Buffers can be deleted using `SPC b k` though. Buffers also
persist after closing the client (`SPC q z`, `C-x #` just prints "No server
buffers remain to edit", even if other files/buffers have been opened after launch).

_Expected behaviour:_

Buffer should get deleted, both when asked to, as well as when the frame which
opened them is closed (`server-kill-new-buffers t`).
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t)
 c-c   clojure common-lisp cscope django emacs-lisp evil-commentary git github go haskell html latex markdown org
 (python :variables python-enable-yapf-format-on-save t)
 racket scheme
 (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-protect-eshell-prompt t)
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking version-control yaml)
```

**Comment by jupl** [comment]
[Related perhaps?](4929)
