### ISSUE TITLE
company-show-doc-buffer should not select help buffer

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#5546]
#### Description
company-show-doc-buffer, bound to `f1` and `c-h` in company-active-map, pops up a temporary help buffer to show documentation for current completion. By default, this keeps point in the text buffer, and any further typing or movement dismisses the temp buffer. In spacemacs, focus moves to the new help window, which must then be dismissed manually before continuing typing.

#### Reproduction guide
- Start Emacs with auto-completion layer
- Go to an elisp buffer (`spc fed`)
- type `def`, and when the company candidates popup appears, press `C-h` or `f1`

*Observed behaviour:*

Point moves to help buffer. To continue typing, or selecting candidates, I need to dismiss help buffer with `q`
<img width="685" alt="screen shot 2016-03-20 at 9 00 45 pm" src="https://cloud.githubusercontent.com/assets/302945/13904301/f6b3825a-eede-11e5-855c-988f03baee7a.png">

*Expected behaviour:*

Point remains in place, so that continued input is immediate.
<img width="712" alt="screen shot 2016-03-20 at 9 06 52 pm" src="https://cloud.githubusercontent.com/assets/302945/13904315/b61e8266-eedf-11e5-8d39-baa15458b7a6.png">

I initially thought this was due to `(setq help-window-select t)`, but changing this variable has no effect (doesn't fix the issue in spacemacs, nor does it reproduce the issue in vanilla emacs with just company). I think it might have to do with spacemacs' use of winner-mode, but don't know enough about it. Any ideas?

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 744cd0f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-tab-key-behavior 'cycle auto-completion-return-key-behavior nil auto-completion-enable-sort-by-usage t)
 better-defaults colors clojure dash erc emacs-lisp
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 finance html git github markdown org osx react
 (shell :variables shell-default-shell 'ansi-term)
 syntax-checking spacemacs-ivy themes-megapack vinegar sooheon soo-clojure soo-parens soo-org)
```

**Comment by StreakyCobra** [comment]
@bmag knows about this maybe?

**Comment by bmag** [comment]
The source of the problem seems to be that we set `:noselect nil` for the \*Help\* buffer in `popwin:special-display-config`. By adding the following to `dotspacemacs/user-config`, pressing `C-h` displays the help window without selecting it.
```elisp
(setcdr (assoc "*Help*" popwin:special-display-config)
        '(:dedicated t :position bottom :stick t :noselect t :height 0.4))
```
The `setcdr` only changes the value of `:noselect`. The other values are the same as in default Spacemacs config.
So, perhaps we should change the default settings.

**Comment by StreakyCobra** [comment]
Thx a lot @bmag! Flagging it as `ready for work` if someone want to PR this (@sooheon ?) :smiley:
