### ISSUE TITLE
"," is not bound correctly if the org file contains `#+SETUPFILE:`

### ISSUE THREAD

**Issue by liaowang11** [syl20bnr/spacemacs#5548]
#### Description
`spacemacs-org-mode-map-prefix` is not bound if the org file contains `#+SETUPFILE:`

#### Reproduction guide
- Start Emacs
- Write a new org file with `#+SETUPFILE: ../anyfile.setup` line (any file works)
- Close this buffer
- Reopen the new org file

Work arounds:
- Delete the line `#+SETUPFILE: ../anyfile.setup` 
- Or, edit *anything* in the file, "," is bound back. Weird....

*Observed behaviour:*
<kbd>,</kbd> reports "No previous search" as it's bound to `evil-repeat-find-char-reverse`

*Expected behaviour:*
<kbd>,</kbd> should be bound to `spacemacs-org-mode-map-prefix` 

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: nil (rev. 744cd0f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(personal spacemacs-helm themes-megapack
          (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip nil auto-completion-enable-sort-by-usage t)
          better-defaults emacs-lisp
          (colors :variables colors-enable-nyan-cat-progress-bar t)
          (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
          github
          (ibuffer :variables ibuffer-group-buffers-by 'projects)
          (org :variables org-enable-github-support t)
          (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh")
          (syntax-checking :variables syntax-checking-enable-by-default nil)
          (spell-checking :variables spell-checking-enable-by-default nil)
          (vinegar :variables vinegar-reuse-dired-buffer t)
          (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
          (chinese :variables chinese-enable-youdao-dict t chinese-enable-fcitx t)
          xkcd emoji
          (clojure :variables clojure-enable-fancify-symbols t)
          yaml html java javascript markdown
          (python :variables python-enable-yapf-format-on-save t)
          ruby rust sql scala vimscript c-c   semantic shell-scripts pdf-tools plantuml erc fasd
          (elfeed :variables rmh-elfeed-org-files
                  (list "./feeds.org"))
          (ranger :variables ranger-show-preview t)
          prodigy gtags
          (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
          eyebrowse tmux)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by adamherzog** [comment]
What was the resolution for this? I've starting experiencing the exact same behavior myself, with  the latest spacemacs release and with the develop branch. I'm not sure if it's something broken by the most recent org release or if there's something I should be doing differently.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/6643
