### ISSUE TITLE
Problem with leuven theme and org macros

### ISSUE THREAD

**Issue by brabalan** [syl20bnr/spacemacs#5552]
#### Description

The face for org-macros when using the leuven theme uses a face that does not work well with hl-line-mode. This has been fixed in the leuven theme in 2014 (see https://github.com/fniessen/emacs-leuven-theme/issues/25) but for some reason the fix does not work with spacemacs. Could this be a conflict with the default theme and loading order?

The problematic face is `org-macro`.
#### Reproduction guide
- Start Emacs
- use the leuven theme (I put it first in `dotspacemacs-themes`)
- open an org file
- enter a macro `{{{foo}}}`

_Observed behaviour:_
This is displayed:
![screen shot 2016-03-21 at 08 51 03](https://cloud.githubusercontent.com/assets/1021637/13912915/182918a6-ef42-11e5-9f2b-892c20b3ba2e.png)

This is the problem with hl-line-mode:
![screen shot 2016-03-21 at 08 51 56](https://cloud.githubusercontent.com/assets/1021637/13912924/31941c46-ef42-11e5-8a1e-ff1fcd50d4ee.png)

_Expected behaviour:_
I started a vanilla emacs with leuven theme, and it looks like this:
![screen shot 2016-03-21 at 08 53 11](https://cloud.githubusercontent.com/assets/1021637/13912936/6a7297d6-ef42-11e5-80a8-51b487fa84ca.png)

It works well with hl-line-mode:
![screen shot 2016-03-21 at 08 53 31](https://cloud.githubusercontent.com/assets/1021637/13912950/796df172-ef42-11e5-9a81-5583b7934107.png)

(Note that the color of the highlighted line is also different.)
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'cycle)
 elfeed emacs-lisp finance git gnus javascript latex ocaml org
 (spell-checking :variables spell-checking-enable-auto-dictionary t))
```

**Comment by cpaulik** [comment]
This might be a problem with lazy loading? Changing to the leuven theme after the org file is already loaded looks fine.

**Comment by cpaulik** [comment]
Putting `(spacemacs/load-theme 'leuven)` into your `dotspacemacs/user-config` function can be a workaround.

**Comment by brabalan** [comment]
@cpaulik Thank you for the workaround, it works.

**Comment by brabalan** [comment]
I finally managed to understand where the issue comes from. Putting the leuven theme first in `dotspacemacs-themes` loads the one from emacs (I guess because packages are not loaded yet), so one has to manually load the theme from `user-config`.
