### ISSUE TITLE
How to move cursor vertically within a wrapped line in LaTeX-mode? 

### ISSUE THREAD

**Issue by mqreric** [syl20bnr/spacemacs#5553]
Of course people that write in latex would give a very long enough shit that will be wrapped by Spacemacs and recognized it as a single line.

I use evil-mode such that using J K just gets the cursor to the starting and ending of the line. But it is seemingly inconvenient to move cursor vertically within the line.

So how to solve this problem? 

BTW, why are there LaTeX-mode and latex-mode in the commend list? Did not figure out any difference.

**Comment by NJBS** [comment]
Are you talking about moving by visual lines? You can use `g k`and `g j` to move up and down by visual lines.

**Comment by mqreric** [comment]
Thank you @NJBS 

That's what I need, many thanks.
