### ISSUE TITLE
A Suggestion about supporting fortran

### ISSUE THREAD

**Issue by gxiaotian** [syl20bnr/spacemacs#5560]
I am a physicist. As I know,  I and most of my colleagues use fortran to  write numerical simulation code, and some of us use spacemacs as a c/c++ and python ide as well. So, we hope spacemacs can support fortran. it would be of great help to scientists. Thank you so much!

**Comment by StreakyCobra** [comment]
Fortran mode is already provided by emacs natively. What feature do you miss?

**Comment by gxiaotian** [comment]
But, we need some advanced features, like auto-completion and navigation.

**Comment by StreakyCobra** [comment]
Ok. Spacemacs is a distribution of emacs packages, so there need to be upstream packages providing these functionalities, we will not implement this into Spacemacs directly.

Tagging this as feature request anyway.

**Comment by gxiaotian** [comment]
That will be fine. Thank you so much!

**Comment by JAremko** [comment]
I googled  emacs fortran autocomplete and got this link https://github.com/rosenbrockc/fortpy-el 
Is this package good?
I think we can make a Spacemcs layer out of it.

**Comment by StreakyCobra** [comment]
PR pending: #5991
