### ISSUE TITLE
spaceline window number is duplicated

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#5561]
Starting from commit 944960d, the format for the window number indicator has changed from a single number to ` 1|1 `, ` 1|2 `, etc.

This looks like an intended change, but those who exclude spacemacs-layouts from the config should not see the superfluous layout number.

<img width="683" alt="screen shot 2016-03-22 at 11 14 02 am" src="https://cloud.githubusercontent.com/assets/302945/13940268/46ffa504-f01f-11e5-99a9-abbac4139a18.png">

**Comment by bixuanzju** [comment]
What theme do you use BTW?

**Comment by sooheon** [comment]
@bixuanzju I use zenburn

**Comment by nixmaniack** [comment]
Does this mean eyebrowse(spacemacs workspaces) is no more optional?

**Comment by syl20bnr** [comment]
Eyebrowse is part of the Spacemacs layouts now. What we can do is hiding the workspace number when there is only one workspace.

**Comment by d12frosted** [comment]
> What we can do is hiding the workspace number when there is only one workspace.

And make an option to always show it :)

**Comment by thejan2009** [comment]
What's the status of this issue? Personally, I don't have a use for eyebrowse when spacemacs-layouts are available, and the additional (1) icon annoys me very much. Is there an option to hide it?

**Comment by TheBB** [comment]
Sure, just toggle the segment off. See spaceline documentation.

**Comment by thejan2009** [comment]
Thanks for the hint.
If anyone else needs it, the setting is `(spaceline-toggle-window-number-off)`.

**Comment by TheBB** [comment]
> Eyebrowse is part of the Spacemacs layouts now. What we can do is hiding the workspace number when there is only one workspace.

Implemented this.
