### ISSUE TITLE
Timeline for a 0.106 release?

### ISSUE THREAD

**Issue by wraithan** [syl20bnr/spacemacs#5575]
I've been running `develop` for a while and would really like to move my critical to work flow to a release version instead of an influx version. I'm doing this because of the `.tern-port` problem that was [merged over 2 months ago](https://github.com/syl20bnr/spacemacs/pull/3465) but not released yet. Is there a timeline or an issue I can follow without having to go check the repo on a regular basis to see if this has been release yet?

**Comment by syl20bnr** [comment]
There is no timeline for 0.106 but I can backport it to a new minor version for 0.105.
