### ISSUE TITLE
In Clojure/Evil SPC m e e is inconvenient at line endings

### ISSUE THREAD

**Issue by gilch** [syl20bnr/spacemacs#5576]
Cider was designed for emacs, but not evil. 

See the Gitter @ [March 23, 2016 4:30 PM](https://gitter.im/syl20bnr/spacemacs?at=56f318fafa6befd738bb1abf) for a description of the problem.

Basically, it makes a lot more sense for `cider-eval-last-sexp` and `cider-eval-last-sexp-and-replace` to still work if the point is at the last bracket, since evil can't put the point on the line ending in normal mode by default. Can we change the binding to a new `evil-cider-eval-last-sexp` or something that takes this into account and goes just one character further than Cider does by default?

**Comment by nixmaniack** [comment]
I think the variable `evil-move-beyond-eol` was introduced for exactly this reason. Check [here](https://github.com/syl20bnr/spacemacs/issues/646#issuecomment-130141394).

**Comment by syl20bnr** [comment]
Yeah but I changed my mind with `evil-move-beyond-eol`, now I prefer to make clojure behaves like elisp, so we need to advise the eval functions (like evil do for emacs-lisp).

See https://github.com/syl20bnr/spacemacs/issues/3103

**Comment by sooheon** [comment]
```
(defadvice cider-last-sexp (around evil activate)
    "In normal-state or motion-state, last sexp ends at point."
    (if (or (evil-normal-state-p) (evil-motion-state-p))
        (save-excursion
          (unless (or (eobp) (eolp)) (forward-char))
          ad-do-it)
      ad-do-it))
```

This should do it.

**Comment by gilch** [comment]
I thought `defadvice` was deprecated now? Better use `add-advice` or the like for future proofing.

**Comment by TheBB** [comment]
Closing this in favor of https://github.com/syl20bnr/spacemacs/issues/3103
