### ISSUE TITLE
java layer unrecognised option when creating jvm

### ISSUE THREAD

**Issue by Chream** [syl20bnr/spacemacs#5579]
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description
Error when java is called in background in java-mode. Problem seems to be the `-command` option which is also not listed as a command when `java -help` is run.

#### Reproduction guide
- java layer enabled. Ensure that eclim is setup.
- Start Emacs
- Save a .java file

*Observed behaviour:*
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java -d64 -command project_by_resource -f /Users/izzy/Documents/university/uio/INF1010/oblig/oblig7/src/AMikstur.java -XX:MaxPermSize=128m -Xmx256m -XstartOnFirstThread -jar /opt/homebrew-cask/Caskroom/eclipse-java/4.5.2/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application
Unrecognized option: -command
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
````
*Expected behaviour:*
Not really sure what it is trying to do, but I guess to get either tag info or something else. Would be nice if someone could explain.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: chream (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking version-control semantic gtags ibuffer osx c-c   common-lisp java)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by NJBS** [comment]
What is the value of `eclim-executable`, SPC  h d v` `eclim-executable`?

**Comment by Chream** [comment]
The variable `eclim-executable` is set to
````
Its value is
"/opt/homebrew-cask/Caskroom/eclipse-java/4.5.2/Eclipse.app/Contents/Eclipse/eclimd"
```
it is symlinked to the plugins folder of Eclipse. Eclipse was installed through Homebrew though Cask.

Other settings i have in my user-config hook in .spacemacs for the java layer: 
```
;; java-layer
  (setq eclim-eclipse-dirs "/opt/homebrew-cask/Caskroom/eclipse-java/4.5.2/Eclipse.app/Contents/Eclipse"
        eclim-executable "/opt/homebrew-cask/Caskroom/eclipse-java/4.5.2/Eclipse.app/Contents/Eclipse/eclimd")
```

You mean it should run eclimd not java? To me the whole option `-command project_by_resource` seems  suspect. As if `project_by_resource` should be a variable that wasn't evaluated. But my knowledge of this layer (and the package `emacs-eclim`) is limited.

**Comment by NJBS** [comment]
"-command project_by_resource" is a literal command passed onto eclim, it doesn't need to be evaluated within Emacs. In your error it looks like the commands that were meant for eclim are being passed to java which is why I suspected your `eclim-executable` wasn't set properly. Can you try setting `eclim-executable` to `eclim` rather than `eclimd`?

**Comment by Chream** [comment]
Hi sorry for the late reply. This fixed the problem. Thank you!
