### ISSUE TITLE
Stop python script in spacemacs

### ISSUE THREAD

**Issue by boboRAY** [syl20bnr/spacemacs#5580]
Hi
I'm running python code in spacemacs ( using python layer and ipython)

I just run a script for a long time and want to interupt it, I hit cirl-c but no use here
So how can I stop my python script in ipython notebook inside spacemacs?

thanks

**Comment by StreakyCobra** [comment]
Have you tried pressing twice `C-c` (`C-c C-c`)?

If it doesn't work, can you update your issue by following [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)?

**Comment by boboRAY** [comment]
It works!
thx
maybe add this to document or somewhere will be good?

**Comment by jonas-hagen** [comment]
For everyone coming here with the same question: `SPC b d`  (`kill-this-buffer`) will ask if the process should be killed; answer with `y`.
