### ISSUE TITLE
Spacemacs throwing cryptic errors

### ISSUE THREAD

**Issue by danielbornt** [syl20bnr/spacemacs#5585]
Having an issue with Spacemacs. Getting weird messages that I do not even pretend to understand. Output of running emacs in debug mode is attached.I am running Emacs 24.5 on Ubuntu Mate 15.10.
[debug.txt](https://github.com/syl20bnr/spacemacs/files/189019/debug.txt)

**Comment by syl20bnr** [comment]
Can you show your dotfile ?

**Comment by danielbornt** [comment]
Sure thing, see attached


[init.el.txt](https://github.com/syl20bnr/spacemacs/files/189444/init.el.txt)

**Comment by danielbornt** [comment]
Also,attached is a screen shot of the screen when it first loads
![screenshot](https://cloud.githubusercontent.com/assets/8417449/14043914/2fa0927c-f260-11e5-98ad-d6d3c765b6aa.png)

**Comment by jupl** [comment]
I think what's being asked is your `.spacemacs` file.

**Comment by sholland1** [comment]
I just had a similar problem.
The problem started happening after trying to update packages.
I tried renaming the elpa directory, so spacemacs would reinstall all its packages. This solved the problem for me.
Try running `mv ~/.emacs.d/elpa ~/.emacs.d/elpa.bak`, then restart spacemacs.
