### ISSUE TITLE
(setq ranger-override-dired t) not working, dired opens from helm instead of deer

### ISSUE THREAD

**Issue by adrsta** [syl20bnr/spacemacs#5589]
#### Description
whenever in helm buffer  I press enter on a directory
spacemacs opens Dired buffer, while I am expecting Deer,
because I have ranger layer installed
and ranger-override-dired is non-nil

**Comment by TheBB** [comment]
Ranger is here: https://github.com/ralesi/ranger.el

However, are you setting the variable before ranger loads? This is one of those variables where you have to be careful you're setting it early enough.

**Comment by adrsta** [comment]
OK, it didn't work because I used the Emacs `customize` thing for it.
But when set this variable in dotspacemacs/user-init () it works as expected.
Thanks!
