### ISSUE TITLE
lazy installation of layers broken if packages of layer are local e.g. for python

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#5591]
#### Description
Spacemacs asks for layer installation even if the layer is already installed. Probably because some packages are not installed or local.

#### Reproduction guide
- Start Emacs
- `dotspacemacs-enable-lazy-installation` is set to `t`
- open e.g. `.py` file

*Observed behaviour:*
- I am asked if I want to install the python layer.
- If answered yes it also installs the `cscope` related packages even though I don't use the cscope layer and tries to do the following:
```
(Spacemacs) --> installing package: py-yapf@python... [2/5]
(Spacemacs) Warning: Cannot install package py-yapf.
(Spacemacs) --> installing package: pylookup@python... [3/5]
(Spacemacs) Warning: Cannot install package pylookup.
(Spacemacs) --> installing package: nose@python... [4/5]
(Spacemacs) Warning: Cannot install package nose.
(Spacemacs) --> installing dependency: helm-cscope... [5/5]
```

*Expected behaviour:*
Load the buffer with the python layer enabled without asking questions.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 35b314f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip nil)
 chrome clojure colors custom_org_config django
 (elfeed :variables rmh-elfeed-org-files
         (list "~/Dropbox/org/feeds.org"))
 emacs-lisp emoji erc eyebrowse finance games
 (git :variables git-gutter-use-fringe t)
 github gnus graphviz html ipython-notebook javascript latex lua markdown my-mu4e my_python org org-ipython org-page pandoc spacemacs-layouts pdf-tools php
 (python :variables python-enable-yapf-format-on-save nil python-auto-set-local-pyenv-version 'on-project-switch python-test-runner 'pytest)
 ranger research-config ruby rust search-engine semantic
 (shell :variables shell-default-shell 'term shell-default-term-shell "/bin/zsh")
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking tmux vagrant
 (version-control :variables version-control-diff-tool 'diff-hl)
 yaml)
```

**Comment by StreakyCobra** [comment]
CC @syl20bnr

**Comment by jmay** [comment]
This sounds like what I've been experiencing with ruby, just after pulling the latest develop `dd14afa`

With `dotspacemacs-enable-lazy-installation` turned on it would ask me if I want to install the ruby layer *every time* I opened a new file. Set to nil it seems OK.

**Comment by syl20bnr** [comment]
I see, thank you for the report, fixing it tonight.

**Comment by syl20bnr** [comment]
Should be fixed in last develop :-)

**Comment by cpaulik** [comment]
Works for me now. Thanks
