### ISSUE TITLE
rspec auto focus output window

### ISSUE THREAD

**Issue by adham90** [syl20bnr/spacemacs#5594]
How to enable auto focus on **rspec** popup window?

**Comment by nixmaniack** [comment]
If it's `*rspec-compilation*` buffer, then it's set by Spacemacs that way i.e. `:noselect t` by default.

If you want to change that behaviour, you can try following in `user-config` section of `~/.spacemacs`
```elisp
(setcdr (assoc "*rspec-compilation*" popwin:special-display-config) '(:dedicated t :position bottom :stick t :noselect nil :height 0.4))
```

**Comment by adham90** [comment]
thanks @nixmaniack :heart_eyes: :+1:

**Comment by adham90** [comment]
@nixmaniack how to do the same with rubocop?
i tried this line but it is not working :cold_sweat:
```lisp
(setcdr (assoc "*RuboCop*" popwin:special-display-config) '(:dedicated t :position bottom :stick t :noselect nil :height 0.4))
```

**Comment by nixmaniack** [comment]
`*RuboCop*` isn't configured by spacemacs hence you'll have add that to `popwin:special-display-config` instead.
```
(push '("*RuboCop*"  :dedicated t :position bottom :stick t :noselect nil :height 0.4) popwin:special-display-config)
```

**Comment by adham90** [comment]
@nixmaniack i need to do it with Regular Expression?
because the buffer name = "*RuboCop /folder_name/file_name.rb*"

**Comment by nixmaniack** [comment]
@adham90 Yes, use regexp in place of `*RuboCop*`
