### ISSUE TITLE
Unable to navigate down the screen from a buffer with an inline image in a small window

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#5599]
#### Description

On a buffer with an inline image if the height of the window is small enough I am unable to move the cursor downward with the down arrow or `j` Evil-wise.
#### Reproduction guide
- Start Emacs
- Ensure window has the home buffer open with a small height like so with a small frame or split windows.
  ![ssx](https://cloud.githubusercontent.com/assets/2065876/14057215/181aead2-f2c7-11e5-8037-69bdfc797286.png)
- Navigate downward with the down arrow or `j` Evil-wise.

_Observed behaviour:_
Cursor is stuck in the row with the image and cannot move down normally. Need to resort to using something like `G`.

_Expected behaviour:_
Continue to move downward.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. dd14afa)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(react csharp colors dockerfile emacs-lisp html github markdown osx react restclient swift syntax-checking vimscript yaml
       (auto-completion :variables auto-completion-enable-help-tooltip t)
       (git :variables git-magit-status-fullscreen t magit-push-always-verify nil)
       (javascript :variables js2-mode-show-parse-errors nil js2-mode-show-strict-warnings nil)
       (org :variables org-src-preserve-indentation t org-startup-folded 'showall)
       (shell :variables shell-default-term-shell "/bin/zsh")
       (version-control :variables version-control-diff-tool 'diff-hl))
```

**Comment by StreakyCobra** [comment]
Can you try to reproduce this in another buffer than `*Spacemacs*` having a image in it?

**Comment by jupl** [comment]
How would I go about having a buffer with text and an image?

**Comment by StreakyCobra** [comment]
`SPC h SPC ruby RET`

**Comment by jupl** [comment]
Happens there too.

**Comment by StreakyCobra** [comment]
The best would be to try reproducing this on a stock emacs, in order to know if it's a Spacemacs bug or an Emacs bug. Sadly I don't really know how to reproduce this on stock emacs. Can anybody give the needed steps?

**Comment by jupl** [comment]
I opened stock Emacs with the home screen and I can't reproduce the issue.

<img width="639" alt="ss" src="https://cloud.githubusercontent.com/assets/2065876/14082962/05c1885c-f4e1-11e5-9cba-db011461ce46.png">

**Comment by rgrinberg** [comment]
This is an issue for me on Linux with emacs from master. @jupl Could you confirm that this is still an issue with emacs 25?
