### ISSUE TITLE
Don't auto center on evil-jumper

### ISSUE THREAD

**Issue by danielwuz** [syl20bnr/spacemacs#560]
Currently `evil-jumper-auto-center` has been set to enabled by default. This causes screen to flash when using emacs in a terminal environment every time on evil-jump, which is kinda annoying and feels buggy. Not sure how much value `auto-center` brings, but I'd suggest to turn it off by default to give better usability of stock spacemacs.

**Comment by syl20bnr** [comment]
I'm OK with it.
