### ISSUE TITLE
Go language layer indents code with tab character

### ISSUE THREAD

**Issue by wilfreddenton** [syl20bnr/spacemacs#5600]
I have `(setq indent-tabs-mode nil)` in my `.spacemacs` but this layer still seems to insert tab characters when it indents my code. How can I change this to spaces?

Looks like this... 
<img width="398" alt="screen shot 2016-03-26 at 1 53 21 am" src="https://cloud.githubusercontent.com/assets/1426935/14058416/8d8c410c-f2f5-11e5-89cb-b81d149aade5.png">

**Comment by JAremko** [comment]
Golang devs insist on using tabs. [Link](https://golang.org/doc/effective_go.html#formatting)

**Comment by wilfreddenton** [comment]
Thanks for letting me know. Is there a reason? I thought spaces were
usually preferred. This is all I found in the article "We use tabs for
indentation and gofmt emits them by default. Use spaces only if you must."

**Comment by JAremko** [comment]
@wilfreddenton  Canonical formatting is one of the language features. It improves "shareability" of the code :smile:

**Comment by JAremko** [comment]
@wilfreddenton  #5635
