### ISSUE TITLE
how to company function name in lua mode?

### ISSUE THREAD

**Issue by yinchunlong** [syl20bnr/spacemacs#5602]
1. config auto-completion   and lua layers
2. when edit a lua file in lua mode, use command : gtags --gtagslabel=ctags to generate tag database
3.can't company a function name...

anyone can help me?

**Comment by TheBB** [comment]
There's no particular support for completion in lua. There is only what company ships with by default. No tags backend as far as I'm aware.

**Comment by TheBB** [comment]
Actually, company does come with a gtags backend, so try to make sure that `company-gtags` is the first element in `company-backends` in lua mode. You can try calling `company-gtags` manually (e.g. with `M-x`) to check if it's working.

**Comment by yinchunlong** [comment]
@TheBB it's not work....

**Comment by TheBB** [comment]
Did you try calling `company-gtags` manually?

**Comment by TheBB** [comment]
If `company-gtags` doesn't work by itself then you should report upstream to company: https://github.com/company-mode/company-mode

**Comment by yinchunlong** [comment]
yes, i call company-gtags manually.
ok, i will report upstream to company: https://github.com/company-mode/company-mode.
thank you!!
