### ISSUE TITLE
Issue in go mode. Mark is getting set in normal mode for no apparent reason

### ISSUE THREAD

**Issue by jrmiller82** [syl20bnr/spacemacs#5604]
#### Description

I'm finding that 'mark' is getting set in go mode and that ESC is not cancelling (sorry for speaking in Vim terms) insert mode to go back to normal mode. Instead, ESC is bringing up a helm menu. 

If I C-[ or 'jk' out of insert mode, and then into normal mode, somehow mark is getting set, and when I start to move using any keyboard navigation, such as 'j' or 'k' to move up or down a line, it's like I'm highlighting things as if I had hit Shift-V or C-v. 

I never noticed it before. My guess is that something's going on with gocode or the syntax checker that is doing something wrong, because it seems to happen especially bad when the cursor was resting on a function or variable definition. 
#### Reproduction guide
- Start Emacs
- see my description, it's not something I can always reproduce. I'm sorry that I can't give you a clear reproduction step.

_Observed behaviour:_
See description.

_Expected behaviour:_
Esc exits to normal mode with one press. 

AND

Mark not set when in normal mode unless explicitly asked for. 
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp git markdown org go c-c   markdown latex python syntax-checking themes-megapack version-control)
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by jrmiller82** [comment]
Bueller? Anyone? Bueller? :)

**Comment by StreakyCobra** [comment]
CC @bogdanteleaga

**Comment by bogdanteleaga** [comment]
I can confirm the mark getting set in an apparently "random" fashion, but it also seems to happen in python mode (haven't tried other modes too). What I'm doing is just moving around and inserting text then going to normal mode and undoing and that's pretty much it.

I cannot reproduce the `ESC`(or `C-[`) not going back to normal mode straight away.

**Comment by StreakyCobra** [comment]
There are 3 different issues there if I understand correctly:

1. Exiting insert state set the mark.
2. After exiting the insert state, moving up and down highlight text like when selecting.
3. ESC is not exiting the insert state.

I can't reproduce 2 and 3 in python mode (not tested with go). Concerning 1, Isn't this made in purpose to allow navigating to old modification place with `C-i`?
