### ISSUE TITLE
 Triple items for some menus in Dired buffers

### ISSUE THREAD

**Issue by hemcsec** [syl20bnr/spacemacs#5607]
#### Description

 Triple items for some menus in Dired buffers
#### Reproduction guide
- Start Emacs
- SPC a d

_Observed behaviour:_
There are triple items for menus Operate, Mark, Regexp and Immediate
<img width="740" alt="screen shot 2016-03-27 at 10 16 20" src="https://cloud.githubusercontent.com/assets/9861126/14063472/60aed5ee-f405-11e5-9895-6d32e6a2d789.png">
 as shown in attached screenshot.

_Expected behaviour:_
There should be no triple items.
#### System Info
- OS: darwin
- Emacs: 25.0.92.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. a9c9e9a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 better-defaults chinese
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 django emacs-lisp gtags git html javascript osx
 (latex :variables latex-build-command "LatexMk")
 python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spacemacs-helm semantic
 (spell-checking :variables spell-checking-enable-by-default nil)
 (syntax-checking :variables syntax-checking-enable-by-default nil))
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by StreakyCobra** [comment]
Can you try reproducing this on a stock emacs (without Spacemacs) to see if it come from Spacemacs or not?

**Comment by HEMCSEC** [comment]
cd ~
mv .spacemacs .spacemacs.old
mv .emacs.d .emacs.d.old
run emacs
Alt+x dired
<img width="765" alt="screen shot 2016-03-28 at 09 01 37" src="https://cloud.githubusercontent.com/assets/9861126/14068930/eef722ca-f4c3-11e5-975f-4754ca2b13d5.png">
It seems OK.

**Comment by StreakyCobra** [comment]
Ok, indeed it's coming from Spacemacs somehow. Let's see if someone has the time to dig into this.

**Comment by HEMCSEC** [comment]
When enable **vinegar** layer as (vinegar :variables vinegar-reuse-dired-buffer t), the problem has gone.

**Comment by StreakyCobra** [comment]
I haven't use `vinegar`, but if it is the same as for `ranger`, it's replacing `dired` so I'm not surprised it doesn't appear there.

**Comment by HEMCSEC** [comment]
According to this url https://bitbucket.org/lyro/evil/issues/404/dired-menus-are-duplicated, the problem may come from evil-mode.

**Comment by StreakyCobra** [comment]
It seems so :-/
