### ISSUE TITLE
Line Number layout too close when using spacemacs in iTerm(and OSX terminal)

### ISSUE THREAD

**Issue by boboRAY** [syl20bnr/spacemacs#5609]
When using Gui Emacs 
There is a space between line number and code region
![image](https://cloud.githubusercontent.com/assets/6420577/14064873/c41077e2-f445-11e5-869b-93ad84463d83.png)

But using spacemacs in iTerm2 (Terminal the same), they become too close 
![image](https://cloud.githubusercontent.com/assets/6420577/14064869/9e30752c-f445-11e5-94d1-cbecb073b32b.png)

**Comment by jupl** [comment]
This is probably because fringes are not available in the terminal.

**Comment by MephistoMMM** [comment]
it does not work while dotspacemacs-line-numbers set to relative

**Comment by brezal** [comment]
I still have this issue. @MephistoMMM Did I miscomprehend how to use the workaround?

<img width="592" alt="screen shot 2017-12-16 at 7 33 17 pm" src="https://user-images.githubusercontent.com/2381998/34075548-1035c400-e298-11e7-9158-971839bb84e3.png">

**Comment by MephistoMMM** [comment]
@brezal 

Well, I mean, add the snippets into `dotspacemacs/user-config` function, as follows:

```elisp
(defun dotspacemacs/user-config ()

    (unless (display-graphic-p)
           (setq linum-relative-format "%3s "))

    ;; Alternatively
    (unless (display-graphic-p)
          (setq linum-relative-format (concat linum-relative-format " ")))

)
```

**Comment by marcw** [comment]
This issue is still valid on the latest version of emacs and spacemacs on iTerm2. [This solution](https://github.com/syl20bnr/spacemacs/issues/5609#issuecomment-202406149) works but I'm confused as I thought `display-line-numbers` was the default and not linum.

**Comment by duianto** [comment]
`display-line-numbers` are the default line numbers when Emacs 26+ is used on the Spacemacs `develop` branch.

**Comment by lebensterben** [comment]
Closing due to its age.

For future references a work around is available for users of `linum` here: https://github.com/syl20bnr/spacemacs/issues/5609#issuecomment-202406149

But Spacemacs now requires >Emacs 27 and `display-line-numbers` is the default so it's not relevant anymore.
