### ISSUE TITLE
qwerty normal mode

### ISSUE THREAD

**Issue by devinrhode2** [syl20bnr/spacemacs#561]
I'm not sure if spacemacs has a qwerty normal/command mode, but this would be really awesome. The idea is to be able to use Dvorak/Colemak/Minimak instead of qwerty when writing code or english, but preserve the vim key-bindings we already know. Opinions aside, I'm just advocating for having a documented way to do this with spacemacs. (I'm also personally curious if you have any ideas or know how)

**Comment by syl20bnr** [comment]
If I correctly understood you want the same layout than qwerty in normal state ?

**Comment by devinrhode2** [comment]
Correct.

Lots of people use Dvorak without mapping vim commands back to their
original qwerty keys. I would love to keep using the standard qwerty vim
bindings in normal state, but set my OS to use the Programmers Dvorak
layout for insert mode and searching


-Devin <http://zerply.com/DevinRhode2>
<http://zerply.com/devinrhode2>

**Comment by syl20bnr** [comment]
I see, I think there are some dvorak mappings for evil on github. Maybe we could try to add one to Spacemacs behind a `dotspacemacs-keyboard-layout` variable.

**Comment by Gonzih** [comment]
It's not really hard to adjust evil to play well with dvorak. I do it partially. With spacemacs problem is that you will need to do a lot of yak shaving to adjust mappings also in all plugins and etc. At least movement keys for example.

**Comment by hijarian** [comment]
If you call `set-input-method` and choose `english-dvorak` you'll get Dvorak in insert mode **and** all keybinginds will work.

Tried just now in Spacemacs `develop`:

1. opened scratch buffer
2. `M-x set-input-method`
3. `english-dvorak`, Enter
4. `i`, `asdf` -- get `aoeu` printed.
5. `M-x` is still "call command" dialog
6. `SPC f f` still opens "Find File" interface.

**Comment by hijarian** [comment]
@syl20bnr We probably need a section in docs explaining the value of Emacs input methods regarding keybindings, it's the second time I see ticket like this, another one was [#1510](https://github.com/syl20bnr/spacemacs/issues/1510#issuecomment-103127209)

**Comment by Nupf** [comment]
@hijarian wouldn't this also change the keybindings when searching?

**Comment by hijarian** [comment]
@Nupf Man, why asking, just try it. :) 

Anyway, to my amazement, it seems that input methods work **only** in input mode. I-search, search by vim `/`, `f` key all receive standard qwerty input even if `set-input-mode` was performed and I was inputting the Dvorak keys a second ago.

I have found a discussion probably related to this in `evil` issue tracker: https://bitbucket.org/lyro/evil/issue/5/input-methods 

This starts to look a serious UI issue and at the same time place of improvement, because as I said, Emacs input methods allow you to continue using the same hotkeys while inputting text in arbitrary input mode.

**Comment by hijarian** [comment]
@syl20bnr I dare ask, how high the adding non-US-land-support to Spacemacs is in your schedule? In my case I personally easily may be in position when I need to write LaTeX document in Russian with pieces of Lisp, Japanese and some Sanskrit written in Devanagari script. 

And I'm unsure that I can afford several hours a day for some weeks to implement this feature in Spacemacs. :( I will, however.

**Comment by syl20bnr** [comment]
I don't use input-method so I'm not the right person to do this kind of support.
@andyque what's your experience with chinese input on Spacemacs ? How the chinese layer deals with that ?

**Comment by syl20bnr** [comment]
Maybe chinese is not a good example since the layout may not change, but there is still the management of the input.

**Comment by brabalan** [comment]
I would also be very much interested in such a feature. I use a bépo layout, and I tweaked evil bindings quite a bit to bring them back to the home row.

**Comment by StreakyCobra** [comment]
@brabalan There is now a [`bepo` layer](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bkeyboard-layouts/bepo) in the `develop` branch. The mapping is based on the proposed vim configuration on the bepo's website. Currently it only remaps the keybindings that I'm using, in the packages that I'm using. Feel free to open issues if you need more bindings. You can also come to the [gitter chat](https://gitter.im/syl20bnr/spacemacs) to shares yours :-)

**Comment by Gonzih** [comment]
Very interesting how people solve this problem :) This is what I do normally (same in my vim configuration): https://github.com/Gonzih/dotfiles/blob/master/.spacemacs#L174-L386. I'm just trying to keep number of remapped keys to the minimum and use as much as possible keybinding provided by editor. Works fine so far (by so far i mean for the last 4 years).

**Comment by brabalan** [comment]
This is great news, @StreakyCobra. Using it directly would probably change some of my habits (I use the tsrd inverted triangle instead of the more traditional ctsr), but it's a smaller change than going hjkl. I don't know how the development process goes: is this going to end up in master, or will it stay on the develop branch?

**Comment by StreakyCobra** [comment]
@brabalan It is in develop yet, and will end up in master for the next release (0.105). Hope you'll enjoy it, and don't hesitate to report issues/ideas.

**Comment by brabalan** [comment]
@StreakyCobra Here is a first issue, #3392 . I'm failing at activating it.

**Comment by syl20bnr** [comment]
there is now a keyboard-layout layer which supports dvorak layout.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
