### ISSUE TITLE
scala layer scalastyle documentation has several problems

### ISSUE THREAD

**Issue by caoilte** [syl20bnr/spacemacs#5611]
This section of the scala layer documentation
https://github.com/syl20bnr/spacemacs/tree/2c3e6b4fb3ac497b08356aacc61525f2c942e77f/layers/%2Blang/scala#scalastyle

has several problems

## `flycheck-scalastyle-jar` isn't valid any more

> The scala-stylestyle syntax checker now expects a scalastyle executable in exec-path now. The flycheck-scalastyle-jar option which used to provide the location of the Scalastyle JAR file was removed. This change makes scalastyle as easy to setup as any other syntax checker in Flycheck—on OS X it’s just a brew install scalastyle away.

from http://www.flycheck.org/2015/11/14/flycheck-0.25.html

## Documentation linked to doesn't exist

This might be a better link
http://www.flycheck.org/manual/latest/Supported-languages.html#Scala

## could say that only scalastyle is enabled for Ensime

https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/scala/packages.el#L169

**Comment by caoilte** [comment]
I would submit a PR but can't figure out why flycheck doesn't start automatically after scala mode hook fires. Perhaps @chrisbarrett can offer advice. 

I was able to get flycheck starting automatically when I did the following,

`(add-hook 'scala-mode-hook 'flycheck-mode)`

but not via

`
(defun scala/post-init-flycheck ()
  (spacemacs/add-flycheck-hook 'scala-mode-hook)
  )
`

which i figured ought to work.

**Comment by hujianxin** [comment]
@caoilte And I find that, `smartparens`  and `yasnippet` have conflicts in spacemacs. The smartparens will be disabled automatically when using yasnippet.

Finally, there's a great emacs configuration file which enhance scala programming. [lunaryorn's emacs](https://github.com/lunaryorn/.emacs.d). In this configuration, lunaryorn write two small packages `flycheck-auto-scalastyle.el` and `flycheck-ensime.el` which are wonderful for scala.

Maybe there's some help for your PR.

**Comment by i-am-the-slime** [comment]
It now says download the `scalastyle.jar` and put it somewhere sensible. What's that somewhere sensible?

**Comment by dayyan** [comment]
I was able to get syntax checking working by using the [syntax-checking layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/syntax-checking) and configuring like so:
```elisp
(syntax-checking :variables
                 flycheck-scalastylerc (expand-file-name "~/scalastyle_config.xml"))
```

You may need to toggle spacemacs syntax checking.

**Comment by d1egoaz** [comment]
@caoilte most of these problems are already fixed in develop branch, it might be a good idea to use spacemacs/develop branch.

I added this PR https://github.com/syl20bnr/spacemacs/pull/7245 to use @dayyan suggested configuration

**Comment by d1egoaz** [comment]
This is the develop scala layer doc https://github.com/d1egoaz/spacemacs/tree/develop/layers/%2Blang/scala

**Comment by TheBB** [comment]
Should be fixed in master.
