### ISSUE TITLE
Clojure layer nREPL cannot jack in (dependency versions)

### ISSUE THREAD

**Issue by porglezomp** [syl20bnr/spacemacs#5612]
I tried to start using ClojureScipt yesterday, and got stuck when I tried to launch the REPL from inside Spacemacs. I've tracked down the issue to stem from an incompatible version of Leiningen. It's very difficult to deduce this from the error that Spacemacs produces, and it's very likely to happen if you follow the installation instructions.

The installation instructions should explicitly mention the Leiningen version required instead of just recommending that the user install it from the OS package manager, because Ubuntu 14.X doesn't seem to package a recent enough version for it to work.

**Comment by porglezomp** [comment]
I'd like to take this fix as my first contribution.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
