### ISSUE TITLE
Function "ruby-toggle-string-quotes" not found

### ISSUE THREAD

**Issue by nedludd** [syl20bnr/spacemacs#5614]
#### Description

The ruby layer defines a key mapping for `ruby-toggle-string-quotes` but no such function exists.

If fact I can't find such a function existing _anywhere_.
#### Reproduction guide

Open a ruby file and press the expected key sequence `SPC m '`.

_Observed behaviour:_
Error message: `Symbol's function definition is void: ruby-toggle-string-quotes`

_Expected behaviour:_
Toggling of the string quotes, I guess?
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. 3aff734)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(ansible
 (auto-completion :variables auto-completion-use-tab-instead-of-enter t auto-completion-enable-company-help-tooltip t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 applescript backup better-defaults colors confluence csv
 (dash :variables dash-helm-dash-docset-path "~/Library/Application Support/Dash/DocSets")
 emacs-lisp erc evernote
 (geolocation :variables geolocation-enable-osx-location-service-support t geolocation-enable-weather-forecast t geolocation-enable-automatic-theme-changer t)
 git html ibuffer javascript lua mail markdown mediawiki org osx persist puppet ranger
 (ruby :variables ruby-version-manager 'rvm)
 ruby-on-rails
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 syntax-checking tiny-tools vimrc)
```

**Comment by StreakyCobra** [comment]
I was sure to have seen something about this somewhere. It took me time to find the information back, but here it is: https://github.com/syl20bnr/spacemacs/commit/e29ac213452ad9d60f2758965e37c2f7e36d7dbd#commitcomment-15896798

**Comment by Miciah** [comment]
`ruby-toggle-string-quotes` was added in Emacs 25.  Can we label this issue "Emacs 24.5"?
