### ISSUE TITLE
Setting `git-gutter-fr:side` has no effect

### ISSUE THREAD

**Issue by xtian** [syl20bnr/spacemacs#5615]
#### Description
I’m very new to Emacs so please let me know if I’m configuring this incorrectly, but I think the way that `git-gutter-fr:side` is set in spacemacs is preventing it from being overridden by users.

I have the following in my .spacemacs:
```lisp
(defun dotspacemacs/user-config ()
  (setq git-gutter-fr:side 'left-fringe)
)
```

However, the Git gutter still appears on the right fringe.

#### Reproduction guide
- Start Emacs
- Set `git-gutter-fr:side` to `left-fringe` in user-config

*Observed behaviour:*
Git gutter is on right fringe

*Expected behaviour:*
Git gutter should be on left fringe

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults elixir emacs-lisp
                 (git :variables git-gutter-use-fringe t)
                 github javascript markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 osx rust syntax-checking version-control)
```

**Comment by jupl** [comment]
Try also setting `git-gutter-fr+-side` to `'left-fringe` as well.

**Comment by xtian** [comment]
@jupl That worked—thanks! I didn't realize that there were multiple git-gutter packages and that git-gutter+ was the default.
