### ISSUE TITLE
"Don't know where `spacemacs/foo' is defined"

### ISSUE THREAD

**Issue by edrex** [syl20bnr/spacemacs#5621]
elisp doesn't know where the spacemacs/* functions are defined. I guess something about the load process is confusing introspection?

You can repro in various ways:

 * `SPC ? *, select `spacemacs/enter-ahs-forward`, `F3
 * type `(spacemacs/enter-ahs-forward)` in `.spacemacs`, place cursor over symbol, type `g d`

**Comment by edrex** [comment]
this applies to the functions defined in https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs/packages.el

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/3430

**Comment by TheBB** [comment]
This should gradually fix itself as we move functions out of `packages.el` and into `funcs.el`, which was the plan the last time I heard.
