### ISSUE TITLE
M-x is slow due to persp-mode

### ISSUE THREAD

**Issue by Peeja** [syl20bnr/spacemacs#5622]
#### Description
`helm-M-x` (and several other `helm` commands) are very slow to start. `persp-mode` is involved, and perhaps to blame.

#### Reproduction guide
- Start Emacs
- Press `M-x`

*Observed behaviour:*
`helm-M-x` takes up to several seconds to appear.

*Expected behaviour:*
Helm window should appear almost instantly.

#### System Info
- OS: darwin
- Emacs: 24.4.1
- Spacemacs: 0.105.14
- Spacemacs branch: nil (rev. a298a5a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(clojure html ruby go javascript yaml markdown php auto-completion extra-langs themes-megapack eyebrowse git version-control)
```

#### Profile

CPU and Memory profiles using `profiler.el`: https://gist.github.com/Peeja/7e24c3f7cc761faea08b

The culprit appears to be that `kill-buffer` calls `#<lambda 0x31d9bc63de987c>`, which calls `apply`, which calls the same `lambda` again, and the stack gets quite deep. I have a theory that it scales with the number of open buffers. Note that killing buffers normally, outside of Helm's operation, does not appear to be slow.

It doesn't show up in the report output, but if I ask the profiler to describe the lambda, it tells me it looks like:

```elisp
(lambda (&rest --cl-rest--) (apply (quote #[(G76499 G76500 b) "J	!\205
J !\207" [G76500 b G76499] 2]) (quote --newpred--) (quote --oldpred--)
--cl-rest--))
```

This leads me to believe it comes from `persp-mode.el`:

```elisp
(defun persp-make-frame-buffer-predicate (frame)
  (lexical-let ((oldpred (frame-parameter frame 'buffer-predicate)))
    (if persp-set-frame-buffer-predicate
        (lexical-let ((newpred
                       #'(lambda (b)
                           (if persp-mode
                               (memq b (safe-persp-buffers (get-frame-persp)))
                             b))))
          (if oldpred
              #'(lambda (b) (and (funcall oldpred b) (funcall newpred b)))
            newpred))
      oldpred)))
```

Sure enough, turning off `persp-mode` makes `M-x` almost instantaneous. But I don't know enough about `persp-mode` and what it's doing to determine who the bad actor is.

**Comment by aaronjensen** [comment]
Reported upstream: https://github.com/Bad-ptr/persp-mode.el/issues/35

**Comment by aaronjensen** [comment]
Fixed upstream, this can be closed: https://github.com/Bad-ptr/persp-mode.el/commit/6449c8511da1de2ddd1cb05bb4e1e7314c136535

**Comment by StreakyCobra** [comment]
Closing this. Let me know if this is not the case, I can reopen.
