### ISSUE TITLE
Spacemacs freezes when accessing a remote REPL in the ESS layer

### ISSUE THREAD

**Issue by Pizza-Boy** [syl20bnr/spacemacs#5623]
#### Description
Spacemacs freezes and becomes unresponsive when trying to SSH to a remote REPL through the ESS layer

#### Reproduction guide
- Start Emacs
- Open a .R file
- Start a REPL with `SPC m-s-i`
- Enter a remote location with `/ssh:host:/folder/address`

*Observed behaviour:*
Spacemacs becomes unresponsive and displays the error message: "error in process sentinel: Text is read only"

*Expected behaviour:*
A REPL is opened in the location specified (as it normally would be if it was a local folder).

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.11
- Spacemacs branch: master (rev. 93e55bb)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp osx git markdown org themes-megapack ess shell)
```

**Comment by StreakyCobra** [comment]
Can you try to verify it's a Spacemacs bug by reproducing this on a stock emacs? `SPC q D` may help to only load the involved packages.

**Comment by Pizza-Boy** [comment]
Sure. What'd be the easiest way to replicate this on stock emacs (without uninstalling spacemacs)?

**Comment by StreakyCobra** [comment]
`SPC q D` :stuck_out_tongue: 

Probably something like:

- `SPC q D`
- Enter `ess` then `RET` (return)
- This restart in a stock emacs with just ESS loaded
- `M-x R RET` to start a R REPL
- And see if your `/ssh:host:/folder/address` problems appear also here.

**Comment by Pizza-Boy** [comment]
Looks like I get the same freezing behavior, although I don't see the "error in process sentinel: Text is read only" message.

**Comment by StreakyCobra** [comment]
Ok, I don't know about the error message, but for the freezing you'll be better to ask upstream I think.

**Comment by Pizza-Boy** [comment]
Alright, reported a bug upstream.

**Comment by nixmaniack** [comment]
@Pizza-Boy would be good to have upstream bug link for tracking and future reference.

**Comment by Pizza-Boy** [comment]
I was having some trouble finding the link on the bug tracker but if I manage to locate it I'll make sure to add it here.
