### ISSUE TITLE
vim-surround puts delimiters on separate lines

### ISSUE THREAD

**Issue by exitface** [syl20bnr/spacemacs#563]
`hello`
Typing `yss"`
Results in:
```
"
hello
"
```
Expected behavior result would be
``` "hello" ```

**Comment by syl20bnr** [comment]
I cannot reproduce it, I even cannot make `yss` work at all.

To do this I do: `SPC v s "` with point anywhere in `hello`

**Comment by exitface** [comment]
Interesing - `ves"` from `h` works correctly for me.

Interesting to note that

```
hello
world
```

`yss"` on `hello` produces the former output, whereas `yss"` on world

results in
```
"
world"
```

This happens on master and development branches for me. Is there anything I can do to be more helpful? Video?

**Comment by syl20bnr** [comment]
I'm not a power user of surround. `yss"` is not even working for me, can you explain to me what you want to achieve with `yss"` ?

**Comment by exitface** [comment]
Sorry, `yss` should result in surrounding the current line with the delimiter ignoring leading whitespace ( https://github.com/tpope/vim-surround/blob/master/doc/surround.txt#L60 )

**Comment by syl20bnr** [comment]
Thank you. This is handy indeed, seems to be a bug in emacs surround implementation: https://github.com/timcharper/evil-surround/issues/39

**Comment by syl20bnr** [comment]
@exitface somehow I can do it now... I have not the same behavior than you:
(point anywhere on the line)
```
    hello
"    hello"
```

**Comment by syl20bnr** [comment]
The above example is in `emacs lisp` major mode

**Comment by exitface** [comment]
I think the keymaps might be swapped or something?

[Spacemacs]

ysS" -> `"hello"`

ySs ->
```
"
hello
"
```

yss" -> 
```
"
hello"
```

[Vim]

ysS"  [does nothing]

ySs" ->
```
"
hello
"
```

yss" -> `"hello"`

[Evil-Vim+Evil-Surround]

ysS"  [does nothing]

ySs" -> [Deletes h]

yss" -> `"hello"`

**Comment by syl20bnr** [comment]
I do have `yss"` ->  `"hello"`

In which major mode are you doing this ?

**Comment by syl20bnr** [comment]
oh I have to mentioned that I use this settings:

```elisp
  ;; I prefer to stay on the original character when leaving insert mode
  ;; (initiated with 'i').
  (setq evil-move-cursor-back nil)
```

**Comment by syl20bnr** [comment]
The previous settings does not change anything.

But wow, I restard spacemacs and now I have the same behavior than you.....

It was not working then `yss"` worked as expected and now I have your behavior!

**Comment by syl20bnr** [comment]
The swap things is strange but spacemacs swap `s` and `S` in `visual state`:

```elisp
(evil-define-key 'visual evil-surround-mode-map "s" 'evil-substitute)
(evil-define-key 'visual evil-surround-mode-map "S" 'evil-surround-region)
```

Maybe it has side effects on `y` behavior.

Source: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#the-vim-surround-case

**Comment by syl20bnr** [comment]
I tested and it is still swapped. I really don't know why :-(

**Comment by syl20bnr** [comment]
OK so I'm not mad !

Before updating my packages it is not swapped and works as expected `yss"` -> `"hello"` but after updating them is is swapped.

**Comment by syl20bnr** [comment]
So I narrowed the issue down to the update of `evil` itself.

evil version `20150105.2348` works.
evil version `20150206.334` swapped.

**Comment by exitface** [comment]
Pardon my ignorance, but how do I lock spacemacs to a particular version (a quick search shows it seems to be difficult to revert to older package versions)? Alternatively, do you know which commit that is in the evil repo?
