### ISSUE TITLE
Mode-icons addition

### ISSUE THREAD

**Issue by ReneFroger** [syl20bnr/spacemacs#5632]
Check the repo [mode-icons](https://github.com/ryuslash/mode-icons) for Emacs.

I think it's benefical for Spacemacs. It makes more distinct what the major mode is. What do you think?

**Comment by syl20bnr** [comment]
Seems a nice addition if it looks nice with resizing etc... otherwise it may be considered a user setting and be used with `dotspacemacs-additional-packages`.

**Comment by ReneFroger** [comment]
I just tried it, and it scales well. Or perhaps do you mean else with it?

And I'm wondering why you would consider it as an user setting? It seems to me it's a nice feature. Why not consider Magit as an user setting? Or Helm? Or Spacemacs, because Spacemacs is all about custom user settings after all.

**Comment by syl20bnr** [comment]
Because we don't create layers just to wrap a package, there is the `dotspacemacs-additional-packages` for this.
If it looks nice (no weird and obvious graphical artefacts) we can add it to the spacemacs distribution, I'll try it to see if it fits there.

**Comment by ragloo** [comment]
it's very nice and sexy but mode-icons sadly breaks helm alignement for me

**Comment by StreakyCobra** [comment]
@ragloo Screenshot and reproduction steps would help :-)

**Comment by syl20bnr** [comment]
We can disable it in helm buffers I guess.

**Comment by ReneFroger** [comment]
How would you disable it for Helm then? I tried it but I couldn't figure it out.

**Comment by CodeFalling** [comment]
@ragloo @ReneFroger `(setq mode-icons-change-mode-name nil)` would disable it in `helm` or `ido` etc

BTW, I add a icon for `spacemacs-buffer-mode` 😂 : https://github.com/ryuslash/mode-icons/pull/27

![screen shot 2016-04-27 at 11 27 33 am](https://cloud.githubusercontent.com/assets/5436704/14840879/1237aef8-0c6b-11e6-921e-2d477aaf98c5.png)

**Comment by ReneFroger** [comment]
@CodeFalling but.... `(setq mode-icons-change-mode-name nil)` will also disable it in mode line, not only in Helm/Ido buffers. There will not be a icon displayed for the major mode. What will be the point of using mode icons after all then? 

I was wondering if I could disable it for Helm/Ido buffers, not for also disabling for mode line.

**Comment by CodeFalling** [comment]
@ReneFroger 
> `(setq mode-icons-change-mode-name nil)` will also disable it in mode line

Really? Everything works well in my spacemacs. 

![screen shot 2016-04-28 at 10 04 25 am](https://cloud.githubusercontent.com/assets/5436704/14873402/a0367bd6-0d28-11e6-8287-2b5f63aa1cc1.png)

**Comment by ReneFroger** [comment]
Could you provide the same working configuration with `emacs -Q`?

I don't use Spacemacs, so it seems another parts of code is conflicting with yours, which will 'cause' your code to working.

**Comment by ReneFroger** [comment]
`(setq mode-icons-change-mode-name nil)` will also disable it in mode line

Any update on this?

**Comment by CodeFalling** [comment]
@ReneFroger Sorry for late reply

With `emacs -Q`

```lisp
(package-initialize)
(require 'mode-icons)
(require 'helm)
(setq mode-icons-change-mode-name nil)
(mode-icons-mode)
```

Everything works well 
![screen shot 2016-05-11 at 8 33 33 am](https://cloud.githubusercontent.com/assets/5436704/15166612/18c6c860-1753-11e6-9c7c-31a8e24853d0.png)

**Comment by CestDiego** [comment]
bump. Is there some progress on whether we would like this? there is also now this https://github.com/domtronn/all-the-icons.el :)

**Comment by d12frosted** [comment]
Wow, @CestDiego 

That package looks super nice.

**Comment by atextor** [comment]
@ReneFroger I made mode-icons work in the mode-line but not the helm buffers by adding
`(remove-hook 'helm-mode-hook 'mode-icons-mode)`
`(remove-hook 'helm-minibuffer-set-up-hook 'mode-icons-mode)` 
to my dotspacemacs/user-config.

**Comment by chriskaukis** [comment]
This looks lovely! Has this been added to dev or master yet? I'm slightly on the new side to Emacs et al and can't seem to find this package in Spacemacs layers list.

**Comment by StreakyCobra** [comment]
@chriskaukis In your `.spacemacs` file, add `mode-icons` to the `dotspacemacs-additional-packages` list, then this somewhere in `dotspacemacs/user-config`:

```elisp
  ;; mode-icons
  (spacemacs|do-after-display-system-init
   (mode-icons-mode))
```

**Comment by mustaqimM** [comment]
@StreakyCobra Is there a way to do it with [all-the-icons](https://github.com/domtronn/all-the-icons.el)?

**Comment by bricewge** [comment]
The author of `all-the-icons` is working on a theme for `spacelin` with this icon set: [domtronn/spaceline-all-the-icons.el](https://github.com/domtronn/spaceline-all-the-icons.el).
