### ISSUE TITLE
The window frame cannot be maximized 100% to suit the whole screen

### ISSUE THREAD

**Issue by mqreric** [syl20bnr/spacemacs#5633]
I installed emacs with Homebrew in OSX 10.11, but the window frame cannot be maximized 100% to suit the desktop screen after pressing [Shift + Option + Click the green button] which is to maximize window, where there is always a space left on the top or bottom like this

<img width="686" alt="screen shot 2016-03-30 at 22 51 43" src="https://cloud.githubusercontent.com/assets/7113010/14146417/11d2208a-f6ca-11e5-9ba6-7d1ace189beb.png">

used the formulae to install:
`brew install emacs -with--cocoa --srgb --with-gnutls --with-imagemagick`

**Comment by jupl** [comment]
Have you tried `SPC T M`?

**Comment by mqreric** [comment]
@jupl Yes, I have configured automatically maximizing window at init. But it still leaves one single gap between the menu bar and the title bar of emacs, or on the bottom. 

It really makes me uncomfortable........

**Comment by jupl** [comment]
I just tried it in stock Emacs and the same thing occurs. If that's the case it may be out of the scope of Spacemacs.

**Comment by mqreric** [comment]
fullscreen is what I am using. If this is the problem of OSX, seemingly have to do so..

Thanks @jupl

**Comment by jupl** [comment]
Regarding the gaps at the bottom, I think it has to do with how Emacs does resizing. If you try to resize the native window (not an Emacs window) you see it resizes in "chunks" and not per pixel. That's why when you maximize the window it resizes up to that point.

**Comment by syl20bnr** [comment]
Not sure at all it can help but did you try setting `dotspacemacs-fullscreen-use-non-native` to `t` ?

**Comment by mqreric** [comment]
@syl20bnr have tried this, but not working. My app is ok working in fullscreen mode.

After toggle `SPC T M`, it just look like this

<img width="686" alt="screen shot 2016-03-30 at 22 51 43" src="https://cloud.githubusercontent.com/assets/7113010/14146417/11d2208a-f6ca-11e5-9ba6-7d1ace189beb.png">

and I cannot drag the border of the window to resize it to attach to the apple menu bar

Maybe it is due to that I use the wrong formulae to install? I also have tried the recommended emacs-mac-port, it is perfect other than it is very laggy

**Comment by jupl** [comment]
Can this be reproduced with stock Emacs?

**Comment by mqreric** [comment]
I just like a maximize-able frame, not full screen, to fill up the mac screen vertically without any gap left between the dock and the apple menu bar..... but it can't...

**Comment by d12frosted** [comment]
Strange. I also use maximise instead of fullscreen and it works fine without any issues.

```
dotspacemacs-fullscreen-use-non-native nil
dotspacemacs-maximized-at-startup t
```

But it could be related to font size. I've noticed that with some font sizes I have to click that green button with option held several times in order to achieve desired effect.

**Comment by mqreric** [comment]
@d12frosted Thanks, let me try some other fonts instead of `Source Code Pro`

**Comment by mqreric** [comment]
@d12frosted Problem solved! I use Menlo size 13 to replace Source Code Pro 13 on my 13'3 Retina mac, the ugly gap is got rid of.

**Comment by d12frosted** [comment]
Glad to hear that Menlo works. For me Source Code Pro 10 works as well. 

BTW, what about hitting green button several times? Does it makes any difference?

**Comment by sooheon** [comment]
`(setq frame-resize-pixelwise t)` solves the issue.

From the docstring:
```
Non-nil means resize frames pixelwise.
If this option is nil, resizing a frame rounds its sizes to the frame's
current values of `frame-char-height' and `frame-char-width'.  If this
is non-nil, no rounding occurs, hence frame sizes can increase/decrease
by one pixel.

With some window managers you have to set this to non-nil in order to
fully maximize frames.  To resize your initial frame pixelwise,
set this option to a non-nil value in your init file.
```

**Comment by d12frosted** [comment]
wow, @sooheon. I didn't know about this variable. Thanks for sharing :)

**Comment by TheBaronHimself** [comment]
I spent quite a while looking for this solution, as well. Do you think it should be included as an optional setting (set to nil by default) in .spacemacs? Seems useful. 

@syl20bnr @d12frosted
