### ISSUE TITLE
Opening an Objective-C File Asks for Octave Every Time

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#5634]
#### Description

When I try to open an Objective-C file (`.m` extension) I get prompted if I want to install the `octave` layer. Even if I say no it opens the file in `octave-mode` instead of `objc-mode` like in stock Emacs. This happens every time I try to open such a file.
#### Reproduction guide
- Start Emacs (without octave layer)
- Open an Objective-C file. (`.m` extension)

_Observed behaviour:_
Prompted to install the `octave` layer. When no is selected file is opened in `octave-mode`. The prompt happens every time for a `.m` file.

_Expected behaviour:_
Open the file in `objc-mode` which is built in, or at the very least not be prompted every time a file is opened.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 91eeccc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((clojure :variables clojure-enable-fancify-symbols t)
 typescript colors docker emacs-lisp html github markdown osx react restclient shell-scripts syntax-checking vimscript yaml
 (auto-completion :variables auto-completion-enable-help-tooltip t)
 (git :variables git-magit-status-fullscreen t magit-push-always-verify nil)
 (javascript :variables js2-mode-show-parse-errors nil js2-mode-show-strict-warnings nil)
 (org :variables org-src-preserve-indentation t org-startup-folded 'showall)
 shell
 (version-control :variables version-control-diff-tool 'diff-hl))
```

**Comment by NJBS** [comment]
This is because spacemacs' [auto-layer associates the `.m` extension with the octave layer and octave-mode](https://github.com/syl20bnr/spacemacs/blob/develop/layers/auto-layer.el#L74) whereas the default `auto-mode-alist` associates them with objective-c files.

For now you can get around this by setting `dotspacemacs-enable-lazy-installation` to `nil` in your dotfile. I personally don't think lazy installation associations should conflict with `auto-mode-alist` but that leaves us with no way to lazy install the octave layer.

cc @syl20bnr

**Comment by jupl** [comment]
That makes sense. The workaround should do, although I do agree with your opinion.

What is still a major problem (IMO) is that I still get nagged if I want to install the layer every time I open a file even if I say no.

**Comment by syl20bnr** [comment]
For now we can set the most used extension.
I'll add support for multiple layers per extension with a completing-read interface but it may require some work.

**Comment by iqbalansari** [comment]
Just a suggestion maybe spacemacs can add an entry `magic-mode-alist` which uses some heuristics to determine whether objective-c or octave mode should be used for a file.

One way might be to check if the file has any objective-c constructs like `@implementation`, something like the following might work

``` emacs-lisp
(defun spacemacs/objective-c-file-p ()
  (and buffer-file-name
       (string= (file-name-extension buffer-file-name) "m")
       (re-search-forward "@interface" 
                          magic-mode-regexp-match-limit t))))

(add-to-list 'magic-mode-alist
             (cons #'spacemacs/objective-c-file-p #'objc-mode))
```

**Comment by syl20bnr** [comment]
Interesting use of `magic-mode-alist`, I'm not sure about the magic alist priorities though.

**Comment by iqbalansari** [comment]
According to Emacs [manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Choosing-Modes.html) `magic-mode-alist` has higher priority than `auto-mode-alist`.

**Comment by phinicota** [comment]
Just wanted to point out .m files are also used for matlab script files (matlab-mode in extra-langs layer).
Don't know if related but, after disabling octave layer (without restarting emacs) and re-enabling extra-langs layer, .m files stay associated with octave-mode (which were previously associated with matlab-mode before enabling octave-layer).

**Comment by bimawa** [comment]
Someone solve this?

**Comment by MaskRay** [comment]
bump for https://github.com/syl20bnr/spacemacs/issues/5634#issuecomment-204340185

**Comment by hpincket** [comment]
The `.m` extension is also used for the Mercury programming language.

**Comment by historybuffjb** [comment]
Has there been any work on this issue?

**Comment by suatkarakusoglu** [comment]
Hey there, I have also experienced this issue as I am iOS developer.
I have found a simple solution that has not been mentioned here.

Overriding the default octave mode can be accomplished through overriding the octave association in .spacemacs file at dotspacemacs/user-config funtion.

Such like:

`(defun dotspacemacs/user-config ()
  "Configuration for user code:
This function is called at the very end of Spacemacs startup, after layer
configuration.
Put your configuration code here, except for variables that should be set
before packages are loaded."
  (add-to-list 'auto-mode-alist '("\\.m" . objc-mode))
  )`

I hope it helps you as well.

**Comment by Atemu** [comment]
This is still an issue.

**Comment by august-feng** [comment]
We can configure `auto-mode-alist` using [directory variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html). I'm going to try having a `.dir-locals.el` file:

```el
((auto-mode-alist . (("\\.m\\'" . objc-mode))))
```
