### ISSUE TITLE
Trouble with Auto-completion

### ISSUE THREAD

**Issue by LikiPiki** [syl20bnr/spacemacs#5638]
I have a trouble
When i do 
1) go to `.spacemacs` and uncomment `;;auto-completion`
2) then i reload emacs and packages installed
3) i create a new `main.cpp` file
4) and open this file in spacemacs 
5) yasnippet and auto-complete worked very cool
But when i close my spacemacs and open it again. auto-complete worked when i tap `C j ` and `C k` yasnippet don't worked on `TAB` in `main.cpp`
How it fixed. Thanks beforehand!

**Comment by bmag** [comment]
Did you also enable the `c-c++` layer?

**Comment by LikiPiki** [comment]
Tes

**Comment by LikiPiki** [comment]
Yes

**Comment by bmag** [comment]
Ok, if I understand correctly, you're saying that you get do a completion popup in `main.cpp`. Pressing `C-j` and `C-k` does select next/previous completion candidate, but pressing `TAB` doesn't trigger yasnippet expansion.

As you can read [here](http://spacemacs.org/layers/auto-completion/README.html#orgheadline16), `TAB` isn't supposed to trigger yasnippet. Instead, use `M-/`. You can enable yasnippet expansion on `TAB` by replacing `auto-completion` with `(auto-completion :variables auto-completion-enable-help-tooltip t)` as noted [here](http://spacemacs.org/layers/auto-completion/README.html#orgheadline5).

By the way, this documentation is also available inside spacemacs via `SPC h SPC` and `SPC h l`.

**Comment by LikiPiki** [comment]
https://gist.github.com/LikiPiki/7f95ab67c7450fbfdc24bf47022d3a1a okay i add this code in my `.spacemacs` but auto-complete and yasnipet didnt worked http://i.imgur.com/MTntibX.png

**Comment by LikiPiki** [comment]
I add some code in my .spacemacs and i have rezult
when i press `TAB` key snippet will expand
http://i.imgur.com/gCBZvgL.png
```
     (auto-completion :variables auto-completion-enable-help-tooltip t
                      auto-completion-enable-snippets-in-popup t
                      auto-completion-tab-key-behavior 'complete)
```

Thanks a lot. All the best from Russian developer

**Comment by d12frosted** [comment]
Hey, an advice that would help you in the future. When you create new issue you'll see following content:

```
If you are posting about a *bug* please close this issue and open a new one
using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs.
You can delete this message to start typing.
```

Doing this or at least pasting output of `SPC h d s` helps to avoid questions like following.

> Did you also enable the c-c++ layer?

P. S. no offence :)

**Comment by LikiPiki** [comment]
Ok, no problem. And thanks for answer
