### ISSUE TITLE
Contacting host tries for too long on startup

### ISSUE THREAD

**Issue by gnzlbg** [syl20bnr/spacemacs#5641]
I use spacemacs a lot in systems with bad or no internet connection at all. 

Right now every time I start spacemacs it tries to e.g. contact host melpa.org:80 for a very long time.

I would like spacemacs to ping the host first, and if it cannot reach it in 1-2 seconds for it to skip it and keep on starting. 

Trying to update spacemacs packages on startup is a nice thing to do, but trying to do so in systems with bad or no internet connection is IMO very annoying.

**Comment by syl20bnr** [comment]
Are you on master or develop ?

**Comment by gnzlbg** [comment]
master

**Comment by syl20bnr** [comment]
That's weird, there should be a time out of 5 seconds (variable `dotspacemacs-elpa-timeout`).
We can't fix this if the issue is a slow connection :-(

Have you tried to turn off your connection ? Spacemacs should display a timeout when it attempts to reach the host.

**Comment by gnzlbg** [comment]
On Fri, Apr 1, 2016 at 6:44 AM, Sylvain Benner <notifications@github.com>
wrote:

> dotspacemacs-elpa-timeout


I'll try to set that to 1 and see if it works.

The problem is that in some hosts where I use spacemacs only connections to
some IPs are whitelisted, the rest are blocked by the firewall and should
just time out.
