### ISSUE TITLE
space-doc lighter " ❤" has to go :crying_cat_face:  [visual bug]

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#5642]
[While the " ❤" is extremely awesome and appropriate](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bemacs/org/local/space-doc/space-doc.el#L37). And using it is, pretty much,  the best idea I ever had... 
It's too fat. One can say "the love is too big" and the [spaceline](https://github.com/TheBB/spaceline) simply can't handle it.

![](http://i.imgur.com/QrXXwYK.png?1)
![](http://i.imgur.com/z0rDg9v.png?1)

So we have to tear out the heart and replace it with something boring and heartless.

I think  @syl20bnr  should pick something better.

**Comment by JAremko** [comment]
Sorry for not noticing it earlier :disappointed:   I was using scaled up  spaceline and looks like the glitch shows only if the scale factor isn't too big.

**Comment by syl20bnr** [comment]
Is there any other heart we can use ?

**Comment by JAremko** [comment]
@syl20bnr  You can take mine if it helps :cry:

Actually I tested many symbols and the most of them don't work.  I think this one did: 
##  ☕

**Comment by JAremko** [comment]
## `	☕`

**Comment by JAremko** [comment]
Fixed in #5706
