### ISSUE TITLE
"zb" and `scroll-margin`

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#5643]
`evil-scroll-line-to-bottom` is not working well when `scroll-margin` is set:

1. Open a file that is large enough to not fit in the window
2. Jump to the end of the file with "G"
3. Jump to the top of the windows with "H"
4. Scroll to the bottom with "zb"

Perform these steps with `scroll-margin` set to 0 (the default) and then with it set to 5.

- When set to 0 all the jumping and scrolling behaves as expected.
- When set to 5 the final scrolling doesn't go to the bottom, only to the centre, i.e. "zb" behaves exactly like "zz"

### Systems

I've observed this behaviour on both *master* and *develop*. With default `~/.spacemacs` files.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. 3aff734)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: develop (rev. 05a0476)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm emacs-lisp)
```

**Comment by JAremko** [comment]
Might be related to the commit [New implementation of scroll commands](https://bitbucket.org/lyro/evil/commits/75fbea13e440)  that was recently pushed.  I think you should report it there.

**Comment by magthe** [comment]
@JAremko that commit is an hour old, the behaviour I report on above was first observed several days ago. I just haven't bothered writing it down until now.

So if anything, that evil commit might be a fix :)

**Comment by JAremko** [comment]
@magthe  [It should be](https://bitbucket.org/lyro/evil/issues/618/evil-scroll-down-cannot-make-it-to-the-end) :smile:

**Comment by magthe** [comment]
It's indeed been fixed by now. `evil-20160331.517`
