### ISSUE TITLE
Provide an alternative linter for the go layer

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#5644]
We can add an alternative to the default Spacemacs go linter [Flycheck checker for golang using gometalinter](https://github.com/favadi/flycheck-gometalinter)  But not sure how it performs - it might be too heavy for a complete replacement.

**Comment by nixmaniack** [comment]
For reference: https://github.com/syl20bnr/spacemacs/pull/4108

**Comment by JAremko** [comment]
@nixmaniack  thanks.  I hope it will be merged. :disappointed:

**Comment by JAremko** [comment]
I played with them. Awesome linters.   Kinda like if your mom did code review :+1: 

I wonder what @bogdanteleaga  thinks.
