### ISSUE TITLE
Can't disable April Fool!!

### ISSUE THREAD

**Issue by KenetJervet** [syl20bnr/spacemacs#5649]
We like having fun but we are also working hard.

We could at least have an option to disable the april fool surprise completely, instead of having to `SPC m aprilfool` each time (I'm in Emacs mode and I have to switch to Vim mode to actually get the key combo working. For somereason M-m aprilfool does not work)

**Comment by cpaulik** [comment]
You don't have to type `SPC m aprilfool` at all. Just start working. `SPC p p` `SPC p l` etc. all work as usual.

**Comment by dustym** [comment]
This is absurd. Why would anyone think this is a good idea?

**Comment by KenetJervet** [comment]
I don't know. I frequently open files from the `Recent Files` list. I just found this april fool "feature" a bit regression of current functionalities. Maybe I'm really a fool.

**Comment by cpaulik** [comment]
I just think that it is not a big deal since also `SPC f r` works also.

Just as a side question, how often per day do you start your emacs? I only do it once so I only see the aprilfools once.

**Comment by dustym** [comment]
@KenetJervet I just commented out this expression https://github.com/syl20bnr/spacemacs/blob/master/core/core-spacemacs.el#L294-L296

**Comment by d12frosted** [comment]
Wow. If it's wasn't this issues I wouldn't know about zemacs. Awesome guys. Zemacs is the **only** **right** editor in the history of humankind!

**Comment by KenetJervet** [comment]
@cpaulik cool. first time i knew this.

I just happen to be fixing an anaconda-mode bug and restart emacs many times (i'm not a heavy emacs lisp user and don't know how to effectively debug something without restarting the whole session)..

and you are right. it's not a very big deal. the work today is almost done and we are on holiday (UTC+8) but still i think the developers should think twice before adding features. it would be best if this is a one-time surprise.

**Comment by cpaulik** [comment]
@KenetJervet If you change an elisp function you can just evaluate it by pressing `SPC m e e` or `C-x C-e` at the end of the expression. This updates the function and you can use it with the new behaviour. Happy April Fools :tada:

**Comment by syl20bnr** [comment]
Fixed for the next millennium!

**Comment by d12frosted** [comment]
> ><((((*>

it's fish shell!

**Comment by JAremko** [comment]
![](http://i.imgur.com/PcQqYUl.gif)
