### ISSUE TITLE
<SPC> f e d: destructive

### ISSUE THREAD

**Issue by pesterhazy** [syl20bnr/spacemacs#565]
The combination `<SPC> f d` destuctively removes the the current file (`delete-current-buffer-file`) without being able to undo the mistake. It's easy to hit this key combination by mistake because `fd` is the universal escape sequence. `delete-current-buffer-file` also does not ask for confirmation.

In my view the function should not be accessible using a keyboard shortcut by default.

**Comment by codygman** [comment]
eesh, that sound pretty bad. Thanks for the warning, it sounds like that should at least have a confirmation.

**Comment by CestDiego** [comment]
I think we have trash support right? maybe it's in the .Trash

**Comment by CestDiego** [comment]
https://github.com/syl20bnr/spacemacs/blob/34e4ef7bf6aec937e1afa1d2e9cef8f857cba547/spacemacs/config.el#L111-L123

**Comment by syl20bnr** [comment]
ouch very sorry for this :-( But what can I do more ? There already is a confirmation prompt. Also trash is enabled by default in Spacemacs as mentioned by @CestDiego.

**Comment by CestDiego** [comment]
@syl20bnr if only we could implement a `spacemacs/restore-last-deleted-file` .... :P

**Comment by syl20bnr** [comment]
@CestDiego would be very handy indeed, as well as a `open trash in dired` maybe.

**Comment by syl20bnr** [comment]
@pesterhazy wee you able to retrieve your deleted file in the trash directory ?

**Comment by syl20bnr** [comment]
I propose to move it on `SPC f D`

**Comment by CestDiego** [comment]
that makes sense.

**Comment by syl20bnr** [comment]
@pesterhazy I let you submit a PR to change the bindings on `SPC f D`

**Comment by pesterhazy** [comment]
@syl20bnr Makes sense. I didn't notice the confirmation prompt before, but it looks like it's there.
