### ISSUE TITLE
Install spacemacs (with all plugins) in a docker image

### ISSUE THREAD

**Issue by casertap** [syl20bnr/spacemacs#5658]
I would like to install spacemacs inside a docker image so I can run the container and develop within spacemacs inside my container.

Every time I spin up the container, I have to reinstall the startup plugins... 
I would like to trigger this installation once and for all during the docker image building time.
I am trying to run commands such as:

```
RUN emacs --batch --eval "(package-initialize)"
```

But it did not do the job.

I also trying to install packages manually using the small utility: emacs-pkg-install.el

```
RUN emacs --batch --eval "(defconst pkg-to-install 'projectile)"
```

but it did not work neither

Here is the repository to reproduce my problem:
https://github.com/casertap/docker-spacemacs

I have done the work emacs already but I would like to switch to spacemacs now.
Thanks

**Comment by chrisbarrett** [comment]
You'll probably need to install a default ~/.spacemacs into the container or the Spacemacs boot process will hang waiting for user input. I'm tethering right now, I'll have a look into your dockerfile later.

**Comment by JAremko** [comment]
https://hub.docker.com/r/jare/spacemacs/

**Comment by casertap** [comment]
Thanks @chrisbarrett I am looking forward into that.
Thanks @JAremko but I would prefer to build my own image because it does not match my programming language and tools I am using.
Can you help me pre-install the spacemacs (startup) plugins during the docker build phase ? (and not when I start emacs in my container)

**Comment by JAremko** [comment]
@casertap  You just need a .spacemacs file with you want. then just use this code https://github.com/JAremko/spacemacs/blob/master/Dockerfile#L97

**Comment by casertap** [comment]
thanks.
I get some timeout today. This was not the case yesterday so I will try later but here is what I get:
(I am using the default .spacemacs, (I updated my repository))
```
Step 11 : COPY .spacemacs /root/.spacemacs
 ---> Using cache
 ---> 47c202114169
Step 12 : RUN emacs -nw -batch -u root -q -kill
 ---> Running in f6bbae2b2276
Loading 00debian-vars...
Loading /root/.emacs.d/core/core-load-paths.el (source)...
Loading /root/.spacemacs...
Contacting host: melpa.org:443
Warning (spacemacs):
Error connection time out for melpa repository!
Contacting host: orgmode.org:80
Warning (spacemacs):
Error connection time out for org repository!
Contacting host: elpa.gnu.org:443
Warning (spacemacs):
Error connection time out for gnu repository!
Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (error Package `spacemacs-theme-' is unavailable))
Saving file /root/.emacs.d/.cache/spacemacs-buffer.el...
Wrote /root/.emacs.d/.cache/spacemacs-buffer.el
Open the quickhelp.
Warning (initialization): An error occurred while loading `/root/.emacs.d/init.el':

error: Package `evil-' is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
Spacemacs is ready.
 ---> 9099b698ea84
Removing intermediate container f6bbae2b2276
Successfully built 9099b698ea84
```

**Comment by JAremko** [comment]
Btw when I tried to include all of the Spacemacs layers I got a ton of conflicts.

**Comment by syl20bnr** [comment]
@JAremko there should be very few conflicts or issues, but the changes I made recently may have introduced some regression in some packages (which is for the best because those regression should pinpoint a bad layer design somewhere).

The only bad side effect I'm aware is that some layer's purpose is to replace others, I think I will ignore these layers when using the `'all` keyword.

**Comment by casertap** [comment]
I think I have the same problem as those guys: https://github.com/syl20bnr/spacemacs/issues/4375

**Comment by JAremko** [comment]
@syl20bnr  
> The only bad side effect I'm aware is that some layer's purpose is to replace others, I think I will ignore these layers when using the 'all keyword.  

That would be really cool :+1:  But probably with some other word. `all` that does not install all is a bit misleading.

**Comment by robbyoconnor** [comment]
Can you run GUI apps in docker?

**Comment by JAremko** [comment]
@robbyoconnor  I run Spacemacs with GUI

**Comment by StreakyCobra** [comment]
Side note: When using docker, be sure to [set the `SHELL` variable](https://github.com/syl20bnr/spacemacs/issues/3652#issuecomment-180946962).

**Comment by JAremko** [comment]
https://github.com/JAremko/spacemacs/blob/master/start.bash

**Comment by casertap** [comment]
I solved the problem using the develop branch.
Now I get this message at the end but spaceman is installed.

````
Loading 00debian-vars...
Loading /root/.emacs.d/core/core-load-paths.el (source)...
Loading /root/.spacemacs...
Contacting host: melpa.org:443
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: melpa.org:443
Contacting host: melpa.org:443
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: orgmode.org:80
Contacting host: elpa.gnu.org:443
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Contacting host: melpa.org:443
Contacting host: melpa.org:443
Parsing tar file...
Parsing tar file...done
Extracting spacemacs-theme-20160310.1337/
...
...
...
(Spacemacs) --> installing package: window-numbering@spacemacs-ui... [89/90]
Generating autoloads for window-numbering.el...
Generating autoloads for window-numbering.el...done
Saving file /root/.emacs.d/elpa/window-numbering-20150228.1247/window-numbering-autoloads.el...
Wrote /root/.emacs.d/elpa/window-numbering-20150228.1247/window-numbering-autoloads.el
(No changes need to be saved)
Checking /root/.emacs.d/elpa/window-numbering-20150228.1247...
Compiling /root/.emacs.d/elpa/window-numbering-20150228.1247/window-numbering-autoloads.el...
Compiling /root/.emacs.d/elpa/window-numbering-20150228.1247/window-numbering-pkg.el...
Wrote /root/.emacs.d/elpa/window-numbering-20150228.1247/window-numbering-pkg.elc
Compiling /root/.emacs.d/elpa/window-numbering-20150228.1247/window-numbering.el...
Wrote /root/.emacs.d/elpa/window-numbering-20150228.1247/window-numbering.elc
Done (Total of 2 files compiled, 1 skipped)
(Spacemacs) --> installing package: ws-butler@spacemacs-base... [90/90]
Contacting host: melpa.org:443
Generating autoloads for ws-butler.el...
Generating autoloads for ws-butler.el...done
Saving file /root/.emacs.d/elpa/ws-butler-20150126.759/ws-butler-autoloads.el...
Wrote /root/.emacs.d/elpa/ws-butler-20150126.759/ws-butler-autoloads.el
(No changes need to be saved)
Checking /root/.emacs.d/elpa/ws-butler-20150126.759...
Compiling /root/.emacs.d/elpa/ws-butler-20150126.759/ws-butler-autoloads.el...
Compiling /root/.emacs.d/elpa/ws-butler-20150126.759/ws-butler-pkg.el...
Wrote /root/.emacs.d/elpa/ws-butler-20150126.759/ws-butler-pkg.elc
Compiling /root/.emacs.d/elpa/ws-butler-20150126.759/ws-butler.el...
Wrote /root/.emacs.d/elpa/ws-butler-20150126.759/ws-butler.elc
Done (Total of 2 files compiled, 1 skipped)
Truncate long lines enabled

Warning (initialization): An error occurred while loading `/root/.emacs.d/init.el':

Wrong type argument: stringp, nil

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
Spacemacs is ready.
 ---> 30199511e1a4
Removing intermediate container 439ebd95bc95
Successfully built 30199511e1a4
```

I added the SHELL variable and try to rebuild the image from scratch again and I get:

````
Loading 00debian-vars...
Loading /root/.emacs.d/core/core-load-paths.el (source)...
Loading /root/.spacemacs...
Contacting host: melpa.org:443
Warning (spacemacs): 
Error connection time out for melpa repository!
Contacting host: orgmode.org:80
Warning (spacemacs): 
Error connection time out for org repository!
Contacting host: elpa.gnu.org:443
Importing package-keyring.gpg...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Contacting host: elpa.gnu.org:443
Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (error Package `spacemacs-theme-' is unavailable))
Open the quickhelp.
Loading /root/.emacs.d/layers/+distribution/spacemacs-bootstrap/funcs.el (source)...
Loading /root/.emacs.d/layers/+distribution/spacemacs/config.el (source)...
Loading /root/.emacs.d/layers/+distribution/spacemacs-base/funcs.el (source)...
Loading /root/.emacs.d/layers/+distribution/spacemacs-base/config.el (source)...
Loading /root/.emacs.d/layers/+spacemacs/spacemacs-layouts/funcs.el (source)...
Loading /root/.emacs.d/layers/+spacemacs/spacemacs-layouts/config.el (source)...
Loading /root/.emacs.d/layers/+lang/emacs-lisp/config.el (source)...
Loading /root/.emacs.d/layers/+completion/spacemacs-helm/packages.el (source)...
Loading /root/.emacs.d/layers/+spacemacs/spacemacs-ui-visual/packages.el (source)...
Loading /root/.emacs.d/layers/+spacemacs/spacemacs-ui/packages.el (source)...
Loading /root/.emacs.d/layers/+spacemacs/spacemacs-language/packages.el (source)...
Loading /root/.emacs.d/layers/+spacemacs/spacemacs-evil/packages.el (source)...
Loading /root/.emacs.d/layers/+spacemacs/spacemacs-editing-visual/packages.el (source)...
Loading /root/.emacs.d/layers/+spacemacs/spacemacs-editing/packages.el (source)...
Loading /root/.emacs.d/layers/+spacemacs/spacemacs-editing/packages-funcs.el (source)...
Loading /root/.emacs.d/layers/+spacemacs/spacemacs-layouts/packages.el (source)...
Loading /root/.emacs.d/layers/+distribution/spacemacs-base/packages.el (source)...
Loading /root/.emacs.d/layers/+distribution/spacemacs-bootstrap/packages.el (source)...
Eager macro-expansion failure: (void-variable evil-normal-state-map)
Loading /root/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...
Loading /root/.emacs.d/layers/auto-layer.el (source)...
Warning (initialization): An error occurred while loading `/root/.emacs.d/init.el':

error: Package `package-build-' is unavailable

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
Spacemacs is ready.
 ---> d8fc856d27d0
Removing intermediate container df948ed35e00
Successfully built d8fc856d27d0
````

So switching from master to develop did solve the problem but I get at the end:
````
Warning (initialization): An error occurred while loading `/root/.emacs.d/init.el':
Wrong type argument: stringp, nil
`````

Setting SHELL=/bin/bash did not do any good

**Comment by JAremko** [comment]
You should remove stuff after this  line https://github.com/casertap/docker-spacemacs/blob/master/.spacemacs#L252  
Also make sure that this .spacemacs file works outside docker.

**Comment by JAremko** [comment]
And read this https://github.com/syl20bnr/spacemacs/wiki/Debugging
