### ISSUE TITLE
spaceline isn't loading on latest develop

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#5662]
Recent change cc5afabcaea4bdd6bfceae8bfe4d41a07a550ae2 deferred loading of spaceline but looks like it isn't loading spaceline at all after this change. 

I also had `(spaceline-toggle-org-clock-off)` in my user-config which I've wrapped in `(with-eval-after-load 'spaceline ...)` after this change caused it to error out. 

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: develop (rev. 22c2763)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip nil auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" :disabled-for org erc)
 semantic better-defaults emacs-lisp
 (git :variables git-gutter-use-fringe t git-magit-status-fullscreen nil)
 github markdown yaml shell
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t)
 syntax-checking twitter
 (elfeed :variables rmh-elfeed-org-files
         (list "~/.emacs.d/private/elfeed.org"))
 lua python ruby ruby-on-rails
 (clojure :variables clojure-enable-fancify-symbols t)
 go shell-scripts html javascript dockerfile spacemacs-layouts window-purpose
 (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu4e/" mu4e-enable-mode-line t mu4e-enable-notifications t)
 nix-mu4e gnus colors deft finance
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (version-control :variables version-control-diff-tool 'diff-hl)
 ansible emoji ranger prodigy osx typography
 (theming :variables theming-headings-inherit-from-default 'all theming-headings-same-size 'all theming-headings-bold 'all)
 org command-log erc pdf-tools
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```

cc: @sooheon

**Comment by NJBS** [comment]
Do you still get an error if you `with-eval-after-load` `spaceline-segments` instead of `spaceline`?

**Comment by syl20bnr** [comment]
Thank you for the report, I reverted the experimental `:defer 0.1` for now.

@TheBB Couple of questions:

1- spaceline can take up to 1 seconds to load on my system, I did not profile it so I don't know which requires slow down the loading.

2- What do you think about `:defer 0.1` ? It really smooth the loading experience on my system. We could  add a level of indirection in Spacemacs with a macro encapsulating the toogle call in an eval-after-load. While not ideal we could mention it in the spaceline documentation itself so it would make it less sneaky.

Anyway I let you try the trick, let me know what do you think.

**Comment by nixmaniack** [comment]
@NJBS I tried your suggestion and it works. :+1: 
So with `defer 0.1` in place and wrapping configuration of spaceline in `with-eval-after-load 'spaceline-segments` helps to load spaceline lazily(I think so!)

**Comment by robbyoconnor** [comment]
Looks like it was fixed

**Comment by robbyoconnor** [comment]
@nixmaniack  close this :)

**Comment by nixmaniack** [comment]
@robbyoconnor Indeed it's fixed!
