### ISSUE TITLE
the Evil-Cleverparens layer breaks evil-surround

### ISSUE THREAD

**Issue by gilch** [syl20bnr/spacemacs#5666]
#### Description

Can't use evil-surround when evil-cleverparens is active.
#### Reproduction guide
- Start Emac?h
- `SPC f e d` add `evil-cleverparens` to `dotspacemacs-configuration-layers`
- activate in a major mode e.g.

``` elisp
  (spacemacs/toggle-evil-cleverparens-on)
  (add-hook 'clojure-mode-hook #'evil-cleverparens-mode)
```

in `dotspacemacs/user-config`.
Reload spacemacs and try using surround in that mode.

**Comment by syl20bnr** [comment]
Not sure 100% but flagging it `should report upstream`: https://github.com/luxbock/evil-cleverparens

cc @luxbock

**Comment by gilch** [comment]
Cleverparens works by overriding certain Vim commands to better respect parentheses. Spacemacs moved the default surround key, so I'm not certain an upstream fix will be enough.

We need surround's version for those keys, so we might need a way to load evil-cleverparens first and evil-surround second, or have the cleverparens layer put just those keybindings back to Spacemacs' default (i.e. surround) after it loads the package.

The cleverparens layer documentation didn't explain very well how to set it up, see #5569.

The best alternative to cleverparens is parinfer, but that isn't working right either, and doesn't even have a layer yet, see #5574.

**Comment by syl20bnr** [comment]
> Cleverparens works by overriding certain Vim commands to better respect parentheses. Spacemacs moved the default surround key, so I'm not certain an upstream fix will be enough.

Changing the key bindings should not prevent an evil-surround integration in cleverparens from working in Spacemacs.

**Comment by idrozd** [comment]
Also breaks evil-snipe, even when snipe if enlisted after in **dotspacemacs-configuration-layers**

Putting evil-cleverparens first in the list, like @gilch, however, fixed evil-surround, at least.

**Comment by luxbock** [comment]
Here is how I enable the evil-surround operations with `evil-cleverparens`:

https://github.com/luxbock/evil-cleverparens/blob/2e5f87be259b47ef37b91a5582f0d008ba6ce508/evil-cleverparens.el#L2114-L2118

I think this needs to happen once `evil-surround` has already been loaded.

If anyone can propose a fix that gets around it I'm happy to fix it upstream.
