### ISSUE TITLE
add basic evil keys to M-x customize

### ISSUE THREAD

**Issue by gilch** [syl20bnr/spacemacs#5668]
New users migrating from Vim could be very confused by this. Before I learned that `M-m` could replace the `SPC` leader and `f10` opened the menu I had no way to switch out of a Custom mode buffer. I resorted to restarting emacs.

It's not enough to evilify the buffer, since you have to be able to type things into the text boxes.

**Comment by TheBB** [comment]
Closing this in favor of https://github.com/syl20bnr/spacemacs/issues/6699
