### ISSUE TITLE
ipython-notebook layer commands not working as expected (i.e. SPC f s doesn't really save the notebook)

### ISSUE THREAD

**Issue by jbmorgado** [syl20bnr/spacemacs#5671]
#### Description

Some ipython-notebook layer commands not working as expected. For instance: `C-r` doesn't call the `ein:notebook-rename-command` as expected, and worst `SPC f s` doesn't `save the notebook like you would a regular buffer` and as expressed in the documentation, instead it saves the all ein environment.
#### Reproduction guide
- Start Emacs
- Open a Jupyter notebook in command line.
- Create a Notebook in Emacs with `SPC a i n` and then choosing new notebook (or open an existing one).

_Observed behaviour:_
- `SPC f s` calls `basic-save-buffer` instead of the intended `ein:notebook-save-notebook-command`
- `C-r` doesn't do anything

_Expected behaviour:_
- `SPC f s` should save the notebook correctly by calling `ein:notebook-save-notebook-command`
- `C-r` should rename the notebook correctly by calling `ein:notebook-rename-command`
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. 3aff734)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-complete-with-key-sequence-delay 0.8 auto-completion-enable-help-tooltip t auto-completion-private-snippets-directory "~/Dropbox/Apps/Yasnippet")
 emacs-lisp ess extra-langs
 (git :variables magit-repository-directories
      '("~/repos/"))
 html ipython-notebook
 (latex :variables latex-build-command "LatexMk")
 markdown
 (org :variables org-enable-github-support t)
 osx
 (python :variables python-enable-yapf-format-on-save t)
 shell
 (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
 (syntax-checking :variables syntax-checking-enable-tooltips nil syntax-checking-enable-by-default nil)
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t))
```

**Comment by AlejandroCatalina** [comment]
Actually, those bindings are intented to be for major mode, so my guess is it works pressing `SPC m f s` and so.

**Comment by cpaulik** [comment]
The `SPC f s` bug was introduced in https://github.com/syl20bnr/spacemacs/commit/9befd20a1a81da0b4b94c69e35951f907bee4615#diff-843bfb6ce8877b56e6d6252b9519852dL62 

@TheBB @justbur is it still ok to use `(evil-leader/set-key-for-mode)`?

`C-r` is indeed supposed to be used with `SPC m`.

**Comment by ManasGeorge** [comment]
Is there any way to map `SPC f s` to `ein:notebook-save-notebook-command`? I've been trying to override maps, remapping at hooks, everything. The closest I got was remapping it in `evil-normal-state-map` but that doesn't keep it buffer local, and for some reason I can't change it in the buffer local version of the map, `evil-normal-state-local-map`

**Comment by cpaulik** [comment]
Have you tried (evil-leader/set-key-for-mode) ?

**Comment by cpaulik** [comment]
@ManasGeorge See https://github.com/syl20bnr/spacemacs/pull/6289

**Comment by ManasGeorge** [comment]
Didn't seem to work. How is `evil-leader/set-key-for-mode` different from `spacemacs/set-leader-keys-for-major-mode` again?

**Comment by TheBB** [comment]
They're the same, as @bmag mentioned in the PR.
