### ISSUE TITLE
Cannot Satisfy -packae-id Haskell Layer

### ISSUE THREAD

**Issue by mckeankylej** [syl20bnr/spacemacs#5674]
#### Description
When I save a file a haskell buffer I get a \*GHC Error\* buffer telling me that it cant satisfy package ids. 

#### Reproduction guide
- Clone this [repo](https://github.com/mckeankylej/laura)
- Start emacs
- Go to file
- SPC f s

*Observed behaviour:*

<command line>: cannot satisfy -package-id MonadRandom-0.4.2.1-4c245241cae6f5a7bd0e0375c092f848: 
    MonadRandom-0.4.2.1-4c245241cae6f5a7bd0e0375c092f848 is unusable due to missing or recursive dependencies:
      base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d mtl-2.2.1-3af90341e75ee52dfc4e3143b4e5d219 random-1.1-c46cc413d88c0a330b5495d03f0ed464 transformers-0.4.2.0-81450cd8f86b36eaa8fa0cbaf6efc3a3 transformers-compat-0.4.0.4-8aa4073730c676dbe210ea8bffd8d092
    (use -v for more information)

*Expected behaviour:*
Save and Flycheck

#### System Info
- OS: gnu/linux
- Emacs: 24.5.50.1
- Spacemacs: 0.105.11
- Spacemacs branch: develop (rev. 8355671)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp haskell idris git org
                 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp")
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control spotify games erc xkcd finance)
```

**Comment by kRITZCREEK** [comment]
Did you run stack build in your project? It might also be a dependency for your tests so make sure you installed those aswell.

**Comment by mckeankylej** [comment]
I have run stack buiId and I don't have any tests.

**Comment by kRITZCREEK** [comment]
Did you maybe do a mix of cabal and stack and have a `cabal.sandbox` or `dist/` folder lying around? If that doesn't help you can stack install the missing dependencies manually, but that shouldn't be necessary.

**Comment by mckeankylej** [comment]
No infact I don't even have cabal installed.

**Comment by kRITZCREEK** [comment]
@mckeankylej `stack install MonadRandom`

**Comment by mckeankylej** [comment]
Still doesnt work after running `stack install MonadRandom` also there is a slight difference when opening a file and saving it seen here:

<command line>: cannot satisfy -package-id MonadRandom-0.4.2.1-4c245241cae6f5a7bd0e0375c092f848: 
    MonadRandom-0.4.2.1-4c245241cae6f5a7bd0e0375c092f848 is unusable due to missing or recursive dependencies:
      base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d mtl-2.2.1-3af90341e75ee52dfc4e3143b4e5d219 random-1.1-c46cc413d88c0a330b5495d03f0ed464 transformers-0.4.2.0-81450cd8f86b36eaa8fa0cbaf6efc3a3 transformers-compat-0.4.0.4-8aa4073730c676dbe210ea8bffd8d092
    (use -v for more information)
<command line>: cannot satisfy -package-id MonadRandom-0.4.2.1-4c245241cae6f5a7bd0e0375c092f848: 
    MonadRandom-0.4.2.1-4c245241cae6f5a7bd0e0375c092f848 is unusable due to missing or recursive dependencies:
      base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d mtl-2.2.1-3af90341e75ee52dfc4e3143b4e5d219 random-1.1-c46cc413d88c0a330b5495d03f0ed464 transformers-0.4.2.0-81450cd8f86b36eaa8fa0cbaf6efc3a3 transformers-compat-0.4.0.4-8aa4073730c676dbe210ea8bffd8d092
    (use -v for more information)
ghc-mod: <command line>: cannot satisfy -package-id MonadRandom-0.4.2.1-4c245241cae6f5a7bd0e0375c092f848: 
    MonadRandom-0.4.2.1-4c245241cae6f5a7bd0e0375c092f848 is unusable due to missing or recursive dependencies:
      base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d mtl-2.2.1-3af90341e75ee52dfc4e3143b4e5d219 random-1.1-c46cc413d88c0a330b5495d03f0ed464 transformers-0.4.2.0-81450cd8f86b36eaa8fa0cbaf6efc3a3 transformers-compat-0.4.0.4-8aa4073730c676dbe210ea8bffd8d092
    (use -v for more information)

**Comment by kRITZCREEK** [comment]
hmm now ghc-mod is also in the mix? Maybe disable the ghc-mod layer variable.

**Comment by mckeankylej** [comment]
@kRITZCREEK Sorry I am new to spacemacs how do I do that

**Comment by bsermons** [comment]
I think ghc-mod is probably the culprit.  I had a similar issue with aeson that resolved itself when I updated the stack.yaml to use the latest LTS and then reinstalling ghc-mod.  

You can try @kRITZCREEK 's suggestion and add this to your `dotspacemacs/user-config` and see if it goes away (from the [guide](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/haskell))
``` elisp
(setq-default dotspacemacs-configuration-layers
  '((haskell :variables haskell-enable-ghc-mod-support nil)))
```

**Comment by d12frosted** [comment]
@kRITZCREEK `ghc-mod` is enabled by default :)

**Comment by d12frosted** [comment]
> I think ghc-mod is probably the culprit. I had a similar issue with aeson that resolved itself when I updated the stack.yaml to use the latest LTS and then reinstalling ghc-mod.

Totally agree. Had similar problem and reinstalling `ghc-mod` helped. The problem is that `ghc-mod` works only with **one** version of `ghc`. So for example, when you build `ghc-mod` with lts version that works with `ghc-8` and then start using lts that works with `ghc-10` - `ghc-mod` will be broken - you have to reinstall it. Just call `stack install ghc-mod`. 

But you can also disable `ghc-mod`. This solves some issues and removes some constraints on workflow, but it comes at the cost of bad or zero completion.

**Comment by mckeankylej** [comment]
Reinstalling stack did the trick!

**Comment by d12frosted** [comment]
Glad to hear :)

În data de joi, 7 aprilie 2016, mckeankylej <notifications@github.com> a
scris:

> Reinstalling stack did the trick!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/5674#issuecomment-207061197>
>


-- 
~ d12frosted

**Comment by mckeankylej** [comment]
Not sure if I should open a new issue but my spacemacs is complaing about the same thing in a different form. Now when I go to a file I get the following error: 

Suspicious state from syntax checker haskell-stack-ghc: Checker haskell-stack-ghc returned non-zero exit code 1, but no errors from output: <command line>: cannot satisfy -package criterion
 (use -v for more information)

**Comment by kRITZCREEK** [comment]
@mckeankylej criterion is a benchmarking framework you might need to run `stack bench` in your project root once.

**Comment by mckeankylej** [comment]
Yep ran `stack test` and it worked. I wish there were more resources or better errors because I wish I could debug this myself.

**Comment by d12frosted** [comment]
@mckeankylej `ghc-mod`, `haskell-mode` and `stack` projects are places where you can find more info and help about some weirdos with haskell tooling. Also, joining #haskell on IRC is a good idea :)
