### ISSUE TITLE
Feature request: org-mode source block editor to use major mode of language

### ISSUE THREAD

**Issue by mathpunk** [syl20bnr/spacemacs#5676]
Suppose you are using org-mode source blocks. From inside a block, you can hit `C-c '` to open up a buffer containing the text from that block, with syntax highlighting active for the language you are using. However, while I expected that `SPC m` would open up major mode options for that language, like going to a repl and so forth, that is not the case -- `SPC m` is undefined.

**Comment by StreakyCobra** [comment]
Can you please update your issue with the [following template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? We need more information such as your system description and some reproduction steps in order to help you. Thanks!

**Comment by mathpunk** [comment]
This seems to be user error! I had not configured my languages for org-babel properly.
