### ISSUE TITLE
About smooth scrolling for wrapped lines

### ISSUE THREAD

**Issue by eric-meng** [syl20bnr/spacemacs#5678]
The smooth-scrolling.el help one can scroll by single line in one time, which is a big improvement for the editorial performance.

But it still has some problem when scrolling over a very long wrapped line, e.g. a paragraph in LaTeX-mode

So I think maybe it will be better to configure that spacemacs can scroll by every visual line instead of wrapped line.

BTW, there are two LaTeX-modes from `M-x`, the official name of LaTeX is just `LaTeX` but not `latex` or `Latex`.... so hope this little bug and all the item `latex` can be fixed for professionalism.

**Comment by syl20bnr** [comment]
You can add `(spacemacs/toggle-visual-line-navigation-on)` to your `dotspacemacs/user-config` function.

**Comment by syl20bnr** [comment]
Also `SPC h t` brings a helm buffer with all the Spacemacs toggles.

**Comment by eric-meng** [comment]
Thanks!
