### ISSUE TITLE
CONTRIBUTE link broken on http://spacemacs.org

### ISSUE THREAD

**Issue by yatesco** [syl20bnr/spacemacs#5680]
Steps:
 - go to http://spacemacs.org
 - click on 'Contribute'
 - Github returns 404 for http://spacemacs.org/doc/CONTRIBUTE.html

**Comment by NJBS** [comment]
This has been reported on the site's repo [here](https://github.com/syl20bnr/spacemacs.org/issues/6).

**Comment by yatesco** [comment]
Ah - apologies, I didn't realise there was a separate repo for the site.
