### ISSUE TITLE
Add `cider-test-run-project-tests` in Clojure layer

### ISSUE THREAD

**Issue by yatesco** [syl20bnr/spacemacs#5681]
First - many thanks for spacemacs and the Clojure layer! 

Would it be possible to add a new keybinding for `cider-test-run-project-tests` bound to `SPC m t p` for example?

Thanks!
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: master (rev. cf8563b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp osx dash
                 (clojure :variables clojure-align-forms-automatically t cljr-favor-prefix-notation nil)
                 dash org themes-megapack git javascript markdown
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control
                 (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu/mu4e"))
```

**Comment by sdwolfz** [comment]
This looks like an old issue that was supposed to be closed a long time ago.
