### ISSUE TITLE
Neotree per frame

### ISSUE THREAD

**Issue by cviebig** [syl20bnr/spacemacs#5682]
Hello.

I usually open multiple frames with one project each. For each project/frame I would like to have one `neotree` buffer. Unfortunately it seems that there can only exist one `neotree` per Emacs instance which means that opening it in one frame will close the one in the other frame. Do you see any reason in spacemacs for this behauvior? I couldn't find any information on that in general.

Thank you in advance!

Best regards
christoph

**Comment by bmag** [comment]
According to https://github.com/jaypei/emacs-neotree/issues/57, Neotree doesn't support this feature.

Maybe hooking an update of Neotree's buffer into various places<sup>1</sup> can serve as an ad-hoc solution. I'm thinking of using the single Neotree buffer in all relevant frames/layouts/workspaces, but have its contents update to the current frame/layout/workspace automatically. Still isn't as good as proper multiple buffer support, though.

If you only want projectile+neotree synchronization, you can try one of these, and maybe make a PR if any of them seems to work well.
```elisp
;; option 1
(add-hook 'projectile-after-switch-project-hook 'neotree-projectile-action)
;; option 2
(setq projectile-switch-project-action 'neotree-projectile-action)
```

<sup>1</sup> various places: frame switch, layout (perspective) switch, workspace (eyebrowse) switch, project switch, ...

**Comment by cviebig** [comment]
Hi @bmag, thank you for looking into this. Unfortunately I did not find that issue. My work around currently is to run multiple instances of Emacs, one per project, each one maintaining one frame and it's neotree buffer.

**Comment by howdoicomputer** [comment]
Oh man, I'm super interested in this and almost opened a duplicate bug report. I'm going to try out those hooks.

**Comment by howdoicomputer** [comment]
```
;; put this into your emacs dotfile
(setq projectile-switch-project-action 'neotree-projectile-action)

;; then
C-c p p <select project> RET
```

That works for me. I'm now able to bounce around projects and use neotree.
