### ISSUE TITLE
SPC f e h only works once

### ISSUE THREAD

**Issue by legendre6891** [syl20bnr/spacemacs#569]
The binding `SPC f e h` only works once. Once it is used, the combination `SPC f * *` is dead, for any keys `*`.

**Comment by syl20bnr** [comment]
I cannot reproduce it, do you have several private layers ? Be sure nothing overrides `SPC f` in those layers.

**Comment by mosic** [comment]
I reproduced this with a clean install of spacemacs, no `.emacs` or `.spacemacs` present, on Ubuntu 14.04 running GNU Emacs 24.4.1.
