### ISSUE TITLE
HOWTOs.org link broken at the end of quick start

### ISSUE THREAD

**Issue by gilch** [syl20bnr/spacemacs#5690]
See the [quick start](http://spacemacs.org/doc/QUICK_START.html#orgheadline12), and try to follow the link under the last header. I get a 404.

**Comment by StreakyCobra** [comment]
This has already been fixed on develop: http://develop.spacemacs.org/doc/QUICK_START.html Duplicate of https://github.com/syl20bnr/spacemacs/issues/4853 :-)
