### ISSUE TITLE
contribute link broken on spacemacs homepage

### ISSUE THREAD

**Issue by gilch** [syl20bnr/spacemacs#5691]
See http://spacemacs.org

There are links near the bottom of the first screen

quick start • documentation • layers list • layers tutorial • conventions • contribute • vim users

But I get a 404 on the contribute link. Broken links on the homepage make us look bad.

**Comment by NJBS** [comment]
Duplicate https://github.com/syl20bnr/spacemacs/issues/5680

**Comment by syl20bnr** [comment]
This is fixed in develop branch of the repo.

**Comment by asmyers** [comment]
The http://spacemacs.org/doc/HOWTOs.html on http://spacemacs.org/doc/QUICK_START.html is also broken.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs.org/issues/6
