### ISSUE TITLE
Inconsistent projectile bindings

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#5692]
It's inconsistent how some projectile/project bindings fall under `SPC p` and some don't.

For example, find file in project is `SPC p f` while search-project is `SPC s p`.  We should either consistently put all project actions under `SPC <key> p` or `SPC p <key>`.  I think the latter is more reasonable.

In particular, `SPC p s` switch-project should be search-project-auto (currently `SPC s p`).  switch-project is already available as `SPC p p`.

**Comment by syl20bnr** [comment]
This is on purpose, `SPC s` then scope. This has been done like this to have all search bindings consistent, `SPC f s` being not free.

**Comment by syl20bnr** [comment]
More info in the documentation: http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline141

**Comment by darkfeline** [comment]
I agree that `SPC s p` binding is sensible, but is there a reason not to put it in `SPC p s`?  For example, `projectile-find-file` is on `SPC p f` and not on `SPC f p`.

**Comment by syl20bnr** [comment]
If we put `SPC p s` then we have an inconsistency with `SPC f s` which is a key binding we cannot move.
I would go the other way around then, `SPC f p` is free :-)

**Comment by syl20bnr** [comment]
Actually I would keep `SPC f p` for other things, there are few keys left, let's keep them and accept the small inconsistencies, `SPC f p` could be for `file print`.

Thinking about `SPC f f` and `SPC f p`, there is another mnemonic behind this, the equivalent of `SPC f f` for projects is not really `SPC p f` it is more `SPC p p` and `SPC b b` for `switch`. `SPC f f` is a special case where switching to a file is the same thing to open/find it. Sometimes we should not pay attention about the name of things but more about what they do. Another example is to no use `h` key for `helm` commands etc...

**Comment by darkfeline** [comment]
My main concern is mental consistency.  If I'm the only one experiencing then it's no problem but if others are too then it should be fixed.

My mental process is "do <foo> in project" -> `SPC p <foo>`.  So find file -> `SPC p f`, shell command -> `SPC p !`, but search and all of a sudden `SPC s p`.  It's like if in Vim delete word is `dw` and yank word is `wy`.

**Comment by syl20bnr** [comment]
Indeed but we cannot achieve consistency with `SPC p s` because `SPC f s` is not changeable, `SPC p s` was the first thing I tried and moved `SPC f s` to `SPC f w` and it was not very well received. At least `SPC s` + scope is consistent.

You can also use `SPC /` and `SPC *` to search in project.

**Comment by d12frosted** [comment]
:+1: for `SPC /` and `SPC *` - great key bindings :smile:

~ d12frosted

**Comment by darkfeline** [comment]
So even with Space magic we don't have enough keys to go around.  Fair enough, I'll close this then.
