### ISSUE TITLE
Issue related to upgraded swiper

### ISSUE THREAD

**Issue by mkomitee** [syl20bnr/spacemacs#5693]
I'm running on `develop` and just updated my packages. It brought in (among other things) `swiper-20160404.829` Which causes the warning on startup:

    Error (use-package): ivy :config: Symbol's value as variable is void: hydra-ivy

If I roll back that one package to `swiper-20160331.2301`, the warning goes away. I haven't experienced any ill-effects from this, yet.

**Comment by al3xandru** [comment]
I ran into the same issue and was pointed to this. Anyways before that I trashed elpa, restarted, and I haven't seen the error since. I do see `swiper-20160405.602` being the new version downloaded.

**Comment by mkomitee** [comment]
Trashing elpa worked for me. This is good to close.

**Comment by kRITZCREEK** [comment]
@mkomitee It's your issue you can just close it yourself

**Comment by StreakyCobra** [comment]
Closing as proposed.
