### ISSUE TITLE
Helm-Dash in Dash package can't be configured according to documentation

### ISSUE THREAD

**Issue by jbmorgado** [syl20bnr/spacemacs#5694]
#### Description
Helm-Dash in Dash package is not following the documentation of the package and ignores the `dash/helm-dash-docset-newpath` variable.

#### Reproduction guide
- Set the `dash/helm-dash-docset-newpath` variable in `.spacemacs`, either in the `dotspacemacs-configuration-layers` with `(dash :variables dash/helm-dash-docset-newpath "~/docsetpath")`
- Or in `dotspacemacs/user-init` with `(setq  dash/helm-dash-docset-newpath "~/docsetpath")`
- Set the path for both an empty directory or for the Dash DocSet path in the user Library path (error message is always the same).
- Start Emacs
- SPC d h

*Observed behaviour:*
Get error: `Error (use-package): helm-dash :config: Opening directory: not a directory, /Users/me/repos/work/test.zip`
Somehow it tries to open some zip file in the directory I'm working.

*Expected behaviour:*
To open the relevant Dash documentation inside Emacs.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.14
- Spacemacs branch: master (rev. 3aff734)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-complete-with-key-sequence-delay 0.8 auto-completion-enable-help-tooltip t auto-completion-private-snippets-directory "~/Dropbox/Apps/Yasnippet")
 dash emacs-lisp ess extra-langs
 (git :variables magit-repository-directories
      '("~/repos/"))
 html ipython-notebook
 (latex :variables latex-build-command "LatexMk")
 markdown
 (org :variables org-enable-github-support t)
 osx
 (python :variables python-enable-yapf-format-on-save t)
 shell
 (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
 (syntax-checking :variables syntax-checking-enable-tooltips nil syntax-checking-enable-by-default nil)
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t))
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by brenogil** [comment]
Same here. 
Have replicated this issue in both Debian (emacs24) and osx  (emacs25).

**Comment by kidd** [comment]
Helm-dash coauthor/maintainer here.  I don't use spacemacs, but if you think I can help somehow, ping me and I'll try to give it a try.

**Comment by morgado-jb** [comment]
Hi kidd, perhaps it's better to ping the package manager, helm functionality is totally broken it only works by installing the docsets to the working folder where you are using a specific emacs session from.

I tried to change both the `dash/helm-dash-docset-newpath ` and `helm-dash-docsets-path` in a number of different ways and it still doesn't work properly. Very annoying.

**Comment by syl20bnr** [comment]
Should be fixed on develop.

**Comment by istinspring** [comment]
+1 Same issue.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by gttiankai** [comment]
+1 Same issue.

**Comment by d12frosted** [comment]
@gttiankai what do you mean? Is it still an issue for you? If so, could you please paste output of `SPS h d s`?

**Comment by eullerborges** [comment]
Same problem here, still.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 semantic better-defaults themes-megapack osx dash
 (dash :variables dash/helm-dash-docset-newpath "~/Library/ApplicationSupport/Dash/DocSets/")
 emacs-lisp git markdown gtags cscope org syntax-checking
 (c-c++ :variables c-c++-enable-clang-support t)
 gtags latex python games spotify shell
 (ranger :variables ranger-show-preview t)
 pandoc)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by syl20bnr** [comment]
@eullerborges can you open a new issue ? This one is old and has been closed already. Thank you!

**Comment by eullerborges** [comment]
@syl20bnr Sorry about that, I was following d12frosted's answer to @gttiankai.
