### ISSUE TITLE
No auto-fill in Org

### ISSUE THREAD

**Issue by bb010g** [syl20bnr/spacemacs#5697]
#### Description
Org mode does not work with the auto-fill minor mode.

#### Reproduction guide
- Start Emacs
- Open an Org buffer
- Enable auto-fill
- Hit space after your fill column has been reached

*Observed behaviour:*
An error appears stating "An element cannot be parsed line 10". No wrapping occurs.

*Expected behaviour:*
The line would wrap, as it does in text mode.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: master (rev. cf8563b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults clojure emacs-lisp emoji games git github java lua markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 version-control xkcd)
```

**Comment by StreakyCobra** [comment]
Do you have an example file? Because I didn't managed to reproduce this.

**Comment by TheBB** [comment]
I'm not able to repro on my work computer, but I was able to repro earlier at home. So it may have to do with recent changes in org, maybe?

**Comment by StreakyCobra** [comment]
Packages up-to-date here, still can't reproduce :-/

**Comment by TheBB** [comment]
Yeah, I also can't reproduce any more.

@bb010g update everything?

**Comment by jb55** [comment]
I just cleaned my packages, updated to 3274e7d518163f4e83dcb88b821485c7309d9bde, and reproduced this.

**Comment by jb55** [comment]
I also get this in `*Messages*` when I type over the fill column:

`user-error: An element cannot be parsed line 21`

**Comment by jb55** [comment]
Updating to develop fixed it...

**Comment by StreakyCobra** [comment]
@bb010g Can you confirm about `develop`?

**Comment by bb010g** [comment]
Confirmed fixed in `develop`.
