### ISSUE TITLE
the start option "--insecure" work only first time behind  a cntlm proxy on Windows

### ISSUE THREAD

**Issue by danyuhao** [syl20bnr/spacemacs#5698]
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description
The command "emacs --insecure" work only when emacs start first time
And when I restart  emacs ,  it install new packages and faild for bad connect to https://melpa.org.

#### Reproduction guide
- Start Emacs
  1. Setup cntlm proxy as http_proxy/https_proxy for cygwin in ~/.bash_rc
  2. Download spacemacs by "git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d"  
  3. Start emacs by "emacs --insecure", and emacs start download packages from http://melpa.org and doing config for spacemacs.
  4. Quit emacs arfter spacemacs configration finished.
  5. restart emacs after something happened.(I can't remember clear).  For example: add layer python for spacemacs? or after spacemacs updated?
- REPRODUCTION STEPS
  I delete the whole .emacs.d, and I re clone spacemacs, then run "emacs --insecure", this problem still stay there and cannot be fixed
*Observed behaviour:*
  It start connect to "https://melpa.org" for updating packages, and faild (May be for proxy certifates??)
  And after googled for this problem ,  i found the issue 4257 is helpful (https://github.com/syl20bnr/spacemacs/issues/4257)
  And then I setted dotspacemacs-elpa-https to nil in mine ~/.spacemacs , restart emacs , problem was fixed.
*Expected behaviour:*
 The problem should be fixed when I re clone the spacemacs. So I think the ~/.spacemacs should be move into dir ~/.emac.d

#### System Info
- OS: cygwin
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: master (rev. cf8563b)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by Ssawa** [comment]
I actually experienced this as well on my Windows box. I believe the root cause is that --insecure is not actually honored if "dotspacemacs-elpa-https" is set to "t" (despite what it says in the documentation). If you go into your ~/.spacemacs file and change dotspacemacs-elpa-https to "f" it should use port 80. I've not had the chance to test if this is also the case with OSX/Linux or if its just a windows bug.

**Comment by syl20bnr** [comment]
I encountered it recently as well. Will be fix soon.

**Comment by syl20bnr** [comment]
Removing hotfix tag, for now use the work around of setting `dotspacemacs-elpa-https` to `nil` to always run in `--insecure` mode.

**Comment by c101088** [comment]
I meet this bug again. When i use emacs --insecure for the first time to open spacemacs, everything is fine ,the package would be installed well. However, i could not install  other packages any more after that .I try download the spacemacs-master and set dotspacemacs-elpa-https to nil before use emacs ,it could not work as the emacs --insecure do .

**Comment by c101088** [comment]
I also try to delete all the contents in elpa and restart the emacs , the errors are still be there.About setting the dotspacemacs-elpa-https to nil , i change the "core-dotspacemacs.el"  and ".spacemacs"  two files.

**Comment by m-sameer** [comment]
I encountered this problem. I reinstalled every single thing I can, but the problem doesn't seem to go.

**Comment by c101088** [comment]
My operation system is windows 10. I solve my problem by  installing the dependent packages of the emacs ,which name may like "emacs-25-i686-deps.zip".You just need to copy the all the thing in the dependent packages to the path of emacs .

**Comment by mimoralea** [comment]
You have to change the variable `dotspacemacs-elpa-https` in two files:

- .emacs.d/core/core-dotspacemacs.el
- .spacemacs
