### ISSUE TITLE
Spacemacs may not be able to operate properly

### ISSUE THREAD

**Issue by DuanTzXavier** [syl20bnr/spacemacs#5701]
I'm a new emacser .

when i have installed emacs in my ubuntu 14.04, I found this configuration of emacs style.

But After git and start up install packages , I occured an error:
 
`Spacemacs may not be able to operate properly`

and here are some log:

```
Error (use-package): helm pre-:config hook: Symbol's function definition is void: helm-flx-mode
Error (use-package): helm pre-:config hook: Symbol's function definition is void: helm-flx-mode

```
How can I fix this?

btw my emacs version is 24.3.1

**Comment by TheBB** [comment]
> btw my emacs version is 24.3.1

That's your problem. Upgrade to a newer Emacs version or exclude the `helm-flx` package (but anyway you will run into problems with other packages eventually.)

**Comment by DuanTzXavier** [comment]
Thanks
I change my emacs to 24.5 ,and error gone

**Comment by everson** [comment]
I am having this issue with Emacs 25.1 on OSX. The frustating part is that it only tells that there is one error, but I cannot see what error is.

**Comment by gzmask** [comment]
same thing on 25.1, one red line of this, not telling any details.

**Comment by everson** [comment]
Just a follow up. After carefully looking at the Messages buffer, I found the error message among the verbose logs. It was indeed a syntax mistake on my end.

**Comment by Fzekiqi** [comment]
Anyone who fixed the problem?

**Comment by duianto** [comment]
@Fzekiqi What's your Emacs version?
The minimum supported on the `master` branch is 24.4 (25.1 on `develop`), the latest Emacs version is 26.2.
