### ISSUE TITLE
spacemacs initialization failure from basic docker file

### ISSUE THREAD

**Issue by alxempirical** [syl20bnr/spacemacs#5707]
Running the following Dockerfile results in emacs reporting `gnutls.c: [0] (Emacs) fatal error: The TLS connection was non-properly terminated.`.  Much of the initialization process still goes through, but this results in the end with `An error occurred while loading "/root/.emacs.d/init.el": Wrong type argument: stringp, nil` and no spacemacs goodness.  Initializing emacs with `emacs --debug-init` results in an attempt to enter the debugger, but an `args out of range` error, and no backtrace.

The same thing happens with ubuntu 16.04.

Perhaps the issue is that it's initializing in a non-graphical environment?  (I'm installing `emacs-nox`, but I got the same issues installing `emacs`.)

```dockerfile
FROM ubuntu:15.10
WORKDIR /root
RUN apt-get update && apt-get upgrade -y && apt-get install -y emacs-nox git
RUN git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
CMD emacs
```

**Comment by alxempirical** [comment]
BTW, in case it's useful there's an image here:

```bash
docker run -it alxempirical/spacemacs-failure
```

**Comment by StreakyCobra** [comment]
Try to [set the `SHELL` variable](https://github.com/syl20bnr/spacemacs/issues/3652#issuecomment-180946962).

**Comment by alxempirical** [comment]
Thanks... that fixed this problem.  Any reason not to put something like this in `init.el`?

```elisp
  (if (not (getenv "SHELL"))
      (throw 'RuntimeError "Your SHELL environment is not set.  Weird things happen when that's the case."))
```

My next problems are getting the install to happen automatically in `emacs -batch` mode... for some reason `package` can't hit the repositories; and that `emacs` starts with an unreadable green background.  I'll make separate issues for those, though.

**Comment by StreakyCobra** [comment]
>  Any reason not to put something like this in init.el?

PR welcome :-)

**Comment by StreakyCobra** [comment]
BTW is you problem is fixed you should consider closing the issue :-)
