### ISSUE TITLE
Restclient-mode not starting: Cannot open load file: no such file or directory, helm-restclient

### ISSUE THREAD

**Issue by LeartS** [syl20bnr/spacemacs#5713]
#### Description
restclient-mode fails to start with error message: `Cannot open load file: no such file or directory, helm-restclient
`

#### Reproduction guide
- Start Emacs
- Open a new buffer (`SPC : spacemacs/new-emtpy-buffer`)
- Try to activate restclient-mode (`SPC : restclient-mode`)

*Observed behaviour:*
Activation fails with `Cannot open load file: no such file or directory, helm-restclient`

*Expected behaviour:*
restclient-mode is activated in the buffer

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: master (rev. cf8563b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory nil)
 better-defaults clojure csv emacs-lisp erlang git html markdown python restclient semantic spotify
 (syntax-checking :variables syntax-checking-enable-tooltips t)
 themes-megapack vinegar)
```

**Comment by StreakyCobra** [comment]
I was able to reproduce this, but updating packages seems to fix it. :warning: Don't update your packages now, otherwise it may break Spacemacs: https://github.com/syl20bnr/spacemacs/issues/5714.

**Comment by LeartS** [comment]
I've just updated the packages and restclient mode now works. Thanks! :+1:
