### ISSUE TITLE
hydra-20160407.319 broke Spacemacs

### ISSUE THREAD

**Issue by joehillen** [syl20bnr/spacemacs#5714]
I updated packages and was greeted with this:

![](https://files.gitter.im/syl20bnr/spacemacs/r2NT/blob)

(notice the line count in the Warnings buffer)

After manually rolling back I found that hydra was the issue.

Rolling back to `hydra-20160404.222` fixed it for me.

**Comment by StreakyCobra** [comment]
:+1: Thanks, you just saved me some debugging time to understand what was the problematic package.

**Comment by e-matteson** [comment]
I'm trying to reinstall spacemacs with an empty dotspacemacs, and it hangs with 100% cpu everytime before it finishes installing packages. Is this the same issue?

**Comment by synic** [comment]
@e-matteson that is happening to me too.

**Comment by joehillen** [comment]
Paging @abo-abo

**Comment by bixuanzju** [comment]
@StreakyCobra my Emacs freezes, how to rollback hydra?

**Comment by StreakyCobra** [comment]
First :warning:  DO NOT DELETE `.emacs.d` :warning: 

Then:

1. Remove `.emacs.d/elpa/hydra-…` (version number may differ here)
2. Copy recursively `.emacs.d/.cache/.rollback/…/hydra-20160404.222` back to `.emacs.d/elpa/`

For me it was:

```bash
rm ~/.emacs.d/elpa/hydra-20160407.319
cp -r ~/.emacs.d/.cache/.rollback/16-04-07_16.43.15/hydra-20160404.222 ~/.emacs.d/elpa
```

But it will probably differ as not all people will have the same old version, and the rollback will not have been done at the same time.

**Comment by joehillen** [comment]
@bixuanzju For me it was:

```
rm -rf ~/.emacs.d/elpa/hydra-20160407.319
cp -r ~/.emacs.d/.cache/.rollback/16-04-07_06.51.06/hydra-20160404.222/ ~/.emacs.d/elpa/
```
Your rollback dir will be different.

**Comment by synic** [comment]
Btw, when emacs is freezing, you can move forward by pressing `C-g` a bunch of times.

**Comment by StreakyCobra** [comment]
Is anyone encountering this on the `master` branch?

**Comment by JAremko** [comment]
https://hub.docker.com/r/jare/spacemacs/builds/bxbxcqjyas3kw2mr8bixpej/ Mother of GOD :scre

**Comment by abo-abo** [comment]
This seems to evaluate fine for me:

    (defhydra hydra-test ()
        "
    _PC_: foobar
    "
        ("PC" forward-char))
        
As the original screenshot shows, the worst thing that can happen is that the failed `defhydra` becomes a no-op.  Theoretically, a no-op instead of a hydra shouldn't be a huge deal. Anyway, test with the current MELPA version and report the problematic hydra to me.

**Comment by e-matteson** [comment]
@StreakyCobra `master` seems ok.
@JAremko trying to load that page killed firefox...

**Comment by joehillen** [comment]
> @JAremko trying to load that page killed firefox...

@e-matteson same
@JAremko please remove your comment

**Comment by joehillen** [comment]
@abo-abo I'm confused. Are you saying this is fixed? You haven't pushed any newer changes than the one that is broken.

**Comment by abo-abo** [comment]
In theory, `hydra` can't break too much. It should work just as `use-package` and generate a no-op instead of raising an error. If that's not the case, the bug should be reported.

From the screenshot, I see a `defhydra` failing due to a `_PC_` key, but testing with the snippet I quoted above, the master seems to work fine.  Also the Travis CI tests for hydra are passing.

Things would move along much faster if someone just quotes me the code of the failing `defhydra`.

**Comment by tuxayo** [comment]
>  trying to load that page killed firefox...

It almost did for me, it's a 130MB 1.7million lines HTML page which contains an absurd quantity of `Warning (emacs): Unrecognized key: _r_` as it show a build log which triggered the current bug.

**Comment by joehillen** [comment]
I can't find `_PC_` anywhere in the spacemacs codebase or any of the packages. Could it be `_SPC_`?

**Comment by abo-abo** [comment]
Nope, this also works in master:

    (defhydra hydra-test ()
        "
    _SPC_: foobar
    "
        ("SPC" forward-char))

**Comment by TheBB** [comment]
We have a macro that wraps `defhydra` so this is not necessarily so trivial. I'm trying to track it down now, though I'm eating at the same time. For example I can load Spacemacs fine without any additional layers.

**Comment by TheBB** [comment]
Looks like the org-agenda transient state is at fault. Let me see if I can get an expanded and simplified case.

**Comment by syl20bnr** [comment]
Was diner time for me too. Pretty sure that's a mistake on top of Hydra since we wrap it and @abo-abo showed that it is OK on his side. Also the master branch does not feature Hydra yet so we are safe for new users using the stable branch but this kind of scenario can (and has) happen in the past on master, this is still a weakness of Spacemacs, for now we have only the community to back this and try to fix it quickly.

I'm looking into this bug as well.

**Comment by syl20bnr** [comment]
The only _SPC_ is in the org-agenda transient state.

**Comment by TheBB** [comment]
Yep, it loads fine if I remove the SPC binding from that hydra.

**Comment by syl20bnr** [comment]
Also as mentioned `C-g` stops the infinite loop.

**Comment by syl20bnr** [comment]
Since @abo-abo showed that `_SPC_` is fine then it has to do with the color highlighting with `[_SPC_]`.

**Comment by syl20bnr** [comment]
Looks like the bug could have been introduced by this commit: https://github.com/abo-abo/hydra/commit/f01f4a46f227961cd2a1571a45a174cfcfbfa81c

**Comment by joehillen** [comment]
Fix found https://github.com/abo-abo/hydra/pull/188

**Comment by syl20bnr** [comment]
Great :+1: 
But it is not related to `[_SPC_]` but more about the whole docstring because I can replace `[_SPC_]` by `[_t_]` and still have the bug with `unrecognized key _t_`.

Here is the whole dosctring for reference:

```
      "
Headline^^            Visit entry^^               Filter^^                    Date^^               Toggle mode^^        View^^             Clock^^        Other^^
--------^^---------   -----------^^------------   ------^^-----------------   ----^^-------------  -----------^^------  ----^^---------    -----^^------  -----^^-----------
[_ht_] set status     [_t_] in other window       [_ft_] by tag               [_ds_] schedule      [_tf_] follow        [_vd_] day         [_ci_] in      [_gr_] reload
[_hk_] kill           [_TAB_] & go to location    [_fr_] refine by tag        [_dd_] set deadline  [_tl_] log           [_vw_] week        [_co_] out     [_._]  go to today
[_hr_] refile         [_RET_] & del other windows [_fc_] by category          [_dt_] timestamp     [_ta_] archive       [_vt_] fortnight   [_ck_] cancel  [_gd_] go to date
[_hA_] archive        [_o_]   link                [_fh_] by top headline      [_+_]  do later      [_tr_] clock report  [_vm_] month       [_cj_] jump    ^^
[_hT_] set tags       ^^                          [_fx_] by regexp            [_-_]  do earlier    [_td_] diaries       [_vy_] year        ^^             ^^
[_hp_] set priority   ^^                          [_fd_] delete all filters   ^^                   ^^                   [_vn_] next span   ^^             ^^
^^                    ^^                          ^^                          ^^                   ^^                   [_vp_] prev span   ^^             ^^
^^                    ^^                          ^^                          ^^                   ^^                   [_vr_] reset       ^^             ^^
[_q_] quit
"
```

**Comment by TheBB** [comment]
Indeed. I managed to create a small reproducing example:

     (defhydra test ()
        "_SPC_"
        ("SPC" org-agenda-show-and-scroll-up))

This reliably reproduced the bug on `make run` from hydra master. It's very similar to the one that @abo-abo claimed worked fine, and in fact that one also reproduces the bug when I try it.

**Comment by syl20bnr** [comment]
Nice find :100:

**Comment by TheBB** [comment]
Since this appears after all to be a hydra bug I've reported upstream to https://github.com/abo-abo/hydra/issues/189.

**Comment by abo-abo** [comment]
Thanks, @syl20bnr. I could reproduce the issue. The docstring works fine for me with the current master.

**Comment by TheBB** [comment]
It's now fixed upstream. We can close this when it lands on MELPA.

**Comment by TheBB** [comment]
Thanks @abo-abo for the swift response!

**Comment by joehillen** [comment]
Fix is in MELPA

**Comment by robbyoconnor** [comment]
I can update now?

**Comment by joehillen** [comment]
@robbyoconnor Yup, g2g

**Comment by robbyoconnor** [comment]
confirm it works.
