### ISSUE TITLE
New startup info box code slows down startup time

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#5717]
I noticed this morning that spacemacs started slower than usual. After bisecting I found that 50515a826aabd48a8179f8614ec56b523a13fe87 is the first slow commit. It adds 5 seconds to my startup time and yasnippet tells me a lot about stuff it is discovering. 

Can somebody reproduce this?

**Comment by cpaulik** [comment]
I've just tested on my work machine and observe the same thing. 

Also here is my system info.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: develop (rev. ec9f6cf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip nil)
 chrome clojure colors custom_org_config django
 (elfeed :variables rmh-elfeed-org-files
         (list "~/Dropbox/org/feeds.org"))
 emacs-lisp emoji erc finance games
 (git :variables git-gutter-use-fringe t)
 github gnus graphviz html ipython-notebook javascript latex lua markdown my-mu4e my_python org org-ipython org-page pandoc spacemacs-layouts pdf-tools php
 (python :variables python-enable-yapf-format-on-save nil python-auto-set-local-pyenv-version 'on-project-switch python-test-runner 'pytest)
 ranger research-config ruby rust search-engine semantic
 (shell :variables shell-default-shell 'term shell-default-term-shell "/bin/zsh")
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking tmux vagrant
 (version-control :variables version-control-diff-tool 'diff-hl)
 yaml)
```

**Comment by StreakyCobra** [comment]
@cpaulik What metric do you use for checking the time needed? The `[xxx packages loaded in x.xxxs]` in the `*spacemacs*` buffer or manually?

I tried to start at 50515a826aabd48a8179f8614ec56b523a13fe87 and it gives me:

    [451 packages loaded in 5.335s]

I tried the same at the parent commit d60228219f840ef73a5830a60b2b01901a00cf2f:

    [451 packages loaded in 5.362s]

So it seems I don't have any performance regression. Looking at the computer's clock manually, both looks to take approximately the same time.

Maybe it is related to the enabled layers, your configurations. I don't have personal snippets, it's may be the cause…

**Comment by cpaulik** [comment]
@StreakyCobra Thanks for checking. I've used the time reported by spacemacs as a first indicator but it is definitely slower.

I don't see the difference with no layers activated, bisecting the layers led me down a path of tweaking my shell configuration which also made startup slower by about 100% because of the `exec-path-from-shell` calls. But I could not find one layer that was causing the difference. Removing my personal snippets also did not change anything.

Which layers did you have enabled when testing this?

**Comment by StreakyCobra** [comment]
Here is my config:

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: develop (rev. 0f7a6c7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 bb-git bb-latex bepo better-defaults c-c++ clojure colors command-log csv deft dockerfile
 (elfeed :variables rmh-elfeed-org-files
         (list "~/org/main.org"))
 encoding emacs-lisp emoji erc erlang ess evil-cleverparens extra-langs finance git github haskell html ipython-notebook java javascript
 (keyboard-layout :variables kl-layout 'bepo)
 latex markdown mu4e no-dots ocaml org pandoc plantuml python ranger restclient ruby rust scala semantic shell shell-scripts spacemacs-helm speed-reading
 (spell-checking :variables spell-checking-enable-auto-dictionary t)
 sql syntax-checking systemd themes-megapack theming typography
 (version-control :variables version-control-diff-tool 'diff-hl)
 vimscript yaml)
```

**Comment by cpaulik** [comment]
Well I've started my .spacemacs from a fresh template and now the difference is gone. It also loads three times as fast now and I have no idea why. Could be worse though :smile:
