### ISSUE TITLE
cmake-ide

### ISSUE THREAD

**Issue by skebanga** [syl20bnr/spacemacs#5718]
How similar to [`cmake-ide`](https://github.com/atilaneves/cmake-ide) is the spacemacs c++ layer?

Have you considered pulling it in?

**Comment by TheBB** [comment]
I haven't tried it but,

* rtags: no, but there's a [PR](https://github.com/syl20bnr/spacemacs/pull/2834) for it that is quite popular
* flycheck: yes
* company-clang: yes
* irony: no

There is no particular support for reading setup from CMake files directly. For big projects I use a [wrapper compiler](https://github.com/Rip-Rip/clang_complete/blob/master/bin/cc_args.py) that extracts the arguments it needs and adds then to a `.clang_complete` file which Spacemacs reads.

It would be interesting to use this package for reading CMake setup files but probably not for the overall integrated experience.

**Comment by skebanga** [comment]
I watched your c++ spacemacs YouTube video, and saw your use of cc_args.

Then I saw Atila's lightening talk which did it automatically, leading to this question.

It's only 15 mins long, much of which can be skipped, worth a quick watch!

https://www.youtube.com/watch?v=5FQwQ0QWBTU

**Comment by mssun** [comment]
If you are using cmake for building, it can generate compiler options by setting [CMAKE_EXPORT_COMPILE_COMMANDS](https://cmake.org/cmake/help/v3.5/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) on. The output file is `compile_commands.json`. YCM will read this file for completion by [setting the compilation database variable](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/.ycm_extra_conf.py#L99). I guess clang complete also supports the `compile_commands.json` file, but haven't tried it. I think it looks better than add a wrapper before compiler. It seems that [cmake-ide](https://github.com/atilaneves/cmake-ide/blob/master/cmake-ide.el#L163) is based on `compile_commands.json`.

**Comment by myrgy** [comment]
this issue could be close because #9432 has been merged

**Comment by Compro-Prasad** [comment]
Still open!!? Almost every other issue/PR referencing this issue has been closed @syl20bnr . Isn't this issue resolved?

**Comment by syl20bnr** [comment]
cmake-ide is now part for the cmake layer which has been extracted from
the c-c++ layer to make it lighter.

**Comment by LucaMarconato** [comment]
@syl20bnr I installed the latest version of Spacemacs from master and if I try to use the layer `cmake` I get an error saying that it is not available. 
How can I set it up? Do I need to "add another source for layers", like when one has to add MELPA if he wants packages that are not in ELPA?

**Comment by sdwolfz** [comment]
@LucaMarconato the `cmake` layer is only available on the `develop` branch right now: http://develop.spacemacs.org/layers/+tools/cmake/README.html.

**Comment by LucaMarconato** [comment]
Ah cool! Is it stable or should I just wait for the final release? :)

**Comment by sdwolfz** [comment]
Develop should be stable enough for day to day use.

**Comment by LucaMarconato** [comment]
@sdwolfz I installed but it does not seem to work out-of-the-box, should I also install `irony` and `company-irony`?

**Comment by sdwolfz** [comment]
Did you add the variable as well? `(cmake :variables cmake-enable-cmake-ide-support t)`

**Comment by LucaMarconato** [comment]
Yes, still not working. Anyway since I do not want go OT I will open another thread (not immediately, I want to experiment more with the configuration first). Thank you for the answers you have given me so far.
