### ISSUE TITLE
Running web-beautify-js when using react-layer causes snytax highlighting to be removed

### ISSUE THREAD

**Issue by qnm** [syl20bnr/spacemacs#5724]
#### Description

When editing a JSX file in spacemacs, when I beautify the file (spc-m-=), the syntax highlighting for the file is removed.
#### Reproduction guide
- Start Emacs
- Open JSX-format file
- Beautify file (spc-m-=)
- File is beautified

_Observed behaviour:_
Syntax highlighting is no longer shown

_Expected behaviour:_
Syntax highlighting should be shown
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: master (rev. cf8563b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp react)
```
#### Backtrace

No backtrace.

**Comment by cpaulik** [comment]
I've seen the same in other modes that use `web-beautify`, namely `.js` and `html`

**Comment by StreakyCobra** [comment]
Can somebody try to reproduce on a stock emacs to see if it is a Spacemacs bug or an upstream issue? `SPC q D` can be used to restart in stock emacs with just some packages enabled.

**Comment by cpaulik** [comment]
I just tried again. It works in `.js` but not in `.html` also when starting with SPC q D and only loading evil and helm.

**Comment by qnm** [comment]
I can confirm that the behaviour is correct when I beautify a React component with `.js` extension.

**Comment by BelfordZ** [comment]
confirmed issue

**Comment by zhewuzhou** [comment]
I have got the same issue, if you have pure js then everything is fine, but if you have jsx(including tags) then after web-beautify-js, syntax highlighting is gone

**Comment by aumana** [comment]
I can confirm that I have the same issue for files with .jsx extension, and tried with pure .js files in the same project and it doesn't happen.

**Comment by cyberxndr** [comment]
Same issue, jsx formatting causes syntax highlight loss.
