### ISSUE TITLE
Recent version of yasnippet breaks

### ISSUE THREAD

**Issue by TheBB** [syl20bnr/spacemacs#5736]
"Error in post-command hook (yas-global-mode-check-buffer): (void-function yas--load-pending-jits)"

Errors in post-command-hook are pretty serious, since this hook is fired almost all the time. For example, there is no way to use helm. This affects at least me and a couple of users on gitter.

I can't look into it now because I have a lot of work to do.

Please do not update your packages, or if you can't rollback you can exclude yasnippet.

**Comment by aroig** [comment]
I think https://github.com/capitaomorte/yasnippet/commit/18f7b1b9fe99339f1bb350779ec43e26e8df1c5c in yasnippet is the one to blame. Reverting the obvious change to `post-command-hook` doesn't seem to help though.

**Comment by syl20bnr** [comment]
Reported upstream in https://github.com/capitaomorte/yasnippet/issues/673

**Comment by ChasingLogic** [comment]
In the referenced yasnippet ticket it appears you have a work around? I currently can't use spacemacs at all :'(

**Comment by NJBS** [comment]
@ChasingLogic I'd recommend just excluding yasnippet until this issue is resolved. Add it to `dotspacemacs-excluded-packages` [like so](https://github.com/NJBS/dotfiles/blob/master/.spacemacs#L63). You might additionally need to delete the yasnippet package folder from `~/.emacs.d/elpa`.

**Comment by JAremko** [comment]
[My docker build is green again](https://hub.docker.com/r/jare/spacemacs/builds/). looks like the patch is out :+1:
