### ISSUE TITLE
Rebinding rules for evilified-state are not documented

### ISSUE THREAD

**Issue by mineo** [syl20bnr/spacemacs#5738]
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistributions/spacemacs-base/local/evil-evilified-state/evil-evilified-state.el#L32 says

```elisp
;; The shadowed original mode key bindings are automatically reassigned
;; following a set of rules:
```

However, that's the end of the comment, the rules are not listed anywhere.

EDIT: [@syl20bnr] updated broken link

**Comment by bmag** [comment]
Yeah, it's weird that the commentary says "here are the rules", but doesn't actually lists them.
For reference, the rules are documented [here](http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline50) and [here](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#evilified-modes), for anyone who wants to make a PR for this.
