### ISSUE TITLE
Disactivate orphan packages deletion by default

### ISSUE THREAD

**Issue by makhtardiouf** [syl20bnr/spacemacs#5757]
Hello,

I am surprised that the individual packages that i install are deleted at every start, e.g. wakatime, project-explorer...etc;  due to the var  "dotspacemacs-delete-orphan-packages".

Isn't it less troublesome NOT TO have to edit the .spacemacs file every time to indicate which package should be excluded ?

Even when I comment out the var " ;;dotspacemacs-delete-orphan-packages t "  it deletes my packages nonetheless...

**Comment by TheBB** [comment]
> Even when I comment out the var " ;;dotspacemacs-delete-orphan-packages t " it deletes my packages nonetheless... 

Well yes, because its default value is `t` this doesn't change anything. To disable this you should set it to `nil`.

**Comment by makhtardiouf** [comment]
ok get that now, thanks.
But ah, why deletion is the default...

**Comment by StreakyCobra** [comment]
You can reopen if you want it to be discussed. I personally don't care about this default, but @syl20bnr may have some reasons to have it like this?

**Comment by TheBB** [comment]
Installing packages with `dotspacemacs-additional-packages` instead of `M-x package-install` is great for having a (nearly) fully reproducible config.

**Comment by nixmaniack** [comment]
> for having a (nearly) fully reproducible config.

Most important part when debugging/reproducing issues. :+1:

**Comment by Cy6erlion** [comment]
I also don't think deletion of orphan packages should be default.

**Comment by LouisAsh** [comment]
Pardon me for the silly question, but where shoud `dotspacemacs-delete-orphan-packages` be found? It is not at all present in my .spacemacs file. If I should include `dotspacemacs-delete-orphan-packages nil` somewhere in the file, where is such place?

**Comment by duianto** [comment]
In the changelog for 0.200.0 (2016/10/02)
https://github.com/syl20bnr/spacemacs/blob/master/CHANGELOG.org#new-variables
it states that:
- New variable =dotspacemacs-install-packages= which replaces the variable
  =dotspacemacs-delete-orphan-packages=. This new variable defines the behavior
  of Spacemacs for installed packages.
  Possible values are =used-only=, =used-but-keep-unused= and =all=.
  - =used-only= installs only explicitly used packages and uninstall any
  unused packages as well as their unused dependencies.
  - =used-but-keep-unused= installs only the used packages but won't uninstall
  them if they become unused.
  - =all= installs *all* packages supported by Spacemacs and never uninstall
  them.
  Default value is =used-only=.
