### ISSUE TITLE
Add status bar icon for gtags?

### ISSUE THREAD

**Issue by qqldd** [syl20bnr/spacemacs#5760]
Now gtags layer has the "HelmGtags" text when enabled. This is a bit to long. Can we use Ⓖ and G to represent gtags mode?

**Comment by TheBB** [comment]
I don't think that would be very useful. Can't we just hide it instead?

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
