### ISSUE TITLE
Clojure layer / Cider obsolete functions need updating

### ISSUE THREAD

**Issue by hnry** [syl20bnr/spacemacs#5762]
Currently there is breakage using clojure layer

Related to https://github.com/clojure-emacs/cider-eval-sexp-fu/issues/2 which is pulled in by clojure layer, so that needs updating too

But also needs updating:
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/clojure/packages.el#L25

**Comment by hnry** [comment]
Whoops I see it's fixed in the develop branch
https://github.com/syl20bnr/spacemacs/commit/5f93dc364f3dfdb73d117e1a6dbed8035d10f442

**Comment by hnry** [comment]
Actually I'm going to keep it open until https://github.com/clojure-emacs/cider-eval-sexp-fu/issues/2 is updated? And the fix in develop branch and everything is released?

Right now clojure layer isn't too useable until all these are released :(

**Comment by robbyoconnor** [comment]
@hnry use `develop` and update frequently -- even if it's once a week

**Comment by StreakyCobra** [comment]
Yes this fix has probably to be hotfixed in master. Will mark, it as so.

**Comment by syl20bnr** [comment]
Backported in 0.105.19
