### ISSUE TITLE
Auto-completion in the Python layer

### ISSUE THREAD

**Issue by awecat** [syl20bnr/spacemacs#5765]
Hi everyone, 
I have recently started to learn how to use Spacemacs and it's great. But I am having one problem... I want to install the python layer, but for some reason, whenever try to I install it (by adding "python" to my dotspacemacs-configuration-layers), the auto-completion doesn't work, and I can't figure out why. There are a couple of warnings, but I don't know what they mean... 

Thanks!

**Comment by duerrp** [comment]
Did you install the auto-completion layer?

**Comment by awecat** [comment]
That fixed the autocomplete problem @duerrp! Thank you so much!!
