### ISSUE TITLE
auto yapf doesn't work

### ISSUE THREAD

**Issue by ntcong** [syl20bnr/spacemacs#5769]
Since the two commit related to lazy load yapf, auto yapf doesn't work anymore.

Manually yapf still works, and remove :defer t also solve the problem

**Comment by StreakyCobra** [comment]
Could you update  your  issue to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report)? It will help us to help you :-)

**Comment by nixmaniack** [comment]
This is happening because py-yapf is a local package without autoloads file. We added autoload for `py-yapf-buffer` using use-package but didn't add for `py-yapf-enable-on-save`. 

This should be fixed once #5535 is merged.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by hidaris** [comment]
auto yapf doesn't work for me..
version: Spacemacs v0.200, 
but when I run yapf-mode manually, It will work...

**Comment by ostrbor** [comment]
try this in user-config:

  (add-hook 'python-mode-hook
            (lambda ()
              (add-hook 'after-save-hook 'yapfify-buffer nil t)))

**Comment by hidaris** [comment]
@ostrbor yes, we can fix it in user-config, but I think maybe [7804](https://github.com/syl20bnr/spacemacs/pull/7804) is a better solution.
