### ISSUE TITLE
Auto-complete doesn't work

### ISSUE THREAD

**Issue by hiaw** [syl20bnr/spacemacs#5771]
#### Description
I can't enable auto-complete. 

#### Reproduction guide
- Start Emacs
- I'll open up a file in any language (Elixir, Emacs Elisp, Elm), 
- type M-x auto-complete and I'll get the error. 

```
Error in post-command-hook (evil-repeat-post-hook): (wrong-type-argument number-or-marker-p nil)
```

*Observed behaviour:*
Auto-complete doesn't work

*Expected behaviour:*
I expect auto-complete to work

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.18
- Spacemacs branch: master (rev. c8c4ff3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html javascript markdown elixir erlang python yaml elm shell-scripts emacs-lisp git
      (auto-completion :variables auto-completion-private-snippets-directory "~/.dotfiles/emacs/snippets" auto-completion-enable-help-tooltip t)
      syntax-checking spell-checking
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
      ranger wakatime org osx games xkcd speed-reading semantic colors restclient emoji dash
      (geolocation :variables geolocation-enable-weather-forecast t geolocation-enable-automatic-theme-changer nil))
```

#### Backtrace
```
auto-complete-mode is not enabled
Error in post-command-hook (evil-repeat-post-hook): (wrong-type-argument number-or-marker-p nil)
```

**Comment by TheBB** [comment]
> type M-x auto-complete

Fair enough that the error should probably not happen, but in spite of the name this has nothing to do with auto-completion in Spacemacs.

* If you have the layer for the language and the auto-completion layer, auto-completion will be enabled for that language. Period. No need to enable it yourself.
* If you *do* need to enable it yourself you should not use auto-complete but company, which is what Spacemacs uses in every single case.
* If you *do* need to enable auto-complete mode you should turn on `auto-complete-mode`. The command `auto-complete` is for actually initiating completion at the current location. (It's what corresponds to `company-complete` as opposed to `company-mode`.)

**Comment by hiaw** [comment]
ok. sorry i brought this up. I just couldn't figure it out myself. Thanks a lot for your help
