### ISSUE TITLE
fail to install on opensuse with emacs 24.5 - complain about info.el package

### ISSUE THREAD

**Issue by andrecbarros** [syl20bnr/spacemacs#5773]
Deserves an investigation but I am new to spacemacs (still learning).
There is an easy workaround: copying info.el to spacemacs/.emacs.d/core allows the installation to finish.

I really like spacemacs, thank you very much for it !

**Comment by StreakyCobra** [comment]
Where do you copy this `info.el` file from?

**Comment by andrecbarros** [comment]
From emacs default installation dir: /usr/share/emacs/24.5/lisp

**Comment by jm2dev** [comment]
Same issue on a fresh opensuse tumbleweed installation. I installed emacs-x11, cloned spacemacs repository to $HOME.emacs.d and when emacs is started spacemacs setup is ignored, like it didn't exist.

**Comment by vatrat** [comment]
Also have a fresh OpenSuSE Tumbleweed installation. Same issue with the Spacemacs config being ignored. The solution of deleting the file `.emacs` in the home directory worked.
