### ISSUE TITLE
Spacemacs-layouts - SPC f e R deletes created layouts

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#5775]
### Repro steps
- Start Emacs
- `SPC f e i`
- `SPC l 2 y foo RET`
- `SPC f e R`
- `SPC l`

### Observed behavior
There is only one layout (`1:Default`)

### Expected behavior
There should be two layout (`1:Default` and `2:foo`)

**Comment by nixmaniack** [comment]
First Bug report: #3875

**Comment by syl20bnr** [comment]
@nixmaniack thank you !

**Comment by StreakyCobra** [comment]
I hope you don't mind if I close this as it's a duplicate :-) We already have enough open issues :sweat:
