### ISSUE TITLE
Org mode hangs very sporadically when using mini-buffers

### ISSUE THREAD

**Issue by i-brute-force** [syl20bnr/spacemacs#5778]
#### Description

The freeze happens very infrequently (once in a few hours of use), but once in a while, when using mini-buffer such as changing todo types or capturing something, the emacs becomes completely irresponsive. `C-g` and `SPC q` are not registered, and the only way I can stop the process is through `pkill -SIGUSR2 Emacs` or shutting it off through Activity Monitor. 
#### Reproduction guide

Difficult to reproduce, but my workflow until the freeze is: 
- Start Emacs
- Use org-mode for a while using various org-mode commands such as `org-todo` or `org-capture`
- With an unidentifiable pattern, the emacs freeze

_Observed behaviour:_
Emacs freeze at a random interval when using some org commands

_Expected behaviour:_
Emacs should not freeze
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: master (rev. cf8563b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil)
 better-defaults emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control
 (latex :variables latex-enable-auto-fill t)
 themes-megapack python)
```
#### Backtrace

```
(funcall #[257 "\302\300\242\301\242\303\304$\210\305@A\"\207" [(624) (659) put-text-property fontified nil signal] 6 "\n\n(fn ERR)"] err)
  jit-lock-fontify-now(653 1153)
  jit-lock-function(653)
  redisplay_internal\ \(C\ function\)()
```

**Comment by i-brute-force** [comment]
Another freeze with the same backtrace

**Comment by syl20bnr** [comment]
What is your color theme ?

**Comment by i-brute-force** [comment]
@syl20bnr Are you talking about the `dotspacemacs-themes`? 

I am currently using `solarized-light`

**Comment by i-brute-force** [comment]
Another case of freeze.

Here is the full backtrace:
`
Debugger entered--beginning evaluation of function call form:
* (funcall #[257 "\302\300\242\301\242\303\304$\210\305@A\"\207" [(11601) (11697) put-text-property fontified nil signal] 6 "\n\n(fn ERR)"] err)
  jit-lock-fontify-now(11601 12101)
  jit-lock-function(11601)
  redisplay_internal\ \(C\ function\)()
`

**Comment by i-brute-force** [comment]
Freeze during refiling. [Here](http://imgur.com/tbU4zz3) is the backtrace

**Comment by i-brute-force** [comment]
I thought it might be my laptop's problem, so I started working on my desktop, but the problem persists. 

My desktop's System Info:

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: master (rev. cf8563b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil)
 better-defaults emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control
 (latex :variables latex-enable-auto-fill t)
 themes-megapack python)
```

#### Backtrace
```
Debugger entered--beginning evaluation of function call form:
* (funcall #[257 "\302\300\242\301\242\303\304$\210\305@A\"\207" [(18052) (18230) put-text-property fontified nil signal] 6 "\n\n(fn ERR)"] err)
  jit-lock-fontify-now(18053 18553)
  jit-lock-function(18053)
  redisplay_internal\ \(C\ function\)()
```

**Comment by i-brute-force** [comment]
Update. The problem seems to be that of flyspell. How do I turn off flyspell?


#### Backtrace
```
Debugger entered--entering a function:
* command-error-default-function((quit) "" nil)
  recursive-edit()
  debug(lambda)
* command-error-default-function((quit) "" nil)
  recursive-edit()
  debug(t)
* (byte-code "\301\302\303!\207" [quit-flag t eval (ignore nil)] 2)
  flyspell-post-command-hook()
  recursive-edit()
  debug(lambda)
* evil--jump-hook()
  recursive-edit()
  debug(lambda)
* evil--jump-hook()
  recursive-edit()
  debug(lambda)
* evil--jump-hook()
  recursive-edit()
  debug(lambda)
* evil--jump-hook()
  recursive-edit()
  debug(t)
* (byte-code "\301\302\303!\207" [quit-flag t eval (ignore nil)] 2)
  flyspell-post-command-hook()
  recursive-edit()
  debug(t)
* (funcall #[257 "\302\300\242\301\242\303\304$\210\305@A\"\207" [(692) (791) put-text-property fontified nil signal] 6 "\n\n(fn ERR)"] err)
  jit-lock-fontify-now(692 1192)
  jit-lock-function(692)
  redisplay_internal\ \(C\ function\)()
  redisplay()
  sit-for(3)
  flyspell-check-word-p()
  byte-code("\306	\306\307 \203\212\fb\210\310 \210)\311 \203#\310 \210p`\2029\306\211	9\2039	\312N\2039\313\314\315 \204k:\203k@@@A\316\"\203b\212b\210\310 \210)A*\2029\211+\207" [inhibit-quit this-command deactivate-mark command flyspell-pre-point flyspell-pre-pre-buffer nil flyspell-check-pre-word-p flyspell-word flyspell-check-word-p flyspell-delayed -1 _ input-pending-p flyspell-check-changed-word-p flyspell-pre-pre-point flyspell-word-cache-end flyspell-word-cache-result flyspell-changes stop start flyspell-previous-command] 4)
  flyspell-post-command-hook()
```

**Comment by StreakyCobra** [comment]
Probably something like:

```elisp
(add-hook 'org-mode-hook 'spacemacs/toggle-spelling-checking-off [append])
```

in `dotspacemacs/user-config`. Not tested though.

**Comment by bellyroun** [comment]
I've met similar issues where Emacs hangs in `redisplay_internal`. Updating emacs to the HEAD version seems to solve the issue.

**Comment by bwinkler** [comment]
I'm not sure that it's flyspell since I'm getting the same behavior (hanging) with it disabled and with a similar backtrace. I think that something is just triggering fontification (flyspell, scrolling, etc.) and that some function being used as a font locking rule not returning or otherwise misbehaving.

So, how do we figure what is going on here:
`(funcall #[257 "\302\300\242\301\242\303\304$\210\305@A\"\207" [(72443) (72639) put-text-property fontified nil signal] 6 "\n\n(fn ERR)"] err)`

Is this a byte-compiled font-lock rule? The readme for [font-lock-studio](https://github.com/Lindydancer/font-lock-studio) talks about both "Hanging emacs" and byte-compiled font lock rules. Unfortunately, since this doesn't happen every time org files are loaded, I'm not sure that using that package to debug will work.

**Comment by bellyroun** [comment]
I've met similar issues in some other situations. I used gdb and found out that in the function `redisplay_window` (xdisp.c) (called indirectly by `redisplay_internal` (xdisp.c)), somehow the height of the mode line cannot be computed consistently.

Somewhere inside `redisplay_window`

```
if (WINDOW_WANTS_MODELINE_P (w)
	  && CURRENT_MODE_LINE_HEIGHT (w) != DESIRED_MODE_LINE_HEIGHT (w))
	{
	  f->fonts_changed = true;
	  w->mode_line_height = -1;
	  MATRIX_MODE_LINE_ROW (w->current_matrix)->height
	    = DESIRED_MODE_LINE_HEIGHT (w);
}
```

The variable ` f->fonts_changed` is set to be `true`, which causes the function`redisplay_window` to be called again somewhere later. But then somehow the `CURRENT_MODE_LINE_HEIGHT (w)` is changed back to an "undesired" value before the code run to the if statement above, which causes a dead loop. 

Those functions in `xdisp.c` are too long, so I didn't go further to inspect the reason.

**Comment by halvorlu** [comment]
I experience the same issue as i-brute-force. Any solutions found yet?

**Comment by angry-bird** [comment]
same here, still searching for a solution

**Comment by varun531** [comment]
What font are you guys using? I found I need to have Source Code Pro AND have it installed (of course).

**Comment by halvorlu** [comment]
I thought I was using Source Code Pro, but it seems I didn't have it installed. @varun531 : Did you _fix_ the problem by installing it, or the other way around?

**Comment by varun531** [comment]
@halvorlu At the time I *thought* I had fixed the problem by installing Source Code Pro, but Emacs started hanging again the next day, despite the installed font. Very frustrating. I just get around it by mashing Ctrl-g whenever Emacs gets hung up on an .org file.

**Comment by richerve** [comment]
I'm having a similar issue. I notice that it happens when trying to open a Salstack (.sls) file. I'm using the salt layer that underneath is using mmm-mode to mix jinja and yaml

**Comment by richerve** [comment]
Now I found that it only happen when opening and .sls file that is using jinja to render jinja files. That's the case when using something like [https://github.com/audreyr/cookiecutter]. It throws the same error: **_Not enabling jit-lock: it does not work in indirect buffer_**

Maybe is related to the recent update of the spacemacs_theme which I'm using

**Comment by mcheema** [comment]
I have similar problems suddenly appear on my upto date OSX  and I don't use spacemacs.  I made some changes to try to make my .emacs more "modern" by copying large parts from a user here on github and changed my theme from default to wheatgrass.  I added a bunch of stuff like flyspell, flycheck, ibuffer, ido, etc. with the use-package idiom so I am guessing that somewhere in there is the problem.
