### ISSUE TITLE
cider-turn-on-eldoc-mode has been removed

### ISSUE THREAD

**Issue by lianxiangru** [syl20bnr/spacemacs#5780]
The clojure layer uses this function which has been removed from cider. Please update the code related to eldoc mode in clojure layer. Thanks!

**Comment by NJBS** [comment]
This issue has been resolved on `develop` and has recently been marked for a hotfix on `master`. https://github.com/syl20bnr/spacemacs/pull/5578

**Comment by lianxiangru** [comment]
@NJBS Great! Thank you.
