### ISSUE TITLE
Perspective/Eyebrowse error

### ISSUE THREAD

**Issue by Chream** [syl20bnr/spacemacs#5781]
#### Description
The perspective layer is not working after rebase on the develop branch. (it says 'chream' but it is a completely new branch from 'develop'. I am not running the eyebrowse package in my config, is this also run automatically with full spacemacs? The same error happens when trying to open previously saved layers from file.

#### Reproduction guide
- Start Emacs
- Try to open new perspective (M-m l 2)

*Observed behaviour:*
"Wrong number of arguments for something hooks related" ? Seems like it is something wrong with the eyebrowse compatibility/integration with perspective.

*Expected behaviour:*
Open new perspective layer

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.18
- Spacemacs branch: chream (rev. 0aafaec)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(markdown auto-completion better-defaults emacs-lisp git org
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          syntax-checking version-control semantic gtags ibuffer osx c-c   common-lisp java python
          (clojure :variables clojure-enable-fancify-symbols t)
          latex csv)
```

#### Backtrace
```
Perspective in this position doesn't exist.
Do you want to create one? (y or n) y
run-hook-with-args: Wrong number of arguments: (lambda (_new-persp-name _frame) "Update and save current frame's eyebrowse workspace to its perspective.
Parameters _NEW-PERSP-NAME and _FRAME are ignored, and exists only for
 compatibility with `persp-before-switch-functions'." (let* ((current-slot (eyebrowse--get (quote current-slot))) (current-tag (nth 2 (assoc current-slot (eyebrowse--get (quote window-configs)))))) (eyebrowse--update-window-config-element (eyebrowse--current-window-config current-slot current-tag))) (spacemacs/save-eyebrowse-for-perspective)), 1
```

**Comment by cpaulik** [comment]
I had the same, updating the packages solved this for me.

**Comment by syl20bnr** [comment]
Indeed, for people on develop branch persp-mode must be updated manually by deleting the folder from the elpa directory and restart Emacs.

This is because we switched to the official MELPA version of persp-mode.

**Comment by Chream** [comment]
Confirmed. Thank you!
