### ISSUE TITLE
clojure layer -> vim mode weird for stack traces and failing tests 

### ISSUE THREAD

**Issue by hnry** [syl20bnr/spacemacs#5783]
Using clojure layer and cider, the buffers that get opened from normal use like stack traces and testing output, the buffer names usually are something like:
- cider-error   (mode `cider-tmp`)
- cider-test-report   (not sure mode? don't see one)

They do not have full vim mode enabled?  Basic movement (h j k l) is ok, but other commands is not ok, shift-4, 0, w, f etc. As well as my own custom keys in vim normal state binding do not work. However C-f C-b work ok (page up/down) so I'm confused.

As expected emacs keys do not work that begin with C- since they do not work normally. But can move using x-f x-b x-e x-a like normal emacs.

So this is weird behaviour. I just end up having to mix styles to get good movement in these buffers.

**Comment by StreakyCobra** [comment]
These modes probably need evilification (i.e. need to be adapted to use vim bindings).

**Comment by hnry** [comment]
So for `cider-test-report` the `x-` emacs keys do not work there so movement is really hard.

How come `h j k l` work ok if vim isn't fully working? is that something that gets pulled into every buffer?

The thing is I'm ok with these things not having vim bindings, since they don't require much editing (think they are read-only anyway). Either solution is fine (full vim or full emacs). Just right now some vim keys work, some don't, some emacs keys work, some don't and it's all messed up. :cry:
