### ISSUE TITLE
Spacemacs layouts - new layout does no longer start with emtpy buffer list

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#5787]
#### Description

A new layout used to and should start with an empty buffer list. But now it adds the current buffer to a newly created layout.
#### Reproduction guide
- Start Emacs
- Open any file
- `SPC l l layout-name RET`

_Observed behaviour:_
Buffer visiting the file is part of new layout.

_Expected behaviour:_
layout should start with empty scratch buffer.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.18
- Spacemacs branch: develop (rev. 5ee970f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(ansible
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/dotfiles/.spacemacs-config/snippets/" auto-completion-enable-help-tooltip nil)
 chrome clojure colors custom_org_config django
 (elfeed :variables rmh-elfeed-org-files
         (list "~/Dropbox/org/feeds.org"))
 emacs-lisp emoji erc finance games
 (git :variables git-gutter-use-fringe t)
 github gnus graphviz html ipython-notebook javascript latex lua markdown my-mu4e my_python org org-ipython org-page pandoc pdf-tools php
 (python :variables python-enable-yapf-format-on-save nil python-auto-set-local-pyenv-version 'on-project-switch python-test-runner
         '(pytest))
 ranger research-config restclient ruby rust search-engine semantic
 (shell :variables shell-default-shell 'term shell-default-term-shell "/bin/zsh")
 shell-scripts
 (spell-checking :variables spell-checking-enable-by-default nil)
 spacemacs-helm spacemacs-layouts syntax-checking systemd tmux vagrant
 (version-control :variables version-control-diff-tool 'diff-hl)
 yaml)
```

**Comment by StreakyCobra** [comment]
I have the impression it's not the first time that I read about this problem, but I'm not sure nor can find any other issue, so I'm probably wrong.
