### ISSUE TITLE
React, Flycheck, and ESLint Not Working Together

### ISSUE THREAD

**Issue by jupl** [syl20bnr/spacemacs#5792]
#### Description

When opening a JSX file, error checking appears to not be working at all.
- Flycheck is enabled for the buffer
- Flycheck and ESLint work properly in a regular JS file
- ESLint by itself works properly on the JSX file

This was working properly several weeks ago. The messages buffer does not supply any information. I will note that it appears that perhaps the linting process does not even get fired as typically I will see the flycheck count update on the mode line but not for JSX files.
#### Reproduction guide
- Start Emacs
- Ensure ESLint is properly set up
- Open a JS file and a JSX file

_Observed behaviour:_
JS file reports errors from ESLint properly, while JSX does not.

_Expected behaviour:_
JS and JSX file reports errors from ESLint properly.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.18
- Spacemacs branch: develop (rev. 5ee970f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((clojure :variables clojure-enable-fancify-symbols t)
 colors dockerfile emacs-lisp html github markdown osx react restclient shell shell-scripts syntax-checking vimscript yaml
 (auto-completion :variables auto-completion-enable-help-tooltip t)
 (git :variables git-magit-status-fullscreen t magit-push-always-verify nil)
 (javascript :variables js2-mode-show-parse-errors nil js2-mode-show-strict-warnings nil)
 (org :variables org-src-preserve-indentation t org-startup-folded 'showall)
 (version-control :variables version-control-diff-tool 'diff-hl))
```

**Comment by ethanluoyc** [comment]
I can report the same errors with my installation of Spacemacs.

1. error-list is not showing up proper.
2. The Eslint linter is not picking up my `.eslintrc` configuration

I have tried to reproduce this error with Vanilla Emacs to see if this is a bug from Eslint or Flycheck, but since everything runs normal under the Vanilla Emacs it is safe to conclude that the bug comes from Spacemacs.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: nil (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(sml ipython-notebook github yaml markdown
     (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
     emacs-lisp javascript personal html go
     (python :variables python-test-runner 'pytest)
     (latex :variables latex-build-command "latex" latex-enable-auto-fill t)
     (ruby :variable ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec ruby-version-manager 'rbenv)
     ruby-on-rails react shell-scripts
     (shell :variables shell-default-shell 'multi-term shell-default-height 40 shell-default-position 'bottom)
     (version-control :variables version-control-diff-tool 'git-gutter version-control-global-margin t)
     dash gtags git osx
     (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip t)
     org syntax-checking sql
     (matlab :variables matlab-indent-function t matlab-shell-command "/applications/matlab_r2015a.app/bin/matlab"))
```

**Comment by d12frosted** [comment]
Quoting @NJBS 

> flycheck does not see react-mode as a valid mode for eslint, https://github.com/flycheck/flycheck/blob/master/flycheck.el#L7657.

**Comment by NerdsvilleCEO** [comment]
@d12frosted has this been reported upstream? I am seeing this issue too, I am able to manually change the binary it uses, but I also can't figure out how to enable eslint even after doing this

**Comment by zinigor** [comment]
Sorry to add meaningless comments, but has anyone had any success with this?

**Comment by pavilion** [comment]
Same problem here

**Comment by girvain** [comment]
I had this problem and it turned out I forgot to install eslint-plugin-react -g
I install this and eslint globally, rather than individual projects.
