### ISSUE TITLE
Project root for vagrant commands

### ISSUE THREAD

**Issue by mekanix** [syl20bnr/spacemacs#5794]
All vagrant related commands complain with "No Vagrantfile found in ~/vagrant or any parent directory"

#### Reproduction guide
- Start Emacs
- SPC V V

#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.18
- Spacemacs branch: master (rev. c8c4ff3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 dockerfile emacs-lisp git github html javascript markdown org spell-checking syntax-checking python react restclient ruby vagrant version-control)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by Ecno92** [comment]
This is a problem in the vagrant.el package:
https://github.com/ottbot/vagrant.el/issues/11

@mekanix already reported it over there. So I expect it will be resolved in the near future.

**Comment by CarlQLange** [comment]
Has been fixed upstream, I updated packages and it's fine now.

**Comment by StreakyCobra** [comment]
@mekanix If it's also solved for you after updating your packages, feel free to close the issue :smiley:
