### ISSUE TITLE
No function signatures for completion in rust-mode

### ISSUE THREAD

**Issue by landaire** [syl20bnr/spacemacs#5798]
#### Description
In rust-mode function signatures should be provided for completion, but I'm not seeing any.

#### Reproduction guide
- Start Emacs
- Load a rust file
- Try completing something (say `std::io::stderr().wr`)

*Observed behaviour:*
Completions are present but there's no signature

<img width="503" alt="screen shot 2016-04-14 at 00 04 06" src="https://cloud.githubusercontent.com/assets/1313522/14546842/fc209912-025c-11e6-89a6-10f69c220185.png">

*Expected behaviour:*
Completions should look like the ones [here](https://github.com/racer-rust/emacs-racer)

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.18
- Spacemacs branch: master (rev. c8c4ff3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 better-defaults emacs-lisp git org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control semantic c-c   d go rust swift yaml latex markdown gtags osx spacemacs-layouts themes-megapack
 (colors :variables colors-enable-rainbow-identifiers nil))
```

#### Racer configuration

Here is my rust/racer config:

```
  (setq-default rust-enable-racer t)
  (setq racer-rust-src-path "/usr/local/src/rust/src/")
  (setq rust-enable-rustfmt-on-save t)
  (add-hook 'rust-mode-hook #'rustfmt-enable-on-save)
```

**Comment by NJBS** [comment]
This was fixed in `develop` https://github.com/syl20bnr/spacemacs/pull/4516

Sadly, it has not made its way to `master` yet.

**Comment by landaire** [comment]
Dang. Glad to see it's fixed, shame it's not on `master` yet. Thanks NJBS.
