### ISSUE TITLE
The `navigation' part of `visual-line-navigation' does not take effect until a state transition

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#5799]
#### Description
When using ```SPC t L``` to toggle visual line navigation for the first time, visual-line-mode is turned on but navigation between visual lines is not available until a state transition.

#### Reproduction guide
- Start Emacs
- Open any file with long lines
- Hit ```SPC t L```
- Navigate between lines using ```j``` or ```k```

*Observed behaviour:*
Visual-line-mode is turned on, but cusor only moves by hard lines. After a state transition, eg. switch to insert state and switch back, the visual line navigation feature is back. 

*Expected behaviour:*
The visutal line navigation should work without having to do a state transition first.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.18
- Spacemacs branch: nil (rev. 5ee970f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :disabled-for org)
 better-defaults emacs-lisp evil-snipe font-lock-studio git github latex markdown org citation gtd window-purpose
 (han :variables han-enable-youdao-dict t han-enable-fcitx t han-org-line-spacing 0.2)
 pdf-tools python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts smex
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking version-control)
```

#### Related
This issue happens after recent commit ec3bbd41769, and it is related to https://bitbucket.org/lyro/evil/issues/301/evil-define-key-for-minor-mode-does-not

**Comment by TheBB** [comment]
I guess we have to trigger `(evil-normalize-keymaps)` in that toggle, then.

**Comment by TheBB** [comment]
#5834

**Comment by et2010** [comment]
Thanks, it works like a charm!
