### ISSUE TITLE
active window's indicator losing highlight after linter pops up message

### ISSUE THREAD

**Issue by svatem1** [syl20bnr/spacemacs#5801]
[as shown here](http://imgur.com/2sZXUSvl) , window's number inside area marked by red hand-drawn circles should be highlighted 

#### Description
when cursor is on area marked by linter and linter's message pops up, active window's (even if still having the focus) indicator loses highlight (which can be regained e.g. by switching to another window via spc-1 e.g. or performing some window related operation like resize)

#### Reproduction guide
load .js file with some error, have properly set up linter, navigate cursor to word marked by linter, wait till linter's description message appears; at that moment, active window's indicator loses highlight

**Comment by StreakyCobra** [comment]
I don't have this behaviour on `develop`. But I suspect it's probably linked to the OS and the windows manager used.

A random guess would be that the windows manager see the popup as being a new window stealing the focus from emacs. Can you paste the output of `SPC h d s`?

**Comment by svatem1** [comment]
#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.18
- Spacemacs branch: master (rev. c8c4ff3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion
 (colors :variables colors-enable-rainbow-mode t)
 (dash :variables dash-helm-dash-docset-path "C:/Zeal/" helm-dash-browser-func 'eww)
 emacs-lisp git html
 (javascript :variables tern-command
             '("node" "c:/users/user/appdata/roaming/npm/node_modules/tern/bin/tern"))
 org syntax-checking themes-megapack theming version-control)
```

**Comment by StreakyCobra** [comment]
Maybe it's windows related then. Let's see if someone on windows can reproduce it.

**Comment by NJBS** [comment]
It is indeed Windows related. However, I can only reproduce this on Emacs 24.5. On Emacs 25 the behavior disappears.

**Comment by svatem1** [comment]
@NJBS good to know, will upgrade

**Comment by svatem1** [comment]
I can confirm this issue being gone on 25.

**Comment by d12frosted** [comment]
Closing as being fixed upstream. Thanks everyone! 😸
