### ISSUE TITLE
Magit "y" binding (magit-show-refs) is provided in magit "?" popup, but unusable

### ISSUE THREAD

**Issue by sp3ctum** [syl20bnr/spacemacs#5802]
Hi guys, thanks for your work on spacemacs - I love it.

Here's how to reproduce this minor issue I found:
- open magit via `SPC g s`
- press `?` to bring up _magit-dispatch-popup_
- the popup lists pressing `y` as "Show refs"
- press `y` -> magit-refs is shown normally

But if you try to press `y` without first pressing `?`, it acts like evil's `y` (yank).
Btw, my spacemacs-version is "0.105.16".

**Comment by joehillen** [comment]
Paging @justbur

**Comment by justbur** [comment]
This is intended, see https://github.com/justbur/evil-magit#key-bindings.

You can set `evil-magit-use-y-for-yank` to `nil` before loading evil-magit if you want `y` to only show-refs.

**Comment by sp3ctum** [comment]
I see, thanks for letting me know!

**Comment by joehillen** [comment]
@justbur is it possible to change what the popup says based on what `evil-magit-use-y-for-yank` is set to?

**Comment by justbur** [comment]
@joehillen It doesn't really make sense. It would have to be `yr` for show-refs, but that would mean creating a new popup under `y` with one entry for `r`. That would also break the functionality of `yy`, `ys` and `yb`. Magit popups are not that flexible. 

If you don't like the yank stuff you can disable it. I personally think the slight inconsistency in the popup versus no popup behavior is worth the added functionality.

**Comment by joehillen** [comment]
It's not possible it have the popup show "`yr` Show Refs" instead of "`y` Show Refs"?

I personally don't mind yank behaviour. I'm just curious if the popup could be made more clear to avoid future confusion.

**Comment by justbur** [comment]
> It's not possible it have the popup show "yr Show Refs" instead of "y Show Refs"?

As far as I know, no. Actions are bound to single characters. If there's an easy way to do it I'm not aware of it. 

Which-key pops up after `y` and shows the options though.

**Comment by joehillen** [comment]
I see.

I think a better solution than `yr` might be to change the binding to something unused (there aren't a whole lot of options left though).

`J` seems like it could work.

**Comment by justbur** [comment]
> I think a better solution than yr might be to change the binding to something unused (there aren't a whole lot of options left though).

No there aren't. I'm open to other possibilities. Hopefully something that helps you remember it

**Comment by tarsius** [comment]
"Sub-popups" are now possible, [here's an example](https://github.com/magit/magit/blob/master/lisp/magit.el#L1361). Whether creating a new popup for this is worth it, I don't know.
