### ISSUE TITLE
holy-mode and lisp editing and escaping back to holy-mode

### ISSUE THREAD

**Issue by mattharrison** [syl20bnr/spacemacs#5805]
Hi, I use holy-mode.

When I'm editing clojure code in "lisp" state (pink), "fd" doesn't escape. It looks like hitting `ESC` does, but it puts me in evil-mode rather than holy-mode. Then I have to do the silly `M-x holy-mode` two times dance to get back to normal. 

Feature? Bug?

**Comment by syl20bnr** [comment]
This is a bug fixed in develop branch, I'll try to backport it in master branch.

**Comment by mattharrison** [comment]
Thanks for the quick response! That would be awesome. I think I'm seeing similar behavior in other places. Will try and track those down too.

**Comment by syl20bnr** [comment]
New holy-mode backported in 0.105.19, should fix this issue.
