### ISSUE TITLE
[OS X] spacemacs init failed after checked out develop branch(5ee970f, 2016-4-13)

### ISSUE THREAD

**Issue by fishmacs** [syl20bnr/spacemacs#5806]
Every thing were ok while the first emacs starting after switching to develop branch, packages installed, spacemacs loaded successfully.

But then spacemacs initialization kept failure at succeeding restart:

```
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "evil") 
|  require(evil)
|  eval-buffer(#<buffer  *load*> nil "/Users/username/.emacs.d/init" nil t)  ; 
...
#[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\20$
...
```

I checked out master then checked out develop again, it still only worked for first time, after that the same error as above... 

Now I have to switch back to master branch, it still works.

**Comment by StreakyCobra** [comment]
I don't know what the problem, but you may try to update the packages (`[Update packages]` from `*spacemacs* buffer) if not already done.
