### ISSUE TITLE
Clojure: CIDER debug mode should allow default hotkeys

### ISSUE THREAD

**Issue by holguinj** [syl20bnr/spacemacs#5808]
CIDER's debug mode helpfully shows a line with the active hotkeys for actions like "(n)ext", "(c)ontinue", "(o)ut", etc., but you can't actually use these in evil-mode without hitting `\` first. Since you shouldn't be doing editing while the debugger is active, it would make sense for those keys to work as they would in emacs-state.

**Comment by sooheon** [comment]
Do you use hybrid editing style, by any chance? Or are you on master, not develop? This is already fixed for vim style on develop, and there is a PR to fix it for hybrid as well at #5809.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
