### ISSUE TITLE
Question: is an HTTP request made the first time you launch helm in a new Spacemacs session?

### ISSUE THREAD

**Issue by zachlatta** [syl20bnr/spacemacs#5811]
For some reason, helm completely hangs after initial startup when I'm tethering my laptop through my phone. When I'm connected to my VPN or on most networks, I don't run into any troubles.

Could this be because T-Mobile is blocking some sort of HTTP request being sent from Spacemacs?

**Comment by cshtarkov** [comment]
See https://github.com/emacs-helm/helm/issues/1000

When Tramp first starts (it gets loaded by Helm), it tries to connect to the "host.does.not.exist". If the ISP reroutes this to a custom "not found" page, Tramp will hang for some time.
One workaround is to map this host to 127.0.0.1 in your hosts file.

**Comment by StreakyCobra** [comment]
Look at the FAQ `SPC f e f`, there is an entry about this and some pointers
for solution.

**Comment by zachlatta** [comment]
Ah, great. Thanks all. Closing for now.
