### ISSUE TITLE
Eyebrowse and Persp errors, conflicting?

### ISSUE THREAD

**Issue by liujoey** [syl20bnr/spacemacs#5813]
#### Description
Eyebrowse seems conflicts with Persp, when creating a new layout with `SPC` `l` `number` it shows below error message (in Back trace session).

#### Reproduction guide
- Start Emacs
- `SPC` `l` `2`
- It asking for a persp name, type any name, then `RET`

*Observed behaviour:*
Report error as shown below in Back trace session.

*Expected behaviour:*
Create a new persp layout with the given name

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.18
- Spacemacs branch: develop (rev. 5ee970f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion better-defaults unimpaired emacs-lisp
                (colors :variables colors-enable-rainbow-identifiers t)
                (version-control :variables version-control-diff-tool 'diff-hl)
                (shell :variables shell-default-shell 'ansi-term)
                markdown git html scala javascript python django evil-commentary osx org org-custom syntax-checking restclient vinegar)
```

#### Backtrace
```
run-hook-with-args: Wrong number of arguments: (lambda (_new-persp-name _frame) "Update and save current frame's eyebrowse workspace to its perspective.
Parameters _NEW-PERSP-NAME and _FRAME are ignored, and exists only for
 compatibility with `persp-before-switch-functions'." (let* ((current-slot (eyebrowse--get (quote current-slot))) (current-tag (nth 2 (assoc current-slot (eyebrowse--get (quote window-configs)))))) (eyebrowse--update-window-config-element (eyebrowse--current-window-config current-slot current-tag))) (spacemacs/save-eyebrowse-for-perspective)), 1
```

**Comment by syl20bnr** [comment]
You have to update your persp-mode package. Delete it from elpa to be sure to grab the MELPA version.

**Comment by liujoey** [comment]
Yes, you are right. I clicked the `update the packages` in spacemacs main page, but didn't clean the elpa folder manually.

**Comment by syl20bnr** [comment]
Normally it is not needed to clean the package directory manually but in this particular case we moved from a fork to the MELPA version and Spacemacs cannot detect this.

**Comment by syl20bnr** [comment]
duplicate of #5781

**Comment by liujoey** [comment]
I'm just thinking what's the use case to combine both eyebrowse and Persp. I know they serve different purpose but activate both of them feels like an overkill of the task. I know I can simply disable eyebrowse package from the configuration, just curious about how other people use them?

**Comment by d12frosted** [comment]
@liujoey see https://github.com/syl20bnr/spacemacs/issues/3733 as example :)

**Comment by liujoey** [comment]
OK, now I get the idea. Thank you.

I'm a vim guy transiting to Spacemacs, in vim world people more often manage multiple domain(projects) in different terminal sessions. Either through Tmux sessions or just use iTerm2 tabs. So each Vim instance will have only buffers list associate with one project. But Emacs tends to manage everything (even mail client and IRC) in single instance. That's quite different philosophy.

**Comment by d12frosted** [comment]
> But Emacs tends to manage everything (even mail client and IRC) in single instance. That's quite different philosophy.

Yes. It's pretty rare for people to have multiple Emacs instances. At least, for my knowledge.
