### ISSUE TITLE
Jump to symbol in Clojure

### ISSUE THREAD

**Issue by favetelinguis** [syl20bnr/spacemacs#5815]
I cant find any support in the Clojure layer for jumping to symbol under point, either in the same buffer or between buffers. I belive this is supported in vanilla Cider, any reason the Clojure layer is not supporting this or am i just missing something???

**Comment by StreakyCobra** [comment]
I'm not doing clojure so I don't know, but you may try:

- `gd` for "go definition"
- `*` for searching the symbol under the point in the current buffer
- `SPC *` for searching the text under the point in the current project

If there is a cider function that does this, please give its name. Also if you are motivated [here is the documentation for adding key-bindings](https://github.com/syl20bnr/spacemacs/blob/develop/CONTRIBUTING.org#contributing-a-keybinding). PR welcome :smiley:. Be sure to use a major-mode specific key binding (i.e. `SPC m …`).

**Comment by nwolfe** [comment]
@favetelinguis Nearly all the commands require that you have a REPL open with your Clojure code loaded in it.  If you don't open a REPL first, you'll still see the keybindings available but they won't do anything when you invoke them.

You basically need to run `, s i` when you start working on a Clojure project.
