### ISSUE TITLE
init error: definition is void: which-key-declare-prefixes

### ISSUE THREAD

**Issue by edrex** [syl20bnr/spacemacs#5816]
I pulled develop, I guess it's been a couple of weeks. Init broke:

```
Warning (initialization): An error occurred while loading `/Users/eric/.emacs.d/init.el':

Symbol's function definition is void: which-key-declare-prefixes

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

Git bisect: 8e897f6b7bae3261376ea0d3ee82077b547e420b is the first bad commit

I diffed my ~/.spacemacs with ~/.emacs.d/core/template/.spacemacs.template and copied over some new lazy init stuff, but didn't see anything else that looked suspicious.

**Comment by edrex** [comment]
narrowed it down to one of my private layers. I guess i need to update it with the new hotness.

**Comment by rogeric** [comment]
Still got problem when init.

![image](https://user-images.githubusercontent.com/7962109/136017493-04410aec-2671-49b4-ad2b-3fafed3abebd.png)

after --debug-init
![image](https://user-images.githubusercontent.com/7962109/136017540-8783f660-2cc1-48b3-b9a9-a78673c6630c.png)

Need your help, thanks!!!
