### ISSUE TITLE
Incompatible between `sp-up-sexp` and `auto-completion`.

### ISSUE THREAD

**Issue by eric-meng** [syl20bnr/spacemacs#5822]
I key-bind `sp-up-sexp` to `C-l` for the convenience to jump out of one level parentheses, 

while after finishing typing in a pair of parentheses, if the inputted information is also tracked by `auto-completion` that gives out several further options and I don't want to complete it anymore and just want to jump out the parentheses, using `sp-up-sexp` will spontaneously complete from the list and modify my input instead of just jumping out the parentheses.

**Comment by bmag** [comment]
The auto-completion layer binds <kbd>C-l</kbd> to `company-complete-selection` in the `company-active-map` keymap. Does adding this snippet to `dotspacemacs/user-config` help?
```elisp
(with-eval-after-load 'company
  (define-key company-active-map (kbd "C-l") nil))
```

**Comment by eric-meng** [comment]
@bmag I thought the keybinding by users would have covered the original settings, but it is proved  incorrect. It is really a keybinding contradictory problem. Thx very much!

In my spacemacs C-l has a original keybinding to recenter-window whatever, as a primary learner, to figure out these elementary problem really hard, thanks for your kind and working help
