### ISSUE TITLE
Mode menu weird behavior under emacsclient

### ISSUE THREAD

**Issue by lianxiangru** [syl20bnr/spacemacs#5829]
If I use `emacsclient` to connect to a daemon, the mode menu does not expand at the bottom of the screen:

---
![ss](https://cloud.githubusercontent.com/assets/8991941/14621604/13c12e5a-0592-11e6-855e-74d82b73388b.png)

---

It behaves normally if I use `emacs` instead:

---
![ss](https://cloud.githubusercontent.com/assets/8991941/14621647/52df3c94-0592-11e6-88a5-fe8728e1d73a.png)

---
Could this be fixed? Though I can just use F10 to invoke a menu, it would be better if this bug can be fixed. (I use i3wm on Arch Linux, though I don't know whether this is relevant or not.)

---
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.18
- Spacemacs branch: develop (rev. 7f95d25)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence "jk" auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 evil-cleverparens emacs-lisp
 (clojure :variables clojure-enable-fancify-symbols nil)
 (latex :variables latex-enable-auto-fill t latex-enable-folding t)
 bibtex rebox git
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 markdown shell-scripts spell-checking systemd semantic sage syntax-checking imenu-list
 (org :variables org-enable-github-support t)
 version-control
 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp")
 evil-commentary)
```

**Comment by StreakyCobra** [comment]
It doesn't looks like a Spacemacs bug for me. Can you try to reproduce on a stock emacs?

I'm also running emacs in daemon mode on archlinux with i3wm and I don't have this behaviour.

**Comment by lianxiangru** [comment]
@StreakyCobra You are right, on a fresh installed emacs the bug persists and the terminal gives
```
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```
Although I think this is irrelevant to my problem. I just find that on another monitor connected to me laptop the bug does not show up.
My screen setting is like this:

```
---------------------------------------------
|                        |                 |
|            1          |       2        |
|      bug here    |                 |
-------------------------|                 |
                         |   no bug  here |
                         --------------------
```

Perhaps it is relevant to the geometry of the screen setting?

**Comment by StreakyCobra** [comment]
> Perhaps it is relevant to the geometry of the screen setting?

Probably then.

So, I don't relly knows if the problem is on Emacs side, i3wm side, gtk side or something else, but it doesn't seems to be on Spacemacs side, we can't do much about this.

**Comment by lianxiangru** [comment]
@StreakyCobra  I completely understand. Thanks for your help! Feel free to close this issue.

It's not a serious bug. I will look into it when I have time.

**Comment by StreakyCobra** [comment]
:+1: :smiley:
