### ISSUE TITLE
How to run python and use anaconda-mode completion in remote server?

### ISSUE THREAD

**Issue by yangj1e** [syl20bnr/spacemacs#5830]
How can I make Python completion work when I edit a remote file?
I opened a Python source file in a remote server and when I run python, I got the following error

```
Warning (emacs): Python shell prompts cannot be detected.
If your emacs session hangs when starting python shells
recover with `keyboard-quit' and then try fixing the
interactive flag for your interpreter by adjusting the
`python-shell-interpreter-interactive-arg' or add regexps
matching shell prompts in the directory-local friendly vars:
  + `python-shell-prompt-regexp'
  + `python-shell-prompt-block-regexp'
  + `python-shell-prompt-output-regexp'
Or alternatively in:
  + `python-shell-prompt-input-regexps'
  + `python-shell-prompt-output-regexps'
```

In Python buffer, I got

```
env: /usr/local/bin/python: No such file or directory
```

I tried to set Python interpreter path via

```
M-x pythoninc-activate RET /ssh:remote_host:/home/user/venv RET
```
and
```
(setq python-shell-interpreter "/ssh:remote_host:/usr/bin/python")
```
but neither worked.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.18
- Spacemacs branch: master (rev. c8c4ff3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 syntax-checking version-control osx latex
                 (c-c   :variable c-c  enable-clang-support t)
                 (python :variables py-yapf-options
                         '("--style=google"))
                 ipython-notebook dash protobuf)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by cpaulik** [comment]
I guess you have read https://github.com/proofit404/anaconda-mode#tramp ? Is your network configured correctly? Port 9000 is often not open. I can try later but at the moment I don't have a machine that fits all the requirements.

**Comment by cpaulik** [comment]
So I just tried remote completion on my raspberry pi. After installing `anaconda-mode` on the raspberry pi everything worked fine. I was even able to execute the code remotely using `SPC m c c`.

**Comment by yangj1e** [comment]
Open a remote Python source file, then `M-x pythoninc-activate RET /ssh:remote_host:/home/user/venv RET` just worked. There is no need to `run python` for auto completion.
For `run python`, see http://emacs.stackexchange.com/questions/13385/running-ipython-remotely
