### ISSUE TITLE
spacemacs support golang?

### ISSUE THREAD

**Issue by YuleiXiao** [syl20bnr/spacemacs#5843]
I try to use spacemacs, and open a golang code file. There is no any highlight but c/c++ is good.

**Comment by TinySong** [comment]
@YuleiXiao Yes, spacemacs support golang, see https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/go, strongly suggest you use develop branch

**Comment by YuleiXiao** [comment]
Thanks very much. It wokred.
