### ISSUE TITLE
Support async def and await in python-mode

### ISSUE THREAD

**Issue by TheJJ** [syl20bnr/spacemacs#5844]
The new [PEP492](https://www.python.org/dev/peps/pep-0492/) is not yet supported in `python-mode` and indentation for an `async def` block has to be adjusted manually.

**Comment by TheBB** [comment]
We don't develop python-mode here. You have to take this upstream to Emacs.

**Comment by bixuanzju** [comment]
@TheJJ @TheBB I find the names of you two amusing

**Comment by obmarg** [comment]
This seems to have been fixed upstream: http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=1f6b0bc1512de08fd542df0234476788038c8c82

**Comment by doomsplayer** [comment]
When will the package be updated for this bug fix?

**Comment by cpaulik** [comment]
Is there a way to use this in spacemacs? It seems that even when I install the latest python package from ELPA there is no way that spacemacs is loading that.

**Comment by TheJJ** [comment]
Meanwhile, I upgraded to emacs `25.0.95` by using `app-editors/emacs-vcs` on gentoo. It works there :)
