### ISSUE TITLE
Add to jumplist for relative motion with count?

### ISSUE THREAD

**Issue by demon386** [syl20bnr/spacemacs#5847]
Vim has a trick to add relative motion (i.e. move with `j`, `k` with a count > 1) into jumplist, see: http://superuser.com/questions/539708/vim-moving-around-using-relativenumber-and-adding-it-to-the-jump-list-for-use-w

I think this feature is quite handy. How can I achieve this in Spacemacs?

**Comment by TheBB** [comment]
You have to redefine the `j` and `k` motions to do `(evil-set-jump)` first. An advice would work as well. For example.

```elisp
(defun my-evil-set-jump (&rest_)
  (evil-set-jump))
(advice-add 'evil-previous-line :before 'my-evil-set-jump)
(advice-add 'evil-next-line :before 'my-evil-set-jump)
```

You can write the advice to only set the jump if the count is ≠ 1 as well.

**Comment by demon386** [comment]
Cool. Thanks!
