### ISSUE TITLE
company-anaconda breaks auto-completion

### ISSUE THREAD

**Issue by mmcnl** [syl20bnr/spacemacs#5849]
#### Description
When `company-anaconda` mode is loaded no completions are offered when typing.

#### Reproduction guide
- Start Emacs
- Open a new blank Python buffer with `SPC f J py`
- start typing, eg `cl`

*Observed behaviour:*
- no completions are offered 
- `Wrong type argument: listp, (2 . 95)` appears in messages mini-buffer

*Expected behaviour:*
- completions from compay-anaconda are presented

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. 78be544)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python auto-completion emacs-lisp)
```

#### Backtrace
- If `(toggle-debug-on-error)` is enabled, then inserting any characters into the buffer leads to this:

```
Debugger entered--Lisp error: (wrong-type-argument listp (2 . 95))
  company-anaconda-prefix()
  company-anaconda(prefix)
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-idle-begin(#<buffer 21-010054.py> #<window 3 on 21-010054.py> 30 4)
  apply(company-idle-begin (#<buffer 21-010054.py> #<window 3 on 21-010054.py> 30 4))
  timer-event-handler([t 22296 35326 603825 nil company-idle-begin (#<buffer 21-010054.py> #<window 3 on 21-010054.py> 30 4) nil 0])
```

**Comment by mmcnl** [comment]
As another data point, the `anaconda-mode-complete` function works as expected and produces a list of completions, so the problem does not seem to be with anaconda's setup.

**Comment by StreakyCobra** [comment]
CC @cpaulik

**Comment by cpaulik** [comment]
I can not reproduce that on the same commit and with the same layer list. Do you have the latest packages?

**Comment by hujianxin** [comment]
Can be confirmed only in Emacs25.1. This will not appear in Emacs24.5.

**Comment by mmcnl** [comment]
@cpaulik: Yes, I verified the behavior with a fresh `elpa` directory and newly updated packages. I also was using a new `.spacemacs` file from the template with the only changes being adding the `python` and `auto-completion` layers.

**Comment by hujianxin** [comment]
@mmcnl @cpaulik This bug has been fixed in upstreamming.
