### ISSUE TITLE
Clojure mode: fuzzy auto-complete of Java class names not working

### ISSUE THREAD

**Issue by jstaffans** [syl20bnr/spacemacs#5853]
#### Description

CIDER [supports](http://bytopia.org/2015/03/06/smart-classname-completion-for/) fuzzy auto-completion of Java class names within the `:import` section of a namespace declaration. The biggest gain is that you don't have to remember the Java package name, but can instead start typing `ConcurrentLi` which should expand to a suggestion like `java.util.concurrent.ConcurrentLinkedQueue`. 

This fuzzy expansion does not work for me, I have to start typing from the start of the Java package name to get the completion suggestions.

#### Reproduction guide
- Start Emacs
- Open a Clojure project 
- `cider-jack-in`
- Open a namespace
- `, r a i` to add a Java class import
- Start typing `ConcurrentLi...`

*Observed behaviour:*
No completion matches.

*Expected behaviour:*
A suggestion like `java.util.concurrent.ConcurrentLinkedQueue`. 

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.18
- Spacemacs branch: master (rev. 3317323)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git markdown auto-complete version-control html javascript themes-megapack
            (clojure :variables clojure-enable-fancify-symbols t))
```

**Comment by NJBS** [comment]
Can you try updating your packages and/or spacemacs to the latest release (0.105.19)?

**Comment by jstaffans** [comment]
Same problem with 0.105.19 and updated packages.

**Comment by jstaffans** [comment]
Is this even a bug, or is it a missing feature? I'm not sure if CIDER with company mode supports this.

**Comment by sooheon** [comment]
Hm yeah some steps to reproduce the desired behavior with vanilla emacs would be nice, I can't seem to get it with just cider and company loaded.

**Comment by jstaffans** [comment]
It seems that this feature is only available with autocomplete, not company. Not really an issue with Spacemacs.
