### ISSUE TITLE
Git Gutter/ Diff-hl not working properly

### ISSUE THREAD

**Issue by andrew-kennedy** [syl20bnr/spacemacs#5856]
#### Description

Git gutter and diff-hl don't seem to be functioning properly, not showing how lines were changed. It shows blue highlights for modified lines but not green or red.
#### Reproduction guide
- Start Emacs
- Open a changed file within a git repo, 

_Observed behaviour:_
<img width="1392" alt="screen shot 2016-04-21 at 12 46 52 pm" src="https://cloud.githubusercontent.com/assets/2387159/14722211/489b6eb8-07bf-11e6-8e35-9c1e7cdf75b8.png">

_Expected behaviour:_
Expect to see a green highlight on the comment that says "inserted a new line"
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 c-c  
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 emacs-lisp emoji
 (git)
 html javascript markdown osx racket semantic syntax-checking themes-megapack
 (version-control :variables version-control-diff-tool 'diff-hl ))
```

**Comment by joehillen** [comment]
It's working for me on `develop`. Are your packages up to date?

**Comment by bleggett** [comment]
OS: Windows
Emacs: 25.0.94.2
Spacemacs: 0.105.21
Spacemacs branch: develop
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm

Using emacs-25 and spacemacs-develop, this is what I get when I include the `version-control` layer and perform no additional configuration to the layer.

![emacsversion-control](https://cloud.githubusercontent.com/assets/854255/16236372/29d7cf00-37a6-11e6-8ad6-aa57fba4ac07.PNG)

And this is what I get with `(version-control :variables version-control-diff-tool 'diff-hl)`
![image](https://cloud.githubusercontent.com/assets/854255/16236540/b76a014e-37a6-11e6-85e6-576fa75b5972.png)

**Comment by TheBB** [comment]
And what's the git diff output on that file? I.e. the diff between the on-disk version and HEAD?

**Comment by d12frosted** [comment]
Oops. There was another comment. 😸
