### ISSUE TITLE
Error on creating new perspectives

### ISSUE THREAD

**Issue by rahulmutt** [syl20bnr/spacemacs#5859]
#### Description
I'm unable to create new perspectives.

#### Reproduction guide
- Start Emacs
- SPC l 2
- Enter some perspective name
- Error will occur

*Observed behaviour:*
Error occurs when creating a perspective.

*Expected behaviour:*
Perspective should be created like it has in the previous versions.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(my-android auto-completion better-defaults restclient extra-langs emacs-lisp scala idris clojure rcirc themes-megapack
            (haskell :variables haskell-enable-ghc-mod-support nil)
            html javascript latex java yaml git github markdown org semantic search-engine eyebrowse shell-scripts
            (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t shell-protect-eshell-prompt t shell-default-height 20 shell-default-position 'bottom)
            spell-checking syntax-checking version-control)
```

#### Backtrace
```
run-hook-with-args: Wrong number of arguments: (lambda (_new-persp-name _frame) "Update and save current frame's eyebrowse workspace to its perspective.
Parameters _NEW-PERSP-NAME and _FRAME are ignored, and exists only for
 compatibility with `persp-before-switch-functions'." (let* ((current-slot (eyebrowse--get (quote current-slot))) (current-tag (nth 2 (assoc current-slot (eyebrowse--get (quote window-configs)))))) (eyebrowse--update-window-config-element (eyebrowse--current-window-config current-slot current-tag))) (spacemacs/save-eyebrowse-for-perspective)), 1
```

**Comment by NJBS** [comment]
Can you try updating your packages from the spacemacs home buffer?

**Comment by rahulmutt** [comment]
Thanks! That fixed it. But now I am facing a different error:
```
(in *Messages* buffer)
(Spacemacs) --> installing package: request@spacemacs-base... [1/1]
(Spacemacs) Warning: Cannot install package request.

(in new buffer)
Warning (emacs): Unable to activate package `helm-gitignore'.
Required package `request-0.1.0' is unavailable
```
I assume this won't affect anything other than magit.

**Comment by NJBS** [comment]
Delete the helm-gitignore folder from .emacs.d/elpa.



From: Rahul Muttineni
Sent: ‎Friday‎, ‎April‎ ‎22‎, ‎2016 ‎1‎:‎35‎ ‎AM
To: syl20bnr/spacemacs
Cc: NJBS; Comment


Thanks! That fixed it. But now I am facing a different error:
(in *Messages* buffer)
(Spacemacs) --> installing package: request@spacemacs-base... [1/1]
(Spacemacs) Warning: Cannot install package request.

(in new buffer)
Warning (emacs): Unable to activate package `helm-gitignore'.
Required package `request-0.1.0' is unavailable


I assume this won't affect anything other than magit.

**Comment by rahulmutt** [comment]
Error-free now. Thanks a lot!
