### ISSUE TITLE
shell-mode C-j and C-k not working

### ISSUE THREAD

**Issue by mijoharas** [syl20bnr/spacemacs#586]
in `*shell-mode*` (`SPC a s i`) and eshell (`SPC a s e`) `C-j` and `C-k` (which [should be](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#key-bindings-1) next and previous in history) do not work ( spacemacs 0.60.0 ). `C-j` goes down a line and `C-k` cycles up to `?` and then `^K` regardless of the history.

In addition `SPC m H` does not seem to work in `*eshell*` (it fails upon attempted insertion into the buffer.)

**Comment by mijoharas** [comment]
I can only find these having been implemented for [the python repl](https://github.com/syl20bnr/spacemacs/blob/master/contrib/lang/python/packages.el#L217) (and ac and helm e.t.c), not for the general shell anywhere (though my grep-fu could be lacking). `C-j` is bound to `electric-line-and-maybe-indent` and `C-k` is bound to `evil-insert-digraph` which is causing the problem. have these ever been implemented for `comint-mode` (or whatever the correct term is)?

**Comment by syl20bnr** [comment]
Cool idea, defining them for comint-mode may make them available for all the REPLs.
The conventions to implements for all REPLs and terminals are here: https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.md#in-terminal
