### ISSUE TITLE
Perspective-local primary shell buffers

### ISSUE THREAD

**Issue by rahulmutt** [syl20bnr/spacemacs#5862]
I frequently find myself wanting a "primary" shell of a given perspective to be different from other perspectives. What happens now is that I'll be in Perspective 1 with an eshell-1 buffer loaded. When I go to Perspective 2, I do SPC ' and the eshell-1 buffer loads up when I really want a new shell buffer (like eshell-2). I end up doing 2 SPC ' to get the new shell buffer and that causes a problem since the new primary buffer is eshell-2. When I go back to Perspective 1 and do SPC ', I get back eshell-2 instead of eshell-1. It seems like the most natural behavior is to have SPC ' assign a new shell buffer to each perspective so that users don't have to remember which shell number they opened in a given perspective.

**Comment by bmag** [comment]
Perhaps this should be a feature request for [shell-pop](https://github.com/kyagi/shell-pop-el)? I have some idea how to make perspective-local features, although I didn't get to test that idea in the wild.

**Comment by Miciah** [comment]
Looks like #10457 is intended to resolve this issue.

**Comment by duianto** [comment]
The following PRs changes have been applied to the `develop` branch:
Local shell pop #13556 

@rahulmutt Could you test the latest develop branch, you can close this if the issue has been solved.
