### ISSUE TITLE
syndaemon command in .profile causes spacemacs startup to hang 1/3rd through

### ISSUE THREAD

**Issue by Reefersleep** [syl20bnr/spacemacs#5865]
In my ~/.profile, I have the following line:
``syndaemon -i 2 -d -k``
This causes my mousepad to disable for 2 seconds after typing, handy for avoiding moving the cursor by mistake.

However, the line causes spacemacs to be unable to start up. Spacemacs will hang 1/3rd through loading. I gauge the process via the loading bar, which is filled one third of the way.

Once spacemacs hangs, I can only escape by either killing the window with ``xkill -id <id of the spacemacs window>`` or by ``C-g`` to stop the loading process, then ``:q`` to quit spacemacs. After ``C-g``, some functionality, such as ``helm`` commands, will be missing. Someone suggested that I access the Messages buffer to view error messages, but I am unable to do so.

If I comment out the ``syndaemon`` command and log out and in, spacemacs will load just fine.

**Comment by StreakyCobra** [comment]
I can't reproduce this on my machine.

As an alternative you may try to add it to your `~/.xinitrc` if your system support it.

**Comment by joehillen** [comment]
I'm having this problem too, and I don't think `syndaemon` is the cause.

Spacemacs takes about 2 minutes to start on my laptop and 5 seconds on my desktop. Identical configs on both. Killing `syndaemon` before starting spacemacs makes no difference on my laptop.

**Comment by Reefersleep** [comment]
@joehillen I think we're having different issues - with ``syndaemon``, spacemacs hangs _forever_ for me. It never finishes. I've tried with a clean config, with ``stable`` and ``master``, with a dirty config, no difference - only removing ``syndaemon`` enables me to load spacemacs fully.

**Comment by Reefersleep** [comment]
@StreakyCobra ``touch``ing a new ``~/.xinitrc`` and adding the ``syndaemon`` line here means that it is never run, in my case. Which means, spacemacs loads just fine, but I'm missing my ``syndaemon``. As I said to @joehillen, I've tried a number of different permutations, but the only thing that makes a difference is that specific line.

Interestingly, running ``syndaemon`` in a terminal _after_ logging in does not hinder spacemacs from loading fully.

**Comment by joehillen** [comment]
Isn't `~/.profile` sourced whenever you open a login shell? I don't think your startup programs belong there anyway. https://wiki.archlinux.org/index.php/Bash#Configuration_files It's quite possible emacs opens a login shell.

`~/.xinitrc` is only run if you use `startx` or `xinit`. What is your window manager or desktop environment?

**Comment by StreakyCobra** [comment]
@joehillen `SPC f e f hanging RET` :wink:

@Reefersleep Ok, your WM probably don't use `xinit` then. As @joehillen has said, I'm also not sure `.profile` is the correct place for running your `syndaemon`. Try to see if there is another way to run it at login time that doesn't impact Spacemacs.

**Comment by joehillen** [comment]
@StreakyCobra Already have that. :(

**Comment by Reefersleep** [comment]
@joehillen If you say so :) I only recently installed Ubuntu, I don't know much about what dotfile is read when. ``~/.profile`` was the only dotfile that I had success with when trying to ensure ``xmodmap``, ``xcape`` and ``syndaemon`` commands in every session, although there were probably more that I could have tried. I would greatly appreciate any other suggestions! I found it time consuming to pursue the "correct" place to put the commands, as it seemed that people on StackOverflow and the like had all kinds of different solutions, none of which worked for me. My WM is i3.

**Comment by joehillen** [comment]
I use i3 as well. :smile_cat: 

I have this at the bottom of my `~/.i3/config`

```
exec --no-startup-id syndaemon -t -k -i 2
```

You can do the same for `xcape` as well. You shouldn't have to do anything for `xmodmap`, the file just needs to be `~/.Xmodmap`

**Comment by StreakyCobra** [comment]
I also use i3. Whether `.xinitrc` would be used depend on the login manager I think (using slim in my case). @joehillen proposal is another way to go :-)

**Comment by Reefersleep** [comment]
Thank you guys, this worked! 

I went for @joehillen's approach, as I had tried ``.xinitrc`` earlier and had no luck.

Before, I had the following in my ``~/.profile``:
```
# Make the Caps Lock key emit Left Windows signal on keydown
xmodmap -e 'keycode 66 = Super_L'
xmodmap -e 'clear Lock'

# Make the Caps Lock key emit Escape signal on keyup when not in combination with other keys during keydown
xcape -e 'Super_L=Escape'

# Disable mousepad during and 2 seconds after keyboard activity - modifier keys excepted. -d means it starts in the background, as a daemon.
syndaemon -i 2 -d -k 
```
Now, I have removed all of that, and instead have the following in ``~/.Xmodmap``:
```
! Make the Caps Lock key emit Left Windows signal on keydown
keycode 66 = Super_L
clear Lock
```
And the following in my ``~/.i3/config``:
```
# Disable mousepad during and 2 seconds after keyboard activity - modifier keys excepted. -d means it starts in the background, as a daemon.
exec --no-startup-id syndaemon -i 2 -d -k 

# Make the Caps Lock key emit Escape signal on keyup when not in combination with other keys during keydown
exec --no-startup-id xcape -e 'Super_L=Escape'
```

And spacemacs starts up just fine.

Thank you so much! :smile:
