### ISSUE TITLE
Non-retina images for spacemacs

### ISSUE THREAD

**Issue by Nolski** [syl20bnr/spacemacs#5869]
I'm using a mbp with a retina display and the images are definitely too small and show color issues. Is there a way to switch these out with retina images?
<img width="723" alt="screen shot 2016-04-22 at 9 30 52 pm" src="https://cloud.githubusercontent.com/assets/2600677/14758526/a42f0a6a-08d1-11e6-8f1f-abb665948e56.png">

**Comment by ynilu** [comment]
I have a similar problem when I use the gnu emacs with cocoa:
<img width="1280" alt="screen shot 2016-04-23 at 3 38 08 pm" src="https://cloud.githubusercontent.com/assets/14059513/14760023/dee1076a-0969-11e6-9273-0ce825b00f24.png">

But it work fine on the emacs-mac-port verison:
<img width="1280" alt="screen shot 2016-04-23 at 3 43 47 pm" src="https://cloud.githubusercontent.com/assets/14059513/14760039/3aff8c6a-096a-11e6-8ee4-4e0592f9206a.png">


#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults
                 (c-c++ :variables c-c++-enable-clang-support t)
                 emacs-lisp git javascript latex markdown org osx python ruby semantic shell
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 (syntax-checking :variables syntax-checking-enable-by-default nil)
                 version-control)
```

**Comment by StreakyCobra** [comment]
For the quality: https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#the-powerline-separators-have-no-anti-aliasing-what-can-i-do (https://github.com/syl20bnr/spacemacs/issues/217)

For the colors: https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#why-are-the-powerline-colors-not-correct-on-os-x

Interesting read concerning the `emacs-macs-port` version: https://github.com/syl20bnr/spacemacs/issues/4955

**Comment by vimuel** [comment]
Had the same issue, used `emacs-mac-port` and looking fine now. Also tweaked `powerline-scale` (in my case 1.4 worked well.

**Comment by Huxpro** [comment]
For the `emac-cocoa` users, you can solve the color issue by adding `(setq ns-use-srgb-colorspace nil)` found from issues https://github.com/syl20bnr/spacemacs/issues/7321
