### ISSUE TITLE
How to return from C-c j?

### ISSUE THREAD

**Issue by xiaoyulei** [syl20bnr/spacemacs#5870]
I use C-c j to jump to definition in golang. How jump back to last point?
Default is C-c p to return when I use prelude. It looks like not work in spacemacs.

**Comment by cpaulik** [comment]
If you are using evil then `C-o` should always get you back to your last position.

**Comment by YuleiXiao** [comment]
@cpaulik I try it , but not work

**Comment by cpaulik** [comment]
What is `C-o` bound to for you? It should be `evil-jump-backward`.

**Comment by StreakyCobra** [comment]
More exactly, what does `SPC h d k C-o` reports?

**Comment by YuleiXiao** [comment]
C-o runs the command open-line (found in global-map)
@cpaulik @StreakyCobra

**Comment by krobelus** [comment]
looks like you are using emacs as dotspacemacs-editing-style

**Comment by YuleiXiao** [comment]
@krobelus yes, I use emacs style.

**Comment by TheBB** [comment]
> **If you are using evil** then C-o should always get you back to your last position.

**Comment by krobelus** [comment]
@YuleiXiao i tested it now with the go layer, and (pop-tag-mark) works fine for me. it is bound to M-*

**Comment by YuleiXiao** [comment]
@krobelus I try M-* , but still not work.

**Comment by krobelus** [comment]
@YuleiXiao For me, it is bound to M-*, on a fresh installation of spacemacs with only the go layer enabled.

**Comment by YuleiXiao** [comment]
@krobelus It is weird, I am the same with you, a fresh installation and only enable go layer.

**Comment by YuleiXiao** [comment]
![image](https://cloud.githubusercontent.com/assets/12639880/14817744/a5ccaae0-0beb-11e6-85cb-ec9523b4bbaa.png)

@krobelus

**Comment by tskinn** [comment]
For posterity, I've found that `M-,` does the trick. It is bound to `xref-pop-marker-stack`
