### ISSUE TITLE
How to scroll input history in REPL?

### ISSUE THREAD

**Issue by favetelinguis** [syl20bnr/spacemacs#5875]
I can not find a way to scroll through previous entered command in the Clojure Cider REPL. Is there a generic way for this or maybe it is a bug in the Clojure layer? Now I have to retype everything instead of scrolling the history.

**Comment by StreakyCobra** [comment]
`C-j` and `C-k` if I'm not mistaken.

**Comment by favetelinguis** [comment]
Not working C-j just moves down in buffer (both in insert and normal) C-k in insert just inserts strange chars and in normal its kill-line.

**Comment by TheBB** [comment]
What editing style are you using?

**Comment by favetelinguis** [comment]
What do you mean by editing style? I use the default Evil mode if that is it...

**Comment by bmag** [comment]
The generic emacs way is M-n and M-p, or C-<up> and C-<down>, though C-j and C-k should work too

**Comment by bmag** [comment]
Whoops, bad formatting on mobile. The missing shortcuts are C-up and C-down

**Comment by TheBB** [comment]
What mode is the cider REPL in? Is it a descendant of comint?

**Comment by bmag** [comment]
IIRC it's not comint-derived

**Comment by TheBB** [comment]
Hm, ok. Looks like they're defined for normal state, indeed.

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/clojure/packages.el#L151-L153

**Comment by favetelinguis** [comment]
Looks like so. How can i track down why its not working for me? I have
minimal custom settings.
Den 23 apr 2016 18:41 skrev "Eivind Fonn" <notifications@github.com>:
>
> Hm, ok. Looks like they're defined for normal state, indeed.
>
>
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/clojure/packages.el#L151-L153

**Comment by hoosierEE** [comment]
Noticed 2 separate bugs related to this issue.

1. If I launch a REPL from `eshell`, typing `C-up` or `C-down` brings up the last *eshell* command, not the last thing I typed in the REPL.

2. Starting a Python repl from eshell, I can type `C-p` to *display* what I typed earlier in history, but hitting Enter does not re-send it to the repl, e.g.

```python
>>> 1+1  # normal typing, hit Enter key
2
>>> 1+1 # use C-p to bring up previous history item, hit Enter, and...
>>> # nothing happens
>>> 1+1  # use C-p to bring up previous history item, and add a Space after the 2nd 1, hit Enter:
...            # ?! hit Enter again
>>> # nothing happens
```

**Comment by bmag** [comment]
1. that makes sense, it's not a bug.

2. that's weird. I don't know much about `eshell`, so I don't know if it's something we can fix

**Comment by TheBB** [comment]
Don't run REPLs or curses or other complicated terminal programs inside eshell or the Emacs terminal emulators, it's usually a recipe for frustration.

**Comment by fmjrey** [comment]
C-j and C-k also not working for me, nor C-up or C-down.
I added the following to my `(defun dotspacemacs/config () ...)` in `.spacemacs`:
```
(define-key cider-repl-mode-map (kbd "<up>") 'cider-rep-previous-input)
(define-key cider-repl-mode-map (kbd "<down>") 'cider-repl-next-input)
```
As I'm on OSX I also had to disable the corresponding mission control shortcuts in OSX preferences:
![screen shot 2017-02-27 at 12 36 42](https://cloud.githubusercontent.com/assets/489016/23361698/d1b26e84-fce9-11e6-966d-919db129e339.png)

Now C-up and C-down work, but it feels a bit brittle.

**Comment by Congrammers** [comment]
@fmjrey suggestion is working but yeah, feels a bit brittle, but I don't really care because I don't use the button for it :)

**Comment by OliverM** [comment]
Disabling the mission control shortcuts in OS X preferences (like @fmjrey suggested) worked for me to restore C-up and C-down functionality (using a British keyboard on a 2017 MBP).

**Comment by hoosierEE** [comment]
@TheBB I'm not well-versed in Emacs or Spacemacs, is there a preferred way to integrating a REPL program that *does* use `ncurses` or `readline`/`rlwrap`?

The Emacs terminal emulators seem to be *almost* what I want (stay inside Spacemacs, split window, editing commands continue to work) but then they all have weird edge cases when the terminal program is a bit complicated.

**Comment by okc0mputer** [comment]
Still needed to address this issue in 2020, the keybindings were not working on a new spaceman's install.  I added
```
(define-key cider-repl-mode-map (kbd "<up>") 'cider-repl-previous-input)
(define-key cider-repl-mode-map (kbd "<down>") 'cider-repl-next-input)
```
to my .spacemacs in order to get my desired behavior.  I like my REPL to behave like normal so the keys are bound to just the up and down keys as opposed to a Ctrl-* sequence.  I personally think this should be default behavior since most of us will want to use the REPL in this way, and others can easily modify as needed.
