### ISSUE TITLE
5-10 second pause when opening spacemacs

### ISSUE THREAD

**Issue by jamesla** [syl20bnr/spacemacs#5878]
#### Description
When I open spacemacs I get a 5-10 second pause where input is completely locked out. I get the message "Wrong type argument: sequencep, projects" in the status bar.

#### Reproduction guide
- Start Emacs
Start emacs wait

*Observed behaviour:*
UI Locks for 5-10 seconds upon opening emacs

*Expected behaviour:*
Opens fast

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git markdown osx tmux spell-checking html javascript syntax-checking)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by linhua55** [comment]
Maybe relate to http://spacemacs.org/doc/FAQ#orgheadline14

**Comment by jamesla** [comment]
thanks this did it 

(setq tramp-ssh-controlmaster-options
      "-o ControlMaster=auto -o ControlPath='tramp.%%C' -o ControlPersist=no")
