### ISSUE TITLE
(shell) in dotspacemacs/config makes initialization fail

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#588]
Steps to reproduce: Take the .spacemacs template and add the line `(shell)` to the `dotspacemacs/config` function at the bottom. Delete `~/.emacs.d/elpa`. Start Emacs, close Emacs, and then start Emacs again. Emacs will fail to initialize with this error:

```
Warning (initialization): An error occurred while loading `~/.emacs.d/init.el':

File error: Cannot open load file, no such file or directory, helm-c-yasnippet

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

**Comment by syl20bnr** [comment]
It should now be possible to do it on `develop` branch.
