### ISSUE TITLE
Unable to turn on relative line numbers

### ISSUE THREAD

**Issue by jamesla** [syl20bnr/spacemacs#5880]
#### Description
I'm relative line numbers won't turn on using the below configuration option:

`dotspacemacs-line-numbers 'relative

#### Reproduction guide
- Start Emacs
- REPRODUCTION STEPS

set dotspacemacs-line-numbers  to 'relative

*Observed behaviour:*
No line numbers at all (even non relative).

*Expected behaviour:*
Relative line numbers appear.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git markdown osx tmux spell-checking html javascript syntax-checking version-control)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by NJBS** [comment]
Does attempting to toggle them on manually work/produce any error messages?

`SPC t n` followed by `SPC t r`

**Comment by jamesla** [comment]
yes sorry I should have menioned it works fine doing it manually

**Comment by StreakyCobra** [comment]
I just tried and it works as expected. Can you try to [enable debug](https://github.com/syl20bnr/spacemacs/wiki/Debugging#enable-debug-at-initialization) and see if you can have a backtrace? Or also look in the `*Messages*` buffer for messages about this?

Also just to be sure, the line numbers will only be set in `prog-mode` and `text-mode` derived modes, so buffers like the home buffer or the messages one will not have them enabled.

**Comment by jamesla** [comment]
Ok thank you I didn't know about debug mode and that told me that I had a bad line in my config and when I removed that relative line numbers started working. Thanks StreakyCobra.
