### ISSUE TITLE
vinegar/dired-diff is not working

### ISSUE THREAD

**Issue by dvzubarev** [syl20bnr/spacemacs#5883]
#### Description
vinegar/dired-diff is not working in any dired buffer

#### Reproduction guide
- Start Emacs
- open any dired buffer
- Spc-h-d-k =

*Observed behaviour:*
= runs the command dired-diff

*Expected behaviour:*
= runs the command vinegar/dired-diff

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp vinegar)
```

It seems it works in the develop branch.
It started to work when i reverted  54a978c commit.

**Comment by StreakyCobra** [comment]
This commit was a fix for a bug introduced in `develop`, not sure it should have reached `master`.

**Comment by houli** [comment]
Any news on a hotfix for this? Even the most basic of commands like `-` aren't working.

**Comment by StreakyCobra** [comment]
I pinged @syl20bnr in https://github.com/syl20bnr/spacemacs/commit/54a978c8e2a38698bbcd1ff080520da96b30b9b3, let's try again here :-)

**Comment by syl20bnr** [comment]
Thanks guys, Backported to 0.105.21
