### ISSUE TITLE
Is there some thing like template mode in spacemacs?

### ISSUE THREAD

**Issue by DelightRun** [syl20bnr/spacemacs#5886]
How can I create new file from some template, just like template mode?

**Comment by cpaulik** [comment]
I don't know about template mode but you could use `yasnippet` for that. For example I have a [snippet](https://github.com/cpaulik/dotfiles/blob/master/.spacemacs-config/snippets/python-mode/pytesmo_license) that inserts a specific license text in python mode with the current year pre-filled.

**Comment by DelightRun** [comment]
Thanks for your reply, I'll take a look at that

**Comment by YasuharuIida** [comment]
I use `yatemplate` ([here](https://github.com/mineo/yatemplate)) for that.
This template file is like yasnippet's snippet.
