### ISSUE TITLE
[Documentation] Tables of contents header links

### ISSUE THREAD

**Issue by mathpunk** [syl20bnr/spacemacs#5890]
The table-of-contents links in the Spacemacs readme, and in most or all configuration layers, link to Github 404 pages. For example, the table of contents in the gtags layer for GNU Global should go to  https://github.com/syl20bnr/spacemacs/tree/master/layers/gtags#gnu-global and instead it links to https://github.com/syl20bnr/spacemacs/blob/master/layers/gtags/GNU%20Global

Now that am comparing the two, it is evident that the problem is that '#' symbol. Perhaps this is a bug in org-mode export, then?

**Comment by mathpunk** [comment]
The problem is similar but different on the export of the main README.org file for the Spacemacs documentation. For example:

Should be: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#searching
Is instead: https://github.com/syl20bnr/spacemacs/blob/master/doc/Searching which 404s.

**Comment by mathpunk** [comment]
Mind you, I also just this minute discovered how to search Spacemacs documentation using helm, which is significantly better than browsing on Github! Perhaps the two ways of searching documentation are irreconcilable.

**Comment by StreakyCobra** [comment]
Thanks for reporting. If you can collect all links to the problematic READMEs you found in a list it would be help people to tackle this issue :-)

**Comment by mineo** [comment]
Seems related to #3797.

**Comment by mathpunk** [comment]
Thank you, I think that settles the issue.

**Comment by StreakyCobra** [comment]
Not sure if this shouldn't be addressed anyway. CC @JAremko
