### ISSUE TITLE
Flycheck refuses to change JavaScript linter to standard

### ISSUE THREAD

**Issue by howdoicomputer** [syl20bnr/spacemacs#5892]
#### Description
I can't change the flycheck linter for JavaScript.

#### Reproduction guide
- Start Emacs
- Make sure that `standard` is installed and part of the $PATH
- `SPC e s` to select `standard` for a buffer
- Still get linting errors (ex: semicolons at the ends of statements are marked)

*Observed behaviour:*
Linting errors displayed by flycheck

*Expected behaviour:*
No linting errors if flycheck is told to explicitly use a specific linter

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(shell puppet osx dockerfile github emacs-lisp git markdown syntax-checking auto-completion erlang elixir colors javascript react fsharp yaml ruby php java ruby-on-rails python org clojure haskell go rust java version-control)
```

I've tried disabling JSHint.

```
The following checker is explicitly selected for this buffer:

  javascript-standard
    - major mode: `js2-mode' supported
    - predicate:  t
    - executable: Found at /Users/doctordoom/.nodenv/shims/standard

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.
```

But I'll get 'missing ; after statement' linting errors for pieces of code similar to this:

```
var express = require('express')
var router = express.Router()

/* GET home page. */
router.get('/', function (req, res) {
  res.render('index', { title: 'Calidrought' })
})

module.exports = router
```

**Comment by howdoicomputer** [comment]
Oh, the problem doesn't seem to be with flycheck but with the JavaScript mode overriding syntax checking.

**Comment by howdoicomputer** [comment]
Toggling javascript mode fixed the problem, huh.

**Comment by x-ji** [comment]
Actually it's caused by `js2-mode` which is different from Javascript mode. If you run `M-x javascript-mode` it will switch to `javascript-mode` instead of `js2-mode` which has some other functionalities. The way to turn of `js2-mode` warning is `SPC m w`.
