### ISSUE TITLE
coffee-script doestn't auto complete

### ISSUE THREAD

**Issue by huaoguo** [syl20bnr/spacemacs#5896]
#### Description

CoffeeScript doesn't auto complete
#### Reproduction guide
- Start Emacs
- Open a .coffee file
- write code

_Observed behaviour:_
doesn't have auto completion support

_Expected behaviour:_
has auto completion support
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp javascript git markdown react org clojure yaml)
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment]
Yes, there's no company backend for coffeescript. If you find one, do let us know.

**Comment by huaoguo** [comment]
When I M-x invoke company-mode in coffee file, it realy works. So I think company-mode has support it, we just need to enable it?

**Comment by TheBB** [comment]
You're getting the basic autocompletion then, I believe, not semantic. Not sure how useful that is, since it's pretty straightforward and knows nothing of the language you're writing.

**Comment by huaoguo** [comment]
If you write coffeescript,you will know it is useful.

**Comment by syl20bnr** [comment]
We can add company to the coffeescript hook then.

**Comment by huaoguo** [comment]
Cool @syl20bnr

**Comment by JuanCaicedo** [comment]
On the latest develop, I see company-disabled with coffescript by default. How do I add it to the coffeescript hook like you mentioned @syl20bnr ? Or should it already be enabled by default and I'm seeing a bug?

**Comment by sdwolf** [comment]
@JuanCaicedo let me know if #8365 fixes your problem.

To check out my branch execute the following commands:
```bash
cd ~/.emacs.d
git remote add sdwolf https://github.com/sdwolf/spacemacs.git
git fetch sdwolf feature/coffee-dumb-autocomplete
git checkout feature/coffee-dumb-autocomplete
```

**Comment by JuanCaicedo** [comment]
@sdwolf Thanks for the step by step instructions! I'll comment on your PR
