### ISSUE TITLE
vi-tilde-fringe-mode: Symbol's function definition is void: define-fringe-bitmap

### ISSUE THREAD

**Issue by kangjianbin** [syl20bnr/spacemacs#5897]
I am using a emacs configured without X (--without-x), and spacemacs report this error when booting.
I can't use (SPC h I) to report the issue, as this key is undefined.

**Comment by StreakyCobra** [comment]
Will probably be solved by https://github.com/syl20bnr/spacemacs/pull/5858

**Comment by rgrinberg** [comment]
@kangjianbin could you verify if your issue is fixed? The PR that @StreakyCobra mentioned has been merged.

**Comment by d12frosted** [comment]
Possibly fixed in master. @kangjianbin let us know if it's still occurs.
