### ISSUE TITLE
spacemacs/sync-configuration-layers searches for layers in old path

### ISSUE THREAD

**Issue by dwang20151005** [syl20bnr/spacemacs#5903]
#### Description
When `spacemacs/sync-configuration-layers` checks that all layers can be found, it looks for them in the directories of the current (not updated) value of `dotspacemacs-configuration-layer-path`.

A workaround is to update `dotspacemacs-configuration-layer-path`, sync, then update `dotspacemacs-configuration-layers`.

#### Reproduction guide
- Start Emacs
- Add a directory D to `dotspacemacs-configuration-layer-path`
- Add to `dotspacemacs-configuration-layers` a layer L that is stored in D
- Call spacemacs/sync-configuration-layers

*Observed behaviour:*
The `*dotfile-test-results*` buffer appears and it shows a test failure because layer L cannot be found.

*Expected behaviour:*
The sync should succeed.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.13
- Spacemacs branch: chrome-layer-plain-text-gmail (rev. 107b53f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip t)
 (chrome :variables chrome-gmail-rich-text-format nil)
 emacs-lisp
 (jane :variables jane-jane-elisp-path "/usr/local/home/dwang/workspaces/jane/emacs/dev/spacemacs/jane-tweaks/rewrite/ share /app/emacs/" Omake\.Server\.program "/j/office/app/emacs/prod/jane-elisp/bin/build-manager")
 markdown org sql
 (version-control :variables version-control-diff-tool 'diff-hl)
 vinegar w3m)
```

#### Backtrace
```

```

**Comment by TheBB** [comment]
I can't repro this on develop. I'm unable to see from your issue whether you have tried this on master or develop because you've reported from some private branch.

**Comment by dwang20151005** [comment]
I will try to reproduce in develop.

**Comment by dwang20151005** [comment]
Yes, you have fixed this already!  I'm sorry for the noise.  I will remember in the future to try to reproduce in develop before I open a new issue.
