### ISSUE TITLE
Web-beautify inserts strange color code text

### ISSUE THREAD

**Issue by andrew-kennedy** [syl20bnr/spacemacs#5905]
#### Description
Running web-beautify-js on any javascript code leads to a bunch of random characters being prepended to the buffer, they look like color codes of some kind.
#### Reproduction guide
- Start Emacs
- open a .js file
- run web-beautify-js
- observe weird text
*Observed behaviour:*
Screenshot, look at top of buffer

![](https://i.imgur.com/GkffhaO.png)

**Note that this happens even when running emacs with spacemacs disabled with only web-beautify. However, running js-beautify from the command line on the same file works fine, so the characters are definitely coming from emacs.**
*Expected behaviour:*
No strange color code text.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. b21c717)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(shell-scripts csv
               (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
               c-c  
               (colors :variables colors-enable-nyan-cat-progress-bar t)
               emacs-lisp emoji
               (git)
               html javascript markdown osx racket semantic syntax-checking themes-megapack
               (version-control :variables diff-hl-side 'left version-control-diff-tool 'diff-hl))
```

**Comment by syl20bnr** [comment]
There must be a command line parameter to output raw string without color codes.

**Comment by andrew-kennedy** [comment]
@syl20bnr do you mean that web-beautify must be using a parameter that is introducing color codes? Because as far as I'm aware it just calls js-beautify under the hood, which doesn't do anything with color codes.

**Comment by TheBB** [comment]
> Note that this happens even when running emacs with spacemacs disabled with only web-beautify.

So this is an upstream bug that nobody is interested in bringing to their attention. Closing.
