### ISSUE TITLE
Feature request: support realgud

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#5910]
Would it be possible/reasonable to add support for realgud?

https://www.emacswiki.org/emacs/DebuggingWithEmacs#toc3

https://github.com/rocky/emacs-dbgr

I guess it's a better debugging front-end for interacting with external debuggers than built-in(?) GUD.

**Comment by jluttine** [comment]
Realgud would probably add support for ipdb (see #5907) among other things.

**Comment by bmag** [comment]
I haven't tried realgud, but it sounds really cool :+1:

**Comment by nixmaniack** [comment]
It's really nice, I have had it before Spacemacs, seems I lost it in migration to Spacemacs!

**Comment by jluttine** [comment]
I'm trying to write a layer for realgud (my first layer ever). I'll write about my progress here so others can help/comment.

I wrote a simple (private) layer which uses realgud package. After activating the layer and restarting spacemacs, I got a loooong list of compiling errors, similar to those listed here: https://github.com/rocky/emacs-dbgr/issues/76

Is this something I should be worried about and should it be fixed or is it something normal?

**Comment by jluttine** [comment]
I'm trying to load the library as told in [the realgud instructions](https://github.com/rocky/emacs-dbgr/wiki/How-to-Use#loading-and-unloading) (`M-x load-library realgud`), but I get error: `Cannot open load file: no such file or directory`. So, I suppose the installation didn't work. Now I'm stuck.

**Comment by robbyoconnor** [comment]
Why not make a pull request ;)

**Comment by bmag** [comment]
@jluttine can you upload the layer to github so we can see and comment? As @robbyoconnor suggested, you can make a pull request and mark it as WIP

**Comment by jluttine** [comment]
Thanks for the suggestion. I made a pull request here: https://github.com/syl20bnr/spacemacs/pull/5915

**Comment by JohnLunzer** [comment]
I realize the PR is stuck but just expressing my interest in this layer.

**Comment by AndreaOrru** [comment]
+1 for this.

**Comment by pedrovanzella** [comment]
This would be great too.

**Comment by syl20bnr** [comment]
`realgud` is now part of the `c-c++` layer.

**Comment by bkudria** [comment]
@syl20bnr Why that layer? `realgud` has support for many different debuggers: https://github.com/realgud/realgud/wiki/Debuggers-Supported

**Comment by robbyoconnor** [comment]
yeah this has power beyond just c/c++...

**Comment by yubrshen** [comment]
If realgud is part of c-c++, but I need to use it with python, how can I start realgud? Without starting C++ mode, in Python mode, realgud is not available? To use, should I start C++ mode first?

**Comment by yubrshen** [comment]
Even with starting C++ mode, I still could not find realgud (by M-x realgud)

**Comment by simpsonw** [comment]
@yubrshen I couldn't find it either.  I looked in [packages.el](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/c-c%2B%2B/packages.el) for the `c-c++` layer.  @syl20bnr did realgud go missing at some point or am I just looking in the wrong spot?

**Comment by simpsonw** [comment]
@yubrshen I think you may have to check out the `develop`  branch of Spacemacs to get realgud in the `c-c++` layer.

**Comment by 9527KGG** [comment]
+1, real gud supports much more debugger that default gud.
Please add the support.

**Comment by jw-cpnet** [comment]
[realgud-lldb](https://github.com/realgud/realgud-lldb) is in MELPA now.
