### ISSUE TITLE
When opening ansi-term at startup I get function definition is void yas-minor-mode

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#592]
But after some time, (2 or 3 seconds) there are messages in the modeline saying yasnippet is loading or sth, and after that doing `SPC a s t` will load just fine... Maybe making yasnippet load at the time any term is invoked? just as yasnippet is forced to load when you do  `SPC f e d` just after you open a new emacs session

**Comment by syl20bnr** [comment]
Did you try with the last commit (not officially released 0.61.0) ?

**Comment by CestDiego** [comment]
yep

**Comment by syl20bnr** [comment]
Can you check again against `develop` branch ? I just fixed the lazy loading of helm-c-yasnippet.

**Comment by syl20bnr** [comment]
@CestDiego Do you still have the issue in 0.64.0 ?

**Comment by justbur** [comment]
@TheBB this one looks closable

**Comment by TheBB** [comment]
Yeah, I agree.
