### ISSUE TITLE
SPC-f-e-R resets the layout of all frames created with make-frame/emacsclient -c

### ISSUE THREAD

**Issue by hedning** [syl20bnr/spacemacs#5925]
#### Description
For the purposes of this bug emacsclient -c/make-frame/new-frame has the same behaviour so I'll just use make-frame in the description.

A new frame created using make-frame will inherit the layout of the last active frame if it was also created using make-frame. Subsequent calls to make-frame et. al. repeats this process. Edit: make-frame will work as intended if it's called from a frame created with 'emacsclient -c $file' if no calls to make-frame from a frame created with make-frame has been made.

Edit: The above issue is reproducible in bare emacs with persp-mode. Ie. running 'emacs --debug-init --daemon -q --execute "(progn (package-initialize) (setq persp-auto-resume-time -1) (require 'persp-mode) (persp-mode))"'. (But syncing can't be tested of course)

Calling dotspacemacs/sync-configuration-layouts will set the layout of all frames created by make-frame et. al. to the most recent inherited layout.

Reproduced using a clean .emacs.d/ and the .spacemacs template. The forked persp-mode (#4120, #4121) fixes it somehow, so doesn't reproduce in 0.105.19. Excluding perps-mode or using the fork fixes the issue in develop. But that's obviously suboptimal.

#### Reproduction guide
- Start Emacs (without an explicit file)
- change the layout in some way, eg.:
  - switch to another buffer
  - move the cursor to some point
  - create a new sub-window
  -  lets call the resulting layout layout_1
- make-frame / emacsclient -c
- modify the layout of both frames, eg:
  - switch to another buffer (buffer-2)
  - etc.
- spc-f-e-R or spacemacs/reload

*Observed behaviour:*
The new frame inherits layout_1 when created. After any modification spc-f-e-R
will reset both frames to layout_1.

*Expected behaviour:*
The new frame should inherit the active buffer not the whole layout if created with make-frame, if created with emacsclient -c the buffer should be the default buffer. (This seems to be both sane and standard emacs behaviour).
The sync should preserve the modified layouts.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. b21c717)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm emacs-lisp)
```

**Comment by StreakyCobra** [comment]
CC @bmag

**Comment by hedning** [comment]
It seems make-frame will work as intended as long as it's only called from frames created with eg. 'emacsclient -c $file'. But as soon as make-frame is called once from a frame created with make-frame, subsequent calls will start to act up. They will open with the layout of the last frame created with make-frame inherited.

Seems pretty strange, but as long as there's nothing really weird with my test setup this should be reproducible (should be pretty clean install).

**Comment by hedning** [comment]
Did some more testing with just emacs and persp-mode (think I managed to test it with the persp-mode fork before, so the problem didn't arise). The things that are testable without sync-configuration-layers are reproducible. Eg. calling make-frame from a frame created with 'emacsclient -c $file' correctly creates a single window with the just previously active buffer. If make-frame is called from a frame created with make-frame the new frame inherits the whole layout, windows and all, and if make-frame is then called from 

So a real fix needs to be applied upstream. The issue might be that `persp-mode` doesn't respect `persp-set-last-persp-for-new-frames` properly.

Spacemacs does make the issue more annoying though because syncing can end up resetting almost all your frames. So a quick fix would be nice.

Such a quick fix could be to rewrite `persp-init-frame` (ala. `helm-hide-minibuffer-maybe`) in the spacemacs-layouts layer by adding `(when persp (persp-activate persp frame new-frame))`. This fixes the issue, though I can't say for sure that it doesn't cause other problems. I could do a PR and close this issue if that's wanted.

**Comment by bmag** [comment]
@hedning can you test how #5952 affects this? It should fix the resetting of layouts on <kbd>SPC f e R</kbd>, but I'm not sure how it affects the issue you reported.

**Comment by hedning** [comment]
Thanks, that fixes the main issue indeed :).

The weird behaviour of `make-frame` and `emacsclient -c` is still there, but that's more of a problem with pers-mode, and looking at the persp-mode code it seems intended for some reason. So your PR fixes the main problem which is spacemacs related, so I'll close the issue when the PR is merged.

**Comment by hedning** [comment]
Closed this issue due to #5952.  Not sure if the weird pers-mode behavior is worth fixing in spacemacs itself.
