### ISSUE TITLE
Cannot change indentation from 4 characters to 2 characters in react-mode.

### ISSUE THREAD

**Issue by stockninja** [syl20bnr/spacemacs#5927]
#### Description
Cannot change indentation from 4 characters to 2 characters in react-mode.

Trimmed my .spacemacs to only enable the `react` layer, and only set the following values javascript indentation-related variables in `spacemacs/user-config`:
```
    (setq web-mode-code-indent-offset 2)
    (setq web-mode-indent-style 2)
    (setq js2-basic-offset 2)
    (setq js-indent-level 2)
```

No one in the Gitter channel could assist me, so I'm opening an issue.

Maybe there some secret variable I just don't know about?

#### Reproduction guide
- Start Emacs
- Open a JSX file with a .js extension.
- Indent any line using `>`.

*Observed behaviour:*
Line indents by 4 characters

*Expected behaviour:*
Line indents by 2 characters

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: nil (rev. b21c717)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(react)
```

**Comment by stockninja** [comment]
Basically the same problem as https://github.com/syl20bnr/spacemacs/issues/5923. These two issues should probably be merged ...

**Comment by StreakyCobra** [comment]
Yes it's the same. Let's close this one to focus on the other discussion.

**Comment by StreakyCobra** [comment]
Feel free to also post your information there :-)
