### ISSUE TITLE
Unable to enter into `helm-micro-state`

### ISSUE THREAD

**Issue by skebanga** [syl20bnr/spacemacs#5928]
#### Description
Can't enter into `helm-micro-state`

When in a `helm buffer`, pressing `M SPC` (as described by the docs [here](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org/#helm-micro-state)) doesn't bring up `helm micro-state`

It instead launches the Emacs right-mouse-click context menu

#### Reproduction guide
- Start Emacs
- `SPC h SPC`
- `M SPC`

*Observed behaviour:*
Emacs right-mouse-click context menu appears

*Expected behaviour:*
`helm micro-state` should be entered

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp c-c  )
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by StreakyCobra** [comment]
It's probably because you have `Alt-Space` configured in your machine to emulate right-click.

**Comment by skebanga** [comment]
You are correct - thanks!

http://ubuntuforums.org/showthread.php?t=1982405

http://unix.stackexchange.com/questions/34085/how-do-i-disable-a-keyboard-shortcut-in-gnome-shell

**Comment by skebanga** [comment]
Well that didn't work! :(

Now that I've disabled the keyboard shortcut in my Desktop Environment, pressing `M SPC` does nothing at all

**Comment by StreakyCobra** [comment]
I think in the `master` branch the `helm-micro-state` hasn't any visual indicator. It's a known issue and it has been fixed in `develop`. Try this:

* `SPC h SPC`
* `M-SPC`
* `t`

This will not enter the letter `t` but will mark the current entry.

**Comment by skebanga** [comment]
Ok, thanks - that works
