### ISSUE TITLE
Projectile search lags when using uppercase in search term

### ISSUE THREAD

**Issue by stormpat** [syl20bnr/spacemacs#593]
When working in a large project, with many files (i have over 2500 files) and doing a projectile search with ```SPC p f``` the search is very laggy when using a uppercase letter in the search.

For example i have a file called "VatModel.js" and when i search for the file with a uppercase ```VatMo...``` the search lags big time (sometimes up to 5-10 secs), but when i search with the lowercase ```vatmod..``` there is no lag at all.

This could be related to the OSX filesystem being case-insensitive, and projectile assuming its not?

Using newest spacemacs, on OSX (w. homebrew Emacs version)

**Comment by syl20bnr** [comment]
Seems to be projectile or helm related. Try deactivating fuzzy matching in your `dotspacemacs/config`:

```elisp
(setq helm-buffers-fuzzy-matching nil)
```

**Comment by TheBB** [comment]
This is unlikely to be our bug, so since this issue has aged quite a bit without discussion, I'm closing this for now.
