### ISSUE TITLE
Disable creation of .un~ and .swp in spacemacs

### ISSUE THREAD

**Issue by jamesla** [syl20bnr/spacemacs#5931]
I have looked through the documentation but can't seem to figure out how to do this. How do I disable the automatic creation of .un~ and .swp files in spacemacs?

**Comment by NJBS** [comment]
This is a Vim thing, to my knowledge Emacs shouldn't be making these files.

If you want to turn off the creation of lockfiles, which are the files that begin with a `.#` that are made in the same directory as the file you're editing, set `create-lockfiles` to `nil` in your `.spacemacs` file.

Auto-save files are created but they're saved pretty out of your way in `.emacs.d/.cache/auto-save`. You can turn these off by setting `auto-save-default` to `nil`, but they're pretty useful to have around and have saved me in a couple of tight spots.

**Comment by jamesla** [comment]
yep it was vim my bad thanks
