### ISSUE TITLE
Key binding to open file in vertical split

### ISSUE THREAD

**Issue by jamesla** [syl20bnr/spacemacs#5932]
I can't seem to find the documentation on the hotkey for opening a neotree file in a verticle split - horizontal split is working (and set to - by default).

Does anybody know what key opens a file in a new vertically split window?

**Comment by NJBS** [comment]
See [the spacemacs documentation](http://spacemacs.org/doc/DOCUMENTATION#orgheadline120) namely section 12.5.7.2.

**Comment by jamesla** [comment]
Ahhh sorry I missed that  FYI if anybody stumbles accross this it's | (pipe)

**Comment by mfaerevaag** [comment]
Has this been change since? At least the section in the docs is gone, and can't find any useful function bound to `|` (pipe)  in my environment.

**Comment by sdwolf** [comment]
I'm using current develop, `|` appears in the neotree help (press `?` while on neotree buffer) and works as expected. The documentation at [14.5.9.2 Opening files with NeoTree](http://spacemacs.org/doc/DOCUMENTATION#neotree-file-tree) lists the `|` as `open file in an vertically split window` but the font is weird and it appears split in the middle.

**Comment by mfaerevaag** [comment]
Oh you're right.. I actually didn't see the mention of neotree when asking. Was looking for something like `SPC f |` to use helm and open in split window.

**Comment by sdwolf** [comment]
Hmm... apparently can use `C-c o` to open a file in a vertical split from helm. I found this by looking in the helm help, with `C-c ?` while helm is open.

**Comment by mfaerevaag** [comment]
Ooo, thanks!! ❤️

**Comment by mooreniemi** [comment]
With `C-c o` is there a way I can split it vertically rather than horizontally?

**Comment by sdwolfz** [comment]
You can control the direction of the split by setting these two variables:

```emacs-lisp
(setq split-height-threshold 0)
(setq split-width-threshold nil)
```

Set one of them to `0` and the other to `nil` and the direction changes.
Here is the associated documentation: https://www.gnu.org/software/emacs/manual/html_node/elisp/Choosing-Window-Options.html

**Comment by mfaerevaag** [comment]
@sdwolfz I put that in my `user-config`, but unfortunatelly it didn't work. Tried both 
```lisp
(setq split-height-threshold 0)
(setq split-width-threshold nil)
```
and
```lisp 
(setq split-height-threshold nil)
(setq split-width-threshold 0)
```
Used `C-c o` from `Helm find files` to test.

**Comment by dschrempf** [comment]
Same here. From the helm buffer I have the same behavior. `split-height-treshold` and `split-width-treshold` are ignored. Whe using `find-file-other-window` the settings are honored.
