### ISSUE TITLE
Changing windows like vim (ctrl + hjkl)

### ISSUE THREAD

**Issue by jamesla** [syl20bnr/spacemacs#5933]
Does anybody know where I can find the documentation to bind the window changing hotkeys to be like vim (ctrl+hjkl)?

**Comment by NJBS** [comment]
As a disclaimer, these bindings will override already present bindings so make sure you know what you're getting rid of by using `SPC h d k`.

I would also like to add that spacemacs offers `C-w h/j/k/l` and `SPC w h/j/k/l` as bindings for navigating windows.

But if you'd like `C-h/j/k/l` instead you can add the following to your `.spacemacs` `user-config`:

``` elisp
  (define-key evil-normal-state-map (kbd "C-h") #'evil-window-left)
  (define-key evil-normal-state-map (kbd "C-j") #'evil-window-down)
  (define-key evil-normal-state-map (kbd "C-k") #'evil-window-up)
  (define-key evil-normal-state-map (kbd "C-l") #'evil-window-right)
```

**Comment by jamesla** [comment]
Ok thank you that makes sense - sorry about noob questions. I will try and get used to default (spc-w-hklj) or otherwise use your config above. Cheers.

**Comment by NJBS** [comment]
No worries :smile: 

There's a nice [gitter chat](https://gitter.im/syl20bnr/spacemacs) full of helpful people that can answer your questions in the future if you feel that they don't warrant their own issue.

**Comment by jamesla** [comment]
Ok I couldn't get used to spc w hjkl so have tried your config to make it work as ctrl+hjkl

I have tried adding the above lines but they don't work - how can I debug keys not working?

**Comment by NJBS** [comment]
You can evaluate the function after pasting it inside your `user-config` function by moving your point to the last parenthesis and hitting `SPC m e e` or `, e e`. You should see the name of the function that was just bound as the return value of the evaluation right below your mode-line.

If you get the correct return value and not some error you can check the keymap to make sure the key and function are correctly associated with one another.

In your case `SPC h d K evil-normal-state-map` and look for the binding or function name using `/`.

**Comment by zhexuany** [comment]
@NJBS  I tried adding code in `.spaceamcs` `user-config`. The new configuration does not work.

**Comment by NJBS** [comment]
@zhexuany Try
``` elisp
  (define-key global-map (kbd "C-h") #'evil-window-left)
  (define-key global-map (kbd "C-j") #'evil-window-down)
  (define-key global-map (kbd "C-k") #'evil-window-up)
  (define-key global-map (kbd "C-l") #'evil-window-right)
```

**Comment by cmccloud** [comment]
I think you'll need to define the key bindings on the evil maps rather than the global map, try:
```
(define-key evil-normal-state-map (kbd "C-h") #'evil-window-left)
...
```

**Comment by NJBS** [comment]
@cmccloud Those were the original bindings that they both said didn't work by the way :smile:

**Comment by staycreativedesign** [comment]
This should definitely be an option on .spacemacs

**Comment by zhexuany** [comment]
@NJBS  I am fine with the current key binding. Just wanna @jamesla has solution for his situation.

**Comment by jamesla** [comment]
Thanks @zhexuany and apoligies for the late reply.

Adding 

```
  (define-key global-map (kbd "C-h") #'evil-window-left)
  (define-key global-map (kbd "C-j") #'evil-window-down)
  (define-key global-map (kbd "C-k") #'evil-window-up)
  (define-key global-map (kbd "C-l") #'evil-window-right)
```

To my user-config worked - however when I open Neotree I am unable to ctrl+l to get out of it (although I can get into it). I assume that Neotree has already claimed the ctrl+l key combination, but how would I check this?

**Comment by TheBB** [comment]
You can check the binding of a key with `SPC hdk`

**Comment by jamesla** [comment]
ok Neotree has bound C-l to (recenter-top-bottom &optional ARG)

How would I override this?

**Comment by TheBB** [comment]
It's not neotree I think. The binding of `recenter-top-bottom` to `C-l` is made on line 7424 in `window.el` which is built-in in Emacs. Probably by the time you check it something has caused this file to load. It should be bound to that function in every buffer, not just neotree.

To sum up: using `global-map` for this is not a good idea. Use one of the evil maps instead (`evil-motion-state-map` for instance.)

**Comment by jamesla** [comment]
@TheBB that worked - thank you guys and closing!

**Comment by TheBB** [comment]
Great! :+1:

**Comment by cmlaverdiere** [comment]
Using the evil-motion-state-map works pretty well, but there's still a lot of modes that shadow ctrl-hjkl bindings (magit, comint, inferior-python, org-agenda, ...). Is there a better map for this? It would be a real pain to have to override each mode manually.

I've tried using the spacemacs-default-map (since SPC never seems to get shadowed), but this didn't work for me.

**Comment by paralin** [comment]
I haven't been able to figure out a way to get C-j and C-k to work properly in term mode.

**Comment by alfa07** [comment]
Tmux layer seems to be what you are looking for https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btools/tmux#what-is-this

**Comment by chongchonghe** [comment]
> @TheBB that worked - thank you guys and closing!

Is this still working? In my case after `(define-key evil-motion-state-map (kbd "C-l") #'evil-window-right)`, `C-l` does nothing but moving the cursor around like in a regular Emacs. Changing the kbd to "M-l" get the error: "Buffer is read-only: <buffer *Neotree*".

**Comment by paralin** [comment]
@chongchonghe I use this:

```
  (define-key evil-motion-state-map (kbd "s-h") #'evil-window-left)
  (define-key evil-motion-state-map (kbd "s-j") #'evil-window-down)
  (define-key evil-motion-state-map (kbd "s-k") #'evil-window-up)
  (define-key evil-motion-state-map (kbd "s-l") #'evil-window-right)

```
