### ISSUE TITLE
Typescript tide now has formatting

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#5935]
Since tide now provides formatting  ananthakumaran/tide#11  We probably can replace all this stuff https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/typescript/packages.el#L80 so we don't have to maintain the code.

**Comment by JAremko** [comment]
Also we wouldn't need the `typescript-formatter` tool .

**Comment by aindlq** [comment]
At least right now typescript-formatter is much flexible than tide formatting support, so I would wait with removal.

**Comment by JAremko** [comment]
I think I can add it as an option then. For example,  If a user has `typescript-formatter` installed the typescript layer will use it for formatting otherwise it will fallback to tide thingy.  :confused:

**Comment by JAremko** [comment]
I think we better ask BDFL @syl20bnr

**Comment by StreakyCobra** [comment]
An option would be fine.

**Comment by syl20bnr** [comment]
You can add a layer variable `typescript-formatting-tool` which takes a symbol value. Default should be the one which does not require any setup.
