### ISSUE TITLE
C-i does not work

### ISSUE THREAD

**Issue by fivethousand** [syl20bnr/spacemacs#5936]
While C-o jumps to the previous location, C-i does not jump to the next one.
Instead it does different things: In python files it changes the indent, in C code either nothing happens or "nothing to complete" is shown. Perhaps the key binding gets re-defined?

In emacs with evil-mode only (SPC q D evil), both keys are not defined.

**Comment by cpaulik** [comment]
Have you tried the `dotspacemacs-distinguish-gui-tab` variable?

```elisp
   ;; These variables control whether separate commands are bound in the GUI to
   ;; the key pairs C-i, TAB and C-m, RET.
   ;; Setting it to a non-nil value, allows for separate commands under <C-i>
   ;; and TAB or <C-m> and RET.
   ;; In the terminal, these pairs are generally indistinguishable, so this only
   ;; works in the GUI. (default nil)
   dotspacemacs-distinguish-gui-tab t
```

**Comment by fivethousand** [comment]
Wow. Didn't see that one. Thanks!

Sometimes C-o still doesn't work, but that's a different issue I still have to examine further.

**Comment by colorwin** [comment]
Is any solution in terminal? I try all solution from [here](https://stackoverflow.com/questions/1792326/how-do-i-bind-a-command-to-c-i-without-changing-tab), but not work.

**Comment by eullerborges** [comment]
@colorwin  I tried the solution mentioned [here](https://emacs.stackexchange.com/questions/17509/how-to-distinguish-c-i-from-tab) and it worked for me on the terminal using [wsltty](https://github.com/mintty/wsltty) on Windows.

`SPC-h-d-k   C-i` shows me 
~~~
<C-i> (translated from TAB) runs the command...
~~~
