### ISSUE TITLE
How to disabled the [ evil ] Plugin

### ISSUE THREAD

**Issue by DemonCloud** [syl20bnr/spacemacs#5937]
I'm a vim user. but I don't want to use vim mode in Emacs. so. how to disable or delete the **evil** plugin ,

and never install it when i open your spacemcs

**Comment by fivethousand** [comment]
SPC fed

change
dotspacemacs-editing-style 'vim

to
dotspacemacs-editing-style 'emacs

Then, SPC fs SPC q R

I don't know if that actually removes evil-mode, but at least it is then no longer enabled at startup.

**Comment by onemanstartup** [comment]
I tried to find in documentation how to disable evil in specific mode. But can't find it. I install sx.el in private layer, but spacemacs overrides all keys which bounded in sx.el. How to unmap keys for specific mode?

**Comment by cpaulik** [comment]
@onemanstartup A quick google search points to http://stackoverflow.com/questions/23798021/disabling-evil-mode-for-nav-in-emacs-or-any-read-only-buffers The first two answers should accomplish what you want.

**Comment by onemanstartup** [comment]
@cpaulik actually after googling i found out https://github.com/vermiculus/sx.el/issues/302 and i can use insert mode to trigger bindings.
I don't understand nav-mode for now :(

**Comment by DemonCloud** [comment]
@cpaulik   Thanks , final I was found a way to switch the mode on Documentation.

Spacemacs behaves like in raw Emacs using the Holy mode which configures Evil to make the emacs state the default state everywhere. Set the dotspacemacs-editing-style variable to emacs in the dotfile.

In Emacs style the leader is available on M-m. It is possible to dynamically switch between evil and holy mode using SPC t E h and M-m t E h.

**Comment by robert-zaremba** [comment]
Hi, Even when disabling the evil-mode the plugin is still there and it's loaded. Is it possible to remove it and speed up spacemacs starting?

**Comment by davidgomes** [comment]
> Hi, Even when disabling the evil-mode the plugin is still there and it's loaded. Is it possible to remove it and speed up spacemacs starting?

Would really like this, there should be a way to set the editing mode to emacs in such a way that the evil package (and all `evil-*` packages) are deleted and no longer loaded on startup.

**Comment by nixmaniack** [comment]
One of the (core) principles of spacemacs is that at any point of time you should be able to switch between `vim` style and `emacs` style. Hence `evil-*` packages will not be ever deleted instead they're part of core spacemacs. And as far as I know, core packages are protected from deletion and don't take into account disabling of packages. 

Regarding the question of loading at startup is concerned - everything that is not required is lazy loaded.

**Comment by didibus** [comment]
Agreed, I'd love to have the Evil stuff excluded, even though I'm in Holy mode, it still always tries to perform the "evelification" of shortcuts and that annoys me, slows things down and also often shows issues with it.
