### ISSUE TITLE
Configuring `flycheck-haskell` causes problems

### ISSUE THREAD

**Issue by ranjitjhala** [syl20bnr/spacemacs#594]
I was working on a layer that creates a new flycheck checker for haskell mode. 
(My layer adds a flycheck checker, but it doesn't do anything with `flycheck-haskell`.)
However, to get my layer to work I had to comment out 

```
;; (defun haskell/init-flycheck ()
;;   ;;(add-hook 'haskell-mode-hook 'flycheck-mode))
;;   (add-hook 'flycheck-mode-hook 'flycheck-haskell-setup)
;;   )
```

in `contrib/lang/haskell/packages.el` as otherwise I was getting an error `"unknown flycheck-haskell-setup"` thrown by `init.el`.  Per the suggestion of @syl20bnr I changed the above to:

```
(defun haskell/init-flycheck ()
  (add-hook 'haskell-mode-hook 'flycheck-mode)
  )

(defun haskell/init-flycheck-haskell ()
   (add-hook 'flycheck-mode-hook 'flycheck-haskell-setup)
   )
```

and that seems to work!

**Comment by syl20bnr** [comment]
Should be fixed in 0.64.0.
@ranjitjhala can you confirm ?

**Comment by ranjitjhala** [comment]
OK, I will try this and get back to you ASAP! Thanks!

On Mon, Mar 2, 2015 at 8:31 PM, Sylvain Benner <notifications@github.com>
wrote:

> Should be fixed in 0.64.0.
> @ranjitjhala <https://github.com/ranjitjhala> can you confirm ?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/594#issuecomment-76885547>.
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
@syl20bnr I still had to apply the change:

```
;; (defun haskell/init-flycheck ()
;;   (add-hook 'haskell-mode-hook 'flycheck-mode)
;;   (add-hook 'flycheck-mode-hook 'flycheck-haskell-setup)
;;   (setq flycheck-display-errors-delay 0))

(defun haskell/init-flycheck ()
  (add-hook 'haskell-mode-hook 'flycheck-mode)
  )

(defun haskell/init-flycheck-haskell ()
   (add-hook 'flycheck-mode-hook 'flycheck-haskell-setup)
   )
```

because otherwise I get an error in the "Warnings" buffer:

```
Warning (initialization): An error occurred while loading `/Users/rjhala/.emacs.d/init.el':

Symbol's function definition is void: flycheck-haskell-setup

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

**Comment by syl20bnr** [comment]
@ranjitjhala thank you for the feedback, we will fix this, or PR welcome :-)

**Comment by chrisbarrett** [comment]
Weird, that function should be autoloaded by the package system. Does putting the following at the top-level fix the warning?

```lisp
(autoload 'flycheck-haskell-setup "flycheck-haskell")
```

**Comment by jeremyjh** [comment]
I get this same error message when trying show a type (SPC m t) using the ghci-ng option. The init change mentioned by @ranjitjhala fixed this for me.

**Comment by syl20bnr** [comment]
Should be fixed in `develop`. I also put a tweak to remove the overlays from ghc-check which should improve the experience with flycheck.

**Comment by TakSuyu** [comment]
I've had flycheck improperly throw an error for TemplateHaskell https://github.com/flycheck/flycheck-haskell/issues/43

Putting this in my dotspacemacs/config ended up fixing that problem for me.
```lisp
(eval-after-load 'flycheck
    '(add-hook 'flycheck-mode-hook #'flycheck-haskell-setup))
```
This leads me to believe that https://github.com/syl20bnr/spacemacs/commit/eedc63438ae115f62a940e23d436ff122362ba7e ended up removing functionality that was present by flycheck-haskell
