### ISSUE TITLE
0.105.19 upgrade broke layout creation

### ISSUE THREAD

**Issue by ifosch** [syl20bnr/spacemacs#5943]
#### Description
Can't create new layouts

#### Reproduction guide
- Start Spacemacs 0.105.19
- Switch to new layout (SPC l 2)
- Choose yes
- Write a name for new layer

*Observed behaviour:*
Once the name is given, it fails and doesn't create anything.

*Expected behaviour:*
Should create a new layer, with given name.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults colors ibuffer spell-checking syntax-checking themes-megapack theming dockerfile shell vagrant ansible c-c   clojure emacs-lisp go ipython-notebook java javascript octave php python ruby shell-scripts sql yaml eyebrowse html markdown pandoc git github version-control org elfeed evernote search-engine emoji xkcd spotify)
```

#### Backtrace
I don't know how to capture backtrace, as soon as I try to capture it, it vanishes. Sorry, a newbie here.

**Comment by mayersj1** [comment]
Working for me here with 0.105.19

**Comment by ifosch** [comment]
Thanks for checking! Could it be a different version of perspective or eyebrowse code? I'm gonna checkout my customized configuration, but I don't think this might cause it.

**Comment by ifosch** [comment]
Cleaning configuration didn't help. I'm trying reinstall spacemacs...

**Comment by ifosch** [comment]
Reinstalling fixed my issues. Thank you @mayersj1!
