### ISSUE TITLE
 Jump in org-mode agenda view using evil 

### ISSUE THREAD

**Issue by neilhwatson** [syl20bnr/spacemacs#5944]
#### Description Jump in org-mode agenda view using evil ####

 Reproduction guide - Start Emacs - 

1. Start agenda view spc a o a
2. In agenda view 'j' to jump to a specific date.

 *Observed behaviour:* Moves cursor down
 *Expected behaviour: * Should allow use to change agenda view to a new day/week

 #### System Info - OS: gnu/linux - Emacs: 24.5.1 - Spacemacs: 0.105.19 - Spacemacs branch: master  rev. 3274e7d  - Graphic display: t - Distribution: spacemacs - Editing style: vim - Completion: helm - Layers:    elisp  emacs-lisp org  

    #### Backtrace     BACKTRACE IF RELEVANT

**Comment by nixmaniack** [comment]
This is expected behaviour for `vim` style since the buffer is [evilified](https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.org#evilified-buffers). In current situation binding would be on `J` for `org-agenda-goto-date`

**Comment by neilhwatson** [comment]
J works.  Didn't know that. Thank you.
