### ISSUE TITLE
Unable to activate package `helm-gitignore' Required package `request-0.1.0' is unavailable

### ISSUE THREAD

**Issue by favetelinguis** [syl20bnr/spacemacs#5946]
Just updated spacemacs and all packages and now I get the following error at startup:
```
Warning (emacs): Unable to activate package `helm-gitignore'.
Required package `request-0.1.0' is unavailable
```

Im running the latest on master. A known issue or something im doing wrong?

**Comment by joehillen** [comment]
Try `rm -rf ~/.emacs.d/elpa/helm-gitignore*`

**Comment by favetelinguis** [comment]
That worked fine, thanks!
