### ISSUE TITLE
react-mode doesn't have syntax highlighting for jsdoc

### ISSUE THREAD

**Issue by sdn90** [syl20bnr/spacemacs#5950]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(shell :variables shell-default-shell 'multiterm shell-default-term-shell "/bin/zsh")
```

Works when switching to js2-mode

![screen shot 2016-04-30 at 5 02 10 pm](https://cloud.githubusercontent.com/assets/2491713/14939290/5072c432-0ef5-11e6-8263-fef0f18fd773.png)

**Comment by axyz** [comment]
jsdoc syntax highlight is a js2 feature not included on js2-minor-mode used by react layer.

Also on develop we are trying to remove js2-minor from react-layer so it is probably a feature that needs anyway to be extracted from js2 and ported elsewhere.

One solution may be to include it directly on react layer, but wouldn't be a very good idea as it is a really distinct feature and should live on its own module. Probably the best idea would be to implement it on the js-doc package that is already used in develop by the react-layer.

I will fill an issue on https://github.com/mooz/js-doc to ask if it may be a viable solution.

**Comment by TheBB** [comment]
https://github.com/mooz/js-doc/issues/10
