### ISSUE TITLE
shell layer causes slowdown/redundancy in term startup

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#5954]
#### Description
When using shell layer, using fish in ansi-term causes environment PATH to be set multiple times, causing slow load times and a giant PATH.

#### Reproduction guide
- Install `fish`
- In your ~/.config/fish/config.fish, add the line:

```
set -x PATH ~/path/to/some/dir $PATH
```

- Start Emacs
- Add `shell` layer to config, and restart
- M-x `term`, then run `fish` (i.e. /usr/local/bin/fish or wherever)
- Once the shell is loaded, type `echo $PATH`

*Observed behaviour:*
The resulting path is way longer than it should be

**Comment by StreakyCobra** [comment]
Does it happen also on stock emacs?

**Comment by sooheon** [comment]
It does not. If I try with emacs -Q, the PATH in the ansi-term fish shell is as it should be.

**Comment by StreakyCobra** [comment]
Ok. I'm not using `fish` so I can't really help more.

**Comment by StreakyCobra** [comment]
Sorry wrong button :sweat:

**Comment by sooheon** [comment]
Closing in favour of #6128
