### ISSUE TITLE
Spaceline performance bug?

### ISSUE THREAD

**Issue by sebastiansturm** [syl20bnr/spacemacs#5955]
#### Description
with Emacs 25.1.50.3 (built from source, git commit 8cfd9ba…, with -O2 and gtk toolkit on Linux Mint 17.3, using the spacemacs develop branch and freshly updated packages as of May 1st 2016), I experience extremely laggy cursor motion. Just writing a single line of text into an otherwise empty text-mode buffer and scrolling back and forth causes the cursor to stutter every ~20 characters.
Disabling the modeline via t-m-t eliminates the issue; with spaceline enabled, I notice that I get on the order of 5 garbage collections for every line traversal (roughly 100 characters).

Memory profiling shows that spaceline indeed allocates a surprisingly large amount of memory (this profile only shows the cost of 1 or 2 line traversals, `command-execute` down below was caused by helm when I toggled the profiler via `helm-M-x-read-extended-command`):
```
- redisplay_internal (C function)                          19,812,999  70%
 - eval                                                    19,812,999  70%
  - spaceline--prepare                                     19,350,659  68%
   - spaceline--prepare-any                                18,402,191  65%
    - spaceline--eval-segment                              14,209,815  50%
     + mapcar                                               6,775,993  24%
     + powerline-raw                                        1,064,653   3%
     + spaceline--eval-segment                                320,340   1%
     + spaceline--segment-major-mode                          127,352   0%
     + eval                                                     5,024   0%
    + mapcar                                                1,389,412   4%
    + spaceline--get-face                                     565,504   2%
   + powerline-render                                         593,944   2%
   + powerline-width                                          349,444   1%
     powerline-fill                                             5,080   0%
+ command-execute                                           7,656,897  27%
+ winner-save-old-configurations                              686,565   2%
+ evil-repeat-pre-hook                                          8,188   0%
  sp--save-pre-command-state                                    2,112   0%
+ command-error-default-function                                2,032   0%
  internal-timer-start-idle                                     1,746   0%
+ timer-event-handler                                           1,572   0%
  ...                                                               0   0%
```

For now, I'm working around the issue by setting the garbage collection threshold to 1GB and triggering collection after 5 idle seconds:
```
  (setq gc-cons-threshold 1000000000)
  (run-with-idle-timer 5 t #'garbage-collect)
```
While this has made basic text navigation bearable again, I still find it a bit unsettling to know that spaceline is doing a lot of probably unnecessary work in the background. Could it be worthwhile to change spaceline from its current, nicely-functional style to a perhaps more efficient imperative style? Or is this performance problem completely unexpected and possibly caused by some configuration error on my side?

#### Reproduction guide
- Start Emacs
- Move the cursor around

#### System Info
- OS: gnu/linux
- Emacs: 25.1.50.3
- Spacemacs: 0.105.19
- Spacemacs branch: c-improved (rev. 1e67a11) (based on develop, with minor changes to c/c++-mode packages.el)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion
                (c-c++ :variables c-c++-enable-clang-support t c-c++-enable-irony-support t)
                colors context emacs-lisp ess evil-snipe
                (git :variables git-magit-status-fullscreen t)
                github gtags haskell html
                (latex :variables latex-enable-auto-fill nil)
                lua java javascript markdown org python ranger ruby
                (shell :variables shell-default-height 30 shell-default-position 'bottom)
                syntax-checking themes-megapack typescript typography
                (version-control :variables version-control-diff-tool 'git-gutter)
                (vinegar :variables vinegar-reuse-dired-buffer t)
                ycmd)
```

**Comment by sebastiansturm** [comment]
actually, it looks as if the memory allocated by spaceline isn't even reclaimed by `garbage-collect`; at least that's what `top` indicates, haven't checked this thoroughly. Is there a known memory leak somewhere?

**Comment by zilongshanren** [comment]
@sebastiansturm 

I have removed Spaceline and my spacemacs become more responsible 👍 

And a weird bug with Swiper also disappeared... https://github.com/abo-abo/swiper/issues/442

**Comment by syl20bnr** [comment]
Would be surprising, maybe your timer triggers only once ? 1GB is huged and not recommended, in develop we recently forced the threshold back to 800KB at the end of Spacemacs init. Before it was always set to 100MB.

**Comment by zilongshanren** [comment]
@TheBB  
I think `Spaceline` might has some performance issues and some unknown bugs..
Many of the previous laggy issues have gone, I will continue to work without Spaceline.

**Comment by StreakyCobra** [comment]
I also have performance issue since my last packages update. The code snippet proposed by @sebastiansturm is not really helping in my case, neither to toggle spaceline with `SPC t m t`. Rollbacking the packages update fixed it. I'll try to identify which update cause the issue, but as there are 33 of them…

-----

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. b772734)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(nginx asciidoc
       (auto-completion :variables auto-completion-enable-snippets-in-popup t)
       bb-git bb-latex bepo better-defaults c-c++ clojure colors command-log csv dash deft dockerfile
       (elfeed :variables rmh-elfeed-org-files
               (list "~/org/main.org"))
       encoding emacs-lisp emoji erc erlang ess evil-cleverparens extra-langs finance git github haskell html imenu-list ipython-notebook java javascript
       (keyboard-layout :variables kl-layout 'bepo)
       latex markdown mu4e no-dots ocaml org pandoc php plantuml python ranger rebox restclient ruby rust scala semantic shell shell-scripts spacemacs-helm speed-reading
       (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
       sql syntax-checking systemd themes-megapack theming typography
       (version-control :variables version-control-diff-tool 'diff-hl)
       vimscript yaml)
```

**Comment by StreakyCobra** [comment]
Hum, my performance issue is probably not related to this one. It is due to `mode-icons` , one of the package that I have in my `dotspacemacs-additionnal-packages`.

**Comment by CodeFalling** [comment]
@StreakyCobra  `mode-icons` seems laggy with so many `minor-mode` icons to replace (without spaceline)

**Comment by syl20bnr** [comment]
Relevant: https://github.com/syl20bnr/spacemacs/commit/d87491c60248288a63d50258c58e94ee90d1acf8

**Comment by syl20bnr** [comment]
I reverted back to 100MB for now, let's keep this issue open to investigate possible optimizations for spaceline.

**Comment by sebastiansturm** [comment]
@syl20bnr I don't think the timer is at fault, because I had also tried to call `(garbage-collect)` manually, with no discernible effect (should have mentioned that right away, sorry). But I didn't look too closely into overall heap growth, nor do I know how the Emacs GC actually works (perhaps `(garbage-collect)` doesn't do anything as long as actual memory usage is far below `gc-cons-threshold`)?
Anyway, I love the functionality and aesthetics of spaceline, so I'm very interested in seeing its excessive memory usage fixed. I'd be glad to help with the code, if I can, though I guess it would make sense for someone with in-depth knowledge of spaceline to take the lead.

**Comment by sebastiansturm** [comment]
for the time being, I'm trying to plaster over the issue by storing the current modeline config in a cache that is forcibly refreshed every second:
```
(defvar spaceline--cache (make-hash-table :test 'equal))
(make-local-variable 'spaceline--cache)
(defun spaceline--clear-cache () (clrhash spaceline--cache))
(run-with-idle-timer 1 t #'spaceline--clear-cache)

(defun spaceline--prepare (left right)
  "Prepare the modeline."
  (run-hooks 'spaceline-pre-hook)
  (let* ((active (powerline-selected-window-active))
         (line-face (spaceline--get-face 'line active))
         (leftkey (list evil-state left active line-face))
         (rightkey (list evil-state right active line-face))
         (lhs (or (gethash leftkey spaceline--cache)
                  (puthash leftkey
                           (spaceline--prepare-any left 'l active line-face)
                           spaceline--cache)))
         (rhs (or (gethash rightkey spaceline--cache)
                  (puthash rightkey
                           (spaceline--prepare-any right 'r active line-face)
                           spaceline--cache))))
    (concat (powerline-render lhs)
            (powerline-fill line-face (powerline-width rhs))
            (powerline-render rhs))))
```

Using `benchmark` to evaluate the following snippet:
```
(defun dotspacemacs/benchmark-spaceline ()
  (interactive)
  (profiler-start 'cpu+mem)
  (dotimes (m 20)
    (dotimes (n 40) (forward-char)
             (redisplay))
    (dotimes (n 40) (backward-char)
             (redisplay)))
  (profiler-report))
```
I obtain the following results (with two different values of `gc-cons-threshold`, always at the same position in the same buffer, same window config, etc.):
```
original, 1MB gc-threshold:
s elapsed / s GC / MB allocated by spaceline--prepare / MB allocated by redisplay
8.7 / 2.6 / 141 / 186
9.9 / 3.0 / 115 / 159
8.9 / 2.6 / 116 / 159
9.1 / 2.6 / 115 / 159

original, 100MB gc-threshold:
6.6 / 0.2 / 233 / 289
6.4 / 0.2 / 247 / 257
6.8 / 0.2 / 238 / 293
6.4 / 0.2 / 247 / 257

cached, 1MB gc-threshold:
4.19 / 0.6 / 10 / 54
4.4 / 0.7 / 11 / 56
4.2 / 0.6 / 11 / 55
4.2 / 0.6 / 11 / 55

cached, 100MB gc-threshold:
3.5 / 0 [not reported, probably no collection] / 27 / 75
3.9 / 0.15 / 32 / 77
3.8 / 0.12 / 27 / 77
3.8 / 0.12 / 32 / 78
```
So, it seems that this simple fix considerably improves performance, but it still allocates a disturbingly large amount of memory for what should be a rather simple task. It also creates some usability issues; for instance, the window/workspace number is not updated correctly when creating additional windows. Until we're ready to discuss a proper fix, I'd like to use my own version locally so I can at least resolve the most glaring usability issues. Is there a simple way to stop Spacemacs from downloading the elpa version of `spaceline` and use my local layer instead?

**Comment by sebastiansturm** [comment]
@TheBB: what are your thoughts on this? should the issue be relocated to the main spaceline repository?

**Comment by sebastiansturm** [comment]
Also:
- the window issue can be fixed by adding `(window-numbering-get-number)` to `leftkey` (but I'm sure there are still other issues)
- disabling the modeline completely reduces the benchmark runtime to 2.5s, so there's still plenty of room for further improvement

**Comment by TheBB** [comment]
@sebastiansturm I responded regarding Spaceline performance on #4552, in particular https://github.com/syl20bnr/spacemacs/issues/4552#issuecomment-217533646. I can't keep track of everywhere where this is being discussed.

**Comment by TheBB** [comment]
But in short: I'm working on a fix. It's quite involved and I don't know yet how much of an impact it will have. It'll take the form of some kind of modeline compiler and there will be some breaking changes. I can't promise when it lands since I'm fairly busy with other things too.

**Comment by sebastiansturm** [comment]
sorry, didn't notice #4552, thanks for the heads up! Great to hear that you're working on a clean solution :+1:

**Comment by TheBB** [comment]
A new and faster version of Spaceline is on MELPA now.

**Comment by sebastiansturm** [comment]
awesome, that was quick! The current version seems to be as fast as the cached version of spaceline 1, while of course being much more pleasant to use. With my simple benchmark and `gc-cons-threshold` set to the default value of 100MB, I obtain the following results (only one measurement per config this time, but these results seem to be highly reproducible anyway):

old spaceline: 6.2s execution time, 300MB allocated
old spaceline, cached: 4.2s, 100MB allocated
new spaceline: 4.2s, 180MB allocated
plain vanilla modeline (spaceline disabled): 2.5s, 42MB allocated (mostly helm-M-x overhead)
modeline disabled: 2.4s, 33MB allocated (mostly helm-M-x overhead)

I also used typometer (https://github.com/pavelfatin/typometer, settings: 300 chars, 50ms delay, native API, with intermediate pauses, period 50, length 1.000ms, async disabled) to measure editor latency; again, only once per config, which obviously makes for some pretty bad statistics, but even so the results are well in line with the above results (although one might argue that the GC spikes are now unfairly distributed):
old spaceline: min latency 5.6ms, max latency 155.7ms, avg. latency 10ms, standard dev. 9.7ms
old spaceline, cached: min 3.7ms, max 22.0 ms, avg. 9.3ms, standard dev. 4.0ms
new spaceline: min 3.8ms, max 185.1 ms, avg. 7.9ms (faster than the cached version!), SD 10.8ms
plain vanilla modeline: min 3.5ms, max 12.8ms, avg. 5.7ms, SD 2.8ms
modeline disabled: min 3.0ms, max. 100ms, avg. 7.2ms, SD 6.3ms

If there is any further potential for optimization, I guess it's probably on the powerline side of things, so thanks again for your great work!

**Comment by TheBB** [comment]
I'm going to have to check with your benchmarks myself, I think. There might still be room for optimization if there are certain segments that are worse than others. The recent update didn't touch any segment code, just the core stuff.

**Comment by sebastiansturm** [comment]
hm, I don't know. Disabling spaceline and only using powerline instead (with the `powerline-default-theme`) yields somewhat lower, but similar benchmark results (around 3.8 - 4s). Perhaps the performance purists among us might enjoy a pure-text version of spaceline that does away with bitmap graphics and uses colored UTF-8 separators instead (but that would also be the end of colored segment backgrounds I guess?).
Anyway, my personal performance issues with spaceline have been completely resolved by your recent update (at least as far as I can tell right now). Although I'd certainly enjoy any further improvements, the difference between 6ms latency and 8ms latency probably shouldn't be exaggerated.

**Comment by TheBB** [comment]
> Perhaps the performance purists among us might enjoy a pure-text version of spaceline that does away with bitmap graphics and uses colored UTF-8 separators instead (but that would also be the end of colored segment backgrounds I guess?).

You can do that now.

```elisp
(setq powerline-default-separator 'utf-8)
(spaceline-compile)
```

You can choose which symbol to use for each direction by configuring `powerline-utf-8-separator-left` and `powerline-utf-8-separator-right`. By default they use the regular powerline symbols, I believe, so you must have a powerline enabled font to use those.

**Comment by aaronjensen** [comment]
Great work @TheBB, thank you. It's faster for me as well.

**Comment by sebastiansturm** [comment]
sorry, didn't express myself clearly there. What I meant was that spaceline could alternatively assemble a plain modeline without any powerline features such as automatic padding or alignment, but with a few UTF-8 separators inbetween to slightly prettify things. But personally I wouldn't want to use that alternative as spaceline looks much nicer and is now fast enough for me.
Not even sure such an "optimization" would help in the first place. Before you dive even deeper into spaceline optimization, it might make sense to assemble a plain modeline that contains no graphics, no UTF-8 niceties but the same amount of information as spaceline that is also `eval`-ed on the fly? If that yields similar runtime/latency results as spaceline, then the only option for further speed increases might be to somehow limit the rate at which the modeline is evaluated?
