### ISSUE TITLE
Powerline doubles in size in ruby-mode

### ISSUE THREAD

**Issue by m3hr** [syl20bnr/spacemacs#596]
I have no idea why. I recreated a .spacemacs file with `dotspacemacs-configuration-layers '(auctex c-c++ clojure company-mode html git python restclient ruby smex)` (so my install feels new) enabled but I think a recent update to the ruby layer might have done this. I don't know. It's not a big deal, but thought you should know.

**Comment by syl20bnr** [comment]
Thank you the for report, it is because of the new unicode symbols introduces recently.
Can you tell me what is your OS ?

**Comment by m3hr** [comment]
This problem does not exist on Windows 8 for me, but on Ubuntu 14.10. I use source code pro as my font.

**Comment by m3hr** [comment]
This problem does not occur my very similar installation on Windows 8, but it happens on Ubuntu 14.10
