### ISSUE TITLE
disable dotspacemacs-whitespace-cleanup on certain mode

### ISSUE THREAD

**Issue by ntcong** [syl20bnr/spacemacs#5961]
Can dotspacemacs-whitespace-cleanup be disabled on certain mode. It's really useful when I programming, but I want to disable in on something like Markdown (New line = two trailing whitespace).

A toggle on cleanup/not cleanup would be fine I guess.

**Comment by TheBB** [comment]
See https://github.com/syl20bnr/spacemacs/pull/6204

**Comment by syl20bnr** [comment]
There is now a toggle thanks to TheBB
See `spacemacs/toggle-whitespace-cleanup-off` and commits https://github.com/syl20bnr/spacemacs/commit/5a4e8a3 and https://github.com/syl20bnr/spacemacs/commit/c0f19ca

**Comment by ntcong** [comment]
Great work as usual 👍

**Comment by magnetophon** [comment]
I agree it's a big improvement, but ideal would still be to turn it of automatically in certain modes.
Especially since it's only a minority of modes that need it off, you'll forget to toggle manually, and lose work.

**Comment by ntcong** [comment]
if you had a toggle, it will be easy enough to add a hook I think.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by yeonghoey** [comment]
```elisp
(defun dotspacemacs/init ()
  (setq-default
   dotspacemacs-whitespace-cleanup 'trailing
  ))

(defun dotspacemacs/user-config ()
  (add-hook 'markdown-mode-hook 'spacemacs/toggle-whitespace-cleanup-off)
  )
```
I added configurations like this, but it still enabled when I opened a markdown file.
How can I solve this problem?

**Comment by liweitianux** [comment]
Please see   #8221 .
