### ISSUE TITLE
Editing Startup Buffer

### ISSUE THREAD

**Issue by Alex-Keyes** [syl20bnr/spacemacs#5965]
I was wondering the loadpath to create the startup buffer?  I want to create something like the momentum dash (a greeting with your name, a nice quote etc.) to make things a little different when you startup emacs.  I am not sure where emacs goes to create the buffer though.  Can someone please explain this?

**Comment by JAremko** [comment]
Cool idea. It also can be something for beginners. Like "advice of the day" with some clever and obscure keybindings. Or something about Vim macros in Spacemacs or where emacs goes to create the buffer :smile:   I think it should be extensible so it will be easy to contribute an advice or an inspirational piece.

**Comment by JAremko** [comment]
https://github.com/syl20bnr/spacemacs/blob/f3c3f2f6b0475eea85ba5924ce64085983c35ef8/core/core-spacemacs-buffer.el#L110

**Comment by Alex-Keyes** [comment]
That's a great idea man!! Thanks for the info. I'll be sure to get something working in the near future and submit a pull request when it's done.

**Comment by lebensterben** [comment]
I will take on this one when I got time.
