### ISSUE TITLE
[SPC m e e] in Lisp mode runs the command slime-eval-last-sexp, which is not defined

### ISSUE THREAD

**Issue by 111lll1l1l** [syl20bnr/spacemacs#5966]
[SPC m e e] in Lisp mode runs the command slime-eval-last-sexp, which is not defined.
But there is a slime-eval-last-expression, should it be the right function?

**Comment by StreakyCobra** [comment]
It's possible, the better would be to check in upstream's commits to see if it has been changed. If yes PR welcome, should be an easy fix :-)

**Comment by sooheon** [comment]
@111lll1l1l fyi, the layer you're likely using can be found with `Spc h Spc` `slime`. You can try making changes to the config there, and if it works, make a PR.

**Comment by StreakyCobra** [comment]
PR: #5998

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
