### ISSUE TITLE
YAPF function is void

### ISSUE THREAD

**Issue by Lknechtli** [syl20bnr/spacemacs#5967]
#### Description
YAPF in python layer is broken

#### Reproduction guide
- Start Emacs
- open python file
- press `, =`

*Observed behaviour:*
messages buffer says: "command-execute: Symbol's function definition is void: py-yapf-buffer"

*Expected behaviour:*
Should execute yapf on file to format it

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-term)
                 spell-checking syntax-checking version-control python django chrome vagrant ruby ruby-on-rails javascript lua clojure bash html themes-megapack speed-reading restclient yaml rcirc)
```

**Comment by NJBS** [comment]
I can't reproduce this on `master` or `develop`.

Can you try updating your packages?

Does `.emacs.d\elpa` contain a folder called `py-yapf-*.*`?

**Comment by Lknechtli** [comment]
Looking further up in the log, I noticed this message: 
`(Spacemacs) Warning: More than one init function found for package py-yapf. Previous owner was python, replacing it with layer python.
Cannot load py-yapf
`
I'll just blow it all away and let it sort out the packages.

**Comment by Lknechtli** [comment]
huh. switching to develop fixed it.

**Comment by screamish** [comment]
I'm getting this error now (on master).

**Comment by TheBB** [comment]
@screamish From the discussion it is likely fixed on the develop branch.
