### ISSUE TITLE
How to add MELPA package (beginner)?

### ISSUE THREAD

**Issue by arvchi** [syl20bnr/spacemacs#5968]
Have been using Emacs/Spacemacs for a couple of weeks now, mainly because of org-mode, but cannot figure out how to add new packages. I am trying to install the package ox-reveal from MELPA in order to use org-reveal. I have created a new layer by using the command "<SPC> : configuration-layer/create-layer". Now I have a new folder in the "private" dir, but do not know how to proceed from here. The new created folder contains the files "README.org" and "packages.el".  I have opened both but don't really understand the instructions.

If anyone could provide a simple walkthrough on how to do this, it would be highly appreciated! I have tried to find some more information, but there is no simple guide explaining what to do in a way understandable for a novice in Emacs/Spacemacs.

Thank you in advance!

**Comment by NJBS** [comment]
If it's just a simple package there's no need to create a layer to install it.

See [this part](http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline21) of the documentation.

For a working example, take a look at my `dotspacemacs-additional-packages` in my [dotfile](https://github.com/NJBS/dotfiles/blob/master/.spacemacs#L73), and since my package autoloads its functions I can just go ahead and [bind them to keys](https://github.com/NJBS/dotfiles/blob/master/.spacemacs#L437-L441) right away. Otherwise, you would have to `(require)` your package before doing anything with it.

**Comment by cpaulik** [comment]
Have you read the [layers documentation](http://spacemacs.org/doc/LAYERS.html#orgheadline1)? If so then it would be helpful to know what information is missing there.

**Comment by arvchi** [comment]
Thanks for the replies. I have read the documentation but still cannot figure out what steps to take in order to make it work. The ox-reveal package is just a simple [file with code](http://melpa.org/packages/ox-reveal-20160224.1819.el). Where do I put this code, and how do I configure Spacemacs in order to be able to use the functions of the package? I am aware it is a really basic issue, but a step-by-step short walkthrough would be really appreciated!

@NJBS Suggests that no layer is needed. So i just have to add "dotspacemacs-additional-packages '(ox-reveal)" in my .spacemacs file and it will automatically install the package from the repository?

**Comment by 5outh** [comment]
@arvchi I was able to get this working http://blog.jenkster.com/2013/02/mapping-jk-in-emacs-evil-mode.html

by adding `key-chord` to `dotspacemacs-additional-packages`, so that is a viable option!

**Comment by cpaulik** [comment]
@arvchi Yes putting `ox-reveal` into `dotspacemacs-additional-packages` will install it. As for how to use it in a layer you can also checkout https://github.com/syl20bnr/spacemacs/pull/2958

**Comment by arvchi** [comment]
Adding "ox-reveal" to "dotspacemacs-additional-packages" worked! Thanks for the help. Not sure if I understand how it works, but good enough for now!

**Comment by StreakyCobra** [comment]
@5outh FYI you'll probably be better to use https://github.com/syl20bnr/evil-escape :-)

**Comment by StreakyCobra** [comment]
@arvchi If your problem is resloved, you can probably close the issue :smiley:

**Comment by shivams** [comment]
I would like to report that adding `ox-reveal` in `dotspacemacs-additional-packages` doesn't install it anymore. I've been trying this for days, until I figured out that `ox-reveal` has now been included in the `org-mode` layer itself. 

What I had to do was set the `org-enable-reveal-js-support` while initializing the `org` layer. 

    dotspacemacs-configuration-layers
    '(
      html
      org
       (org :variables
             org-enable-reveal-js-support t
             )
      )

But for me, including `ox-reveal` in `dotspacemacs-additional-packages` was simply not working. I don't know why.

**Comment by cpaulik** [comment]
@shivams That might be a bug in how the packages are loaded. Might be best to open a new issue.

**Comment by onenightinminhangcampus** [comment]
Where can I find a step-by-step guide to install melpa package and configure them, e.g. sr-speedbar. The documentation is just confusing for beginners.

**Comment by TheBB** [comment]
To install a MELPA package, simply add its name to the list `dotspacemacs-additional-packages` in the your ~/.spacemacs file. Restart Emacs and it should be automatically downloaded.

To configure it, you have to consult the package itself. There's simply no way to make a guide that works the same with all packages.

**Comment by anmoljagetia** [comment]
@shivams Thanks a lot! What you have suggested is the only method that worked for me! There are a lot of tutorials on the internet, but they don't work anymore, probably because of addition of ox-reveal into the org layer. Isn't it better if we add this change to README, so other *new* people don't have to undergo the pain of finding this the hard way?

**Comment by cpaulik** [comment]
I still think that this might be a bug in the package loading. Any package in `dotspacemacs-additional-packages` should be loaded even if the internal support is disabled by a layer variable. I'll investigate in the evening.

**Comment by Makohoek** [comment]
Thanks @anmoljagetia and @shivams .

I was trying to use `dotspacemacs-additional-packages` and a seperate layer for this but i could not get it to work.

@cpaulik, did you investigated this since 25 Oct?
Anyway, problem solved on my end

**Comment by achikin** [comment]
@NJBS I've read through your `.spacemacs` but still can't understand where you install `company` package.

**Comment by NJBS** [comment]
@achikin I never install the `company` package in my `.spacemacs` file using `dotspacemacs-additional-packages` as it is [already installed](https://github.com/syl20bnr/spacemacs/blob/8e1af145480d53e8d32cdff2c83291889903164b/layers/%2Bcompletion/auto-completion/packages.el#L16) by the [`auto-completion` spacemacs layer](http://spacemacs.org/layers/+completion/auto-completion/README.html). If you wish to install `company` [simply activate one of the layers](https://github.com/NJBS/dotfiles/blob/5999192dd1d0922ef4c4c32cce9d443778f2f1bc/.spacemacs#L46) that requires it by adding the layer name to your `dotspacemacs-configuration-layers` and restart your emacs.

Additionally, I've updated my original comment's links so they should point to the proper section in the dotfile now.

Feel free to drop into the [spacemacs gitter chat](https://gitter.im/syl20bnr/spacemacs) and either ask in the main channel or send me a direct message if you have any additional questions!

**Comment by ssfrr** [comment]
thanks @shivams! I'd also tried enabling `ox-reveal` by adding it to `spacemacs-additional-packages` and it didn't work (though installing from MELPA manually worked until the next restart of spacemacs). Using your configuration solved the problem.
