### ISSUE TITLE
Prevent cursor from escaping minibuffer

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#597]
So user won't accidentally move the cursor elsewhere and be confused. This can be done by setting the variable `helm-prevent-escaping-from-minibuffer`.

**Comment by syl20bnr** [comment]
Thank you @tuhdo !

**Comment by syl20bnr** [comment]
Unfortunately it is set to `t` by default. I have no reproducible step for now, so I leave this issue opened until we find one and we can try to fix it.

**Comment by syl20bnr** [comment]
I added a key binding to force focus back to the minibuffer, the commit will close this issue.
