### ISSUE TITLE
how to make the Dockerfile have  highlight ?

### ISSUE THREAD

**Issue by alexsunxl** [syl20bnr/spacemacs#5972]
#### Description
how to make the Dockerfile have  highlight ?

![](http://7xkr17.com2.z0.glb.qiniucdn.com/issue/79238C1A-685A-4F40-B100-D078235002AC.png)

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. 17fbeaf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((ranger :variables ranger-show-preview t)
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 react javascript html php auto-completion better-defaults emacs-lisp git
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking)
```

**Comment by StreakyCobra** [comment]
Just add the `dockerfile` layer :-)

**Comment by alexsunxl** [comment]
@StreakyCobra  thank you , it is very helpful
