### ISSUE TITLE
tmux navigation keybindings broken

### ISSUE THREAD

**Issue by pavelkogan** [syl20bnr/spacemacs#5975]
#### Description
After an update, tmux layer bindings for window navigation stopped working.
#### Reproduction guide
- Start Emacs
- Create windows
- Use tmux navigation keys (C-[hjkl])

*Observed behaviour:* Keys trigger functions unrelated to window navigation
*Expected behaviour:* Focus moves between windows
#### System Info
- OS: gnu/linux - Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master  rev. 3274e7d
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:    elisp  ansible auto-completion clojure emacs-lisp evil-commentary extra-langs eyebrowse  git :variables git-gutter-use-fringe t  github haskell html latex markdown org python restclient scala shell-scripts sql syntax-checking tmux unimpaired yaml

**Comment by StreakyCobra** [comment]
Related comments: https://github.com/syl20bnr/spacemacs/commit/cc78f057c423f62d8ba0de118feb98834861d15b

**Comment by aaronjensen** [comment]
Fix to master in #5977 (this is already fixed in develop due to https://github.com/syl20bnr/spacemacs/commit/33ead6fc42700a6000ef10a662ceff604f3f8e51)

**Comment by rjhilgefort** [comment]
@StreakyCobra thanks for linking to the discussion. I'll be sure to just open a pull next time to keep the conversation in one place around an issue.

**Comment by syl20bnr** [comment]
Backported to 0.105.21
