### ISSUE TITLE
auto-revert-tail-mode ignored

### ISSUE THREAD

**Issue by favetelinguis** [syl20bnr/spacemacs#5976]
Are there any confilicts with using this mode together with spacemacs?

When I open a log file and do SPC : and use auto-revert-tail-mode the cursor is not following as the file grows.

**Comment by TheBB** [comment]
I get the same behaviour as in regular Emacs: it will follow if the cursor is at the end, but not if it's somewhere in the middle.

There is nothing in the documentation about this mode that says anything about the cursor. The file itself says,

> After reverting a file buffer, Auto Revert Mode normally puts point 
at the same position that a regular manual revert would.  However,  
there is one exception to this rule.  If point is at the end of the 
buffer before reverting, it stays at the end.  Similarly if point   
is displayed at the end of a file buffer in any window, it will stay
at the end of the buffer in that window, even if the window is not  
selected.  This way, you can use Auto Revert Mode to `tail' a file. 
Just put point at the end of the buffer and it will stay there.     
These rules apply to file buffers. For non-file buffers, the        
behavior may be mode dependent.                                     

Seems this is exactly as it should be.

**Comment by favetelinguis** [comment]
Can confirm the beahvior is ok, my fault
