### ISSUE TITLE
Ctrl-W is not sent to ansi-shell or multi-shell

### ISSUE THREAD

**Issue by liujoey** [syl20bnr/spacemacs#5979]
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. 17fbeaf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(spacemacs-helm auto-completion better-defaults unimpaired emacs-lisp
                (colors :variables colors-enable-rainbow-identifiers t)
                (version-control :variables version-control-diff-tool 'diff-hl)
                (shell :variables shell-default-shell 'ansi-term)
                markdown git html scala javascript python django evil-commentary osx org org-custom syntax-checking restclient vinegar)
```

How to reproduce:
type some command in the shell, Ctrl-w to delete the command, type a new command, hit Enter. The deleted command will be run, the new command will report errors because now the new command is just treated as the parameters of the deleted command.

**Comment by sooheon** [comment]
FWIW, I'm using ansi-term in char run mode, and C-w works as expected. It deletes the word, and the text is not hidden and hanging about or anything.

**Comment by liujoey** [comment]
@sooheon I don't know there are two different mode for the shell. Thank you for the info. 
I just tested, it's funny that when I run in char mode, I have the issue as I mentioned above, when I change it to line mode, the issue disappeared. But in line mode if I run command `exit`, it doesn't close my shell, instead it shows this:

```
~/D/icon ❯❯❯ exit                                                                                                                                                                               icqa-rebas
e ✱
exit: too many arguments
~/D/icon ❯❯❯ 
```

**Comment by liujoey** [comment]
duplicate with #9844. close this one.
