### ISSUE TITLE
Spacemacs not loading editorconfig

### ISSUE THREAD

**Issue by schmittyjd** [syl20bnr/spacemacs#5980]
I have added editorconfig to additional packages and it is installed. Here is my user-config and editor config is not applying proper configurations to my files

```emacs-lisp
(setq ns-use-srgb-colorspace nil)
  (global-linum-mode nil)
  (linum-relative-toggle)
  (use-package editorconfig)
  (editorconfig-mode 1)
```
New to spacemacs, just switched from vim

**Comment by schmittyjd** [comment]
closing, solved with the help of some good people on the gitter

**Comment by tasmo** [comment]
What was the solution?

**Comment by TheBB** [comment]
https://gitter.im/syl20bnr/spacemacs/archives/2016/05/05

Here are the archives for May 5. @schmittyjd was using some unsupported syntax in his editorconfig file.

**Comment by agriffis** [comment]
FWIW the relevant discussion seems to be a day earlier:

https://gitter.im/syl20bnr/spacemacs/archives/2016/05/04
