### ISSUE TITLE
bibtex layer is not working

### ISSUE THREAD

**Issue by hemcsec** [syl20bnr/spacemacs#5985]
#### Description
bibtex layer is not working

#### Reproduction guide
- Start Emacs
- Open a BIB file

*Observed behaviour:*
- Space m is undefined

*Expected behaviour:*

#### System Info
- OS: darwin
- Emacs: 25.0.93.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. 17fbeaf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip nil)
 better-defaults bibtex chinese
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 csharp django emacs-lisp extra-langs gtags git html javascript markdown org osx
 (latex :variables latex-build-command "LatexMK")
 python shell spacemacs-helm semantic
 (spell-checking :variables spell-checking-enable-by-default nil)
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 typescript vimscript
 (vinegar :variables vinegar-reuse-dired-buffer t))
```

#### Backtrace
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by cpaulik** [comment]
I can reproduce. It seems that the keybindings are never loaded because they are in the `:config` section of use package. I've submitted a https://github.com/syl20bnr/spacemacs/pull/5986 to fix it.
