### ISSUE TITLE
Viewing docs breaks company keymappings

### ISSUE THREAD

**Issue by mmcnl** [syl20bnr/spacemacs#5992]
#### Description

Viewing docs breaks company keymappings
#### Reproduction guide
- Start Emacs
- Open a new Python junk file `SPC f J py RET`
- Starting typing the name of a function, e.g. `ma`
- Observe completion popup appearing
- Press `C-j` and `C-k` to move point up/down and change selection
- Press `C-d` to show documentation
- Press `C-j` to move point to next completion option
- Press `C-d` to show documentation

_Observed behaviour:_
- documentation window does not appear
- `C-k` closes the company popup instead of moving point up

_Expected behaviour:_
- documention window appears whenever requested with `C-d`
- `C-k` moves the point up even after viewing documentation
#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. 9502ed1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory nil)
 csv dash emacs-lisp fasd
 (git :variables git-magit-status-fullscreen t)
 github html ipython-notebook javascript markdown org osx pdf-tools
 (python :variables python-test-runner 'pytest)
 ruby
 (spell-checking :variables spell-checking-enable-by-default nil)
 sql syntax-checking terraform
 (theming :variables theming-headings-inherit-from-default 'all theming-headings-same-size 'all theming-headings-bold 'all)
 version-control yaml)
```

**Comment by TheBB** [comment]
Interestingly, `C-h` doesn't seem to be afflicted (it still ruins `C-k` but it works several times).

**Comment by olejorgenb** [comment]
PS: This is not specific to python-mode/layer in my experience. It affects lisp-mode too at least.
