### ISSUE TITLE
Tern binary not found

### ISSUE THREAD

**Issue by anthonybrice** [syl20bnr/spacemacs#5993]
#### Description
Spacemacs reports the warning `(Spacemacs) Warning: tern binary not found!` even though my Emacs path is configured with the location of the tern binary.

#### Reproduction guide
- Ensure you have tern installed in a location referenced by your Emacs path
- Start Emacs
- Enable a layer that uses tern. I use the javascript layer, but another user on Gitter has reported the same issue with web-mode
- Open a javascript file

*Observed behaviour:*
- Receive the following message: `(Spacemacs) Warning: tern binary not found!`
- tern-mode is disabled

*Expected behaviour:*
- Emacs finds the tern binary
- tern-mode is enabled

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown org spell-checking syntax-checking themes-megapack colors
                 (latex :variables latex-enable-auto-fill t latex-build-command "LaTeX")
                 semantic cscope elm haskell html sql pandoc javascript)
```

#### Backtrace
Here's the trace when I try to enable tern-mode manually. 
```
Debugger entered--Lisp error: (file-error "Searching for program" "no such file or directory" "tern")
  start-process("Tern" nil "tern" "--strip-crs")
  apply(start-process "Tern" nil ("tern" "--strip-crs"))
  tern-start-server(#[514 "...
  tern-find-server(#[514 "...
  tern-run-request(#[514 "...
  tern-send-buffer-to-server()
  tern-mode-enable()
  tern-mode(toggle)
  call-interactively(tern-mode record nil)
  command-execute(tern-mode record)
  helm-M-x(nil "tern-mode")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

```

**Comment by rakkesh** [comment]
> Ensure you have tern installed in a location referenced by your Emacs path

where is `tern` installed, and does that path exist in the output of `(getenv "PATH")`?

**Comment by anthonybrice** [comment]
Tern is installed in `/home/anthony/.npm-global/bin`. `(getenv "PATH")` returns:
```
"/home/anthony/bin:/home/anthony/.cabal/bin:/home/anthony/.local/bin:/home/anthony/.npm-global/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
```

But I think I just found my answer. I need to add `/home/anthony/.npm-global/bin` to my `exec-path` to use tern, not Emacs' PATH environment variable.

Here's a page from the Emacs wiki for reference: https://www.emacswiki.org/emacs/ExecPath

**Comment by d12frosted** [comment]
Please, fire PR with this info to corresponding part of FAQ (where we tell
how to setup PATH).

P. S. Glad you found solution :)

~ d12frosted

**Comment by motecshine** [comment]
I met the same problem. 

System : macOS (10.12.2)
Branch : master
Emacs : 25.1
* tern PATH 

![image](https://cloud.githubusercontent.com/assets/7615270/22158435/235eb354-df77-11e6-8ae0-f4e385e1e2df.png)

* Here are my ways to solve it
   set exec path in your .spacemacs user/init

```
 (setenv "PATH" (concat (getenv "PATH") ":/usr/local/bin"))
 (setq exec-path (append exec-path '("/usr/local/bin")))
```

**Comment by sr105** [comment]
@motecshine 's solution worked for me, but I'm not sure why it was necessary since my exec-path contains /usr/local/bin after Emacs has completed starting up. My guess is that the tern binary is being looked for before exec-path is setup.

**Comment by liuchong** [comment]
(setenv "PATH" (concat "[MY_HOME_DIR]/.nvm/versions/node/v7.7.1/bin:" (getenv "PATH")))
(add-to-list 'exec-path "~/.nvm/versions/node/v7.7.1/bin")

still warning after the above two lines, tern is installed

**Comment by sangjeedondrub** [comment]
I installed `tern` in `/opt/node/bin`, even though I exported this dir to $PATH in my .zshrc, but emacs somehow were not able to locate the binary.
@motecshine 's method works for me too.
```e-lisp
;; 用户代码的初始化函数
;; 在spacemacs/init 之后立即执行 (在用户自定义配置层之前)
(defun dotspacemacs/user-init ()
  ;; fix Tern binary not found issue, even if tern is installed by running npm install tern -g
  (setenv "PATH" (concat (getenv "PATH") ":/opt/node/bin"))
  (setq exec-path (append exec-path '("/opt/node/bin")))
```
