### ISSUE TITLE
request-0.1.0 is not available

### ISSUE THREAD

**Issue by otwieracz** [syl20bnr/spacemacs#5995]
#### Description
Problem while installing request@spacemacs-base (package is unavailable)

#### Reproduction guide
- Start Emacs
- Notice error

*Observed behaviour:*
```
Found 1 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: request@spacemacs-base... [1/1]

[311 packages loaded in 9.845s]
```

```
buffer *Warning*
Warning (emacs): Unable to activate package `helm-gitignore'.
Required package `request-0.1.0' is unavailable
```

*Expected behaviour:*
Clean start

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(better-defaults emacs-lisp git org
                 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
                 version-control common-lisp themes-megapack spell-checking syntax-checking react latex restclient
                 (c-c   :variables c-default-style "bsd" c-basic-offset 4)
                 (auto-completion :variables auto-completion-enable-help-tooltip t))
```

**Comment by NJBS** [comment]
Can you try deleting the `emacs.d/elpa/helm-gitignore*` folder and restarting?

Additionally, if that doesn't work can you try deleting `emacs.d/elpa` entirely and restarting emacs with the `--insecure` flag?

(duplicate of https://github.com/syl20bnr/spacemacs/issues/5523)

**Comment by otwieracz** [comment]
Thanks, this resolves this issue.
