### ISSUE TITLE
SPC SPC is undefined on latest develop

### ISSUE THREAD

**Issue by aldanor** [syl20bnr/spacemacs#5999]
After pulling the most recent `develop` today, `SPC SPC` is no longer working (`M-x` still does):

```
SPC SPC is undefined
```

#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. 78f11f4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 csv deft emacs-lisp eyebrowse
 (git :variables git-magit-status-fullscreen t magit-save-repository-buffers 'dontask magit-revision-show-gravatars nil)
 (github :variables gh-profile-default-profile "aldanor")
 html javascript ipython-notebook markdown org
 (python :variables python-fill-column 99 python-test-runner 'pytest)
 rust search-engine
 (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t)
 shell-scripts spacemacs-helm syntax-checking themes-megapack theming version-control yaml aldanor)

**Comment by StreakyCobra** [comment]
I can't reproduce on `develop` (same revision as you) + packages updated.

**Comment by aldanor** [comment]
Interesting, I can't reproduce it either on my Mac with *exactly* the same config, the same develop revision etc. Wonder why could it be suddenly messed up on Windows? Will confirm on Monday.

**Comment by WillianPaiva** [comment]
I'm on linux and have the same problem

**Comment by aldanor** [comment]
Ok so it's not just me then. How do we reproduce this though?

**Comment by StreakyCobra** [comment]
FWIW I also tried a totally fresh install (i.e. no `.spacemacs`, fresh `.emacs.d` on `develop`) and it's working as expected.

**Comment by WillianPaiva** [comment]
i did this change on my version and it works now 

https://github.com/syl20bnr/spacemacs/pull/6009

**Comment by TheBB** [comment]
@WillianPaiva That is not likely the correct solution. The key binding is set here: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+completion/spacemacs-helm/packages.el#L225

You should probably check if you have any errors reported in `dotspacemacs/user-config` which prevents this hook from running as expected.

Also check if your `dotspacemacs-emacs-command-key` is indeed set to `SPC`.

**Comment by aldanor** [comment]
@TheBB Here's my entire config: https://github.com/aldanor/.spacemacs.d, and `dotspacemacs-emacs-command-key` is set to `SPC` there.

**Comment by NJBS** [comment]
@aldanor Can you verify the variable is correct set via `SPC h d v`?

Additionally, can you try changing your command-key to a different key and seeing if the issue persists?

**Comment by StreakyCobra** [comment]
Maybe some versions are not running the `emacs-startup-hook` ?

**Comment by WillianPaiva** [comment]
my case was the command key thanks

**Comment by aldanor** [comment]
After restarting Emacs a few more times, the problem seemed to correct itself, I think there was something in the messages log about recentf and a void function, maybe something was preventing the hook from working.

**Comment by nietaki** [comment]
I had the exact same problem, and the variable was set correctly.
After restarting a bunch of times and re-enabling org layer (the lack of which was giving me some warnings in the messages, but probably it's unrelated) it fixed itself
