### ISSUE TITLE
Develop spacemacs function to update spacemacs

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#60]
For people following a certain branch, we need a function that will update spacemacs,  this should both update the repo to the latest checkout, but also update all extension level submodules.  

Perhaps also integrate this in startup, so in addition to adding packages, we also update submodules.  The latest switch for `nerd-commenter` as an extension was missed in my setup when I just did a `git pull`

**Comment by syl20bnr** [comment]
We have Update of the packages. Update of spacemacs repo is on the way.
I close this since the function is here but need improvements.
