### ISSUE TITLE
HiDPi Support

### ISSUE THREAD

**Issue by ruuda** [syl20bnr/spacemacs#6005]
#### Description
When I tried Spacemacs, suddenly everything looked tiny. The regular Emacs looked fine. I use a HiDPi desktop environment (Gnome 3).

#### Reproduction guide
- Clone the repository to `~/.emacs.d`.
- Ensure that `~/.emacs` does not exist.
- Start Emacs.

*Observed behaviour:*
All text is tiny. The size is likely correct for low-dpi monitors, but not for my high-dpi setup. Note that plain Emacs worked fine (not too small text size) out of the box. See also the screenshot. For comparison I added Vim, which has a decent text size.

![spacemacs](https://cloud.githubusercontent.com/assets/506953/15081077/3b39b262-13c1-11e6-8c35-b120b5244f4c.png)

*Expected behaviour:*
Text should be legible. On a high-dpi screen that means more pixels to get the same size.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

**Comment by emidln** [comment]
I have a 3840x2160 resolution on a 15.6" screen. I use `:size 28` and
:powerline-scale 1.6`in my dotspacemacs-default-font config inside
.spacemacs and dospacemacs/init.

**Comment by abcdw** [comment]
Commented `:size` keyword and set org.gnome.desktop.interface scaling-factor 2.
It's work for me.

```
   dotspacemacs-default-font '("Ubuntu Mono"
                              ;; :size 18
                              :weight normal
                              :width normal
                              :powerline-scale 1.1)
```

**Comment by jody-frankowski** [comment]
I have the same problem with a 3840x2160 screen. If I disable the size attribute, emacs automatically selects size 22. Shouldn't the size attribute be disabled by default and let emacs figure out the best one base on scaling factors?

**Comment by d12frosted** [comment]
Question was answered.

**Comment by Pastafarianist** [comment]
@abcdw's solution works with the default Source Code Pro as well.

```
   dotspacemacs-default-font '("Source Code Pro"
                              ;; :size 18
                              :weight normal
                              :width normal
                              :powerline-scale 1.1)
```

**Comment by spazm** [comment]
Setting size with a _floating point value_ uses point values which scale with display resolution scaling.

Thank you to whomever updated the documentation comments in the `.spacemacs` file:

>    ;; Default font or prioritized list of fonts. The `:size' can be specified as
   ;; a non-negative integer (pixel size), or a floating-point (point size).
   ;; Point size is recommended, because it's device independent. (default 10.0)

I have just set mine to a lovely 15.0 with source code pro, which gives me an 80 column window when using 1/2 my 4K screen.
