### ISSUE TITLE
[DOC] dead "How To" links

### ISSUE THREAD

**Issue by nelson-liu** [syl20bnr/spacemacs#6006]
I was looking over the quick start, and noticed that the link to howtos.org (removed in https://github.com/syl20bnr/spacemacs/commit/0fb5e2403973209a065e7167dc1c721e0ce6a974) still pointed to the original location (see [the quick start](https://github.com/syl20bnr/spacemacs/blob/master/doc/QUICK_START.org#how-tos)).

Additionally, the links in the [FAQ](https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org) seem to be broken.

Thanks!

**Comment by StreakyCobra** [comment]
I think all these issues have been fixed in the `develop` branch. Can you check this?

**Comment by nelson-liu** [comment]
indeed they are, sorry for the noise!
