### ISSUE TITLE
Helm M-x has no key binding

### ISSUE THREAD

**Issue by TheSeldonPlan** [syl20bnr/spacemacs#6007]
#### Description
The key binding that maps to `helm M-x` has dissapeared after removing my .emacs.d and cloning the spacemacs repo from scratch. 
 
#### Commands run:
`git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`

#### Reproduction guide
- Start Emacs

*Observed behaviour:*
No spacemacs leader keys for `helm M-x` after pressing SPC.

*Expected behaviour:*
`Spc :` Should map to `helm M-x`.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(auto-completion clojure emacs-lisp git html javascript markdown org osx ruby ruby-on-rails scheme spell-checking syntax-checking yaml my-config)
```

#### Messages Buffer
*All other modes load normally*
Loading /Users/Kenny/.spacemacs.d/my-config/config.el (source)...
Loading /Users/Kenny/.spacemacs.d/my-config/customizations/ui.el (source)...done
Loading /Users/Kenny/.spacemacs.d/my-config/customizations/navigation.el (source)...done
Loading /Users/Kenny/.spacemacs.d/my-config/customizations/editing.el (source)...done
Loading /Users/Kenny/.spacemacs.d/my-config/customizations/misc.el (source)...done
Loading /Users/Kenny/.spacemacs.d/my-config/other-modes/my-workflow.el (source)...done
Loading /Users/Kenny/.spacemacs.d/my-config/language-modes/base.el (source)...done
Loading /Users/Kenny/.spacemacs.d/my-config/language-modes/clojure.el (source)...
Cannot load clojure-mode
Loading /Users/Kenny/.spacemacs.d/my-config/language-modes/clojure.el (source)...done
Loading /Users/Kenny/.spacemacs.d/my-config/config.el (source)...done
*All other packages load normally*
Loading /Users/Kenny/.spacemacs.d/my-config/packages.el (source)...done
You appear to be setting environment variables ("PATH") in your .bashrc or .zshrc: those files are only read by interactive shells, so you should instead set environment variables in startup files like .profile, .bash_profile or .zshenv.  Refer to your shell's man page for more info.  Customize `exec-path-from-shell-arguments' to remove "-i" when done, or disable `exec-path-from-shell-check-startup-files' to disable this message.
smooth-scrolling enabled.
(Spacemacs) Warning: tern binary not found!
Starting new Ispell process /usr/local/bin/aspell with default dictionary...
Spacemacs is ready.
Start checking for new version...
cond: Symbol's function definition is void: async-start
Symbol's function definition is void: async-start
avy-handler-default: No such candidate, 127
avy-handler-default: No such candidate, 32
SPC : is undefined

#### Help Buffer
SPC SPC runs the command evil-avy-goto-word-or-subword-1, which is an
interactive compiled Lisp function in `evil-integration.el'.

It is bound to SPC SPC, M-m SPC.

(evil-avy-goto-word-or-subword-1 &optional COUNT)

Evil motion for `avy-goto-word-or-subword-1'.

#### Backtrace
None.

**Comment by NJBS** [comment]
@FrozenInc was experiencing this issue as well but we were unable to reproduce it after switching to the `master` branch.

See discussion in gitter https://gitter.im/syl20bnr/spacemacs?at=5728eee40149d6bb04b85e52

**Comment by StreakyCobra** [comment]
This issue may be a duplicate of https://github.com/syl20bnr/spacemacs/issues/5999 actually

**Comment by StreakyCobra** [comment]
I also tried a totally fresh install (i.e. no `.spacemacs`, fresh `.emacs.d` on `master`) and it's working as expected.

What's your value of the following variables:

- `dotspacemacs-leader-key`
- `dotspacemacs-emacs-leader-key`
- `dotspacemacs-emacs-command-key`

**Comment by TheSeldonPlan** [comment]
Resolution was to blow away my emacs.d and clone again.
