### ISSUE TITLE
Need to press Enter twice in eshell

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#6008]
#### Description

Sometimes you need to hit Enter twice in eshell.  I think it might be related to
autocompletion.
#### Reproduction guide
- Start Emacs
- Start eshell
- Type `ls`
- Press Enter.

_Observed behaviour:_
Nothing happens.

Pressing Enter twice runs the command normally.  Typing `ls` followed by `<C-g>`  followed by Enter also works normally.  Typing `ls` followed by a space, followed by Enter also works normally.

_Expected behaviour:_
`ls` command runs
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. b772734)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:

``` elisp
(spacemacs-ivy spacemacs-layouts
               (auto-completion :variables auto-completion-enable-sort-by-usage t)
               better-defaults gtags ibuffer spell-checking syntax-checking semantic typography
               (chrome :variables edit-server-new-frame nil)
               dash elfeed finance mu4e org
               (shell :variables shell-default-shell 'eshell shell-default-term-shell
                      (mir/with-executable "/usr/local/bin/fish" "/usr/bin/fish" "/bin/bash" "/bin/sh")
                      shell-default-height 50)
               prodigy restclient version-control git c-c   common-lisp csv emacs-lisp go html javascript latex lua markdown python ruby shell-scripts sql yaml django mir-bbdb mir-magit-annex mir-pass mir-remind-to-diary mir-rc mir-rc-org mir-rc-qualia mir-rc-mu4e mir-rc-mail)
```

**Comment by darkfeline** [comment]
Disabling autocompletion (`SPC t a`) makes this behavior go away.

**Comment by darkfeline** [comment]
This problem becomes clearer if you switch `company-preview-frontend` in the `shell` layer to `company-pseudo-tooltip-frontend` for `eshell`.

When I type `pwd`, there are actually two candidates, `pwd` and `pwdx`, however nothing displays with `company-preview-frontend` so Company is in an "invisible" completion state.  The first Enter exits the completion, and the second actually submits the command.

This is probably more easily reproduces with `ls`, which shares a prefix with `lscpu`, `lsmod` which are more commonly available than `pwdx`.

**Comment by TheBB** [comment]
I can't reproduce this. I do get a completion popup, but only a single enter is needed to exit the completion and run the command.

**Comment by darkfeline** [comment]
@TheBB Are you using company?

With the default Spacemacs setup, a single enter only completes and doesn't run the command.  This makes sense since usually you may want to type additional arguments before running a command.

![eshell](https://cloud.githubusercontent.com/assets/855210/15699380/5210d956-2781-11e6-8f89-8530e2c7c534.png)

However, if you type something like `ls`, with the default setup there is no indication that a completion is in progress, and the first enter exits completion invisibly.

**Comment by teaforthecat** [comment]
I'm seeing this too, and have changed the variables as suggested by @TheBB to: 
```emacs-lisp
(auto-completion :variables
                 auto-completion-return-key-behavior nil
                 auto-completion-tab-key-behavior 'complete)
```
Now I don't have to hit enter twice. As an added bonus, if I hit tab twice I get a popup of all the completions (in eshell).

**Comment by darkfeline** [comment]
I'm not really fond of that workaround.  I think this should be fixed upstream in company now that I know what's causing it.  `company-preview-frontend` should handle the special case by sending whatever is bound to `RET`.

**Comment by rgrinberg** [comment]
@darkfeline Did you make a ticket upstream? I agree that this seems to be something that company should handle properly without any help from spacemacs.
