### ISSUE TITLE
Proper way to change cursor color?

### ISSUE THREAD

**Issue by aminb** [syl20bnr/spacemacs#601]
I have 2 questions:

1. What's the proper way to change the cursor color (defined [here](https://github.com/syl20bnr/spacemacs/blob/a654bf6d55b48689938ac19527de2449bc58de67/spacemacs/packages.el#L543)), using spacemacs configuration layers? I want to use the default zenburn cursor color.

2. The background color for `evil-search-highlight-persist` looks really bad with zenburn. For solarized, it's taken care of ([here](https://github.com/syl20bnr/spacemacs/blob/a654bf6d55b48689938ac19527de2449bc58de67/spacemacs/extensions/solarized-theme/solarized.el#L759)). Is there a way I could do a similar thing for zenburn in my config layers?

Thanks.

**Comment by bjarkevad** [comment]
I have this in my config for zenburn-hc:
`(custom-set-faces  '(evil-search-highlight-persist-highlight-face ((t (:background "selectedMenuItemColor")))))`

**Comment by syl20bnr** [comment]
@aminb The cursor colors are `defcustom` variables you can access with `SPC : customize-group RET spacemacs RET`

It recalls me that I have to evilify the customize UI of emacs.

**Comment by aminb** [comment]
@bjarkevad Thank you very much that worked beautifully.

@syl20bnr I don't know what I'm doing wrong, but I can't get it to work. I change the value, but the color of the cursor is still the same after saving and setting. Can please copy a sample output generated in the custom section, here? I want to change the cursor's background color in normal state to `#FFFFEF`.

> It recalls me that I have to evilify the customize UI of emacs.

Please do :)

**Comment by syl20bnr** [comment]
I see, they are overwritten when the packages are initialized.
For now the work-around is to not use the customize interface from emacs and set the color to your liking directly in the `dotspacemacs/config` function:

```elisp
(set-face-attribute spacemacs-normal-face nil :background "#FFFFEF")
```

**Comment by aminb** [comment]
@bjarkevad Oh I see. When I put this in the dotspacemacs/config function, I get the following in the status bar (or mini-buffer I suppose?):

`Symbol's value as variable is void: spacemacs-normal-face`

I'm guessing that means the variable definition is not in scope, but I don't know what I should do. Do I need to `require` anything? Sorry for all these questions, I'm still an Emacs Lisp newb haha.

**Comment by syl20bnr** [comment]
@aminb my mistake. The symbol need to be quoted.

```elisp
(set-face-attribute 'spacemacs-normal-face nil :background "#FFFFEF")
```

**Comment by syl20bnr** [comment]
Oh you are starting with elisp, the quote means to pass the symbol as this, not its value.

**Comment by aminb** [comment]
@syl20bnr Thanks for the explanation! I actually did try with the quote (from the bit of Clojure that I know), it doesn't give any errors anymore, but again, nothing really happens (the cursor is still orange) :confused: Maybe I shouldn't insist and just change it in the spacemacs source itself.

**Comment by syl20bnr** [comment]
@aminb indeed it is not so trivial to change it ^^
I added a new function in `develop` branch: `spacemacs/set-evil-cursor-color`
I'm just about to make the release note for 0.61.0 and this function will be available in it.

This should work now, in your `dospacemacs/config`:
```elisp
(spacemacs/set-evil-cursor-color 'normal "#FFFFEF")
```

**Comment by aminb** [comment]
@bjarkevad Awesome. Thank you very much!

I'm just going to link the commit here for future reference: afff22e

**Comment by syl20bnr** [comment]
@aminb In release 0.63.0 I removed the function `spacemacs/set-evil-cursor-color` and there is a new variable `dotspacemacs-colorize-cursor-according-to-state` which can be set to `nil` in your dotfile.
See the updated template: https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/.spacemacs.template#L40-41
