### ISSUE TITLE
Tmux navigation not working 

### ISSUE THREAD

**Issue by jamesla** [syl20bnr/spacemacs#6011]
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description
I am trying to work out how to get tmux navigation working with spacemacs. I have installed the tmux layer and added the following to my tmux.conf:

```
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim(diff)?$|emacs.*$' && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim(diff)?$|emacs.*$' && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim(diff)?$|emacs.*$' && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iqE '(^|\/)vim(diff)?$|emacs.*$' && tmux send-keys C-l) || tmux select-pane -R"
```

I am using the following configuration in the user-config block inside my .spacemacs file.

```
  (define-key evil-normal-state-map (kbd "C-h") #'evil-window-left)
  (define-key evil-normal-state-map (kbd "C-j") #'evil-window-down)
  (define-key evil-normal-state-map (kbd "C-k") #'evil-window-up)
  (define-key evil-normal-state-map (kbd "C-l") #'evil-window-right)

```

#### Reproduction guide
- Start Emacs and tmux - create a new tmux pane
Press C-j

*Observed behaviour:*
Will not recognise the tmux pane below

*Expected behaviour:*
Cursor will navigate outside of spacemacs into a tmux pane.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git markdown osx dockerfile tmux spell-checking html javascript syntax-checking version-control)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment]
The tmux layer has bindings for `C-hjkl` already. It's unlikely to work if you change them yourself.

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+tools/tmux/local/tmux/tmux.el#L48-L88

**Comment by NJBS** [comment]
I believe Tmux is broken on master pending https://github.com/syl20bnr/spacemacs/pull/5977

**Comment by jamesla** [comment]
ok thanks @NJBS

**Comment by jamesla** [comment]
working on master
