### ISSUE TITLE
Weird string appends to buffer when click recently open file link

### ISSUE THREAD

**Issue by li-xinyang** [syl20bnr/spacemacs#6013]
#### Description
Weird string (Seems the text is from `customized-group`) is inserted into buffer when to clicking the recently opened file link in welcome screen

#### Reproduction Guide
- Start Emacs
- Click the recently opened file link

*Observed behaviour:*
See gif below

![2016-05-07 13_21_11](https://cloud.githubusercontent.com/assets/3349406/15097204/b32a8eb4-1546-11e6-8390-4e72b1e2b19f.gif)

*Expected behaviour:*
Open the file without insert wired string

#### System Info
- OS: darwin
- Emacs: 25.0.93.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults syntax-checking version-control emacs-lisp org python swift XYLayer)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by hemcsec** [comment]
It seems the same problem as stated in #5435

**Comment by StreakyCobra** [comment]
@li-xinyang Do you confirm it's the same bug? If yes we can close this one as duplicate, and you can report your information there :-)

**Comment by li-xinyang** [comment]
Yes, I think it is the same bug. I am closing this issue. Thanks :D

**Comment by li-xinyang** [comment]
I am reopening this issue since @hemcsec closed his one.
