### ISSUE TITLE
Bibtex Layer keybinding `SPC m i c` is invalid in LaTex Mode using AUCTeX 

### ISSUE THREAD

**Issue by hemcsec** [syl20bnr/spacemacs#6014]
#### Description
Bibtex Layer keybinding `SPC m i c` is invalid in LaTex Mode using AUCTeX 

#### Reproduction guide
- Start Emacs
- Open a LaTeX file
- SPC m i c

*Observed behaviour:*
byte-code: Symbol’s value as variable is void: org-ref-insert-cite-key

*Expected behaviour:*

#### System Info
- OS: darwin
- Emacs: 25.0.93.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. c9e8664)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip nil)
 better-defaults bibtex chinese
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 csharp django emacs-lisp extra-langs gtags git html javascript markdown org osx
 (latex :variables latex-build-command "LatexMK")
 python shell spacemacs-helm semantic
 (spell-checking :variables spell-checking-enable-by-default nil)
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 typescript vimscript
 (vinegar :variables vinegar-reuse-dired-buffer t))
```

#### Backtrace
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
Only if you have loaded org first, if you haven't then you get void-variable `org-mode-map`. Is something amiss with the required dependencies of `org-ref-helm-bibtex`?

**Comment by TheBB** [comment]
You should report this upstream. It doesn't appear to be caused by us. https://github.com/jkitchin/org-ref/issues

**Comment by hemcsec** [comment]
It works after update org-ref package, thanks.

**Comment by hemcsec** [comment]
After I add (add-hook 'LaTeX-mode-hook (lambda () (require 'org-ref))), it works. But I don't know whether this is the correct way to solve the problem.
