### ISSUE TITLE
Syntax not highlighting until cursor leaves code block

### ISSUE THREAD

**Issue by with-heart** [syl20bnr/spacemacs#6015]
#### Description

Inside of code blocks, syntax highlighting fails to be applied and a gray background/highlight shows instead. The issue persists when opening new blocks inside that block or re-opening the block _until_ you have moved your cursor out of the block and moved the cursor back in, in which case things seem to operate as expected (for the surrounding block, at least; new blocks inside that block have the same issue).
#### Reproduction guide
- Start Emacs
- Start typing code inside of a block ((), [], function() { }, etc.)

_Observed behaviour:_
Issue happens in all languages tried and with multiple themes selected.

Elixir:
![elixir](https://cloud.githubusercontent.com/assets/1954752/15098665/4b21789a-1510-11e6-98ae-dee78ad65321.gif)

es6:
![react](https://cloud.githubusercontent.com/assets/1954752/15098666/4f777b1a-1510-11e6-90c1-05fcf285665b.gif)

_Expected behaviour:_
Syntax should be highlighted as typed.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults colors syntax-checking themes-megapack osx shell git org react erlang elixir javascript html emacs-lisp
                 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by kRITZCREEK** [comment]
I've turned that off with: `(setq sp-highlight-pair-overlay nil)`

**Comment by lionize** [comment]
@kRITZCREEK: Thank you! That fixed the issue. Do you know what that overlay is supposed to do?

**Comment by kRITZCREEK** [comment]
No idea... :D It annoyed the crap out of me

**Comment by Miciah** [comment]
Looks like #7058 / https://github.com/syl20bnr/spacemacs/commit/f373105be11c6d2375ee310731fb2cab7cb1289 should have resolved this issue.  Can you confirm that it is resolved?
