### ISSUE TITLE
SPC f f (helm-find-file) opens in project root not current directory

### ISSUE THREAD

**Issue by ulyssesp** [syl20bnr/spacemacs#6016]
#### Description

`SPC f f` sometimes opens in the project root and not the current file's directory. It's especially a problem in a project with a `src` directory because then `src` has to be typed every time. This looks like it's happening with elm files only.
#### Reproduction guide
- Start Emacs
- Open a project
- Create .elm file with src/Test.elm and save the buffer
- Press `SPC f f`

_Observed behaviour:_
find-files starts at the project root not the current file directory

_Expected behaviour:_
find-files starts at the current directory
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults
                 (c-c   :variables c-c  -enable-clang-support t)
                 chrome dash elm emacs-lisp git haskell javascript markdown org react restclient search-engine
                 (shell :variables shell-default-shell 'eshell)
                 spell-checking syntax-checking)
```

**Comment by edrex** [comment]
hmm, I am seeing something similar, except `SPC f f` opens in my home directory when the current buffer is in `elm-mode` (the elm file is in a git project somewhere inside my home dir).

**Comment by edrex** [comment]
ah, for me this is only happening when I open a new buffer in `elm-mode` for a file that doesn't exist yet (ie, via emacs-client). After saving the file, destroying the buffer, and reopening, `SPC f f` works normally.

Possibly related:

On first opening the buffer, I see:

```
(New file)
Suspicious state from syntax checker elm: Checker elm returned non-zero exit code 1, but no errors from output: elm-make: /.../Main.elm: openFile: does not exist (No such file or directory)

Checker definition probably flawed.
```

**Comment by mkleehammer** [comment]
I've been seeing this periodically with ivy, not helm, (so counsel-find-file) and unrelated to elm-mode.   I haven't noticed a pattern yet, but this last time I was in a Python file as part of a git / projectile project and used SPC f f to try to load a file from the same directory.  Instead, counsel-find-file started from a completely different directory I'd opened earlier in the night via SPC p p.  (In fact, my spacemacs directory.)

I have 0.200.5 which very few customizations at this point - the main one being ivy.

**Comment by joefiorini** [comment]
I dug a little bit into this and found that if I [comment out this line](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/elm/packages.el#L29) then `SPC f f` works like it should. Unfortunately, don't know Spacemacs quite well enough to know why that happens, but maybe someone else will?

**Comment by joefiorini** [comment]
Okay, turns out it may be the [use of `setq` here](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/elm/funcs.el#L16). If I change it to a `let*`, then `SPC f f` seems to work without the above-mentioned line commented out.

**Comment by TheunisKotze** [comment]
Above worked for me

**Comment by Miciah** [comment]
Looks like #8075 / https://github.com/syl20bnr/spacemacs/commit/9a69d451071a97c287caada91d84c914f6f904d7 should resolve this issue on the develop branch.
