### ISSUE TITLE
Unclear docs

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#6019]
The sentence is unclear under Documentation > Commands > Discovering > Key bindings > Which-key:
 *To narrow the list to some key bindings using the leader key type a pattern like this regular expression: `SPC\ b` which would list all buffer related bindings.*

**Comment by robbyoconnor** [comment]
Pull requests welcome.

**Comment by nixmaniack** [comment]
Without looking at the doc you pointed, it looks like you're reading doc for `helm-descbinds` which is under `SPC ?`. If it's under `which-key` then it's wrong but under helm you narrow as you would usually by inputting filter characters.

**Comment by xged** [comment]
Docs under `which-key` has changed, or I was looking to some old ones.
