### ISSUE TITLE
Speed Reading Layer documentation has no CSS on website

### ISSUE THREAD

**Issue by vijaykiran** [syl20bnr/spacemacs#6020]
The page `http://spacemacs.org/layers/speed-reading/README.html` renders without CSS. The page 404s for
• `http://spacemacs.org/layers/css/readtheorg.css`
• `http://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js`

The stickytableheader has 404s across the site not just in speed-reading layer.

**Comment by StreakyCobra** [comment]
For the 404 and CSS this has probably been corrected in `develop` already. Can you try on http://develop.spacemacs.org  ?

**Comment by StreakyCobra** [comment]
Ping @nashamri @bobbyangelov for the javascript 404.

**Comment by nashamri** [comment]
Yes it's working fine in develop
http://develop.spacemacs.org/layers/+tools/speed-reading/README.html

**Comment by StreakyCobra** [comment]
@nashamri Ok thanks for the feedback.

@vijaykiran Thanks for the report. All this is already corrected in `develop` and will be deployed on next major release, so I'm closing this.
