### ISSUE TITLE
Spaceline off globally?

### ISSUE THREAD

**Issue by microamp** [syl20bnr/spacemacs#6022]
I'd like to turn off Spaceline globally due to [this issue](https://github.com/syl20bnr/spacemacs/issues/5955). I've tried `M-x spaceline-toggle-global-off` and `spaceline-toggle-global` but neither seems to take any effect. I can turn it off in individual buffers by running `spacemacs/toggle-mode-line`, but I'm wondering if there is a way to do this globally.

**Comment by izahn** [comment]
The easiest thing is to  add `spaceline` to
`dotspacemacs-excluded-packages`.

Best,
Ista

**Comment by TheBB** [comment]
The commands you've tried toggle the segment called 'global'.

**Comment by TheBB** [comment]
A new and faster version of Spaceline is on MELPA now.

**Comment by carbohydratesn** [comment]
Faster [but less pretty](https://github.com/syl20bnr/spacemacs/issues/6027) :thinking_face:

**Comment by microamp** [comment]
@TheBB Thanks for that, it does appear to be faster. The cursor motion is still a bit laggy at times but it may not be related to Spaceline. I'll close this issue as @izahn has already answered my question. Thanks!
