### ISSUE TITLE
Can't highlight selected region in holy mode?

### ISSUE THREAD

**Issue by hanfeisun** [syl20bnr/spacemacs#6025]
I'm using the holy mode of spacemacs.

I use `Ctrl + Space` to mark the start of a region and `Ctrl + n` to move down the cursor. However, the region selected is not highlighted visually. 

Does anyone have ideas about this?

**Comment by nixmaniack** [comment]
Just some thoughts from top of my head. 
By any chance have you disabled `transient-mark-mode`? If not, does your theme define different color for `region` face than your background color?

**Comment by hanfeisun** [comment]
@nixmaniack Thanks! 
It works somehow after I restart the computer.. I'll close the issue now until I can reproduce it..
