### ISSUE TITLE
Latest spaceline does not respect powerline-default-separator

### ISSUE THREAD

**Issue by carbohydratesn** [syl20bnr/spacemacs#6027]
Hello, updating to spaceline-20160510.542 forces use of the default separators, even if another (box in this case) is specified in config.  

Rolling back to spaceline-20160507.302 is a temporary fix.

**Comment by NJBS** [comment]
You'll have to call `spaceline-compile` in your `user-config` after setting `powerline-default-separator`.

See [discussion in gitter](https://gitter.im/syl20bnr/spacemacs?at=57321dffed393f3409b187a1) for more info.

**Comment by TheBB** [comment]
@carbohydratesn If this fixed your problem (judging by your reactions) please close this issue. That goes for the other one too.

**Comment by nwolfe** [comment]
Yeah, this seems like something that users will have to discover themselves when they start configuring their powerline/spaceline.

👍 for closing the issue

**Comment by cpaulik** [comment]
Should that not be documented? https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#powerline-separators says nothing about calling `(spaceline-compile)`

**Comment by nwolfe** [comment]
Ah, forgot we had documentation around powerline already!  Yes we should definitely add mention of `(spaceline-compile)` to that section.

**Comment by carbohydratesn** [comment]
Documentation sounds great, closed indeed

**Comment by TheBB** [comment]
I updated the docs, thanks for finding that.

**Comment by spijet** [comment]
After adding (spaceline-compile) to ~/.spacemacs, there's no more need to reload config (SPC-f-e-R) after starting Emacs in daemon mode and attaching a GUI emacsclient to get custom powerline separator right! :smile:
