### ISSUE TITLE
Typescript TSLint crashes on linted files without errors/warning

### ISSUE THREAD

**Issue by nrehm** [syl20bnr/spacemacs#6029]
Hey,
stumbled upon this strange behavior today when a Typescript file gets linted and has errors everything works as expected and you get errors/warnings from tslint & tide.

But when there are no tslint errors/warnings the checker errors out with:
Error from syntax checker typescript-tslint: End of file during parsing
This also swallows tide messages.

And the flycheck-typescript-tslint packages is no longer required its now part of flycheck

**Comment by nrehm** [comment]
Updated to the newest develop branch today.

It looks like this error is caused by a missing tslint.json in the project or home dir
but im not 100% sure right now as i get different results on two machines

On the other side a different problem occurred now i either have tslint errors/warnings or tide errors/warnings but not both. Is this intended behavior?

```
Syntax checkers for buffer category.component.ts in typescript-mode:

  typescript-tide
    - predicate:         t
    - Typescript server: running
    - Tide mode:         enabled

  typescript-tslint
    - predicate:  t
    - executable: Found at /usr/bin/tslint
```

**Comment by StreakyCobra** [comment]
Pinging the only spacemacser typescriptist I know: @JAremko

**Comment by JAremko** [comment]
> On the other side a different problem occurred now i either have tslint errors/warnings or tide errors/warnings but not both. Is this intended behavior? 

I'll look into it but it most likely an upstream problem.  tslint was merged to flycheck and removed from Melpa - might be something gone wrong. 
 
Also can you try to clear your emacs cache?

**Comment by JAremko** [comment]
I look like I can't make it crush.

**Comment by nrehm** [comment]
Tested a little bit and i can reproduce all cases.

If there is no tslint.json to be found the linter crashed with:
Error from syntax checker typescript-tslint: End of file during parsing

If there are tide errors tslint does not run or the messages do not get appended into the flymake window.

If there are not tide errors the tslint works as expected.

**Comment by nrehm** [comment]
@JAremko its a chaining issue no additional checker is executed after tide encounters errors.
Any idea how to fix this or if this is an spacemacs or flycheck issue?

My elisp is non existent atm just started to use spacemacs 3 days ago and i dont really have a clue where to look.

**Comment by JAremko** [comment]
@nrehm  ananthakumaran/tide#26

**Comment by nrehm** [comment]
Will take the tslint problem upstream and and close this issue.

For anybody else coming here via google.
Its intended behavior for tslint not to show up when we have tide errors.
 `"Please ensure that the TypeScript source files compile correctly before running the linter." is stated on https://www.npmjs.com/package/tslint `

Thanks for the help :)
