### ISSUE TITLE
Powerline won't be scaled up when using the utf-8 seperator

### ISSUE THREAD

**Issue by ynilu** [syl20bnr/spacemacs#6030]
#### Description

After upgraded to 0.105.20, I added the spaceline-compile into user-config to use the utf-8 powerline separator.

The scale of powerline will be changed if I reach the top or bottom of the buffer.
#### Reproduction guide
- Add the following into user-config

``` elisp
(setq powerline-default-separator 'utf-8)
(spaceline-compile)
```
- Increase the powerline-scale (to see the change clearly)
- Start Emacs
- Open a buffer with enough lines
- Move to the top or bottom of the buffer

_Observed behaviour:_
At top or bottom:
<img width="660" alt="screen shot 2016-05-11 at 4 40 22 pm" src="https://cloud.githubusercontent.com/assets/14059513/15175212/d77e6864-1797-11e6-847d-f3f3fa8ad4a1.png">
Not at top or bottom:
<img width="660" alt="screen shot 2016-05-11 at 4 40 11 pm" src="https://cloud.githubusercontent.com/assets/14059513/15175213/d7815452-1797-11e6-9d0b-791c7aabc3a7.png">

_Expected behaviour:_
Powerline should be scaled up 
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp)
```

**Comment by TheBB** [comment]
The powerline scale works by scaling all the images in the modeline. If you don't use images as separators, there's not much to do. The reason it's scaled in the middle of the buffer is that the HUD is visible, and that's an image.

**Comment by TheBB** [comment]
Anyway it looks like it's possible to make scaling work with utf-8 as well.

**Comment by ynilu** [comment]
@TheBB Thank you for the explanation. I'd be very grateful if you could fix this.

**Comment by fikovnik** [comment]
I run into this after reinstalling my desktop. The mode line is fine for unfocused buffers. For the focused buffer it shows like

![image](https://user-images.githubusercontent.com/374674/40927887-29f4ef84-6820-11e8-9187-e39d50d681ec.png)

I tried to play with different `powerline-scale` but it has no effect. I use the following font:

```
  dotspacemacs-default-font '("DejaVu Sans Mono for Powerline"
                               :size 13
                               :weight normal
                               :width normal)
```

**Comment by fikovnik** [comment]
The fix for above is installing Nanum Gothic font -- cf. https://github.com/syl20bnr/spacemacs/issues/1012
