### ISSUE TITLE
How to select an item from helm menu?

### ISSUE THREAD

**Issue by cyrillk** [syl20bnr/spacemacs#6033]
RET works fine when I do C-x C-f to open the file. But it doesn't work when I do M-x and try to pick one of the items of helm menu. Would really appreciate you help.

Mac, fresh install of spacemacs.

**Comment by d12frosted** [comment]
Hey, does this problem still exist?

**Comment by cyrillk** [comment]
Hi. Yes, I've just tried it again. Still doesn't work for me. 

Followed this tutorial ```
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus --with-cocoa --with-gnutls --with-librsvg --with-imagemagick --with-spacemacs-icon
$ brew linkapps
``` from https://github.com/syl20bnr/spacemacs

**Comment by d12frosted** [comment]
Could you please share the output of `SPC h d s`? Also, do you have more clear steps of reproduce?

**Comment by cyrillk** [comment]
@d12frosted Sure.

```
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

**Comment by cyrillk** [comment]
Steps to reproduce

1. Install following a tutorial on https://github.com/syl20bnr/spacemacs
1. ALT-X to open a helm menu
1. Choose one of the options (`paradox-list-packages` for e.g. or any other)
1. Press `enter`
1. The menu is getting closed. Nothing happens. A `Quit` label appears in the left bottom corner.

Please let me know if you need more details.

**Comment by d12frosted** [comment]
Hey @cyrillk,

There is new version of Spacemacs (v0.200.x), could you please try to reproduce the issue with new version of Spacemacs. And also don't forget to update all your packages (especially `helm`). If it doesn't help you, there is `ivy` completion layer, could you please try it instead of `helm` to see if it's `helm` or not `helm` related.

**Comment by cyrillk** [comment]
@d12frosted I've just tried it again with a fresh new version of emacs and spacemacs and it all works fine now. Not sure what was the problem. You can close the ticket now as I can't reproduce it anymore.
