### ISSUE TITLE
web-beautify-js erases whole buffer

### ISSUE THREAD

**Issue by neonsamurai** [syl20bnr/spacemacs#6034]
#### Description

When invoking 'web-beautify-js' in JSON mode, for example by pressing `, =` or `SPC m =` the whole buffer is erased on many JSON files.
#### Reproduction guide
- Start Emacs
- rename attached file 'mtc.simple.json.txt. to 'mtc.simple.json'
- open attached file 'mtc.simple.json'
- invoke 'web-beautify-json' (press `SPC m =` or `, =`)

_Observed behaviour:_
The buffer is erased, resulting in an empty buffer.

_Expected behaviour:_
The JSON in the buffer should be pretty printed.

_Notes_
When invoking 'json-mode-beautify' by pressing `C-c C-f` (while JSON mode is active) the buffer is pretty printed as expected.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp osx git github markdown org restclient
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control elixir elm html javascript sql yaml react)
```
#### Backtrace

```
web-beautify-format-region: Wrong type argument: numberp, "Abort trap: 6"
Suspicious state from syntax checker json-python-json: Checker json-python-json returned non-zero exit code 1, but no errors from output: No JSON object could be decoded

Checker definition probably flawed.

```

[mtc.simple.json.txt](https://github.com/syl20bnr/spacemacs/files/260965/mtc.simple.json.txt)

**Comment by cpaulik** [comment]
I can't reproduce that. Do you have the latest version of the packages? Have you tried calling `js-beautify` on the file in your terminal?

**Comment by codahale** [comment]
Probably related to this issue: nodejs/node#6563.

**Comment by neonsamurai** [comment]
js-beautify errors when invoking like this:

```bash
$ js-beautify -f mtc.simple.json
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Object.processInputSync (/usr/local/lib/node_modules/js-beautify/js/lib/cli.js:311:24)
    at Array.forEach (native)
    at Object.exports.interpret (/usr/local/lib/node_modules/js-beautify/js/lib/cli.js:199:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/js-beautify/js/bin/js-beautify.js:4:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
Run `js-beautify -h` for help.
```

But works when piping the file from stdin:

```bash
js-beautify < mtc.simple.json
{
    "PA": "MAN Truck & Bus AG, 80995, M\u00fcnchen, DE",
    "GT": "Abschrankungskonstruktion f\u00fcr einen Rollstuhlplatz in einem Fahrzeug",
    "AD": "20131009",
    "MC": [
        "A61G",
        "A61G0003",
        "A61G000308"
    ],
    "DE": "102013016746",
    "AN": "DE102013016746",
    "PC": "DE",
    "AB": "<p num=\"0000\">Die Erfindung betrifft eine Abschrankungskonstruktion (100) f\u00fcr einen Rollstuhlplatz in einem Fahrzeug, vorzugsweise in einem Omnibus. Die Abschrankungskonstruktion (100) umfasst ein Oberteil (1) und ein Unterteil (2) zur Montage an das Fahrzeug und eine mit dem Oberteil (1) und dem Unterteil (2) verbundene Abschrankungseinrichtung (3). Die Abschrankungskonstruktion (100) zeichnet sich insbesondere dadurch aus, dass die Abschrankungseinrichtung (3) relativ zu dem Oberteil (1) und dem Unterteil (2) translatorisch in eine eingefahrene Stellung und eine oder mehrere ausgefahrene Stellungen verschiebbar ist.<\/p><p num=\"\"><de-figure num=\"0\"><\/de-figure><\/p>",
    "IN": [
        "Kittel, Ralf, 80939, M\u00fcnchen, DE",
        "Schmerbeck, Franz, 94522, Wallersdorf, DE"
    ],
    "IC": [
        "A61G",
        "A61G0003",
        "A61G000308"
    ],
    "KI": "A1",
    "DP": "20150409"
```

Hope that helps.

**Comment by leohxj** [comment]
What's the progress about this issue?
I am using the lastest spacemacs dev branch on Windows 7.
When I run `SPC m =`  on web-mode, it erases whole buffer too...

**Comment by d12frosted** [comment]
Looks like an upstream issue to me. Especially thanks to @neonsamurai's comment.

**Comment by neonsamurai** [comment]
The issue does not occur to me anymore. Seems to be an upstream issue.
Maybe related to some node dependency.

Boris <notifications@github.com> schrieb am Fr. 23. Dez. 2016 um 13:41:

**Comment by leohxj** [comment]
@neonsamurai 
what means an upstream issue?
Should I combine some code?

**Comment by neonsamurai** [comment]
It means that the problem is likely not within Spacemacs but one of the
libraries used by web-beautify and this out of direct control of the
Spacemacs team.
Leo Hui <notifications@github.com> schrieb am Fr. 23. Dez. 2016 um 16:03:

**Comment by leohxj** [comment]
@neonsamurai 
Ok, it means the problem may be causing by node or js-beautify module, right?
How do you fixed this issue?
