### ISSUE TITLE
Clojure Layer: Provide Variable for disabling injection of dependencies on cider-jack-in

### ISSUE THREAD

**Issue by Sohalt** [syl20bnr/spacemacs#6035]
With `:pedantic? :abort` configured in `project.clj` `cider-jack-in` fails. This is described here:
https://cider.readthedocs.io/en/latest/caveats/#injecting-dependencies-and-leiningen-pedantic-abort-mode
One (not ideal) solution is to provide the dependencies from `~/.lein/profiles.clj` and disable injection from Cider.
It would be cool to have a variable to configure this in spacemacs.

**Comment by sooheon** [comment]
There is already a variable to configure this in cider: `cider-inject-dependencies-at-jack-in`. Unless the layer is making some kind of well thought out choice and configuration, I don't see a need to add variables at the spacemacs level to replicate basic plugin behaviour. Consider just setting `(cider-inject-dependencies-at-jack-in nil)` elsewhere in your config.

**Comment by TheBB** [comment]
That seems to cover it, indeed. Maybe we should document this? I'm not a clojure man.

**Comment by Sohalt** [comment]
I know about the variable (as it is described in the Cider docs). But setting that manually somewhere else in my .spacemacs file seems more ugly to me than using layer specific `:variables` when listing layers.

**Comment by TheBB** [comment]
Oh, you can set it in `:variables` too if you like. There is nothing special about layer variables.

**Comment by Sohalt** [comment]
Oops, OK, my bad. Closing then.
