### ISSUE TITLE
Remapping hippie-expand to C-;

### ISSUE THREAD

**Issue by domi91c** [syl20bnr/spacemacs#6039]
I'm having trouble figuring out the proper ways of remapping keys in Spacemacs. There just seem to be so many different functions for different modes and situations. Specifically in this case, I just want to remap hippie expand from `M-/` to `C-;`. Would appreciate the help!

**Comment by TheBB** [comment]
I just defined it in `evil-insert-state-map` since that's where I always use it.

```elisp
(define-key evil-insert-state-map (kbd "C-;") 'hippie-expand)
```
