### ISSUE TITLE
I want to help to get lispy into spacemacs. What should I work on?

### ISSUE THREAD

**Issue by sp3ctum** [syl20bnr/spacemacs#6050]
Hey guys, I'd like to put in work that would enable spacemacs users to use lispy. I see there has been some work already on this:
- [lispy: New layer that puts lispy-mode toggle on M-m k](https://github.com/syl20bnr/spacemacs/pull/4596)
- [(WIP) Add Lispy Layer](https://github.com/syl20bnr/spacemacs/pull/2792)

But it seems to me that both those efforts have stalled for the time being.

I've worked on the [evil-lispy package](https://github.com/sp3ctum/evil-lispy), which provides an opinionated way of using evil with lispy. It aims for simplicity for evil users - see the readme for more.
I have a private layer set up for it [in my own config](https://github.com/sp3ctum/spacemacs/blob/mika/private/lispy/packages.el), but I don't think it's ready for inclusion in spacemacs yet.

---

For this purpose I'd like to open a discussion. Please tell me what you think about this, and what I should work on.
I think spacemacs and lispy are great, and would love to see them work together in an idiomatic way :+1:

**Comment by nixmaniack** [comment]
Just my 2 cents. 

I am already using lispy with spacemacs while using hybrid style. As an active user of both spacemacs and lispy, I would just like to have lispy as is in hybrid state without any modifications except having `M-m` on something else.

You should go through the discussion of the first thread you pointed as in the end syl20bnr had expressed what he's expecting to include with lispy.

**Comment by sp3ctum** [comment]
Fair enough. That should be totally doable: hybrid state would need no
modifications, possibly.

**Comment by sooheon** [comment]
>I would just like to have lispy as is in hybrid state without any modifications except having M-m on something else.

This is how I use it currently as well, along with [lispyville](https://github.com/noctuid/lispyville). I don't think a lispy layer really needs that much, it works pretty much as you'd expect, going into special in insert mode and staying out in normal mode.

**Comment by randre03** [comment]
@sp3ctum I'm curious how this is going? I am an evil user that wants to use lispy in spacemacs and am not interested in having to temp. switch to hybrid style to do so. About your private layer you mentioned, do you use that with the stock clojure layer as well? Thanks

**Comment by sooheon** [comment]
I think this is an antipattern. You don't need another mode for lispy, just use insert (or hybrid), it doesn't matter. I've been doing it this way without any special customizations for a while now, it's far better than toggling using M-m k or whatever else. An insert command like `I` or `A` is usually all it takes to get into special, from where you can move around using all the lispy commands directly, and `esc` takes you to normal state, just like vanilla evil. 99% of the time after `I/i/A/a` I'm immediately in special state, the other 1% of the time, I do have to press C-M-f or C-M-b once.

**Comment by sp3ctum** [comment]
@randre03 Unfortunately I haven't worked on this since my last messages. I kind of settled on using my own layer, and am wondering, much like @sooheon, whether spacemacs users would find this a useful addition or not. It probably doesn't handle all use cases (only evil mode), and I think it's likely that it doesn't provide a lot of extra value for many.

However, I do use it personally all the time (for me it's nice at least). I use it with emacs lisp and with clojure, and both work very well.

Any thoughts?

**Comment by sondr3** [comment]
Do you guys have your private layer/dotfiles anywhere so I can look around for how you configured it? I'm almost considering ripping out the Scheme layer and replace it with my own version using Lispy.

**Comment by sp3ctum** [comment]
Yeah, mine is in the same repo as the private layer, see the original post.

**Comment by sondr3** [comment]
Ah, completely overlooked that, thanks.

**Comment by Somelauw** [comment]
Maybe [lispyville](https://github.com/noctuid/lispyville) can be added to spacemacs. It's a plugin similar to evil-cleverparens, but backed by lispy.

**Comment by lane-s** [comment]
Based on the old lispy layer thread, it looks like we need the lispy layer to, by default, act like a replacement for evil-lisp-state. I think the layer that @sp3ctum created works great, but I understand wanting have consistency with the `SPC k` sexp editing functions. Sometime soon I will try to see if I can make a layer that replaces evil-lisp-state with evil-lispy state and has appropriate key bindings in the `SPC k` menu. I would also want to add a configuration variable that just makes `SPC k` enter `evil-lispy-mode`. 

I was not able to get lispyville working in spacemacs, so I'm leaning towards using evil-lispy-mode.
