### ISSUE TITLE
git gutter toggle default off not working

### ISSUE THREAD

**Issue by WuTheFWasThat** [syl20bnr/spacemacs#6051]
I'm have the following layer:
```
     (version-control
         :variables
            version-control-global-margin nil
      )
```

But this does not seem to work, in that <space>Td gives:
```
Symbol's value as variable is void: git-gutter+-mode
```

When i set `version-control-global-margin t`, toggling the margin works fine

**Comment by StreakyCobra** [comment]
Can you run with `emacs --debug-init` and print the backtrace here?

**Comment by WuTheFWasThat** [comment]
```
Debugger entered--Lisp error: (void-variable git-gutter+-mode)
  (cond ((eql version-control-diff-tool (quote diff-hl)) diff-hl-mode) ((eql version-control-diff-tool (quote git-gutter)) git-gutter-mode) ((eql version-control-diff-tool (quote git-gutter+)) git-gutter+-mode))
  version-control/margin-p()
  (and (or (and (symbolp (quote (version-control/margin-p))) (boundp (quote (version-control/margin-p)))) (listp (quote (version-control/margin-p)))) (version-control/margin-p))
  (if (and (or (and (symbolp (quote (version-control/margin-p))) (boundp (quote (version-control/margin-p)))) (listp (quote (version-control/margin-p)))) (version-control/margin-p)) (progn (version-control/disable-margin) (message "version-control-margin disabled.")) (version-control/enable-margin) (message "version-control-margin enabled."))
  (if (or (null (quote nil)) (and (or (and (symbolp (quote nil)) (boundp (quote nil))) (listp (quote nil))) nil)) (if (and (or (and (symbolp (quote (version-control/margin-p))) (boundp (quote (version-control/margin-p)))) (listp (quote (version-control/margin-p)))) (version-control/margin-p)) (progn (version-control/disable-margin) (message "version-control-margin disabled.")) (version-control/enable-margin) (message "version-control-margin enabled.")) (message "This toggle is not supported."))
  spacemacs/toggle-version-control-margin()
  call-interactively(spacemacs/toggle-version-control-margin nil nil)
  command-execute(spacemacs/toggle-version-control-margin)
```

**Comment by StreakyCobra** [comment]
Ok, I suppose I found it:

- `spacemacs/toggle-version-control-margin` [uses](https://github.com/syl20bnr/spacemacs/blob/1ebbe18b478945b0c1eacfd6a3a82b22c3fdbd87/layers/%2Bsource-control/version-control/funcs.el#L114) `version-control/margin-p` to get the status of the toggle
- `version-control/margin-p` returns the variable storing the status of the margin according the the tool used.
- By default, `git-gutter+` is used, and the [`git-gutter+-mode`](https://github.com/syl20bnr/spacemacs/blob/1ebbe18b478945b0c1eacfd6a3a82b22c3fdbd87/layers/%2Bsource-control/version-control/funcs.el#L104) variable doesn't exists before `git-gutter+` is turned on, which is not the case as the global mode is not used.

@ralesi any idea how to solve this properly?

**Comment by TheBB** [comment]
Maybe we should just use `(bound-and-true-p git-gutter+-mode)` instead.

**Comment by WuTheFWasThat** [comment]
seems fixed now!  thanks
