### ISSUE TITLE
Mode-line separator can't be set to nil

### ISSUE THREAD

**Issue by jmfurlott** [syl20bnr/spacemacs#6052]
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description
Mode-line not properly able to be set to `nil`

#### Reproduction guide
- Add following to spacemacs config: `(setq powerline-default-separator 'nil)`
- Reload config

*Observed behaviour:*
After updating to spacemacs 0.105.20, the curved icons are back in the mode line when they should just be "vertical".

![image](https://cloud.githubusercontent.com/assets/805688/15269737/ae7ee6be-19bd-11e6-97c9-d9ec23a1e73e.png)

*Expected behaviour:*
No curves at all -- just a "vertical" modeline

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(git html javascript
     (shell :variables shell-default-term-shell "/bin/zsh")
     erc rcirc restclient markdown org deft ruby-on-rails)
```

**Comment by TheBB** [comment]
I can't reproduce this on develop. You did remember to do call `(spaceline-compile)` after setting `powerline-default-separator` to `nil`, right?

**Comment by jmfurlott** [comment]
@TheBB I just compiled it and it worked.  Closing this.  Thanks!

Did not realize I had to do that -- don't remember ever having to after using spacemacs for at least a year

**Comment by TheBB** [comment]
You probably upgraded Spaceline. It's a requirement with the new version. Packages change sometimes. ;-)
