### ISSUE TITLE
projectile-global-mode not enabled by default

### ISSUE THREAD

**Issue by ErDetMam** [syl20bnr/spacemacs#6054]
#### Description
Projectile does not save projects to known projects.
Fixed by setting projectile-global-mode in user-config.

#### Reproduction guide
- Start Emacs with a fresh installation of Spacemacs.
- projectile-global-mode not enabled by default.
- Go to a .projectile project.
- Go to home buffer.
- Project not saved in list of projects or by SPC p p.

#### System Info
- OS: gnu/linux
- Emacs: 25.0.93.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 0709d93)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm emacs-lisp)
```

**Comment by StreakyCobra** [comment]
PR welcome to discuss the change :-)

**Comment by StreakyCobra** [comment]
Wait, could this be related to this: https://github.com/syl20bnr/spacemacs/commit/3f22eeaa03d10c8733cf83b8c1649c37643febf1#commitcomment-17479953

**Comment by syl20bnr** [comment]
That would be surprising, the change just moves projectile config to another layer included by the Spacemacs distribution.

**Comment by ErDetMam** [comment]
It must have been a recent commit though because I only recently switched to the development branch about a week ago and it worked then.

**Comment by sooheon** [comment]
FWIW, I think this change deleted projectile for me as well. Spacemacs simply sees it as an unnecessary package and deletes it.

**Comment by ErDetMam** [comment]
I could still bring up the projectile window (SPC p p) though. Also, if I was inside a project I would be able to see the project from SPC p p, but it wouldn't stay there when I leave the project.

**Comment by StreakyCobra** [comment]
It's most probably because of the comment I linked in the commit. Probably @syl20bnr didn't saw the comment :-)

**Comment by syl20bnr** [comment]
![im-sorry-animal-meme-02](https://cloud.githubusercontent.com/assets/1243537/15277525/539222de-1ad5-11e6-8198-2fceacf072a9.jpg)

Fixed with https://github.com/syl20bnr/spacemacs/commit/8fb5d86
