### ISSUE TITLE
Show keybindings in smex results

### ISSUE THREAD

**Issue by colin4124** [syl20bnr/spacemacs#6055]
I see that smex already has a [pull request](https://github.com/nonsequitur/smex/pull/55) to fix it. But the author has not merged it.  Would the smex layer to merge it?

**Comment by StreakyCobra** [comment]
I think this kind of change should be handled upstream. It would be at best a ugly hack to do it on our side.

**Comment by colin4124** [comment]
I think so. But it has not updated 5 months ago. And I think if spacemacs use it as layer, it should continue to maintain it when upstream long time not update.

I just suggest, it is not a problem. ^_^

**Comment by syl20bnr** [comment]
A less ugly hack is to fork the repo upstream and merge the PR. We can point to this fork in the meantime with a clear comment. But we try to avoid that since it is a pretty slow process.

**Comment by colin4124** [comment]
@syl20bnr 

Ok, I got it. After all, it is not the major one which spacemacs should focus on.
