### ISSUE TITLE
Global / System-wide installation

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#6056]
I wonder if it would be possible to allow global / system wide installations of Spacemacs. Each user could have their own `.spacemacs` file, and layers enabled there would be installed into the user's `.emacs.d` directory, while the core distribution would be installed systemwide.

**Comment by StreakyCobra** [comment]
CC @TheBB: He worked on packaging spacemacs for archlinux, and for this I suppose he needed to install it system-wide. He may have some experience about this then.

**Comment by TheBB** [comment]
It's possible with some patching. I didn't finish it but I got far enough to be convinced that it's doable at least.
