### ISSUE TITLE
[magit] COMMIT_EDITMSG buffer is not killed upon making a commit

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#606]
In vanilla magit, the COMMIT_EDITMSG is killed upon making a commit. But in spacemacs, the buffer remains. Sometimes it is even considered a "modified buffer" so Emacs queries me whether I want to save it when I try to quit Emacs.

**Comment by syl20bnr** [comment]
I link the url found by @CestDiego (I love gitter on this one, easy to search in the chat history): https://groups.google.com/forum/#!topic/magit/x_iTFHgLyqk

We may be able to hack an advice for it but I prefer to find why the buffer is not closed properly.

**Comment by kini** [comment]
I see references to `emacsclient` in that thread. Maybe it is related to #492?

**Comment by syl20bnr** [comment]
It may have something to do with the fact that a server is automatically started at the end of the init. But I recall that I had this issue before adding the server.

**Comment by cpaulik** [comment]
+1 I'm observing the same problem.

**Comment by herbertjones** [comment]
Correct functionality occurs when ```magit-use-emacsclient-p``` is replaced by ```nil``` in the function that normally deletes the buffer.  Adding ```(setq magit-emacsclient-executable nil)``` to ```dotspacemacs/init``` restores the deleting the buffer after committing, but then the commit message comments don't show up.

The source explains the reason for the behavior of ```magit-use-emacsclient-p``` is found at the following URL:

 https://github.com/magit/magit/wiki/Emacsclient

**Comment by herbertjones** [comment]
emacsclient behavior works as expected when set:  ```(add-hook 'server-done-hook 'kill-buffer)
```

**Comment by syl20bnr** [comment]
Fixed with #743
