### ISSUE TITLE
Evil prog-mode code folding broken on develop branch

### ISSUE THREAD

**Issue by dubnde** [syl20bnr/spacemacs#6066]
#### Description
Evil prog-mode folding doesn't work anymore on `develop` branch. It appears `(add-hook 'prog-mode-hook 'spacemacs//enable-hs-minor-mode)` was removed from `spacemacs-evil/init-hs-minor-mode` when it was moved to `layers/+spacemacs/spacemacs-evil/packages.el`

#### Reproduction guide
- Start Emacs
- Open prog-mode file for elisp/c/c++
- try code folding on a function e.g `z-a`

*Observed behaviour:*
Function should fold

*Expected behaviour:*
No folding happens

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. c9f7fc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle :disabled-for shell erc)
 better-defaults
 (colors :variables colors-enable-rainbow-identifiers nil colors-enable-nyan-cat-progress-bar nil)
 cscope
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
 emacs-lisp evil-cleverparens evil-commentary
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 (go :variables go-tab-width 4)
 git github gtags haskell helm html
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 ivy javascript markdown
 (org :variables org-enable-github-support t)
 osx pdf-tools perforce plantuml python ranger ruby rust search-engine semantic
 (shell :variables shell-enable-smart-eshell t shell-default-full-span nil)
 shell-scripts spell-checking syntax-checking version-control vimscript windows-scripts yaml)
```

**Comment by syl20bnr** [comment]
Sorry I moved a lot of code lately, made some dumb mistakes. Should be OK in develop now.

**Comment by dubnde** [comment]
Yeah! I have updated the package and it works fine now. Checked for `elisp/c/c++` Thanks. 

Do I close the issue?

**Comment by StreakyCobra** [comment]
As the bug was introduced and fixed in develop, yes you can :-)

**Comment by dubnde** [comment]
Fixed on develop
