### ISSUE TITLE
Unintentional switch from editing to commnd mode when typing f followed d in insert mode

### ISSUE THREAD

**Issue by harikb** [syl20bnr/spacemacs#6070]
#### Description
I am using spacemacs with vim keybinding and enjoy the insert/command mode. However emacs switches to command mode if I type `f` followed by `d` fast (without delay)
 
#### Reproduction guide
- Start Emacs
- Go to insert mode and start editing. Type f followed by d one after the other without any delay. `fd` is a common variable name I have and that is why I am used to typing it so fast.

*Observed behaviour:*
The editor switches to command mode.

*Expected behaviour:*
It should insert the two letters f and d and continue

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 3274e7d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp go git markdown python syntax-checking)
```

#### Backtrace
```
None
```

**Comment by NJBS** [comment]
This is from the `evil-escape` package, see [this part](http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline78) of the documentation if you'd like to change the key combination.

**Comment by harikb** [comment]
Thanks! I didn't know this.  `fd` is a popular file descriptor variable for me :)
