### ISSUE TITLE
expand-region-reset-fast-key should not be set to "r"

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#6073]
The reset-fast-key undoes all expand-region calls and puts your cursor back at original position. Though "r" is mnemonic for reset, it sadly shadows evil-replace, which is not too rarely used with a visual selection. I'm not sure what would be better for it though... the package default is "0", but that is used with visual selections sometimes as well. If you set it to nil, C-g can still be used, fwiw.

**Comment by StreakyCobra** [comment]
:+1: :point_right: https://github.com/syl20bnr/spacemacs/blob/463e477fd1d28656564a376c974f5a7bf1608458/layers/%2Bspacemacs/spacemacs-editing/packages.el#L134
