### ISSUE TITLE
Company-mode menu breaks the comment background face

### ISSUE THREAD

**Issue by isolet** [syl20bnr/spacemacs#6075]
Hi,

Thanks for the awesome package for emacs starters! I find that the company-mode popup menu will break the comment background. Please see the differences below.

![screen shot 2016-05-18 at 12 06 29](https://cloud.githubusercontent.com/assets/5475262/15347348/7825034e-1cf3-11e6-8a19-278b09255376.png)

![](https://ssl.moefq.com/images/2016/05/18/dbeddf51bd4e59202933ca628df4830a.png)

I'm wondering whether I can get rid of this or not ? Thanks in advance !

**Comment by StreakyCobra** [comment]
At first glance I would think of a limitation (bug?) of company, probably not something that should be corrected at Spacemacs level. I may be wrong though.
