### ISSUE TITLE
Avy commands fail with: cannot open load file: no such file or directory, avy

### ISSUE THREAD

**Issue by LeartS** [syl20bnr/spacemacs#6078]
#### Description
Avy commands fail with error message: "Cannot open load file: no such file or directory, avy". They worked for me until yesterday, today I've just updated the packages.

#### Reproduction guide
- Start Emacs
- Update packages
- Try an avy command, e.g. `SPC SPC` for `avy-word` or `SPC d` for `avy-char`

*Observed behaviour:*
The command fails with `Cannot open load file: no such file or directory, avy` in the minibuffer

*Expected behaviour:*
The command should work.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory nil)
 better-defaults clojure csv emacs-lisp erlang frame-geometry git html markdown python react restclient semantic spotify
 (syntax-checking :variables syntax-checking-enable-tooltips t)
 themes-megapack vinegar)
```

**Comment by StreakyCobra** [comment]
I can't reproduce this on a fresh install.

----

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

**Comment by LeartS** [comment]
Sorry, my bad. I launched `update-packages` but forgot to restart after.
