### ISSUE TITLE
gjslint linter not working.

### ISSUE THREAD

**Issue by awb99** [syl20bnr/spacemacs#6080]
I am trying to get .js linting to work; but I cannot seem to get the gjslint to work

I tried a lot:
```
npm install gjslinter
npm install grunt-gjslint --save-dev
git clone https://github.com/google/closure-linter.git
cd closure-linter && python ./setup.py install
```
The git commit I think is the right way. I guess it is using the wrong version of python.
Is there an easier way to set this up?

**Comment by rgrinberg** [comment]
Doesn't seem like it's the responsibility of spacemacs to install these external dependencies.

For example, on archlinux install closure-linter is just `$ sudo pacman -S closure-linter`.

**Comment by d12frosted** [comment]
Closing as inactive and irrelevant issue.
