### ISSUE TITLE
Using R in ess freeze for few second when cursor in print() function

### ISSUE THREAD

**Issue by boboRAY** [syl20bnr/spacemacs#6081]
I'm writing R in spacemacs
Every time when my cursor go into print('cursor slow here'), my spacemacs freeze for a few second and become very laggy in print function
Can anyone help here
Thanks

**Comment by izahn** [comment]
Are you writing directly at the R prompt (i.e. the "inferior" R buffer) or
in a separate R script (i.e., an "R-mode" buffer)?

Which spacemacs branch are you on? What version of ESS do you have
installed?

**Comment by boboRAY** [comment]
Hi @izahn
 
I have this problem both in R prompt and R scirpt (After I started an iESS buffer)

How do I check my spacemacs branch and ESS version?

**Comment by a13ph** [comment]
@boboRAY Sorry you had no response for so long.
You can use `SPC h d s` to copy your versions and some other info to paste here.

**Comment by boboRAY** [comment]
Hello @a13ph 
Here is my spacemacs information

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python ipython-notebook version-control eyebrowse dash shell osx ess go auto-completion emacs-lisp git syntax-checking)
```

**Comment by izahn** [comment]
@boboRAY I never noticed this until I tried turning smartparens mode on (I usually disable it). For me I only have problems in the iESS buffer, not in R scripts, so it seems that we are not seeing exactly the same thing. Nevertheless, can you try disabling smartparens and see if that fixes things for you? You can disable it by adding it to `dotspacemacs-excluded-packages`, e.g., I have `dotspacemacs-excluded-packages '(yasnippet smartparens)` in my `.spacemacs`.

**Comment by boboRAY** [comment]
@izahn Thanks for reply.
I had tried and seems no problems here.

**Comment by izahn** [comment]
@boboRAY do you mean that excluding smartparens fixes the slowdown you were noticing in ESS? If so I don't think this issue should be closed. While I personally hate smartparens and disable it anyway, lots of people like it and it would be nice for them if it didn't break ESS. Lets leave this issue open to encourage someone to look into why smarparens and ESS don't play nicely together.

**Comment by boboRAY** [comment]
@izahn Yes, it fixed my problems!
