### ISSUE TITLE
Tern not running on node v6.1.0

### ISSUE THREAD

**Issue by sendyhalim** [syl20bnr/spacemacs#6083]
#### Tern not running on node v6.1.0
I upgraded node from v5.7.0 to v6.1.0, I installed tern on v6.1.0 (globally). It works on v5.7.0, any idea? However, it works if I start the tern manually:
1. Start emacs
2. Open a javascript file
3. _Autocomplete not working_
4. I start the tern manually
5. Run `tern-use-server` and specify the port of the tern that I ran manually.
6. _Autocomplete works fine_

```
which tern
$HOME/.nvm/versions/node/v6.1.0/bin/tern
```

#### Reproduction guide
- Start Emacs
- Open a javascript file
- Type a variable name
- Press `TAB`, it will fail to show completion and there's a message `Request failed: (nil)`

*Observed behaviour:*
There's a message `Request failed: (nil)`, I did check the tern process `ps aux | grep tern`, no tern process running.

*Expected behaviour:*
It should show completion list when I pressed `TAB` when I'm typing a variable name

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion elm emacs-lisp git go haskell html javascript markdown org osx php react restclient swift syntax-checking themes-megapack theming unimpaired version-control vim-empty-lines vim-powerline yaml)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by tmkbry** [comment]
Might be related to this problem. https://github.com/nodejs/node/issues/6563
Open a shell in emacs and check if you can run node in it. You should get "Abort trap: 6 error ".
If so, then you have to upgrade Node to 6.2

**Comment by sendyhalim** [comment]
@tmkbry yep upgrading to v6.2.0 solves the issue, downgrading to v5.7.0 solves it too. I'm closing this issue because it's node related.
