### ISSUE TITLE
Why is the broken org-repo-todo part of Spacemacs?

### ISSUE THREAD

**Issue by fladd** [syl20bnr/spacemacs#6086]
The package seems broken since over a year: https://github.com/waymondo/org-repo-todo/issues/5.

I was wondering why it is still part of Spacemacs? I mean, it is unusable!

**Comment by TheBB** [comment]
I've been thinking of writing a replacement for a while. It has a number of shortcomings not related to that problem as well.

**Comment by fladd** [comment]
That's great!
But why not just remove the package from Spacemacs, until there is a working solution?

**Comment by syl20bnr** [comment]
If it's broken then we can `:excluded t` it and add a comment about the reason.

**Comment by syl20bnr** [comment]
`org-repo-todo` has been replaced by `org-projectile`.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
