### ISSUE TITLE
Org agenda does not show captured tasks

### ISSUE THREAD

**Issue by fladd** [syl20bnr/spacemacs#6087]
#### Description
In a freshly installed Spacemacs, when I capture my first task with org-capture, Spacemacs nicely asks me if I want to create the folder `~/org` and within it the file `notes.org`.

So far, so good.

When I now check my org agenda todo items, however, this new task is not in there. If Spacemacs adds an `~/org` directory for me, then it should also set `org-agenda-files` accordingly.

#### Reproduction guide
- Start Emacs
- `SPC a o c` --> choose `t` --> write a task --> `C-c C-c`
- `SPC a o t`

*Observed behaviour:*
I see an empty todo list.

*Expected behaviour:*
I see a todo list with the task I just created.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git github markdown org python)
```

#### Backtrace
```

```

**Comment by TheBB** [comment]
> If Spacemacs adds an `~/org` directory for me, then it should also set `org-agenda-files` accordingly.

Spacemacs doesn't create an `~/org` directory for you, org does that on its own. Therefore I presume this is a feature request for org and not us.

What Spacemacs does it set the value of `org-default-notes-file` though.

**Comment by fladd** [comment]
So you're saying the org team should implement automatically changing the
spacemacs file and not the spacemacs team?

**Comment by d12frosted** [comment]
> spacemacs file

which file?

**Comment by TheBB** [comment]
No, that's not what I'm saying.

> If Spacemacs adds an `~/org` directory for me, then it should also set `org-agenda-files` accordingly.

Spacemacs **does not** create this directory for you. Org does. Therefore, if you consider this discrepancy a bug, it is a bug in Org.

**Comment by d12frosted** [comment]
BTW, I am not sure, but setting `org-directory` to anything else might help you. Buy default it's value is `~/org`.
