### ISSUE TITLE
Should projectile be part of spacemacs-base

### ISSUE THREAD

**Issue by ralesi** [syl20bnr/spacemacs#6088]
I know this is a recent change, and this might be semantic, because I can technically include `spacemacs-projects` in my configuration-layers when using base, but it seems like it is a base package used in a quite a few layers.  Just looking through the layers directory, the following layers are referencing `projectile`:

```
+emacs\ibuffer\config.el
+emacs\ibuffer\packages.el
+emacs\org\funcs.el
+tags\cscope\packages.el
+emacs\org\packages-funcs.el
+frameworks\ruby-on-rails\packages.el
+emacs\org\packages.el
+lang\c-c++\packages.el
+spacemacs\spacemacs-layouts\funcs.el
+spacemacs\spacemacs-projects\packages.el
+completion\helm\packages.el
+completion\ivy\funcs.el
+completion\ivy\packages.el
+tools\shell\funcs.el
+tools\shell\packages.el
+lang\python\local\nose\nose.el
+lang\python\packages.el
+lang\scala\funcs.el
```

Just wanted to bring this up for a discussion.  There might be other reasons for moving it to `spacemacs-projects` that I am not aware of.

**Comment by syl20bnr** [comment]
I decided to make spacemacs-base as light as possible (i.e. closer to base Emacs). The idea is that for users starting with spacemacs-base they can cherry-pick the blocks they want in `+spacemacs` which activates the services in the Spacemacs layers.

But seems like `projectile` is used in places that are not really isolated like `funcs.el` and `config.el` so yeah it should be in `spacemacs-base`. I'll move it back.

**Comment by syl20bnr** [comment]
Done :-)

**Comment by ralesi** [comment]
@syl20bnr,  thanks for the response.  Along the vein of what you are talking about with plans for spacemacs-base, how does one declare a specific package from a layer without including the entire layer?

**Comment by syl20bnr** [comment]
It is not possible but @justbur started to work on a `:packages` keyword to be able to cherry-pick. The PR has been deleted but I have in my todo list to re-apply it and fix the eventual bugs.

You can see the PR here: https://github.com/syl20bnr/spacemacs/pull/5339

**Comment by ralesi** [comment]
Thanks, this is a big issue for me since I am trying to work off `base`, so I will look into it if you are already not working on it.

**Comment by syl20bnr** [comment]
Great, thank you 👍
