### ISSUE TITLE
nlinum-relative latency issues

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#6094]
`nlinum-relative` while quicker introduce input latency, for instance when releasing `j` after keeping it pressed a few seconds, the point continues to go down. This is not comfortable.

I pushed a delay of `0.2` seconds to redraw the relative live but it freeze Emacs when scrolling down with `smooth-scrolling` activated.

I tried to not use a timer for `nlinum-relative` but once again `smooth-scrolling` conflicts and the relative numbers don't make sense.

What we need:
A 0 ghosting of actions when the user stop pressing a navigation key, i.e. releasing `j` must stop the point immediately. If we must introduce a delay to get this then let's use a delay, the navigation slickness is more important.

cc @CodeFalling

**Comment by syl20bnr** [comment]
Not sure if it is easily implementable but having absolute lines while scrolling and relative lines when idle for a short time could be best of both world.

Other possibility, having the relative numbers only when initiating a verb waiting for a motion, but it may slow down some people.

**Comment by hkjels** [comment]
`nlinum` seems entirely broken. A couple of line-number flickers and the numbers are also still absolute. The previous plug-in worked flawlessly as far as I could see.

**Comment by CodeFalling** [comment]
I have removed `post-command-hook` now. But sorry I still have no idea to implement absolute lines while scrolling..

**Comment by syl20bnr** [comment]
I will move nlinum to a layer tonight so we can put back linum as default but still work on nlinum integration into Spacemacs.

**Comment by syl20bnr** [comment]
Done, see commit https://github.com/syl20bnr/spacemacs/commit/fd756a1
For now I did not put a README.org.
