### ISSUE TITLE
How to override default keybindings?

### ISSUE THREAD

**Issue by with-heart** [syl20bnr/spacemacs#6096]
In both user-config and user-init, I have placed the following code:

```
(spacemacs/set-leader-keys "SPC" `avy-goto-word-1)
```

When I first run Emacs, `SPC-SPC` is still bound to `M-x`. If I then run `SPC f e R` to reload my .spacemacs file, `SPC-SPC` is now bound to avy. Is there something specific I need to do to override the default `M-x` binding?

I'm running on develop branch.

**Comment by TheBB** [comment]
You have to set the command key to something other than space.

**Comment by lionize** [comment]
Do you mean that `SPC-SPC` is reserved and I can't use it?

**Comment by TheBB** [comment]
If you set the command key to `SPC` then `SPC SPC` will be reserved. If you want to use something else on `SPC SPC` you have to set the command key to something other than `SPC`.

I'm talking about the variable `dotspacemacs-command-key` (on master) or `dotspacemacs-emacs-command-key` (on develop).
