### ISSUE TITLE
can't quite spacemacs..(tramp-compute-multi-hops)

### ISSUE THREAD

**Issue by godndevil** [syl20bnr/spacemacs#6098]
hi.
i'm a korean. i don't english very well.
i have question.
i am using spacemace and gnu-ftp.
--------------detail ---------
pc os - window7
spacemace - 0.105.20(vim mode)
gnutls-3.3.11-w32-bin
ftp - ftp-for-win32(ange-ftp)

-- questions --
spacemace can't quit after remote server file editing.

commands:
1.:e /ftp:useid@server-ip:path/to/file
  password
2.editing or modify at file
3.:w (save)
4.:q (spacemacs quit)

message is "Symbol's function definition is void: tramp-compute-multi-hops"

so, i am kill emace.exe to the windows-work-manager.
please, help me.

**Comment by Bad-ptr** [comment]
Well it seems like a persp-mode bug.) Now it must be fixed https://github.com/Bad-ptr/persp-mode.el/commit/41678f3bcdc55c322166e8484f9298cd2fb4cc9f. So try to update the persp-mode package.

**Comment by godndevil** [comment]
right now. i was done "Package Update".
 i have connecting ftp.
 but when i quit. next message displayed.

Host `xxx.xxx.xxx.xxx' looks like a remote host, `ftp' can only use the local host

thanks you.

**Comment by Bad-ptr** [comment]
> thanks you.

Thank you for response and patience).

I updated the fix https://github.com/Bad-ptr/persp-mode.el/commit/88f7c1f68e0b192442454d6c08ab2c1b54d612ad

So, wait till persp-mode will be updated at MELPA(~2 hours from now) and do the package update.

**Comment by godndevil** [comment]
Thank you!
It was done well with Quit.
Very Very Well.

**Comment by StreakyCobra** [comment]
@godndevil If your problem is fixed, you can close the issue :-)

Thanks for the  support @Bad-ptr :+1:

**Comment by godndevil** [comment]
OK. Thank you!
