### ISSUE TITLE
How to revert custom-set-faces in auto-completion/init-company?

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#6099]
I prefer the standard look, but there is a custom-set-faces for company's init function that overrides whatever I customize it to, even when I reset all customizations. Shouldn't custom-set be left to the end user? While variables can be overriden, custom-set becomes pretty set in stone.

https://github.com/syl20bnr/spacemacs/blob/master/layers/auto-completion/packages.el#L114

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
