### ISSUE TITLE
How to hide specific minor mode indicator?

### ISSUE THREAD

**Issue by ynilu** [syl20bnr/spacemacs#6101]
I want to hide the "Ⓔh" when using hybrid style.

I tried to add these into user-config
```elisp
(diminish 'hybrid-mode)
```
```elisp
(spacemacs|diminish hybrid-mode)
```
```elisp
(spacemacs|diminish 'hybrid-mode)
```
But none of them works.

**Comment by sooheon** [comment]
I have `(spacemacs|diminish hybrid-mode nil)` in my user-config, and it works for me. Is it just the nil arg you're missing?

**Comment by ynilu** [comment]
@sooheon Thank you for the suggestion. I tried to add "nil" but it didn't take effect.

**Comment by ynilu** [comment]
@sooheon It works after I changed to develop branch. Thank you for that.
