### ISSUE TITLE
Can't open more than one emacs frame (Invalid face: linum).

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#6104]
#### Description

Since fa4eeb49f050c0caa23f635a5d2c94fc50e86f86, I can't open more than one emacs frame (client/daemon).
#### Reproduction guide
- Start Emacs as a daemon.
- Open an emacs frame (`emacsclient -c -n`).
- Repeat once.

_Observed behaviour:_

emacsclient spits out the following when run the second time:

``` txt
*ERROR*: Invalid face: linum
```

There are no relevant errors in the `*messages*` buffer (as far as I can tell).

_Expected behaviour:_

Two frames are opened.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. da55a89)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm better-defaults git
      (auto-completion :variables auto-completion-return-key-behavior nil)
      org spell-checking syntax-checking
      (shell :variables shell-default-shell 'ansi-term)
      emoji emacs-lisp markdown latex yaml c-c   html haskell go javascript python systemd
      (rust :variables rust-format-on-save nil))
```

**Comment by Stebalien** [comment]
It appears that this bug disappears when either `*Messages*` or `*spacemacs*` buffer is open in some frame.

**Comment by Stebalien** [comment]
Disabling the `dotspacemacs-line-numbers` setting works around the bug.

**Comment by Stebalien** [comment]
> It appears that this bug disappears when either the *Messages* or *spacemacs* buffer is open in some frame (this doesn't apply to the *scratch* buffer).

I believe this is because I don't have line numbers enabled in these modes.

**Comment by lukepfister** [comment]
I'm pretty sure this is related to this issue: https://github.com/kaushalmodi/.emacs.d/issues/4

I haven't tried the proposed fix.

**Comment by Stebalien** [comment]
It looks related. Unfortunately, that fix only seems to allow one frame to load. Really, it looks like `nlinum--setup-window` (`nlinum.el`) needs to be modified to not run until after the frame is loaded. Is there any way to tell if the current frame is completely loaded? I was able to get it to work by adding:

```elisp
(defvar frame-ready nil)
(add-hook 'after-make-frame-functions (lambda (frame) (set-frame-parameter frame 'frame-ready t)))
(add-hook 'after-init-hook (lambda () (set-frame-parameter nil 'frame-ready t)))
```

To mark a frame as "ready" and changing:

```elisp
(defun nlinum--setup-window ()
  (let ((width (if (display-graphic-p)
                   (ceiling
                    (let ((width (nlinum--face-width 'linum)))
                      (if width
                          (/ (* nlinum--width 1.0 width)
                             (frame-char-width))
                        (/ (* nlinum--width 1.0
                              (nlinum--face-height 'linum))
                           (frame-char-height)))))
                 nlinum--width)))
    (set-window-margins nil (if nlinum-mode width)
                        (cdr (window-margins)))))
```

To:

```elisp
(defun nlinum--setup-window ()
  (let ((width (if (and frame-ready (display-graphic-p)) ;; <-- Here
                   (ceiling
                    (let ((width (nlinum--face-width 'linum)))
                      (if width
                          (/ (* nlinum--width 1.0 width)
                             (frame-char-width))
                        (/ (* nlinum--width 1.0
                              (nlinum--face-height 'linum))
                           (frame-char-height)))))
                 nlinum--width)))
    (set-window-margins nil (if nlinum-mode width)
                        (cdr (window-margins)))))
```

**Comment by Stebalien** [comment]
There appears to be a two year old upstream report: https://lists.gnu.org/archive/html/bug-gnu-emacs/2014-10/msg00126.html

**Comment by StreakyCobra** [comment]
@Stebalien FYI https://github.com/syl20bnr/spacemacs/commit/fd756a1 reverted line numbers back to the `linum` package.

**Comment by Stebalien** [comment]
@StreakyCobra Thanks! (Although it might be a good idea to keep this open as there is still an nlinum layer which may eventually, from what I've read, be enabled by default).

**Comment by zw963** [comment]
Following code is worked for only one frame.

```cl
(defun initialize-nlinum (&optional frame)
  (require 'nlinum)
  (add-hook 'prog-mode-hook 'nlinum-mode))
(when (daemonp) (add-hook 'window-setup-hook 'initialize-nlinum))
```
But, I still not find out a way to make `make-frame` worke well with `nlinum-mode`.

**Comment by zw963** [comment]
Because I use `make-frame` to create new frame, following snippets worked for me at least for now.

```cl
(defun initialize-nlinum (&optional frame)
  (require 'nlinum)
  (add-hook 'prog-mode-hook 'nlinum-mode))
(when (daemonp)
  (add-hook 'window-setup-hook 'initialize-nlinum)
  (defadvice make-frame (around toggle-nlinum-mode compile activate)
  (nlinum-mode -1) ad-do-it (nlinum-mode 1)))
```

Those code make my emacs 24.5.1 worked with nlinum-mode very well.
no matter what open a frame from terminal or create a new frame in emacs.

**Comment by kaushalmodi** [comment]
Simply running linum/nlinum in `after-make-frame-functions` hook works when `(daemonp)`.

``` el
;; Set/unset linum
(if (daemonp)
    ;; Need to delay linum activation till the frame and fonts are loaded, only
    ;; for emacsclient launches. For non-daemon, regular emacs launches, the
    ;; frame is loaded *before* the emacs config is read. Not doing so results
    ;; in the below error in emacs 24.5:
    ;;   *ERROR*: Invalid face: linum
    (add-hook 'after-make-frame-functions #'modi/toggle-linum)
  ;; Even when running in non-daemon mode, run `modi/toggle-linum' only after the
  ;; init has loaded, so that the last modified value of `modi/linum-fn-default'
  ;; if any in setup-personal.el is the one effective, not its standard value
  ;; in its defvar form above.
  (add-hook 'after-init-hook #'modi/toggle-linum))
```
https://github.com/kaushalmodi/.emacs.d/blob/c5a7d1a9c0aba5c80fac7be87ece0afffc51099b/setup-files/setup-linum.el#L166-L178

*PS: I was surprised to see my config referenced here :)*
