### ISSUE TITLE
spacemacs desktop-save-mode

### ISSUE THREAD

**Issue by vinurs** [syl20bnr/spacemacs#6107]
Dose spacemacs stop  reopening files that opened by emacsclient  by desktop-save-mode?
I added the following in dotspacemacs/user-config:
(desktop-save-mode 1)
then, I close my emacs and reopen emacs, but the files opened by emacsclient will be not reopened, files that opened by C-x C-f will be reopened correctly.

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx emacs-lisp vinurs-basic vinurs-dev-env git
	 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory
					  (concat
					   (car dotspacemacs-configuration-layer-path)
					   "snippets/")))
```

**Comment by vinurs** [comment]
there is no solution for this?

**Comment by syl20bnr** [comment]
Best would be to try to reproduce it without Spacemacs, if it happens without Spacemacs then it is a bug with desktop-save-mode and you could report it upstream.

**Comment by vinurs** [comment]
Hi，I've tried that already, without spacemacs it works well

**Comment by bmag** [comment]
@vinurs as an alternative to desktop-save-mode, you can set `dotspacemacs-auto-resume-layouts` to `t` to enable session restoration via spacemacs-layouts (it uses `persp-mode` behind the scenes).

If that doesn't work, can you provide a detailed step-by-step reproduction recipe?

**Comment by vinurs** [comment]
@bmag  I tried that:
(setq dotspacemacs-auto-resume-layouts t)
it doesn't work, it only reopen the file opened by C-x C-f

It can be reproduced by this:
1. open emacs
2. open file in terminal by: (emacsclient test.el &), then the file will be opened
3. close emacs
4. reopen emacs, the file opened by emacsclient doesn't reopened

**Comment by bmag** [comment]
> (setq dotspacemacs-auto-resume-layouts t)

There should already be a `dotspacemacs-auto-resume-layouts` entry in your config file, which you can change. Although putting `(setq dotspacemacs-auto-resume-layouts t)` in `dotspacemacs/user-init` is also ok (I think).

> it doesn't work, it only reopen the file opened by C-x C-f

It works for me. After changing `dotspacemacs-auto-resume-layouts` to `t`, I've followed these steps:
1. open emacs: `$ emacs &` (from bash terminal)
2. open file from terminal: `$ emacsclient ~/tmp/temp.el &`
3. close emacs: `SPC q q`
4. reopen emacs: `$ emacs &`
After ~5 seconds `~/tmp/temp.el` is automatically opened.
Perhaps the `dotspacemacs-auto-resume-layouts` approach doesn't work for you due to changes between master branch and develop branch.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 3130cc6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.5 auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip t company-tooltip-align-annotations t)
 emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 markdown org
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control
 (latex :variables latex-enable-auto-fill t latex-enable-folding t)
 pdf-tools evil-cleverparens python command-log smex themes-megapack c-c++
 (clojure :variables clojure-enable-fancify-symbols nil)
 ruby common-lisp ibuffer octave imenu-list window-purpose nameless)
```

**Comment by bmag** [comment]
Using desktop-save-mode also works me. I disabled `dotspacemacs-auto-resume-layouts` and added this to my `dotspacemacs/user-config`:
```elisp
(desktop-save-mode)
(desktop-read)
```
Then:
1. open emacs: $ emacs & (from bash terminal)
2. open file from terminal: $ emacsclient ~/tmp/temp.el &
3. close emacs: SPC q q
4. reopen emacs: $ emacs &
`~/tmp/temp.el` is automatically opened.

**Comment by vinurs** [comment]
@bmag I recloned a clean spacemacs configuration, without other configurations, only:
`(desktop-save-mode)`
`(desktop-read)`
in `dotspacemacs/user-config`
 then dit the same as you, It works for me.
^_^ maybe there is sth wrong with my own configuration files, I'll try to find the root cause, thanks again

**Comment by vinurs** [comment]
I found that, I create a layer for my own, then I put the
(desktop-save-mode)
(desktop-read)
in the layer's config.el, it won't work, if I move it to user-config, it works.
I don't know why.

**Comment by bmag** [comment]
> in the layer's config.el, it won't work, if I move it to user-config, it works.

I think that's because `config.el` is evaluated before spacemacs home buffer is displayed, while user-config is called afterwards. You can use the hook `spacemacs-post-user-config-hook` to run your code after the loading process is done:
```elisp
(add-hook 'spacemacs-post-user-config-hook
          (lambda ()
            (desktop-save-mode)
            (desktop-read)))
```
