### ISSUE TITLE
void variable spacemacs//unset-scroll-margin

### ISSUE THREAD

**Issue by sooheon** [syl20bnr/spacemacs#6109]
[shell layer](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+tools/shell/packages.el#L312) and [erc layer](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+chat/erc/packages.el#L254) use this function in a hook, but this was undefined with the latest change in develop.

**Comment by darkfeline** [comment]
https://github.com/syl20bnr/spacemacs/pull/6113

**Comment by SShrike** [comment]
Yeah, the issue breaks `mcc` in python-mode.

```
Debugger entered--Lisp error: (void-function spacemacs//unset-scroll-margin)
  spacemacs//unset-scroll-margin()
  run-hooks(change-major-mode-after-body-hook comint-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook comint-mode-hook))
  run-mode-hooks(comint-mode-hook)
  comint-mode()
  compilation-start("python setup.py" t)
  compile("python setup.py" t)
  (if arg (call-interactively (quote compile)) (setq compile-command (format "python %s" (file-name-nondirectory buffer-file-name))) (compile compile-command t) (save-current-buffer (set-buffer (get-buffer "*compilation*")) (inferior-python-mode)))
  spacemacs/python-execute-file(nil)
  call-interactively(spacemacs/python-execute-file nil nil)
  command-execute(spacemacs/python-execute-file)
```

**Comment by syl20bnr** [comment]
I'm on it.

**Comment by syl20bnr** [comment]
Merged into develop branch.
I hesitated between put the function back or remove the hook, I went for the removal of the hooks, I guess a user setting the scroll margin themselves should take care of ERC and the like as well.
