### ISSUE TITLE
Eshell: 'run-hooks: Symbol's function definition is void: spacemacs//unset-scroll-margin'

### ISSUE THREAD

**Issue by microamp** [syl20bnr/spacemacs#6114]
#### Description
Eshell: 'run-hooks: Symbol's function definition is void: spacemacs//unset-scroll-margin'

#### Reproduction guide
- Start Emacs
- `M-x spacemacs/shell-pop-eshell`
- Switch to the `*Messages*` buffer
- Find the error message where it says `run-hooks: Symbol's function definition is void: spacemacs//unset-scroll-margin`

I see the function removed in [one of the recent commits](https://github.com/syl20bnr/spacemacs/commit/e06929d).

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. fd756a1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults clojure colors csv elfeed elixir emacs-lisp git
                 (go :variables gofmt-command "goimports" go-tab-width 2 go-use-gometalinter t)
                 html ipython-notebook jabber
                 (javascript :variables js2-basic-offset 2 js-indent-level 2)
                 lua markdown
                 (mu4e :variables mu4e-installation-path "/usr/local/Cellar/mu/HEAD/share/emacs/site-lisp/mu/mu4e")
                 ocaml org osx puppet python rcirc restclient
                 (scala :variables scala-auto-insert-asterisk-in-comments t)
                 search-engine
                 (shell :variables shell-default-height 40 shell-default-position 'bottom)
                 shell-scripts sml sql syntax-checking version-control)
```

**Comment by microamp** [comment]
Appears to be a duplicate of https://github.com/syl20bnr/spacemacs/issues/6114.

**Comment by syl20bnr** [comment]
This is a duplicate of itself ? :-)

**Comment by microamp** [comment]
> This is a duplicate of itself ? :-)

Good catch! 

Thanks for fixing it by the way!
