### ISSUE TITLE
Haskell, Windows, Freezing, Lisp error: (error "Process <cwd> not running")

### ISSUE THREAD

**Issue by YellowOnion** [syl20bnr/spacemacs#6115]
I'm trying to get structured haskell mode working, I just completely removed spacemacs, but this issue still happens.

my `.spacemacs` file:
```
auto-completion
(haskell :variables
              haskell-enable-shm-support t
              haskell-enable-ghc-mod-support t
              haskell-enable-hindent-style "chris-done"
              haskell-process-type 'stack-ghci)
syntax-checking
```

What is strange is that the error is says the name of the Process is the current working directory (I assume it's mangling the file name some how?)

There's a similar error on opening a file:
`
File mode specification error: (error "Process <cwd> not running")
`

Edit: on further investigation, it's only on this directory that I'm having this issue (currently anyway).
How do I get the backtrace "out" of the editor? Its saying that 'y' (being yank) is undefined.

**Comment by StreakyCobra** [comment]
@d12frosted Any hint about the current status of structured haskell mode?

**Comment by d12frosted** [comment]
Well, @jhenahan is willing to dig into shm support to make it usable under evil. But it's not related to this issue. 

I never seen such error and from what I know - SHM is supported on windows, so there's must be something obviously wrong. 

@YellowOnion 
Just a shot in the sky - try updating all emacs packages and make sure that shm is installed and up to date.

**Comment by YellowOnion** [comment]
I got the latest version of emacs provided by msys2 (which is the official method to install the app).

shm is working (I figured out how spacemacs doesn't use the "official" method for install and must use stack to build a binary.)

I just updated my packages, still freezing/100% CPU of one core.

Could be related to ghc-mod but I don't see any messages relevant ghc-mod.

**Comment by d12frosted** [comment]
> I figured out how spacemacs doesn't use the "official" method for install

What do you mean by this? Spacemacs doesn't install any external dependencies. It's up to you. How you install them - up to you, the only requirement - `shm` must be available in Emacs either by setting `shm-program-name` or placing executable somewhere in your `PATH` or... well there are several ways for achieving this. But this is properly not they right place to discuss them.

Back to freeze. Please, try setting `haskell-enable-shm-support` and `haskell-enable-ghc-mod-support` to `nil` to see if the problem gone. If it's gone - try enabling one of them to see which one causes freeze.

Also, telling when exactly freeze occurs would be helpful. Did you just open hs file and Emacs become unresponsive? Or have you performed any specific actions?

**Comment by YellowOnion** [comment]
What I mean to say is that shm install method via the github readme page also specifies that you direct emacs to the elisp folder it provides, I found another method (that directly uses stack), and it seems to  work.

setting `haskell-enable-ghc-mod-support` to `nil` fixed the freezing.

**Comment by d12frosted** [comment]
Ah, that's because manual installing requires more steps 😸 

OK, `ghc-mod`. It might be because of several reasons (though I don't remember any freezes, but it's windows, so anything is possible). To start with:

- if you're using `stack` - make sure that you don't have any cabal artefacts lying around in the root of project you're working on - they confuse `ghc-mod`
- if you're using `stack`, please share `ghc-mod --version` and version of `lts` you're using in the project emacs freezes on
- check that `ghc-mod debug` executes without any errors or warning in the root of project

But in case you don't have time to dig into this - you can avoid using `ghc-mod` without much loss if you're on develop.

**Comment by d12frosted** [comment]
Hey @YellowOnion,

Any update in this issue? Just as a note, on develop branch by default we use `ghci` completion by default which doesn't require any external programs like `ghc-mod` to be installed - only `ghc` and `cabal` / `stack`. So it might be helpful until this issue is fixed.

**Comment by YellowOnion** [comment]
@d12frosted hey sorry I got distracted with life, I really haven't touched the project since, and I can't reproduce it with others I've made. You can probably just close this since the project wasn't made properly, I've remembered that I originally wasn't using a stack sandbox, but had to add a stack.yaml file to trick it in to using stack instead of vanilla ghc, There's probably a better way to do this.

**Comment by d12frosted** [comment]
@YellowOnion Thanks for the response. Yeah, I'm going to close this issue then. If you ever encounter similar one in future, just reopen this one or create new one.

But I have several comments.

1. There is no such thing as `stack` sandbox. Only `cabal` has sandboxes. 😸 
2. `Stack` basically works only with `stack` projects. For example, running `stack build` in directory that doesn't have `stack.yaml` file, it will kindly tell you that you are not in `stack` project. The good solution is to call `stack init`. So this is the better way 😸
