### ISSUE TITLE
gtags ivy support

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#6121]
Currently the gtags layer only supports helm.  It should be improved to work with ivy as well.

**Comment by dubnde** [comment]
and `cscope` please

**Comment by bmag** [comment]
For future reference:
- [emacs-counsel-gtags](https://github.com/syohex/emacs-counsel-gtags): ivy+gtags support
- I did not find a package that provides ivy+cscope support
- [xcscope.el](https://github.com/dkogan/xcscope.el): a non-ivy and non-helm interface to cscope

**Comment by dubnde** [comment]
cscope layer currently us [helm-cscope](https://github.com/alpha22jp/helm-cscope.el)

**Comment by Miciah** [comment]
Looks like #9498 / https://github.com/syl20bnr/spacemacs/commit/c61ae1a1c19a8af4475a25d94d1b8fd0acf08dd8 added gtags ivy support on the develop branch.
