### ISSUE TITLE
auto change to emacs state(blue state)

### ISSUE THREAD

**Issue by linuxr** [syl20bnr/spacemacs#6125]
Hi，when I update to latest develop branch（ac104d273917e224638606ca579f26a4602a5f98），
I have encountered a problem, could you  help me.

I have write some code in evil-insert state(green state), then press ESC to go to evil-nomal state(orange state), then press SPC f s to save buffer, after several seconds, then press i to continue coding.
The problem is that when I press i , the spacemacs change to emacs state(bule state), not the evil-insert state.

**Comment by robbyoconnor** [comment]
Did you read the template? You were supposed to do it via `SPC h I`

**Comment by robbyoconnor** [comment]
I've had this happen -- manually running `M-x evil-insert-state` has usually fixed it...not sure why it happens...

**Comment by linuxr** [comment]
@robbyoconnor thank you for your reply.
I will use `SPC h I` to report issue next time.

I find this problem will occur just when I input Chinese, when I input English, this problem doesn't occur.
Maybe this the problem of fcitx!

**Comment by linuxr** [comment]
I have solved this problem by update  [fcitx.el](https://github.com/cute-jumper/fcitx.el)

I have just updated [fcitx-remote-for-osx](https://github.com/CodeFalling/fcitx-remote-for-osx) before, and I think this is the reason of the problem.

**Comment by ryukinix** [comment]
This is weird. I have that same on master. How I can go back to the evil state?
