### ISSUE TITLE
Wrong OSX installation instructions on master

### ISSUE THREAD

**Issue by d12frosted** [syl20bnr/spacemacs#6126]
Installation section for OSX in `README` file is a bit messed right now. On [develop](https://github.com/syl20bnr/spacemacs/tree/develop#os-x) it looks right, while on [master](https://github.com/syl20bnr/spacemacs#os-x) it mixes `emacs-plus` and `emacs-mac-port`. I believe that we just forgot to cherry-pick (or whatever) this commit: https://github.com/syl20bnr/spacemacs/commit/fa5e66c799e74325fbd513cdfa9348b53e023491

**Comment by d12frosted** [comment]
cc @syl20bnr

**Comment by syl20bnr** [comment]
Thank you, Backported to 0.105.21
