### ISSUE TITLE
smartparens vanish, replaced with colored box

### ISSUE THREAD

**Issue by quicknir** [syl20bnr/spacemacs#6131]
#### Description
Smartparens makes my parentheses vanish, and replace them with boxes (which are the same color as the paren/brace was supposed to be).

#### Reproduction guide
- Start Emacs
- Open a .cpp file
- put cursor between two braces

*Observed behaviour:*
As above.

*Expected behaviour:*
See the actual character in a different color, not just a box.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```
![screenshot from 2016-05-25 18-08-55](https://cloud.githubusercontent.com/assets/10457096/15557929/2be04564-22a4-11e6-89c1-5b176f5d928a.png)

**Comment by TheBB** [comment]
Are you sure this is due to smartparens? Looks more like rainbow-delimiters to me.

**Comment by quicknir** [comment]
Haven't seen this issue in a while, going to close this.
