### ISSUE TITLE
Can't force tabs in python-mode

### ISSUE THREAD

**Issue by kennymalac** [syl20bnr/spacemacs#6137]
Maybe I'm extremely naive, but I have been unable to get the python layer to actually accept tabs for indention using spacemacs. I've tried everything: smart tabs, putting a config in user-config/user-init. I recognize PEP8 uses spaces, but I do not care about that right now. I am not migrating an entire codebase to use 4 spaces because of some arbitrary standard.
What's killing me is I got it working for new python files, but I still am lost as to how to get all python files to work with tabs only for indention.

Here is the code I was using:
```
;; Attempt 2
   (require 'smart-tabs-mode)
    	(smart-tabs-advice python-indent-line-1 python-indent)
    	(add-hook 'python-mode-hook
    						(lambda ()
    							(setq indent-tabs-mode t)
                  (setq tab-width (default-value 'tab-width))
    							;; (require 'smart-tab)
    							;; (smart-tabs-advice py-indent-line py-indent-offset)
    							;; (smart-tabs-advice py-newline-and-indent py-indent-offset)
    							;; (smart-tabs-advice py-indent-region py-indent-offset)
    							))
    	(smart-tabs-advice py-indent-line py-indent-offset)
    	(smart-tabs-advice py-newline-and-indent py-indent-offset)
    	(smart-tabs-advice py-indent-region py-indent-offset)

  ;; Attempt 1
  (add-hook 'python-mode-hook
            (lambda ()
              (setq indent-tabs-mode t)
              ;(setq tab-width 4)
										;(setq python-indent 4)
              (setq py-indent-tabs-mode t)
              (setq-default indent-tabs-mode t)
              ;(setq-default tab-width 4)
							;(setq-default python-indent 4)
              (setq-default py-indent-tabs-mode t)
              (add-to-list 'write-file-functions 'delete-trailing-whitespace)))
  )
```

what's interesting is I can't get smart-tabs-mode to load in user-init, either. If someone could help me out I'd appreciate it!

**Comment by TheBB** [comment]
```elisp
  (add-hook 'python-mode-hook (lambda () (setq indent-tabs-mode t)))
```

This is quite sufficient for me to get tabs. If that doesn't work for you maybe you can show me a file I can open that reproduces the problem?

**Comment by kennymalac** [comment]
The problem is actually general to any programming language. If you have tabs in one file but spaces formatting in another there is no easy way to change the default.

I.e. if I have 10 python files in tabs, and switch to a python file that uses spaces, but my setting is setup for python tabs, it will still use tabs when the file is clearly indented by spaces.

"Smart" tabs doesn't seem to do much. I have to annoyingly change the local vars everytime I switch between projects.
