### ISSUE TITLE
Helm moves the mouse to the upper-right hand corner of the frame

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#6138]
#### Description

The mouse cursor gets moved to the upper-right hand corner of the frame if a helm prompt is closed with ESC.

#### Reproduction guide
- Start Emacs
- Open a helm prompt (e.g., `SPC SPC`)
- Hit `ESC`

*Observed behaviour:*

The mouse cursor is moved to the upper-right corner of the frame.

*Expected behaviour:*

My mouse stays where I left it...

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. ac104d2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm better-defaults git
      (auto-completion :variables auto-completion-return-key-behavior nil)
      org spell-checking syntax-checking
      (shell :variables shell-default-shell 'ansi-term)
      emoji emacs-lisp markdown latex yaml c-c   html haskell go javascript python systemd
      (rust :variables rust-format-on-save nil))
```

**Comment by StreakyCobra** [comment]
:flushed: What the hell…

I can't reproduce this on my Archlinux setup though.

**Comment by Stebalien** [comment]
Just to make sure, I killed my window manger/keybinding manager (bspwm/sxhkd) and I can still reproduce. I'm using daemon/client, FYI.

**Comment by Stebalien** [comment]
This shows up when `mouse-autoselect-window` is set.

**Comment by StreakyCobra** [comment]
Indeed,  `mouse-autoselect-window` is responsible of this.

I just tried on stock Emacs with `SPC q D helm RET` and this happens there too, so it's not a Spacemacs bug. This should be reported upstream.

**Comment by Stebalien** [comment]
Reported upstream. Sorry, I somehow missed your the notification for your comment.

**Comment by Stebalien** [comment]
Fixed upstream.
