### ISSUE TITLE
Writing a bibliography layer, needs help

### ISSUE THREAD

**Issue by wwguo** [syl20bnr/spacemacs#6141]
Hi everyone,

I'm learning writing layer by doing. I write a simple layer based on `ebib'. Actually ebib is the only package that the layer uses. 

The layer works as expected except one issues:

- Ebib defines many keybindings, such as `a' for add a new bib entry. Those keybindings conflict with those of Evil. How to set Ebib's own keybindings as default when its buffers are active?

To use the layer, two variables should be set in user-config, such as:

(setq ebib-preload-bib-files '("~/my/path/to/mybibfile.bib")
        ebib-file-search-dirs  '("~/my/path/to/documents/folder/"))

The layer is attached here. 
[bibliography.tar.gz](https://github.com/syl20bnr/spacemacs/files/285573/bibliography.tar.gz)

**Comment by wwguo** [comment]
I solved the problem by the following line: 

`(evil-set-initial-state 'ebib-index-mode 'emacs) `

**Comment by TheBB** [comment]
We usually handle non-editing modes like that by evilifying the mode. This allows evil's own most typical keybindings to work, while rebinding the rest according to a predictable pattern.

See [evilified modes](http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline50) in the main documentation for more information. You can use the macro `evilified-state-evilfy-map` to do this. There are many example usages in the Spacemacs source code, for example in [magit](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+source-control/git/packages.el#L175).

**Comment by TheBB** [comment]
You can close this issue if your own solution or mine is satisfactory.

**Comment by paynito** [comment]
Hi can you add me a Collaborator?  Currently when I open a .bib space line tells me I'm in BibTeX mode. I use org-ref extensively so I will concentrate on making your ebib layer play nice with org-ref.

**Comment by wwguo** [comment]
I attached the modified layer. I haven't written the Readme yet. 

Put the layer into your `private` folder and then just put `bibliography` in `dotspacemacs-additional-packages`. Wen you restart emacs, ebib will be installed and then you can call Ebib by `SPC : ebib`.

[bibliography.tar.gz](https://github.com/syl20bnr/spacemacs/files/296951/bibliography.tar.gz)
