### ISSUE TITLE
There is no documented, simple way to turn off smartparens

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#6144]
#### Description :octocat:
1. Excluding the smartparens package doesn't work; it still gets installed. I can create an immutable `elpa/smartparens-$version` file to keep it from being installed but that causes several layers to complain loudly.
2. I can call `spacemacs/toggle-smartparens-off` and `spacemacs/toggle-smartparens-globally-off` in my config but this doesn't make a difference (it's still enabled automatically).

My current solution is the following:

``` lisp
(add-hook 'smartparens-enabled-hook #'spacemacs/toggle-smartparens-off)
(spacemacs/toggle-smartparens-globally-off)
```

But this is ridiculous.

![Useless Machine](http://i.imgur.com/a9obRN7.gif)
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 380be09)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm better-defaults git
      (auto-completion :variables auto-completion-return-key-behavior nil)
      org spell-checking syntax-checking
      (shell :variables shell-default-shell 'ansi-term)
      emoji emacs-lisp markdown latex bibtex csv yaml c-c   html haskell go javascript python systemd
      (rust :variables rust-format-on-save nil))
```

**Comment by syl20bnr** [comment]
Some packages relies on it as a dependency, we cannot do anything for this.

Putting smartparents in dotspacemacs-excluded-packages will effectively remove all Spacemacs configuration regarding smartparents. Not much we can do about packages using it internally.

**Comment by Stebalien** [comment]
The only package mentioning smartparens was evil-lisp-state. Excluding it and smartparens doesn't fix anything (it still get's installed).

Also, can you think of any reason this might have started causing problems after updating to the latest develop commit this morning (something changed between last night and noon today)? Everything worked fine before then. It turns out that my above code doesn't even entirely turn off smartparens as it still causes trouble in rust-mode (which doesn't mention smartparens) with smartparens off:

* Opening a parentheses prints out "Unmatched expression." (an error message from the smartparens package).

And sometimes (inconsistent):
* Starting with "(A " (space intentional) and typing a closing ")" yields "(A) )".
* Starting with "B" and prefixing it with "(A)" yields "(AB)" (the closing parenthesis *jumps* over the "B").

The rust-mode package doesn't pull in smart parentheses!

**Comment by Stebalien** [comment]
Rolling back my repo to ec3ea5b41e91e8f65662a1950d5675b66ffe3329 and excluding smartparens fixes my problems. smartparens is still installed and show-smartparens-mode is still enabled by default (that's fine) but smartparens-mode itself isn't turned on by default (and doesn't get itself into this zombie refuses-to-completely-turn-off state).

**Comment by syl20bnr** [comment]
Interesting, thank you for the investigation, I'll look into it.

**Comment by Stebalien** [comment]
As of d98be63dfa3c0bb10a2967bb6e9f678132390ca8, the old behavior has been restored (smartparens can be turned off by default by excluding the package). However, if the package isn't explicitly excluded, calling `spacemacs/toggle-smartparens` or `smartparens-mode` to turn of smartparens doesn't completely turn it off (this is the behavior that was present prior to 37dfa47).

Would you like me to move this to a new bug report? Also, thanks for bearing with me here and sorry for the exploratory nature of this report.

**Comment by TheBB** [comment]
Can you provide some clearer reproduction steps? I tried playing around with toggling smartparens and it seems to behave as expected.

**Comment by Stebalien** [comment]
If you try excluding smartparens, you should notice a difference between simply disabling it and excluding it.

For example, if you simply disable it, an unmatched parentheses (in a scratch buffer) will be highlighted in red. If you exclude the package entirely, it won't be highlighted at all. Unfortunately, I can't consistently reproduce the other problems. They seem to occur at random in some modes (notably, rust-mode).

**Comment by afcowie** [comment]
I've got smartparens excluded, but try as I might, I can't get it to stop highlighting the opening brace, bracket, or parenthesis in red when I close a symbol pair. Is there a toggle for that?

**Comment by trishume** [comment]
For anyone coming to this issue looking for a good way to disable smartparens, try this snippet which allows you to disable it for certain pairs while keeping the package around and running:

```elisp
  (eval-after-load 'smartparens
    '(progn
       (sp-pair "(" nil :actions :rem)
       (sp-pair "[" nil :actions :rem)
       (sp-pair "'" nil :actions :rem)
       (sp-pair "\"" nil :actions :rem)))
```

**Comment by makkus** [comment]
I'm running into a problem with inferior python mode, where, when there is a lot of output (say, a large json document), spacemacs hangs, and I'm 99% it's because of smartparens (when sending a SIGUSR2 kill signal emacs shows it's working on smartparens functions) . I could reproduce that with a fresh spacemacs install, so I'm fairly confident it's not any of my additional configuration.

The only way I could prevent that from happening is using @trishume 's eval-after-load trick. I don't mind having smartparens around usually, but I'd like my python code not to hang when possible. I am the only one who has that problem? Is there a way to disable smartparens just for the inferior python mode?

**Comment by makkus** [comment]
Hm, this seems to work for me:

```
    (eval-after-load 'smartparens
    '(progn
       (sp-local-pair 'inferior-python-mode "(" nil :unless nil)
       (sp-local-pair 'inferior-python-mode "[" nil :unless nil)
       (sp-local-pair 'inferior-python-mode "'" nil :unless nil)
       (sp-local-pair 'inferior-python-mode "\"" nil :unless nil)))
```

**Comment by kootenpv** [comment]
I have the same situation as @makkus and it has been bothering me for a very very long time.
I would really like to have my cake and eat it (I like the syntax highlighting and emacs not to hang).

**Comment by ChShersh** [comment]
@trishume Unfortunately your solution doesn't work for me :cry: I put your lines inside `(defun dotspacemacs/user-config () )` but nothing happened for me :disappointed:
Solution from issue itself also doesn't work for me. Basically, nothing helps to stop Spacemacs automatically insert `)` when I press `(` :sob: 

Emacs version: 24.5.1
Spacemacs version: 0.200.10
Ubuntu Version: 16.04
