### ISSUE TITLE
Error when using dotspacemacs-fullscreen-at-startup t 

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#6145]
When  my `.spacemacs` has `dotspacemacs-fullscreen-at-startup t`  it throws void function `spacemacs/toggle-frame-fullscreen` error at startup. 

*Latest develop on Emacs 24*

**Comment by robbyoconnor** [comment]
Use the template or else :angry:

**Comment by JAremko** [comment]
@robbyoconnor  I saw this coming :smile: 
Unfortunately it breaks too early so I can't use Vim bindings to copy the function's output, let alone calling it  :cry: 

Fine... 
======

#### Description :octocat:
Error when using dotspacemacs-fullscreen-at-startup t

#### Reproduction guide :beetle:
- Start Emacs
- see the error

*Observed behaviour:* :eyes:
 :boom: 

*Expected behaviour:* :broken_heart:
not :boom: 

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp restclient html javascript markdown shell-scripts typescript yaml git github evil-snipe vinegar colors auto-completion smex spell-checking version-control syntax-checking shell search-engine prodigy org gnus clojure ranger dockerfile
      (go :variables go-use-gometalinter t))
```

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-variable system)
  eval(system nil)
  eval-last-sexp-1(nil)
  eval-last-sexp(nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)

```
*^^^^^Probably the result of me facerolling keyboard mindlessly to call the report thingy.*

**Comment by StreakyCobra** [comment]
@JAremko If it was working before, can you try to bisect to find the problematic commit? I wouldn't be surprised if 37dfa4796176ee3851f4c5c96395d4614b275ca7 get out of the loop

> Spacemacs branch: nil (rev. nil)

Why?

**Comment by JAremko** [comment]
@StreakyCobra  Because I remove `.git` folder. Don't ask why.

**Comment by StreakyCobra** [comment]
> Because I remove .git folder.

Why?

**Comment by JAremko** [comment]
@StreakyCobra  Because it prevents my  dockerized Spacemacs from updating. And for other "historical" reasons.

**Comment by StreakyCobra** [comment]
:joy: I was just kidding. Don't ask me to not ask why :grimacing:

**Comment by JAremko** [comment]
@StreakyCobra  So you don't want to know about " other historical reasons." :wink:

**Comment by StreakyCobra** [comment]
Now you say it, yes. What are the "other historical reasons"?

**Comment by JAremko** [comment]
@StreakyCobra  "It's a secret" :point_up:

**Comment by JAremko** [comment]
@StreakyCobra  It works with 7945d39208ec494e5476859fe6e84e0f9a1e3d47 but doesn't with 37dfa4796176ee3851f4c5c96395d4614b275ca7 and its parent c6e47c0306b6cb199b0ec39b8bdc4aef20430b3e

**Comment by StreakyCobra** [comment]
~~Another commit that may be related is c35e4ee27b437c40ce57c55675eef98d69e4ba73~~

I'll bisect myself :stuck_out_tongue:

**Comment by StreakyCobra** [comment]
`git bisect` told me that c35e4ee27b437c40ce57c55675eef98d69e4ba73 is the first bad commit.

@syl20bnr :point_up: Another bug regarding load order. `config.el` needing a function from `funcs.el` that is only loaded afterward.

**Comment by syl20bnr** [comment]
Thanks for the investigation, I will work on funcs.el issues this evening.

**Comment by robbyoconnor** [comment]
I know this contributes zero but I love this thread so much

![[]](http://gifrific.com/wp-content/uploads/2014/02/Maurice-Moss-Eating-Popcorn-The-IT-Crowd.gif)

**Comment by syl20bnr** [comment]
Should be fixed on last develop :-)

For those interested be sure to read the commit message for core changes.

**Comment by robbyoconnor** [comment]
It introduced some other fun stuff though
