### ISSUE TITLE
Buffer command fails on buffer visiting file whose parent folder is deleted

### ISSUE THREAD

**Issue by sptzxbbb** [syl20bnr/spacemacs#6146]
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description

**This bug doesn't exist in native emacs** and I think there are some bugs in **spacemacs's buffer management**. When I delete the directory of the file visited by current buffer, some buffer commands fail on this buffer. For example, kill-buffer, switch-to-scratch-buffer, helm mini which totally doesn't make sense.  When I restore the directory, they work again.  

Actually, this bug **shows up in dev branch** as well. I've try it myself.
#### Reproduction guide
- Start Emacs
- Create a folder called test and a file called foo in it
- Open foo with spacemacs
- Delete folder test
- Call kill-buffer on foo buffer

_Observed behaviour:_
Command fail. The minibuffer shows 

> "Setting current directory: no such file or directory, /home/peter/Desktop/test/"

_Expected behaviour:_
Foo buff is killed successfully
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(yaml auto-completion better-defaults emacs-lisp git markdown org c-c   python java html colors
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (chinese :variables chinese-enable-fcitx t)
      syntax-checking version-control)
```

**Comment by StreakyCobra** [comment]
I can not reproduce this on `develop` with my setup

-----

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 380be09)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 bb-git bb-latex bepo better-defaults c-c++ clojure colors command-log csv dash deft dockerfile
 (elfeed :variables rmh-elfeed-org-files
         (list "~/org/main.org"))
 encoding emacs-lisp emoji erc erlang ess evil-cleverparens extra-langs finance git github haskell html imenu-list ipython-notebook java javascript
 (keyboard-layout :variables kl-layout 'bepo)
 latex markdown mu4e nginx no-dots ocaml org pandoc php plantuml python ranger rebox restclient ruby rust scala semantic shell shell-scripts spacemacs-helm speed-reading
 (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
 sql syntax-checking systemd themes-megapack theming typography
 (version-control :variables version-control-diff-tool 'diff-hl)
 vimscript yaml)
```

**Comment by TheBB** [comment]
Same, can't reproduce.
