### ISSUE TITLE
Layer request vue language

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [syl20bnr/spacemacs#6148]
Hello,

There is a layer for .vue files but it is not in the layers in the main repository. Is there any reason for that ?

Could someone add it. I don't know how to add layers.

Best regards

**Comment by syl20bnr** [comment]
Hello, where is this layer ?

**Comment by GuillaumeLeclerc** [comment]
Here it is : https://github.com/CodeFalling/vue-mode

**Comment by syl20bnr** [comment]
OK, this is a package, not a layer, it happens that @CodeFalling also provides instructions for Spacemacs user it his READMEs (which is great, kudos for that 👍 ). These instructions consider that you already have a custom layer where you can add the `vue-mode` package.

In layers distributed with Spacemacs we avoid to define layers for just one package. There is the variable `dotspacemacs-addtional-packages` of your dotfile for this. You can add the recipe to this variable:

```elisp
(setq dotspacemacs-additional-packages
  '((vue-mode :location (recipe :fetcher github :repo "codefalling/vue-mode"))))
```

Restart Emacs and it will be installed.

When the package is in MELPA you can add it like this:

```elisp
(setq dotspacemacs-additional-packages '(vue-mode))
```

Note that the variable `dotspacemacs-additional-packages` should be already in your dotfile. You can find it with `SPC h . additional-packages RET` (or `SPC h SPC`).

**Comment by kevin-DL** [comment]
Thanks a lot for that.

**Comment by d12frosted** [comment]
Closing this issue since @syl20bnr answered it. 

Let us know if you still have any troubles with `vue-mode`, @GuillaumeLeclerc.

**Comment by pdilyard** [comment]
Just FYI for anyone trying to get this to work, the package is now available in MELPA, so all you need to do is:
```lisp
(setq dotspacemacs-additional-packages '(vue-mode))
```
And reload your .spacemacs file.

**Comment by watzon** [comment]
vue-mode is no longer being maintained, so maybe integrating vue wouldn't be such a bad idea

**Comment by d12frosted** [comment]
@watzon why do you say that it's unmaintained? Latest commit was like 14 days ago from what I see. And I don't see any announcements.

P. S. In my opinion integrating something that is not maintained **is** a bad idea 😸

**Comment by watzon** [comment]
@d12frosted I think I found the wrong one at first

**Comment by bersace** [comment]
There is a `react` layer. Maybe that's would be relevant to have a vue layer for the framework, not only the `.vue` files.

**Comment by standino** [comment]
I think we need to create a vue layer according to this https://medium.com/@aria_39488/improving-vue-mode-for-better-vue-js-editing-inside-of-spacemacs-4509f0577ea0

**Comment by mspinelli** [comment]
@stardino

I'm struggling to get flycheck to work. Liniting is happening at at all. The medium article doesn't work either. You need to make these changes (but again it's not working despite checking the linter with `SPC e v` showing everything is configured).
In `dotspacemacs/user-config()`:
```
  ;; https://medium.com/@aria_39488/improving-vue-mode-for-better-vue-js-editing-inside-of-spacemacs-4509f0577ea0
  (require 'vue-mode)
  (add-to-list 'vue-mode-hook #'smartparens-mode)

  (require 'lsp-mode)
  (require 'lsp-vue)
  (add-hook 'vue-mode-hook #'lsp-vue-mmm-enable)
  ;; Error: (Spacemacs) Error in dotspacemacs/user-config: Flycheck support has been moved
  ;; to package lsp-ui. Please consult https://github.com/emacs-lsp/lsp-ui for documentation on lsp-ui-flycheck.
  ;;(with-eval-after-load 'lsp-mode
  ;;  (require 'lsp-flycheck))
  (require 'lsp-ui)
  (add-hook 'lsp-mode-hook 'lsp-ui-mode)
  (add-hook 'lsp-ui-mode-hook 'flycheck-mode)
  (add-hook 'lsp-ui-mode-hook 'add-node-modules-path)

  (require 'company-lsp)
  (push 'company-lsp company-backends)
  (add-to-list 'company-backends 'company-tern)
  (add-hook 'js-mode-hook #'tern-mode)

  (require 'company)
  (global-company-mode)
  (global-set-key (kbd "TAB") #'company-indent-or-complete-common)

  ;; https://github.com/emacs-lsp/lsp-mode/issues/318

  (setq lsp-ui-doc-enable nil
        lsp-ui-peek-enable nil
        lsp-ui-sideline-enable nil
        lsp-ui-imenu-enable nil
        lsp-ui-flycheck-enable t)
```

**Comment by standino** [comment]
@GuillaumeLeclerc  & @d12frosted 

I think we should reopen this issue since we need to make multi-packages to work together. 

Thanks.

**Comment by lawrsp** [comment]
I have made one https://github.com/lawrsp/vue-layer 
try it by clone to your private layers directory  .e.g:

```bash
git clone git@github.com:lawrsp/vue-layer.git  ~/.spacemacs/layers/vue
```

**Comment by lawrsp** [comment]
@svepe 
It seems you didnot install the `lsp` layer
make sure  `lsp` is in the  `dotspacemacs-configuration-layers` list. 
or  make sure your  spacemacs's is in `develop`  branch, the `master` branch doesn't contains the `lsp` layer.

**Comment by thanhvg** [comment]
Hi,
@lawrsp vue layer is no longer working because of major breaking change in `lsp-mode` package.

I am working toward a vue layer PR. You can check it out as a private layer at https://github.com/thanhvg/vue
It works with dev branch. Features include: lsp, eslint, prettier, emmet-mode...
Feedback and contributions are welcome. 

Thanks

**Comment by x-ji** [comment]
@thanhvg Hi, your layer is working great for me. Would you mind opening a PR to add this as an official layer? It wasn't easy for me to find it out there.

**Comment by dbrw** [comment]
I am very excited for this PR!
Great work!

**Comment by duianto** [comment]
This is the PR that dbrw is referring to: Vue layer #12977
