### ISSUE TITLE
Why were the inferior-shell bindings removed from the ESS layer README.orrg?

### ISSUE THREAD

**Issue by alxempirical** [syl20bnr/spacemacs#6149]
#### Description :octocat:

@izahn's docs for the ESS inferior-shell bindings seem useful, so I'm curious
why they were reverted a761c0de. For instance, The binding `SPC m s i j` seems
to DTRT, as long as you're in a `.jl file.`

Has documentation for the bindings moved somewhere else?

#### Reproduction guide :beetle:
N/A, this is a doc bug.  

*Observed behaviour:* :eyes:

*Expected behaviour:* :broken_heart:

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 380be09)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(javascript c-c   clojure dockerfile emacs-lisp erc eyebrowse ess git github markdown org python shell-scripts spell-checking themes-megapack
            (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            (syntax-checking :variables python-test-runner 'pytest flycheck-pylintrc "~/.config/flake8" flycheck-checker-error-threshold 1500))
```

#### Backtrace :paw_prints:
```

```

**Comment by syl20bnr** [comment]
cc @izahn ;-)

**Comment by izahn** [comment]
If I remember correctly we ditched those bindings in favor of global
binding to `SPC a '`. See https://github.com/syl20bnr/spacemacs/pull/4600

**Comment by TheBB** [comment]
`SPC m s i` or `SPC m '` should open the REPL of whatever programming language you're using, and `SPC a '` is a global catalogue of REPLs that can be accessed from any buffer.

**Comment by TheBB** [comment]
By the way you seem to have linked to the commit where they were added, not where they were removed.
