### ISSUE TITLE
Toggle "Linum-Relative" functionality suggestion

### ISSUE THREAD

**Issue by TheGreenHabi** [syl20bnr/spacemacs#6151]
Very often I toggle relative line numbers with `SPC t r``` without toggling "Line Numbers" first.
And "Relative Numbers" do not toggle automatically "Line Numbers" if they are not enabled.

I suggest to add functionality to enable "Line Numbers" when user enables "Relative Line Numbers" without activating "Line Numbers First"

**Comment by syl20bnr** [comment]
I agree, would be more natural to have the same behavior for both toggles.

**Comment by deb0ch** [comment]
#7365

**Comment by TheBB** [comment]
Should be fixed in master.
