### ISSUE TITLE
php syntax color does't awake.

### ISSUE THREAD

**Issue by chenyangguang** [syl20bnr/spacemacs#6154]
after i install superemacs (develop branch), html,js file had awoke their syntax color, exepct php .

**Comment by kRITZCREEK** [comment]
superemacs <- next april fools pls

@chenyangguang try to install the php layer

**Comment by chenyangguang** [comment]
@iRITZCREEK, i'm still wondering.

**Comment by TheBB** [comment]
Did you add the php layer?

**Comment by chenyangguang** [comment]
@TheBB , Not yet. Do you mean this "spacemacs/layers/+lang/php/", It already was there. 


  dotspacemacs-configuration-layers
   '(
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     auto-completion
     better-defaults
     emacs-lisp
     git
     markdown
     org
     php
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     syntax-checking
     version-control
     )

**Comment by robbyoconnor** [comment]
@chenyangguang that was an april fool's joke :P

**Comment by chenyangguang** [comment]
Yet! Of Course. Just add the php  layer to .spacemacs. Then restart emacs. Emacs will install some packages after some minutes. Then it works! That's amazing!

**Comment by TheBB** [comment]
Good, I'm closing this then.
