### ISSUE TITLE
Setting shell layer defaults

### ISSUE THREAD

**Issue by quicknir** [syl20bnr/spacemacs#6157]
To set the shell layer default terminal, I tried following the instructions and added

```
(setq-default dotspacemacs-configuration-layers
  '(shell :variables shell-default-shell 'eshell))
```

in my dotspacemacs/user-config. This didn't seem to do anything. However, adding:

`(setq shell-default-shell 'multi-term)`

Did the trick. Any idea what gives?

**Comment by TheBB** [comment]
`dotspacemacs-configuration-layers` is a list of layers. You have tried enabling layers called `:variables` and `shell-default-shell` among others. I see the shell documentation is incorrect here, I'll fix it. You need another set of parens.

```elisp
(setq-default dotspacemacs-configuration-layers
  '((shell :variables shell-default-shell 'eshell)))
```

**Comment by TheBB** [comment]
Also note that you can't add that in `user-config`. It should be added to the existing list of layers you have in your dotfile, near the top.

**Comment by quicknir** [comment]
Oh dang, I see what you mean, I feel dumb. Thanks! This whole lisp thing is taking getting used to :-)

**Comment by quicknir** [comment]
Btw, as a closing thought it might be helpful to add to the term docs for some of us beginners the tip that it is possible to get key bindings to get transmitted into the shell if they are unbound from the emacs layer. E.g. I use:

```
(eval-after-load "Term"
     '(define-key evil-insert-state-map (kbd "C-e") nil))
```
To get ctrl-e to work properly in my terminal.
