### ISSUE TITLE
Non existing layer causes error

### ISSUE THREAD

**Issue by jtbm37** [syl20bnr/spacemacs#6158]
#### Description :octocat:
When adding a non existing layer it causes the below error.
I had the `spacemacs-helm` layer but it has just been renamed to `helm`.
I had the `slime` layer specified but it has been renamed a long time ago. 

#### Reproduction guide :beetle:
- Start Emacs
- Add foofoo to `dotspacemacs-configuration-layers`

*Observed behaviour:* :eyes:
The following error message is shown.
`Symbol's function definition is void: evil-define-key`
Spacemacs will be in a broken state. No user config loaded. 

*Expected behaviour:* :broken_heart:
An error saying an invalid layer has been included in `dotspacemacs-configuration-layers`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 46138cd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp
      (shell :variables shell-default-shell 'multi-term shell-enable-smart-eshell t)
      syntax-checking erc auto-completion emacs-lisp
      (git :variables git-enable-magit-svn-plugin t)
      org typescript csharp html javascript sql restclient gnus rust markdown
      (mu4e :variables mu4e-installation-path "/usr/share/emacs24/site-lisp/mu4e"))
```

**Comment by jtbm37** [comment]
As other layers will surely be renamed/removed in the future, we should ensure that we check for the existence of the layers in that list.

**Comment by syl20bnr** [comment]
Ouch I'll try to fix ASAP. Thank you for the report.

**Comment by syl20bnr** [comment]
Should be fixed in develop.

**Comment by jtbm37** [comment]
@syl20bnr Thank you.
