### ISSUE TITLE
Can't start spacemacs tutor (SPC h T)

### ISSUE THREAD

**Issue by devinrhode2** [syl20bnr/spacemacs#616]
I'm completely new to spacemacs, coming from sublime, and can't figure out how to run SPC commands. I alias'd `emacs=/usr/local/Cellar/emacs-mac/emacs-24.4-mac-5.2/bin/emacs` in my `bash_profile`, type `emacs` in iTerm 2 or Terminal.app, see "Spacemacs is ready" at the bottom, hit the spacebar, then 'h' and I see "h is undefined" on the bottom. If I do `emacs some/file.js` I find myself in insert mode. I just want to start the spacemacs tutor (SPC h T) but can't find anything anywhere as to the exact keys/steps and will add whatever I'm missing to the documentation.md or readme.

I'm on OS X 10.10 Yosemite, installed just as instructed, `git clone --recursive http://github.com/syl20bnr/spacemacs ~/.emacs.d` and then added the OS X configuration layer to my ~/.spacemacs file `((setq-default dotspacemacs-configuration-layers '(osx)
  "List of contribution to load."
)`

halp

**Comment by syl20bnr** [comment]
I guess that your dotfile has a syntax error. Reinstall a new one and add just `osx` in the list `dotspacemacs-configuration-layers` that is already in the installed dotfile. You just have to add the layer name, nothing more.

**Comment by devinrhode2** [comment]
Oh... so on this page: 
https://github.com/syl20bnr/spacemacs/blob/master/contrib/osx/README.md#install
This code:
```elisp
(setq-default dotspacemacs-configuration-layers '(osx)
  "List of contribution to load."
)
```
Should NOT be copy-pasted verbatim. So shouldn't `"List of contribution to load."` be a regular elisp comment, like this?
```elisp
;; List of contribution to load.
```

Spacemacs loaded and I see the proper solarized light theme. Awesome!

**Comment by syl20bnr** [comment]
The example assumes that `.spacemacs` is empty. You're not the first to make the same mistake, the doc is not clear enough.

**Comment by devinrhode2** [comment]
My file is empty, except for this one line. ?

**Comment by syl20bnr** [comment]
Fixed by https://github.com/syl20bnr/spacemacs/commit/50e32b80811a8aac5c6e1c9b3ec61e418c942a1f
