### ISSUE TITLE
Symbol's definition is void: evil-define-key

### ISSUE THREAD

**Issue by incandescentman** [syl20bnr/spacemacs#6160]
I'm suddenly getting this error on Emacs launch, and I'm not sure where it's coming from. rgrep shows that I have no `evil-define-key` anywhere in my config files or private layer.

Here's my *Messages* buffer:
http://pastebin.com/RqryGp7b

I tried rolling back Spacemacs packages, but I get the same error. I also tried restoring previous working commits of my configuration just to make sure, but again, same error. Any suggestions? How can I track down and fix this error?

**Comment by jtbm37** [comment]
See https://github.com/syl20bnr/spacemacs/issues/6158. You have to rename `spacemacs-helm` to `helm` and make sure you do not have any non existing layers in `dotspacemacs-configuration-layers`

**Comment by incandescentman** [comment]
Thanks, that solved it!
