### ISSUE TITLE
Changing Powerline separators dont work following guide in the docs.

### ISSUE THREAD

**Issue by 4goodapp** [syl20bnr/spacemacs#6161]
In the [docs](http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline72), about the Powerline separators, you didn't mention that one need to recompile the modeline with M-x spaceline-compile to make it works after adding `(setq powerline-default-separator 'arrow)` in `dotspacemacs/user-config ()`

**Comment by TheBB** [comment]
Thanks, but this has been fixed in develop already.

**Comment by 4goodapp** [comment]
Ah okay, cool, So does it means the next version don't need the recompile part?

**Comment by 4goodapp** [comment]
Ohh okay. Thanks.
