### ISSUE TITLE
Spacemacs doesn't see agda executable

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#6165]
During startup I'm getting `(Spacemacs) Warning: Agda not detected, be sure that Agda binaries are available in your PATH or check the installation instructions in the README file.`  while I can execute `:!agda` so it's something with the load timing.  

Latest Spacemacs develop on Emacs 24 and `dotspacemacs-enable-lazy-installation 'unused`

*I don't need agda, just testing `'all` layers option.*

**Comment by syl20bnr** [comment]
Mmmmhh just checked the source code and the layer looks for `agda-mode` executable :-)
Smell the find and replace that went wrong.

**Comment by TheBB** [comment]
Fixed in https://github.com/syl20bnr/spacemacs/commit/2477a3bf89eb2e666d33bce2b36833dce092ddec

**Comment by TheBB** [comment]
I don't think this is right, it's supposed to be `agda-mode`. It's not looking for agda, it's looking for the Emacs files. I just installed agda in Archlinux and it gave me an agda-mode executable.

Reverting for now.

**Comment by JAremko** [comment]
I'll keep it open then.  Don't care about agda much but whatever...

**Comment by JAremko** [comment]
@TheBB   hm. I installed it on Debioan and it doesn't have agda-mode executable only `/usr/share/doc/agda-mode` folder withe a bunch of gz. So it looks like a need to build it. So yeah. Not a bug.

**Comment by JAremko** [comment]
Sorry for the confusion :wink:

**Comment by enolan** [comment]
This is real. Agda ships with the elisp for its mode and the `agda-mode` executable is to tell emacs where the files are. I opened `agda/init-agda` in the debugger and got this line from the backtrace `* locate-file("agda-mode" ("/home/enolan/bin" "/usr/local/sbin" "/usr/local/bin" "/usr/sbin" "/usr/bin" "/sbin" "/bin" "/usr/games" "/usr/local/games" "/usr/lib/emacs/24.5/x86_64-linux-gnu") ("") 1)`. That is not the `$PATH` set in my `.bashrc`. Running `(find-executable "agda-mode")` after initialization returns `"/home/enolan/.local/bin/agda-mode"` which is correct. Maybe the process that gets `$PATH` from `.bashrc` happens after `agda/init-agda` is called?

Debian doesn't have an `agda-mode` executable for some reason (maybe the path is just hardcoded?) but it is part of the [Hackage package](https://hackage.haskell.org/package/Agda).

**Comment by anka-213** [comment]
For me it helped to change the line


    (defvar agda-mode-path use-helper)

to

    (defvar agda-mode-path nil)

in `.emacs.d/layers/+lang/agda/config.el`.
<sub>It  "Indicates the location of the agda-mode package (the file
 `agda2.el') If `nil', it is assumed to be already available by
 Emacs. If `use-helper', the `agda-mode' executable is used to
 find its location."</sub>

---

Perhaps the layer should be trying the builtin (nil) option if the binary can't be found.
