### ISSUE TITLE
Old file is reopened instead of new file on OS X

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#6166]
#### Description

When I open a file in Finder on OS X, Emacs sometimes reopens the previously opened file instead of showing the newly opened one.
#### Reproduction guide

Not quite clear yet. Working on it.

_Observed behaviour:_
Reopens last file.

_Expected behaviour:_
Opens double-clicked file.
#### System Info
- OS: darwin
- Emacs: 25.0.93.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp syntax-checking auto-completion semantic
            (latex :variables latex-enable-auto-fill t)
            org git github version-control extra-langs markdown emacs-lisp haskell html javascript ipython-notebook shell-scripts java
            (haskell :variables haskell-enable-ghc-mod-support nil haskell-enable-ghci-ng-support t haskell-enable-hindent-style "gibiansky" haskell-enable-shm-support nil)
            (c-c   :variables c-c  -enable-clang-support t)
            (python :variables python-test-runner 'pytest)
            (clojure :variables clojure-enable-fancify-symbols t)
            (shell :variables shell-default-height 20 shell-default-position 'bottom shell-enable-smart-eshell t shell-default-shell 'eshell)
            evil-snipe)
```

**Comment by beojan** [comment]
Are you using emacs's daemon mode (i.e. `emacsclient`)

**Comment by 3rd3** [comment]
Yes, I am using `emacsclient`.
