### ISSUE TITLE
how to replace multiple lines with evil?

### ISSUE THREAD

**Issue by wduspa** [syl20bnr/spacemacs#6174]
text like this:
```
aaa
bbb
ccc
```
I typed `/aaa``Ctrl-q``Ctrl-j``bbb``Ctrl-q``Ctrl-j`ccc, it can match these 3 lines,i think evil could match these multiple lines and replace them.

so I use `%s/aaa``Ctrl-q``Ctrl-j``bbb``Ctrl-q``Ctrl-j``ccc` in evil mode,but it doesn't match the 3 lines any more.

but when i try `replace regexp` command, it works.

how to solve it with evil mode?

**Comment by TheBB** [comment]
Looks like `\n` matches newlines in the `:%s` syntax.

**Comment by JAremko** [comment]
Yeah I think it behaves the same way like in Vim http://vim.wikia.com/wiki/Search_across_multiple_lines

**Comment by wduspa** [comment]
thanks a lot,^_^

**Comment by StreakyCobra** [comment]
@wduspa If your question has been answered, you  can close the issue :-)
