### ISSUE TITLE
Display trailing whitespace in red

### ISSUE THREAD

**Issue by yogsototh** [syl20bnr/spacemacs#6179]
Hi! Is there a way to display trailing whitespace in red?

like here:

![red whitespace](http://yannesposito.com/Scratch/img/blog/Vim-as-IDE/trim.gif)

I only found a way to delete them and I can't even see whitespace anymore using the last version apparently.

Thanks!

**Comment by syl20bnr** [comment]
They should be highlighted by default, what is the major mode you are using ?

**Comment by yogsototh** [comment]
You're right, it works perfectly when I edit files with in deft, but they are hidden when I code in clojure.
I believe the major mode might be cider.

**Comment by syl20bnr** [comment]
We only display them in prog modes I believe and chances are cider-mode does not derive from prog-mode.

**Comment by yogsototh** [comment]
I know this is closed but here is something that worked for me. I added this in my `dotspacemacs/user-config`:

~~~elisp
  ;; SHOW TRAILING WHITESPACE
  (require 'whitespace)
  (setq-default whitespace-style '(face trailing))
  (setq-default whitespace-line-column 80)   
  (global-whitespace-mode 1)
~~~
