### ISSUE TITLE
Elixir new checkers for flycheck in develop, need some help

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#6182]
@smeevil @tomekowal

Hey guys,
I added your flycheck checkers in the elixir layer in develop.
credo seems to work fine but mix compile and test result display no information, since mix compile checker is inspired from test result checker and they both rely on a utility script in Elixir I wonder if you could help to debug what's going on.

Commits:

credo: 5b97df8
mix compile: dd572af
test result: 4996f52
Notes:
For mix compile the checker is disabled by default since it is not safe, you have to setup the layer variable =elixir-enable-compilation-checking= to t or use a directory local variable (see README.org).

Thank you !

**Comment by tomekowal** [comment]
Hi, thanks for your interest! In the `mix compile` checker there need to be three things in place for the checker to actually display anything:

* the `mix_compile_helper` needs to be in path. Is there a way to tell emacs that file shipped with package should be visible as an executable for flycheck? This would remove manual step of copying the file to path.
* the project needs to be valid mix project containing `mix.exs` configuration file otherwise it does nothing
* there have to be errors in place

I will try to debug the problem some time next week.

**Comment by syl20bnr** [comment]
I think all these 3 requirements where met when I tested on ecto.
The utility helper is added to exec-path variable and pressing `SPC e v` in an elixir buffer shows that the checker is operational (provided you set the variable `elixir-enable-compilation-checker` to t).

@tomekowal if you refactor your repo to not be like a Spacemacs layer it would be possible to directly point to it in the elixir layer instead of having the files in Spacemacs.

**Comment by aaronjensen** [comment]
fwiw, the test result checker appears to not work at all, i'm not sure if it was ever completed. Even with `mix_test_helper` in the path, it prints no output. If I modify it to print output, it does not work. @smeevil should https://github.com/smeevil/flycheck-elixir-testresult be working?

**Comment by smeevil** [comment]
Hi,

Sorry I tried a few months ago to switch from the intelli-j range of editors to spacemacs. The initial learning cure was quite big, but after a month I got the hang of it and started to appreciate the editor. I tried to get several of the flycheck plugins to work, credo was one of the first things amongst them. I did get it to work eventually on my setup, but a clean install would not work correctly IIRC. In the mean time I switched back to intelli-j again because i missed the deep integration of the code and other utils it offers. I'm afraid i can be of little help here :/

Gerard.

**Comment by aaronjensen** [comment]
@syl20bnr I'd probably recommend removing credo and testresult. It doesn't sound like they're going to be actively maintained, testresult doesn't work at all and credo has issues out of the box (it should have a predicate, but does not)

Ultimately, implementing most elixir flychecks in a good way are blocked until https://github.com/flycheck/flycheck/pull/973 is merged in.

**Comment by smeevil** [comment]
I will remove the repos as well. Wish you all the best :)

**Comment by syl20bnr** [comment]
The credo checker was working for me, actually it was the only one that worked.

What is the preferred linter between dogma and credo ? Do they overlap ?

**Comment by aaronjensen** [comment]
The credo checker works, but requires the archive install which is not normal. I don't believe it will use your custom credo config and it will attempt to run (and fail) if credo is not installed properly (if I remember correctly).

Dogma and credo overlap somewhat, but people do use both. They should both have [predicates](https://github.com/aaronjensen/spacemacs.d/blob/e8c73e31dad4412ddf2313e9d92ce364fcab0f25/lisp/init-elixir.el#L33-L39) that detect whether or not they should be used based on whether or not they are installed in the project (or, in the case of an archive install, detect if it is installed)

**Comment by syl20bnr** [comment]
Ok, I removed test results and credo checkers.

**Comment by tomekowal** [comment]
I came to the conclusion that I don't need external script at all. I did a hack around changing current working directory too https://github.com/tomekowal/elixir-flycheck-mix-compile/blob/master/local/elixir-flycheck-mix-compile/elixir-flycheck-mix-compile.el#L39 Now without the additional script I am going to make my checker into a package. Expect it some time next week.

**Comment by aaronjensen** [comment]
@tomekowal awesome. @syl20bnr I was able to get both dogma and dialyzer flycheckers working well thanks to @tomekowal's suggestion. I've never created a melpa package before, but it'd probably be best if I did that and then we could include those, yeah?

https://github.com/aaronjensen/spacemacs.d/blob/d312ed3815d26716a598aca766ba7b5e0daf3d8d/lisp/init-elixir.el

**Comment by syl20bnr** [comment]
@aaronjensen Great !
You can also submit a PR with a local package (like it is done currently with @tomekowal's checker) if you want, and we can replace it with the MELPA package afterward.

**Comment by tomekowal** [comment]
@syl20bnr Status update: I created a package and made a pull request against melpa. https://github.com/melpa/melpa/pull/3958 I am waiting for some additional feedback :)

**Comment by syl20bnr** [comment]
@tomekowal Great 👍  PR welcome to use it when it lands :-)

**Comment by tomekowal** [comment]
PR created :-) It works locally on my computer, but I am not sure how to test if it works properly everywhere. If you still have problems running it, let me know and we will try to debug the issue.

**Comment by TheBB** [comment]
> I am not sure how to test if it works properly everywhere

When someone figures that out, we'll all be out of jobs!

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
