### ISSUE TITLE
unimpaired mappings not working in all buffers

### ISSUE THREAD

**Issue by DanielFGray** [syl20bnr/spacemacs#6189]
Unimpaired bindsing like `[b` and `]b` don't seem to work in all buffers, for example dired and DocView.

Steps to reproduce:
- open any two files
- switch back and forth with `[b` and `]b`
- use `-` to open dired (vinegar layer mapping)
- cannot use `[b`/`]b` in dired
#### System Info :computer:
- OS: Ubuntu GNU/Linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 8f45a94)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp evil-cleverparens evil-commentary evil-snipe
                 git github javascript haskell html lua markdown org php python react shell
                 spell-checking syntax-checking themes-megapack version-control vinegar)
```

**Comment by duianto** [comment]
`]b` and `[b` now switches to the next/prev buffer from a dired buffer.
It was most likely fixed by this PR:
evil-unimpaired: Switch from normal state to motion state #11787
