### ISSUE TITLE
Python completion not working

### ISSUE THREAD

**Issue by lowerzero** [syl20bnr/spacemacs#6190]
#### Description
Python completion not working

#### Reproduction guide
- Start Emacs
- Open some python file, with for example imported 'os' module
- type os.<tab>

*Observed behaviour:*
Completion needs an interior Python process running

*Expected behaviour:*
Expected completed call

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git python)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment]
> Completion needs an interior Python process running

It sounds like you're trying to invoke the Emacs completion system by hitting TAB. Spacemacs uses company instead. Does it work if you invoke `company-complete` manually? If not can you check the contents of your anaconda mode buffer?

**Comment by lukmy** [comment]
It seems that you need to `M-x run-python` first, which will launch a python REPL.

**Comment by TheBB** [comment]
As I said, TAB invokes a different python completion tool. The company popup should be automatic or you can invoke it manually with `company-complete`.

**Comment by Cadair** [comment]
thanks for the explanation. That leaves me with two things. Firstly, is it possible to rebind the `python-mode` compltetion `TAB` behavior to `company-complete` and secondly it is not automatically displaying for me, how can I debug that?

**Comment by Cadair** [comment]
ok, I answered both these points myself. The automatic company completion seems to be working again, and this: `(global-set-key "\t" 'company-complete-common)` seems to bind the completion to `TAB`.

**Comment by binjo** [comment]
I got the error trace as follows, looks some kind backend error?

Debugger entered--Lisp error: (error "Company: backend company-anaconda async timeout with args (candidates os.)")
  signal(error ("Company: backend company-anaconda async timeout with args (candidates os.)"))
  error("Company: backend %s async timeout with args %s" company-anaconda (candidates "os."))
  company--force-sync(company-call-backend-raw (candidates "os.") company-anaconda)
  company-call-backend(candidates "os.")
  company--fetch-candidates("os.")
  company-calculate-candidates("os.")
  company--begin-new()
  company--perform()
  company-auto-begin()
  company-manual-begin()
  company-complete()
  funcall-interactively(company-complete)
  call-interactively(company-complete record nil)
  command-execute(company-complete record)
  helm-M-x(nil "company-complete")
  funcall-interactively(helm-M-x nil "company-complete")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)

**Comment by binjo** [comment]
so it's a known issue when installing python from brew, the workaround provided in https://github.com/proofit404/anaconda-mode/issues/114 solves the problem.

**Comment by d12frosted** [comment]
Initial question was answered.
