### ISSUE TITLE
Insertion of multiline string as a file-local variable is broken

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#6193]
#### Description
When using <kbd>SPC f v f</kbd> to insert a variable's current value, if it is a multiline string, it is not properly escaped

#### Reproduction guide
- Start Emacs
- <kbd>SPC f v f</kbd> `org-latex-hyperref-template` <kbd>RET RET</kbd>

*Observed behaviour:*

```
# Local Variables:
# org-latex-hyperref-template: "\\hypersetup{
 pdfauthor={%a},
 pdftitle={%t},
 pdfkeywords={%k},
 pdfsubject={%d},
 pdfcreator={%c},
 pdflang={%L}}
"
# End:
```
is inserted

*Expected behaviour:*

```
# Local Variables:
# org-latex-hyperref-template: "\\hypersetup{
#  pdfauthor={%a},
#  pdftitle={%t},
#  pdfkeywords={%k},
#  pdfsubject={%d},
#  pdfcreator={%c},
#  pdflang={%L}}
# "
# End:
```
is inserted.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion deft better-defaults emacs-lisp markdown
                 (org :variables org-enable-github-support t)
                 spell-checking
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 version-control markdown rust emacs-lisp
                 (latex :variables latex-enable-auto-fill nil latex-build-command "Rubber")
                 bibtex
                 (haskell :variables haskell-enable-ghci-ng-support t)
                 (git :variables git-magit-status-fullscreen t git-gutter-use-fringe t)
                 github
                 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
                 ov ocaml hide-region unicode-fonts finance command-log speed-reading liquid-types eyebrowse mu4e)
```

**Comment by rpglover64** [comment]
...And this appears to be an Emacs bug. I'm not sure whether this is something worth working around (e.g. by providing a different function for the keybinding.

**Comment by CestDiego** [comment]
if you can report it to emacs it would be great as well :)

**Comment by TheBB** [comment]
Appears not to have been reported upstream.
