### ISSUE TITLE
Auto-completion breaks the python interpreter

### ISSUE THREAD

**Issue by djeis97** [syl20bnr/spacemacs#6194]
#### Description

 When auto-completion is installed, pressing `TAB` in the inferior python buffer puts two spaces into the `*python*` buffer but actually causes python to do a completion operation (which prints out the contents of the global namespace on the lines above the current one)
#### Reproduction guide
1. Start Emacs
2. Open an inferior python (run-python)
3. Press tab
4. Press enter (to update the buffer, I think)

_Observed behaviour:_ 
Python prints out the contents of the global namespace and never sees the two spaces inserted into the `*Python*` buffer

_Expected behaviour:_
Python waits for another line (as it would if you type two spaces and hit enter)

This causes a more serious issue when entering in blocks of code, where python gets confused by the indentation (since the two spaces in the buffer are never passed to the interpreter itself, I think)
#### System Info

OS: gnu/linux
Emacs: 25.1.50.2
Spacemacs: 0.105.14
Spacemacs branch: nil  rev. 3aff734 
Graphic display: t
Distribution: spacemacs
Editing style: vim
Completion: helm
Layers:    elisp  auto-completion python emacs-lisp

**Comment by djeis97** [comment]
For reference, I have also tried this on a windows 7 machine (which I do not have access to at the moment) and the same issue shows up. Also, AFAIK, python works fine when the auto-completion layer is not installed.

**Comment by cpaulik** [comment]
I can no reproduce this at all using a recent develop version of spacemacs on emacs 24.5.1

**Comment by djeis97** [comment]
While I haven't tried all of these combinations, I've been able to reproduce the behavior on both master and develop, on an almost fresh windows machine from my job and my personal linux machine, with both my personal config and a fresh config with python and auto-completion enabled, and with both the native and fallback autocompletion options for python.

I've been playing with it a bit, and while the tab trick works sometimes, I've found that a more rigorous test is:
```
for i in range(10):
  if i < 5:
    print i
```
(Python breaks and prints an unexpected indent error after the second line)
One thing possibly worth noting is that I'm getting errors with Company:
`Company: backend (company-files company-capf) error "Invalid search bound (wrong side of point)" with args (prefix)`
as I type in the `*Python*` buffer.

**Comment by cpaulik** [comment]
Hmm. I just tried again after `M-x run-python` and I get the following:

```
In [15]: for i in range(19):
   ....: 	if i < 5:
   ....: 		print(i)
   ....: 
0
1
2
3
4

In [19]: 
```

The code is indented with `tab` but this gets lost in the github formatting.

**Comment by djeis97** [comment]
Also, if I disable company-mode inside the inferior-python buffer the code works perfectly (so I may just do that, although auto-completion would be preferable).

**Comment by djeis97** [comment]
I believe you're using ipython, correct? Unfortunately, I don't have access to ipython atm, so I'm just using standard python2.7.

**Comment by djeis97** [comment]
For reference, here's my output
```
Python 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python.el: native completion setup loaded
>>> for i in range(10):
  File "<stdin>", line 1
   for i in range(10):
    ^
IndentationError: unexpected indent
>>> for i in range(10):
...   if i < 5:
  File "<stdin>", line 1
    if i < 5:
    ^
IndentationError: unexpected indent
>>> 
```
This is with the windows 7 machine I mentioned, with a fresh config on the develop branch.
Also, I only just noticed, but it seems like the first line of code I enter always errors with an unexpected indent now.

**Comment by cpaulik** [comment]
I just tried in regular python. I can reproduce the Indentation Error but could find no relationship with tab or company-mode disable or enabled. At the moment it works sometimes and sometimes it does not. I also got the indentation error when using spaces for identation. Then on the next try it worked for unknown reasons.

```
>>> >>> >>> >>> 
>>> for i in range(10):
...     if i < 5:
...         print(i)
  File "<stdin>", line 1
    print(i)
    ^
IndentationError: unexpected indent
>>> 
>>> for i in range(10):
...     if i < 5:
...         print(i)
... 
0
1
2
3
4
>>> for i in range(10):
... 	if i < 5:
... 		print(i)
... 
0
1
2
3
4
>>> for i in range(19):
... 	if i < 5:
  File "<stdin>", line 1
    if i < 5:
    ^
IndentationError: unexpected indent
>>> for i in range(19):
... 	if i < 5:
... 		print(i)
... 
0
1
2
3
4
>>> 
```

**Comment by cpaulik** [comment]
Ok, now I get what you mean. This seems to happen if the autocompletion kicks in when typing an indented line. If I type fast enough that is does not get used everything works as expected. Is that right?

**Comment by djeis97** [comment]
Yes, that's the behavior I've been noticing.

**Comment by cpaulik** [comment]
It seems that this is also happening in vanilla emacs with just company mode loaded. So I don't think that this is spacemacs specific. So you might want to raise this upstream.

**Comment by djeis97** [comment]
Alright, will do.

**Comment by djeis97** [comment]
As it turns out, this is an issue with emacs proper:
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=23678

**Comment by deb0ch** [comment]
Autumnal cleanup: what is the status on this ? Can you still reproduce the behaviour ? (I have tried this
```
1. Start Emacs
2. Open an inferior python (run-python)
3. Enter this code:

for i in range(10):
  if i < 5:
    print i
```
and everything woks fine, using python 2.7.12.

Let us know so we can close this or not.

**Comment by djeis97** [comment]
I cannot test it again right now, but the issue actually has to do with running Python's competition-at-point function on an indented line at the repl. The trick to forcing it, as I mentioned on the upstream bug report, is calling C-M-i on vanilla emacs (complete-at-point, IIRC) between the 5 and : on the second line. So far I have yet to receive any response on the upstream bug report.

**Comment by endc42** [comment]
I can reproduce this issue. I'm using python 3.5.2, the develop branch of Spacemacs (though it also happened on master), and Emacs 25.1.

**Comment by cpaulik** [comment]
Is there a policy regarding upstream Bugs that affect spacemacs Users? I mean should they stay open or be closed? They do have the reported upstream Tag so it might be best to close them on spacemacs side since it would involve quite a lot of effort tracking all the upstream bugreports until we can close an issue.

**Comment by jessepollak** [comment]
I can confirm that this issue still exists as well. Thanks!
