### ISSUE TITLE
Allow setting a list of fonts to try as default

### ISSUE THREAD

**Issue by pfmoore** [syl20bnr/spacemacs#6195]
At the moment, I can set my preferred font in my ```.spacemacs```. But if I want to use the same config on multiple machines, which don't all have quite the same set of fonts installed, I'd like to be able to specify fallbacks.

Could a configuration option be added which is a list of fonts, with the first available font from the list being selected for use? Ideally, ```dotspacemacs-default-font``` could work like that, but it may not be possible to do that in a way that's compatible with current config files.

**Comment by syl20bnr** [comment]
Good idea 👍

**Comment by joehillen** [comment]
This is the workaround I've been using:

```elisp
(defun dotspacemacs/user-init ()
  "Initialization function for user code.
It is called immediately after `dotspacemacs/init'.  You are free to put any
user code."
  ;; make font bigger on laptop
  (when (string= system-name "thinkpad")
    (setq dotspacemacs-default-font
          '("Source Code Pro"
            :size 17
            :weight normal
            :width normal
            :powerline-scale 1.5))))
```

**Comment by TheBB** [comment]
I did this: https://github.com/syl20bnr/spacemacs/pull/6217

**Comment by syl20bnr** [comment]
Should do it thanks to @TheBB :-)

**Comment by pfmoore** [comment]
Nice! Thanks for this :-)

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by namdnguyen** [comment]
I'm still a little confused about how to use this feature. How would we set it in init.el to have a prioritized list of fonts and settings? Is this functionality covered by this commit?

**Comment by joehillen** [comment]
@namdnguyen You set `dotspacemacs-default-font` to a list of plists, like so:

```elisp
dotspacemacs-default-font '(("Not a font!"
                             :size 12
                             :weight normal
                             :width normal
                             :powerline-scale 1.5)
                            ("Ubuntu Mono"
                             :size 12
                             :weight normal
                             :width normal
                             :powerline-scale 1.5)
                            ("Source Code Pro"
                             :size 12
                             :weight normal
                             :width normal
                             :powerline-scale 1.5))
```

or to deduplicate the common bits:

```elisp
dotspacemacs-default-font (let ((fonts '("Not a font!" "Ubuntu Mono" "Source Code Pro")))
                            (mapcar (lambda (font)
                                      `(,font
                                        :size 12
                                        :weight normal
                                        :width normal
                                        :powerline-scale 1.5))
                                    fonts))
```

**Comment by namdnguyen** [comment]
Thank you so much for the examples!
