### ISSUE TITLE
Relative line number breaks theme

### ISSUE THREAD

**Issue by hicksy994** [syl20bnr/spacemacs#6201]
When using the relative line number option, the theme is broken on the current line.

http://imgur.com/wTeY63t

**Comment by TheBB** [comment]
This is the theme. Not much we can do about it. Customize `linum-relative-current-face` if you'd like to change it.

**Comment by hicksy994** [comment]
@TheBB Thanks for your reply. How would I go about doing this? I don't seem to have that command?

**Comment by TheBB** [comment]
It's not a command, but a face, hence the name. :-)

Try using the theming layer to alter the background for example.

```elisp
(theming :variables
         theming-modifications
         '((solarized-dark
            (linum-relative-current-face :background "#000000"))))
```

* [Theming layer doc](http://spacemacs.org/layers/theming/README.html)
* [Face attributes](http://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html)
