### ISSUE TITLE
init/pre-init/post-init stopped being called after update (develop branch)

### ISSUE THREAD

**Issue by aldanor** [syl20bnr/spacemacs#6202]
#### Description

After updating to recent `develop` (02-06-2016), [updating the config file](https://github.com/aldanor/.spacemacs.d/commit/d9cf98696434415359e9fdec257f13ab3c380f4c) to match the most recent template and updating the packages, all of `init-*`, `pre-init`, `post-init-*` functions [defined in packages.el of my local layer](https://github.com/aldanor/.spacemacs.d/blob/master/layers/aldanor/packages.el) stopped being called. 

The `packages.el` itself is executed, I've verified that, but none of the init functions are recognized for some reason. In fact, after update Spacemacs decided to remove one of the packages (`jinja2-mode`) for which I had a matching `init-` function, as unused.

I can't seem to figure what changed in develop branch or the config that could be causing this -- would appreciate any help!

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 9414a8a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 csv deft emacs-lisp
 (git :variables git-magit-status-fullscreen t magit-save-repository-buffers 'dontask magit-revision-show-gravatars nil)
 (github :variables gh-profile-default-profile "aldanor")
 helm html javascript ipython-notebook markdown org
 (python :variables python-fill-column 99 python-test-runner 'pytest)
 rust search-engine
 (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t)
 shell-scripts syntax-checking themes-megapack theming version-control yaml
```

Here's my `.spacemacs.d`: https://github.com/aldanor/.spacemacs.d

**Comment by TheBB** [comment]
Move the `aldanor-packages` list from config.el to packages.el.

**Comment by aldanor** [comment]
@TheBB Thanks! I'm a bit confused, guess I must have misread this commit? https://github.com/syl20bnr/spacemacs/commit/c35e4ee27b437c40ce57c55675eef98d69e4ba73 (_The list of packages of the layer must now be placed in config.el; packages.el only contains pre-init, init and post-init functions_)

I've moved `aldanor-packages` back from `config.el` to `packages.el`, restarted emacs and that didn't seem to do anything. 

However, then also changing `defvar aldanor-packages` to `setq aldanor-packages` seemed to have fixed it; wonder why did it work previously...

**Comment by darkfeline** [comment]
It was changed back to `packages.el` a few commits after that one (somewhat confusingly).  The LAYERS doc is up to date however.  Spacemacs switched to `setq` quite a while ago, to support reloading configuration (because `defvar` only works the first time).

**Comment by TheBB** [comment]
Yep, as @darkfeline says, defvar only sets the value if it doesn't already have a value. As it happens, Spacemacs already runs defvar internally on all package lists (https://github.com/syl20bnr/spacemacs/blob/develop/core/core-configuration-layer.el#L643) so you need to use setq. As it happens it's not a good idea to use defvar in the first place for reasons @darkfeline went into.

**Comment by syl20bnr** [comment]
@aldanor Sorry for the confusion, I moved the package list to config.el but changed my mind quickly (hum ^^) and commits were already pushed upstream so I did not take the risk to force push anything.

**Comment by aldanor** [comment]
Thanks for explaining all, I guess I was unlucky to look at the commit history at a wrong time... :) Re: `defvar` versus `setq`, maybe it would make sense to mention it explicitly in the docs unless it's 100% obvious to everyone? Since there are now many examples of spacemacs configs floating around that have defvars which may make it a bit unclear.

**Comment by chrisbarrett** [comment]
Why is spacemacs using `setq`/`defvar` to define package lists and not `defconst`?

**Comment by TheBB** [comment]
If we have to use `setq` because the package lists can change I don't think `defconst` will help much.

**Comment by syl20bnr** [comment]
The "official" (read in the templates) is `defconst` indeed.

**Comment by syl20bnr** [comment]
Motivation is here: https://github.com/syl20bnr/spacemacs/issues/4488#issuecomment-169900416

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/4488#issuecomment-169919749

Nice, I'm senile now. :-(

**Comment by chrisbarrett** [comment]
@TheBB: the value of a defconst can change each time it's evaluated. Defconst and defvar are basically the opposites of what you expect them to be.

@syl20bnr: Yeah, I think I wrote those templates :p

**Comment by darkfeline** [comment]
To keep things consistent https://github.com/syl20bnr/spacemacs/pull/6208
