### ISSUE TITLE
New undo behaviour

### ISSUE THREAD

**Issue by samdesota** [syl20bnr/spacemacs#6203]
Edit: 
#### Description :octocat:

Is there new undo behavior? If so, how can I change it?
The grouping appears to be messed up.
#### Reproduction guide :beetle:
- Start Emacs
- Insert text on one line
- move to another line
- delete the line
- hit undo 

_Observed behaviour:_ :eyes:
it put's the line back, but then goes back to the line you inserted text on and removes the insert

_Expected behaviour:_ :broken_heart:
It put's the line back
#### System Info :computer:
- OS: darwin
- Emacs: 25.0.94.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 9414a8a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion search-engine fasd emacs-lisp react html git markdown org clojure yaml haskell elm rust
                 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control)
```

**Comment by syl20bnr** [comment]
Interesting, I'll check it out, we did not change anything in this regard.
In the meantime be sure that your packages are up to date.

**Comment by syl20bnr** [comment]
Also use `SPC h I` to submit your issue, this way we can have more info about your system.

**Comment by mrapogee** [comment]
Updated with `SPC h I`

**Comment by mrapogee** [comment]
I'm on the latest develop, also.

**Comment by Stebalien** [comment]
Could you give the reproduction instructions assuming one starts in a scratch buffer and give the exact key sequence? For example, `ia<RET>b<RET>c<ESC>ggaa<ESC>jddu` (which doesn't reproduce the problem for me).

**Comment by mrapogee** [comment]
Your moves worked as expected, this appears not to work though:

ex: `ifoo<RET>bar<ESC>kA test<ESC>jddu`

**Comment by mrapogee** [comment]
Still broken on a fresh .spacemacs

**Comment by mrapogee** [comment]
Cloned master, still broken. Could be a problem with GNU Emacs 25?

**Comment by Stebalien** [comment]
Still can't reproduce but I'm using emacs 24.5. Have you tried setting `evil-want-fine-undo` to `nil`?

**Comment by StreakyCobra** [comment]
You can also try to look for similar problems upstream [here](https://bitbucket.org/lyro/evil/issues?q=undo).

A potentially related one: https://bitbucket.org/lyro/evil/issues/594/undo-doesnt-behave-like-vim

**Comment by mrapogee** [comment]
Looks like it's an issue with Emacs 25. Setting `evil-in-single-undo` to `t` fixed it though.

Thanks!

**Comment by syl20bnr** [comment]
So we can consider to add that setting in Spacemacs.
