### ISSUE TITLE
Incorrect indentation in haskell-mode

### ISSUE THREAD

**Issue by codygman** [syl20bnr/spacemacs#621]
![test](https://cloud.githubusercontent.com/assets/225847/6241152/d6f95af6-b718-11e4-9354-5288ff1582d9.gif)

I'm not sure if this is an error with hi2, if you need to modify behavior of evil-open-below in Haskell mode, or both. This is a vanilla Haskell mode install on nixos but I've also reproduced on a vanilla Ubuntu install.

**Comment by ocharles** [comment]
I think this is a bug/something to be reported for `hi2`. I tend to agree, I find this behavior quite annoying, though I can see the sense in it...

**Comment by syl20bnr** [comment]
What's the status of this bug ?

**Comment by ocharles** [comment]
I don't think it's a `spacemacs` bug - if anything it should be reported at https://github.com/haskell/haskell-mode

**Comment by ajnsit** [comment]
Is there a way to be certain if it's haskell-mode or spacemacs which has the bug? I see the same issue on a vanilla install of spacemacs on ubuntu. In fact the symptoms are much worse because a lot of times, the current line will also get automatically indented on pressing enter. But I don't see the same issue on vanilla emacs with haskell mode.

**Comment by codygman** [comment]
Have you tried building from master? I think this fixed it:
https://github.com/syl20bnr/spacemacs/commit/2af7ea89dff44eead028003510e6fbd5b3671794

**Comment by PierreR** [comment]
:+1: 
I have found the behavior of `evil-open-below` quite counter-intuitive/annoying in general.
Is there an easy way to have the normal 'vim' behavior' (i + RET) back ?

**Comment by x-ji** [comment]
Umm... `eval-open-below` is still exhibiting the same behavior if I do not enable `structured-haskell-mode`. However `structured-haskell-mode` seems to have issues with inserting brackets in `INSERT` state. It's quite annoying.

**Comment by TheBB** [comment]
@d12frosted And this...

**Comment by d12frosted** [comment]
Well, in `haskell-indentation-mode` (which is used in Spacemacs) behaviour is the same. The idea of using `tab` on region with this indentation mode enabled is that it allows you to move region left or right by pressing `tab` or `S-tab` repeatable without marking region again. Notice, what is written in echo area when you press `=` with active region. And looks like, we should mimic this behaviour somehow. When I try pressing `=` in normal state and then `tab` - nothing happens. When I press `=` again - region is not indented further. I am not sure how to mimic this thing, cause I don't use vim editing style. 

> But I don't see the same issue on vanilla emacs with haskell mode.

@ajnsit Have you enabled `haskell-indentation-mode` or `turn-on-haskell-indentation` before testing it?

**Comment by d12frosted** [comment]
@TheBB And here :smile:

**Comment by d12frosted** [comment]
Oh, forgot to share [this](link). :smile:

**Comment by StreakyCobra** [comment]
Any update on this issue?

**Comment by d12frosted** [comment]
@StreakyCobra see related PR (#3586). 

But I believe that it's 'wontfix'.

**Comment by StreakyCobra** [comment]
Oh, I didn't saw it, thx.

**Comment by StreakyCobra** [comment]
Probably the same problem as in #5010. Problem with indentation has been reported upstream.

**Comment by d12frosted** [comment]
Upstream issue is not fixed yet. 

Reference: https://github.com/haskell/haskell-mode/issues/1265 (original report https://github.com/haskell/haskell-mode/issues/896 was closed in favour of https://github.com/haskell/haskell-mode/issues/1265).

**Comment by fiveNinePlusR** [comment]
seems like this should be closed as it's an upstream issue.
