### ISSUE TITLE
Feature request: terminal for project

### ISSUE THREAD

**Issue by simplyianm** [syl20bnr/spacemacs#6210]
It would be nice if there were a hotkey to open a terminal specific for a project.

**Comment by NJBS** [comment]
It already exists on `develop` :smile: 

`SPC p '`

[Here's](https://github.com/syl20bnr/spacemacs/commit/010444c) the commit if you'd like to define it yourself.

**Comment by CestDiego** [comment]
Has anyone looked at this? https://github.com/IvanMalison/term-manager

**Comment by robbyoconnor** [comment]
> Has anyone looked at this? https://github.com/IvanMalison/term-manager

<3 <3 <3 <3

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
