### ISSUE TITLE
`C-g` doesn't cancel 

### ISSUE THREAD

**Issue by embg** [syl20bnr/spacemacs#6219]
#### Description

Often I need to cancel a command mid-way with `C-g`. However, instead of closing the completion window, it just corrupts the helm completion window and makes it impossible to run further commands. This problem affects all commands that require input, not just `C-x C-f`.
#### Reproduction guide
- Start Emacs
- Run any command that requires input, like `C-x C-f`
- Press `C-g`

_Observed behaviour:_
Screenshots from running reproduction steps:

Run `C-x C-f`:
![screenshot from 2016-05-28 14-36-35](https://cloud.githubusercontent.com/assets/12179121/15637675/efd723f0-25d5-11e6-9822-45eaa67325ef.png)

Cancel with `C-g`:
![screenshot from 2016-05-28 14-36-44](https://cloud.githubusercontent.com/assets/12179121/15637679/ff5aed02-25d5-11e6-8427-7bc9b1523288.png)

_Expected behaviour:_
The helm completion window should close and the modeline should read `Quit`.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp git markdown spell-checking syntax-checking)
```

**Comment by syl20bnr** [comment]
Thank you for the report, I cannot reproduce it, `C-g` correctly closes the completion.

**Comment by embg** [comment]
Hm, any idea what might be going on? It gives me `[No match]` at the bottom, and if I press `C-g` n times it gives me `"[No match]" * n` at the bottom. Is something intercepting the `C-g` and triggering pattern matching?

**Comment by bmag** [comment]
> the helm completion window

Minor detail: The window in the screenshot is not Helm, it looks like Ido (`ido-find-file`). I can't reproduce the bug either (using latest develop branch and Ivy).

**Comment by syl20bnr** [comment]
Do you have some custom config in your dotfile or in custom layers ?

**Comment by embg** [comment]
Nope

**Comment by syl20bnr** [comment]
This is strange, as @bmag mentioned, on your screenshots this is not helm, this is ido.

**Comment by embg** [comment]
How do I reset spacemacs to the default config to verify that this is not a result of my accidentally misconfiguring something? I tried commenting all the code in my `user-config`, it didn't help.

**Comment by bmag** [comment]
> How do I reset spacemacs to the default config

copy `core/templates/.spacemacs.template` to `~/.spacemacs`

**Comment by embg** [comment]
I reset to `core/...` and restarted spacemacs, it didn't help.

**Comment by syl20bnr** [comment]
The first question to answer is why you get ido instead of helm when pressing `C-x C-f`. If you tried with a fresh install and it does not fix the issue then it looks like an UBO for me (Unidentified Bug Object).
