### ISSUE TITLE
few pixel wide line below the modeline, seperators look weird.

### ISSUE THREAD

**Issue by bibek22** [syl20bnr/spacemacs#6221]
So, this is what it looks like normally. 
![screenshot-30](https://cloud.githubusercontent.com/assets/12458377/15797229/9994440a-2a30-11e6-81c2-eefeed0d4899.png)

And when i'm idle for a minute or so or i switch to a different workspace and switch back to emacs. It looks normal like so:
![screenshot-31](https://cloud.githubusercontent.com/assets/12458377/15797237/baf87c1a-2a30-11e6-93b9-5fc724b0caad.png)

But soon as I press some key, the line below comes back.

unsurprisingly, If i set the separator to `nil`, it looks as expected. 

What could be the issue? I'm on Arch with dwm.

EDIT: 
another observation:  When i launch another instance of emacs, and let each one use half of screen real-estate, left and right. Both instances show separators fine. but, when one is increased beyond the half of portion, it looks weird again. Here's what i mean:  

![screenshot-32](https://cloud.githubusercontent.com/assets/12458377/15797311/f8c4d9b0-2a32-11e6-9ce3-f64d92989588.png)  

![screenshot-35](https://cloud.githubusercontent.com/assets/12458377/15797317/234a8a5e-2a33-11e6-897b-2cd6e45b9a01.png)

EDIT2: okay, this is weird.  ^^^ this behaviour also seems to be buffer dependent.  It needs to have sufficiently small width for it to look normal, which seemingly varies according to buffer.

**Comment by syl20bnr** [comment]
To fix this ugly mode-line you can adjust the keyword :powerline-scale in your dotfile where you setup the font.

**Comment by bibek22** [comment]
so, I changed the scale to make it minimal. hope this doesn't come back again, somehow. 
Thanks @syl20bnr . Closing.
