### ISSUE TITLE
smartparens is slow with Emacs 25

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#6222]
Issue to track upstream: https://github.com/Fuco1/smartparens/issues/595

**Comment by aaronjensen** [comment]
@syl20bnr this ended up not being an emacs 25 issue. A patch was just merged in that should make it faster in the case where you have many buffers open, which seems to have been the main problem. 

https://github.com/Fuco1/smartparens/pull/628

If someone else wants to give this a test and confirm this can probably be closed

**Comment by d12frosted** [comment]
@aaronjensen thanks for the heads up!

**Comment by istinspring** [comment]
everything is slower in emacs 25, i had performance issues. So i decided to stay on 24
