### ISSUE TITLE
5a444184f109ac3c1487cbcd0440867f4b05c635 5a44418 is broken on ubuntu 16.04

### ISSUE THREAD

**Issue by liugang** [syl20bnr/spacemacs#6226]
I'm using GNU Emacs 25.0.94.1

this commit 5a444184f109ac3c1487cbcd0440867f4b05c635 5a44418 is works on ubuntu 14.04, but it was broken on ubuntu 16.04

Switch to 5a44418 is broken

git co -b branch-5a444184f109ac3c1487cbcd0440867f4b05c635 5a44418

Switch to previous commit 98e6d46 is works.

git co -b branch-98e6d46ab99fd83eb553d126196123afa6696269 98e6d46

    Warning (initialization): An error occurred while loading ‘/home/galen_liu/.emacs.d/init.el’:

    Wrong type argument: listp, Source Code Pro

    To ensure normal operation, you should investigate and remove the
    cause of the error in your initialization file. Start Emacs with
    the ‘--debug-init’ option to view a complete error backtrace.

emacs --debug-init

    Debugger entered--Lisp error: (wrong-type-argument listp "Source Code Pro")
    car("Source Code Pro")
    mapconcat(car ("Source Code Pro" :size 13 :weight normal :width normal :powerline-scale 1.1) ", ")
    (spacemacs-buffer/warning "Cannot find any of the specified fonts (%s)! Font settings may not be correct." (mapconcat (quote car) dotspacemacs-default-font ", "))
    (if (spacemacs/set-default-font dotspacemacs-default-font) nil (spacemacs-buffer/warning "Cannot find any of the specified fonts (%s)! Font settings may not be correct." (mapconcat (quote car) dotspacemacs-default-font ", ")))
    (progn (message "Setting the font...") (if (spacemacs/set-default-font dotspacemacs-default-font) nil (spacemacs-buffer/warning "Cannot find any of the specified fonts (%s)! Font settings may not be correct." (mapconcat (quote car) dotspacemacs-default-font ", "))))
    (if (symbol-value init) (progn (message "Setting the font...") (if (spacemacs/set-default-font dotspacemacs-default-font) nil (spacemacs-buffer/warning "Cannot find any of the specified fonts (%s)! Font settings may not be correct." (mapconcat (quote car) dotspacemacs-default-font ", ")))) (setq spacemacs--after-display-system-init-list (cons (function (lambda nil (message "Setting the font...") (if (spacemacs/set-default-font dotspacemacs-default-font) nil (spacemacs-buffer/warning "Cannot find any of the specified fonts (%s)! Font settings may not be correct." (mapconcat ... dotspacemacs-default-font ", "))))) spacemacs--after-display-system-init-list)))
    (let ((init (cond ((boundp (quote ns-initialized)) (quote ns-initialized)) ((boundp (quote w32-initialized)) (quote w32-initialized)) ((boundp (quote x-initialized)) (quote x-initialized)) (t (quote t))))) (if (symbol-value init) (progn (message "Setting the font...") (if (spacemacs/set-default-font dotspacemacs-default-font) nil (spacemacs-buffer/warning "Cannot find any of the specified fonts (%s)! Font settings may not be correct." (mapconcat (quote car) dotspacemacs-default-font ", ")))) (setq spacemacs--after-display-system-init-list (cons (function (lambda nil (message "Setting the font...") (if (spacemacs/set-default-font dotspacemacs-default-font) nil (spacemacs-buffer/warning "Cannot find any of the specified fonts (%s)! Font settings may not be correct." ...)))) spacemacs--after-display-system-init-list))))
    spacemacs/init()
    (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat user-emacs-directory "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs-buffer/display-info-box) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
    eval-buffer(# nil "/home/galen_liu/.emacs.d/init.el" nil t) ; Reading at buffer position 1157
    load-with-code-conversion("/home/galen_liu/.emacs.d/init.el" "/home/galen_liu/.emacs.d/init.el" t t)
    load("/home/galen_liu/.emacs.d/init" t t)
    #[0 "�\205\266

**Comment by bmag** [comment]
Looks like [this line](https://github.com/syl20bnr/spacemacs/commit/5a444184f109ac3c1487cbcd0440867f4b05c635#diff-6104ae45148ccdd2fc150ad8aa59ab80R109) doesn't handle the case where `dotspacemacs-default-font` is a list of plists.

As a temporary workaround, you can either install the font "Source Code Pro" or change `dotspacemacs-default-font` to use a font that is installed on your computer.

cc @TheBB

**Comment by liugang** [comment]
OK, install "Source Code Pro" manually, can workaround this issue.
https://github.com/adobe-fonts/source-code-pro/issues/17#issuecomment-167650167

> git clone --depth 1 --branch release https://github.com/adobe-fonts/source-code-pro.git ~/.fonts/adobe-fonts/source-code-pro
> fc-cache -f -v ~/.fonts/adobe-fonts/source-code-pro

**Comment by deb0ch** [comment]
You can also just download the [release binaries](https://github.com/adobe-fonts/source-code-pro/archive/2.010R-ro/1.030R-it.tar.gz) instead of cloning the entire repo.

**Comment by TheBB** [comment]
I fixed this.

Note that if this bug affected you, your font config is incorrect.
