### ISSUE TITLE
Option enabling restricted actions is written to init.el

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#6228]
#### Description :octocat:

IMO current behavior is ugly even for vanilla Emacs and even more so for more compartmentalized Spacemacs
#### Reproduction guide :beetle:
- Start Emacs
- Try narrowing to a page with `SPC n p`
- See the message about restricted stuff
- Answer `y y` (I think) - to enable permanently this action
- Open your init.el (`SPC f e i`) and see the last line

_Observed behaviour:_ :eyes:
Notice that `(put 'narrow-to-page 'disabled nil)` got appending to init.el

_Expected behaviour:_ :broken_heart:
Unsure. But some more compatibility between what is done on enabling some restricted functions like that.
I really doubt it belongs there, given how little code of such small scale is there in Spacemacs.

Maybe even just disable those restricted functions.
Or write them to `customize` area instead?
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.50.2
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 3130cc6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(eyebrowse org elfeed ranger version-control git github markdown themes-megapack theming colors emoji erc deft emacs-lisp common-lisp vimscript javascript python ipython-notebook clojure haskell spacemacs-helm auto-completion spell-checking syntax-checking
           (shell :variables shell-default-height 30 shell-default-position 'bottom)
           dash)
```

**Comment by bmag** [comment]
Of relevance: the variable `disabled-command-function` and the functions `disabled-command-function`, `enable-command`, `disable-command`, `en/disable-command` in `novice.el`.

Looking at the source code (for Emacs 24.5.1), it seems that  `user-init-file` is hard-coded as the output file. We can:
- 1. advice `en/disable-command` to wrap in a let-binding that temporarily changes the value of `user-init-file`
- 2. write our own function and set `disabled-command-function` to our function. This won't help if the user calls `enable-command` or `disable-command` manually (a possible but unlikely scenario)

> Maybe even just disable those restricted functions.

According to `disabled-command-function` variable's docstring, we can enable all the disabled function without asking confirmation or writing to file:
> If nil, the feature is disabled, i.e., all commands work normally.

**Comment by syl20bnr** [comment]
Disabled functions are pretty rare, I'm for removing `SPC n p`, we should not have it by default if it has been disabled. It does not fix this issue though :-)

**Comment by kini** [comment]
Maybe this should be reported upstream? Seems strange that this function doesn't just use the customize framework, and directly writes to your `~/.emacs` (or in this case `~/.emacs.d/init.el`).

**Comment by bmag** [comment]
@kini that's an interesting idea, that `novice.el` should write to `custom-file` (when it is non-nil) instead of `user-init-file`. You are welcome to submit this idea as a feature request with `M-x report-emacs-bug`, although the response might be along the lines of "patch welcome", as I'd estimate it's a low-priority issue. Also note that customize (AFAIK) sets values for variables and faces, while `novice.el` adds properties to functions, so fully utilizing customize interface might not be so simple.
