### ISSUE TITLE
Can't open spacemacs with sudo in Manjaro/Arch

### ISSUE THREAD

**Issue by vanloc0301** [syl20bnr/spacemacs#6229]
I using Manjaro, I was install Spacemacs. But when I tried call with `sudo emacs -nw` it will open emacs.
If using command `emacs -nw` it will open spacemacs. 

How to fix this. I want open spacemacs in sudo to create and edit file when folder need permission.
Thanks.

**Comment by TheBB** [comment]
When you run a program as sudo, you run it as the root user, whose home directory is `/root`. Therefore emacs looks for config in `/root/.emacs.d`, not your own home directory (where you have put Spacemacs). There's nothing we can do about this, and all other programs that you might want to run under sudo with user-specific configs will behave the same way.

Possible solutions:

* Install spacemacs as root.
* Use `sudo -E` to preserve the environment variables (specifically, `$HOME`).

**Comment by NJBS** [comment]
You should be able to use `SPC f E` to create/edit files as a super user.

**Comment by vanloc0301** [comment]
@NJBS if using `SPC f E` it will create file as sudo.

So, in next time when you open file to edit and save again. It will need chmod.

`Doing chmod. operation is not permitted`.

In this case I must chmod one by one folder I was created? This have many time.

**Comment by TheBB** [comment]
If you need to chmod a lot of files you can do it recursively.

`chmod ... -R <path>`

I'm not sure I see the problem here though, looks like the permission system working as it should.

**Comment by vanloc0301** [comment]
When using `SPC f E` seems to occur many steps to create new file or folder. So, I decided using `sudo -E` but it a better solution to resolve my problem? Thanks.

**Comment by syl20bnr** [comment]
`sudo -E` looks like the standard way to do it.

**Comment by chenyangguang** [comment]
https://www.emacswiki.org/emacs/SudoSave
