### ISSUE TITLE
Prevent rcirc log files from getting included in the repository

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#623]
Two options: Include `rcirc-log/` in `.gitignore`, or set the `rcirc-log-directory` to be inside `private/`. Which one of these is preferred?

**Comment by syl20bnr** [comment]
I would put them in `.cache/rcrc-logs` by default and carrefully setup the variable to be still able to modify it in `dotspacemacs/config` (i.e. the variable should set in a `:init` block)

PR welcome ! :-)

**Comment by CestDiego** [comment]
Hello, I uploaded a PR to address this #815 with a whole new layer offc

**Comment by syl20bnr** [comment]
Oh forgot to close this.
It should be OK now that logs are in `.cache` directory.
