### ISSUE TITLE
spacemacs freezes for 1:20 immediately after startup

### ISSUE THREAD

**Issue by ShaneKilkelly** [syl20bnr/spacemacs#6230]
#### Description

spacemacs freezes for 1:20 immediately after startup.
Immediately after emacs starts, it will become unresponsive for approximately 1 minute and 20 seconds, ignoring all input. Once this time period has passed, emacs/spacemacs behaves as normal.

#### Reproduction guide
- Start Emacs
- try to interact with emacs

*Observed behaviour:*
Emacs freezes and is unresponsive for 1 minute and 20 seconds

*Expected behaviour:*
not freeze

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

#### Things I've tried so far, with no luck
- completely re-install spacemacs
- rebuild emacs itself (using both the `emacs-mac` and `emacs-plus` homebrew packages, same behaviour in both)
- checked contents of the Messages buffer, no indication of a problem
- remove existing .spacemacs file, allow spacemacs to generate a new one
- disable automatic updates
- tried both GUI and command-line emacs programs
- remove everything from `.bashrc`

#### Things I've tried so far, which did help

- start emacs with `-Q` flag, emacs is immediatly responsive and remains so

#### *Messages* buffer

```
Loading /Users/shanek/.emacs.d/core/core-load-paths.el (source)...done
Loading /Users/shanek/.spacemacs...done
Loading /Users/shanek/.emacs.d/.cache/spacemacs-buffer.el (source)...done
Open the quickhelp.
Loading /Users/shanek/.emacs.d/layers/+distribution/spacemacs-base/funcs.el (source)...done
Loading /Users/shanek/.emacs.d/layers/+distribution/spacemacs-base/config.el (source)...done
Loading /Users/shanek/.emacs.d/layers/+distribution/spacemacs-base/keybindings.el (source)...done
Loading /Users/shanek/.emacs.d/layers/+lang/emacs-lisp/config.el (source)...done
Loading /Users/shanek/.emacs.d/layers/+distribution/spacemacs-base/packages.el (source)...done
Loading /Users/shanek/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done
Spacemacs is ready.
Skipping check for new version (reason: dotfile)
Loading /Users/shanek/.emacs.d/.cache/recentf...done
Open the quickhelp.
byte-code: End of buffer [2 times]
helm-resume: helm-resume: No helm buffers found to resume
```

**Comment by NJBS** [comment]
Have you taken a look at this FAQ entry?

http://spacemacs.org/doc/FAQ.html#orgheadline14

**Comment by ShaneKilkelly** [comment]
@NJBS Thanks, that appears to have solved the problem

Now that I look more closely, the spacemacs welcome page had been saying `[321 packages loaded in 80s]`, which was suspect. 

I wonder if we could detect when package init takes much longer than it should, and perhaps show the user a link to either the page linked above, or a general "Why is spacemacs slow?" page. 

Anyway, will close this issue, thanks!
