### ISSUE TITLE
Haskell repl: 'c-p' prints prompt

### ISSUE THREAD

**Issue by reckbo** [syl20bnr/spacemacs#6234]
Using `c-p` to get previous command reprints the prompt characters, e.g:

    λ> main
    repl test
    λ> mainλ>

**Comment by d12frosted** [comment]
`c-p`? `M-p` and `M-n` is for getting previous / next commands.

**Comment by reckbo** [comment]
Ah ok, so command key is meta, whoops.

Thanks.
