### ISSUE TITLE
terminal abnormal display

### ISSUE THREAD

**Issue by chenyangguang** [syl20bnr/spacemacs#6235]
After installed spacemacs. Alt+x shell to enter the shell mode. But it display in an odd way : -> ~ ^[[?2004h , (messy code), any idea of this maybe great help for me. The '-> ~' means i use oh-my-zsh, and the dir is my own user dirpath.

**Comment by TheBB** [comment]
Don't use `shell`, it's a dumb terminal. Use `term`, `ansi-term` or `multi-term`. See also the shell layer.

**Comment by chenyangguang** [comment]
Does it means there is a compatibility bug in shell-mode ?

**Comment by shahinism** [comment]
#3035 has addressed this problem.

**Comment by TheBB** [comment]
Nice find. :+1:

**Comment by chenyangguang** [comment]
But it is ok on ubuntu14.04, then this phenomenon occurred on ubuntu16.04.

**Comment by shahinism** [comment]
Trusty provides you with version 5.0.2 of zsh. Xenial (16.04) on the other hand has the version 5.1.1 which as described in #3035 causes the problem. Anyway, I'm using zsh `5.2` here, and the problem you described doesn't exist anymore.

**Comment by chenyangguang** [comment]
➜  ~ [?2004hzsh --version
zsh --version[?2004l
zsh 5.2 (x86_64-unknown-linux-gnu)
➜  ~ [?2004h
