### ISSUE TITLE
Ability to display current time in the modeline

### ISSUE THREAD

**Issue by ocharles** [syl20bnr/spacemacs#624]
I used to have `display-time-mode` enabled before moving to Spacemacs, and do miss that feature. Just enabling it manually doesn't seem to do anything, so perhaps this is a powerline interaction issue. If I'm reporting this to the wrong project, please let me know.

**Comment by syl20bnr** [comment]
nope this is a spacemacs issue. There is a ticket opened to improve the powerline extensibility in spacemacs, for now it is the most awful part of spacemacs.
I'll add this to the mode-line.

**Comment by TheBB** [comment]
This seems to work fine after the modeline refactoring.

**Comment by ocharles** [comment]
Do I just need to enable `display-time-mode`?

**Comment by TheBB** [comment]
Yes. On the develop branch, mind.
