### ISSUE TITLE
No eldoc information when editing Clojure files

### ISSUE THREAD

**Issue by jgertm** [syl20bnr/spacemacs#6242]
#### Description :octocat:
No eldoc information when editing Clojure files

#### Reproduction guide :beetle:
- Start Emacs
- Open Clojure file in Leiningen project
- jack in (```, s i```)
- load ns (```, s n```)
- move cursor over function
- observe empty bottom bar where short function doc should display

*Observed behaviour:* :eyes:
No symbol information is displayed

*Expected behaviour:* :broken_heart:
Symbol signature/docstring should display in eldoc area

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. a4b8039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(;; abbreviated
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 (clojure :variables
              clojure-enable-fancify-symbols t
              cider-font-lock-dynamically '(macro core deprecated function)
              cljr-suppress-middleware-warnings t)
 emacs-lisp evil-commentary evil-cleverparens
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 extra-langs spell-checking syntax-checking themes-megapack version-control)
```

**Comment by kdelwat** [comment]
I can't reproduce this, using the same clojure layer configuration as you. Can you confirm that it's still a problem with 0.200?

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
 (clojure :variables clojure-enable-fancify-symbols t cider-font-lock-dynamically
          '(macro core deprecated function)
          cljr-suppress-middleware-warnings t)
```

**Comment by jgertm** [comment]
It's not an issue anymore. I determined the cause to be a mismatch in cider versions.
Note that updating spacemacs had no effect on this thought, tweaking of ```profiles.clj``` was neccessary.

This issue can be closed.
