### ISSUE TITLE
Missing org-export to reveal.js

### ISSUE THREAD

**Issue by Allaman** [syl20bnr/spacemacs#6244]
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-C C-C` TO SUBMIT>>
#### Description :octocat:
ox-reveal is not working since it was included to the org layer although
org-enable-reveal-js-support is set to true.

#### Reproduction guide :beetle:
- Start Emacs
- Open an org file to be exported to reveal.js
- Hit ~C-c C-e~ for export Buffer
- There is no option for reveal.js export available

*Observed behaviour:* :eyes:
- I can't export an org file to reveal.js

*Expected behaviour:* :broken_heart:
- An option like org-export-as-revealjs

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. a4b8039)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults c-c++ clojure deft emacs-lisp erc extra-langs evil-snipe finance git gtags jabber javascript gnus latex markdown org
				 (org :variables org-enable-reveal-js-support t org-reveal-js "file:///home/michael/org/reveal")
				 php python ipython-notebook syntax-checking spell-checking version-control html ruby ruby-on-rails shell sql search-engine themes-megapack
				 (auto-completion :variables auto-completion-enable-help-tooltip t)
				 (shell :variables shell-protect-eshell-prompt t shell-default-shell 'ansi-term shell-pop-autocd-to-working-dir nil)
				 (ranger :variables ranger-show-preview t ranger-cleanup-on-disable t ranger-show-dotfiles t ranger-ignored-extensions
						 '("mkv" "iso" "mp4")
						 ranger-max-preview-size 10))
```

#### Backtrace :paw_prints:
```
https://github.com/syl20bnr/spacemacs/pull/2958
```

**Comment by TheBB** [comment]
I can't reproduce this.

In an org file, can you check that `(featurep 'ox-reveal)` is truthy?

**Comment by Allaman** [comment]
Steps:
- open a org file
- eval-expression (M-:)
- (featurep 'ox-reveal) RETURN
- Minibuffer returns nil

**Comment by TheBB** [comment]
Can I see `use-package--org-post-config-hook`?

**Comment by Allaman** [comment]
value of `use-package--org-post--config-hook` is 
```
Back to top level.
((lambda nil (if (member (quote (python . t)) org-babel-load-languages) org-babel-load-languages (setq org-babel-load-languages (cons (quote (python . t)) org-babel-load-languages)))) (lambda nil (if (member (quote (shell . t)) org-babel-load-languages) org-babel-load-languages (setq org-babel-load-languages (cons (quote (shell . t)) org-babel-load-languages)))))
```

**Comment by Allaman** [comment]
Problem solved. In my layer list I had multiple org entries and the variable for revealjs were not set:
```
org
 (org :variables
         org-enable-reveal-js-support t
         org-reveal-js "file:///home/michael/org/reveal")
```
Removing the first org solves my problem
Many thanks @TheBB
