### ISSUE TITLE
org: cannot export to markdown (ox-gfm)

### ISSUE THREAD

**Issue by reckbo** [syl20bnr/spacemacs#6248]
I expect that when I add the configs for `ox-gfm` that I'd be able to see a markdown option
after `SPC m e` in an org document.  

### Description

1. Added config variables as described by spacemacs org README:

    (setq-default dotspacemacs-configuration-layers '(
                                                    (org :variables org-enable-github-support t)))
    (setq-default dotspacemacs-configuration-layers '(
                                                    (org :variables org-enable-reveal-js-support t)))

2. Made `test.org`, then hit `SPC m e`.  No option to export to markdown is shown.

3. Wrapped configs in 

    (with-eval-after-load 'org
      ;; here goes your Org config :)
      ;; ....
      )

Still no export option for markdown.  Put configs in every init function in .spacemacs, still nothing.

### System info

* OS: OS x 10.9.5
* Emacs: 24.5.1
* Spacemacs: 0.105.20 (develop)

**Comment by syl20bnr** [comment]
The documentation examples modify the same variable, you have to set the layer variable in the same and **unique** `setq dotspacemacs-configuration-layers`.

```elisp
(setq-default dotspacemacs-configuration-layers
  '(
    (org :variables org-enable-github-support t
                    org-enable-reveal-js-support t)
  ))
```

**Comment by syl20bnr** [comment]
PS: you don't have to add the variable `dotspacemacs-configuration-layers` to the dotfile, it is already present in it, you just have to modify it.

**Comment by reckbo** [comment]
Ah that was the issue - I added the configs to everywhere but the right place.
Thanks.

**Comment by neo-anderson** [comment]
Does this not work anymore? I added `(org :variables org-enable-github-support t)` to `dotspacemacs-configuration-layers` but I don't see GFM option in the export menu. When I select Markdown option, the output is not GFM.
