### ISSUE TITLE
Mouse click in results in search highlighting when running Spacemacs via SSH

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#6250]
#### Description

Spacemacs highlights the characters at the mouse when clicking on text in an SSH session e.g. in C++ mode.

#### Reproduction guide
- Start SSH session, e.g. `ssh localhost`.
- Start Emacs in terminal, e.g. `emacs -nw`.
- Open a C++ source file.
- Click on any text position in the buffer.

*Observed behaviour:*
Characters at mouse are highlighted throughout buffer.

*Expected behaviour:*
Highlighting shall not occur.

#### System Info
- OS remote machine: linux
- OS local machine: OS X, iTerm2
- Emacs: 25.0.93.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp syntax-checking auto-completion semantic
            (latex :variables latex-enable-auto-fill t)
            org git github version-control extra-langs markdown emacs-lisp haskell html javascript ipython-notebook shell-scripts java
            (haskell :variables haskell-enable-ghc-mod-support nil haskell-enable-ghci-ng-support t haskell-enable-hindent-style "gibiansky" haskell-enable-shm-support nil)
            (c-c   :variables c-c  -enable-clang-support t)
            (python :variables python-test-runner 'pytest)
            (clojure :variables clojure-enable-fancify-symbols t)
            (shell :variables shell-default-height 20 shell-default-position 'bottom shell-enable-smart-eshell t shell-default-shell 'eshell)
            evil-snipe)
```

**Comment by 3rd3** [comment]
@StreakyCobra What would be the best way to deactivate this kind of highlighting altogether? I couldn't find any binding via `SPC h d k <mouse-1>`.

**Comment by StreakyCobra** [comment]
I never encountered this, so I don't really know :-/

**Comment by 3rd3** [comment]
Were are these things bound in spacemacs? If I click and drag it goes completely wild, it even deletes selections and calls `spacemacs/evil-numbers-transient-state/evil-numbers/inc-at-pt`. Occasionally it enters the `symbol-highlight` microstate, sends keys like `C-u 1 -.`, `C-u 5 -.`, `, <mouse-1>`, `C-u 21`, `,-` and `[-`.

I now suspect the problem is rather somewhere in the chain iTerm2 → ssh → screen → Emacs, rather in Spacemacs. It also seems different mouse coordinates result in different keys, but single clicks definitely always result in highlights. Interesting.

**Comment by 3rd3** [comment]
`tmux` makes it work a bit better. This is not relevant to Spacemacs.

**Comment by ryukinix** [comment]
I have the same problem using `emacs -nw` on `xfce4-terminal`. Really this is not relevant to Spacemacs? BTW, how I can disable this or just exit from hightlight? I check all the guides about quit of mark mode, but nothing of that makes any sense.

Any thought about disable highlight ou just quitting that creep behavior for mouse-click?

**Comment by ryukinix** [comment]
THIS IS REALLY ANNOYING!

**Comment by 3rd3** [comment]
Please tone down and refrain from posting more than once within a short time.

The problem seems to be that all kinds of terminal emulators don't correctly implement the XTerm Control Sequences for mouse events. You can read about it a bit here: http://unix.stackexchange.com/questions/76628/gnu-screen-weird-characters-on-click and https://bugs.launchpad.net/ubuntu/+source/screen/+bug/113227 

You might have more luck reporting this to the Emacs mailing list, in case it has anything to do with it. I am pretty sure this is not specific to Spacemacs because some problems persisted when I ran `emacs -q`, which you should try too. Feel free to post a link here in case you report it to the Emacs list.

**Comment by orenra** [comment]
I had a similar issue with ssh over browser to google compute. I found the answer here:
https://stackoverflow.com/questions/36319654/change-default-emacs-mouse-highlight-behaviour. Basically added (setq mouse-drag-copy-region nil).
