### ISSUE TITLE
have winner-mode work separately for each layout

### ISSUE THREAD

**Issue by honkhonkhonk** [syl20bnr/spacemacs#6253]
I find working with layouts frustrating since I frequently use winner-mode to switch buffers. Currently winner-undo opens the previous window configuration even if it's from a different layout. 

I would really like to have winner-undo/redo track a separate buffer history for each layout.

**Comment by TheBB** [comment]
CC @bmag :-)

**Comment by syl20bnr** [comment]
I thought the same as @TheBB when reading this :-)

**Comment by bmag** [comment]
Steps necessary to have winner-mode track separate buffer/window history for each layout:
- identify the variables, and possibly frame parameters, that winner-mode uses to keep track of changes in window configurations. Lets call these variables the "state" of winner-mode.
- add hooks:
  - save state as perspective parameters (`set-persp-parameter`) before changing layout (use `persp-before-switch-functions`)
  - load state (`persp-parameter`) after changing layout (use `persp-activated-functions`)
  - if winner-mode's state should persist between sessions (it probably shouldn't): save state as perspective parameters before saving layouts to file
- the same layout can be used in more than one frame, so each layout should save one winner-mode state for terminal frames and a different winner-mode state for graphical frames
- it seems that winner-mode stores different histories for different frames - each layout should only save and restore the winner-mode state that is relevant to the layout's frame. In other words, don't change state of other frames when loading a layout's winner-mode state.

If we also want separate winner-mode histories for different workspaces (within a layout):
- save workspace's state as perspective parameters before changing workspace or layout (`eyebrowse-pre-window-switch-hook`, `persp-before-switch-functions`)
- load workspace's state from perspective parameters after changing workspace or layout (`eyebrowse-post-window-switch-hook`, `persp-activated-functions`)

Implementing this will require some effort, and the code could be messy. I think it would help to have an external package that makes features local to layouts (perspectives) or workspaces. If I'll have the time, I might write such a package - but is's unlikely to happen before July/August.
