### ISSUE TITLE
fail to change powerline separators using recipe from documentation

### ISSUE THREAD

**Issue by apegushin** [syl20bnr/spacemacs#6258]
#### Description
Hi, I tried changing powerline default separators using a snippet from the official spacemacs DOCUMENTATION:
(defun dotspacemacs/user-config ()
  "This is were you can ultimately override default Spacemacs configuration.
This function is called at the very end of Spacemacs initialization."
  (setq powerline-default-separator 'arrow))
but it fails for me on a freshly cloned spacemacs repo. Fails as in no matter which separator I choose default separator is displayed.

#### Reproduction guide
- Start Emacs
- copy-paste the documentation recipe for changing powerline separators into .spacemacs
- restart spacemacs

*Observed behaviour:*
Separators did not change to the value specified.

*Expected behaviour:*
Separators should have changed to 'box or 'butt.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(git c-c   emacs-lisp)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by d12frosted** [comment]
Relevant: https://github.com/syl20bnr/spacemacs/issues/6161, https://github.com/syl20bnr/spacemacs/issues/6027 and some others.

In short - now you have to place `(spaceline-compile)` in `user-config`.

**Comment by d12frosted** [comment]
More info [here](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#powerline-separators) (it's currently not on master).

**Comment by apegushin** [comment]
Thank you, that worked.

**Comment by d12frosted** [comment]
:+1: Soon it will be in master :)
