### ISSUE TITLE
neotree misbehave after invoking `evil-move-window-far-right/left'

### ISSUE THREAD

**Issue by autosquid** [syl20bnr/spacemacs#6261]
The neotree buffer stays, but its width changes， and key-bindings not working (I suspect it is no longer a vaid neotree). -- for example, press `g r` to refresh, a new frame is opened.

**Comment by bmag** [comment]
Can you explain in a bit more detail what's happening? I'm experiencing something a bit different:

#### Steps:
- start with a frame containing a single window, showing some file
- `SPC f t` to open neotree. there are now 2 windows: neotree on the left, original file on the right
- `SPC w L` (`evil-window-move-far-right) to move neotree to the far right

#### Observed behavior:
The other window is deleted, neotree's window occupies the whole frame. There's an error message:
> Window #<window 551 on  *NeoTree*> too small for splitting 2

Pressing `g r` doesn't appear to do anything (there's probably nothing to refresh), other neotree key-bindings work as expected.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 06a7731)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.5 auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip t company-tooltip-align-annotations t)
 emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 markdown org
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control
 (latex :variables latex-enable-auto-fill t latex-enable-folding t)
 pdf-tools evil-cleverparens python command-log smex themes-megapack c-c++
 (clojure :variables clojure-enable-fancify-symbols nil)
 ruby common-lisp ibuffer octave imenu-list window-purpose nameless)
```

**Comment by bmag** [comment]
Neotree sets its window to have a fixed size, which throws an error when `evil-window-move-far-right` calls `split-window-horizontally`.
