### ISSUE TITLE
Proposal: new layer to support Programmer Dvorak

### ISSUE THREAD

**Issue by MadAnd** [syl20bnr/spacemacs#6264]
I have a [private layer](https://github.com/MadAnd/dotemacs/tree/master/layers/my-programmer-dvorak) that does minimal non-intrusive configuration to make Spacemacs usable with [Programmer Dvorak](http://www.kaufmann.no/roland/dvorak/) keyboard layout. At the moment it does the following:

* Adapt window navigation: `SPC 1` to `SPC &`, `SPC 2` to `SPC [` etc.
* Adapt layout and workspace navigation: `SPC l 1` to `SPC l &`, `SPC l 2` to `SPC l [` etc. Note that the preview bindings (e.g. `SPC l C-1`) are not adapted, because `C-[` works like `ESC` and I do not know how to circumvent that issue.
* Adapt `avy` and `ace-window` to Dvorak's home row.

If there is demand for such a layer in upstream, I can write a readme and make a PR.

**Comment by TheBB** [comment]
You should probably coordinate with @StreakyCobra and the bepo layer.

**Comment by CharlesHD** [comment]
Thire is some work on that already here : #5245

**Comment by StreakyCobra** [comment]
I've a `keyboard-layout` layer in the pipeline that will offer both `bepo` and `dvorak` support. Actually it's already working, I'm just fighting to find time to finalize it. Once done, your customizations would easily be moved in it :-)

**Comment by andysaini** [comment]
@StreakyCobra will it support default dvorak too?

**Comment by StreakyCobra** [comment]
I don't know the differences between the dvorak versions, but the layer is extensible to more than two keyboard layouts, so it will not be a problem to make a different remapping if needed.

**Comment by d12frosted** [comment]
@StreakyCobra how about Colemak? :D

**Comment by MadAnd** [comment]
@StreakyCobra I reviewed your layer and I like the fact that you allow fine grained selection of packages to reconfigure. Though, I prefer to stick with the default Spacemacs/Emacs bindings with minimal amount of remapping (see OP).

Your layer already does `avy` and `ace-window` configuration. However, if you plan to support Programmer Dvorak, you might find the code for remapping [window](https://github.com/MadAnd/dotemacs/blob/master/layers/my-programmer-dvorak/keybindings.el#L17), [layout](https://github.com/MadAnd/dotemacs/blob/master/layers/my-programmer-dvorak/packages.el#L52) and [workspace](https://github.com/MadAnd/dotemacs/blob/master/layers/my-programmer-dvorak/packages.el#L39) navigation useful.

**Comment by MadAnd** [comment]
Fixed by #6308

**Comment by syl20bnr** [comment]
#6308 is now in develop.

**Comment by vimuel** [comment]
I am a long-time Colemak user.

I would like to change as few keys as possible in spacemacs. I want to try a small cosmetic surgery that would implement the following behaviour:

![Colemak Vim](https://raw.githubusercontent.com/vimuel/screenshots/master/spacemacs/20160717_colemak_vim.png)

From what I understand, this would require simply swapping `j` and `k`.

How should I best do this?

addendum {
An alternative that I considered:

![Colemak Vim Alternative](https://raw.githubusercontent.com/vimuel/screenshots/master/spacemacs/20160717_colemak_vim_alternative.png)

I think this would make things too complicated, however. Any constructive feedback is much appreciated.
}
