### ISSUE TITLE
Missing script in documentation page

### ISSUE THREAD

**Issue by geekplux** [syl20bnr/spacemacs#6267]
missing the `jquery.stickytableheaders.js`.

<img width="686" alt="screen shot 2016-06-09 at 02 01 31" src="https://cloud.githubusercontent.com/assets/3816105/15906155/3bc117dc-2dea-11e6-92d4-4668402e2951.png">

there may be some alternative link.

**Comment by NJBS** [comment]
I don't get this error on the `develop` site:

http://develop.spacemacs.org/doc/DOCUMENTATION.html

By the way, the repo for site is [here](https://github.com/syl20bnr/develop.spacemacs.org).

**Comment by geekplux** [comment]
develop LGTM.

because there is no depends to `jquery.stickytableheaders.js`...

Thanks  :)
