### ISSUE TITLE
Error with Gist layer `SPC g g l` isn't working

### ISSUE THREAD

**Issue by geo7** [syl20bnr/spacemacs#6268]
I've just set up an oauth token and put it into the git config file in `~/`

I can create public / private gists of buffer / region, but I'm not able to
access this `list buffer` thing. I've not actually accessed it before, so I'm
not sure what I'm missing.

Here's the error I get;

```text
byte-code: Wrong type argument: listp, "https://developer.github.com/v3"
```

To reproduce all you have to do is type `SPC g g l` (presuming things are
setup).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 022ce99)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t auto-completion-tab-key-behavior 'complete)
 better-defaults c-c++ colors emacs-lisp emoji erc evil-snipe eyebrowse git github haskell html ipython-notebook javascript latex markdown ranger org python
 (shell :variables shell-default-shell 'eshell shell-default-height 30)
 syntax-checking themes-megapack version-control yaml)
```

#### edit

Problem was that I had the wrong user name in my gitconfig - running a backtrack as suggested fixed this.

**Comment by StreakyCobra** [comment]
I can access the list with `SPC g g l` on `develop`. I don't remember having done anything special for this. Maybe try `develop` or try updating your packages.

----

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 022ce99)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 bb-git bb-latex bepo better-defaults c-c++ clojure colors command-log csv dash deft dockerfile
 (elfeed :variables rmh-elfeed-org-files
         (list "~/org/main.org"))
 encoding emacs-lisp emoji erc erlang ess evil-cleverparens extra-langs finance git github haskell html imenu-list ipython-notebook java javascript latex markdown mu4e nginx no-dots ocaml org pandoc php plantuml python ranger rebox restclient ruby rust scala semantic shell shell-scripts speed-reading
 (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
 sql syntax-checking systemd themes-megapack theming typography
 (version-control :variables version-control-diff-tool 'diff-hl)
 vimscript yaml)
```

**Comment by geo7** [comment]
still gives me the same error - updated issue with new system info

**Comment by TheBB** [comment]
Please show us a backtrace. `SPC t D`.

**Comment by geo7** [comment]
@TheBB fixed - the problem was the username was incorrect in the gitconfig , backtrace showed this. Thanks
