### ISSUE TITLE
Persistent visual state highlighting while in normal state

### ISSUE THREAD

**Issue by stonecauldron** [syl20bnr/spacemacs#6269]
#### Description

Highlighting of visual state while in normal state
#### Reproduction guide
- Start Emacs
- Enter any editable buffer
- Enter insert mode
- Type `C-F` (ctrl-shift-f I am not sure about the convention for the shift key)
- Some text gets selected
- Type `ESC` to return to normal state
- Move around with `h j k l`

_Observed behaviour:_
Previously highlighted text stays highlighted. Furthermore moving around causes the selection to grow

_Expected behaviour:_
Highlighted selection should disappear when returning to normal state.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell shell-default-term-shell "/usr/local/bin/zsh")
                 (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
                 syntax-checking version-control c-c   lua osx scala latex javascript elm
                 (racket :variables racket-pretty-lambda t))
```
#### Backtrace

```

```

**Comment by syl20bnr** [comment]
I can confirm this bug and can reproduce with `SPC q D evil RET` (just evil enabled). Should report this bug upstream in evil repo: https://bitbucket.org/lyro/evil/wiki/Home

**Comment by stonecauldron** [comment]
I've reported the issue upstream: https://bitbucket.org/lyro/evil/issues/675/highlighting-of-visual-mode-persists-while

**Comment by stonecauldron** [comment]
It seems that the policy of evil-mode is to only rebind keys that have a direct equivalent in Vim. Free keys should maintain their original emacs functionality.

Austin Smith commented on issue #675:
Highlighting of visual mode persists while in normal mode
Keep it as it is, because the package tries to be as non-intrusive to Emacs as possible. I think if Vim has an open binding (like C-SPC), it should do what Emacs does.
If a user really finds C-SPC to be annoying, they can disable it themselves easy enough. Although it is confusing at first, and should probably be made more obvious, somehow.

(For some reason his comment does not show so I've reproduced it here)

Given this information, I think we can tag this issue as a wontfix

**Comment by DataBranner** [comment]
Persistent highlighting can be turned off _manually_ with `:nohl` or by searching for the end of a line with `/$`.
