### ISSUE TITLE
Paredit rebind keys?

### ISSUE THREAD

**Issue by endrebak** [syl20bnr/spacemacs#627]
I'm just starting out with Clojure/Paredit, but it seems to me the paredit keybindings are not very good for evil users.

Seems like magnars has found a way to rebind the paredit keymap:
https://github.com/magnars/.emacs.d/blob/master/settings/setup-paredit.el

Could something similar be added to paredit in Spacemacs?

And does anyone have any ideas for a good way to rebind regular paredit commands to keys that are not RSI-inducing?

We will perhaps want to start with these: http://www.braveclojure.com/using-emacs-with-clojure/#5_4__Summary

**Comment by endrebak** [comment]
Background: Rebinding paredit keys is supposedly a lot harder than for other modes. See http://stackoverflow.com/questions/16605571/why-cant-i-change-paredit-keybindings

**Comment by syl20bnr** [comment]
@endrebak you can give a go with `SPC k` which is the lisp state, it is now available everywhere since `0.62.0` (so the release of yesterday :-))

Documentation here: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#editing-lisp-code

**Comment by syl20bnr** [comment]
@endrebak I realize that the documentation is slightly not up to date.

`slurp` is on `s` not `n`.
`SPC m` is false, it is `SPC k` now.

Not that guide-key will work now with `SPC k`.

**Comment by endrebak** [comment]
Nice. 

Short q: I use M-s to save. What would be the best way of preventing paredit to rebind that command be?

This did not work:

```
  (eval-after-load 'paredit-mode
    (global-set-key "\M-s" 'save-buffer))
```

**Comment by t3chnoboy** [comment]
I'm going to port https://github.com/tpope/vim-sexp-mappings-for-regular-people this weekend.

**Comment by syl20bnr** [comment]
@endrebak you should use a hook instead of a `eval-after-load`, the hook happens at activation time whereas the `eval-after-load` can happen before the mode kicks in.

@t3chnoboy interesting !

**Comment by syl20bnr** [comment]
@endrebak to be complete, the other method available in spacemacs to save a buffer are:
- `SPC : w`
- `SPC f s`

**Comment by endrebak** [comment]
@t3chnoboy Look forward to seeing it.

@syl20bnr Thanks for the tip. I guess this issue can be closed since slurping and barfing is possible without breaking my fingers?

**Comment by endrebak** [comment]
I have changed the clojure layer to use smartparens instead of paredit and included the following line in my `.spacemacs`:
```
dotspacemacs-excluded-packages '(paredit)
```
but paredit is still started when I open a clojure file. How do I banish it?

**Comment by syl20bnr** [comment]
Just checked the clojure layer and it is not conventional so excluding packages has no effect.
I'll refactor it tonight.

Meanwhile a work around is to add a hook to disable paredit.

**Comment by endrebak** [comment]
When I get the time I'll be trying out [lispy](https://github.com/abo-abo/lispy) by emacs pro abo-abo.
lispy is a vi-mode for paredit.

**Comment by syl20bnr** [comment]
Take a look at [paxedit](https://github.com/promethial/paxedit) too.

**Comment by syl20bnr** [comment]
I close this question. Feel free to reopen if needed.

**Comment by murtaza52** [comment]
Hi,

Did you get a chance to look at either lispy or paxedit ? Are they integrated in sapcemacs. 

Also I would love to use spacemacs for clojure. Does it have a clojure layer, or will it just work out of the box if I install clojure-mode ?

Thanks,
Murtaza

**Comment by endrebak** [comment]
Spacemacs has a `clojure` contrib layer that uses CIDER. There is an `evil-lispy` I have not had the time to try. Will do but I found the built-in spacemacs lisp movements in pretty nice  so using them until I get time to try the other stuff.

**Comment by bjeanes** [comment]
You can also put `(sp-use-paredit-bindings)` in your `dotspacemacs/config` function to get paredit-like behaviour out of the included packages.
