### ISSUE TITLE
ranger-travel does not expand ~ to $HOME

### ISSUE THREAD

**Issue by jbeigel** [syl20bnr/spacemacs#6272]
#### Description

ranger-travel (triggered by pressing f in ranger), doesn't expand ~ in helm buffer when below $HOME.
#### Reproduction guide
- Start Emacs
- open ranger (SPC a r), navigate to some directory below $HOME (not $HOME itself)
- issue ranger-travel (f)

_Observed behaviour:_
The path is displayed as ~/somedir/ and no contents of the directory is shown.

_Expected behaviour:_
Expand ~ to $HOME and actually list directory contents.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
 emacs-lisp git happymake haskell my-magit-gerrit org osx python ranger rtags syntax-checking themes-megapack version-control)
```

**Comment by jbeigel** [comment]
There's probably a call to expand-file-name missing in ranger-travel. Or is helm supposed to expand this?

**Comment by StreakyCobra** [comment]
CC @ralesi

**Comment by ralesi** [comment]
I will take a look at this,  but I am thinking this is all helm,  all travel does is prompt with `helm-find-file`
