### ISSUE TITLE
Error at load: "Don't know how to compile nil"

### ISSUE THREAD

**Issue by bhilburn** [syl20bnr/spacemacs#6276]
#### Description
When spacemacs is started, the following error is displayed in the `Compile-Log`:

![compile-nil](https://cloud.githubusercontent.com/assets/569571/15941932/42650cea-2e50-11e6-87ed-5e5d3b21b91e.png)

I deleted everything in `~/.emacs.d/elpa/` and let spacemacs redownload / compile everything, but the same error occured:

![fresh](https://cloud.githubusercontent.com/assets/569571/15941966/60ee183c-2e50-11e6-98ba-905cd2da63a6.png)

Running spacemacs with `--insecure` does not solve the problem.

#### Reproduction guide
While running:
    (emacs-24.5.1)                                          (spacemacs-0.105.2)

With the following configuration-layers enabled:

     auto-completion
     ;; better-defaults
     c-c++
     colors
     dockerfile
     emacs-lisp
     git
     haskell
     html
     javascript
     latex
     markdown
     org
     python
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     shell-scripts
     spell-checking
     syntax-checking
     version-control
     vimscript
     yaml
     )

Start spacemacs as you would normally.

*Observed behaviour:*
spacemacs always displays an error about compiling `nil`.

*Expected behaviour:*
spacemacs does not display an error at boot

#### System Info
- OS: gnu/linux (Fedora 22)
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((c-c   :variables c-c  -enable-clang-support t))
```

**Comment by t-ander** [comment]
This is happening for me as well.
- OS: Fedora 23
- Emacs: 24.5.1
- Spacemacs: 0.105.21

Fresh install, haven't touched config at all.

**Comment by jmcarthur** [comment]
Also happening to me.

* OS: CentOS 6.6
* Emacs: 24.5.3
* Spacemacs: 0.105.21

**Comment by TheBB** [comment]
This is an issue with `persp-mode`. I was able to reproduce it with stock Emacs and only persp-mode.

**Comment by TheBB** [comment]
I'm 99% certain this is fixed upstream by https://github.com/Bad-ptr/persp-mode.el/commit/d1e13ca908050f895d6e6e56e28284acf040b6b3 and you only need to wait until it makes its way to MELPA.

CC @Bad-ptr maybe you can verify

**Comment by TheBB** [comment]
By the way @bhilburn you are setting some layers incorrectly in your dotfile. Should probably fix that. :-)

**Comment by microamp** [comment]
Upgraded to the latest version of `persp-mode` and it's no longer happening. Thanks guys.

**Comment by bhilburn** [comment]
@TheBB - Sorry, I'm totally new to `spacemacs` (or `emacs` in general, really) - just migrating after many years in Vim. Can you point me to something that describes how I'm configuring the layers incorrectly? It's not clear to me from looking at it.

**Comment by TheBB** [comment]
The autogenerated issue report doesn't show the same layers you claim to be using. That's because you override the value of dotspacemacs-configuration-layers after Spacemacs has started (and indeed you do that in user-config).

All layers should be declared in dotspacemacs/layers (near the top) and only there. That includes layer variables. Later changes to this variable won't have any effect because its value has already been read ams acted on by then.

**Comment by bhilburn** [comment]
@TheBB - Ah, I see what you are referring to. Frankly, I copied the lines out of [these docs for the c-c++ layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/c-c%2B%2B) without understanding how they should be used. The example from the [Vim migration guide of setting variables for git](http://jaremko.github.io/spacemacs.org/doc/VIMUSERS.html) helped me sort it out.

Thanks again for your help!
