### ISSUE TITLE
vim's macro invalid after first time call in  evil-mode 

### ISSUE THREAD

**Issue by chenyangguang** [syl20bnr/spacemacs#6278]
well, it's fail to call the vim's macro in spacemacs. Here is my step, and it can replay everytime like this:
1) q a
2) I 
3)  'test macro'
4)esc
5)q

Now i call the 'a' macro by @a in the other line for the first time, it works well.
But  emacs will shutdown working if i recall the vim's macro @a the second time.

**Comment by TheBB** [comment]
This doesn't seem right. You have to finish the recorded macro with `q` at some point. Also you are using `cw` after switching to insert state with `I`. Is this the exact key sequence you're using?

**Comment by chenyangguang** [comment]
Macro remember all the key comman before the another q. Sorry, exactly i use I and add + .(shift + '+').

**Comment by TheBB** [comment]
Thanks. I tried and I can't reproduce, the macro works fine for me. Do I need to have a particular file type?

**Comment by chenyangguang** [comment]
All right. Today it works ok.  I will reconfirm next time.

**Comment by TheBB** [comment]
Then I'll close for now. :-)
