### ISSUE TITLE
Update screenshot in documentation

### ISSUE THREAD

**Issue by d12frosted** [syl20bnr/spacemacs#6279]
It would be nice to have badge and `Made with :heart: by the community` on [that screenshot](https://github.com/syl20bnr/spacemacs/tree/develop#introduction).

**Comment by a13ph** [comment]
Just make automatic screenshot generation functions, finally.
That way it can be at least partially automated and there won't be need for dry texts without visuals and for excuse text of ~"Spacemacs moves too fast, screenshots are hard to update" :)

**Comment by d12frosted** [comment]
Ya. But probably we can make screenshots before major releases.
