### ISSUE TITLE
[Solved]Update issue

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [syl20bnr/spacemacs#6284]
I am a newbie with spacemacs, when I open emacs, current version is 0.105.20, then, it prompts that there is a new version 0.105.21, then, I click the up arrow in the bottom, it will open a popup window, the info is "Do you want to update to the newest version 0.105.21", I choose "yes", but nothing happens.

In addition, I use ```git fetch```  and ```git reset --hard 9c7250a ```, but the version still keeps 0.105.20.

I don't know if there is something wrong.

**Comment by syl20bnr** [comment]
This commit hash is weird, the current HEAD for master is `0283f647`.

**Comment by syl20bnr** [comment]
Are you on master or on develop ? Seems that you are on your own branch and you track the develop branch, the correct HEAD of develop is `9d7259d8` not really what you are using.

**Comment by d12frosted** [comment]
Hey,

It looks like you haven't forked Spacemacs, so it's highly likely that syl2bnr remote is named `origin`. So you have to:

```
$ git fetch [origin]
$ git reset --hard origin/master # if you wish to switch to latest master
$ git reset --hard origin/develop # if you wish to switch to latest develop
```

Using `origin/branch` is preferable in your situation as you don't need to check proper hash.

**Comment by ZhengshuaiPENG** [comment]
I think I am using master branch, because I install through the command
 ```
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
```
then my console output is
```
➜  .emacs.d git:(master) ✗ git fetch
remote: Counting objects: 84, done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 84 (delta 31), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (84/84), done.
From https://github.com/syl20bnr/spacemacs
   9c7250a..0283f64  master     -> origin/master
   9414a8a..1b77fd8  develop    -> origin/develop
```
I tried to set ```02834647```, now the version changed to 0.105.21.

I want to know why in the output it's ```0283f64``` but not ```0283f647```,
Thanks @syl20bnr

**Comment by TheBB** [comment]
> I want to know why in the output it's 0283f64 but not 0283f647

Same thing. Git lets you use just the first few characters, as long as it's unique. Usually seven or eight suffice. If you want to be technical about it, the real hash is `0283f6475b4207ff4f2f217322075eacd02030fc`.

**Comment by TheBB** [comment]
Anyway closing since it's solved.
