### ISSUE TITLE
Haskell defaults forcibly enable `haskell-tags-on-save`

### ISSUE THREAD

**Issue by bgamari** [syl20bnr/spacemacs#6292]
The `+lang/haskell` layer appears to forcibly set `haskell-tags-on-save`, overriding the user's own configuration. This is a very opinionated setting and is quite detrimental to user experience when working on large projects as `hasktags` hangs the editor for several seconds on every save.

**Comment by TheBB** [comment]
If you're planning on PRing that commit, please do not include any changes to the changelog.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
