### ISSUE TITLE
Spaceline overflows if font size is increased

### ISSUE THREAD

**Issue by pavkum** [syl20bnr/spacemacs#6299]
#### Description :octocat:

Spaceline overflow if font size is increased
#### Reproduction guide :beetle:
- Start Emacs
- open .spacemacs file
- increase font size to 15
- split window vertically (don't enable golden ratio) with equal width
- open a version control managed large file which has flycheck enabled and having couple of minor modes (had 1 fly check error in my case)
- now scroll page using page-down / page-up

_Observed behaviour:_ :eyes: :broken_heart:
The scroll position indicator at far right of spaceline along with line/column indicator gets hidden

_Expected behaviour:_ :heart: :smile:
Spaceline should have auto adjusted the layout by collapsing few segments
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: nil (rev. 022ce99)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(eyebrowse javascript html helm emacs-lisp typescript git org
           (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

I'm using default source code pro font. Works fine for font-size 14.
I tried scaling down `powerline-scale` property but with no sucess.

**Comment by TheBB** [comment]
This should be reported to Spaceline, and in fact it has been: https://github.com/TheBB/spaceline/issues/46

**Comment by deb0ch** [comment]
This was resolved in https://github.com/TheBB/spaceline/pull/133, I think this issue should be closed now.
