### ISSUE TITLE
ivy layouts buffer switching doesn't respect layout

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#6300]
`SPC l b` (switch to buffer respecting layouts) doesn't work with `ivy`.

The relevant function in the `ivy` layer:

``` emacs-lisp
(defun spacemacs/ivy-spacemacs-layout-buffer ()
  "Switch to layout buffer using ivy."
  (interactive)
  (let (ivy-use-virtual-buffers)
    (with-persp-buffer-list ()
                            (call-interactively 'ivy-switch-buffer))))
```

However, `ivy-switch-buffer` doesn't use `buffer-list` internally, so `with-persp-buffer-list` here doesn't do anything.

**Comment by d12frosted** [comment]
Hm... indeed. But I think previously it worked. I mean, I remember `SPC l b` helping me a lot compared to `SPC b b`.

**Comment by ahyatt** [comment]
FWIW, there is a gist with code to fix this linked from persp-mode: https://gist.github.com/Bad-ptr/1aca1ec54c3bdb2ee80996eb2b68ad2d#file-persp-ivy-el

**Comment by bmag** [comment]
@ahyatt thanks, that looks promising.

**Comment by TheBB** [comment]
Should be fixed in master.
