### ISSUE TITLE
OSX Crashing when closing full screen window

### ISSUE THREAD

**Issue by eastwood** [syl20bnr/spacemacs#6301]
#### Description
I'm on OSX `10.11.5`.
Spacemacs `master` => `0.105.x`
emacs -v => `24.5.1`

When I fullscreen emacs, open a new window and then kill said window. Emacs crashes.

#### Reproduction guide
- Start Emacs GUI
- Put emacs into fullscreen `SPC T F`
- Create new window `S-n` or `C-x 5 2`
- Kill Frame `C-x 5 0` or `S-w` or `Click close window`

*Observed behaviour:*
Emacs crashes

*Expected behaviour:*
The selected window closes and emacs continues to run.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp javascript react git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking version-control)
```

**Comment by benquebec** [comment]
Can et Can't reproduce ;)

Can reproduce on 10.11.1
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.6
- Spacemacs: 0.105.20
- Spacemacs branch: develop (rev. 9414a8a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git latex org osx pdf-tools spell-checking syntax-checking version-control)

Can't reproduce on 10.9.5 with same spacemacs configuration.

HTH

**Comment by d12frosted** [comment]
I can't reproduce it on 10.11.5 (15F34). 

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 52202cc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy

**Comment by benquebec** [comment]
just updated spacemacs and packages: still occurs on 10.11.1

switched to ivy: still occurs


#### System Info :computer:
- OS: darwin
- Emacs: 24.5.6
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 52202cc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion emacs-lisp git ivy latex org osx pdf-tools spell-checking syntax-checking version-control)
```

**Comment by d12frosted** [comment]
So switching to Emacs 25 fixes it? @eastwood could you try using Emacs 25?

**Comment by d12frosted** [comment]
I will also try to reproduce with Emacs 24, but a little bit later.

**Comment by benquebec** [comment]
Switching to Emacs 25 fixes it for me (tried both ivy and helm).

**Comment by d12frosted** [comment]
I believe it's not `ivy` or `helm` related thing :)

**Comment by eastwood** [comment]
@d12frosted Cannot reproduce on Emacs 25.

**Comment by gehrman** [comment]
This seems to be a problem in emacs itself:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-01/msg00763.html
https://lists.gnu.org/archive/html/bug-gnu-emacs/2015-11/msg00020.html

My work-around, since I don't want to right emacs 25, is the following:
```lisp
(defun demaximize-frame ()
  "Unmaximize the current frame if maximized, otherwise do nothing."
  (if (equal (assoc 'fullscreen (frame-parameters))
             (cons 'fullscreen 'fullboth))
      (toggle-frame-fullscreen)))
(defun before-evil-quit (orig-fun &rest args)
  "Work around OS X / Emacs 24 fullscreen quit crash."
  (demaximize-frame))
(advice-add 'evil-quit :before #'before-evil-quit)
```

It won't fix the crashes, but it has prevented me from losing any more work.

**Comment by d12frosted** [comment]
Ok, I am able to reproduce the bug with Emacs 24.5 running it with `-Q` option. There is nothing Spacemacs can do here. Either wait for new version of Emacs 24 which will hopefully fix it or use Emacs 25 which already has a fix :D 

I think it's better to leave this issue open as Emacs 24.5 is supported by Spacemacs.

**Comment by d12frosted** [comment]
Closing this issue as for now you can install only Emacs 25 using `brew` (recommended way).

**Comment by adrianbrink** [comment]
The same bug happens with 25.1.90. I would vote to open this issue again.

**Comment by muhifauzan** [comment]
Also happens with 25.1.1

**Comment by KevinSjoberg** [comment]
Still get this in emacs 25.1.1.

**Comment by mekeor** [comment]
Is there a current/active/recent bug-report for this for GNU Emacs 25(.1.1)?

**Comment by Leimy** [comment]
I've been building Emacs on my Mac. As of yesterday, this still happens for me. I don't use spacemacs either. Not a spacemacs issue.

**Comment by matthewbauer** [comment]
Still have this issue in GNU Emacs 26.0.91 with the "Nextstep" backend.

This does not happen in Mitsuharu's "mac" backend, however.

**Comment by GamovCoder** [comment]
Can reproduce on GNU Emacs 25.1.1 (OS X High Sierra)

**Comment by bitti** [comment]
Also happens to me with GNU Emacs 26.1 on Mac OS. Is this issue tracked somewhere in the GNU Emacs list?

**Comment by matthewbauer** [comment]
Here's a newer thread: https://lists.gnu.org/archive/html/emacs-devel/2018-03/msg00546.html

Basically you need to make sure you have the newest apple sdk when building emacs.

**Comment by baineng** [comment]
This issue still happens in Emacs 28.0.50, installed by @d12frosted 's [homebrew-emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus)
