### ISSUE TITLE
Proposal: new layer to insert template automatically

### ISSUE THREAD

**Issue by iiharu** [syl20bnr/spacemacs#6304]
I made new layer providing automatically template insertion. [here](https://github.com/YasuharuIida/spacemacs-auto-insert-template)
However , I think this feature might be part of the auto-complete .
Which would you like to choose new layer or part of auto-completion layer?

**Comment by d12frosted** [comment]
I like the idea. I found that package several days ago, added it to my private layer, but haven't tried it yet :-P

**Comment by Miciah** [comment]
Since #6893 is merged, can this issue be considered resolved and either closed or labeled "Fixed in develop"?
