### ISSUE TITLE
Git time machine key bindings suggestions

### ISSUE THREAD

**Issue by hrvladev** [syl20bnr/spacemacs#631]
Is it possible not to go to Emacs state to use [git-timemachine](https://github.com/pidu/git-timemachine)?

There are a couple of keys to be mapped:

> - `p` Visit previous historic version
> - `n` Visit next historic version
> - `w` Copy the abbreviated hash of the current historic version
> - `W` Copy the full hash of the current historic version
> - `q` Exit the time machine.

However, I'm not sure which are the best choices. Once we got to git-timemachine (`<SPC> g t`) we end up in evil's normal state and I don't know what are the conventions in this situation.

I have some mere suggestions:

`p` -> `C - k`
`n` -> `C - j`
`w` -> ???
`W` -> ???
`q` -> `fd` and `q`

**Comment by syl20bnr** [comment]
There is no convention for this tricky case.
`C-j` and `C-k` are very good choices for changing the revision.
Since the buffer is read-only we have also the possibility to override the key bindings in `normal state` like `c`, `s` etc....

**Comment by hrvladev** [comment]
@herbertjones resolved this issue with #653 :heart:
