### ISSUE TITLE
Python mode company not working

### ISSUE THREAD

**Issue by zhewuzhou** [syl20bnr/spacemacs#6313]
Steps to reproduce it(Emacs version 24.5.1       Spacemacs  0.105.21        OS X EI Capitan        Python 3.5):
- Install whole new spacemacs with only python and auto-completion layers enabled
<img width="730" alt="screen shot 2016-06-13 at 3 09 06 pm" src="https://cloud.githubusercontent.com/assets/1425814/15999507/d41e68cc-3178-11e6-8a6c-600a867d2aac.png">
- Open a python file which has a local variable
<img width="796" alt="screen shot 2016-06-13 at 3 04 52 pm" src="https://cloud.githubusercontent.com/assets/1425814/15999427/55cbad0e-3178-11e6-95b0-9d5af4ffde12.png">
- Type the first five chars of that local variable, expect completions show up but nothing happened
- M-x company-complete and get this error message: 
<img width="1123" alt="screen shot 2016-06-13 at 3 04 31 pm" src="https://cloud.githubusercontent.com/assets/1425814/15999436/681dc17c-3178-11e6-9c3b-a0e6cf903780.png">
- It's actually works previously I experienced maybe 2 months before.

**Comment by zhewuzhou** [comment]
Could someone shed light on it? I am new to use spacemacs working on python stuff

**Comment by cpaulik** [comment]
What does your `*anacoda-mode*` buffer display? If you are using python from homebrew then your pip is broken.

**Comment by zhewuzhou** [comment]
<img width="1131" alt="screen shot 2016-06-13 at 4 03 53 pm" src="https://cloud.githubusercontent.com/assets/1425814/16000717/8a2f9fe4-3180-11e6-9ee2-318d22c5fb04.png">

**Comment by zhewuzhou** [comment]
@cpaulik Thanks, you are right something wrong with pip in *anacoda-mode*

**Comment by zhewuzhou** [comment]
It's works as I take the suggestion from http://stackoverflow.com/questions/24257803/distutilsoptionerror-must-supply-either-home-or-prefix-exec-prefix-not-both thank you again @cpaulik
