### ISSUE TITLE
PageUp/PageDown behavior broken (doesn't go to top/bottom of buffer)

### ISSUE THREAD

**Issue by michaelbeaumont** [syl20bnr/spacemacs#6316]
#### Description
Spacemacs scrolling (especially PageUp/PageDown) appears broken, at best unintuitive.

#### Reproduction guide
- Start Emacs (using newly cloned repo and default .spacemacs)
- Open a file longer than one screen size, scroll to the bottom and try hitting PageUp

*Observed behaviour:*
PageUp will stop scrolling the window such that if the cursor is at the bottom of the window (i.e. 5 lines away because scrolling lower will push the window down), then PageUp will not move the window further than 3 lines from the top. This means repeatedly hitting PageUp will not show the beginning of the file.
Using `(setq smooth-scroll-margin 0)` fixed this issue, but creates another because Emacs will recenter the window on scrolling. Setting `(setq scroll-conservatively 10000)` or `(setq scroll-step 1)` or `(setq auto-window-vscroll nil)` or any combination of those DOES NOT fix this issue, the screen will still jump. 

This appears to be a recent regression due to package updates in the last week or so. On `develop` it appears not to be a problem

*Expected behaviour:*
PageUp/PageDown should push the window as far as possible, and with PageUp (PageDown) leave the cursor at the bottom (top). Scrolling should be as intuitive as it is with vim.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

**Comment by TheBB** [comment]
This is fixed in develop (as you say) due to recent changes in the scrolling setup.

**Comment by michaelbeaumont** [comment]
OK, I'll just switch to develop I guess. When does a bug fix like this make it into master though?

**Comment by TheBB** [comment]
When the next release happens. :-)

Hopefully that shouldn't be too long. It's been a while since last time.

**Comment by tddsg** [comment]
I also face the same problem with the Page-Up key in Emacs Lisp mode. I did switch to the `develop` branch but it didn't work. The weird thing is that so far only EmacsLips mode is affected. In other mode like Tuareg, Latex, both the two keys Page-Up Page-Down work perfectly...

**Comment by alanbernstein** [comment]
This also bothers me; I didn't want to mess with develop.

I just took the bindings for pageup and pagedown and bound them to M-v and C-v:

  (global-set-key (kbd "M-v") '(lambda nil (interactive) (condition-case nil
                                                             (scroll-down) (beginning-of-buffer (goto-char (point-min))))))
  (global-set-key (kbd "C-v") '(lambda nil (interactive) (condition-case nil
                                                             (scroll-up) (end-of-buffer (goto-char (point-max))))))

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
