### ISSUE TITLE
Go configuration layer errors during installation

### ISSUE THREAD

**Issue by Futile** [syl20bnr/spacemacs#632]
##### Steps to reproduce:
1. Install a fresh version of spacemacs(v 0.62.0)
2. Create a `.spacemacs` via `dotspacemacs/install`
3. Add the configuration layer `go`
4. Restart spacemacs

##### What will go wrong:
Installation of `go` will come up with errors also mentioning `company`. Some SPC-subcommands won't work, e.g. `SPC f s` or `SPC f e d`

##### Mitigation:
Removing `go` again will solve the issue.

**Comment by Funnnny** [comment]
I have added a PR with company-go loading fix, can you please test?

It works fine for me.

**Comment by Funnnny** [comment]
okay there's some extra problem with recent commit regarding improved GOPATH loading. I will look into it.

**Comment by Funnnny** [comment]
You might need #630 which contains the GOPATH fix

**Comment by Futile** [comment]
With both #630 and #634 I still get the following error during Installation of `go`(I only tested with both of them, not with only #634):

`Compiling file /home/felix/.emacs.d/elpa/company-go-20150109.2051/company-go.el at Thu Feb 19 12:04:32 2015  
company-go.el:19:13:Error: Cannot open load file: no such file or directory, go-mode`

But afterwards, everything seems to work fine. E.g. all keybindings working, and working auto completion in `.go` files.

**Comment by Funnnny** [comment]
it shouldn't be like that, can you double check in contrib/lang/go/packages.el, line 46. It should have this: eval-after-load 'go-mode

**Comment by syl20bnr** [comment]
@Futile it should be fixed in 0.62.1.

**Comment by Futile** [comment]
I will check as soon as I can when I'm home again.

**Comment by Futile** [comment]
Fixed with 0.62.1! I probably got something wrong when I merged the two PRs locally. Thanks for the fast replies!
