### ISSUE TITLE
Emacs daemon fails to start

### ISSUE THREAD

**Issue by StreakyCobra** [syl20bnr/spacemacs#6321]
#### Description :octocat:
Starting a new `emacsclient` instance in daemon mode fails. It works normally in standalone mode. Reproduced with a clean `.spacemacs`.

I was able to get a warning but I have no idea what's the bug causing this.

`git bisect` tell me that 8368be3c89b0bc872ce252c1dd5261792ff3c648 is responsible.

#### Reproduction guide :beetle:
- Start the dameon with `emacs --daemon`
- Connect to the daemon with `emacsclient -a emacs -c`

*Observed behaviour:* :eyes: :broken_heart:
`emacsclient` starts Spacemacs **not** fully loaded. `evil` is working for instance but it is not possible to use `SPC b b`

*Expected behaviour:* :heart: :smile:
`emacsclient` starts Spacemacs fully loaded.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 8368be3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 bb-git bb-latex bepo better-defaults c-c   clojure colors command-log csv dash deft dockerfile
 (elfeed :variables rmh-elfeed-org-files
         (list "~/org/main.org"))
 encoding emacs-lisp emoji erc erlang ess evil-cleverparens extra-langs finance git github haskell html imenu-list ipython-notebook java javascript
 (keyboard-layout :variables kl-layout 'bepo)
 latex markdown mu4e nginx no-dots ocaml org pandoc php plantuml python ranger rebox restclient ruby rust scala semantic shell shell-scripts speed-reading
 (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
 sql syntax-checking systemd themes-megapack theming typography
 (version-control :variables version-control-diff-tool 'diff-hl)
 vimscript yaml)
```

#### Backtrace :paw_prints:
```
Warning (initialization): An error occurred while loading `/home/fabien/.emacs.d/init.el':

Wrong type argument: wholenump, -6

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

**Comment by StreakyCobra** [comment]
This seems related to #6315 but the fix doesn't appear to be working for daemon mode in my case.

**Comment by StreakyCobra** [comment]
It is possible to set `dotspacemacs-loading-progress-bar` to `nil` as a workaround.

**Comment by TheBB** [comment]
I fixed this on my end with https://github.com/syl20bnr/spacemacs/commit/dfad604faaa542080d252902babfdd392e354eea. Are you not on that commit?

**Comment by StreakyCobra** [comment]
Indeed, this fixed it, thanks! ( For my defense you pushed the commit after my morning update :stuck_out_tongue_winking_eye: )
