### ISSUE TITLE
org-html-export-to-html with info-js broken in org 8.3.x

### ISSUE THREAD

**Issue by alejandroerickson** [syl20bnr/spacemacs#6324]
#### Description

the org layer installs org 8.3.4 in which an important feature of `org-html-export-to-html` is broken.

Specifically, [Org-info-js folding is broken in 8.3 releases](https://lists.gnu.org/archive/html/emacs-orgmode/2015-09/msg00191.html)
#### Reproduction guide
- Start Emacs with the org layer
  open an org file containing

```
#+INFOJS_OPT: view:info toc:nil
* this is a heading 
this is content
* another heading
foo
```

and call `org-export-dispatch`, choosing html output in the dialogue, or call `org-html-export-to-html`
open the exported html file

_Observed behaviour:_
a webpage with only a signature.   none of the key commands work, nothing else is visible.  see the org bug reported to the org mailing list above.

_Expected behaviour:_
need a say of keeping the org layer but with org 8.2 until this is fixed.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp misc xkcd latex themes-megapack org speed-reading spell-checking
            (c-c   :variables c-c  -enable-clang-support t)
            auto-completion cscope)
```

**Comment by TheBB** [comment]
> need a say of keeping the org layer but with org 8.2 until this is fixed.

You can use recipes to point the package to a different source.

http://spacemacs.org/doc/LAYERS.html#orgheadline11

Add org-plus-contrib to your dotspacemacs-additional-packages with a suitable `:location`.

**Comment by alejandroerickson** [comment]
I was unable to figure out how to make a recipe that installs org 8.2 and I can't seem to find the repository containing org or org-plus-contrib, and even if I installed org-plus-contrib, I don't know whether I can control the org version number there.  But emacs already has org 8.2 build-in, so I just did a quick work-around, removing org-plus-contrib from `(setq org-packages '( ...))` in layers/org/packages.el.

For posterity, recipies are documented [here](https://github.com/melpa/melpa#recipe-format).

**Comment by d12frosted** [comment]
Yeah, I also don't know how to force specific version. In some rare cases it would be nice to have such ability.

**Comment by TheBB** [comment]
You can

* use a recipe pointing to the repo and a `:commit` or `:branch` pointing to the right version
* check out or download the source code yourself and use a path as `:location` (note this works as a local package so no automatic autoload generation in this case)
