### ISSUE TITLE
failing to cleanup whitespace

### ISSUE THREAD

**Issue by ankhers** [syl20bnr/spacemacs#6333]
#### Description
When `dotspacemacs-whitespace-cleanup` is set to `all`, it fails to actually cleanup whitespace on save.

#### Reproduction guide
- Start Emacs
- Open a file
- Edit file, making sure to add superfluous whitespace
- Save 

*Observed behaviour:*
The white space is not cleaned up

*Expected behaviour:*
This whitespace to be cleaned up

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(c-c++ common-lisp elixir emacs-lisp elm erlang go html idris java javascript latex lua markdown purescript racket ruby rust sql yaml ruby-on-rails auto-completion better-defaults git github org colors jabber restclient dash erc gnus dockerfile spell-checking syntax-checking nixos intero)
```

#### Backtrace
None

Calling `whitespace-cleanup` manually also does not seem to change anything.

It seems like setting the variable to `changed` fixes the whitespace (only with what was changed). Also tested on latest develop.

**Comment by TheBB** [comment]
Can you provide some additional details, especially the precise contents of the file before saving?

**Comment by ankhers** [comment]
A simple ruby file.

``` ruby
class Foo       
  def initialize           
    puts "I am a new object"             
  end        
          
 
           
end             

```

Just because it doesn't show unless you highlight the code block, there are a number of extra spaces at the end of each line, even the completely empty lines.

**Comment by ankhers** [comment]
Apparently this is my fault. I'm modifying the `whitespace-style` variable and it is causing this to happen. I feel like this is actually working as intended. I have the following snippet in my `dotspacemacs-user-config`.

``` elisp
(setq whitespace-style '(face lines-tail))
(add-hook 'prog-mode-hook 'whitespace-mode)
```

If this is working as intended, feel free to close this ticket.
