### ISSUE TITLE
kill-buffer-and-window

### ISSUE THREAD

**Issue by freddie-freeloader** [syl20bnr/spacemacs#6334]
After using all the time `SPC b d` and `SPC w d`, I got tired of it and I use now `kill-buffer-and-window` (per default `C-x 4 0`).

It would be nice, if one could trigger this with `SPC b D` since `SPC b d` just deletes the buffer and `SPC w D` is already used.

Does this make sense to anyone else?

**Comment by bmag** [comment]
That does sound nice. I've used `kill-buffer-and-window` in the past and I'm sure I'd use it more if it had a better binding than `C-x 4 0`. Are you planning to submit a pull request?

**Comment by freddie-freeloader** [comment]
I'm reading *Beginner's Guide to Contributing a Pull Request to Spacemacs* right know. :smile:
