### ISSUE TITLE
ipython shell fails when query a variable 

### ISSUE THREAD

**Issue by shelper** [syl20bnr/spacemacs#6336]
#### Description

have ipython shell run, and if i do:

```
a = 1
a?
```

ipython shell fails and quits with message below:

> Traceback (most recent call last):
>   File "c:\Anaconda3\Scripts\ipython-script.py", line 5, in <module>
>     sys.exit(IPython.start_ipython())
>   File "c:\Anaconda3\lib\site-packages\IPython__init__.py", line 119, in start_ipython
>     return launch_new_instance(argv=argv, **kwargs)
>   File "c:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 596, in launch_instance
>     app.start()
>   File "c:\Anaconda3\lib\site-packages\IPython\terminal\ipapp.py", line 340, in start
>     return self.subapp.start()
>   File "c:\Anaconda3\lib\site-packages\jupyter_console\app.py", line 152, in start
>     self.shell.mainloop()
>   File "c:\Anaconda3\lib\site-packages\jupyter_console\interactiveshell.py", line 483, in mainloop
>     self.interact(display_banner=display_banner)
>   File "c:\Anaconda3\lib\site-packages\jupyter_console\interactiveshell.py", line 659, in interact
>     self.run_cell(source_raw)
>   File "c:\Anaconda3\lib\site-packages\jupyter_console\interactiveshell.py", line 203, in run_cell
>     self.handle_execute_reply(msg_id, timeout=0.05)
>   File "c:\Anaconda3\lib\site-packages\jupyter_console\interactiveshell.py", line 231, in handle_execute_reply
>     page.page(item['data']['text/plain'])
>   File "c:\Anaconda3\lib\site-packages\IPython\core\page.py", line 273, in page
>     return pager_page(data, start, screen_lines, pager_cmd)
>   File "c:\Anaconda3\lib\site-packages\IPython\core\page.py", line 247, in pager_page
>     page_dumb(strng,screen_lines=screen_lines)
>   File "c:\Anaconda3\lib\site-packages\IPython\core\page.py", line 76, in page_dumb
>     print(last_escape + os.linesep.join(screens[-1]), file=io.stdout)
> IndexError: list index out of range

This does not happen in the ipython shell in the cmd window
#### Reproduction guide

windows 7 64 bit, anaconda with python 3.5.1, ipython 4.1.2

-㊡ħ

**Comment by TheBB** [comment]
How are you running ipython?

**Comment by shelper** [comment]
"ipython console"

if i run "ipython" without console option, it seems everything is fine,
but the problem becomes that on windows figures will freeze.

which is described here:
http://stackoverflow.com/questions/16324497/ipython-in-emacs-no-figure-output/16357786#16357786

I dont know how to solve both of the issues.

**Comment by TheBB** [comment]
No, I mean, how are you running it in Spacemacs? Which key bindings are you using to launch it?

**Comment by shelper** [comment]
[C-c C-z] which calls python-switch-to-python-shell,
which runs: "ipython console"

**Comment by shelper** [comment]
any update on this?:(
i think it should be something related to the "readline" module in ipython shell in emacs. 
it is basically expecting more sys arguments
