### ISSUE TITLE
have to Ctrl-x in terminal to close Emacs in Cygwin

### ISSUE THREAD

**Issue by xarthurx** [syl20bnr/spacemacs#6339]
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description

When exit Emacs normally using Ctrl-x Ctrl-c, Emacs will freeze.
Then I need to press Ctrl-x (kill process) in Cygwin terminal to let Emacs continue the closing process...
Then Emacs will close normally.

When using my personal .emacs.d, everything works fine.
#### Reproduction guide
- Start Emacs
- Press Ctrl-x
- Press Ctrl-c

_Observed behaviour:_
DESCRIPTION OF THE OBSERVED BEHAVIOUR

_Expected behaviour:_
Ctrl-x Ctrl-c will close Emacs normally.
#### System Info
- OS: cygwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(emacs-lisp)
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by corngood** [comment]
I've noticed this too.  It's probably a bug in emacs or cygwin related to child processes, but I haven't actually reproduced it (yet) without spacemacs.

Usually when I start a spacemacs instance I get two child process `(list-processes)`: aspell and server.  When emacs is quitting it hangs with aspell still running.  If I kill the aspell process, emacs exits.

If I disable spell checking, I have only the server process, but it still hangs on exit.

If I comment out the `(server-start)` in init.el, I no longer get the hang.  If I manually run `(server-start)` the hang comes back.

However, if I start vanilla emacs with `emacs -q` and run `(server-start)`, there's no hang on exit.

That's all I've got so far, but I'll keep investigating.

**Comment by corngood** [comment]
Ah, ok, I tracked it down to:

```
(defadvice kill-emacs (around spacemacs-really-exit activate)
  "Only kill emacs if a prefix is set"
  (if (and (not spacemacs-really-kill-emacs)
           (spacemacs/persistent-server-running-p))
      (spacemacs/frame-killer)
    ad-do-it))
```

So I suppose this just doesn't work as intended with the windows GUI emacs?
