### ISSUE TITLE
help with evil keybindings for my media layer

### ISSUE THREAD

**Issue by alejandroerickson** [syl20bnr/spacemacs#6343]
I am trying to create media layer, starting with [EMMS](https://www.gnu.org/software/emms/).

At the moment the layer works in emacs state but I'm having trouble with evil key bindings.  I'm not too familiar with this so I've just tried to emulate things in other layers and documentation.  One user told me that emms-browser is not a real major mode, so evilify doesn't work properly there.

If you want to help and see the code please find it in [my spacemacs fork media layer](https://github.com/alejandroerickson/spacemacs/tree/myconfig/layers/media).

I'm looking to at least have evil bindings to cover the [bindings listed in the manual](https://www.gnu.org/software/emms/manual/#Browser-Interface)

**Comment by TheBB** [comment]
That was me. Did you see my note about the hook? It worked for me.

**Comment by alejandroerickson** [comment]
I see your message now (I was there, so I don't know how I missed that)

"You probably need to put evil-initialize in emms-browser-show-display-hook"

I did find and try to use `emms-browser-show-display-hook` but I don't know what evi-initialize is.  Are you suggesting a change to `emms-browser-show-display-hook` itself?

**Comment by TheBB** [comment]
I'm suggesting

```elisp
(add-hook 'emms-browser-show-display-hook 'evil-initialize)
```

**Comment by alejandroerickson** [comment]
Okay, yes I just figured it out and got it working.  My problem was that I did that in :config instead of :init, I think...  Anyway, it works now, and I replaced the "SPC" command with "t" using 

```

    (evilified-state-evilify-map emms-browser-mode-map
      :mode emms-browser-mode
      :bindings
      "t" 'emms-browser-toggle-subitems
     ;;"r" 'emms-browser-goto-random 
     )
```

**Comment by alejandroerickson** [comment]
Most things work now, including mark-mode, but opening an emms browser and using "s a <search term> RET" to search by artist seems to revert to evil's normal mode, rather than an evilified emms.  I don't see a hook for emms-browser-search, and its major mode is emms-browser.

Any suggestions?

**Comment by CharlesHD** [comment]
`emms-browser-search` calls `emms-browser-mode` then use `emms-browser-search-mode-map` for inputs. Seems like you have to evilify this keymap. 
From emms source : 
```elisp
(defun emms-browser-search-buffer-go ()
  "Create a new search buffer, or clean the existing one."
  (switch-to-buffer
   (get-buffer-create "*emms-browser-search*"))
  (emms-browser-mode t)
  (use-local-map emms-browser-search-mode-map)
  (emms-with-inhibit-read-only-t
   (delete-region (point-min) (point-max))))
```

**Comment by alejandroerickson** [comment]
Closing.  thanks for feedback.  made pull request.
