### ISSUE TITLE
Freezing on Full Screen Resizing

### ISSUE THREAD

**Issue by JZL** [syl20bnr/spacemacs#6344]
#### Description

Frequent Freezes of SpaceMacs if resize to/from full screen (i3wm)
#### Reproduction guide

I use i3wm on linux and I frequently use it's full-screen mode (think maximimze buffer but for windows) and often (but not every time), doing this freezes spacemacs 

_Observed behaviour:_
It freezes, is unresponsive to C-g and, on resizing the window, doesn't reflow.

I ran `kill -SIGUSR2 PID_SPACEMACS` which recovered the editor. I pasted at the very bottom the resulting debg trace

_Expected behaviour:_
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp git markdown org spell-checking syntax-checking html)
```
#### Backtrace

```
Debugger entered--Lisp error: (quit)
  redisplay_internal\  \(C\ function\)()
```

Thanks!

**Comment by a13ph** [comment]
I'm unsure if it plays part, but it might be relevant whether you run compositor or not, since Desktop Environments like Gnome, Unity etc use composition and it can affect redrawing and fullscreen.

**Comment by JZL** [comment]
If it helps, sometimes it takes 2 `kill`s and often the error is
```
Debugger entered--Lisp error: (quit)
  linum-update-window(#<window 7 on *Backtrace*>)
  mapc(linum-update-window (#<window 7 on *Backtrace*>))
  #[257 "r\211q\210\205	\303\212\304\305\306\303\307#\"\210)\304\310\n\"\210\303\211)\207" [linum-mode linum-overlays linum-available nil mapc linum-update-window get-buffer-window-list visible delete-overlay] 7 ("/usr/local/share/emacs/24.5/lisp/linum.elc" . 8212)](#<buffer functions.php<zerif-lite>>)
  ad-Advice-linum-update(#[257 "r\211q\210\205	\303\212\304\305\306\303\307#\"\210)\304\310\n\"\210\303\211)\207" [linum-mode linum-overlays linum-available nil mapc linum-update-window get-buffer-window-list visible delete-overlay] 7 ("/usr/local/share/emacs/24.5/lisp/linum.elc" . 8212)] #<buffer functions.php<zerif-lite>>)
  apply(ad-Advice-linum-update #[257 "r\211q\210\205	\303\212\304\305\306\303\307#\"\210)\304\310\n\"\210\303\211)\207" [linum-mode linum-overlays linum-available nil mapc linum-update-window get-buffer-window-list visible delete-overlay] 7 ("/usr/local/share/emacs/24.5/lisp/linum.elc" . 8212)] #<buffer functions.php<zerif-lite>>)
  linum-update(#<buffer functions.php<zerif-lite>>)
  linum-after-scroll(#<window 7 on *Backtrace*> 12801)
  redisplay_internal\ \(C\ function\)()
```
I am going to disable line numbers (I had relative line numbers and normal line numbers) and see if that helps

**Comment by LindyBalboa** [comment]
I have this issue using normal emacs 26 on Arch Linux also with i3wm. This is an emacs/i3wm issue not specific to spacemacs.

**Comment by JZL** [comment]
I agree with the bot, this is stale - for anyone else who finds the thread - I haven't had much issue with it anymore. I've been using spacemacs dev and master on 2 different installations of i3 without any difficulty. I seem to remember switching to ivy helped reduce hanging (compared to helm) but, to be honest, never went back to test out helm

Also if any spacemacs devs see this - I love spacemacs, use it every day all-day. Thanks for all the hard work :) !
