### ISSUE TITLE
evil-jumper is unavailable

### ISSUE THREAD

**Issue by mstry** [syl20bnr/spacemacs#6346]
index a64580c..4db28ca 100644
--- a/layers/+distribution/spacemacs/packages.el
+++ b/layers/+distribution/spacemacs/packages.el
@@ -1253,8 +1253,7 @@ Search for a search tool in the order provided by `dotspacemacs-search-tools'."
         "sS"    'spacemacs/helm-swoop-region-or-symbol
         "s C-s" 'helm-multi-swoop-all)
       (defadvice helm-swoop (before add-evil-jump activate)
\-        (when (configuration-layer/package-usedp 'evil-jumper)
\-          (evil-set-jump))))))
\+          (evil-set-jump)))))
 
 (defun spacemacs/init-helm-themes ()
   (use-package helm-themes

**Comment by TheBB** [comment]
Thanks, but this has been fixed in develop already it seems.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
