### ISSUE TITLE
`dotspacemacs-helm-resize` does not work when helm is on the right

### ISSUE THREAD

**Issue by deb0ch** [syl20bnr/spacemacs#6347]
#### Description :octocat:
dotspacemacs-helm-resize does not work when helm is on the right.

I did not start to investigate more than that, but if someone has some indications to give it would be gladly welcomed.

#### Reproduction guide :beetle:
- Start Emacs
- `dotspacemacs-helm-resize` is set to `t`
- Use C-x C-f

*Observed behaviour:* :eyes: :broken_heart:
- Helm-find-files takes more than half the screen

![screenshot from 2016-06-16 19-46-00](https://cloud.githubusercontent.com/assets/6248219/16127351/6422ab2e-33fc-11e6-837a-0131eb37231c.png)

*Expected behaviour:* :heart: :smile:
- Helm-find-file should be just as wide as its largest line (though a maximum would be nice)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. dfad604)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults c-c++ colors common-lisp emacs-lisp git gtags helm markdown multiple-cursors org python semantic
		 (shell :variables shell-default-height 50 shell-default-position 'bottom)
		 shell-scripts spacemacs-layouts syntax-checking version-control)
```

#### Backtrace :paw_prints:
```
Nope.
```

**Comment by TheBB** [comment]
This isn't a bug. I don't think helm supports this. You should make a feature request upstream instead.

**Comment by d12frosted** [comment]
I am closing this issue as there is no interest in reporting this issue upstream.
