### ISSUE TITLE
Editor config won't work in hybrid state while in insert mode

### ISSUE THREAD

**Issue by pavkum** [syl20bnr/spacemacs#6348]
### Description :octocat:

Editorconfig mode doesn't work while in insert state mode, but does work while in non editing state
#### Reproduction guide :beetle:
- Start Emacs
- install editor-config
- have .editorconfig in root dir of your project
- enable editorconfig mode
- apply editorconfig props by editorconfig-apply
- open a file in hybrid mode
- move to insert state
- modify indentation styling
- press tab

_Observed behaviour:_ :eyes: :broken_heart:
Nothing happens

_Expected behaviour:_ :heart: :smile:
Should have applied editorconfig rules
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: nil (rev. dfad604)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(csv eyebrowse javascript html ibuffer helm emacs-lisp typescript git ranger org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     (syntax-checking :variables syntax-checking-enable-by-default nil)
     theming)
```

But editorconfig works when ESCaped out of insert state. I'm not sure if this is the intended behaviour of hybrid state.

**Comment by TheBB** [comment]
Can you give some more precise reproduction steps? Specifically, file type, exact contents of file and the editorconfig file, and exactly where you expect a different indentation than you are getting.

**Comment by pavkum** [comment]
@TheBB I was wrong earlier. I generalized the bug. But the bug seems to be specific to web mode files. I'm able to reproduce the bug with .hbs and .html files but not with js / ts files.

Here is my editorconfig https://gist.github.com/pavkum/306fef0516979ef96b4fad99b0b86dd1

**Comment by TheBB** [comment]
Okay, I'm trying that file with HTML and I can't produce any errors. I'm getting two-space indents with spaces as expected. What exactly are you doing in hybrid/insert state?

**Comment by pavkum** [comment]
https://drive.google.com/file/d/0B4OkMG5Mt6VqMnFQQjI5clU1QXc/view?usp=sharing

I'm trying to indent by pressing <TAB> key here.

**Comment by TheBB** [comment]
At the end, right? Before that you are pressing space?

**Comment by pavkum** [comment]
@TheBB Yes.  Exactly

**Comment by TheBB** [comment]
Then I'm not sure what the problem is. You wanted two-space indents and you got it. The `<link>` tag is indented two spaces deeper than the `<head>`.

**Comment by pavkum** [comment]
@TheBB Please check this out. I have enabled command-log and walked though the issue.

https://drive.google.com/open?id=0B4OkMG5Mt6VqcTB5eXBiNDEtMlU

There is a difference in the behaviour of how js file is handled and how html file is handled

**Comment by TheBB** [comment]
Oh, that's because if emmet is enabled, it takes the tab key HTML.

**Comment by pavkum** [comment]
@TheBB went through the code base, would like to contribute if we can decide upon the expected behaviour

**Comment by pavkum** [comment]
@TheBB any thoughts on `C-<tab>` for `indent-for-tab-command`? I see <tab> is used at many places
