### ISSUE TITLE
Org-Mode Syntax Highlighting Doesn't Take Effect Immediately

### ISSUE THREAD

**Issue by bhilburn** [syl20bnr/spacemacs#6351]
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description

With the `org` layer enabled, `spacemacs` is configured to 'fontify' the code in code blocks in org documents by default. By 'fontify' I mean "syntax highlight", normally enabled by this:

```
(setq org-src-fontify-natively t)
```

After you create a code block, though, it doesn't immediately take effect. You have to either close & re-open the buffer, or you have to cut & paste the buffer.
#### Reproduction guide
- Start Emacs
- Start a new org-mode file.
- **type** in this code:

```
#+BEGIN_SRC c
uint32_t type = 0;
#+END_SRC
```
- Note that the code is _not_ syntax highlighted.
#### Method 1
- Kill the buffer.
- Reopen the buffer
- Note that the code _is_ syntax highlighted.
#### Method 2
- Select the lines and cut the text
- Paste the text
- Note that the code _is_ syntax highlighted.

_Observed behaviour:_
Code highlighting / fontification doesn't take effect when the code block is closed with `#+END_SRC`, but rather the text must be 'reloaded' somehow.

_Expected behaviour:_
Once the `#+END_SRC` line is entered, emacs properly 'fontifies' the code in the src block without needing the text to be 'reloaded'.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 colors dockerfile emacs-lisp git haskell html javascript latex markdown org python shell-scripts spell-checking syntax-checking version-control vimscript yaml)
```

**Comment by d12frosted** [comment]
Hey @bhilburn. It seems that I can't reproduce the problem here. Do you have any `org-mode` specific custom configurations?

**Comment by bhilburn** [comment]
@d12frosted - Nope, other than enabling the layer itself, I have no configuration.

So as soon as you type the `#+END_SRC` line, you see proper highlighting?

**Comment by d12frosted** [comment]
Ah, indeed. It's important to **type** by hand. I missed that, sorry. 

<img width="124" alt="screenshot 2016-06-17 09 39 21" src="https://cloud.githubusercontent.com/assets/6507913/16142629/95083600-346f-11e6-80a6-0a94a0c7581d.png">

And I see how annoying it is. I never encountered this problem because I usually insert blocks using this function (mostly stolen from Chris Done `.emacs.d`):

```
(defun d12-org/insert-block-template ()
  "Insert block template at point."
  (interactive)
  (if (org-at-table-p)
      (call-interactively 'org-table-rotate-recalc-marks)
    (let* ((choices '(("s" . "SRC")
                      ("e" . "EXAMPLE")
                      ("h" . "HTML")
                      ("q" . "QUOTE")
                      ("c" . "CENTER")))
           (key
            (key-description
             (vector
              (read-key
               (concat (propertize "Template type: " 'face 'minibuffer-prompt)
                       (mapconcat (lambda (choice)
                                    (concat (propertize (car choice) 'face 'font-lock-type-face)
                                            ": "
                                            (cdr choice)))
                                  choices
                                  ", ")))))))
      (let ((result (assoc key choices)))
        (when result
          (let ((choice (cdr result)))
            (cond
             ((region-active-p)
              (let ((start (region-beginning))
                    (end (region-end)))
                (goto-char end)
                (insert "\n#+END_" choice)
                (goto-char start)
                (insert "#+BEGIN_" choice "\n")))
             (t
              (insert "#+BEGIN_" choice "\n")
              (save-excursion (insert "\n#+END_" choice))))))))))
```

**Comment by TheBB** [comment]
This reproduces just fine with stock Emacs + Org, so it's an upstream bug.

**Comment by bhilburn** [comment]
@TheBB - Is the onus on the reporter to report upstream, or is that something the spacemacs devs typically handle?

**Comment by d12frosted** [comment]
@bhilburn there are no rules for such situations. If you are very interested in solving this problem and no one else is reporting upstream - take matters in your hands and report 😸

**Comment by mwillsey** [comment]
For what it's worth, this is a super easy way to insert blocks that's built right into org-mode, so no additional config required. Also, it will correctly fontify.

http://orgmode.org/manual/Easy-Templates.html

**Comment by 4goodapp** [comment]
@mwillsey Seems like the link was edited to this one:
https://orgmode.org/manual/Easy-templates.html

**Comment by ambimorph** [comment]
I just had this issue, too, and cutting and pasting worked.

**Comment by theophilusx** [comment]
Running latest spacemacs devel branch with emacs 27.0.

No src block syntax highlighting. Default org layer configuration. 

run Emacs 27 without spacemacs and source block highlighting works fine.

**Comment by duianto** [comment]
This is what I'm seeing.
- `C-x C-f` `~/temp/test.org`
- manually type:
```org
#+BEGIN_SRC c
uint32_t type = 0;
#+END_SRC
```
After typing the last character: `C`
- In `emacs --quick` (Emacs without any configuration), there's no syntax highlighting.
The syntax highlighting can be applied by either:
calling: `M-x org-mode`
or by closing the buffer: `C-x k` `RET`, and reopening it: `C-x C-f` `~/temp/test.org`
- In Spacemacs on the `develop` branch with updated packages.
The `C` is inserted but the evil insert cursor remains before the `C` for two seconds while something loads.
When the cursor moves after the `C`, then the typed text gets syntax highlighted.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 7a7b04abb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git go graphviz haskell helm
            (javascript :variables javascript-backend 'lsp)
            lsp multiple-cursors org
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            shell version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by theophilusx** [comment]
After doing an update of spacemacs and updating the packages, this issue
seems to be resolved. Not sure which fixed the issue as there was an
update of org (org-plus-contrib 9.4) as well as an update of spacemacs
(which reverted a recent change to how user init stuff is loaded). I had
done the same before reporting the issue, so spacemacs and packages
were all up to date.

In my tests, made no difference whether I manually typed in the code
block, used the insert special block template (, i b) or cut and copied
a block. Likewise, no difference with upper or lower case
BEGIN_SRC/END_SRC - all worked fine.

**Comment by dmusican** [comment]
I was having the same problem (no syntax highlighting at all in org mode), and I followed the above advice to update packages. Fixed the problem. Thanks!
