### ISSUE TITLE
Feature Request: Next & Last Object Motion

### ISSUE THREAD

**Issue by bhilburn** [syl20bnr/spacemacs#6353]
This may already exist for emacs, but I haven't been able to find anything on it.

In Vim, there is a snippet from Steve Losh that provides motion for _next_ and _last_ text objects. As an example of how this works:

```
    this_is_some_func(arg1, arg2, arg3);
      ^
      cursor
```

If the cursor was on the character indicated, the user could press `c i n (` and the result would be:

```
    this_is_some_func( );
                      ^
                      cursor
```

Where that command sequence is `change-in-next-(`. So just as you usually have `change-in-(` and `change-around-(`, for example, it understands the concept of `next` and `last` instances of those text objects for motion.

You can see the code that does this here: https://github.com/bhilburn/dotfiles/blob/master/vim/vimrc#L1313

**Comment by TheBB** [comment]
https://github.com/wellle/targets.vim

We should just port this, sounds like what you're asking for and more.

“Just”

**Comment by bhilburn** [comment]
@TheBB - Oh wow, I didn't know that existed. But yes! A port of that would be fantastic. It really is tremendously useful.

**Comment by ninrod** [comment]
behold: https://github.com/noctuid/targets.el. Courtesy of  @noctuid, the master of evil.

But it is not ready yet. (although I'm using it for precisely the case stated by the thread opener and it is working wonderfully already). 

And you don't have to even use `n`.  Just `ci(` will do.

Enjoy.

**Comment by bhilburn** [comment]
@ninrod - Thanks so much for sharing this! It is, indeed, exactly what I was looking for.

Perhaps when it's done it can be pulled into Spacemacs =)

**Comment by ninrod** [comment]
No problem. [Here](https://github.com/ninrod/dotfiles/blob/master/emacs/boot.org#evil-targets)'s how I use it: 

```elisp
(use-package avy
  :ensure t
  :config
  (use-package targets
    :load-path "lisp/ninrod/targets.el"
    :init
    (setq targets-user-text-objects '((pipe "|" nil separator)
                                      (paren "(" ")" pair :more-keys "b")
                                      (bracket "[" "]" pair :more-keys "r")
                                      (curly "{" "}" pair :more-keys "c")))
    :config
    (targets-setup t
                   :inside-key nil
                   :around-key nil
                   :remote-key nil)))
```

this package will be a big hit on the evil community. @noctuid is packing a lot of awesome features in it. stay tuned.
