### ISSUE TITLE
Spacemacs unresponsive after install

### ISSUE THREAD

**Issue by e-matteson** [syl20bnr/spacemacs#6354]
#### Description

I can't (re-)install spacemacs, it becomes unresponsive after I quit and re-open it. I deleted .emacs.d and .spacemacs, tried both develop and master, and it always fails. I tried re-installing in the first place because spacemacs suddenly became unresponsive, so maybe this is a scary issue on my machine that wasn't fixed by a clean install? Is anyone else experiencing this problem?

#### Reproduction guide

- Delete/rename .emacs.d and .spacemacs
- Clone repository
- Start emacs
- Wait for packages to install
- Quit emacs
- Start emacs again

*Observed behaviour:*

After packages are installed, it says SOMETIMES says "1 error(s) detected at startup...", but `*messages*` doesn't contain any obvious error messages. Sometimes it does not report any errors. In either case, after restarting emacs, the `*spacemacs*` buffer loads and then emacs becomes unresponsive. It uses a tiny but non-zero amount of CPU. SIGINT can eventually kill it, but it takes a few minutes.

`emacs -Q` works fine.

*Expected behaviour:*

Not that.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

**Comment by e-matteson** [comment]
Emacs eventually becomes responsive again if I let it sit quietly for a few minutes. After that everything seems to work ok. The long delay is still concerning, but at least emacs is not totally unusable.

**Comment by TheBB** [comment]
Sounds a bit like http://spacemacs.org/doc/FAQ.html#orgheadline14

**Comment by e-matteson** [comment]
Yes, that fixed it! The problem was TRAMP. Sorry folks, thanks for the help.

**Comment by d12frosted** [comment]
Wow. helm#1000. Again. @TheBB 💯
