### ISSUE TITLE
recent which-key update breaks develop

### ISSUE THREAD

**Issue by oldk1331** [syl20bnr/spacemacs#6358]
#### Description :octocat:
New fresh install from develop branch @ 2016 Jun 18,
when started, get following error message:

`Error (use-package): vi-tilde-fringe :init: Wrong type argument: stringp, nil`

The problem is that `which-key-20160617.542` removes calling to
`(which-key--init-buffer)` recently:

https://github.com/justbur/emacs-which-key/commit/9184b1bcbf316e8d619d72ae140efa48c5e6595d

causing `which-key--buffer` at line 364 of `layers/+spacemacs/spacemacs-evil/packages.el`
to be nil.

#### Reproduction guide :beetle:
- Start Emacs
- do nothing

*Observed behaviour:* :eyes: :broken_heart:
At the end of init, get a `*Warnings*` buffer with error message
described above.

*Expected behaviour:* :heart: :smile:
Successfully init.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.50.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 2570a13)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

**Comment by syl20bnr** [comment]
Thank you for the report, should be fixed in develop branch.

**Comment by oldk1331** [comment]
Fixed!
