### ISSUE TITLE
Quit `twig` mode issues error

### ISSUE THREAD

**Issue by bixuanzju** [syl20bnr/spacemacs#6362]
#### Description :octocat:

Quit `twig` mode issues error, not sure this is Spacemacs-related error or the package itself though
#### Reproduction guide :beetle:
- Start Emacs
- Press `SPC a t`
- Quit twig mode by pressing `q`

_Observed behaviour:_ :eyes: :broken_heart:
Minibuffer says: twittering-stop: Wrong number of arguments: setq, 1

_Expected behaviour:_ :heart: :smile:
Quit gracefully
#### System Info :computer:
- OS: darwin
- Emacs: 25.0.95.1
- Spacemacs: 0.105.21
- Spacemacs branch: haskell (rev. 888fbd2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 (markdown :variables markdown-live-preview-engine 'vmd)
 org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control osx colors idris
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell")
 latex
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 ocaml twitter games lua proof-general)
```
#### Backtrace :paw_prints:

```
Debugger entered--Lisp error: (wrong-number-of-arguments setq 1)
  signal(wrong-number-of-arguments (setq 1))
  twittering-stop()
  twittering-unregister-buffer(#<killed buffer>)
  #[(buffer) "\301!?\205\n\302!\207" [buffer buffer-live-p twittering-unregister-buffer] 2](#<killed buffer>)
  mapc(#[(buffer) "\301!?\205\n\302!\207" [buffer buffer-live-p twittering-unregister-buffer] 2] (#<killed buffer>))
  twittering-unregister-killed-buffer()
  twittering-kill-buffer()
  funcall-interactively(twittering-kill-buffer)
  call-interactively(twittering-kill-buffer nil nil)
  command-execute(twittering-kill-buffer)
```

**Comment by TheBB** [comment]
The backtrace shows it's a problem in twittering-mode, and [indeed](https://github.com/hayamiz/twittering-mode/blob/master/twittering-mode.el#L10302).

**Comment by TheBB** [comment]
I PR'd https://github.com/hayamiz/twittering-mode/pull/117

**Comment by bixuanzju** [comment]
@TheBB Wow, that was quick, thx!

**Comment by bixuanzju** [comment]
Fixed upstream
