### ISSUE TITLE
VISUAL mode in Evil mode doesn't work when choosing multi lines with fast speed.

### ISSUE THREAD

**Issue by zhongke** [syl20bnr/spacemacs#6368]
I use Spacemacs in a VISUAL mode in Evil mode.
I try to choose multiple lines a little bit fast. Then the highlighted lines disappeared.
I mean the highlighted color disappeared.

Branch : develop
Version : 0.105.21
OS        : Mac OS X El Captain 10.11.5

**Comment by syl20bnr** [comment]
Not sure to understand what you mean, can you provide a reproduction step with keys ?

**Comment by zhongke** [comment]
Just highlight multiple lines in VIM VISUAL mode with quick speed.
I try to reproduce in my windows, failed.

**Comment by NJBS** [comment]
@zhongke Can you give us the value of `evil-escape-key-sequence`? `SPC h d v evil-escape-key-sequence`

**Comment by zhongke** [comment]
hi, NJBS 
sorry. I forgot that I had configured a key binding for this.
This should not be an issue.


evil-escape-key-sequence is a variable defined in `evil-escape.el'.
Its value is "jj"
Original value was "fd"

Documentation:
Two keys sequence to escape from insert state.

You can customize this variable.
