### ISSUE TITLE
Mode-line is looking strange

### ISSUE THREAD

**Issue by zmaril** [syl20bnr/spacemacs#637]
![screenshot from 2015-02-19 11 39 52](https://cloud.githubusercontent.com/assets/539927/6271028/056d3452-b82c-11e4-825f-69f26f4307fe.png)

I just installed this to play with it and the tab looking things in the mode line are offset somewhat. I'm running debian 8.0. Any ideas what may be going on here?

**Comment by Funnnny** [comment]
You need to change powerline-scale, it's documented in this section:

**Comment by zmaril** [comment]
Great! That fixed it!
