### ISSUE TITLE
Ag "search at" is not right using SPC s p

### ISSUE THREAD

**Issue by casertap** [syl20bnr/spacemacs#6371]
When doing [SPC s p] I was expecting to have ag searching from the current folder I opened emacs from, but it seems that spacemacs is using the first parent git repository as the basis for all search.

This is a problem to me because I have a git repo that contains lots of projects.
When I go in a project and start emacs I want the Ag search to only search from this sub-project.

How do I do that?
Thanks.

**Comment by syl20bnr** [comment]
`SPC s p` is search in project, what you want is `SPC s f`.
Exhaustive info here: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#searching

**Comment by casertap** [comment]
Sorry this is 2 different things: 
```SPC s p``` search in content in files
```SPC s f``` search a file by name

How can I do a search in content in files from the folder I started emacs?
Or how do I change the project root folder?

**Comment by NJBS** [comment]
Both `SPC s p` and `SPC s f` search contents of files.

`SPC s f` will ask you to select a file or directory and will search the contents of all of the file(s) that you've selected.

`SPC s p` will do the same but will act as if the directory you've selected is your current project's root directory.

To search for files by name in your current project you can use `SPC p f`.

To search for files by name in any arbitrary directory first navigate to the directory using `SPC f f` then use `C-c /` to begin searching in that directory and recursively in all subdirectories for a file's name.

**Comment by casertap** [comment]
@NJBS Awesome, I have everything I need with this explonation.
Thanks

**Comment by NJBS** [comment]
Great! :smile: 

If you feel that your issue has been solved, feel free to close this.
