### ISSUE TITLE
Remapping issue when org-habit is present

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#6380]
#### Description :octocat:

Auto-evilication could not remap function in map `org-agenda-mode-map` when `org-habit` module is loaded.
#### Reproduction guide :beetle:
- Add `(add-to-list 'org-modules 'org-habit)` to your `user-config`
- Start emacs

_Observed behaviour:_ :eyes: :broken_heart:
In *message* buffer, you will get a few warnings telling you that some functions were not properly remapped:

> (Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':   - `org-agenda-next-line' originally mapped on `C-n'
> 
> (Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':   - `org-agenda-toggle-time-grid' originally mapped on `G'
> 
> (Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':   - `org-agenda-filter-remove-all' originally mapped on `|'
> 
> (Spacemacs) Warning: Auto-evilication could not remap these functions in map `org-agenda-mode-map':   - `org-agenda-filter-by-tag-refine' originally mapped on `\'

_Expected behaviour:_ :heart: :smile:
No warnings.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: nil (rev. 50d5cdd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
((auto-completion :disabled-for org)
 better-defaults emacs-lisp evil-snipe git github latex bibtex markdown org org-config window-purpose
 (han :variables han-enable-youdao-dict t han-enable-fcitx t han-org-line-spacing 0.2)
 pandoc pdf-tools python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts smex
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking version-control yaml)
```

**Comment by TheBB** [comment]
This isn't necessarily a bug. There will always be mappings that evilification can't fit. I disagree that the expected behaviour should be no warnings.

**Comment by bmag** [comment]
> This isn't necessarily a bug

I'm not sure if clarification is necessary, but I'll clarify anyway just in case: the warnings themselves are not a bug. What may be a bug is that the specified commands lost their bindings, and we may want to explicitly rebind them. Suggestions are welcome.

**Comment by syl20bnr** [comment]
> Auto-evilication

Never saw the typo before :-)

@bmag When the warning is displayed it means that we effectively lose the key binding. One possibility would be to move these lost bindings to `SPC m` prefix.

**Comment by Stebalien** [comment]
This has become a bit of an annoyance given that the `*spacemacs*` buffer now displays warnings by default.

**Comment by d12frosted** [comment]
The warning is converted to message with this commit https://github.com/syl20bnr/spacemacs/commit/4f700556af46dcf4bf927ddfaaab5ce25c24f185

**Comment by Stebalien** [comment]
Thanks!

**Comment by eedahl** [comment]
@syl20bnr That sounds like a good idea. I get a bunch of these warnings too.

**Comment by kain88-de** [comment]
I get these warnings by just enabling agenda or todos in `dotspacemacs-startup-lists`. That is annoying since it takes screen space away to show my agenda.
 I'm using version `Spacemacs v.0.200.5`

**Comment by aulambda** [comment]
I'm having the same issue as @kain88-de, I get warnings if I enable agenda or todos in `dotspacemacs-startup-lists`, is there a way around this? I'm currently just not enabling agenda there, since there is no point, because the messages take up the space.

**Comment by gnohz** [comment]
same here @et2010

**Comment by kain88-de** [comment]
Btw the problem I described above does not appear on the develop branch.

**Comment by fbob** [comment]
Same here.
Any workaround without switching to the dev branch ?
Thanks :)

**Comment by xkpd3** [comment]
Just fyi, because it fits in here. The same happens when mobile-org is loaded:
```
Warnings:
                                - Auto-evilication could not remap these functions in map `org-agenda-mode-map': -
                                  `org-agenda-next-line' originally mapped on `C-n'      
                                - Auto-evilication could not remap these functions in map `org-agenda-mode-map': -
                                  `org-agenda-toggle-time-grid' originally mapped on `G'      
                                - Auto-evilication could not remap these functions in map `org-agenda-mode-map': -
                                  `org-agenda-filter-remove-all' originally mapped on `|'      
```

**Comment by syl20bnr** [comment]
> Same here.
Any workaround without switching to the dev branch ?

There is no clean work-around but a *slightly* clean hack you can try is to set `spacemacs-buffer--warnings` to `nil` in your `user-config` function. But it may also drop other warnings, fortunately enough they should still be logged in `*messages*` buffer.

**Comment by danielkrizian** [comment]
these startup messages are informative at first, but later become noise. 

one way to make them disappear at next startup is:
```elisp
(defun dotspacemacs/user-init ()
  ;; remove startup auto-evilification messages:
  ;; Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
  ;; - ‘org-agenda-next-line’ originally mapped on ‘C-n’
  ;; Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
  ;; - ‘org-agenda-toggle-time-grid’ originally mapped on ‘G’
  ;; Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
  ;; - ‘org-agenda-filter-remove-all’ originally mapped on ‘|’
  ;; Auto-evilification could not remap these functions in map ‘org-agenda-mode-map’:
  ;; - ‘org-agenda-filter-by-tag’ originally mapped on ‘\’
  ;; `org-agenda-next-line' and `org-agenda-toggle-time-grid' are already evilified to other non-conflicting keys.
  ;; `org-agenda-filter-remove-all' and `org-agenda-filter-by-tag' - we will evilify manually, along with other filter-by functions:
  (with-eval-after-load 'org-agenda
    (dolist (key '("f" "C-n" "G" "\\" "|")) (define-key org-agenda-mode-map (kbd key) nil))
    (evil-define-key 'evilified org-agenda-mode-map (kbd "fc") #'org-agenda-filter-by-category)
    (evil-define-key 'evilified org-agenda-mode-map (kbd "fd") #'org-agenda-filter-remove-all)
    (evil-define-key 'evilified org-agenda-mode-map (kbd "fe") #'org-agenda-filter-by-effort)
    (evil-define-key 'evilified org-agenda-mode-map (kbd "fh") #'org-agenda-filter-by-top-headline)
    (evil-define-key 'evilified org-agenda-mode-map (kbd "ft") #'org-agenda-filter-by-tag)
    (evil-define-key 'evilified org-agenda-mode-map (kbd "fx") #'org-agenda-filter-by-regexp)
    )
  )
```

let me know if there is better approach, if reducing the startup noise is the goal.

defining `evilified-state--auto-evilification-verbose` (default non-nil) predicate variable in `evil-evilified-state.el` would be preferable, as user does not have to pollute `dotspacemacs/user-init` and could choose to `evil-define-key` any failed remappings -- after becoming aware of them from messages -- in `user-config` or custom layer config. 
then `(setq evilified-state--auto-evilification-verbose nil)`
