### ISSUE TITLE
persp-mode customize bug.

### ISSUE THREAD

**Issue by qx** [syl20bnr/spacemacs#6382]
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-C C-C` TO SUBMIT>>
```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(persp-save-dir "/Users/ok/Desktop/layouts/"))
```
persp-save-dir can't be changed.
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 52202cc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by d12frosted** [comment]
>  ;; If you edit it by hand, you could mess it up, so be careful.

You should set it in `dotspacemacs/user-config` function in your `.spacemacs` file. But `spacemacs-layouts` exposes variable named `spacemacs-layouts-directory`. So better solution would be to set this variable like this:

```
(defun dotspacemacs/layers ()
  "Configuration Layers declaration."
  (setq-default
   ;; ...
   dotspacemacs-configuration-layers
   '(
     ;; ...
     (spacemacs-layouts :variables
                        spacemacs-layouts-directory "/Users/ok/Desktop/layouts/")
     )
   ;; ...
   ))
```

**Comment by qx** [comment]
Thanks,It works with your code.
