### ISSUE TITLE
Is it possible to activate yasnippet without auto-completion layer?

### ISSUE THREAD

**Issue by istinspring** [syl20bnr/spacemacs#6383]
Auto-completion is a bit laggy for me, so i just disable it. But i still want to use yasnippet, is it possible?

**Comment by TheBB** [comment]
You can exclude the packages you don't want. (That would be company.) Add them to `dotspacemacs-excluded-packages`.

**Comment by istinspring** [comment]
ok, will try.

**Comment by istinspring** [comment]
It work, thank you!

**Comment by TheBB** [comment]
Great. :-)
