### ISSUE TITLE
Support confirm/abort conventions in helm-ag-edit

### ISSUE THREAD

**Issue by toupeira** [syl20bnr/spacemacs#6389]
I've noticed that the buffer opened by `helm-ag-edit` doesn't support the `SPC m c` / `SPC m k` conventions, not sure if this is a bug or an oversight (I'm on latest develop).

**Comment by TheBB** [comment]
Why not both?

**Comment by TheBB** [comment]
Oh actually it's in fundamental-mode, that makes it a bit more challenging to add `SPC m` bindings.
