### ISSUE TITLE
Is "How do I … idiomatically?" out of date?

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#6391]
Going through the current layers for examples on how to handle company backends it seems to me the documented combination of auto-completion and company

``` elisp
(setq yoyo-packages '(some-weird-package))

(when (configuration-layer/layer-usedp 'auto-completion)
  (defun yoyo/init-some-weird-package ()
    (use-package some-weird-package
      ;; Only if company is installed
      :if (configuration-layer/package-usedp 'company)
      ...
```

has been superseded with something along the lines of

``` elisp
(setq yoyo-packages '(some-weird-package :toggle (configuration-layer/package-usedp 'company))

(defun yoyo/init-some-weird-package ()
  (use-package some-weird-package
  ...
```

?

http://spacemacs.org/doc/LAYERS.html#orgheadline26

Edit: Oops, wrong branch. However `develop` docs don't seem to be mentioning `:toggle` either?

https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#setup-auto-completion-for-a-major-mode

**Comment by d12frosted** [comment]
It has been [fixed](https://github.com/syl20bnr/spacemacs/blob/develop/doc/LAYERS.org#how-do-i--idiomatically) on `develop` branch. But to be fair, [develop version of site](http://develop.spacemacs.org/doc/LAYERS.html#how-do-i--idiomatically) is also out of date.

**Comment by syl20bnr** [comment]
I don't see it fixed on develop branch :-(

**Comment by d12frosted** [comment]
Ah. Didn't see the edit. Indeed, toggles are not mentioned.
