### ISSUE TITLE
Flycheck error message UI inconsistent

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#6394]
#### Description :octocat:

Flycheck displays message in GUI popup when point is over error and displays
message in minibuffer when mouse cursor is over error.

It is more consistent to flip the two behaviors.
#### Reproduction guide :beetle:
- Start Emacs
- (Any setup that produces flycheck errors)
- Open test file tmp.py
- Insert text class (invalid syntax)
- Wait for pylint/flycheck to pick up errors
- Move point/mouse over error

_Observed behaviour:_ :eyes: :broken_heart:

Flycheck displays message in GUI popup when point is over error and displays
message in minibuffer when mouse cursor is over error.

_Expected behaviour:_ :heart: :smile:

Flycheck displays message in GUI popup when mouse cursor is over error and displays
message in minibuffer when point is over error.
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 6d5bca7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:

``` elisp
(ivy
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults gtags ibuffer spell-checking syntax-checking semantic typography
 (chrome :variables edit-server-new-frame nil)
 dash
 (shell :variables shell-default-shell 'shell shell-default-term-shell
        (mir/with-executable "/usr/local/bin/fish" "/usr/bin/fish" "/bin/bash" "/bin/sh")
        shell-default-height 50)
 prodigy restclient version-control git csv elm html javascript markdown nginx python ruby shell-scripts sql yaml django mir-magit-annex mir-pass mir-rc mir-rc-qualia mir-rc-grandbell)
```

**Comment by syl20bnr** [comment]
@darkfeline if you open an issue upstream, can you provide the link here so we can track the issue ? Thank you.
