### ISSUE TITLE
SPC : is undefined

### ISSUE THREAD

**Issue by didibus** [syl20bnr/spacemacs#6405]
I installed spacemacs on RHEL 64 bit, and when I try to run SPC : it says that it is undefined.

On my windows machine, it works fine.

Any idea how I can fix this?

**Comment by ynilu** [comment]
What branch are you using?
M-x is bind to `SPC SPC` by default in develop branch

**Comment by didibus** [comment]
It's working now. I think the issue was something with my shell. I was getting an exec-path error on launch, and once I fixed that, the keybind started working again.
