### ISSUE TITLE
 GnuTLS garbage at end of files makes spacemacs uninstallable - "(void-variable -) in page-break-lines.el"

### ISSUE THREAD

**Issue by alexanderkjeldaas** [syl20bnr/spacemacs#6407]
Steps to reproduce:
1. rm -rf ~/.emacs.d ~/.spacemacs
2. git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
3. emacs --debug-init

I then removed `rm ~/.emacs.d/elpa/page-break-lines-20160617.2100/*.elc` to try to get a better stack trace.

```
Debugger entered--Lisp error: (void-variable -)
  eval-buffer(#<buffer  *load*-554555> nil "/Users/me/.emacs.d/elpa/page-break-lines-20160617.2100/page-break-lines.el" nil t)  ; Reading at buffer position 6079
  load-with-code-conversion("/Users/me/.emacs.d/elpa/page-break-lines-20160617.2100/page-break-lines.el" "/Users/alekje/.emacs.d/elpa/page-break-lines-20160617.2100/page-break-lines.el" nil t)
...
```

The end of `page-break-lines.el` contains:

```
...
(provide 'page-break-lines)

;; Local Variables:
;; coding: utf-8
;; byte-compile-warnings: (not cl-functions)
;; checkdoc-minor-mode: t
;; End:

;;; page-break-lines.el ends here
- Peer has closed the GnuTLS connection
```

Of course the `- Peer has closed the GnuTLS connection` is not valid lisp.

**Comment by TheBB** [comment]
We're aware of this, and that's why we provide the `dotspacemacs-elpa-https` variable, for systems with shaky HTTPS connections.

Of course it would be nice if Emacs didn't spew garbage into the files it downloads, but I don't think there's much we can do about it other than report such things upstream.

**Comment by alexanderkjeldaas** [comment]
Would it be possible to wrap an exception handler around loading this, catch this specific issue `(void variable -)`, and specifically point to the solution?

**Comment by TheBB** [comment]
It's possible but I would hate wrapping core functions like that just for this.

**Comment by syl20bnr** [comment]
You may report a bug upstream on Emacs bug tracker. At the Spacemacs level there is little we can do. A FAQ entry with a work around would be great though.
