### ISSUE TITLE
How to override builtin packages with those from ELPA?

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#6408]
Earlier today I was trying to install an [up to date `python.el` from elpa](https://elpa.gnu.org/packages/python.html). First I tried removing the `:location local` from the `packages.el` in the python layer which did not work. After that I also tried adding `:location 'elpa` to no avail. 

After manually installing the package it got deleted, then I set `dotspacemacs-download-packages` to keep it but it was still not loaded.

**Comment by d12frosted** [comment]
I am not sure (can't check it right now), but I believe that you can add `python` to `dotspacemacs-additional-packages` and specify it's location (ELPA recipe). It should override recipe for package from layer. But I am not 100% sure. Just wanted to share possible way of solving your problem.

**Comment by cpaulik** [comment]
Having `(python :location 'elpa)` in `dotspacemacs-additional-packages` did nothing. 

Is there another way to specify that? I was having trouble finding documentation on the available keywords for quelpa (which is what is used behind the scenes right?).

**Comment by d12frosted** [comment]
You should use [MELPA recipe format](
https://github.com/melpa/melpa#recipe-format). But look like it doesn't
support specifying package archive. You could try loading it directly from
python repository.

But if it's not critical for you and you want to avoid blind experiments,
let's wait for someone who knows the topic better than me :D

**Comment by cpaulik** [comment]
I guess this would need a change in the way the packages are loaded. The package is not installed since [configuration-layer//get-uninstalled-packages](https://github.com/syl20bnr/spacemacs/blob/904f7ea6653226823a3164fdfe9fdcfd164c395e/core/core-configuration-layer.el#L1250) will always always find the built-in python package. 

What I do not quite understand yet is why the package is not loaded instead of the built-in one. It is in the `load-path` and from what I know `package.el` and `use-package` should work that out correctly.

**Comment by TheBB** [comment]
Furthermore, why does org work this way but python does not?

**Comment by cpaulik** [comment]
I guess because we are loading org-plus-contrib.

**Comment by TheBB** [comment]
Oh, right.

**Comment by robbyoconnor** [comment]
Are you gonna make a PR @cpaulik ?

**Comment by TheBB** [comment]
I don't think he/we have worked out how to fix it yet?

**Comment by cpaulik** [comment]
Yes, no fix yet. The only thing that I can think of right now is to use the `min-version` keyword of `package-installed-p`. So we could add a `min-version` keyword to the pkg class. I'll try that on the weekend.

**Comment by syl20bnr** [comment]
@cpaulik indeed the min-version is inevitable, it is impossible to replace a built-in package without it.
I can work on it tomorrow if you are OK.

**Comment by cpaulik** [comment]
@syl20bnr I did not have time to try to implement it yet, so I'll be happy if you do it.

**Comment by syl20bnr** [comment]
We can now specify `:min-version` and a version string for package lists, commit https://github.com/syl20bnr/spacemacs/commit/2152f66

**Comment by cpaulik** [comment]
@syl20bnr Thanks. But for me still the built-in python mode is loaded instead of the one in the elpa directory.

### To reproduce
- Add `(python :location elpa :min-version "0.25.2")` to `dotspacemacs-additional-packages`
- Restart - new python mode is installed
- Restart again
- `SPC f J .py`
- `async def test():` is not properly highlighted and pressing RET does not indent correctly
- `SPC h d m` tells me that `python-mode` is defined in the built-in `python.el`

After the first restart that installs the new package everything works though.

**Comment by syl20bnr** [comment]
@cpaulik not sure how we can fix, I guess forcing a reload somewhere on the library should do it.
To be sure, did you try with a vanilla develop branch and `.spacemacs` ? Maybe you have something in your dotifile that forces a load on `python.el` before installing the new one ?

**Comment by syl20bnr** [comment]
note: In the repro steps there are two restarts, but after you wrote that the first restart fixes it, is it the first or second restart ?

**Comment by cpaulik** [comment]
It works after the first restart when the new package is installed. I guess because the new `python.el` is evaluated during installation. Any restart after that does load the built-in `python.el` for me. But I'll try with an empty `.spacemacs` in the evening.

**Comment by syl20bnr** [comment]
Oh ok, I get it, thank you. Can you open an issue with your message above ?

**Comment by cpaulik** [comment]
I tracked it down. The reason was the a private layer that did not use the `:defer` attribute when it should have. Thanks and sorry for the noise.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
