### ISSUE TITLE
ghc-init not called

### ISSUE THREAD

**Issue by pmiddend** [syl20bnr/spacemacs#641]
To use haskell properly, I added
    (setq-default dotspacemacs-configuration-layers '(haskell))
to my ~/.spacemacs. When I open a Haskell file containing an error, I get no feedback about that error. Only after manually executing (ghc-init) in the eval minibuffer after the file has been loaded, I get error feedback (and have M-? available for checking the actual error message).

**Comment by syl20bnr** [comment]
Did you install the cabal packages mentioned in the readme ? https://github.com/syl20bnr/spacemacs/tree/master/contrib/lang/haskell#cabal-packages

**Comment by pmiddend** [comment]
Yes, I installed all necessary packages. As I said, the whole system works fine, I just have to explicitly call (ghc-init) after loading a haskell file.

I see ghc-init in the packages.el file of contrib/lang/haskell, so I'm wondering why this would be necessary.

**Comment by bjarkevad** [comment]
@pmiddend  I'm looking into this issue now, if you've found a solution or anything please report :)

**Comment by fatlazycat** [comment]
Same here.

**Comment by bjarkevad** [comment]
@fatlazycat Fixed in #657 :)

**Comment by fatlazycat** [comment]
Yeah sorry popped up after I posted :) Will track the PR and upgrade.

Thanks

**Comment by bjarkevad** [comment]
@fatlazycat No problem, just wanted to inform you that it has been fixed! :)

**Comment by pmiddend** [comment]
Wow, thanks for fixing it so fast. :)
