### ISSUE TITLE
how to custom emacs state face?

### ISSUE THREAD

**Issue by z-ray** [syl20bnr/spacemacs#6413]
hi, i am starting spacemacs today, my question is how to custom emacs state face? what i want is the color like in normal state.

**Comment by TheBB** [comment]
The face you want to customize is called `spacemacs-emacs-face`. Here is the Emacs lisp manual on faces: https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces.html#Faces

For example

```elisp
(set-face-attribute 'spacemacs-emacs-face nil :background "DarkGoldenrod2")
```

**Comment by z-ray** [comment]
@TheBB Thank you very much, it works!
