### ISSUE TITLE
python3 jedi staticmethod first param complate error

### ISSUE THREAD

**Issue by JinMaiAymazon** [syl20bnr/spacemacs#6415]
I'm sorry, my English is poor.

def A:
----@staticmethod
----def a(param):
--------""":type param: str"""
--------param.    # this pop a(param == cls) and not str.xxx
--------assert isinstance(param, str)
--------param.    # this pop str.xxx

Another problem is how to use the single-line comments for type completion?
x = y['xxx']  # :type: str
is not complate, i test is not work, and:
x = y['xxx']  # type: str  | # @type: str
: (

**Comment by TheBB** [comment]
I don't know if jedi should read type information from docstrings or comments. In any case, the jedi people are more likely to be able to answer you than we are. Please ask there.

**Comment by JinMaiAymazon** [comment]
thank you very much!
