### ISSUE TITLE
"helm-file-smart-do-search" complains "Wrong type argument: stringp, nil"

### ISSUE THREAD

**Issue by AlohaWorld** [syl20bnr/spacemacs#6416]
#### Description

When invoke "helm-file-smart-do-search" with a current unsaved buffer, emacs will complain
"helm-basename: Wrong type argument: stringp, nil"
#### Reproduction guide
- Start Emacs
- M-x list-packages
- M-m s f
  Error messages appear.
#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: cyd (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory
                  (concat
                   (car dotspacemacs-configuration-layer-path)
                   "snippets/")
                  auto-completion-enable-sort-by-usage t)
 better-defaults emacs-lisp git org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking themes-megapack chinese my-commons my-cygwin my-buffer)
```

**Comment by TheBB** [comment]
Can you upgrade your packages and provide a backtrace (`SPC t D`)

**Comment by AlohaWorld** [comment]
Upgraded all the packages.

**System Info**
#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: cyd (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory
                  (concat
                   (car dotspacemacs-configuration-layer-path)
                   "snippets/")
                  auto-completion-enable-sort-by-usage t)
 better-defaults emacs-lisp git org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking themes-megapack chinese my-commons my-cygwin my-buffer my-org)
```


**Backtrace**
`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  directory-file-name(nil)
  helm-basename(nil)
  (if helm-ff-transformer-show-only-basename (helm-basename preselection) preselection)
  (helm-read-file-name "Search in file(s): " :marked-candidates t :preselect (if helm-ff-transformer-show-only-basename (helm-basename preselection) preselection))
  (if targs targs (helm-read-file-name "Search in file(s): " :marked-candidates t :preselect (if helm-ff-transformer-show-only-basename (helm-basename preselection) preselection)))
  (let ((targets (if targs targs (helm-read-file-name "Search in file(s): " :marked-candidates t :preselect (if helm-ff-transformer-show-only-basename (helm-basename preselection) preselection))))) (helm-do-grep-1 targets nil nil nil nil use-region-or-symbol-p))
  (let ((preselection (or (dired-get-filename nil t) (buffer-file-name (current-buffer))))) (let ((targets (if targs targs (helm-read-file-name "Search in file(s): " :marked-candidates t :preselect (if helm-ff-transformer-show-only-basename (helm-basename preselection) preselection))))) (helm-do-grep-1 targets nil nil nil nil use-region-or-symbol-p)))
  (progn (fset (quote helm-do-grep-1) vnew) (let ((preselection (or (dired-get-filename nil t) (buffer-file-name (current-buffer))))) (let ((targets (if targs targs (helm-read-file-name "Search in file(s): " :marked-candidates t :preselect (if helm-ff-transformer-show-only-basename ... preselection))))) (helm-do-grep-1 targets nil nil nil nil use-region-or-symbol-p))))
  (unwind-protect (progn (fset (quote helm-do-grep-1) vnew) (let ((preselection (or (dired-get-filename nil t) (buffer-file-name (current-buffer))))) (let ((targets (if targs targs (helm-read-file-name "Search in file(s): " :marked-candidates t :preselect ...)))) (helm-do-grep-1 targets nil nil nil nil use-region-or-symbol-p)))) (fset (quote helm-do-grep-1) old))
  (let* ((vnew (function (lambda (targets &optional recurse zgrep exts default-input region-or-symbol-p) (let* ((new-input ...) (quoted-input ...)) (this-fn targets recurse zgrep exts default-input quoted-input))))) (old (symbol-function (quote helm-do-grep-1)))) (unwind-protect (progn (fset (quote helm-do-grep-1) vnew) (let ((preselection (or (dired-get-filename nil t) (buffer-file-name ...)))) (let ((targets (if targs targs ...))) (helm-do-grep-1 targets nil nil nil nil use-region-or-symbol-p)))) (fset (quote helm-do-grep-1) old)))
  (progn (fset (quote this-fn) vnew) (let* ((vnew (function (lambda (targets &optional recurse zgrep exts default-input region-or-symbol-p) (let* (... ...) (this-fn targets recurse zgrep exts default-input quoted-input))))) (old (symbol-function (quote helm-do-grep-1)))) (unwind-protect (progn (fset (quote helm-do-grep-1) vnew) (let ((preselection (or ... ...))) (let ((targets ...)) (helm-do-grep-1 targets nil nil nil nil use-region-or-symbol-p)))) (fset (quote helm-do-grep-1) old))))
  (unwind-protect (progn (fset (quote this-fn) vnew) (let* ((vnew (function (lambda (targets &optional recurse zgrep exts default-input region-or-symbol-p) (let* ... ...)))) (old (symbol-function (quote helm-do-grep-1)))) (unwind-protect (progn (fset (quote helm-do-grep-1) vnew) (let ((preselection ...)) (let (...) (helm-do-grep-1 targets nil nil nil nil use-region-or-symbol-p)))) (fset (quote helm-do-grep-1) old)))) (fset (quote this-fn) old))
  (let* ((vnew (symbol-function (quote helm-do-grep-1))) (old (symbol-function (quote this-fn)))) (unwind-protect (progn (fset (quote this-fn) vnew) (let* ((vnew (function (lambda ... ...))) (old (symbol-function (quote helm-do-grep-1)))) (unwind-protect (progn (fset (quote helm-do-grep-1) vnew) (let (...) (let ... ...))) (fset (quote helm-do-grep-1) old)))) (fset (quote this-fn) old)))
  spacemacs//helm-do-grep-region-or-symbol(nil nil)
  spacemacs/helm-files-do-grep()
  call-interactively(spacemacs/helm-files-do-grep)
  spacemacs/helm-files-smart-do-search()
  call-interactively(spacemacs/helm-files-smart-do-search nil nil)
  command-execute(spacemacs/helm-files-smart-do-search)`

**Comment by syl20bnr** [comment]
Weird I cannot reproduce it using both develop and master branches and same version of Emacs 24.5.1.
Helm opens in the root folder.
You can ultimately wipe out you elpa directory and restart to see if fixes the bug.

**Comment by duianto** [comment]
Confirmed, the message: `helm-basename: Wrong type argument: stringp, nil`, appears when trying to call `spacemacs/helm-files-smart-do-search`, by pressing `SPC s f`, in a buffer that's not visiting a file, for example: `*scratch*`.

The command works from a buffer that is visiting a file, because the HELM File Completions buffer opens when `SPC s f` is pressed in `.spacemacs`.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 177da959)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey markdown html ranger emacs-lisp git github helm org syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by Miciah** [comment]
Note: I could not reproduce the issue until I deleted `"rg"` from `dotspacemacs-search-tools`.

**Comment by hh** [comment]
I'm still getting issues on this one, but only on windows boxes.

**Comment by duianto** [comment]
@hh It's working for me on the `develop` branch in Windows 1903.

Could you post your system information. Press `SPC h d s` to copy it to your clipboard.

If your on the `master` branch, then you might want to switch to the `develop` branch. It's the recommended branch until the next version is released (I have no insight into when that will happen).

#### To try the `develop` branch:
Backup your current setup, then make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f578e618a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git github helm imenu-list
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org
            (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>
