### ISSUE TITLE
Use system-configuration-features in spacemacs/report-issue with Emacs version > 25.1

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#6420]
Emacs  25.1 has `system-configuration-features` variable:  
>  New variable 'system-configuration-features', listing some of the
main features that Emacs was compiled with.  This is mainly intended
for use in Emacs bug reports.

Might be useful with Spacemacs troubleshooting.  Should we add its content to the ` spacemacs/report-issue` report ?

**Comment by d12frosted** [comment]
For some issues that might be useful.

**Comment by JAremko** [comment]
Fixed in #6994
