### ISSUE TITLE
on micro-state exit, last per-binding doc remains visible

### ISSUE THREAD

**Issue by dwang20151005** [syl20bnr/spacemacs#6423]
#### Description :octocat:

In a micro-state, if a binding has both :exit t and :doc not-nil, then the lv
window with the doc stays visible after I've exited the micro-state. I don't
know how to close it except by calling (lv-delete-window) manually.

I think this is because set-transient-map calls exit-pred before it executes the
keybinding. We close the lv window via the exit-pred, but then after that we
show the per-binding documentation in the bound function.

I don't know how to fix this or even what the desired behavior would be.
#### Reproduction guide :beetle:

cat - > /tmp/test.el <<EOF
(spacemacs|define-micro-state test
  :doc "[a] a [b] b [q] quit"
  :bindings
  ("q" nil :doc "quit" :exit t))

(spacemacs/test-micro-state)
EOF
emacs --debug-init --load /tmp/test.el

Type q.

_Observed behaviour:_ :eyes: :broken_heart:
The lv window stays until I manually call (lv-delete-window).

(There is a second error also, about stringp 1, but I have submitted PR #6422 .)

_Expected behaviour:_ :heart: :smile:
The ideal behavior would be for the lv window to go away on its own.

Alternatively, I would also be happy if I could get an error when I defined a
micro-state with a binding that had :exit t and :doc not-nil.

Minimally, I'd like to be warned about this in the docstring of
spacemacs|define-micro-state.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.3
- Spacemacs: 0.105.21
- Spacemacs branch: nil (rev. 07829f8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-help-tooltip t)
 edit-server org
 (shell :variables shell-default-shell 'eshell shell-default-height 50 shell-default-position 'bottom))
```

**Comment by TheBB** [comment]
Is this reproducible on develop with `spacemacs|define-transient-state`? Microstates are deprecated.

**Comment by d12frosted** [comment]
Lol. I live in previous century.

**Comment by dwang20151005** [comment]
Well, `spacemacs|define-transient-state` documents the behavior, so I guess that
resolves my issue.

Is there documentation yet on transient states? I don't know how to convert my
micro-states. When I try the naive thing

    (spacemacs|define-transient-state test
      :doc "[a] a [b] b [q] quit"
      :bindings
      ("a" nil "a")
      ("b" nil "b")
      ("q" nil "quit" :exit t))

I see the new functions `spacemacs/test-transient-state/nil` and
`spacemacs/test-transient-state/body`. The first echos the name of the second.
The second shows me something that looks like a micro-state, but when I type "a"
the help text vanishes even though "a" is not bound with `:exit t`.

Would it be possible provide a compatibility layer that wraps the micro-states
interface around the transient-states implementation? I don't mean to sound
ungrateful, because spacemacs is great. It's just that maintaining my emacs
config is starting to take more time than I expected.  Sorry, I'm frustrated.

**Comment by syl20bnr** [comment]
Pressing `a` exists because you put nil as the bound code to execute, try with:

 ```elisp
(spacemacs|define-transient-state test
  :doc "[a] a [b] b [q] quit"
  :bindings
  ("a" (message "a") "a")
  ("b" (message "b") "b")
  ("q" (message "q") "quit" :exit t))
```
