### ISSUE TITLE
Leuven theme error "list: Symbol's value as variable is void: diff-refine-added"

### ISSUE THREAD

**Issue by aeberts** [syl20bnr/spacemacs#6426]
#### Description
Leuven theme is not enabled on `SPC T h leuven` and gives error:
`list: Symbol's value as variable is void: diff-refine-added`

#### Reproduction guide
- Start Emacs GUI
- Update Packages by clicking "Update Packages" from Spacemacs buffer
- Update Spacemacs by click "Update Spacemacs" from Spacemacs buffer 
- Type `SPC T h leuven`  
-> Leuven theme is not activated and `list: Symbol's value as variable is void: diff-refine-added` appears in *Messages* buffer.

*Observed behaviour:*
- The leuven theme is not applied. 

*Expected behaviour:*
- The leuven theme is applied.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(html auto-completion better-defaults emacs-lisp org git markdown clojure erc ess spell-checking syntax-checking version-control themes-megapack)

```
#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by NJBS** [comment]
Do you still experience this issue on the latest Spacemacs release?

**Comment by aeberts** [comment]
This issue appears to be fixed on my configuration:

```GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G31)) of 2016-09-20```

with the latest spacemacs release ( 0.200.2 )

**Comment by TheBB** [comment]
Closing, then.
