### ISSUE TITLE
Where are the customizable ein:notebook-* variables when using Ein with the ipython-notebook layer?

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#6427]
When I do `M-x customize-variable RET ein:` I get an empty list. Am I overlooking something?

**Comment by bmag** [comment]
Hey, can you provide a detailed reproduction recipe? It is possible that due to lazy-loading, the customizable variables aren't available until Ein is actually loaded.

**Comment by 3rd3** [comment]
I didn't know that. That was the problem. Thanks.
