### ISSUE TITLE
[auctex] C-` is undefined

### ISSUE THREAD

**Issue by rakyi** [syl20bnr/spacemacs#643]
In auctex layer after pressing <kbd>S m b</kbd> ( `auctex/build-view`) message "Errors! Check with C-\`"  is displayed if errors are encountered, but C-\` is undefined.

**Comment by pluskid** [comment]
+1

**Comment by TheBB** [comment]
Hi guys. This issue is several months old, I can't reproduce it (it says `C-c \`` which works fine for me), and probably a lot of things have changed about this layer since this was reported. I'm going to close this for these reasons and if you find it still happens, please feel free to reopen.
