### ISSUE TITLE
Typing `fd` really quickly acts like escape.

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#6430]
#### Description :octocat:

Hitting `f` then `d` in quick succession closes prompts/exits insert mode.

#### Reproduction guide :beetle:
- Start Emacs
- Open a prompt (e.g., `SPC SPC`).
- Hit `f` then `d` really quickly (practically at the same time but make sure to
  hit `f` first).

*Observed behaviour:* :eyes: :broken_heart:

The prompt closes. No error messages.

*Expected behaviour:* :heart: :smile:

"fd" 😕

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. a713189)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm better-defaults git
      (auto-completion :variables auto-completion-return-key-behavior nil)
      org spell-checking syntax-checking
      (shell :variables shell-default-shell 'ansi-term)
      emoji emacs-lisp markdown latex bibtex csv yaml c-c   html haskell go javascript python systemd
      (rust :variables rust-format-on-save nil))
```

**Comment by Stebalien** [comment]
"Not a bug"... (why would anyone want this?).

**Comment by jb55** [comment]
> why would anyone want this
This was my initial reaction as well, but over time I realized how amazing it is, it's so much faster than ESC. Only downside is I try to do it in vim all the time now :(

**Comment by Stebalien** [comment]
At the time, I was trying to submit an upstream bug report using `report-emacs-bug`. Part of my subject contained the string "asdf" (filler text). Unfortunately, I was typing "asdf" too fast and, on my keyboard, if a set of keys are hit at approximately the same time the events are received right to left. This meant my bug report kept on getting aborted halfway through typing the subject...

**Comment by punitsoni** [comment]
I just encountered this. While typing in spacemacs evil insert mode, typing letters "fd" fast, would cause emacs to get out of insert mode without typing anything in buffer. How is this a feature?

Isn't this clearly a bug?

This causes lot of problems when you are a fast typer and need to type "fd" many times. (Especially for C/C++ file descriptors)

**Comment by swaroopch** [comment]
@punitsoni You can customize it to something else - http://spacemacs.org/doc/VIMUSERS.html#changing-the-escape-key
