### ISSUE TITLE
Spacemacs freezes (unresponsive, 100% CPU) when editing a Haskell file

### ISSUE THREAD

**Issue by kvelicka** [syl20bnr/spacemacs#6433]
#### Description
Spacemacs freezes (unresponsive, 100% CPU) when editing a particular Haskell file:
https://gist.github.com/kvelicka/217ae60620acec3990c448dfa8299c32

Note that the string literal on line 6 is missing the trailing double quote character. If this character is put back, the freeze no longer occurs.

#### Reproduction guide
- Start Emacs
- Open the above-mentined gist as a file with spacemacs
- Go to line 8
- (at least in vi mode) press shift-o, i.e. insert a line above the current one

*Observed behaviour:*
Emacs freezes - becomes completely unresponsive and (presumably) goes into an infinite loop as CPU usage goes to 100% (of one core) and stays there seemingly indefinitely.

*Expected behaviour:*
A new line above the current one is inserted, the editor goes into INSERT mode with the cursor placed at the start of this new line.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp
 (latex :variables latex-enable-auto-fill nil)
 markdown org
 (haskell :variables haskell-enable-ghc-mod-support nil)
 c-c  )
```

**Comment by bixuanzju** [comment]
I can confirm this. Might related to haskell-mode, because you miss close `"` on line 6?

**Comment by kvelicka** [comment]
Yes, that is the case (I mentioned it in the OP) - the closing `"` fixes the issue. I suspect this may be related to syntax highlighting specifically, since even before triggering the freeze one can observe that all lines below 6 are coloured as if they were no longer part of the string.  

Just guesswork from here on, but this might have been caused by the original implementor's assumption that Haskell literal strings can only be single-line, which is not the case (just tested with ghc-7.10.3):  
https://mail.haskell.org/pipermail/haskell-cafe/2006-January/013911.html

**Comment by kvelicka** [comment]
Confirmed as a haskell-mode bug. Closing this.
