### ISSUE TITLE
4 minutes long freezes on startup when connected to a Connectify access point

### ISSUE THREAD

**Issue by tuxayo** [syl20bnr/spacemacs#6434]
#### Description
- When connected directly
  - when no packages to install, after launching Spacemacs, after few keystrokes
    (if I never stop typing during more than a second, it's fine...) it freezes.
    That freeze can't be Ctrl-C nor Ctrl-\, I have to `killall emacs` or wait 4
    minutes for the editor to be usable.
    - When using --insecure, Wireshark shoes that Emacs is trying to do HTTPS
      anyway (should be related to #5698 ) And I see that the TLS connections are
      to the gateway (private local address), that must be related to how
      Connectify makes it's hotspot and explain the different behavior when using
      the phone a an intermediary (because it adds a NAT that uses a similar IP addresses range)
  - Installing some packages will trigger this freeze (I haven't waited enough
    to see if this one ends and that the install can continue)
- When connected using a phone as an intermediary (Android sharing by USB with a Linux PC)
  - when no packages to install, It's usable
  - can't install some packages, freeze during startup (when it tries to install), that freeze can be
    Ctrl-C from the terminal that ran Emacs

All of this happens on a fresh install with a new .spacemacs

#### Reproduction guide
All of this happens on a fresh install with a new .spacemacs

- Connect to an access poing managed by the horrible Connectify Hotspot software. All I know about the access point is that it's done with the same network adapter to connect to the internet and make the hotspot. That might imply some networking black magic that triggers this issue.
- Install spacemacs

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git org spell-checking syntax-checking haskell python javascript c-c  )
```

**Comment by TheBB** [comment]
http://spacemacs.org/doc/FAQ.html#orgheadline14

**Comment by tuxayo** [comment]
First workaround worked, thanks! :-D

> The root cause is probably your ISP redirecting non-existing addresses to their own servers. 

Yep, random non existing domains are resolved to the same IP address. I hope I'll will never have to deal with Connectify again...
