### ISSUE TITLE
Should we change the placement of neotree and imenu-list windows?

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#6438]
Right now, neotree opens on the left and imenu-list (from `imenu-list` layer) opens on the right, so when they're both open, the frame looks like this: ("NT" means neotree, "IL" means imenu-list)
```
+-------+----------------+-------+
|       |                |       |
|       |                |       |
|       |                |       |
|  NT   |    File        |  IL   |
|       |                |       |
|       |                |       |
|       |                |       |
+-------+----------------+-------+
```
I want to change the placement so imenu-list also opens on the left, and when both neotree and imenu-list are open then neotree will be above imenu-list, like this:
```
+----------+-------------+-------+
|          |                     |
|    NT    |                     |
|          |                     |
+----------+        File         |
|          |                     |
|    IL    |                     |
|          |                     |
+----------+-------------+-------+
```
Do you (the people around here) think this is a good/bad idea, or have any suggestions?

**Comment by syl20bnr** [comment]
Would be cool if you can tweak if for 0.200, if you need `emacs-purpose` then we can wait for after 0.200 is released, the next version will focus on window placement to provide a sane default and an easy way for users to tweak it.

**Comment by nixmaniack** [comment]
It's nice to have option but should be customizable to keep the current behaviour. If I don't have much screen height I wouldn't like them to be combined.

**Comment by bmag** [comment]
> if you need `emacs-purpose`

I probably don't need it for this. My current approach is to use `display-buffer-in-side-window`, but it seems to have some impact in unexpected places.

> should be customizable to keep the current behaviour

No problem, I'll keep that in mind.

**Comment by ikhthiandor** [comment]
I would like the previous way. That's just me though.

**Comment by bmag** [comment]
I'm giving up on this idea for now. The proper way to implement what I wanted is to display imenu-list and neotree as "side windows": a window is a "side window" if it has non-nil `window-side` and `window-slot` window parameters. Side windows are easy to create with `display-buffer-in-side-window`. It isn't hard to create side windows, but I encountered some surprising integration issues with other features.

First, changing workspaces (and layouts?) erases the "side window" status of the side windows, so they become regular windows. This can be fixed by changing the value of `window-persistent-parameters`. Second, the `SPC w H/J/K/L` commands (`evil-window-move-far-*`) mess up the layout, because they don't handle side windows correctly. This isn't easily fixed.

Of course we could display neotree and imenu-list on the same side without making them proper side windows, but I don't want to abuse the window system (it's already abused too much as it is).

All in all, I felt that the effort required to make the change is too big and the gain just isn't worth the effort. Besides, I'm afraid that tweaking the window display configuration will bite us in the future if we do it in bits-and-pieces throughout the code base. I might give it another shot in the future, but configuring the Emacs window system *correctly* is very hard :dizzy_face:
