### ISSUE TITLE
Mouse clic on margin with line numbering and semantic-stickyfunc enabled doesn't jump to the desired line

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#6440]
#### Description :octocat:

Mouse clic on margin with line numbering and semantic-stickyfunc enabled doesn't jump to the desired line.
#### Reproduction guide :beetle:
- Start Emacs with initial spacemacs configuration
- enable semantic layer
- enable semantic-stickyfunc `SPC T S`
- enable line-numbers with `SPC t n`
- clic on a line in the margin

_Observed behaviour:_ :eyes: :broken_heart:
Jump to the line under the desired line

_Expected behaviour:_ :heart: :smile:
Jump to the desired line
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 1a13cba)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm emacs-lisp semantic)
```

**Comment by bmag** [comment]
Can you perform these two actions and paste the output of each action?
1. `C-h c <mouse click on margin>`
2. `SPC h d k <mouse click on margin>`

When I perform the first step, I see this message:
```
<left-margin> <down-mouse-1> (translated from <down-mouse-1>) at that spot runs the command spacemacs/md-select-linum
```

When I perform the second step, I see a help buffer beginning with the same message and followed by documentation about the command.

**Comment by wutsdat** [comment]
1. 
```
<left-margin> <down-mouse-1> (translated from <down-mouse-1>) at that spot runs the command spacemacs/md-select-linum
```

2.
```
<left-margin> <down-mouse-1> (translated from <down-mouse-1>) at that spot runs
the command spacemacs/md-select-linum, which is an interactive Lisp function in
`funcs.el'.

It is bound to <left-margin> <down-mouse-1>.

(spacemacs/md-select-linum EVENT)

Set point as spacemacs-linum-mdown-line

----------------- up-event ----------------

<mouse-1> at that spot runs the command mouse-set-point, which is an interactive
compiled Lisp function in `mouse.el'.

It is bound to <triple-mouse-1>, <double-mouse-1>, <mouse-1>.

(mouse-set-point EVENT)

Move point to the position clicked on with the mouse.
This should be bound to a mouse click event type.
```

**Comment by bmag** [comment]
I'm not able to reproduce the bug in latest develop with my setup. If you're up to it, you can try debugging the problem by going to the definition of `spacemacs/md-select-linum` in `layers/+distributions/spacemacs-base/funcs.el` and running the command `edebug-defun` (the cursor should be inside the defun). Next time you click the margin, emacs should take you into a debugging state. You should change to emacs-state (`C-z`) and press `?` to view edebug's help.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 237d114)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.5 auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip t company-tooltip-align-annotations t)
 emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 markdown org
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control
 (latex :variables latex-enable-auto-fill t latex-enable-folding t)
 pdf-tools evil-cleverparens python command-log smex themes-megapack c-c++
 (clojure :variables clojure-enable-fancify-symbols nil)
 ruby common-lisp ibuffer octave imenu-list semantic window-purpose nameless
 (theming :variables theming-modifications
          '((spacemacs-dark
             (aw-leading-char-face :foreground "red" :height 3.0))
            (spacemacs-light
             (aw-leading-char-face :foreground "red" :height 3.0))
            (monokai
             (aw-leading-char-face :foreground "red" :height 3.0))
            (flatland
             (aw-leading-char-face :foreground "red" :height 3.0)))))
```
