### ISSUE TITLE
Unicode replacement cannot be repeated via `.`

### ISSUE THREAD

**Issue by menelaos** [syl20bnr/spacemacs#6442]
#### Description

There's a slight difference to Vim's behaviour when it comes to repeating the replacement of a character with a unicode character entered via `C-v NNNN`.
#### Reproduction guide
- Start Vim/Spacemacs
- Use the following snippet:

```
a
a
```
- Place cursor on the first `a`
- Vim: `r C-v u 2200`
- Spacemacs: `r C-v 2200 RET`
  (This assumes that you have set `read-quoted-char-radix` to `16`)
- (Try to) repeat action by presssing `.` on second `a`

_Observed behaviour in Spacemacs:_

```
∀
<empty line>
<empty line>
```

_Expected behaviour (and observed in Vim):_

```
∀
∀
```
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp markdown)
```

**Comment by syl20bnr** [comment]
Thank you for the detailed report. I was able to reproduce it with `SPC q D evil RET` (which restart emacs with just `evil` package).
Can you report the bug upstream and post a link to track the issue here ?

evil repo: https://bitbucket.org/lyro/evil/wiki/Home

**Comment by menelaos** [comment]
Thanks for the quick response. I've filed an issue upstream: https://bitbucket.org/lyro/evil/issues/681/unicode-replacement-cannot-be-repeated-via
