### ISSUE TITLE
Spaceline distorted display

### ISSUE THREAD

**Issue by jinks** [syl20bnr/spacemacs#6445]
This is on a pristine install of Spacemacs (git clone 5 minutes ago). OS is Arch Linux, so usually as close to upstream as reasonably possible.

In the active window the Spaceline doubles in height and looks really distorted.
Screenshot:
![Spaceline](http://i.imgur.com/UOp7dfn.png)

I'm relatively inexperienced with the Emacs ecosystem, so I can't really tell if this is caused by Spaceline, Spacemacs' config options for Spaceline or something else entirely (font problems? xft?).
I'm not sure what to look for to fix this, so I'm grateful for any advice. Considering the lack of similar reported issues I'm quite sure the problem is on my end.

**Comment by NJBS** [comment]
This is likely an issue with your font, can you try installing source code pro or another good unicode fallback font. If that doesn't work you can also try setting `dotspacemacs-mode-line-unicode-symbols` to `nil`.

Duplicate of https://github.com/syl20bnr/spacemacs/issues/1012

**Comment by jinks** [comment]
Messing with fonts did "something"...

I'm still off by one pixel, but that's not as jarring as before (and also happening without Unicode symbols). I haven't restarted X yet, so that might also just be a caching issue.

Fonts and X are black magic.
