### ISSUE TITLE
csv-mode does not show field index

### ISSUE THREAD

**Issue by spuelrich** [syl20bnr/spacemacs#6446]
#### Description :octocat:
csv-mode does not show field index

#### Reproduction guide :beetle:
- fresh clone of .spacemacs
- checkout origin/develop
- Start Emacs
- add "csv" to dotspacemacs-configuration-layers
- restart Emacs
- check variable csv-field-index-mode using "F1 v csv-field-index-mode"
  """Its value is t"""
- open a CSV file

*Observed behaviour:* :eyes: :broken_heart:
In the modeline there is no csv field index shown.

*Expected behaviour:* :heart: :smile:
In the modeline the CSV field index should be visible.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.0.93.1
- Spacemacs: 0.105.21
- Spacemacs branch: nil (rev. 237d114)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp csv)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
You should report this to spaceline. Thanks!

https://github.com/TheBB/spaceline

**Comment by spuelrich** [comment]
reported issue to spaceline:
https://github.com/TheBB/spaceline/issues/92
