### ISSUE TITLE
Centered buffers interact poorly with multiple frames

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#6450]
#### Description :octocat:

Centered buffer mode does very odd things indeed when multiple frames are used.

I've described an example reproduction below, but it seems to be kind of iffy.
Switching back and forth between multiple frames and toggling centered buffer
mode should make the incorrect behavior obvious.

In particular, once you have triggered this, it seems to be impossible to disable centered buffer mode in all frames including minibuffers without restarting Emacs.

#### Reproduction guide :beetle:
- Start Emacs
- Create a new frame (e.g., `M-x make-frame-command`)
- `SPC w c` -> Both frames (including minibuffer) are centered
- Switch to other frame
- `SPC w c`

*Observed behaviour:* :eyes: :broken_heart:

Only current frame is uncentered.

*Expected behaviour:* :heart: :smile:

Both frames are uncentered?

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 237d114)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-enable-sort-by-usage t)
 better-defaults gtags ibuffer spell-checking syntax-checking semantic typography
 (chrome :variables edit-server-new-frame nil)
 dash
 (shell :variables shell-default-shell 'shell shell-default-term-shell
        (mir/with-executable "/usr/local/bin/fish" "/usr/bin/fish" "/bin/bash" "/bin/sh")
        shell-default-height 50)
 prodigy restclient version-control git csv elm html javascript markdown nginx python ruby shell-scripts sql yaml django mir-magit-annex mir-pass mir-rc mir-rc-qualia mir-rc-grandbell)
```

**Comment by deb0ch** [comment]
Autumnal cleanup: Status on this ? As there was a lot of activity recently around centered-buffer-mode, can you still reproduce ?

@JAremko does it ring a bell ?

Let us know so we can close this or not.

**Comment by JAremko** [comment]
@deb0ch  Nope. This is the old `centering-buffer-mode` [the new one was added in July](https://github.com/syl20bnr/spacemacs/commits/develop/layers/%2Bdistributions/spacemacs-base/local/centered-buffer-mode/centered-buffer-mode.el)  Also I  can't reproduce.

**Comment by darkfeline** [comment]
I'll take your word for it, I don't use centering myself.
