### ISSUE TITLE
How to add marmalade repo to spacemacs

### ISSUE THREAD

**Issue by liuxueyang** [syl20bnr/spacemacs#6455]
I want to install this package `https://github.com/daimrod/highlight-sexp` and is in the marmalade-repo.org, how to add this to package-archives in spacemacs?

Or is there another way to install the package in a better way?

**Comment by bixuanzju** [comment]
If you just want to try out this package, consider adding this package in `dotspacemacs-additional-packages` in your `.spacemacs` as follows

```elisp
dotspacemacs-additional-packages '((highlight-sexp :location (recipe :fetcher github :repo "daimrod/highlight-sexp")))
```

 For valid package specifications, refer http://spacemacs.org/doc/LAYERS.html#orgheadline11

**Comment by liuxueyang** [comment]
@bixuanzju  But it does not work may be because of my network?
