### ISSUE TITLE
Anchor links doenst work in Documentation 

### ISSUE THREAD

**Issue by stef264** [syl20bnr/spacemacs#6458]
https://github.com/syl20bnr/spacemacs/blob/master/doc/

**Comment by d12frosted** [comment]
If you mean links in the table of content - it's fixed in develop branch. For example, see [Conventions](https://github.com/syl20bnr/spacemacs/blob/develop/doc/CONVENTIONS.org).

**Comment by stef264** [comment]
Oh, nice. Thanks!

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
