### ISSUE TITLE
Helm Ag not opening multiple marked files

### ISSUE THREAD

**Issue by deep-spaced** [syl20bnr/spacemacs#6460]
#### Description

Helm Ag (using ag) does not open multiple files in the project search pane (`SPC /` or `SPC s p`) when multiple are marked. Only the file under the cursor is opened.

When using project find or file find (`SPC p f` or `SPC f f`) this works as expected. 
#### Reproduction guide
- Start Emacs
- Open a project.
- Search for something with `SPC /` or `SPC s p`
- Mark several files with `Ctrl+SPC`
- Press RET

_Observed behaviour:_
Only the file under the cursor in the search results is opened in a buffer.

_Expected behaviour:_
All selected file should open in buffers.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp
                 (git :variables git-magit-status-fullscreen t)
                 markdown org
                 (shell :variables shell-default-shell 'ansi-term)
                 osx
                 (ruby :variables ruby-version-manager 'rbenv ruby-test-runner 'rspec)
                 ruby-on-rails yaml elixir html php
                 (version-control :variables version-control-diff-tool 'diff-hl))
```

**Comment by bridgesense** [comment]
I'm new to Helm-ag.  Is there any way around this or is it normal to repeat the same search for each of the files I want to open?  I've migrated over to emacs from VIM for a stint, but bugs like this are pretty painful.

**Comment by cimocimocimo** [comment]
I'm also having this issue.

**Comment by agzam** [comment]
I can confirm - I was able to reproduce

**Comment by Miciah** [comment]
Upstream issue: https://github.com/syohex/emacs-helm-ag/issues/295.

**Comment by upbqdn** [comment]
This would be so useful to have. Can we reopen the issue?
