### ISSUE TITLE
elixir smart parens not working for do ... end

### ISSUE THREAD

**Issue by ankhers** [syl20bnr/spacemacs#6465]
#### Description :octocat:
On `develop` branch, I do not get `do ... end` completion in elixir-mode
#### Reproduction guide :beetle:
- With the elixir layer enabled
- Start Emacs
- open a buffer in elixir mode
- Type the following
``` elixir
defmodule Foo doRET
```

*Observed behaviour:* :eyes: :broken_heart:
I go to a new line, indented, but no `end` appears. I also get a message in the
mini-buffer stating "mismatched parentheses"

*Expected behaviour:* :heart: :smile:
I go to a new line, indented, but with the `end` keyword below my current line

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 237d114)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp erlang elixir html javascript markdown racket ruby rust sql yaml ruby-on-rails auto-completion better-defaults git github org colors restclient dash erc dockerfile spell-checking syntax-checking nixos intero)
```

**Comment by rgrinberg** [comment]
Can you still reproduce this in develop? I'm unable to do so.

**Comment by ankhers** [comment]
No, this seems to be working for me now. Though, I am still getting the "mismatched parentheses" message. Though, that must be an unrelated issue.
