### ISSUE TITLE
Some features hang with font ligatures

### ISSUE THREAD

**Issue by tobia** [syl20bnr/spacemacs#6468]
#### Description

Some features stop responding when some font ligatures are enabled on Mac OS X with:

```
(set-char-table-range composition-function-table ...)
```
#### Reproduction guide
- Set your font to [Fira Code](https://github.com/tonsky/FiraCode)
- Copy the settings found here: https://github.com/tonsky/FiraCode/wiki/Setting-up-Emacs
- Restart Emacs
- Verify that these combinations of character are replaced with ligatures: `<=` `!=` `>=`
- Open `SPC T h` or `SPC :` or a number of other functions

_Observed behaviour:_
- Emacs goes to 99% CPU. You need to close the helm buffer (Cmd-w) and then hit Esc to make Spacemacs work again.

_Expected behaviour:_
- The requested function should just work, with any sequence of symbols replaced by its ligature as appropriate

I tried to narrow down which of the settings cause it to hang. I got it down to the following two:

```
(let ((alist '((45 . ".\\(?:\\(?:-[>-]\\|<<\\|>>\\)\\|[<>}~-]\\)")
               (46 . ".\\(?:\\(?:\\.[.<]\\)\\|[.=-]\\)"))))
  (dolist (char-regexp alist)
    (set-char-table-range composition-function-table (car char-regexp)
                          `([,(cdr char-regexp) 0 font-shape-gstring]))))
```

Either of the two (or both) make Emacs hang as described. They seem to enable the ligatures that start with a `-` or a `.` which should be:

```
-> --> ->> -< -<< --> -- --- -~ 
.= .- .. ... ..< 
```
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp 
 haskell
 (osx :variables osx-use-option-as-meta nil))
```
#### Backtrace

![screen shot 2016-06-30 at 23 54 29](https://cloud.githubusercontent.com/assets/48756/16505616/29e64b82-3f1e-11e6-8db6-f669934154f8.png)

(sorry, I couldn't figure out how to copy or save the backtrace buffer contents)

**Comment by tobia** [comment]
I'm pretty sure the culprit is `->` because it's a symbol that appears in the screens than hang (helm-theme, M-x…) and most importantly, I can reproduce the issue by enabling this single ligature:

    (set-char-table-range composition-function-table 45 '(["->" 0 font-shape-gstring]))

and make the issue go away by disabling it:

    (set-char-table-range composition-function-table 45 nil)

I'm an Emacs newbie, so I have a few questions:

1. Is this a bug in Spacemacs, in Helm, or in Emacs itself?
2. Can I disable the ligatures in Helm buffers and keep them in source code?
3. Can you think of any other workaround?

**Comment by a13ph** [comment]
sorry for somewhat passer-by style, but better something useful early even if little

0. I didn't think ligatures (that stuff at least) are supported yet/well. BTW, take a look at debugging section on Spacemacs github wiki

1. *You* should be the one providing test information about that, ideally, by trying to replicate it with/without Helm (you can set your completion to ivy for example), Spacemacs (`SPC q D` on develop or just run emacs with `-q` flag to ignore `.emacs.d`)

2. Probably possible.

**Comment by CarlQLange** [comment]
:+1: I'm seeing this too. Going to have a little debugging session soon.

**Comment by porglezomp** [comment]
I wasted a few hours today trying to deal with this before finding this issue. Have any of you guys found a workaround besides disabling ligatures entirely?

**Comment by CarlQLange** [comment]
I didn't get anywhere. :( I just decided to use prettify-symbols-mode.

**Comment by spijet** [comment]
I confirm the same problem on Linux (Exherbo x86_64, Emacs 24.5). Eval'ing the Fira Code example hangs Spacemacs when `SPC b b`'ing to another buffer.

**Comment by fmthoma** [comment]
Just a hint (I don't experience this problem, just happened to stumble upon this thread): One culprit could be the regex itself. Some pathological regexes lead to ridiculous amounts of backtracking, which would explain why your CPU is maxed out.
See also this blog post about [a similar issue in Atom](http://davidvgalbraith.com/how-i-fixed-atom/).
