### ISSUE TITLE
Clarify license of logo

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#6469]
It just says "a Creative Commons license`, not [CC-BY-SA 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/) (or however you'd like to present it)

Hopefully, PR incoming :joy:

**Comment by syl20bnr** [comment]
cc @nashamri :-)

**Comment by nashamri** [comment]
It does say "Creative Commons Attribution-ShareAlike 4.0 International License." in my repo :smile: https://github.com/nashamri/spacemacs-logo
It only needs a little update in the README

**Comment by JAremko** [comment]
As I understand logo is also distributed with Spacemacs?  Doesn't it interfere with Emacs/Spacemacs license? It reminds me [the Firefox logo drama]( https://en.wikipedia.org/wiki/Mozilla_software_rebranded_by_Debian)  

Disclaimer: :dog: *woof*

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
