### ISSUE TITLE
Problems with terminal (iTerm2) bindings M-"arrowleft" M-"arrowright" do not work as expected.

### ISSUE THREAD

**Issue by istinspring** [syl20bnr/spacemacs#6470]
Some annoying glitches in org-mode, it works for a while after i reinstall emacs but shortly come back.

#### Description :octocat:

In org mode i can't modify headlines using M-[ M-] or C-] C-] instead emacs just delete the line.

```
M-[ 1 ; is undefined [2 times]
Undo branch point!
TODO state changed to TODO
M-[ 1 ; is undefined [2 times]
Undo branch point!
```
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 237d114)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx git better-defaults ibuffer
     (org :variables org-enable-github-support t)
     auto-completion vim-powerline syntax-checking
     (shell :variables shell-default-shell 'eshell shell-default-position 'bottom shell-default-height 30)
     finance
     (wakatime :variables wakatime-api-key "my-api-key" wakatime-cli-path "/usr/local/bin/wakatime")
     emacs-lisp markdown django react javascript python yaml html themes-megapack)
```

**Comment by istinspring** [comment]
actually there is nothing to do with dev/master branches the behavior is the same. What i found, it's probably happened because i had emacs instance as a service (daemon mode).

**Comment by istinspring** [comment]
Or maybe not, i just fully reinstalled emacs, spacemacs using .spacemacs config. And it's still the same.

**Comment by d12frosted** [comment]
Hey @istinspring,

I am not sure what you are trying to achieve by using `M-[` and `M-]`. For me they are not defined either with Spacemacs nor with stock Emacs. 

Also, if you have keybindings problems, you don't have to reinstall Emacs 😸

**Comment by istinspring** [comment]
emacs show me in message, i'm trying to use M-LeftArrow (<-) M-RightArrow (->)

**Comment by d12frosted** [comment]
Thats strange. Since you are using terminal, are you sure that you don't have some funky keybinding setup in your terminal? Also, please share the output of `C-h k M-<leftarrow>` (`SPC h k M-<leftarrow>)?

**Comment by istinspring** [comment]
Report nothing. But when i hit M-<rightarrow> it delete the string from cursor to the end of line and switch into the INSERT mode.

```
M-[ 1 ; is undefined
```

this is from **message**

**Comment by d12frosted** [comment]
What emulator are you using? Terminal.app or anything else? Could you try with clean configuration scheme in Terminal.app? 

Oh... and also I have a question, what do you mean by 'hit `M-`'? Pressing option and `-`? Also, what happens when you press `M-x` (hold option and press `x`)?

**Comment by istinspring** [comment]
iTerm2

[http://i.imgur.com/aduoolA.png](iTerm2 key mapping)

**Comment by istinspring** [comment]
i just tried to reset settings for iTerm. Still same.

**Comment by istinspring** [comment]
hm now when i hit ```M-x``` i got ```≈ is undefined```

**Comment by istinspring** [comment]
tried to run emacs under Terminal.app and it works normally. So what's going on with iTerm2? I'm pretty damn sure this started after recent update.

**Comment by istinspring** [comment]
probably relevant http://unix.stackexchange.com/questions/24414/shift-arrow-not-working-in-emacs-within-tmux

**Comment by d12frosted** [comment]
> hm now when i hit M-x i got ≈ is undefined

This means that iTerm doesn't use option as meta-key. In Terminal.app this can be configured in following screen.

<img width="665" alt="screenshot 2016-07-02 12 04 23" src="https://cloud.githubusercontent.com/assets/6507913/16539480/325c174e-404d-11e6-87c4-36a02dbb74bc.png">

In iTerm the setting is similar (just use `+ESC`).

<img width="1016" alt="screenshot 2016-07-02 12 21 38" src="https://cloud.githubusercontent.com/assets/6507913/16539557/9164723e-404f-11e6-8040-997210f844a9.png">

**Comment by istinspring** [comment]
@d12frosted i did but it's still the same, i guess there is something with Tmux, since i run emacs inside the Tmux sessions.

**Comment by istinspring** [comment]
@d12frosted  the problem isn't gone =( Something with iTerm2 key mapping. I already drop all preferences, set +Esc for Left Option.

**Comment by d12frosted** [comment]
Hey @istinspring,

Since I am not using TMUX, I don't see how I can help you with configuring iTerm and TMUX. This is a little outside of Spacemacs scope to be honest. Anyway, could you please try running Emacs outside of TMUX to confirm that setting option key to `+Esc` fixes your isssue?

**Comment by istinspring** [comment]
OK. Somehow it works now, i'm not sure what's caused it. I set keys to ```xTerm default```, next left option to ```+ESC``` and right option to ```Meta```. Also i updated iTerm2 to the latest version.

**Comment by d12frosted** [comment]
@istinspring Glad you fixed it 😸
