### ISSUE TITLE
Slow with same file open in multiple windows

### ISSUE THREAD

**Issue by rationalis** [syl20bnr/spacemacs#6471]
#### Description

Spacemacs lags whenever the same file is open in multiple windows
#### Reproduction guide
- Start Emacs
- Open a file
- For the most exaggerated effect, use a large syntax-highlighted file like .spacemacs and turn on line numbering
  -- I believe it was also much worse when I had vim-empty-lines enabled, but I disabled that quite early on in the process of trying to find an immediate workaround, so the extra lag might've been some other un-isolated variable (like the branch or version of emacs)
- Open multiple windows (tested using vertical splits) which all display the same file. It lagged more with more windows open.
- Attempt scrolling, which-key, etc. in any of the windows

_Observed behaviour:_
Slow to unusable lag (maxed out CPU usage, freezing if line numbering is also turned on)

_Expected behaviour:_
Unhindered performance
#### System Info :computer:
- OS: windows-nt
- Emacs: 24.5.1 (Also tested on 25.0.94.2)
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 237d114) (Also tested on master)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults chrome emacs-lisp
                 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
                 git org ranger search-engine
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking)
```

**Comment by syl20bnr** [comment]
Not sure this is Spacemacs related, I always noticed performance drop when opening the same buffer in multiple windows. `line-numbers` are a known mode that can greatly impact performance.

Does it happen in any type of buffer or is it major-mode specific ?

**Comment by rationalis** [comment]
Just checked in a plaintext file -- still seems to happen, but it takes more windows to get noticeable lag/freezing.

**Comment by simendsjo** [comment]
Turning off line-numbers worked for me. Guess native line numbers will solve this issue.
