### ISSUE TITLE
Cursor jumps between windows when switching windows

### ISSUE THREAD

**Issue by landaire** [syl20bnr/spacemacs#6475]
#### Description

When I switch windows the cursor will jump between all of the windows very quickly for a couple of seconds then stop on the correct window.
#### Reproduction guide
- Start Emacs
- Open a few windows
- Switch windows

_Observed behaviour:_
The cursor jumps between all windows very quickly for a few seconds before stopping on the correct window

_Expected behaviour:_
Cursor should move to the specified window without the jumping
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 better-defaults emacs-lisp git org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control semantic c-c   d go rust swift java yaml latex markdown gtags osx spacemacs-layouts themes-megapack
 (colors :variables colors-enable-rainbow-identifiers nil))
```

**Comment by landaire** [comment]
[NJBS mentioned on gitter](https://gitter.im/syl20bnr/spacemacs?at=5776d82ccdab7a1f4fc135d4) that it could have been a bug with Helm and that updating packages should fix it. Helm didn't update when I ran update-packages, but it's no longer occurring after a restart so I'll mark this as closed.

**Comment by landaire** [comment]
Reopening since it actually started occurring again.

**Comment by syl20bnr** [comment]
I had a similar issue and I use golden-ratio too, it does not happen all the time. I'll investigate when I encounter it again.

**Comment by landaire** [comment]
Here is a video demonstrating the issue: https://gfycat.com/OddUntimelyIbadanmalimbe (I suggest going fullscreen)

I think the below conditions need to be met in order to trigger it though:

- Open `neotree` (`SPC f t`)
- Create a split window (`SPC w v`, three windows total should be open now)
- Press `:` and cursor should jump
- Or enable `golden-ratio` (`SPC t g`), then switch windows (`SPC w [h,l]`)  and cursor should jump

None of this can be reproduced with a `neotree` window not open.

**Comment by YeFFreY** [comment]
I had a similar issue (even worse, each time I was pressing the SPC key I had to wait 3 to 5 seconds until the cursors stops jumping between every windows). (Im on OSX)
Then I installed this emacs : emacs-mac (https://github.com/railwaycat/homebrew-emacsmacport)
and the problems stopped.

**Comment by landaire** [comment]
@YeFFreY if you still have regular GNU Emacs installed could you see if you can reproduce it with `neotree` open? `emacs-mac` is not a good solution since while it adds some good features it also introduces some other issues that aren't present in standard.

**Comment by sbdchd** [comment]
@landaire Does the issue still occur if you set `dotspacemacs-colorize-cursor-according-to-state nil` in your `.spacemacs`?

**Comment by landaire** [comment]
@sbdchd Hey, sorry I never saw your response here. I think that did the trick! I'm not seeing that behavior anymore with `dotspacemacs-colorize-cursor-according-to-state nil`.

**Comment by timjstewart** [comment]
I created 5 vertical splits and then pressed SPC b h and saw the flickering.  This is not the only way to reproduce the error for me.  Any tips on debugging?

![emacs-flicker](https://user-images.githubusercontent.com/55925/40751604-1bafbd6e-6429-11e8-8614-2a469d3818f4.gif)

**Comment by syl20bnr** [comment]
Does it happen everytime or just with the home buffer, we have some
computation that is trigerred to center the home buffer contents which
may be the cause of this glitch.

Can you try your repro with `dotspacemacs-startup-buffer-responsive` set
to nil ?

**Comment by timjstewart** [comment]
Sorry for just getting to this @syl20bnr.  I can no longer reproduce this behavior using the steps I provided.

My dotspacemacs-startup-buffer-responsive variable is set to t.

Thanks!

**Comment by timjstewart** [comment]
Today I did a pull from develop and the jumping issue is back.
