### ISSUE TITLE
Hl-line overlay blinks when typing the character "f"

### ISSUE THREAD

**Issue by PeppermintHippo** [syl20bnr/spacemacs#6481]
#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp org syntax-checking racket common-lisp scheme)
```

#### Description
typing "f" causes the hl-line to blink, pressing and holding "f" the overlay completely disappears until you stop pressing. This does not happen in vanilla emacs. 
Problem still present even when I remove all my person edits/configs.

#### Reproduction guide
- Start Emacs
- go to "scratch" buffer 
- with hl-line visible,
 type "f"
- notice hl-line overlay blink.

**Comment by NJBS** [comment]
This is due to `evil-escape-key-sequence` being set to `fd` by default.

See [here](http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline82) if you want to learn more or change the sequence.

**Comment by PeppermintHippo** [comment]
ah ill close this then, although it would be nice to keep this feature and not have the blink occur

**Comment by a13ph** [comment]
@PeppermintHippo For me, on Ubuntu, I don't have a blink, my line highlighting just disappears temporarily, until key is resolved, just like it is with `y` operator pending, for example. 
See if this is the same for you?

**Comment by PeppermintHippo** [comment]
well the time between pressing "f" and "d" is small enough that I would consider it a blink, I am speaking of course in "Insert State" no the normal state.
