### ISSUE TITLE
support shader language

### ISSUE THREAD

**Issue by wolfand11** [syl20bnr/spacemacs#6483]
glsl-mode  https://github.com/jimhourihan/glsl-mode
hlsl-mode  https://github.com/lenxyang/env/blob/master/emacs/.emacs.d/site-lisp/hlsl-mode.el
unity surface-shader https://github.com/midnightSuyama/shader-mode
cg-mode   https://www.emacswiki.org/emacs/CgMode
~~there isn't an enable cg-mode.~~

**Comment by ksjogo** [comment]
glsl is already in melpa, so you could just install that package: http://melpa.org/#/glsl-mode

**Comment by d12frosted** [comment]
While it's easy to do (all configuration falls into `auto-mode-alist` modification) it might be useful to provide a layer with these two packages. 

Also, even if it's not on elpa, you still can install that package by adding it to list of additional packages (or into list of your private layer packages) with github location. You can find more info in documentation 😸

**Comment by d12frosted** [comment]
FYI, `glsl-mode` is now available on develop. I am going to add support of `hlsl-mode` pretty soon. The layer is `shaders`.

**Comment by Warezovvv** [comment]
Where is hlsl-mode?)

**Comment by Warezovvv** [comment]
Soo I need hlsl and where is it?))

**Comment by d12frosted** [comment]
Ahaha, I was dragged by real life and haven't finished that yet. Feel free to add that to shaders layer.

**Comment by Warezovvv** [comment]
Oh. I'm new to spacemacs and emacs. You mean this file 
https://github.com/lenxyang/env/blob/master/emacs/.emacs.d/site-lisp/hlsl-mode.el
to somewhere? 
Also why is it not in melpa package. Some things confusing me.
