### ISSUE TITLE
Too much issues to use.

### ISSUE THREAD

**Issue by qx** [syl20bnr/spacemacs#6487]
This is not real bug,Just advise.
About 3 weeks ago ,I found spacemacs,it  attracted me in first meet. 
It was beautify and easy use for emacs's beginner.
After some days learn and using , I find some problem,some bug or maybe not. 
I confused with too much issues, Is there all bug? or others, if not bug or some problem that need not to be fixed ,why don't you close it? It's bit fear to use a tool with so much problems. How do you think?

**Comment by NJBS** [comment]
The issue tracker is very convenient for project management and not only used for reporting bugs.

For example, some of the additional things issues can serve as are: 

- forums for discussion about a question

- mailing lists for development of future features or changes for spacemacs

- bug trackers for upstream issues with packages that spacemacs uses

- feature requests for what people would like to see in spacemacs

Additionally, a lot of the issues that are in-fact bugs have been fixed on the `develop` branch of spacemacs (which is currently about 1,000 commits ahead of `master` :open_mouth:) and are left open until the fix has been applied to the `master` branch.

That being said, I can understand where you're coming from and how at a first glance the sheer volume of issues might be a deterrent to those looking to try out spacemacs.

Perhaps it's time for another cleanup https://github.com/syl20bnr/spacemacs/issues/3549 :smile: 

cc @syl20bnr @d12frosted

**Comment by d12frosted** [comment]
I agree on what @NJBS has already said, and would like to add only following things.

1. Spacemacs combines multiple packages. Sometimes those packages have different bugs. Most Spacemacs users come to Spacemacs issue tracker before actually reporting the problem upstream. And to be fair, Spacemacs users helped to find and solve lots of bugs with 3rd-party packages.
2. A lot of Spacemacs users are new to Emacs world and so whenever they have general questions about Emacs or problems with it - they open new issue in Spacemacs bug tracker. While this is OK - it takes time and effort to help them. And such issues remain open for some time. 

As @NJBS said, there are actually three types of issues - questions, development discussions, bugs. They all have corresponding tags - `-Forum-`, -Mailing list` and `-Bug tracker-`. To see more or less comprehensive list of bugs, use this [link](https://github.com/syl20bnr/spacemacs/issues?utf8=✓&q=is%3Aopen%20is%3Aissue%20label%3A%22-%20Bug%20tracker%20-%22%20-label%3A%22Fixed%20in%20develop%22%20-label%3A%22Fixed%20upstream%22%20-label%3A%22Reported%20upstream%22%20-label%3A%22Should%20report%20upstream%22%20-label%3A%22Wontfix%20%3A-%2F%22%20). 

Also keep in mind that this is Emacs - it is in it's core philosophy to be used in whatever way one desires. So there are lots of corner cases which are hard to predict. Some of them are hard to resolve and sometimes they go out of Spacemacs scope. 

Another thing you should know - whenever something critical happens we try to solve it ASAP (be it in Spacemacs itself or in 3rd-party package, or even with MELPA availability). 

As per cleanup - @StreakyCobra shared the tool he created for cleanup event and I am planning to start new round pretty soon.

**Comment by qx** [comment]
@d12frosted  I completely understand you've try your best for spacemace, and it's not easy, thanks for your hard working! 
As @NJBS said: "Perhaps it's time for another cleanup #3549 😄"
