### ISSUE TITLE
Spacemacs crashed on startup when using a wide enough picture as banner

### ISSUE THREAD

**Issue by potmpark** [syl20bnr/spacemacs#6488]
#### Description
Setting `dotspacemacs-startup-banner "path/to/picture.png"` with a wide enough(width > 75)
picture will cause a crash on spacemacs startup

#### Reproduction guide
- Setting `dotspacemacs-startup-banner "path/to/picture.png"` in .spacemacs
- Make sure `picture.png` is wider than 75 using: 

  ```elisp
  (floor (car (image-size (create-image "path/to/picture.png"))))
  ```
- Start Spacemacs

*Observed behaviour:*
Spacemacs crashed on startup
*Expected behaviour:*
The picture is shown in the startup buffer

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git org emoji markdown c-c   go haskell python racket scheme javascript shell-scripts html syntax-checking)
```

#### Backtrace
```
;; The width of the picture used is 213
Debugger entered--Lisp error: (wrong-type-argument wholenump -70)
make-string(-70 32)
(insert (make-string left-margin 32))
(let* ((title spacemacs-buffer-logo-title)
       (spec (create-image banner))
       (size (image-size spec))
       (width (car size))
       (left-margin (floor (- spacemacs-buffer--banner-length width) 2)))
  (goto-char (point-min))
  (insert "\n")
  (insert (make-string left-margin 32))
  (insert-image spec)
  (insert "\n\n")
  (insert (make-string
            (floor (/ (- spacemacs-buffer--banner-length (+ (length title) 1)) 2)) 32))
  (insert (format "%s\n\n" title)))

```

**Comment by NJBS** [comment]
Fixed on `develop` by https://github.com/syl20bnr/spacemacs/commit/f305bd

**Comment by potmpark** [comment]
Sorry, I should try the `develop` branch first.
