### ISSUE TITLE
GNU Emacs 25 on Mac -- can't change font

### ISSUE THREAD

**Issue by reckbo** [syl20bnr/spacemacs#6489]
#### Description :octocat:

Upgraded from Emacs 24.5 to GNU Emacs 25 on Mac, now my font config isn't recognized.

#### Reproduction guide :beetle:

- Add font setting to .spacemacs, e.g.

    dotspacemacs-default-font '("Source Code Pro for Powerline"
                                :size 14
                                :weight light
                                :width normal
                                :powerline-scale 1.0)

- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Menlo font.

*Expected behaviour:* :heart: :smile:
Beautiful Source Code Pro font.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 079e0ae)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(nixos erc pdf-tools fasd prodigy markdown html
       (haskell :variables haskell-process-type 'stack-ghci haskell-completion-backend 'ghc-mod)
       java csv yaml finance auto-completion emacs-lisp git
       (org :variables org-enable-github-support t)
       (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
       spell-checking syntax-checking version-control imenu-list search-engine themes-megapack
       (bibtex :variables bibtex-completion-pdf-field "File")
       vinegar)
```

**Comment by d12frosted** [comment]
Hey @reckbo,

How have you installed Emacs 25? I also use Emacs 25 (from brew with `--HEAD --use-git-head` options) and everything works for me. But I use `Source Code Pro` (you could also try it, cause IIRC new versions are already powerline compatible - but I could be wrong).

**Comment by reckbo** [comment]
Hi @d12frosted 

I installed it as you suggested in another thread, using brew `--HEAD --use-git-head` etc. I tried different fonts but none are recognized.  On the upside, spacemacs is a lot less laggy.

**Comment by d12frosted** [comment]
Hm. Interesting. Just curious if it's possible to change font from options menu. 

<img width="536" alt="screenshot 2016-07-04 11 48 15" src="https://cloud.githubusercontent.com/assets/6507913/16555436/54cce07e-41dd-11e6-9ae0-6622a08f314c.png">

![screenshot 2016-07-04 11 48 26](https://cloud.githubusercontent.com/assets/6507913/16555441/58d50ad4-41dd-11e6-9ba7-f023dcda9fe5.png)

**Comment by reckbo** [comment]
Yes, except for the typeface options, I can change the font from the menu and it works.  Changing it in my .spacemacs has no effect (e.g. `dotspacemacs-default-font '("Helvetica")`)

**Comment by d12frosted** [comment]
Do you see any related errors in `*Messages*` buffer?

**Comment by reckbo** [comment]
Nope, no errors.

---
Loading /Users/ryan/.emacs.d/core/core-load-paths.el (source)...done
Loading /Users/ryan/.spacemacs...done
Setting the font...
Open the quickhelp.
Loading /Users/ryan/.emacs.d/layers/+os/nixos/packages.el (source)...done
Loading /Users/ryan/.emacs.d/layers/+chat/erc/packages.el (source)...done
Loading /Users/ryan/.emacs.d/layers/+tools/pdf-tools/packages.el (source)...done
...

**Comment by reckbo** [comment]
I figured it out -- at the very end of my .spacemacs under 'custom-set-faces' there was an extra setting
that wasn't there before, setting some default value (I deleted it otherwise I would post it).  Now my fonts work.  However, spacemacs feels laggy again, but now I know it has something to do with the fonts.

Thanks @d12frosted.

**Comment by d12frosted** [comment]
Haha, it happens 😸 Glad you figured it out! Spread the love for Emacs 25!

**Comment by reckbo** [comment]
I figured out that my scrolling lag was caused by my escape sequence 'jk' -- after removing that my spacemacs is as fast as vim.  I'm happy again :)

**Comment by boj** [comment]
If anyone else comes across this issue the custom-set-face culprit was `'(default ((t (:background nil))))` in my own case. Thanks to the other comments in this thread for leading me to that.

**Comment by olivier-ma** [comment]
I'm also having this problem. Can change the font in system menu, but can't change it in `.spacemace` file, and I don't have anything in my `custom-set-faces`..

**Comment by choppsv1** [comment]
I had both problems with the custom.el setting showing up for some reason, and then also the slow lag from escape sequence jk. Thanks for the fix. I wonder how many other people run into the 'jk' thing and don't realize it (just put up with it being slow).
