### ISSUE TITLE
personal  yasnippets in org-mode doesn't work properly with  ```tab``` key

### ISSUE THREAD

**Issue by mihaelS** [syl20bnr/spacemacs#6495]
#### Description
personal  yasnippets in org-mode doesn't work properly with  ```tab``` key

#### Reproduction guide
- Start Emacs
- configure yasnippets:
 - add autocomplection level
 - define personal snippets 
 ```bash
# cat ~/.emacs.d/snippets/org-mode/test

# -*- mode: snippet -*-
# name: test_org
# key: test
# --
test-snippet-text
```
  - add snippets-directory to the user-config
  ``` elisp
   '("~/.emacs.d/snippets"            ;; personal snippets
    ))
  ```
- restart emacs
- open the .org file
- check if the snippets are avaible with the mouse: left click on the (y) in circle
 
![image](https://cloud.githubusercontent.com/assets/11715774/16576410/bf944a86-4297-11e6-8515-689a72825266.png)

- try to add your snippet by the clipboard: type "test" and then press ```tab```

*Observed behaviour:*
nothing happens

*Expected behaviour:*
replace snippet-key "test" with the snipet-text "test-snippet-text"

#### System Info
- OS: windows-nt
- Emacs: 25.0.94.2
- Spacemacs: 0.105.21
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp html org)
```

**Comment by d12frosted** [comment]
Hey @mihaelS,

`Tab` is not used for snippets expansion. Please, check `auto-completion` layer [documentation](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+completion/auto-completion/README.org#yasnippet). In short, you are looking for `M-/`.

**Comment by mihaelS** [comment]
Thanx for the guidance :+1:
