### ISSUE TITLE
Spacemacs how to start describe-mode auto in console?

### ISSUE THREAD

**Issue by yestab123** [syl20bnr/spacemacs#6496]
I use spacemacs to edit C file, it will show the variable or function definition on the bottom when I open ~/.emacs.d/layer/+distribution/spacemacs-base/keybindings.el first.[M-m h d f -> spacemacs/describe-mode -> and then press the file [keybindings.el] which show on the message]

But it need to open this file every time when I restart spacemacs. Has any solution to auto load this mode?

Thank You.

**Comment by a13ph** [comment]
Try installing `semantic` layer

It's not "describe-mode".
It's most probably one of `semantic` modes, `semantic-idle-summary-mode`

There is a `eldoc`, which gives you those nice function signatures (as lists of arguments) for ELisp.
For `eldoc` btw there is a package on ELPAs which adds support of `C` language: `c-eldoc`.

Just in case:
[How to install layers to Spacemacs](http://spacemacs.org/doc/DOCUMENTATION#orgheadline38)
[How to install packages to Spacemacs](http://spacemacs.org/doc/DOCUMENTATION#orgheadline21)

Bonus information for curious:
There's also https://www.emacswiki.org/emacs/PosTip
But I assume there's some alternative/better ways to automatically show help about 'thing at point' bigger than just a docstring

**Comment by yestab123** [comment]
@a13ph Yes, it's 'semantic-idle-summary-mode'. 

Add `(semantic-idle-sumarry-mode)` in .spacemacs, it can auto load the mode what I want now.

Thank you very much!
