### ISSUE TITLE
setq-default tab-width breaks prefix labels in helm/ivy

### ISSUE THREAD

**Issue by crshd** [syl20bnr/spacemacs#6497]
#### Description :octocat:
Setting `tab-width` to anything but 0, 1, 2, 4, 8 or 16 breaks the prefix labels in helm/ivy.

#### Reproduction guide :beetle:
- Start Emacs
- eval `(setq-default tab-width 3)`
- `SPC`

*Observed behaviour:* :eyes: :broken_heart:
All prefix keys are labeled "prefix"

*Expected behaviour:* :heart: :smile:
Prefix keys should be labeled according to their function.

---

- eval `(setq-default tab-width 17)`
- `SPC`

*Observed behaviour:* :eyes: :broken_heart:
`SPC`-menu doesn't open, instead message "which-key: There are no keys to show"

*Expected behaviour:* :heart: :smile:
Prefix keys should be labeled according to their function.

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. a650877)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence "jk" auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 emacs-lisp erc evil-cleverparens evil-snipe
 (figlet :variables figlet-font "cyberlarge")
 (games)
 git html javascript markdown org osx php shell-scripts
 (smarttab :variables smarttab-insinuate 'c 'javascript)
 syntax-checking
 (version-control :variables version-control-diff-tool 'diff-hl)
 vinegar)
```

**Comment by NJBS** [comment]
Oh, that's quite odd.

@justbur any ideas?

**Comment by justbur** [comment]
Yes, that's bizarre, but it should be fixed with https://github.com/justbur/emacs-which-key/commit/9ec4b6a258c99bff307cfbde6b183634210d6363

**Comment by d12frosted** [comment]
@justbur thanks for the quick fix 💯 

@crshd could you please confirm that latest change in `emacs-which-key` package fixes your problem?

**Comment by crshd** [comment]
Works fine, thanks.
