### ISSUE TITLE
error: spacemacs/search-project-auto-region-or-symbol

### ISSUE THREAD

**Issue by pA0k** [syl20bnr/spacemacs#6499]
#### Reproduction guide :beetle:
- Start Emacs
- M-m *

_Observed behaviour:_ :eyes: :broken_heart:

_Expected behaviour:_ :heart: :smile:
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. a650877)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:

``` elisp
(ivy auto-completion better-defaults shell-scripts emacs-lisp
     (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save t)
     (ruby :variables ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec)
     git html markdown org
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-protect-eshell-prompt t)
     (spell-checking :variables spell-checking-enable-by-default nil)
     syntax-checking version-control chrome)
```
#### Backtrace :paw_prints:

```
```

I got an error message.

```
rxt-string->pcre: Wrong type argument: arrayp, nil
```

**Comment by pA0k** [comment]
I found out why error occured.
It happend running command at blank line.

**Comment by d12frosted** [comment]
@pA0k thanks for the report. Didn't see such behaviour before but I can confirm it.

**Comment by Miciah** [comment]
#11013 should prevent the error.
