### ISSUE TITLE
Org-mode how to insert timestamp with Minutes:Seconds?

### ISSUE THREAD

**Issue by istinspring** [syl20bnr/spacemacs#6503]
Originally it's ```C-u C-c ```. but in spacemacs it's just move cursor into the beginning of the file.

**Comment by a13ph** [comment]
Vim style: `SPC u , .`  
Emacs style:  `C-u C-M-m .` or `M-m u C-M-m .`
Explanation/mnemonics:
`C-u` => `SPC u` if on vim style, `M-m u` or the vanilla `C-u` on emacs style
`C-c` => `,` (at least for org-mode it usually is, especially while in org-mode. `C-M-m` on Emacs style)
`.` => still `.`

**Comment by istinspring** [comment]
Yes it works! Thank you.

**Comment by d12frosted** [comment]
Since original question is resolved, I am closing this issue. If anyone has anything else to add to this topic, please don't hesitate 😸

**Comment by Jks15063** [comment]
Is there a way to specify the time?

**Comment by chrissound** [comment]
It seems to be `SPC u C-c .` in vim mode now.
