### ISSUE TITLE
Add string-inflection

### ISSUE THREAD

**Issue by anonymni** [syl20bnr/spacemacs#6504]
https://github.com/akicho8/string-inflection

**Comment by a13ph** [comment]
There are also some alternative implementations of it, around 5 in total, I think

**Comment by anonymni** [comment]
Yeah. We  should discuss how to add this feature to Spacemacs to make editing more convenient. I'd love to hear thoughts.

**Comment by d12frosted** [comment]
Whatever implementation you chose, please don't follow this madness:

```
(global-unset-key (kbd "C-q"))
```

**Comment by rmhsilva** [comment]
I've added string-inflection to my fork (fa20d65095adb2784a898542da078170919f2012), but there is currently a bug upstream, so I'll hold off on the PR for now.

I've done nothing more than add the package and set up some keybindings (`SPC x i` prefix).

**Comment by rundong08** [comment]
Should be closed by #8084.
