### ISSUE TITLE
trouble in delete trailing whitespace in markdown mode

### ISSUE THREAD

**Issue by was4444** [syl20bnr/spacemacs#6510]
Hi,
In the markdown mode, the two whitespaces at the end of a line are meaningful. Is there a smarter way to delete the trailing whitespace?

**Comment by nixmaniack** [comment]
Not sure of smarter way but you can disable whitespace-cleanup in buffer using `SPC t W` or add hook to markdown mode to disable whitespace cleanup.

**Comment by was4444** [comment]
@nixmaniack, I can disable it, but whitespace-cleanup is also useful. It may be better if I can cleanup whitespaces but skip the only two trailing whitespaces.

**Comment by nixmaniack** [comment]
In that case you might request this feature upstream at [ws-butler](https://github.com/lewang/ws-butler) with some customization variable to enable in markdown.

**Comment by was4444** [comment]
@nixmaniack, I agree, and I will open a ticket there. Now time to close this one.

**Comment by was4444** [comment]
It seems ``Spacemacs`` only use [``ws-butler``](https://github.com/lewang/ws-butler) if ``dotspacemacs-whitespace-cleanup``  is set to ``changed`` 

https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs-base/config.el#L165

https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistribution/spacemacs-base/packages.el#L1630

**Comment by nixmaniack** [comment]
That's right. For `'all` and `'trailing` the feature needs to be implemented in Emacs itself.

**Comment by divansantana** [comment]
@nixmaniack Can this not be fixed in spacemacs or does it need to be in Emacs itself? Would be nice to be able to set `dotspacemacs-whitespace-cleanup` to `all` and not break `markdown-mode` editing. 

Anyone have a hack to mack this possible?

**Comment by nixmaniack** [comment]
The intelligence required to handle `markdown-mode` isn't in any of the options as of now. Even `ws-buttler` just disables itself in `markdown-mode`.

So the only workaround for now is to disable whitespace cleaning in `markdown-mode` until someone fixes this! 

> Can this not be fixed in spacemacs or does it need to be in Emacs itself?

Well, that's possible given its Emacs! ;) But better fix for `'all` and `'trailing` would be in Emacs itself by patching the functions that Spacemacs uses viz. `whitespace-cleanup` and `delete-trailing-whitespace`. And fix for `'changed` would go in `ws-butler` but I think it needs much work hence author has just exempted it.
