### ISSUE TITLE
We need an official term for the Spacemacs users!

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#6511]
Golang users are called gophers.
also they have a mascot
![gopher](https://habrastorage.org/getpro/habr/comment_images/5d0/2d6/13d/5d02d613daac968219806823876112b9.png)
I think the induced tribalism  is a main reason of its success. So... We clearly need the name of our own! We can't call each other simply people - we are much more! We are Spacemacsers.. ? Spacemacsians.. well.. Spacemacs has a planet on its logo. :confused:   

Any idea?

**Comment by dubnde** [comment]
_Spacemacs_ works for me. I know :confused:

**Comment by d12frosted** [comment]
> Spacemacsians

I love it

**Comment by sindikat** [comment]
Emacstronauts.

**Comment by JAremko** [comment]
@a13ph  the depth :+1:

**Comment by crshd** [comment]
> Spacemacsians

I keep reading that as "Spacemexicans", which makes absolutely no sense whatsoever...

**Comment by JAremko** [comment]
>I keep reading that as "Spacemexicans", which makes absolutely no sense whatsoever...  

Mast not... make.. joke... About...  Sphere of concrete around the planets.. :cold_sweat:

**Comment by CestDiego** [comment]
How about Spatial Gnus

**Comment by JAremko** [comment]
> How about Spatial Gnus

hm. It's hard to scream out loud. I don't think that the enemy will be intimidated. :confused:
