### ISSUE TITLE
org-toggle-inline-image failed

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#6516]
#### Description :octocat:
org toggle inline image failed.

#### Reproduction guide :beetle:
- Start Emacs
- Open an org file containing following lines:

```
#+attr_latex: :width 0.5\textwidth
[[./image.png]]
```
where `image.png` could be any image file.

- toggle inline image with `org-toggle-inline-image` (default on)

*Observed behaviour:* :eyes: :broken_heart:
Inline image does not show. It should be noted that when I delete the attrib line, the inline image can be toggled on (**only image links with an attrib line are affected**). Also when started as stock emacs with latest org (org-plus-contrib), the image shows correctly. Spacemacs at master branch does not suffer from this issue.

*Expected behaviour:* :heart: :smile:
Inline image shows as expected.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: nil (rev. a650877)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(better-defaults emacs-lisp git org version-control)
```

#### Backtrace :paw_prints:
No error message available

**Comment by syl20bnr** [comment]
> #+attr_latex :width 0.5\textwidth

Are you sure this is a valid attribute? 
In master branch this attribute is ignored, whereas in develop branch it is now taken into account because we set `org-image-actual-width` to nil (https://github.com/syl20bnr/spacemacs/blob/develop/layers/+emacs/org/packages.el#L114)
The documentation for this variable:
```
org-image-actual-width is a variable defined in `org.el'.
Its value is nil
Original value was t

Documentation:
Should we use the actual width of images when inlining them?

When set to t, always use the image width.

When set to a number, use imagemagick (when available) to set
the image's width to this value.

When set to a number in a list, try to get the width from any
#+ATTR.* keyword if it matches a width specification like

  #+ATTR_HTML: :width 300px

and fall back on that number if none is found.

When set to nil, try to get the width from an #+ATTR.* keyword
and fall back on the original width if none is found.

This requires Emacs >= 24.1, build with imagemagick support.
```

**Comment by et2010** [comment]
Sorry, I should check the history of org layer first before reporting this.

Thanks for the hint. So this one is on orgmode. It should use fallback width when there is a `:width` property whose value cannot be used by inline image.

The attribute itself is actually valid, see: [](http://orgmode.org/manual/LaTeX-specific-attributes.html). But it seems that org cannot parse it correctly for inline image and doesn't use a fallback either.

**Comment by d12frosted** [comment]
Closing this as it seems that original question was resolved. Feel free to reopen if you still have problems we can help you with 😸
