### ISSUE TITLE
Improve Helm default bindings

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#652]
Currently, we cannot clear pattern prompt because `C-k` is taken to move up. There should be some other key binding to replace it.

Also, `TAB` currently does not work for switching to action menu.

**Comment by syl20bnr** [comment]
I added a convention for the micro-states initiated in special buffers, there now use <kbd>C-SPC</kbd>.
<kbd>C-k</kbd> can be performed with <kbd>C-backspace</kbd> but it does not work in a terminal.

What about <kbd>C-d</kbd>.

**Comment by tuhdo** [comment]
I've read the documentation about Helm micro state and I think it's fine to leave it as is, except that we only need to find a key to replace `C-k`. Since `C-<backspace>` does not work in terminal, we should add a key binding to current micro state, such as `dd`.

**Comment by syl20bnr** [comment]
There are several issues with TAB to toggle the micro state (from the less important to the most):
- it overwrites a default action of `helm`
- some people rewire TAB to be CTRL
- TAB is completion in `ido`

I had already planned to change TAB for something that can be used in both ` helm` and `ido`. I came with `C-SPC` but maybe something better can be found. I would have preferred `S-SPC` but it does not work in terminal without explicit setup :-(
