### ISSUE TITLE
Add support for vim magic filetype strings

### ISSUE THREAD

**Issue by a13ph** [syl20bnr/spacemacs#6524]
- [x] Why!
- Helping Vim users to migrate easier
  - Since they may have used magic strings in their files
- Just plain simple for compatibility/parity with Vim features
  - Will help to deal with vim magic strings in projects and teams
  - One step closer to making #5427 done by virtue of "just working" for more vim features :smile:
- [x] How!
  [`magic-filetype.el`](https://github.com/zonuexe/magic-filetype.el) + `(setq-default magic-filetype-enable-vim-filetype t)`
- [ ] Where?
  Somewhere in the `/+distributions/` or smth like that...
  It should go closer to spacemacs core and not as a layer, I believe
  It's small and expected to work out of the box (at least in sufficiently big version of the box)
- [ ] Instead?
  I'm not sure this one supports everything vim magic strings can do

**Comment by d12frosted** [comment]
Hey @a13ph,

I don't have any vim background and my google-fu is quite weak, so... Could you please explain in short (or at least point me to explanation of) what magic filetypes are? 

Thanks in advance!

**Comment by a13ph** [comment]
@d12frosted think mode strings like this in emacs `-*- org-mode -*-` (or something of sorts)
Those are rarely used in emacs nowadays, but still occur in the wild.
While vim their kind of magic strings is quite common and can do much more, being their file-local variables, if you wish.
[See vim docs on sourceforge or elsewhere for the word "modeline"](http://vimdoc.sourceforge.net/htmldoc/options.html#modeline)

**Comment by d12frosted** [comment]
@a13ph Those are not mode strings, but file local variables. You can do [much more](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html#Specifying-File-Variables) than just specifying modes. 

And thanks for explaining. Looks like it might be useful when working in one team with vim-users.

**Comment by JAremko** [comment]
@d12frosted   Isn't  `-*- org-mode -*-` is some kind of file metadata?  I think I saw something like this as a first line in a file.  We might use to set variables, toggle modes. Seems useful(and dangerous). [`org-mode` has similar stuff](http://orgmode.org/manual/Initial-visibility.html).

**Comment by d12frosted** [comment]
@JAremko you might seen it [here](https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template#L1). Not sure what you mean by 'metadata', but actually it's simply special comments that Emacs knows how to 'evaluate'.

**Comment by JAremko** [comment]
@d12frosted Yes. I was thinking how safe they are. And that "magic filetype strings" are, probably, safer version. But then I found [Safety of File Variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Safe-File-Variables.html#Safe-File-Variables) so it's should be ok :smiley:

**Comment by JAremko** [comment]
Might be worth a while to add  vim magic file type strings support to  smooth out Vim -> Spacemacs migration.

**Comment by a13ph** [comment]
@d12frosted I was actually referring exactly to strings specifying modes, which are logical to call mode strings even if that's not a convention (thought I thought it is/was amongst emacsers?) 
I might've not known they are file variables, though. But I do know what those are.

Most of what you've said also pertains to Vim ones. Which is why I'm pushing towards supporting both kinds. (not ideal, but better than asking for a third, but 'definitely final' standard)
