### ISSUE TITLE
orgtbl-* not listed until org-mode is loaded

### ISSUE THREAD

**Issue by alejandroerickson** [syl20bnr/spacemacs#6535]
#### Description

orgtbl-mode and related functions are not listed as interactive functions until org-mode is loaded.
#### Reproduction guide
- Start Emacs
  `SPC : orgtbl`

_Observed behaviour:_
Nothing related to `orgtbl` in list

_Expected behaviour:_
should see `orgtbl-mode` and other things
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: myconfig (rev. 287df0f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp misc xkcd osx gnus latex themes-megapack
                 (shell :variables shell-default-shell 'ansi-term)
                 org speed-reading spell-checking syntax-checking
                 (c-c   :variables c-c  -enable-clang-support t)
                 ruby python yaml cscope media markdown pandoc search-engine sagemath typography vim-powerline git)
```

**Comment by NJBS** [comment]
I can't reproduce this on latest `develop`, `orgtbl-mode` should be available as of https://github.com/syl20bnr/spacemacs/commit/d33507f42a398a090ccbe4ad7b8b0534e71aa364.

**Comment by jeremyjh** [comment]
I still have this issue on develop HEAD as of 71bea49e48f1b81f5eeb36231ccbe02b497fbb9d. Also this breaks Markdown mode which tries to invoke `orgtbl-mode` and finds it void.

**Comment by jeremymeng** [comment]
> Also this breaks Markdown mode which tries to invoke `orgtbl-mode` and finds it void.

hit this too

**Comment by d12frosted** [comment]
@jeremymeng it's easy to reproduce, indeed. Thanks for pinging this issue.

I've created a PR addressing this issue. But please note, that one has to enable `org` layer in order to use `orgtbl-mode`.

**Comment by duianto** [comment]
The following PR is now on the `develop` branch:
[makrdown] use orgtbl-mode only when org layer is used #11560
