### ISSUE TITLE
How to add and configure evil-easymotion for spacemacs

### ISSUE THREAD

**Issue by casertap** [syl20bnr/spacemacs#6540]
I do not understand the configuration file very well.
Can you guys explain how to install and assign a keybinding to evil-easymotion?

so far I added this to my .spacemacs
````
dotspacemacs-additional-packages
   '(
     evil-easymotion
     )
````

**Comment by d12frosted** [comment]
Hey @casertap,

Adding `evil-easymotion` to `dotspacemacs-additional-packages` list just makes Spacemacs install that package, but configuration is left to you. Usually configurations go to `dotspacemacs/user-init` or `dotspacemacs/user-config` functions. Usually you want the second function unless it's clearly said in package readme that something must be set **before** package is loaded. So in general, when you want to install additional package you have to follow that package's readme file. Just skip the section when it says `package-install package-name <ret>` (or similar) as it's handled by adding package to `dotspacemacs-additional-packages`.

As per your situation, please refer to [evil-easymotion usage section](https://github.com/PythonNut/evil-easymotion#basic-usage). I am not evil user, so don't know which is the best key binding for that, but don't bind anything to `SPC` as it is evil leader by default in Spacemacs. 

And aside the general question of how to install and configure addition packages, I would like to point you to [Vim motions with avy](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#vim-motions-with-avy) section in Spacemacs documentation. This is not the same as `evil-easymotion`, but has some similarities (at least at the first glance).

**Comment by casertap** [comment]
Thanks @d12frosted 
I was interested to know in which section should I put 
```(evilem-define (kbd "SPC w") 'evil-forward-word-begin)``` ?
Is this biding a good choice ? A lot of other binding are available on SPC w so maybe not.
I did not found the functionality to jump to a particular word with avy. Maybe I am using it wrong.

**Comment by casertap** [comment]
Maybe I should define
```  (evilem-define (kbd "SPC e m") 'evil-motion-state-map) ``` 
but then SPC e m is undefined 
````
(defun dotspacemacs/user-config ()
  (evilem-define (kbd "SPC e m") 'evil-motion-state-map)
...
  (setq eclim-eclipse-dirs "/Users/pierrecaserta/java-mars/Eclipse.app/Contents/Eclipse/"
        eclim-executable "/Users/pierrecaserta/java-mars/Eclipse.app/Contents/Eclipse//eclim")
 ...
````

**Comment by casertap** [comment]
actually SPC-SPC-char is doing what I was looking for: https://github.com/syl20bnr/spacemacs/issues/6528
thanks

**Comment by d12frosted** [comment]
@casertap FYI, `SPC-SPC-char` was changed on develop 😸

**Comment by casertap** [comment]
@d12frosted what do you mean? this is a new feature?

**Comment by d12frosted** [comment]
No, I mean, it was remapped to `SPC j j char`

**Comment by casertap** [comment]
ok I am going to switch to the develop branch because I want to get the good habit of using ```SPC j j char``` as soon as possible.

**Comment by casertap** [comment]
just one more thing I switched to develop branch I hit ```SPC f t``` to open neotree and it says SPC f t is undefined
also I get
````
Warning (initialization): An error occurred while loading `/Users/pierrecaserta/.emacs.d/init.el':
File error: Cannot open load file, no such file or directory, f
````
with --debug-init I have
````
Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "f")
require(f)
...
````
I think I was too ambitious, master branch will be fine for me.

**Comment by d12frosted** [comment]
@casertap for that error see https://github.com/syl20bnr/spacemacs/issues/6523

**Comment by duianto** [comment]
An `evil-easymotion` layer has been added to Spacemacs:
vim][new layer] add evil-easymotion layer #13981

When the `evil-easymotion` layer has been added,
then the evil-easymotion key binding prefix is: `gs`
