### ISSUE TITLE
L-j not behaving as standard vim

### ISSUE THREAD

**Issue by michelrandahl** [syl20bnr/spacemacs#6541]
When pressing 'L' followed by 'j' I expect the cursor to go to the bottom of the visible portion of the buffer and then one line down. However, in spacemacs this does something crazy. It seems it goes to the bottom of the visible portion of the buffer and then several lines more down instead of just one. This behavior is super confusing.

Is it supposed to be like that or is it a bug?

**Comment by TheBB** [comment]
This has been fixed in develop.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
