### ISSUE TITLE
Javascript Layer: Support eslint auto fixing

### ISSUE THREAD

**Issue by samdesota** [syl20bnr/spacemacs#6546]
Maintaining a `.eslintrc` and `.jsbeautify` obviously isn't ideal, and since eslint has fixing it would be wonderful to have that supported alongside js beautify.

I already have it working via [this gist I threw together](https://gist.github.com/mrapogee/ae0674c6ba33025b1bd13e7d6561f76a)

The node script is needed since eslint's cli only supports fixing the actual files, not buffers/text.

I understand eslint is flycheck's thing, but I don't think flycheck will be supporting this anytime soon. Let me know if you think this is possible, thanks!

**Comment by istinspring** [comment]
How it's going?

**Comment by mrapogee** [comment]
@istinspring You can set it up yourself by adding the node script to your `$PATH` and copying the .spacemacs code to your user config, then fix with `SPC e e f`.

@syl20bnr Do you know how this would be implemented in the javascript layer and if you would accept a pull request?

**Comment by CarlQLange** [comment]
This would be amazing :)

**Comment by haishengwu-okta** [comment]
hi @mrapogee , what is `SPC e e f`? I didn't find at https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bcheckers/syntax-checking#key-bindings

**Comment by mrapogee** [comment]
https://gist.github.com/mrapogee/ae0674c6ba33025b1bd13e7d6561f76a

^-- I implemented it here. Haven't updated in a while so not sure if it's latest
