### ISSUE TITLE
Renaming from lowercase to uppercase doesn't work.

### ISSUE THREAD

**Issue by vimuel** [syl20bnr/spacemacs#6547]
#### Description
`rename-current-buffer-file` doesn't work when only changing case. Is this intended behaviour?

#### Reproduction guide
- Start Spacemacs
- Open `somefile.txt`
- Using [SPC f R] rename to `SomeFile.txt`

*Observed behaviour:*
Filename is still `somefile.txt`.

*Expected behaviour:*
Filename should get changed to `SomeFile.txt`.

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git haskell markdown org pandoc
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 syntax-checking version-control)
```

**Comment by cpaulik** [comment]
This works for me. Have you made sure that `somefile.py` is selected when pressing `RET` and not `SomeFile.py`. Helm will automatically select an existing file if it matches the search string.

**Comment by vimuel** [comment]
Yes, `SomeFile.txt` was selected. See screenshots below:
![Screenshot 1](https://raw.githubusercontent.com/vimuel/screenshots/master/spacemacs/20160701_spacemacs_1.png)
![Screenshot 2](https://raw.githubusercontent.com/vimuel/screenshots/master/spacemacs/20160701_spacemacs_2.png)
![Screenshot 3](https://raw.githubusercontent.com/vimuel/screenshots/master/spacemacs/20160701_spacemacs_3.png)
![Screenshot 4](https://raw.githubusercontent.com/vimuel/screenshots/master/spacemacs/20160701_spacemacs_4.png)

**Comment by TheBB** [comment]
This is an OS X issue. See https://github.com/syl20bnr/spacemacs/issues/6547

**Comment by vimuel** [comment]
My bad.

**Comment by nixmaniack** [comment]
Another point to note here is that if you use `ivy`, it lets you rename correctly(looks like it passes correct `dir` value to `read-file-name`). But with `helm` the issue persists and as explained in the referenced issue, if you pass correct value of `dir` to `read-file-name` it allows you to rename on OS X as well. We can patch that function for `'darwin`.

**Comment by vimuel** [comment]
@nixmaniack I'm not super confident on how to fix this myself yet. It'd be great if you patched this.

**Comment by d12frosted** [comment]
> Another point to note here is that if you use ivy, it lets you rename correctly(looks like it passes correct dir value to read-file-name). But with helm the issue persists and as explained in the referenced issue, if you pass correct value of dir to read-file-name it allows you to rename on OS X as well. We can patch that function for 'darwin.

Oh, that explains why I didn't notice such behaviour. When I was writing that function I hard-tested only ivy completion, while helm was tested briefly. Thanks for catching that.

**Comment by d12frosted** [comment]
@vimuel This is fixed on develop branch thanks to @nixmaniack

**Comment by vimuel** [comment]
@nixmaniack 👍 nice one
