### ISSUE TITLE
Changing the weight of the bold font

### ISSUE THREAD

**Issue by vimuel** [syl20bnr/spacemacs#6548]
This has been asked [before](./2087), but the answers didn't help me.

### Problem
I have a screen with a high pixel density and I had to change the default font weight of Source Code Pro to `light`, as the normal weight was giving me text overglow on the dark theme. The bold font is too bold and now the disparity between my default font weight and the bold is anything but subtle.

How do I change the weight of the bold font? (Bearing in mind that I am new to Emacs and Lisp.)

Example screenshot below
![Screenshot 1](https://raw.githubusercontent.com/vimuel/screenshots/master/spacemacs/20160701_spacemacs_1.png)

**Comment by TheBB** [comment]
You have to change the `:weight` attribute on all the faces that currently have it set to `bold`. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html and https://www.gnu.org/software/emacs/manual/html_node/elisp/Attribute-Functions.html#Attribute-Functions

**Comment by cpaulik** [comment]
Could it be a solution to just use `Source Code Pro Light` instead of changing the weight in emacs?

**Comment by vimuel** [comment]
OK, so I just made a version of Source Code Pro that uses the `light` weight as `regular` and `regular` for `bold` and I called it very creatively [space code pro](https://github.com/vimuel/space-code-pro). Just in case somebody else wants this as well.

@cpaulik Is this what you meant?

**Comment by cpaulik** [comment]
Yes. I had thought that using `Source Code Pro Light` as the default font would do that but I was wrong. So what you made makes a lot of sense.

**Comment by fsvehla** [comment]
@vimuel How did you make this variant? I want the same thing for SF UI :)

**Comment by vimuel** [comment]
@fsvehla I used [fontforge](http://fontforge.github.io/en-US/) and redefined the light version of the font as normal and the normal as bold. Does that make sense?

**Comment by fsvehla** [comment]
@vimuel It did, thanks!

**Comment by EarthCitizen** [comment]
@vimuel This worked perfectly for me! Thanks!

**Comment by liber145** [comment]
@vimuel It worked great! Many thanks!
