### ISSUE TITLE
 "Wrong number of arguments" on intero-repl-load #153 

### ISSUE THREAD

**Issue by elvis-sik** [syl20bnr/spacemacs#6549]
#### Description :octocat:
It seems intero's `haskell-repl-load` was updated and it isn't working any longer in spacemacs:

https://github.com/commercialhaskell/intero/issues/153

#### Reproduction guide :beetle:
- Start Emacs
- Create new Haskell stack project with `stack new foobar`
- Open some `.hs` file in Spacemacs
- Wait for messages of intero being installed and booted up, then buffer shows up
- `SPC m s b` or `M-x intero-repl-load`

*Observed behaviour:* :eyes: :broken_heart:
The following error occurs:
```(wrong-number-of-arguments (lambda (f) (let ((buffer (current-buffer))) (funcall f) (pop-to-buffer buffer))) 2)```

*Expected behaviour:* :heart: :smile:
I expected the buffer would be sent to a repl.

#### System Info :computer:
- OS: Arch
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. f1247c8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv auto-completion better-defaults emacs-lisp git markdown
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
     spell-checking smex syntax-checking version-control cscope gtags semantic xkcd github
     (c-c   :variables c-c  -default-mode-for-headers 'c-mode c-c  -enable-clang-support t)
     extra-langs html javascript shell-scripts sql yaml
     (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save t)
     ipython-notebook
     (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "gibiansky" haskell-enable-shm-support t haskell-completion-backend 'intero)
     evil-commentary django
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-repeat-scope "visible")
     react idris agda scheme ranger selectric evil-cleverparens speed-reading pdf-tools asm octave)
```

#### Backtrace :paw_prints:
```
    Debugger entered--Lisp error: (wrong-number-of-arguments (lambda (f) (let ((buffer (current-buffer))) (funcall f) (pop-to-buffer buffer))) 2)
      haskell-intero//preserve-focus(#[(

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/6550 should fix it.

**Comment by d12frosted** [comment]
Hey @elvis-sik,

Thanks to @TheBB this is fixed in develop branch. Please update and have fun with `intero` 😸 

P. S. Since this problem is not on master, closing this issue.
