### ISSUE TITLE
'helm-hoogle' package used in spacemacs doesn't return any result

### ISSUE THREAD

**Issue by korayal** [syl20bnr/spacemacs#6551]
There are two different `helm-hoogle` modules on the web, one at [melpa](https://elpa.zilongshanren.com/melpa/helm-hoogle-20150919.32.el) and another one at [github](https://github.com/markus1189/helm-hoogle). We are using the former on spacemacs. But that one seems to only get the results that contain `--` characters which seems to not exist in [Hoogle 5.0](https://github.com/ndmitchell/hoogle)

I managed to make it work replacing the characters `--` with `::` since most of my queries contain them, but that's basically a workaround.

**Comment by d12frosted** [comment]
To be fair, on GitHub there are several implementations of `helm-hoogle`. The one that is on MELPA is implemented by [jwiegley](https://github.com/jwiegley/helm-hoogle). The other you linked is implemented by [markus1189](https://github.com/markus1189/helm-hoogle). 

Any way, I don't understand your problem. I tried hoogling `:: (a -> b) -> f a -> f b)` and it worked with plain `hoogle` and `helm-hoogle`.

<img width="908" alt="screenshot 2016-07-12 11 22 17" src="https://cloud.githubusercontent.com/assets/6507913/16760124/fcabf9ec-4822-11e6-96b4-9f950d6529f7.png">

Whenever I try hoogling `-- a -> b` it gives me no results. 

So could you please be more specific and share repo steps with expected result and actual result?

**Comment by korayal** [comment]
This was working alright with me before too. But I think it doesn't work with Hoogle 5.0. What version are you using for hoogle?

the issue is with the `helm-c-hoogle-set-candidates` function in the [melpa version](https://elpa.zilongshanren.com/melpa/helm-hoogle-20150919.32.el)

Basically what this module does is running command `hoogle search -l -n 100 <keywords>` and checking the output if there is any line that matches the regex `\\(.+?\\) -- \\(.+\\)` (basically any line that have two  set of words separated by `--`)

But when I run the same command in the command prompt, I don't see module names or the `--` separator:
![image](https://cloud.githubusercontent.com/assets/313801/16761677/d6e283fa-4829-11e6-879e-63e1a108ef45.png)

**Comment by d12frosted** [comment]
Ah I see. It's related to new version of Hoogle, which is not available via `stack`. Anyway, it should be fixed upstream. Be it in Hoogle itself or `helm-hoogle`.

For me described command returns following output.
```
[15:17:15] ~
λ hoogle -l -n 200 ":: (a -> b) -> f a -> f b"
Data.Traversable fmapDefault :: Traversable t => (a -> b) -> t a -> t b -- http://hackage.haskell.org/packages/archive/base/latest/doc/html/Data-Traversable.html#v:fmapDefault
Prelude fmap :: Functor f => (a -> b) -> f a -> f b -- http://hackage.haskell.org/packages/archive/base/latest/doc/html/Prelude.html#v:fmap
Data.Functor fmap :: Functor f => (a -> b) -> f a -> f b -- http://hackage.haskell.org/packages/archive/base/latest/doc/html/Data-Functor.html#v:fmap
Control.Monad fmap :: Functor f => (a -> b) -> f a -> f b -- http://hackage.haskell.org/packages/archive/base/latest/doc/html/Control-Monad.html#v:fmap
Control.Monad.Instances fmap :: Functor f => (a -> b) -> f a -> f b -- http://hackage.haskell.org/packages/archive/base/latest/doc/html/Control-Monad-Instances.html#v:fmap
Data.Functor (<$>) :: Functor f => (a -> b) -> f a -> f b -- http://hackage.haskell.org/packages/archive/base/latest/doc/html/Data-Functor.html#v:-60--36--62-
Control.Applicative (<$>) :: Functor f => (a -> b) -> f a -> f b -- http://hackage.haskell.org/packages/archive/base/latest/doc/html/Control-Applicative.html#v:-60--36--62-
Control.Applicative liftA :: Applicative f => (a -> b) -> f a -> f b -- http://hackage.haskell.org/packages/archive/base/latest/doc/html/Control-Applicative.html#v:liftA
Control.Monad liftM :: Monad m => (a1 -> r) -> m a1 -> m r -- http://hackage.haskell.org/packages/archive/base/latest/doc/html/Control-Monad.html#v:liftM
```

P. S. Thanks for reporting it to Hoogle issue tracker!

**Comment by korayal** [comment]
It seems `stack` [will also include](https://gist.github.com/chrisdone/78c1c1c052a853697cf3b902de086172) hoogle command. And it will be Hoogle 5.

Btw, the issue with the CLI command is already fixed in the upstream. And it's now working nicely on my end.

**Comment by ndmitchell** [comment]
Thanks for noting the bug, and the details. I reproduced and made Hoogle 5 match the output in the case you seem to care about. In future, if there are any bugs around Hoogle integration do feel free to mention me.

**Comment by d12frosted** [comment]
@ndmitchell thank you for the quick fix! Much appreciated 💯
