### ISSUE TITLE
Eyebrowse workspaces and layouts interaction bug

### ISSUE THREAD

**Issue by GreyGhostIX** [syl20bnr/spacemacs#6552]
#### Description
Eyebrowse workspaces and layouts interact incorrectly. Each layout doesn't have an independent set of workspaces. If you use eyebrowse and layouts in conjunction you start to see the workspaces become unordered, and the layouts share buffers with eachother. 

#### Reproduction guide
- Start Emacs.
- Open *scratch* buffer. `SPC b b scratch ret`
- Switch to workspace 2. `SPC l w 2`
- Open *messages* buffer. `SPC b b mess RET`
- Open new layout. `SPC l 2` then `y new RET`
- Swtich to workspace. 1 `SPC l w 1`
- Open *messages* buffer. `SPC b b mess RET`
- Switch to layout 1. `SPC l 1`

*Observed behaviour:*
- Upon creation of the second layout, started on workspace 2 (the current workspace when creating the new layout).

-  Now layout 1 workspace 1 contains *messages* instead of *scratch*. Also, layout 1 workspace 2 now contains *spacemacs*.

*Expected behaviour:*
- On creating new layout, should start on workspace 1.

- Layout 1 workspace 1 should contain *scratch*. Also, layout 1 workspace 2 should cointain *messages*.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx
 (org :variables org-pretty-entities t org-bullets-bullet-list
      '("○"))
 (version-control :variables version-control-diff-tool 'diff-hl)
 (git :variables git-magit-status-fullscreen t)
 (shell :variables shell-default-shell 'multi-term)
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 dash vinegar ibuffer syntax-checking eyebrowse c-c   csharp emacs-lisp vimscript markdown yaml html javascript)
```

**Comment by bmag** [comment]
Thanks for the report. I'll check this bug when I have time, which is probably next week.

**Comment by bmag** [comment]
I tried to reproduce the bug your describing, and I couldn't. I'm experiencing the expected behavior.

@GreyGhostIX your system info says that you're using develop branch, but the revision hash links to release 0.105.21. What branch are you using, and do you experience the same bug in latest develop branch?

For reference, here's my system info: (I'm running on develop)
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.0.95.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 6fb7adf)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.5 auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip t company-tooltip-align-annotations t)
 emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 markdown org
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control
 (latex :variables latex-enable-auto-fill t latex-enable-folding t)
 pdf-tools evil-cleverparens python command-log smex themes-megapack c-c++
 (clojure :variables clojure-enable-fancify-symbols nil)
 ruby common-lisp ibuffer octave imenu-list window-purpose nameless
 (theming :variables theming-modifications
          '((spacemacs-dark
             (aw-leading-char-face :foreground "red" :height 3.0))
            (spacemacs-light
             (aw-leading-char-face :foreground "red" :height 3.0))
            (monokai
             (aw-leading-char-face :foreground "red" :height 3.0))
            (flatland
             (aw-leading-char-face :foreground "red" :height 3.0)))))
```

**Comment by GreyGhostIX** [comment]
Thanks for the quick response!

Everything had been working on the develop branch until I updated and switched to master yesterday.

I did a clean install of my emacs.d on master with the default .spacemacs template except for the addition of the `eyebrowse` layer, and I'm still getting the same strange behavior. I'll check it out on develop next.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp eyebrowse)
```

**Comment by GreyGhostIX** [comment]
When I switch to develop with `git checkout origin/develop` I'm getting:
`Warning (initialization): An error occurred while loading `/Users/NAME/.emacs.d/init.el':
File error: Cannot open load file, no such file or directory, f`.
This breaks everything so I can't test the original issue.

As some backstory, I also got this error when I updated my develop branch originally with `git pull --rebase`, prompting me to switch to master (not sure why it said I was on develop in my first post), and discover my layout issue.

I'll check out issue #6523 and see if that workaround will work for me.

**Comment by GreyGhostIX** [comment]
SUCCESS. Everything works great on develop. This may still be an issue for people using master though. Shall i close the issue?

Thanks for the help!

**Comment by TheBB** [comment]
That's up to you. If there are bugs in master that are fixed in develop, chances are there are open issues about them already, although I haven't checked this one in particular.

**Comment by GreyGhostIX** [comment]
You are correct, issue #5871 seems to describe the same problem. I don't know how I didn't notice that one before I opened this issue. Sorry for the duplicate.

**Comment by syl20bnr** [comment]
Seems I did not back port it, will do soon, thank you for the reminder.

**Comment by igoralmeida** [comment]
FYI,

I cherry-picked a few commits into master (looked for commits in develop that touched `layers/+spacemacs/spacemacs-layouts/`), but after fixing a few minor conflicts I get an error that `spacemacs-layouts-directory` does not exist during persp-init.
