### ISSUE TITLE
status bar (deface)

### ISSUE THREAD

**Issue by jnreynoso** [syl20bnr/spacemacs#6557]
![bottom-bar](https://cloud.githubusercontent.com/assets/8073456/16752677/1fa4852e-47a9-11e6-815a-3f0f57cf2b69.png)

My status-bar seems to be superposed.

Information:
 - Emacs 24.4.1.
 - Ubuntu 16.04 LTS.
 - Branch Master.

**Comment by NJBS** [comment]
See http://spacemacs.org/doc/FAQ.html#orgheadline8

**Comment by jnreynoso** [comment]
thank you very much, I just had to alter powerline-scale (1.3)

**Comment by NJBS** [comment]
Great! :smile: 

If you feel that your problem has been solved feel free to close this issue.
