### ISSUE TITLE
improve avy highlighting in terminal with standard spacemacs theme

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#6564]
I'm using avy with `SPC SPC`.

right now it's very hard to see the right sequence that the user needs to hit. Sample below:

<img width="970" alt="screen shot 2016-07-13 at 2 05 16 am" src="https://cloud.githubusercontent.com/assets/8352747/16792385/577eec6e-489e-11e6-9fca-7ddc718ca016.png">

**Comment by NJBS** [comment]
This should probably be reported to the [spacemacs-theme](https://github.com/nashamri/spacemacs-theme) package directly.

**Comment by ninrod** [comment]
Ok I've also open an issue [upstream](https://github.com/nashamri/spacemacs-theme/issues/54).

**Comment by ninrod** [comment]
Hi @TheBB. It seems that upstream has fixed the issue. But I'd have to test it yeat because I'm wating for MELPA to update. ref: https://github.com/nashamri/spacemacs-theme/issues/54
