### ISSUE TITLE
Slowness opening ruby files

### ISSUE THREAD

**Issue by AshtonKem** [syl20bnr/spacemacs#6569]
#### Description :octocat:

Opening ruby buffers is very slow. I first noticed general slowness on master (latest release) opening both Ruby and Clojure files. I decided to try out develop but it turns out to be way worse. 

Currently I'm seeing 8  seconds to open up a ruby file, either via helm-projectile, helm-find-file, or even magit. 
#### Reproduction guide :beetle:
- Start Emacs
- Navigate to a ruby project
- Use helm-projectile to pick an arbitrary ruby file
- Wait

_Observed behaviour:_ :eyes: :broken_heart:
- 5 seconds before RVM message appears
- "Not enabling jit-lock: it does not work in indirect buffer" message
- 2  second pause
- File renders

_Expected behaviour:_ :heart: :smile:
Near instantaneous rendering.
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 304e338)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(ansible auto-completion clojure csv emacs-lisp git haskell html java javascript nginx ruby ruby-on-rails markdown osx
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         spell-checking ibuffer version-control yawl)
```

I grabbed a profile snapshot if it's helpful.

**Comment by TheBB** [comment]
How fast is the second ruby file?

**Comment by AshtonKem** [comment]
Updates:

Master seems affected as well, but the total time to open is 4-5s instead of ~8. 

Here are the speeds I'm observing on Develop

- First file: 8s
- Second file: 8s
- Helm autocomplete speed: faster than I can count
- Switching to previously opened ruby buffer: 0.5s
- Reopening previously opened file: 8s


For the record: when switching between branches I've been using the following procedure, just in case I'm doing something wrong.

1. Close Emacs
2. ```git clean -fdx``` in ~/.emacs.d
3. ```git co develop```
4. ```git pull```
5. Open Emacs
6. Rerun tests after packages have been installed

**Comment by AshtonKem** [comment]
Clicked the wrong button and closed the issue on accident, apologies.

**Comment by AshtonKem** [comment]
This appears to really only affect my OSX machine. 

--
Ashton

**Comment by AshtonKem** [comment]
This behavior seems to be getting worse. I'm counting up to 12-18s to load a single ruby file or the latest develop branch along with the latest packages installed.

**Comment by d12frosted** [comment]
Sorry to hear that.

What version of Emacs are you using? And how did you install it?

**Comment by AshtonKem** [comment]
Emacs 25.1.1, installed via homebrew.

A clean .spacemacs file completely eliminates the problem. I'm going to slowly add layers back in to figure out where the problem came from.

**Comment by AshtonKem** [comment]
Got it! 

One of the following bits of code will cause problems on my machine:

```
(ruby :variables ruby-version-manager 'rvm)
```

```
  (add-hook 'ruby-mode-hook
            (lambda () (rvm-activate-corresponding-ruby)))
```

I accidentally had both lines added, but one or the other is sufficient to cause problems on my machine.

I'm currently running rvm 1.27.0, along with the following relevant emacs packages.

```
rvm-20150402.742
inf-ruby-20170115.1602
ruby-test-mode-20160930.9
ruby-tools-20151209.815
chruby-20161222.430
```

**Comment by d12frosted** [comment]
I am not familiar with ruby and rvm. Does it take long to execute `rvm-activate-corresponding-ruby`? I mean, if this function takes too long, than it's a bad idea to put it into `ruby-mode-hook` (which is fired every time `ruby-mode` is enabled, for example when you open a ruby file).

**Comment by AshtonKem** [comment]
It looks like ```rvm-activate-corresponding-ruby``` is extremely slow, about 7s or slower, although for the life of me I have no idea why. This feels like an upstream issue to me.

**Comment by RomanKapitonov** [comment]
Potentially duplicated by https://github.com/syl20bnr/spacemacs/issues/9299

**Comment by d12frosted** [comment]
@RomanKapitonov thanks for noticing.

Let's close this old one in favour of #9299 as the latter is more transparent. 

Anyways, @AshtonKem thanks for details you shared here. If you have a working solution for this (apart from just removing that hook), it would be really great!

**Comment by jdelStrother** [comment]
@AshtonKem it might be worth timing `rvm use 2.3.3` (or whatever version you're using) in your shell to see if you can narrow down the problem.  Mine was taking > 2.5s, much of which was in `__rvm_setup_utils_functions_common` - turned out to be that `npm-which` had snuck into my path, making `which` far slower than usual.
