### ISSUE TITLE
markdown mmm scala

### ISSUE THREAD

**Issue by wookietreiber** [syl20bnr/spacemacs#6571]
#### Description

I am using the markdown layer and have a markdown file containing Scala code. I would like to have syntax highlighting for the Scala code blocks. I guess this can be done with **mmm**.

I checked the **mmm-mode** via <kbd>SPC</kbd> <kbd>h</kbd> <kbd>SPC</kbd> and Scala is missing from `mmm-add-classes`.

Also, I don't know and cannot find any documentation about how to enable **mmm** within the **markdown layer**.
#### Reproduction guide
- Start Emacs
- open a markdown file with Scala code blocks

_Observed behavior:_
- Scala code blocks are colored uniformly 

_Expected behavior:_
- Scala code blocks are colored with Scala-specific syntax highlighting
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp git lua markdown scala)
```

**Comment by TheBB** [comment]
> Also, I don't know and cannot find any documentation about how to enable mmm within the markdown layer.

It's enabled, you just need to add scala to the list.

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/markdown/packages.el#L159-L208

**Comment by wookietreiber** [comment]
@TheBB Am I supposed to or not to edit this file as a user? I thought I was only supposed to edit the `~/.spacemacs` file.

**Comment by crshd** [comment]
@wookietreiber No, you're not. But you can put `mmm-add-class` and `mmm-add-mode-ext-class` in your `~/.spacemacs`, too.

**Comment by TheBB** [comment]
@wookietreiber I was suggesting you make a pull request with this contribution, but @crshd beat you to it.

**Comment by wookietreiber** [comment]
@crshd To which section? `dotspacemacs/user-init`?

@TheBB Yeah, sure :-) I would contribute, too, but I'm not that well versed yet with spacemacs to feel comfortable enough.

**Comment by TheBB** [comment]
You can't do it in user-init, mmm won't be available that soon. As a rule, the only thing you can do there is to set variables.

**Comment by crshd** [comment]
Nope, but in `dotspacemacs/user-config`.

**Comment by wookietreiber** [comment]
Ok, I tested this: my `dotspacemacs/user-config` now looks like this:

```lisp
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
  (mmm-add-classes '((markdown-scala
                      :submode scala-mode
                      :face mmm-declaration-submode-face
                      :front "^```scala[\n\r]+"
                      :back "^```$")))
  (mmm-add-mode-ext-class 'markdown-mode nil 'markdown-scala)
  )
```

[This is the file I'm editing](https://raw.githubusercontent.com/eva4s/eva4s-book/master/src.scala.md). I hit <kbd>,</kbd> <kbd>c</kbd> <kbd>s</kbd> and there is a message in the bottom status bar:

```
Symbols value as variable is void: ensime-mode-key-prefix.
```

The code is not highlighted. Apparently, this does not work for non-ensime projects (ensime is sort of an IDE for Scala in emacs which gets loaded with scala-mode).

Is there a way to disable ensime for the Scala mode **only within** mmm?

---

I tested the same with a Python code block and syntax highlighting works there and the message in the status bar reads:

```
MMM-ifying buffer...done
```

**Comment by crshd** [comment]
Possibly related to #6578 

I'm not sure about disabling ensime for mmm-mode, but `(require 'ensime)` in you `dotspacemacs/user-config` seems to fix this problem temporarily.

Since I don't know Scala (or ensime, for that matter), I cannot say if this will break other things, but it _does_ make the highlighting work.

**Comment by wookietreiber** [comment]
I can confirm adding `(require 'ensime)` to `dotspacemacs/user-config` works.
