### ISSUE TITLE
Error when installing package

### ISSUE THREAD

**Issue by vimuel** [syl20bnr/spacemacs#6572]
#### Description
An error occurred while installing emoji-cheat-sheet-plus (error: (cl-assertion-failed (or (= (buffer-size tar-data-buffer) (buffer-size)) (eq tar-data-swapped (> (buffer-size tar-data-buffer) (buffer-size))))))

#### Reproduction guide
- add emoji to layers
- Start Emacs

I get this same error with other packages as well. What am I doing wrong?

#### System Info
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp emoji git haskell markdown org pandoc
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 syntax-checking version-control)
```

#### Messages
(Spacemacs) --> refreshing package archive: melpa... [1/3]
Contacting host: melpa.org:443
Failed to download ‘melpa’ archive.
(Spacemacs) --> refreshing package archive: org... [2/3]
Contacting host: orgmode.org:80 [2 times]
(Spacemacs) --> refreshing package archive: gnu... [3/3]
Contacting host: elpa.gnu.org:443
Failed to download ‘gnu’ archive.
(Spacemacs) --> installing package: emoji-cheat-sheet-plus@emoji... [1/1]
Contacting host: melpa.org:443
Parsing tar file...done
smooth-scrolling enabled.
Spacemacs is ready.

**Comment by TheBB** [comment]
You probably just got a corrupted download. Clear packages, try again, possibly disable HTTPS, the usual.

**Comment by vimuel** [comment]
@TheBB How do I clear packages?

**Comment by vimuel** [comment]
I just noticed that `company-emoji.el` and `.elc` are both empty.

**Comment by TheBB** [comment]
You delete the folder(s) from .emacs.d/elpa

**Comment by vimuel** [comment]
Yes, I worked that out, but I still get the same error when trying to reinstall. Same when I use `emacs --insecure`.

**Comment by vimuel** [comment]
OK, so this seems to be an issue with emacs 25. Have reinstalled with latest stable and issue is gone.
