### ISSUE TITLE
File mode specification error: (void-variable ensime-mode-key-prefix)

### ISSUE THREAD

**Issue by reactormonk** [syl20bnr/spacemacs#6578]
#### Description :octocat:

File mode specification error: (void-variable ensime-mode-key-prefix)
And no modeline
#### Reproduction guide :beetle:
- Start Emacs
- Open a .scala file

_Observed behaviour:_ :eyes: :broken_heart:
In the messages buffer: File mode specification error: (void-variable ensime-mode-key-prefix)
And no modeline displayed

_Expected behaviour:_ :heart: :smile:
No error and a modeline
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 5c371f0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp git org syntax-checking version-control scala deft themes-megapack ansible ess haskell idris nim javascript github evil-snipe markdown chrome c-c  )
```

_Futher information:_

https://gitter.im/ensime/ensime-emacs?at=5787737be4375c9212d1835b

**Comment by bmag** [comment]
@agboom this is the same error message you had a while ago. Were you able to fix it? (https://gitter.im/syl20bnr/spacemacs?at=577a2e585c023e194f7722ac)

@reactormonk until this is resolved, does adding `(require 'ensime)` to your `dotspacemacs/user-config` work as a work-around?

**Comment by reactormonk** [comment]
@bmag Yes, that fixes the error.

**Comment by agboom** [comment]
@bmag I worked around it by adding `(require 'ensime')` to the user-config
