### ISSUE TITLE
Inconsitent bindings in some minibuffers

### ISSUE THREAD

**Issue by bjarkevad** [syl20bnr/spacemacs#658]
I'm not sure if this is intended or not, but there are some inconsitencies when using mini-buffers.
For example when using `ido-find-file` on `spc f f`, `C-h` goes up a level, where as in `helm-find-files`, `C-l` goes up a level.
Is this something that should be worked on making consitent across buffers of this type?

This might be related to #652

**Comment by syl20bnr** [comment]
I agree, both should be the same.

**Comment by TheBB** [comment]
This is fixed now.
