### ISSUE TITLE
Delete packages on startup rather than before restarting 

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#6583]
Deleting packages when doing "Update Packages" in running instance of emacs may render emacs unusable. 

Reference: https://github.com/syl20bnr/spacemacs/issues/4127#issuecomment-226769130

Created this issue for tracking with clear issue description so that someone can try to fix it.

**Comment by cpaulik** [comment]
There were problems with this approach but I can not find the discussion at the moment. Maybe it is enough to make it even clearer that emacs has to be restarted. Or maybe change the Button to `Update and Restart`?

**Comment by nixmaniack** [comment]
After package update it does mention that you have to restart emacs. But yes, making it mandatory to restart after updating packages might be a better option

**Comment by CestDiego** [comment]
I think this is the way to go, I end up restarting anyway, there should be a direct action to restart when updating,

**Comment by nixmaniack** [comment]
There's just one possibility of `restart` failing in case the `restart-emacs` package is updated in the process because it gets deleted.

**Comment by syl20bnr** [comment]
I like this approach, but we have to do it manually, i.e. _before_ initializing `package.el`.

**Comment by Stebalien** [comment]
> I like this approach

I assume "this" is "delete on start"?

---

Regardless, would you consider the following instead of simply deleting? It would be nice to have atomic updates that are automatically rolled back on failure.

1. When an update is requested, record the intended update (which packages are being updated) in a file (`update.el`).
2. Early after restarting (before initializing anything)...
3. If `update.el` exists:
    1. Load `update.el`.
    2. Move it to `partial-update.el`
    3. Move the to-be-updated packages to `~/.emacs.d/elpa-backup/`.
    4. Continue loading and perform the update.
    6. Delete `partial-update.el`.
    5. Delete `~/.emacs.d/elpa-backup/`.
4. If `partial-update.el` exists:
    1. Load it.
    2. Delete the packages listed in it from `~/.emacs.d/elpa` (roll back the update).
    3. Move all packages from `~/.emacs.d/elpa-backup/` to `~/.emacs.d/elpa/`.
    4. Delete `partial-update.el`.
    5. Delete `~/.emacs.d/elpa-backup/`.
    6. Load as usual.
    7. Inform the user that an update was aborted.
4. Otherwise, delete `~/.emacs.d/elpa-backup/` if it exists.

**Comment by JonasDralle** [comment]
`restart-emacs` updated successfully. Now how to I restart 😆

**Comment by nixmaniack** [comment]
This is still valid today. Leave this open!

**Comment by syl20bnr** [comment]
I'm not sure that doing it after startup is any better. The only way to safely update an Emacs instance and get the expected state is to restart Emacs with the new version of the packages code.

We cannot predict how the state will mutate when we bunch update the packages.
