### ISSUE TITLE
Deleting left of empty smartparen pair doesn't delete right when hungry-delete is enabled

### ISSUE THREAD

**Issue by andrew-christianson** [syl20bnr/spacemacs#6584]
#### Description :octocat:

Deleting left of empty smartparen pair doesn't delete right when hungry-delete is enabled
#### Reproduction guide :beetle:
- Start Emacs
- enable hungry delete mode globally
- Enter a matched pair e.g. `()`
- Delete the left of the pair in insert mode

_Observed behaviour:_ :eyes: :broken_heart:
matching part of pair isn't deleted. For example, where `|` is the cursor, we're starting with `(|)` and pressing backspace.  We're left with `|)`

_Expected behaviour:_ :heart: :smile:
The above should (and indeed does, if hungry-delete is disabled), delete the right paren, leaving nothing.
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. b23cfa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm ansible
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-tab-key-behavior 'cycle auto-completion-return-key-behavior 'complete auto-completion-enable-snippets-in-popup t)
      agda better-defaults
      (c-c   :variables c-c  -enable-clang-support t)
      (clojure :variables clojure-enable-fancify-symbols t)
      common-lisp colors csv dash docker
      (elfeed :variables rmh-elfeed-org-files
              (list "~/.spacemacs.d/settings/elfeed.org"))
      emacs-lisp ess elm elixir extra-langs evil-commentary evil-cleverparens
      (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
      finance git
      (geolocation :variables geolocation-enable-osx-location-service-support t geolocation-enable-weather-forecast t geolocation-enable-automatic-theme-changer nil)
      go gtags html idris imenu-list
      (ibuffer :variables ibuffer-group-buffers-by 'projects)
      jabber javascript java
      (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "chris-done")
      latex markdown
      (org :variables org-enable-github-support t org-enable-reveal-js-support t)
      osx pandoc purescript python
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      racket restclient ruby rust scala scheme search-engine semantic shell-scripts spotify
      (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t)
      sql syntax-checking systemd terraform theming vagrant vim-empty-lines-mode version-control windows-scripts)
```

**Comment by d12frosted** [comment]
This is due the fact that enabling `hungry-delete-mode` [overrides](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+spacemacs/spacemacs-editing/packages.el#L167) `backspace` from `smart-ops-backspace` to `hungry-delete-backwards`. So this is entirely different function that doesn't know anything about smart-parens.

I am not sure what is the best way to resolve this issue, but I believe that this should be reported upstream to `smart-parens` to make it play nice with `hungry-delete-mode`. 

But on other hand, it doesn't really fit `smart-parens`. So probably it would be better to avoid mixing `smart-paren` and `hungry-delete-mode` under one key binding. 

So let's wait for others to share their thoughts on this matter.

Oh, and I would like to invite @Fuco1 here. If you need more context on this problem, just let me know 😸

**Comment by ShineFan** [comment]
add 
`(defadvice hungry-delete-backward (before sp-delete-pair-advice activate)
    (save-match-data
      (sp-delete-pair (ad-get-arg 0))))` 
to dotspacemacs/user-config work for me
Thank @Fuco1

**Comment by Fuco1** [comment]
Thanks for testing this out.  Would you mind a pull request into SP? I think this wouldn't hurt to have support in the "core" :)

**Comment by sebhahn** [comment]
Any updates on this matter?

**Comment by Fuco1** [comment]
@sebhahn Did you try it?  As far as I remember someone made a patch to smartparens to integrate it with hungry-delete.

**Comment by sebhahn** [comment]
it works with the function provided by @ShineFan

**Comment by Fuco1** [comment]
Someone fixed this two years ago in commit https://github.com/Fuco1/smartparens/commit/df16b4824ee3e5325af72870e0b4d1470a0302ab

It should therefore work with latest SP.

**Comment by sebhahn** [comment]
True, thanks!

**Comment by njunxuan** [comment]
I am experiencing the same issue when using hungry mode on the latest smartparens. Currently using the advice as a work around.
