### ISSUE TITLE
Cannot find layer perspectives

### ISSUE THREAD

**Issue by tieubao** [syl20bnr/spacemacs#6589]
#### Description
I installed Spacemacs yesterday and when I run `[SPC f e R] I cannot find layer perspectives.

<img width="1372" alt="screen shot 2016-07-15 at 10 14 27 am" src="https://cloud.githubusercontent.com/assets/1749624/16862630/571da368-4a75-11e6-83c6-40bc636b5b59.png">

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion perspectives emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking colors themes-megapack osx erlang elixir elm javascript shell-scripts yaml html dockerfile dash tmux)
```

**Comment by NJBS** [comment]
Well, `perspectives` isn't  layer. Are you looking for the [eyebrowse](http://spacemacs.org/layers/+window-management/eyebrowse/README.html) or [spacemacs-layouts](http://spacemacs.org/layers/+window-management/spacemacs-layouts/README.html) layers?

**Comment by tieubao** [comment]
oh, i found the link: https://github.com/syl20bnr/spacemacs/blob/6eab954afecb4af81aa29916deaa5c1cd332bcb9/layers/%2Bwindow-management/perspectives/README.org#key-bindings

Can help to explain more?

**Comment by NJBS** [comment]
That is now the [spacemacs-layouts](http://spacemacs.org/layers/+window-management/spacemacs-layouts/README.html) layer, you are viewing a very old commit so it does not reflect the current layers available on the `master` branch.

**Comment by tieubao** [comment]
Oh I see. Thanks for the help.
