### ISSUE TITLE
Symbol's function definition is void: dired-jump

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#659]
It seems like `dired-x` is not loaded when the command is executed.

**Comment by bjarkevad** [comment]
How do you reproduce the issue? `SPC f j` seems to work fine for me.

**Comment by tuhdo** [comment]
I tried with freshly installed Spacemacs.

**Comment by sooheon** [comment]
I've had similar messages "Symbol's function definition is void: foo", which deleting the elpa directory and letting spacemacs initialise again has fixed.

**Comment by syl20bnr** [comment]
@tuhdo do you still have this issue ?

**Comment by tuhdo** [comment]
I still have. Latest Spacemacs master branch.

**Comment by tuhdo** [comment]
Ops you have just updated to 0.64. I will try it again.

**Comment by tuhdo** [comment]
It is fixed. Thanks.
