### ISSUE TITLE
haskell: swap keys for stylish-haskell and hindent

### ISSUE THREAD

**Issue by ljli** [syl20bnr/spacemacs#6591]
I use hindent much more than stylish-haskell. I imagine that is quite common. Therefore it makes sense to me to have the slightly simpler `, f` for hindent and `, F` for stylish-haskell. Currently it's the other way around. I recognize this is pretty minor, but if no one objects I could just make a PR and we are done with it. I also think stylish-haskell could in principle be subsumed by hindent or one key could just do both (that is if the user wants both). The change seems beneficial anyway.

**Comment by d12frosted** [comment]
Hey @ljli,

Yeah, it really makes sense. I never use `, f`, but time to time I do use `, F`. So PR is warmly welcome.
