### ISSUE TITLE
Paste within tmux got extra control characters

### ISSUE THREAD

**Issue by dingmingxin** [syl20bnr/spacemacs#6595]
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description

I use emacs(daemon mode: `emacsclient -t -a ''`)with tmux. Here is my [tmux.conf](https://gist.github.com/dingmingxin/ffbc811bdc06ba448c790ba8c9ba126f)
When copy some thing into system paste-board, and paste into emacs(int tmux) using `CMD-V`.
The content I pasted become to this:
`200~content.....content~`
#### Reproduction guide
- Start tmux
- Start Emacs in tmux
- Copy something from webbrower into system pasteboard
- Paste content to Emacs

_Observed behaviour:_
The content was wraped with `200~...~`

_Expected behaviour:_
Content with no extra control characters.
#### System Info
- OS: darwin(10.11.4)
- Emacs: 24.5.1
- Zsh 5.0
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults git markdown org javascript ycmd c-c   swift php html java python emacs-lisp vimscript shell-script go yaml search-engine tmux games dash shell-scripts
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 dmx dmx-lua)
```
#### Debug

I look into spacemacs layers and found this in `layers/+distribution/spacemacs/packages.el`

``` elisp
(defun spacemacs/init-bracketed-paste ()
  (use-package bracketed-paste
    :defer t
    :init
    ;; Enable bracketed-paste for tty
    (add-hook 'tty-setup-hook 'bracketed-paste-enable) 
    ))
```

When I comments this line: `(add-hook 'tty-setup-hook 'bracketed-paste-enable)` and restart emacs the pasting problem has gone. 

Then I switch to bash and restart emacs without comment any layer code. The problem still exist. I think this has nothing to do with $SHELL evrionment. 

If I using emacs just in Terminal.app  without tmux, everthing is fine. 

How to solve the problem, is there some way to make tmux and emacs work well ?

**Comment by bauerd** [comment]
Did you find a solution for this? I roll my own emacs configuration and since today my clipboard contents get wrapped with `200~[Clipboard contents]\n201~`. I have no clue why this is happening since I only made very minor changes to my emacs config, none to my tmux config.
