### ISSUE TITLE
New user key bindings

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#660]
Hi, stupid question number 1 :)

How should I define new bindings ? I assume under SPC o ?

In the dotspacemacs file ?

Could someone point me at the docs that I'm obviously can't see.

Thanks
Graham

**Comment by bjarkevad** [comment]
I do it like this in `dotspacemacs/config`:
```elisp
  (evil-leader/set-key
    "ox" 'interactive-function
    )
```
which would create a binding under `SPC o x`, running the interactive function `interactive-function`.

**Comment by fatlazycat** [comment]
Thanks
