### ISSUE TITLE
`tern-reparse-on-idle': (wrong-type-argument stringp 110)

### ISSUE THREAD

**Issue by elvis-sik** [syl20bnr/spacemacs#6601]
#### Description :octocat:
I leave a `.js` buffer untouched for some time:

    Error running timer `tern-reparse-on-idle': (wrong-type-argument stringp 110) [3 times]
    
I type something (`document.`) in `insert-state` and press `TAB` to bring autocompletion:

    apply: Wrong type argument: stringp, 110

#### Reproduction guide :beetle:
- Start Emacs
- Install `tern` (`npm install -g tern`)
- Open JavaScript file
- Type `document.` in `insert-state`
- Press `TAB` to bring autocompletion

*Observed behaviour:* :eyes: :broken_heart:

    Error running timer `tern-reparse-on-idle': (wrong-type-argument stringp 110) [3 times]

*Expected behaviour:* :heart: :smile:

Popup with autocompletion gooderies helping out the poor beginner developer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 41baea8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv auto-completion better-defaults emacs-lisp git markdown
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
     spell-checking smex syntax-checking version-control cscope gtags semantic xkcd github
     (c-c++ :variables c-c++-default-mode-for-headers 'c-mode c-c++-enable-clang-support t)
     extra-langs html
     (javascript :variables tern-command "node" "/usr/bin/tern")
     shell-scripts sql yaml
     (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save t)
     ipython-notebook
     (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "gibiansky" haskell-enable-shm-support t haskell-completion-backend 'intero)
     evil-commentary django
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-repeat-scope "visible")
     react idris agda scheme ranger selectric evil-cleverparens speed-reading pdf-tools asm octave pandoc systemd)
```

#### Backtrace :paw_prints:

This is awfully long and polluted, but I do not know which parts are not important to trim it, sorry:

[backtrace.txt](https://github.com/syl20bnr/spacemacs/files/367308/backtrace.txt)

**Comment by elvis-sik** [comment]
This turned out to be the old PATH & nvm & weird interactions that we've all been familiar with for long. I installed nvm, and started using it, and the issue magically resolved itself.

**Comment by androclus** [comment]
i know this is old, but i am getting the same problem. yet, i am using nvm. If it is a common problem that everyone has all been long familiar with, then could someone provide a link to the solution? (i have been battling tern/company installation for 2 days now on emacs 25 (generic on debian) and this 'error' message is the only thing i see going by, and i still do not have autocompletion, despite following Nicolas Petton's tutorials and the emacs/tern install docs. thx.)
