### ISSUE TITLE
Failed to install evil-unimpaired in latest develop branch

### ISSUE THREAD

**Issue by kangjianbin** [syl20bnr/spacemacs#6602]
#### Description :octocat:
Failed to install evil-unimpaired in latest develop branch

--> installing package: evil-unimpaired@spacemacs-evil... [1/1]

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

Found an buffer named "*ftp anonymous@c*" with these messages:

>无效帮助命令 foo。
>open c
>未知主机 c。

It may be something like this in English:

>Invalid help command foo
>open c
>Unknown host c

*Expected behaviour:* :heart: :smile:

Install evil-unimpaired successfully

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.0.94.2
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. c64d04f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html javascript python markdown c-c   auto-completion go git better-defaults csharp ivy syntax-checking emacs-lisp)
```

**Comment by NJBS** [comment]
I believe this is an upstream issue related to Windows.

It manifests itself in different places, but for some reason Windows file paths are sometimes interpreted as FTP addresses. I haven't been able to reliably reproduce it and the upstream issue isn't much help either.

For reference:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2014-05/msg00199.html
https://lists.gnu.org/archive/html/bug-gnu-emacs/2014-11/msg00593.html

**Comment by kangjianbin** [comment]
It may be upstream related. But I have been using emacs25 for several weeks and didn't see this issue unitl I updated spacemacs yesterday.

**Comment by NJBS** [comment]
Can you try bisecting to find the commit?

**Comment by kangjianbin** [comment]
Bitsect result is: 
E:\home\.emacs.d>git bisect bad
41baea8744ed380da89d51dfe795124a974537fa is the first bad commit
commit 41baea8744ed380da89d51dfe795124a974537fa
Author: d12frosted <d12frosted@gmail.com>
Date:   Tue Jul 12 20:08:21 2016 +0300

    install evil-unimpaired using quelpa

    And properly setup dependencies.

    Fixes #6523
    Suppresses #6559

:040000 040000 68d43bc4544bc2c2717f4a502070896a7a2063a6 36467991d1fbbad95de775cd9ae90e431be136e1 M  layers

**Comment by NJBS** [comment]
Thanks for bisecting! :smile: 

https://github.com/syl20bnr/spacemacs/pull/6609 should fix this, can you confirm?

**Comment by d12frosted** [comment]
Hey @kangjianbin,

Sorry for the breakage. Possible fix is in `develop` branch, could you please confirm that it works for you?

**Comment by kangjianbin** [comment]
The latest develop branch works now. Thanks a lot.

**Comment by d12frosted** [comment]
@kangjianbin Glad to hear 😸 

Thanks @NJBS 😸 💃
