### ISSUE TITLE
Finding keys bound in spacemacs/user-config

### ISSUE THREAD

**Issue by lverns** [syl20bnr/spacemacs#6603]
Finding functions bound to keys is quite pleasant using `SPC h d k`. It shows what the function name is, a human readable description if one was given, other bindings to this function, and it links to the source of the function if you're curious about implementation.  However, bindings in `spacemacs/user-config` don't seem to show the source.

```elisp
(defun hello-world ()
    "Copies \"Hello World\" to the kill ring."
    (interactive)
    (kill-new  "Hello World"))
  (spacemacs/set-leader-keys "oh" 'hello-world)
```
Then pressing `SPC h d k` `SPC o h` gives
```
SPC o h runs the command hello-world, which is an interactive Lisp function.

It is bound to SPC o h, M-m o h.

(hello-world)

Copies "Hello World" to the kill ring.
```
This is nice but I'd love for the first line to read like 
```
SPC o h runs the command hello-world, which is an interactive
Lisp function in `.spacemacs'
```
Is is expected behavior? Should I just make a layer for my custom functions?

**Comment by d12frosted** [comment]
Most probably you just evaluated these expressions. So actually Emacs didn't get it from file, which means that Emacs can't tell you where this function is defined. Try restarting Emacs - and you'll see file defining `hello-world` when using describe system. 

Just as a side note - describe system is not implemented by Spacemacs, but itself is part of Emacs.

**Comment by lverns** [comment]
>So actually Emacs didn't get it from file, which means that Emacs can't tell you where this function is defined. Try restarting Emacs  

Just tried that now with no change. However, you got me thinking.

I removed the snippet, dropped it in a file named `hello.el`, restarted Emacs, and loaded the file with `load-file`. Now the describe system correctly source of the function.

Next, I changed `hello.el` to look like so:
```elisp
(defun load-hello-world ()
  "Defines the hello-world function and creates keybindings"
  (interactive)
  (defun hello-world ()
    "Copies \"Hello World\" to the kill ring."
    (interactive)
    (kill-new  "Hello World"))
  (spacemacs/set-leader-keys "oh" 'hello-world))
```
So now after a fresh start of Emacs, I can `load-file` and then call `load-hello-world`. The `hello-world` function will then be defined, and bound, but `describe-function` will once again not be able to find the source of `hello-world`. So it seems that when you use a `defun` inside a `defun`, Emacs can't find the source and this is what I'm doing in `~/.spacemacs`

Looks like `symbol-file` is the function that is responsible for finding the file name.

**Comment by syl20bnr** [comment]
Indeed, Emacs cannot find the location of functions defined in functions this is why we are moving slowly all the functions to a`funcs.el` file in each layer.

So basically your solution to create another file and load it from user-config seems to be the right approach.
