### ISSUE TITLE
[Enhancement] gentoo layer

### ISSUE THREAD

**Issue by bb010g** [syl20bnr/spacemacs#6606]
It would be nice if there was a `gentoo` layer containing at least [`ebuild-mode`](https://github.com/emacsmirror/ebuild-mode).

**Comment by bmag** [comment]
Implemented in #8562

**Comment by Miciah** [comment]
https://github.com/syl20bnr/spacemacs/commit/a4aab1ee31ef3f8aea02d958936e66618eb6b95d based on #8562 added ebuild-mode to the major-modes layer.  Does that resolve this issue? If so, the issue should be closed or labeled as "Fixed in develop".
