### ISSUE TITLE
[Enhancement] kite layer

### ISSUE THREAD

**Issue by anonymni** [syl20bnr/spacemacs#6611]
It would be really awesome if Spacemacs can add support for Kite. 
https://kite.com/

**Comment by JAremko** [comment]
Looks cool :+1:

**Comment by a13ph** [comment]
And then we can study it closely and make a GNU one! Mwahahaha!

**Comment by stephanschubert** [comment]
Kite has released support for Javascript today — https://www.kite.com/blog/product/kite-launches-ai-powered-javascript-completions/

**Comment by JAremko** [comment]
https://twitter.com/kitehq/status/1092912557801664512?lang=en

# F
