### ISSUE TITLE
How can I override faces of a theme that uses `let` to define colors?

### ISSUE THREAD

**Issue by mineo** [syl20bnr/spacemacs#6614]
I'm talking about themes like monokai-emacs (https://github.com/oneKelvinSmith/monokai-emacs/blob/master/monokai-theme.el#L96). AFAICT I could override those with the `theming` layer, however, that does not allow me to reuse the existing color definitions (ok, maybe I could extract them somehow after the theme has been activated, but that's not really a good solution). I also tried creating a repo with the modified version of the theme in it (https://github.com/mineo/monokai-emacs) and added that to my `dotspacemacs-additional-packages):

```elisp
   dotspacemacs-additional-packages '(github-clone
                                      pkgbuild-mode
                                      (monokai-theme
                                       :location
                                       (recipe :fetcher github
                                               :repo "mineo/monokai-emacs"
                                               :branch "mod")))
```

However, spacemacs seems to retrieve the `monokai-theme` package from melpa before my definition is taken into account.

What's a good solution to this? Do I need to create a new melpa package with a different name, which would make rebasing annoying?

**Comment by TheBB** [comment]
There's currently no good solution to custom themes, AFAIK. The theming layer is just a thin wrapper around Emacs' native face tweaking solutions. Whether those colors have been let-bound or not doesn't really matter, you modify faces the same way.

> What's a good solution to this? Do I need to create a new melpa package with a different name

You can't presently solve this problem with additional packages at all because the theme is applied before any package resolution takes place.

**Comment by TheBB** [comment]
> AFAICT I could override those with the theming layer, however, that does not allow me to reuse the existing color definitions (ok, maybe I could extract them somehow after the theme has been activated, but that's not really a good solution).

I'm not sure why this is necessarily a bad solution.

```elisp
(setq theming-modifications
      (let ((col1 (face-attribute 'default :foreground))
            (col2 (face-attribute  ...)))
        `((monokai
           (some-face :foreground ,col2)
           (other-face :foreground ,col1)
            ...))))
```

**Comment by mineo** [comment]
The let-based solution works to some extent, but in addition to assigning colors to faces that are already available on some other faces, I'd like to change the values of some of the basic color definitions, like `monokai-bg` and `monokai-highlight-line`, which are used by multiple faces.

**Comment by TheBB** [comment]
You can do as in https://github.com/syl20bnr/spacemacs/issues/6626 to substitute a custom monokai.

`(push "~/some/path/" custom-theme-load-path)`

Then copy monokai-theme.el to that path and change it.

**Comment by mineo** [comment]
Thanks, that works.
