### ISSUE TITLE
'Contribute' link is broken on spacemacs.org

### ISSUE THREAD

**Issue by collenjones** [syl20bnr/spacemacs#6615]
Steps to reproduce: Click 'Contribute' link on spacemacs.org landing page or go [here](http://spacemacs.org/doc/CONTRIBUTE.html).

![image](https://cloud.githubusercontent.com/assets/1937828/16903481/5daa92c0-4c34-11e6-9e73-2159ac55836b.png)

**Comment by TheBB** [comment]
Reported here: https://github.com/syl20bnr/spacemacs.org/issues/6
