### ISSUE TITLE
visual-line-mode navigation should move logical lines on up/down keys

### ISSUE THREAD

**Issue by istathar** [syl20bnr/spacemacs#6616]
#### Description

At first I thought visual-line-mode didn't work; no matter how many times I toggled, manually invoked, etc, in a text document with long lines (aka paragraphs) the cursor kept jumping between paragraphs, not [visual] lines.

Then randomly it _was_ working, and I couldn't figure out what the difference was... until I discovered that visual line mode works when vi keys are used (`h`,`j`,`k`,`l`) but _doesn't work_ when arrow keys (`up`,`down`) are used.
#### Reproduction guide
- Start Emacs
- Edit a document with long lines (paragraphs)
- Enable visual line mode with `SPC t L`
- Move down with arrow keys and cursor jumps paragraphs. Use vi keys and it moves single (logical) lines correctly.

_Expected behaviour:_

I would expect navigation vertically across paragraphs in visual line mode to be by logical line regardless of whether navigating up/down via `j`/`k` or `up`/`down`.

Based on discussion in a few other issues #681 and #6177 it seems like the settings changed by toggling visual line mode might need to have Up and Down added. Hopefully it's that simple.
#### System Info
- OS: gnu/linux
- Emacs: 25.0.94.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp git markdown spell-checking version-control intero)
```

AfC

**Comment by schuach** [comment]
Please reopen this issue, as I am experiencing the same problem. As I am using a nonstandard keyboard layout, so `h`, `j`, `k`, `l` is no real option for me. Problem description same as above.

**System Info**

- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Editing style: vim
- Completion: helm
- Layers: `(csv windows-scripts helm auto-competion finance emacs-lisp org markdown mu4e python themes-megapack spell-checking)

Thanks,
Stefan

**Comment by d12frosted** [comment]
It is open, though inactive.

**Comment by duzaichuan** [comment]
+1

**Comment by smile13241324** [comment]
I have merged the fix from duianto, @afcowie would you mind checking whether this fixed your issue.
