### ISSUE TITLE
Add calc to toggle list

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#662]
[Calc](http://www.gnu.org/software/emacs/manual/html_mono/calc.html) is a built-in scientific calculator in Emacs. `SPC t c` is free, we should give the calculator that key binding. The command to toggle Calc on and off is simply `calc`.

**Comment by syl20bnr** [comment]
ahah very funny, I thought it would be better to put in on `SPC a` since it is more an application to me. So I checked if `SPC a c` was free and...... it is not. Because it is already assigned to `calc` ;-)

**Comment by tuhdo** [comment]
Thanks. Nice to know that :)
