### ISSUE TITLE
Add collaborative editing support to Spacemacs

### ISSUE THREAD

**Issue by anonymni** [syl20bnr/spacemacs#6621]
Please please please!

**Comment by TheBB** [comment]
Maybe you can do some research to get the ball rolling? There's not much to go on here. Are there any collaborative editing solutions for Emacs that you would like to see supported in Spacemacs?

**Comment by kRITZCREEK** [comment]
We already have a floobits layer. Does that fit your need?

**Comment by anonymni** [comment]
Floobits free plan is limited to five workspaces. I think something like Motepair is what I want. I don't know what would be the steps to implement this in Emacs though.
 
https://atom.io/packages/motepair
