### ISSUE TITLE
 semantic and python layer cannot be used together

### ISSUE THREAD

**Issue by ikzk** [syl20bnr/spacemacs#6622]
#### Reproduction guide :beetle:
- Start Emacs
- add semantic and python layer
- create a .py file

*Observed behaviour:* :eyes: :broken_heart:
Emacs hangs and cannot switch to the buffer.

*Expected behaviour:* :heart: :smile:
Emacs successfully create and switch to the buffer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 9773ad6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(semantic
 (python))
```

**Comment by lukepfister** [comment]
Ran into this.  Are you using ipython 5.0?

**Comment by lukepfister** [comment]
I'm not sure if this is the best long-term fix, but
```
(setq python-shell-interpreter-args "--simple-prompt")
```
seems to do the trick for me.

**Comment by cpaulik** [comment]
Yes this is indeed the first ipython 5 related bug. See my PR for a fix based on @lukepfister experience which is the ipython-recommended solution for now.

**Comment by ikzk** [comment]
@lukepfister Yes I am using ipython 5.0. Thanks for your solution!
