### ISSUE TITLE
Is it just me or the links in the docs are broken?

### ISSUE THREAD

**Issue by carlosyasu91** [syl20bnr/spacemacs#6624]
I just wanted clarification and if they are I can help fixing them,

Reference: [docs](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org)

**Comment by TheBB** [comment]
They are not broken on develop, and in master they are only broken on github.

**Comment by TheBB** [comment]
Should be noted that it's quite challenging to get links to work in Emacs, on github and when exported. The issue you discovered is not exactly trivial and it was no oversight. :-)

**Comment by TheBB** [comment]
I'll close this as duplicate of https://github.com/syl20bnr/spacemacs/issues/4399.
