### ISSUE TITLE
highlight-persist/smartparens does not respect color theme

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#6626]
In my color-theme file I set `lazy-highlight` face, but smartparens overlay still rendering default face, unless I open color-theme  file and evaluate buffer manually. After that It renders using the correct face, until next restart.

To reproduce:

 - set the environment so Emacs would use custom color theme that loads from a file. e.g.: `(add-to-list 'custom-theme-load-path "~/spacemacs_layers/themes")`
 - set a theme in e.g. `dotspacemacs-themes '(base16-ocean-dark...`.
 - in the theme file change lazy-highlight face: e.g. `(lazy-highlight ((t (:background "Red"))))`
 - set  `dotspacemacs-smartparens-strict-mode t` and `dotspacemacs-smart-closing-parenthesis t`
 - restart Emacs
 - open a buffer in lisp or clojure mode
 - type `(`, observe that not the color that's been set in the theme is being used
 - open the theme file; evaluate the buffer - `, e b`
 - switch back to lisp mode buffer, type `(` - observe that now it uses the color set in the theme file

**Comment by TheBB** [comment]
Thanks for the repro steps. As discussed on gitter I cannot reproduce this problem, it works fine here.

**Comment by agzam** [comment]
it seems that particular face inherits from `isearch-lazy-highlight-face` setting that right fixed the issue for me
