### ISSUE TITLE
python-start-or-switch-repl doesn't start REPL in Emacs 25

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#6628]
#### Description :octocat:
In Emacs 25, calling `python-start-or-switch-repl` (`SPC m '` in Python buffers) when there's no REPL doesn't start a new REPL. In Emacs 24.5 it *does* start a new REPL.

A short check revealed that `python-start-or-switch-repl` (defined in Python layer) calls `python-shell-switch-to-shell` (built-in Emacs function). In Emacs 24.5, if no REPL exists then `python-shell-switch-to-shell` start a new REPL, but in Emacs 25 it no longer does so.

#### Reproduction guide :beetle:
- Enable the python layer
- Start Emacs 25 (note: 25, not 24.5 or 24.4)
- Open or create a python file
- press `, '` (calls `python-start-or-switch-repl`)

*Observed behaviour:* :eyes: :broken_heart:
Emacs doesn't open a REPL, instead prints an error message:
> python-shell-get-process-or-error: No inferior Python process running.

*Expected behaviour:* :heart: :smile:
Emacs opens a python REPL.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.0.95.1
- Spacemacs: 0.105.21
- Spacemacs branch: buffer-predicate (rev. bd7225f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-complete-with-key-sequence "jk" auto-completion-complete-with-key-sequence-delay 0.5 auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip t company-tooltip-align-annotations t)
 emacs-lisp
 (git :variables git-magit-status-fullscreen t)
 markdown org
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control
 (latex :variables latex-enable-auto-fill t latex-enable-folding t)
 pdf-tools evil-cleverparens python command-log smex themes-megapack c-c  
 (clojure :variables clojure-enable-fancify-symbols nil)
 ruby common-lisp ibuffer octave imenu-list window-purpose
 (theming :variables theming-modifications
          '((spacemacs-dark
             (aw-leading-char-face :foreground "red" :height 3.0))
            (spacemacs-light
             (aw-leading-char-face :foreground "red" :height 3.0))
            (monokai
             (aw-leading-char-face :foreground "red" :height 3.0))
            (flatland
             (aw-leading-char-face :foreground "red" :height 3.0)))))
```

**Comment by bmag** [comment]
Update: this is probably a duplicate of #2872

**Comment by TheBB** [comment]
Should be fixed in master.
