### ISSUE TITLE
Problem with Python environment

### ISSUE THREAD

**Issue by andy47** [syl20bnr/spacemacs#6629]
#### Description

Errors when opening a .py file with the python layer enabled.
#### Reproduction guide
- Start Emacs
- Open a .py file

_Observed behaviour:_
I see an error message as shown in the backtrace below

I have multiple versions of Python installed and a number of Python virtual environments. My suspicion is that I'm picking up a broken Python virtual environment. I would appreciate any help in working out which version/enviroment the anaconda-mode code is call.

_Expected behaviour:_
No error messages.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp markdown org syntax-checking python)
```
#### Backtrace

```
 File "<string>", line 4, in <module>
  File "build/bdist.macosx-10.11-intel/egg/anaconda_mode.py", line 18, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/__init__.py", line 14, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/factory.py", line 14, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/providers/basehttp.py", line 18, in <module>
ImportError: No module named BaseHTTPServer
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "build/bdist.macosx-10.11-intel/egg/anaconda_mode.py", line 18, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/__init__.py", line 14, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/factory.py", line 14, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/providers/basehttp.py", line 18, in <module>
ImportError: No module named BaseHTTPServer
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "build/bdist.macosx-10.11-intel/egg/anaconda_mode.py", line 18, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/__init__.py", line 14, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/factory.py", line 14, in <module>
  File "build/bdist.macosx-10.11-intel/egg/service_factory/providers/basehttp.py", line 18, in <module>
ImportError: No module named BaseHTTPServer
```

**Comment by TheBB** [comment]
Anaconda-mode calls whichever python installation the binary "python" in your PATH is.

**Comment by shadyproject** [comment]
I'm having this same issue.  When loading python from the command line, I can verify that i do have BaseHTTPServer module available.  I only have one python installed, system python.

**Comment by dmdsig** [comment]
im having the same issue, writing python code is impossible since im getting the popup every single time.
@TheBB how do i fix this? ive tried `  (setq python-python-command "/usr/local/bin/python3")` which is my preffered python version, ive installed that with homebrew on osx.

my path looks like this `/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin`, if im understanding this correctly, its calling my python2 before python3?

**Comment by a13ph** [comment]
@dmdsig you can do `which python` in shell to see which (sic!) one is getting prioritized for execution

**Comment by dmdsig** [comment]
```
bash-3.2$ which python
/usr/bin/python
bash-3.2$ which python3
/usr/local/bin/python3
bash-3.2$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin
bash-3.2$  
``` 
thats my output, can't figure out why it keeps saying `no module named BaseHTTPServer` imma fiddle with modules on `PYTHONPATH` for a bit more see if there is an inconsistency bewteen where theyre stored and where spacemacs or the python binary (?) is looking

**Comment by PierreR** [comment]
I have a similar issue. I have got `ImportError: No module named setuptools.command`.

In *Message* I have "Can not install `anaconda-mode' server" without anymore explanation.

I just want to edit some python script. Can I disable `anaconda` ? Do I really need to install `anaconda` to do some python with spacemacs ?

**Comment by TheBB** [comment]
> I just want to edit some python script. Can I disable anaconda?

Of course you can. https://github.com/syl20bnr/spacemacs/blob/develop/core/templates/.spacemacs.template#L60-L61

**Comment by MephistoMMM** [comment]
im having the same issue, but i fix it by reinstalling my python packages using normal user.

it causes my problem when all my python packages installed by root. PermissionError！

**Comment by dmdsig** [comment]
how do you fix it then? i should remove my python install then install as
usr? not as root?

**Comment by Ps-Pencil** [comment]
Same problem here.

**Comment by dmdsig** [comment]
Could not solve even if I removed all my python installations. Any clues? Im dumbfounded and need to work in other editors for python files which is ewww..

**Comment by TheBB** [comment]
Have you asked on the anaconda-mode repo? The problem originates in Python code which means it's more likely something to do with them.

**Comment by saltycrane** [comment]
Here's the issue in the anaconda-mode repo: https://github.com/proofit404/anaconda-mode/issues/188

**Comment by dmdsig** [comment]
thank you very much Eivind, you are always of great help

**Comment by greyfade** [comment]
@TheBB  Is there, or will there be any way of customizing which python binary anaconda it points to?

On Arch Linux systems, `/usr/bin/python` points to Python 3, for instance, and most environments default to Python 2. It seems like it would be wise to make this a tunable variable so that I could, for instance, set it to look for `python2` and `ipython2` instead of `python` and `ipython`. I imagine that would help with this issue.

**Comment by TheBB** [comment]
This is a known issue in the Python community and it doesn't just impact Spacemacs. The generally accepted solutions are tools like venvs and pyenv. On our side the interfaces to these tools are pyvenv and pyenv. The bindings to these are listed in the python layer documentation. It's unfortunate that they can be a little involved, but I'm reluctant to introduce even more layers of indirection.

**Comment by bogdanvuk** [comment]
I solved the issue of anaconda-mode reporting `ImportError: No module named setuptools.command` in \*anaconda-mode\* buffer, and "Can not install `anaconda-mode' server" in \*Messages\* buffer by doing the following (it seems that pip for python2 wasn't installed):

```
sudo apt-get install python-pip
/usr/local/bin/pip install anaconda-mode
```

**System Info**

- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.22
