### ISSUE TITLE
Display window number after 'Space'

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#663]
Is it possible to display the window numbers after choosing 'Space' ?

ie. to help with 'select-window-0' etc

thanks

**Comment by syl20bnr** [comment]
It is technically doable but won't it be annoying to have this ? Every bindings on the leader starts with `SPC`.

**Comment by fatlazycat** [comment]
Yeah perhaps something more specific, just something similar to ace-window

**Comment by CestDiego** [comment]
I think we could make it an offset, just like guide-key does right? D: the thing is that the numbers of the windows already show in the powerline...but they are not very visible.

[see](http://i.imgur.com/cDmqung.png)

**Comment by syl20bnr** [comment]
The number of the inactive window should now be readable so I close this. Feel free to reopen if needed.
