### ISSUE TITLE
Inconsistent key mapping in Org layer

### ISSUE THREAD

**Issue by liujoey** [syl20bnr/spacemacs#6630]
in org-mode `SPC m R` mapped to `org-refile`, but in agenda view it's mapped to `SPC m q`
in org-mode `SPC m q` mapped to `org-clock-cancel`, but in agenda view it's mapped to `SPC m Q`

Is there any specific reason we set this inconsistent mappings?

**Comment by TheBB** [comment]
No reason, just PR a change.
