### ISSUE TITLE
evil `cgn` motion fails with message `Search failed: "No search pattern"`

### ISSUE THREAD

**Issue by brendanator** [syl20bnr/spacemacs#6636]
#### Description
evil `cgn` motion fails with message `Search failed: "No search pattern"`

#### Reproduction guide
- Add `(setq evil-search-module 'evil-search)` to `.spacemacs` file
- Restart Emacs
- Search for text in a buffer using `/`
- Type `cgn`

*Observed behaviour:*
Message is displayed `Search failed: "No search pattern"`

*Expected behaviour:*
Searched text is found, deleted and mode is changed to insert

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git java markdown org ranger syntax-checking)
```

#### Backtrace
```
```

**Comment by TheBB** [comment]
I get a more comprehensible error message:

    Next-match text objects only work with the Evil search module.

Spacemacs defaults to isearch. If you want to use evil's built-in search you need to set `evil-search-module` to `evil`.

**Comment by andno037** [comment]
this issu is stil a problem right ?

**Comment by brendanator** [comment]
Yes it is

**Comment by andno037** [comment]
sorry for being a bit of a nob but at this, but I think I have stumbled on a workaround for this problem and not sure way it works or not work at the beginning. The fixe I did was to just set evil-search-module to evil-search with emacs customize tool insted of adding the line manually. here is a link for the issues at evil repo https://bitbucket.org/lyro/evil/issues/541/gn-seems-to-be-broken

**Comment by brendanator** [comment]
I'm using emacs in the terminal. Is there a way of doing this configuration in my case?

**Comment by karvus** [comment]
The suggestion in (https://bitbucket.org/lyro/evil/issues/541/gn-seems-to-be-broken) 
is to use the customization framework to set `evil-search-module', instead of simply setting the variable in your startup file.  That worked for me.

**Comment by brendanator** [comment]
Excellent, this works. Thanks all

For others who don't know what the customization framework is, it can be accessed with `:customize`
The customization settings are saved right at the bottom of the .spacemacs files

**Comment by YayConnolly** [comment]
Awesome, thanks for the fix! I suggest this issue be re-opened to add the solution somewhere in the docs, many people migrating from vim will encounter it.

**Comment by casouri** [comment]
I want to add that `cuatomize-set-variable` wouldn't work. You have to set it through customize.
