### ISSUE TITLE
How can I use LLDB in spacemacs?

### ISSUE THREAD

**Issue by Roife** [syl20bnr/spacemacs#6637]
I'm a user on macOS and I want to use LLDB instead of GDB to debug  C++ programs. I search google for information and it said that I should use `M-x lldb` . However, I can only find `M-x gdb` but it does't work well with LLDB. How can I use LLDB? Is there a layer or a package about it?

**Comment by bmag** [comment]
You can use <kbd>SPC h SPC</kbd> (`help-spacemacs-help`) to search for layers and for packages that are used by layers.

You can use <kbd>SPC a k</kbd> (`spacemacs/paradox-list-packages`) to search for packages in the archives that Spacemacs uses (Gnu ELPA and MELPA).

I searched and didn't find an LLDB package.

Can you please link to the source that told you to use `M-x lldb`?

**Comment by a13ph** [comment]
@roife you can use GDB on Mac OS X as well. 
Since this would be a linkrotting answer otherwise, I'll just point you to websearch for "gdb mac os" / "gdb os x" or with any other designation of your os, like "gdb El Capitan", say

**Comment by Roife** [comment]
@bmag Thanks for your useful advise. I got `M-x lldb` on this page [LLDB Status](https://llvm.org/svn/llvm-project/lldb/tags/lldb-80/www/emacs-integration.html) .

**Comment by TheBB** [comment]
That advice seems to be based on a patched version of gud.el. I can't find this file anywhere, in Aquamacs or in LLVM. Certainly the gud.el that ships with Emacs does not support lldb, and considering GNU's stance on certain issues it doesn't seem likely that it will happen. (See https://lwn.net/Articles/632773/ for example)

The patch appears to be this one if you wish to apply it yourself. https://gist.github.com/ptrv/71b93594589f3a5f27d2

**Comment by Roife** [comment]
@a13ph That's what I doing right now. I just wonder how to use LLDB in Spacemacs

**Comment by Roife** [comment]
@theBB I apply the patch and LLDB works fine with Emacs !
