### ISSUE TITLE
gist.el: (wrong-type-argument number-or-marker-p nil)

### ISSUE THREAD

**Issue by crshd** [syl20bnr/spacemacs#6641]
#### Description :octocat:
Using gist.el fails with `(wrong-type-argument number-or-marker-p nil)` on Emacs 25.1

#### Reproduction guide :beetle:
- Start Emacs
- `SPC g g b`

*Observed behaviour:* :eyes: :broken_heart:
Fails with

```
Contacting host: api.github.com:443
(wrong-type-argument number-or-marker-p nil)
```

*Expected behaviour:* :heart: :smile:
Get Gist

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 653da2a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence "jk" auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 emacs-lisp erc evil-cleverparens evil-snipe
 (figlet :variables figlet-font "cyberlarge")
 games git github html javascript markdown org osx php shell-scripts
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (smarttab :variables smarttab-insinuate 'c 'javascript)
 syntax-checking theming
 (version-control :variables version-control-diff-tool 'diff-hl)
 vinegar)
```

#### Backtrace :paw_prints:

See https://github.com/defunkt/gist.el/issues/90

**Comment by d12frosted** [comment]
The good thing - this is already known bug. And even reported upstream in Emacs mailing lists (can't find link right now). 

As temporary workaround - build emacs without `gnutls` support. Since you are on OS X, I suppose you have installed Emacs using `brew`. If so, you have to uninstall Emacs before building it without `gnutls` support. 

```
$ brew uninstall emacs[-plus]
$ brew install emacs[-plus] --with-cocoa --without-gnutls --with-librsvg --with-imagemagick --HEAD --use-git-head
```

To test that it works, execute following snippet.

```
(setq gnutls-log-level 2)
(switch-to-buffer (url-retrieve-synchronously "https://www.gnu.org"))
```

If it works for you - everything should be fine.

**Comment by crshd** [comment]
Yup, that works. Thanks!

So, this is a bug in Emacs itself? Then I guess I can go ahead and close the issue in gist.el as well and patiently wait for it to be fixed...

**Comment by d12frosted** [comment]
You can find more info in this issue: https://github.com/sigma/gh.el/issues/73.
