### ISSUE TITLE
Off by one scrolling with H and L

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#665]
To reproduce:

- First, press <kbd>L</kbd>.
- Then, press <kbd>H</kbd>
- Repeat the two steps above again.
- Now, instead of returning to the original line of the first <kbd>H</kbd>, point is on the line above.

**Comment by herbertjones** [comment]
I am unable to reproduce.  I know the Nyan Cat animation seems to cause an extra line to appear when it is animating, but after it stops lines return to normal.  Are you able to reproduce the issue when the Nyan Cat is disabled?

**Comment by syl20bnr** [comment]
I tried without nyan cat (yes... I use it...) and this is ok _with_ the above fix.

@herbertjones does the fix break the symmetry for you ?

**Comment by herbertjones** [comment]
I tried it before and after pulling the change in and didn't see a difference.  It was fine either way.  I didn't try with the nyan cat installed.  Last week I noticed some one off behavior with moving around a file but it wasn't limited to ```H``` and ```L```.  I haven't written an issue yet as I'm not sure if it's spacemacs or the cat yet.  I'll try to look at it later once I'm back on the machine with the cat installed.

**Comment by tuhdo** [comment]
The error still exists. `PgUp` and `PgDown` work fine: it correctly returns to original locations, always. Maybe instead of wrapping `(evil-next-visual-line)`, we can simply use `scroll-down-command` and `scroll-up-command`, then `recenter ` the new location.

**Comment by syl20bnr** [comment]
I don't understand how:
- @herbertjones has the same working H and L with the fix
- @tuhdo has the same non working H and L with the fix
It makes the issue independent from moving the point one more line after `L` which makes little sense to me.

@tuhdo where you at the end of the file ?

`scroll-down` is not the same behavior I believe, `H` and `L` goes to the line at the bottom of the visible area.

We could add all the different scrolling possibility to the scrolling micro-state.

**Comment by tuhdo** [comment]
Actually, it's not only off by one, but sometimes randomly returns to a position a few line before the original position. I can reproduce this behaviour with freshly installed Spacemacs, no `.spacemacs` file. You can open a random Emacs Lisp file and reproduce it.

**Comment by syl20bnr** [comment]
I found the issue, this is due to the height of the mode-line, not sure if it is only due to the `powerline-height` value or if this is a general behavior with Emacs mode-line.

A quick-workaround I see is to `let` the value of the mode-line while scrolling, I have not tested it yet though.

**Comment by herbertjones** [comment]
That makes sense, the nyan cat animation on my system raises the height of the bar a few pixels only when it is animated, which could throw off the calculations.  Nice catch.
