### ISSUE TITLE
Delay when yanking or deleting to non-blackhole registers in daemon mode

### ISSUE THREAD

**Issue by mgwio** [syl20bnr/spacemacs#6650]
#### Description :octocat:

Running emacs in daemon mode and connecting with emacsclient causes a delay when executing commands that store to the default (dd) or other non-blackhole register ("aD).

When run without daemon, this problem does not occur. When run with daemon/emacsclient, yank/delete to blackhole register ("_dd or "_yy or "_D...etc) does not observe this problem.

Here are a few clips of what I mean. The gifs are a bit choppy but I think the delay is still pretty evident in the ones using emacsclient. You can see that movement (jk), undo, and "_dX (blackhole register commands) still happen instantly.

With daemon in GUI (emacsclient)
![daemoncap](https://cloud.githubusercontent.com/assets/8557981/17028109/7dd7ee6e-4f34-11e6-8fdf-918f3593697c.gif)

Without daemon in GUI (emacs)
![nondaemon](https://cloud.githubusercontent.com/assets/8557981/17028110/7dee6f0e-4f34-11e6-825c-f6a43676e945.gif)

With daemon in terminal (emacsclient)
![termdaemon](https://cloud.githubusercontent.com/assets/8557981/17028111/7df0e144-4f34-11e6-82e3-8e533f39b1b8.gif)
#### Reproduction guide :beetle:
- Start Emacs --daemon
- Connect to instance with emacsclient (happens in both graphical and terminal)
- Any yank or delete to a non-blackhole buffer

_Observed behaviour:_ :eyes: :broken_heart:
Delayed operation by about a second, no matter file size

_Expected behaviour:_ :heart: :smile:
Operation to happen 'instantly', a la vim or non-daemon emacs
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.2
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 9773ad6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle)
 emacs-lisp erc git html ivy jade-theme nlinum osx
 (python :variables python-test-runner
         '(nose pytest))
 ranger)
```
#### Backtrace :paw_prints:

```
<<BACKTRACE IF RELEVANT>>
```

**Comment by alexisvincent** [comment]
Can confirm same behavior.
