### ISSUE TITLE
Reftex doesn't work well with Biblatex 

### ISSUE THREAD

**Issue by maikol-solis** [syl20bnr/spacemacs#6653]
Hello, 

I'm a super noob in emacs but I like it and today I started to use spacemacs. 

When I tried to cite some book or article  with biblatex, reftext doesn't recognized my .bib file and don't show me the articles already available. 

So as usual `C-RET` to select any command, I choose for example `cite` and normally it should be a textbox saying which author I want to cite.  Instead of that, there is nothing...

I tried to force emacs to read the .bib putting `reftex-default-bibliography: ("mybib.bib")` at the end of the file, but it doesn't work. 

Here it is a minimal example and please tell me if you need more information. 

Thanks. 

```
\documentclass[11pt]{article}

\usepackage[ %
style = authoryear-icomp, %
isbn = false, %
url = false, %
natbib
]{biblatex}

\addbibresource{mybib.bib}

\begin{document}
I want to cite something  \cite{<PROBLEM IS HERE>}
 
\printbibliography{}

\end{document}

%%% Local Variables:
%%% mode: latex
%%% TeX-master: t
%%% reftex-default-bibliography: ("mybib.bib")
%%% End:
```

**Comment by cpaulik** [comment]
Are you using the `bibtex` layer? If so then then `SPC m i c` should open org-ref which lets you insert the references.

**Comment by maikol-solis** [comment]
Apparently I don't have the `bibtex` layer. I did `SPC m` and it says `SPC m is undefined`  .

**Comment by cpaulik** [comment]
Could you please paste the output of `SPC h I` into your original bug report. Otherwise it is really hard to help.

**Comment by maikol-solis** [comment]
I solved the issue. I haven't put the `latex` layer explicitly in the .spacemacs file. Now reftex is loaded from the beginning. It was a newbie mistake. 
Thanks for the help.
