### ISSUE TITLE
Without dash installed, cannot restart or quit Spacemacs

### ISSUE THREAD

**Issue by numkem** [syl20bnr/spacemacs#6655]
#### Description :octocat:

If the `dash` shell isn't installed, it's not possible to quit or restart Spacemacs.
#### Reproduction guide :beetle:
- Start Emacs
- Without dash shell binary installed, try to restart `SPC q r` or quit `SPC q q` Spacemacs

_Observed behaviour:_ :eyes: :broken_heart:
`apply: Searching for program: no such file or directory, global` shows up in the message buffer. Cannot quit or restart Spacemacs.

_Expected behaviour:_ :heart: :smile:
Spacemacs should be quitting or restarting.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 1b5bc13)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(nginx
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 emacs-lisp themes-megapack git markdown
 (org :variables org-enable-github-support t)
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (syntax-checking :variables syntax-checking-enable-tooltips nil)
 python spacemacs-layouts html ansible vagrant dockerfile sql javascript shell-scripts spell-checking restclient gtags fasd yaml deft ibuffer typescript fasd ranger search-engine shell ipython-notebook go mu4e evil-snipe java puppet)
```

**Comment by TheBB** [comment]
I don't know what the "dash" shell is, but apparently the error is that you are using the gtags layer but haven't installed gtags (the *global* executable which the error message is asking about).

**Comment by numkem** [comment]
I've noticed that I was missing `global` for using the `gtags` layer which I removed but isn't this a major bug that a layer would make it impossible to exit Spacemacs?

Either way after installing dash (some evil- plugin needs it apparently) it worked so I'm assuming that there is a bug that makes it not possible to exit Spacemacs if an external binary is missing.

**Comment by TheBB** [comment]
I still don't know what dash is. Could you enlighten me?

**Comment by numkem** [comment]
Dash seems to be a very simple and bare-bone [shell](https://wiki.archlinux.org/index.php/Dash). It doesn't have tab completion so it's pretty much as simple as it gets.

**Comment by jtbm37** [comment]
@TheBB `/bin/sh` is symlinked to `/bin/dash`, at least for me on Ubuntu ;)

**Comment by TheBB** [comment]
Are you suggesting that there is no `/bin/sh` by default on Ubuntu unless you install a non-default package? I find that hard to believe.

**Comment by korayal** [comment]
I have Ubuntu Xenial (16.04) and I also have `/bin/sh` symlinked to `dash`
