### ISSUE TITLE
The `'relative` flag for `dotspacemacs-line-numbers` seems to not enable relative line numbers

### ISSUE THREAD

**Issue by arronmabrey** [syl20bnr/spacemacs#6656]
#### Description
The `'relative` flag for `dotspacemacs-line-numbers` seems to not enable relative line numbers 

#### Reproduction guide
- set `dotspacemacs-line-numbers 'relative`

*Observed behaviour:*
Line numbers are shown, but they are not relative.

*Expected behaviour:*
I expect relative line numbers to be shown.

The following is a work around for me in my config

```elisp
    (when (eq dotspacemacs-line-numbers 'relative)
      (add-hook 'prog-mode-hook 'linum-relative-mode)
      (add-hook 'text-mode-hook 'linum-relative-mode))
```

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults clojure emacs-lisp fasd git github gtags javascript themes-megapack markdown
                 (ranger :variables ranger-show-preview t)
                 (ruby :variables ruby-version-manager 'rbenv ruby-test-runner 'rspec)
                 theming org react
                 (shell :variables shell-default-height 40 shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh")
                 spell-checking syntax-checking
                 (version-control :variables version-control-global-margin t version-control-diff-tool 'git-gutter))
```

**Comment by JorisE** [comment]
Just to be sure, how and where have you set this variable?

You have to set this variable in the `dotspacemacs/init` section of .spacemacs. That is not immediately clear from the documentation.

Doing that, I have not been able to reproduce this by the way :)

**Comment by arronmabrey** [comment]
@JorisE thanks for checking this. You're correct I didn't fully capture the reproducible issue.

First, yes the `dotspacemacs-line-numbers 'relative` is set in `dotspacemacs/init`

But it looks like there is something in my `dotspacemacs/user-config` that's triggering the issue.

```elisp
(setq-default
  linum-format "%4d \u2502"
  linum-relative-format "%4s \u2502"
  )
```

If I comment that out, then the `dotspacemacs-line-numbers 'relative` works correctly.
If it's in my config, then `dotspacemacs-line-numbers 'relative` is broken.

Maybe there is a better way to set a custom linum format that doesn't break ``dotspacemacs-line-numbers 'relative`` I'm not sure.

Thoughts?

**Comment by JorisE** [comment]
Hmm, looks like relative-mode will break anytime you change the value of linum-format/linum-relative-format. 

I think we could 'fix' this in spacemacs by adding a dotspacemacs-line-numbers-(relative-)format and use that when initialising linum-mode. However, assuming that there is no reason why changing this value *has* to break the relative part of linum, a fix in linum-relative would probably be preferred.

**Comment by TheBB** [comment]
Linum-relative works by setting linum-format to a function whose return value is whatever is displayed. It stores the previous value of linum-format and resets it when turned off. Therefore if you are going to change linum-format you ought to do it before turning on linum-relative, which means do it in user-init, not user-config.

**Comment by arronmabrey** [comment]
@TheBB you are indeed correct.

Moving 
```elisp
(setq-default
  linum-format "%4d \u2502"
  linum-relative-format "%4s \u2502"
  )
```

from `dotspacemacs/user-config` to `dotspacemacs/user-init` fixes the issue.

Thank you very much!

**Comment by dphaener** [comment]
@arronmabrey This is *mostly* working for me, except that when an indicator is shown in the gutter it takes up extra space and bumps the line numbers over a bit to the right.

<img width="54" alt="screen shot 2018-02-16 at 10 48 22 am" src="https://user-images.githubusercontent.com/5187971/36323816-07a424ea-1307-11e8-8873-30bb53dc91df.png">
Any ideas on a workaround for that?
