### ISSUE TITLE
Set evil-search-highlight-persist-highlight-face to inverse-video

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#666]
Some themes have the color adjusted, some don't. For example, the highlight face in Zenburn theme when searching with `/` is unreadable. For best consistency, set the face attribute `:inverse-video` to `t`.

**Comment by syl20bnr** [comment]
Nice proposal! I'l try it, thank you!

**Comment by tuhdo** [comment]
@syl20bnr  I forgot to mention that you should also remove the `:background` colours and everything. Just set `:inverse-video` to `t` is enough.
