### ISSUE TITLE
Spacemacs taking several minutes to be ready for use

### ISSUE THREAD

**Issue by c-j-j** [syl20bnr/spacemacs#6664]
#### Description
Spacemacs is taking a very long time to become ready for use on my Mac. During the first few minutes a lot of the spacemacs commands results in unresponsive behaviour. For example, if I want to open a file and I press `<space> f f`, it crashes and I can only regain control by holding `Ctrl-G`. When I look at the *messages* buffer I can see "Waiting for process to die... done".

After a few minutes, it seems to spark into life with a message "Spacemacs is up to date". Should the update process take several minutes and cause the rest of spacemacs to be unusable during that time?

I've tried reinstalling a fresh version of spacemacs by doing a `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`, as well as removing the `.spacemacs` file and having it being regenerated, but the issue still persists.

#### Reproduction guide
- Start Emacs
- Press <Space> f f

*Observed behaviour:*
Emacs crashes, becomes unresponsive

*Expected behaviour:*
Spacemacs lets me select 

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

#### Backtrace
```
```

**Comment by TheBB** [comment]
Sounds like http://spacemacs.org/doc/FAQ.html#orgheadline14

**Comment by c-j-j** [comment]
Thanks @TheBB - that fixed the issue.

Adding 

```
(setq tramp-ssh-controlmaster-options
      "-o ControlMaster=auto -o ControlPath='tramp.%%C' -o ControlPersist=no")
```
inside `defun dotspacemacs/user-config` fixed the issue.

Cheers!
