### ISSUE TITLE
key mapping confliction

### ISSUE THREAD

**Issue by autosquid** [syl20bnr/spacemacs#6670]
`SPC m p` is both mapped in `org` layer and `bibtex` layer.

**Comment by TheBB** [comment]
The org layer sets it for org-mode and the bibtex layer sets it for bibtex-mode. There's no conflict.

**Comment by autosquid** [comment]
Thanks for replies, I double checked the description from bibtex layer, and you are right. However, the current bibtex layer get `org-ref` integrated which works in org-mode and provides a function to open pdf from citation, so I think the description with `SPC m p` in bibtex layer is just confusing. Maybe we can provide another key binding for `org-ref-open-pdf-at-point`.
