### ISSUE TITLE
How to disable buffer auto save?

### ISSUE THREAD

**Issue by timstott** [syl20bnr/spacemacs#6677]
I've searched all over the place and wasn't able to find an answer to the question.

When editing a buffer without saving to disk Spacemacs creates a file following the format `.#file-name`.
Is it possible to disable this behaviour?

**Comment by NJBS** [comment]
Those aren't auto-saves, those are lockfiles.

See [this](http://spacemacs.org/doc/FAQ.html#orgheadline18) entry in the FAQ.

**Comment by timstott** [comment]
Thanks for clarifying @NJBS 🙇 . `(setq create-lockfiles nil)` works like charm.
