### ISSUE TITLE
Please make +tool/tmux layer's hotkeys configurable

### ISSUE THREAD

**Issue by yzhuang** [syl20bnr/spacemacs#6679]
Currently, the tmux layer is hardcoded to use CTRL + "h, i, j, k". 
Can we make the tmux layer configurable by taking in the hotkeys from variables?

(E.g. my ctrl-k is kill to the end of line, and is very frequently used.)

Thanks,

**Comment by TheBB** [comment]
Is there any reason you can't rebind it yourself?

**Comment by yzhuang** [comment]
That's exactly what I am doing right now :-)

As you can see this file is only https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Btools/tmux/local/tmux/tmux.el 116 lines long.  I ended up copying 70 lines from 48 - 112 into my configs, just to change the key bindings.  It started making my configs look quite ugly.

**Comment by TheBB** [comment]
Yeah, it's not written the way it should be. Gimme a sec.

**Comment by TheBB** [comment]
Should be a lot simpler now. https://github.com/syl20bnr/spacemacs/commit/50297348462ea0bd71694c773fd83eb4ce5f4f1c

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
