### ISSUE TITLE
terminal output scroll off the screen

### ISSUE THREAD

**Issue by longlinht** [syl20bnr/spacemacs#6680]
When I issue a command in spacemacs's terminal,  
eg:
`svn log -v --diff  | less`
if the command output too much to display in one screen, the most top lines in first page always scroll off the screen, it very annoying， please fix this problem，if it is not a prolem and I use it wrong way, please tell me the right way.

**Comment by TheBB** [comment]
What is "Spacemacs's terminal" here? There are a few different ones.

**Comment by longlinht** [comment]
I mean shell layer's term.

**Comment by longlinht** [comment]
I set shell-default-shell to ansi-term

**Comment by TheBB** [comment]
I can't reproduce this with just `cat <filename> | less`. It works well here.

**Comment by longlinht** [comment]
My OS is ubuntu14.04,  use zsh, I'm not sure what caused this problem.
