### ISSUE TITLE
Commit fe60d0f breaks notmuch

### ISSUE THREAD

**Issue by vashirov** [syl20bnr/spacemacs#6681]
#### Description :octocat:
Commit fe60d0f breaks notmuch

#### Reproduction guide :beetle:
- Use notmuch package
- Start notmuch `M-x notmuch`
- Do search or open some email
- Press `q` to go to the previous buffer

*Observed behaviour:* :eyes: :broken_heart:
`*scratch*` buffer is displayed

*Expected behaviour:* :heart: :smile:
Previous useful buffer should be displayed

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.0.94.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 84580b1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible erc auto-completion emacs-lisp git c-c++ org
         (python :variables python-test-runner 'pytest pytest-cmd-flags "-v" pytest-cmd-format-string "echo %s; %s %s %s")
         (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/bin/zsh")
         syntax-checking version-control git my-notmuch vagrant yaml)
```

#### Backtrace :paw_prints:
```
```

**Comment by bmag** [comment]
@vashirov what is the exact buffer that you expected to see? I don't use `notmuch`, so I don't have all the necessary context. Can you tell me what windows/buffers are shown on the screen after each step in the repro guide? (gif also ok if you prefer that)

**Comment by vashirov** [comment]
`M-x notmuch` opens `notmuch-hello`, every following buffer is also prefixed with "notmuch".
Here are the webm files showing the issue:
Expected results:
https://fedorapeople.org/~vashirov/emacs-notmuch-working.webm
Actual results:
https://fedorapeople.org/~vashirov/emacs-notmuch.webm

**Comment by TheBB** [comment]
Okay, this is simple to solve.

**Comment by TheBB** [comment]
Try this

```elisp
(push "\\*notmuch.+\\*" spacemacs-useful-buffers-regexp)
```

**Comment by vashirov** [comment]
Thanks! That works for me.
