### ISSUE TITLE
Font width parameter not respected when creating new frames

### ISSUE THREAD

**Issue by edran** [syl20bnr/spacemacs#6684]
#### Description :octocat:

`width` parameter in `dotspacemacs-default-font` is not respected when making more frames.
#### Reproduction guide :beetle:
- Set `dotspacemacs-default-font` to:

``` lisp
dotspacemacs-default-font '("source Code Pro"
                            :size 11
                            :weight normal
                            :width condensed
                            :powerline-scale 1.1)
```
- Start Emacs
- `SPC : make-frame-command`

_Observed behaviour:_ :eyes: :broken_heart:
Width of font in new frame is set on `normal` instead of `condensed`.

_Expected behaviour:_ :heart: :smile:
Fonts look the same in all frames.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 84580b1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
nil
```
#### Backtrace :paw_prints:

```
n/a
```

**Comment by edran** [comment]
Screenshot of resulting initial frame and new frame compared:

![screenshot](https://i.imgur.com/NGrqO0T.png)

**Comment by fsvehla** [comment]
Same effect here.

**Comment by edran** [comment]
@fsvehla Did you manage to solve this at some point? I reckon it must be a problem with xft.

My `.Xresources` has:
```
Xft.dpi:        96
Xft.antialias: true
Xft.rgba: rgb
Xft.hinting: false
Xft.hintstyle: hintnone 
```
