### ISSUE TITLE
[LaTeX mode] Invisible ampersand ("&") character

### ISSUE THREAD

**Issue by kir0ul** [syl20bnr/spacemacs#6691]
Hi,

If I write an ampersand ("&") character in LaTeX mode, I can only see a space. If I write a backslash before, the ampersand character becomes visible. If I open the file with another editor, I can see that the ampersand character exists. _This happens only in LaTeX mode._
This is annoying because the ampersand character is needed in the `tabular` environment to separate the columns of the table.
Thanks.
#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(emacs-lisp git spell-checking latex)
```

**Comment by kccai** [comment]
Maybe your customized theme changes the font locking of the latex mode. You can check your theme in the `dotspacemacs-themes '()` variable. The default theme `spacemacs-dark` works very well.

**Comment by kir0ul** [comment]
My `dotspacemacs-themes` is the following:
````
   dotspacemacs-themes '(spacemacs-dark
                         spacemacs-light
                         solarized-light
                         solarized-dark
                         leuven
                         monokai
                         zenburn)
````

**Comment by eedahl** [comment]
I have this problem too, with the standard Spacemacs theme.

**Comment by kir0ul** [comment]
I had this problem on a Windows machine I don't have anymore. I tried to reproduce it recently on my Linux machine but everything seems to work pretty well :grimacing:

**Comment by duianto** [comment]
It might have been fixed since this was originally reported.
Let's close this for now. If someone is able to reproduce the issue then it can be reopened.
