### ISSUE TITLE
how to set this comment's color

### ISSUE THREAD

**Issue by vinurs** [syl20bnr/spacemacs#6695]
in c-mode, when i use comment like this:
`/* THIS */`
or
` /*`
` * this`
` */`

then, i can set 

> font-lock-comment-face

to set its' face and color, but when i type comment like this:
`/**`
` *`
` */`
it seams that it doesn't obey font-lock-comment-face setting.
how to set this comment's color and face?
Thanks!

**Comment by TheBB** [comment]
Use SPC hdc to check which face is being used on any given character.

**Comment by vinurs** [comment]
@TheBB thank you very much, it is customized by 
> font-lock-doc-face

It seems that this format will be treated as doxygen doc. 
That's great!
