### ISSUE TITLE
Variable is void: projectile-go-function

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#6697]
After updating projectile (20160727.748) the `projectile-go-function` variable seems to be undefined.

- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)

**Comment by TheBB** [comment]
We don't seem to be using this variable anywhere. Are you getting an error? If so can you post the error message and the backtrace?

**Comment by NJBS** [comment]
This is an upstream issue with projectile https://github.com/bbatsov/projectile/pull/1035

**Comment by chrisbarrett** [comment]
In the meantime 

```lisp
;; HACK: Fix missing or undefined internal function. :/
(defalias #'projectile-go-function #'projectile-go)
```

**Comment by sebhahn** [comment]
Thank you all!

**Comment by Stebalien** [comment]
FYI, this has been pushed to MELPA.
