### ISSUE TITLE
Spacemacs GUI freeze

### ISSUE THREAD

**Issue by ddsal** [syl20bnr/spacemacs#6698]
#### Description
When I try to launch emacs the startup freeze and only responds to Ctrl-g. The *Messages* buffer shows 
`Loading /home/daniel/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done`
`Waiting for process to die...done`
`Loading /home/daniel/.emacs.d/recentf...done`
`Cleaning up the recentf list...done (0 removed)`
`cond: Symbol's function definition is void: projectile-mode`

This only happens with the graphical version of emacs, if I use `emacs -nw`, Spacemacs works perfectly. I have tried deleting and reinstalling Spacemacs in a system with empty .bashrc and the --insecure flag.
#### Reproduction guide
- Start Emacs (GUI)

*Observed behaviour:*
- Emacs freeze with message "Loading /home/daniel/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done"

*Expected behaviour:*
- Clean startup of emacs (as achieved with "emacs -nw") which ends with the message "Spacemacs is up to date") and working perfectly.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

**Comment by syl20bnr** [comment]
I think you are on the right track, do you have other resource files than .bashrc in your home directory ?

**Comment by ddsal** [comment]
No, there aren't any other resource files. I just tested everything again with a newly created user with any files in its /home and I got the same result. Spacemacs works only with "emacs -nw"

**Comment by syl20bnr** [comment]
I suppose `--debug-init` gives nothing new ?

**Comment by ddsal** [comment]
`--debug-init` adds a bunch of text in between the original output of my first post, but ends in the same place:
`Loading /home/daniel/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...`
`Loading package ielm...`
`Configuring package ielm...done`
`Loading package ielm...done`
`Loading /home/daniel/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done`
`Loading /home/daniel/.emacs.d/layers/spotify/packages.el (source)...done`
`Loading /home/daniel/.emacs.d/layers/spotify/extensions.el (source)...done`
`(Spacemacs) Configuring bind-map...`
`(Spacemacs)   -> init (spacemacs-base)...`
`Loading package bind-map...done`
`(Spacemacs) Configuring evil-evilified-state...`
`(Spacemacs)   -> init (spacemacs-base)...`
`Loading package evil-evilified-state...done`
`(Spacemacs) Configuring holy-mode...`
`(Spacemacs)   -> init (spacemacs-base)...`
`(Spacemacs) Configuring hybrid-mode...`
`(Spacemacs)   -> init (spacemacs-base)...`
`Loading package hybrid-mode...`
`Configuring package hybrid-mode...done`
`Loading package hybrid-mode...done`
`(Spacemacs) Configuring ace-jump-helm-line...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring ace-link...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring ace-window...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring adaptive-wrap...`
`(Spacemacs)   -> init (spacemacs)...`
`Loading package adaptive-wrap...`
`Configuring package adaptive-wrap...done`
`Loading package adaptive-wrap...done`
`(Spacemacs) Configuring aggressive-indent...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring auto-compile...`
`(Spacemacs)   -> init (emacs-lisp)...`
`(Spacemacs) Configuring auto-highlight-symbol...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring avy...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring bind-key...`
`(Spacemacs)   -> init (spacemacs-base)...`
`(Spacemacs) Configuring bookmark...`
`(Spacemacs)   -> init (spacemacs-base)...`
`(Spacemacs) Configuring bracketed-paste...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring buffer-move...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring centered-cursor...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring clean-aindent-mode...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) company ignored since it has no owner layer.`
`(Spacemacs) Configuring define-word...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring desktop...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring diminish...`
`(Spacemacs)   -> init (spacemacs-base)...`
`Loading package diminish...done`
`(Spacemacs) Configuring dired-x...`
`(Spacemacs)   -> init (spacemacs-base)...`
`(Spacemacs) Configuring doc-view...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring ediff...`
`(Spacemacs)   -> init (spacemacs-base)...`
`(Spacemacs) Configuring eldoc...`
`(Spacemacs)   -> init (spacemacs-base)...`
`(Spacemacs)   -> post-init (emacs-lisp)...`
`(Spacemacs) Configuring electric-indent-mode...`
`(Spacemacs)   -> init (spacemacs-base)...`
`(Spacemacs) Configuring elisp-slime-nav...`
`(Spacemacs)   -> init (emacs-lisp)...`
`(Spacemacs) Configuring emacs-lisp...`
`(Spacemacs)   -> init (emacs-lisp)...`
`(Spacemacs) Configuring eval-sexp-fu...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring evil...`
`(Spacemacs)   -> init (spacemacs-base)...`
`Loading package evil...`
`Configuring package evil...done`
`Loading package evil...done`
`(Spacemacs)   -> post-init (emacs-lisp)...`
`(Spacemacs) Configuring evil-anzu...`
`(Spacemacs)   -> init (spacemacs)...`
`Loading package evil-anzu...`
`Configuring package evil-anzu...done`
`Loading package evil-anzu...done`
`(Spacemacs) Configuring evil-args...`
`(Spacemacs)   -> init (spacemacs)...`
`Loading package evil-args...done`
`(Spacemacs) Configuring evil-escape...`
`(Spacemacs)   -> init (spacemacs-base)...`
`Loading package evil-escape...`
`Configuring package evil-escape...done`
`Loading package evil-escape...done`
`(Spacemacs) Configuring evil-exchange...`
`(Spacemacs)   -> init (spacemacs)...`
`Loading package evil-exchange...done`
`(Spacemacs) Configuring evil-iedit-state...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring evil-indent-plus...`
`(Spacemacs)   -> init (spacemacs)...`
`Loading package evil-indent-plus...done`
`(Spacemacs) Configuring evil-lisp-state...`
`(Spacemacs)   -> init (spacemacs)...`
`Loading package evil-lisp-state...`
`Configuring package evil-lisp-state...done`
`Loading package evil-lisp-state...done`
`(Spacemacs) Configuring evil-matchit...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring evil-mc...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring evil-nerd-commenter...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring evil-numbers...`
`(Spacemacs)   -> init (spacemacs)...`
`Loading package evil-numbers...`
`Configuring package evil-numbers...done`
`Loading package evil-numbers...done`
`(Spacemacs) Configuring evil-search-highlight-persist...`
`(Spacemacs)   -> init (spacemacs)...`
`Loading package evil-search-highlight-persist...done`
`(Spacemacs) Configuring evil-surround...`
`(Spacemacs)   -> init (spacemacs-base)...`
`Loading package evil-surround...done`
`(Spacemacs) evil-terminal-cursor-changer ignored since it has been excluded.`
`(Spacemacs) Configuring evil-tutor...`
`(Spacemacs)   -> init (spacemacs)...`
`(Spacemacs) Configuring evil-visualstar...`
`(Spacemacs)   -> init (spacemacs-base)...`
`(Spacemacs) Configuring exec-path-from-shell...`
`(Spacemacs)   -> init (spacemacs-base)...`
`Waiting for process to die...done`
`Loading /home/daniel/.emacs.d/recentf...done`
`Cleaning up the recentf list...done (0 removed)`
`cond: Symbol's function definition is void: projectile-mode`

**Comment by ddsal** [comment]
Wait... I did some search and included some line in init.el and I got the following extra information

`(Spacemacs) Configuring exec-path-from-shell...`
`(Spacemacs)   -> init (spacemacs-base)...`
`Invoking shell /bin/bash with args ("-l" "-i" "-c" "/usr/bin/printf '__RESULT\\000%s\\000%s' \"${PATH-04c98bd3ee6c12785f4a61e050704f9d}\" \"${MANPATH-04c98bd3ee6c12785f4a61e050704f9d}\"")`
`Waiting for process to die...done`

**Comment by d12frosted** [comment]
Hey @ddsal 

I have one unrelated to your problem comment. In markdown you can wrap code block with three backslashes. So instead writing \`code\` you can write following thing:

\`\`\`
line1 
line2
\`\`\`

And it gets rendered as 

```
line1 
line2
```

**Comment by d12frosted** [comment]
> included some line in init.el

Which line did you include?

**Comment by ddsal** [comment]
I added `(setq exec-path-from-shell-debug t)` to the top of `init.el`

**Comment by ddsal** [comment]
I fixed the issue by excluding `exec-path-from-shell` in `.spacemacs`. I got that solution from [purcell/exec-path-from-shell#33](https://github.com/purcell/exec-path-from-shell/issues/33), also related to [syl20bnr/spacemacs#3887](https://github.com/syl20bnr/spacemacs/issues/3887).

**Comment by syl20bnr** [comment]
Maybe we should add a :toggle for this package to exclude it on FreeBSD.

**Comment by ddsal** [comment]
That would be a great idea, although the problem is not exclusive to FreeBSD, I'm using Arch Linux with Gnome.

**Comment by ddsal** [comment]
That would be a great idea, although the problem is not exclusive to
FreeBSD, I'm using Arch Linux with Gnome.

**Comment by bb010g** [comment]
I hit the same issue with GTK3 (no GNOME) on Funtoo (basically Gentoo).
