### ISSUE TITLE
Rebind "k" key to something else in magit

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#670]
Currently, Evil overrides the <kbd>k</kbd> that allows Magit to delete stuffs (i.e. hunks, files, branches...). It is quite an important key. We should keep it. The default command that is bound to <kbd>k</kbd> is `magit-discard-item` that performs corresponding delete action depends on which object point is on.

**Comment by tuhdo** [comment]
I discovered that it is bound to <kbb>K</kbd> now.

**Comment by syl20bnr** [comment]
When a buffer is evilified, the shadowed keys are upped one level:
- k -> K
- K -> C-k
- C-k -> C-K
More info in the conventions: https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.md#evilify-buffers
