### ISSUE TITLE
SPC m is undefined

### ISSUE THREAD

**Issue by tasmo** [syl20bnr/spacemacs#6700]
#### Description
When I try to use "SPC m" I get "SPC m is undefined" in the status.

#### Reproduction guide
- Start Emacs
- Disabling all layers under "dotspacemacs-configuration-layers"
- brand new installation

*Observed behaviour:*
It does not depend on the mode I use. And it happens at Mac OS X and Arch Linux.

*Expected behaviour:*
Emacs should switch into major mode.

#### System Info
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

**Comment by NJBS** [comment]
I might be misunderstanding your bug report, but `SPC m` bindings are set by their respective layers. If you disable all of your layers none of the bindings will be set.

For example, if you want the `SPC m` bindings shown in the [ocaml](http://spacemacs.org/layers/+lang/ocaml/README.html) layer you will have to add `ocaml` to your `dotspacemacs-configuration-layers` list in your `.spacemacs` file.

If you're looking to manually switch a buffer into a specific major mode that binding is under `SPC h M`.

**Comment by TheBB** [comment]
`SPC m` isn't for switching major mode, it's for doing stuff that depends on what major mode you're in.
Since you only have the emacs-lisp layer enabled, you need to be in emacs lisp mode to use `SPC m`. Open a `.el` file and see.

**Comment by tasmo** [comment]
So I completely misunderstood what is it for. Sorry, as you can see I'm coming from Vim and am new to Spacemacs.
