### ISSUE TITLE
When I try to add spacemacs-ivy to spacemacs layers, got error

### ISSUE THREAD

**Issue by wudixiaotie** [syl20bnr/spacemacs#6702]
* TEST: Each layer in [[file:/Users/tiexiao/.spacemacs::dotspacemacs-configuration-layers]  [dotspacemacs-configuration-layers]] can be found  
*** FAIL: spacemacs-ivy  
*** PASS: auto-completion  
*** PASS: better-defaults  
*** PASS: emacs-lisp  
*** PASS: markdown  
*** PASS: spell-checking  
*** PASS: syntax-checking  
*** PASS: version-control  
*** PASS: erlang  
*** PASS: erlang-rebar

**Comment by NJBS** [comment]
The layer has been renamed to just `ivy`.

**Comment by wudixiaotie** [comment]
@NJBS Still failed

**Comment by NJBS** [comment]
Can you provide the output of `SPC h d s`?

**Comment by wudixiaotie** [comment]
@NJBS 
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp markdown spell-checking syntax-checking version-control erlang erlang-rebar)
```

**Comment by NJBS** [comment]
Ah, you're currently on `master` and unfortunately, the `ivy` layer is only currently available on the `develop` branch of spacemacs. So if you'd like to try it out you'll have to switch to the `develop` branch :smile: .

**Comment by wudixiaotie** [comment]
@NJBS Thanks, very helpful.
