### ISSUE TITLE
Errors when exit.

### ISSUE THREAD

**Issue by asdyjd** [syl20bnr/spacemacs#6705]
When I type "spc q q" to exit spacemacs.It sticks and tell me "Wrote d:/emacs/.emacs.d/.cache/recentf".
And I type <C-g>,2 minutes later,it tell me:
error in process sentinel: open-network-stream: make client process failed: connection refused, :name, 127.0.0.1, :buffer, #<killed buffer>, :host, 127.0.0.1, :service, 36035, :nowait, nil
error in process sentinel: make client process failed: connection refused, :name, 127.0.0.1, :buffer, #<killed buffer>, :host, 127.0.0.1, :service, 36035, :nowait, nil

Enviroment: Windows10 x64

**Comment by NJBS** [comment]
Can you please update your issue to follow [this template](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report), `SPC h I` (capital I) should fill out most of this for you.

Additionally, can you toggle debugging on errors on using `SPC t D` and wait for the error to occur, then kindly provide the backtrace that comes up?
