### ISSUE TITLE
Proposal: move swoop into layer, auto follow in helm-ag

### ISSUE THREAD

**Issue by quicknir** [syl20bnr/spacemacs#6706]
My proposal is to:
1. Make helm-ag (and helm-grep) searches in the current file and open buffers start in follow mode.
2. Move swoop into a layer of its own and out of the core; this layer can be included by default in generated .spacemacs files. This way, users can easily drop swoop and benefit from helm-ag (more on this below) simply by removing the layer.

Locally, I use helm-ag for searching in the current file as well as project, directories, and buffers. I've also written a simple customization that starts helm-ag for the current file and for buffers in follow mode, which is one of the main reasons swoop is so popular. The helm maintainer recently pushed an update that causes follow mode in helm to update on typing, not just on up and down, making it really equivalent to swoop. Users will benefit from follow mode not only for single file search, but also for multi buffer. Note that I'm not proposing adding follow mode to searches on disk; following in this case is slow and opens many new buffers.

Helm-ag offers the following advantages over swoop:
1. Performance. Swoop's performance is just bad, even on single larger files. helm-ag is instant.
2. Consistency. Helm-ag is already used to search in the project, and in directories, and in open buffers (swoop is capable of doing this, but it's very slow).
3. Reduce dependencies.  Removes a dependency from core spacemacs, in particular a dependency that has received close to zero attention from its maintainer for a good chunk of time.

Arguments against, and my counters:

>  swoop output looks nicer

helm-ag until recently had face choices that didn't stand out in the spacemacs themes, this has been changed and it looks good, so this is now even. swoop groups the files more nicely in the multi buffer search, but it's too slow to search multiple buffers effectively so this is irrelevant; in single file search they are the same. swoop maintains syntax highlighting, but its extremely inconsistent and buggy, so I'd rather not have this at all.

> swoop has no dependencies

The only reason I'm suggesting keeping it in a layer and maybe even including that layer by default. In general though SPC s is largely dysfunctional if none of ag, pt, ack and grep are installed. Having one function more or less working is not a critical argument. We should anyway encourage *nix/windows users to install ag/pt to get the most out of the SPC s prefix.

> swoop searches unsaved changes

Of course this can be good or bad, but is generally preferable. This is a legitimate disadvantage of helm-ag but I think it's quite small compared to significantly better performance, and having a consistent search interface.

Thoughts, feedback?

**Comment by TheBB** [comment]
Does this supersede https://github.com/syl20bnr/spacemacs/issues/6592?

**Comment by syl20bnr** [comment]
Instead of putting helm-swoop in a layer we can add a layer variable to the helm layer `:buffer-search-method` or something like that and move `helm-swoop` to helm layer (is it not already the case?).

I think helm-swoop despite the performance issue is better suited for buffer search, mainly because it searches unsaved text occurrence, this is a must-have in my opinion.

**Comment by quicknir** [comment]
@syl20bnr Sounds good to me, I actually prefer a variable to a layer as its less work for me :-). I save the file constantly so I don't see this as an issue. I'll start looking at the code and preparing a PR.

**Comment by quicknir** [comment]
@TheBB Sort of? I guess it's partial overlap, partially not. Here I'm only going to add follow mode to search related stuff, and make swoop optional. There I'm talking more about following generally. So they partly overlap. Hope to do some PR's and start closing these soon.

**Comment by TheBB** [comment]
I hope so too…

**Comment by bmag** [comment]
Does the helm-ag approach work in remote buffers? (when editing a file on a remote machine)

**Comment by quicknir** [comment]
@bmag I don't use it this way myself, but I think it does: https://github.com/syohex/emacs-helm-ag/issues/122. At least when you go through tramp.
