### ISSUE TITLE
Line numbers disappear on empty lines if fill column indicator enabled and the indicator is outside the visible buffer area

### ISSUE THREAD

**Issue by katusk** [syl20bnr/spacemacs#6708]
#### Description

Line numbers disappear on empty lines if fill column indicator enabled _and_ the indicator is outside the visible buffer area.
#### Reproduction guide
- Start a graphical Emacs with a fresh Spacemacs installation
- Enable line numbers by setting `dotspacemacs-line-numbers t` (requires restart)
- Open your new `.spacemacs` file
- Enable fill column indicator by `SPC t f`
  - Note: `SPC t f` should disable everything related to visual word wrapping across multiple lines, so one line will be always one line visually
- Decrease the window width, so that the fill column indicator is not shown

_Observed behaviour:_
- On all the empty lines, the line numbers disappear---except on that empty line where your cursor might rest

_Expected behaviour:_
- Line numbers should be shown on all lines, including empty lines independent of the visibility of the fill column indicator.
#### System Info
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp)
```

**Comment by TheBB** [comment]
This is reproducible in `emacs -Q` so you should take it upstream.

**Comment by katusk** [comment]
#### Linked Issues
- [Fill-Column-Indicator Issue #71](https://github.com/alpaker/Fill-Column-Indicator/issues/71)
- [GNU bug report logs - #24638](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24638)

**Comment by katusk** [comment]
#### Linked Issues (Update)
- [Fill-Column-Indicator Issue #71](https://github.com/alpaker/Fill-Column-Indicator/issues/71) -- Still open; also see comment:
    - "Just FYI, I'm abandoning this package and welcoming requests to be take over as maintainer."
- [GNU bug report logs - #24638](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24638) -- This was closed:
    - "Please bring this first to the attention of the developers of fill-column-indicator.el.  I'm not at all sure this is a core Emacs problem."

Do you have alternative packages in mind for replacing `highlight-beyond-fill-column.el`?
