### ISSUE TITLE
Running code *after* a layer configures a package.

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#6711]
The eshell layer has a section that reads (approximately):

```elisp
(defun shell/pre-init-company ()
  ;; support in eshell
  (spacemacs|use-package-add-hook eshell
    ;; ... omitted ...
    :post-config
    (progn
      ;; ... omitted ...
      ;; The default frontend screws everything up in short windows like
      ;; terminal often are
      (defun spacemacs//eshell-switch-company-frontend ()
        "Sets the company frontend to `company-preview-frontend' in e-shell mode."
        (setq-local company-frontends '(company-preview-frontend)))
      (add-hook 'eshell-mode-hook
                'spacemacs//eshell-switch-company-frontend))))
```

I'd like to remove the `spacemacs//eshell-switch-company-frontend` hook (I've never noticed the company drop-down menu "screw[ing] everything up in short windows").

For now, I've added the following to my config:

```elisp
  (add-hook 'eshell-first-time-mode-hook
            (lambda ()
              (remove-hook 'eshell-mode-hook 'spacemacs//eshell-switch-company-frontend)))
```

However, this is eshell specific (most modes don't have an extra hook that runs before the `*-mode-hook` so, what's the "correct" way to do this? That is, how does a user generally run something after a layer finishes configuring a package?

**Comment by Stebalien** [comment]
In a similar vein, I map `M-l` to `evil-window-right` but the eshell layer insists on mapping it to `spacemacs/helm-eshell-history` in an `eshell-mode-hook` hook. Again, this is a case where I would like to run a hook after the layer-defined hooks but can't seem to do it, I've tried to clear the `M-l` mapping with:

```elisp
(add-hook 'eshell-mode-hook (lambda () (define-key eshell-mode-map (kbd "M-l") nil)))
```
...but it runs too early.

**Comment by TheBB** [comment]
Isn't this what `with-eval-after-load` is for? Running code after a file has loaded.

For that matter, the code you have cited from eshell really should be running in the init block, not config. Feel free to make a PR changing that if you wish.

`add-hook` adds to the front of the hook, so the function runs before all the other existing ones. It has an optional argument for adding to the back of the hook. See the documentation for `add-hook`…

**Comment by TheBB** [comment]
> (add-hook HOOK FUNCTION &optional APPEND LOCAL)

Add to the value of HOOK the function FUNCTION.
FUNCTION is not added if already present.
**FUNCTION is added (if necessary) at the beginning of the hook list
unless the optional argument APPEND is non-nil, in which case
FUNCTION is added at the end.**

**Comment by TheBB** [comment]
For that matter, the reason we have to define keys in `eshell-mode-map` in the hook is because eshell recreates this keymap every time the mode is enabled. Yes, it's stupid, but it's not our fault.

**Comment by Stebalien** [comment]
> add-hook adds to the front of the hook, so the function runs before all the other existing ones. It has an optional argument for adding to the back of the hook. See the documentation for add-hook…

Yes, reading the documentation would have been a good idea...

> Isn't this what with-eval-after-load is for? Running code after a file has loaded.

`(with-eval-after-load 'eshell ...` did the trick. Thanks!
