### ISSUE TITLE
w3m layer

### ISSUE THREAD

**Issue by fjp** [syl20bnr/spacemacs#6715]
Is there a reason why [w3m](http://emacs-w3m.namazu.org/) isn't already an available layer?
I wanted to use w3m in order to read html-emails in gnus.

Do you recommend another way of viewing mails sent in html?

Otherwise I am going to try adding this https://github.com/venmos/w3m-layer to my spacemacs config.

**Comment by TheBB** [comment]
> Is there a reason why w3m isn't already an available layer?

Nobody wrote one and PR'd it.

**Comment by TheBB** [comment]
If it's GPL licensed it shouldn't be a problem. It's good courtesy to ask first, however. If the owner doesn't reply then... well, it happens. Up to you. :-)

**Comment by praxanaix** [comment]
Hi. I just was wondering if you ever got it to work? I just installed Spacemacs a couple of days ago and tried to get it to work, but I couldn't get it to work at all. I posted a thread on Reddit about it but nobody answered (though I got a few upvotes about it so I know some are interested). Please let me know if you actually got it to run and, if so, how? That would be greatly appreciated.
Thank you very much.

**Comment by fjp** [comment]
@praxanaix I don't use spacemacs anymore. However, I think the author of https://github.com/venmos/w3m-layer added some instructions in the readme lately which should help to get this layer running.

**Comment by praxanaix** [comment]
> @praxanaix I don't use spacemacs anymore. However, I think the author of https://github.com/venmos/w3m-layer added some instructions in the readme lately which should help to get this layer running.

That's a shame. May I ask what you use instead? I'm just curious.
I did try that Venmos layer, but I couldn't get it to run at all. It gave me all kinds of errors. I posted on Reddit about it and got several upvotes, but nobody replied at all. It seems that nobody who has seen my post or who has talked to me so far in the Spacemacs community has yet managed to run w3m (or they haven't had the time or desire to let us know how to do it).

**Comment by fjp** [comment]
@praxanaix I didn't invest enough time to setup up everything the way I wanted. I still believe spacemacs is a great project. However, I use different os (windows, macOS, linux) and I got all kinds of different behaviours including errors with the same spacemacs config and wasn't willing to spend more time on configuring spacemacs stuff (same with this layer). Maybe these configuration issues would be solved in the meantime but this is why I use mainly vscode now.

**Comment by praxanaix** [comment]
Thank you for letting me know. I mostly only use Mac right now so that's not an issue for me but I appreciate the explanation. I'll keep searching for an answer and maybe post another github issue thing when I figure out how and where is appropriate.

**Comment by moritzschaefer** [comment]
The layer is now under GPL
https://github.com/venmos/w3m-layer/issues/4#event-4749965663

**Comment by lebensterben** [comment]
At current state this layer is unmergable. It must comply with our code conventions.
