### ISSUE TITLE
Odd symbol as pre-prompt of Intero REPL

### ISSUE THREAD

**Issue by joshcho** [syl20bnr/spacemacs#6718]
#### Description :octocat:
As in title, just slightly annoying :P

#### Reproduction guide :beetle:
- Start Emacs
- Open a .hs file
- SPC-m-s-r

*Observed behaviour:* :eyes: :broken_heart:
- Weird ? symbol for REPL

*Expected behaviour:* :heart: :smile:
- Lambda symbol or anything else

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. be6fd0e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 better-defaults c-c   emacs-lisp eyebrowse git
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "chris-done" hindent-style "johan-tibell")
 markdown org
 (shell :variables shell-default-term-shell "/bin/bash" shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 (syntax-checking :variables syntax-checking-enable-by-default nil)
 (scheme :variables scheme-program-name "/Applications/mit-scheme.app/Contents/Resources/mit-scheme")
 version-control)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by joshcho** [comment]
Problem with intero-mode, hard-coded prompt as \4.

**Comment by d12frosted** [comment]
AFAIK, this is by design 😸
