### ISSUE TITLE
Broken link in documentation for spell checking layer

### ISSUE THREAD

**Issue by sbdchd** [syl20bnr/spacemacs#6722]
The link to the spell checking layer is broken on [develop branch on github](https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#spell-checking), [develop version of the website](http://develop.spacemacs.org/doc/DOCUMENTATION#spell-checking), [default version of the website](http://spacemacs.org/doc/DOCUMENTATION#orgheadline151), but not on the [master branch on github](https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#spell-checking).

**Comment by nikolaiam** [comment]
#8138 fixes this together with #8146.

**Comment by syl20bnr** [comment]
Should be fixed on http://develop.spacemacs.org

**Comment by syl20bnr** [comment]
oops did not mean to close it
