### ISSUE TITLE
Default to insert state in COMMIT_EDITMSG buffers

### ISSUE THREAD

**Issue by mineo** [syl20bnr/spacemacs#6726]
What I usually want to do in those buffers is type a commit message and then close them. They are different from other buffers containing text in that they are empty when opened most of the time, so opening them in normal state doesn't seem useful.

I did try

```elisp
(add-to-list 'evil-buffer-regexps
                 '("COMMIT_EDITMSG" . 'insert))
```

However, that opened them in some weird state indicated as emacs state in the modeline, but with the block cursor from normal state.

**Comment by mineo** [comment]
Argh, I guess it's too late today and I'm making stupid mistakes,

```elisp
(add-to-list 'evil-buffer-regexps
                 '("COMMIT_EDITMSG" . insert))
```
works just fine. I'll try to make a pull request tomorrow.

**Comment by syl20bnr** [comment]
I consider this a user tweak and prefer the consistency of normal state as a sane default.

**Comment by mineo** [comment]
That works for me, the change is small enough.

**Comment by rinetd** [comment]
evil-buffer-regexp
