### ISSUE TITLE
Missing packages or ?

### ISSUE THREAD

**Issue by morpheusbeing** [syl20bnr/spacemacs#6727]
I have tried installing from both github and zip file and keep getting the following problems:

Found 2 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: adaptive-wrap@spacemacs... [1/2]
Package adaptive-wrap is unavailable. Is the package name misspelled?
--> installing package: paradox@spacemacs... [2/2]
An error occurred while installing paradox (error: (error Package `seq-' is unavailable))

I did try the SPC h l command, but did not work

**Comment by morpheusbeing** [comment]
Problem now fixed. 

   ;; Maximum allowed time in seconds to contact an ELPA repository.
   dotspacemacs-elpa-timeout 20

changed the timeout setting from 5 to 20 to allow for my sloooooow internet connection

**Comment by TheBB** [comment]
Great. Assuming I can close this then.
