### ISSUE TITLE
Error during redisplay: (eval (spaceline-ml-main)) signaled (void-variable which-func-current)

### ISSUE THREAD

**Issue by vladimir-vovk** [syl20bnr/spacemacs#6729]
#### Description
Modline blank (displays nothing).
Errors in *Messages* buffer:
...
Error during redisplay: (eval (spaceline-ml-main)) signaled (void-variable which-func-current) [34 times]
 ...
[https://www.dropbox.com/s/0prouj6fuiy314y/screenshot.png?dl=0](https://www.dropbox.com/s/0prouj6fuiy314y/screenshot.png?dl=0)

#### Reproduction guide
- Start Emacs
- Then you see loading progress bar in modline
- Then modline empty (displays nothing)
- If you switch to another application (Cmd-Tab on MacOS) and then return to emacs, modline displays all information
- Then if you press any key, modline empty again

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion python html javascript clojure django react latex go sql emacs-lisp c-c   git markdown org dockerfile syntax-checking ibuffer ranger evil-commentary evil-snipe)
```

**Comment by TheBB** [comment]
Is spaceline up to date?

**Comment by vladimir-vovk** [comment]
I am updated all packages right now and nothing changed. :(
[https://www.dropbox.com/s/uklbhcwzt7lxegm/screenshot2.png?dl=0](https://www.dropbox.com/s/uklbhcwzt7lxegm/screenshot2.png?dl=0)

How can I see spaceline version?

**Comment by TheBB** [comment]
It's in the folder name in .emacs.d/elpa/spaceline-...

Anyway I can't reproduce. In fact the variable is defvar'd [here](https://github.com/TheBB/spaceline/blob/master/spaceline-segments.el#L316) and only used if [which-function-mode](https://github.com/TheBB/spaceline/blob/master/spaceline-segments.el#L566-L567) is turned on.

**Comment by TheBB** [comment]
Does it work if you turn off the segment? `M-x spaceline-toggle-which-function-off`?

**Comment by vladimir-vovk** [comment]
Yes, thank you! :)
After `M-x spaceline-toggle-which-function-off` spaceline works as expected. 
Problem in which-function-mode?

**Comment by TheBB** [comment]
Are you using which-function-mode or not?

**Comment by TheBB** [comment]
Actually, looks like which-func-mode and which-function-mode mean subtly different things. I'll push a change but I doubt it will help with your problem, which should not ever happen since that variable is defined by Spaceline if nothing else.

**Comment by TheBB** [comment]
Actually, looks like which-func-mode and which-function-mode mean subtly different things. I'll push a change, see if it fixes your problem.

**Comment by vladimir-vovk** [comment]
Yes, I had `(setq which-function-mode t)` in my .spacemacs file. Now I remove this line and spaceline works great.

**Comment by TheBB** [comment]
Ah I see.

For the future, you can't turn on modes by just setting the mode variable, you have to call the function. See the documentation for the `which-function-mode` variable for example:

> Non-nil if Which-Function mode is enabled.
See the command `which-function-mode' for a description of this minor mode.
**Setting this variable directly does not take effect;**
either customize it (see the info node `Easy Customization')
or **call the function `which-function-mode'.**

**Comment by vladimir-vovk** [comment]
Now it is clear, thank you for your help! :)
