### ISSUE TITLE
In develop branch, I have to type every single char include '_' so I can find file.

### ISSUE THREAD

**Issue by wudixiaotie** [syl20bnr/spacemacs#6730]
When I was in master branch, if I want to find a file named 'sniffle_iprange.erl', I call <kbd>C</kbd>-<kbd>x</kbd> <kbd>C</kbd>-<kbd>f</kbd>, then type 'sniffleiprange', the file will be opened.
But in develop branch, I have to type 'sniffle_iprange' to find the 'sniffle_iprange.erl', otherwise the candidate list will be empty.
I have to type '_' every time I search file, why?

**Comment by TheBB** [comment]
I still have fuzzy matching in helm-find-files on develop. I trust your packages are fully up to date?

**Comment by wudixiaotie** [comment]
@TheBB Do you use flx and counsel?

**Comment by TheBB** [comment]
No, I use helm.

**Comment by TheBB** [comment]
No, I use helm. Is this about ivy? You haven't made that clear.

**Comment by wudixiaotie** [comment]
@TheBB haha, Never mind. I find the answer. [ivy-flx](http://oremacs.com/2016/01/06/ivy-flx/). Thanks. My bad.
