### ISSUE TITLE
PHP layer XDebug support?

### ISSUE THREAD

**Issue by d9k** [syl20bnr/spacemacs#6732]
I'm new to spacemacs and I would like to ask how good xdebug support in spacemacs is?
I'm interested in visual representation of debugging process at the file edit buffer (for example, breakpoints shown as red circles symbols near the lines numbers and arrow symbol appointed at currently debugged line). Also I would like to see good keymapping, for example F10 for step over, F5 for continue. Eval expression functionality (with ability to copy result)

**Comment by TheBB** [comment]
There's no particular support for debugging in the php layer. From some brief googling it looks like you can use xdebug via geben. Since you're in uncharted territory (from the Spacemacs perspective) you'll probably have to implement it yourself.

**Comment by d9k** [comment]
@TheBB, thanks!

How do you guys debug when you code php in spacemacs?
Do you use just use cli or some separate external application?

**Comment by codingquark** [comment]
I'm not in spacemacs, but yes, [geben](https://github.com/ahungry/geben) works well.

The docs are good too.

**Comment by d9k** [comment]
thanks, @codingquark!

**Comment by d9k** [comment]
It works!
But I changed xdebug port to `9002` earlier so I had to properly confugure geben for it.

Parts of my `~/.spacemacs`:

```
(defun dotspacemacs/layers ()
   ;; . . . . .
  (setq-default
   ;; . . . . .
   dotspacemacs-additional-packages '(
                                      geben
   )
   ;; . . . . .
)

;; . . . . .

(defun dotspacemacs/user-config ()
  ;; ...
  (setq geben-dbgp-default-port 9002)
  (setq dbgp-default-port 9002)
)

```

**Comment by d9k** [comment]
BTW, how can I turn off "evil" mode with a hotkey?

**Comment by TheBB** [comment]
You can set geben buffers to open in emacs state. That's better than turning off evil.

    (evil-set-initial-state 'geben-mode 'emacs)

Assuming the major mode is `geben-mode` of course. If not adjust as needed.

**Comment by TheBB** [comment]
Seems this is solved then. Feel free to make a PR to add this support to Spacemacs if you like.

**Comment by d9k** [comment]
thx 2 @MarkRedeman at https://github.com/ejmr/php-mode/issues/313#issuecomment-236956029:

> @d9k fyi there is an open pull request https://github.com/syl20bnr/spacemacs/pull/6376
