### ISSUE TITLE
vagrant-tramp-term can't find box on vagrant 1.8.1

### ISSUE THREAD

**Issue by sinewalker** [syl20bnr/spacemacs#6735]
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description
Cannot use `vagrant-tramp-term` (**SPC V t**) to connect to a running vagrant box. Instead it provides a prompt in the mini-buffer asking for a box to connect, with no completions available. 

#### Reproduction guide
- Start Emacs
- Open a directory to a vagrant instance (**SPC a d** */path/to/vagrant/*)
- ensure the box is up (**SPC V V**)
- attempt to open a Vagrant TRAMP shell (**SPC V t**)

*Observed behaviour:*
The mini-buffer displays `vagrant ssh to:  [No match]` and pressing TAB for completions gives an Ido Completions buffer with no completions available.  

*Expected behaviour:*
An ansi-term starts and connects to the vagrant VM via SSH.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/")
 better-defaults emacs-lisp git markdown org
 (shell :variables shell-default-height 66 shell-default-position 'top)
 spell-checking syntax-checking version-control colors php python javascript erc xkcd mjl-org deft puppet lua vagrant emoji org-journal osx
 (mjl :variables mjl-bind-osx-keys nil mjl-bind-unix-keys nil)
 (clojure :variables clojure-enable-fancify-symbols t)
 (squiz :variables squiz-wiid-script
        (expand-file-name "~/Work/git/whyisitdown/whyisitdown"))
 (mu4e :variables mu4e-installation-path "/usr/local/Cellar/mu/0.9.16/share/emacs/site-lisp/mu/mu4e"))
```

#### Backtrace

I wasn't able to figure out how to get one.  But I did do some diagnosis myself.  I found that `vagrant-tramp-term` calls `vagrant-tramp--all-boxes` and filters that for the running ones.  So I looked to see what it thinks is running, or not running:

```elisp
ELISP> (vagrant-tramp--all-boxes)
(((id . "hax")
  (name . "virtualbox")
  (provider . "running")
  (state . "/Users/mjl/hax/hax-vm")))
```

It *is* running, but that value's in the `provider` slot on the alist, not the `state` slot. That' s why it's filtered out.

Where does the alist come from? From the function picking out fields from the output of vagrant's `global-status --machine-readable` command:

```sh
mjl@milo:hax-vm (master=)$ vagrant global-status --machine-readable
1470105175,,ui,info,id
1470105175,,ui,info,name
1470105175,,ui,info,provider
1470105175,,ui,info,state
1470105175,,ui,info,directory
1470105175,,ui,info,
1470105175,,ui,info,-----------------------------------------------------------------------
1470105175,,ui,info,ee94da3
1470105175,,ui,info,hax
1470105175,,ui,info,virtualbox
1470105175,,ui,info,running
1470105175,,ui,info,/Users/mjl/hax/hax-vm
1470105175,,ui,info,
1470105175,,ui,info, \nThe above shows information about all known Vagrant environments\non this machine. This data is cached and may not be completely\nup-to-date. To interact with any of the machines%!(VAGRANT_COMMA) you can go to\nthat directory and run Vagrant%!(VAGRANT_COMMA) or you can use the ID directly\nwith Vagrant commands from any directory. For example:\n"vagrant destroy 1a2b3c4d"
mjl@milo:hax-vm (master=)$
```

In `vagrant-tramp--all-boxes` it does `(status-lines (-drop 8 (split-string status-raw "\n")))` but the output above has only 7 lines of preamble...

I changed the code to `(status-lines (-drop 7 (split...` and re-evaluated that `defun`.  After doing that, it works:

```elisp
ELISP> (vagrant-tramp--all-boxes)
(((id . "ee94da3")
  (name . "hax")
  (provider . "virtualbox")
  (state . "running")
  (dir . "/Users/mjl/hax/hax-vm")))
```

and so do `vagrant-tramp-term` and the `/vagrant:` TRAMP method to edit files (which is what I wanted)....

I'm unsure if the off-by-one error is specific to me, or my provider (virtualbox), or my version of Vagrant (**1.8.1**)...  Also I suspect the *Right Thing* to do would be to parse the output properly, not just blindly pick row X, column Y of the output.

**Comment by ksjogo** [comment]
I reported some (maybe related) problem with head on OS X upstream: https://github.com/dougm/vagrant-tramp/pull/32
Should probably be fixed upstream and not in spacemacs.

**Comment by sinewalker** [comment]
Yes I agree it should be fixed upstream. I didn't realise this came from another source.

**Comment by sinewalker** [comment]
This is an issue from upstream, and it's being addressed there. Not a Spacemacs issue.
