### ISSUE TITLE
org-capture "Required feature `org-projectile' was not provided"

### ISSUE THREAD

**Issue by linchen2chris** [syl20bnr/spacemacs#6736]
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-C C-C` TO SUBMIT>>
#### Description :octocat:
org-capture doesnot work, it produce "Required feature `org-projectile' was not provided"

#### Reproduction guide :beetle:
- Start Emacs
- press "SPC SPC  org-capture"
- the error message "Required feature `org-projectile' was not provided" will appear.

*Observed behaviour:* :eyes: :broken_heart:
org-capture popup doesnot appear

*Expected behaviour:* :heart: :smile:
error message appear "Required feature `org-projectile' was not provided"

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 9773ad6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm ivy syntax-checking
      (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
      javascript ycmd org markdown react git python
      (version-control :variables version-control-diff-tool 'diff-h1 version-control-global-margin t)
      emacs-lisp
      (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
Try to delete your org-projectile package and restart.

**Comment by linchen2chris** [comment]
I delete the org-projectile folder in elpa, and then restart it , the spacemacs reinstall org-projectile package. now it work fine , thank you very much for your reply and solution.  @TheBB
