### ISSUE TITLE
Control-W doesn't work when the completion drop-down is open

### ISSUE THREAD

**Issue by jpalmer** [syl20bnr/spacemacs#6740]
#### Description
When the completion list is open in insert mode, Control-W doesn't delete the current word

#### Reproduction guide
- Start Emacs
- Type enough to get the completion to pop up
- press Control W

*Observed behaviour:*
status line prints: "No location available"

*Expected behaviour:*
The most recent typed word is deleted

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp
                 (latex :variables latex-enable-auto-fill nil latex-enable-folding t)
                 extra-langs matlab)
```

#### Backtrace
```
No relevant backtrace
```

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/4243

Closing as duplicate. There's a workaround in there.
