### ISSUE TITLE
[question] how to choose font type in spacemacs? 

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#6743]
So I have three types of fira code in my mac: `retina`, `light` and `regular`. How can I be sure that spacemacs is picking `retina`? 

I'm doing this on my `~/.spacmacs.d/init.el`. But I don't see a way to place this config `retina`. 

``` elisp
   dotspacemacs-default-font '("Fira Code"
                               :size 14
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)

```

**Comment by willwright82** [comment]
I have the same issue — adding this to your user-config() works:

```
  (set-face-attribute 'default nil :font "Fira Code Retina-14")
```

**Comment by fsvehla** [comment]
@willwright82 That doesn’t work for me in latest develop, on what branch / ref are you?

**Comment by willwright82** [comment]
Hi @fsvehla — I cloned from `master` a while ago… Currently on versions (emacs-24.5.1) & (spacemacs-0.105.22). Just tested changing from Retina, to Regular to Light and all seems to still work fine. Of course the ligatures aren't officially supported yet and I haven't found a reliable hack for those. 😞

**Comment by fsvehla** [comment]
@willwright82 If you are on OS X, `emacs-mac` from `railwaycat/emacsmacport/emacs-mac-emacs-25.1-z-mac-6.0` (Homebrew) and with `mac-auto-operator-composition-mode` make Ligatures work for me.

**Comment by willwright82** [comment]
Thanks @fsvehla — Will give that a go!

**Comment by RichardJohnn** [comment]
thank you for the tips @fsvehla !

for any total noobs (like myself) still scratching their head: check out https://github.com/railwaycat/homebrew-emacsmacport#homebrew

i'd recommend `brew install emacs-mac --with-spacemacs-icon` to get the fancy purple icon.

and
`(mac-auto-operator-composition-mode)` goes inside your `dotspacemacs/user-config` in your ~/.spacemacs

**Comment by Compro-Prasad** [comment]
`menu-set-font` works for me. I am on Linux. Not sure if the font dialog popup appears on `emacs-plus` for Mac OS users. Because `x-select-font` is probably unavailable for them.

**Comment by but0n** [comment]
> thank you for the tips @fsvehla !
> 
> for any total noobs (like myself) still scratching their head: check out https://github.com/railwaycat/homebrew-emacsmacport#homebrew
> 
> i'd recommend `brew install emacs-mac --with-spacemacs-icon` to get the fancy purple icon.
> 
> and
> `(mac-auto-operator-composition-mode)` goes inside your `dotspacemacs/user-config` in your ~/.spacemacs

I installed emacs-**mac**, font ligatures works well, but both Meta(option) key and Command key doesn't work, do you have same issue?

**Comment by lebensterben** [comment]
Closing due to lack of response.
For other users please open a new issue with details.
