### ISSUE TITLE
[question] how to bind to a specific mode?

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#6744]
I was using the following binds with success until I had to operate on wrapped lines:  

```elisp
(define-key evil-normal-state-map "gk" 'org-backward-heading-same-level)
(define-key evil-normal-state-map "gj" 'org-forward-heading-same-level)
```

I don't mind overriding `gj` and `gk` in `org mode`, but in other modes, I'd like to maintain the original behaviour of `gj` and `gk`. How do I achieve that?

**Comment by TheBB** [comment]
`(evil-define-key 'normal org-mode-map ...)`

**Comment by don-han** [comment]
Something like `(spacemacs/set-leader-keys-for-major-mode 'org-mode "oR" 'org-clock-report)` might work as well

**Comment by ninrod** [comment]
@don-han with your solution I'd have to issue `,gk` or `,gj` is that correct?

**Comment by ninrod** [comment]
@thanks @TheBB, your solution is spot on. I think @don-han's solution is close if I have to issue a leading `,` if I understand correctly
