### ISSUE TITLE
Add keybinding to open shell in project root directory

### ISSUE THREAD

**Issue by menelaos** [syl20bnr/spacemacs#6745]
What do you think about adding a keybinding to open a shell/term/ansi-term/multi-term/eshell at the root directory of a project? Personally, I'd find this more useful than `projectile-run-shell-command-in-root`.

**Comment by TheBB** [comment]
Isn't this what `SPC p '` does?

**Comment by menelaos** [comment]
Hm, `SPC p '` isn't bound to any command as far as I can see. 
`SPC '` opens the default shell in the current directory, not the project root. I might be missing something though...

**Comment by TheBB** [comment]
Must be on the develop branch then.

**Comment by TheBB** [comment]
See https://github.com/syl20bnr/spacemacs/issues/6210 for example.

Added to develop on February 2nd. I'm closing this as a duplicate.
