### ISSUE TITLE
powerline separators not rendered in terminal

### ISSUE THREAD

**Issue by dmgening** [syl20bnr/spacemacs#6748]
So I'm trying fresh installation on os x. Emacs is installed via brew. And spacemacs is checked out via git at tag v0.105.21. Terminal emulator - iTerm2

```
$ emacs --version
GNU Emacs 24.5.1
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

Running from GUI
<img width="1069" alt="2016-08-03 0 56 00" src="https://cloud.githubusercontent.com/assets/151911/17346996/34293976-5916-11e6-8772-a1b9ae70304c.png">

Running for terminal under tmux:
<img width="1920" alt="2016-08-03 0 55 44" src="https://cloud.githubusercontent.com/assets/151911/17346997/342bf242-5916-11e6-8452-c0aab1aee52a.png">

Running outside tmux or using different terminal emulator produces same results. Any ideas? :)

**Comment by TheBB** [comment]
What's the value of `powerline-default-separator`?

**Comment by dmgening** [comment]
@TheBB thanks for response!
```
powerline-default-separator is a variable defined in `powerline.el'.
Its value is arrow

Documentation:
The separator to use for the default theme.

Valid Values: alternate, arrow, arrow-fade, bar, box, brace,
butt, chamfer, contour, curve, rounded, roundstub, wave, zigzag,
utf-8.

You can customize this variable.
```

**Comment by TheBB** [comment]
You can't use graphical separators in the terminal. You need to use `utf-8`.

**Comment by dmgening** [comment]
@TheBB oh, cool. Seems like i missed it in reference. Thank you :)
