### ISSUE TITLE
When started as daemon, toolbar and scrollbar modes default to "true"

### ISSUE THREAD

**Issue by nedludd** [syl20bnr/spacemacs#675]
If you start emacs with `--daemon` both `tool-bar-mode` and `scroll-bar-mode` are enabled.  They are disabled otherwise.

**Comment by CestDiego** [comment]
bump

**Comment by syl20bnr** [comment]
Looking into this tomorrow, promise!

**Comment by syl20bnr** [comment]
Fixed in develop :-)

**Comment by syl20bnr** [comment]
Fixed in master.

**Comment by c02y** [comment]
No, it's broken in latest develop branch.

scoll-bar is disabled in normal emacs, but enabled in daemon/emacsclient.

The value of `scroll-bar-mode` is `nil`, but the scroll bar is displayed in daemon/emacsclient.

emacs v26.2
