### ISSUE TITLE
custom error display

### ISSUE THREAD

**Issue by casertap** [syl20bnr/spacemacs#6750]
I am using material-design-light theme from megapack and I am using the java layer with eclim to report build errors on my code.

The problem is that error are only displayed using underline which is very difficult to see.
I would like to override a config to display those using red color.

How can I do that?

**Comment by TheBB** [comment]
Use `SPC hdc` to check the face under cursor. Then [modify that face](https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces.html#Faces).

**Comment by TheBB** [comment]
Upstream for material theme is [here](https://github.com/cpaulik/emacs-material-theme). You should report there.

**Comment by d12frosted** [comment]
Closing this issue for the lack of interest. Also this should fixed either in upstream theme or in your own configs.
