### ISSUE TITLE
eshell is not working in ubuntu

### ISSUE THREAD

**Issue by Niansheng** [syl20bnr/spacemacs#6755]
This is possibly not an issue about spacemacs. I post here just try to get some help. If there is better place please let me know. 

I got this in the message buffer when I try m-x eshell.
Configuring package eshell...done                                                                                                                                                    |  ;; This setq-default sexp is an exhaustive list of all the supported
Symbol's value as variable is void: closed

Emacs version:
$ emacs --version
GNU Emacs 24.5.1
Copyright (C) 2015 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

But the same thing works in my Mac. Emacs version is 24.5(9.0)
thanks in advance
Victor

**Comment by TheBB** [comment]
You have downloaded some corrupted packages. Please see the discussion in https://github.com/syl20bnr/spacemacs/issues/4524. Delete your elpa directory and reinstall, possibly also disable HTTPS when you do so.

**Comment by TheBB** [comment]
Closing this as a duplicate, since the linked issue is still open.
