### ISSUE TITLE
Adding eclimd to Java layer

### ISSUE THREAD

**Issue by elken** [syl20bnr/spacemacs#6756]
Hi,

I'd like to add support for starting/stopping eclimd, stumbled upon #3073 but as I'm new to the emacs scene, I'm not sure why the support isn't there. I've got the bindings and variables setup to just be able to do `SPC d s` and I'm away.

Any advice on this? Sorry for the noob q.

**Comment by TheBB** [comment]
No, of course you can add it. Just send a PR and we'll look at it.

**Comment by elken** [comment]
What was #3073 about then?

**Comment by TheBB** [comment]
He was complaining that he couldn't run `start-eclimd` interactively. I explained why (it's not autoloaded), and I also mentioned that the java layer doesn't support starting or stopping it anyway so it is out of scope of the layer. I'm fine with a PR adding such support.

**Comment by elken** [comment]
I see, my bad then. Closing.
