### ISSUE TITLE
dotspacemacs-startup-recent-list-size is not respected in develop

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#6758]
#### Description :octocat:
`dotspacemacs-startup-recent-list-size 5` is not respected

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
verify that recents list size is >= 5

*Expected behaviour:* :heart: :smile:
recents list size should be <= 5 

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. cce0213)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(emacs-lisp vimscript auto-completion better-defaults colors dash evil-commentary org shell git version-control markdown sql latex elixir ruby rust c-c++ html javascript)
```

#### Backtrace :paw_prints:
```
not applicable
```

**Comment by TheBB** [comment]
That's not so surprising, this variable was removed in develop. You can now change the sizes directly in `dotspacemacs-startup-lists` (see documentation for that variable).

**Comment by TheBB** [comment]
See https://github.com/syl20bnr/spacemacs/pull/6049
