### ISSUE TITLE
Func using define-key breaks with Error running timer: (void-variable key)

### ISSUE THREAD

**Issue by voltecrus** [syl20bnr/spacemacs#6762]
#### Description
I have the following func + keybinds with it:

```
  (defun define-key-maps (key func)
    (define-key evil-normal-state-map key func)
    (evil-define-key 'normal dired-mode-map key func)
    (evil-define-key 'normal diff-mode-map key func)
    )

  (define-key-maps (kbd "4") 'helm-projectile-switch-project)
  (define-key-maps (kbd "C-r") 'shell-command)
  (define-key-maps (kbd "9") 'spacemacs/helm-files-smart-do-search)
  (define-key-maps (kbd "8") 'helm-mini)
  (define-key-maps (kbd "3") 'helm-projectile-find-file)

 ;; This is working
  ;; (define-key evil-normal-state-map (kbd "2") 'helm-find-files)
  ;; (evil-define-key 'normal dired-mode-map (kbd "2") 'helm-find-files)
  ;; (evil-define-key 'normal diff-mode-map (kbd "2") 'helm-find-files)

  ;; This isn't
  (define-key-maps (kbd "2") 'helm-find-files)
 ;; Neither do those
  ;; (define-key-maps (kbd "C-j") 'evil-forward-paragraph)
  ;; (define-key-maps (kbd "C-k") 'evil-backward-paragraph)
```

Spacemacs fails to start with `Error running timer (void-variable key)`

#### Reproduction guide

- Put the following code in .spacemacs
- Restart spacemacs

*Observed behaviour:*
It reports an error on start. Surprisingly evaluating them one by one is fine.

*Expected behaviour:*
To be working like all the statements above that one

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: my_master (rev. 995ffa1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
 emacs-lisp git markdown syntax-checking restclient org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 vagrant ruby deft dash html github version-control yaml dockerfile ruby-on-rails)
```

**Comment by voltecrus** [comment]
I guess it's not an issue with spacemacs per se, going to ask someplace else.

**Comment by TheBB** [comment]
> It reports an error on start. Surprisingly evaluating them one by one is fine.

Usually you would cite the error message in the bug report. Otherwise it's hard to help…

**Comment by voltecrus** [comment]
It's there, right after the code block. The error is `Error running timer (void-variable key)`

**Comment by voltecrus** [comment]
It seems like that func is breaking something fundamental. Like everything just sort of stops working. For example to restart Emacs, I have to press `SPC q r` prbly 4-5 times and it gives me the same error but on the 5th time it actually restarts.

**Comment by voltecrus** [comment]
It is as if the `key` symbol becomes a bottleneck somewhere inside emacs.

Something along the lines of "I press the button -> which evaluates to the key symbol somewhere -> it times out.

**Comment by voltecrus** [comment]
Okay, it's exactly 3 times. In other words, after start of spacemacs,

Press 2 - void variable key
Press 2 - void variable key
Press 2 - void variable key

Press 2 - actually calls the func.

**Comment by voltecrus** [comment]
Changing the function to this macro:

```
  (defmacro define-key-maps (key func)
    `(progn
       (define-key evil-normal-state-map ,key ,func)
       (evil-define-key 'normal dired-mode-map ,key ,func)
       (evil-define-key 'normal diff-mode-map ,key ,func)
       ))
```

Solved the problem. Now the only question is why was it breaking...

**Comment by TheBB** [comment]
`evil-define-key` is a macro, not a function. Looks like it's not coded exactly right.
