### ISSUE TITLE
 (file-error "Cannot open load file" "No such file or directory" "bind-map")

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#6767]
#### Description :octocat:
Startup error

#### Reproduction guide :beetle:
- Start Emacs (fresh install)
- see error

*Observed behaviour:* :eyes: :broken_heart:
Error: ` (file-error "Cannot open load file" "No such file or directory" "bind-map")`

*Expected behaviour:* :heart: :smile:
no error

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.50.2 (also 24.x see [build log](https://hub.docker.com/r/jare/spacemacs/builds/bxbxfqtuxlnvddmp2tsat4x/))
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 7280a46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (file-error "Cannot open load file" "No such file or directory" "bind-map")
  require(bind-map)
  spacemacs-bootstrap/init-bind-map()
  funcall(spacemacs-bootstrap/init-bind-map)
  (let* ((pkg-name (eieio-oref pkg (quote :name))) (owner (car (eieio-oref pkg (quote :owners)))) (owner-layer (configuration-layer/get-layer owner)) (disabled-for-layers (eieio-oref owner-layer (quote :disabled-for)))) (spacemacs-buffer/message (format "Configuring %S..." pkg-name)) (mapc (function (lambda (layer) (if (memq layer disabled-for-layers) (spacemacs-buffer/message (format "  -> ignored pre-init (%S)..." layer)) (spacemacs-buffer/message (format "  -> pre-init (%S)..." layer)) (condition-case err (funcall (intern ...)) ((debug quote error) (configuration-layer//increment-error-count) (spacemacs-buffer/append ...)))))) (eieio-oref pkg (quote :pre-layers))) (spacemacs-buffer/message (format "  -> init (%S)..." owner)) (funcall (intern (format "%S/init-%S" owner pkg-name
```

**Comment by JAremko** [comment]
Tested both on Debian Emacs 24 (Spacemacs built by dockerHub) and my local build Ubuntu(also docker)  Emacs 25

**Comment by TheBB** [comment]
Well, do you have bind-map in the elpa directory?

**Comment by JAremko** [comment]
@TheBB  I'll be able to check it only in like 5+ hours :smile:

**Comment by JAremko** [comment]
@TheBB 

```sh
find / -name "*bind-map*"
/home/spacemacser/workspace/.emacs.d/.cache/quelpa/build/package-build/recipes/bind-map
/home/spacemacser/workspace/.emacs.d/elpa/bind-map-20160606.1343
/home/spacemacser/workspace/.emacs.d/elpa/bind-map-20160606.1343/bind-map-autoloads.el
/home/spacemacser/workspace/.emacs.d/elpa/bind-map-20160606.1343/bind-map.el
/home/spacemacser/workspace/.emacs.d/elpa/bind-map-20160606.1343/bind-map.elc
/home/spacemacser/workspace/.emacs.d/elpa/bind-map-20160606.1343/bind-map-pkg.el

```

**Comment by JAremko** [comment]
@TheBB  it looks like I don't have it :confused:

**Comment by JAremko** [comment]
Ok looks like it was some kind of elpa fluke. 
 
I'll close it for now.

**Comment by lwx5924** [comment]
I still have this issue with the develop branch, while master branch I have another issue. 
I uese mac and emacs 25.1

**Comment by ro31337** [comment]
Same issue on master. Using Mac Sierra, iTerm2

**Comment by bleepster** [comment]
I have the same issue on my first run after cloning the repo.
versions: 0.200.9@25.2.1

**Comment by bleepster** [comment]
I should have read the [install instructions](https://github.com/syl20bnr/spacemacs#install) properly. 

In #4 it says:

> emacs --insecure

**Comment by BubblesToTheLimit** [comment]
Same issue on master using Windows 7.
My attempts to fix it:
- Added the company proxy to the beginning of ~/.spacemacs
- Added the exact proxy config from my personal config to the beginning of ~/.spacemacs
- replaced https with http in ~/.emacs.d/core/core-configuration-layer.el
- cloned bind-map manually into ~/.emacs.d/elpa which is one of the errors thrown at me. source: https://github.com/justbur/emacs-bind-map
- start emacs with the insecure option: runemacs.exe --insecure

**Comment by adi-007** [comment]
I have the same issue.
OS: Manjaro 17.1.10
Emacs version: 26.1
Spacemacs version: 0.200.13

**Comment by yanghaoxie** [comment]
This is a very dirty workaround.
As others point out, the problem may be network connecting issues, so what if I use a local elpa-mirror which does not need network. Fortunately, this works. The steps are:
1. cd ~
2. git clone https://github.com/d12frosted/elpa-mirror. About 1.8G, I know, that is why I said the workaround is very dirty :(.
3. add following code to `(defun dotspacemacs/user-init ())` in file `.spacemacs`, since spacemacs support local elpa-mirror.
```
  (setq configuration-layer-elpa-archives
	      '(("melpa" . "~/elpa-mirror/melpa/")
	        ("org" . "~/elpa-mirror/org/")
	        ("gnu" . "~/elpa-mirror/gnu")
          ))

```
