### ISSUE TITLE
dotspacemacs-download-packages 'all doesn't work

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#6769]
`dotspacemacs-download-packages 'all` doesn't download all packages.  
@syl20bnr  :cry:

**Comment by d12frosted** [comment]
@JAremko could you please try again? Note that this variable was [renamed](https://github.com/syl20bnr/spacemacs/commit/1e64768fb7a8421f9c280d9efe3c8a4d3e52d43a) to `dotspacemacs-install-packages`.

**Comment by JAremko** [comment]
ok

**Comment by syl20bnr** [comment]
Actually it should work as expected now. `dotspacemacs-install-packages` only controls which package to install (and keep installed). This was the previous behavior that required to switch the value (previous behavior considered all installed packages to be used which forces to change the value to `used-but-keep-unused` afterward to enable only the truly used packages).

**Comment by JAremko** [comment]
@syl20bnr  @d12frosted So the total amount of installed packages is changed [I see only 284 packages](https://hub.docker.com/r/jare/spacemacs/builds/bsdmjnds5bkgk6ir4kbkkii/) and [previously(a month ago) it was 512](https://hub.docker.com/r/jare/spacemacs/builds/bevh7uzkz6ufa8umvzdxafr/) 

But how to tell how many packages was downloaded?

**Comment by TheBB** [comment]
I just tried from a fresh install and I get 515.

**Comment by JAremko** [comment]
Hm... Looks like I forgot to push the rename `dotspacemacs-download-packages` to `dotspacemacs-install-packages` I'll  try again.

**Comment by JAremko** [comment]
Thanks! Fixed!
