### ISSUE TITLE
haskell layer overriding C-left & C-right

### ISSUE THREAD

**Issue by emmanueltouzery** [syl20bnr/spacemacs#677]
The haskell contrib layer (which otherwise very good) is overriding C-left and C-right to call haskell-move-nested.

I find it quite annoying, because while in normal mode you can use b & w to move back and forward by one word, in insert mode there is no such possibility, so I'm used to use C-left and C-right for that purpose, which is supported by vim and evil (and spacemacs in other major modes).

Maybe it's a bad habit (maybe I should go out of insert mode more often?), I'm open if you have suggestions, otherwise I would be interested if there's any way I could disable that haskell layer feature while keeping the other features from that layer..?

**Comment by bjarkevad** [comment]
I tend to agree that C-{right, left} should not be overridden in the Haskell layer, but I'll have to look into it to confirm this. I'm working on integrating `structured-haskell-mode`, where I'll be taking a look at all the Haskell keybindings at the same time to make sure everything makes sense - it's very likely that `haskell-move-nested` will get a new binding or be completely removed. 

As to whether you should leave insert mode more often: whatever works for you! 

A quickfix would be commenting out the keybindings:
`SPC f e h`,  find the Haskell package, find the two lines containing `haskell-move-nested` and comment them out.

**Comment by TheBB** [comment]
It appears that these bindings have been removed, so I'm closing this. Please let me know if I'm mistaken.
