### ISSUE TITLE
go: replace deprecated oracle with guru

### ISSUE THREAD

**Issue by edrex** [syl20bnr/spacemacs#6772]
[go layer doc: oracle section](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go#go-oracle)

[go team's emacs guru integration](https://github.com/golang/tools/blob/master/cmd/guru/go-guru.el)

[spacemacs' current oracle bindings](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/go/extensions.el#L35), using go team's oracle integration. These are misfiled under `rename`. Hopefully folks don't have too much muscle memory built up and we can map them elsewhere.

[go guru design doc](https://docs.google.com/document/d/1_Y9xCEMj5S-7rv2ooHpZNH15JgRT5iM742gJkw5LtmQ/edit)

**Comment by goofansu** [comment]
+1

go-oracle is too slow

**Comment by sunisdown** [comment]
+1

**Comment by Sn0rt** [comment]
+1

**Comment by goofansu** [comment]
waiting for merge 👍
