### ISSUE TITLE
vkill instead of proced in osx layer

### ISSUE THREAD

**Issue by emanresusername** [syl20bnr/spacemacs#6773]
`proced` doesn't work in osx [for the time being](https://www.masteringemacs.org/article/displaying-interacting-processes-proced)
![osx-proced](https://cloud.githubusercontent.com/assets/860471/17451691/9bd216fc-5b1d-11e6-800b-b870dd9268e1.png)

[`vkill`](https://github.com/emacsmirror/vkill) could be used as a stop-gap in the `osx` layer like in [prelude](https://github.com/bbatsov/prelude/blob/master/core/prelude-osx.el#L45-L47)

thanks to @houli for the sleuthing

**Comment by CarlQLange** [comment]
Proced works on `emacs-plus --HEAD` (26.0.50) now: 
<img width="1981" alt="screen shot 2017-09-14 at 23 39 21" src="https://user-images.githubusercontent.com/859820/30459012-00c3bddc-99a6-11e7-9cfa-ae8e7d31c139.png">

This patch happened in this commit: https://github.com/emacs-mirror/emacs/commit/ef4ed84e72a323b3d29dc34df92d3f89ad4fc322 which states that 25.2 and on should have the fix. I don't know if it's necessary to support a stopgap anymore ¯\_(ツ)_/¯

**Comment by mddavila** [comment]
I confirm proced is also working in emacs-mac!
