### ISSUE TITLE
Helm Fuzzy Match: Cannot turn fuzzy-match off in develop branch

### ISSUE THREAD

**Issue by zzjjzzgggg** [syl20bnr/spacemacs#6776]
OS: Linux Mint 18
Emacs: 24.5.1
Spacemacs: latest develop branch

Problem:
Fuzzy match cannot be turned off by setting `:fuzzy-match nil`.

Reproduce Method:
First, let's see the normal behavior of turning on/off fuzzy-match in helm:
- Start emacs with `emacs -Q`
- Open a scratch buffer with `lisp-interaction-mode` enabled
- Run following code
  ```
(require 'package)
(setq package-load-list '((helm t)))
(package-initialize)

(require 'helm)
(setq h-src
      (helm-build-sync-source "test"
        :candidates '(foo bar)
        :fuzzy-match t
      ))
  ```
 And you will obtain result
  ```
((name . "test")
 (candidates foo bar)
 (action . identity)
 (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches)
 (match helm-mm-exact-match helm-mm-match helm-fuzzy-match)
 (fuzzy-match)
 (header-line . "C-j: Do Nothing (keeping session)")
 (matchplugin))
  ```
- Now turn fuzzy match off by setting `:fuzzy-match` to `nil`, and you obtain result
```
((name . "test")
 (candidates foo bar)
 (action . identity)
 (filtered-candidate-transformer helm-fuzzy-highlight-matches)
 (match helm-mm-exact-match helm-mm-match)
 (header-line . "C-j: Do Nothing (keeping session)")
 (matchplugin))
```
So far, these results are expected.

- Now, clone the latest develop branch of spacemacs.
- Open a scratch buffer with `lisp-interaction-mode` enabled
- Run code
```
(setq h-src
      (helm-build-sync-source "test"
        :candidates '(foo bar)
        :fuzzy-match t
      ))
```
Whatever you set `:fuzzy-match` to `t` or `nil`, fuzzy match is always enabled, and you always obtain same output
  ```
((name . "test")
 (candidates foo bar)
 (action . identity)
 (filtered-candidate-transformer helm-flx-fuzzy-matching-sort helm-fuzzy-highlight-matches)
 (match helm-mm-exact-match helm-mm-match helm-fuzzy-match)
 (fuzzy-match)
 (header-line . "C-j: Do Nothing (keeping session)")
 (matchplugin))
  ```
- Strangely, if you leave `:fuzzy-match` to be empty, i.e.,
```
(setq h-src
      (helm-build-sync-source "test"
        :candidates '(foo bar)
        :fuzzy-match
      ))
```
The fuzzy match is finally turned off. I don't know what an empty `:fuzzy-match` means.

There is no such issue in the master branch.

**Comment by zzjjzzgggg** [comment]
#6593 is related to this issue.

**Comment by TheBB** [comment]
In fact I would say it *is* this issue. You can post there.
