### ISSUE TITLE
python auto-complete freezes

### ISSUE THREAD

**Issue by vitiral** [syl20bnr/spacemacs#6778]
Anytime I follow the directions [here](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/python) to get autocompletion working for spacemacs, the emacs completely freezes (can't change buffers, can't do anything).

**Steps to reproduce**:
 - install Emacs 24.5.1 (most recent)
 - cloned spacemacs to `~/.emacs.d`
 - start spacemacs, selecting vim mode and default
 - add `python` and `auto-completion` to layers
 - open `test.py`, `SPC m s i` then `<enter>` to run ipython (kicks off ipython2 installed in my ~/.local/bin
 - type the following:
```
import sys
sys.pa<tab>
```
- entire emacs system freezes up

**Comment by vitiral** [comment]
#6752 I can also leave the stuck state with `C-g`, these two may be related.

**Comment by TheBB** [comment]
Ipython version?

**Comment by vitiral** [comment]
Sorry, forgot to comment.
```
# ipython --version
5.0.0
# python --version
Python 2.7.12
```

**Comment by TheBB** [comment]
Yes, ipython 5 doesn't work with Emacs. This has been fixed in develop. See https://github.com/syl20bnr/spacemacs/issues/6622
