### ISSUE TITLE
hl-todo causes long fontification times

### ISSUE THREAD

**Issue by gracjan** [syl20bnr/spacemacs#6782]
`hl-todo` causes large areas of a buffer to be propertized at every keystroke. This gets in the way of usual font-lock optimizations and makes some modes unusably slow, for example `haskell-mode` has rather involved character property rules.

Related issue: https://github.com/haskell/haskell-mode/issues/1360

**Comment by TheBB** [comment]
Users who experience problems can exclude it, no?

**Comment by bgamari** [comment]
Yes, but I'm not sure it's a great idea to ship a default configuration which is unusable for editing perfectly reasonable source files.

**Comment by izahn** [comment]
I agree with @bgamari. Spacemacs is unusable with the default configuration on old hardware. Resource intensive features should be opt-in, because tracking down which layer or option is causing problems is time consuming and tedious.

**Comment by gracjan** [comment]
Note that this particular case is a simple bug in `hl-todo` and the simplest course of action is to just fix it `hl-todo`.

**Comment by tarsius** [comment]
I've just pushed the fix. Thanks!
