### ISSUE TITLE
Pressing enter after opening brace in SCSS  file inserts extra newline

### ISSUE THREAD

**Issue by nmk** [syl20bnr/spacemacs#6786]
#### Description :octocat:
In SCSS mode (happens in CSS mode as well), pressing Enter after an opening parenthesis causes an extra newline to be inserted (`|` denotes cursor):

```
.foo {|} -- press enter

--results in
.foo {
  |

}
```

I would expect it (and it was the case until a few weeks ago) to result in:

```
.foo {
  |
}
```

#### Reproduction guide :beetle:
- Start Emacs
- open an (S)CSS file and type `.foo { Enter`.

*Observed behaviour:* :eyes: :broken_heart:
```
.foo {
   |

}
```

*Expected behaviour:* :heart: :smile:
```
.foo {
   |
}
```

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. e51a89a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-tab-key-behavior nil)
 elm emacs-lisp git github
 (haskell :variables haskell-enable-hindent-style "chris-done" haskell-enable-ghci-ng-support t haskell-enable-ghc-mod-support t haskell-process-auto-import-loaded-modules t haskell-stylish-on-save t)
 html javascript latex nlinum org purescript ranger ruby ruby-on-rails semantic
 (shell :variables shell-default-shell 'multi-term shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "/usr/local/bin/zsh")
 syntax-checking yaml)
```

**Comment by TheBB** [comment]
Can't reproduce this, I only get one new line as expected.

**Comment by nmk** [comment]
Using scss-mode or web-mode (asking because of the "Web" tag added to this). Any ideas on how to debug this?

**Comment by TheBB** [comment]
Yeah, start by reproing on 24.5 and not bleeding edge Emacs.

**Comment by TheBB** [comment]
I just tried on 25.1.50 and I can't reproduce there, either.

**Comment by nmk** [comment]
And I tried it on 24.5.1 and get the same behaviour.

**Comment by nmk** [comment]
It turns out it was because I had both smartparens mode and electric-pair-mode both on.
