### ISSUE TITLE
Strange behaviour of insert-sexp-before for nested one-line sexps

### ISSUE THREAD

**Issue by abcdw** [syl20bnr/spacemacs#6788]
#### Description

It inserts new sexp inside previous symbol.
#### Reproduction guide
- Start Emacs
- Open lisp file with two nested sexps on one line `(first (second))`
- Place cursor on `e` letter
- `SPC k (` (lisp-state-insert-sexp-before)

_Observed behaviour:_

```
(firs ()t
 (second))
```

_Expected behaviour:_

```
(first () (second))
```

or

```
(first ()
 (second))
```
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-complete-with-key-sequence "C-m" auto-completion-enable-snippets-in-popup t)
 (ranger :variables ranger-show-preview t)
 lua
 (c-c   :variables c-c  -enable-clang-support t)
 (clojure :variables cider-repl-history-size 1000 cider-repl-history-file "~/.cider_history")
 emacs-lisp java python ipython-notebook html latex markdown org yaml version-control git
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 semantic gtags syntax-checking spell-checking
 (colors :variables colors-enable-rainbow-identifiers nil)
 spacemacs-layouts)
```

**Comment by TheBB** [comment]
You should report this to evil-lisp-state since that's the package providing this.
