### ISSUE TITLE
Quitting spray-mode with `C-g` makes insert mode cursor disappear

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#679]
As title.

Reproduce:

1. open spacemacs
2. open a buffer with some text in it (such as the `*spacemacs*` buffer)
3. do `SPC a s r`
4. do `C-g` while text is scrolling

Now the cursor is invisible when in insert mode.

**Comment by syl20bnr** [comment]
hehe any hack will always bite you one day :-)

You can quit with `q` I believe to properly set the cursor back.

**Comment by kini** [comment]
Yes, that works. BTW, how I found this bug: I typed `SPC a s` and saw "??" in the guide-key popup, so I thought "what's his?" and typed `r`. Then suddenly some weird stuff is happening on the screen!!! So I hit `C-g` in a panic :)

**Comment by syl20bnr** [comment]
AHAH ok I will remove the lambda to have a proper function name in the guide-key.

**Comment by syl20bnr** [comment]
This is fixed in develop.
I also made a PR to fix it when spray quits by itself: https://github.com/ian-kelling/spray/pull/4
