### ISSUE TITLE
Can't activate vim mode in emacs editing style

### ISSUE THREAD

**Issue by y-usuzumi** [syl20bnr/spacemacs#6792]
#### Description

I set `dotspacemacs-editing-style` to `'emacs`. I expected commands like `evil-exit-emacs-state` and `evil-execute-in-normal-state` to work but they do nothing.
#### Reproduction guide
- Edit `.spacemacs` and change `dotspacemacs-editing-style` to `'emacs`
- Run Emacs
- `M-x` and `evil-normal-state`

_Observed behaviour:_
Spacemacs remains on emacs editing mode (Blue indicator at the bottom-left corner)

_Expected behaviour:_
Spacemacs switches to vim editing mode (Orange indicator at the bottom-left corner)
#### System Info
- OS: gnu/linux
- Emacs: 25.0.95.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking version-control csharp extra-langs idris html javascript php purescript python typescript racket themes-megapack)
```
#### Backtrace

```
```

**Comment by bmag** [comment]
To switch editing styles on the fly: (key bindings may be different in master branch)
- `SPC t E e` or `M-m t E e`: enable/disable emacs editing style
- `SPC t E h` or `M-m t E h`: enable/disable hybrid editing style

Emacs style is supposed to be non-modal, so I'm pretty certain (but not 100% sure) that's the observed behavior is expected.

**Comment by syl20bnr** [comment]
'emacs is 100% non-modal, use 'hybrid in your case and set hybrid-state as the default evil state (I'm not in front of a computer now).

**Comment by KenetJervet** [comment]
Thanks! 'hybrid and `(setq evil-default-state 'hybrid-mode-default-state)` did the trick. (although the cursor color sometimes goes wrong and indicates the opposite).

Not sure what "non-modal" means though. Could you please explain a little bit?

**Comment by TheBB** [comment]
Modal editing is what vim is all about: normal mode, insert mode, visual mode etc.

Emacs is a non-modal editor, and emacs editing style is also (as @syl20bnr says) completely non-modal, so no switching modes, even manually.

FWIW you don't have to set `evil-default-state`, it should be enough to set `hybrid-mode-default-state`.

**Comment by KenetJervet** [comment]
@TheBB Thanks. But I can't get it to work. The doc says
"Value of `evil-default-state' for hybrid-mode. Set to hybrid
to start in hybrid state (emacs bindings) by default."

I set it to `hybrid` and it still starts in normal state.

**Comment by TheBB** [comment]
Well yes, you should set it to `insert`, not `hybrid`.

**Comment by KenetJervet** [comment]
@TheBB. Thanks! Was just about to say that :D

**Comment by KenetJervet** [comment]
That's weird. For me only setting `dotspacemacs-editing-style` to `'hybrid` and `hybrid-mode-default-state` to either `hybrid` or `insert` does not work .

When I boot up spacemacs the bottom-left corner is pink (might be an indicator for hybrid mode?), but when i open any file it turns to orange and only responds to vim key bindings.

Explicitly setting `evil-default-state` to `emacs` or `hybrid` works for me.

**Comment by fikovnik** [comment]
I guess I must be doing something wrong, but non of these really work. I followed the docs and set:

```
   dotspacemacs-editing-style '(hybrid :variables
                                       hybrid-mode-default-state 'hybrid)
```

But the default state when visiting a buffer is somewhat random. In most cases it is the normal mode. In some (scratch buffer, .spacemacs) it is insert. How can I make the default state the hybrid one?

**Comment by syl20bnr** [comment]
Can you open a new issue with reproduction steps ?

**Comment by y-usuzumi** [comment]
@syl20bnr sorry, I was not aware of the concept of "modalness". Now that I know this the issue is invalid. Sorry I didn't close the issue in time.
