### ISSUE TITLE
Spacemacs disable mouse.

### ISSUE THREAD

**Issue by vasspilka** [syl20bnr/spacemacs#6793]
I am using a laptop and my touchpad often interferes with my typing. I can disable the trackpad fairly easily, but it is strange that spacemacs does not provide configuration to disable mouse by default.
My guess would be that it is popular feature request among laptop users.

I tried using https://github.com/purcell/disable-mouse but after a while it just stopped working, not sure exactly why.

I would love to see an easy `dotspacemacs-disable-mouse t` in `dotspacemacs/init`.
Ofcourse a way to toggle it would be nice aswell.

Would anyone else like to see this feature? I am new here but could try to debug an implement a solution with `disable-mouse` package

::EDIT:: The problem was that Evil took over mouse events so disabling the emacs ones was not enough

**Comment by vasspilka** [comment]
Hey so I came up this a solution, 
```
  (define-key evil-normal-state-map (kbd "<down-mouse-1>") 'nothing)
  (dolist (mouse '("<down-mouse-1>" "<mouse-1>"))
    (global-unset-key (kbd mouse)))
```
the above code disables clicks, you can still doubleclick if you really want to use the mouse/touchpad

**Comment by TheBB** [comment]
Bind it to `nil` instead of `nothing`. :-)

**Comment by vasspilka** [comment]
@TheBB Just tried with puting `'nil` instead of `'nothing` and it was not woking anymore o.O

**Comment by TheBB** [comment]
Well, what's happened then (I suspect) is that there's another keymap that has keys bound to the mouse. When you bind it to `nil` it falls through to the next keymap, and when you bind it to `nothing`, it's the `evil-normal-state-map` that takes precedence over others (since it's the highest precedence keymap with a binding for the mouse).

**Comment by TheBB** [comment]
That's probably why the `disable-mouse` package doesn't work with Spacemacs: because it defines a minor mode that intercepts the mouse events. However the evil keymaps have higher precedence than minor mode maps ([see here](https://github.com/syl20bnr/spacemacs/wiki/Keymaps-guide)).

**Comment by vasspilka** [comment]
Yes its exactly that evil mode handles the mouse events and it's not enough just to disable mouse from emacs

**Comment by CestDiego** [comment]
This is what I do to have org-mode keybindings where I wouldn't be able to:

```lisp

    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;;; OVERRIDING GLOBALLY STUFF ;;;;;;;;
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    (defvar custom-keys-mode-map (make-keymap) "custom-keys-mode keymap.")
    (define-minor-mode custom-keys-mode
      "A minor mode so that my key settings override annoying major modes."
      t " my-keys" 'custom-keys-mode-map)
    (custom-keys-mode 1)

    (defun my-minibuffer-setup-hook ()
      (custom-keys-mode 0))
    (add-hook 'minibuffer-setup-hook 'my-minibuffer-setup-hook)

    (defadvice load (after give-my-keybindings-priority)
      "Try to ensure that my keybindings always have priority."
      (if (not (eq (car (car minor-mode-map-alist)) 'custom-keys-mode))
          (let ((mykeys (assq 'custom-keys-mode minor-mode-map-alist)))
            (assq-delete-all 'custom-keys-mode minor-mode-map-alist)
            (add-to-list 'minor-mode-map-alist mykeys))))

    (ad-activate 'load)

    (define-key custom-keys-mode-map (kbd "C-\"") 'org-cycle-agenda-files)
    (define-key custom-keys-mode-map (kbd "C-'") 'spacemacs/default-pop-shell)

```

**Comment by diego-alvarez-hs** [comment]
@vasspilka solution worked for me!

**Comment by TheWaWaR** [comment]
You also can try `(xterm-mouse-mode -1)` , works great for me :)
