### ISSUE TITLE
Org mode disappearing subheadings

### ISSUE THREAD

**Issue by Eilie** [syl20bnr/spacemacs#6795]
### Expected
1. Open org file.
2. Find every heading collapsed or at least collapsed 1 level deep.
 
### Actual
1. Open org file.
2. Find everything messed up:
![GIF](https://transfer.sh/Z6BnE/anim.gif)
`revert-buffer` imitates state of org buffer when I open it for first time in emacs. Some headings are invisible and for some reason not everything is collapsed. Headings becoming visible when collapse/uncollapse parent heading(see gif).

Not sure if it's a bug, I hope it's not.

**Comment by Eilie** [comment]
https://imgur.com/a/o86di Direct URL to gif on imgur is broken, sigh.

**Comment by Eilie** [comment]
Help.

**Comment by d12frosted** [comment]
Hey, I am not sure that I understand your problem correctly. But it seems that you are looking for [startup (initial) visibility](http://orgmode.org/manual/Initial-visibility.html).

**Comment by Eilie** [comment]
@d12frosted I think this is it, thank you!
