### ISSUE TITLE
can not init

### ISSUE THREAD

**Issue by lly365** [syl20bnr/spacemacs#6798]
![qq20160811-0](https://cloud.githubusercontent.com/assets/9651699/17586607/56102d8e-5ff5-11e6-97b8-06a3d8501f3b.png)
Warning (initialization): An error occurred while loading `/Users/Nemo/.emacs.d/init.el':

Symbol's value as variable is void: -

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

**Comment by TheBB** [comment]
Duplicate of https://github.com/syl20bnr/spacemacs/issues/4412 which is a duplicate of https://github.com/syl20bnr/spacemacs/issues/4410. This is also covered in the [FAQ](http://spacemacs.org/doc/FAQ.html#orgheadline5).
