### ISSUE TITLE
Error installing packages since latest package update

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#6801]
Since the latest update today I'm getting the following error message every time I start Spacemacs. Are any package services offline at the moment? Can anyone reproduce this problem?

> Found 14 new package(s) to install...
--> refreshing package archive: gnu... [3/3]
--> installing package: adaptive-wrap@spacemacs... [1/14]
Package adaptive-wrap is unavailable. Is the package name misspelled?
--> installing package: auctex@latex... [2/14]
Package auctex is unavailable. Is the package name misspelled?
--> installing package: auctex-latexmk@latex... [3/14]
An error occurred while installing auctex-latexmk (error: (error Package `auctex-' is unavailable))
--> installing package: cider@clojure... [4/14]
An error occurred while installing cider (error: (error Package `queue-' is unavailable))
--> installing package: clj-refactor@clojure... [5/14]
An error occurred while installing clj-refactor (error: (file-error https://melpa.org/packages/peg-20150707.2341.el Bad Request))
--> installing package: company-auctex@latex... [6/14]
An error occurred while installing company-auctex (error: (error Package `auctex-' is unavailable))
--> installing package: company-statistics@auto-completion... [7/14]
Package company-statistics is unavailable. Is the package name misspelled?
--> installing package: flycheck@syntax-checking... [8/14]
An error occurred while installing flycheck (error: (error Package `let-alist-' is unavailable))
--> installing package: flycheck-pos-tip@syntax-checking... [9/14]
An error occurred while installing flycheck-pos-tip (error: (error Package `let-alist-' is unavailable))
--> installing package: flycheck-pyflakes@python-config... [10/14]
An error occurred while installing flycheck-pyflakes (error: (error Package `let-alist-' is unavailable))
--> installing package: helm-bibtex@research-config... [11/14]
An error occurred while installing helm-bibtex (error: (error Package `let-alist-' is unavailable))
--> installing package: org-ref@research-config... [12/14]
An error occurred while installing org-ref (error: (error Package `let-alist-' is unavailable))
--> installing package: paradox@spacemacs... [13/14]
An error occurred while installing paradox (error: (error Package `seq-' is unavailable))
--> installing package: rainbow-mode@colors... [14/14]
Package rainbow-mode is unavailable. Is the package name misspelled?

**Comment by TheBB** [comment]
Elpa is down.

**Comment by sebhahn** [comment]
Thanks @TheBB

**Comment by yuvadm** [comment]
Any workaround for this situation? I just tried moving from master to develop and now all my shit is broken, can't even go back to master.

**Comment by TheBB** [comment]
Substitute the gnu URL in core/core-configuration-layer.el with one of the mirrors:

* elpa.zilongshanren.com/gnu/
* mirrors.tuna.tsinghua.edu.cn/elpa/gnu/

**Comment by TheBB** [comment]
Looks like it's back now.
