### ISSUE TITLE
Clean install has problems with installing Helm.

### ISSUE THREAD

**Issue by macbem** [syl20bnr/spacemacs#6803]
#### Description
I have a clean install of Spacemacs on Ubuntu 14.04 - when I try to run spacemacs, I get the following errors - 

Error connection time out for gnu repository!
Error (use-package): helm pre-:config hook: Symbol's function definition is void: helm-flx-mode
Error (use-package): helm pre-:config hook: Symbol's function definition is void: helm-flx-mode

and

--> installing package: adaptive-wrap@spacemacs... [1/2]
Package adaptive-wrap is unavailable. Is the package name misspelled?
--> installing package: helm-flx@spacemacs-base... [2/2]
An error occurred while installing helm-flx (error: (error Package `emacs-24.4' is unavailable))

I can't use helm because of it. I have tried running emacs in unsafe mode or with sudo, but it didn't help.

#### System Info
- OS: gnu/linux
- Emacs: 24.3.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

**Comment by TheBB** [comment]
Helm is fine, your problem is with helm-flx. Emacs 24.3 is too old. Please upgrade to a newer Emacs or (as a stopgap measure) exclude helm-flx.

See https://github.com/syl20bnr/spacemacs/issues/4443

Closing this as duplicate.
