### ISSUE TITLE
erc-yank excluded?

### ISSUE THREAD

**Issue by slackorama** [syl20bnr/spacemacs#6806]
How come `erc-yank` was excluded but the docs still it's available?
http://spacemacs.org/layers/+irc/erc/README.html

The commit doesn't have too much details:
https://github.com/syl20bnr/spacemacs/commit/b908c654d3320ab113cce3ce2b123795274481b3

Thanks,

**Comment by TheBB** [comment]
We just forgot to update the documentation, that's all.

**Comment by TheBB** [comment]
Fixed by #6809

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
