### ISSUE TITLE
evil visual mode - missing visual line navigation

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#681]
When selecting something after pressing <kbd>v</kbd> the keys <kbd>j</kbd> and <kbd>k</kbd> are not bound to ```evil-next-visual-line``` and ```evil-previous-visual-line``` which means I can not select part of the line.

I guess this is behaviour that is wanted, happy to provide a PR with the keybindings

**Comment by syl20bnr** [comment]
I never thought about it but I surely experience the same frustration!
PR welcome :-)

**Comment by cpaulik** [comment]
I also noticed that the [visual-line-navigation toggle](https://github.com/syl20bnr/spacemacs/blob/94f0b6975003ee9cb0806662c420e5618075dc7e/spacemacs/keybindings.el#L159) does not change the keybindings back. But I guess this is not super relevant since evil mode does not really use visual line mode as it is supposed to be used, see this [evil issue](https://bitbucket.org/lyro/evil/issue/188/evil-breaks-visual-line-mode)

**Comment by syl20bnr** [comment]
Do we really need to change the keybindings back ? I mean, toggling visual-line will change the bindings on `j` and `k` ?

**Comment by cpaulik** [comment]
For me <kbd>SPC t L</kbd> only changes the way the lines are broken. It does not change the way navigation with <kbd>j k</kbd> works. This is behaviour I like but I understood the documentation differently since the toggle description says "Move point according to visual lines." I had assumed that this should be toggled.

Maybe we should discuss what visual-line-mode should do in general before making a decision on that. 

I would like:
- <kbd>j k</kbd> always move visual lines, like it is now
- All operations like <kbd>dd</kbd>, <kbd>yy</kbd> and movements like <kbd>$</kbd> work on visual lines if mode is enabled, but this is an [evil issue](https://bitbucket.org/lyro/evil/issue/188/evil-breaks-visual-line-mode). So in an ideal world visual lines would behave like real lines also according to line highlighting.
- Having said that I would not change line numbering in visual line mode

**Comment by cpaulik** [comment]
This is obsolete now since it was changed back to default evil behavour.
