### ISSUE TITLE
C-b should move backward by space in the evil command buffer

### ISSUE THREAD

**Issue by jkrmr** [syl20bnr/spacemacs#6812]
#### Description
In the Evil command buffer (Ex mode?) <kbd>Ctrl</kbd>-<kbd>b</kbd> jumps to the start of the line instead of moving backward by a char.

#### Reproduction guide
- Start Emacs
- With Hybrid mode enabled 
- Enter `:` to open the Evil command buffer
- Enter `random text`
- Hit <kbd>Ctrl</kbd>-<kbd>b</kbd>

*Observed behaviour:*
The cursor moves from `text|` to `|random`. 

*Expected behaviour:*
The cursor should move from `text|` to `tex|t`.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
 better-defaults command-log dash deft elixir elm emacs-lisp evil-cleverparens evil-commentary eyebrowse git github javascript latex markdown ocaml
 (org :variables org-enable-github-support t)
 osx react restclient
 (ruby :variables ruby-version-manager 'rbenv ruby-test-runner 'rspec)
 ruby-on-rails scala
 (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/usr/local/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
 spacemacs-layouts sql spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default t syntax-checking-enable-tooltips t)
 unimpaired vimscript vinegar version-control yaml)
```

#### Backtrace
n / a

**Comment by TheBB** [comment]
Maybe I'm missing something but why is that the expected behaviour? `C-b` goes to the beginning of the ex input field in vim and this is correctly emulated by evil.

**Comment by TheBB** [comment]
Can you modify `evil-ex-completion-map` to suggest an improved version for hybrid mode users?

**Comment by jkrmr** [comment]
It turns out that I've been blissfully unaware that the default behavior of `C-b` in Vim was to jump to the beginning of the line -- I've had tpope's vim-rsi plugin installed since forever. Since an evil port of it exists (https://github.com/linktohack/evil-rsi), would this be something better left to a separate package installation? 

On the other hand, it seems intuitive to me that in Hybrid mode you'd have emacs bindings available in the ex input field, so I'd consider it an enhancement. I'll do as you suggest, thanks.

**Comment by jkrmr** [comment]
@TheBB Sorry, I'm not sure what you're referring to. I thought I'd open a PR against spacemacs but I'm not seeing `evil-ex-completion-map` anywhere in the code for it. Can you clarify?

**Comment by TheBB** [comment]
`evil-ex-completion-map` is defined by evil, not Spacemacs. It defines the keybindings available when entering ex commands, `C-b` among them. If we want to do as you suggest, we have to modify this keymap when `hybrid-mode` is active. Therefore I'm asking if someone (such as yourself) would please define which keys should be bound in this keymap and to which functions, in order to satisfy `hybrid-mode` users.

You can inspect the current value with `SPC hdK evil-ex-completion-map`.

**Comment by jkrmr** [comment]
What I was looking for, thanks: https://github.com/syl20bnr/spacemacs/blob/0283f6475b4207ff4f2f217322075eacd02030fc/layers/%2Bdistribution/spacemacs-base/local/hybrid-mode/hybrid-mode.el

:)
