### ISSUE TITLE
Magit doesn't return to status after commit

### ISSUE THREAD

**Issue by toupeira** [syl20bnr/spacemacs#6813]
#### Description :octocat:
Magit used to stay on the status screen after committing, but this stopped working at some point over the past few weeks, and now I always end up in my original buffer after committing. It doesn't seem like this was a deliberate change in Magit, so I'm wondering if it's caused by something in Spacemacs, or my own configuration?

I don't have any Magit customizations except for `git-magit-status-fullscreen t`, but the behaviour is the same without it.

#### Reproduction guide :beetle:
- Start Emacs
- Open a file from a Git repository and make a change
- Open Magit status using `SPC g s`
- Commit using `cc` etc.

*Observed behaviour:* :eyes: :broken_heart:
I'm back at the file I was editing.

*Expected behaviour:* :heart: :smile:
I'm back at the Magit status screen.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: nil (rev. e51a89a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t)
 better-defaults colors command-log dash games
 (git :variables git-magit-status-fullscreen nil)
 github helm mu4e org pdf-tools
 (ranger :variables ranger-show-dotfiles nil)
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-term-shell "emacs-shell" shell-enable-smart-eshell t)
 syntax-checking version-control graphviz elixir elm emacs-lisp emoji erlang html javascript lua
 (markdown :variables markdown-live-preview-engine 'vmd)
 php python ruby ruby-on-rails shell-scripts vimscript yaml dotfiles-ui dotfiles-evil dotfiles-org)
```

**Comment by TheBB** [comment]
I cant' reproduce this.

**Comment by toupeira** [comment]
@TheBB thanks, I narrowed it down to `persp-mode` and my usage of `def-auto-persp`. Haven't found a workaround yet, but that definitely excuses Spacemacs :) Sorry for the noise!
