### ISSUE TITLE
Bug of "evil-avy-goto-line"

### ISSUE THREAD

**Issue by AllenSue** [syl20bnr/spacemacs#6814]
#### Description
Incorrect display of evil-avy-goto-line when linum-mode is enabled.
Test on C type files.

#### Reproduction guide
- Start Emacs
- Open a C type file.
- M-x and type in linum-mode.
- SPC y and see what's happening.

*Observed behaviour:*
Sometimes not all lines show the jump key and sometimes several lines still show jump key until move the cursor into those lines.

*Expected behaviour:*
Work just as linum-mode is disabled.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

#### Backtrace
```

```

**Comment by TheBB** [comment]
Can you provide a C-file that reproduces this? I don't seem to be able to.

**Comment by AllenSue** [comment]
[go.c.zip](https://github.com/syl20bnr/spacemacs/files/416588/go.c.zip)

I got error with this file.

**Comment by TheBB** [comment]
https://gist.github.com/bedc905bd319dcd75898219709ca95bc

If others are interested

**Comment by TheBB** [comment]
What is `SPC y` bound to on master, again?

**Comment by TheBB** [comment]
Okay. What I see is that sometimes the line numbers vanish, but all the jump keys are visible. However I was able to reproduce this effect with emacs -q as well, so this should probably be reported either to avy or to linum. It's not our bug.

**Comment by AllenSue** [comment]
OK, I guess maybe it comes by some non-English characters. Nevermind, it not bother me very much, and should I close this issue?

**Comment by TheBB** [comment]
Well that's up to you, but I don't think it will do much good here.
