### ISSUE TITLE
Add option to use default Flycheck icons

### ISSUE THREAD

**Issue by sbdchd** [syl20bnr/spacemacs#6816]
I would like an option to be able to use the default Flycheck fringe icons, instead of the ones defined by spacemacs.

**Comment by TheBB** [comment]
You can redefine the error levels with other bitmaps.

https://github.com/syl20bnr/spacemacs/blob/develop/layers/+checkers/syntax-checking/packages.el#L58-L74

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/6817
