### ISSUE TITLE
Spacemacs doesn't open correctly

### ISSUE THREAD

**Issue by abasar** [syl20bnr/spacemacs#6822]
I have installed Spacemacs on cygwin 2 days ago, and today it stopped working. I have tried to reinstall it a few time and now when I start the program in the "status bar" it says "failed to download 'melpa' archive", and if I start it with -debug-init this is what I get:

`Debugger entered--Lisp error: (error "Package `evil-' is unavailable")
  signal(error ("Package `evil-' is unavailable"))
  error("Package `%s-%s' is unavailable" evil "")
  package-compute-transaction(nil ((evil)))
  package-install(evil)
  (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-$
  (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" $
  (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spa$
  (let ((warning-minimum-level :error)) (condition-case nil (require pkg) (error (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-p$
  spacemacs/load-or-install-package(evil t nil)
  spacemacs/load-or-install-protected-package(evil t)
  spacemacs/init()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %d or above.") emacs-version spacemacs-emacs-mi$
  eval-buffer(#<buffer  *load*> nil "/home/abasar/.emacs.d/init.el" nil t)  ; Reading at buffer position 1077
  load-with-code-conversion("/home/abasar/.emacs.d/init.el" "/home/abasar/.emacs.d/init.el" t t)
  load("/home/abasar/.emacs.d/init" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320\nB^R\321\202;^@\316\322^S\323^A\322\211#\210^K\322=\203$
  command-line()
  normal-top-level()`

I have tried looking at other people that had this problem but couldn't really understand the solutions, can someone please help? 
Thanks

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/6821
