### ISSUE TITLE
Clojure layer is not installing

### ISSUE THREAD

**Issue by VictorVoid** [syl20bnr/spacemacs#6823]
#### Description
I put a layer clojure but is not properly installing =( 

![screenshot from 2016-08-14 10 30 07](https://cloud.githubusercontent.com/assets/6734111/17649757/6010bdb4-620a-11e6-87d9-c6ed71c38088.png)

#### Reproduction guide
- Start Emacs

*Observed behaviour:*

An error occurred while installing cider (error: (file-error https://melpa.org/packages/cider-20160806.2354.tar Not found))
An error occurred while installing clj-refactor (error: (file-error https://melpa.org/packages/cider-20160806.2354.tar Not found))

Warning (spacemacs): 
Error connection time out for melpa repository!

*Expected behaviour:*
Without errors 

#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp javascript markdown syntax-checking html shell colors clojure)
```

**Comment by bmag** [comment]
https://github.com/syl20bnr/spacemacs/issues/6821#issuecomment-239676456:
> MELPA is currently unavailable. Nothing to do but wait until it is fixed.
