### ISSUE TITLE
MELPA package refresh doesn't respect dotspacemacs-elpa-timeout

### ISSUE THREAD

**Issue by tadfisher** [syl20bnr/spacemacs#6830]
#### Description :octocat:

MELPA is down today (2016-08-15). When starting a fresh Spacemacs, packages are automatically refreshed, but the defunct MELPA connection does not time out according to `dotspacemacs-elpa-timeout`. I have not timed it but it takes on the order of several minutes to time out the connection to MELPA. This severely impacts using Spacemacs, as pressing `C-g` aborts Spacemacs startup, and waiting several minutes for the connection to time out is not ideal.
#### Reproduction guide :beetle:
- Set `dotspacemacs-elpa-timeout` to a low value (i.e. `2`)
- Somehow route melpa.org:443 to a host which accepts the connection but does not respond, or try this on a day MELPA is down.
- Start Emacs

_Observed behaviour:_ :eyes: :broken_heart:

Spacemacs reports it is connecting to MELPA, and it does not time out for several minutes.

```
(Spacemacs) --> refreshing package archive: melpa... [1/3]
Contacting host: melpa.org:443
```

_Expected behaviour:_ :heart: :smile:

The connection to MELPA should time out within the value specified by `dotspacemacs-elpa-timeout`.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 36f3b63)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp
                 (erc :variables erc-server-list
                      '(REDACTED))
                 (git :variables git-magit-status-fullscreen t)
                 github helm markdown org pass
                 (rust :variables rust-format-on-save t)
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 scala spell-checking syntax-checking themes-megapack)
```

**Comment by rossvor** [comment]
melpa.org seems down again and the issue is still occurring.
