### ISSUE TITLE
Fresh install / bootstrap of spacemacs is failing

### ISSUE THREAD

**Issue by rebcabin** [syl20bnr/spacemacs#6833]
I can no longer run spacemacs (fresh download install, no .emacs.d, .spacemacs moved out of the way). Emacs produces the following error

    Error connection time out for melpa repository! 
    Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error (error Package `spacemacs-theme-' is unavailable))

This has been the case since 13 August at least.

**Comment by TheBB** [comment]
Please do not hesitate to contact MELPA about it. There's not much we can do.

**Comment by d12frosted** [comment]
Thanks for bringing up this issue. I am closing this one in favour of #6836.
