### ISSUE TITLE
Numerous 404's on spacemacs web page ?

### ISSUE THREAD

**Issue by rebcabin** [syl20bnr/spacemacs#6835]
Clicking "contribute" on the front page of spacemacs.org yields a 404.

looks like the URL is http://spacemacs.org/doc/CONTRIBUTE.html

also http://spacemacs.org/doc/HOWTOs.html is 404, off the http://spacemacs.org/doc/QUICK_START.html page.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs.org/issues/6

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs.org/issues/6 and https://github.com/syl20bnr/spacemacs.org/issues/7 cover these.

https://github.com/syl20bnr/spacemacs.org is the repository for the website.

Thanks though. :-)
