### ISSUE TITLE
Cannot start spacemacs if melpa.org is down

### ISSUE THREAD

**Issue by tcfunk** [syl20bnr/spacemacs#6836]
That's all, really.

Running on OS X. Not a fresh install, although I tried a fresh install with the same results.

**Comment by rpls** [comment]
Weird thing is, usually if I can't reach one of the repositories, it will just time out and continue (and not install the packages). But it appears the connection can be opened, but hangs, causing emacs to hang indefinitely. Is it possible to add a timeout to this?

And is there a machanism to automatically deactivate a layer, if packages can't be fetched?

**Comment by adriandeveloper** [comment]
Would be cool if there was a fallback to Melpa stable, or better yet, just not freezing emacs if you're not able to connect.

**Comment by Profeten** [comment]
503 Service Unavailable

**Comment by endrebak** [comment]
I deleted spacemacs to reinstall and now I cannot reinstall due to this :(

How do I fix it?

**Comment by logorrhea** [comment]
@endrebak I feel like it was more of a reminder of how fragile spacemacs is compared to vim =\

**Comment by d12frosted** [comment]
To be fair, this is the first time MELPA went down for such a long time. At least on my memory. I do understand how bad it is for people willing to install new packages or start Emacs on fresh Spacemacs installation. Spacemacs can't function without some packages. Layer system is all about combining packages. And Spacemacs depends on third-party package archives. When something happens to them there is little we can do. Now MELPA is up and running, so we can try to solve this issue. Most probably we'll provide snapshot with all packages used by Spacemacs, so in future when something happens with any of third-party archives users always can automatically fallback to snapshots. It's hard to give any ETA, but keep tuned 😸 

> I feel like it was more of a reminder of how fragile spacemacs is compared to vim

Please, don't bring Emacs vs Vim here. It's about any software depending on third-party services.

**Comment by d12frosted** [comment]
BTW, if someone still encounter this problem (though I sure that you should not) you could use following workaround. 

```
(setq configuration-layer--elpa-archives
      '(("melpa" . "elpa.zilongshanren.com/melpa/")
        ("org" . "elpa.zilongshanren.com/org/")
        ("gnu" . "elpa.zilongshanren.com/gnu/")))
```

Just put it into `dotspacemacs/user-init`. Credits goes to people from https://github.com/melpa/melpa/issues/4156

**Comment by lverns** [comment]
Melpa must still be experiencing issues. I had to `rm ~/.emacs.d/elpa -rf` and add the above code in order to do a fresh install.

**Comment by hello-code** [comment]
@endrebak How do you fixed it?

> Warning (spacemacs): 
> Error connection time out for melpa repository!
> Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (error Package `spacemacs-theme-' is unavailable))
> Warning (initialization): An error occurred while loading `/Users/labsenter/.emacs.d/init.el':
> 
> error: Package `evil-' is unavailable

**Comment by endrebak** [comment]
I didnt fix it, melpa started working again 🙂

**Comment by hello-code** [comment]
@endrebak 
I found increase timeout will solve this error.
`dotspacemacs-elpa-timeout 10`

**Comment by qbe** [comment]
Melpa caused my spacemacs to hang as stated above. Is there any news on fallback options ?
