### ISSUE TITLE
Python layer flake8 dependency

### ISSUE THREAD

**Issue by kalouantonis** [syl20bnr/spacemacs#6838]
The python layer README is missing any mention of how to add PEP-8 highlighting. 

I've managed to figure out that using `pip install flake8` solves that problem. Shouldn't this also be included in the README?

**Comment by TheBB** [comment]
Certainly you can add it to the readme. `SPC e v` should tell you about the possible syntax checkers in a python buffer. IIRC the options are pylint and flake8.

**Comment by kalouantonis** [comment]
There we go, sorry for the mess

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
