### ISSUE TITLE
cursor in *Buffer List* will move to the start of buffer cyclically

### ISSUE THREAD

**Issue by tepmnthar** [syl20bnr/spacemacs#6844]
#### Description
Cursor in *Buffer List* will move to the start of buffer cyclically.
And `linum-mode` doesn't function correctly in *Buffer List* too. 
#### Reproduction guide
- Start Emacs
- Open anything
- M-x global-linum-mode
- C-x C-b (show *Buffer List*)
- see what is wrong

*Observed behaviour:*
Cursor in *Buffer List* will move to the start of buffer cyclically.
Line-num is weired, also changed cyclically
*Expected behaviour:*
Nothing will change cyclically.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(TEP themes-megapack auto-completion emacs-lisp git org javascript html react
     (shell :variables shell-default-shell 'term))
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

TEP is my private layer
```
(defun TEP/init-switch-window()
  (use-package switch-window
    :defer t)
  (setq-default switch-window-shortcut-style 'alphabet)
  (setq-default switch-window-timeout nil)
  (global-set-key (kbd "C-x o") 'switch-window)
  )
(defun TEP/init-expand-region()
  (use-package expand-region
    :defer t)
  (global-set-key (kbd "C-=") 'er/expand-region)
  )

(with-eval-after-load "company"
  (global-set-key (kbd "S-SPC") 'company-complete))
;; 显示行号
(global-linum-mode)
;; (global-set-key (kbd "C-v") 'scroll-up-command)
(add-hook 'org-mode-hook
          (lambda()
            (linum-mode -1)))
(setq column-number-mode t)

;; 高亮括号配对
(electric-pair-mode)

;; 高亮括号配对
(show-paren-mode t)
(setq show-paren-style 'parenthesis)
```

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/2667

That issue has a workaround. It was considered wontfix because it's not part of regular Spacemacs workflow to be using the buffer list. Feel free to make a PR if you like.

**Comment by d12frosted** [comment]
Closing this as duplicate / wontfix. As TheBB said, feel free to PR 😸
