### ISSUE TITLE
Adding racket layer hangs Spacemacs upon installation

### ISSUE THREAD

**Issue by mattnedrich** [syl20bnr/spacemacs#6845]
<PLEASE REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE>
#### Description
DESCRIPTION OF THE PROBLEM

#### Reproduction guide
- Start Emacs
- Add racket layer (https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/racket)

*Observed behaviour:*
Spacemacs hangs and is unresponsive

*Expected behaviour:*
It should install the racket layer

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults evil-commentary emacs-lisp
                 (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rvm ruby-test-runner 'rspec)
                 git markdown swift python html
                 (javascript)
                 typescript spell-checking syntax-checking version-control js-mocha)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment]
This is just due to MELPA being down again. It has nothing to do with racket.

**Comment by TheBB** [comment]
Take it here: https://github.com/syl20bnr/spacemacs/issues/6833

**Comment by mattnedrich** [comment]
Gotcha, thanks.
