### ISSUE TITLE
how set .spacemacs to run [SPC T M] when the program running？

### ISSUE THREAD

**Issue by arstum** [syl20bnr/spacemacs#6851]
I like use spacemacs with full screen.
I must enter [SPC T M] after run the spacemacs everytime.
This is the wrong way to lifting efficiency.
Who can tell me to how set .spacemacs to run [SPC T M] when the program running.

**Comment by lsytj0413** [comment]
Hav you try use the varible **dotspacemacs-fullscreen-at-startup**, **dotspacemacs-maximized-at-startup** in the .spacemacs file?

**Comment by TheBB** [comment]
As @lsytj0413 says the correct way is to use those variables.

You can check what function is run by a keybinding using `SPC h d k`. Then you can run that function in dotspacemacs/user-config. 

> SPC T M runs the command spacemacs/toggle-maximize-frame, which is an
interactive Lisp function in `keybindings.el'.

Therefore:

    (spacmacs/toggle-maximize-frame)

Or:

    (spacemacs/toggle-maximize-frame-on)

**Comment by arstum** [comment]
@TheBB You`re the better way,but it can`t take effect。

in the .spacemacs:
(defun dotspacemacs/user-config (
                                 (spacemacs/toggle-maximize-frame-on)
                                 )
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
  )

restart but no change.

**Comment by TheBB** [comment]
That isn't valid elisp.

```elisp
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
  (spacemacs/toggle-maximize-frame-on)
  )

```

**Comment by arstum** [comment]
It's work.
Thank you.
