### ISSUE TITLE
Send <C-r> to ansi-term

### ISSUE THREAD

**Issue by sbdchd** [syl20bnr/spacemacs#6852]
When using a terminal, I like to use <kbd>C-r</kbd> to search through my previous command history; however, this doesn't work in ansi-term.

If I disable evil-mode, I can send <kbd>C-r</kbd> to ansi-term, but I would like to know how to do so with evil-mode enabled.

Thanks.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/2345

**Comment by TheBB** [comment]
It's tricky to rebind term-mode keys. This is the best way I have found.

```elisp
(defun bb/setup-term-mode ()
  (evil-local-set-key 'insert (kbd "C-r") 'bb/send-C-r))

(defun bb/send-C-r ()
  (interactive)
  (term-send-raw-string "\C-r"))

(add-hook 'term-mode-hook 'bb/setup-term-mode)
```

**Comment by sbdchd** [comment]
Works like a charm. Thanks!
