### ISSUE TITLE
Long lines in compilation buffer lead to 100% cpu use that doesn't ever stop (X only)

### ISSUE THREAD

**Issue by jamescasbon** [syl20bnr/spacemacs#6854]
#### Description
Long lines in compilation buffer lead to 100% cpu use that doesn't stop.

This only affects spacemacs in X window.  It does not affect spacemacs run with (emacs -nw).  It also does not affect vanilla emacs.  I tried disabling all compilation regexps but this does not help.  Found this bug on both arch and rhel6.  If you disable follow compilation output, it seems to only affect you once you scroll the buffer.

#### Reproduction guide
- Start Emacs (with X, i.e. without -nw)
- SPC c C (compile)
- enter python -c "for _ in range(100): print('abcdefg ' * 30)"

*Observed behaviour:*
Cpu spins for 100%, never returns.
Ctrl g cannot interrupt.

*Expected behaviour:*
Can use emacs.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git org syntax-checking version-control python)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment]
I can't really reproduce this, even with 300 in place of 30, I don't get any special CPU usage.

**Comment by jamescasbon** [comment]
Hmmm, thanks for trying. It's very reproducible for me on different linuxes.  Are you trying on linux?

**Comment by TheBB** [comment]
Yes, Linux, same Emacs version. I'm on develop though.

**Comment by izahn** [comment]
There are problems with font-locking long lines in emacs generally, see http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21077 for example. Does disabling `font-lock-mode` help? If so You could add `(add-hook 'compilation-mode-hook (lambda() (font-lock-mode -1)))` to your `dotspacemacs/user-config`.

Note per the emacs bug report I mentioned this should be dramatically improved in emacs 25.

**Comment by jamescasbon** [comment]
Thanks @izahn seems like that does improve things.  I can get to about (x 100) fine but not (x 150).

I suppose I must close and wait for an upstream fix.  The only nagging doubt is that a vanilla emacs doesn't show the problem, so there must be something in the font setup that is related?

**Comment by izahn** [comment]
@jamescasbon Yes, I also see that vanilla emacs is way faster, so `font-lock-mode` isn't the main problem (though it is a problem, and disabling it does speed things up).  Looking further I noticed that spacemacs sets `compilation-scroll-output` to a non-nil value. In my tests this does slow things down, and I would guess that is the reason for the difference between vanilla emacs and spacemacs. Try `(setq compilation-scroll-output 1)` and see if that solves your problem.

**Comment by jamescasbon** [comment]
@izahn thanks both tips helped.   I just updated to emacs 25 and it is really much better on that.  So this problem will be resolved by upstream.
