### ISSUE TITLE
SPACEMACSDIR unrecognized

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#6855]
Spacemacs does not recognize environment variable SPACEMACSDIR as it does not load $SPACEMACSDIR/init.el on startup (only `~/.spacemacs` or `~/.spacemacs.d/init.el`).

After `SPC f e d` where $SPACEMACSDIR is not set to `/home/xged/`(default):
`find-file-existing: /home/xged/.spacemacs.d/init.el does not exist`

- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 36f3b63)
- Graphic display: t

**Comment by bmag** [comment]
@xged please provide a detailed recipe to reproduce the bug. It was working last time I tried (1 or 2 weeks ago).

**Comment by xged** [comment]
@bmag I think reproduction and expectation are obvious.

**Comment by bmag** [comment]
No, they are not. I have no idea what did you do to set SPACEMACSDIR, or what's the difference between your regular spacemacs config to the config in SPACEMACSDIR. I tried it now, and it works for me, so I have no way to reproduce your problem and help you.

This is what I tried, from a bash terminal:
```sh
SPACEMACSDIR=~/tmp/spcmcs emacs &
```
The directory `~/tmp` existed before, but `spcmcs` directory didn't. This command started Spacemacs and it tried to install a new dotfile to `~/tmp/spcmcs/init.el` (I stopped the process once I saw it installs to the correct place), which is exactly what was supposed to happen.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.0.95.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 36f3b63)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup nil auto-completion-enable-help-tooltip t company-tooltip-align-annotations t)
 command-log dash evil-cleverparens
 (git :variables git-magit-status-fullscreen t)
 ibuffer imenu-list nlinum org pdf-tools
 (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
 smex syntax-checking version-control c-c++
 (clojure :variables clojure-enable-fancify-symbols nil)
 emacs-lisp
 (latex :variables latex-enable-auto-fill t latex-enable-folding t)
 markdown octave python ruby common-lisp spaceline-tweaks window-purpose window-tweaks themes-megapack
 (theming :variables theming-modifications
          '((spacemacs-dark
             (aw-leading-char-face :foreground "red" :height 3.0))
            (spacemacs-light
             (aw-leading-char-face :foreground "red" :height 3.0))
            (monokai
             (aw-leading-char-face :foreground "red" :height 3.0))
            (flatland
             (aw-leading-char-face :foreground "red" :height 3.0)))))
```

**Comment by xged** [comment]
@bmag I added `export SPACEMACSDIR=MY_DIR` to `~/.zshrc` (_zsh_ shell). SPACEMACSDIR is part of the output from `printenv`. `init.el` is in $SPACEMACSDIR and in `~/.spacemacs.d`. Emacs loads fine until I remove `~/.spacemacs.d/init.el`.

**Comment by bmag** [comment]
I'm not sure I understand your last two sentence. Are you saying that:
> If `~/.spacemacs.d/init.el` exists, then Spacemacs loads correctly configuration from SPACEMACSDIR. But if `~/.spacemacs.d/init.el` doesn't exist, then Spacemacs encounters an error during startup.

Are you using the same `init.el` in both SPACEMACSDIR and `~/.spacemacs.d`, or are there any differences?

In any case, here are two things to try:
- run emacs with the following terminal command. Does Spacemacs load the correct config?
```sh
SPACEMACSDIR=/path/to/desired/dir emacs
```

- after Emacs starts, what is the output of the following command? Please try it both with Spacemacs and with stock emacs (`emacs -q`).
```
M-: (getenv "SPACEMACSDIR")
```
 (`M-:` evaluates arbitrary elisp code)

**Comment by xged** [comment]
@bmag `init.el` files are the same.

Turns out running Emacs via terminal is all fine in contrast to running it via menu (to not popup an extra window). Thought it was same thing, sorry.
