### ISSUE TITLE
[git] rebase interactive: move line down/up

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#6860]
#### Reproduction guide :beetle:
- Start Emacs
- `SPC g s`
- `l L`
- Move cursor on a commit
- `r i` (*git-rebase-todo* buffer)
- `gj`/`gk`
- *Please answer y or n.  Revert buffer from file ../.git/rebase-merge/git-rebase-todo? (y or n)* `y`

*Observed behaviour:* :eyes:
Cursor moves to the top

*Expected behaviour:* :heart:
Line moves down/up

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 36f3b63)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion better-defaults emacs-lisp git markdown org
                (shell :variables shell-default-position 'full)
                syntax-checking version-control python github javascript)
```
**Edit**: `M-j` `M-k` started working for me now (runnning Emacs via terminal instead of via menu). Just [git] docs needs to be updated, I suppose.

**Comment by TheBB** [comment]
I'm not sure why you expect that. It says in the rebase window that the keys for this are `M-j` and `M-k`.

**Comment by xged** [comment]
@TheBB `M-j` `M-k` not working as well. I 'took' `gj` `gk` from [git] docs.

**Comment by TheBB** [comment]
Okay, assuming by “[git]” you mean “the git layer”, fixed in https://github.com/syl20bnr/spacemacs/commit/25eb00c24fd25a3e166f3df91512906cd68cb462
