### ISSUE TITLE
(Spacemacs) Error in dotspacemacs/user-config: Symbol's value as variable is void: mouse-wheel-mode

### ISSUE THREAD

**Issue by arronmabrey** [syl20bnr/spacemacs#6865]
#### Description :octocat:
(Spacemacs) Error in dotspacemacs/user-config: Symbol's value as variable is void: mouse-wheel-mode

#### Reproduction guide :beetle:
- `git clone git@github.com:syl20bnr/spacemacs.git ~/.emacs.d`
- `cd ~/.emacs.d && git checkout develop` (optional this error happens on both master and develop)
- `emacs`
- wait for everything to compile/install

*Observed behaviour:* :eyes: :broken_heart:
(Spacemacs) Error in dotspacemacs/user-config: Symbol's value as variable is void: mouse-wheel-mode

*Expected behaviour:* :heart: :smile:
I expect to not see any errors using a fresh install of spacemacs

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 5001e21)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults clojure emacs-lisp fasd git github gtags javascript themes-megapack markdown
                 (ranger :variables ranger-show-preview t)
                 (ruby :variables ruby-version-manager 'rbenv ruby-test-runner 'rspec)
                 theming org react
                 (shell :variables shell-default-height 40 shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh")
                 spell-checking syntax-checking
                 (version-control :variables version-control-global-margin t version-control-diff-tool 'git-gutter))
```

**Comment by arronmabrey** [comment]
nevermind, I believe I narrowed it down to my config.

**Comment by arronmabrey** [comment]
Actually I narrowed id down to one line in my `dotspacemacs/user-config`

```elisp
(spacemacs/toggle-centered-point-globally-on)
```

If I comment that line out, the error goes away.

Also, I hadn't noticed before, but turns out centered-point seems to not be working for me period. Even if I comment `(spacemacs/toggle-centered-point-globally-on)` and try and toggle it manually via `SPC t -` or `SPC t C--`

**Comment by TheBB** [comment]
Fixed by https://github.com/syl20bnr/spacemacs/pull/6866

**Comment by arronmabrey** [comment]
@TheBB wow thanks! that was crazy fast

**Comment by arronmabrey** [comment]
@TheBB I can confirm this fix in develop, thanks again!
