### ISSUE TITLE
Remap ESC for ansi-term

### ISSUE THREAD

**Issue by sbdchd** [syl20bnr/spacemacs#6871]
When hitting <kbd>esc</kbd> in `ansi-term`, evil switches from insert to normal mode as expected.

This is great for most things, but when using the terminal I want to be able to send <kbd>esc</kbd> to some interactive programs.

How would I remap the escape sequence for `ansi-term` to something like neovim's <kbd>C-\</kbd><kbd> C-n</kbd>?

_Note:_ if I exit `evil-mode`, I am able to send <kbd>esc</kbd> to programs in the terminal.

Edit: I want to have <kbd>esc</kbd> send <kbd>esc</kbd> to the shell, and another key bind, like <kbd>C-\</kbd><kbd> C-n</kbd>, to switch from insert (in the terminal) to normal mode.

**Comment by NJBS** [comment]
`multi-term` handles it by binding it to `C-c C-e`.

You can emulate that in `ansi-term` with something like this:
``` elisp
  (defun term-send-esc ()
    "Send ESC in term mode."
    (interactive)
    (term-send-raw-string "\e"))

  (evil-define-key 'insert term-raw-map (kbd "C-c C-e") 'term-send-esc)
```
