### ISSUE TITLE
Add ox-twbs integration to org-mode export

### ISSUE THREAD

**Issue by yilihong** [syl20bnr/spacemacs#6878]
I am wondering if ox-twbs could be added to the default export options of the org-mode (C-c C-e)?

It is possible in regular emacs but seems to lack such option in spacemacs. An extension similar to the gfm extension for the org-mode will do.

Thank you.

**Comment by TheBB** [comment]
Feel free to make a PR adding the ox-twbs package.

**Comment by yilihong** [comment]
thanks @TheBB 

Wonder if someone could help out here. The task is to add the ox-twbs.el under:
layers/org/extensions/ and modify the extensions.el to add the export option. Unfortunately, I just switched from vim a few days ago and not quite literate in elisp yet.

The ox-twbs file is here: https://github.com/marsmining/ox-twbs/blob/master/ox-twbs.el

I think there might be use cases for this, as the exported HTML using bootstrap looks much better than the default.
