### ISSUE TITLE
cannot get some external links to work in org-mode

### ISSUE THREAD

**Issue by yilihong** [syl20bnr/spacemacs#6879]
#### Description

Cannot get some external links to work in org-mode. In particular:
bibliography:references.bib
This is after org-ref is installed as an optional package in spacemacs
#### Reproduction guide
- Start Emacs
- Install org-ref
- open a file called "test.org"
  -type "bibliography:references.bib"
  -again, in a new line, type "file:references.bib", the external link shows up

_Observed behaviour:_
There is no external link showing up for the line "bibliography:references.bib"

_Expected behaviour:_
"bibliography:references.bib" will show up as a clickable external link
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp git github markdown python
                 (latex :variables latex-build-command "LatexMk" latex-enable-auto-fill nil latex-enable-folding nil)
                 company-mode html themes-megapack
                 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-enable-smart-eshell t)
                 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t)
                 syntax-checking
                 (version-control :variables version-control-diff-tool 'git-gutter  version-control-global-margin t)
                 flycheck
                 (org :variables org-enable-github-support t))
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by yilihong** [comment]
this was resolved by adding:

(require 'org-ref)

to the user config file. I suspect the integration with org-ref is still not perfect? Adding org-ref to the additional layer didn't work.

**Comment by jajpater** [comment]
I guess that's a feature not a bug.
