### ISSUE TITLE
Turning aggressive-indent for LIsp modes

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#688]
For other modes, `aggressive-indent` can be annoying. But for Lisp modes, i.e. Emacs Lisp, it's just so much more productive. No editing trick can beat it.

**Comment by syl20bnr** [comment]
aggressive-indent it already installed in the spacemacs layer, <kbd>SPC t i</kbd> to enable it. I cannot enable it by default because it plays in the same field as `paredit` to my mind, this is a somewhat unexpected behavior for a novice.

You can hook it to emacs-lisp mode in your dotifile if you want it enabled by default.

**Comment by tuhdo** [comment]
Yes I am currently enabling it in Lisp modes in my personal config. But I want to discuss about enabling it by default since it's much superior to any manual indentation and more pleasant to write Lisp. It's less convenient as in other modes. i.e. if you delete a word or Word or anything, everything below is indented automatically. How can something be more useful?

**Comment by syl20bnr** [comment]
Aggressive indent is indeed a great package but sometimes it gets in the way. This is similar as automatic deletion of white spaces on save, very handy but it gets in the way: they both alter the buffer behind the scene which makes code review sometime awful. They impose their conception of the world upon a code base, this is not how things work, this is the authors/maintained who impose the code style.

For this reason these settings (white spaces cleanup, auto-indent of whole sexps etc...) cannot be imposed to the user. Using them must be a conscious act, it is a certification that the user understand the consequences about using them.

I won't make this choice for them but I make the option available to them.

**Comment by tuhdo** [comment]
But how can it can it the way when writing Lisp? Let's look at [this demo](https://raw.githubusercontent.com/Bruce-Connor/aggressive-indent-mode/master/lisp-example.gif). Currently, `indent-defun` is bound to no key. When writing Lisp prior the existence of `aggressive-indent`, I had to reindent defun to make it look properly after I made some changes. And the point of `aggressive-indent` is that it does it for me automatically. Do you write code with `aggressive-indent` always turned on?

**Comment by syl20bnr** [comment]
It gets in the way for the same reason that deleting white spaces on save automatically gets int the way, especially when working with other people code and doing code reviews and PRs.

See my answer above.

The name of the package is self explanatory to me, it aggressively reindents the code, it is too much aggressive to be on by default on a distribution like spacemacs. A section can be added to the documentation to show how to hook aggressive-indent.

**Comment by tuhdo** [comment]
Alright that's fine to me then :). I just want people to have more pleasant writing Lisp code. `aggressive-indent` only indents the current defun point is in, not the whole buffer, so the problem you described with whitespace on save won't happen.

> It gets in the way for the same reason that deleting white spaces on save automatically gets int the way, especially when working with other people code and doing code reviews and PRs.

You may check [ws-butler](https://github.com/lewang/ws-butler). It only trims whitespace the lines you touched, and upon save only. With it, I never have to worry about trailing whitespace anymore. In general, I favor automatic solutions over any editing tricks.

**Comment by syl20bnr** [comment]
We discussed about this in this issue #235 and we forgot to follow up on this. Thanks to point it out again.

**Comment by syl20bnr** [comment]
I re-opened the issue about whitespaces and ws-butler.

**Comment by syl20bnr** [comment]
I consider this question answered, for `ws-butler` we can continue on the issue referenced above.
