### ISSUE TITLE
Sublimity not working with Spacemacs

### ISSUE THREAD

**Issue by abhi18av** [syl20bnr/spacemacs#6892]
Hi, everyone!!

I am literally in awe of this package for emacs but when I installed it in Spacemacs, and setting it on at startup inside user-config, I don't see anything at all.

Please let me know if I'm missing a crucial piece or perhaps it's a bug?

**Comment by duianto** [comment]
It seems to be working here:
#### System Info :computer:
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 4071e0c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
In .spacemacs
i added sublimity to the additional packages
`   dotspacemacs-additional-packages '(sublimity)`

and these lines to the user-config
```
(defun dotspacemacs/user-config (
 (require 'sublimity)
  (require 'sublimity-scroll)
  ;; (require 'sublimity-map)
  ;; (require 'sublimity-attractive)
)
```

uncomment them one at a time: -scroll, -map, or -attractive
and comment out the other two, restart emacs, and run `M-x sublimity-mode` to enable it.

**Comment by abhi18av** [comment]
Yes, this perfectly solves everything. Though I added ``` (sublimity 1)`` in the user-config as well.

Thank you @duianto for the prompt reply,  appreciate it ;)
