### ISSUE TITLE
Ranger preview/spaceline redraw issue

### ISSUE THREAD

**Issue by arronmabrey** [syl20bnr/spacemacs#6894]
#### Description :octocat:

Ranger preview/spaceline redraw issue
#### Reproduction guide :beetle: [updated]
- `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
- checkout current master [9f9faa4]  or current develop [b8ca74e] (verified with both)
- start spacemacs for first time and accept defaults
- edit generated `.spacemacs` file with the following diff 

``` diff
diff --git a/.spacemacs b/.spacemacs
index 170910c..030dd92 100644
--- a/.spacemacs
+++ b/.spacemacs
@@ -34,7 +34,10 @@ values."
      ;;        shell-default-position 'bottom)
      ;; spell-checking
      ;; syntax-checking
-     ;; version-control
+     version-control
+     (ranger :variables
+             ranger-show-literal nil
+             ranger-show-preview t)
      )
    ;; List of additional packages that will be installed without being
    ;; wrapped in a layer. If you need some configuration for these
@@ -206,7 +209,7 @@ values."
    ;; If non nil line numbers are turned on in all `prog-mode' and `text-mode'
    ;; derivatives. If set to `relative', also turns on relative line numbers.
    ;; (default nil)
-   dotspacemacs-line-numbers nil
+   dotspacemacs-line-numbers t
    ;; If non-nil smartparens-strict-mode will be enabled in programming modes.
    ;; (default nil)
    dotspacemacs-smartparens-strict-mode nil
```
- quit/relaunch spacemacs
- invoke ranger `SPC a r` and preview files (I previewed the core spacemacs elisp file, but any should work)

_Observed behaviour:_ :eyes: :broken_heart:
![spacemacs-ranger-bug](https://cloud.githubusercontent.com/assets/128298/17872548/981ad138-688e-11e6-8814-e7269080d5e3.gif)

_Expected behaviour:_ :heart: :smile:
not that ^^^ ;-)
### Note: these values may no longer apply / I have reproduced with fresh installs as detailed above
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 4071e0c)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults clojure emacs-lisp fasd git github gtags javascript themes-megapack markdown
                 (ranger :variables ranger-show-literal nil ranger-show-preview t)
                 (ruby :variables ruby-version-manager 'rbenv ruby-test-runner 'rspec)
                 theming org react
                 (shell :variables shell-default-height 40 shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh")
                 spell-checking syntax-checking
                 (version-control :variables version-control-global-margin t version-control-diff-tool 'git-gutter))
```

**Comment by arronmabrey** [comment]
I cloned a fresh copy of master with a default generated `.spacemacs` file and this bug is not present. I switched to the latest develop with the fresh `.spacemacs` file and the bug is not present. So it must be something in my config. I try to isolate it and report back.

**Comment by arronmabrey** [comment]
Here are the distilled reproduction steps using both fresh install of current master OR current develop.

- `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
- checkout current master [9f9faa4]  or current develop [b8ca74e] \(verified with both\)
- start spacemacs for first time and accept defaults
- edit generated `.spacemacs` file with the following diff 
```diff
diff --git a/.spacemacs b/.spacemacs
index 170910c..030dd92 100644
--- a/.spacemacs
+++ b/.spacemacs
@@ -34,7 +34,10 @@ values."
      ;;        shell-default-position 'bottom)
      ;; spell-checking
      ;; syntax-checking
-     ;; version-control
+     version-control
+     (ranger :variables
+             ranger-show-literal nil
+             ranger-show-preview t)
      )
    ;; List of additional packages that will be installed without being
    ;; wrapped in a layer. If you need some configuration for these
@@ -206,7 +209,7 @@ values."
    ;; If non nil line numbers are turned on in all `prog-mode' and `text-mode'
    ;; derivatives. If set to `relative', also turns on relative line numbers.
    ;; (default nil)
-   dotspacemacs-line-numbers nil
+   dotspacemacs-line-numbers t
    ;; If non-nil smartparens-strict-mode will be enabled in programming modes.
    ;; (default nil)
    dotspacemacs-smartparens-strict-mode nil
```
- quit/relaunch spacemacs
- invoke ranger `SPC a r` and preview files (I previewed the core spacemacs elisp file, but any should work)

**Comment by rjhilgefort** [comment]
I'm seeing something similar, but my buffers are affected as well.
