### ISSUE TITLE
Slow evil-smart-goto-definition when using ycmd layer

### ISSUE THREAD

**Issue by dubnde** [syl20bnr/spacemacs#6898]
#### Description :octocat:
`dumb-jump` seems to slow down `evil-smart-goto-definition` when using `ycmd` layer for C/C++ project

It appears it selects the `dumb-jump-go` instead of `ycmd-goto`

#### Reproduction guide :beetle:
- Start Emacs
- Configure `ycmd`
- Build the C/C++ project compilation database file - `compile_commands.json`. The
  `compile_commands.json` file is approximately 10MB in my case
- Load compilation database
- Open C/C++ file
- Run key sequence `g d - evil-smart-goto-definition`

*Observed behaviour:* :eyes: :broken_heart:
It takes a number of seconds to jump to definition or declaration. Even for definitions in the same
buffer/file takes approximately 5 seconds. 

*Expected behaviour:* :heart: :smile:
Instantly jump to definition/declaration

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. b8ca74e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t :disabled-for shell erc)
 (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
 (colors :variables colors-colorize-identifiers 'variables)
 cscope emacs-lisp evil-cleverparens evil-commentary
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 fasd git html
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 imenu-list java javascript markdown
 (org :variables org-projectile-file "~/org/todo.org")
 osx pdf-tools python semantic
 (shell :variables shell-enable-smart-eshell t shell-default-full-span nil)
 shell-scripts spell-checking syntax-checking
 (typography :variables typography-enable-typographic-editing t)
 version-control vimscript windows-scripts yaml my-c-c++ my-ycmd my-org my-uml)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
What's the value of `spacemacs-jump-handlers` in the relevant buffer?

**Comment by TheBB** [comment]
Oh wait, ycmd-goto is asynchronous, isn't it?

**Comment by TheBB** [comment]
Yeah it's asynchronous, so it immediately returns, then Spacemacs assumes ycmd didn't find anything, so it continues on to dumb-jump.

…suggestions?

**Comment by dubnde** [comment]
`spacemacs-default-jump-handlers` is `(dumb-jump-go)`

`spacemacs-jump-handlers` is `(ycmd-goto dumb-jump-go)`

`spacemacs-jump-handlers-c++-mode `is `(ycmd-goto)`

`spacemacs-jump-handlers-c-mode `is `(ycmd-goto)`

**Comment by syl20bnr** [comment]
If it is async then how does it move the point in the other process ? Is there an option to make it sync ?
I don't really understand the benefit of the async process in the case of jumping somewhere, what the user could do between the request to jump and the actual jump ?

**Comment by syl20bnr** [comment]
Scratch my question :-) But I still wonder why this should be done async.

**Comment by dubnde** [comment]
sorry closed by mistaked

**Comment by TheBB** [comment]
I don't really know, I'm just assuming this is what's happening, since the ycmd code uses callbacks and an external server.

My best suggestion so far is to just break the loop after the first asynchronous jumper, come what may.

**Comment by TheBB** [comment]
Does https://github.com/syl20bnr/spacemacs/pull/6904 work better?

**Comment by dubnde** [comment]
@TheBB Yes #6904 does fix this issue.

**Comment by dubnde** [comment]
By the way how does one pull an unmerged PR into local `develop `branch? I had to copy-paste code which obviously is the dumb way and wont scale well if there are a lot of changes.

**Comment by TheBB** [comment]
You have to add my repository as a remote and then fetch the commit(s). Then you can do with the branch as you please (merge it into your develop, check it out as is, whatever.)

**Comment by dubnde** [comment]
got it. thanks.

**Comment by TheBB** [comment]
Pull requests are tied to branches, so you can manipulate them as you would any other branch. This particular branch lives on my fork (git@github.com:TheBB/spacemacs) and is called async-jump, so to use it you have to add my fork as a remote and grab the branch from there.

**Comment by TheBB** [comment]
I merged the fix, closing.

**Comment by dubnde** [comment]
thanks. `magit `makes it easy to add the remote repo and merge the PR. Was good practice.
