### ISSUE TITLE
I want to replace not additional when I select something and then typing.

### ISSUE THREAD

**Issue by wudixiaotie** [syl20bnr/spacemacs#6902]
How could I do that?
My spacemacs branch is develop.
My computer is mac book pro 15.

**Comment by fabianhjr** [comment]
VIM-style: ESC *select* d i *write*
Emacs: https://www.emacswiki.org/emacs/DeleteSelectionMode (IE, enable delete-selection-mode)

**Comment by wudixiaotie** [comment]
@fabianhjr Thank you very much, Your reply is very helpful to me. 👍 💯
