### ISSUE TITLE
no undo-boundary after 20 chars

### ISSUE THREAD

**Issue by datafux** [syl20bnr/spacemacs#6906]
Stock emacs sets an undo-boundary every 20chars and with every newline.
In spacmacs 0.105.22 this doesn't work

**Comment by TheBB** [comment]
Can you be more precise? Repro steps?

**Comment by datafux** [comment]
If you start typing in an empty buffer and never leave insert mode the last undo-boundary (point) will be the empty buffer. you can type in a whole article - the last undo point will be the empty buffer.
The emacs reference states that after 20 chars an undo point is inserted. 
https://www.gnu.org/software/emacs/manual/html_node/elisp/Undo.html
If you do the same in stock emacs you will get a lot more undo points.

**Comment by TheBB** [comment]
If you set `evil-want-fine-undo` to `t` it looks like you get the same?

**Comment by datafux** [comment]
Thanks! This solved the issue.
