### ISSUE TITLE
evil-open-below not work when I define key for evil insert mode

### ISSUE THREAD

**Issue by qx** [syl20bnr/spacemacs#6912]
#### Description :octocat:
(define-key evil-insert-state-map (kbd "C-o") 'evil-open-below)
evil-open-below not work, always treat as evil-open-above when I press C-o

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 0191a81)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((spacemacs-layouts :variables spacemacs-layouts-directory "~/.spacemacs.d/layouts/")
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 osx dash smex yaml chinese oyqx html
 (ruby :variables ruby-version-manager 'rbevn ruby-test-runner 'rspec)
 ruby-on-rails helm
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence-delay 0.5)
 better-defaults emacs-lisp git markdown org syntax-checking)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
That line works fine here. How are you using it?

**Comment by qx** [comment]
I found problem 
 ` (define-key evil-insert-state-map (kbd "C-O") 'evil-open-above)`  this cofig will block C-o
  change below is work fine, didn't know why.
` (define-key evil-insert-state-map (kbd "C-S-o") 'evil-open-above)`

**Comment by TheBB** [comment]
Okay, good!
