### ISSUE TITLE
*FORUM* Should space-doc enable centered-buffer-mode by default?

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#6916]
### I wonder what other spacemacsers think

:+1:  YES 
- - - - - - -
:-1:  NO

#### WTF is `centered-buffer-mode` ?
*Note that it's configured to enable only on wide screens (frames)*

![http://i.imgur.com/7C9TLng.png](http://i.imgur.com/7C9TLng.png)
![http://i.imgur.com/xCeS5AN.png](http://i.imgur.com/xCeS5AN.png)
![http://i.imgur.com/p0c8T29.png](http://i.imgur.com/p0c8T29.png)

**Comment by deb0ch** [comment]
I really like the idea behind your mode, and I think that it could be applied to way more things than just the docs :smile: 

Though I think it is wiser to not set it by default but under an easily accessible keybinding and let people discover and try it for some time before considering setting it as default.

**Comment by JAremko** [comment]
@deb0ch  it's already bound to `w` `c`

**Comment by deb0ch** [comment]
(I didn't mean the contrary :stuck_out_tongue_winking_eye: )

**Comment by dubnde** [comment]
Is there a currently a setting to disable it by default?

**Comment by TheBB** [comment]
Yes, you can configure `spacemacs-space-doc-modificators`

**Comment by dubnde** [comment]
@TheBB ta

**Comment by d12frosted** [comment]
While I do like the idea, I don't think I'll ever use it. Also what I really don't like - black background. It looks especially bad with light themes (which I always use). 

But I really believe that some plain text writes might like it :D Distraction free, centered text editing 💯

**Comment by syl20bnr** [comment]
@JAremko what do you mean by purging it ? We can just disable it by default.

**Comment by deb0ch** [comment]
Yeah, don't remove it please :smile:

**Comment by TheBB** [comment]
Yes, my understanding is that this vote is about not enabling the mode by default when viewing docs. Keeping `SPC w c` is not up for discussion (at least, not here).

**Comment by JAremko** [comment]
@syl20bnr   I will disable it by the default. But also it might make sense to remove the integration between the `space-doc` and `centered-buffer` modes(given no one seems to like it enabled) it might allow to remove a ton of hacks and simplify `space-doc`  FAQ.

**Comment by Andre0991** [comment]
I agree with @d12frosted - the black background feels a bit weird depending on the theme. 

I wonder if there's  some way to match the theme colour (not using the exactly same background colour, but a similar one, I'd say).

**Comment by JAremko** [comment]
@Andre0991  you can set color by modifying variable `spacemacs-centered-buffer-mode-fringe-color`  it's in `spacemacs-centered-buffer-mode` emacs customization group - it should have nice color picker :smile:

**Comment by JAremko** [comment]
Alright I promised 24 hours voting so it's officially done now. 
 I'll make a PR that purges `centered-buffer-mode` out of the default `space-doc-mod` modificators list(I think I'll keep it as an option for now). Also I'll update FAQ and clean up the code a bit. 
Then it will be up to Spacemacs collaborators to merge it or not (I'M pretty sure it will be merged)

**Comment by Spadavecchia** [comment]
Sometimes, democracy is not so good.

**Comment by JAremko** [comment]
@Spadavecchia  At least the outcome can always be fixed. For example, I never told when I gonna open the PR.  :smile:  

Hm... It reminded me something

**Comment by TheBB** [comment]
We're releasing 0.200 soon. It would be good to have this settled before then.

**Comment by JAremko** [comment]
@TheBB 
But can you make something sooner than soon ? Im not sure :confused: 
  I'll try to make it very soon then :+1:
