### ISSUE TITLE
Alias org-set-tags to counsel-org-tag when using ivy and org

### ISSUE THREAD

**Issue by darkfeline** [syl20bnr/spacemacs#6918]
The default ivy completion and `org-set-tags` is fairly useless since it doesn't complete after the first tag.  `ivy`/`counsel` has a function for this that should replace `org-set-tags` entirely if `ivy` layer is used.

For reference: https://github.com/abo-abo/swiper/issues/177

**Comment by github-god** [comment]
I double that.

**Comment by syl20bnr** [comment]
@darkfeline thank you for the PR, merged in develop branch.

**Comment by codygman** [comment]
I think this can be closed FYI.

**Comment by duianto** [comment]
Any issue that's marked as `Fixed in develop` will be closed when the next version is released.
But we can close this now. Thanks for the suggestion.
