### ISSUE TITLE
Form feed character in `insert-page-break` causes issue with `Inconsolata`

### ISSUE THREAD

**Issue by menelaos** [syl20bnr/spacemacs#6924]
#### Description

With the `Inconsolata` font , the form feed character (`U+000C`) in `spacemacs-buffer/insert-page-break` causes the home buffer content to shift when the cursor is over the horizontal line. Sometimes this behaviour stops after using `Spacemacs` for a while but I haven't been able to reproduce this reliably.
Is the form feed character really necessary? A similar visual effect could be achieved with e.g. `U+2500`.
#### Reproduction guide
- Install `Inconsolata` font and set it as default font in `.spacemacs`:
  
  ```
    dotspacemacs-default-font '("Inconsolata"
                                :size 16
                                :weight normal
                                :width normal
                                :powerline-scale 1.1)
  ```
- Start Emacs
- Press `j` until the cursor is over the horizontal line

_Observed behaviour:_
Cursor jumps to the end of the line and consequently, the home buffer content shifts to the left.

_Expected behaviour:_
There should be no sudden jump when the cursor is over the horizontal line.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion colors deft emacs-lisp eyebrowse git haskell markdown org purescript react
                 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'full)
                 themes-megapack)
```

**Comment by andreybratukhin** [comment]
I think, the horizontal line should not exceed the current buffer width. In this case the jump to the end of line will not affect the current buffer so much.

**Comment by andreybratukhin** [comment]
The following code creates a page break line from '─' (box drawings light horizontal) symbol by filling it up to window width.

    (defun spacemacs-buffer/insert-page-break ()
      "Insert a page break line in spacemacs buffer."
      (spacemacs-buffer/append (concat "\n" (make-string (window-body-width) ?\u2500) "\n")))
