### ISSUE TITLE
Spacemacs home buffer replaces buffers when reattaching to a session.

### ISSUE THREAD

**Issue by GregorySchwartz** [syl20bnr/spacemacs#6925]
#### Description

Attaching to emacs session replaces focused buffer with the spacemacs home
screen. When using the emacs daemon as a session (like tmux), it's inefficient
to have the previous layout interrupted due to the home screen replacing a
buffer. It's easily fixed by opening the previous buffer, but sometimes I have
to search for which file or terminal I was using and it's an unnecessary
roadblock. I suggest to only have the spacemacs home screen when the emacsclient
does not attach to a layout with opened buffers.
#### Reproduction guide
- Start Emacs
- Open files
- C-x 5 0
- Start Emacs

_Observed behaviour:_
Most recent buffer is replaced with the spacemacs home buffer.

_Expected behaviour:_
The entire layout is preserved from the previous attachment to the session.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. b2d1088)
- Graphic display: t or nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-sort-by-usage)
 better-defaults emacs-lisp git markdown
 (org :variables org-enable-reveal-js-support t)
 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "/usr/bin/fish")
 spell-checking syntax-checking version-control
 (haskell :variables haskell-completion-backend 'intero)
 erc)
```

**Comment by lverns** [comment]
As I understand it, this is not really an issue with Spacemacs, but with Emacs itself. 
> *Expected behaviour:*
The entire layout is preserved from the previous attachment to the session.

When running in daemon mode, one can launch many different instances of `emacsclient` at once, and their "layouts" are manipulated independently. Because of this, I don't think that "previous attachment" can be defined well.

Experimenting with Emacs 24.5.2 and `emacs --no-init --daemon` shows that `emacsclient -c` always opens to the scratch buffer.

**Comment by GregorySchwartz** [comment]
Interesting. When I use `emacsclient -c` it always does the behavior I descript using the "previous attachment". I was using a spacemacs configuration, though. There is clearly some saving going on, otherwise that "saved" layout would not be possible.

**Comment by leezu** [comment]
I experience the same behavior as @GregorySchwartz: `emacsclient -c` shows the "previous attachement" if it is started multiple times (instead of the scratch buffer). I believe this is a bug induced by `persp-mode` and have reported it as #7644
