### ISSUE TITLE
Make helm-find-files faces more consistent

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#693]
Helm added a new face a while ago: `helm-ff-doted-directory`. This is the face of the top two lines in `helm-find-files`. We should make it inherit from `helm-ff-directory` for consistency across themes, otherwise the default theme makes it hard to read in GUI and unreadable in terminal.

We can also make `helm-buffer-directory` consistent by making it inherit `helm-ff-directory`.

**Comment by syl20bnr** [comment]
I'm ok to do it but I feel this should be something to add as a default in helm directly.

**Comment by tuhdo** [comment]
Adding it to `helm-find-files` hook doesn't solve the problem completely. You can try with `magit-status` outside of any Git project; when a file browser pops up for navigating (using Helm interface), the face remains still until you actually run `helm-find-files`. 

We should set it once instead of repeatedly set the face when open Helm.
