### ISSUE TITLE
AucTex mode creates 2 separate buffers for the same master Tex file

### ISSUE THREAD

**Issue by tddsg** [syl20bnr/spacemacs#6932]
#### Description

AucTex mode creates 2 separate buffers for the same master file
#### Reproduction guide
- Start Emacs
- Open the master file of a Latex project. Suppose the master Tex file is `main.tex`, and at the end of the file, it contains these comments to indicate it as the master file.

```
%%% Local Variables:
%%% mode: latex
%%% TeX-master: "main"
%%% End:

```

_Observed behaviour:_
Two separate buffers are created for the same file `main.tex`.
As indicated in the attached picture, there are two buffers `main.tex<fm16>` and `main.tex`. Note that `fm16` is the folder containing the file `main.tex`

![spacemacs-latex](https://cloud.githubusercontent.com/assets/20593743/18026654/dacb2c4e-6c80-11e6-8463-4355d1f559c0.png)

_Expected behaviour:_
Only 1 buffer should be created for the master Tex file
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control semantic latex ocaml haskell tddsg)
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment]
I can't reproduce this. I made a file with the contents described, opened it, and I only have one buffer.

**Comment by TheBB** [comment]
Okay, I can reproduce this from `emacs -q` with only auctex enabled. Therefore it's an auctex bug/feature. You should report to them.

**Comment by tddsg** [comment]
Thanks for the update!

**Comment by deb0ch** [comment]
Hey, checking on this for the seasonnal cleanup.

What is the status on this issue ? Has it been reported or fixed upstream ?

**Comment by tddsg** [comment]
I am trying to report to the developers of AucTex. 
I will keep it update once I get the news
