### ISSUE TITLE
how to change the line spacing in the which-key buffers?

### ISSUE THREAD

**Issue by yilihong** [syl20bnr/spacemacs#6935]
currently the which-key buffers line spacing is very large, want to shrink it a bit. wonder how that could be done.

<img width="1093" alt="screenshot 2016-08-26 16 11 54" src="https://cloud.githubusercontent.com/assets/11595258/18027107/0b61f7ce-6c0f-11e6-9d6e-6bed523f52cc.png">

**Comment by TheBB** [comment]
This should be reported to which-key.

**Comment by yilihong** [comment]
I have reported to which key and close here.

**Comment by TheBB** [comment]
Thanks. It's common courtesy to leave a link, though.

https://github.com/justbur/emacs-which-key/issues/138
