### ISSUE TITLE
Disable evil-escape by default

### ISSUE THREAD

**Issue by sliedes** [syl20bnr/spacemacs#6936]
#### Description

When spacemacs is open in a text terminal (emacs -nw at least in either konsole or gnome-terminal) and in insert mode, using the terminal's paste feature to paste the text `mkfd` from X clipboard results in only `mk` being inserted. This does not happen with vanilla emacs (emacs -nw -q) nor in spacemacs in windowed mode (emacs without -nw).
#### Reproduction guide
- Start `emacs -nw` in konsole or gnome-terminal
- Press `q` to close the splash screen
- Press `i` to enter the insert mode
- In a different terminal/browser/whatever, select the text `mkfd` and copy it to clipboard
- Test paste clipboard contents to another terminal to ensure that the contents are indeed `mkfd`
- Use the terminal's paste feature to paste the string to spacemacs

_Observed behaviour:_
Text `mk` is inserted.

_Expected behaviour:_
Text `mkfd` is inserted.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp haskell syntax-checking)
```

**Comment by NJBS** [comment]
This is a side-effect of [evil-escape](http://spacemacs.org/doc/DOCUMENTATION.html#orgheadline78) on terminals.

Duplicate of https://github.com/syl20bnr/spacemacs/issues/5268

**Comment by TheBB** [comment]
Yeah, you should probably paste from the clipboard instead of streaming characters in the terminal. That will usually not end well.

**Comment by sliedes** [comment]
Are you sure it is a good idea to have this enabled by default? It's certainly surprising to have characters eaten from the middle of a base64 encoded string in a URL (which is what happened to me), and I've never heard of this feature before.

Note that this also has quite obvious security implications. If pasted text can run arbitrary commands, you must never paste text you do not trust or have audited...

**Comment by TheBB** [comment]
> Note that this also has quite obvious security implications. If pasted text can run arbitrary commands, you must never paste text you do not trust or have audited...

Pasted text can't run arbitrary commands. Streamed characters into the terminal *can*, and they can do that regardless of what you're running. Try opening vim, going to insert state and then pasting `^[:!echo oh looks like i can run shell commands^M` or equivalent.

If you have xclip installed, here's a hack that allows Emacs (at least, evil) to access the X clipboard(s). I don't know if it works with the standard Emacs copy/paste.

```elisp
(defun bb/x-get-selection (orig-fun &optional type data-type)
  (condition-case nil
      (funcall orig-fun type data-type)
    (error
     (when (and (executable-find "xclip")
                (memq type '(PRIMARY CLIPBOARD)))
       (message "yo")
       (let ((type (if (eq 'PRIMARY type) "primary" "clipboard")))
         (shell-command-to-string
          (format "xclip -selection %s -o" type)))))))
(advice-add 'x-get-selection :around 'bb/x-get-selection)
```

**Comment by sliedes** [comment]
But a terminal can help you there; xterm and gnome-terminal won't let you paste many control characters (like ESC). (To my dismay, I realized konsole does let them through.) Also getting such strings to the clipboard via a web page is probably much more difficult than getting a string containing "fd" there.

**Comment by TheBB** [comment]
Yep, all true. If there's widespread support for disabling evil-escape by default, we can discuss it, but I don't expect there to be.

**Comment by sliedes** [comment]
One option might be to disable it only when running in terminal mode?

**Comment by amosbird** [comment]
Doesn't `bracketed paste mode` take care of such issue?

**Comment by TheBB** [comment]
Yeah, it should.

**Comment by amosbird** [comment]
Well, I did nothing to set things up and haven't encountered a problem since using `emacs-25rc` and `urxvt`.

**Comment by TheBB** [comment]
Just asking because I don't see any functions by that name.

**Comment by bmag** [comment]
The plot thickens: Tried the repro steps on Emacs 25.1-rc2, develop branch, hybrid editing style, gnome-terminal. Encountered the expected behavior, no bug. Then I tried with vim editing style instead of hybrid, and I encountered the bug.

As for bracketed-paste, the package isn't used in Emacs 25.1. From `spacemacs-editing/packages.el`:
```elisp
(setq spacemacs-editing-packages
      '( ;; ... snipped ...
        (bracketed-paste :toggle (version<= emacs-version "25.0.92"))
        ;; ... snipped ...
        ))
```

**Comment by bmag** [comment]
Something on our side is causing the trouble. With this repro I see no bug:
1. `emacs -Q -nw -L /path/to/elpa/evil-escape-<timestamp>/ -L /path/to/elpa/evil-<timestamp>/`
2. evaluate in scratch buffer:
```elisp
(require 'evil)
(require 'evil-escape)
(evil-mode)
(evil-escape-mode)
```
3. enter insert state with `i`
4. use terminal to paste `mkfd` from clipboard

Observed behvaior: `mkfd` is insterted into the buffer, state remains insert-state.

(the numbering is supposed to be 1,2,3,4 of course, not 1,2,1,2, but GitHub is acting dumb and stubborn)

**Comment by parthsdoshi** [comment]
This doesn't seem to happen with emacs 25.2.1 with vim editing style. Typing fd quickly will take me back to normal mode but I can paste mkfd just fine. I'm on macOS running spacemacs through iTerm 2.
