### ISSUE TITLE
haskell layer - ghc8 error messages not formatted properly

### ISSUE THREAD

**Issue by alexanderkjeldaas** [syl20bnr/spacemacs#6938]
If you are posting about a *bug* please close this issue and open a new one
    using [SPC h I] or [M-m h I] (I = capital i) from within Spacemacs.
    You can delete this message to start typing.

The above instructions do nada in my spacemacs, so I ignored those instructions.

The latest ghc release give errors like this: 

<img width="177" alt="example" src="https://cloud.githubusercontent.com/assets/339369/18028884/0ea3cece-6c89-11e6-8704-996be220a3a6.png">

I'm using ghc-mod and intero.  What I would like to see is the actual error from ghc.

**Comment by d12frosted** [comment]
> I'm using ghc-mod and intero

Wut? How is that possible in plain Spacemacs? AFAIK, they are exclusive.

**Comment by bravomikekilo** [comment]
me too 
I use 
1. the universal Linux Haskell platform
2. ghc-mod 5.6.0.0 build by the ghc8
3. the stack set to a ghc8 nightly build

**Comment by alexanderkjeldaas** [comment]
I mean I have `ghc-mod` and `intero` installed.  I couldn't find any way to configure either, so Spacemacs will do whatever it wants.

**Comment by alexanderkjeldaas** [comment]
I'm using 0.105.22

**Comment by NerdGGuy** [comment]
I had this issue after switching to GHC 8. Was fixed by upgrading spacemacs and related packages. Unless @alexanderkjeldaas still has issues we can close?

**Comment by d12frosted** [comment]
Please try to reproduce this issue using latest Spacemacs (master or dev) and latest version of all related packages (better to just update all of them 😸 ). Closing this as being potentially fixed on master / upstream. Let me know if it's not.
