### ISSUE TITLE
Rails support isn't loading

### ISSUE THREAD

**Issue by kofno** [syl20bnr/spacemacs#694]
I have added `(setq-default ruby-on-rails-support t)` to dotspacemacs/init, but it still doesn't load.

I have also looked in the elpa directory, and it doesn't look like spacemacs have even installed the projectile-rails package.

**Comment by syl20bnr** [comment]
It is `ruby-enable-on-rails-support`. The documentation needs to be updated.

https://github.com/syl20bnr/spacemacs/blob/master/contrib/lang/ruby/packages.el#L15

I will also add in the convention that all layer variables that enable something are named `<layer>-enable-xxxxxx`.

**Comment by kofno** [comment]
Using the correct var (ruby-enable-ruby-on-rails-support) fixed it. Thanks!

**Comment by hrvladev** [comment]
@syl20bnr I think this issue is resolved by #704. :thought_balloon:

**Comment by kofno** [comment]
Looks like it. Thanks!
