### ISSUE TITLE
spacemacs/set-leader-keys-for-major-mode not working with notmuch

### ISSUE THREAD

**Issue by Stebalien** [syl20bnr/spacemacs#6943]
So, I'm working on a custom notmuch layer and am having trouble binding keys to "SPC m ...". The following works:

```elisp
(spacemacs/set-leader-keys-for-major-mode 'notmuch-message-mode
        "af" 'mml-attach-file
        "ab" 'mml-attach-buffer
        "ae" 'mml-attach-external)
```

However, the following doesn't:

```elisp
(spacemacs/set-leader-keys-for-major-mode 'notmuch-search-mode
          "c" 'notmuch-jump-search
          "l" 'notmuch-search-filter
          "L" 'notmuch-search)
```

By "doesn't work" I mean that opening a notmuch search buffer `(notmuch-search "tag:inbox")` and hitting `SPC m` doesn't bring anything up. However, the `spacemacs-notmuch-search-mode-map{,-prefix,-active,-root-map}` variables are all defined correctly.

I believe this is due to how notmuch declares it's layers (other than `notmuch-message-mode`). Specifically, notmuch uses `defun` instead of `define-derived-mode`. For example, `notmuch-search-mode` is defined as follows:

```elisp
(defun notmuch-search-mode ()
  "...docs..."
  (interactive)
  (kill-all-local-variables)
  (make-local-variable 'notmuch-search-query-string)
  (make-local-variable 'notmuch-search-oldest-first)
  (make-local-variable 'notmuch-search-target-thread)
  (make-local-variable 'notmuch-search-target-line)
  (setq notmuch-buffer-refresh-function #'notmuch-search-refresh-view)
  (set (make-local-variable 'scroll-preserve-screen-position) t)
  (add-to-invisibility-spec (cons 'ellipsis t))
  (use-local-map notmuch-search-mode-map)
  (setq truncate-lines t)
  (setq major-mode 'notmuch-search-mode
	mode-name "notmuch-search")
  (setq buffer-read-only t))
```

So, is there any way to get this to work or is this an upstream issue?

**Comment by TheBB** [comment]
It's an upstream issue, either in `bind-map`, which is the package implementing Spacemacs leader maps (in case they want to support this kind of “major mode“) or in `notmuch`, which is using improper “major modes”.

**Comment by TheBB** [comment]
From a brief look at the bind-map source code it looks like it would be enough if the notmuch functions made sure to run `change-major-mode-after-body-hook` as appropriate.

**Comment by Stebalien** [comment]
Thanks. I've submitted a patch upstream to just use `define-derived-mode`: https://notmuchmail.org/pipermail/notmuch/2016/022912.html
