### ISSUE TITLE
Enable line numbers for conf-mode too

### ISSUE THREAD

**Issue by valentjedi** [syl20bnr/spacemacs#6947]
Hi! For now `dotspacemacs-line-numbers` enables line numbers only for `prog-mode` and for `text-mode`. Why not activate it for `conf-mode` too by default? I think it's very common to have line numbers shown when editing configuration files. For now I use 
```elisp
(when dotspacemacs-line-numbers
  (add-hook 'conf-mode-hook 'linum-mode)
```
for this. I can make PR to `config.el` if you don't mind :)

**Comment by TheBB** [comment]
Hold on a minute. The reason for this is not that it was forgotten, rather that conf-mode is implemented as a function and not a genuine major mode, a characteristic it shares with a number of others, e.g. matlab-mode, which is fixed [like this](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/extra-langs/packages.el#L31). You can make the same tweak for conf-mode (deriving from text-mode seems reasonable).

**Comment by valentjedi** [comment]
Thanks for clearing things. 
The main reason I created this issue is to know if it was made intentionally and why. Not gonna make PRs just because something is unclear to me, I think there are too many of them already.

**Comment by TheBB** [comment]
I'll do it then.

**Comment by valentjedi** [comment]
@TheBB Now I'm a little bit wrap my brains around code repo and I think I can do it. But where should I put such fix? For now I think that `Edit` section of `spacemacs/layers/+distribution/spacemacs-base/config.el` might be a good place. What do you think?

**Comment by TheBB** [comment]
I would add another package in `spacemacs-base/packages.el` called `conf` or something. Make sure it's built-in like most of the others. Then make an init-function for that package, and you can put the add-hook in there.

**Comment by valentjedi** [comment]
Just did a PR to develop branch. Sorry in advance if anything bad with it, I'm always ready to improve :)
