### ISSUE TITLE
The search highlight is almost invisible in the develop branch

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#6948]
#### Description :octocat:

The search highlights background color: `#293239`, in the develop branch is to similar to the spacemacs default themes background color: `#292E34`, that makes the highlights almost invisible.

#### Reproduction guide :beetle:

1. Start Emacs
2. Open .spacemacs `SPC f e d`
3. Search for the word "the" with either: C-s the RET , /the RET or ?the RET

*Observed behaviour:* :eyes: :broken_heart:

All visible instances of the word "the" gets highlighted.

Spacemacs branch: develop (rev. 89137bb)
The highlight is pretty much invisible, the text background color is: `#293239`

The highlight is a lot more visible in the master branch:
Spacemacs branch: master (rev. 9f9faa4)
There the text background color is: `#444155`

In both the master and develop branch, the emacs background color is the same: `#292E34`

*Expected behaviour:* :heart: :smile:

The highlight color should be more visible in the develop branch. Probably the same color as in the master branch.

#### System Info :computer:
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 89137bb)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git)
```

**Comment by TheBB** [comment]
Please report this to the maintainer of the theme you are using. It is responsible for colours.
