### ISSUE TITLE
How to use counsel-git-grep from ivy ?

### ISSUE THREAD

**Issue by shanavas786** [syl20bnr/spacemacs#6956]
From `layers/+completion/helm/packages.el` and `layers/+completion/avy/packages.el`, key `SPC s g p` is bound to `helm-projectile-grep` and `counsel-git-grep`.

Now `SPC s g p` triggers `helm-projectile-grep`. How can I switch to `counsel-git-grep` ?

I am on develop branch -- commit -- `781532d4d2a5859f9813788303c90888f5313423`

**Comment by TheBB** [comment]
Have you enabled the ivy layer?

**Comment by shanavas786** [comment]
Got it. Thanks.
However, documentations are missing for ivy and helm layers.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/6961

**Comment by shanavas786** [comment]
:+1:

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
