### ISSUE TITLE
Upgrading spacemacs without upgrading packages results in error message about spacemacs//window-numbering-assign

### ISSUE THREAD

**Issue by tchajed** [syl20bnr/spacemacs#6968]
It looks like commit 4b2f123a052 removed a workaround for nschum/window-numbering.el#10, which has been fixed upstream. Thus upgrading Spacemacs past 4b2f123a052 on the develop branch without also upgrading packages (or at least window-numbering.el) results in a fairly broken Emacs, where many operations (including `:` and quitting Emacs) results in failure and the error message `Symbol's value as variable is void: spacemacs//window-numbering-assign` in the echo area.

Is there a way for Spacemacs to warn that upgrading packages is needed, or better yet, specifically offer to upgrade window-numbering.el?

**Comment by TheBB** [comment]
No, there's no such mechanism. Spacemacs quite explicitly tracks the latest packages, users should not upgrade one without also upgrading the other.

**Comment by xged** [comment]
I updated packages, *pulled* latest `develop` branch and been having the same issue on `develop` (`master` is fine). *Chekingout* 4b2f123 did not help.

**Comment by bmag** [comment]
@xged the package update must have gone wrong. In updated develop branch and latest window-numbering package, there is no code that treats `spacemacs//window-numbering-assign` as a variable, so the error above just isn't possible.

To make sure window-numbering is updated, find it's directory inside of `~/.emacs,d/elpa`, The directory should be called `window-numbering-<timestamp>`. The timestamp should be `20160809.1110`.

**Comment by xged** [comment]
I forgot to mention that updates did went wrong (I believe it was `the tls connection was non-properly terminated`)
@bmag The timestamp of `window-numbering` is `20150228.1247` therefore not updated.

**Comment by bmag** [comment]
The work-around was re-added, this issue can be closed.
