### ISSUE TITLE
[LaTeX Layer] Can we streamline compilation of latex file that include bibtex?

### ISSUE THREAD

**Issue by yilihong** [syl20bnr/spacemacs#6970]
any idea how to streamline the compilation of latex files that include bibtex in one set of C-c C-c? I know we need to run it four times, but I don't know how to enable the sequence in a lisp code that binds it to one process. Below is something that org-mode does when exporting the pdf files. 

Any suggestion will be greatly appreciated.

`(setq org-latex-pdf-process '("pdflatex -interaction nonstopmode -output-directory %o %f" "bibtex %b" "pdflatex -interaction nonstopmode -output-directory %o %f" "pdflatex -interaction nonstopmode -output-directory %o %f"))`

**Comment by TheBB** [comment]
Yeah, use latexmk instead of pdflatex.

**Comment by yilihong** [comment]
@TheBB 

I do use this setting in dotspacemacs (below), am I missing something?

(latex :variables
            latex-build-command "LatexMk"
            latex-enable-auto-fill nil
            latex-enable-folding nil)

**Comment by TheBB** [comment]
That's what is used by `SPC m b` in a latex file, yes. `C-c C-c` runs a slightly different command (when I try it, it asks me for the command, and LatexMk is an option).

**Comment by yilihong** [comment]
@TheBB  thanks, so when I run C-c C-c and choose latexmk as the option for compiling, I get this in status bar, after running latexmk, or latex twice more, this message goes away. Any ideas?

<img width="674" alt="screenshot 2016-09-03 11 40 24" src="https://cloud.githubusercontent.com/assets/11595258/18226979/5a4f4dfc-71cb-11e6-862a-cb2efb3d9391.png">

**Comment by yilihong** [comment]
@TheBB 
If I hand code  "latexmk -synctex=1 -shell-escape -xelatex %s", it actually works, it does get the citations squared out.

Also, the latexmk works with sublime text, so it is not the system latex issue. Really have no idea why latexmk won't work with spacemacs and whether it is just me an isolated case.

**Comment by TheBB** [comment]
This is the output I get using default `SPC m b` with latexmk on a sample latex/bibtex paper ([this one](http://shelah.logic.at/eindex.html)). As you can see it runs pdflatex two times, then bibtex and finally pdflatex again.

If you try the same, what do you get?
