### ISSUE TITLE
Key bindings for moving lines up/down on Git rebase don't work

### ISSUE THREAD

**Issue by carlosgaldino** [syl20bnr/spacemacs#6971]
#### Description

Key bindings for moving lines up/down on Git rebase don't work.
#### Reproduction guide
- Start Emacs
- Visit any project using Git
- `SPC g s`
- `r i` to rebase interactively
- `C-c` in a comit to start the rebase
- `K` or `J` to try to move the commit line up or down, respectively.
  - `M-k` or `M-j` as the message in the rebase window show also do not do what is expected (move lines up/down).
  - `M-p` also does not move the line up

_Observed behaviour:_
If `K` is pressed: the command `spacemacs/evil-smart-doc-lookup` is executed.
If `J` is pressed: the command `evil-join` is executed.
If `M-k` is pressed: the command `kill-this-buffer` is executed.
If `M-j` is pressed: the command `exchange-point-and-mark` is executed.
If `M-p` is pressed: the command `ns-print-buffer` is executed.

_Expected behaviour:_
Move commit line up or down.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables
                  '(auto-completion-enable-help-tooltip t))
 ruby haskell syntax-checking git github javascript c-c   markdown org go html rust
 (shell :variables shell-default-shell 'eshell)
 spell-checking themes-megapack erlang theming)
```

Thank you.

**Comment by TheBB** [comment]
I cannot reproduce this on develop with updated packages.

**Comment by carlosgaldino** [comment]
I tried with the `develop` branch as well and the same issues occur. Could it be the [Emacs version I'm using](https://github.com/syl20bnr/spacemacs#os-x)?

Thanks.

**Comment by mbertheau** [comment]
I have a similar issue: K is `spacemacs/evil-smart-doc-lookup` and J is `evil-join`. My window manager rightfully gets all key strokes with `M-`, so `M-k` and `M-j` don't get to emacs.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t)
 clojure
 (colors :variables colors-colorize-identifiers 'all)
 emacs-lisp git gtags html ibuffer javascript markdown
 (python :variables python-test-runner 'pytest)
 sql syntax-checking version-control yaml)
```

**Comment by mbertheau** [comment]
A tedious but functioning workaround is to call the commands directly using `SPC : git-rebase-move-line-up` and `-down` respectively.

**Comment by joyarzun** [comment]
The same happens to me

- Spacemcas: 0.200.5
- Emacs: 25.1.1
- OS: darwin
- Editing style: vim
- Completion: helm
`   markdown
     ruby
     yaml
     helm
     elm
     emacs-lisp
     git
     javascript
     syntax-checking
     react
`

**Comment by TheBB** [comment]
I'm still unable to reproduce the original issue.

@mbertheau You have the correct bindings for `J` and `K`. `M-k` and `M-j` are supposed to move lines.

> My window manager rightfully gets all key strokes with M-, so M-k and M-j don't get to emacs.

Rightfully? Common consensus is to keep window manager keys on super. I don't accept that it's a Spacemacs bug to have bindings on the meta key.

It's also easy to modify:

```elisp
(with-eval-after-load 'git-rebase
  (evil-magit-define-key evil-magit-state 'git-rebase-mode-map "K" 'git-rebase-move-line-up)
  (evil-magit-define-key evil-magit-state 'git-rebase-mode-map "J" 'git-rebase-move-line-down))
```

**Comment by mbertheau** [comment]
@TheBB Alright about Meta/Super. Thanks for the snippet. It feels great! :)

Since evil-smart-doc-lookup and evil-join are so much less useful in a rebase buffer than move-line-up/down, it'd make more sense to have the latter on J/K by default.

**Comment by Reefersleep** [comment]
I just want to give my thanks for your remapping tip, @TheBB!
I had lots of trouble getting the meta keystrokes to Emacs when I was trying to get work with magit interactive rebase, in trying to use `git-rebase-move-line-up` and `git-rebase-move-line-down`. I'm using Spacemacs in Evil mode, and so far, I don't have any other use case for the meta key, so this tip is a godsend! It feels much better and Vim-like to me than I'm sure the meta key combination would have felt :) 👍

**Comment by mbertheau** [comment]
On current develop this code works:
```elisp
  (with-eval-after-load 'git-rebase
    (evil-define-key evil-magit-state 'git-rebase-mode-map "K" 'git-rebase-move-line-up)
    (evil-define-key evil-magit-state 'git-rebase-mode-map "J" 'git-rebase-move-line-down))
```
