### ISSUE TITLE
Support for Protocol buffers

### ISSUE THREAD

**Issue by amol-mandhane** [syl20bnr/spacemacs#6973]
It would be great if Spacemacs has a layer for editing [protocol buffer](https://developers.google.com/protocol-buffers/) files. There are Emacs packages available for this. The supporting config can also go in extra-langs layer instead of a layer of its own.

**Comment by amol-mandhane** [comment]
I have a private layer for this. I'd be happy to send a pull request.

**Comment by TheBB** [comment]
Are you proposing to solve your own issue? Then, yes, we humbly accept. :-P

**Comment by syl20bnr** [comment]
The layer is now in develop branch.

**Comment by Iulian7** [comment]
Does anyone know when this will go out of develop? Also what do I need to do to get it from the develop branch? If I add `protobuf` to `dotspacemacs-configuration-layers` it doesn't seem to find it (it is also not in the list if I search for it: SPC h l).
