### ISSUE TITLE
Issue with vi-tilde-fringe

### ISSUE THREAD

**Issue by ankhers** [syl20bnr/spacemacs#6976]
#### Description :octocat:
Spacemacs starts incorrectly after updating to latest develop branch

#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
I see the `*spacemacs*` buffer for a brief moment, then get a message in the `*Warnings*` buffer saying

`Error (use-package): vi-tilde-fringe :init: No buffer named *spacemacs*`

*Expected behaviour:* :heart: :smile:
Emacs starts properly, without the error

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. a90414c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp elm erlang elixir html
            (javascript :variables javascript-disable-tern-port-files nil)
            markdown racket ruby rust sql yaml ruby-on-rails auto-completion better-defaults git github org colors restclient dash erc dockerfile spell-checking syntax-checking nixos intero)
```

**Comment by ankhers** [comment]
This seems to have been caused by a7d4674202720d8dc8310fcae2ca9f8ffbbe1d9d

**Comment by TheBB** [comment]
Thanks, closing this as #7016 has more traffic.
