### ISSUE TITLE
How to resume eyebrowse configs?

### ISSUE THREAD

**Issue by zhengpd** [syl20bnr/spacemacs#6979]
I tried `dotspacemacs-auto-resume-layouts t` but it can't resume eyebrowse configs. Is there any option to persist and resume eyebrowse configs?

**Comment by bmag** [comment]
There isn't a built-in option to persist eyebrowse configs (AKA workspaces), but:
1. The workspaces are already stored as persp parameters (persp is short for perspective, AKA layout), and these persp parameters are in fact restored.
2. After a bit of testing, I see that the workspaces of all layouts are restored, except for the workspaces of the layout that is current after the resume process.

The only missing part is to load the workspaces of the current layout. To do so, you'll need to update the relevant frame parameters according to the current persp parameters. From reading the code, I suggest you write a function and hook it into `persp-after-load-state-functions`. The function should do something similar to `spacemacs/load-eyebrowse-for-perspective`. In fact, this might work (not tested):
```elisp
(defun load-workspaces-of-current-layout (&rest _args)
  (spacemacs/load-eyebrowse-for-perspective))

(add-hook 'persp-after-load-state-functions #'load-workspaces-of-current-layout)
```

If you find a solution that works well, please submit a PR.

**Comment by zhengpd** [comment]
@bmag Thanks for your reply. The function you provided raise errors so I slightly modified it:

```lisp
  (defun load-workspaces-of-current-layout (file phash persp-names)
    (spacemacs/load-eyebrowse-for-perspective 'frame))

  (add-hook 'persp-after-load-state-functions #'load-workspaces-of-current-layout)
```

I put this in `dotspacemacs/user-config` and it works so far.
