### ISSUE TITLE
.fs files not recognised as f# files with the fsharp layer

### ISSUE THREAD

**Issue by Custodia** [syl20bnr/spacemacs#6982]
Not sure if bug or additional configuring needed.

I addded the fsharp layer to my layers but when I open a .fs file my major mode is Fundamental.

**Comment by d12frosted** [comment]
From what I see it `auto-mode-alist` should be properly set. 

> I addded the fsharp layer to my layers

After adding new layer you have to `SPC f e R` or restart Spacemacs. Have you done that before opening `.fs` file?

**Comment by Custodia** [comment]
> After adding new layer you have to SPC f e R or restart Spacemacs. Have you done that before opening .fs file? 

Yes I did

**Comment by Custodia** [comment]
It also does seem to be loading the layer

`Loading c:/Users/JaniM/.emacs.d/layers/+lang/fsharp/packages.el (source)...done`

**Comment by TheBB** [comment]
Can you paste the value of auto-mode-alist?

**Comment by Custodia** [comment]
How do I get that value inside Emacs?

Sorry for the delay haven't been to work in multiple days where this was the issue.

**Comment by TheBB** [comment]
SPC hdv

**Comment by Custodia** [comment]
I have re installed spacemacs and this is not a issue anymore.
