### ISSUE TITLE
Spacemacs jumping does not work correctly with anaconda mode.

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#6985]
It seems that the new implementation of jumping in spacemacs has some problems with anaconda mode.

1. Sometimes `dumb-jump-go` is used when `anaconda-mode-find-definitions` executed directly works without problems. I have not yet found a minimal working example for this case but I'll try to find one.
2. Spacemacs reports `"No jump handler was able to find this symbol."` but that is not true since a correct jump was made. 

  Example:
  1. create a file called `first.py` with the following contents:
  ```python
  def test():
      pass
  ```
  2. In the same folder create `second.py`:
  ```python
  from first import test
  ```
  In `second.py` put the cursor on `test` and `SPC m g g`. It hangs a little (sometimes) then jumps to the definition of `test` and writes the message `No jump handler was able to find this symbol.`. 

My guess is that these two issues are related and have to do with the fact that anaconda mode sends the responses async.

**Comment by TheBB** [comment]
We probably have to apply the same fix for anaconda as we did with ycmd then.

**Comment by cpaulik** [comment]
Adding the `:async` keyword works.

**Comment by TheBB** [comment]
Fixed.
