### ISSUE TITLE
REGRESSION: auto centering spacemacs-buffer causes several second startup hang

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#6986]
#### Description :octocat:
Auto centering spacemacs-buffer (a7d4674) when combined with using
initial-frame-alist causes a several second hang during starutp.

#### Reproduction guide :beetle:
- Add something like this to your init.el:
```
(setq initial-frame-alist
      '(
        (top . 23)
        (left . 0)
        (width . 122)
        (height . 40)))
```
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
Emacs freezes for several seconds after the window resizes.

*Expected behaviour:* :heart: :smile:
Emacs does not freeze.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: nil (rev. 4e7d80b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(better-defaults spacemacs-layouts helm emacs-lisp markdown
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 (auto-completion :variables auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup nil)
                 erlang elixir git dash html clojure
                 (org :variables org-enable-github-support t)
                 colors osx github javascript react deft ruby
                 (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
                 spell-checking ranger version-control rcirc tmux yaml docker elm evil-little-word auto-correct frame-geometry cleverparens-lispy flow)
```

**Comment by TheBB** [comment]
I just tried this and I can't reproduce any freeze. Have you tried with the stable version?

**Comment by aaronjensen** [comment]
@TheBB it does not repro on master. I bisected to that exact commit. It repros on it and not before.

**Comment by aaronjensen** [comment]
I should also mention that the hangs are due to the two (!) `spacemacs//redisplay` -> `refresh` triggered by `spacemacs-buffer/goto-buffer`

**Comment by aaronjensen** [comment]
@TheBB see also #6997. 

I can fix this one by adding the hook later:

```
(add-hook 'window-setup-hook
          (lambda ()
            (add-hook 'window-configuration-change-hook 'spacemacs-buffer//resize-on-hook)))
```

But the hook itself is fundamentally flawed, so it should probably be reverted or fixed.

**Comment by aaronjensen** [comment]
This is related to the fact that `dotspacemacs-startup-lists` changed to include limits and `dotspacemacs-startup-recent-list-size` was removed. I did not have new limits set, so I was rendering 1000+ recent files. This was too slow. Upon fixing my config, it got much better.

See #6997 for more info.

**Comment by TheBB** [comment]
Thanks for taking the time to figure this out. I propose to add something like a `dotspacemacs-startup-lists-max-size` that will globally cap the length of the unbounded lists to some reasonable value that is set by default, so that users aren't caught unaware of this problem. If it's `nil` we can revert to current behaviour. Perhaps we should also make the responsive centering behaviour optional.

**Comment by deb0ch** [comment]
I think it should not be a dotspacemacs variable, else you will just be recreating the same problem where those who don't have updated their dotspacemacs will encounter the problem.

Unless I'm understanding it wrong.

Were you thinking of a default variable that would take effect only if the new `dotspacemacs-startup-lists` is `nil` ?

**Comment by TheBB** [comment]
> Unless I'm understanding it wrong.

All the dotspacemacs variables are `defvar`'d in [here](https://github.com/syl20bnr/spacemacs/blob/develop/core/core-dotspacemacs.el#L53-L331) with their default values, so it's not critical that they're not present in the dotfile.

What I'm thinking of is a variable such that this:

```elisp
(setq dotspacemacs-startup-lists
      '(bookmarks
        (recents . 10)
        projects))
```

is equivalent to 

```elisp
(setq dotspacemacs-startup-lists
      `((bookmarks . ,spacemacs--startup-lists-max-size)
        (recents . 10)
        (projects . ,spacemacs--startup-lists-max-size)))
```

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/7007

**Comment by TheBB** [comment]
Fixed!

**Comment by aaronjensen** [comment]
Thanks @TheBB
