### ISSUE TITLE
Unable to reinstall packages due to intermittent failures

### ISSUE THREAD

**Issue by paulyoung** [syl20bnr/spacemacs#6988]
<img width="693" alt="screen shot 2016-09-01 at 5 52 00 pm" src="https://cloud.githubusercontent.com/assets/84700/18189132/e2343526-706c-11e6-9b51-b3d598c941e4.png">

#### Description
I ran a package update and got into a strange state. I ended up removing everything in the elpa directory. After reinstalling I now consistently get into the above state on startup.

#### Reproduction guide
- Start Emacs
- See the error in the above screenshot

*Observed behaviour:*
Spacemacs fails to start correctly

*Expected behaviour:*
Spacemacs starts as normal

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git github markdown osx purescript react syntax-checking)
```

#### Backtrace

This is the result of running `emacs --debug-init` as suggested in my original screenshot.

Apologies for the screenshot. I wasn't able to copy and paste the text.

<img width="1610" alt="screen shot 2016-09-01 at 5 53 07 pm" src="https://cloud.githubusercontent.com/assets/84700/18189151/0e220a5a-706d-11e6-8283-7e23ebe050da.png">

**Comment by paulyoung** [comment]
I removed evil-numbers from the elpa directory and got a different error on the next startup.

I've taken the following steps (and restarted in between removing each package until I got another error)

```
➜  .emacs.d git:(master) ✗ rm -r elpa/evil-numbers-20140606.551
➜  .emacs.d git:(master) ✗ rm -r elpa/evil-search-highlight-persist-20151215.238
➜  .emacs.d git:(master) ✗ rm -r elpa/evil-surround-20160501.1704
➜  .emacs.d git:(master) ✗ rm -r elpa/exec-path-from-shell-20160812.159
➜  .emacs.d git:(master) ✗ rm -r elpa/flx-ido-20151030.1112
➜  .emacs.d git:(master) ✗ rm -r elpa/helm-flx-20160227.1652
➜  .emacs.d git:(master) ✗ rm -r elpa/js2-mode-20160826.1908
➜  .emacs.d git:(master) ✗ rm -r elpa/hl-todo-20160807.523
```

I'm almost back to where I was, except for this latest message:

<img width="693" alt="screen shot 2016-09-01 at 6 15 02 pm" src="https://cloud.githubusercontent.com/assets/84700/18189483/2c1a87be-7070-11e6-81cf-818e451f9ee4.png">

**Comment by paulyoung** [comment]
Various packages still appear to be broken. Attemping to reinstall.

**Comment by paulyoung** [comment]
More strange behavior:

<img width="693" alt="screen shot 2016-09-01 at 7 09 04 pm" src="https://cloud.githubusercontent.com/assets/84700/18190423/c56cf68e-7077-11e6-8ed3-8de5ce3b5f8e.png">

**Comment by paulyoung** [comment]
Just want to confirm that I see similar results using `emacs --insecure`, and on a different network.

<img width="1066" alt="screen shot 2016-09-01 at 8 49 46 pm" src="https://cloud.githubusercontent.com/assets/84700/18192090/c8631ba8-7085-11e6-815d-b24877f7516b.png">

**Comment by TheBB** [comment]
http://spacemacs.org/doc/FAQ.html#orgheadline4

**Comment by tko** [comment]
I just saw similar corruption and `--insecure` didn't seem to make much of a difference. After `rm -rf elpa` _some_ but not all of the packages got corrupted, seemingly random. After deleting the first offending package it always reinstalled fine the next time, and then the errors were because of the next package. Rinse and repeat. After getting to home screen cleanly there's more errors waiting when file modes etc. are triggered.

Server problems maybe, doesn't like too many concurrent(?) requests?

**Comment by TheBB** [comment]
Possibly, but it's at least more likely to be between you, your Emacs build and MELPA/ELPA than anything involving Spacemacs code.

**Comment by paulyoung** [comment]
Any advice on how to stop installing packages on the first failure, or retry in an automated way would be really helpful. Thanks again.

**Comment by paulyoung** [comment]
I still haven't been able to get things into a working state, even by addressing issues as they come up and trying to reinstall problem packages.

At this point I think I just need to try again later and see if whatever potential issue on the server resolves itself.

**Comment by paulyoung** [comment]
This seems to be related to https://github.com/melpa/melpa/issues/4191

**Comment by paulyoung** [comment]
This also sounds like my problem: https://github.com/melpa/melpa/issues/4187

I'm attempting the suggested workaround.

**Comment by paulyoung** [comment]
If anyone could explain how to do the equivalent of this in Spacemacs, I think that would help: https://github.com/melpa/melpa/issues/4187#issuecomment-243324946

**Comment by TheBB** [comment]
Should be the same. It just sets a variable. Just do it in user-init I guess.

**Comment by paulyoung** [comment]
As mentioned in https://github.com/melpa/melpa/issues/4187#issuecomment-244477345, I ended up putting this at the top of `~/.emacs.d/init.el` and then ran `emacs --insecure` and everything appears to be working!

**Comment by favadi** [comment]
Maybe you could try the mirrors in   https://github.com/melpa/melpa/issues/4157#issuecomment-243326501.

**Comment by purcell** [comment]
No need to try mirrors - we've rolled back to nginx, so workarounds should now be unnecessary.

**Comment by TheBB** [comment]
Closing this as fixed upstream.
