### ISSUE TITLE
java layer emacs-eclim install error

### ISSUE THREAD

**Issue by linchen2chris** [syl20bnr/spacemacs#6990]
#### Description :octocat:
I open the java layer, restart spacemacs, then I get

--> installing package: emacs-eclim@java... [1/1]
Package emacs-eclim is unavailable. Is the package name misspelled?

I seach eclim in package elpa, I can get *ac-emacs-eclim* and *company-emacs-eclim* 

#### Reproduction guide :beetle:
- Start Emacs
- add java to layer config
- restart it

*Observed behaviour:* :eyes: :broken_heart:
--> installing package: emacs-eclim@java... [1/1]
Package emacs-eclim is unavailable. Is the package name misspelled?

*Expected behaviour:* :heart: :smile:
install all package successfully
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. 9773ad6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(csv helm ivy syntax-checking
     (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
     (ibuffer :variables ibuffer-group-buffers-by 'projects)
     java javascript ycmd org markdown react git python
     (version-control :variables version-control-diff-tool 'diff-h1 version-control-global-margin t)
     emacs-lisp
     (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

#### Backtrace :paw_prints:
```
--> installing package: emacs-eclim@java... [1/1]
Package emacs-eclim is unavailable. Is the package name misspelled?
```

**Comment by NJBS** [comment]
This should be fixed on latest `develop`, please update your branch.

**Comment by TheBB** [comment]
See https://github.com/syl20bnr/spacemacs/issues/6949 for more issues with eclim. I'll close this as duplicate.

**Comment by linchen2chris** [comment]
thank you for your reply, after update, it work correctly now
