### ISSUE TITLE
REGRESSION: auto centering spacemacs-buffer makes resizing of windows incredibly choppy

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#6997]
#### Description :octocat:
*This probably only repros on macs*

Auto centering spacemacs-buffer (a7d4674) makes resizing of windows with mouse when spacemacs buffer is shown super choppy.

#### Reproduction guide :beetle:
- Start Emacs
- Open more than one window, at least one should be the spacemacs home buffer
- Try to resize a window with mouse

*Observed behaviour:* :eyes: :broken_heart:
You're able to resize the window but emacs freezes every couple of seconds.

*Expected behaviour:* :heart: :smile:
Emacs behaves as it does when the spacemacs home buffer is not shown, that is, resizing with the mouse works smoothly.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: nil (rev. 4e7d80b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(better-defaults spacemacs-layouts helm emacs-lisp markdown
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 (auto-completion :variables auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup nil)
                 erlang elixir git dash html clojure
                 (org :variables org-enable-github-support t)
                 colors osx github javascript react deft ruby
                 (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
                 spell-checking ranger version-control rcirc tmux yaml docker elm evil-little-word auto-correct frame-geometry cleverparens-lispy flow)
```

**Comment by aaronjensen** [comment]
Related: #6986

**Comment by TheBB** [comment]
I'm beginning to think there's something wrong with your build. This also works fine here.

**Comment by aaronjensen** [comment]
@TheBB you're not on a mac. Mac window resizing is totally funky

**Comment by aaronjensen** [comment]
Actually, if I keep the mouse held down, it does eventually go to where I'm holding, it just janks like crazy:

![jank](https://cloud.githubusercontent.com/assets/8588/18204498/feab7baa-70d1-11e6-86fe-55907924523d.gif)

**Comment by aaronjensen** [comment]
@TheBB the problem actually has to do with how many files and projects are in my recent file and project lists. If I comment those lists out from `spacemacs-buffer/insert-startupify-lists` it's fast even w/ the hook.

I have 1000 recent files. I thought there was a max on that, i'll turn it down.

Either way, I wonder if we should only render the first 50 recent files or so?

**Comment by aaronjensen** [comment]
Oh, wow. `dotspacemacs-startup-lists` changed to include limits and `dotspacemacs-startup-recent-list-size` was removed. 

Maybe there should be some sort of warning if I try and set `dotspacemacs-startup-recent-list-size` still? That's why I had 1000 recent files showing...

**Comment by aaronjensen** [comment]
Ok, it's not perfect, but it's much better with the lists limited. I'm going to close both of these out, but it seems like something more should be done about deprecating the old setting and notifying users of the new.

**Comment by TheBB** [comment]
We should maybe have a strict upper limit on the size of those lists.

**Comment by syl20bnr** [comment]
> We should maybe have a strict upper limit on the size of those lists.

Yes and `nil` should default to something reasonable for each section like 50 or something.
