### ISSUE TITLE
Missing autocomplete popup for c/c++ mode with clang_complete

### ISSUE THREAD

**Issue by jkvargas** [syl20bnr/spacemacs#6999]
#### Description

https://github.com/syl20bnr/spacemacs/issues/5122

seems that this case is happening with me, i do have clang 3.8 installed and i dont have autocomplete for some headers given by my .clang_complete file.
#### Reproduction guide
- Start Emacs
  .clang_complete contains -I/usr/local/VulkanSDK/1.0.21.1/x86_64/include

start a cpp file, include vulkan/vulkan.h, no popup when you write the function name.

_Observed behaviour:_
hitting SPC h d v, looking into company-clang-arguments there is only:

company-clang-arguments is a variable defined in `company-clang.el'.
Its value is ("-std=c++11")
Original value was nil

no popup when you start to write the name of a method/function...

_Expected behaviour:_
a popup for autocomplete.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp gtags
                 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
                 git org semantic syntax-checking)
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment]
Does it work if you manually add in the missing flag after opening the file? IOW is the problem just with reading the .clang_complete file?

**Comment by jkvargas** [comment]
![spacemacs](https://cloud.githubusercontent.com/assets/11624159/18213829/7882cc78-7120-11e6-8825-33f4825e8143.png)

yes, if I add the value manually it works.

**Comment by TheBB** [comment]
Okay, can you pastebin the .clang_complete file somewhere so I can try it?

**Comment by jkvargas** [comment]
[dotclangcomplete.txt](https://github.com/syl20bnr/spacemacs/files/453134/dotclangcomplete.txt) just rename the file as .clang_complete

**Comment by TheBB** [comment]
That file works fine for me on both master and develop.

**Comment by beta1440** [comment]
@jkvargas Do you still have this issue?
