### ISSUE TITLE
list-processes (`process-menu-mode`) needs evilification.

### ISSUE THREAD

**Issue by jcpetkovich** [syl20bnr/spacemacs#700]
Currently it starts in `normal` mode, and masks things like `q` for quitting the mode.

Should just be:

    (add-to-list 'evil-emacs-state-modes 'process-menu-mode)
    (spacemacs|evilify 'process-menu-mode)

But I'm not quite sure where you would want to put it.

**Comment by syl20bnr** [comment]
Good question... I would say in `spacemacs/config.el`

**Comment by syl20bnr** [comment]
Fixed with #708
