### ISSUE TITLE
Spacemacs torrent client

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#7001]
It is surprising but it looks like there is no well developed Emacs package that adds something like transmission :scream: Or is there? It would be cool to have something like this in Spacemacs.

**Comment by JAremko** [comment]
I found this one https://melpa.org/#/mentor 

Haven't tried it yet.

**Comment by bmag** [comment]
here's another one to try: https://melpa.org/#/transmission

**Comment by JAremko** [comment]
@bmag  Looks nice. Thanks!

**Comment by JAremko** [comment]
ok. I'll make a new layer for transmission

**Comment by JAremko** [comment]
I ran into a problem :confused:   holomorph/transmission#6

**Comment by JAremko** [comment]
Solved in #7053

**Comment by tidux** [comment]
These really should be set to auto-refresh by default.
