### ISSUE TITLE
Macros Failing / Producing Unexpected Results

### ISSUE THREAD

**Issue by exitface** [syl20bnr/spacemacs#701]
I haven't been able to pinpoint what exactly causes this, but here are a few examples, note that a non-spacemacs emacs install will produce the expected behavior.

Pipe character = position of cursor

1)
```javascript
|var url = "http://google.com";
var url = "http://google.com";
```
Define the following macro `qq -> f" -> ci" -> changed -> ESC -> j -> ^ -> q`

Buffer will now look like the following

```javascript
var url = "changed";
var url = "http://google.com";
```
Move to line 2 and hit `@q` to replay macro
Results in:
```javascript
var url = "changed";
"changed"var url = "http://google.com";
```

2)
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
  <body>
    |<a href='http://google.com'>Test</a>
    <a href='http://google.com'>Test</a>
  </body>
</html>
```
Define the macro: `qq -> f/ -> [LEFT],[LEFT] -> cw -> yahoo -> ESC -> j -> ^ -> q

Buffer now looks like

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
  <body>
    <a href='http://yahoo.com'>Test</a>
    <a href='http://google.com'>Test</a>
  </body>
</html>
```

Move to line 9 and replay the macro. Buffer remains unchanged, and fails with the error `After 0 kbd macro iterations: Keyboard macro terminated by a command ringing the bell`.

**Comment by syl20bnr** [comment]
Thank you for the report. This is on my todo list for evil-escape. I will make move it on top of the list.

**Comment by syl20bnr** [comment]
If you don't use `fd` to escape then you can add `evil-escape` to the `dotspacemacs-excluded-packages` variable in your dotfile as a work-around.

**Comment by herbertjones** [comment]
I believe it may be fixed in this PR.

https://github.com/syl20bnr/evil-escape/pull/17

**Comment by syl20bnr** [comment]
Fixed in last version on MELPA, update your packages to get it.
Thank you @herbertjones for the fix !

**Comment by syl20bnr** [comment]
You have to be on develop branch to use the MELPA version of evil-escape.
Otherwise wait for the next release of Spacemacs.
