### ISSUE TITLE
Spacemacs use double tab to indent

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#7010]
Hello,
I just notice something strange with Spacemacs. I use tab to indent code and use `(setq-default indent-tabs-mode t)`.

But Spacemacs put 2 tab by indent level, and i can't find why : 

![selection_081](https://cloud.githubusercontent.com/assets/1810149/18223681/6750afb6-71bf-11e6-82e1-90f078d601c3.png)

I don't have tthis problem in a PHP file.

Anyone know what I should do ?

**Comment by TheBB** [comment]
In web-mode HTML, `web-mode-markup-indent-offset` defines the number of spaces to indent with. The variable `tab-width` defines how many spaces a tab should be displayed as. It looks like you have set `web-mode-markup-indent-offset` to 4 and `tab-width` to 2 therefore Emacs correctly decides it needs two tabs per indent level.

**Comment by phenix-factory** [comment]
Hello,
Thank you for your quick answer !
But i didn't config anything, here my config : https://github.com/phenix-factory/config-spacemacs

I think the default config with tabs should be only 1 tab.

I'm going to try to edit `web-mode-markup-indent-offset` and `tab-width`.

**Comment by TheBB** [comment]
If you didn't configure those values, they have their defaults, which are 4 and 2.

> I think the default config with tabs should be only 1 tab.

How do you resolve an ambiguous config then? You have specified that the indent offset should be 4 but you have also specified that the tab width should be 2. If you want tab-width to always take precedence, that's fine, but good luck getting all the major modes to agree on this.

**Comment by phenix-factory** [comment]
I just use `(setq-default tab-width 4)` and the problem is solved. Thank you for your help !
