### ISSUE TITLE
Evil Numbers Transient State, numeric argument, how to show [0-9] with colored numbers

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#7013]
### Description
The Evil Numbers Transient State accepts a numeric prefix argument before pressing +/= or - to increase or decrease by that numeric amount. It should probably be indicated by adding "[0-9] amount" to the TS popup. 

### Question
How does one get the 0 and 9 numbers to show up with the bright red color: `#E12726` that indicates that the TS will stay open when the key is pressed.

It seems like the keys that are bound to run a function but not exit the TS,  are shown with the red color, and the bound keys that exit the TS are shown with the moderate blue color: `#4C8EC8`, here's how the keys are bound (q isn't bound in the current dev version but should probably be added):
https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bspacemacs/spacemacs-evil/packages.el#L191
```
        :bindings
        ("+" evil-numbers/inc-at-pt)
        ("=" evil-numbers/inc-at-pt)
        ("-" evil-numbers/dec-at-pt)
        ("q" nil :exit t)) 
```

Since the 0 and 9 aren't bound keys but only listed in the ":doc" (see below) then that causes them to be shown with the default gray text color: `#B2B2B2`

Is it possible to just color the 0 and 9 numbers without them having to be bound to call a function, because the numbers need to be pressed several times for numeric arguments larger than a single digit.

### Underscores testing
When the 0, - (dash) and 9 keys are written with underscores around them like this:
`        :doc "\n[_+_/_=_] increase number  [_-_] decrease  [_0_-_9_] amount  [_q_] quit"`

Then the next time emacs is restarted, then a *Warnings* buffer opens with this text:
Warning (emacs): Unrecognized key: _0_
Warning (emacs): Unrecognized key: _9_

and when the Evil Numbers TS is opened, then the numbers are shown with underscores: `[_0_-_9_]`.

When the underscores are removed around the numbers:
`        :doc "\n[_+_/_=_] increase number  [_-_] decrease  [0-9] amount  [_q_] quit"`

and emacs is restarted, then the `*Warnings*` buffer doesn't open, and the numbers are shown without the underscores: [0-9]

It seems like the underscores are needed to show the correct colors for bound keys. For example if the underscores are removed around the q key: [q] then the q also is shown with the default gray text color.
<br>
If there's no clear way of coloring the 0-9 keys, then they probably could be left with the default gray text color.

![evil numbers ts gray numbers](https://cloud.githubusercontent.com/assets/13420573/18227879/53c505bc-7234-11e6-9d28-eddeeee1334b.png)

#### System Info :computer:
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. bc5eb62)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp)
```

**Comment by TheBB** [comment]
Maybe you have to bind the keys to `evil-digit-argument`?

**Comment by duianto** [comment]
After binding 0 through 9 to `evil-digit-argument`:
```
("0" evil-digit-argument)
...
("9" evil-digit-argument)
```

when any of the number keys were pressed in the Evil Numbers TS then the minibuffer showed this message: 
`(wrong-type-argument commandp evil-digit-argument)`

I searched through the .emacs.d folder for "`evil-digit-argument`", and it only found these two commands: 
`evil-digit-argument-or-evil-beginning-of-line`
and
`evil-digit-argument-or-%s`

Then i tried the command without "evil-":
```
("0" digit-argument)
...
("9" digit-argument)
```
and now everything works as expected, even with multiple digits, and when the underscores are added `[_0_-_9_]`, then the numbers also show up with the bright red color. Thanks for pointing me in the right direction.

I'll make a PR with the changes.

**Comment by TheBB** [comment]
Should be fixed in master.
