### ISSUE TITLE
*spacemacs* buffer disappears when using emacsclient

### ISSUE THREAD

**Issue by aroig** [syl20bnr/spacemacs#7016]
#### Description :octocat:
Since a7d46742027, the `*spacemacs*` buffer disappears when connecting via emacsclient. As a side effect, this causes the following error message to pop up:

    Error (use-package): vi-tilde-fringe :init: No buffer named *spacemacs*

@ralesi any clue on what is going on?

#### Reproduction guide :beetle:
- Start Emacs in daemon mode: `emacs --daemon`
- open a new frame with emacsclient: `emacsclient -c`

*Observed behaviour:* :eyes: :broken_heart:
The `*spacemacs*` buffer is missing.

*Expected behaviour:* :heart: :smile:
There exists a `*spacemacs*` buffer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: nil (rev. a7d4674)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" helm-mini-default-sources
                  '(helm-source-buffers-list))
 (colors :variables color-colorize-identifiers nil)
 finance git github
 (markdown :variables markdown-indent-on-enter nil)
 (org :variables org-enable-github-support t)
 (mu4e :variables mu4e-enable-mode-line nil)
 (rcirc :variables rcirc-spacemacs-layout-name "@rcirc" rcirc-spacemacs-layout-binding "i")
 jabber twitter
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support nil)
 syntax-checking asciidoc bibtex emacs-lisp extra-langs go haskell html ipython-notebook java javascript latex lua octave python restclient ruby shaders shell-scripts sql systemd theming vimscript yaml fasd spell-checking windows-scripts ab2-base ab2-clang ab2-devel ab2-latex ab2-org ab2-mu4e ab2-visual ab2-chat ab2-science ab2-audio)
```

**Comment by deb0ch** [comment]
I was able to reproduce, and indeed it is coming from that particular commit.

Though it appears allright when creating it with `SPC b h`.

**Comment by TheBB** [comment]
Does https://github.com/syl20bnr/spacemacs/pull/7028 fix it?

**Comment by deb0ch** [comment]
At least for me it doesn't fix it =/

**Comment by TheBB** [comment]
@ralesi Any idea?

**Comment by deb0ch** [comment]
Apparently the buffer gets created again when adding the following line to `spacemacs/init` (core-spacemacs.el:l124):

``` elisp
  (unless (display-graphic-p)
    ;; explicitly recreate the home buffer for the first GUI client
    ;; in order to correctly display the logo
    (spacemacs|do-after-display-system-init
     (kill-buffer (get-buffer spacemacs-buffer-name))
     (setq spacemacs-buffer--last-width nil)        ; <------- This line
     (spacemacs-buffer/goto-buffer)))
```
 so for that matter I suspect this condition (core-spacemacs-buffer.el:l879):

``` elisp
    (when (or refresh
              (not buffer-exists))
      ;; revise banner length in GUI
      (when (display-graphic-p)
        (setq spacemacs-buffer--banner-length
              (window-width)))
      (unless (eq spacemacs-buffer--last-width spacemacs-buffer--banner-length) ; <---- This line
        (setq spacemacs-buffer--last-width spacemacs-buffer--banner-length)
        (with-current-buffer (get-buffer-create spacemacs-buffer-name)
 ```

Though after that it directly goes to the `*scratch*` buffer and I have no idea why. But the `*spacemacs*` buffer is still there.

**Comment by aroig** [comment]
I didn't have much time to look into this yet. What @deb0ch  suggests looks to me more like a workaround to force recreating the buffer than a proper fix.

When I opened the emacsclient frame, I sometimes saw the spacemacs buffer flashing before it disappears. Someone kills it. Possibly something is racing against the frame initialization... but still, who kills the buffer? What are its motives? What is the weapon of the crime? ;)

**Comment by aroig** [comment]
By the way, here is an easy workaround to avoid the annoying error message until the crime is solved:

    (setq dotspacemacs-startup-buffer-responsive nil)

**Comment by deb0ch** [comment]
@aroig I was saying that more as a hint, it is not really a suggestion.

**Comment by ankhers** [comment]
Just for when this gets fixed as it has more traction, #6976 is a duplicate.

**Comment by deb0ch** [comment]
That one is hard to fix ><

Though could manage to partially fix it in #7054.

There was indeed a logic flaw in (core-spacemacs-buffer.el:l879): is the buffer doesnt exist but the value of spacemacs-buffer--last-width is still the same, it is not re-created.

**Comment by TheBB** [comment]
@deb0ch https://github.com/syl20bnr/spacemacs/pull/7109 should finish this up.

**Comment by aroig** [comment]
I have just updated. It looks like the issue has gone away, at least in my usage pattern. So, I'm closing this.

Thanks!
