### ISSUE TITLE
Text Motions with HTML Behaving Unexpectedly

### ISSUE THREAD

**Issue by exitface** [syl20bnr/spacemacs#702]
Something seems to be interfering with text motions

In all examples the cursor beings on the opening `<` of the body tag

1)
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
  <body>
    <h1>Title</h1>
  </body>
</html>
```
`cit` or `dit` results in (note that if the cursor is on the `b` in `body` it will work correctly)
```html
<!DOCTYPE html>
<html></html>
```
However, `cat` or `dat` do perform the correct behavior of just deleting the body tag
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
</html>
```

2) 
Same as above, but with a nested tag

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
  <body>
    <h1><a href='http://google.com'>Test</a></h1>
  </body>
</html>
```

Typing `cit` or `dit` will result in the removal of the link, rather than everything within the body tag. 

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
  <body>
    <h1></h1>
  </body>
</html>
```
In this same scenario `cat` or `dat` will NOT work in correctly and will only remove the `h1` tag rather than the body tag:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>title</title>
  </head>
  <body>
  </body>
</html>
```

**Comment by syl20bnr** [comment]
Thank you for the detailed repro steps.

If I put the point in the tag (like on the b of body) the behaviors are always correct. Except with `'` instead of `"`.

Did you test with only evil installed ?

**Comment by exitface** [comment]
Yes, it works for me as well _inside_ the tag, just not on the `<`, sorry for not being explicit about that. With just evil installed, I get the correct behavior with the cursor on `<`

**Comment by StreakyCobra** [comment]
I just reproduced this bug on a stock Emacs with `web-mode` and `evil`. You can try with the last Spacemacs version with `SPC q D web-mode,evil RET`. This is not a Spacemacs bug and should be reported upstream (not sure on which project though).

**Comment by aldanor** [comment]
Fixed upstream: https://bitbucket.org/lyro/evil/issues/625
