### ISSUE TITLE
Rendering error run spacemacs in the terminal

### ISSUE THREAD

**Issue by gentcys** [syl20bnr/spacemacs#7024]
There are something wrong running spacemacs in the terminal. I don't know how to describe them, these are screenshots.
![Running in the terminal](https://cloud.githubusercontent.com/assets/10412450/18235114/4c23e3a8-7349-11e6-886b-cd33b6a4a503.png)
![Running as gui application](https://cloud.githubusercontent.com/assets/10412450/18235122/7037ee56-7349-11e6-87e0-afecb0dd87fd.png)
Another, there is one more line at the bottom running in there termianl than gui.

**Comment by syl20bnr** [comment]
I'm not sure this is a bug induced by Spacemacs, try starting emacs with `emacs -Q` which deactivate Spacemacs.

**Comment by d12frosted** [comment]
On OS X I see similar thing in Terminal.app without Spacemacs. It depends on the theme used in Terminal and theme used in Emacs. Specially, backgrounds.

**Comment by gentcys** [comment]
@syl20bnr I tried with `emacs -nw -Q`, and i found that it wasn't a bug induced by Spacemacs.

**Comment by TheBB** [comment]
Then close?
