### ISSUE TITLE
Increase delay for (setq-default evil-escape-key-sequence "jj")

### ISSUE THREAD

**Issue by drodrigo** [syl20bnr/spacemacs#7029]
Hello,

I'm new to Spacemacs and something that I'm struggling with is that I have to VERY FAST when pressing "jj" in order to Spacemacs leaves insert to normal mode, is there an option to increase the time to press the second "j" ?

Thanks.

**Comment by dubnde** [comment]
`evil-escape-delay` can be updated from the default value in `dotspacemacs/user-config`

**Comment by drodrigo** [comment]
So simple!

Sorry if it's documented somewhere but I couldn't find it!

Thanks for your quick response.
