### ISSUE TITLE
default auto-completion is REALLY slow

### ISSUE THREAD

**Issue by drodrigo** [syl20bnr/spacemacs#7030]
Hello everyone!

Something that I thought would be a common issue is that when I uncomment auto-completion and activate auto-completion mode  it actually works, but sometimes I have to wait 7-10 seconds to get some results from auto-completion. 

I thought about using this plugin: https://github.com/auto-complete/auto-complete that was working fine when I was trying to do a setup from scratch, but is it a common issue or is it just me? 
 
Thanks

**Comment by TheBB** [comment]
That depends on a lot of factors: what major mode, what backend you are using, which external tools it needs, whether the project is large, and so on. So you will need to provide more details. Usually, no, it shouldn't be that slow.

Spacemacs doesn't use auto-complete, instead we use company.

**Comment by TheBB** [comment]
Hello?

**Comment by drodrigo** [comment]
I won't  be able to reproduce since the computer I was using wasn't mine.

I got spacemacs on my personal computer now and auto-completion is working fine. Even though it was a big project I was really confused about what was going on and since I'm completely newbie when comes to Emacs it will take me some time to figure out what was happening before. If I get what was causing the problem (or be able to reproduce the weird behavior) I'll bring this topic again here.

Btw sorry for not responding quickly...

**Comment by TheBB** [comment]
Sure, no problem. :+1:
