### ISSUE TITLE
Greedy register-usage

### ISSUE THREAD

**Issue by scriptmode** [syl20bnr/spacemacs#7031]
#### Description

When using registers in visual state, immidiatly followed by a command which should access the default register, then instead that command is using the named register from the former command.

It's not clear whether it only happens when visual state is involved. Some test with normal state works as excepted, some other as observed with visual state.
#### Reproduction guide
- Start Emacs 
- Open a file with text.
- Position curor at beginning of some block of text.
- Select some text (For example: v3j)
- Save the selected text in a named register (For example: "bx)
- Use some command that saves something in the default register (For example: dd)
- Move cursor somewhere else and paste the content of the named register (For example: "bp)
- Wonder why the content from the first command is not pasted.

Example keysequence: v3j"bxdd3j"bp

_Observed behaviour:_ 
The second command has accessed the named register used by the first command

_Expected behaviour:_ 
The second command should have used the default register, not overwritten the content in the named register from the first command
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master  rev. 9f9faa4 
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:    elisp  ansible auto-completion better-defaults dockerfile emacs-lisp git html ibuffer lua markdown org  python :variables python-test-runner  pytest anaconda-mode-port 9500  ranger search-engine  shell :variables shell-default-height 30 shell-default-position  bottom  shell-scripts  spell-checking :variables spell-checking-enable-by-default nil  sql syntax-checking version-control vimscript

**Comment by TheBB** [comment]
This repros just fine with only evil, therefore it's an upstream bug.

**Comment by TheBB** [comment]
From reading some code it looks like visual state is necessary to reproduce this bug, and the problem is that `evil-visual-post-command` doesn't do anything about `evil-this-register` such as `evil-normal-post-command` does.
