### ISSUE TITLE
Can't load Base16-3024 

### ISSUE THREAD

**Issue by Androcas** [syl20bnr/spacemacs#7034]
Hi,
a bug occured when I tried to change my default theme: installing the package `base16-theme` and putting `base16-3024` in `dotspacemacs-themes` (this is the name that appears with `SPC T h`) throws this warning at startup:
`Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (error Package base16-3024-theme- is unavailable))`

@Bastacyclop fixed it by replacing `base16-3024-dark/light` with `base16-3024` in [these two lines](https://github.com/syl20bnr/spacemacs/blob/master/core/core-themes-support.el#L33).

**Comment by NJBS** [comment]
Fixed in develop, https://github.com/syl20bnr/spacemacs/pull/6905

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
