### ISSUE TITLE
Folding doesn't work for HTML/XML

### ISSUE THREAD

**Issue by tobimensch** [syl20bnr/spacemacs#7036]
Using the za shortcut doesn't work for XML/HTML tags/files.

Although opening/closing tags are visually indicated correctly!

I think this shortcut (and others similar to it) should work consistent for different types of source code.

**Comment by nixmaniack** [comment]
I agree that `code-folding` isn't that great and consistent, and if you're using the default folding method `evil` it's not best experience. You might get better results by changing `dotspacemacs-folding-method` to `'origami`.

**Comment by nixmaniack** [comment]
I agree that `code-folding` isn't that great and consistent, and if you're using the default folding method `evil` it's not best experience. You might get better results by changing `dotspacemacs-folding-method` to `'origami`.

**Comment by TheBB** [comment]
Origami has decent folding support in these modes based on indentation. Marking this as fixed in develop, therefore.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by tobimensch** [comment]
Is it possible to use origami in xml/html buffers while still using evil code folding everywhere else?
