### ISSUE TITLE
pandoc-data-dir variable in pandoc layer should be set to private dir

### ISSUE THREAD

**Issue by bdarcus** [syl20bnr/spacemacs#7037]
By default, the `pandoc-data-dir` variable is set to `~/.emacs.d/pandoc-mode`. Given spacemacs conventions, should be set to `~/.emacs.d/private/pandoc-mode`.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/commit/6bb4416585ad18a1a0d01a14659d58317f19e021

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
