### ISSUE TITLE
UI freezes when you type in Emacs 25

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#7038]
#### Description :octocat:

Emacs-lisp mode in Emacs 25 freezes. I suspect it has something to do with company-mode.
I do not see this in Emacs 24. 
I am not sure yet, but I think disabling company-mode "fixes" this. It might be an upstream issue with company.el

![emacs-25-company](https://cloud.githubusercontent.com/assets/1091022/18257629/ca08bf32-737b-11e6-85da-1c020b928623.gif)
#### Reproduction guide :beetle:
- Start Emacs
- Open any emacs-lisp mode file. Start typing

_Observed behaviour:_ :eyes: :broken_heart:
there are messages in mini-buffer about parsing and compiling things and that process is blocking Emacs's main UI
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 107fe46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((org :variables org-enable-reveal-js-support t)
 (auto-completion :variables auto-completion-tab-key-behavior 'cycle)
 emacs-lisp javascript html markdown shell-scripts clojure lua react
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rvm)
 ruby-on-rails
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 syntax-checking spell-checking helm
 (shell :variables shell-enable-smart-eshell t shell-default-term-shell "/bin/zsh")
 (deft :variables deft-directory "~/Google Drive/deft" deft-auto-save-interval 60)
 fasd ibuffer osx chrome semantic restclient emoji ranger search-engine imenu-list pdf-tools git
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 (github :variables gist-view-gist t)
 agzam ag-dash synonyms)
```

**Comment by aijony** [comment]
Hey agzam it's a lot more helpful for me to see the issue. Now I think that could be an issue with the 'spell-checking' layer, because it says starting new ispell process. Try disabling that, I know it has given me similar issues. If that doesn't solve it then my second guess is that it's a problem with emacs 25 [async](https://github.com/jwiegley/emacs-async).

**Comment by zilongshanren** [comment]
@agzam  I think you could disable semantic-mode in emacs-lisp-mode to get rid of this issue.

**Comment by sooheon** [comment]
For me, this only happens inside strings/comments, as well. As far as I can tell, it's not really to do with company or ispell, but semantic is the main culprit like @zilongshanren says.

**Comment by syl20bnr** [comment]
To disable the `semantic` layer support in `emacs-lisp` you should be able to use this declaration:

```
(semantic :disabled-for emacs-lisp)
```

**Comment by agzam** [comment]
Yup it worked... should we close this, or maybe think about implementing a flag of some sort, so people switching to 25 struggle less?

**Comment by TheBB** [comment]
Would `:toggle` work for non-owned packages in a layer?

**Comment by syl20bnr** [comment]
Yes `:toggle` should be overridable by non owning functions in current develop. It was not the case before my last few commits on the layer system, I made a few changes like the variable to inhibit side effects when `SPC h SPC` is invoked (which parses all the layers to gather information), it allows to have consistent capability to override any keywords without their side effects to be active with `SPC h SPC`.

**Comment by JAremko** [comment]
Still happening to me :cry:

**Comment by d12frosted** [comment]
@JAremko have you tried disabling `semantic` layer?

**Comment by JAremko** [comment]
@d12frosted  As soon as I saw it(like after using emacs 25 for 5 minutes.) I switched back to 24, assuming that it's just a beginning  :smile: 

But this will be a problem for "the thing"

**Comment by syl20bnr** [comment]
I have the same issue with Emacs 25 in comments in elisp.

**Comment by d12frosted** [comment]
The same here. But only when I enable `semantic` layer.

**Comment by ninjarai4** [comment]
I found a workaround to this issue without disabling auto-completion or semantic by putting this in my user-config:
    
    (with-eval-after-load 'semantic
        (cl-delete-if (lambda (x) (string-match-p "^semantic-" (symbol-name x))) completion-at-point-functions))

There is some more disscussion [here](https://github.com/company-mode/company-mode/issues/525)

**Comment by ninjarai4** [comment]
Correcting the code in my previous comment:
    
    (with-eval-after-load 'semantic
        (add-hook semantic-mode-hook
                  (lambda ()
                    (cl-delete-if (lambda (x)
                                    (string-prefix-p "semantic-" (symbol-name x)))
                                  completion-at-point-functions))))

Without the add-hook it won't always work.

**Comment by sooheon** [comment]
Thank you, but `semantic-mode-hook` should be quoted I think!

**Comment by ninjarai4** [comment]
Wow, I have no idea how that was working before. I've edited my comment with the correct code, thanks for the help.

**Comment by agzam** [comment]
Sorry, late to the party, couple of questions: 

 - Could this be included in the semantic layer?
 - What are the benefits of enabling semantic for emacs-lisp mode? I have disabled it and I don't feel like missing anything.

**Comment by aijony** [comment]
I was still having this issue on the develop branch. 

This snippet did not work for me:
```
(eval-after-load 'semantic
    (add-hook 'semantic-mode-hook
              (lambda ()
                (dolist (x (default-value 'completion-at-point-functions))
                  (when (string-prefix-p "semantic-" (symbol-name x))
                    (remove-hook 'completion-at-point-functions x))))))
```
This one did:
```
(semantic :disabled-for emacs-lisp)
```
