### ISSUE TITLE
bibtex layer "symbol's value as variable is void" error in markdown and latex

### ISSUE THREAD

**Issue by bdarcus** [syl20bnr/spacemacs#7040]
If I open a markdown file and try to insert a citation, i get a "symbol's value as variable is void" error.

If I then open up an org file in the org layer, and do the same thing, I get expected behavior; helm-bibtex open up, etc.

If I then go back to the markdown layer, THEN it works correctly.

Same behavior with LaTeX.

In short, then, bibtex layer only works correctly if org-mode is first loaded.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 107fe46)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git markdown
                 (pandoc :variables pandoc-data-dir "~/.emacs.d/private/pandoc-mode")
                 bibtex haskell intero elixir ruby python org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control)
```

**Comment by TheBB** [comment]
This is a bug in org-ref. Please report upstream. The function `org-ref-helm-insert-cite-link` is autoloadable but the file in which it is defined does not load all the files it needs.

**Comment by TheBB** [comment]
Workaround here: https://github.com/syl20bnr/spacemacs/pull/7047

**Comment by bdarcus** [comment]
Thanks. [Reported](https://github.com/jkitchin/org-ref/issues/284).

**Comment by TheBB** [comment]
Fixed upstream.
