### ISSUE TITLE
Make selected theme permanent

### ISSUE THREAD

**Issue by tobimensch** [syl20bnr/spacemacs#7041]
Currently I can install and select a theme easily.

But everytime I reload emacs the theme and the settings are gone. (I need to reinstall the package in order to see the theme in the list of themes again). I tried to put the (load theme *) line in my .spacemacs config, but to no avail.

I think it should behave like in other modern IDE/editors, so when I install and select a theme that theme should be the new default/permanent setting, until the user changes it again.

The configuration should be updated accordingly.

**Comment by NJBS** [comment]
You'll need to modify the value of `dotspacemacs-themes` in your `.spacemacs` file such that the theme you want to use is the first value in the list:
```
   ;; List of themes, the first of the list is loaded when spacemacs starts.
   ;; Press <SPC> T n to cycle to the next theme in the list (works great
   ;; with 2 themes variants, one dark and one light)
   dotspacemacs-themes '(spacemacs-dark
                         spacemacs-light
                         solarized-light
                         solarized-dark
                         leuven
                         monokai
                         zenburn)
```
https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template#L95-L104

**Comment by tobimensch** [comment]
ok, that works. Thank you. My point is just that something like that should be handled automatically.

**Comment by yilihong** [comment]
that will be a cool feature to have. 

I change theme from time to time too.

**Comment by jsmestad** [comment]
I'd like to see this as well. Makes sharing configurations a bit easier when everyone has a complete theme list and picking one persists that across sessions. Right now we have to maintain a fork just to put our preferred theme first.
