### ISSUE TITLE
Lisp error: (void-variable osx-use-dictionary-app)

### ISSUE THREAD

**Issue by hiberno** [syl20bnr/spacemacs#7042]
I am running Spacemacs using the `develop` branch (mostly, because the `CSV` layer hasn't been merged into master yet) and pulled the latest changes this morning. Since then, Spacemacs aborts loading with the following error:

```
Symbol's value as variable is void: osx-use-dictionary-app
```

I suspect the error to stem from here: `layers/+spacemacs/spacemacs-languages/packages.el:13`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. edf16ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(auto-completion better-defaults c-c++ clojure colors csv emacs-lisp evil-cleverparens evil-commentary evil-snipe git github haskell html ivy java javascript latex markdown nixos notmuch org puppet rust scheme
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 shell-scripts spell-checking sql syntax-checking version-control weechat yaml)
```

**Comment by StreakyCobra** [comment]
```
$ git blame layers/+spacemacs/spacemacs-language/packages.el
[...]
047b5722 (syl20bnr 2016-09-05 11:51:30 -0400 13)       '((define-word :toggle (not osx-use-dictionary-app))
[...]
```

:purple_heart: :grin:

**Comment by kccai** [comment]
Just tested. This is fixed in #7044 :smile:

**Comment by d12frosted** [comment]
Fix is in `develop`. Closing this issue since it's develop-branch only.

**Comment by hiberno** [comment]
Thank you, that was quick! Now I know how to fix this kind of error, might open a PR myself next time. Well, thank you!
