### ISSUE TITLE
symbol's value as variable is void: osx-use-dictionary-app

### ISSUE THREAD

**Issue by thepreacher** [syl20bnr/spacemacs#7043]
This is definately a bug however I am unable to report it via the recommended  [SPC h I] or [M-m h I] because those key combinations don't work. 

I did a fresh install brew install emacs -HEAD, then installed the develop version of spacemacs. Upon starting emacs for the first time, I get to choose the between Evil and Regular Emacs (I choose Evil), after that is the choice between Helm and Ivy for completion (I choose Ivy). Emacs tries to install stuff then pops up with the message 

`symbol's value as variable is void: osx-use-dictionary-app`

then everything stops. I confirm that swaping the develop branch for the master branch of spacemacs makes this problem go away which suggests to me that its peculiar to the develop branch.

I've reverted to the master branch in order to get work done but I'd really like to use the develop branch.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/7042
