### ISSUE TITLE
let: Symbol's function definition is void: avy--with-avy-keys

### ISSUE THREAD

**Issue by asdyjd** [syl20bnr/spacemacs#7045]
#### Description
DESCRIPTION OF THE PROBLEM
In the '*spacemacs*' buffer,I press 'o'.But it prompt 'let: Symbol's function definition is void: avy--with-avy-keys'
Is it a bug?
#### Reproduction guide
-d:/note/

**Comment by TheBB** [comment]
What's your Spacemacs version? We fixed this a long time ago from what I can remember.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/5307
