### ISSUE TITLE
Pop Shell doesn't keep user set directory

### ISSUE THREAD

**Issue by tobimensch** [syl20bnr/spacemacs#7046]
Hi,

I like to use the default-pop-shell, cd into whatever directory I want (usually the build directory), start compiling (or something else), browse the source some more, toggle the default-pop-shell again.

In the last step the default-pop-shell automatically tries to change directories to the according to the current buffer's file. Which messes with the custom set directory, and with the way I intend to use that shell.

However I like the feature in principle that when the pop shell is opened for the first time, that it is in the same directory as the opened file. That's the part I'd like to keep.

**Comment by TheBB** [comment]
Set `shell-pop-autocd-to-working-dir` to `nil`.

**Comment by tobimensch** [comment]
Thank you.
