### ISSUE TITLE
Is thera a layer for crystal lang?

### ISSUE THREAD

**Issue by mrkaspa** [syl20bnr/spacemacs#7052]
Is there a way to set up the editor for this language https://crystal-lang.org/ ?

**Comment by TheBB** [comment]
No work done on this as far as I'm aware.

**Comment by tuhdo** [comment]
@mrkaspa you may need to add it your own: https://github.com/jpellerin/emacs-crystal-mode

**Comment by benjamreynolds** [comment]
There is a contrib layer [here](https://github.com/juanedi/crystal-spacemacs-layer) but it looks like the crystal mode package itself has been forked a few times and the community hasnt landed on one really. (likely because the crystal community is relatively small)

**Comment by kommen** [comment]
Crystal lang layer was added here: https://github.com/syl20bnr/spacemacs/commit/fe7cc15a8a7edc92e8acde1b53033b6fee9771cb

**Comment by lagerfeuer** [comment]
will this make it to master any time soon?

**Comment by duianto** [comment]
There's beta testing going on for a major feature for the next release:
Beta testing of spacelpa ELPA repository on various OS distributions #12652

But I would not guess when the next version will be released.


You can test the crystal layer now on the develop branch:
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/crystal

If you backup your current setup, and make sure that there's no `.emacs.d` directory or `.spacemacs` file in your home directory, then you can clone and checkout the develop branch directly:
```
git clone -b develop https://github.com/syl20bnr/spacemacs ~/.emacs.d
```
https://github.com/syl20bnr/spacemacs/tree/develop
