### ISSUE TITLE
Code block forground and background contrast very low, making it impossible to see code while typing.

### ISSUE THREAD

**Issue by thepreacher** [syl20bnr/spacemacs#7056]
System Info

    OS: osx
    Emacs: 25 
    Spacemacs: 0.1.5.22
    Spacemacs branch: develop
    Graphic display: t
    Distribution: spacemacs
    Editing style: vim
    Completion: ivy

<img width="565" alt="screen shot 2016-09-07 at 03 10 06" src="https://cloud.githubusercontent.com/assets/219075/18298118/02671936-74ae-11e6-82b3-8cba05e302e1.png">

As you can see from the screen shot above the contrast of the code block makes it unreadable without considerable effort. I'm only reporting it here because the master branch doesn't have this problem. I have tried three themes so far with the spacemacs develop branch:

`sanityinc-solarized-dark`
`base16-tomorrow-dark`
`spacemacs-dark`

of these only `spacemacs-dark` is readable, `sanityinc-solarized-dark and base16-tomorrow-dark` have the same problem as depicted by the screen shot above.

I happens the first time you type code into a `{} or "" or ()` any block structure as in the above `do end`.

I'll appreaciate any help or direction as to how to fix this.

**Comment by bmag** [comment]
The highlight can be disabled by unsetting `sp-highlight-pair-overlay`:
```elisp
(setq sp-highlight-pair-overlay nil)
```

If you want to change the highlight overlay, you can report the issue upstream at the relevant theme's bug tracker or repository, or modify `sp-pair-overlay-face` via the `theming` layer.

You might also want to change `sp-highlight-wrap-overlay` and `sp-wrap-overlay-face`.

**Comment by TheBB** [comment]
I made https://github.com/syl20bnr/spacemacs/pull/7058

**Comment by thepreacher** [comment]
Thanks everybody, indeed adding the fix from ThBB's PR has fixed the issues for me. Thanks ever so much. I know an editor theme is maybe not the most important but for some of us we just like things just right. Maybe there's a bit of OCD lurking somewhere :)
