### ISSUE TITLE
Bug: Neotree expand directory cursor jump

### ISSUE THREAD

**Issue by tgroshon** [syl20bnr/spacemacs#7057]
#### Description
When expanding a directory in Neotree (with `RET` or `l`), the cursor jumps up to the top of the listing.

#### Reproduction guide
- Start Emacs
- Open neotree (SPC-f-t or SPC-p-t)
- Navigate to and expand a directory (`RET` or `l` over a directory listing)

*Observed behaviour:*
After expanding the directory successfully, the cursor jumps to the top of the neotree buffer.

*Expected behaviour:*
After expanding the directory successfully, the cursor should stay where it is.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible better-defaults emacs-lisp clojure elm floobits
         (git :variables git-gutter-use-fringe t)
         go java javascript markdown org osx python react
         (ruby :variables ruby-enable-enh-ruby-mode t)
         rust shell syntax-checking terraform yaml)
```

**Comment by bmag** [comment]
I can't reproduce the issue on develop branch and Emacs 25.1-rc2. Don't know if that's because I'm on develop or because of the Emacs version.

**Comment by tobimensch** [comment]
Can confirm!

**Comment by TheBB** [comment]
I don't know what you're confirming @tobimensch but I can confirm that I'm also unable to reproduce.

**Comment by tobimensch** [comment]
I can confirm that the issue exists in master.

**Comment by tgroshon** [comment]
@TheBB did you try reproducing with that master rev (9f9faa4) and on Emacs 24.5?

**Comment by TheBB** [comment]
Nope, going back to master is kinda time consuming.

**Comment by TheBB** [comment]
You're right, though, it does reproduce in master, so I can probably label this as fixed in develop.

**Comment by tgroshon** [comment]
Thanks for digging into that guys!

**Comment by eastwood** [comment]
Can confirm this issue too :)

**Comment by jamlen** [comment]
Reproducible on emacs-24.5.1 and spacemacs-0.105.22

**Comment by bmag** [comment]
Now I'm seeing the same issue on develop branch, right after I updated NeoTree package. Probably an upstream issue, will investigate.

**Comment by tgroshon** [comment]
@bmag that makes sense, as I had also updated all my packages not long before noticing the issue.

**Comment by tgroshon** [comment]
NeoTree patched the bug and published to melpa.  I confirm that updating the neotree package fixes this bug.

Thanks for taking the time to look into this everyone!
