### ISSUE TITLE
dotspacemacs-install-packages 'all broken

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#7059]
When run Spacemacs with `dotspacemacs-install-packages 'all` the function `spacemacs/toggle-line-numbers-off` is undefined.  Using  `dotspacemacs-install-packages 'used-but-keep-unused`  works fine.

@syl20bnr  If it's a bug I think it need to be fixed before release :confused:

**Comment by syl20bnr** [comment]
I cannot reproduce it, is this bug still valid. If yes, what's the repro steps ?

**Comment by JAremko** [comment]
@syl20bnr 

1. use [this](https://gist.github.com/JAremko/df155133b8b19f744042800908dab073) as `.spacemacs`
2. `SPC` `h` SPC` and open random file.

**Comment by JAremko** [comment]
Also it may require Spacemacs installation from that .spacmeacs

**Comment by JAremko** [comment]
@syl20bnr nuked my Spacemacs (absolutely) and used that ^^^^^ bash snippet. Started emacs - got a bunch of errors + the bug.   Then executed `sed -i "s/dotspacemacs-install-packages 'all/dotspacemacs-install-packages 'used-but-keep-unused/" ~/.spacemacs` and started emacs - all is ok.

**Comment by syl20bnr** [comment]
Thanks, I'm looking into it.

**Comment by syl20bnr** [comment]
Fixed in 0.200.1

**Comment by JAremko** [comment]
@syl20bnr  Awesome! :heart:

**Comment by ksjogo** [comment]
This patch breaks :excluded entries in dotspacemacs-additional-packages in dotfile. 'dotfile is not in configuration-layer--used-layers, thus the exclude won't be taken.

**Comment by zilongshanren** [comment]
@ksjogo  
Before apply this patch, it seems there is no method to install a package which is excluded in layer.

Now I could add the excluded package name in the dotspacemacs-additional-packages which seems good for me.

**Comment by syl20bnr** [comment]
@ksjogo thank for the report, I don't think this is a bug there is a dotfile variable for this purpose: `dotspacemacs-excluded-packages`.

But I can add a warning to explicitly say that `:excluded` is ignored and that a user should to use `dotspacemacs-excluded-packages` variable instead.

**Comment by syl20bnr** [comment]
@ksjogo thank for the report, I don't think this is a bug there is a dotfile variable for this purpose: `dotspacemacs-excluded-packages`.

But I can add a warning to explicitly say that `:excluded` is ignored and that a user should to use `dotspacemacs-excluded-packages` variable instead.

**Comment by ksjogo** [comment]
I was qqing some excluded values, so I only needed them in one place, will look into moving to excluded packages.
Anyway, why is the dotfile layer not seens as used layer?

**Comment by syl20bnr** [comment]
@ksjogo this is a good question :-) I have not the answer right now, I need to think about it and the implication (right now the dotfile can own a package config but it is not a really a layer).
