### ISSUE TITLE
Window equalization (SPC w =) doesn't always work.

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#7062]
#### Description :octocat:

Even if golden ratio is off, sometimes pressing `SPC w =` gives you some super interesting results:

This is without golden ratio on: http://d.pr/i/1fRE1/29A6YnSD
Here's what happens if I turn golden ratio on while in the top right corner: http://d.pr/i/18QeY/3HRnAzgQ

It is clearly broken in both states.  I'm not totally sure how to reproduce.  It doesn't ALWAYS happen.
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. ae6bd22)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(sql unscroll auto-completion emacs-lisp git yaml github javascript html markdown extra-langs python org osx python django syntax-checking spell-checking colors spacemacs-layouts vimscript helm
     (version-control :variables version-control-diff-tool 'diff-hl)
     (c-c++ :variables c-c++-enable-clang-support t)
     (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by TheBB** [comment]
That doesn't give us a lot to work with…

**Comment by ksjogo** [comment]
`balance-windows` is a vanilla emacs function, can you try it on your setup with spacemacs?
