### ISSUE TITLE
Move file size away from file name and next to encoding in mode line

### ISSUE THREAD

**Issue by tobimensch** [syl20bnr/spacemacs#7064]
Reasoning:
1) The filename should always start at the same "pixel"/position. For example sometimes I left/right click on the filename to switch buffers, and when the filename start position varies it's not perfectly predictable if the mouse cursor will still be over the file name with the next click. Also it'd also look better and more consistent if the file name was always in the exact same (pixel) position. 
2) The file size is a similar type of information as the file encoding or the current position of the cursor.
3) The file size appearing first in the mode line suggests that it's the most important information about a buffer. When the file/buffer name is clearly the most important information, and the file size is at best auxiliary.

Suggested solution:
Put the file size information left next to the encoding information.

Example:
"7.1k | utf-8 | 6: 5" instead of "utf-8 | 6: 5"

If there is opposition to making this change, I'd like to have an option.

**Comment by TheBB** [comment]
This should probably be an issue to spaceline instead of spacemacs. It's a very easy change to make though. And I agree.

**Comment by tobimensch** [comment]
I copied this issue for spaceline.

**Comment by TheBB** [comment]
Reported upstream, so closing.
