### ISSUE TITLE
Spacemacs on Sabayon Linux does not start properly

### ISSUE THREAD

**Issue by AresAndy** [syl20bnr/spacemacs#7065]
Hello, I'm encountering some issues running Spacemacs under Sabayon linux.
I just cloned the repository under ```.emacs.d``` as explained in the guide.
After I start Emacs, it does not change the theme, it does not start its installation
routines (I already installed successfully Spacemacs under Archlinux and Gentoo), and
I end up with the dull unchanged Emacs. Launching it with the ```--debug-init``` flag from
terminal it does not output a thing. What should I do?

**Comment by bmag** [comment]
If Spacemacs doesn't even try to startup, the most likely cause is that you have a `~/.emacs`, which is loaded instead of `~/.emacs.d/init.el`. You can verify this by typing `C-h v user-init-file RET` and checking the variable's value. Solution is to delete or move `~/.emacs` out of the way.

**Comment by AresAndy** [comment]
Found the .emacs file .. I can't believe I overlooked it so many times.. Thanks
