### ISSUE TITLE
Clojure layer does not respect `(setq cider-repl-popup-stacktraces nil)` var in `user-config()`

### ISSUE THREAD

**Issue by aeberts** [syl20bnr/spacemacs#7068]
#### Description
The variable `cider-repl-popup-stacktraces` is ignored when set to `nil` in `user-config()`.

#### Reproduction guide
- Start Emacs
- Set `cider-repl-popup-stacktraces` to `nil` in `user-config()`
- Start a repl using `, s i `
- Enter something in the repl that will cause an error e.g. `(/ 1 0)`

*Observed behaviour:*
- The `*cider-error*` buffer is displayed in a popup window.

*Expected behaviour:*
- No `*cider-error*` buffer is displayed.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(osx
 (auto-completion :variables auto-completion-enable-snippets-in-popup)
 better-defaults emacs-lisp
 (org :variables org-enable-github-support t)
 git github markdown clojure python html erc
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control themes-megapack)
```

### Code that may be source of the problem

from: `/.emacs.d/layers/+lang/clojure/packages.el`
```
(defun clojure/pre-init-popwin ()
  (spacemacs|use-package-add-hook popwin
    :post-config
    (push '("*cider-error*" :dedicated t :position bottom :stick t :noselect nil :height 0.4)
          popwin:special-display-config)
    (push '("*cider-doc*" :dedicated t :position bottom :stick t :noselect nil :height 0.4)
          popwin:special-display-config)))
```

**Comment by mahinshaw** [comment]
@aeberts - `cider-repl-popup-stacktraces` is a deprecated var in cider refer to [Changelog](https://github.com/clojure-emacs/cider/blob/de7d734dd2551522eeac48c65c581c0b1e1c325f/CHANGELOG.md#L550)

**Comment by aeberts** [comment]
@mahinshaw Thanks for the heads-up. I can confirm that removing:

```(setq cider-repl-popup-stacktraces nil)``` 

and adding:

```(setq cider-show-error-buffer 'except-in-repl)```

to the user-config section of the .spacemacs file solves the problem on my setup and the error buffer is no longer shown when an error appears in the repl.

**Comment by d12frosted** [comment]
Great to hear! Closing this issue as being solved. 💃
