### ISSUE TITLE
file delete and file rename under different namespaces

### ISSUE THREAD

**Issue by BrianHicks** [syl20bnr/spacemacs#707]
- deleting a file: `SPC f D`
- renaming a file: `SPC b r`

Should these be under the same namespace? Since they both deal with buffers backed by real files, I would think `SPC f` to be the appropriate prefix.

Would you accept a PR for this? I can probably figure it out. :)

**Comment by syl20bnr** [comment]
`SPC f r` is taken so it would go on `SPC f R`.
But we may keep `SPC b r` as well because buffer without any visited file can be renamed too.

**Comment by BrianHicks** [comment]
Good point. IMO it would make sense to have capital letters for both
anyway, since they both modify the filesystem.

**Comment by syl20bnr** [comment]
I moved `SPC b r` to `SPC f R` in develop.
