### ISSUE TITLE
Opening Spacemacs with emacsclient results in input focus but not display focus

### ISSUE THREAD

**Issue by sampablokuper** [syl20bnr/spacemacs#7078]
#### Description

When starting Spacemacs via `emacsclient`, Spacemacs does not receive focus from the window manager, i.e. the Spacemacs window (or "frame", I think, in Emacs terminology) is not brought to the front.

Anton Tarasenko reported a [similar issue](http://stackoverflow.com/q/7559060/82216) affecting Emacs in 2011, as did Gyom on EmacsWiki [in 2010](https://www.emacswiki.org/emacs?action=browse;id=Gyom;revision=14), so perhaps this is an upstream bug.
#### Reproduction guide

In Bash on Debian 8 "Jessie" GNU/Linux with Gnome 3, open Spacemacs (GUI rather than terminal). Then open Terminal, maximise the Terminal window, and do as follows:

```
$ touch foo.txt
$ emacsclient -a "" foo.txt
```

_Observed behaviour:_

Spacemacs is not brought to the front, so because Terminal is maximised, the Spacemacs window (i.e. "frame" in Emacs terminology) is not visible. That is, Spacemacs does not receive display focus.

However, Spacemacs does get input focus. For example, if I next type `ifoo<Esc>` then "foo" is inserted at the beginning of the buffer. I can't actually _see_ that it has been inserted, because Spacemacs is still hidden behind the Terminal, but if I Alt-Tab to Spacemacs, then I can see Spacemacs and can see the inserted text.

_Expected behaviour:_

The Spacemacs window (i.e. "frame" in Emacs terminology) would receive both display focus and window focus. That is:
- it would be brought to the front, so that any other windows are behind it, and
- key-presses from the keyboard would be sent to it.

As described above, the second of these two things happens as desired, but the first does not.
#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp finance html markdown org)
```

**Comment by TheBB** [comment]
Certainly not a Spacemacs bug. I use a wrapper script that fixes it: https://github.com/TheBB/dotfiles/blob/master/scripts/ecli#L5
