### ISSUE TITLE
improve consistency of the <ESC> key in ivy buffers

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7079]
`SPC f f` brings up the helm-find-files buffer. Pressing `<ESC>` while inside this buffer quits the buffer, as expected.

`SPC s s` brings up the swiper buffer. pressing `<ESC>` in this buffer brings up a which-key buffer with tons of other options (as seen by the screenshot bellow). Among those options, theres a ESC subgroup. If you Press ESC again, which-key narrows down to more options where finally you can see that pressing ESC again will quit the current ivy buffer because it will issue the function `keyboard-escape-quit`. 

So I have to press `<ESC>` 3 times, but only if I'm in an ivy buffer. If I'm inside a helm buffer, it's only one time. Seems rather inconsistent and bothersome.

How can I fix that behaviour across all temporary buffers? I want that `<ESC>` quits the current buffer when the current buffer is not meant to sport a normal mode. Is there a way to achieve that? 

Thanks in advance.

<img width="1280" alt="screen shot 2016-09-10 at 11 31 00 am" src="https://cloud.githubusercontent.com/assets/8352747/18411246/1bece02c-774a-11e6-95fc-842c0a0c7b45.png">

**Comment by bmag** [comment]
1. How is it that you're using both Ivy (swiper) and Helm at the same time?

2. according to Spacemacs source, `<escape>` is already configured to exit Ivy if you're using vim style or hybrid style with `hybrid-mode-enable-hjkl-bindings`

3. here's how you can bind `<escape>`:
```elisp
(define-key ivy-minibuffer-map (kbd "<escape>") 'minibuffer-keyboard-quit)
```

4. the standard Emacs way of quitting a command or a prompt is `C-g`

**Comment by ninrod** [comment]
I've just put ivy and helm in the layers section. Is that like, not recommended? 

Ok, I'm not using `hybrid-mode-enable-hjkl-bindings` but I'm using hybrid style. Maybe activating `hybrid-mode-enable-hjkl-bindings` will fix it? trying that.

**Comment by ninrod** [comment]
Ahm, how can I exactly enable hybrid-style with hjkl-bindings? it says that i have to configure a `:variable`but I have no clue on how I could do that (zero lisp experience).

**Comment by ninrod** [comment]
Ok, I have found the following link: https://github.com/syl20bnr/spacemacs/blob/develop/doc/DOCUMENTATION.org#hybrid

there's lisp block on there: 

```lisp
(setq-default dotspacemacs-editing-style '(hybrid :variables
                                           hybrid-mode-enable-evilified-state t
                                           hybrid-mode-enable-hjkl-bindings nil
                                           hybrid-mode-default-state 'normal)

```

I guess i have to change that to `hybrid-mode-enable-hjkl-bindings t`. 

Oh god I'm learning lisp now.

**Comment by nixmaniack** [comment]
> I've just put ivy and helm in the layers section. Is that like, not recommended?

AFAIK, at present, in spacemacs `ivy` and `helm` are _mutually exclusive_. It's an unknown territory and you're on your own! 

And if my understanding is correct, we might have some kind of warning if users are using both layers.

**Comment by ninrod** [comment]
oh! all right, I will try to stick with just one of those. 

By the way, which one do you prefer? advantages, rants, thoughts?

**Comment by ninrod** [comment]
closing, since @bmag 's comment solved the issue.
