### ISSUE TITLE
[question] how to make the magit-diff buffer to accept vim-keybinds in commit window?

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7080]
i love the magit commit window. It splits the frame and shows me two windows: one for the commit msg and one with a magit-diff showing me the diffs of my current proposed staged changes. Lovely. 

Now suppose that I want to copy a little text snippet that lies in the magit-diff window. I can easily navigate to the magit-diff buffer with `SPC w j`. But when I choose to copy a word with `yiw` or simply navigate a char to the right with `l`, all hell breaks loose because `l` is bound to some magit hunk staging thing. 

So how can I tell magit-diff buffer to behave like a normal buffer, but leave those lovely highlighted diffs untouched?

**Comment by nixmaniack** [comment]
Two ways:

1. Set `evil-magit-want-horizontal-movement`
2. Toggle magit buffer to `text-mode` with `C-t`

If you set `evil-magit-want-horizontal-movement` to `t`, you'll get horizontal movement using `h/l`. It moves other bindings accordingly - `h` to `H`, `l` to `L`, and `L` to `C-l`.

Other option is to toggle the magit buffer temporarily to `text-mode` using `C-t` which allows normal movement, copying etc. 

Check [`evil-magit`](https://github.com/justbur/evil-magit) for more information on this.

**Comment by TheBB** [comment]
@ninrod Considering your enthusiastic response, does this answer your question?

**Comment by ninrod** [comment]
Oh yes, `C-t` nailed it.
