### ISSUE TITLE
Magit Feature Request `magit-list-repositories`

### ISSUE THREAD

**Issue by rphillips** [syl20bnr/spacemacs#7083]
I think it would be nice to have `<space>gL` binding for `magit-list-repositories`. It's trivial to add the binding, but where I got hung up is the buffer only responds to `emacs` mode bindings (ctrl-z then a return will open the status buffer). I'm not sure how to fix it.

In my `dotspacemacs/user-config()` I configured the feature with:

``` lisp
  (setq magit-repository-directories 
      '( "~/Development" ))
```

**Comment by TheBB** [comment]
Please look up evilification to fix the bindings issue.

**Comment by rphillips** [comment]
Thanks. I added a PR

**Comment by arronmabrey** [comment]
@rphillips do you have a link to the PR?

**Comment by d12frosted** [comment]
@arronmabrey GitHub automatically adds references. But here is PR: https://github.com/syl20bnr/spacemacs/pull/7096 .
