### ISSUE TITLE
org kills babel that was working with only org-plus-contrib

### ISSUE THREAD

**Issue by paynito** [syl20bnr/spacemacs#7087]
#### Description
No org-babel-execute function for python!
I had working org-babel with C-c. 
I wanted org-mime-htmlize that lives in org.

#### Reproduction guide
- Start Emacs
- user config:
(org-babel-do-load-languages
   'org-babel-load-languages
   '(
     (R . t)  ;; disable R to fix error
     (emacs-lisp . t)
     (sh . t)
     ;;  (C . t) ;; I'm not coding C right now 
     (python . t)))
-  dotspacemacs-configuration-layers
   '(
     ;;org
     org-plus-contrib
- babel works
- enable org
- restart
- send html-mime message with org-mime-htmlize
-attempt to execute org-babel 
#+BEGIN_SRC python
print("hello")
#+END_SRC

*Observed behaviour:*
receive error: No org-babel-execute function for python!

*Expected behaviour:*
output of function in org-mode.

#### System Info
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(org-plus-contrib lua emacs-lisp git bbdb bbdb-handy ess mu4e osx dash eyebrowse pandoc highlight github markdown auto-completion notmuch)
```

#### Backtrace
```
BACKTRACE IF RELEVANT
```

**Comment by TheBB** [comment]
There isn't a layer called org-plus-contrib. Only org.

**Comment by cpaulik** [comment]
I think this is related to https://github.com/syl20bnr/spacemacs/issues/4618 . When ob-R can not load then also the other babel languages are not working.

**Comment by TheBB** [comment]
Good point. I'm closing this as duplicate, please continue discussion in there. (It has a workaround, actually.)
