### ISSUE TITLE
[question] What is the correct/idiomatic way to use org-babel in the init file

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7091]
So I have completely *org-babelified* my [`~/.spacemacs/init.el`](https://github.com/ninrod/dotfiles/blob/master/dot/spacemacs.d/init.el). It looks exactly like this:

```lisp
(defun dotspacemacs/layers () (org-babel-load-file (expand-file-name "~/.spacemacs.d/layers.org")))
(defun dotspacemacs/init () (org-babel-load-file (expand-file-name "~/.spacemacs.d/settings.org")))
(defun dotspacemacs/user-init ())
(defun dotspacemacs/user-config () (org-babel-load-file (expand-file-name "~/.spacemacs.d/userconfig.org")))
```

Spacemacs loads up ok, and it is all fun and games, but I am starting to get the feeling that it was not a very good idea: I suspect that my usage of org so early in the load phase has done some damage to my overall org installation. 

For example, if I invoke `,'` inside a code block in an org file, I get this error message:

```txt
org-element--parse-to: Symbol’s value as variable is void: org-planning-line-re
```

So, is it my fault? How am I suppose to integrate the org-babel strategy into my `~/.spacemacs/init.el`?

thanks in advance.

**Comment by nixmaniack** [comment]
Since you're trying to use `org` functionalities before the _right_ version of `org-mode` is properly initialised, it looks like version mismatch issue. 

Can you check what `M-x` `org-version` is loaded?

**Comment by TheBB** [comment]
It's impossible to do this because you need to load org before Spacemacs has finished initializing. You'll get the wrong org version. Please see the FAQ entry on this.

**Comment by TheBB** [comment]
See https://github.com/syl20bnr/spacemacs/issues/3262 https://github.com/syl20bnr/spacemacs/issues/4793 https://github.com/syl20bnr/spacemacs/issues/2967

**Comment by ninrod** [comment]
Yes, is version 8.2.10. 

What should be the correct version? I'll revert to the standard way, anyway, just curious.

**Comment by nixmaniack** [comment]
I get `8.3.5` which is sourced from elpa package `org-plus-contrib`. 

But as TheBB explained, it'd be impossible to do this in current spacemacs architecture so you better revert to standard way.

**Comment by ninrod** [comment]
Ok, will do. It's a bummer though. initializing emacs through org-babel is very instructive and keeps things clean and organized.
