### ISSUE TITLE
org-wunderlist not working

### ISSUE THREAD

**Issue by abhi18av** [syl20bnr/spacemacs#7095]
#### Description

I want to use the following package with emacs [org-wunderlist](https://github.com/myuhe/org-wunderlist.el).

But instead, there are errors upon executing ```org-wunderlist-fetch```

#### Reproduction guide
- Start Emacs

*Observed behaviour:*

Nothing really happens, the backtrace is listed below.

*Expected behaviour:*

The buffer is populated with the tasks in the wunderlist cloud.

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp clojure git markdown org haskell html lua php ruby d go rust c-c   javascript latex python racket scheme sql vimscript common-lisp django react xkcd emoji ruby-on-rails chrome finance search-engine speed-reading eyebrowse dash fasd pandoc ansible dockerfile chinese theming restclient prodigy gtags deft colors
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking version-control)
```

#### Backtrace
```
REQUEST [error] Error (error) while connecting to https://a.wunderlist.com/api/v1/list_positions.
REQUEST [error] Error (error) while connecting to https://a.wunderlist.com/api/v1/lists.
REQUEST [error] Error (error) while connecting to https://a.wunderlist.com/api/v1/root.
deferred error : (wrong-type-argument numberp nil)

```

**Comment by TheBB** [comment]
We can't really help you with external packages unless you have tried them without Spacemacs and confirm that it's Spacemacs that is the problem.

**Comment by abhi18av** [comment]
Yes, I can assure you that it works in the vanilla emacs conf. So, any suggestions/ or guidance here would be much appreciated.

Btw, does spacemacs packages have a certain priority list in the order of loading packages and their unique configuration files f.ex. like org-wunderlist needs the KEY and ID to be loaded from a different file?

**Comment by d12frosted** [comment]
https://github.com/myuhe/org-wunderlist.el/issues/5 could be related. Also it would be helpful to share more details on how you installed that package and how you configured it.

**Comment by abhi18av** [comment]
Yup, @d12frosted that did it!

Thanks for the wonderful support, @d12frosted and @TheBB - people like you make me love coding all the more. Appreciate it 👍
