### ISSUE TITLE
How to configure spaceline to truncate mode-line instead of wrapping it?

### ISSUE THREAD

**Issue by kangjianbin** [syl20bnr/spacemacs#7099]
Hi All,

I'm running emacs in terminal mode.
When the text in mode-line is too long, spaceline will warp it into each area.
Is it able to configure spaceline to truncate it?

<img width="576" alt="1" src="https://cloud.githubusercontent.com/assets/121803/18443925/a6a00a22-7949-11e6-8fed-59226572b995.png">

Thanks.

**Comment by d12frosted** [comment]
Wow. Never seen such behaviour. It always truncates for me.

**Comment by syl20bnr** [comment]
I would actually like to have a "wrappeable" mode line! :-D

Like @d12frosted I have never seen this, can you provide us with information returned with `SPC h d s` key binding ?

**Comment by kangjianbin** [comment]
The output is:

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: develop (rev. e51a89a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(org html javascript python markdown c-c++ auto-completion go git better-defaults csharp ivy syntax-checking emacs-lisp)
```

I saw it happened many times. However I can't reproduce today :-（
May it be problem of terminal? I am using mintty. Seems that putty has the same problem.

**Comment by TheBB** [comment]
Looks like it has problems rendering your separators, you're getting some other characters that look like double width. There are probably many contributing factors here (terminal, font) but the easiest fix may be to set `dotspacemacs-mode-line-unicode-symbols` to `nil`.

**Comment by kangjianbin** [comment]
Thanks, @TheBB , that may be the problem.
Is that some way to bind dotspacemacs-mode-line-unicode-symbols to frame, instead of global?
For example, emacs is running in daemon mode. I want emacsclient that running in X sets this variable to t and emacsclient running in terminal sets it to nil.

**Comment by TheBB** [comment]
Not at the moment.

**Comment by kangjianbin** [comment]
I found that _dotspacemacs-mode-line-unicode-symbols_ was set to nil. However _powerline-default-separator_ was set to 'utf-8 in terminal mode.
My _dotspacemacs-mode-line-unicode-symbols_ was set to: _(display-graphic-p)_.
So if I start _emacs --daemon_ in X, everything works fine since _powerline-default-separator_ is set to wave and doesn't take effect in terminal.
But if I start _emacs --daemon_ in terminal, I get this error.
Is there some font that supports 0xe0b0? Or some other unicode that can be used as seperator?

**Comment by kangjianbin** [comment]
After switching to a font contains 0xe0b0 and 0xe0b2, this probelm didn't happpened.
