### ISSUE TITLE
Unable to set custom yasnippet directory

### ISSUE THREAD

**Issue by herbert-jones-mediafire** [syl20bnr/spacemacs#710]
If I recall correctly, at one point in the past I could set ```yas-snippet-dirs``` inside of ```dotspacemacs/config``` and it would work.  Later changes required me to instead place it inside an ```after-init-hook```.  However now neither way works.  It appears that ```yas-snippet-dirs``` gets overwritten with default values any time any buffer that doesn't have yasnippet mode already actived for it is created.

**Comment by cpaulik** [comment]
I don't know about setting a custom directory but there is a directory for custom snippets in the private folder that works for me ```https://github.com/syl20bnr/spacemacs/tree/master/private/snippets```

**Comment by herbertjones** [comment]
@cpaulik I have my own snippets layer I share across my computers.  I'm not sure how easy it would be to add that directory to my personal layers repo.  A fix is always nicer too than a workaround.

https://gist.github.com/herbertjones/fb612256ef1f50bdc231

**Comment by cpaulik** [comment]
Great if we can set this explicitly in the future. In the past I just symbol linked it in my [dotfiles install script](https://github.com/cpaulik/dotfiles/blob/master/install_script#L26).

**Comment by syl20bnr** [comment]
Fixed with #713
