### ISSUE TITLE
Spacemacs home window always opens behind new frames. How to prevent it?

### ISSUE THREAD

**Issue by domi91c** [syl20bnr/spacemacs#7100]
When I open a text file in OSX it opens in the Emacs GUI, which is what I want. But the main Spacemacs window always opens behind it. How can I prevent this from happening? This makes it so that when I'm done with a file, I have to close it's frame _and_ the Spacemacs home window. How can I prevent both frames from opening when I open a file?

**Comment by duianto** [comment]
It would be helpful if you provided more information, here's a guide: https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report

Only a single frame opens with this system:
#### System Info :computer:
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 6bb4416)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp git)
```

**Comment by TheBB** [comment]
Closing in favor of https://github.com/syl20bnr/spacemacs/issues/6023
