### ISSUE TITLE
freeze all the time

### ISSUE THREAD

**Issue by yunfan** [syl20bnr/spacemacs#7102]
i am vim user, and  i am now trying to use emacs, then i found this project
i like its concepts, and agree with it
so i have download and try it

its almost what i need, the only problem is i happened to met freeze at startup

first, i met the adobe-source-pro font problem, after some googling, found solution, problem solved.
and then i met another problem which caused the freeze at startup too, only this time, none tips showed

i am still have passion with this project and willing to wait for solving the problem and try again and again

i only hope you could try you best to avoid such problem like this which prevent people to trying
if a options not work, its ok i could go on. but if the whole emacs freeze, i cant do anything. 

(sorry for my poor english )

**Comment by NJBS** [comment]
Have you tried the entry in our FAQ?

http://develop.spacemacs.org/doc/FAQ.html#why-is-spacemacs-hanging-on-startup

**Comment by geekplux** [comment]
If you based in China, I guess you fucked by GFW...
Try to change the ELPA mirror to this: http://elpa.emacs-china.org/

**Comment by yunfan** [comment]
@geekplux maybe, but i have a proxy entry, so that's not a problem, also that problem solved 
but the following freeze gaves no tips.

@NJBS yes solved that
