### ISSUE TITLE
[question] how do I tell spacemacs to look for a local elpa mirror?

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7103]
for example, say that I git cloned this repo: https://github.com/syl20bnr/spacemacs-elpa-mirror

And I want to use that as my elpa mirror. How do I say to spacemacs to stop trying to connect to melpa/elpa whatever, and fetch the packages in my local git cloned folder instead?

That would be super useful for me because I'm behind a corporate firewall that prevents emacs from fetching elpa packages, but allows github access.

**Comment by d12frosted** [comment]
AFAIK, you can't just change the value of `package-archives` as it will be change by Spacemacs in `configuration-layer/initialize`. But you can set desired archives by changing the value of `configuration-layer--elpa-archives`. For example, put following in `dotspacemacs/init`.

```
(setq configuration-layer--elpa-archives
      '(("melpa" . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/melpa/")
        ("org"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/org/")
        ("gnu"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/gnu/")))
```

The only problem - currently `configuration-layer//resolve-package-archives` doesn't respect URLs starting with `file://`, so if you wish to use other than http[s] protocol, you need to modify that function.

**Comment by d12frosted** [comment]
Ok, just pushed https://github.com/syl20bnr/spacemacs/commit/8578b40404827bfa1cc12353d8ee4fb1747bbd19. It allows you to use local archive. For example, put following in your `dotspacemacs/init` function (just don't forget to update path).

```
(setq configuration-layer--elpa-archives
        '(("melpa" . "/Users/d12frosted/Developer/d12frosted/elpa-mirror/melpa")
          ("org"   . "/Users/d12frosted/Developer/d12frosted/elpa-mirror/org/")
          ("gnu"   . "/Users/d12frosted/Developer/d12frosted/elpa-mirror/gnu/")))
```

**Comment by ninrod** [comment]
Ok, will try that ASAP.

**Comment by ninrod** [comment]
@d12frosted, where exactly am I supposed to place the above lisp block in my `~/.spacemacs.d/init.el`? 

putting that in  dotspacemacs/user-init did not work.

**Comment by ninrod** [comment]
oh, i used "~/apps/elpa-mirror" as the path. does "~" expands to /home/ninrod? maybe that's why it is not working.

**Comment by ninrod** [comment]
nope. it is indeed an error: emacs with --debug-init gives me:  "Cannot open load file" "No such file or directory" "elpa-mirror")

**Comment by ninrod** [comment]
I think the error happens because strangely some function is looking for https://github.com/redguardtoo/elpa-mirror

**Comment by ninrod** [comment]
maybe I need to do something like this first? 

```lisp
(add-to-list 'load-path "~/.emacs.d/site-lisp/elpa-mirror")
(require 'elpa-mirror)
```

**Comment by ninrod** [comment]
Strange. It errors out on me saying that it cannot find spacemacs-theme- package.

**Comment by d12frosted** [comment]
Oh welp, never really tried using local archive. It works with remote archive, but when I try to bootstrap using local archive I experience pretty similar problem. Gonna investigate that. 😸 

Funky, over the internet I see people using local archives, so it might be something wrong in our setup. I thought that the only change required is the url resolver function. But seems that it's not enough 💃 

I'll keep you updated. 😈

**Comment by d12frosted** [comment]
@ninrod Oh I just realised why it doesn't work. It turns out that `configuration-layer/retrieve-package-archives` doesn't work with `/path/to/mirror` URLs. As a (temporary) workaround you can redefine `configuration-layer/retrieve-package-archives` to following function. Meanwhile I am gonna make sure that local urls work with https://github.com/syl20bnr/spacemacs/pull/6828. 

```
(defun configuration-layer/retrieve-package-archives (&optional quiet force)
  "Retrieve all archives declared in current `package-archives'.

This function first performs a simple GET request with a timeout in order to
fix very long refresh time when an archive is not reachable.

Note that this simple GET is a heuristic to determine the availability
likelihood of an archive, so it can gives false positive if the archive
page is served but the archive is not.

If QUIET is non nil then the function does not print message in the Spacemacs
home buffer.

If FORCE is non nil then refresh the archives even if they have been already
refreshed during the current session."
  (unless (and configuration-layer--package-archives-refreshed
               (not force))
    (setq configuration-layer--package-archives-refreshed t)
    (let ((count (length package-archives))
          (i 1))
      (dolist (archive package-archives)
        (unless quiet
          (spacemacs-buffer/replace-last-line
           (format "--> refreshing package archive: %s... [%s/%s]"
                   (car archive) i count) t))
        (spacemacs//redisplay)
        (setq i (1+ i))
        (unless (eq 'error
                    (with-timeout
                        (dotspacemacs-elpa-timeout
                         (progn
                           (display-warning
                            'spacemacs
                            (format
                             "\nError connection time out for %s repository!"
                             (car archive)) :warning)
                           'error))
                      (condition-case err
                          (unless (string-prefix-p "/" (cdr archive))
                            (url-retrieve-synchronously (cdr archive)))
                        ('error
                         (display-warning 'spacemacs
                          (format
                           "\nError while contacting %s repository!"
                           (car archive)) :warning)
                         'error))))
          (let ((package-archives (list archive)))
            (package-refresh-contents))))
      (package-read-all-archive-contents)
      (unless quiet (spacemacs-buffer/append "\n")))))
```

**Comment by ninrod** [comment]
nice workd @d12frosted! I will try that ASAP.

**Comment by d12frosted** [comment]
Also keep in mind that not all packages configured in Spacemacs are installed from MELPA, GNU ELPA or Org package archive. Some of them are installed from GitHub. Not many of them, but still.

**Comment by PrgrmAtCeleritas** [comment]
@d12frosted Is there a way to make this hack work with relative paths from home directory  (i.e. ~/some/elpa/location/) as opposed to absolute paths (/path/from/root/to/elpa/location/) as it is setup now?

**Comment by ninrod** [comment]
@PrgrmAtCeleritas, I don't know exactly what spacemacs is doing differently, but I'm rolling my own config and this [snippet](https://github.com/ninrod/dotfiles/blob/ae35834941fd793dfbddd465fe0e92b051b0b87f/emacs/init.el#L13-L15) is working beautifully for me, using @d12frosted elpa-mirror repo:

```emacs-lisp
(require 'package)
(setq package-enable-at-startup nil)
(setq package-archives '(("melpa" . "~/.emacs.d/mirror-elpa/melpa/")
                         ("org"   . "~/.emacs.d/mirror-elpa/org/")
                         ("gnu"   . "~/.emacs.d/mirror-elpa/gnu/")))
```

**Comment by PrgrmAtCeleritas** [comment]
@ninrod I tried something similar in the "Spacemacs" flavor but it won't work unless I give it the absolute path. Maybe I can bypass the the Spacemacs sugar and set it up like you did since it is not a problem with Emacs apparently.

**Comment by ninrod** [comment]
@PrgrmAtCeleritas, Are you using #6828? @d12frosted implemented quite a few hacks in that to make it work properly in spacemacs.

**Comment by PrgrmAtCeleritas** [comment]
I am not. I am using the code snippet provided above. [#6828](https://github.com/syl20bnr/spacemacs/pull/6828) seemed to deal with Melpa being down but I could give it a shot.

**Comment by d12frosted** [comment]
Oh sorry, missed this issue.

@ninrod thanks for answers 😸 

@PrgrmAtCeleritas in order to use this 'trick' in Spacemacs you have to add following snipped to your `dotspacemacs/user-init` function.

```elisp
  (setq configuration-layer--elpa-archives
        '(;; ("melpa" . "/Users/d12frosted/Developer/d12frosted/elpa-mirror/melpa/")
          ;; ("org"   . "/Users/d12frosted/Developer/d12frosted/elpa-mirror/org/")
          ;; ("gnu"   . "/Users/d12frosted/Developer/d12frosted/elpa-mirror/gnu/")
          ("melpa" . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/melpa/")
          ("org"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/org/")
          ("gnu"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/gnu/")))
```

This is exactly [what I use][1] (mostly for testing purposes or when I need to quickly reinstall all packages).

P. S. Note that using `configuration-layer--elpa-archives` is a hack rather than documented feature. If at one point it stops working - you have to find another way 😸 

  [1]: https://github.com/d12frosted/environment/blob/master/emacs/spacemacs.el#L103

**Comment by d12frosted** [comment]
Ah, almost forgot, #6828 allows usage of local archive (like `/Users/d12frosted/Developer/d12frosted/elpa-mirror/melpa/`).

**Comment by ninrod** [comment]
@PrgrmAtCeleritas, you could set up absolute path symlinks in all your machines that point to the correct location. 

for example, in machine A: 

```sh
/opt/emacs/melpa-dir -> path/to/melpa/dir-in-machine-A
/opt/emacs/elpa-dir -> path/to/elpa/dir-in-machine-A
...
so on and so forth
```

**Comment by PrgrmAtCeleritas** [comment]
I don't have admin privileges. So I can only write to NFS directories, which are different for each machine. So the only consistent thing across all machines is `~` points to the home directory for that particular machine.

**Comment by ninrod** [comment]
Ouch. that sucks.

**Comment by d12frosted** [comment]
@PrgrmAtCeleritas try following snippet:

```
(setq configuration-layer--elpa-archives
             `(("melpa"        . ,(expand-file-name "~/Developer/d12frosted/elpa-mirror/melpa"))
               ("org"          . ,(expand-file-name "~/Developer/d12frosted/elpa-mirror/org"))
               ("gnu"          . ,(expand-file-name "~/Developer/d12frosted/elpa-mirror/gnu"))))
```

**Comment by ninrod** [comment]
I get lost with all those backquotes and commas. I don't really know what that means. I've just got used to single quotes `'`.

**Comment by d12frosted** [comment]
@ninrod 😸 

Might be useful to read about [Quoting][1] and [Backquote][2]. In short - backquote allows to evaluate some code in a quoted expression. And `,` indicates what to evaluate. 

  [1]: https://www.gnu.org/software/emacs/manual/html_node/elisp/Quoting.html#Quoting
  [2]: https://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html#Backquote

**Comment by PrgrmAtCeleritas** [comment]
That worked @d12frosted. Thank you!

**Comment by d12frosted** [comment]
@ninrod @PrgrmAtCeleritas also you can avoid using backquotes and duplicating `expand-file-name` by using following snippet.

```elisp
(setq configuration-layer--elpa-archives
      (mapcar
       (lambda (pair)
         (cons (car pair)
               (expand-file-name (cdr pair))))
       '(("melpa" . "~/personal/emacs/elpa-mirror/spacemacs-elpa-mirror-latest/melpa/")
         ("org"   . "~/personal/emacs/elpa-mirror/spacemacs-elpa-mirror-latest/org/")
         ("gnu"   . "~/personal/emacs/elpa-mirror/spacemacs-elpa-mirror-latest/gnu/"))))
```

**Comment by ninrod** [comment]
@d12frosted thanks. what was your path to learn elisp? did you read the reference manual?

**Comment by d12frosted** [comment]
Well, to be honest I didn't read it all. Only some parts that I was interested in. I am planning to read it at some point 😸 I began to learn Emacs Lisp when started to make my own configs for the first time. But it was more copy-paste than actual coding. When I started to use and contribute to Spacemacs I really started to 'learn by practice'. Sylvain, Eivind and bmag are the guys who explained me several tricks and topics 😸 So my way is practice + theoretical parts from reference manual.

**Comment by ninrod** [comment]
@d12frosted nice. You learn a lot from open source. 

Now just one minor question. What is the meaning of that `.` dot like in here:

```elisp
("gnu"   . "~/personal/emacs/elpa-mirror/spacemacs-elpa-mirror-latest/gnu/")
```

Why can't I just write

```elisp
'("gnu"  "~/personal/emacs/elpa-mirror/spacemacs-elpa-mirror-latest/gnu/")
```

which is a list of 2 strings?

**Comment by d12frosted** [comment]
@ninrod Checkout [documentation][1] about dotted pair notation.

As example:

```elisp
ELISP> (cdr '(1 . 2))
2 (#o2, #x2, ?\C-b)
ELISP> (cdr '(1 2))
(2)
```

As you can see, without dot, `cdr` is list, but usage of `configuration-layer--elpa-archives` requires it to be a string instead of list. 

  [1]: https://www.gnu.org/software/emacs/manual/html_node/elisp/Dotted-Pair-Notation.html

**Comment by ninrod** [comment]
@d12frosted thanks I'll have to read the manual. Good stuff and seems well written.

**Comment by mfehlhaber** [comment]
I am using the following to my full contentment with spacemacs 0.200.9 and thus suggesting to close this issue.

```
(defun dotspacemacs/init ()
  (setq configuration-layer--elpa-archives
        '(("melpa" . "~/.emacs.d/elpa-mirror/")
          ("org"   . "~/.emacs.d/elpa-mirror/")
          ("gnu"   . "~/.emacs.d/elpa-mirror/")))
...
)
```

**Comment by ninrod** [comment]
Hum. was #6828 merged?

**Comment by bhipple** [comment]
It looks like it hasn't been merged yet, and this doesn't work in develop without those commits, as far as I can tell.  This would be a really nice feature to have; I'm running into a lot of issues where my plugin versions are slightly different between my various computers and I see slightly different behavior, and I'd like to be able to pin everything to a distribution I control.

**Comment by CeleritasCelery** [comment]
You can add packages to the `dotspacemacs-frozen-packages` to keep certain packages from being automatically updated. You can also change the code yourself to enable this feature.

**Comment by ninrod** [comment]
I don't see why this can't be merged in. @d12frosted do you know the status on this? 

I'm using this for 1 year in my own config and it has been fantastic, super stable and fast.

**Comment by CeleritasCelery** [comment]
I have been using it too

**Comment by d12frosted** [comment]
@nickanderson unfortunately, no I don't know.

But using local mirror works on develop. At least, I am using it without any 'special' commits to Spacemacs.

I just have following line inside of `dotspacemacs/init` function of [.spacemacs file](https://github.com/d12frosted/environment/blob/master/emacs/spacemacs/spacemacs.el#L42)

```emacs-lisp
  (setq configuration-layer--elpa-archives
        `(("melpa" . ,(concat d12-path-elpa-mirror-home "melpa/"))
          ("org"   . ,(concat d12-path-elpa-mirror-home "org/"))
          ("gnu"   . ,(concat d12-path-elpa-mirror-home "gnu/"))
          ("melpa" . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/melpa/")
          ("org"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/org/")
          ("gnu"   . "https://raw.githubusercontent.com/d12frosted/elpa-mirror/master/gnu/")))
```

In case it doesn't work for you, let me know and I'll look into it.

**Comment by d12frosted** [comment]
@CeleritasCelery my previous comment is addressed to you as well 😸

**Comment by cppddz** [comment]
in windows ,you can set like this

> (defun dotspacemacs/init ()
> (setq configuration-layer--elpa-archives
>     '(("melpa-cn" . "//?/f:/elpa-mirror/melpa/")
>       ("org-cn"   . "//?/f:/elpa-mirror/org/")
>       ("gnu-cn"   . "//?/f:/elpa-mirror/gnu/")))
> ...
> )

windows path in emacs use like this:

> long UNC or UNCW, such as \?\C:\File or \?\UNC\Server\Volume\File

**Comment by AleXoundOS** [comment]
@d12frosted, it's probably better to put this in `dotspacemacs/user-init`, because `dotspacemacs/init` is not recommended for adding new options as I understood. Works for me.

**Comment by d12frosted** [comment]
Closing this issue as the initial question was answered and it's possible to use local ELPA archive for a long time already 😸 Let me know if you disagree with this action of treason!

**Comment by LoganBarnett** [comment]
I had trouble getting the examples here to work, but it looks like the `configuration-layer--elpa-archives` has been renamed to `configuration-layer-elpa-archives`. Using that name instead makes everything seem to work for me.
