### ISSUE TITLE
Ag with ivy enabled

### ISSUE THREAD

**Issue by aspett** [syl20bnr/spacemacs#7106]
I have recently enabled ivy on my installation of spacemacs due to helm being too slow for the size of project I'm working on. When using ag functions such as `SPC s a p`, I'm having an issue with search strings containing a space. 

For instance, if I typed: `SPC s a p hello world` then the results would match something resembling the regex of `hello.*world`. In helm, I could get around this by instead searching for `hello\ world`. This causes an error with ivy; "error code 2".

Is there a different way to search for strings containing spaces, or is this a bug?

**Comment by nixmaniack** [comment]
Can you try inputting two spaces to match single one? 

This comes from [`swiper`](http://oremacs.com/swiper/#ivy--regex-plus) docs but should work here.

**Comment by aspett** [comment]
That's perfect, and has solved the issue. Thanks!
