### ISSUE TITLE
After using `gd` to jump to definition, `C-o` doesn't go back correctly

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#7108]
#### Description :octocat:
After using `gd` to jump to definition, `C-o` doesn't go back correctly

#### Reproduction guide :beetle:
- Start Emacs
- `SPC f e i`
- Goto function call `(spacemacs/init)` and hit `gd` (`spacemacs/evil-smart-goto-definition`) to goto definition
- Hit `C-o` (`evil-jump-backward`) to go back

*Observed behaviour:* :eyes: :broken_heart:
Doesn't go back to from where it was invoked.

*Expected behaviour:* :heart: :smile:
Go back to right place from where the jump call was made.

https://github.com/syl20bnr/spacemacs/pull/6771 has fixed the issue but looks
like that fix is removed with new refactoring. 

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 6bb4416)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy restclient
     (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip nil auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" :disabled-for org erc)
     semantic better-defaults emacs-lisp
     (git :variables git-gutter-use-fringe t git-magit-status-fullscreen nil)
     github markdown yaml shell
     (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t enable-flyspell-auto-completion nil)
     syntax-checking twitter
     (elfeed :variables rmh-elfeed-org-files
             (list "~/.emacs.d/private/elfeed.org"))
     lua
     (python :variables python-enable-yapf-format-on-save t python-test-runner
             '(nose pytest))
     ruby ruby-on-rails sml
     (clojure :variables clojure-enable-fancify-symbols t)
     go
     (gtags :disabled-for python)
     shell-scripts html javascript docker spacemacs-layouts window-purpose
     (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp/mu/mu4e/" mu4e-enable-mode-line t mu4e-enable-notifications t)
     nix-mu4e colors deft finance
     (ibuffer :variables ibuffer-group-buffers-by 'projects)
     imenu-list
     (version-control :variables version-control-diff-tool 'diff-hl)
     ansible emoji ranger prodigy osx typography
     (theming :variables theming-headings-inherit-from-default 'all theming-headings-same-size 'all theming-headings-bold 'all)
     org
     (plantuml :variables org-plantuml-jar-path
               (expand-file-name "~/bin/plantuml.jar")
               puml-plantuml-jar-path
               (expand-file-name "~/bin/plantuml.jar"))
     command-log erc pdf-tools bh-org-mode
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
     search-engine)
```

#### Backtrace :paw_prints:
```

```

**Comment by nixmaniack** [comment]
`,gg` is different than `gd`. Should they be bound to same function call (`spacemacs/jump-to-definition`)?

**Comment by TheBB** [comment]
Yes, once `evil-goto-definition` is added to the jumper list they are effectively identical.

**Comment by TheBB** [comment]
Although actually I just did exactly what you proposed and I can jump back like a champ. Tried this with and without gtags, too.

**Comment by TheBB** [comment]
Should work now?

**Comment by nixmaniack** [comment]
Thanks @TheBB . Works with latest changes on `develop`.
