### ISSUE TITLE
ability to display selection info in the modeline

### ISSUE THREAD

**Issue by emmanueltouzery** [syl20bnr/spacemacs#711]
I noticed bug #624 and #524 so potentially close this as a duplicate.

I don't know the timeline before you implement #524... I have locally patched my spacemacs to enable me to display after row/column info also info about the selection as http://www.emacswiki.org/emacs/modeline-posn.el does for raw emacs.

      (defun column-number-at-pos (pos)
        "Analog to line-number-at-pos."
        (save-excursion (goto-char pos) (current-column)))

      (defun selection-info ()
        (if (use-region-p)
            ;; could also include the total columns in the selection (even multiline):
            ;; (abs (- (column-number-at-pos (region-end)) (column-number-at-pos (region-beginning)))))
            (let* ((lines (count-lines (region-beginning) (region-end)))
                   (chars (- (region-end) (region-beginning))))
            (number-to-string (if (> lines 1) lines chars)))
          "-"
        ))

----

then after the row:column block (currently line 2002 in .emacs.d/spacemacs/packages.el):

           (list
            ;; selection info
            (powerline-raw " " face1)
            (powerline-raw (selection-info) face1)
            (funcall separator-left face1 line-face)
            (powerline-raw " " line-face))

So if #524 is far away maybe something like that could be possible as a stopgap, or if it's not that far I guess you can close this issue as duplicate.

**Comment by syl20bnr** [comment]
The powerline DSL is not high on my priority list.
You can PR your segment but I would prefer it to auto-hide if there is no selection.
