### ISSUE TITLE
Home buffer rerenders when opening helm

### ISSUE THREAD

**Issue by mahinshaw** [syl20bnr/spacemacs#7116]
#### Description :octocat:
Home buffer rerenders when opening helm

#### Reproduction guide :beetle:
- Start Emacs
- On the Home huffer, initialize a helm buffer.
- This seems to be related to commit fd9ac4a

*Observed behaviour:* :eyes: :broken_heart:
- Watch the ui jump around while it tries to resize.

*Expected behaviour:* :heart: :smile:
- No jumping ui.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. f373105)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm spacemacs-layouts
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
      colors evil-commentary evil-cleverparens fasd
      (git :variables git-magit-status-fullscreen t)
      github nginx org restclient
      (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-term)
      (spell-checking :variables spell-checking-enable-by-default nil)
      syntax-checking version-control vinegar clojure emacs-lisp erlang html markdown rust yaml)
```

**Comment by deb0ch** [comment]
I don't see any different behaviour between before and after fd9ac4a on my end.

What do you mean exactly by "UI jumps" ?

**Comment by mahinshaw** [comment]
If you open helm (I'm guessing ivy will cause this as well, but I don't use it), the text jumps on the screen.  When I say UI, I am more speaking to the UI components, as it is not only text that jumps. This only happens on the home buffer, which is why I am pointing to the aforementioned commit.  Furthermore, if I roll back to the prior commit, the "jumpy" behavior is not present.

**Comment by TheBB** [comment]
Does the PR fix it?

**Comment by mahinshaw** [comment]
@TheBB Yes. It does.

**Comment by TheBB** [comment]
Cool, thanks. :+1:

**Comment by mahinshaw** [comment]
And Thank You for all the work you do on Spacemacs!

**Comment by TheBB** [comment]
Then this is fixed.
