### ISSUE TITLE
org-mode broken?symbol's value as variable is void: org-planning-line-re

### ISSUE THREAD

**Issue by qx** [syl20bnr/spacemacs#7120]
#### Description :octocat:
export html from org mode get error,and some keybinding not worked for org-mod eg, M-RET

I've cleaned mine .emacs.d folder with `git clean -xdf` then pull the latest dev branch

#### Reproduction guide :beetle:
- Start Emacs
- open org file,
- C-c C-e h o 
- get " byte-code: Symbol's value as variable is void: org-planning-line-re""

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. e02c012)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
((spacemacs-layouts :variables spacemacs-layouts-directory "~/.spacemacs.d/layouts/")
 (colors :variables colors-enable-nyan-cat-progress-bar t colors-enable-rainbow-identifiers t)
 osx dash smex yaml javascript chinese oyqx html
 (ruby :variables ruby-version-manager 'rbevn ruby-test-runner 'rspec)
 ruby-on-rails ivy
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence-delay 0.5)
 better-defaults emacs-lisp git markdown org syntax-checking)
```

#### Backtrace :paw_prints:
```
byte-code: Symbol's value as variable is void: org-planning-line-re
(No files need saving)
org-element-headline-parser: Symbol's value as variable is void: org-planning-line-re

```

**Comment by TheBB** [comment]
http://spacemacs.org/doc/FAQ.html#orgheadline13

95% of the time I see this error, the user has violated this by doing something with org before user-config. You will have some parts of old org loaded and some parts of new org, and they disagree particularly on this variable existing.

See for example https://github.com/syl20bnr/spacemacs/issues/7091 but there are plenty of issues about this error already.

**Comment by qx** [comment]
@TheBB  ,Follow your advise, the problem resolved.It's strange it works few days ago, it broken after I install highlight and update .emacs.d, so I'm not sure where is wrong .Thank's again,I should be more careful
