### ISSUE TITLE
[question] how does spacemacs keeps two separate evil-leader convoluted maps

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7121]
So I was skimming through spacemacs source code trying to find an answer to explain this sorcery, but to no avail. 

When I'm in org mode I know I have two convoluted key maps under evil-leader. One map is under the `<SPC>` leader key and the other map under the `,` key. The `<SPC>` key guards general binds and the `,`guards mode specific binds. Lovely. 

But how in hell does spacemacs managed to set that up? I'm curious because reading through evil-leader documentation, you have only one way to set the leader key and that is by writing: 

```lisp
(evil-leader/set-leader "<SPC>")
```

Yes, you can overwrite bits of that mapping according to the mode you are in by writing

```lisp
(evil-leader/set-key-for-mode 'emacs-lisp-mode "b" 'byte-compile-file)
```

but that also does not explain that evil sorcery.

Enlighten me, please. 

Thanks in advance.

**Comment by TheBB** [comment]
You can forget about the evil-leader documentation. We don't use it. Here: https://github.com/justbur/emacs-bind-map

Basically the trick is to use a hook that activates on every major mode change to locally bind the comma key to the submap of the main leader map bound to m.

**Comment by TheBB** [comment]
For the record, this worked with evil-leader too, bind-map is just a lot more smooth.

**Comment by ninrod** [comment]
Very interesting, but wait. If I understand correctly, with bind-map, you can forget about evil-leader. Is that right?

**Comment by TheBB** [comment]
bind-map covers all the necessary functionality we need from evil-leader yes.

**Comment by TheBB** [comment]
Does this answer your question?

**Comment by ninrod** [comment]
Yes! Thank you very much. If I may ask one last question, why then, in develop (GIT HEAD) evil-leader is still used?

**Comment by nixmaniack** [comment]
@ninrod It's `defalias`ed to `bind-map` - to keep old code working till all the migration is done.

**Comment by ninrod** [comment]
ok @nixmaniack!. Thank you both!
