### ISSUE TITLE
ipython with line indicator

### ISSUE THREAD

**Issue by Michaelizm** [syl20bnr/spacemacs#7122]
Hi there, I am just wondering if this is a normal case without line indicator in `ipython`, since I didn't find any post of ipython workflow pic online.

<img width="633" alt="screen shot 2016-09-15 at 16 05 23" src="https://cloud.githubusercontent.com/assets/10254172/18542694/b254c7f6-7b5e-11e6-8d8f-72672b950030.png">

Above image is invoked by `SPC m s i` from a 'just installed' env with one additional `python` layer.

Thanks.

**Comment by TheBB** [comment]
No, that's not normal, but I see you have ipython 5 so you might have better with develop (assuming this is not develop).

**Comment by TheBB** [comment]
Basically: try running with `--simple-prompt`

**Comment by Michaelizm** [comment]
Got it. Thanks for your prompt feedback, I will close this issue.
