### ISSUE TITLE
Helm evil scroll down / up

### ISSUE THREAD

**Issue by tobimensch** [syl20bnr/spacemacs#7123]
Hello,

at first when using helm I thought you couldn't use evil/vim navigation keys at all (since it would
conflict with entering search terms),
then I discovered that you can use ctrl+j and ctrl+k.

But apparently evil style page down with ctrl+d and ctrl+u doesn't work. So I have to use the page down/page up keys, and I don't really want to since I've come to expect consistent behaviour.

**Comment by TheBB** [comment]
```elisp
(define-key helm-map (kbd "C-d") 'helm-next-page)
(define-key helm-map (kbd "C-u") 'helm-previous-page)
```

**Comment by tobimensch** [comment]
Nice. Thank you! Don't you think this ought to be included in spacemacs's evil mode?

**Comment by tobimensch** [comment]
It's not working in all helm buffers correctly. For example in the M-x buffer Ctrl+u seems to be for something else (while ctrl+d works).
Meanwhile in helm-imenu your solution works.

**Comment by TheBB** [comment]
Yes of course, you have to unbind the existing keys that shadow these keys. That's one reason why I wouldn't want this default, to be honest. Another is that it's far more efficient to find what you want in helm by simply typing its name rather than scrolling up and down.

**Comment by tobimensch** [comment]
@TheBB:

Unless you don't know yet what exactly you're searching for and hence want to just scroll through a list of (functions in helm-imenu) or whatever else, to get a general overview or to find something you don't quite remember the name of anymore.

**Comment by sooheon** [comment]
If you use ivy over helm, there is a far more vimmy way to do this: https://github.com/abo-abo/hydra/wiki/hydra-ivy-replacement

This gives you `d/u/g/G` movement inside a hydra for ivy. The hydra is like an equivalent of the "normal" mode or state, so you don't need to Ctrl prefix keys like C-j C-u, which causes conflicts. You simply press C-o once in ivy, then single presses of u,d,G, etc will work. If you wish to type again to narrow your searches, you can just press `i` for insert.

**Comment by syl20bnr** [comment]
There is also a transient state for Helm on `C-SPC` or `M-SPC`.

**Comment by sixshotx** [comment]
Is it possible to rebind <escape> to helm transient state trigger in a helm buffer (e.g. helm-mini)?
