### ISSUE TITLE
dotspacemacs-command-key ";" is not working

### ISSUE THREAD

**Issue by Michaelizm** [syl20bnr/spacemacs#7126]
I'am working on develop branch, this entry is default to `dotspacemacs-command-key ":"`
see commands below:
>The command key used for Evil commands (ex-commands) and Emacs commands (M-x). By default the command key is `:`, so ex-commands are executed like in Vim with `:` and Emacs commands are executed with `<leader> :`

As I change it to `dotspacemacs-command-key ";"` for faster entering ex-command with `;` and helm with `SPC ;` without press the `shift`, but only the latter is working fine.

I tried `dotspacemacs-command-key ";"` on master branch and both way looks well. I raise an issue here for a mark and will keep finding the root cause.

**Comment by TheBB** [comment]
`dotspacemacs-command-key` was removed on the develop branch in favour of `dotspacemacs-emacs-command-key`. Please do read the changelog when switching branches.

**Comment by TheBB** [comment]
> - Key binding ~SPC :~ acting as M-x as been replaced by ~SPC SPC~.   If you want to revert to the old ~SPC :~ key binding set the new variable =dotspacemacs-emacs-command-key= to ":".
> - New variable =dotspacemacs-emacs-command-key= which replaces the variable =dotspacemacs-command-key=. This variable represents the key to press after the leader key to execute =M-x=. Default value is ~SPC~.
