### ISSUE TITLE
Helm-tramp is broken in OSX (?)

### ISSUE THREAD

**Issue by agzam** [syl20bnr/spacemacs#7127]
#### Description :octocat:
`spacemacs/sudo-edit` should allow to edit files in directories with restricted access

#### Reproduction guide :beetle:
- Start Emacs
- Try running `SPC f E` `(sudo-edit)` and navigate to a directory with restricted access, e.g. `/usr/lib/cron` 

*Observed behaviour:* :eyes: :broken_heart:
`file-access: Opening directory permission denied`

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 26df4a7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((org :variables org-enable-reveal-js-support t)
 (auto-completion :variables auto-completion-tab-key-behavior 'cycle)
 emacs-lisp javascript html markdown shell-scripts clojure lua react
 (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rvm)
 ruby-on-rails
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 syntax-checking spell-checking helm
 (shell :variables shell-enable-smart-eshell t shell-default-term-shell "/bin/zsh")
 (deft :variables deft-directory "~/Google Drive/deft" deft-auto-save-interval 60)
 fasd ibuffer osx chrome
 (semantic :disabled-for emacs-lisp)
 restclient emoji ranger search-engine imenu-list pdf-tools slack git
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t)
 (github :variables gist-view-gist t)
 agzam ag-dash synonyms)
```

**Comment by TheBB** [comment]
Use tramp instead. Way better. `SPC f f /sudo::` etc.

**Comment by TheBB** [comment]
Oh, and don't edit your crontab directly, use `crontab -e`. ;-)

**Comment by agzam** [comment]
For some reason when I do `SPC f f /sudo::` Emacs hangs badly. and nothing works. Must be OS X issue

**Comment by agzam** [comment]
Yeah it seems to be able to use sudo with tramp Emacs needs to be started in sudo mode

**Comment by agzam** [comment]
Now for some reason even `SPC f E` doesn't work. It would say Tramp: sending password and would hang Emacs

**Comment by TheBB** [comment]
> Yeah it seems to be able to use sudo with tramp Emacs needs to be started in sudo mode.

Definitely not the case, at least on Linux.

**Comment by agzam** [comment]
I just asked my colleague who uses straight Emacs "GUI" in OSX, same version, etc. The only difference is - I'm in Spacemacs. Tramping into sudo hangs for me. works for him :(

**Comment by agzam** [comment]
Others reporting that everything works just fine.. so this appears to be localized issue.

**Comment by agzam** [comment]
While trying to pin down the source of my sorrow I did following things: 

 - I rimrafed elpa and .cache and recompiled packages
 - I commented out all layers in .spacemacs file
 - I removed ~/.ssh/known_hosts file
 
Now everything seems to be working fine, (even after reverting .spacemacs changes) and I am not sure what caused this - my attempts to reproduce failed. I am happy that it works.

**Comment by chriskaukis** [comment]
I'm seeing the exact same issue. Happens every time, no matter what I do.

#### System Info
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle)
 better-defaults emacs-lisp git markdown org ruby go osx sql react c-c++ dockerfile spell-checking syntax-checking version-control emoji scheme ruby-on-rails semantic restclient java
 (shell :variables shell-default-shell 'eshell shell-default-position 'bottom shell-default-height 30))
```

Steps to replicate:

* Open Spacemacs 
* Open a file using sudo edit: `Space f E`
* Search for a file, example: `/etc/hosts`
* Freezes with `Tramp: Sending Password` in the status

**Comment by agzam** [comment]
@chriskaukis check ~/.ssh/known_hosts, try clearing it

**Comment by pawandubey** [comment]
This is related to a projectile bug, I think. See https://github.com/bbatsov/projectile/issues/523
