### ISSUE TITLE
How to install a package from Github which lacks a file header?

### ISSUE THREAD

**Issue by enzochiau** [syl20bnr/spacemacs#7128]
Try to install the org-wiki package from github as below:

```
(org-wiki :location (recipe
                     :fetcher github
                     :repo "caiorss/org-wiki"))
```

But I received this error:

```
Warning: (error "Package lacks a file header")
Error getting PACKAGE_DESC: (error Package lacks a file header)
```

How could I install this kind of package?

**Comment by d12frosted** [comment]
Take a look at [org-wiki.el](https://github.com/caiorss/org-wiki/blob/master/org-wiki.el) you are trying to install. Unfortunately, `quelpa` (or `package.el`) can not install packages without proper meta info. So it's an upstream issue you should report to that project.
