### ISSUE TITLE
U+2500 is double width in terminal.

### ISSUE THREAD

**Issue by kangjianbin** [syl20bnr/spacemacs#7130]
Hi experts,
Can I ask emacs related question here?
Spacemacs uses 'page-break-lines' package to draw a horizontal line for ^L. Page-break-lines uses U+2500 to draw line.
However this character is treated as a double-width in my terminal (something like '- '):
<img width="44" alt="s" src="https://cloud.githubusercontent.com/assets/121803/18583308/76452ea2-7c3c-11e6-8e51-acca79c56973.png">
(Note: there is only 1 character U+2500 before cursor).
I tried these fonts: Monaco, source code pro, terminus. And there terminal: urxvt, xterm, mintty, gnome-terminal.
All have the problem.

There is no problem in Windows or X.

**Comment by TheBB** [comment]
It works fine with my terminal and font, but if not with yours then just disable page-break-lines mode or exclude the package.
