### ISSUE TITLE
`SPC m g` vs. `SPC j`

### ISSUE THREAD

**Issue by syl20bnr** [syl20bnr/spacemacs#7131]
Since we now have a generic approach to jumping to definition, would it makes sense to move `SPC m g` to `SPC j` for all generic commands and move very specific commands to `SPC m j` ?

**Comment by jacktasia** [comment]
FWIW, I also recently added `dumb-jump-go-other-window` to dumb-jump. I find myself using this more than the traditional `dumb-jump-go` which uses the same window.
