### ISSUE TITLE
How to configure startup buffers?

### ISSUE THREAD

**Issue by abhi18av** [syl20bnr/spacemacs#7133]
Hii Spacemacs team)

This issue is related to customization features in Spacemacs, actually I'm trying to use [org-wunderlist](https://github.com/myuhe/org-wunderlist.el) in Spacemacs and it works fine **but** I haven't been able to configure the startup behavior to not to have a *wunderlist* buffer clog up my startup?

Do you have any suggestions to only enable the buffer when I activate the wunderlist mode?

Thanks, I'd really appreciate any help!

**Comment by d12frosted** [comment]
> Do you have any suggestions

In general, make sure you defer loading of `org-wunderlist`. But without having ability to look at exact configurations are used it's hard to help 😸

**Comment by abhi18av** [comment]
Hi @d12frosted :)

Actually, I'm not at home right now so can't really update the configs but I feel this is a general question about spacemacs since apart from the ```.spacemacs``` file there must be a way to configure the startup buffers or silent some buffer. 

Do you have any ideas? I've gone through the docs, but couldn't related much

**Comment by d12frosted** [comment]
Oh, probably I misunderstood your question. I am not quite sure what you mean by 'startup buffers'. Does `org-wunderlist` create some buffers when it's being loaded? I am asking because I have never used `org-wunderlist` and I don't see anything related to creating new buffers in their readme.

**Comment by abhi18av** [comment]
Ah, I think it's something related to persistent buffers across emacs sessions or so I've inferred after experimenting a lot. 

I guess, this isn't an issue as such but for further reference could you please guide me a bit regarding customizing this sort of behavior on spacemacs? I'm insanely curious about this wonderful environment :)
