### ISSUE TITLE
customize keybindings 'C-w' won't overwrite default behavior

### ISSUE THREAD

**Issue by Michaelizm** [syl20bnr/spacemacs#7134]
Hi, I simply work on `evil mode` all the time. so I want to personalize more keystrokes start with `Ctrl`, assuming `dotspacemacs/user-config ()` will take effect in the last step(correct me if I'm wrong), I put 
* (global-set-key (kbd "C-w") 'evil-delete-window)  
or
* (global-set-key (kbd "C-w") 'delete-window)  
under `dotspacemacs/user-config ()`, but seems neither will take effect.

> `evil-delete-window` defines in `evil-commands.el` and `delete-window` defines in `window.el`

**Comment by TheBB** [comment]
Global keys have the lowest priority, so you can't be surprised when global keys are shadowed by other bindings.

[Here](https://github.com/syl20bnr/spacemacs/wiki/Keymaps-guide) is an overly detailed sketch of keymaps and their priorities.

You probably want to define these keys in `evil-normal-state-map` instead.

**Comment by Michaelizm** [comment]
@TheBB Thanks :-)
