### ISSUE TITLE
fill-column-indicator visually unpleasant when increasing font size

### ISSUE THREAD

**Issue by meditans** [syl20bnr/spacemacs#7135]
#### Description :octocat:

`fill-column-indicator` has a visually unpleasant effect when increasing font size
#### Reproduction guide :beetle:
- Start Emacs
- Open a file and input some paragraph of text.
- Toggle `fill-column-indicator`: `SPC t f`
- Increase the font size: `SPC z x` till the column indicator is broken

_Observed behaviour:_ :eyes: :broken_heart:
The column indicator seems to be made with the `|` character, and the text
sometimes displaces his position.

_Expected behaviour:_ :heart: :smile:
A column-indicator which is a nice line indipendently of the size of the text.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.21
- Spacemacs branch: nil (rev. b2d1088)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(emacs-lisp git github version-control latex bibtex markdown erc gnus dash extra-langs finance purescript yaml themes-megapack syntax-checking speed-reading
            (spell-checking :variables spell-checking-enable-auto-dictionary t spell-checking-enable-by-default nil)
            (org :variables org-enable-github-support t)
            (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-scope 'visible)
            (shell :variables shell-default-shell 'eshell shell-enable-smart-eshell t)
            (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johann-tibell")
            (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-complete-with-key-sequence "jk" auto-completion-enable-snippets-in-popup t))
```

**Comment by bmag** [comment]
This is a known issue of `fill-column-indicator`, see upstream issue: https://github.com/alpaker/Fill-Column-Indicator/issues/57

For anyone wondering what's the visually unpleasant effect:
Without scaled font:
![before-font-scale](https://cloud.githubusercontent.com/assets/4334375/18615508/4080691e-7db1-11e6-95ae-096189f22b21.png)

With scaled font:
![after-font-scale](https://cloud.githubusercontent.com/assets/4334375/18615512/5cf281cc-7db1-11e6-81da-ff8bf33bdf7c.png)

**Comment by naclander** [comment]
A workaround for this is to use [zoom-frm](https://github.com/emacsmirror/zoom-frm) instead of adjusting font size. zoom-frm-in and zoom-frm-out ( kind of ) give you the same behavior.

My init.el contains:
```elisp
(if window-system (progn
    (global-set-key (kbd "C--" ) 'zoom-frm-out)
    (global-set-key (kbd "C-=") 'zoom-frm-in)))
````

**Comment by nixmaniack** [comment]
@naclander's workaround is perfect. It should be documented somewhere in docs.

**Comment by sdahdah** [comment]
The same problem also happens when layers like org and latex resize headers. Can the zoom-frm workaround still be applied somehow in that case?
