### ISSUE TITLE
Opening a large JSON file results in long period of unresponsiveness

### ISSUE THREAD

**Issue by bgamari** [syl20bnr/spacemacs#7136]
This is essentially a continuation of #3491. In #3609 there was disagreement regarding the threshold size for prompting to open a file literally. I think that 1MB may even be too high given how inefficient some major modes seem to be. For instance, opening a 200kB JSON file (with all content on a single line) takes over four minutes on my laptop. During this time the editor is completely unresponsive, even to `Ctrl-G`.

**Comment by TheBB** [comment]
Probably your problem is the single line, not the file size.

**Comment by tkothe** [comment]
I'm having exactly the same issue. A 220KB JSON that was missing line breaks renders emacs/Spacemacs (not sure what exactly) completely useless. That should not be the case. Any idea where this should be fixed?
