### ISSUE TITLE
Password prompt in term not working when having f in password

### ISSUE THREAD

**Issue by antonbasic** [syl20bnr/spacemacs#7137]
#### Description :octocat:
Password prompt in term not working when having f in password

#### Reproduction guide :beetle:
- Set your password to for exampel 'sdfg'
- Start Emacs
- Type ':term' or ':ansi-term'
- In the new term buffer type 'sudo echo test'
- When prompted for password type your password

*Observed behaviour:* :eyes: :broken_heart:
You get 'Sorry, try again'

If you change to line run via 'C-c C-j' when prompted/before prompted for password
you can se that typing 'sdfg' will yeild 'fgsd'. When pressing 'f' the point first
be put at begining of line. I've tried all the other characters and it is just 'f'
that is weird.

This is not reproducible with just evil-mode in emacs (i.e. no spacemacs).

*Expected behaviour:* :heart: :smile:
'test' echoed in the buffer

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. e110d91)
- Graphic display: nil
- Distribution: spacemacs-base
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp)
```

#### Backtrace :paw_prints:
```
```

**Comment by TheBB** [comment]
Is it reproducible without evil-escape?

**Comment by antonbasic** [comment]
Nope, I cannot reproduce the problem when evil-escape is disabled so the bug is in that package.

**Comment by TheBB** [comment]
Then please report there.

**Comment by antonbasic** [comment]
Will do that, thank you for helping me pin point the problem :)
