### ISSUE TITLE
go layer fails after update golang

### ISSUE THREAD

**Issue by cocodrino** [syl20bnr/spacemacs#7139]
Hi guys, I don't know if it is the right place for comment this issue, but I've update my system, I'm using arch and it update golang to version 1.7
```bash

yo  /  etc  X11  go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/yo/Documentos/proyectos/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build118286845=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
 yo  /  etc  X11  go version
go version go1.7.1 linux/amd64


```

unfortunately after it update I get this error

```emacs
Company: backend company-go error "GOCODE PANIC: Please check your code by "go build"" with args (candidates )
```

the other features in the go layer works ok but gocode doesnt...I've reinstalled it but seems than it didn't fix the trouble..thanks so much

**Comment by deuill** [comment]
Had the same issue, updating `gocode` etc, i.e.:
```
go get -u -v github.com/nsf/gocode
go get -u -v github.com/rogpeppe/godef
go get -u -v golang.org/x/tools/cmd/oracle
go get -u -v golang.org/x/tools/cmd/gorename
```
Fixed it for me.

**Comment by cocodrino** [comment]
thank you so much, this fix the issue, I only needed download again gocode...I did it before post the issue here but seems than I miss the -v flag..btw what do this?...thanks..

**Comment by deuill** [comment]
The `-v` flag makes `go get` a bit more verbose, which shouldn't affect anything else. It may be that you also forgot the `-u` flag, which has `go get` update the package if it already exists.

**Comment by obscuren** [comment]
Unfortunately I have the same issue, even after updating the go tools. Should I open a new issue?

**Comment by deuill** [comment]
May be because `oracle` was renamed/migrated to `guru`. I always check the Go layer's [README file](https://github.com/syl20bnr/spacemacs/blob/b7e51d70aa3fb81df2da6dc16d9652a002ba5e6b/layers/%2Blang/go/README.org) for up-to-date info. Try this:

```
go get -u -v golang.org/x/tools/cmd/guru
go get -u -v golang.org/x/tools/cmd/goimports
```

**Comment by himanshub16** [comment]
I still have this issue.

```
OS: Ubuntu 17.04 GNOME
Emacs: 25.1.1
Go version: 1.8.3
Spacemacs: v.0.200.9
```
When attempting to auto-complete, I get the same error
```
Company: backend company-go error "GOCODE PANIC: Please check your code by "go build"" with args (candidates )
```

All packages as described in Go layer's readme are installed.

**Comment by himanshub16** [comment]
Nope. @c101088

**Comment by c101088** [comment]
My OS  is windows 10 and i find my go source file (xxx.go)'s directory name  includes  Chinese(Chinese Simplified) characters which trigger this problem .May this help you. :)
