### ISSUE TITLE
Allow ability to unspecify the dotspacemacs-default-font

### ISSUE THREAD

**Issue by nwolfe** [syl20bnr/spacemacs#714]
Basically, I'm suggesting support for a nil value or "system default" value - that is, I don't want to define the font, just use whatever the default would be if I didn't specify it.

I can achieve this effect by specifying a font that doesn't exist, like so:
```lisp
 dotspacemacs-default-font '("DOES NOT EXIST"
                             :size 12
                             :weight normal
                             :width normal
                             :powerline-scale 1.1)
```

This effectively prevents the call to `spacemacs/set-default-font` here: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-spacemacs-mode.el#L104.
Note that I also tried `'()` and `nil`, but those weren't valid definitions. If I removed the setting altogether, it would fall back to the internally defined "Source Code Pro" default.

This ticket is for providing a formal way of doing this. One way might be to allow for a `nil` value to be specified, though a more self-describing value might be appropriate as well.

----

This issue came about when I finally got around to installing the Source Code Pro font, and my .spacemacs had the default font specified as:
```lisp
 dotspacemacs-default-font '("Source Code Pro"
                             :size 12
                             :weight normal
                             :width normal
                             :powerline-scale 1.1)
```
Upon restarting Emacs, my font changed and was now Source Code Pro, but I didn't like it. I wanted to revert to what I was using before, except I don't actually know what that was because I never specified it - it was just using the system default because it couldn't find Source Code Pro (since I didn't have it installed).

I don't necessarily want to uninstall the Source Code Pro font on my system, or disable it, both of which would effectively get me back to whatever font I was using before. But, I also don't want to figure out what that default is and then hard-code it in my .spacemacs, hence the desire for a way to say "I don't care to specify the font - use the system default".

**Comment by nwolfe** [comment]
@syl20bnr In an effort to simply reduce the number of issues, I think we should just close this unless you really think it's worthwhile.

There will always be more important things to spend your time on, and I don't think this is that big of a deal.  From what I've seen in Gitter chat, people know how to install fonts.  It was just me :smile:

**Comment by syl20bnr** [comment]
I agree, if you are OK to close it then do it :+1:
