### ISSUE TITLE
[Q] Can ansi-term with zsh and bindkey -v be friendly to each other?

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7140]
I use zsh with `bindkey -v`. It is deeply ingrained in my muscle memory.
In zsh with bindkey -v, You press `<ESC>` and then `k` to navigate up in the history of commands.

I like very much the idea of using zsh inside ansi-term and not having to leave emacs.

but when I'm inside `ansi-term`, the `<ESC>` key is captured by emacs and not sent to zsh's zle (*zsh line editor*).

Is there a way to tell emacs to send the `<ESC>` key to zsh, or to bind some sequence to represent the `<ESC>` key (e.g.  `<C-x><C-v>`) and then send this to zle?

**Comment by TheBB** [comment]
Try opening term in emacs state instead of evil insert.

```elisp
(evil-set-initial-state 'term-mode 'emacs)
```

**Comment by TheBB** [comment]
See [here](https://github.com/TheBB/spacemacs-layers/blob/master/init.el#L340-L343) for my setup.

**Comment by ninrod** [comment]
@TheBB thanks. Ok, I did that. but Emacs is still swallowing ESC key. Now I hit "ESC" and `which-key` shows me a bunch of options.

<img width="740" alt="screen shot 2016-09-20 at 6 34 13 am" src="https://cloud.githubusercontent.com/assets/8352747/18665175/52463ca4-7efc-11e6-9574-8aea997d7a12.png">

**Comment by bmag** [comment]
These Q&A from Emacs SE deal with `M-` bindings instead of escape, but I think you can adapt the answers to suit your need:
- http://emacs.stackexchange.com/questions/21605/term-raw-map-and-local-unset-key-need-to-pass-m-left-right-up-down-to-shel
- http://emacs.stackexchange.com/questions/17085/undesirable-cursor-jump-after-movement-with-m-left-or-m-right-in-term-mode

**Comment by chadhs** [comment]
@ninrod this could help you as well; modify my examples as needed if they work for you.  :-)

in your zshrc don't turn on vi-mode when launching zsh from emacs and make sure you have command history search setup for emacs- mode
```bash
## mac + emacs plugins
if [ $(uname) = "Darwin" ] && [ $EMACS ]; then
    plugins=(bundler git jump vagrant virtualenvwrapper)
## mac plugins
elif [ $(uname) = "Darwin" ]; then
    plugins=(bundler git jump tmux tmuxinator vagrant vi-mode virtualenvwrapper)
else
## default plugins
    plugins=(git tmux vi-mode)
fi

## command specific history search
### emacs bindings
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
### vim bindings
bindkey -a k history-beginning-search-backward
bindkey -a j history-beginning-search-forward
```

then in your emacs config make some tweaks like this
```elisp
(evil-define-key 'normal term-raw-map "p" 'term-paste)
(evil-define-key 'normal term-raw-map "j" 'term-send-down)
(evil-define-key 'normal term-raw-map "k" 'term-send-up)
(evil-define-key 'normal term-raw-map (kbd "C-c") 'term-send-raw)
(evil-define-key 'insert term-raw-map (kbd "C-c") 'term-send-raw)
```

**Comment by ninrod** [comment]
Thaks @chadhs. Will try that later!
