### ISSUE TITLE
Fresh Install: Symbol's value as variable is void

### ISSUE THREAD

**Issue by sourlemon11** [syl20bnr/spacemacs#7141]
#### Description
This is a fresh install. I'm getting the startup error
```
Symbol's value as variable is void: a566dd7227dd3f88dfa606a8da0e08d3da305df0
```
I **did** check the [ _FAQ_](http://spacemacs.org/doc/FAQ#orgheadline5) and removed the elpa folder, used `emacs --insecure` and also changed `dotspacemacs-elpa-https` to `nil`. I'm testing the waters with spacemacs so I'm not sure if this would cause any issues! Thanks!

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(better-defaults emacs-lisp git markdown org latex javascript gnus evernote elfeed spell-checking syntax-checking)
```
#### Init Backtrace
````
Loading /home/mitchell/.emacs.d/layers/syntax-checking/packages.el (source)...done
smooth-scrolling enabled.
(Spacemacs) Warning: tern binary not found!
Starting new Ispell process [aspell::default] ...
Spacemacs is ready.
(Spacemacs) Error in dotspacemacs/user-config: Symbol's value as variable is void: a566dd7227dd3f88dfa606a8da0e08d3da305df0
````

**Comment by NJBS** [comment]
Could you paste your `.spacemacs` file in a gist?

**Comment by sourlemon11** [comment]
Argh, I'm an idiot. I had an old `.spacemacs` file from a couple years ago and forgot all about it. I had a paradox-github-token that showed up as void (and... deleted). Commented that out and works fine.

I guess you can close this now.

**Comment by TheBB** [comment]
Why can't you close it?
