### ISSUE TITLE
Scala jump to definition is broken

### ISSUE THREAD

**Issue by diego-alvarez-hs** [syl20bnr/spacemacs#7144]
#### Description :octocat:

Scala jump to definition is broken
#### Reproduction guide :beetle:
- Start Emacs
- Open scala project
- Run `ensime` command
- Go to a type
- Press `, g g`   => `spacemacs/jump-to-definition`

_Observed behaviour:_ :eyes: :broken_heart:
- No jump handler was able to find this symbol.

_Expected behaviour:_ :heart: :smile:
- It should navigate where type is defined.
- If I run manually `ensime-edit-definition` it works as expected

Weird thing is that function is the same used here:
https://github.com/syl20bnr/spacemacs/blob/develop/layers/ lang/scala/packages.el#L38

``` scala
  (add-to-list 'spacemacs-jump-handlers-scala-mode 'ensime-edit-definition))
```
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. e110d91)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(ansible
 (auto-completion :variables auto-completion-tab-key-behavior 'complete auto-completion-enable-company-help-tooltip t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 command-log deft emacs-lisp evil-commentary emoji
 (git :variables magit-refs-show-commit-count 'all magit-diff-refine-hunk 'all git-magit-status-fullscreen t)
 github gtags helm html javascript
 (markdown :variables markdown-live-preview-engine 'vmd)
 nlinum nginx plantuml php osx org
 (shell :variables shell-default-shell 'eshell shell-default-term-shell "/usr/local/bin/zsh")
 sql spacemacs-evil spacemacs-language spacemacs-ui-visual spell-checking syntax-checking
 (scala :variables scala-auto-insert-asterisk-in-comments t scala-auto-start-ensime nil scala-enable-eldoc-mode nil)
 react restclient
 (version-control :variables version-control-global-margin t)
 yaml d1egoaz d1egoaz-scala)
```
#### Backtrace :paw_prints:

```
<<BACKTRACE IF RELEVANT>>
```

**Comment by diego-alvarez-hs** [comment]
```
spacemacs-jump-handlers-scala-mode is a variable defined in ‘config.el’.
Its value is (ensime-edit-definition spacemacs/helm-gtags-maybe-dwim)
```

**Comment by TheBB** [comment]
Is `ensime-edit-definition` asynchronous?

**Comment by TheBB** [comment]
If so you can try replacing it with `(ensime-edit-definition :async t)` and see if that works.

**Comment by diego-alvarez-hs** [comment]
@TheBB didn't work either.

This is `ensime-edit-definition`
https://github.com/ensime/ensime-emacs/blob/master/ensime-editor.el#L276-L286
```lisp
(defun ensime-edit-definition (&optional where)
  "Lookup the definition of the name at point.
Goes to the point of the definition (returning point), or fails with `nil'."
  (interactive)
  (let* ((info (ensime-rpc-symbol-at-point))
         (pos (ensime-symbol-decl-pos info)))
    (if (ensime-pos-valid-local-p pos)
        (progn
          (ensime-push-definition-stack)
          (ensime-goto-source-location pos where))
      (not (message "Sorry, ENSIME couldn't find the definition.")))))
```

it seems this function is not being called by `, g g

**Comment by TheBB** [comment]
I'm not sure you did it correctly. Does #7155 fix it?

**Comment by diego-alvarez-hs** [comment]
it didn't work :/
```
      (add-to-list 'spacemacs-jump-handlers-scala-mode '(ensime-edit-definition :async t)))
```

**Comment by t3chnoboy** [comment]
@diego-alvarez-hs try adding `(require 'ensime)` to your `dotspacemacs/user-config`

**Comment by smishmash** [comment]
I seem to have a similar problem. I just installed ensime on more or less stock emacs. Scala 2.11.8, sbt 0.13.13. When I first open a buffer and `M-.` on a definition, I get `Sorry, ENSIME couldn’t find the definition.`

But then when I manually visit the file where the definition lives, come back, and `M-.` on the definition again, ensime jumps to the correct location. Any suggestions for how to fix this issue?

**Comment by andrejlamov** [comment]
Also got broken jump to def on the `master` branch  of spacemacs.

Observed  this when scala-mode loaded:

`File mode specification error: (void-variable imenu-auto-rescan)`

Setting it to `nil` made scala mode load correclty, and use `'spacemacs-jump-handlers-scala-mode`.
