### ISSUE TITLE
Its too slow to change return back to normal mode

### ISSUE THREAD

**Issue by yunfan** [syl20bnr/spacemacs#7145]
i found that when i was in normal mode and i press `i` to enter insert mode, the mode changing happend immediately

but when i want to return back to normal mode by pressing `esc`, it will cost me about 0.5s or more to wait the changing completed. such delay caused many problem when i am doing an action sequences

for eg.      i might drop in 1 line to modify some text and then return back to normal mode to use its quick move abilliys. like `i` -> `blah blah` -> `<esc>` -> `11j`
because of the delay, finally i wont get my cursor 11 line after, instead, i got a new line break after my last editing

i guess this caused by everytime you enter normal node, you need to do lots of initialization jobs?

**Comment by bmag** [comment]
Please follow [how to make a great bug report](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report). I don't experience the slowness you describe (and I tried), so there must be some hidden factors here.

**Comment by bmag** [comment]
> finally i wont get my cursor 11 line after, instead, i got a new line break after my last editing

What? That's what would have happened if you pressed <kbd>C-j</kbd>, not <kbd>11j</kbd>. Must be a bug somewhere. When this happens, please run <kbd>C-h l</kbd> (or `M-x view-lossage`) and include the output here. (it shows what keys were typed, and in Emacs 25.1 also what commands were executed)

**Comment by yunfan** [comment]
@bmag i am using emacs24 from ubuntu 1604's repo

**Comment by yunfan** [comment]
i cant reproduced this time. all lag just happened to disapeared!!!!. please keep this issue opened. i will record a screen video when i met them

**Comment by bmag** [comment]
@yunfan I don't want to brush you off, but so far I don't have enough info to help you. I point you again to our wiki entry for how to report bugs: https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report
I understand that you don't have exact reproduction steps, so if it happens again this info will help us to help you:
- output of <kbd>C-h l</kbd> immediately after a lag happens
- if you do a screen recording, make sure that we can see what keys you press. The `command-log` layer can help - it records the keys you press and shows them inside an Emacs buffer.

**Comment by nixmaniack** [comment]
How about we add an FAQ entry for known delay issues when using `ESC`.
 - If you're using tmux - `escape-time` can affect the behaviour 
 - If you're on Mac (Mavericks+) - if you start GUI with daemon and use tty emacsclient - if GUI is not active, emacs goes into 'App Nap' after some time and terminal client gets this delays in keypresses. 

There may be other known issues as well.

**Comment by yunfan** [comment]
@nixmaniack aha, i am using spacemacs inside a dvtm session which inside a tmux session

@bmag i am sorry for this malformat bug report, but the situation at that time is i was introduced by an article which encourage vim user to use emacs via spacemacs, cause it has well vim simulatation.
so i followed that and try, it works and even support register. this make me very happy, then i met that lag problem, i just hope that could be quickly solved so i could continue to my trying

you know that before this issue, i have another one which is the freeze of spacemacs after init. its caused by the autostart script which try to do an updating check. and i happened live in a hardplace for interenet(china). it failed and freeze. so after reporting that issue. people point me the problem, i followed the solution steps, it just be fixed. then i thought i might get a quickly help in this issue case again.

sorry again.

**Comment by yunfan** [comment]
i just met that problem now, and i have record a screenshot for you with `C-h l`

i uploaded the reprodced video at `http://do.geek42.info/hole/demo.mkv`

just skip to 0:16 

you will see the real effects in emacs and later you can see my keypress logs

for summary, i press `esc` then i press `j` which i suppose will affect like `enter normal mode` then `move to next line` . but it doesnt.

if i wait about 0.5s after i press `esc`, (extractly wait that left bottom green icon to turned into yellow), and then `j` , i will get what i expected like in normal vim

my enviroment is

ubuntu 16.04 x86_64
emacs24
spacemacs from github clone

**Comment by bmag** [comment]
@yunfan thanks for the additional info. I watched the video, and I see that typing <kbd>ESC j</kbd> resulted in Emacs creating a new indented line and remaining in insert state. In stock Emacs, the <KBD>ESC</KBD> prefix serves as a replacement for <kbd>M-</kbd> combinations, so <kbd>ESC j</kbd> is the same as <kbd>M-j</kbd>. In fact, Emacs' behavior in the video is the exact same thing that would happen if you press <kbd>M-j</kbd> instead <kbd>ESC j</kbd>. 

In Spacemacs (and also just with `evil-mode`) insert state, <kbd>\<escape\></kbd> is bound `evil-normal-state`. Pressing the <KBD>ESC</KBD> char is translated to <kbd>\<escape\></kbd>, and then Emacs exits from insert state to normal state.

Your situation looks like <kbd>\<escape\></kbd> is not bound to `evil-normal-state`, or <KBD>ESC</KBD> is not translated to <kbd>\<escape\></kbd>. As a result <kbd>ESC j</kbd> calls `indent-new-commen-line` instead of `evil-normal-state` followed by `evil-next-line`. Does your configuration contain anything the might change the <KBD>ESC</KBD> or <kbd>\<escape\></kbd> key bindings? Can you please paste the output of <kbd>SPC h d s</kbd>? Does this happen also in GUI Emacs, or just in terminal Emacs? There is also a chance that the behavior depends on your terminal application and tmux.

P.S. a short explanation of <KBD>ESC</KBD> and <kbd>\<escape\></kbd>: http://stackoverflow.com/questions/16677825/emacs-escape-key

@nixmaniack adding to the FAQ sounds like a good idea

**Comment by yunfan** [comment]
@bmag you are right, i have tested, this problem happened only in tmux session . and in a naked terminal, it just works well, also the color scheme were different too

and i have tried `ctrl-[` , `j` , same issue

here is the output of `SPC h d s`

```
elisp
(emacs-lisp)


Information has been copied to clipboard.
You can paste it in the gitter chat.
Check the *Messages* buffer if you need to review it
Auto-saving...
Undo branch point!
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
elisp
(emacs-lisp)


Information has been copied to clipboard.
You can paste it in the gitter chat.
Check the *Messages* buffer if you need to review it
C-c C-b is undefined
user-error: Previous command was not an evil-paste: next-line
byte-code: End of line [3 times]
byte-code: End of line

```

**Comment by bmag** [comment]
@yunfan I have almost zero experience with tmux, but according to http://unix.stackexchange.com/questions/23138/esc-key-causes-a-small-delay-in-terminal-due-to-its-alt-behavior and http://superuser.com/questions/252214/slight-delay-when-switching-modes-in-vim-using-tmux-or-screen/252717#252717 adding this setting to `.tmux.conf` might solve the problem:
```
set -s escape-time 0
```
If that doesn't work, I'd suggest searching the web for tmux+escape problems.

**Comment by nixmaniack** [comment]
I do use emacs within tmux and as @bmag mentioned you should try setting `escape-time` to `0`. I assumed my comment would have given hint in exploring in right direction for `tmux` issue.

What's the output of following command? 
```
tmux show-option -s | grep escape-time
```

**Comment by yunfan** [comment]
@bmag @nixmaniack  yes, as you both mentioned. my tmux has a 0.5 value of escape-time. i have set it to 0 and problem solved . thanks all very much

**Comment by cdepillabout** [comment]
I was able to fix a similar problem that occured while running emacs under gnu screen.  I'll just leave this here in case anyone else stumbles on it as well.

http://unix.stackexchange.com/questions/8439/gnu-screen-makes-vim-esc-key-slow

Basically, I just added `maptimeout 0` to my `~/.screenrc`.  All lag with <kbd>ESC</kbd> went away.

**Comment by Blaisorblade** [comment]
Thanks for the `escape-time` tip! I should have googled this sooner!

Would it be possible to warn users of this feature interaction? Or rather, is that the sort of thing that Spacemacs might merge (either by default or in some layer?)

One could detect if it’s happening: `tmux` sets `$TMUX`, and `tmux show-option -s` allows testing if the current setting is 0. So Spacemacs could test for `$TMUX`, test the current setting, and warn if it’s bad and point to a fix (with options to disable the warning).

**Comment by Blaisorblade** [comment]
BTW for others: with `tmux set-option -t 0 escape-time 0` I was able to change the setting in a running `tmux` session (the one number 0, I checked with `tmux list-sessions`; change the argument to `-t` to affect a different session).

**Comment by nixmaniack** [comment]
> Would it be possible to warn users of this feature interaction? Or rather, is that the sort of thing that Spacemacs might merge (either by default or in some layer?)

@Blaisorblade That should definitely be desirable if you can do it. The other option is to add it to FAQ section of spacemacs which was pointed earlier in the discussion.

**Comment by reedspool** [comment]
I found this thread extremely helpful and `set -s escape-time 0` solved my problem. I just want to add that you can run this in a current tmux session by getting to the tmux command line first `C-b : set -s escape-time 0 RET`
