### ISSUE TITLE
[Q] how to properly bind TAB?

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7147]
TAB is a big key residing in prime keyboard real state with no real purpose in evil normal mode. 

but how do I rebind it properly? The following works in graphic mode, but does not work in terminal emacs:

```emacs-lisp
(define-key evil-normal-state-map 
  (kbd "<tab>") 'spacemacs/alternate-buffer)
```
* how do I make it work on terminal?

Now suppose you want to bind `SPC TAB` to your liking through the `bind-map` package.
`(kbd "<tab">)` won't work. You have to use `"TAB"`:

```emacs-lisp
  (bind-map-set-keys main-map "TAB" 
   'spacemacs/alternate-buffer)
```

* why in some cases I have to use `"TAB"` and in other cases I have to use `(kbd "<tab>")`?

**Comment by TheBB** [comment]
This is necessary to make things work across GUI and terminal. In the GUI it's possible to distinguish the tab key and the C-i key, whereas in the terminal these are identical. AFAIK `<tab>` refers to the tab *key* and will only ever work when the actual tab *key* is pressed, while `TAB` and `C-i` captures the *keycode* 9.

> how do I make it work on terminal?

You have to use TAB, there's no such thing as `<tab>` in the terminal.

> Now suppose you want to bind SPC TAB to your liking through the bind-map package.
(kbd "<tab">) won't work. You have to use "TAB":

Well, `(kbd "<tab">)` is a syntax error, so try `(kbd "<tab>")` instead :-).

Probably because SPC TAB is bound and that takes precedence. Have you tried unbinding SPC TAB?

**Comment by TheBB** [comment]
Note also the dotspacemacs variable for distinguishing TAB and <tab>.

**Comment by ninrod** [comment]
Really, the problem is that `(kbd "<tab>")` does work, but only in graphical mode, not in terminal.

"TAB" does not work
(kbd "tab") does not work

**Comment by TheBB** [comment]
Which one are you talking about now? Give me the exact code please.

**Comment by TheBB** [comment]
> Really, the problem is that (kbd "\<tab\>") does work, but only in graphical mode, not in terminal.

I told you, there's no way to get `<tab>` in a terminal.

**Comment by ninrod** [comment]
I'm using: 

```lisp
(define-key evil-normal-state-map 
  (kbd "<tab>") 'spacemacs/alternate-buffer)
```

only thing that works. If i change "<tab>" to "tab", then it stops working even in graphical mode.

Thanks for your help by the way

**Comment by ninrod** [comment]
that variable you mentioned is set to nil (distinguish TAB from C-i).

**Comment by TheBB** [comment]
```elisp
(define-key evil-normal-state-map (kbd "TAB") 'spacemacs/alternate-buffer)
```

works for me, in all four combinations of gui/terminal and `dotspacemacs-distinguish-gui-tab` set to `nil` or `t`.

Tested this in the scratch buffer (text-mode). It's of course possible that you have other keys shadowing it. (You haven't told me what else it is bound to so there's no way for me to know that.)

**Comment by ninrod** [comment]
Yes! that works. Thanks @TheBB. I discovered I'm having problems in org-mode though.

Seems that org-mode defines it's binds after I define my binds. So TAB is defined to org-cycle.

Is there a way to workaround that? (maybe this is a separate issue)

**Comment by ninrod** [comment]
Ok so I think I got it down and I'm leaving it here for posterity:

If you want to rebind TAB in normal evil state, do this.

```lisp
;; evil normal mode bind
(define-key evil-normal-state-map (kbd "TAB") 'spacemacs/alternate-buffer)
;; org mode specific bind
(evil-define-key 'normal org-mode-map (kbd "TAB") 'spacemacs/alternate-buffer)
```

**Comment by TheBB** [comment]
That's because evil-org overrides it.

**Comment by ninrod** [comment]
Thank @TheBB.

Just an update: Actually, the solution is a bit more involved. `(kbd "TAB")` does work in terminal but not in graphical. `(kbd "<tab>")` works in graphical, but not in terminal. A condition is warranted:

```lisp
  (evil-define-key 'normal org-mode-map (kbd "TAB") 'spacemacs/alternate-buffer)
  (when (display-graphic-p)
    (evil-define-key 'normal org-mode-map (kbd "<tab>") 'spacemacs/alternate-buffer) )
```

Maybe that's ugly, but that works for me in all scenarios.

**Comment by cviebig** [comment]
For anyone who prefers `spacemacs/set-leader-keys`:

    (spacemacs/set-leader-keys-for-major-mode 'c++-mode "<tab>" 'clang-format-buffer)
