### ISSUE TITLE
Octave layer uses wrong comment character

### ISSUE THREAD

**Issue by Honigmelone** [syl20bnr/spacemacs#7148]
#### Description :octocat:

Octave mode does not use Matlab comment character to comment lines with M-;

Octave scripts should be compatible with Matlab. This behaviour breaks compatibility. 
#### Reproduction guide :beetle:
- Start Emacs
- Open new file in octave-mode
- type something
- mark it and press M-;

_Observed behaviour:_ :eyes: :broken_heart:
`## something`

_Expected behaviour:_ :heart: :smile:
`% something`
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. e110d91)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(emacs-lisp git latex org octave spell-checking syntax-checking version-control)
```

**Comment by TheBB** [comment]
Emacs source code: https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/octave.el#L51-L52

So first of all it's an Emacs bug if it's a bug at all, not a Spacemacs one.

Second, it's easy to fix yourself by changing the value of `octave-comment-char` in `dotspacemacs/user-init`.

Third, `#` is a valid comment character in octave scripts, so compatibility is technically not being broken. It's Octave's responsibility to be compatible with Matlab, while the responsibility of octave-mode is to be compatible with Octave (which it is).

Fourth, of course we can change this in Spacemacs if everyone wants, but I think this is splitting hairs for something that is easily configured yourself. Better just to document it IMO.

**Comment by bmag** [comment]
I've started to comment, then saw that @TheBB answered, so I'll just add a source:

> In the Octave language, a comment starts with either the sharp sign character, ‘#’, or the percent symbol ‘%’

https://www.gnu.org/software/octave/doc/v4.0.0/Single-Line-Comments.html#Single-Line-Comments

**Comment by Honigmelone** [comment]
You are both right that technically this is not a bug. But let me explain why I think the % character is better.
 The reason for  # being an additional comment charakter is that it allows for #! /usr/bin/octave -q to be the first line of a file, in order to execute is as a script from the commandline. http://wiki.octave.org/FAQ#Comments_with_.23 
If the % character is used after the #! /usr/bin/octave line, this does not impair the commandline execution of an octave script.
Thus using the % character as the default comment character has no drawbacks for those who don't use Matlab. It is however beneficial for everyone who needs Matlab compatibility, because matlab does not understand the # character. 

Thus I want to propose to add the line: 
`   (setq octave-comment-char 37) ` 
to the packages.el of the octave layer. 
This does not break syntax highlighting because both characters are defined as comment characters in the octave mode. 

I don't know how to make a pull request. If you agree with my reasoning I will read it up.
