### ISSUE TITLE
Spacemacs unresponsible when sending commands to octave

### ISSUE THREAD

**Issue by Honigmelone** [syl20bnr/spacemacs#7150]
#### Description :octocat:

I am not sure if this is a spacemacs bug or an emacs bug. But sending a buffer or a region to octave will hang spacemacs until the evaluation is complete. When the commands are executed manually in the inferior process buffer, everything works fine.

I tried this on two workstations.
#### Reproduction guide :beetle:
- Start Emacs
- write folling in octave mode:
  `for i=1:10
  i,
  pause(1);
  end`
- send the buffer to octave with <SPC m s b>

_Observed behaviour:_ :eyes: :broken_heart:
Emacs is unresponsible for 10 seconds. Then a second buffer window opens with the output visible.
(sending the same buffer to octave again will also trigger emacs becoming unresponsible for 10 seconds with the full output shown afterwards.)

_Expected behaviour:_ :heart: :smile:
Second buffer opens and i is counting up.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. e110d91)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(emacs-lisp git latex org octave spell-checking syntax-checking version-control)
```

**Comment by TheBB** [comment]
It's an Emacs problem. This is pretty easy to check since the same happens when running stock Emacs. Please report upstream.

**Comment by Honigmelone** [comment]
Upstream report: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24492

**Comment by gzmask** [comment]
same problem. Then I Press 'i' into insert mode, and then press "enter", the octave turn from red to green and all a sudden the output goes out. I suspect that this is a evil mode specific problem.
