### ISSUE TITLE
Golden ratio w/ tmux layer doesn't resize on `tmux-nav-*`

### ISSUE THREAD

**Issue by rjhilgefort** [syl20bnr/spacemacs#7152]
#### Description :octocat:
Golden ration doesn't seem to work with the tmux package in develop. This worked previously in master, as I just upgraded to devlop to find it's not working. Specifically, it doesn't resize the window when using `tmux-nav-right` (or `left`, `up`, `down`). It does resize if I `mouse-1` on the newly targetted window, or if I make another split out of the newly targetted window.

#### Reproduction guide :beetle:
- Start Emacs
- Toggle golden ration mode on: `SPC t g`
- Open a couple windows
- Invoke `tmux-nav-right` (or `left`, `up`, `down`)

*Observed behaviour:* :eyes: :broken_heart:
Window remains the size it was before I focused into it.

*Expected behaviour:* :heart: :smile:
Newly targetted window should resize (expand).

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. e110d91)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-company-help-tooltip t)
 better-defaults colors dash emacs-lisp emoji evil-snipe evil-commentary games
 (git :variables git-enable-github-support t git-gutter-use-fringe t)
 github lua org osx pandoc
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts themes-megapack tmux version-control vim-empty-lines html javascript markdown syntax-checking rjhilgefort)
```

**Comment by TheBB** [comment]
Feedback on https://github.com/syl20bnr/spacemacs/pull/7154 ?

**Comment by rjhilgefort** [comment]
👍 Thanks!

**Comment by TheBB** [comment]
Fixed
