### ISSUE TITLE
Evil mode, bufdo, arglist and so forth

### ISSUE THREAD

**Issue by tobimensch** [syl20bnr/spacemacs#7158]
For me one of the things I like about spacemacs is the prospect of going back and forth between it and vim without having to relearn much in either direction.

I just learned about a vim command called bufdo that lets you do operations on all buffers, and I simply assumed that it had to exist in spacemacs as well. I was wrong. Of course there's an emacs way to do the same thing, but I intend to learn and use the vim way in spacemacs. The same holds true for arglist and other commands.

Not sure that this is the right place for this ticket. I hope these features will get implemented in spacemacs/evil. Or maybe they are and I miss some additional packages?

**Comment by TheBB** [comment]
It's not in the scope of evil (or Spacemacs) to perfectly mimic vim. If you want these features you are probably going to have to implement them yourself.

bufdo is simple, just loop over `(buffer-list)` and do whatever you need. arglist would be tougher probably.

**Comment by TheBB** [comment]
I'd recommend to make a feature request to evil, but don't expect to find much enthusiasm for it there.

**Comment by MephistoMMM** [comment]
Bufdo is not much useful for emacs. 

Perhaps spacemacs need a function like bufdo but only work for the buffers  belonging to the same project (projectile-do?)

**Comment by dzop** [comment]
@tobimensch If you are still interested in having argdo in evil, I have a package that adds support for argument lists (https://github.com/dzop/evil-arglist) that you may want to try out.
