### ISSUE TITLE
Terminals with RPROMPT are incomatible with window resizing

### ISSUE THREAD

**Issue by qqldd** [syl20bnr/spacemacs#7161]
#### Description

With golden-ratio-mode enabled, the shell mode behaves abnormally. The mouse click on shell buffer will generate extra shell prompts. (Like type RET multiple times)
#### Reproduction guide
- Start Emacs
- Enable golden-ratio-mode
- M-x shell
- Left-Click shell buffer

_Observed behaviour:_
Shell buffer generated multiple shell prompts. Like I typed RET multiple times. Sometime generated random characters like `8wd`

_Expected behaviour:_
The shell should just be focused withl left-click.
#### System Info
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(emacs-lisp c-c   shell-scripts python csv shell sql markdown latex javascript html git perforce auto-completion gtags irony-mode semantic colors themes-megapack sr-speedbar org eyebrowse ibuffer)
```
#### Backtrace

```
BACKTRACE IF RELEVANT
```
#### Additions

The same behavior can also be reproduced on OSX with Emacs 25.1.1 and 24.5

**Comment by TheBB** [comment]
Can't repro this.

**Comment by qqldd** [comment]
It turns out that it is because of oh-my-zsh double line prompt theme problem. For example, 'candy' theme in oh-my-zsh has the issue. But all one line prompt theme does not have the issue.

**Comment by TheBB** [comment]
I have a double line prompt and can't repro.

**Comment by TheBB** [comment]
Okay, it's not the two lines, it's the `RPROMPT` you need.

Then this is easily reproducible with stock Emacs, so you should report there, not here.
