### ISSUE TITLE
org mode html export fails to launch browser

### ISSUE THREAD

**Issue by rgoggans** [syl20bnr/spacemacs#7164]
Hi

Just installed the org mode layer, when I try to do an export "as html file and open" the generated html code simply opens in a new buffer. Nothing happens with my browser. There are no errors in messages.

My emacs seems to have some awareness of chrome as links such as the homepage link on the spacemacs startup works and launches chrome OK.

Any help is appreciated

**Comment by izahn** [comment]
I think that is the expected behavior. At any rate I doubt it has anything
to do with spacemacs. Do  you see different behavior with vanilla emacs?

**Comment by rgoggans** [comment]
yea i think you're right, seems to be the expected behavior
