### ISSUE TITLE
Add impatient-mode to the html layer

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#7168]
Add [impatient-mode.el](https://github.com/skeeto/impatient-mode) [video](https://www.youtube.com/watch?v=QV6XVyXjBO8&feature=youtu.be) 

There is an old PR #2776 that seems to be dead. Mb someone wants to take over?

**Comment by TheBB** [comment]
> Mb someone wants to take over?

I nominate you. You're good at posting feature requests, why not implement some?

**Comment by JAremko** [comment]
> I nominate you. You're good at posting feature requests, why not implement some?

If everybody will not do anything or no one will do something I'll do it :shipit:
