### ISSUE TITLE
Spacemacsify zone.el

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#7169]
Add Spacemacs key bindings and stuff for [zone.el](https://github.com/emacs-mirror/emacs/blob/master/lisp/play/zone.el) - built-in package with a ton of  awesome(and mildly useful) features.

**Comment by JAremko** [comment]
just type `:zone` and you'll see why we need it.

**Comment by JAremko** [comment]
Then do it again (it has random selection)

**Comment by nixmaniack** [comment]
And may be provide an option to enable `zoning` after some amount of idle time! May be there's already variable to configure it. It'd be cool to just zonify the banner.

**Comment by JAremko** [comment]
@nixmaniack  we can add 2 variables to .spacemacs:
  1. Time after "screen saver" enables.
  2. Type - may have value `'random` or specific and If `nil` - disable. 

Also it might be useful to  have a key binding for enabling it manually.

**Comment by nixmaniack** [comment]
I just tried using `zone` on spacemacs text banners - it looks nice only with certain `zone-programs` like `zone-pgm-rotate-RL-lockstep or zone-pgm-whack-chars` which keep the integrity of the logo/banner intact i.e. `spacemacs` ASCII text remains readable even in zoning phase - which IMO looks good. Also centring the banner while zoning IMO looks much better. 

![zone-1](https://cloud.githubusercontent.com/assets/542810/18764105/b19386d4-812d-11e6-9333-0fe94aec1829.gif)
