### ISSUE TITLE
Add fireplace.el  layer 

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#7170]
Add [fireplace.el](https://github.com/johanvts/emacs-fireplace)  layer  so @TheBB  can sit down and look at cozy calming fire after a long working day labeling all the issues and chill (because the fire isn't real. Duh!)  
Others may also use it for the similar purposes.

![https://camo.githubusercontent.com/fb294d4545fdc5558777cffe6d21777748fec615/68747470733a2f2f7261772e6769746875622e636f6d2f6a6f68616e7674732f656d6163732d66697265706c6163652f6d61737465722f696d672f66697265706c6163652e676966](https://camo.githubusercontent.com/fb294d4545fdc5558777cffe6d21777748fec615/68747470733a2f2f7261772e6769746875622e636f6d2f6a6f68616e7674732f656d6163732d66697265706c6163652f6d61737465722f696d672f66697265706c6163652e676966)

**Comment by d12frosted** [comment]
Haha. I like this. But last time I used it - it was cropped on my screen :(

**Comment by d12frosted** [comment]
P. S. I bet you'll love [this thread](https://www.reddit.com/r/emacs/comments/4bk85r/whats_the_weirdest_thing_youve_done_with_emacs/). Most notable thing is [Deldo - Vibration Control and Teledildonics Mode for Emacs](https://www.youtube.com/watch?v=D1sXuHnf_lo) and [answer](https://www.reddit.com/r/emacs/comments/4bk85r/whats_the_weirdest_thing_youve_done_with_emacs/d1shlmv) from author:

> Yup, that's mine. And it's definitely the weirdest thing I've done in emacs. :)

**Comment by JAremko** [comment]
@d12frosted    May be a good addition for the the FUN section mb FUN/after-work subcategory :smiley:

**Comment by JAremko** [comment]
Looks like it has some bugs that hasn't been fixed for a while.
