### ISSUE TITLE
Consider merging javascript and reactjs layers

### ISSUE THREAD

**Issue by tko** [syl20bnr/spacemacs#7172]
Considering that ultimately reactjs is nothing but plain javascript + syntactic jsx sugar on top having two independent and divergent layers seems... artificial, or seemingly pointless duplicate effort at least.

I'm vaguely aware of web-mode (react) and js2-mode (javascript; or is it js4-mode already?) being the main difference between the two but don't really know the details. Couldn't we just have _all_ the javascript goodies including the support for jsx syntax?

**Comment by robbyoconnor** [comment]
I don't see the problem with it being modular like it is.

**Comment by TheBB** [comment]
Please keep this discussion to https://github.com/syl20bnr/spacemacs/issues/5848
