### ISSUE TITLE
Create a new layer

### ISSUE THREAD

**Issue by yangjiedage** [syl20bnr/spacemacs#7174]
I want to create a new layer of spacemacs. And what are the exact steps?

**Comment by yangjiedage** [comment]
I want to create a new layer of spacemacs. And what are the exact steps?

**Comment by NJBS** [comment]
See http://spacemacs.org/doc/LAYERS.html

**Comment by quangv** [comment]
I'm new to spacemacs, but I think `M-x configuration-layer/create-layer` might be what you are looking for.
