### ISSUE TITLE
avy-move-region is missing

### ISSUE THREAD

**Issue by xetra11** [syl20bnr/spacemacs#7176]
Hey guys!

I just discovered avy and was playing around with it. As I wanted to move a region by it today I realized `avy-move-region` is gone. I restarted spacemacs but that did not fixed the problem. Everything else is available but move-region.

spacemacs-0.105.2
emacs-24.5.1

**Comment by d12frosted** [comment]
Please, make sure that you have upgraded all packages 😸

**Comment by xetra11** [comment]
...sorry

I thought spacemacs update check on startup would automatically update packages as well :(
