### ISSUE TITLE
Clojure-mode not working with golden-ratio turned off?

### ISSUE THREAD

**Issue by BartAdv** [syl20bnr/spacemacs#719]
Hi,

Just fresh clone with only couple of layers activated: `caskell clojure extra-langs`. When I load clojure file, I get error about undefined variable `golden-ratio-extra-commands`. Turning on golden ratio (`SPC t g`) before loading clojure file helped...

**Comment by nwolfe** [comment]
@BartAdv I believe this is fixed in the `develop` branch. I've been on that branch for a few days with no issues.

**Comment by glittershark** [comment]
:+1: fixed in `develop`

**Comment by BartAdv** [comment]
Indeed...time to move on the develop-side!
