### ISSUE TITLE
Missing functionality? How to descend into a sexp?

### ISSUE THREAD

**Issue by bpstahlman** [syl20bnr/spacemacs#7193]
I see that L can be used to move forward by sexps, but if I'm sitting at the head of a deeply nested list, L causes a jump to the very end. Often, I want to descend _**into**_ the sexp. What is the right way to do this in evil-lisp-state?

I can't imagine there would be a function for backing up out of a sexp (U - sp-backward-up-sexp), but not one for descending down into the sexp in the first place...

Thanks,
Brett S.

**Comment by bmag** [comment]
The key <kbd>l</kbd> (`evil-lisp-state-forward-symbol`) jumps to the next symbol, in this case it will descend to the first symbol inside the sexp. All the bindings are listed [here](http://develop.spacemacs.org/doc/DOCUMENTATION.html#editing-lisp-code) (or via `which-key` and <kbd>SPC ?</kbd>).

**Comment by bpstahlman** [comment]
Ah. I missed it because I was searching for "down".
Thanks!
Brett Stahlman

**Comment by bmag** [comment]
@bpstahlman if the issue is solved, please press the "close" button
