### ISSUE TITLE
Default emacs' empty line indicator is missing

### ISSUE THREAD

**Issue by elandx** [syl20bnr/spacemacs#7196]
#### Description
Even with removed `vi-tilde-fringe` package `toggle-indicate-empty-lines` command does nothing, means default emacs's indicator of empty lines is missing and the fringe remains empty.

#### Reproduction guide
- Start Emacs
- `M-x vi-tilde-fringe-mode` 
- `M-x toggle-indicate-empty-lines` 

*Observed behaviour:*
The left fringe remains empty

*Expected behaviour:*
Default emacs' empty line indicator 

#### System Info
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((shell :variables shell-default-term-shell "/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
 mu4e auto-completion org spell-checking ess emacs-lisp latex asciidoc lua markdown org-reveal org-pandoc pdf-tools google-calendar helm-add xah-math writeroom no-mouse langtool wcheck csv)
```

#### Backtrace
```
```

**Comment by TheBB** [comment]
Can't reproduce this. Excluded vi-tilde-fringe-mode and toggle-indicate-empty-lines does indeed indicate empty lines.

**Comment by elandx** [comment]
Thanks for such a quick reply! Unfortunately i have the problem even with fresh spacemacs installation from master branch, new `.spacemacs` and `vi-tilde-fringe` excluded.  When install from develop branch the problem is gone, but i am on the master...

**Comment by TheBB** [comment]
Okay, then let's say this is fixed. ;-)

**Comment by TheBB** [comment]
If you'd like to stay on master, there will be a release soon.

**Comment by elandx** [comment]
Thank You very much for Spacemacs!
