### ISSUE TITLE
C/C++ clang auto-completion not working

### ISSUE THREAD

**Issue by cneira** [syl20bnr/spacemacs#7197]
Hi,

clang-autocomplete is not working following the documentation at 
https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/c-c%2B%2B

Observed behaviour:
C++ auto completion does not work

Expected behaviour:
C++ auto completion working

System Info

OS: Windows 7 
Emacs: 25.0.50.1
Spacemacs: 0.105.22
Graphic display: t
Distribution: spacemacs
Editing style: emacs
clang version : 3.9.0

--additions to .spacemacs 
dotspacemacs-configuration-layers
'(
  ;; ----------------------------------------------------------------
  ;; Example of useful layers you may want to use right away.
  ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
  ;; <M-m f e R> (Emacs style) to install them.
  ;; ----------------------------------------------------------------
  auto-completion
  ycmd
  (c-c++ :variables c-c++-enable-clang-support t)
  auto-completion
  emacs-lisp
 
  )

(defun dotspacemcs/user-config ()
(push '("cpp" "h") projectile-other-file-alist)
(global-set-key [C-M-tab] 'clang-format-region)
;; Bind clang-format-buffer to tab on the c++-mode only:
(add-hook 'c++-mode-hook 'clang-format-bindings)
(defun clang-format-bindings ()
  (define-key c++-mode-map [tab] 'clang-format-buffer))
)

(setq-default dotspacemacs-configuration-layers
              '((c-c++ :variables c-c++-enable-clang-support t)))

**Comment by TheBB** [comment]
What's the contents of the clang output buffers?

**Comment by cneira** [comment]
Hi, I don't even have clang output buffers. I tried to autocomplete just typing TAB and nothing happens.

**Comment by TheBB** [comment]
TAB doesn't trigger auto-completion. Can you give me an example of a case where you expect to see something popping up and you don't?

**Comment by TheBB** [comment]
For example, if you open a C file and type this

```C
int some_function();
int some_other_function();

int main() {
    some|
}
```

Then put your cursor where the `|` is and do `M-x company-complete`, what happens?
```

**Comment by cneira** [comment]
company -complete is not available :(

**Comment by TheBB** [comment]
How? You have the auto-completion layer enabled, company should be installed. Can you check?

**Comment by TheBB** [comment]
1. Do you have .emacs.d/elpa/company-.... folder?
2. In `SPC hdf` if you type `company`, are there things called `company-...` there?

**Comment by cneira** [comment]
I just checked  I don't have such folder  .emacs.d/elpa/company-*. That should have been installed by default  ?

**Comment by TheBB** [comment]
Can I see your *whole* dotfile?

**Comment by TheBB** [comment]
Please just put it on http://pastebin.com, not a comment. :-)

**Comment by cneira** [comment]
Here it is 
https://pastebin.ubuntu.com/23234378/

**Comment by TheBB** [comment]
Okay, here's what you're going to do. Delete everything after line 342. Then go to line 20 and put your layers there instead, where they should be.

**Comment by cneira** [comment]
Thank you very much now is working ?

Mon Sep 26 14:57:08 2016
clang failed with error 1:
c:/Program Files (x86)/LLVM/bin/clang.exe -fsyntax-only -Xclang -code-completion-macros -x c++ -Xclang -code-completion-at=-:44:6 -

<stdin>:40:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^
1 error generated.

**Comment by TheBB** [comment]
Yep, it's working. Now you just need to configure the include paths.

**Comment by TheBB** [comment]
https://www.youtube.com/watch?v=OjbkCEkboA8

I have a video about this (about halfway in maybe). It's on Linux but the idea is the same on Windows, you need to make this .clang_complete file which has the paths where clang can find the header files you are including in your project.

**Comment by cneira** [comment]
Thank you very much!
