### ISSUE TITLE
Persp-mode causes warning

### ISSUE THREAD

**Issue by GreyGhostIX** [syl20bnr/spacemacs#7199]
#### Description :octocat:
A few seconds after opening, \*compile-log\* appears and `Warning: (lambda (b)...) quoted with ' rather than with #'` is shown. This error doesn't appear when`persp-mode` is included in `dotspacemacs-excluded-packages`, leading me to believe it is caused by something in this package. It could be related to [this issue](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=11357), as it seems there are non-spacemacs users experiencing it. [This reddit thread](https://www.reddit.com/r/emacs/comments/54jpl9/warning_lambda_b_quoted_with_rather_than_wits/) discusses this issue.

#### Reproduction guide :beetle:
- Start Emacs with default .spacemacs template.

*Observed behaviour:* :eyes: :broken_heart:
- Observe \*compile-log\* popup with warning.

*Expected behaviour:* :heart: :smile:
- Do not observe \*compile-log\* popup warning.

#### Temporary fix reproduction guide
- Add `persp-mode` to `dotspacemacs-excluded-packages`.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. cf951a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(osx
 (org :variables org-pretty-entities t org-bullets-bullet-list
      '("○"))
 (version-control :variables version-control-diff-tool 'diff-hl)
 (git :variables git-magit-status-fullscreen t)
 (shell :variables shell-default-shell 'multi-term)
 (auto-completion :variables auto-completion-enable-snippets-in-popup nil)
 dash vinegar ibuffer syntax-checking c-c   csharp emacs-lisp vimscript markdown yaml html python)
```

**Comment by TheBB** [comment]
All this investigation pinpointing where the error comes from and *still* people come *here* to report it first. I really don't get it.

**Comment by GreyGhostIX** [comment]
My reasoning is that some people, like me, check these issues first when they encounter a problem. I'm thought that having the issue and a potential workaround doccumented here would be helpful to others and improve its visibility. I appologize if this is crowding the real issues that need your attention. If you think this is innapropriate I'll close this and not add errors outside the scope of spacemacs in the future. 

Thanks for everything you do here.

**Comment by TheBB** [comment]
No, it's not inapproriate. It's just that it ought to be accompanied with an actual report to the place where it matters and a link to it.

**Comment by GreyGhostIX** [comment]
Very good. [Link to issue on persp-mode repo.](https://github.com/Bad-ptr/persp-mode.el/issues/46)

**Comment by TheBB** [comment]
Thanks!

**Comment by GreyGhostIX** [comment]
The issue with persp-mode has been fixed!
