### ISSUE TITLE
clang autocompletion is really slow

### ISSUE THREAD

**Issue by cneira** [syl20bnr/spacemacs#7203]
#### Description
clang-autocomplete is slow, typing a class object the autocompletion of member functions takes around 7 or more seconds to display the autocompletion menu and there is no progress indicator to reflect that is actually trying to autocomplete

#### Reproduction guide

Enable clang autocompletion in C++ layer

*Observed behaviour:*
clang-autocomplete is slow, typing a class object the autocompletion of member functions takes around 7 or more seconds to display the autocompletion menu.

*Expected behaviour:*
It should take around a second.

#### System Info
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git
                 (c-c   :variables c-c  -enable-clang-support t)
                 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
                 syntax-checking version-control)
```

**Comment by TheBB** [comment]
Yes, clang is slow. It has to parse the entirety of your file and all the included files every time you type something. There's nothing to do about this. If you need faster C/C++ auto-completion consider using a server solution like ycmd that can retain information.

**Comment by cneira** [comment]
Thank you very much. Will Rtags be included in the C++ layer ?

**Comment by TheBB** [comment]
Probably, eventually. There's a long-standing open PR and @BinaryKhaos seems interested in working on it.
