### ISSUE TITLE
Smartparens is not installing and excludes anyway

### ISSUE THREAD

**Issue by shahinism** [syl20bnr/spacemacs#7204]
#### Description
Smartparens is not available in my freshly installed spacesmacs. `SPC t p` is undefined. I can install it but it'll be uninstalled on startup even if I add it to `dotspacemacs-additional-packages`. 

#### Reproduction guide
- Start Emacs
- Try to find smartparens-mode

#### System Info
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible c-c   dash django dockerfile emacs-lisp evil-commentary git github html javascript latex markdown react rust ruby-on-rails spell-checking syntax-checking sql typescript yaml
         (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
         (colors :variables colors-enable-rainbow-identifiers t)
         (org :variables org-enable-github-support t)
         (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save t)
         (ruby :variables ruby-version-manager 'rbenv)
         (ranger :variables ranger-show-preview t)
         (shell :variables shell-default-height 30 shell-default-position 'bottom)
         (version-control :variables version-control-global-margin t))
```

**Comment by TheBB** [comment]
Can you reproduce on develop?

**Comment by NJBS** [comment]
This is as expected, you are using the `spacemacs-base` distribution which does not include smartparens. You can switch to the full distribution of spacemacs (which includes smartparens) by changing your `dotspacemacs-distribution` to `'spacemacs` in your `.spacemacs` file.

The `develop` branch offers some additional granularity when using `spacemacs-base` that unfortunately isn't currently available on `master`.

**Comment by TheBB** [comment]
Oh, I'm blind. Thanks.

**Comment by shahinism** [comment]
Oh, thanks.
