### ISSUE TITLE
Confusing layer installation instructions

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#7206]
We used to have confusing installation instructions for layers, instructing users to do stuff like:

``` elisp
(setq-default dotspacemacs-configuration-layers '(org))
```

This was confusing, so we changed the instruction, for example: https://github.com/syl20bnr/spacemacs/blob/463be7916cefd8eb47e5949d4e480ca4b8be9237/layers/+emacs/org/README.org#layer

However, some confusing instructions still remain, specifically when regarding layer variables. I did not go through all the layers READMEs, but at least org layer and auto-completion layer suffer from this. Examples:
- [in org layer](https://github.com/syl20bnr/spacemacs/blob/463be7916cefd8eb47e5949d4e480ca4b8be9237/layers/+emacs/org/README.org#revealjs-support):

``` elisp
(setq-default dotspacemacs-configuration-layers
 '((org :variables org-enable-reveal-js-support t)))
```
- [in auto-completion layer](https://github.com/syl20bnr/spacemacs/blob/463be7916cefd8eb47e5949d4e480ca4b8be9237/layers/%2Bcompletion/auto-completion/README.org#tooltips):

``` elisp
(setq-default dotspacemacs-configuration-layers
  '((auto-completion :variables
                    auto-completion-enable-help-tooltip t)))
```

Example of confusion on gitter chat: https://gitter.im/syl20bnr/spacemacs?at=57eb775c857ab70f7d49ac1d

It probably sounds like I'm nagging, but It'd be nice if someone got around to finding all instances of such documentation bugs and fix them :smile:

**Comment by TheBB** [comment]
Do we have a good example for variables?

**Comment by bmag** [comment]
Not sure what you meant by "do we have", but In the dotfile template, `the shell` layer is commented-out together with layer variables:
```elisp
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
```

**Comment by TheBB** [comment]
I meant, are there some examples of documentation that explain how to add `:variables` adequately so that we can copycat that for the rest of the layers?

**Comment by bmag** [comment]
A quick `ag -Gorg$ :variables` brought me to javascript layer, which seems ok:
https://github.com/syl20bnr/spacemacs/blob/c42a08a842e40bad6f482266cebe450b27af743d/layers/%2Blang/javascript/README.org#tern
```org
** Tern
To make tern re-use the server across multiple different editing sessions (thus
creating multiple =.tern-port= files for each document you have open [[http://ternjs.net/doc/manual.html][see here
for more details]]):

The variables provided below can be set when adding the =javascript=
configuration layer, as detailed in [[file:../../../doc/DOCUMENTATION.org::Setting%20configuration%20layers%20variables][this]] section of the documentation.

#+BEGIN_SRC emacs-lisp
  (javascript :variables javascript-disable-tern-port-files nil)
#+END_SRC

Windows users may need to set the variable =tern-command= in order for emacs to
locate and launch tern server successfully. See [[https://github.com/syl20bnr/spacemacs/issues/5733][this open issue for more
details]]. The variable can be set when adding the =javascript= configuration
layer:

#+BEGIN_SRC emacs-lisp
  (javascript :variables tern-command '("node" "/path/to/tern/bin/tern"))
#+END_SRC
```

**Comment by d12frosted** [comment]
Every layer lives it's own life in terms of README 😸
