### ISSUE TITLE
Saving layouts by name `SPC l S` broken

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#7207]
#### Description :octocat:

Save layouts by names is broken.

#### Reproduction guide :beetle:
- Start Emacs
- Create a layout: `SPC l 2`, press `y` and give some name (e.g., `foobar`)
- Save the layout: `SPC l S`, choose `foobar` and press enter.

*Observed behaviour:* :eyes: :broken_heart:

Instead of saving you'll see the following error: `Wrong type argument: keymapp, nil`

*Expected behaviour:* :heart: :smile:

Allow the user to choose further layouts and then after finishing, choose a filename and save.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. cf951a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml extra-langs emacs-lisp ranger
     (python :variables nose-capture nil python-test-runner 'pytest pytest-cmd-flags "")
     ipython-notebook
     (shell :variables shell-pop-autocd-to-working-dir nil)
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
     (syntax-checking :variables syntax-checking-enable-by-default t)
     haskell latex git org c-c   html javascript colors lua markdown ibuffer
     (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
     (window-purpose :variables purpose-default-layout-file "~/.emacs.d/.cache/purpose-layouts/ "))
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
>     <<BACKTRACE IF RELEVANT>>

It's relevant. Don't worry. I have you covered.

    Debugger entered--Lisp error: (wrong-type-argument keymapp nil)
      lookup-key(nil [C-return])
      persp-prompt("to save" t "Home" t)
      persp-save-to-file-by-names()

As you can see the error originates from persp-mode code, so this should be reported upstream.

**Comment by TheBB** [comment]
@jluttine Please close issues when they are fixed.

**Comment by jluttine** [comment]
Yep, sorry!
