### ISSUE TITLE
Company: An error occurred in auto-begin

### ISSUE THREAD

**Issue by abhi18av** [syl20bnr/spacemacs#7209]
Hii @syl20bnr  and the Spacemacs team

I'm trying to setup the cljs/clj REPL with the inf-clojure mode on Spacemacs.

After some guidance from [ClojureScript wiki](https://github.com/clojure/clojurescript/wiki/Emacs-&-Inferior-Clojure-Interaction-Mode) , the [Planck REPL setup](http://www.planck-repl.org/emacs.html)  and README.md from `inf-clojure` repo I've set it up as following  

``` lisp
(defun cljs-node-repl ()
  (interactive)
  (let ((default-directory "~/.emacs.d/private/snippets/cljs_repl/"))
    ;(shell-command "ls")
  (run-clojure "lein trampoline run -m clojure.main node_repl.clj")))
```

So, the basic thing is working fine but I keep getting this error 

```
Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of file.
Company: An error occurred in auto-begin
Company: backend company-capf error "Wrong type argument: listp, WARNING:" with args (candidates de)
Company: An error occurred in auto-begin
Company: backend company-capf error "Wrong type argument: listp, WARNING:" with args (candidates def)
```

which means the company backend isn't setup correctly, I guess. Could you please tell me how to correct this?

Thanks :)

**Comment by mahinshaw** [comment]
@abhi18av The clojure layer makes no use of `inf-clojure`. Rather `cider` is used for repl interaction and completion
