### ISSUE TITLE
Avy should merge/replace with the classic '/' search command.

### ISSUE THREAD

**Issue by fausterjames** [syl20bnr/spacemacs#7210]
The search command should be replaced by avy, save the letter n and N to keep the native next and last motion and appart from that just replace every first char in matches by a letter that you just have to hit to jump to it. Basically merge all the commands avy-goto-char, word, line into just the search matches.

Maybe it would just be sufficient to add a little thing to the search function : `if search string is 1 char long then avy-goto-char, and av-goto-word otherwise`

For the search results that are off screen it would just react like the search command.

**Comment by TheBB** [comment]
Disagree, these two things are too different.

> For the search results that are off screen it would just react like the search command.

Yeah this doesn't sound great, I don't want my searching to behave completely different just based on what I'm looking for is visible or not.
