### ISSUE TITLE
ahs-forward/backward bound to M-<left>/<right> in org-mode?

### ISSUE THREAD

**Issue by 3rd3** [syl20bnr/spacemacs#7211]
Did Spacemacs change this key binding?

**Comment by bmag** [comment]
For me `M-<left>` and `M-<right>` are `org-metaleft` and `org-metaright`. Besides, what is `auto-highlight-forward`? That doesn't exist (at least on my setup), perhaps you got the name wrong?

**Comment by TheBB** [comment]
No, nothing changed.

**Comment by gleber** [comment]
I lost these keybindings in general when I switched to version 0.200 from an unspecified older version (it was somewhere on master branch, probably close to 0.104). I am trying to re-enable this.

**Comment by bmag** [comment]
Repeating my comments from gitter, for future reference: (slightly modified)
The removal is intentional: https://github.com/syl20bnr/spacemacs/tree/e6357a5ea35f5ad03c446b7f55871779da62e7ae/layers/+spacemacs/spacemacs-editing-visual/packages.el#L54-L56
This code should add the keys back, and can go in `user-config`:
```elisp
(with-eval-after-load 'auto-highlight-symbol
  (define-key auto-highlight-symbol-mode-map (kbd "M-<left>") #'ahs-backward)
  (define-key auto-highlight-symbol-mode-map (kbd "M-<right>") #'ahs-forward)
  (define-key auto-highlight-symbol-mode-map (kbd "M-S-<left>") #'ahs-backward-definition)
  (define-key auto-highlight-symbol-mode-map (kbd "M-S-<right>") #'ahs-forward-definition))
```

**Comment by gleber** [comment]
I came to depend on these commands available globally, so I've added this to my `.spacemacs` file:

```
(defun dotspacemacs/user-config ()
  ;; snip
  (global-set-key (kbd "M-<left>") #'ahs-backward)
  (global-set-key (kbd "M-<right>") #'ahs-forward)
  (global-set-key (kbd "M-S-<left>") #'ahs-backward-definition)
  (global-set-key (kbd "M-S-<right>") #'ahs-forward-definition)
  ;; snip
)
```
