### ISSUE TITLE
python-start-or-switch-repl doesn't work

### ISSUE THREAD

**Issue by elvis-sik** [syl20bnr/spacemacs#7212]
#### Description :octocat:
`python-start-or-switch-repl` answers with `No inferior Python process running.`
This was working up to a few days ago. I cannot pinpoint exactly what triggered the behavior.

#### Reproduction guide :beetle:
- Start Emacs
- Open python buffer
- `SPC m s i` or `SPC m '`

*Observed behaviour:* :eyes: :broken_heart:
`No inferior Python process running.`

*Expected behaviour:* :heart: :smile:
ipython REPL opening.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. cf951a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv auto-completion better-defaults emacs-lisp git markdown
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
     spell-checking smex syntax-checking version-control cscope gtags semantic xkcd github
     (c-c   :variables c-c  -default-mode-for-headers 'c-mode c-c  -enable-clang-support t)
     extra-langs html javascript shell-scripts sql yaml
     (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save t)
     ipython-notebook
     (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "gibiansky" haskell-enable-shm-support t haskell-completion-backend 'intero)
     evil-commentary
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-repeat-scope "visible")
     react idris scheme ranger selectric evil-cleverparens speed-reading asm octave pandoc systemd extra-langs ess)
```

**Comment by bmag** [comment]
duplicate: #2872 #6628 
PR pending: #7070

**Comment by d12frosted** [comment]
Closing this issues as duplicate in favour of #6628. 

Anyway, @elvis-sik, could you please check if #7070 fixes your issue?
