### ISSUE TITLE
Layout saving/loading does not recover saved layout state

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#7214]
#### Description :octocat:

Layout saving and/or loading is broken in develop: the loaded layout is not in
the state it was saved in. No problems in master.

#### Reproduction guide :beetle:
- Start Emacs
- Create a new layout `SPC l 2`, give it a name (e.g., `foobar`). The layout is automatically activated.
- Modify the layout, for instance, `SPC w 2` and open some files to both windows with `SPC f f`.
- Save the layout `SPC l s` to a file `foobar`.
- Quit emacs `SPC q q`.
- Start Emacs.
- Load the layout file you saved `SPC l L`.
- Switch to the layout `SPC l 2`.

*Observed behaviour:* :eyes: :broken_heart:

The loaded layout is just the home buffer.

*Expected behaviour:* :heart: :smile:

The loaded layout should be in the state in which it was saved, that is, two
windows with the files open in them.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. cf951a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml extra-langs emacs-lisp ranger
     (python :variables nose-capture nil python-test-runner 'pytest pytest-cmd-flags "")
     ipython-notebook
     (shell :variables shell-pop-autocd-to-working-dir nil)
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
     (syntax-checking :variables syntax-checking-enable-by-default t)
     haskell latex git org c-c   html javascript colors lua markdown ibuffer
     (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
     (window-purpose :variables purpose-default-layout-file "~/.emacs.d/.cache/purpose-layouts/ "))
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
Can confirm this is an issue, and I have a suspicion. @jluttine please test if this work-around recovers the layout's window state: before saving with `SPC l s`, change the active layout with `SPC l 1`, and only then do `SPC l s`.

Another thing: please attach the contents of the saved layout file `foobar`. It should contain the file names and other layout parameters, so make sure there isn't any sensitive info there.

I will have more time to look into it during the weekend.

**Comment by jluttine** [comment]
Thanks, I'll do that today. Perhaps the other issue you're refering is this: https://github.com/syl20bnr/spacemacs/issues/7105? I suppose that was a different issue.

**Comment by bmag** [comment]
No, not #7105

**Comment by deb0ch** [comment]
I can confirm both the bug and your workaround @bmag :smile:

**Comment by jluttine** [comment]
Contents of the layout file `foobar`:

```
((def-persp nil nil (def-wconf (((min-height . 4) (min-width . 10) (min-height-ignore . 3) (min-width-ignore . 4) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 72) (min-pixel-width . 90) (min-pixel-height-ignore . 54) (min-pixel-width-ignore . 36) (min-pixel-height-safe . 18) (min-pixel-width-safe . 18)) leaf (pixel-width . 952) (pixel-height . 972) (total-width . 105) (total-height . 54) (normal-height . 1.0) (normal-width . 1.0) (buffer "*spacemacs*" (selected . t) (hscroll . 0) (fringes 8 8 nil) (margins nil) (scroll-bars nil 0 t nil 0 t) (vscroll . 0) (dedicated) (point . 229) (start . 1)))) (def-params ((gui-eyebrowse-last-slot . 1) (gui-eyebrowse-current-slot . 1) (gui-eyebrowse-window-configs (1 (((min-height . 4) (min-width . 10) (min-height-ignore . 3) (min-width-ignore . 4) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 72) (min-pixel-width . 90) (min-pixel-height-ignore . 54) (min-pixel-width-ignore . 36) (min-pixel-height-safe . 18) (min-pixel-width-safe . 18)) leaf (pixel-width . 952) (pixel-height . 972) (total-width . 105) (total-height . 54) (normal-height . 1.0) (normal-width . 1.0) (buffer "*spacemacs*" (selected . t) (hscroll . 0) (fringes 8 8 nil) (margins nil) (scroll-bars nil 0 t nil 0 t) (vscroll . 0) (dedicated) (point . 229) (start . 1))) "")))) t nil nil) (def-persp "foobar" ((def-buffer "foo.txt" "/home/jluttine/foo.txt" text-mode) (def-buffer "bar.txt" "/home/jluttine/bar.txt" text-mode)) (def-wconf (((min-height . 4) (min-width . 20) (min-height-ignore . 3) (min-width-ignore . 8) (min-height-safe . 1) (min-width-safe . 4) (min-pixel-height . 72) (min-pixel-width . 180) (min-pixel-height-ignore . 54) (min-pixel-width-ignore . 72) (min-pixel-height-safe . 18) (min-pixel-width-safe . 36)) hc (pixel-width . 952) (pixel-height . 990) (total-width . 106) (total-height . 55) (normal-height . 1.0) (normal-width . 1.0) (combination-limit) (leaf (pixel-width . 475) (pixel-height . 990) (total-width . 53) (total-height . 55) (normal-height . 1.0) (normal-width . 0.5) (buffer "foo.txt" (selected) (hscroll . 0) (fringes 8 8 nil) (margins nil) (scroll-bars nil 0 t nil 0 t) (vscroll . 0) (dedicated) (point . 1) (start . 1))) (leaf (last . t) (pixel-width . 477) (pixel-height . 990) (total-width . 53) (total-height . 55) (normal-height . 1.0) (normal-width . 0.5) (buffer "bar.txt" (selected . t) (hscroll . 0) (fringes 8 8 nil) (margins nil) (scroll-bars nil 0 t nil 0 t) (vscroll . 0) (dedicated) (point . 1) (start . 1))))) (def-params ((gui-eyebrowse-last-slot . 1) (gui-eyebrowse-current-slot . 1) (gui-eyebrowse-window-configs (1 (((min-height . 4) (min-width . 10) (min-height-ignore . 3) (min-width-ignore . 4) (min-height-safe . 1) (min-width-safe . 2) (min-pixel-height . 72) (min-pixel-width . 90) (min-pixel-height-ignore . 54) (min-pixel-width-ignore . 36) (min-pixel-height-safe . 18) (min-pixel-width-safe . 18)) leaf (pixel-width . 952) (pixel-height . 972) (total-width . 105) (total-height . 54) (normal-height . 1.0) (normal-width . 1.0) (buffer "*spacemacs*" (selected . t) (hscroll . 0) (fringes 8 8 nil) (margins nil) (scroll-bars nil 0 t nil 0 t) (vscroll . 0) (dedicated) (point . 229) (start . 1))) "")))) nil nil nil))
```

**Comment by jluttine** [comment]
And yes, the workaround works for me too.

**Comment by bmag** [comment]
Can you confirm that the issue is fixed by #7231?
The other issue I was thinking about was #6979.

**Comment by jluttine** [comment]
@bmag Thanks, I tested and it seems to work! :+1:

**Comment by bmag** [comment]
@jluttine excellent. Just one thing - the PR isn't merged yet, so the issue isn't fixed yet in Spacemacs, so the issue report should remain open.

**Comment by jluttine** [comment]
@bmag I'm currently using your PR. I'm not sure if my issue is related to that or if it's more general. Anyway, the order of layouts sometimes changes when I load a file containing multiple layouts. The order is different every other time I load the file, and every other time it's the original order.

**Comment by bmag** [comment]
@jluttine the PR has been merged already, and is part of the current release. Can you open a new issue, with reproduction steps?

**Comment by jluttine** [comment]
Yep, I opened a new issue: https://github.com/syl20bnr/spacemacs/issues/7396. I think this issue has been solved now. At least the original issue doesn't appear on develop anymore.
