### ISSUE TITLE
Develop is FAR ahead of master.

### ISSUE THREAD

**Issue by peterhoeg** [syl20bnr/spacemacs#7215]
Are there any plans to release all the good stuff in ```develop``` soon?

Many new features are flowing into develop but it looks like a formal release is far away.

Example: the ```pdf-tools``` layer was added 8 months ago but is not part of a release.

**Comment by TheBB** [comment]
Yes, this has been repeated several times in the gitter channel. A release is coming very soon, just need to wait for @syl20bnr.

**Comment by peterhoeg** [comment]
Sorry, I don't follow the gitter channel. What I wouldn't give for a mailing list.... Thanks for the update.

**Comment by d12frosted** [comment]
> Yes, this has been repeated several times in the gitter channel.

Not only in Gitter channel, but in some other issues on GitHub as well. But yeah, I think for people who don't follow project too closely it's hard to figure the state of develop branch. But on other hand we have [milestones](https://github.com/syl20bnr/spacemacs/milestones).

**Comment by tobimensch** [comment]
> 0.106 will be 0.200 instead since there is a lot of breaking changes

A video documenting those changes would be great.

**Comment by d12frosted** [comment]
@tobimensch I haven't heard about anyone willing to 'document' changes in video, but at least there is always good old [Change log](https://github.com/syl20bnr/spacemacs/blob/develop/CHANGELOG.develop).

**Comment by TheBB** [comment]
> Sorry, I don't follow the gitter channel. What I wouldn't give for a mailing list.... Thanks for the update.

Me too, but @syl20bnr refuses.

**Comment by syl20bnr** [comment]
0.200 is out so we can close this issue :-)
