### ISSUE TITLE
spacemacs python layer anaconada mode show doc

### ISSUE THREAD

**Issue by RushPu** [syl20bnr/spacemacs#7216]
How to jump back after press <spc m h h> anaconada mode show doc? Thanks~

**Comment by TheBB** [comment]
You just quit the window with `q`, no?

**Comment by RushPu** [comment]
No, I try to use ctrl-o to jump back, but no work

**Comment by TheBB** [comment]
I'm not sure I follow. anaconda-mode-show-doc opens a buffer in a different window, the place you came from is still there on screen.

**Comment by RushPu** [comment]
In my emacs, anaconda-mode-show-doc opens a buffer and replace my python file buffer, I can not use ctrl-o jump back python buffer(ex cmd shows:Buffer is read-only,buffer<anaconda>)

**Comment by TheBB** [comment]
You should be able to use `q`. Did you try this in develop?

**Comment by RushPu** [comment]
Thanks~
