### ISSUE TITLE
Warning (with-editor): Cannot determine a suitable Emacsclient

### ISSUE THREAD

**Issue by xmaillard** [syl20bnr/spacemacs#7222]
#### Description
I just installed emacs-plus as indicated in the OSX instruction, started emacs-plus and I get the warning bellow:

> Warning (with-editor): Cannot determine a suitable Emacsclient
> 
> Determining an Emacsclient executable suitable for the
> current Emacs instance failed.  For more information
> please see https://github.com/magit/magit/wiki/Emacsclient.

#### Reproduction guide
- Start Emacs
- nothing more

*Observed behaviour:*

Warning (with-editor): Cannot determine a suitable Emacsclient

Determining an Emacsclient executable suitable for the
current Emacs instance failed.  For more information
please see https://github.com/magit/magit/wiki/Emacsclient.

*Expected behaviour:*

No error, no warning

#### System Info
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion bepo better-defaults clojure command-log deft emacs-lisp emoji finance games git gnus html ibuffer jabber javascript markdown org osx php ranger restclient
                 (shell :variables shell-default-shell 'eshell)
                 shell-scripts sql swift syntax-checking version-control xkcd yaml)
```

#### Backtrace
```
```

**Comment by d12frosted** [comment]
Hey,

What is the value of `$PATH` and how exactly do you run Emacs?

**Comment by xmaillard** [comment]
Hey,

Launching via 'Launchpad'
My $PATH from what ? Emacs or shell ?

**Comment by xmaillard** [comment]
Notice that whatever way I choose to launch GNU emacs, it ends up with this warning (either form launchpad or a shell)

PATH (from emacs via SPC : getenv RET PATH): /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/pkg/sbin:/opt/pkg/bin:/usr/local/sbin

PATH from shell (terminal): /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/pkg/sbin:/opt/pkg/bin

Also, I have OS X layer installed and added into the spacemacs layers list.

**Comment by xmaillard** [comment]
Update. 

I removed my .spacemacs file and did a: touch .spacemacs
Launched emacs again, the warning is now gone ...

Still trying to find out which layer (since I am pretty sure now it is due a layer) is doing wrong things on me.

**Comment by xmaillard** [comment]
Fixed. This warning came from magic. Actually, magit was not the culprit but home-brew which went wrong.
Fixed:
```
brew cleanup
brew link emacs-plus
```

And voila.
