### ISSUE TITLE
Symbol’s value as variable is void: with-editor-file-name-history-exclude

### ISSUE THREAD

**Issue by yilihong** [syl20bnr/spacemacs#7225]
Error in dotspacemacs/user-config: Symbol’s value as variable is void: with-editor-file-name-history-exclude

Anyone has the same issue when starting up? I am on the newest release of 25.1.1

**Comment by d12frosted** [comment]
Do you have `with-editor-file-name-history-exclude` somewhere in your `dotspacemacs/user-config`?

**Comment by yilihong** [comment]
actually I don't.

**Comment by strongh** [comment]
I also ran into this. I don't know what the significance of `with-editor-file-name-history-exclude`, but the git layer seems to work fine after adding `(setq with-editor-file-name-history-exclude 1)` to `.spacemacs`.

**Comment by shellbj** [comment]
Try reinstalling `with-editor`; `magit` recently starting using a newer version.

See: https://github.com/magit/magit/issues/2824
