### ISSUE TITLE
How to add custom mnemonic keybindings?

### ISSUE THREAD

**Issue by adamcavendish** [syl20bnr/spacemacs#7226]
How can I give a message to show in helm so that it gives a hint when I use keybindings instead of just "+prefix"?

Thx.

**Comment by TheBB** [comment]
Helm? Do you mean which-key?

**Comment by adamcavendish** [comment]
Could you please elaborate on it... I don't fully understand.

What I meant was:

![which-key](https://cloud.githubusercontent.com/assets/1346161/19201905/7a931d30-8d02-11e6-9942-8daa423b7a00.jpeg)

```
f -> +prefix
p -> +projectile-command-map
```

I hope to customize the "+prefix" into somewhat like "+mykeymap".

**Comment by LdBeth** [comment]
```
(spacemacs/declare-prefix "]" "bracket-prefix")
(spacemacs/set-leader-keys "]]" 'double-bracket-command)
```
This example cab be seen in [Spacemacs documentation 11. Binding Keys](http://spacemacs.org/doc/DOCUMENTATION.html#binding-keys)
You can customize it in your layers.

**Comment by d12frosted** [comment]
@LdBeth thanks for sharing solution. 

@adamcavendish this should answer your question 😸 Closing this issue, but let us know if it's still relevant for you.

**Comment by adamcavendish** [comment]
@LdBeth Thx. However, `spacemacs/declare-prefix` seems to work only with `SPC`. I cannot use it to define other custom key bindings. i.e.:

```
(spacemacs/declare-prefix "C-c w" "MyPrefix")
(spacemacs/set-leader-keys "C-c w ]" 'forward-char)
```

**Comment by adamcavendish** [comment]
I found it, after reading the `spacemacs/declare-prefix`

The example

```
(spacemacs/declare-prefix "C-c w" "MyPrefix")
(spacemacs/set-leader-keys "C-c w ]" 'forward-char)
```

should be written in the following way instead:

```
(which-key-add-key-based-replacements "C-c w" "MyPrefix")
(global-set-key (kbd "C-c w ]") 'forward-char)
```
