### ISSUE TITLE
Weird line spacing on high dpi screen

### ISSUE THREAD

**Issue by Towerism** [syl20bnr/spacemacs#7233]
I use the same spacemacs configuration on two of my systems. One is a high dpi 1080p screen and the other a high dpi 4k screen. On the 1080p screen I don't see this problem. On the 4k screen, there is weird line spacing between some lines and not others (variable declarations, directories, etc.). I can't figure out why so I can disable it.

**Comment by jasonm23** [comment]
What's the font you're using?

Try setting the font height attribute in Emacs.

```
(set-face-attribute 'default nil :height  n)
```

`n` as 190 works well for me on _larger than HD_ displays.

**Comment by Towerism** [comment]
Thanks, but I believe that is going to affect all lines. The weird line spacing only appears on certain lines, such as those with an org header on it.

**Comment by Towerism** [comment]
I finally figured out what the problem was. I did not have Adobe Source Code Pro font package installed. I'm not sure why I didn't have a warning in my home buffer about this. But installing the fonts solved the issue. Finally, after all this time! :)
