### ISSUE TITLE
Void function toc-org-enable when using spacemacs-base and spacemacs-org

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#7235]
#### Description :octocat:
When `spacemacs-org` is used, and using a minimal Spacemacs config, opening an Org file causes a `toc-org-enable` void function error.
`spacemacs-org` layer assumes `toc-org-enable` is always defined (see https://github.com/syl20bnr/spacemacs/blob/ac31e45c155d4cb3d365e609794504c69b9924bf/layers/+spacemacs/spacemacs-org/packages.el#L76), but that isn't always true. The function is defined in `core/tools/spacefmt/toc-org.el` (see https://github.com/syl20bnr/spacemacs/blob/ac31e45c155d4cb3d365e609794504c69b9924bf/core/tools/spacefmt/toc-org.el#L355).

#### Reproduction guide :beetle:
- Have a Spacemacs configuration with the same layer list and distribution as in System Info section below.
- Start Emacs
- Open an Org file

*Observed behaviour:* :eyes: :broken_heart:
Org is not properly loaded (some settings are missing), and an error message in the echo area:
> File mode specification error: (void-function toc-org-enable)

*Expected behaviour:* :heart: :smile:
No error, and Org is properly loaded.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. ac31e45)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((spacemacs-editing :packages
                    (avy expand-region))
 (spacemacs-evil :packages
                 (evil-lisp-state evil-iedit-state evil-nerd-commenter evil-numbers evil-surround))
 spacemacs-layouts
 (spacemacs-ui :packages
               (restart-emacs))
 ivy auto-completion emacs-lisp git markdown org spacemacs-org
 (latex :variables latex-enable-auto-fill t latex-enable-folding t))
```

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-function toc-org-enable)
  toc-org-enable()
  run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
  run-mode-hooks(org-mode-hook)
  org-mode()
  set-auto-mode-0(org-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer config.org> "c:/Users/bar/Desktop/emacs/spacedirs/base/config.org" nil nil "c:/Users/bar/Desktop/emacs/spacedirs/base/config.org" (1688849861441643 9362352))
  find-file-noselect("c:/Users/bar/Desktop/emacs/spacedirs/base/config.org" nil nil nil)
  find-file("c:/Users/bar/Desktop/emacs/spacedirs/base/config.org")
  #[257 "\304\305!!r\306\307\310\311\312!\313\"\314$\216\315@\316\"\210	\205

**Comment by bmag** [comment]
Update: this is happening also with a regular install, with or without `org` layer enabled: (the branch says "nil", but it's really latest develop)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: nil (rev. 72d87de)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

**Comment by bmag** [comment]
The work-around is to exclude the package `toc-org`.

**Comment by rgrinberg** [comment]
I'm unable to reproduce this on a clean, minimal install with or without spacemacs-org.

**Comment by bmag** [comment]
@rpglover64 thank you, I updated my packages (`toc-org` was one of them) and the issue has disappeared. Must have been fixed upstream.
