### ISSUE TITLE
Magit commit causes error when fci-mode is not used

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#7236]
#### Description :octocat:
Commiting with Magit causes an error when `fci-mode` is not defined. The cause is that `git` layer hooks `fci-mode` into `git-commit-mode-hook` even when the package `fill-column-indicator` is not used. (see https://github.com/syl20bnr/spacemacs/blob/ac31e45c155d4cb3d365e609794504c69b9924bf/layers/+source-control/git/packages.el#L116)

#### Reproduction guide :beetle:
- Have a Spacemacs config that doesn't use `fill-column-indicator` package 
- Start Emacs
- In a git projects with changes, open magit-status (`SPC g s`)
- open a commit (`c c`)

*Observed behaviour:* :eyes: :broken_heart:
Error message in the echo area: 
> Git failed ... [Hit $ to see buffer *magit-process: spacemacs-base for details]

Pressing `$` shows that the error was:
```
*ERROR*: Symbol’s function definition is void: fci-modeerror: There was a problem with the editor '"c:/Users/bar/Desktop/emacs/programs/emacs-w64-25.1/bin/emacsclient.exe"'.
Please supply the message using either -m or -F option.
```

*Expected behaviour:* :heart: :smile:
Commit buffer opens and I'm able to commit the changes.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. ac31e45)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((spacemacs-editing :packages
                    (avy expand-region))
 (spacemacs-evil :packages
                 (evil-lisp-state evil-iedit-state evil-nerd-commenter evil-numbers evil-surround))
 spacemacs-layouts
 (spacemacs-ui :packages
               (restart-emacs))
 ivy auto-completion emacs-lisp git markdown org
 (spacemacs-org :packages
                (not toc-org))
 (latex :variables latex-enable-auto-fill t latex-enable-folding t))
```

**Comment by TheBB** [comment]
Should be fixed in master.
