### ISSUE TITLE
SPC-SPC undefined 0.200

### ISSUE THREAD

**Issue by tobimensch** [syl20bnr/spacemacs#7248]
#### Description :octocat:
SPC-SPC undefined

#### Reproduction guide :beetle:
- Update from 0.105.22 to 0.200 using git
- Keep the old configuration
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
- Try SPC-SPC which according to the documentation
  should now be the same as SPC-: used to be,
  but it isn't

*Expected behaviour:* :heart: :smile:
- SPC-SPC should be the same as M-x

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. c788da7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp c-c   git markdown org
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking version-control themes-megapack)
```

**Comment by NJBS** [comment]
I can't seem to reproduce this. Can you try updating your `.spacemacs` file using `SPC f e D`?

**Comment by tobimensch** [comment]
@NJBS:

Had to change dotspacemacs-command-key. Shouldn't something like that be set to nil or be commented out by default, so that changes from a newer version trickle down more easily?

Thank you.

**Comment by d12frosted** [comment]
> Had to change dotspacemacs-command-key

What was it before?

**Comment by tobimensch** [comment]
@d12frosted
":"

**Comment by d12frosted** [comment]
Ok. Anyways, closing this issue as it the initial question is resolved. 

P. S. `dotspacemacs-emacs-command-key` is the new name of `dotspacemacs-command-key`, but latter is an alias of `dotspacemacs-emacs-command-key`. So I would advice you to rename that variable.
