### ISSUE TITLE
paste-transient-state not working

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#7249]
#### Description :octocat:
I changed `dotspacemacs-enable-paste-transient-state` variable from `nil` to `t` in `dotspacemacs/init`, but see no effect.

*Observed behaviour:* :broken_heart:
Pressing <kbd>p</kbd> again will paste the last yanked text on the kill ring again.

*Expected behaviour:* :heart:
from Docs:
> Pressing <kbd>p</kbd> again will replace the pasted text with the previous yanked (copied) text on the kill ring.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. ac31e45)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm auto-completion better-defaults emacs-lisp git markdown org shell
                (shell :variables shell-default-position 'full)
                syntax-checking version-control python github javascript)
```

**Comment by bmag** [comment]
Repro steps, observed behavior? I have a transient state after pressing `p` with non-nil `dotspacemacs-enable-paste-transient-state`.

**Comment by bmag** [comment]
Aha, the expected behavior isn't how the TS works anymore. `C-j`/`C-k` replace the pasted text with older/newer yanks.

**Comment by xged** [comment]
Works fine then :). I leave issue open for Docs to be updated.

**Comment by bmag** [comment]
Sure. Can you point to the docs that need to be updated?

**Comment by xged** [comment]
Commands/Editing/Paste_text/Paste_Transient-state

**Comment by TheBB** [comment]
Should be fixed in master.
