### ISSUE TITLE
spacemacs/alternate-buffer to not ignore shell

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#7250]
I want that `spacemacs/alternate-buffer` (`SPC TAB`) would not ignore *shell* buffers.

If I go to the *shell* via `SPC ...` from buffer, associated to a different path then the *shell* path, I would lose data (text) from the *shell* buffer, which is usually some important *traceback* massage :/. (my `shell-default-position` is `'full`)

**Comment by TheBB** [comment]
> I want that spacemacs/alternate-buffer would not ignore shell buffers.

Add a regexp for the buffer name to `spacemacs-useful-buffers-regexp`.

> I would lose data (text) from the shell buffer

Set `shell-pop-autocd-to-working-dir` to `nil`.

**Comment by xged** [comment]
@TheBB 
> Add a regexp for the buffer name to spacemacs-useful-buffers-regexp.

Currently such a regexp (`"\\*\\(ansi-term\\|eshell\\|shell\\|terminal.+\\)\\*" "\\*scratch\\*"`) already includes *shells* (?), therefor *shells* should not be ignored?

**Comment by deb0ch** [comment]
This is also most likely related to #7104.

IMHO the best way to handle this would be to simply *ignore* `buffer-predicate` in `spacemacs/alternate-buffer`.

**Comment by xged** [comment]
@deb0ch How to do it?

**Comment by deb0ch** [comment]
I don't really know, I haven't looked into it. I assume the function `spacemacs/alternate-buffer` in `~/.emacs.d/layers/+distributions/spacemacs-base/funcs.el` should be modified and loose a few lines.

**Comment by TheBB** [comment]
@xged Okay, I see, the regexp is a bit wrong. Should work now, can you confirm?

**Comment by xged** [comment]
@TheBB Works now - shells are not ignored by `SPC TAB`!

**Comment by deb0ch** [comment]
looks like I was mistaken, sorry for the noise

**Comment by uruk1993** [comment]
It seems ignore the org agenda buffer  which is the most important buffer for me.

**Comment by deb0ch** [comment]
Even after including it in `spacemacs-useful-buffers-regexp` ?

**Comment by uruk1993** [comment]
Well, after including it in `spacemacs-useful-buffers-regexp` all things works well.
