### ISSUE TITLE
command-key ";" in vim mode

### ISSUE THREAD

**Issue by honza** [syl20bnr/spacemacs#7255]
#### Description :octocat:

When using the vim mode of Spacemacs, setting `dotspacemacs-command-key` or
`dotspacemacs-emacs-command-key` seems to have no effect.  Before the `0.200`
release, I was able to set the `command-key` to `;`, meaning I could avoid
having to hit `shift+;` to enter the vim command line menu.

The vim-related code that made this work was removed in 58e5241c8d96da0a2cf04d4897a74c9d1250875e.

#### Reproduction guide :beetle:
- Start Emacs
- Set `dotspacemacs-command-key` to `;`
- Reload emacs config with `SPC f e R`

*Observed behaviour:* :eyes: :broken_heart:
- Hitting `;` in normal mode doesn't enter command menu

*Expected behaviour:* :heart: :smile:
- Hitting `;` in normal mode does enter command menu

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp c-c++ git github haskell shell-scripts purescript puppet ansible markdown notmuch org python clojure javascript html react go rust sql extra-langs syntax-checking version-control yaml
                 (spell-checking :variables spell-checking-enable-by-default nil))
```

#### Backtrace :paw_prints:
```
none
```

**Comment by deb0ch** [comment]
Also experience that bug

**Comment by syl20bnr** [comment]
Fixed in 0.200.1 :-)

**Comment by honza** [comment]
Thank you!

**Comment by lijoantony** [comment]
I'm still facing this bug on 0.200.4@24.5.1 (spacemacs)

**Comment by honza** [comment]
@lijoantony Did you rename the config key name in your `~/.spacemacs` file?

**Comment by lijoantony** [comment]
@honza I have the below line in my ~/.spacemacs inside dotspacemacs/init function.
 
`dotspacemacs-command-key ";"`

**Comment by honza** [comment]
@lijoantony That's your problem. It should be `(dotspacemacs-ex-command-key ";")`.

**Comment by lijoantony** [comment]
@honza Thank you very much!
