### ISSUE TITLE
How to toggle transparency in a terminal

### ISSUE THREAD

**Issue by brezal** [syl20bnr/spacemacs#7262]
Hi. I started trying out Spacemacs over the weekend and it's been nice.

I came across M-m T T for toggling transparency, and it works in the standalone gui version of emacs, but from within a terminal, it doesn't seem to work. I'm using iTerm 3.0.9.

**Edit:** I meant *terminal emulator*, sorry about the confusion.

**Comment by TheBB** [comment]
Of course, the terminal is a text-only interface, and has no concept of things like transparency. You will have to configure the terminal emulator itself to enable transparency.

**Comment by brezal** [comment]
Hi @TheBB, thanks for responding so quickly. The terminal is transparent, but when I start spacemacs using `emacs -nw`, the editor's background is a pretty black with no transparency and no way of toggling the background to be transparent.

**Comment by jasonm23** [comment]
I assume the color theme `default` face isn't matching the default background color for the terminal.

If you set them to match, it should become transparent.

```
(set-face-attribute 'default nil :background  COLOR)
```

where color is the same as the terminal background.  

BTW What is the terminal emulator you're using?

**Comment by TheBB** [comment]
> I'm using iTerm 3.0.9.

**Comment by brezal** [comment]
@jasonm23 
(set-face-attribute 'default nil :background  "black") just sets the background to black. The background color of the term emulator is `#000000`, but there is transparency.

1. Has anyone successfully been able to have transparency in a terminal emulator?
2. Has anyone successfully used the transparency feature in iTerm?

**Comment by jasonm23** [comment]
Sorry, I just tried this out, my other solution was untested.

Instead of 

```
(set-face-attribute 'default nil :background "black")
```

Try 

```
(set-face-attribute 'default nil :background nil)
```

Simpler (perhaps just more direct)

```
(set-face-background 'default nil)
```

This seems to work for me.

<img width="723" alt="screen shot 2016-10-09 at 1 54 47 am" src="https://cloud.githubusercontent.com/assets/71587/19214963/6ceb87dc-8dc3-11e6-8f9d-024ed3fde5fb.png">

#7288 is for GUI of course.

**Comment by brezal** [comment]
<img width="1920" alt="screen shot 2016-10-08 at 9 15 05 pm" src="https://cloud.githubusercontent.com/assets/2381998/19217588/5b090a2a-8d9c-11e6-8350-8d905a1855f0.png">
@jasonm23 Thanks for sticking with me on this! I tried these commands with my version of spacemacs (0.200) just now. The screenshot shows me typing out one of the commands again. Both were tried several times, but the end result is that pretty default black background. Also, in the screenshot, the edges of the screen show the surrounding terminal is transparent.

I'll keep tinkering on my end. Any other ideas?

**Comment by brezal** [comment]
Adding this to `~/.emacs.d/init.el` gave me a transparent emacs:

```
(defun on-after-init ()
  (unless (display-graphic-p (selected-frame))
    (set-face-background 'default "unspecified-bg" (selected-frame))))

(add-hook 'window-setup-hook 'on-after-init)
```
That code came from http://stackoverflow.com/questions/19054228/emacs-disable-theme-background-color-in-terminal

Now I need to figure out how to toggle it with a shortcut.
