### ISSUE TITLE
spacemacs/ert-run-tests-buffer runs too many tests

### ISSUE THREAD

**Issue by bmag** [syl20bnr/spacemacs#7266]
#### Description :octocat:
`spacemacs/ert-run-tests-buffer` runs all defined tests, instead of just the tests defined in the current buffer.

#### Reproduction guide :beetle:
- Start Emacs
- open an Elisp buffer with tests
- press `, t b`: the buffer's tests are executed
- open another Elisp buffer with tests
- press `, t b`

*Observed behaviour:* :eyes: :broken_heart:
The tests of both buffers are executed.

*Expected behaviour:* :heart: :smile:
Only the tests of the second buffer are executed.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: fix-ivy-persp-restriction (rev. 2fe339d)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((spacemacs-editing :packages
                    (avy expand-region smartparens))
 (spacemacs-editing-visual :packages
                           (auto-highlight-symbol))
 (spacemacs-evil :packages
                 (evil-lisp-state evil-iedit-state evil-nerd-commenter evil-numbers evil-surround evil-exchange))
 spacemacs-layouts
 (spacemacs-ui :packages
               (restart-emacs))
 (spacemacs-ui-visual :packages
                      (golden-ratio fill-column-indicator))
 ivy auto-completion emacs-lisp git markdown org
 (spacemacs-org :packages
                (not toc-org))
 (latex :variables latex-enable-auto-fill t latex-enable-folding t)
 imenu-list)
```

**Comment by TheBB** [comment]
Should be fixed in master.
