### ISSUE TITLE
haskell mode: gtags doesn't work

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#7268]
#### Description :octocat:

gtags doens't work in haskell mode

I'm somewhat confused by the presence of the gtags functions in the mode menu, given that `global`, according to its own web site, doesn't support Haskell.
#### Reproduction guide :beetle:
- Start Emacs
- Open haskell source file
- Navigate to a function call site
- Press `SPC m g d`

_Observed behaviour:_ :eyes: :broken_heart:
If the gtags files are missing, they are _sometimes_ generated. After that, nothing.

If the gtags files are already present, nothing happens.

_Expected behaviour:_ :heart: :smile:
I expect that I'm transported to the definition of the function I've placed the cursor on.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: c-c  -add-irony (rev. b14e317)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(html
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash evil-commentary evil-snipe git gtags helm mu4e syntax-checking vim-powerline
 (c-c   :variables c-c  -enable-clang-support t c-c  -enable-irony-support t)
 clojure emacs-lisp python
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell")
 scheme dockerfile latex markdown org pandoc yaml archlinux clipboard-fix)
```

**Comment by jacktasia** [comment]
FWIW, `dumb-jump` should work with Haskell. That said, I don't know if spacemacs is configured by default to fallback to, or use, it with Haskell.

**Comment by rgrinberg** [comment]
So the correct course of action here would be to remove the gtags functions from the haskell menu right? Can't see what can be done until global supports haskell.

**Comment by magthe** [comment]
@rgrinberg Yes, I think that's the correct course of action at this point.
