### ISSUE TITLE
haskell mode (intero): no way to jump back from a definition

### ISSUE THREAD

**Issue by magthe** [syl20bnr/spacemacs#7269]
#### Description :octocat:
Jumping to definition using the `spacemacs/jump-to-definition` doesn't allow one to jump back.

#### Reproduction guide :beetle:
- Start Emacs
- Open a haskell source file
- Navigate to a function call site
- Jump to the definition using `SPC m g g`
- Become irritated at the lack of a jump-back function (`SPC m g p` doesn't work)

*Observed behaviour:* :eyes: :broken_heart:
No such function to be found... nothing happens on `SPC m g p`.

*Expected behaviour:* :heart: :smile:
I really expect there to be a way to jump back, and it should work like the `SPC m g d`/`SPC m g p` pair (or `Ctrl-]`/`Ctrl-T` in vim for that matter).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: c-c  -add-irony (rev. b14e317)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html
 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 dash evil-commentary evil-snipe git gtags helm mu4e syntax-checking vim-powerline
 (c-c   :variables c-c  -enable-clang-support t c-c  -enable-irony-support t)
 clojure emacs-lisp python
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell")
 scheme dockerfile latex markdown org pandoc yaml archlinux clipboard-fix)
```

**Comment by TheBB** [comment]
`C-o` doesn't work?

**Comment by magthe** [comment]
Actually it does, which means `Ctrl-T` works too.

I'll write this up as a ticket on the confusion that is code navigation then. In haskell there's

* gtags - found under mode-specific commands (`SPC m g d` / `SPC m g p`) that uses its own jump stack.
* intero - go-to-definition is found under mode-specific commands, but there's no function for jumping back there, uses the evil jump stack
* evil tags - uses the standard `Ctrl-]` and `Ctrl-T`, uses the evil jump stack

Anyway, this is probably by design, so I'll just close it.
