### ISSUE TITLE
Hybrid mode: no message is shown when switching to insert state

### ISSUE THREAD

**Issue by andresilva** [syl20bnr/spacemacs#7271]
#### Description :octocat:

When using hybrid mode and entering "insert" state there's no message displayed
on the minibuffer. The message is shown when entering visual state though.
#### Reproduction guide :beetle:
- Start Emacs
- Use hybrid mode
- Switch to "insert" state

_Observed behaviour:_ :eyes: :broken_heart:

No message is printed on the minibuffer.

_Expected behaviour:_ :heart: :smile:

A message should be printed on the minibuffer showing the current state (`-- HYBRID --`).
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(helm better-defaults auto-completion spell-checking syntax-checking
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      osx org emoji git
      (version-control :variables version-control-diff-tool 'diff-hl)
      docker emacs-lisp html javascript markdown restclient ruby rust scala shell-scripts yaml)
```

**Comment by bmag** [comment]
I'm seeing the same thing. Will investigate later today or tomorrow.

**Comment by bmag** [comment]
This one is very hard to debug. I did discover that replace-state (`R`) doesn't display a message either, even in stock emacs + evil-mode. I will research a bit more and report the issue upstream.

**Comment by bmag** [comment]
Reported upstream: https://bitbucket.org/lyro/evil/issues/719/entering-replace-state-doesnt-show-replace
