### ISSUE TITLE
Compiling Spacemacs First install

### ISSUE THREAD

**Issue by GiacomoSilli** [syl20bnr/spacemacs#7273]
I'm on Windows, I try to install spacemacs,
finding these errors during compilation

http://pastebin.com/ZubSGnU9

I tried deleting the cache folder and elpa, but always the same problem.
Any tips?

**Comment by TheBB** [comment]
Not errors but warnings. They're caused by byte-compilation of packages. Completely normal.

**Comment by GiacomoSilli** [comment]
And what about that one:

`php-extras (error: (wrong-type-argument stringp nil)) php-extras (error: (wrong-type-argument stringp nil))`

Can't solve that

**Comment by d12frosted** [comment]
That problem is probably not from compile buffer. Please, try running emacs with `--debug-init` option.

**Comment by GiacomoSilli** [comment]
I run emacs --debug-init from emacs/bin/ in console, but its opened normally without any errors or something
