### ISSUE TITLE
evil-unimpaired 

### ISSUE THREAD

**Issue by asdyjd** [syl20bnr/spacemacs#7274]
#### Description :octocat:
It can't install evil-unimpaired package.
How to install it manually?
I have tried deleting all files of .emacs.d/.cache/.
It hints me every time:
(Spacemacs) --> installing package: evil-unimpaired@spacemacs-evil... [1/1]
Cloning https://github.com/melpa/melpa.git to d:/emacs/.emacs.d/.cache/quelpa/melpa
Cannot load evil-unimpaired

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey better-defaults
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
                 (chinese :variables chinese-enable-avy-pinyin t)
                 cscope emacs-lisp html org python syntax-checking javascript ycmd)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by d12frosted** [comment]
> Spacemacs branch: nil (rev. nil)

Could you please try on `master` or on `develop`? And please let me know which branch exactly you use.

**Comment by duckdodger** [comment]
I'm on the master branch and I can reproduce the same error. Using Emacs 24.5.1.

**Comment by d12frosted** [comment]
Could you please start with `--debug-init` option passed to `emacs`?

**Comment by duckdodger** [comment]
This is what I got in *Messages*:
```
(Spacemacs) --> installing package: evil-unimpaired@spacemacs-evil... [3/3]
Fetcher: file
Source: nil

File: /home/hari/.emacs.d/.cache/quelpa/build/evil-unimpaired/evil-unimpaired.stamp
Saving file /home/hari/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20161004.191603.el...
Wrote /home/hari/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20161004.191603.el
Wrote /home/hari/.emacs.d/.cache/quelpa/packages/evil-unimpaired-readme.txt
Generating autoloads for evil-unimpaired.el...done
Saving file /home/hari/.emacs.d/elpa/evil-unimpaired-0.1pre0.20161004.191603/evil-unimpaired-autoloads.el...
Wrote /home/hari/.emacs.d/elpa/evil-unimpaired-0.1pre0.20161004.191603/evil-unimpaired-autoloads.el
(No files need saving)
Checking /home/hari/.emacs.d/elpa/evil-unimpaired-0.1pre0.20161004.191603... [2 times]
Compiling /home/hari/.emacs.d/elpa/evil-unimpaired-0.1pre0.20161004.191603/evil-unimpaired-pkg.el...done
Wrote /home/hari/.emacs.d/elpa/evil-unimpaired-0.1pre0.20161004.191603/evil-unimpaired-pkg.elc
Checking /home/hari/.emacs.d/elpa/evil-unimpaired-0.1pre0.20161004.191603...
Compiling /home/hari/.emacs.d/elpa/evil-unimpaired-0.1pre0.20161004.191603/evil-unimpaired.el...
Checking /home/hari/.emacs.d/elpa/evil-unimpaired-0.1pre0.20161004.191603...
Done (Total of 1 file compiled, 1 failed, 1 skipped)

```

This is the error I'm getting in *Compile Log*:
`evil-unimpaired.el:32:1:Error: Cannot open load file: no such file or directory, dash`

**Comment by asdyjd** [comment]
I'm on Master branch.

**Comment by asdyjd** [comment]
I found the problem.
The git is corrupt.
Thank you.

**Comment by joehillen** [comment]
@asdyjd Can you be more specific? How did you fix it?

**Comment by duckdodger** [comment]
Oh wait, I think his problem was entirely different from mine. I think I should probably open a new issue for my problem.

**Comment by asdyjd** [comment]
I run the command "git clone https://github.com/syl20bnr/spacemacs .emacs.d".
It hints me something like it can't load cert in d:\program files\git\**********.
I delete the whole git directory and use the git in cygwin.
It successed.
I don't know why the git is corrupt.
@joehillen

**Comment by d12frosted** [comment]
@duckdodger hm... that kind of error is exactly why we now install `evil-unimpaired` using file fetcher. Ok, try removing `~/.emacs.d/.cache/quelpa` and `~/.emacs.d/elpa/[version/]evil-unimpaired-*`. And then start again.

**Comment by duckdodger** [comment]
@d12frosted I did as you said, but I'm getting the same error.

**Comment by d12frosted** [comment]
@duckdodger do you have file `/home/hari/.emacs.d/elpa/evil-unimpaired-0.1pre0.20161004.191603/evil-unimpaired.el`?

**Comment by duckdodger** [comment]
Yeah, I do. I have evil-unimpaired.el, evil-unimpaired-autoloads.el, evil-unimpaired-pkg.el and evil-unimpaired-pkg.elc

**Comment by d12frosted** [comment]
Does it work fine on second run? 

If someone is experiencing this issue and it stops from normal using of Spacemacs, just add `evil-unimpaired` to list of excluded packages in your `.spacemacs` file.

**Comment by duckdodger** [comment]
@d12frosted Yes, indeed it works fine on second run. So I don't need to be worried?

**Comment by kyleholzinger** [comment]
I had this as well, deleting the whole cache directory fixed it for me.

**Comment by unclechu** [comment]
Happened with me after clean install on Fedora 25. Removing just `~/.emacs.d/.cache` haven't helped at all. But removing both `~/.emacs.d/.cache` and `~/.emacs.d/elpa` solved it for me.

**Comment by CGDS** [comment]
Manually adding `dash` to the configuration layers in `~/.spacemacs` resolved this for me on a fresh install

**Comment by openist** [comment]
Th key for me was also removing both ~/.emacs.d/.cache and ~/.emacs.d/elpa for some reason.

**Comment by joaopaulo23** [comment]
I just disabled it. I prefeer emacs sintax. To disable you just need to go on the file
/layers/+spacemacs/spacemacs-evil/packages.el and comment the lines
241 and line 243.

**Comment by d12frosted** [comment]
If you wish to disable package, it's better to add it to `dotspacemacs-excluded-packages` inside of your `.spacemacs` file 😸

**Comment by joaopaulo23** [comment]
Sorry, i didn't had time to learn spacemacs properly, i was at the end of a college period. That was the fastest solution that i found, so i tried to share. My bad.

**Comment by d12frosted** [comment]
Sorry, didn't mean to offend you. I just wanted to share 'official' solution for disabling packages from being loaded and used, so you don't run into update issues in future. 

> i didn't had time to learn spacemacs

That's ok 😸 Spacemacs is a huge project. I really recommend to read through [FAQ](http://spacemacs.org/doc/FAQ.html). Btw, there is a [note about disabling packages](http://spacemacs.org/doc/FAQ.html#disable-a-package-completely) 😸

**Comment by kyleholzinger** [comment]
If you want to learn more, I really liked [this evil mode guide](https://github.com/noctuid/evil-guide) that I found too!

**Comment by kirisky** [comment]
I had this problem as well, the "cannot load evil-unimpaired."
My OS is Win10 Home Edition. But I found I didn't install the git. Then I installed the git. The problem is gone.
So, there is a little advice. If you found this issue, maybe you should first check if you installed the git.
