### ISSUE TITLE
Updater fails to get new version and update to 0.200

### ISSUE THREAD

**Issue by deb0ch** [syl20bnr/spacemacs#7275]
**If you experienced issues with updating, maybe this thread is a good place to report it.**

#### Description :octocat:
Updater fails to check for new version and to update to 0.200 when pressing the `update spacemacs` button.

Tested on a clean install of 0.105.22 and 0.105.21, after nuking elpa and .cache directories. ~/.emacs.d was clean (nothing present in `git status`)

When specifying the precise version number `0.200` when prompted I was able to successfully update.

On another note, I don't remember precisely but at some point I first noticed this issue on 0.105.22 and having an error along the lines of `wrong version number: v0.200`.

Other users also reported problems updating spacemacs in the gitter chat, and for some of them even specifying the version number didn't work.

#### Reproduction guide :beetle:
- Start a clean install of Spacemacs (0.105.22 or 0.105.21)
- No update proposed whereas one is available. In `*messages*`: `Unable to check for new version`
- press `Update spacemacs` in the Home buffer
- When prompted `Version (default nil [latest]):` just press enter, as you don't know in advance the version number
- in `*messages*`:
```
Getting version information...
An error occurred while switching to version 
```

*Observed behaviour:* :eyes: :broken_heart:
- No proposed update
- Impossible to update without knowing the precise version number

*Expected behaviour:* :heart: :smile:
- An update is proposed, as it is actually available
- Pressing the update button should update spacemacs

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 5001e21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

#### Backtrace :paw_prints:
```
Getting version information...
An error occurred while switching to version 
```

**Comment by TheBB** [comment]
@syl20bnr You tagged it `v0.200` instead of `v0.200.0`.

**Comment by deb0ch** [comment]
Hahahahaha I'm sure that's it then, it damn well looks like it :laughing:

**Comment by d12frosted** [comment]
@TheBB did you fix the name?

**Comment by TheBB** [comment]
I think we need a new commit to make a new tag.

**Comment by TheBB** [comment]
Hang on, I'm on it.

**Comment by TheBB** [comment]
Yep, works now.

**Comment by syl20bnr** [comment]
You can delete the release and the tag by clicking on them.

Recreating the release afterward should fix the issue.
Sorry for the bad tag format, I'm getting rusty it seems :-)

**Comment by d12frosted** [comment]
> @syl20bnr You tagged it v0.200 instead of v0.200.0.

Ah, I misread it. I've seen that the tag is named `v0.200` and thought that you already fixed it. But since it should be `v0.200.0`.... welp, thanks for fixing it ASAP!

**Comment by nixmaniack** [comment]
This might not be related to the current issue but https://github.com/syl20bnr/spacemacs/releases/latest is still pointing to `0.105.22`. Also the `Release Notes` for `v0.200.0` seems to be missing from [this](https://github.com/syl20bnr/spacemacs/releases ) page.

**Comment by TheBB** [comment]
@nixmaniack Fixed
