### ISSUE TITLE
Typescript layer should not overwrite flycheck customization

### ISSUE THREAD

**Issue by Peluko** [syl20bnr/spacemacs#7276]
Hello.

Typescript layer overrides the `flycheck-check-syntax-automatically` customization by setting a hook on `typescript-mode` and `web-mode`.

Is this necessary?

**Comment by TheBB** [comment]
Probably not. https://github.com/syl20bnr/spacemacs/pull/7277

**Comment by TheBB** [comment]
Should be fixed in master.
