### ISSUE TITLE
Spaceline does not work with pdf-tools

### ISSUE THREAD

**Issue by duckdodger** [syl20bnr/spacemacs#7278]
#### Description :octocat:
Spaceline does not work with pdf-tools. It gives me this error whenever I am in Pdf-View mode:
``` 
Error during redisplay: (eval (spaceline-ml-main)) signaled
(invalid-function pdf-view-current-page) 
```
I should also note that I get the following warning from time to time, since I'm not sure if it's related.
```
PNG warning: Interlace handling should be turned on when using png_read_image
```

#### Reproduction guide :beetle:
- Start Emacs
- Install pdf-tools dependencies
- Install the pdf-tools layer
- Open a PDF document.

*Observed behaviour:* :eyes: :broken_heart:
Spaceline is completely blank in Pdf-View mode, i.e., no letters and no characters and keeps throwing an error. 

*Expected behaviour:* :heart: :smile:
Spaceline should work as expected.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion c-c   emacs-lisp ess latex markdown org pdf-tools ranger
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking)
```

#### Backtrace :paw_prints:

![screenshot_20161004_191045](https://cloud.githubusercontent.com/assets/17142033/19076405/45fcb7d2-8a66-11e6-91e6-75b262fc1018.png)

**Comment by TheBB** [comment]
https://github.com/TheBB/spaceline/pull/99

**Comment by TheBB** [comment]
Fixed upstream.
