### ISSUE TITLE
Adding Clojure to org-babel-load-languages

### ISSUE THREAD

**Issue by drewokane** [syl20bnr/spacemacs#7282]
Are there any plans to add Clojure to the list of org-babel languages? Particularly since it seems pretty straightforward. Not trying to be annoying but curious and would be willing to help.

**Comment by TheBB** [comment]
There's no org-babel specific config in Spacemacs at the moment. If you want to contribute, be my guest.

**Comment by drewokane** [comment]
I can whip up a quick pull request in that case.

**Comment by TheBB** [comment]
Should be fixed in master.
