### ISSUE TITLE
Web browser layer

### ISSUE THREAD

**Issue by yetatore** [syl20bnr/spacemacs#7284]
Hi. There is any layer to do web browsing **inside** spacemacs?
If not, can I use MELPA to install eww without conflicting anything?

Note: I'm new to spacemacs (with few past emacs experience).

Thanks!

**Comment by TheBB** [comment]
> There is any layer to do web browsing inside spacemacs?

No.

> If not, can I use MELPA to install eww without conflicting anything?

[Yes](http://spacemacs.org/doc/DOCUMENTATION.html#without-a-layer).

**Comment by yetatore** [comment]
Oh! Thanks for that fast response!
