### ISSUE TITLE
Fill column indicator color is nearly identical to the background color when connected to an emacs daemon with a client

### ISSUE THREAD

**Issue by fardog** [syl20bnr/spacemacs#7285]
#### Description :octocat:
**Note:** This was edited after more information became available. Original text is in ~~strikethrough~~ and new text is in _italics_.

Fill column indicator ~~does not appear~~ _is a nearly identical color to the background_ in an emacsclient session connected to an emacs daemon. This was as of 0.200, previous versions did not display this issue. _This is using the default spacemacs dark theme._

~~Toggling the fill-column indicator has no effect (a message is displayed in the
command area, but no column appears).~~

Using the same configuration but not via emacsclient, the fill-column indicator
works correctly.

This appears to be independent of mode. I've seen the issue in Python, JS, and
Markdown files.

#### Reproduction guide :beetle:
- Start Emacs in Daemon mode with `emacs --daemon`
- Connect to running daemon with `emacsclient -nc -a ""`
- Toggle fill column indicator with `SPC t f`

*Observed behaviour:* :eyes: :broken_heart:
Fill column indicator is ~~not displayed~~ _nearly the same color as the background_.

*Expected behaviour:* :heart: :smile:
Fill column indicator is displayed _in the standard yellow-ish color_.

#### System Info :computer:
- OS: gnu/linuxdoes not appear 
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp clojure python javascript markdown go html django groovy yaml
            (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-complete-with-key-sequence "fd")
            syntax-checking spell-checking version-control git github
            (shell :variables shell-default-shell 'ansi-term))
```

**Comment by bmag** [comment]
Sounds like something that might not be related to Spacemacs. Can you try reproducing it with stock Emacs? Repro might be something like this: (didn't try it myself)
- `emacs -Q --daemon`
- `emacsclient -nc -a ""`
- `M-x package-initialize` (loads the `*-autoload.el` files in elpa directory)
- `M-x fci-mode`

**Comment by TheBB** [comment]
I can't reproduce this on my Spacemacs, at least.

**Comment by fardog** [comment]
@bmag so I've got a bit more information:

- it turns out the fill-column indicator is not missing: it's just almost exactly the same color as the background; I had to hook up to a different monitor to notice it was there. i'm using the default theme
- it's definitely spacemacs related; it was working with the previous version of spacemacs, and then broke on the 0.200 update; no other configuration changed between them

a bit more about my config:

- i have fci-mode set to always be enabled via a `(add-hook 'prog-mode-hook 'fci-mode)` in my `.spacemacs`
- i can override the color by setting `fci-rule-color` variable to a value like `"#ff0000"`, and then toggling off/on the fci
- setting that color in my `.spacemacs` doesn't work though; its like its being overridden elsewhere. in my `.spacemacs` under my user-config, i was trying `(setq-default fci-rule-color "#ff0000")` with no effect

I don't know enough about the emacs/spacemacs init process to understand why setting that variable in my user-config is ignored, unfortunately.

I'm going to update the title of this bug to more accurately reflect the issue, given this new info.

**Comment by bmag** [comment]
> i can override the color by setting fci-rule-color variable to a value like "#ff0000", and then toggling off/on the fci

That's good, this is how it's supposed to work. We know the feature isn't broken.

> I don't know enough about the emacs/spacemacs init process to understand why setting that variable in my user-config is ignored, unfortunately.

Spacemacs sets `fci-rule-color` after `dotspacemacs/user-init` and before `dotspacemacs/user-config`, in `spacemacs-ui-visual/init-fill-column-indicator`. It sets the value to `"#D0BF8F"`.

> setting that color in my .spacemacs doesn't work though; its like its being overridden elsewhere. in my .spacemacs under my user-config, i was trying `(setq-default fci-rule-color "#ff0000")` with no effect

That's odd. Likely your setting isn't executed, or it is overridden later. Please type `SPC h d v fci-rule-color` after connecting with the client and report what's the value of `fci-rule-color`.

Other things to try:
- if you use a different theme, is the ruler still nearly-invisible? (if the color isn't caused by spacemacs, the theme author may want to fix this)
- do you have any `custom-set-variables` section that changes `fci-rule-color`? It is generated automatically under some circumstances.
- put a debugging message right before the `setq`, and check if it appears in the `*Messages*` buffer. For example:
```elisp
(message "-- reached before setq --")
(setq-default fci-rule-color "#ff0000")
(message "-- reached after setq --")
```

I'm on a Windows machine and having trouble running the daemon, so I can't debug (or reproduce) it for now. I'll try again next week when I'm back on my Ubuntu machine.

**Comment by bmag** [comment]
Update: I can't reproduce this bug on develop branch on my Ubuntu machine, even with the layers from the repro guide.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: develop (rev. 72d87de)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp clojure python javascript markdown go html django groovy yaml
      (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-complete-with-key-sequence "fd")
      syntax-checking spell-checking version-control git github
      (shell :variables shell-default-shell 'ansi-term))
```

**Comment by fardog** [comment]
@bmag thanks tons for checking; its hugely appreciated. after updating to 0.200.1 this morning the problem went away, although I don't see anything specific that would have changed its behavior. the issue was occurring both on my home and work laptop (which use the same configs from my dotfiles) but has resolved on both.

closing this. again, thanks so much.
