### ISSUE TITLE
[Q] how to bind a vim arpeggio?

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7287]
I have this on my vimrc:

```viml
" my custom pageups and pagedowns. 
nmap <leader>d LztM
nmap <leader>u HzbM
```

how can I specify the same bind in spacemacs? 

I mean, how do I say that I want a specific bind to translate to a series of evil/vim like keypresses, not just one?

**Comment by TheBB** [comment]
```elisp
(spacemacs/set-leader-key (kbd "d") (kbd "LztM"))
```

**Comment by ninrod** [comment]
@TheBB thank you very much.
