### ISSUE TITLE
suggestion: enable which-function by default

### ISSUE THREAD

**Issue by cocodrino** [syl20bnr/spacemacs#7289]
Hi guys, coming from intellij I found this pretty useful

``` lisp
(which-function-mode)
(setq-default header-line-format
              '((which-func-mode ("" which-func-format " "))))
(setq mode-line-misc-info
            ;; We remove Which Function Mode from the mode line, because it's mostly
            ;; invisible here anyway.
            (assq-delete-all 'which-func-mode mode-line-misc-info))

```

please check this.. with this function you get the info similar to intellij idea...is really cool

**Comment by bmag** [comment]
Interesting idea about the header line. Just a note: `semantic` layer (and package) has a similar feature for showing current function name in the header line, so any implementation should take that into account.

**Comment by agzam** [comment]
This will only work for emacs-lisp, am I right?

**Comment by TheBB** [comment]
No, which-function-mode works for many languages.

**Comment by idlethread** [comment]
Bump on this old issue. Is there a preferred way in spacemacs to do this?
