### ISSUE TITLE
evil-iedit-state should be lazy loaded in more modes

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#729]
[In this part](https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L730) ```evil-iedit-state``` is only loaded in ```prog-modes``` and ```markdown-mode```. This means that e.g. if the first file I open is an ```xml``` file then <kbd>SPC s e</kbd> gives an error since the function is not defined.

It might be better to load this the first time any file is opened, since it is probably not feasible to keep a list of all mode hooks where it should be loaded?

**Comment by syl20bnr** [comment]
Fixed with #730
