### ISSUE TITLE
org-indent-mode not automatically activated when switching to org-mode

### ISSUE THREAD

**Issue by Odie** [syl20bnr/spacemacs#7290]
#### Description :octocat:
Just updated to 0.200 from 0.150.x.
It appears that org-indent-mode is not automatically activated when switching to org-mode.

#### Reproduction guide :beetle:
- Start Emacs
- Open up a .org file
- Start level 1 or level 2 heading
- Start typing some text

*Observed behaviour:* :eyes: :broken_heart:
Text is always aligned to the left of the window regardless of the heading level it's under.
Manually enabling org-indent-mode fixes this.

*Expected behaviour:* :heart: :smile:
Text should be indented to the same indentation as the heading levels.
org-indent-mode should automatically be activated when switching to org-mode.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp clojure html markdown org osx spell-checking syntax-checking)
```

**Comment by NJBS** [comment]
Indeed, we've stopped turning it on by default as of bc5b7ec.

You'll have to enable it again by setting the variable in your user-config.

**Comment by Odie** [comment]
Okay, it's easy enough to enable again. 😄

I did a quick looking around to see why it was disabled. For anybody who might be wondering, please see:
  - #4693
  - #4692 
  - #2732

I understand it's hard to keep everyone happy with a project like this. However, I suspect this issue will cause a bit of confusion to org users who are upgrading from 0.150.x.

**Comment by punitsoni** [comment]
Sorry for a noob question. What do I need to add in my user-config to enable org-indent-mode for all org mode files?

**Comment by Odie** [comment]
Try adding this:

```elisp
  (use-package org
    :config
    (setq org-startup-indented t))
```

to user-config
