### ISSUE TITLE
Version check fails

### ISSUE THREAD

**Issue by avdv** [syl20bnr/spacemacs#7292]
#### Description
Hitting `Enter` on "Update Spacemacs" in the spacemacs buffer does not find the latest version.

This seems to be due to the fact that the latest release is tagged with v0.200 (as well as with v0.200.0). Here is the output of `git describe --tags --abbrev=0 --match=v\* checkversion/master FETCH_HEAD`:

```
v0.200
v0.200
```

Alas, that does not match the expected version format `x.x.x`.

*Possible fix*: use `--match=v*.*.*` to filter only tags with two dots.

#### Reproduction guide
- Start Emacs
- Click on the "Update Spacemacs" button

*Observed behaviour:*
It fetches the latest version information, but then it shows this prompt in the minibuffer:

```
Version (default nil [latest]): _
```
*Expected behaviour:*
Show proper version information 0.200.0, as the time of this writing.

#### System Info
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(asciidoc emacs-lisp git html javascript markdown python scala spell-checking version-control yaml)
```

**Comment by TheBB** [comment]
Closing as duplicate: https://github.com/syl20bnr/spacemacs/issues/7275

This is fixed already, as the v200.0 tag has been deleted. Unfortunately this doesn't help those who already pulled that tag. Delete it locally and you should be good to go.
