### ISSUE TITLE
Org going back to previous location after closing/re-opening the file

### ISSUE THREAD

**Issue by hicksy994** [syl20bnr/spacemacs#7296]
If I am in an org subtree and I close the buffer/close emacs, when I re-open the file I will go straight back to my previous location in the file. 

I asked on the #emacs IRC channel and apparently this is not default org mode behavior. Is there a package in the org layer causing this behavior? Or a function defined somewhere? I would quite like to disable this functionality.

**Comment by TheBB** [comment]
Uh, org is a red herring. Spacemacs does this with all files. It's the saveplace package, exclude that.

**Comment by hicksy994** [comment]
@TheBB Thanks, I only really noticed it with org because it looked weird with some subtrees open and some closed.
