### ISSUE TITLE
Whitespace highlighting (with `SPC t w`) seems to ignore the theme

### ISSUE THREAD

**Issue by jazzpi** [syl20bnr/spacemacs#7297]
#### Description :octocat:

Whitespace highlighting (with `SPC t w`) seems to ignore the theme
#### Reproduction guide :beetle:
- Start Emacs (with a default theme that configures whitespace highlighting, e.g. spacemacs-dark)
- Toggle whitespace highlighting with `SPC t w`

_Observed behaviour:_ :eyes: :broken_heart:
Spaces are displayed in orange/red, looks like it is from the default theme.

_Expected behaviour:_ :heart: :smile:
Spaces should be displayed according to the theme (e.g. in gray for spacemacs-dark theme).
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm auto-completion emacs-lisp syntax-checking
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
      (ycmd :variables ycmd-server-command
            '("python" "/home/jasper/dev/ycmd/ycmd")
            ycmd-force-semantic-completion t))
```
#### Workaround

Switching to a different theme and back again fixes the issue.

**Comment by bmag** [comment]
I can reproduce this behavior, and I found the cause: These lines in `spacemacs-base/init-whitespace`:
```elisp
(set-face-attribute 'whitespace-space nil
                    :background nil
                    :foreground (face-attribute 'font-lock-warning-face
                                                :foreground))
(set-face-attribute 'whitespace-tab nil
                    :background nil)
(set-face-attribute 'whitespace-indentation nil
                    :background nil)
```
Another suspicious setting from the same function:
```elisp
(set-face-attribute 'trailing-whitespace nil
                    :background
                    (face-attribute 'font-lock-comment-face
                                    :foreground))
```
Source: [layers/+distributions/spacemacs-base/packages.el](https://github.com/syl20bnr/spacemacs/blob/896180408ab51e230037ef4b921b2761e7645d3c/layers/+distributions/spacemacs-base/packages.el#L450)

I have no idea[1] why we're changing the faces, and we probably shouldn't be doing this. PR welcome.

[1] well, some of the built-in themes (e.g wombat) have a hideous background color for `whistespace-space` face, so maybe that's the reason. Still, not a good enough reason.

**Comment by bmag** [comment]
Maybe related: #1499
