### ISSUE TITLE
Can't use org-edit-special in org-mode with plantuml (puml-mode)

### ISSUE THREAD

**Issue by EMayej** [syl20bnr/spacemacs#7298]
#### Description :octocat:
Can't use org-edit-specil with plantuml

#### Reproduction guide :beetle:
- Start Emacs
- Open test.org
- Type in below text
```org
# BEGIN_SRC plantuml :file x.svg
  Alice -> Bob : Hello
# END_SRC
```
- `SPC m '` (which calls org-edit-special)

*Observed behaviour:* :eyes: :broken_heart:
emacs reports no plantuml-mode

*Expected behaviour:* :heart: :smile:
a new window opens with puml-mode

*Possible solution:*
https://github.com/skuro/puml-mode#integration-with-org-mode

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. cf951a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 clojure semantic dash emacs-lisp fasd git plantuml graphviz org osx ranger shell-scripts
 (python :variables python-test-runner 'pytest)
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking)
```

**Comment by Mitchicus** [comment]
Yes, and also for this layer it could be handy to document that you may need to set `puml-plantuml-jar-path`. I got tripped up on this when the layer was added and replaced my own config. 

I'll make a PR briefly to fix this issue
