### ISSUE TITLE
Org-agenda-list does not show todo

### ISSUE THREAD

**Issue by fer-git** [syl20bnr/spacemacs#7305]
#### Description :octocat:
Spacemacs does not show my scheduled todo list in org-agenda-list (Space a o a) even though I have specified org-agenda-files in .spacemacs.
This is what I put under dotspacemacs/user-config:
```elisp
  (with-eval-after-load 'org (setq org-agenda-files
                                   '("~/Sync/Orgzly Files/")))
```
This setup worked well when my spacemacs version was 0.105. It stops working after I update spacemacs to version 0.200.

My current work around after starting emacs is to execute the code above manually, which is to find spacemacs setting (Space f e d) and execute that code above (Ctrl x Ctrl e).
#### Reproduction guide :beetle:
- Start Emacs
- Open org-agenda-list (Space a o a)

*Observed behaviour:* :eyes: :broken_heart:
Org-Agenda buffer opened and displayed none of my todo list.

*Expected behaviour:* :heart: :smile:
Org-Agenda buffer opened and displayed all my scheduled todo list stored in org files.
The location of org files have been specified in org-agenda-files.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git markdown
                 (org :variables org-enable-github-support t)
                 (python :variables python-enable-yapf-format-on-save t auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
                 spell-checking syntax-checking
                 (haskell :variables haskell_enable-hindent-style "chris-done" haskell-enable-shm-support t)
                 themes-megapack
                 (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh")
                 (clojure :variables clojure-enable-fancify-symbols t)
                 (scala :variables scala-enable-eldoc-mode t scala-auto-insert-asterisk-in-comments t))
```

#### Backtrace :paw_prints:
```
```

**Comment by TheBB** [comment]
So to be clear, the *actual* issue here is that the above code no longer sets `org-agenda-files` as it should? What is it set to instead?

**Comment by fer-git** [comment]
Today I change the location of 
```elisp
  (with-eval-after-load 'org (setq org-agenda-files
                                   '("~/Sync/Orgzly Files/")))
```
at the top in dotspacemacs/user-config. Now org-agenda-list can display my todo list.

I am not sure why the position of the code matters, as I have no problem with it in 0.105.
