### ISSUE TITLE
go and ctags key binding conflict

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#7306]
go layer uses `SPC m g c` for `go-coverage` and gtags layer `SPC m g c`  for `helm-gtags-create-tags`  

Can we use `SPC m g C` for  `helm-gtags-create-tags` ? This is not a function that you would call often and it will help to avoid similar conflicts.

**Comment by deb0ch** [comment]
Or maybe use `SPC m g C` for go coverage and keep `SPC m g c` consistent with all the other layers ?

**Comment by JAremko** [comment]
@deb0ch  I mean use `SPC m g C` `helm-gtags-create-tags`  for all layers.  This way it will have less chance to collide with a layer bindings ( `SPC m g C` is less likely to be used than  `SPC m g c` +  `SPC m g c` can be used for something that a user would like to use often)

**Comment by JAremko** [comment]
It looks like some other layers (like Clojure)  are already using `SPC m g C` for their stuff. So it looks like we can go with changing  `go-coverage` key binding to  `SPC m g C` 

@TheBB  Mb this is `ready for work` ? also it's a bug(key binding conflict) fix.

**Comment by quicknir** [comment]
IMHO, no layer other than the one responsible for the major mode should be allowed to bind anything under the major mode prefix. As long as this is ok, you're going to have conflicts like this that have to be resolved ad hoc.

The correct fix would be to make the helm layer not bind anything. Instead, provide a function where you give it a prefix, and then the layer would bind all of its shortcuts under that prefix. Layers can then choose whether or not to call that function, and at which prefix. Consistency between layers would be nice but not at the expense of conflicts.

**Comment by JAremko** [comment]
@quicknir   Makes sense. Also we can detect collisions by parsing `spacemacs/set-leader-keys-for-major-mode` forms in the sources code or check if a key binding already exist during evaluation and warn if collision is detected. @syl20bnr

**Comment by syl20bnr** [comment]
Actually I went with the initial proposition by @JAremko which was to move create tags to `SPC m g C`.

In clojure layer `SPC m g c` was free so I moved `SPC m g C` to `SPC m g c`. Moreover `SPC m g c` was used in other layers than `go`. Finally as stated, the action of creating tags is not so common so it is a good candidate for a shifted key.
