### ISSUE TITLE
[Q] evil-escape question

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7307]
I want that when I press the ESC key, emacs gets me out of everyting. ivy buffers, hydras, helm, which-key, insert mode, magit buffers, you name it. 

So I was reading documentation about [evil-escape](https://github.com/syl20bnr/evil-escape) and found that I could do this:

`(global-set-key (kbd "ESC") 'evil-escape)` or
`(global-set-key (kbd "<ESC>") 'evil-escape)` or 
`(global-set-key "<ESC>" 'evil-escape)`

But something tells me that this could be a bad idea. Because if it were a good idea, it would be a default, right? 

So what am I'm missing here? 

thanks in advance.

**Comment by TheBB** [comment]
The global keymap has the lowest priority. That means any time escape is bound to something else in a higher priority keymap your evil-escape binding will be shadowed.

**Comment by ninrod** [comment]
ok @TheBB, thank you. so basically, this has no chance of working. thanks.
