### ISSUE TITLE
Evaluate node.js buffer in REPL(skewer)

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#7308]
Hi, how do I evaluate current node.js buffer in skewer REPL?

**Comment by Miciah** [comment]
#2979 / https://github.com/syl20bnr/spacemacs/commit/ba403b2df16763d9f6b7e43bb6c60d0d60f4b4e5 added the `SPC m s b` key binding to send the buffer contents to the skewer REPL; see [the javascript layer documentation on REPL (skewer-mode)](http://spacemacs.org/layers/+lang/javascript/README.html#repl-skewer-mode).  Does that resolve the issue?
