### ISSUE TITLE
add ivy support to bibtex layer

### ISSUE THREAD

**Issue by bdarcus** [syl20bnr/spacemacs#7309]
Add support for inserting citations as with `helm-bibtex`, but with ivy.

`Org-ref` does include an ivy version, but there seems to be some [problem with separating it out as a separate package](https://github.com/jkitchin/org-ref/issues/218). The author suggests:

> If helm is a deal breaker, I would suggest you run org-ref off the git repo and manage the packages yourself. You could use el-get for that.

**Comment by brabalan** [comment]
There is an `ivy-bibtex` package now: https://github.com/tmalsburg/helm-bibtex. Could it be used for that?

**Comment by bdarcus** [comment]
@brabalan it's been awhile since I've looked into the details, and I'm not comfortable enough with emacs and spacemacs to know for sure, but it does seem that `helm-bibtex` (well, `ivy-bibtex`) may have this functionality now (to browse bibliographies and insert citations into org and markdown documents).

**Comment by brabalan** [comment]
I think the issue is that one has to install helm to use helm-bibtex, even if one uses the ivy completion system. It would be great if ivy-bibtex was installed instead of helm-bibtex in that case.

**Comment by bdarcus** [comment]
I know that's true of org-ref. Is that really the case with ivy-bibtex?

https://melpa.org/#/ivy-bibtex

**Comment by brabalan** [comment]
I don't know.

**Comment by bdarcus** [comment]
Been a long time, but I just confirmed that ivy-bibtex does indeed have citation browsing and insertion functionality.

**Comment by tshu-w** [comment]
ivy should already be supported on the latest develop branch https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Blang/bibtex
