### ISSUE TITLE
Javascript/tern layer error, minor mode help keymap

### ISSUE THREAD

**Issue by eipplusone** [syl20bnr/spacemacs#7310]
#### Description :octocat:

Disclaimer: I'm not a javascript developer and encountered this problem while doing a demo to a react developer.

JavaScript `, h t` or `, h d`(not sure which actually returned the error) returns the following error message:

`Making url-show-status local to  *http 127.0.0.1:64866* while let-bound!`

Could be a tern problem, let me know and I'll redirect the issue there.
#### Reproduction guide :beetle:
- Start Emacs
- Load the layers I have 
- Open a .jsx file
- Try running the commands above

_Observed behaviour:_ :eyes: :broken_heart:
Error/nothing happening

_Expected behaviour:_ :heart: :smile:
Not sure, but at least docs popup in some capacity
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(helm auto-completion better-defaults emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control latex go dash github javascript html react themes-megapack)
```
#### Backtrace :paw_prints:

```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
Not really an error, just a warning. But yes, it should be redirected either to the package that let-binds the variable or the one that makes it buffer-local. Spacemacs doesn't touch it.

**Comment by voltecrus** [comment]
@TheBB would it be hard for you to post a screenshot of it working for you? It just didn't do anything for me. 

I essentially cloned https://github.com/badsyntax/react-seed and tried running it on words inside 
https://github.com/badsyntax/react-seed/blob/master/app/components/Menu/Menu.jsx file

**Comment by szilveszter99** [comment]
I've had the same error message on load, using es6 module import/export,
I've upgraded my tern from 0.18 to 0.20, and put es_modules: {} into plugins section into my .tern-project file. Now it works fine. You can find all my configs in my gist https://gist.github.com/szilveszter99

**Comment by TheBB** [comment]
I don't use javascript, just saying that the warning you have received isn't an error. Whatever fails, that isn't it.

**Comment by szilveszter99** [comment]
@TheBB thanks, I've amended my comment.

**Comment by tomterl** [comment]
Just to confirm @szilveszter99 : I'm using tern-0.21.0 at the moment, and just adding `es_modules: {}` to the .tern-project plugins section got rid of this warning for me as well.
