### ISSUE TITLE
Emacsclient AucTeX Biber command not found

### ISSUE THREAD

**Issue by Mengesh** [syl20bnr/spacemacs#7313]
#### Description
Cannot execute Biber from AucTeX within emacsclient

#### Reproduction guide
- Start Emacs by running `emascclient -c`
- Open `.tex` file
- Type `,,` and choose `Biber`

*Observed behaviour:*
I observe biber has no effects since output buffer gives `/bin/sh: biber: command not found`

*Expected behaviour:*
I expect biber to run normally like everywhere else (`emacs`, `/bin/sh`, shell in `emacsclient`)

#### System Info
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 better-defaults emacs-lisp git markdown pandoc org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables spell-checking-enable-auto-dictionary t)
 syntax-checking extra-langs ranger semantic gtags
 (python :variables python-enable-yapf-format-on-save t)
 (latex :variables font-latex-fontify-script nil latex-enable-auto-fill t latex-enable-folding t))
```

**Comment by TheBB** [comment]
`(executable-find "biber")` returns?

**Comment by Mengesh** [comment]
It returns `/usr/bin/vendor_perl/` so adding `(add-to-list 'load-path "/usr/bin/vendor_perl/")` to `.spacemacs` config solves the issue. That was quick. Thank you!
