### ISSUE TITLE
Typescript layers breaks web-mode usage on buffers without file

### ISSUE THREAD

**Issue by Peluko** [syl20bnr/spacemacs#7314]
Typescript layer sets a hook on `web-mode` used to detect if file is `tsx`. This check uses `buffer-file-name` to obtain the file extension, but when the buffer is not attached to a file `buffer-file-name` is `nil`, so the check crashes.

**Comment by Peluko** [comment]
PS: I use [`string-edit.el`](https://github.com/magnars/string-edit.el) to edit templates contained into typescript strings. This mode creates a buffer without file for template editing, and this bug breaks web-mode usage in these buffers.

**Comment by TheBB** [comment]
Thanks, fixed.

**Comment by TheBB** [comment]
Should be fixed in master.
