### ISSUE TITLE
( search function makes slime almost unusable

### ISSUE THREAD

**Issue by asmyers** [syl20bnr/spacemacs#7315]
#### Description

When using slime one tends to type ( quite a lot.  This inserts the character but there appears to be  some kind of search function that starts when the cursor is after a (.  After inserting a ( an error is immediately emitted in the minibuffer which says:

> Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of file.

It's hard to discover what is doing this because describe key just tells you that ( is bound to self insert.  However once the slime repl buffer is a few thousand lines this search function locks up emacs for seconds or minutes.  Even better is that it immediately restarts after failing if the cursor is still on or after the paren.  To recover emacs it is necessary to click madly somewhere else so the cursor is moved in the small window between emacs becoming responsive and the search triggering again.
#### Reproduction guide
- Start Emacs
- start slime
- generate a repl a few thousand lines long.  (dotimes (i 10000) (format t "foobar~%"))
- Type ( at the repl.

_Observed behaviour:_
Emacs becomes unresponsive for several seconds and there is an error in the minibuffer.  Madly smash a cursor movement operation in order to recover Emacs interaction.

_Expected behaviour:_
Nothing
#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp git version-control markdown org gtags dash haskell purescript idris agda rust clojure java common-lisp asciidoc spell-checking syntax-checking version-control)
```

**Comment by fouric** [comment]
Can confirm this with spacemacs 0.200.5 and layers (vimscript haskell markdown helm emacs-lisp common-lisp), and everything else sans branch being identical. Why was this closed?

**Comment by scrathat** [comment]
Can reproduce the minibuffer message with spacemacs 0.200.9 and emacs 25.2.1 but only after enabling and then disabling smartparens.
If smartparens is disabled _from the start_ everything works.
If smartparens is enabled everything works, too.
