### ISSUE TITLE
In the case of cleanup event!

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#7316]
@d12frosted  hinted that there may be the annual issue/pr cleanup event. May be even really soon. so he and I  come up with Idea to notify everyone about it in the Spacemacs.   I think the best way will be to replace Spacemacs banner in the startup buffer with a ascii life and an invitation to pitch in and and revisit your own issues and pool request and report your progress. Also provide a link to the cleanup event issue with details. Top N cleaners will be immortalized in the hall of heroes.

Some ideas:
 - *Pull request against open issues also count.*
 - *If your issue still valid please bump it :up:* 
 - *Lets run it for a month!*
 - *The notification banner can be dismissed and the usual (user selected thingy) will appear from now on. This way everyone will be notified without much irritation.*

**Comment by JAremko** [comment]
I wonder what @syl20bnr  and @TheBB  think :thinking:

**Comment by syl20bnr** [comment]
I find the idea very good and I'm all for an achievement section in the doc for top cleaners. We may even be able to create the section right now and feed in the top cleaners of 2015, I believe we can dig this info from the gitter chat, @StreakyCobra wrote the results there IIRC.

I don't want to ditch the banner though, but we have the info text frame which can be used, it appears automatically when the version number is bumped. We may be able to insert ascii art in the text frame but right now it is justified using a built-in Emacs command and it may screw up the beautiful art a little bit...

**Comment by syl20bnr** [comment]
Instead of telling people to check their issues and bump them, I prefer the process of last year where people subscribed for a given number of issues and the system gave them a random list of issues, a bit like code triage. @StreakyCobra made some tooling to do this and he gave them to @d12frosted so we can organize a new event at next fall.

The info we put on the home buffer can be a quick guide to explain people how to subscribe for new issues with some candy to catch the eyes.

**Comment by JAremko** [comment]
This is clever :+1:  
But reminding people to check their old issues/prs can't hurt. I think this is the fastest and easiest way to contribute.

**Comment by syl20bnr** [comment]
I'm working on the 0.200.1 and will use the release note text file to promote the cleanup event :-)

**Comment by StreakyCobra** [comment]
@syl20bnr Results:

-----

Some statistics about the :fallen_leaf: [Autumnal Cleanup 2015](https://github.com/syl20bnr/spacemacs/wiki/Autumnal-Cleanup-2015) progress:

Contributions:
- d12frosted: 333 (55.69%)
- StreakyCobra: 207 (34.62%)
- dsdshcym: 20 (3.34%)
- CestDiego: 10 (1.67%)
- ralesi: 10 (1.67%)
- cpaulik: 10 (1.67%)
- sooheon: 5 (0.84%)
- robbyoconnor: 3 (0.50%)

Overall progress: 598/598 (100.00%)

----

FYI the tooling is available at https://github.com/StreakyCobra/spacemacs-cleanup, but it is a quite basic software IMHO :-)

**Comment by JAremko** [comment]
@d12frosted  333 ?   :scream:

**Comment by d12frosted** [comment]
Wow. It's embarrassing, but I didn't see this issue. Welp... everything goes well :D thanks to @StreakyCobra !
