### ISSUE TITLE
Next layout spacemacs buffer issue

### ISSUE THREAD

**Issue by vendethiel** [syl20bnr/spacemacs#7317]
Note: I set up the template manually because the in-editor one doesn't seem to work. Maybe it's just because I didn't configure Org mode yet...

#### Description :octocat:

Switching workspace with `SPC l n` doesn't close the menu.

#### Reproduction guide :beetle:
- Start Emacs
`SPC l 2`
It asks me about perspective (wtf is that, even?)
I say I want to create one (well, it's a non-question really, if I say no it cancels the action)
It asks me the name of the perspective (what am I supposed to set here?). I just set `persp-frame-switch` otherwise the action is canceled as well.
`SPC l n` to switch to the next layout.

*Observed behaviour:* :eyes: :broken_heart:
The switch happens, but the `*spacemacs*` buffer doesn't close, and shows "layouts transient state" until I press a key

*Expected behaviour:* :heart: :smile:
The spacemacs buffer should close.

---------

macOS 10.12 Sierra
Spacemacs e6357a5ea35f5ad03c446b7f55871779da62e7ae

**Comment by JAremko** [comment]
`SPC l 2` will create a new perspective with a specified name. Then you can use `SPC l n` to switch between the new one and the default one. What is the problem :confused:

**Comment by vendethiel** [comment]
Looks like the description I pasted was truncated.

I understand the part about names (why is that needed?)

I do think that the spacemacs buffer not closing until next keystroke is a bug

**Comment by TheBB** [comment]
I don't understand this report either. Why would the window show any other buffer in a completely new perspective.

**Comment by bmag** [comment]
@vendethiel please edit the original report to include the observed behavior and the expected behavior. Right now I don't understand what you're trying to say.

In the repro guide, describe clearly the steps you do take to experience the observed behavior. You can add comments, but make it clear what keys you pressed. For example, when you write "I just set `persp-frame-switch`", I have no idea what you mean or what keys I need to press.

**Comment by JAremko** [comment]
> I understand the part about names (why is that needed?)
For humans. This is much easier to manage named stuff. You are entering the naming buffer automatically but you can provide one letter name or hack it to auto generate names - may be supported out of the box, by the underlying package.

> I do think that the spacemacs buffer not closing until next keystroke is a bug
you can use `SPC l 2` for fast switching.   `SPC l n` keeps you in the transient state so consequential `n` will keep rotating perspectives.

**Comment by vendethiel** [comment]
@bmag I'm afraid github mobile (still) doesn't allow to edit.

**Comment by vendethiel** [comment]
@JAremko I see. I guess it somewhat makes sense (though it's a very very surprising behavior. YMMV, as usual, I've just had a hard time understanding how to get a setup like vim tabs on spacemacs, so I'm trying a lot of stuff...)

**Comment by bmag** [comment]
@vendethiel ok, will be waiting then

**Comment by JAremko** [comment]
@vendethiel  You can use tabs Vimish https://github.com/krisajenkins/evil-tabs

**Comment by JAremko** [comment]
@bmag  Can we add a flag that if `t` will make perspective mode auto-generate names? Like Docker does if a name isn't provided. We can grab some catchy names from https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go. Like `prickly beaver` - sounds great   :smile:

**Comment by bmag** [comment]
@JAremko I will look into it. I'm thinking about matching the first letter of each name to the layout's number, so layout 2 starts with "b", 3 with "c", etc. so we can have names like: "Default" (1), "banana" (2), "carrot" (3), and so on.

**Comment by JAremko** [comment]
@bmag  It's cool. But I think that there is something to docker naming patter.  When you use adjective(or a verb) +  noun creates a mental context (backstory) so it automatically more memorable.

**Comment by TheBB** [comment]
The layout name will be in the modeline though, so let's try to keep them short.

**Comment by JAremko** [comment]
@TheBB good point. Mb we can shorten the name if modeling becomes "crowded"?  Fist shorten from two words to the first one like `prickly b` or `prickly` and if it is really crowded  to `pb`.

**Comment by bmag** [comment]
@JAremko see #7323. Instead of "adjective+noun" I went for "familiar objects" naming style.

**Comment by vendethiel** [comment]
> `SPC l n` keeps you in the transient state so consequential n will keep rotating perspectives.

Okay, I think that's the answer I was looking for. It was pretty confusing, even more so because that's not how `gt` works on vim.

Going to close this one now! Thanks y'all.

Also updated the original post, just to make it clear to whoever comes back to this.
