### ISSUE TITLE
Install package, close spacemacs, open spacemacs, package is gone

### ISSUE THREAD

**Issue by brezal** [syl20bnr/spacemacs#7319]
I can install packages and they work until I restart emacs. Here are the steps to follow

0. `emacs -nw`
1. M-x package-list-packages
2. Mark the package `intero` as to be installed using the shortcut `i`
3. Type `x` to install
4. C-x left arrow to get into scratch mode
5. M-x intero-mode ;; success!
6. C-x C-c
7. `emacs -nw`
8. open scratchpad
9. M-x ??..intero-mode isn't an option

GNU Emacs 26.0.50.1
Spacemacs Version 0.200

**Comment by TheBB** [comment]
http://spacemacs.org/doc/FAQ.html#why-are-packages-installed-with-package-install-automatically-deleted-by-spacemacs-when-it-boots

**Comment by brezal** [comment]
@TheBB Thanks!
