### ISSUE TITLE
Racket-Layer No Autocomplete After Update to 0.200.0 

### ISSUE THREAD

**Issue by exrok** [syl20bnr/spacemacs#7320]
#### Description :octocat:
No proper autocomplete in racket mode when using the racket layer
like in the older version of spacemacs the one right before 0.200.0
it work like good but now it don't like at all. Talk'in like company-mode
and shiz, it used to be like I wouldn't get user defined identies inside the
auto-complete without running but I still got something. Now I get nothing with
out running and even after running racket in buffer I only get user defined
funcs downgrading backto older spacemacs fixes it.

#### Reproduction guide :beetle:
- Start Emacs
- Open Buffer
- Enter Racket Mode
- Type "(eq"
- hit tab
- observe the lack of autocomplete

*Observed behaviour:* :eyes: :broken_heart:
no auto-complete

*Expected behaviour:* :heart: :smile:
autocomplete

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp racket latex themes-megapack theming python org unimpaired)
```

**Comment by jmiven** [comment]
I believe that racket-mode require that you declare a `#lang`, or at least a module.

Auto-completion works for me when:
1. the file contains a `#lang` declaration
2. the file has been run through `racket-run` (`SPC m s b`)

**Comment by exrok** [comment]
Yes, this resolves it. Weird it worked before the update with `#lang` but whatever.
