### ISSUE TITLE
cheaply looking spaceline in mac retina

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7321]
* the spaceline looks very cheap in my retina mac as you can see in the comparison below:
  - the first shot is from my retina mac
  - the next shot is taken directly from this github repo, just for comparison

* you can see that the antialiasing is way cheaper on my screenshot
* the height of the spaceline is smaller
* the overlay of the separators is pretty visible. it does not have the same color as the rest of the spaceline. it is slightly different. 

Is it some configuration on my end? Does anyone experience the same problem?

thanks in advance.

<img width="636" alt="retina-mac-spaceline" src="https://cloud.githubusercontent.com/assets/8352747/19209435/bb8c31e0-8ce0-11e6-992f-c75e93c2237d.png">

![advertised-spaceline](https://cloud.githubusercontent.com/assets/8352747/19209446/d16ae59c-8ce0-11e6-93ff-2311743ecc19.png)

**Comment by NJBS** [comment]
In regards to the color of the seperators, see the notes in the [macOS section](https://github.com/syl20bnr/spacemacs#macos) of the README.

As for the height and anti aliasing, you can refer to sections 1.8 and 1.9 of the FAQ respectively.
http://spacemacs.org/doc/FAQ.html#the-powerline-separators-are-ugly-how-can-i-fix-them

**Comment by ninrod** [comment]
Thanks @NJBS.
