### ISSUE TITLE
[SPC :] not working as it used to?

### ISSUE THREAD

**Issue by tostrio** [syl20bnr/spacemacs#7324]
I used spacemacs some time ago, but stayed on vim because I had little time to play around back then. Now with the new release I want to try again, but my most used feature seems to be gone. Namely `SPC :` which gave me a nive way to search all existing commands. I tried `smex` but it only shows the current major mode commands. Am I just missing something? Is there a layer for this?

Thanks in advance
tostr

**Comment by TheBB** [comment]
Read the changelog, and/or the documentation. This feature is on `SPC SPC` now.

**Comment by tostrio** [comment]
Ah yes, the changelog. That would have been a great idea :) Thank you for your quick respone tough!
