### ISSUE TITLE
Links to Spacemacs distribution layers documentation point to 404

### ISSUE THREAD

**Issue by sabastiaan** [syl20bnr/spacemacs#7326]
#### Description :octocat:

All links in Section 15 (Spacemacs distribution layers) of the LAYERS documentation point to 404 pages
#### Reproduction guide :beetle:
- Start Emacs
  Navigate to layers/LAYERS.HTML in and open any of the links in section 15.

_Observed behaviour:_ :eyes: :broken_heart:
Go to an 404 page

_Expected behaviour:_ :heart: :smile:
Go to the documentation pages.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-help-tooltip t))
```
#### Backtrace :paw_prints:

```
```

**Comment by duianto** [comment]
The Observed and Expected behavior descriptions need to be flipped.

**Comment by sabastiaan** [comment]
Thanks for pointing it out @duianto.

**Comment by philtothetop** [comment]
Hey, just gave a look at this issue, and the problem is that none of the files linked in the **Spacemacs Distribution layer** exists. From what I can see in the previous releases, they actually never existed.

**Comment by slackorama** [comment]
Duplicate of #7624? Which should be fixed with my PR on that ticket.
