### ISSUE TITLE
Fix dead link in master's README.md

### ISSUE THREAD

**Issue by voltecrus** [syl20bnr/spacemacs#7328]
A link under [this](https://github.com/syl20bnr/spacemacs#macos) section is dead.

The fix could be found [here](https://github.com/voltecrus/spacemacs/commit/8949195c011e19074be0c1a79570e56dc0e8a374).

It's fixed in develop but it still makes it hard for people to follow instructions who are just starting.

On a separate note, pull requests against master are discouraged and I wasn't sure how to submit something like this. I couldn't find anything in CONTRIBUTING.org file regarding this.

**Comment by voltecrus** [comment]
This is the commit that fixes it in develop - https://github.com/syl20bnr/spacemacs/commit/839f64ee5a97563154023e71703f21101032c494.

**Comment by TheBB** [comment]
I guess we can't even make it a week without people complaining that the master branch is getting outdated.

**Comment by voltecrus** [comment]
Not sure if it is a joke or I should feel bad...

**Comment by TheBB** [comment]
No, just some graveyard humour from someone tired of reading bug reports.

**Comment by voltecrus** [comment]
looked like it was fixed
