### ISSUE TITLE
It's really difficult to turn off company-quickhelp-mode

### ISSUE THREAD

**Issue by luxbock** [syl20bnr/spacemacs#733]
The way `company-quickhelp-mode` is initialized:

```emacs-lisp
(when (display-graphic-p)
      (add-hook 'company-mode-hook 'company-quickhelp-mode))
```

...makes it really difficult to turn it off for those of us who dislike uncalled pop-ups.

**Comment by syl20bnr** [comment]
Did you try to add it to the `dotspacemacs-excluded-packages` variable in your dotfile ?

In spacemacs you should always be able to remove any packages globally as a last resort with this variable. If it does not work then it is a bug.

**Comment by luxbock** [comment]
Whops. My bad.
