### ISSUE TITLE
html.erb does not associate with html-mode, default is fundamental mode

### ISSUE THREAD

**Issue by wangchuande** [syl20bnr/spacemacs#7330]
I use rails to program.When I jump to view from a controler using SPC m g v , the view ended with .erb does not associate with html-mode, default is fundamental mode.Help me.

**Comment by TheBB** [comment]
Add the html layer.

**Comment by wangchuande** [comment]
I have added the html layer to  dotspacemacs-configuration-layers, but it does not work.

**Comment by TheBB** [comment]
It should. https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/html/packages.el#L245 Can you check if this entry is in your auto-mode-alist?

**Comment by wangchuande** [comment]
Yes,it's there.

**Comment by TheBB** [comment]
And if you do `SPC SPC normal-mode` in an erb-file, do you get web-mode then?

**Comment by wangchuande** [comment]
File mode specification error, can not open load file.

**Comment by TheBB** [comment]
Which file?

**Comment by wangchuande** [comment]
sorry, web-mode

**Comment by TheBB** [comment]
Sounds like the package wasn't installed, this should have produced an error message earlier.

**Comment by wangchuande** [comment]
I found the problem.I added (global-git-commit-mode t)  to dotspacemacs/user-init () which should be added to user-config().But I don't know why this line can not be added to user-init fuction.
Thanks a lot.

**Comment by TheBB** [comment]
Because user-init runs before all the packages are set up, you can't call functions there that are defined in packages.

**Comment by wangchuande** [comment]
Thanks!
