### ISSUE TITLE
evil seeker

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7331]
As a vim expatriate, I miss dearly the *seeking* feature provided by the awesome and fantastic vim plugin [wellle/targets.vim](https://github.com/wellle/targets.vim). 

Here's a quick description of the feature:

> If any of the normal pair commands (not containing n or l) is executed when the cursor is not positioned inside a pair, it seeks for pairs before or after the cursor by searching for the appropriate delimiter on the current line. This is similar to using the explicit version containing n or l, but in only seeks on the current line.
*[wellle](https://github.com/wellle/targets.vim#pair-seek)*

Is there some way to achieve the same effect? I know that there's currently no evil-targets port. But can it be done in evil ways?

```javascript
//[cursor]
bla[h] blah blah function(a, b, c, d)
```

- now I hit `cinb` (change inside next brackets), or just `cib`. 

```javascript
//in insert mode
blah blah blah function(|) 
```

I just find this so convenient and quick. Don't you agree?

**Comment by TheBB** [comment]
Duplicate: https://github.com/syl20bnr/spacemacs/issues/6353

We're just waiting for someone to rewrite targets in elisp. Feel free. ;-)

**Comment by ninrod** [comment]
I'd like to do it. I just wonder how hard that would be for a completely noob in elisp.
