### ISSUE TITLE
what's up with evil-unimpaired?

### ISSUE THREAD

**Issue by cremacs** [syl20bnr/spacemacs#7332]
For the past few days, evil-unimpaired keeps trying to update and failing. This is true with a custom config and also with no .spacemacs/.d. I have successfully updated several times, but there are still issues - should I freeze for now? Or what?

**Comment by cremacs** [comment]
This is on Ubuntu 16.04, btw.

**Comment by TheBB** [comment]
Duplicate: https://github.com/syl20bnr/spacemacs/issues/6610

**Comment by cremacs** [comment]
The solution was to clear .emacs.d/cache for anyone googling.
