### ISSUE TITLE
"M-x" no longer bring up the helm buffer after upgrading to .200

### ISSUE THREAD

**Issue by yilihong** [syl20bnr/spacemacs#7333]
anyone has same issue?

**Comment by TheBB** [comment]
No.

**Comment by TheBB** [comment]
That's about the extent of the answer you're going to get unless you provide some more information (as it said to do when you reported this issue).

**Comment by yilihong** [comment]
I think its because I updated to 0.200 but didnt put helm in the layer list (in 0.150 we didnt need to put helm in the layer list?)
