### ISSUE TITLE
scss-mode syntax highlighting issues

### ISSUE THREAD

**Issue by guimachiavelli** [syl20bnr/spacemacs#7336]
#### Description

scss-mode loses syntax highlighting after second scss-mode buffer is opened.
#### Reproduction guide
1. start emacs
2. open .scss file
3. `SPC b b [another filename]` 

_Observed behaviour:_
first file displays expected highlighting (http://i.imgur.com/1HzUHxp.png), second file displays minimal highlighting (http://i.imgur.com/VNx18t6.png) [for instance, selectors and property names]

_Expected behaviour:_
both buffers should display similar highlighting.
#### Extra info

This issue happens in both GUI and terminal versions. 

Probably unrelated, but worth mentioning: I am experiencing a separate issue with flycheck in scss-mode not finding the scss_lint gem. The scss_lint issue only happens in GUI emacs.
#### System Info
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm auto-completion emacs-lisp git markdown org
      (shell :variables shell-default-term 'eshell shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking mu4e react ruby-on-rails emoji c-c html javascript php
      (ruby :variables ruby-version-manager 'rvm)
      scheme vinegar colors themes-megapack)
```
#### Backtrace

no output generated with debug-on-error enabled

**Comment by TheBB** [comment]
This one is weird.

**Comment by guimachiavelli** [comment]
Tell me about it. Are you able to reproduce it? Or is it some weirdness related to my (I believe very ordinary) setup? Or, even, an scss-mode bug?

**Comment by TheBB** [comment]
I can repro (otherwise I'd but "To be reproduced"). It doesn't repro in emacs -q so unlikely to be an scss-mode bug. However we do nothing special at all with this package and I've never seen anything like this happen elsewhere.

**Comment by elektronaut** [comment]
It's probably not spacemacs specific. I've got the same issue, and I'm not using spacemacs.

**Comment by elektronaut** [comment]
I've done some digging, and it does indeed seem to be a scss-mode problem. I reproed by deleting everything except scss-mode from my ~/.emacs.d/elpa dir, running `emacs -q` and loading it with `M-x package-initialize`.

In 25.1, the built in CSS mode now provides it's own scss-mode, I'm guessing that's where the conflict is. 

The built-in one doesn't do any compilation, everything else seems fine. I don't care about compilation so I'll just avoid the package, but I'll open an issue upstream.

**Comment by guimachiavelli** [comment]
Didn't have much time to look into this during the week, but can confirm @elektronaut's conclusion: deactivating the scss-mode package seems to fix the highlighting issue. Since I also don't need compilation, it's an acceptable fix in my case, but most likely others will disagree.

**Comment by cozywigwam** [comment]
As a follow-up to @guimachiavelli (to assist newer Spacemacs users like myself), here is the place for deactivating the scss-mode package in a .spacemacs file:
```
dotspacemacs-excluded-packages '(scss-mode)
```

**Comment by egardner** [comment]
I ran afoul of this issue as well – thanks @cozywigwam for the explicit instructions! Like you I can live with this fix, I just want proper linting and highlighting in the editor.

**Comment by zw963** [comment]
I run into this issue too, following is some info:

Emacs: 25.2.1 
Sass 3.4.23 (Selective Steve)

**Comment by zw963** [comment]
Because I use emacs daemon, so, the first time I open a scss file, the highlight is not worked, but, `scss-compile` can work.

**Comment by zw963** [comment]
I resolve this with rename this mode to another name.
