### ISSUE TITLE
Tern doesn't autostart with the React layer

### ISSUE THREAD

**Issue by futuro** [syl20bnr/spacemacs#7338]
#### Description :octocat:

Using the React layer doesn't get tern to automatically start when opening jsx files even though spacemacs can find tern.
#### Reproduction guide :beetle:
- Start Emacs
- Open a .jsx file
- Run `ps aux | grep tern` in a terminal
- Note `tern` is not running, and that none of your completions are smart

_Observed behaviour:_ :eyes: :broken_heart:
Tern doesn't start when I open a jsx file and I don't get smart completions. If I manually start tern mode
with `SPC SPC tern-mode ENTER` I get the expected behavior

_Expected behaviour:_ :heart: :smile:
When I open a js or jsx file tern should start and I should get smart completions.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm auto-completion shell-scripts emacs-lisp clojure react javascript evil-cleverparens markdown erc spell-checking syntax-checking nlinum git)
```

**Comment by TheBB** [comment]
`tern-mode` is in `react-mode-hook`, correct? If you open a jsx file with `SPC tD` turned on, do you get errors?

**Comment by futuro** [comment]
`tern-mode` is not in `react-mode-hook`. Here's the current value for that hook:

```
(spacemacs//setup-react-mode smartparens-mode spacemacs/js-doc-require react/use-eslint-from-node-modules spacemacs//init-jump-handlers-react-mode spacemacs//init-company-react-mode company-mode)
```

Opening jsx files after `SPC tD` doesn't print any errors.

**Comment by futuro** [comment]
Also, for what it's worth, `tern` also doesn't start when I have only the `javascript` layer on and open a `.js` file.

**Comment by futuro** [comment]
Ok, so I tested this in a vm with tern installed in the system wide location so I don't have to alter the PATH at all, and that started. So my next step is to test out a system wide install on my physical machine.

I should also note that I've added `(add-to-list 'exec-path "~/.node_modules/bin/")` to my user-config and `(executable-find "tern")` properly finds the binary. If my testing with a system wide tern works I'll need to read the Javascript layer more in depth to figure out where this is falling apart.

**Comment by futuro** [comment]
Alright, after some more debugging, it appears that tern won't load if it's not in your `PATH`, even if it's in your `exec-path`. Once I got spacemacs to start with the proper path tern loads automatically.

**Comment by futuro** [comment]
The fix if you've got your node bins in somewhere aside from the system path is to add the following to your `dotspacemacs/user-init` function

```elisp
  (add-to-list 'exec-path "~/.node_modules/bin" t)
```

Putting it into your `dotspacemacs/user-config` brings it in too late; we need it before the layers are configured or they won't detect tern.

I'll write up a change to the javascript and react layers.

**Comment by d12frosted** [comment]
Usually, we mark issues with a `Fixed in develop` label and actually close them only when `develop` branch is merged to `master` (e.g. release happens). So others stumbling upon an issue can easily understand the state of the fix.
