### ISSUE TITLE
Can't find Source Code Pro fonts.....

### ISSUE THREAD

**Issue by kylidboy** [syl20bnr/spacemacs#7340]
I'm running openSUSE Tumbleweed 20161003 + emacs 25.1 + spacemacs 0.200 , 
And I'm pretty sure adobe source code pro has been installed, 'cause I can use it in my vs code 1.5.
Then I tried emacs 24.5, then the fonts works just ok with the same .spacemacs and .emacs.d/

**Comment by bmag** [comment]
shot in the dark: is it possible that your Emacs 25.1 was built without some font support, and you need to rebuild it? (see #6686)

**Comment by kylidboy** [comment]
recompiled & problem is gone......

**Comment by biocyberman** [comment]
I faced this problem and it had hard time solving it because of remnants from `linuxbrew`: 
https://askubuntu.com/questions/923347/cant-enable-xft-and-freetype-support-for-emacs-25-2/923388#923388

**Comment by Tom007Cheung** [comment]
https://github.com/adobe-fonts/source-code-pro#toc0

**Comment by adeltby** [comment]
On MacOS after installing the font from google fonts you have to run : 

`cp SourceCodePro-VariableFont_wght.ttf ~/Library/Fonts`

**Comment by lebensterben** [comment]
locking this topic now.

refer the README at root of the repository for installation institutes of source code pro font.
