### ISSUE TITLE
whitespace-mode face  and default theme

### ISSUE THREAD

**Issue by kvaneesh** [syl20bnr/spacemacs#7341]
It doesn't show space before tag and indentation correctly in default theme adwaita theme works better.
This is with cc-mode enabled.

**Comment by TheBB** [comment]
**PLEASE** follow standard bug reporting procedures.

Tell us:

* What you do.
* What happens.
* What you expect.

**Comment by kvaneesh** [comment]
I have the below  value for whitespace style and white-space-mode enabled.

whitespace-style’s value is
(face indentation space-before-tab trailing lines-tail)
Original value was 
(face tabs spaces trailing lines space-before-tab newline indentation empty space-after-tab space-mark tab-mark newline-mark)

Local in buffer a.c; global value is 
(face tabs spaces trailing lines space-before-tab newline indentation empty space-after-tab space-mark tab-mark newline-mark)

and with cc-mode enabled and spacemacs-dark theme, we don't display the faces for space-before-tab and indentation correct.y. When i switch to a lighter theme things are better.

This is with the develop version of spacemacs . What i am suggesting in this report is we enhance spacemacs-theme to handle these face values correctly.
