### ISSUE TITLE
dotspacemacs-startup-lists should not be nil by default

### ISSUE THREAD

**Issue by deb0ch** [syl20bnr/spacemacs#7342]
As we discussed about it in the gitter chat with @houli, we do not understand the logic behind syl20bnr/spacemacs@36f861a.

Disabling this by default hurts discoverability and functionality for new users, as the startup lists are one of the main features (if not THE main feature) of the home buffer.

People will only discover it if maybe one day they happen to take the time to try it, instead of just disabling it for the rare ones that it will bother.

**Comment by syl20bnr** [comment]
It should have been in 0.200 and was surprised it was not.
The recent files are full of weird things when we first install Spacemacs and it takes some additional time when starting Emacs. Also I prefer a cleaner startup page when a user first install Spacemacs.

For me it is an opt-in feature, I don't want to impose something that increase startup time if it is not use and TBH these lists are borderline unuseful, opening a project is as close as a `SPC p p`, opening a recent file `SPC f r`.

**Comment by syl20bnr** [comment]
An alternative to keep discoverability could be to add a widget to toggle the startup list contents.

**Comment by deb0ch** [comment]
It is totally part of the \*wow\* effect of discovering spacemacs. It is also really useful, or at least very comfortable for starting a spacemacs session, even knowing `SPC f r` and `SPC p p`. It doesn't *feel* the same.

About startup time, I wasn't able to notice anything different. I did not take precise measurements, but on a fresh install my spacemacs takes between 2.22s to 2.45s to load, with or without startup lists, on a few tens of restarts. It doesn't make much of a difference.

IMO it is an opt *out* option, the users who want to optimize their startup time to that point will disable it, or use spacemacs-base in the first place.

**Comment by syl20bnr** [comment]
You are right. I just saw the other day our intern trying spacemacs using the list with the mouse to open files. I'll revert the commit.

**Comment by syl20bnr** [comment]
Reverted, thank you for your inputs.
