### ISSUE TITLE
Using neotree in two different layouts breaks down

### ISSUE THREAD

**Issue by vendethiel** [syl20bnr/spacemacs#7343]
#### Description :octocat:
Opening neotree buffer after it was opened in another layout "bugs" the buffer out: using motion keys or whatever else opens a new neotree split.

#### Reproduction guide :beetle:
 - Start Emacs
 - `SPC p t` to open neotree.
 - `SPL l 2`, then `y` with some random name to create a layout
 - `SPC p t` (we're in the new layout), then `q` to close it.
 - `SPC l 1` to go back to first layout
 - `j` (or pretty much any other key).

*Observed behaviour:* :eyes: :broken_heart:
A new split of neotree opens. To be noted: `q` on the old split doesn't close it, like it usually does. The new split can correctly be closed with `q`, however.

![image](https://cloud.githubusercontent.com/assets/199499/19236668/d63f70a0-8ef8-11e6-9620-987b7826874f.png)

*Expected behaviour:* :heart: :smile:
It should use the previously-opened neotree buffer/split.

macOS 10.12 Sierra
Spacemacs e6357a5

**Comment by TheBB** [comment]
I suggest we keep this in here: https://github.com/syl20bnr/spacemacs/issues/5682

It all comes down to that neotree doesn't support running multiple instances. Since we have an issue for that already we don't need more.

**Comment by vendethiel** [comment]
Very well. I found that issue, but it seemed different (mine doesn't close). Thanks!

**Comment by TheBB** [comment]
I know, but it's essentially the same problem. Feel free to copy your comment there though.

**Comment by zztczcx** [comment]
I have the same problem. and the duplicated neotree will show the same as the other one.
