### ISSUE TITLE
[Q] telling M-x man to no open a split and behave like a normal buffer

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7346]
how can I tell `M-x man` to not split up my frame and only take over the current window?
I want also that the man buffer starts with evil-normal-state and not with `Man-mode-map`. 

is that possible?

tks in advance.

**Comment by TheBB** [comment]
Configure it in popwin?

I don't even have an `M-x man`. What is that?

**Comment by TheBB** [comment]
> I want also that the man buffer starts with evil-normal-state and not with Man-mode-map. 

`evil-set-initial-state`

**Comment by ninrod** [comment]
@TheBB, are you sure? because I've just started emacs with `emacs -Q` and `M-x man` is shown.

well, it simply show for you a man page after showing you a searchable list of all the man pages that exist in your machine. really useful.

**Comment by ninrod** [comment]
> evil-set-initial-state

I tried this, but did not work: 

`(evil-set-initial-state 'Man-mode 'evil)`

I know that this works, but I don't want emacs. I want evil-normal-state.

`(evil-set-initial-state 'Man-mode 'emacs)`

**Comment by TheBB** [comment]
If you want evil-normal-state why are you setting the intial state to `evil`? Set it to `normal`.

**Comment by ninrod** [comment]
`'normal` did the trick.

How I would prevent `M-x man` to stop opening a new split though. That remains a mistery.

**Comment by TheBB** [comment]
> Man-notify-method is a variable defined in ‘man.el’.
Its value is ‘friendly’

> Documentation:
Selects the behavior when manpage is ready.
This variable may have one of the following values, where (sf) means
that the frames are switched, so the manpage is displayed in the frame
where the man command was called from:

> newframe   -- put the manpage in its own frame (see ‘Man-frame-parameters’)
pushy      -- make the manpage the current buffer in the current window
bully      -- make the manpage the current buffer and only window (sf)
aggressive -- make the manpage the current buffer in the other window (sf)
friendly   -- display manpage in the other window but don’t make current (sf)
polite     -- don’t display manpage, but prints message and beep when ready
quiet      -- like ‘polite’, but don’t beep
meek       -- make no indication that the manpage is ready

Looks like you want `pushy`.

**Comment by TheBB** [comment]
How to find options for man: `M-x customize-group man`

**Comment by ninrod** [comment]
thank you @TheBB.
