### ISSUE TITLE
python autocomplete not working.

### ISSUE THREAD

**Issue by asdyjd** [syl20bnr/spacemacs#7349]
It was working in emacs 24.5 and old spacemacs.
Recently I upgrade them to emacs 25 and spacemacs 0.2.
It's not working.
I use `M-x company-complete`, it hints me:
```
Company: An error occurred in auto-begin
Company: backend (company-anaconda :with company-yasnippet) async timeout with args (candidates filep)
```

**Comment by TheBB** [comment]
Should report upstream probably.

**Comment by TheBB** [comment]
Did you remember to upgrade packages, though?

**Comment by asdyjd** [comment]
@TheBB 
Yes,I upgrade all packages.
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>

#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: nil (rev. nil)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion autohotkey better-defaults
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
                 (chinese :variables chinese-enable-avy-pinyin t)
                 cscope emacs-lisp html javascript org
                 (python :variables python-enable-yapf-format-on-save t)
                 spacemacs-layouts syntax-checking
                 (javascript :variables tern-command
                             '("node" "D:/Program Files/nodejs/node_modules/tern/bin/tern"))
                 ycmd)
```


#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by JorisE** [comment]
I think I had the same problem (anaconda-mode was not working), but after a while found out that it was happening only in one virtualenv. Running `pip install anaconda_mode` restored funcitionality and now I can't really reproduce what went wrong :). 

Anaconda-mode has changed the way it installs dependencies. It might be that this broke something and emacs25 was not the problem.

Anyway, I hope this helps.

**Comment by d12frosted** [comment]
Thanks @JorisE for sharing this. Is this your case, @asdyjd ?
