### ISSUE TITLE
[haskell layer] Remove `hi2` when it's been merged into `haskell-mode`

### ISSUE THREAD

**Issue by bjarkevad** [syl20bnr/spacemacs#735]
PR here: https://github.com/haskell/haskell-mode/pull/483

**Comment by syl20bnr** [comment]
cool, kudos to keep spacemacs in sync ! :+1:

**Comment by bjarkevad** [comment]
I hope it's okay I open issues for this purpose, they're great as a shared reminder!

**Comment by syl20bnr** [comment]
of course!

**Comment by meditans** [comment]
Ok, so, that issue was closed and this one https://github.com/haskell/haskell-mode/pull/502 got merged in `master` 4 days ago. What should we do now (I hope this change will lead to the fix of the recent haskell indentation problems).

**Comment by syl20bnr** [comment]
I made the changes in develop and it seems to have fixed the issues :-)

**Comment by tekul** [comment]
There are also one or two references to `hi2` in the Haskell layer readme, which should perhaps be removed.

**Comment by syl20bnr** [comment]
Thank you, I fixed it.
