### ISSUE TITLE
Problem with 'which-key--update'

### ISSUE THREAD

**Issue by kgourgou** [syl20bnr/spacemacs#7352]
#### Description :octocat:
Pressing SPC results to the error:

```Error running timer ‘which-key--update’: (void-function display-buffer-in-major-side-window)```

#### Reproduction guide :beetle:
* Fresh-install of emacs and spacemacs.
* Start spacemacs, press SPC.

*Observed behaviour:* :eyes: :broken_heart:
No help buffer shown.

*Expected behaviour:* :heart: :smile:
Help buffer with the keys that follow SPC should pop-up.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50.2
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-function display-buffer-in-major-side-window)
  display-buffer-in-major-side-window(#<buffer  *which-key*> bottom 0 ((window-width . which-key--fit-buffer-to-window-horizontally) (window-height lambda (w) (fit-window-to-buffer w nil 1))))
  which-key--show-buffer-side-window((11 . 107))
  which-key--show-popup((11 . 107))
  which-key--show-page(0)
  which-key--create-buffer-and-show([32])
  which-key--update()
  apply(which-key--update nil)
  timer-event-handler([t 0 0 400000 t which-key--update nil idle 0])
```

**Comment by TheBB** [comment]
Go ask which-key if they support Emacs 26.

**Comment by kgourgou** [comment]
Apologies, I should have tracked that down first. Turns out it's a known issue.

https://github.com/justbur/emacs-which-key/issues/146

**Comment by adamcavendish** [comment]
If ur using nightly, add this to `dotspacemacs/user-init`

```
  (if (not (version<= emacs-version "26"))
      (defalias 'display-buffer-in-major-side-window 'window--make-major-side-window))
```
