### ISSUE TITLE
`SPC f e D` tip in the release notes

### ISSUE THREAD

**Issue by deb0ch** [syl20bnr/spacemacs#7357]
I was just thinking, as yet another person was being taught in the gitter chat of the existence of `SPD f e D` to easily update their dotspacemacs, maybe we should include a tip notice in each release note ?

Something like "Check&update your .spacemacs on each release (`SPC f e D` to view diff)", or something shorter.

What do you think ?

**Comment by deb0ch** [comment]
And maybe about updating packages too.

**Comment by deb0ch** [comment]
Fixed by #7603. Can this issue be closed now or do we have to wait for the commits to reach `master` ?

**Comment by LemmingAvalanche** [comment]
> Can this issue be closed now or do we have to wait for the commits to reach master ?

There’s a "fixed in develop" tag.
