### ISSUE TITLE
Neotree should allow to open in external application

### ISSUE THREAD

**Issue by Dietr1ch** [syl20bnr/spacemacs#7358]
Using xdg-open (or whatever is equivalent on other platforms) should be allowed from neotree.

Currently `o` is free, `o`pen should be easy enough to remember. Maybe use `o` for regular open, and `O` for external open.

**Comment by tobimensch** [comment]
Maybe you should file this at neotree's github page:
https://github.com/jaypei/emacs-neotree

**Comment by Dietr1ch** [comment]
I'll leave this open until we set spacemacs bindings.
It already had a ticket open on neotree's repo, I resurrected it.

On the bindings on spacemacs, `l` opens the file, but `L` is taken to move to next sibling, so it can't be `L`.
`enter` also opens the file, is `shift+enter` a viable binding?

Adding the `o`/`O` pair, would allow easier mnemonics, it'll be (more :P) redundant, but `l` and `enter` are natural following vi-bindings, or classical select/enter, rather than following a verb like open (as currently used on create/delete/rename).

**Comment by syl20bnr** [comment]
`o/O` is nice, `o` means open or other. We use it in `SPC x o` I believe.

**Comment by agzam** [comment]
That brings the good old argument about including Neotree by default or not. I personally think it should not be included and should be sitting in its own dedicated layer. It's utterly confusing and extremely annoying and unpredictable at times. I know - tree-based navbar is probably the very first thing newcomers would be asking for. Maybe we can improve documentation, list and describe alternatives, I dunno. I think there are not only better ways (but that's my personal opinion) but also speedbar, which might not be better than Neotree but already included in Emacs.

**Comment by bmag** [comment]
> It already had a ticket open on neotree's repo, I resurrected it.

link: https://github.com/jaypei/emacs-neotree/issues/112
