### ISSUE TITLE
shortcuts for web-mode and nxml-mode

### ISSUE THREAD

**Issue by emmanueltouzery** [syl20bnr/spacemacs#736]
I was preparing some spacemacs shortcuts for web-mode and it looks great. I would make a PR, however I think something similar and very compatible should be done for XML at the same time. However I can't find where the nxml mode is handled? Where can I add the spacemacs shortcuts for XML?

This is what I have for web-mode (goes to contrib/lang/html/packages.el):

(evil-leader/set-key-for-mode 'web-mode
  "mr" 'web-mode-element-rename
  "mx" 'web-mode-dom-xpath
  "mp" 'web-mode-element-parent
  "mc" 'web-mode-element-child
  "mN" 'web-mode-element-previous
  "mn" 'web-mode-element-next
  "ms" 'web-mode-element-sibling-next
  "mw" 'web-mode-element-wrap
  "mb" 'web-mode-element-beginning
  "mc" 'web-mode-element-clone
  "mf" 'web-mode-fold-or-unfold
  ;; TODO element close would be nice but broken with evil.
  )

**Comment by emmanueltouzery** [comment]
note that from what i've been looking nXML does not offer all the facilities that web-mode does (for instance rename tag), so a perfect match between the shortcuts won't be possible. Some can be though, like XPATH display.

**Comment by emmanueltouzery** [comment]
hmm now i'm a bit confused tested on a develop checkout on another computer and I got html-mode, not web-mode. That's a misconfiguration on my side right? spacemacs should always use web-mode for HTML files right, never html-mode?

**Comment by syl20bnr** [comment]
`nxml` is not installed in spacemacs, you will have to add it to the `html` layer.
For your issue with the other computer I guess that you did not add the `html` layer to the dotfile of the second computer.

**Comment by emmanueltouzery** [comment]
Hmm i'll have to research where did i get nxml from then. Yes the second
computer was a clean install to check before sending a PR, no layers. I'll
add html and re-test. would you accept those new web-mode keybindings as
listed?

**Comment by syl20bnr** [comment]
I would put them behind `mg` but we can discuss this in the PR directly.
Be sure to check the conventions here: https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.md
For instance `mr` is for refactoring commands.

**Comment by syl20bnr** [comment]
maybe a micro-state could be handy too.
