### ISSUE TITLE
Org-mode contents indentation under heading level 2 or below have changed

### ISSUE THREAD

**Issue by neocryses** [syl20bnr/spacemacs#7367]
#### Description :octocat:
With the previous spacemacs distribution, the content under level2 headings were aligned with the first letter of the level2 heading.
however with the current spacemacs distribution, contents are displayed at the very left of the window regardless of the level of it’s headings.
I have tested it with the stock spacemacs (no modifications to .spacemacs file) and the above situation can be reproduced. If there is a way to revert back to the way it was before, I’d like to know/get back to the way it was before. I have searched the web and found no solution/any notices of org-mode changing the way things are displayed. I have asked in the gitter community and 3 people including myself have noticed this change.

#### Reproduction guide :beetle:
- Start Emacs
- Open up an .org file
- Make a heading level 2 or below (two asterisks or more)
- enter some texts right below it

*Observed behaviour:* :eyes: :broken_heart:
The texts are left aligned to very left of the window.

*Expected behaviour:* :heart: :smile:
Aligned with the first letter of the heading it was under (e.g. if the content is under heading lvl2, I expect the contents to be aligned with the first letter of the heading lvl2).
The above behaviour was the way org-mode was with the previous distribution of spacemacs (before 0.200).

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion colors emacs-lisp git html java javascript markdown org
     (shell :variables shell-default-term-shell "/usr/local/bin/zsh" shell-default-shell 'multi-term shell-default-height 20 shell-default-position 'bottom)
     python ruby syntax-checking vimscript yaml)
```

#### Backtrace :paw_prints:
```
```

**Comment by swaroopch** [comment]
I believe this is because of https://github.com/syl20bnr/spacemacs/commit/bc5b7ec2c6779c5d70418c9c0227a5964c06d735

**Comment by swaroopch** [comment]
@TheBB Any reason why this was removed? If I know the reason, I can add a PR for mentioning this in the org layer docs.

**Comment by neocryses** [comment]
As mentioned in this [changelong](https://github.com/syl20bnr/spacemacs/blob/3706a42c4346dc555b8e46bea220617ce11a9ddb/CHANGELOG.org), I can see that the change was due to the glitches it caused. I'll be closing this issue as closed as the fix, reason behind it and the cause was found.
Thanks a lot to @swaroopch.
