### ISSUE TITLE
Invalid auto indentation for .rst files

### ISSUE THREAD

**Issue by spirali** [syl20bnr/spacemacs#7368]
#### Description :octocat:

Invalid auto indentation while editing reStructuredText file
#### Reproduction guide :beetle:
- Start Emacs
- create .rst file with the following content:

```
.. toctree::
   :maxdepth: 2

   abc
   xyz
```

then press "Enter" in edit mode at the end of the last line (`xyz`)

_Observed behaviour:_ :eyes: :broken_heart:

Spacemacs creates unexpected spaces before `xyz`

```
.. toctree::
   :maxdepth: 2

   abc
              xyz

```

_Expected behaviour:_ :heart: :smile:

No change of the line with `xyz`
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm better-defaults
      (auto-completion :variables auto-completion-enable-help-tooltip t)
      emacs-lisp git
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
      python syntax-checking version-control)
```

**Comment by TheBB** [comment]
Disable electric-indent-mode.

**Comment by spirali** [comment]
It has solved my problem. Thank you
