### ISSUE TITLE
spacemacs v0.2 .org file content indent error

### ISSUE THREAD

**Issue by wolfand11** [syl20bnr/spacemacs#7369]
![bug](https://cloud.githubusercontent.com/assets/1425676/19300537/74759926-908d-11e6-9ee6-69b7ed6aee11.png)

the bug is appear both windows7 and osx

**Comment by TheBB** [comment]
That's not a bug, it's just org-indent-mode that was disabled by default. See https://github.com/syl20bnr/spacemacs/issues/2732.

If you want to turn it back on:

```elisp
(setq org-startup-indented t)
```

**Comment by wolfand11** [comment]
@TheBB oh！ thank you!

**Comment by d12frosted** [comment]
Additionally you can configure it using [in-buffer settings](http://orgmode.org/manual/In_002dbuffer-settings.html). Just place following snippet somewhere in the top your org file, save and reopen file.

```
#+STARTUP: indent
```
