### ISSUE TITLE
Support ripgrep search

### ISSUE THREAD

**Issue by avdv** [syl20bnr/spacemacs#7370]
It would be nice to have support for [ripgrep](https://github.com/BurntSushi/ripgrep) for searching in spacemacs.

Unfortunately its command line options are not directly compatible with any other search tool so that it could be used as a drop in replacement for one.

**Comment by TheBB** [comment]
If someone writes a package for it we can use it.

**Comment by avdv** [comment]
Um, I not sure I get what you mean. There's a stand-alone package [here](https://github.com/nlamirault/ripgrep.el)...

But, is there a common agreed upon interface for search tools in spacemacs that needs to be implemented?

For the time being, I just wrote a quick [wrapper](https://gist.github.com/avdv/2ee9a382cee297f2a3d7081e7a818ea2) script called "ag" which does a best effort translation of ag's command line options and calls "rg" instead.

**Comment by ekmecic** [comment]
If you're using helm-ag, you can easily substitute ripgrep for ag by setting the `helm-ag-base-command` to `"rg --vimgrep --no-heading"`, as specified in the [`helm-ag` documentation here](https://github.com/syohex/emacs-helm-ag#ripgrep). 

Hope that helps :)

**Comment by bmag** [comment]
And since PT and ACK support in Spacemacs is essentially `helm-ag` + let-bindings `helm-ag-base-command`, that means adding support for RG should be easy. For example, the source of ACK-powered buffer search:
```elisp
(defun spacemacs/helm-buffers-do-ack (&optional _)
  "Search in opened buffers with `ack'."
  (interactive)
  (let ((helm-ag-base-command "ack --nocolor --nogroup"))
    (helm-do-ag-buffers)))
```

**Comment by avdv** [comment]
@ekmecic I'm not using helm, I'm using ivy.

Anyway, I'd like spacemacs to take care of which search tool to use by just setting `dotspacemacs-search-tools` to `"rg"`.

**Comment by bmag** [comment]
For Ivy support, [this](https://github.com/syl20bnr/spacemacs/blob/7869154e9dd5ad2228dd09e3546a3722a522961a/layers/+completion/ivy/funcs.el#L167-L171) and [this](https://github.com/syl20bnr/spacemacs/blob/7869154e9dd5ad2228dd09e3546a3722a522961a/layers/+completion/ivy/config.el#L15-L21) need to be modified. Documentation and default value of `dotspacemacs-search-tools` will also need to change, probably. PR welcome, I guess.

**Comment by TheBB** [comment]
OP claimed the command line arguments were not compatible, so I assumed we would need another implementation. If not then that's great, this is basically ready for whoever wants to work on it.

**Comment by syl20bnr** [comment]
> Edit: also key bindings need to be added

The current approach is cute but I don't why I did this because it does not scale well and it is. It very useful.
I'm thinking about changing the attribution of specific key bindings for each tool with something else. Some ideas:
- use a numerical argument to force the use of a specific tool in the list
- use the universal prefix argument to ask the user for a tool using helm/ivy

**Comment by swaroopch** [comment]
I'm [looking into this](https://github.com/syl20bnr/spacemacs/compare/develop...swaroopch:rg?expand=1), anybody understand helm-ag well can point me in the direction on how to make helm-ag handle grouping options for rg, I see this:

<img width="944" alt="screen shot 2016-10-17 at 5 02 05 pm" src="https://cloud.githubusercontent.com/assets/42988/19460070/21de005a-948d-11e6-912a-039e2cd5b8ba.png">

**Comment by koterpillar** [comment]
rg support was just added to Helm: https://github.com/emacs-helm/helm/pull/1625

**Comment by agriffis** [comment]
WIP PR at #7490

**Comment by deb0ch** [comment]
Shouldn't this issue be closed, or tagged `fixed in develop` ?

**Comment by bmag** [comment]
thanks @deb0ch, I forgot to label it

**Comment by Swoorup** [comment]
In ag I could do, 
`SPC /` and then `--cpp pattern` to specify the file type to search. 
How do I do this with ripgrep?

**Comment by d12frosted** [comment]
@Swoorup I think you should 'contact' [ripgrep README file][1]. I found following examples on that page:

```
$ rg foo -g 'README.*'
$ rg foo -g '!*.min.js'
$ $ rg -thtml -tcss foobar
```

  [1]: https://github.com/BurntSushi/ripgrep#whirlwind-tour

**Comment by mijoharas** [comment]
Should we be giving multiple different lines of matches when the same match shows up multiple times on a line?

e.g. have a file with content (`example_file.txt`):
```
foobar foobar foobar
```

search for foobar

see

```
example_file.txt:1:1:foobar foobar foobar
example_file.txt:1:8:foobar foobar foobar
example_file.txt:1:15:foobar foobar foobar
```

show up in helm.

**Comment by agriffis** [comment]
@mijoharas rg returns multiple results with the `--vimgrep` option, which is recommended by [helm-ag upstream](https://github.com/syohex/emacs-helm-ag#helm-agel-with-other-searching-tools). I think helm-ag intends to parse that output though, rather than showing all the results, so this might be an upstream bug.

**Comment by agriffis** [comment]
@mijoharas see https://github.com/syohex/emacs-helm-ag/issues/293 ... we'll figure this out

**Comment by AlexIljin** [comment]
When will this appear in the master branch?
