### ISSUE TITLE
Dlang layer should list the tools it depends on

### ISSUE THREAD

**Issue by Dietr1ch** [syl20bnr/spacemacs#7374]
Currently adding the `d` layer, may cause emacs to misbehave on D files.

I don't know the exact errors, but if I tell a friend to try the d layer, it should be straightforward to get it right after reading the layer's README.
The problem should be some unstated dependencies, as the layer works great for me.

This should apply for every layer, but currently the d layer has the issue.

**Comment by TheBB** [comment]
PRs welcome.

**Comment by Dietr1ch** [comment]
I know (=, I just have to further investigate what went wrong, but I won't get my hands on the machine until next week

**Comment by Dietr1ch** [comment]
How should the requirements be listed?

Further thinking through this, It will be better to grab an empty machine, install barely emacs, and then checking what goes wrong. I'm willing to do that for arch, but testing every distro out there seems to be an overkill.

Some projects build per-distro requirements list. Maybe we should start having them on the end of each layer, what do you think of this? which distros should be listed, if any?

**Comment by Dietr1ch** [comment]
I'm not sure if the installation instructions are now redundant. Installing dependencies is as easy as `pacman -S dcd` (or similar), and installing from source should imply that users know about `$PATH`.

**Comment by Miciah** [comment]
Since #7576 / https://github.com/syl20bnr/spacemacs/commit/e4e6638d4df91e315e95cc7860c448ce9bcfca53 has been merged, can this issue be labeled "Fixed in develop"?
