### ISSUE TITLE
(void-variable company-backends-typescript-mode) when open `.ts` file 

### ISSUE THREAD

**Issue by martin-liu** [syl20bnr/spacemacs#7377]
#### Description :octocat:
Error when switch to a `.ts` file

#### Reproduction guide :beetle:
- Start Emacs
- Go to a `.ts` file

*Observed behaviour:* :eyes: :broken_heart:
Failed to open `.ts` file, some error happens

*Expected behaviour:* :heart: :smile:
File open successful

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults git org
                 (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh")
                 (syntax-checking :variables syntax-checking-enable-by-default nil)
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 version-control
                 (colors :variables colors-enable-nyan-cat-progress-bar t)
                 (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
                 (ibuffer :variables ibuffer-group-buffers-by 'projects)
                 github markdown sql emacs-lisp scheme lua haskell scala
                 (clojure :variables clojure-enable-fancify-symbols t)
                 python html javascript typescript go rust dockerfile react m-layer)
```

#### Backtrace :paw_prints:
```elisp
Debugger entered--Lisp error: (void-variable company-backends-typescript-mode)
  (set (make-variable-buffer-local (quote company-backends)) company-backends-typescript-mode)
  spacemacs//init-company-typescript-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook typescript-mode-hook typescript-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook typescript-mode-hook typescript-mode-hook))
  run-mode-hooks(typescript-mode-hook)
  typescript-mode()
  set-auto-mode-0(typescript-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  ...
```

**Comment by TheBB** [comment]
Thanks, fixed in develop.

**Comment by tmkbry** [comment]
No more errors, however, the auto completion doesn't work anymore.
I have to manually call company-tide (M-x company-tide) on the element under the cursor to get
the popup.

**Comment by TheBB** [comment]
Also fixed in develop.

**Comment by tmkbry** [comment]
Thank you very much, there is one more problem with .tsx files. These files contain both,
Typescript and HTML elements. When opening a .tsx file, emacs goes into web-mode, which disables any typescript support. Manually switching to typescript-mode (M-x typescript-mode) solves this problem, this however disables the web-mode goodies.

Sorry for not fixing it myself, I was trying but couldn't get all three modes to run. Still learning 🐤

**Comment by tmkbry** [comment]
Will open a separate issue for that since the original problem has been solved.
Can be closed.

**Comment by TheBB** [comment]
Should be fixed in master.
