### ISSUE TITLE
Add keybindings for smerge-mode

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#7378]
When using magit to resolve a merge conflict `smerge-mode` opens automatically for me; however, all the keybindings are under <kbd>C-c ^</kbd>. I believe it would be better to also have them under <kbd>SPC m</kbd> or <kbd>SPC g</kbd> or even <kbd>SPC g m</kbd>.
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:

``` elisp
(auto-completion better-defaults haskell emacs-lisp git ivy emacs-lisp org agda deft spell-checking
                 (syntax-checking syntax-checking-enable-tooltips 'nil))
```

**Comment by bmag** [comment]
For those who wonder, those bindings are:
```
C-c ^ RET       smerge-keep-current
C-c ^ =         Prefix Command
C-c ^ C         smerge-combine-with-next
C-c ^ E         smerge-ediff
C-c ^ R         smerge-refine
C-c ^ a         smerge-keep-all
C-c ^ b         smerge-keep-base
C-c ^ m         smerge-keep-mine
C-c ^ n         smerge-next
C-c ^ o         smerge-keep-other
C-c ^ p         smerge-prev
C-c ^ r         smerge-resolve

C-c ^ = <       smerge-diff-base-mine
C-c ^ = =       smerge-diff-mine-other
C-c ^ = >       smerge-diff-base-other
```
Since the bindings are mnemonic, we can just use the same keys under a different prefix. However, <kbd>SPC g s</kbd> is already taken by `magit-status`, and <kbd>SPC g m</kbd> is taken by `magit-dispatch-popup`. Maybe we can use <kbd>SPC g r</kbd> ("r" for "resolve").

We'd probably want a a transient-state <kbd>.</kbd> (that's a dot). We can also bind <kbd>j</kbd> to `smerge-next` and <kbd>k</kbd> to `smerge-previous`.

I think this issue is ready for work, for anyone who wants to implement it. What do you think @rpglover64?

**Comment by rpglover64** [comment]
Sounds good! Unfortunately I don't think I can commit to working on it.

One more thought: it might be useful to start in the transient state (e.g. by an `smerge-mode-hook`).

**Comment by perfectayush** [comment]
I recently came across smerge mode, and was looking transient state for it in spacemacs but it isn't there yet. So I wrote a transient state based on examples in spacemacs. The keybindings are what I found natural to use for me:

``` elisp
(spacemacs|define-transient-state smerge
  :title "Smerge Transient State"

  :doc "
 Movement^^^^               Merge Action^^           Other
 ---------------------^^^^  -------------------^^    -----------
 [_n_/_p_]  next/prev hunk  [_b_] keep base          [_u_] undo
 [_j_/_k_]  move up/down    [_m_] keep mine          [_R_] refine
 ^^^^                       [_a_] keep all           [_q_] quit
 ^^^^                       [_o_] keep other
 ^^^^                       [_c_] keep current
 ^^^^                       [_C_] combine with next"
  :bindings
  ("n" smerge-next)
  ("p" smerge-prev)
  ("k" smerge-prev)
  ("j" evil-next-line)
  ("k" evil-previous-line)
  ("a" smerge-keep-all)
  ("b" smerge-keep-base)
  ("m" smerge-keep-mine)
  ("o" smerge-keep-other)
  ("c" smerge-keep-current)
  ("C" smerge-combine-with-next)
  ("R" smerge-refine)
  ("u" undo-tree-undo)
  ("q" nil :exit t)
)
```
I will try to implement a smerge layer. Any suggestions/improvement are welcome.

**Comment by bmag** [comment]
@perfectayush did you continue work on this? What's the status?

**Comment by perfectayush** [comment]
I had this implemented as a private layer, but didn't push it. Please review the pull request and comment if any change is required.

**Comment by bmag** [comment]
Thanks, I've reviewed it and commented there.
