### ISSUE TITLE
Opening helm toggles relative line numbers

### ISSUE THREAD

**Issue by dudelson** [syl20bnr/spacemacs#7379]
#### Description :octocat:

After disabling relative line numbers in a buffer with `SPC t r` and opening and
closing helm, the relative line numbers come back.
#### Reproduction guide :beetle:
- Start Emacs
- Ensure that `dotspacemacs-line-numbers` is set to `'relative`
  (`SPC t r` appears to work as expected when this is set to `t`). Also ensure that the `nlinum` layer is activated.
- `SPC f e R` to reload changes to `init.el` and install `nlinum` layer.
- Open a buffer
- Toggle off relative line numbers with `SPC t r`
- Open helm with `SPC b b`, `SPC f f`, or the like
- Close helm

_Observed behaviour:_ :eyes: :broken_heart:
- After opening the buffer: Relative line numbers _are_ displayed
- After `SPC t r`: Relative line numbers are _not_ displayed
- After opening and closing helm: Relative line numbers _are_ displayed

_Expected behaviour:_ :heart: :smile:
- After opening the buffer: Relative line numbers _are_ displayed
- After `SPC t r`: Relative line numbers are _not_ displayed
- After opening and closing helm: Relative line numbers are _not_ displayed
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'cycle :disabled-for org)
 c-c   fasd emacs-lisp
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-scope 'visible evil-snipe-repeat-scope 'visible)
 git gtags java javascript lua
 (latex :variables latex-build-command "LaTeX")
 markdown nlinum ocaml org pdf-tools python
 (ranger :variables ranger-cleanup-eagerly t)
 react rust semantic shell-scripts syntax-checking yaml)
```

**Comment by TheBB** [comment]
I cannot reproduce with these steps.

**Comment by dudelson** [comment]
I looked into this in more depth, and it is also crucial that the nlinum layer is activated. I've updated the reproduction steps to reflect this.
