### ISSUE TITLE
Extra top line when openning python files

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#738]
![le_img](http://i.imgur.com/wa3f5Xj.png)

This doesn't happen with othe files e.g haskell, elisp, etc, nor modes: magit, paradox etc.

**Comment by CestDiego** [comment]
OK, so I discovered by hovering on this like line is actually the header line, and is generated   by stickyfunc mode....I'm off to see the changelogs :P

**Comment by syl20bnr** [comment]
Is `stickyfunc` part of spacemacs or part of your private layers ?

**Comment by tuhdo** [comment]
It's `semantic-sticky-func-mode` that is activated when `c-c++` layer is initialized. `semantic-mode` not only supports C/C++, but also other languages with a grammar file. As far as I know, it currently supports PHP/Java/Python/Ruby/Emacs Lisp/Common Lisp, outside of C/C++. So, when you enter a file supported by Semantic and Semantic is enabled, its minor modes are enabled as well (currently the minor modes enabled in  C/C++ layer are `semantic-sticky-func-mode` and `semantic-idle-summary-mode`.

I think it's pretty beneficial. The extra top line you see will show your function signature when it's off screen and point is still inside the function, similar to [this in C/C++](http://tuhdo.github.io/static/c-ide/semantic-sticky-func.gif).

**Comment by syl20bnr** [comment]
I find this pretty cool :-)

**Comment by cpaulik** [comment]
Yeah, can we add this to the python contrib layer as a default?

**Comment by CestDiego** [comment]
it was already as a default to python... the thing is that in high res it scales badly...or maybe it's supposed to be this way?
![see](http://i.imgur.com/h4lyivj.png) 

In any case, we should be able to toggle it :D it's cool just that it took me by surprise...

**Comment by syl20bnr** [comment]
+1 for the toggle.
I like that the font is not the same size, it makes it obvious that it is not part of the code.

**Comment by CestDiego** [comment]
It would be better if there was another type of indicator apart from font size...it makes it asymmetrical and just weird. :/

**Comment by cpaulik** [comment]
Toggle would be great. Right now it also does not work with multiline function definitions.

**Comment by CestDiego** [comment]
@tuhdo in my case it's not enabled on EmacsLisp :/

**Comment by CestDiego** [comment]
@syl20bnr actually, forget about the font-size difference, I just restarted Emacs and it's all cool. :D

**Comment by CestDiego** [comment]
I'm starting to find it very useful. But I wish there could be a way of disable it if you are in the first lines, as in you don't need this
![http://i.imgur.com/tLzjH5D.png]
But when the documentation is extensive it might be useful to also take into account multiple lines:
![http://i.imgur.com/0nD48TB.png]

vs

![http://i.imgur.com/6JSLorv.png]

**Comment by tuhdo** [comment]
@CestDiego This issue is fixed with https://github.com/syl20bnr/spacemacs/pull/812.

**Comment by tuhdo** [comment]
I've created a package that handles this issue: [semantic-stickyfunc-enhance](https://github.com/tuhdo/semantic-stickyfunc-enhance). Here is a demo:

![semantic-stickyfunc-enhance-c-cpp](https://cloud.githubusercontent.com/assets/4818719/6624713/bfb6adaa-c91d-11e4-8534-553c37f262fa.gif)

**Comment by tuhdo** [comment]
A demo in Emacs Lisp:

![semantic-stickyfunc-enhance-elisp](https://cloud.githubusercontent.com/assets/4818719/6624982/a87bfda0-c91f-11e4-9efd-c3a8e5afe16c.gif)

**Comment by CestDiego** [comment]
wow, I was about to post this here saying we should take a look at this because I saw it on reddit. I didn't know you were the author. @tuhdo great job!

**Comment by trishume** [comment]
Holy crap that's cool! I love how it gradually adds parameters to the extra line as they go off. No doubt if I wrote this I would just shove the whole signature up there and tell people to deal with the repetition. The polish :heart_eyes_cat:

**Comment by tuhdo** [comment]
@everyone Thanks!

The package is now available on MELPA. Here is a Python demo:

![semantic-stickyfunc-enhance-python](https://cloud.githubusercontent.com/assets/4818719/6642039/5adec18a-c9d4-11e4-841f-7d53494bda1d.gif)

**Comment by CestDiego** [comment]
tuhdo I need to know how do you generate this gifs D: they are so smooth and high res compared with any other gifs I've tried to do

**Comment by tuhdo** [comment]
I made these gifs on Windows, using [ScreenToGif](https://screentogif.codeplex.com/).

On Linux, I use Byzanz. You can see this [question on Emacs SE](http://emacs.stackexchange.com/questions/798/recording-a-gif-screencast-of-emacs) for how to use it.

**Comment by cpaulik** [comment]
I think this was only added to the c++ layer. Should we add it also specifically for e.g. python mode or should we add it to the core packages and make a toggle for it?

**Comment by syl20bnr** [comment]
I'm for a toggle under `SPC t H`.
@tuhdo  By the way it uses the emacs header ?

**Comment by tuhdo** [comment]
It is added to C/C++ layer, and once you enable C/C++ layer it will be available for all mode that Semantic supported, since `semantic-mode` is a global minor mode, although you can disable its individual support minor modes such as `semantic-stickyfunc-mode`. Probably we should separate Semantic and made it an init function in the core, and once a user add C/C++ layer or Python layer, Semantic is activated along with other `semantic-stickyfunc-enhance`.

> By the way it uses the emacs header ?

Yes, it uses Emacs header. Is there a problem? I think we should let it on the default when open a supported file and user can toggle it off.

**Comment by syl20bnr** [comment]
> robably we should separate Semantic and made it an init function in the core, and once a user add C/C++ layer or Python layer

Yes!

**Comment by syl20bnr** [comment]
> Yes, it uses Emacs header. Is there a problem?

Nope it is a good news, we can then add a toggle for the emacs header which is agnostic of `stickyfunc`.
