### ISSUE TITLE
provide a facility to disable global-auto-revert-mode

### ISSUE THREAD

**Issue by kvaneesh** [syl20bnr/spacemacs#7381]
I am hitting this issue and this is making working with git really difficult. I found that disabling global-auto-revert-mode work around this issue.

https://github.com/syl20bnr/spacemacs/issues/2868

Adding (global-auto-revert-mode nil) dotspacemacs/user-config() doesn't really disable the auto-revert-mode. I still find it enabled in different buffers. Is there a way to disable auto-revert-mode globally ?

-aneesh

**Comment by bmag** [comment]
> Adding `(global-auto-revert-mode nil)` dotspacemacs/user-config() doesn't really disable

That's because you need `(global-auto-revert-mode -1)`.
