### ISSUE TITLE
indentation of JSX line on react-mode

### ISSUE THREAD

**Issue by selfawaresoup** [syl20bnr/spacemacs#7384]
#### Description :octocat:

In react-mode, when editing a javascript file that contains lines with JSX syntax, those lines are indented with 4 spaces while the rest of the same file is indented with 2, like I configured it.

I use the following setting for indentation of JS files:

``` elisp
(setq-default
    standard-indent 2
    tab-width 2
    indent-tabs-mode nil
    js-indent-level 2
    js2-basic-offset 2
    js2-strict-semi-warning nil
    js2-missing-semi-one-line-override nil
    web-mode-markup-indent-offset 2
    web-mode-css-indent-offset 2
    web-mode-code-indent-offset 2
    web-mode-indent-style 2
  )
```
#### Reproduction guide :beetle:
- Start Emacs with the above configuration
- open a JS file with JSX syntax in it
- auto-format the entire file, e.g. with `[g] [g] [=] [G]`

_Observed behaviour:_ :eyes: :broken_heart:
- lines with just regular JS code get indented as configured (2 spaces in this case)
- lines with JSX get indented with 4 spaces

_Expected behaviour:_ :heart: :smile:
all lines have the same indentation (2 spaces), according to the config

**Comment by lnwdr** [comment]
cc @paulyoung

**Comment by TheBB** [comment]
Please show me some code so I can try.

**Comment by lnwdr** [comment]
Here's a small example:

Lines 9-15 are indented 4 spaces while the rest has 2

```js
import React from 'react'

export default (props) => {
  const handleClick = (ev) => {
    alert("Foobar!")
  }

  return (
    <div>
        <div>
            <button onClick={handleClick}>
                Foobar
            </button>
        </div>
    </div>
  )
}
```

**Comment by TheBB** [comment]
Works here.

```jsx
import React from 'react'

export default (props) => {
  const handleClick = (ev) => {
    alert("Foobar!")
  }

  return (
    <div>
      <div>
        <button onClick={handleClick}>
          Foobar
        </button>
      </div>
    </div>
  )
}
```

**Comment by syl20bnr** [comment]
@lnwdr what is your emacs version ?

**Comment by lnwdr** [comment]
25.1, I use the OSX build from https://emacsformacosx.com

**Comment by lnwdr** [comment]
Did a clean reinstall of spacemacs and the issue disappeared. No idea how to reproduce it, though.

**Comment by tko** [comment]
I have noticed the react-mode indentation gets confused sometimes such that at least the jsx-bits get misaligned, though in my case the lines get indented too little rather than too much. No idea how to reproduce either, but reloading react-mode seems to fix it.

**Comment by tthew** [comment]
I experience the same issue as @tko and can also confirm that reloading `react-mode` fixes the issue.

**Comment by tthew** [comment]
Moving ` (push '("\\.js\\'" . react-mode) auto-mode-alist)` to the `(defun dotspacemacs/user-config ())` as opposed to `(defun dotspacemacs/user-init ())` has resolved the issue for me.

**Comment by lnwdr** [comment]
Recently, I started having the issue that @tthew describes as well: JSX indentation sometimes just stops working and reinitialising react-mode fixes it.

I already had all my config in `dotspacemacs/user-config` though.

**Comment by benbotwin** [comment]
The issue @selfawaresoup described still exists. It happens for me whenever I paste some jsx into the file. syntax highlighting stops working and so does jsx formatting
