### ISSUE TITLE
/.emacs.d/private/REAME.md inaccuracy

### ISSUE THREAD

**Issue by cyberthal** [syl20bnr/spacemacs#7386]
The instructions say

`<SPC> : configuration-layer/create-layer RET`

This doesn't work on my system.  Instead, I had to do: 

`M-x configuration-layer/create-layer RET`

The error is that `<SPC>` is a leader key and M-x isn't. 

Probably the solution is to change the readme.  Possibly I'm wrong because novice.

**Comment by TheBB** [comment]
Fixed.
