### ISSUE TITLE
creating an outshine layer - odd package initialization behavior

### ISSUE THREAD

**Issue by cyberthal** [syl20bnr/spacemacs#7388]
I tried to create an outshine layer.  It almost works.

First I followed these #5258 [instructions](https://github.com/syl20bnr/spacemacs/issues/5258), which worked.  Then I decided to make things neater by putting them in a layer. 

When I start spacemacs, the outshine package installs.  Then there's a warning, and the package is deleted without initializing.  If I reload my .spacemacs, outshine redownloads and initializes without errors.

The other problem is that  outshine/pre-init-outshine doesn't seem to trigger early enough to change the outline-minor-mode-prefix.  Which means outshine mode won't work as a self-contained layer? 

It's a pretty fresh spacemacs, and I haven't done a lot to it.  Org mode is enabled.

Here are the startup messages I get: 

> Loading d:/1-text/5-spacemacs/.emacs.d/private/outshine/packages.el (source)...done
> (Spacemacs) Warning: package outshine not initialized in layer outshine, you may consider removing this package from the package list or use the :toggle keyword instead of a `when' form.
> Loading d:/1-text/5-spacemacs/.emacs.d/private/outshine/funcs.el (source)...done
> (Spacemacs) --> deleting outshine... [1/2]
> Package ‘outshine-20160416.846’ deleted.

Here's the outshine funcs.el

```
;; adapted from
;; https://github.com/syl20bnr/spacemacs/issues/5258
;; http://spacemacs.org/doc/LAYERS.html#funcsel

(defun outshine/pre-init-outshine ()
  ;; To define the outline-minor-mode-prefix key before the package is loaded
  (defvar outline-minor-mode-prefix (kbd "H-c"))
)

(defun outshine/init-outshine ()
  ;; Setup outshine
  (use-package outshine)
  ;; Set outline-minor-mode to be automatically loaded for the mode you want
  (require 'outshine)
  (add-hook 'outline-minor-mode-hook 'outshine-hook-function)
  (add-hook 'prog-mode-hook 'outline-minor-mode)
  )

(defun outshine/post-init-outshine ()

)

;; * test target


```

**Comment by TheBB** [comment]
1. Those functions have to be in packages.el.
2. No reason for your layer to define both pre-init ad int.
3. `(use-package outshine)` does the same thing as `(require 'outshine)`

**Comment by cyberthal** [comment]
Thanks.  It works.

```
;;; packages.el --- outshine layer packages file for Spacemacs.
;;
;; Copyright (c) 2012-2016 Sylvain Benner & Contributors
;;
;; URL: https://github.com/syl20bnr/spacemacs
;;
;; This file is not part of GNU Emacs.
;;
;;; License: GPLv3

;; * code

;; ** package include

(defconst outshine-packages
  '(outshine))

;; ** init job

;; adapted from
;; https://github.com/syl20bnr/spacemacs/issues/5258
;; http://spacemacs.org/doc/LAYERS.html#funcsel
;; https://github.com/syl20bnr/spacemacs/issues/7388#issuecomment-253602911

(defun outshine/init-outshine ()
  ;; To define the outline-minor-mode-prefix key before the package is loaded
  (defvar outline-minor-mode-prefix (kbd "H-c"))
  ;; Setup outshine
  (use-package outshine)
  (add-hook 'outline-minor-mode-hook 'outshine-hook-function)
  (add-hook 'prog-mode-hook 'outline-minor-mode)
  )

;;; packages.el ends here

```

**Comment by vigilancetech-com** [comment]
Is this a bona fide layer now?  SE couldn't find it when I added it to the layers list

**Comment by cyberthal** [comment]
I haven't submitted it as a layer. It's rough. I don't know how. I plan to
learn one day.

Here is the URL to my personal version:
https://github.com/cyberthal/spacemacs-outshine

On Wed, Aug 9, 2017 at 10:58 AM, VigilanceTech.com <notifications@github.com
