### ISSUE TITLE
Erlang mode doesn't autocomplete

### ISSUE THREAD

**Issue by mrkaspa** [syl20bnr/spacemacs#7389]
do I have to do a special setting to get it work?

**Comment by TheBB** [comment]
Erlang only has support for non-semantic autocompletion (e.g. words in buffer).

**Comment by mrkaspa** [comment]
can't be added another emacs package like disel or edts to add it?

**Comment by TheBB** [comment]
Of course, PRs are welcome.

**Comment by rjcoelho** [comment]
Maybe https://github.com/DBoroujerdi/erlang-plus ?

**Comment by ikhthiandor** [comment]
There is also a new package which looks decent https://github.com/s-kostyaev/ivy-erlang-complete.

**Comment by beta1440** [comment]
Do any of you use [distel](https://github.com/massemanet/distel)? I don't use Erlang but I can submit a pull request for either [`company-erlang`](https://github.com/s-kostyaev/company-erlang) or [`company-distel`](https://github.com/sebastiw/distel-completion).
