### ISSUE TITLE
FR: alternate-buffer transient-state

### ISSUE THREAD

**Issue by xged** [syl20bnr/spacemacs#7390]
I would like to, after pressing <kbd>SPC</kbd><kbd>TAB</kbd> (`spacemacs/alternate-buffer`), be able to press <kbd>TAB</kbd> again to switch to the next buffer.

**Comment by bmag** [comment]
Can you elaborate on what the feature should do? We already got a TS on `SPC b .` that has `n` (next) and `p` (previous) for cycling between buffers.

**Comment by xged** [comment]
@bmag Same as `SPC b .`, but with half as much keystrokes.
