### ISSUE TITLE
Centered buffer mode not working as expected; Org-mode lists not wrapping properly

### ISSUE THREAD

**Issue by skalyan91** [syl20bnr/spacemacs#7394]
After upgrading to 0.200.1, I was surprised to find that `M-m w M` no longer triggers `spacemacs-centered-buffer-mode` (this change is not mentioned in the release notes). The command has apparently been rebound to `M-m w c`—however, this still does not work, as I get an error saying "Not enough space to center the buffer!".

(Actually, centered-buffer-mode *does* work after a fashion in the `scratch` buffer—but only if the lines are less wide than the window! I.e., word wrapping is not supported at all.)

Also, previously I was able to get word wrapping in Org mode (using the `visual-fill-column` package) in such a way that list indentation is respected; this no longer works.

Is there a way I can roll back to the previous version of Spacemacs?

**Comment by TheBB** [comment]
CC @JAremko 

This is probably going to be a wontfix.

I'm not sure what you mean with the word wrapping, you'll have to provide an example.

Of course you can roll back to a previous version, Spacemacs is stored in a git repository and this is what git does, all previous versions are available.

**Comment by skalyan91** [comment]
Sorry, I didn't explain the issues I'm having in nearly enough detail.

With regard to centered-buffer mode: If I go to the `*scratch*` buffer and enable centered-buffer mode (via `M-m w c`), I get huge fringes that leave a very narrow text area in the center of the screen. If I type in some text, the text area expands horizontally (and the fringes shrink), until the line of text fills the width of the screen. At that point, centered-buffer mode abruptly turns off, and if I try to re-enable it, I get a message saying, "Not enough space to center the buffer!". This is *very* different from the former behaviour of centered-buffer mode (bound to `M-m w M`), which would just force the text area to be a certain width, regardless of how wide the lines in the buffer are. If possible, I would like a way of recapturing the former functionality of centered-buffer mode.

With regard to word wrapping in org mode: What is happening is that if I have a nested list with some items that overflow the line width, then I get the following:
```
1. Blah
2. Blah
  - Blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah 
blah blah blah blah blah blah blah blah blah blah
  - Blah
3. Blah
```
What I used to be able to get (with the help of the `visual-fill-column` package, and excluding the `adaptive-wrap` package) is the following:
```
1. Blah
2. Blah
  - Blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah 
    blah blah blah blah blah blah blah blah blah blah
  - Blah
3. Blah
```
which is much cleaner.

Are you able to reproduce these issues?

In any case, yes, I'll download an earlier version of the repository. (Sorry, I'm not yet familiar with the use of git, other than cloning a repository and keeping it updated.)

**Comment by TheBB** [comment]
I don't know anything about visual-fill-colum, this doesn't look like a package that comes with Spacemacs, so if you have problems configuring that I suggest you take it up with the developers of that package. Personally I use auto-fill-mode in org-mode, which enables me to get your desired output (with actual linebreaks, mind, not virtual ones—I'm not sure which kind of wrap you want).

As for centered buffer mode let's wait for @JAremko. This does seem like a pretty significant regression.

**Comment by syl20bnr** [comment]
Sorry for missing the key binding changes in the release notes.

**Comment by JAremko** [comment]
> With regard to centered-buffer mode: If I go to the *scratch* buffer and enable centered-buffer mode (via M-m w c), I get huge fringes that leave a very narrow text area in the center of the screen. If I type in some text, the text area expands horizontally (and the fringes shrink), until the line of text fills the width of the screen. At that point, centered-buffer mode abruptly turns off, and if I try to re-enable it, I get a message saying, "Not enough space to center the buffer!". This is very different from the former behaviour of centered-buffer mode (bound to M-m w M), which would just force the text area to be a certain width, regardless of how wide the lines in the buffer are. If possible, I would like a way of recapturing the former functionality of centered-buffer mode.

Yeah. That is an intended behavior.  It centers content of a buffer without squishing it. But sure. Instead of disabling mode when a content becomes too wide, we can enable line wrap.

**Comment by JAremko** [comment]
Basically this is centered buffer mode, not squished :smile:

**Comment by JAremko** [comment]
So we can add a customization variable, something ` spacemacs-centered-buffer-mode-constrain-width` that if set will always center buffer. If buffer is too wide it will squash it to ` ` spacemacs-centered-buffer-mode-constrain-width`` value and enable line-wrap or overflow.    
I think the PR should target this [place](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistributions/spacemacs-base/local/centered-buffer-mode/centered-buffer-mode.el#L199)

**Comment by JAremko** [comment]
I think if we go for it, we should use overflow and let user toggle line wrap if needed, because long org-tables will be warped by wrapping.

@TheBB  mb it's a feature request then?

**Comment by skalyan91** [comment]
OK, I've solved my problems.

Firstly, I found out that the old way of doing centered-buffer-mode was something called `bzg-big-fringe-mode`; so I Googled up the source code for this and added it to my `.spacemacs` file (setting it to turn on automatically whenever there are no vertical splits). It works perfectly, just like in the old days (and moreover, I can now customize the width as well!). I see the reason for no longer calling this "centered-buffer-mode"; but it would be nice, I think, to have a dedicated `spacemacs-big-fringe-mode` that does things the old way.

As for (soft) line-wrapping in org-mode: This is actually taken care of perfectly well by the `adaptive-wrap` package. The only reason I was using `visual-fill-column` for this purpose in the first place was that there was a bug in earlier versions of Spacemacs (https://github.com/syl20bnr/spacemacs/issues/1418) that prevented `adaptive-wrap` from doing its job properly in org mode. But that bug seems to have been fixed, so I'm now just using `adaptive-wrap`, and have deleted `visual-fill-column`.

**Comment by JAremko** [comment]
`centered-buffer-mode` now has a lot more customizations:
``` elisp
(defgroup spacemacs-centered-buffer-mode nil
  "Minor mode to center buffer in its window."
  :group 'convenience)

(defcustom spacemacs-centered-buffer-mode-min-fringe-width 50
  "Minimal fringe width. `centered-buffer-mode' will be disabled
if one of windows displaying it becomes too narrow."
  :type 'integer
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-min-content-width 400
  "Minimal width of the centered buffer content."
  :type 'integer
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-max-content-width 800
  "Maximal width of the centered buffer content before it stops starching."
  :type 'integer
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-safety-gap-width 20
  "Add extra width to the modified buffer to make sure
that differed modifications won't cause an overflow."
  :type 'integer
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-fringe-color
  (face-background 'default)
  "Color of the fringes."
  :type 'color
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-deferred-update nil
  "Defer buffer re-centering if t.
If set to t it may improve input latency."
  :type 'boolean
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-only-grow nil
  "If t ignore reduction of the centered buffer width.
NOTE: Useful with some types of line wrappings but also
can be mush slower with huge buffers."
  :type 'boolean
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-visual-line-mode t
  "If t also enable `visual-line-mode' when `centered-buffer-mode' is enabled."
  :type 'boolean
  :group 'spacemacs-centered-buffer-mode)
```
