### ISSUE TITLE
Bibtex - `, i c` opens PDF instead of inserting citation

### ISSUE THREAD

**Issue by triss** [syl20bnr/spacemacs#7397]
#### Description :octocat:
With `bibtex` layer installed `, i c` does not insert a citation.

#### Reproduction guide :beetle:
- Start Emacs
- Set up layer as per install and configuration instructions in layers `README.org`
- `SPC f e R` - to reload configuration
- Open `.org` file
- Do `, i c` to insert citation
- Choose document to cite through helm ui

*Observed behaviour:* :eyes: :broken_heart:
Rather than inserting a citation, the PDF associated with it is opened in my Web browser.

*Expected behaviour:* :heart: :smile:
A citation should have been inserted.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control clojure bibtex extra-langs osx mu4e erc)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
Are you picking a document from your local bibliography? If so I can't reproduce, it works fine here.

**Comment by triss** [comment]
Yes I believe I am selecting from my local bibliography... i.e. a file on my machine. All entries are displayed properly by the helm system.

This is a constant issue for me.

**Comment by triss** [comment]
Fixed by installing latest update to spacemacs and packages.

Sorry for the noise
