### ISSUE TITLE
web-mode does not indent .hbs file correctly

### ISSUE THREAD

**Issue by nightire** [syl20bnr/spacemacs#7398]
#### Description :octocat:
web-mode does not indent .hbs file correctly.

Before 0.200.1, use same configurations works really good for handlebars template, these mis-indentation happens after upgrade to 0.200.1, no matter how I tweak related settings for web-mode.

#### Reproduction guide :beetle:
- Start Emacs
- Open or create an .hbs file
- Confirm it's in the web-mode
- type something like:
  ```hbs
  {{my-inline
    attribute=value}}

  {{#my-block
    attribute=value}}
    ...
  {{/my-block}}

  {{yield (hash
    foo=(helper "bar")
  )}}
  ```

*Observed behaviour:* :eyes: :broken_heart:
```hbs
{{!-- 4 spaces --}}
{{my-inline
    attribute=value}}

{{!-- 5 spaces wat? --}}
{{#my-block
     attribute=value}}
  ...
{{/my-block}}

{{!-- 4 spaces for attrs and 2 spaces closing --}}
{{yield (hash
    foo=(helper "bar")
  )}}
```

*Expected behaviour:* :heart: :smile:
```hbs
{{!-- always 2 spaces for anything --}}
{{my-inline
  attribute=value}}

{{#my-block
  attribute=value}}
  ...
{{/my-block}}

{{yield (hash
  foo=(helper "bar")
)}}
```

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults
                 (colors :variables colors-enable-nyan-cat-progress-bar t)
                 git html javascript markdown
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 syntax-checking version-control yaml)
```

**Comment by TheBB** [comment]
Should probably report this upstream since we don't do anything whatsoever with web-mode indentation settings.

**Comment by nightire** [comment]
@TheBB After read your comment, I was wondering if it's possible caused by not a fresh upgrade, then I uninstall emacs (v25.1), delete `~/.emacs.d` and `~/.spacemacs`, reinstall them all over again, now everything works well as it used to be.

Can't explain, but thank you very much for enlighten me.
