### ISSUE TITLE
Ivy and yasnippet integration

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#7401]
Is there a way to get yasnippet to work with ivy?
As expected `SPC i s` don't work when using ivy, but it would be super cool to have it back with ivy!

**Comment by jb55** [comment]
I've started using company-yasnippet as an _okay_ replacement for now. Would love to have an ivy version!

```elisp
  (spacemacs/set-leader-keys
    "is" 'company-yasnippet
    )
```

**Comment by kreedz** [comment]
https://github.com/mkcms/ivy-yasnippet
I haven't tried it yet.
