### ISSUE TITLE
Docker layer: Running `docker-containers` fails on Windows

### ISSUE THREAD

**Issue by bleggett** [syl20bnr/spacemacs#7403]
#### Description :octocat:

Docker layer: Running `docker-containers` fails on Windows

#### Reproduction guide :beetle:

- Start Emacs

- Install docker layer

- `SPC D c`

*Observed behaviour:* :eyes: :broken_heart:

`docker-containers-refresh: Symbol’s value as variable is void: docker-containers-show-all`

*Expected behaviour:* :heart: :smile:

To see a listing of my docker containers

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml helm
      (version-control :variables version-control-diff-tool 'diff-hl)
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
      windows-scripts sql
      (javascript :variables javascript-disable-tern-port-files nil)
      html syntax-checking emacs-lisp git github org markdown pandoc colors evil-commentary react docker
      (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```

**Comment by TheBB** [comment]
We make no reference to this variable in Spacemacs code, so I suggest you report upstream.

**Comment by bleggett** [comment]
Raised. https://github.com/Silex/docker.el/issues/49
