### ISSUE TITLE
Python layer: get path of Python from nix-shell?

### ISSUE THREAD

**Issue by sid-kap** [syl20bnr/spacemacs#7404]
I'm currently developing a Python project using a local nix package, and using nix-shell. Would there be any way to tell Python layer to run python as if it were run from nix-shell?

**Comment by swaroopch** [comment]
If you are starting Emacs inside the "nix-shell", it should get automatically picked up?
Else, you can configure `python-shell-interpreter`?

**Comment by swaroopch** [comment]
You can also use [directory variables](https://www.emacswiki.org/emacs/DirectoryVariables), e.g.

```elisp
((python-mode . ((python-shell-virtualenv-root . "~/.pyenv/versions/foo/"))))
```

**Comment by sid-kap** [comment]
Configuring `python-shell-interpreter` worked for me. Thanks!
