### ISSUE TITLE
Windows - symlinked layer directories not recognized

### ISSUE THREAD

**Issue by cyberthal** [syl20bnr/spacemacs#7406]
PROBLEM:

I created two layers for my personal use: outshine and personal.  They worked fine when placed in the ~/.emacs.d/private directory.

Then I moved them to a different directory where I keep my Github repos organized.  I symlinked the two directories "outshine" and "personal" back into ~/.emacs.d/private directory.  

I restarted spacemacs and it could not find the layers.  

TROUBLESHOOTING: 

I read this: 
http://emacs.stackexchange.com/questions/3673/how-to-make-vc-and-magit-treat-a-symbolic-link-to-a-real-file-in-git-repo-just
and set vc-follow-symlinks to 2 and find-file-visit-truename to t.  
It still didn't work.  

Outshine loads before personal.  Oddly, when I refresh my .spacemacs, the outshine link vanishes, and is replaced by an empty outshine directory.  Nothing happens to the personal directory.

Therefore I think the issue is symlink handling in Windows.  

I don't know what to try next.  So I just put the directories back.  

ENVIRONMENT:

My .spacemacs is pretty vanilla.  Almost all my customizations are in the personal layer.

OS: Windows 8.1 build 6.3
#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(helm better-defaults emacs-lisp git org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      outshine personal)
```

**Comment by iamthad** [comment]
A workaround may be to use junction points (mklink /J) instead of directory symlinks.

**Comment by cyberthal** [comment]
Honeycombing your FS with junctions is pretty scary for a number of reasons, and harms deployability.  I strongly prefer to deal with the more manageable symlink issues: link rot and avoiding loops.  

My solution was to learn how to virtualbox a solid Linux OS to run Spacemacs in Windows.  I chose Manjaro and haven't looked back.  Maybe I could solve the above issue in some kludgy way but there are a thousand other NTEmacs issues following behind it.  The issues with Host-Guest OS integration are much more manageable via Samba shares, hotkey switching, etc.

**Comment by jbayardo** [comment]
Is there any way to get around this?
