### ISSUE TITLE
spacemacs will not exit

### ISSUE THREAD

**Issue by arronmabrey** [syl20bnr/spacemacs#7409]
#### Description :octocat:
can not exit spacemacs

#### Reproduction guide :beetle:
- Start Emacs
- `SPC q q`
- or `C-x C-c`
- or `:q!`

*Observed behaviour:* :eyes: :broken_heart:
It pops up a helm buffer reading `HELM Persp Save To File By Names`

*Expected behaviour:* :heart: :smile:
I expect emacs to exit

### Addtional notes
I did figure out. If I make another (non Default) layout. E.g. via `SPC l 1`
Then after that layout exists. `SPC q q` will exit emacss

### Syste Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by arronmabrey** [comment]
Also in gitter @torotoki said they experienced the same issue after updating packages and have not been able to find a fix yet

**Comment by DavidGregory084** [comment]
I am experiencing this also after upgrading packages / upgrading spacemacs from 0.105.x

**Comment by arronmabrey** [comment]
I'm not sure if this is related, but [Emacs doesn't exit when persp-auto-save-opt is non-zero ](https://github.com/Bad-ptr/persp-mode.el/issues/49)

**Comment by PandaLz** [comment]
Having the same issue after upgrading packages but C-x C-c working for me

**Comment by vishakhkumar** [comment]
C-x C-c not working for me - just had a fresh install.

**Comment by clintonc** [comment]
Indeed, replacing persp-mode with commit v1.0-267-g30e2703 fixes the problem.

**Comment by cyberthal** [comment]
Same issue.  I just hit C-x C-c again.  Persistence pays.

Persp-mode is redundant with projectile, right?  Would one lose anything by excluding the package?

**Comment by jackkamm** [comment]
I have also begun experiencing this issue after reinstalling spacemacs yesterday

**Comment by Ananasr** [comment]
I have also this problem !

**Comment by axlm** [comment]
So do I.

**Comment by brettlyons** [comment]
A temporary workaround:  Add persp-mode to the dotspacemacs-excluded-packages list in .spacemacs.  To to get your features back when it's fixed, remember to remove it.

**Comment by zhengpd** [comment]
Got the same issue after running `paradox-upgrade-packages` a few minutes ago.

**Comment by robbyoconnor** [comment]
Shoot

**Comment by JAremko** [comment]
evaluating `(kill-emacs 42)` also fails. May be something with the `kill-emacs-hook`s

**Comment by robbyoconnor** [comment]
what's going down here

**Comment by syl20bnr** [comment]
I have the same issue.

Summoning @Bad-ptr :-)

@Bad-ptr the following comments [1] suggest this is a recent change in `persp-mode` but I did not check without Spacemacs TBH.

[1] https://github.com/syl20bnr/spacemacs/issues/7409#issuecomment-254020761

**Comment by JAremko** [comment]
Quick fix - will make `:q!` great again.

``` elisp
(defun emacs-kill-O-matic-9000 (x)
  (advice-remove 'kill-emacs 'emacs-kill-O-matic-9000)
  (setq kill-emacs-hook nil)
  (kill-emacs x))

(advice-add 'kill-emacs :around 'emacs-kill-O-matic-9000)
```

**Comment by agzam** [comment]
While some suggesting more radical solutions like disabling persp completely, I would like to tell that this has worked for me:

   (setq persp-auto-save-opt 0)

**Comment by Dangeranger** [comment]
@agzam Just wanted to confirm that your fix works for me as well.

Just upgraded to `0.200.2@24.5.1` around `04:00:00 GMT` and experienced the same problem exiting as the original description.

After setting `(setq-default persp-auto-save-opt 0)` in `dotspacemacs/user-config ()` the problem is resolved.

Great workaround.

**Comment by tonylotts** [comment]
It worked for me, to pin perps-mode to melpa-stable.

**Comment by Bad-ptr** [comment]
Must be fixed https://github.com/Bad-ptr/persp-mode.el/commit/59c2e7557450374e29048c983ae188fea801d7d7

> It worked for me, to pin persp-mode to melpa-stable

Yes, this is a good idea for everyone. On the other hand if nobody will try master branch, then these bugs will go to stable. For example this bug only shows itself when you have no layouts other than Default, so I have not seen it(because I have no automatic tests:p).

**Comment by robbyoconnor** [comment]
It's Hacktoberfest, somebody can write those tests for you @Bad-ptr -- anybody interested...who's not me :joy_cat:
