### ISSUE TITLE
Search microstate

### ISSUE THREAD

**Issue by legendre6891** [syl20bnr/spacemacs#741]
Is it possible to make evil-search (activated with `/` or `?`) also a micro-state (a la `#` and `*`), so that the highlighting is turned off after exiting the micro-state?

**Comment by syl20bnr** [comment]
the persistent highlighting is due to `evil-search-highlight-persist`, add it to `dotspacemacs-excluded-packages` variable of your dotfile.

**Comment by legendre6891** [comment]
Thanks!
