### ISSUE TITLE
Org-babel fails to tangle code.

### ISSUE THREAD

**Issue by vishakhkumar** [syl20bnr/spacemacs#7410]
#### Description :octocat:

Org-babel fails to tangle code
#### Reproduction guide :beetle:
- Start Emacs
- Admire beautiful latex code interspersed in org-mode. Knuth would be disgusted and turned on.
- Open org file and try to tangle using <org-babel-tangle> or <C-c C-v t>

_Observed behaviour:_ :eyes: :broken_heart:
Fails to tangle. Does not show error message. 

_Expected behaviour:_ :heart: :smile:
Create a file with the same name as org file with the extension .tex
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(html helm auto-completion emacs-lisp git markdown latex org pandoc erc spell-checking syntax-checking xkcd c-c   haskell markdown osx git command-log games)
```
#### Backtrace :paw_prints:

```
<<BACKTRACE IF RELEVANT>>
```

**Comment by d12frosted** [comment]
Sorry, but reproduction steps are not really clear. Where should I admire beautiful latex code?
