### ISSUE TITLE
After sp-kill-sexp (SPC-k-d-x) in Vim-mode, Vim-mode is temporarily disabled and Emacs-mode is active.

### ISSUE THREAD

**Issue by randre03** [syl20bnr/spacemacs#7411]
#### Description :octocat:
After sp-kill-sexp (SPC-k-d-x) in Vim-mode, Vim-mode is temporarily disabled and Emacs-mode is active.

#### Reproduction guide :beetle:
- Start Emacs
- Open a clojure file
- Place cursor on the opening paren of a sexp
- execute sp-kill-sexp (using SPC-k-d-x)

*Observed behaviour:* :eyes: :broken_heart:
Mode will switch away from Vim-mode (notice the layer notifier will change color) indicating that emacs-mode is now active. By pressing Escape you can return to Vim-mode.

*Expected behaviour:* :heart: :smile:
Starting in vim-mode, after executing sp-kill-sexp mode should still be vim-mode and not switch.

#### System Info :computer:
- OS: darwin
- Emacs: 25.2.50.1
- Spacemacs: 0.200.2
- Spacemacs branch: develop (rev. 6cb349e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(sql
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 better-defaults
 (clojure :variables clojure-enable-fancify-symbols t)
 dash elixir emacs-lisp erlang git github haskell html
 (ibuffer :variables ibuffer-group-buffers-by 'modes)
 ivy java javascript markdown org osx rust scala semantic
 (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
 spell-checking
 (syntax-checking :variables flycheck-scalastylerc
                  (expand-file-name "/Users/randre03/scalastyle_config.xml"))
 version-control vinegar)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
What is the color of the state indicatory? It should be pink, which indicates lisp state.

**Comment by randre03** [comment]
Oh, now I see...executing one of those commands automatically causes lisp state to be entered. So, this is actually operating as designed. After reviewing https://github.com/syl20bnr/evil-lisp-state, I now see that by changing evil-lisp-state-enter-lisp-state-on-command.

Consider this closed.
