### ISSUE TITLE
go layer: add godoctor

### ISSUE THREAD

**Issue by cocodrino** [syl20bnr/spacemacs#7412]
Hi, I think than would be great if you include godoctor, which provides several useful tools for golang developers

https://github.com/microamp/godoctor.el

thank you!!!......

**Comment by d12frosted** [comment]
PRs are welcome 😸

**Comment by Miciah** [comment]
Support for godoctor was added with #7742 / https://github.com/syl20bnr/spacemacs/commit/b7370f454e7f3a427ea17a43500b71afa1b9c02d on the develop branch.

**Comment by cocodrino** [comment]
thank you guys, I'll close this issue then...thank you!!!
