### ISSUE TITLE
Spacemacs misinterprets Hyper as Super on Manjaro Linux

### ISSUE THREAD

**Issue by cyberthal** [syl20bnr/spacemacs#7413]
I rebound my menu key to Hyper_R using xmodmap.  Spacemacs interprets it as Super instead. 

I'm surprised that it's easier to get a Hyper key on Windows than Linux. 

I am using a Microsoft Natural Keyboard Pro USB.  Here is the output of xev when I press my Hyper key:

```
KeyRelease event, serial 37, synthetic NO, window 0x2c00001,
    root 0x26b, subw 0x0, time 10840814, (396,-209), root:(987,36),
    state 0x40, keycode 135 (keysym 0xffee, Hyper_R), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm better-defaults emacs-lisp git org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      outshine personal)
```

EDIT:  It's basically this problem.  Mostly the OS's fault, but something mainly noticed by Emacs users.  

https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-input-evdev/+bug/683459

The key is to clear Hyper from mod4 and then map it to mod3.  Still figuring out how to do that.

**Comment by d12frosted** [comment]
It seems that there is nothing Spacemacs can help you with this issue. Thanks for sharing ticket in Ubuntu bug tracker. Closing this issue as a wontfix.

**Comment by cyberthal** [comment]
Spacemacs should give the same quality errors that XEmacs did, which would greatly reduce the amount of time users spend confused about the cause of this issue.  From the same [link](https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-input-evdev/+bug/683459):

> XEmacs gives these warnings:
> 
> (2) (key-mapping/warning)
>        Two distinct modifier keys (such as Meta and Hyper) cannot generate
>        the same modifier bit, because Emacs won't be able to tell which
>        modifier was actually held down when some other key is pressed. It
>        won't be able to tell Meta-x and Hyper-x apart, for example. Change
>        one of these keys to use some other modifier bit. If you intend for
>        these keys to have the same behavior, then change them to have the
>        same keysym as well as the same modifier bit.
> 
> (3) (key-mapping/warning) XEmacs: Super_R (0x86) generates Mod4, which is generated by Hyper.
> 
> (4) (key-mapping/warning) XEmacs: Super_R (0x86) generates both Mod3 and Mod4, which is nonsensical.

Also, I will figure out how to solve this in xmodmap and post it here.

**Comment by cyberthal** [comment]
Problem confirmed: 

Run:
`xmodmap -pm`

> xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):
> 
> shift       Shift_L (0x32),  Shift_R (0x3e)
> lock        Caps_Lock (0x42)
> control     Control_L (0x25),  Control_R (0x69)
> mod1        Alt_L (0x40),  Alt_R (0x6c),  Meta_L (0xcd)
> mod2        Num_Lock (0x4d)
> mod3      
> mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce),  Hyper_L (0xcf)
> mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)

The issue is that Super and Hyper are both mod4.  Spacemacs can't tell them apart.

**Comment by cyberthal** [comment]
Problem fixed.  

I adapted the instructions from [here](http://xahlee.info/linux/linux_swap_control_and_alt_xmodmap.html).  My ~/.Xmodmap contains the following:

```
clear mod4
keycode 135 = Hyper_R
add mod3 = Hyper_R
add mod4 = Super_L Super_R
```

This rebinds <menu> to Hyper_R and places Hyper on a separate mod than Super.
