### ISSUE TITLE
Clojure ac-cider with Compliment

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#7414]
It looks like at some point Clojure layer [used ac-cider](https://github.com/nwolfe/spacemacs/blob/5fe402a1913a9529ddc1e9c3c678a39f43bf5989/contrib/lang/clojure/packages.el#L6) and mentioned it in the layer's features:

> - Auto completion via ac-cider

But now [it doesn't](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/clojure#features) .

---

  Was it integrated into Cider or was there a problem ?  It looks like ac-cider uses [Compliment](https://github.com/alexander-yakushev/compliment)  and it is in active development. So if there was a problem it may be resolved.

**Comment by JAremko** [comment]
Also Clojure layer docs don't mention Compliment in the installation guide. So I assume it is not supported (or mb auto-installed?)

**Comment by syl20bnr** [comment]
I don't remember exactly but I'm pretty sure we just replaced `ac-cider` with the `company` alternative without looking to fix any issue.

Is there better completion support with `ac-cider`?

**Comment by JAremko** [comment]
@syl20bnr  https://github.com/alexander-yakushev/compliment#installation  
Hm... It looks like we at least need to add compliment (to the docs) as a requirement for auto completion.

**Comment by Nollo** [comment]
AFAIK compliment is already used with any recent cider version, so it should not require any setup.

**Comment by SlightlyCyborg** [comment]
Well, autocomplete doesn't work out of the box for me after installing cider.
