### ISSUE TITLE
Emacs doesn't launch spacemacs.

### ISSUE THREAD

**Issue by AnthonyJacob** [syl20bnr/spacemacs#7418]
I have followed the installation steps but it looks like emacs doesn't know about spacemacs.

I have :
1) unzipped emacs into `C:\Language\Emacs\bin`, added that path into sys variable
2) ran `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
3) ran `emacs`

But only the classic emacs windows pops up.

-- I use Windows 8.1

**Comment by bmag** [comment]
Make sure that you don't have a `~/.emacs` file and try again. If that doesn't work, please paste the (absolute) path to Spacemacs directory.

**Comment by ThatCube** [comment]
What version of Emacs are you using? Spacemacs requires Emacs 24.4 or above. Had the same issue.

**Comment by jupl** [comment]
Try setting the `HOME` environment variable to `%USERPROFILE%` before starting Emacs.

**Comment by AnthonyJacob** [comment]
Solved with : `git clone https://github.com/syl20bnr/spacemacs /.emacs.d` .

**Comment by mrprofessor** [comment]
> 
> 
> Try setting the `HOME` environment variable to `%USERPROFILE%` before starting Emacs.

Worked for me

**Comment by erichlf** [comment]
If you are looking at this in 2022 then you have to have emacs 27 or later.
