### ISSUE TITLE
Blobs of rectangle colors being rendered over source code

### ISSUE THREAD

**Issue by chrissound** [syl20bnr/spacemacs#7419]
![2016-10-16-18 31 31](https://cloud.githubusercontent.com/assets/1499652/19419439/6cd62d30-93cf-11e6-8475-0f7e0c7cb2cf.png)

#### Description
Blobs of rectangle colors being rendered over source code.

#### Reproduction guide
- Start Emacs

#### System Info
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git haskell syntax-checking)
```

**Comment by duianto** [comment]
It looks like trailing whitespace, the same thing appears when the .spacemacs file is opened <kbd>SPC f e d</kbd> and whitespace is added to the end of a line.

The keybinding to delete trailing whitespace is <kbd>SPC x d w</kbd>

To turn it off globally add this:
`(setq spacemacs-show-trailing-whitespace nil)`
to the `(defun dotspacemacs/user-config ()` section in the .spacemacs file, and restart emacs.

source: 
How to hide whitespace in buffer #3024

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: develop (rev. 72d87de)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
‘‘‘elisp
(autohotkey emacs-lisp git helm)
‘‘‘

**Comment by chrissound** [comment]
Oh my I completely missed that! Cheers!
