### ISSUE TITLE
C-x C-c doesn't kill spacemacs in one chord anymore

### ISSUE THREAD

**Issue by jrmiller82** [syl20bnr/spacemacs#7420]
Instead, it pops up a helm window at the bottom saying:

`HELM Persp Save To File By Names`

and I then have to hit `C-x C-c` again to kill emacs. 

This even happens on a cold invoke of spacemacs and without any files being modified. 

Expected behaviour is that `C-x C-c` should just kill emacs with no dialogs etc., particularly when there are no unsaved files to save.

**Comment by jrmiller82** [comment]
This is a duplicate of #7409 and that issue is more informative.

**Comment by syl20bnr** [comment]
Thank you @jrmiller82, closing as duplicate.

**Comment by jrmiller82** [comment]
Sure. No problem. Thanks for your hard work and the new release!
