### ISSUE TITLE
centered-buffer-mode is much less useful since 0.200

### ISSUE THREAD

**Issue by porglezomp** [syl20bnr/spacemacs#7421]
#### Description :octocat:

Centered buffer mode isn't useful for my writing anymore!

In 0.105 I used centered-buffer for all my prose writing, it was nice to be able to get a narrower window with line wrapping. In 0.200 the new centered-buffer isn't useful for this use case—honestly I'm not sure what it's useful for. If you have a line nearly as wide as the window, it gives you a frame that's nearly as wide as the window.
#### Reproduction guide :beetle:
- Start Emacs
- Switch to a scratch buffer.
- Type a line long enough to wrap the screen.
- Attempt to use centered buffer mode.

_Observed behaviour:_ :eyes: :broken_heart:
The buffer refuses to center with `Not enough space to center the buffer!`

_Expected behaviour:_ :heart: :smile:
The pre-0.200 behavior: the buffer should be centered with some maximum width, and overflow should be wrapped.
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-help-tooltip t)
 better-defaults
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 clojure cscope
 (elfeed :variables rmh-elfeed-org-files
         (list "~/org/feeds.org")
         url-queue-timeout 30 elfeed-search-filter "@1-year-ago  unread -pocket" elfeed-use-curl t)
 emacs-lisp finance fsharp git haskell html idris javascript
 (latex :variables latex-enable-auto-fill nil)
 markdown org pandoc
 (python :variables python-test-runner 'pytest)
 rust semantic
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control)
```

**Comment by deb0ch** [comment]
Do you mean that there should be a setting stating the maximum width of the window ?

**Comment by JAremko** [comment]
Welp. This is easy to add

**Comment by JAremko** [comment]
Just add min and max width customization variables and shovel them into [`spacemacs//centered-buffer-buffer-update-window-fringes`](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bdistributions/spacemacs-base/local/centered-buffer-mode/centered-buffer-mode.el#L189)    ez PR. I'll do it later if no one else will.

**Comment by agzam** [comment]
btw. for some reason `spacemacs/toggle-centered-buffer-mode` on my machine almost hangs Emacs - everything becomes so slow, basically you need to restart Emacs. I still can't figure out why. It is strange, I've tried `writeroom-mode` and works fine.

**Comment by JAremko** [comment]
@agzam  It basically unwrap everything to measure width. Which is pretty stupid thing to do with big files. Gotta fix it. :+1:

**Comment by agzam** [comment]
@JAremko I've created #7857 for reference

**Comment by skalyan91** [comment]
Any news on this? As mentioned in #7394, I worked around this by resuscitating the old definition of centered-buffer mode (aka bzg-big-fringe-mode); but this works inconsistently (esp. on Linux), and I would like to see an “official”, properly-implemented solution.

**Comment by JAremko** [comment]
@skalyan91  Soon :shipit:

**Comment by JAremko** [comment]
I added new customizations that should make it more useful:
``` elisp
(defgroup spacemacs-centered-buffer-mode nil
  "Minor mode to center buffer in its window."
  :group 'convenience)

(defcustom spacemacs-centered-buffer-mode-min-fringe-width 50
  "Minimal fringe width. `centered-buffer-mode' will be disabled
if one of windows displaying it becomes too narrow."
  :type 'integer
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-min-content-width 400
  "Minimal width of the centered buffer content."
  :type 'integer
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-max-content-width 800
  "Maximal width of the centered buffer content before it stops starching."
  :type 'integer
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-safety-gap-width 20
  "Add extra width to the modified buffer to make sure
that differed modifications won't cause an overflow."
  :type 'integer
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-fringe-color
  (face-background 'default)
  "Color of the fringes."
  :type 'color
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-deferred-update nil
  "Defer buffer re-centering if t.
If set to t it may improve input latency."
  :type 'boolean
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-only-grow nil
  "If t ignore reduction of the centered buffer width.
NOTE: Useful with some types of line wrappings but also
can be mush slower with huge buffers."
  :type 'boolean
  :group 'spacemacs-centered-buffer-mode)

(defcustom spacemacs-centered-buffer-mode-visual-line-mode t
  "If t also enable `visual-line-mode' when `centered-buffer-mode' is enabled."
  :type 'boolean
  :group 'spacemacs-centered-buffer-mode)
```

**Comment by skalyan91** [comment]
Thanks! Looking forward to these features being released.

**Comment by nealot** [comment]
Oh sweet! That was just what I was looking for.

**Comment by nealot** [comment]
Sweet! That's exactly what I needed :+1:

**Comment by skalyan91** [comment]
Any news on when these features will be released?

**Comment by AmbientComplexity** [comment]
Any news on this ;-)? I was looking for this solution right now. I'm not sure how useful centered buffer is, if you cant stop it from starching the line until it has its containing buffers width.

**Comment by JAremko** [comment]
@AmbientComplexity  it was fixed on develop.  Now we simple need new release for master :wink:
