### ISSUE TITLE
Rails comma keybindings not available when on a view file window

### ISSUE THREAD

**Issue by yurighensev** [syl20bnr/spacemacs#7424]
Working with rails on spacemacs, I found it would be incredibly useful to have rails comma keybindings enabled on view file windows. 
For example when implementing feature tests it is cumbersome to have to switch to any *.rb window in order to be able to `, t a` [rspec-verify-all - run all tests].

I am still learning how to customize spacemacs, but so far couldn't identify how to have those keybindings enabled on view file windows. 

Will gladly send a PR once I learn how to implement that. Meanwhile, any suggestions?

**Comment by Arkilus** [comment]
I see most of those keybindings are defined in the `package.el` of ruby layer. As ruby is a major mode I'm still figuring out how to enable those for modes like `haml` and `erb`.
