### ISSUE TITLE
Add integration with jade for javascript development

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#7432]
https://github.com/NicolasPetton/jade

**Comment by robbyoconnor** [comment]
This is gonna have the same issues that jade had (they're now called pugjs)

**Comment by robbyoconnor** [comment]
Sounds like somebody wasn't paying attention when they named their project

**Comment by robbyoconnor** [comment]
That said, PRs welcome.

**Comment by robbyoconnor** [comment]
Also, I would recommend strongly we hold off until the author gets around to renaming it -- it's pointless to integrate until the trademark issue is resolved. How the author didn't see it is beyond me. filed an issue: https://github.com/NicolasPetton/jade/issues/13

**Comment by robbyoconnor** [comment]
Also, we already integrated skewer-mode: https://github.com/syl20bnr/spacemacs/tree/develop/layers/+lang/javascript#repl

**Comment by bleggett** [comment]
If this is a pathway to get NodeJS debugger support in Spacemacs I'm very much for it.

**Comment by robbyoconnor** [comment]
it's already there....I linked to it...

--Rob

**Comment by bleggett** [comment]
@robbyoconnor Yeah I know we have the skewer REPL, but the stepping debugger is something emacs doesn't currently have for Javascript. There's realGUD but I've not had much luck with it.

**Comment by robbyoconnor** [comment]
As soon as the author of jade settles on a new name, I'd be all for adding this...well you can add it...I don't care enough to do it :)

**Comment by CestDiego** [comment]
has anyone tried it out? I'm down to integrating this. If the author changes the name of the library later, we just change it. If anyone has a layer for it or is interested in doing it I encourage them to do so :)

**Comment by robbyoconnor** [comment]
I integrated pug and **REMOVED** support for jade. You really should upgrade to pug...it's not that much work to fix it. The jade support in flycheck was broken. The pug support is very much full-featured...for all errors at least. Support is also currently in spacemacs.

**Comment by robbyoconnor** [comment]
@CestDiego do it :) I hated the name but they're gonna have the same problem the jade project had...

**Comment by Stebalien** [comment]
They've changed the name to [indium](https://indium.readthedocs.io/en/latest/).

**Comment by robbyoconnor** [comment]
They changed it at my request -- well also to save their own butts...but...

**Comment by stormpat** [comment]
Wow Indium looks really good! Going to test it out!

**Comment by yqrashawn** [comment]
This package is great. Is there any integrated patch?

**Comment by robbyoconnor** [comment]
Not yet -- have at it.

**Comment by pavilion** [comment]
Up! Will love to see js debugging in emacs!

**Comment by robbyoconnor** [comment]
If you want it -- add it :D

**Comment by p1mps** [comment]
Hello, has anybody worked yet on porting idium to spacemacs? I'm definitely interested to collaborate if anyone needs help!

**Comment by robbyoconnor** [comment]
nope
