### ISSUE TITLE
Why isn't Neotree showing a parent direct (..)?

### ISSUE THREAD

**Issue by chrissound** [syl20bnr/spacemacs#7436]
![2016-10-17-07 31 19](https://cloud.githubusercontent.com/assets/1499652/19427455/f552e326-943b-11e6-9b6e-f1af675e3cb4.png)

How am I suppose to I navigate up a directory?

**Comment by robbyoconnor** [comment]
if you type `?` with your cursor in the neotree buffer, you'll see help. It works for me.

**Comment by chrissound** [comment]
I've tried `?` with no change besides `?` appearing in the bottom status bar? (I've also pressed enter after that to no effect).

**Comment by robbyoconnor** [comment]
it shows you the path, you can go to the parent directory by typing `K`

**Comment by chrissound** [comment]
Does not appear to be doing that (showing the path).

**Comment by bmag** [comment]
@chrissound please paste output of `SPC h d s`. How come you don't have at the top of Neotree buffer this line?
> Press ? for neotree help

**Comment by chrissound** [comment]
#### System Info
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.20
- Spacemacs branch: master (rev. 9c7250a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git haskell syntax-checking)
```

No idea haha, but that sure explains my confusion.

**Comment by bmag** [comment]
Ah, you didn't upgrade to 0.200, that explains why `?` doesn't open a TS for you and don't have the help header line. Still, `K` and `U` both are supposed to navigate to displayed root directory (in this case `ris/Projects/Haskell/hackerrank`) or to its parent.

You can get a list of all defined key-bindings with `SPC ?` or  with `SPC h d b`, which should answer the question "How am I suppose to I navigate up a directory?". As for answering "Why isn't Neotree showing a parent direct (..)?", you should check what variables Neotree offers by using `SPC h d v` or `SPC : customize-group neotree`. It appears you need to set `neo-show-updir-line`.

**Comment by chrissound** [comment]
Will check back on later after work. Many thanks for everyones help!
