### ISSUE TITLE
Persp-mode asks which perspective names to save when restarting Emacs

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#7437]
#### Description :octocat:

Persp-mode asks which perspective names to save on restart.

#### Reproduction guide :beetle:

- Start Emacs
- `SPC l 2`, accept creating new layout `y`, name it `foo`
- `SPC l 3`, accept creating new layout `y`, name it `bar`
- `SPC l 4`, accept creating new layout `y`, name it `blah`
- Save layouts `SPC l S`, choose `foo`, then `bar`, then `blah`, then `[>done<]`. Name the file `foobarblah`.
- Restart Emacs `SPC q r`

*Observed behaviour:* :eyes: :broken_heart:

When restarting Emacs asks which perspective names to save. Well, let's tell again:

- Choose `foo`, then `bar`, then `blah`, then `[>done<]`.

I see the following error:
`persp-mode can not save perspectives, do you want to exit anyway? (y or n)`

Let's choose `y` anyway.

*Expected behaviour:* :heart: :smile:

I expected Emacs just restart without asking any perspective names to save.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: develop (rev. a6e5ad2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml extra-langs emacs-lisp ranger
     (python :variables nose-capture nil python-test-runner 'pytest pytest-cmd-flags "")
     ipython-notebook
     (shell :variables shell-pop-autocd-to-working-dir nil)
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
     (syntax-checking :variables syntax-checking-enable-by-default t)
     (haskell :variables haskell-process-type 'stack-ghci)
     latex git org c-c++ html javascript colors lua markdown ibuffer
     (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
     (window-purpose :variables purpose-default-layout-file "~/.emacs.d/.cache/purpose-layouts/ "))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by adimit** [comment]
Duplicate of #7409

**Comment by adimit** [comment]
Could be related to #7409

**Comment by jluttine** [comment]
Yep, I think this is a duplicate.
