### ISSUE TITLE
spacemacs-purpose-popwin and popwin not working correctly

### ISSUE THREAD

**Issue by nixmaniack** [syl20bnr/spacemacs#7439]
#### Description :octocat:

[These](https://github.com/syl20bnr/spacemacs/blob/b8745c316e5241241e48655a9591402da165524e/layers/%2Bspacemacs/spacemacs-ui-visual/packages.el#L260-L268) configurations aren't being respected.

This might be due the change of name from `purpose-popwin` to `spacemacs-purpose-popwin` while integrating the` window-purpose` layer in spacemacs. [Local package](https://github.com/syl20bnr/spacemacs/blob/b8745c316e5241241e48655a9591402da165524e/layers/+spacemacs/spacemacs-purpose/local/spacemacs-purpose-popwin/spacemacs-purpose-popwin.el#L243)  doesn't have this `(provide 'spacemacs-purpose-popwin)` change and and also it's toggled based on use of `popwin` but I think it's supposed to be used with `popwin`.

cc @bmag 

#### Reproduction guide :beetle:
- Start Emacs
- Hit `SPC f e d` and go to any dotspacemacs variable and hit `K` in normal mode to get its help description. 

*Observed behaviour:* :eyes: :broken_heart:
Opens at right hand side taking half screen.  

*Expected behaviour:* :heart: :smile:
Opens `*Help*` and similar buffers in the bottom respecting the popwin configurations. 

#### System Info :computer:
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.200.2
- Spacemacs branch: develop (rev. b8745c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion emacs-lisp git github yaml org
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     version-control)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IRRELEVANT>>
```

**Comment by TheBB** [comment]
Does https://github.com/syl20bnr/spacemacs/pull/7441 help?

**Comment by bmag** [comment]
I'm going over the changes right now, and also seen this. If you find further issues, please report them as well.

**Comment by bmag** [comment]
@nixmaniack I think adding `(pupo/update-purpose-config)` to the end of `user-config` should make help buffers pop at the bottom again (as a work-around for now).

**Comment by nixmaniack** [comment]
@TheBB Looks like that solved it. :+1: 

@bmag Okay thanks. I actually evaluated purpose-popwin and was using `purpose-x-popwin-setup` which seemed to work as workaround. Since @TheBB's fix seems more right, I'll keep that one for now and report if I find any more issues.

**Comment by bmag** [comment]
Yeah, I tried @TheBB's fix now and it is the right way.

**Comment by TheBB** [comment]
Great, I merged it then. Closing this.
