### ISSUE TITLE
Visual block insert undo behavior is inconsistent

### ISSUE THREAD

**Issue by tjdoc** [syl20bnr/spacemacs#7440]
#### Description :octocat:
Visual block insert undo behavior is inconsistent. Visual multi-line inserted contents should be removed with one undo command. 

#### Reproduction guide :beetle:
- Start Emacs
- `<SPC>-b-s` (in scratch buffer)
- `ithis is a test<ESC>Yppppggw<C-v>jjjI#######<ESC>u`

*Observed behaviour:* :eyes: :broken_heart:
only the last single pound (#) is removed

*Expected behaviour:* :heart: :smile:
expected all inserted pounds (#) to be removed

The spacemacs undo behavior is inconsistent with vim
I have to press u multiple times to remove the block inserted pounds.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: (hybrid :variables hybrid-mode-enable-evilified-state t hybrid-mode-enable-hjkl-bindings t hybrid-mode-default-state (quote normal))
- Completion: helm
- Layers:
```elisp
(python
 (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
 better-defaults emacs-lisp git markdown org ranger themes-megapack
 (shell :variables shell-default-shell 'eshell shell-default-height 60 shell-default-position 'bottom)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-by-default nil))
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
This is a user configuration issue. I can produce the desired behaviour with `evil-want-fine-undo` set to `nil`, but the undesired behaviour with it set to `t`.

**Comment by TheBB** [comment]
For the record, the default value of this setting is `nil` and Spacemacs does not change it.

**Comment by tjdoc** [comment]
Ah! you're right! Thank you for your help.
