### ISSUE TITLE
Discussion on keyboard bindings in <S-arrow>, <M-arrow>

### ISSUE THREAD

**Issue by krazedkrish** [syl20bnr/spacemacs#7442]
With the new update on spacemacs develop `(commit id: 2a2fb56452a425d2b012a21b48fee3dce01182a7 )`, I realized that the functions on `<S-arrow>`,` <M-arrow>` are different, for example.

```
<S-left> runs the command windmove-left, which is an interactive autoloaded
compiled Lisp function in `windmove.el'.

It is bound to <S-left>.
```

```
<M-left> runs the command left-word, which is an interactive compiled Lisp
function in `bindings.el'.

It is bound to <C-left>, <M-left>.
```

I find this feature odd, I believe the previous binding of  `<S-arrow>`, for selecting word and, `<M-arrow>` for switching window better. But this is my view point. I wonder if my view point matches with that of the mass. And the spacemacs contributers are willing to revert this change.

PS: Thanks for this awesome config, called spacemacs.

**Comment by TheBB** [comment]
I don't have those bindings…

**Comment by krazedkrish** [comment]
I am not sure, what caused the change in the bindings. Seems like an external factor. I will check.
