### ISSUE TITLE
package-selected-packages keeps spawning in .spacemacs/init.el

### ISSUE THREAD

**Issue by YiLiu6240** [syl20bnr/spacemacs#7443]
I store the code generated by Custom in a dedicated file `"custom.el"` to keep my spacemacs config tidy, at the end of `dotspacemacs/user-config`:

``` elisp
(defun dotspacemacs/user-config ()
  (setq custom-file (expand-file-name "custom.el" dotspacemacs-directory))
  (load custom-file))
```

However since I upgrade my Emacs to 25.1 and each time I install new packages, there is a specific portion of custom information spawning in my `".spacemacs"` or `"init.el"`, like (I removed the comment lines):

``` elisp
(custom-set-variables
 '(package-selected-packages
   (quote
    (NEW-PACKAGES OLD-PACKAGES...))))
(custom-set-faces
 )
```

where `NEW-PACKAGES` are the new packages that I installed this time.
In my `"custom.el"` there is also a similar part for `package-selected-packages` containing only `OLD-PACKAGES`, and other parts of the custom code.

How do I let `package-selected-packages` be updated in `"custom.el"` instead of spawning in my config file?

**Comment by TheBB** [comment]
Set `custom-file` in `user-init`, not `user-config`.

**Comment by YiLiu6240** [comment]
@TheBB Super thanks!
Could you consider adding to the documentation about the correct way to set `custom-file` in `user-init`?

**Comment by TheBB** [comment]
Sure, no problem.
