### ISSUE TITLE
Set `edit` purpose for web-mode, json-mode etc.

### ISSUE THREAD

**Issue by tmtx** [syl20bnr/spacemacs#7449]
Files opened in web-mode, json-mode (maybe others) opens with purpose `general` instead of `edit`.

They should have the same purpose as other code files, so it's easier to work with them at the same time.

For example, right now, if the active window has `.html` file open and second window has `.js` file open - if you do `SPC p f` and select `.js` file, it will not open in the active window.

Note for css-mode: It doesn't have `edit` mode only in  Emacs 24.4 and 24.5, because there `css-mode` inherits from`fundemntal-mode`, instead of `prog-mode`.

@bmag

**Comment by TheBB** [comment]
Moving issues related to purpose: https://github.com/syl20bnr/spacemacs/issues/7453
