### ISSUE TITLE
Control of popup windows

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#745]
Hi, what's the recommend way of controlling popup windows ?

I see popwin is in, but deprecated ?

Looking to change the behaviour of 'GHC Info' etc just to appear and easily dismissed window, rather than it currently changing a window.

Thanks

**Comment by syl20bnr** [comment]
I did not know that, popwin is deprecated ?

**Comment by fatlazycat** [comment]
Sorry was meaning more from a spacemacs usage. Probably just misinterpreted a comment elsewhere. 




Can you config popwin in the dotspacemacs file ?




Thanks

**Comment by fatlazycat** [comment]
Ah sorry found the docs for this. 

See you implement via customise group. 

Just need to get the window *GHC Info* to stick as a popup

Thanks

**Comment by syl20bnr** [comment]
You have some example of sticky windows here: https://github.com/syl20bnr/spacemacs/blob/master/spacemacs/packages.el#L1878-1895

**Comment by fatlazycat** [comment]
And you add an extra ones to dotspacemacs?

**Comment by syl20bnr** [comment]
Yes it should work.

**Comment by fatlazycat** [comment]
Sorry, could you point me in the direction of how to set them ?

Probably to new to emacs config to work it out.

Thanks

**Comment by syl20bnr** [comment]
I think setting them in `dotspacemacs/config` should do the trick:

```elisp
(push '("XXX" :dedicated t :position bottom :stick t :noselect t) popwin:special-display-config)
```

Where `XXX` is the name of the GHC info buffer.

**Comment by fatlazycat** [comment]
Thanks, I was trying that in the Init section and it didn't work :)

All good, thanks for the help.
