### ISSUE TITLE
Symbol’s function definition is void: xterm-color-unfontify-region

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#7450]
#### Description :octocat:
Spacemacs show this error after updating package today :
```
font-lock-unfontify-region: Symbol’s function definition is void: xterm-color-unfontify-region Error during redisplay: (jit-lock-function 1) signaled (void-function xterm-color-unfontify-region)
```

#### Reproduction guide :beetle:
- Start Emacs
- update packages

You can find my configuration here : https://github.com/phenix-factory/config-spacemacs

*Observed behaviour:* :eyes: :broken_heart:
Error + Term not working in emacs

*Expected behaviour:* :heart: :smile:
Well, working I guess :)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking shell-scripts php php-mby html javascript lua gtags imenu-list yaml finance colors dash twitter
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t))
```

Thanks !

**Comment by bixuanzju** [comment]
You need to update to the latest master version.

**Comment by phenix-factory** [comment]
Spacemacs didn't tell me about that update.
Problem solved, thx !
