### ISSUE TITLE
Renaming to a prefix of a file is impossible with ivy completion

### ISSUE THREAD

**Issue by hcnelson99** [syl20bnr/spacemacs#7454]
#### Description :octocat:

Renaming to a prefix of a file is impossible with ivy completion
#### Reproduction guide :beetle:
- Ensure the ivy layer is enabled
- Start Emacs
- Create a new file called "test123" and save it
- Attempt to rename the file to "test" with SPC f R (rename-current-buffer-file)
- Observe that this is impossible because autocompletion tries to suggest test123 instead

_Observed behaviour:_ :eyes: :broken_heart:
There is no way to rename the current buffer to a prefix of its name because autocompletion gets in the way.

_Expected behaviour:_ :heart: :smile:
There should be some way to get around the autocompletion and rename the current buffer file to exactly what you have typed. When helm is enabled, this is possible because one of the options offered by autocomplete is exactly what you have typed so far.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp git ivy markdown org rust
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking version-control)
```

**Comment by NJBS** [comment]
You should be able to use `C-M-j` to have ivy select your currently entered text rather than the first suggestion.

**Comment by hcnelson99** [comment]
Thanks! Is this documented somewhere?

**Comment by NJBS** [comment]
Yep, check out http://oremacs.com/swiper/
