### ISSUE TITLE
the indent of SRC code block in Org file is not right

### ISSUE THREAD

**Issue by geekplux** [syl20bnr/spacemacs#7458]
#### Description :octocat:

Hi, the indent of SRC code block in my Org file is not right, since I updated Spacemacs to 0.200 and Emacs-mac to 25.1. And ran `evil-indent` could not make them indent right and report a error message:

```
eldoc error: (wrong-type-argument processp nil)
```

#### Reproduction guide :beetle:
- Start Emacs
- Open a Org file
- `SPC j =` or `gg = G`

*Observed behaviour:* :eyes: :broken_heart:

for example

```
*** org-mac-link

    You may also optionally bind a key to activate the link grabber menu, like this:


    # BEGIN_SRC emacs-lisp

(add-hook 'org-mode-hook (lambda ()
  (define-key org-mode-map (kbd "C-c g") 'org-mac-grab-link)))

    # END_SRC
```

*Expected behaviour:* :heart: :smile:

```
*** org-mac-link

    You may also optionally bind a key to activate the link grabber menu, like this:


    # BEGIN_SRC emacs-lisp

    (add-hook 'org-mode-hook (lambda ()
      (define-key org-mode-map (kbd "C-c g") 'org-mac-grab-link)))

    # END_SRC
```

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(html
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 ivy better-defaults emacs-lisp git github markdown
 (org :variables org-enable-github-support t org-enable-priority-commands t)
 (shell :variables shell-default-shell 'eshell shell-default-term-shell "/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
 html javascript typescript
 (python :variables python-test-runner 'pytest)
 python ruby ruby-on-rails racket scheme yaml syntax-checking version-control themes-megapack dash pandoc latex osx
 (colors :variables colors-enable-nyan-cat-progress-bar t)
 search-engine chinese geekplux emacs-lisp org osx)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
Org has never offered indentation of code inside src blocks as far as I'm aware. To do that you need to edit in a separate buffer (`C-c '`).

**Comment by d12frosted** [comment]
@TheBB the same here. The only way to properly indent code blocks in org-mode I know is <kbd>C-c '</kbd>.

**Comment by geekplux** [comment]
but before updated It appears as I expected:
line indent is same as `# BEGIN_SRC`, not the left of the file..

**Comment by TheBB** [comment]
I don't understand that either. In previous version of Spacemacs org-mode content *looked* like it was indented due to org-indent mode being enabled. This is disabled by default now so if you want that behaviour you can re-enable it. However it's only a display feature, the contents of the org file doesn't change.

**Comment by geekplux** [comment]
I just wanna the display feature, I understand. thanks to your clear explaination.

**Comment by TheBB** [comment]
Set `org-startup-indented` to `t` to get back the old behaviour.

**Comment by geekplux** [comment]
LGTM
