### ISSUE TITLE
Layouts order not preserved when saving

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#7459]
#### Description :octocat:

When saving the layouts, order is not preserved.

This is not a duplicate of https://github.com/syl20bnr/spacemacs/issues/7396 in which the order changes between every load. In this issue, the order is always the same when loading, but it's not the order in which the layouts were originally saved.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC l 2`, accept creating new layout `y`, name it `aaa`
- `SPC l 3`, accept creating new layout `y`, name it `wiki-aaa`
- `SPC l 4`, accept creating new layout `y`, name it `bbb`
- `SPC l 5`, accept creating new layout `y`, name it `wiki-bbb`
- Save layouts `SPC l S`, choose `aaa`, then `wiki-aaa`, then `bbb`, then `wiki-bbb`, then `[>done<]`. Name the file `aaabbb`.
- Check layout order `SPC l`: you see `2: aaa`, `3: wiki-aaa`, `4: bbb`, `5: wiki-bbb`
- Quit Emacs `SPC q q`
- Start Emacs
- Open layout file `SPC l L`, choose `aaabbb`.
- Check layout order `SPC l` again.

*Observed behaviour:* :eyes: :broken_heart:

The observed layout order: `2: wiki-aaa`, `3: wiki-bbb`, `4:aaa`, `5:bbb`

*Expected behaviour:* :heart: :smile:

 I expected the layout order to be the original one: `2: aaa`, `3: wiki-aaa`, `4: bbb`, `5: wiki-bbb`
 
 I could reproduce this issue only when some layout names contained hyphens. And
 it seems that the ones with hyphen in the names are put at the beginning of the
 order.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: develop (rev. b8745c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv yaml extra-langs emacs-lisp ranger
     (python :variables nose-capture nil python-test-runner 'pytest pytest-cmd-flags "")
     ipython-notebook
     (shell :variables shell-pop-autocd-to-working-dir nil)
     (auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence nil auto-completion-private-snippets-directory nil auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
     (syntax-checking :variables syntax-checking-enable-by-default t)
     (haskell :variables haskell-process-type 'stack-ghci)
     latex git org c-c   html javascript colors lua markdown ibuffer
     (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
     (window-purpose :variables purpose-default-layout-file "~/.emacs.d/.cache/purpose-layouts/ "))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
@jluttine can you comment on https://github.com/Bad-ptr/persp-mode.el/issues/53 please? This seems like a continuation of that issue, so lets keep the discussion there.

**Comment by jluttine** [comment]
Fixed upstream.
