### ISSUE TITLE
Purpose mode make company mode really slow...

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#7460]
![image](https://cloud.githubusercontent.com/assets/785541/19467035/884a51ae-9541-11e6-8413-0d2a42aab018.png)

When I disabled purpose-mode, my company mode behaviors normal now.

@syl20bnr  Any workaround? thanks.

**Comment by bmag** [comment]
Is the behaviour fixed if you enabled `purpose-mode`, but also call `purpose-x-kill-unset`? You can call it manually with `M-x`, or add it to `user-config`.

**Comment by zilongshanren** [comment]
@bmag 
It works like a charm 👍 

Thanks.

**Comment by d12frosted** [comment]
Thanks all! This is now fixed in develop. Closing issue since it appeared only on develop.
