### ISSUE TITLE
osx layer: CMD+ALT+H(Mac system shortcut for 'Hide Others') is caught by emacs, not the OS

### ISSUE THREAD

**Issue by basveeling** [syl20bnr/spacemacs#7464]
#### Description :octocat:
CMD+ALT+H(Mac system shortcut for 'Hide Other Windows') is caught by emacs, not the OS

#### Reproduction guide :beetle:
- On OSX:
- Start Emacs
- Enable 'osx' layer
- (Restart Emacs)
- Press CMD+ALT+H

*Observed behaviour:* :eyes: :broken_heart:
```M-s-˙ is undefined```

*Expected behaviour:* :heart: :smile:
Other programs are hidden, except Emacs.

#### System Info :computer:
- OS: darwin (OS X El Captain)
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript osx auto-completion emacs-lisp git org bibtex
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking
            (latex :variables latex-build-command "LatexMk")
            syntax-checking pdf-tools pandoc deft)
```

#### Backtrace :paw_prints:
```
M-s-˙ is undefined
```

**Comment by d12frosted** [comment]
Well, to be precise, this is how it works in plain GNU Emacs. And I am not sure how to fix that. And I never really looked into it, because I don't use hide others feature.

**Comment by basveeling** [comment]
Fair enough, looks like this was changed with the new emacs version (25.1.1). Emacs 24.5 doesn't capture the shortcut, but I couldn't figure out what has changed that causes this.

**Comment by d12frosted** [comment]
If you ever find a solution, could you please share it here? :D Or even send PR with workaround for this issue. 💃

**Comment by basveeling** [comment]
setting `(global-set-key (kbd "M-s-˙") 'ns-do-hide-others)` in user-config did the trick. I'll send a pull request for the osx layer, we can debate if this should be default behavior.

**Comment by pavopax** [comment]
for some reason, I get different behavior with left vs right keyboard keys, so I have:

    (global-set-key (kbd "M-s-˙") 'ns-do-hide-others)
    (global-set-key (kbd "M-s-h") 'ns-do-hide-others)

macOS sierra 10.12.2
GNU Emacs 25.1.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2016-09-20

**Comment by vv111y** [comment]
fwiw I added
```(global-set-key (kbd "H-h") 'ns-do-hide-emacs)```

so that command-h hides emacs as is normal for osx
