### ISSUE TITLE
Quitting Emacs brings up HELM Persp Save To File By Names

### ISSUE THREAD

**Issue by laMudri** [syl20bnr/spacemacs#7467]
#### Description :octocat:
Quitting Emacs brings up HELM Persp Save To File By Names

#### Reproduction guide :beetle:
- Start Emacs
- Open a file
- Close the file (`ZZ`, `ZQ`, &c) or quit Emacs using SIGTERM

*Observed behaviour:* :eyes: :broken_heart:
Emacs quits.

*Expected behaviour:* :heart: :smile:
There is a buffer titled “HELM Persp Save To File By Names”, which doesn't seem to do much. The only way to get past it is to send a SIGKILL to emacs (SIGTERM brings up the HELM buffer again).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. f6245bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(agda auto-completion emacs-lisp nixos
      (shell :variables shell-default-shell 'ansi-term shell-default-position 'right))
```

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/7409
