### ISSUE TITLE
Eshell buffers are excluded from the list of switchable buffers once you switch projects

### ISSUE THREAD

**Issue by bleggett** [syl20bnr/spacemacs#7468]
#### Description :octocat:

Eshell buffers are excluded from the list of switchable buffers once you switch projects.
#### Reproduction guide :beetle:
- Start Emacs
- `M-x eshell`
- Switch to another buffer
- `SPC b b`
- Note that `eshell` is listed.
- `SPC p l` and switch to a project.
- `SPC b b`
- Note that `eshell` is now missing from the buffer list.
- `M-x eshell`
- Note that the old `eshell` session is resurrected into the current buffer
- `SPC b b` and note that `eshell` still does not appear in the buffer list.

_Observed behaviour:_ :eyes: :broken_heart:

_eshell_ buffer is never listed in active buffers list once inside of a projectile project

_Expected behaviour:_ :heart: :smile:

To see _eshell_ buffer in active buffers list when in a projectile project.
#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(yaml helm
      (version-control :variables version-control-diff-tool 'diff-hl)
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
      windows-scripts sql
      (javascript :variables javascript-disable-tern-port-files nil)
      html syntax-checking emacs-lisp git github org markdown pandoc colors evil-commentary react docker
      (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```

**Comment by TheBB** [comment]
Can't reproduce.

**Comment by bleggett** [comment]
Updated to latest helm (20161017.2343) and I'm no longer having the problem.

**Comment by bleggett** [comment]
Ok, reopening this after some more experimentation. `eshell` buffers do drop out of existence in a confusing way on project switch, so I think there is still a bug.
