### ISSUE TITLE
matlab-mode comments color

### ISSUE THREAD

**Issue by Mengesh** [syl20bnr/spacemacs#7469]
#### Description :octocat:

Comments in `.m` files are not colored well in `matlab-mode` if they contain a number and some
operation symbol like `+-*/`.
#### Reproduction guide :beetle:
- Start Emacs
- Open `.m` file
- Load `matlab-mode`

_Observed behaviour:_ :eyes: :broken_heart:
The color of _comment_ lines are different

_Expected behaviour:_ :heart: :smile:
The color of all _comment_ lines should be the same regardless of the comment text
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 better-defaults emacs-lisp git markdown pandoc org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking extra-langs ranger semantic gtags
 (python :variables python-enable-yapf-format-on-save t)
 (latex :variables font-latex-fontify-script nil latex-enable-auto-fill t latex-enable-folding t))
```

**Comment by TheBB** [comment]
This reproduces in emacs -q with matlab-mode and highlight-numbers-mode, therefore one of these is the culprit.

**Comment by Mengesh** [comment]
So I guess the workaround would be 
```
 (remove-hook 'matlab-mode-hook 'highlight-numbers-mode)
```
but it doesn't work for me.

**Comment by TheBB** [comment]
Because `highlight-numbers-mode` isn't in `matlab-mode-hook`, it's in `prog-mode-hook`.

**Comment by Mengesh** [comment]
That makes sense :)

**Comment by jb55** [comment]
(triage) is there anything left to do here?

**Comment by DvdMgr** [comment]
Wouldn't removing highlight-numbers-mode from prog-mode-hook affect other modes, too?

I found that adding an entry to the hash table highlight-numbers-modelist with key 'matlab-mode and symbol 'do-not-use works, too!

**Comment by braham-snyder** [comment]
it would, but I don't think anyone was suggesting that was a satisfactory solution, only that it was sufficient

adding an entry to `highlight-numbers-modelist` works, as does the following:

```
    (add-hook 'matlab-mode-hook
            ;; `highlight-numbers-mode' breaks MATLAB comment coloring --
            ;; `highlight-numbers-mode' is mostly redundant with
            ;; `rainbow-identifiers-mode' anyway
            (lambda ()
              (highlight-numbers-mode -1))
            ;; We must append the above *after* `spacemacs/run-prog-mode-hooks'
            ;; in `matlab-mode-hook', since the former hook enables
            ;; `highlight-numbers-mode'. Note that
            ;; `spacemacs/run-prog-mode-hooks' is manually added to
            ;; `matlab-mode-hook' by Spacemacs since the upstream `matlab-mode'
            ;; package does not derive `matlab-mode' from `prog-mode' (oddly --
            ;; IIRC the author refused to do so for compatibility with XEmacs).
            'append)
```

which is quite confusing in that it requires appending to achieve the expected effect (whereas, normally, the `prog-mode-hook` will always run before any functions in the derived mode's hook). Perhaps we could change where `spacemacs/run-prog-mode-hooks` is called to avoid this situation more generally?

**Comment by DvdMgr** [comment]
That explains why the hook didn't seem to work when I was toying with it, nice to know!
