### ISSUE TITLE
How do you stop dired from opening in a split window by default?

### ISSUE THREAD

**Issue by synic** [syl20bnr/spacemacs#7471]
On the master branch, when I press `RET` on a file, the dired buffer is replaced by the file that I want to open.

On the develop branch, it now opens the file in a split, if there is a split open.

I do not like this behavior, but I can't figure out how to disable it.  What dired changes were made?

**Comment by TheBB** [comment]
This is probably purpose. Let's keep it in https://github.com/syl20bnr/spacemacs/issues/7453.
