### ISSUE TITLE
Feature Request - Rust Layer "compile/run with verbose"

### ISSUE THREAD

**Issue by randre03** [syl20bnr/spacemacs#7474]
When using the Rust layer one can run `SPC-M-C-x` to compile & run code using the function `Cargo-process-run`. If/when the code does not compile due to errors, Cargo will indicate the error(s) causing it to not compile and indicate that you can re-run the command and get additional information using the `--verbose` tag.

Is there a way to add an option under `SPC-M-C` that would run `Cargo-process-run` but with the 
`--verbose` flag?

**Comment by TheBB** [comment]
Should probably be a feature request to cargo, not us.

**Comment by randre03** [comment]
Maybe I did not describe this well enough. Cargo already allows one to issue the command with the --verbose tag. I'm asking if that functionality could be added to the Rust layer such that under the prefix SPC-M-C there would be a new item (v?) that would correspond to issuing the Cargo run command with the --verbose flag.

________________________________

**Comment by bmag** [comment]
There is Cargo, and then there is [`cargo.el'](https://github.com/kwrooijen/cargo.el). We use `cargo.el` as an interface to Cargo, and I don't see there explicit support for verbose, so you can make a feature request to `cargo.el`. But, I think it is unnecessary.

In Emacs, it is normal for compilation commands to let you change the raw command line when called with a universal argument (`C-u` in stock Emacs, `SPC u` in Spacemacs). From reading the source of `cargo.el` ([here](https://github.com/kwrooijen/cargo.el/blob/master/cargo-process.el#L198)), it appears that if you run `SPC u SPC m c x`, then you can manually add the `--verbose` flag. If that's not good enough, then I do suggest a report upstream to `cargo.el`.

**Comment by TheBB** [comment]
Yes, I meant of course the Emacs cargo package, not the actual CLI tool cargo.

**Comment by nugend** [comment]
As a workaround, you can set CARGO_TERM_VERBOSE=true in your environment.

I imagine it's probably pretty easy to work up a toggle for that.
