### ISSUE TITLE
add support for the evil-search module

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7475]
update: 

It could be implemented as a variable that the user may set in his .spacemacs. like evil-search nil. If set to tthen spacemacs uses the evil-search instead of emacs' iSearch.

this is very useful for folks that got used to the `gn` text object from vim. Evil implements the [gn](http://vimcasts.org/episodes/operating-on-search-matches-using-gn/) text object, but only if you use evil-search instead of ISearch for the evil-search-module. 

[Here](https://bitbucket.org/lyro/evil/issues/327/gn-motion-not-implemented-yet) is the relevant issue on bitbucket that caused the gn text object to be implement in evil.

if you install evil by hand, and issue `/` to enter the search minibuffer, pressing ESC does not exit the search minibuffer. it instead triggers which-key with a hell of a lot of options.

But within in spacemacs, it just works. I press esc and I'm out of the `/` minibuffer. 

Can you share your wisdom and knowledge if us poor people? 

How did you manage do configure that?

**Comment by ninrod** [comment]
I think I've found the answer. I'll document it here for posterity's sake:

steps to find the answer:

1. type `/` to enter search state.
2. type `C-h k` and then escape. so that emacs tells us what is bound to `<ESC>` in this scenario
3. we see that `<ESC>` is really bound to `(isearch-cancel)`, which does not reveal the answer but sheds a huge light on the solution. 
4. now armed with that information we navigate to `~/.emacs.d` where the spacemacs installation lives. 
5. realize that spacemacs devs must have bound `isearch-cancel` in some way, so we must find that.
6.  so we must use ag (or grep) to search for `isearch-cancel` in the whole spacemacs installation: `ag isearch-cancel`, which returns the following: 

```shell
.emacs.d ➜  ag isearch-cancel
layers/+distributions/spacemacs-base/keybindings.el
84:(define-key isearch-mode-map (kbd "<escape>") 'isearch-cancel)
.emacs.d ➜
```
7. add that to your config
8. ???
9. profit.

**Comment by TheBB** [comment]
So is there anything left to do here?

**Comment by ninrod** [comment]
well, not so fast @TheBB, I think there's and edge case.

this works if you did not use `'(evil-search-module (quote evil-search)) ` on your customization section. I would you use that, you ask?

well you would use that if you wanted to use the [gn](http://vimcasts.org/episodes/operating-on-search-matches-using-gn/) text object, which evil implements if you customize as describe by the above paragraph. 

Now if you did customize that, then the solution does not work. 

With even more research, I found that this works:

```elisp
(define-key evil-ex-search-keymap (kbd "<escape>") 'minibuffer-keyboard-quit)
```

but it seems to be a bit forceful, because emacs gets angry and beeps at me writing `Quit` in the echo area. 

@TheBB, I don't think spacemacs is configured to handle this scenario, do you agree?

**Comment by ninrod** [comment]
`(define-key evil-ex-search-keymap (kbd "<escape>") 'minibuffer-keyboard-quit)` is the solution if you use the `evil-search` module for the `gn` text object. 

@TheBB, I'll leave this open because I believe that spacemacs does not configure `<ESC>` if the user configures `evil-search` as the search module.

**Comment by TheBB** [comment]
Well, Spacemacs sets the search module to isearch. No guarantees are made for other settings.

I ask again what we are doing here. You've asked a question and answered it.

Is this a feature request that we support evil-search as a search module with all the features of isearch? Because if so that is not clear at all.

**Comment by ninrod** [comment]
Yes, I think spacemacs ought to consider to include support for the `gn` text object because it is really useful and a bunch of vim expatriates are used to it. As spacemacs is a platform for vim expatriates to land with comfort, I think it really makes sense. 

Plus, I thought this issue would pose as an instructional issue for folks that want to dig a little bit below the surface and answer their own questions about how spacemacs does things.

I'll change the title accordingly.

**Comment by e-matteson** [comment]
I've been using evil-search for a while and don't see any problem. I just have `(setq evil-search-module (quote evil-search))` in `dotspacemacs/user-init()`, and `escape` quits the `/` minibuffer correctly. Specifically, it's mapped to `keyboard-escape-quit` in `evil-ex-search-keymap`.

Besides your `escape` issue, what would it mean for spacemacs to add more support for evil-search?

**Comment by ninrod** [comment]
@e-matteson, that was my initial doubt. If this is indeed working like you describe in spacemacs, then I really see no reason to keep this opened. This issue stands as documentation should a spacemacs user wants to use the evil-search-module. 

just set `(setq evil-search-module (quote evil-search))` in `dotspacemacs/user-init()` as @e-matteson  described. end of story. 

thank you very much gentleman.

**Comment by ninrod** [comment]
@e-matteson, do you use `cgn` in your setup? 

when you type a search with `/` and substitute the first match with `cgn`, does applying successively `.` commands changes the next patterns as well? 

I tried to set `(setq evil-search-module (quote evil-search))` and it did not work. 

The only way that I know of to set that right is to apply this setting on the customization section like demostrated [here](https://github.com/ninrod/dotfiles/blob/6698719103ba3a3ab61d91a8458054d623c858c6/emacs/emacs-customizations.el#L6).

**Comment by e-matteson** [comment]
Yes, I just tested it and `cgn` works with `.` commands. That's a neat trick, thanks for showing me!

What do you mean by "it did not work"? Did it not change the search module? Did just `escape` or `cgn` not work?

**Comment by ninrod** [comment]
yes, the gn text object is __[awesome](http://vimcasts.org/episodes/operating-on-search-matches-using-gn/)__. 

the `gn` text object did not work for me with only that line. Are you sure you don't have [this](https://github.com/ninrod/dotfiles/blob/999ad8766228bf5cde3d6172d101f1a0a70a9d86/emacs/emacs-customizations.el#L6) line on your customization section?

**Comment by e-matteson** [comment]
Nope, I'm only ever setting it in `user-init`.  I'm using `develop`, updated today. Maybe try out a clean install of spacemacs with the default `.spacemacs`, and see if it works there?

**Comment by ninrod** [comment]
Ok, then it must be something on my end. No big deal. Thanks again.
