### ISSUE TITLE
C/C++ mode comment indentation error

### ISSUE THREAD

**Issue by sachdevaprash** [syl20bnr/spacemacs#7476]
#### Description :octocat:
Indentation of comments fails in C/C   mode
#### Reproduction guide :beetle:
- Start Emacs
- Create a C   file.
- Write the code: 
```
int main(){
// alpha
}
```
- Try to indent comment line

*Observed behaviour:* :eyes: :broken_heart:
Comment line fails to indent correctly

*Expected behaviour:* :heart: :smile:
Comment line is indented

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.0.50.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(python ivy auto-completion emacs-lisp git org
        (mu4e :variables mu4e-installation-path "/usr/local/share/emacs/site-lisp" mu4e-mu-binary "/usr/local/bin/mu" mu4e-enable-mode-line t mu4e-enable-notifications t)
        syntax-checking version-control pdf-tools c-c  )

**Comment by d12frosted** [comment]
> Try to indent comment line

Hey, it would be helpful to know how exactly you try to indent it 😸

**Comment by sachdevaprash** [comment]
Certainly. It's using ```<TAB>``` key or ```c-indent-line-or-region```

**Comment by TheBB** [comment]
You're aware that `TAB` will not add or remove indent, right? It will just reset the indentation of the current line if it happens to be off.

**Comment by sachdevaprash** [comment]
Yes, so is a comment inside a function intended to be unindented?

I expect ```TAB``` to place indentation of the comment in line with the code indentation, i.e.,
**Expected behavior**
```
int main(){
    //alpha
    return 0;
}
```
**Current behavior**
```
int main(){
//alpha
    return 0;
}
```

**Comment by TheBB** [comment]
I get your expected behaviour, not your current behaviour.

**Comment by d12frosted** [comment]
What is the value of `c-indentation-style`? I mean, in some styles your behaviour might be valid. I am not sure (can't check right now), but I think there is configuration named `comment-intro` for offsets which might be set to something you don't like 😸

**Comment by sachdevaprash** [comment]
Alright. c-default-style does it. It got accidentally set to ```bsd``` it seems. Thanks for the help!
