### ISSUE TITLE
spacemacs initialisation on windows ignores customisation of projectile-generic-command

### ISSUE THREAD

**Issue by puzl** [syl20bnr/spacemacs#7478]
#### Description :octocat:
spacemacs initialisation on windows ignores customisation of projectile-generic-command

#### Reproduction guide :beetle:
- Start Emacs
On windows
customise projectile-generic-command
restart emacs
examine variable projectile-generic-command
see that customisation isn't applied

*Observed behaviour:* :eyes: :broken_heart:
Can't tune projectile for your local system

*Expected behaviour:* :heart: :smile:
Projectile customisations should be applied

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. 5ae2605)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(version-control python org markdown emacs-lisp spell-checking gtags semantic
                 (syntax-checking :variables flycheck-disabled-checkers
                                  '(c/c++-clang c/c++-gcc)
                                  flycheck-cppcheck-checks "style")
                 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
                 (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-emable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
                 (shell :variables shell-default-height 30 shell-default-term-shell "/bin/bash" shell-default-position 'bottom))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by puzl** [comment]
I have a fix for this.  Will submit a PR soon.

**Comment by TheBB** [comment]
This is just another aspect of https://github.com/syl20bnr/spacemacs/issues/5170.
