### ISSUE TITLE
Change the default escape sequence to something else

### ISSUE THREAD

**Issue by tuhdo** [syl20bnr/spacemacs#748]
The default <kbd>fd</kbd> can be confused with "fd" as in "file descriptor", a common variable name, or "df", a disk space utility checking. I propose changing the sequence to <kbd>jj</kbd> or <kbd>jk</kbd> or <kbd>qq</kbd>.

**Comment by syl20bnr** [comment]
`jj` and `jk` cannot be used, see the note in the documentation: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.md#escaping

There is no mnemonic for this sequence, as there is no mnemonic with `jj` of `jk`, the main reason about the choice of `fd` is that it is on the home row.

I won't change the default to `fd` in spacemacs but you can customize it to your liking as it is described in the link above.

**Comment by tuhdo** [comment]
I can understand about `jj`. How about `jk` or `,,`? Could it be used to escape everything? I imagine that someone in insert state and want to type `fd` as variable name, and got escaped into normal mode. It's quite annoying. Of course I can always change it but there are potential future users who may get into that scenario.

**Comment by syl20bnr** [comment]
Indeed `fd` can be required to be inserted like any other sequence you could imagine. I cannot find the perfect sequence that no one needs to enter ever, `fd` is a reasonable choice. Now it cannot be a silver-bullet for everybody, hence the possibility to customize it.

**Comment by tuhdo** [comment]
Alright that's fine then. I'm closing this. However, is it possible to have `evil-escape` supporting `q`, so I can use `qq` to return to normal mode?

**Comment by syl20bnr** [comment]
@tuhdo officially only the keys defined in the `evil-motion-state-map`, making it work for other keys requires to support it explicitly. But it may work with `qq`, did you try it ?
If it works then you will loose `q` evil key binding which is `start keyboard macro recording`.
