### ISSUE TITLE
A modified fileless buffer gets deleted without confirmation

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#7487]
#### Description :octocat:

Any text that has been written in a new buffer, that hasn't been saved to a file yet, will be lost right away if one deletes that buffer, because there's no confirmation before it gets deleted.
#### Reproduction guide :beetle:
- Start Emacs
- Open a new buffer <kbd>SPC b N</kbd>
- Add some text, f.ex. a lorem ipsum paragraph: <kbd>SPC i l p</kbd>
- Delete the buffer <kbd>SPC b d</kbd>

_Observed behaviour:_ :eyes: :broken_heart:

The buffer gets deleted instantly without asking for confirmation first.

_Expected behaviour:_ :heart: :smile:

It should probably ask for confirmation first.
#### Possible prompt message (or something better):
- This buffer isn't associated with a file, kill it anyway? (y or n)
- This buffer has not been saved to a file, kill it anyway? (y or n)

slightly shorter:
- Buffer not associated with a file; kill anyway? (y or n)
- Buffer not saved to a file; kill anyway? (y or n)

The shorter messages would be similar to the current message that appears when one tries to delete a buffer containing a modified file:

> Buffer filename.txt modified; kill anyway? (y or n)
#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: develop (rev. b550945)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(auto-completion autohotkey emacs-lisp git helm)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by fiveNinePlusR** [comment]
There is a problem with this because emacs uses a lot of one-off special buffers. I would love to have this as a feature though but only for the buffers I create manually. (e.g. not a magit or helm buffer.)
