### ISSUE TITLE
chinese layer breaks org layer

### ISSUE THREAD

**Issue by leezu** [syl20bnr/spacemacs#7491]
#### Description :octocat:

If both the `chinese` layer and the `org` layer are activated, the org-refile functionality is broken.
#### Reproduction guide :beetle:
- Enable chinese layer and org layer
- Try to refile in org mode

_Observed behaviour:_ :eyes: :broken_heart:
The following error is displayed: `Wrong type argument: listp, quote`

_Expected behaviour:_ :heart: :smile:
Refiling should work.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t)
 (chinese :variables chinese-enable-fcitx t)
 emacs-lisp mu4e git
 (latex :variables latex-build-command "LatexMk")
 bibtex pdf-tools markdown
 (org :variables org-agenda-span 10 org-extend-today-until 5 org-agenda-start-on-weekday nil)
 (deft :variables deft-directory "~/Dropbox/org/deft" deft-recursive t deft-use-filter-string-for-filename t deft-use-filename-as-title t)
 syntax-checking typescript html javascript
 (python :variables python-enable-yapf-format-on-save t)
 semantic gtags
 (c-c++ :variables c-c++-enable-clang-support t c-c++-default-mode-for-headers 'c++-mode)
 finance)
```

**Comment by zilongshanren** [comment]
@leezu 
Could you reproduce this issue with the latest develop branch and the latest version of org?

I can't reproduce this issue on my side.

thanks.

**Comment by d12frosted** [comment]
> Spacemacs: 0.200.3
> Spacemacs branch: master (rev. b7e51d7)

This is pretty new 😸

**Comment by leezu** [comment]
Hm, I realized that by disabling the chinese layer, most of my custom configuration was not run anymore (as my custom configuration started with chinese layer related settings and (I assume) the configuration function would abort at that point given that the layer was not present). 

Sorry for the wrong attribution. I will investigate which part of my configuration breaks the refile functionality and post another comment here. 

On October 20, 2016 2:03:32 PM GMT+08:00, Boris <notifications@github.com> wrote:
>> Spacemacs: 0.200.3
>> Spacemacs branch: master (rev. b7e51d7)
>
>This is pretty new 😸 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/syl20bnr/spacemacs/issues/7491#issuecomment-255016796

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by leezu** [comment]
Sorry for the delay in following up on the issue. In the end it was due to a semantic error in my configuration of my org-refile-targets. Anyone who runs into similar issues is highly recommended to read about emacs lisp: https://tuhdo.github.io/emacs-tutor2.html
