### ISSUE TITLE
hybrid mode doesn't word well with iedit mode

### ISSUE THREAD

**Issue by liujoey** [syl20bnr/spacemacs#7493]
if use `hybrid` editing style, then the `iedit` can't start editing. It feels like in the `iedit` mode, the `ctrl` key is always be hold down. e.g. in `iedit` mode if I want to input char `s`, it will start I-Search.

EDIT: suddenly can't reproduce any more, probably my keyboard CTRL key got stuck....

**Comment by bmag** [comment]
Please follow https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report

**Comment by liujoey** [comment]
@bmag updated.
