### ISSUE TITLE
can people use powershell as the default shell in emacs?

### ISSUE THREAD

**Issue by chantisnake** [syl20bnr/spacemacs#7495]
or is there a way to use powershell in emacs?

**Comment by bleggett** [comment]
You can open a powershell buffer with `SPC a s p`. I'm not really sure what you mean by `default shell` though.

`M-x term` and `M-x ansi-term` will not work with Windows shells.

**Comment by rschuetzler** [comment]
@bleggett What layer do you have installed to see an option for `SPC a s p`? Because I don't have it.

**Comment by Ethergeist** [comment]
Not sure if @rschuetzler found the answer to his question, however the keybinds @bleggett mentions above are from the windows-scripts spacemacs layer.

**Comment by jiagoumengxiang** [comment]
I config ↓
----------init.el----------
windows-scprips    
(shell :variables
            shell-default-shell 'powershell
            shell-default-height 35
            shell-default-position 'bottom)
--------------
when I press ctl+' 

let: Wrong type argument: commandp, spacemacs/shell-pop-powershell

so I defun a fun spacemacs/shell-pop-powershell
so, it can open the powershell buffer,but also has some bug

so..how to use powershell in ctl+'

**Comment by bmag** [comment]
@jiagoumengxiang Setting `shell-default-shell` to `powershell` is not currently supported, but you can open powershell with `SPC a s p` as mentioned above. You are welcome to open a new feature request. (the other shells are defined with `make-shell-pop-command` in `shell/init-shell-pop`)

> `ctl+'`

You mean <kbd>SPC '</kbd>, right? (using Emacs notation for keys)

**Comment by bmag** [comment]
Anyway, I'm closing this issue since the questions have been answered. If someone wants to support powershell as the default shell, please submit a feature request or a pull request.
