### ISSUE TITLE
Improve documentation on setting `python-test-runner` in directory local variable

### ISSUE THREAD

**Issue by jluttine** [syl20bnr/spacemacs#7496]
Would it be possible to add explicit instructions on how to set `python-test-runner` in a directory local variable?

In https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/python#test-runner, it just says:

> To set project specific test runners you can set python-test-runner in a directory local variable in your project root. `SPC f v d` in Spacemacs. See the official documentation for more information.

I tried that, but: 

I chose `python-mode` and `python-test-runner` wasn't listed. I wrote `python-test-runner` anyway and set value `nose`. It created `.dir-locals.el` with the following contents:

```
((python-mode (python-test-runner . nose)))
```

I restarted Emacs and I get the following error now:

```
Symbol's function definition is void: nosetests-all
```

I'm a bit lost here, so I don't think the current documentation is sufficient or then I'm just missing something trivial.

**Comment by jluttine** [comment]
If I set it in my .spacemacs but not in .dir-locals.el, then it works:
```
(python :variables
             python-test-runner 'nose)
```
But I want to have pytest the global default, and use nose on some projects..

**Comment by TheBB** [comment]
You can set it to `(pytest nose)`. Then `pytest` is the default but `nose` will be loaded. Agree that this is needlessly complicated though.

**Comment by TheBB** [comment]
To be precise: the default global value must include every test runner you intend to use. The first one is the one that will be used by default. You can then change the value per project to use specific test runners.

**Comment by jluttine** [comment]
Ok, thanks! Now I got it working. :+1:

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/7498

**Comment by syl20bnr** [comment]
We should modify the python layer to handle the test runners _exactly_ like the ruby layer. I also find the list value not needed. `python-test-runner` should take only one runner and directory/file local variables should be used to alter it.

I like the idea of the universal argument to be able to choose a test runner though. It could popup a helm/ivy buffer to choose the runner. Can be applied to other layer.

In the end all this should land in the conventions file.

I have this on my todo list for a long time TBH :-(
