### ISSUE TITLE
On startup, this warning message appears: `(Spacemacs) Warning: tern binary not found!`

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#7497]
#### Description :octocat:

On startup, this warning message appears: `(Spacemacs) Warning: tern binary not found!`

This is a follow-up to #7452 based on same issue being also reported by @AndreaOrru and @liujoey .
#### Reproduction guide :beetle:
- Run `npm install -g tern`
- Enable `javascript` layer
- Start Emacs

_Observed behaviour:_ :eyes: :broken_heart:

Warning message: `(Spacemacs) Warning: tern binary not found!`

_Expected behaviour:_ :heart: :smile:

No warning message should appear.
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: develop (rev. b550945)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm auto-completion better-defaults clojure django emacs-lisp git github
      (go :variables go-use-gometalinter t)
      html javascript markdown
      (org :variables org-enable-github-support t org-enable-bootstrap-support t)
      osx python rust
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
      sql syntax-checking version-control yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES
#### Backtrace :paw_prints:

N/A

**Comment by TheBB** [comment]
I guess toggles are evaluated before packages are initialized (`exec-path-from-shell` particularly), even the `pre` or `bootstrap` step packages. Can we do something about this @syl20bnr?

**Comment by syl20bnr** [comment]
@TheBB hard one, looks like a chicken and egg problem. The bootstrap packages could be initialized before but I don't how hackish it will look like in the code.

**Comment by syl20bnr** [comment]
After investigation there is multiple issues unveiled by this behavior.

### exec-path-from-shell 

First `exec-path-from-shell` on my machine (macOS) works with XQuartz but not with the Cocoa application:

Output of XQuartz with `exec-path-from-shell-debug` on:

```
Invoking shell /bin/bash with args ("-l" "-i" "-c" "/usr/bin/printf '__RESULT\\000%s\\000%s' \"${PATH-0f261860db16caf8995e71f0a6a3aecd}\" \"${MANPATH-0f261860db16caf8995e71f0a6a3aecd}\"")
Shell printed: "__RESULT/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Users/sylvain/Library/Haskell/bin:/Users/sylvain/.i3ci/bin0f261860db16caf8995e71f0a6a3aecd"
Invoking shell /bin/bash with args ("-l" "-c" "/usr/bin/printf '__RESULT\\000%s\\000%s' \"${MANPATH-3ba9f5018dce4cca38566a33a4101be6}\" \"${PATH-3ba9f5018dce4cca38566a33a4101be6}\"")
Shell printed: "__RESULT3ba9f5018dce4cca38566a33a4101be6/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Users/sylvain/Library/Haskell/bin:/Users/sylvain/.i3ci/bin"
```

In the Cocoa app:
```
Invoking shell /bin/bash with args ("-l" "-i" "-c" "/usr/bin/printf '__RESULT\\000%s\\000%s' \"${PATH-7bb141f5ac3a9322698e747a892a4dfe}\" \"${MANPATH-7bb141f5ac3a9322698e747a892a4dfe}\"")
Shell printed: "__RESULT/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin7bb141f5ac3a9322698e747a892a4dfe"
Invoking shell /bin/bash with args ("-l" "-c" "/usr/bin/printf '__RESULT\\000%s\\000%s' \"${MANPATH-00002e46c4a57fd18f2e94f5de611cea}\" \"${PATH-00002e46c4a57fd18f2e94f5de611cea}\"")
Shell printed: "__RESULT00002e46c4a57fd18f2e94f5de611cea/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin"
```

I put a tern executable placeholder in `.i3ci/bin`. No warning on XQuartz, but warning in Cocoa.

The solution is to manipulate `exec-path` manually in `dotspacemacs/user-init` function.

### :toggle relying on `exec-path-from-shell` cannot be installed

At installation time the packages are not yet initialized so `exec-path-from-shell` cannot do its job and the result is that tern cannot be installed since the `:toggle` evaluates to nil.

### Few possible issues with the home buffer

Were discovered while investigating but not fixing the current problem.
https://github.com/syl20bnr/spacemacs/commit/ee6c353
https://github.com/syl20bnr/spacemacs/commit/48c3ecd

**Comment by d12frosted** [comment]
@syl20bnr how do you start cocoa version of emacs? From terminal or from Finder/Spotlight/Launcher/Dock/etc? In case you use the latter method - you have to setup your environment variables not only using `export var=val`, but you have to also `launchctl setenv var val`, this specifies environment variable to be set on all future processes launched by `launchd` (when you start `.app` from Finder/etc) in the caller's context. If you wish to have good automated solution for this, checkout [solution proposed by yogsototh](https://gist.github.com/yogsototh/2c67171d203fcbf55bc5373d77cc378e).

**Comment by swaroopch** [comment]
> @syl20bnr wrote: The solution is to manipulate exec-path manually in dotspacemacs/user-init function.

I can confirm that adding `(setenv (concat (getenv "PATH") "/usr/local/bin"))` to my `dotspacemacs/user-init` made the warning go away.

**Comment by hnry** [comment]
Same issue as described by OP. But it should be noted tern in fact does run, everything works as normal, but the warning shows up anyway.

Also weird, the warning doesn't always show up, it's 50/50. But it _always_ works regardless of warning or not.

**Comment by syl20bnr** [comment]
@d12frosted thank you! 

@hnry @swaroopch so we need to dig deeper to find a way to reproduce it we your environments. Have you both tried last develop (I pushed commits this morning that may or may not fix your issue).

**Comment by swaroopch** [comment]
@syl20bnr Tried the latest develop branch, I see no warnings in the `*Messages*` buffer.

**Comment by liujoey** [comment]
@syl20bnr I tried the latest develop branch, no warning message.

**Comment by BelfordZ** [comment]
@d12frosted Thanks for the info -- I was running from Dock and running into a lot of these types of issues. Stopped using the dock and all is well.

**Comment by markmansour** [comment]
I receive this issue when attempting to install yaml-mode from windows.

**Comment by Arbitrageur** [comment]
In my case, I solved the problem by putting the NVM initialization codes in the .zshenv file.

I think that when you launch emacs from Alfred or spotlight, .zshrc or .zprofile are not sourced.
So, emacs couldn't have proper PATH variable.

On the other hand, .zshenv file is always sourced. 

I'm not sure that my case is the same with this. 

My case is
- OS : darwin
- Emacs : 25.1.1
- Spacemacs : 0.200.7
- Graphic Display : t
- Using node via NVM
- Launching emacs using Alfred

**Comment by rangelke** [comment]
Coud this be a related issue? #8296

**Comment by M3kH** [comment]
Same issue

- OS: Sierra 10.12.1
- SpaceMacs 0.200.7@25.1.1
- Node from homebrew but I also use N (equivalent node package to NVM)

**Comment by martinffx** [comment]
I'm experiencing the same issue. When I start emacs from spotlight it can't find the tern binary but when I launch from iterm it works perfectly. 

I've tried @Arbitrageur suggestion above and moved my nvm init to `~/.zshenv` but no luck I still get the same problem 😭 .

My `zshenv` file looks like this:

    # node
    export NVM_DIR="/Users/martinrichards/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
    [[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn

Am I perhaps missing something?

**Comment by Arbitrageur** [comment]
@martinffx You should try to put this at the first line
```sh
export PATH=/usr/local/bin:$PATH
```

zshenv is sourced at the very early stage of initialization. So, PATH must be almost empty.

**Comment by martinffx** [comment]
@Arbitrageur I've already got `export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"` as the first line. My path is a bit crazy atm...

```
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

# typesafe activator
export PATH=~/.activator/bin:$PATH

# heroku
export PATH="/usr/local/heroku/bin:$PATH"

# node
export NVM_DIR="/Users/martinrichards/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn

# python
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export WORKON_HOME=~/.venv

# ruby
export PATH="$HOME/.rbenv/bin:$PATH"

# java
export JAVA_HOME=$(/usr/libexec/java_home)
export SDKMAN_DIR="/Users/martinrichards/.sdkman"
export PATH="$HOME/.jenv/bin:$PATH"

# php
export PATH="$HOME/.phpenv/bin:$PATH"

# llvm
export PATH="/usr/local/opt/llvm/bin:$PATH"
```

**Comment by romariolopezc** [comment]
I have the same issue as @martinffx

**Comment by therimalaya** [comment]
I already have installed tern, it is in my path. I can access it from shell. But spacemacs is still warning  `- tern binary not found`.

**Comment by olessavluk** [comment]
I've created symlink in one of "default" folder and now tern works fine:
`ln -s /path/to/tern /usr/bin/tern`

**Comment by M3kH** [comment]
@olessavluk your solution doesn't work on OSX. Sorry.

**Comment by martinffx** [comment]
I've tried some of these to no effect:

https://emacswiki.org/emacs/EmacsApp
http://superuser.com/questions/476752/setting-environment-variables-in-os-x-for-gui-applications

**Comment by olessavluk** [comment]
@M3kH I am actually using OS X, and it works fine. And I see this a lot easier than tweaking `LaunchServices` or other os x internals. 

Please make sure you have created a correct symlink (try to run it via `/usr/bin/tern`), and you will also need to restart emacs (or re-run config).

**Comment by martinffx** [comment]
@olessavluk unfortunately your solution doesn't work for me either 😭 . 

After struggling a bit I got `LaunchServices` hack to work. With the help of [this](http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x/32405815#32405815) and [that](https://github.com/ersiner/osx-env-sync). 

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
      <dict>
        <key>Label</key>
        <string>com.user.loginscript</string>
        <key>ProgramArguments</key>
        <array>
          <string>bash</string>
          <string>-l</string>
          <string>-c</string>
          <string>
            $HOME/.bin/init.sh
          </string>
        </array>
        <key>RunAtLoad</key>
        <true/>
        <key>StandardErrorPath</key>
        <string>/tmp/login.log</string>
        <key>StandardOutPath</key>
        <string>/tmp/login.log</string>
      </dict>
    </plist>

My bash script looks like this:

    #! /bin/bash

    echo "setenv PATH"
    /bin/launchctl setenv PATH "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/martinffx/.pyenv/shims:/Users/martinffx/.config/fnm/bin:/Users/martinffx/.rbenv/bin";
    echo "PATH setenv"

Then check `/tmp/login.log`, I had all sorts of issues with my script not working correctly and couldn't track it down until I started logging what I was doing.

This too doesn't solve the issue for me. I've added the following to my `user-config` section:

      (print (getenv "PATH"))

and get the following:
```
"/Users/martinffx/.pyenv/shims:/Users/martinffx/.config/fnm/bin:/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9:/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_9:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/martinffx/.rbenv/bin"
```

tern is on that path `/Users/martinffx/.config/fnm/bin/tern` and `/usr/local/bin/tern`.

This is driving me mad?! What am I missing? @syl20bnr @d12frosted

**Comment by olessavluk** [comment]
@martinffx just place tern symlink into the `/usr/bin/tern`
(not into the `/usr/local/bin/tern` as you have done, because by default it is not included in `PATH` for gui applications)

**Comment by martinffx** [comment]
Thanks @olessavluk, but that folder is protected System Integrity Protection which needs to be disabled in order to place the symlink there. `csrutil disable` needs to be run in the Recovery OS, which is not ideal.

    $ sudo ln -s /Users/martinrichards/.config/fnm/bin/tern /usr/bin/tern                                                                           
    Password:
    ln: /usr/bin/tern: Operation not permitted

But I'll give it a try

**Comment by martinffx** [comment]
@olessavluk it worked! but I'd really like to know why it doesn't find it when it has been set via launchctrl?

**Comment by tarvos21** [comment]
@olejorgenb, thanks, I use `sudo ln -s /usr/local/bin/tern /usr/bin/tern`, and it works, now I start Emacs in Alfred or iTerm2, no warnings, great! I am on macOS Sierra 10.12.4.

**Comment by nickolasacosta** [comment]
@olessavluk  Thanks for this.  I have my npm global packages in a folder called .npm-global in my home folder so the symlink to the binary in the bin folder there works.

**Comment by jessecogollo** [comment]
the easy way is install tern using npm `npm i tern -g`

**Comment by martinffx** [comment]
@jessecogollo that installs tern that emacs can't find on startup. You need to symlink it into /usr/bin as per @olessavluk

**Comment by bheesham** [comment]
I installed tern using npm which installed it to `/usr/local/bin/tern` and the warning message went away.

Is this still an issue for people?

**Comment by roryk** [comment]
Yes, it is still an issue on OSX, it gets stuck in /usr/local/bin/tern but can't be found.

**Comment by djazo** [comment]
What if you add this to dotspacemacs/user-init:
`(add-to-list 'exec-path "/usr/local/bin")`

**Comment by olessavluk** [comment]
Recently, after updating emacs & packages, I discovered that this issue is no longer reproduced for me. No matter if I executed emacs from Terminal, Spotlight or Dock. So can just upgrade everything and remove all of your symlinks/launchd/exec-path hacks 😉

P.S. I am using: 
Emacs for Mac OS X v25.3
tern from `~/.nvm/versions/node/v8.9.0/bin/tern`

**Comment by yqrashawn** [comment]
If you using alfred launch emacs, simply kill emacs, quit alfred and reopen it with 
`open /Applications/Alfred\ 3.app`.   
 Emacs will works fine when you launch it via alfred next time.  

This works fine if you only launch emacs via alfred or ternimal. Dock, Finder, Launch pad won't work.

**Comment by kommen** [comment]
This is fixed for me on the latest develop branch, and there have been a bunch of tern related commits recently, most notably https://github.com/syl20bnr/spacemacs/commit/abf3df4ad79500d4f3a5b10da32c7955cfc855d0

**Comment by wlads** [comment]
> @martinffx just place tern symlink into the `/usr/bin/tern`
> (not into the `/usr/local/bin/tern` as you have done, because by default it is not included in `PATH` for gui applications)

In Mojave /usr/local/bin is included in /etc/paths - it worked for me ;)

**Comment by onemargaro** [comment]
This works for me.
```
➜ npm i -g ternjs
/Users/margaro/.nvm/versions/node/v8.11.1/bin/ternjs -> /Users/margaro/.nvm/versions/node/v8.11.1/lib/node_modules/ternjs/bin/tern
+ ternjs@0.22.0
updated 1 package in 0.629s

~
➜ sudo ln -s /Users/margaro/.nvm/versions/node/v8.11.1/lib/node_modules/ternjs/bin/tern /usr/local/bin/tern
```

**Comment by poglesbyg** [comment]
I just had to run
`npm i -g ternjs`
The error no longer appears after that.

**Comment by chnoack** [comment]
For the ones using Spacemacs: I encountered a similar problem with nvm. The node binary could not be found inside Spacemacs on Mac OS X. After cleaning up my .bash_profile and .bashrc I had to stop Spacemace, remove the .spacemacs.env and  restart Spacemacs. Only the the current PATH settings will be updated for Spacemacs.
