### ISSUE TITLE
markdown live preview not working

### ISSUE THREAD

**Issue by chantisnake** [syl20bnr/spacemacs#7499]
on windows 10 with emacs64 25.1 and just downloaded spacemacs yesterday

It always gives me `'markdown' is not recognized as an internal or external command, operable program or batch file.` no matter what I set `markdown-command` to.

![capture](https://cloud.githubusercontent.com/assets/10100995/19557754/17c9fcd4-96bf-11e6-8e70-aed69e6dfef3.PNG)

my current config file is like this:

``` lisp
  ;; markdown section
  ;; use pandoc as markdown compiler
  (custom-set-variables
   '(markdown-command "pandoc"))
```

and when I run `M-: (executable-find "pandoc")` it did gives me the location of pandoc

and I run pandoc in powershell it gives me the right thing too:

```
❯ pandoc .\test.md
<p>this is a test</p>
```

Is this issue with spacemacs (because I didn't see `markdown-command` in spacemacs document) or an issue with markdown mode.

**Comment by m-stolle** [comment]
Try using the absolute path, my value is value is "D:\\Tools\\PandaDoc\\pandoc.exe" and it works fine.

**Comment by MarcusE1W** [comment]
Hi I have got it working like this. In the layer configuration directly after markdown add:

```
     markdown
     (markdown :variables markdown-command "pandoc" )
```

With that I can export, preview (in a browser) or use live preview in spacemacs. However, the live preview is not realy live. It only updates the view when you save. Not sure if that is intendet or additional config can fix that.

It would probaly be good to update the markdown layer docu if this approach is correct.

**Comment by Zweihander-Main** [comment]
Got this initially working using WSL by installing markdown in a WSL shell:
`sudo apt-get install markdown`
and then setting the layer configuration:
```
markdown
     (markdown :variables markdown-command "wsl markdown")
```

This worked alright but I ended up switching to using `vmd` as described in the [layer docs.](https://www.spacemacs.org/layers/+lang/markdown/README.html)
