### ISSUE TITLE
README for the Dash layer should mention sqlite3 requirement

### ISSUE THREAD

**Issue by JAremko** [syl20bnr/spacemacs#7501]
[Helm Dash Requirements:](https://github.com/areina/helm-dash#requirements)  
  - helm
  - sqlite3

**Comment by slonari** [comment]
@JAremko  What we need to do here, can you help me to understand?

**Comment by JAremko** [comment]
@slonari  Mention somewhere in here https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Btools/dash#install that sqlite3 is required for the layer to be fully functional because it uses  "Helm Dash" package that needs sqlite3
