### ISSUE TITLE
Terminal buffer not a "last-buffer"?

### ISSUE THREAD

**Issue by pspencil** [syl20bnr/spacemacs#7505]
#### Description :octocat:

Terminal not considered a buffer when using `last-buffer`
#### Reproduction guide :beetle:
- Start Emacs
- Switch to another layout
- Open a terminal (`SPC a s t`)
- `SPC TAB`
- `SPC TAB`

_Observed behaviour:_ :eyes: :broken_heart:
Terminal buffer not returned to

_Expected behaviour:_ :heart: :smile:
Switching between terminal buffer and some other buffer
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:

``` elisp
((auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'cycle auto-completion-private-snippets-directory nil)
 fasd better-defaults emacs-lisp
 (latex :variables latex-enable-folding t)
 git evil-commentary markdown org ivy python java
 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
#### Backtrace :paw_prints:

```
```

**Comment by TheBB** [comment]
Can't repro, works fine here.

**Comment by Ps-Pencil** [comment]
EDIT: This seems to be about layouts. Pressing `SPC `` doesn't seem to add the terminal buffer to the current layout (is that the expected behaviour?).

**Comment by jdnavarro** [comment]
This is also happening to me.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: develop (rev. 452931b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm html auto-completion dash emacs-lisp git github haskell html java markdown osx
      (shell :variables shell-default-shell 'eshell shell-default-position 'right shell-enable-smart-eshell t)
      (scala :variables scala-enable-eldoc-mode t scala-auto-insert-asterisk-in-comments t scala-auto-start-ensime nil ensime-startup-snapshot-notification nil)
      search-engine spell-checking syntax-checking version-control yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by Ps-Pencil** [comment]
Temporary fix, `SPC l a` and select the terminal file to add that buffer to the current layout.

**Comment by jdnavarro** [comment]
It seems that this happens when more than 1 window is on display. With a single window there is no problem.

**Comment by Ps-Pencil** [comment]
@jdnavarro This happened to me on single window as well. The key here seems to be that the terminal buffer is only included in the default layout

**Comment by zorino** [comment]
I have a similar problem, when I close the current buffer and the last-buffer is *ansi-term* it won't switch to it.

**Comment by dcaixinha** [comment]
I'm also being affected by this. Is there any way to add a hook that will add the opened shell to the current layout?

**Comment by Miciah** [comment]
This looks like a duplicate of #5776.  Workaround:
```emacs-lisp
(setq persp-add-buffer-on-after-change-major-mode 'free)
```
