### ISSUE TITLE
Windows-purpose layer is automatically enabled

### ISSUE THREAD

**Issue by mkcode** [syl20bnr/spacemacs#7506]
#### Description :octocat:
Purpose-mode is enabled automatically without adding it to `dotspacemacs-configuration-layers`

One possible resolution would be to update the documentation to indicate that is automatically installed: https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bspacemacs/spacemacs-purpose/README.org#install

I doubt that is what we want though. It was very surprising to me to find that the behavior of simple buffer switching changed after an update. Ideally, we would not define the keybinding on | ~SPC r~ | either when the layer is not enabled.

#### Reproduction guide :beetle:
- Start Emacs without `windows-pupose` added to `dotspacemacs-configuration-layers`
- Observe that `purpose-mode` is enabled.

*Observed behaviour:* :eyes: :broken_heart:
`purpose-mode` is enabled.

*Expected behaviour:* :heart: :smile:
`purpose-mode` is not enabled.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: develop (rev. 48c3ecd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip nil auto-completion-complete-with-key-sequence "kj")
 better-defaults chrome
 (clojure :variables clojure-enable-fancify-symbols t)
 csv
 (dash :variables dash-at-point-legacy-mode t)
 emacs-lisp emoji
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 games
 (git :variables auto-revert-check-vc-info t evil-magit-want-horizontal-movement t magit-save-repository-buffers 'dontask magit-delete-by-moving-to-trash nil magit-wip-after-save-mode t magit-repository-directories
      '("~/src/projects/github" "~/src/pocket")
      vc-follow-symlinks t git-magit-status-fullscreen nil)
 github
 (gtags :variables helm-gtags-suggested-key-mapping t helm-gtags-prefix-key "" helm-gtags-pulse-at-cursor nil helm-gtags-display-style 'detail helm-gtags-fuzzy-match t helm-gtags-direct-helm-completing t)
 (helm :variables helm-follow-mode-persistent t)
 (html :variables web-mode-markup-indent-offset 2 web-mode-css-indent-offset 2 web-mode-code-indent-offset 2)
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 (javascript :variables js-basic-offset 2 js2-basic-offset 2)
 lua markdown
 (org :variables org-enable-github-support t)
 (osx :variables osx-dictionary-dictionary-choice
      (list "Dictionary" "Spanish - English" "German-English")
      osx-dictionary-separator "\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\n\n")
 pandoc plantuml prose
 (ranger :variables ranger-show-literal nil)
 restclient
 (ruby :variables ruby-enable-enh-ruby-mode nil ruby-version-manager 'rbenv ruby-test-runner 'rspec)
 ruby-on-rails search-engine selectric
 (shell-scripts :variables sh-indentation 2)
 sql spacemacs-helm
 (spell-checking :variables enable-flyspell-auto-completion nil)
 syntax-checking
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margins t)
 vinegar xkcd yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by TheBB** [comment]
Let's keep it to https://github.com/syl20bnr/spacemacs/issues/7453
