### ISSUE TITLE
activate hlint with intero

### ISSUE THREAD

**Issue by letheed** [syl20bnr/spacemacs#7508]
Intero decided to not add hlint to flycheck's next-checkers anymore (see [here](https://github.com/commercialhaskell/intero/commit/06527fc4c9a5239e7921845f9c7cd4d2783eb030)). Is it possible to add it again/add an option to activate it? Both the `'ghci` and the `'ghc-mod` completion backends turn hlint on by default.

**Comment by TheBB** [comment]
Just (re)define your own checker with the definition as it used to be.

**Comment by letheed** [comment]
I did try to add
```
 (flycheck-add-next-checker 'intero
                            '(warning . haskell-hlint))
```
to my user-config but to no avail.
I also tried readding `:next-checkers '((warning . haskell-hlint))` in intero.el.

**Comment by TheBB** [comment]
Is there a reason you can't just do 

```elisp
(flycheck-define-generic-checker 'my-intero
  "A syntax and type checker for Haskell using an Intero worker
process."
  :start 'intero-check
  :modes '(haskell-mode literate-haskell-mode)
  :next-checkers '((warning . haskell-hlint)))
```

Then use the `my-intero` checker?

**Comment by letheed** [comment]
Wouldn't that bypass the intero setup from the layer?

**Comment by TheBB** [comment]
I don't know.

What was the problem with using `flycheck-add-next-checker`?

**Comment by TheBB** [comment]
Sample IELM session where I try it out.

```elisp
ELISP> (defun intero-check ())
intero-check
ELISP> (flycheck-define-generic-checker 'intero "Doc" :start 'intero-check :modes '(haskell-mode literate-haskell-mode))
2 (#o2, #x2, ?\C-b)
ELISP> (flycheck-checker-get 'intero 'next-checkers)
nil
ELISP> (flycheck-add-next-checker 'intero '(warning . ada-gnat))
((warning . ada-gnat))
ELISP> (flycheck-checker-get 'intero 'next-checkers)
((warning . ada-gnat))
```

**Comment by letheed** [comment]
`flycheck-add-next-checker` had no effect, the warnings didn't show up.
I'll be honest I'm not too familiar with the lisps nor emacs/spacemacs internals so it might be that it was evaluated too early or too late. I just added-it at the end of my user-config and then opened a haskell file.
If I define my own checker like you suggested, I miss on all the interno setup from the haskell layer.

**Comment by TheBB** [comment]
I assume the intero checker has to be defined *first*, so you need to do

```elisp
(with-eval-after-load 'intero
  (flycheck-add-next-checker ...))
```

There could be a million other reasons why the warnings don't show up, I'm more interested in if the actual setting is saved. I.e. if `(flycheck-checker-get 'intero 'next-checkers)` returns what you expect. If it does then great, if not then your problem is *something else*.

> If I define my own checker like you suggested, I miss on all the interno setup from the haskell layer.

There's no intero setup in the haskell layer that has anything to do with the flycheck checker. If there are anything else you need to do it's in intero.el, not in the layer. There can't be much though since the checker definition is so short, it just points straight to a function and since your new checker points to the same function then… well…

**Comment by letheed** [comment]
If I use `'my-intero`, I don't have `SPC m i`

**Comment by letheed** [comment]
I do get this:
```
ELISP> (flycheck-checker-get 'intero 'next-checkers)
((warning . haskell-hlint))
```
But the lints don't show up.

**Comment by TheBB** [comment]
Your code does what it should though, you have the same checker definition as before. So your problem is something else.

**Comment by letheed** [comment]
Well, I've tried a ton of things and a can seem to get both to work at the same time.

**Comment by clojj** [comment]
Does anyone know why hlint was removed in intero in the first place ..?

**Comment by letheed** [comment]
Thanks, I tried again and it's working now. Really not sure what was wrong before, that's the exact same code I had. ¯\_(ツ)_/¯

**Comment by TheBB** [comment]
I assume that means I can do this.

**Comment by letheed** [comment]
Yes, thanks.
