### ISSUE TITLE
Buffers glued to windows

### ISSUE THREAD

**Issue by quicknir** [syl20bnr/spacemacs#7509]
#### Description :octocat:
Buffers get "glued" to windows in develop.

#### Reproduction guide :beetle:
- Start Emacs, be on develop branch
- Hit `SPC w \` to do a vertical split.
- Hit `SPC f e d` to bring up dot file in the left split.
- Switch to the right split.
- Hit `SPC f e d` again

*Observed behaviour:* :eyes: :broken_heart:
Focus switches to left split.

*Expected behaviour:* :heart: :smile:
Bringing up the dotfile in the right split as well

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion git helm version-control ycmd syntax-checking emacs-lisp cpp2 python markdown javascript lua
                 (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "/spare/local/nir/zsh/bin/zsh" multi-term-program "/spare/local/nir/zsh/bin/zsh")
                 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND DBUS NOTIFY ACL LIBSELINUX LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB X11

I strongly suspect that this is related to purpose. When I switched back to master, purpose was uninstalled and behavior was immediately fine. I have no concrete evidence though.

**Comment by TheBB** [comment]
Let's keep it to https://github.com/syl20bnr/spacemacs/issues/7453
