### ISSUE TITLE
Unexpected results if evil-shift-width and language indent aren't the same

### ISSUE THREAD

**Issue by exitface** [syl20bnr/spacemacs#751]
Not experiencing this issue with vanilla evil

```ruby
def meth
  do_something
  my_collection.each do |item|
    if item == something
      do_something_else
    end
  end
end
```
With the cursor at the top of the file typing `>G` results in

```ruby
    def meth
    do_something
    my_collection.each do |item|
        if item == something
        do_something_else
        end
    end
    end
```

This can be fixed via setting evil-shift-width in the .spacemacs file

```
(custom-set-variables
 '(evil-shift-width 2))
```

But obviously is going to break languages that don't use 2 spaces.

**Comment by syl20bnr** [comment]
Thank you for spotting another inconsistency.

`>G` works here, the indentation is preserved but everything is shifted by 4 spaces instead of 2.
Same when using `>`.

When you say that it does not happen in vanilla evil , do you mean that in vanilla evil everything is shifted by 2 characters by default ?

**Comment by exitface** [comment]
Sorry, to clarify, with [this](https://gist.github.com/exitface/6799f3e32cadc039a54b) init.el, everything is indented 4 characters, but the indentation of the code blocks doesn't get messed up:

So with the above example, with the cursor at the top of the file typing `>G` results in

```ruby
    def meth
      do_something
      my_collection.each do |item|
        if item == something
          do_something_else
        end
      end
    end
```

**Comment by syl20bnr** [comment]
This is what I get, I will try with an up to date evil.

**Comment by syl20bnr** [comment]
Confirmed to work with `evil-20150218.13` and to break with the next release `evil-20150219.53`. Seems there was something different regarding indentation between these 2 releases.

**Comment by exitface** [comment]
I was using a very old version (2014) of evil, I just updated to the latest version and have the same result. [This is the offending commit](https://github.com/emacsmirror/evil/commit/4af09ecefbd153dcd3318aa7003f79e38ded345d).

**Comment by StreakyCobra** [comment]
It's a consequence of `evil-shift-round` being `t`. @TheBB doesn't like its default value as he explained in one of his video. Maybe we should think about setting it to `nil` as default?

@exitface Customize your `.spacemacs` with [this](https://github.com/TheBB/dotfiles/blob/master/emacs/spacemacs.el#L143).

**Comment by syl20bnr** [comment]
@StreakyCobra @TheBB I'm not sure this is a good thing to put it to nil because the issue we fix on one side creates the exact same issue on the other side. By other side I mean "someone wanting to fix the indentation in a file" (say everything is indented with 3 spaces and the user want 4 instead).

The issue here seems to be the round operation which should round to the _next_ nearest tab instead of allowing to go backward.

**Comment by syl20bnr** [comment]
The round may fill more natural to people because it makes it behave like hard tabs in a word processor. I do fill that this is how tab should work, if you want 4 spaces not aligned on hard tab then we can use `4i `.

**Comment by TheBB** [comment]
Looks like a candidate for a FAQ then.

**Comment by StreakyCobra** [comment]
@TheBB Ok, can you add the `beginner friendly` tag then :smile:

**Comment by syl20bnr** [comment]
We should also thix this in evil if we want to address this issue:

> should round to the next nearest tab instead of allowing to go backward.

**Comment by StreakyCobra** [comment]
I just reproduced this bug on a stock Emacs with `ruby-mode` and `evil`. You can try with the last Spacemacs version with `SPC q D ruby-mode,evil RET`. This is not a Spacemacs bug and should be reported upstream (not sure on which project though).
