### ISSUE TITLE
Helm autocompletion not working over ssh

### ISSUE THREAD

**Issue by Hajto** [syl20bnr/spacemacs#7510]
#### Description :octocat:

No SSH autocompletion in helm file finder (C-x C-f) (it was present before update).
#### Reproduction guide :beetle:
- Start Emacs
- C-x C-f
- type /ssh:

_Observed behaviour:_ :eyes: :broken_heart:
No autocompletion, no remote file browsing
If typed manually like user@server:files and hit enter no reaction. On previous version the file would open after a short while.

_Expected behaviour:_ :heart: :smile:
Autocompletion of remote server folders.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(auto-completion better-defaults emacs-lisp git react html javascript markdown elixir org yaml jekyll spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by TheBB** [comment]
You have to type `/ssh:`, not `ssh:/`.

**Comment by Hajto** [comment]
That what I meant, sry for typo.

**Comment by TheBB** [comment]
Okay… well, it works here.

**Comment by Hajto** [comment]
I just installed on second computer with OS X.


#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

**Comment by Hajto** [comment]
Same behavior on system 3:

System Info :computer:

OS: darwin
Emacs: 24.5.1
Spacemacs: 0.200.2
Spacemacs branch: master (rev. 7bdde17)
Graphic display: t
Distribution: spacemacs
Editing style: emacs
Completion: helm
Layers:
(yaml python c-c++ auto-completion emacs-lisp react better-defaults javascript git markdown
      (markdown :variables markdown-live-preview-engine 'vmd)
      elm elixir rust)

**Comment by joefromct** [comment]
Not sure if this is related, however I believe I'm having this issue on Emacs on windows, with `cmd.exe` as my shell, and `plink` as my connection method for tramp.  

If i use `M-x find-files` i can use something such as `//plink:test-server:/` `RET` and then get prompts and i'm in with `dired`. 

However with `spacemacs/helm-find-files` it appears to do nothing. 

I just was going to live with it as it's windows and what can i expect however it sounds similar to this issue you are having.

**Comment by liujoey** [comment]
@joefromct Same here. `M-x ido-find-files` works great with tramp but `helm-find-files` hangs after type the second colon in `/ssh:<machine-name>:`

**Comment by kandelvijaya** [comment]
@liujoey thanks. This helped.
