### ISSUE TITLE
WINDOWS-10 An error occurred while installing php-extras 

### ISSUE THREAD

**Issue by GiacomoSilli** [syl20bnr/spacemacs#7517]
Hello,
I know there are several threads about this topic, but I could not solve in any way.
I'm on Windows 10
I also tried using spacemacs-develop, but I'm not able to solve the problem.
`An error occurred while installing php-extras (error: (wrong-type-argument stringp nil))`

Unfortunately, the php is precisely the language that use more
Some idea?

**Comment by NJBS** [comment]
Can you provide us with a backtrace by starting emacs with the `--debug-init` flag?

That particular error is very broad so it doesn't help us pinpoint the problem very well.

I'd also like to note that spacemacs uses `git` to fetch the `php-extras` package. Is `git` available in your PATH and accessible by spacemacs `M-: (executable-find "git")`?

**Comment by GiacomoSilli** [comment]
Yes, git is installed and in PATH.
Also accessible by spacemacs.
http://imgur.com/a/1Btam

**Comment by TheBB** [comment]
Should probably take that backtrace and report to quelpa.

**Comment by GiacomoSilli** [comment]
Hi guys, any news?

**Comment by TheBB** [comment]
> Should probably take that backtrace and report to quelpa.

**Comment by TheBB** [comment]
In the meantime you can exclude php-extras as a workaround unless it has features you absolutely need.

**Comment by GiacomoSilli** [comment]
I have to report it to quelpa..?

Btw yes, meantime, i've excluded it.

**Comment by TheBB** [comment]
From the backtrace the error seems to originate from quelpa so they would be more likely to help you out.

https://github.com/quelpa/quelpa/

**Comment by GiacomoSilli** [comment]
Then i'll ask there too, thank you.
But you do not have this problem?

**Comment by TheBB** [comment]
I don't use Windows.

**Comment by TheBB** [comment]
https://github.com/quelpa/quelpa/issues/118

**Comment by GiacomoSilli** [comment]
Solved

https://github.com/quelpa/quelpa/issues/118
