### ISSUE TITLE
Ruby mode hook not calling rvm-activate-corresponding-ruby

### ISSUE THREAD

**Issue by pawandubey** [syl20bnr/spacemacs#7519]
#### Description :octocat:
`rvm-use-corresponding-ruby` not being called on `ruby-mode`. Related to #4289

#### Reproduction guide :beetle:
- Start Emacs
- Start a new rails project with a ruby version different from default version on your system. ( I am using 2.2.3, default being 2.2.2 )
- Open a file in the rails project
- Run `bundle-install` through <kbd>M-RET b i<kbd>

*Observed behaviour:* :eyes: :broken_heart:
Bundler doesn't run saying the specified ruby version is different from the activated ruby version

*Expected behaviour:* :heart: :smile:
Bundler runs correctly

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(yaml auto-completion emacs-lisp git markdown org version-control clojure html ruby ruby-on-rails latex restclient pandoc ocaml)
```

**Comment by pawandubey** [comment]
Yes.

````elisp
(setq ruby-version-manager 'rvm)
````

**Comment by TheBB** [comment]
Where?

**Comment by pawandubey** [comment]
In `dotspacemacs/user-config ()`. `eval-expression` with `ruby-version-manager` returns `rvm` so I think its being set properly.

**Comment by TheBB** [comment]
Yeah it's being *set*, but not before it's being *read*. Layer variables are mostly read during startup so you have to set them as part of the layer description.

```elisp
(
;; ...
(ruby :variables ruby-version-manager 'rvm)
;; ...
)
```

**Comment by pawandubey** [comment]
That works. Thanks a lot. I need to study up on the layer loading process once more, I guess. :smile:
