### ISSUE TITLE
Avy fails with args out of range when using uppercase chars from avy-dispatch-alist 

### ISSUE THREAD

**Issue by jschaf** [syl20bnr/spacemacs#7521]
#### Description :octocat:

Avy fails with args out of range when using avy-dispatch-alist 
#### Reproduction guide :beetle:
- Start Emacs
- <kbd>SPC jl</kbd> for `evil-avy-goto-line`
- Before selecting a line, press a **uppercase** character from `avy-dispatch-alist`, like `X` to modify the action on the selection.
- Emacs errors like below:

_Observed behaviour:_ :eyes: :broken_heart:
Emacs errors

_Expected behaviour:_ :heart: :smile:
Avy would execute the function corresponding to `X` in `avy-dispatch-alist`, which by default is `avy-action-kill-stay` which would kill the sexp at the target. 

Notably, `X` works when invoking `M-x avy-goto-line` and pressing X.  So, there's probably something wrong with the evilifed version.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.50.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
  Tested in `emacs --no-layers`. 
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
#### Backtrace :paw_prints:

```
Debugger entered--Lisp error: (args-out-of-range "X" 0 7)
  read-key-sequence-vector(nil nil t)
  read-key()
  avy-read((LONG_LIST_OF_LEAFS) avy--overlay-at-full avy--remove-leading-chars)
  avy--process(((19751 . #<window 3 on spacemacs>)) avy--overlay-at-full)
  avy--line(nil)
  avy-goto-line(1)
  funcall-interactively(avy-goto-line 1)
  call-interactively(avy-goto-line)
  evil-avy-goto-line(nil)
  funcall-interactively(evil-avy-goto-line nil)
  call-interactively(evil-avy-goto-line nil nil)
  command-execute(evil-avy-goto-line)

```

**Comment by TheBB** [comment]
Here's the evil issue tracker: https://bitbucket.org/lyro/evil/issues?status=new&status=open

**Comment by TheBB** [comment]
This is bizarre. When I run `evil-avy-goto-line` via the keybinding `SPC j l` I can reproduce the error, but not when I run `evil-avy-goto-line` via `M-x`.

**Comment by TheBB** [comment]
You don't even need a complicated evil wrapper for it. This is sufficient:

```elisp
(defun my-test ()
  (interactive)
  (call-interactively 'avy-goto-line))
(global-set-key (kbd "C-x C-y") 'my-test)  ; or whatever other key sequence
```

- `M-x my-test X` → works
- `C-x C-y X` → doesn't work

**Comment by ynilu** [comment]
I think this bug is related to which-key
avy will behave correctly If you press `SPC` `j` `l` one by one slowly,
triggering the which-key popup

**Comment by d12frosted** [comment]
For some reason I can't reproduce this issue.

**Comment by jschaf** [comment]
Just updated my packages and I'm still seeing it.  I can reproduce @ynilu working example of pressing slowly.

This works:
<kbd>SPC</kbd> (wait for which-key) <kbd>j</kbd> (wait for which key) <kbd>l</kbd> <kbd>X</kbd> `$SOME_AVY_LINE`

This doesn't work:
<kbd>SPC</kbd> <kbd>j</kbd> <kbd>l</kbd> <kbd>X</kbd> `$SOME_AVY_LINE`
