### ISSUE TITLE
Opening file with base64 encoded image string hangs Spacemacs

### ISSUE THREAD

**Issue by bleggett** [syl20bnr/spacemacs#7523]
#### Description :octocat:

Opening file with base64 encoded image string hangs Spacemacs
#### Reproduction guide :beetle:
- Start Emacs
- Open attached file

_Observed behaviour:_ :eyes: :broken_heart:
Spacemacs becomes unresponsive

_Expected behaviour:_ :heart: :smile:
Spacemacs to not become unresponsive, even though I'm doing something silly like storing an image string in a code file.
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(yaml helm
      (version-control :variables version-control-diff-tool 'diff-hl)
      (auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
      windows-scripts sql
      (javascript :variables javascript-disable-tern-port-files nil)
      html syntax-checking emacs-lisp git github org markdown pandoc colors evil-commentary react docker
      (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```
- System configuration features: JPEG RSVG NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

This may be a problem with an upstream package but not sure how to easily narrow down which one.

JS file that causes the problem: [breaksEmacs.js.txt](https://github.com/syl20bnr/spacemacs/files/545866/breaksEmacs.js.txt)

**Comment by TheBB** [comment]
Long lines is a known dealbreaker. Not much to be done about it other than open in fundamental mode (where, might I add, Emacs performs splendidly).
