### ISSUE TITLE
after cloning .emacs.d nothing seems to be happened

### ISSUE THREAD

**Issue by AhmedA-del** [syl20bnr/spacemacs#7524]
after cloning .emacs.d I started emacs and it started normally am I supposed to do anything right now ?

**Comment by TheBB** [comment]
Do you

* have a file `~/.emacs`?
* have a version of Emacs that is older than 24.4?

**Comment by AhmedA-del** [comment]
no I don't have it 
I have 25.1.1 version

**Comment by TheBB** [comment]
What's the output of `C-h v user-init-file` in Emacs?

**Comment by AhmedA-del** [comment]
oops looks like I have .emacs file but it was in another directory sorry for that mistake 
anyway here is the output
  after cloning .emacs.d nothing seems to happened

**Comment by TheBB** [comment]
Then delete it and move `.emacs.d` to where it should be.

**Comment by AhmedA-del** [comment]
thanks it worked 👍

**Comment by AhmedA-del** [comment]
now it says (error "Required feature ‘package-build’ was not provided")
  require(package-build nil noerror)
  (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)
  (if (require pkg nil (quote noerror)) nil (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir))
  (let ((warning-minimum-level :error)) (if (require pkg nil (quote noerror)) nil (require (quote cl)) (let ((pkg-elpa-dir (spacemacs//get-package-directory pkg))) (if pkg-elpa-dir (add-to-list (quote load-path) pkg-elpa-dir) (if log (progn (spacemacs-buffer/append (format "(Bootstrap) Installing %s...\n" pkg)) (spacemacs//redisplay))) (configuration-layer/retrieve-package-archives (quote quiet)) (package-install pkg) (setq pkg-elpa-dir (spacemacs//get-package-directory pkg))) (require pkg nil (quote noerror)) (if file-to-load (progn (load-file (concat pkg-elpa-dir file-to-load)))) pkg-elpa-dir)))
  configuration-layer/load-or-install-package(package-build nil nil)
  configuration-layer/load-or-install-protected-package(package-build)
  configuration-layer//install-quelpa()
  (let ((display-buffer-alist (quote (("\\(\\*Compile-Log\\*\\)\\|\\(\\*Warnings\\*\\)" (display-buffer-in-side-window) (inhibit-same-window . t) (side . bottom) (window-height . 0.2)))))) (configuration-layer//install-quelpa) (let* ((upkg-names (configuration-layer//get-uninstalled-packages packages)) (not-inst-count (length upkg-names)) installed-count) (if upkg-names (progn (spacemacs-buffer/append (format "Found %s new package(s) to install...\n" not-inst-count)) (configuration-layer/retrieve-package-archives) (setq installed-count 0) (spacemacs//redisplay) (let ((--dolist-tail-- upkg-names) pkg-name) (while --dolist-tail-- (setq pkg-name (car --dolist-tail--)) (setq installed-count (1+ installed-count)) (configuration-layer//install-package (configuration-layer/get-package pkg-name)) (setq --dolist-tail-- (cdr --dolist-tail--)))) (spacemacs-buffer/append "\n")))))
  configuration-layer//install-packages((ace-link ace-window adaptive-wrap aggressive-indent async auto-compile auto-highlight-symbol avy bind-key bind-map clean-aindent-mode column-enforce-mode counsel counsel-projectile define-word desktop diminish dumb-jump elisp-slime-nav eval-sexp-fu evil evil-anzu evil-args evil-ediff evil-escape evil-exchange evil-iedit-state evil-indent-plus evil-lisp-state evil-matchit evil-mc evil-nerd-commenter evil-numbers evil-search-highlight-persist evil-surround evil-tutor evil-unimpaired evil-visual-mark-mode evil-visualstar exec-path-from-shell expand-region eyebrowse fancy-battery fill-column-indicator flx flx-ido golden-ratio google-translate helm-make help-fns+ ...))
  (let ((packages (append (configuration-layer/filter-objects configuration-layer--used-distant-packages (function (lambda (x) (let ... ...)))) (if (eq (quote all) dotspacemacs-install-packages) (progn (let (all-other-packages) (let ... ...) (configuration-layer//get-distant-packages all-other-packages nil))))))) (configuration-layer//install-packages packages) (if (and (or (eq (quote used) dotspacemacs-install-packages) (eq (quote used-only) dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages))))
  (if no-install nil (let ((packages (append (configuration-layer/filter-objects configuration-layer--used-distant-packages (function (lambda ... ...))) (if (eq (quote all) dotspacemacs-install-packages) (progn (let ... ... ...)))))) (configuration-layer//install-packages packages) (if (and (or (eq (quote used) dotspacemacs-install-packages) (eq (quote used-only) dotspacemacs-install-packages)) (not configuration-layer-force-distribution) (not configuration-layer-exclude-all-layers)) (progn (configuration-layer/delete-orphan-packages packages)))))
  configuration-layer/sync()
  (if (not (version<= spacemacs-emacs-min-version emacs-version)) (message (concat "Your version of Emacs (%s) is too old. " "Spacemacs requires Emacs version %s or above.") emacs-version spacemacs-emacs-min-version) (load-file (concat (file-name-directory load-file-name) "core/core-load-paths.el")) (require (quote core-spacemacs)) (spacemacs/init) (spacemacs/maybe-install-dotfile) (configuration-layer/sync) (spacemacs-buffer/display-info-box) (spacemacs/setup-startup-hook) (require (quote server)) (if (server-running-p) nil (server-start)))
  eval-buffer(#<buffer  *load*> nil "c:/Users/Ahmed/AppData/Roaming/.emacs.d/init.el" nil t)  ; Reading at buffer position 1194
  load-with-code-conversion("c:/Users/Ahmed/AppData/Roaming/.emacs.d/init.el" "c:/Users/Ahmed/AppData/Roaming/.emacs.d/init.el" t t)
  load("c:/Users/Ahmed/AppData/Roaming/.emacs.d/init" t t)
  #[0 "\205\266
