### ISSUE TITLE
Company Mode Not Loading

### ISSUE THREAD

**Issue by r6203** [syl20bnr/spacemacs#7526]
#### Description :octocat:
Company Mode Not Loading

#### Reproduction guide :beetle:
- Start Emacs
- Open a JavaScript file
- Type in a variable name

*Observed behaviour:* :eyes: :broken_heart:
There is no auto completion inside JavaScript/React source files.
Also Company mode isn't listed by pressing <Space><Space>.

*Expected behaviour:* :heart: :smile:
Having auto completion and the optiont to manually active Company mode.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.1
- Spacemacs branch: master (rev. 3706a42)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python markdown react javascript helm emacs-lisp)
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
You don't have the auto-completion layer enabled…

**Comment by r6203** [comment]
Aaah, yes. Thank you. Should have better read the .spacemacs file.
