### ISSUE TITLE
Ruby layer/Rspec mode: Run all specs/ Re-run specs not present anymore

### ISSUE THREAD

**Issue by fabrik42** [syl20bnr/spacemacs#7537]
#### Description :octocat:
After the last update it seems like some of the Ruby layer functionality went missing.
Even though still documented, these functions in the Rspec mode don't exist anymore: `SPC m t a` and `SPC m t r`

#### Reproduction guide :beetle:
- Start Emacs
- Open a ruby spec file
- Press `, t`

*Observed behaviour:* :eyes: :broken_heart:
Rspec mode does not provide options to run all specs or rerun the last specs.

*Expected behaviour:* :heart: :smile:
The missing options should be provided.

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql emacs-lisp
     (ruby :variables ruby-version-manager 'rvm)
     elixir javascript go html markdown git yaml org deft
     (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
     osx)
```

#### Backtrace :paw_prints:
```
```

**Comment by TheBB** [comment]
The bindings are there:

* https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/ruby/packages.el#L176
* https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/ruby/packages.el#L184

I can't see from your report that you have set `ruby-test-runner` to `rspec`, so that is probably why you're not getting the rspec bindings.

**Comment by fabrik42** [comment]
Hi! Thank you for the fast reply. Yes this fixes it. Still strange why I didn't need to set this up before, but now it works :)
