### ISSUE TITLE
ESS layer disables evil-org-mode

### ISSUE THREAD

**Issue by Nikolaiam** [syl20bnr/spacemacs#7539]
#### Description
`org` and `ess` layers conflict, resulting in evil-org-mode not working properly when both layers are installed

#### Reproduction guide 
- Install `org` layer
- `evil-org-mode` loads normally when opening an `org` document
- Install `ess` layer
- `evil-org-mode` does not loead when opening an `org` document

*Observed behaviour:*
When `org` and `ess` layers are installed at the same time, `evil-org-mode` does not load normally. When `ess` layer is removed, `evil-org-mode` loads automatically again. The presence and absence of the minor mode can be seen from the appearance and disappearance of the `e` character in the modeline. Launching `evil-org-mode` manually with `spc spc` still does not activate expected `evil-org-mode` behaviour. Opening an `org-mode` file results in the following message being printed in the `messages` buffer:

`File mode specification error: (invalid-function org-babel-header-args-safe-fn)`

*Expected behaviour:* 
 Navigating `org-mode` headings with `g k`, for example, should launch `org-backward-heading-same-level` instead of `evil-previous-visual-line` which is observed.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp org ess)
```

**Comment by TheBB** [comment]
Duplicate: https://github.com/syl20bnr/spacemacs/issues/4618
