### ISSUE TITLE
Font information/documentation

### ISSUE THREAD

**Issue by quicknir** [syl20bnr/spacemacs#7542]
Spacemacs docs have some comments about Source Code Pro being the default font, and to install it, and also some comments about how to get the mode line to look nice in the terminal. However, I very recently discovered (discovered, because another spacemacs user told me) something surprising: Source Code Pro does not include any (or hardly any?) of the symbols you see in the mode line to indicate which minor modes are active.

On Linux at least, GUI emacs will try to automatically fall back to some other font set that does have the symbol. But at this point, it's completely system dependent. I was using spacemacs on an older OS and my unicode symbols looked terrible.

I suggest we add a note to the docs regarding this issue. For me, I ended up (after wasting hours, and just living with ugly unicode glyphs for months) being able to fix everything in five minutes by simply installing Nanum Gothic, a font I'd never heard of before, that happens to have all of the necessary characters. I think the docs should mention this issue and encourage people to install Nanum Gothic if they're having problems; that way spacemacs users are getting the glyphs independent of the system they are working on.

**Comment by d12frosted** [comment]
Well... as usually, PRs are welcome 😸

**Comment by quicknir** [comment]
@d12frosted Sure, I'm happy to PR this :-) I just like to get "agreement in principle" first.

**Comment by andschwa** [comment]
Wow @quicknir we're having the same problem at the same time. What OS are you on? I'm trying to setup Emacs from source on a CentOS 7 server build with X forwarded from Windows. I've compiled it with Xft support and got it to use the Hack font, but am just missing so many glyphs. Thought Google Noto fonts would fix it... no go yet. About to try Nanum Gothic now.

**Comment by andschwa** [comment]
Ah yes! That got some more added. The symbol `ل͜` from the [release notes](https://github.com/syl20bnr/spacemacs/blob/b6d52030b165fc5b74c95d2ade9f1ba6b5c15ab7/core/info/release-notes/0.200.txt) is giving me hell though.

**Comment by andschwa** [comment]
I replaced Nanum Gothic with `yum install google-noto*` (yes wildcard, there's like 90+ packages). This gave me all the glpyhs I needed 😄
