### ISSUE TITLE
spaceline-toggle-nyan-cat doesn't work

### ISSUE THREAD

**Issue by cyberthal** [syl20bnr/spacemacs#7544]
#### Description :octocat:

spaceline-toggle-nyan-cat does not work

I can't figure out how to get the nyan cat progress bar

Or any other mode line indicator for percentage of document scrolled

I tested this on vanilla Spacemacs, no customizations, fresh .spacemacs.

#### Reproduction guide :beetle:
- Start Emacs
- M-x spaceline-toggle-nyan-cat 

*Observed behaviour:* :eyes: :broken_heart:

No rainbow cat in modeline

*Expected behaviour:* :heart: :smile:

Rainbow cat in modeline

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

**Comment by TheBB** [comment]
All modeline segments are toggled on by default, they just won't show if the required packages or modes aren't switched on, and there's nothing in your issue report that indicates that you have even installed nyan-cat, let alone enbled it. It's in the [colors](http://spacemacs.org/layers/+themes/colors/README.html) layer.

**Comment by cyberthal** [comment]
I did not add the colors layer.
