### ISSUE TITLE
When I use C-c C-p to open a python-shell there is always an error.

### ISSUE THREAD

**Issue by GeraltCN** [syl20bnr/spacemacs#7545]
`Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native’ was t and "python" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 
`
how to fix it?

**Comment by GeraltCN** [comment]
And the Python version is 2.7.10. How to make it 3.5.2?

**Comment by TheBB** [comment]
It's not an error, it's a warning. That's why it says “Warning“.

> And the Python version is 2.7.10. How to make it 3.5.2?
I have used pyenv, and set the 3.5.2 as the default version.

Spacemacs supports pyenv, see the python layer readme for keybindings. Switch to the environment you want after you open the file.

**Comment by TheBB** [comment]
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24401
