### ISSUE TITLE
Attempting to run helm-spacemacs-help results in `Symbol’s value as variable is void: fringe-mode`

### ISSUE THREAD

**Issue by jonaustin** [syl20bnr/spacemacs#7546]
#### Description :octocat:

Attempting to run helm-spacemacs-help results in `Symbol’s value as variable is void: fringe-mode`

Environment:
- Mac OS X El Capitan
- ZSH / Oh My ZSH
- MacBook Pro Retina (2012)

I've tried the usual fixes for the void error - `rm -rf ~/.emacs/elpa` and restarting with `emacs --insecure`. No luck.

Also tried starting over with a brand new install (i.e. `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
`, `rm ~/.spacemacs`), same thing.

Thanks for Spacemacs, it's great!
#### Reproduction guide :beetle:
- Start Emacs
- SPC h SPC

_Observed behaviour:_ :eyes: :broken_heart:
Simply returns above error. Nothing else happens.

_Expected behaviour:_ :heart: :smile:
It's never worked so I don't know what the expected behavior is.
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm emacs-lisp)
```
- System configuration features: JPEG NOTIFY ACL LIBXML2 ZLIB

**Comment by bmag** [comment]
Backtrace please. `SPC t D` before `SPC h SPC` will give you a backtrace when the error occurs. I suspect `fringe-mode` is not defined in non-GUI Emacs.

**Comment by jonaustin** [comment]
Thanks, here you go:

Also, all the other `SPC h xxxx` commands seem to work fine.

```
Debugger entered--Lisp error: (void-variable fringe-mode)
  (equal fringe-mode 0)
  (not (equal fringe-mode 0))
  (and (or (and (symbolp (quote (not (equal fringe-mode 0)))) (boundp (quote (not (equal fringe-mode 0))))) (listp (quote (not (equal fringe-mode 0))))) (not (equal fringe-mode 0)))
  spacemacs/toggle-fringe-p()
  funcall(spacemacs/toggle-fringe-p)
  (let* ((toggle-symbol (symbol-name (car toggle))) (toggle-status (funcall (plist-get (cdr toggle) :predicate))) (toggle-name (capitalize (replace-regexp-in-string "-" " " toggle-symbol))) (toggle-doc (format "(%s) %s: %s" (if toggle-status "+" "-") toggle-name (propertize (or ($
  (while --dolist-tail-- (setq toggle (car --dolist-tail--)) (let* ((toggle-symbol (symbol-name (car toggle))) (toggle-status (funcall (plist-get (cdr toggle) :predicate))) (toggle-name (capitalize (replace-regexp-in-string "-" " " toggle-symbol))) (toggle-doc (format "(%s) %s: %$  (let ((--dolist-tail-- spacemacs-toggles) toggle) (while --dolist-tail-- (setq toggle (car --dolist-tail--)) (let* ((toggle-symbol (symbol-name (car toggle))) (toggle-status (funcall (plist-get (cdr toggle) :predicate))) (toggle-name (capitalize (replace-regexp-in-string "-" " $
  (let (result) (let ((--dolist-tail-- spacemacs-toggles) toggle) (while --dolist-tail-- (setq toggle (car --dolist-tail--)) (let* ((toggle-symbol (symbol-name (car toggle))) (toggle-status (funcall (plist-get ... :predicate))) (toggle-name (capitalize (replace-regexp-in-string "$
  helm-spacemacs-help//toggle-candidates()
  (let ((candidates (helm-spacemacs-help//toggle-candidates))) (helm-make-source "Toggles" (quote helm-source-sync) :candidates candidates :persistent-action (function helm-spacemacs-help//toggle) :keymap helm-map :action (helm-make-actions "Toggle" (function helm-spacemacs-help/$  helm-spacemacs-help//toggle-source()
  (list (helm-spacemacs-help//documentation-source) (helm-spacemacs-help//layer-source) (helm-spacemacs-help//package-source) (helm-spacemacs-help//dotspacemacs-source) (helm-spacemacs-help//toggle-source) (helm-spacemacs-help//faq-source))
  (helm :buffer "*helm: spacemacs*" :sources (list (helm-spacemacs-help//documentation-source) (helm-spacemacs-help//layer-source) (helm-spacemacs-help//package-source) (helm-spacemacs-help//dotspacemacs-source) (helm-spacemacs-help//toggle-source) (helm-spacemacs-help//faq-sourc$
  helm-spacemacs-help(nil)                                                                                                                                                                                                                                                                 call-interactively(helm-spacemacs-help nil nil)
  command-execute(helm-spacemacs-help)
```

Out of curiosity, I installed GUI emacs via homebrew and it worked fine, so sounds like your hunch is correct.

**Comment by bmag** [comment]
@jonaustin looks like we need to wrap the definition of `spacemacs/toggle-fringe` in a check for `(fboundp fringe-mode)`. PR welcome.
Interesting, on my Ubuntu `fringe-mode` is defined even if I run `emacs -nw`, so installing the GUI version might have fixed your problem even when running Emacs inside a terminal.

**Comment by jonaustin** [comment]
@bmag thanks for the tip, I've created a pull request: https://github.com/syl20bnr/spacemacs/pull/7564

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/7571 also

**Comment by cdfa** [comment]
I'm surprised that this issue has been open for so long. I just started learning Spacemace an hour ago and it SPC h SPC seems like a relatively important and certainly useful command. I don't have the option of installing GUI Emacs. Does anybody have other suggestions?

**Comment by jonaustin** [comment]
@cdfa I haven't used spacemacs in a while, but it's possible the simple keybindings.el change here will still fix it until the fix in develop is released: https://github.com/syl20bnr/spacemacs/pull/7564/files

**Comment by cdfa** [comment]
Wow, that was quick. That fixed it. Thanks :)

**Comment by grahamlopez** [comment]
FWIW, I just downloaded spacemacs for the first time tonight, and this was the first thing I ran into. Ubuntu 20.04 with emacs-nox installed from apt.

**Comment by tveyben** [comment]
Spacemac new user here (day 1 :-)
I also encounter the exact same problem on OS X (10.14.6):
I installed emacs with `brew install emacs`
and spacemacs via `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
And have not yet made ANY customisation (only accepted the default settings at first launch, IE = 3 x  ENTER)

I am working my way through the tutorials and then encountered this.

Yesterday (during my research) I stumbled over a dead link in the documentation, I quickly identified that a single extra character had found it's way into the link, and immediately wanted to make a PR to get it fixed - only to identify that it had been fixed 1 or 2 YEARS ago, but have been collecting dust in the develop branch.

So my $ 64.000 question is - what branch to use?
MASTER (despite it seems to have a lot of problems, solar I have encountered one pr day) or DEVELOP (as that seems to be receiving all the fixes).

The project (spacemacs) looks REALLY interesting, but I am puzzled to find solved problems that are years old but don't make it into the master branch - I'm likely missing something very obvious, please enlighten me :-)

**Comment by JAremko** [comment]
@tveyben  use develop branch and https://develop.spacemacs.org/doc/QUICK_START.html documentation :wink:
