### ISSUE TITLE
Keybindings missing from new version.

### ISSUE THREAD

**Issue by Ps-Pencil** [syl20bnr/spacemacs#7549]
#### Description :octocat:
Some key bindings missing not reflected in update.
Probably because of using ivy

#### Reproduction guide :beetle:

see observed behaviour. I have only found some commands that I frequently use.
*Observed behaviour:* :eyes: :broken_heart:
In org mode, `SPC m` only has insert-todo-heading whereas it used to have a lot other commands.
`SPC s a` only has file and project search whereas it used to have search buffers .. etc

*Expected behaviour:* :heart: :smile:
The keybindings remain.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.2
- Spacemacs branch: master (rev. 7bdde17)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(markdown yaml
          (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'cycle auto-completion-private-snippets-directory nil)
          fasd better-defaults emacs-lisp
          (latex :variables latex-enable-folding t)
          git evil-commentary ivy python java
          (shell :variables shell-default-full-span nil shell-default-position 'right))
```

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
The search stuff is because you're using ivy. There aren't any ivy equivalents for the helm commands (yet).

The org problem I can't reproduce. Are you getting any errors when opening an org file?

**Comment by Ps-Pencil** [comment]
No error message. One command I remember is `org-insert-link` which is mapped to its original keybinding. (C-c C-l)

**Comment by TheBB** [comment]
I just realized you don't have the org layer enabled. Might have something to do with it…

**Comment by Ps-Pencil** [comment]
Erh...Right. After the update, I rewrote the dotfile.. forgot to enable that.
