### ISSUE TITLE
C-c C-c in SCSS mode doesn't work

### ISSUE THREAD

**Issue by phenix-factory** [syl20bnr/spacemacs#7550]
#### Description :octocat:
Using C-c C-c in SCSS mode doesn't work anymore.

#### Reproduction guide :beetle:
- Start Emacs
- Open a SCSS file
- C-c C-c to compile it

*Observed behaviour:* :eyes: :broken_heart:
C-c C-c is undefined

*Expected behaviour:* :heart: :smile:
SCSS file compilation to css

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 emacs-lisp git markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking shell-scripts php php-mby html javascript lua gtags imenu-list yaml finance colors dash twitter
 (version-control :variables version-control-diff-tool 'diff-hl version-control-global-margin t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by TheBB** [comment]
`C-c C-c` is bound here, in `scss-mode-map`. Can you confirm that `SPC hdK scss-mode-map` doesn't show this binding? What is your version of scss-mode?

**Comment by phenix-factory** [comment]
> Can you confirm that SPC hdK scss-mode-map doesn't show this binding?

Yes : 
![selection_009](https://cloud.githubusercontent.com/assets/1810149/19683933/dfd8d684-9ab4-11e6-9b22-c9f04000a0b9.png)

> What is your version of scss-mode?

;; Created: Sep 1 23:11:26 2010
;; Version: 0.5.0
;; Keywords: scss css mode

My configuration file are here : https://github.com/phenix-factory/config-spacemacs

Thx !

**Comment by TheBB** [comment]
https://github.com/antonj/scss-mode/blob/master/scss-mode.el#L100

Looks like your problem is entirely with scss-mode, better take it there instead.

**Comment by phenix-factory** [comment]
This plugin didn't move in a long time. It was working before, maybe something change in spacemacs ?

**Comment by phenix-factory** [comment]
Well, today, C-c C-c work. I just rebooted my computer, wierd...
