### ISSUE TITLE
go-guru moved (again)

### ISSUE THREAD

**Issue by marienz** [syl20bnr/spacemacs#7552]
#### Description :octocat:
go-guru moved (again).

See melpa/melpa#4331: although go-guru is now part of go-mode upstream, melpa split it
back into two packages. Spacemacs references go-guru but (as of a few days ago)
no longer pulls in `go-guru.el`, so the commands do not work (and the keybindings are added unconditionally, so you get broken keybindings instead of missing ones).

This is related to spacemacs commit 5b13467805889a21321ac2fef623f6cd4e758df0. The melpa change more or less broke that change.

#### Reproduction guide :beetle:
- Start Emacs
- Open a .go file
- Try to use a go-guru command (like `, f d`)

*Observed behaviour:* :eyes: :broken_heart:
`command-execute: Wrong type argument: commandp, go-guru-describe`

*Expected behaviour:* :heart: :smile:
Command executes.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults emacs-lisp
     (go :variables go-tab-width 4)
     python c-c   markdown sql systemd shell-scripts git
     (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
     syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by TheBB** [comment]
So are you saying that we have to revert that commit?

**Comment by sunisdown** [comment]
we can just change [here](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/go/packages.el#L13)

change
`(go-guru :location site)`
 to
 `go-guru`

**Comment by TheBB** [comment]
Okay, I opened https://github.com/syl20bnr/spacemacs/pull/7558. Can some go users confirm it works?

**Comment by marienz** [comment]
Thanks, that change works for me (on top of spacemacs 0.200.3, let me know if you need me to test on master).

Note I did not test this with an older install of go-mode (one that still has its own copy of go-guru.el). I assume it's considered a good habit to update your packages after updating spacemacs, which would take care of that, and that it wouldn't fail badly otherwise. Let me know if you need me to test rolling back to an older go-mode.

**Comment by TheBB** [comment]
Heavens no, we're targeting latest. Especially when MELPA decides to switch things around.

Master should be the same as develop in this case.

**Comment by marienz** [comment]
Err, I meant "let me know if you need me to test on develop" (looks like you interpreted what I meant, not what I said).

**Comment by TheBB** [comment]
Okay, this should be fixed in develop and master.
