### ISSUE TITLE
[documentation edit] dotspacemacs-install-packages effect unclear

### ISSUE THREAD

**Issue by cyberthal** [syl20bnr/spacemacs#7553]
Text is in .spacemacs.  

Original text:

```
;; Defines the behaviour of Spacemacs when installing packages.
   ;; Possible values are `used-only', `used-but-keep-unused' and `all'.
   ;; `used-only' installs only explicitly used packages and uninstall any
   ;; unused packages as well as their unused dependencies.
   ;; `used-but-keep-unused' installs only the used packages but won't uninstall
   ;; them if they become unused. `all' installs *all* packages supported by
   ;; Spacemacs and never uninstall them. (default is `used-only')
   dotspacemacs-install-packages 'used-but-keep-unused))
```

Corrected text:

```
;; Defines the behaviour of Spacemacs when installing packages.
   ;; Possible values are `used-only', `used-but-keep-unused' and `all'.
   ;; `used-only' installs only explicitly used packages and deletes any
   ;; unused packages as well as their unused dependencies.
   ;; `used-but-keep-unused' installs only the used packages but won't delete
   ;; them if they become unused. `all' installs *all* packages supported by
   ;; Spacemacs and never deletes them. (default is `used-only')
   dotspacemacs-install-packages 'used-but-keep-unused))
```

Rationale: 

The original confuses "uninstall" with "delete".  The correct meaning is "delete".  

Usage case study: 

My goal was to avoid needless download time when switching between vanilla and modded configs.  I like to switch back and forth rapidly to implement new features and track down problems.  This works great with magit branch switching and lazy-load fast Spacemacs restart times.  However, the bottleneck was that Spacemacs kept deleting and redownloading all the packages.  

I read the original instructions above.  They were unclear.  I wasn't sure whether "keep-unused" would merely avoid deleting orphans, or actually load them.  I had to test to verify that orphan layers were not loaded.

The description of 'all is confusing as well.  I think it means that all Spacemacs layers are downloaded and activated regardless of whether they have been explicitly enabled, and that orphans are not deleted.

**Comment by TheBB** [comment]
Is there a reason this is an issue and not a pull request?

**Comment by cyberthal** [comment]
Never done one before.  It's #7555
