### ISSUE TITLE
c++file doesn't read header files and clang doesn't work

### ISSUE THREAD

**Issue by junhyeokahn** [syl20bnr/spacemacs#7557]
#### Description :Octocat:
My company mode doesn't work
in c++ file it doesn't read header file and show me it errror
and clang also doesn't work for function defined in other file
#### Reproduction guide :beetle:
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
red lines so sad

*Expected behaviour:* :heart: :smile:
happy with clang, sythax checker

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(python
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-complete-with-key-sequence-delay 0.1 auto-completion-private-snippets-directory nil auto-completion-enable-snippets-in-popup t)
 helm better-defaults emacs-lisp git semantic cscope
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```

```

**Comment by TheBB** [comment]
Have you written a .clang_complete file?

**Comment by junhyeokahn** [comment]
yes I saw your youtube video and just copy and paste cc_args.py and save it on /Applications/CMake.app/Contents/bin and type command what you typed in the video and it shows error like below
but it says CMake Error at /Applications/CMake.app/Contents/share/cmake-3.6/Modules/CMakeDetermineCompilerId.cmake:132 (file): file failed to open for writing (Permission denied):

**Comment by TheBB** [comment]
Well never mind that just now, does it work if you write the .clang_complete file manually?

**Comment by junhyeokahn** [comment]
I have so many files in project so i didnot try to write that file manually.
Is that doable? so which information should be there?
I saw some of path in your .clang_complete files and something else.

**Comment by TheBB** [comment]
Well since you have problems finding the include paths, you need to add those at least.

```
-Ipath/to/include
-Ianother/path/here
```

**Comment by junhyeokahn** [comment]
could it be a solution for autocompletion of function in that header files as well?

**Comment by TheBB** [comment]
Yes, you need this to get syntax checking *and* auto-completion with clang to work.

**Comment by junhyeokahn** [comment]
Thank you. Then do i need to include every header files at the end?
Is there no way to solve that automatically?

**Comment by TheBB** [comment]
You need only the include paths, not every header.

Yes there are ways to solve that automatically, for example with the cc_args.py script. However that is outside the scope of Spacemacs.

**Comment by junhyeokahn** [comment]
Ah..
So if I have directory tree like below,
Project    A   |-- (a) : a.cpp, b.cpp, c.cpp, a.h, b.h, c.h
                      |--  (b) : d.cpp, e.cpp, d.h, e.h
                B   |-- (a) : f.cpp, g.cpp, h.cpp, f.h, g.h, h.h
                      |--  (b) : i.cpp, j.cpp, i.h, j.h

I need to make .clang_complete file in Project directory and in that file I need to write,
-I/~/Project/A/(a)/to/include
-Ianother/~/Project/A/(b)/here
-Ianother/~/Project/B/(a)/here
-Ianother/~/Project/B/(b)/here

I am sorry for bad understanding

**Comment by TheBB** [comment]
No, those were just example paths, I didn't mean you need "another" and "here" literally.

If this is your directory tree (I'm making a new one, I can't read yours):

```
root
|- src
|  |- main.cpp
|  |- other.cpp
|  |- include
|     |- includefile.h
|     |- otherincludefile.h
|  |- somelibrary
|     |- somelibrary.h
|- randomfolder
   |- lala.h
```

And if the cpp files need all the include files, you need to have a `.clang_complete` file that looks something like

```
-I.../root/src/include
-I.../root/src/somelibrary
-I.../root/randomfolder
```

Where `...` is the full path to `root`, e.g. on Linux if the project is in `~/root` it would be


```
-I~/root/src/include
-I~/root/src/somelibrary
-I~/root/randomfolder
```

And so on. Literally this file is just a list of flags passed to the compiler to ensure that it can compile your file. The `-I` flag is passed to clang so that it knows where to look for include files.

It's your responsibility as a coder to know how to compile your code. Essentially you can just look at the command line invocation of the compiler and see what flags are being used and put them in the file. It's nothing more complicated than that. If you are using a build system that is more complicated then yeah, it can be tricky, but at the end of the day this isn't more magical than compiling your code in the first place. If you can do that, you can do this.

**Comment by junhyeokahn** [comment]
Thanks a lot
it is gonna be last question
do i need to seperate headers from cpp files?
i usually put my header files with cpp files and even in this case do i just put the path for header? (ex  if i assume every headerfiles and
cpp files are in root/src then,
- I../root/src)

**Comment by TheBB** [comment]
> i usually put my header files with cpp files and even in this case do i just put the path for header?

That depends on whether clang automatically searches the location of the source file for include files. As I said, this goes directly to the compiler, so the compiler decides what is allowed or not. (I honestly don't know the answer to this.)

**Comment by junhyeokahn** [comment]
I really appreciate your help bb.
Have a good night!
