### ISSUE TITLE
spaceline-compile error message on startup, after update

### ISSUE THREAD

**Issue by proc** [syl20bnr/spacemacs#7560]
After updating spacemacs to the latest, I get an error message which reads, "Error (use-package): spaceline-config :init: Symbol's function definition is void: spaceline-compile" everytime I start the app.  It seems pretty harmless as everything else still works, after you close the buffer.

**Comment by TheBB** [comment]
Update your bleeping packages.

**Comment by proc** [comment]
That worked.. I found the "Update Packages" link. Thanks. I was under the impression that the packages were updated automatically along with spacemacs. Thanks!

**Comment by Hanjae-Jea** [comment]
Thx. I really appreciate.

**Comment by zinking** [comment]
thanks @proc I had exactly the same issue, and I assumed `update spacemacs` solves everything.
