### ISSUE TITLE
Geolocation theme changer doesn't work on fresh start of Emacs

### ISSUE THREAD

**Issue by iamthad** [syl20bnr/spacemacs#7563]
#### Description :octocat:

Geolocation theme changer doesn't work on fresh start of Emacs. 
It does work after <SPC> f e R to reload .spacemacs, however.

It looks like the dotspacemacs-themes variable isn't initialized when the theme changer tries to load.
#### Reproduction guide :beetle:
- Start Emacs

_Observed behaviour:_ :eyes: :broken_heart:
The following error appears in the Warnings buffer:

```
Error (use-package): theme-changer :config: Wrong type argument: arrayp, nil
```

and the theme does not change

_Expected behaviour:_ :heart: :smile:
If appropriate, the theme changes to the night theme, and no error message appears.
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm auto-completion c-c   emacs-lisp evernote
      (geolocation :variables geolocation-enable-automatic-theme-changer t)
      git gnus html imenu-list javascript latex markdown org pandoc puppet python semantic
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      shell-scripts spell-checking syntax-checking vagrant vim-empty-lines yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by iamthad** [comment]
A crude hack that does appear to fix this issue is to add 

    :defer 1

to the use-package declaration in the geolocation/init-theme-changer function in layers/+tools/geolocation/packages.el

This silences the warning and makes the theme change, but it takes ~ 1 second due to the defer.

**Comment by namdnguyen** [comment]
The defer option didn't seem to fix it for me, but `f e R` after starting up spacemacs.

**Comment by namdnguyen** [comment]
I gave it another try. Turns out I had a couple of errors in my `user-init` section. Some lines belonged in `user-config`.

Theme-changer still didn't change the theme after I made this fix, but I tried the `:defer 1` method again, and it worked for me this time.

**Comment by joshcass** [comment]
Yeah, the `:defer' has been working for me as well. It's a bit of an unfortunate hack but not a huge deal.

**Comment by Novite5** [comment]
Same problem on Ubuntu 16.04 lts and emacs 24.5.
The `:defer` solution works but affects spacemacs update checking.

**Comment by iamthad** [comment]
I think this is related to the "chicken and egg problem" @syl20bnr describes over at #7497, since the list of themes is not loaded by the time the theme changer tries to load. 

Is there a need for better control over loading order in the .spacemacs?

In the mean time I'll submit a PR with the `:defer` workaround.

**Comment by idoo** [comment]
@syl20bnr yes, it's still doesn't works without that defer

**Comment by iamthad** [comment]
Please see new proposed fix #9081.

**Comment by dennismayr** [comment]
Where *exactly* in `layers/+tools/geolocation/packages.el` does `:defer 1` go?
Here?
```
(defun geolocation/init-theme-changer ()
  "Initialize theme-changer"
  (use-package theme-changer
    :if geolocation-enable-automatic-theme-changer
    :config
    (progn
      (when (> (length dotspacemacs-themes) 1)
        (change-theme (nth 0 dotspacemacs-themes)
                      (nth 1 dotspacemacs-themes))))))
```

**Comment by dennismayr** [comment]
It says "fixed in develop", but it's still not working as of today, April 10 2019.

Per package author's indication, under `dotspacemacs/user-config ()`, I've set:

```elisp
(require 'theme-changer)
(change-theme 'spacemacs-light 'spacemacs-dark)
```

It still doesn't switch themes, and I got an error message:
`(Spacemacs) Error in dotspacemacs/user-config: Wrong type argument: arrayp, nil`

I know it's `theme-changer` because I started from scratch in `develop`, and it's the only package that triggers the error message.

If I move `(change-theme 'spacemacs-light 'spacemacs-dark)` to `dotspacemacs/emacs-custom-settings ()` and change the syntax to `'(change-theme (quote spacemacs-light) (quote spacemacs-dark))`, the error message disappears, but `theme-changer` still doesn't work.

OS: elementaryOS 5.0 Juno (Ubuntu 18.04)
Emacs: 26.1
Spacemacs version: `develop`, latest pull done today.
`theme-changer` version: `theme-changer-20171221.1927`

**Comment by dennismayr** [comment]
On the other hand, `circadian` replaces `theme-changer` functionality nicely in `develop`:

```elisp
(use-package circadian
  :ensure t
  :config
  (setq calendar-latitude 49.0)  ;; choose you location's coordinates
  (setq calendar-longitude 8.5) ;;
  (setq circadian-themes '((:sunrise . spacemacs-light)
                           (:sunset  . spacemacs-dark)))
  (circadian-setup))
```

(Perhaps a replacement?)

**Comment by stjornandi** [comment]
I had this issue today
