### ISSUE TITLE
Add flycheck-mypy for python

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#7568]
https://melpa.org/#/flycheck-mypy

**Comment by JacobJakub** [comment]
👍

**Comment by Miciah** [comment]
Looks like this has been fixed upstream by https://github.com/flycheck/flycheck/pull/1354 / https://github.com/flycheck/flycheck/commit/d169cab8c4d542a0bb922bfc8487429dba023f5f.

**Comment by fkromer** [comment]
```
dotspacemacs-additional-packages
'(
  flycheck-mypy
  )
```

with 

```
(defun dotspacemacs/user-config ()
  (require 'flycheck-mypy)
  (flycheck-add-next-checker 'python-flake8 'python-mypy t)
)
```

works in my `.spacemacs` if `flake8-mypy` is "pip installed".

**Comment by smitty1eGH** [comment]
No joy with either work-around on 0.200.13@27.0.50

**Comment by langston-barrett** [comment]
Still valid.

**Comment by robbyoconnor** [comment]
bump
