### ISSUE TITLE
Completion for haskell layer seems has a bug.

### ISSUE THREAD

**Issue by xiaohanyu** [syl20bnr/spacemacs#7569]
#### Description :octocat:
Haskell completion with ghci backend seems has a bug

#### Reproduction guide :beetle:
- Start Emacs
- Open a `xxx.hs` haskell source code file
- Check the value of `company-backends` by `C-h v company-backends`
```
Value: ((company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)
```
- open another `yyy.hs` haskell source code file
- Check the value of `company-backends` again
```
Value: ((company-ghci company-dabbrev-code company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)
```

*Observed behaviour:* :eyes: :broken_heart:
When you open the first haskell source file, the completion for source code is
not available cause the value of `company-backends` is 

```
((company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)
```

and when you open another haskell source code file, the completion works as
expected cause the value of `company-backends` has been setq to 

```
((company-ghci company-dabbrev-code company-yasnippet)
 (company-dabbrev-code company-gtags company-etags company-keywords)
 company-files company-dabbrev)`
```

I've read the code of haskell package and found that this may be related to the
lazy-loading feature of spacemacs, but I'm not very sure about this.

So I post this issue here and want to confirm with the community. If this is
really bug, I can dive into more time to figure out a PR.

*Expected behaviour:* :heart: :smile:
The completion for haskell should work when you editing the first haskell source
code file.

#### System Info :computer:
- OS: darwin
- Emacs: 25.0.50.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b7e51d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: haskell

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/7426
