### ISSUE TITLE
Add reftex layer (on top of auctex, maybe?)

### ISSUE THREAD

**Issue by rpglover64** [syl20bnr/spacemacs#757]
I'm new to spacemacs and absolutely loving it.

When I enabled the auctex layer, I was surprised that there were no bindings for reftex (last time I worked on a latex document, I found <kbd>C-c =</kbd> to be indispensable), so I'm brining it up.

I'm willing to try to do it, but I've never written anything more than glue code in elisp and am not sure exactly how to proceed with adding a layer. My first question there is, "Should I modify the auctex layer or add a separate reftex layer?"

**Comment by syl20bnr** [comment]
If it is related to auctex then it should go in the auctex layer.
You can try to duplicate an init function in the `packages.el` file of the auctex layer and modify it for reftex, then in a PR we can improve it.
