### ISSUE TITLE
dotspacemacs-line-numbers 'relative

### ISSUE THREAD

**Issue by ubuntutest** [syl20bnr/spacemacs#7570]
I do not understand the logic of the number of lines in this way "relative",
I think it's useless

I would like to have the numbers simply in ascending order

Is possibile to  configure them in this way? thank you

**Comment by dubnde** [comment]
` dotspacemacs-line-numbers t`

**Comment by TheBB** [comment]
Closing this since I assume @ubuntutest :+1: means this answers his question.

**Comment by GiacomoSilli** [comment]
Yes, he solved my problem.
I know you don't like useless post, so i just used the "like reaction"
Thanks for help.
