### ISSUE TITLE
Seg faults when I try to use C-f

### ISSUE THREAD

**Issue by agonzalezro** [syl20bnr/spacemacs#7572]
_**Update:** This just happens when I use spacemacs in the console. With the GUI it works as expected._

_**Update #2:** It doesn't happen to me if the line numbers are disabled._

#### Description :octocat:

Sometimes I get segmentations faults (and Spacemacs exits) when I try to use helm.

Example:

```
Fatal error 11: Segmentation fault[1]    53690 abort      emacs -nw main.go
```

I have a friend using it as well and it seems that it just happens to us on the console, not on the GUI. I always use spacemacs from my console so it's a big problem.
#### Reproduction guide :beetle:
- Start Emacs
- Open a pane
- Move to the pane
- C-f to open the `helm` for file

If the previous steps didn't work keep repeating 2, 3 & 4 until it happens.

I think that the problem could be related `helm` because it happened to me some times without using C-f, just with a SPC SPC.

_Observed behaviour:_ :eyes: :broken_heart:

Spacemacs exits and I see the following on the console:

```
Fatal error 11: Segmentation fault[1]    53690 abort      emacs -nw main.goB
```

Also, I need to `reset` the console if I want to keep using it because when I press the keys I get weird characters.

_Expected behaviour:_ :heart: :smile:

Not a seg fault :) Just keep using Spacemacs.
#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm auto-completion better-defaults git markdown spell-checking syntax-checking version-control ansible chrome dockerfile emacs-lisp java javascript elixir emoji go html osx python ruby terraform thrift latex protobuf-mode colors themes-megapack)
```

cc: @csaura

**Comment by larsx2** [comment]
The same has been happening to me during the day (at least 3 times in less than an hour).

OS: OSX El Capitan
Spacemacs: 0.200.4
Emacs 25.1.1
Editing Style: vim
Layers enabled 
`html go javascript python semantic gtags helm auto-completion better-defaults emacs-lisp git markdown org syntax-checking (shell :variables shell-default-height 30 shell-default -position 'bottom) (version-control :variables version-control-diff-tool 'diff-hl)`

**Comment by GregorySchwartz** [comment]
I have run into this issue many times. See https://github.com/syl20bnr/spacemacs/issues/6093. There was one other issue where the guy had many segmentation faults with helm when multiple windows were open, but I can't find it for some reason.

**Comment by larsx2** [comment]
Indeed, this happen the most when having multiple windows (as low as 2) open and trying to do string searches. I have basically restrained myself of using multiple windows at the same time because of this reason.

**Comment by agonzalezro** [comment]
What I am doing in the mean time is using the GUI @larsx2 & @GregorySchwartz. It doesn't seg faults there.

**Comment by GregorySchwartz** [comment]
@agonzalezro Unfortunately the GUI is not always available, especially over SSH over poor connections where TUI emacs shines.

**Comment by GregorySchwartz** [comment]
I see that the tag says macOS. It happens on linux (on three of my systems) as well.

**Comment by qoshi** [comment]
+1

**Comment by GregorySchwartz** [comment]
Here's a question: what's common to spacemacs/search-project-auto and helm-find-files but not to counsel-find-file?

**Comment by yanjijinxiao** [comment]
I got the same problem. It sometimes happens in my virtual machine(ubuntu). I use "vagrant ssh" to connect my VM, It happens when I use the command "C-x 3" to split the window and work for a while, then the next "C-x C-f" pulls  the trigger. = =|||

OS: MacOS  Sierra
VM OS: Ubuntu 16.04
VM provider: VirtualBox (vagrant)
Spacemacs: 0.200.5
Emacs 25.1.1
Editing Style: emacs
Graphic display: nil
Spacemacs branch: develop
Completion: helm

**Comment by hanzejl** [comment]
+1

**Comment by agonzalezro** [comment]
@TheBB this happens on Linux as well, could you update the tags? I experienced it in another PC and it seems that @GregorySchwartz as well.

**Comment by racingmackerel** [comment]
I have been encountering the same issue under Debian Jessie (8.6) - segmentation faults while using helm (for instance, with `SPC b b` or `SPC f f`). Unfortunately I have not yet been able to reproduce the issue consistently.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.4.1 (still happens with 26.0.50.2)
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(c-c++ javascript helm auto-completion python emacs-lisp git gtags markdown extra-langs latex bibtex themes-megapack org spell-checking syntax-checking)
```
#### Backtrace:
```
Fatal error 11: Segmentation fault
Backtrace:
emacs[0x503593]
emacs[0x4e9f9e]
emacs[0x5023ae]
emacs[0x502413]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7fa8c6fe88d0]
emacs[0x4a9fd8]
...
[1]    28911 segmentation fault  emacs -nw
```

**Comment by larsx2** [comment]
I do get that error consistently. I just need to open a file in a split and then doing infile searches with SPC s s.. so far the last weeks i have been using the GUI version to avoid this... but it sucks not being able to use the command line version since i have a tmux oriented workflow.

**Comment by racingmackerel** [comment]
Possibly related (?): https://github.com/emacs-helm/helm/issues/969 - helm-autoresize-mode crash emacs in terminal

**Comment by wujiang** [comment]
+1

**Comment by agonzalezro** [comment]
In case it helps other, disabling line number fix the issue for now. It's still an issue of course, but it's a pretty decent workaround for now :)

**Comment by wujiang** [comment]
I switched to `ivy` and it works well.

**Comment by sdwolf** [comment]
This might be fixed by https://github.com/emacs-mirror/emacs/commit/8275687bb908174b84021ee15ecd959733cecb9d, see #8197.
