### ISSUE TITLE
Multiple CIDER REPLs brings edit buffers to a crawl

### ISSUE THREAD

**Issue by neverfox** [syl20bnr/spacemacs#7573]
When jacking into multiple CIDERs, the clojure mode edit buffers often become painfully slow: typing, saving, evaluating, all of it. The REPL buffers remain responsive. As soon as you cut it back to one, everything is responsive again, even if some of the edit buffers are from a different project. It doesn't appear to be because the system itself is under any memory or CPU strain. All of those facts leads me to suspect that maybe there's some kind of confusion in the autocomplete or some other layer where it's failing to recognize boundaries between classpaths, but that's just a guess. I also understand that this may be an upstream issue with CIDER or other plugins, but I thought I'd start here.

I'm running 0.200.0@25.1.1 with the following layers and defaults:

```
     auto-completion
     better-defaults
     clojure
     dockerfile
     emacs-lisp
     git
     go
     html
     javascript
     markdown
     org
     osx
     python
     react
     (shell :variables
            shell-default-height 30
            shell-default-position 'bottom)
     spell-checking
     syntax-checking
     version-control
     yaml
```

And my only customization:

```
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration. You are free to put any user code."
  (setq magit-repository-directories '("~/Repos/"))
  (setq clojure-enable-fancify-symbols t)
  (add-hook 'clojure-mode-hook #'smartparens-strict-mode)
  (add-hook 'clojure-mode-hook #'aggressive-indent-mode)
  (add-hook 'cider-repl-mode-hook #'smartparens-strict-mode)
  (add-hook 'cider-repl-mode-hook #'aggressive-indent-mode)
  )
```

```
;; Connected to nREPL server - nrepl://localhost:51762
;; CIDER 0.14.0snapshot (package: 20161010.811), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_74
```

**Comment by royalaid** [comment]
I want to add that I am experiencing the same issue but I have only done with different projects. I suspect that it has to do with autocomplete but I am really new to emacs and I am not sure how to debug.

**Comment by kommen** [comment]
This is a problem with `aggressive-indent-mode` and `cider-dynamic-indentation`, see https://github.com/clojure-emacs/cider/issues/2210
