### ISSUE TITLE
How do I enable Tabing

### ISSUE THREAD

**Issue by Atrifex** [syl20bnr/spacemacs#7577]
For some reason, I am not able to tab passed the auto indented location. Please let me know how to fix this. I am also having trouble with how the code looks with the auto indentations.

So for a for loop:

```
for(int i = 0; i < 9; i++)
        {
                // code
        }

```
this is what it ends up looking like. I want smart indent to work correctly so it doesn't do this.

**Comment by TheBB** [comment]
Configuration manual for C styles: https://www.gnu.org/software/emacs/manual/html_node/ccmode/Styles.html#Styles

(Tip: don't use the default GNU style)

For the behaviour of the tab key, see `tab-always-indent`. As a rule, tab only brings you back to the correct indentation, it doesn't add any.

**Comment by Atrifex** [comment]
When you say, "As a rule, tab only brings you back to the correct indentation, it doesn't add any.", do you mean that there is no way for me to be able to add additional tabs without using <C-q> TAB?

**Comment by TheBB** [comment]
`C-q TAB` adds a literal tab character. `SPC` adds a literal space character.

**Comment by Atrifex** [comment]
Oh okay, is it considered bad practice to map those to TAB?

**Comment by TheBB** [comment]
No, you can do that if you wish.

**Comment by Atrifex** [comment]
oh okay, thank you.
