### ISSUE TITLE
Haskell: hindent setting not preserved across emacs restart.

### ISSUE THREAD

**Issue by PierreR** [syl20bnr/spacemacs#758]
For hindent in haskell, the help suggests to customize the variable `hindent-style` by using `M-x customize-variable`.

> By default it uses the style called fundamental, if you want to use another, johan-tibell, run M-x customize-variable hindent-style.

It does not seem to work. On restart, the setting is not kept even if the `customize-set-variables` section of `.spacemacs` has been updated. The style is always set back to "chris-done".

**Comment by chrisbarrett** [comment]
I notice the haskell config layer hardcodes the indent style to "chrisdone".

**Comment by syl20bnr** [comment]
It is ok to propose `chris-done` as default, but it should be moved to `:init` argument in order to be overridable in `dotspacemacs/config`.

**Comment by bjarkevad** [comment]
I'll have a look at this. The original idea was to change the default to `chris-done` as the fundamental setting is quite incomplete, though it should be override-able by `customize`.

**Comment by chrisbarrett** [comment]
The fundamental setting isn't meant to be used at all. :)

It feels a bit weird to me to foist Chris Done's personal style on unsuspecting users, so you might consider making Gibiansky the default. Last I checked, the Gibiansky setting is close to 'normal' Haskell formatting you see in the wild.

**Comment by PierreR** [comment]
A personal opinion here: `Gibiansky` is good except for record (where it is unfortunately not close to 'normal' Haskell). This is one reason I have switched  back to `johan-tibell` (with 2 space indentation instead of 4) but the style is less complete. What would be ideal for me is an `ekmett` style (I find his style really nice, consistent and close to many other well-known haskellers)

**Comment by bjarkevad** [comment]
So should we do a vote or something?

**Comment by PierreR** [comment]
I am not sure there is a really good default right now. So the best might be to force the user to choose a style whenever `hindent` is enabled. 

If we really need a default, I would vote for `gibiansky` or `johan-tibell` instead of `chris-done` (the latter looks unconventional to me but this is just taste ;-).

**Comment by syl20bnr** [comment]
Choose the default according to the principle of least surprise. Then document clearly in the layer README the option with an snippet to change it to something else. No need to describe the different style, users wanting to change it should already be aware of different styles.

**Comment by syl20bnr** [comment]
Another option is to make layer variable `haskell-hindent-style` by default to nil which disable the package. The user must then provide a style to enable the package.

**Comment by bjarkevad** [comment]
:+1:  for that option @syl20bnr

**Comment by PierreR** [comment]
:+1:

**Comment by chrisbarrett** [comment]
Sounds good

**Comment by PierreR** [comment]
Does someone fix this or do you want me to do the PR ?

**Comment by bjarkevad** [comment]
Go ahead :-)
