### ISSUE TITLE
Remove SPC p C-g

### ISSUE THREAD

**Issue by EMayej** [syl20bnr/spacemacs#7580]
I use C-g in a lot of places to do `quit`.
now `SPC p C-g` mapped to `projectile-regenerate-tags` in dev branch.
It makes me generate tags over and over.

Could you please consider remove C-g from `SPC p`?

Or do you have another option that I can use for `quit`.

**Comment by TheBB** [comment]
Thanks, fixed.

**Comment by EMayej** [comment]
Thanks.
