### ISSUE TITLE
which-key: more compact display of window number related bindings

### ISSUE THREAD

**Issue by deb0ch** [syl20bnr/spacemacs#7582]
Some keybindings could be displayed in a more compact way by which-key. For instance,

```
1  → window 1    5  → window 5    9  → window 9
2  → window 2    6  → window 6
3  → window 3    7  → window 7
4  → window 4    8  → window 8
```

could be just

```
1..9  → window 1..9
```

This would help uncluttering some crowded which-key panes, for instance for `SPC` or `SPC b`.

I didn't see any obvious customization variable in which-key offering a way of doing that.

I wouldn't mind implementing it, but a head start would be very nice :smile: 

@bmag, @justbur, any ideas ?

See upstream issue justbur/emacs-which-key#152.

**Comment by bmag** [comment]
I don't have any special knowledge in this area, but seems that a custom `which-key-sort-order` or modifying `which-key--format-and-replace` is needed.

**Comment by deb0ch** [comment]
I saw a special thanks for you in which key's Readme, that's why I thought of you :smile: 

Thanks for pointing me to `which-key--format-and-replace `, I'll look into it soon(ish).

Though I don't see how it is related with `which-key-sort-order` ?
