### ISSUE TITLE
lua-mode gtags layer shortcut is disable

### ISSUE THREAD

**Issue by wolfand11** [syl20bnr/spacemacs#7585]
![bug1](https://cloud.githubusercontent.com/assets/1425676/19828173/dffd3eda-9df1-11e6-98b4-19040f56d58d.jpg)
![bug2](https://cloud.githubusercontent.com/assets/1425676/19828175/e2875564-9df1-11e6-8001-45c8e40f6450.jpg)

emacs-lisp-mode gtags layer shortcut is enable, but lua-mode gtags layer shortcut is disable,

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/7586

**Comment by Miciah** [comment]
Since #7586 / https://github.com/syl20bnr/spacemacs/commit/26615a64cbe114cbae4df6ce0d55fed278b9ad90 has been merged, can this issue be labeled as "Fixed in develop"?
