### ISSUE TITLE
It suddenly takes 30s to startup

### ISSUE THREAD

**Issue by HarumiKiyama** [syl20bnr/spacemacs#7588]
#### Description :octocat:

I did nothing but just updated spacemacs from v0.200.3 to v0.200.4 and updated packages yesterday, and after updating, I restarted emacs, all things worked well.
However, today when I opened emacs, it took about 30s to start up.I tried to rollback spacemacs but it still took 30s to start up.Normally it just takes 2s to startup.
#### Reproduction guide :beetle:
- Start Emacs

_Observed behaviour:_ :eyes: :broken_heart:
mini-buffer at buttom displays "Loading /home/uruk/.emacs.d/layers/ distributions/spacemacs-base/keybindings.el (source)...done" and emacs freezes.
After about 30s emacs works.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:

``` elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t :disabled-for org markdown)
 better-defaults markdown scheme emacs-lisp
 (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
 python org spacemacs-org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/7575 could have clues for you

**Comment by TheBB** [comment]
If it actually freezes, you can have a look at the helm issue in the FAQ.

**Comment by uruk1993** [comment]
Thank you, It seems the same shell problem, I migrated from `oh-my-zsh` to `prezto` yesterday.And it causes the problem.

**Comment by uruk1993** [comment]
After excluding package named `exec-path-from-shell`.My fast emacs comes back.
So as far as `exec-path-from-shell` just works for OSx, can we just exclude it in both windows and linux?

**Comment by TheBB** [comment]
I can't say for sure. If Emacs launches within the appropriate environment it's safe to exclude it. If it doesn't, you may have problems (but it's possible to fix by just setting environment variables or regular variables from within Emacs—you don't technically need `exec-path-from-shell`). Which applies where is difficult for me to say.

**Comment by yenda** [comment]
Just wanted to say that I had the same problem on Archlinux with emacs 25.1.1 and spacemacs 0.200.5

**Comment by uruk1993** [comment]
Since you are using Archlinux I think you can just exclude the package named `exec-path-from-shell` . 
Look at the [repository](https://github.com/purcell/exec-path-from-shell), this package is created to deal with some environment variable problem happening on OSX

**Comment by yenda** [comment]
Sorry I forgot to mentionned that I fixed it with the fix mentionned in this thread. 

However I am not sure it is OK to add a default package for one system that creates problems for others.

**Comment by TheBB** [comment]
You can remove `-i` from `exec-path-from-shell-arguments` too. It shouldn't really be there in the first place, except lots of people have important setup that only happens for interactive shells. If you're not one of those you can drop it. If you have also kept your expensive setup to only interactive shell, then it should be more than fast enough.

**Comment by aalireza** [comment]
If I'm not mistaken, excluding `exec-path-from-shell` causes at least one problem if you have the `go` layer since it tries to execute `exec-path-from-shell-copy-env`.

For some reason though if you don't use gui and enter `emacs24 -nw` in the terminal, the startup time would still be slow. It consistently takes around 130 seconds to load all the packages: `301 packages loaded in 130.889s (e:236 r:2 l:14 b:49)`, as opposed to around 5 seconds which is what it used to be before I reinstalled Ubuntu.


P.S. I'm using Ubuntu Gnome 16.04 with Emacs 24.5.1 and Spacemacs 0.200.7.
P.P.S. The startup delay doesn't occur if the system is not connected to the internet.
