### ISSUE TITLE
spacemacs/auto-yasnippet-expand not works

### ISSUE THREAD

**Issue by lislon** [syl20bnr/spacemacs#7589]
#### Description :octocat:

`SPC i S e` (`spacemacs/auto-yasnippet-expand`) triggers error

#### Reproduction guide :beetle:
- Start Emacs
- Open \*scratch\* buffer 
- Try expand snipped `SPC i S e`

*Observed behaviour:* :eyes: :broken_heart:
```
spacemacs/auto-yasnippet-expand: Symbol’s value as variable is void: holy-mode
```

*Expected behaviour:* :heart: :smile:

Snippet expansion works

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.4
- Spacemacs branch: develop (rev. 4bf8e52)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/commit/977a29316bb4432e109935fdfdafc277de7b33d2

**Comment by lislon** [comment]
That's was fast) Thanks
