### ISSUE TITLE
`jump-to-definition` with tern handler does not resolve properly

### ISSUE THREAD

**Issue by coreygrunewald** [syl20bnr/spacemacs#7591]
#### Description :octocat:

When using `jump-to-definition` where `tern-find-definition` is the first handler (react, javascript layers),
`dump-jump-quick-look` is executed, displaying the quick look list, but after a short period of time, the correct file is navigated to by `tern`.
#### Reproduction guide :beetle:
- Open javascript file
- Place cursor on a result from require declaration, e.g. `utils` in `const utils = require('./utils');`
- Execute `jump-to-definition` via `, g g`
- Quick look list is displayed
- `./utils` file is eventually displayed

_Observed behaviour:_ :eyes: :broken_heart:
- Quick look list displayed before navigating to correct file via tern.
- Once file is navigated to, must use `C-g` to cancel quit `jump-to-definition` command?

_Expected behaviour:_ :heart: :smile:
- `tern-find-definition` correctly finds file first, only falling back to other handlers after timeout, or error
#### Solution?

By setting switching

``` eslisp
  (add-to-list (intern (format "spacemacs-jump-handlers-%S" mode))
            'tern-find-definition)
```

To

``` eslisp
  (add-to-list (intern (format "spacemacs-jump-handlers-%S" mode))
            '(tern-find-definition :async t))
```

Things seemingly work in the expected manner - however, with my limited knowledge of spacemacs / elisp, I don't know if I'm simply covering up a root cause that is occurring somewhere else?

Looking at the tern emacs code, it does appear that the tern commands are async?
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(spacemacs better-defaults helm auto-completion syntax-checking osx yaml racket emacs-lisp evil-cleverparens git markdown org ess
           (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
           spell-checking version-control
           (colors :variables colors-enable-rainbow-identifiers nil)
           prodigy docker html lua javascript themes-megapack common-lisp react python restclient clojure github vinegar shell-scripts emoji evil-snipe imenu-list evil-commentary chrome ocaml)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by TheBB** [comment]
Is tern asynchronous?

**Comment by TheBB** [comment]
That's the solution. Can't you just PR it?

**Comment by coreygrunewald** [comment]
Yes, I'll create a PR - just wanted to submit an issue first with my concerns about making sure my fix was indeed the correct solution. I'll have the PR out shortly.
