### ISSUE TITLE
Frame jitter after 3b92a4c

### ISSUE THREAD

**Issue by 0xkag** [syl20bnr/spacemacs#7594]
#### Description :octocat:

After commit 3b92a4c2bf512a22658aa29b5830e6df86b9810d (found with git bisect), the frame, when redrawing, will shake/jitter by a few pixels.  You can see this with something like C-x C-f and then C-g.  Keep your eyes on the left border.  This is happening for me with emacs running on Linux but displaying on the Cygwin/X X server version 1.16.3 on Windows.  I haven't tried to reproduce it yet on the Linux X server.  This wasn't happening until that above commit.
#### Reproduction guide :beetle:
- Enable maximize at startup
- (see note above about the X server)
- Start Emacs
- C-x C-f, C-g

_Observed behaviour:_ :eyes: :broken_heart:
- Watch frame jitter by a few pixels as it redraws

_Expected behaviour:_ :heart: :smile:
- It shouldn't do that.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.4
- Spacemacs branch: develop (rev. 721426f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(ansible asciidoc
         (auto-completion :variables auto-completion-complete-with-key-sequence nil auto-completion-enable-help-tooltip t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle company-show-numbers t)
         better-defaults c-c++
         (colors :variables colors-enable-rainbow-identifiers t)
         elfeed emacs-lisp eyebrowse git gtags haskell helm html javascript latex markdown org pandoc
         (python :variables python-test-runner
                 '(pytest nose))
         restclient
         (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'eshell)
         shell-scripts speed-reading spell-checking sql syntax-checking themes-megapack version-control xkcd yaml)
```

**Comment by TheBB** [comment]
Since the commit is about `dotspacemacs-maximized-at-startup` I think it's pertinent to include what you have this set to...

**Comment by TheBB** [comment]
I can't reproduce this on linux no matter the value.

**Comment by 0xkag** [comment]
I thought this implied that I have it set to t:

Reproduction guide :beetle:
- Enable maximize at startup

**Comment by TheBB** [comment]
Ah, sorry.

**Comment by 0xkag** [comment]
It goes away when I git revert 3b92a4c.  That commit looks innocuous enough, but I don't know the implications of what was changed.

I guess the material difference is this (new):

`
(add-to-list 'default-frame-alist '(fullscreen . maximized)
`

vs. this (old):

`
(add-hook 'window-setup-hook 'toggle-frame-maximized)
`

And where that code lives.

**Comment by TheBB** [comment]
@deb0ch Can you enlighten us?

**Comment by 0xkag** [comment]
Another bit of information: If I double click the titlebar on the Cygwin/X-displayed window (frame) BEFORE spacemacs finishes initializing (e.g., maximize it myself) the problem is not immediately visible.  But if I then un-maximize it and remaximize the same window (frame), the problem comes back.

**Comment by deb0ch** [comment]
Does it still happen if you comment [this line](https://github.com/syl20bnr/spacemacs/commit/3b92a4c2bf512a22658aa29b5830e6df86b9810d#diff-6104ae45148ccdd2fc150ad8aa59ab80R84) (with the `(toggle-frame-maximized)` ) ?

**Comment by 0xkag** [comment]
Yes.  This diff (what you suggested @deb0ch) makes the problem go away:

```
diff --git a/core/core-spacemacs.el b/core/core-spacemacs.el
index ac75288..fab6e3c 100644
--- a/core/core-spacemacs.el
+++ b/core/core-spacemacs.el
@@ -81,7 +81,7 @@ the final step of executing code in `emacs-startup-hook'.")
   (require 'core-configuration-layer)
   (dotspacemacs|call-func dotspacemacs/init "Calling dotfile init...")
   (when dotspacemacs-maximized-at-startup
-    (toggle-frame-maximized)
+    ;; (toggle-frame-maximized)
     (add-to-list 'default-frame-alist '(fullscreen . maximized)))
   (dotspacemacs|call-func dotspacemacs/user-init "Calling dotfile user init...")
   (setq dotspacemacs-editing-style (dotspacemacs//read-editing-style-config
```

**Comment by deb0ch** [comment]
Mmmmhhhh that line was the main reason of that commit actually.

The `(add-to-list 'default-frame-alist '(fullscreen . maximized))` line is there to have the frames created with `emacsclient -c` maximized as well at creation.

Does the problem still happen if you comment that line out ? If yes, I might have a simple solution. Else, I will have to spend slightly more research and thinking :sweat_smile:

**Comment by 0xkag** [comment]
> Does the problem still happen if you comment that line out ?

I applied this diff and it still happens:

```
diff --git a/core/core-spacemacs.el b/core/core-spacemacs.el
index ac75288..d025dcd 100644
--- a/core/core-spacemacs.el
+++ b/core/core-spacemacs.el
@@ -81,8 +81,7 @@ the final step of executing code in `emacs-startup-hook'.")
   (require 'core-configuration-layer)
   (dotspacemacs|call-func dotspacemacs/init "Calling dotfile init...")
   (when dotspacemacs-maximized-at-startup
-    (toggle-frame-maximized)
-    (add-to-list 'default-frame-alist '(fullscreen . maximized)))
+    (toggle-frame-maximized))
   (dotspacemacs|call-func dotspacemacs/user-init "Calling dotfile user init...")
   (setq dotspacemacs-editing-style (dotspacemacs//read-editing-style-config
                                     dotspacemacs-editing-style))
```

**Comment by 0xkag** [comment]
It may also be worth mentioning that as long as I've been using spacemacs setting `dotspacemacs-maximized-at-startup t` has always been a little confused on how to maximize with Cygwin/X and multiple monitors: sometimes the frame (window) is too big for the main display, and almost always it's off center (e.g., not truly "maximized" in the Windows sense).  But perhaps that's a separate issue.

**Comment by deb0ch** [comment]
Damn :scream_cat: 

One question, if it already didn't work in a first place, is it really a problem on our end that we should fix ? I mean, has that modification made it a lot worse ?

I will start investigating how frame parameters work and how `toggle-frame-maximized` work to see what can be done.

I think you should as well, if you have the time and courage, as you are really the one who can see the difference.

One thing that really puzzle me is that you're saying that you are on Linux but are using Cygwin, which AFAIK is specific to Windows. Are you using Wine or something ?

**Comment by 0xkag** [comment]
> One question, if it already didn't work in a first place, is it really a problem on our end that we should fix ? I mean, has that modification made it a lot worse ?

Yes, it's a problem that should be fixed IMHO.  Yes, it's made it a lot worse.  Before, if the placement was wrong I could just maximize it and it was fine.  Now, everything I do is distracted by the jitter of the frame (window in Windows).

> One thing that really puzzle me is that you're saying that you are on Linux but are using Cygwin, which AFAIK is specific to Windows. Are you using Wine or something ?

No, not Wine.  emacs runs on Linux.  My X DISPLAY is exported to my desktop PC over ssh which is running Windows with the Cygwin/X X server.  This is in a work environment where Windows desktop PCs are standard.  This is a typical X forwarding setup, where the only difference is that the X server is Cygwin/X on Windows and not X.org on Linux.

**Comment by 0xkag** [comment]
I mean the workaround is just to disable `dotspacemacs-maximized-at-startup` and maximize it myself after spacemacs starts.  So it's not like this is a showstopper that's keeping me from using spacemacs.  But that kind of defeats the purpose of having that option.
