### ISSUE TITLE
Always in Evil mode on fresh install

### ISSUE THREAD

**Issue by kylevedder** [syl20bnr/spacemacs#7596]
#### Description :octocat:

I tried submitting this bug report using the report build into spacemacs, but when I used `C-c C-c` to submit as instructed, it did not recognize that keybinding. As a result, here is the bug report as copied from spacemacs:

I installed spacemacs by cloning the git repo, as instructed, and when the first time install prompt appeared, I selected emacs mode. After install completed, I opened the .spacemacs file and found it was running in Evil mode. I then repeatedly deleted the .spacemacs file and .emacs.d/ folder and retried installation, and each time, regardless of the combination of options I selected, spacemacs was in Evil mode.
#### Reproduction guide :beetle:
- Delete .spacemacs file and .emacs.d/ folder
- git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
- Start Emacs
- In first time setup, select emacs mode
- Select any other modes as needed

_Observed behaviour:_ :eyes: :broken_heart:
Always has Evil keybindings enabled, regardless of first time setup selection.

_Expected behaviour:_ :heart: :smile:
Pick the keybindings that match the selection in the first time setup.
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:

``` elisp
(ivy emacs-lisp)
```
#### Backtrace :paw_prints:

```
```

**Comment by kylevedder** [comment]
It appears that restarting spacemacs after install initial fixes the issue.

**Comment by LemmingAvalanche** [comment]
It seems like this would be fixed
when <https://github.com/syl20bnr/spacemacs/pull/7659> lands.

> I tried submitting this bug report using the report build into spacemacs, but
> when I used `C-c C-c` to submit as instructed, it did not recognize that
> keybinding.

The function is `spacemacs//report-issue-done`.

**Comment by TheBB** [comment]
Closing in favour of https://github.com/syl20bnr/spacemacs/issues/7658
