### ISSUE TITLE
Using '{' and '}' in OS X Portuguese Keyboard

### ISSUE THREAD

**Issue by sashaafm** [syl20bnr/spacemacs#7599]
Hello, I recently bought a Macbook Pro and I've installed Spacemacs (I've been using it for a few months in a Linux laptop with no problems, amazing tool). I began programming to try it out but I can't seem to insert the { and } characters. I can do it in regular Vim (I'm also using Vim Mode in Spacemacs).

I'm not sure if this is a bug or not. I'm using OS X Sierra and the keyboard layout is Portuguese (PT-PT is the name believe). I've searched for ways to change the keyboard layout but every other key works correctly I think, just these two are not working as intended.

Spacemacs is version 0.200.4@25.1.1

Thank you.

**Comment by Nollo** [comment]
I use an AZERTY keyboard, I had to rebind some mac keys to type `{` or `[`. I set `(setq-default mac-right-option-modifier nil)` in my user-init. The right alt is now free for special characters and left alt is still used as Meta key (or Super, your choice).

Emacs can rebind some of mac keys:
> mac-function-modifier
> mac-control-modifier
> mac-command-modifier
> mac-option-modifier
> mac-right-command-modifier
> mac-right-control-modifier
> mac-right-option-modifier
https://www.emacswiki.org/emacs/EmacsForMacOS#toc21

**Comment by sashaafm** [comment]
@Nollo thank you for your answer. Is the 'user-init' the dotfile that you can edit with SPC-f-e-d?

Could you give me any tips on what binding I should do to properly use the { and } characters?

**Comment by Nollo** [comment]
Yes, user-init is in your `~/.spacemacs` and you can access it with `SPC-f-e-d`

Binding is really a question of tastes. However I suggest to free the right option for special characters. I see a lot of people inverting Option and Cmd, so Cmd is Meta and Option is Super.

PS: If it resolved your issue, you can close it :)

**Comment by sashaafm** [comment]
@Nollo yes it did work. Just experimented. I'll leave here the answer for other people trying to use a default Pt-Pt keyboard layout:

`  (setq-default mac-option-modifier nil)`

This will make the Option key work like everywhere else in MacOS.

Thank you @Nollo.
