### ISSUE TITLE
Emacs marks tern as an orphan package and deletes it on startup

### ISSUE THREAD

**Issue by owenmpierce** [syl20bnr/spacemacs#7601]
#### Description :octocat:

Emacs marks tern as an orphan package and deletes it on startup
#### Reproduction guide :beetle:
- Start Emacs

_Observed behaviour:_ :eyes: :broken_heart:
Emacs marks tern as an orphan package and deletes it on startup
If tern is reinstalled manually, then emacs will delete it again
on the next startup

_Expected behaviour:_ :heart: :smile:
Package shouldn't be deleted
#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
(helm common-lisp emacs-lisp
      (javascript :variables tern-command
                  '("node" "/home/owen/.nvm/versions/node/v6.5.0/bin/tern")))
```

**Comment by nixmaniack** [comment]
Spacemacs enables and installs `tern` package only if `tern` binary is found in PATH. Since you're using `nvm` it might be the case that it's not in PATH. 

Some workarounds:
 - Add `tern` package to `dotspacemacs-additional-packages` so that it's installed unconditionally.
 - Or change the value of `dotspacemacs-install-packages` to  `'used-but-keep-unused` which will keep the manually installed packages even after restart.

**Comment by owenmpierce** [comment]
The first workaround didn't stop emacs from deleting tern as an orphan package.

The second workaround prevents tern from being deleted as an orphan package on startup, but I still get the "tern binary not found" warning message

tern is on my path...

    $ echo $PATH
    /home/owen/.nvm/versions/node/v6.5.0/bin:...

    $ which tern
    /home/owen/.nvm/versions/node/v6.5.0/bin/tern

    $ tern
    Listening on port 58762

**Comment by d12frosted** [comment]
Tern is on your `PATH`. But where? I mean, `PATH` variable might be properly set in your terminal, but not in Emacs.

**Comment by nixmaniack** [comment]
Possibly related to https://github.com/syl20bnr/spacemacs/issues/7497 which seems to be fixed in `develop`.

**Comment by jessecogollo** [comment]
the easy way is install tern using npm `npm i tern -g`
