### ISSUE TITLE
Windows 10 - An error occurred while installing magit

### ISSUE THREAD

**Issue by GiacomoSilli** [syl20bnr/spacemacs#7605]
Hi guys, i'm on windows 10
```
emacs --version
GNU Emacs 25.1.1
```
I'm getting the following error after packages update:
`error: Unable to activate package ‘evil-magit’. Required package ‘magit-2.6.0’ is unavailable`
Its should be fixed in Emacs 24.* + right?

**Comment by Nollo** [comment]
Did you add the git layer in your `.spacemacs` ?

**Comment by GiacomoSilli** [comment]
Seems to have resolved itself, it is very strange do not know what can depend on, i think its a bug
Often when I update packages I get some error.
But sometimes i just need to reboot and update it again to solve the problem

**Comment by NJBS** [comment]
Perhaps your connection timed out when trying to first fetch the package.

Try increasing the value of `dotspacemacs-elpa-timeout` in your `.spacemacs` file.

Regardless, if you feel that your original issue has been solved, feel free to close this 😄 .
