### ISSUE TITLE
.clang_complete doesn't seem to be loaded by flycheck

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#7606]
#### Description :octocat:
`.clang_complete` doesn't seem to be loaded by flycheck, so headers in include directories listed in this file aren't found by flycheck.
#### Reproduction guide :beetle:
- Start Emacs with a C++ file, in a directory with a custom `.clang_complete`

*Observed behaviour:* :eyes: :broken_heart:
- Headers that are in included directories listed in the `.clang_complete` are not found

*Expected behaviour:* :heart: :smile:
All headers are found

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.2
- Spacemacs: 0.200.3
- Spacemacs branch: develop (rev. b550945)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(d helm
   (auto-completion :variables auto-completion-complete-with-key-sequence "<tab> <tab>" auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
   colors emacs-lisp extra-langs git markdown org syntax-checking spell-checking typography
   (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
   (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "gibiansky")
   python pandoc latex html csv asm ipython-notebook javascript shell-scripts yaml semantic cscope dash vim-empty-lines)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

**Comment by TheBB** [comment]
I can't reproduce this. Works fine for me with this example:

`~/tmp/clangtest/test.c`

```c
#include "someheader.h"

int main(int argc, char **argv)
{
    return somefunction();
}
```

`~/tmp/clangtest/includepath/someheader.h`

```c
int somefunction()
{
    return 0;
}
```

Try syntax checking in `test.c`, it complains that the header can't be found. Then add this file

`~/tmp/clangtest/.clang_complete`

```
-I~/tmp/clangtest/includepath
```

Reopen the `test.c` buffer and turn syntax checking on. Now it works.

Can you confirm?

**Comment by beojan** [comment]
That is precisely what doesn't work.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/c-c++/funcs.el#L42-L52

You can try stepping through this function to see where it breaks down then?

**Comment by beojan** [comment]
How?

**Comment by TheBB** [comment]
Well, with your regular debugging tricks.

* Inspect values of variables (`SPC hdv`)
* Eval emacs lisp code in a buffer (`M-:`)
* Print out intermediate values (`(message "%S" something)`)
* Feel free to rewrite the functions to make this easier for you and re-eval them with `SPC mef`

I mean there's no easy way... call the function and check if you get errors, and check if the variables have the values they should have. If not, check if the function sets them. If it does, check why it sets them to the wrong values, if it doesn't, check why. And so on.

**Comment by TheBB** [comment]
Anyway, to begin with:

* Does `flycheck-clang-args` have the value you expect?
* Does `company-clang-arguments` have the value you expect?
* Does `(company-mode/find-clang-complete-file)` return the path of `.clang_complete`?
* Does `(company-mode/load-clang-complete-file (company-mode/find-clang-complete-file))` evaluate to the correct list of flags?

**Comment by beojan** [comment]
>  Does flycheck-clang-args have the value you expect?

No

>   Does company-clang-arguments have the value you expect?

No

>   Does (company-mode/find-clang-complete-file) return the path of .clang_complete?

Yes

>   Does (company-mode/load-clang-complete-file (company-mode/find-clang-complete-file)) evaluate to the correct list of flags?

Yes

**Comment by TheBB** [comment]
After calling `(c-c++/load-clang-args)`, do the variables then have the value you expect?

**Comment by beojan** [comment]
On Tuesday, 1 November 2016 14:45:28 GMT Eivind Fonn wrote:
> After calling `(c-c++/load-clang-args)`, do the variables then have the
> value you expect?

Yes.


Sincerely,
Beojan Stanislaus

**Comment by TheBB** [comment]
And is `c-c++/load-clang-args` in `c-mode-hook` and `c++-mode-hook`?

**Comment by beojan** [comment]
On Tuesday, 1 November 2016 14:48:44 GMT Eivind Fonn wrote:
> And is `c-c++/load-clang-args` in `c-mode-hook` and `c++-mode-hook`?
Yes.


Sincerely,
Beojan Stanislaus

**Comment by TheBB** [comment]
Does it run when you open a C++ file? Try putting a message in there to check.

**Comment by beojan** [comment]
On Tuesday, 1 November 2016 14:53:29 GMT Eivind Fonn wrote:
> Does it run when you open a C++ file? Try putting a message in there to
> check.
Yes.


Sincerely,
Beojan Stanislaus

**Comment by beojan** [comment]
On Tuesday, 1 November 2016 14:53:29 GMT Eivind Fonn wrote:
> Does it run when you open a C++ file? Try putting a message in there to
> check.
In fact, putting in a message to check if flycheck-clang-args is set correctly 
after it finishes running seems to indicate that it is.


Sincerely,
Beojan Stanislaus

**Comment by beojan** [comment]
On Tuesday, 1 November 2016 14:55:57 GMT Eivind Fonn wrote:
> And you don't have anything else in your config that sets any of the
> variables in question?

Certainly not flycheck-clang-args. I do have 

```
  (add-hook 'c++-mode-hook
            (lambda ()
              (setq flycheck-clang-language-standard "c++14")
              (setq flycheck-gcc-language-standard "c++14")
              (setq company-clang-arguments '("-std=c++14"))
            )
            )
```
in `dotspacemacs/user-config`.


Sincerely,
Beojan Stanislaus

**Comment by TheBB** [comment]
Well there's your problem. You're setting `company-clang-arguments` yourself. The Spacemacs function then sees that you've set it so it doesn't try to change the value.

`-std=c++14` is something that should go in your .clang_complete file together with the other flags.

**Comment by TheBB** [comment]
Hello? Did this solve your problem?

**Comment by beojan** [comment]
Yep. You can close the issue.

Sincerely,
Beojan Stanislaus
