### ISSUE TITLE
Git Blame in the Powerline

### ISSUE THREAD

**Issue by idoo** [syl20bnr/spacemacs#7610]
I know that we have a magit with blame functions, however I suppose that a git blame for current line in powerline is very useful feature. Do you have any ideas how I can add it? and may be it's good idea to add this snippet to documentation?

**Comment by TheBB** [comment]
Upstream is here: https://github.com/TheBB/spaceline

**Comment by idoo** [comment]
@TheBB added issue to upstream https://github.com/TheBB/spaceline/issues/118
