### ISSUE TITLE
initialize failed with (Wrong-type-argument stringp nil) on Docker-Ubuntu16.04-image

### ISSUE THREAD

**Issue by LiZoRN** [syl20bnr/spacemacs#7617]
initialize failed with Docker on Ubuntu 16.04 image. 
(Wrong-type-argument stringp nil)
    **string-match("\\(fish\\|t?csh\\)$" nil)**

![screenshot from 2016-11-01 20-52-11](https://cloud.githubusercontent.com/assets/11865103/19890457/bde0db46-a075-11e6-817d-4407bab2a11c.png)

**Comment by TheBB** [comment]
This is pretty simple, you're running Emacs in an environment in which the variable `SHELL` is not set. So set it.

**Comment by LiZoRN** [comment]
@TheBB Thanks.  add `DEBIAN_FRONTEND=noninteractive` echo "export SHELL=/bin/bash" >> ~/.bashrc \` to the dockerfile . It works now.
