### ISSUE TITLE
Enabling Clojure layer leads to slow startup and an error

### ISSUE THREAD

**Issue by LemmingAvalanche** [syl20bnr/spacemacs#7618]
#### Description :octocat:

When starting Spacemacs with the Clojure layer enabled, Spacemacs doesn’t seem
to be working completely well. It’s not broken by any means, but there are
issues:

- Every startup includes contacting MELPA: `Contacting host: melpa.org:443`. So
  startup is very slow.
- There is that red “Error” notice after having completed all the
  initialization. What’s weird is that I can’t find any errors in the
  `*Messages*` buffer. (I could attach the output of this buffer.) I can’t seem
  to find anything in the `*Compile-Log*` buffer, either[1]. Spacemacs seems to
  be working, though.

If I disable the Clojure layer, there is no problem; Spacemacs starts up without
contacting MELPA and there is no red error.

#### Reproduction guide :beetle:
- Recreate my setup to some extent
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:

Every startup requires downloading packages, and a red error occurs after initialization.

*Expected behaviour:* :heart: :smile:

For most startups not to require updates, and no errors.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp git markdown org latex pandoc nixos clojure)
```
#### Backtrace :paw_prints:

Does not apply, it seems. I enabled `debug-on-error` but I didn’t get a `*Backtrace*` buffer.

#### Other

I get the same result on both `master` and `develop` branches.

#### Update 1

Tested on the previous version, namely v.0.200.3. Same problem.

#### Footnotes

[1] *Update:* The error is in the `*spacemacs*` buffer:

```
An error occurred while installing clj-refactor (error: (file-error https://melpa.org/packages/paredit-20160615.1325.el Bad Request))
```

**Comment by TheBB** [comment]
Probably there's a package in the clojure layer that can't be downloaded for whatever reason. Can you try to figure out which? Just exclude packages until it works.

**Comment by LemmingAvalanche** [comment]
Will do.

**Comment by LemmingAvalanche** [comment]
`clj-refactor` must be the offending package. I totally missed where the actual
*error* was that reported in red. I was too tunnel-visioned by the expectation
that it would be in the `*Messages*``*spacemacs*` buffer that I didn’t manage to
see this line in the `*spacemacs*` buffer:

```
An error occurred while installing clj-refactor (error: (file-error https://melpa.org/packages/paredit-20160615.1325.el Bad Request))
```

Deleting all code that mentions `clj-refactor` in the `packages.el` file for the
Clojure layer indeed leads to an error-less startup which is fast—about 3′′,
compared to 80′′ the last time I tried with an unmodified `packages.el`.

And ultimately it might be `paredit` that is the problem, judging from the error
above.

I will update the issue to include that error.

**Comment by TheBB** [comment]
That URL exists: https://melpa.org/packages/paredit-20160615.1325.el

**Comment by LemmingAvalanche** [comment]
Yep, it seems I can access it in my browser as well. Do you why Emacs might have a problem fetching it?

**Comment by TheBB** [comment]
Try disabling https?

**Comment by LemmingAvalanche** [comment]
↑ I’ll try that tomorrow.

**Comment by LemmingAvalanche** [comment]
There is no mention of “paredit” in the Clojure layer files. Indeed, the error
is coming from the installation of clj-refactor, so it seems to me that the
error might be upstream. No?

I can’t seem to find some point from which to debug this in the Clojure layer.
It doesn’t really help that I’m not an Elisp programmer. (But we’ve all got to
start somewhere, right.)

**Comment by LemmingAvalanche** [comment]
I tried using `ping` on both the HTTP and the HTTPS links:

``` elisp
(ping "https://melpa.org/packages/paredit-20160615.1325.el")
(ping "http://melpa.org/packages/paredit-20160615.1325.el")
```

Both of which failed with this error (showing for HTTP):

```
** Ping ** ping ** http://melpa.org/packages/paredit-20160615.1325.el
ping: unknown host http://melpa.org/packages/paredit-20160615.1325.el

Process Ping http://melpa.org/packages/paredit-20160615.1325.el exited abnormally with code 2
```

And as a sanity check:

```
(ping "www.google.com")
```

Which did succeed.

I tried accessing the links in my browser. Both worked. The HTTP redirected to
HTTPS. Might that happen with `ping` as well?

**Comment by LemmingAvalanche** [comment]
Are any one else experiencing this problem? Or are able to reproduce? This is
not an issue for me personally since I don’t use Clojure (I just wanted it when
I was reading some old code). So if this is only an issue that affects *me*,
maybe it’s not something that is worth pursuing.

It’s fun trying to debug this though.

**Comment by LemmingAvalanche** [comment]
Since I seem to have gotten this problem after an upgrade, I just tested on the previous version. The issue persists. (Updated issue.)

**Comment by d12frosted** [comment]
Pinging something like `http://example.com` or `https://example.com` is not going to work anyways (just try in your terminal). Instead of using `ping` function, try using something like following.

```emacs-lisp
(setq gnutls-log-level 2)
(switch-to-buffer (url-retrieve-synchronously "https://melpa.org/packages/paredit-20160615.1325.el"))
```

**Comment by LemmingAvalanche** [comment]
Yep, using `ping` on HTTP* URLs turned out to be naive. ☺

I tried your code. It worked; I got the HTTP response in the buffer and the
paredit file:

```
HTTP/1.1 200 OK
```

**Comment by LemmingAvalanche** [comment]
I am closing this because:

1. I just tried on `v0.200.5` and was unable to reproduce.
2. I haven't come across anyone else experiencing this issue.

I'm chalking it up to a temporary remote package problem.

**Comment by LemmingAvalanche** [comment]
> I'm chalking it up to a temporary remote package problem.

It was also pointed out by John Stevenson on the clojure-emacs/refactor-nrepl Gitter channel that it might have been a problem with my Elpa cache. And that indeed sounds like a more likely explanation than my above reasoning, since I was the only one having this issue (apparently).

Less of an Emacs newbie day by day.
