### ISSUE TITLE
Apply smartparens configuration to REPLs

### ISSUE THREAD

**Issue by nwolfe** [syl20bnr/spacemacs#762]
I'm wondering if we should extend the `dotspacemacs-smartparens-strict-mode` to cover REPLs as well.  After all, I'm still programming when I'm in the REPL, right? Maybe there's an additional setting that would toggle this REPL coverage on/off - not sure.

I'm specifically interested in the Clojure REPL, but I figured this might be generally useful.

Thoughts?

**Comment by syl20bnr** [comment]
This is a good idea. This is something to add to the conventions since I guess it must be enabled for each REPL major mode explicitly.

**Comment by nwolfe** [comment]
bq. This is something to add to the conventions since I guess it must be enabled for each REPL major mode explicitly.

Yeah, each package with a REPL would have to implement this support explicitly, if that's what you're alluding to with making this a convention.

I've got a simple one-liner to support this in the Clojure layer.  I'll file it as a PR and we can go from there.

**Comment by nwolfe** [comment]
>  I'll file it as a PR and we can go from there.

See #768

**Comment by person808** [comment]
Couldn't you just check if a major-mode is derived from `comint-mode` to check if a buffer is a repl? Thats how its done for buffer switching. This should work for most of them except for cider.
