### ISSUE TITLE
Magit log

### ISSUE THREAD

**Issue by quicknir** [syl20bnr/spacemacs#7621]
When using magit, e.g. after entering the magit status screen, I observe that if I hit `b b` I'm given a helm auto completion on the name of the branch. This makes sense. But if I hit `l o` (log other), I have a text prompt where I have to enter the exact branch name. This is kind of strange because helm auto completion on the branch name would make perfect sense in the context of viewing a log. I'm not sure whether this behavior is: a) only on my machine, b) a bug in spacemacs, c) a bug upstream, or d) intentional.

Happy to report this upstream if that's the case; similarly if this is intentional but decided upstream I'll also raise an issue as I don't see what the upside is of doing it this way.

**Comment by TheBB** [comment]
For me, `SPC gs lo TAB` pops up a help session with completion candidates. If that's not enough for you I suggest you take it upstream.

**Comment by quicknir** [comment]
No problem, thanks for pointing that out. I tried `TAB` on another machine but it seems like my install there is bugged because it didn't work, on my current machine however it does. I'll point this out upstream.
