### ISSUE TITLE
Monokai theme highlight

### ISSUE THREAD

**Issue by GiacomoSilli** [syl20bnr/spacemacs#7623]
Hi guys, i would like to know if there is a way to remove this crazy highlight on monokai theme.

I would have "normal" one like spacemacs-dark theme

http://imgur.com/a/5kb3b

There is a way to do that? without change theme?

**Comment by TheBB** [comment]
Yes, customize the theme. See `SPC hdf custom-set-faces` or the theming layer.

**Comment by TheBB** [comment]
Here's a PR with an example for the theming layer: https://github.com/syl20bnr/spacemacs/pull/7608

**Comment by GiacomoSilli** [comment]
It seems a bit complicated, but thanks for the answer,
I think there no easier way to do this

**Comment by smimish** [comment]
I had same issue. 
Try base16-monokai theme. 
You need to add base16 package additionally in your. spacemacs

**Comment by GiacomoSilli** [comment]
i've installed base16-monokai and,
added base16 in `dotspacemacs-additional-packages()
`But it wont work, cant find packages base16 
and i see everything green

**Comment by smimish** [comment]
```
   dotspacemacs-additional-packages '(
                                      base16-theme
                                      )
```

**Comment by smimish** [comment]
after above, try it out via SPC T s
then type base16 and you will get all themes

**Comment by TheBB** [comment]
You don't need to mess with additional packages, just set your theme to base16-monokai.

**Comment by GiacomoSilli** [comment]
if i do that
```
   dotspacemacs-additional-packages '(
                                      base16-theme
                                      )
```
then SPC T s > base16-monokai
Or just setting my theme to base16-monokai
I still see all green

**Comment by GiacomoSilli** [comment]
I've just noticed that the problem is with spacemacs terminal version
If i use GUI its fixed

I would like to use the terminal, it is possibile?

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/1269
