### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by honkycat** [syl20bnr/spacemacs#7624]
The layers readme page:

http://spacemacs.org/layers/LAYERS.html

has a TON of dead links:

http://spacemacs.org/layers/+completion/helm/README.html
http://spacemacs.org/layers/+spacemacs/spacemacs-ui-visual/README.html
http://spacemacs.org/layers/+distributions/spacemacs-bootstrap/README.html

Unsure of how I can assist, please advise!

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/blob/develop/core/core-documentation.el#L29-L54

Fix this function so that it checks for existence of a README before inserting the link.

**Comment by slackorama** [comment]
whoops. force push. sorry about the double commits.

**Comment by calsioro** [comment]
I also get a 404 in:

http://spacemacs.org/doc/DOCUMENTATION.html#example-themes-megapack-example

which links to:

http://spacemacs.org/layers/themes-megapack/README.html

**Comment by duianto** [comment]
@calsioro That link seems to have been fixed in the develop version:
http://develop.spacemacs.org/doc/DOCUMENTATION.html#example-themes-megapack-example
The link was missing `+themes/`
here's the correct url
http://spacemacs.org/layers/+themes/themes-megapack/README.html

**Comment by benjamreynolds** [comment]
I think that this issue, #9346, and #7326 are all basically duplicates of one another, and once all the issues in #9346 are fixed, they can all be marked as "Fixed in develop"
