### ISSUE TITLE
c-c++ Layer needs improvement

### ISSUE THREAD

**Issue by psamim** [syl20bnr/spacemacs#7628]
Hi,

I am using Spacemacs for 6 months now, today I started using c-c++ layer for the first time. I feel it needs major improvements. It needs some major mode key bindings (`SPC m`) for

- Compile/debug of one file
- Compile/debug of project (using projectile)
- ~~clang-format (buffer/file) `(SPC m =)`~~ (fixed in develop branch)
- Refer to gtags layer in README

Thanks

-----------------------------------------------------

Edit:
- _syl20bnr on 19th December 2017_ Strikethrough "clang-format (buffer/file) `(SPC m =)`"

**Comment by TheBB** [comment]
> Compile/debug of project (using projectile)

`SPC c c`

> Compile/debug of one file

In C/C++ this typically doesn't make sense.

> clang-format (buffer/file) (SPC m =)

PR welcome.

> Refer to gtags layer in README

PR welcome.
