### ISSUE TITLE
The `SPC w .` microstate can sometimes kill buffers

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#763]
Reproduce:
- open Spacemacs
- do `SPC b p` to go to the `*scratch*` buffer, which is a writable buffer
- do `SPC w /` to get two windows in the frame
- do `SPC w .` to enter the microstate
- do `l H H ESC`

Now there are three copies of the microstate prompt filling the frame, and the `*scratch*` buffer has apparently been killed (you can check by doing `SPC b s` and looking at the list of buffers).

**Comment by syl20bnr** [comment]
Thanks for reporting this in an issue, I totally forgot about it.
