### ISSUE TITLE
`search proj` command of `Symbol Highlight Transient State` is not working.

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#7631]
#### Description :octocat:
`search proj` command of `Symbol Highlight Transient State` is not working.

#### Reproduction guide :beetle:
- Start Emacs
- Open any file from a project
- Move cursor on a symbol, use `SPC s h /` to search symbol in current project

*Observed behaviour:* :eyes: :broken_heart:
Nothing is found, the helm buffer is empty.

*Expected behaviour:* :heart: :smile: 
There should be at least one candidate (the one at point). While this command
not working, `helm-ag` works perfectly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.4
- Spacemacs branch: nil (rev. db20ba5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :disabled-for org)
 better-defaults c-c++ emacs-lisp evil-snipe font-lock-studio git github latex bibtex markdown
 (org :variables org-projectile-file "TODOs.org")
 org-config pfc-fish
 (han :variables han-enable-youdao-dict t han-enable-fcitx t han-org-line-spacing 0.2)
 html pandoc pdf-tools python rebox
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking version-control yaml)
```

**Comment by d12frosted** [comment]
Hey @et2010, what is the value of `dotspacemacs-search-tools`? Try setting it to something like `'("ag" "pt" "ack" "grep")`.

**Comment by et2010** [comment]
The value is `("ag" "pt" "ack" "grep")` and `helm-ag` works with no problem.

**Comment by bmag** [comment]
Works for me on latest develop both with Ivy and Helm. @et2010 what branch are you on? The info says `nil (rev. db20ba5)`. Perhaps the symbol you search for doesn't appear anywhere else?

**Comment by et2010** [comment]
After updating spacemacs and packages to the latest, the problem was gone! Thanks for your help, @d12frosted @bmag
