### ISSUE TITLE
Question about spacemacs|use-package-add-hook

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#7633]
So I am trying to expand the git-link remote-alist. I normally could do it in the `dotspacemacs/user-config` function but I wanted to have a separate layer with all the work-related configurations in place, so I did something like this:

```elisp
(defun evilcorp/pre-init-git-link ()
  (spacemacs|use-package-add-hook git-link
    :post-config
    (spacemacs/set-leader-keys
      "glh" 'git-link-homepage)
    (setq git-link-use-commit nil)
    (add-to-list 'git-link-remote-alist
                 '("github.evilcorp.com"  git-link-github))
    (add-to-list 'git-link-commit-remote-alist
                 '("github.evilcorp.com"  git-link-commit-github))))
```

This is what spacemacs has in it's use-package usage of git-link

```elisp
(defun git/init-git-link ()
  (use-package git-link
    :defer t
    :init
    (progn
      (spacemacs/declare-prefix "gl" "links")
      (spacemacs/set-leader-keys
        "gll" 'spacemacs/git-link
        "glL" 'spacemacs/git-link-copy-url-only
        "glc" 'spacemacs/git-link-commit
        "glC" 'spacemacs/git-link-commit-copy-url-only)
      ;; default is to open the generated link
      (setq git-link-open-in-browser t))))
```
See there is no `post-config` in it. Could this be the issue?

See how engine-mode does have a `:config` part of its config: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+web-services/search-engine/packages.el#L19-L82

and this is how I do mine:
```elisp
(defun evilcorp/pre-init-engine-mode ()
  (spacemacs|use-package-add-hook engine-mode
    :post-init
    (add-to-list 'search-engine-alist
                 '(evilcorp-github
                   :name "E Corp Github"
                   :url "https://github.evilcorp.com/search?type=Code&ref=searchresults&utf8=✓&q=%s"))
    (autoload 'engine/search-evilcorp-github "engine-mode" nil 'interactive)
    (define-key evil-normal-state-map "gs" 'engine/search-evilcorp-github)
    :post-config
    (defengine evilcorp-github
      "https://github.evilcorp.com/search?type=Code&ref=searchresults&utf8=✓&q=%s")
    ))
```

And this works great. Maybe it's also worth pointing out that the `defer load` fix that @syl20bnr applied to the engine mode makes it a little harder to be able to customize this :(

Is there a solution Any of you might think about? How do we enable people to have access to configure our packages in their own layers?  Are we doing this in a natural easy to follow way?

**Comment by bmag** [comment]
> See there is no post-config in it. Could this be the issue?

Probably this is the issue. But the solution is simple: if the relevant use-package declaration doesn't have a `:config` section, use a plain `with-eval-after-load` instead.

**Comment by TheBB** [comment]
https://github.com/jwiegley/use-package/issues/250  
https://github.com/syl20bnr/spacemacs/issues/3070  
https://github.com/syl20bnr/spacemacs/pull/3084 (note the author of this one :-D)  
https://github.com/syl20bnr/spacemacs/issues/5135

Closing as very, very duplicate.
