### ISSUE TITLE
Safest Reinstall Method

### ISSUE THREAD

**Issue by Atrifex** [syl20bnr/spacemacs#7636]
What is the safest way to remove and reinstall Spacemacs.

 I am not sure what all of the dependencies are and if i delete the wrong thing I am worried that when I try to perform a clean build I will have errors. Thanks in advance.

**Comment by NJBS** [comment]
Spacemacs is a configuration for Emacs. It does not modify any files outside of `~/.emacs.d` (other than generating your dotfile, named `.spacemacs` in your home directory). Thus, to completely remove Spacemacs you can simply remove the `.emacs.d` folder and the `.spacemacs` file.

To reinstall simply reclone the spacemacs repository as described in https://github.com/syl20bnr/spacemacs#install

**Comment by d12frosted** [comment]
> It does not modify any files outside of ~/.emacs.d (other than generating your dotfile, named .spacemacs in your home directory).

Well, to be fair, we are running some 3d-party lisp code. Sometimes it generates files outside of `~/.emacs.d`. But when it happens we try to move it to `~/.emacs.d` 😸

**Comment by NJBS** [comment]
@d12frosted Absolutely correct, thanks for the clarification :smile: !
