### ISSUE TITLE
Modifying Existing Layer

### ISSUE THREAD

**Issue by bennigoetz** [syl20bnr/spacemacs#7638]
I want to add some custom behavior to the Python layer, and am not sure how to do it in Spacemacs.

Main issue: coming from a vi+tmux+slimux setup, I am very frustrated with an aspect of the Inferior Python REPL in Emacs, namely that when you send a command to the REPL, it doesn't display the code itself, only the results. For my workflow, this makes it difficult to tell exactly what code I've executed.

A friend who's a long-time Emacs user hacked up some Elisp code to do what I want, namely display the actual code in the REPL. He's put it in his `.emacs` file. If I try putting it in my `.spacemacs` file, specifically in the `dotspacemacs/user-config` section, it messes something up where the Python layer isn't even available! Since this is specific to the Python layer, it feels like it ought to be associated with the layer itself, rather than a general config file, anyway.

His code is even nice enough to use a keybinding that sends an individual line to the REPL if nothing is selected, or the same keybinding on a selected region will send that region. That's the behavior I had in vi+tmux+slimux, and I found it super convenient.

In my ideal world, I'd like to use `, l` to send a line (or region, if selected) to an iPython interpreter in the REPL, have it display the code in the `In` cell, and any output is displayed in the `Out` cell. (`ipython` with `--simple-prompt` in 5.0 now, I guess.) I'll never use `live-py-mode`, and I'm fine with overwriting the `, l` keybinding.

Any help greatly appreciated!!

**Comment by TheBB** [comment]
Unless you actually show us the code that supposedly breaks the python layer and the error(s) you are getting, if any, that indicates to you that the python layer isn't even available, the only help I can offer is the moral support of suggesting that you can figure it out yourself.

Certainly nothing at all in your user-config function should render a layer unavailable, since layers are resolved before that function even runs. You can for sure break things after the fact but the *layer* should still be there.

**Comment by bennigoetz** [comment]
Sorry to leave out the code, and post something vague. I suppose one of my questions was *where* should modifications to specific layers be written, if they are only for one later. I put it in `.spacemacs`, in the `user-config` function.

Before I get to that... a different quick question. I put `(setq python-excluded-packages '(live-py-mode))` in the `user-config` function, but `live-py-mode` remained in the Python major mode menu, and it remained working. (This is after running `SPC f e R`.)

Back to the main thread. Here's the code, sorry it's a few paragraphs.

```
  (require 'python)
  (setq python-shell-interpreter "python")
  (eval-after-load 'python
    '(progn
      (setq python-remove-cwd-from-path nil)
      (setq compilation-scroll-output t)
      (defun python-send-string-experimental (min max)
        (let ((pybuf (process-buffer (python-shell-get-or-create-process)))
              (curbuf (current-buffer)))
          (switch-to-buffer pybuf)
          (goto-char (point-max))
          (insert "\n")
          (insert-buffer-substring curbuf min max)
          (goto-char (point-max))
          (comint-send-input)
          (switch-to-buffer curbuf)))
      (defun python-send-line-experimental ()
        (interactive)
        (let ((min (line-beginning-position))
              (max (line-end-position)))
          (python-send-string-experimental min max)))
      (defun python-send-region-experimental ()
        (interactive)
        (if (use-region-p)
            (let ((min (region-beginning))
                  (max (region-end)))
              (python-send-string-experimental min max))))
      (defun python-send-either-experimental ()
        (interactive)
        (if (use-region-p)
            (let ((min (region-beginning))
                  (max (region-end)))
              (python-send-string-experimental min max))
          (let ((min (line-beginning-position))
                (max (line-end-position)))
            (python-send-string-experimental min max))))
      (spacemacs/set-leader-keys-for-major-mode 'python-mode "sa" 'python-send-either-experimental)))
```

After running `SPC f e R`, the `s a` option appeared in the major mode menu just fine. Sending a line worked, sending a selection didn't (but I'm sure this is a problem with iPython 5, that my sysadmins insisted on installing).

**But** open quitting Spacemacs and reopening a Python file called `walrus.py`, Spacemacs says:
`Spacemacs encountered an error while loading your .../.spacemacs file. Pick your editing style for recovery...`

Then (after selecting `vim`, obviously 😄 ):
`Support for python-mode requires installation of layer python, do you want to install it? (y or n)`

First, if I choose `n`, I'm not in any major mode, no syntax highlighting, no `SPC m`.

If I quit Spacemacs and then restart with `emacs walrus.py`, I get the same error message. If I choose `y`, Spacemacs does some downloading... and then things are as usual. (I have the Python layer.)

If I quit and restart Spacemacs again, and I choose `n`, the Powerline bar says "Python" (so I'm in the Python major mode?), and I have syntax highlighting, but `SPC m` is undefined. I can't bring up the Python menu.

Every time I load Spacemacs up with a Python file, I get the same messages.

Thanks... I don't know any eLisp, so maybe I shouldn't be screwing around with this stuff yet anyway. I just wish I could replicate the Python REPL behavior I have in vi+tmux+slimux. It's so convenient, and seems so obvious.

**Comment by cpaulik** [comment]
The code you posted works fine for me if I also set 
`(setq python-shell-interpreter-args "-i")`

So it is not releated to the snippet you posted.
