### ISSUE TITLE
Error (use-package): org post-:config hook: Unknown keyword: :export-block

### ISSUE THREAD

**Issue by G1enY0ung** [syl20bnr/spacemacs#7640]
#### Description
today when I update packages and restart, then Spacemacs pop up me a **warning**:

> Error (use-package): org post-:config hook: Unknown keyword: :export-block

#### Reproduction guide
- Start Spacemacs
- pop up this warning directly

I only find the keyword :export-block in `.emacs.d/layers/+emacs/org/local/ox-gfm/ox-gfm.el`:

```emacs-lisp
;;; Define Back-End

(org-export-define-derived-backend 'gfm 'md
  :export-block '("GFM" "GITHUB FLAVORED MARKDOWN")
.......
```

And I don't know why it occurs this error.

Is this error relate to use-package or org?

Or this error about update use-package?

#### System Info :computer: 
- OS: fedora23
- Emacs: 24.5.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 better-defaults emacs-lisp git markdown
 (colors :variables colors-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar t)
 html
 (clojure :variables clojure-enable-fancify-symbols t)
 javascript react
 (wakatime :variables wakatime-api-key "0e5273fb-eb69-41cc-9b47-901e6c06bbdc" wakatime-cli-path "/usr/bin/wakatime" wakatime-python-bin "/usr/bin/python3.4")
 (org :variables org-enable-github-support t)
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking version-control sql g1en)
```

**Comment by TheBB** [comment]
> Is this error relate to use-package or org? Or this error about update use-package?

It's related to Org 9.0.

**Comment by G1enY0ung** [comment]
Ok, I understand. Sorry about not conform to the great report bug report when I first report it.

It's my fault. and I update my system info.

Hope this can help you, I only find this warning message with this issue and I don't know how to debug it.
:cry: 

If you want me to provide some help message, I am very glad to do:smile:

**Comment by TheBB** [comment]
No worries, you haven't done anything wrong. It's just that Org 9 was just released and some of the Spacemacs stuff is probably not compatible with it yet. Until it is you can downgrade org or exclude the offending package (ox-gfm) in case you're not using it.

**Comment by G1enY0ung** [comment]
Ok, thank you very much :smiley:

**Comment by LemmingAvalanche** [comment]
- [Org news (9.0 release)](http://orgmode.org/Changes.html)
- [”Permalink” to this release](http://orgmode.org/w/org-mode.git?p=org-mode.git;a=blob_plain;f=etc/ORG-NEWS;h=dd332a4f4e9eb546ba38981ca8611e2f5956dc7a;hb=c61ee8b82af52f09792a554029addcb48c5b2c5b)

**Comment by G1enY0ung** [comment]
@LemmingAvalanche thanks :smile: I already see it.

**Comment by G1enY0ung** [comment]
@LemmingAvalanche thanks :smile: I already see it.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/ox-gfm/pull/1

**Comment by G1enY0ung** [comment]
@TheBB I try to remove this line ` :export-block '("GFM" "GITHUB FLAVORED MARKDOWN")` before I report this issue, but the error also exists when Spacemacs start

**Comment by LemmingAvalanche** [comment]
@G1enY0ung Are you using Org v9.0? Mine is only 8.3.6.

**Comment by G1enY0ung** [comment]
@LemmingAvalanche yeah, I have already updated my Org to 9.0

**Comment by TheBB** [comment]
> @TheBB I try to remove this line :export-block '("GFM" "GITHUB FLAVORED MARKDOWN") before I report this issue, but the error also exists when Spacemacs start

The file in Spacemacs isn't ever used for anything.

**Comment by agzam** [comment]
btw, can someone explain why `ox-gfm.el` is local in org layer? Why not the MELPA package is used? The same question pops about evil-org.el

**Comment by agzam** [comment]
Hey guys. Any update on the issue? It's a mere annoyance, not very critical. I would be happy though to see it fixed.

**Comment by G1enY0ung** [comment]
@agzam Seems that there is no update for the master branch of Spacemacs

**Comment by agzam** [comment]
@G1enY0ung I'm on develop

**Comment by LemmingAvalanche** [comment]
@agzam The PR is still pending.

**Comment by syl20bnr** [comment]
The PR is merged, sorry guys for the long delay.
