### ISSUE TITLE
persp-mode breaks emacsclient useage

### ISSUE THREAD

**Issue by leezu** [syl20bnr/spacemacs#7644]
#### Description :octocat:
`persp-mode` sets `initial-buffer-choice` to `#[nil "\207" [persp-special-last-buffer] 1]`,
which breaks using emacsclient when running emacs in the server mode.
Specifically, when opening a new emacsclient frame, it displays the exactly same content as the last frame, whereas it is expected to just open the spacemacs-buffer.

As a workaround `persp-mode` can be added to `dotspacemacs-excluded-packages`.

#### Reproduction guide :beetle:
- Start Emacs server with some layer that enables `persp-mode`
- Start one emacsclient and open a file in a buffer
- Start another emacsclient

*Observed behaviour:* :eyes: :broken_heart:
- The second emacsclient will start with the buffer of the first emacsclient open

*Expected behaviour:* :heart: :smile:
- The second emacsclient should start with the spacemacs-buffer

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-help-tooltip t)
 bibtex pdf-tools
 (org :variables org-agenda-span 10 org-extend-today-until 5 org-agenda-start-on-weekday nil)
 (deft :variables deft-directory "~/Dropbox/org/deft" deft-recursive t deft-use-filter-string-for-filename t deft-use-filename-as-title t)
 finance emacs-lisp git shell
 (latex :variables latex-build-command "LatexMk")
 markdown syntax-checking typescript html javascript
 (python :variables python-enable-yapf-format-on-save t)
 semantic gtags
 (c-c   :variables c-c  -enable-clang-support t c-c  -default-mode-for-headers 'c  -mode)
 ess)
```

**Comment by TheBB** [comment]
If persp-mode overrides initial-buffer-choice it sounds to me like this is a bug report that should go there.

**Comment by TheBB** [comment]
Actually we can override this behaviour by setting `persp-is-ibc-as-f-supported` to `nil`. Seems to work fine here and should have no other problems that I can see.

**Comment by leezu** [comment]
That works indeed, thanks. Should this be set per default in the `spacemacs-layouts` layer?

**Comment by TheBB** [comment]
Well, that's what I suggest.
