### ISSUE TITLE
helm-spacemacs clobbers dotspacemacs/config settings.

### ISSUE THREAD

**Issue by gbarta** [syl20bnr/spacemacs#765]
I have (setq-default indent-tabs-mode t) in my dotspacemacs/config function, and found that sometimes it was being set back to nil as is the spacemacs default.

It turns out this happens after invoking helm-spacemacs, because it reloads funcs.el and config.el from every configuration layer, including the spacemacs layer itself.  It appears this is in order to populate the helm choices.

Now that I know why it happens it isn't too much to deal with.

In order to fix it, am not sure what would be better - only load layers which have not already been loaded, or call dotspacemacs/config again after reloading all the layers.

**Comment by syl20bnr** [comment]
Thanks for pointing this out, this is a regression induced by the new dotspacemacs reloading feature on `SPC m c c`.

**Comment by syl20bnr** [comment]
Fixed in 0.64.2
