### ISSUE TITLE
origami package is not installed

### ISSUE THREAD

**Issue by adamcavendish** [syl20bnr/spacemacs#7651]
**Description**

Start emacs, no origami package.

I know that `spacemacs-editing` should include this package, however it is not installed.
Even I created my own layer and add init-origami () for it, but it is not installed.

**System Information**

OS: osx
Emacs: 24.5.1
Spacemacs: 0.200.5
Graphic display: t
Editing style: emacs

**Comment by TheBB** [comment]
Do you have `dotspacemacs-folding-method` set to `origami`? It won't be installed otherwise, see https://github.com/syl20bnr/spacemacs/blob/develop/layers/+spacemacs/spacemacs-editing/packages.el#L24

**Comment by TheBB** [comment]
See also `SPC h SPC origami F2` for an explanation of why Spacemacs will not install a package.

**Comment by adamcavendish** [comment]
@TheBB  Great thx. It works.

My configuration of spacemacs file is too old and the `dotspacemacs-folding-method` was not there so I did not realize so.

Is there any way to automatically update one's spacemacs file along with the spacemacs repo template?

**Comment by TheBB** [comment]
You can try diffing with `SPC feD`, or read the changelog on dotfile changes.

**Comment by adamcavendish** [comment]
@TheBB Thx. That's a good way.
