### ISSUE TITLE
Spacemacs rendering is broken when running inside Tmux

### ISSUE THREAD

**Issue by sirn** [syl20bnr/spacemacs#7653]
#### Description :octocat:

When running Spacemacs inside Tmux session, after Spacemacs finished initializing itself, the rendering of Emacs in Tmux will left rendering artifacts around.

Demonstration: https://asciinema.org/a/88f5bzzxyasbw89zjt9tgj3lh

In the above Asciinema, after Spacemacs finished initializing (0:08), the following rendering artifacts can be seen:

* Repeated [?]
* There's a black bar on below of statusline (doesn't appear prior to initization)
* When moving cursor, it cause lines to be repeated.
* Opening and closing minibuffer will left rendering artifacts.

This only happens when running Spacemacs under Tmux (no problem with Screen), so I guess it's more of a Tmux's bug. But it doesn't happen with non-Spacemacs Emacs, so I have no idea what is causing this. The above Asciicinema was captured with a newly-cloned Spacemacs.

#### Reproduction guide :beetle:

- Start Tmux
- Start Emacs inside Tmux

*Observed behaviour:* :eyes: :broken_heart:

- Repeated lines
- Black bar under status line
- Etc.

*Expected behaviour:* :heart: :smile:

- No rendering artifacts

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

```
$ tmux -V
tmux 2.3
$ echo $TERM
xterm-256color
```

Inside Tmux:

```
[tmux] $ echo $TERM
screen-256color
```

(Screen with `screen-256color` doesn't have this problem, Tmux with `xterm-256color` still has this problem.)

#### Backtrace :paw_prints:

:cry:

**Comment by TheBB** [comment]
Does it repro with stock Emacs?

**Comment by sirn** [comment]
@TheBB Nope. No problem with stock Emacs.

**Comment by sirn** [comment]
@TheBB Nope. No problem with stock Emacs.

**Comment by TheBB** [comment]
How about `spacemacs-base`?

**Comment by TheBB** [comment]
How about `spacemacs-base`?

**Comment by TheBB** [comment]
I can't reproduce this myself with a stock tmux config and a very complete Spacemacs install.

**Comment by sirn** [comment]
@ThBB doesn't happen with `spacemacs-base`.

**Comment by TheBB** [comment]
Then I guess you can try to selectively exclude packages to see which one breaks it.

**Comment by sirn** [comment]
OK thank you. I think I found it. Looks like the ➊ character from `window-numbering` is triggering a bug in Tmux 2.3. Will file the bug with Tmux.

**Comment by TheBB** [comment]
You can disable unicode symbols then.

**Comment by TheBB** [comment]
This seems to be answered.

**Comment by sirn** [comment]
Thanks. For now I'll workaround by disabling unicode symbols.

**Comment by filib** [comment]
For anyone finding this via Google, here's how you disable unicode symbols as of today.

> Unicode symbols are displayed by default. Setting the variable
> `dotspacemacs-mode-line-unicode-symbols` to `nil` in your `~/.spacemacs` will
> display ASCII characters instead (may be useful in terminal if you cannot set an
> appropriate font).

Source: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#minor-modes

**Comment by therealpxc** [comment]
FYI this can also be fixed by using a `tmux` which is compiled with `utf8proc` support. Just make `utf8proc` available in the build environment and add the configure flag `--with-utf8proc`.

**Comment by kprav33n** [comment]
For those who see something like this, try to explicitly turn on UTF-8 support in tmux using `tmux -u` when invoking the client.
