### ISSUE TITLE
Spell checking doesn't work in web mode

### ISSUE THREAD

**Issue by dmusican** [syl20bnr/spacemacs#7656]
#### Description :octocat:
Spell checking doesn't work in web mode

#### Reproduction guide :beetle:
- Make sure spell-checking and html layers are enabled in startup file
- Make sure ispell-local-dictionary is set to something (I have "english")
- Start Emacs
- Open up a .txt file, a .tex file, or nearly anything else, and observe that flyspell checking is on and working

*Observed behaviour:* :eyes: :broken_heart:
In web mode, misspelled words are not indicated, and manually checking individual words through SPC-S-c seems to do nothing.

*Expected behaviour:* :heart: :smile:
In web mode, misspelled words should be indicated appropriately, and checking words through SPC-S-c should test the word.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ruby python auto-completion html emacs-lisp markdown org
      (latex :variables latex-build-command "LatexMk")
      spell-checking)
```

**Comment by TheBB** [comment]
Can't repro, works fine.,

**Comment by dmusican** [comment]
Whoops -- something went wrong in my initial report: the key to reproducing it is to open an html file, which has web mode kick in. Spell checking then fails in an html file. Was that clear? @TheBB, I appreciate the quick response.

**Comment by TheBB** [comment]
Yes, I opened an HTML file, turned on spell checking (`SPC tS`), wrote some rubbish and observed red underlines under my rubbish.

**Comment by dmusican** [comment]
Hmmmm. any suggestions on what might be different in my setup? See screenshot.
![spacemacs_spelling](https://cloud.githubusercontent.com/assets/695685/20018464/cd0f6f0c-a295-11e6-82da-b6dedc942295.png)

**Comment by TheBB** [comment]
I can't see the minor mode indicators, are you sure that flyspell is activated in the html buffer?

**Comment by dmusican** [comment]
Yep, it is. New screenshot attached. (I had to make sure to keep that window active when getting the screenshot to keep the indicators.)
![emacsnov7](https://cloud.githubusercontent.com/assets/695685/20056614/cb49c956-a4ac-11e6-9f66-ee0331db82d8.png)

**Comment by dmusican** [comment]
I just found this workaround, which solves my problem:

http://blog.binchen.org/posts/how-to-use-flyspell-in-web-mode.html

By putting the following code (from above) into my dotspacemacs/user-config, spell-checking in web mode works for me. So "problem solved," but it seems I shouldn't have to do this manually, especially since @TheBB couldn't duplicate the problem. Does this suggest any thoughts as to what might be going wrong or how to duplicate it for others?

```
(defun web-mode-flyspefll-verify ()
  (let ((f (get-text-property (- (point) 1) 'face)))
    (not (memq f '(web-mode-html-attr-value-face
                   web-mode-html-tag-face
                   web-mode-html-attr-name-face
                   web-mode-doctype-face
                   web-mode-keyword-face
                   web-mode-function-name-face
                   web-mode-variable-name-face
                   web-mode-css-property-name-face
                   web-mode-css-selector-face
                   web-mode-css-color-face
                   web-mode-type-face
                   )
               ))))
(put 'web-mode 'flyspell-mode-predicate 'web-mode-flyspefll-verify)

(add-hook 'web-mode-hook
          (lambda ()
            (flyspell-mode 1)
            ))
```

**Comment by philjackson** [comment]
I have the same issue.
