### ISSUE TITLE
Wifi turns off everytime i start Spacemacs

### ISSUE THREAD

**Issue by Kellsor** [syl20bnr/spacemacs#7657]
First of all, i am still a newbie with spacemacs, emacs, vim, the Linux world and even github. Sorry if i am doing this "submit issue" wrong.

I am using Manjaro and everytime i open Spacemacs my wi-fi turns off. Does someone has the same problem and knows why this is hapening?

**Comment by LemmingAvalanche** [comment]
Please run the function `spacemacs/describe-system-info` (or use the keybinding
`SPC h d s`, or `M-m h d s`) and paste the result into your issue post. That
function will copy a description of your setup to your clipboard.

**Comment by agzam** [comment]
@Kellsor can you try starting Emacs with `--no-init-file` option? Let's see if it's definitely Spacemacs' fault

**Comment by Kellsor** [comment]
This is the result of describe-system-info:
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

agzam, i tried and the wifi didn't turn off. It looks like it's definitely Spacemacs fault

**Comment by Stebalien** [comment]
Describe "turn off". Do you just get disconnected, does it get disabled (i.e., you have to re-enable wifi manually), does it get permanently disabled (do you have to reboot to fix it)?

**Comment by Kellsor** [comment]
@Stebalien only disabled, not permanently. Re-enable wifi is possible

**Comment by Stebalien** [comment]
@Kellsor so you have to go up to the network manager icon and check the "Enable Wi-Fi" checkbox to re-enable (just want to make sure we're on the same page?

Just to double check, how are you opening emacs? Are you just running `emacs` on the command line?

**Comment by Kellsor** [comment]
@Stebalien yes i need to check the wifi checkbox to re-enable

Both ways of opening emacs (command line or launcher) disable the wifi.

**Comment by TheBB** [comment]
Can you trigger an error if you run Spacemacs as a user that does not have permission to disable the wifi?

**Comment by Kellsor** [comment]
@TheBB, on an user with no permission to disable wifi, spacemacs doesn't turn off wifi, but no error appears.

By excluding exec-path-from-shell you mean removing from .spacemacs? If so, i tried and didn't help

**Comment by TheBB** [comment]
The only reference to nmcli I can find is [this package](https://github.com/nicferrier/emacs-nm). You haven't installed it by any chance?

**Comment by Kellsor** [comment]
I only used "git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d" so I don't think so.
