### ISSUE TITLE
Selecting holy mode upon installation will leave emacs in evil mode until restart

### ISSUE THREAD

**Issue by quietnan** [syl20bnr/spacemacs#7658]
#### Reproduction guide :beetle:
- Remove .spacemacs and clear all caches (I went as far as spinning up a fresh AWS instance)
- Start Emacs
- When prompted, choose holy mode over evil
- Change buffer to some file or *scratch*
- Start typing to realize you are in evil mode
- Restart emacs
- Change buffer to some file or *scratch*
- Start typing to realize that you are now in holy mode

*Observed behaviour:* :eyes: :broken_heart:
- See above. Evil mode after installation before restart

*Expected behaviour:* :heart: :smile:
- Never seeing evil mode if I choose holy upon installation

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion emacs-lisp git
     (go :variables gofmt-command "goimports" go-use-gometalinter t)
     (latex :variables latex-enable-visual-line t latex-enable-auto-fill nil latex-enable-folding t)
     markdown python spell-checking syntax-checking)
```

**Comment by bmag** [comment]
The README [says](https://github.com/syl20bnr/spacemacs#default-installation) to restart Emacs after the initial installation of packages. Not sure if it's a bug or just a quirk of the installation process.

**Comment by TheBB** [comment]
You should probably do that anyway, however I was able to tweak the loading process for this to work: https://github.com/syl20bnr/spacemacs/pull/7659

Downside is you don't get the nice home buffer showing until after you have answered the initial questions.

**Comment by LemmingAvalanche** [comment]
It seems that this is a duplicate
of <https://github.com/syl20bnr/spacemacs/issues/7596>.
