### ISSUE TITLE
evil-surround breaks the dot operator

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7662]
#### Description :octocat:
evil-surround breaks the dot operator

#### Reproduction guide :beetle:
- Start Emacs
- go the scratch buffer
- create two simple words
- surround the first with `ysiw"`
- try to surround the other word using the `.` operator

*Observed behaviour:* :eyes: :broken_heart:
the `.` operator breakes and evil prints this message to the minibuffer:
`After 0 kbd macro iterations: evil-motion-range: Args out of range: "", 0`

*Expected behaviour:* :heart: :smile:
the other word should be surrounded

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 29049dd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(org emacs-lisp version-control git ivy markdown)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

#### Backtrace :paw_prints:
```
not applicable.
```

#### References:
timcharper/evil-surround#84

**Comment by LemmingAvalanche** [comment]
I was able to reproduce.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 29049dd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(org emacs-lisp version-control git ivy markdown)
```

**Comment by ninrod** [comment]
This have appeared before: #4641. And it seemed to have been fixed. maybe it is a regression on evil-surround codebase.

**Comment by ninrod** [comment]
I've gained push access to upstream and merge the fix to this issue. Should be available in a few hours on melpa.

**Comment by ninrod** [comment]
fixed on melpa.
