### ISSUE TITLE
`End of file during parsing` during package installation

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#7663]
#### Description :octocat:
`End of file during parsing` 

#### Reproduction guide :beetle:
- Start Emacs
- `SPC a k` to bring out package list
- Mark a random package with `i`, e.g. `anything`
- Install the marked package with `x`

Note that some of the packages may not reproduce.

*Observed behaviour:* :eyes: :broken_heart:
In the compile-log, one can see errors like this:

`End of file during parsing`

*Expected behaviour:* :heart: :smile:
No errors, since installation of the same package on stock emacs does not suffer from this issue.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: nil (rev. 29049dd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :disabled-for org)
 better-defaults c-c++ emacs-lisp evil-snipe git github latex bibtex markdown
 (org :variables org-projectile-file "TODOs.org")
 html pandoc pdf-tools python rebox
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts
 (spell-checking :variables spell-checking-enable-by-default nil)
 syntax-checking version-control yaml)
```

**Comment by TheBB** [comment]
I was not able to reproduce this with the `anything` package.

**Comment by LemmingAvalanche** [comment]
I was also unable to reproduce; there was no such string in the compile log. I used the same layers as you.

Here’s a random hunch; try deleting `.emacs.d` and clone this repository again.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((helm
  (auto-completion :disabled-for org)
  better-defaults c-c++ emacs-lisp evil-snipe git github latex bibtex markdown
  (org :variables org-projectile-file "TODOs.org")
  html pandoc pdf-tools python rebox
  (shell :variables shell-default-height 30 shell-default-position 'bottom)
  shell-scripts
  (spell-checking :variables spell-checking-enable-by-default nil)
  syntax-checking version-control yaml))
```

**Comment by et2010** [comment]
Thanks for your help! As @LemmingAvalanche 's suggestion, I did a fresh start and cleaned my `.spacemacs` file also. Now the issue is gone. Sorry for the noise.
