### ISSUE TITLE
spacemacs-bootstrap: bind-map needs evil prematurely

### ISSUE THREAD

**Issue by boykov** [syl20bnr/spacemacs#7664]
I tried to use bare `spacemacs-bootstrap` layer as `dotspacemacs-distribution` and discovered that `bind-map` package needs `evil` package earlier than it is loaded. 
[issue.txt](https://github.com/syl20bnr/spacemacs/files/573093/issue.txt)

**Comment by TheBB** [comment]
You can't use spacemacs-bootstrap as a distribution layer.

**Comment by TheBB** [comment]
I tried it though and it works fine for me, no errors.

**Comment by boykov** [comment]
I know it is not officialy supported, but I use it (with some bypass for this `evil` issue now). ...I think it points to certain package boot order issue in `spacemacs-bootstrap` layer itself.

**Comment by boykov** [comment]
Thank you for your test, I found the cause: old version of `bind-map` package.
