### ISSUE TITLE
Emacs users left in vim-y state

### ISSUE THREAD

**Issue by jabranham** [syl20bnr/spacemacs#7665]
#### Description :octocat:
Some commands leave Emacs users in evil state

#### Reproduction guide :beetle:
- Start Emacs
- M-m k L

*Observed behaviour:* :eyes: :broken_heart:
Runs evil-lisp-state-sp-forward-sexp and leaves user in some sort of vim-y mode (the cursor is red/pink, if that helps. Can get back to "usual" emacs by hitting ESC.)

*Expected behaviour:* :heart: :smile:
Should run sp-forward-sexp (this is what is listed under the which-key popup when pausing between hitting "M-m k" and "L"). This kind of behavior seems to happen with many (all?) of the smartparens commands under "M-m k".

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 better-defaults bibtex
 (elfeed :variables rmh-elfeed-org-files
         (list "~/.spacemacs.d/elfeed.org")
         elfeed-search-filter "@1-week-ago  unread " elfeed-db-directory "~/Dropbox/.elfeed")
 emacs-lisp ess finance git github helm latex markdown
 (mu4e :variables mu4e-maildir "~/.mail" mu4e-enable-notifications t mu4e-enable-mode-line t mu4e-alert-interesting-mail-query
       (concat "flag:unread" " AND " " maildir:\"/utexas/INBOX\"" " OR maildir:\"/gmail/INBOX\"" " AND flag:unread"))
 (org :variables org-directory "~/Dropbox/org/" org-agenda-files
      (list
       (concat org-directory "todo.org")
       "~/Dropbox/bibliography/notes.org")
      org-projectile-file
      (concat org-directory "todo.org"))
 pdf-tools python
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by TheBB** [comment]
Yeah, those are **evil-lisp-state** commands and as the name implies are not really intended for Emacs users. If you want to use smartparens commands in emacs style, just use the smartparens bindings (whatever they are).

**Comment by TheBB** [comment]
@syl20bnr holy-mode advices insert, motion and normal state. None of the others.

**Comment by jabranham** [comment]
But when I do M-m k, which-key pops up saying that L should run sp-forward-sexp. But M-m k L isn't actually bound to sp-forward-sexp, it's bound to evil-lisp-state-sp-forward-sexp.

**Comment by TheBB** [comment]
Yeah that's a convenience thing. In fact a lot of function names in which-key are not verbatim.

I guess we have to write some sort of dynamic advising for holy-mode if we want to support this kind of thing.

**Comment by jabranham** [comment]
Gotcha. This of course means that there aren't any bindings for the smartparens commands in holy-mode.
