### ISSUE TITLE
Documentation for symbol at point

### ISSUE THREAD

**Issue by entropitor** [syl20bnr/spacemacs#7673]
Is it possible to get the tooltip from the auto-completion layer (http://spacemacs.org/layers/+completion/auto-completion/README.html#tooltips) if you are just with your cursor on a (completed) symbol?

It would be nice to be able to quickly read the documentation also when the code is already written.

**Comment by bmag** [comment]
I'm assuming you're talking about the text cursor, not the mouse cursor. We already have a feature that displays a short description (usually not full documentation) in the echo area (at the bottom of the frame) when the cursor is on a symbol (variable, function, etc.). This feature is called ElDoc and is enabled by default. Did you have something else in mind?

**Comment by caske33** [comment]
Indeed, the text cursor.

And the documentation that is available in auto-completion layer is a lot longer. It would be nice if there was a command to get this full description without having to go to the definition of the symbol (where the comment is) or popping up an auto-complete window, just to read the documentation.

**Comment by bmag** [comment]
Hmm... usually `K` or `SPC m h h` display the documentation in a buffer in a popup window (like `describe-function` does, not a tooltip window like the auto-completion uses). If you specifically want a tooltip window, then I don't think we have a solution currently.

The documentation tooltip we have is provided by [`company-quickhelp`](https://github.com/expez/company-quickhelp) and relies on auto-completion ([Company](https://github.com/company-mode/company-mode)) to be in progress. If there's a package for showing help/documentation in a tooltip window, then we can include it in Spacemacs. So far I found [a draft](http://jasonm23.roughdraft.io/eea3b4662e2a3028a07e-emacs-help-popup-for-function-or-variable-at-point) and [an SX question](http://emacs.stackexchange.com/questions/18771/pop-up-documentation-with-pos-tip-or-popup).

**Comment by caske33** [comment]
`SPC m h h` doesn't seem to work for me. At least not in the rust layer, where the company-quickhelp does work. To which function is it bound for you?

**Comment by sooheon** [comment]
In rust mode, that should be bound to `spacemacs/racer-describe`.

**Comment by caske33** [comment]
Do you have any idea why it's not bound to that for me? (There is no `SPC m h` binding even)

**Comment by bmag** [comment]
For rust-mode, that binding was only recently added in develop branch. Try it in an elisp file, for example your dotfile.
