### ISSUE TITLE
`spacefmt` cleanup tool doesn’t like `tree`-like output in source blocks

### ISSUE THREAD

**Issue by LemmingAvalanche** [syl20bnr/spacemacs#7675]
Running `spacefmt` turns ASCII `tree`-like output in example/source blocks into Org tables.

#### Steps to reproduce

- `cd .emacs.d`
- `./core/tools/spacefmt/spacefmt doc`
- `git diff doc/DOCUMENTATION.org`:

``` diff
diff --git a/doc/DOCUMENTATION.org b/doc/DOCUMENTATION.org
index 48ea73b..d4f9f4d 100644
--- a/doc/DOCUMENTATION.org
+++ b/doc/DOCUMENTATION.org
@@ -184,7 +184,7 @@
…
@@ -343,12 +343,13 @@ Configuration is organized in layers. Each layer has the following structure:
       |__ [local]
       | |__ [package 1]
       | |     ...
-      | |__ [package n]
-      |-- layers.el
-      |__ packages.el
-      |__ funcs.el
-      |__ config.el
-      |__ keybindings.el
+
+      |                   | __ [package n] |
+      |-------------------+----------------|
+      | __ packages.el    |                |
+      | __ funcs.el       |                |
+      | __ config.el      |                |
+      | __ keybindings.el |                |

```
#### Reported before?

- I searched the issue tracker. I only found one open issue that mentioned `spacefmt`.
- There does not seem to have been run a `spacefmt` (judging by commit messages) since the `doc/DOCUMENTATION.md -> doc/DOCUMENTATION.org` move (MD to Org). So I guess it might not have come up yet.

#### A possible fix

Using non-ASCII for such `tree`-like output should solve the issue.

**Comment by JAremko** [comment]
[It uses](https://github.com/syl20bnr/spacemacs/blob/develop/core/tools/spacefmt/spacefmt.el#L133) `org-table-any-line-regexp`  that may be too simplistic. We probably also should check if  the line is a part of a tree.

**Comment by JAremko** [comment]
And add a tree to the [test file](https://github.com/syl20bnr/spacemacs/blob/develop/core/tools/spacefmt/tests/test.org)
