### ISSUE TITLE
org-store-link stops working with pdf-tools after opening outline. 

### ISSUE THREAD

**Issue by cycomanic** [syl20bnr/spacemacs#7681]
#### Description :octocat:
If I open a pdf with pdf-tool layer everything is working fine, I can use SPC a o l to store a link to the document and use it in my org files. However after opening the pdf outline, when I try to store a link I get a `Wrong type argument: stringp, nil` error. 
#### Reproduction guide :beetle:
- Start Emacs
- open pdf document
- press `SPC a o l` (to store a link, works)
- press `O` to open the outline for the PDF
- press `SPC a o l` -> Wrong type argument: stringp, nil

*Observed behaviour:* :eyes: :broken_heart:
org-store-link does not work
*Expected behaviour:* :heart: :smile:
org-store-link continues to work

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html shell-scripts helm auto-completion emacs-lisp git markdown pdf-tools org
      (org :variables org-enable-github-support nil org-enable-reveal-js-support t)
      spell-checking syntax-checking version-control python bibtex latex ranger semantic ibuffer
      (shell :variables shell-default-shell 'eshell)
      typography pdf-tools-org)
```

**Comment by TheBB** [comment]
I can't reproduce this. In the outline buffer I get an error that there's no method for storing a link to that buffer, and in the PDF buffer it continues to work.

**Comment by cycomanic** [comment]
OK weird, I'm quite certain I tried to reproduce with a minimal setup, let me get back to you.

**Comment by cycomanic** [comment]
Ok this is somewhat more difficult to trigger than I thought. Below is a way how I can trigger it most of the time. 
1. I seem to need the bibtex layer installed as well 
2. open org file (this one has latex included) 
3. split windows, open pdf (possibly large) document in other window
here is the where it comes a "random"
4. Scroll a small bit
5. open outline
6 switch back to pdf
7. SPC a o l -> wrong type argument error

This is happening both before and after upgrading to org 9.0. Let me know if I can do anything else to help debug this.

**Comment by cycomanic** [comment]
OK some more info, after stepping through the `org-store-link` with edebug. It fails inside `org-label-store-link` (from org-ref-core.el) on the first line:
```elisp
(let* ((object (org-element-context)))
```
inside `org-element-context` it stops at 
```elisp
(looking-at org-complex-heading-regexp)
```
Am I right in interpreting that this is an org bug?

**Comment by TheBB** [comment]
I've seen that error before. You can call `org-set-regexp-and-options` to fix it. I'm not sure why it sometimes doesn't run, but it's deep within org so probably it's their problem.

**Comment by TheBB** [comment]
Next time it happens see if org reports any errors when setting up the mode.

**Comment by cycomanic** [comment]
Sorry for my ignorance (I've just started with emacs, still trying to wrap my head around elisp), but how do I call `org-set-regexp-and-options`? It doesn't show when I press ~SPC SPC~

**Comment by TheBB** [comment]
No, it's not interactive, so you have to call it manually, e.g. with `M-:`

**Comment by stdcall** [comment]
I have the same problem here.
