### ISSUE TITLE
indent-line-function doesn't work as expected in coffee-mode

### ISSUE THREAD

**Issue by skomanduri** [syl20bnr/spacemacs#7682]
#### Description :octocat:
Indentation via the TAB key doesn't work correctly when editing CoffeeScript files using coffee-mode from the `javascript` layer.

#### Reproduction guide :beetle:
- Start Emacs
- Have javascript layer installed
- Create a new file
- M-x coffee-mode
- Type the following text
  ```
  f ->
    foo
  ```
- Place cursor before "f" in "foo"
- Hit TAB key

*Observed behaviour:* :eyes: :broken_heart:
TAB key inserts spaces instead of fixing line indentation.  If the cursor is in the middle of the line, it inserts spaces even in normal mode in Evil.

*Expected behaviour:* :heart: :smile:
TAB should reindent the line.  For example, TAB works fine in `javascript-mode`.  Manually running the command `coffee-indent-line` works.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp javascript)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Notes
```
(setq indent-line-function 'coffee-indent-line)
```
provides the desired behavior.

But
```
  (add-hook 'coffee-mode-hook (lambda () (setq indent-line-function 'coffee-indent-line)))
```
in my dotspacemacs/user-config didn't work for me.  `indent-line-function` is still set to `javascript/coffee-indent` from the javascript layer.

**Comment by ndan** [comment]
Here is work around solution:

```
  ;; Remove spacemacs hook for coffee-mode
  (remove-hook 'coffee-mode-hook '(lambda ()
                                    (setq indent-line-function 'javascript/coffee-indent
                                          evil-shift-width coffee-tab-width)))

  ;; Fix Evil's o and O commands
  (setq coffee-indent-like-python-mode t)
```

**Comment by d12frosted** [comment]
Clothing this issue as an old and inactive one. If you need help with your problem, try proposed solution or let me know, and I'll reopen this one.
