### ISSUE TITLE
Motion `g n` not working after `*`

### ISSUE THREAD

**Issue by diegomarangoni** [syl20bnr/spacemacs#7683]
#### Description :octocat:
Not being able to use `g n` motion after highlight a word with `*`

#### Reproduction guide :beetle:
- Start Emacs
- Set **Evil Search Module** to **Evil interactive search** by using `:customize` 
- Put the cursor on a word that has more than 1 occurrence on the buffer
- Press `*`
- Then press `g n`

*Observed behaviour:* :eyes: :broken_heart:
Received a message telling that **no search pattern** was set

*Expected behaviour:* :heart: :smile:
Go to the next occurrence of the highlighted word

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 2c4cd4d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go helm emacs-lisp)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by TheBB** [comment]
You have to bind `*` to whatever the original evil binding was to be able to do this.

**Comment by diegomarangoni** [comment]
Evil originally binds to `evil-ex-search-word-forward` but `spacemacs/enter-ahs-forward` has some nice features.
I can't see a reason why `g n` does not work with `*`

**Comment by TheBB** [comment]
> I can't see a reason why g n does not work with *

Since it calls a different function, it doesn't set the search pattern that `gn` looks for.

**Comment by diegomarangoni** [comment]
Is there a way to make it set the search pattern then?

**Comment by TheBB** [comment]
Yes, you set it. :-P

https://github.com/syl20bnr/spacemacs/pull/7689

**Comment by diegomarangoni** [comment]
I've just tested with you PR, but still not working as expected
I was trying to replace a match with `c g n` and then navigate through all matches with `n` and replace other random matches just by hitting `.` like I was used to do in vim, but not working

**Comment by TheBB** [comment]
Works fine for me.
