### ISSUE TITLE
flycheck haskell can't find dependencies for stack project

### ISSUE THREAD

**Issue by ublubu** [syl20bnr/spacemacs#7685]
#### Description :octocat:
flycheck haskell can't find dependencies for stack project

#### Reproduction guide :beetle:
- `stack setup` and `stack build` and `stack test` a project with multiple modules - e.g. https://github.com/ublubu/shapes
- Start Emacs
- open a source file in one module that depends on another module in the project - e.g. shapes/src/Physics/Broadphase/Aabb.hs
- flycheck complains that it can't find shapes-math

Alternate steps:
- per haskell layer troubleshooting doc: in user-config (setq flycheck-haskell-stack-ghc-executable "/Users/krilee/wrapped-stack")
- `stack --project-root` yields "Invalid option `--project-root'" when flycheck runs
- `stack --version` yields "Version 1.2.0 x86_64 hpack-0.14.0"

*Observed behaviour:* :eyes: :broken_heart:
- see reproduction guide

*Expected behaviour:* :heart: :smile:
- flycheck starts without warning that haskell-stack-ghc exited
- syntax checking works

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml helm
      (auto-completion
       (haskell :variables haskell-completion-backend 'intero))
      emacs-lisp osx syntax-checking
      (haskell :variables haskell-enable-hindent-style "gibiansky"))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by mrkgnao** [comment]
Can you try using the `intero` backend?

**Comment by ublubu** [comment]
How do I use `intero` for flycheck?

Also, I just re-enabled syntax-checking after disabling it last night, and now it seems to work fine.

All I'm sure I did in the intervening time was load a module into the repl. I'll spend some time later to see if I can figure out what changed.

**Comment by d12frosted** [comment]
@ublubu checkout [readme](https://github.com/syl20bnr/spacemacs/blob/master/layers/+lang/haskell/README.org#completion-support) file of `haskell` layer. 😸 But you almost using it. You probably have a mistake in your layers declaration. 

```
(yaml helm
      (auto-completion
       (haskell :variables haskell-completion-backend 'intero))
      emacs-lisp osx syntax-checking
      (haskell :variables haskell-enable-hindent-style "gibiansky"))
```

It should be 

```
(yaml helm auto-completion emacs-lisp osx syntax-checking
      (haskell :variables haskell-enable-hindent-style "gibiansky")
                          haskell-completion-backend 'intero)
```

**Comment by ublubu** [comment]
?? I only see instructions for using intero for completion, repl, and refactoring suggestions, not flycheck. Is it automatically also used for syntax-checking?

**Comment by d12frosted** [comment]
`intero` automatically configures `flyckeck` as well. Also you have a typo in your configurations regarding `haskell` layer.

**Comment by ublubu** [comment]
Yes, I see that now. =S

**Comment by d12frosted** [comment]
Did `intero` solve your problem? 😸

**Comment by ublubu** [comment]
Been busy the last couple evenings. I'll try reproducing the error tonight. So far as I can tell, both intero and non-intero flycheck now work for me.

I'll figure out what changed, and maybe that can go into the README in case anyone else makes the same mistake.

**Comment by ublubu** [comment]
I can't reproduce the problem. I'm just going to close this. Weird that I have no idea what changed.
