### ISSUE TITLE
REPORTING.template incorrect instructions for submitting bugs

### ISSUE THREAD

**Issue by ublubu** [syl20bnr/spacemacs#7686]
#### Description :octocat:
`C-c C-c` on the bug report template doesn't do anything.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC h I`
- fill in template
- `C-c C-c`

*Observed behaviour:* :eyes: :broken_heart:
- `C-c C-c is undefined`

*Expected behaviour:* :heart: :smile:
Opens a browser tab with filled-in template copied into new GitHub issue.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml helm
      (auto-completion
       (haskell :variables haskell-completion-backend 'intero))
      emacs-lisp osx
      (haskell :variables haskell-enable-hindent-style "gibiansky"))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by Miciah** [comment]
Actually, this issue looks like a duplicate of #10833.
