### ISSUE TITLE
Support emacs-gitlab

### ISSUE THREAD

**Issue by cellofellow** [syl20bnr/spacemacs#7687]
Feature request for a new layer:

- https://github.com/nlamirault/emacs-gitlab

Seems very nice but needs some Evil magic to make it really work.

**Comment by CarlQLange** [comment]
+1 :)

**Comment by jachtoro** [comment]
+1

**Comment by ffloyd** [comment]
+1

**Comment by aqua36** [comment]
+1

**Comment by vityafx** [comment]
Any news when this will be merged?

**Comment by n1kio** [comment]
+1

SPC-g-g is not taken

**Comment by myrgy** [comment]
https://github.com/syl20bnr/spacemacs/issues/4174

**Comment by arnelandwehr** [comment]
+1

**Comment by Amatrelan** [comment]
+1

**Comment by behoof4mind** [comment]
+1

**Comment by mabo3n** [comment]
+1

**Comment by vityafx** [comment]
Sorry, hasn't been working on it, did not need gitlab support anymore.
