### ISSUE TITLE
Crash undere Windows10 + Emacs25.1

### ISSUE THREAD

**Issue by MangelMaxime** [syl20bnr/spacemacs#7688]
#### Description :octocat:

Emacs25.1 is crashing on launch when adding spacemacs.

#### Reproduction guide :beetle:
- Download Emacs25.1 for windows x86_64
- Download the latest master version of spacemacs
- Install spacemacs to `~/.emacd.d` for me it is: `C:\Users\mmangel\AppData\Roaming\.emacs.d`
- Start Emacs
- Emacs crash and the os ask if we want to debug or no

I am using Windows10 enterprise edition.

I don't really know emacs and don't know where to find more info to help you guys. If you need more info so me the way and I will help :)

**Comment by tuhdo** [comment]
With my Windows 10 Home edition, it doesn't crash. Is this newly installed spacemacs?

**Comment by MangelMaxime** [comment]
Yes this a new Windows10 **Enterprise** and new spacemacs.

In the past I has some mode installed manually in Emacs but I remove my .emacs.d file to start from blank before installing the .emacd.d repo from spacemacs.
