### ISSUE TITLE
`SPC a s i` messes up layout

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#7691]
#### Description :octocat:
`SPC a s i` messes up layout

#### Reproduction guide :beetle:
1. Start Emacs
2. Do `SPC w / SPC a s i`
3. Do `ESC SPC a s i`

*Observed behaviour:* :eyes: :broken_heart:

After step 2, the left window is focused and contains the shell
buffer.  The bottom window and right window contain the Spacemacs
splash screen buffer.

After step 3, the frame is split between a large top window and a
small bottom window, both containing the Spacemacs splash screen
buffer.

*Expected behaviour:* :heart: :smile:

After step 2, the bottom window is focused and contains the shell
buffer.  The left and right windows contain the Spacemacs splash
screen buffer.

After step 3, the frame is split between equally sized left and right
windows, both containing the Spacemacs splash screen buffer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 2c4cd4d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml html python helm better-defaults emacs-lisp git github markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (spell-checking :variables spell-checking-enable-by-default nil)
      syntax-checking version-control rust)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY GNUTLS FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by TheBB** [comment]
This is easily reproducible outside Spacemacs, therefore please take it upstream.

**Comment by kini** [comment]
Thanks.  Reported as kyagi/shell-pop-el#51.
