### ISSUE TITLE
How to enable Rainbow Mode by default?

### ISSUE THREAD

**Issue by li-xinyang** [syl20bnr/spacemacs#7693]
Rainbow mode is declared inside `colors` layer, but there is no variables to enable the Rainbow mode by default. 

https://github.com/syl20bnr/spacemacs/tree/c788da709bb1c74344f5ab1b6f18cfdf6b930df8/layers/%2Bthemes/colors

There is a PR https://github.com/syl20bnr/spacemacs/pull/6875 but seems not get merged due to violate contribution guideline.

**Comment by d12frosted** [comment]
Hey,

Try adding `(add-hook 'prog-mode-hook 'rainbow-mode)` to `dotspacemacs/user-config` function in your `.spacemacs` file.
