### ISSUE TITLE
No characters but little boxes since last update ...

### ISSUE THREAD

**Issue by Schelmenzunft** [syl20bnr/spacemacs#7696]
Can't file a bug in Spacemacs since I don't see any characters on the screen but little boxes.
Do I have to install a special font?

I'm on OSX 10.11.6 with Spacemacs 0.200.5@25.1.1 (emacs-mac homebrew port).

**Comment by TheBB** [comment]
Yes, you're probably missing some font or your font configuration is messed up.

**Comment by deb0ch** [comment]
Does it look like something like [that](https://github.com/adobe-fonts/source-code-pro/issues/17#issuecomment-223753308) ?

**Comment by Schelmenzunft** [comment]
@deb0ch Exactly :-) Do you know how to fix on OSX?

**Comment by deb0ch** [comment]
Nope, but it should be detailed in that thread, isn't it ?

**Comment by Schelmenzunft** [comment]
Found the link to the binaries and installed them using the font utility in OSX and everything is working again - previously I had installed a broken Source Code Pro version. Thanks.
