### ISSUE TITLE
Key shortcut for gtags missed

### ISSUE THREAD

**Issue by miraclemore** [syl20bnr/spacemacs#7697]
I clone the spacemacs today from master branch.
As I follow the gtags layer documents to enable gtags layer from dot spacemacs file
  (setq dotspacemacs-configuration-layers
        '( ;; ...
          gtags
           ;; ...
          ))
But when i open my c source files, there is no alt+m m shorcut for gtags.
i confirm that i already generate GTAGS related files on my workspace.
Due to i am newer for emacs, is there anyone know the entire configuration for gtags on spacemacs ?

**Comment by bmag** [comment]
Please post the output of `SPC h d s`, it will give us more info about your setup. When reporting issues, you can also use the template prodcued by the shortcut `SPC h I`. You might have configured your layers incorrectly. Did you enable the `c-c++` layer? (`SPC h d s` will answer that question)

**Comment by miraclemore** [comment]
thx for your help!.
i will follow that rule.

**Comment by TheBB** [comment]
Did you enable the c-c++ layer?

**Comment by miraclemore** [comment]
Already enable that, and gtags worked fine for me now.
And i will check the entire document for spacemacs.
thx for both your help!
