### ISSUE TITLE
ac-php not working properly

### ISSUE THREAD

**Issue by cjohansson** [syl20bnr/spacemacs#7699]
If I add this to my .spacemacs in the section `(defun dotspacemacs/user-config ()`

```elisp
  (use-package company-php)
  (use-package ac-php
     :config
     (add-hook 'php-mode-hook
               '(lambda ()
                  (add-to-list 'company-backends 'company-ac-php-backend)
                  (setq ac-sources '(ac-source-php)))))
```

And this to my `dotspacemacs-additional-packages`

```elisp
ac-php
company-php
```

And this to my `dotspacemacs-configuration-layers`

```elisp
     (auto-completion :variables
                      auto-completion-enable-snippets-in-popup t
                      auto-completion-enable-help-tooltip t
                      auto-completion-enable-sort-by-usage t)
    php
```

And after creating a `ac-php-conf.json` file in project root and running `ac-php-remake-tags`.

**Expected result**
 I should get scope-based auto-completion, like namespaces, classes, methods and functions with function descriptions generated from PhpDoc.

**Actual result**
Only name based auto-completion based on current file without function descriptions.

It works without Spacemacs but it doesn't work with Spacemacs.

**Comment by TheBB** [comment]
Can you confirm whether the company backend is actually in the company-backends list, and whether it works if you call the company backend directly?

**Comment by cjohansson** [comment]
Do you mean this?

describe-variable:company-backends

```
...
Value: ((company-dabbrev-code company-gtags company-etags company-keywords :with company-yasnippet)
 (company-files :with company-yasnippet)
 (company-dabbrev :with company-yasnippet))

Original value was 
(company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)

Local in buffer Application.php; global value is 
(company-ac-php-backend php-extras-company company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
                        (company-dabbrev-code company-gtags company-etags company-keywords)
                        company-oddmuse company-dabbrev)
```

If I manually run `company-ac-php-backend` I get the error `Cannot complete at point`

**Comment by dbrw** [comment]
Any update on this?
It would be nice to have PHP layer with PHPdoc based auto completion.
