### ISSUE TITLE
Haskell snippets are over-indented on every line

### ISSUE THREAD

**Issue by mrkgnao** [syl20bnr/spacemacs#7700]
#### Description :octocat:
Haskell snippets are incorrectly indented on insertion

#### Reproduction guide :beetle:
- Start Emacs
- Open a Haskell file
- Type, say, `fn`
- Press `M-/` and select one of the matching snippets
- Press `Return` to insert it

*Observed behaviour:* :eyes: :broken_heart:
This is what's inserted:

```haskell
f :: a -> b
  f pattern = undefined
  f pattern = undefined
```

The extra indentation on the lines after the first one breaks the snippet.

*Expected behaviour:* :heart: :smile:
Properly indented code should be inserted, i.e. something like this:

```haskell
f :: a -> b
f pattern = undefined
f pattern = undefined
```

My guess is that Spacemacs is behaving like `vim` when one pastes code without doing `:set paste` beforehand and indenting every line successively as if the snippet were being directly typed into the buffer.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. c82239a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(better-defaults
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 fasd
 (syntax-checking :variables
                  (syntax-checking-enable-by-default t))
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'complete auto-completion-complete-with-key-sequence "kj" auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" auto-completion-enable-help-tooltip t :disabled-for org erc)
 (ranger :variables ranger-show-preview t ranger-override-dired t)
 ivy smex version-control git emacs-lisp purescript rust java python django javascript html yaml markdown shell-scripts
 (haskell :variables haskell-completion-backend 'intero haskell-enable-ghc-mod-support nil haskell-process-type 'stack-ghci haskell-process-args-stack-ghci
          '("--ghc-options=-ferror-spans" "--with-ghc=intero")
          hindent-style "johan-tibell" haskell-stylish-on-save t)
 (latex :variables
        (latex-build-command "latexmk -pvc -pdf -view=none" latex-enable-auto-fill t))
 (org :variables
      (org-enable-github-support t))
 command-log
 (semantic :disabled-for emacs-lisp)
 games selectric xkcd)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by Miciah** [comment]
This issue was fixed upstream with https://github.com/joaotavora/yasnippet/pull/743 / https://github.com/joaotavora/yasnippet/commit/5534cab0b70cc5c88fcfb8a4a90cc5a18464db2e.

**Comment by Miciah** [comment]
@mrkgnao, can you confirm that the issue is resolved by using a newer yasnippet package? If it is, we should label this issue "Fixed upstream" and close it.
