### ISSUE TITLE
I can't open call find-file-at-point with <g f> in Compilation mode

### ISSUE THREAD

**Issue by FrancescElies** [syl20bnr/spacemacs#7702]
#### Description :octocat:
I can't open call `find-file-at-point` with `<g f>` in `Compilation` mode

#### Reproduction guide :beetle:
- Start Emacs
- Open a python file with some tests
- Run some test with `<, t t>`
*Observed behaviour:* :eyes: :broken_heart:
A new buffer in compilation mode with the results of the test is opened.
But I can't call `find-file-at-point` typing `<g f>`

*Expected behaviour:* :heart: :smile:
I would love to call `find-file-at-point` typing `<g f>` in `Compilation` mode

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.3
- Spacemacs branch: master (rev. b3918e8)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t
                  (haskell :variables haskell-completion-backend 'intero))
 better-defaults deft
 (elfeed :variables rmh-elfeed-org-files
         (list "~/.private/feed-index.org")
         elfeed-search-filter "@1-week-ago  unread ")
 csv
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 command-log emacs-lisp elm emoji erc fasd
 (git :variables git-magit-status-fullscreen t git-enable-github-support t git-gutter-use-fringe t)
 github gnus gtags haskell html ipython-notebook javascript latex markdown
 (org :variables org-agenda-files
      (list "~/org/sprints/fred.org" "~/org/home.org"))
 osx
 (python :variables python-test-runner 'pytest)
 (ranger :variables ranger-cleanup-eagerly t ranger-cleanup-on-disable t ranger-ignored-extensions
         '("mkv" "iso" "mp4")
         ranger-max-preview-size 10 ranger-parent-depth 2 ranger-show-preview t)
 restclient ruby search-engine semantic slack
 (shell :variables shell-default-shell 'multi-term)
 speed-reading spell-checking syntax-checking typescript
 (version-control :variables version-control-global-margin t)
 yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

```

**Comment by bmag** [comment]
`compilation-mode` buffers are opened in `motion` state, which doesn't have a binding for `gf` or `gF` (these are defined for `normal` state). We can add the binding by using `evil-define-key` for `motion` state and `compilation-mode-map` keymap. PR welcome. In the meantime, `RET` should also work (and better) when the compilation buffer puts a link on the filename.

**Comment by FrancescElies** [comment]
Hi,
thanks for the quick response, as you suggested `RET` works perfectly, I found in the documentation as `RET compile-goto-error`, nice!
I'll check if I can manage to define the motion correctly and submit a PR

**Comment by FrancescElies** [comment]
closing in favor of the PR https://github.com/syl20bnr/spacemacs/pull/7712
