### ISSUE TITLE
FSharp mode auto-completion not working

### ISSUE THREAD

**Issue by abhi18av** [syl20bnr/spacemacs#7704]
#### Description :octocat:
I've added the FSharp layer to my `.spacemacs` but it's not functioning as it's supposed to. The ideas setup behaviour would be [the popup suggestions working like so.](http://blog.nikosbaxevanis.com/2015/04/25/fsharp-on-emacs-with-spacemacs/)

I've tried out various combinations using the instructions outlined in the [official F# emacs repo](https://github.com/fsharp/emacs-fsharp-mode) but the variables themselves seem to be missing. Please let me know if it is an error on my part.

* I've filed an issue over there as well, but please do suggest me something. I really need this to be working asap.
#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(mu4e auto-completion better-defaults emacs-lisp clojure git markdown org haskell html java javascript python fsharp sql ipython-notebook react xkcd emoji finance search-engine dash fasd pandoc chinese restclient prodigy gtags deft colors
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      (ruby :variables ruby-enable-enh-ruby-mode t ruby-test-runner 'rspec ruby-version-manager 'rbenv)
      spell-checking syntax-checking version-control)
```
- System configuration features: JPEG RSVG IMAGEMAGICK DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by TheBB** [comment]
The fsharp layer has no particular support for auto-completion. (Nowehere in the fsharp layer readme does it mention anything about this.) You can enable global company mode, but you'll only get non-semantic completion.

**Comment by abhi18av** [comment]
Hmm, but it does mention `fsharp-ac-use-popup` so I figure that company mode would also be there as well. I think, global company mode is enabled by default right?

**Comment by TheBB** [comment]
> Hmm, but it does mention fsharp-ac-use-popup so I figure that company mode would also be there as well.

I don't see where it mentions that, actually.

> I think, global company mode is enabled by default right?

No it's not, if you want that you have to enable it yourself. (See auto-completion layer readme.)

**Comment by abhi18av** [comment]
Copy-pasting it from the official repo, here.
```markdown

### Behavior

There are a few variables you can adjust to change how fsharp-mode behaves:

- `fsharp-ac-use-popup`: Show tooltips using a popup at the cursor
  position. If set to nil, display the tooltip in a split window.

- `fsharp-doc-idle-delay`: Set the time (in seconds) to wait before
  showing type information in the minibuffer.
  
- `fsharp-ac-intellisense-enabled`: This mode overrides some aspects of
  auto-complete configuration and runs the background process automatically.
  Set to nil to prevent this. Note that this will only prevent the background
  process from being launched in the *future*. If it is already running you
  will also need to quit it using <kbd>C-c C-q</kbd>.

You might also add `company-sort-prefer-same-case-prefix` to the list
of company transformers to to prefer exact case sort in completion
lists:

```lisp
(add-to-list 'company-transformers 'company-sort-prefer-same-case-prefix)
```
```

Oh, right. Let me experiment with the auto-completion layer, thanks for the hint 👍

**Comment by TheBB** [comment]
Okay, maybe fsharp-mode has some integration with ac and/or company. If that's the case we would of course welcome a PR to make this work with Spacemacs.

Sorry I can't help you further than that.

**Comment by abhi18av** [comment]
Yeah, let's wait if something comes along.
