### ISSUE TITLE
ggtags, cscope's keymap is not complete in ivy.

### ISSUE THREAD

**Issue by zwb-ict** [syl20bnr/spacemacs#7713]
#### Description :octocat:
When use layer **ivy**, in c/c   mode, run **SPC m g** for jump to tags, but ggtags and cscope layers key is not complete.
I only see 
```
SPC m g A
SPC m g a
SPG m g G
SPC m g g
SPC m g i
```
if I add layer "helm", run **SPC m g**, then ggtags and cscope's keymap is complete.

#### Reproduction guide :beetle:
- Start Emacs
- use layer ivy, without layer helm.
- open a C/C   file, run **SPC m g** for jump
- add layer helm, run **SPC m g** again

*Observed behaviour:* :eyes: :broken_heart:
When only use ivy, ggtags and cscope's keymap is not complete.

*Expected behaviour:* :heart: :smile:
I hope only use ivy without helm layer, ggtags and cscope's keymap is complete.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. a134714)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(erc syntax-checking
     (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'complete)
     ivy nginx better-defaults
     (org :variables org-enable-github-support t)
     semantic ruby-on-rails
     (chinese :variables chinese-enable-fcitx t)
     (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
     emacs-lisp
     (go :variables gofmt-command "goimports")
     html
     (javascript :variables javascript-disable-tern-port-files nil)
     lua markdown
     (ruby :variables ruby-enable-enh-ruby-mode t ruby-version-manager 'rvm ruby-test-runner 'chruby)
     (python :variables python-test-runner
             '(nose pytest))
     (rust :variables rust-format-on-save t)
     shell-scripts yaml osx floobits
     (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
     github
     (version-control :variables version-control-diff-tool 'git-gutter  version-control-global-margin t)
     (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
     cscope
     (gtags :variables gtags-enable-by-default t)
     (dash :variables helm-dash-docset-newpath "~/Library/Application Support/Dash/DocSets")
     docker fasd imenu-list ranger
     (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/usr/local/bin/zsh")
     tmux vagrant
     (ycmd :variables ycmd-server-command
           '("python" "/Users/zwb/.bin/ycmd/ycmd")
           ycmd-force-semantic-completion t)
     blog gtd zwb)
```
- System configuration features: IMAGEMAGICK DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by bmag** [comment]
What keys are available with Helm the are not available with Ivy?

**Comment by zwb-ict** [comment]
![image](https://cloud.githubusercontent.com/assets/10378547/20238991/0c99b414-a932-11e6-9024-ca486c1940ae.png)

**Comment by zwb-ict** [comment]
when ivy layer:
![image](https://cloud.githubusercontent.com/assets/10378547/20239008/552022cc-a932-11e6-80ec-14d26a9cb5e9.png)

**Comment by zwb-ict** [comment]
It seems that, when use ivy layer only, package helm-gtags and helm-cscope will not be installed:

![image](https://cloud.githubusercontent.com/assets/10378547/20239034/ad3e8ee4-a932-11e6-844e-441dbfb448a8.png)

**Comment by bmag** [comment]
Ok, I see now. The current behavior makes sense, because we don't have an Ivy integration for cscope and gtags. See #6121, I'm closing this one as a duplicate issue.

**Comment by zwb-ict** [comment]
Thank you @bmag, I doubt is there away to use helm-cscope and helm gtags with ivy layer? I saw in elpa dir there are helm and helm-core. Is it enough?

**Comment by bmag** [comment]
It's not officially supported, but you can have both `helm` and `ivy` layers enabled at the same time. Another option is to enable `ivy`, and to enable `helm` only for certain layers, e.g. `(helm :enabled-for cscope gtags)` instead of `helm` in your enabled layers list. A third option is to copy the configuration for `helm-cscope`, `helm-gtags` and whatever else is necessary to a private layer.

**Comment by zwb-ict** [comment]
Thank you @bmag I changed
```
(defconst gtags-packages
  '(
    ggtags
    (helm-gtags :toggle (configuration-layer/package-usedp 'helm))
    ))
```
to
```
(defconst gtags-packages
  '(
    ggtags
    helm-gtags
    ))
```
and do  the same to cscope, then all the things goes well very.

I have two doubts.
1. Is there a config way to cover 
```
(helm-gtags :toggle (configuration-layer/package-usedp 'helm))
```
in init.el;
2. Is this toggle is necessary? if delete this toggle, only helm-gtags and helm-cscope package will be installed, and don't need helm layer. Should we suggest officially to support this?

**Comment by bmag** [comment]
> Should we suggest officially to support this?

Support what exactly? Please be more precise.

> Is this toggle is necessary?

Yes, because of consistency. If the user specifically chooses to use Ivy, it will be surprising to show a Helm prompt. Instead of deleting the toggle, you can add `helm` to `dotspacemacs-additional-packages` to get the same effect (and also enable some other packages that depend on Helm, like `helm-c-yasnippet`).

**Comment by zwb-ict** [comment]
Thank you @bmag, I understand the toggle now, so nothing to suggest.

**Comment by zwb-ict** [comment]
@bmag  I add helm to dotspacemacs-additional-packages, but configuration-layer/package-usedp 'helm) still return false.

**Comment by bmag** [comment]
Really? For me, `configuration-layer/package-usedp` returns non-nil for packages that I installed as additional packages. There might be a different error in your config that causes `(configuration-layer/package-usedp 'helm)` to return nil as a side-effect.
If you can't get the additional package working, you can try installing helm through a private layer (you'll need to write a `<layer>/init-helm` function)
