### ISSUE TITLE
org-enable-reveal-js did work

### ISSUE THREAD

**Issue by wxjeacen** [syl20bnr/spacemacs#7714]
#### Description :octocat:
org-enable-reveal-js did work

#### Reproduction guide :beetle:
- Start Emacs
- Add below code to .spacemacs file
```
(org :variables org-enable-reveal t) in configuration-layers section 
```
- restart Emacs

*Observed behaviour:* :eyes: :broken_heart:
package ox-reveal did not installed properly.

*Expected behaviour:* :heart: :smile:
package ox-reveal will be installed properly.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html helm auto-completion better-defaults emacs-lisp git markdown
      (org :variables org-enable-reveal-js t)
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control python yaml clojure)
```

**Comment by cpaulik** [comment]
The variable is called differently. See https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bemacs/org#revealjs-support

**Comment by wxjeacen** [comment]
@cpaulik works for me.
