### ISSUE TITLE
Missing variable for LaTeX layer

### ISSUE THREAD

**Issue by MagisDing** [syl20bnr/spacemacs#7718]
I have added latex layer to ~/.spacemacs.d/init.el, and add 
`dotspacemacs-configuration-layers '(
  (latex :variables latex-enable-folding t))`
But one warning :"Missing variables for latex" always shows when emacs launches.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. aa3f181)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-complete-with-key-sequence nil auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-private-snippets-directory
                  '("~/.spacemacs.d/snippets/")
                  :disabled-for org markdown)
 better-defaults bibtex
 (chinese :variables chinese-enable-youdao-dict t chinese-enable-avy-pinyin t)
 (clojure :variables clojure-enable-fancify-symbols t)
 colors deft emacs-lisp
 (git :variables git-magit-status-fullscreen t magit-push-always-verify nil magit-save-repository-buffers 'dontask magit-revert-buffers 'silent magit-refs-show-commit-count 'all magit-revision-show-gravatars nil)
 github graphviz haskell html
 (ibuffer :variables ibuffer-group-buffers-by 'projects)
 ivy javascript
 (latex :variables latex-build-command "Xelatex" latex-enable-auto-fill t)
 markdown org osx prodigy ranger react restclient search-engine
 (scala :variables scala-use-java-doc-style t scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-start-ensime t)
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 (spell-checking :variables spell-checking-enable-by-default nil)
 (spacemacs-layouts :variables layouts-enable-autosave nil layouts-autosave-delay 300)
 (syntax-checking :variables syntax-checking-enable-by-default nil syntax-checking-enable-tooltips nil)
 (typescript :variables typescript-fmt-on-save nil typescript-fmt-tool 'typescript-formatter)
 (typography :variables typography-enable-typographic-editing t)
 (vinegar :variables vinegar-reuse-dired-buffer t)
 yaml zilongshanren)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
Please add a backtrace (`emacs --debug-init`)

**Comment by kccai** [comment]
Try changing 

`(latex :variables latex-build-command "Xelatex" latex-enable-auto-fill t)`

to

`(latex :variables latex-enable-auto-fill t)`

**Comment by MagisDing** [comment]
@kccai Thanks for the reply. But I am good with adding `latex-build-command`, the actually cause for the warning is the variable `latex-enable-folding t`

**Comment by kccai** [comment]
> But I am good with adding latex-build-command, the actually cause for the warning is the variable latex-enable-folding t. Confirmed by test.

That is very strange because auctex in the latex layer does not come with `Xelatex` support if you define `latex-build-command` in that way.  I have been using the latex layer with the following layer configuration
```emacs-lisp
     (latex :variables
            latex-enable-auto-fill t
            latex-enable-folding t)
```
And it works just fine.

If you still get warnings, you need to provide us the backtrace information.

**Comment by MagisDing** [comment]
@kccai, Sorry for my delayed reply. I set the layer with your configuration, same warning occurs. Please forgive my ignorance, how to provide the backtrace info?

**Comment by TheBB** [comment]
Please have a look at [how to make a great bug report](https://github.com/syl20bnr/spacemacs/wiki/Debugging#how-to-make-a-great-bug-report).

**Comment by kccai** [comment]
@MagisDing 
Try following steps:

1. Start Emacs as usual
2. toggle debug on error with `SPC t D`
3. Reload the configuration `SPC f e R`

If a pop-up window is reporting error in Emacs, then copy the message in the window to this issue.

**Comment by angry-bird** [comment]
Also want to config XeLaTeX as my default latex engine, still don't know how. Waiting for your trying. ~_~

**Comment by kccai** [comment]
@angry-bird 
@MagisDing 
If you want to use XeLaTeX to compile your latex file, then you need to add following lines at the end of your file, save the file,  and revert (reopen) the buffer.

```
%%% Local Variables: 
%%% mode: LaTeX
%%% TeX-PDF-mode: t
%%% TeX-engine: xetex 
%%% End:
