### ISSUE TITLE
How can I change the font size of the popup window?

### ISSUE THREAD

**Issue by chrissound** [syl20bnr/spacemacs#7721]
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git
                 (haskell :variables haskell-completion-backend 'intero)
                 syntax-checking)
```

The font size is tiny, bear in mind I'm running with a screen resolution of 4k.

![2016-11-13-11 22 25](https://cloud.githubusercontent.com/assets/1499652/20245171/832e9be2-a993-11e6-8b40-aed399de42ec.png)

**Comment by TheBB** [comment]
It's defined by your desktop environment and its theming of popup windows.

**Comment by chrissound** [comment]
Thank you! I modified the font size in the following file: ~/.config/gtk-3.0/settings.in
