### ISSUE TITLE
LaTeX layer ignores closing $ or \] while highlighting

### ISSUE THREAD

**Issue by mrkgnao** [syl20bnr/spacemacs#7722]
#### Description :octocat:
LaTeX layer does math-mode highlighting past a closing `\]` or `$`

#### Reproduction guide :beetle:
- Work on a semi-large (>500loc) LaTeX file for a while

*Observed behaviour:* :eyes: :broken_heart:
- Enjoy seeing half of your buffer highlighted as if it's in math mode but not really
- If you add a `$` somewhere, the math-mode highlighting stops there. I think the layer doesn't pick up one of the `$` signs for some reason (possible race condition between file editing and parsing?)
- The problem is gone if you restart Emacs or even if you do `SPC b d` and open the file again

*Expected behaviour:* :heart: :smile:
- Pretty, sane highlighting

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. a134714)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(ivy better-defaults syntax-checking auto-completion version-control git
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     markdown yaml org latex django emacs-lisp extra-langs html java javascript purescript python rust shell-scripts
     (haskell :variables haskell-enable-hindent-style "johan-tibell" haskell-completion-backend 'intero haskell-enable-ghc-mod-support nil haskell-process-type 'stack-ghci haskell-process-args-stack-ghci
              '("--ghc-options=-ferror-spans" "--with-ghc=intero")
              haskell-stylish-on-save t)
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
This is auctex's problem, it's been around for ages and won't go away. Just re-apply the mode whenever it happens.
