### ISSUE TITLE
helm-ucs display & insert error

### ISSUE THREAD

**Issue by yangguang760** [syl20bnr/spacemacs#7725]
SPC i u  does not show the unicode char correctly.
For example, BELL is "^G", and the others all looks like a square with its unicode within it, like
```
-----
|0E0|
|18E|
-----
```

I'm sure that it worked well several weeks ago.

**Comment by TheBB** [comment]
Install a font with the symbol you want, or configure whatever font system you are using to use it as a fallback.

**Comment by yangguang760** [comment]
@TheBB 
For my font, the first 100 candidates symbols from helm are all not contained. It confused me. 
After typing something to search, supported symbols displayed well.
Thank you for you help :)
