### ISSUE TITLE
Always ask to open TAGS file when opening new files

### ISSUE THREAD

**Issue by goofansu** [syl20bnr/spacemacs#7730]
Messages are like following:

```
/Users/suyejun/src/egroup/TAGS is a large file, open literally to avoid performance issues? (y or n)
OR
File TAGS is large (19.9M), really open?"
```

Where are these TAGS file coming from? Can I disable them or avoid to disturb me on such warnings?

**Comment by goofansu** [comment]
This question cannot reproduced with a fresh install with master branch.
If anyone meet this issue, please reopen it again.

**Comment by ahmedelgabri** [comment]
I have the same issue with a clean install. Don't know ho to disable this & it's very annoying. 

It's related to ctags for sure, but not sure why do I get this prompt.

**Comment by Zeeker** [comment]
I've encountered the same issue. This can be resolved by using the `customize-variable` command, selecting the `spacemacs-large-file-modes-list` variable and adding `tags-table-mode` to the list of modes.
