### ISSUE TITLE
projectile find file does not use current project

### ISSUE THREAD

**Issue by JoshRagem** [syl20bnr/spacemacs#7731]
#### Description :octocat:
`SPC p f` does not use current project

#### Reproduction guide :beetle:
- Start Emacs
- `SPC p p` select a project and file in that project
- `SPC p f` see files from this project
- `SPC p p` select other project and file
- `SPC TAB` go back to previous file
- `SPC p f` list files in project

*Observed behaviour:* :eyes: :broken_heart:
The files listed in the last step are from the wrong project--it is using the last project selected, instead of the project of the current file. The user has to select the project again to projectile find files.

*Expected behaviour:* :heart: :smile:
The files listed should be in the same project as the current file.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ansible rust python sql markdown javascript erlang yaml themes-megapack ivy auto-completion
         (shell :variables shell-default-shell 'eshell))
```
- System configuration features: JPEG NOTIFY ACL LIBXML2 ZLIB

#### Backtrace :paw_prints:
```

```

**Comment by kingoftheknoll** [comment]
Looks like I've got the exact same setup as you and I'm experiencing the same thing for the last couple months but only this week have I had the time to try and figure it out. 

So far it looks like projectile works by tracking a "project root". As far as I can tell this is a variable that is most explicitly set with `projectile-switch-project` bound to `SPC p p`. When you select a project it calls `projectile-switch-project-by-name` which in turn sets the project and emits `projectile-after-switch-project-hook`. So what you'll find is that no matter what, find files, magit, ag search; if you go through `SPC p p` first it will always work. 

So if my assumptions are correct `project-switch-project` is supposed to be called via a hook callback after `SPC TAB \\ spacemacs/alternate-buffer` or `ivy--switch-buffer-action` or any other thing that changes buffer. 

I'm not sure what this hook would be but that's my gut feeling right now. I should caveat all this by saying while comfortable with Clojure, I'm new to Elisp and the spacemacs codebase so if anyone can give me hits on where to look that would be great.

**Comment by kingoftheknoll** [comment]
Actually after doing a bit more digging it seems more likely that it's `ivy` that's tracking the project directories. `counsel--git-grep-dir` was one example of a var that didn't seem to update.

**Comment by kingoftheknoll** [comment]
For the moment I fixed this problem by running `projectile-invalidate-cache` or `SPC p I (capital i)`.

**Comment by duianto** [comment]
This issue might have been fixed recently in the projectile package. 

[projectile-switch-project breaks after recent caching commit #1150](https://github.com/bbatsov/projectile/issues/1150)

It's working like the "Expected behaviour" for me, in both the latest Spacemacs master and develop branches.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. c9b668ed)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey
 (auto-completion :variables auto-completion-enable-help-tooltip 'manual)
 emacs-lisp git haskell helm markdown
 (org :variables org-agenda-files
      '("c:/Users/Username/Documents/"))
 spell-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by jmay** [comment]
It seems to me that the base projectile functions are working, but the helm-projectile versions are having this problem. e.g. I see different behavior for `C-c p f` (projectile-find-file) vs `SPC p f`(helm-projectile-find-file). {helm-}projectile-switch-project also.

**Comment by JoshRagem** [comment]
it is working again for me. unclear what updates fixed it
