### ISSUE TITLE
[Q] Is there something like the vis vim plugin?

### ISSUE THREAD

**Issue by ninrod** [syl20bnr/spacemacs#7734]
The [vis](http://www.vim.org/scripts/script.php?script_id=1195) vim [plugin](https://github.com/ninrod/vis) allows you to perform searches or operations enclosed inside a visual selected region (block or linewise).
Is there something like it for emacs?
thanks in advance

**Comment by TheBB** [comment]
Narrowing is your best bet.

**Comment by ninrod** [comment]
Thanks, I've tested narrowing. Sadly it does not take block selection into account.

**Comment by TheBB** [comment]
Then no, there's nothing.

**Comment by madhat2r** [comment]
Try using `:` command for replace when you have a selection.

When you enter `:` you should get  a prompt that has `:'<,'>` that means it is limiting the search replace to the selected region. just enter your normal replace expression `:'<,'>s/search/replace/[flags]` This is what I do.
