### ISSUE TITLE
select all (mark-whole-buffer) key binding, a suggestion to make it easier to find

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#7738]
### This might help spacemacs beginners to find the "select all" key binding.

Selecting everything in most applications, is done with a "Select all" command, but in emacs the command is called `mark-whole-buffer`. I wasn't able to find it without googling, because i didn't know that selecting also could be called "mark" and that i should have searched for "mark buffer" in helm desbinds <kbd>SPC ?</kbd>.

### Possible solution
A function could be added that just calls `mark-whole-buffer`, with a name that can be found by searching for "select all".

```
(defun select-all-text-in-buffer ()
  "This just calls the `mark-whole-buffer' command. The new function
name makes it possible to find it by searching for \"select all\"."
  (interactive)
  (mark-whole-buffer))
```

### Issue
I tried adding the function to the file: `../emacs-w64-25.1-O2/share/emacs/25.1/lisp/simple.el` below the `mark-whole-buffer` function. After evaluating it manually (with the cursor in the function) <kbd>, e f</kbd>, then it can be found in helm M-x.

But when emacs is restarted then it has to be evaluated again before it can be found in helm M-x again.

### Key binding

The function needs to have a key binding to show up in helm descbinds <kbd>SPC ?</kbd>. A good place to add the new key binding might be to the expand region <kbd>SPC v</kbd> (transient state?) as the key binding: <kbd>SPC v a</kbd> "a to select all".

#### Currently the <kbd>SPC v</kbd> listed keys look like this:
`Type v to expand again, V to contract, r to reset, e to edit, / to search in project, f to search in files, b to search in opened buffers`

#### With "a to select all" added it would look like this
`Type v to expand again, V to contract, a to select all, r to reset, e to edit, / to search in project, f to search in files, b to search in opened buffers`

#### Possible rewrite
There's a lot of duplicate words that make it look cluttered and it's not obvious which keys to press. It should probably be rewritten to look like the other transient states:
```
select:    [v] expand   [V] contract        [a] all    [e] edit  [r] reset
search in: [/] project  [b] opened buffers  [f] files
```

or like this:
```
select                             search in
[v] expand  [V] contract  [a] all  [/] project       [f] files
[e] edit    [r] reset              [b] open buffers
```

**Comment by TheBB** [comment]
We have a "whole buffer" text object, it's in the [documentation](http://spacemacs.org/doc/DOCUMENTATION.html#additional-text-objects).

**Comment by duianto** [comment]
I didn't know about that <kbd>v i g</kbd> key binding, but i knew about <kbd>g g V G</kbd>, i just thought it might make it easier to find if one searches for the key binding in helm descbinds <kbd>SPC ?</kbd>. 

I don't know if it's possible, but maybe another solution would be to add something like a search term to the `mark-whole-buffer` function, so that it also shows up in descbinds when one searches for "select all". But i suspect that it's outside the scope of how descbinds work, and it only looks for the function names of bound keys.

**Comment by duianto** [comment]
I've been using the <kbd>i g</kbd> to select/copy/delete the whole buffer and it works great.

After thinking some more about this, i realized that it's unnecessary to add another function just to make it easier to find the select all/mark whole buffer command. And the reformatting of the expand region keys should be a separate issue. So i'll close this.
