### ISSUE TITLE
rcirc-track-minor-mode only shows *invalid* in spaceline

### ISSUE THREAD

**Issue by mnetzwur** [syl20bnr/spacemacs#7739]
#### Description :octocat:
rcirc-track-minor-mode only shows "*invalid* in spaceline"

#### Reproduction guide :beetle:
- Start Emacs
- Start rcirc in your preferred way
- SPC-SPC rcirc-track-minor-mode
- Join some channels, wait for some activity.

*Observed behaviour:* :eyes: :broken_heart:
The string "&ast;invalid&ast;" appears towards the right edge of the spaceline.

*Expected behaviour:* :heart: :smile:
The names of buffers with channel activity appear in the spaceline. It would be even better if they appeared where erc-track appears, since they will often be out of view in column mode when they're too far to the right.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp
                 helm html markdown mu4e osx pandoc pdf-tools python
                 (rcirc :variables rcirc-enable-znc-support t)
                 (shell :variables shell-default-shell 'multi-term shell-default-term-shell "/bin/bash"))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by TheBB** [comment]
What does `(format-mode-line global-mode-string)` evaluate to?

**Comment by mnetzwur** [comment]
![screenshot 2016-11-15 14 27 50](https://cloud.githubusercontent.com/assets/15339801/20307486/f7c05132-ab3f-11e6-9e94-c1bac03c785c.png)

**Comment by TheBB** [comment]
Other questions:

* What is `global-mode-string`
* What is the value of 
```elisp
(let ((segs (assq 'main spaceline--mode-lines)))
  (append (spaceline--global-excludes (cadr segs))
          (spaceline--global-excludes (cddr segs))))
```
* If `global-mode-string` is a list, what is the value of
```elisp
(-difference global-mode-string
             (let ((segs (assq 'main spaceline--mode-lines)))
               (append (spaceline--global-excludes (cadr segs))
                       (spaceline--global-excludes (cddr segs)))))
```

**Comment by mnetzwur** [comment]
Question 1:
`((:eval mu4e-alert-mode-line) rcirc-activity-string)`

Question 2:
```
(org-mode-line-string org-pomodoro-mode-line 
                      (:eval mu4e-alert-mode-line) 
                      fancy-battery-mode-line)
```

Question 3:
`(rcirc-activity-string)`

**Comment by TheBB** [comment]
Ok thanks. https://github.com/TheBB/spaceline/pull/119 should fix it. Can you confirm?

**Comment by mnetzwur** [comment]
Yeah, that did the trick. Thanks!

**Comment by TheBB** [comment]
Ok, merged upstream. Thanks.
