### ISSUE TITLE
stekene-dark theme gives a warning

### ISSUE THREAD

**Issue by elvis-sik** [syl20bnr/spacemacs#7740]
#### Description :octocat:
`stekene-dark` theme seems to be broken. Please note that I've tried `git pull --rebase`-ing my Spacemacs (so I have tried latest develop with the exact same behavior) despite what it says on the `System Info` section.

#### Reproduction guide :beetle:
- Start Emacs with `stekene-dark` theme as the first one in `.spacemacs`

*Observed behaviour:* :eyes: :broken_heart:
Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (error Package ‘stekene-theme-’ is unavailable))

*Expected behaviour:* :heart: :smile:
Beautiful eye candy.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 58c8fd5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv auto-completion better-defaults emacs-lisp git markdown
     (shell :variables shell-default-height 30 shell-default-position 'bottom shell-default-shell 'multi-term shell-default-term-shell "/bin/zsh" shell-enable-smart-eshell t)
     spell-checking smex syntax-checking version-control cscope gtags semantic xkcd github
     (c-c   :variables c-c  -default-mode-for-headers 'c-mode c-c  -enable-clang-support t)
     extra-langs html javascript shell-scripts sql yaml
     (python :variables python-test-runner 'pytest python-enable-yapf-format-on-save t)
     ipython-notebook
     (haskell :variables haskell-enable-ghc-mod-support t haskell-enable-hindent-style "gibiansky" haskell-enable-shm-support t haskell-completion-backend 'intero)
     evil-commentary
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t evil-snipe-repeat-scope "visible")
     react idris evil-cleverparens asm octave systemd ess
     (ranger :variables ranger-show-preview t)
     selectric)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by TheBB** [comment]
Steken has been removed from MELPA because it is unmaintained.

https://github.com/melpa/melpa/pull/4369
