### ISSUE TITLE
[Documentation] Add instructions on how to customize evil-lisp-state keymap

### ISSUE THREAD

**Issue by aeberts** [syl20bnr/spacemacs#7746]
Apologies if this is already stated somewhere but it's not obvious how to configure keybindings for ```evil-lisp-state``` without directly changing the ```evil-lisp-state-commands``` map in ```/.emacs.d/elpa/evil-lisp-state/evil-lisp-state.el```

I have tried adding the following to ```user-config```: 

```
(with-eval-after-load 'evil-lisp-state
   (bind-keys :map evil-lisp-state-map
       ("f" . sp-down-sexp)))
```

but ```evil-lisp-state``` is not enabled after the command is executed.

**Comment by TheBB** [comment]
```elisp
(define-key evil-lisp-state-map "f" (evil-lisp-state-enter-command sp-down-sexp))
```

**Comment by aeberts** [comment]
Thanks. Works for me.
