### ISSUE TITLE
[Haskell] Problems when using :cd to set emacs directory

### ISSUE THREAD

**Issue by cgag** [syl20bnr/spacemacs#775]
I should note I'm new to emacs and spacemacs so I may be missing something obvious.

I'm using the GUI emacs on Debian.  When I cd into a project directory on the shell (one with .git and cabal files), run `emacs &` and then open a Haskell file, I can then run `SPC m c c` and see if it compiles.  The REPL as started with `SPC m s S` works fine as well.

If I just open Emacs through my app launcher (dmenu) and then run :cd and change into a project directory, then open and Haskell file and run `SPC ms c c` I get errors about not being able to find GHC:

```
-*- mode: haskell-compilation; default-directory: "~/code/yorgey/" -*-
HsCompilation started at Sat Mar  7 12:35:47

cd /home/cgag/code/yorgey/ && cabal build --ghc-option=-ferror-spans
cabal: The program 'ghc' version >=6.4 is required but it could not be found.
Warning: Couldn't reinstall some add-source dependencies.
Some add-source dependencies have been reinstalled. Re-configuring with most
recently used options. If this fails, please run configure manually.
cabal: The program 'ghc' version >=6.4 is required but it could not be found.

HsCompilation exited abnormally with code 1 
```

If I start a REPL, I'm unable to enter any commands.  Flycheck doesn't detect any errors.  Basically nothing Haskell related works unless I initially open emacs in the correct directory.

**Comment by syl20bnr** [comment]
Is your dmenu running as another user (say root) ?

**Comment by cgag** [comment]
Hmm now that I try running emacs from the terminal outside of the project directory and then using :cd, I see that it works, so it's almost certainly dmenu's fault.   I've gotta run, I'll investigate how to figure out what user dmenu runs as later and update this.  Thanks!

**Comment by syl20bnr** [comment]
@cgag do you have any news to share ?

**Comment by cgag** [comment]
Nothing past thinking it's dmenu or i3's fault, but I haven't been able to figure out what they're doing to cause it, but I haven't looked too deeply, I'll try to set some time aside on monday and dig it into it.

**Comment by cgag** [comment]
I don't seem to be able to reproduce this anymore, not sure what changed, but I'm just going to close this.
