### ISSUE TITLE
ZZ doesn't delete buffer in server mode

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#7750]
#### Description :octocat:
ZZ doesn't delete buffer in server mode

#### Reproduction guide :beetle:
- Start Emacs in daemon mode
- Start emacsclient with a file
- Edit file
- Save - quit with `ZZ`

*Observed behaviour:* :eyes: :broken_heart:
The emacs frame closes, but when a new client window is opened without a file, the buffer still exists.

*Expected behaviour:* :heart: :smile:
The buffer should be deleted, and a new client window should open the scratch buffer (or preferably, the spacemacs home buffer)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. fea919c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-complete-with-key-sequence "<tab> <tab>" auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
 colors emacs-lisp extra-langs git markdown org syntax-checking
 (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion t)
 typography
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "gibiansky")
 python pandoc latex html csv asm ipython-notebook shell-scripts yaml semantic cscope dash vim-empty-lines)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
```

**Comment by TheBB** [comment]
> The buffer should be deleted

The docstring for `ZZ` says that it closes the *window*, not the buffer.

**Comment by beojan** [comment]
In order to work like vim, it should also close the buffer. Otherwise, using emacsclient to edit many different files leaves a large number of buffers open. The same really applies for `:q` as well.

**Comment by TheBB** [comment]
If `ZZ` does something else than vim you should report to evil, not us.
