### ISSUE TITLE
How to set different fonts between chinese and english?

### ISSUE THREAD

**Issue by asdyjd** [syl20bnr/spacemacs#7751]
In old version I can set different fonts between chinese and english with `spacemacs//set-monospaced-font` command in `chinese layer`.
`(spacemacs//set-monospaced-font   "Consolas" "等线" 16 18)`
But I don't know from which version,that command doesn't work in .emacs file.And it's useful in elisp mode.I tested it.
It seems it is executed at first and then overwritten by `dotspacemacs-default-font` in `.spacemacs`.

**Comment by TheBB** [comment]
> But I don't know from which version

You can git bisect to find out.

**Comment by asdyjd** [comment]
It's good in 0.105.22 and bad in 0.200.1

**Comment by asdyjd** [comment]
It's done.
I have found a way to set the font for only chinese.
```
  (dolist (charset '(kana han symbol cjk-misc bopomofo))
    (set-fontset-font (frame-parameter nil 'font)
                      charset (font-spec :family "等线" :size 16)))
```
