### ISSUE TITLE
Make space-doc-mode available for any Org file

### ISSUE THREAD

**Issue by jlombera** [syl20bnr/spacemacs#7757]
#### Description :octocat:
`space-doc-mode` is very convenient to view notes/doc, I use it to view my personal notes too, not just Spacemacs's.  However, this function is not auto-loaded for org-mode files, it is available only after some Spacemacs doc is visited (e.g. after `SPC h l ...`).  This means that I need to open a random Spacemacs doc before I can use `space-doc-mode` to view my documents.

It would be would that `spac-doc-mode` were available right away (auto-loaded?) for any Org document.  Furthermore, since it is such a great view mode (IMHO), it would be even better if it were mapped to a key binding by default (e.g. `SPC m v`).

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. fea919c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults emacs-lisp git markdown org spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

**Comment by TheBB** [comment]
I mean, all you need is to mark it as autoloadable.

`(autoload 'space-doc-mode "space-doc" nil 'interactive)`

Then you can add it to org-mode-hook as usual.

**Comment by jflombera** [comment]
Thanks for the pointer, I will do that.  However, it would be good if this were provided by default in stock Spacemacs.

**Comment by TheBB** [comment]
Yeah that's why I mentioned it, now you can PR. ;-)

**Comment by jflombera** [comment]
@TheBB thank you for you promptly reply.

I am new to Emacs and am not so familiar (yet) to Emacs/Spacemacs architecture/design and elisp in general.  I guess this is a trivial change but it will take me perhaps a little more time.  Sure, I will do it, just have a little patience with me ;)

**Comment by Beta1440** [comment]
Don't forget to close this issue.

**Comment by blackdev1l** [comment]
Hello, sorry if i'm writing here but i don't know if the right place to ask, but is this issue being resolved in the stable release? Because i'm interested as well to space-doc-mode in my org files and i'd like to know how to use it
