### ISSUE TITLE
Perl Layer

### ISSUE THREAD

**Issue by PrgrmAtCeleritas** [syl20bnr/spacemacs#7758]
It would be great to have a Perl layer added to spacemacs. It could include [PLSense](https://github.com/aki2o/emacs-plsense) for auto-completion, [dumb jump](https://github.com/jacktasia/dumb-jump) for jump to definition, [perl flymake](https://github.com/flymake/emacs-flymake-perlcritic) for syntax checking, [helm perldoc](https://github.com/syohex/emacs-helm-perldoc) for perldoc browsing, [perl6 support](https://github.com/hinrik/perl6-mode), and [more](https://github.com/jplindstrom/emacs-lang-refactor-perl). 

My question is, has this been discussed before, and is there any political willpower within the Spacemacs community to make this happen? I would be willing to contribute but I am still quite new to Spacemacs, and Emacs in general.

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/issues/5019

**Comment by PrgrmAtCeleritas** [comment]
I'll take that as a no.

**Comment by AlexDaniel** [comment]
The question was asked about Perl 5, but Perl 6 ticket was linked? What's going on?

**Comment by AlexDaniel** [comment]
In fact, OP does the same mistake. These are two different languages, why one layer for both?

**Comment by PrgrmAtCeleritas** [comment]
That's a good point. What I really need is a Perl 5 layer. But there is no reason it couldn't have Perl 6 support as well. I have started development on a Perl layer that I hope to do a PR with.

**Comment by AlexDaniel** [comment]
This issue has to be renamed to “Perl 5 Layer” and reopened.

**Comment by PrgrmAtCeleritas** [comment]
I think I will have to open a new issue if we want this opened again.
