### ISSUE TITLE
popup hint misplaced

### ISSUE THREAD

**Issue by bravomikekilo** [syl20bnr/spacemacs#7763]
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>
#### Description :octocat:
the popup hint misplaced in a wired way. seems that there is a scale or something.

#### Reproduction guide :beetle:
- Start Emacs
- try to get a hint

*Observed behaviour:* :eyes: :broken_heart:
the popup placed in a wired way . 
![screenshot from 2016-11-17 11-17-46](https://cloud.githubusercontent.com/assets/17548436/20375194/87657a6e-acb8-11e6-9794-b28f1336866e.png)
*Expected behaviour:* :heart: :smile:
normal placed popup

#### System Info :computer:
- OS: gnu/linux ubuntu16.10 
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown org python
      (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support t)
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      syntax-checking)
```
I use a 4K display and set the gnome DPi scale to 2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by bmag** [comment]
Most likely an upstream issue. The package that provides this popup is `flycheck-pos-tip`.

**Comment by bravomikekilo** [comment]
I solver a the problem
it seems that there is something wrong with the gtk-tooltip. It haven't consider the window scaling for HiDPi. 
so I just set the `x-gtk-use-system-tooltips` to `nil` in the `user-config` to let emacs use its own API.
