### ISSUE TITLE
emacs daemon mode can't read path variable correctly. 

### ISSUE THREAD

**Issue by zhexuany** [syl20bnr/spacemacs#7765]
I am rookie of using emacs daemon mode. But recently, I am tired of waiting tedious loading time. 
The problem I found while using emacs daemon is that emacs can't load `PATH` correctly. 
The output of `echo $PATH` when I use emacs:
`/root/repo/go/bin:/usr/local/go/bin:/root/repo/go/bin:/usr/local/go/bin:/root/repo/go/bin:/usr/local/go/bin:/root/repo/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

But when I use emacs in daemon, the output of `echo $PATH` is quite different:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`

I am really happy if anyone can give me hits about how to solve this. Without correct `PATH` variable, emacs doesn't work in a lot of things such as `go-mode`. 

Extra Info:

System: Ubuntu 16.04
Emacs: 25.1

**Comment by TheBB** [comment]
This is the responsibility of `exec-path-from-shell`, please start looking there.

**Comment by zhexuany** [comment]
@TheBB It's actually not `exec-path-from-shell` issue. I add a user in my machine and stop using `root` fixed the problem. I sincerely wish anyone can tell me why is this.

**Comment by TheBB** [comment]
I don't know why, but I'm not surprised. Lots of things will break if you try to run them as root.

**Comment by TheBB** [comment]
And running Spacemacs as root is a really bad idea.
