### ISSUE TITLE
Use compile_commands.json with clang complete

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#7768]
Would it be possible to use a `compile_commands.json` file with clang complete, as is currently possible with a `.clang_complete` file?

I would use `ycmd`, but I am unimpressed with the completions it provides, appearing to simply list all matching symbols, without any contextual awareness (for instance `window->` lists global identifiers instead of members of the object `window` points to).

**Comment by TheBB** [comment]
See https://github.com/syl20bnr/spacemacs/issues/5718 and attached PR.

Closing this as duplicate.
