### ISSUE TITLE
buffer popup with error trace

### ISSUE THREAD

**Issue by tippenein** [syl20bnr/spacemacs#7771]
#### Description
When I save, a buffer pops up with 
```
$HOME/.stack/snapshots/x86_64-osx/lts-6.4/ghcjs-0.2.0_ghc-7.10.3/pkgdb/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)
```

It doesn't seem to effect the workings of haskell-mode in the file I'm editing.

The messages buffer doesn't reveal anything strange. It shows a Save ... Write ... message for the file I would expect.

This may not be a spacemacs issue at all, but I'm unaware of how to debug this.

thanks

#### Reproduction guide
- Start Emacs
- Save a file

*Observed behaviour:*

A buffer pops up alongside with the above trace.

*Expected behaviour:*

This buffer should not pop up

#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp gtags markdown org git ruby python ipython-notebook syntax-checking scala elm haskell rust)
```

#### Backtrace
```
.stack/snapshots/x86_64-osx/lts-6.4/ghcjs-0.2.0_ghc-7.10.3/pkgdb/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (Not a valid Unicode code point!)
```

**Comment by TheBB** [comment]
Try disabling packages until it doesn't happen, then ask there.

**Comment by TheBB** [comment]
Start with ghc-mod I guess.
