### ISSUE TITLE
Autoinstalling a new layer resets `powerline-default-separator`

### ISSUE THREAD

**Issue by mineo** [syl20bnr/spacemacs#7773]
#### Description :octocat:
Autoinstalling a new layer resets `powerline-default-separator`.

#### Reproduction guide :beetle:
- Start Emacs with `(setq powerline-default-separator nil)` in `dotspacemacs/user-config`
- `SPC f J`
- use a file extension for which the appropriate mode is not installed
- agree to installing it

*Observed behaviour:* :eyes: :broken_heart:
- `powerline-default-separator` is reset to `wave`
- `spaceline-compile` is called at some point and the `wave` separator is used

*Expected behaviour:* :heart: :smile:
- `powerline-default-separator` is not touched

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql markdown helm emacs-lisp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by mineo** [comment]
@TheBB I'm not exactly sure what it means for an issue to be flagged "To be reproduced" for 11 days (after all, it could just mean everyone's to busy with other thing, for which I don't blame anyone :-) ), but if you're having trouble reproducing this, please let me know. I'm seeing this on my Linux machine at home and (I'm pretty sure, but would need to test again) macOS at work.

**Comment by mineo** [comment]
This still happens.

**Comment by duianto** [comment]
Confirmed.

<details><summary>
PopOS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d17c6e1e9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html auto-completion command-log emacs-lisp git helm markdown multiple-cursors
      (org :variables org-agenda-files
           '("~/org/notes.org"))
      pdf
      (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 710aa947b)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(html autohotkey auto-completion c-c++ command-log emacs-lisp git github
      (gnus :variables gnus-summary-thread-gathering-function 'gnus-gather-threads-by-subject)
      go helm imenu-list javascript
      (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
      multiple-cursors org pdf python racket
      (shell :variables shell-default-shell 'shell shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

</pre>
</details>

**Comment by duianto** [comment]
The `powerline-default-separator` is assigned here:
https://github.com/syl20bnr/spacemacs/blob/710aa947b7760dc69f864ca6cd1b2b382780005e/layers/%2Bspacemacs/spacemacs-modeline/packages.el#L105

in the function: `spacemacs-modeline/init-spaceline`

I don't know how/where it's loading when a layer is installed.
And I don't know how to check if the user has assigned another value to the variable.

Currently if the `dotspacemacs-mode-line-theme` is set to `spacemacs`, then the separator is retrieved from the themes definition in `.spacemacs`.
ex: `dotspacemacs-mode-line-theme '(spacemacs :separator wave :separator-scale 1.5)`

That might be the recommended place for defining the separators.
