### ISSUE TITLE
org-ref package needs to be updated?

### ISSUE THREAD

**Issue by wadkar** [syl20bnr/spacemacs#7778]
#### Description :octocat:
Starting spacemacs and updating packages show following error

```
Error (use-package): org post-:config hook: Unknown keyword: :export-block
```
When I searched for this issue I found that a PR on the `org-ref` repo is already [closed](https://github.com/jkitchin/org-ref/pull/110).
I am not sure why spacemacs does not pick the updated package.

#### Reproduction guide :beetle:
- Start Emacs
- Update spacemacs and packages to make sure we have latest build
- Sync spacemacs configuration using `SPC f e R`

*Observed behaviour:* :eyes: :broken_heart:
A `*Warnings*` window opens with following error:

```
Error (use-package): org post-:config hook: Unknown keyword: :export-block
```

*Expected behaviour:* :heart: :smile:
Spacemacs should start without any errors

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml ruby html
      (auto-completion :variables auto-completion-complete-with-key-sequence "jk" auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t)
      better-defaults emacs-lisp git markdown pdf-tools
      (org :variables org-enable-github-support t org-enable-reveal-js-support t)
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking osx tmux
      (latex :variables latex-enable-folding t)
      bibtex
      (version-control :variables version-control-diff-tool 'git-gutter  version-control-global-margin t)
      (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by istinspring** [comment]
look here https://github.com/syl20bnr/spacemacs/issues/7641
