### ISSUE TITLE
golden-ratio-mode breaks eyebrowse when using multiple windows

### ISSUE THREAD

**Issue by topher200** [syl20bnr/spacemacs#7779]
#### Description :octocat:
Creating or moving to a eyebrowse workspace with a complex window arrangement while in golden-ratio-mode results in error.

Turning off golden-ratio-mode removes the error.

Observed on master and develop.

#### Reproduction guide :beetle:
- Start Emacs
- `C-x b sc Enter` Navigate to \*scratch\* buffer
- `Space t g` Turn on golden-ratio-mode
- `Space w v` Split the window vertically
- `Space w h` Split the window horizontally
- `Space w v` Split the window vertically one more time
- :white_check_mark: There should be four window
- `C-c C-w C-c` Attempt to create a new workspace

*Observed behaviour:* :eyes: :broken_heart:
The new workspace is created!

However, we stay in our original workspace. One of the windows has disappeared from our original workspace; we now have three buffers.

This error appears in the status bar:
`window--state-put-1: Cannot resize window #<window 3 on  *temp*>`

*Expected behaviour:* :heart: :smile:
The new workspace is created. We move to the new workspace. Our original workspace is unmodified.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. fea919c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sql auto-completion emacs-lisp
     (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
     (git :variables git-gutter-use-fringe t)
     go helm html javascript markdown python shell
     (syntax-checking :variables syntax-checking-enable-tooltips nil)
     topher yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by TheBB** [comment]
Should probably report this to either golden-ratio or eyebrowse.

**Comment by TheBB** [comment]
> ￼ There should be four buffers

Four *windows*

**Comment by topher200** [comment]
Submitted upstream to eyebrowse bug tracker: https://github.com/wasamasa/eyebrowse/issues/56

I replaced all incorrect instances of "buffer" with "window" in the original description, per TheBB

**Comment by topher200** [comment]
Issue filed with eyebrowse: https://github.com/wasamasa/eyebrowse/issues/56

The eyebrowse dev has repro'd the issue and released an update, but he and I both agree that his update does not solve the issue.

Filed an issue with golden-ratio-mode here: https://github.com/roman/golden-ratio.el/issues/72

**Comment by ChrisSalisbury** [comment]
In case anyone else is having this problem, this pull request seems to solve the problem for me:  https://github.com/roman/golden-ratio.el/pull/66

I have only tested in two workspaces that I am using right now so far, so caveat emptor.

**Comment by Bad-ptr** [comment]
Did anyone try to disable `golden-ratio-mode' in the `eyebrowse-pre-window-switch-hook` and then reenable it in the `eyebrowse-post-window-switch-hook` ?

**Comment by duianto** [comment]
The `eyebrowse-pre-window-switch-hook` doesn't contain: `golden-ratio-mode`
Either before or after the reproduction steps above.

>eyebrowse-pre-window-switch-hook is a variable defined in ‘eyebrowse.el’.
Its value is (deactivate-mark)
Original value was nil

@Bad-ptr 

The `eyebrowse-post-window-switch-hook` looks like this by default on the Spacemacs `develop` branch:
>eyebrowse-post-window-switch-hook is a variable defined in ‘eyebrowse.el’.
Its value is (spacemacs/save-eyebrowse-for-perspective)
Original value was nil

#### The issue still occurs when (restarted Spacemacs between each test):
- Just adding `golden-ratio-mode` to the eyebrowse pre hook:
```elisp
(add-to-list 'eyebrowse-pre-window-switch-hook 'golden-ratio-mode)
```
>eyebrowse-pre-window-switch-hook is a variable defined in ‘eyebrowse.el’.
Its value is (golden-ratio-mode deactivate-mark)
Original value was nil

- Just adding `golden-ratio-mode` to the eyebrowse post hook:
```elisp
(add-to-list 'eyebrowse-post-window-switch-hook 'golden-ratio-mode)
```
>eyebrowse-post-window-switch-hook is a variable defined in ‘eyebrowse.el’.
Its value is
(golden-ratio-mode spacemacs/save-eyebrowse-for-perspective)
Original value was nil

- Adding `golden-ratio-mode` to both the eyebrowse pre and post hooks.

- Just removing `spacemacs/save-eyebrowse-for-perspective`  from the eyebrowse post hook:
```elisp
(setq eyebrowse-post-window-switch-hook (delete 'spacemacs/save-eyebrowse-for-perspective eyebrowse-post-window-switch-hook))
```
>eyebrowse-post-window-switch-hook is a variable defined in ‘eyebrowse.el’.
Its value is nil

- Removing the `spacemacs/save-eyebrowse-for-perspective` function and adding `golden-ratio-mode` to the eyebrowse post hook:
>eyebrowse-post-window-switch-hook is a variable defined in ‘eyebrowse.el’.
Its value is (golden-ratio-mode)
Original value was nil

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. f578e618a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey auto-completion command-log emacs-lisp git github helm imenu-list
            (markdown :variables markdown-live-preview-engine 'vmd markdown-command "vmd")
            multiple-cursors org ranger
            (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2
</pre>
</details>

**Comment by Bad-ptr** [comment]
In my mind the correct way to do this:
```elisp
(add-to-list 'eyebrowse-pre-window-switch-hook 'golden-ratio-mode)
(add-to-list 'eyebrowse-post-window-switch-hook 'golden-ratio-mode)
```
will be:
```elisp
(add-hook 'eyebrowse-pre-window-switch-hook  #'(lambda () (golden-ratio-mode -1)))
(add-hook 'eyebrowse-post-window-switch-hook #'(lambda () (golden-ratio-mode nil)))
```

**Comment by duianto** [comment]
`*facepalm*` of course.
Yeah that seems to work, there's no error message when adding those hooks.

**Comment by duianto** [comment]
After testing it some more, those hooks enable `golden-ratio-mode` again when switching eyebrowse config, if it was disabled in another eyebrowse config.

I added a variable to restore the golden ratio state pre eyebrowse config switch.
And created two functions that are added to the hooks. That makes it easier to read what the hooks do, and it also makes it possible to remove the hooks by name:
```elisp
      (defvar spacemacs/golden-ratio-enabled-pre-eyebrowse-switch nil)
      (defun spacemacs/disable-golden-ratio-pre-eyebrowse-switch ()
          "Disable golden-ratio-mode before switching eyebrowse config.
Save the pre switch golden-ratio-mode state to the variable:
`spacemacs/golden-ratio-enabled-pre-eyebrowse-switch'"
        (setq spacemacs/golden-ratio-enabled-pre-eyebrowse-switch
              golden-ratio-mode)
        (golden-ratio-mode -1))
      (defun spacemacs/maybe-enable-golden-ratio-post-eyebrowse-switch ()
          "Enable golden-ratio-mode if it was enabled before switching
eyebrowse config."
          (when spacemacs/golden-ratio-enabled-pre-eyebrowse-switch
            (golden-ratio-mode t)))
      (add-hook 'eyebrowse-pre-window-switch-hook
                'spacemacs/disable-golden-ratio-pre-eyebrowse-switch)
      (add-hook 'eyebrowse-post-window-switch-hook
                'spacemacs/maybe-enable-golden-ratio-post-eyebrowse-switch)
```
