### ISSUE TITLE
fish users get a warning message about PATH being set for allegedly non-interactive shells

### ISSUE THREAD

**Issue by lvh** [syl20bnr/spacemacs#7780]
#### Description :octocat:

If user's default shell is fish, Emacs appears to run the shell in a way that makes it think it is interactive; in particular, `status --is-interactive` will return true. This results in the following error message:

```
You appear to be setting environment variables ("PATH") in your .bashrc or .zshrc: those files are only read by interactive shells, so you should instead set environment variables in startup files like .profile, .bash_profile or .zshenv.  Refer to your shell’s man page for more info.  Customize ‘exec-path-from-shell-arguments’ to remove "-i" when done, or disable ‘exec-path-from-shell-check-startup-files’ to disable this message.
```

fish doesn't distinguish between interactive and non-interactive shells via different files. In my shell, `PATH` is configured via the usual `set -gx`. Meanwhile, my fish config has stuff like:

```
function interactive_setup
  . (pyenv init -|psub);
  . (rbenv init -|psub);
  . (pyenv virtualenv-init -|psub);

  eval (thefuck --alias | tr '\n' ';')

  . /usr/local/share/autojump/autojump.fish
end

status --is-interactive; and interactive_setup
```

According to the order of messages in `*Messages*`, I think auto-layer might be the thing creating a shell.

#### Reproduction guide :beetle:

- Start Emacs with fish shell as described above
- See error in minibuffer 

*Observed behaviour:* :eyes: :broken_heart:

Above error message in minibuffer.

According to the order of messages in `*Messages*`, I think auto-layer might be the thing creating a shell.

*Expected behaviour:* :heart: :smile:

No error message; ideally because fish correctly does not set the env vars the message is complaining about.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.4
- Spacemacs branch: master (rev. 6feb70d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(shell-scripts helm auto-completion better-defaults emacs-lisp git github markdown org
               (shell :variables shell-default-height 30 shell-default-position 'bottom)
               spell-checking syntax-checking version-control clojure go python sql osx dash ansible evil-cleverparens)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by TheBB** [comment]
https://github.com/purcell/exec-path-from-shell
