### ISSUE TITLE
helm-persp-switch-project errors out the first time a project is chosen

### ISSUE THREAD

**Issue by edran** [syl20bnr/spacemacs#7782]
#### Description :octocat:

Creating a new layout by project results in an error `Symbol's function
definition is void: alist-get`. Moreover, a layout is created, but the previous
buffer remains open (as helm doesn't even start).
If `spacemacs/helm-persp-switch-project` is run again on the same project,
then it seems to correctly allow you to open a file.

#### Reproduction guide :beetle:
- Start emacs
- `SPC p l`
- Choose a project
- `SPC p l`
- Choose the same project

*Observed behaviour:* :eyes: :broken_heart:
Emacs echoes `Symbol's function definition is void: alist-get (the first time).
Helm starts fine the second time.

*Expected behaviour:* :heart: :smile:
Helm allows you to choose project and file, and opens the chosen buffers.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. fea919c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp)
```

#### Backtrace :paw_prints:
```
```

**Comment by wigust** [comment]
#### Description
I have the same issue with 664ba6a

#### Reproduction guide
- Start emacs
- M-m l 2

#### Error
Symbol's function definition is void: alist-get

**Comment by bmag** [comment]
`alist-get` is only available in Emacs 25.1. Please include a backtrace so we know where the comes from.

**Comment by bmag** [comment]
Nevermind, reported upstream: https://github.com/Bad-ptr/persp-mode.el/issues/62

**Comment by bmag** [comment]
Closing this one as fixed upstream. Please reopen or comment if you still encounter errors.
