### ISSUE TITLE
'f' key broken inside vim/less running inside (ansi-/multi-)term

### ISSUE THREAD

**Issue by jackkamm** [syl20bnr/spacemacs#7783]
#### Description :octocat:
'f' key broken inside vim/less running inside (ansi-/multi-)term

#### Reproduction guide :beetle:
- Start Emacs
- Start term/ansi-term/multi-term (e.g., M-x multi-term)
- Start vim inside the term
- Enter insert mode and type the letter 'f'

*Observed behaviour:* :eyes: :broken_heart:
The string 'f^?f' is inserted.

*Expected behaviour:* :heart: :smile:
The letter 'f' should be inserted

#### Other notes:
- Also happens in less (i.e., if searching for the letter 'f' inside less inside multi-term, it will search for the string 'f^?f')
- The 'f' key behaves normally at the usual command prompt (not inside vim or less)
- 'f' key behaves correctly in vanilla emacs -Q
- Reproduced this on two separate OSX computers. Couldn't reproduce it on a Linux computer.
- EDIT to add: BACKSPACE is also broken, vim/less (and possibly other interactive programs) will insert '^?' instead of deleting.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. fea919c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(org helm emacs-lisp auto-completion git github markdown html python ipython-notebook ranger ess shell latex bibtex syntax-checking shell-scripts spell-checking version-control emoji gnus erc twitter my-spacemacs-layer)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by jackkamm** [comment]
My problems appear to be solved by redefining `term-send-backspace` as
```
(defun term-send-backspace  () (interactive) (term-send-raw-string "\C-h"))
```
(by default, it is defined in `term.el` as "\C-?" instead of "\C-h").

This actually might be an upstream problem with emacs -- <backspace> inserts the raw character ^? inside vim inside ansi-term inside emacs-Q. However, inserting f^?f (i.e. inserting f+backspace+f) seems to be unique to spacemacs.

See also: http://stackoverflow.com/a/10197995 about ^? vs ^H for backspace/delete.

**Comment by lzrski** [comment]
I could not get backspace / del to work, but at least I got the `f` key to work properly by following this FAQ: http://spacemacs.org/doc/FAQ.html#typing-quickly-fd-takes-me-out-of-insert-state-what-is-going-on, i.e. having something like that in my .spacemacs file:

```emacs-lisp
(defun dotspacemacs/layers ()
  (setq-default
   ;; ...
   dotspacemacs-excluded-packages '(evil-escape)
   ;; ...
))
```

Sorry for late comment. Hopefully it will help someone.
