### ISSUE TITLE
go-layer broken auto-completion for external go packages

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#7784]
#### Description
 `go install` is needed for `gocode` to get suggestions about auto-completion, so atom, sublime text and other editors are constantly running this command to make sure that correct auto-completion suggestions are given to user, spacemacs should provide similar option in `go-layer`, currently there is no option.

When sublime text, go-sublime plugin does `go install` when you open a file, and you open the same file in spacemacs, with different code , auto-completion stops working because sublime text is constantly reinstalling packages and spacemacs is sitting there doing nothing and using incorrect go-install done by sublime-text go-sublime plugin so to fight incorrect import paths, there should be an option in go-layer to automatically run `go install` command when user starts to edit a go package.

Go-sublime uses `gocode` and packages are installed in same location, which are shared between sublime text, spacemacs and maybe atom as well , so that's causing a problem.

#### Reproduction guide 

- Delete installed `*.a` files from `$GOPATH/pkg/` and auto-completion in spacemacs for go packages will completely stop working for external packages.

- If import paths are incorrect , gocode will return nothing but `GOCODE PANIC` causing `company-mode` to completely stop working for go files. 

#### Suggested fix

- Go-sublime is doing auto install of packages without asking the user allowing packages to get installed , `go-layer` should provide similar option for installing packages on the fly.

- Installed `*.a` files are very small in size so, running `go install` while editing `*.go` files will not cause performance issues.

**Comment by bmag** [comment]
I don't use Go, but let me just get this straight: if you use Spacemacs alone for writing Go code, everything is fine, but if you also use Sublime Text (with Go plugins?), then Sublime Text updates (via `go-install`) Go packages that Spacemacs depends on and that somehow prevents Spacemacs auto-completion from working?

Pinging @bogdanteleaga as well.

**Comment by dineshbhosale** [comment]
yes exactly !! thanks for taking this issue into consideration, I have temporarily fixed this issue by adding `go install` in my task runner but need a permanent fix by implementing this inside `go-layer`

**Comment by bogdanteleaga** [comment]
So you're saying that Sublime does a go install for the package defined by the file you're editing when you open it?

That can be very slow for large projects.

**Comment by dineshbhosale** [comment]
`GoSublime` and `autocomplete-go` plugins for atom and sublime text are providing this functionality as default behavior . [See FAQ of `autcomplete-go`](https://github.com/joefitzgerald/autocomplete-go#faq)

IMO `go` layer should not implement this feature as default behavior but we can implement a layer variable 

for example : 

```
(go :variables run-go-install-on-save t)
```

Personally, I have not experienced any performance issues while editing large files, golang itself is very fast.

**Comment by dineshbhosale** [comment]
`Gocode` doesn't parse raw source files and packages have to be compiled into binaries before any auto-completion suggestion is given by `gocode`, this can be considered a flaw in `gocode` itself so currently we have no other option other than running `go install ./..` manually, refer to this issue : https://github.com/nsf/gocode/issues/404 

I wish someone will create a separate plugin for emacs to run `go install ./..` on file save.

**Comment by syl20bnr** [comment]
> IMO go layer should not implement this feature as default behavior but we can implement a layer variable
for example :
    (go :variables run-go-install-on-save t)

Yes would be handy to have this.

**Comment by tlightsky** [comment]
can i use this config now: 
`(go :variables run-go-install-on-save t)`
