### ISSUE TITLE
Clojure layer not providing `C-j` and `C-k` keybindings in Cider REPL

### ISSUE THREAD

**Issue by Kasuko** [syl20bnr/spacemacs#7785]
#### Description :octocat:
Clojure layer attempts to provide `C-j` and `C-k` keybindings in the Cider REPL

#### Reproduction guide :beetle:
- Start Emacs
- Install `clojure` layer
- `M-x cider-jack-in`
- `SPC h d k C-j`
- Notice it is not bound to `cider-repl-next-input`

*Observed behaviour:* :eyes: :broken_heart:
What's happening is `cider-repl-next-input` is bound to the prefix `C-` and then the hotkey `j`

*Expected behaviour:* :heart: :smile:
When on a cider-repl buffer `C-j` and `C-k` should cycle through the history of commands

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-return-key-behavior nil auto-completion-tab-key-behavior 'complete)
 better-defaults emacs-lisp osx git version-control markdown org
 (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/bin/zsh" shell-default-height 30 shell-default-position 'bottom)
 evil-cleverparens clojure yaml html javascript sql docker)
```

**Comment by infracanophile** [comment]
I'm using it with both normal and insert mode. The complete-from-history-that-matches-what-you-typed-so-far functionality is great.

Might consider making that change as well.

**Comment by kommen** [comment]
`cider-repl-next-input` and `cider-repl-previous-input` are bound to `C-j` and `C-k` now in normal mode. https://github.com/syl20bnr/spacemacs/blob/64cf9f56f6d380c162158a5f68d077cd2e72aa3a/layers/%2Blang/clojure/packages.el#L214-L216

In insert mode, they are bound to `M-n` and `M-p`. While not consistent, they are provided now so I think this can be closed?
