### ISSUE TITLE
Is there a plugin/layer in spacemacs equivalent to tagbar?

### ISSUE THREAD

**Issue by lijingjiang** [syl20bnr/spacemacs#7787]
Hi, all

It would be great if there is some plugin like [tagbar for vim](https://github.com/majutsushi/tagbar). I have tried the `imenu-list` layer before, but seems like it can only simulate very limited functionality in tagbar.

Thank you very much.

**Comment by bmag** [comment]
Can you explain what is missing? Seems to me that the only difference is that tagbar uses `ctags`, while imenu-list uses Emacs' `imenu` feature.

**Comment by lijingjiang** [comment]
Sure, I would love to. For example, I use spacemacs and my vim to open the same cpp file

The following screenshot is using the `imenu-list`

<img width="1610" alt="screen shot 2016-11-18 at 2 35 04 pm" src="https://cloud.githubusercontent.com/assets/8180212/20445995/16983a84-ad9d-11e6-8886-40b5690071b9.png">

The following screenshot is using the `tagbar`

<img width="1920" alt="screen shot 2016-11-18 at 2 36 32 pm" src="https://cloud.githubusercontent.com/assets/8180212/20445999/1f91d53c-ad9d-11e6-9c60-6c9f23fd586b.png">

`imenu-list` is good enough in most cases (Thank you @bmag for creating this awesome plugin! ), but `ctags` can provide more detailed information.

Thank you!

**Comment by bmag** [comment]
Imenu-list uses `imenu`, `imenu` can be configured to use different backends depending on the buffer. If you can find a package that provides Ctags support for Emacs and configures `imenu` to use Ctags, then we can probably include it in a layer. Emacs has support for Etags ("Emacs Tags"), that just might be able to read Ctags' index, but I didn't find any info about Etags+`imenu` integration.

On the other hand, if you're willing to use GNU Global, then you can install the `gtags` layer. It includes the `ggtags` package that implements a gtags-powered backend for `imenu`. It's disabled by default, so you'll have to configure it in `user-config` according to the [upstream instructions](https://github.com/leoliu/ggtags#integration-with-other-packages):
```elisp
(defun enable-gtags-imenu ()
  (setq-local imenu-create-index-function #'ggtags-build-imenu-index))
;; replace `c-mode-hook' with the hook of whatever major-mode you prefer
;; you can have multiple `add-hook's of course
(add-hook 'c-mode-hook #'enable-gtags-imenu)
```

**Comment by lijingjiang** [comment]
Thank you for your reply, it looks cool! Still looking forward some layer that can integrate with `ctags` directly.

Feel free to close this issue if needed.
