### ISSUE TITLE
Is there functionality to enable relative and normal line numbers?

### ISSUE THREAD

**Issue by chrissound** [syl20bnr/spacemacs#7788]
I'm looking for functionality to display two columns for the line numbers. One for the actual line number and the other for the relative line number. 

Is there any layer that provides the above? If not, any suggestions for how to achieve the above? Bear in mind I'm a newcomer to spacemacs and lisp - but willing to learn.

**Comment by jupl** [comment]
I don't know about two columns, but I use the option`dotspacemacs-line-numbers` and set that to `'relative` so that all the line numbers are relative, except the line where the cursor is at where that line number is non-relative.

**Comment by chrissound** [comment]
Closing. I don't think this functionality exists natively. If anyone has some code for this though please post it. :)
