### ISSUE TITLE
org-agenda-redo fails

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#7795]
#### Description :octocat:
org-agenda-redo fails to refresh agenda view (error msg see below)

#### Reproduction guide :beetle:
- Start Emacs
- Open Agenda view
- Press g and r

*Observed behaviour:* :eyes: :broken_heart:
Agenda disappears

*Expected behaviour:* :heart: :smile:
Agenda refresh

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 9acfcf3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" auto-completion-enable-help-tooltip nil)
 bibtex c-c   clojure colors csv custom-org-config docker emacs-lisp elixir erc erlang ess games
 (git :variables git-gutter-use-fringe t)
 github gnus graphviz html ipython-notebook latex lua markdown
 (org :variables org-enable-reveal-js-support t)
 pandoc pdf-tools plantuml
 (python :variables python-enable-yapf-format-on-save nil python-auto-set-local-pyenv-version 'on-project-switch python-test-runner 'pytest)
 python-config ranger research-config search-engine semantic
 (shell :variables shell-default-shell 'term shell-default-term-shell "/bin/zsh")
 speed-reading spell-checking syntax-checking tmux version-control yaml)
```

Debugger entered--Lisp error: (wrong-type-argument keymapp nil)
  copy-keymap(nil)
  (set (make-local-variable (quote evilified-state--normal-state-map)) (copy-keymap evil-normal-state-map))
  (if evilified-state--normal-state-map nil (set (make-local-variable (quote evilified-state--normal-state-map)) (copy-keymap evil-normal-state-map)))
  evilified-state--setup-normal-state-keymap()
  evilified-state--evilified-state-on-entry()
  run-hooks(evil-evilified-state-entry-hook)
  (let ((evil-state (quote evilified))) (evil-normalize-keymaps) (if (quote nil) (activate-input-method evil-input-method) (if deactivate-current-input-method-function (deactivate-input-method))) (if evil-no-display nil (evil-refresh-cursor (quote evilified)) (evil-refresh-mode-line (quote evilified)) (if (called-interactively-p (quote any)) (progn (redisplay)))) (run-hooks (quote evil-evilified-state-entry-hook)) (if (and evil-echo-state arg (not evil-no-display) evil-evilified-state-message) (progn (if (functionp evil-evilified-state-message) (funcall evil-evilified-state-message) (evil-echo "%s" evil-evilified-state-message)))))
  (let ((evil-next-state (quote evilified)) input-method-activate-hook input-method-deactivate-hook) (evil-change-state nil) (setq evil-state (quote evilified)) (evil-add-to-alist (quote evil-previous-state-alist) (quote evilified) evil-previous-state) (let ((evil-state (quote evilified))) (evil-normalize-keymaps) (if (quote nil) (activate-input-method evil-input-method) (if deactivate-current-input-method-function (deactivate-input-method))) (if evil-no-display nil (evil-refresh-cursor (quote evilified)) (evil-refresh-mode-line (quote evilified)) (if (called-interactively-p (quote any)) (progn (redisplay)))) (run-hooks (quote evil-evilified-state-entry-hook)) (if (and evil-echo-state arg (not evil-no-display) evil-evilified-state-message) (progn (if (functionp evil-evilified-state-message) (funcall evil-evilified-state-message) (evil-echo "%s" evil-evilified-state-message))))))
  (cond ((and (numberp arg) (< arg 1)) (setq evil-previous-state evil-state evil-state nil) (let ((evil-state (quote evilified))) (run-hooks (quote evil-evilified-state-exit-hook)) (setq evil-state nil) (evil-normalize-keymaps))) (t (if evil-local-mode nil (evil-local-mode 1)) (let ((evil-next-state (quote evilified)) input-method-activate-hook input-method-deactivate-hook) (evil-change-state nil) (setq evil-state (quote evilified)) (evil-add-to-alist (quote evil-previous-state-alist) (quote evilified) evil-previous-state) (let ((evil-state (quote evilified))) (evil-normalize-keymaps) (if (quote nil) (activate-input-method evil-input-method) (if deactivate-current-input-method-function (deactivate-input-method))) (if evil-no-display nil (evil-refresh-cursor (quote evilified)) (evil-refresh-mode-line (quote evilified)) (if (called-interactively-p (quote any)) (progn (redisplay)))) (run-hooks (quote evil-evilified-state-entry-hook)) (if (and evil-echo-state arg (not evil-no-display) evil-evilified-state-message) (progn (if (functionp evil-evilified-state-message) (funcall evil-evilified-state-message) (evil-echo "%s" evil-evilified-state-message))))))))
  evil-evilified-state(nil)
  evil-change-state(evilified nil)
  evil-change-to-initial-state(nil)
  evil-initialize-state()
  evil-local-mode(1)
  evil-initialize()
  evil-mode-enable-in-buffers()
  run-hooks(after-change-major-mode-hook)
  run-mode-hooks(org-agenda-mode-hook)
  apply(run-mode-hooks org-agenda-mode-hook)
  org-agenda-mode()
  org-agenda-prepare("Agenda")
  (let nil (org-agenda-prepare name))
  eval((let nil (org-agenda-prepare name)))
  org-let(nil (org-agenda-prepare name))
  org-agenda-run-series("Agenda" (((agenda "" nil) (tags "REFILE" ((org-agenda-overriding-header "Tasks to Refile") (org-tags-match-list-sublevels nil))) (tags-todo "-CANCELLED/!" ((org-agenda-overriding-header "Stuck Projects") (org-agenda-skip-function (quote bh/skip-non-stuck-projects)) (org-agenda-sorting-strategy (quote (category-keep))))) (tags-todo "-HOLD-CANCELLED/!" ((org-agenda-overriding-header "Projects") (org-agenda-skip-function (quote bh/skip-non-projects)) (org-tags-match-list-sublevels (quote indented)) (org-agenda-sorting-strategy (quote (category-keep))))) (tags-todo "-CANCELLED/!NEXT" ((org-agenda-overriding-header (concat "Project Next Tasks" (if bh/hide-scheduled-and-waiting-next-tasks "" " (including WAITING and SCHEDULED tasks)"))) (org-agenda-skip-function (quote bh/skip-projects-and-habits-and-single-tasks)) (org-tags-match-list-sublevels t) (org-agenda-todo-ignore-scheduled bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-deadlines bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-with-date bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-sorting-strategy (quote (todo-state-down effort-up category-keep))))) (tags-todo "-REFILE-CANCELLED-WAITING-HOLD/!" ((org-agenda-overriding-header (concat "Project Subtasks" (if bh/hide-scheduled-and-waiting-next-tasks "" " (including WAITING and SCHEDULED tasks)"))) (org-agenda-skip-function (quote bh/skip-non-project-tasks)) (org-agenda-todo-ignore-scheduled bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-deadlines bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-with-date bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-sorting-strategy (quote (category-keep))))) (tags-todo "-REFILE-CANCELLED-WAITING-HOLD/!" ((org-agenda-overriding-header (concat "Standalone Tasks" (if bh/hide-scheduled-and-waiting-next-tasks "" " (including WAITING and SCHEDULED tasks)"))) (org-agenda-skip-function (quote bh/skip-project-tasks)) (org-agenda-todo-ignore-scheduled bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-deadlines bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-with-date bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-sorting-strategy (quote (category-keep))))) (tags-todo "-CANCELLED+WAITING|HOLD/!" ((org-agenda-overriding-header (concat "Waiting and Postponed Tasks" (if bh/hide-scheduled-and-waiting-next-tasks "" " (including WAITING and SCHEDULED tasks)"))) (org-agenda-skip-function (quote bh/skip-non-tasks)) (org-tags-match-list-sublevels nil) (org-agenda-todo-ignore-scheduled bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-deadlines bh/hide-scheduled-and-waiting-next-tasks))) (tags "-REFILE/" ((org-agenda-overriding-header "Tasks to Archive") (org-agenda-skip-function (quote bh/skip-non-archivable-tasks)) (org-tags-match-list-sublevels nil)))) nil))
  eval((org-agenda-run-series "Agenda" (quote (((agenda "" nil) (tags "REFILE" ((org-agenda-overriding-header "Tasks to Refile") (org-tags-match-list-sublevels nil))) (tags-todo "-CANCELLED/!" ((org-agenda-overriding-header "Stuck Projects") (org-agenda-skip-function (quote bh/skip-non-stuck-projects)) (org-agenda-sorting-strategy (quote ...)))) (tags-todo "-HOLD-CANCELLED/!" ((org-agenda-overriding-header "Projects") (org-agenda-skip-function (quote bh/skip-non-projects)) (org-tags-match-list-sublevels (quote indented)) (org-agenda-sorting-strategy (quote ...)))) (tags-todo "-CANCELLED/!NEXT" ((org-agenda-overriding-header (concat "Project Next Tasks" ...)) (org-agenda-skip-function (quote bh/skip-projects-and-habits-and-single-tasks)) (org-tags-match-list-sublevels t) (org-agenda-todo-ignore-scheduled bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-deadlines bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-with-date bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-sorting-strategy (quote ...)))) (tags-todo "-REFILE-CANCELLED-WAITING-HOLD/!" ((org-agenda-overriding-header (concat "Project Subtasks" ...)) (org-agenda-skip-function (quote bh/skip-non-project-tasks)) (org-agenda-todo-ignore-scheduled bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-deadlines bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-with-date bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-sorting-strategy (quote ...)))) (tags-todo "-REFILE-CANCELLED-WAITING-HOLD/!" ((org-agenda-overriding-header (concat "Standalone Tasks" ...)) (org-agenda-skip-function (quote bh/skip-project-tasks)) (org-agenda-todo-ignore-scheduled bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-deadlines bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-with-date bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-sorting-strategy (quote ...)))) (tags-todo "-CANCELLED+WAITING|HOLD/!" ((org-agenda-overriding-header (concat "Waiting and Postponed Tasks" ...)) (org-agenda-skip-function (quote bh/skip-non-tasks)) (org-tags-match-list-sublevels nil) (org-agenda-todo-ignore-scheduled bh/hide-scheduled-and-waiting-next-tasks) (org-agenda-todo-ignore-deadlines bh/hide-scheduled-and-waiting-next-tasks))) (tags "-REFILE/" ((org-agenda-overriding-header "Tasks to Archive") (org-agenda-skip-function (quote bh/skip-non-archivable-tasks)) (org-tags-match-list-sublevels nil)))) nil))))
  org-agenda-redo(nil)
  call-interactively(org-agenda-redo nil nil)
  command-execute(org-agenda-redo)

**Comment by nixmaniack** [comment]
Related: https://github.com/syl20bnr/spacemacs/issues/7791

**Comment by syl20bnr** [comment]
I reverted the offending commit, thanks for the report.
