### ISSUE TITLE
Disable rainbow delimiter changing color automatically.

### ISSUE THREAD

**Issue by lijingjiang** [syl20bnr/spacemacs#7801]
Hi, all

I really love the `rainbow delimiter` plugin, but there is one thing really confused me. For example, the following is my customized rainbow delimiter color scheme. 

When the cursor is outside of the parenthesis region. It looks like this

<img width="943" alt="screen shot 2016-11-21 at 9 29 01 pm" src="https://cloud.githubusercontent.com/assets/8180212/20509885/8de42e22-b031-11e6-95e6-55a8cf21c2bb.png">

But when I put my cursor inside the parenthesis region, it looks like this 

<img width="937" alt="screen shot 2016-11-21 at 9 30 27 pm" src="https://cloud.githubusercontent.com/assets/8180212/20509895/c0e4389e-b031-11e6-8ed6-3dacb369262d.png">

Some parenthesis has been embolden, which looks pretty cool! But the color of the parenthesis has been changed which makes the hierarchy not very intuitive under my emacs theme. So is there any way that I can only embolden the parenthesis, but leave the color as before.

I have made a thorough search on [github](https://github.com/Fanael/rainbow-delimiters) and the setting manual through: `M-x` -> `customize-group` -> `rainbow-delimiters` but still have no idea how to disable it. Any comment will be deeply appreciated.

Thank you very much, wish you guys have a great Thanksgiving!

**Comment by lijingjiang** [comment]
Solved, never mind :)

**Comment by xXQWERTXx** [comment]
May I ask how? I'm struggling with the same issue myself

**Comment by xXQWERTXx** [comment]
Solved: `SPC SPC customize-group RET highlight-parentheses RET`
Then, delete values from `Hl Paren Colors`
