### ISSUE TITLE
Discussion: Emacs java-mode: malabar, jdee, or eclim?

### ISSUE THREAD

**Issue by zhexuany** [syl20bnr/spacemacs#7806]
I am not into current `java`'s implementation. It is supper slow in my computer even it has 8G Ram and 2.7Ghz CPU. The speed of completion is the only reason I use `intellij` for wrting `java` code. Here I propose two alternative chioce for `eclim`.

Any opinions are welcome.  

http://stackoverflow.com/questions/4654725/emacs-java-mode-malabar-jdee-or-eclim

https://www.emacswiki.org/emacs/MalabarMode

https://github.com/jdee-emacs/jdee

**Comment by mahinshaw** [comment]
This is also a good option => https://github.com/mopemope/meghanada-emacs
I've used it a little, and found it to be easy to use.

**Comment by zhexuany** [comment]
@mahinshaw This mode looks really nice. @syl20bnr Do you mind if I migrate current eclim to meghanada?

**Comment by hicksy994** [comment]
+1 On the performance problems. 

I also have a reasonably high end system but eclim is painfully slow.

**Comment by syl20bnr** [comment]
@zhexuany you can create a new layer `java-meghanada`, once it is mature enough we could consider migrating to the java layer 👍

**Comment by hicksy994** [comment]
@mahinshaw Would you mind sharing how you have meghanada set up?

For me when I run the server it all looks good, my project gets found etc but autocompletion and jump to definition fails.

Thanks

**Comment by mahinshaw** [comment]
In the `.spacemacs` config:

```
   dotspacemacs-additional-packages '(meghanada groovy-mode gradle-mode)
```

And then to wire together to modes:
```
  (require 'meghanada)
  (add-hook 'java-mode-hook
             (lambda ()
               (meghanada-mode t)
               (gradle-mode t)
               (add-hook 'before-save-hook 'delete-trailing-whitespace)))
  (add-hook 'groovy-mode-hook
            (lambda ()
              (gradle-mode t)))
```

`groovy-mode` and `gradle-mode` were there for gradle, and are not necessary.

With regards to the autocompletion and jumping, I had to make sure the project got built before either of those would work.

**Comment by zhexuany** [comment]
@syl20bnr Nice. I would like contribute my time on this `java-meghanada`.

**Comment by hicksy994** [comment]
@mahinshaw Thanks for your reply, but my project builds fine yet autocomplete and jump still do not work. :(

**Comment by zhexuany** [comment]
@hicksy994 
~~~
  (require 'meghanada)
  (add-hook 'java-mode-hook
             (lambda ()
               (meghanada-mode t)
               (gradle-mode t)
               (add-hook 'before-save-hook 'delete-trailing-whitespace)))
  (add-hook 'groovy-mode-hook
            (lambda ()
              (gradle-mode t)))
~~~
Where do you put this configuration code? I believe this should go to `user-init`.

**Comment by hicksy994** [comment]
@zhexuany I've just been turning on the modes manually,  which shouldn't make a difference...right?

As it doesn't do anything yet I haven't bothered adding it to my config.

**Comment by syl20bnr** [comment]
I'm currently mainly working on the java layer to bring multiple backends support to it based on the PR #7755, the objective is to have support for Eclim, ENSIME, Meghanada and JDEE and to be able to select on a per project basis which backend to use. I pushed a new branch `java_multi_backends` you can try, for now `Eclim` and `Meghanada` are in a working and tested condition. Check the README of the layer to learn more on how to set the backend for a specific project.
Note that I freely **force push** to this branch so may have to `git reset` if you are testing this branch.

**Comment by zhexuany** [comment]
@syl20bnr  thanks. I will give a try. Actually, I have been worked on this for a while. But obviously, you have much more experience than me. So, I will discard any changes I made and give your version a try.

**Comment by zhexuany** [comment]
Comparing give it a try, I am more interested in the changes you made. Creating a PR seems pretty good. How could a PR can hurt this project, right?

**Comment by syl20bnr** [comment]
I gave up on JDEE since it seems pretty complicated to integrate it with Spacemacs. Meghanada and Eclim are usable but I did not test Ensime.

**Comment by syl20bnr** [comment]
I pushed the `java-multi-backend` branch to `develop`, the supported backends are:
- meghanada (tested)
- eclim (tested)
- ensime (requires some tests by people using it, may contain some regression)

I removed the `ensime` layer and `ensime` is part of the `java` layer. So now `scala` depends on the `java` layer which makes sense. Ensime key bindings are setup in `scala` via a `:pre-config` use-package hook.

Meghanada is impressive and works so well and is so seamless (auto-install) that I decided to put it as the default backend.  Try it!

We can keep this issue opened to discuss the regressions and improvements.

**Comment by hedning** [comment]
Got ensime up and running again with no obvious regressions in the spacemacs code.

To test it you'll need to follow the [sbt installation guide](http://ensime.org/build_tools/sbt/#install), adding the `~/.sbt/0.13/global.sbt` bit since spacemacs uses the developer version of ensime.

If `sbt ensimeConfig` fails try `rm -rf ~/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots` and rerun as described [here](https://github.com/ensime/ensime-sbt/issues/276).

Completion annotations are a bit buggy, but that's a problem with upstream (though solvable by overwriting some functions).

**Comment by tutysara** [comment]
wow, have been checking if I have to make a layer for meghanada and found we have it already, spacemacs rocks. thanks @syl20bnr

**Comment by therealpxc** [comment]
Hi guys!

Very new Spacemacs user here (first-time Emacs user, too), wondering what the best way is to get this new layer working for me without having to use the entire develop branch of Spacemacs. Eclim really seems like a pain and I don't want to have to maintain/manage an Eclipse workspace just to get autocompletion, etc. I've played a little bit with Ensime for Scala (I'm new to the language but they use it at my workplace) and I've been very pleased with it. What should I do?

Sorry for the vagueness of this question.

PS: Relatedly, is there a particular timeframe by which we should say this is ready to go into Spacemacs? Can we maybe get a check-in from those in the thread who were using it before as to whether they're still using it (it's been a couple months :-)) and how it's working for them?

**Comment by therealpxc** [comment]
For now I'm just running the new Java layer by using the `develop` branch of Spacemacs. So far using the `develop` branch appears not to have caused an additional issues, and the new Java layer is nice.

I can't seem to access the debug features, though. When I hit `SPC m d` I get a message that `SPC m d` is undefined. Is there some additional thing I need to do to enable those features? I see in the documentation on that branch that those keybindings need a `transient-state`, but I don't know what that means. Is it related?

**Comment by xiaogaozi** [comment]
Have tried Spacemacs with Meghanada, very impressive, thanks you guys hard work. 👏

**Comment by didibus** [comment]
I'm confused, my java layer is still using eclim, how do I get it to use Meghanada?

**Comment by igoralmeida** [comment]
@didibus are you using the master branch?

**Comment by didibus** [comment]
@igoralmeida Yes I am. Oh, I see, the changes havn't reached master yet.
