### ISSUE TITLE
Issue with helm and project switch

### ISSUE THREAD

**Issue by fatlazycat** [syl20bnr/spacemacs#781]
When changing project it all seems to work and but when choosing the file from the project to view I get

![emacs](https://cloud.githubusercontent.com/assets/338975/6552217/6d458fe4-c63b-11e4-9513-a551bb4ecfcc.png)

Any ideas ?

Thanks

**Comment by tuhdo** [comment]
It is being addressed on Projectile side. See this PR: https://github.com/bbatsov/projectile/pull/681

Currently, you should temporary use separate Helm Projectile commands.

**Comment by fatlazycat** [comment]
Thanks, will track that.
