### ISSUE TITLE
`SPC w C` does not restore windows layout

### ISSUE THREAD

**Issue by jlombera** [syl20bnr/spacemacs#7811]
#### Description :octocat:
`SPC w C` does not restore windows layout.  Not sure whether this is the expected behavior.

#### Reproduction guide :beetle:
- Start Emacs
- Create two or more windows
- Center one window full width with `SPC w C`
- Leave centered mode with `SPC w C`

*Observed behaviour:* :eyes: :broken_heart:
Only one window exists after leaving centered mode; i.e. after `SPC w C` is pressed the second time.

*Expected behaviour:* :heart: :smile:
The original windows layout is restored after leaving centered mode.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 96e6de2)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion better-defaults c-c++ cscope emacs-lisp git github
     (go :variables go-tab-width 4)
     html markdown
     (mu4e :variables :packages
           (not mu4e-maildirs-extension))
     org semantic shell spell-checking syntax-checking systemd version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XWIDGETS

**Comment by Compro-Prasad** [comment]
You can do `SPC w u` in that case. `SPC w C` is for toggling `centered-buffer` mode. Undoing a window layout is a totally different operation and a keybinding is giving for the purpose. So, this isn't a bug at all.
