### ISSUE TITLE
Need 'pdb' module while Python Debugger.

### ISSUE THREAD

**Issue by JamesYuan** [syl20bnr/spacemacs#7812]
#### Description :octocat:
Python debuger doesn't work and need module named 'pdb'.

#### Reproduction guide :beetle:
- Start Emacs
- open a python file.
- click Menu -> Python -> Debugger

Current directory is /Users/james/projects/opensources/services/
Traceback (most recent call last):
  File "/usr/local/bin/pdb", line 7, in <module>
    from pdb.pdb import main
ImportError: No module named pdb

Debugger exited abnormally with code 1

I have ensure `which pdb` is in (getenv "PATH"), and 
follow 'http://stackoverflow.com/questions/9167614/python-mode-in-emacs-no-such-file-or-directory-pdb'.

No lucky.

Thanks,
James

*Observed behaviour:* :eyes: :broken_heart:
A *GUD* buffer popup and say "ImportError: No module named pdb".

*Expected behaviour:* :heart: :smile:
The Python Debugger works. thanks.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(asciidoc auto-completion ansible better-defaults colors common-lisp dash deft docker emacs-lisp erc git ibuffer imenu-list markdown org osx ruby ruby-on-rails go javascript python react rust restclient scheme haskell html yaml search-engine shell-scripts sql
          (shell :variables shell-default-height 30 shell-default-position 'bottom)
          smex sml spell-checking syntax-checking vagrant)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

#### Backtrace :paw_prints:
```
Current directory is /Users/james/projects/opensources/services/
Traceback (most recent call last):
  File "/usr/local/bin/pdb", line 7, in <module>
    from pdb.pdb import main
ImportError: No module named pdb

Debugger exited abnormally with code 1
```

**Comment by bmag** [comment]
That looks like an error in pdb itself. Check what happens if you try to run `pdb` from a terminal, or if you open a python interpreter and try to import pdb.

**Comment by marcosmoyano** [comment]
Couldn't reproduce. Worked fine over here.
