### ISSUE TITLE
Move `SPC b m` to kill other buffers to `SPC b C-d` doesn't work

### ISSUE THREAD

**Issue by halfcrazy** [syl20bnr/spacemacs#7814]
#### Description :octocat:
When press SPC b C-d it not call 'spacemacs/kill-other-buffers but 'spacemacs/kill-matching-buffers-rudely

#### Reproduction guide :beetle:
- Start Emacs
- Press SPC b C-d or SPC ? 'spacemacs/kill-other-buffers

*Observed behaviour:* :eyes: :broken_heart:
Call spacemacs/kill-matching-buffers-rudely

*Expected behaviour:* :heart: :smile:
Call spacemacs/kill-other-buffers

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. e699f18)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(php csv windows-scripts
     (auto-completion :variables auto-completion-enable-snippets-in-popup t)
     semantic better-defaults
     (imenu-list :variables imenu-list-size 0.2)
     gtags deft emacs-lisp git
     (colors :variables colors-enable-nyan-cat-progress-bar t)
     (chinese :variables chinese-enable-youdao-dict t)
     markdown osx
     (org :variables org-enable-github-support t)
     syntax-checking version-control
     (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
     (go :variables go-tab-width 4)
     lua python shell html yaml javascript dash ansible docker nginx tmux)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

BTW
It's introduced by [Move `SPC b m` to kill other buffers to `SPC b C-d`](https://github.com/syl20bnr/spacemacs/commit/237b2a73734e988fc8fd4a653bf9deee82d4dda3).

Looks like caused by the following [function](https://github.com/syl20bnr/spacemacs/blob/237b2a73734e988fc8fd4a653bf9deee82d4dda3/layers/%2Bdistributions/spacemacs-base/keybindings.el#L119). May be case insensitive or override i guess.
```
(spacemacs/set-leader-keys
  "TAB"   'spacemacs/alternate-buffer
  "bd"    'spacemacs/kill-this-buffer
  "be"    'spacemacs/safe-erase-buffer
  "bh"    'spacemacs/home
  "b C-d" 'spacemacs/kill-other-buffers
  "b C-D" 'spacemacs/kill-matching-buffers-rudely
  "bn"    'next-buffer
  "bm"    'view-echo-area-messages
  "bN"    'spacemacs/new-empty-buffer
  "bP"    'spacemacs/copy-clipboard-to-whole-buffer
  "bp"    'previous-buffer
  "bR"    'spacemacs/safe-revert-buffer
  "bs"    'spacemacs/switch-to-scratch-buffer
  "bY"    'spacemacs/copy-whole-buffer-to-clipboard
  "bw"    'read-only-mode)
```

**Comment by marienz** [comment]
Same here (Emacs 25.1.1 on Linux/GTK+). `spacemacs/set-leader-keys` uses `kbd`, which returns the same string for `C-d` and `C-D`. So it ends up defining the same keybinding twice, and the last one takes effect.

It looks like the fix is to use `C-S-d` instead of `C-D`.

**Comment by syl20bnr** [comment]
My bad..... thank you for the pointer :-D

**Comment by syl20bnr** [comment]
Fixed with https://github.com/syl20bnr/spacemacs/commit/a1516a6 😄
