### ISSUE TITLE
Make Vim and Emacs keybindings for autocompletion available in both editing styles

### ISSUE THREAD

**Issue by Somelauw** [syl20bnr/spacemacs#7819]
## Problem
Company and Helm use different keybindings for scrolling/cycling. Also the assumption that I want to use Vim keys in company mode is wrong.

### Activate company
For company, start typing the first few letters of a function and wait for the drop down menu to appear.

Company uses TAB or M-n (and S-TAB or M-p) to cycle between completions.
When C-n or C-p is/are pressed, it aborts company.

### Activate helm
For helm, start typing until drop down menu appears. Press ESC, press a, press TAB. A menu "Helm completion at point" shows up.

Helm uses C-n (and C-p) to scroll between completions.
It uses TAB for an arbitrary action.

## Configuration

     (setq-default dotspacemacs-editing-style 'vim)

     (auto-completion :variables
                      auto-completion-return-key-behavior 'complete
                      auto-completion-tab-key-behavior 'cycle
                      auto-completion-complete-with-key-sequence nil
                      auto-completion-complete-with-key-sequence-delay 0.1
                      auto-completion-private-snippets-directory nil
                      auto-completion-enable-snippets-in-popup t)

## Proposed solution
Make C-n and C-p available in company too when using vim style.
This doesn't break functionality, because C-n and C-p aren't defined by company.
Also, these keys already work in pure Vim, so they aren't really Emacs style anyway.

Alternatively, define a variable in the autocompletion layer called auto-completion-completion-style to let me choose between "default", "vim", "emacs". If set to default, it should fall back on dotspacemacs-editing-style otherwise it should use the style specified.

**Comment by syl20bnr** [comment]
But `C-j` and `C-k` should work in company and helm when using the Vim style, this is what is expected in this style, maybe `C-n` or `C-p` work in Vim style because they are the default key bindings for a mode, that's fine but this is not a convention. The convention is `C-j` and `C-k` in Vim style.

**Comment by Somelauw** [comment]
Thanks. I didn't expect these keys, because in raw vim, C-j works like return. If C-j and C-k are the convention in Vim style in Spacemacs, I'll try to get used to this and unlearn the other ones.

**Comment by daren25** [comment]
Having the same problem. I do understand that this is the vim style convention, but I am using hybrid mode. And since I am in insert mode when I use auto-completion I would expect it to at least support the emacs bindings.
