### ISSUE TITLE
Errors in ssh using tramp in Windows10

### ISSUE THREAD

**Issue by winkar** [syl20bnr/spacemacs#7824]
I'm using windows 10  with latest emacs build downloaded from http://emacsbinw64.sourceforge.net/ and tried to make use of tramp to remote access a ubuntu server.

When type  `/ssh:ubuntu:~` in eshell, it took long time without response and turned out with below output:

https://gist.github.com/winkar/cf5e7a050d253e9a368921e960aa5045#file-gistfile1-txt

Can easily know that ssh session had started successfully but prompt was not sent, which kept tramp waiting. When simpily using ssh on eshell, I can add option "-tt" to ssh to make ssh work correctly, but have no idea how to add the same option to tramp ssh command.

I've tried add  `(setq tramp-default-method "sshx")` and `(setq tramp-default-method "plink")` to user-init in dotspacemacs, but output remained unchanged.

It didn't work and output the same in SPC-f-f 

Do anyone have idea?

P.S. I've checked similar issue that is caused by using zsh,  above error output are generated when remote server default shell set to bash.

**Comment by bmag** [comment]
Thank you for the report, have you read this [FAQ entry](http://spacemacs.org/doc/FAQ.html#why-is-spacemacs-hanging-on-startup)? If that doesn't help you solve the problem, please add some more info as detailed in [Debugging](https://github.com/syl20bnr/spacemacs/wiki/Debugging) in our wiki.

**Comment by winkar** [comment]
I've solved this just by changing url from ```/ssh:ubuntu:~ to /sshx:ubuntu:~``` , although I still cannot understand why setting default-method doesn't work.
