### ISSUE TITLE
Diminish indicators for daemon mode and ycmd.

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#7825]
Currently there are no unicode symbols for ycmd or to indicate that the current frame is an `emacsclient` instance.

In the case of ycmd, changing the symbol (perhaps two different colours) based on whether or no parsing is in progress (https://github.com/abingham/emacs-ycmd/issues/388) may be useful.

**Comment by deb0ch** [comment]
For indicating parsing status there was something similar and interesting proposed for flycheck at some point, to indicate the status using unicode emojis: https://github.com/liblit/flycheck-status-emoji.

I'm not sure if something like that exists for ycmd, if it is easy to implement or if anyone will ever have the courage of doing so.

Just felt like mentioning the idea.
