### ISSUE TITLE
[Improvement] Bind NeoTree to SPC `

### ISSUE THREAD

**Issue by phoe** [syl20bnr/spacemacs#7826]
When active, NeoTree window is currently bound to `SPC 0` which is on the far right of the keyboard and nowhere close to `SPC 1`.
In my opinion it could be bound to ``SPC ` `` which is just beside `1` and just feels much more natural to me as a newcomer.

**Comment by duianto** [comment]
A recent commit to the develop branch, added the key binding <kbd>SPC \`</kbd>, it runs the command:
`winum-select-window-by-number`. Which opens a "Window:" minibuffer prompt, where one can type a window number to select that window. 

This is the help documentation for the command:
> SPC ` runs the command winum-select-window-by-number (found in
> evil-normal-state-local-map), which is an interactive autoloaded compiled Lisp
> function in ‘winum.el’.
> 

> It is bound to SPC ², SPC \`, <motion-state> SPC ², <motion-state> SPC \`, M-m ²,
> M-m \`, C-x w ², C-x w `.
> 
> (winum-select-window-by-number &optional ARG)
> 
> Select or delete window which number is specified by ARG.
> If the number is negative, delete the window instead of selecting it.
> There are several ways to provide the number:
> - if called from elisp with an argument, use it.
> - if called interactively with a numeric prefix argument, use it.
> - if prefix argument is the negative argument, delete window 0.
> - if prefix argument is the default prefix argument, delete current window.
> - if called interactively and no valid argument is provided, read from
>   minibuffer.
> 

Does this mean that this issue and PR needs to be modified or closed?

**Comment by d12frosted** [comment]
Closing the issue due to lack of activity. 😿
