### ISSUE TITLE
Appreciate your work.

### ISSUE THREAD

**Issue by deech** [syl20bnr/spacemacs#7827]
No issue, just wanted to thank you for your work on Spacemacs. It's an integral part of my daily workflow both for work and play.

**Comment by syl20bnr** [comment]
Thank you! 💜

**Comment by luismilanooliveira** [comment]
I second that! More than any other open source project, Spacemacs became part of my routine and it is my goto solution for many different workflows, both for coding and writing!
I'm really thankful to @syl20bnr and all the contributors that dedicate so much of their (precious) time for improving this whole experience!
