### ISSUE TITLE
Anyone has been able to customize neo tree with icons?

### ISSUE THREAD

**Issue by Oxyrus** [syl20bnr/spacemacs#7828]
Hello, I want to customize my neo tree with icons, I found [this](https://www.youtube.com/watch?v=6airCRZqawM&feature=youtu.be&t=4m1s) video in which he explains it, however at that minute when he searches for neo I get 

> No customizable group, face or option matching

![http://i.imgur.com/EEU7fNp.png](http://i.imgur.com/EEU7fNp.png)

Someone faced the same issue and was able to solve it? or how could I go over adding icons to my neo tree?

**Comment by nixmaniack** [comment]
Assuming you're using `dotspacemacs-distribution` as  `'spacemacs` and not `'spacemacs-base` - you'll have to install [`all-the-icons.el`](https://github.com/domtronn/all-the-icons.el) package and also install fonts it mentions in [readme](https://github.com/domtronn/all-the-icons.el#resource-fonts). You can add the package to `dotspacemacs-additional-packages` in dotspacemacs file. 

Then add following line to your dotspacemacs file.
```elisp
(setq neo-theme 'icons)
```

**Comment by Oxyrus** [comment]
@nixmaniack thank you so much, I was missing the `(setq neo-theme 'icons)` in my user configuration :+1:

**Comment by bmag** [comment]
Closing as solved
