### ISSUE TITLE
failed to install some of the themes

### ISSUE THREAD

**Issue by zyfyy** [syl20bnr/spacemacs#7833]
## just asking for help

```
Warning (spacemacs): An error occurred while retrieving the theme, using default theme. (error: (error Required feature ‘sublime-themes’ was not provided))
```

I found the `sublime-themes` installed in the `elpa` folder `sublime-themes-20160403.1902`.

So, what's problem, any sugesstion?

I fact, I have tried all of the theme, failed theme lists:

`brin` `dorsey` `fogus` `graham` `granger` `hickey` `junio` `mccarthy` `odersky`  `ritchie`  `spolsky` and `wilson`

**Comment by bmag** [comment]
Not enough info. Please read about [Debugging](https://github.com/syl20bnr/spacemacs/wiki/Debugging) in our wiki. Also, what are you trying to accomplish?

**Comment by syohex** [comment]
Which theme did you use ? `sublime-themes` provide neither `sublime-themes` nor `sublime`. You can find theme names from here(https://github.com/owainlewis/emacs-color-themes/search?utf8=✓&q=provide-theme)

**Comment by zyfyy** [comment]
Sorry put the issue wrong place @bmag @syohex .

I originally got the theme lists from [spacemacs_theme_gallery](http://themegallery.robdor.com/), and try every of the themes by `SPC - T - n`.Some of these themes faild :
`brin` `dorsey` `fogus` `graham` `granger` `hickey` `junio` `mccarthy` `odersky` `ritchie` `spolsky` and `wilson` with Warning `An error occurred while retrieving the theme, using default theme. (error: (error Required feature ‘sublime-themes’ was not provided))`

Here is the really issue [place](https://github.com/robmerrell/spacemacs_theme_gallery/issues/5)

Thanks for your concern!
