### ISSUE TITLE
diary-insert-entry does not work

### ISSUE THREAD

**Issue by srid** [syl20bnr/spacemacs#7834]
#### Description :octocat:

Unable to insert to diary.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC SPC diary-insert-entry`

*Observed behaviour:* :eyes: :broken_heart:

Errors out (see error message below)

*Expected behaviour:* :heart: :smile:

Should have worked.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml helm auto-completion better-defaults emacs-lisp git markdown org haskell purescript nixos rcirc syntax-checking)
```

#### Backtrace :paw_prints:

```
diary-insert-entry: Symbol's value as variable is void: displayed-month
```

**Comment by srid** [comment]
I just realized that I was supposed to be running this calendar from the calendar view.

**Comment by apteryks** [comment]
Maybe should be a bug reported against in Emacs, I just ran into that, and it's surprising.
