### ISSUE TITLE
Org breaks keybindings of pdfview mode

### ISSUE THREAD

**Issue by et2010** [syl20bnr/spacemacs#7836]
#### Description :octocat:
pdfview mode loses keybindings after org started.

#### Reproduction guide :beetle:
- Start Emacs
- Open any pdf file with more than one page
- Using `j/k` to navigate between pages
- Open an org buffer
- Switch back to the pdf buffer
- `j/k` cannot navigate through different pages any longer.

*Observed behaviour:* :eyes: :broken_heart:
With `SPC h d k`, you can see that `j` is bound to `doc-view-next-line-or-next-page` now (before starting org, it is bound to `pdf-view-next-line-or-next-page`).

*Expected behaviour:* :heart: :smile:
keybindings keep the same, with or without org started.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm emacs-lisp pdf-tools)
```

**Comment by et2010** [comment]
Org mode version 9.0.1 (org-plus-contrib-20161118/)

**Comment by et2010** [comment]
@bmag That's strange cuz I did a fresh install and still got this problem. Did you follow the rep guide exactly?

**Comment by bmag** [comment]
Yes, I followed it exactly. Note that I tried it on develop, not master.

**Comment by et2010** [comment]
Which version of emacs are you using? @bmag

**Comment by bmag** [comment]
Emacs 25.1, Ubuntu 16.04

**Comment by rodonn** [comment]
I just checked on OSX Emacs 25.1. I cannot reproduce the error.
`j` is bound to `pdf-view-next-line-or-next-page` for me.

**Comment by et2010** [comment]
Ah, this has been haunted me for quite a while. I don't know where to start to debug this. I tried both emacs 24 an 25 but the problem remains.

**Comment by bmag** [comment]
First, if you're switching between Emacs versions, you should make sure that you're using the correct byte-compiled elc files for the Emacs version in use (elc files compiled with Emacs 24.5 won't necessarily work with 25.1, and vice versa). There's a built-in command for recompiling elisp files, so that shouldn't be a problem.

Second, you can press `SPC h d k j` to open the description of the `j` key binding. If you're using 25.1, then it should also tell you in what keymap the key is defined. I'd search for `doc-view-next-line-or-next-page` in all elisp files (recursively) in `~/.emacs.d/`, `~/.emacs.d/elpa/`, and `.spacemacs` (or `~/.spacemacs.d/`).

**Comment by et2010** [comment]
Thanks for help @bmag.

I switched to 25.1 and recompiled all possible el files under `.emacs.d/elpa/`, but the problem still remains. I also tried grep through all possible init files, it seems `doc-view-next-line-or-next-page` only presents in `spacemacs-ui/packages.el`. 

I have compared `pdf-view-mode-map` before and after org is started, here is the result:
![spacemacs_issue_7836](https://cloud.githubusercontent.com/assets/11584902/21002016/7cb0d03a-bd5e-11e6-970c-5aefeab0af95.png)
It seems that the changed keybindings happen to be those defined in `spacemacs-ui/init-doc-view`, and the doc-view bindings is in some way overriding the pdf-view bindings. But I have no clue how does that happen.

**Comment by et2010** [comment]
I came up with a temporary solution:

```elisp
(add-hook 'org-mode-hook (lambda ()
                                 (evilified-state-evilify pdf-view-mode pdf-view-mode-map
                                   ;; Navigation
                                   "0"  'image-bol
                                   "$"  'image-eol
                                   "j"  'pdf-view-next-line-or-next-page
                                   "k"  'pdf-view-previous-line-or-previous-page
                                   "l"  'image-forward-hscroll
                                   "h"  'image-backward-hscroll
                                   "J"  'pdf-view-next-page
                                   "K"  'pdf-view-previous-page
                                   "gg"  'pdf-view-first-page
                                   "G"  'pdf-view-last-page
                                   "gt"  'pdf-view-goto-page
                                   "gl"  'pdf-view-goto-label
                                   "u" 'pdf-view-scroll-down-or-previous-page
                                   "d" 'pdf-view-scroll-up-or-next-page
                                   (kbd "C-u") 'pdf-view-scroll-down-or-previous-page
                                   (kbd "C-d") 'pdf-view-scroll-up-or-next-page
                                   (kbd "``")  'pdf-history-backward
                                   ;; Search
                                   "/" 'isearch-forward
                                   "?" 'isearch-backward
                                   ;; Actions
                                   "r"   'pdf-view-revert-buffer
                                   "o"   'pdf-links-action-perform
                                   "O"   'pdf-outline
                                   "zr"  'pdf-view-scale-reset)) 'append)
```

**Comment by et2010** [comment]
Close this for now. Feel free to reopen it.

**Comment by braham-snyder** [comment]
essentially the same issue here--this was indeed the (or at least a) culprit:

```
(defun spacemacs-ui/init-doc-view ()
  (use-package doc-view
    :defer t
    :init
    (evilified-state-evilify doc-view-mode doc-view-mode-map
      "/"  'spacemacs/doc-view-search-new-query
      "?"  'spacemacs/doc-view-search-new-query-backward
      "gg" 'doc-view-first-page
      "G"  'spacemacs/doc-view-goto-page
      "gt" 'doc-view-goto-page
      "h"  'doc-view-previous-page
      "j"  'doc-view-next-line-or-next-page
      "k"  'doc-view-previous-line-or-previous-page
      "K"  'doc-view-kill-proc-and-buffer
      "l"  'doc-view-next-page
      "n"  'doc-view-search
      "N"  'doc-view-search-backward
      (kbd "C-d") 'doc-view-scroll-up-or-next-page
      (kbd "C-k") 'doc-view-kill-proc
      (kbd "C-u") 'doc-view-scroll-down-or-previous-page)
    :config
    ...
```

I've a hunch that `evilified-state-evilify` imparts to its key bindings extraneous resilience because of https://github.com/syl20bnr/spacemacs/issues/3978

**Comment by benneti** [comment]
Can confirm the problem, after commenting out org mode in my configuration I could scroll again in pdfview mode
