### ISSUE TITLE
Helm doesn't distinguish between upper and lowercase (develop branch)

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#7837]
The screenshot should be clear:
![image](https://cloud.githubusercontent.com/assets/3727925/20623813/5ffd2342-b301-11e6-9510-eb3740867f16.png)

For instance, both `C` and `c` are labeled `+capture/colors`, while actually pressing `c` gets `compile/comments`.

**Comment by bmag** [comment]
That's not [helm](https://github.com/emacs-helm/helm), that's [which-key](https://github.com/justbur/emacs-which-key) (two different features that pop a window at the bottom). Please report upstream.
@justbur seems that `replace-regexp-in-string` is case-insensitive, and changing `case-fold-search` to `nil` makes it case-sensitive.

**Comment by justbur** [comment]
Thanks. I think it should be fixed after the next update.

**Comment by Stebalien** [comment]
The fixed version is on melpa.

**Comment by bmag** [comment]
Can confirm issue is fixed :+1:
