### ISSUE TITLE
Using source code pro on windows results in weird line highlight behaviour

### ISSUE THREAD

**Issue by sohail-surge** [syl20bnr/spacemacs#7840]
#### Description :octocat:

Using the SourceCode Pro fonts on Windows, selecting syntax highlighted lines
results in a different height for the selected lines.

#### Reproduction guide :beetle:

- On Windows, install source code pro fonts
- Start Emacs
- Open a syntax highlighted file
- Select some text in the file

*Observed behaviour:* :eyes: :broken_heart:

The line height of the selected lines seems to change causing the rest of the
file to move up/down with selection.

See here: https://i.imgur.com/xJnp3vG.gifv

*Expected behaviour:* :heart: :smile:

The line height of the selected lines should remain the same.

(%LAST_KEYS%)

#### System Info :computer:
- OS: windows-nt
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript windows-scripts auto-completion better-defaults emacs-lisp common-lisp python clojure git org latex ruby-on-rails
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            syntax-checking version-control c-c++ erc my-file-templates typescript ipython-notebook markdown csharp html docker)
```

```

```

**Comment by syl20bnr** [comment]
Not sure it is releated to `source code pro`, I do have this bug on Windows when `fill-column-indicator` is on. Is it the case here?

**Comment by sohail-surge** [comment]
Yes, that's it. Turning off `fill-column-indicator` fixes the issue. Any suggestions (or another bug to follow?)

**Comment by sohail-surge** [comment]
Found it: #6707
