### ISSUE TITLE
`spacemacs/alternate-window` (on SPC w TAB)

### ISSUE THREAD

**Issue by braham-snyder** [syl20bnr/spacemacs#7845]
Since we already have `spacemacs/alternate-buffer` on <kbd>SPC</kbd><kbd>TAB</kbd>, `spacemacs/jump-to-last-layout` on <kbd>SPC</kbd><kbd>l</kbd><kbd>TAB</kbd>, and `eyebrowse-last-window-config` on <kbd>SPC</kbd><kbd>l</kbd><kbd>w</kbd><kbd>TAB</kbd>, adding something like `spacemacs/alternate-window` on <kbd>SPC</kbd><kbd>w</kbd><kbd>TAB</kbd> seems like a natural, useful progression.

**Comment by bmag** [comment]
So, you want `SPC w TAB` to select the previously selected window? And if `SPC w TAB` is pressed several times then it should switch back-and-forth between a pair of windows?

**Comment by braham-snyder** [comment]
Yup!
