### ISSUE TITLE
Annoying coding-system prompt on startup and paradox invocation

### ISSUE THREAD

**Issue by valrus** [syl20bnr/spacemacs#785]
Whenever I start up Emacs or bring up Paradox with `<SPC> a P`, I get a warning buffer with the following due to characters in the package description for `yatex`:

```
These default coding systems were tried to encode text
in the buffer ` *temp*':
  (iso-latin-1-dos (3418 . 37326) (3419 . 40165))
However, each of them encountered characters it couldn't encode:
  iso-latin-1-dos cannot encode these: 野 鳥
```

The minibuffer says `Select coding system (default utf-8):` and just hitting `<RET>` works. But it seems the default coding system should just be set to UTF-8 right off.

P.S. This is on Windows 7.

**Comment by syl20bnr** [comment]
It's weird, the default coding system should be utf-8. What build of emacs do you use on windows ?

**Comment by syl20bnr** [comment]
I got it on the windows box when updating the packages, I will try to find a good repro step in order to fix it.

**Comment by valrus** [comment]
Thanks. Embarrassingly I was having a tough time figuring out where I got my Emacs build :blush:

**Comment by syl20bnr** [comment]
Fixed in develop branch.
