### ISSUE TITLE
ein: canot delete last line of input cell with `d d`

### ISSUE THREAD

**Issue by adrianstaniec** [syl20bnr/spacemacs#7850]
#### Description :octocat:

can't delete line of input cell of ipython-notebook
using `d d` in Normal Mode

#### Reproduction guide :beetle:

- Start Emacs

- Start jupyter server
- open a notebook using SPC a i n
- add input cell with few lines of code
- go to last line
- press d d (Normal state in evil mode)

*Observed behaviour:* :eyes: :broken_heart:

nothing happens

*Expected behaviour:* :heart: :smile:

line should be deleted and cursor move to the line above,
it prrobably fails because nortmaly it goes to line below,
but in that case it' the end of the cell

(%LAST_KEYS%)

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(windows-scripts ivy auto-completion better-defaults emacs-lisp evil-commentary python ipython-notebook spacemacs-evil spacemacs-editing-visual spacemacs-ui-visual)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:

```



```

**Comment by syl20bnr** [comment]
I believe it should be reported upstream (to ein package repo) but we should reproduce with `emacs -Q` with only ein and evil enabled to be sure.

**Comment by diadochos** [comment]
### Workaround
I wrote the code below to workaround (I'm not sure if I should post it here). This requires advice, but so far it's working for me.
(Please kindly direct me if there's an appropriate place to post this reply)

``` elisp
(defun advice:evil-delete (orig-func &rest args)
    (cond ((not (derived-mode-p 'ein:notebook-multilang-mode)) (apply orig-func args))
          ((not (eq (get-text-property (point) 'read-only) nil)) (apply orig-func args)) ; Outside cell
          ((not (let* ((below (line-beginning-position 2)) ; Only line of a cell
                       (above (- (line-beginning-position) 1))
                       (above-is-readonly (eq (get-text-property above 'read-only) t))
                       (below-is-readonly (eq (get-text-property below 'read-only) t)))
                  (not (and above-is-readonly below-is-readonly)))) (progn (print "Only line in the cell.") (apply orig-func args)))
          (t (let* ((begin (- (line-beginning-position 2) 1))
                    (end (+ 1 begin))
                    (read-only-state-of-the-next-line-head (get-text-property begin 'read-only)))
               (let ((inhibit-read-only t)) (remove-text-properties begin end '(read-only t)))
               (apply orig-func args)
               (let ((inhibit-read-only t)) (add-text-properties begin end '(read-only read-only-state-of-the-next-line-head)))))
          'around))
(advice-add 'evil-delete :around 'advice:evil-delete)
```
