### ISSUE TITLE
Can't turn spacemacs/toggle-auto-fill-mode off in latex-mode

### ISSUE THREAD

**Issue by maplewizard** [syl20bnr/spacemacs#7851]
I set 
```
(eval-after-load "TeX-mode"
    '(spacemacs/toggle-auto-fill-mode-off))
```
In 'dotspacemacs/user-init ()', but it seems fails to run. I have to run it with 'M-x'. Is there anything wrong with my config?

**Comment by syl20bnr** [comment]
You should use the `add-hook` instead of `eval-after-load`.
`eval-after-load` happens only once when the library is loaded, what you want is to force it off everytime a TeX buffer is opened, it requires to use a hook, conventionally such hook variable should `TeX-mode-hook`.

**Comment by maplewizard** [comment]
I set 
`(setq latex-enable-auto-fill nil)` in .spacemacs
and it works. 
Thanks
