### ISSUE TITLE
Cannot display which-key names

### ISSUE THREAD

**Issue by LdBeth** [syl20bnr/spacemacs#7858]
#### Description :octocat:
Cannot disaplay which-key prefix names normally 

#### Reproduction guide :beetle:
- Copy and paste my [custom layer](https://github.com/LdBeth/emms/tree/master) to ~/.emacs.d/private
- Start Emacs
- Try `SPC x` or anything that can make the mini buffer disaplay which-key prefix names

*Observed behaviour:* :eyes: :broken_heart:
Prefix names like " irc" "emacs" all change to " prefix"
![5bffc8965029f3291b079ea70578b7f1498aa0a8](https://cloud.githubusercontent.com/assets/22933696/20657412/9251377c-b570-11e6-99d6-4e9d2d3d183d.png)
however, some of them still works.
![4f49b8333c0cab9aa419849272df6d1b9de99d64](https://cloud.githubusercontent.com/assets/22933696/20657457/00645942-b571-11e6-8fe6-80f976829fb2.png)

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 emacs-lisp markdown sql syntax-checking
 (osx :variables osx-use-dictionary-app nil)
 chinese emms emoji
 (erc :variables erc-nick "LdBeth" erc-nick-uniquifier "`LdBeth" erc-nickserv-passwords
      '((freenode
         (("LdBeth" . "my-password"))))
      erc-server-list
      '(("irc.freenode.net" :port "6667" :nick "LdBeth")
        ("irc.myserver.net" :port "6667" :nick "LdBeth" :password "password"))
      erc-networks-alist
      '((freenode "freenode.net")
        (Bancho "myserver.net"))
      erc-network-hide-list
      '(("Bancho" "JOIN" "PART" "QUIT"))
      erc-rename-buffers t erc-networks-mode t erc-prompt-for-nickserv-password nil)
 gnus)
```
- System configuration features: RSVG NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by LdBeth** [comment]
The which-key package I us is 20161125.600

**Comment by d12frosted** [comment]
Hey, I don't see you using `spacemacs/declare-prefix` for your 'prefixes'. You only set `music` for `SPC a m`. For example, you should add `(spacemacs/declare-prefix "xa" "apps")` in your layer.

**Comment by toinfty** [comment]
I can confirm this issue. Actually, all the **second level** `which-key` prefix are gone. Maybe `which-key` changes its function and makes ` (spacemacs/declare-prefix "xa" "apps") ` do not work any more ...

**Comment by nixmaniack** [comment]
Still not fixed it seems. I update to latest packages, also tried which-key.el directly from github.

<img width="1280" alt="screenshot 2016-11-30 14 19 16" src="https://cloud.githubusercontent.com/assets/542810/20745670/57bda200-b708-11e6-913a-77174496e3a2.png">
<img width="1280" alt="screenshot 2016-11-30 14 19 04" src="https://cloud.githubusercontent.com/assets/542810/20745671/57be416a-b708-11e6-95f0-439433a733a7.png">

**Comment by kccai** [comment]
This commit https://github.com/justbur/emacs-which-key/commit/a2b3383f49530fd4a99e924e8b7973f468795a9d breaks which-key ... It worked fine in the previous commit. Maybe we can update which-key later as I think @justbur is refactoring which-key these days.
