### ISSUE TITLE
shell color is not acceptable for kernel to make menuconfig

### ISSUE THREAD

**Issue by miraclemore** [syl20bnr/spacemacs#7859]
![kernel_config](https://cloud.githubusercontent.com/assets/3292065/20660862/aced808e-b586-11e6-8f8f-7ebfa3444a31.png)
#### Description :octocat:
when i launch shell from spacemacs to do the kernel configuration, it is hard to use

#### Reproduction guide :beetle:
- Start Emacs
- Launch shell
- Enter kernel dir
- do make menuconfig

*Observed behaviour:* :eyes: :broken_heart:
1. cost too much time to load
2. color for user can't be acceptable in spacemacs-dark

*Expected behaviour:* :heart: :smile:
1. fast load
2. optimize color

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(markdown vimscript helm
          (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
          better-defaults colors shell emacs-lisp git markdown org syntax-checking version-control c-c   asm gtags
          (python :variables python-test-runner
                  '(pytest nose)
                  python-sort-imports-on-save t python-fill-column 99)
          ipython-notebook)
```

**Comment by bmag** [comment]
Maybe you're hitting a limitation in Emacs shells - they can have problems with "graphic in terminal" programs (e.g. anything based on ncurses). You should be able to find more info about the topic on the internet. You can also try using a different Emacs shell.

**Comment by miraclemore** [comment]
I try two shell on spacemacs. one is eshell, there is nothing to output, and the other one is ansi-term, the result is shown above.
