### ISSUE TITLE
Cannot sync config file: keymapp nill

### ISSUE THREAD

**Issue by y0ast** [syl20bnr/spacemacs#7860]
#### Description :octocat:
"wrong type argument: keymapp nill" when trying to sync configuration file

#### Reproduction guide :beetle:
- Start Emacs
- open config file: SPC f e d
- Try to sync config file: SPC f e R

*Observed behaviour:* :eyes: :broken_heart:
get error: wrong type argument: keymapp nill

*Expected behaviour:* :heart: :smile:
Expected to sync config file but that doesn't happen

Note that when I just restart spacemacs it does sync correctly and installs packages

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml lua osx python helm auto-completion emacs-lisp git syntax-checking
      (shell :variables shell-default-height 30 shell-default-position 'bottom))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

(C-c C-c didn't seem to work from spacemacs, had to copy paste. Is that intended?)

**Comment by syohex** [comment]
If it is following magit issue, you can fix it by updating magit.

https://github.com/magit/magit/issues/2873

**Comment by y0ast** [comment]
That was it! thanks!
