### ISSUE TITLE
Changing pyenv version doesn't change interpreter used by flycheck

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#7862]
I'm using pyenv to switch between Python 2 and 3 (with 3 the default, installed as `/usr/bin/python`). Even after switching to version 2 with `SPC m V s`, flycheck complains about Python 2 `print` statements.

**Comment by marcosmoyano** [comment]
what does SPC e v say after you switch from 3 to 2?

**Comment by beojan** [comment]
```
Syntax checkers for buffer produce_TrigEff.py in python-mode:

  python-flake8 (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  python-pylint (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  python-pycompile
    - may enable: yes
    - executable: Found at /usr/local/bin/python

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 31snapshot (package: 20161117.144)
Emacs version:    25.1.1
System:           x86_64-unknown-linux-gnu
Window system:    x
```

**Comment by marcosmoyano** [comment]
The flycheck messages stick around right after I switch python versions, but the immediately go way right after I change the file and force flycheck to re-run. Try changing the file or reloading it with C-x C-v and see if you still get those errors.

**Comment by beojan** [comment]
For me, they stay even if I force flycheck to re-run by saving the file.

**Comment by marcosmoyano** [comment]
Saving after changing python versions doesn't re-run flycheck, you need to actually modify the buffer. You can run it manually without modifying the buffer with C-c ! c 
I've tried it locally and it's working fine with this file https://gist.github.com/c2411b18cada85fdcabcfad60f5fe6f6
I don't get anything in python 2.7.6
I get: Missing parenthesis in call to 'print' (L5) in python 3.5.2
But switching back and fwd doesn't change the flycheck output. I either modify the buffer or run it manually.

**Comment by cpaulik** [comment]
Do you have flake 8 or any other checker installed for python 3? If so, have you told emacs about it? If you work with the system python versions problems like these are unavoidable since there is no way for emacs to know which flake8 executable belongs to which python version. I would recommend to use virtual environments if you have to work with different python versions.

**Comment by beojan** [comment]
It doesn't work even with `C-c ! c`. I think the problem is that it picks up the version in `/usr/bin` (`/usr/local/bin/python` was a symlink to `/usr/bin/python`) instead of using the pyenv shim.

**Comment by marcosmoyano** [comment]
What do you get by running "which python" on a terminal?

**Comment by beojan** [comment]
`/home/beojan/.pyenv/shims/python`

**Comment by itamarst** [comment]
I'm having similar issues: I enable a virtualenv via pyenv. The virtualenv is where `flake8` is installed, and that isn't found by flycheck.

**Comment by beojan** [comment]
It seems the issue was caused because `/home/beojan/.pyenv/shims` is only in my `PATH` in ZSH, not if emacs is started from the desktop. I fixed it by adding
```elisp
(setq exec-path (cons "/home/beojan/.pyenv/shims" exec-path))
```
to `dotspacemacs/user-config`. If anyone else does the same, remember to change the home directory in the path.

**Comment by blueabysm** [comment]
> It seems the issue was caused because `/home/beojan/.pyenv/shims` is only in my `PATH` in ZSH, not if emacs is started from the desktop. I fixed it by adding
> 
> ```emacs-lisp
> (setq exec-path (cons "/home/beojan/.pyenv/shims" exec-path))
> ```
> 
> to `dotspacemacs/user-config`. If anyone else does the same, remember to change the home directory in the path.

Works for me, Thanks!
