### ISSUE TITLE
sql-mode test fails and does not install

### ISSUE THREAD

**Issue by arnm** [syl20bnr/spacemacs#7863]
#### Description :octocat:
sql-mode test fails and does not install

#### Reproduction guide :beetle:
- Start Emacs
- add sql-mode to layers
- reload spacemacs config
- see errors

*Observed behaviour:* :eyes: :broken_heart:
sql-mode test fails and does not install

*Expected behaviour:* :heart: :smile:
sql-mode test should pass and the layer should get installed

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: nil (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(themes-megapack auto-completion better-defaults git syntax-checking version-control tmux shell clojure elixir emacs-lisp java html javascript react ruby markdown org python sql-mode)
```
- System configuration features: JPEG NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

#### Backtrace :paw_prints:
```
```

**Comment by d12frosted** [comment]
Hey,

`sql-mode` is not a layer. Please checkout the [FAQ section](https://github.com/syl20bnr/spacemacs/blob/develop/doc/FAQ.org#install-a-package-not-provided-by-a-layer) describing on how to install package not provided by a layer. But note that there is a layer named `sql`. Probably this is what you wanted. 

> see errors

I am pretty sure that the error says that there is no layer named `sql-mode`.

**Comment by arnm** [comment]
Whoops, you're right. Adding "sql" instead works. Miss read docs. Thanks
