### ISSUE TITLE
wrong type argument: commandp, clang-format-region

### ISSUE THREAD

**Issue by canxer314** [syl20bnr/spacemacs#7864]
why these happen when I tried to format my code using C-M-TAB?

**Comment by d12frosted** [comment]
Hey, it would be really nice to have more info about your problem. Like what major mode you where in while experiencing the described problem and your setup. Also, stack trace might be helpful as well. Please refer to [contribution guidelines](https://github.com/syl20bnr/spacemacs/blob/master/CONTRIBUTING.org#reporting-issues).

**Comment by canxer314** [comment]
I added
` (c-c++ :variables
             c-c++-default-mode-for-headers 'c++-mode
             c-c++-enable-clang-support t)
`
in dotspacemacs-configuration-layers and
`;; Bind clang-format-region to C-M-tab in all modes:
(global-set-key [C-M-tab] 'clang-format-region)
;; Bind clang-format-buffer to tab on the c++-mode only:
(add-hook 'c++-mode-hook 'clang-format-bindings)
  (defun clang-format-bindings ()
    (define-key c++-mode-map [tab] 'clang-format-buffer))`
in (defun dotspacemacs/user-config () following [https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/c-c%2B%2B](url)
and I tried to format my code that I selected all the code under evil and C++/l through visual state and then pressed Ctrl-Alt-Tab and then the error occurred.

*Messege* buffer*

Auto-saving...done
mwheel-scroll: End of buffer
Quit [2 times]
command-execute: Wrong type argument: commandp, clang-format-region [2 times]
Auto-saving...done
Error during redisplay: (eval undecided-unix) signaled (void-variable undecided-unix) [23 times]
command-execute: Wrong type argument: commandp, clang-format-region
