### ISSUE TITLE
Can't use github fork of base16-emacs

### ISSUE THREAD

**Issue by beojan** [syl20bnr/spacemacs#7867]
I'm trying to use my fork of base16-emacs (to make the fringe the same color as the text background), but despite adding it to `dotspacemacs-additional-packages`:
```
(base16-emacs :location (recipe
                         :fetcher github
                         :repo "beojan/base16-emacs"))
```
spacemacs insists on using the theme from the version of the package on MELPA.

**Comment by bmag** [comment]
Please add system info (`SPC h d s`), as described in [Debugging](https://github.com/syl20bnr/spacemacs/wiki/Debugging) in our wiki.

**Comment by beojan** [comment]
```
#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 4289a49)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-complete-with-key-sequence "<tab> <tab>" auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup nil)
 colors emacs-lisp extra-langs git markdown org syntax-checking
 (spell-checking :variables spell-checking-enable-by-default nil enable-flyspell-auto-completion t)
 typography
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support nil)
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "gibiansky")
 python pandoc latex html csv asm ipython-notebook shell-scripts yaml semantic cscope dash ycmd vim-empty-lines
 (javascript))
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11
```

**Comment by d12frosted** [comment]
This is because theme must be [supported](https://github.com/syl20bnr/spacemacs/blob/master/core/core-themes-support.el) before you can activate it. AFAIK, right now there is now easy way for installing your theme via `dotspacemacs-additional-packages` if it's not supported. But you can manually activate it in `user-init` or `user-config` function.

**Comment by beojan** [comment]
It is supported, but it installs from MELPA instead of using the github
version.

**Comment by syl20bnr** [comment]
@beojan recent improvements in develop branch for theme support should fix this issue.

Put the recipe in `dotspacemacs-themes` directly but use the **theme name** instead of the package name, for instance for `base16-darkone`:

```emacs-lisp
(setq dotspacemacs-themes '(
(base16-darkone :location (recipe
                         :fetcher github
                         :repo "beojan/base16-emacs"))
)
```

**Comment by belak** [comment]
Alternatively, if you want to develop themes locally, you can do something like this in your `dotspacemacs/user-init`:

```
  (add-to-list 'load-path "~/.belak/base16-emacs")
  (add-to-list 'custom-theme-load-path "~/.belak/base16-emacs/build")
```

Those are specific settings for base16, but it should be fairly similar for other packages as well.

**Comment by syl20bnr** [comment]
It is also possible to use `:location local` and put the theme in `emacs.d/private/local/base16-Emacs`
