### ISSUE TITLE
Trouble with "helm-dash-docsets-path"

### ISSUE THREAD

**Issue by nedludd** [syl20bnr/spacemacs#7869]
#### Description :octocat:

I have `helm-dash-docsets-path` set to the default MacOS path in the layer declaration:

```elisp
(dash :variables
      helm-dash-docsets-path "~/Library/Application Support/Dash/DocSets")
```

AND now also as a customized variable:

```elisp
 '(helm-dash-docsets-path "~/Library/Application Support/Dash/DocSets")
```

When I start up Emacs I see that it is set correctly.

However, once I actually try to use it: `SPC d H` and enter a search term, I get 

```
Error (use-package): helm-dash :config: Opening directory: No such file or directory, /Users/nedludd/.docsets
```

It seems to revert somehow.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-use-tab-instead-of-enter t auto-completion-enable-company-help-tooltip t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 applescript backup better-defaults colors csv
 (dash :variables helm-dash-docsets-path "~/Library/Application Support/Dash/DocSets")
 emacs-lisp erc evernote git go html ibuffer
 (javascript :variables tern-command
             '("node" "/Users/therma000/.npm-packages/bin/tern"))
 ldap lua markdown mediawiki org osx puppet
 (ruby :variables ruby-version-manager 'rvm)
 ruby-on-rails
 (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
 syntax-checking tiny-tools vim-empty-lines vinegar vimscript yaml)
```
- System configuration features: JPEG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by bmag** [comment]
The variable was renamed, see release notes for Spacemacs 0.200.0, section "Dash".

**Comment by jiahut** [comment]
`     (dash :variables helm-dash-docset-newpath "~/Library/Application Support/Dash/DocSets/")`
