### ISSUE TITLE
Each project shell should be a unique process

### ISSUE THREAD

**Issue by bugeats** [syl20bnr/spacemacs#7870]
When inside a particular project layout, pressing `SPC p '` will open a shell window and run a command to change the working directory to match the project.  

When you then `SPC p '` within the context of a different project, the new window will re-use the existing shell process. This results in command history getting intermixed, and shell state being clobbered. 

I feel that in a true multi-project workflow, it is reasonable to expect that projects would have their own shell instances, and that spacemacs would intelligently allocate them.

**Comment by duianto** [comment]
The following PRs changes have been applied to the develop branch:
Local shell pop #13556

@bugeats Could you test the latest develop branch, you can close this if the issue has been solved.
