### ISSUE TITLE
Can't get evilified keybings in new po-mode translation layer

### ISSUE THREAD

**Issue by nicorikken** [syl20bnr/spacemacs#7873]
I'm trying to develop a 'translation' layer for doing translation. This mainly features the [po-mode](https://www.emacswiki.org/emacs/PoMode) for editing `.po` gettext files, although I intend to include other minor things like the `mo-mode` for viewing binary language files.

I'm now at the point where I have a custom 'translation' layer in `private/translation`, in which the modes are loaded correctly for the specific file extensions. The next step is to implement keybindings, and thereby evilify existing keybindings. I uploaded [my code](https://gist.github.com/nicorikken/781efbec51e188cce1da1ca10df76e02) for reference.

So far I've tried 2 different methods, all without luck, so I guess I'm doing something wrong:
1. Use `spacemacs/set-leader-keys-for-major-mode` together with `spacemacs/declare-prefix-for-mode` similar to the Markdown layer.
2. Use `evilified-state-evilify-map` to transform the existing [po-mode-map](https://gist.github.com/nicorikken/bf274918c241813a52a1613a7ad147aa#file-po-mode-el-L1107-L1173) keybindings.

Both methods result in no major mode keybindings being defined for Spacemacs, and only the default keybindings for `po-mode` being loaded. So if I try `SPC m` or `,` I get an error.

**Debugging**
* I added some `message` statements inside the `progn` of my `(use-package po-mode` which shows that that section is loaded when a `.po` file is opened.
* I checked `describe-bindings` next to the Helm output.
* I have not been able to properly identify the state the buffer is in, once a po-file is loaded. It is read-only, but that is about it.

*I hope somebody here can get me on the right track.*

**Comment by bmag** [comment]
This should work to set the key bindings. They will only be available (under `SPC m`) when the major-mode is `po-mode`:
```elisp
(spacemacs/set-leader-keys-for-major-mode 'po-mode
  ;;command
  "e" 'po-edit-msgstr
  "cV" 'po-validate)
```
`spacemacs/declare-prefix-for-mode` changes the prefix descriptions in which-key menu.
If the key bindings don't appear (assuming you are in the correct major-mode, and looking at the correct keys), it's because the code didn't run. There are plenty of examples in Spacemacs source to help you.

**Comment by nicorikken** [comment]
@bmag Thanks for the confirmation on my code. Then somehow the key bindings are not set.
Plenty of examples in the code indeed, but many different patterns and use cases as well.
I'll try the most minimal code example to load `po-mode` and set leader keys, and look into edebug to dive deeper if needed. I'll get back with more details.

**Comment by nicorikken** [comment]
@bmag I ripped out all other parts except for the selection you quoted:
```elisp
(defconst translation-packages
  '(po-mode))

(defun translation/init-po-mode ()
  (message "init-po-mode called")
  (use-package po-mode
    :mode ("\\.po\\'" . po-mode)
    :defer t
    :config
    (progn
      (spacemacs/set-leader-keys-for-major-mode 'po-mode
        ;;command
        "e" 'po-edit-msgstr
        "cV" 'po-validate))))
```
The `po-mode` is loaded, but no keybings are set. The major key combinations `SPC m` and `,` only trigger errors.

How can I best detect what is going wrong here?

**Comment by bmag** [comment]
First, put a debug message inside of the `progn`. Does the message appear (in echo-area or in `*Messages*` buffer) after the first time you open a `po` file?

Second, please describe the steps you perform to determine that the keys are not properly bound.

Third, I see that `po-mode` is not a proper major-mode, as it doesn't use `define-derived-mode` (https://gist.github.com/nicorikken/bf274918c241813a52a1613a7ad147aa#file-po-mode-el-L1176). That could be the problem. (you might be able to find more references to "major-modes" with the same problem if you search other issues)

**Comment by nicorikken** [comment]
@bmag Thank you very much. I'm on the right track now. Modifying the `po-mode` to use `define-derived-mode` did the job. I took inspiration from the recently closed issue https://github.com/syl20bnr/spacemacs/issues/7229 and its related pull-request https://github.com/dathinaios/spacemacs-supercollider/commit/923774f9885ce3fb7a5d500216ea1bbfea3bbfb3#diff-f40627aeb3458e3661c006ff120c8126 I'm not sure what is supposed to be left out, For now I've disabled these commands besides rewriting the surrounding function:

```elisp
  (interactive)
  (kill-all-local-variables)
  (setq major-mode 'po-mode
        mode-name "PO")
  (use-local-map po-mode-map)
...
  (run-hooks 'po-mode-hook)
```

This leaves the easy menu, local variables, and some keymaps.

**Fixing this upstream**
If this is a more common problem with existing major modes, can it be documented in the [documentation](http://spacemacs.org/doc/DOCUMENTATION.html)? If it is mentioned as a more common problem, I would have known to try it. Now I was looking in the section about 'states' as a source of the problem.

**Next steps**
- [ ] As the loading of keybindings seems to work again, I expect no further related issues with writing my own layer.
- [ ] Making sure this is documented for other contributers.

**Comment by nicorikken** [comment]
Apparently the `po-subedit-mode` used as a prompt for editing entries is not a real mode. It is text-mode with additional local keybindings. I'll try to turn it into a real `derived-mode`, hoping to fix the keybindings there as well.

**Comment by nicorikken** [comment]
By defining a custom derived mode, I've been able to get the subedit-mode working as well. After tuning the keybindings a bit, I intend to release my translation layer to the community. Stay tuned.

**Comment by bmag** [comment]
> Making sure this is documented for other contributers.

It can be added to the FAQ (`FAQ.org`). Perhaps also to `LAYERS.org`.

Glad to hear you worked it out.

**Comment by bmag** [comment]
If all the issues have been resolved, you can close the ticket.

**Comment by fcevado** [comment]
since this issue is still open... shouldn't spacemacs have a translation/gettext layer? I don't know, maybe in misc...
It would be great if it had [PoMode, MoMode, po-mode+ or gb-po-mode](https://www.emacswiki.org/emacs/PoMode)

**Comment by d12frosted** [comment]
Contributions are warmly welcome 😸
