### ISSUE TITLE
Really minimal configuration

### ISSUE THREAD

**Issue by orestis** [syl20bnr/spacemacs#7877]
Is there any plan for creating an *even* more minimal configuration than `spacemacs-base`? I'm talking about just installing Evil and getting out of the way, allowing users to opt-in to specific plug ins. 

For example, in `spacemacs-base/packages.el` I see 43 packages. Being new to emacs, I have no idea what any of those do, and whether I want them to be active or not. Additionally, when I'm looking for commands I see so many things that I am really lost.

On the other hand, I love how spacemacs prompts me to install layers like markdown or python whenever I open a file, so I don't want to lose that capability.

Thanks!

**Comment by sooheon** [comment]
My current answer to this, btw, is to simply have my own minimal config, but also keep a local spacemacs repo that I keep synced and steal ideas from.

**Comment by bmag** [comment]
`spacemacs-base` is the minimal collection of packages that still gives you the "Spacemacs Experience". Out of the 43 packages, almost all of them are built-in packages. The few new packages in there include projectile, spacemacs-theme, evil-escape, holy-mode and hybrid-mode. That said, you can try using `spacemacs-bootstrap` as your distribution. It's not guaranteed to work and not officially supported, but that's even more minimal than `spacemacs-base`.

For official plans, that's something @syl20bnr will be able to answer, but I haven't heard about such plans.
