### ISSUE TITLE
"Tab" in org-mode tables is not intuitive with evil-mode

### ISSUE THREAD

**Issue by YayC** [syl20bnr/spacemacs#7878]
#### Description :octocat:
 When in an org table, "Tab" should (a) not be repeated with ".", and (b) prefix numbers should work.

 #### Reproduction guide :beetle:
 - Start Emacs
 - visit an org-mode table
 - a. press "iTest\<esc\>"; press "Tab" (org-cycle) to go to next cell; press "*"
 - b. press "3Tab"

 *Observed behaviour:* :eyes: :broken_heart:
 a. "Tab" command is repeated (cursor moves one cell right)
 b. Nothing happens

 *Expected behaviour:* :heart: :smile:
 a. insert command is repeated
 b. moves 3 cells right

 #### System Info :computer:
 - OS: darwin
 - Emacs: 25.1.1
 - Spacemacs: 0.200.5
 - Spacemacs branch: develop (rev. 4289a49)
 - Graphic display: nil
 - Distribution: spacemacs
 - Editing style: vim
 - Completion: helm
 - Layers:
 ```elisp
 (org auto-completion helm emacs-lisp evil-cleverparens unimpaired sql elixir
      (ruby :variables ruby-version-manager 'rvm ruby-enable-enh-ruby-mode t)
      ruby-on-rails dash git markdown vinegar)
 ```
 - System configuration features: JPEG RSVG NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by sooheon** [comment]
This isn't a spacemacs (config/settings) issue, and definitely the fuzzy area where emacs and vim paradigms clash. If you'd do `C-h k <tab>`, you'll see it's bound to `org-cycle`. Follow the link to org.el to see it's a monster >100 line function, overloaded to hell. It has its own logic for how number arguments should work. I do agree with you the command should probably be removed from being recorded in the repeat ring somehow, if that's possible.

**Comment by YayConnolly** [comment]
Gotcha, thanks for your explanation. Sounds like (b) above isn't feasible.

> the command should probably be removed from being recorded in the repeat ring somehow, if that's possible.

That would be great!

**Comment by YayConnolly** [comment]
Same issue with the Tab key when expanding / collapsing outline nodes (it's the same "org-cycle" command).
