### ISSUE TITLE
Suggestion: Release keybinding utilities as independent packages

### ISSUE THREAD

**Issue by chrisbarrett** [syl20bnr/spacemacs#7879]
Hey everyone,

I've rolled my own personal Emacs configuration which uses the Spacemacs style of setting up prefix keys under SPC, but is otherwise very much its own thing. 

I've done the work of extracting some core Spacemacs features into standalone lisp files in package.el format, which could be easily hosted in their own repos and published to MELPA. Have a look and see if you'd be interested in taking these over yourselves. :)

- [spacemacs-keys](https://github.com/chrisbarrett/.emacs.d/blob/master/lisp/spacemacs-keys/spacemacs-keys.el)
- [evil-transient-state](https://github.com/chrisbarrett/.emacs.d/blob/master/lisp/evil-transient-state/evil-transient-state.el)
- [evilified-state](https://github.com/chrisbarrett/.emacs.d/blob/master/lisp/evilified-state/evilified-state.el)

**Comment by nixmaniack** [comment]
IMO `evil-transient-state` name is misleading as it has nothing to do with `evil` nor it integrates with it. In case this is getting published it'd be better to rename it to something else to avoid confusion - maybe on the lines of `hydra-transient-state` or `space-transient-state`
