### ISSUE TITLE
Does window switch key changed?

### ISSUE THREAD

**Issue by halfcrazy** [syl20bnr/spacemacs#7881]
#### Description :octocat:
C-j C-k C-l C-h no longer switch windows.

#### Reproduction guide :beetle:
- Start Emacs
- Open 2 or more windows
- Try to use C-j C-k C-l C-h to switch between them.

*Observed behaviour:* :eyes: :broken_heart:
C-j C-k C-l C-h doesn't switch windows but do something like emacs behaviour.
C-k does kill to end of line etc.

*Expected behaviour:* :heart: :smile:
Cursor switch between the window.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 4289a49)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(php csv windows-scripts
     (auto-completion :variables auto-completion-enable-snippets-in-popup t)
     semantic better-defaults ibuffer
     (imenu-list :variables imenu-list-size 0.2)
     gtags deft emacs-lisp git
     (colors :variables colors-enable-nyan-cat-progress-bar t)
     (chinese :variables chinese-enable-youdao-dict t)
     markdown osx
     (org :variables org-enable-github-support t)
     syntax-checking version-control
     (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
     (go :variables go-tab-width 4)
     lua python shell html yaml javascript dash ansible docker nginx)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by nixmaniack** [comment]
I'm unaware of this functionality being present in Spacemacs. By any chance you were using `tmux` - I can see only `tmux` layer was providing such bindings for navigation.

**Comment by halfcrazy** [comment]
@nixmaniack You're right... I comment my enabled tmux layer by mistake.
