### ISSUE TITLE
The suggestions provided by which-key do not describe what the key does

### ISSUE THREAD

**Issue by esjee** [syl20bnr/spacemacs#7882]
#### Description :octocat:
The entries provided by which-key seem to be wrong. It appears that something like a namespace is rendered rather than a helpful function name.

#### Reproduction guide :beetle:
- Start Emacs
- Open any Ruby file
- Press `SPC r r`

(The same issues seems to apply to all which-key suggestions, I just happened to choose `SPC r r`.)

*Observed behaviour:* :eyes: :broken_heart:
The suggestions provided by which-key are all the same: `ruby/RuboCop`.

![2016-11-30-130900_854x60_scrot](https://cloud.githubusercontent.com/assets/2501554/20751911/b8be356a-b6fe-11e6-8157-1ed71bf045fe.png)

*Expected behaviour:* :heart: :smile:
The suggestions provided by which-key give an accurate description of what is going to happen, e.g. `rubocop-check-current-file`, `rubocop-check-project`, etc.

![pasted image at 2016_11_30 11_54 am](https://cloud.githubusercontent.com/assets/2501554/20751898/a5bac7b2-b6fe-11e6-9bb0-8269715e5cb1.png)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript
 (ruby :variables ruby-version-manager 'rvm ruby-test-runner 'rspec)
 ruby-on-rails helm auto-completion emacs-lisp git)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by hiemanshu** [comment]
After doing some debugging on Gitter, found out that this is caused by a new which-key update. Rolling back to an older slot will fix this.

**Comment by esjee** [comment]
That indeed solved the issue! Thanks!

Is it helpful to leave this issue open, or do you prefer I close it out? I'm not sure if something in spacemacs needs to be changed, or if perhaps the latest which-key contains a bug.

**Comment by hiemanshu** [comment]
I think we should leave the issue open. Its a workaround to downgrade and not an actual fix.

**Comment by dubnde** [comment]
May be https://github.com/justbur/emacs-which-key/issues/155

**Comment by dubnde** [comment]
Fixed `which-key`  seems to be available on ` melpa` now

**Comment by esjee** [comment]
Thanks! I just updated and it did indeed work as expected. The issue appears to have been resolved.
