### ISSUE TITLE
Following symlinks doesn't work with vc-follow-symlinks set to true

### ISSUE THREAD

**Issue by jschaf** [syl20bnr/spacemacs#7885]
#### Description :octocat:

Spacemacs does not follow symlinks to linked file with `(setq vc-follow-symlinks t)`

#### Reproduction guide :beetle:
- From a shell:
```bash
mkdir /tmp/symlink-bug
git init /tmp/symlink-bug
echo 'empty file' > /tmp/symlink-bug/foo.txt
ln -s /tmp/symlink-bug/foo.txt ~/foo-link.txt
```
- In emacs: `(setq vc-follow-symlinks t)`
- <kbd>M-x find-file</kbd> ~/foo-link.txt
- <kbd>M-x eval-expression</kbd> `(buffer-file-name)` => `~/foo-link.txt`

*Observed behaviour:* :eyes: :broken_heart:
Emacs opens the file in `~` instead of in `/tmp/symlink-bug`.

*Expected behaviour:* :heart: :smile:
Emacs should open the file in `/tmp/symlink-bug` and `buffer-file-name` should be `/tmp/symlink-bug/foo.txt`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers: **Tested in emacs --no-layer**
```elisp
(google rust sql csv python yaml finance
        (auto-completion :variables auto-completion-tab-key-behavior 'complete auto-completion-private-snippets-directory "~/.dotfiles/snippets" auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t :disabled-for org git)
        emacs-lisp git html markdown mu4e org javascript joe latex syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:

N/A

**Comment by dubnde** [comment]
try setting `find-file-visit-truename`

**Comment by bmag** [comment]
Reprodues in stock Emacs, and anyway @jschaf you probably misunderstood what `vc-follow-symlinks` is supposed to do. Use `find-file-visit-truename` as @dubnde suggested.

**Comment by jschaf** [comment]
Ah, yep.  That did it, thanks.
