### ISSUE TITLE
Keyboard shorcut completion labels not shown correctly.

### ISSUE THREAD

**Issue by karlbright** [syl20bnr/spacemacs#7887]
#### Description :octocat:
Having done a clean install of spacemacs and starting with minimal distribution, and enabling ivy.
I'm left with labels, being missing on meta key shortcut completion buffers.

![](http://i.imgur.com/aOY5SH7.png)

*Expected behaviour:* :heart: :smile:
Expected to see labels that refer to the action of the given keybinding.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy auto-completion emacs-lisp javascript spacemacs-ui spacemacs-ui-visual spacemacs-editing spacemacs-editing-visual git version-control)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by karlbright** [comment]
After enabling `helm` and removing `ivy` I have realised that the completion around shortcut keys may not be handled by `ivy` at all. Have corrected initial PR description for this.

**Comment by nixmaniack** [comment]
It's `which-key`. Duplicate of https://github.com/syl20bnr/spacemacs/issues/7882. It's fixed upstream.

**Comment by karlbright** [comment]
Thanks @nixmaniack. Unfortunately I wasn't able to really determine what to look for under issues for this particular situation. Closing.
