### ISSUE TITLE
dotspacemacs/emacs-custom-settings is broken, messages "selecting deleted buffer" 

### ISSUE THREAD

**Issue by ksjogo** [syl20bnr/spacemacs#7898]
#### Description :octocat:
`dotspacemacs/emacs-custom-settings` is broken, messages "selecting deleted buffer" and will make emacs unusable as that messages will reoccur

#### Reproduction guide :beetle:
- Start Emacs
`customize-variable` something, then save

*Observed behaviour:* :eyes: :broken_heart:
"selecting deleted buffer"

*Expected behaviour:* :heart: :smile:
Variable saved.

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50.6
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 4289a49)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-front-end 'company)
 (better-defaults)
 (c-c   :variables c-c  -enable-clang-support t)
 (cscope)
 (clojure)
 (colors :variables colors-enable-rainbow-identifiers t)
 (elfeed)
 (elm)
 (emacs-lisp)
 (emoji)
 (erc)
 (extra-langs)
 fasd
 (git :variables git-enable-magit-svn-plugin t)
 (github)
 gtags
 (gnus)
 (go :variables go-tab-width 4)
 (helm)
 (html)
 (javascript)
 (latex :variables latex-build-command "LatexMk" latex-enable-auto-fill t)
 (markdown)
 (mu4e :variables mu4e-installation-path "/usr/share/emacs/site-lisp/mu4e")
 (php)
 (plantuml)
 (react)
 (ruby)
 (rust)
 (shell :variables shell-default-shell 'ansi-term shell-default-term-shell "/usr/local/bin/fish")
 (shell-scripts)
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t)
 (sql)
 (syntax-checking :variables syntax-checking-enale-tooltips nil)
 (typescript)
 (version-control :variables)
 (xkcd)
 (yaml))
```
- System configuration features: RSVG DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by syl20bnr** [comment]
I cannot reproduce it using Emacs 25.
What do you mean by `save` ? I clicked the button `Apply and Save` which correctly updated the `.spacemacs` file.

**Comment by ksjogo** [comment]
`Custom-save` in the customization buffer, but also triggers on accepting new dir-locals, new packages etc.

**Comment by ksjogo** [comment]
The first part until `(princ (spacemacs//get-custom-settings-from-cache))` is executed, I suppose the `with-current-buffer` in `spacemacs//get-custom-settings-from-cache` is causing the problem. Strangely that function works if I add a breakpoint and step through it but fails if I don't.

**Comment by syl20bnr** [comment]
I am really embarrassed, I just cannot reproduce it, I tried what you said and it works in Emacs 25. As long as I cannot reproduce it, it will be hard for me to fix it.

**Comment by aaronjensen** [comment]
@syl20bnr I hit it every time I add something to `dotspacemacs-additional-packages` then restart.

I do not have a `dotspacemacs/emacs-custom-settings` in my `init.el`, but a partial/broken one gets added every time I do this. You might try ensuring you have something like [this](https://github.com/aaronjensen/spacemacs.d/blob/master/init.el#L514-L535) at the bottom of your `init.el`.

**Comment by syl20bnr** [comment]
@aaronjensen thanks for the information, I am going to try this repro step.

**Comment by syl20bnr** [comment]
Still working, I can see that Emacs save the `.custom-settings` file (due to `packages.el`) but I have no issues with it. I try a bunch of weird stuff like deleting some parts of the custom settings in the dotfile or in `.custom-settings` file and it still works.

**Comment by syl20bnr** [comment]
@ksjogo @et2010 @hicksy994 @yang-ling Do you use a dotfile `.spacemacs` or a dotdirectory `.spacemacs.d` ?

**Comment by syl20bnr** [comment]
I guess that the error comes from `find-file-noselect`.

The documentation for the function:

> find-file-noselect is a compiled Lisp function in ‘files.el’.

> (find-file-noselect FILENAME &optional NOWARN RAWFILE WILDCARDS)

> Read file FILENAME into a buffer and return the buffer.
If a buffer exists visiting FILENAME, return that one, but
verify that the file has not changed since visited or saved.
The buffer is not selected, just returned to the caller.
Optional second arg NOWARN non-nil means suppress any warning messages.
Optional third arg RAWFILE non-nil means the file is read literally.
Optional fourth arg WILDCARDS non-nil means do wildcard processing
and visit all the matching files.  When wildcards are actually
used and expanded, return a list of buffers that are visiting
the various files.

If a buffer already exists then it returns it, seems like it may return a handle to a delete buffer.

The code in core is:

```emacs-lisp
(defun spacemacs//get-custom-settings-from-cache ()
  "Returns the custom settings from `spacemacs--custom-file'."
  (with-current-buffer (let ((find-file-visit-truename t)
                             (delay-mode-hooks t))
                         (find-file-noselect spacemacs--custom-file))
    (goto-char (point-min))
    ;; Skip all whitespace and comments.
    (while (forward-comment 1))
    (buffer-substring-no-properties (point) (point-max))))
```

**Comment by aaronjensen** [comment]
@syl20bnr maybe the key is in the `SPC q r` I do after modifying `init.el`. It opens the buffer upon restart. Maybe that's conflicting with something wanting to write to that buffer to update the customize settings?

**Comment by syl20bnr** [comment]
@aaronjensen thanks for the suggestion, tried it and it still works. This bug puzzles me, nowhere we keep a handle to a deleted buffer so the bug seems to lie deeper into Emacs. We have nested `with-current-buffer` in the code, `spacemacs//get-custom-settings-from-cache` is called from within a `with-current-buffer`.

**Comment by aaronjensen** [comment]
@syl20bnr Are the two things related--the emitting of `dotspacemacs/emacs-custom-settings` and the actual error? I don't understand why `dotspacemacs/emacs-custom-settings` is being emitted, what it's actually for and/or why I don't have it in my init.el already.

One thing you could try is:

1. grab my spacemacs.d dir in its entirety
2. reset to https://github.com/aaronjensen/spacemacs.d/commit/8d2a5d1868c0bb0862ba833e65001b77b63842f9
3. launch spacemacs, let it install everything, then `SPC q r`
4. Open `init.el` and add `add-node-modules-path` to `dotspacemacs-additional-packages`
5. `SPC q r`

That may not help you narrow down the minimum repro, but maybe it'll at least reproduce.

**Comment by syl20bnr** [comment]
Good news! I can reproduce it with your config :-)
I'll investigate it tomorrow.

**Comment by syl20bnr** [comment]
Ok so actually I was not able to sleep so I looked into it. Turns out that I found the cause but it is _very_ weird. The root cause is the missing file local variable `mode`:

> ;; -*- mode: emacs-lisp -*-

For whatever reason, if the file has not this line then we get the `select deleted buffer` error and it is triggered whenever `emacs-lisp-mode` is called, Emacs is then completely broken.

I fixed the issue with commit https://github.com/syl20bnr/spacemacs/commit/a5c4863
You have to delete the `.custom-settings` file once and restart Emacs.

**Comment by syl20bnr** [comment]
@ksjogo @et2010 @hicksy994 @yang-ling I fixed another issue with commit https://github.com/syl20bnr/spacemacs/commit/0ab8b7b
The reason for this change is explained in the commit.

**Comment by aaronjensen** [comment]
@syl20bnr I can confirm that a5c4863 fixed the issue I was having, thank you!

**Comment by aaronjensen** [comment]
Just so I understand correctly, it is normal now to have custom settings duplicated like [this](https://github.com/aaronjensen/spacemacs.d/commit/f3fc8aebb374dba53363ef10f67e827bb8b710ff), right?

**Comment by syl20bnr** [comment]
@aaronjensen yes it is expected, you can remove the sexp outside of the function. The replacement is made relatively secure by checking that the sexp are inside the dotspacemacs functions, so anything out of it won't be deleted.

**Comment by aaronjensen** [comment]
will emacs add the old sexp back and I'll have to remove it every time it changes? Or just this once.

**Comment by syl20bnr** [comment]
Just once ;-)

**Comment by yang-ling** [comment]
Sorry for late reply
> Do you use a dotfile .spacemacs or a dotdirectory .spacemacs.d ?

I use dotfile `.spacemacs`

>  I can confirm that a5c4863 fixed the issue I was having, thank you!

I haven't checked this commit. I will test it and report result later.
Thank you.

**Comment by yang-ling** [comment]
> I haven't checked this commit. I will test it and report result later.

Just now I tested the latest develop branch. I can confirm this issue is fixed. Thanks for your work!.

**Comment by ksjogo** [comment]
Fixed now, thank you very much.
