### ISSUE TITLE
Using c-c++ configuration layer breaks spacemacs

### ISSUE THREAD

**Issue by idbrii** [syl20bnr/spacemacs#790]
Using c-c++ configuration layer breaks spacemacs. It looks like emacs is fine, but I can no longer engage evil-mode and powerline is no longer applied (so I get the standard statusline).

Here's the output in the emacs buffer:

    (Bootstrap) Installing bind-key...
    (Bootstrap) Installing use-package...
    (Bootstrap) Installing evil...
    (Bootstrap) Installing evil-leader...
    Found 85 new package(s) to install...
    --> fetching new package repository indexes...
    --> installing (c-c++):srefactor... [78/85]

Restarting emacs usually results in something similar:

    Found 7 new package(s) to install...
    --> fetching new package repository indexes...
    --> installing (c-c++):srefactor... [1/7]

.emacs.d is a clone of syl20bnr/spacemacs@7c85db35866b0dd6a033fa8ccdaac9be2034ecdf (a fresh one so it had to download new packages).

.spacemacs is exactly this:

    ;; -*- mode: dotspacemacs -*-

    (defun dotspacemacs/layers ()
    "Configuration Layers declaration."
    (setq-default
    dotspacemacs-configuration-layers '(
                                        c-c++
                                        )))

GNU Emacs 24.3.1 on Ubuntu 14.04.1 LTS

I'm brand new to emacs so I don't have the knowledge/patience to figure out what's actually wrong.

**Comment by tuhdo** [comment]
You should try again with Emacs 24.4 in the mean time.

**Comment by tuhdo** [comment]
@idbrii I've fixed it in this PR: https://github.com/syl20bnr/spacemacs/pull/782. Maybe you could delay the usage of C/C++ layer until it is merged. Thanks for reporting.

**Comment by syl20bnr** [comment]
Thanks @tuhdo I'll merge tonight and make a new minor version.

**Comment by syl20bnr** [comment]
Fixed in 0.65.2, thanks @tuhdo
