### ISSUE TITLE
Missing documentation tooltip

### ISSUE THREAD

**Issue by t3chnoboy** [syl20bnr/spacemacs#7900]
#### Description :octocat:
Hi!
Today I opened a Clojure project after ~1 year pause.
Back then when I was working with clojure in spacemacs, the auto-completion had an awesome inline documentation.
Now either there’s something wrong with my setup, or the clojure layer doesn’t have the documentation tooltip any more 😞  
I found this issue https://github.com/syl20bnr/spacemacs/issues/4660
Looks like spacemacs doesn’t support help tooltips in terminal any more 😞  and I only use terminal emacs.
I also tested it in GUI emacs. It didn’t work with clojure but worked with emacs lisp(but the tooltip was ugly and weirdly placed), so there’s probably a problem with clojure layer too.
Are there any ways I can restore the previous behavior, at least for clojure?
I did a little bit of research and it seems like it’s a regression from switching to `company` for autocompletion.
I tried excluding `company`, but it didn’t help.

#### Reproduction guide :beetle:
- Start Emacs
- Open a Clojure/Clojurescript file
- start typing a function name and press tab to auto-complete

*Observed behaviour:* :eyes: :broken_heart:
An autocompletion popup without the documentation

*Expected behaviour:* :heart: :smile:
An autocompletion popup with the documentation

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.50.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 4289a496)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(t3chnoboy osx helm
           (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'cycle)
           emacs-lisp org syntax-checking shell-scripts version-control evil-commentary better-defaults xkcd
           (haskell :variables haskell-enable-ghci-ng-support t)
           erlang elixir
           (javascript :variables javascript-disable-tern-port-files nil)
           react
           (scala :variables scala-auto-start-ensime t)
           shell games emoji latex html tmux
           (ruby :variables ruby-version-manager 'rbenv ruby-test-runner 'rspec)
           ruby-on-rails markdown clojure sql
           (git :variables git-magit-status-fullscreen t git-enable-github-support t git-gutter-use-fringe t)
           github restclient colors vim-powerline evil-cleverparens yaml terraform nginx extra-langs themes-megapack)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

#### Backtrace :paw_prints:

**Comment by bmag** [comment]
company-quickhelp doesn't work in terminal, closing as duplicate of #4660

**Comment by t3chnoboy** [comment]
@bmag It wasn't a bug report. It was a question/feature request. It was working ~ a year ago so this is a regression. If you are closing this issue, can you suggest me a better place to make feature requests or asking questions?
I tried asking exactly the same question in slack before opening this issue, but it was ignored 😞

thanks!

**Comment by bmag** [comment]
Oh, I didn't realize you were making a feature request. I'll reopen it, but https://github.com/expez/company-quickhelp might be a better place for this feature request (although I don't know if change `company-quickhelp` is any easier than writing another company frontend).
