### ISSUE TITLE
You're not in a project problem

### ISSUE THREAD

**Issue by hujianxin** [syl20bnr/spacemacs#7901]
#### Description :octocat:
When I open a project using `SPC p l` , I got `You're not in a project` .

#### Reproduction guide :beetle:
- Start Emacs
- Enter `Space p l`
- Select a file within your project to open.

*Observed behaviour:* :eyes: :broken_heart:
Got a message: You're not in a project.

*Expected behaviour:* :heart: :smile:
Emacs checkout to a new layout and open the file you selected.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.50.2
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 4289a496)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(vimscript ivy
           (auto-completion :variables auto-completion-enable-snippets-in-popup t)
           better-defaults git version-control
           (shell :variables shell-default-height 30 shell-default-position 'bottom)
           ibuffer spell-checking syntax-checking
           (semantic :disabled-for emacs-lisp)
           org markdown html emacs-lisp javascript
           (c-c   :variables c-c  -enable-clang-support t)
           (ess :variables ess-enable-smart-equals nil ess-enable-smartparens t)
           (python :variables python-test-runner
                   '(pytest nose))
           (scala :variables scala-auto-insert-asterisk-in-comments t)
           (clojure :variables clojure-enable-fancify-symbols t)
           sql shell-scripts yaml ranger imenu-list evil-cleverparens evil-snipe colors deft cscope gtags restclient all-the-icons)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by hujianxin** [comment]
This problem doesn't appear when I use helm rather ivy. But I met other problem described in other issue.https://github.com/syl20bnr/spacemacs/issues/7903

**Comment by nixmaniack** [comment]
This was due to recent changes in `ivy` which broke `counsel-projectile`. It's recently fixed and should be available on melpa. 

See https://github.com/ericdanan/counsel-projectile/issues/19.

**Comment by hujianxin** [comment]
@nixmaniack Thanks a lot.
