### ISSUE TITLE
Magit and `Space p l' have no a good collaboration.

### ISSUE THREAD

**Issue by hujianxin** [syl20bnr/spacemacs#7902]
#### Description :octocat:
Spacemacs cann't open/attach magit process for each layout.

#### Reproduction guide :beetle:
- Start Emacs
- `Space p l` to select a project you want to open.
- Select a file in this project.(I met a `You're not in a project` problem).
- Given that you got no problem until now. `Space g s` to open a magit buffer for this project.
- `Space p l` to select other project to open.
- In new layout, `Space g s` to open a new magit buffer for current project.

*Observed behaviour:* :eyes: :broken_heart:
Spacemacs open the magit process for previous project(layout) rather than current project(layout).

*Expected behaviour:* :heart: :smile:
Spacemacs open the magit process for current project(layout)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.50.2
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 4289a496)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(vimscript ivy
           (auto-completion :variables auto-completion-enable-snippets-in-popup t)
           better-defaults git version-control
           (shell :variables shell-default-height 30 shell-default-position 'bottom)
           ibuffer spell-checking syntax-checking
           (semantic :disabled-for emacs-lisp)
           org markdown html emacs-lisp javascript
           (c-c   :variables c-c  -enable-clang-support t)
           (ess :variables ess-enable-smart-equals nil ess-enable-smartparens t)
           (python :variables python-test-runner
                   '(pytest nose))
           (scala :variables scala-auto-insert-asterisk-in-comments t)
           (clojure :variables clojure-enable-fancify-symbols t)
           sql shell-scripts yaml ranger imenu-list evil-cleverparens evil-snipe colors deft cscope gtags restclient all-the-icons)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by hujianxin** [comment]
This problem doesn't appear when I use helm rather ivy. But I met other problem described in other issue.https://github.com/syl20bnr/spacemacs/issues/7903

**Comment by nixmaniack** [comment]
Can you update your packages(specially `ivy` and `counsel-projectile`)  and try this again? This mostly looks related to #7901 which you have reported.

**Comment by hujianxin** [comment]
@nixmaniack This problems has been solved perfectly, thanks a lot.
