### ISSUE TITLE
Conflict when open a new project with layout and select a same name file.

### ISSUE THREAD

**Issue by hujianxin** [syl20bnr/spacemacs#7903]
#### Description :octocat:
If I open a new layout with `Space p l`, and select a file whose name is the same as the name of file in current buffer. Spacemacs will change the file in current layout to the file in the project to be open.

#### Reproduction guide :beetle:
- Start Emacs
- `Space p l` to open a project with new layout(which number is 2). Select a file such as `.gitignore file`.
- `Space p l` to open other project with new layout(which number is 3). Select a file whose name is the same as previous file. In this case, its name's `.gitignore`.
- 'Space l 2' to switch to previous layout. 

*Observed behaviour:* :eyes: :broken_heart:
When I switch back to layout 2. I found that the gitignore file is that in layout/project 3, rather than it should be.

*Expected behaviour:* :heart: :smile:
When I switch back to layout 2, the `.gitignore` file is still in it.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.50.2
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 4289a496)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 better-defaults git version-control
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 ibuffer spell-checking syntax-checking
 (semantic :disabled-for emacs-lisp)
 org markdown html emacs-lisp javascript
 (c-c   :variables c-c  -enable-clang-support t)
 (ess :variables ess-enable-smart-equals nil ess-enable-smartparens t)
 (python :variables python-test-runner
         '(pytest nose))
 (scala :variables scala-auto-insert-asterisk-in-comments t)
 (clojure :variables clojure-enable-fancify-symbols t)
 sql shell-scripts yaml ranger imenu-list evil-cleverparens evil-snipe colors deft cscope gtags restclient all-the-icons)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by nixmaniack** [comment]
Again, related to #7901. Please update packages and report if the issue still exists.

**Comment by hujianxin** [comment]
@nixmaniack This problems is not the same as those two. Either `ivy` or `helm` will cause this problem. I upgraded all the packages to the latest. The issue #7901 and #7902 disappeared, but this problem is still at there.

**Comment by nixmaniack** [comment]
Okay, the issue seems to exists.

**Comment by Miciah** [comment]
Looks like a duplicate of #10183.  Granted this issue is older, but that issue has more information at this point, so it might make more sense to close this issue.
