### ISSUE TITLE
how to add my own major-mode-cmd prefix

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#7904]
now space+m is a prefix for major mode cmds, and major-mode related cmds are in it.
I want to add my extra major-mode cmds, but i don't wan to add it in space+m,
i want to define space+o+m to be my own major-mode prefix, then every major-mode cmds i add will in space+o+m.
I've try spacemacs/declare-prefix-for-mode, but it also add the cmds in space+m.

how should i do?

**Comment by bmag** [comment]
You should look at how `spacemacs/set-leader-keys-for-major-mode`, although it's kind of advanced code.
