### ISSUE TITLE
Editing of todo items from agenda view does not work

### ISSUE THREAD

**Issue by gutsle** [syl20bnr/spacemacs#7906]
#### Description :octocat:
Pressing ' in the agenda todo view will display the item in the respective file but it cannot be edited.
Pressing q to close the agenda view will return to the previous file. Pressing C-w ARROW to switch windows somehow doesn't work in this window.

#### Reproduction guide :beetle:
- Start Spacemacs
- Open a new file
- Switch to org mode with: M-x org-mode
- Type: * first item
- Turn it into a todo item using: t
- Set org-agenda-files using: M-: (setq org-agenda-files '("~/filename"))
- Switch to a different buffer for example using: :b *Messages*
- Switch to the org agenda view using: SPC a o t
- Go to latest entry and show the origin using '
- Try to change the name to "second item" or add a subitem

*Observed behaviour:* :eyes: :broken_heart:
You cannot switch to the buffer where it is displayed using C-w leftarrow.
You need to use the mouse to get to the other buffer.
(SPC w h however, works.)

*Expected behaviour:* :heart: :smile:
Window switching should work as usual.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. cf951a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp
 (org :variables org-enable-reveal-js-support t)
 (shell :variables shell-default-height 30 shell-default-position 'bottom))
```

**Comment by bmag** [comment]
<kbd>'</kbd> (`org-agenda-show-and-scroll-up`) doesn't let you edit because it doesn't change the selected window, the cursor is still in the agenda buffer. You can use <kbd>TAB</kbd> instead.
<kbd>C-w ARROW</kbd> doesn't change the window because `C-w` is bound to `kill-region`.
