### ISSUE TITLE
[Question] Python syntax checker don't work in virtual environment

### ISSUE THREAD

**Issue by forrestchang** [syl20bnr/spacemacs#7908]
I have installed python layer and opened my project in virtual environment (use SPC m V a), but it seems like the syntax checker don't work for me. I have installed flake8 and autopep8 in virtual environment. Is there any suggestions?

**Comment by cpaulik** [comment]
Do you have the syntax checking layer enabled?

**Comment by forrestchang** [comment]
@cpaulik Yes, I forgot that, thank you!
