### ISSUE TITLE
*R* buffer keeps getting in third position with Ivy resulting in the Spc Tab shortcut not working as intended

### ISSUE THREAD

**Issue by fausterjames** [syl20bnr/spacemacs#7909]
The shortcut `Spc Tab` is used to switch quibkly between two buffer. When using a normal buffer and the buffer *R* from ESS however the buffer *R* keeps getting in third position after *scratch*, disabling the quick switch with `Spc Tab` as it now switch between the normal buffer and *scratch*

**Comment by harishkrupo** [comment]
This happens with all the buffers which don't have a backing file. For example octave shell, ansi-term and python shell.

**Comment by bmag** [comment]
You can configure `spacemacs-useful-buffers-regexp` and `spacemacs-useless-buffers-regexp`, see for example #7104. Search the bug tracker for "alternate-buffer', "spacemacs-useful-buffers-regexp", etc. to find related issues.
However, buffers that derive from `comint-mode` (I'm not sure if `*R*` does that) should always be considered "useful" and not skipped by `SPC TAB`. @harishkrupo can you provide more details? It should not be happening with the kind of buffers you mentioned.
