### ISSUE TITLE
org: capture mode saves before refile is finished

### ISSUE THREAD

**Issue by leezu** [syl20bnr/spacemacs#7910]
When using `org-capture` to create new entries, spacemacs maps `, r` to `org-capture-refile`. Creating a new entry and then refiling it "executes" the following steps:

- User is prompted to fill entry
- The entry is added to the location specified in the capture template
- As soon as the user calls `org-capture-refile`: The buffer holding the location specified in the capture template is saved
- User is prompted for refile location.
- Entry is moved to refile location

Neither the source nor target buffer of the refiling process is saved after the refiling is finished. This is inconsistent with the way spacemacs saves files when capturing to the default location (i.e. calling `org-capture-finalize`). Furthermore it is inconsistent in itself, as it leaves the entry in the default location of the capture template, where it conceptually never was.

I wonder if the org-mode layer should be adapted to save automatically after refiling a newly created entry?

**Comment by bmag** [comment]
Could you add more info as per [Debugging](https://github.com/syl20bnr/spacemacs/wiki/Debugging)? Also, does the behavior reproduce in stock Emacs with latest org-mode (from orgmode.org/elpa/)?

**Comment by beetleb** [comment]
I'm not a Spacemacs user, but I saw this while searching about the same problem in stock Org Mode/Emacs.

So yes, this is an Org Mode annoyance - not specific to Emacs. The regular capture saves the target file. The capture-refile command doesn't. Or rather, it captures, saves, and *then* refiles, leaving the end file not saved.

Not sure if you want to modify stock Org Mode behavior...

**Comment by beetleb** [comment]
This snippit in init.el should take care of it:

```
(defun save-after-capture-refile ()
  (with-current-buffer (marker-buffer org-capture-last-stored-marker)
    (save-buffer)))
(advice-add 'org-capture-refile :after 'save-after-capture-refile)
```
