### ISSUE TITLE
“Key binding” or “keybinding”?

### ISSUE THREAD

**Issue by LemmingAvalanche** [syl20bnr/spacemacs#7912]
Is it called “key binding” or “keybinding”? As in “The `C-c C-c`
keybinding”.

Some terminology
----------------

This word is a *compound noun*, since it consists of more than one word.

“Keybinding” would be a *closed* or *solid* compound noun. “Key binding”
would be an *open* or *spaced* compound noun.

Data
----

| Spelling      | Count |
|---------------|-------|
| “key binding” | 1001  |
| “keybinding”  | 104   |

Go into `~/.emacs.d` and run:

``` shell
find -name "*\.org" | xargs grep -i "key binding" | wc -l
find -name "*\.org" | xargs grep -i "keybinding" | wc -l
```

To count the number of occurrences

Other words starting with “key”
-------------------------------

Looking at [this page](http://www.sightwordsgame.com/spelling/compound-words/#K), there
is one open compound word that starts with “key”:

```
key pal
```

There are four closed words that start with “key”:

```
keyboard
keyhole
keynote
keystone
```

Searching my Stardict dictionaries:

``` shell
sdcv "key*"
```

These are the open compound words:

```
key distribution center (KDC)
key ring
key signature
```

And these are the closed compound words:

```
keybled
keyboard
keyboarder
keyhole
keylaunch
keylookup
keynote
keypad
keystone
keystroke
```

**Comment by bmag** [comment]
We probably should follow what Emacs itself uses, and that seems to be "key bindings" (separated). for example https://www.gnu.org/software/emacs/manual/html_node/emacs/Key-Bindings.html. That's also less work :smile:

**Comment by thornjad** [comment]
Has the documentation been standardized to this, or are there changes to be made?

**Comment by JAremko** [comment]
@d12frosted  «key⩷bindings»

**Comment by JAremko** [comment]
@d12frosted  Done. Now bot will take care of this.  :+1:

**Comment by d12frosted** [comment]
@JAremko ❤️

**Comment by d12frosted** [comment]
@JAremko ❤️
