### ISSUE TITLE
cannot preview latex formula in org file

### ISSUE THREAD

**Issue by csfreebird** [syl20bnr/spacemacs#7913]
when typing C-c C-x C-l on latex formula, got following error:

> Creating image...
> org-create-formula--latex-header: Symbol’s function definition is void: org-export-get-backend

**Comment by chewzerita** [comment]
Do you have texlive (or other latex package(s)) installed on your system? I know at least for Arch Linux the meta-package `texlive-most`.

**Comment by csfreebird** [comment]
@chewzerita yes, I have texlive-most in my Arch Linux.

**Comment by politza** [comment]
Try `(require 'ox)`.

**Comment by csfreebird** [comment]
@politza thanks, it works.
