### ISSUE TITLE
Add `go-playground` package to `+lang/go` layer

### ISSUE THREAD

**Issue by grafov** [syl20bnr/spacemacs#7914]
I propose add a helper package for golang local playground. go-mode has abilities for interacting with play.golang.org but in my opinion Emacs is much better for code experiments than web editor. So I created a mode that based on `go-mode` and `compile` mode and allows you create and maintain local library of the code snippets: https://github.com/grafov/go-playground. There is even more simple solution https://github.com/shosti/go-scratch.el but I think `go-playground` more easily integrated with external utilities because it saves the code to files. If you interesting I will create a pull request for adding `go-playground` to Go layer.

**Comment by bmag** [comment]
Looks good, PR welcome :smile:
