### ISSUE TITLE
Minor UI bugs in MacBook Pro with retina display

### ISSUE THREAD

**Issue by lijingjiang** [syl20bnr/spacemacs#7917]
Hey guys. I also have some issues about the UI. I have two Macs. One of them is old with non-retina screen, the other one is relatively new with retina display. 

However, I have experienced some display issues in my retina mac. For example, the `flycheck` mode, when I put my cursor at the error position, the prompt window looks like this. Firstly it is not in the correct position, then the window is very small.

<img width="1367" alt="4" src="https://cloud.githubusercontent.com/assets/8180212/20914064/5974c996-bb42-11e6-9cc9-81b7d59df822.png">

But in my old Mac, everything works normally just like the screen capture in `readme`

![3](https://cloud.githubusercontent.com/assets/8180212/20914071/6d83c70c-bb42-11e6-9882-b38839bb4bc6.png)

Also, for the `neotree`, in my old Mac, it looks like this

![screen shot 2016-12-05 at 10 54 46 pm](https://cloud.githubusercontent.com/assets/8180212/20914083/849377b2-bb42-11e6-9f3b-fd4eb695876c.png)

However, in my new Mac, the cursor is hollow when I placed it on the folder symbol

<img width="580" alt="hehe" src="https://cloud.githubusercontent.com/assets/8180212/20914131/ea61e984-bb42-11e6-9975-3f1c9439c8f7.png">

Both my old Mac and new Mac are running the OSX 10.12 system.

And the `power line` in the following picture looks pretty good, can the contributor share the configuration for this. In my retina display, if I am using the default `power-line` theme, it looks serrated.

![pretty](https://cloud.githubusercontent.com/assets/8180212/20914174/52a98b6e-bb43-11e6-981e-1241d2be4b44.png)

Thank you very much.

**Comment by kccai** [comment]
I see you are still using a very old repo version of Spacemacs. Why not give the new versions a try?

**Comment by CarlQLange** [comment]
Ah, cool! I hadn't thought of what might cause that first issue, with the tooltips.

What version of emacs are you using? Did you install it with brew? I no longer see the tooltips issue, having installed emacs with:

    brew install --HEAD emacs --srgb --use-git-head --with-cocoa --with-gnutls --with-rsvg --with-imagemagick --with-spacemacs-icon

Unfortunately I can't help more than that, I can't remember when I last saw it or how I'd previously installed emacs.

The spaceline separators are listed here: https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#powerline-separators

I think the one you're looking for is 'contour', so in your .spacemacs config function, add the line

      (setq powerline-default-separator 'contour)

**Comment by lijingjiang** [comment]
Hi @CarlQLange,

Thank you for your reply. My Emacs was installed using the same way instructed by `readme` The version of Emacs in both machines are 25.1.1. 

```
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus
$ brew linkapps emacs-plus
```

I have tried your suggested way to install the Emacs, but seems like it may have some compatibility issue with `spacemacs`. I even cannot start it.

![image](https://cloud.githubusercontent.com/assets/8180212/20931011/440f25c6-bb95-11e6-8b4f-9239f39c363b.png)

The error message is:

`Symbol's value as variable is void: default major mode`.

And, yes, the `contour` separator is what I am looking for. But my question is, how to config it to make it looks more smooth. Currently it looks like this (on my retina-mac)

![image](https://cloud.githubusercontent.com/assets/8180212/20931318/51a5e87c-bb96-11e6-8e12-1589ae572152.png)

My configuration for `powerline` is default, the scale is 1.1

```
   dotspacemacs-default-font '("Fira Code"
                               :size 15
                               :weight normal
                               :width normal
                               :powerline-scale 1.1)
```

Thank you for your help!

**Comment by CarlQLange** [comment]
So the powerline thing, there's a longstanding issue with Emacs on Mac OS X and colour spaces. You can read about it here: https://github.com/milkypostman/powerline/issues/54 and here: https://github.com/syl20bnr/spacemacs/issues/4955

In short, you can add this to your user-config in .spacemacs and it'll workaround the issue

      (setq ns-use-srgb-colorspace nil)

Unfortunately, it breaks the overall colour space, so it kind of depends on whether you prefer a baby or a clean bathtub. :)

Personally I set my separator to

      (setq powerline-default-separator 'utf-8)

and just deal with the kind of ugly arrow separators :)

------

The issue you're facing with the install not working looks like you need to delete the elpa directory in ~/.emacs.d and let it redownload the packages, but no promises :)

**Comment by lijingjiang** [comment]
@CarlQLange 

Thank you for the update! The setting `(setq powerline-default-separator 'utf-8)` looks pretty nice! Highly recommend every Mac user (with retina display specifically) try it :)

Also I have removed the `elpa` and reinstalled the `Emacs` using your instruction, but still have the same error. 

FYI the newly installed version is `26`, but when I using `brew install emacs-plus` for installation, the corresponding version is `25.1.1`

Anyway, thank you very much!

**Comment by shishirsharma** [comment]
Bump! Any solutions for this with latest version ?

**Comment by anuragm** [comment]
The power line color issue has been resolved recently by a [commit it made here](https://github.com/milkypostman/powerline/commit/8a246902e86a0c59015bb897a9c59be9729ef5c4). You need to set `powerline-image-apple-rgb` to `t` in order to enable the workaround.

If someone has a newer Macbook with DCI-P3 color space, I will appreciate if you let me know that the workaround is working for you or not.

**Comment by CarlQLange** [comment]
I've also added a PR changing the docs to this fix: https://github.com/syl20bnr/spacemacs/pull/9550
