### ISSUE TITLE
Font Issues

### ISSUE THREAD

**Issue by Vm900** [syl20bnr/spacemacs#7919]
Hi folks,
I've just installed installed spacemacs on my windows 10 system and everytime i launch it
i'm getting the following error message:
Cannot find any of the specified fonts (SOURCE CODE PRO)! Font settings may not be correct

How do i work around this problem?
Thanks in advance

**Comment by kccai** [comment]
The source code pro font can be found at the repo: https://github.com/adobe-fonts/source-code-pro 

You can download the font from this link: https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it .

For font installation on windows, please refer to this link: https://www.microsoft.com/en-us/Typography/TrueTypeInstall.aspx

**Comment by Vm900** [comment]
Already tried the release binaries but windows 10 wont accept them as genuine fonts.Thanks anyway

**Comment by tmaetzold** [comment]
[This link](https://fonts.google.com/specimen/Source+Code+Pro) worked to clear this error for me.

**Comment by adeltby** [comment]
On MacOS after installing the font from google fonts you have to run :

`cp SourceCodePro-VariableFont_wght.ttf ~/Library/Fonts`

**Comment by lebensterben** [comment]
locking this topic now.

refer the README at root of the repository for installation institutes of source code pro font.
