### ISSUE TITLE
Bug in helm-show-kill-ring

### ISSUE THREAD

**Issue by davendesai** [syl20bnr/spacemacs#792]
Upon version 0.65.0 and newer (I believe as I don't remember seeing this error before) upon SPC-r-y to view the kill-ring, I get an error reporting 'Symbol's function definition is void: js2-echo-error'.

The relevant code inside my dotspacemacs is as follows: 
```lisp
   dotspacemacs-configuration-layers '(
                                       git

                                       ;; languages
                                       javascript
                                       )
```

**Comment by syl20bnr** [comment]
I cannot reproduce it, does it happen every time ?
