### ISSUE TITLE
Auto-save filename hijacks `C-x C-s`: file contents are written to auto-save file and not to original filename

### ISSUE THREAD

**Issue by riccardomurri** [syl20bnr/spacemacs#7927]
#### Description :octocat:

Auto save file name `#file#` replaces the "real" file name in `C-x C-s` save
operations. In other words, when I press `C-x C-s` the auto-save file is updated
and the file that I had originally opened is not written to.

In the buffer that shows this behavior, I can see this from Lisp code:

* evaluating `(buffer-file-name)` returns the "wrong" (i.e., auto-save) filename
* evaluating `buffer-file-truename` returns the "right" (i.e., original) filename

I have this in my `.spacemacs.d/init.el`::

    ;; Location where to auto-save files.
    dotspacemacs-auto-save-file-location 'original

**Comment by riccardomurri** [comment]
#### Reproduction guide :beetle:

Unfortunately I cannot give steps for deterministically reproducing it. It
happens frequenty on my setup, but I could not yet find out the exact conditions
that trigger the bug.

*Observed behaviour:* :eyes: :broken_heart:

`C-x C-s` saves content to auto-save file.

*Expected behaviour:* :heart: :smile:

`C-x C-s` saves content to the file name that was originally opened.


#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(auto-completion ansible better-defaults c-c++ common-lisp emacs-lisp git github gtags html latex markdown mu4e pandoc python org shell-scripts spell-checking syntax-checking version-control yaml)
```

**Comment by riccardomurri** [comment]
Screenshot shows the wrong filename (on line 1 of Emacs' buffer list).

![spacemacs-autosave-bug](https://cloud.githubusercontent.com/assets/447228/21044428/3f7a00bc-bdfc-11e6-93c0-496ff2996cfb.png)

**Comment by wolfv6** [comment]
I am having the same problem, but it seems intermittent.
Sometimes I use 'SPC f s' (save-buffer), so it could be caused by that, but I can not reproduce it.
I have this in my defun dotspacemacs/init () (setq-default

    dotspacemacs-auto-save-file-location 'original

**Comment by wolfv6** [comment]
This issue is probably related to https://github.com/syl20bnr/spacemacs/issues/10348
