### ISSUE TITLE
Unnecessary pagination in which-key

### ISSUE THREAD

**Issue by letheed** [syl20bnr/spacemacs#7930]
#### Description :octocat:
Which-key is wasting visual space: one column is missing. Where I used to have three columns, I now have to page right to see the missing bindings. This is especially problematic since it happens after pressing the "SPC" leader key. There is clearly enough space on the screen to fit the 3rd column.

![capture du 2016-12-08 17-54-13](https://cloud.githubusercontent.com/assets/5330692/21019547/277ad71a-bd71-11e6-8805-e41ebbcd2633.png)
![capture du 2016-12-08 17-54-22](https://cloud.githubusercontent.com/assets/5330692/21019549/2a0a9902-bd71-11e6-9acf-802815638ebf.png)

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-enable-snippets-in-popup t)
 better-defaults
 (c-c   :variables c-c  -enable-clang-support t)
 colors emacs-lisp emoji git
 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell")
 markdown rust
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 shell-scripts syntax-checking version-control yaml)
```

**Comment by nixmaniack** [comment]
Is it the same case in stock emacs with `which-key`? If so you should report it upstream.

**Comment by letheed** [comment]
Here's a side by side view of stock emacs and spacemacs:

![capture du 2016-12-08 20-55-16](https://cloud.githubusercontent.com/assets/5330692/21025697/b12f8b96-bd89-11e6-91d1-6534f3ab2c3b.png)

The problem also remains with stock spacemacs, so it looks more like a configuration issue with to me.

**Comment by nixmaniack** [comment]
`which-key-max-description-length` is set to `32` in `spacemacs` while original value is `27`. This could be most possible reason. You can experiment with that. 

Also, I see we're unnecessarily using precious space in `which-key` description with `spacemacs/` prefix which wasn't the case before. So it's must be an issue in master as we have a fix for it in develop as per new `which-key` update.

**Comment by letheed** [comment]
Yeah I thought it might be due to a change in the which-key package that interacts poorly with master.
I thought I should report it since my setup is most likely pretty common (emacs in split screen (1080) in Unity). Makes for a bad user experience for newcomers.

I re-set `which-key-max-description-length` to 27 in user-config and it's good again. I'll try to remove it with a future release.
