### ISSUE TITLE
persp-mode warning when submitting via org-projectile/capture

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#7931]
#### Description :octocat:
When finishing or aborting a buffer opened with `org-projectile/capture`,
persp-mode complains that the buffer being killed is not in the current
perspective. You have to hit something to continue.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC a o p`
- Type something
- `C-c C-c`

*Observed behaviour:* :eyes: :broken_heart:
Warning from persp mode

![capture-todos org 2016-12-08 12-38-16](https://cloud.githubusercontent.com/assets/8588/21026900/7b7c56d2-bd43-11e6-8f97-a9557031cf2f.png)

*Expected behaviour:* :heart: :smile:
Buffer closes w/o warning

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 4289a49)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(better-defaults spacemacs-layouts helm emacs-lisp markdown
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 (auto-completion :variables auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup nil auto-completion-private-snippets-directory
                                  (expand-file-name "snippets" dotspacemacs-directory))
                 erlang elixir git dash html clojure
                 (org :variables org-enable-github-support t org-enable-reveal-js-support t)
                 colors osx github javascript react deft ruby
                 (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
                 (spell-checking :variables spell-checking-enable-by-default t enable-flyspell-auto-completion t)
                 ranger version-control rcirc tmux yaml docker elm restclient typescript evil-little-word auto-correct frame-geometry cleverparens-lispy flow)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

**Comment by nixmaniack** [comment]
I have added this in my dotspacemacs.

```elisp
  ;; Adding this so that capturing process is not interrupted with annoying
  ;; prompts "Kill and Close" etc.
  (setq persp-kill-foreign-buffer-action nil)
```

But I think this should be handled in better way just for this `org-capture` buffer.  `persp-kill-foreign-buffer-action` takes a function as well and based on buffer should be able to not prompt for this buffer. But I didn't get time to dive in and figure out how. You can ask upstream if needed as it's generic issue with `persp-mode`.

**Comment by bmag** [comment]
Alternative approach is to automatically add the capture buffer to the current layout (AKA perspective).

**Comment by aaronjensen** [comment]
How would one do that?

**Comment by bmag** [comment]
I'm not too sure, but it's possibly documented inside `persp-mode.el`'s code or GitHub page. It's generic enough that it can be asked upstream as well.

**Comment by aaronjensen** [comment]
This looks related: https://github.com/Bad-ptr/persp-mode.el/issues/34

**Comment by aaronjensen** [comment]
@bad-ptr do you have a suggestion on this one?

**Comment by Bad-ptr** [comment]
> This looks related: https://github.com/Bad-ptr/persp-mode.el/issues/34

Also see this: https://github.com/Bad-ptr/persp-mode.el/issues/27
https://github.com/Bad-ptr/persp-mode.el/commit/138a3099827785f5fa22127afdc1561f8524d6b9
(The `persp-add-buffer-on-after-change-major-mode` variable)

> do you have a suggestion on this one?

I think that @nixmaniack and @bmag are correct. You can set the `persp-kill-foreign-buffer-action` to `nil` or customize the `persp-add-buffer-on-after-change-major-mode`(setting it to `t` or `free`).

**Comment by aaronjensen** [comment]
Great, thanks. `persp-add-buffer-on-after-change-major-mode` to `free` seems to be exactly what I want. I wonder if we should make that the spacemacs default?

**Comment by aaronjensen** [comment]
Actually, scratch that. Setting `persp-add-buffer-on-after-change-major-mode` to `free` breaks all sorts of magit behavior. I'm just going to set `persp-kill-foreign-buffer-action` to `nil`

**Comment by Bad-ptr** [comment]
> Setting `persp-add-buffer-on-after-change-major-mode` to free breaks all sorts of magit behavior

Can you tell us more detail? What's wrong with it?
(Also there is a `persp-add-buffer-on-after-change-major-mode-filter-functions` so you can filter out magit buffers.)

**Comment by aaronjensen** [comment]
Sure, the first time you attempt to commit it will show the diff buffer instead of the commit buffer.

If you `C-c C-c` from the commit buffer it will kill that buffer and commit, but it will not return you to the magit status buffer as it usually does.

Those are the first two things I noticed before reverting the change.

**Comment by Bad-ptr** [comment]
Ok, I think this must fix the `persp-add-buffer-on-after-change-major-mode` behaviour:
```elisp
(with-eval-after-load "persp-mode"
(defun persp-after-change-major-mode-h ()
  (let ((buf (current-buffer)))
    (persp-find-and-set-persps-for-buffer buf)
    (when persp-add-buffer-on-after-change-major-mode
      (unless (persp-buffer-filtered-out-p
               buf persp-add-buffer-on-after-change-major-mode-filter-functions)
        (let (persp-switch-to-added-buffer)
          (case persp-add-buffer-on-after-change-major-mode
            ('nil nil)
            (free (and (persp-buffer-free-p buf) (persp-add-buffer buf)))
            (t (persp-add-buffer buf)))))))))
```
Can you test it?

**Comment by aaronjensen** [comment]
@Bad-ptr that seemed to clear up those issues for me, thanks!

**Comment by Bad-ptr** [comment]
This fix(slightly modified, but must work the same way) is in the persp-mode now https://github.com/Bad-ptr/persp-mode.el/commit/28eaf5e56e18be4bab1639ce2c31b64bd2828746

**Comment by aaronjensen** [comment]
@Bad-ptr thank you, that worked.

Ok, @bmag what do you think about setting `persp-add-buffer-on-after-change-major-mode` to `free` by default?

**Comment by bmag** [comment]
> what do you think about setting persp-add-buffer-on-after-change-major-mode to free by default?

Could work :+1:  I'm a bit concerned about how the behavior of generic buffers like `*Help*` will change. Viewing the help buffer in one layout will mean it now belongs to that layout, but what will happen when I later view the help buffer (after its contents have changed) in a different layout? I can't think of anything bad that could really happen here, so I don't think there's really a problem, but we should keep that in mind when we merge it.

**Comment by bmag** [comment]
@aaronjensen So we will have trouble (annoying prompt) when killing a generic buffer that was already added to another layout, but we won't get a prompt if the generic buffer is buried (which is what `q` does). The `*Help*` isn't killed, it's buried, so no problem here. I believe that's the usual case with generic buffers, so we can go with `free` :smile:

**Comment by aaronjensen** [comment]
@bmag #7998

**Comment by Bad-ptr** [comment]
Just remind you about [`persp-add-buffer-on-after-change-major-mode-filter-functions`](https://github.com/syl20bnr/spacemacs/issues/7931#issuecomment-266951864):
```elisp
(push
 #'(lambda (b)
     (string= "*Help*" (buffer-name b))
     ;; or (eq 'help-mode (buffer-local-value b 'major-mode))
     )
 persp-add-buffer-on-after-change-major-mode-filter-functions)
```

**Comment by aaronjensen** [comment]
Thanks @Bad-ptr, I'll see if they're interested in filtering any out.

**Comment by bmag** [comment]
@Bad-ptr thanks for the reminder. @aaronjensen we can use `persp-add-buffer-on-after-change-major-mode-filter-functions` if any problems arise, but I think we won't need it initially.

**Comment by aaronjensen** [comment]
@Bad-ptr This bug seems to be back, though with regular org captures now (no org-projectile).

If I capture from PerspA, then `C-c C-k` to abort the capture, switch to PerspB and open a new capture, that capture will be added only to PerspA, so when I `C-c C-k` that one I get the warning.

**Comment by aaronjensen** [comment]
I'm using this for now which seems to work well:

```elisp
  (push
   #'(lambda (b) (buffer-local-value 'org-capture-mode b))
   persp-add-buffer-on-after-change-major-mode-filter-functions)
```

**Comment by Bad-ptr** [comment]
> If I capture from PerspA, then C-c C-k to abort the capture, switch to PerspB and open a new capture, that capture will be added only to PerspA, so when I C-c C-k that one I get the warning.

Ok. Then maybe the `(setq persp-kill-foreign-buffer-action nil)` is the solution. Or do you have any ideas?)

Well actually I have one: I can make the `perps-kill-foreign-buffer-action` to be a list of functions, kill buffer if any return non nil. This will allow more flexible customization.

**Comment by aaronjensen** [comment]
Even with `persp-kill-foreign-buffer-behaviour nil` I get a warning about removing the capture buffer from all perspectives.

Maybe we can back up a bit.

The original problem is that org projectile capture buffers get the kill foreign buffer warning without any of spacemacs defaults overridden, so `persp-add-buffer-on-after-change-major-mode` is `nil`

I don't fully understand why that is. The value of `persp-buffer-in-persps` is set to the current persp, but I get the warning when I try to kill it any way, possibly because `(persp-contain-buffer-p (current-buffer) (get-current-persp))` is nil. What exactly is `persp-buffer-in-persps`? How do I tell what persps actually have a buffer?

To work around this, I set `persp-add-buffer-on-after-change-major-mode 'free`. So now all buffers get added to the current perspective when they come to be. This seems to mostly work, but there were some issues at some point so I added `persp-kill-foreign-indirect-buffer-behaviour-override 'as-base-buffer`. Then it worked until org capture, which has an intermediate buffer named `*Org Select*` where you can select a capture template. For some reason, even though each org capture buffer seems to be a new buffer, it still gets added to the very first perspective you did an org capture in rather than the current perspective.

The work around for that was to just filter them out of the on after change major mode. But what is confusing to me, is how is that different from `persp-add-buffer-on-after-change-major-mode nil` which led to my first issue? I seem to have come full circle, but without the original problem. What am I missing here?

I wonder if the ideal situation is that for certain buffers (a configurable filter list probably) they are never added to any persp and/or they can freely be killed. Things like org capture, the org select buffer, org agenda, compose message, help, etc. Basically, anything that can be brought in and killed that isn't actually specific to the project the persp is representing. This suggestion may not actually make sense though, there are a lot of moving parts that I do not understand at all when it comes to what buffers are in what persp, what that means exactly, etc.

**Comment by Bad-ptr** [comment]
> The original problem is that org projectile capture buffers get the kill foreign buffer warning without any of spacemacs defaults overridden, so persp-add-buffer-on-after-change-major-mode is nil
> I don't fully understand why that is. The value of persp-buffer-in-persps is set to the current persp

Each perspective has a list of buffers(list that store pointers to buffer objects). Initially there were no `persp-buffer-in-persps` buffer-local variable. This var is needed mostly for optimization purposes, for example when you want to see if a buffer is `free` you only need to check if the `persp-buffer-in-persps` is `nil`, rather than loop through buffer lists of all perspectives, etc.
All buffer owners must be in the `persp-buffer-in-persps` list of the buffer, and reference to the buffer object of that buffer must be in the buffer list of all owners. These two facts must be in sync.
Now here comes an indirect buffer and breaks this contract, because the indirect buffer is represented by an unique buffer object(like any other buffer) and therefore it is not in the buffer list of any perspective yet, but it inherits all buffer-local variables of the base buffer(including the `persp-buffer-in-persps`).

> Then it worked until org capture, which has an intermediate buffer named *Org Select* where you can select a capture template. 
For some reason, even though each org capture buffer seems to be a new buffer, it still gets added to the very first perspective you did an org capture in rather than the current perspective.

Form this description It looks like the org capture buffer is not a new buffer on every invocation.

**Comment by aaronjensen** [comment]
> From this description It looks like the org capture buffer is not a new buffer on every invocation.

This is possibly the case, though I do not see it in the buffer list when it is not visible. Is that possible? It appears to be a Fundamental Mode buffer called `*Org Select*`. 

I should probably filter `*Org Select*` out as well from the after-change-major-mode. Though...


> Now here comes an indirect buffer and breaks this contract, because the indirect buffer is represented by an unique buffer object(like any other buffer) and therefore it is not in the buffer list of any perspective yet, but it inherits all buffer-local variables of the base buffer(including the persp-buffer-in-persps).

I see, this helps me understand, thank you. It seems as if persp-mode should handle this then out of the box, either by verifying the optimization variable or by detecting the creation of indirect buffers and being sure to add them to the persp (or clear their `persp-buffer-in-persps`. In other words, we probably shouldn't have to change any settings for this behavior to work.

If this were the case, I wouldn't necessarily need to set `persp-add-buffer-on-after-change-major-mode` to `free`, things would work naturally with indirect buffers, yeah?

**Comment by Bad-ptr** [comment]
> It seems as if persp-mode should handle this then out of the box, either by verifying the optimization variable or by detecting the creation of indirect buffers and being sure to add them to the persp

The problem is if we want to get all indirect buffers of the given buffer we need to loop through all buffers. I'm afraid that this will slow down emacs.
Here is my attempt which you can test:
[develop branch](https://github.com/Bad-ptr/persp-mode.el/tree/develop) Just fixing `persp-find-and-set-persps-for-buffer`, now it will add indirect buffer to perspective of the base buffer in `after-change-major-mode-hook`.
+
[buffer-props-hash branch](https://github.com/Bad-ptr/persp-mode.el/tree/buffer-props-hash) If we can not trust buffer-local variables then we can use hash table to map buffer to owners list (but this may increase memory consumption I guess). 

> This is possibly the case, though I do not see it in the buffer list when it is not visible. Is that possible? It appears to be a Fundamental Mode buffer called *Org Select*.

Ok, I will look at it..

**Comment by aaronjensen** [comment]
`buffer-props-hash` worked for me with default settings in all the scenarios listed in this bug as far as I can tell.

The only problem was that I got this on trying to exit emacs:

```
[persp-mode] Error: Can not autosave perspectives -- (error Selecting deleted buffer)
persp-mode can not save perspectives, do you want to exit anyway? (y or n) n
```

**Comment by Bad-ptr** [comment]
I forget to mention, that you must restart emacs (It seems to me that spacemacs has a special command to reload everything after package upgrade).
You can eval this code to get rid of this error: `(setq persp-buffer-props-hash (make-hash-table :test #'eq :size 10))`. (or you can answer yes and then restore perspectives from backup)

**Comment by Bad-ptr** [comment]
> worked for me with default settings in all the scenarios listed in this bug as far as I can tell.

I think it worked because it is not working at all until you restart emacs.)
Or you can eval this code:
```elisp
(setq persp-buffer-props-hash (make-hash-table :test #'eq :size 10))
(mapc #'persp-find-and-set-persps-for-buffer (buffer-list))
```

**Comment by aaronjensen** [comment]
I had restarted emacs entirely.

After restarting emacs once again w/ the new code in place I no longer get the warning on quit.



> I think it worked for all scenarios because it is not working at all until you restart emacs.

Is there something you would expect not to work? So far things are looking good.

**Comment by Bad-ptr** [comment]
> Is there something you would expect not to work? 

The case with the `*Org Select*`. But if it works for you -- then this is great).

**Comment by aaronjensen** [comment]
Well, I have `(setq persp-add-buffer-on-after-change-major-mode nil)` (well, i'm not setting it at all, so it's defaulting. This means, I believe, that they stay persp free. Is there a function to list a buffer's current perps?

**Comment by Bad-ptr** [comment]
Something like:
`(message "%s" (mapcar #'persp-name (persp--buffer-in-persps (current-buffer))))`
or:
`(mapc #'(lambda (b) (message "%s : %s" b (mapcar #'persp-name (persp--buffer-in-persps b)))) (buffer-list))`

**Comment by aaronjensen** [comment]
Looks as if no buffers are getting added to any persps for me according to those. Should they get added by default w/o `persp-add-buffer-on-after-change-major-mode`?

**Comment by Bad-ptr** [comment]
> Should they get added by default w/o persp-add-buffer-on-after-change-major-mode

Yes, they should.
I made mistake in `persp--buffer-in-persps-set`. It must be:
```elisp
(defun persp--buffer-in-persps-set (buf persps)
  (let* ((buf-props (gethash
                     buf persp-buffer-props-hash))
         (oldcons (assq 'persp-buffer-in-persps
                        buf-props)))
    (if oldcons
        (setf (cdr oldcons) persps)
      (setq oldcons (cons 'persp-buffer-in-persps persps))
      (push oldcons buf-props)
      (puthash buf buf-props persp-buffer-props-hash))))
```

**Comment by aaronjensen** [comment]
Ok, that fixed assigning persps from what I can tell. Everything else still seems to work fine still. Capture buffers have no persp assigned to them when they're created.

**Comment by Bad-ptr** [comment]
I have merged these changes to master.

**Comment by aaronjensen** [comment]
This is great. I've been able to remove this from my config, so I think I can close this issue and the associated pull request:

```
(setq persp-add-buffer-on-after-change-major-mode 'free)
(setq persp-kill-foreign-indirect-buffer-behaviour-override 'as-base-buffer)
```

Thank you @Bad-ptr !
