### ISSUE TITLE
.dir-locals.el ipython can not work well

### ISSUE THREAD

**Issue by hujianxin** [syl20bnr/spacemacs#7934]
#### Description :octocat:
Specific ipython pointed at `.dir-locals.el` file works not well. There is a bit plank after prompt.

#### Reproduction guide :beetle:
- Start Emacs
- New python project
- Touch a `.dir-locals.el` file and add something blow into it.
```
((python-mode
  (python-shell-interpreter . "ipython")
  (python-shell-virtualenv-root . "env")
  (flycheck-python-flake8-executable . "env/bin/flake8")))
```
- `, '` to start a ipython shell.

*Observed behaviour:* :eyes: :broken_heart:
```
In [1]:         import requests
In [1]: import requests
```
After the first In [1], before `import requests`, there is a bit plank which I can not remove.

*Expected behaviour:* :heart: :smile:
```
In [1]: import requests
In [1]: import requests
```
The text after In[x] can align well.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.90.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 20741006)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy
 (auto-completion :variables auto-completion-enable-snippets-in-popup t)
 better-defaults git version-control
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 ibuffer spell-checking syntax-checking
 (semantic :disabled-for emacs-lisp)
 org markdown html emacs-lisp javascript
 (c-c   :variables c-c  -enable-clang-support t)
 (ess :variables ess-enable-smart-equals nil ess-enable-smartparens t)
 (python :variables python-test-runner
         '(pytest nose))
 (scala :variables scala-auto-insert-asterisk-in-comments t)
 (clojure :variables clojure-enable-fancify-symbols t)
 sql shell-scripts yaml ranger imenu-list evil-cleverparens evil-snipe colors deft cscope gtags restclient all-the-icons)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by hujianxin** [comment]
If I use pyenv, all things are ok!

**Comment by hujianxin** [comment]
Because my poor English, I recordered a gif to describe this problem.

https://asciinema.org/a/55e8m1xf7bb5emdm0ay6mx0es

**Comment by d12frosted** [comment]
Hey, I am not sure, but I think that `python-shell-virtualenv-root` and `flycheck-python-flake8-executable` should be absolute file paths instead of relative to... whatever dir you run `emacs -nw` in 😸

**Comment by hujianxin** [comment]
@d12frosted Thanks for your rely, the same thing happens when I change to absolute file paths. And the result is the same when I change to UI Emacs.

**Comment by hujianxin** [comment]
IPython version: 5.1.0

**Comment by hujianxin** [comment]
@d12frosted Indeed, I ran `emacs -nw` in the project dir. If I ran it someplace else, Emacs won't find flake8 and python interpreter.

**Comment by d12frosted** [comment]
Ok that was just a suggestion. Since I do no python coding, it was a blind one 😸 

cc @TheBB @cpaulik 
I know you guys use Python 😸 Probably you can help here.

**Comment by pwalsh** [comment]
You need to add `--simple-prompt --pprint` args to the ipython interpreter call (`python-shell-interpreter-args`).

See https://emacs.stackexchange.com/questions/24750/emacs-freezes-with-ipython-5-0-0
