### ISSUE TITLE
How do I call spacemacs/custom-perspective-* from .spacemacs?

### ISSUE THREAD

**Issue by systemovich** [syl20bnr/spacemacs#7935]
I want to load layouts on start-up, instead of autoresuming layouts, because autoresuming does not play well with `@ERC`. When autoresuming, all the `@ERC` buffers are gone.

When calling `spacemacs/custom-perspective-@ERC` interactively or from `*scratch*` it works, but it does not from `dotspacemacs/user-config` in **.spacemacs**.

**Comment by bmag** [comment]
That's probably because `persp-mode` wasn't activated yet. Putting this in `user-config` worked for me:
```elisp
(add-hook 'persp-mode-hook #'spacemacs/custom-perspective-@Org)
```

**Comment by systemovich** [comment]
@bmag, thanks! It works for me too.

**Comment by usharf** [comment]
How would you cleanup existing `auto-persp` errors such as this one, on startup...

```
Can not autoresume perspectives -- (error Buffer is not associated with any file 
```
