### ISSUE TITLE
spacemacs not showing correctly

### ISSUE THREAD

**Issue by nanounanue** [syl20bnr/spacemacs#7938]
I just reinstalled my computer today nad when I fired up spacemacs, the following is happening:

![captura de pantalla de 2016-12-10 14-09-01](https://cloud.githubusercontent.com/assets/494528/21075857/55dd82c0-bee2-11e6-9dda-0095a520cfbb.png)

Whay should I do?

*NOTE*: I already installed the `Source Pro` fonts

**Comment by bmag** [comment]
I'm sure I've seen an issue like this in the past (with a similar picture), and IIRC it was a font issue. Can you try and find it in the issue-tracker?

**Comment by deb0ch** [comment]
Yup, it looks like a font issue. When I had a font issue with source code pro it looked *exactly* the same.

How have you setup your font ? Do these issues look pertinent to you ? 

https://github.com/adobe-fonts/source-code-pro/issues/17
https://github.com/syl20bnr/spacemacs/issues/7696

What kind of system are you on ?

Have you tested your font somewhere else, like in a terminal ? How ?

**Comment by nanounanue** [comment]
Hi

The problem (as you properly told) is the fonts

I followed the instructions given [here](https://github.com/adobe-fonts/source-code-pro/issues/17#issuecomment-8967116) by @foozlevazquez 

```
[ -d /usr/share/fonts/opentype ] || sudo mkdir /usr/share/fonts/opentype
sudo git clone https://github.com/adobe-fonts/source-code-pro.git /usr/share/fonts/opentype/scp
sudo fc-cache -f -v
```

But doing this installed the `SourcePro` wrongly, the steps that corrected this were:

1. Download the fonts from [here](https://github.com/adobe-fonts/source-code-pro/releases/latest)
2. Extract them to the `~/.fonts` directory
3. Run `sudo fc-cache -f -v`

And everything works now :)

Thanks for your help

**Comment by deb0ch** [comment]
Glad we could help ! :smiley_cat:
