### ISSUE TITLE
Dot eslintrc did not work in react-mode

### ISSUE THREAD

**Issue by JamesYuan** [syl20bnr/spacemacs#7942]
#### Description :octocat:
Dot eslintrc did not work in react-mode.

#### Reproduction guide :beetle:
- Start Emacs
- Enter a ReactJS project with a .eslintrc under the project root
- Open a js file with react-mode enabled
- Input some codes

- .eslintrc
```
{
  "parser": "babel-eslint",
  "extends": [
    "airbnb"
  ],
  "plugins": [
    "babel",
    "react",
    "promise"
  ],
  "env": {
    "browser" : true
  },
  "globals": {
    "__DEV__"      : false,
    "__TEST__"     : false,
    "__PROD__"     : false,
    "__COVERAGE__" : false
  },
  "rules": {
    "key-spacing"          : 0,
    "jsx-quotes"           : [2, "prefer-single"],
    "max-len"              : [2, 120, 2],
    "object-curly-spacing" : [2, "always"],
    "indent"               : ["error", 2]
  }
}
```

Refer to http://eslint.org/docs/rules/indent.html .

*Observed behaviour:* :eyes: :broken_heart:
The new line always is intented with 4 spaces.

*Expected behaviour:* :heart: :smile:
The new line should be intented with 2 spaces as the .eslintrc.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(helm ansible auto-completion better-defaults colors common-lisp emacs-lisp docker ibuffer git go html javascript markdown org osx
      (python :variables python-fill-column 99)
      react restclient ruby ruby-on-rails scheme
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      shell-scripts sql syntax-checking vagrant version-control yaml)
```
- System configuration features: NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS

#### Backtrace :paw_prints:
```
```

**Comment by bmag** [comment]
Pardon my ignorance, but isn't eslintrc only supposed to do error-checking? Looking at the layer and at the link you referred, it doesn't look like the existence of eslintrc is meant to change how Emacs indents. In fact, the documentation for the `javascript` layer suggests to set `js2-basic-offset` and `js-indent-level` for controlling the indentation. To configure them on a per-project basis, you can use directory-local variables. (see Emacs documentation)

**Comment by JamesYuan** [comment]
Thanks for replying. 

But js2-basic-offset and js-indent-level are not found in my Emacs.

1. M-x customize-variable
2. Enter js2-basic-offset

[No match]

**Comment by JamesYuan** [comment]
It seems the js2-basic-offset only works under js2-mode, not the react-mode.

**Comment by JamesYuan** [comment]
Add the following in .spacemacs, it works.

(setq-default
 ;; js2-mode
 js2-basic-offset 2
 ;; web-mode
 css-indent-offset 2
 web-mode-markup-indent-offset 2
 web-mode-css-indent-offset 2
 web-mode-code-indent-offset 2
 web-mode-attr-indent-offset 2)

https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bframeworks/react#optional-configuration
