### ISSUE TITLE
sftp upload

### ISSUE THREAD

**Issue by alexdrupal** [syl20bnr/spacemacs#7946]
Hello

Is it possible to click on folder and upload it via SFTP on remote server?
Thanks!

**Comment by alexdrupal** [comment]
Note: I don't want to actually edit files on remote server. I prefer to work locally  and only need to be able to upload selected files and folders.

**Comment by bmag** [comment]
From Dired, you can use `!` to execute an arbitrary command on the current file.
If Tramp supports it, you can probably upload the file by giving a `sftp://something` argument as the destination file of a copy command (e.g. after `C` in Dired).
I believe there isn't anything Spacemacs-specific for SFTP, unless `ranger` has something.
