### ISSUE TITLE
No binding for evil-next-visual-line in org-mode

### ISSUE THREAD

**Issue by brabalan** [syl20bnr/spacemacs#7947]
In org-mode, the binding for `evil-next-visual-line`, i.e., `g j`, is used by `org-forward-heading-same-level`, as defined here https://github.com/syl20bnr/spacemacs/blob/b7e51d70aa3fb81df2da6dc16d9652a002ba5e6b/layers/%2Bemacs/org/local/evil-org/evil-org.el#L129

Could it be possible do either change the binding for `org-forward-heading-same-level`, or define another binding for `evil-next-visual-line`?

This issue is probably related to #4905.

**Comment by d12frosted** [comment]
Do you propose a change or just wish to change some keybindings in your settings? In case it's the latter, just add following snippet to `dotspacemacs/user-config` function.

```
(evil-define-key 'normal evil-org-mode-map
  "gj" 'whatever-function-you-wish-it-to-be)
```

**Comment by brabalan** [comment]
Setting the binding by hand is what I'm currently doing. I'm asking whether `gj` should not be a canonical binding for next visual line, in every mode, including org-mode.

**Comment by Somelauw** [comment]
The convention to use gj and gk is defined ![here](
https://github.com/syl20bnr/spacemacs/blob/master/doc/CONVENTIONS.org#movement-in-normal-mode.html#key-bindings-conventions). This convention conflicts with the standard keybinding for org-next-visual-line.

> Could it be possible do either change the binding for org-forward-heading-same-level, or define another binding for evil-next-visual-line?

In Vim, the shortcuts for navigation between file-type sections and headings are "]]", "[[", "]m" and "[m". I think these keys should be overwritten as they are easy to press and do what Vim users expect them to do. If another shortcut is needed, maybe "SPC m j" and "SPC m k" should be used.

Another good choice is "zj" and "zk". In Vim these shortcuts jump to next and previous folds, which should coincide with the locations of org-mode headings, but haven't been defined yet in evil. "zh" and "zl" are currently defined for horizontal scrolling by Evil, but Spacemacs has its own scrolling mode defined under "SPC n" that can be used instead.
