### ISSUE TITLE
Critical bug in auto-completion layer's handling of multiple dirs

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#7948]
**What is supposed to happen:**

http://spacemacs.org/layers/+completion/auto-completion/README.html#snippets-directories

> You can provide additional directories by setting the variable `auto-completion-private-snippets-directory` which can take a string in case of a single path or a list of paths. If its value is nil then the path ~/.emacs.d/private/snippets is used.

**Config to reproduce bug:**

```emacs-lisp
     (auto-completion :variables
                   auto-completion-private-snippets-directory '("~/.spacemacs.d/snippets/" "~/.spacemacs.d/snippets-default/"))
```

Now try `<SPC i S w>` to write a snippet via auto-yasnippet. You will get an error about something expecting a string.

I finally tracked it down:
https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bcompletion/auto-completion/packages.el

That file is full of legacy code from before `auto-completion-private-snippets-directory` could take a list. Search for the phrase `auto-completion-private-snippets-directory` in it.

All of them will need investigation, but the main culprit is:

`aya-persist-snippets-dir` which is being set to the list. It should probably be set to the 1st/leftmost item from the list instead.

----

Edit: A temporary workaround for end-users (until it's fixed in the source) is possible by putting this in dotspacemacs/user-config:

```emacs-lisp
  (when (configuration-layer/layer-usedp 'auto-completion)
    (with-eval-after-load 'auto-yasnippet
      (setq aya-persist-snippets-dir "~/.spacemacs.d/snippets/")))
```

The package isn't loaded until you try calling one of its functions, so the above is guaranteed to run before your attempt to save a file with aya is executed.

**Comment by SteveJobzniak** [comment]
Found a nice, undocumented keybinding. Not worth opening a ticket about it. When this bug is taken care of, it's worth also updating the documentation.

https://github.com/syl20bnr/spacemacs/blob/f49792e1206895b7440e24c8193ac5af6c5548c7/layers/auto-completion/packages.el#L173

```emacs-lisp
  (global-set-key (kbd "M-/") 'hippie-expand)
  (define-key evil-insert-state-map (kbd "C-p") 'hippie-expand)
```

The Docs (under YASnippet) say:

> `M-/` Expand a snippet if text before point is a prefix of a snippet

Add this to the docs:

> `C-p` (Evil insert mode only) Expand a snippet if text before point is a prefix of a snippet

**Comment by voobscout** [comment]
the temporary workaround didn't work for me :-(
I had to disable auto-yasnippet completely, hopefully this'll get fixed soon.

**Comment by SteveJobzniak** [comment]
@voobscout I do not know what you are talking about.

The workaround still works:

Here's the value (seen via `SPC h d v`) at startup of Spacemacs:

```
aya-persist-snippets-dir’s value is ("~/.spacemacs.d/snippets/" "~/.spacemacs.d/snippets-default/")
```

Here's the value as soon as you press `SPC i S c` to create a snippet via auto-yasnippet:

```
aya-persist-snippets-dir is a variable defined in ‘auto-yasnippet.el’.
Its value is "~/.spacemacs.d/snippets/"
```

The hook does its work properly: As soon as auto-yasnippet is loaded, it corrects the path, and ensures that auto-yasnippet will work.
