### ISSUE TITLE
How to evilify a visual-mode binding?

### ISSUE THREAD

**Issue by dwang20151005** [syl20bnr/spacemacs#7951]
I've trying to evilify an emacs major mode key map in which one of the bindings
(say, "B") expects an active region to be selected. So you'd select a few lines,
type "B", and this binding would take the first and last lines as its arguments.

I think the right way to port this key map to the evil/spacemacs paradigm is to
make it so that the "B" binding is available when I transition into visual state
from this evilified state, but not when I enter visual state from any other
state. Is that right?

If so, how do I accomplish this?

I see the "evilified-state-evilify" function, but it appears to install all its
bindings into the evilified state. Is there a way to configure the existing code
to do what I want?

If not, how conceptually would I implement this behavior? I could try to write
the elisp if someone explained what it should do.

**Comment by bmag** [comment]
To bind a key in visual state, use `evil-define-key` with `visual` as the state argument. For example:
```elisp
(define-derived-mode my-mode fundamental-mode "Mine")
(evilified-state-evilify-map my-mode-map :mode my-mode)
(evil-define-key 'visual my-mode-map "x" (lambda () (interactive) (message "Hello")))
```

**Comment by dwang20151005** [comment]
Works, thanks!
