### ISSUE TITLE
haskell-stack-ghc is returning with non-zero exit code

### ISSUE THREAD

**Issue by financeCoding** [syl20bnr/spacemacs#7953]
#### Description :octocat:
haskell-stack-ghc is returning with non-zero exit code

#### Reproduction guide :beetle:
- Start Emacs
- Open directory with haskell project, also unsure if its registering as a haskell project. 

*Observed behaviour:* :eyes: :broken_heart:
minibuffer error message

```
Suspicious state from syntax checker haskell-stack-ghc: Flycheck checker haskell-stack-ghc returned non-zero exit code 1, but its output contained no errors: <command line>: cannot satisfy -package criterion
    (use -v for more information)

Try installing a more recent version of haskell-stack-ghc, and please open a bug report if the issue persists in the latest release.  Thanks!
```

*Expected behaviour:* :heart: :smile:
No errors

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(yaml helm auto-completion better-defaults emacs-lisp git markdown spell-checking syntax-checking version-control
      (haskell :variables haskell-process-type 'stack-ghci))
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
```

**Comment by financeCoding** [comment]
seems the project that was opened has some issues making it look like spacemacs was the issue. By creating a new project, I had no issues with flycheck/hlint/stack/etc..

**Comment by ukari** [comment]
I had to add that this could be fixed in an already existing stack project by run `stack build`. If there is nothing wrong with your ghc version
