### ISSUE TITLE
evil-inner-quote doesn't seem for work in the import section of Go files

### ISSUE THREAD

**Issue by theherk** [syl20bnr/spacemacs#7955]
#### Description :octocat:
In the import section of go code while using the go layer, evil-inner-double-quote doesn't work. It works elsewhere in the code just not in import, seemingly. `y i "` is the command given.

#### Reproduction guide :beetle:
- Start Emacs
- Open a go file
- Move the point between a quoted import
- Enter `y i "`
- Attempt to paste

*Observed behaviour:* :eyes: :broken_heart:
Registers do not change.

*Expected behaviour:* :heart: :smile:
Registers `"`, ` `, `0`, and `1` would be populated with the contents within the quote pair.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(csv nginx windows-scripts rust auto-completion better-defaults emacs-lisp emoji docker git go gtags html javascript markdown org plantuml python salt search-engine shell spell-checking syntax-checking terraform themes-megapack version-control xkcd yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by Miciah** [comment]
This is essentially the same issue as #7764 and was fixed by the same upstream change.
