### ISSUE TITLE
Quick start page, 404 link, spelling, fragment id issue, and generalize link text

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#7956]
On the page: http://spacemacs.org/doc/QUICK_START.html

### 2 Dotfile (.spacemacs)
The last paragraph:
> The dotfile template contain further information about how to customize Spacemacs. See the dotfile configuration section of the documentation for more details.

#### 404 Link
The link "dotfile template" opens a 404 page, because: http://spacemacs.org/core/templates/.spacemacs.template leads to a non-existent file.

#### Possible cause
If i understand it correctly then the http://spacemacs.org/doc/QUICK_START.html file is generated from the .org file: https://github.com/syl20bnr/spacemacs/blob/master/doc/QUICK_START.org

In the .org file the "dot template" link leads to the correct file:
https://github.com/syl20bnr/spacemacs/blob/master/core/templates/.spacemacs.template

When the .html page is generated, then it seems like the end of the path: `core/templates/.spacemacs.template` gets added to the end of the url: http://spacemacs.org/

#### Possible solution
Maybe the link shouldn't be auto-generated and instead hard-coded?

#### Spelling
In the first sentence of the same paragraph:
> The dotfile template contain further information about how to customize Spacemacs.

The word "contain" seems to be missing an "s", with that change, the sentence reads as:

> The dotfile template contains further information about how to customize Spacemacs.

### How-To's
> Some quick how-to's are compiled in the FAQ.org file.

#### Fragment identifier issue
The text "FAQ.org" links to: http://spacemacs.org/doc/FAQ.html#MissingReference

#### Possible cause
Maybe the fragment id `#MissingReference` gets added automatically when a link points to a removed section.

#### Possible solution
The FAQ page has 3 sections that start with "How to"
1.4 How to fix package download errors when installing Spacemacs ?
1.5 How to fix Symbol's value as variable is void errors on startup?
1.6 How to fix (wrong-type-argument arrayp nil) errors on startup?

Should the "FAQ.org" link redirect to the first one? It's id is: `how-to-fix-package-download-errors-when-installing-spacemacs-`

If it's the correct internal link, then the url becomes:
http://spacemacs.org/doc/FAQ.html#how-to-fix-package-download-errors-when-installing-spacemacs-

Or should it just link to the start of the FAQ page without a fragment id: http://spacemacs.org/doc/FAQ.html

#### Generalize link text
The link text "FAQ.org" makes sense in the .org file: https://github.com/syl20bnr/spacemacs/blob/master/doc/QUICK_START.org
because the link leads to the FAQ.org file: https://github.com/syl20bnr/spacemacs/blob/master/doc/FAQ.org

But on the .html page: http://spacemacs.org/doc/QUICK_START.html
the link leads to FAQ.html: http://spacemacs.org/doc/FAQ.html#MissingReference

#### Possible solution
If ".org" is removed then it works in both the .org and .html files.
Before:
> Some quick how-to's are compiled in the FAQ.org file.

After:
> Some quick how-to's are compiled in the FAQ file.

or maybe "file" also can be removed:
> Some quick how-to's are compiled in the FAQ.

**Comment by bmag** [comment]
I don't understand if "Fragment identifier issue" and "Generalize link text" are the same issue or two separate issues. For the rest, PR welcome (although they may already be fixed in develop or have PRs).

**Comment by duianto** [comment]
Both talk about the same item "FAQ.org" on the page, but the fragment identifier issue asks what the links target #id should be or if it should be removed, and the generalize link text suggests that the link text can be shortened by removing ".org". One can be changed without affecting the other, so they are probably two separate issues.

**Comment by bmag** [comment]
Hmm.. I haven't really touched the documentation-generating code, so I'm not sure how to solve it, sorry.

**Comment by nikolaiam** [comment]
Well spotted! #8138 fixes these together with #8146.
