### ISSUE TITLE
magit-github package avatar caching prevents Spacemacs update

### ISSUE THREAD

**Issue by koterpillar** [syl20bnr/spacemacs#7958]
#### Description :octocat:

`magit-github` package uses `url` directory under `.emacs.d` for caching avatars. This results in the Spacemacs repo not being "clean" and prevents updating.

#### Reproduction guide :beetle:
- Start Emacs
- Use `git` and `github` layers
- View some commits in a GitHub repository where authors have Gravatars
- Try updating Spacemacs (or switching to a different version)

*Observed behaviour:* :eyes: :broken_heart:

```
Your Emacs directory is not clean.
git status:
?? url/
```

*Expected behaviour:* :heart: :smile:

Spacemacs switches to the selected version.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: master (rev. 664ba6a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion helm emacs-lisp version-control
                 (git :variables git-magit-status-fullscreen t)
                 github dash syntax-checking
                 (haskell :variables haskell-completion-backend 'intero haskell-enable-hindent-style "johan-tibell")
                 html javascript python shell-scripts elm purescript yaml markdown docker puppet)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by d12frosted** [comment]
That's a bit strange, to be honest. From what I can see, `magit` uses `url-cache` package in order to cache gravatar images. And `url-cache` package stores cache inside of `url-cache-directory`, which is properly set to `"/Users/d12frosted/.emacs.d/.cache/url/cache"` for me.

What is you value of `url-configuration-directory`?

**Comment by d12frosted** [comment]
Even more, spacemacs base properly setups that value.

```
(defun spacemacs-base/init-url ()
  ;; gravatars from magit use this to store their cache
  (setq url-configuration-directory (concat spacemacs-cache-directory "url/")))
```

This line was added in 4df79581. Could you please check that you do not override ownership of `url` package? Or don't change value of `url-configuration-directory` somewhere?

**Comment by koterpillar** [comment]
I'm not seeing the issue anymore on Spacemacs 0.200.7.
