### ISSUE TITLE
Newline and move cursor, suggested functions, key bindings, questions and observations

### ISSUE THREAD

**Issue by duianto** [syl20bnr/spacemacs#7961]
### Description
There are a couple of functions that insert one or more empty lines with or without indentation, above or below the current line:
<kbd>[ SPC</kbd> (evil-unimpaired/insert-space-above COUNT)
<kbd>] SPC</kbd> (evil-unimpaired/insert-space-below COUNT)

<kbd>SPC i</kbd> (insertion)

- <kbd>j</kbd> (spacemacs/evil-insert-line-below COUNT)
- <kbd>k</kbd> (spacemacs/evil-insert-line-above COUNT)
- <kbd>J</kbd> (spacemacs/insert-line-below-no-indent COUNT)
- <kbd>K</kbd> (spacemacs/insert-line-above-no-indent COUNT)

but none of them move the cursor to the new line.

### A possible solution
I copied this function:
```
(defun spacemacs/evil-insert-line-above (count)
  "Insert one or several lines above the current point's line without changing
the current state and point position."
  (interactive "p")
  (dotimes (_ count) (save-excursion (evil-insert-newline-above))))
```
without the "save-excursion" command, resulting in these functions:
```
(defun spacemacs/newline-above-move-cursor (&optional count)
  "Insert one or more newlines above and move the cursor to the last added newline."
  (interactive "p")
  (dotimes (_ count) (evil-insert-newline-above)))

(defun spacemacs/newline-below-move-cursor (&optional count)
...
```

I'm guessing that the new functions should be added after the `spacemacs/evil-insert-line-above` and `..-below` functions in the file: `.emacs.d/layers/+distributions/spacemacs-base/funcs.el` on Line 49

### Key bindings

The key bindings should probably be added after the other insert line key bindings in the <kbd>SPC i</kbd> insertion panel, which is defined in the file: `.emacs.d/layers/+distributions/spacemacs-base/keybindings.el` on line L215:
```
;; insert stuff ---------------------------------------------------------------
(spacemacs/set-leader-keys
  "iJ" 'spacemacs/insert-line-below-no-indent
  "iK" 'spacemacs/insert-line-above-no-indent
  "ik" 'spacemacs/evil-insert-line-above
  "ij" 'spacemacs/evil-insert-line-below
  "i C-k" 'spacemacs/newline-above-move-cursor
  "i C-j" 'spacemacs/newline-below-move-cursor)
```

### Questions

1. What should the function name be?

The first attempt was: `insert-newline-and-move-above`, but "move" might be interpreted as the line moving.

Adding "cursor": `insert-newline-and-move-cursor-above` is probably less confusing, but it's to long for the <kbd>SPC i</kbd> insertion panel, the last 4 characters disappear. `insert-newline-and-move-cursor-a..`.

If "and" is removed: `insert-newline-move-cursor-above`, then it fits but it's still quite long and the direction is the last word.

The shortest name i could come up with was: `newline-above-move-cursor`, then the direction is the second word, and there's less risk of it being pushed past the right edge of a small emacs window if/when more key bindings are added.

`newline-above-and-move-cursor`, sounds better, or maybe: `newline-above-n-move-cursor`, is  enough.

2. Is there a preferred maximum length for function comments?
>  "Insert one or more newlines above and move the cursor to the last added newline."
>  "Insert one or more newlines below and move the cursor to the last added newline."

these comments are 79 characters.

3. Should the key bindings be: 

<kbd>SPC i</kbd>
- <kbd>C-j</kbd>
- <kbd>C-k</kbd>
or
- <kbd>M-j</kbd>
- <kbd>M-k</kbd>

4. Documentation

Is there any key binding documentation for the insert line keys that also need to be added? I did a quick search but couldn't find any.

### Observations
a. Group similar functions

These functions:
`(defun spacemacs/evil-insert-line-above (count)`
`(defun spacemacs/evil-insert-line-below (count)`
are located on lines: 37 and 43

but these similar functions:
`(defun spacemacs/insert-line-above-no-indent (count)`
`(defun spacemacs/insert-line-below-no-indent (count)`
are located on lines: 530 and 545, wouldn't it be better if similar functions were located next to each other?

b. Identical functions:

Both of these functions and their `..-below` counterpart are identical:
```
(defun evil-unimpaired/insert-space-above (count)
  (interactive "p")
  (dotimes (_ count) (save-excursion (evil-insert-newline-above))))

(defun spacemacs/evil-insert-line-above (count)
  "Insert one or several lines above the current point's line without changing
the current state and point position."
  (interactive "p")
  (dotimes (_ count) (save-excursion (evil-insert-newline-above))))
```
I don't know if anything can/should be done about it, but i just noticed it and if someone thinks that the knowledge is of any use, then here it is.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 6288b28)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
‘‘‘elisp
(auto-completion autohotkey emacs-lisp git helm html org)
‘‘‘
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by Somelauw** [comment]
> but none of them move the cursor to the new line.

There are also two built-in evil commands: evil-open above (bound to o) and evil-open-below (bound to O). They move the cursor to the new line and put you in insert mode. In my opinion going to insert mode makes sense, because I can't think of many useful operations that you can perform on an empty line anyway.

**Comment by duianto** [comment]
I think I'm used to that behavior from sublime text, where <kbd>C-RET</kbd> adds newlines below and <kbd>S-C-RET</kbd> above.

Now that i think of it, i should have suggested those as the key bindings, they seem to be undefined in both normal and insert state.

**Comment by stackerzzq** [comment]
@duianto I think there are so many persons who need this feature and you should turn your code to a PR.

**Comment by stackerzzq** [comment]
Why not just use this name? I need your feature. I think many persons need this too. @duianto 
`(defun spacemacs/insert-line-above-with-indent (count)
(defun spacemacs/insert-line-below-with-indent (count)`
