### ISSUE TITLE
spacemacs/toggle-truncate-lines-off enables truncation, and vice versa

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs#7962]
`(spacemacs/toggle-truncate-lines-off)` = enable truncation
`(spacemacs/toggle-truncate-lines-on)` = disable truncation

No idea why. keybindings.el looks okay:

```emacs-lisp
(spacemacs|add-toggle truncate-lines
  :status truncate-lines
  :on (toggle-truncate-lines)
  :off (toggle-truncate-lines -1)
  :documentation "Truncate long lines (no wrap)."
  :evil-leader "tl")
```

Edit: I know why... seems like it is a bug in the upstream package...

`(toggle-truncate-lines -1)` outputs the message "disabling" and enables it. And `(toggle-truncate-lines 1)` outputs the message "enabling" and disables it.

Edit 2: Here is the code from simple.el, it seems this was a built-in emacs function and that Spacemacs is possibly misusing it:

```emacs-lisp
(defun toggle-truncate-lines (&optional arg)
  "Toggle truncating of long lines for the current buffer.
When truncating is off, long lines are folded.
With prefix argument ARG, truncate long lines if ARG is positive,
otherwise fold them.  Note that in side-by-side windows, this
command has no effect if `truncate-partial-width-windows' is
non-nil."
  (interactive "P")
  (setq truncate-lines
	(if (null arg)
	    (not truncate-lines)
	  (> (prefix-numeric-value arg) 0)))
  (force-mode-line-update)
  (unless truncate-lines
    (let ((buffer (current-buffer)))
      (walk-windows (lambda (window)
		      (if (eq buffer (window-buffer window))
			  (set-window-hscroll window 0)))
		    nil t)))
  (message "Truncate long lines %s"
	   (if truncate-lines "enabled" "disabled")))
```

Edit 3: May also be a bug in my port of Emacs for Mac (the from by d12frosted). Because it seems truncation is setting a truncate-lines property and just reading it...

Edit 4: Ehh, wait... "When truncating is off, long lines are folded." - Now I see, I think I thought about this backwards. I thought truncation meant wrapping the lines (truncating them to make them shorter). But it turns out that truncating off = "Do word-wrapping to display the ENTIRE line without cutting it off at the right and showing a 'right-arrow for more' icon". God damn that's confusing. Whoever designed that function should be slapped. ;) Because "truncating" is mentally the same as wrapping (truncating a line early to wrap it). So wrapping should be truncating == on.

I will leave this ticket open to let you consider if there's something Spacemacs can do to improve this situation and fix the confusing terminology, perhaps by clearer documentation in the toggle-wrapper you've added `"Truncate long lines (no wrap)."` is not clear enough until I `wrapped` my head around this weird function. Anyway, close this ticket at will.

**Comment by SteveJobzniak** [comment]
Here's an idea for a better documentation comment, to avoid confusion:

Replace:
`"Truncate long lines (no wrap)."`

With:
`"Toggle between line wrapping or truncation (no wrap)."`

**Comment by plajjan** [comment]
I ran into the exact same mental ditch and had it all backwards. Horribly non-intuitive nomenclature in use. Some clarification to documentation here sure doesn't hurt.

**Comment by duianto** [comment]
The documentation for `SPC h SPC` (search for `trunc`) has now been updated to match ghost's suggestion.

#### Before:
`(+) Truncate Lines: Truncate long lines (no wrap). (SPC t l)`

#### After:
`(+) Truncate Lines: Toggle between line wrapping or truncation (no wrap). (SPC t l)`

But the documentation still needs to be updated for both the:
- `SPC t` (mouse over) `l -> truncate lines`
- `SPC h d k SPC t l` docstring.

Which still says:
>Toggle truncate-lines on and off.

More info in the PR: [doc] Clarify line wrapping vs truncation #12570

**Comment by smile13241324** [comment]
The PR has been merged by now, would you mind taking a look at develop @plajjan and close the issue when it is clearer now?

**Comment by plajjan** [comment]
@smile13241324 I think this looks better but I didn't open the issue so can't close.

**Comment by duianto** [comment]
The original authors account might have been deleted (from the mouse over info). This is now marked as `fixed in develop`. It will be closed when this fix is part of the next version of Spacemacs is released 
(I don't know when that is going to happen).
