### ISSUE TITLE
Freezing Spacemacs every 10 min in 2 vertical buffer view

### ISSUE THREAD

**Issue by dabro** [syl20bnr/spacemacs#7964]
#### Description :octocat:
<<Freezing Spacemacs in 2 buffer view with helm installed>>

#### Reproduction guide :beetle:
- Start Emacs
- Open `.spacemacs`
- Open another file with `:vs`
- Navigate to bottom of `.spacemacs`
- Can also cause freezeup by `SPC-SPC` or `SPC-s`

*Observed behaviour:* :eyes: :broken_heart:
<<Spacemacs becomes unresponsive.  CTR-G doesn't work to terminate activity.  CPU usage jumps.  Eventually CPU drops and SPacemacs becomes usable but slow.  Occurs regularlary, restarting Spacemacs every 10 min, unusable.>>

*Expected behaviour:* :heart: :smile:
<<Able to edit `.spacemacs` without restarting spacemacs.>>

#### System Info :computer:
- OS: darwin
- Emacs: 26.0.50.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 664ba6ab)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables :disabled-for markdown org erc)
 ispell better-defaults evil-cleverparens evil-snipe deft vim-empty-lines vinegar osx themes-megapack ...)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Debugger entered--entering a function:
* #[nil "\302	\211#\207" [vim-empty-lines-overlay p move-overlay] 4]()
  ad-Advice-vertical-motion(#<subr vertical-motion> -1)
  apply(ad-Advice-vertical-motion #<subr vertical-motion> -1)
  vertical-motion(-1)
  vline-show()
  col-highlight-highlight()
  recursive-edit()
  debug(lambda)
* company-pre-command()

```

**Comment by d12frosted** [comment]
Oh well. Sounds terrible. I wonder if it's caused by https://github.com/syl20bnr/spacemacs/commit/6288b28bb0b3120b42a9e840a0632208697fad76. Though that issue usually causes problems at startup.

**Comment by dabro** [comment]
It clearly correlates with the `'(package-selected-packages (quote (...` _very_ long string at the bottom of `.spacemacs`.  I can make Spacemacs hang every time I `G` to the bottom, even in a single buffer view.  However, it happens elsewhere too.

**Comment by CarlQLange** [comment]
does it happen if the buffer(s) are in fundamental-mode?

**Comment by jmcclell** [comment]
I just started with Spacemacs today and have experienced this exact issue with `.spacemacs` open and then opening Helm. The server just hangs for 10+ minutes and then suddenly is fine again. It's happened 3 times today. I'm on the latest OSX with the latest emacs from brew.

**Comment by CarlQLange** [comment]
I thought this was simply to do with the syntax highlighting murdering CPU for really long lines, but maybe not. @jmcclell is there a really long line (let's say >200 chars) somewhere in your `.spacemacs`?

**Comment by jmcclell** [comment]
@CarlQLange Yes, the auto-generated list of available layers/packages is a single massive line. When it first happened I thought that Helm was doing some crazy stuff behind the scenes because nothing was cached but when it happened again it seemed to coincide with me fumbling around and trying to manipulate the `.spacemacs` file while Helm was still open. In Vim it's generally no problem to `C-w k` (to move up a window) while you have something similar to Helm open, but given what I'm reading here I'm wondering if perhaps the UI thread is choking on trying to manipulate the panes (frames in emacs parlance, I believe?) with the transient one open and a giant line in the way. It's a shot in the dark, but the way it freezes *everything* really seems to indicate something on the UI thread just going bonkers.

**Comment by CarlQLange** [comment]
If you switch your `.spacemacs` buffer to `fundamental-mode` (by doing `SPC SPC fundamental-mode`, do you see the same behaviour?

Either way, that line should probably be written across multiple lines to prevent this happening

**Comment by jmcclell** [comment]
It's difficult for me to say as I haven't been able to reproduce it with any consistency. Worst kind of bug ever. I'll continue to run that command when I am editing that file and we'll see. If it happens again while it's in `fundamental-mode` I'll ping this thread.

**Comment by CarlQLange** [comment]
You could probably also have it happen by toggling between `fundamental-mode` and `emacs-lisp-mode` - every time you switch into elisp mode it might hang (the line in question might have to be on screen). At least, if this is what I think it is - just a lot of highlighting and other language-specific stuff for emacs to do. I have an extremely similar issue with a (very) long line in a python file.

**Comment by dabro** [comment]
I tried shifting to ivy per some other issue threads, and the instances of freeze dropped significantly.  Switched back to helm (new `.spacemacs` each time, patched with my `user-config`s), and am _not_ getting (or at least not consistently) the freezing anymore at the bottom of `.spacemacs`.  

However, I did get freezing consistently yesterday (after shifting back to helm), though in different places and times, when I tried to view the FAQ org-mode page (`SPC h SPC $PATH RET`).  First three times completely froze up emacs, then froze up later while viewing the page after simple `SPC f f` file open.

**Comment by CarlQLange** [comment]
Seems like this issue is beyond me :) Sorry!

**Comment by bryanbecker** [comment]
Do happen to have `vim-empty-lines` layer active?  Disabling that fixed the issue for me

**Comment by CarlQLange** [comment]
It looks like the OP does have that layer active!!

**Comment by syl20bnr** [comment]
@dabro Can  you confirm that removing `vim-empty-lines` "fixes" it ?

**Comment by vise890** [comment]
I seem to have the same issue. Disabling `vim-empty-lines` appears to solve it (although it doesn't look as pretty!! :P)
