### ISSUE TITLE
dotspacemacs-emacs-command-key not applied when reloading config

### ISSUE THREAD

**Issue by deb0ch** [syl20bnr/spacemacs#7965]
#### Description :octocat:
When reloading configuration files with `SPC f e R`, non-default
`dotspacemacs-emacs-command-key` is not taken into account.

#### Reproduction guide :beetle:
- Start Emacs with `dotspacemacs-emacs-command-key` set to ";"
- Reload your configuration: `SPC f e R`

*Observed behaviour:* :eyes: :broken_heart:
- `SPC ;` is set to `evilnc-comment-operator`

*Expected behaviour:* :heart: :smile:
- `SPC ;` should be bound to `helm-M-x`

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 6288b28)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables :disabled-for markdown org erc)
 (better-defaults :variables better-defaults-move-to-beginning-of-code-first nil better-defaults-move-to-end-of-code-first t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support nil)
 (colors :variables colors-enable-nyan-cat-progress-bar nil)
 common-lisp csv emacs-lisp
 (erc :packages
      (not erc-social-graph)
      :variables erc-server-list
      '(("jinan.parrot.biz" :ssl t :port "7000" :nick "ThomdB" :full-name "Thomas de Beauchene")))
 git github gtags helm markdown multiple-cursors org pdf-tools
 (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t)
 ranger
 (shell :variables shell-default-height 50 shell-default-position 'bottom)
 shell-scripts spacemacs-layouts
 (syntax-checking :variables syntax-checking-use-original-bitmaps nil)
 themes-megapack version-control vim-empty-lines xkcd ycmd)
```

**PS:** By the way, the integrated issue report tool is broken as well, when I validated with `, ,` to send the issue, only a fraction was sent (everything before the first occurrence of the `"` character).
But I guess this should be a separate issue :stuck_out_tongue:

**Comment by d12frosted** [comment]
> By the way, the integrated issue report tool is broken as well, when I validated with , , to send the issue, only a fraction was sent (everything before the first occurrence of the " character).
But I guess this should be a separate issue

Oh damn. Should it be escaped to make it working?

**Comment by deb0ch** [comment]
@d12frosted That's possible, I don't really know. Might be a url problem, here is the responsible piece of code:

``` elisp
(defun spacemacs//report-issue-done ()
  (interactive)
  (let ((url "http://github.com/syl20bnr/spacemacs/issues/new?body="))
    (setq url (url-encode-url (concat url (buffer-string))))
    ;; HACK: Needed because the first `#' is not encoded
    (setq url (replace-regexp-in-string "#" "%23" url))
    (browse-url url)))
```
but isn't `url-encode-url` supposed to take care of that ?

**Comment by deb0ch** [comment]
I'm opening a new issue for that one,
