### ISSUE TITLE
spacemacs/report-issue submitting truncated issues

### ISSUE THREAD

**Issue by deb0ch** [syl20bnr/spacemacs#7966]
#### Description :octocat:
`spacemacs/report-issue` submits truncated issue reports when there is an occurence of the string `";"`

#### Reproduction guide :beetle:
- Start Emacs
- Open an issue report with `SPC h I`
- Write your issue report with an occurence of the string `";"`
- Submit issue report using `, ,` in normal state.

*Observed behaviour:* :eyes: :broken_heart:
The issue report is truncated, e.g. if the full issue report was

```
Yolo blabla ";" j'aime les poules
```

only

```
Yolo blabla "
```

will be displayed.

*Expected behaviour:* :heart: :smile:
Your full issue should be displayed on github's web interface

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.5
- Spacemacs branch: develop (rev. 6288b28)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
((auto-completion :variables :disabled-for markdown org erc)
 (better-defaults :variables better-defaults-move-to-beginning-of-code-first nil better-defaults-move-to-end-of-code-first t)
 (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode c-c++-enable-clang-support nil)
 (colors :variables colors-enable-nyan-cat-progress-bar nil)
 common-lisp csv emacs-lisp
 (erc :packages
      (not erc-social-graph)
      :variables erc-server-list
      '(("jinan.parrot.biz" :ssl t :port "7000" :nick "ThomdB" :full-name "Thomas de Beauchene")))
 git github gtags helm markdown multiple-cursors org pdf-tools
 (python :variables python-enable-yapf-format-on-save t python-sort-imports-on-save t)
 ranger
 (shell :variables shell-default-height 50 shell-default-position 'bottom)
 shell-scripts spacemacs-layouts
 (syntax-checking :variables syntax-checking-use-original-bitmaps nil)
 themes-megapack version-control vim-empty-lines xkcd ycmd)
```

#### Additional notes

I tried with occurences of strings like `"yolo"` or `"y"` but it doesn't reproduce in these cases.

**Comment by deb0ch** [comment]
@d12frosted said:

> > By the way, the integrated issue report tool is broken as well, when I validated with , , to send the issue, only a fraction was sent (everything before the first occurrence of the " character).
> > But I guess this should be a separate issue

> Oh damn. Should it be escaped to make it working?

and I replied:

@d12frosted That's possible, I don't really know. Might be a url problem, here is the responsible piece of code:

``` elisp
(defun spacemacs//report-issue-done ()
  (interactive)
  (let ((url "http://github.com/syl20bnr/spacemacs/issues/new?body="))
    (setq url (url-encode-url (concat url (buffer-string))))
    ;; HACK: Needed because the first `#' is not encoded
    (setq url (replace-regexp-in-string "#" "%23" url))
    (browse-url url)))
```
but isn't `url-encode-url` supposed to take care of that ?

**Comment by d12frosted** [comment]
Yeah, ideally everything should be escaped according to [this scheme](http://www.w3schools.com/tags/ref_urlencode.asp). But honestly I don't really like that the issue reporting feature is built around doing a GET request to GitHub API with huge body in the query string. Ideally it should be POST request (where we can place anything in the body), but IIRC it requires API token from the user.

**Comment by d12frosted** [comment]
Oh forgot to tell, it's not about `"`, but about `;` - it's used as separator in query strings.

**Comment by d12frosted** [comment]
Fixed in develop with https://github.com/syl20bnr/spacemacs/commit/5dbfaf3a8d44584e25576cb99a045dd22c29ca3d

**Comment by d12frosted** [comment]
@deb0ch thanks for finding and reporting this issue 😸 could you please try on latest `develop` to see if my commit fixes it for you? I just tried different combinations and it worked well.

**Comment by deb0ch** [comment]
Sure, will keep you tuned !

**Comment by deb0ch** [comment]
Works like a charm :+1:
